= Syntax
:lang: de
// include::{includedir}/_header.adoc[]
:keywords: CMS, Webdesign, Syntax, Grundlagen
:position: 20

*CMS » Webdesign*

== Inhalt dieses Kapitels

Auf den folgenden Handbuchseiten erhältst du erste grundlegende Informationen zu Struktur, Codierung und Syntax der Inhalte deines Webshops. Du erfährst, wie die verschiedenen Elemente aufgebaut sind und wie du die Elemente verändern kannst. Die meisten Strukturen sind im Standard-Design (d.h. der Grundkonfiguration bei Start deines Webshops) in plentymarkets bereits vorhanden und konfiguriert. Die Erläuterungen dieser Seiten sollen dir helfen, diese Strukturen zu verstehen und anzupassen. Dazu sind gewisse Grundkenntnisse im Bereich Webdesign nötig. Alternativ solltest du gewünschte Anpassungen von einer Agentur vornehmen lassen.

Beachte die folgenden Erläuterungen zu den Handbuchseiten dieses Bereichs sowie die Seite <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten, Webdesign bearbeiten>>, die weitere Hinweise zur Gestaltung deines Onlineshops enthält.

Für die Bearbeitung eines Webdesigns sind erweiterte Kenntnisse in den Bereichen HTML und CSS nötig. Auf der folgenden Seite findest du Informationen über HTML und CSS zum Selbststudium: link:http://de.selfhtml.org/[selfhtml^].

== CMS-Syntax

Für die Realisierung eines Webdesigns im plentymarkets CMS ist eine eigene Skriptsprache verfügbar. Im Kapitel <<omni-channel/online-shop/webshop-einrichten/cms-syntax#, CMS-Syntax>> erhältst du eine Übersicht aller Möglichkeiten der Gestaltung. Du findest dort außerdem Erläuterungen zu den *Template-Variablen* und -*Funktionen* sowie zu *Operatoren* und *Kontrollstrukturen*.

== jQuery

jQuery ist eine umfangreiche JavaScript-Klassenbibliothek, die komfortable Funktionen zur Manipulation und Navigation deiner Website anbietet. Informationen dazu findest du auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/_cms/webdesign/syntax/jquery#, jQuery>>.
