= Werkzeuge
:lang: de
// include::{includedir}/_header.adoc[]
:position: 25

*CMS » Webdesign*

== Editor

plentymarkets enthält einen integrierten WYSIWYG-Editor. Du kannst damit Texte und z.B. Tabellen in Content-Seiten direkt bearbeiten oder Formatierungen, wie z.B. Überschriften, Nummerierungen oder Listen, anwenden. Du siehst bei diesem Editor direkt das Ergebnis. Du kannst die Inhalte auch im Quellcode bearbeiten. erfährst du mehr dazu auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-werkzeuge-editor, Editor>>.

== Syntax-Editor

Zur Bearbeitung von HTML-Inhalten, wie Artikelbeschreibungen, Templates und E-Mail-Vorlagen steht dir neben dem bekannten Editor und dem herkömmlichen *Textfeld* der neue *Syntax-Editor* zur Verfügung. Vereinfacht gesagt ist dieser die professionelle Alternative zum *Textfeld*, da der Syntax-Editor neben Syntax-Highlighting weitere Funktionen mit sich bringt, die den Komfort und die Produktivität für die Bearbeitung von HTML enorm erhöhen. Details dazu erfährst du auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-werkzeuge-syntax-editor, Syntax-Editor>>.
