= Best Practice: Correcting / Redistributing/ Deleting stock ¤:lang: en ¤:description: Find out how to completely redistribute stock of one warehouse to another one. ¤:keywords: Stocktaking, manage stock, redistribute stock, correct stock, redistribute warehouse, delete stock ¤:position: 10

With the data format *Stock* it is possible to change the stock of all variations at once. This is for example helpful, if you want to enter all current stocks into the system after a stocktaking.

Further application possibilities are the redistribution of stock to a new storage location in the same warehouse or into a new warehouse.

== Which steps are necessary in advance for redistributing and correcting stock?

* the warehouse has to be set up ¤* if you’re not only working with the standard storage location, the storage locations have to be set up

For more information about setting up warehouses and storage locations, please refer to the manual page <<stock-management/setting-up-a-warehouse#, warehouse>> and the subordinate pages. (Die Handbuchseiten sind noch nicht überarbeitet. Die grundsätzliche Vorgehensweise ist jedoch in plentymarkets 6 und 7 gleich.)

== Examples of use ¤In order to better understand the process, we will give you three concrete examples. The first example shows the necessary steps for correcting the stock. However, the stock remains in the same warehouse as before. ¤In the second example, the whole stock is redistributed into another warehouse.

The data format Stock is used for all of the above mentioned examples and the following parameters must be included:

.Storage and rounding settings ¤[cols="1,1,2"] ¤|==== ¤|Parameter |Import settings |Explanation

|VariationID ¤|Import ¤|Contains the plenty ID of a variation and thus is obligatory for the mapping of the stock.

|Stock ¤|Import ¤|Contains the stock figure and the import procedure setting Import ensures that the previous stock figure will be overwritten when importing the file. Therefore, the parameter is obligatory.

|WarehouseID ¤|Import ¤|Contains the warehouse ID and is obligatory, so the stock can be assigned to a warehouse.

|LocationID ¤|Import ¤|Contains the storage location ID and is obligatory, so the the stock can be assigned to a storage location.

|VariationString ¤|Import ¤|Contains the full name of a variation. The parameter is optional, but often helps recognising the variation

[.instruction] ¤Correcting stock

. Export the data format *Stock*. ¤. Enter the current stock into the column *Stock*. ¤. Save the file. ¤. Upload the file in plentymarkets.

[.instruction] ¤Booking whole stock in a new warehouse

In the described procedure, for a short period of time there is more stock booked in the system than there actually exists. You should especially pay attention to this when having a small stock in which the existing stock is already completely reserved and therefore there may currently be no listing active etc. Due to the additional stock, automated actions such as sending emails or starting listings could be triggered. Basically, the stock in the old warehouse can also be set to zero first, but in that case, listings or other offers that are connected with the stock automatism, may be closed.

. Export the data format Stock. ¤. Save the file twice. ¤. Open one file. ¤. Enter the ID of the new warehouse into the column *WarehouseID*. ¤. Enter the ID of the new storage location into the column *LocationID* ¤. Save the file. ¤. Upload the file in plentymarkets. ¤. Carry out exemplary tests on two or three items in the stock movements and check, whether stock was booked for the new warehouse ¤. Open the second, still un unprocessed file. ¤. In the *Stock* column, enter 0 for all stocks. ¤. Upload the file in plentymarkets. ¤. Carry out exemplary tests on two or three items in the stock movements and check, whether the stock for the old warehouse was set to zero.

== Where can I find my warehouse IDs and storage location IDs?

You will find the IDs in the menu *Settings » Stock » Warehouse* in the submenus *Settings* and *Racks*. ¤Info: The ID of the standard storage location is 0.

== Exporting and importing data

How the general procedure of importing and exporting data works is explained in the manual under <<basics/data-exchange/export-import/exporting-data#, exporting data>> and <<basics/data-exchange/export-import/importing-data#, importing data>>. ¤The other available data formats are listed <<basics/data-exchange/export-import/data-formats#, here>>. ¤