= Managing incoming items
:lang: en
include::{includedir}/_header.adoc[]
:keywords: booking stock, cancelling stock reservations, booking items, registering stock, new stock, adding stock
:position: 20

There are several ways to book stock into your system. However, to book variations in you need to have set up a complete warehouse and you need to have a warehouse, a storage location and a supplier assigned to a variation. On this page you will learn how to assign a storage location and a supplier to a variation. Furthermor you will read how to book stock in the **Stock » New incoming items** men. Your system will only be able to **<<item/managing-items#230, adjust the display of variations in your store automatically>>** as well as to start listings automatically if you book variations in and out and manage your stock correctly in plentymarkets.

[#100]
== Assigning suppliers to a variation

A supplier must be assigned to a variation before you can book incoming items and the supplier is also required to create reorders. Suppliers are customers that were assigned to the customer type supplier. So you need to create a supplier before you can assign a supplier to a variation. The steps for creating a supplier are the same as for creating other types of **<<crm/managing-customer-data#800, customers>>**. You just have to make sure that you select supplier as customer type.

[.instruction]
Assigning suppliers:

. Go to **Item » Edit item**.
. Open the item.
. Open the variation.
. Click on the **Supplier** tab.
. Select a supplier from the drop-down menu.
. Click on **Add**.  +
→ The supplier will be assigned to the variation and you can carry out further settings.

.Supplier information of a variation
[cols="a,a"]
|====
|Setting |Explanation

|**Supplier item No.**
|Enter the item number that your supplier gave the variation. You can use this number to search for incoming items.

|**Purchase price**
|Enter the purchase price of the variation. Depending on your incoming items settings the purchase price will be overwritten. You can define whether or not the purchase price that was entered during an incoming items operation will overwrite the purchase price saved for the supplier. The setting for overwritting the purchase price are defined in the **Settings » Stock » stock » incoming items** menu.

|**Minimum purchase**
|Enter the minimum quantity that you need to order from a supplier. The minimum purchase will be used for reorders. However, the minimum purchase will only be used and displayed if the variation has actually reached the reorder level and really needs to be reordered. In other words the minimum purchase will not be displayed if variations have sufficient stock.

|**Delivery time in days**
|Enter the number of days that your supplier usually needs to deliver reordered variations. The delivery time can influence the quantity suggested for an reorder and the day that an reorder will be delivered. You can define whether or not the delivery time will influence the suggested quantity. The settings are in the **Settings » Stock » Reorder management » Basic settings** menu. The delivery time is here considered replacement time.

|**Last price query**
|Select the date from the calendar when you lasted requested the current price from your supplier.

|**Discount**
|Enter the discount in percent if the supplier offers a discount on the variation. However, the discount will only be used in reorders if the check mark for discountable is placed as well.

|**Discountable**
|Place a check mark to activate the discount entered. The discount entered will not be used in reorders if this check mark is not saved.

|**Packaging unit**
|Enter the units contained. This is especially important if the units contained in the variation that the supplier offers differs from the regular number of units contained and that you saved in your variation data record. The units contained saved in the variation data record can be found in the **Settings** tab of a variation.
|====

[#200]
== Linking a variation to a storage location

A variation needs a warehouse and a storage location before you can book stock in. Without a warehouse and a storage location the system does not know where to book the stock and therefore does not book stock. The standard storage location is only a placeholder location and is used if you have not assigned an individual storage location yet. The best is to select one of your storage locations to begin with.

. Go to **Item » Edit item » Open item » Edit variation**.
. Click on the **Warehouse** tab.
. Select a warehouse from the drop-down menu.
. Click on **Add**.  +
→ The warehouse will be assigned to the variation and you can carry out further settings.

.Warehouse settings of a variation
[cols="a,a"]
|====
|Setting |Explanation

|**Storage location type**
|Select the type according to the size of the variation

|**Zone**
|Select a zone if you have set up zones for this warehouse

|**Reorder level**
|Enter the quantity at which a variation should be reordered. A suggestion for a reorder quantity will be made when this reorder level is reached. Until the level is reached 0 will be displayed as suggestion, because the reorder level defines when you wish to make a reorder.

|**Stock turnover (in days)**
|Enter the number of days that the stock of a specific variation should suffice until the next reorder. This value is relevant for calculating the reorder quantity. A standard value that could be used for the stock turnover is 14 days. Once the item has reached the reorder level, the value entered will be used for calculating the quantity of items that need to be reordered. In other words, the quantity suggested for reorder would be sufficient for the following 14 days.
If no value is entered here, the stock turnover (in days) is not taken into account for the calculation of the reorder date.

|**Maximum stock**
|Enter the maximum stock for the warehouse. The maximum stock influences the suggested reorder quantity by limiting the reorder quantity. Or in other words the reorder quantity will not exceed the quantity entered here.

|**Stock buffer**
|Enter a desired value as the stock buffer. The stock for particular markets will then be reduced by this value.  +
__Example__: You have 50 items in stock and you want a stock buffer of 10 items so that the item can not be sold out completely on this market. In this case, enter **10** as the stock buffer. Now, 40 items are in stock on this market.  +
The values entered here are considered for markets such as <<omni-channel/multi-channel/neckermann-at#, **Neckermann**>>, <<omni-channel/multi-channel/otto#, **Otto**>> and <<omni-channel/multi-channel/plus-gartenxxl#, **Plus.de**>>. The buffer entered here takes priority over the buffer values entered for the particular market.

|**Suggested storage location**
|Select a storage location for the particular warehouse. This storage location will automatically be suggested when a reorder is made. Or select the setting Default storage location if you don't want a storage location to be assigned.
|====

[#300]
== Preparing the data transfer

When you add items as incoming item, you can enter the purchase price, the recommended retail price and the storage location. The RRP will be applied to the variation data record once the incoming item data record is approved. When you add the same variation several times but with different RRPs, then the highest RRP will be saved in the variation data, once the incoming item data record is approved. You can specify if and in what way the purchase prices of incoming items are saved with the item. In addition, you can select if and how a specified storage location for incoming items is saved in the variation data.

[.instruction]
Choosing a transfer option:

. Open the menu **Settings » Stock » Stock » Incoming items**.
. Select a setting. Pay attention to the information given in table 3.
. **Save** the settings.

.Defining how prices and the storage location are transferred
[cols="a,a"]
|====
|Setting |Explanation

|**Purchase price**
|Choose whether or not the purchase price will be transferred and if you choose to transfer the purchase price, select where the price will be saved. The storage location while be saved once the incoming items data record was approved.  +
**Do not save the purchase price** = The purchase price will not be saved.  +
**Save purchase price in variation data** = The purchase price will automatically be saved in the **Settings** tab of a variation.  +
**Save purchase price in variation and supplier data** = The purchase price will automatically be saved in the **Settings** tab of a variation as well as in the **Stock** tab of a supplier.  +
**Save the average purchase price in the variation data** = The average purchase price will be recalculated every time new incoming items are received. The purchase prices of all variations currently available in the warehouse are used for this calculation. The average purchase price will automatically be saved in the **Settings** tab of a variation.  +
**Save the highest purchase price** = If several different purchase prices are available, then the highest purchase price of the current incoming items data record will be saved with the variation data.  +
**Save the lowest purchase price** = If several different purchase prices are available, then the lowest purchase price of the current incoming items data record will be saved with the variation data.

|**Storage location**
| Choose whether or not the storage location will be transferred and if you choose to transfer the purchase price, select where the price will be saved. The storage location while be saved once the incoming items data record was approved.  +
**Do not save the storage location** = The storage location will not be saved.  +
**Save storage location in variation data** = The storage location is automatically saved as suggested storage location in the **Warehouse** tab of a variation. The storage location will be newly transferred with each new incoming items data record that the variation is included in.  +
**Save the storage location for items and variations if no storage location was saved yet** = The function only takes effect if no storage location was saved yet.
|====

[#400]
== Assigning the RRP to a price

If you want to enter a RRP while booking stock in, you need to define which sales price will be used as RRP. Furthermore you can select the sales price that will be displayed when booking incoming items.

[.instruction]
Assigning the RRP to a price:

. Go to **Settings » Stock » New incoming items**.
. Select one of your sales prices from the drop-down menu for the **RRP**.
. Select one of your sales prices from the drop-down menu for the **price**.
. Save the settings.

However, it is not enough to assign a price in the **Settings » Stock » Neuer incoming items** menu in order to display a sales price in a variation. You also need to assign a sales price to a variation. Sales prices are created in the **Settings » Item » Sales prices** menu. How to create sales prices and how to assign them to variations is described in detail on the **<<item/managing-items#, Managing items>>** page of the manual. On this page you will also learn how to calculate prices for customer classes and so on.

[#500]
== Recording incoming items

The recording on incoming items is carried out in 2 steps. At first you need to enter general information such as the supplier and the currency. In the second step the variations and the delivered quantities are registered.

=== Recording general incoming items information

You need to have at least one warehouse and supplier before you can register incoming items.
Create a **<<crm/managing-customer-data#800, customer data record>>** for each supplier and select the customer type Supplier.
Furthermore, at least one user must be activated as an **<<basics/working-with-plentymarkets/manage-users#40, owner of incoming items>>**. This ensures that the incoming items can be assigned to a specific person.
It is not possible to record incoming items without an owner.
The owners are sorted by ID.
If the user who is currently logged in was also activated as an owner, then this user will be selected by default.

[.instruction]
Recording general incoming items information:

. Go to **Stock » New incoming items**.
. Click on **New incoming items**.  +
→ A new tab will open.
. Enter a **supplier**.  +
→ Click on the down arrow to see a list of all suppliers or enter a supplier's name to see matching results. The results will be displayed once 3 or more letters were entered.
. Select a warehouse.  +
→ If a main warehouse is defined for the variation, then this **<<item/managing-items#290, main warehouse>>** will be pre-selected.
. Select an owner.  +
→ If you were activated as an **<<basics/working-with-plentymarkets/manage-users#40, owner of incoming items>>**, then you will be cted by default since you are currently logged in.
. Carry out further optional settings as desired.
. Save the settings, to create an incoming items data record.  +
→ The incoming items data record will open in a new tab. It will have an ID and will be given the status **Created**. Click on the small plus on the far left side of the header to see additional information about the incoming items data record.

If you pay for the incoming items in a currency other than your **<<order-processing/payment/currencies#30, standard currency>>**, then the **<<order-processing/payment/currencies#20, exchange rate>>** will be entered automatically.

It is possible to change any of the entries that are made. Finalize the incoming items data record by adding items and procurement costs.

[#600]
=== Adding items to the incoming items data record

You can add variations individually or several at once. It is only possible to add variations that already exist as data records in your system. First create a new item and the corresponding variations, if a completely new **<<item/managing-items#, item>>** is delivered.
When you first open the list of items and variations all variations from all suppliers are listed. Use the search to display items of a particular supplier. +
If you entered a purchase price for a variation, then it will automatically be displayed here and can be used. Click on the item ID to open and edit the item data record. Proceed as described below to add the delivered items to the incoming items data record.

[#700]
==== Adding an individual variation

Add an individual variation as described below. Entries such as the purchase price and the storage location are not mandatory. If you do not want to enter these entries, then simply skip the corresponding steps in the description.

[.instruction]
Adding an individual variation:

. Go to **Stock » New incoming items**.
. Open an incoming items data record.
. Click on **Add item**.  +
→ A new window for searching and selecting items will open.
. Enter the search terms and select the filter options. Pay attention to the information given in table 4.
. Click on **Search**.  +
→ The items that correspond to the search criteria entered will be listed.
. Enter the **Purchase price** (optional).
. Enter the **quantity** (mandatory entry).  +
→ The variation is selected automatically when a quantity is entered.
. Select a **Storage location** from the drop-down menu.  +
→ If you have not yet assigned a storage location to a variation, then you can assign a storage location here as well. Click on **Search** to do so. The standard storage location is only a placeholder location and is used if you have not assigned an individual storage location yet.
. Enter the **RRP** (optional).  +
→ The RRP will be applied to the variation data record once the incoming items data record is approved.
. Click on **Add items** within the **procedure** tab.  +
→ The variation will be added to the data record.

.item filters
[cols="a,a"]
|====
|Setting |Explanation

|**Item data**
|Searches through item name 1 and the item's meta keywords.

|**Barcode**
|Filters barcodes such as EAN, UPC or ISBN depending on the barcode type that you set up.

|**Reset**
|Resets all of the filter settings so that you see items that correspond to all suppliers. After the reset, click on search to update the list.
|====

Click on **Back to incoming items** to return to the overview of incoming items data record.

[#800]
==== Adding several variations at once

If you want to add several variations at the same time, then enter the quantities and purchase prices. However, the purchase price is not a mandatory entry. You can also use the tab key to switch to the next entry field. You can only add variations that are displayed on the same page. If you switch to a new page, then your system will load the entries for the new page and discard the entries on the previous page.

[.instruction]
Adding several variations:

. Go to **Stock » New incoming items**.
. Open an incoming items data record.
. Click on **Add item**.  +
→ A new window for searching and selecting items will open.
. Enter the search terms and select the filter options. Pay attention to the information given in table 4.
. Click on **Search**.  +
→ The variations that match the search criteria will be listed.
. Enter the **Purchase price** (optional).
. Enter the **quantity** (mandatory entry).  +
→ The variation is selected automatically when a quantity is entered.
. Enter the **RRP** (optional). +
→ The RRP that you booked will be transferrd to the item data record.
. Enter the **Quantity**, the **Purchase price** and the **RRP** for any additional variations.
. Click on **Add** button that is displayed above the item list.  +
→ The variations will be added to the incoming items data record.

Click on **Back to incoming items** to return to the overview of incoming items data record.

If you add another quantity of the same variation and you do not change the purchase price or storage location, then this new quantity will simply be added to the existing quantity. If the purchase price or storage location are different, then the variation will be listed a second time.

[#900]
== Adding procurement costs

Add procurement costs, e.g. the freight, packaging and customs charges that are incurred when acquiring new items.

[.instruction]
Adding procurement costs:

. Go to **Stock » New incoming items**.
. Open an incoming items data record.
. Click on the small plus icon to expand the header.
. Click on the coins.  +
→ A window will open.
. Enter your costs.
. **Save** the settings to save costs.

[#1000]
== Changing and understanding the status

Incoming items data records receive the status **Created** as soon as they are created. Any status changes are saved in the **Status history**. Open the **Status history** by clicking on the symbol to the right of the drop-down menu. The history includes information about each status change. It lists the user, date and referrer, e.g. Client.

[.instruction]
Changing the status:

. Go to **Stock » New incoming items**.
. Open an incoming items data record.
. Select a status from the drop-down menu.  +
→ You can choose between the statuses **In review**, **Error**, **Cancelled** and **Approved**.
. **Save** the status.

.possible statuses
[cols="a,a"]
|====
|**Status** |Explanation

|**Created**
|Incoming items data records automatically receive this status when they are created.

|**In review**
|It makes sense to select this status once all of the delivered items have been recorded and the data record in plentymarkets is checked for accuracy against the delivery note.

|**Error**
|Indicates that the data record includes an error.

|**Cancelled**
|Indicates that the data record should no longer be used. It is not possible to delete incoming items data records. Therefore, it makes sense to use this status for faulty data records.

|**Approved**
|Adds the incoming items to the stock. In other words, this status makes the new incoming items available for outstanding orders, new listings, etc. The incoming items data record will be locked and can no longer be edited.

|**Correction**
|Unlocks certain entries such as the supplier, the delivery note number etc. for editing However, the purchase price remains locked and can not be edited.
|====

[#1100]
== Adding stock to a variation

Approve the incoming items data record to actually add the stock to a variation and to apply the RRP from the incoming items data record to the variation data. If there are several different RRPs for the same variation, then the highest RRP will be applied to the variation data. +
It is no longer possible to change a variation or add further variations once an incoming items data record is switched to the status **Approved**. Other data e.g. the supplier also remain locked when the incoming items data record is in **Approved** status.

You can see a variation's stock under **Tab: Stock » Tab: Stock**. The tab **Item movement** lists all of the item movements. For example, this tab shows you when the purchase price was changed in the incoming items data record. All changes to the item quantity or purchase price are recorded as item movements regardless of which status the incoming item has.

Open the menu **<<stock-management/managing-stocks#, Stock » Stocks>>** to see the stock of all items and variations.

[#1200]
== Adding a note

Use notes to save additional information. For example, to save a message for other colleagues who will also edit the data record at a later time. Notes can neither be edited nor deleted.

[.instruction]
Adding a note:

. Go to **Stock » New incoming items**.
. Open an incoming items data record.
. Click on **Notes**, i.e. the small paper icon on the far right of the header.  +
→ A window will open.
. Enter a text. +
→ Format the note as desired.
. **Save** the settings to save the note.  +
→ Previously saved notes are displayed on the left side of the window.

[#1300]
== Changing and correcting an incoming items data record

Incoming items data records can only be changed if they have a certain status. Data records can be changed if they have the status **Created**, **In review**, **Error** or **Cancelled**. Information such as the supplier, the delivery note number and the quantity can be changed. A note is automatically saved when changing sensitive data such as the purchase price or the item quantity. The user who made this change is automatically saved as the author of the note. It is not possible to change data records that have already been approved. When using the status **Correction**, some data becomes editable again.

[#1400]
== Exporting an incoming items data record

Data is exported in CSV format. Proceed as described below to export an incoming items data record.

[.instruction]
Exporting an incoming items data record:

. Go to **Stock » New incoming items**.
. Open an incoming items data record.
. Click on the small plus icon to expand the header.
. Click on **Export**. +
→ The file will be downloaded.
. Select semicolon as the separator when opening the file.

[#1500]
== Creating a PDF receipt

It is only possible to create a PDF receipt when the status **Approved** is selected.

[.instruction]
Creating a PDF receipt:

. Go to **Stock » New incoming items**.
. Open an incoming items data record.
. Click on the small plus icon to expand the header.
. Click on **Create receipt**. +
→ The PDF file will be downloaded.

[#1600]
== Searching for an incoming items data record

There are two menus where you can search for incoming items data records. These menus are **Stock » Incoming items** and **Stock » New incoming items**. In the **Stock » Incoming items** menu all incoming items data records are listed regardless of whether they were created per SOAP, dynamic import or in the **New incoming items** menu. In the **New incoming items** menu you can only find incoming items data records that were booked in this menu.

[#1700]
=== Searching in the new incoming items menu

Use the search function in the incoming items menu to find specific data records. Many of the search filters refer to items and variations. In other words, you can use the filters to search for incoming item data records that include an item or variation with this ID, number or flag. When you open the menu, the last 2 months are automatically selected as the delivery period. If you want to find an incoming items data record that is older, then you will need to reset the filters first.

[.instruction]
Searching in the new incoming items menu:

. Go to **Stock » New incoming items**.
. Select the desired search settings. Pay attention to the information given in table 6.
. Click on **Search**.

.search settings for incoming items
[cols="a,a"]
|====
|Setting |Explanation

|**Barcode**
|Searches variations that have the barcode. Barcodes can be EAN, UPC, ISBN etc.

|**Reorder ID**
|Searches for all data records that include an item from this reorder.
|====

[#1800]
=== Searching for incoming items in the **Stock » incoming items** menu

The many ways to book stock into your system are e.g. SOAP, Rest, dynamic import, the variation menu or the **Incoming items** menu. However, no matter how the stock was booked into your system all incoming items data records are listed in the **Stock » Incoming items** menu. The search is by month.

[.instruction]
Searching for an incoming items data record:

. Go to **Stock » Incoming items**.
. Select a filter. +
→ The current month is set by default.
. Click on **Search**.

[IMPORTANT]
.Identifying archive entries
====
An entry will be archived after 3 months, but only if all stock that was booked in with this entry has either been booked out or has been redistributed in the meanwhile. Once an incoming items data record has been archived you will see an archive symbol in the **Archive** column.
Archive data can neither be edited nor deleted.
====

In this menu you can also do the following:

* You can export incoming items data records by month
* You can open, edit and individually export incoming items data records

You can edit the **Supplier**, **Delivery date** and **Delivery note number** in the **Base** tab. You can edit the **Purchase price** in the **Item** tab.

