= Carrying out redistributions
:lang: en
include::{includedir}/_header.adoc[]
:description: Learn how to work with redistributions between different warehouses in your plentymarkets system.
:keywords: Redistribution, warehouse redistribution, storage location, storage locations, PO delivery note
:position: 35
:url: stock-management/working-with-redistributions

In the *Stock » Redistribution* menu, your plentymarkets system offers you the possibility to redistribute items between different warehouses. The redistribution is carried out using a particular order type.

A redistribution consists of the following steps:

* <<#600, Creating a redistribution>>
* <<#700, Adding order items>>
* <<#800, Generating a PO delivery note>>
* <<#900, Booking items out>>
* <<#1000, Booking items in>>
* <<#1100, Finishing a redistribution>>

We recommend carrying out some <<#100, preparatory settings>> before working with redistributions.

[#100]
== Preparatory settings
To optimise your workflow using warehouse redistributions, we recommend carrying out some preparatory settings. These settings are described in the following. Create new order statuses and tags that are used exclusively with redistributions and thus enable you to keep a better overview. In addition, setting up a document template for the particular document type *PO delivery note* is mandatory.

[#200]
=== Preparing order statuses for redistributions
A certain number of statuses is saved in your plentymarkets system by default. Those default order statuses can also be used for redistributions. However, it is also possible to create statuses that are exclusively used for this particular order type. Creating new order statuses is described in detail in the respective chapter on the <<orders/managing-orders#1200, Managing orders>> page of the manual.

[TIP]
.Creating own order statuses for redistributions
====
We recommend creating separate order statuses that you only use for working with redistributions. Assign particular names to the order statuses to distinguish between redistributions and other order types. This is particularly important when automating the redistribution with the help of <<#1100, event procedures>>.
====

[#300]
=== Creating tags
Tags are keywords that you create centrally before you can use them to mark data in different areas of your plentymarkets system. If you want to use tags with redistributions, you need to create those tags beforehand in the *System » System settings » Settings » Tags* menu. To do so, follow the instructions on the <<basics/working-with-plentymarkets/tags#, Managing tags>> page of the manual.

[#400]
=== Carrying out default settings
You can determine default settings to reduce the workload involved in creating a new redistribution. The default settings are then automatically displayed in the data fields when creating a new redistribution. Proceed as described below to carry out default settings.

[.instruction]
Carrying out default settings:

. Go to *System » System settings » Stock » Reorder management » Redistribution » Settings*.
. Select a *Default status* that should be preselected when creating a redistribution.
. Carry out the desired settings for the *Default owner*. Pay attention to the information provided in <<table-default-owner-redistribution>>.
. *Save* the settings. +
→ The selected default settings are displayed when creating new redistributions.

[[table-default-owner-redistribution]]
.Available settings for the default owner
[cols="1,3"]
|====
|Setting |Explanation

|*Active owner preselected*
|The user creating the redistribution in the plentymarkets back end is preselected in the *Owner* field.

|*No owner preselected*
|If you select this option, no *Owner* is preselected when creating a new redistribution.

|====

[#500]
=== Setting up a template for the PO delivery note
Working with redistributions requires using the particular document type *PO delivery note*. *PO* stands for *Purchase order*, which is a standard term within the context of reorder and stock management.
 This delivery note lists all variations included in a redistribution.  Warehouse staff and logistics partners can use this document to keep track of the variations included when booking the order items in in the receiving warehousel

[WARNING]
.Document template must be set up
====
The document template for the document *PO delivery note* has to be set up before creating such a document for the first time. As long as the document template has not been set up, no delivery note can be generated for a redistribution.
====

The following instructions describe how to transfer the default document template saved in your plentymarkets system.

[.instruction]
Setting up a template for the PO delivery note:

. Go to *System » System settings » Stock » Reorder management » Redistribution » Documents » PO delivery note*.
. Open the *transfer* tab.
. Select the language from the drop-down list above the tab title.
. In the *Apply settings from default document template* area, click on *Accept*. +
→ The default document template is applied to the document.

If you wish to make individual changes to the *PO delivery note* document, such as displaying your company logo or further information, proceed according to the instructions provided on the <<orders/order-documents#300, order documents>> page of the manual.

[#600]
== Creating a redistribution
After having carried out the preparatory settings, you can proceed with creating an order of the type redistribution.

[.instruction]
Creating a new redistribution:

. Go to *Stock » Redistribution*.
. Move the cursor over the *Plus icon* and click on *New redistribution*. +
→ The menu for creating a new redistribution opens.
. In the *Status* field, select an initial <<#200, status>> that should be assigned to the new redistribution. This status can be changed at a later point in time.
. In the *Sender* field, select the warehouse from which items should be booked out.
. In the *Receiver* field, select the warehouse into which the items should be booked.
. *_Optional:_* Select one or several *Tags* to mark the new redistribution.
. *_Optional:_* Select an *Owner*, meaning the user responsible for the redistribution.

[IMPORTANT]
.Selecting an owner
====
If the desired *Owner* is missing from the list, no users of your plentymarkets system have been activated as owners. Proceed according to the instructions on the <<basics/admin-tasks/manage-users#40, Managing user accounts>> page of the manual to activate owners. In addition, check the <<#400, default settings>> for owners described above.
====

[#700]
=== Adding order items
The next step consists of adding the items that should be redistributed from one warehouse to another. Use the *Filter* to search for the desired order items according to the available <<item/managing-items#_filtering_items, item and variation data>>.

[.instruction]
Adding order items:

. In the *Item list* area, click on *Add*. +
→ A menu for adding order items opens.
. Select one of the filters described in <<table-filter-item-search-redistribution>> to search for order items.
. Select a search term fitting the search filter in the *Item search* field.
. Click on *Search*. +
→ The item variations that are in stock in the sending warehouse are displayed.
. Enter the item quantity that should be redistributed in the *Quantity* column of the variation.
. Click on the *Cart* icon. +
→ The variations are added to the cart.
. Repeat the steps described above until all variations that should be redistributed are included in the cart in the desired quantities.
. In the *Cart* area, click on *Save*. +
→ The cart is saved. +
→ The redistribution opens.

[[table-filter-item-search-redistribution]]
.Available filters in the item search
[cols="1,3"]
|====
|Setting |Explanation

|*Item ID*
|Enter the ID to search for the item with this ID.

|*Variation ID*
|Enter the ID to search for the variation with this ID.

|*Variation number*
|Enter the variation number to search for the variation with this number.

|*Barcode*
|Enter the barcode to search for the variation with this barcode.

|*Item name*
|Enter the item data to search for the item with this name.

|*Supplier number*
|Enter the number of the supplier to search for items with this supplier number.

|*Warehouse*
|Enter the name of the warehouse to search for items linked to this warehouse.

|====


[IMPORTANT]
.Results of the item search
====
The item search in this menu only lists items and variations that are in stock in the sending warehouse. If items or variations are not displayed in the search results, check the available stock in the *Stock<b> » </b>Stocks* menu or in the *Stock* tab of the respective item or variation.
====

[#800]
=== Generating a PO delivery note
After adding the order items to the redistribution, the stock movements are already prepared. The red arrows on the *Stock movements* table represent those prepared stock movements.
We urgently recommend that you check the stock movements as well as the quantities included in this table before proceeding with the redistribution. Afterwards, proceed with generating a *PO delivery note* that lists all order items included in the redistribution.

[.instruction]
Generating a PO delivery note:

. Open the *Documents* area.
. Click on *Add delivery note*.
. Select the option *Generate delivery note*. +
→ The PO delivery note is generated.

After the document has been generated, the PO delivery note is permanently available in the *Documents* area, where it can be downloaded and deleted. Alternatively, an external delivery note can be uploaded in this area. To do so, click on *Add delivery note* and select the option *Upload delivery note*.

[#900]
=== Booking items out
After generating the PO delivery note, proceed with booking the items out in the sending warehouse.

[WARNING]
.Redistribution locked
====
After carrying out the steps described in the following, the redistribution *cannot* be edited any more. Order items can neither be deleted nor added after this step. Only book items out after carefully checking the redistribution!
====

[.instruction]
Booking items out:

. In the *Order details* area, click on the *gear-wheel* icon next to the *Order initiated* field. +
→ The redistribution is created and outgoing items are booked in the sending warehouse.

[#1000]
=== Booking items in
Upon arrival in the receiving warehouse, the order items included in the redistribution have to be booked in. Proceed as described below.

[.instruction]
Booking items in:

. Open the *order items* area.
. Enter the item quantity that should be booked in in the *Quantity* column.
. Click on *Create stock movements*. +
→ The stock movements are created.
. Open the *Stock movements* area. The green arrows in the table represent the prepared stock movements.
. Enter a storage location in the *Storage location* column.
. Place a check mark in every line belonging to an item variation that should be booked in.
. In the *Delivery note number* field, enter the number of the delivery note that was generated during the process of booking items out.
. Click on *Create stock movements*. +
→ Incoming items are booked in the receiving warehouse.

[#1100]
=== Finishing a redistribution
As soon as all order items included in the redistribution have been booked in in the receiving warehouse, you should finish the redistribution in your plentymarkets system. To do so, proceed as described below.

[.instruction]
Finishing a redistribution:

. Open the redistribution.
. Open the *Order details* area.
. Click on the *gear-wheel* icon next to the *Finish date* field. +
→ The current date is automatically set as the finishing date of the redistribution. +
→ The redistribution is locked and cannot be edited any more.

[TIP]
.Unlocking a redistribution
====
In case you have set the finish date by mistake, unlock the redistribution by clicking on the same icon once more. This way, the redistribution is unlocked and can be edited again.
====

[#1200]
== Automating redistributions
Redistributions can be partly automated with the help of the event procedures available in your plentymarkets system. In the *System » System settings » Orders » Events* menu, the events, filters and procedures available in the groups named *Purchase order* allow you to automate certain steps of the redistribution. +

For more detailed information on setting up event procedures, refer to the <<basics/automation/event-procedures#, Event procedures>> page of the manual. If you are working with event procedures for the first time, pay attention to the information provided on creating event procedures in the chapter <<automation/event-procedures#100, Creating a new event procedure>>.
