= Carrying out redistributions
:lang: en
include::{includedir}/_header.adoc[]
:description: Learn how to work with redistributions between different warehouses in your plentymarkets system.
:keywords: Redistribution, warehouse redistribution, storage location, storage locations, PO delivery note
:position: 50
:url: stock-management/working-with-redistributions

In the *Stock » Reorder management » Purchase order*, your plentymarkets system offers you to redistribute items between different warehouses.

A redistribution consists of the following steps:

* <<#600, Creating a redistribution>>
* <<#700, Adding order items>>
* <<#800, Generating a PO delivery note>>
* <<#900, Booking items out>>
* <<#1000, Booking variations in>>
* <<#1100, Finishing a redistribution>>

We recommend carrying out some preparatory settings before working with redistributions.


[#100]
== Preparatory settings
To optimise your workflow using warehouse redistributions, we recommend carrying out some preparatory settings. These settings are described in the following. Create new order statuses especially for reorders and create tags to keep a good overview. Setting up a document template for the *PO delivery note* is required as well.

[#200]
=== Creating order statuses for redistributions
A certain number of statuses is saved in your plentymarkets system by default. Those default order statuses can also be used for redistributions. You can create statuses that are exclusively used for this particular order type. Creating new order statuses is described in detail on the <<orders/managing-orders#1200, Managing orders>> page of the manual.

[TIP]
.Creating own order statuses for redistributions
====
We recommend creating separate order statuses that you only use for working with redistributions. Assign particular names to the order statuses to distinguish between redistributions and other order types. This is particularly important when automating the redistribution with the help of <<#1100, event procedures>>.
====

[#300]
=== Creating tags for redistributions
Tags are keywords that you create centrally before you can use them to mark data in different areas of your plentymarkets system. If you want to use tags with redistributions, you need to create those tags beforehand in the *System » System settings » Settings » Tags* menu. To do so, follow the instructions on the <<basics/working-with-plentymarkets/tags#, Tags>> page of the manual.

[#400]
=== Carrying out default settings
You can determine default settings to reduce the workload involved in creating a new redistribution. The default settings are then automatically displayed in the data fields when creating a new redistribution. To do so, proceed as described below.

[.instruction]
Carrying out default settings:

. Go to *System » System settings » Stock » Reorder management » Redistribution » Settings*.
. Select a *Default status* that should be preselected when creating a redistribution.
. Carry out the desired settings for the *Default owner*. Pay attention to the information provided in <<table-default-owner-redistribution>>.
. *Save* the settings. +
→ The selected default settings are displayed when creating new redistributions.

[[table-default-owner-redistribution]]
.Available settings for the default owner
[cols="1,3"]
|====
|Setting |Explanation

|*Active owner preselected*
|The user creating the redistribution in the plentymarkets back end is preselected in the *Owner* field.

|*No owner preselected*
|The *Owner* field remains empty when creating a new redistribution.

|====

[#500]
=== Setting up a template for the PO delivery note
Working with redistributions requires using the particular document type *PO delivery note* (PO = Purchase order). This delivery note lists all variations included in a redistribution.  Warehouse staff and logistics partners can use this document to keep track of the variations included when booking the order items in in the receiving warehouse.

[IMPORTANT]
.Document template must be set up
====
The document template for the document *PO delivery note* has to be set up before creating the document for the first time. As long as the document template has not been set up, no delivery note can be generated for a redistribution.
====

The following instructions describe how to transfer the default document template saved in your plentymarkets system.

[.instruction]
Setting up a template for the PO delivery note:

. Go to *System » System settings » Stock » Reorder management » Redistribution » Documents » PO delivery note*.
. Open the *transfer* tab.
. Select the language from the drop-down list above the tab title.
. In the *Apply settings from default document template* area, click on *Accept*. +
→ The default document template is applied to the document.

To set up the document *PO delivery note* according to your individual wishes, proceed as described in the <<orders/order-documents#300, Setting up a document template>> chapter.

[#600]
== Creating a redistribution
After having carried out the preparatory settings, you can proceed with creating an order of the type redistribution.

[.instruction]
Creating a new redistribution:

. Go to *Stock » Reorder management » Purchase order*.
. Move the cursor over the *Plus icon* and click on *New redistribution*. +
→ The menu for creating a new redistribution opens.
. In the *Status* field, select an initial <<#200, status>> that should be assigned to the new redistribution. This status can be changed at a later point in time.
. In the *Sender* field, select the warehouse from which items should be booked out.
. In the *Receiver* field, select the warehouse into which the items should be booked.
. *_Optional:_* Select one or several *Tags* to mark the new redistribution.
. *_Optional:_* Select an *Owner*, meaning the user responsible for the redistribution.

// muss hier noch gespeichert werden?

[IMPORTANT]
.Selecting an owner
====
If the desired *Owner* is missing, check if the user has been activated as an owner. Proceed according to the instructions on the <<basics/admin-tasks/manage-users#40, Managing user accounts>> page of the manual to activate owners. In addition, check the <<#400, default settings>> for owners described above.
====

[#700]
=== Adding order items
The next step consists of adding the items that should be redistributed from one warehouse to another. Use the *Filter* to search for the desired order items according to the available <<item/managing-items#_filtering_items, item and variation data>>.

[.instruction]
Adding order items:

. In the *Order items* area, click on *Add*. +
→ A menu for adding order items opens.
. Select a filter to search for items. The filters are described in <<table-filters-item-search-redistribution>>.
. Select a search term fitting the search filter in the *Item search* field.
. Click on *Search*. +
→ The item variations that are in stock in the sending warehouse are displayed.
. Enter the item quantity that should be redistributed in the *Quantity* column of the variation.
. Click on the *Cart* icon. +
→ The variations are added to the cart.
. Repeat steps 1 to 6 until all variations that should be redistributed are included in the cart in the desired quantities.
. In the *Cart* area, click on *Save*. +
→ The cart is saved. +
→ The redistribution opens.

[[table-filters-item-search-redistribution]]
.Available filters in the item search
[cols="1,3"]
|====
|Setting |Explanation

|*Item ID*
|Enter the ID to search for the item with this ID.

|*Variation ID*
|Enter the ID to search for the variation with this ID.

|*Variation number*
|Enter the variation number to search for the variation with this number.

|*Barcode*
|Enter the barcode to search for the variation with this barcode.

|*Item name*
|Enter the item data to search for the item with this name.

|*Supplier number*
|Enter the number of the supplier to search for items with this supplier number.

|*Warehouse*
|Enter the name of the warehouse to search for items linked to this warehouse.

|====


[IMPORTANT]
.Results of the item search
====
The item search in this menu only lists items and variations that are in stock in the sending warehouse. If items or variations are not listed, check the available stock in the *Stock< » Stocks* menu or in the *Stock* tab of the respective item or variation.
====

[#800]
=== Generating a PO delivery note
After adding the order items to the redistribution, the stock movements are already prepared. The red arrows on the *Stock movements* table represent those prepared stock movements.
We urgently recommend that you check the stock movements as well as the quantities included in this table before proceeding with the redistribution. Afterwards, proceed with generating a *PO delivery note* that lists all order items included in the redistribution.

[#830]
==== Manually create a PO delivery note
Proceed as described below to manually create the document *PO delivery note*.

[.instruction]
Manually creating a PO delivery note:

. Open the *Documents* area.
. Click on *Add delivery note*.
. Select the option *Generate delivery note*. +
→ The *PO delivery* note is generated.

[#870]
==== Automatically creating a PO delivery note

Set up the following event procedure to automatically generate the document *PO delivery note* as soon as you have <<#900, booked out>>the items included in the redistribution from the sending warehouse.

[.collapseBox]
.Automatically generating a PO delivery note:
--
. Go to *System » System settings » Orders » Events*.
. Click on *Add event procedure*.  +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<table-event-procedure-create-po-delivery-note>>.
. *Save* the settings.
. Carry out the settings as desired. Pay attention to the information given in table <<table-event-procedure-create-po-delivery-note>>.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--
[[table-event-procedure-create-po-delivery-note]]
.Event procedure for automatically generating the PO delivery note
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Purchase order > Purchase order initiated*
|

|*Filter*
|*Order type > Purchase order, type redistribution*

|*Procedure*
|*Purchase order > Generate PO delivery note*
|
|====

After the document has been generated, the PO delivery note is permanently available in the *Documents* area, where it can be downloaded and deleted. If your supplier sends you an external delivery note, it might not make sense to create your own delivery note. You can upload the external delivery note in the *Documents* area as well. To do so, click on *Add delivery note* and select the option *Upload delivery note*.

[#900]
=== Booking items out
After adding all items that should be redistributions, book the order items out of the sending warehouse.

[WARNING]
.Redistribution is locked
====
After carrying out the steps described in the following, the redistribution *cannot* be edited any more. Order items can neither be deleted nor added after this step. Only book items out after carefully checking the redistribution!
====

[.instruction]
Booking items out:

. In the *Order details* area, click on the *gear-wheel* icon next to the *Order initiated* field. +
→ The redistribution is created and outgoing items are booked in the sending warehouse.

[#1000]
=== Booking variations in
As soon as the items from the sending warehouse arriv,, book the order items into the receiving warehouse. To do so, proceed as described below.

[.instruction]
Booking variations in:

. Open the *Order items* area.
. Enter the item quantity that should be booked in in the *Quantity* column.
. Click on *Create all stock movements*. +
→ The stock movements are created.
. Open the *Stock movements* area. The green arrows in the table represent the prepared stock movements.
. Enter a storage location in the *Storage location* column.
. Place a check mark in every line belonging to an item variation that should be booked in.
. In the *Delivery note number* field, enter the number of the delivery note that was generated during the process of booking items out.
. Click on *Create all stock movements*. +
→ Incoming items are booked in the receiving warehouse.

[#1100]
=== Finishing a redistribution
As soon as all order items included in the redistribution have been booked in in the receiving warehouse, finish the redistribution in your plentymarkets system. To do so, proceed as described below.

[.instruction]
Finishing a redistribution:

. Open th redistribution.
. Open the *Order details* area.
. Click on the *gear-wheel* icon next to the *Finish date* field. +
→ The current date is automatically set as the finishing date of the redistribution. +
→ The redistribution is locked and cannot be edited any more.

[TIP]
.Unlocking a redistribution
====
In case you have set the finish date by mistake, unlock the redistribution by clicking on the icon once more. This way, the redistribution is unlocked and can be edited again.
====

[#1200]
== Searching for redistributions
When opening the *Stock » Reorder management » Purchase order* menu, all existing redistributions and <<stock-management/working-with-redistributions#, reorders>> are displayed. You can change the result by changing the filter settings. You can either choose to use more filters or to reset the filters and to get all redistributions.

[.instruction]
Searching for redistributions:

. Go to *Stock » Reorder management » Purchase order*. +
. Select one or several of the filters listed in <<table-redistribution-search-filter>> to limit the search results.
. Click on *Search*.

[[table-redistribution-search-filter]]
.Available filters for searching for redistributions
[cols="1,3"]
|====
|Setting |Explanation

|*Order ID*
|Enter the order ID of the redistribution.

|*Order type*
|Select the order type *Redistribution* to only display orders of the type *Redistribution*.

|*Item ID*
|Enter an item ID to search for redistributions containing an item with this ID.

|*Variation ID*
|Enter a variation ID to search for redistributions containing a variation with this ID.

|*Variation number*
|Enter a variation number to search for redistributions containing a variation with this number.

|*Item data*
|Enter a search term or a numeric value to search for redistributions that contain items with the term or number. The *Item ID*, *Item number* and *Name* are searched. In addition, set the *Order type* filter to *Redistribution*.

|*Status*
|Select a status from the list. In addition, set the *Order type* filter to the option *Redistribution* to search for redistributions with this status.

|*Owner*
|Select an owner from the list. In addition, set the *Order type* filter to the option *Redistribution* to search for redistributions with this owner.

|*Order date from ... to*
|Select a start and end date from the calendar. This selection limits the time period to include the order date of the redistribution.

|====

[#1300]
== Automating redistributions
Use event procedures to automate the separate working steps of a redistribution. One possibility of automating the generation of the *PO delivery note* has already been described in the <<#870, Automatically generating a PO delivery note>> chapter. In the *System » System settings » Orders » Events* menu, the events, filters and procedures available in the groups named *Goods* allow you to automate certain steps of the redistribution. +

For more detailed information on setting up event procedures, refer to the <<basics/automation/event-procedures#, Event procedures>> page of the manual. +
If you are working with event procedures for the first time, pay attention to the information provided on creating event procedures in the chapter <<automation/event-procedures#100, Creating a new event procedure>>.
