= Global settings
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Client, Store, Global settings
:position: 30

**plentymarkets » Settings » Client (store) » Global settings**

== Content of this chapter

This chapter contains information about the global settings for stores, i.e. the settings that affect all of your online stores and clients.

You will learn more about configuring **<<client-store/global-settings/ftp-access#, FTP access  >>** as well as about working with the **<<client-store/global-settings/language-packages#, language packages  >>** and editing the different messages that are generated by the system. Furthermore, you will learn how to configure **<<client-store/global-settings/external-services#, external services  >>** such as **<<client-store/global-settings/external-services/facebook#, Facebook  >>** or **<<client-store/global-settings/external-services/twitter#, Twitter  >>**. Information is also given about settings which must be carried out in order to work with **<<client-store/global-settings/sweepstakes#, sweepstakes  >>** or **<<client-store/global-settings/live-shopping#, live shopping  >>**.

== Links to other menus

In order for **<<item/managing-items#680., item images >>**, **<<orders/settings/documents#, PDF documents  >>** and other files to be available online for all visitors, these files must be transferred from your computer onto the plentymarkets server. File Transfer Protocol (FTP) is used for loading files onto a web server. Save the settings corresponding to the **<<client-store/global-settings/ftp-access#, FTP access  >>**.

== Direct access to important pages of the manual

* <<client-store/global-settings/language-packages#, **Language packages**  >>
* <<client-store/global-settings/ftp-access#, **FTP access**  >>
* <<client-store/global-settings/external-services#, **Services**  >>
* **<<client-store/global-settings/external-services/facebook#, Facebook  >>**
* **<<client-store/global-settings/external-services/twitter#, Twitter  >>**
* <<client-store/global-settings/live-shopping#, **Live shopping**  >>
* **<<client-store/global-settings/statistics#, Statistics  >>**

