= Standard
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Store, Client, Standard
:position: 40

**plentymarkets » Settings » Client (store) » Standard**

== Content of this chapter

This chapter explains various basic settings for configuring your **<<client-store/standard/online-store#, online store  >>**. Here you can save settings for your default store and configure the **<<crm/sending-emails#, E-mail service  >>**. Settings for **link::/[search engine optimization]** are particularly important. These settings ensure that your online store is easy to find on the Internet. This chapter also explains basic settings for **<<item/categories#, categories  >>**, the **<<client-store/standard/my-account#, my account  >>** area and the **<<client-store/standard/order-process#, order process  >>**. It also provides information about the basic settings of your <<client-store/standard/item-layouts#, **item layouts**  >>.

[TIP]
.Tip
====
Every additional online store or client (store) is configured in its own menu. These additional menus have the same structure as the Standard menu. The system automatically gives the menu the same name as the online store.
====

== Links to other menus

Before you start working with the **<<crm/using-the-ticket-system#, ticket system  >>** or sending out **<<crm/sending-newsletters#, newsletters  >>**, you will first have to save the configurations in the **<<crm/sending-emails#, E-mail  >>** area. The settings saved in the "Item layouts" area lay the foundation for managing your **<<item#, items  >>**.

Direct access to important pages of the manual

* <<client-store/standard/basic-settings#, **Basic settings**  >>
* **<<client-store/standard/online-store/multilingualism#, Multilingualism  >>**
* **<<client-store/standard/online-store/legal-information#, Legal information  >>**
* <<crm/sending-emails#100, **Access data** >>
* **<<crm/sending-emails1200#, E-mail templates  >>**
* <<client-store/standard/item-layouts#, **Item layouts**  >>
* **link::/[URL structure]**
* **link::/[Sitemap.xml]**
* <<item/categories#, **Categories**  >>
* <<client-store/standard/my-account#, **My account**  >>
* <<client-store/standard/order-process#, **Order process**  >>
* <<client-store/standard/external-services#, **External services**  >>
* **<<client-store/standard/external-services/trusted-shops#, Trusted Shops  >>**
* **<<client-store/standard/modules#, Modules  >>**

