= Old: CMS & online store - EASYMARKETING
:lang: en
include::{includedir}/_header.adoc[]
:keywords: easymarketing
:position: 60

*Setup » Client » Select client » Services » Easymarketing*

==  General information about EASYMARKETING

EASYMARKETING automatically organizes online advertising campaigns. The system analyzes your online store and finds relevant keywords. Then it starts campaigns, specifies the cost-per-click and creates advertisements. Improvements are continuously being made so that you can achieve even better results. (Source: translation of link:https://easymarketing.de/[easymarketing.de^])

With the help of the EASYMARKETING interface, orders will be tracked in your online store and a Google site verification will be carried out.

==  Setting up EASYMARKETING

First register with link:https://easymarketing.de/users/new?website_url=&expected_conversion_rate=&advertising_strategy=aggressive&webshop_or_other=other&daily_budget=13[easymarketing^]. You will receive a token that you need to enter in plentymarkets.

[.instruction]
Configuring the settings for EASYMARKETING:

.  Go to *Easymarketing* (see path above).
.  Enter the *Access Token* that you received from EASYMARKETING.
.  Place a check mark next to the option *Active*.
.  *Save* the settings.
