= Trusted Shops
:lang: en
include::{includedir}/_header.adoc[]
:position: 100

*System » Client » Select client » Services » Trusted Shops*

== General information about Trusted Shops

Trusted Shops is a Trustbadge for online stores, which provides buyer protection for online customers. This page teaches you how the Trusted Shops certification process works. It tells you which settings you should pay attention to in plentymarkets if you want to be certified. +
plentymarkets already began working with Trusted Shops while the software was developed. As such, many of the certification requirements are already fulfilled. Your advantages: You can receive Trusted Shops certification with less effort and for a reduced price.

[TIP]
.Tip
====
For further information about online store certification, refer to the Trusted Shops website: link:https://www.trustedshops.eu/merchants/[https://www.trustedshops.eu/merchants/].
====

== Trusted Shops certification

Trusted Shops will thoroughly examine your online store during the certification process and will provide you with an individual audit report. This audit report will list any adjustments that need to be made in your plentymarkets system before you can receive certification by Trusted Shops.

In general, the order process and the structure of the online store already comply with the Trusted Shops quality criteria. However, there may still be a few areas where you will need to make individual adjustments. These adjustments are typically to correct any incorrect wording that is used in the email templates or in your store's privacy policy and cancellation rights.  +
Here you will find an overview of the menus that may need adjustments.

* <<crm/sending-emails#1200, email templates>>
* <<omni-channel/online-store/setting-up-clients/online-store#legal-information, Legal information>> such as the terms and conditions, privacy policy or cancellation rights.
* Texts in the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process, order process>>
* Texts in the <<omni-channel/online-store/setting-up-clients/extras/language-packages#, language packages>> +
The language packages contain some of the standard texts that are also displayed in the order process.  +
If your store is available in several different languages, then save translations of all the texts.
* <<crm/sending-emails#600, email signature>> +
Save your signature and include all of the information that is legally required in your country.
* Automatic reminder in case of <<crm/sending-emails#1800, aborted purchase>> +
We recommend that you do not send this email if you have not explicitly been given prior consent by the customer.
* <<omni-channel/online-store/setting-up-clients/order-process#, Basic settings>> for the order process +
Do not combine orders and do not allow changes to be made retroactively.
* Mark mandatory entries in <<omni-channel/online-store/setting-up-clients/cms#settings-forms, forms>> and enter a note to explain what the marking means.
* <<omni-channel/online-store/setting-up-clients/extras/language-packages#, Note>> below the email field during the store registration process +
You can use the *General texts* section of the language packages to save a note directly below the email entry field. The *Internal name* of this field is *Registrierung E-Mail Hinweis*. Here is a suggestion for this note: +
"We will regularly send you an email containing carefully selected offers for similar products from our collection. Your email address will not be passed on to other companies. You can request that we no longer send offers and advertisements to your email address at any time. This can be done by simply sending us an email."

[TIP]
.Additional information about the certification
====
link:http://www.trustedshops.eu/seal-of-approval/quality-criteria.html[Trusted Shops quality criteria^] +
link:http://www.trustedshops.eu/seal-of-approval/buyer-protection.html[Questions about buyer protection^] +
link:https://www.trustedshops.eu/merchants/[Information for online sellers^]
====

Set up <<omni-channel/online-store/setting-up-clients/extras/_trusted-shops/seller-rating#, seller ratings>> once you have been certified by Trusted Shops.
