= Händlerbund
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Legal information, Händlerbund
:description: plentymarkets integration: Set up the interface to Händlerbund and the rating tool in plentymarkets.
:position: 150
:url: online-store/online-store/extras/haendlerbund

[NOTE]
.Old: CMS & online store
====
This manual page describes functions that pertain to the old plentymarkets online shop *Callisto*. For information regarding the online store template *Ceres*, please refer to the <<omni-channel/online-store/setting-up-ceres#, Setting up Ceres page>>.
====

The Händlerbund e.V. is Europe's largest online trade association and one of the leading online providers of <<omni-channel/online-store/setting-up-clients/online-store#legal-information, German legal texts>>. The company is based in Leipzig. The Händlerbund has an interface for terms and conditions, called the AGB-Schnittstelle. You can use this interface to easily integrate German legal texts into your plentymarkets system. The legal texts can be updated easily, e.g. if they need to be changed because of amendments to the law.

== Registering with the Händlerbund

You need to link:http://www.haendlerbund.de/mitgliedschaft/details[register^] with the Händlerbund before you can use its services for your plentymarkets system. Please note that the services are only available in German.

[IMPORTANT]
.SOAP API not available for plentymarkets Zero
====
Note that the *SOAP API* module is required for setting up the interface to Händlerbund. This module is not available for plentymarkets Zero.
====

== Setting up users for the Händlerbund

Your plentymarkets system will be connected to the Händlerbund via the SOAP interface. In order for it to have access, you first need to create an individual <<basics/admin-tasks/manage-users#10, user account>> with access rights to the API in your system.

[.instruction]
Setting up a user account:

. Go to *Setup » Settings » User » Accounts*.
. Click on *New*. +
→ The *Create new user* window will open.
. Enter the *User name*, *Actual name* and *Password*.
. Repeat the password.
. Enter the user's email address. This will allow the user to receive messages from the system.
. Select the user class *API*.
. *Save* the settings.

Next, activate the following calls in the user profile in the tab *Rights » Tab: SOAP-API*. The Händlerbund requires these calls:

* *Item » GetItemsImages*
* *Order » SearchOrders*
* *Webshop » SetLegalInformation*
* *Webshop » SetTermsAndCancellation*
* *Webshop » GetMultiShops*
* *Others » SetContentPage*

== Setting up the rating tool

The Händlerbund offers its members a rating tool called *Käufersiegel*. You must be a member of the Händlerbund in order to use this rating tool. You need to have a Händlerbund member number in order to link:https://www.kaeufersiegel.de/bewertung/register.php[register^] the ratings. You need to have the access data of the previously created API user in order to configure the Käufersiegel backend area. This access data consists of the *user name*, *password* and the *URL* of the plentymarkets system that you want to use the rating tool with.

There is a link:http://wiki.kaeufersiegel.de/index.php/Plentymarkets[Käufersiegel wiki^] that you can use for the settings in the backend of Händlerbund and for saving the access data.

[IMPORTANT]
.Server URL
====
The *server URL* that is saved in the Käufersiegel backend is the *URL of the plentymarkets system*.
====
