= Live shopping
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Online store, Client, Live shopping
:position: 200

[NOTE]
.Old: CMS & online store
====
This manual page describes functions that pertain to the old plentymarkets online shop *Callisto*. For information regarding the online store template *Ceres*, please refer to the <<omni-channel/online-store/setting-up-ceres#, Setting up Ceres page>>.
====

//  plentymarkets 7
With live shopping, one of the items from your range of products will be offered at a discounted price each day during a specified period (e.g. from 9:00am to 6:00pm). Configure live shopping offers in the *System » System settings » Client » Settings » Live shopping* menu.

== Creating a live shopping offer

Proceed as described below to create a new live shopping offer.

[NOTE]
.Sales price for live shopping offers
====
Create a sales price of the type *Special offer*, add it to an item and save a price. The sales price for your live shopping offers is selected automatically based on the sales price settings.
====

[.instruction]
Creating a live shopping offer:

. Go to *System » System settings » Client » Settings » Live shopping*.
. Click on a live shopping tab.
. Click on the *green plus icon*.  +
→ The *New live shopping offer* window will be displayed.
. Carry out the settings as desired. Pay attention to the explanations given in <<table-live-shopping-settings>>.
. *Save* the settings.

[[table-live-shopping-settings]]
.live shopping settings
[cols="1,3"]
|====
|Setting |Explanation

|*Start*
|Select a date and a time when the live shopping offer should start.

|*End*
|Select a date and a time when the live shopping offer should end.

|*Item ID*
|Enter the item's ID. +
*_Note:_* The same item cannot be offered in more than one live shopping offer during the same period.

|*Quantity sold*
|Setting changes the displayed percentage of items that have been purchased in live shopping already.

|*Total*
|Enter maximum quantity that can be sold at the discounted price. Regardless of this entry, there must be enough stock available for those items that are tied to the stock. +
If a customer tries to put a larger quantity into their shopping cart, then the quantity will automatically be reduced. As soon as this quantity has been sold, the item will be offered at the normal price again.

|*Link active*
|The same period can be configured for more than one live shopping offer. Activate option to display this live shopping offer as soon as a live shopping item that is higher up in the live shopping display and is sold at the same time has sold out.
|====


[WARNING]
.Price if the remaining quantity is exceeded
====
At some point, a buyer may try to order more copies of an item than are still available in the live shopping offer. If this happens, then the normal item price will be used for the entire order. Example: There are 7 copies of a live shopping item remaining. A customer puts 8 copies of the live shopping item into their shopping cart. All 8 copies of the item will be sold at the normal sales price.

Advise customers of this fact and make sure that they can always see how many items are still available at a reduced price as part of the live shopping offer.
====

== Configuring a live shopping offer

Configure newly created live shopping offers as described below.

[.instruction]
Configuring a live shopping offer:

. Go to *System » System settings » Client » Settings » Live shopping*.
. Click on a live shopping tab.
. Click on the *Settings* tab.
. Carry out the settings as desired. Pay attention to the explanations given in <<table-settings-live-shopping-offers>>.
. *Save* the settings.

[[table-settings-live-shopping-offers]]
.settings for live shopping offers
[cols="1,3"]
|====
|Setting |Explanation

|*Show live shopping*
|*Hide if no offer is active* = The template variable <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewliveshopping, Container_ItemViewLiveShopping()>> will only be displayed if an item currently can be purchased at the discounted price. +
*Show upcoming offer if no offer is currently active* = Template variable will always be filled. If no offer is active, a preview of an upcoming offer is shown. However, the discounted price will only be applied once the live shopping offer starts. Therefore, set the same starting time for offers that should automatically follow each other. Also see <<table-live-shopping-settings>> , option *Link active*.
|====


== Integrating live shopping into your online store

Now insert the live shopping function into your online store. Insert the following template function and template variable into your online store's design.

* *{% Container_ItemViewLiveShopping() %}*
* *{% $LiveShoppingID = 1 %}* +
→ The ID determines which live shopping offer is inserted. For example, use *ID 1*, to insert the offer *Live shopping 1*.

=== Modifying the ItemViewSingleItem view

You can indicate again that the live shopping is a special offer by inserting the following template variables into the *ItemViewSingleItem* template:

* *$LiveShoppingQuantityRemaining*
* *$LiveShoppingPrice*

Example code for your ItemViewSingleItem template:

[source,plenty]
----
include::assets/EX-EN-Live-Shopping-SoAngebot.html[]

----

=== Modifying the offer view using template variables

Design the layout for live shopping offers in the *CMS » Web design » Layout » ItemView » ItemViewLiveShopping* template. The following template variables are available for this purpose:

* *$LiveShoppingContainerId*
* *$LiveShoppingQuantityRemaining*
* *$LiveShoppingPrice*
* *$LiveShoppingPriceOriginal*
* *$LiveShoppingPercentRemaining*
* *$LiveShoppingPercentSold*
* *$LiveShoppingQuantitySold*
* *$LiveShoppingStartTime*
* *$LiveShoppingEndTime*

The following code shows a possible layout for live shopping offers in the *ItemViewLiveShopping* template:

[source,plenty]
----
include::assets/EX-EN-liveshopping.html[]

----

== Publishing live shopping offers

Live shopping offers can also be presented on external platforms such as the German site link:http://www.liveshopping-aktuell.de[liveshopping-aktuell.de^]. Register with the provider and save the offer's URL as follows:

* Offer 1: your_domain/plenty/api/liveshopping_xml_1.php
* Offer 2: your_domain/plenty/api/liveshopping_xml_2.php

In these examples, the items for the first and second live shopping offer are exported.

Use the ID to specify which live shopping offer should be exported. Use the parameter *SHIPPING* to set specific shipping costs.

[TIP]
.Example: ID and SHIPPING parameters
====
ID for live shopping offer 1: "your_domain/plenty/api/liveshopping_xml_1.php?ID=1" +
ID for live shopping offer 3 and code for 3.90 shipping costs: "your_domain/plenty/api/liveshopping_xml_2.php?ID=3&amp;SHIPPING=3.90"
====

Only the preview text (short_description) will be exported as the item description.

[IMPORTANT]
.Export condition
====
Live shopping offers will only be exported if the item is linked to a category.
====

[#100]
== Posting information about live shopping offers automatically

Use the procedure manager to publish information about your live shopping offers on Twitter and Facebook every day. To do so, set up procedures. For further information about setting up your Twitter account in plentymarkets, refer to the <<omni-channel/online-store/extras/twitter#, Twitter>> page of the manual.

[.instruction]
Setting up a procedure:

. Go to *System » System settings » Item » Procedures*.
. Click on the *New procedure* tab.
. Select the*Tweet live shopping offers* procedure.
. Enter a name.
. Specify a time at which the procedure is to be carried out.
. Place a check mark next to the option *Active*.
. Click on the *Filter* tab.
. Select the client (store).
. Select which category page the template variable for the live shopping offer was inserted in.
. Select the Twitter account that is to be used for the procedure.
. Click on the *Procedure* tab.
. Enter a message for the procedure.
. *Save* the settings. +
→ The procedure will be set up and displayed in the *Procedures* tab.

In order to post live shopping offers on Facebook, set up a second procedure *Post live shopping on Facebook* in the same way and link the procedure to your Facebook account.

[WARNING]
.Facebook-Berechtigungen
====
To ensure that the linking of your Facebook account is functioning properly, you have to activate the two permissions link:https://developers.facebook.com/docs/facebook-login/permissions/v2.4#reference-manage_pages[manage_pages^] and link:https://developers.facebook.com/docs/facebook-login/permissions/v2.4#reference-publish_pages[publish_pages^].
====

== FAQs

=== Active live shopping offer

[.instruction]
When is live shopping active for an item?

[.indented]
The live shopping for an item is active when the current time is within the previously specified time frame and when there is still a sufficient amount of stock available for items that are tied to the stock.=== Selling attribute items

[.instruction]
I sell item variations. Can the selection of attributes be built into the live shopping offer?

[.indented]
Yes, the selection of attributes can be built into the live shopping offer. Use the same template variables as for displaying single items. These include *$AttributeSelect* and *$AttributeSelectWithoutAttributeName*. Simply insert one of these two template variables into your *ItemViewLiveShopping* template.=== Inserting a link to live shopping offer

[.instruction]
I would like to create a link from the homepage to the page with the live shopping offer. How do I display this link only while a live shopping offer is active?

[.indented]
To do so, use the template function *{% if Container_ItemViewLiveShopping() %} LINK {% endif %}*.
