= Protected Shops
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Protected Shops, Online store, Client (store)
:position: 220

*System » System settings » Client » Select client » Online store » Legal information*

[NOTE]
.Old: CMS & online store
====
This manual page describes functions that pertain to the old plentymarkets online shop *Callisto*. For information regarding the online store template *Ceres*, please refer to the <<omni-channel/online-store/setting-up-ceres#, Setting up Ceres page>>.
====

==  General information about Protected Shops

*Protected Shops GmbH* is a leading *provider of legal texts* for online businesses. Please note that their services are only available in German. Protected Shops provides online sellers with <<omni-channel/online-store/setting-up-clients/online-store#legal-information, legal texts>> that are individually customized to meet the seller's personal needs. Protected Shops offers a variety of different service packages that contain all of the necessary legal texts and guarantees the assumption of liability. Whenever changes are made to current legislation, Protected Shops automatically updates its texts and informs its customers about the changes via Protect Mail.

As a plentymarkets customer, you can benefit from the AGB Connect interface, which Protected Shops offers especially for the system. This interface makes it possible to transfer all of the legal texts into your plentymarkets online shop at any time and with a minimum amount of effort. This ensures that the legal texts are always up to date.

==  Settings in plentymarkets

Our SOAP API interface is used to make a connection. The following settings need to be carried out as well:

*  Configuration of the *shop data* in your Protected Shops account.
*  Configuration of a <<basics/admin-tasks/manage-users#, user>> who was given the necessary *SOAP rights*.
*  Check the <<basics/data-exchange/api-data#, SOAP WSDL>> and the *names* and *IDs* of the <<item/managing-categories#, category pages>>.
*  You may need to create additional content pages, e.g. *battery ordinance* and *sale or return policy*.

This link:https://www.plentymarkets.co.uk/tpl/download/KK_DE_Domain.pdf[document^] contains detailed information about carrying out the steps listed above. Please note that the document is currently only available in German.
