= Universal Analytics
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Universal Analytics, Tracking
:position: 300
:url: online-store/online-store/extras/universal-analytics

*CMS » Web design*

[NOTE]
.Old: CMS & online store
====
This manual page describes functions that pertain to the old plentymarkets online shop *Callisto*. For information regarding the online store template *Ceres*, please refer to the <<omni-channel/online-store/setting-up-ceres#, Setting up Ceres page>>.
====

== General information about Universal Analytics

Universal Analytics is the current operating standard for Google Analytics. link:http://www.google.com/intl/en_uk/analytics/[Universal Analytics^] is a free tool for analyzing websites and apps with respect to visitor statistics and user behavior. Furthermore, the link:https://support.google.com/analytics/answer/1037249?hl=en&topic=1037061&ctx=topic[e-commerce^] service provided by Google Analytics allows you to track e-commerce activities.

This page teaches you how to set up Universal Analytics in order to collect data about visitor statistics and user behavior (section 2).

Additionally, section 3 teaches you how to collect data about your sales. Please note that you need to set up the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-individual-order-process, individual order process>> in order to use conversion tracking with Universal Analytics.

[WARNING]
.Important information about privacy policy
====
The following link lists three important points that need to be considered when using Classic Google Analytics and Universal Analytics in Germany: +
link:http://www.lhr-law.de/lbr-blog/nrw-datenschutzbeauftragter-uberpruft-google-analytics-einsatz[http://www.lhr-law.de/lbr-blog/nrw-datenschutzbeauftragter-uberpruft-google-analytics-einsatz^]

Privacy policy guidelines and regulations are continuously changing. Please make sure that you comply with the laws for the country that you are based in. Stay informed and contact your legal adviser.
====

== Setting up Universal Analytics

This section teaches you how to set up Universal Analytics (analytics.js) and how to switch from the Classic Google Analytics (ga.js) to Universal Analytics. The configuration is divided into settings that are carried out in your Google Analytics account and settings that are carried out in plentymarkets.

=== Settings in Google Analytics

Log in or create an account with link:http://www.google.com/intl/en_uk/analytics/[Google Analytics^] in order to use Universal Analytics for your website. For further information about setting up a profile for your website, refer to the link:https://support.google.com/analytics/?hl=en#topic=3544906[Google Analytics Help Center^].

If you already use Classic Google Analytics (ga.js), then you can find information about switching to Universal Analytics (analytics.js) in the link:https://developers.google.com/analytics/devguides/collection/upgrade/[Universal Analytics Upgrade Center^].

[TIP]
.Settings for encrypted websites
====
If you use an <<basics/admin-tasks/plentymarkets-account#ssl-certificate, SSL certificate>> for your website, then select *https* in Google Analytics.
====

=== Retrieving the tracking code snippet (analytics.js)

After you created a profile for your website in Google Analytics, you need the tracking code (analytics.js). For further information about generating the tracking code, refer to the link:https://support.google.com/analytics/answer/1008080?hl=en[Google Analytics help^].

Your tracking code (analytics.js) is displayed once alone and once embedded within a tracking code snippet. The tracking code snippet is located in a field with several lines of JavaScript. It begins with *&lt;script&gt;* and ends with *&lt;/script&gt;*. Copy the tracking code snippet that was generated (*Ctrl+C* or *cmd+C*). Then insert the tracking code snippet into plentymarkets as described below.

=== Settings in plentymarkets

Insert the tracking code snippet into plentymarkets as described below.

[.instruction]
Inserting the tracking code snippet (analytics.js) into plentymarkets:

. Go to *CMS » Web design*.
. Click on the *Layout* folder and select the template *PageDesign » PageDesignContent*.
. Click on the *PageDesignContentHtmlStructure* tab.
. Insert the tracking code snippet (analytics.js) from Universal Analytics into the end of the text field.
. *Save* the settings. +
→ Now the code is active and Google Analytics starts collecting data about how your website is used.

== Conversion tracking in the individual order process

In addition to information such as the number of visitors, which pages the visitors clicked on, etc., you can also track conversion data with Universal Analytics.

[WARNING]
.Universal Analytics can only track conversion with the individual order process
====
Universal Analytics conversion tracking can only be used in plentymarkets in combination with the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-individual-order-process, individual order process>>. The Universal Analytics tracking code for e-commerce tracking will not work with the shopping cart and the order process found under *CMS » Web design » Order process*. Therefore, set up the individual shopping cart before you switch from Classic Google Analytics to Universal Analytics.
====

All of your sales will be analyzed once you have activated conversion tracking in plentymarkets. Universal Analytics analyzes the following order data and item data:

Order data:

* Order ID
* Order VAT
* Delivery costs for the order

Item data:

* Item ID
* Order ID
* Item name
* Item category
* Item price
* Item quantity

Proceed as described below to activate conversion tracking.

=== Settings in Google Analytics

You need the link:https://support.google.com/analytics/answer/1037249?hl=en&topic=1037061&ctx=topic[e-commerce^] service provided by Google Analytics in order to track order processes in your online store. Activate this service in your Google Analytics profile before you carry out the settings described below.

=== Settings in plentymarkets

Universal Analytics can only track conversion in the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-individual-order-process, individual order process>>. The template function *{% CheckoutGoogleUniversalTracking() %}* is used to analyze data from the individual order process. This template function and the tracking code snippet (analytics.js) from Universal Analytics are inserted into the menu *CMS » Web design » Layout » Checkout » CheckoutOrderConfirmation*. Proceed as described below to activate conversion tracking in plentymarkets.

[.instruction]
Inserting the tracking code snippet (analytics.js) and template function into the individual order process:

. Go to *CMS » Web design*.
. Click on the *Layout* folder and select the template *Checkout » CheckoutOrderConfirmation*.
. Click on the *CheckoutOrderConfirmationHeader* tab.
. Insert the tracking code snippet from Universal Analytics (analytics.js) into the end of the text field.
. Insert the template function *{% CheckoutGoogleUniversalTracking() %}* into the tracking code snippet. Insert this function between the lines +
*ga('create', 'UA-XXXX-Y', 'auto');* and *ga('send', 'pageview');*. UA-XXXX-Y stands for your tracking ID. +
The last part of the code snippet will look something like this: +

* *ga('create', 'UA-1234-5', 'auto'); +*
* *{% CheckoutGoogleUniversalTracking() %} +*
* *ga('send', 'pageview');*

. *Save* the settings. +
→ Now the code is active and Google Analytics starts collecting data from the order process.
