= YOOCHOOSE
:lang: en
include::{includedir}/_header.adoc[]
:keywords: yoochoose, cross-selling, recommendations
:position: 310

[NOTE]
.Old: CMS & online store
====
This manual page describes functions that pertain to the old plentymarkets online shop *Callisto*. For information regarding the online store template *Ceres*, please refer to the <<omni-channel/online-store/setting-up-ceres#, Setting up Ceres page>>.
====

The external service provider YOOCHOOSE offers an alternative to plentymarkets cross-selling. YOOCHOOSE offers online store customers individually tailored cross-selling recommendations that are based on statistical analyses of the user's behavior. The YOOCHOOSE Recommender Engine offers personalised product recommendations by combining knowledge about your products with your customers' consumer behavior to give individual recommendations. Recommendations range from the simple Amazon approach of "Customers Who Bought This Item Also Bought" all the way to individually personalised recommendations and recommendations that automatically improve over time.

YOOCHOOSE offers the following features:

* *Calculating recommendations:*Latest patented algorithms are used to calculate precise recommendations based on a combination of the user's activity and knowledge of your portfolio.
* *Situation-based presentation:* The placement as well as the context on both the main pages and detailed pages have an influence on the algorithms and filters that are used.
* *Optimisation with the help of filters:* The use of suitable filters for categories, duplicates, time frames or previously displayed recommendations will greatly improve the quality of recommendations.
* *Fallback:* If there is no usage or profile data available for a particular item or customer, then fall-back solutions will be used automatically to give suitable recommendations.
* *Statistical analysis:* Statistical analyses of the solution's utilisation and acceptance.

== Registering with YOOCHOOSE

Proceed as described below to register with YOOCHOOSE.

[.instruction]
Registering with YOOCHOOSE:

. Go to *System » System settings » Client » Select client » Services » Yoochoose*.
. Click on the link to *Register now*. +
→ The YOOCHOOSE registration page opens.
. Register as described on the external registration page. +
→ You are assigned a customer number and a license key for setting up YOUCHOOSE in plentymarkets.
. Switch back to the plentymarkets back end.
. Pay attention to the explanations given in <<table-yoochoose-registration>> and carry out further settings as desired.
. *Save* the settings.

[[table-yoochoose-registration]]
.YOOCHOOSE; registration
[cols="1,3"]
|====
|Option |Explanation

|*Registration*
|Link to the YOOCHOOSE website. Click on the link to register.

|*Customer number*
|Enter the customer number you received during the registration process.

|*License key*
|Enter the license key you received during the registration process.

|*Tracking activated*
|*Yes* = The store's user-related data will be transferred to YOOCHOOSE.

|*Retrieve recommendations*
|*Yes* = Item data will be retrieved for cross-selling with YOOCHOOSE.
|====

== Setting up YOOCHOOSE in plentymarkets

After you have entered your YOOCHOOSE registration details, additional tabs are displayed that allow you to set up YOOCHOOSE in plentymarkets.

=== Configuring recommendations and layout

With the options that you set in this tab, you decide which items should be offered to a customer as cross-selling items. While the options for the category layout provide more general results, the possibilities for the item layout are more specific.

[.instruction]
Configuring recommendations and layout:

. Go to *System » System settings » Client » Select client » Services » Yoochoose*.
. Click on the *Configuration* tab.
. Pay attention to the explanations given in <<table-yoochoose-configuration>> and carry out the settings as desired.
. *Save* the settings.

[[table-yoochoose-configuration]]
.Configuration
[cols="1,3"]
|====
|Option |Explanation

|*Recommendations for category layout*
|Select an option for the category layout.

|*Layout*
|Select the template for displaying the cross-selling item layouts in your online store.

|*Recommendations for item layout*
|Select an option for the item layout.

|*Layout*
|Select the template for displaying the cross-selling item layouts in your online store. The *ArticleListCrossSelling* template is selected by default. You could select *ArticleListCrossSelling2* as a variation of this template and use it e.g. to save differing settings. As such, you have the possibility of setting different layouts depending on your needs.
|====

=== Export purchase history

Use the *Export purchase history* function to create a one-time record of information on the items you sold in your online store so far. YOOCHOOSE will use this information to create reliable recommendations out of the box.

[IMPORTANT]
.Only export purchase history once
====
Only run the *Export purchase history* function once at the very start of your cooperation with YOOCHOOSE. Providing YOOCHOOSE with the purchase history more than once will result in incorrect recommendations.
====

[.instruction]
Exporting the purchase history:

. Go to *System » System settings » Client » Select client » Services » Yoochoose*.
. Click on the *Purchase history* tab.
. Select the purchase history period to export.
. Click on the *gear-wheel icon* to export the data. +
→ The data will be transferred to YOOCHOOSE. +
*_Tip:_* YOOCHOOSE does not import data instantaneously. YOOCHOOSE will let you know when the import is complete.

=== Retrieving statistics

Proceed as described below to retrieve a list of events and clicks associated with YOOCHOOSE.

[.instruction]
Retrieving statistics:

. Go to *System » System settings » Client » Select client » Services » Yoochoose*.
. Open the *Statistics* tab. +
→ The statistics are shown in chronological order.

=== Relevant template variables and template functions

==== Container_YOOCHOOSE_Recommendations

*Container_YOOCHOOSE_Recommendations* corresponds to the template *Container_ItemViewCrossSellingItemsList* or *Container_ItemViewCrossSellingItemsList2*. However, it only uses the items that were recommended by YOOCHOOSE.

==== Link_CrossSellingItem()

The target of the link corresponds to the template function *Link_Item()*. However, an additional parameter is added here, which identifies the viewed items as cross-selling items after the link was clicked on. That is necessary for the collection of data for YOOCHOOSE, but it can also be used for other applications. The parameter that was transferred is called *from_crossselling* and it has the value *1*.

==== Additional mandatory parameters for the template function Link_CrossSellingItem()

These additional mandatory parameters for the template function Link_CrossSellingItem() ensure that categories are transferred correctly. Note that the code may neither contain spaces nor line breaks.

*[Link_CrossSellingItem()_]&amp;yc1=[Request_CategoryId_Level1]&amp;yc2=[Request_CategoryId_Level2]&amp;yc3=[Request_CategoryId_Level3]&amp;yc4=[Request_CategoryId_Level4]&amp;yc5=[Request_CategoryId_Level5]&amp;yc6=[Request_CategoryId_Level6]*

==== Additional mandatory parameters for the template function Link_Item()

These additional mandatory parameters for the template function Link_Item() ensure that categories are transferred correctly. Note that the code may neither contain spaces nor line breaks.

*{% Link_CrossSellingItem($_itemID) %}&amp;yc1=$Request_CategoryId[Level1]&amp;yc2=$Request_CategoryId[Level2]&amp;yc3=$Request_CategoryId[Level3]&amp;yc4=$Request_CategoryId[Level4]&amp;yc5=$Request_CategoryId[Level5]&amp;yc6=Request_CategoryId[Level6]*

The parameters for *Link_Item()* have to be supplemented in the store layout in all item lists (e.g. ItemViewCategoriesList).
