Items are managed centrally in plentymarkets. In other words, you’ll enter your product information into plentymarkets and then you’ll be able to sell your items on various <<markets#, markets>>, in your own <<online-store#, online store>> and in your <<pos#, brick and mortar store>>.

If you need to make any changes in the future, e.g. edit an item’s price or description, then you’ll only have to modify this data centrally in plentymarkets. The data will automatically be changed on all of your sales channels.

[#100]
== Introducing the item structure

Are you new to plentymarkets? Before you start entering data, learn how items are structured! The introduction teaches you about the topic and answers your basic questions:

* What’s the difference between <<item/introduction/structure#, items and variations>>?
* How does <<item/introduction/inheritance#, inheritance>> work?
* How do I <<item/introduction/search#100, search for items>>?
* Can I also see a few <<item/introduction/search#900, example items>>?

[#200]
== Preparatory settings

Items are made up of lots of information, e.g. categories, prices, manufacturers, descriptive texts and images. But sometimes a little preliminary work is necessary.

Before you can sort an item into a specific category, the category first needs to exist in plentymarkets. Before you can select an item’s manufacturer, the manufacturer data needs to exist in plentymarkets.

//Link ##<<vorbereitenden Einstellungen>>## ändern sobald neue Seiten-Struktur steht
Once you’ve saved such <<item/managing-items#, preparatory settings>> in plentymarkets, you’ll be able to apply them to all of the relevant items and variations.

[#300]
== Importing, exporting and manually creating items

//Link <<Assistenten>> ändern sobald neue Seiten-Struktur steht. Prüfe auf dieser Seite und Basis-Seite, dass die Assistenten richtig benannt wurden.
Ready to start entering item data into plentymarkets? There are several different tools for doing so. The easiest way is to import item and variation data with an <<basics/assistants#, assistant>>.

//Link <<artikel/artikel-verwalten#20, manuell in plentymarkets zu erstellen>> ändern sobald neue Seiten-Struktur steht
But it’s also possible to <<item/managing-items#20, manually create items in plentymarkets>> or to send product information back and forth between your own plentymarkets system and other external systems. For example, item data records can be:

* imported from existing <<markets/ebay/ebay-setup#11000, eBay listings>>.
* managed in CSV files and imported with <<data/importing-data/ElasticSync#, ElasticSync>>.
* imported from other systems with the <<basics/admin-tasks/rest-api#, REST-API>>.
* exported out of plentymarkets with the <<data/exporting-data/FormatDesigner#, FormatDesigner>>.

[#400]
== Displaying items in your online store

Once you’ve saved your items in plentymarkets, you’re ready to start selling them. plentymarkets comes with a free <<online-store#, online store>>, which you can use to sell your products.

//Link <<artikel/best-practices#, Artikel und Kategorien nicht im Webshop angezeigt>> ändern sobald neue Seiten-Struktur steht
Turn to this chapter for help if your <<item/best-practices#, items and categories aren’t showing up in the online store>>. This chapter also shows you how to set up additional functions for displaying your items exactly how you want:

//Diese 3 Links anpassen, sobald neue Seiten-Struktur steht
* <<item/frontend-item-search#, Faceted search>>
* <<item/managing-items#950, Cross-selling>>
* <<item/managing-items#1010, Store specials>>

[#500]
== Use cases

Do you have a particular scenario in mind? In this chapter, you’ll learn how to:

//Diese 3 Links anpassen, sobald neue Seiten-Struktur steht
* <<item/managing-items#420, Manage item data in multiple languages>>
* <<item/combining-products#, Combine products>> and sell them as a unit
* <<item/managing-items#4300, Add give-aways or promotional gifts>> to an order
