////
zuletzt bearbeitet 02.03.2022
////

PIM stands for [.underline]##P##roduct [.underline]##I##nformation [.underline]##M##anagement.
The plentymarkets PIM lets you manage all of your item information in one central system.
In other words, you enter your product information into plentymarkets.
Then you can sell your items on various <<markets#, markets>>, in your own <<online-store#, plentyShop>> and in your <<pos#, brick and mortar store>>.

If you need to make any changes in the future, e.g. edit an item's price or description, then you'll only have to modify this data centrally in plentymarkets.
The data can automatically be changed on all of your sales channels.

[#100]
== Introducing the item structure

//tag::intro[]
Are you new to plentymarkets?
Before you start entering data, learn how items are structured!
The introduction teaches you about the topic and answers your basic questions:

* What’s the difference between <<item/introduction/structure#, items and variations>>?
* How does <<item/introduction/inheritance#, inheritance>> work?
* Where do I find my <<item/introduction/search#100, items in the back end>>?
* Can I also see a few <<item/introduction/search#900, example items>>?
//end::intro[]

[#200]
== Preparatory settings

//tag::preparatory-settings[]
Items are made up of lots of information, e.g. categories, prices and manufacturers.
But before you can sort an item into a specific category, the category first needs to exist in plentymarkets.
Before you can select an item’s manufacturer, the manufacturer data needs to exist in plentymarkets.
//end::preparatory-settings[]

Once you’ve saved such <<item/settings#, preparatory settings>> in plentymarkets, you’ll be able to apply them to all of the relevant items and variations.

include::../../introduction/structure.adoc[tag=system-settings-list]

[#300]
== Import, export and manual processing

//tag::import-export-create[]

Ready to start entering item data into plentymarkets?
Or do you want to send product information back and forth between your own plentymarkets system and other external systems?
There are many options for importing, exporting and manually editing item data records.

[discrete]
==== Import

[cols="2*", width=100%, grid=cols, frame=none, stripes=none]
|====

a| *_Import tool_*:

* <<data/importing-data/ElasticSync#, General info about the import tool>>
* <<data/importing-data/elasticsync-best-practices/best-practices-elasticsync-creating-variations#, Practical example: Importing items and variations>>
* <<data/importing-data/sync-types/elasticSync-item#, Directory of all data fields for importing items>>

a| *_Other imports_*:

* <<welcome/assistants#, Importing items with the "Item import" assistant>>.
* <<markets/ebay/ebay-setup#11000, Importing items from existing eBay listings>>.
* <<data/rest-api#, Importing items from other systems with the REST-API>>.
|====

[discrete]
==== Export

[cols="2*", width=100%, grid=cols, frame=none, stripes=none]
|====

a| *_Catalogue tool_*:

* <<data/exporting-data/catalogues#, General info about the catalogue tool>>
* <<data/exporting-data/catalogues-item#, Directory of all data fields for exporting items (catalogue)>>

a| *_FormatDesigner + Elastischer Export_*:

* <<data/exporting-data/elastic-export#, General info about the Elastic Export>>
* <<data/exporting-data/FormatDesigner/format-types/item#, Directory of all data fields for exporting items (FormatDesigner)>>
|====

[discrete]
==== Manual processing

[cols="2*", width=100%, grid=cols, frame=none, stripes=none]
|====

a| *_New item UI_* +
*_(open beta)_*:

* <<item/new-ui/search#, Searching for items>>
* <<item/new-ui/detail-view#, Detail view: Design>>.

a| *_Old item UI_*:

* <<item/import-export-create/create/new-item#, Manually creating new items>>
* <<item/managing-items#, Directory of all item data fields>>
* <<item/import-export-create/create/mass-processing#, Editing multiple items at once>>
|====

//end::import-export-create[]

[#500]
== Use cases

//tag::use-cases[]
Do you have a particular scenario in mind?
In this chapter, you’ll learn how to:

//* Manage item data in multiple languages
* <<item/use-cases/combining-products#, Combine products>> and sell them as a unit
* Sell <<item/use-cases/personalised-items#, personalised items>> in your plentyShop
* <<item/use-cases/give-aways#, Add give-aways or promotional gifts>> to an order
* Work with items that have <<item/use-cases/serial-numbers#, serial numbers or license keys>>
* <<item/use-cases/changes#, Track changes to items>>, i.e. track the entire life cycle of an item
* Modify the <<item/use-cases/search-behaviour#, default item search behaviour>> in the plentymarkets backend
//end::use-cases[]

[#400]
== Appearance in the plentyShop

//tag::appearance-webshop[]
Once you’ve saved your items in plentymarkets, you’re ready to start selling them.
plentymarkets comes with a free <<online-store#, online store>>, which you can use to sell your products.

Turn to this chapter for help if your items or categories aren't displayed in the plentyShop.
This chapter also shows you how to set up additional functions for displaying your items exactly how you want:

* <<item/online-store/checklist-categories-visibility#, Category isn't visible in plentyShop>>
* <<item/online-store/checklist-items-visibility#, Item isn't visible in plentyShop>>
* <<item/online-store/search-bar#, Search bar>>
* <<item/frontend-item-search#, Search filters>>
* <<item/online-store/cross-selling#, Cross-selling>>
* <<item/online-store/store-specials#, Store specials>>
//end::appearance-webshop[]
