= Webshop sperren
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, Webshop sperren
:position: 40

Mit der Funktion **Webshop jetzt sperren** stellen Sie Ihren Mandanten während der Einrichtung unsichtbar. Besuchern eines gesperrten Webshops wird ein Wartungshinweis angezeigt. Auch wenn Sie später umfangreiche Änderungen an Ihrem Webshop vornehmen möchten, können Sie Ihren Webshop sperren und Kunden so auf den Wartungshinweis umleiten. Vergessen Sie jedoch nicht, Ihren Webshop nach Abschluss der Arbeiten wieder zu entsperren, sonst erhalten Sie keine Bestellungen mehr!

[TIP]
.Tipp
====
Erstellen Sie bei umfangreichen Änderungen eine Kopie Ihres Designs und arbeiten Sie in der Kopie. So können Sie bei Bedarf das ursprüngliche Design wieder verwenden. Starten Sie den Webshop nach jeder Wartung über die Standard-URL in einem anderen Browser und prüfen Sie alle Änderungen gründlich.
====

== Webshop sperren

Gehen Sie wie unten beschrieben vor, um den Webshop zu sperren.

[.instruction]
Webshop sperren:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Webshop » Webshop sperren**.
. Klicken Sie auf **Webshop jetzt sperren**. +
→ Der Webshop wird gesperrt und ist nur noch über direkte Produkt-Links oder das URL-Suffix **/index.php** erreichbar. +
**__Tipp:__** Wenn Sie den Standard-Mandanten sperren, werden alle Mandanten des Shops gesperrt.

[IMPORTANT]
.Gesperrter Webshop nicht per REST-API erreichbar
====
Wenn Sie einen Webshop sperren, ist die Kommunikation mit dem plentymarkets System per REST-API nicht möglich.
====

== Webshop entsperren

Gehen Sie wie unten beschrieben vor, um den Webshop zu entsperren.

[.instruction]
Webshop entsperren:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Webshop » Webshop sperren**.
. Klicken Sie auf **Webshop jetzt entsperren**. +
→ Der Webshop wird entsperrt und ist für Besucher wieder erreichbar.

