= Automation
:lang: de
include::{includedir}/_header.adoc[]
:position: 140
:url: automation
:id: KM681RQ
:nav-alias: Overview
:author: team-docs-automation

Automate your daily tasks! plentymarkets includes three different tools that help you automate your routine business processes.

Learn about the three different tools in a playful introduction:

.Automate your day-to-day tasks
video::198165819[vimeo]

== Procedure manager

In plentymarkets, you can use the <<automation/procedure-manager#, procedure manager>> to automatically complete routine tasks at a specific time every day.

For example, you can <<automation/best-practices-automation#_practical_examples_procedure_manager, use the procedure manager>> to set a time each day when non-paying eBay or store customers should receive a payment reminder or dunning letter. The reminder will then be automatically sent by email.

== Event procedures

<<automation/event-procedures#, Event procedures>> are easy to understand: specific *_events_* in your online store trigger specific *_procedures_*.

For example, you can <<automation/best-practices-automation#_practical_examples_event_procedures, use event procedures>> to send emails to your customers. Use event procedures to configure such automatic tasks and have plentymarkets complete them reliably.

== Prozesse

Use <<automation/processes/setting-up-processes#, processes>> to automate complex tasks in plentymarkets.

For example, you can use processes to pick and pack items in your warehouse.
