= CMS
:lang: en
include::{includedir}/_header.adoc[]
:position: 150

**plentymarkets » CMS**

==  Content of this chapter

This chapter teaches you how to arrange your online store and customize its design to meet your needs. For further information, refer to the <<cms/web-design#, **Web design**  >> section. +
The CMS chapter also includes information about working with the <<cms/image-gallery#, **image gallery**  >>. Use the image gallery to upload images that should be displayed in your online store. Images can be grouped together there and managed in folders.

Use the **<<cms/webspace#, Webspace tool  >>** to save elements for your design, e.g. images, logos or JavaScript files. Elements are managed there on the file level.

The <<cms/documents#, **Documents**  >> page shows you another way to make files available to your customers. Here you will learn how to upload documents and link them to E-mails.

The <<cms/blog-weblog#, **Blog**  >> page teaches you how to set up a blog in your online store.

The <<cms/faqs#, **FAQ**  >> page shows you how to set up a list of __**Frequently Asked Questions**__ in your online store.

This chapter also teaches you how to configure <<crm/sending-newsletters#, **newsletters**  >> that are sent automatically and that help you reach a wide range of potential customers.

==  Web design in plentymarkets

This section teaches you how to work with the integrated __**Content Management System**__. It shows you how to edit **templates** and thus customize the design for your online store. Furthermore, you will learn how to use wildcard characters to insert content into your online store. Wildcard characters make it possible to edit the content dynamically. For example, you can use wildcard characters to display item prices and availabilities. Use <<cms-syntax/basics/if#, **if queries**  >> to make case-by-case decisions. Procedures will then be carried out on an if-then basis.

Format your online store with **CSS** and make changes to the design with only a few clicks of the mouse.

For further information, refer to the <<cms/web-design#, **Web design**  >> page of the manual.

==  Direct access to important pages of the manual

* <<cms/web-design#, **Web design**  >>
* <<cms/web-design/user-interface#, **User interface**  >>
* <<cms/web-design/basic-information-about-syntax#, **Basic information about syntax**  >>
* <<cms-syntax/basics/if#, **if queries**  >>
* <<cms/web-design/basic-information-about-syntax/displaying-lists#, **Displaying lists**  >>
* **<<cms/web-design/editing-the-web-design#, Editing the web design  >>**
* <<cms/best-practice/ssl-encryption#, **SSL encryption**  >>
* <<cms-syntax/web-design/pagedesign/link-ajaxbasket#, **Shopping cart with Ajax**  >>

