= CRM
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Managing customer data, using the ticket system, sending emails
:description: Learn how to manage your customer data, how to use the ticket system for your customer communication and how to send emails and newsletters.
:position: 60
:nav-alias: Overview

In this area, you will find all information about creating and editing <<crm/managing-contacts#100, contact data records>> - from the address via orders to tickets, documents, <<basics/statistics/customer-statistics#, statistics>> etc. Create <<crm/managing-contacts#15, customer classes>>, <<crm/managing-contacts#20, customer types>> and use the <<crm/managing-contacts#25, discount system>> in plentymarkets.

Furthermore, learn how to use the <<crm/using-the-ticket-system#, ticket system>> for your customer communication and how to retain control over orders that are still unpaid with the help of the <<crm/managing-contacts#5200, AR list>>.

All emails that are sent with plentymarkets are based on email templates. You can define up to two attachments for each email template. In this area, you will learn how to <<crm/sending-emails#1200, create email templates>>.

Set up a <<crm/sending-newsletters#, newsletter>> in order to inform your customers at regular intervals about news in your online store. For this purpose, you can set up the newsletter that is integrated in plentymarkets or you set up an interface to <<crm/sending-newsletters#1700, CleverReach>> or <<crm/sending-newsletters#2100, Newsletter2Go>>.

Learn more about customer data and email templates in the following video tutorials:

[.row]
====
[.col-md-6]
=====
video::145369998[vimeo]
=====

[.col-md-6]
=====
video::181592415[vimeo]
=====
====

[.row]
====
[.col-md-6]
.Managing customer data
=====
* <<crm/managing-contacts#15, Creating a customer class>>
* <<crm/managing-contacts#20, Creating a customer type>>
* <<crm/managing-contacts#100, Creating a contact>>
* <<crm/managing-contacts#5200, Displaying the accounts receivable list>>
* <<crm/managing-contacts#25, Using the discount system>>
=====

[.col-md-6]
.Using the ticket system
=====
* <<crm/using-the-ticket-system#700, Adding a role>>
* <<crm/using-the-ticket-system#800, Adding a type>>
* <<crm/using-the-ticket-system#900, Adding a status>>
* <<crm/using-the-ticket-system#1100, Adding a topic>>
* <<crm/using-the-ticket-system#1600, Creating a ticket>>
=====
====

[.row]
====
[.col-md-6]
.Sending emails
=====
* <<crm/sending-emails#100, Saving the email server's access data>>
* <<crm/sending-emails#200, Selecting the encryption for email communication>>
* <<crm/sending-emails#1200, Creating an email template>>
* <<crm/sending-emails#1300, Using template variables and template functions>>
=====

[.col-md-6]
.Sending newsletters
=====
* <<crm/sending-newsletters#100, Using the integrated newsletter>>
* <<crm/sending-newsletters#2100, Using Newsletter2Go>>
* <<crm/sending-newsletters#1700, Using CleverReach>>
=====
====
