= CRM
:lang: en
include::{includedir}/_header.adoc[]
:keywords: customer data, contact data, ticket system, emails, email, EmailBuilder, newsletter, quick search, messenger, messages, companies, company
:description: Learn how to manage your contact and company data, use the ticket system for your customer communication and send emails and newsletters.
:position: 50
:url: crm
:id: IWIIOPV
:nav-alias: Overview
:author: team-crm

In this area, you find all information about creating and editing <<crm/managing-contacts#100, contact data records>> – from the address via orders to tickets, documents and much more. Create <<crm/managing-contacts#15, customer classes>>, <<crm/managing-contacts#20, types>> and use the <<crm/managing-contacts#25, discount types>> in plentymarkets. Manage your <<crm/companies#, companies>> and link contacts with the companies.

Use the <<crm/quick-search#, quick search>> to retrieve at a glance all information that is saved for a contact or the address data of a guest order. In this area, you can also download - in accordance with GDPR - all data that is saved for a contact or a guest order and anonymise data records.

Use the <<crm/messenger#, messenger>> to create messages that can be assigned to your contacts. Messages are only visible in your plentymarkets back end and cannot be accessed by your contacts.

All emails that are sent with plentymarkets are based on email templates. Learn how to <<crm/sending-emails#1200, create email templates>> and how to <<crm/sending-emails#2300, set up the automatic despatch>> for your email templates. Use the <<crm/emailbuilder-test-phase#, new EmailBuilder>> to create your templates even faster and more intuitive.

Furthermore, learn how to use the <<crm/using-the-ticket-system#, ticket system>> for your customer communication and how to retain control over orders that are still unpaid with the help of the <<crm/ar-list#, AR list>>.

Set up a <<crm/sending-newsletters#, newsletter>> service in your system to automatically inform your customers at regular intervals about news in your plentyShop.

[.row]
====
[.col-md-6]
.Managing contacts and companies
======
* <<crm/managing-contacts#15, Creating a customer class>>
* <<crm/managing-contacts#20, Creating a customer type>>
* <<crm/managing-contacts#100, Creating a contact>>
* <<crm/managing-contacts#300, Editing a contact>>
* <<crm/managing-contacts#25, Using the discount system>>
* <<crm/ar-list, Showing the accounts receivable list>>
* <<crm/companies#, Managing companies>>
======

[.col-md-6]
.Sending emails
======
* <<crm/sending-emails#100, Saving the email server's login details>>
* <<crm/sending-emails#200, Selecting the encryption for email communication>>
* <<crm/sending-emails#1200, Creating an email template>>
* <<crm/emailbuilder-test-phase#, Creating an email template with the new EmailBuilder>>
======
====

[.row]
====
[.col-md-6]
.Using the ticket system
======
* <<crm/using-the-ticket-system#700, Adding a role>>
* <<crm/using-the-ticket-system#800, Adding a type>>
* <<crm/using-the-ticket-system#900, Adding a status>>
* <<crm/using-the-ticket-system#1100, Adding a topic>>
* <<crm/using-the-ticket-system#1600, Creating a ticket>>
======

[.col-md-6]
.Setting up newsletters
======
* <<crm/sending-newsletters#, Sending newsletters>>
======
====

[.row]
====
[.col-md-6]
.Finding data records
======
* <<crm/quick-search#, Using the quick search>>
======

[.col-md-6]
.Managing messages
======
* <<crm/messenger#, Using the messenger>>
======
====
