= Data exchange
:lang: en
include::{includedir}/_header.adoc[]
:position: 90
:nav-alias: Overview

This area deals with exchanging data in plentymarkets. Data can be exchanged automatically or manually. Use the SOAP API or sub-menus in the **Data exchange** menu to exchange data between your plentymarkets system and external systems. The REST API can be used for automatic data exchange. The **Data exchange** menu is used to manually transfer data. <<basics/data-exchange/api-log#, Log entries>> in the API log help you keep track of any data you exchanged.

video::126357396[vimeo]
You can also use the data exchange to quickly and easily make changes and adapt settings within your plentymarkets system. Simply export the data of your items, customers, stocks or orders into a CSV file, make changes to the data and import the file back into the system.

[.row]
====
[.col-md-4]
.Manual data exchange
=====
* <<data/export-import/data-formats#, Data formats>>
* <<data/export-import/exporting-data#, Exporting data>>
* <<data/export-import/importing-data#, Importing data>>
=====

[.col-md-4]
.Interfaces
=====
* link:http://showcase.plentymarkets.com/[REST API^]
* *Deprecated*: link:{imagesdir}/basics/assets/SOAP-Version-200-Documentation-2016-07-14.zip[SOAP API]
=====

[.col-md-4]
.Viewing protocols
=====
* <<data/api-log#, API log>>
=====
====
