= Glossary
:lang: en
include::{includedir}/_header.adoc[]
:description: Glossary for plentymarkets
:position: 300
:!sectnums:
:url: glossary

[glossary]
== A

[glossary]
[#accounts-receivable-list]
Accounts receivable list:: Contains an overview of customers with unpaid orders (number of claims plus total pending amount).

[#attribute]
Attribute:: Some items like shoes and t-shirts are sold in various sizes and colours. In plentymarkets, such characteristics are called attributes. Attributes help you simultaneously characterise your products and create saleable <<#variation, variations>>, e.g. the t-shirt in the colour red and the size S. +
* For further information, refer to the <<item/settings/attributes#, Attribute>> page. +
* Synonyms: Characteristics

[#auction]
Auction:: A <<#listing, listing>> type. Auctions are possible on the marketplaces eBay, Hood and ricardo. *Auction* type listings start at a predefined price, then customers bid on the item.

[glossary]
== B

[glossary]
[#backend]
Back end:: The part of the system where functions are saved and are available for users.

[#back-end-plugin-set]
Back end plugin set:: A <<plugin-set,plugin set>> that’s linked to a user account. The <<plugin,plugins>> that are included in the plugin set can add menus and functions to the <<backend,back end>>. Every user account is always linked to exactly one plugin set.

[#barcode]
Barcode:: Barcodes are used to uniquely identify items. They are often displayed e.g. on item labels or on documents like invoices and delivery notes. There are different types of barcodes, e.g. GTIN, ISBN, UPC or QR barcodes. +
* For further information, refer to the <<item/settings/barcodes#, Barcodes and labels>> page.

[#beta]
beta:: A development state of plentymarkets. Normally, functionality is first published on this version. If no problems are identified, the functionality is published on <<#early, early>>. +
* For further information, refer to the <<basics/admin-tasks/version-cycle#, Changing state of development>> page.

[#box-picking]
Box picking:: Method of combining items from multiple orders. Multiple orders are brought to the packing table picked, packed and pre-sorted for shipping at the same time.

[#box-storage-rack]
Box storage rack:: Box storage racks in plentymarkets are a kind of interim storage for multi order picking and are only available in <<automation/processes/procedures#, processes>>. Thus, when picking stock, the items are not sorted immediately, but gathered in a box storage rack. +
* For further information, refer to the <<app/functions/warehouse-management/mobile-box-picking#, Mobile box picking>> page.

[#bundle]
Bundle:: See <<#item-bundle, item bundle>>.

[glossary]
== C

[glossary]
[#calculation-type]
Calculation type:: Is used in the <<#table of shipping charges, table of shipping charges>> of a <<#shipping profile, shipping profile>>. Offers different ways of calculating the shipping costs for an item, depending on, for example, weight, quantity or price. +
* For further information, refer to the <<fulfillment/preparing-the-shipment#1600, Preparing the shipment>> page.

[#cash-deposit]
Cash deposit:: Physical complement of the cash on hand in the checkout area in order to have change available. <<pos/plentymarkets-pos-for-pos-users#190, Cash deposits>> are booked in the plentymarkets App or in the back end and can be assigned to different booking accounts.

[#cash-journal]
Cash journal:: Contains all available POS movements and can be exported in PDF or CSV formats. You can search and view POS transactions in the <<pos/integrating-plentymarkets-pos#400, cash journal>>.

[#cash-on-delivery]
Cash on delivery:: Payment method which you can offer in your online store. The shipping service provider transports the packages to the addressee and takes care of the payment transaction. The addressee only receives their package after having paid for it.

[cash-withdrawal]
Cash withdrawal:: Physical reduction of available cash, for example when transferring cash amounts from the till to other accounts. <<pos/plentymarkets-pos-for-pos-users#200, Cash withdrawals>> are booked in the plentymarkets app or in the plentymarkets back end and can be assigned to different booking accounts.

[#category]
Category:: plentymarkets categories can be used either to _group items_ or to create _content pages_ for your online store. The category type determines how the category can be used. +
* For further information, refer to the <<item/settings/categories#, Categories>> page.

[#check-digit]
Check digit:: The final number of a GTIN <<#barcode, barcode>>.

[#click-and-collect]
Click & Collect:: This method allows the the customer to pay and collect items that have been ordered via the online store or via marketplaces directly in the <<pos/integrating-plentymarkets-pos#4100, retail shop>>.

[#client]
Client:: An entity of plentymarkets. You can, for instance, link a client with a domain in order to operate an <<#online-store, Online store>>. It is possible to manage multiple clients with one system.

[#colli]
Colli:: Load unit for the transport of goods. More specifically, it is the packing unit of piece goods, thus, the smallest unit of a goods shipment. The entry Colli: 7 e.g. means that the package consists of 7 units.

[#coupon]
Coupon:: One of two coupon types available in plentymarkets. Offers customers a discount in your online store. +
The other available coupon type is a <<#voucher, voucher>>. +
A coupon has a code which belongs to a <<#coupon-campaign, coupon campaign>> and which can be redeemed either once or multiple times. Coupons can be emailed to customers as special offer codes or gift cards can be sold as items in your online store. If sold as an item, customers receive the coupon in a PDF document. +
* For further information, refer to the <<orders/coupons#, Coupons>> page of the manual.

[#coupon-campaign]
Coupon campaign:: Each coupon belongs to a specific campaign. The campaign allows you to centrally manage coupons, e.g. how long coupons of this campaign are valid or how often they can be redeemed. +
* For further information, refer to the <<orders/coupons#, Coupons>> page of the manual.

[#cross-selling]
Cross-selling:: In cross-selling, customers are subtly encouraged to spend more money. This is done by offering additional products that relate to the purchased product. The salesman in an electronics store for example suggests a memory card that would work with the digital camera.
* For further information, refer to the <<item/webshop/cross-selling#, Cross-selling>> page.

[#customer-class]
Customer class:: Allows you to divide your customer base into subgroups based on specific criteria. Afterwards, you can define different discounts for the different customer classes. +
* For further information, refer to the <<crm/managing-contacts#15, Managing contacts>> page.

[#customer-type]
Customer type:: Allows you to classify and differentiate contacts. Some types are defined in the system by default. You can add your own types. +
* For further information, refer to the <<crm/managing-contacts#20, Managing contacts>> page.

[glossary]
== D

[glossary]
[#days-early-payment-discount]
Days for early payment discount:: Number of days when the contact can pay the pending amounts at a discounted price.

[#default-client]
Default client:: The <<#client, client>> that is related to the contract of the system. Some functions can only be accessed via the main client. These are, for example, event procedures and REST API calls.

[#delivery-list]
Delivery list:: Contains the package number, the delivery address, the amount of the order as well as the order ID. When picking up the packages, the driver of the shipping service provider signs the list. Thus, it also serves as a pick-up receipt.

[#dep-export]
DEP export:: Data collection protocol that is provided as JSON file. In Austria, it is required by law to make the <<pos/pos-legal-compliance#900, DEP export>> available for every cash register.

[#drop-shipping]
Drop shipping:: A model where stock is delivered from the manufacturer directly to the customer, without passing through the warehouse of the seller at any time. The seller assumes an intermediary function and buys the items directly from the manufacturer.

[glossary]
== E

[glossary]
[#early]
early:: A development state of plentymarkets. Functionality is published on this version if no problems were detected on <<#beta, beta>>. If no problems are detected on this version either, the functionality is published on <<#stable, stable>>. +
* For further information, refer to the <<basics/admin-tasks/version-cycle#, Changing state of development>> page.

[#elasticsync]
ElasticSync:: Tool for carrying out data imports by creating so-called syncs. A data import can be carried out manually or automatically. It is recommended to carry out an import if new data are already available in digital form. +
* For further information, refer to the <</data/importing-data/ElasticSync#, Importing data with ElasticSync>> page.

[#event-procedure]
Event procedure:: Event procedures are a tool to automatise different parts of order processing. With an event procedure, an event triggers a procedure: _If x happens, y is triggered_. One example of a frequently used event procedure is sending an order confirmation via email as soon as a new order has been created or placed by customers via the online store. The procedures that are triggered can be specified by using filters within the event procedure. +
* For further information, refer to the <<automation/event-procedures#, Event procedures>> page.

[glossary]
== F

[glossary]
[#faceted-search]
Faceted search:: Facets are filter options that are used to make search results in the online store more precise based on specific criteria (facets). For example, search results can be made more precise so that they only contain a certain price range, brand names, sizes or colours. +
* For further information, refer to the <<item/frontend-item-search#, Search function in the online store>> page. +
* Synonyms: Facet navigation, filter search, item search

[#favicon]
Favicon:: An icon or symbol used to mark websites in browser tabs or in the list of browser bookmarks. The favicon is saved in .ico format. The favicon is either saved in the <<online-store/setting-up-ceres#20, Ceres configuration>> or in the Ceres assistant.

[#fixed-price]
Fixed price listing:: <<#listing, Listing>> offered at a fixed price and not up for auction.

[#flag]
Flag:: Flags are visual helpers. They help you find the right item at a glance. Assign one or two flags to each item. You can see these flags when you access your items in the plentymarkets back end.  You can also search for items that are marked with a specific flag or a combination of flags. +
* For further information, refer to the <<item/settings/flags#, Tags and flags>> page.

[#formatdesigner]
FormatDesigner:: Tool used for creating so-called data formats for data exports. The FormatDesigner plugin has to be installed and set up before creating export formats. +
* For further information, refer to the <<data/exporting-data/FormatDesigner#, FormatDesigner>> page.

[#frontend]
Front end:: Contains all content that is visible to customers, such as the online store.

[#fulfilment]
Fulfillment:: Term that describes all activities and processes carried out after the purchase of items to arrange for delivery and comply with further contractual obligations.

[glossary]
== G

[#gift-card]
Gift card:: One of the two varieties of the coupon type *Coupon*. When redeeming a gift card, the coupon value is subtracted from the total amount including VAT. +
The other available coupon variety is the <<#promotional coupon, promotional coupon>>. The other available coupon type in plentymarkets is the <<#voucher, voucher>>.

[#graduated-price]
Graduated price:: A series of prices that are based on a different factor, usually the number of items ordered. For example, you may sell an item for EUR 5.00 per unit. When a customer purchases 3 or more units of the item, you can reduce the price to EUR 4.00 per unit. +
* For further information, refer to the <<item/settings/prices#, Sales prices and price calculation>> page.

[glossary]
== I

[glossary]
[#idea-export]
IDEA export:: An export of all POS transactions that complies with the GoBD and can be requested by German tax officers as part of a tax audit. The export files can be downloaded as a ZIP file for individual years.

[#incoming-items]
Incoming items:: Items are booked in to the system and stock is increased. +
* For further information, refer to the <<stock-management/stock-management/new-incoming-items#, Managing incoming items>> page.

[#incoming-payment]
Incoming payment:: Term for an incoming payment for an order. Payments can either be booked automatically or manually and are recorded directly in the order.

[#inheritance]
Inheritance:: The <<#main-variation, main variation>> of an item differs from the child variations: The main variation can pass data on, i.e. other variations can _inherit_ its data. As such, the main variation is a parent variation that passes on certain settings to its children. By default, this inheritance function is active. When a new variation is created for an item, this variation inherits the inheritable settings of the main variation by default if no other data is saved. +
* For further information, refer to the <<item/introduction/inheritance#, Inheritance>> page.

[#insertion-fee]
Insertion fee:: See <<#listing-fee, Listing fee>>.

[#item]
Item:: Items can be thought of as _data containers_. They always include one or more <<#variation, variations>>, i.e. one or more saleable versions of a product. For example, if you sell a t-shirt in small, medium, and large, then all of these sizes together form the item. Each individual size is a variation of the item. +
* For further information, refer to the <<artikel/introduction/structure#, Items vs. Variations>> page. +
* Synonyms: Products, goods, commodities

[#item-bundle]
Item bundle:: A way to _combine products and sell them as a single unit_. Item bundles consist of several different <<#variation, variations>> that are grouped together and sold for a bundle price. Customers can only purchase the entire bundle as a whole. The individual components can not be chosen. Example: a kitchen starter set consisting of a pan, a pot and a spatula. +
* For further information, refer to the <<item/use-cases/combining-products#, Managing multipacks, item bundles and sets>> page. +
* Synonyms: Product bundles, package deals

[#item-pack]
Item pack:: See <<#item-bundle, item bundle>>.

[glossary]
== K

[#ktype]
K type number:: Unique number associated with exactly one vehicle from the TecDoc catalogue. eBay uses this number in their <<#parts-compatibility-listing, Parts compatibility listing>>. +
* Alternative spellings: KType, K-type

[glossary]
== L

[glossary]
[#list of delivery addresses]
List of delivery addresses:: Export file that includes shipment information you provide to the shipping service provider via which you ship your goods. The shipping service provider creates valid shipping labels for your packages on the basis of this information.

[#listing]
Listing:: The listing contains basic settings that are independent of the platform, for example settings for stock dependence and listing contents. Here, you can also define the listing type. The listing types are <<#fixed-price, Fixed price>>, <<#auction, Auction>> or <<#shop-item, Shop item>>. +
Each listing may be associated with multiple <<#market-listing, Market listings>>.

[#listing-fee]
Listing fee:: Fee that needs to be paid to eBay when listing an offer on eBay.
* Synonyms: Insertion fee

[#listing-template]
Listing template:: Template for listings. You can create a template using either the group function in the *Listings » Edit listings » Tab: Group function* menu or REST. A listing template contains settings for <<#listing, Listings>>, <<#market-listing, Market listings>> and actions for listings, as well as specific options for eBay, Hood, and ricardo. You can use the same template for any number of listings.

[#loyalty-program]
Loyalty program:: Can be used with eBay Plus or Amazon. Is activated in the <<#shipping-profile, shipping profile>>.

[glossary]
== M

[glossary]
[#main-variation]
Main variation:: The first <<#variation, variation>> of an item is called the main variation. If an item consists of more than one variation, the main variation can either be a sellable product or serve as a virtual data container only. A virtual main variation allows you to manage all child variations of the item using the <<#inheritance, inheritance>> feature.

[#mapping]
Mapping:: Determines which column of a CSV file equates with which data field in plentymarkets during a data import. +
* For further information, refer to the <<data/importing-data/ElasticSync#1500, ElasticSync>> page.

[#market-listing]
Market listing:: Offer on the marketplaces eBay, Hood, and ricardo. A market listing is always associated with exactly one <<#listing, Listing>>. Use the market listing for example for carrying out settings specific to a single marketplace.

[#master-data]
Master data:: Basic information of a user (for example contact information such as company name, address, telephone number, and so on).

[#matching]
Matching:: Specifies which data should be used to check whether a data record already exists when importing data. +
* For further information, refer to the <</data/importing-data/ElasticSync#, Importing data with ElasticSync>> page.

[#multi-order-picking]
Multi order picking:: Method of combining items from multiple orders. Multiple orders are processed at the same time. All items are commissioned in a single dispenser and only associated with a specific order at the packing table.

[#multipack]
Multipack:: A way to _combine products and sell them as a single unit_. Multipacks are different quantities of the same <<#variation, variation>>. Example: a single bottle of water, a six-pack of water and a pack containing 12 bottles. +
* For further information, refer to the <<item/use-cases/combining-products#, Managing multipacks, item bundles and sets>> page.

[glossary]
== O

[glossary]
[#online-store]
Online store:: Term for the plugin-based plentymarkets online store Ceres and its predecessor Callisto.

[#order-item]
Order item:: Order items indicate which items were ordered in which quantity and are thus assigned to an order. Order items can be viewed directly within an order in the back end. Furthermore, order items are also displayed on order documents such as order confirmations or invoices. +
* Synonyms: Variation, Stock unit

[#order-note]
Order note:: Is used for saving informational texts for an order.

[#outgoing-items]
Outgoing items:: Items are booked out of the system and stock is reduced. +
* For further information, refer to the <<stock-management/outgoing-items#, Booking items out>> page.

[glossary]
== P

[glossary]
[#package-number]
Package number:: Specific package number which contains the package’s status.

[#packing-list]
Packing list:: Overview of orders with all included order items and the order ID as barcode. Can be generated as PDF if a document template was set up.

[#pallet-type]
Pallet type:: For securing a load (e.g. pallet, container, etc.). Pallet types are used to combine small packing units or bulky items into a single shipment. For example, individual items are secured onto a pallet using foil and straps.

[#parts-compatibility-listing]
Parts compatibility listing:: With parts compatibility listings, you link the items that you want to sell to the correct vehicles. This increases your sales prospects since <<#listing, listings>> of parts compatibility listings have a higher ranking in the search results. Parts compatibility listings are used for vehicle parts and car accessories.

[#percentage-early-payment-discount]
Percentage for early payment discount:: Value in percent that the contact may subtract if they make the payment within the <<#day-early-payment-discount, days for early payment discount>>.

[#pick-list]
Pick list:: List for warehouse technicians for picking items. The list is a structured compilation of items which must be picked from the warehouse for shipping packages. It optimises transport routes and helps to manage picking items more efficiently.

[#pick-path]
Pick path:: The path which is taken through the warehouse during the picking process.

[#plentybase]
plentyBase:: A tool which must be installed in order to be able to use <<#process, processes>> and printers. The tool can be downloaded at link:https://marketplace.plentymarkets.com/en[plentyMarketplace^].

[#plugin]
Plugin:: An add-on for the plentymarkets system. Can be purchased at link:https://marketplace.plentymarkets.com/en[plentyMarketplace^] or via Git and the tools plentyDrive and plentyDevTool and can be integrated into the system.

[#plugin-set]
Plugin set:: A compilation of plugins. Can be linked with clients and <<#backend-plugin-set, backend user accounts>>.

[#pre-certified-online-store]
Pre-certified online store:: The standard Ceres online store is pre-certified by EHI and Trusted Shops. Thus, it is considerably faster and easier for users of the Ceres online store to have it certified by EHI and Trusted Shops.

[#price]
Price:: In plentymarkets, a distinction is made between _sales prices_ and _prices_. In contrast to this abstract concept of a sales price, the price is the actual monetary amount at which a variation is sold if the conditions defined by the <<#sales-price, sales price>> are met. This price is applied, i.e. the customer can buy the variation at that price, if the conditions defined for the sales price are met. +
* For further information, refer to the <<item/settings/prices#, Sales prices and price calculation>> page.

[#price-calculation]
Price calculation:: Price calculations allow you to calculate and update the <<#price, prices>> of variations automatically based on specific criteria. Users can add several costs saved for a variation to a sales price, e.g. transportation costs, storage costs, customs, VAT. Furthermore, users can add individual amounts to the price or subtract them from the price, e.g. plus 5% or multiplied by 1,05. +
* For further information, refer to the <<item/settings/prices#, Sales prices and price calculation>> page.

[#process]
Process:: Functionality within the plentymarkets backend which serves to automate workflows and consists of different steps. It is required to install <<#plentybase, plentyBase>> in order to use the processes.

[#promotional-coupon]
Promotional coupon:: One of the two varieties of the coupon type *Coupon*. Grants a discount. When using a promotional coupon, the coupon value is subtracted first and the remaining amount is then taxed. +
The other available coupon variety is the <<#gift-card, gift card>>. The other available coupon type in plentymarkets is the <<#voucher, voucher>>. +
* For further information, refer to the <<orders/coupons#, Coupons>> page of the manual.

[#property]
Property:: Some items stand out from the masses. It could be a waterproof watch or a speaker that is Bluetooth capable. In plentymarkets, these traits are called _characteristics_ and _properties_. They highlight the technical features of a product. The difference is that characteristics characterise whole items, whereas <<#property, properties>> characterise specific variations. Characteristics and properties also differ from <<#attribute, attributes>>, since both characterise products _without_ creating saleable variations. +
* For further information, refer to the <<items/settings/properties#, Characteristics and properties>> page. +
* Synonyms: Characteristics

[glossary]
== R

[glossary]
[#redemption]
Redemption:: The redemption of a <<#voucher, voucher>> happens during the order process. The corresponding discount value is directly displayed. +
* For further information, refer to the <<orders/coupons#, Coupons>> page of the manual.

[#reorder]
Reorder:: A reorder is the process of ordering stock from a supplier. In the back end, this process is carried out via reorders. There are multiple ways to create reorders, for instance through editing an order. You can create reorders for each individual warehouse or supplier. +
* For further information, refer to the <<stock-management/managing-reorders/wotking-with-reorders#, Working with reorders>> page.

[#reorder-level]
Reorder level:: The quantity at which a reorder should be placed. With reorder levels, you will be automatically notified whenever you need to reorder individual items. You can choose between static and dynamic reorder levels.

[#return-label]
Return label:: Included in a package. When returning a package, for example because of warranty or repairs, customers only have to package the item and affix the label.

[#return-slip]
Return slip:: Used by customers to label items for return. Can either be included in the package or printed by the customer once the corresponding document template is saved in the system.

[glossary]
== S

[glossary]
[#sales-price]
Sales price:: In plentymarkets, a distinction is made between _sales prices_ and _prices_. Sales prices are data containers. They allow for the central management of all conditions regarding prices. Thus, sales prices define in which situations variations are sold for a specific <<#price, price>>. +
* For further information, refer to the <<item/settings/prices#, Sales prices and price calculation>> page.

[#sales-representative]
Sales representative:: A freelance commercial agent who negotiates deals or procures business for a company.

[#serial-number]
Serial number:: Serial numbers are alphanumeric strings that provide a unique identifier for an item. Serial numbers make it possible to trace sold items in case errors or problems occur, and make it easier to find stolen or forged products. Examples for serial numbers include cards, electronics and household appliances. +
* For further information, refer to the <<item/use-cases/serial-numbers#, Serial numbers>> page.

[#set]
Set:: A way to _combine products and sell them as a single unit_. Item sets contain various <<#item, items>>. It’s possible to select a <<#variation, variation>> for each item. For example, a kitchen starter set contains one pan (either red or black), a pot (either silver or black) and a slotted turner (either made out of plastic or wood). +
* For further information, refer to the <<item/use-cases/combining-products#, Managing multipacks, item bundles and sets>> page.

[#shipping order]
Shipping order:: The order which is registered with a shipping provider.

[#shipping-profile]
Shipping profile:: Contains shipping combinations which customers can either select in the checkout or which are already assigned automatically to specific order types. For example, payment methods or customer classes can be deleted or extra charges for islands saved in the shipping profile. Those extra charges apply whenever a delivery to an island, e.g. Helgoland, is made. This means that additionally to the shipping costs a surcharge is due. +
* For further information, refer to the <<fulfilment/preparing-the-shipment#1000, Preparing the shipment>> page.

[#shop-item]
Shop item:: Listing type for the Hood marketplace. The item is offered in the Hood store.

[#single-order-picking]
Single order picking:: Method of combining items from multiple orders. Each order is handled and processed separately.

[#stable]
stable:: A development state of plentymarkets. Functionality is published on this version if no problems were detected on <<#early, early>>. +
* For further information, refer to the <<basics/admin-tasks/version-cycle#, Changing state of development>> page.

[#stock]
Stock:: Quantity of goods currently available in the warehouse. +
* For further information, refer to the <<stock-management/managing-stocks#, Managing stock>> page.

[#stock-turnover-days]
Stock turnover (in days):: The period in days that the stock of a specific variation will suffice until the next reorder.

[#storage-location]
Storage location:: Specific spot where an item is located (e.g. Storage building 1, rack 4, shelf 2, storage location 6).

[#store-special]
Store special:: A way of highlighting specific items in the online store. Used, for example, to mark individual items as best sellers, special offers or new items. +
* For further information, refer to the <<item/online-store/store-specials#, Store specials>> page.

[glossary]
== T

[glossary]
[#table-of-shipping-charges]
Table of shipping charges:: Contains the shipping costs of the <<#shipping-profile, shipping profile>>. Shipping costs must be saved for each region contained in the shipping profile. This includes each country of delivery which was activated and possibly summarised as one region along with other countries of delivery. +
* For further information, refer to the <<fulfillment/preparing-the-shipment#1500, Preparing the shipment>> page.

[#tag]
Tag:: Tags make it possible to emphasise certain data records. Tags can be used for variations, contact data records, orders, tickets, and many more. +
* For further information, refer to the <<basics/working-with-plentymarkets/tags#, Tags>> page.

[#template-function]
Template function:: Pre-defined function for email templates. When the email is sent, the function is automatically replaced with the actual URL, e.g. the URL that leads to the basket (`{%Link_Basket()%}`) or to the terms and conditions of the online store `{%Link_TermsConditions()%}`). +
* For further information, refer to the <<crm/sending-emails#4100, Sending emails>> page.

[#template-variable]
Template variable:: Pre-defined variable for email templates. When the email is sent, the variable is automatically replaced with the actual content when the corresponding requirements are met. For example, the variable `$OrderID` returns the ID of the order and the variable `$CustomerFullName` returns the first name and the last name of the contact. +
* Synonyms:  +
* For further information, refer to the <<crm/sending-emails#4200, Sending emails>> page.

[#till-count]
Till count:: A till count documents the current cash on hand of a till. The cash on hand is counted physically and the result is entered into the plentymarkets App. <<pos/plentymarkets-pos-for-pos-users#450b, Till count reports>> can be printed and are saved in the document archive.

[#traits]
Traits:: See <<#attribute, Attribute>>, <<#characteristic, Characteristic>> <<#property, Property>>.

[glossary]
== U

[glossary]
[#unit-price]
Unit price:: The price of an item per pound, litre or other unit. For example, this price is indicated for products offered in supermarket shelves. The unit price is calculated based on the <<item/settings/unit#, unit>>, content and price of the item. Unit prices can be displayed in the online store, on markets such as eBay or Netto, and on item labels.

[glossary]
== V

[glossary]
[#variation]
Variation:: A sellable version of a product. For example, if you sell a shirt in small, medium and large, then each size is a variation of this shirt. All sizes together form the <<#item, item>>. +
* For further information, refer to the <<artikel/introduction/structure#, Items vs. Variations>> page.

[#vat-number]
VAT number:: Value added tax number. Unique identifier of a person or company subject to turnover tax within the European Union for turnover tax purposes.

[#voucher]
Voucher:: One of two coupon types available in plentymarkets. They are redeemed through third parties, e.g. hotel business. +
The other available coupon type is the <<#coupon, coupon>>.

[glossary]
== W

[glossary]
[#warehouse]
Warehouse:: A space for storing goods. For example, a warehouse can be a storehouse equipped with racks. These racks are divided into shelves and the shelves are divided into specific storage locations.

[glossary]
== X

[glossary]
[#x-report]
X report:: Contains various information about the turnover generated by a POS system since the last Z report. <<pos/plentymarkets-pos-for-pos-users#210, Reports>> are not deposited as documents in the plentymarkets back end and do not count as tax records.

[glossary]
== Z

[glossary]
[#z-report]
Z report:: Documents the POS revenue accrued since the last Z report. Depending on local law, the saving of <<pos/plentymarkets-pos-for-pos-users#230, Z reports>> may be required for fiscal purposes.
