= Orders
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Managing orders, Order types, Accounting, Documents, Taxes
:description: Learn how to set up your accounting and document templates and how to manage orders in plentymarkets.
:position: 60
:nav-alias: Overview

This area contains all information about incoming orders and how to proceed after receiving orders. Depending on the sales strategy and markets you choose, orders from different *<<orders/order-referrer#, referrers>>* are transferred to your plentymarkets system. Apart from your own online store, order referrers are primarily the different *<<omni-channel/multi-channel#, markets>>*. +

Among others, plentymarkets offers you an extensive interface to *<<omni-channel/multi-channel/amazon/amazon-setup#, Amazon>>*. This interface does not only include automatic synchronisation with *<<omni-channel/multi-channel/amazon/amazon-setup#900, Seller Central>>*, but also further services offered by Amazon such as *<<omni-channel/multi-channel/amazon/amazon-setup#3300, Fulfilment by Amazon>>* and *<<omni-channel/multi-channel/amazon/amazon-setup#3700, Amazon Multi-Channel>>*. +

Thanks to the comprehensive *<<omni-channel/multi-channel/ebay/ebay-setup#, eBay>>* interface integrated in plentymarkets, you can start listings and display eBay shop items on eBay, retrieve orders, automatically post feedback and start dunning procedures for customers ordering via eBay. +

Incoming orders are collected in one menu and displayed in a consistent format so that you can easily manage these orders. Each order receives an individual **Order ID**. Additional steps taking place after incoming orders, such as sending the order confirmation, sending emails or generating invoices and delivery notes, can be automatised. In addition to main orders representing orders placed by customers, several other *order types* exist in plentymarkets. Order types represent different business transactions. +

The following order types are available in plentymarkets:

 * Order
 * Offer
 * Advance order
 * Warranty
 * Credit note order
 * Delivery order
 * Repair
 * Return
 * Multi-order
 * Multi credit note

Documents necessary for a quick fulfilment process, such as *<<orders/order-documents/pick-list#, pick list>>* and *<<orders/order-documents/packing-list#, packing list>>* are available in plentymarkets as well.

Use the <<fulfilment/shipping-centre#700, Shipping centre>> to register shipping orders, edit them if needed of search for particular shipping orders.

In order to manage orders and business transactions efficiently in your plentymarkets system, you can also create *<<automation/processes/setting-up-processes#, Processes>>* and have them run automatically. Processes offer the highest potential of automation for your plentymarkets system.
