= Payment
:lang: en
include::{includedir}/_header.adoc[]
:description: Payment in plentymarkets: Manage payments and integrate payment methods and payment providers.
:position: 70
:url: payment
:id: EJC9AQU
:nav-alias: Overview
:keywords: payment, payments, managing payments, payment processing
:author: team-fulfillment-payment

One important aspect of your online shop is the selection of payment methods offered. If the right selection is missing, customers could cancel the purchase at the end of the order process or not order in your online shop at all. To avoid this, you should find out which payment methods your customers prefer to use. This area of the manual describes how to set up payment methods and payment providers in plentymarkets.
Moreover, options and functionalities as well as working with payments, currencies and bank data are explained.

[.row]
====
[.col-md-6]
.Managing payment methods
=====
* <<payment/managing-payment-methods#, Managing payment methods>>
* <<payment/managing-payment-methods#25, Specifying the default payment method>>
* <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>>
* <<payment/managing-payment-methods#50, Offering a discount based on the payment method>>
* <<payment/managing-payment-methods#65, Overview of payment methods in the system>>
* <<payment/managing-payment-methods#70, Payment methods for markets>>
=====

[.col-md-6]
.Payments and banking in general
=====
* <<payment/beta-managing-payments#, Managing payments>>
* <<payment/beta-managing-payments#30, Assigning payments>>
* <<payment/beta-managing-payments#20, Searching for payments>>
* <<payment/managing-bank-details#, Managing bank details>>
* <<payment/managing-bank-details#70, Setting up EBICS>>
* <<payment/managing-bank-details#200, Setting up SEPA direct debit mandate>>
* <<payment/currencies#, Managing currencies>>
=====
====

[#400]
== Payment providers and payment methods

Various payment providers and payment methods are available. They are integrated into your plentymarkets system via individual plugins. Downloaded the plugins from the link:https://marketplace.plentymarkets.com/en/plugins/payment/payment-integrations[plentyMarketplace^] to install them into your system.
