= plentymarkets 7
:lang: en
include::{includedir}/_header.adoc[]
:position: 10

This chapter of the manual provides important information about migrating to plentymarkets 7 and about the tasks that need to be completed before the migration. It also includes an overview of all the changes. +
This page of the manual lists areas that have not yet been migrated in plentymarkets 7. As previously announced, our software developers are happy to answer any of your questions about the new item architecture. You can also use our forum to send them feedback.

toc::[]
== Migration status of Markets

We have already migrated the most relevant markets to plentymarkets 7. Of course, we will make all of the markets available in plentymarkets 7 as soon as possible. Markets that are integrated into plentymarkets via SOAP will not be available until we have finished migrating the SOAP area. The following table provides you with an overview of which markets have already been migrated and which ones will be available soon.

[cols="a,a,a"]
|====
|Migrated |Will be migrated soon |Will be migrated along with SOAP

|Amazon (except for BMVD) +
Allyouneed +
Cdiscount +
DaWanda +
eBay +
Flubit +
Fruugo +
Gimahhot +
Hitmeister +
Hood +
Kauflux +
La Redoute +
Mercateo +
OTTO +
Plus.de +
Rakuten +
ricardo +
Shopgate +
Yatego +
Price comparsion portals
| Amazon BMVD +
Neckermann +
PIXmania +
Zalando
| grosshandel.eu +
Hertie +
Restposten.de +
SumoNet
|====

__Table 1: migration status of each market__

== Mention interface information

The mention interface has not yet been migrated to match plentymarkets 7.

