= Point of sale system
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, POS, point of sale, plentymarkets point of sale, point of sale system, plentymarkets app, coupons, coupon point of sale, click and collect, click & collect
:position: 120
:url: pos
:nav-alias: Overview
:id: 8OEUR6U

[#100]
== What is plentymarkets POS?

plentymarkets POS (*Point of Sale*) is our in-house developed solution for managing till sales at your brick and mortar store. The plentymarkets POS functionalities are integrated as a component that is part of 
the link:https://knowledge.plentymarkets.com/en/app[plentymarkets app^].
This manual page offers you an overview on where to find information on setting up plentymarkets POS and using its functionalities to their best.

[TIP]
.POS demo mode
====
Are you interested in using plentymarkets POS and want to take a look at its functions without any obligation? Check out our detailed instructions on using the plentymarkets POS demo mode <<pos/demo#, here>>.
====

[#200]
== How do you set it up?

Have you already decided to use plentymarkets POS as your point of sale system for your brick and mortar store? Great! Take a look at the following pages to find further instructions as well as information on how to contact our specialised service partners.

* link:https://plentypos.plentymarkets.com/en/[Choosing suitable hardware^]
* <<pos/integrating-plentymarkets-pos#, Integrating plentymarkets POS>>
* <<pos/plentymarkets-pos-for-pos-users#, plentymarkets POS for POS users>>

[#300]
== How many functions does it include?

Once completely set up, your plentymarkets POS system offers you a variety of possibilities for managing your daily business in your brick and mortar store. Depending on how exactly you would like to work with the system, the following functions are available:

** <<pos/plentymarkets-pos-for-pos-users#30, Ringing up customers>>
** <<pos/integrating-plentymarkets-pos#2700, Selling and redeeming gift cards and coupons>>
** <<app/functions/item-search#4400, Printing item labels>>
** <<pos/plentymarkets-pos-for-pos-users#173, Cancellations and returns>>
** <<pos/integrating-plentymarkets-pos#4100, Completing click and collect orders>>
** <<pos/plentymarkets-pos-for-pos-users#180, Withdrawing or depositing cash into the cash drawer>>
** <<pos/plentymarkets-pos-for-pos-users#210, Creating Z reports and till count reports>>

In addition, there are legal regulations and specific exports that you need to take into account when using plentymarkets POS:

** <<pos/integrating-plentymarkets-pos#300, Documenting POS transactions for German tax authorities>>
** <<pos/integrating-plentymarkets-pos#910, Operating plentymarkets POS in Austria>>
** <<pos/integrating-plentymarkets-pos#1090, Creating IDEA exports>>
** <<pos-integrating-plentymarkets-pos#950, Saving booking accounts for POS events>>


[#400]
== Stay up to date

Are you looking forward to an upcoming feature? We’re happy to keep you in the loop about changes to the software! You can see a record of changes link:https://forum.plentymarkets.com/c/changelog/changelog-app[in our changelog^]. Subscribe to the changelog and always stay up to date.
