= Point of sale system plentyPOS
:lang: en
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: plentyPOS overview, POS functions
:position: 120
:url: pos
:nav-alias: Overview
:id: 8OEUR6U

[#100]
== What is plentyPOS?

plentyPOS (*Point of Sale*) is our in-house developed solution for managing till sales at your brick and mortar store. The plentyPOS functionalities are integrated as a component that is part of 
the link:https://knowledge.plentymarkets.com/en/app[plentymarkets app^]{nbsp}icon:external-link[].
This manual page offers you an overview on where to find information on setting up plentyPOS and using its functionalities to their best.

[TIP]
.POS demo mode
====
Are you interested in using plentyPOS and want to take a look at its functions without any obligation? Check out our detailed instructions on using the plentyPOS demo mode <<pos/demo#, here>>.
====

[#200]
== How do you set it up?

Have you already decided to use plentyPOS as your point of sale system for your brick and mortar store? Great! Take a look at the following pages to find further instructions as well as information on how to contact our specialised service partners.

* link:https://plentypos.plentymarkets.com/en/[Choosing suitable hardware^]{nbsp}icon:external-link[]
* <<pos/integrating-plentymarkets-pos#, Integrating plentyPOS>>
* <<pos/plentymarkets-pos-for-pos-users#, plentyPOS for POS users>>

[#300]
== How many functions does it include?

Once completely set up, your plentyPOS system offers you a variety of possibilities for managing your daily business in your brick and mortar store. Depending on how exactly you would like to work with the system, the following functions are available:

** <<pos/plentymarkets-pos-for-pos-users#30, Ringing up customers>>
** <<pos/integrating-plentymarkets-pos#2700, Selling and redeeming coupons>>
** <<app/functions/item-search#400, Printing item labels>>
** <<pos/plentymarkets-pos-for-pos-users#173, Managing cancellations>>
** <<pos/plentymarkets-pos-for-pos-users#175, Booking returns>>
** <<pos/pos-online-ordders#, Completing Click & Collect orders>>
** <<pos/plentymarkets-pos-for-pos-users#180, Withdrawing or depositing cash into the cash drawer>>
** <<pos/plentymarkets-pos-for-pos-users#210, Creating Z reports, X reports and till count reports>>

In addition, there are legal regulations and specific exports that you need to take into account when using plentyPOS:

** <<pos/pos-legal-compliance#100, Documenting POS transactions for German tax authorities>>
** <<pos/pos-legal-compliance#1000, Operating plentyPOS in Austria>>
** <<pos/pos-legal-compliance#300, Creating IDEA exports>>
** <<os/pos-legal-compliance#950, Creating a DSFinV-K export>>
** <<pos/integrating-plentymarkets-pos#950, Saving booking accounts for POS events>>


[#400]
== Stay up to date

Are you looking forward to an upcoming feature? We’re happy to keep you in the loop about changes to the software! You can see a record of changes link:https://forum.plentymarkets.com/c/changelog/changelog-app[in our changelog^]{nbsp}icon:external-link[]. Subscribe to the changelog and always stay up to date.
