= Stock management
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Stock, Stock management
:position: 40
:url: stock-management
:id: 200DET3
:nav-alias: Overview

The stock management integrated in plentymarkets helps you to keep track of your current stock, your incomming items as well as outgoing items. The stock management allows you to manage several warehouses, to reserve stock as well as to automate stock update.
In this topic, you find all information about creating and editing warehouses, booking and assigning stock as well as reordering items.
You need to register stock quantities if you want to work with stock reservations and if you want that items are automatically subtracted from your stock as soon as they are booked out. Stock reservations are made to avoid that items are sold twice or more.

The points listed below give you a rough idea of the steps that are necessary to set up the stock management in plentymarkets:

* Creating warehouses
* Creating suppliers
* Booking incoming items
* Creating reorders

There are many factors that influence a well-functioning stock management. Some of these factors are e.g. defining reorder levels for variations and knowing your suppliers minimum order quantity, keeping track of your stock quantities as well as reordered and returned items and regular stocktaking. Another factor is the reservation of stock for listings - that you can use in plentymarkets. How to reserve stock for listings is explained on the pages dealing with listing platforms. There are many more topics that are connected to stock management e.g. how pick lists are created. However, topics that have less to do with juggling interactive stock quantities and are more related to someone actually carrying out a task like picking items from a pick list and handing packages over to shipment providers are all covered under Fulfillment.

[.row]
====
[.col-md-6]
.Planing and setting up warehouses
=====
* <<stock-management#100, **Planing a warehouse**>>
* <<stock-management#200, **Creating a warehouse**>>
* <<stock-management#700, **Preparing the packing process**>>
* <<stock-management#800, **Making storage location scannable**>>
=====

[.col-md-6]
.Registering and booking item quantities
=====
* <<crm/managing-contacts#20, Creating suppliers>>
* <<stock-management/new-incoming-items#100, Assigning suppliers to variations>>
* <<stock-management/new-incoming-items#200, Specifying the storage location of a variation>>
* <<stock-management/new-incoming-items#500, Registering incoming items and their quantities>>
* <<stock-management/new-incoming-items#1200, Adding stock to variations>>
* <<stock-management/managing-stocks#1300, Overlooking item movements caused by incoming items>>
=====

[.col-md-6]
.Overlooking and reordering stock
=====
* **<<stock-management/managing-stocks#100, Which stock types exist?>>**
* **<<stock-management/managing-stocks#200, When is stock reserved?>>**
* **<<stock-management/managing-stocks#500, Redistributing stock>>**
* **<<stock-management/managing-reorders#500, Defining reorder levels for variations>>**
* **<<stock-management/managing-reorders#600, Defining minimum reorder quantities for variations>>**
* **<<stock-management/managing-reorders#300, Creating a reorder document>>**
* **<<stock-management/managing-reorders#900, Reordering variations that are below the reorder level>>**
* **<<stock-management/managing-reorders#1800, Cancelling reordered items>>**
// TODO: fix links
* **link:/[Dividing reorders into work steps]**
* **link:/[Checking incoming item supply]**
* **link:/[Carrying out stocktaking]**
=====

[.col-md-6]
.Booking items out
=====
* **<<stock-management/outgoing-items#2, Booking outgoing items automatically>>**
* **<<stock-management/outgoing-items#3, Editing cancellations, returns or warrenties>>**
* **<<stock-management/outgoing-items#4, Booking outgoing items manually>>**
=====
====

'''
