= Verpackungseinheiten entpacken
:lang: de
include::{includedir}/_header.adoc[]
:position: 30

Was ist entpacken?

* VPE-Varianten können nur über die plentymarkets Prozesse eingebucht werden.
* Varianten können nur über die plentymarkets App entpackt werden.
* Die Namen für VPEs werden automatisch vergeben.

* Beispiel “P24K4” für 1 Palette mit 24 Kartons a 4 Stück




== Verpackungseinheiten über die plentymarkets App entpacken (ab App-Version 1.XX)

Entpacken bedeutet, dass Sie eine Variante, die aus einer größeren Verpackungseinheit besteht, in kleinere Verpackungseinheiten auflösen. Sie können nur den Bestand von Varianten entpacken, die eine Elternvariante haben. Beim Entpacken wird der Bestand der Kindvariante ausgebucht. In einem zweiten Schritt wird der Bestand der Kindvariante auf die Elternvariante umgebucht. Wenn die Kindvariante zum Beispiel eine Palette ist, wird durch das Entpacken aus diesem Bestand "1 Palette" der Bestand "36 Kartons". Dieser neue Bestand wird dann auf die Elternvariante gebucht.

[#xxx]
=== Berechtigungen für Entpacken erteilen

Benutzerinnen und Benutzer mit Admin-Rechten dürfen standardmäßig Verpackungseinheiten über die App entpacken. Benutzerinnen und Benutzer der Benutzerklasse *Variabel* und *Logistik* müssen Sie die Berechtigung dafür erteilen, Verpackungseinheiten zu entpacken.

[.instruction]
Berechtigungen für das Entpacken erteilen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer*.
. Öffnen Sie das Benutzerkonto.
. Wechseln Sie in das Tab *Berechtigung*. +
*_Tipp:_* Wenn dieses Tab nicht sichtbar ist, hat das Benutzerkonto Admin-Rechte.
. Öffnen Sie das Tab *Mobile*.
. Aktivieren Sie im Bereich *Sichtbare Funktionen* die Berechtigung *Entpacken*.
. *Speichern* Sie die Einstellungen.


=== Verpackungseinheiten über die plentymarkets App entpacken

Gehen Sie wie unten beschrieben vor, um Verpackungseinheiten über die plentymarkets App zu entpacken.

[TIP]
.Lagerorte labeln
====
Noch schneller entpacken Sie Verpackungseinheiten, wenn Sie Ihre <<warenwirtschaft/lager-einrichten#800, Lagerorte labeln>>. Beim Entpacken können Sie dann die Labels der Quell- und Ziellagerorte scannen.
====

[.instruction]
Ware über die plentymarkets App entpacken:

. Öffnen Sie die plentymarkets App.
. Tippen Sie in der Menüleiste auf das *Menüsymbol*.
. Tippen Sie auf *Entpacken*. +
→ Die Variantensuche wird angezeigt.
. Geben Sie ein Suchkriterium ein.
. Tippen Sie auf *Suchen*. +
→ Die gefundenen Varianten werden angezeigt. +
*_Hinweis:_* Nur Varianten mit Elternvariante werden angezeigt.
. Tippen Sie auf die Variante. +
*_Tipp:_* Bei einem eindeutigen Suchergebnis wird die Variante automatisch geöffnet. +
??? → In der Ansicht *XXXX* wird die Bestandsmenge der Variante pro Lagerort angezeigt.
??? . Tippen Sie auf den grünen Balken des Lagerorts, aus dem der Bestand entfernt werden soll. +
??? *_Tipp:_* Wenn Sie gelabelte Lagerorte haben, scannen Sie stattdessen das Label des Lagerorts. Dazu bei Bluetooth-Scannern vorher in das Feld *Barcode* tippen. +
??? → Im Bereich *XXXX* werden Lagerort und Bestandsmenge angezeigt.
??? . Tippen Sie auf den grünen Balken des Lagerorts, in den der Bestand gebucht werden soll. +
??? *_Tipp:_* Wenn Sie gelabelte Lagerorte haben, scannen Sie stattdessen das Label des Lagerorts. Dazu bei Bluetooth-Scannern vorher in das Feld *Barcode* tippen. +
??? → Wenn für die Variante im neuen Lager Mindesthaltbarkeitsdaten und/oder Chargeninformationen gepflegt werden, diese Daten jedoch im alten Lager nicht erfasst wurden, werden Sie aufgefordert, diese Daten einzugeben.
??? . *_Optional:_* Wählen Sie das Mindesthaltbarkeitsdatum und/oder geben Sie die Charge ein und tippen Sie auf *Umbuchen*. +
??? → Der Bestand wird entpackt.


// =============== UMBUCHEN ===================



== Ware über die plentymarkets App umbuchen

Ab plentymarkets 7 kann Ware auch über die plentymarkets App umgebucht werden. Erteilen Sie dazu Benutzern der Benutzerklasse *Variabel* und *Logistik* die nötigen Berechtigungen. Mit Umbuchungsvorlagen und App-Einstellungen passen Sie den Umbuchungsvorgang an Ihre Lagergegebenheiten an.

[TIP]
.Hardware für plentymarkets App
====
Hardware-Empfehlungen für das Umbuchen von Ware über die plentymarkets App finden Sie auf der Handbuchseite <<erste-schritte/systemvoraussetzungen#_warenbestand_mit_der_plentymarkets_app_verwalten, Systemvoraussetzungen>>.
====

=== Berechtigungen für Umbuchen erteilen

Anwender mit Admin-Rechten haben standardmäßig die Berechtigung, Umbuchungen über die App vorzunehmen. Benutzern der Benutzerklasse *Variabel* und *Logistik* müssen Sie diese Berechtigungen erteilen.

[.instruction]
Benutzern Berechtigungen für das Umbuchen erteilen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer*.
. Öffnen Sie das Konto des Benutzers.
. Wechseln Sie in das Tab *Berechtigung*. +
*_Tipp:_* Wenn dieses Tab nicht sichtbar ist, hat der Benutzer Admin-Rechte.
. Öffnen Sie das Tab *Mobile*.
. Aktivieren Sie im Bereich *Sichtbare Funktionen* die Berechtigung *Umbuchung*.
. *Speichern* Sie die Einstellungen.

=== Umbuchungsvorlage erstellen

Im plentymarkets Backend erstellen Sie beliebig viele Vorlagen für das Umbuchen über die plentymarkets App. Über diese Vorlagen definieren Sie, die Felder und Feldanordnung, die Benutzern beim Umbuchen in der App angezeigt werden.

[TIP]
.Standardvorlage
====
Wenn Sie keine Vorlage erstellen, wird automatisch die Standardvorlage gewählt.
====

[.instruction]
Vorlage für Umbuchen über App erstellen:

. Öffnen Sie das Menü *System » plenty App » Umbuchung*.
. Klicken Sie auf *Neue Vorlage*. +
→ Das Fenster *Neue Vorlage* wird angezeigt.
. Geben Sie einen Namen für die Vorlage ein.
. *Speichern* Sie die Einstellungen. +
→ Die Vorlage wird erstellt und zur weiteren Bearbeitung geöffnet.
. Wählen Sie, wie Variantendaten in der *Artikelansicht* dargestellt werden. Beachten Sie <<tabelle-umbuchen-vorlage>>.
. Wählen Sie, wie Variantendaten in der *Artikellistenansicht*, also in der Liste der Suchergebnisse, dargestellt werden. Beachten Sie <<tabelle-umbuchen-vorlage>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-umbuchen-vorlage]]
.Vorlage für Umbuchen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Beschreibung*
|Beschreibung des Felds eingeben. Diese Beschreibung wird Benutzern als Name des Felds angezeigt. Wenn keine Beschreibung eingegeben wird, wird keine Beschreibung angezeigt. +
*_Beispiel:_* Wenn für *Barcode* die Beschreibung *Barcode* eingegeben wird, wird beim Umbuchen in der App *Barcode: 12345* angezeigt. Wenn die Beschreibung leer bleibt, wird nur *12345* angezeigt.

|*Zeile*
|Wählen, in welcher Zeile die Variantendaten angezeigt werden oder *Nicht anzeigen* wählen, um die Daten nicht anzuzeigen.

|*Zeilenpriorität*
|Wählen, in welcher Reihenfolge die Variantendaten angezeigt werden. Variantendaten mit Priorität *1* werden ganz oben angezeigt.

|*Spalte*
|Wählen, wie die Variantendaten innerhalb des Suchergebnisses angezeigt werden. +
*Links* = Die Daten werden in der linken Spalte angezeigt. +
*Rechts* = Die Daten werden in der rechten Spalte angezeigt. +
*Ganze Zeile* = Die Daten werden über die gesamte Breite angezeigt.

|*Schriftgröße*
|Schriftgröße aus der Dropdown-Liste wählen, in der die Variantendaten angezeigt werden. Verfügbare Größen sind *XS* bis *XXL*.

|*Schriftstil*
|In das Feld klicken und in der Auswahlliste die Formatierung aktivieren, in der die Variantendaten angezeigt werden.

|Spezifische Einstellungen
|*Artikelpreis » Preisauswahl* = Verkaufspreis aus der Dropdown-Liste wählen. +
*Barcode » Barcode-Auswahl* = Barcode-Typ aus der Dropdown-Liste wählen. +
*Artikelbild » Bildgröße* = Größe wählen, in der das Artikelbild angezeigt wird. Verfügbare Größen sind *XS* bis *L*. +
|====


=== Umbuchen über die plentymarkets App personalisieren

In der plentymarkets App können Benutzer weitere Einstellungen vornehmen, um den Umbuchungsvorgang zu personalisieren.

[.instruction]
Umbuchen über die plentymarkets App personalisieren:

. Melden Sie sich bei der plentymarkets App an.
. Tippen Sie in der Menüleiste auf das *Menüsymbol*.
. Tippen Sie auf *Einstellungen*.
. Tippen Sie auf *Umbuchung*. +
→ Das Einstellungsmenü *Umbuchung* wird angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie <<tabelle-umbuchung-app-einstellungen>>. +
*_Tipp:_* Die Einstellungen werden gespeichert, wenn Sie das Menü verlassen.

[[tabelle-umbuchung-app-einstellungen]]
.Umbuchung; App-Einstellungen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Artikelsuchfelder*
|Suchfelder aktivieren, die im Menü *Umbuchung* angezeigt werden. +
*_Tipp:_* Reihenfolge, in der die Suchfelder angezeigt werden, über die Pfeile links neben Suchfeldname festlegen. Auf Pfeil nach oben tippen, um Suchfeld eine Ebene höher zu schieben. Auf Pfeil nach unten tippen, um Suchfeld eine Ebene tiefer zu schieben.

|*Fokus auf Suchfeld*
|Auf das Suchfeld tippen, in das der Cursor beim Öffnen des Menüs automatisch springt. Wenn kein Suchfeld gewählt wird, muss  bei der Suche jedes Mal in ein Feld getippt werden, bevor der Suchwert eingegeben werden kann.

|*Lagerortvorschlagsliste*
|Wählen, welche Lagerorte als Ziellagerorte vorgeschlagen werden. +
*_Tipp:_* Reihenfolge, in der die Lagerortvorschläge angezeigt werden, über die Pfeile links neben Lagerortvorschlag festlegen. Auf Pfeil nach oben tippen, um Lagerortvorschlag eine Ebene höher zu schieben. Auf Pfeil nach unten tippen, um Lagerortvorschlag eine Ebene tiefer zu schieben. +
*Lagerortvorschlag* = Zeigt die Lagerorte an, die mit der Variante verknüpft sind. +
*Verwendete Lagerorte* = Zeigt die Lagerorte an, in denen die Variante bereits lagert. +
*Leere Lagerorte* = Zeigt alle vorhandenen leeren Lagerorte an. +
*_Hinweis:_* Je nach Anzahl der Lagerorte kann die Einstellung *Leere Lagerorte* das Umbuchen stark verlangsamen. Daher Varianten mit Lagerorten verknüpfen und *Leere Lagerorte* nur im Ausnahmefall aktivieren.

2+|Von Lagerort umzubuchende Menge

|*Gesamtmenge vorschlagen*
|Wählen, ob die Gesamtmenge der Variante für die Umbuchung vorgeschlagen wird. +
Nicht aktiviert = Keine Menge wird vorgeschlagen. Die Menge muss manuell eingegeben werden. +
Aktiviert = Der gesamte Bestand am Lagerort wird automatisch eingefügt.

|*Fokus auf Ziel-Lagerort setzen*
|Aktivieren, um nach Auswahl der Variante automatisch in das Eingabefeld *Lagerort* zu springen.

|*Schnelles Umbuchen*
|Aktivieren, um die Auswahl des Quelllagerorts zu überspringen. +
*_Tipp:_* Option nur aktivieren, wenn es nur einen möglichen Quelllagerort gibt.

|*Netto-WB anzeigen*
|Aktivieren, um beim Umbuchen in der App den Netto-Warenbestand am Quelllagerort anzuzeigen. +
Deaktiviert = Beim Umbuchen in der App wird nur die physikalische Menge des Artikels am Quelllagerort angezeigt. +
Aktiviert = Beim Umbuchen in der App wird die physikalische Menge und der Netto-Warenbestand des Artikels am Quelllagerort angezeigt.

|*Vorlage*
|Auf die Vorlage tippen, die verwendet werden soll. +
Vorlagen werden im plentymarkets Backend im Menü *System » plentymarkets-App » Umbuchung* erstellt.
|====

=== Ware über die plentymarkets App umbuchen

Gehen Sie wie unten beschrieben vor, um Ware über die plentymarkets App umzubuchen.

[TIP]
.Lagerorte labeln
====
Noch schneller buchen Sie Ware um, wenn Sie Ihre <<warenwirtschaft/lager-einrichten#800, Lagerorte labeln>>. Beim Umbuchen können Sie dann die Labels der Quell- und Ziellagerorte scannen.
====

[.instruction]
Ware über die plentymarkets App umbuchen:

. Öffnen Sie die plentymarkets App.
. Tippen Sie in der Menüleiste auf das *Menüsymbol*.
. Tippen Sie auf *Umbuchung*. +
→ Die Variantensuche wird angezeigt.
. Geben Sie ein Suchkriterium ein.
. Tippen Sie auf *Suchen*. +
→ Die gefundenen Varianten werden angezeigt.
. Tippen Sie auf die Variante. +
*_Tipp:_* Bei eindeutigem Suchergebnis wird die Variante automatisch geöffnet. +
→ In der Ansicht *Artikel zum Umbuchen* wird die Bestandsmenge der Variante pro Lagerort angezeigt.
. Tippen Sie auf den grünen Balken des Lagerorts, aus dem der Bestand entfernt werden soll. +
*_Tipp:_* Wenn Sie gelabelte Lagerorte haben, scannen Sie stattdessen das Label des Lagerorts. Dazu bei Bluetooth-Scannern vorher in das Feld *Barcode* tippen. +
→ Im Bereich *Umbuchen von* werden Lagerort und Bestandsmenge angezeigt.
. *_Optional:_* Bearbeiten Sie die Menge, die umgebucht werden soll.
. Tippen Sie auf den grünen Balken des Lagerorts, in den der Bestand gebucht werden soll. +
*_Tipp:_* Wenn Sie gelabelte Lagerorte haben, scannen Sie stattdessen das Label des Lagerorts. Dazu bei Bluetooth-Scannern vorher in das Feld *Barcode* tippen. +
→ (Ab Version 1.7.11) Wenn für die Variante im neuen Lager Mindesthaltbarkeitsdaten und/oder Chargeninformationen gepflegt werden, diese Daten jedoch im alten Lager nicht erfasst wurden, werden Sie aufgefordert, diese Daten einzugeben.
. (Ab Version 1.7.11) *_Optional:_* Wählen Sie das Mindesthaltbarkeitsdatum und/oder geben Sie die Charge ein und tippen Sie auf *Umbuchen*. +
→ Der Bestand wird umgebucht.



// ================== Anwendungsfall // Best Practice =================


In plentymarkets können Sie


== Anwendungsfall

Sie verkaufen Katzenfutter.
Sie verkaufen Katzenfutter an große und an kleine Kunden.
Sie verkaufen Paletten mit Katzenfutter.
Sie verkaufen Kartons mit Katzenfutter.
Sie verkaufen Dosen mit Katzenfutter.

plentymarkets erlaubt es Ihnen, denselben Artikel, also das Katzenfutter, in verschiedenen Verpackungseinheiten zu verkaufen. Sie können also eine Palette mit Katzenfutter direkt als eine Variante einbuchen und im Webshop anbieten.

Um diese Möglichkeit in der Artikelstrukur abzubilden, erstellen Sie einen Artikel mit Varianten. Der Einzelartikel (1 Dose Katzenfutter) ist die Hauptvariante. Der Karton ist eine Kindvariante der Hauptvariante. Die Palette wiederum ist eine Kindvariante der Variante mit dem Bestand Karton.

Nun kann es sein, dass Sie Ihr Katzenfutter von verschiedenen Lieferanten beziehen. Dadurch kann die Anzahl der Dosen pro Karton und/oder die Anzahl der Kartons pro Palette je nach Palette unterschiedlich sein.
