= Lager einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Lager planen, Lager einrichten, Lagereinstellungen
:position: 10

In diesem Kapitel werden die Einstellungs- und Bearbeitungsmöglichkeiten für Lager beschrieben.
Sie erfahren, wie Sie ein neues Lager anlegen, um in Ihrem plentymarkets System Ihr Lager 1:1 nachzubilden.
Außerdem erfahren Sie, wie Sie Box-Regale als Zwischenlager für Sammelkommissionierungen erstellen.

* Eine optimale Einrichtung des Lagers ist entscheidend für den Versandprozess und hilft Ihnen, Zeit zu sparen.
Nehmen Sie sich also vorab Zeit, um Ihr Lager sinnvoll und wegeoptimiert abzubilden.
* Um alle Tools, z.B. auch das Tool link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentyBase^], optimal zu nutzen, sollte jeder Lagerort mit einem **Label** mit Barcode versehen werden.

[IMPORTANT]
.Mindestens ein Lager wird zur Bestandspflege und für Aufträge benötigt
====
Jedes System hat zu Beginn 2 Beispiellager, ein Vertriebslager und ein zugehöriges Reparaturlager. Diese Lager können Sie umbenennen und weiter nutzen oder löschen und eigene Lager anlegen. Sie benötigen mindestens ein Lager in Ihrem System, um Wareneingänge zu buchen und Bestände zu pflegen. Ohne ein Lager können Sie also keine Bestände verwalten. Eingehende Aufträge werden je nach Artikelverfügbarkeit einem Lager zugeordnet.
====

[#100]
== Lager planen

Lager werden aus Dimensionen aufgebaut. Alle Dimensionen zusammen bilden das Layout Ihres Lagers. Die Dimensionen sind komplett frei-definierbar. Beim Anlegen der Dimensionen ist es jedoch wichtig, dass Sie Ihre kleinste Dimension als erstes erstellen und dann der Größe nach aufsteigend weitere Dimensionen erstellen.

[IMPORTANT]
.Beispieldimensionen übernehmen
====
In jedem Lager, egal ob Beispiellager oder neu-erstelltes Lager werden Ihnen im Layout 2 Beispieldimensionen angezeigt. Diese Dimensionen sind nicht gespeichert. Sie können die Dimensionen übernehmen, umbenennen oder entfernen. Zum Erstellen von Lagerorten benötigen Sie jedoch mindestens eine Dimension.
====

.Einteilung eines Lagers
[cols="1,2"]
|====
|Einstellung|Erläuterung

|**Dimension**
|Dimensionen bilden die grundsätzlichen Einteilungselemente Ihres Lagers. Aus den Dimensionen ergeben sich später die tatsächlichen Ebenen eines Lagers. Ebenen sind sozusagen die konkrete Anwendung einer Dimension. Wenn Sie z.B. eine Lagerhalle als Dimension in Ihrem Layout führen, stellen die Lagerhalle 1, Lagerhalle 2 und Lagerhalle 3 die konkrete Anwendung dar. +
_Hinweis_: Mindestens eine Dimension wird benötigt, um Lagerorte zu generieren.

|**Lagerort**
|Lagerorte sind in plentymarkets keine Dimension. Lagerorte sind der konkrete Ablageplatz, an dem Ihre Produkte liegen. Sie benötigen mindestens eine Dimension, um Lagerorte zu generieren. Die Dimension ist dem Lagerort übergeordnet.
|====

Eine wegeoptimierte Pickliste ergibt sich durch die Position der Lagerorte. Ob eine Dimension die Position von Lagerorten beeinflusst, bestimmen Sie durch Ihre Einstellung. Eine Pickliste beginnt mit der niedrigsten Position und wird aufsteigend sortiert.

== Lager einrichten

Das Einrichten eines Lagers gliedert sich in 3 grundsätzliche Schritte. Zunächst müssen Sie allgemeine Daten wie den Namen und Zweck des Lagers angeben. Anschließend pflegen Sie weitere allgemeine Daten, wie die Adresse des Lagers, ein. Im 2. Schritt richten Sie Dimensionen ein, in die Sie Ihr Lager unterteilen. Im letzten Schritt generieren Sie Ihre Lagerorte.

=== Allgemeine Lagerdaten pflegen

Egal, ob Sie die Beispiellager bearbeiten und zu Ihren Lagern machen oder ob Sie neue Lager hinzufügen, die folgenden Angaben pflegen Sie für jedes Lager.

[.instruction]
Neues Lager erstellen:

. Öffnen Sie das Menü **System » Waren » Lager**.
. Klicken Sie auf **Neues Lager**.
. Tragen Sie einen Namen ein.
. Wählen Sie einen *Lagertyp*.
. Wählen Sie einen *Logistiktyp*.
. **Speichern** Sie die Einstellungen, um das Lager anzulegen. +
→ Die Einstellungen des Lagers, in denen Sie weitere allgemeine Daten pflegen, werden geöffnet.

Das neue Lager wird alphabetisch in die Liste der Lager einsortiert.

[.instruction]
Allgemeine Lagerdaten pflegen:

. Öffnen Sie das Menü **System » Waren » Lager**.
. Öffnen Sie ein Lager.
. Klicken Sie auf *Einstellungen*.
. Nehmen Sie die Einstellungen anhand <<tabelle-allgemeine-Lagerdaten>> vor.
. **Speichern** Sie die Einstellungen.

[[tabelle-allgemeine-Lagerdaten]]
.Allgemeine Lagerdaten
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Lager-ID**
|ID des Lagers. Wird automatisch durch das System vergeben und ist nicht änderbar.

|**Lagername**
|Name des Lagers.

|**Lagertyp**
|Typ nach Zweck des Lagers wählen: +
**Vertrieb** = Standardlager. Lager für den Verkauf mit den entsprechenden Automatismen wie Bestandsreservierung und Statuswechsel bei Aufträgen.  +
**Reparatur** = Lager für Retourenartikel. Dieses Lager ist für Lager des Typs **Vertrieb** als **Zugeordnetes Reparaturlager** wählbar.  +
**Vorrat** = Lager für Artikel, die auf Vorrat liegen. +
**Umschlag** = Kurzfristiges Lager für die Zuordnung der Artikel zur Zieladresse bei der Umladung von einem Transportmittel auf ein anderes.  +
**Verteiler** = Auslieferungslager. +
**Sonstiges** = Sonderlager.

|**Logistiktyp**
|Lagerverwalter.  +
**Eigenes Lager** = Logistik wird vom eigenen Lager verwaltet.  +
**Amazon** = Artikel werden über Amazon FBA Multi-Channel vertrieben.  +
**DHL Fulfillment** = Artikel werden über DHL Fulfillment vertrieben.

|**Zugeordnetes Reparaturlager**
|Hier sind Lager des Typs **Reparatur** wählbar. Damit wird einem Lager ein Reparaturlager zugeordnet, in dem z.B. **Retouren** zur Reparatur eingelagert werden. So kommen defekte Artikel nicht mit dem normalen Lagerbestand in Berührung. Wenn die Artikel repariert oder ausgetauscht wurden, ordnen Sie sie wieder dem Vertriebslager zu.  +
Der Bestand in einem Reparaturlager ist nicht in den Webshop oder auf andere Portale übertragbar. Der Bestand im Reparaturlager bietet eine Übersicht, ob sich Geräte noch in der Reparatur befinden. Der Bestand kann also nicht verkauft werden. +
Das gewünschte Reparaturlager anlegen, damit es in dieser Dropdown-Liste verfügbar ist.

|**Priorität**
|Die Priorität für das Lager festlegen. Von **pass:[+]** (niedrigste Priorität) bis **pass:[+++++]** (höchste Priorität).

|**Nach Versandprofil splitten**
|Diese Option ist z.B. für die Erzeugung von <<auftragsabwicklung/auftraege/auftraege-verwalten#lieferauftrag, Lieferaufträgen>> auf **Ja** zu stellen, insofern damit gearbeitet wird.

|**Standort**
|Standort des Lagers.  +
Hier stehen die Länder zur Auswahl, die als Lieferländer unter <<auftragsabwicklung/fulfillment/versand-vorbereiten#100, System » Aufträge » Versand » Optionen » Tab: Lieferländer>> eingerichtet wurden.

|**Standard-Lagerort-Typ**
|Der Standard-Lagerort-Typ, der bei Lagereinstellungen, z.B. im Tab **Lager** der Artikeleinstellung, automatisch vorgewählt sein soll.

|[[Meldebestand_Variante_Lager]]**Dynamischer Meldebestand**
|Wählen zwischen aktiv und inaktiv. +
*aktiv* = die Differenz zum Meldebestand, MeldΔ, wird für Varianten in diesem Lager basierend auf dem dynamischen Meldebestand berechnet. Der dynamische Meldebestand selbst wird Ihnen im System noch nicht angezeigt. +
Hinweis: Damit für eine Variante die Differenz zum Meldebestand basierend auf dem dynamischen Meldebestand berechnet wird, muss der <<warenwirtschaft/nachbestellungen-verwalten/#500, Meldebestand der Variante>> für das Lager 0 sein. +
*inaktiv* = die Differenz zum Meldebestand wird für Varianten in diesem Lager nicht basierend auf dem dynamischen Meldebestand berechnet, sondern basierend auf dem <<warenwirtschaft/nachbestellungen-verwalten/#500, eingetragenen Meldebestand>>. Sie können also einen Meldebestand für die Variante eintragen, der größer als 0 ist.

|**Durchschnittspreis**
|Wählen wie der Durchschnittspreis für das Lager bestimmt wird. +
*EK der Mengen im Bestand* = der Durchschnittseinkaufspreis für Varianten in diesem Lager beruht auf den Einkaufspreisen der vorhandenen Bestandsmenge. Er wird bei jedem Wareneingang und Warenausgang neu berechnet. Diese Berechnungsmethode heißt Livedurchschnittsberechnung. +
*EK der Varianten* = als Durchschnittseinkaufspreis für Varianten in diesem Lager wird der Einkaufspreis aus den Variantendaten übernommen. +
*Gleitender Durchschnittspreis der Variante* = der Durchschnittseinkaufspreis für Varianten in diesem Lager wird gleitend berechnet. In diesem Fall wird der Einkaufspreis bei jedem Wareneingang berechnet, jedoch nicht bei Warenausgang. +
Die Berechnungsmethoden sind ausführlich unter <<https://knowledge.plentymarkets.com/warenwirtschaft/wareneingaenge-verwalten#250, Wareneingänge verwalten>> beschrieben


|**Verfügbarkeit mit Bestand** und +
 **Verfügbarkeit ohne Bestand**
|Hiermit wird festgelegt, welche Verfügbarkeit angezeigt wird, wenn Bestand vorhanden bzw. nicht vorhanden ist. Diese Einstellung ist dominant gegenüber dem Symbol, dass im Tab **Einstellungen** einer Variante für die **Verfügbarkeit** eingestellt ist. Wichtig ist jedoch, dass im Tab **Einstellungen** einer Variante die Einstellungen **Verfügbar, Nicht verfügbar** ebenfalls gewählt wurden. +
Nach jeder Änderung muss der Warenbestand neu berechnet werden. Diese Neuberechnung erfolgt im Menü <<warenwirtschaft/warenbestaende-verwalten#, **Waren » Warenbestände**>> durch einen Klick auf **Warenbestände neu berechnen**. +
Es werden die Verfügbarkeitssymbole angezeigt, die im Menü **System » Artikel » Verfügbarkeit** im Bereich **Webshop-Symbol** hinterlegt sind.

|**Notiz**
|Notizen, also alles was Sie zusätzlich als Informationen zum Lager speichern möchten, eintragen.

|**Inventur-Modus aktiv**
|Der <<warenwirtschaft/inventur-vornehmen#500, Inventur-Modus>> friert den Warenbestand des Lagers für die Dauer der Inventur ein.
|====

=== Dimensionen erstellen

Richten Sie Dimensionen ein, um Ihr Lager grundlegend in Elemente zu gliedern. Mindestens eine Dimension wird zum Generieren von Lagerorten benötigt. Diese Dimension kann z.B. eine Halle sein. Sie können bis zu 10 Dimensionen für jedes Lager erstellen. Aus den Dimensionen ergeben sich die Ebenen eines Lagers. +
Überlegen Sie vorab welche Dimensionen Sie erstellen möchten und beginnen Sie mit der kleinsten Dimension. Erstellen Sie die Dimensionen der Größe nach aufsteigend.

[IMPORTANT]
.Beispieldimensionen übernehmen oder löschen
====
In jedem Lager werden im Layout 2 Beispieldimensionen angezeigt. Diese Dimensionen sind nicht gespeichert. Sie können die Dimensionen übernehmen, umbenennen oder löschen. Zum Erstellen von Lagerorten benötigen Sie jedoch mindestens eine Dimension.
====

[.instruction]
Dimension erstellen:

. Öffnen Sie das Menü **System » Waren » Lager**.
. Öffnen Sie ein Lager.
. Klicken Sie auf *Layout*.
. Tragen Sie einen Namen für die Dimension ein.
. Nehmen Sie weitere optionale Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-Einstellungen-Dimensionen>>
. Klicken Sie auf *Neue Dimension hinzufügen*.
. **Speichern** Sie die Einstellungen, um die Dimension zu erstellen. +

Die Dimension wird als größte Dimension hinzugefügt. Wenn Sie weitere Dimensionen hinzufügen, sind diese übergeordnet, also größer. Beginnen Sie deshalb mit der kleinsten Dimension.

[[tabelle-Einstellungen-Dimensionen]]
.Dimension erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Präfix**
|_folgt_

|**Trenner**
|_folgt_

|**Position**
|_folgt_

|**Im Namen anzeigen**
|_folgt_
|====


=== Lagerorte generieren

Generieren Sie Lagerorte, um die tatsächlichen Plätze zum Lagern Ihrer Ware angeben zu können. Varianten können nur auf konkrete Lagerorte gebucht werden und nicht auf Dimensionen.
