= Lager einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Lager planen, Lager einrichten, Lagereinstellungen
:position: 10

In diesem Kapitel werden die Einstellungs- und Bearbeitungsmöglichkeiten für Lager beschrieben.
Sie erfahren, wie Sie ein neues Lager anlegen, um in Ihrem plentymarkets System Ihr Lager 1:1 nachzubilden.
Außerdem erfahren Sie, wie Sie Box-Regale als Zwischenlager für Sammelkommissionierungen erstellen.

* Eine optimale Einrichtung des Lagers ist entscheidend für den Versandprozess und hilft Ihnen, Zeit zu sparen.
Nehmen Sie sich also vorab Zeit, um Ihr Lager sinnvoll und wegeoptimiert abzubilden.
* Um alle Tools, z.B. auch das Tool link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentyBase^], optimal zu nutzen, sollte jeder Lagerort mit einem **Label** mit Barcode versehen werden.

[IMPORTANT]
.Mindestens ein Lager wird zur Bestandspflege und für Aufträge benötigt
====
Jedes System hat zu Beginn 2 Beispiellager, ein Vertriebslager und ein zugehöriges Reparaturlager. Diese Lager können Sie umbenennen und weiter nutzen oder löschen und eigene Lager anlegen. Sie benötigen mindestens ein Lager in Ihrem System, um Wareneingänge zu buchen und Bestände zu pflegen. Ohne ein Lager können Sie also keine Bestände verwalten. Eingehende Aufträge werden je nach Artikelverfügbarkeit einem Lager zugeordnet.
====

[#100]
== Lager planen

Lager werden aus Dimensionen aufgebaut. Alle Dimensionen zusammen bilden das Layout Ihres Lagers. Die Dimensionen sind komplett frei-definierbar. Beim Anlegen der Dimensionen ist es jedoch wichtig, dass Sie Ihre kleinste Dimension als erstes erstellen und dann der Größe nach aufsteigend weitere Dimensionen erstellen.

[IMPORTANT]
.Beispieldimensionen übernehmen
====
In jedem Lager, egal ob Beispiellager oder neu-erstelltes Lager werden Ihnen im Layout 2 Beispieldimensionen angezeigt. Diese Dimensionen sind nicht gespeichert. Sie können die Dimensionen übernehmen, umbenennen oder entfernen. Zum Erstellen von Lagerorten benötigen Sie jedoch mindestens eine Dimension.
====

.Einteilung eines Lagers
[cols="1,2"]
|====
|Einstellung|Erläuterung

|**Dimension**
|Dimensionen bilden die grundsätzlichen Einteilungselemente Ihres Lagers. Aus den Dimensionen ergeben sich später die tatsächlichen Ebenen eines Lagers. Ebenen sind sozusagen die konkrete Anwendung einer Dimension. Wenn Sie z.B. eine Lagerhalle als Dimension in Ihrem Layout führen, stellen die Lagerhalle 1, Lagerhalle 2 und Lagerhalle 3 die konkrete Anwendung dar. +
_Hinweis_: Mindestens eine Dimension wird benötigt, um Lagerorte zu generieren.

|**Lagerort**
|Lagerorte sind in plentymarkets keine Dimension. Lagerorte sind der konkrete Ablageplatz, an dem Ihre Produkte liegen. Sie benötigen mindestens eine Dimension, um Lagerorte zu generieren. Die Dimension ist dem Lagerort übergeordnet.
|====

Eine wegeoptimierte Pickliste ergibt sich durch die Position der Lagerorte. Ob eine Dimension die Position von Lagerorten beeinflusst, bestimmen Sie durch Ihre Einstellung. Eine Pickliste beginnt mit der niedrigsten Position und wird aufsteigend sortiert.

== Lager einrichten

Das Einrichten eines Lagers gliedert sich in 3 grundsätzliche Schritte. Zunächst müssen Sie allgemeine Daten wie den Namen und Zweck des Lagers angeben. Anschließend pflegen Sie weitere allgemeine Daten, wie die Adresse des Lagers, ein. Im 2. Schritt richten Sie Dimensionen ein, in die Sie Ihr Lager unterteilen. Im letzten Schritt generieren Sie Ihre Lagerorte.

=== Allgemeine Lagerdaten pflegen

Egal, ob Sie die Beispiellager bearbeiten und zu Ihren Lagern machen oder ob Sie neue Lager hinzufügen, die folgenden Angaben pflegen Sie für jedes Lager.

[.instruction]
Neues Lager erstellen:

. Öffnen Sie das Menü **System » Waren » Lager**.
. Klicken Sie auf **Neues Lager**.
. Tragen Sie einen Namen ein.
. Wählen Sie einen *Lagertyp*.
. Wählen Sie einen *Logistiktyp*.
. **Speichern** Sie die Einstellungen, um das Lager anzulegen. +
→ Die Einstellungen des Lagers, in denen Sie weitere allgemeine Daten pflegen, werden geöffnet.

Das neue Lager wird alphabetisch in die Liste der Lager einsortiert.

[.instruction]
Allgemeine Lagerdaten pflegen:

. Öffnen Sie das Menü **System » Waren » Lager**.
. Öffnen Sie ein Lager.
. Klicken Sie auf *Einstellungen*.
. Nehmen Sie die Einstellungen anhand Tabelle (_folgt_) vor.
. **Speichern** Sie die Einstellungen.

=== Dimensionen erstellen

Richten Sie Dimensionen ein, um Ihr Lager in strukturelle Elemente zu gliedern. Mindestens eine Dimension wird zum Generieren von Lagerorten benötigt. Diese Dimension kann z.B. eine Halle sein.

=== Lagerorte generieren

Generieren Sie Lagerorte, um die tatsächlichen Plätze zum Lagern Ihrer Ware angeben zu können. Varianten können nur auf konkrete Lagerorte gebucht werden und nicht auf Dimensionen.
