= Leitfaden zur Inventur
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Inventur, plentyWarehouse App, plenty warehouse app, plenty-warehouse App, Zählprotokoll, Warenbewegungen exportieren, Warenbestände exportieren, Inventur vornehmen, Inventur durchführen, Tipps Inventur
:position: 75
:id: 1SHGYNJ
:url: warenwirtschaft/leitfaden-inventur
:author: team-stock, team-mobile

Du möchtest eine Bestandsinventur durchführen und somit deinen Warenbestand zu einem bestimmten Zeitpunkt erfassen? Dann bist du auf dieser Seite genau richtig. Hier erfährst du, welche Schritte für die Inventur notwendig sind und kannst den Vorgang auf deine Bedürfnisse abstimmen.

[IMPORTANT]
.Orientierung: Verschiedene Vorgehensweisen zur Inventur in plentymarkets
====
////
mal überarbeiten; pW ist nicht Pflicht aber der einzige Weg ein Zählprotokoll zu erhalten (aktuell). plentymarkets App geht auch, oder halt Inventur ohne jegliche App. Irgendwie als Fall 1, Fall 2 oder Fall 3 beschreiben.
////
====

[#100]
== Vorbereitungen

Im Folgenden findest du Informationen darüber, welche Vorbereitungen wir dir für eine möglichst einfache Inventur empfehlen.

[#150]
=== plentyWarehouse App herunterladen

Am einfachsten führst du die Inventur mithilfe der <<warenwirtschaft/plentywarehouse#, plentyWarehouse App>> durch. plentyWarehouse enthält eine neu entwickelte Funktion zur Inventur, die in der aktuellsten Version auch den nachträglichen Export von <<warenwirtschaft/plentywarehouse/inventur-durchfuehren#600, rechtskonformen Zählprotokollen>> zu Inventuren in verschiedenen Dateiformaten unterstützt. Außerdem werden die Stückzahlen der mit der plentyWarehouse App gezählten Artikel und Varianten automatisch im Hintergrund mit deinem plentymarkets System synchronisiert.

Lade die plentyWarehouse App link:https://play.google.com/store/apps/details?id=com.plentysystems.plentywarehouse[hier im Google Play Store^] {nbsp}icon:external-link[] kostenlos herunter. 

Arbeitest du zum ersten mal mit der plentyWarehouse App? Dann schaue dir auch die Informationen auf unserer <<warenwirtschaft/plentywarehouse#, Übersichtsseite zu plentyWarehouse>> an.

include::../warenwirtschaft/plentywarehouse/_textblocks/hinweis-offene-beta.adoc[]

[#200]
=== Einstellungen zur Inventur in der plentyWarehouse App

Damit die Inventur genau so abläuft, wie es für dich am besten ist, müssen im Bereich *Einstellungen* der plentyWarehouse App einige vorbereitende Einstellungen vorgenommen werden. Details und Anleitungen dazu findest du auf der Handbuchseite <<warenwirtschaft/plentywarehouse/inventur-durchfuehren#200, Inventur durchführen>>.

[#300]
=== Erstellen von Exporten via Katalog

Um eine Inventur durchzuführen und diese später auch dokumentieren und kontrollieren zu können, solltest du vor der Inventur die Bestände und Warenbewegungen deines Systems exportieren.

Wie du generell einen Katalog für den Export von Daten erstellst, erfährst du <<daten/daten-exportieren/dateiexport#, hier>>.
Wie du einen Export der Warenbestände in einem Katalog erstellst, erfährst du <<daten/daten-exportieren/katalog-warenbestaende#, hier>>.
Wie du einen Export der Warenbewegungen in einem Katalog erstellst, erfährst du <<daten/daten-exportieren/katalog-warenbewegungen#, hier>>.

[#400]
=== Bestände per Import nullen

Wie du die Bestände per Import auf 0 setzen kannst, erklären wir dir hier. +

*_Hinweis:_* Dieser Schritt ist nur notwendig, wenn du den Inventurmodus verwendest und Warenbestände genullt werden sollen.

[#500]
=== Bestände komplett nullen oder nicht?

Bevor du mit der Inventur startest, solltest du dir die Frage stellen, ob du vor Beginn der Inventur alle Bestände nullen möchtest oder nicht. Hier zeigen wir dir zunächst, was genau du dabei beachten musst.

* Solange der Inventurmodus aktiv ist, werden die Warenbewegungen in dieser Zeit zwar gespeichert, es werden aber keine Berechnungen durchgeführt.
* Mit der Deaktivierung des Inventurmodus werden die ausstehenden Berechnungen durchgeführt.
* Wenn du mit aktiviertem Inventurmodus die Lagerbestände nullst, dann bekommen Marktplätze und der eigene Webshop davon nichts mit. Wenn nun aber während der Inventur Waren verkauft werden, dann werden die Bestandreservierungen auch nicht berechnet und es kann daher zu Überverkäufen in dieser Zeit kommen.
* Wenn der Inventurmodus nicht aktiviert ist, laufen die Berechnungen nach Bestandsänderung normal weiter. Wenn dann durch die App ein Lagerort gezählt wurde, werden die Bestände im Anschluss an das System übertragen und ggf. angepasst. Wenn nun also eine Menge eines Artikels sich auf einem Lagerort bestätigt, entsteht keine Warenbewegung.

Entscheide also hier für dich, welches Vorgehen besser zum jeweiligen Ablauf passt. +
In der folgenden Tabelle sind noch einmal die Vor- und Nachteile des Nullens aufgeführt.

[[tabelle-vor-und-nachteile]]
.Vor- und Nachteile des Nullens
[cols="2,2"]
|====
|Vorteile |Nachteile

|Zum Stichtag sind alle Bestände aller Varianten in deinem Lager auf 0. Dies hat zur Folge, dass alle Mengen, die während der Inventur gezählt werden, auch eine Warenbewegung mit positivem Wert erhalten. +
_Beispiel:_ Variante 123 +
- Menge vor Inventur: 8 +
- Menge durch Nullen: 0 +
-  Warenbewegung: -8 +
- Menge durch Zählung: 8 +
- Warenbewegung: +8
|Du musst daran denken, den Inventurmodus vor der Inventur zu aktivieren und nach der Inventur wieder zu deaktivieren.

|Du erhältst in jedem Fall eine Warenbewegung für Artikel, die auf Lager sind.
|Bestände müssen nach aktiviertem Inventurmodus, z.B per Import, genullt werden.

|
|Während des Inventurmodus kann es zu Überverkäufen kommen.

|
|Falls während der Inventur etwas schief geht, müssen die Bestände von vor der Inventur ggf. wieder importiert werden.

|
|Jeder Lagerort muss vor dem Deaktivieren des Inventurmodus komplett gezählt sein.

|====

[#600]
=== Daten exportieren

Um festzuhalten, welche Artikelmengen vor der Inventur systemseitig auf Lager waren, sollten diese exportiert werden. Dies geschieht über unseren <<daten/daten-exportieren/dateiexport#, Katalog>> und das Exportformat <<daten/daten-exportieren/katalog-warenbestaende#, Warenbestände>>.

Lege die exportierte Datei bei dir zur späteren Kontrolle und Dokumentation ab.

[#700]
== Inventur durchführen

Je nachdem, ob du vor der Inventur den <<warenwirtschaft/inventur-vornehmen#500, Inventurmodus aktivierst>>, solltest du bei der Inventur stets die folgenden Schritte durchführen:

[.tabs]
====
Bei Nutzung des Inventurmodus::
+

--
* <<warenwirtschaft/inventur-vornehmen#600, Inventurmodus aktivieren>>
* <<warenwirtschaft/inventur-vornehmen#200, Bestände vor der Inventur exportieren>> und sichern
* <<warenwirtschaft/inventur-vornehmen#800, Bestände per Import leeren>>
* <<warenwirtschaft/plentywarehouse/inventur-durchfuehren#300, Inventur mit plentyWarehouse App durchführen>>
* <<warenwirtschaft/inventur-vornehmen#1000, Inventurmodus deaktivieren>>
* <<warenwirtschaft/inventur-vornehmen#200, Bestände nach der Inventur erneut exportieren>> und sichern
* Bei Verwendung der plentyWarehouse App: <<warenwirtschaft/plentywarehouse/inventur-durchfuehren#700, Zählprotokoll herunterladen>>
* <<#1100, Abweichungen per Katalog exportieren und vergleichen>>
--

Ohne Nutzung des Inventurmodus::
+

--
* <<warenwirtschaft/inventur-vornehmen#200, Bestände vor der Inventur exportieren>> und sichern
* <<warenwirtschaft/plentywarehouse/inventur-durchfuehren#300, Inventur mit plentyWarehouse App durchführen>>
* <<warenwirtschaft/inventur-vornehmen#200, Bestände nach der Inventur erneut exportieren>> und sichern
* Bei Verwendung der plentyWarehouse App: <<warenwirtschaft/plentywarehouse/inventur-durchfuehren#700, Zählprotokoll herunterladen>>
* <<#1100, Abweichungen per Katalog exportieren und vergleichen>>

--
====

[#1000]
== Inventur dokumentieren

Nachdem du die Inventur durchgeführt hast, hast du die Möglichkeit, den Inventurvorgang rechtskonform zu protokollieren. Dazu steht dir im Bereich *Waren » Inventur* das Menü *Zählprotokoll-Export* zur Verfügung. Hier kannst du mithilfe verschiedener Filter Zählprotokolle im PDF- oder CSV-Format herunterladen. 

[IMPORTANT]
.Zählprotokoll: Beschränkung auf plentyWarehouse
====
Aktuell beinhalten Zählprotokolle nur Daten zu Inventuren, die mit der plentyWarehouse App durchgeführt werden. Inventuren, die mit der <<app/funktionen/lagerverwaltung/inventur#, plentymarkets App>> oder lediglich durch den <<warenwirtschaft/inventur-vornehmen#, Export und Import von Warenbeständen>> vorgenommen werden, können also nicht mithilfe des Zählprotokolls dokumentiert werden.
====

Wichtige Zusatzinformationen zu möglichen Filtern und eine Anleitung zum Erstellen des Zählprotokolls findest du auf der Handbuchseite <<warenwirtschaft/plentywarehouse/inventur-durchfuehren#600, Inventur durchführen.>> 

[#1100]
== Inventurergebnisse und Bestände kontrollieren

Um die Inventur im Nachgang zu kontrollieren, wenn z.B. große Abweichungen zwischen den Beständen vor und nach der Inventur vorliegen, bieten sich die folgenden 3 Möglichkeiten.

[#1200]
=== Vergleich der Bestände vor und nach der Inventur

Bei dieser Methode vergleichst du die beiden Bestands-Dateien, die du vor und nach der Inventur erstellt hast. Wenn du die jeweiligen Bestände pro Variante vergleichst, kannst du berechnen, wo Abweichungen vorliegen und diese nachkontrollieren und ggf. anpassen. Da du hier nur die Bestände siehst, musst du ggf. im System nachschauen, auf welchen Lagerorten die Artikel liegen.

[#1300]
=== Vergleich der Gesamtabweichungen pro Variante

Wenn du einen Export über einen Katalog des Formats <<daten/daten-exportieren/katalog-warenbewegungen#, Warenbewegungen>> erstellst und anhand des Datumsfilters sowie des Grundes für die Warenbewegung (ID 302) nur die Bewegungen, die während und durch die Inventur entstanden sind, exportieren lässt und dabei noch den Filter für die Summe der Warenbewegungen pro Variante verwendest, dann erhältst du beim Export nur eine Datenzeile pro Variante. Dies ist allerdings auch nur dann der Fall, wenn bei dieser Variante vor und nach der Inventur eine Abweichung bei den Mengen vorliegt. Sind die Mengen auf allen Lagerorten identisch, dann erhältst du keine Datenzeile. Weichen die Mengen pro Lagerort ab, aber die Gesamtmenge der Bestände dieser Variante ist identisch, dann erhältst du im Export eine Datenzeile mit der Menge 0 im Feld Warenbewegung.

Diese Art des Exports ermöglicht es dir somit, sehr schnell zu erfassen, bei welchen Artikeln es Abweichungen in der Gesamtmenge pro Variante gegeben hat.
Weitere Details dazu findest du im Kapitel zum Thema <<warenwirtschaft/leitfaden-inventur#1500, Abweichungen feststellen und auswerten>>.

[#1400]
=== Vergleich der Abweichungen einer Variante pro Lagerort

Ein weiterer Export sollte über das Export-Format <<daten/daten-exportieren/katalog-warenbewegungen#, Warenbewegungen>> erstellt werden, allerdings ohne den Filter für die Summe der Warenbewegungen. Es werden also lediglich der Datumsfilter und der Grund für die Warenbewegung (ID 302) benötigt. In diesem Fall erhältst du dann eine Datenzeile, wenn die Menge einer Variante auf einem bestimmten Lagerort vor und nach der Inventur abweicht. Diese Liste ist dann hilfreich, wenn du durch die Liste der Gesamtabweichungen festgestellt hast, dass du eine Variante noch einmal genauer kontrollieren musst. Dann kannst du in der Liste jeden Lagerort prüfen, auf dem es Abweichungen zu dieser Variante gegeben hat und so zügig feststellen, auf welchem Lagerort du noch einmal genauer nachschauen solltest.
Weitere Details dazu findest du im nachfolgenden Kapitel zum Thema <<warenwirtschaft/leitfaden-inventur#1500, Abweichungen feststellen und auswerten>>..

[#1500]
== Abweichungen zwischen Zählung und vorherigem Bestand feststellen und auswerten

////
umschreiben
////
Das Export-Format <<daten/daten-exportieren/katalog-warenbewegungen#, Warenbewegungen>> vereinfacht dir die Auswertung der Inventur. Der Katalog dient dazu, Abweichungen zwischen Zählung und vorherigem Bestand im System pro Variante und Abweichungen auf einzelnen Lagerorten festzustellen. Im Folgenden beschreiben wir, wie dir der Katalog dabei hilft.

Es gibt 2 wichtige Kriterien, wenn es darum geht, Abweichungen bei den Warenbeständen nach der Inventur festzustellen:

[#1600]
=== Kriterium 1: Sind die Bestände eines Artikels vor und nach der Inventur identisch?

////
prüfen und umschereiben
////
Hierfür bietet es sich an, einen Export mit dem Katalogformat Warenbewegungen zu erstellen und sich alle Warenbewegungen, gruppiert pro Variante, im Zeitraum der Inventur und für den Warenbewegungsgrund Korrektur durch Inventur ausgeben zu lassen. Um pro Variante zu gruppieren, nutzt du im Katalog den Filter Summe der Warenbewegungen. Bei den Filtern kannst du auch den Datumbereich wählen, in dem die Inventur stattgefunden hat. Um nur die Bewegungen zu erhalten, die mit der Inventur zu tun haben, setzt du als weiteren Filter die Grund-ID. Für die Inventur trägst du hier den Wert 302 ein.
Als Ergebnis bekommt man die Gesamtabweichung pro Variante. Im besten Fall ist diese immer 0. Man kann über diese Liste allerdings schnell sehen, bei welchen Artikeln es Abweichungen vor und nach der Inventur gab. Wir sehen allerdings in dieser Liste nicht, ob bei einem Lagerort für einen Artikel 5 Stück mehr gezählt wurden und bei einem anderen Lagerort 5 weniger, denn die Summe ist 0.

Fazit: Diese Liste dient dem Gesamtüberblick der Abweichungen, lässt Abweichungen auf einzelnen Lagerorten aber außen vor.

[#1700]
=== Kriterium 2: Liegen die Artikel vor und nach der Inventur auf den gleichen Lagerorten im System?

////
prüfen und umschreiben
////
Während eines Jahres kann es vorkommen, dass Ware umgelagert wird, aber das Umbuchen im System vergessen wurde.

Um Abweichungen zu Artikeln auf einzelnen Lagerorten sehen zu können, bietet es sich an, einen Export mit dem Katalogformat Warenbewegungen zu erstellen und sich alle Warenbewegungen, im Zeitraum der Inventur, für den Warenbewegungsgrund Korrektur durch Inventur ausgeben zu lassen.
Bei den Filtern kannst du dafür den Datumbereich wählen, in dem die Inventur stattgefunden hat. Um nur die Bewegungen zu erhalten, die mit der Inventur zu tun haben, setzt du als weiteren Filter die Grund-ID. Für die Inventur trägst du hier den Wert 302 ein.
Als Ergebnis bekommt man pro Warenbewegung, also Abweichung gegenüber dem Ergebnis vor der Inventur, einen Eintrag in der Liste. Wenn also z.B. die Variante mit der ID 123 im System 10x auf Lagerort A gebucht ist, während der Inventur dort aber nicht gezählt wurde, dafür aber 10x auf Lagerort B, dann habe ich für diese Variante eine Warenbewegung von -10 für Lagerort A und eine Warenbewegung von +10 für Lagerort B. In Summe bedeutet das, dass die Gesamtmenge vor und nach der Inventur für diese Variante identisch ist, aber physisch auf einem anderen Lagerort liegt als zuvor. Des Weiteren hilft diese detaillierte Liste, falls es im Gesamtergebnis Abweichungen gibt, die Lagerorte gezielt aufzusuchen und die Bestände noch einmal nachzuzählen und mit der Inventurzählung zu vergleichen.

Fazit: Diese Liste hilft, bei Abweichungen die genauen Abweichungen pro Lagerort festzustellen und gegenprüfen zu können. Außerdem gibt diese Liste eine Übersicht, wie viele Artikel ggf. physisch umgelagert wurden, ohne systemisch umgebucht worden zu sein.
