= MHD/Charge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: MHD, Charge, Mindesthaltbarkeitsdatum, Mindersthaltbarkeit, Chargen
:position: 60
:url: warenwirtschaft/mhd-charge-verwalten

Sie können in plentymarkets Varianten mit Mindesthalbarkeitsdatum (MHD) und/oder Chargen verwalten. Aktuell sind diese Funktionen jedoch nur im plentymarkets Backend produktiv nutzbar.

[IMPORTANT]
.MHD/Chargen mit App und Prozessen nutzen
====
Wenn Sie mit den Prozessen und/oder der App arbeiten, sollten Sie die Funktionen zur Verwaltung von MHD/Chargen noch nicht nutzen, da MHD- und Chargen-Daten in der App und den Prozessen aktuell noch zu Fehlern führen können. Diese Funktionen werden in Kürze nachgeliefert.
====

== MHD/Charge aktivieren

Um MHD und/oder Chargen für Varianten zu pflegen, aktivieren Sie die Optionen *MHD* und/oder *Charge* am Lager einer Variante. Sobald das Lager Bestand hat, ist es nicht mehr möglich, die Option am Lager der Variante zu aktivieren bzw. zu deaktivieren. Ist in diesem Lager der Lagerbestand gleich null, ist eine Änderung möglich. Weitere Informationen finden Sie im Abschnitt <<warenwirtschaft/wareneingaenge-verwalten#200, Variante mit Lagerort verknüpfen>>.

== Wareneingang

Abhängig davon, welche Einstellung Sie wählen, können Sie Varianten mit MHD, Varianten mit Charge oder Varianten mit MHD und Charge einbuchen. Es wird empfohlen, pro Lager und Variante nur gleiche MHD und Chargen auf einen Lagerort zu buchen. Diese Einstellung ist bereits standardmäßig getroffen. Wenn Sie unterschiedliche MHD/Chargen auf den gleichen Lagerort buchen, kann dies zu Problemen beim Picken führen, da Picker dann ein spezifisches MHD und/oder eine spezifische Charge suchen müssen. Weitere Informationen finden Sie im Kapitel <<warenwirtschaft/wareneingaenge-verwalten#810, Wareneingang mit MHD/Charge>>.

== Umbuchen

Sie können Artikel mit MHD/Charge in andere Lager umbuchen. Bei der Umbuchung von Varianten mit MHD/Charge kann es jedoch zu Beschränkungen kommen. Informationen zur Umbuchung finden Sie im Kapitel <<warenwirtschaft/warenbestaende-verwalten#500, Warenbestand über das Backend umbuchen>>.

== Mindesthaltbarkeit prüfen

Im Menü *Waren » Lagerort-Verwaltung* prüfen Sie den Status von Varianten mit Mindesthalbarkeitsdatum. Die Spalte *Tage haltbar* zeigt, wie viele Tage eine Variante noch haltbar ist.

[.instruction]
Mindesthaltbarkeit prüfen:

. Öffnen Sie das Menü *Waren » Lagerort-Verwaltung*.
. Wählen Sie Daten für die Filter *MHD von:* und *bis:*. +
→ Alle Lagerorte mit Varianten im gewählten MHD werden angezeigt.

.Status Mindesthaltbarkeit
[cols="1,3"]
|====
|Tage haltbar |Status

|**< 1**
|Ware abgelaufen
|**>1 & <30**
|Ware läuft demnächst ab
|**> 30**
|Ware ok
|====

== Retouren

Beim Wiedereinbuchen einer Variante mit MHD/Charge wird das Einbuchen verschiedener Chargen und MHD auf den gleichen Lagerort nicht automatisch blockiert. Es wird jedoch empfohlen, pro Variante und Lager nur gleiche MHD/Chargen auf einen Lagerort zu buchen. Bei einer chaotischen Lagerhaltung von MHD- und Chargenartikeln kann es bei der Komissionerung zu Problemen kommen. Weiter Informationen zum Thema Retoure finde sie im Kapitel <<warenwirtschaft/waren-ausbuchen, Retoure>>.

== Picklisten, Packlisten und Lager-Picklisten

Auch auf Picklisten, Packlisten und Lager-Picklisten können optional die MHD-/Chargeninformationen ausgeben werden. Weitere Informationen finden Sie auf den folgenden Handbuchseiten:

* <<auftraege/auftragsdokumente/pickliste#, Pickliste>>
* <<auftraege/auftragsdokumente/lager-pickliste, Lager-Pickliste>>
* <<auftraege/auftragsdokumente/packliste#, Packliste>>
