= MHD/Charge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: MHD, Charge, Mindesthaltbarkeitsdatum, Mindersthaltbarkeit, Chargen
:position: 60

Sie können in plentymarkets Artikel mit MHD/Charge verwalten. Aktuell ist die Funktion nur im plentymarkets Backend produktiv nutzbar.

[IMPORTANT]
.MHD/Chargen mit App und Prozessen nutzen
====
Wenn Sie mit den Prozessen und der App arbeiten empfehlen wir Ihnen die Funktion MHD/Chargen noch nicht zu aktivieren, da das Arbeit mit der App und den Prozesse aktuell noch zu Fehlern führen kann. Diese Funktionen werden in kürze nachgeliefert.
====

== MHD/Charge aktivieren.

Um die Funktion MHD/Chargen nutzen zu können, müssen Sie diese im Lager einer Variante aktivieren. Sobald auf diesem Lager Lagerbestand mit MHD/Charge vorhanden ist, ist es nicht mehr möglich, die Option am Lager einer Variante zu deaktivieren. Ist in diesem Lager der Lagerbestand mit MHD/Charge gleich null, ist eine Änderung auch möglich. Weitere Informationen finden Sie im Abschnitt **<<warenwirtschaft/wareneingaenge-verwalten#200, Variante mit Lagerort verknüpfen>>**


== Wareneingang

Sie können je nach dem welche Einstellung Sie gewählt haben entweder Waren mit MHD oder Charge oder MHD und Charge einbuchen. Wir empfehlen Ihnen pro Lager und Variante nur gleich MHD und Chargen auf einen Lagerort zubuchen. Diese Einstellung ist bereits standardmäßig getroffen. Wenn Sie unterschiedliche MHD/Chargen auf den gleichen Lagerort buchen kann dies zur Problemen bei Picken führe, da ein spezifisches MHD oder Charge gesucht werden muss.
Weitere Informationen entnehmen Sie bitte dem Abschnitt **<<warenwirtschaft/wareneingaenge-verwalten#810, Wareneingang mit MHD/Charge>>**

== Umbuchen

Das Buchen des Warenausgangs beim Eingaben der Paketnummer hat den Vorteil, dass die Versandetiketten erst am Ende des Fulfillment-Prozesses erstellt werden. So kann davon ausgegangen werden, dass alle Aufträge, zu denen ein Versandetikett mit Paketnummer vorliegt, sich auch wirklich im Versand befinden.

Das Buchen des Warenausgangs lässt sich mithilfe einer Ereignisaktion automatisieren. Zusätzlich kann mittels derselben Ereignisaktion auch eine E-Mail mit der Versandbestätigung an den Kunden gesendet werden.
Der Versand der E-Mail kann auch mit einer separaten Ereignisaktion erfolgen. Nach dem Einrichten der Ereignisaktion wird das Importieren der Paketnummern beschrieben.

== Mindesthaltbarkeit prüfen

Sie können sich eine Übersicht der Lagerorte mit MHD-Artikel anzeigen lassen. Außerdem können Sie in der Spalte *Tage haltbar* sehen wie lang ein bestimmter Artikel noch haltbar ist.

.Status Mindesthaltbarkeit
[cols="1,1"]
|====
|Tage haltbar |Status

|**< 1**
|Ware abgelaufen
|**>1 & <30**
|Ware läuft demnächst ab
|**> 30**
|Ware ok
|====

[.instruction]
Mindesthaltbarkeit prüfen:

. Öffnen Sie das Menü **Waren » Lagerort-Verwaltung**.
. Setzten Sie den Filter für MHD.  +
→ Es werden Ihnen alle Lagerorte mit MHD angezeigt.

== Retouren

Beim wiedereinbuchen eine Artikels mit MHD/Charge wird das Einbuchen verschiedener Chargen und MHD auf den gleichen Lagerort nicht automatisch blockiert. Wir empfehlen pro Variante und Lager nur gleiche MHD/Chargen auf einen Lagerort zu buchen.

== Pickliste, Packliste und Lager-Pickliste

Auch auf der Pickliste, Packliste und Lager-Pickliste können Sie entscheiden, ob Sie die MHD-/Chargeninformationen ausgeben möchten. Für weitere Informationen schauen Sie bitte in die folgenden Abschnitte **<<auftragsabwicklung/auftraege/auftragsdokumente/pickliste, Pickliste**, **<<auftragsabwicklung/auftraege/auftragsdokumente/lager-pickliste, Lager-Pickliste>>**, **<<auftragsabwicklung/auftraege/auftragsdokumente/packliste, Packliste>>**,
