= MHD/Charge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: MHD, Charge, Mindesthaltbarkeitsdatum, Mindersthaltbarkeit, Chargen
:position: 60

Sie können in plentymarkets Artikel mit MHD/Charge verwalten. Aktuell ist die Funktion nur im plentymarkets Backend prdouktiv nutzbar. Wenn Sie mit den Prozessen und der App arbeiten empfehlen wir Ihnen die Funktion MHD/Chargen noch nicht zu aktivieren, da das Arbeit mit der App und den Prozesse aktuell noch zu Fehlern führen kann. Diese Funktionen werden in kürze nachgeliefert.

== MHD/Charge aktivieren.

Um die Funktionen MHD/Chargen nutzen zu können müssen Sie diese im Lager einer Variante aktiveren. Sobald Lagerbestand mit MHD/Charge vorhanden ist, ist es nicht mehr möglich, die Option am Lager einer Variante zu deaktivieren. Ist der Lagerbestand mit MHD/Charge gleich 0, ist eine Änderung auch im Nachhinein möglich.  Detaillierte informationen finden Sie im Abschnitt https://knowledge.plentymarkets.com/warenwirtschaft/wareneingaenge-verwalten#200


== Wareneingang

Sie können je nach dem welche Einstellung Sie gewählt haben entweder Waren mit MHD oder Charge oder MHD und Charge einbuchen. Wir empfehlen Ihnen pro Lager und Variante nur gleich MHD und Chargen auf einen Lagerort zubuchen. Diese Einstellung ist bereits standardmäßig getroffen. Wenn Sie unterschiedliche MHD/Chargen auf den gleichen Lagerort buchen kann dies zur Problemen bei Picken führe, da ein spezifisches MHD oder Charge gesucht werden muss.
Weitere Informationen entnehmen Sie bitte dem Abschnitt: https://knowledge.plentymarkets.com/warenwirtschaft/wareneingaenge-verwalten#810

== Umbuchen

Das Buchen des Warenausgangs beim Eingaben der Paketnummer hat den Vorteil, dass die Versandetiketten erst am Ende des Fulfillment-Prozesses erstellt werden. So kann davon ausgegangen werden, dass alle Aufträge, zu denen ein Versandetikett mit Paketnummer vorliegt, sich auch wirklich im Versand befinden.

Das Buchen des Warenausgangs lässt sich mithilfe einer Ereignisaktion automatisieren. Zusätzlich kann mittels derselben Ereignisaktion auch eine E-Mail mit der Versandbestätigung an den Kunden gesendet werden.
Der Versand der E-Mail kann auch mit einer separaten Ereignisaktion erfolgen. Nach dem Einrichten der Ereignisaktion wird das Importieren der Paketnummern beschrieben.

== Mindesthaltbarkeit prüfen

Sie können sich eine Übersicht der Artikel mit MHD/Chargen anzeigen lassen. Außerdem können Sie sehen wie lang ein bestimmter Artikel noch haltbar ist.

[.instruction]
Übersicht MHD/Chargen anzeigen lassen:

. Öffnen Sie das Menü **Waren » Lagerort-Verwaltung**.
. Setzten Sie den Filter für MHD/Chargen .  +
→ Es werden Ihnen alle Lagerorte mit MHD/Chargenartikel angezeigt

== Retouren

Beim wiedereinbuchen eine Artikel mit MHD/Charge wird das einbuchen verschiedener Chargen und MHD auf den gleichen Lagerort nicht automatisch blockiert. Wir empfehlen pro Variante und Lager nur gleiche MHD/Chargen auf einen Lagerort zu buchen.

== Pickliste, Packliste und Lager-Pickliste

Auch auf der Pickliste, Packloste und Lager Pickliste können Sie entscheiden, ob Sie die MHD-/Chargeninformationen ausgeben möchten. Für weitere Informationen schauen Sie bitte hier:
https://knowledge.plentymarkets.com/auftragsabwicklung/auftraege/auftragsdokumente/pickliste
https://knowledge.plentymarkets.com/auftragsabwicklung/auftraege/auftragsdokumente/lager-pickliste
https://knowledge.plentymarkets.com/auftragsabwicklung/auftraege/auftragsdokumente/packliste
