= MHD/Charge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: MHD, Charge, Mindesthaltbarkeitsdatum, Mindersthaltbarkeit, Chargen
:position: 60

Sie können in plentymarkets Artikel mit MHD/Charge verwalten. Aktuell ist die Funktion nur im plentymarkets Backend produktiv nutzbar.

[IMPORTANT]
.MHD/Chargen mit App und Prozessen nutzen
====
Wenn Sie mit den Prozessen und der App arbeiten empfehlen wir Ihnen die Funktion MHD/Chargen noch nicht zu aktivieren, da das Arbeit mit der App und den Prozesse aktuell noch zu Fehlern führen kann. Diese Funktionen werden in kürze nachgeliefert.
====

== MHD/Charge aktivieren.

Um die Funktion MHD/Chargen nutzen zu können, müssen Sie diese im Lager einer Variante aktivieren. Sobald dieses Lager Bestand hat, ist es nicht möglich, die Option am Lager einer Variante zu aktivieren bzw. deaktivieren. Ist in diesem Lager der Lagerbestand gleich null, ist eine Änderung auch möglich. Weitere Informationen finden Sie im Abschnitt **<<warenwirtschaft/wareneingaenge-verwalten#200, Variante mit Lagerort verknüpfen>>**


== Wareneingang

Sie können je nach dem welche Einstellung Sie gewählt haben entweder Waren mit MHD und Charge oder nur mit MHD oder Charge einbuchen. Wir empfehlen Ihnen pro Lager und Variante nur gleiche MHD und Chargen auf einen Lagerort zubuchen. Diese Einstellung ist bereits standardmäßig getroffen. Wenn Sie unterschiedliche MHD/Chargen auf den gleichen Lagerort buchen, kann dies zur Problemen bei Picken führen, da ein spezifisches MHD oder Charge gesucht werden muss.
Weitere Informationen entnehmen Sie bitte dem Abschnitt **<<warenwirtschaft/wareneingaenge-verwalten#810, Wareneingang mit MHD/Charge>>**

== Umbuchen

Sie können Artikel mit MHD/Charge in andere Lager umbuchen. Bitte beachten Sie, dass es dabei zu beschränkungen kommen kann. Die entsprechenden Informationen zur Umbuchung können Sie dem Abschnitt **<<warenwirtschaft/warenbestaende-verwalten#500, Warenbestand über das Backend umbuchen**

== Mindesthaltbarkeit prüfen

Sie können sich eine Übersicht der Lagerorte mit MHD-Artikel anzeigen lassen. Außerdem können Sie in der Spalte *Tage haltbar* sehen wie lang ein bestimmter Artikel noch haltbar ist.

.Status Mindesthaltbarkeit
[cols="1,1"]
|====
|Tage haltbar |Status

|**< 1**
|Ware abgelaufen
|**>1 & <30**
|Ware läuft demnächst ab
|**> 30**
|Ware ok
|====

[.instruction]
Mindesthaltbarkeit prüfen:

. Öffnen Sie das Menü **Waren » Lagerort-Verwaltung**.
. Setzten Sie den Filter für MHD.  +
→ Es werden Ihnen alle Lagerorte mit MHD angezeigt.

== Retouren

Beim wiedereinbuchen eine Artikels mit MHD/Charge wird das Einbuchen verschiedener Chargen und MHD auf den gleichen Lagerort nicht automatisch blockiert. Wir empfehlen pro Variante und Lager nur gleiche MHD/Chargen auf einen Lagerort zu buchen. Bei einer chaotischen Lagerhaltung von MHD- und Chargenartikel kann es bei der Komissionerung zu Problemen kommen.

== Pickliste, Packliste und Lager-Pickliste

Auch auf der Pickliste, Packliste und Lager-Pickliste können Sie entscheiden, ob Sie die MHD-/Chargeninformationen ausgeben möchten. Für weitere Informationen schauen Sie bitte in die folgenden Abschnitte **<<auftragsabwicklung/auftraege/auftragsdokumente/pickliste, Pickliste**, **<<auftragsabwicklung/auftraege/auftragsdokumente/lager-pickliste, Lager-Pickliste>>**, **<<auftragsabwicklung/auftraege/auftragsdokumente/packliste, Packliste>>**,
