= Nachbestellungen verwalten
:lang: de
include::{includedir}/_header.adoc[]
:description: Erfahre, wie du mit der neuen Nachbestellung in plentymarkets arbeitest.
:keywords: Nachbestellung, Waren nachbestellen
:position: 30
:url: warenwirtschaft/nachbestellungen-verwalten

[IMPORTANT]
.Betaversion der neuen Nachbestellung
====
Diese Handbuchseite beschreibt das Anlegen und Verwalten von Nachbestellungen mit der Betaversion der neuen Funktionalitäten zur Nachbestellung. Diese Funktionalitäten werden erst in den kommenden Wochen in allen plentymarkets Systemen sichtbar. Weitere Informationen zur kommenden Veröffentlichung findest du in diesem link:https://forum.plentymarkets.com/t/ankuendigung-releaseprozess-neue-nachbestellung/542252[Forumsbeitrag^] (Stand 24.05.2019).
====

Im Menü *Waren » Bestellwesen » Bestellung* nimmst du nicht nur <<warenwirtschaft/umbuchungen-vornehmen#, Umbuchungen>> vor, sondern legst auch Nachbestellungen an. Über Nachbestellungen bildest du die Bestellung von Waren bei deinen Lieferanten ab.

Eine Nachbestellung gliedert sich in folgende Arbeitsschritte:

* <<#200, Varianten für die Nachbestellung identifizieren>>
* <<#300, Nachbestellung anlegen>>
* <<#400, Auftragspositionen hinzufügen>>
* <<#500, Auftragspositionen bearbeiten>>
* <<#600, Weitere Informatinen hinterlegen>>
* <<#700, Nachbestellung auslösen und übermitteln>>
* <<#800, Rückstandsliste nutzen>>
* <<#900, Waren einbuchen>>
* <<#1000, Nachbestellung abschließen>>

Vor dem Anlegen der ersten Nachbestellungen solltest du einige vorbereitende Einstellungen vornehmen.

[#100]
== Vorbereitende Einstellungen
Die folgenden Kapitel beschreiben einige vorbereitende Einstellungen, die du vor dem Anlegen einer Nachbestellung vornehmen solltest. In der Regel sind diese Einstellungen nur einmalig notwendig. Richte den Meldebestand und den Bestellmengenvorschlag ein, um festzulegen, wann Artikel nachbestellt werden sollen. Erstelle neue Auftragsstatus speziell für die Nachbestellungen und lege Tags an, um dir die Übersicht zu erleichtern. Verpflichtend ist zudem die Einrichtung einer Dokumentenvorlage für das Dokument *Nachbestellung*.

[#110]
=== Meldebestand und Bestellmengenvorschlag festlegen

Vor dem Anlegen der ersten Nachstellung solltest du die Einstellungen zum Meldebestand und zum Abverkaufszeitraum vornehmen. So legst du fest, ab welchem Restbestand Artikel nachbestellt werden

[.instruction]
Meldebestand und Bestellmengenvorschlag festlegen:

. Öffne das Menü *Einrichtung » Waren » Bestellwesen » Nachbestellung » Einstellungen*.
. Nimm die Einstellungen anhand der Informationen in <<tabelle-meldebestand-bestellvorschlag-nachbestellung>> vor.
. *Speichere* die Einstellungen.

[[tabelle-meldebestand-bestellvorschlag-nachbestellung]]
.Vorbereitende Einstellungen für das Bestellwesen
[cols="1,3"]
|====

|Einstellung |Erläuterung

|*Standard-Status*
|Wähle einen Standard-Status, der beim Anlegen einer Nachbestellung vorausgewählt sein soll. Wie du spezielle Status für Nachbestellungen anlegst, erfährst du im Kapitel <<#120, Status für Nachbestellungen anlegen>>.

|*Standard-Eigner*
|Wähle eine der verfügbaren Optionen aus. +
*Aktiver Benutzer vorausgewählt*: Der Benutzer, der die Nachbestellung im plentymarkets Backend anlegt, wird im Feld *Eigner* vorausgewählt. +
*Kein Eigner vorausgewählt*: Bei dieser Auswahl bleibt das Feld *Eigner* beim Anlegen einer Nachbestellung leer.

|*Abverkaufszeitraum*
|Einen Zeitraum wählen. Der Zeitraum gibt vor, welcher Zeitraum für die Berechnung des durchschnittlichen Abverkaufs berücksichtigt wird. Dieser Durchschnittsverkauf fließt in die Berechnung des Nachbestellungsvorschlags von Varianten ein. Der Nachbestellungsvorschlag wird dir im Menü *Waren » Warenbestände* für die einzelnen Varianten angezeigt.

|*Voreingetragener Wert für Meldebestand/Bestellmenge*
a|Diese Einstellung bestimmt, wie die Bestellmenge im Nachbestellungsvorschlag berechnet wird. +
Du kannst wählen zwischen: +
*Meldebestand - Nettobestand - bestellte Menge* oder +
*(Meldebestand - Nettobestand - bestellte Menge) + (Durchschnittsverbrauch * (Wiederbeschaffungszeit + Lagerreichweite))* +
 +
Berechnungsparameter für den Bestellmengenvorschlag:

* *Meldebestand* = Bestandsmenge, bei der nachbestellt werden soll. Du kannst entweder einen statischen oder dynamischen Meldebestand einstellen.
* *Nettobestand* = Verkaufbare Menge des Lagerbestands.
* *Bestellte Menge* = Bereits nachbestellt, aber noch nicht geliefert.
* *Durchschnittsverbrauch* = Tagesdurchschnittsverkaufsmenge. Den Zeitraum, der zum Ermitteln des Tagesdurchschnitts verwendet wird, legst du mit dem Abverkaufszeitraum fest.
* *Wiederbeschaffungszeit* = Lieferzeit eines Lieferanten. In einer Variante im Tab *Lieferant* wird die Lieferzeit in Tagen eingetragen.
* *Lagerreichweite* = Eingetragene Lagerreichweite. Die Lagerreichweite wird pro Variante und Lager im Tab *Lager* einer Variante eingetragen und stellt einen Reichweitenwunsch dar, anhand dessen der Bestellmengenvorschlag ermittelt wird.

|====

[#120]
=== Status für Nachbestellungen anlegen
In deinem plentymarkets System sind bestimmte Auftragsstatus voreingestellt. Diese voreingestellten Status stehen dir auch für die Nachbestellungen zur Verfügung. Du kannst aber auch beliebig viele individuelle Status für verschiedene Verwendungszwecke anlegen. Das Anlegen neuer Status wird im dazugehörigen Kapitel auf der Handbuchseite <<auftraege/auftraege-verwalten#1200, Aufträge verwalten>> beschrieben.

[TIP]
.Eigene Status für Nachbestellungen anlegen
====
Wir empfehlen, separate Status anzulegen, die du ausschließlich für den Auftragstyp *Nachbestellung* nutzt. Stelle sicher, dass sich mittels unterschiedlicher Namensgebung die Status der Nachbestellungen von den Status der weiteren Auftragstypen unterscheiden.
====

[#130]
=== Tags für Nachbestellungen anlegen
Tags sind Kennzeichnungen, die du zentral in deinem plentymarkets System anlegst und anschließend für verschiedene Bereiche nutzen kannst. Möchtest du Nachbestellungen mit Tags versehen, musst du diese Tags zuvor im Menü *Einrichtung » Einstellungen » Tags* anlegen. Folge der Anleitung auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/tags#, Tags>>.

[#140]
=== Dokument Nachbestellung einrichten
Als Bestellschein für die Nachbestellung wird der speziell dafür vorgesehene Dokumententyp *Nachbestellung* genutzt. Dieses Dokument enthält alle nachzubestellenden Artikel und wird von dir als Händler an deinen Lieferanten übermittelt.

[WARNING]
.Dokumentenvorlage muss eingerichtet sein
====
Vor der erstmaligen Nutzung des Dokuments *Nachbestellung* muss zwingend die Dokumentenvorlage eingestellt werden. Solange keine Vorlage eingerichtet wurde, kann der Bestellschein nicht erzeugt werden.
====

Im Folgenden wird beschrieben, wie du die einfache Standard-Vorlage übernimmst, die in deinem plentymarkets System bereits hinterlegt ist.

[.instruction]
Dokumentenvorlage für das Dokument *Nachbestellung* einrichten:

. Öffne das Menü *Einrichtung » Waren » Bestellwesen » Nachbestellung » Dokumente » Nachbestellung*.
. Öffne das Tab *Transfer*.
. Wähle über dem Tab-Titel die Sprache.
. Klicke im Bereich *Einstellungen aus Standard-Dokumentenvorlage* auf *Übernehmen*. +
→ Die Standard-Einstellungen werden auf das Dokument angewendet.

Möchtest du das Dokument *Nachbestellung* individueller gestalten, das Logo deiner Firma oder zusätzliche Informationen darauf abbilden, gehe analog zu den Anleitungen auf der Handbuchseite zum Thema <<auftraege/auftragsdokumente#300, Auftragsdokumente>> vor.

[#150]
=== Versand des Bestellscheins vorbereiten
Nachdem du im vorherigen Schritt die Dokumentenvorlage für den Bestellschein eingerichtet hast, solltest du im Folgenden noch Einstellungen zum Versand des Dokuments vornehmen, damit dein Lieferant die Nachbestellung auch erhält. Hierfür richtest du zunächst eine E-Mail-Vorlage ein, die den Bestellschein als PDF-Anhang enthält.

[.instruction]
E-Mail-Vorlage einrichten:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Klicke auf *Neue E-Mail-Vorlage*.
. Trage einen Namen ein, z.B. "Bestellschein an Lieferant".
. Wähle die oder den Eigner aus, für den oder die die E-Mail-Vorlage verfügbar sein soll.
. *Speichere* die Einstellungen.
. Wähle aus der Dropdown-Liste *PDF-Anhang* die Option *Nachbestellung (PDF)*.
. Wechsle in das Tab *E-Mail-Nachricht*.
. Trage einen Betreff ein.
. Trage den Text ein, den die E-Mail-Vorlage enthalten soll.
. *Speichere* die Einstellungen.

Im zweiten Schritt kannst du den Versand des Bestellscheins an den Lieferanten automatisieren. So wird direkt nach dem Erzeugen des Bestellscheins das Dokument automatisch per E-Mail an deinen Lieferanten gesendet.

Richte dir dazu die folgende Ereignisaktion ein.

[.collapseBox]
.Senden des Bestellscheins an Lieferanten automatisieren:
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*.  +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-bestellschein-an-lieferant>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-bestellschein-an-lieferant>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
[[tabelle-ereignisaktion-bestellschein-an-lieferant]]
.Ereignisaktion zum automatischen Senden eines Bestellscheins an Lieferanten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Bestellwesen > Nachbestellungsdokument generiert*
|

|*Filter*
|*Auftragstyp > Bestellung, Typ Nachbestellung*

|*Aktion*
|*E-Mail versenden > Eigene Vorlage "Bestellschein an Lieferant"*
|
|====

[#160]
=== Meldebestand einer Variante festlegen
Möchtest du zuverlässig benachrichtigt werden, sobald es Zeit wird, einzelne Varianten nachzubestellen, solltest du in deinem plentymarkets System für jede Variante einen Meldebestand pflegen. Der Meldebestand zeigt an, bei welcher Menge einer Variante eine Nachbestellung veranlasst werden sollte.

[TIP]
.Lager hinzufügen, um Meldebestand einzutragen
====
Ein statischer Meldebestand lässt sich nur eingeben, wenn der Variante ein Lager zugeordnet ist. Wenn kein Lager zugeordnet ist, füge zunächst das Lager hinzu.
====

[.instruction]
Statischen Meldebestand eintragen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Lager*.
. Trage eine Menge unter *Meldebestand* ein.
. *Speichere* die Einstellung.

[TIP]
.Artikel, die den Meldebestand unterschreiten, direkt auf der Startseite anzeigen
====
Auf der Startseite deines Systems kanst du anzeigen, wie viele Varianten eines Lagers den Meldebestand unterschritten haben. Füge dafür das Element *Artikel unter Meldebestand* hinzu. Ein Klick auf die Anzahl der Varianten öffnet das Menü *Waren » Warenbestände* und filtert nach Varianten unter Meldebestand.
====

[#dynamischerMeldebestand.subhead]
Aktuelle Umsetzung des dynamischen Meldebestand

Pro Lager kannst du entscheiden, ob du den dynamischen Meldebestand nutzt oder nicht. Wenn du den dynamischen Meldebestand nutzt, berechnet dein System den dynamischen Meldebestand jede Nacht im Hintergrund. Dieser berechnete dynamische Meldebestand wird noch in keinem Feld dargestellt, d.h. du siehst den Wert nicht. Die Differenz zum Meldebestand, MeldΔ, basiert jedoch auf dem berechneten Meldebestand. Die Differenz wird Ihnen z.B. in der Bestandsübersicht angezeigt. So kannst du anhand der Differenz absehen, wann eine Nachbestellung erfolgen sollte.

[IMPORTANT]
.Wenn dynamischer Meldebestand genutzt wird, keinen statischen Meldebestand pflegen
====
Wenn du den dynamischen Meldebestand nutzt, darfst du manuell keinen statischen Meldebestand eintragen. Belasse den Meldebestand für die Varianten in dem Lager auf 0. Wenn ein Meldebestand größer als 0 gespeichert ist, wird die Berechnung des dynamischen Meldebestands nicht ausgeführt.
====

Der dynamische Meldebestand wird jede Nacht anhand der folgenden Formel berechnet:

latexmath:[\mbox{Dynamischer Meldebestand} = {(\mbox{Ø Abverkauf} \cdot \mbox{Lagerreichweite}) + (\mbox{Ø Abverkauf} \cdot \mbox{kürzeste Lieferzeit})}]

Erläuterung der Formelparameter:

* Ø Abverkauf = durschnittlich verkaufte Menge
* kürzeste Lieferzeit = kürzeste Lieferzeit einer Variante egal von welchem Lieferanten

Die Differenz zum dynamischen Meldebestand (MeldΔ) wird im System dargestellt und berechnet sich folgendermaßen:

latexmath:[\mbox{MeldΔ} = {(\mbox{dynamischer Meldebestand} - (\mbox{Nettobestand} + (\mbox{nachbestellte Menge})}]

Die Einstellung für den dynamischen Meldebestand triffst du für jedes Lager in den <<warenwirtschaft/lager-einrichten#300, Lagereinstellungen>>.

[#170]
=== Mindestabnahme einer Variante festlegen

Die Mindestabnahme ist die Menge, die du deinem Lieferanten mindestens abnehmen musst, wenn du bei ihm bestellst. Wenn du eine Mindestabnahme für eine Variante einträgst, entspricht der Bestellmengenvorschlag für die Variante mindestens dieser Mindestabnahme. Ein Bestellmengenvorschlag wird wiederum nur angezeigt, wenn der Meldebestand erreicht wurde.

[TIP]
.Lieferant hinzufügen, um Mindestabnahme einzutragen
====
Eine Mindestabnahme lässt sich nur eingeben, wenn der Variante ein Lieferant zugeordnet ist. Wenn kein Lieferant zugeordnet ist, füge zunächst den Lieferanten hinzu.
====

[.instruction]
Mindestabnahme festlegen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Lieferant*.
. Trage eine Menge unter Mindestabnahme ein.
. *Speichere* die Einstellung.

Wenn weder eine Mindestabnahme noch ein Meldebestand für eine Variante eingetragen ist, beträgt der Vorschlag 0.

[#200]
== Varianten für die Nachbestellung identifizieren
Für eine gut funktionierende Warenwirtschaft ist es wichtig, nachzubestellende Varianten zeitnah zu ermitteln. So vermeidest du, dass dir Artikel ausgehen und verhinderst somit unnötig lange Lieferzeiten bei deinen Kunden.

Am einfachsten erkennst du nachzubestellende Varianten daran, dass sie den Meldebestand erreicht haben. Arbeitest du nicht mit dem Meldebestand, kannst du alternativ nach dem Netto-Warenbestand filtern.

[.instruction]
Varianten für die Nachbestellung identifizieren:

. Öffne das Menü *Waren » Warenbestände*.
. Wähle für den Filter *Beschränkung* die Option *Meldebestand erreicht/unterschritten*. +
(icon:map-signs[]) *_Oder:_* Wähle die Option *Negativer Netto-Warenbestand oder Netto-Warenbestand gleich 0*, wenn du den Meldebestand nicht nutzt.
. Wähle optional ein Lager.
. Klicke auf *Suchen*. +
→ Eine Liste mit Artikeln, die nachbestellt werden sollten, erscheint.

[#300]
== Nachbestellung anlegen
Je nach Bedarf bietet dir dein plentymarkets System verschiedene Möglichkeiten an, Nachbestellungen anzulegen. Die folgenden Kapitel beschreiben kurz diese Möglichkeiten.

[#310]
=== Artikel unter Meldebestand nachbestellen
Im Folgenden wird beschrieben, wie du eine Nachbestellung für Artikel anlegst, die den Meldebestand unterschritten haben. Im Kapitel <<#200, Varianten für die Nachbestellung identifizieren>> wurde bereits beschrieben, wie du herausfindest, welche Artikel den Meldebestand erreicht oder unterschritten haben. Die folgenden Schritte schließen sich an das Filtern an.

[.instruction]
Nachbestellung anlegen:

. Öffne das Menü *Waren » Warenbestände*.
. Führe wie im Kapitel <<#200, Varianten für die Nachbestellung identifzieren>> beschrieben eine Suche nach Artikeln durch, die den Meldebestand erreicht oder untschritten haben.  +
. Klicke auf *Vorschläge übernehmen*, um den errechneten Bestellmengenvorschlag zu übernehmen. +
→ Trage bei Bedarf eigene Werte ein.
. Klicke auf *Bestellung erstellen*. +
→ Die Nachbestellung wird geöffnet.

[#320]
=== Artikel pro Lager und Lieferant nachbestellen
Es kann vorkommen, dass du eine Nachbestellung bezogen auf ein spezielles Lager oder einen speziellen Lieferanten anlegen möchtest. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Artikel pro Lager und Lieferant nachbestellen:

. Öffne das Menü *Waren » Bestellwesen » Bestellung*.
. Klicke auf das *grüne Plus*.
. Klicke auf *Neue Nachbestellung*.
. Wähle im Feld *Lieferant* den Lieferanten aus dem Dropdown-Menü aus.
. Wähle im Feld *Lager* das Ziellager aus, an das die Nachbestellung geliefert werden soll.
. *_Optional:_* Wähle ein oder mehrere *Tags* für die neue Nachbestellung aus.
. *_Optional:_* Gib im Feld *Eigner* einen Eigner, also den bearbeitenden Nutzer, ein.
. *Speichere* die Nachbestellung.

Befolge anschließend die in den Kapiteln <<#400, Auftragspositionen hinzufügen>> bis <<#1000, Nachbestellung abschließen>>, um die Nachbestellung vollständig zu durchlaufen.

[#330]
=== Artikel aus einem Auftrag nachbestellen
Es ist möglich, direkt aus einem regulären Auftrag hinaus eine Nachbestellung für eine oder mehrere Artikel anzulegen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Artikel aus einem Auftrag nachbestellen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, für den du Artikel nachbestellen möchtest.
. Öffne das Tab *Nachbestellung* des Auftrags.
. Klicke auf *Alle Positionen nachbestellen*. +
(icon:map-signs[]) *_Oder:_* Wenn nicht alle im Auftrag enthaltenen Positionen nachbestellt werden sollen, wähle die nachzubestellenden Auftragspositionen aus und klicke auf *Markierte Positionen nachbestellen*. +
→ Die Nachbestellung wird geöffnet.

Befolge anschließend die in den Kapiteln <<#400, Auftragspositionen hinzufügen>> bis <<#1000, Nachbestellung abschließen>>, um die Nachbestellung vollständig zu durchlaufen.

[TIP]
.Zuordnung der Nachbestellung zum Auftrag
====
Bei Artikeln, die du wie oben beschrieben aus einem bestehenden Auftrag bestellst, wird der nachbestellte Bestand direkt dem entsprechenden Auftrag zugeordnet. Dies erkennst du in der Nachbestellung im Bereich *Auftragspositionen* am Einkaufswagen-Icon, das vor der Variante angezeigt wirst. Ein Klick auf das Icon zeigt dir im Tooltip die ID des Auftrags an und öffnet den Tab *Übersicht* des bestehenden Auftrags.
====

[#340]
=== Einzelne Variante nachbestellen
Diese Methode bietet sich an, wenn du gezielt nur eine Variante eines Artikels nachbestellen möchtest. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Einzelne Variante nachbestellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel, den du nachbestellen möchtest.
. Öffne die Variante, die du nachbestellen möchtest.
. Öffne das Tab *Bestand* der Variante.
. Öffne das Untertab *Warenbestand*.
. Klicke auf *Vorschläge übernehmen* oder trage eine *Menge* ein.
. Klicke auf *Bestellung erstellen*. +
→ Die Nachbestellung wird geöffnet.

Befolge anschließend die in den Kapiteln <<#400, Auftragspositionen hinzufügen>> bis <<#1000, Nachbestellung abschließen>>, um die Nachbestellung vollständig zu durchlaufen.

[#400]
== Auftragspositionen hinzufügen
Oben wurden die verschiedenen Wege beschrieben, wie du eine Nachbestellung in deinem plentymarkets System anlegen kannst. Du kannst nun weitere nachzubestellende Artikel in Form von Auftragspositionen hinzufügen.

[.instruction]
Auftragspositionen hinzufügen:

. Klicke im Bereich *Auftragspositionen* auf *Hinzufügen*. +
→ Ein Menü zum Hinzufügen der Artikelpositionen öffnet sich.
. Wähle einen der <<tabelle-filter-artikelsuche-nachbestellung>> beschriebenen Filter zur Artikelsuche.
. Gib einen zum Filter passenden Suchbegriff im Feld *Artikel suchen* ein.
. Klicke auf *Suchen*. +
. Gib die nachzubestellende Anzahl in der Spalte *Menge* der nachzubestellenden Variante ein.
. Klicke auf das *Warenkorb-Icon*. +
→ Die Varianten werden dem Warenkorb hinzugefügt.
. Wiederhole die oben beschriebenen Schritte, bis alle nachzubestellenden Artikelvarianten in der gewünschten Menge im Warenkorb enthalten sind.
. Klicke im Bereich *Warenkorb* auf *Speichern*. +
→ Der Warenkorb wird gespeichert. +
→ Die Nachbestellung wird geöffnet.

[[tabelle-filter-artikelsuche-nachbestellung]]
.Verfügbare Filter in der Artikelsuche
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Artikel-ID*
|ID eingeben, um nach dem Artikel mit dieser ID zu suchen.

|*Varianten-ID*
|ID eingeben, um nach der Variante mit dieser ID zu suchen.

|*Variantennummer*
|Variantennummer eingeben, um nach der Variante mit dieser Nummer zu suchen.

|*Barcode*
|Barcode eingeben, um nach der Variante mit diesem Code zu suchen.

|*Artikelname*
|Artikelnamen eingeben, um nach dem Artikel mit diesem Namen zu suchen.

|*Lieferantennummer*
|Nummer des Lieferanten eingeben, um nach Artikeln mit dieser Lieferantennummer zu suchen.

|*Lager*
|Name des Lagers eingeben, um nach Artikeln zu suchen, die mit diesem Lager verknüpft sind.

|====

[#500]
== Auftragspositionen bearbeiten
Nachdem du die gewünschten Artikel zum Warenkorb hinzugefügt hast, kannst du sie im Bereich *Auftragspositionen* noch bearbeiten. Für jeden Artikel wird dir beispielsweise die Option *Löschen* angezeigt, mit der du die Auftragspositionen entfernen kannst.
Im Feld *Einkaufspreis* kannst du den voreingetragenen Einkaufspreis ändern, falls dein Lieferant dir beispielsweise kurzfristig einen veränderten Preis zugesagt hat.

[IMPORTANT]
.Einkaufspreis für Varianten bearbeiten
====
Das Bearbeiten des Einkaufspreises kann Auswirkungen auf deine im System gespeicherten Preise haben.
Ist im Menü *Einrichtung » Waren » Warenbestand » Wareineingang* für den *Einkaufspreis* eine der Optionen *Einkaufspreis auf Variante übertragen* oder *Einkaufspreis auf Variante und Lieferant übertragen* aktiviert, wird der an der Variante hinterlegte Einkaufspreis durch deine Eingabe während der Nachbestellung überschrieben. Genauere Informationen dazu findest du auf der Handbuchseite <<warenwirtschaft/wareneingaenge-verwalten#300, Wareneingänge verwalten>>.
====

Hast du alle notwendigen Änderungen an den Auftragspositionen vorgenommen, drücke im Bereich *Warenkorb* auf *Speichern*.

[#600]
== Weitere Informationen hinterlegen
Der Bereich *Details* bietet dir die Möglichkeit, zur besseren Übersicht weitere Informationen an der Nachbestellung zu hinterlegen. <<tabelle-weitere-informationen-nachbestellung>> beschreibt die möglichen Informationen.

[[tabelle-weitere-informationen-nachbestellung]]
.Weitere Informationen für die Nachbestellung
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Lieferdatum*
|Manuell das Lieferdatum wählen, soweit es vom Händler mitgeteilt wurde. Alternativ über die Funktion *Lieferdatum ermitteln* nutzen. Das System berechnet dann auf Basis der *Lieferzeit*, die im Tab *Lieferant* der Varianten hinterlegt ist, das voraussichtliche Lieferdatum. Weitere Informationen zum Hinterlegen der Lieferzeit an der Variante findest du auf der Handbuchseite <<artikel/artikel-verwalten#180, Artikel verwalten>>.

|*Händlerzeichen*
|Das zum Lieferanten gehörende Händlerzeichen eingeben.

|*Eigner*
|Benutzer auswählen, der als Eigner der Nachbestellung festgelegt werden soll. Alternativ werden hier, falls festgelegt, der <<#200, Standard-Eigner>> angezeigt.

|*Währung*
|Standardmäßig ist in diesem Feld die Systemwährung voreingestellt. Bei Bedarf eine abweichende *Währung* des Lieferanten plus den geltenden *Wechselkurs* für die gewählte Währung eingeben. Oben im Bereich *Details* der Nachbestellung wird dann der aktuell berechnete *Nettowarenwert* angezeigt.

|====

[#700]
== Nachbestellung auslösen und übermitteln
Nachdem du alle nachzubestellenden Varianten zur Nachbestellung hinzugefügt hast, setzt du das Bestelldatum. Klicke dazu auf den Button *Bestellung auslösen* im Bereich *Details*.

Nach dem Auslösen der Nachbestellung musst du noch deine Nachbestellung an den Lieferanten übermitteln. Dazu erstellst du den Bestellschein in Form des Dokuments *Nachbestellung*. Im Kapitel <<#150, Versand der des Bestellscheins vorbereiten>> wurde bereits beschrieben, wie du die Dokumentenvorlage einrichtest und das Dokument automatisch an deinen Lieferanten übermittelst. Im Folgenden findest du jeweils eine Anleitung zum manuellen und zum automatisierten Erzeugen des Dokuments.

[WARNING]
.Auftragspositionen nicht mehr editierbar
====
Sobald du das Bestelldatum gesetzt hast, kannst du in der Nachbestellung keine Auftragspositionen mehr hinzufügen oder löschen. Setze das Datum also erst nach sorgfältiger Prüfung!
====

[#710]
=== Bestellschein manuell erstellen
Gehe wie im Folgenden beschrieben vor, um den Bestellschein manuell zu erzeugen. Je nach Workflow kannst du auch einen Bestellschein hinterlegen, falls dir das Dokument vom Lieferanten übermittelt wurde.

[.instruction]
Bestellschein manuell erzeugen:

. Öffne den Bereich *Dokumente*.
. Klicke auf *Dokument hinzufügen*.
. Wähle die Option *Bestellschein erzeugen*. +
(icon:map-signs[]) *_Oder:_* Wähle die Option *Bestellschein hochladen*, um einen vom Lieferanten erstellten Bestellschein hochzuladen. +
→ Der Bestellschein wird erstellt und ist im Bereich *Dokumente* verfügbar.
. Klicke auf *Aktionen*, um das Dokument herunterzuladen oder zu löschen.

[#720]
=== Bestellschein automatisch erzeugen
Richte die folgende Ereignisaktion ein, um den Bestellschein automatisch zu erzeugen, sobald du das Bestelldatum gesetzt hast.

[.collapseBox]
.Erzeugen des Bestellscheins automatisieren:
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*.  +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-bestellschein-erzeugen>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-bestellschein-erzeugen>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
[[tabelle-ereignisaktion-bestellschein-erzeugen]]
.Ereignisaktion zum automatischen Erzeugen des Bestellscheins
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Bestellwesen > Bestellung ausgelöst*
|

|*Filter*
|*Auftragstyp > Bestellung, Typ Nachbestellung*

|*Aktion*
|*Bestellwesen > Nachbestellungsdokument erzeugen*
|
|====

[TIP]
.Bestellschein automatisch an den Lieferanten senden
====
Möchtest du im Anschluss an das automatische Erzeugen des Bestellscheins diesen auch automatisiert an den Lieferanten senden, richte zusätzlich die im Kapitel <<#150, Versand des Bestellscheins vorbereiten>> beschriebene Ereignisaktion ein.
====

[#800]
== Rückstandsliste nutzen
Wenn du eine große Anzahl von Artikeln nachbestellt hast oder viele Nachbestellungen parallel laufen, nutze die Rückstandsliste, um den Überblick über nachbestellte, aber noch nicht gelieferte Artikel zu behalten. Diese Artikel werden dir im Menü *Waren » Bestellwesen » Rückstandsliste* angezeigt. Weitere Informationen zur Rückstandsliste findest du auf der Handbuchseite <<warenwirtschaft/nachbestellungen-verwalten/rueckstandsliste-verwalten#, Rückstandsliste verwalten>>.

[#900]
== Waren einbuchen
Sobald die nachbestellten Artikel in deinem Lager eintreffen, müssen diese eingebucht werden. Je nachdem, ob du alle Artikel der Nachbestellung in einer zusammenhängenden Lieferung oder in separaten Lieferungen erhältst, buchst du entweder Teilmengen oder alle Artikel in einem Schritt ein.

[IMPORTANT]
.Lagerort für die Einbuchung
====
Pflegst du keine separaten Lager und Lagerorte für deine Artikel in deinem plentymarkets System, werden die Artikel beim Einbuchen auf den im System standardmäßig vorhandenen Standard-Lagerort gebucht.
====

[#910]
=== Teilmengen einbuchen
Gehe wie im Folgenden beschrieben vor, um Teilmengen aus verschiedenen Lieferungen derselben Nachbestellung einzubuchen.

[.instruction]
Teilmengen einbuchen:

. Öffne das Menü *Waren » Bestellwesen » Bestellung*.
. Öffne die Nachbestellung, zu der Waren eingebucht werden sollen.
. Öffne den Bereich *Auftragspositionen*.
. Trage in der Spalte *Teilmenge* die Anzahl der gelieferten Artikelpositionen ein.
. Klicke auf *Warenbewegungen anlegen*. +
→ Die Warenbewegungen werden angelegt.
. Gehen zum Bereich *Warenbewegungen*. Dort erkennst du an der grünen Markierung die vorbereiteten Wareneingänge.
. Gib in der Spalte *Lagerort* die ID des Lagerorts an, in den die Artikel eingebucht werden sollen.
. Setze jeweils ein Häkchen in der Zeile mit der einzubuchenden Artikelvariante.
. Gib im Feld *Lieferschein-Nr.* die Nummer des Bestellscheins ein, der zur Nachbestellung gehört.
. Klicke auf *Markierte Warenbewegungen buchen*. +
→ Die Teilmenge wird auf die angegebenen Lagerorte gebucht.

[#920]
=== Alle Artikel einbuchen
Gehe wie im Folgenden beschrieben vor, um alle in der Nachbestellung enthaltenen Artikel gleichzeitig einzubuchen.

[.instruction]
Vollständige Menge einbuchen:

. Öffne das Menü *Waren » Bestellwesen » Bestellung*.
. Öffne die Nachbestellung, zu der Waren eingebucht werden sollen.
. Öffne den Bereich *Auftragspositionen*.
. Trage in der Spalte *Teilmenge* die Anzahl der vollständig gelieferten Artikel ein.
. Klicke auf *Warenbewegungen anlegen*. +
→ Die Warenbewegungen werden angelegt.
. Gehen zum Bereich *Warenbewegungen*. Dort erkennst du an der grünen Markierung die vorbereiteten Wareneingänge.
. Gib in der Spalte *Lagerort* die ID des Lagerorts an, in den die Artikel eingebucht werden sollen.
. Gib im Feld *Lieferschein-Nr.* die Nummer des Bestellscheins ein, der zur Nachbestellung gehört.
. Klicke auf *Alle Warenbewegungen buchen*. +
→ Die vollständige Menge wird auf die angegebenen Lagerorte gebucht.

[#1000]
== Nachbestellung abschließen
Sobald du alle in der Nachbestellung enthaltenen Artikel erhalten und eingebucht hast, schließt du die Nachbestellung ab. Klicke dazu oben im Bereich *Details* der Nachbestellung auf *Bestellung abschließen*. Das aktuelle Datum wird als Abschlussdatum gesetzt und die Nachbestellung für die Bearbeitung gesperrt.

[TIP]
.Sperrung der Nachbestellung aufheben
====
Hast du die Nachbestellung versehentlich abgeschlossen, klicke erneut auf das Icon. So wird die Nachbestellung entsperrt und einzelne Informationen können erneut bearbeitet werden.
====

Schließe die Nachbestellung auch ab, wenn einzelne Artikel aus der Nachbestellung voraussichtlich nicht mehr nachgeliefert werden können, zum Beipiel aufgrund von Verlust auf dem Versandweg. So werden die ausstehenden Auftragspositionen auch aus der <<warenwirtschaft/nachbestellungen-verwalten/rueckstandsliste-verwalten#, Rückstandliste>> entfernt.

[#1100]
== Nachbestellung suchen
Beim Öffnen des Menüs *Waren » Bestellwesen » Bestellung* werden dir alle Nachbestellungen und <<warenwirtschaft/umbuchungen-vornehmen#, Umbuchungen>> angezeigt. Das Ergebnis kannst du durch Verändern der Filter einschränken, um so entweder alle oder ein weiter eingeschränktes Ergebnis anzuzeigen.

[.instruction]
Nachbestellung suchen:

. Öffne das Menü *Waren » Bestellwesen » Bestellung* +
. Wähle einen oder mehrere der in <<tabelle-nachbestellung-suchen-filter>> beschriebenen Filter, um die Ergebnisse einzugrenzen.
. Klicke auf *Suchen*.

[[tabelle-nachbestellung-suchen-filter]]
.Verfügbare Filter zum Suchen einer Nachbestellung
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Auftrags-ID*
|Auftrags-ID der Nachbestellung eingeben, um die Nachbestellung zu suchen.

|*Auftrags-Typ*
|Auftrags-Typ *Nachbestellung* eingeben, um nur Aufträge vom Typ *Nachbestellung* anzuzeigen.

|*Artikel-ID*
|Artikel-ID eingeben, um Nachbestellungen zu suchen, die einen Artikel mit dieser ID enthalten.

|*Varianten-ID*
|Varianten-ID eingeben, um Nachbestellungen zu suchen, die eine Variante mit dieser ID enthalten.

|*Variantennumer*
|Variantennummer eingeben, um Nachbestellungen zu suchen, die eine Variante mit dieser Nummer enthalten.

|*Artikeldaten*
|Suchbegriffe oder Zahlenwerte eintragen, um Nachbestellungen zu suchen, die Artikel mit diesen Daten enthalten. Durchsucht werden folgende Datenfelder: *Artikel-ID*, *Artikelnummer* und *Name*. Beschreibungstexte wie der Artikeltext und der Vorschautext werden nicht durchsucht.
Zusätzlich den Filter *Auftrags-Typ* auf die Option *Nachbestellung* setzen.

|*Status*
|Einen Status aus der Liste auswählen. Zusätzlich den Filter *Auftrags-Typ* auf die Option *Nachbestellung* setzen, um Nachbestellungen mit diesem Status zu suchen.

|*Eigner*
|Einen Eigner aus der Liste auswählen. Zusätzlich den Filter *Auftrags-Typ* auf die Option *Nachbstellung* setzen, um Nachbestellungen mit diesem Eigner zu suchen.

|*Auftragsdatum von ... bis*
|Start- und Enddatum aus dem Kalender wählen. Diese Angabe grenzt den Zeitraum auf das Bestelldatum der Nachbestellung ein.

|====

[#1200]
== Nachbestellungen automatisieren
Mithilfe der in plentymarkets verfügbaren Ereignisaktionen kannst du die einzelnen Arbeitsschritte einer Nachbestellung automatisieren. Eine Möglichkeit zur Automatisierung des Bestellscheins wurde bereits im Kapitel <<#720, Bestellschein automatisch erzeugen>> beschrieben. Im Menü *Einrichtung » Aufträge » Ereignisse* stehen dir in den Ereignis-, Filter- und Aktionsgruppen *Bestellwesen* weitere Optionen zur Automatisierung einzelner Arbeitsschritte der Nachbestellung zur Verfügung. +

Genauere Informationen zu diesen Einstellungsmöglichkeiten findest du auf der Handbuchseite <<automatisierung/ereignisaktionen#, Ereignisaktionen>>. Arbeitest du zum ersten Mal mit den Ereignisaktionen, findest du genauere Informationen zum Anlegen von Ereignisaktionen im Kapitel <<automatisierung/ereignisaktionen#100, Neue Ereignisaktion anlegen>>.
