= Die plentyWarehouse App (Beta)
:lang: de
include::{includedir}/_header.adoc[]
:keywords: 
:position: 100
:nav-alias: Übersicht
:id: CLMUE7M
:url: warenwirtschaft/plentywarehouse
:author: team-mobile

[#100]
== Warum solltest du die plentyWarehouse App nutzen

Die neu entwickelte plentyWarehouse App bietet dir zahlreiche Möglichkeiten, die mobile Warenwirtschaft einfach und effizient abzuwickeln. Viele Funktionen werden vorherigen Nutzer:innen der bestehenden plentymarkets App bekannt sein. Nach und nach überführen wir alle Funktionen zur Warenwirtschaft aus der plentymarkets App in die neue plentyWarehouse App. Dabei legen wir Wert auf intuitive Bedienkonzepte, eine stabile Performance und eine zuverlässige, hochaktuelle technische Basis. Von all diesen Vorteilen und einer Reihe ganz neuer Entwicklungen kannst du profitieren, indem du die plentyWarehouse App herunterlädst. 

[IMPORTANT]
.Hinweise zum aktuellen Stand der plentyWarehouse App
====
Die plentyWarehouse App befindet sich in der offenen Beta-Phase. Das bedeutet, dass wir fortlaufend Anpassungen und Fehlerbehebungen vornehmen und schrittweise neue Versionen veröffentlichen, die diese Änderungen enthalten. Ebenso werden die enthaltenen Funktionen Schritt für Schritt erweitert. Feedback und Fragen nehmen wir in dieser Phase gern im link:https://forum.plentymarkets.com/c/app-pos/plentywarehouse/579[Forum^]{nbsp}icon:external-link[] entgegen. Dort findest du auch jederzeit aktuelle Informationen und Versionshinweise. 
====

[#200]
== Welche Funktionen bietet die plentyWarehouse App?

Aktuell beinhaltet die plentyWarehouse App folgende Funktionen. Klicke auf die einzelnen Einträge in der Liste, um zu den entsprechenden Handbuchseite mit weiteren Informationen und Anleitungen zu gelangen.

* <<warenwirtschaft/plentywarehouse/artikel-und-lagerorte#, Artikelsuche>>
* <<warenwirtschaft/plentywarehouse/artikel-und-lagerorte#, Lagerorte inspizieren>>
* <<warenwirtschaft/plentywarehouse/artikeletiketten-drucken#, Artikeletiketten drucken>>
* <<warenwirtschaft/plentywarehouse/umbuchen-und-verraeumen#, Artikel umbuchen und verräumen>>
* <<warenwirtschaft/plentywarehouse/inventur-durchfuehren#, Inventur durchführen>>

[#300]
== Die plentyWarehouse App herunterladen und installieren

// TODO: Direkten Downloadlink zum PlayStore einfügen

include::../app/_textblocks/hardware-voraussetzungen/hardware-plentywarehouse.adoc[]

[#400]
== Welche Schritte gehören zur Einrichtung?

Du hast die plentyWarehouse App heruntergeladen und auf der passenden Hardware installiert? Dann kannst du mit der Einrichtung fortfahren.

Auf der Handbuchseite <<warenwirtschaft/plentywarehouse/installation-und-ersteinrichtung#, Installation und Ersteinrichtung>> findest du alle detaillierte Informationen zum ersten Login in der App, zur allgemeinen Orientierung und zu den grundlegenden Einstellungen, die du in der plentyWarehouse App vornehmen musst.

[#500]
== Auf dem Laufenden bleiben





