= Umbuchungen vornehmen
:lang: de
include::{includedir}/_header.adoc[]
:description: Erfahren Sie, wie Sie mit Lager-Umbuchungen in Ihrem plentymarkets System arbeiten.
:keywords: Umbuchung, Lager-Umbuchung, Lagerort, Lagerorte, PO Lieferschein
:position: 35

Im Menü *Waren » Bestellung* bietet Ihnen Ihr plentymarkets System die Möglichkeit, Waren zwischen verschiedenen Lagern umzubuchen.

[#100]
== Vorbereitende Einstellungen
Um Ihre Arbeit mit den Lager-Umbuchungen optimal zu organisieren, sollten Sie einige vorbereitende Einstellungen vorzunehmen. Diese Einstellungen werden im Folgenden beschrieben. Erstellen Sie neue Status speziell für die Umbuchungen und legen Sie Tags an, um sich die Übersicht zu erleichtern. Verpflichtend ist zudem die Einrichtung einer Dokumentenvorlage für den *PO Lieferschein* als spezieller Lieferschein für die Umbuchung.

[#200]
=== Status für Umbuchungen vorbereiten
In Ihrem plentymarkets System sind bestimmte Auftragsstatus voreingestellt. Diese voreingestellten Status stehen Ihnen auch für die Umbuchungen zur Verfügung. Sie können für die Umbuchung gesonderte Status anlegen, die Sie dann ausschließlich für diesen Auftragstyp nutzen. Das Anlegen neuer Status wird im dazugehörigen Kapitel auf der Handbuchseite <<auftraege/auftraege-verwalten#1200, Aufträge verwalten>> beschrieben.

[TIP]
.Eigene Status für Umbuchungen anlegen
====
Wir empfehlen, separate Status anzulegen, die Sie ausschließlich für die Umbuchungen nutzen. So können Sie mittels unterschiedlicher Namensgebung die Status der Umbuchungen von den Status der weiteren Auftragstypen unterscheiden, beispielsweise bei der Automatisierung der Umbuchungen durch Ereignisaktionen.
====

[#300]
=== Tags anlegen
Tags sind Kennzeichnungen, die Sie zentral in Ihrem plentymarkets System anlegen und anschließend für verschiedene Bereiche nutzen können. Wenn Sie Umbuchungen mit Tags versehen , müssen Sie diese Tags zuvor im Menü *System » Systemeinstellungen » Einstellungen » Tags* anlegen. Folgen Sie dazu der Anleitung auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/tags#, Tags verwalten>>.

[#400]
=== Vorlage für PO Lieferschein einrichten
Für die Umbuchung können Sie den speziell dafür vorgesehenen Dokumententyp *PO Lieferschein* nutzen. Dieser Lieferschein listet die in der Umbuchung vorhandenen Auftragspositionen auf. So ist der Inhalt der Umbuchung beim Ausbuchen aus dem Senderlager und beim Einbuchen in das Empfängerlager für die Mitarbeiter im Lager nachvollziehbar.

[WARNING]
.Dokumentenvorlage muss eingerichtet sein
====
Vor der erstmaligen Nutzung des Dokumententyps *PO Lieferschein* muss zwingend die Dokumentenvorlage eingestellt werden. Solange keine Vorlage eingerichtet wurde, wird der Lieferschein bei der Umbuchung nicht erstellt.
====

Im Folgenden wird beschrieben, wie Sie die einfache Standard-Vorlage übernehmen, die in Ihrem plentymarkets System bereits hinterlegt ist.

[.instruction]
Dokumentenvorlage für PO Lieferschein einrichten

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente.*
. Wählen Sie den Menüpunkt *PO Lieferschein*.
. Öffnen Sie das Tab *Transfer*.
. Wählen Sie über dem Tab-Titel die *Sprache*.
. Klicken Sie im Bereich *Einstellungen aus Standard-Dokumentenvorlage* auf *Übernehmen*. +
→ Die Standard-Einstellungen werden auf das Dokument angewendet.

Möchten Sie das Dokument *PO Lieferschein* individueller gestalten, das Logo Ihrer Firma  oder zusätzliche Informationen darauf abbilden, gehen Sie analog zu den Anleitungen auf der Handbuchseite zum Thema <<auftraege/auftragsdokumente#300, Auftragsdokumente>> vor.

[#500]
== Umbuchung anlegen
Nachdem Sie die vorbereitenden Einstellungen vorgenommen haben, können Sie die eigentliche Lager-Umbuchung anlegen.

[.instruction]
Neue Umbuchung anlegen:

. Öffnen Sie das Menü *Waren » Bestellung*.
. Bewegen Sie die Maus über das *Plus-Icon* und klicken Sie auf *Neue Umbuchung*. +
→ Das Fenster zum Anlegen der Umbuchung öffnet sich.
. Wählen Sie im Feld *Status* einen [link]Status aus, mit dem die Umbuchung angelegt werden soll. Dieser Status ist später noch änderbar.
. Geben Sie im Feld *Sender* das Lager an, aus dem umgebucht werden soll.
. Geben Sie im Feld *Empfänger* das Lager an, in das umgebucht werden soll.
. Wählen Sie optional ein *Tag* für die neue Umbuchung aus.
. Geben Sie optional im Feld *Eigner* einen Eigner, also den bearbeitenden Nutzer, ein.

[IMPORTANT]
.Eigner auswählen
====
Fehlt die gewünschte Auswahl im Feld *Eigner*, liegt das daran, dass keine Benutzer Ihres plentymarkets Systems als Eigner aktiviert wurden. Eine Anleitung zum Aktivieren der Eigner finden Sie auf der Handbuchseite <<basics/admin-aufgaben/benutzer-verwalten#40, Benutzer verwalten>>.
====

[#600]
=== Auftragspositionen hinzufügen
Im nächsten Schritt fügen Sie die Auftragspositionen hinzu, die von einem Lager in ein anderes Lager umgebucht werden sollen.

[.instruction]
Auftragspositionen hinzufügen:

. Klicken Sie im Bereich *Auftragspositionen* auf *Hinzufügen*. +
→ Ein Suchfeld zum Hinzufügen der Artikelpositionen öffnet sich.
. Nutzen Sie die vorhandenen Filter zur Artikelsuche.
. Klicken Sie auf *Suchen*. +
→ Die Artikelvarianten, die im Senderlager Bestand haben, werden angezeigt.
. Geben Sie die umzubuchende Anzahl in der Spalte *Menge* der Variante ein.
. Klicken Sie auf das *Warenkorb-Icon*. +
→ Die Varianten werden dem Warenkorb hinzugefügt.
. Wiederholen Sie die Schritte, bis alle umzubuchenden Artikelvarianten in der gewünschten Menge im Warenkorb enthalten sind.
. Klicken Sie im Bereich *Warenkorb* auf *Speichern*. +
→ Der Warenkorb wird gespeichert. +
→ Die Umbuchung wird geöffnet.

[IMPORTANT]
.Ergebnisse der Artikelsuche
====
Die Artikelsuche in diesem Menü zeigt ausschließlich Artikelvarianten, die Bestand im Senderlager haben. Wird eine Artikelvariante nicht aufgeführt, überprüfen Sie den Bestand der Variante im Menü *Waren » Warenbestände* oder im Tab *Bestand* der Artikelvariante.
====

[#700]
=== PO Lieferschein erstellen
Nach dem Hinzufügen der Auftragspositionen werden die Warenbewegungen für die Ausbuchung bereits vorbereitet. Dies erkennen Sie an den roten Pfeilen in der Tabelle *Warenbewegungen*.
Überprüfen Sie hier unbedingt die vorbereiteten Warenbewegungen sowie die Mengen der einzelnen Artikelvarianten. Anschließend erstellen Sie einen *PO Lieferschein*, der die auszubuchenden Auftragspositionen enthält.

[.instruction]
PO Lieferschein erstellen:

. Öffnen Sie den Bereich *Dokumente*.
. Klicken Sie auf *Lieferschein hinzufügen*.
. Wählen Sie die Option *Lieferschein erzeugen*. +
→ Der PO Lieferschein wird erstellt.

Nach Erstellung ist der PO Lieferschein dauerhaft im Bereich *Dokumente* verfügbar und kann dort beliebig heruntergeladen oder gelöscht werden. Alternativ können in diesem Bereich bei Bedarf einen externen Lieferschein hochladen. Klicken Sie dazu auf *Lieferschein hinzufügen* und wählen die Option *Lieferschein hochladen*.

[#800]
=== Waren ausbuchen
Nach dem Erzeugen des PO Lieferscheins buchen Sie die Artikelpositionen aus dem Senderlager aus.

[WARNING]
.Umbuchung nicht mehr editierbar
====
Sobald Sie den nachfolgend beschriebenen Schritt ausgeführt haben, können Sie die Umbuchung *nicht* mehr bearbeiten. Artikelpositionen können dann weder gelöscht noch hinzugefügt werden. Buchen Sie die Waren deshalb erst nach sorgfältiger Prüfung aus!
====

[.instruction]
Waren ausbuchen:

. Klicken Sie im Bereich *Auftragsdetails* auf das *Zahnrad* neben dem Feld *Bestelldatum*. +
→ Die Umbuchung wird angelegt und der Warenausgang im Senderlager gebucht.

[#900]
=== Waren einbuchen
Die Auftragspositionen werden im Empfängerlager eingebucht. Gehen Sie dazu wie im Folgenden beschrieben vor:

[.instruction]
Waren einbuchen:

. Gehen Sie zum Bereich *Auftragspositionen*.
. Tragen Sie in der Spalte *Menge* die angelieferten Artikelpositionen ein.
. Klicken Sie auf *Warenbewegungen anlegen*. +
→ Die Warenbewegung wird angelegt.
. Gehen Sie zum Bereich *Warenbewegungen*. Dort erkennen Sie an der grünen Markierung die vorbereiteten Warenbewegungen.
. Geben Sie in der Spalte *Lagerort* einen Lagerort an.
. Setzen Sie jeweils ein Häkchen in der Zeile mit der einzubuchenden Artikelvariante.
. Geben Sie im Feld *Lieferschein-Nr.* die Nummer des PO Lieferscheins ein, der bei der Ausbuchung erstellt wurde.
. Klicken Sie auf *Warenbewegungen buchen*. +
→ Der Wareneingang wird im Empfängerlager gebucht.

[#1000]
=== Umbuchung abschließen
Wurde für alle Artikelvarianten im Empfängerlager der Wareneingang gebucht, sollten Sie die Umbuchung in Ihrem plentymarkets System abschließen. Gehen Sie dazu wie im Folgenden beschrieben vor:

[.instruction]
Umbuchung abschließen:

. Öffnen Sie die Umbuchung.
. Gehen Sie zum Bereich *Auftragsdetails*.
. Klicken Sie auf das *Zahnrad-Icon* neben dem Feld *Abschlussdatum*. +
→ Das aktuelle Datum wird automatisch als Abschlussdatum gesetzt. +
→ Die Umbuchung wird für die Bearbeitung gesperrt.

[TIP]
.Sperrung der Umbuchung aufheben
====
Haben Sie die Umbuchung versehentlich abgeschlossen, klicken Sie erneut auf das Icon. So wird die Umbuchung entsperrt und kann erneut bearbeitet werden.
====

[#1100]
== Umbuchungen automatisieren

Mithilfe der in plentymarkets verfügbaren Ereignisaktionen können Sie Umbuchungen automatisieren. Im Menü *System » Systemeinstellungen » Aufträge » Ereignisse* stehen Ihnen in den Ereignis-, Filter- und Aktionsgruppen *Bestellwesen* spezielle Einstellungen zur Automatisierung der Umbuchung zur Verfügung. +

Genauere Informationen zu diesen Einstellungsmöglichkeiten finden Sie auf der Handbuchseite <<automatisierung/ereignisaktionen#, Ereignisaktionen>>. Arbeiten Sie zum ersten Mal mit den Ereignisaktionen, finden Sie genauere Informationen zum Anlegen von Ereignisaktionen im Kapitel <<automatisierung/ereignisaktionen#100, Neue Ereignisaktion anlegen>>.
