= Umbuchungen vornehmen
:lang: de
include::{includedir}/_header.adoc[]
:description: Erfahre, wie du mit Lager-Umbuchungen in deinem plentymarkets System arbeitest.
:keywords: Umbuchung, Lagerumbuchung, Lagerort, Lagerorte, PO Lieferschein
:position: 50
:url: warenwirtschaft/umbuchungen-vornehmen

Im Menü *Waren » Bestellwesen » Bestellung* kannst du Waren zwischen verschiedenen Lagern umbuchen.

Die Umbuchung gliedert sich in folgende Arbeitsschritte:

* <<#600, Umbuchung anlegen>>
* <<#700, Auftragspositionen hinzufügen>>
* <<#800, Lieferschein erstellen>>
* <<#900, Waren ausbuchen>>
* <<#1000, Waren einbuchen>>
* <<#1100, Umbuchung abschließen>>

Wir empfehlen dir, vor der Abwicklung der Umbuchungen die folgenden vorbereitenden Einstellungen vorzunehmen.


[#100]
== Vorbereitende Einstellungen
Um deine Arbeit mit Lagerumbuchungen optimal zu organisieren, solltest du einige vorbereitende Einstellungen vornehmen. Diese Einstellungen werden im Folgenden beschrieben. Erstelle neue Status speziell für Umbuchungen und lege Tags an, um dir die Übersicht zu erleichtern. Die Einrichtung einer Dokumentenvorlage für den *PO Lieferschein* ist zudem zwingend erforderlich.

[#200]
=== Status für Umbuchungen anlegen
In deinem plentymarkets System sind bestimmte Auftragsstatus voreingestellt. Diese voreingestellten Status stehen dir auch für Umbuchungen zur Verfügung. Du kannst gesonderte Status für Umbuchungen anlegen, die du dann ausschließlich für diesen Auftragstyp nutzt. Das Anlegen neuer Status wird auf der Handbuchseite <<auftraege/auftraege-verwalten#1200, Aufträge verwalten>> beschrieben.

[TIP]
.Eigene Status für Umbuchungen anlegen
====
Wir empfehlen, separate Status anzulegen, die du ausschließlich für die Umbuchungen nutzt. So kannst du mittels unterschiedlicher Namensgebung die Status der Umbuchungen von den Status der weiteren Auftragstypen unterscheiden, beispielsweise bei der <<#1100, Automatisierung der Umbuchungen durch Ereignisaktionen>>.
====

[#300]
=== Tags für Umbuchungen anlegen
Tags sind Kennzeichnungen, die du zentral in deinem plentymarkets System anlegst und anschließend für verschiedene Bereiche nutzen kannst. Um Umbuchungen mit Tags zu versehen, musst du diese Tags zuvor im Menü *System » Systemeinstellungen » Einstellungen » Tags* anlegen. Folge dazu der Anleitung auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/tags#, Tags verwalten>>.

[#400]
=== Standardeinstellungen vornehmen
Um den Aufwand beim Anlegen einer neuen Umbuchung zu verringern, empfiehlt es sich, einige Standardeinstellungen vorzunehmen. Durch diese Einstellungen werden einzelne Felder mit Standardwerten vorausgefüllt, wenn du eine neue Umbuchung erstellst. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Standardeinstellungen vornehmen:

. Öffne das Menü *System » Systemeinstellungen » Waren » Bestellwesen » Umbuchung » Einstellungen*.
. Wähle einen *Standard-Status*, der beim Anlegen einer neuen Umbuchung vorausgewählt sein soll.
. Nimm die gewünschten Einstellungen zum *Standard-Eigner* vor. Beachte dazu die Informationen in <<tabelle-standard-eigner-umbuchung>>.
. *Speichere* die Einstellungen. +
→ Die gewählten Standardeinstellungen werden beim Anlegen neuer Umbuchungen vorausgewählt.

[[tabelle-standard-eigner-umbuchung]]
.Verfügbare Einstellungen zum Standard-Eigner
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Aktiver Benutzer vorausgewählt*
|Der Benutzer, der die Umbuchung erstellt, wird im Feld *Eigner* vorausgewählt.

|*Kein Eigner vorausgewählt*
|Das Feld *Eigner* bleibt beim Anlegen einer Umbuchung leer.

|====

[#500]
=== Vorlage für PO Lieferschein einrichten
Für die Umbuchung kannst du den speziell dafür vorgesehenen Dokumententyp *PO Lieferschein* nutzen. Die Benennung
*PO* (PO = Purchase order, dt. Bestellwesen). Dieser Lieferschein listet die in der Umbuchung vorhandenen Auftragspositionen auf. So ist der Inhalt der Umbuchung beim Aus- und Einbuchen in das Empfängerlager für Lagermitarbeiter und Logistikpartner nachvollziehbar.

[IMPORTANT]
.Dokumentenvorlage muss eingerichtet sein
====
Vor der erstmaligen Nutzung des Dokumententyps *PO Lieferschein* muss zwingend die Dokumentenvorlage eingestellt werden. Solange keine Vorlage eingerichtet wurde, wird der Lieferschein bei der Umbuchung nicht erstellt.
====

Im Folgenden wird beschrieben, wie du die einfache Standard-Vorlage übernimmst, die in deinem plentymarkets System hinterlegt ist.

[.instruction]
Dokumentenvorlage für PO Lieferschein einrichten:

. Öffne das Menü *System » Systemeinstellungen » Waren » Bestellwesen » Umbuchung » Dokumente » PO Lieferschein*.
. Öffne das Tab *Transfer*.
. Wähle über dem Tab-Titel die Sprache.
. Klicke im Bereich *Einstellungen aus Standard-Dokumentenvorlage* auf *Übernehmen*. +
→ Die Standardeinstellungen werden auf das Dokument angewendet.

Um das Dokument *PO Lieferschein* individuell zu gestalten, gehe analog zu den Anleitungen im Kapitel <<auftraege/auftragsdokumente#300, Dokumentenvorlage einrichten>> vor.

[#600]
== Umbuchung anlegen
Nachdem du die vorbereitenden Einstellungen vorgenommen hast, kannst du einen Auftrag vom Typ Umbuchung anlegen.

[.instruction]
Neue Umbuchung anlegen:

. Öffne das Menü *Waren » Bestellwesen » Bestellung*.
. Bewege die Maus über das *Plus-Icon* und klicke auf *Neue Umbuchung*. +
→ Das Menü zum Anlegen der Umbuchung öffnet sich.
. Wähle im Feld *Status* einen <<#200, Status>> aus, mit dem die Umbuchung angelegt werden soll. Dieser Status ist später noch änderbar.
. Gib im Feld *Sender* das Lager an, aus dem umgebucht werden soll.
. Gib im Feld *Empfänger* das Lager an, in das umgebucht werden soll.
. *_Optional:_* Wähle ein oder mehrere *Tags* für die neue Umbuchung aus.
. *_Optional:_* Gib im Feld *Eigner* einen Eigner, also den bearbeitenden Nutzer, ein.

// muss hier noch gespeichert werden?

[IMPORTANT]
.Eigner auswählen
====
Fehlt der gewünschte *Eigner* fehlt, liegt das daran, dass kein Benutzer deines plentymarkets Systems als Eigner aktiviert wurde. Eine Anleitung zum Aktivieren der Eigner findest du auf der Handbuchseite <<basics/admin-aufgaben/benutzer-verwalten#40, Benutzer verwalten>>. Prüfe außerdem die oben beschriebenen <<#400, Standardeinstellungen>> zum Eigner.
====

[#700]
=== Auftragspositionen hinzufügen
Im nächsten Schritt fügst du die Auftragspositionen hinzu, die von einem Lager in ein anderes Lager umgebucht werden sollen. Nutze dabei den *Filter*, um die gewünschten Auftragspositionen anhand der vorhandenen <<artikel/artikel-verwalten#_artikel_filtern, Artikel- und Variantendaten>> zu finden.

[.instruction]
Auftragspositionen hinzufügen:

. Klicke im Bereich *Auftragspositionen* auf *Hinzufügen*. +
→ Ein Menü zum Hinzufügen der Artikelpositionen öffnet sich.
. Wähle einen der in <<tabelle-filter-artikelsuche-umbuchung>> beschriebenen Filter zur Artikelsuche.
. Gib einen zum Filter passenden Suchbegriff im Feld *Artikel suchen* ein.
. Klicke auf *Suchen*. +
→ Die Artikelvarianten, die im Senderlager Bestand haben, werden angezeigt.
. Gib die umzubuchende Anzahl in der Spalte *Menge* der Variante ein.
. Klicke auf das *Warenkorb-Icon*. +
→ Die Varianten werden dem Warenkorb hinzugefügt.
. Wiederhole Schritte 1 bis 6, bis alle umzubuchenden Artikelvarianten in der gewünschten Menge im Warenkorb enthalten sind.
. Klicke im Bereich *Warenkorb* auf *Speichern*. +
→ Der Warenkorb wird gespeichert. +
→ Die Umbuchung wird geöffnet.

[[tabelle-filter-artikelsuche-umbuchung]]
.Verfügbare Filter in der Artikelsuche
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Artikel-ID*
|ID eingeben, um nach dem Artikel mit dieser ID zu suchen.

|*Varianten-ID*
|ID eingeben, um nach der Variante mit dieser ID zu suchen.

|*Variantennummer*
|Variantennummer eingeben, um nach der Variante mit dieser Nummer zu suchen.

|*Barcode*
|Barcode eingeben, um nach der Variante mit diesem Code zu suchen.

|*Artikelname*
|Artikelnamen eingeben, um nach dem Artikel mit diesem Namen zu suchen.

|*Lieferantennummer*
|Nummer des Lieferanten eingeben, um nach Artikeln mit dieser Lieferantennummer zu suchen.

|*Lager*
|Name des Lagers eingeben, um nach Artikeln zu suchen, die mit diesem Lager verknüpft sind.

|====


[IMPORTANT]
.Ergebnisse der Artikelsuche
====
Die Artikelsuche in diesem Menü zeigt ausschließlich Artikel und Varianten, die Bestand im Senderlager haben. Werden Varianten oder Artikel nicht aufgeführt, überprüfe den Bestand im Menü *Waren » Warenbestände* oder im Tab *Bestand* der Artikelvariante.
====

[#800]
=== PO Lieferschein erstellen
Nach dem Hinzufügen der Auftragspositionen werden die Warenbewegungen für die Ausbuchung bereits vorbereitet. Dies erkennst du an den roten Pfeilen in der Tabelle *Warenbewegungen*.
Überprüfe hier unbedingt die vorbereiteten Warenbewegungen sowie die Mengen der einzelnen Artikelvarianten. Anschließend erstellst du einen *PO Lieferschein*, der die auszubuchenden Auftragspositionen enthält.

[#830]
==== PO Lieferschein manuell erstellen
Gehe wie im Folgenden beschrieben vor, um das Dokument *PO Lieferschein* manuell erstellen.

[.instruction]
PO Lieferschein manuell erstellen:

. Öffne den Bereich *Dokumente*.
. Klicke auf *Lieferschein hinzufügen*.
. Wähle die Option *Lieferschein erzeugen*. +
→ Der *PO Lieferschein* wird erstellt.

[#870]
==== PO Lieferschein automatisch erstellen

Richte die folgende Ereignisaktion ein, um das Dokument *PO Lieferschein* automatisch zu erstellen, sobald du im nächsten Schritt die in der Umbuchung enthaltenen Artikel aus dem Senderlager <<#900, ausgebucht>> hast.

[.collapseBox]
.Erzeugen des Dokuments PO Lieferschein automatisieren:
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*.  +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-po-lieferschein-erzeugen>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-po-lieferschein-erzeugen>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
[[tabelle-ereignisaktion-po-lieferschein-erzeugen]]
.Ereignisaktion zum automatischen Erzeugen des Bestellscheins
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Bestellwesen > Bestellung ausgelöst*
|

|*Filter*
|*Auftragstyp > Bestellung, Typ Umbuchung*

|*Aktion*
|*Bestellwesen > PO Lieferschein erzeugen*
|
|====

Nach Erstellung ist der PO Lieferschein dauerhaft im Bereich *Dokumente* verfügbar und kann dort heruntergeladen oder gelöscht werden. Hat dein Lieferant dir einen externen Lieferschein übermittelt, ist es unter Umständen nicht nötig, deinen eigenen Lieferschein zu generieren. Den externen Lieferschein kannst du im Bereich *Dokumente* ebenfalls hochladen. Klicke dazu auf *Lieferschein hinzufügen* und wählen die Option *Lieferschein hochladen*.

[#900]
=== Waren ausbuchen
Nach dem Hinzufügen aller umzubuchenden Artikel buchst du die Artikelpositionen aus dem Senderlager aus.

[WARNING]
.Umbuchung kann nicht mehr bearbeitet werden
====
Sobald du den nachfolgend beschriebenen Schritt ausgeführt hast, kannst du die Umbuchung *nicht* mehr bearbeiten. Artikelpositionen können dann weder gelöscht noch hinzugefügt werden. Buche die Waren deshalb erst nach sorgfältiger Prüfung aus!
====

[.instruction]
Waren ausbuchen:

. Klicke im Bereich *Auftragsdetails* auf das *Zahnrad* neben dem Feld *Bestelldatum*. +
→ Die Umbuchung wird angelegt und der Warenausgang im Senderlager gebucht.

[#1000]
=== Waren einbuchen
Sobald die Artikel aus dem Senderlager im Empfängerlager eintreffen, buchst du die Auftragspositionen im Empfängerlager ein. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Waren einbuchen:

. Öffne den Bereich *Auftragspositionen*.
. Trage in der Spalte *Menge* die angelieferten Artikelpositionen ein.
. Klicke auf *Warenbewegungen anlegen*. +
→ Die Warenbewegung wird angelegt.
. Gehe zum Bereich *Warenbewegungen*. Dort erkennst du an der grünen Markierung die vorbereiteten Warenbewegungen.
. Gib in der Spalte *Lagerort* einen Lagerort an.
. Setze jeweils ein Häkchen in der Zeile mit der einzubuchenden Artikelvariante.
. Gib im Feld *Lieferschein-Nr.* die Nummer des PO Lieferscheins ein, der bei der Ausbuchung erstellt wurde.
. Klicke auf *Warenbewegungen buchen*. +
→ Der Wareneingang wird im Empfängerlager gebucht.

[#1100]
=== Umbuchung abschließen
Wurde für alle Artikelvarianten im Empfängerlager der Wareneingang gebucht, schließt du die Umbuchung in deinem plentymarkets System ab. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Umbuchung abschließen:

. Öffne die Umbuchung.
. Gehe zum Bereich *Auftragsdetails*.
. Klicke auf das *Zahnrad-Icon* neben dem Feld *Abschlussdatum*. +
→ Das aktuelle Datum wird automatisch als Abschlussdatum gesetzt. +
→ Die Umbuchung wird für die Bearbeitung gesperrt.

[TIP]
.Sperrung der Umbuchung aufheben
====
Hast du die Umbuchung versehentlich abgeschlossen, klicke erneut auf das Icon. So wird die Umbuchung entsperrt und kann erneut bearbeitet werden.
====

[#1200]
== Umbuchung suchen
Beim Öffnen des Menüs *Waren » Bestellwesen » Bestellung* werden dir alle Umbuchungen und <<warenwirtschaft/nachbestellungen-verwalten/nachbestellungen-vornehmen#, Nachbestellungen>> angezeigt. Das Ergebnis kannst du durch Verändern der Filter einschränken, um so entweder alle oder ein weiter eingeschränktes Ergebnis anzuzeigen.

[.instruction]
Umbuchung suchen:

. Öffne das Menü *Waren » Bestellwesen » Bestellung* +
. Wähle einen oder mehrere der in <<tabelle-umbuchung-suchen-filter>> beschriebenen Filter, um die Ergebnisse einzugrenzen.
. Klicke auf *Suchen*.

[[tabelle-umbuchung-suchen-filter]]
.Verfügbare Filter zum Suchen einer Umbuchung
[cols="1,3,3"]
|====
|Einstellung |Erläuterung

|*Auftrags-ID*
|Auftrags-ID der Umbuchung eingeben, um die Umbuchung zu suchen.

|*Auftrags-Typ*
|Auftrags-Typ *Umbuchung* auswählen, um nur Aufträge vom Typ *Umbuchung* anzuzeigen.

|*Artikel-ID*
|Artikel-ID eingeben, um Umbuchungen zu suchen, die einen Artikel mit dieser ID enthalten.

|*Varianten-ID*
|Varianten-ID eingeben, um Umbuchungen zu suchen, die eine Variante mit dieser ID enthalten.

|*Variantennummer*
|Variantennummer eingeben, um Umbuchungen zu suchen, die eine Variante mit dieser Nummer enthalten.

|*Artikeldaten*
|Suchbegriffe oder Zahlenwerte eintragen, um Umbuchungen zu suchen, die Artikel mit diesen Daten enthalten. Durchsucht werden *Artikel-ID*, *Artikelnummer* und *Name*. Zusätzlich den Filter *Auftrags-Typ* auf die Option *Umbuchung* setzen.

|*Status*
|Einen Status aus der Liste auswählen. Zusätzlich den Filter *Auftrags-Typ* auf die Option *Umbuchung* setzen, um Umbuchungen mit diesem Status zu suchen.

|*Eigner*
|Einen Eigner aus der Liste auswählen. Zusätzlich den Filter *Auftrags-Typ* auf die Option *Umbuchung* setzen, um Umbuchungen mit diesem Eigner zu suchen.

|*Auftragsdatum von ... bis*
|Start- und Enddatum aus dem Kalender wählen. Diese Angabe grenzt den Zeitraum auf das Bestelldatum der Umbuchung ein.

[#1300]
== Umbuchungen automatisieren
Mithilfe von Ereignisaktionen kannst du die einzelnen Arbeitsschritte einer Umbuchung automatisieren. Die Automatisierung der Erzeugung des *PO Lieferscheins* wurde bereits im Kapitel <<#870, PO Lieferschein automatisch erzeugen>> beschrieben. Im Menü *System » Systemeinstellungen » Aufträge » Ereignisse* stehen dir in den Ereignis-, Filter- und Aktionsgruppen *Bestellwesen* Möglichkeiten zur Automatisierung von Umbuchungen zur Verfügung. +

Genauere Informationen zu diesen Einstellungsmöglichkeiten findest du auf der Handbuchseite <<automatisierung/ereignisaktionen#, Ereignisaktionen>>. +
Falls du zum ersten Mal mit Ereignisaktionen arbeitest, findest du Informationen zum Anlegen von Ereignisaktionen im Kapitel <<automatisierung/ereignisaktionen#100, Neue Ereignisaktion anlegen>>.
