= Wareneingänge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Ware buchen, Ware freigeben, Bestand buchen, Wareneingang, Ware einbuchen, Bestand einbuchen, Ware erfassen
:position: 20

Es gibt verschiedene Wege, über die Sie Waren in Ihr System buchen können. Voraussetzung für einen Wareneingang ist, dass der Variante ein Lager sowie ein Lagerort und ein Lieferant zugeordnet sind. Auf dieser Seite wird beschrieben, wo und wie das Zuordnen des Lagerorts und des Lieferanten erfolgt. Außerdem wird der Wareneingang über das Menü **Waren » Neuer Wareneingang** beschrieben. Nur wenn Sie Wareneingänge und Warenausgänge buchen und so Warenbestände in plentymarkets führen, kann Ihr System **<<artikel/artikel-verwalten#230., Varianten anhand der Beschränkung und Verfügbarkeit automatisiert im Webshop ein- und ausblenden >>** sowie Listings automatisiert starten und beenden.

toc::[]
[#100]
== Lieferanten einer Variante zuordnen

Ein Lieferant muss einer Variante zugeordnet werden, damit der Wareneingang gebucht werden kann und damit später auch eine Nachbestellung an den Lieferanten erfolgen kann. Lieferanten sind Kunden des Kundentyps Lieferant. Bevor Sie also Ihren Lieferanten zuordnen können, müssen Sie Ihn erst einmal anlegen. Die Vorgehensweise ist die gleiche wie beim **<<crm/kundendaten-verwalten#800., Anlegen eines Kunden >>**. Allerdings muss der Kundentyp Lieferant gewählt werden.

[.instruction]
Lieferanten zuordnen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel.
. Öffnen Sie die Variante.
. Öffnen Sie das Tab **Lieferant**.
. Wählen Sie einen Lieferanten aus dem Dropdown-Menü.
. Klicken Sie auf **Hinzufügen**.  +
→ Der Lieferant wird der Variante zugeordnet und weitere Einstellungen können optional vorgenommen werden.

.Lieferanteninformationen für eine Variante
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Lieferanten-Artikel-Nr.**
|Artikelnummer eintragen, unter der Ihr Lieferant die Variante führt. Wareneingänge können auch anhand dieser Nummer gesucht werden.

|**EK**
|Einkaufspreis der Variante eintragen. Je nach Einstellung für Wareneingänge wird dieser EK überschrieben. Im Menü **Einstellungen » Waren » Warenbestand » Wareneingang** stellen Sie ein, ob der Einkaufspreis eines Wareneingangs für Lieferanten übernommen wird.

|**Mindestabnahme**
|Anzahl der Variante eintragen, die Sie mindestens bestellen müssen. Die Mindestabnahme wird für Nachbestellungen berücksichtigt. Allerdings wird sie nur angezeigt, wenn die Variante den Meldebestand erreicht hat und tatsächlich nachbestellt werden muss. Für Varianten, die noch ausreichend vorhanden sind, wird die Mindestabnahme nicht angezeigt.

|**Lieferzeit in Tagen**
|Anzahl der Tage eintragen, die der Lieferant für die Lieferung der Variante benötigt. Die Lieferzeit kann Einfluss auf den Mengenvorschlag einer Nachbestellung haben und auf das Lieferdatum einer Nachbestellung. Ob die Lieferzeit für den Bestellmengenvorschlag berücksichtigt wird, stellen Sie im Menü **Einstellungen » Waren » Bestellwesen » Grundeinstellungen** ein. Die Lieferzeit wird hier als Wiederbeschaffungszeit für die Bestellmenge berücksichtigt.

|**Letzte Preisanfrage**
|Datum aus dem Kalender wählen, an dem der Preis für die Variante zuletzt abgefragt wurde.

|**Rabatt**
|Rabatt in Prozent eintragen, wenn der Lieferant einen Rabatt auf die Variante gewährt. Der Rabatt wird in Nachbestellungen nur berücksichtigt, wenn auch das Häkchen bei Rabattfähigkeit gesetzt ist.

|**Rabattfähigkeit**
|Häkchen setzen, um den unter Rabatt eingetragenen Rabatt zu aktivieren. Wenn die Rabattfähikgeit nicht gesetzt ist, wird der eingetragene Rabatt für Nachbestellungen nicht berücksichtigt.

|**Verpackungseinheit**
|Verpackungseinheit (VPE) eintragen, insbesondere wenn die Verpackungseinheit des Lieferanten von der im Tab **Einstellungen** gespeicherten Verpackungseinheit abweicht.
|====

[#200]
== Variante mit Lagerort verknüpfen

Eine Variante muss mit einem Lager samt Lagerort verknüpft werden, damit ein Wareneingang gebucht werden kann. Ohne eine Lagerzuordnung weiß das System nicht, wohin der Wareneingang gebucht wird, und kann deshalb nicht buchen. Der Standard-Lagerort dient als Platzhalter-Lagerort und bedeutet, dass noch kein Lagerort zugeordnet wurde. Wählen Sie deshalb besser einen Ihrer Lagerorte als Lagerortvorschlag.

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen**
. Öffnen Sie das Tab **Lager**.
. Wählen Sie ein Lager aus dem Dropdown-Menü.
. Klicken Sie auf **Hinzufügen**.  +
→ Das Lager wird der Variante zugeordnet und weitere Einstellungen können optional vorgenommen werden.

.Lagereinstellungen einer Variante
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Lagerorttyp**
|Lagerorttyp anhand der Artikelgröße wählen.

|**Zone**
|Zone wählen, wenn das Lager in Zonen eingeteilt wurde.

|**Meldebestand**
|Anzahl der Variante eintragen, bei der eine Nachbestellung erfolgen soll. Erst wenn eine Variante später auf den Meldebestand sinkt, wird auch ein Mengenvorschlag für die Variante angezeigt, da ja erst bei Erreichen des Meldebestands eine Nachbestellung erfolgen soll.

|**Lagerreichweite**
|Anzahl der Tage eintragen, den der Warenbestand bis zur nächsten Nachbestellung reichen soll. Die Lagerreichweite fließt in die Berechnung des Nachbestellungsvorschlags ein. Ein Standardwert aus der Praxis für die Lagerreichweite ist z.B. 14 Tage. Wenn der Artikel den Meldebestand erreicht hat, werden die 14 Tage zur Berechnung der Nachbestellmenge berücksichtigt, d.h. es wird die Menge zur Nachbestellung vorgeschlagen, die für die folgenden 14 Tage ausreicht.
Wird hier kein Wert eingetragen, wird die Lagerreichweite bei der Berechnung eines Nachbestellungstermins nicht berücksichtigt.

|**Maximalbestand**
|Maximalen Bestand für das Lager eintragen. Der Maximalbestand wird für den Bestellmengenvorschlag berücksichtigt, sodass der Vorschlag den Maximalbestand nicht überschreitet.

|**Bestandspuffer**
|Ein Bestandspuffer bewirkt, dass der Bestand für bestimmte Marktplätze um den eingetragenen Wert reduziert wird.  +
__Beispiel__: Der Artikel hat einen Bestand von 50. Sie möchten einen Bestandspuffer von 10 Artikeln, damit der Artikel nicht vollständig über den Marktplatz abverkauft wird. Dazu **10** als Bestandspuffer eintragen. Zum Marktplatz wird ein Bestandswert von **40** übertragen.  +
Hier eingetragene Werte gelten für die Marktplätze <<multi-channel/neckermann-at#, **Neckermann**  >>, <<multi-channel/otto#, **Otto**  >> und <<multi-channel/plus-gartenxxl#, **Plus.de**  >>. Die Werte sind gegenüber den hinterlegten Bestandspufferwerten dieser Marktplätze dominant.

|**Lagerortvorschlag**
|Lagerort wählen, der bei Nachbestellungen automatisch vorgeschlagen werden soll. Die Einstellung Standard-Lagerort bedeutet, dass kein Lagerort zugewiesen wurde.
|====

[#300]
== Übernahme von Daten vorbereiten

Beim Hinzufügen der Artikel können Sie sowohl den Einkaufspreis als auch die UVP sowie den Lagerort angeben. Die UVP wird bei Freigabe eines Wareneingangs automatisch in die Variantendaten übernommen. Wenn ein Wareneingang die gleiche Variante mehrmals, jedoch mit unterschiedlichen UVPs enthält, wird bei der Freigabe die höchste UVP übernommen. Ob und wie Einkaufspreise von Wareneingängen zu den Artikeldaten übertragen werden und ob und wie ein Lagerort aus einem Wareneingang zu einem Artikel übertragen wird, legen Sie vorab fest.

[.instruction]
Übernahme festlegen:

. Öffnen Sie das Menü **Einstellungen » Waren » Warenbestand » Wareneingang**.
. Wählen Sie eine Einstellung. Beachten Sie dazu die Erläuterungen in Tabelle 3.
. **Speichern** Sie die Einstellungen.

.Preis- und Lagerortübertragung festlegen
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Einkaufspreis**
|Wählen ob und wohin der EK aus dem Wareneingang übertragen wird. Die Übertragung erfolgt bei Freigabe eines Wareneingangs.  +
**Einkaufspreis nicht übertragen** = Einkaufspreis wird nicht übertragen.  +
**Einkaufspreis auf Varianten übertragen** = Einkaufspreis wird automatisch im Tab **Einstellungen** einer Variante hinterlegt.  +
**Einkaufspreis auf Varianten und Lieferant übertragen** = Einkaufspreis wird automatisch im Tab **Einstellungen** einer Variante sowie im Tab **Bestand** in den Lieferantendaten hinterlegt.  +
**Durchschnittseinkaufspreis auf Varianten übertragen** = Bei jedem Wareneingang wird der durchschnittliche EK neu berechnet und angepasst. Dabei werden die Einkaufspreise aller im Lager verfügbaren Bestände einer Variante zur Berechnung herangezogen. Der errechnete Mittelwert wird im Tab **Einstellungen** einer Variante hinterlegt.  +
**Höchsten Einkaufspreis übertragen** = Bei mehreren unterschiedlichen Einkaufspreisen wird der höchste Einkaufspreis aus dem aktuellen Wareneingang in die Variantendaten übertragen.  +
**Niedrigsten Einkaufspreis übertragen** = Bei mehreren unterschiedlichen Einkaufspreisen wird der niedrigste Einkaufspreis aus dem aktuellen Wareneingang in die Variantendaten übertragen.

|**Lagerort**
| Wählen ob und wohin der Lagerort übertragen wird. Die Übertragung erfolgt bei Freigabe eines Wareneingangs.  +
**Lagerort nicht übertragen** = Lagerort wird nicht übertragen.  +
**Lagerort auf Variante übertragen** = Lagerort wird automatisch als Lagerort-Vorschlag in das **Tab: Lager** einer Variante übernommen. Der Lagerort wird mit jedem Wareneingang neu übertragen.  +
**Lagerort auf Variante übertragen, wenn noch keiner oder Standard-Lagerort hinterlegt wurde** = Übertragung erfolgt nur, wenn noch kein Lagerort hinterlegt wurde.
|====

[#400]
== UVP und Preis zuordnen

Damit Sie im Wareneingang eine UVP eintragen können, müssen Sie zuordnen, welcher Verkaufspreis als UVP genutzt werden soll. Außerdem können Sie wählen, welcher Verkaufspreis Ihnen im Wareneingang angezeigt wird.

[.instruction]
UVP und Preis zuordnen:

. Öffnen Sie das Menü **Einstellungen » Waren » Neuer Wareneingang**.
. Wählen Sie für **UVP** einen Ihrer Verkaufspreise aus dem Dropdown-Menü.
. Wählen Sie für **Preis** einen Ihrer Verkaufspreise aus dem Dropdown-Menü.
. Speichern Sie die Einstellungen.

Die Zuordnung im Menü **Einstellungen » Waren » Neuer Wareneingang** reicht nicht, um einen Verkaufspreis in einer Variante anzuzeigen. Sie müssen einen Verkaufspreis auch mit einer Variante verknüpfen. Verkaufspreise legen Sie im Menü **Einstellungen » Artikel » Verkaufspreise** an. Wie Sie Verkaufspreise anlegen und mit Varianten verknüpfen, finden Sie auf der Handbuchseite **<<artikel/artikel-verwalten#, Artikel verwalten  >>**. Auf dieser Seite erfahren Sie auch, wie Sie mit der Preiskalkulation Preise für Kundenklassen u.v.m. errechnen lassen.

[#500]
== Wareneingang erfassen

Das Erfassen eines Wareneingangs teilt sich in zwei Schritte. Zunächst geben Sie übergeordnete Daten wie den Lieferanten und die Währung an. Im zweiten Schritt geben Sie an, welche Artikel in welcher Menge geliefert wurden.

=== Kopfdaten eines Wareneingangs erfassen

Um einen Wareneingang zu erfassen, benötigen Sie mindestens ein Lager und einen Lieferanten.
Lieferanten legen Sie als **<<crm/kundendaten-verwalten#800., Kunden >>** an und ordnen ihnen den Kundentyp Lieferant zu.
Außerdem muss mindestens ein Benutzer als **<<arbeiten-mit-plentymarkets/benutzer-verwalten#40., Eigner für Wareneingänge >>** aktiviert sein, damit der Wareneingang einem Eigner zugeordnet werden kann.
Ohne Eigner kann kein Wareneingang erfasst werden.
Die Eigner stehen Ihnen nach ID sortiert zur Verfügung.
Wenn der eingeloggte Benutzer als Eigner möglich ist, wird er vorausgewählt.

[.instruction]
Kopfdaten eines Wareneingangs erfassen:

. Öffnen Sie das Menü **Waren » Neuer Wareneingang**.
. Klicken Sie auf **Neuer Wareneingang**.  +
→ Ein neues Tab wird geöffnet.
. Tragen Sie einen **Lieferanten** ein.  +
→  Mit der Pfeiltaste nach unten öffnen Sie eine Liste aller Lieferanten, alternativ werden ab Eingabe des dritten Buchstabens Vorschläge eingeblendet.
. Wählen Sie ein Lager.  +
→ Wenn ein Hauptlager für die Variante gespeichert ist, ist das **<<artikel/artikel-verwalten#290., Hauptlager >>** vorausgewählt.
. Wählen Sie einen Eigner.  +
→ Wenn Sie als **<<arbeiten-mit-plentymarkets/benutzer-verwalten#40., Eigner für Wareneingänge >>** aktiviert wurden, sind Sie als eingeloggter Benutzer als Eigner vorausgewählt.
. Nehmen Sie weitere optionale Einstellungen vor.
. Klicken Sie auf Speichern, um den Wareneingang anzulegen.  +
→ Der Wareneingang wird in einem Tab geöffnet, erhält eine ID und den Status **Erfasst**. Durch einen Klick auf das Plus am Anfang der Kopfzeile des Wareneingangs werden weitere Angaben sichtbar.

Wenn Sie den Wareneingang in einer anderen Währung als Ihrer **<<payment/waehrungen#30., Standardwährung >>** bezahlen, wird der **<<payment/waehrungen#20., Umrechnungskurs >>** voreingetragen.

Alle erfassten Angaben können geändert werden. Um den Wareneingang zu vervollständigen, fügen Sie Artikel und Warenbezugskosten hinzu.

[#600]
=== Artikel zum Wareneingang hinzufügen

Varianten eines Artikels lassen sich einzeln hinzufügen oder Sie können mehrere Varianten gleichzeitig hinzufügen. Sie können nur Varianten von Artikeln hinzufügen, die bereits angelegt sind. Wenn ein neuer Artikel geliefert wird, legen Sie zunächst den Artikel mit Varianten im Menü **<<artikel/artikel-verwalten#, Artikel  >>** an.
Zunächst werden Ihnen alle Artikel aller Lieferanten aufgelistet. Nutzen Sie die Suche, um Artikel einzelner Lieferanten anzuzeigen. +
Wenn Sie einen Einkaufspreis für eine Variante eingetragen haben, ist dieser hier voreingetragen und kann übernommen werden. Ein Klick auf die Artikel-ID öffnet den Artikel zur Bearbeitung. Wie Sie vorgehen, um die gelieferten Artikel dem Wareneingang hinzuzufügen, wird nachfolgend beschrieben.

[#700]
==== Varianten einzeln hinzufügen

Einzelne Varianten fügen Sie folgendermaßen hinzu. Angaben wie Einkaufspreis und Lagerort sind keine Pflichtangaben. Wenn Sie diese Angaben nicht pflegen möchten, überspringen Sie die Punkte in der Beschreibung.

[.instruction]
Varianten einzeln hinzufügen:

. Öffnen Sie das Menü **Waren » Neuer Wareneingang**.
. Öffnen Sie einen Wareneingang.
. Klicken Sie auf **Artikel hinzufügen**.  +
→ Ein Fenster zur Artikelsuche und -auswahl wird geöffnet.
. Tragen Sie Suchbegriffe ein und stellen Sie Filteroptionen ein. Beachten Sie dabei die Erläuterungen in Tabelle 4.
. Klicken Sie auf **Suchen**.  +
→ Die Artikel, die den eingegebenen Suchkriterien entsprechen, werden aufgelistet.
. Tragen Sie optional den **Einkaufspreis** ein.
. Tragen Sie die **Menge** ein (Pflichtangabe).  +
→ Die Variante wird nach dem Eintragen der Menge automatisch gewählt.
. Wählen Sie einen **Lagerort** aus dem Dropdown-Menü.  +
→ Wenn Sie einer Variante noch keinen Lagerort zugeordnet haben, können Sie hier auch einen Lagerort zuordnen. Klicken Sie dafür auf **Suchen**. Der Standard-Lagerort ist ein Platzhalter-Lagerort und bedeutet, dass kein Lagerort zugeordnet ist.
. Tragen Sie optional eine **UVP** ein.  +
→ Die UVP wird nach Freigabe des Wareneingangs in die Variantendaten übernommen.
. Klicken Sie in der Spalte **Aktionen** auf **Artikel hinzufügen**.  +
→ Die Variante wird dem Wareneingang hinzugefügt.

.Artikelfilter
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Artikeldaten**
|Durchsucht den Artikelnamen 1 und die Meta-Keywords eines Artikels.

|**Barcode**
|Filtert Barcodes wie EAN, UPC oder ISBN je nach Barcodetyp, den Sie angelegt haben.

|**Reset**
|Setzt alle Filtereinstellungen zurück, sodass Ihnen alle Artikel unabhängig vom Lieferanten angezeigt werden. Nach dem Zurücksetzen muss eine Suche ausgeführt werden, damit die Liste aktualisiert wird.
|====

Über **Zurück zum Wareneingang** gelangen Sie in die Übersicht des Wareneingangs.

[#800]
==== Mehrere Varianten gleichzeitig hinzufügen

Wenn Sie mehrere Varianten gleichzeitig hinzufügen möchten, tragen Sie Menge und Einkaufspreis ein, wobei der Einkaufspreis keine Pflichtangabe ist. Sie können außerdem mit der Tabulatortaste ins nächste Eingabefeld wechseln. Sie können nur Varianten der aktuellen Seite hinzufügen. Beim Wechsel auf eine neue Seite wird die Liste für diese Seite geladen und die Angaben auf vorhergehenden Seiten werden verworfen.

[.instruction]
Mehrere Varianten hinzufügen:

. Öffnen Sie das Menü **Waren » Neuer Wareneingang**.
. Öffnen Sie einen Wareneingang.
. Klicken Sie auf **Artikel hinzufügen**.  +
→ Ein Fenster zur Artikelsuche und -auswahl wird geöffnet.
. Tragen Sie Suchbegriffe ein und stellen Sie Filteroptionen ein. Beachten Sie dabei die Erläuterungen in Tabelle 4.
. Klicken Sie auf **Suchen**.  +
→ Die Varianten, die den eingegebenen Suchkriterien entsprechen, werden aufgelistet.
. Tragen Sie optional den **Einkaufspreis** ein.
. Tragen Sie die **Menge** ein (Pflichtangabe).  +
→ Die Variante wird nach dem Eintragen der Menge automatisch gewählt.
. Tragen Sie optional eine **UVP** ein. +
→ Die UVP wird nach Freigabe des Wareneingangs in die Artikeldaten übernommen.
. Tragen Sie die **Menge**, den **Einkaufspreis** und die **UVP** für weitere Varianten ein.
. Klicken Sie auf den Button **Hinzufügen**, der oberhalb der Artikelliste angezeigt wird.  +
→ Die Varianten werden dem Wareneingang hinzugefügt.

Über **Zurück zum Wareneingang** gelangen Sie in die Übersicht des Wareneingangs.

Wenn Sie erneut eine Menge der gleichen Variante hinzufügen und der Einkaufspreis sowie der Lagerort gleich sind, wird diese zur bereits vorhandenen Menge addiert. Wenn sich Einkaufspreis oder Lagerort unterscheiden, wird die Variante noch einmal aufgeführt.

[#900]
== Warenbezugskosten hinzufügen

Kosten, die beim Bezug der Ware anfallen, hinterlegen Sie als Warenbezugskosten.

[.instruction]
Warenbezugskosten hinzufügen:

. Öffnen Sie das Menü **Waren » Neuer Wareneingang**.
. Öffnen Sie den gewünschten Wareneingang.
. Klicken Sie auf das kleine Plus, um die Kopfzeile aufzuklappen.
. Klicken Sie auf die Münzen.  +
→ Ein Fenster wird geöffnet.
. Tragen Sie Ihre Kosten ein.
. Klicken Sie auf **Speichern**, um die Kosten zu sichern.

[#1000]
== Status ändern und nachvollziehen

Direkt nach dem Anlegen erhält der Wareneingang den Status **Erfasst**. Alle Änderungen des Status werden in der **Statushistorie** gespeichert. Die **Statushistorie** öffnen Sie über das Symbol rechts neben dem Status-Dropdown-Menü. In der Historie sehen Sie, von wem, wann und über welches Medium, z.B. Client, ein Status geändert wurde.

[.instruction]
Status ändern:

. Öffnen Sie das Menü **Waren » Neuer Wareneingang**.
. Öffnen Sie einen Wareneingang aus der Liste.
. Wählen Sie einen Status aus dem Dropdown-Menü.  +
→ Die Status **In Prüfung**, **Fehler**, **Storniert** und **Freigegeben** stehen zur Wahl.
. **Speichern** Sie den Status.

.Einstellbare Status
[cols="a,a"]
|====
|**Status** |Erläuterung

|**Erfasst**
|Erhält jeder Wareneingang automatisch nach dem Anlegen.

|**In Prüfung**
|Wenn alle Artikel, die geliefert wurden, erfasst sind und noch einmal ein Abgleich mit dem Lieferschein oder einer Bestellung erfolgt, ist dieser Status sinnvoll.

|**Fehler**
|Wenn ein Wareneingang einen Fehler enthält.

|**Storniert**
|Für Wareneingänge, die nicht mehr genutzt werden sollen. Wareneingänge können nicht gelöscht werden, daher bietet sich dieser Status für fehlerhafte Wareneingänge an.

|**Freigegeben**
|Die Ware wird dem Bestand hinzugefügt, d.h. sie wird für ausstehende Aufträge, neue Listings etc. berücksichtigt. Daher wird der Wareneingang für eine weitere Bearbeitung gesperrt.

|**Korrektur**
|Erlaubt einige Angaben wie den Lieferanten, die Lieferscheinnummer etc. wieder zu bearbeiten. Der Einkaufspreis kann nicht mehr bearbeitet werden.
|====

[#1100]
== Bestand auf Variante buchen

Durch die Freigabe des Wareneingangs wird die Menge im Wareneingang dem Bestand einer Variante hinzugefügt und die UVP aus dem Wareneingang wird für die Variante übernommen. Bei unterschiedlichen UVPs für eine Variante wird die höchste UVP in die Variante übernommen. +
Sobald ein Wareneingang den Status **Freigegeben** erhält, können Varianten weder geändert noch weitere Varianten hinzugefügt werden. Auch andere Daten, wie z.B. der Lieferant, sind im Status **Freigegeben** nicht mehr änderbar.

Den Bestand einer Variante sehen Sie im Tab **Bestand** und hier im Untertab **Warenbestand**. Im Untertab **Warenbewegung** werden zusätzlich alle Warenbewegungen angezeigt, d.h. hier sehen Sie auch, wenn z.B. der Einkaufspreis im Wareneingang geändert wurde. Alle Änderungen der Artikelmenge oder des Einkaufspreises in einem Wareneingang werden unabhängig vom Status des Wareneingangs als Warenbewegungen festgehalten.

Den Bestand aller Artikel und Varianten sehen Sie im Menü **<<warenwirtschaft/warenbestaende-verwalten#, Waren » Warenbestände  >>**.

[#1200]
== Notiz hinzufügen

Notizen nutzen Sie, um z.B. Informationen für Kollegen für die Nachbearbeitung zu speichern. Notizen lassen sich nicht ändern oder löschen.

[.instruction]
Notiz hinzufügen:

. Öffnen Sie das Menü **Waren » Neuer Wareneingang**.
. Öffnen Sie einen Wareneingang aus der Liste.
. Klicken Sie auf **Notizen**, den kleinen Zettel, in der ersten Zeile rechts.  +
→ Ein Fenster wird geöffnet.
. Tragen Sie einen Text ein. +
→ Sie haben verschiedene Formatierungsmöglichkeiten.
. Klicken Sie auf **Speichern**, um die Notiz zu sichern.  +
→ Gespeicherte Notizen werden im Notizenfenster links angezeigt.

[#1300]
== Wareneingang ändern und korrigieren

Ob Sie einen Wareneingang noch ändern können oder nicht, hängt vom Status des Wareneingangs ab. In den Status **Erfasst**, **In Prüfung**, **Fehler** und **Storniert** sind Wareneingänge noch änderbar. Angaben wie z.B. Lieferant, Lieferscheinnummer und Artikelmenge lassen sich ändern. Bei Änderungen von sensiblen Daten wie Einkaufspreis und Artikelmenge wird automatisch eine Notiz angelegt. Als Autor der Notiz wird der Bearbeiter gespeichert. Freigegebene Wareneingänge können nicht mehr geändert werden. Im Status **Korrektur** sind die Menge und übergeordnete Angaben wie das Lager etc. wieder änderbar.

[#1400]
== Wareneingang exportieren

Der Export erfolgt im CSV-Format. Gehen Sie wie nachfolgend beschrieben vor, um einen Wareneingang zu exportieren.

[.instruction]
Wareneingang exportieren:

. Öffnen Sie das Menü **Waren » Neuer Wareneingang**.
. Wählen Sie einen Wareneingang.
. Klicken Sie auf das kleine Plus, um den Kopfbereich des Wareneingangs zu öffnen.
. Klicken Sie auf **Export**. +
→ Die Datei wird heruntergeladen.
. Wählen Sie beim Öffnen der Datei das Semikolon als Trennzeichen.

[#1500]
== PDF-Beleg erstellen

Das Erstellen eines PDF-Belegs ist nur im Status **Freigegeben** möglich.

[.instruction]
PDF-Beleg erstellen:

. Öffnen Sie das Menü **Waren » Neuer Wareneingang**.
. Wählen Sie einen Wareneingang.
. Klicken Sie auf das kleine Plus, um den Kopfbereich des Wareneingangs zu öffnen.
. Klicken Sie auf **Beleg erstellen**. +
→ Die PDF-Datei wird heruntergeladen.

[#1600]
== Wareneingang suchen

Für die Suche nach Wareneingängen gibt es zwei Menüs, **Waren » Wareneingänge** und **Waren » Neuer Wareneingang**. Im Menü **Waren » Wareneingänge** werden alle Wareneingänge aufgelistet, egal ob sie per SOAP, per dynamischem Import oder über das Menü **Neuer Wareneingang** erfolgt sind. Im Menü **Neuer Wareneingang** werden nur Wareneingänge aufgeführt, die über dieses Menü erfolgt sind.

[#1700]
=== Neuen Wareneingang suchen

Mit der Wareneingangssuche listen Sie gezielt Wareneingänge auf. Viele der Filter für die Suche beziehen sich auf Artikel und Varianten eines Artikels, d.h. mit ihnen suchen Sie Wareneingänge, in denen Artikel oder Varianten mit dieser ID, Nummer oder Markierung vorkommen. Beim Öffnen des Menüs sind standardmäßig die letzten zwei Monate als Lieferzeitraum eingestellt. Wenn Sie einen Wareneingang suchen, der weiter zurückliegt, wird er erst aufgelistet, wenn Sie die Filter zurücksetzen.

[.instruction]
Neuen Wareneingang suchen:

. Öffnen Sie das Menü **Waren » Neuer Wareneingang**.
. Wählen Sie die gewünschten Sucheinstellungen. Beachten Sie dabei auch die Erläuterungen in Tabelle 6.
. Klicken Sie auf **Suchen**.

.Sucheinstellungen für Wareneingänge
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Barcode**
|Sucht Varianten mit dem eingetragenen Barcode. Barcodes können EANs, UPC, ISBN etc. sein.

|**Nachbestellungs-ID**
|Sucht alle Wareneingänge, in denen ein Artikel aus der Nachbestellung enthalten ist.
|====

[#1800]
=== Wareneingang im Menü **Waren » Wareneingänge** suchen

Waren gehen auf verschiedenen Wegen ins System ein. Sie können Waren z.B. per SOAP, per Rest, per dynamischen Import, in den Artikeldaten oder über das Menü **Neuer Wareneingang** einbuchen. Egal auf welchem Weg die Ware in Ihr System eingebucht wurde, im Menü **Waren » Wareneingänge** finden Sie alle Wareneingänge. Die Suche erfolgt immer monatsweise.

[.instruction]
Wareneingang suchen:

. Öffnen Sie das Menü **Waren » Wareneingänge**.
. Wählen Sie Filter aus. +
→ Der aktuelle Monat ist voreingestellt.
. Klicken Sie auf **Suchen**.

[IMPORTANT]
.Archivierte Einträge erkennen
====
Archiviert wird ein Eintrag frühestens nach drei Monaten und dann nur, wenn bereits alle eingegangenen Waren wieder ausgebucht oder umgebucht wurden. Wenn ein Wareneingang arichiviert wurde, wird ein Archivsymbol in der Spalte **Archiv** angezeigt.
Archivdaten sind nicht mehr änderbar und auch nicht löschbar.
====

Folgende Möglichkeiten stehen Ihnen in diesem Menü außerdem zur Verfügung:

* Wareneingänge monatsweise exportieren
* Wareneingänge öffnen, bearbeiten und einzeln exportieren

Im Tab **Base** sind die Optionen **Lieferant**, **Lieferdatum** und **Lieferscheinnummer** änderbar. Im Tab **Artikel** ist der **Einkaufspreis** änderbar.

