= FAQ

:lang: en
:keywords: eBay, Questions, FAQ, Help, Markets
:position: 10

This best practice gives you useful tips to solve several issues.

== Why are no orders imported into my system?

Checking the log can be useful here. In terms of orders, a look at the process *AuctionControllerOrders* can be helpful.

A. Has your eBay token expired?
You can check if your eBay token has expired within the *System » Markets » eBay » Accounts* menu.

B. Has the order been stored in the data exchange?
This happens if a customer has not completed the checkout and has the shipping costs calculated by eBay.
You can view those orders within *System » Markets » eBay » Data exchange*.

== Invalid selection of a variation within a market listing

[TIP]
.Has the variation been released for export?
====
Please check at first whether the variations have been released for export. +
For more information, see the corresponding best practice.
====

If the variations’ export settings are correct, the cause may be changes to the content of the variation. +
Whenever you change the content of a variation after having created the listing, these changes also have to be applied to the listing.

. Open the corresponding listing’s LID.
. Adjust the content within the listing’s settings and save the settings.

== Why is a listing not ended / restarted automatically?

A. Has the option *End/hide offers automatically* been activated?
This option is activated within *System » Listings » Stock*.

B. Has the *automatic stock update* been activated?
The automatic stock update is activated within *System » Markets » eBay » Settings » Initial settings*.
The stock dependence has to be set to *limited (without reservation)*.

C. Has the option *Use out of stock control* been activated?
The Use out of stock control option is activated within *System » Markets » eBay » Settings » Account settings*.

== Which price will be prioritised if there are several sales prices?

[TIP]
.Several sales prices
====
You can create as many prices as desired within *System » Item » Sales prices*. +
Thus, you can create an individual price for each eBay account and each eBay platform if the prices differ.
====

If there is more than one sales price with similar settings, the prices will be prioritised according to fixed criteria. +
For more information on the priorities, refer to the following list.

* Sales prices which are only set for one *market* are prioritised over sales prices which have been released for several or all markets. +
* Sales prices which are only set for one *country* are prioritised over sales prices which have been released for several or all countries. +
* Sales prices which are only set for one *eBay account* are prioritised over sales prices which have been released for several or all eBay accounts. +
* Sales prices which are only set for one *currency* are prioritised over sales prices which have been released for several or all currencies. +
* Sales prices which have a higher *minimum quantity* are prioritised over sales prices which have a minimum quantity of *1*. +
* Sales prices which are only set for one *customer class* are prioritised over sales prices which have been released for several or all customer classes. +

[NOTE]
.Important:
====
Only sales prices which fulfil the respective search criteria will be checked.
For eBay, the referrer and the eBay accounts are taken into account.
====

== Why is an order flagged as eBay plus on eBay but not in my plentymarkets system?

Please note that the flag for eBay Plus will only be transferred to us once the customer has completed the checkout on eBay.

In a case where the shipping costs are calculated by eBay, orders with an uncompleted checkout will be stored in the data exchange within *System » Markets » eBay » Data exchange*. +
The option *Automatically combine open eBay orders* is activated within *System » Listings » Checkout*. +
If a duration of e.g. one hour is set there, orders will be imported into the plentymarkets system after one hour, no matter whether checkout has been completed or not. +

There will *not* be a query for an eBay Plus flag afterwards.

== Which information can be changed for active listings and when?

For information about which changes you can apply to an active eBay listing and when you can change an active listing, refer to this link:http://pages.ebay.de/help/sell/listing-variations.html[*eBay page*^]. +

[NOTE]
.Important:
====
If you have already sold your offer, the changes you can apply to the listing are restricted. For further information, see the link above.
====


== What do various error messages mean?

Many errors which occur when setting up listings are from eBay and the same message is shown in your plentymarkets system.
For an overview of error messages, refer to the following list of link:http://developer.ebay.com/devzone/xml/docs/reference/ebay/errors/errormessages.htm[*eBay error messages*^].

=== Variation specifics cannot be changed. Variation specifics cannot be changed in restricted revise.

Refer to *Which information can be changed for active listings and when?* +
If this error message occurs, the variations in your plentymarkets system and the variations on eBay do not match anymore. +
Therefore, the variations, including the attribute name and the values, have to be changed so that they match the status of the listing.

*Solution:* +
Compare the eBay attributes and attribute names to the attributes and attribute names in your plentymarkets system. Also consider the attribute link within *System » Item » Attributes* if an attribute link is used for the respective category. +

=== Variation Specifics Mismatch. Variation Specifics provided does not match with the variation specifics of the variations on the item.

This error message is either issued by the CronJob during the automatic relisting process or if you select the option *End and restart*. +

If one of these options applies, it is possible to retain the ranking of the old listing and to transfer it to the new listing. +
Nevertheless, eBay expects that the variations which have already been sold are not changed on the listing. +
If this happens, the aforementioned error message will be issued and restarting will fail. +

*Solution*: +
A.
Recover the variations as in the old listing.
This means that if you have removed variations, you have to add them again. If you have changed the variation’s names, you have to undo the change or create an attribute link for the corresponding attribute within *System » Item » Attributes*.

B.
End the listing via the option *End and delete* and restart it via the group function.
However, the ranking of your listing will be lost during this process.

== How does eBay Picture Services work and how is it used?

With eBay Picture Services, listing images are uploaded to eBay and added to the listing by the eBay servers. Without eBay Picture Services, the image is added to the listing by the plenty servers.

If and how you should use eBay Picture Services is described below:

=== Listing a single item
*One image:* +
The setting within *System » Markets » eBay » Settings » Initial settings* is applied.

*Activated*: The image will be uploaded to eBay.

*Deactivated*: The listing’s image is provided by our servers.

*More than one image:* +
Ebay Picture Services will be used automatically. The initial settings will be ignored in this case.

=== Listing a variation
*One image:* +
The setting within *System » Markets » eBay » Settings » Initial settings* is applied.

*Active*: The image will be uploaded to eBay.

*Deactivated*: The listing’s image is provided by our servers.
In this case, you can link every variation to a different image. +
For example, if you have 10 variations, you can upload 11 different images without using eBay Picture Services because you have 1 gallery image and 10 variation images.

*More than one image:* +
Ebay Picture Services will be used automatically. The initial settings will be ignored in this case.

== Why is the telephone number not transferred during the order import?

In the field for the telephone number, eBay transfers “Invalid Request” to plentymarkets by default.

*Solution:* +
Log into eBay. Go to *Account Settings » Site Preferences » Shipping preferences* and activate the option *Require phone number for shipping*.


== Cross border trade agreement

The cross border trade agreement must be accepted once an item is to be listed on an international platform.
You can accept the agreement link:https://scgi.ebay.de/ws/ebayISAPI.dll?UserAgreementV2&isemail=1&agrid=7&aid=1&UserAgreement=&guest=1[on eBay^].
