= Installing plentyBase
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plentyBase, processes, process, printer, printers, printing, installing printer, install printer, run processes, execute processes, automation, print history, base
:description: Installing plentyBase
:position: 3
:url: automation/processes/installing-plentybase
:id: ZDXC8YS

plentyBase is a tool that allows your own computer to communicate with plentymarkets.

You need to install and run plentyBase to perform the following tasks in plentymarkets:

* Processes
** Create processes in plentymarkets
** Run processes in plentymarkets
* Printers
** Print documents from your plentymarkets system
** Access the print history from your plentymarkets system
** Print receipts for plentymarkets POS
* Save
** Save documents (originating in plentymarkets) on your computer's hard drive

If plentyBase is installed on the computer, these tasks can be performed in the plentymarkets back end.

Get to know plentyBase in our playful tutorial:

.plentyBase
video::232836578[vimeo]

You can download the installation files in the link:https://marketplace.plentymarkets.com/en/plugins/integration/plentyBase_5053[plentyMarketplace].
