= Sub-procedures
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Sub-procedures, processes, client
:description: Overview of the sub-procedures that can be configured in plentymarkets.
:position: 50
:url: automation/processes/sub-procedures

This page of the manual contains information about the sub-procedures you can add to the procedures of processes in the **Setup » Processes** menu.

The sub-procedures are listed in alphabetical order. The information is presented based on the following pattern:

* Short explanation of the sub-procedure
* The procedures for which the sub-procedure is available
* Any settings that are specific to this sub-procedure and available in addition to the <<automation/processes/sub-procedures#100, general settings>>.

The information presented on this page serves as reference for users familiar with the basic concept of plentymarkets procedures. For basic information on processes, refer to the <<automation/processes/setting-up-processes#, Setting up processes>> page of the manual.

[IMPORTANT]
.Tool plentyBase required
====
To create and run processes, you need plentyBase. You can download the installation files in the link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentyMarketplace^].
====

[#110]
== General settings

Some settings are available for all sub-procedures. The following table explains these settings.

.General settings for sub-procedures
[cols="1,2"]
|====
|Setting |Explanation

|**Position**
|The sub-procedure's current position in the procedure. The sub-procedure with the lowest position number is run first. Select a different position from the drop-down list to change the order in which the sub-procedures are run in the procedure.
|====

[#120]
== Scan item

Use the **Scan item** sub-procedure to open an entry mask for scanning items with a barcode scanner.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#160, Item search>>

[.subhead]
Settings

No additional settings are required for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

[#130]
== Add order notes

Use the **Add order notes** sub-procedure to add a note to an order.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#170, Order>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Add order notes** sub-procedure
[[table-subprocedure-settings-general]]
[cols="1,2"]
|====
|Setting |Explanation

|Note
|Select the type of note to be added to the order. +
**Individual note** = Allows the user to enter a message during the process. This message is saved as a note for the order. +
**Predefined note** = Opens a window. Enter a message into the **Message** area. This message will be saved automatically for errors during the process. +
**No note** = (Procedure "In case of error" only) Notes are never saved in the order. This option is recommended if you want to save the error message only as the order note.

|Save error message as additional note
|(Procedure "In case of error" only) Place a check mark to save the error message displayed in the process as an order note.
|====

[#140]
== Remove from procedure

Use the **Remove from process** sub-procedure to remove orders from the process. The sub-procedure also removes the order from filters and previously started box picking.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#170, Order>>

[.subhead]
Settings

No additional settings are required for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

[#150]
== Scan reorder

The **Scan reorder** sub-procedure opens a window that allows you to book in items using a barcode scanner.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#200, Reorder search>>

[.subhead]
Settings

No additional settings are required for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

[#160]
== Carry out booking

Use the **Carry out booking** sub-procedure to book incoming items or outgoing items automatically.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#440, Outgoing items>>
* <<automation/processes/procedures#450, Incoming items (reorder)>>

[.subhead]
Settings

No additional settings are required for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

[#170]
== Reset booking

Use the **Reset booking** sub-procedure to reset outgoing items that were booked for selected orders.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#440, Outgoing items>>

[.subhead]
Settings

No additional settings are required for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

[#180]
== Print

Select the desired printer when adding this sub-procedure. This will allow you to print documents, e.g. delivery notes or invoices.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#110, Pick-up/delivery note>>
* <<automation/processes/procedures#120, Address label>>
* <<automation/processes/procedures#130, Offer>>
* <<automation/processes/procedures#150, Item label>>
* <<automation/processes/procedures#180, Order confirmation>>
* <<automation/processes/procedures#210, Documents>>
* <<automation/processes/procedures#240, Entry certificate (Gelangensbestätigung)>>
* <<automation/processes/procedures#250, Credit note>>
* <<automation/processes/procedures#270, Adjustment form>>
* <<automation/processes/procedures#280, Warehouse pick list>>
* <<automation/processes/procedures#290, Delivery note>>
* <<automation/processes/procedures#300, Dunning letter>>
* <<automation/processes/procedures#310, packing list>>
* <<automation/processes/procedures#320, pick list>>
* <<automation/processes/procedures#350, Invoice>>
* <<automation/processes/procedures#360, Repair slip>>
* <<automation/processes/procedures#380, Return label>>
* <<automation/processes/procedures#390, Return slip>>
* <<automation/processes/procedures#430, Shipping center>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Print** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|Printer setting
|Select one of the <<basics/admin-tasks/printer#, printer profiles>> saved in the **Setup » Settings » Printers** menu.

|Copies
|Enter the number of copies per print.

|As multi-document
|Place a check mark to merge all documents into a single document. This single document will be printed.
|====

[#190]
== Change owner

Use the **Change owner** sub-procedure to change the owner. You can select from the owners saved in your system.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#170, Order>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Change owner** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|Owner
|Select the owner to be assigned with the sub-procedure from the drop-down list. You can select an owner from all those saved in your system.
|====

[#195]
=== Remove order from box

The sub-procedure **Remove order from box** is used for <<automation/processes/mobile-box-picking, mobile box picking>>. This sub-procedure unlinks the order from the box. This frees up the box again so that the warehouse technician can re-use it on his next trip through the warehouse.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#170, Order>>

[.subhead]
Settings

No additional settings are required for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

[#200]
== Show note

The **Note** sub-procedure shows a note that you have saved in advance. You can choose how much time should elapse before the note is hidden.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#260, Note>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Note** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|**Title**
|Enter a title for the note to be displayed.

|**Close automatically**
|Specify whether the note should be closed automatically after it was shown. +
**Never** = The user has to click on the note to close it. +
**After 1–5 seconds** = The note is closed automatically after the selected time has elapsed.

|**Message**
|Enter the text that is to be shown as the note.
|====

[#210]
== Change flag

Use the **Change flag** sub-procedure to change the flag. You can select from the flags saved in your system.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#170, Order>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Change flag** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|Flag
|Select the flag to be assigned with the sub-procedure from the drop-down list.
|====

[#230]
== Order notes

By combining the **Order notes** sub-procedure with the <<automation/processes/procedures#260, Note>> procedure, you can display the information saved in the <<Orders » Edit orders » Tab: Overview>> menu during the process so you employees can take appropriate action. +
The customer can write notes during the order process. Example:

* Please do not send your promotional product. I have no use for it!

Or you can enter the notes yourself. Example:

* The customer does not want the promotional product. Do not include in the package!

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#260, Note>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Order notes** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|Visibility
|Select the notes to be displayed. +
**ALL** = All notes are shown during the process. +
**Customer notes only** = Only notes entered by customers are shown during the process. +
**Employee notes only** = Only notes entered by an employee are shown during the process.
|====

[#240]
== Customer notes

By combining the **Customer notes** sub-procedure with the <<automation/processes/procedures#260, Note>> procedure, you can display the information saved in the **CRM » Contacts » Open contact » Area: Notes** menu during the process so you employees can take appropriate action. +
Example:

* The customer does not want to receive any advertisement.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#260, Note>>

[.subhead]
Settings

No additional settings are required for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

[#245]
== Save online

Use the **Save online** sub-procedure to save an online pick list that you can retrieve and process it in the plentymarkets App.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#320, pick list>>

[.subhead]
Settings

No additional settings are required for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

[#250]
== Scan package number

Use the **Scan package number** sub-procedure to register a package number.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#170, Order>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Scan package number** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|Package number format
|Select the package number format from the drop-down list.
|====

[#260]
== Register serial numbers

Use the **Register serial numbers** sub-procedure to register <<item/managing-items#820, serial numbers>> using a barcode scanner during the process. Decide whether to permit new serial numbers and whether serial numbers should be saved automatically.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#420, Serial numbers>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Register serial numbers** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|New serial numbers
|**Allow** = Serial numbers that were not registered along with the incoming items can be scanned with the outgoing items. +
**Do not permit** = Serial numbers have to be scanned with incoming items and again with outgoing items.

|Automatic save
|**Yes** = The process will be saved once serial numbers have been registered for all of the stock units. The process will continue automatically. +
**No:** Users have to click on **Save** once serial numbers have been registered for all of the stock units. The process will not continue until this is done.
|====

[#270]
== Sounds

Use the **Sounds** sub-procedure if you want an acoustic signal to be played as confirmation that the procedure was carried out.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#110, Pick-up/delivery note>>
* <<automation/processes/procedures#120, Address label>>
* <<automation/processes/procedures#130, Offer>>
* <<automation/processes/procedures#150, Item label>>
* <<automation/processes/procedures#160, Item search>>
* <<automation/processes/procedures#170, Order>>
* <<automation/processes/procedures#180, Order confirmation>>
* <<automation/processes/procedures#210, Documents>>
* <<automation/processes/procedures#220, Email>>
* <<automation/processes/procedures#240, Entry certificate (Gelangensbestätigung)>>
* <<automation/processes/procedures#250, Credit note>>
* <<automation/processes/procedures#260, Note>>
* <<automation/processes/procedures#270, Adjustment form>>
* <<automation/processes/procedures#280, Warehouse pick list>>
* <<automation/processes/procedures#290, Delivery note>>
* <<automation/processes/procedures#300, Dunning letter>>
* <<automation/processes/procedures#310, packing list>>
* <<automation/processes/procedures#320, pick list>>
* <<automation/processes/procedures#340, Polling>>
* <<automation/processes/procedures#350, Invoice>>
* <<automation/processes/procedures#360, Repair slip>>
* <<automation/processes/procedures#380, Return label>>
* <<automation/processes/procedures#390, Return slip>>
* <<automation/processes/procedures#400, SEPA Pain001>>
* <<automation/processes/procedures#410, SEPA Pain008>>
* <<automation/processes/procedures#430, Shipping center>>
* <<automation/processes/procedures#440, Outgoing items>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Sounds** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|Sounds
|Select the acoustic signal to be generated when a procedure has been carried out.
|====

[#280]
== Save

The documents will be saved in the folder that you selected when creating the sub-procedure. If the process is to be carried out by more than one user, specify a folder that can be accessed by all users.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#110, Pick-up/delivery note>>
* <<automation/processes/procedures#120, Address label>>
* <<automation/processes/procedures#130, Offer>>
* <<automation/processes/procedures#150, Item label>>
* <<automation/processes/procedures#180, Order confirmation>>
* <<automation/processes/procedures#210, Documents>>
* <<automation/processes/procedures#220, Email>>
* <<automation/processes/procedures#230, Finance export>>
* <<automation/processes/procedures#240, Entry certificate (Gelangensbestätigung)>>
* <<automation/processes/procedures#250, *Credit note>>
* <<automation/processes/procedures#270, Adjustment form>>
* <<automation/processes/procedures#280, Warehouse pick list>>
* <<automation/processes/procedures#290, Delivery note>>
* <<automation/processes/procedures#300, Dunning letter>>
* <<automation/processes/procedures#310, packing list>>
* <<automation/processes/procedures#320, pick list>>
* <<automation/processes/procedures#340, Polling>>
* <<automation/processes/procedures#350, Invoice>>
* <<automation/processes/procedures#360, Repair slip>>
* <<automation/processes/procedures#380, Return label>>
* <<automation/processes/procedures#390, Return slip>>
* <<automation/processes/procedures#400, SEPA Pain001>>
* <<automation/processes/procedures#410, SEPA Pain008>>
* <<automation/processes/procedures#430, Shipping center>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Save** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|Target folder
|Click on the pencil icon and select the path for saving the documents.

|File name
|Select the name with which the documents are to be saved. +
**Standard** = Files are assigned the default name. +
**User-defined** = Enter a user-defined name. Available variable: $PlentyID. +
**Create subfolder** = The documents are saved in a subfolder. This subfolder is created based on the pattern target_folder/type_date_time/.

|As multi-document
|Place a check mark to merge all documents into a single document. Only this single document will be saved.
|====

[#290]
== Change status

Use the **Change status** sub-procedure to change the status. You can select from the statuses saved in your system.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#170, Order>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Change status** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|Status
|Select the status to be assigned with the sub-procedure from the drop-down list.
|====

[#300]
== Change shipping service provider

Use the **Change shipping service provider** sub-procedure to change the shipping service provider.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#170, Order>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Order** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|Shipping service provider
|Select the shipping service provider from the drop-down list that you want to assign with this sub-procedure. You can select a shipping service provider from all those saved in your system.
|====

[#310]
== Shipping packages

Use the **Shipping packages** sub-procedure to create and process shipping packages.

Procedures This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#170, Order>>

[.subhead]
Settings

No additional settings are required for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

[#320]
== Change shipping profile

Use the **Change shipping profile** sub-procedure to change the shipping profile.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#170, Order>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Change shipping profile** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|Shipping profile
|Select the shipping profile from the drop-down list that you want to assign with this sub-procedure. You can select a shipping profile from all those saved in your system.

|Checkbox
|Place a check mark if you want to use different shipping costs than the ones saved in the selected shipping profile.

|Shipping costs
|Enter the shipping costs. If you placed a check mark in the checkbox, then the shipping costs that are entered will be used.
|====

[#330]
== Send

The **Send** sub-procedure sends the email template that was selected for the <<automation/processes/procedures#220, email>> procedure.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#220, Email>>

[.subhead]
Settings

No additional settings are required for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

[#340]
== Change payment method

Use the **Change payment method** sub-procedure to change the payment method of an order.

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#170, Order>>

[.subhead]
Settings

The following table explains the additional settings for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.

.**Print** sub-procedure
[cols="1,2"]
|====
|Setting |Explanation

|**Payment method**
|Select the payment method to be assigned to the orders with the sub-procedure from the drop-down list.
|====

[#350]
== Save to clipboard

It can take a long time to print or save a large number of documents. This leads to waiting times. You can avoid this by using the **Save to clipboard** sub-procedure. For example, you can use it before a procedure that takes longer to carry out than it does to save. The information will be saved in the background while the procedure is carried out. You can follow this e.g. by the **Print** sub-procedure. The printer will access and print the documents that were saved in the background.

[NOTE]
.Do not combine Save to clipboard with procedures for error handling
====
Do not configure the sub-procedure Save to clipboard for a procedure for which you also want to configure a procedure for error handling. Because documents are cached asynchronously, this combination would mean that the process cannot execute correctly.
====

[.subhead]
Procedures

This sub-procedure is available for the following procedures:

* <<automation/processes/procedures#110, Pick-up/delivery note>>
* <<automation/processes/procedures#120, Address label>>
* <<automation/processes/procedures#130, Offer>>
* <<automation/processes/procedures#150, Item label>>
* <<automation/processes/procedures#180, Order confirmation>>
* <<automation/processes/procedures#210, Documents>>
* <<automation/processes/procedures#240, Entry certificate (Gelangensbestätigung)>>
* <<automation/processes/procedures#250, Credit note>>
* <<automation/processes/procedures#270, Adjustment form>>
* <<automation/processes/procedures#280, Warehouse pick list>>
* <<automation/processes/procedures#290, Delivery note>>
* <<automation/processes/procedures#300, Dunning letter>>
* <<automation/processes/procedures#310, packing list>>
* <<automation/processes/procedures#320, pick list>>
* <<automation/processes/procedures#350, Invoice>>
* <<automation/processes/procedures#360, Repair slip>>
* <<automation/processes/procedures#380, Return label>>
* <<automation/processes/procedures#390, Return slip>>
* <<automation/processes/procedures#430, Shipping center>>

[.subhead]
Settings

No additional settings are required for this sub-procedure. The general settings for sub-procedures are described in <<table-subprocedure-settings-general>>.
