= Verschiedene Listings gleichzeitig bearbeiten
:lang: de
include::{includedir}/_header.adoc[]
:position: 50
:url: videos/ebay/listings/mehrere-listings-bearbeiten

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Du hast viele Listings, die überarbeitet werden müssen? Kein Problem! Verwende einfach die Gruppenfunktion, die Stapelverarbeitung oder die Listing-Vorlagen, um Einstellungen für mehrere Listings gleichzeitig zu bearbeiten.
|<<videos/ebay/listings/mehrere-listings-bearbeiten-teil-eins#video, Bestimmte Listings bearbeiten (0:25)>>

<<videos/ebay/listings/mehrere-listings-bearbeiten-teil-zwei#video, Listings mit bestimmten Kriterien bearbeiten (0:50)>>

<<videos/ebay/listings/mehrere-listings-bearbeiten-teil-drei#video, Listing-Vorlagen nutzen, um Voreinstellungen zu vermeiden (1:18)>>

<<videos/ebay/listings/mehrere-listings-bearbeiten-teil-vier#video, Fallbeispiel: Listings für neue Artikel anlegen (3:52)>>

|===
//end::einleitung[]

video::277274842[vimeo]

// tag::transkript[]
[.collapseBox]
.Transkript
--
Bis hierher hast du vor allem gelernt, wie Du ein Listing erstellen und bearbeiten kannst. Das ist zwar ganz nett, aber in deinem normalen Betrieb wird es sicher mehrere Listings geben, die auch mal gleichzeitig bearbeitet werden müssen.

Kein Problem! plentymarkets bietet dir die Möglichkeit, deine Einstellungen auf mehrere Listings gleichzeitig anzuwenden.

Im Prinzip stehen dir dafür sogar mehrere Optionen zur Verfügung. Wenn du also in plentymarkets bereits mehrere Listings erstellt hast und nun 2-3 spezifische Listings ändern möchtest ... Click "Group function" ...empfehle ich dir die Gruppenfunktion zu nutzen.
Set Directory = eBay UK Die Gruppenfunktion stellt dabei eine Möglichkeit dar plentymarkets klarzumachen, dass beispielsweise für
diese drei Listings diese Einstellung geändert werden soll.
Execute -----------
------------- Es gibt noch eine andere Option die du nutzen kannst, wenn Du in plentymarkets bereits eine ganze Menge
Listings angelegt hast und nur die ändern möchtest, die ein bestimmtes Kriterium erfüllen.
Click on Listings > (Batch processing) Listings
Die Stapelverarbeitung
Set "Flag 1" = 5 Du kannst damit beispielsweise einstellen, dass du nur Listings mit einem bestimmten Flag...
Set Market = eBay; Set Platform = UK
...für eine bestimmte Plattform....
Enter Category ID 1234 ...die sich in einer bestimmten Kategorie befinden, bearbeiten möchtest.
Set Directory = eBay UK Auch hier bestimmst du, dass für alle Listings, die diese Kriterien erfüllen, eine andere Einstellung verwendet
wird.
Execute -------------
Mouseover "No template" in the drop-down menu
Zu guter Letzt möchte ich dir noch die Listing-Vorlage zeigen.
Switch to "Edit listings" tab Die Idee dahinter ist relativ simpel. Anstatt die Einstellungen bei der Anlage
für jedes Listing einzeln zu bearbeiten ....
Switch back to Listings > (Batch processing) Listings; Mouseover green plus
.... kannst du eine Listing-Vorlage erstellen, die alle Einstellungen im Listing automatisch setzt. Grafik 02 - Teig ist auf einem Tisch ausgerollt. Daneben liegen diverse Formen
Die Vorlagen sind also vergleichbar mit Ausstechförmchen.
Grafik 02 - Form fährt über den Teig und überblendet in diverse Kekse, die alle gleich sind
Somit kannst du eine Form anlegen und diese immer dann nutzen, wenn du bestimmte Einstellungen für deine Listings hinterlegen willst.
Grafik 02 - Streusel und Glasur kommen auf die Kekse, damit sie alle unterschiedlich sind
Und du kannst die grundlegende Form deiner Listings sogar noch nachträglich verfeinern um es so einzigartig zu machen.

In Fade to plenty backend
plentymarkets... (Batch processing > Listings)
Open the item menu and item ID ???? (duck) before recording this bit
Under "Listing settings", click "Type" and choose "Fixed price"
...hinterlegst du einfach die Einstellungen , die von der Vorlage gesetzt werden sollen. Scroll a bit down and then back up to top
Auf den ersten Blick sieht es hier aus, als enthalte dieses Menü viele Einstellungen, die du noch nie gesehen hast. Aber der Schein täuscht!
Bild-In-Bild: Das Pop-Up Fenster ist zu sehen und auch die Listing-Vorlage Einstellungen. Eine blaue Umrandung markiert die gleiche Einstellungen
Wenn du genauer hinsiehst, wirst du feststellen, dass diese Einstellungen dieselben sind, die du beim Erstellen eines neuen Listings vorgenommen hast...
Bild-In-Bild: Das Pop-Up Fenster ist zu sehen und auch die Listing-Vorlage Einstellungen. Eine blaue Umrandung markiert die gleiche Einstellungen
...und diese Einstellungen sind dieselben, die du im Tab Base deines Listings genutzt hast.
Switch to "Edit listings" menu (with listing open to Base tab)
Jetzt nur noch ein kleiner Tipp...
Copy the setting "Shipping profile" (in Screenflow use the key stroke setting)
...solltest du mal eine bestimmte Einstellung suchen ... Switch back to "Listings" menu
-----
cmd + f; paste "Shipping profile"
...kannst du ganz einfach deine Browser suche nutzen. Fade to all the template settings are filled in
Sobald du alle Einstellungen vorgenommen hast, die du in deiner Vorlage verwenden möchtest...
Click green plus ...KLICKE ganz einfach das grüne Plus...
Enter name "eBay UK - product line: rubber ducks"
...gib deiner Listing-Vorlage einen Namen...
Save ...und speichere die Einstellungen.
Mouseover template selection in drop-down
Hier ist es dann auch ganz einfach...
Change Platform = Germany; Change Shipping profile = Germany shipping profile
...eine weitere Vorlage mit anderen Einstellungen anzulegen.
Click green plus; Enter name "eBay DE - product line: rubber ducks"; Save
Vielleicht für eine andere Plattform oder für eine andere Produktlinie? Sobald du deine Vorlagen eingerichtet hast...
Open Item > Edit item with ID ???? (duck)
already open ...bist du bereit diese auf deine Listings anzuwenden.
Click on "Multi-Channel" tab Klicke ganz einfach den Multi-Channel Tab....
Link "eBay UK - product line: rubber ducks"; Save
....um eine Listing-Vorlage mit einem bestimmten Artikel zu verknüpfen.
Callout eBay category 1 and 2
Du hast sicherlich auch bemerkt, dass eBay-Kategorie-IDs direkt am Artikel gespeichert werden können. Wenn du also möchtest, kannst du Vorlagen erstellen, die für alle Kategorien greifen oder hier eine bestimmte Kategorie-ID angeben.

Click on "New listing" icon Wenn du ein neues Listing anlegst....
Click on "Listing template" and select "eBay UK - product line: rubber ducks"; Save
...kannst du dann hier deine Vorlage auswählen.
Switch to "Edit listings" with the base tab open
Du kannst aber die Vorlagen auch nutzen um bereits vorhandene Listings zu bearbeiten.
Click "Listing template" icon; Apply
So wendest du sie für ein einzelnes Listing an.
Click on "Market listings" tab; Check top 3 listings; Click "Group function"
Um sie dagegen auf mehrere Listings gleichzeitig anzuwenden gehst du so vor.
Show drop-down with templates; Click "Execute"
----------
Switch back to (Batch processing) Listings; Set "Flag 2" = 3; Execute
Schließlich kannst du deine Vorlage so auf verschiedene Listings anwenden, die bestimmte Filterkriterien erfüllen.
Grafik 03 - Mitarbeiter am Schreibtisch. Glühbirne leuchtet über seinem Kopf
Jetzt da du das Prinzip verstanden hast schauen wir uns das ganze in einem kleinen Praxisbeispiel an.
Fade to "Item > Edit item" with new items as the search results; Callout the item search results
Angenommen, du hast gerade einige neue Produkte zu deinem Portfolio hinzugefügt und möchtest jetzt eBay-Listings aus diese Artikel erstellen.
Open Listings > (Batch processing) Listings
Wenn du noch keine Listing-Vorlage erstellt hast ist das dein erster Halt...
Fade to listing template already filled out
...wo du deine Einstellungen hinterlegst...
Click green plus; Enter name " ???????
"; Save ...und deine Vorlage speicherst.
Switch back to "Item > Edit item"
Der zweite Halt ist die Artikelübersicht....
Check all ...in der du all deine neuen Artikel findest, für die ein Listing erstellt werden soll . Click "Item group function" Hier klickst du auf die Artikel-Gruppenfunktion...
Click "Listing template"; Select template "???????" from drop-down; Execute
...und wendest die Vorlage auf deine Artikel an.
Check all items; Click on "Item group function"
Zu guter letzt öffnest du erneut die Gruppenfunktion...
Check "Create listing"; Execute
...und erstellst Listings für deine Artikel.
Open "Listings > Edit listings"; Callout new listings
Wenn du jetzt die Auftragsübersicht öffnest siehst du alle neuerstellten Listings
PPT In diesem Video hast du gelernt, mehrere Listings gleichzeitig zu ändern. Du hast gesehen, wie du die
Stapelverarbeitung und die Gruppenfunktion einsetzt und den Unterschied zwischen den beiden verstanden. Außerdem haben wir dir gezeigt, wie Du mit den Listing-Vorlagen eine Art Ausstechform erstellst, mit denen du deinen Listings voreingestellte Konfigurationen geben kannst. Mit einem Beispiel konnten wir dir dann noch zeigen, wie einfach du mehrere Listings für eine Reihe neuer Produkte anlegen kannst.
--
//end::transkript[]
