= bol.com
:lang: en
include::{includedir}/_header.adoc[]
:keywords: bol.com, bol, market, marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market bol.com in your plentymarkets system.
:position: 30
:url: markets/bol-com

The Dutch market link:http://bol.com[bol.com^] is the leading online market in Benelux and distributes many different products, including multimedia, electronics, toys etc.

[#100]
== Registering with bol.com

Before setting up bol.com in plentymarkets, you have to register with link:https://bol.com[bol.com^] first.

[#200]
== Setting up bol.com in plentymarkets

Set up bol.com in plentymarkets to sell items on bol.com. To do so, proceed as described below.

[.instruction]
Setting up bol.com in plentymarkets:

. Go to *System » System settings » Markets » bol.com » Settings*.
. Carry out the settings. Pay attention to the explanations given in <<basic-settings-bol>>.
. *Save* the settings.

[[basic-settings-bol]]
.Basic settings for the market bol.com
[cols="1,3"]
|====
|Setting |Explanation

|*Activate automatic data exchange*
|If the data exchange is activated, then items are imported daily, stock is synchronised hourly, and orders are imported hourly.

|*Public key*
|Enter the API key as received from bol.com.

|*Private key*
|Enter the API key as received from bol.com.

|*Client*
|Select a client. Orders are assigned to this client during the order import.

|*Warehouse selection*
|Select the stock quantity for the offer export. Select one of the following options: +
*Use stock quantity sum of all sales warehouses* +
*Use main warehouse of item* +
*Select warehouses* = Select one or more warehouses. +
*Important:* The option *Warehouse selection* affects the item export. If an item is not linked to the warehouses selected here, then this item will not be exported.
|====

Connecting to this market allows for the following automatic processes to take place:

* Hourly order import

[#250]
== Activating an order referrer

In order to link items, properties etc. with bol.com, you have to activate the order referrer bol.com in the *System » System settings » Orders » Order referrer* menu.

[.instruction]
Activating the order referrer bol.com:

. Go to *System » System settings » Orders » Order referrer*.
. Place a check mark next to *bol.com*.
. *Save* the settings.

[#300]
== Setting the item availability

Items have to be available for bol.com. This is done in the *Availability* tab of an item within the *Item » Edit item » Open item » Tab: Variation ID* menu.

[.instruction]
Setting the item availability for bol.com:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Activate the option *bol.com*.
. Click on *Add*. +
→ The market is added.
. *Save* the settings. +
→ The item is available on bol.com.

The availability for variations can be individually edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

Note that item descriptions have to be in Dutch for bol.com.

[#400]
== Linking categories

Link your online store categories to the bol.com categories in order to display your items in these bol.com categories. Further items from the linked category are assigned automatically.

[.instruction]
Linking categories:

. Go to *System » System settings » Markets » bol.com » Category link*.
. Click on *Search*.  +
→ The *Select category* window opens.
. Select the bol.com category that best matches your online store category.
. Click on *Apply*. +
→ The name and category path of the bol.com category are displayed.
. If you know the name of the bol.com category, enter it directly into the *Market category* field to link it to your online store category.
. *Save* the settings.

[#450]
== Creating properties

Next create <<item/managing-items#480, properties>> and link these to the bol.com properties. Matching properties to a bol.com category can be found within the bol.com data model file. Download the bol.com data model file link:https://developers.bol.com/datamodel/[here^].

[.instruction]
Creating a property:

. Go to *System » System settings » Item » Characteristics*.
. Click on the *New property* tab.
. Enter a name for the property under *Name (internal)*.
. Select *nl* for Dutch from the *Language* drop-down list.
. Enter the Dutch name that you want to use for this property into the *Name* field.
. Select the option *Text* from the *Property type* drop-down list.
. Enter the bol.com property which can be found in the column *Attribute name* within the bol.com data model file into the line *bol.com property*.
. *Save* the settings.

*bol_fulfillment* is a mandatory field for the offer export. This indicates whether the item is shipped by you or by bol.com. Enter the bol.com property *bol_fulfillment* into the line *bol.com property*.

If you want to sell used items on bol.com, you have to indicate this by using the property *bol_used*. Enter the bol.com property *bol_used* into the line *bol.com property*.

[#500]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer bol.com. This price is shown on bol.com.

[.instruction]
Defining a sales price for bol.com:

. Go to *System » System settings » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *bol.com*.
. *Save* the settings.

[#600]
== Setting up the item export and offer export

This chapter explains how to export your items and offers to bol.com. Items and offers are transferred to bol.com with the elastic export. First, create the data formats *BolItemExport* and *BolOfferExport* and then send the CSV files to bol.com. Both files have to be sent in order to sell items on bol.com.

The following fields are mandatory for the item export:

* EAN
* SKU
* Name
* Categories
* Item description
* Image
* Manufacturer

The following fields are mandatory for the offer export:

* EAN
* SKU
* Stock
* Price
* Item condition
* Shipping availability
* Fulfilment by

[.instruction]
Setting up the export:

. Go to *Data » Elastic export*.
. Click on *New export*.
. Carry out the settings. Pay attention to the explanations given in <<settings-item-export-bol>>.
. Carry out further settings for item filters and format settings. Pay attention to the explanations given in table 2 on the <<data/exporting-data/elastic-export#, Elastic export>> page of the manual.
. *Save* the settings. +
→ The export format is given an ID and it appears in the overview within the *Exports* tab. +
→ In the *Data » Elastic Export » Tab: Exports* menu, click on *Download* (arrow icon) to download the file that you have created.

[[settings-item-export-bol]]
.Settings for the item export
[cols="1,3"]
|====
|Setting |Explanation

2+|Settings

|*Name*
|Enter a name. The export format is listed by this name in the overview within the *Exports* tab.

|*Type*
|Select the type *item* from the drop-down list.

|*Format*
|Select the format *BolItemExport* for the item export or *BolOfferExport* for the offer export.

|*Limit*
|Enter a number. If you want to transfer more than 10,000 data records to bol.com, then the output file is not generated again for another 24 hours. This is to save resources.

|*Provisioning*
|Select *FTPS*.

|*File name*, +
*server*, +
*port*, +
*user name*, +
*password*, +
*path*
|Enter a parameter. The access data including the password and user name are provided by bol.com. The file name for BolOfferExport has the structure <SellerID>.csv. The file name for BolItemExport has the structure <SellerID>.txt. +
The file for the format *BolItemExport* has to be saved in the */SQUARE/feed* folder. +
The file for the format *BolOfferExport* has to be saved in the */inbound* folder.

|*Transfer*
|Select *daily* for the item export, as bol.com allows a maximum of 4 exports per day. Select *hourly* for the offer export.
|====

[#650]
== Activating the payment method

Activate the <<payment/managing-payment-methods#, payment method>> *BOL.com* as described below.

[.instruction]
Activating the bol.com payment method:

. Go to *System » System settings » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
. Click on *BOL.com*. +
→ The *Settings* tab opens.
. Carry out the settings. Pay attention to the explanations given in <<payment-method-bol>>.
. Place a check mark next to the option *Active*.
. *Save* the settings.

[[payment-method-bol]]
.Settings for the payment method
[cols="1,3"]
|====
|Setting |Explanation

|*Language*
|The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo* and *Upload logo*. This enables you to enter values for these options in various languages. The values for a language are activated as soon as a buyer selects the language in the online store.

|*Name*
|Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
|Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
|If you selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
|Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely set up.

|*Logo*
|Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

|*Logo view*
|If *Show upload logo* was selected from the *Logo* drop-down list, then the logo that was uploaded is displayed here.

|*Upload logo*
|If *Show upload logo* was selected from the *Logo* drop-down list, then upload an external logo here. +
Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG, and JPG.

|*Priority*
|Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
|If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. *Important:* Do not enter a value into both fields.  +
For further information, refer to the <<basics/working-with-plentymarkets/statistics/managing-statistics#, Managing statistics>> page. For an example of flat rate and percentage costs, refer to the <<payment/managing-payment-methods#20, Managing payment methods>> page.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *System » System settings » CRM » Classes* to activate or deactivate *permitted payment methods*. +
For further information, refer to the <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter.
====

For further information, refer to the <<payment/managing-payment-methods#, Managing payment methods>> page.

[#700]
== Automatically sending shipping confirmations

Set up an <<automation/event-procedures#, event procedure>> to automatically send shipping confirmations to bol.com when the outgoing items have been booked.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » System settings » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<event-procedure-shipping-confirmation-bol>>.
. *Save* the settings. +
→ The event is created.
. Carry out further settings. Pay attention to the explanations given in <<event-procedure-shipping-confirmation-bol>>.
. Place a check mark next to the option *Active*.
. *Save* the settings. +
→ The event procedure is saved.
--

[[event-procedure-shipping-confirmation-bol]]
.Event procedure for automatically sending shipping confirmations to bol.com
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order change: Outgoing items booked*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Referrer*
|*bol.com*

|*Procedure*
|*Shipping > Send shipping confirmation to bol.com*
|
|====

[#800]
== Automatically sending the return status

Set up an <<automation/event-procedures#, event procedure>> to automatically inform bol.com of the status of a return. bol.com requests the status of returns. The following cancellation reasons can be transferred to bol.com:

* Return received
* Repaired or exchanged
* Incomplete return
* Refund without returning goods

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » System settings » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<event-procedure-return-status-bol>>.
. *Save* the settings. +
→ The event is created.
. Carry out further settings. Pay attention to the explanations given in <<event-procedure-return-status-bol>>.
. Place a check mark next to the option *Active*.
. *Save* the settings. +
→ The event procedure is saved.
--

[[event-procedure-return-status-bol]]
.Event procedure for automatically sending return statuses to bol.com
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*New return*
|

|*Filter 1*
|*Order > Order type*
|*Return*

|*Filter 2*
|*Order > Referrer*
|*bol.com*

|*Procedure*
|*Order > Send return status to bol.com*
|Select a status.
|====

[#900]
== Automatically sending cancellations

Set up an <<automation/event-procedures#, event procedure>> to automatically inform bol.com of cancellations. Whenever you are dealing with cancellations, you need to send bol.com a reason for the cancellation. Go to *System » System settings » Orders » Order status* and create additional order statuses as needed. The following cancellation reasons can be transferred to bol.com:

* Item not in stock
* Customer cancellation

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » System settings » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<event-procedure-cancellations-bol>>.
. *Save* the settings. +
→ The event is created.
. Carry out further settings. Pay attention to the explanations given in <<event-procedure-cancellations-bol>>.
. Place a check mark next to the option *Active*.
. *Save* the settings. +
→ The event procedure is saved.
--

[[event-procedure-cancellations-bol]]
.Event procedure for automatically sending cancellations to bol.com
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Status change: [8.1] Cancelled by customer*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Referrer*
|*bol.com*

|*Procedure*
|*Order > Send cancellation to bol.com*
|*Customer cancellation*
|====

[#1000]
== Viewing the API log

The <<data/api-log#, Data » API log>> menu contains a history of processes that run via the bol.com interface.

[.instruction]
Viewing the API log:

. Go to *Data » API log » Tab: API log*.
. Select the format *bol.com* from the *Process* drop-down list.
. Select a *date* if you only want to see entries for a specific day.
. Click on *Search* to carry out the search. +
→ The processes are displayed.
