= Cdiscount
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Cdiscount, Market, Marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market Cdiscount in your plentymarkets system.
:position: 40

Cdiscount was the first online market in France. Today, it is still one of the most popular and widely used French online sales platforms. In order to sell items on Cdiscount, you need to make your catalogue of items completely available in French.

[#100]
== Registering with Cdiscount

You need to register with Cdiscount before setting up Cdiscount in plentymarkets. Fill in the link:https://marketplace-registration.cdiscount.com/#[registration form^] and send your data to Cdiscount. One of the market's support employees will contact you to verify the registration.

Change your API password before you save the access data in your plentymarkets system. A new password is sent to the mailbox in your Cdiscount seller back end area.

[#200]
== Setting up Cdiscount in plentymarkets

Once you have registered with Cdiscount, use the data that is saved there to set up the market in plentymarkets. To do so, proceed as follows.

[IMPORTANT]
.Access data
====
Use the API access data for the configuration. Do not confuse the API access data with your access data for Cdiscount's back end. You find the user name within Cdiscount's back end. The back end is also where the password is generated or edited.
====

[.instruction]
Setting up Cdiscount in plentymarkets:

. Go to *System » Markets » Cdiscount » Tab: Settings*.
. Carry out the settings. Pay attention to the explanations given in <<basic-settings-cdiscount>>.
. *Save* the settings.

[IMPORTANT]
.Access data
====
Use the API access data for the configuration (user name and password). The user name includes the suffix api. In contrast, use the login access data to log into the back end area on Cdiscount.
====

[[basic-settings-cdiscount]]
.Basic settings for the market Cdiscount
[cols="1,3"]
|====
|Setting |Explanation

|*Request product creation*
|Activate in order to activate the automatic stock synchronisation and the order import via the API interface. If the option *Request product creation* is not activated, offers are only generated for already existing items on Cdiscount.

|*Update prices and stock and activate order import*
|Activate to transfer the item catalogue via the CSV interface. Stock is still synchronised automatically via the API interface. +
When this setting is activated along with the setting *Request product creation*, then the data is exchanged automatically via the API interface only.

2+|*Sales partner information*

|*Company name*
|Enter the company name as stated on Cdiscount (optional).

|*API user name*
|Enter the API user name that you received from Cdiscount.

|*API password*
|Enter the API password that you received from Cdiscount.

2+|*Order settings*

|*Cdiscount C Logistique order status*
|Status for Cdiscount C Logistique orders. *Status [7] Outgoing items booked* is set by default. However, no stock is booked from the warehouse. The status can be edited as desired for future order imports. Please note that once an order entered status 7, the order cannot enter a smaller status.

2+|*Item settings*

|*Item name*
|Select which field to transfer to Cdiscount as the item name.

|*Short item description*
|Select which field to transfer to Cdiscount as the short item description.

|*Item description*
|Select which field to transfer to Cdiscount as the item description.

|*Item marketing description*
|Select the text that you want to transfer as marketing description or select *Do not transfer*.

|*Transfer variation dimensions*
|Place a check mark if you want to transfer the variation’s dimensions.

|*Stock quantity for items that are not limited to stock and do not have a positive net stock*
|Enter the value. The entered value is transferred as stock if the item is not limited to stock and if the item does not have a positive net stock.

|*Warehouse*
|Select which warehouse should be used. Select one warehouse, several warehouses, or *Total in all warehouses*.

|*Minimum price*
|Select the minimum price for an item. +
*Important:* The minimum price must be the special offer price saved for the item.

2+|*Preparation for shipping (in days)*

|*Default preparation time for shipping*
|*Mandatory field* +
Enter a default preparation time for shipping in days. The value entered here is transferred to Cdiscount. Cdiscount increases this value on the basis of the shipping method. +
*Important:* Only enter values from 1-10.

|*Availability 1-10*
|Enter an availability from 1-10. The availability is the same as the availability of variations in the *Availability* section of the *Item » Edit item » Open item » Tab: Variation ID* menu. The value entered here is transferred to Cdiscount. Cdiscount increases this value on the basis of the shipping method. +
If you do not enter a value here, the *standard preparation time* is transferred to Cdiscount.

2+|*Shipping costs*

|*Apply shipping costs from the shipping cost calculation*
|Select *Configuration 1* or *Configuration 2* and a *payment method*. The selected configuration transfers the standard shipping costs to Cdiscount.  +
The options that can be selected here are the settings for Configuration 1 and Configuration 2 that are configured in the <<order-processing/fulfilment/preparing-the-shipment#1700, System » Orders » Shipping » Settings » Tab: Calculate shipping costs>> menu.

|*Overwrite shipping costs*
|Enter a fixed price for the shipping costs. The shipping costs entered here are transferred to Cdiscount instead of the shipping costs that are saved for an item.

|*Item ID for instalment purchase fee*
|Cdiscount charges a fee for instalment purchases. It is possible to create an item that bills customers for this fee. To do so, create an item in plentymarkets and enter the ID here.
|====

Connecting to this market allows for the following automatic functions to take place:

* Daily item export
* Hourly stock synchronisation
* Hourly order import

During the hourly order import, no invoice data or delivery information are transferred from Cdiscount when the order is first imported. The order remains in status [3]. It may take up to 48 hours for the invoice data and the delivery information to be transferred to plentymarkets because Cdiscount carries out a credit rating for the end customer first.

[#250]
== Activating an order referrer

In order to link items, properties etc. with Cdiscount you have to activate the order referrer Cdiscount in the menu *System » Orders » Order referrer*.

[.instruction]
Activating order referrer for Cdiscount:

. Go to *System » Orders » Order referrer*.
. Place a check mark next to the option *Cdiscount*.
. *Save* the settings.

[#300]
== Setting the item availability

Items have to be available for Cdiscount. This is done in the *Availability* tab of an item within the <<item/managing-items#170, Item » Edit item » Open item » Tab: Variation ID>> menu.

[.instruction]
Setting the item availability for Cdiscount:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Activate the option *Cdiscount*.
. Click on *Add*. +
→ The market is added.
. *Save* the settings. +
→ The item is available on Cdiscount.

The availability for variations can be individually edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

Use the <<item/managing-items#330, Variation group function>>, the <<item/managing-items#330, Batch processing>> or the <<item/managing-items#330, Dynamic Export and Import of the format VariationMarketLink>> in order to edit the availability for several variations.

[#350]
==  Defining SKU manually

Add SKUs manually for specific referrers in the menu <<item/managing-items#170, Item » Edit item » Open item » Tab: Variation ID » Tab: Availability>> if needed.

[IMPORTANT]
.Automatic SKU generation
====
If the setting *Request product creation* is activated in the menu *System » Markets » Cdiscount » Tab: Settings*, a SKU is generated which matches the variation ID for each variation during the export that takes place at night.
====

[IMPORTANT]
.SKUs of already existing items
====
Items with variations in plentymarkets can be linked to already existing items on Cdiscount. The SKU serves as the identification in plentymarkets. The SKU can be found as *Your reference* on Cdiscount's back end.
====

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
.  Click on the *Availability* tab.
.  Click on *Add* in the section *SKU*. +
→ The window *New SKU* is displayed.
.  Select the referrer *Cdiscount.com*.
.  Enter the SKU.
.  Click on *Add*. +
→ The SKU is saved and displayed.

[#400]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Cdiscount. This price is displayed on Cdiscount.

[.instruction]
Defining the sales price for Cdiscount:

. Open the menu *System » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *Cdiscount*.
. *Save* the settings.

Afterwards, <<item/managing-items#240, link>> the sales price with the desired variations.

==  Setting the barcode

Proceed as described below to define a barcode for the order referrer Cdiscount. This barcode is transferred to Cdiscount for the variation. The barcode has to be of the type GTIN 13.

[.instruction]
Setting the barcode for Cdiscount:

.  Go to *System » Item » Barcode*.
.  Place a check mark next to the referrer *Cdiscount*.
. *Save* the settings.

Afterwards, <<item/managing-items#250, link>> the barcode with the desired variations.

[#500]
== Linking categories

In order to link your categories with Cdiscount categories, download the Cdiscount category list first. Then link your own categories with the most appropriate Cdiscount categories.

[.instruction]
Downloading the category list:

. Go to *System » Markets » Cdiscount.com » Tab: Category list*.
. Click on the gear-wheel icon *Update category list*. +
→ The category list is displayed with code and category names further below.

You need the codes displayed here in order to link your categories with Cdiscount categories. To do so, proceed as follows.

[.instruction]
Linking categories:

. Go to *System » Markets » Cdiscount.com » Tab: Category link*.
. Enter the Cdiscount category code matching your online store category under *Category link*.
. *Save* the settings.

[#600]
== Linking attributes

If you have created <<item/managing-items#390, attributes>> in your plentymarkets system, you have to link these attributes with Cdiscount. Proceed as described below to link the attribute Colour with Cdiscount. Link further attributes in the same way.

[.instruction]
Linking attributes:

. Go to *System » Item » Attributes*. +
→ An overview of all existing attributes opens.
. Expand the attribute *Colour*.
. Open the *Market variation* tab.
. Select the option *Cdiscount.com* from the *Market* drop-down list. +
→ A second drop-down list *Cdiscount.com* is displayed.
. Select the attribute *Colour* from the *Cdiscount.com* drop-down list.
. Enter the Cdiscount attribute values that most closely match your own attribute values. This is done in the Market variation area.
. *Save* the settings.

[#700]
== Creating properties

Next create <<item/managing-items#480, properties>> and link the properties to Cdiscount properties. The properties have to be created in French.

[.instruction]
Creating a property:

. Go to *System » Item » Properties*.
. Click on the *New property* tab.
. Enter a name for the property under *Name (internal)*.
. Select *fr* for French from the *Language* drop-down menu.
. Enter the French name that you want to use for this property into the *Name* field.
. Select the option *Text* from the *Property type* drop-down list.
. Select the Cdiscount property from the *Cdiscount.com attribute* drop-down list.
. *Save* the settings.

[#800]
== Linking manufacturers

Create manufacturer links so that your items will be displayed for sale on Cdiscount. First download the Cdiscount manufacturer list and then link your own manufacturers with the most appropriate Cdiscount manufacturers by saving the Cdiscount manufacturer ID in the system. The Cdiscount manufacturer ID is the name of the manufacturer.

[.instruction]
Downloading the manufacturer list:

. Go to *System » Markets » Cdiscount.com » Tab: Manufacturer list*.
. Click on *Update manufacturer list*. +
→ The manufacturer list is displayed with code and manufacturer names further below.
. Select and copy the manufacturer to the clipboard.
. *Tip:* Download the manufacturer list as a CSV file. You can search for specific manufacturers in this file. +
 Go to *System » Markets » Cdiscount » Tab: Manufacturer list* and click on *Download manufacturer list as CSV file*.

Now, proceed as follows to link the manufacturer.

[.instruction]
Linking manufacturers:

. Go to *System » Item » Manufacturers*.
. Open the manufacturer that you want to link to Cdiscount.
. Enter the name of the manufacturer into the field *Cdiscount.com ID*.
. *Save* the settings.

[#900]
==  Activating the payment method

Activate the <<order-processing/payment/managing-payment-methods#, payment method>> *Cdiscount* as described below.

[.instruction]
Activating the Cdiscount payment method:

.  Go to *System » Orders » Payment » Methods*.
.  Place a check mark next to the setting *Also show inactive*.
.  Open the folder *International*.
.  Click on *Cdiscount*. +
→ The *Settings* tab opens.
.  Carry out the settings. Pay attention to the explanations given in <<payment-method-cdiscount>>.
.  Place a check mark next to the option *Active*.
. *Save* the settings.

[[payment-method-cdiscount]]
.Settings for the payment method
[cols="1,3"]
|====
| Setting | Explanation

|*Language*
| The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo* and *Upload logo*. This enables you to enter values for these options in various languages. The values for a language are activated as soon as a buyer selects the language in the online store.

|*Name*
| Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
| Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
| If you have selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
| Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely configured.

|*Logo*
| Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

|*Logo view*
| If *Show upload logo* has been selected from the *Logo* drop-down list, then the logo that has been uploaded is displayed here.

|*Upload logo*
| If *Show upload logo* has been selected from the *Logo* drop-down list, upload an external logo here. +
 Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|*Priority*
| Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
| If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. *Important*: Do not enter a value into both fields. +
For further information, refer to the <<basics/statistics/managing-statistics#, Managing statistics>> page of the manual. For an example of flat rate and percentage costs, refer to the <<order-processing/payment/managing-payment-methods#20, Managing payment methods>> page of the manual.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *System » CRM » Classes* to activate or deactivate *Permitted payment methods*. +
For further information, refer to the <<order-processing/payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter.
====

For further information, refer to the <<order-processing/payment/managing-payment-methods#, Managing payment methods>> page of the manual.

==  Configuring data exchange

In order for the interface to successfully carry out the item export, the order import and the stock synchronisation, certain settings are mandatory. Pay attention to the following list.

[IMPORTANT]
.Product creation on Cdiscount
====
The product creation serves as a query to add a new product to Cdiscount's product database. As soon as Cdiscount approves and adds your item to its database, you can not make any further changes to the item data. Therefore, check if you have saved all the necessary data. The check list serves as a list for all mandatory settings for the product creation. Further settings can be carried out as desired.
====

[IMPORTANT]
.Offer creation on Cdiscount
====
Every created item will be saved in a database on Cdiscount. Every item can be identified by eat least one EAN. Marking products with EANs enables sellers to create offers for these products. The configuration is simpler in comparison to the previous product creation and makes it easy to get started on Cdiscount. +
 The offer creation as well as the synchronisation (stock) are controlled by one file. +
 The following check list contains all mandatory settings for an item to be transferred in this file.
====

[[mandatory-settings-cdiscount]]
.Mandatory settings for Cdiscount
[cols="1,3"]
|====
| Settings area  | Settings

2+|*Offer creation/Stock synchronisation*

| Basic settings for the market
a|
* *Update prices and stock and activate order import* is activated.
* *API user name* is entered.
* *API password* is entered.
* *Preparation for shipping (in days)* is set.
* *Apply shipping costs from shipping cost calculation* or *Overwrite shipping costs* is configured.

| Configuration of the variation
a|
* The variation is *active*
* The variation *availability* is set.
* A *sales price* is created and linked.
* A *barcode* is configured and linked.
* A *SKU* is set.

2+|*Item creation*

| Basic settings for the market
a|
* *Update prices and stock and activate order import* is activated.
* *API user name* is entered.
* *API password* is entered.

| Configuration of the item
a|
* *Item descriptions* are entered in French.
* A *Manufacturer* is saved for the item and linked with Cdiscount.

| Configuration of the variation for single items
a|
* The variation is *active*
* The variation *availability* is set.
* A *barcode* is configured and linked.
* A *SKU* is set.
* At least one *category* which is linked to Cdiscount is saved for the item.
* At least one *category* which is linked to Cdiscount is activated for the standard client.
* At least one *image* is saved for the item and released for Cdiscount.

| Further settings of the variation for variation items
a|
* The variation's *attributes* are linked with Cdiscount.

2+|*Order import*

| Basic settings for the market
a|
* *Update prices and stock and activate order import* is activated.
* *API user name* is entered.
* *API password* is entered.

| Payment methods
a|
* The *payment method Cdiscount* is activated.

| Configuration of the variation
a|
* A *SKU* is set.

|====

[#1000]
=== Downloading the item catalogue and stock synchronisation

In the *Archive* tab, download the item catalogue or the stock synchronisation as a ZIP file. Downloading the ZIP files makes it possible for you to transfer the files to your Cdiscount contact person in case there are problems during the import. This helps Cdiscount to analyse the situation more quickly in order to eliminate the problem.

[.instruction]
Transferring the stock synchronisation to Cdiscount:

. Go to *System » Markets » Cdiscount.com » Tab: Archive*.
. Click on *Download stock synchronisation*.
. Save the file on your computer and send it to Cdiscount in an email if needed.

[#1100]
=== Exporting the item catalogue via CSV file

In rare cases, the automatic item export may not work correctly. In such cases export your French item catalogue as a CSV file to Cdiscount. To do so, go to the *Data » Elastic export* menu and carry out the settings as described below. After you saved all necessary settings as described below, copy the complete URL and send it to Cdiscount. Stock is updated once an hour.

[.instruction]
Setting up an export:

. Go to *System » Markets » Cdiscount » Tab: Settings*.
. Activate the option *Update prices and stock and activate order import*. +
*Important:* The option *Request product creation* must not be active. Otherwise, the automatic data exchange would be carried out via the API interface.
. *Save* the settings.
. Switch to the menu *Data » Elastic export*.
. Click on the *New export* tab.
. Select *Cdiscount.com* from the *Data format* drop-down list.
. Enter a name for the export.
. Pay attention to the explanations given in the <<data/export-import/exporting-data#30, Exporting data with the dynamic import>> page of the manual and carry out the settings.
. *Save* the settings. +
→ The export is created as a sub-folder in the *Exports* tab and the URL is generated.
. Click on the *Exports* tab and open the sub-folder *Cdiscount.com*.
. Copy the *URL* and send the URL to Cdiscount.

[NOTE]
.Linking properties for a CSV file
====
Link the properties *Gender*, *Main colour*, *Note*, *Comment*, *Marketing description*, *Audience* and *Sport* in the <<item/managing-items#480, System » Item » Properties>> menu in order to transfer your item catalogue to Cdiscount via a CSV file.
====

[#1200]
== Automatically sending returns

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically send returns to Cdiscount.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-returns-cdiscount>> below.
. *Save* the settings.
.  Carry out the settings as described in <<event-procedure-returns-cdiscount>> below.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[event-procedure-returns-cdiscount]]
.Event procedure for automatically sending returns to Cdiscount
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order generation: New return*
|

|*Filter 1*
|*Order &gt; Order type*
|*Return*

|*Filter 2*
|*Order &gt; Referrer*
|*CDiscount.fr*

|*Procedure*
|*Return &gt; Send return to Cdiscount*
|
|====

[#1300]
== Automatically updating the order status

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically update the order status on Cdiscount whenever specific events occur. You can use event procedures to automatically assign the following statuses to orders on Cdiscount:
--

* Refused by seller
* Shipped by seller#
* Shipment refused by seller

An example of an event procedure that you can use to notify Cdiscount when you have shipped the ordered items is described below. Set up further event procedures in the same way.

In order to successfully transfer a shipping confirmation, the following data must be saved for the order.

* Shipping service provider
* Outgoing items must be booked
* External order number

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<update-order-status-cdiscount>>.
. *Save* the settings.
.  Carry out the settings as described in <<update-order-status-cdiscount>>.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[update-order-status-cdiscount]]
.Event procedure for automatically updating order statuses on Cdiscount
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order change: Status change &gt; Outgoing items booked* +
*_Or:_* *Order change: Outgoing items booked*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*CDiscount.fr*

|*Procedure*
|*Order > Notify Cdiscount of order changes*
|*Shipped by seller*
|====

[IMPORTANT]
.Status: Accepted by seller
====
The status *Accepted by seller* does not have to be sent via an event procedure. Every incoming order triggers an automatic message about this status and sends it to Cdiscount.
====

[#1400]
== Viewing the API log

The menu *Data » API log* contains a history of processes that run via the Cdiscount interface. The *Cdiscount.com* format is available for Cdiscount.

[.instruction]
Viewing the API log:

.  Go to *Data » API log » Tab: API log*.
.  Select the format *Cdiscount.com* from the *Process* drop-down list.
.  Select a date if you only want to see entries for a specific day.
.  Select the number of results per page.
.  Click on *Search* to display the results.
