= Check24
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Check24, market, marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market Check24 in your plentymarkets system.
:position: 50
:url: markets/check24
:id: BZ3ZIMQ

On this page, you will find information about the settings you need to carry out in order to set up the market Check24 in plentymarkets. Learn how to set up the interface, how to export items to Check24 and how to define sales prices.

[#100]
== Registering with Check24

You need to register with link:https://merchantcenter.check24.de/landing/partner_info[Check24^] before setting up Check24 in plentymarkets.

[#200]
== Setting up Check24 in plentymarkets

Carry out the following settings in plentymarkets in order to set up the interface to Check24.

[.instruction]
Setting up Check24:

. Go to *Setup » Markets » Check24*.
. Activate the automatic data exchange.
. Enter the user name for the FTP partner login.
. Enter the FTP access password.
. *Save* (icon:save[role="green"]) the settings.

Connecting to this market allows for the following automatic processes to take place:

* hourly order synchronisation

[#250]
=== Activating the order referrer

In order to link items, properties etc. with Check24, you have to activate the order referrer Check24 in the *Setup » Orders » Order referrer* menu.

[.instruction]
Activating the order referrer for Check24:

. Go to *Setup » Orders » Order referrer*.
. Place a check mark next to *Check24*.
. *Save* (icon:save[role="green"]) the settings.

[#300]
=== Setting the item availability

Items have to be available for Check24. This is done in the *Availability* tab of an item within the *Item » Edit item » Open item » Tab: Variation ID* menu.

[.instruction]
Activating the item availability for Check24:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Activate the option *Check24*.
. Activate the option *Web API*.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The market is added.
. *Save* (icon:save[role="green"]) the settings.

The availability for variations can be edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

[#400]
===  Defining SKUs

Add SKUs manually for specific referrers in the *Item » Edit item » Open item » Tab: Variation ID » Tab: Availability* menu if needed.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Click on the *Availability* tab.
. Click on *Add* (icon:plus-square[role="green"]) in the *SKU* section. +
→ The *New SKU* window is displayed.
. Select the referrer *Check24*.
. Select the corresponding marketplace account.
. Enter the SKU.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The SKU is saved and displayed.

[#500]
=== Setting up the item export

This section explains how to transfer your items to Check24. The item export for Check24 is carried out by the elastic export. The data format Check24DE is used for this. Therefore, the plugins *ElasticExport* and *ElasticExportCheck24DE* have to be installed. First, create the data format Check24DE. Then transfer the URL to Check24.

[.instruction]
Setting up the item export:

. Go to *Data » Elastic export*.
. Click on *New export*.
. Carry out the settings. Pay attention to the explanations given in <<settings-item-export-check24>>.
. Carry out further settings for item filters and format settings. Pay attention to the explanations given in table 2 on the <<data/exporting-data/elastic-export#300, Elastic export>> page. +
  *_Tip:_* In order to only export items to Check24 which are activated for Check 24 and available for the market in the item’s *Availability* tab, select the item filter *Active* and the item filter *Markets » Check24*.
. *Save* (icon:save[role="green"]) the settings. +
→ The export format is given an ID and it appears in the overview within the *Exports* tab.

[[settings-item-export-check24]]
.Settings for the item export
[cols="1,3"]
|====
|Setting |Explanation

2+|Settings

|*Name*
|Enter a name. The export format is listed by this name in the overview within the *Exports* tab.

|*Type*
|Select the type *item* from the drop-down list.

|*Format*
|Select the format *Check24DE* from the drop-down list.

|*Limit*
|Enter a number. If you want to transfer more than 10,000 data records to Check24, then the output file is not generated again for another 24 hours. This is to save resources.

|*Provisioning*
|Select *URL*.

|*Token*, +
*URL*
|If you selected the option *URL* under *Provisioning*, then click on *Generate token*. The token is entered automatically. The URL is entered automatically if the token was generated under *Token*. Give this URL to Check24.de in order to export the items.
|====

[IMPORTANT]
.Export information
====
If you change one or more settings, then you will have to transfer the new link to Check24.

A maximum of 4000 items is exported at once. If you export more items, then a second export is automatically carried out. To display the second export process, set the parameter *&Page* = in the export link to *2*.

Technical data is transferred to Check24 in the last column of the export file.
====

[#600]
=== Defining a sales price

Proceed as described below to define a sales price for the order referrer Check24. This price is shown on Check 24.

[.instruction]
Defining a sales price for Check24:

. Go to *Setup » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *Check24*.
. *Save* (icon:save[role="green"]) the settings.

[#700]
=== Activating the payment method

Activate the <<payment/managing-payment-methods#, payment method>> *Check24* as described below.

[.instruction]
Activating the payment method Check24:

. Go to *System » System settings » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Click on the folder *DE > Check24*.  +
→ The settings for the Check24 payment method are displayed.
. Carry out the settings. Pay attention to the explanations given in <<settings-payment-method-check24>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings.

[[settings-payment-method-check24]]
.Settings for the payment method
[cols="1,3"]
|====
|Setting |Explanation

|*Language*
|The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo*, and *Upload logo*. This enables you to enter values for these options in various languages. The values for a language are activated as soon as a buyer selects the language in the online store.

|*Name*
|Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
|Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
|If you selected the *Info page (external)* option under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
|Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely set up.

|*Logo*
|Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

|*Logo view*
|If *Show upload logo* was selected from the *Logo* drop-down list, then the logo that was uploaded is displayed here.

|*Upload logo*
|If *Show upload logo* was selected from the *Logo* drop-down list, then upload an external logo here. +
Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG, and JPG.

|*Priority*
|Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
|If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. *Important:* Do not enter a value into both fields.  +
For further information, refer to the <<basics/working-with-plentymarkets/statistics/managing-statistics#, Managing statistics>> page. For an example of flat rate and percentage costs, refer to the <<payment/managing-payment-methods#20, Managing payment methods>> page.
|====

[#950]
== Order import

After the order import the order is set to status *[5] cleared for shipping*. The invoice address is always Check24. The customer's address is the delivery address.

[#975]
== Sending shipping confirmations

At the moment it is not possible to automatically send shipping confirmations via the interface. Contact Check24 to set up automatic shipping confirmations.

[#1000]
== Viewing the API log

The *Data » API log* menu contains a history of processes that run via the Check24 interface. The *Check24OrderImportAdapter* format is available for Check24.

[.instruction]
Viewing the API log:

. Go to *Data » API log » Tab: API log*.
. Select the format *Check24OrderImportAdapter* from the *Process* drop-down list.
. Select a *date* if you only want to see entries for a specific day.
. Select the number of results per page.
. Click on *Search* (icon:search[role="blue"]) to display the results.
