= Check24
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Check24, Market, Marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market Check24 in your plentymarkets system.
:position: 50

On this page, you will find information about the settings you need to carry out in order to set up the market Check24 in plentymarkets. Learn how to set up the interface, how to export items to Check24 and how to define sales prices.

[#100]
== Registering with Check24

You need to register with link:https://merchantcenter.check24.de/landing/partner_info[Check24^] before setting up Check24 in plentymarkets.

[#200]
== Setting up Check24 in plentymarkets

Carry out the following settings in plentymarkets in order to set up the interface to Check24.

[.instruction]
Setting up Check24:

. Go to *System » System settings » Markets » Check24*.
. Activate the automatic data exchange.
. Enter the user name for the FTP partner login.
. Enter the FTP access password.
. *Save* the settings.

Connecting to this market allows for the following automatic processes to take place:

* hourly order synchronisation

[#250]
=== Activating an order referrer

In order to link items, properties etc. with Check24 you have to activate the order referrer Check24 in the menu *System » System settings » Orders » Order referrer*.

[.instruction]
Activating the order referrer for Check24:

. Go to *System » System settings » Orders » Order referrer*.
. Place a check mark next to *Check24*.
. *Save* the settings.

[#300]
=== Setting the item availability

Items have to be available for Check24. This is done in the *Availability* tab of an item within the *Item » Edit item » Open item » Tab: Variation ID* menu.

[.instruction]
Activating the item availability for Check24:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Activate the option *Check24*.
. Activate the option *Web API*.
. Click on *Add*. +
→ The market is added.
. *Save* the settings.

The availability for variations can be individually edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

[#400]
===  Defining SKUs

Add SKUs for specific referrers in the *Availability* tab of the menu <<item/managing-items#170, Item » Edit item » Open item » Tab: Variation ID>>.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
.  Click on the *Availability* tab.
.  Click on *Add* in the section *SKU*. +
→ The window *New SKU* is displayed.
.  Select the referrer *Check24*.
.  Select the corresponding marketplace account.
.  Enter the SKU.
.  Click on *Add*. +
→ The SKU is saved and displayed.

[#500]
=== Setting up the item export

This section explains how to transfer your items to Check24. The item export for Check24 is carried out by the elastic export. The data format Check24DE is used for this. Therefore, the plugins *ElasticExport* and *ElasticExportCheck24DE* have to be installed. First, create the data format Check24DE. Then transfer the URL to Check24.

[.instruction]
Setting up the item export:

. Go to *Data » Elastic export*.
. Click on *New export*.
. Carry out the settings. Pay attention to the explanations given in <<settings-item-export-check24>>.
. Carry out further settings for item filters and format settings. Pay attention to the information given in table 5 on the <<data/export-import/exporting-data#60, Exporting data page of the manual>>. +
  *_Tip:_* In order to only export items to Check24 which are activated for Check24 and available for the market in the item’s *Availability* tab, select the item filter *Active* and the item filter *Markets » Check24*.
. *Save* the settings. +
→ The export format is given an ID and it appears in the overview within the *Exports* tab.

[[settings-item-export-check24]]
.Settings for the item export
[cols="1,3"]
|====
|Setting |Explanation

2+|Settings

|*Name*
|Enter a name. The export format is listed by this name in the overview within the *Exports* tab.

|*Type*
|Select the type from the drop-down list. Currently, *Item* is the only available option. Further options will be available soon.

|*Format*
|Select the format *Check24DE* from the drop-down list.

|*Limit*
|Enter a number. If you want to transfer more than 10,000 data records to Check24, then the output file will not be generated again for another 24 hours. This is to save resources.

|*Provisioning*
|Select *URL*.

|*Token, +
URL*
|If you have selected the option *URL* under *Provisioning*, then click on *Generate token*. The token is entered automatically. The URL is entered automatically if the token has been generated under *Token*. Give this URL to Check24.de in order to export the items.
|====

[IMPORTANT]
.Export information
====
If you change one or more settings, then you will have to transfer the new link to Check24.

A maximum of 4000 items are exported at once. If you export more items, then a second export is automatically carried out. To display the second export process, set the parameter *&amp;Page* = in the export link to *2*.

Technical data is transferred to Check24 in the last column of the export file.
====

[#600]
=== Defining a sales price

Proceed as described below to define a sales price for the order referrer Check24. This price is shown on Check24.

[.instruction]
Defining a sales price for Check24:

. Open the menu *System » System settings » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *Check24*.
. *Save* the settings.

[#950]
== Order import

After the order import, the order is set to *Status [5] Cleared for shipping*. The invoice address is always Check24. The customer's address is the delivery address.

[#1000]
== Viewing the API log

The menu *Data » API log » Tab: API log* contains a history of processes that run via the Check24 interface. The format *Check24OrderImportAdapter* is available for Check24.

[.instruction]
Viewing the API log:

.  Go to *Data » API log » Tab: API log*.
.  Select the format *Check24OrderImportAdapter* from the drop-down list *Process*.
.  Select a date if you only want to see entries for a specific day.
.  Select the number of results per page.
.  Click on *Search* to display the results.
