= Etsy
:lang: en
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: Etsy, market, marketplace, Multi-Channel, marketplace Etsy, setting up Etsy, Etsy setup, Etsy marketplace, Multichannel, Multi-Channel Etsy, Multichannel Etsy, multi channel Etsy, dawanda, Etsy-plugin, Etsy plugin, Etzy
:description: Multi-Channel in plentymarkets: Set up the interface to the market Etsy in your plentymarkets system.
:position: 60
:url: markets/etsy
:id: J8WLEBE

link:https://www.etsy.com/[Etsy^] is an American online market focused on handmade and vintage items.

[discrete]
===== Note

The term “Etsy” is a trademark of Etsy, Inc. This application uses the Etsy API but is not endorsed or certified by Etsy, Inc.

[IMPORTANT]
.Installing the Etsy plugin
====
The interface to Etsy is integrated via a link:https://marketplace.plentymarkets.com/en/plugins/sales/marktplaetze/etsy_4689[plugin^]. Download the Etsy plugin in the plentyMarketplace in order to use it.
====

[#100]
== Registering with Etsy

In order to set up Etsy in your plentymarkets system, you have to register as a Etsy seller first.

[#200]
== Installing the Etsy plugin in plentymarkets

After buying the Etsy plugin in the plentyMarketplace, install the market in the *Plugins » Plugin overview* menu. Select the filter *Not installed* or *All* to display plugins that have not yet been installed. For further information about downloading and installing plugins, see <<plugins/adding-plugins-system#marketplace-plugins, Adding plugins to the system>>.

[#250]
=== Activating the interface

First, the interface has to be activated in the *Setup » Markets » Etsy » Authentication* menu. This is to grant plentymarkets access to your Etsy account.

[.instruction]
Activating the interface:

. Go to *Setup » Markets » Etsy » Authentication*.
. Click on the globe icon (icon:globe[role="green"]). +
→ A new window opens and you are forwarded to Etsy.
. Enter your Etsy access data.
. Click on *Allow access*. +
→ The interface to Etsy is activated and you can carry out further settings.


[#300]
=== Setting up Etsy in plentymarkets

[IMPORTANT]
.Pay attention to the Renewal options at Etsy
====
Prior to setting up Etsy in plentymarkets, you have to set the setting *Renewal options* to *Manual* in the *Shop-Manager » Listings »* _Open listing_ menu at Etsy. Otherwise, the Etsy plugin will not work correctly.
====

Go to *Setup » Markets » Etsy » Settings* to activate the data exchange.

[.instruction]
Activating the data exchange:

. Go to *Setup » Markets » Etsy » Settings*.
. In the *Processes* area, activate the *Item export*, *Stock update*, and *Order import*.
. *Save* (icon:save[role="green"]) the settings.

[discrete]
===== Setting up export languages

In the *Export languages* area, you carry out settings for export languages. The *Shop language* is exported by default. Other languages are used for translations of your offers.

[.instruction]
Setting up export languages:

. Go to *Setup » Markets » Etsy » Settings*.
. Select the languages that your offers should be translated into. Available languages are *English*, *German*, and *French*. +
*_Note:_* The defined *Shop language* is exported by default.
. *Save* (icon:save[role="green"]) the settings.


[#400]
== Activating the order referrer

:market: Etsy
:referrer: Etsy
:referrer-option: pass:quotes[option *Etsy*]

include::_textblocks/instructions/activate-referrer.adoc[]

[#500]
== Setting the variation availability

:market-availability: Etsy
:option-availability: Etsy

include::_textblocks/instructions/variation-availability.adoc[]

// Web API NOT required!

[#550]
== Saving existing Etsy listing IDs

If you already sell a variation on Etsy, save the Etsy listing ID as an SKU for the referrer *Etsy*. By doing so, variations will be assigned to the variations already listed on Etsy during the item export. This is to prevent overselling. +

[.instruction]
Saving an Etsy listing-ID:

. Go to *Item » Edit item »* _Open item_ *» Tab: Variation ID » Tab: Settings*.
. Click on the *Availability* tab.
. In the *SKU* area, click on *Add* (icon:plus-square[role="green"]). +
→ The *New SKU* window opens.
. Select the referrer *Etsy*.
. Enter the *SKU* in the following format: +
  _[Etsy listing ID]_-_[plentymarkets variation ID]_ +
  *_Example:_* 708093072-3467
. Enter the *Parent SKU* in the following format: +
  _[Etsy Listing-ID]_ +
  *_Example:_* 708093072
. Click on *Add* (icon:plus-square[role="green"]). +
→ The SKU is saved and displayed.

[#600]
== Defining a sales price

:referrer-price: Etsy

include::_textblocks/instructions/define-sales-price.adoc[]

[#900]
== Setting up the item export

Item data is exported to Etsy via catalogues. The marketplace format *Listing - Etsy* creates a catalogue for exporting data for all Etsy product categories.

[#700]
=== Creating a catalogue

Item data is exported to Etsy via catalogue using the marketplace format *Listing - Etsy*. Create a catalogue in the *Data » Catalogue* menu to export your items to Etsy. Link the Etsy data fields with item data saved in plentymarkets in the marketplace format afterwards. The catalogue data is automatically exported to Etsy once a day if you have activated the *Item export* in the *Setup » Markets » Etsy » Settings* menu. Is this your first time working with catalogues? Then read up on the basic principle of <<en/data/exporting-data/managing-catalogues, catalogues first>>.

TIP: You can create only one catalogue for Etsy. Multiple catalogues are currently not supported for Etsy.

:catalogue-template-name: Listing - Etsy

include::_textblocks/instructions/creating-catalogues.adoc[]

[#map-data-fields]
=== Mapping data fields in the catalogue

[IMPORTANT]
.Notes for the Etsy marketplace format
====
The *Shop sections* data field in the *Listing - Etsy* template provides all shop sections that you created at Etsy. The shop sections can be selected from the drop-down list and can be linked to data saved in plentymarkets.
====

include::_textblocks/instructions/catalogue-map-data-fields.adoc[]

[#800]
== Updating Etsy categories

In order to update Etsy categories in plentymarkets, delete your credentials in the *Setup » Markets » Etsy » Authentication* menu and add them again.


[.instruction]
Updating Etsy categories:

. Go to *Setup » Markets » Etsy » Authentication*.
. Click on *Delete* to delete the credentials.
. Click on the globe icon (icon:globe[role="green"]) to add new credentials. +
→ You are forwarded to Etsy.
. Click on *Allow access* at Etsy. +
→ New credentials are created and saved in plentymarkets. +
→ The Etsy categories are updated.


[#900]
== Transferring legal information

In order to transfer legal information to Etsy, you have to save the information for each language you use for Etsy. The legal information is then added to the item description.

[.instruction]
Saving legal information:

. Go to *Setup » Markets » Etsy » Legal information*. +
→ The window *Legal information* opens.
. Select the language in which you want to save legal information.
. Enter the text.
. *Save* (icon:save[role="green"]) the settings.


[#1000]
== Automatically sending payment confirmations

Set up an <<automation/event-procedures#, event procedure>> to automatically send payment confirmations to Etsy when incoming payment is booked.

:table-event-procedure: <<#etsy-payment-confirmation>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[etsy-payment-confirmation]]
.Automatically sending payment confirmations to Etsy
[cols="1,3,3"]
|====
|Setting | Option | Selection

| *Event*
| *Payment: Complete*
|

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Referrer*
| *Etsy*

| *Procedure*
| *Plugin > Send payment confirmation to Etsy*
|
|====


[#1100]
== Automatically sending shipping confirmations

Set up an <<automation/event-procedures#, event procedure>> to automatically send shipping confirmations to Etsy when the outgoing items are booked.

:table-event-procedure: <<#etsy-shipping-confirmation>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[etsy-shipping-confirmation]]
.Automatically sending shipping confirmations to Etsy
[cols="1,3,3"]
|====
|Setting | Option | Selection

| *Event*
| *Order change: Outgoing items booked*
|

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Referrer*
| *Etsy*

| *Procedure*
| *Plugin > Send shipping confirmation to Etsy*
|
|====


[#1200]
== Assigning user rights

Users with *Back end* access need rights to use the Etsy plugin. Open the *Setup » Settings » User » Rights » User* menu to assign rights.

[.instruction]
Assigning user rights for back end users:

. Go to *Setup » Settings » User » Rights » User*.
. Use the search function and open the account that you want to edit.
. Expand the *Authorisation: Markets* menu.
. Select the option *Credentials*.
. *Save* (icon:save[role="green"]) the settings.


[#1300]
== License

:license-link: https://github.com/plentymarkets/plugin-etsy/blob/master/LICENSE.md

include::_textblocks/explanations/plugin-license.adoc[]
