= Setting up grosshandel.eu
:lang: en
include::{includedir}/_header.adoc[]
:keywords: grosshandel.eu, Market, Marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market grosshandel.eu in your plentymarkets system.
:position: 90
:url: markets/grosshandel

link:http://www.grosshandel.eu/[grosshandel.eu^] is a pure B2B portal, which means that both sellers and buyers have to be in possession of a valid trading licence. You can use this market to buy and sell consumer goods and brand-name items (source: grosshandel.eu).

[#100]
== Registering with grosshandel.eu

You have to link:http://www.grosshandel.eu/registrierung-verkaeufer.php[register^] in the grosshandel.eu seller portal before you can set up grosshandel.eu in your plentymarkets system.

[#200]
== Creating a user account

Your plentymarkets system is connected to grosshandel.eu via the SOAP API. In order to gain access, the market requires its own user account with access rights to the API in your plentymarkets system. Go to *System » System settings » Settings » User » Accounts* and create a new user account for grosshandel.eu with the user class *API*. Furthermore, activate the call *GetCategoryMappingForMarket*. This call ensures that the market will later be able to retrieve your category links.

[.instruction]
Creating a user account for grosshandel.eu:

. Go to *System » System settings » Settings » User » Accounts*.
. Click on *New*. +
→ The *Create new user* window opens.
. Enter the data.
. Select the user class *API*.
. *Save* the settings. +
→ The user is created.
. Select the user from the list. +
→ An editing window opens.
. Click on the tab *Right » API*.
. Expand the *Item* area.
. Activate the *GetCategoryMappingForMarket* call.
. *Save* the settings.

For further information refer to the <<basics/admin-tasks/manage-users#, Managing user accounts>> page of the manual.

[#300]
== Procuring data

grosshandel.eu needs to have the following data from you in order to connect to your plentymarkets system:

* The URL for the SOAP API WSDL.  +
→ This URL can be found in the *System » System settings » Settings » API » Data* menu under *SOAP WSDL*.
* The user name and password for the user account that you created for grosshandel.eu
* Your login details for the grosshandel.eu seller portal.

[#350]
== Activating an order referrer

In order to link items, properties etc. with grosshandel.eu, you have to activate the order referrer grosshandel.eu in the menu *System » System settings » Orders » Order referrer*.

[.instruction]
Activating the order referrer for grosshandel.eu:

. Go to *System » System settings » Orders » Order referrer*.
. Place a check mark next to *grosshandel.eu*.
. *Save* the settings.

[#400]
== Setting the item availability

Items have to be available for grosshandel.eu. This is done in the *Availability* tab of an item within the *Item » Edit item » Tab: Variation ID* menu.

[.instruction]
Setting the item availability for grosshandel.eu:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Place a check mark next to the option *grosshandel.eu*.
. Place a check mark next to the option *Web API*.
. Click on *Add*. +
→ The market is added.
. *Save* the settings. +
→ The item is available on grosshandel.eu.

The availability for variations can be edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

[#450]
==  Defining SKU manually

Add SKUs manually for specific referrers in the *Item » Edit item » Open item » Tab: Variation ID » Tab: Availability* menu if needed.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
.  Click on the *Availability* tab.
.  Click on *Add* in the section *SKU*. +
→ The window *New SKU* is displayed.
.  Select the referrer *grosshandel.eu*.
.  Enter the SKU.
.  Click on *Add*. +
→ The SKU is saved and displayed.

[#500]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer grosshandel.eu. This price is displayed on grosshandel.eu.

[.instruction]
Defining a sales price for grosshandel.eu:

. Open the menu *System » System settings » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *grosshandel.eu*.
. *Save* the settings.

[#600]
== Linking categories

Link your store categories to the grosshandel.eu categories in order to display your items in these categories. Further items from the linked categories are assigned automatically.

[.instruction]
Linking categories:

. Go to *System » System settings » Markets » grosshandel.eu*.
. Expand the category which you want to link to a grosshandel.eu category.
. Select a main category for grosshandel.eu from the drop-down list. +
→ A window with subcategories opens.
. Select the appropriate grosshandel.eu category from the subcategories that appear. +
→ Once the lowest category level has been reached, the category path will be displayed in the field *Category*.
. Click on *Accept*. +
→ The category window is closed.
. *Save* the settings.

[IMPORTANT]
.Link to the lowest category level
====
Always select a path to the lowest level. Otherwise, the item will not be linked.
====

[#700]
== Linking multiple subcategories

Use the option *Apply the same selection to the sub-categories* to apply the same grosshandel.eu category path for all of the subcategories that are listed within a category. This is useful if you want to use the same link for the subcategories. If needed, you can use the drop-down list to manually change individual subcategories.

[.instruction]
Linking multiple subcategories:

. Go to *System » System settings » Markets » grosshandel.eu*.
. Expand the category which you want to link.
. Select a main category for grosshandel.eu from the drop-down list in the line *Apply the same selection to the sub-categories*. +
→ A window with subcategories opens.
. Select the appropriate category path from the subcategories that appear. +
→ Once the lowest category level has been reached, the category path is displayed in the field *Category*.
. Click on *Accept*. +
→ The category window is closed.
. Click on *Select all* in the line *Apply the same selection to the subcategories*.
. Click on *Reload*. +
→ The category path is applied to all of the subcategories.
. *Save* the settings.
