= Kauflux
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Kauflux, Market, Marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market Kauflux in your plentymarkets system.
:position: 120
:url: markets/kauflux

link:http://www.kauflux.de/[Kauflux.de^] is an open marketplace with independent providers from various areas. Kauflux.de markets your items and services and enables direct contact to purchasers.

[#100]
==  Registering with Kauflux

You have to register with link:http://www.kauflux.de/konto[Kauflux^] before you can set up Kauflux in your plentymarkets system.

[#200]
==  Setting up Kauflux in plentymarkets

Carry out the following basic settings in order to transfer item data to Kauflux.

[.instruction]
Setting up Kauflux in plentymarkets:

. Go to *System » System settings » Markets » Kauflux » Settings*.
. Carry out the settings. Pay attention to the explanations given in table 1.
. *Save* the settings.

.Basic settings for Kauflux
[cols="1,3"]
|====
|Setting |Explanation

|*Exchange period*
|Enter the exchange period for the items. The exchange period is given in days. If you want to forbid items from being exchanged, then enter the value *0*.

|*Order referrer*
|Select the order referrer for Kauflux.

|*Type of stock management*
|Select whether you would like to transfer your stock and if so, whether you would like it to be *publicly* visible or not.

|*API URL for the order import*
|Kauflux uses this link to transfer orders to plentymarkets. This link is needed for importing orders from Kauflux and not for creating the item catalogue. The item catalogue is created with the price comparison portals. This is done in the *System » System settings » Markets » Price analysis » Exports* menu. Further information in German can be found on link:http://www.kauflux.de/shop-anmelden/automatischer-auftragsdatenexport[Kauflux^].
|====

[#250]
== Activating an order referrer

In order to link items, properties etc. with Kauflux, you have to activate the order referrer Kauflux in the menu *System » System settings » Orders » Order referrer*.

[.instruction]
Activating the order referrer for Kauflux:

. Go to *System » System settings » Orders » Order referrer*.
. Place a check mark next to the option *Kauflux*.
. *Save* the settings.

[#300]
== Setting the item availability

Items have to be available for Kauflux. This is done in the *Availability* tab of an item within the <<en/item/managing-items#40, Item » Edit item » Tab: Variation ID>> menu.

[.instruction]
Setting the item availability for Kauflux:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Activate the option *Kauflux*.
. Click on *Add*. +
→ The market is added.
. *Save* the settings. +
→ The item is available on Kauflux.

The availability for variations can be individually edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

[#350]
==  Defining SKU manually

Add SKUs manually for specific referrers in the menu <<en/item/managing-items#170, Item » Edit item » Open item » Tab: Variation ID » Tab: Availability>> if needed.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
.  Click on the *Availability* tab.
.  Click on *Add* in the section *SKU*. +
→ The window *New SKU* is displayed.
.  Select the *Kauflux* referrer.
.  Enter the SKU.
.  Click on *Add*. +
→ The SKU is saved and displayed.

[#400]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Kauflux. This price is displayed on Kauflux.

[.instruction]
Defining a sales price for Kauflux:

. Open the menu *System » System settings » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *Kauflux*.
. *Save* the settings.

[#500]
== Linking properties

In order to be able to use properties for the Kauflux market, these have to be linked with Kauflux in the corresponding property's settings.

[.instruction]
Linking properties:

. Go to *System » System settings » Item » Properties*.
. Expand a property.
. Activate the option *Kauflux*.
. *Save* the settings.

[#600]
== Linking categories

Go to *System » System settings » Markets » Kauflux » Category link* to link your online store categories with the categories on Kauflux. You need the Kauflux CSV file for setting up a category link. This file contains the *category IDs* for this market. You can download this link:http://support.expeedo.de/f/kl/kauflux-Kategorien.xls[*file*] from the sellers area on the Kauflux website. In the next steps, export a list of categories in your online store, link these categories and then import the category links.

[.instruction]
Exporting links:

. Go to *System » System settings » Markets » Kauflux » Category link*.
. Click on *Export link*. +
*→* This generates a CSV file with your online store categories.
. Open the online store CSV file.

[.instruction]
Entering category Ids:

. Open the Kauflux CSV file.
. For each category in your online store, search for the corresponding *category IDs* in the Kauflux CSV file.
. Enter the category IDs from the Kauflux CSV file into the *KaufluxCat* column in the online store CSV file.
. Save the online store CSV file on your computer's hard drive.

[.instruction]
Importing links:

. Go to *System » System settings » Markets » Kauflux » Category link*.
. Click on *Select file* in the line *File*.
. Select the online store CSV file that you have saved on your computer's hard drive.
. Click on *Open*.
. *Save* the settings. +
→ The links are imported and displayed in the *Links* area.

[#700]
== Exporting items

After you have set up Kauflux, you can export your items under *System » System settings » Markets » Price analysis » Exports*.

For an automatic item export, you have to copy the complete URL and save it with Kauflux. The requirements for this are that you have carried out at least one item export manually and that you have assigned the individual fields in Kauflux. Additionally, the automatic item export from Kauflux has to be activated.

[#800]
== Exporting variations

During the export, variations are exported as additional CSV fields. If you would like to import this CSV or ZIP file into Kauflux, then you will be asked to map the categories.

[IMPORTANT]
.Example
====
The variation fields *colour*, *size* and *length* are displayed in the mapping. For all variation fields, you have to select *GroupParam* as the mapping field so that these fields can be saved as variations on Kauflux.de. The field *GroupID* serves exclusively to identify the items that belong together in a group.
====

[#900]
== Importing orders

Your orders from Kauflux can be imported into your system automatically. To do so, you have to save the API URL on Kauflux. This URL is found under *System » System settings » Markets » Kauflux » Settings*. After completing this step, orders are automatically imported into your system and displayed in the menu *Orders » Edit orders*.

[#1000]
== Sending an email when orders are imported

It is possible to send automatic emails when orders are imported into plentymarkets. Go to *System » System settings » Client » Select client » Email » Templates* to create and activate an email template for Kauflux.

[.instruction]
Sending an email when orders are imported:

. Go to *System » System settings » Client » Select client » Email » Automatic*.
. Select the previously created email template for the option *New order from Kauflux*.
. *Save* the settings.

Click on *Edit email template* to access the menu *System » System settings » Client » Select client » Email » Templates* and edit the email template.
