= limango
:lang: en
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: limango, market, marketplace, limango.de, setting up limango, limango market, limango marketplace, Multi-Channel, Multichannel, Multi-Channel limango, Multichannel limango, Multi Channel limango
:description: Multi-Channel in plentymarkets: Set up the interface to the market limango in your plentymarkets system.
:position: 0
:url: markets/limango
:id: ZG3WRBH

[IMPORTANT]
.Download the limango plugin
====
You need a plugin to link plentymarkets to limango. Visit the link:https://marketplace.plentymarkets.com/en/limango_7023[plentyMarketplace^]{nbsp}icon:external-link[] to download the limango plugin.
====

[#100]
== About limango

limango, a member of the Otto Group, is the number one platform for young families. Besides its private Shopping Club, limango also operates the link:https://www.limango.de/shop[online shop^]{nbsp}icon:external-link[] which is accessible without registration. Since the marketplace was launched in 2017, end users also take advantage of a broad and permanent product range that is now provided by more than 300 merchants.

[#150]
== Becoming a limango partner

Join the leading platform for family shopping and click ink:https://entdecke.limango.de/marktplatz-partnerprogramm[here^]{nbsp}icon:external-link[] for more information on the limango marketplace and their partner program and to send your registration request (please note: information is only available in German).

Alternatively, you can also contact our team of partner managers by sending an email to marketplace@limango.de. A partner manager will get in touch with you soon and will work with you to evaluate the potential on link:https://www.limango.de[limango.de^]{nbsp}icon:external-link[] and talk about your next steps.

After registering, you will receive login details from limango. You need these login details to set up the limango plugin in plentymarkets.

[#200]
== Overview of automatic data exchange with limango

After installing and setting up the plugin, the automatic processes described in <<#data-exchange-limango>> become available:

[[data-exchange-limango]]
.Frequency of data exchange
[cols="1,3a"]
|====
|Data |Interval

2+| Item data

| Item export
| once a day

| Stock synchronisation
| Hourly +
*_Tip:_* For technical reasons, shorter stock update intervals are not possible. Set a <<#300, stock buffer>> to prevent overselling.

| Price synchronisation
| Hourly

2+| Order data

| Order import
| Every 15 minutes +
*_Note:_* Customers make their payments to limango. As such, all orders are imported with the status *[5] Paid*.
|====

[#220]
== Workflow of a limango order

* Your products are listed in the limango marketplace. The name of your company is shown with your products.
* Customers place an order on limango.
* Customers make their payments to limango.
* → The order is imported to plentymarkets. +
*_Note:_* Because customers make their payments to limango, orders are imported with the status *[5] Paid*.
* When you receive the order, you ship the products (drop shipping).

[#170]
== Installing the limango plugin

To connect to limango in plentymarkets, install the link:https://marketplace.plentymarkets.com/en/limango_7023[limango plugin^] in your plentymarkets system. You can download the plugin in the link:https://marketplace.plentymarkets.com/en[plentyMarketplace^]{nbsp}icon:external-link[].

[.collapseBox]
.Not sure how to install the limango plugin?
--
:plugin: limango

include::../../../plugins/_textblocks/instructions/plugin-installieren-en_gb.adoc[]
--

[#300]
== Setting up limango

After you have installed the limango plugin, set up the market in the plugin settings. Keep the login details at hand that you received from limango.

[.instruction]
Setting up limango:

. Go to *Plugins » Plugin set overview*. +
→ The list of plugin sets is shown.
. Click on the plugin set in which you have installed the limango plugin. +
→ The plugin set opens.
. Click on the plugin *limango*. +
→ The plugin settings open.
. Carry out the settings. Pay attention to the information given in <<#limango-setup>>.
. *Save* (icon:save[role="green"]) the settings in each area in which you made changes.


[[limango-setup]]
.Setting up limango
[cols="1,3a"]
|====
|Setting |Explanation

2+| *SFTP credentials*

| *Host*
| Enter `ftp-partner.limango.de`.

| *Port*
| Enter port `22`.

| *User name* +
*Password*
| You will receive these credentials from limango.

2+| *Stock export*

| *Stock buffer*
| The stock of all warehouses is exported to limango. Enter a whole number to reduce the exported stock information by the entered amount. +
*_Note:_* Stock information is exported to limango once per hour. For technical reasons, shorter stock update intervals are not possible. Use the stock buffer to prevent overselling.

2+| *Information*

| *Order referrer ID created by plugin*
| The ID of the order referrer *limango* that is created automatically when you install the plugin. The ID is filled in automatically.

| *Status of last price export*
a| * *1* = The prices were exported to limango. You can check the last time the export was successful *Timestamp of last successful price export*.
* *2* = The last price export failed.

| *Time of last successful price export*
| The timestamp of the last successful price export.

2+| *Order status*

| *Order status for orders with items that cannot be linked to items in plentymarkets (>= 5)*
| Enter an order status of 5 or higher. This status is assigned to orders that contain one or more items that no longer exist in plentymarkets. For example, this can happen if a customer orders an item on limango that was deleted in plentymarkets after the last item export to limango.

| *Order status for orders with no shipping service provider (>= 7)*
| Enter an order status of 7 or higher. This status is assigned to orders if the shipping service provider in the order is not linked to a shipping service provider in plentymarkets.

2+| *Shipping service provider*

| *DHL*; +
*Hermes*; +
*UPS* +
etc.
| For each shipping service provider that you want to offer for limango orders, enter the ID of the shipping service provider in plentymarkets. +
*_Tip:_* Go to *Setup » Orders » Shipping » Settings » Tab: Shipping service provider* to find the ID of your shipping service providers in the column *ID*.
|====

[#600]
== Activating the order referrer

:market: limango
:referrer: limango
:referrer-option: pass:quotes[option *limango*]

include::_textblocks/instructions/activate-referrer.adoc[]

[#500]
== Defining a sales price

:referrer-price: limango

include::_textblocks/instructions/define-sales-price.adoc[]

[#550]
== Activating the referrer in shipping profiles

:referrer: limango

include::_textblocks/instructions/shipping-profile-activate.adoc[]

[#900]
== Setting up the item export

Item data is exported to limango via a catalogue format. Go to *Data » Catalogues* to create catalogues. Is this your first time working with catalogues? Then read up on the <<en/data/exporting-data/managing-catalogues, principle of catalogues first>>.

To export your item data to limango, you need to create a catalogue. Link the limango data fields with the item data saved in plentymarkets in the marketplace format afterwards. After you activate the catalogue, the catalogue data is automatically exported to limango in regular intervals.

[#901]
=== Notes on the limango item data structure

The structure of limango item data differs from the structure in plentymarkets. The limango item data is categorised into three levels:

. *Product group:* A product in all its different versions
. *Product:* A colour version of the product
. *Variation:* The size / EAN / SKU

If the product is only available in a single version, then the product group is equivalent to the variant.

[IMPORTANT]
.Use the parent-SKU
====
Do you sell products in different colours but manage these different colours in separate items? The parent SKU allows you to link these separate items. Parent SKUs can be saved for both items and individual variations. The manual maintenance of SKUs enables you to assign the Parent SKU of entirely different item variations to variations of an item.

* You can assign the Parent SKU of a variation which belongs to an entirely different item five times to an item with five variations. These variations are listed on limango as variations of the item with the Parent SKU they are assigned to. +
* If one variation has a different Parent SKU than the remaining variations of an item, then two different items are listed on limango. You only have to maintain one item in your plentymarkets system.
====

[#902]
=== Creating a catalogue

Item data is exported to limango via catalogue using the marketplace format *limango*. Create a catalogue in the *Data » Catalogue* menu to export your items to limango. Link the limango data fields with item data saved in plentymarkets in the marketplace format afterwards. Is this your first time working with catalogues? Then read up on the <<en/data/exporting-data/managing-catalogues, principle of catalogues first>>.

TIP: You can create only one catalogue for limango. Multiple catalogues are currently not supported for limango.

:catalogue-template-name: limango
:catalogue-plugin:

include::_textblocks/instructions/creating-catalogues.adoc[]

[#903]
=== Mapping catalogue fields

After you have created a catalogue, map the market's data fields to item data saved in plentymarkets. This chapter describes how you map data fields and what particularities apply for item exports to limango. In addition, we provide recommendations for suitable mappings. This information is structured as follows:

* <<#907, Mapping data fields in the catalogue>>
* <<#905, Notes on mapping data fields>>
* <<#906, Recommendations for limango data field mapping>>

[#907]
==== Mapping data fields in the catalogue

Now, map the limango data fields to the item data saved in plentymarkets. Take note of the information regarding specific mappings and recommendations in this chapter.

include::_textblocks/instructions/catalogue-map-data-fields.adoc[]

[#905]
==== Notes on mapping data fields

Every market structures item data differently. As such, there are some particularities for each market when mapping data fields. <<#catalogue-limango-mappings>> contains mapping information for important data fields for limango.

[[catalogue-limango-mappings]]
.Notes on mapping data fields
[cols="1,3a"]
|====
| Marketplace data field | plentymarkets data field

| *Description*
a| If you want to sell shoes on the market, all information regarding the material of your products must be exported to limango using the data field *Description*. To do this, you combine two plentymarkets data fields and export them as one filed to limango.

First, decide how you want to manage material information for your items. There are two ways to manage material information for limango:

* Enter the material information in the data field *Technical data* of the item.

_or_

* Create a property of the type *Text*. Link this property to the main variation of the item and manage the material information in this property.

Now, map the plentymarkets data field that you want in the catalogue:

. Map the plentymarkets data field that contains the item description to the marketplace data field *Description*.
. To the right of this data field, click on *Add data field* (icon:link[rotate=90]).
. Map the plentymarkets data field that contains the material information. +
*_Tip:_* This is either the field *Technical data* or the property that you created for the material information.
. To the right of the column, click on *Settings* (icon:cog[]).
. From the drop-down list *Separator*, select the option *Space*.

| Measurements
(*Length*; +
*Width*; +
*Height*; +
*Volume*; +
*Diameter*; +
*Weight*
etc.)
a| Measurements must be exported to limango with the format *[numeric value];[unit]*. Due to the limango product structure, the normal plentymarkets data fields for measurements cannot be mapped. Instead, create two properties:

* One property of the type *Decimal number* for the numerical value.
* One property of the type *Selection* for the unit.

Combine these two properties, separated by a semicolon.

[.collapseBox]
.*_Example:_* Exporting the length to limango
--
. Create a property of the type *Decimal number* with the name *Length*.
. Create a property of the type *Selection* with the name *Length unit*.
. Add the units you need to the property *Length unit* as property values.
. Open the limango catalogue.
. Map the marketplace data field *Length* to the plentymarkets property *Length*.
. To the right of this data field, click on *Add data field* (icon:link[rotate=90]).
. Map the property *Length unit*. +
*_Tip:_* If you are sure that you only need one unit for all your variations, you can also export the unit by entering it as an own value. To do so, instead of mapping the property *Length unit*, map the field *Own value* and enter the unit in the field that opens.
. To the right of the column, click on *Settings* (icon:cog[]).
. From the drop-down list *Separator*, select the option *Semicolon*.
--

[.collapseBox]
.*_Example:_* Exporting the volume to limango
--
. Create a property of the type *Decimal number* with the name *Volume*.
. Create a property of the type *Selection* with the name *Volume unit*.
. Add the units you need to the property *Volume unit* as property values. +
*_Note:_* Only the units l (for litres) and ml (for millilitres) can be exported.
. Open the limango catalogue.
. Map the marketplace data field *Volume* to the plentymarkets property *Volume*.
. To the right of this data field, click on *Add data field* (icon:link[rotate=90]).
. Map the property *Volume unit*. +
*_Tip:_* If you are sure that you only need one unit for all your variations, you can also export the unit by entering it as an own value. To do so, instead of mapping the property *Volume unit*, map the field *Own value* and enter the unit in the field that opens.
. To the right of the column, click on *Settings* (icon:cog[]).
. From the drop-down list *Separator*, select the option *Semicolon*.
--

| Data fields under Material composition
a| Material information is exported to limango using a property of the type *Short text*. You need one property for each marketplace data field. This property is used to save all components of the material mix for a main variation.
Enter the material composition in the following format:

* *{"material1": "percentage","material2": "percentage","material3": "percentage"}* +
*_Example:_* *{"baumwolle": "90","elastan": "10"}*

Specify the individual materials in descending order based on the percentage value. As such, the first material is the one with the highest percentage value, the last one that with the lowest percentage value. The sum of all percentages must be 100. You can specify as many materials as you need.

[.collapseBox]
.*_Example:_* Exporting material information for a blazer to limango
--
The following example shows you how to save material information for a blazer for the limango export.

[.instruction]
Mapping outer fabric and saving material mix for a variation:

. Create a property of the type *Short text* with the name *Material 1*.
. Map the marketplace data field *Material 1* to the plentymarkets property *Material 1*.
. Link the property *Material 1* to the main variation of the item.
. Our blazer is made of 65% polyester, 32% rayon and 3% elastane. Enter the following into the text field of the property:
  * {"polyester": "65","viskose": "32","elastan": "3"}
. Save the settings.

[.instruction]
Mapping lining and saving material mix for a variation:

. Create a property of the type *Short text* with the name *Lining 1*.
. Map the marketplace data field *Lining 1* to the plentymarkets property *Lining 1*.
. Link the property *Lining 1* to the main variation of the item.
. The lining of the blazer is made of 100% rayon. Enter the following into the text field of the property:
  *
. Save the settings.
--
|====

[#906]
==== Recommendations for limango data field mapping

To help you with mapping your data fields for the limango catalogue, we have created a list of recommended data field mappings for limango. Note that these mappings are recommendations only. Depending on how you manage your item data, other mappings may be more appropriate than the recommendation given here.

[.collapseBox]
.List of recommended data field mappings for limango
--
include::_textblocks/explanations/limango-recommended-mappings.adoc[]
--

[#904]
=== Activating the catalogue

:interval: once a day during the night
:market: limango

include::_textblocks/instructions/catalogue-activation.adoc[]

[#750]
== Setting the variation availability

:market-availability: limango
:option-availability: limango

include::_textblocks/instructions/variation-availability.adoc[]

// Web API NOT required!

== Automatically notify limango about cancellations

Set up an <<automation/event-procedures#, event procedure>> to automatically notify limango of cancellations.

:table-event-procedure: <<#event-procedure-cancellation-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[event-procedure-cancellations-limango]]
.Event procedure to notify limango of cancellations
[cols="1,2,2"]
|===
| *Setting*
| *Option*
| *Selection*

| *Event*
| *Status change*
| Select an event, e.g. *[8] Cancelled*.

| *Filter*
| *Order > Referrer*
| *limango*

| *Procedure*
| *Plugins > limango: Send order cancellation to limango*
|
|===

[#1300]
== Setting up automatic shipping confirmations

limango expects each shipping confirmation to contain a tracking number. As such, set up an <<automation/event-procedures#, event procedure>> to automatically book outgoing items whe a tracking number is created.

:table-event-procedure: <<#event-procedure-tracking-number-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[event-procedure-tracking-number-limango]]
.Event procedure for booking outgoing items
[cols="1,2,2"]
|===
|Setting |Option |Selection

| *Event*
| *Package number*
|

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Referrer*
| *limango*

| *Procedure*
| *Order*
| *Book outgoing items*
|===

Now, set up an <<automation/event-procedures#, event procedure>> to automatically send a shipping confirmation to limango when outgoing items have been booked for an order.

:table-event-procedure: <<#event-procedure-shipping-confirmation-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[event-procedure-shipping-confirmation-limango]]
.Event procedure to send shipping confirmations to limango
[cols="1,2,2"]
|===
|Setting |Option |Selection

| *Event*
| *Status change*
| Select an event, for example [7] *Outgoing items booked*.

| *Filter 1*
| *Order > Order type*
| *Order*

| *Filter 2*
| *Order > Referrer*
| *limango*

| *Procedure*
| *Plugin*
| *Send shipping confirmation to limango*
|===

[#1000]
== Setting up return management

Now set up the processing of returns for limango.

[#1010]
=== Workflow for returns

The delivery note also functions as the return form. The workflow of limango returns is as follows:

. Customers return the items to you.
. You process the return in plentymarkets.
. You notify limango when you have received the items.
. limango reimburses the customer. +
*_Note:_* When you notify limango that the return is completed, limango triggers a credit note and the buyer receives a refund. As such, only notify limango about completing the return after you have received and checked the returned items.

[#1030]
=== Automatically notify limango about completed returns

Set up an <<automation/event-procedures#, event procedure>> to automatically inform limango when you have completed processing a return.

:table-event-procedure: <<#event-procedure-returns-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[event-procedure-return-limango]]
.Event procedure for automatically sending returns to limango
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *New return*
|

| *Filter 1*
| *Order > Order type*
| *Return*

| *Filter 2*
| *Order > Referrer*
| *limango*

| *Procedure*
| *Plugins > Send return notification to limango* +
*_Note:_* The procedure *Send return notification to limango* triggers a credit note. As such, a refund will be issued to the buyer. As such, make sure the event procedure is only triggered after you have received and checked the returned items.
|
|====

[#1600]
== Preparing delivery notes for limango

The limango letterhead return instructions provided by limango must be shown on every delivery note for limango orders.

* <<#16001, How to upload a PDF template for delivery notes>>
* <<#16001, How to enter return instructions for limango delivery notes>>

[#16001]
=== Uploading a PDF template for delivery notes

limango delivery notes must contain the limango logo. Proceed as describes below to upload a <<orders/order-documents#170, PDF template>> for delivery notes for limango to plentymarkets.

[.instruction]
Uploading a PDF template for delivery notes:

. Download the PDF template for limango delivery notes and save it on your computer:
  ** link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/Lieferschein_Vorlage_limango_Marktplatz.pdf[Download PDF template]
. Go to *Setup » Client » Select client » Locations » Location: Germany » Documents » Delivery note*.
. Click on the tab *PDF template*.
. Click on *Add template*. +
→ The editing window *Upload new PDF template* opens.
. From the drop-down list *Payment method*, select the option *Plugin: limango Payment*.
. *_Optional:_* Can’t find the payment method *Plugin: limango Payment* in the drop-down list?
  .. Go to *Setup » Orders » Settings*.
  .. For the setting *Show inactive plugin payment methods*, select the option *Yes*.
  .. *Save* (icon:save[role="green"]) the setting.
. In the drop-down list *Language*, select the option *de*.
. In the line *Template*, click on *Choose template file*.
. Select the PDF template for limango delivery notes.
. Click on *Upload template* (icon:save[role="green"]). +
→ The template is uploaded.

[#16002]
=== Entering return information for limango delivery notes

limango specifies a text containing return instructions that needs to be shown on all limango delivery notes. Proceed as described below to enter these return instructions for limango delivery notes.

[.instruction]
Entering return information for limango delivery notes:

. Expand the "Text: Return instructions for limango delivery notes" below this description.
. Copy the text to the clipboard.
. Go to *Setup » Client » Standard » Locations » Germany » Documents » Invoice » Tab: Template*.
. Scroll down to the area *Optional elements below stock unit table*, to the setting *Payment instruction*.
. Find a field that does not contain any payment instructions.
. From the drop-down list *Payment method* of this field, select the option *Plugin: limango Payment*.
. Copy the limango return instructions to the field.
. Replace the two placeholders "xxx" with the name of your company.
. *Save* (icon:save[role="green"]) the settings.

[#16003]
[.collapseBox]
.Text: return instructions for limango delivery notes
--
include::_textblocks/explanations/limango-delivery-note-text.adoc[]
--


[#1100]
== Troubleshooting: Viewing log entries

Your variations were not exported to limango? No variation data is exported if one or more variations do not meet the requirements of limango. As such, none of your variations will be exported to limango if one of your variations is invalid. To find the error, check the entries in the data log.

:market: limango
:identifier: limango

include::_textblocks/instructions/viewing_logs.adoc[]
