= myToys
:lang: en
include::{includedir}/_header.adoc[]
:author: team-plenty-channel
:keywords: myToys, myToys, mytoys, my toys, mytois, mirapodo, yomonda
:description: Multi-Channel in plentymarkets: Set up the interface to the market myToys in your plentymarkets system.
:position: 0
:url: markets/mytoys
:id: CQERJR4

:market: myToys
:mytoys:

With more than 9 million orders per year and over 4 million active customers, {market} is the leading platform for family shopping in Germany. {market} offers you sales opportunities for the 3 online shops {market}, mirapodo and yomonda by using only one technical integration.

[#150]
== Becoming a {market} partner

Click link:https://partnerprogramaccess.mytoys.de/Registrierung/[here^]{nbsp}icon:external-link[] to send your request for registration and learn more about the {market} market and the partner program.

Alternatively, you can also contact our team of partner managers by sending an email to mailto:partnerteam@mytoys.de. A partner manager will get in touch with you soon and will work with you to evaluate your potential on link:https://www.mytoys.de[mytoys.de^]{nbsp}icon:external-link[] and talk about your next steps.

After registering, you will receive login details from {market}. You need these login details to set up the {market} plugin in plentymarkets.

[#200]
== Overview of automatic data exchange

After installing and setting up the plugin, the automatic processes described in <<#data-exchange>> become available.

[[data-exchange]]
.Frequency of data exchange
[cols="1,3a"]
|====
|Data |Interval

2+| Item data

| Item export
| daily +
*_Note:_* Item data is exported once or twice a day. The export also triggers the price update for the variations included.

| Stock synchronisation
| every 15 minutes

2+| Order data

| Order import
| every 15 minutes +
*_Note:_* Customers make their payments to {market}. Thus, all orders are imported with the status *[5] Paid*. If no stock is available or no SKU is assigned, the order remains in the order status *[4] In preparation for shipping*.
|====

[#250]
== Workflow of a {market} order

* Your products are listed in the {market} marketplace.
* Customers place an order on {market}.
* Customers make their payments to {market}.
* → The order is imported to plentymarkets. +
*_Note:_* Because customers make their payments to {market}, orders are imported with the status *[5] Paid*.
* When you receive the order, you ship the products (drop shipping).

[#300]
== Installing a plugin

To connect to {market} in plentymarkets, install the link:https://marketplace.plentymarkets.com/en/mytoys_54776[myToys plugin^] in your plentymarkets system. You can download this and many other plugins in the link:https://marketplace.plentymarkets.com/en[plentyMarketplace^]{nbsp}icon:external-link[].

:plugin: myToys
include::_textblocks/instructions/plugin-installation.adoc[]

[#300]
== Setting up the market

After you have installed the plugin, set up the market in plentymarkets.

[#350]
=== Setting up the data exchange

Use the *{market} - Wizard* assistant in the *Setup » Assistants » Plugins » [select plugin set]* menu to set up the data exchange with {market} in plentymarkets. Keep the access data at hand that you received from {market}.

:menu-path: pass:quotes[*Setup » Assistants » Omni-Channel*]
:assistant-name: Base settings - myToys
:number-of-boxes: info box

include::_textblocks/instructions/assistant-basic-instructions.adoc[]

[.collapseBox]
.Options in the assistant
--
[[table-basic-settings-assistant]]
[width="100%"]
[cols="1,2a"]
|======
|Setting |Explanation

2+| Step *API settings*

| *Account number*; +
*User name*; +
*Password*
| You will receive these credentials from {market}.

2+| Step *SFTP settings*

| *Host*
| Enter `sftp.trade-server.net`.

| *Port*
| Enter port `22`.

| *User name*; +
*Password*
| You will receive these credentials from {market}.

2+| Step *Cron settings*

| *Order import cron*
| Activate to activate the order import. Orders are imported every 15 minutes.

| *Product export cron*
| Activate to activate the item export. +
*_Note:_* Item data is exported once or twice a day. The export also triggers the price update for the variations included.

| *Stock export cron*
| Activate to activate the stock export. Stock is exported every 15 minutes.

2+| Step *Shipping profile matching*

| Select one or more existing shipping profiles and map it to {market}.
| Which shipping service providers do you want to offer your customers for {market}?

Map all external shipping service providers that you want to allow for {market} orders to plentymarkets <<fulfilment/preparing-the-shipment#1000, shipping profiles>>:

. Click on icon:plus-square[role="green"].
. Select the plentymarkets shipping profile from the drop-down list *Internal shipping profile*.
. Select a shipping service provider from the drop-down list *Shipping service provider*.

2+| Step *Warehouse selection*

| Select the warehouses whose stock should be synchronised with {market}.
| Select which warehouses should be considered when exporting stock details to {market}.

Select one or several warehouses that contain the products that you want to sell on {market}:

. Click on icon:plus-square[role="green"].
. From the drop-down list *Warehouses*, select plentymarkets warehouses.

2+| Step *Client selection*

| Select the client that imported orders should be assigned to.
| Select the client that you want to use to sell on {market}. +
*_Note:_* If you want to sell your products on {market} using your default client, you do not need to select a client.
|====
--

[#400]
=== Activating an order referrer

:referrer: myToys
:referrer-option: pass:quotes[option *myToys*]

include::_textblocks/instructions/activate-referrer.adoc[]

[#450]
=== Defining a sales price

:referrer-price: myToys

include::_textblocks/instructions/define-sales-price.adoc[]

[#500]
=== Activating the referrer in shipping profiles

:referrer: myToys

include::_textblocks/instructions/shipping-profile-activate.adoc[]

[#prepare-variations]
== Activating variations for the market

Continue with preparing your variations.

[#900]
=== Making variations available

:market-availability: myToys
:option-availability: myToys

include::_textblocks/instructions/variation-availability.adoc[]

[IMPORTANT]
.Deactivating variation availability
====
If you deactivate the market availability for {market} of a variation in the *Item » Edit item » [Open item] » [Open variation] » Tab: Availability*menu, the variation is deactivated on {market}. If you reactivate the availability of such a variation, the variation is only reactivated on {market} during the nightly item export. +
*_Note:_* To deactivate the variation, the property *{market} category group* has to be remain saved in the *Properties* tab of the respective variation.
====

[#link-category-property]
=== Linking variation to market category

After you created the first marketplace format for {market} with the assistant, the property *{market} category group* is created in your plentymarkets system. For each category that you create a catalogue for, a new selection value is added to this property. This selection value has the same name as the category.

In order for your variations to be exported in the appropriate catalogue, they have to be linked to the *{market} category group* property in the *Properties* tab of the variation.

[.instruction]
Linking a variation to the {market} category group:

. Go to *Item » Edit item » [Open item]*.
. Click on the *Variations* tab.
. Open the variation that should be linked.
. Open the *Properties* tab.
. In the *Variation properties* area, select the property *{market} category group* from the *Properties* drop-down list and click on *Add* (icon:plus-square[role="green"]). +
→ The property is added.
. Select the desired category group from the *Value* drop-down list for the *{market} category group* property. +
→ The variation is exported in the catalogue for this category.
. Save (icon:save[set=plenty]) the settings.

[#550]
== Setting up the item export

Item data is exported to {market} using catalogue formats. Go to *Data » Catalogues* to create catalogues.

* Is this your first time working with catalogues? Then read up on the <<en/data/exporting-data/managing-catalogues, basic concept of the plentymarkets catalogues first>>.

To export your item data to {market}, you need to create catalogues. The catalogues have to be created specifically for each category. Depending on the selected category, the required mandatory fields and optional fields vary. Link the {market} data fields with the item data saved in plentymarkets in the marketplace format afterwards. After you activate the catalogue, the catalogue data is automatically exported to myToys in regular intervals.
// TODO: rewrite

[#600]
=== Notes on the {market} item data structure

The structure of {market} item data differs from the structure in plentymarkets. Only the naming is different:

. The *product* on {market} is the same as the *item* in plentymarkets.
. The *item* on {market} is the same as the *variation* in plentymarkets.

[#650]
=== Creating a catalogue in the assistant

:catalogue-assistant-name: myToys - Catalogues
:number-of-boxes: info box
:catalogue-path: pass:quotes[*Setup » Assistants » Plugins » Select plugin set*]
:catalogue-note: You need a separate catalogue for each category on {market}.
:mapping-fields: more

include::_textblocks/catalogues/instructions/catalogue-assistant-config.adoc[]

[#700]
=== Mapping catalogue fields

After you have created a catalogue, map the market's data fields to item data saved in plentymarkets. This chapter describes how you map data fields and what particularities apply for item exports to {market}. In addition, we provide recommendations for suitable mappings. This information is structured as follows:

* <<#750, Mapping data fields in the catalogue>>
* <<#800, Notes on mapping data fields>>

[#750]
==== Mapping data fields in the catalogue

Now, map the {market} data fields to the item data saved in plentymarkets. Take note of the information regarding specific mappings and recommendations in this chapter.

include::_textblocks/catalogues/instructions/catalogue-mapping.adoc[]

[#800]
==== Notes on mapping data fields

Every market structures item data differently. <<#catalogue-mappings>> contains mapping information for important data fields for {market}.

Also take note of the following general information:

* Map at least all *mandatory fields*. You can limit the data fields shown to the mandatory fields by clicking on the toggle button (icon:toggle-on[role="green"]) *Only display mandatory fields*.

* For some mappings, it makes sense to create <<item/settings/properties#500, properties>> beforehand. You need to create and save these properties before you can map them in the catalogue. Thus, make sure you have created all necessary properties.

* {market} cannot process HTML tags. As such, HTML tags are removed during the export. Keep this in mind, particularly when working with <<#option-itemtext, item descriptions>> and <<#option-bulletpoints, bullet points>>.
//TODO

[[catalogue-mappings]]
.Notes on mapping data fields
[cols="1,3a"]
|====
| Marketplace data field | Explanation

| *Product name*
| Map the plentymarkets data field *Name 1*, *Name 2* or *Name 3*.

The following rules apply to product names:

* Enter the item name in German.
* There is no character limit for product names. However, do not use too many characters because {market} will automatically cut off products name that are too long. Thus, keep the product name as short as possible.
* Manufacturers or brand names do not have to be included in the product name, This information is displayed separately above the product name on {market}.
* Colours, sizes, gender information or repetitions are not allowed as part of product names.

| *Brand*
| Map the plentymarkets data field *Item » External manufacturer name*.

| [option-itemtext]*Texts*
| map the plentymarkets data field *Item text » Item text*. +
The item description can be up to 4000 characters long. Longer text is cut off after 4000 characters and `...` is added. +
*_Note:_* Do you use HTML tags to format your item texts? +
{market} cannot process HTML tags. As such, HTML tags are removed during the export. As such, check your item texts. If you use a lot of HTML tags, you might want to create a property in which you save item descriptions without HTML tags.

| *Colour*
| The colour is used to create variations in plentymarkets and on {market}.

There are two marketplace data fields for exporting colours:

[cols="1,2"]
!===
! Marketplace data field ! Mapping recommendation

! *General Attributes > Colour*
! Map an attribute for colours to the marketplace data field *Colour*.

! *Colour > Colour*
! To each {market} colour shade, map an attribute value of the same attribute for colours that you mapped to the marketplace data field *General Attributes > Colour*.
!===

[.collapseBox]
.Do you use other colour shades than {market}?
--
If you use colour shades that differ from {market}, you can map fallback data fields.

*_Example:_* In addition to *Red*, you also use the shades *Light red*, *Dark red* and *Cherry red* which you manage either as attribute values or property values.

Map these attribute/property values to the marketplace data field *Red* as fallback data fields.

Customers can then find the variation with all of the three different properties when they filter for *Red* on {market}.
--

| *Size*
| The size usually is used to create variations in plentymarkets and on {market}. As such, map an attribute for size information. +
*_Note:_* Whether or not the size is used to create variations largely depends on your product portfolio. If your variations were created without attributes for sizes, contact the {market} integration team to talk about how you can proceed.

| *RRP*
| Map a sales price of the type *RRP*. The referrer {market} must be activated for this sales price.

RRP are shown based on the following logic:

* If the sales price is lower than the RRP, the RRP is shown on {market} as a strikethrough price.
* If the sales prices is higher than or equal to the RRP, the RRP will not be displayed on {market}.

*_Note:_* Do you not have any RRP, for example because you are the manufacturer? Assign the same sales price as for the marketplace data field *Net sales price*. This way, no strikethrough price will be displayed on {market}.

| [option-bulletpoints]*Bullet points*
| Additional information on an item is displayed on the {market} item page by means of bullet points. Up to 255 characters can be exported per bullet point. The text is cut off after 355 characters and `...` is added. We recommend that you create a separate property of the type *Text* for each bullet point. +
*_Note:_* Do not use HTML tags in the properties for the bullet points. {market} cannot process HTML tags. As such, HTML tags are removed during the export.

| *Season*
| Map the values of a plentymarkets property to the seasons. +
*_Tip:_* For variations that are not seasonal, save the property value that you mapped to the {market} value *NOOS* in the catalogue.

{market} uses the following abbreviations for seasons:

* NOOS = never out of stock
* FS = Spring/summer
* HW = Autumn/winter

| *Pattern*
| Map the values of a plentymarkets property to each pattern. +
*_Tip:_* For variations that do not have a pattern, save the property value that you mapped to the {market} value *uni* in the catalogue.

| *Material composition*
| You need to specify the material composition to list products in some categories. This is particularly relevant for textiles and shoes.

Of the five fields available, at least one field has to be linked. This is a multi-dimensional mapping: +
In step 1, link the material type (complex mapping), such as "upper material". +
In step 2, Enter the material composition of “upper material” in the following format: +
{"material1": "percentage","material2": "percentage","material3": "percentage"} +
*_Example:_* {"WO": "90","EL": "10"} +
*_Note:_* Refer to link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/myToys/myToys_Materialien_sortiert.pdf[this document] to access a full list of all material types accepted my {market}.

| *Item weight*
| The entered value is transmitted in grams.

| *Age recommendation*
| The age recommendation defines the target group. This information is used to automatically determine the shop in which the variation is published:

* Variations with an age recommendation of *up to 16 years* are published on {market}.
* Variations with an age recommendation of *18 years or higher* are published on mirapodo/yomonda.

The following values can be used:

* *new born* = 0-9 months +
* *baby* = 9-24 months +
* *mini* = 2-8 years +
* *teen* = 8-16 years +
* *adult* = 18-99 years

[.collapseBox]
.Map a property for *Age recommendation* and link it to your variations
--

. Create a property with the following settings:
  ** Name: Age group
  ** Section: Item
  ** Type: Selection
  ** Selection values:
    ** *new born*
    ** *baby*
    ** *mini*
    ** *teen*
    ** *adult*
. In the menu *Item » Edit item » [Open item] » [Open variation] » Variation tab: Settings*, link the variation to the property.
. Select the property value that suits the variation.
--
|====

Are you missing any marketplace data fields for mapping the items correctly? Contact {market} to add any missing marketplace data fields.

[#850]
=== Activating the catalogue

:interval:

include::_textblocks/catalogues/instructions/catalogue-activation.adoc[]

[#order-documents]
== Preparing order documents

The {market} letterhead has to be included on order documents for {market}. The documents also must contain specific information.

* <<#delivery-notes, Prepare delivery notes>>
* <<#return-notes, Preparing return slips>>

[#delivery-notes]
=== Preparing delivery notes

* <<#1300, How to upload a PDF template for delivery notes>>
* <<#16003, How to adjust delivery notes for {market}>>

[#1300]
==== Uploading a PDF template for delivery notes

{market} delivery notes must contain the {market} logo. Proceed as described below to upload a <<orders/order-documents#170, PDF template>> for delivery notes for {market} to plentymarkets.

[.instruction]
Uploading a PDF template for delivery notes:

. Download the PDF template for {market} delivery notes and save it on your computer:
  ** link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/myToys/myToys_delivery_note_return_note.pdf[Download PDF template]
. Go to *Setup » Client » Select client » Locations » Location: Germany » Documents » Delivery note*.
. Click on the tab *PDF template*.
. Click on *Add template*. +
→ The editing window *Upload new PDF template* opens.
. From the drop-down list *Payment method*, select the option *Plugin: myToys Payment*.
. *_Tip:_* Can’t find the payment method *Plugin: myToys Payment* in the drop-down list?
  .. Go to *Setup » Orders » Settings*.
  .. For the setting *Show inactive plugin payment methods*, select the option *Yes*.
  .. Save (icon:save[set=plenty]) the setting.
. In the drop-down list *Language*, select the option *de*.
. In the line *Template*, click on *Choose template file*.
. Select the PDF template for {market} delivery notes.
. Click on *Upload template* (icon:save[set=plenty]). +
→ The template is uploaded.

[#16003]
==== Adjusting delivery notes

In addition to the {market} letterhead, delivery notes for {market} orders must also contain the following information:

* External order number
* External customer number
* EAN

[.instruction]
Adjusting delivery notes:

. Go to *Setup » Client » Standard » Locations » Germany » Documents » Invoice » Tab: Template*.
. Scroll to the *Columns stock units*.
. For the setting *Item name*, activate the option *EAN*.
. Scroll down to the area *Optional elements below stock unit table*.
. For the setting *External customer number*, select the option *Yes* from the drop-down list.
. For the setting *External customer number*, select the option *Yes* from the drop-down list.
. Save (icon:save[set=plenty]) the settings. +
→ The information is shown on delivery notes.

[#return-notes]
=== Preparing return slips

* <<#1150, Upload a PDF template for return slips>>
* <<#1150-1, How to adjust return slips for {market}>>

[#1150]
==== Uploading a PDF template for return slips

The {market} letterhead has to be included on return slips for {market} orders.
Proceed as described below to upload a <<orders/order-documents#170, PDF template>> for return slips for {market} in plentymarkets.

[.instruction]
Uploading a PDF template for return slips:

. Download the PDF template for {market} return slips and save it on your computer:
  ** link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/myToys/myToys-Retourenschein.pdf[Download PDF template]
. Go to *Setup » Client » Select client » Locations » Location: Germany » Documents » Return slip*.
. Click on the tab *PDF template*.
. Click on *Add template*. +
→ The editing window *Upload new PDF template* opens.
. From the drop-down list *Payment method*, select the option *Plugin: myToys Payment*.
. *_Tip:_* Can’t find the payment method *Plugin: myToys Payment* in the drop-down list?
  .. Go to *Setup » Orders » Settings*.
  .. For the setting *Show inactive plugin payment methods*, select the option *Yes*.
  .. Save (icon:save[set=plenty]) the setting.
. In the drop-down list *Language*, select the option *de*.
. In the line *Template*, click on *Choose template file*.
. Select the PDF template for {market} delivery notes.
. Click on *Upload template* (icon:save[set=plenty]). +
→ The template is uploaded.

[#1150-1]
==== Adjusting return slips

In addition to the {market} letterhead, return slips for {market} orders must also contain the following information:

* External order number
* External customer number
* EAN

[.instruction]
Adjusting return slips:

. Go to *Setup » Client » Standard » Locations » Germany » Documents » Return slip » Tab: Template*.
. Scroll to the *Columns stock units*.
. For the setting *Item name*, activate the option *EAN*.
. Scroll down to the area *Optional elements below stock unit table*.
. For the setting *External customer number*, select the option *Yes* from the drop-down list.
. For the setting *External customer number*, select the option *Yes* from the drop-down list.
. Save (icon:save[set=plenty]) the settings. +
→ The information is shown on return slips.

[#order-processing]
== Automating order processing

Automate the following aspects of limango order processing:

* Automatically send cancellations <<#950, How?>>
* Automatically inform {market} when items have shipped <<#1000, How?>>
* Return management <<#1050, How?>>

[#950]
=== Automatically sending cancellations

Set up an <<automation/event-procedures#, event procedure>> to automatically inform {market} of cancellations.

:table-event-procedure: <<#event-procedure-cancellation-myToys>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[event-procedure-cancellations-myToys]]
.Event procedure to send a cancellation to {market}
[cols="1,2,2"]
|===
| *Setting*
| *Option*
| *Selection*

| *Event*
| *Status change*
| Select an event, for example [8] *Waiting for payment*.

| *Filter*
| *Order > Referrer*
| *myToys*

| *Procedure*
| *Plugins*
| *Report order cancellation to myToys*
|===

[#1000]
=== Automatically sending shipping confirmations to {market}

Set up an <<automation/event-procedures#, event procedure>> to automatically send shipping confirmations to {market}.

:table-event-procedure: <<#event-procedure-shipping-info-myToys>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[event-procedure-shipping-info-myToys]]
.Event procedure for shipping confirmations
[cols="1,2,2"]
|===
|Setting |Option |Selection

| *Event*
| *Status change*
| Select an event, for example [7] *Outgoing items booked*.

| *Filter 1*
| *Order > Order type*
| *Order* +
* Delivery order*

| *Filter 2*
| *Order > Referrer*
| *myToys*

| *Procedure*
| *Plugins*
| *Send shipping information to myToys*
|===

[#1050]
=== Setting up return management

Now set up the processing of returns for {market}.

[#1100]
==== Workflow for returns

The workflow of {market} returns is as follows:

. Customers return the items to you, along with the filled in <<#1150, return slip>>.
. You process the return in plentymarkets.
. You notify {market} when you have received the items.
. {market} reimburses the customers. +
*_Note:_* When you notify {market} that the return is completed, {market} triggers a credit note and the customers receive a refund. Thus, only notify {market} about completing the return after you have received and checked the returned items.

[#1200]
==== Automatically notifying {market} about returns

Set up an <<automation/event-procedures#, event procedure>> to automatically inform {market} when you have completed processing a return.

:table-event-procedure: <<#event-procedure-returns-myToys>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[event-procedure-returns-myToys]]
.Event procedure for automatically notifying {market} of returns
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *New return*
|

| *Filter 1*
| *Order > Order type*
| *Return*

| *Filter 2*
| *Order > Referrer*
| *myToys*

| *Procedure*
| *Plugins*
| *Send return notification to myToys* +
*_Note:_* The procedure *Send return notification to {market}* triggers a credit note. This means that customers will receive a refund. Thus, make sure the event procedure is only triggered after you have received and checked the returned items.
|====

[#1350]
== Troubleshooting

NOTE: Your variations were not exported to {market}? No variation data is exported if one or more variations do not meet the requirements of {market}. This means that none of your variations will be exported to {market} if one of your variations is invalid. To find the error, check the entries in the data log.

[#log-entries]
=== Viewing log entries

include::_textblocks/instructions/viewing_logs.adoc[tag=data-log-intro]

* *Integration* » *myToys*
* *Reference type* » *variationId*

include::_textblocks/instructions/viewing_logs.adoc[tag=data-log-config]

[#mandatory-missing]
=== Finding variations with missing mandatory fields

In addition to the method described above, you can also check which mandatory fields were not specified for your variations. To do so, first activate the log level *Debug* in the log.

[.instruction]
Activating Debug log level:

. Go to *Data » Log*.
. Click on *Configure logs* (icon:cog[]).
. From the list on the left, select the option *myToys*.
. Go to *Settings* on the right and activate the option *Active*.
. Select the *Duration* for which you want the log level to stay active.
. In the drop-down menu *Log level*, activate the option *Debug*.
. *Save* (icon:save[set=plenty]) the settings.

After the next export, you can click on *myToys* entries with the level *Debug* in the *Data » Log* menu. This way, the entries will expand and further details regarding missing mandatory fields is displayed.

[.instruction]
Find variations with missing mandatory fields:

. Go to *Data » Log*.
. In the column on the left, select the following filters:
  * Integration *myToys*
  * Level *Debug*
  * Reference type *variationId*
. Click on *Search* (icon:search[role="blue"]). +
→ All variations with missing mandatory fields are listed.
. Click on the entry to see details. +
→ Under *requiredFields: Object*, the missing mandatory fields are listed.
