= OTTO
:lang: en
include::{includedir}/_header.adoc[]
:keywords: OTTO, market, marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market OTTO in your plentymarkets system.
:position: 150
:url: markets/otto
:id: VM4QQ6Y

The market link:https://www.otto.de/[OTTO^] is part of the Otto Group and one of Germany’s most successful companies for online mail order business. For data protection reasons, the content of the OTTO page is only available for customers who have a contract with OTTO.

OTTO partners find the OTTO page in our link:https://forum.plentymarkets.com/[forum^] within the OTTO category.

[IMPORTANT]
.Three OTTO interfaces
====
The market OTTO offers three interfaces: *Direktversand*, *Cooperation*, and *Integration*. All interfaces are supported by plentymarkets. +
There is a difference in the order import for the interfaces. When using the *Direktversand* and *Cooperation* interfaces, OTTO transfers individual orders to your plentymarkets system which you can process and ship directly to your end customers. +
With the *Integration* interface, your plentymarkets system exchanges one multi-order per day with OTTO. In this case, OTTO ships the ordered items to the end customers.
====
