= Setting up OTTO
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Otto, Market, Marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market OTTO in your plentymarkets system.
:position: 150
:url: markets/otto

The market link:https://www.otto.de/[OTTO^] is part of the Otto Group and one of the most successful companies for online mail order business in Germany. For data protection reasons, the content of the OTTO page is only available for customers who have a contract with OTTO.

OTTO partners find the OTTO page in our link:https://forum.plentymarkets.com/[forum^] within the OTTO category.

[IMPORTANT]
.Two OTTO interfaces
====
The market OTTO offers two interfaces: *Cooperation* and *Integration*. Both interfaces are supported by plentymarkets. +
There is a difference in the order import for the two interfaces. When using the Cooperation interface, OTTO transfers individual orders to your plentymarkets system which you can process and ship directly to your end customer. +
With the Integration interface, your plentymarkets system exchanges one multi-order per day with OTTO. In this case, OTTO ships the ordered items to the end customer.
====
