= PIXmania
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market PIXmania in your plentymarkets system.
:position: 160
:url: markets/pixmania

link:http://www.pixmania.co.uk/index.html[*PIXmania*^] is an online market, which offers a wide range of products in the areas of consumer electronics, home and garden, toys and more. You can offer your new or even used items there and in doing so, extend your reach and generate new customers.

[#10]
== Registering with PIXmania

First register with link:https://www.pixmania-pro.co.uk/secure/gb/uk/s_action/register/index.html[*PIXmania*^] in order to set up the interface to PIXmania in your plentymarkets system. You will then receive the access data that you need for the setup in plentymarkets.

[#20]
== Setting up PIXmania in plentymarkets

The conditions for using PIXmania in your plentymarkets system:

* Items for PIXmania need to have the manufacturer and at least one item image saved for them.
* You will need your PIXmania seller key, which you received from PIXmania after registering for this market.

Country platforms become available for selection after you have saved your seller key.

[.instruction]
Setting up PIXmania in plentymarkets:

. Go to *System » System settings » Markets » PIXmania » Settings*.
. Carry out the settings as desired. Pay attention to the information given in table 1.
. *Save* the settings.

[cols="1,3"]
|====
|Setting |Explanation

|*Activate the automatic data exchange*
|Activate in order to automatically exchange data with PIXmania.

|*PIXmania seller key*
|Enter the seller key that you received from PIXmania.Seller key eingeben, wie von PIXmania received.

|*Countries sold to*
|Activate the country platforms that you want to sell your items on. The list of countries will not be visible until you have entered and saved your seller key.

|*Incoming payment*
|Select whether the orders should be listed with an *open* or *booked* incoming payment when they are transferred into your plentymarkets system. The payments that you receive from PIXmania are grouped together. If you choose to import the payments as *booked*, then the orders that are still awaiting payment from PIXmania will already be marked as paid when they are imported into your system.

|*Referrer*
|Select *PIXmania*. For further information about the order referrer, refer to the chapter <<omni-channel/multi-channel/pixmania#40, *Defining a price column*>>.

2+|Delivery period in full days

|*Default*
|Enter the delivery time in days. The number of days you enter here is the standard delivery time that most of your shipments require.

|*Availability 1 - 5*
|Enter the delivery time in days for each option into the *Domestic* and *Foreign country* fields. Only the days that are entered here will be transferred to PIXmania as a delivery period. 0 is not allowed as a number of days. You have to enter a natural number. Set up the options for item availability in the *<<item/managing-items#, System » System settings » Item » Item availability>>* menu.
|====

__Table 1: basic settings for the market PIXmania__

Connecting to this market allows for the following automatic functions to take place:

* Daily item export
* Stock synchronisation every 15 minutes
* Price synchronisation every 15 minutes
* Order import every 15 minutes

[#30]
== Setting the item availability

Items have to be available for PIXmania. This is done in the *Availability* tab of an item within the *<<item/managing-items#40, Item » Edit item » Tab: Variation ID>>* menu. Items for PIXmania also need to have the manufacturer and at least one item image saved for them.

[.instruction]
Setting the item availability for PIXmania:

. Open the *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings* menu.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the *Markets* section in the selection field.  +
→ A list with all available markets will be displayed.
. Activate the option *PIXmania*.
. Activate the option Web-API.
. Click on *Add*. +
→ The Market will be added.
. *Save* the settings.  +
→ The item is available on PIXmania.

The availability for variations can be individually edit in the *Item » Edit item » Open item » Tab: Variation ID » Open variation » Tab: Availability* menu.

[#40]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer PIXmania. This price will be displayed on PIXmania.

[.instruction]
Defining a sales price for PIXmania:

. Open the menu *System » System settings » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a checkmark next to the referrer *PIXmania*.
. *Save* the settings.

[#50]
== Importing brand IDs

The brand IDs from PIXmania are required. You receive them by following the procedure described below.

[.instruction]
Exporting the data format:

. Go to *Data » Dynamic export » Tab: New data format*.
. Select the setting *Producer* under *Data format type*.
. Enter name.
. Activate the fields *ProducerID*, *ProducerName* and *ProducerPixmaniaID*.
. *Save* the settings. +
→ The *Edit data format* tab will open.
. Expand the data format.
. Click on *Export data*.
. Save the CSV file on your computer.

Send the CSV file to the PIXmania customer service. You will then receive an Excel file from PIXmania. Generate a CSV file from this Excel file which corresponds to the *Producer* data format.

[.instruction]
Importing the data format:

. Go to *Data » Dynamic import*.
. Select the field separator.
. Select your data format under *Format*.
. Click on *Browse...*.
. Open the CSV file.
. Click on *Import*.  +
→ After having imported the brand IDs, you can find the PIXmania ID of a manufacturer in the *System » System settings » Item » Manufacturers* menu.

[#60]
== Linking categories

In order to link your categories with PIXmania categories, download the PIXmania category list first. Then link your own categories with the most appropriate PIXmania categories.

[.instruction]
Importing PIXmania categories:

. Go to *System » System settings » Markets » PIXmania » Category link*.
. Click on *Browse...*.
. Select the *field separator*.
. *Save* the settings. +
→ The category list will be imported.

Proceed as described below to link your categories with PIXmania categories.

[.instruction]
Linking categories:

. Go to *System » System settings » Markets » PIXmania » Category link*.
. Click on the *gear-wheel icon* in the *PIXmania link* column. +
→ The PIXmania categories will be displayed in the *Categories* area.
. Expand the category.
. Select the subcategory.  +
→ The linked category will be displayed in the *Selection* area.
. Click on *Reload*. +
→ The links will be displayed under *PIXmania link*.

[IMPORTANT]
.*Deleting category links*
====
You can delete category links in the *Selection* area.
====

After you have linked your categories with PIXmania's categories, you export the data to PIXmania.

[.instruction]
Exporting category links:

. Go to *System » System settings » Markets » PIXmania » Category link*.
. Click on *Export link*. +
→ A CSV file will be created.
. Save the CSV file on your computer.
. Send the CSV file to PIXmania.

[#70]
== Linking attributes

If you have created *<<item/managing-items#390, attributes>>* in your plentymarkets system, you will have to link these attributes with PIXmania. Proceed as described below to link the attribute Colour with PIXmania. Link further attributes in the same way.

[.instruction]
Linking attributes:

. Go to *System » System settings » Item » Attributes*. +
→ An overview of all existing attributes will open.
. Expand the attribute *Colour*.
. Click on the *Market variation* tab.
. Select *PIXmania* from the *Market* drop-down menu.  +
→ A second drop-down menu *Pixmania* will be displayed.
. Select the attribute *Colour* from the *Pixmania* drop-down menu.
. *Save* the settings.

[#80]
==  Activating the payment method

Activate the *<<payment#, payment method>>* *PIXmania Payment* as described below.

[.instruction]
Activating the PIXmania payment method:

.  Go to *System » System settings » Orders » Payment » Methods*.
.  Place a check mark next to the setting *Also show inactive*.
.  Open the folder *International*.
.  Click on *PIXmania Payment*.  +
→ The *Settings* tab will open.
.  Carry out the settings as desired. Pay attention to the information given in table 2.
.  Place a check mark next to the option *Active*.
. *Save* the settings.

[cols="1,3"]
|====
| Setting | Explanation

|*Language*
| The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo* and *Upload logo*. This makes it possible to enter values for these options in various languages. The values for a language will be activated as soon as a buyer selects the language in the online store.

|*Name*
| Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
| Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
| If you selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
| Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely set up.

|*Logo*
| Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method will be displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method will not be displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* will be displayed.

|*Logo view*
| If *Show upload logo* was selected from the *Logo* drop-down menu, then the logo that was uploaded will be displayed here.

|*Upload logo*
| If *Show upload logo* was selected from the *Logo* drop-down menu, then you will be able to upload an external logo here. +
Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|*Priority*
| Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
| If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. *Important:* Do not enter a value into both fields. +
For further information, refer to the *<<basics/statistics#, Statistics>>* and *<<basics/statistics/general-statistics/item/tops-flops#, Tops/Flops>>* pages of the manual. For an example for flat rate and percentage costs, refer to the *<<omni-channel/multi-channel/pixmania#20, Basic settings>>* page of the manual.
|====

__Table 2: settings of the payment method__

[TIP]
.Permitting the payment method in customer classes
====
Go to *System » System settings » CRM » Classes* to activate or deactivate the *Permitted payment methods*. +
For further information, refer to the *<<omni-channel/multi-channel/pixmania#40, Payment methods and customer classes>>* chapter of the manual.
====

For further information, refer to the *<<payment#, Payment methods>>*  page of the manual.

[#90]
== Viewing the export history

In the *System » System settings » Markets » PIXmania » Export history* menu, you can see an overview of the export history of your PIXmania items. Export histories *in progress* as well as *completed* export histories are displayed here.
