= PIXmania
:lang: en
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: PIXmania, market, marketplace, marketplace PIXmania, pixmania.de, setting up PIXmania, PIXmania setup, multichannel, multi-channel, multi channel, market place
:description: Multi-Channel in plentymarkets: Set up the interface to the market PIXmania in your plentymarkets system.
:position: 160
:url: markets/pixmania
:id: XMVLNKP

link:http://www.pixmania.co.uk/index.html[PIXmania^]{nbsp}icon:external-link[] is an online market which offers a wide range of products in consumer electronics, home and garden, toys and more. You can offer your new but also your used items there and in doing so, extend your reach and generate new customers.

[#100]
== Registering with PIXmania

First register with link:https://www.pixmania-pro.co.uk/secure/gb/uk/s_action/register/index.html[PIXmania^]{nbsp}icon:external-link[] in order to set up the interface to PIXmania in your plentymarkets system. You will then receive the access data that you need for the setup in plentymarkets.

[#200]
== Setting up PIXmania in plentymarkets

Requirements for using PIXmania in your plentymarkets system:

* Items for PIXmania need to have the manufacturer and at least one item image saved for them.
* You need your PIXmania seller key, which you received from PIXmania after registering for this market.

Country platforms become available for selection after you have saved your seller key.

[.instruction]
Setting up PIXmania in plentymarkets:

. Go to *Setup » Markets » PIXmania » Settings*.
. Expand the *Basic settings* area (icon:plus-square-o[]).
. Carry out the settings. Pay attention to the explanations given in <<#basic-settings-pixmania>>.
. *Save* (icon:save[role="green"]) the settings.

[[basic-settings-pixmania]]
.Basic settings for the market PIXmania
[cols="1,3a"]
|====
|Setting |Explanation

| *Activate the automatic data exchange*
|Activate in order to automatically exchange data with PIXmania. +
The data exchange includes the daily item export, the stock synchronisation every 15 minutes and the order import every 15 minutes.

| *PIXmania seller key*
|Enter the seller key that you received from PIXmania.

| *Countries sold to*
|Activate the country platforms that you want to sell your items on. The list of countries is not visible until you have entered and saved your seller key.

| *Incoming payment*
|Select whether the orders should be listed with an *open* or *booked* incoming payment when they are transferred into your plentymarkets system. The payments that you receive from PIXmania are grouped together. If you choose to import the payments as *booked*, then the orders that are still awaiting payment from PIXmania are already marked as paid when they are imported into your system.

| *Referrer*
| Select *PIXmania*.

2+|Delivery period in full days

| *Standard*
|Enter the delivery time in days. The number of days you enter here is the standard delivery time that most of your shipments require.

| *Availability 1 - 5*
|Enter the delivery time in days for each option into the *Domestic* and *Foreign* country fields. Only the days that are entered here are transferred to PIXmania as a delivery period. 0 is not allowed as a number of days. You have to enter a natural number. Set up the options for item availability in the *Setup » Item » Availability* menu.
|====

Connecting to this market allows for the following automatic functions to take place:

* Daily item export
* Stock synchronisation every 15 minutes
* Price synchronisation every 15 minutes
* Order import every 15 minutes

[#250]
== Activating the order referrer

In order to link items, characteristics etc. with PIXmania, you have to activate the order referrer PIXmania in the *Setup » Orders » Order referrer* menu.

[.instruction]
Activating the order referrer PIXmania:

. Go to *Setup » Orders » Order referrer*.
. Activate the option *PIXmania*.
. *Save* (icon:save[role="green"]) the settings.

[#300]
== Setting the variation availability

Items have to be available for PIXmania. This is done in the *Availability* tab of an item within the *Item » Edit item » [Open item] » Tab: Variation ID* menu.

[TIP]
.Selling all variations of an item on PIXmania
====
To sell all variations of an item on PIXmania, carry out the settings described below for the main variation. The settings are then passed on to all variations of the item.
====

[.instruction]
Setting the variation availability for PIXmania:

. Go to *Item » Edit item » [Open item] » Tab: Variation ID » Tab: Settings*.
. Open the variation that you want to sell on PIXmania.
. In the *Availability* area, activate the option *Active*.
. Click on the *Availability* tab.
. In the *Markets* area, click in the selection field. +
→ A list of all available markets is displayed.
. Activate the option *PIXmania*.
. Activate the option *Web API*.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The market is added.
. *Save* (icon:save[role="green"]) the settings.

[#400]
== Defining a sales price

:referrer-price: PIXmania

include::_textblocks/instructions/define-sales-price.adoc[]

[#500]
== Importing brand IDs

The brand IDs from PIXmania are required. You receive them by following the procedure described below.

[.instruction]
Exporting the data format:

. Go to *Data » Dynamic export » Tab: New data format*.
. Select the setting *Producer* under *Data format type*.
. Enter a name.
. Activate the fields *ProducerID*, *ProducerName*, and *ProducerPixmaniaID*.
. *Save* (icon:save[role="green"]) the settings. +
→ The *Edit data format* tab opens.
. Expand the data format (icon:plus-square-o[]).
. Click on *Export data*.
. Save the CSV file on your computer.

Send the CSV file to the PIXmania customer service. You will then receive an Excel file from PIXmania. Generate a CSV file from this Excel file which corresponds to the *Producer* data format.

Import the brand IDs into your plentymarkets system using the import tool. To do so, create an import of the type <<data/importing-data/sync-types/elasticSync-manufacturer#, Manufacturer>>. After you have created the import, you have to set the import options for the import, set the matching, and create the mappings.

[discrete]
=== Creating an import

First create an import of the type *Manufacturer*.

[.instruction]
Creating an import:

. Go to *Data » Data import: Import*. +
→ The import overview opens.
. Click on *Add import* (icon:plus-square[role="green"]). +
→ The editing area *New import* is displayed.
. Carry out the settings. Pay attention to the explanations given in <<#manufacturer-sync-pixmania>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The import is created. +
→ The matching settings of the import open.

[[manufacturer-sync-pixmania]]
.Creating an import
[cols="1,3a"]
|====
|Setting |Explanation

2+^| *Basic data*

| *Name*
|Enter a name. This name is displayed in the overview and can be used for the search.

| *Interval*
|Select an interval for the imports. +
By choosing the option *Schedule* you can determine how often and at what time imports shall be started.

| *Type*
|Select the type <<data/importing-data/sync-types/elasticSync-manufacturer#, Manufacturer>> from the drop-down list. This import type is used to import manufacturer data.

2+^| *Import*

| *Data type*
|Select the file format of the import file. +
Currently, *CSV/TXT* is the only available option, as only CSV or TXT files can be imported.

| *Character set*
|Select the character set of the file or the option *Detect automatically*.

| *Starting in line*
|Select a line starting from which the data should be imported.

| *Header is included*
|Select whether the import file contains a header.

| *Use global cache*
|Determine whether the global cache should be used for a file or not. If the setting is activated, only modified data rows will be imported. If the setting is not activated, you can import one and the same file again at any time.

| *Automatic mapping*
|Select whether the mapping should be done automatically. The columns in the CSV or TXT file can be mapped automatically to the plentymarkets data fields. To ensure that the mapping works properly, the names of the fields that you selected in the FormatDesigner must not be changed.

2+^| *Separator*

| *Separator*
|The separator of the CSV or TXT file is automatically detected. This setting is activated by default. +
Alternatively, you can manually select the field separator that is set in the import file in order to separate the data fields (columns) of a data record from each other. +
Possible separators are *Semicolon*, *Comma*, *Tab* and *Pipe*.

| *Delimiter*
|Select delimiters within the fields that may contain multiple values. +
* " = individual values within one field are separated by double quotation marks.
* ' = individual values within one field are separated by single quotation marks.

2+^| *Source*

| *Source*
a| Select *Manual upload*, *FTP*, *HTTPS* or *SFTP*. +
Depending on the selected option, the following settings are displayed:

*Manual upload* = Select and upload a local file. +
After running an import, the file is automatically deleted from the webspace. This is preset by default. In order to save the file you need to remove the check mark. *_Note:_* storing the file on the webspace is subject to a fee.

*FTP* = Host, port, user name, password and file name are displayed.

    * *Host (mandatory field)* = Enter the host of the FTP server. +
      *_Tip:_* Use your plentymarkets FTP access.
    * *Port* = Enter the port of the FTP server. If no port is entered, the standard port (22) is used.
    * *User name (mandatory field)* = Enter the user name for the FTP access.
    * *Password (mandatory field)* = Enter the password for the FTP access.
    * *File name* = Enter the path and the name of the file from which the data is to be imported. The file name has to end with .csv or .txt. +
    *_Note:_* You can use wildcard characters in the field *File name* by e.g. replacing a part of the file name with a ***. Only use wildcard characters in combination with the option *Move file to archive when import was successful*.
    * *Move file to archive when import was successful* = If this option is activated, the import file is automatically moved to the new *Archive* folder in the FTP directory once the import was successful.


*HTTPS* = *Select External URL.

        * *External URL* = Enter the URL to access the import file. +
         *_Tip:_* Save the file on your plentymarkets webspace.
          * *Authentication:* Select whether an authentication is required to access the file.
            ** *none* = no authentication required
            ** *HTTP authentication* = = an authentication is required for each user and password

*SFTP* = Host, port, user name, password and file name are displayed.

        * *Host (mandatory field)* = Enter the host of the FTP server. +
        * *Port (mandatory field)* = Enter the port of the FTP server. If no port is entered, the standard port (22) is used.
        * *User name (mandatory field)* = Enter the user name for the FTP access.
        * *Password (mandatory field)* = Enter the password for the FTP access.
        * *File name* = Enter the path and the name of the file from which the data is to be imported. The file name has to end with .csv or .txt. +
        *_Note:_* You can use wildcard characters in the field *File name* by e.g. replacing a part of the file name with a ***. Only use wildcard characters in combination with the option *Move file to archive when import was successful*.
        * *Move file to archive when import was successful* = If this option is activated, the import file is automatically moved to the new *Archive* folder in the FTP directory once the import was successful.
|====

[discrete]
=== Setting the import options

After you created a *Manufacturer* import, you set the import options. To do so, carry out the settings as described in the <<data/importing-data/ElasticSync#1300, Setting the import options>> chapter on the import tool page.

[discrete]
=== Setting the matching

Next, set the matching for the import. To do so, carry out the settings as described in the <<data/importing-data/ElasticSync#1400, Setting the matching>> chapter on the import tool page.

[discrete]
=== Creating a mapping

Last, you have to create the mappings for the data fields. To do so, carry out the settings as described in the <<data/importing-data/ElasticSync#1500, Creating a mapping>> chapter on the import tool page.

[#600]
== Linking categories

In order to link your categories with PIXmania categories, download the PIXmania category list first. Then link your own categories with the most appropriate PIXmania categories.

[.instruction]
Importing PIXmania categories:

. Go to *Setup » Markets » PIXmania » Category link*.
. Click on *Select file*.
. Select the *field separator*.
. *Save* (icon:save[role="green"]) the settings. +
→ The category list is imported.

Proceed as described below to link your categories with PIXmania categories.

[.instruction]
Linking categories:

. Go to *Setup » Markets » PIXmania » Category link*.
. In the *PIXmania link* area, click on the *gear-wheel icon*. +
→ The PIXmania categories are displayed under *Categories*.
. Expand the category.
. Select the subcategory. +
→ The linked category is displayed in the *Selection* area.
. Click on *Reload*. +
→ The links are displayed under *PIXmania link*.

[IMPORTANT]
.*Deleting category links*
====
You can delete category links in the *Selection* area.
====

After you have linked your categories with PIXmania's categories, export the data to PIXmania.

[.instruction]
Exporting category links:

. Go to *Setup » Markets » PIXmania » Category link*.
. Click on the *Export link* button. +
→ A CSV file is created.
. Save the CSV file on your computer.
. Send the CSV file to PIXmania.

[#700]
== Linking attributes

If you have created <<item/managing-items#390, attributes>> in your plentymarkets system, you have to link these attributes with PIXmania. Proceed as described below to link the attribute Colour with PIXmania. Link further attributes in the same way.

[.instruction]
Linking attributes:

. Go to *Setup » Item » Attributes*. +
→ An overview of all existing attributes opens.
. Expand the attribute *colour*.
. Click on the *Market variation* tab.
. Select *PIXmania* from the *Market* drop-down list. +
→ A second drop-down list *PIXmania* is displayed.
. Select the attribute *Colour* from the *PIXmania* drop-down list.
. *Save* (icon:save[role="green"]) the settings.

[#800]
==  Activating the payment method

Activate the <<payment/managing-payment-methods#, payment method>> *PIXmania Payment* as described below.

[.instruction]
Activating the PIXmania payment method:

. Go to *Setup » Orders » Payment » Methods*.
. Activate the option *Also show inactive*.
. Open the folder *International*.
. Click on *PIXmania Payment*. +
→ The *Settings* tab opens.
. Carry out the settings. Pay attention to the explanations given in <<#settings-payment-method-pixmania>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings.

[[settings-payment-method-pixmania]]
.Settings for the payment method
[cols="1,3a"]
|====
| Setting | Explanation

| *Language*
| The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo*, and *Upload logo*. This enables you to enter values for these options in various languages. The values for a language are activated as soon as a buyer selects the language in the plentyShop.

| *Name*
| Enter the name that should be displayed in the plentyShop and on invoices etc.

| *Info page*
| Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

| *Info page (external)*
| If you selected the *Info page (external)* option under *Info page*, then enter the URL of the info page here.

| *Countries of delivery*
| Do not select a country of delivery. +
You cannot use the payment method in your plentyShop. Therefore, this payment method is only activated in plentymarkets. It is not completely set up.

| *Logo*
a| Select one of the following options for displaying the logo: +

* *Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
* *Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
* *Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

| *Logo view*
| If *Show upload logo* was selected from the *Logo* drop-down list, then the logo that was uploaded is displayed here.

| *Upload logo*
| If *Show upload logo* was selected from the *Logo* drop-down list, then upload an external logo here. +
Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG, and JPG.

| *Priority*
| Select the priority for displaying the payment method in the plentyShop.

| *Costs: Flat rate or percentage*
| If the payment method results in additional costs, enter the percentage value or flat rate value. The selection depends on the conditions of your contract. *_Important:_* Do not enter a value into both fields. +
For further information, refer to the <<business-decisions/plenty-bi/statistics#, Statistics>> page of the manual. For an example of flat rate and percentage costs, refer to the <<payment/managing-payment-methods#20, Managing payment methods>> page.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *Setup » CRM » Classes* to activate or deactivate *permitted payment methods*. +
For further information, refer to the <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter.
====

For further information, refer to the <<payment/managing-payment-methods#, Managing payment methods>> page.

[#900]
== Viewing the export history

In the *Setup » Markets » PIXmania » Export history* menu, you can see an overview of the export history of your PIXmania items. Export histories *in progress* as well as *completed* export histories are displayed here.
