= Setting up Netto, GartenXXL.de, and GartenXXL.at
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Plus.de, GartenXXL.de, GartenXXL.at, Netto, Market
:description: Multi-Channel in plentymarkets: Set up the interface to the markets Netto Marken-Discount, GartenXXL.de and GartenXXL.at in your plentymarkets system.
:position: 170
:url: markets/plus-gartenxxl
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

link:https://shop.netto-online.de/[Netto Marken-Discount] offers various products from different product categories, such as food, toiletries, household items, gardening and leisure equipment.

link:http://www.gartenxxl.de/[GartenXXL^] is a brand belonging to the Tengelmann E-Stores GmbH. The GartenXXL website offers brand-name equipment and outdoor furniture as well as tips and tricks for garden maintenance.

[#100]
== Registering with Netto eStores

Before setting up Netto eStores in your plentymarkets system, you have to register with Netto eStores. Contacts for the registration: +
Katrin.Beer@netto-online.de +
Christian.Mertens@netto-online.de

[IMPORTANT]
.Item export with product XML 4.0
====
plentymarkets transfers item data with the product XML 4.0 to the markets belonging to Netto eStores GmbH. Inform Netto eStores about this when registering. Otherwise, your items cannot be exported.
====

[#200]
== Setting up Netto eStores in plentymarkets

In order to sell items on Netto Marken-Discount, GartenXXL.de, and GartenXXL.at, you have to set up the markets in plentymarkets. To do so, proceed as follows:

[.instruction]
Setting up Netto Marken-Discount/GartenXXL.de/GartenXXL.at in plentymarkets:

. Go to *Setup » Markets » Netto eStores*. +
→ The *Settings* tab opens.
. Carry out the settings. Pay attention to the information given in <<settings-plus>>.
. *Save* (icon:save[role="green"]) the settings.

[[settings-plus]]
.Settings for Netto Marken-Discount, GartenXXL.de and GartenXXL.at
[cols="1,3"]
|====
|Setting |Explanation

|*Activate the automatic data exchange*
|Select *Yes* to activate the automatic data exchange or *No* to deactivate the data exchange. +
If you select *Yes,* the stock synchronisation, the item export, and the order import are activated.

|*Activate item export*
|Select *Yes* to activate the automatic item export or *No* to deactivate it.

|*Activate the stock update*
|Select *Yes* to activate the automatic stock update or *No* to deactivate the stock update.

2+|Sales partner information

|*Supplier number*
|Enter the supplier number that you have received from Netto eStores.

2+|Item settings

|*Item name*
|Select the item name that is transferred to Netto eStores.

|*Variation name*
|Select the variation name that is transferred to Netto eStores. +
*Variation name* = The variation name is transferred. +
*Add attribute values of the variation* = The attribute values are added to the variation name, separated by space (example: “T-Shirt red XL”)

|*Short item description*
|Select the short item description that is transferred to Netto eStores.

|*Item description*
|Select the item description that is transferred to Netto eStores.

|*Image position for energy label*
|Enter the image's position number if the energy label was not uploaded to the energy label property but saved as an item image instead. See the <<Creating the property energy efficiency, Creating the property energy efficiency>> chapter for details on energy labels.

|*Quantity for items that are not limited to the stock*
|For items that have the setting *no limitation*, the maximum amount of the real stock and the quantity defined here is transferred. +
Example: Setting 0, net stock 8. plentymarkets transfers 8. +
Items with the setting *Limited to net stock* are not taken into consideration.

|*Quantity for items not limited to stock, if stock is 0*
|Enter a number that you want to transfer as the stock quantity for items that are not limited to stock, if the stock is 0.

|*Standard delivery time*
|Enter the average delivery time in days.

|*Item delivery time 1 - 10*
|Enter the average delivery time in days for the item availabilities 1-10. +
*Important:* Note that you can only enter exact values (time periods, e.g. 2-3, are not possible).

|*Standard commission in percent*
|Enter the commission value that you agreed on with Netto eStores.

|*Default shipping costs*
|Enter the shipping costs in Euro. The value entered is used as default shipping costs for all items.

|*Price for purchase price/sales price model*
|Select a price for the purchase price/sales price model. You can select all prices that are released for Plus.de. If the selected price is saved for all variations of an item, then the price is exported as purchase price for Plus.de. Otherwise, the commission rate that is saved for the setting *Standard commission in percent* is exported. +
*Important:* The price selected here must not be the sales price because in this case, no price will be exported for the purchase price/sales price model.

2+|Order settings

|*Minimum order quantity*
|Enter a number of items if you want to define a minimum order quantity.

|*Maximum order quantity*
|Enter a number of items if you want to define a maximum order quantity.

|*Item names in order items*
|Select whether the item name in the order items should be taken from Netto eStores or from your online store.

2+|SFTP settings

|*User name*
|Enter the user name that you have received from Netto eStores.
|====

[IMPORTANT]
.Only change the purchase price/sales price after contacting the sales channel
====
Only change the settings for the options *Standard commission in percent* and *Price for purchase price/sales price model* after contacting the sales channel. Netto eStores recommends to use a commission model with the commission rate agreed upon with Netto eStores as default.
====

Connecting to this market allows for the following automatic processes to take place:

- daily item export
- daily price synchronisation
- hourly stock synchronisation
- hourly order import

[#250]
== Activating an order referrer

In order to link items, properties etc. with Netto Marken-Discount, GartenXXL.de, and GartenXXL.at, you have to activate the order referrer in the *Setup » Orders » Order referrer* menu. The following example describes how to activate the order referrer for Netto. Activate the order referrers for GartenXXL.de and GartenXXL.at in the same way. +

[IMPORTANT]
.Also activate the order referrer plus.de
====
 Always activate the order referrer *plus.de* additionally.  This is to ensure a proper operation.
====

[.instruction]
Activating the order referrer for Netto:

. Go to *Setup » Orders » Order referrer*.
. Place a check mark next to the option *Netto*.
. *Save* (icon:save[role="green"]) the settings.

[#300]
== Setting the item availability

Items have to be available for Netto Marken-Discount, GartenXXL.de, and GartenXXL.at. This is done in the *Availability* tab of an item within the <<item/managing-items#_changing_the_variation_data_shown_in_variation_tabs, Item » Edit item » Open item » Tab: Variation ID menu>>. Set the item availability for the markets Netto Marken-Discount, GartenXXL.de, and GartenXXL.at separately, depending on which markets you would like to offer your items on. +

The following instruction describes how you set the item availability for Netto. Carry out the settings for the other markets in the same way. +

[.instruction]
Setting the item availability for Netto:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Place a check mark next to the option *Netto*.
. Place a check mark next to the option *Web API*.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The market is added.
. *Save (icon:save[role="green"]) the settings. +
→ The item is available on Plus.de.

The availability for variations can be edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu. +

[#330]
==  Defining SKU manually

Add SKUs manually for specific referrers in the menu <<item/managing-items#170, Item » Edit item » Open item » Tab: Variation ID » Tab: Availability>> if needed. +

The referrer *Plus.de* also covers the markets Netto Marken-Discount, GartenXXL.de, and GartenXXL.at if you add SKUs.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Click on the *Availability* tab.
. Click on *Add* (icon:plus-square[role="green"]) in the section *SKU*. +
→ The window *New SKU* is displayed.
. Select the referrer *Plus.de*.
. Enter the SKU.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The SKU is saved and displayed.

[#350]
== Defining a sales price

Proceed as described below to define a sales price for the order referrers Netto, GartenXXL.de, and GartenXXL.at. The order referrer *Plus.de* has to be activated at the sales price to make sure that the price is exported during the item export.

[IMPORTANT]
.Activate multiple order referrers
====
For the markets Netto, GartenXXL.de, and GartenXXL.at, we recommend to define a sales price with the order referrers *Plus.de*, *Netto*, *GartenXXL.de*, and *GartenXXL.at*. This is to ensure that the price is included in the item export an order import.
====

[.instruction]
Defining a sales price for Netto Marken-Discount/GartenXXL.de/GartenXXL.at:

. Go to *Setup » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the order referrers *Plus.de*, *Netto*, *GartenXXL.de*, and *GartenXXL.at*. +
. *Save* (icon:save[role="green"]) the settings.

[#365]
== Setting the Show unit price-option

It is mandatory to specify whether items that you would like to sell on the markets Netto and GartenXXL have a unit price. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings* and activate the option *Show unit price* to indicate that an item needs to have a unit price.

[.instruction]
Activating the Show unit price-option:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Place a check mark next to the option *Show unit price* in the *Dimensions* section. +
→ The filter attribute *Grundpreispflicht* (Mandatory unit price) is set to *ja* (yes) when exporting the XML file.

If you do not activate the *Show unit price* option, then *nein* (no) is transferred and indicates that the item does not need an obligatory unit price.

As an alternative, you can create a property for mandatory unit prices. This property overwrites the setting for the *Show unit price* option. For further information, refer to the <<Creating the property Mandatory unit price, Creating the property Mandatory unit price>> chapter.

[#400]
== Activating the payment method

Activate the <<payment/managing-payment-methods#, payment method>> *Netto* as described below. Afterwards, carry out the settings in the same way for the payment methods *GartenXXL.de*, and *GartenXXL.at*.

[.instruction]
Activating the payment method Netto:

. Go to *Setup » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Click on the folder *DE &gt; Netto*. +
→ The settings for the Netto payment method are displayed.
. Carry out the settings. Pay attention to the explanations given in <<settings-payment-method>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings.

[[settings-payment-method]]
.Settings for the payment method
[cols="1,3"]
|====
|Setting |Explanation

|*Language*
|The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo* and *Upload logo*. This enables you to enter values for these options in various languages. The values for a language are activated as soon as a buyer selects the language in the online store.

|*Name*
|Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
|Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
|If you have selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
|Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely configured.

|*Logo*
|Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

|*Logo view*
|If *Show upload logo* has been selected from the *Logo* drop-down list, then the logo that has been uploaded is displayed here.

|*Upload logo*
|If *Show upload logo* has been selected from the *Logo* drop-down list, upload an external logo here. +
 Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|*Priority*
|Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
|If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. Important: Do not enter a value into both fields.  +
For further information, refer to the <<basics/working-with-plentymarkets/statistics/managing-statistics#, Managing statistics>> page of the manual. For an example of flat rate and percentage costs, refer to the <<payment/managing-payment-methods#20, Managing payment methods>> page of the manual.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *Setup » CRM » Classes* to activate or deactivate *permitted payment methods*. +
For further information, refer to the <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter.
====

For further information, refer to the <<payment/managing-payment-methods#30, Managing payment methods>> page of the manual.

[#500]
== Linking categories

You need to create category links in order for your items to be displayed on the markets Netto Marken-Discount, GartenXXL.de, and GartenXXL.at. Netto eStores will send you the necessary Netto Marken-Discount, GartenXXL.de, and GartenXXL.at category Ids. Proceed as follows to create category links in order for your items to be displayed in the <<item/managing-categories#, categories>> on the marketplaces.

[.instruction]
Linking categories:

. Go to *Setup » Markets » Netto eStores*.
. Click on the *Activate categories* tab.
. Enter the category ID that best matches your online store categories in the columns*Netto category link*/*GartenXXL.de category link*/*GartenXXL.at category link*. +
→ The category IDs of the markets can be found in the category files that you have received from Netto eStores.
. Activate the categories.
. *Save* (icon:save[role="green"]) the settings.

[#700]
== Creating properties

Use <<item/managing-items#480, properties>> to link your items to particular characteristics that you need for the markets Netto Marken-Discount, GartenXXL.de, and GartenXXL.at. If needed, you can save commissions and category links that differ from the default settings saved for the items. Moreover, you transfer item information to the markets with the help of property filters and determine criteria for the item search on the markets.

As described in chapter <<Linking categories, Linking categories>>, go to *Setup » Markets » Netto eStores* and save the standard category links in the *Activate categories* tab. If you want to link specific items to a different category, use the <<item/managing-items#480, properties>> *Item category link for Netto*, *Item category link for GartenXXL.de*, or *Item category link for GartenXXL.at*.

[.instruction]
Creating a property:

. Go to *Setup » Item » Characteristics*.
. Open the *New Property* tab.
. Enter the name in the *Name (internal)* field.
. Select the property type *Text*.
. Select the property *Item category link for Netto Marken-Discount* / *Item category link for GartenXXL.de* / *Item category link for GartenXXL.at* from the drop-down list.
. *Save* (icon:save[role="green"]) the settings.

[#800]
=== Setting commission rates saved for an item

Go to *Setup » Markets » Netto eStores* to save a standard commission rate for the markets. You can save a different commission rate for each item because different commissions may apply to particular Netto eStores item classes. To do so, use the <<item/managing-items#480, property>> *Commission in percent*. This setting has a higher priority than the standard provision. Make sure to coordinate this percentage value with Netto eStores in advance.

[.instruction]
Creating a property:

. Go to *Setup » Item » Characteristics*.
. Open the *New Property* tab.
. Enter the name in the *Name (internal)* field.
. Select the property type *Text*.
. Select the Netto eStores property *Commission in percent* from the drop-down list.
. *Save* (icon:save[role="green"]) the settings.

[TIP]
.Properties: Filter
====
Filters for Netto eStores have two functions: First, they are used to transfer item information to Netto eStores and second, items can be found with filters for Netto eStores. After having selected a filter, another drop-down list is displayed. Select the filter property that you want to link to the item. +
Note: The property *Energy efficiency* is only available for the market Netto eStores.
====

[#900]
=== Creating the property energy efficiency

To comply with EU regulations on energy efficiency that came into force on 1 January 2015, you have to provide information on the energy efficiency of certain items to sell them on Netto eStores markets. In addition, you have to make product data sheets available to potential buyers of these items. Create the following three <<item/managing-items#480, properties>>: *Energy efficiency class*, *Energy label* and *Product data sheet*.

[.instruction]
Creating the property energy efficiency class:

. Go to *Setup » Item » Characteristics*.
. Open the *New Property* tab.
. Enter the name in the *Name (internal)* field.
. Select the property type *No*.
. Select the option *Energy efficiency* from the *Netto eStores property* drop-down list. +
→ A drop-down list opens.
. Select the energy efficiency class.
. *Save* (icon:save[role="green"]) the settings.

Select the property type *File* for the properties Energy label and Product data sheet. Select the option *Energy label* or *Product data sheet* from the drop-down list *Netto eStores property*. The following example describes how to create the property energy label. Afterwards, create the property product data sheet the same way.

[.instruction]
Creating the property energy label:

. Go to *Setup » Item » Characteristics*.
. Open the *New Property* tab.
. Enter the name in the *Name (internal)* field.
. Select the property type *File*.
. Select the option *Energy label* from the drop-down list *Netto eStores property*.
. *Save* (icon:save[role="green"]) the settings.

You then link the properties in the <<item/managing-items#480, Properties>> tab of a Netto eStores item. Proceed as described below to do so.

[.instruction]
Linking energy efficiency properties to a Netto eStores item:

. Go to *Item » Edit item*.
. Open the item.
. Open the *Properties* tab.
. Activate the properties *Energy efficiency class*, *Energy label* and *Product data sheet* that you have just created.
. *Save* (icon:save[role="green"]) the settings. +
→ The properties are linked to the item and are visible in the *Properties* area.
. Upload the image file of the energy label to the *Energy label* property.
. Upload the PDF file of the product data sheet to the *Product data sheet* property.
. *Save* (icon:save[role="green"]) the settings.

icon:map-signs[] *_Or:_* Instead of linking the *Energy label* property, you can also upload the energy label file to the <<item/managing-items#660, Images>> tab of the item. To do so, proceed as follows.

[.instruction]
Saving the energy label in the "Images" tab:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Images* tab.
. Add the image file of the energy label either via *Select files* or via the drag & drop function.
. *Save* (icon:save[role="green"]) the settings.
. Go to *Setup » Markets » Netto eStores*.
. In the *Settings* tab, enter the image's position number into *Image position for energy label* field (table 1).
. *Save* (icon:save[role="green"]) the settings.

[#950]
=== Creating the property Mandatory unit price

If you do not use the option *Show unit price* to indicate that items need a mandatory unit price (see chapter <<Setting the Show unit price-option, Setting the Show unit price-option>> for further information), you can use a property to indicate that items need to have a unit price. This property overwrites the setting for the *Show unit price* option. +

Go to *Setup » Item » Properties* to create a property for mandatory unit prices.

[.instruction]
Creating a property for mandatory unit prices:

. Go to *Setup » Item » Characteristics*.
. Open the *New property* tab.
. Enter a name in the *Name (internal)* field.
. Select the property type *Selection*.
. Select *Free text* from the *Netto eStores property* drop-down list. +
→ A text box appears.
. Enter *Mandatory unit price* into the text box.
. *Save* (icon:save[role="green"]) the settings.
. In the selection section, add the selection values *yes* and *no* one after another and *save* (icon:save[role="green"]) the settings.

Then link the *Mandatory unit price* property in the *Properties* tab of a Netto eStores item as described below.

[.instruction]
Linking the mandatory unit price-property to a Netto eStores item:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Characteristics* tab.
. Activate the *Mandatory unit price* property that you created.
. *Save* (icon:save[role="green"]) the settings. +
→ The property will be linked to the item and can be viewed in the *Characteristics* section.
. Select *yes* or *no* from the *Selection* drop-down list, depending on whether the item needs a unit price.
. *Save* (icon:save[role="green"]) the settings.

[#1000]
== Automatically sending shipping confirmations

Set up an <<automation/event-procedures#, event procedure>> to automatically send shipping confirmations to Netto eStores when the outgoing items have been booked. The shipping confirmation is automatically sent to Netto eStores when the order changes its status to *[7] Outgoing items booked*. After that, Netto eStores informs the buyer about the shipment of the item.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *Setup » Orders » Events*.
.  Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-shipping-confirmation>> below.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
.  Configure the settings as described in <<event-procedure-shipping-confirmation>> below.
.  Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[event-procedure-shipping-confirmation]]
.Event procedure for automatically sending shipping confirmations to Netto eStores
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Outgoing items booked*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*Netto*, *GartenXXL.de*, and *GartenXXL.at*

|*Procedure*
|*Shipping &gt; Send shipping confirmation to Netto eStores*
|
|====

[#1100]
== Automatically sending cancellations

Set up an <<automation/event-procedures#, event procedure>> to automatically send cancellations to Netto eStores.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *Setup » Orders » Events*.
.  Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-cancellation>> below.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
.  Carry out the settings as described in <<event-procedure-cancellation>> below.
.  Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[event-procedure-cancellation]]
.Event procedure for automatically sending cancellations to Netto eStores
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change &gt; [8] Cancelled*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*Netto*, *GartenXXL.de*, and *GartenXXL.at*

|*Procedure*
|*Payment methods &gt; Send cancellation to Netto eStores*
|
|====

[#1200]
== Automatically sending returns

Set up an <<automation/event-procedures#, event procedure>> to automatically send returns to Netto eStores.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *Setup » Orders » Events*.
.  Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-returns>> below.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
.  Carry out the settings as described in <<event-procedure-returns>> below.
.  Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[event-procedure-returns]]
.Event procedure for sending automatic returns to Netto eStores
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order generation: New return*
|

|*Filter 1*
|*Order &gt; Order type*
|*Return*

|*Filter 2*
|*Order &gt; Referrer*
|*Netto*, *GartenXXL.de*, and *GartenXXL.at*

|*Procedure*
|*Return &gt; Send return to Netto eStores*
|
|====

[#1250]
== Automatically cancelling unpaid orders in plentymarkets after 30 days

Orders which have not been paid by the customer are automatically cancelled at Netto Marken-Discount/GartenXXL.de/GartenXXL.at after 30 days. Use the <<automation/procedure-manager#, procedure manager>> to set up a procedure in order to automatically cancel unpaid Netto Marken-Discount/GartenXXL.de/GartenXXL.at orders in your plentymarkets system after 30 days. This way, reserved stock is released again.

[.instruction]
Setting up a procedure:

. Go to *Setup » Orders » Procedures » Tab: New procedure*.
. Click on the *Settings* tab.
. Place a check mark next to the option *Active*.
. Select a time at which the procedure is to be carried out from the drop-down list *Execute every day at*. We recommend to use *24:00 o clock* for this procedure.
. Enter a name.
. Click on the *Filter* tab.
. Select the filters according to <<unpaid-orders>>.
. Click on the *Procedure* tab.
. Select a status from the drop-down list *Change order status*, e.g. *[8.1] Cancelled by customer*. For further information about the selection of the status, refer to the info box below.
. *Save* (icon:save[role="green"]) the settings.
→ The procedure is created and displayed in the *Procedures* tab.

[TIP]
.Select a status
====
Select a status for the procedure *Change order status* that you have saved within *Setup » Orders » Settings* for the option *Status of cancelled orders (No reservation of stocks)* to cancel reservations. Neither select a status that triggers an event action which reports cancellations to Netto eStores.
====

[[unpaid-orders]]
.Filters for the procedure for automatically cancelling unpaid orders after 30 days
[cols="1,3"]
|====
| Filter | Selection

|*Status*
|*[3] Waiting for payment*

|*Order type*
|*Order*

|*Incoming orders*
|*30 days ago*

|*Order referrer*
|*Netto*, *GartenXXL.de*, and *GartenXXL.at*
|====

[#1350]
== Creating delivery notes and return labels

The following information only applies to delivery notes and return labels for Netto Marken-Discount, GartenXXL.de, and GartenXXL.at. It does not apply to other markets.

[IMPORTANT]
.Invoices are sent by the marketplaces
====
Netto Marken-Discount/GartenXXL.de/GartenXXL.at sends the invoice to the customer. You will receive the customer's delivery address from the marketplaces but not the customer's invoice address. The delivery address supplied by Netto Marken-Discount/GartenXXL.de/GartenXXL.at is saved as the delivery and invoice address in plentymarkets. You send the items to this address.
====

Proceed as follows to create <<orders/order-documents#1700, PDF templates>> for delivery notes and return labels for Netto Marken-Discount, GartenXXL.de, and GartenXXL.at. The following example describes how to create a delivery note for Netto eStores. Afterwards, create a return slip for Netto eStores in the same way. Proceed the same way to create these two documents also for GartenXXL.de and GartenXXL.at. The Netto Marken-Discount, GartenXXL.de, or GartenXXL.at logos must be included in the PDF templates. Request the logos at Netto eStores. +

Download the PDF templates for link:http://www.plentymarkets.eu/documents/category/3507/pdf-template-netto.pdf[Netto Marken-Discount^], link:http://www.plentymarkets.eu/documents/category/3507/pdf-template-gartenXXL-de.pdf[GartenXXL.de^], and link:http://www.plentymarkets.eu/documents/category/3507/pdf-template-gartenXXL-at.pdf[GartenXXL.at^] here.

[.instruction]
Creating a delivery note for Netto eStores:

. Go to *Setup » Client » Select client » Locations » Germany (standard) » Documents » Delivery note*.
. Click on the tab *PDF template*.
. Click on *Add template*. +
→ An editing window opens.
. Select the option *Netto*/*GartenXXL.de*/*GartenXXL.at* from the drop-down list *Payment method*.
. Select a language from the *Language* drop-down list.
. In the line *Template*, click on *Choose template file*.  +
→ Upload the PDF template.
. *Save* (icon:save[role="green"]) the settings.

[IMPORTANT]
.Mandatory document entries
====
The external order number and the external customer number are mandatory on documents that belong to orders with the referrer Netto, GartenXXL.de or GartenXXL.at. You can normally hide these entries by selecting *NO* in the *Template* tab's *Optional elements in the stock unit table* section of the *Setup » Client » Select client » Locations » Germany (standard) » Documents » Delivery note* and/or *Return label* menu. +
For Netto Marken-Discount, GartenXXL.de, and GartenXXL.at, the external order number and the external customer number are not hidden, even if you select the option *NO* here.
====

[IMPORTANT]
.Note will be hidden
====
The text that you can save in the *Note* field in the *Template* tab's *Optional elements in the stock unit table* section of the *Setup » Client » Select client » Locations » Germany (standard) » Documents » Delivery note* and/or *Return label* menu is hidden on documents that belong to the referrers Netto, GartenXXL.de, and GartenXXL.at. This is required by Netto eStores.
====
