= Setting up Restposten.de
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Restposten, Restposten.de, Market, Marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market Restposten.de in your plentymarkets system.
:position: 200
:url: markets/restposten-de
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

link:https://www.restposten.de/?language=english[Restposten.de^] is a pure B2B portal, which means that both sellers and buyers have to be in possession of a valid traders licence (source: Restposten.de). On this page, you will learn how to link the Restposten.de market to your plentymarkets system.

[#100]
== Registering with Restposten.de

You have to register in the Restposten.de link:https://www.restposten.de/register.php[seller portal^] before you can set up Restposten.de in your plentymarkets system.

[#200]
== Creating a user account

Your plentymarkets system is connected to Restposten.de via the SOAP API. In order to gain access, the market requires its own user account with access rights to the API in your plentymarkets system. Go to *System » System settings » Settings » User » Accounts* and create a new user account for Restposten.de with the user class *API*. Furthermore, activate the call *GetCategoryMappingForMarket*. This call ensures that the market will later be able to retrieve your category links.

[.instruction]
Creating a user account for Restposten.de:

. Go to *System » System settings » Settings » User » Accounts*.
. Click on *New*. +
→ The *Create new user* window opens.
. Enter the data.
. Select the user class *API*.
. *Save* (icon:save[role="green"]) the settings. +
→ The user is created.
. Select the user from the list. +
→ An editing window opens.
. Click on the tab *Right » API*.
. Expand the *Item* area.
. Activate the *GetCategoryMappingForMarket* call.
. *Save* (icon:save[role="green"]) the settings.

For further information refer to the <<basics/admin-tasks/manage-users#, Managing user accounts>> page of the manual.

[#300]
== Procuring data

Restposten.de requires the following data from you in order to connect to your plentymarkets system:

* The URL for the SOAP API WSDL +
→ This URL can be found in the *System » System settings » Settings » API » Data* menu under *SOAP WSDL*.
* The user name and password for the user account that you have created for Restposten.de
* Your login details for the Restposten.de. seller portal.

[#350]
== Activating an order referrer

In order to link items, properties etc. with Restposten.de, you have to activate the order referrer Restposten in the menu *System » System settings » Orders » Order referrer*.

[.instruction]
Activating the order referrer for Restposten:

. Go to *System » System settings » Orders » Order referrer*.
. Place a check mark next to the option *Restposten*.
. *Save* (icon:save[role="green"]) the settings.

[#400]
== Setting the item availability

Items have to be available for Restposten.de. This is done in the *Availability* tab of an item within the *Item » Edit item » Open item » Tab: Variation ID* menu.

[.instruction]
Setting the item availability for Restposten.de:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Place a check mark next to the option *Restposten*.
. Place a check mark next to the option *Web API*.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The market is added.
. *Save* (icon:save[role="green"]) the settings. +
→ The item is available on Restposten.de.

The availability for variations can be edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

[#430]
==  Defining SKU manually

Add SKUs manually for specific referrers in the *Item » Edit item » Open item » Tab: Variation ID » Tab: Availability* menu if needed.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Click on the *Availability* tab.
. Click on *Add* (icon:plus-square[role="green"]) in the section *SKU*. +
→ The window *New SKU* is displayed.
. Select the referrer *Restposten*.
. Enter the SKU.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The SKU is saved and displayed.

[#450]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Restposten.de. This price is displayed on Restposten.de.

[.instruction]
Defining a sales price for Restposten.de:

. Open the menu *System » System settings » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *Restposten*.
. *Save* (icon:save[role="green"]) the settings.

[#500]
== Creating properties

Use <<item/managing-items#480, properties>> to link your items to particular characteristics that you need for the market Restposten.de. In order for Restposten.de to be able to retrieve the necessary parameters, the property has to be created with the *property type* set to the option *Selection*. Get in contact with Restposten.de to clarify which values are needed for the property.

[.instruction]
Creating a property for Restposten.de:

. Go to *System » System settings » Item » Properties*.
. Open the *New Property* tab.
. Enter the name in the *Name (internal)* field.
. Select the option *Selection* from the *Property type* drop-down list. +
→ An area opens where you enter the name and description.
. *Save* (icon:save[role="green"]) the settings. +
→ The property is created.
. Open the *Properties* tab.
. Expand the property.
. Enter another name in the next selection field of the *Selection* area.
. *Save* (icon:save[role="green"]) the settings.
. Repeat steps 8 and 9 until all required values are created.
. *Save* (icon:save[role="green"]) the settings.

[#600]
== Linking categories

Link your online store <<item/managing-items#10, categories>> to the Restposten.de categories in order to display your items in these categories. Further items from the linked category are assigned automatically.

[.instruction]
Linking categories:

. Go to *System » System settings » Markets » Restposten*. +
→ The *Category link* tab is displayed.
. Expand the category which you want to link to a Restposten category.
. Select a main category for Restposten from the drop-down list. +
→ A window with subcategories opens.
. Select the appropriate Restposten category from the subcategories that appear. +
→ The category path is displayed in the field *Category*.
. Click on *Accept*. +
→ The category window is closed.
. *Save* (icon:save[role="green"]) the settings.

[IMPORTANT]
.Link to the lowest category level
====
Always select a path to the lowest level. Otherwise, the item will not be linked.
====

[.subhead]
Returns

For returns, you have to create an order with the type return, not credit note. It is also important to specify each individual item's value as a percentage. This is done within the return's stock units tab.
