= Yatego
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Yatego, Market, Marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market Yatego in your plentymarkets system.
:position: 220

With plentymarkets you can offer your items on the link:http://www.yatego.com/[Yatego.com^] sales platform. Yatego offers sellers extensive services with powerful, complete solutions as well as comprehensive technical support.

[#100]
== Registering with Yatego

Register with link:http://www.yatego.com/doc,yategoverkaufen[Yatego.com^] to receive your access data. You need this data for the settings in plentymarkets.

[#200]
== Setting up Yatego in plentymarkets

Once you have registered with Yatego, use the access data that is saved there to set up the market in plentymarkets. To do so, proceed as follows.

[.instruction]
Setting up Yatego in plentymarkets:

. Go to *System » Markets » Yatego » Settings*.
. Expand the *Settings* section.
. Carry out the settings. Pay attention to the explanations given in table 1.
. *Save* the settings.

.Basic settings for the market Yatego
[cols="1,3"]
|====
|Setting |Explanation

|*User name (Yatego store name)*
|Enter the *user name* for logging in to Yatego.com.

|*Password*
|Enter the *password* for logging in to Yatego.com.

|*Item image size*
|Select *Item image (standard)*, *Medium-sized item image* or *Preview image*.

|*Item name*
|Select *Name 1*, *Name 2* or *Name 3*. The names are entered in the *Texts* tab of an item.

|*Shipping costs*
|*Add up shipping charges for each item* = For every item, plentymarkets transfers the shipping costs (domestic) that are valid for the online store. If a customer purchases two items on Yatego, then the shipping charges of the individual items are added up. In addition, the shipping costs that are saved in Yatego are added to the shipping costs that were transferred by plentymarkets. +
*Add up, but only once for multiple copies of the same item* = plentymarkets also transfers the shipping costs (domestic) that are valid for the online store. The shipping charges are added when purchasing various items. When purchasing two or more of the same item, the shipping charge is only calculated once. Finally, this is also added to the extra shipping charges saved for Yatego. +
*Use Yatego table of shipping charges based on the item weight* = plentymarkets does not transfer any shipping costs to Yatego. Based on the weight which is saved in plentymarkets and which is also transferred to Yatego, Yatego calculates the shipping costs itself.

//|*Client for the item export*
//|Select the *standard online store*, a *client (store)* or the option *ALL*, depending on which online store you want to use for the item export.

//|*Client for the order import*
//|Select the *standard online store* or a *client (store)* for the order import.

|*Sorting of variations*
|Select *Alphabetical*, *Surcharge* or *No sorting*.

|*Transfer RRP*
|*Yes* = Transfer value for RRP, if an *RRP* for Yatego items is entered. +
*No* = Do not transfer a value for RRP.

|*Automatic upload (daily)*
|Activate in order to automatically transfer item data to Yatego each day.

|*Sold out variations*
|*Visible* = Variations that are sold out are displayed on Yatego. +
*Invisible* = Variations that are sold out are not displayed on Yatego.

|*Yatego properties*
|*Do not export* = Properties are not exported to Yatego. +
*Place in the upper part of the description* = Place properties for Yatego items in the upper part of the description. +
*Place in the lower part of the description* = Place properties for Yatego items in the lower part of the description.

|*Free text fields 1 to 20*
|*Do not export* = Free text fields are not exported to Yatego. +
*Place in the upper part of the description* = Place the text for Yatego items in the upper part of the description. +
*Place in the lower part of the description* = Place the text for Yatego items in the lower part of the description. +
*Export in a separate column* = Export the property in a separate column of the CSV file during the item export. +
*Note:* This function is still supported only for customers who already use the free text field functions in the Yatego settings. New customers are requested to use the following two options.

|*Yatego warehouse rights*
|Select *Exactly* or *Simply* if you manage stock with the values -1, 0, 1 or 2.

//tr>
//<td>&nbsp;</td>
//<td><strong>YATEGO package type (valid until plentymarkets version 4,306)</strong>:<br />
//The <strong>Standard</strong> setting provides no information about cross-selling in the item export file. Die Auswahl <strong>Standard</strong> bzw. <strong>Professional</strong> entfällt ab Version 4.400, da es keine gesonderten Tarife bei Yatego mehr gibt.</td>
//</tr

|*Item description*
|Select *Standard description*, *Technical data* or *Both*.

|*Short item description*
|Select whether the *preview text* or the *technical data* should be used as the short item description on Yatego.

|*Warehouse*
|Select own warehouse, *Main item warehouse* or *Transfer stock quantity of distribution warehouse that currently has the largest stock*.

|*Are you sure you want to delete all item images before importing from the Yatego shop?*
|*Yes* = All item images that are currently available on Yatego are deleted when importing new images for these items. This prevents errors when importing images. If you do not delete the old images, Yatego does not replace the old image with the new one if they have the same file name. +
*No* = Do not delete item images before the import.

|*Status for all credit card orders*
|Select *status 3* (waiting for payment) or *status 5* (cleared for shipping).

|*Set all credit card orders in status 5 to booked*
|Select whether credit card orders in status 5 should be set to booked or not.

|*Status for all Sofortbanking orders*
|Select *status 3* (waiting for payment) or *status 5* (cleared for shipping).

|*Set all Sofortbanking orders in status 5 to booked*
|Select whether Sofortbanking orders in status 5 should be set to booked or not.

|*Status for all PayPal orders*
|Select *status 3* (waiting for payment) or *status 5* (cleared for shipping).

|*Set all PayPal orders in status 5 to booked*
|Select whether PayPal orders in status 5 should be set to booked or not.

|*Transfer item URL*
|Select whether the item URL should be transferred or not.

|*Use all of the images (max. 5) from the long description as the item images*
|Select whether all item images belonging to an item should be used or not. A maximum of 5 images can be used.

|*Transfer online store categories*
|Select *All*, *Only the default category*, or *No*. +
 The *Default category* is selected in the *Categories* tab of an item. If you select the option *Only the default category* for Yatego, then check which default category was saved for the item in its *Categories* tab. If you did not select a category there, then the *default category* is automatically selected. If you have multiple category links, then the first category link is treated as the default category.

|*Online store category levels*
|Select which *category levels* you wish to transfer. You can select any 3 consecutive levels. Note that all the levels must be set up and linked for all of the relevant Yatego items.
|====

[#250]
== Activating an order referrer

In order to link items, properties etc. with Yatego, you have to activate the order referrer Yatego in the menu *System » Orders » Order referrer*.

[.instruction]
Activating the order referrer to Yatego:

. Go to *System » Orders » Order referrer*.
. Place a check mark next to *Yatego*.
. *Save* the settings.

[#300]
== Setting the item availability

Items have to be available for Yatego. This is done in the *Availability* tab of an item within the <<en/item/managing-items#40, Item » Edit item » Open item » Tab: Variation ID>> menu.

[.instruction]
Setting the item availability for Yatego:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Place a check mark next to the option *Yatego*.
. Place a check mark next to the option *Web API*.
. Click on *Add*. +
→ The market is added.
. *Save* the settings. +
→ The item is available on Yatego.

The availability for variations can be individually edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

[#350]
==  Defining SKU manually

Add SKUs manually for specific referrers in the menu <<en/item/managing-items#170, Item » Edit item » Open item » Tab: Variation ID » Tab: Availability>> if needed.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
.  Click on the *Availability* tab.
.  Click on *Add* in the section *SKU*. +
→ The window *New SKU* is displayed.
.  Select the referrer *Yatego*.
.  Enter the SKU.
.  Click on *Add*. +
→ The SKU is saved and displayed.

[#400]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Yatego. This price is displayed on Yatego.

[.instruction]
Defining a sales price for Yatego:

. Open the menu *System » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *Yatego*.
. *Save* the settings.

[#500]
== Linking categories

First, import the official Yatego categories.

[.instruction]
Importing Yatego categories:

. Go to *System » Markets » Yatego » Category link*.
. Click on *Update Yatego categories*. +
→ The Yatego categories appear in the *Category link* area.

Link your online store categories to the Yatego categories in order to display your items in these categories. Further items from the linked categories are assigned automatically.

[.instruction]
Linking categories:

. Go to *System » Markets » Yatego » Category link*.
. Click on the *gear-wheel icon* under *Yatego link*.
. Select a category in the *Official Yatego categories* section. +
→ *_Or:_* Enter the category ID under *Yatego category ID link*.
. *Save* the settings.

Then export your online store categories in Yatego format.

[.instruction]
Exporting online store categories in Yatego format:

. Go to *System » Markets » Yatego » Category link*.
. Click on *Export online store categories*. +
→ A new window opens.
. Click on *OK* to save the CSV file.
. Import the CSV file at Yatego. +
→ The online store categories are now available at Yatego.

[#600]
== Linking properties

Link your <<en/item/managing-items#480, properties>> with the Yatego properties. To do so, proceed as follows.

[.instruction]
Linking properties:

.  Go to *System » Item » Properties*.
.  Expand a property.
.  Place a check mark next to the option *Yatego*.
. *Save* the settings.

[#700]
== Automatically transmitting items

Go to *System » Markets » Yatego » Settings* to carry out the item exchange with Yatego. The functions in this menu are only available after having entered the access data, as described above. The preview function allows you to check the data before the transfer takes place. The Yatego import can take a long time. plentymarkets has no control over this.

In order to ensure a smooth item export, make sure that the access data for the Yatego shop are correct and valid.

[WARNING]
.*Full Yatego import*
====
With plentymarkets, you always need to transfer entire data sets to Yatego. This means that all items already existing in Yatego have to be deleted before a new import is carried out. If you already have items in your Yatego account, make sure that you create the same items in plentymarkets first before you allow for the items to be exported to Yatego.
====

[.instruction]
Transmitting items to Yatego:

. Go to *System » Markets » Yatego » Settings*.
. Expand the sub-menu *Item exchange yatego.com (FTP)*.
. Click on the corresponding *preview icon* to check the data that will be made available as a CSV file.
. After checking the data, click on *Transmit data* to transfer the data to Yatego.

[#800]
== Importing orders

Orders are transferred directly from Yatego if the plentymarkets system with an SSL certificate was booked. The transfer of orders from Yatego to plentymarkets takes place with an encoded connection only. An SSL certificate is necessary for this. If no SSL certificate was booked, this has to be done retrospectively.

[TIP]
.Tip: Book SSL certificate
====
To book an SSL certificate in the Service centre, go to *plentymarkets logo » Service centre* in your plentymarkets system. You can book the SSL certificate in the *Domain* tab.
====

////
p>Liegt ein SSL-Zertifikat vor, müssen im Yatego-Backoffice nur noch einige Einstellungen unter <strong>yatego.com &gt; Bestellungen &gt; Bestellanbindungen</strong> vorgenommen werden (siehe Bild 4) und zukünftig eintreffende Aufträge werden in plentymarkets übertragen. Achten Sie darauf, dass die richtige URL inkl. <b>https://</b> eingegeben wird (also: <b>https://www.mein-shop.de/</b>).</p>

<div class="plentyInfoBox plentyIsWarning"><div class="plentyInfoBoxHeader"><strong>Artikelexport weiterer Webshops</strong></div>
<div class="plentyInfoBoxContent">Wird der Artikelexport für einen weiteren Webshop (Mandanten) eingerichtet, sind für den Auftragsimport trotzdem die <strong>Zugangsdaten</strong> (<strong>URL</strong> mit <strong>SSL</strong>-Zertifikat und <strong>WebToken</strong> aus den plenty API Daten) des <strong>Hauptsystems</strong> zu hinterlegen. (WebToken = <u>nicht PlentyToken</u>)</div></div>

<div class="plentyInfoBox plentyIsImportant"><div class="plentyInfoBoxHeader"></div>
<div class="plentyInfoBoxContent">Den <strong>Web-Token</strong> finden Sie in plentymarkets im Menü <b>Einstellungen &gt; Grundeinstellungen &gt; API-Daten</b> und dort unter <strong>WebToken</strong>.</div></div>

<div class="plentyInfoBox plentyIsWarning"><div class="plentyInfoBoxHeader"><strong>Versandbestätigung</strong></div>
<div class="plentyInfoBoxContent">Es erfolgt keine automatische Versandbestätigung an Yatego. Der Auftrag muss manuell direkt bei Yatego bestätigt werden.</div></div
////

[#900]
== Activating the payment method

Activate the <<payment/managing-payment-methods#, payment method>> *Yatego invoice* as described below.

[.instruction]
Activating the payment method Yatego invoice:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the option *Also show inactive*.
. Click on the folder *DE &gt; Yatego invoice*. +
→ The settings for the Yatego payment method are displayed.
. Carry out the settings. Pay attention to the explanations given in table 2.
. Place a check mark next to the option *Active*.
. *Save* the settings.

.Settings for the payment method
[cols="1,3"]
|====
|Setting |Explanation

|*Language*
|The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo* and *Upload logo*. This makes it possible to enter values for these options in various languages. The values for a language are activated as soon as a buyer selects the language in the online store.

|*Name*
|Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
|Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
|If you have selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
|Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely set up.

|*Logo*
|Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

|*Logo view*
|If *Show upload logo* has been selected from the *Logo* drop-down list, then the logo that has been uploaded is displayed here.

|*Upload logo*
|If *Show upload logo* has been selected from the *Logo* drop-down list, upload an external logo here. +
 Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|*Priority*
|Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
|If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. *Important*: Do not enter a value into both fields.  +
For further information, refer to the <<en/basics/statistics#, Statistics>> page of the manual.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *System » CRM » Classes* to activate or deactivate *Permitted payment methods*. +
For further information, refer to the <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter.
====

For further information, refer to the <<payment/managing-payment-methods#, Payment methods>> page of the manual.

[#1000]
== Viewing the API log

The menu *Data » API log » Tab: API log* contains a history of processes that run via the Yatego interface. The following formats are available for Yatego:

* *Yatego(new)* (item catalogue, variations, attributes)
* *OrdersYatego* (order import)
* *Writer_OrdersYatego_Execution* (export)

[.instruction]
Viewing the API log:

. Go to *Data » API log » Tab: API log*.
. Select a format from the drop-down list *Process*.
. Select a date if you only want to see entries for a specific day.
. Click on *Search* to carry out the search. +
→ The processes are displayed.
. Click on the folder in the *Process* column.  +
→ The *Yatego* tab opens and error messages for this process are displayed.

[#1100]
== FAQ

[.instruction]
How does plentymarkets transmit items that are not limited to stock to Yatego?

[.indented]
All items that are set to *No limitation* are transferred to Yatego. This setting is found by opening an item and clicking on the *Tab: Stock » Tab: Settings*. The setting is found in the *Limitation* line. plentymarkets will send a value of -1 for these items, so that Yatego knows that these items can be bought without limitation.

[.instruction]
Can I manually import orders from Yatego to plentymarkets?

[.indented]
Yes. If a Yatego order is manually transferred to plentymarkets from Yatego, then Yatego does not send an item ID or variation ID (attribute_value_set_id). This will make it impossible for the item to be assigned and the item will be imported with the item ID "-2" (unknown item). Unassigned items are flagged by a *green plus* icon in the order. The item then has to be assigned manually.

[.instruction]
How do I know that the purchaser has already paid the order?

[.indented]
Yatego neither sends a transaction ID for payments nor other information that indicates whether the order was paid for or not. Therefore, the Yatego settings include an option that allows you to set orders to be booked for some payment methods: *Set all orders in status 5 to booked*. Select this option if the payment method ensures that payment was already made when the order is booked.

[.instruction]
The link for the item in the order does not work. What can I do?

[.indented]
Yatego sends a link for the orders, which directly connects to the item on the Yatego platform. Usually, this link doesn't work, since Yatego adds "yatego.com" to the name of the online store. Delete "yatego.com" from the link and then it will work correctly. +
*Example*: http://www.yatego.com/SHOPNAME.yatego.com/p,4fcaaf8c8292c,461e2919becf22_4 +
*The correct format is*: http://www.yatego.com/SHOPNAME/p,4fcaaf8c8292c,461e2919becf22_4

[.instruction]
I set up Yatego in plentymarkets. Why are my orders not transferred?

[.indented]
The first time that an online store activates the Yatego order process for plentymarkets, it is common that the first two to three orders will not be automatically transferred to plentymarkets. These orders have to be manually triggered again from within the Yatego system.

[.instruction]
I would like to offer an item with attributes. Why does Yatego not display the stock correctly?

[.indented]
Yatego is not able to process the warehouse data records that plentymarkets sends for items if there are more than 999 possible combinations of attributes. As such, all possible combinations of variations are activated for the item and set to endless stock (meaning that stock doesn't exist for Yatego). If you need to use a large number of attributes, contact Yatego before exporting the corresponding items.

[.instruction]
Why does Yatego not immediately edit the CSV files I transferred?

[.indented]
The CSV files that are transferred to Yatego each day are not imported and edited immediately, but rather have to wait in line to be processed. Therefore, the import and editing process can take several hours. You can go to Yatego and check where your file is in line.
