= Zalando
:lang: en
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: Zalando, market, marketplace, marketplace Zalando, setting up Zalando, Zalando setup, multichannel, multi-channel, multi channel, multi-channel Zalando
:description: Multi-Channel in plentymarkets: Set up the interface to the market Zalando in your plentymarkets system.
:position: 250
:url: markets/zalando
:id: H1AGZUB

Thanks to the Zalando partner programme, online sellers and manufacturers can use Zalando as an additional distribution channel for selling their high-quality products and take advantage of the well-known brand name Zalando.

[#100]
== Registering with Zalando

If you are interested in the link:https://www.zalando.co.uk/partner-programme/[partner programme^]{nbsp}icon:external-link[], then contact Zalando directly.

[[contact-person]]
.Contact person
[cols="1,3"]
|====
|Contact person |Email address

| *Zalando partner programme team*
|link:mailto:partner-programme@zalando.co.uk[partner-programme@zalando.co.uk^]{nbsp}icon:external-link[]
|====

[#200]
== Setting up Zalando in plentymarkets

As soon as Zalando has accepted you into their partner programme, you will receive a user guide from Zalando which helps you setting up the interface. In plentymarkets, carry out the following basic settings.

[.instruction]
Setting up Zalando in plentymarkets:

. Go to *Setup » Markets » Zalando » Settings*. +
→ The *Settings* tab opens.
. Carry out the settings as described in <<#basic-settings-zalando>>.
. *Save* (icon:save[role="green"]) the settings.

[[basic-settings-zalando]]
.Basic settings for the market Zalando
[cols="1,3"]
|====
|Setting |Explanation

2+|Basic configuration

| *User*
|Select the API user. The account for the API user is created during the initial setup.

| *Item name*
| Select *Name 1*, *Name 2* or *Name 3*.

| *Assignment client (store)*
|Select a client (store).

| *Warehouse selection*
a|Select a warehouse. +

* *Transfer stock quantity of distribution warehouse that currently has largest stock* = Select the distribution warehouse that currently has the largest stock of the item. +
* *Use the item's main warehouse* = Select the main warehouse of the item. +
* *Transfer sum of stock quantities from all distribution warehouses* = Stock of all distribution warehouses is added and transferred as sum.

2+|Advanced options

| *Stock buffer*
|Enter the stock buffer in units.

| *Quantity for items that are not limited to the stock*
|Enter the quantity for items that are not limited to stock.

| *Maximum for item upload*
|Enter a number to determine the limit value for the item upload in units per item.

| *Standard tax rate*
| Select *19%* or *7%*.

| *Reduced tax rate*
| Select *19%* or *7%*.
|====

Connecting to this market allows for the following automatic functions to take place:

* Daily item export

[#250]
== Activating the order referrer

:market: Zalando
:referrer: Zalando
:referrer-option: pass:quotes[option *Zalando*]

include::_textblocks/instructions/activate-referrer.adoc[]

[#300]
== Setting the variation availability

:market-availability: Zalando
:option-availability: Zalando

include::_textblocks/instructions/variation-availability.adoc[tags=availability;web-api;!*]

// Web API required!

[#330]
== Defining SKU manually

:referrer-sku: Zalando

include::_textblocks/instructions/sku-manually.adoc[]

// Marketplace account not required!

[#350]
== Defining a sales price

:referrer-price: Zalando

include::_textblocks/instructions/define-sales-price.adoc[]

[#1100]
== Preparing variations

Zalando specifies some mandatory information. That means that a variation can be exported to the market if this mandatory information is saved for the variation. The information listed in <<#zalando-variations-mandatory>> must be saved for all variations that you want to export to Zalando.

[[zalando-variations-mandatory]]
.Mandatory fields for the variation
[cols="1,3"]
|====
|Mandatory data |Explanation

| EAN
a| An EAN must be saved for the variation.

* In the *Setup » Item » Barcode* menu, an EAN must be created and linked to the referrer Zalando.
* The EAN must be added to the *Settings* tab of the variation in the *Barcode* area and a barcode code must be entered.

| Technical data
a| Technical data must be saved for the item.

* In the *Texts* tab of the item, text must be saved in the *Technical data* field.

| Images
a| An image must be saved for the variation.

* in the *Images* tab of the item, the option *Zalando* must be selected from the drop-down list *Availability*.

| Price
a| A price must be saved for the variation.

* The sales price must be activated for the referrer Zalando in the *Setup » Item » Sales prices*.
* The sales price must be added in the *Settings* tab in the *Sales price* area of the variation.
* A price must be saved for the sales price.
|====

[#400]
== Linking categories

Link your online store categories to the Zalando categories in order to display your items in these categories. Further items from the linked category are assigned automatically.

[.instruction]
Linking categories:

. Go to *Setup » Markets » Zalando » Category link*.
. Select a category under *Zalando category*.
. *Save* (icon:save[role="green"]) the settings.

[#500]
== Converting silhouettes to characteristics

In the *Setup » Markets » Zalando » Settings » Tab: Silhouettes* menu, you convert Zalando silhouettes to item characteristics. Silhouettes are transferred when Zalando is first set up.

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Silhouettes* tab.
. Select the *Groups* for the characteristics that you want to convert.
. *Save* (icon:save[role="green"]) the settings. +
→ The characteristics are created in your plentymarkets system.

[#600]
== Exporting Zalando item characteristics

You can export the silhouettes that you saved in the *Groups* area.

[.instruction]
Exporting Zalando item characteristics:

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Silhouettes* tab.
. Click on *Export Zalando item characteristics*. +
→ A file containing the characteristic parameters is exported.
. Open the file.
. Carry out the settings. Pay attention to the explanations given in <<#zalando-characteristics>>.
. *Save* (icon:save[role="green"]) the settings.

[[zalando-characteristics]]
.Values for Zalando characteristics
[cols="1,3"]
|====
|Column |Explanation

| *Group name*
|Names of the characteristic groups.

| *Silhouette*
|Values of all silhouettes.

| *Characteristics ID*
|Enter the ID of the online store characteristic. The characteristic ID can be found in the *Setup » Item » Characteristics* menu.

| *Characteristics type*
a|Enter the characteristic type. The following entries are possible: +

* *empty* = Enter this value if the characteristic is not used. If the characteristic is used, *empty* must be replaced by *1*. +
* *text* = Enter the value in text form, e.g. "Red” for colour. +
* *int* = Enter a number, e.g. the heel height. +
* *selection* = Enter the option’s selection ID from the drop-down list. You find the selection ID for the characteristics of the type *Selection* in the *Setup » Item » Characteristics* menu under *Selection ID*.

| *Mandatory entry*
|If a cell contains the value *1*, the characteristic must be transferred. Characteristics may also contain the value *1* because links to other selected characteristics exist. Observe the documentation provided by Zalando.

| *Language*
| Enter *de* in the lines that you use. Currently, only German is available.
|====

[discrete]
=== Linking characteristics to items

Link the Zalando characteristics to the items in your plentymarkets system.

To export your variations to Zalando, link at least the following mandatory characteristics:

* 1. Farbcode (colour code)
* Altersgruppe(n) (age group(s))
* Geschlecht
* Größenregister (size list)
* Hersteller-Code (manufacturer code)
* Herstellerfarbe (manufacturer colour)
* Jahreszeiten-Code (Seasonal code)
* Silhouetten-Typ (silhouette type)

[.instruction]
Linking a characteristic to an item:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Characteristics* tab.
. Activate the characteristic in the *Activate further characteristics* area.
. *Save* (icon:save[role="green"]) the settings. +
→ The characteristics are displayed in the *Characteristics* area.
. *_Optional:_* Carry out additional settings. Pay attention to the explanations regarding <<item/managing-items#80, characteristics>>.
. *Save* (icon:save[role="green"]) the settings.

[#700]
== Linking attributes

If you have created attributes in your plentymarkets system, link these attributes with Zalando. The following example describes how you can link the attribute “colour” with Zalando. Link further attributes in the same way.

[.instruction]
Linking the attribute “colour”:

. Go to *Setup » Item » Attributes*. +
→ An overview of all existing attributes opens.
. Open the attribute *colour*.
. Click on the *Market variation* tab.
. From the *Market* drop-down list, select the option *Zalando*. +
→ The *Zalando* drop-down list is displayed.
. From the *Zalando* drop-down list, select the attribute *colour*.
. *Save* (icon:save[role="green"]) the settings.

[#800]
== Activating the payment method

:paymentmethod: Zalando Payment
:folder: International

include::_textblocks/instructions/activate-payment-method.adoc[tags=!real-name;!real-client]

[#850]
== Order status changes

When an order status changes, this information is not transferred to Zalando via event procedures, but retrieved automatically via an interface. The following statuses are transferred to Zalando: shipping confirmation, cancellation, and return.

The order statuses shipping confirmation, cancellation, and return are sent to Zalando if the following criteria are fulfilled:

* *Shipping confirmation:* The outgoing items have been booked. In addition, a return label was created and package numbers were added.

* *Cancellation:* The order moved to *status [8.X]* or the quantity of an order item is *0*.

* *Return:* A return was created in plentymarkets.

[#900]
== Retrieving reports

Go to the *Setup » Markets » Zalando » Settings » Tab: processing reports* menu to download the following reports for Zalando:

[cols="1,3"]
|====
|Report |Explanation

| *Export-Log*
a| The export log contains log entries for variations that could not be exported to Zalando. The report is generated once every night.

| *Product status reports*
a| The product status reports are created by Zalando. As such, these reports only contain information regarding variations that were successfully exported to Zalando.

* *_ProductErrorReport.csv_*\: Contains variations that can currently not be sold on Zalando. The report also contains the first five error codes and an error description. The report is generated once every night. Click on *Update file* (icon:cog[]) to get current data from Zalando before downloading the file.
* *_ProductLiveReport.csv_*\: Contains variations that can currently be sold on Zalando. The report also contains information on the stock and price of the variations on the different Zalando channels (DE, FR, etc.) at the time the file was generated. The report is generated once every night. Click on *Update file* (icon:cog[]) to get current data from Zalando before downloading the file.

|====

[#905]
=== Retrieving the export log

The export log contains plentymarkets log entries for items that could not be exported to Zalando.

[.instruction]
Retrieving the export log:

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Processing reports* tab.
. In the *Export log* area, click on *Download file* (icon:eye[role="blue"]). +
→ The CSV file is created.
. Save the CSV file on your computer.

[#910]
=== Retrieving product status reports

Product status reports contain information regarding the items that were exported to Zalando.

[.instruction]
Retrieving a product status report:

. Go to *Setup » Markets » Zalando » Settings*.
. Click on the *Processing reports* tab. +
→ The following files can be downloaded in the *Product status reports - Account ID* area:

  * *_ProductErrorReport.csv_* contains the variations that cannot be sold on Zalando since the last export.
  * *_ProductLiveReport.csv_* contains the variations that can be sold on Zalando since the last export.

. *_Optional:_* By default, the file is updated once every night. To get current data from Zalando before downloading the file, go to the *Product status-reports - Account ID* area and click on *Update file* (icon:cog[]).
. Go to the *Product status reports - Account ID* area. In the row of a processing report click on *Download file* (icon:eye[role="blue"]). +
→ The CSV file is created.
. Save the CSV file on your computer.

[#1000]
== Viewing the API log

The *Data » API log* menu contains a history of processes that run via the Zalando interface. The *ZalandoController* format is available for Zalando.

[.instruction]
Viewing the API log:

. Go to *Data » API log » Tab: API log*.
. Select the *ZalandoController* format from the *Process* drop-down list.
. Select a date if you only want to see entries for a specific day.
. Select the number of results per page.
. Click on *Search* (icon:search[role="blue"]) to display the results.
