= Affiliate
:lang: en
include::{includedir}/_header.adoc[]
:position: 50

**Settings » Client (store) » Standard » Affiliate**

== Affiliate marketing

Affiliate marketing is a type of marketing practice that is based on commission. There are specialized companies for these marketing channels, which not only arrange for your item to be linked to partner websites but which also deal with the commission process. In this section, you will find information about the corresponding interfaces. As such, these affiliate marketing systems support the commercialization of your item at a reasonable price: You only pay for measurable results, i.e. for sales that were actually generated.

The most prevalent compensation methods are:

* Pay-per-Click (PPC)
* Pay-per-Lead (PPL)
* Pay-per-Sale (PPS)

As such, affiliate partners create the basis for a form of cooperative internet marketing or sales. Instead of placing individual banners on advertising platforms, you can create virtual networks with the help of an affiliate provider and then offer and sell your items on other websites.

== Important terminology

To help you understand the concept of affiliates, we have collected definitions of some of the terms commonly used:

* **Advertiser/merchant**: Store owner who registers with the affiliate network
* **Publisher**: Advertising medium, which carries out the banner advertising or the link
* **Tracking**: URL record of a visitor who clicks on or buys the advertiser's offer

== Affiliates in plentymarkets

You can set up and use the following affiliates in plentymarkets.

* <<marketing/affiliate/affilinet#, **affilinet**  >>
* <<marketing/affiliate/belboon#, **belboon**  >>
* <<marketing/affiliate/criteo#, **Criteo**  >>
* <<marketing/affiliate/redpeppix#, **redpeppix.**  >>
* <<marketing/affiliate/trade-doubler#, **Trade Doubler**  >>
* <<marketing/affiliate/zanox#, **zanox**  >>

