= Externe Rabattseiten
:lang: de
include::{includedir}/_header.adoc[]
:description: Nutzen Sie die Möglichkeit in Ihrem Onlineshop, Gutscheine für Ihre Artikel auf externen Rabattseiten, wie z.B. Groupon anzubieten.
:position: 70

Gutscheine sind ein beliebtes Marketing-Instrument in Webshops. Nutzen Sie auch die Möglichkeit, Gutscheine für Ihre Artikel auf externen Rabattseiten, z.B. Groupon (www.groupon.de), anzubieten. Auf dieser Handbuchseite werden die Schritte zur Bereitstellung von Gutscheinen auf externen Rabattseiten erläutert.

== Neue Kategorie anlegen

Im ersten Schritt legen Sie eine Kategorie für die Gutschein-Aktion an. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Eine neue Kategorie anlegen:

. Öffnen Sie das Menü **<<artikel/kategorien/kategorien-bearbeiten#, Artikel » Kategorien>>**.
. Legen Sie eine neue Kategorie des Typs **<<artikel/kategorien/kategorietyp-content-bearbeiten#, Content>>** an.
. Wechseln Sie in das Tab **Beschreibung 1**.
. Wählen Sie in der Dropdown-Liste rechts die Option **Syntax-Editor**.
. Fügen Sie den unten aufgeführten Beispiel-Code für ein Formular in das Textfeld ein.
. Passen Sie den Beispiel-Code gemäß Tabelle 1 an.
. **Speichern** Sie die Einstellungen.

Nachfolgend finden Sie einen Beispiel-Code für ein Formular. Nehmen Sie die Anpassungen gemäß Tabelle 1 vor, bevor Sie den Beispiel-Code produktiv nutzen.

[source,plenty]
----
include::assets/EX-DE-form.html[]

----

Um das Formular an Ihre Anforderungen anzupassen, nehmen Sie die in Tabelle 1 beschriebenen Ersetzungen vor.

[cols="1,3"]
|====
|Code |Erläuterungen

|&lt;input name="BuyParamId" value="xxx" type="hidden"&gt;
|"xxx" durch die Preis-ID aus dem Preis-Tab des Artikels ersetzen, für den Gutscheine auf externen Rabattseiten angeboten werden.

|&lt;input name="BuyParam$ReferrerId" value="1" type="hidden"&gt;
|Die Referrer-ID Ihres Webshops eingetragen. Diese ist standardmäßig 1. Dieser Wert ist bereits eingetragen. Wenn der Webshop eine andere Referrer-ID hat, "1" durch diese Referrer-ID ersetzen.

|&lt;input name="BuyParam$ContentPage" value="xxx" type="hidden"&gt;
|"xxx" durch die ID der Kategorie ersetzen, auf der das Beispielformular eingefügt wird.

|&lt;input name="BuyParam$ArticleId" value="xxx" type="hidden"&gt;
|"xxx" durch die ID des Artikels ersetzen, für den Gutscheine auf externen Rabattseiten angeboten werden. +
**Hinweis:** Die Funktion ist nicht für Artikelpakete geeignet. Daher keine Artikelpaket-IDs eintragen.
|====

__Tab. 1: Ersetzungen im Code-Beispiel__

== Eine Gutscheinkampagne anlegen

Da jeder Gutschein einer Kampagne angehört, legen Sie im nächsten Schritt wie unten beschrieben eine Gutscheinkampagne an.

[.instruction]
Neue Gutscheinkampagne anlegen:

. Öffnen Sie das Menü **<<auftragsabwicklung/auftraege/gutscheine#, Aufträge » Gutscheine>>**.
. Erstellen Sie eine neue **<<auftragsabwicklung/auftraege/gutscheine#, Kampagne>>**.
. Nehmen Sie für diese Kampagne die in Tabelle 2 beschriebenen spezifischen Einstellungen vor.
. **Speichern** Sie die Einstellungen. +
→ Die Kampagne wird angelegt und im Tab **Kampagnen** angezeigt.

[cols="1,3"]
|====
|Option |Erforderliche Einstellung

|**Konzept**
|Dropdown-Liste 1: **Mehrere Codes** +
Dropdown-Liste 2: **Eine Einlösung pro Kunde**

|**Rabattart**
|**Festbetrag**

|**Rabattwert**
|Höhe des Rabatts eingeben. +
**Tipp:** Soll auch der Versand kostenlos sein, die Option **inkl. Versandkosten** wählen und die Versandkosten des Artikels zu dem Rabattwert addieren. +
Wenn für den Artikel mehrere Versandarten zur Verfügung stehen, den Preis der Versandart mit der höchsten Priorität wählen. Bei Auswahl einer anderen Versandart kann es dabei sein, dass der Kunde geringe Kosten hat. Alternativ die Versandeinstellungen des Artikels ändern, so dass nur eine Versandart angeboten wird.

|**Artikel**
|IDs der Artikel eintragen, für die der Gutschein angeboten werden soll.
|====

__Tab. 2: Einstellungen für eine Kampagne auf externen Rabattseiten__

== Gutschein-Codes erzeugen

Erzeugen Sie nun die erforderlichen Gutschein-Codes. Gutschein-Codes können <<auftragsabwicklung/auftraege/gutscheine#10, **manuell generiert oder manuell eingetragen**>> werden.

== Zahlungsart Coupon konfigurieren

Konfigurieren Sie nun die Zahlungsart **Coupon**, damit Kunden die Gutscheine tatsächlich in Ihrem Shop einlösen können.

[.instruction]
Zahlungsart Coupon konfigurieren:

. Öffnen Sie das Menü **<<auftragsabwicklung/payment/zahlungsarten-verwalten#, System » Aufträge » Zahlung » Zahlungsarten>>**.
. Öffnen Sie die Zahlungsart **Coupon**.
. Setzen Sie ein **Häkchen** bei **Zahlungsart aktiv**.
. Wählen Sie die Lieferländer basierend auf der externen Rabattseite, auf der Sie die Gutscheine anbieten.
. **Speichern** Sie die Einstellungen.

== Gutschein-Codes an externe Rabattseite übergeben

Sie übergeben nun die Gutschein-Codes an die externe Rabattseite. Gehen Sie wie unten beschrieben vor, um eine Datei zu erzeugen, die alle Gutschein-Codes der Kampagne enthält. Diese Datei stellen Sie dann Ihrem Ansprechpartner bei der externen Rabattseite zur Verfügung.

[.instruction]
Gutschein-Codes übergeben:

. Öffnen Sie das Menü **<<auftragsabwicklung/auftraege/gutscheine#, Aufträge » Gutscheine>>**.
. Öffnen Sie die Gutscheinkampagne.
. Öffnen Sie das Tab **Einstellungen**.
. Klicken Sie auf den **grünen Pfeil** direkt unterhalb des Tabs. +
→ Eine Datei wird erzeugt, die alle Codes dieser Kampagne enthält.
. Übergeben Sie diese Datei an Ihren Ansprechpartner bei der externen Rabattseite.

== Link zur Kategorie bereitstellen

Nun stellen Sie den Link zur Kategorie für die externe Rabattseite bereit. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Link zur Kategorie bereitstellen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Öffnen Sie die Kategorie.
. Öffnen Sie das Tab **Einstellungen**.
. Kopieren Sie den Link aus dem Feld **URL**.
. Hinterlegen Sie diesen Link auf der externen Rabattseite oder senden Sie den Link an Ihren Ansprechpartner bei der Rabattseite. Informationen zur genauen Vorgehensweise finden Sie auf den externen Rabattseiten.
