= Installation und Ersteinrichtung
:lang: de
include::{includedir}/_header.adoc[]
:position: 10
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:url: app/installation

Bist du bereits von den <<app#, Vorteilen der plentymarkets App>> überzeugt? Dann verliere keine Zeit und richte jetzt die App auf der passenden Hardware ein.

Auf dieser Seite wird Schritt für Schritt beschrieben, wie du die App einrichtest und welche Aufgaben du vorher noch erledigen musst. Die Einstellungen, die auf dieser Seite beschrieben sind, treten in Kraft, wenn du <<app/funktionen#, die Funktionen der App nutzt>>.

[#100]
== Wahl der richtigen Hardware

Wofür möchtest du die plentymarkets App nutzen? Je nach Anwendungsfall unterscheidet sich die Wahl der passenden Hardware.

Willst du beispielsweise Unternehmenskennzahlen abrufen oder Kunden-, Artikel- und Auftragsdaten suchen? Für diese Funktionen benötigst du lediglich ein mobiles Android- oder iOS-Gerät.

Die plentymarkets App stellt außerdem Funktionen für die mobile Warenwirtschaft sowie das Kassensystem plentymarkets POS bereit. Wenn du diese weiterführende Funktionen nutzen möchtest, empfehlen wir dir ein link:https://www.plentypos.de/[zusätzliches Hardware-Package^] zu buchen.

[#200]
=== Fall 1: Geschäftsdaten verwalten

include::_textblocks/hardware-voraussetzungen/hardware-kennzahlen.adoc[]

[#300]
=== Fall 2: Mobile Warenwirtschaft

include::_textblocks/hardware-voraussetzungen/hardware-wawi.adoc[]

[#400]
=== Fall 3: Kassensystem plentymarkets POS

include::_textblocks/hardware-voraussetzungen/hardware-pos.adoc[]

[#500]
== App herunterladen

include::_textblocks/hardware-voraussetzungen/download-links.adoc[]

[TIP]
.Sind deine Geschäftsdaten auf dem Gerät sicher?
====
Die plentymarkets App ist in dem Sinne geschützt, dass Nutzer sich <<app/installation#1200, mit Zugangsdaten in die App einloggen>> müssen. Da die App aber vertrauliche Geschäftsdaten enthalten kann, solltest du dir ein paar Gedanken zur Sicherheit machen. Dürfen Mitarbeiter die App auch auf ihren privaten Handys nutzen? Werden Endgeräte mit einer Geheimzahl gesperrt? Verschaffe dir zunächst einen Überblick über die Datenschutzrichtlinien deiner Firma.
====

[#600]
== App-Zugang gewähren

Die App ist nur in Kombination mit link:https://www.plentymarkets.eu/gratis-testen/[einem gebuchten plentymarkets System^] funktionsfähig. Das heißt, dass Nutzer sich mit den Login-Daten eines gültigen plentymarkets Systems anmelden müssen.

Vergib zunächst Zugangsdaten an alle Mitarbeiter, die die plentymarkets App nutzen sollen. Lege dabei fest, in welchem Umfang jeder Mitarbeiter die App verwenden darf.

[#700]
=== Benutzerkonten anlegen

Haben deine Mitarbeiter alle bereits ein plentymarkets Konto? Falls nicht, logge dich in dein plentymarkets System ein und <<basics/admin-aufgaben/benutzer-verwalten#10, erstelle die nötigen Konten>>.

Deine Mitarbeiter werden sich später mit dem Benutzernamen und Passwort des Systems auch <<app/installation#1200, in der App einloggen>>.

[TIP]
.Admin- oder Backend-Zugang?
====
Admin-Benutzer verfügen automatisch über alle plentymarkets Berechtigungen ohne Einschränkung. Sei vorsichtig, wenn du Admin-Konten erstellst, denn sie können auch weitere Benutzerkonten uneingeschränkt erstellen, verwalten und bearbeiten. +
Willst du selbst bestimmen, welche Funktionen und Menüs ein Benutzer sehen darf, empfiehlt es sich, einen Backend-Zugang zu erstellen.
====

[#800]
=== Berechtigungen festlegen

Sollen deine Mitarbeiter alle Funktionen der App sehen oder nur einzelne? Vielleicht willst du deinen Kassenkräften Zugang zur mobilen Kasse gewähren, aber nicht zur Lagerverwaltung.

In deinem plentymarkets System kannst du individuell festlegen, welche Bereiche und Kennzahlen für jedes Benutzerkonto sichtbar sind.

[.instruction]
App-Berechtigungen festlegen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Öffne ein Benutzerkonto des Typs *Backend*. +
*_Hinweis:_* *Admin*-Benutzer verfügen immer über alle Berechtigungen. Somit ist es nicht möglich, die App-Berechtigungen für Admins anzupassen.
. Öffne das Tab *Mobile*.
. Aktiviere Funktionen oder Kennzahlen, die dem Benutzerkonto in der App zur Verfügung stehen sollen. Beachte dabei die Erläuterungen in <<tabelle-app-berechtigung>>.
. *Speichere* die Einstellungen.

[[tabelle-app-berechtigung]]
.App-Berechtigungen festlegen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sichtbare Funktionen*
|Welche <<app/funktionen#, App-Funktionen>> sollen deine Mitarbeiter sehen können? Setze Häkchen und bestimme somit die genaue Menüpunkte, die diesen Backend-Nutzer sehen darf.

|*Einbuchung*
|Sollen deine Mitarbeiter beim <<app/funktionen/lagerverwaltung/einbuchen-umbuchen#, Einbuchen>> der Einkaufspreis sehen und bearbeiten können? Setze Häkchen, um die Berechtigungen zu vergeben. +
Dieser Bereich wird erst aktiviert nachdem du unter *Sichtbare Funktionen* ein Häkchen neben die Option *Einbuchung* gesetzt hast.

|*POS-Funktionen*
|Welche <<pos#, POS-Funktionen>> sollen deine Mitarbeiter nutzen können? Setze Häkchen und bestimme somit die genaue Funktionen, die diesen Backend-Nutzer verwenden darf. +
Dieser Bereich wird erst aktiviert nachdem du unter *Sichtbare Funktionen* ein Häkchen neben die Option *POS* gesetzt hast.

|*Sichtbare Kennzahlen*
|Welche <<app/funktionen/kennzahlen#, Geschäftskennzahlen>> sollen deine Mitarbeiter sehen können? Setze Häkchen und bestimme somit die genaue Daten, die diesen Backend-Nutzer sehen darf.
|====

//Was ist mit den REST-Berechtigungen oder andere Berechtigungen?

[#900]
=== App-PIN vergeben

Werden sich mehrere Mitarbeiter ein Gerät teilen? Falls ja, dann kann das ständige Ein- und Ausloggen schnell viel Zeit in Anspruch nehmen. In solchen Situationen empfiehlt es sich, dass Benutzer sich nicht direkt mit Benutzername und Passwort einloggen, sondern wenn sie <<app/installation#1700, das Konto mit einer PIN wechseln>>. Haben alle Benutzer eine eigene PIN, ist ein schneller Kontowechsel in der plentymarkets App möglich.

[.instruction]
App-PIN vergeben:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Öffne ein Benutzerkonto.
. Gib eine App-PIN für den Benutzer ein. Beachte dabei die Erläuterungen in <<tabelle-app-pin>>.
. Wiederhole die Eingabe.
. *Speichere* die Einstellungen.

//Als Single Sourcing Info einbringen von der Benutzer-Verwalten Seite

[[tabelle-app-pin]]
.App-PIN vergeben
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Neue App-PIN*
|Für Personal, das mit der plentymarkets App arbeitet, optional PIN mit 4 bis 12 Ziffern eingeben. Wenn eine PIN gespeichert ist, ist ein schneller Kontowechsel in der plentymarkets App möglich. Personal kann sich aber auch mit dem Passwort in die plentymarkets App einloggen. +
*_Tipp:_* Nachdem die PIN gespeichert wurde, werden in diesem Feld 4 Punkte angezeigt. Diese Punkte dienen dazu, sichtbar zu machen, dass für das Benutzerkonto eine App-PIN gespeichert ist, und stimmen nicht unbedingt mit der Länge der gespeicherten PIN überein. +
Beim schnellen Benutzerwechsel werden alle Benutzerkonten angezeigt, für die eine PIN gespeichert ist. Um die PIN zu entfernen, zum Beispiel, weil die Person nicht mehr mit der App arbeitet, die 4 Punkte löschen und das Konto erneut speichern. +

|*App-PIN wiederholen*
|PIN noch einmal eingeben.
|====

[#1000]
=== Gleichzeitige Nutzung

In deinem link:https://www.plentymarkets.eu/preise/[plentymarkets Tarif^] wird festgelegt, wie viele Benutzer gleichzeitig in plentymarkets eingeloggt sein dürfen. Dieses Limit gilt für dein plentymarkets Backend und für die plentymarkets App.

Das kannst du tun, wenn du das Benutzerlimit erreichst:

* Fordere eingeloggte Nutzer auf, sich manuell auszuloggen.
* <<basics/admin-aufgaben/benutzer-verwalten#170, Logge Benutzerkonten über die Session-Verwaltung aus>>.
* <<basics/admin-aufgaben/benutzer-verwalten#190, Erhöhe das Benutzerlimit deines plentymarkets Vertrags>>.

[TIP]
.Wie viele Konten kann ich erstellen?
====
Wir limitieren nur die gleichzeitige Nutzung und nicht die Anzahl der Benutzerkonten, die du erstellen kannst.
====

[#1100]
== Anmelden und orientieren

[#1200]
=== In die App einloggen

//Kapitel 2 von POS für Kassenpersonal entweder mit include oder mit Link (da raus und nur hier)

Die plentymarkets App ist nur in Kombination mit link:https://www.plentymarkets.eu/gratis-testen/[einem gebuchten plentymarkets System^] funktionsfähig. Das heißt, dass du bei der Anmeldung die Login-Daten deines plentymarkets Systems eingeben musst.

[.instruction]
In der App einloggen:

. Melde dich auf deinem mobilen Gerät an.
. Tippe auf dem Bildschirm auf die plentymarkets App. +
→ Der Login-Bildschirm wird angezeigt.
. Gib die Login-Daten deines plentymarkets Systems ein. Beachte dabei die Erläuterungen in <<tabelle-app-einloggen>>.
. Tippe auf **Login**. +
→ Der Startbildschirm der plentymarkets App wird angezeigt. +
→ Du bleibst angemeldet, bis du dich <<app/installation#1500, ausloggst>> oder dein Benutzerkonto <<app/installation#1600, sperrst>>. Du kannst die App also schließen und öffnen, ohne dich erneut anmelden zu müssen.


[[tabelle-app-einloggen]]
.In die App einloggen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sprache*
|Möchtest du die App auf Deutsch oder auf Englisch verwenden? Wähle die Sprache aus der Dropdown-Liste.

|*System (Basis-URL)*
|Wie lautet die URL deines plentymarkets Systems? Gib die Domain ohne führendes https:// oder http:// ein, zum Beispiel: ihr-shop.de.

|*Benutzer*
|Mit welchem Benutzerkonto möchtest du dich einloggen? Gib den <<basics/admin-aufgaben/benutzer-verwalten#30, Benutzernamen deines Kontos>> ein.
//(Auf die Benutzer-Seite sollte vorhanden sein: Wenn du ein neues plenty-System gebucht hast, dann bekommst du diese Benutzerdaten in eine E-Mail. Du kannst dann die Benutzername und Passwort ändern).

|*Passwort*
|Gib das <<basics/admin-aufgaben/benutzer-verwalten#30, Passwort deines Kontos>> ein.
|====

[#1300]
=== Sich in der App zurechtfinden

Hast du dich in die plentymarkets App eingeloggt? Willkommen! Deine erste Anlaufstelle ist der Startbildschirm. Schaue zunächst oben auf die Kopfzeile. Hier findest du zwei wichtige Symbole:

* Das Stiftsymbol (icon:pencil[role="blue"]) oben rechts. Tippe auf dieses Symbol, um <<app/funktionen/kennzahlen#, Geschäftszahlen wie Umsätze und Auftragsvolumen>> auf deiner Startseite einzurichten.

//Link zur Seite "Artikel, Kunden, Auftragsdaten einsehen" einbauen, sobald die Seite steht.
* Das Menüsymbol (icon:bars[role="blue"]) oben links. Tippe auf dieses Symbol, um in das Hauptmenü zu gelangen. Von hier aus kannst du deine Artikel-, Kunden- und Auftragsdaten einsehen. Du kannst die App für deine <<app/funktionen/lagerverwaltung#, Warenwirtschaft im Lager nutzen>>. Oder du kannst in deinem <<pos#, stationären Laden kassieren>>.

Bist du ins Hauptmenü gelangt? Schaue wieder auf die Kopfzeile. Auf die rechte Seite findest du jetzt zwei weitere Symbole:

* Das Wolkensymbol (icon:cloud[role="blue"]). Dieses Symbol zeigt an, ob du die App gerade im Online- oder Offline-Modus verwendest.

* Das Benutzersymbol (icon:user-circle[role="blue"]). Tippe auf dieses Symbol, um das <<app/installation#1600, Benutzerkonto zu sperren>>, <<app/installation#1700, zu wechseln>> oder <<app/installation#1500, gänzlich auszuloggen>>.

[TIP]
.Menü neu laden
====
Aktualisiere die Ansicht, indem du das Fenster nach unten ziehst.
====

[#1400]
== Abmelden, sperren oder Konto wechseln

[#1500]
=== Aus der App ausloggen

Um dich aus der plentymarkets App auszuloggen, gehe wie folgt vor.

[.instruction]
Aus der App ausloggen:

. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe unten auf *Ausloggen*. +
→ Das Fenster *Ausloggen* wird angezeigt.
. Bestimme, ob du beim nächsten Anmelden deine Login-Daten erneut eingeben möchtest oder nicht. Beachte dabei die Erläuterung in <<tabelle-app-ausloggen>>.

[[tabelle-app-ausloggen]]
.Aus der App ausloggen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Aktuellen Benutzer automatisch wieder einloggen*
|Verwende die Umschaltfläche, um plentymarkets mitzuteilen, ob du beim nächsten Anmelden deine Login-Daten erneut eingeben möchtest. +
*Aktiviert* (icon:toggle-on[role="green"]) = Beim nächsten Öffnen der App wird dieses Benutzerkonto automatisch wieder eingeloggt. Beim Start der App muss kein Passwort eingegeben werden. +
*Deaktiviert* (icon:toggle-off[role="darkGrey"]) = Das Benutzerkonto wird vollständig ausgeloggt und die Anmeldedaten verworfen. Beim nächsten Anmelden müssen Sprache, Basis-URL und Benutzerdaten eingegeben werden. +
*_Hinweis:_* Diese Einstellung wird übernommen und gilt für alle Benutzerkonten der App.
|====

[TIP]
.Alternative Vorgehensweise
====
Tippe alternativ auf das Benutzersymbol (icon:user-circle[role="darkGrey"]) und dann auf das Logoutsymbol (icon:sign-out[role="red"]). Beachte dabei die Erläuterung in <<tabelle-app-ausloggen>>.
====

[#1600]
=== Zugriff sperren und entsperren

Wenn du dich von der Kasse entfernst, aber weiterhin eingeloggt bleiben möchtest, sperre den Zugriff auf die App.

[.instruction]
Zugriff sperren:

. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe oben rechts auf das Benutzersymbol (icon:user-circle[role="darkGrey"]). +
→ Eine Liste der Personen wird angezeigt, für die <<app/installation#900, eine App-PIN>> gespeichert ist.
. Tippe unten links auf das Sperrensymbol (icon:lock[role="blue"]). +
→ Der Zugriff auf die App wird gesperrt. +
→ Dein realer Name wird als erster Eintrag in der Liste der Benutzerkonten angezeigt.

[.instruction]
Zugriff wieder entsperren:

. Tippe auf dein Benutzerkonto.
. Gib deine PIN oder dein Passwort ein. +
→ Der Zugriff auf die App wird entsperrt. +
*_Tipp:_* Auch bei gesperrtem App-Zugriff kannst du das Benutzerkonto wechseln. Tippe auf ein anderes Benutzerkonto in der Liste, um das Benutzerkonto zu wechseln.

[#1700]
=== Benutzerkonto wechseln

Teilen sich mehrere Mitarbeiter ein Gerät? Falls ja, dann kann das ständige Ein- und Ausloggen viel Zeit in Anspruch nehmen. Schneller geht es wenn der eingeloggte Benutzer sich nicht direkt abmeldet, sondern wenn das Konto mit einer PIN gewechselt wird.

Welches Benutzerkonto gerade angemeldet ist, erkennst du an dem Benutzersymbol (icon:user-circle[role="darkGrey"]) oben rechts. Dieses Symbol enthält die Initialen der aktuell eingeloggten Person. Das Symbol hat die Farbe, die für das Benutzerkonto im plentymarkets Backend gespeichert wurde.

[.instruction]
Benutzerkonto im laufenden Betrieb wechseln:

. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe oben rechts auf das Benutzersymbol (icon:user-circle[role="darkGrey"]). +
→ Eine Liste der Personen wird angezeigt, für die <<app/installation#900, eine App-PIN>> gespeichert ist. +
. Tippe auf das gewünschte Benutzerkonto.
. Wenn der neue Benutzer sich zum ersten Mal in der App anmeldet, muss er sein Passwort eingeben. Ab dem zweiten Anmelden gibt er seine PIN ein. +
→ Das Benutzerkonto wird gewechselt.

Nach dem Wechsel wird derselbe Bereich der App geöffnet. Wenn das neue Benutzerkonto für diesen Bereich keine Rechte hat, wird stattdessen das Hauptmenü der App geöffnet.

[TIP]
.Auftragsdaten bleiben erhalten
====
Wenn du das Benutzerkonto mitten in einem Kassiervorgang wechselst, sieht der neu eingeloggte Benutzer den angefangenen Kassiervorgang. Somit kann der neue Benutzer diesen Vorgang abschließen.
====

[#1800]
== Personalisieren

Um die App zu personalisieren, gehe wie folgt vor.

[#1900]
=== Mit Vorlagen arbeiten

Möchtest du z.B. bestimmen, in welcher Reihenfolge und in welcher Schriftgröße einzelne Informationen in der App dargestellt werden?

//Link zur Seite "Artikel- und Auftragsdaten" einbauen, sobald die Seite steht.
//Link zur Seite "mobilen Picklisten" einbauen, sobald die Seite steht.
Im plentymarkets Backend kannst du Vorlagen für einige App-Funktionen erstellen. Du kannst beispielsweise bestimmen, wie deine Artikel- und Auftragsdaten in der App dargestellt werden oder wie deine <<app/funktionen/lagerverwaltung/picklisten#, mobilen Picklisten>> aussehen sollen.

[#2000]
=== Hintergrundbild auswählen

Willst du statt des Standard-Hintergrunds z.B. die Farben deines eigenen Corporate Designs verwenden? Bestimme selbst, welches Bild oder welche Farbe angezeigt werden sollen.

[.instruction]
Hintergrundbild wechseln:

. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe auf *Einstellungen*.
. Tippe auf *Darstellung*.
. Tippe auf ein Hintergrundbild oder auf eine Hintergrundfarbe. +
→ Der Hintergrund ändert sich. +
. Tippe auf das Häkchen (icon:check[role="blue"]), um die Änderung zu bestätigen.

[#2100]
== App aktualisieren

Wartest du sehnsüchtig auf ein neues Feature? Wir informieren dich gerne über Änderungen an der Software. Versionen der plentymarkets App sind durch Versionsnummern gekennzeichnet. Änderungen werden zudem in einem Changelog veröffentlicht. link:https://forum.plentymarkets.com/c/changelog/changelog-app[Abonniere den Changelog^] und bleibe immer auf dem Laufenden.


//Wie kommen updates rein? Automatisch über den Play-Store oder muss der Händler aktiv etwas machen?
