= Setting up Allyouneed in plentymarkets
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Allyouneed, Market, Marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market Allyouneed in your plentymarkets system.
:position: 1

On this page, you will find information about the settings you need to carry out in order to set up the market *Allyouneed* in plentymarkets. You will learn how to set up the interface, link categories and export your items to Allyouneed.

[#100]
==  Registering with Allyouneed

First, register with link:http://de.allyouneed.com/de/dealer/page/selfsignup/step1[Allyouneed^] as a seller in order to set up the interface to *Allyouneed* in your plentymarkets system. Please note that the Allyouneed website is currently only available in German. You will then receive the access data that you need for the configuration in plentymarkets.

[#200]
==  Setting up Allyouneed in plentymarkets

Once you have registered with Allyouneed, use the access data that is saved there to set up the market in plentymarkets. To do so, proceed as follows.

[.instruction]
Setting up Allyouneed in plentymarkets:

.  Go to *System » Markets » Allyouneed » Settings*.
.  Carry out the settings. Pay attention to the explanations given in table 1.
. *Save* the settings.

.Basic settings for the market Allyouneed
[cols="1,3"]
|====
| Setting | Explanation

2+| Access data

|*Email address*
| Enter the email address.

|*Password*
| Enter the password of the Allyouneed account.

|*Test account*
|Select *Yes* for the *test mode*. +
Activate the Allyouneed test environment. This tests the item upload and makes it possible to receive test orders. You need separate access data for a test account. Register with Allyouneed to receive a link:https://portal.allyouneed.com/funktionsuebersicht/testsystem.html[test system^].

2+| Basic configuration

|*Item name*
| Select the name that should be used for Allyouneed items.

|*Assignment client (store)*
| Select the stores that you would like the settings to apply to.

|*Item availability*
| Select the availability. The items with the selected availability are transferred. Set up the options for item availability in the <<item/managing-items#190, System » Item » Availability>> menu.

|*Delivery period*
| Select a delivery period or select *Do not transfer*.

|*Additional days*
| Enter the number of days that should be added to the value specified under *Item availability*.

|*Warehouse selection*
|Select the *main warehouse* or the *maximum stock quantity of all distribution warehouses*.

|*Automatically transfer changes in stock & price*
| Select whether you want to transfer stock & price changes automatically. +
*YES* = Changed stock and prices are transferred to Allyouneed every hour. +
*NO* = Items are only synchronised if the whole item is transferred to Allyouneed. The synchronisation is carried out approximately every 7 days.

2+| Advanced options

|*Mark order as paid*
|Select *YES* to mark the order as paid after it has been imported.

|*Add technical data to the description*
|Select *YES* if you would like the entry under *Technical data* to be added to the entry under *Description* in the *Texts* tab of the item data.

|*Stock buffer*
| Enter a value for the stock buffer, e.g. *4*. This means that 4 items will be reserved for Allyouneed and will be subtracted from the net stock in your system.

|*Quantity for items not limited to the stock*
| Enter a quantity of items that is not limited to stock. This amount represents the *stock* that is displayed on Allyouneed.

|*Maximum for item upload*
| Enter a maximum limit for the item quantity, i.e. how many pieces may be uploaded per item.

|*Standard tax rate*
| Select the standard tax rate.

|*Reduced tax rate*
| Select the corresponding *reduced tax rate*. +
Pay attention to the tax rates settings in the <<orders/accounting#, System » Client » Select client » Locations » Select locations » Accounting>> menu.

|*Add the variation name to the item name*
|Select *Yes* to add the variation name to the item name. +
*Example*: T-Shirt [Colour:dark blue; Size:L]].

|*Transfer manufacturers*
| Select an option for the transfer of *manufacturers*. It is necessary to enter the manufacturer in order to export items to Allyouneed.
|====

Connecting to this market allows for the following automatic functions to take place:

* Daily transfer of new items and changes to items
* Hourly synchronisation of order status
* Hourly order import
* Hourly shipping confirmation for orders with the outgoing items booked
* Hourly cancellation of orders with a status higher than [8] and lower than [9]
* Daily stock synchronisation of all stocks
* Hourly synchronisation of order data (e.g. changed stock, prices)
* Daily deletion of items on the market that are no longer available

[#250]
== Activating an order referrer

In order to link items, properties etc. with Allyouneed you have to activate the order referrer Allyouneed in the menu *System » Orders » Order referrer*.

[.instruction]
Activating the order referrer for Allyouneed:

. Go to *System » Orders » Order referrer*.
. Place a check mark next to the option *Allyouneed*.
. *Save* the settings.

[#300]
== Setting the item availability

Items have to be available for Allyouneed. This is done in the *Availability* tab of an item within the <<item/managing-items#170, Item » Edit item » Open item » Tab: Variation ID>> menu.

[.instruction]
Setting the item availability for Allyouneed:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Place a check mark next to the option *Allyouneed*.
. Place a check mark next to the option *Web API*.
. Click on *Add*. +
→ The market is added.
. *Save* the settings. +
→ The item is available on Allyouneed.

The availability for variations can be individually edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

In order to prepare your items for the export to Allyouneed, the settings described below are necessary. In addition, pay attention to the requirements published by Allyouneed in order to have your items exported correctly. In the *Item » Edit item* menu, the following fields are mandatory for the item export:

* *Name*: Enter text in the *Name 1* field in the *Texts* tab. This text is transferred to Allyouneed and displayed as the item name.
* *Price*: Enter a value bigger than 0.00.
* *Manufacturer*: Enter a text in the field *Manufacturer* in the tab *Global*.
* *Category*: Link the categories. For further information, refer to the <<en/item/managing-items#10, Creating categories>> chapter.
* *Description (long)*: Enter text in the *Item text* field in the *Texts* tab. This text is transferred to Allyouneed and displayed as the long product description.
* *Description (short)*: Enter text in the *Preview text* field in the *Texts* tab. This text is transferred to Allyouneed and displayed as the short product description. The maximum length is 200 characters. If you do not enter a preview text, the item name is automatically used as the short product description text.

In the *Item » Edit item* menu, the following fields are optional for the item export:

* *Item images*: Allyouneed only accepts item images that are at least 500 x 500 px with a resolution of 72 dpi and have the formats JPG, GIF or PNG.
* *Technical data*: Enter text in the *Technical data* field in the *Texts* tab. This text is displayed with the normal item description if you have activated the option *Add technical data to the description* in the basic settings.

[NOTE]
.Switching items "offline"
====
If you no longer want to export the item, open the item in the *Item » Edit item* menu and deactivate the *Allyouneed* option in the *Available* tab. During the next round of automatic stock updates, this item is then set to "offline" in Allyouneed.
====

[#350]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Allyouneed. This price is displayed on Allyouneed.

[.instruction]
Defining a sales price for Allyouneed:

. Open the menu *System » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *Allyouneed*.
. *Save* the settings.

[#400]
==  Linking categories

Approximately 3,000 Allyouneed product categories are available for linking your item categories to the Allyouneed categories. Because you have to link the Allyouneed categories all the way to the last level, your categories should be as specific as possible. Check your categories and, if necessary, create additional subcategories that are more suitable for linking with Allyouneed.

[TIP]
.Adding additional Allyouneed categories
====
Additional Allyouneed categories can be added. To do so, get in contact with *link:https://portal.allyouneed.com/verkaufen-mit-allyouneed.html[Allyouneed.com]^*.
====

[.instruction]
Linking categories:

.  Go to *System » Markets » Allyouneed » Category link*.
.   Select a main category from the *Allyouneed category* drop-down list. +
→ The window *Category selection* opens.
. Select a subcategory. +
→ The *category ID* is only displayed once you have reached the lowest category level.
.  Click on the gear-wheel icon to save the link. +
→ The editing window is closed.
. *Save* the settings.

[#500]
== Linking attributes

Item variations, i.e. items that are saved with specific attributes, can also be exported to Allyouneed. If you have created <<item/managing-items#390, attributes>> in your plentymarkets system, you have to link these attributes with Allyouneed. Proceed as described below to link the attribute *colour* of the *outerwear* group with Allyouneed. Link further attributes in the same way. Information on parameters and attribute values that you can use for Allyouneed are available in the link:https://portal.allyouneed.com/support/downloadbereich/allyouneed.html[Allyouneed documentation^] (German only).

[.instruction]
Linking attributes:

. Go to *System » Item » Attributes*. +
→ An overview of all existing attributes opens.
. Expand the attribute *Colour*.
. Open the *Market variation* tab.
. Select the option *Allyouneed* from the *Market* drop-down list. +
→ A second drop-down list *Allyouneed* is displayed.
. Select the option *Outerwear* from the *Group* drop-down list.
. Select the *Colour* option from the *Attribute* drop-down list.
. Enter a unit if needed.
. Enter the Allyouneed attribute values that most closely match your own attribute values. This is done in the Market variation area.
. *Save* the settings.

[NOTE]
.Optional: Unit
====
In addition to the mandatory fields *Group* and *Attribute*, the third option, *Unit*, is displayed for certain groups or attributes, e.g. *measurements*. You can enter a value here, e.g. *dpt* (dioptre value) for contact lenses.
====

[#600]
==  Creating properties

The properties described below are required to specify the condition and the shipping information. You can create a <<item/managing-items#490, property group>> for Allyouneed and assign all properties you create for Allyouneed to this group. Only options relevant for Allyouneed are described here. For further details, refer to the <<item/managing-items#480, Managing properties>> page of the manual.

[#700]
===  Creating a property for the condition

The Allyouneed market has a separate section for link:https://portal.allyouneed.com/verkaufen-mit-allyouneed/highlights-vorteile/b-ware.html[selling factory seconds^] (B-Ware). You have to possibilities to list there:

* Go to *Item » Edit Item » Open item » Tab: Global*. In the section *Basic settings*, select *Factory seconds* from the drop-down list *Condition for API*.
* Create a <<item/managing-items#500, property>> for the condition. The advantage of creating a property is that the property can be used for other conditions such as *display item*.

If the sale of an item marked as factory second has been activated by one of these two possibilities, the fields *EAN*, *Manufacturer* and *Manufacturer number* are no longer transferred. This prevents mixing factory seconds with normal items in search results.

[.instruction]
Creating a property for the condition:

. Go to *System » Item » Properties*.
. Open the *New Property* tab.
. Enter a name in the *Name (internal)* field.
. Select a *Property group*, if available.
. Select the option *Selection* from the *Property type* drop-down list. +
→ The *New selection* area is opened.
. Enter *Factory seconds* in the *Name* field.
. Select the option *Factory Seconds* from the *Allyouneed property* drop-down list.
. *Save* the settings. +
→ The property is created.
. Open the *Properties* tab.
. Expand the property.
. Enter the name *Refurbished* in the next selection field of the *Selection* area.
. *Save* the settings.
. Repeat steps 11 and 12 for the selection fields *Verpackungsschäden* (means that the packaging is damaged) and *Demoware* (means that the item was on display).

[#800]
===  Creating a property for shipping information

Using properties you can also transfer *shipping information* for an item. This is useful if an item needs to be shipped by a forwarding agency and the shipping costs thus differ from the general settings on Allyouneed.

[.instruction]
Creating a property for shipping information:

. Go to *System » Item » Properties*.
. Open the *New Property* tab.
. Enter a name in the *Name (internal)* field.
. Select a *Property group*, if available.
. Select the option *Decimal number* from the *Property type* drop-down list.
. Select the option *Shipping costs* from the *Allyouneed property* drop-down list.
. *Save* the settings. +
→ The property is created.

[NOTE]
.Fixed shipping costs
====
For the property *Fixed shipping costs*, enter the name *Fixed shipping costs*, select the property type *Whole number* and the Allyouneed property *Fixed shipping costs*.
====

[#900]
===  Creating a property for shipping method

First create the property *Shipping method* for an item.

[.instruction]
Creating a property for shipping method:

. Go to *System » Item » Properties*.
. Open the *New Property* tab.
. Enter a name in the *Name (internal)* field.
. Select a *Property group*, if available.
. Select the option *Selection* from the *Property type* drop-down list. +
→ The *New selection* area is opened.
. Enter *BULK_GOODS* in the *Name* field.
. Enter the description *Bulky goods* in the *Description* field.
. Select the option *Shipping method* from the *Allyouneed property* drop-down list.
. *Save* the settings. +
→ The property is created.
. Open the *Properties* tab.
. Expand the property.
. Enter the name *FORWARDING_AGENCY* in the next selection field of the *Selection* area.
. Enter the description *Cargo*.
. *Save* the settings.
. Repeat steps 12 to 14 for the *BOOK_RATE* selection field with the description *Book mail* and the *CONSIGNMENT_OF_GOODS* selection field with the description *Shipping*.

[#1000]
==  Activating the payment method

Activate the <<payment/managing-payment-methods#, payment method>> *Allyouneed Payments* as described below.

[.instruction]
Activating the Allyouneed payment method:

.  Go to *System » Orders » Payment » Methods*.
.  Place a check mark next to the setting *Also show inactive*.
.  Open the folder *DE*.
.  Click on *Allyouneed Payments*. +
→ The *Settings* tab opens.
.  Carry out the settings. Pay attention to the information given in table 5.
.  Place a check mark next to the option *Active*.
. *Save* the settings.

.Settings for the payment method
[cols="1,3"]
|====
| Setting | Explanation

|*Language*
| The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo* and *Upload logo*. This makes it possible to enter values for these options in various languages. The values for a language are activated as soon as a buyer selects the language in the online store.

|*Name*
| Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
| Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
| If you have selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
| Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely set up.

|*Logo*
| Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

|*Logo view*
| If *Show upload logo* has been selected from the *Logo* drop-down list, then the logo that has been uploaded is displayed here.

|*Upload logo*
| If *Show upload logo* has been selected from the *Logo* drop-down list, upload an external logo here. +
 Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|*Priority*
| Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
| If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. *Important*: Do not enter a value into both fields. +
For further information, refer to the <<en/basics/statistics#, Statistics>> page of the manual. For an example of flat rate and percentage costs, refer to the <<payment/managing-payment-methods#20, Managing payment methods>> page of the manual.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *System » CRM » Classes* to activate or deactivate *Permitted payment methods*. +
For further information, refer to the <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter of the manual.
====

For further information, refer to the <<payment/managing-payment-methods#, Payment methods>> page of the manual.

[#1100]
==  Setting up shipping profiles

Orders received from Allyouneed may only be shipped with *DHL* or *Deutsche Post*. Allyouneed does not guarantee full payment protection when other shipping service providers are used. Exceptions for shipping exist for cargo.

[.instruction]
Setting up a shipping profile for Allyouneed:

. Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Open a shipping profile.
. Activate the option *Allyouneed* under *Order referrer*.
. Deactivate the option *Allyouneed* under *Blocked payment methods*.
. *Save* the settings.

After the order has been edited, plentymarkets will confirm the shipment with Allyouneed and transfer the package number. Make sure you save the package number in the corresponding order directly after you have booked the outgoing items. This will ensure that it is transferred along with the shipping confirmation and that the purchaser can receive them from Allyouneed.

[#1150]
==  Defining SKU manually

Add SKUs manually for specific referrers in the menu <<en/item/managing-items#170, Item » Edit item » Open item » Tab: Variation ID » Tab: Availability>> if needed.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
.  Click on the *Availability* tab.
.  Click on *Add* in the section *SKU*. +
→ The window *New SKU* is displayed.
.  Select the referrer *Allyouneed.com*.
.  Enter the SKU.
.  Click on *Add*. +
→ The SKU is saved and displayed.

[#1160]
== Automatically sending returns

Set up an <<automation/event-procedures, event procedure>> to automatically send returns to Allyouneed.

[.collapseBox]
.Setting up an event procedure
--
[.instruction]
. Go to *System » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the event listed in table <<table-event-procedure-return>>.
. *Save* the settings.
. Pay attention to the information given in <<table-event-procedure-return>>.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[table-event-procedure-return]]
.Event procedure for sending automatic returns to Allyouneed
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order generation: New return*
|

|*Filter 1*
|*Order > Order type*
|*Return*

|*Filter 2*
|*Order > Referrer*
|*Allyouneed*

|*Procedure*
|*Return > Send return to Allyouneed*
|
|====

[#1170]
== Automatically sending credit notes

If you already received a payment and you want to refund a customer with a credit note, set up an <<automation/event-procedures#, event procedure>> to automatically send credit notes to Allyouneed.

[.collapseBox]
.Setting up an event procedure
--
[.instruction]
. Go to *System » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the event listed in table <<table-event-procedure-credit-note>>.
. *Save* the settings.
. Pay attention to the information given in <<table-event-procedure-credit-note>>.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[table-event-procedure-credit-note]]
.Event procedure for automatically sending credit notes to Allyouneed
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order generation: New credit note*
|

|*Filter 1*
|*Order > Order type*
|*Credit note*

|*Filter 2*
|*Order > Referrer*
|*Allyouneed*

|*Procedure*
|*Payment methods > Send credit note to Allyouneed*
|
|====

[#1200]
==  FAQ

[#130]
===  Error message type: PRODUCT_NOT_FOUND

[.collapseBox]
.Product could not be found. (Code: 1005) / Product could not be created. No description exists for this product. (Code: 1040)
--
These messages indicate that Allyouneed has not saved any data for this EAN yet and that the item cannot be created without a description. +
→ Enter a description and save the categories.
--

[.collapseBox]
.The product could not be clearly assigned. Add further identifiers. (Code: 4026)
--
This message indicates that multiple sellers have already listed the item with different specifications. +
→ Contact Allyouneed and ask them to combine the items or transfer your description and category links. +
Another reason might be that you have saved multiple price sets for this item in plentymarkets. +
→ Only one price set can be transferred. Delete the other price sets in plentymarkets, remove the item from Allyouneed and transfer the item again.
--

[#140]
===  Error message type: INVALID_MODIFICATION

[.collapseBox]
.The product cannot be updated or created due to ambiguous identifiers for the product. (Code: 4010)
--
This message indicates that the manufacturer data does not match the EAN that was transferred. For example, "Gigaset" was transferred as the manufacturer. However, it is saved as "Siemens AG" in the Allyouneed catalogue. +
→ Check your manufacturer data and contact Allyouneed if necessary.
--

[.collapseBox]
.A product with identical manufacturer data was found. (Code: 4025)
--
This error message indicates that the manufacturer data is wrong. Contact Allyouneed.
--

[.collapseBox]
.Product 'xxx' with Allyouneed ID 'xxx' could not be matched with product 'xxx'. (Code: 4023)
--
This error message indicates that the item is included in the Allyouneed catalogue but could not be assigned to it because the item has already been listed with this account. +
→ Delete the item from the Allyouneed account. The item should be listed correctly when it is transferred again.
--

[.collapseBox]
.Marketplace category cannot be mapped because you are not the originator of this product.
--
This error message indicates that the item with this EAN is already included in the Allyouneed catalogue, but it is listed in a different category. +
→ If this message is not followed by "PRODUCT_NOT_FOUND”, then it is simply a warning and the item is listed anyway. However, the item is not listed with your description. Instead, it is listed with the description in the Allyouneed catalogue.
--

[.collapseBox]
.The EAN is already in use. It is only possible to use EANs several times if the products contain different manufacturer data or variation attributes. (Code: 4027)
--
This error message indicates that the item has already been transferred to Allyouneed with this account. However, the specified IDs ("own product number") do not match. +
→ Delete the item from the Allyouneed account. The item should be listed correctly when it is transferred again.
--

[.collapseBox]
.The product xxx could not be assigned to the variation group xxx because the mandatory attribute values could not be found. (Code: 5019)
--
This error message indicates that a different seller has already transferred the item with variations and that your item does not have any variations or has different variations saved for it.
--

[.collapseBox]
.The EAN cannot be changed. You have not created the product 'xxx' (mpid: xxx). (Code: 4002)
--
This error message indicates that the item was already linked to an item from the Allyouneed catalogue and that it is therefore not possible to change the EAN. +
→ Delete the item from the account on Allyouneed or contact Allyouneed.
--

[.collapseBox]
.Not possible to update physical product. Product with the same ManufacturerName and AID found in the system.
--
Delete the item from the account on Allyouneed. The item should be listed correctly when it is transferred again.
--

[.collapseBox]
.An unknown error occurred, please contact Allyouneed support, with this xmlfile.
--
This message indicates that the attribute links are incorrect. For example, only numbers might be permitted as values but letters were entered as well. Or if a combination of attributes does not fit together, e.g. if an attribute for "shoes" was combined with an attribute for "hats".
--

[.collapseBox]
.Invalid variation attributes for product "xyz". Check whether the variation group/attribute configuration corresponds to your product data. (Code: 5008)
--
This error message indicates that no attribute group was assigned to the attribute for Allyouneed. +
→ Carry out the steps listed in the <<en/item/managing-items#440, Linking attributes>> chapter.
--

[#150]
===  Error message type: MARKETPLACE_CATEGORY_NOT_FOUND

[.collapseBox]
.Market category 'c' was not found. (Code: 1003)
--
This error message indicates that an error occurred while linking the categories. +
→ Check whether the category ID that was entered is correct. You may simply have made a typo while entering the ID.
--

[#160]
===  Error message type: VARIANT_GROUP_NOT_FOUND

[.collapseBox]
.Variation group 'xxx' was not found. (Code: 5009)
--
This error message is a consequence of the error "Failed to create variation group (Code: 50026)". +
→ Contact Allyouneed.
--

[#170]
===  Error message type: INVALID_DATA

[.collapseBox]
.Not valid or missing required variant attribute values for DescriptionProduct with code 'xxx'. Variant group: xxx. Required attribute 'memoryCapacity'.
--
This error message indicates that the attributes were not linked correctly or that a different seller has already transferred the item with variations and that your item does not have any variations saved for it.
--

[.collapseBox]
.Invalid price &lt;0&gt;. The price must be a positive decimal number. (Code: 1015)
--
This error message indicates that no price was saved. +
→ Save a price for the item in the item data.
--

[.collapseBox]
.Duplicate variant attribute values found for physical product with code $xyz inside a variant group - code: xyz
--
This error message indicates that there are duplicate attribute values or that multiple item attributes were linked with various, non-compatible Allyouneed attribute groups. +
→ For further information about Allyouneed groups, refer to the <<en/item/managing-items#440, Linking attributes>> chapter.
--

[#180]
===  Error message type: plenty

[.collapseBox]
.missing "marketplaceCategory"
--
This error message indicates that there is neither an EAN nor a description/category link that the item can be listed with. +
→ Save an EAN and description in the item data and link the categories.
--

[.collapseBox]
.missing "name"
--
This error message indicates that the item does not have a name. +
→ Enter a name in the item data.
--

[.collapseBox]
.missing "productId"
--
This error message indicates that an ID is missing. +
→ Contact plentymarkets.
--

[.collapseBox]
.missing "attribute group code"
--
This error message indicates that no attribute group was assigned to the attribute for Allyouneed. +
→ Carry out the steps listed in the <<en/item/managing-items#440, Linking attributes>> chapter.
--
