= Klarna
:lang: en
include::{includedir}/_header.adoc[]
:keywords: payment plugin, payment method, Klarna
:description: Integration of the Klarna plugin.
:position:
:url: payment/payment-plugins/klarna
:id: 3SGDQQB
:author: team-order-payment

With the plugin Klarna, you integrate the Klarna payment methods in your online shop and make them available to your customers. To do so, download the Klarna plugin from the link:https://marketplace.plentymarkets.com/en/klarna_6731[plentyMarketplace^]{nbsp}icon:external-link[]. You also have to carry out a few basic settings in your plentymarkets system so that the payment methods are activated in your system. +
The explanations in this section apply after adding the plugin. You can find more information on adding and installing plugins in the <<plugins#, Plugins>> section of the manual.

[#10]
== Requirement: Opening a Klarna business account

To work with Klarna, you first need a link:https://www.klarna.com/uk/business/[Klarna business account^]{nbsp}icon:external-link[]. You get information as well as login details when you open the account. Without these, the plugin cannot be set up and is not usable. In case you have not registered with Klarna yet or your Klarna customer ID does not start with Kxxxxx, send an email to vertrieb@klarna.com.

[#20]
== Configuration of the plugin

Setting up Klarna requires configuring the plugin and setting up event procedures. First, configure the plugin.

[.instruction]
Configuration of the plugin:

. Go to *Plugins » Plugin set overview » [select Plugin set]*.
. Open the plugin *Klarna*. +
→ You are redirected to the authentication.
. Select a mode.  You can choose between *Testing* and *Productive*.
. Enter the required *user name* and *password*.  Make sure to enter the correct date for the chosen mode.
. *Save* (icon:save[role="green"]) the settings.

After this, you can choose between the Klarna modules *Klarna Payments* or *Klarna Checkout*. If you choose *Klarna Payments*, the Klarna payment method *Pay later* is then available in your online shop. If you choose *Klarna Checkout*, you automatically overwrite the online shop’s existing checkout. With Klarna Checkout, no further configurations are needed. Overwriting the checkout can be reversed by deactivating the plugin.

[.instruction]
Selection of the Klarna module:

. Go to *Configuration » Base settings* in the left-hand menu.
. Select a *Klarna module*.
. Save (icon:save[role="green"]) the settings.

[.30]
== Activating the payment method

include::../_textblocks/activate-payment-method.adoc[]

[#40]
== Customer classes and shipping profiles

include::../_textblocks/customer-class-and-shipping-profile.adoc[]

[#50]
== Setting up event procedures

Set up event procedures so that all needed data are sent to Klarna. 5 event procedures are required for this.

[.collapseBox]
.*Setting up an event procedure*
--

[.instruction]
Setup of an event procedure:

. Go to *Setup » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *Event* as listed in tables 1-5.
. *Save* (icon:save[role="green"]) the settings.
. Carry out the settings according to tables 1-5.
. Activate the option *Active*.
. *Save* (icon:save[role="green"]) the settings.

--

[#60]
=== Automatically sending shipping confirmations

In order for the payment to be activated with Klarna, a shipping confirmation has to be sent. For this, we recommend the following configuration:

[[table-procedure-klarna-shipping-confirmation]]
.Event procedure: Send shipping confirmation to Klarna
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| Outgoing items booked
|

| *Filter 2*
| Order > Payment method
| Select all payment methods of the Klarna plugin.

| *Filter 1*
| Order type > Order
|

| *Procedure*
| Plugin > Send shipping confirmation to Klarna
|

|====

[#70]
=== Automatically sending cancellations

If an order is cancelled, Klarna has to be informed. For this, we recommend the following configuration:

[[table-procedure-klarna-cancellation]]
.Event procedure: Send cancellation to Klarna
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| Status change
| Select a status from the return range.

| *Filter 2*
| Order > Payment method
| Select all payment methods of the Klarna plugin.

| *Filter 1*
| Order type > Order
|

| *Procedure*
| Plugin: Send cancellation notification to Klarna
|

|====

[#80]
=== Automatically sending refund information to Klarna

If a refund is issued, Klarna has to be informed. For this, we recommend the following configuration:

[[table-procedure-klarna-refund]]
.Event procedure: Send refund to Klarna
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| Credit note
|

| *Filter 2*
| Order > Payment method
| Select all payment methods of the Klarna plugin.

| *Filter 1*
| Order type > Credit note
|

| *Procedure*
| Plugin: Send refund to Klarna
|

|====

[#90]
=== Automatically sending address changes

If the address given for an order is changed between the order creation and shipping, Klarna has to be informed. For this, we recommend the following configuration:

[[table-procedure-klarna-address-change]]
.Event procedure: Send address change to Klarna
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| Status change
|

| *Filter 2*
| Order > Payment method
| Select all payment methods of the Klarna plugin.

| *Filter 1*
| Order type > Order
|

| *Procedure*
| Plugin: Send address change to Klarna
|

|====

[#100]
=== Automatically send order item changes

If the the order items are changed between the order creation and shipping, For this, we recommend the following configuration:

[[table-procedure-klarna-change-items]]
.Event procedure: Send order item changes to Klarna
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| Status change
|Select the status, for which this event is to be activated.

| *Filter 2*
| Order > Payment method
| Select all payment methods of the Klarna plugin.

| *Filter 1*
| Order type > Order
|

| *Procedure*
| Event procedure: Send order item changes to Klarna
|

|====

[#110]
== Editing text elements

You can edit texts of the plugin in the *CMS » Multilingualism* menu. The texts can be adapted into all available system languages. To do so, proceed as described below.

[.instruction]
Adapting language files:

. Go to *CMS » Multilingualism*.
. On the left side, select the *Source language* from the drop-down list.
. On the right side, select the *Target language* from the drop-down list.
. Expand the section *payment method* in the *Klarna* area.
. Enter the text for the individual text elements in the area of the target language.
. Save (icon:save[role="green"]) the settings.

Find more information in how to edit online shop texts on the manual page <<online-store/setting-up-ceres#231, Editing online store texts>>.
