= Pay upon pickup
:lang: en
include::{includedir}/_header.adoc[]
:keywords: payment method, cash, pay-upon-pickup, pay upon pickup
:description: Integration of the plugin Pay upon pickup.
:position:
:url: payment/payment-plugins/pay-upon-pickup
:id: PRW1S0P
:author: team-order-payment

With the plugin Pay upon pickup, you integrate the payment method *Cash payment* in your online shop and make it available to your customers. To do so, download the plugin Pay upon pickup from the link:https://marketplace.plentymarkets.com/en/payuponpickup_4757[plentyMarketplace^]{nbsp}icon:external-link[]. Setup of the payment method is done with an assistant. You also have to carry out a few basic settings in your plentymarkets system so that the payment method is activated in your system. +
The explanations in this section apply after adding the plugin. You can find more information on adding and installing plugins in the <<plugins# Plugins>> section of the manual.

[#10]
== Completing the assistant

:name-assistant: Pay upon pickup
:name-payment-method: cash payment

include::../_textblocks/completing-assistant.adoc[]

[#20]
== Activating the payment method

include::../_textblocks/activate-payment-method.adoc[]

[#30]
== Customer classes and shipping profiles

include::../_textblocks/customer-class-and-shipping-profile.adoc[]

[#40]
== Editing text elements

You can edit texts of the plugin in the *CMS » Multilingualism* menu. The texts can be adapted into all available system languages. To do so, proceed as described below.

[.instruction]
Adapting language files:

. Go to *CMS » Multilingualism*.
. On the left side, select the *Source language* from the drop-down list.
. On the right side, select the *Target language* from the drop-down list.
. Expand the section *payment method* in the *PayUponPickup* area.
. Enter the text for the individual text elements in the area of the target language.
. Save (icon:save[role="green"]) the settings.

Find more information in how to edit online shop texts on the manual page <<online-store/setting-up-ceres#231, Editing online store texts>>.
