= Payone
:lang: en
include::{includedir}/_header.adoc[]
:keywords: payment method, payment, payments, Payone, payone-plugin, payone, payone payment method, payone method, payone account, payone-payment, payone-account, payone-merchant-interface, merchant-interface, merchant ID, portal ID, payone-configuration, payone-setting, secure invoice, payone credit card, payone-template, payone shipping, payone refund, payone integration, payment plugin, payment method plugin, payment method integration
:description: Integration of the Payone plugin.
:position:
:url: payment/payment-plugins/payone
:id: SKISHNV
:author: team-order-payment

With the Payone plugin, you integrate the Payone payment methods in your online shop and make them available to your customers. To do so, download the Payone plugin from the link:https://marketplace.plentymarkets.com/en/payone_5434[plentyMarketplace^]{nbsp}icon:external-link[]. You also have to carry out a few basic settings in your plentymarkets system so that the payment methods are activated in your system. +
The explanations in this section apply after adding the plugin. You can find more information on adding and installing plugins in the <<plugins#, Plugins>> section of the manual.

[IMPORTANT]
.Requirement
====
The Payone plugin has been developed for use with the online store Ceres and only works with its structure or other template plugins. The plugins Ceres and IO have to be activated so that the Payone plugin can be used.
====

[#10]
== Requirement: Opening a Payone account

In order to use Payone, you need a Payone account. You get information as well as login details when you open the account. Without these, the plugin cannot be set up and is not usable. If your don’t have a Payone account yet, use this link:https://www.psg-projektmanagement.de/payone-plentymarkets/[registration form^]{nbsp}icon:external-link[] or contact: +
PSG Projektmanagement GmbH +
Meergässle 4 +
89180 Berghülen +
Telephone: 00497344-9592588 +
Email: plenty@psg-projektmanagement.de +
Internet: http://www.psg-projektmanagement.de

Upon receipt of your access data, log into the PAYONE merchant interface and carry out the following settings.

[.instruction]
Carrying out settings in the Payone merchant interface:

. Open the *Configuration » Payment portals* menu.
. Open the *Extended Tab* of the payment portal of your online shop.
. In the field *TransactionStatusURL*, enter a URL following the pattern *DOMAIN/payment/payone/status*. Replace *DOMAIN* with the URL of your online shop.
. For the procedure *Method hash calculation*, select the option *md5 or sha2-384 (during migration)*.
. *Save* (icon:save[role="green"]) the settings.

[#20]
== Configuration of the plugin

The following steps for setting up the plentymarkets Payone plugin are carried out in the plugin overview of your plentymarkets system. To do so, proceed as described below.

[.instruction]
Carrying out the basic settings:

. Go to *Plugins » Plugin set overview*.
. Open the plugin set you want to edit.
. Open the plugin *Payone*. +
→ The plugin detail view opens.
. Open the menu entry *Configuration*.
. Click on *Basic settings*.
. Carry out the settings according to the information provided in <<table-payone-basic-settings>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-payone-basic-settings]]
.Carrying out basic settings
[cols="1,3"]
|====
|Setting |Explanation

| *Merchant ID*
|Enter the customer number as received after the registration process with Payone.

| *Portal ID*
|Enter the payment portal ID as received after the registration process with Payone.

| *Account ID*
|Enter the account ID as received after the registration process with Payone.

| *Key*
|Enter the key as received after the registration process with Payone.

| *Mode*
|Select one of the modes *Test* or *Live*.

| *Authorisation method*
|Select the method of authorisation.

|*User ID for notes*
|Enter the ID of the user who should be the owner of the order notes.

|====

After these basic settings, you have to carry out settings for those Payone payment methods you want to activate. To do this, proceed as follows.

[.instruction]
Carrying out the settings for payment methods:

. Go to *Plugins » Plugin set overview*.
. Open the plugin set you want to edit.
. Open the plugin *Payone*. +
→ The plugin detail view opens.
. Open the menu entry *Configuration*.
. Click on the payment method.
. Carry out the settings according to the information provided in <<table-payone-payment-methods-settings>>.
. *Save* (icon:save[role="green"]) the settings.

Repeat these instructions for other Payone payment methods you want to activate.

[[table-payone-payment-methods-settings]]
.Carrying out settings for payment methods
[cols="1,3"]
|====
|Setting |Explanation

| *Active*
|Select the option *Yes* to activate the payment method and thus offer it in the online shop. +
Select the option *No* if the payment method should be deactivated and thus not be available.

| *Name*
|Enter a name for the payment method. This name is visible for your customers in the online shop.

| *Description*
|Enter a description for the payment method. This text is visible for your customers in the online shop.

| *Minimum order value*
|Enter a minimum order value for which the payment method should be available in the online shop. If this minimum value is not reached, the Payone payment method is not available for this order.

| *Maximum order value*
|Enter a maximum order value for which the payment method should be available in the online shop.  If this value is exceeded, the Payone payment method is not available for this order.

| *Allowed countries of delivery*
|Activate (icon:check-square[role="blue"]) the delivery countries for which this Payone payment method is allowed.

|====

[#30]
=== Secure Invoice

You need a separate *Portal ID* and *Key* for the payment method *Secure Invoice*. This Portal-ID and this key have to be deposited in the plugin in the *Secure Invoice* area while configuring it. You get the Portal ID and the Key via the Payone Merchant Interface in the *Configuration » Payment portals* menu.

[#40]
=== Credit card

The payment method *Credit card* is a special case. Additional settings are needed for this payment method. These are described in <<table-settings-credit-card>>.

[[table-settings-credit-card]]
.Setting up the payment method Credit card
[cols="1,3"]
|====
|Setting |Explanation

| *Minimum card validity in days*
|Enter the required minimum card validity in days that a credit card must have to be accepted for the payment method.

| *Credit card fields default style*
|Default settings are saved for the colour, font size and font used for the data fields into which customers enter their credit card data in the online store. The values are editable.

| *Credit card fields height in px*
|The height of the data fields in px is set by default. The value is editable.

| *Credit card fields width in px*
|The width of the data fields in px is set by default. The value is editable.

| *Allowed card types*
|Activate the card types that should be accepted for the payment method.

|====

[#50]
=== Amazon Pay

In order to use the payment method *Amazon Pay* you have to link your Amazon account with Payone. To do so, contact the  link:https://www.payone.com/DE-de/kundenservice/kontakt/[Payone support^]{nbsp}icon:external-link[]. +
When setting up the payment method Amazon Pay, you can additionally to the other settings also activate the setting *Test-Environment*. This setting enables you to test the payment method first with test purchases. You cannot generate orders or turnover with these, they are solely for testing the payment method. Deactivate the setting *Test-Environment* to activate Amazon Pay. Note that you cannot use Amazon Pay if you have already integrated PayPal in *Mode 1*. In this mode, PayPal overwrites the entire checkout with the PayPal-Wall so that the widgtes Amazon Pay needs are not available.

[#60]
== Adapting the Ceres checkout

In the next step, an adjustment to your Ceres checkout settings is necessary. These adjustments need to be made so that customers using Payone for payment processes can enter their date of birth (for secure invoice only) correctly. There are two ways to do this. You can either use the ShopBuilder or configure the Ceres plugin accordingly. Both ways are described below.

[.tabs]
====
ShopBuilder::
+
--

[.instruction]
Adapting the ShopBuilder for the checkout:

. Select the widget category *Customer data* on your checkout ShopBuilder page.
. Select the widget *Address selection*.
. Click on the *Settings* (con:cog[]) of this widget.
. Select also *Date of birth* next to the other needed address fields for *Display input fields for invoice and delivery address*.
. *Save* (icon:save[role="green"]) the settings.

You can find additional information about the <</webshop/shop-builder#, ShopBuilder>> in general as well as the widget category <<webshop/shop-builder#85, Customer data>> in the Webshop section of the manual.

--

Ceres-Plugin::
+
--

[.instruction]
Adapt the Ceres checkout for Secure Invoice:

. Go to *Plugins » Plugin set overview*.
. Open the plugin set you want to edit.
. Open the plugin *Ceres*. +
→ The plugin detail view opens.
. Select *Ceckout and My account* in the *Configuration* menu.
. Set the toggle *Toggle deprecated entries* to active (green).
. Open the section *Show invoice address fields in address form (DE)*.
. Activate the option *Date of birth* by selecting the checkbox.
. *Save* (icon:save[role="green"]) the settings.

A field for entering the date of birth is now displayed for your customers in the checkout area.

[TIP]
.Input errors
======
Make sure to carefully carry out these settings. Otherwise, your customers will not be able to complete the payment process using Payone in your online shop.
======
--
====

[#70]
== Linking template containers

You have multiple options to integrate the payment method Payone into your online shop. To do this, the plentymarkets system offers containers at relevant places which can be filled with content to meet your needs.

[.instruction]
Linking template containers:

. Go to *Plugins » Plugin set overview*.
. Open the plugin set you want to edit.
. Open the plugin *Payone*. +
→ The plugin detail view opens.
. Click on *Container links*.
. From the drop-down list, select the data provider you want to link.
. Select the container you want to link to the data provider to. → Pay attention to the information provided in <<table-payone-template-container>>.
. Repeat steps 5 and 6 for all data providers you want to link to containers.
. *Save* (icon:save[role="green"]) the settings.

[[table-payone-template-container]]
.Linking template containers
[cols="1,3"]
|====
|Content |Explanation

| *Payone Order Confirmation Page Payment Data*
|Link this content to the container Order confirmation: Additional payment information to display the Payone payment methods on the order confirmation page in the online shop.

| *Payone Checkout JS*
|Link this content to the container Script loader: After script loaded to display the Payone payment methods during the checkout process in the online shop.

|====

[#20]
== Activating the payment method

include::../_textblocks/activate-payment-method.adoc[]

[#90]
== Customer classes and shipping profiles

include::../_textblocks/customer-class-and-shipping-profile.adoc[]

[#100]
== Setting up event procedures

Set up event procedures so that all needed data are sent to Payone. We recommend 2 event procedures for this.

[.collapseBox]
.*Setting up an event procedure*
--

[.instruction]
Setup of an event procedure:

. Go to *Setup » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the event as listed in tables 5 and 6.
. *Save* (icon:save[role="green"]) the settings.
. Carry out the settings according to tables 5 and 6
. Activate the option *Active*.
. *Save* (icon:save[role="green"]) the settings.

--

[#110]
=== Sending an automatic shipping confirmation to Payone

Set up an event procedure to send an automatic shipping confirmation to Payone as soon as you have shipped the order.

[IMPORTANT]
.Event procedure and Authorisation method
====
Setting up the following event procedure is mandatory if you have selected the option *Preauthorisation* as *Authorisation method* in the basic settings. This event procedure is not necessary and cannot be used if you have selected the option *Authorisation*.
====

[[table-procedure-payone-shipping-confirmation]]
.Event procedure for automatically sending shipping confirmations to Payone
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| Select the event after which an automatic shipping confirmation should be sent, e.g. *Order change > Outgoing items booked*.
|

| *Filter 1*
| Order > Payment method
| Plugin: PAYONE

| *Procedure*
| Plugin > Payone | Send shipping confirmation
|

|====

[#120]
=== Automatically refunding Payone payments

Set up an event procedure to automatically refund a Payone payment.

[[table-procedure-payone-refund]]
.Event procedure for automatically refunding Payone payments
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| Select the event that will trigger a refund.
|

| *Filter 1*
| Order > Payment method
| Plugin: PAYONE

| *Procedure*
| Plugin > PAYONE | Send refund
|

|====
