= ItemCrossSelling
:lang: de
include::{includedir}/_header.adoc[]
:description: Datenformat ItemCrossSelling
:position: 140

Das Datenformat **ItemCrossSelling** wird verwendet, um <<artikel/artikel-verwalten#950, **Cross-Selling-Artikel** >> zu exportieren, zu bearbeiten und zu importieren. Sie erstellen und exportieren das Datenformat im Menü **Datenaustausch » Export » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Datenaustausch » Import » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten **<<datenaustausch/daten-exportieren#, Daten exportieren  >>** und **<<datenaustausch/daten-importieren#, Daten importieren  >>** beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **ItemCrossSelling** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

[cols="a,a,a"]
|====
|Feldname |Erläuterung |Filter

|**CrossItemID**
|Cross-Selling-Artikel-ID
|

|**CrossItemNo**
|Cross-Selling-Artikelnummer
|

|**CrossSellingDelete**
|Cross-Selling-Artikel löschen +
**0** = Nein +
**1** = Ja
|

|**ItemID**
|Artikel-ID
|

|**ItemNo**
|Artikelnummer
|

|**Relationship**
|Beziehung zwischen Artikel und zugehörigem Cross-Selling-Artikel. +
**Accessory** = Zubehör +
**ReplacementPart** = Ersatzteil +
**Similar** = Ähnlicher Artikel +
**Bundle** = Artikelpaket
|Filter aktivieren, Operator und Wert aus dem Dropdown-Menü wählen.
|====

__Tab. 1: Datenfelder des Datenformats **ItemCrossSelling**__

== Übersicht der Pflichtfelder

Eines der folgenden Pflichtfelder muss für das Datenformat **ItemCrossSelling** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* **ItemID** oder **ItemNo**
* **CrossItemID** oder **CrossItemNo**

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<datenaustausch/daten-importieren#25, **Datenabgleich** >> zur Verfügung. Bei Pflichtabgleichfeldern (P) muss für die **Importaktion** die Option **Abgleich** gewählt werden.

[cols="a,a,a"]
|====
|Feldname |Erläuterung |Abgleichfeld

|**CrossItemID**
|Cross-Selling-Artikel-ID
|P

|**CrossItemNo**
|Cross-Selling-Artikelnummer
|Alternative zu **CrossItemID**

|**ItemID**
|Artikel-ID
|P

|**ItemNo**
|Artikelnummer
|Alternative zu **ItemID**
|====

__Tab. 2: Datenfelder mit Einstellung auf die Option **Abgleich**__

