= ItemImage
:lang: de
include::{includedir}/_header.adoc[]
:position: 151

Mit dem Datenformat **ItemImage** bearbeiten Sie die Optionen von im Tab **Bilder** eines Artikels verknüpften Artikelbildern. Mit diesem Datenformat exportieren, bearbeiten, importieren und löschen Sie Artikelbilder. Sie erstellen und exportieren das Datenformat im Menü **Datenaustausch » Export » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Datenaustausch » Import » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten **<<datenaustausch/daten-exportieren#, Daten exportieren  >>** und **<<datenaustausch/daten-importieren#, Daten importieren  >>** beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

toc::[]
== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **ItemImage** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

[cols="a,a,a"]
|====
|Feldname |Erläuterung |Filter

|**ItemImageID**
|Artikelbild-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**ItemImageItemID**
|Artikel-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**ItemImageType**
|Bildtyp; nur beim Export relevant
|Filter aktivieren und Bildtyp wählen. +
**INTERNAL** = Bilder, die am Artikel hinterlegt wurden. +
**EXTERNAL** = Bilder, deren Link über SOAP importiert wurde.

|**ItemImageFileType**
|Dateiformat: jpg, jpeg, png, gif oder svg
|

|**ItemImageURL**
|Artikelbild-URL
|

|**ItemImagePosition**
|Bildposition +
Wird keine Position gesetzt, wird beim Import die nächsthöchste Position verwendet.
|Filter aktivieren, Operator wählen und Wert eingeben.

|**ItemImageLastUpdate**
|Letzte Aktualisierung
|

|**ItemImageInserted**
|Datum, an dem das Bild hochgeladen wurde
|

|**ItemNo**
|Artikelnummer
|

|**ItemEAN1**
|EAN (internationale Artikelnummer)
|

|**ItemEAN2**
|Weitere EAN
|

|**ItemEAN3**
|Weitere EAN
|

|**ItemEAN4**
|Weitere EAN
|

|**AttributeValueID**
|ID des Attributwertes
|

|**ItemImageDelete**
|**1** = Artikelbild löschen +
Löscht Artikelbild unwiederbringlich, wenn der Wert 1 eingegeben wird. Weitere Informationen zu Filtern, siehe Handbuchseite **<<datenaustausch/daten-exportieren#20., Daten exportieren >>**.
|

|**VariationLink**
|Nur Import. Varianten-IDs eingeben, um ein Bild mit diesen Varianten zu verknüpfen. Mehrere Varianten-IDs durch Kommas trennen.
|
|====

__Tab. 1: Datenfelder des Datenformats **ItemImage**__

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat **ItemImage** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* **ItemImageItemID**
* **ItemNo**
* **ItemEAN1-4**

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<datenaustausch/daten-importieren#25., **Datenabgleich** >> zur Verfügung. Bei Pflichtabgleichfeldern (P) muss für die **Importaktion** die Option **Abgleich** gewählt werden. Die anderen Datenfelder können zusätzlich zum Abgleich verwendet werden. Alternative Abgleichfelder sind mit einem **A** gekennzeichnet.

[cols="a,a,a"]
|====
|Feldname |Erläuterung |Abgleichfeld

|**ItemEAN1-4**
|EAN (internationale Artikelnummer)
|A

// /tr>
//             <tr>
//                <td><strong>ItemID</strong></td>
//                <td>Artikel-ID</td>
//                <td>&nbsp;</td

|**ItemImageID**
|Artikelbild-ID +
Beim Aktualisieren von Bildern ist dieses Datenfeld ein Pflichtabgleichfeld.
|P

|**ItemNo**
|Artikelnummer
|A
|====

__Tab. 2: Datenfelder mit Einstellung auf die Option **Abgleich**__

