= ItemBundle
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenformat
:description: Datenformat ItemBundle
:position: 120

Das Datenformat **ItemBundle** wird verwendet, um Artikelpakete zu exportieren, zu bearbeiten und zu importieren. Dieses Datenformat ist nur bis plentymarkets 6 verfügbar. Sie erstellen und exportieren das Datenformat im Menü **Datenaustausch » Export » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Datenaustausch » Import » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten **<<datenaustausch/daten-exportieren#, Daten exportieren  >>** und **<<datenaustausch/daten-importieren#, Daten importieren  >>** beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

Tabelle 1 erläutert die Datenfelder des Datenformats **ItemBundle** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

[cols="a,a,a"]
|====
|Feldname |Erläuterung |Filter

|**AttributeValueSetID**
|ID der Artikelvariante
|

|**ItemID**
|Artikel-ID des Artikelpakets
|Filter aktivieren, Operator wählen und Wert eingeben.

|**ItemSourceID**
|Artikel-ID eines Basis-Artikels
|Filter aktivieren, Operator wählen und Wert eingeben.

|**PriceID**
|Preis-ID des Preises des Artikelpakets
|

|**Quantity**
|Menge
|
|====

__Tab. 1: Datenfelder des Datenformats **ItemBundle**__

