= VariationWebstoreLink
:lang: de
include::{includedir}/_header.adoc[]
:description: Datenformat VariationWebstoreLink
:position: 320

Mit dem Datenformat **VariationWebstoreLink** verknüpfen Sie Varianten mit Ihrem Webshop, damit diese im Webshop angezeigt werden. Sie erstellen und exportieren das Datenformat im Menü **Datenaustausch » Export » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Datenaustausch » Import » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten **<<datenaustausch/daten-exportieren#, Daten exportieren  >>** und **<<datenaustausch/daten-importieren#, Daten importieren  >>** beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **VariationWebstoreLink** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

[cols="a,a,a"]
|====
|Feldname |Erläuterung |Filter

|**VariationID**
|Varianten-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**VariationCustomNumber**
|Variantennummer
|

|**Mandant (Shop)**
|Sichtbarkeit des Mandanten (Shop). +
**VISIBLE** = Die Verfügbarkeit wird im Webshop angezeigt. +
**INVISIBLE** = Die Verfügbarkeit wird nicht im Webshop angezeigt.
|Filter aktivieren und Wert aus dem Dropdown-Menü wählen.
|====

__Tab. 1: Datenfelder des Datenformats **VariationWebstoreLink**__

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat **VariationWebstoreLink** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* **VariationID** oder **VariationCustomNumber**
* Webshop, der importiert werden soll

////
h2>Übersicht der Abgleichfelder</h2>
<p>Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <a href="{% Link(3183) %}#25."><strong>Datenabgleich</strong></a> zur Verfügung. Bei Pflichtabgleichfeldern muss für die <strong>Importaktion</strong> die Option <strong>Abgleich</strong> gewählt werden. Die anderen Datenfelder können zusätzlich zum Abgleich verwendet werden. Pflichtabgleichfelder sind mit einem <strong>P</strong> gekennzeichnet.</p>
<table>
<tr>
<th>Feldname</th>
<th>Erläuterung</th>
<th>Abgleichfeld</th>
</tr>
<tr>
<td><strong>##</strong></td>
<td>##</td>
<td>##</td>
</tr>
</table>
<p><em>Tab. 2: Datenfelder mit Einstellung auf die Option <b>Abgleich</b></em></p
////
