[.instruction]
Katalog öffnen:

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf den Katalog. +
→ Das Tab *Zuordnung* wird geöffnet. +
ifdef::amazon-flatfile[]
*_Hinweis:_* Der Katalog wird erst leer angezeigt. Je nach Größe der Flatfile kann es mehrere Minuten dauern, bis die Datenfelder geladen und angezeigt werden. +
endif::amazon-flatfile[]
→ In der linken Spalte werden die Datenfelder des Marktplatzes angezeigt. +
*_Tipp:_* Pflichtfelder sind mit Sternchen (*) gekennzeichnet. +
→ In der rechten Spalte ordnest du die plentymarkets Datenfelder zu. Bereits zugeordnete plentymarkets Datenfelder werden ebenfalls in der rechten Spalte angezeigt.

[.instruction]
ifdef::catalogue-assistant[Für ein Marktplatz-Datenfeld ein plentymarkets Datenfeld exportieren:]
ifndef::catalogue-assistant[Für ein Marktplatz-Datenfeld ein plentymarkets Datenfeld exportieren:]

. Klicke neben dem Marktplatz-Datenfeld auf *+ Datenfeld hinzufügen*. +
→ Links wird die Liste der verfügbaren plentymarkets Datenfelder als Gruppen angezeigt.
. Nimm die Zuordnung vor:
* .. Klicke auf die gewünschte Gruppe, um die plentymarkets Datenfelder anzuzeigen. +
  → Die plentymarkets Datenfelder werden angezeigt.
  .. Klicke neben dem gewünschten plentymarkets Datenfeld auf das Plus.
  .. *_Optional:_ Ein Ausweich-Datenfeld hinzufügen* +
  Nachdem du das Datenfeld zugeordnet hast, kannst du ein Ausweich-Datenfelder hinzufügen:
  Klicke dazu in der Liste der plentymarkets Datenfelder neben dem gewünschten plentymarkets Datenfeld auf das Plus. +
  → Das Ausweich-Datenfeld wird exportiert, wenn das erste Datenfeld nicht vorhanden oder leer ist. +
  *_Hinweis:_* Auch wenn du einem Marktplatz-Datenfeld Ausweich-Datenfelder zuordnest, wird für jede Variante nur ein Wert übertragen. Für jede Variante werden die Felder in der Reihenfolge geprüft, in der sie zugeordnet wurden. Wenn also das erste Datenfeld keinen Wert für die Variante liefert, wird das erste Ausweich-Datenfeld übertragen usw.
  .. Klicke auf *Bestätigen*.
. *Speichere* (icon:save[role="green"]) den Katalog. +
→ Die Zuordnungen werden gespeichert.

[.instruction]
Für ein Marktplatz-Datenfeld denselben Wert für alle Varianten exportieren:

. Klicke neben dem Marktplatz-Datenfeld auf *+ Datenfeld hinzufügen*. +
→ Links wird die Liste der verfügbaren plentymarkets Datenfelder als Gruppen angezeigt.
. Nimm die Zuordnung vor:
  . Klicke ganz oben neben *Eigener Wert* auf das Plus. +
  → Das Feld für den eigenen Wert wird in der Ansicht hinzugefügt.
  . Gib einen Wert in das Eingabefeld darunter ein. +
  → Dieser Wert wird für alle Varianten exportiert.
. *Speichere* (icon:save[role="green"]) den Katalog. +
→ Die Zuordnungen werden gespeichert.

[.collapseBox]
.*_Optional:_* 1:n-Zuordnung - Für 1 Marktplatz-Datenfeld mehrere plentymarkets Datenfelder kombiniert exportieren
--
. Ordne dem Marktplatz-Datenfeld wie oben beschrieben ein plentymarkets Datenfeld oder einen eigenen Wert zu.
. Klicke rechts neben dem zugeordneten plentymarkets Datenfeld auf *Datenfeld hinzufügen* (icon:link[rotate=90]). +
→ Links wird die Liste der verfügbaren plentymarkets Datenfelder wieder als Gruppen angezeigt.
. Ordne dem Marktplatz-Datenfeld wie oben beschrieben ein oder mehrere weitere plentymarkets Datenfelder zu.
. Klicke auf *Bestätigen*.
. Klicke ganz rechts in der Zeile des Marktplatz-Datenfelds auf *Einstellungen* (icon:cog[]).
. Wähle aus der Dropdown-Liste *Trennzeichen* ein Trennzeichen oder bestimme ein eigenes Trennzeichen.
. Klicke auf *Speichern*.
. *Speichere* (icon:save[role="green"]) den Katalog. +
→ Die Zuordnungen werden gespeichert. +
→ Beim Export wird der Inhalt der plentymarkets Datenfelder kombiniert exportiert.
--

////
[#datenfelder-zuordnen]
=== Datenfelder im Katalog zuordnen

include::../../_textblocks/catalogues/instructions/catalogue-mapping.adoc[]
////
