[.instruction]
ifdef::catalogue-assistant[Weitere Datenfelder im Katalog zuordnen:]
ifndef::catalogue-assistant[Datenfelder im Katalog zuordnen:]

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf den Katalog. +
→ Das Tab *Zuordnung* mit den Marktplatz-Datenfeldern wird geöffnet. +
ifdef::amazon-flatfile[]
*_Hinweis:_* Der Katalog wird zunächst leer angezeigt. Je nach Größe der Flatfile kann es mehrere Minuten dauern, bis die Datenfelder geladen und angezeigt werden. +
endif::amazon-flatfile[]
→ In der linken Spalte werden die Datenfelder des Marktplatzes angezeigt. +
*_Tipp:_* Pflichtfelder sind mit Sternchen (*) gekennzeichnet.
. Klicke neben einem Marktplatz-Datenfeld auf *+ Datenfeld hinzufügen*. +
→ Links wird die Liste der verfügbaren plentymarkets Datenfelder als Gruppen angezeigt.
. Nimm die Zuordnung vor:
* *_Möglichkeit 1:_ Ein plentymarkets Datenfeld zuordnen*
  .. Klicke auf die gewünschte Gruppe, um die plentymarkets Datenfelder anzuzeigen. +
  → Die plentymarkets Datenfelder werden angezeigt.
  .. Klicke neben dem gewünschten plentymarkets Datenfeld auf das Plus.
  .. *_Optional:_ Ein Ausweich-Datenfeld hinzufügen* +
  Nachdem du das Datenfeld zugeordnet hast, kannst du ein Ausweich-Datenfelder hinzufügen:
  Klicke dazu in der Liste der plentymarkets Datenfelder neben dem gewünschten plentymarkets Datenfeld auf das Plus. +
  → Das Ausweich-Datenfeld wird exportiert, wenn das erste Datenfeld nicht vorhanden oder leer ist. +
  *_Hinweis:_* Auch wenn du einem Marktplatz-Datenfeld Ausweich-Datenfelder zuordnest, wird für jede Variante nur ein Wert übertragen. Für jede Variante werden die Felder in der Reihenfolge geprüft, in der sie zugeordnet wurden. Wenn also das erste Datenfeld keinen Wert für die Variante liefert, wird das erste Ausweich-Datenfeld übertragen usw.
  .. Klicke auf *Bestätigen*.
* *_Möglichkeit 2:_ Für ein Marktplatz-Datenfeld immer denselben Wert übergeben*
    .. Klicke ganz oben neben *Eigener Wert* auf das Plus. +
    → Das Feld für den eigenen Wert wird in der Ansicht hinzugefügt.
    .. Gib einen Wert in das Eingabefeld darunter ein. +
    → Dieser Wert wird für alle Varianten exportiert.
. Ordne analog alle Datenfelder des Marktplatzes zu, für die du Produktinformationen übertragen möchtest. +
. *Speichere* (icon:save[role="green"]) den Katalog. +
→ Die Zuordnungen werden gespeichert.

[.collapseBox]
.*_Optional:_* 1:n-Zuordnung - 1 Marktplatz-Datenfeld, mehrere plentymarkets Datenfelder
--
. Ordne dem Marktplatz-Datenfeld wie oben beschrieben ein plentymarkets Datenfeld oder einen eigenen Wert zu.
. Klicke rechts neben dem zugeordneten plentymarkets Datenfeld auf *Datenfeld hinzufügen* (icon:link[rotate=90]). +
→ Links wird die Liste der verfügbaren plentymarkets Datenfelder wieder als Gruppen angezeigt.
. Ordne dem Marktplatz-Datenfeld wie oben beschrieben ein oder mehrere weitere plentymarkets Datenfelder zu.
. Klicke auf *Bestätigen*.
. Klicke ganz rechts in der Zeile des Marktplatz-Datenfelds auf *Einstellungen* (icon:cog[]).
. Wähle aus der Dropdown-Liste *Trennzeichen* ein Trennzeichen oder bestimme ein eigenes Trennzeichen.
. Klicke auf *Speichern*.
. *Speichere* (icon:save[role="green"]) den Katalog. +
→ Die Zuordnungen werden gespeichert. +
→ Beim Export wird der Inhalt der plentymarkets Datenfelder kombiniert exportiert.
--

////
[#datenfelder-zuordnen]
=== Datenfelder im Katalog zuordnen

include::../../_textblocks/catalogues/instructions/catalogue-mapping.adoc[]
////
