[#change-elastic-export-catalogue]
=== _Möglichkeit 3:_ Wechsel von elastischem Export zu Katalog

Du exportierst schon Artikeldaten mit dem elastischen Export an {market} und möchtest zum Katalogexport wechseln? Dazu erstellst du wie im Kapitel <<#catalogue-export, Katalogexport>> beschrieben einen Katalog.

Um einen reibungslosen Übergang zu schaffen, empfehlen wir die folgende Vorgehensweise:

. Prüfe zuerst, welche Merkmale du aktuell für {market} verwendest. Merkmale und Freitextfelder können für den Katalogexport nicht mehr verwendet werden. Erstelle deshalb Eigenschaften für alle Merkmale, die du weiterhin benötigst. +
*_Wichtig:_* Die Werte der neuen Eigenschaften müssen mit den Werten der alten Merkmale identisch sein. Sonst kann es passieren, dass beim Export zu {market} neue Artikel erstellt werden.
. Erstelle einen Katalog für {market}. (<<#catalogue-creation, Wie?>>)
. Ordne den Marktplatz-Datenfeldern von {market} dieselben plentymarkets Datenfelder zu, die zurzeit auch über den elastischen Export an {market} exportiert werden. (<<#data-field-mappings, Wie?>>) +
////
*_Tipp:_* In <<#elastic-export-catalogue-mappings>> findest du Informationen dazu, welche Datenfelder im elastischen Export welchen Marktplatz-Datenfeldern im Katalog entsprechen.
////
. Hast du im elastischen Export Artikeldaten gefiltert? Dann verwende dieselben Filter auch im Katalog. (<<#filter-export, Wie?>>)
. Nimm die Exporteinstellungen vor. Damit erstellst du eine URL für {market}. (<<#catalogue-settings, Wie?>>)
. Aktiviere den Katalog (<<#catalogue-activation, Wie?>>)
. Speichere die URL des Katalogs bei {market}. (<<#catalogue-url, Wie?>>)

[IMPORTANT]
.Elastischen Export exakt nachstellen
====
Damit der Artikelexport beim Wechsel vom elastischen Export auf den Katalog weiterhin funktioniert, musst du deinen vorherigen elastischen Export im Katalog exakt nachstellen. Das bedeutet, dass du im Katalog genau die gleichen Datenfelder zuordnen musst, die im elastischen Export an das Preisportal übertragen wurden. Wenn du andere Datenfelder als im elastischen Export zuordnest, kann es passieren, dass beim Export neue Artikel erstellt werden.
====

////
<<#elastic-export-catalogue-mappings>> zeigt, welche Spalten im elastischen Export welchen Datenfelder des Katalogs entsprechen.
////
