[#change-elastic-export-catalogue]
=== Wechsel von elastischem Export zu Katalog

Du exportierst schon Artikeldaten mit dem elastischen Export an {market} und möchtest zum Katalogexport wechseln? Dazu erstellst du wie im Kapitel <<#catalogue-export, Katalogexport>> beschrieben einen Katalog.

Um einen reibungslosen Übergang zu schaffen, empfehlen wir die folgende Vorgehensweise:

. Merkmale und Freitextfelder können für den Katalogexport nicht mehr verwendet werden. Prüfe deshalb zuerst, welche Merkmale du aktuell für {market} verwendest. Erstelle Eigenschaften für alle Merkmale, die du weiterhin benötigst. +
*_Wichtig:_* Die Werte der Eigenschaften müssen mit den Werten der Merkmale identisch sein. Sonst kann es passieren, dass beim Export zu {market} neue Artikel erstellt werden.
. <<#catalogue-creation, Katalog für {market} erstellen>>.
. Den Marktplatz-Datenfeldern von {market} dieselben plentymarkets <<#data-field-mappings, Datenfelder zuordnen>>, die zurzeit auch über den elastischen Export an {market} exportiert werden. +
*_Tipp:_* In <<#elastic-export-catalogue-mappings>> findest du Informationen dazu, welche Datenfelder im elastischen Export welchen Marktplatz-Datenfeldern im Katalog entsprechen.
. Bei Bedarf bestimmte Artikeldaten über die <<#filter-export, Filter>> vom Export ausschließen.
. Katalogeinstellungen vornehmen.
. <<#catalogue-activation, Katalog aktivieren>>.
. <<#catalogue-url, Katalogdaten an {market} übergeben.

[IMPORTANT]
.Elastischen Export exakt nachstellen
====
Damit der Artikelexport beim Wechsel vom elastischen Export auf den Katalog weiterhin funktioniert, musst du deinen vorherigen elastischen Export im Katalog exakt nachstellen. Das bedeutet, dass du im Katalog genau die gleichen Datenfelder zuordnen musst, die im elastischen Export an das Preisportal übertragen wurden. Wenn du andere Datenfelder als im elastischen Export zuordnest, kann es passieren, dass beim Export neue Artikel erstellt werden.
====

////
In <<#elastic-export-catalogue-mappings>> findest du Empfehlungen für die Zuordnung von Datenfeldern im Katalog.

[[#elastic-export-catalogue-mappings]]
[cols="2,1,3a"]
|====
|Spalte im elastischen Export |Datenfeld im Katalog |Empfohlene plentymarkets Zuordnung

|
|
|
|====
////
