= Begleitmaterial zum Webinar "Das Einmaleins des Shop-Designs"
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webinar, CSS, Ceres, Plugina, Webshop
:description: Begleitmaterial zum Webinar "Das Einmaleins des Shopdesigns - Mit eigenem CSS zum individuellen Webshop"
:position: 50
:url: webshop/referenz/webinar-css

[#10]
In link:https://vimeo.com/335379273[Das Einmaleins des Shop-Designs - mit eigenem CSS zum individuellen Webshop^] haben wir dir gezeigt, wie man mit dem Plugin *CustomCSS* und einigen einfachen Handgriffen weitreichende Änderungen am Design des Ceres-Webshops erzielen kann. Da man im Eifer des Gefechts nicht immer durch ein fast einstündiges Video klicken muss, findest du hier alle Anpassungen, die wir dir im Webinar eingebaut haben. +
Das notwendige kostenlose Plugin findest du link:https://marketplace.plentymarkets.com/plugins/widgets/CfourCustomCssJs_5143[hier^]. Wie man das Plugin dem System hinzufügt, erfährst du auf unserer <<plugins-neue-plugins#, Handbuchseite zu Plugins>>. +


[#20]
== CSS-Anpassungen


=== Hindergrundfarbe der Top-Bar ändern

[source,plenty]
----
include::../assets/css-topbar.html[]

----

=== Schriftart des Titelleisten-Widgets ändern

[source,plenty]
----
include::assets/css-title-bar-font.html[]

----

=== Schriftgröße im Titelleisten-Widgets ändern

[source,plenty]
----
include::assets/css-title-bar-fontsize.html[]

----

=== Hintergrundbild ändern

[source,plenty]
----
include::assets/css-background-image.html[]

----

=== Transparenten Layer über Hintergrundbild legen

[source,plenty]
----
include::assets/css-background-transparent.html[]

----

=== Parallax-Effekt von Kategoriebildern entfernen

[source,plenty]
----
include::assets/css-remove-parallax.html[]

----

=== Textfarbe der Artikelnamen in Artikellisten ändern

[source,plenty]
----
include::assets/css-font-colour-item-names.html[]

----

=== Rahmen für Artikel in Artikellisten

[source,plenty]
----
include::assets/css-item-frame.html[]

----

=== Abstände der Artikellisten ändern

[source,plenty]
----
include::assets/css-paddings-list.html[]

----


=== Zum Warenkorb hinzufügen-Symbol entfernen

[source,plenty]
----
include::assets/css-add-basket.html[]

----

=== Streichpreis einfärben

[source,plenty]
----
include::assets/css-strikethrough-price.html[]

----

=== Den Hover-Effekt der Artikelliste auf der Artikelansicht hinzufügen

[source,plenty]
----
include::assets/css-add-hover.html[]

----
