= ItemView
:lang: de
// include::{includedir}/_header.adoc[]
:keywords: ItemView, Seitenansichten, Webdesign, CMS
:position: 40

*CMS » Webdesign » Layout » ItemView*

== Inhalt dieser Seite

Die folgenden Kapitel beschreiben die Artikelansichten in plentymarkets, also den Seitenaufbau anhand der im Bereich *ItemView* verfügbaren Templates. Sie erhalten einige Grundinformationen zur Verwendung der Templates sowie zur HTML-Struktur. Weitere Details werden in Anwendungsbeispielen ausführlicher behandelt.

[IMPORTANT]
.Grundstrukturen im plentymarkets-CMS
====
Wir weisen darauf hin, dass Sie zur Bearbeitung der Templates im plentymarkets-CMS über gewisse Grundkenntnisse im Bereich HTML und CSS verfügen sollten. Darüber hinaus empfehlen wir Ihnen, die grundlegenden Erläuterungen des Kapitels <<omni-channel/online-shop/webshop-einrichten/cms#webdesign, Webdesign>> sorgfältig zu lesen. Beachten Sie besonders das Kapitel <<omni-channel/online-shop/webshop-einrichten/cms-syntax#, Grundlagen der Syntax>>, bevor Sie das Template anpassen. Die Handbuchseite <<omni-channel/online-shop/webshop-einrichten/_cms/webdesign/syntax/seitenaufbau#, Seitanaufbau>> gibt Ihnen einen Überblick zur Templatestruktur in plentymarkets.
====

== Allgemeines zu Artikelansichten

Neben dem Template *ItemViewSingleItem*, dem grundlegenden Template zur Darstellung eines Artikels, enthält der Bereich ItemView eine Fülle an Templates zur Gestaltung von Artikelauflistungen, z.B. wie das Ergebnis einer Artikelsuche im Webshop dargestellt wird oder die Auswahl von Artikeln anhand eines Filters. Auch für die Darstellung von Cross-Selling-Artikeln oder Sonderangeboten gibt es jeweils spezielle Templates.

Das folgende Beispiel zeigt einen Ausschnitt aus der Codestruktur des Templates *ItemViewSingleItem*, das eine Artikeldetailansicht enthält.

[TIP]
.Beispiel Artikeleigenschaften
====
Hier ein einfaches Beispiel, wie die Artikeleigenschaften *Name* (Name), *Preis* (Price) mit *Währungssymbol* (CurrencySign), *Mehrwertsteuerhinweis* (VATHint) und *MwSt*-Anzeige (VAT) sowie einem Link auf die *Versandkostenseite* im Code umgesetzt werden können:

&lt;h1&gt;$Name[1]&lt;/h1&gt;

&lt;span class="price"&gt;$Price$CurrencySign&lt;/span&gt; +
&lt;span class="smallText"&gt;$VATHint$VAT% &lt;a href="{&amp;#037; Link_ShippingCosts()  &amp;#037;}" title="Versandkosten"&gt;Versandkosten&lt;/a&gt;
====

Die verschiedenen Parameter des Artikels, wie *Name* oder *Preis*, werden mit den entsprechenden <<omni-channel/online-shop/webshop-einrichten/cms-syntax#grundlagen-template-variablen, Template-Variablen>> umgesetzt.

== Artikelansichten: Templates

Für die Gestaltung der Artikelansichten ist eine Fülle an unterschiedlichen Templates verfügbar, von denen nachfolgend beispielhaft die wichtigsten genannt werden. Detailinformationen zu den Templates finden Sie im Kapitel <<omni-channel/online-shop/webshop-einrichten/cms-syntax#, CMS-Syntax>> unter der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview, ItemView>>.

[.subhead]
ItemViewSingleItem

Darstellung der <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewsingleitem, Artikeldetailansicht>> im Webshop.

[.subhead]
ItemViewSearchResultsList

Stellt das Ergebnis einer Artikelsuche im Webshop in Form einer Listenansicht dar.

[.subhead]
ItemViewFilterResultsList

Darstellung einer Liste der mit einer Filterfunktion gefundenen Artikel. Ein Beispiel ist ein Merkmalfilter.

[.subhead]
ItemViewCategoriesList

Auflistung der Artikel einer im Webshop gewählten <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewcategorieslist, Kategorie>>.

[.subhead]
ItemViewCrossSellingItemsList

Auflistung der <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewcrosssellingitemslist, Cross-Selling-Artikel>>.

[.subhead]
ItemViewTopSellersList

Auflistung der <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-getitemviewtopsellerslist, Top-Seller-Artikel>>.

[.subhead]
ItemViewSpecialOffersList

Auflistung von <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-getitemviewspecialofferslist, Sonderangeboten>>.

[.subhead]
ItemViewLatestItemsList

Auflistung der zuletzt zum Webshop <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewlatestitemslist, hinzugefügten Artikel>>.

[.subhead]
ItemViewItemsByPositionList

Liste der <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewitemsbypositionlist, meistverkauften Artikel>>. Wird über Nacht aktualisiert.

[.subhead]
ItemViewLastSeenList

Auflistung der <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewlastseenlist, zuletzt betrachteten Artikel>>.

[.subhead]
ItemViewRandomList

Auflistung vom System <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewrandomlist, zufällig ausgewählter Artikel>>.

[.subhead]
ItemViewItemImagesList

Darstellung von Artikelbildern in Listenform.
