= Mein Konto
:lang: de
// include::{includedir}/_header.adoc[]
:keywords: Mein Konto, Webdesign, CMS
:position: 90

*CMS » Webdesign » Mein Konto*

== Inhalt dieses Kapitels

In diesem Kapitel erhalten Sie detaillierte Erläuterungen zur Anpassung des Bereichs *Mein Konto* im Webshop.

*Mein Konto* bezeichnet den Bereich im Webshop, in den nur registrierte Kunden gelangen. Hier können Kunden alle bisher getätigten Käufe sowie angegebene Informationen wie z.B. Kontaktdaten sehen.

Der Mein Konto-Bereich im Menü *CMS* bietet Ihnen individuelle Möglichkeiten, das Frontend zu gestalten. Übersichtliche Untermenüs ermöglichen eine sehr genaue Konfiguration.

== Grundeinstellungen

Das Menü <<omni-channel/mandant-shop/standard/mein-konto/grundeinstellungen#, System » Systemeinstellungen » Mandant » Mandant wählen » Mein Konto » Einstellungen>> enthält wichtige Grundeinstellungen für den Mein Konto-Bereich Ihres Webshops. So können Sie hier z.B. einige fakultative Kontobereiche aktivieren bzw. deaktivieren.

== Mein Konto: Design bearbeiten

Dieser Bereich ist bereits vorkonfiguriert. Sie haben jedoch vielfältige Änderungsmöglichkeiten.

[TIP]
.CSS-Anpassung
====
Sie können das CSS anpassen. In plentymarkets sind jedoch auch vorkonfigurierte CSS-Regeln hinterlegt. Sie finden diese im Templateordner *Layout* unter *CSS*. Die CSS-Regeln sind im Ordner *CSS* und dort unter *CSSMyAccount* hinterlegt und können in dem entsprechenden Tab einfach angepasst werden.
====

Folgende Bereiche können Sie im Tab *Mein Konto* in den entsprechenden Unterordnern individuell anpassen:

* *Login*
* *Mein Konto*
* *Kundendaten*
* *Persönliche Daten*
* *Kontaktinformationen*
* *Bankinformationen*
* *Passwort ändern*

* *Newsletter*
* *Auftragshistorie*
* *Bestellübersicht*
* *Lieferanschrift ändern*
* *Versandart ändern*
* *Zahlungsart ändern*
* *Artikel ändern*

* *Retoure*

* *Abonnementhistorie*
* *Abonnementübersicht*
* *Abonnement ändern*
* *Artikel ändern*

* *Merkliste*
* *Wunschzettel*
* *Tickets*
* *Gutscheine*
* *Zeitkonto*
* *Dokumente*
* *Datenexport*

Einige Felder und Einstellungen tauchen in mehreren der oben genannten Menüs und Untermenüs auf und werden nachfolgend erläutert. Spezielle Funktionen finden sich in den Erläuterungen zum jeweiligen Menü.

=== Wiederkehrende Einstellungen

Hier werden Einstellungen erläutert, die in mehreren Untermenüs des Mein Konto-Bereichs auftauchen. Einige dieser Einstellungen kommen auch im Bereich *Bestellvorgang* vor und sind Ihnen vielleicht schon bekannt.

.Erläuterungen zu mehrfach vorkommenden Einstellungen der Untermenüs
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Titel
|Die Menü-Überschrift, die Kunden im Webshop angezeigt werden soll.

|Text vor &amp; Text nach
|Hinweise oder Begrüßungstexte passend zum Menü hinterlegen. +
Diese beiden Felder schließen jeweils alle Punkte eines Menüs ein, d.h. *Text vor* steht direkt unter dem Titel und *Text nach* erst nach allen anderen Menüpunkten.

|Position (Hauptmenüpunkt)
|Die Reihenfolge der Menüs in der Hauptebene durch Auswahl der Positionsnummer aus der Dropdown-Liste festlegen.

|Position (Untermenü)
|*Container 1*: Wird links in der Bestellübersicht angezeigt. +
*Container 2*: Wird rechts in der Bestellübersicht angezeigt. +
Mit den Positionsnummern die Reihenfolge festlegen. +
Werden z.B. für alle Elemente *Container 1* und fortlaufende Positionsnummern gewählt, erscheinen die Elemente links untereinander in der durch die Positionsnummern bestimmten Reihenfolge. +
Beide Container nutzen, um Elemente nebeneinander zu positionieren.

|Position (Untermenü Artikel)
|Das Untermenü Artikel *unten* oder *oben* positionieren. +
*Oben* = über den weiteren Untermenüs des Bereichs +
*Unten* = unter diesen Untermenüs

|Darstellung
|*Direkte Anzeige* = Der gesamte Inhalt eines Menüpunkts wird im Webshop angezeigt. Das Menü ist ausgeklappt. +
*Anzeige nach Klick* = Nur der Menütitel wird angezeigt. Wenn der Kunde auf den Menütitel klickt, werden sämtliche Informationen angezeigt.

|Details anzeigen
|Der hier eingetragene Text ist im Webshop verlinkt und leitet den Kunden zu einer Detailansicht.

|Keine Artikel gefunden
|Der hier eingetragene Hinweis wird Kunden angezeigt, wenn Kunden z.B. keine Artikel in der Merkliste oder auf dem Wunschzettel haben.
|====


=== Individuelle Einstellungen der Mein-Konto-Untermenüs

Die Einstellungen in den Untermenüs wurden möglichst selbsterklärend benannt. Der Text, den Sie in die Textfelder eintragen, wird Ihren Kunden im Webshop angezeigt.

.Erläuterungen zu den Einstellungen der Untermenüs
[cols="1,3"]
|====
|Menüpunkt |Erläuterung

|CSS Mein Konto
|In diesem Bereich erfolgt die Gestaltung (Layout) der Kundenkonten per CSS. Eine Standard-CSS-Formatierung legt die allgemeinen CSS-Regeln für Kundenkonten fest. Hier kann auch der gesamte CSS-Code für den Bereich *Mein Konto* eintragen werden. Alternativ hier nur den allgemein gültigen Teil eintragen. Für mehr Übersichtlichkeit dann in den nachfolgenden Bereichen im Feld *CSS* die Informationen eintragen, die dann nur für den Bereich gültig sind.

|Login
|Die hier eingetragenen Informationen sieht der Kunde, nach Klick auf das Tab *Mein Konto* im Webshop. Eine *CSS*-Formatierung ist voreingetragen. Wenn die Informationen in diesem Menü anders angeordnet werden sollen, erfolgt die Anpassung mittels CSS. +
*Passwortsicherheit* +
Für das Passwort genügen 6 Zeichen. Die Sicherheitsstufe im Webshop ist nicht so hoch wie im Admin-Bereich. Daher genügt für das Passwort der Login-Daten die einfache Mischung aus Buchstaben und Ziffern. Siehe Handbuchseite <<basics/admin-aufgaben/benutzer-verwalten#10, Benutzer anlegen>>.

|Mein Konto
|Der Kunde gelangt in diesen Bereich nachdem der Kunde die Login-Daten eingetragen und auf *Anmelden* geklickt hat. Eine CSS-Formatierung ist voreingetragen. Darüber kann ein Hinweis (*Text vor*) stehen. Darunter sieht der Kunde sämtliche Bereiche des Kundenkontos. Diese Bereiche sind die Untermenüs der ersten Ebene des *Mein Konto-Bereichs*, z.B. *Kundendaten* und *Auftragshistorie*. Die Informationen können mittels CSS anders angeordnet werden.

|Kundendaten
|Eine CSS-Formatierung ist voreingetragen. Die hier angezeigten Daten stammen z.B. aus den bisherigen Einkäufen des Kunden und den dort gemachten Angaben. Die Kundendaten gliedern sich wiederum in einige Untermenüs. Unter *Persönliche Daten* sieht der Kunde die Rechnungsadresse, die der Kunde eingetragen hat, unter *Kontaktinformationen* die für den Login verwendete E-Mail-Adresse. Diese Daten können vom Kunden durch Klicken auf *Ändern* bearbeitet werden. +
Die Fenster, die sich für den Kunden nach dem Klick auf *Ändern* öffnen, werden in den Kundendaten-Untermenüs bearbeitet. Das Fenster *Lieferanschrift* wird im gleichnamigen Untermenü der Auftragshistorie bearbeitet.

|Newsletter
|Titel für den Bereich <<crm/newsletter-versenden#, Newsletter>> sowie die Position und die Art der Darstellung.

|Auftragshistorie
a|Die Felder *Auftrags-ID* und *Zeitraum wählen* gehören zur Auftragssuche im Kundenkonto. Die Felder *Auftragsdatum*, *Empfänger*, *Details anzeigen*, *Status* und *Voraussichtlicher Versand* werden für jeden Auftrag in der Historie angezeigt.
* *Bestellübersicht* +
Die Bestellübersicht ist die Detailansicht eines bestimmten Auftrags mit allen dazugehörigen Daten.
* *Lieferanschrift* +
In diesem Untermenü werden die Eintragsfelder konfiguriert und benannt, die der Kunde sieht. Diese werden auch für die Kundendaten genutzt.
* *Versandart* +
In diesem Untermenü werden die Eintragsfelder für den Bereich *Versandart* konfiguriert und benannt, die der Kunde sieht.
* *Zahlungsart* +
In diesem Untermenü werden die Eintragsfelder für den Bereich *Zahlungsart* konfiguriert und benannt, die der Kunde sieht.
* *Artikel* +
In diesem Untermenü werden die Eintragsfelder für den Bereich *Artikel* konfiguriert und benannt, die der Kunde sieht.

* *Retoure* +
Sobald ein Auftrag vom Kunden bezahlt und versandt wurde und der Auftrag sich also in *Status 7* befindet, wird im Kundenkonto die Schaltfläche *Artikel zurück senden* angezeigt. Klickt der Kunde darauf, wird das Menü geöffnet, das hier konfiguriert wird. Das Feld *Grund der Retoure* ist eine Dropdown-Liste. Die dort wählbaren Gründe werden im System unter <<auftraege/auftraege-verwalten#400, System » Systemeinstellungen » Aufträge » Auftragstypen » Retouren>> angelegt.

|Abonnementhistorie
|Nur sichtbar, wenn diese Funktion aktiviert ist. +
Die Felder *Auftragsnummer* und *Zeitraum wählen* dienen der Abonnementsuche im Kundenkonto. Die Felder *Empfänger*, *Erste Versendung* etc. werden für jedes Abonnement angezeigt. Über *Details anzeigen* gelangt der Kunde in die Einzelansicht eines bestimmten Abonnements. +
*Abonnementübersicht* +
Die Abonnementübersicht ist die Detailansicht eines bestimmten Abonnements. Hier werden die Position und der Titel der einzelnen Untermenüs, wie Versandart und Artikel, dieses Bereichs angepasst. Die eigentlichen Felder für die Einträge werden in den Untermenüs der Bestellübersicht konfiguriert.

|Merkliste
|Die Funktion <<omni-channel/mandant-shop/standard/mein-konto/grundeinstellungen#, Merkliste>> wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Mein-Konto » Grundeinstellungen* aktiviert. Mit der Funktion *Merkliste* stellen Kunden mit Benutzerkonto im Webshop eine Liste der Artikel zusammen, die sich Kunden merken bzw. evtl. kaufen möchten. Eine Position verschwindet erst von der Merkliste, wenn die Position gelöscht oder in den Warenkorb verschoben wird. +
Schaltfläche *Merkliste* +
Wenn die Funktion Merkliste nicht aktiviert wird, sollte auch die Schaltfläche *Merkliste* aus dem Webshoplayout entfernt werden. Dazu das Menü *CMS » Webdesign » Ordner: Layout* öffnen und *ItemViewSingleItem* aus den *ItemView-Templates* wählen. Den entsprechenden Code entfernen.

|Wunschzettel
|Die Funktion <<omni-channel/mandant-shop/standard/mein-konto/grundeinstellungen#, Wunschzettel>> wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Mein-Konto » Grundeinstellungen* aktiviert. Mit der Funktion können Kunden mit Benutzerkonto im Webshop eine Liste von Artikeln zusammenstellen, die Kunden evtl. kaufen, sich schenken lassen oder sich aus anderen Gründen merken möchten. Ein Wunschzettel wird meist angelegt, um ihn anderen zu zeigen. Eine Position verschwindet erst vom Wunschzettel, wenn die Position gelöscht oder in den Warenkorb verschoben wird. +
Schaltfläche *Wunschzettel* +
Wenn die Funktion Wunschzettel nicht aktiviert wird, sollte auch die Schaltfläche *Wunschzettel* aus dem Webshop-Layout entfernt werden. Dazu das Menü *CMS » Webdesign » Ordner: Layout* öffnen und *ItemViewSingleItem* aus den *ItemView-Templates* wählen. Den entsprechenden Code entfernen.

|Tickets
|Dieser Menüpunkt wird nur angezeigt, wenn das <<crm/ticketsystem-nutzen#, Ticketsystem>> als Erweiterung gebucht wurde. Das plentymarkets-Modul "Ticketsystem STARTER" ist kostenlos buchbar. +
In diesem Menü die für den Kunden sichtbaren Eintragsfelder des Bereichs *Tickets* konfigurieren und benennen.

|Gutscheine
|Die Funktion *Gutschein* wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Mein-Konto » Grundeinstellungen* aktiviert.

|Dokumente
|In diesem Menü sieht der Kunde Dokumente, die im Menü *CMS » Dokumente* hochgeladen wurden und bei denen unter *Berechtigung* die Einstellung *Kunden* gewählt wurde.

|Datenexport
|Mit dieser Funktion wird z.B. für Firmenkunden eine Artikelliste zur Verfügung gestellt. Dazu unter <<daten/export-import/daten-exportieren#, Daten » Dynamischer Export>> ein neues Datenformat konfigurieren. In den Filtereinstellungen für das Datenformat ein Häkchen vor *Export für Kundenklasse* setzen, um den Filter zu aktivieren. Unter *Wert* die Kundenklasse wählen, für die das Datenformat zur Verfügung stehen soll. Je nach Kundenklasse sieht der Kunde die entsprechenden Daten im Menü *Datenexport* des Kundenkontos.
|====


[IMPORTANT]
.jQuery
====
In diesem Bereich sind jQuery-Funktionen integriert. Wenn Sie diese Funktionen anpassen oder erweitern möchten, beachten Sie die Hinweise auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/_cms/webdesign/syntax/jquery#, jQuery>>.
====
