= Plugins verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: So verwalten Sie Plugins im plentymarkets Backend.
:position: 30

Über das Menü **Plugins** verwalten und veröffentlichen Sie im link:https://marketplace.plentymarkets.com/[plentyMarketplace^] erworbene Plugins sowie selbsterstellte Plugins. Installieren Sie neue Plugins, ändern Sie den Zustand vorhandener Plugins, um sie zu veröffentlichen, und löschen Sie Plugins. Wie Sie Plugins selbst erstellen, erfahren Sie auf link:http://developers.plentymarkets.com/[plentyDevelopers^].

[NOTE]
.Ausbau der Plugin-Fähigkeit
====
Die Plugin-Fähigkeit von plentymarkets und die Bearbeitungsmöglichkeiten werden suk­zes­si­ve ausgebaut. Auch das Angebot an Plugins wird nach und nach erweitert.
====

[#marketplace-plugins-kaufen]
== Marketplace-Plugins kaufen

link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^] ist die neue Plattform für die Distribution von hauseigenen und externen plentymarkets Software-Erweiterungen. Diese Plattform ermöglicht Ihnen einen leichten Zugang zu Plugins, damit Sie schnell und einfach von allen Vorteilen profitieren. Gehen Sie wie folgt vor, um ein Plugin zu kaufen.

[.instruction]
Plugin kaufen:

. Öffnen Sie das Menü **Plugins » Plugins-Übersicht**.
. Klicken Sie auf **plentyMarketplace**.
→ Der Marktplatz wird in einem neuen Tab geöffnet.
→ _Oder_: Melden Sie sich direkt auf link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^] mit Ihren Zugangsdaten aus dem Service-Center an.
. Wählen Sie ein Plugin aus einer Kategorie. Eine Übersicht aller Kategorien finden Sie in der Tabelle <<tabelle-marketplace-kategorien>>.
. Klicken Sie in der Detailansicht des Plugins auf **Plugin kaufen**. +
//Eine Übersicht aller Kaufoptionen finden Sie in der Tabelle <<tabelle-kaufoptionen>>. +
→ Das Fenster **Kasse** wird geöffnet.
. Nehmen Sie die Nutzungsbedingungen zur Kenntnis.
. Klicken Sie auf **Jetzt kaufen**. +
→ Das gekaufte Plugin ist als nicht installiertes Plugin im Menü **Plugins » Plugin-Übersicht** verfügbar.

[[tabelle-marketplace-kategorien]]
.plentyMarketplace-Kategorien
[cols=”1,3”]
|====
|Kategorie |Erläuterung

|*Channels >> Marktplätze*
|Anbindung an andere Marktplätze wie Rakuten und idealo. Weitere Informationen zum Anbinden von von plentymarkets entwickelten Marktplätzen unter *Omni-Channel >> Multi-Channel*.

|*Channels >> Online-Shop*
|Verbindung zu anderen Shopsystemen wie Shopify.

|*Channels >> Preisportale*
|Fügen Exportformate für den elastischen Export hinzu. Weitere Informationen zu allen Exportformaten hier.

|*Themes*
|Ändern das Design des Online-Shops.

|*Templates*
|Die Grundlage des Online-Shops. Weitere Informationen zu von plentymarkets entwickelten Templates unter *Omni-Channel >> Online-Shop*.

|*Widgets*
|Fügen dem Online-Shop neue Elemente wie Schaltflächen für soziale Netzwerke oder Kontaktinformationen hinzu.

|*Payment*
|Geben Kunden die Möglichkeit, andere Zahlungsmöglichkeiten zu verwenden. Weitere Informationen zum Installieren und Einrichten dieser Plugins in der Artikelbeschreibung auf plentyMarketplace.

|*Integration*
|Zusätzliche Funktionalität für das plentymarkets System durch externe Tools.

|*Services*
|Agenturen bieten verschiedene, auf individuelle Ansprüche ausgelegte, Leistungen an.
|====
////
[[tabelle-kaufoptionen]]
.Kaufoptionen
[cols=”1,3”]
|====
|Option |Erläuterung

|*Testen*
|Plugin kann in vollem Umfang 30 Tage lang umsonst genutzt werden. Nicht mehr möglich, nachdem das Plugin bereits abonniert wurde. Ablaufdatum kann im *Mein Konto*-Bereich eingesehen werden.

|*Kaufen*
|Einmalkauf. Plugins werden teilweise in verschiedenen Umfängen angeboten. Welche Funktionalitäten in welchem Umfang enthalten sind, kann der Artikelbeschreibung entnommen werden.

|*Abonnement*
|Plugins können abonniert werden, um sie in vollem Umfang für einen begrenzten Zeitraum zu nutzen. Je nach Plugin stehen unterschiedliche Zahlungszeiträume zu Verfügung. Abgerechnet wird immer am Anfang eines Zahlungszeitraums. Abonnements laufen nicht automatisch aus, sondern müssen im *Mein Konto*-Bereich gekündigt werden.
////
[#git-plugins-hinzufuegen]
== Plugins über Git hinzufügen

Wenn Sie plentymarkets erweitern möchten, aber kein Plugin mit der entsprechenden Funktionalität auf plentyMarketplace finden, haben Sie die Möglichkeit, Ihrem System Plugins über Git hinzuzufügen. Manche externe Entwickler bieten Plugins auf diesem Wege an. Wenn Sie weitere Informationen zu so verfügbaren Plugins erhalten möchten, sollten Sie direkt mit Entwicklern Kontakt aufnehmen. Nutzen Sie dafür entweder die link:https://www.plentymarkets.eu/service/partneragenturen/search/plugin-30/?aoff=s[Partnerübersicht^], schreiben Sie eine Nachricht in der Forumskategorie link:https://forum.plentymarkets.com/c/suche-biete/suche-biete-plugins[Suche/Biete^] oder erstellen Sie eine link:https://marketplace.plentymarkets.com/plentyprojects[neue Projektanfrage^] auf plentyMarketplace.

Handelt es sich um ein privates Repository, wird zusätzlich zur URL des Repositorys ein persönlicher Zugriffstoken benötigt. Hier wird nur beschrieben, wie Sie einen solchen Token auf GitHub erzeugen können, auf anderen Seiten wie GitLab ist der Vorgang jedoch ähnlich. Wenn Sie solch eine Seite nutzen und weitere Informationen benötigen, ziehen Sie bitte die Dokumentation der entsprechenden Seite zu Rate.

[.instruction]
Einen persönlichen Zugriffstoken für private Repositorys erzeugen:

. Öffnen Sie die link:https://github.com/settings/tokens[Tokeneinstellungen^] auf GitHub.
. Klicken Sie auf *Generate new token*.
→ Geben Sie Ihr Passwort ein, um fortzufahren.
. Geben Sie in das Feld *Token description* eine Beschreibung ein.
. Aktivieren Sie im Menü *Select scopes* das Kontrollkästchen *repo:status*.
. Klicken Sie auf *Generate token*.
→ Es wird ein neuer Token erzeugt. Dieser wird im nächsten Schritt benötigt, also lassen Sie die Seite geöffnet oder speichern Sie den Token lokal. Wenn Sie den Token speichern, sollten Sie ihn nach dem Hinzufügen des Plugins wieder löschen.

Damit haben Sie jetzt alle notwendigen Informationen, um das Git-Plugin Ihrem plentymarkets System hinzuzufügen.

[.instruction]
Git-Plugin dem System hinzufügen:

. Öffnen Sie das Menü *Plugins » Git*.
. Klicken Sie auf *Neues Repository hinzufügen*. +
→ Die Repository-Einstellungen werden angezeigt.
. Geben Sie die URL des Repositorys, Ihren Benutzernamen sowie den zuvor erzeugten Zugriffstoken in die dafür vorgesehenen Felder ein.
. Geben Sie den Branch an, der für die Installation verwendet werden soll. Standardmäßig ist hier der master-Branch angegeben, Sie sollten sich aber vom Entwickler des Plugins bestätigen lassen, welches der richtige Branch ist und das Feld entsprechend aktualisieren.
. *Speichern* Sie die Einstellungen. +
→ Die Verbindung zum Git-Repository wird geprüft und hergestellt.

[NOTE]
.Öffentliche Repositorys
====
Bei öffentlichen Repositorys müssen keine tatsächlichen Zugangsdaten als Benutzername und Token eingegeben werden. Die beiden Felder dürfen aber auch nicht leer sein. Geben Sie also jeweils eine beliebige Zeichenfolge ein, beispielsweise „Gast“.
====

[[tabelle-git-plugins-hinzufuegen]]
.Git-Plugins hinzufügen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Repository-URL*
|HTTPS oder HTTP URL des Git-Repositorys.

|*Benutzername*
|Der Benutzername ist Bestandteil der Benutzerdaten des Anbieters (z.B. GitHub) für das Git-Repository. +
Bei öffentlichen Repositories einen beliebigen Wert in das Feld eingeben, z.B. *Gast*.

|*Token*
|Der Token ist Bestandteil der Benutzerdaten des Anbieters (z.B. GitHub) für das Git-Repository. Neue Tokens können in den Einstellungen des Anbieters erzeugt werden. +
Bei öffentlichen Repositories einen beliebigen Wert in das Feld eingeben, z.B. *Gast*. +

|*Name des zu installierenden Branch (muss gültige plugin.json-Datei enthalten).*
|Das Git-Repository muss eine valide Plugin.json-Datei enthalten. Die Eingabe ist für die Erstinstallation notwendig.
|====


=== Git-Repository löschen

Im Menü *Plugins » Git* können Repositories über *Löschen* gelöscht werden, wenn das Plugin in allen Sets deaktiviert wurde.

[#plugin-sets-verwalten]
== Plugin-Übersicht - Plugin-Sets verwalten

Die nachfolgende Tabelle enthält eine Liste aller Elemente des Menüs *Plugin-Übersicht* sowie eine kurze Beschreibung dieser Elemente. Außerdem finden Sie in diesem Abschnitt Anweisungen zu der Erstellung, Bearbeitung und Löschung von Plugin-Sets.

[[tabelle-plugin-uebersicht]]
.Tabellenansicht des Menüs *Plugin » Plugin-Übersicht*
[cols="1,3"]
|====
|Element |Erläuterung

|*Neues Plugin-Set erstellen*
|Öffnet ein Fenster zur Erstellung eines neuen Plugin-Sets. +
*Speichern*: Speichert das neue Plugin-Set. +
*Plugin-Set-Name*: Der Name des Plugin-Sets. +
*Plugin-Set kopieren*: Wählt bestehendes Plugin-Set aus Dropdown-Menü aus, um Einstellungen zu übernehmen.

|*Plugin-Sets verknüpfen*
|Ein neues Fenster öffnet sich. Aus einem Dropdown-Menü kann für jedes Plugin-Set ein Mandant ausgewählt werden. Durch *Speichern* der Einstellungen werden die Plugin-Sets mit den ausgewählten Mandanten verknüpft. Eine Verknüpfung kann vollständig aufgehoben werden, indem aus dem Dropdown-Menü die leere Zeile für ein Set ausgewählt wird.

|Name des Plugin-Sets
|Lädt die Plugin-Übersicht des Plugin-Sets.

|*Plugin-Set löschen*
|Löscht das Plugin-Set. Bestätigung notwendig.

|Filter
|*Suchen*: Lädt für das ausgewählte Plugin-Set in der Plugin-Übersicht alle Plugins, die die gewählten Filtereinstellungen erfüllen. +
*Reset*: Setzt die Filtereinstellungen auf die Standardeinstellungen zurück. +
*Name*: Filtert nach Plugins, deren Namen die eingegebene Zeichenfolge beinhaltet. +
*plentyMarketplace*: Filtert nach Plugins, die dem System über plentyMarketplace hinzugefügt wurden. +
*Git*: Filtert nach Plugins, die dem System über ein Git-Repository hinzugefügt wurden. +
*Local*: Filtert nach Plugins, die dem System über einen lokalen Speicher hinzugefügt wurden. +
*Installiert*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set installiert sind. +
*Nicht installiert*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set nicht installiert sind. +
*Aktiv*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set aktiv sind. +
*Nicht akitv*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set nicht aktiv sind.

|*Speichern & Plugin bereitstellen*
|Speichert Änderungen am Plugin-Set und stellt das Plugin-Set zur weiteren Nutzung bereit.

|*Plugin-Set-Vorschau*
|Öffnet ein Tab, in dem eine Vorschau des Frontends mit den derzeitigen Einstellungen angezeigt wird. Plugin-Set muss zuvor mittels der Schaltfläche *Speichern & Bereitstellen* bereitgestellt worden sein.

|*plentyDrive: Änderungen automatisch bereitstellen*
|Wenn aktiviert und dem Plugin-Set ein Plugin mithilfe von plentyDrive hinzugefügt oder geändert wird, wird das Plugin-Set automatisch gespeichert und bereitgestellt.

|*Plugin-Set-Einstellungen*
|Öffnet ein Fenster zur Bearbeitung des ausgewählten Plugin-Sets. +
*Speichern*: Speichert die geänderten Einstellungen. +
*Name*: Ändert den Namen des Plugin-Sets. +
*Plugin-Set-ID*: Die ID des Plugin-Sets.

|*Log*
|Nur sichtbar, wenn Fehlermeldungen existieren. Zeigt diese an.

|*Aktiv*
|Zeigt an, ob das Plugin aktiv oder inaktiv ist.

|*Name*
|Der Name des Plugins. Wenn installiert, klicken um Informationen und Einstellungsmöglichkeiten anzuzeigen.

|*Installierte Version*
|Die neuste Version des Plugins, die installiert ist. Ein Symbol zeigt an, wenn eine neuere Version des Plugins existiert.

|*Aktive Version*
|Die Version des Plugins, die aktiv ist und für das ausgewählte Plugin-Set in Frontend und Backend geladen wird.

|*Herkunft*
|Die Herkunft des Plugins, also plentyMarkets, Git oder ein lokaler Speicher.

|*Aktion*
|*Plugin installieren*: Installiert das Plugin. Ein Fenster öffnet sich, in dem die zu installierende Version ausgewählt und der Changelog eingesehen werden kann. Wird nur angezeigt, wenn das Plugin nicht installiert ist. +
*Aktualisieren*: Aktualisiert das Plugin auf eine neuere Version. Ein Fenster öffnet sich, in dem die zu installierende Version ausgewählt und der Changelog eingesehen werden kann. Wird nur angezeigt, wenn eine neuere Version vorhanden ist. +
*Keine Aktualisierung verfügbar*: Die neuste Version des Plugins ist installiert. +
*Position festlegen*: Legt die Reihenfolge fest, in der Plugins geladen werden. Plugins mit niedrigerer Position werden zuerst ausgeführt. +
*Löschen*: Entfernt das Plugin aus dem Plugin-Set. Bestätigung notwendig.

|*plentyMarketplace*
|Öffnet plentyMarketplace in einem neuen Tab.
|====

Ein Plugin-Set ist eine Sammlung von verschiedenen Plugins, die für einen oder für mehrere Mandanten zentral in der *Plugin-Übersicht* verwaltet werden können. Plugin-Sets können ein Plugin oder mehrere Plugins enthalten und beinhalten darüber hinaus ebenfalls die Einstellungen der Plugin-Konfiguration und Layout-Container. Plugin-Sets eignen sich insbesondere für Händler, die mehrere Webshops gleichzeitig über plentymarkets verwalten, da unterschiedliche Plugin-Sets für unterschiedliche Mandanten gesondert aktiviert und konfiguriert werden können.

In den folgenden Abschnitten wird beschrieben, welche Aktionen Sie durchführen müssen, um neue Plugin-Sets zu erstellen, bereits existierende Plugin-Sets zu bearbeiten oder Plugin-Sets zu löschen.

[#plugin-sets-erstellen]
== Plugin-Sets erstellen

[.instruction]
Plugin-Sets erstellen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin-Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin-Set ein.
. Wählen Sie auf dem Dropdown-Menü *Plugin-Set kopieren* ein Plugin-Set aus, um dessen Einstellungen zu übernehmen.
. *Speichern* Sie die Einstellungen.

[.instruction]
Plugins installieren:

. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Nutzen Sie die Filterfunktion indem Sie das Kontrollkästchen *Nicht installiert* aktivieren und auf *Suchen* klicken. Möchten Sie Plugins installieren, die Sie über ein Git-Repository oder einen lokalen Speicher hinzugefügt haben, müssen Sie vor der Suche auch das Kontrollkästchen *Git* beziehungsweise *Lokal* auswählen.
→ Die Plugin-Übersicht wird entsprechend aktualisiert.
. Wenn Sie ein Plugin installieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Plugin installieren*. +
→ Ein Fenster zur Auswahl der zu installierenden Version öffnet sich. Wählen Sie aus dem Dropdown-Menü *Zu installierende Version* die Version des Plugins aus, die Sie installieren möchten. Standardmäßig ist die neuste Version ausgewählt. In einem Textfeld unterhalb des Dropdown-Menüs wird der Changelog der aktuell ausgewählten Version angezeigt. Wenn Sie sich für eine Version entschieden haben, klicken Sie auf die Schaltfläche *Installieren*. +
→ Das Plugin wird installiert und ist in der Plugin-Übersicht des Plugin-Sets verfügbar. Eine Ansicht mit allen installierten Plugins wird angezeigt.

[.instruction]
Plugins aktivieren:

. Wenn Sie ein Plugin einem Plugin-Set aktivieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktiv* auf die Schaltfläche *Inaktiv*. +
→ Aktive Plugins werden in Frontend und Backend geladen.

[.instruction]
Position von Plugins ändern:

. Wenn Sie die Position eines Plugins verändern möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Position festlegen*. +
→ Das Fenster *Plugin-Position* öffnet sich. Geben Sie in das Textfeld die gewünschte Position des Plugins ein und klicken Sie auf *Speichern*.
→ Die Position des Plugins wird aktualisiert.

[TIP]
.Plugin-Position
====
Die relative Position der Plugins bestimmt, in welcher Reihenfolge sie innerhalb des Sets geladen werden. Dabei gilt: Je niedriger die Position des Plugins desto früher wird es geladen. Aus diesem Grund sollte das Plugin IO die höchste Positionsnummer erhalten, das Plugin Ceres in der Regel die zweithöchste.
====

[.instruction]
Plugins als Vorschau öffnen:

. Klicken Sie auf *Plugin-Set-Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. Das ausgewählte Plugin-Set muss zuvor über den Button *Plugin-Set speichern & bereitstellen* bereitgestellt werden. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

[.instruction]
Plugin-Sets aktivieren:

. Klicken Sie auf *Plugin-Sets verknüpfen*. +
→ Das Fenster *Plugin-Sets verknüpfen* wird geöffnet.
. Wählen Sie das Plugin-Set, das Sie mit Ihrem Webshop verknüpfen wollen.
. *Speichern* Sie die Einstellungen.

[TIP]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugin-sets-bearbeiten]
== Plugin-Sets bearbeiten

[#plugin-set-namen-aendern]
=== Plugin-Set-Name ändern

[.instruction]
Plugin-Set-Namen ändern:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Klicken Sie auf die Schaltfläche *Plugin-Set-Einstellungen*.
→ Der Bereich *Einstellungen* wird geöffnet.
. Geben Sie in das Textfeld *Name* den neuen Namen für Ihr Plugin-Set ein.
. Klicken Sie auf die Schaltfläche *Speichern*.
→ Das Plugin-Set wird umbenannt.

[TIP]
.Sicherheitskopie
====
Wenn Sie ein Plugin-Set bearbeiten und entweder neue Plugins hinzufügen oder bereits existierende Plugins aktualisieren oder löschen möchten, ist es empfehlenswert, eine Kopie dieses Plugin-Sets zu erstellen und die Änderungen zunächst auf dieser vorzunehmen. Dadurch wird verhindert, dass die Änderungen unbeabsichtigte Auswirkungen auf Ihren aktiven Shop hat.
====

[#plugins-hinzufuegen]
=== Plugins hinzufügen

[.instruction]
Plugin-Set kopieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin-Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin-Set ein.
. Klicken Sie auf *Von Plugin-Set kopieren*, um Einstellungen aus einem existierenden Plugin-Set zu übernehmen.
. *Speichern* Sie die Einstellungen.

[.instruction]
Plugins installieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Nutzen Sie die Filterfunktion indem Sie das Kontrollkästchen *Nicht installiert* aktivieren und auf *Suchen* klicken. Möchten Sie Plugins installieren, die Sie über ein Git-Repository oder einen lokalen Speicher hinzugefügt haben, müssen Sie vor der Suche auch das Kontrollkästchen *Git* beziehungsweise *Lokal* auswählen.
→ Die Plugin-Übersicht wird entsprechend aktualisiert.
. Wenn Sie ein Plugin installieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Plugin installieren*. +
→ Ein Fenster zur Auswahl der zu installierenden Version öffnet sich. Wählen Sie aus dem Dropdown-Menü *Zu installierende Version* die Version des Plugins aus, die Sie installieren möchten. Standardmäßig ist die neuste Version ausgewählt. In einem Textfeld unterhalb des Dropdown-Menüs wird der Changelog der aktuell ausgewählten Version angezeigt. Wenn Sie sich für eine Version entschieden haben, klicken Sie auf die Schaltfläche *Installieren*. +
→ Das Plugin wird installiert und ist in der Plugin-Übersicht des Plugin-Sets verfügbar. Eine Ansicht mit allen installierten Plugins wird angezeigt.

[.instruction]
Plugins aktivieren:

. Wenn Sie ein Plugin aktivieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktiv* auf die Schaltfläche *Inaktiv*. +
→ Aktive Plugins werden in Frontend und Backend geladen.

[.instruction]
Position von Plugins ändern:

. Wenn Sie die Position eines Plugins verändern möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Position festlegen*. +
→ Das Fenster *Plugin-Position* öffnet sich. Geben Sie in das Textfeld die gewünschte Position des Plugins ein und klicken Sie auf *Speichern*.
→ Die Position des Plugins wird aktualisiert.

[TIP]
.Plugin-Position
====
Die relative Position der Plugins bestimmt, in welcher Reihenfolge sie innerhalb des Sets geladen werden. Dabei gilt: Je niedriger die Position des Plugins desto früher wird es geladen. Aus diesem Grund sollte das Plugin IO die höchste Positionsnummer erhalten, das Plugin Ceres in der Regel die zweithöchste.
====

[.instruction]
Plugins als Vorschau öffnen:

. Klicken Sie auf *Plugin-Set-Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. Das ausgewählte Plugin-Set muss zuvor über den Button *Plugin-Set speichern & bereitstellen* bereitgestellt werden. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

[.instruction]
Plugin-Sets verknüpfen:

. Klicken Sie auf *Plugin-Set verknüpfen*. +
→ Das Fenster *Plugin-Set verknüpfen* wird geöffnet.
. Wählen Sie das Plugin-Set, das Sie mit Ihrem Webshop verknüpfen wollen.
. *Speichern* Sie die Einstellungen.

[TIP]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugins-aktualisieren]
=== Plugins aktualisieren

[.instruction]
Plugin-Set kopieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin-Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin-Set ein.
. Klicken Sie auf *Von Plugin-Set kopieren*, um Einstellungen aus einem existierenden Plugin-Set zu übernehmen.
. *Speichern* Sie die Einstellungen.

[.instruction]
Plugins aktualisieren:

. Wenn ein Update für ein Plugin verfügbar ist, wird in der entsprechenden Zeile in der Spalte *Aktion* die Schaltfläche *Aktualisieren* farbig gekennzeichnet. Klicken Sie auf diese Schaltfläche, um das Plugin zu aktualisieren. +
→ Ein Fenster zur Auswahl der zu installierenden Version öffnet sich. Wählen Sie aus dem Dropdown-Menü *Zu installierende Version* die Version des Plugins aus, die Sie installieren möchten. Standardmäßig ist die neuste Version ausgewählt. In einem Textfeld unterhalb des Dropdown-Menüs wird der Changelog der aktuell ausgewählten Version angezeigt. Wenn Sie sich für eine Version entschieden haben, klicken Sie auf die Schaltfläche *Installieren*. +
→ Das Plugin wird aktualisiert.

[.instruction]
Position von Plugins ändern:

. Wenn Sie die Position eines Plugins verändern möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Position festlegen*. +
→ Das Fenster *Plugin-Position* öffnet sich. Geben Sie in das Textfeld die gewünschte Position des Plugins ein und klicken Sie auf *Speichern*.
→ Die Position des Plugins wird aktualisiert.

[TIP]
.Plugin-Position
====
Die relative Position der Plugins bestimmt, in welcher Reihenfolge sie innerhalb des Sets geladen werden. Dabei gilt: Je niedriger die Position des Plugins desto früher wird es geladen. Aus diesem Grund sollte das Plugin IO die höchste Positionsnummer erhalten, das Plugin Ceres in der Regel die zweithöchste.
====

[.instruction]
Plugins als Vorschau öffnen:

. Klicken Sie auf *Plugin-Set-Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. Das ausgewählte Plugin-Set muss zuvor über den Button *Plugin-Set speichern & bereitstellen* bereitgestellt werden. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

[.instruction]
Plugin-Sets verknüpfen:

. Klicken Sie auf *Plugin-Set verknüpfen*. +
→ Das Fenster *Plugin-Set verknüpfen* wird geöffnet.
. Wählen Sie das Plugin-Set, das Sie mit Ihrem Webshop verknüpfen wollen.
. *Speichern* Sie die Einstellungen.

[TIP]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugins-entfernen]
=== Plugins entfernen

Es gibt zwei Möglichkeiten, die Funktionalität eines Plugins von Ihrem Set zu entfernen. Wenn Sie ein Plugin deaktivieren, ist es weiterhin Teil des Sets und Sie können es später erneut aktivieren ohne es neu installieren zu müssen. Wenn Sie ein Plugin löschen, wird es vollständig aus dem Set entfernt.

[#plugins-deaktivieren]
==== Plugins deaktivieren

[.instruction]
Plugin-Set kopieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin-Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin-Set ein.
. Klicken Sie auf *Von Plugin-Set kopieren*, um Einstellungen aus einem existierenden Plugin-Set zu übernehmen.
. *Speichern* Sie die Einstellungen.

[.instruction]
Plugins deaktivieren:

. Wenn Sie ein Plugin deaktivieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktiv* auf die Schaltfläche *Aktiv*. +
→ Inaktive Plugins werden in Frontend und Backend nicht geladen.

[.instruction]
Plugins als Vorschau öffnen:

. Klicken Sie auf *Plugin-Set-Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. Das ausgewählte Plugin-Set muss zuvor über den Button *Plugin-Set speichern & bereitstellen* bereitgestellt werden. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

[.instruction]
Plugin-Sets verknüpfen:

. Klicken Sie auf *Plugin-Set verknüpfen*. +
→ Das Fenster *Plugin-Set verknüpfen* wird geöffnet.
. Wählen Sie das Plugin-Set, das Sie mit Ihrem Webshop verknüpfen wollen.
. *Speichern* Sie die Einstellungen.

[TIP]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugins-loeschen]
==== Plugins löschen

[.instruction]
Plugin-Set kopieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin-Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin-Set ein.
. Klicken Sie auf *Von Plugin-Set kopieren*, um Einstellungen aus einem existierenden Plugin-Set zu übernehmen.
. *Speichern* Sie die Einstellungen.

[.instruction]
Plugins löschen:

. Wenn Sie ein Plugin löschen möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Löschen*. +
→ Gelöschte Plugins werden von dem Plugin-Set entfernt.

[.instruction]
Plugins als Vorschau öffnen:

. Klicken Sie auf *Plugin-Set-Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. Das ausgewählte Plugin-Set muss zuvor über den Button *Plugin-Set speichern & bereitstellen* bereitgestellt werden. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

[.instruction]
Plugin-Sets verknüpfen:

. Klicken Sie auf *Plugin-Set verknüpfen*. +
→ Das Fenster *Plugin-Set verknüpfen* wird geöffnet.
. Wählen Sie das Plugin-Set, das Sie in Ihrem Webshop aktivieren wollen.
. *Speichern* Sie die Einstellungen.

[TIP]
.Plugin-Sets verknüpfen
====
Das Verknüpfen eines Plugin-Sets mit einem Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es verknüpfen.
====

[#plugin-sets-loeschen]
== Plugin-Sets löschen

[.instruction]
Plugin-Sets löschen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie bei einem Plugin-Set auf *Löschen*. +
→ Das Fenster *Plugin-Set löschen* wird geöffnet.
. Bestätigen Sie die Löschung. +
→ Das Plugin-Set wird gelöscht.

[#plugin-sets-im-backend-aktivieren]
== Plugin-Sets im Backend aktivieren

Plugin-Sets und die in den Sets aktivierten Plugins können sowohl dazu benutzt werden, Ihrem Shop neue Funktionalitäten hinzuzufügen als auch, um Ihr Backend um Menüeinträge und Benutzerschnittstellen zu erweitern. Dabei kann jeder Benutzer ein eigenes Backend-Plugin-Set auswählen und die in dem Set aktivierten Plugins für das eigene Backend laden. Dies kann dann hilfreich sein, wenn einige Ihrer Mitarbeiter Zugriff auf bestimmte Funktionen benötigen, nicht jedoch auf andere. Wenn Sie das Plugin-Set für Ihre Backend-Ansicht ändern möchten, gehen Sie wie folgt vor.

[.instruction]
Backend-Plugin-Set wählen:

. Klicken Sie im plentymarkets Backend oben rechts auf das Benutzersymbol.
. Klicken Sie auf *Backend-Plugin-Set*. +
→ Das Fenster *Backend-Plugin Set* wird geöffnet.
. Klicken Sie auf ein Plugin-Set.
. *Speichern* Sie die Einstellungen.
→ Das gewählte Plugin-Set ist jetzt für Ihr Backend aktiviert.

[#plugin-konfiguration]
== Plugin-Konfiguration

Nach der Installation müssen Plugins teilweise noch konfiguriert werden. Je nach Plugin gibt es hierbei eine von zwei Möglichkeiten. Entweder öffnet sich ein Fenster mit Einstellungsmöglichkeiten, wenn Sie auf den Namen des Plugins im Plugin-Set klicken oder es wird bei Installation des Plugins eine Schnittstelle zu dem Menü *System* hinzugefügt. Werden Einstellungen innerhalb eines Plugin-Sets vorgenommen, sind sie auf dieses eine Plugin-Set beschränkt. Einstellungen, die im Menü *System* vorgenommen werden, sind global und betreffen alle Plugin-Sets, auch wenn das Plugin erst später in dem Set installiert wird.

[NOTE]
.Ausnahmen
====
Wenn ein Plugin vor der Einführung von Plugin-Sets entwickelt wurde, sind möglicherweise andere Einstellungen notwendig.
====

[#container-verknüpfungen]
== Container-Verknüpfungen

Wenn durch ein Plugin neue Elemente zum Webshop hinzugefügt werden sollen, etwa das Logo für eine Zahlungsmethode, müssen diese Angaben mit sogenannten Containern im Webshop verknüpft werden.

Standardmäßig können diese Verknüpfungen im Menü *CMS* >> *Container-Verknüpfungen* angelegt werden. Teilweise geben Entwickler aber auch standardmäßig Verknüpfungen an, die mit einem Klick in der Plugin-Detailansicht angelegt werden können.

[.instruction]
Standard-Container-Verknüpfung wählen:

. Öffnen Sie das Menü *Plugins* >> *Plugin Übersicht*.
. Öffnen Sie die Detailansicht des Plugins, für das Sie Verknüpfungen anlegen möchten, indem Sie auf den Namen des Plugins klicken.
. Klicken Sie auf die Schaltfläche *Standard-Container-Verknüpfung*.
. Aktivieren Sie die Kontrollkästchen der Verknüpfungen, die Sie anlegen möchten.
. Speichern Sie die Einstellungen.

Ob für ein Plugin Standard-Container-Verknüpfungen vorliegen, können Sie in der Artikelansicht des Plugins auf plentyMarketplace einsehen.

[WARNING]
.Vorhandene Verknüpfungen werden nicht überschrieben
====
Beim Speichern der Standard-Container-Verknüpfungen werden bereits vorhandene Verknüpfungen nicht überschrieben. Wenn Sie nur die Standard-Container-Verknüpfungen nutzen möchten, müssen Sie zunächst alle Verknüpfungen im Menü *CMS* >> *Container-Verknüpfungen* löschen.
====