= Managing reports
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Report, Reports, raw data, key performance indicator, KPI, key figure, data analysis, statistics, BI, Business Intelligence
:position: 10
:url: business-decisions/business-intelligence/reports/manage-reports
:id: LAKHMQK
:author: team-bi

A report is a data analysis that determines a single key performance indicator (KPI) or a list of KPIs. The data base for this analysis is an export of raw data at regular intervals. This data is saved on a secure cloud storage.

== Raw data

Raw data is collected in the background, usually over night. The raw data to be saved is set in the *Setup » plentyBI » Raw data* menu. You can retrieve the generated files via the REST API and process the data externally.

=== For end users

We have observed that business decisions are often not made based on key figures, but rather intuitively. In order to change this behaviour, we recommend using a business intelligence tool. Ideally, such a toll analyses different data from several sources. This allows you to identify specific recommendations for action. Start now and use our integrated plentyBI dashboard to keep track of relevant data and key figures. Further information is available in the <<business-decisions/business-intelligence/plenty-bi#, plentyBI>> section of the manual.

=== For developers

Raw data is available in CSV format and can therefore easily be processed. All plentymarkets systems have a standardised REST API. You can find the documentation on link:https://developers.plentymarkets.com/[this page^]{nbsp}icon:external-link[].

Raw data is retrieved in two steps. We recommend retrieving the data once a day after around noon. At this point, the process of generating raw data is completed for all systems.

First, a list of available raw data files is retrieved via this link:https://developers.plentymarkets.com/rest-doc#/Report/get_rest_report_raw_data[route^]{nbsp}icon:external-link[]. The time at which the latest file of the last retrieval was created serves as a filter for the next retrieval. In this way, the files are not retrieved several times. The number of files that are generated per day may vary depending on how many creator processes are activated for a plentymarkets system. Furthermore, only a certain number of data rows is written in each file. If required, another file is created. With this route, either all files of a single creator or all files that were created during the retrieval interval are exported.
With this link:https://developers.plentymarkets.com/rest-doc#/Report/get_rest_report_raw_data_file[route^]{nbsp}icon:external-link[], a raw data file is exported. The required file path is contained in the sample space of the REST route listed in point 1. Raw data files are provided as a GZIP-compressed CSV file (RFC 1952). A comma is used as column separator.

[TIP]
.Standard time stamp format
====
The standard date format is MM/DD/YYYY HH:MI:SS TZ. This date format can be copied directly to an AWS Redshift column of the type TIMESTAMPTZ. Example: 01/30/2019 05:14:57 Europe/Berlin
====

=== Data format creator

The creator is a specific process that provides a raw data format. Each creator only saves data after you have activated the creator in the *Setup » plentyBI » Raw data* menu.

For explanations and links to individual format pages, see <<table-reports-data-formats>>.

[IMPORTANT]
.Limited saving of raw data
====
In plentymarkets, raw data are the data basis for the key figures available in the <<business-decisions/business-intelligence/plenty-bi#, plentyBI>> module. Depending on the plentyBI tariff that was booked, raw data are saved for different periods of time in the system. In general,the following periods apply: +

* plentyBI XS: 3 months
* plentyBI S:  6 months
* plentyBI M:  12 months
* plentyBI L:  48 months

More detailed information for each raw data format can be accessed by clicking on the links in <<table-reports-data-formats>>.
====

[[table-reports-data-formats]]
.Available raw data formats
[cols="1,3"]
|====
|Data format |Explanation

|accountContacts
|Contact +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/accountcontacts#, accountContacts>> page.

|accounts
|Company +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/accounts#, accounts>> page.

|categories
|Categories +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/categories#, categories>> page.

|feedbacks
|Feedbacks +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/feedbacks#, feedbacks>> page.

|itemManufacturer
|Manufacturer +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/itemmanufacturer#, itemManufacturer>> page.

|itemVariations
|Variation +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/itemvariations#, ItemVariations>> page.

|itemVariationSuppliers
|Links between suppliers and variations +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/itemvariationsuppliers#, itemVariationSuppliers>> page.

|messages
|Messages +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/messages#, messages>> page.

|messageTagRelations
|Tag relations of messages +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/messagetagrelations#, messageTagRelations>> page.

|orderDocuments
|Order documents +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/orderdocuments#, orderDocuments>> page.

|orderItemAmounts
|Number of order items +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/orderitemamounts#, orderItemAmounts>> page.

|orderItemProperties
|Property of the order item +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/orderitemproperties#, orderItemProperties>> page.

|orderItems
|Order item +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/orderitems#, orderItems>> page.

|orderProperties
|Order property +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/orderproperties#, orderProperties>> page.

|orders
|Order +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/orders#, orders>> page.

|orderStatuses
|Order status +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/orderstatuses#, orderStatuses>> page.

|paymentOrderRelations
|Links between payments and orders +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/paymentorderrelations#, paymentOrderRelations>> page.

|payments
|Payments +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/payments#, payments>> page.

|properties
|Properties +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/properties#, properties>> page.

|propertyRelations
|Links between properties and other data +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/propertyrelations#, propertyRelations>> page.

|stockManagementStock
|Stock +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/stockmanagementstock#, stockManagementStock>> page.

|stockManagementStockMovements
|Stock movements +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/stockmanagementstockmovements#, stockManagementStockMovements>> page.

|stockManagementWarehouses
|Warehouses +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/stockmanagementwarehouses#, stockManagementWarehouses>> page.

|tags
|Tags +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/tags#, tags>> page.

|tagRelations
|Tag links +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/tagrelations#, tagRelations>> page.

|users
|Users +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/users#, users>> page.

|variationValidation
|Variations that have been exported to markets but have been rejected +
For further information, see the <<business-decisions/business-intelligence/reports/data-formats/variationvalidation#, variationValidation>> page.

|====

More data formats will be added to this table as they become available.
