= FAQ: EBICS-Plugin
:lang: de
:description: Die wichtigsten Fragen und Antworten zum EBICS-Plugin.
:keywords: EBICS, Plugin, FAQ, Konto, Bankbuchungen, Vorkasse, Überweisung, HBCI, IBAN, Zahlungen

In unserem Marketplace erhaltet ihr alle wichtigen Infos zu unserem link:https://marketplace.plentymarkets.com/plugins/payment/EBICS_5098[EBICS-Plugin^].
Ihr könnt euch auch gerne noch den link:https://www.plentymarkets.eu/blog/plentyCommunity-Projekt-EBICS-Komplett-auf-den-Anwender-ausgerichtet/b-1941/[Blog-Beitrag^] zum Plugin durchlesen, um alles Wissenswerte zu erfahren.

== Erste Schritte: Wie benutze ich das EBICS-Plugin?
Für das EBICS-Plugin, sowie alle anderen Plugins, wird Plentymarkets 7 vorausgesetzt.

[NOTE]
.HINWEIS
====
Um ein Konto anzulegen, muss zuerst das EBICS-Modul über den Konfigurator gebucht werden.
====

[discrete]
===== Anforderungen um das Plugin zu nutzen
. <<basics/erste-schritte/plugins#10, Plugin kaufen>>
. <<basics/erste-schritte/plugins#20, Plugin installieren>>
. <<basics/erste-schritte/plugins#50, Plugin bereitstellen>>

== Wie lege ich ein neues Konto an?
Zuerst wird ein neues Konto mit den Daten vom Bankschreiben angelegt.

[NOTE]
.HINWEIS
====
Prüfe bei der Auswahl der Bank, ob die URL und der Hostparameter / -name mit der vom Bankschreiben übereinstimmt.
====

Über den Button *Konto initialisieren* werden die Schlüssel generiert und der INI- und HIA-Call ausgeführt.
Anschließend kann der INI-Brief erstellt werden. Dies erfolgt über einen direkten pdf-Download im Browser.
Achte bitte darauf, dass die Pop-Ups dabei nicht blockiert werden.
Der INI-Brief sollte direkt oder zeitnah unterschrieben und an die Bank übermittelt werden.
Die Bank schaltet das Konto frei, wenn alles ordnungsgemäß durchgeführt wurde.
Über *Konto-Initialisierung abschließen (HPB)* wird die Initialisierung nach der Bank-Freigabe abgeschlossen.

== Ich benutze EBICS bereits. Wieso soll ich auf das Plugin wechseln?
Das EBICS-Tool für den Zahlungsabruf läuft stabiler als in der alten EBICS-Integration.
Weiterhin wird das Tool, sowie das Plugin, fortlaufend weiterentwickelt.
Die alte EBICS-Schnittstelle ist nicht mehr wartungsfähig.
Bereits vorhandene Konten können ganz einfach in das Plugin migriert werden.

== Es werden keine Zahlungen abgerufen. Was kann ich tun?
* Inaktive Geschäftsvorfälle über den Menüpunkt *Geschäftsvorfälle* laden
* Geschäftsvorfälle nach Wunsch aktivieren
* Überprüfen, ob Vormerkposten und Tagesumsätze das richtige Format nutzen

== Die Bank stellt das Transaktionsfile um X Uhr bereit. Warum wird dieses erst später von plenty abgerufen?
* Der Abruf erfolgt täglich über einen Servercron
* Der Zahlungsabruf erfolgt meistens spät am Abend oder in der Nacht

== Was bedeuten die Felder “Tagesumsatz” und “Vormerkposten”?
* Tagesumsatz = bestätigte Buchung, die einmal am Tag bereitgestellt wird
* Vormerkposten = autorisierte Buchung, die mehrmals am Tag bereitgestellt wird und den Zahlungseingang reserviert
* Der Vormerkposten wird durch die bestätigte Buchung aufgehoben

[WARNING]
.HINWEIS
====
Tagesumsatz und Vormerkposten sollten immer das selbe Format besitzen, da sonst Fehler bei der Zahlungszuweisung auftreten.
====

== Was ist der Unterschied zwischen CAMT und MT?

.Die Formate CAMT und MT im Vergleich
|===
| |CAMT |MT

|*Feld IBAN in Kontoeinstellungen*
|IBAN
|Kontonummer

|*Transaktionsfiles*
|Standardisiertes Format
|Bankenspezifisches Format

|===

Weitere Infos zu den Formaten erhaltet ihr auch in diesem link:https://forum.plentymarkets.com/t/vormerkposten-camt052-oder-mt942-bei-postbank-taeglich-abruf-um-13-uhr-und-17-uhr-moeglich/120442/2[Forumsbeitrag^].
