= CMS syntax
:lang: en
include::{includedir}/_header.adoc[]
:position: 160

== General information

The CMS syntax is a script language that is used in the **web design**, **categories** and **e-mail templates** of plentymarkets. The CMS syntax was introduced in plentymarkets version 5.1. New language constructs and functions are added continuously.

'''

[.row]
====
[.col-md-4]
.Basic concepts
=====
<<omni-channel/online-store/cms-syntax/basics/compiler#, Compiler  >> +
<<omni-channel/online-store/cms-syntax/basics/block#, Block  >> +
<<omni-channel/online-store/cms-syntax/basics/comment#, Comment  >>
=====

[.col-md-4]
.Types
=====
<<omni-channel/online-store/cms-syntax/basics/types#, Primitive types  >>
=====

[.col-md-4]
.Variables
=====
<<omni-channel/online-store/cms-syntax/basics/variables#, Private variables  >> +
<<omni-channel/online-store/cms-syntax/basics/template-variables#, Template variables  >>
=====
====

[.row]
====
[.col-md-4]
.Operators
=====
<<omni-channel/online-store/cms-syntax/basics/operators#, Operators  >>
=====

[.col-md-4]
.Control structures
=====
<<omni-channel/online-store/cms-syntax/basics/if#, if / elseif / else  >> +
<<omni-channel/online-store/cms-syntax/basics/for#, for  >>
=====

[.col-md-4]
.Functions
=====
<<omni-channel/online-store/cms-syntax/basics/template-functions#, Template functions  >>
=====
====
== Templates

You can find information on all templates for designing your online store and your e-mail templates in this chapter of the manual.

[.row]
====
[.col-md-4]
.Global
=====
This section describes PHP functions that are used in the web design and e-mail templates.

<<omni-channel/online-store/cms-syntax/global/phpfunctions#, Open PHP functions  >>
=====

[.col-md-4]
.Web design
=====
This section is divided into subsections. These sections describe all templates and functions available for designing your online store.

<<omni-channel/online-store/cms-syntax/web-design#, Open Web design  >>
=====

[.col-md-4]
.E-mail
=====
List of template variables and functions available for creating your e-mail templates.

<<omni-channel/online-store/cms-syntax/email/email#, Open E-mail  >>
=====
====
