= Setting up the ShopBuilder
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Online store, client, Standard, Ceres, IO, Plugin, configuration, Template, homepage, Drag and Drop, ShopBuilder, ShopBuilder, item lists, image box, carousel
:position: 55

[#10]
The plentymarkets ShopBuilder is an online store construction kit, with which you can assemble your link:https://marketplace.plentymarkets.com/plugins/templates/Ceres_4697[Ceres online store^] quickly and easily via Drag&Drop. No programming skills are required.

[WARNING]
.Version requirements of the ShopBuilder
====
The ShopBuilder is only compatible with Ceres and IO versions 2.8.1 and higher. If you are using an older version, please go to the link:https://marketplace.plentymarkets.com[plentyMarketplace^] to install the current version.
====

[NOTE]
.Functionality of the ShopBuilder
====
Currently, it is only possible to create and edit the homepage of your Ceres online store with the ShopBuilder. The functionality of the ShopBuilder module is constantly expanding and it will be possible in the future to arrange the entire Ceres store through this tool.
====

[NOTE]
.Displaying the homepage created with the ShopBuilder
====
Please note that the homepage created with the ShopBuilder has to be activated first. Go to *CMS » ShopBuilder » Overview » Settings » Homepage*. Activate the option *Show ShopBuilder homepage* and deactivate the option *Show default homepage*.
====

== Editing the Ceres homepage with the ShopBuilder

In the preview area, you can add elements to the homepage to adjust it to your individual needs.

[.instruction]
Adding an element to the preview area:

. Go to *CMS » ShopBuilder*. +
→ The ShopBuilder opens.
. Click on *homepage*. +
→ The preview area of the homepage opens.
. Move elements from the left side into the preview area via drag & drop. Pay attention to the information given in <<table-structure-elements-shop-builder>> and <<table-widget-elements-shop-builder>>. +
→ New elements are added below the existing ones.
. *Save* the settings. +
→ The homepage of your online store is displayed with the selected elements.

[[table-structure-elements-shop-builder]]
.Structure elements of the ShopBuilder
[cols="1,3"]
|====
|Structure element |Explanation

|*2 boxes*
|Provides a structure element with 2 boxes that can be filled with the widgets listed below. Click on *Edit* to change the layout. Select a size ratio from the *Layout* drop-down list.

|*3 boxes*
|Provides a structure element with 3 boxes that can be filled with the widgets listed below. Click on *Edit* to change the layout. Select a size ratio from the *Layout* drop-down list. *Stacked* options display 2 boxes on top of each other.

|*4 boxes*
|Provides a structure element with 4 boxes that can be filled with the widgets listed below. Click on *Edit* to change the layout. The size ratio cannot be adjusted.

|====

[[table-widget-elements-shop-builder]]
.Widget elements of the ShopBuilder
[cols="1,3"]
|====
|Widget element |Explanation

|*Title bar*
|This widget provides a text box. Click *Edit* to enter text and determine the <<#616, colour>> of the title bar via the *Appearance* drop-down list.

|*Image carousel*
|Provides the Ceres image carousel. Click *Edit* to add or remove images. Images can be selected through the category picker, by entering a variation ID or via the file selector. Determine the <<#616, colour>> of the image carousel via the *Appearance* drop-down list.

|*Image box*
|Provides a container for images. Click *Edit* to add or remove images. Images can be selected through the category picker, by entering a variation ID or via the file selector. Determine the <<#616, colour>> of the image box via the *Appearance* drop-down list. Adjust the size of text and image via the *Box style* and *Image size* drop-down lists.

|*Item list*
|Provides the <<omni-channel/online-store/setting-up-ceres#110, Ceres item list>>. Click *Edit* to add or remove pictures. You can add item lists of the types *Category items*, *Last seen items* and *Items with tags*. Determine the sorting value via the *Item sorting* drop-down list and enter the *Maximum number of displayed items* for the list.

|*Text*
|Provides a text box. Click *Edit* to open the text editor. You can select the <<#616, colour>> for the text widget from the *Appearance* drop-down list. Enter the text you want to display in the widget as plain text or switch to HTML by clicking the *</>* symbol in the text editor. _Note that at this point implementing CSS is not yet possible._

|*Top bar* (Header)
|Provides a top bar. Click on *Edit* to carry out the settings and determine the display of the elements, the search or the shopping cart information.

|*Category navigation* (Header)
|Provides a category navigation. Click on *Edit* to carry out the settings and determine the style of the category navigation, the category levels as well as the number of categories. Moreover, a company logo can be added.

|*Breadcrumbs* (Header)
|Provides a breadcrumb navigation. Click on *Edit* to carry out the settings.

|*List*
|Provides a list that serves as placeholder. Click on *Edit* to add list entries or icons.

|*Link list*
|Provides a link list that serves as placeholder. Click on *Edit* to add a list title, list entries or icons.

|*Dividing line*
|Provides a dividing line that serves as placeholder.

|*Legal information* (Footer)
|Provides the display of legal information. Click on *Edit* to determine which elements should be visible in the footer. Moreover, you can upload a cancellation form.
|====


=== Editing elements of the Ceres homepage with the ShopBuilder

In the preview area, you can edit elements of the homepage to adjust it to your individual needs.

[.instruction]
Editing elements in the preview area:

. Go to *CMS » ShopBuilder*. +
→ The ShopBuilder opens.
. Move the cursor over the element you want to edit. +
→ The context menu opens.
. Click on *Edit*. +
→ The *Settings* bar is displayed.
. Carry out the settings. Pay attention to the information given in <<table-structure-elements-shop-builder>> and <<table-widget-elements-shop-builder>>.
. *Save* the settings. +
→ The homepage of your online store is modified according to the settings.

You can also remove elements.

[.instruction]
Removing elements from the preview area:

. Go to *CMS » ShopBuilder*. +
→ The preview area opens.
. Move the cursor over the element you want to remove. +
→ The context menu opens.
. Click *Delete* to remove the element. +
→ The element is removed. +
→ The surrounding elements are regrouped and replace the deleted element.
. *Save* the settings. +
→ The homepage of your online store is modified according to the settings.

== Editing colour settings in the ShopBuilder

You can globally manage the colour scheme of all your pages in the ShopBuilder.

[.instruction]
Editing colour settings in the ShopBuilder:

. Go to *CMS » ShopBuilder*. +
→ The ShopBuilder opens.
. Click on *Homepage*. +
→ The preview area of the homepage opens.
. Click on *Global colour settings*. +
→ The menu *Editing global colour settings* opens.
. Carry out the settings. Pay attention to the information given in <<table-colours-shop-builder>>.
. *Save* the settings.

[[table-colours-shop-builder]]
.Global colour settings in the ShopBuilder
[cols="1,3"]
|====
|Element |Explanation

|*Primary colour*
|This attribute changes the primary colour of the shop. Choose a colour from the colour picker or enter a hexadecimal value. +
*_Note:_* This value can be used by theme plugins for different colour schemes.

|*Secondary colour*
|This attribute changes the secondary colour of the shop. Choose a colour from the colour picker or enter a hexadecimal value. +
*_Note:_* This value can be used by theme plugins for different colour schemes.

|*Success colour*
|This attribute changes the colour of the success notifications in the shop. Choose a colour from the colour picker or enter a hexadecimal value. *_Note:_* This value can be used by theme plugins for different colour schemes.

|*Information colour*
|This attribute changes the colour of information notifications in the shop. Choose a colour from the colour picker or enter a hexadecimal value. +
*_Note:_* This value can be used by theme plugins for different colour schemes.

|*Warning colour*
|This attribute changes the colour of warning notifications in the shop. Choose a colour from the colour picker or enter a hexadecimal value. +
*_Note:_* This value can be used by theme plugins for different colour schemes.

|*Danger colour*
|This attribute changes the colour of error notifications in the shop. Choose a colour from the colour picker or enter a hexadecimal value. +
*_Note:_* This value can be used by theme plugins for different colour schemes.
|====

== Editing fonts in the ShopBuilder

The ShopBuilder also offers the possibility of selecting individual fonts for the online store. Either enter the URL of a font or upload a font file.

[.instruction]
Editing fonts:

. Go to *CMS » ShopBuilder*. +
→ The ShopBuilder opens.
. Click on *Homepage*. +
→ The preview area of the homepage opens.
. Click on *Design*. +
→ The window *Design* opens.
. Carry out the settings in the *Fonts* fields. Pay attention to the information given in <<table-fonts-shop-builder>>.
. *Save* the settings.

[[table-fonts-shop-builder]]
.Editing fonts in the ShopBuilder
[cols="1,3"]
|====
|Setting |Explanation

|*Enter font URL*
|Enter a URL in the respective fields (regular, *bold*, _italic_ or *_bold-italic_*).

|*Upload font*
|Select a font file from your computer. Select the font file you want to use in the respective fields (regular, *bold*, _italic_ or *_bold-italic_*).
|====

== Carrying out additional settings

The ShopBuilder also serves to carry out all settings available in the Ceres configuration. To do so, proceed as follows.

. Go to *CMS » ShopBuilder*. +
→ The ShopBuilder opens.
. Click on *Settings*. +
→ The menu *Plugin configuration* opens.
. Carry out the settings. Pay attention to the information given in <<omni-channel/online-store/setting-up-ceres#20, Setting up Ceres>>.
. *Save* the settings. +


[TIP]
.Selecting a client in the ShopBuilder

By selecting a client from the drop-down list, the page preview shows the settings performed for the selected client (e.g. which articles are visible).


== Creating a page in the ShopBuilder

The overview of the ShopBuilder offers the possibility of creating and naming new pages for the homepage.

[.instruction]
Creating a page:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder opens.
. Click on *New*. +
→ The window *Create new page* opens.
. Enter a name.
. *Save* the settings. +
→ The newly created page is displayed in the overview.

=== Editing a page in the ShopBuilder

Currently, the overview only enables to edit the name of a page. However, further settings will be available soon.

[.instruction]
Editing the name of a page:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder opens.
. Move the mouse cursor over the page you want to edit.
. Click on the *Options* button.
. Click on *Edit*. +
→ The *Edit* window opens.
. Enter any desired name for the page.
. *Save* the settings.

=== Deleting a page in the ShopBuilder

Pages created in the ShopBuilder can also be removed.

[.instruction]
Deleting a page:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder opens.
. Move the mouse cursor over the element you want to delete.
. Click on the *Options* button.
. Click on *Delete*. +
→ The *Delete* window opens.
. Click on *Delete* to delete the page. +
→ The page is deleted.


=== Deleting links of ShopBuilder pages to the homepage

Every page that is created in the ShopBuilder is automatically linked to the homepage. However, the link can be deleted.

[.instruction]
Deleting a link:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder opens.
. Move the mouse cursor over the page whose link to the homepage you want to delete.
. Click on the *Options* button.
. Click on *Deactivate*. +
→ The link to the homepage is deleted.

=== Recreating links of ShopBuilder pages to the homepage

A deleted link of a ShopBuilder page to the homepage can be recreated.

[.instruction]
Creating a link:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder opens.
. Move the mouse cursor over the page that you want to link to the homepage.
. Click on the *Options* botton.
. Click on *Activate*. +
→ The selected page is linked to the homepage.

The blue marking indicates that a link exists.


== Selecting a language

It is possible to create homepages with different languages independently of one another.

[.instruction]
Selecting a language:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder opens.
. Select a language from the dropdown list.
. Click on *Add page*.
. Enter a name for the page.
. *Save* the settings. +
→ The language settings for the page will be saved automatically.


== Displaying client preview

On the editing page, it is possible to view the created page for the different clients (preview).

[.instruction]
Displaying client preview:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder opens.
. Select a page. +
→ The selected page opens.
. Select the desired client from the dropdown list *client for preview*. +
→ The created page is displayed for the selected client.


== Creating new categories in the ShopBuilder

The categories in the ShopBuilder are displayed on the left in the overview. Here you can create new categories as main or sub categories.

[.instruction]
Creating new categories in the ShopBuilder:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder will open.
. On the left of the category tree, click on *New category*. +
→ The window *Create new category* will open.
. Enter a name and select *Main page* for a main category or *Subpage* for a subcategory.
. If you want to create a subpage, click in the editing window on the category in which you want to create the subcategory.
. Click on *Create*. +
→ The new category has been added to the category tree.


== Creating a header or a footer in the ShopBuilder

In the ShopBuilder you can create a header and a footer. The header and the footer are globally effective for the whole online store.

[.instruction]
Creating a header or footer in the ShopBuilder:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder will open.
. In the section *Header elements* or *Footer elements*, click on *New*. +
→ The window *Create new page* will open.
. Select *Create header* or *Create footer*.
. Enter a name.
. Select either the standard header respectively the standard footer or do not make any selection.
. *Save* the settings. +
→ The header or the footer has been created.
. Click on *Activate/deactivate link* to link the header or the footer.


== Editing the header

The settings carried out in the header are globally effective. For the header, the widgets *Top bar*, *Category navigation* and *Breadcrumbs* are available for selection.

[.instruction]
Globally editing the header:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder will open.
. Click on the header. +
→ The page created for the header will open.
. Via Drag&Drop, move the desired widget into the preview area.
. Click on *Edit*. +
→ The respective editing window will open.
. Carry out the settings. Pay attention to the information given in <<table-widget-elements-shop-builder>>. +
→ The settings are saved automatically.


== Editing the footer

The settings carried out in the footer are globally effective. For the footer, the widget *Legal information* is additionally available for selection.

[.instruction]
Globally editing the footer:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder will open.
. Click on the footer. +
→ The page created for the footer will open.
. Via Drag&Drop, move the desired widget into the preview area.
. Click on *Edit*. +
→ The respective editing window will open.
. Carry out the settings. Pay attention to the information given in <<table-widget-elements-shop-builder>>. +
→ The settings are saved automatically.


== Using the standard header template

For the header you can use the standard header template. Some widgets are already preset and can be edited. Moreover, further widgets can be added. Settings that have already been carried out in the Ceres configuration respectively in the multilingualism are considered.

[.instruction]
Using the standard header template:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder opens.
. In the section Header elements, click *New*. +
→ The window *Create new page* opens.
. Enter a name and select the *Standard header* in the *template* field.
. *Save* the settings. +
→ The page is created in the section Header elements.
. Click on the page. +
→ The preview with the default settings for the standard header opens.
. In order to edit the default settings, click *Edit* in the respective widget.
. Carry out the settings. Pay attention to the information given in <<table-widget-elements-shop-builder>>.


== Using the standard homepage template

For the homepage you can use the standard homepage template. Some widgets are already preset and can be edited. Moreover, further widgets can be added. Settings that have already been carried out in the Ceres configuration respectively in the multilingualism are considered.

[.instruction]
Using the standard homepage template:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder opens.
. In the section Content, click *New*. +
→ The window *Create new page* opens.
. Enter a name and select the *Standard homepage* in the *template* field.
. *Save* the settings. +
→ The page is created in the section Content.
. Click on the page. +
→ The preview with the default settings for the standard homepage opens.
. In order to edit the default settings, click *Edit* in the respective widget.
. Carry out the settings. Pay attention to the information given in <<table-widget-elements-shop-builder>>.


== Using the standard footer template

For the footer you can use the standard footer template. Some widgets are already preset and can be edited. Moreover, further widgets can be added. Settings that have already been carried out in the Ceres configuration respectively in the multilingualism are considered.

[.instruction]
Using the standard footer template:

. Go to *CMS » ShopBuilder*. +
→ The overview of the ShopBuilder opens.
. In the section Footer elements, click *New*. +
→ The window *Create new page* opens.
. Enter a name and select the *Standard footer* in the *template* field.
. *Save* the settings. +
→ The page is created in the section Footer elements.
. Click on the page. +
→ The preview with the default settings for the standard footer opens.
. In order to edit the default settings, click *Edit* in the respective widget.
. Carry out the settings. Pay attention to the information given in <<table-widget-elements-shop-builder>>.

== Ideal image sizes for the ShopBuilder

There are 4 different aspect ratios for images in the *Image box* and *Image carousel* widgets. These ratios are dependent on whether the widget is integrated as a *standalone* or in a *grid* with 2, 3 or 4 columns as well as which layout setting is selected for the grid.

For image widgets that are integrated *without a grid* or in a *2 column grid* with the layout setting *50%:50%*, the ideal image aspect ratio of width to height is *3:1*. If you change the layout settings, the aspect ratio changes to *2:1* (for 66,6% elements) and *1:1* (for 33,3% elements).

For image widgets in a *3 column grid* with the layout setting *30%:30%:30%*, the ideal image aspect ratio of width to height is *1,5:1*. Depending on the layout settings, the aspect ratio changes according to the <<table-image-sizes-shop-builder, table>> below.

For image widgets in a *4 column grid*, the ideal image aspect ratio of width to height is *1:1*. The layout for this type of grid cannot be changed.


[[table-image-sizes-shop-builder]]
.Ideal image sizes for ShopBuilder widgets
[cols="a,a,a,a"]
|====
|Number of grid columns |Layout setting (%) |Aspect ratio | Example size

|Kein Raster
|-
|3:1
|1200x400px

|2
|50%
|3:1
|1200x400px

|2
|66,6%
|2:1
|1200x600px

|2
|33,3%
|1:1
|1200x1200px

|3
|33,3%
|1,5:1
|1200x800px

|3
|50%
|2:1
|1200x600px

|3
|25%
|1:1
|1200x1200px

|3
|66,6% (stacked)
|1,5:1
|1200x800px

|3
|33,3% (stacked)
|1,5:1
|1200x800px

|4
|-
|1:1
|1200x1200px
|====


== Scripts in the TextWidget

To use scripts in the shop, the script2 tag can be used. It is used like a normal script tag.
For the documentation of the framework see link:https://github.com/taoeffect/vue-script2[here^].

<script2 src="https://momentjs.com/downloads/moment.js"></script2>

*Explanation*: Here a script2 tag is used only with the src attribute to load an external script.

<script2> +
    var today = moment().format('dddd'); +
    alert("today is " + today); +
</script2>

*Explanation*: JavaScript code is written within the script2 tag. moment.js is accessed here, which was loaded in the previous script.

*Tip*: External scripts can be uploaded in the webspace and integrated via the ShopBuilder.
