= Attributes
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Attribute, Attribute, Attribute, Attributes, Attributes, Attributes, Characterise products, Characterise items, Create variation, Create variations, Generate variation, Generate variations, Create attribute, Create attributes, Attribute value, Attribute values, Image link possible, Attribute selection in store, Groupable in item lists, Percentage, Automatic distribution, Attribute images, Attribute image, Market attributes, Market attribute, Market attribute link, Attribute name, Attribute names
:description: Attributes simultaneously characterise your products and build saleable variations.
:url: item/settings/attributes
:position: 20
:id: 559N81B
:author: team-item

////
zuletzt bearbeitet 11.02.2021
////

Some items like shoes and t-shirts are sold in various sizes and colours.
In plentymarkets, such characteristics are called attributes.
Attributes help you simultaneously characterise your products and create <<item/introduction/structure#, saleable variations>>, e.g. the t-shirt in the colour red and the size S.

[TIP]
.Other ways to characterise products
====
Do you want to characterise your products _without_ building variations?
For example, do you only want to highlight the technical features of a product in your store?
This is done with the help of <<item/settings/properties#, properties and characteristics>>!
====

Learn about attributes in our playful tutorial:

video::265563423#t=0m31s[vimeo]

[discrete]
=== Procedure

. Create <<item/settings/attributes#100, attributes>> like colour and their corresponding <<item/settings/attributes#200, values>> like red, blue and green.
.. *_Optional_*: Do you sell your products on markets like Amazon and eBay? Some markets require you to <<item/settings/attributes#500, link your own attribute values with their attribute values>>.
.. *_Optional_*: Add <<item/settings/attributes#600, images>> to visually represent your attribute values.
.. *_Optional_*: Save the names of attributes and their values <<item/settings/attributes#1000, in multiple languages>>.


. Combine attribute values together to <<item/settings/attributes#300, create variations>>.
For example, you would get 9 different variations if you combine the sizes S, M, L with the colours red, blue and green.

[#100]
== Creating new attributes

First, create attributes like colour or size.

[.instruction]
Creating a new attribute:

. Go to *Setup » Item » Attributes*.
. Click on *New attribute* (icon:plus[role="green"]).
. Enter the internal name.
. *Save* (icon:save[set=plenty, role="green"]) the settings. +
→ The attribute is created and the tab *Basic settings* is displayed.
. Carry out the additional settings. Note <<table-create-attribute>>.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

[[table-create-attribute]]
.Creating a new attribute
[cols="1,2"]
|====
|Setting |Explanation

| *Name (internal)*
a|include::../_textblocks/table/internal-name.adoc[]

| *Position*
a|Which attribute should be displayed in the plentyShop first, second, third, etc?
Enter a position number into this field.
If an item has multiple attributes, then the attributes will be displayed in ascending order according to their position number.

|[#intable-allow-image-link]*Image link possible*
a|Select this option (icon:check-square[role="blue"]) if you want the item image to change, e.g. on eBay, depending on which size or colour a customer chooses. In other words, the appropriate images will automatically be displayed on eBay.

*_Note:_* Although multiple attributes can be linked with one variation, the image link is only possible for one attribute per variation.

*_Additional settings_*: Link your variations to the appropriate images. Make sure that you’ve made these images available for the marketplace. Then link the variation images to the market attributes. These steps are described in further detail <<item/settings/attributes#900, in another chapter>>.

|[#intable-attribute-selection]*Attribute selection in store*
a|How do you want customers to choose sizes or colours in your plentyShop? Should they choose the name from a drop-down list or click on an image?

* *With drop-down menu* = The attribute names will be displayed in a drop-down list.
* *With image* = The attributes will be displayed as <<item/settings/attributes#700, images in your plentyShop>>.
* *With box* = Attributes are displayed as boxes with attribute values in the plentyShop.

| *Groupable in item lists*
a|include::../_textblocks/table/groupable.adoc[]
|====

[#200]
== Specifying values

Create attribute values like red, blue, green or S, M, L, XL.

[.instruction]
Specifying attribute values:

. Go to *Setup » Item » Attributes*.
. Click on the attribute.
. Click on the *Values* tab.
. Click on *New value* (icon:plus[role="green"]).
. Enter the internal name.
. *Save* (icon:save[set=plenty, role="green"]) the settings. +
→ The attribute value is assigned an ID and displayed in the *Values* tab.
. Carry out the additional settings. Note <<table-create-attribute-values>>.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

[[table-create-attribute-values]]
.Specifying attribute values
[cols="1,2"]
|====
|Setting |Explanation

| *ID*
|A consecutive ID is automatically assigned by the system and cannot be changed.

| *Image*
|How do you want customers to choose sizes or colours in your plentyShop? Should they choose the name from a drop-down list or click on an image? Upload an image here if you want to visually display the attribute value. +
*_Additional settings_*: In the basic settings, specify that this attribute should be selected with an image. Optionally, enter the maximum image size. These steps are described in further detail <<item/settings/attributes#700, in another chapter>>.

| *Position*
|Which attribute value should be displayed in the plentyShop first, second, third, etc?
Enter a position number into this field.
The attribute values will be displayed in ascending order according to their position number.

| *Name*
|Enter a name to be displayed in the plentyShop.

| *Name (internal)*
a|Unique name of the attribute value. The internal name is used in the plentymarkets back end only and is not visible for the customers. The internal name can only be assigned once per attribute. The internal name must not contain the following characters, otherwise errors may occur while exchanging data: +

* Comma
* Colon
* Semicolon
* Quotation marks

| *Note*
|Enter a note about the attribute value (optional).

| *Percentage*
|Enter the percentages for the automatic distribution of attribute values. When reordering an item, the quantities of attribute values will automatically be distributed among the total quantity. +
*__Note:__* Automatic distribution only takes effect for items with exactly two attribute values.
|====

[#300]
== Creating variations with the attributes

An item's first variation is called its _main variation_.
If an item has multiple variations, then the main variation can either be a saleable product or it can be a virtual data record. A virtual main variation is used to manage the other variations of the item with <<item/introduction/inheritance#, inheritance>>.

How exactly you'll proceed depends on whether the main variation should be for sale or not.

[.tabs]
====
Main variation is _not_ for sale::
+
--
Imagine you sell a t-shirt in the sizes S, M, L and XL.
The main variation is not for sale and it doesn't correspond to any of these sizes.
The main variation is simply a data container used to manage prices, categories and other product settings.

. <<item/import-export-create/create/new-item#200, First create the item>> without selecting any attributes.
This will create the main variation without any attributes.
. Then choose the attributes while you <<item/import-export-create/create/new-item#400, create the necessary variations>>.

--
Main variation is for sale::
+
--
Imagine you sell a t-shirt in the sizes S, M, L and XL.
The main variation is for sale and corresponds to one of these sizes, e.g. S.

. <<item/import-export-create/create/new-item#200, First create the item>> and choose the appropriate attribute value, e.g. the size S.
The main variation will be created with this attribute value.
. Then choose the remaining attributes while you <<item/import-export-create/create/new-item#400, create the other variations>>.

--
====

[#400]
== Optional functions

[#500]
=== Linking attribute values with marketplaces

Some markets, such as <<markets/amazon/preparing-variations#1350, Amazon>> and <<markets/ebay/ebay-setup#6100, eBay>>, require you to link _your own_ attribute values with _their attribute values_.
For example, imagine you sell a turquoise t-shirt. But the market you want to sell it on only accepts the colours green and blue. Link your own attribute values with the ones on the other market. This ensures that your items are displayed correctly.

This video illustrates the idea with a playful example:

video::199997850#t=5m27s[vimeo]

[TIP]
.Linking attribute values with variation images too
====
Should the item image also change depending on which size or colour a customer chooses?
Some markets, such as eBay, require you to also <<item/settings/attributes#900, link your variation images with the appropriate attribute values>>.
====

[#600]
=== Visually displaying attributes

[#700]
==== Displaying attribute values as images

How do you want customers to choose sizes or colours in your plentyShop? Should they choose the name from a drop-down list or click on an image?
Follow these three steps if you want your attribute values to be displayed as images.

[.instruction]
Uploading images for attribute values:

. Go to *Setup » Item » Attributes*.
. Click on the attribute.
. Click on the *Values* tab.
. Click on *Upload image* (icon:upload[set=plenty, role="purple"]) in the *Image* column.
. Select the image for the attribute value.
. Click on *Open*.
. *Save* (icon:save[set=plenty, role="green"]) the settings. +
→ The image is uploaded and a preview is shown in the *Image* column.
. Repeat these steps to upload images for other attribute values.

[.instruction]
Changing the appearance in the plentyShop from text to image:

. Go to *Setup » Item » Attributes*.
. Click on the attribute.
. Click on the *Basic setting* tab.
. Select *With image* from the *Attribute selection in store* drop-down list.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

[.instruction]
Changing the size of attribute images:

. Go to *Setup » Item » Images » Settings*.
. Enter the maximum height and width in the *Attribute images* area.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

[#800]
==== Saving an individual image for every variation

Should the item image change in the plentyShop depending on which size or colour a customer chooses?
Follow the steps below if the appropriate images should automatically be displayed.

[#variation-image-link]
[.instruction]
Linking variations to the appropriate images:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Images* tab.
. <<item/managing-items#90, Upload the necessary images>>.
. Select the images (icon:check-square[role="blue"]) that you want to link.
. Click on *Variation link* (icon:plus[role="green"]). +
→ The *Variation link* window is displayed.
. Use the filters on the left as needed.
. Choose which variations (icon:check-square[role="blue"]) should be linked to the selected images.
. Click on *Link* (icon:check[role="green"]). +
→ The images are linked with the selected variations.
. *Save* (icon:save[set=plenty, role="green"]) the settings. +
→ If a customer chooses the variation in your plentyShop, he will see the appropriate item image.

[#900]
===== Linking variation images to market attributes

Should the item image change, e.g. on eBay, depending on which size or colour a customer chooses?

Some markets like eBay not only require you to <<item/settings/attributes#500, link your attributes with the market>>, but also to link your variation images with the appropriate attribute values.

[TIP]
.Have you met all of the requirements?
====
////
nachdem alles umgestellt ist, mache den Link auf Marktplatz-Verfügbarkeit eindeutiger, nicht ganze Kapitel sondern Einstellung
////
Make sure you’ve already <<item/settings/attributes#variation-image-link, linked your variations with the appropriate images>> and that you’ve <<item/managing-items#90, made the images available for the marketplace>>. Furthermore, make sure you’ve <<item/settings/attributes#intable-allow-image-link, allowed image links in the basic settings>>.
====

[.instruction]
Linking variation images to market attributes:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Images* tab.
. Select the appropriate attribute value for the item image from the *Market attribute link* drop-down list.
. *Save* (icon:save[set=plenty, role="green"]) the settings. +
→ If a customer chooses the variation on eBay, he will see the appropriate item image.

[TIP]
.Where do I find the “Market attribute link” field?
====
This option is only displayed if the image has been <<item/settings/attributes#variation-image-link, linked to one or more variations>>.
====

[#1000]
=== Saving the names in multiple languages

Is your plentyShop available in multiple languages? Then you’ll also need to translate the names of your attributes and attribute values.

[.instruction]
Translating the names of attributes:

. Go to *Setup » Item » Attributes*.
. Click on the attribute.
. Click on the *Name* tab.
. Enter the name in as many different languages as needed.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

[TIP]
.How the attribute name is displayed in the plentyShop
====
The name should be as short as possible since it will appear next to a selection box in the plentyShop.
====

[.instruction]
Translating the attribute values:

. Go to *Setup » Item » Attributes*.
. Click on the attribute.
. Click on the *Values* tab.
. Select a language from the *Show language* drop-down list in the header. +
→ Only the text in the *Name* column will change.
. In the *Name* column, enter the attribute values in the selected language.
. *Save* (icon:save[set=plenty, role="green"]) the settings.

[TIP]
.Displaying the name in one language and saving it in another
====
The drop-down list *Save language* indicates which language the name will be saved in when you click on the save icon.
You _won’t_ usually work with this drop-down list since the language is _automatically_ selected here when you choose a language from the *Show language* drop-down list.

However, you can choose a different language from the *Save language* drop-down list if you want to see the name in one language and save it in a different one.
====

[#1100]
== Deleting attributes

Before you can delete an attribute, you have to delete all of the variations that are linked with this attribute.
The <<item/import-export-create/create/mass-processing#300, variation group function>> is a useful tool for doing so.

[.instruction]
Deleting variations linked to an attribute:

. Go to *Item » Edit item*.
. Set the filters on the left as follows:
.. Set the filter <<item/introduction/search#intable-table-type, Table type>> to *Variations*.
.. Set the filter <<item/introduction/search#intable-active, Active>> to *ALL*.
.. Use the <<item/introduction/search#intable-all, ALL>> filter to select the attribute from the drop-down list.
. Click on *Search* (icon:search[role="blue"]). +
→ All variations linked with this attribute are displayed.
. Select all of the variations (icon:check-square[role="blue"]).
. Click on *Variation group function*. +
→ The *Variation group function* window opens.
. In the *Procedures* area, select the option *Delete variations* (icon:check-square[role="blue"]).
. Click on icon:execute[set=plenty] *Execute*. +
→ The variations are deleted. +
→ The attribute can now be deleted.

[.instruction]
Deleting an attribute:

. Go to *Setup » Item » Attributes*.
. Click on *Delete* (icon:minus-circle[role="red"]) in the line of an attribute. +
→ A new window opens.
. Click on *Delete* (icon:minus-circle[role="red"]) again to confirm your decision. +
→ The attribute is deleted.
