= Availabilities
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Availability, Availabilities, Item availability, Item availabilities, Availability level, Availability levels, Availability symbol, Availability icon, Callisto, Back end symbol, Store symbol, Delivery time, Delivery times, Delivery, AvailabilityString, AvailabilityIcon, ItemViewSingleItem, Attribute availability, Server check, Client check
:description: Learn how to configure the ten availability symbols in plentymarkets.
:url: item/settings/availabilities
:position: 70
:id: TFKTSN1
:author: team-item

You are legally required to provide information in your online store about how long it takes to deliver all items that you offer. There are ten availability options in plentymarkets.

First, configure the ten availability levels. In a second step, you’ll define the <<item/managing-items#intable-symbol, availability of each item>>.

[#100]
== Configuring the availability levels

Enter the availability texts one-time only in the plentymarkets back end. You can also replace the default availability icons with your own icons.

[.instruction]
Setting the availability options:

. Go to *Setup » Item » Availability*.
. Carry out the settings. Note <<table-define-availability>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-define-availability]]
.Setting the availability options
[cols="1,3a"]
|====
|Setting |Explanation

| *ID*
|The IDs 1-10 are automatically assigned by plentymarkets and cannot be changed.

*_Use case_*: Imagine you want to <<data/importing-data/sync-types/elasticSync-item#2300, import lots of item data with the help of a CSV file>>. Among other things, you want to specify the availability of each item. You can use the IDs 1-10 to specify the availability of each item.

| *Backend icon*
|The default availability icons of the system are displayed here. These icons are set by default and can be replaced with individual icons.

| *Name*
|Enter a name or a description for the delivery time, e.g. ships within 48 hours, 3-5 business days, etc.

*_Tip_*: Choose a different language from the drop-down list if you want to save the availability texts in multiple languages.

| **Average delivery period**
|Enter the average delivery time in days. These values will be analysed by search engines.

*_Tip_*: Enter realistic delivery times, as this information is considered to be a promise and it is also relevant in terms of competition law.

| *Online store icon*
|Here you’ll see three buttons.
Click on the button on the far left to open a detailed view of the symbol.

[cols="1,4"]
!===

! icon:upload[set=plenty, role="purple"]
! Click on this button to upload your own store icon.
The symbol will be displayed in the online store instead of the back end icon. +
Available image formats: *PNG*, *JPG* and *GIF*. Ideal image size: *16 x 16 pixels*.

! icon:minus-circle[role="red"]
! Click on this button to delete your own store icon.
Once you’ve deleted this icon, the back end icon will be displayed in the online store.

!===
|====

[#200]
== Old store: displaying the availability in Callisto

By default, the availability in the design Callisto is displayed in the online store using the <<online-store/online-store/cms-syntax#web-design-itemview-container-itemviewsingleitem, ItemViewSingleItem>> template. Use the template variables **$AvailabilityString** and **$AvailabilityIcon** to display the availability text and icon in the online store. By default, these template variables are included in the template **ItemViewSingleItem** of the plentymarkets default design.

[TIP]
.Availability is not displayed correctly in the online store
====
If you use your own store icons for the availability, upload files for all availability options. Otherwise, an empty frame will be displayed in the design when the icon is missing. +
If the availability is not displayed correctly in the online store after changes were made, then delete the browser cache and reload the page.
====

[IMPORTANT]
.Relationship to other settings: Attribute availability
====
Whether or not the variation is visible in the online store depends on which <<online-store/online-store/item-layouts#, type of verification>> was selected for the attribute availability in the menu *Setup » Client » [Select client] » Item layouts » Settings*.

* If the option **Attribute availability** is set to **Server check**, the variation is visible and can be selected. The availability will not be checked until the last attribute has been selected in the order process.
* If you select the setting **Client check**, the variation either is not shown in the online store or it is greyed out.
====

[#300]
== Old systems: activating/deactivating the availabilities

Usually only two steps are necessary to specify the delivery times for items offered in your online store.
First, you <<item/settings/availabilities#100, define the individual availability levels>>, e.g. ships within 48 hours, 3-5 business days, etc.
Second, you <<item/managing-items#intable-symbol, link the appropriate availability level to each of your items>>.

The availability levels are activated by default and visible in the online store.
But if an availability level was deactivated for some reason, then products with this availability level will no longer be visible in the online store.
So if an item isn’t visible in your online store, then check to make sure the availability level is activated for the store.

[TIP]
.This setting only affects older systems
====
In new systems, this setting is obsolete and is no longer displayed. We recommend that you check whether you have this setting in your system. If so, activate the setting.
====

[.instruction]
Activating availabilities for the store:

. If available, go to *Setup » Client » [Select client] » Item layouts » Availability*.
. Press and hold Ctrl or Cmd and select the availability options.
. *Save* (icon:save[role="green"]) the settings.
