= Availabilities
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Availability, Availabilities, Item availability, Item availabilities, Availability level, Availability levels, Availability symbol, Availability icon, Delivery time, Delivery times
:description: Learn how to configure the ten availability levels in plentymarkets.
:url: item/settings/availabilities
:position: 70
:id: TFKTSN1
:author: team-item

////
zuletzt bearbeitet 08.04.2021
////

You are legally required to provide information in your online store about how long it takes to deliver all items that you offer.
There are ten availability options in plentymarkets.

[discrete]
=== Procedure

This function is configured in two steps:

* <<item/settings/availabilities#100, Define the ten availability levels>>
* <<item/settings/availabilities#150, Set the availability of each variation>>

[#100]
== Defining the availability levels

Enter the availability texts one-time only in the plentymarkets back end. You can also replace the default availability icons with your own icons.

[.instruction]
Setting the availability options:

. Go to *Setup » Item » Availability*.
. Carry out the settings. Note <<table-define-availability>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-define-availability]]
.Setting the availability options
[cols="1,3a"]
|====
|Setting |Explanation

| *ID*
|The IDs 1-10 are automatically assigned by plentymarkets and cannot be changed.

*_Use case_*: Imagine you want to <<data/importing-data/sync-types/elasticSync-item#550, import lots of item data with the help of a CSV file>>. Among other things, you want to specify the availability of each item. You can use the IDs 1-10 to specify the availability of each item.

| *Backend icon*
|The system’s availability icons are displayed here. These icons are set by default and can be replaced with individual icons.

| *Name*
|Enter a name or a description for the delivery time, e.g. ships within 48 hours, 3-5 business days, etc.

*_Tip_*: Choose a different language from the drop-down list if you want to save the availability texts in multiple languages.

| **Average delivery period**
|Enter the average delivery time in days. These values will be analysed by search engines.

*_Tip_*: Enter realistic delivery times, as this information is considered to be a promise and it is also relevant in terms of competition law.

| *Online store icon*
|Here you’ll see three buttons.
Click on the button on the far left to open a detailed view of the symbol.

[cols="1,4"]
!===

! icon:upload[set=plenty, role="purple"]
! Click on this button to upload your own icon.
The symbol will be displayed in the plentyShop instead of the back end icon. +
Available image formats: *PNG*, *JPG* and *GIF*. Ideal image size: *16 x 16 pixels*.

! icon:minus-circle[role="red"]
! Click on this button to delete your own icon.
Once you’ve deleted this icon, the back end icon will be displayed in the plentyShop.

!===
|====

[#150]
== Setting the availability of a variation

[.tabs]
====
Manually::
+
--
If you only want to save the availability _for a few variations_, then it makes sense to do this manually.

. Go to *Item » Edit item*.
. <<item/introduction/search#400, Search for>> and open the variation.
. Click on the *Settings* tab in the lower row and find the *Availability* area.
. Select the appropriate availability level (symbols 1-10).
. *Save* (icon:save[role="green"]) the settings.

--
Import::
+
--
If you want to save the availability _for lots of variations_, then it makes sense to do this via import.
Use the mapping field *Item variations / Availability* to do so.

[discrete]
===== Further information

////
the link will change once there's new formatting for the sync type item - at that point, fix the link
////

* <<data/importing-data/ElasticSync#, Using the import tool>>
* <<data/importing-data/sync-types/elasticSync-item#550, Information about the mapping field>>

--
Group function or batch processing::
+
--
If you want to save the availability _for lots of variations_, then it makes sense to do this with the variation group function or batch processing.

[discrete]
===== Variation group function

include::../import-export-create/create/mass-processing.adoc[tag=variation-group-function]

. Activate the option with the symbols 1-10 (icon:check-square[role="blue"]) and select the appropriate availability level (icon:dot-circle-o[role="blue"]).
. Click on icon:execute[set=plenty] *Execute* to apply the settings to the variations.

[discrete]
===== Batch processing

include::../import-export-create/create/mass-processing.adoc[tag=variation-batch-processing]

. On the _right_, activate the option with the symbols 1-10 (icon:check-square[role="blue"]) and select the appropriate availability level (icon:dot-circle-o[role="blue"]).
. Click on icon:execute[set=plenty] *Apply* to apply the settings to the variations.

--
====
