= Tags and flags
:lang: en
include::{includedir}/_header.adoc[]
:description: Don’t lose track of your items! Tags and flags are good ways to organise your items and sort them logically.
:url: item/settings/flags
:icons: font
:position: 100
:docinfodir: /workspace/manual-adoc
:docinfo1:

It’s easy to lose track if you work with many different items. Tags and flags are good ways to organise your items and sort them logically.

[TIP]
.What’s the difference between tags and flags?
====
<<item/settings/flags#100, Flags>> can only be linked to entire item data records. In contrast, <<item/settings/flags#400, tags>> can be linked to individual variations. Therefore, tags are much more flexible.

Tags can also be used to highlight other types of data records. In other words, tags can also be used to highlight specific customers, orders, tickets, etc.
====

[#100]
== Flags

The idea is simple. Assign each of your items one or two flags. You’ll see these flags when you look at your <<item/introduction/search#100, items in the overview>>. Such visual aids help you find the right items at a glance. You can also <<item/introduction/search#100, search for items>> that have a specific flag or combination of flags.

Take a look at the different flags that are included in plentymarkets. By default, flags are named after their ID. However, you can <<item/settings/flags#200, rename them as needed>>. Once you’re happy with the names, you can <<item/settings/flags#300, link the flags to items>>.

[#200]
=== Renaming flags

Take a look at the different flags that are included in plentymarkets. There are 31 symbols that you can use as “Flag 1” and 11 symbols that you can use as “Flag 2”. By default, flags are named after their ID. However, you can rename them as needed.

[.instruction]
Renaming a flag:

. Go to *Setup » Item » Flags*.
. In the line *Name*, enter a name.
. *Save* (icon:save[role="green"]) the settings.

[#300]
=== Flagging items

Once you’re happy with the names, you can <<item/managing-items#810, link the flags to items>>. You’ll see these flags when you look at your <<item/introduction/search#100, items in the overview>>. Such visual aids help you find the right items at a glance. You can also <<item/introduction/search#100, search for items>> that have a specific flag or combination of flags.

[#400]
== Tags

In contrast to <<item/settings/flags#100, flags>>, tags can be linked to individual variations. Therefore, tags are much more flexible.

Tags can also be used to highlight other types of data records. In other words, tags can also be used to highlight specific customers, orders, tickets, etc.

[#500]
=== Creating tags

First, <<basics/working-with-plentymarkets/tags#, create the tags>> that you want to use for your items.

[#600]
=== Adding tags to variations

<<item/managing-items#150, Link your variations to as many tags as you want>>. Tags that you link to the main variation are passed on to the item’s other variations. To save other tags for a variation, deactivate inheritance and save different tags.
