= Item images
:lang: en
include::{includedir}/_header.adoc[]
:description: Learn which settings can be configured for item images and how to upload images via FTP.
:url: item/settings/images
:icons: font
:position: 90
:docinfodir: /workspace/manual-adoc
:docinfo1:

Item images are saved on S3 and delivered using CloudFront, a CDN service by AWS. CDN is short for Content Delivery Network. CDN allows completely scalable delivery of item images. CDN makes it possible to only save the original image. A specified dimension of the original image is created when the image is displayed on screen. This dimension is then saved in the CloudFront CDN cache.

Learn which settings can be configured for item images and how to upload images via FTP.

[#100]
== Setting up item images

In the *Setup » Item » Images » Settings* menu, carry out the following settings for item images:

* Import and export
* Placeholder images
* Size of attribute images
* Image names

[.instruction]
Carrying out settings for item images:

. Go to *Setup » Item » Images » Settings*.
. Carry out the settings. Note <<table-image-settings>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-image-settings]]
.Image settings
[cols="1,3"]
|====
|Setting |Explanation

2+|*Settings*

|*Export item image position*
|Select the item image position for the image export, for example to a market. +
The position is defined in the item's <<item/managing-items#90, Images>> tab.

|*Image import using FTP*
|Select whether imported images should be added (default setting) or whether the old images should be deleted before importing the new images.

|*Image names of the FTP import*
|Select whether the file names of <<item/settings/images#600, images imported via the FTP server>> include the *item ID* or the *variation No.*.

|*URL of placeholder image*
|Enter the URL of a placeholder image. This image will be shown if item images cannot be displayed. Upload the placeholder image in the menu *CMS » Webspace*.

|*URL of placeholder preview image*
|Enter the URL of a placeholder image for preview images. This image will be shown if preview images cannot be displayed. Upload the placeholder image in the menu *CMS » Webspace*.

2+|*Attribute images*

|*Max. height in pixels*
|Enter the maximum height of attribute images in pixels. The value *40* is set by default.

|*Max. width in pixels*
|Enter the maximum width of attribute images in pixels. The value *40* is set by default.

2+|Name

|*Original name*; +
*Item ID*; +
*Item No.*; +
*Name 1* - *Name 3*; +
*Keywords*; +
*Model*; +
*Free text field 1* - *Free text field 20*; +
*Own prefix*
|Select parameters to be included in the image name and define positions for the order of parameters in the name. Parameters are hyphenated in the image name. You have to specify the *item ID* or the *item number*. The image name is limited to a maximum of 32 characters.

|*Prefix*
|Enter a prefix to be inserted in the image name. +
*_Note:_* The prefix you enter is only inserted into image names if you selected a position in the *Prefix* drop-down list.
|====

[#200]
== Saving own domain for image URLs

Item images are assigned the URL of the default CDN domain by default. This means that the URLs of item images contain the domain name "plentymarkets.com”. However, instead of the default CDN domain, you can also set up the domain of the client and save a custom subdomain for item images. <<table-domain-image-URLs>> shows the differences between the default CDN domain and an individual CDN domain. You can set up an own CDN domain for domains hosted by plentymarkets and for domains hosted by an external provider. However, note the following limitations:

* You can only save individual subdomains for the main domain.
* You can only save one subdomain for each client.
* The subdomain must not contain *www*.
* The subdomain must not exist in the Service center.

[[table-domain-image-URLs]]
.Own domain for image URLs
[cols="2,3,3"]
|====
| |Image URL with default domain |Image URL with own domain

|URL pattern
a|The URL of item images is created as follows:

. Subdomain *CDN1*, *CDN2* or *CDN3*
. Domain *plentymarkets.com*
. Customer hash
. File path *item/images*
. Item ID
. Folder name of image size
. Name of image file with file extension
a|The own domain is specified instead of the default domain. The customer hash is not shown in the URL:

. Own subdomain.
. Domain of the client
. File path *item/images*
. Item ID
. Folder name of image size
. Name of image file with file extension

|Example URL
|https://*cdn01.plentymarkets.com/ +
1abcd2e3fghi*/item/images/118/full/118-chair-Rio.jpg
|https://*yoursubdomain.yourstore.co.uk*/ +
item/images/118/full/118-chair-Rio.jpg
|====

Proceed as described below to save an own domain for the image URLs of a client.

* <<item/settings/images#300, For a domain hosted by plentymarkets>>
* <<item/settings/images#400, For a domain hosted by an external provider>>

[#300]
=== A domain hosted by plentymarkets

Proceed as described below to save an own domain for the image URLs of a client if your domain is hosted by plentymarkets.

[IMPORTANT]
.Activate the domain after the subdomain has been created
====
It can take several hours for the subdomain to be created. The creation process is complete when green checkmarks are shown in all three columns, i.e. *SSL*, *DNS* and *Cloud status*. Once the subdomain is created, activate the domain.
====

[.instruction]
Saving own domain for image URLs:

. Go to *Setup » Client » Select client » Domains*.
. Click on *Add*. +
→ The *New domain* window opens.
. Carry out the settings. Note <<table-plenty-domain>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The subdomain is created. +
→ A SSL certificate is created for the subdomain. +
→ A DNS record is created for the subdomain. +
→ A CloudFront instance is created. +
*_Note:_* This process can take several hours. The process is complete when green checkmarks are shown in the columns *SSL*, *DNS* and *Cloud status*.
. Once all three checkmarks are shown, click on *Activate* in the *Status* column. +
→ The domain is activated.

[[table-plenty-domain]]
.Saving subdomain for image URLs
[cols="1,3"]
|====
|Setting |Explanation

|*Section*
|Select the type of subdomain from the drop-down list. Currently, only the type *CDN1* is available.

|*Subdomain*
|Enter a custom subdomain. Valid characters are letters (a-z, A-Z), numbers (0-9), underscore (_) and hyphen (-). The first character of the subdomain must be either a letter or a number.

|*Domain*
|Select the domain from the drop-down list. You can only select the main domain of the client.
|====

[#400]
=== A domain hosted by an external provider

If your domain is hosted by an external provider, you need to save the DNS settings with your external domain provider. Proceed as described below to save an own domain for the image URLs of a client and save the DNS settings with the external provider.

[TIP]
.What is DNS?
====
DNS is short for Domain Name System. DNS makes it possible to enter the domain name instead of the numerical IP address of your online store.
====

[.instruction]
Saving own domain for image URLs for an external domain:

. Go to *Setup » Client » Select client » Domains*.
. Click on *Add*. +
→ The *New domain* window opens.
. Carry out the settings. Note <<table-external-domain>>.
. *Save* (icon:save[role="green"]) the settings. +
→ A DNS record is created for the subdomain.
. In the row of the domain entry, click *DNS info*. +
→ The *DNS info* window opens. +
→ The DNS settings are shown.
. Log into the service area of your domain provider.
. Copy the DNS settings shown in plentymarkets into the relevant fields of the domain provider. +
→ Check the documentation of the domain provider on how to do this.
. *Save* (icon:save[role="green"]) the settings. +
→ A SSL certificate is created for the subdomain. +
→ A CloudFront instance is created. +
→ The DNS settings are updated. +
*_Note:_* It can take up to 72 hours for the DNS settings to take effect. plentymarkets is unable to speed up this process. +
→ The process is complete once green checkmarks are shown in the columns *SSL*, *DNS* and *Cloud status* of the *Setup » Client » Open client » Domains* menu in the plentymarkets back end.
. Once all three checkmarks are shown in the *Setup » Clients » Open client » Domains* menu, click on *Activate* in the *Status* column. +
→ The domain is activated.

[[table-external-domain]]
.Saving subdomain for image URLs
[cols="1,3"]
|====
|Setting |Explanation

|*Section*
|Select the type of subdomain from the drop-down list. Currently, only the type *CDN1* is available.

|*Subdomain*
|Enter a custom subdomain. Valid characters are letters (a-z, A-Z), numbers (0-9), underscore (_) and hyphen (-). The first character of the subdomain must be either a letter or a number.

|*Domain*
|Select the domain from the drop-down list. You can only select the main domain of the client.
|====

[#500]
== Specifying item image sizes

In the *Setup » Item » Images » Sizes* menu, you select settings for each image size. The following sizes are available:

* *preview* = The size of the preview image
* *secondPreview* = The size of the second preview image
* *middle* = The size of the medium image
* *full* = The size of the full size image

Proceed as described below to specify the item image sizes.

[.instruction]
Specifying item image sizes:

. Go to *Setup » Item » Images » Sizes*.
. Carry out the settings for each image size. Note <<table-image-sizes>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-image-sizes]]
.Setting the image sizes
[cols="1,3"]
|====
|Setting |Explanation

|*Name*
|Enter an internal name for this image size.

|*Folder name*
|The folder name for this image size. The folder name cannot be changed and is part of the item image’s URL.

|*Maximum height in pixels*
|Enter the maximum height in pixels for images of this size. If your item image exceeds this size, then the displayed image will be scaled down. The aspect ratio will stay the same.

|*Maximum width in pixels*
|Enter the maximum width in pixels for images of this size. If your item image exceeds this size, then the displayed image will be scaled down. The aspect ratio will stay the same.

|*Max. lifetime of cache in days*
|Enter the number of days that created images are saved in the CloudFront cache. The image’s lifetime begins once the image has been displayed on screen in this size, i.e. loaded into the cache.

|*Rotate the output image based on the EXIF Orientation tag*
|Decide whether you want to retain the original image orientation (image rotation of 90, 180, 270°). +
Activated = The original image’s rotation is retained for scaled images of this size.

|*Retain meta data (EXIF, XMP, IPTC) of the original image*
a|Select if the meta data of the original image is to be retained. +
Examples of meta data are description texts, geo data (GPS), date and time.

* *Activated* = The original image’s meta data is retained for scaled images of this size. +
*_Tip:_* To optimise load time and data volume, it may be advisable to not retain meta data particularly for preview images.

|*Do not enlarge*
a|Select if original images are to be enlarged.

* *Not activated* = Images are scaled to size if the original image is smaller than the maximum dimensions defined for this size.

2+|JPG

|*Quality in percent*
|Enter a compression for original JPG images in percent. Compression reduces load times and can help you achieve better page speed values. +
*_Tip:_* Compressing images to 80 % results in no visible loss of quality.

|*Progressive*
a|Select if images of this size are to be displayed instantly when the page is loaded.

* *Activated* = The image is available at low resolution as soon as the page is loaded. The quality of the image increases gradually during page load.

2+|PNG

|*Compression level (0-9)*
a|Select a compression level for PNG files.

* *0* = Lowest compression
* *9* = Highest compression +
PNG is a loss-free format. As such, PNG images are always decompressed and shown at the original quality. However, if you select a higher compression level, the browser needs more time to decompress the image.

|*Progressive*
a|Select if images of this size are to be displayed instantly when the page is loaded.

* *Activated* = The image is available at low resolution as soon as the page is loaded. The quality of the image increases gradually during page load.
|====

[NOTE]
.Invalidate CDN cache
====
It may be necessary to clear the image cache after changing settings in the *Setup » Item » Images* menu. Images may be displayed with old settings because these settings are still saved in the cache. Click on *Invalidate CDN cache*, to show the changes more quickly. The cache invalidation is done by CloudFront.
After you invalidate the cache, each image size is created on the fly when the image is opened.
====

[#600]
== Uploading item images via FTP server

Every plentymarkets system has its own <<basics/admin-tasks/ftp-access#, FTP server>>. This FTP server contains the folder *upload_article_image_XXXX* (XXXX = plentyID) to which you can upload item images.  The folder is checked for changes every 60 minutes. New, correctly named images are assigned to the correct item automatically. To upload files, you need an FTP program and your FTP login details.

[#700]
=== Naming of item image files for FTP import

Go to *Setup » Item » Images » Settings* and use the option *Image names of the FTP import* to choose whether the file names of the imported item images include the item ID or the variation No. Depending on this setting, you either name the files with the item ID or the variation number.

[NOTE]
.Valid characters for file names
====
The following characters are supported for image file names:

* Letters (a-z, A-Z) excluding umlauts
* Numbers (0-9)
* Underscores (_)
* Hyphens (-)

Spaces and special characters are not permitted. When you upload images, spaces and special characters are replaced by hyphens (-).
====

If you want to upload several images for one item, number the files by adding suffixes. You have to separate the image number from the item ID or variation No. with three hyphens, i.e. *---*. You can upload up to 100 images per item by numbering them from 0 to 99.

[.instruction]
Example:

You want to upload images for an item with item ID 4562 and the variation number AQ3957.

[[table-ftp-compliant-naming]]
.Examples of FTP compliant naming of item images
[cols="2,1,1"]
|====
|Setting |Naming 1 image per item |Naming more than 1 image per item

|*Image names of the FTP import* = *Item ID*
a|
* 4562.jpg
* 4562.png
* 4562.gif
* 4562.svg

a|
* 4652---0.jpg
* 4652---1.jpg
* 4652---2.gif

|*Image names of the FTP import* = *Variation number*
a|
* AQ3957.jpg
* AQ3957.png
* AQ3957.gif
* AQ3957.svg

a|
* AQ3957---0.png
* AQ3957---19.png

|====

[#800]
=== Importing item images via FTP server

Proceed as described to import item images to the FTP server.

[.instruction]
Importing item images using FTP:

. Copy the item images that you want to upload using FTP to a folder on your hard drive.
. Check the <<item/settings/images#700, names of the image files>>.
. Modify the names of the image files if they do not comply with the file name conventions.
. Select the target folder *upload_article_image_XXXX* (XXXX = plentyID) in your FTP program.
. In the *Upload* section of your FTP program, select the files to be uploaded.
. Start the upload. +
→ The images are assigned to the items and displayed in the online store after up to 60 minutes.

[TIP]
.Take upload time into account
====
200 images are processed in each run, 2000 images if you have your own server. Depending on the data volume, the upload may take several hours, even if you have a powerful computer and a fast data connection. Therefore, schedule the file upload at a time when it will not interfere with your day-to-day business.
====
