= Manufacturers
:lang: en
include::{includedir}/_header.adoc[]
:description: plentymarkets helps you manage your manufacturers. Learn how to save your manufacturer data in plentymarkets.
:url: item/settings/manufacturers
:icons: font
:position: 50
:docinfodir: /workspace/manual-adoc
:docinfo1:

//bei jeder Überarbeitung, schauen was der Stand hier ist.
//https://forum.plentymarkets.com/t/unterscheidet-plenty-zwischen-hersteller-hersteller/440009/3

Who makes your products? Do your manufacturers get paid a commission? plentymarkets helps you manage your manufacturers.

You can either <<item/settings/manufacturers#100, manually save manufacturer data>> in plentymarkets or you can import this data with a <<item/settings/manufacturers#200, tool called ElasticSync>>. You can also <<item/settings/manufacturers#300, save commissions for your manufacturers>> and specify <<item/settings/manufacturers#400, who manufacturers each of your items>>.

[#100]
== Manually saving manufacturer data

Create a data record for each of your manufacturers. If you only want to create data records for a few manufacturers, then we would recommend creating them manually. However, if you have a lot of different manufacturers, then it will probably be quicker to <<item/settings/manufacturers#200, import your manufacturer data>>.

[.instruction]
Manually adding a new manufacturer:

. Go to *Setup » Item » Manufacturers*.
. Click on icon:plus[role="green"] *New*. +
→ The *New manufacturer* tab opens.
. Enter the manufacturer data. Note <<table-add-manufacturers>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The manufacturer is added.

[[table-add-manufacturers]]
.Adding manufacturers
[cols="1,2"]
|====
|Setting |Explanation

|*ID*
|Enter the manufacturer's ID or leave the field empty. If you do not enter an ID, the next available ID will automatically be assigned to the manufacturer.

|*Name*
|Enter the internal name of the manufacturer.

|*Logo URL*
|Enter the URL that leads to the manufacturer’s logo. The URL can have up to 2,000 characters.

|*Homepage*
|Enter the URL that leads to the manufacturer’s homepage. The URL can have up to 2,000 characters.

|*Street*; +
*House No.*; +
*Postcode*; +
*Town*; +
*Country*; +
*Telephone number*; +
*Fax number*; +
*Email*
|Enter the manufacturer’s address data.

|*PIXmania ID*; +
*Neckermann.de Enterprise ID*; +
*Neckermann.at Enterprise ID*; +
*Neckermann.at Cross-Docking ID*; +
*La Redoute ID*; +
*Netto eStores ID*; +
*Cdiscount.com ID*
|Enter the manufacturer's ID of the market. You will receive the manufacturer's IDs of a market when setting up the <<markets#, market>>.

|*External name*
|Enter an external name for the manufacturer in order to save an alternative name for the export. The manufacturer name that you enter here will be used when the item is exported to external markets. If no external name was entered, the *name* will be used. The external name will also be transferred to <<online-store/online-store/extras/findologic#, FINDOLOGIC>> and will be indexed for the search.

|*Position*
|Enter a position for the manufacturer. By default, manufacturers are assigned the position *0*. Manufacturers with identical positions are sorted by name.

|*Comment*
|Enter an internal comment about the manufacturer, if needed.
|====

[TIP]
.Can I save my manufacturer data in the CRM menu instead?
====
Maybe you noticed that it’s possible to <<crm/managing-contacts#90, create manufacturer data records in the CRM menu>>. But be careful. This data is _not_ transferred over to the menu *Setup » Item » Manufacturers*. Therefore, we recommend that you ignore the manufacturer data in the CRM menu for now.
====

[#200]
== Importing manufacturer data

Create a data record for each of your manufacturers. If you only want to create data records for a few manufacturers, then we would recommend <<item/settings/manufacturers#100, creating them manually>>. However, if you have a lot of different manufacturers, then it will probably be quicker to import your manufacturer data.

Manufacturer data records are imported with a <<data/importing-data/ElasticSync#, tool called ElasticSync>>. The idea is simple. Rather than manually saving manufacturer information in plentymarkets, you’ll <<data/importing-data/sync-types/elasticSync-manufacturer#, enter the same information into a CSV file>> and then import this file into your system.

[#300]
== Adding commissions

Have you already <<item/settings/manufacturers#100, saved basic manufacturer data>>? Then you’re ready to add commission models as needed.

[.instruction]
Adding manufacturer commissions:

. Go to *Setup » Item » Manufacturers*.
. Click on the pencil (icon:pencil[role="yellow"]). +
→ The manufacturer data record opens in a new tab.
. Click on the *Commissions* tab.
. Click on the plus (icon:plus[role="green"]). +
→ A new line for commissions is added to the table.
. Enter information about the commission. Note <<table-add-manufacturer-commission>>.
. *Save* (icon:save[role="green"]) the settings. +
→ An ID is assigned to the commission automatically.

[[table-add-manufacturer-commission]]
.Adding commissions for manufacturers
[cols="1,2"]
|====
|Setting |Explanation

|*Client (store)*
|Which company does the commission apply to? Select a client from the drop-down list.

|*Referrer*
|Which market or sales platform does the commission apply to? Select the order referrer from the drop-down list.

|*Commission*
|Enter a value in percent for the commission.
|====

[TIP]
.Transferring commissions to other manufacturers
====
Do the same commission models apply to several different manufacturers? You don’t have to manually save each commission! Simply copy a commission and transfer it to other manufacturers.

First, click on *Copy commission to other manufacturers* (icon:files-o[role="yellow"]). Then use check marks (icon:check-square[role="blue"]) to specify which commission you want to copy and which manufacturers you want to transfer it to.
Finally, click on icon:save[role="green"] *Copy commission*.
====

[#400]
== Linking manufacturers to items

Once you’ve saved your manufacturer data in plentymarkets, you’ll specify who manufactured each individual item. This is done by linking each item with a manufacturer.

There are several different ways to link items to manufacturers:

* Specify the manufacturer <<item/managing-items#20, while you manually create a new item>>.
* Specify the manufacturer <<item/managing-items#610, in an existing item’s Global tab>>.
* <<item/managing-items#155, Use the group function>> to manually specify the manufacturer for several existing items at once.
* Do you want to import your items with ElasticSync? Then <<data/importing-data/sync-types/elasticSync-item#2260, specify each item’s manufacturer in the CSV file>> that you will import.

[#500]
== Deleting manufacturers

Before you can delete a manufacturer, you’ll have to delete all of the links to the manufacturer.
The <<item/managing-items#155, item group function>> is a useful tool for doing so.

//In order to delete manufacturers, all links between items and manufacturers must be deleted first. Use the *Item group function* and proceed as follows.

[.instruction]
Deleting links to the manufacturer:

. Go to *Item » Edit item*.
. In the *Manufacturer* filter, select the manufacturer from the drop-down list.
. Select *ALL* in the *Active* filter.
. Click on *Search* (icon:search[role="blue"]). +
→ All items linked with this manufacturer are displayed.
. Select all of the items (icon:check-square[role="blue"]).
. Click on *Item group function*. +
→ The *Item group function* window opens.
. Select the *Manufacturers* option (icon:check-square[role="blue"]) in the *Global* area.
. Select the empty option from the drop-down list.
. Click on *Execute* (icon:cog[role="darkGrey", stack="arrow-right,lr"]). +
→ The manufacturer links are deleted. +
→ The manufacturers can now be deleted.

[.instruction]
Deleting manufacturers:

. Go to *Setup » Item » Manufacturers*.
. Click on *Delete* (icon:minus-circle[role="red"]) in the line of a manufacturer. +
→ A new window opens.
. Click on *Delete* (icon:minus-circle[role="red"]) again to confirm your decision. +
→ The manufacturer is deleted.
