= Manufacturers
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Manufacturer, Manufacturers, Commission, Manufacturer data, Manufacturer commission, Commission models, Commission model, Brand, Brands, Producer
:description: plentymarkets helps you manage your manufacturers. Learn how to save your manufacturer data in plentymarkets.
:url: item/settings/manufacturers
:position: 50
:id: RF86X9P
:author: team-item

////
zuletzt bearbeitet 04.01.2022

bei jeder Überarbeitung, schauen was der Stand hier ist.
https://forum.plentymarkets.com/t/unterscheidet-plenty-zwischen-hersteller-hersteller/440009/3
////

Who makes your products?
Which brands do you sell?
plentymarkets helps you manage your manufacturer data.

[discrete]
=== Procedure

* First, <<item/settings/manufacturers#100, create the necessary manufacturer data records>> manually or via import.
* Then add <<item/settings/manufacturers#300, commission models>> as needed.
* Finally, specify who manufactured each of your items. This is done by <<item/settings/manufacturers#400, linking your items to manufacturers>>.
* Should your customers be able to search in the plentyShop for products made by a specific manufacturer?
Customise the <<item/settings/manufacturers#450, plentyShop settings>> as needed.

[#100]
== Creating manufacturer data records

[.tabs]
====
Manual creation::
+
--
. Go to *Setup » Item » Manufacturers*.
. Click on icon:plus[role="green"] *New*. +
→ The *New manufacturer* tab opens.
. Enter the manufacturer data.
. *Save* (icon:save[set=plenty, role="green"]) the settings. +
→ The manufacturer is added.

--
Data import::
+
--
plentymarkets has an <<data/importing-data/ElasticSync#, import tool>>.
The idea is simple. Rather than manually saving manufacturer information in plentymarkets, you’ll <<data/importing-data/sync-types/elasticSync-manufacturer#, enter the same information into a CSV file>> and then import this file into your system.

--
====

[TIP]
.Can I save my manufacturer data in the CRM menu instead?
====
Maybe you noticed that it’s possible to <<crm/managing-contacts#90, create manufacturer data records in the CRM menu>>.
But be careful.
This data is _not_ transferred over to the menu *Setup » Item » Manufacturers*.
Therefore, we recommend that you ignore the manufacturer data in the CRM menu for now.
====

:manual:

[cols="1,3a"]
|====
|Setting |Explanation

| *ID*
|
include::../_textblocks/settings/manufacturer/manufacturer-id.adoc[]

| *Name*
|
include::../_textblocks/settings/manufacturer/manufacturer-name.adoc[]

| *Logo URL*
|
include::../_textblocks/settings/manufacturer/logo-url.adoc[]

| *Homepage*
|
include::../_textblocks/settings/manufacturer/homepage.adoc[]

| *Street*
|
include::../_textblocks/settings/manufacturer/street.adoc[]

| *House No.*
|
include::../_textblocks/settings/manufacturer/house-no.adoc[]

| *Postcode*
|
include::../_textblocks/settings/manufacturer/postcode.adoc[]

| *Town*
|
include::../_textblocks/settings/manufacturer/town.adoc[]

| *Country*
|
include::../_textblocks/settings/manufacturer/country.adoc[]

| *Telephone number*
|
include::../_textblocks/settings/manufacturer/telephone-number.adoc[]

| *Fax number*
|
include::../_textblocks/settings/manufacturer/fax-number.adoc[]

| *Email*
|
include::../_textblocks/settings/manufacturer/email.adoc[]

| *PIXmania ID*
|
include::../_textblocks/settings/manufacturer/pixmania.adoc[]

| *Neckermann.de Enterprise ID*
|
include::../_textblocks/settings/manufacturer/neckermann.adoc[]

| *Neckermann.at Enterprise ID*
|
include::../_textblocks/settings/manufacturer/neckermann.adoc[]

| *La Redoute ID*
|
include::../_textblocks/settings/manufacturer/laredoute.adoc[]

| *Netto eStores ID*
|Enter the manufacturer ID for the market.
You will receive the manufacturer ID when setting up the market.

| *Cdiscount.com ID*
|Enter the manufacturer ID for the market.
You will receive the manufacturer ID when setting up the market.

| *External name*
|
include::../_textblocks/settings/manufacturer/external-name.adoc[]

| *Position*
|
include::../_textblocks/settings/manufacturer/manufacturer-position.adoc[]

| *Comment*
|
include::../_textblocks/settings/manufacturer/comment.adoc[]

|====

[#300]
== Adding commissions

Once you’ve <<item/settings/manufacturers#100, saved basic manufacturer data>>, you’re ready to add commission models as needed.

[.instruction]
Adding manufacturer commissions:

. Go to *Setup » Item » Manufacturers » [Open manufacturer] » Tab: Commissions*.
. Click on *Add* (icon:plus[role="green"]). +
→ A new line for commissions is added to the table.
. Enter information about the commission.
. *Save* (icon:save[set=plenty, role="green"]) the settings. +
→ An ID is assigned to the commission automatically.

[cols="1,3a"]
|====
|Setting |Explanation

| *Client (store)*
|Which company does the commission apply to? Select a client from the drop-down list.

| *Referrer*
|Which market or sales platform does the commission apply to? Select the order referrer from the drop-down list.

| *Commission*
|Enter a value in percent for the commission.

| icon:copy[set=plenty, role="yellow"]
|Do the same commission models apply to several different manufacturers?
You don’t have to manually create each commission.
Instead, you can copy a commission and apply it to other manufacturers.

. Click on *Copy commission to other manufacturers* (icon:copy[set=plenty, role="yellow"]). +
→ A pop-up window opens.
. Upper part of the window: select the commission (icon:check-square[role="blue"]) that you want to copy.
. Lower part of the window: select the manufacturers (icon:check-square[role="blue"]) that the commission should apply to.
. Click on icon:save[set=plenty, role="green"] *Copy commission*.

|====

[#400]
== Linking manufacturers to items

Once you’ve saved your manufacturer data in plentymarkets, you’ll specify who manufactured each individual item. This is done by linking each item with a manufacturer.

There are several different ways to link items to manufacturers:

* Specify the manufacturer <<item/import-export-create/create/new-item#200, while you manually create a new item>>.
* Specify the manufacturer <<item/managing-items#40, in an existing item’s Global tab>>.
* <<item/import-export-create/create/mass-processing#100, Use the group function>> to manually specify the manufacturer for several existing items at once.
* Do you want to import your items? Then <<data/importing-data/sync-types/elasticSync-item#2260, specify each item’s manufacturer in the CSV file>> that you will import.

[#450]
== Checking the plentyShop settings

Should your customers be able to search in the plentyShop for products made by a specific manufacturer?
Then make sure that you’ve configured the following settings:

* <<item/settings/manufacturers#100, External name>>: Have you saved an external name for the manufacturer?
* <<item/online-store/search-bar#70, Search bar>>: Are manufacturers included in the search results?
* <<item/frontend-item-search#, Search filters>>: Have you read the instructions on setting up the so-called faceted search?

[#500]
== Deleting manufacturers

Before you can delete a manufacturer, you’ll have to delete all of the links to the manufacturer.
The <<item/import-export-create/create/mass-processing#200, variation group function>> is a useful tool for doing so.

[.instruction]
Deleting links to the manufacturer:

. Go to *Item » Edit item*.
. Set the filters on the left as follows:
.. Set the filter <<item/introduction/search#intable-table-type, Table type>> to *Item*.
.. Set the filter <<item/introduction/search#intable-active, Active>> to *ALL*.
.. Use the <<item/introduction/search#intable-manufacturer, Manufacturer>> filter to select the manufacturer from the drop-down list.
. Click on *Search* (icon:search[role="blue"]). +
→ All items linked with this manufacturer are displayed.
. Select all of the items (icon:check-square[role="blue"]).
. Click on *Item group function*. +
→ The *Item group function* window opens.
. Select the *Manufacturers* option (icon:check-square[role="blue"]) in the *Global* area.
. Select the empty option from the drop-down list.
. Click on icon:execute[set=plenty] *Execute*. +
→ The manufacturer links are deleted. +
→ The manufacturers can now be deleted.

[.instruction]
Deleting manufacturers:

. Go to *Setup » Item » Manufacturers*.
. Click on *Delete* (icon:minus-circle[role="red"]) in the line of a manufacturer. +
→ A new window opens.
. Click on *Delete* (icon:minus-circle[role="red"]) again to confirm your decision. +
→ The manufacturer is deleted.
