= Manufacturers
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Manufacturer, Manufacturers, Commission, Manufacturer data, Manufacturer commission, Commission models, Commission model, Brand, Brands, Producer
:description: plentymarkets helps you manage your manufacturers. Learn how to save your manufacturer data in plentymarkets.
:url: item/settings/manufacturers
:position: 50
:id: RF86X9P
:author: team-item

////
zuletzt bearbeitet 15.02.2021

bei jeder Überarbeitung, schauen was der Stand hier ist.
https://forum.plentymarkets.com/t/unterscheidet-plenty-zwischen-hersteller-hersteller/440009/3
////

Who makes your products?
Which brands do you sell?
plentymarkets helps you manage your manufacturer data.

[discrete]
=== Procedure

* First, create the necessary manufacturer data records <<item/settings/manufacturers#150, manually>> or <<item/settings/manufacturers#200, via import>>.
* Then add <<item/settings/manufacturers#300, commission models>> as needed.
* Finally, specify who manufactured each of your items. This is done by <<item/settings/manufacturers#400, linking your items to manufacturers>>.
* Should your customers be able to search in the plentyShop for products made by a specific manufacturer?
Customise the <<item/settings/manufacturers#450, plentyShop settings>> as needed.

[#100]
== Creating manufacturer data records

[#150]
=== Manual creation

. Go to *Setup » Item » Manufacturers*.
. Click on icon:plus[role="green"] *New*. +
→ The *New manufacturer* tab opens.
. Enter the manufacturer data. Note <<table-add-manufacturers>>.
. *Save* (icon:save[set=plenty, role="green"]) the settings. +
→ The manufacturer is added.

[[table-add-manufacturers]]
.Adding manufacturers
[cols="1,3"]
|====
|Setting |Explanation

| *ID*
|The manufacturer’s unique ID.

*_Recommendation_*: Leave this field blank while creating new manufacturer data records.
If you leave the field blank, then the manufacturer will automatically be assigned the next available ID.

| *Name*
|Enter the internal name of the manufacturer.

| *Logo URL*
|Enter the URL that leads to the manufacturer’s logo.
The URL can have up to 2,000 characters.

| *Homepage*
|Enter the URL that leads to the manufacturer’s homepage.
The URL can have up to 2,000 characters.

| *Street* +
*House No.* +
*Postcode* +
*Town* +
*Country* +
*Telephone number* +
*Fax number* +
*Email*
|Enter the manufacturer’s address and contact data.

| *PIXmania ID* +
*Neckermann.de Enterprise ID* +
*Neckermann.at Enterprise ID* +
*Neckermann.at Cross-Docking ID* +
*La Redoute ID* +
*Netto eStores ID* +
*Cdiscount.com ID*
|Enter the manufacturer ID for the market.
You will receive the manufacturer ID when setting up the market.

| *External name*
a|Enter the external name of the manufacturer.

* The external name will be visible to customers in the plentyShop.
It is also <<item/settings/manufacturers#450, relevant for the search function in your plentyShop>>.
* When you transfer your item data to marketplaces later, this external manufacturer name will be transmitted.

| *Position*
|Enter a position number for the manufacturer.
If you leave this field blank, then the position number 0 will automatically be assigned.

Manufacturer data records can be sorted by their position number in the menu *Setup » Item » Manufacturers*.
Move your mouse cursor over the column header *Position*.
Click on the small triangle (icon:caret-down[role="darkGrey"]) to sort the manufacturers in ascending or descending order by their position number.
Manufacturers with identical positions are sorted by name.

| *Comment*
|Enter an optional comment about the manufacturer.
This is an internal comment, i.e. it is only visible in your plentymarkets system.
|====

[TIP]
.Can I save my manufacturer data in the CRM menu instead?
====
Maybe you noticed that it’s possible to <<crm/managing-contacts#90, create manufacturer data records in the CRM menu>>. But be careful. This data is _not_ transferred over to the menu *Setup » Item » Manufacturers*. Therefore, we recommend that you ignore the manufacturer data in the CRM menu for now.
====

[#200]
=== Import

plentymarkets has an <<data/importing-data/ElasticSync#, import tool>>.
The idea is simple. Rather than manually saving manufacturer information in plentymarkets, you’ll <<data/importing-data/sync-types/elasticSync-manufacturer#, enter the same information into a CSV file>> and then import this file into your system.

[#300]
== Adding commissions

Once you’ve <<item/settings/manufacturers#100, saved basic manufacturer data>>, you’re ready to add commission models as needed.

[.instruction]
Adding manufacturer commissions:

. Go to *Setup » Item » Manufacturers*.
. Click on *Edit* (icon:pencil[role="yellow"]). +
→ The manufacturer data record opens in a new tab.
. Open the *Commissions* tab.
. Click on *Add* (icon:plus[role="green"]). +
→ A new line for commissions is added to the table.
. Enter information about the commission. Note <<table-add-manufacturer-commission>>.
. *Save* (icon:save[set=plenty, role="green"]) the settings. +
→ An ID is assigned to the commission automatically.

[[table-add-manufacturer-commission]]
.Adding commissions for manufacturers
[cols="1,3"]
|====
|Setting |Explanation

| *Client (store)*
|Which company does the commission apply to? Select a client from the drop-down list.

| *Referrer*
|Which market or sales platform does the commission apply to? Select the order referrer from the drop-down list.

| *Commission*
|Enter a value in percent for the commission.
|====

[TIP]
.Transferring commissions to other manufacturers
====
Do the same commission models apply to several different manufacturers? You don’t have to manually save each commission! Simply copy a commission and transfer it to other manufacturers.

First, click on *Copy commission to other manufacturers* (icon:copy[set=plenty, role="yellow"]). Then use check marks (icon:check-square[role="blue"]) to specify which commission you want to copy and which manufacturers you want to transfer it to.
Finally, click on icon:save[set=plenty, role="green"] *Copy commission*.
====

[#400]
== Linking manufacturers to items

Once you’ve saved your manufacturer data in plentymarkets, you’ll specify who manufactured each individual item. This is done by linking each item with a manufacturer.

There are several different ways to link items to manufacturers:

* Specify the manufacturer <<item/import-export-create/create/new-item#200, while you manually create a new item>>.
* Specify the manufacturer <<item/managing-items#40, in an existing item’s Global tab>>.
* <<item/import-export-create/create/mass-processing#100, Use the group function>> to manually specify the manufacturer for several existing items at once.
* Do you want to import your items? Then <<data/importing-data/sync-types/elasticSync-item#2260, specify each item’s manufacturer in the CSV file>> that you will import.

[#450]
== Checking the plentyShop settings

Should your customers be able to search in the plentyShop for products made by a specific manufacturer?
Then make sure that you’ve configured the following settings:

* <<item/settings/manufacturers#150, External name>>: Have you saved an external name for the manufacturer?
* <<item/online-store/search-bar#70, Search bar>>: Are manufacturers included in the search results?
* <<item/frontend-item-search#, Search filters>>: Have you read the instructions on setting up the so-called faceted search?

[#500]
== Deleting manufacturers

Before you can delete a manufacturer, you’ll have to delete all of the links to the manufacturer.
The <<item/import-export-create/create/mass-processing#200, variation group function>> is a useful tool for doing so.

[.instruction]
Deleting links to the manufacturer:

. Go to *Item » Edit item*.
. Set the filters on the left as follows:
.. Set the filter <<item/introduction/search#intable-table-type, Table type>> to *Item*.
.. Set the filter <<item/introduction/search#intable-active, Active>> to *ALL*.
.. Use the <<item/introduction/search#intable-manufacturer, Manufacturer>> filter to select the manufacturer from the drop-down list.
. Click on *Search* (icon:search[role="blue"]). +
→ All items linked with this manufacturer are displayed.
. Select all of the items (icon:check-square[role="blue"]).
. Click on *Item group function*. +
→ The *Item group function* window opens.
. Select the *Manufacturers* option (icon:check-square[role="blue"]) in the *Global* area.
. Select the empty option from the drop-down list.
. Click on icon:execute[set=plenty] *Execute*. +
→ The manufacturer links are deleted. +
→ The manufacturers can now be deleted.

[.instruction]
Deleting manufacturers:

. Go to *Setup » Item » Manufacturers*.
. Click on *Delete* (icon:minus-circle[role="red"]) in the line of a manufacturer. +
→ A new window opens.
. Click on *Delete* (icon:minus-circle[role="red"]) again to confirm your decision. +
→ The manufacturer is deleted.
