= Sales prices and price calculation
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Price, Prices, Sales price, Sales prices, Price calculation, Price calculations, Calculation, Calculations, Assistant, Assistants, Sales price assistant, RRP, Special offer, Set price, Customer classes, Customer class, Quantity-based dependency, Currency, Currencies, Subscription int., Minimum quantity, Live conversion, Standard currency, Conversion factor, Price type, Monetary price, Monetary prices, Profit margin, Purchase price, Price source, Transportation costs, Storage costs, Operating costs, Operator, Operand, Manufacturer commission, Manufacturer commissions, Price range, Price ranges, Price scale, Price scales, Scale of prices, Sliding scale, Graduated prices, Staggered prices
:description: Learn about sales prices, price calculations, their settings and your opportunities.
:url: item/settings/prices
:position: 70
:id: GBG1FJX
:author: team-item

Prices are an important topic for any business.
Thanks to plentymarkets, you can be very flexible with your prices.

* First, you can <<item/settings/prices#100, define the conditions>> under which your products are sold at a specific price.
For example, you can sell products for a lower price in the online store than on Amazon.
Or you can sell products cheaper to B2B customers than to B2C customers. In plentymarkets, such conditions are called _sales prices_.
* Second, you can save <<item/settings/prices#900, prices for each individual variation>>.
For example, if you sell a t-shirt in S, M, L and XL, then you can decide whether the XL variation should be a bit more expensive than the rest.
* Third, you can have plentymarkets <<item/settings/prices#1000, automatically calculate your monetary prices>>.
For example, you could start out with the item’s purchase price and then add transportation costs, storage costs and taxes. Finally, you could add a 20% profit margin on top.

This video gives you a playful introduction to sales prices, price calculations, their settings and your opportunities:

.Learn about sales prices in our playful tutorial
video::265563480[vimeo]

[#100]
== Sales prices

Sales prices define the _conditions_ under which a variation is sold at a specific price.
For example, you can sell products for a lower price in the online store than on Amazon. Or you can sell products cheaper to B2B customers than to B2C customers.

New plentymarkets systems come equipped with _two default sales prices_.
Take a look at these default sales prices and use them to get acquainted with the topic.
Feel free to modify the default sales prices and/or create entirely new sales prices.

[#200]
=== Creating new sales prices

Sales prices are created and managed centrally in plentymarkets.
You can either <<item/settings/prices#300, create new sales prices with the help of an assistant>> or you can <<item/settings/prices#400, manually create new sales prices in the setup menu>>.
Both procedures are described below.

Either way, you’ll customise the sales prices to meet your needs.
You’ll give the sales prices names and you’ll decide which currencies, customer classes, marketplaces or other conditions should apply.
Finally, you’ll <<item/settings/prices#900, link the sales prices to individual variations>>.

[TIP]
.Avoid frequent sources of errors
====
To avoid errors, you should not configure multiple sales prices with the same conditions.
Example: If you create two different sales prices that are both valid for Amazon, plentymarkets will not know which one to use.
====

[#300]
==== With the assistant

Use the assistant to easily create new sales prices.
The assistant guides you through all of the _most common settings_.
During the process, you’ll give the sales prices names and you’ll decide which currencies, customer classes, marketplaces or other conditions should apply.
There are also <<item/settings/prices#800, a few advanced settings>>, which are optional. You might want to configure these settings afterwards.


[.instruction]
Creating a sales price:

. Go to *Setup » Assistants » Basic setup*.
. Click on the sales prices assistant.
. Click on New configuration (icon:plus[role="green"]).
. Follow the instructions on the screen. Expand the info box below (icon:chevron-down[role="darkGrey"]) if you need additional information about one of the options.
. Check the summary for any possible errors and click on icon:check[role="green"] *Finalise*. +
→ The assistant is finished. Repeat these steps until you’ve created all of the sales prices that your company needs.

The assistant guides you through all of the _most common settings_ for sales prices. However, there are also <<item/settings/prices#800, a few advanced settings>>, which are optional. You might want to configure these settings afterwards.

Once you’ve finished configuring all of the sales prices that your company needs, you’ll be ready to <<item/settings/prices#900, link these sales prices to item data records>>.

[.collapseBox]
.*Additional information about the individual options*
--

[[table-sales-price-assistant]]
[width="100%"]
[cols="1,3"]
|====
|Setting |Explanation

2+|Step: Settings

| *Type*
a|Which type of sales price do you want to configure? In most cases, you’ll create a _standard sales price_.

But in some cases, you might want to create an “RRP”, “set price” or “special offer” instead.
If so, then activate this option (icon:toggle-on[role="green"]).
An additional configuration step will appear. During this step, you’ll specify which type of sales price you want to create.

* *RRP* = A recommended retail price, which only serves to show the price difference between the RRP and a standard sales price. In the online store, the RRP is displayed in red strikethrough text next to the sales price. Products cannot be sold for the recommended retail price.
* *Special offer* = The price for a promotional offer or deal. For example, a special offer that’s only available on Amazon for a limited time.
* *Set price* = <<item/use-cases/combining-products#3000, Sets>> are a way to combine products and sell them as a unit. If you decide to combine products and sell them as a set, then you’ll also need to give the individual set components a set price.

| *Customer classes*
|Should the sales price only apply to specific customer classes? For example, do you want to sell products cheaper to B2B customers than to B2C customers?
If so, then activate this option (icon:toggle-on[role="green"]).
An additional configuration step will appear. During this step, you’ll specify which customer classes the sales price applies to.

*_Frequent source of errors_*: To avoid errors, you should not configure multiple sales prices for the same customer class.
Example: If you create two different sales prices that are both valid for B2B customers, plentymarkets will not know which one to use.

*_Note_*: <<crm/managing-contacts#15, Create the necessary customer classes>> in advance, if they don’t already exist in your plentymarkets system.

| *Quantity-based dependency*
|Should the sales price only apply if a customer buys _multiple copies of the item_?
For example, let’s assume you sell socks for 6 EUR per pair. Do you want the price to be reduced to 5 EUR per pair if a customer buys 3 or more pairs of socks?
If so, then activate this option (icon:toggle-on[role="green"]).
An additional configuration step will appear. During this step, you’ll specify which quantity the sales price applies to.

*_Tip_*: Add _even more_ quantity-based sales prices to create a sliding scale of prices.

2+|Step: Name

| *Internal name*
|Enter a name for the sales price.
This name appears in a variety of different places within your plentymarkets back end. For example, you’ll choose the sales price by name when you <<item/settings/prices#900, link it to individual items>>.

| *External name*
|Enter an external name for the sales price.
Currently, this name is neither displayed in the Ceres store nor in the Callisto store.

2+|Step: Availabilities

| *Currencies*
|Which currencies should the price automatically be converted into?
Select them from the list (icon:check-square[role="blue"]).

*_Background info_*: While configuring your online store, you’ll decide which <<online-store/setting-up-ceres#220, languages>> and <<online-store/setting-up-ceres#201, currencies>> your store should be available in.
For example, let’s assume that customers can choose the currencies EUR, PLN, CHF and GBP from the header.
In this case, it would make sense to have plentymarkets automatically convert your prices from the <<payment/currencies#30, standard currency>>,e.g. EUR, into the other currencies, e.g. PLN, CHF and GBP.

Make sure you’re happy with the <<payment/currencies#20, conversion factors>> saved in the menu *Setup » Orders » Payment » Currencies*.

| *Sales channels*
|Should the sales price only apply to specific distribution channels? For example, do you want to sell the item for a lower price in your online store than on Amazon?
Select all of the platforms (icon:check-square[role="blue"]) that this sales price should apply to.

*_Frequent source of errors_*: To avoid errors, you should not configure multiple sales prices for the same sales channel.
Example: If you create two different sales prices that are both valid for Amazon, plentymarkets will not know which one to use.

*_Note_*: If you choose eBay or Amazon, then an additional configuration step will appear. During this step, you’ll tell plentymarkets which eBay or Amazon account the sales price should apply to.
Therefore, <<markets/ebay/ebay-setup#, link your eBay or Amazon account to plentymarkets>> in advance.

| *Countries of delivery*
|Should the sales price only apply to specific countries of delivery?
For example, you probably pay different tax rates in different countries. As such, you might want to sell an item for a slightly higher price in some countries, rather than pay the difference yourself.
Select all of the countries (icon:check-square[role="blue"]) that this sales price should apply to.

| *Client*
|Should the sales price only apply to specific clients (stores)? If so, then select all of the stores (icon:check-square[role="blue"]) that this sales price should apply to.

*_Background info_*: This setting is only visible if you use plentymarkets to manage multiple online stores, i.e. <<online-store/setting-up-clients#, multiple clients>>.
Since it’s possible to implement several different areas of business with just one plentymarkets system, you always need to tell plentymarkets which online store the sales price applies to.
|====

--

[#400]
==== In the setup menu

Create any number of sales prices to map the entire range of your prices in plentymarkets.
During the process, you’ll give the sales prices names and you’ll decide which currencies, customer classes, marketplaces or other conditions should apply.

[.instruction]
Creating a sales price:

. Go to *Setup » Item » Sales prices*.
. Click on icon:plus[role="green"] *New*. +
→ The *New* tab opens.
. Carry out the settings. Note <<table-create-sales-price>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-create-sales-price]]
.Creating a sales price
[cols="1,3"]
|====
|Setting |Explanation

| *Subscription int.*
|This option is relevant if you offer plugins on plentyMarketplace on a subscription basis.

*_Note_*: This option is neither relevant for the Ceres store nor for the scheduler or subscription module.

| *Position*
|Enter the position number.
If you <<item/settings/prices#900, link multiple sales prices to a variation>>, then you’ll see these sales prices sorted by their position number in the item data record.

| *Internal name EN*
|Enter a name for the sales price.
This name appears in a variety of different places within your plentymarkets back end. For example, you’ll choose the sales price by name when you <<item/settings/prices#900, link it to individual items>>.

| *External name EN*
|Enter an external name for the sales price.
Currently, this name is neither displayed in the Ceres store nor in the Callisto store.

| *Minimum quantity*
|Should the sales price only apply if a customer buys _multiple copies of the item_?
For example, let’s assume you sell socks for 6 EUR per pair. Do you want the price to be reduced to 5 EUR per pair if a customer buys 3 or more pairs of socks?
If so, then enter the quantity that applies to this sales price.

*_Tip_*: Add _even more_ quantity-based sales prices to create a sliding scale of prices.

| *Currency*
|Which currencies should the sales price apply to?
Select them from the list (icon:check-square[role="blue"]).

*_Background info_*: While configuring your online store, you’ll decide which <<online-store/setting-up-ceres#220, languages>> and <<online-store/setting-up-ceres#201, currencies>> your store should be available in.
For example, let’s assume that customers can choose the currencies EUR, PLN, CHF and GBP from the header.
Then it would make sense to also save prices for these currencies.

*_Automatic conversion_*: Activate the option *Live conversion* (icon:check-square[role="blue"]) to have plentymarkets automatically convert your prices from the <<payment/currencies#30, standard currency>>, e.g. EUR, into the other currencies, e.g. PLN, CHF and GBP. +
If you _don’t_ activate this option, then your prices will all have the same number, but different currencies, e.g. 19 EUR and 19 PLN. Therefore, it usually makes sense to have plentymarkets automatically convert the prices.

Make sure you’re happy with the <<payment/currencies#20, conversion factors>> saved in the menu *Setup » Orders » Payment » Currencies*.

| *Price type*
a|Which type of sales price do you want to configure? In most cases, you’ll create a _standard sales price_.

But in some cases, you might want to create an “RRP”, “set price” or “special offer” instead.
If so, then select the corresponding price type (icon:check-square[role="blue"]).

* *RRP* = A recommended retail price, which only serves to show the price difference between the RRP and a standard sales price. In the online store, the RRP is displayed in red strikethrough text next to the sales price. Products cannot be sold for the recommended retail price.
* *Special offer* = The price for a promotional offer or deal. For example, a special offer that’s only available on Amazon for a limited time.
* *Set price* = <<item/use-cases/combining-products#3000, Sets>> are a way to combine products and sell them as a unit. If you decide to combine products and sell them as a set, then you’ll also need to give the individual set components a set price.

| *Display*
|Should this sales price _automatically_ be linked to new item data records?
If so, then activate the option *Always display for new items* (icon:check-square[role="blue"]).

If this setting is deactivated, then you will still be able to <<item/settings/prices#900, manually add the sales price to items>>.

| *Client*
|Should the sales price only apply to specific clients (stores)? If so, then select all of the stores (icon:check-square[role="blue"]) that this sales price should apply to.

*_Background info_*: With plentymarkets, you can manage several online stores, i.e. <<online-store/setting-up-clients#, several clients>>, with only one software. Consequently, it is possible to manage several different areas of business with one plentymarkets system.
That’s a great advantage. But it also means that you’ll always need to tell plentymarkets which online store the sales price applies to.

| *Class*
|Should the sales price only apply to specific customer classes? For example, do you want to sell products cheaper to B2B customers than to B2C customers?
If so, then select all of the customer classes (icon:check-square[role="blue"]) that this sales price should apply to.

*_Frequent source of errors_*: To avoid errors, you should not configure multiple sales prices for the same customer class.
Example: If you create two different sales prices that are both valid for B2B customers, plentymarkets will not know which one to use.

*_Note_*: <<crm/managing-contacts#15, Create the necessary customer classes>> in advance, if they don’t already exist in your plentymarkets system.

| *Country*
|Should the sales price only apply to specific countries of delivery? For example, you probably pay different tax rates in different countries. As such, you might want to sell an item for a slightly higher price in some countries, rather than pay the difference yourself.
Select all of the countries (icon:check-square[role="blue"]) that this sales price should apply to.

| *Referrer*
|Should the sales price only apply to specific distribution channels? For example, do you want to sell the item for a lower price in your online store than on Amazon?
Select all of the platforms (icon:check-square[role="blue"]) that this sales price should apply to.

*_Frequent source of errors_*: To avoid errors, you should not configure multiple sales prices for the same sales channel.
Example: If you create two different sales prices that are both valid for Amazon, plentymarkets will not know which one to use.

*_Note_*: If you select eBay or Amazon, then the corresponding account settings will appear further below. Here you’ll tell plentymarkets which eBay or Amazon account the sales price should apply to.
Therefore, <<markets/ebay/ebay-setup#, link your eBay or Amazon account to plentymarkets>> in advance.

| *Amazon accounts*
|Tell plentymarkets which Amazon account the sales price should apply to.
Therefore, <<markets/amazon/amazon-setup#, link your Amazon account to plentymarkets>> in advance.

This setting is greyed out until you select an Amazon platform from the list above.

| *eBay accounts*
|Tell plentymarkets which eBay account the sales price should apply to.
Therefore, <<markets/ebay/ebay-setup#, link your eBay account to plentymarkets>> in advance.

This setting is greyed out until you select an eBay platform from the list above.
|====

[#500]
=== Editing existing sales prices

As soon as you <<item/settings/prices#200, create a new sales price>>, it is automatically added to the overview in the menu *Setup » Item » Sales prices*.

[#600]
==== Searching for sales prices

Use the filters on the left to limit which sales prices are displayed in the overview on the right.

[.instruction]
Filtering sales prices:

. Go to *Setup » Item » Sales prices*.
. Select the filters on the left. Note <<table-filter-sales-prices>>.
. Click on *Search* (icon:search[role="blue"]). +
→ The filtered sales prices will be displayed in the overview on the right.

[[table-filter-sales-prices]]
.Filtering sales prices
[cols="1,3"]
|====
|Setting |Explanation

| *ID*
|Enter the ID to search for the sales price with this ID.

| *Name*
|Enter the name to search for the sales price with this name.

| *Minimum quantity*
|Enter a quantity value to search for the sales price with this quantity.

| *Client*
|Select a client (store) or *ALL* to search for sales prices for this client.

| *Class*
|Select a customer class or *ALL* to search for sales prices for this class.

| *Referrer*
|Select an order referrer or *ALL* to search for sales prices for this referrer.

| *Amazon accounts*
|Select an Amazon account or *ALL* to search for sales prices for this Amazon account.

| *eBay accounts*
|Select an eBay account or *ALL* to search for sales prices for this eBay account.

| *Currency*
|Select a currency or *ALL* to search for sales prices for this currency.

| *Language*
|Select a language or *ALL* to search for sales prices in this language. *English* is set by default.

| *Country*
|Select a country of delivery or *ALL* to search for sales prices for this country.
|====

[#700]
==== Saving the names in multiple languages

After <<item/settings/prices#200, creating a new sales price>>, you can translate the name of the sales price into the required languages.

[.instruction]
Translating a sales price:

. Go to *Setup » Item » Sales prices*.
. <<item/settings/prices#600, Search for>> and open the sales price.
. Click on the *Language* tab.
. Enter the *internal name* in the required languages.
. Enter the *external name* in the required languages.
. *Save* (icon:save[role="green"]) the settings.

[#800]
==== Advanced settings (not included in the assistant)

<<item/settings/prices#300, The assistant>> guides you through all of the _most common settings_ for sales prices. However, there are also a few advanced settings, which are optional. You might want to configure these settings afterwards.

[.instruction]
Configuring the advanced settings:

. Go to *Setup » Item » Sales prices*.
. <<item/settings/prices#600, Search for>> and open the sales price.
. Configure the advanced settings if needed. Note <<table-sales-price-advanced-settings>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-sales-price-advanced-settings]]
.The following settings are not included in the assistant
[cols="1,3"]
|====
|Setting |Explanation

| *Subscription int.*
|This option is relevant if you offer plugins on plentyMarketplace on a subscription basis.

*_Note_*: This option is neither relevant for the Ceres store nor for the scheduler or subscription module.

| *Position*
|Enter the position number.
If you <<item/settings/prices#900, link multiple sales prices to a variation>>, then you’ll see these sales prices sorted by their position number in the item data record.

| *Display*
|Should this sales price _automatically_ be linked to new item data records?
If so, then activate the option *Always display for new items* (icon:check-square[role="blue"]).

If this setting is deactivated, then you will still be able to <<item/settings/prices#900, manually add the sales price to items>>.
|====

[#900]
=== Linking a sales price with a variation

Sales prices are linked to <<item/introduction/structure#, individual variations>>, rather than to the item as a whole.
For example, if you sell a t-shirt in S, M, L and XL, then you can decide whether the XL variation should be a bit more expensive than the rest.

There are a few different ways to link sales prices to variations and enter the actual monetary prices:

* If you only want to save prices _for a few items_, then it makes sense to <<item/managing-items#240, manually link sales prices and enter monetary amounts>>.
* If you want to save prices _for lots of items_, then we would recommend <<item/import-export-create/import#800, importing the sales prices and monetary amounts>>.
Alternatively, you could also import this data with an <<welcome/assistants#, assistant>>.
* Rather than manually entering the monetary amounts, you might want plentymarkets to <<item/settings/prices#1000, automatically calculate them for you>>.

[#1000]
== Price calculations

You can have plentymarkets automatically calculate your monetary prices for you.
For example, you could start out with the item’s purchase price and then add transportation costs, storage costs and taxes. Finally, you could add a 20% profit margin on top.

This is done with the help of so-called _price calculations_.
First, you’ll <<item/settings/prices#1100, create>> the individual price calculations.
Then you’ll <<item/settings/prices#1200, link>> the price calculations with variations.

[#1100]
=== Creating price calculations

[.instruction]
Creating a price calculation:

. Go to *Setup » Item » Calculation*.
. Click on icon:plus[role="green"] *New price calculation*. +
→ The *New price calculation* window opens.
. Enter a name.
. Click on icon:plus[role="green"] *Add*. +
→ The new price calculation opens.
. Carry out the settings. Note <<table-create-price-calculation>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-create-price-calculation]]
.Creating a price calculation
[cols="1,3"]
|====
|Setting |Explanation

2+|Settings

| *Name*
|Enter a name for the price calculation. The name will be displayed in the *Sales prices* area in the *Settings* tab of an item variation.

| *Price source*
|Select a price which serves as the basis of the price calculation.

| *Transportation costs*
|Activate to add transportation costs to the price source. Enter the transportation costs in the *Costs* area in the *Settings* tab of an item variation.

| *Storage costs*
|Activate to add storage costs to the price source. Enter the storage costs in the *Costs* area in the *Settings* tab of an item variation.

| *Customs*
|Activate to add customs to the price source. Enter the customs rate in the *Costs* area in the *Settings* tab of an item variation. Customs is entered in percent.

| *Operating costs*
|Activate to add operating costs to the price source. Enter the operating costs in the *Costs* area in the *Settings* tab of an item variation. Operating costs are entered in percent.

| *VAT*
|Activate to add the VAT rate to the price source. Select the VAT rate in the *Costs* area in the *Settings* tab of an item variation. The VAT is entered in percent.

2+|Links

| *Add*
|Click on *Add* to create a new link.

| *Target*
|Select a price which serves as the target price of the price calculation.

| *Operator*
|Select the operator. *Plus*, *Minus*, *Plus percentage*, *Minus percentage*, *Multiplied by* and *Divided by* are available.

| *Operand*
|Enter a numerical value.

| *Client (store)*
|This option _only_ relates to <<item/settings/manufacturers#300, manufacturer commissions>>. Select a client (store) to be linked with the price calculation.

| *Referrer*
|This option _only_ relates to <<item/settings/manufacturers#300, manufacturer commissions>>. Select a referrer to be linked with the price calculation.
|====

[#1200]
=== Linking price calculations

There are a few different ways to link price calculations to variations and thus have the monetary prices calculated:

* If you only want to save price calculations _for a few items_, then it makes sense to <<item/managing-items#240, manually link price calculations>>.
* If you want to save prices _for lots of items_, then we would recommend <<data/importing-data/sync-types/elasticSync-item#2300, importing the price calculations>>.
Alternatively, you could use the <<item/import-export-create/create/mass-processing#300, variation group function>> to set up price calculations for multiple item variations at once.
