= Characteristics and properties
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Characteristic, Characteristics, Characteristic group, Characteristic groups, Surcharge, Surcharges, Order characteristic, Order characteristics, Single selection, Multiple selection, Create characteristic, Create characteristics, Characteristic type, Characteristic link, Characteristic value, Characteristic values, Property, Properties, Variation, Variations, Contact, Contacts, Storage location, Storage locations, Create property, Section, Property type, Property group, Edit property, Order property, Deposit, Deposits, Additional costs, Display as additional costs, Selection property, Multiselect, Surcharge type, Attribute, Attributes, Characterise products, Characterise items
:description: Learn how to highlight a product’s technical features.
:url: item/settings/properties
:position: 30
:id: I13JJLO
:author: team-item

////
zuletzt bearbeitet 20.01.2021
////

Some items stand out from the crowd. Be it a watch that is water resistant or a loudspeaker that has Bluetooth technology.
In plentymarkets, such distinguishing features are called characteristics and properties.

With the help of characteristics and properties, for example, you can:

* highlight the technical features of a product (e.g. Bluetooth, Wi-Fi).
* <<item/frontend-item-search#, set up filters in your online store>>. Your customers can then use these filters to refine the search results in the store (e.g. only see speakers that have Bluetooth technology).
* sell <<item/use-cases/personalised-items#, personalised items>>.

[TIP]
.Characteristics, properties and attributes: what’s the difference?
====
* <<item/settings/properties#100, Characteristics>> define _entire items_.
For example, if an item is available in red, blue or green, then the characteristic will apply to all three variations.
Characteristics aren’t very flexible, they’re outdated and they’re gradually being replaced by properties.
//Therefore, we recommend that you already start turning your characteristics into properties.
* <<item/settings/properties#500, Properties>> define _specific variations_.
For example, if an item is available in red, blue or green, then the property can apply to one, two or all three of the variations.
Therefore, properties are much more flexible.
* <<item/settings/attributes#, Attributes>>, for example, are the various colours and sizes that your products are available in.
Attributes help you simultaneously characterise your products and create saleable variations, e.g. a t-shirt in the colour red and the size S.

//lass drin, könnte hilfreich sein als Erklärung Eigenschaft vs Attribute nachdem die Merkmale wegfallen
//Characteristics and properties are _passive features_ of an item. That means they are not linked to stock.
//Attributes, on the other hand, are used to generate saleable variations that can all have different stock levels. For example, the red variation might be sold out but the blue one is still available.
====

////
== Turning characteristics into properties
siehe Kanbanize-Karte für Merkmale -> Eigenschaften Assistenten
////

[#100]
== Characteristics

[.collapseBox]
.*What are characteristics?*
--

Some items stand out from the crowd. Be it a watch that is water resistant or a loudspeaker that has Bluetooth technology.
In plentymarkets, such distinguishing features are called characteristics.

With the help of characteristics, for example, you can:

* highlight the technical features of a product (e.g. Bluetooth, Wi-Fi).
* <<item/frontend-item-search#, set up filters in your online store>>. Your customers can then use these filters to refine the search results in the store (e.g. only see speakers that have Bluetooth technology).
* sell <<item/use-cases/personalised-items#, personalised items>>.

[discrete]
===== Characteristics, properties and attributes: what’s the difference?

* <<item/settings/properties#100, Characteristics>> define _entire items_.
For example, if an item is available in red, blue or green, then the characteristic will apply to all three variations.
Characteristics aren’t very flexible, they’re outdated and they’re gradually being replaced by properties.
//Therefore, we recommend that you already start turning your characteristics into properties.
* <<item/settings/properties#500, Properties>> define _specific variations_.
For example, if an item is available in red, blue or green, then the property can apply to one, two or all three of the variations.
Therefore, properties are much more flexible.
* <<item/settings/attributes#, Attributes>>, for example, are the various colours and sizes that your products are available in.
Attributes help you simultaneously characterise your products and create saleable variations, e.g. a t-shirt in the colour red and the size S.

//lass drin, könnte hilfreich sein als Erklärung Eigenschaft vs Attribute nachdem die Merkmale wegfallen
//Characteristics and properties are _passive features_ of an item. That means they are not linked to stock.
//Attributes, on the other hand, are used to generate saleable variations that can all have different stock levels. For example, the red variation might be sold out but the blue one is still available.
--

[#200]
=== Creating characteristic groups

There are two typical applications for characteristic groups. On the one hand, if you have lots of characteristics, then you can group them together so that it’s easier to keep track of them in your plentymarkets back end.

On the other hand, characteristic groups help you sell <<item/use-cases/personalised-items#, personalised items>> in your online store.
You can use characteristic groups to sort the additional options and services that you offer under one heading.

[TIP]
.Example: Group various trimmings
====
Imagine you sell wedding rings. Your customers can choose an optional gold or diamond trim for an additional fee.
You can create a characteristic group called “Trim” to clearly display these options.
Within this group, customers can choose the options “Gold trim” or “Diamond trim”.
====

[.instruction]
Creating a new characteristic group:

. Go to *Setup » Item » Characteristics*.
. Click on the *New characteristic group* tab.
. Carry out the settings. Note <<table-create-characteristic-groups>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-create-characteristic-groups]]
.Creating a new characteristic group
include::../_textblocks/table/create-characteristic-group.adoc[]

[#300]
=== Creating characteristics

Characteristics allow you to highlight a product’s features.
For example, you might want to specify technical details like Bluetooth or WLAN. Or you might want to offer extra services and options for an additional fee.

[.instruction]
Creating a new characteristic:

. Go to *Setup » Item » Characteristics*.
. Click on the *New characteristic* tab.
. Carry out the settings. Note <<table-create-characteristic>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-create-characteristic]]
.Creating a new characteristic
include::../_textblocks/table/create-characteristic.adoc[]

[#350]
=== Linking characteristics to items

include::../_textblocks/config/link-characteristic-to-item.adoc[]

[#500]
== Properties

This page explains properties that are used to characterise products.
But properties can also be used to characterise <<crm/managing-contacts#950, contacts>> or <<stock-management/setting-up-a-warehouse#850, storage locations>>.
Click on the links to learn more about these other use cases.


[.collapseBox]
.*What are properties?*
--

Some items stand out from the crowd. Be it a watch that is water resistant or a loudspeaker that has Bluetooth technology.
In plentymarkets, such distinguishing features are called properties.

With the help of properties, for example, you can:

* highlight the technical features of a product (e.g. Bluetooth, Wi-Fi).
* <<item/frontend-item-search#, set up filters in your online store>>. Your customers can then use these filters to refine the search results in the store (e.g. only see speakers that have Bluetooth technology).
//* sell <<item/use-cases/personalised-items#, personalised items>>.

[discrete]
===== Characteristics, properties and attributes: what’s the difference?

* <<item/settings/properties#100, Characteristics>> define _entire items_.
For example, if an item is available in red, blue or green, then the characteristic will apply to all three variations.
Characteristics aren’t very flexible, they’re outdated and they’re gradually being replaced by properties.
//Therefore, we recommend that you already start turning your characteristics into properties.
* <<item/settings/properties#500, Properties>> define _specific variations_.
For example, if an item is available in red, blue or green, then the property can apply to one, two or all three of the variations.
Therefore, properties are much more flexible.
* <<item/settings/attributes#, Attributes>>, for example, are the various colours and sizes that your products are available in.
Attributes help you simultaneously characterise your products and create saleable variations, e.g. a t-shirt in the colour red and the size S.

//lass drin, könnte hilfreich sein als Erklärung Eigenschaft vs Attribute nachdem die Merkmale wegfallen
//Characteristics and properties are _passive features_ of an item. That means they are not linked to stock.
//Attributes, on the other hand, are used to generate saleable variations that can all have different stock levels. For example, the red variation might be sold out but the blue one is still available.
--

[#530]
[discrete]
==== General procedure

[.tabs]
====
Standard::
+
--

. <<item/settings/properties#600, Create properties>> like Wi-Fi or Bluetooth.
. <<item/settings/properties#700, Edit the properties further>>.
During this step, you’ll specify e.g. which marketplaces and online stores the property should be visible on.
. <<item/settings/properties#1200, Group the properties>> if needed. This helps you to keep track of the properties in your plentymarkets back end.
. <<item/settings/properties#1400, Link the properties>> to the appropriate variations. For example, link the Bluetooth property to your Bluetooth compliant products.
. <<item/frontend-item-search#, Create webshop filters>>, e.g. if you want customers to be able to search for Bluetooth compliant products in your online store.

--
Catalogues and assistants for Amazon and OTTO::
+
--
Have you already started using the new catalogue tool to transmit your product data to a market like Amazon or OTTO? If so, then you can create properties directly within the catalogue assistant and link them to the marketplace.

Learn more using the <<markets/amazon/variation-data-export#, Amazon catalogue assistant>> as an example.

--
====

////
[#560]
[discrete]
==== Number of properties is limited

in the limits page, either use an include to display the limits for properties or add a comment to remind that it needs to be changed here if the limit changes
How many variation properties you can create and link depends on which plentymarkets rate you’ve booked.
Learn <<more about limits>> and how you can switch to a higher rate if needed.

[cols="1,1,1"]
|====
|Rate |Create ^1^ |Link ^2^

|*Basic / Zero / Advanced*
|500
|???

|*Classic / Partner rate*
|1000
|???

|*Flex*
|1500
|???

|*Plus / Enterprise*
|2000
|???
|====
[.small]#1: Maximum number of properties (“Items” section) that can be created in plentymarkets.# +
[.small]#2: Maximum number of properties that can be linked to one single variation.#


lass drin für später Unterscheidung Attribute vs Eigenschaften
Unlike <<item/settings/attributes#, attributes>>, properties are passive. As such, properties cannot be used to create variations. Properties are not linked to stock and also cannot be selected in the detailed view of an item in the online store.
////

[#600]
=== Creating new properties

First, create the properties that you’ll use to characterise your products, e.g. Bluetooth or Wi-Fi.
Properties can be created manually, imported or created with the help of a catalogue assistant.

You can create up to 500 variation properties and link them to variations.

[#620]
==== Manual creation

. Go to *Setup » Settings » Properties » Configuration*. +
→ You will see an overview of the previously created properties.
. Click on *Add property* (icon:plus[role="green"]).
. In the drop-down list *Section*, select the option *Items*.
. Carry out the additional settings. Note <<table-create-variation-property>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The property is created and opened for <<item/settings/properties#700, further editing>>.

[[table-create-variation-property]]
.Creating properties
[cols="1,4a"]
|======
|Setting |Explanation

| *Section*
a|What do you want to use the property for? Choose the appropriate section from the drop-down list.

* *Items* = Property will be used for items.
* *Contact* = Property will be used for contacts.
* *Storage location* = Property will be used for storage locations.
//* *Stock* = Property is used for warehouse management.

*_Note_*: This setting can no longer be changed once you’ve created the property.

| *Property type*
|What sort of property do you want to create? Choose this property type from the drop-down list.

*_Note_*: This setting can no longer be changed once you’ve created the property.

[cols="1,4a"]
!======
!Type !What is the type useful for?

! *None*
!The property’s name can be displayed in the online store.
This is useful, e.g. to:

* highlight the technical features of a variation (Bluetooth, Wi-Fi).
* create online store filters (only include Bluetooth-capable products in the search results)
//* <<item/settings/properties#intable-order-characteristic, As an order characteristic>>: appropriate e.g. for offering customers <<item/use-cases/personalised-items#200, additional options and services>> while they place their orders.

! *Date*
!A date can be displayed in the online store.

! *File*
!A file can be made available for the variation, e.g. assembly instructions.

//<<item/settings/properties#intable-order-characteristic, As an order characteristic>>: allows customers, e.g. to <<item/use-cases/personalised-items#100, upload an image>> that should be printed on a t-shirt.


! *Int*
!A whole number can be displayed in the online store.

* Appropriate e.g. for specifying a weight or a length. For example, HDMI cables that are longer than 10m.

! *Float*
!A number with decimal places can be displayed in the online store.

* Appropriate e.g. for displaying measurements in the online store. For example, a pitcher that holds 1.4 litres.

! *Long text*
!A text with formatting can be displayed in the online store.

* Appropriate e.g. for creating variation-specific product descriptions.

//<<item/settings/properties#intable-order-characteristic, As an order characteristic>>: allows customers, e.g. to <<item/use-cases/personalised-items#100, enter a personal text>> that should be printed on a t-shirt.

! *Short text*
!A text without formatting can be displayed in the online store.

* Appropriate e.g. for creating variation-specific product descriptions.

! *Selection*
!Creates a drop-down list with possible values.
While linking the property to a variation, you’ll specify which one of the values applies to the variation.

//You can enter up to 65,535 characters for each option and value.


*_Example of use_*:

. <<item/settings/properties#760, First>> you’ll create various levels of water resistance.
. <<item/settings/properties#1400, Second>> you’ll specify the water resistance level for each variation.
. <<item/frontend-item-search#, Third>> you’ll create online store filters, which allow your customers to search for variations with a specific water resistance level.

! *Multi selection*
!Creates a series of checkboxes.
While linking the property to a variation, you’ll check all of the values that apply.

*_Example of use_*:

. <<item/settings/properties#760, First>> you’ll create various features. For example, if you sell books: first edition, author signature, rarity, collector’s edition.
. <<item/settings/properties#1400, Second>> you’ll check all of the features that apply to the variation, e.g. a first edition that’s also signed.
. <<item/frontend-item-search#, Third>> you’ll create online store filters, which allow your customers to search for variations with such features.
!======

| *Name*
|Enter a name for the property in your plentymarkets system’s default language. This name <<item/settings/properties#1500, can be made visible to customers>> in the online store. It depends on how you design the layout with ShopBuilder.

*_Note_*: Once you’ve created the property, you can save the name in further languages.

| *Description* +
(Currently not in use)
|In the future, this option will allow you to display a description of the order property in the online store.
But at the moment, it’s only possible to use order characteristics.

| *Group*
|Should this property be sorted into a specific <<item/settings/properties#1200, group>>? If so, then select the group here.

*_Note_*: This drop-down list only includes property groups that were already created.
Proceed as follows to create a new group:

. Click on *Add property group* (icon:plus[role="green"]).
. Configure the <<item/settings/properties#1200, settings for the group>>. +
→ Once you’ve saved the group, you will automatically be taken back to this menu and the group will be pre-selected here.

*_Note_*: It would take a lot of time to manually select a group for every property.
Instead, use the group function to <<item/settings/properties#1300, add several properties to a group at once>>.

| *Position*
|Which property should be displayed first, second, third, etc? Enter a position number into this field. If a variation has multiple properties, then the properties will be displayed in the store in ascending order according to their position number.
|======

[#640]
==== Import

plentymarkets has an <<data/importing-data/ElasticSync#, import tool>>, which you can use to import properties.
The idea is simple.
Rather than manually saving property data in plentymarkets, you’ll enter the same information into a CSV file and then import this file into your system.

Use the *Properties* import type. The fields that you can use for mapping and matching are described on the page of the manual of the import type <<data/importing-data/sync-types/elasticSync-properties#, Properties>>.

[#660]
==== Catalogue

Have you already started using the new catalogue tool to transmit your product data to a market like Amazon or OTTO? If so, then you can create properties directly within the catalogue assistant and link them to the marketplace.

Learn more using the <<markets/amazon/variation-data-export#, Amazon catalogue assistant>> as an example.

[#800]
=== Searching for existing properties

Previously created properties are displayed in an overview.
You can use filters to narrow down the search results and only see the properties that meet specific criteria.
You can combine as many search filters as you like.

[.instruction]
Searching for properties:

. Go to *Setup » Settings » Properties » Configuration*.
. In the *Filter* view, enter the search term in the search field or set the filter options in the drop-down lists. Note <<table-filter-variation-properties>>.
. Click on *Search* (icon:search[role="blue"]). +
→ The properties that correspond to the search criteria entered are displayed.
. Click in the line of the property. +
→ The detail view of the property opens.

[[table-filter-variation-properties]]
.Filters for the properties
[cols="1,4"]
|====
|Setting |Explanation

| icon:search[role="blue"]
|Starts the search. The properties found are listed in the overview.

*_Tip_*: Don’t choose any filters if you want to see all of the properties in the overview.

| icon:undo[role="orange"]
|Resets the selected filter criteria.

| *ID*
|Enter an ID to search for the property with this exact ID.

*_Background info_*: Each property automatically receives a consecutive and unique ID when it is created.

| *Name*
|Enter a name to search for properties with this name.
It’s also possible to search for parts of the name.

*_Example_*: By entering “start”, you would find properties called “starting date” and “starter pack”.

| *Language*
|Select a language to search for properties that have a name saved in this language.

| *Group*
a|Select a group to search for properties that are part of this group. +

* *Ungrouped* = The search results include properties that are not assigned to any group.
* *Grouped* = The search results include properties that are assigned to a group.

*_Note_*: This list only includes groups that have already been created. If you haven’t created any <<item/settings/properties#1200, property groups>> yet, then you won’t see any group names here either.

| *Section*
|Select a section to search for properties that are used for this section.

| *Property type*
|Select a property type to search for properties with this type.
|====

[#700]
=== Editing existing properties

Once you’ve created a property, you can edit its settings further.

[.instruction]
Editing a property:

. Go to *Setup » Settings » Properties » Configuration*.
. <<item/settings/properties#800, Search for>> and open the appropriate property.
. Edit the settings that are relevant for your situation.
. *Save* (icon:save[role="green"]) the settings.

[#720]
[discrete]
==== General

[[table-edit-variation-property-general]]
.Properties » Configuration » General
[cols="1,3"]
|====
|Setting |Explanation

2+| *Details*

| *ID*
|Each property automatically receives a consecutive and unique ID when it is created.
This ID cannot be changed.

| *Section*
|The section that you chose while creating the property.
This setting can no longer be changed.

| *Property type*
|The type that you chose while creating the property.
This setting can no longer be changed.

| *Position*
|Which property should be displayed first, second, third, etc? Enter a position number into this field. If a variation has multiple properties, then the properties will be displayed in the store in ascending order according to their position number.

2+| *Options*

| *Units*
|Is the property something like a weight or a length, e.g. HDMI cables that are longer than 10m? If so, then choose the appropriate <<item/settings/units#, unit>>.

| *Order property* +
(Currently not in use)
a|In the future, this option will allow you to create _order properties_.
But at the moment, it’s only possible to use _order characteristics_.

In other words, currently it’s only possible to <<item/use-cases/personalised-items#, sell personalised items>>, rather than personalised variations. But our developers are working hard on a solution: order properties. Once they are released, it will be possible to sell personalised variations.

//Select this option (icon:check-square[role="blue"]) if customers should be allowed to <<item/use-cases/personalised-items#, personalise their orders>>. For example:

//* by entering a personal text that should be engraved.
//* by choosing optional services for an additional fee.

//How exactly customers can personalise their orders depends on which <<property type>> you selected.


| *Display as additional costs* +
(Currently not in use)
|In the future, this option will allow you e.g. to display deposit amounts.
In other words, this option specifies that no VAT should be added to a surcharge.

At the moment, it’s only possible to implement such surcharges with <<item/settings/properties#300, characteristics>>.

//|[#intable-pricecalc]*Price calculation property*
//|Properties of the type "Int" or "Float" can be used in <<item/settings/prices#1000, price calculations>>.
//Select this option (icon:check-square[role="blue"]) if you are creating a property of the type "Int" or "Float" and you want it to be available in price calculations.

2+| *Name*

| *Language*
|Is your store available in multiple languages? Then choose a language version from the drop-down list.

| *Name*
|Enter a name for the property in the selected language.
This name <<item/settings/properties#1500, can be made visible to customers>> in the online store. It depends on how you design the layout with ShopBuilder.

| *Description* +
(Currently not in use)
|In the future, this option will allow you to display a description of the order property in the online store.
But at the moment, it’s only possible to use order characteristics.

//Enter a description of the property in the selected language.
//sichtbar im Webshop je nachdem wie man ShopBuilder konfiguriert?
//The description will be displayed if you place the cursor on the characteristic.

2+| *Group*

| *Group*
|Should this property be sorted into a specific <<item/settings/properties#1200, group>>? If so, then select the group here.

*_Note_*: This drop-down list only includes <<item/settings/properties#1200, property groups that were already created>>.

*_Note_*: It would take a lot of time to manually select a group for every property.
Instead, use the group function to <<item/settings/properties#1300, add several properties to a group at once>>.
|====

[#740]
[discrete]
==== Visibility

[[table-edit-variation-property-visibility]]
.Properties » Configuration » Visibility
[cols="1,3"]
|====
|Setting |Explanation

| *Referrers*
|Which sales platforms should the property be visible on?
Select (icon:check-square[role="blue"]) one or more referrers.

*_Note_*: The drop-down list only includes active referrers.
So if you can’t find a specific market in the list, then open the menu *Setup » Orders » Order referrer* and make sure the market was activated (icon:check-square[role="blue"]).

| *Clients*
|Should the property only apply to specific clients (stores)? If so, then select all of the stores (icon:check-square[role="blue"]) that this property should apply to.

*_Background info_*: With plentymarkets, you can manage several online stores, i.e. <<online-store/setting-up-clients#, several clients>>, with only one software. Consequently, it is possible to manage several different areas of business with one plentymarkets system. That’s a great advantage. But it also means that you’ll always need to tell plentymarkets which online store the property applies to.

| *Display everywhere*
|Where should the property be displayed? Choose the areas (icon:check-square[role="blue"]) where your customers should see the property.
|====

[#760]
[discrete]
==== Values

[IMPORTANT]
.Not visible for every type of property
====
You will only see this area if you are working with a property of the type *Selection* or *Multi selection*.
This area is irrelevant for all of the other property types.
====

Here you’ll define the individual values that can be selected.

. Click on *Add value* (icon:plus[role="green"]).
. Is your store available in multiple languages? Then choose a language version from the drop-down list.
. Enter a name and description for the value in the selected language.
. *Save* (icon:save[role="green"]) the settings. +
→ The value is created and displayed in the overview.
The value automatically receives a consecutive and unique ID that cannot be changed.

[#780]
[discrete]
==== Amazon

Here you can <<markets/amazon/preparing-variations#1390, link the property with Amazon fields>> if needed.
To do so, it is necessary to activate an Amazon referrer in the *Visibility* tab.

. Click on *Add correlation* (icon:plus[role="green"]).
. Use the three drop-down lists to select the appropriate Amazon platform, category and field.
. Repeat the procedure if you want to link additional Amazon fields.
. *Save* (icon:save[role="green"]) the settings. +
→ The property is linked with the Amazon field and exported during the next item export.

[#1200]
=== Grouping properties

If you have lots of properties, then you can group them together so that it’s easier to keep track of them in your plentymarkets back end.

[TIP]
.Example: grouping sales channels
====
Imagine you use some properties for the market Amazon and others for your online store.
In this case, you could create one group called Amazon and another group called Store.
====

////
diese Einleitung erst anzeigen nachdem Bestelleigenschaften veröffentlicht wurden

There are two typical applications for property groups. On the one hand, if you have lots of properties, then you can group them together so that it’s easier to keep track of them in your plentymarkets back end.

On the other hand, property groups help you sell <<item/use-cases/personalised-items#, personalised items>> in your online store.
You can use property groups to sort the additional options and services that you offer under one heading.

[TIP]
.Example: Group various trimmings
====
Imagine you sell wedding rings. Your customers can choose an optional gold or diamond trim for an additional fee.
You can create a property group called “Trim” to clearly display these options.
Within this group, customers can choose the options “Gold trim” or “Diamond trim”.
====
////

[#1250]
==== Creating groups

[.instruction]
Creating a new property group:

. Go to *Setup » Settings » Properties » Groups*.
. Click on *Add property group* (icon:plus[role="green"]).
. Carry out the settings. Note <<table-create-variation-property-group>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The group is created and displayed in the overview.
The group automatically receives a consecutive and unique ID that cannot be changed.

[[table-create-variation-property-group]]
.Creating a new property group
[cols="1,3"]
|====
|Setting |Explanation

| *Name*
|Enter a name for the property group in your plentymarkets system’s default language.
This name <<item/settings/properties#1500, can be made visible to customers>> in the online store. It depends on how you design the layout with ShopBuilder.

*_Note_*: Once you’ve created the property group, you can save the name in further languages.

| *Description* +
(Currently not in use)
|In the future, this option will allow you to display a description of the order property group in the online store.
But at the moment, it’s only possible to use order characteristic groups.

//Enter a description of the property group in your plentymarkets system’s default language.
//*_Note_*: Once you’ve created the property group, you can save the description in further languages.
//sichtbar im Webshop je nachdem wie man ShopBuilder konfiguriert?
//The description will be displayed if you place the cursor on the characteristic.

| *Position*
|Which property group should be displayed first, second, third, etc? Enter a position number into this field.
If a variation has properties from multiple groups, then the groups will be displayed in the store in ascending order according to their position number.

| *Group type* +
(Currently not in use)
a|How many additional options or services should your customers be able to choose from the group?

* *None* = Your customers will see the order properties in the online store. However, they will not be able to choose anything.
* *Select* = Your customers will see a drop-down list in the online store. They will be able to select one option only from the list.
* *Multiselect* = Your customers will see check boxes in the online store. They will be able to select multiple options.

*_Note_*: This option only applies to order properties of the type *None*.

| *Surcharge type*
|Do you plan on offering extra services or options for an additional fee? If so, then decide whether the surcharge should be treated as a percentage or as a fixed price, e.g. 5% or 5 EUR.
|====

[#1300]
==== Assigning properties to a group

plentymarkets includes a function, which you can use to simultaneously assign multiple properties to a group.

[.instruction]
Assigning properties to a group:

. Go to *Setup » Settings » Properties » Configuration*.
. Select the properties (icon:check-square[role="blue"]) that you want to assign to the group.
. Click on *Assign property group* (icon:settings_transfer[set=plenty]). +
→ The property groups will appear.
. Select one or more property groups (icon:check-square[role="blue"]).
. Click on icon:execute[set=plenty] *Group function*. +
→ The selected properties will be assigned to the groups.

[#1350]
==== Deleting groups again

Previously created groups are displayed in the menu *Setup » Settings » Properties » Groups*.
Groups can also be deleted here.

. Select the groups (icon:check-square[role="blue"]) that you want to delete.
. Click on icon:minus-circle[role="red"] *Delete groups* in the upper right corner.
. Confirm your decision.

Properties that are assigned to groups remain unaffected.

[#1400]
=== Linking properties with variations

[IMPORTANT]
.Properties are linked in a different tab depending on their type
====
In the lower row of tabs, click on the tab *Properties* or *Texts*. Which tab depends on the property type.
====

[cols="1,2", width=100%]
|====
|Property type |Where is the property linked?

|Short text +
Long text
|<<item/managing-items#5000, Tab: Texts>>

|None +
Int +
Float +
Selection +
Multi-selection +
Date +
File
|<<item/managing-items#4800, Tab: Properties>>
|====

[#1420]
==== Manual link

. Go to *Item » Edit item*.
. <<item/introduction/search#400, Search for>> and open the variation.
. In the lower row of tabs, click on the tab *Properties* or *Texts*.
Which tab depends on the property type.
. Click on the *Properties* field. +
→ A drop-down list of available variation properties opens.
. Select the appropriate properties (icon:check-square[role="blue"]).
. Click on Add (icon:plus[role="green"]). +
→ The properties will be added.
. If necessary, add additional information about the property.
. *Save* (icon:save[role="green"]) the settings. +

//check this to make sure it's true
[TIP]
.Inheritance
======
By default, properties and values are passed from the main variation to the sub-variations.
If you want to use other properties for the sub-variations, then deactivate the inheritance function and then link the property.

Properties and values are inherited all together. You can inherit either all or none of the values.
======

[#1440]
[discrete]
===== Saving additional information

Depending on the scenario, it might be necessary to save additional information. For example:

* If the property is something like a weight or a length, then it will be necessary to enter a numeric value.
* If the property is a product description for a specific variation, then the text will need to be entered.

[cols="1,4a"]
|======
|Setting |Explanation

2+| *Tab: Properties*

| *Name*
|Here you’ll see the property name. This is purely informative and cannot be changed here.

| *Type*
|Here you’ll see the property type. This is purely informative and cannot be changed here.

[cols="1,1a"]
!======
!Appearance !Meaning

! *empty*
!None

! *int*
!Int

! *float*
!Float

! *selection*
!Selection

! *multiSelection*
!Multi selection

! *date*
!Date

! *file*
!File

!======

*_Note_*: How you will interact with the *Value* column depends on the property type.

| *Value*
|How you interact with this column depends on the property type.

[cols="1,4a"]
!======
!Type !Interaction

! *empty*
!No further action is necessary.

! *int*
!Enter the numerical value as a whole number, e.g. 350 centimetres.

Whole numbers between -2,147,483,648 and 2,147,483,647 are permitted.


! *float*
!Enter the numerical value as a decimal number, e.g. 3.5 metres.

8 places before and 4 places after the decimal point are permitted.

! *selection*
!Select the appropriate option from the drop-down list.

! *multiSelection*
!Check all of the appropriate options.

! *date*
!Click on the entry field and select the date from the calendar. Or manually enter the date in the following format: DD.MM.YY

! *file*
!Click on icon:upload[set=plenty, role=purple] *Upload files* and upload the appropriate file.
!======

| *Procedures*
|Click on *Delete* (icon:minus-circle[role="red"]) to delete the property link. The property itself will not be deleted. It will simply be removed from the variation.

*_Inheritance logic_*: The following logic applies when you delete a property link:
//test this to make sure it's true

* Are you removing the property from a _main variation_? Then the property will also be removed from all of the sub-variations that had previously inherited this property.
* Are you removing the property from a _sub-variation_ for which the inheritance function was activated? Then the inheritance function will be deactivated. The remaining properties will no longer be inherited. Rather, they will be saved directly for the sub-variation.

//* If you delete the property link of a _main variation_, the link and value are deleted for all variations of the item that inherit the properties of the main variation.

//If you delete the property link of a variation for which inheritance is active, inheritance is deactivated and the remaining properties are saved for this variation. +


2+| *Tab: Texts*

| *Short text*
|Enter up to 65,535 characters of plain text.

*_Note_*: Your plentymarkets system’s default language is pre-selected.
If you want to save the text in a different language, then choose this language from the drop-down list up top.

| *Text*
|Enter up to 65,535 characters of text.
Format the text as needed.
Choose your preferred editor from the drop-down list in the top right corner.

*_Note_*: Your plentymarkets system’s default language is pre-selected.
If you want to save the text in a different language, then choose this language from the drop-down list up top.

| *Procedures*
|Click on *Delete* (icon:minus-circle[role="red"]) to delete the property link. The property itself will not be deleted. It will simply be removed from the variation.

*_Inheritance logic_*: The following logic applies when you delete a property link:

//test this to make sure it's true

* Are you removing the property from a _main variation_? Then the property will also be removed from all of the sub-variations that had previously inherited this property.
* Are you removing the property from a _sub-variation_ for which the inheritance function was activated? Then the inheritance function will be deactivated. The remaining properties will no longer be inherited. Rather, they will be saved directly for the sub-variation.

//* If you delete the property link of a _main variation_, the link and value are deleted for all variations of the item that inherit the properties of the main variation.

//If you delete the property link of a variation for which inheritance is active, inheritance is deactivated and the remaining properties are saved for this variation. +
|======

[#1460]
==== Importing links

plentymarkets has an <<data/importing-data/ElasticSync#, import tool>>, which you can use to import property links. The idea is simple. Rather than manually linking properties with variations, you’ll enter the same information into a CSV file and then import this file into your system.

Use the *Item* import type and the mapping fields under the heading <<data/importing-data/sync-types/elasticSync-item#2410, Properties>>.

[#1500]
=== Displaying properties in the online store

How your properties are displayed in the <<online-store/setting-up-ceres#, Ceres store>> depends on how you configured the settings with <<online-store/shop-builder#, ShopBuilder>>. This video provides a short demonstration (German only).

.Displaying properties in the Ceres store
video::360260315#t=24m18s[vimeo]

[#1600]
=== Exporting properties

Do you want to export property information out of your plentymarkets system? This is done in two steps:

* First you’ll use the <<data/exporting-data/FormatDesigner#, FormatDesigner>> to create a so-called data format.
** Use the format type <<data/exporting-data/FormatDesigner/format-types/properties#, Properties>> if you want to export the actual properties and property groups.
** Use the format type *item* along with the data fields <<data/exporting-data/FormatDesigner/format-types/item#1600, VariationEigenschaften>> if you want to export the links between properties and variations.
* In a second step, you’ll use the <<data/exporting-data/elastic-export#, Elastic Export>> tool to export the data format that you just created.

[#900]
=== Deleting properties

Previous created properties are displayed in the menu *Setup » Settings » Properties » Configuration*.
Properties can also be deleted here.

. Select the properties (icon:check-square[role="blue"]) that you want to delete.
. Click on icon:minus-circle[role="red"] *Delete* in the upper right corner.
. Confirm your decision. +
→ The selected properties are deleted and removed from the overview.

[IMPORTANT]
.Even properties that are currently linked to variations can be deleted
====
It’s possible to delete properties, regardless whether they are currently linked to a variation or not.
So think carefully before you delete properties. Make sure that you no longer need the property for any variations.
====
