= Characteristics and properties
:lang: en
include::{includedir}/_header.adoc[]
:description: Learn how to highlight a product’s technical features.
:url: item/settings/properties
:icons: font
:position: 40
:docinfodir: /workspace/manual-adoc
:docinfo1:

Some items stand out from the crowd. Be it a watch that is water resistant or a loudspeaker that has Bluetooth technology.

In plentymarkets, such distinguishing features are called characteristics and properties. Characteristics and properties help you highlight a product’s technical features. The difference is that <<item/settings/properties#500, properties>> define _specific variations_ whereas <<item/settings/properties#100, characteristics>> define _entire items_.

[TIP]
.Other ways to characterise products
====
Do you want to simultaneously characterise your products and create <<item/introduction/structure#, saleable variations>>, e.g. a t-shirt in the colour red and the size S? This can be done with the help of <<item/settings/attributes#, attributes>>!
====

[#100]
== Characteristics

Characteristics are the distinguishing features of an item. Unlike <<item/settings/attributes#, attributes>>, characteristics are passive. As such, characteristics are not required to create variations. Besides, characteristics cannot be selected in the detailed view of an item in the online store. With characteristics, you can highlight features of items, for example technical details such as Bluetooth or Wi-Fi, etc.

Characteristics are passive and are not connected to stock. By using order characteristics, you can provide services for an additional charge or integrate a text field for a customer's additional requests. When setting up the characteristics search, you can use characteristics to provide your customers with a more specific search. Characteristics also allow you to link your items with the characteristics for variations of a market.

[TIP]
.What’s the difference between characteristics and properties?
====
Characteristics are linked to items. As such, they apply to all variations of the item. Characteristics are out of date and will gradually be replaced by <<item/settings/properties#500, properties>>. Properties are linked to variations. As such, they are much more flexible.
====

[#200]
=== Creating characteristic groups

Create characteristic groups to sort your characteristics into groups. If you need a large number of characteristics, then use groups to keep track of them all. When linking items with characteristics, the characteristics will be displayed in the assigned characteristic groups.

[.instruction]
Creating a new characteristic group:

. Go to *Setup » Item » Characteristics*.
. Click on the *New characteristic group* tab.
. Carry out the settings. Note <<table-create-characteristic-groups>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-create-characteristic-groups]]
.Creating a new characteristic group
[cols="1,2"]
|====
|Setting |Explanation

|*Name*
|Enter a name for the characteristic group. The name will be displayed in the *Characteristic groups* tab in this menu and in the item's *Characteristics* tab.

|*Language*
|Select a language.

|*Language: Name*
|Enter the name in the selected language. The name is displayed in the online store.

|*Language: Description*
|Enter a description in the selected language.

|*Surcharges*
|*Flat rate* or *in percent*. This setting is used for calculating surcharges.

|*Grouping of order characteristics (type: "none")*
a|This option can only be used for order characteristics of the type *none*. How should the order characteristics be grouped?

* *None* = Order characteristics are not grouped by default.
* *Single selection* = One of the grouped order characteristics can be selected from the drop-down list.
* *Multiple selection* = Multiple order characteristics can be selected. +

|*OTTO characteristic group*
a|If needed, link a characteristic group to OTTO. All of the characteristics in this group will be transferred to OTTO. All of the characteristics will be grouped into a SellingPoint.

* *None* = No link to OTTO.
* *SellingPoint with group names* = Link to OTTO. The name of the group will be transferred.
* *SellingPoint without group names* = Link to OTTO. The name of the group will not be transferred.
|====

[#300]
=== Creating characteristics

Create characteristics to link your items with passive characteristics.

[.instruction]
Creating a new characteristic:

. Go to *Setup » Item » Characteristics*.
. Click on the *New characteristic* tab.
. Carry out the settings. Note <<table-create-characteristic>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-create-characteristic]]
.Creating a new characteristic
[cols="1,2"]
|====
|Setting |Explanation

|*Name (internal)*
|Enter an internal name for the characteristic. The internal name is displayed in the *Characteristics* tab of an item.

|*Online store: Language*
|Select the language in which the characteristic is displayed in the online store.

|*Online store: Name*
|Enter a name for the characteristic. The name is displayed in the detailed view of an item in the online store.

|*Online store: Description*
|Enter a description for the characteristic. The description will be displayed if you place the cursor on the characteristic.

|*Unit*
|Select a <<item/settings/units#, unit>>.

|*Characteristic group*
|Select a <<item/settings/properties#200, characteristic group>>.

|*Characteristic type*
a|Select the characteristic type. Once a characteristic has been linked to one or more items, it is no longer possible to change the characteristic type.

* *No* = Do not select a characteristic type.
* *Whole number* = Allows you to enter a whole number between -2,147,483,648 and 2,147,483,647 into the item’s *Characteristics* tab. For example, the number could be a size.
* *Decimal number* = Allows you to enter a number with decimal places in the item's *Characteristics* tab, for example a measurement.
* *Text* = Allows you to enter text in the item's *Characteristics* tab.
* *Selection* = Additional options will be displayed.

. Enter a name and description for the first selection that you wish to be displayed as a characteristic, for example version 1.0.
. Save.
. Scroll down in the window and enter another name, for example version 2.0.
. *_Optional:_* Repeat the process. +
→ Every time you save your entry, a new empty field for further selection will be created.

* *File* = Allows you to upload a file in the item's *Characteristics* tab.

|*Surcharge*
a|Enter a value if a surcharge is to be added for the characteristic. Surcharges will automatically be added to the item price in the detailed view of an item and in the order process. The value *0.00* is set by default, i.e. no surcharge will be calculated.

* *Display as additional costs* = VAT will not be taken into account for the entered surcharge. One possible use for this option is to set up a bottle deposit which is added to the item price without calculating VAT. Characteristics that have this option selected will be displayed as separate items on invoices etc. These items will be displayed with the *ID -2*.

|*Position*
|Enter the position number. Characteristics can be sorted by their position numbers.

|*Searchable*
|Activate to search for items with this characteristic when entering the characteristic as the search term.

|*Show*
a|Activate options.

* *Show on the item's page in the online store* = The characteristic will be displayed on the product page.
* *Show in the item listing in the online store* = The characteristic will be displayed in the item list.
* *Display in order process* = The characteristic will be displayed in the order process.
* *Show in PDF documents* = The characteristic will be displayed in PDF documents.

|*Order characteristic*
|Activate to make the characteristic available in the order process. Depending on the *characteristic type*, the customer can for example enter a text or value or select an option from a drop-down list.

|*Note*
|Enter a note, for example to display specific information about the characteristic.

|Characteristic links for markets and price comparison portals
|Select the marketplace characteristic from the drop-down list. This links the characteristic with a <<markets/amazon/amazon-setup#1400, characteristic on a marketplace like Amazon>>.
|====

<<item/managing-items#80, Link any number of characteristics with an item>>. Customers can search for characteristics in the online store by using the linked characteristics.

[#400]
=== Changing characteristic values via group function

The *group function* allows you to edit the characteristic values for all items linked with this characteristic value at once.

[.instruction]
Changing a characteristic's value with a group function:

. Go to *Setup » Item » Characteristics*.
. Click on the *Group function* tab.
. Select the characteristic's language.
. Select the characteristic from the *Characteristic selection* drop-down list for which you want to change a value.
. Enter the old value into the *Value to be changed* field.
. Enter the *new value*.
. *Save* (icon:save[role="green"]) the settings. +
→ The characteristic value is changed for all items with this value.

[#500]
== Properties

Properties help you highlight items, contacts or storage locations. For example, you can use properties to:

* highlight a variation’s technical features such as Bluetooth or WLAN
* specify which storage locations are appropriate for <<item/settings/properties#550, items requiring refrigeration>>
* display text fields that customers can write additional requests in

Properties are <<item/settings/properties#600, created centrally>> in the menu *Setup » Settings » Properties » Configuration* and then they are linked to <<item/managing-items#4800, variations>>, <<crm/managing-contacts#, contacts>> or <<stock-management/setting-up-a-warehouse#500, storage locations>>.

Properties that are assigned to the *Item* section are linked to variations. These properties differ from <<item/settings/properties#100, characteristics>>, which are linked to items. You can create up to 500 variation properties and link them to variations.

Unlike <<item/settings/attributes#, attributes>>, properties are passive. As such, properties cannot be used to create variations. Properties are not linked to stock and also cannot be selected in the detailed view of an item in the online store.

You can also use properties to link your variations with the <<markets/amazon/amazon-setup#1390, properties used on markets like Amazon>>. Furthermore, your customers can <<item/frontend-item-search#, search for properties in the online store>> and find variations linked to this property.

[#550]
[TIP]
.Practical example: Storing items in the right spot
====
Do you have items that need to be stored in a specific place? For example, some food items should _only_ be stored in refrigerators or freezers. Characterise your storage locations and make sure your items always end up in the right spot.

What you’ll need to do:

* <<item/settings/properties#600, Create a property>> and assign it to the section *Storage location*.
* Link the property to all of the <<item/managing-items#4900, appropriate items>>, e.g. with perishable goods.
* Link the property to all of the <<stock-management/setting-up-a-warehouse#500, appropriate storage locations>>, e.g. with refrigerators and freezers.
* <<stock-management/new-incoming-items#450, When receiving items>>, you’ll automatically be suggested the appropriate storage location for the item.
====

[#600]
=== Creating a property

Go to *Setup » Settings » Properties » Configuration* to create properties. These properties are used for characterising your items. Proceed as described below to create a property.

[.instruction]
Creating a property:

. Go to *Setup » Settings » Properties » Configuration*. +
→ The overview of the properties opens.
. Click on *Add property*.
. In the drop-down list *Section*, select the option *Items*.
. Carry out the additional settings. Note <<table-create-variation-property>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The property is created and opened for editing.

[[table-create-variation-property]]
.Creating properties
[cols="1,3"]
|====
|Setting |Explanation

|*Section*
a|Select a section from the drop-down list where the property should be used.

* *Items* = Property will be used for items.
* *Contact* = Property will be used for contacts.
* *Storage location* = Property will be used for storage locations.
//* *Stock* = Property will be used for stock management.

|*Property type*
a|Select the property type from the drop-down list.

* *None* = No property type
* *Whole number* = Makes it possible to enter a whole number between -2,147,483,648 and 2,147,483,647.
* *Decimal number* = Makes it possible to enter a number with decimal places.
* *Selection* = Makes it possible to select multiple options. You can enter up to 65,535 characters for each option and value.
* *Short text* = Makes it possible to enter a text that is not formatted and is a maximum of 65,535 characters.
* *Text* = Makes it possible to enter and format a text with up to 65,535 characters.
* *Date* = Makes it possible to enter a date.
* *File* = Makes it possible to upload a file.

|*Name*
|Enter a name for the property. This name will for example be displayed in the order process. +
*_Note:_* The name of the system language is displayed by default. After the property has been created, you can save the name in English. Further languages are planned.

|*Description*
|Enter a description of the property. +
*_Note:_* The description of the system language is displayed by default. After the property has been created, you can save the description in English. Further languages are planned.

|*Group*
|Select a property group from the drop-down list to assign the property to this group. This is optional. +
*_Tip:_* Click on *Add property group* to create a group.

|*Position*
|Enter the position number for the property. Properties are sorted by the position number in ascending order. +
*_Tip:_* Count by tens when creating position numbers. This will allow you to easily add new properties in between.
|====

[#700]
=== Editing a property

You can find properties in the menu *Setup » Settings » Properties » Configuration*. You can modify the settings described in <<table-create-variation-property>>.

[.instruction]
Editing a property:

. Go to *Setup » Settings » Properties » Configuration*.
. Click on *Search* to see all properties. +
*_Tip:_* Select filters to limit the search results.
. Click on the property. +
→ The *General* tab opens.
. Edit the settings. Note <<table-edit-variation-property>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-edit-variation-property]]
.Editing a property
[cols="1,3"]
|====
|Setting |Explanation

2+|View *General*

|*Position*
|Enter the new position to change the order of the properties.

|*Units*
|This setting is currently without function.

|*Order property*
|Activate this option to make sure that the property will be displayed in the order process.

|*Display as additional costs*
|Activate to show the surcharge as additional costs.

|*Name*; +
*Description*
|For multilingualism, enter name and description for other languages.

2+|View *Visibility*

|*Client (store)*
|Select one or more clients (stores) that the property should be activated for.

|*Visibility*
|Select one or more types that the property should be visible for.

2+|*Values*

|Only visible for property type *Selection*
a|Enter the values that should be displayed in the drop-down list. +
Click on *Add value* to create a value.

* *Name* = Enter a name for the property value.
|====

[#800]
=== Searching for a property

Properties are centrally managed in the *Setup » Settings » Properties » Configuration* menu. After opening the menu, start the search to display the properties. In order to search for specific properties, enter a search term in the search fields. The drop-down lists will help you to search for properties that share specific criteria. You can combine as many search filters as you like.

[.instruction]
Searching for a property:

. Go to *Setup » Settings » Properties » Configuration*.
. In the *Filter* view, enter the search term in the search field or set the filter options in the drop-down lists. Note <<table-filter-variation-properties>>.
. Click on *Search*. +
→ The properties that correspond to the search criteria entered are displayed.
. Click in the line of the property. +
→ The detail view of the property opens.

[[table-filter-variation-properties]]
.Filters for the properties
[cols="1,3"]
|====
|Setting |Explanation

|*Search*
|Click on *Search* without selecting any filter settings. This will display all properties. +
icon:map-signs[] *_Or:_* Limit the search results by using filters and click on *Search*. +
→ The properties found are listed in the overview.

|*Reset*
|Resets the filter criteria that was entered.

|*ID*
|Each property automatically receives a consecutive and unique ID.

|*Name*
|Enter the name to search for the property with this name. It is also possible to search only for parts of the name.

|*Language*
|Select a language to only display properties for which a name has been saved in this language.

|*Group*
a|Select the group to only display properties that are assigned to this group.

* Select *Not grouped* to only display properties that are not assigned to a group.
* Select *Grouped* to only display properties that are assigned to a group.

|*Section*
|Select a section to only display properties that are used in this section.

|*Property type*
|Select a property type to only display properties of this type.
|====


[#900]
=== Deleting a property

You can delete one or more properties at the same time.

[#1000]
==== Deleting a property

Proceed as described below to irreversibly delete a property if it is no longer needed.

[.instruction]
Deleting a property:

. Go to *Setup » Settings » Properties » Configuration*.
. *_Optional:_* Select filters to limit the search results.
. Start the search.
. Click on the property. +
→ The detail view of the property opens.
. Click on *Delete property*. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The property is deleted and removed from the overview.

[#1100]
==== Deleting multiple properties

Proceed as described below to irreversibly delete multiple properties if they are no longer needed.

[.instruction]
Deleting multiple properties:

. Go to *Setup » Settings » Properties » Configuration*.
. *_Optional:_* Select filters to limit the search results.
. Start the search.
. Activate the properties that you want to delete.
. Click on *Delete*. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The selected properties are deleted and removed from the overview.

[#1200]
=== Grouping properties

Create property groups to summarise multiple properties. Proceed as described below to create a property group.

[.instruction]
Creating a property group:

. Go to *Setup » Settings » Properties » Groups*.
. Click on *Add property group*.
. Carry out the settings. Note <<table-create-variation-property-group>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The property group is created.

[[table-create-variation-property-group]]
.Creating a new property group
[cols="1,3"]
|====
|Setting |Explanation

|*Name*
|Enter the name for the property group. +
*_Note:_* The name of the system language is displayed by default. After the property group has been created, you can save the name in English. Further languages are planned.

|*Description*
|Enter the description for the property group. +
*_Note:_* The description of the system language is displayed by default. After the property group has been created, you can save the description in English. Further languages are planned.

|*Position*
|Enter the position number for the property group. Properties are sorted by the position number in ascending order. +
*_Tip:_* Count by tens when creating position numbers. This will allow you to easily add new property groups in between.

|*Group type*
a|Select the group type from the drop-down list. This option determines how properties of the type *Empty* are displayed in the order process.

* *None* = Properties will not be grouped by default.
* *Select* = One of the grouped properties can be selected from the drop-down list.
* *Multiselect* = Multiple properties can be selected.
*_Note:_* This option only applies for properties of the type *None* for which the *Order process* option has been activated.

|*Surcharge type*
a|Select the type of surcharge from the drop-down list.

* *Flat* = The surcharge will be entered as flat amount.
* *Percent* = The surcharge will be entered as percentage.
|====

[#1300]
==== Assigning properties to a group

Proceed as described below to assign one or more properties to a property group.

[.instruction]
Assigning properties to a group:

. Go to *Setup » Settings » Properties » Configuration*.
. *_Optional:_* Select filters to limit the search results.
. Start the search.
. Activate the properties that you want to assign to the group.
. Click on *Assign property group*. +
→ A drop-down list of property groups opens.
. Select the property group from the drop-down list.
. Click on *Group function*. +
→ The selected properties are assigned to the property group.

[#1400]
==== Deleting property groups

You can delete one or more property groups at the same time. Properties that are assigned to groups will remain unaffected when deleting property groups.

[#1500]
===== Deleting a property group

Proceed as described below to irreversibly delete a property group if it is no longer needed.

[.instruction]
Deleting a property group:

. Go to *Setup » Settings » Properties » Groups*.
. *_Optional:_* Select filters to limit the search results.
. Start the search.
. Click on the property group. +
→ The detail view of the property group opens.
. Click on *Delete group*. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The property group is deleted and removed from the overview. +
*_Note:_* When you delete a property group, the properties that are assigned to the group will not be deleted.

[#1600]
===== Deleting multiple property groups

Proceed as described below to irreversibly delete multiple property groups if they are no longer needed.

[.instruction]
Deleting multiple property groups:

. Go to *Setup » Settings » Properties » Groups*.
. *_Optional:_* Select filters to limit the search results.
. Start the search.
. Activate the property groups that you want to delete.
. Click on *Delete*. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The selected property groups are deleted and removed from the overview. +
*_Note:_* When you delete a property group, the properties that are assigned to the group will not be deleted.
