= Units
:lang: en
include::{includedir}/_header.adoc[]
:description: There are 52 units saved in plentymarkets by default. Learn how to create additional units of measure as needed.
:url: item/settings/units
:icons: font
:position: 20
:docinfodir: /workspace/manual-adoc
:docinfo1:

Units such as kilograms, litres and centimetres help you define the size or dimensions of your products.

There are 52 units saved according to their ISO code in plentymarkets by default. However, you can <<item/settings/units#100, create additional units of measure>> or edit the existing units as needed.

You can also <<item/settings/units#200, create variations>> by combining units with different quantities. For example, you might sell a bottle of soap that’s available in 50ml, 100ml or 150ml.

You’ve surely seen an item’s <<item/settings/units#300, unit price>> displayed on the shelves in grocery stores. The unit price tells you how much the item costs per pound, litre or other unit of measure. It’s calculated based on the item’s content, unit and price. It can be displayed on various sales channels and on item labels.

[#100]
== Creating new units and editing existing ones

There are 52 units saved according to their ISO code in plentymarkets by default. Take a look at the existing units in the menu *Setup » Item » Units*. Create additional units of measure or edit the existing units as needed.

[.instruction]
Creating a new unit:

. Go to *Setup » Item » Units*.
. Click on *New* (icon:plus[role="green"]). +
→ The *Create new unit* window opens.
. Enter a name.
. *_Optional:_* Enter a position number.
. *Save* (icon:save[role="green"]) the settings. +
→ The new unit will be created and it will open automatically.
. Edit the unit further as needed.

[.instruction]
Editing an existing unit:

. Go to *Setup » Item » Units*.
. Click on a unit. +
→ The unit opens in a new tab.
. Carry out the settings. Note <<table-edit-units>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-edit-units]]
.Editing units
[cols="1,2"]
|====
|Setting |Explanation

2+|*Settings*

|*Position*
|Enter the position number of the unit.

|*Units of measure (ISO)*
|Select the unit of measure according to its ISO code.

|*Decimal numbers*
|Select *Permit* or *Do not permit*.

2+|*Language*

|*Unit name*
|Enter the unit name in the respective languages.
|====

[#200]
== Combining units and creating variations

You can create variations by combining units with different quantities. For example, you might sell a bottle of soap that’s available in 50ml, 100ml or 150ml.

You can enter an item’s unit and content <<item/managing-items#20, while creating the item>>. If you <<item/managing-items#160, create additional variations>>, then you can enter the unit and content for each variation separately.

[#300]
== Displaying the unit price on sales channels and labels

You’ve surely seen an item’s unit price displayed on the shelves in grocery stores. The unit price tells you how much the item costs per pound, litre or other unit of measure.

It’s calculated based on the item’s <<item/managing-items#270, content, unit>> and <<item/managing-items#240, price>>. It can be displayed <<item/managing-items#270, in the online store>>, on sales channels such as <<markets/ebay/ebay-setup#4000, eBay>> or <<markets/plus-gartenxxl#365, Netto>> and <<item/managing-items#3300, on item labels>>.
