= Die plentymarkets App
:lang: de
include::{includedir}/_header.adoc[]
:position: 10
:url: app

[#100]
== Warum du die App nutzen solltest

Verschaffe dir auch von unterwegs einen Überblick über dein Business. Willst du wichtige Geschäftszahlen wie Umsätze und Auftragsvolume direkt auf deinem Smartphone sehen? Mit der plentymarkets App bist du auch unterwegs gut ausgerüstet!

Sollen deine Lagermitarbeiter mit einer mobilen Warenwirtschaft kommissionieren? Die plentymarkets App unterstützt dich beim Picken und Packen. Weiterhin können Lagermitarbeiter die App nutzen, um Ware zu verräumen oder Inventur durchzuführen.

Willst du deinen stationären Handel mit plentymarkets verbinden? Dafür ist das mobile Kassensystem plentymarkets POS genau das richtige Tool. Lass deine Mitarbeiter intuitiv im Laden kassieren. Die App meldet alle Geschäftsvorgänge zurück an plentymarkets. Somit bleiben deine On- und Offline-Verkäufe immer im Einklang.

[#200]
== Welche Schritte gehören zur Einrichtung?

[#300]
=== App herunterladen und auf der passenden Hardware installieren

Wofür möchtest du die plentymarkets App nutzen? Je nach Anwendungsfall unterscheidet sich die <<app/installieren#123456, Wahl der passenden Hardware>>. Willst du beispielsweise Barcodes scannen und Kartenzahlungen annehmen, brauchst du andere Hardware als wenn du lediglich deine Geschäftszahlen im Blick behalten möchtest.

Entscheide dich für die passende Hardware und lade die App auf dem Gerät herunter.

* link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=de[plentymarkets App bei Google Play^]
* link:https://itunes.apple.com/de/app/plentymarkets/id957702618[plentymarkets App bei iTunes^]

[#400]
=== Einloggen und Zugang gewähren

Die plentymarkets App ist nur in Kombination mit link:https://www.plentymarkets.eu/gratis-testen/[einem gebuchten plentymarkets System] funktionsfähig. Das heißt, dass du dich in der App <<app/installieren#123456, mit denselben Zugangsdaten anmeldest>> wie in deinem plentymarkets System.

Sollen weitere Mitarbeiter die plentymarkets App benutzen, müssen sie ebenfalls Zugangsdaten erhalten. Lege zunächst fest, <<app/installieren#123456, in welchem Umfang deine Mitarbeiter die App verwenden>> dürfen.

[#500]
=== Die App personalisieren

Möchtest du z.B. bestimmen, in welcher Reihenfolge und in welcher Schriftgröße einzelne Informationen in der App dargestellt werden? Oder willst du z.B. statt das Standard-Hintergrunds die Farben deines eigenen Corporate Designs verwenden? <<app/personalisieren#, Personalisiere die App>> und richte sie nach deinen Wünschen ein!

[#600]
=== Auf dem Laufenden bleiben

Wartest du sehnsüchtig auf ein neuer Feature? Wir informieren dich gerne über Änderungen an der Software! Versionen der plentymarkets App sind durch Versionsnummern gekennzeichnet. Änderungen werden zudem link:https://forum.plentymarkets.com/c/changelog/changelog-app[in einem Changelog] veröffentlicht. Abonniere den Changelog und bleibe immer auf dem Laufenden.


[#700]
== Welche Funktionen stehen dir zur Verfügung?

Die plentymarkets App beinhaltet eine Reihe nützlicher Funktionen, die auf den folgenden Seiten beschrieben sind.

* <<app/funktionen/kennzahlen#, Unternehmenskennzahlen einsehen>>
* <<app/funktionen/daten-suchen#, Artikel-, Kunden- und Auftragsdaten einsehen>>
* <<app/funktionen/lagerverwaltung#, Lagerverwaltung>>
** <<app/funktionen/lagerverwaltung/picklisten#, Mit Picklisten arbeiten>>
** <<app/funktionen/lagerverwaltung/rollende-kommissionierung#, Rollende Kommissionierung>>
** <<app/funktionen/lagerverwaltung/einbuchen-umbuchen#, Ware einbuchen und umbuchen>>
** <<app/funktionen/lagerverwaltung/verräumen#, Ware verräumen>>
** <<app/funktionen/lagerverwaltung/inventur#, Inventur durchführen>>
* <<pos#, Mobile Kassensystem plentymarkets POS>>
** <<pos/pos-kassenbenutzer#30, Kassieren>>
** <<pos/pos-best-practice#10, Gutscheine verkaufen und einlösen>>
** <<pos/pos-kassenbenutzer#173, Stornierungen und Retouren>>
** <<pos/pos-best-practice#100, Online-Bestellungen an der Kasse abschließen (Click & Collect)>>
** <<pos/pos-kassenbenutzer#180, Einlagen und Entnahmen>>
** <<pos/pos-kassenbenutzer#210, Tagesabschluss und Kassensturzbericht>>
