= Die plentymarkets App
:lang: de
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: App, plentymarkets App, Hardware, App Zugangsdaten, App-Installation, App installieren, App personalisieren, plentymarkets POS, plentyPOS, plenty POS, plentymarketsApp, plentyApp
:position: 115
:url: app
:nav-alias: Übersicht

[#100]
== Warum du die App nutzen solltest

Verschaffe dir auch von unterwegs einen Überblick über dein Business. Willst du wichtige Geschäftszahlen wie Umsätze und Auftragsvolume direkt auf deinem Smartphone sehen? Mit der plentymarkets App bist du auch unterwegs gut ausgerüstet!

Sollen deine Lagermitarbeiter:innen mit einer mobilen Warenwirtschaft kommissionieren? Die plentymarkets App unterstützt dich beim Picken und Packen. Weiterhin können Lagermitarbeiter:innen die App nutzen, um Ware zu verräumen oder die Inventur durchzuführen.

Willst du deinen stationären Handel mit plentymarkets verbinden? Dafür ist das mobile Kassensystem plentyPOS genau das Richtige. Lass deine Mitarbeiter:innen intuitiv im Laden kassieren. Die App meldet alle Geschäftsvorgänge zurück an plentymarkets. Somit bleiben deine Verkäufe immer im Einklang - egal ob online oder im Ladengeschäft.

[#200]
== Welche Schritte gehören zur Einrichtung?

[#300]
=== App herunterladen und auf der passenden Hardware installieren

Wofür möchtest du die plentymarkets App nutzen? Je nach Anwendungsfall unterscheidet sich die <<app/installation#100, Wahl der passenden Hardware>>. Willst du beispielsweise Barcodes scannen und Kartenzahlungen annehmen, brauchst du andere Hardware als wenn du lediglich deine Geschäftszahlen im Blick behalten möchtest.

Entscheide dich für die passende Hardware und lade die App auf dem Gerät herunter.

* Für Android-Geräte: link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=de[plentymarkets App im Google Play Store^]{nbsp}icon:external-link[]
* Für iOS-Geräte: link:https://itunes.apple.com/de/app/plentymarkets/id957702618[plentymarkets App im App Store^]{nbsp}icon:external-link[]

[#400]
=== Einloggen und Zugang gewähren

Die plentymarkets App funktioniert nur in Kombination mit link:https://www.plentymarkets.com/de/[einem gebuchten plentymarkets System^]{nbsp}icon:external-link[]. Das heißt, dass du dich in der App <<app/installation#1200, mit denselben Zugangsdaten anmeldest>> wie in deinem plentymarkets System.

Sollen mehrere Mitarbeiter:innen die plentymarkets App benutzen, müssen sie ebenfalls Zugangsdaten erhalten. Lege zunächst fest, <<app/installation#600, in welchem Umfang deine Mitarbeiter:innen die App verwenden>> dürfen.

[#500]
=== Die App personalisieren

Möchtest du z.B. bestimmen, in welcher Reihenfolge und in welcher Schriftgröße einzelne Informationen in der App dargestellt werden? Oder willst du anstatt des Standard-Hintergrunds die Farben deines eigenen Corporate Designs verwenden? <<app/installation#1800, Personalisiere die App>> und richte sie nach deinen Wünschen ein!

[#600]
=== Auf dem Laufenden bleiben

Wartest du sehnsüchtig auf ein neues Feature? Wir informieren dich gerne über Änderungen an der Software! Versionen der plentymarkets App sind durch Versionsnummern gekennzeichnet. Änderungen werden zudem link:https://forum.plentymarkets.com/c/changelog/changelog-app[in einem Changelog^]{nbsp}icon:external-link[] veröffentlicht. Abonniere den Changelog und bleibe immer auf dem Laufenden.


[#700]
== Welche Funktionen stehen dir zur Verfügung?

Die plentymarkets App bietet dir eine Reihe nützlicher Funktionen, die auf den folgenden Seiten beschrieben sind.

* <<app/funktionen/kennzahlen#, Unternehmenskennzahlen einsehen>>
* <<app/funktionen/artikelsuche#, Artikel-, Kunden- und Auftragsdaten einsehen>>
* <<app/funktionen/lagerverwaltung#, Mobile Warenwirtschaft>>
** <<app/funktionen/lagerverwaltung/rollende-kommissionierung#, Rollende Kommissionierung>>
** <<app/funktionen/lagerverwaltung/einbuchen-umbuchen#, Ware einbuchen und umbuchen>>
** <<app/funktionen/lagerverwaltung/verräumen#, Ware verräumen>>
** <<app/funktionen/lagerverwaltung/inventur#, Inventur durchführen>>
* <<pos#, Mobiles Kassensystem plentyPOS>>
** <<pos/pos-kassenbenutzer#30, Kassieren>>
** <<pos/pos-einrichten#2700, Gutscheine verkaufen und einlösen>>
** <<pos/pos-kassenbenutzer#173, Stornierungen und Retouren>>
** <<pos/pos-online-bestellungen#, Online-Bestellungen an der Kasse abschließen (Click & Collect)>>
** <<pos/pos-kassenbenutzer#180, Einlagen und Entnahmen>>
** <<pos/pos-kassenbenutzer#210, Tagesabschluss und Kassensturz>>
