= Aufträge
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Aufträge verwalten, Auftragstypen, Buchhaltung, Dokumente, Steuer
:description: Erfahren Sie, wie Sie Ihre Buchhaltung einrichten, Dokumente einrichten und generieren sowie Aufträge verwalten.
:position: 60
:url: auftraege
:id: QV9OPKI
:nav-alias: Übersicht

In diesem Themenbereich finden Sie alle Informationen zu eingehenden Aufträgen und wie Sie nach dem Auftragseingang fortfahren. Je nachdem für welche Verkaufsstrategie und Verkaufskanäle Sie sich entscheiden, fließen nach erfolgreicher Einrichtung der Kanäle Aufträge verschiedener *<<auftraege/auftragsherkunft#, Herkünfte>>* in Ihr plentymarkets-System ein. Neben dem eigenen Webshop sind dies in erster Linie die verschiedenen *<<maerkte#, Marktplätze und Preisportale>>*. +

plentymarkets verfügt u.a. über eine umfangreiche Schnittstelle zu *<<maerkte/amazon/amazon-einrichten#, Amazon>>*, die nicht nur den automatisierten Abgleich mit dem *<<maerkte/amazon/amazon-einrichten#900, Seller Central>>* gewährleistet, sondern auch weitere Amazon-Angebote wie *<<maerkte/amazon/amazon-einrichten#3300, Fulfillment by Amazon>>* und *<<maerkte/amazon/amazon-einrichten#3700, Amazon Multi-Channel>>* umfasst. +

Dank der vollständigen *<<maerkte/ebay/ebay-einrichten#, eBay-Anbindung>>* in plentymarkets können Sie u. a. Listings starten und eBay-Shop-Artikel bei eBay einstellen, Verkäufe abrufen, automatisch Bewertungen abgeben und Käufer anmahnen. +

Nach dem Auftragseingang werden alle Aufträge in einem Menü gesammelt und in einem identischen Format dargestellt, damit die Bearbeitung leicht erfolgen kann. Jeder Auftrag erhält eine eindeutige **Auftrags-ID**. Weitere Schritte nach dem Auftragseingang, wie die Eingangsbestätigung zur Bestellung, andere E-Mails oder Rechnungs- und Lieferscheingenerierung lassen sich automatisieren. Neben dem eigentlichen Auftrag, der im Rahmen einer Bestellung angelegt wird, gibt es in plentymarkets weitere *Auftragstypen*. Die Auftragstypen dienen dazu, verschiedene Geschäftsvorfälle abzubilden. +

Folgende Auftragstypen gibt es in plentymarkets:

 * Auftrag
 * Angebot
 * Vorbestellung
 * Gewährleistung
 * Gutschrift
 * Lieferauftrag
 * Reparatur
 * Retoure
 * Sammelauftrag
 * Sammelgutschrift

Für den Versand stehen mit Dokumenten wie der *<<auftraege/auftragsdokumente/pickliste#, Pickliste>>* und der *<<auftraege/auftragsdokumente/packliste#, Packliste>>* die notwendigen Unterlagen zur Verfügung, um ein schnellstmögliches Fulfillment zu gewährleisten.

Im <<fulfillment/versand-center#versandauftrag-anmelden, Versand-Center>> melden Sie schließlich die Versandaufträge an, bearbeiten diese bei Bedarf oder lassen sich spezielle Versandaufträge anzeigen.

Zur effizienten Bearbeitung von Aufträgen und anderen Geschäftsvorfällen können Sie außerdem *<<automatisierung/prozesse/prozesse-einrichten#, Prozesse>>* anlegen und diese automatisiert ablaufen lassen. Prozesse bieten den höchsten Grad der Automatisierung für plentymarkets.
