= Aufträge
:lang: de
include::{includedir}/_header.adoc[]
:description: Erfahre, wie du deine Buchhaltung einrichtest, Dokumente einrichtest und generierst sowie Aufträge verwaltest.
:position: 60
:url: auftraege
:id: QV9OPKI
:nav-alias: Übersicht
:keywords: Aufträge verwalten, Auftrag, Aufträge, Auftragsabwicklung
:author: team-order-core, team-docs-automation

In diesem Themenbereich findest du alle Informationen zu eingehenden Aufträgen und wie du nach dem Auftragseingang fortfährst. Je nachdem für welche Verkaufsstrategie und Verkaufskanäle du dich entscheidest, fließen nach erfolgreicher Einrichtung der Kanäle Aufträge verschiedener <<auftraege/auftragsherkunft#, Herkünfte>> in dein plentymarkets System ein. Neben dem eigenen Webshop sind dies in erster Linie die verschiedenen <<maerkte#, Marktplätze und Preisportale>>.

plentymarkets verfügt u.a. über eine umfangreiche Schnittstelle zu <<maerkte/amazon/amazon-einrichten#, Amazon>>, die nicht nur den automatisierten Abgleich mit dem Seller Central gewährleistet, sondern auch weitere Amazon-Angebote wie <<maerkte/amazon/amazon-fulfillment#, Fulfillment by Amazon>> umfasst.

Dank der vollständigen <<maerkte/ebay/ebay-einrichten#, eBay-Anbindung>> in plentymarkets kannst du u.a. Listings starten und eBay-Shop-Artikel bei eBay einstellen, Verkäufe abrufen, automatisch Bewertungen abgeben und Käufer:innen anmahnen.

Nach dem Auftragseingang werden alle Aufträge in einem Menü gesammelt und in einem identischen Format dargestellt, damit die <<auftraege/auftraege-verwalten#1500, Bearbeitung>> leicht erfolgen kann. Jeder Auftrag erhält eine eindeutige *Auftrags-ID*. Weitere Schritte nach dem Auftragseingang, wie die Eingangsbestätigung zur Bestellung, andere E-Mails oder die Generierung von <<auftraege/auftragsdokumente#, Auftragsdokumenten>>, lassen sich automatisieren. Neben dem eigentlichen Auftrag, der im Rahmen einer Bestellung angelegt wird, gibt es in plentymarkets weitere *Auftragstypen*. Die Auftragstypen dienen dazu, verschiedene Geschäftsvorfälle abzubilden.

Folgende Auftragstypen gibt es in plentymarkets:

 * <<auftraege/auftraege-verwalten#, Auftrag>>
 * <<auftraege/auftraege-verwalten#240, Angebot>>
 * <<auftraege/auftraege-verwalten#1100, Vorbestellung>>
 * <<auftraege/auftraege-verwalten#600, Gewährleistung>>
 * <<auftraege/auftraege-verwalten#500, Gutschrift>>
 * <</auftraege/auftraege-verwalten#300, Lieferauftrag>>
 * <<auftraege/auftraege-verwalten#700, Reparatur>>
 * <<auftraege/auftraege-verwalten#400, Retoure>>
 * <<auftraege/auftraege-verwalten#800, Sammelauftrag>>
 * <<auftraege/auftraege-verwalten#850, Sammelgutschrift>>

Für den Versand stehen mit Dokumenten wie der <<auftraege/auftragsdokumente/pickliste#, Pickliste>> und der <<auftraege/auftragsdokumente/packliste#, Packliste>> die notwendigen Unterlagen zur Verfügung, um ein schnellstmögliches Fulfillment zu gewährleisten.

Im <<fulfillment/versand-center#versandauftrag-anmelden, Versand-Center>> meldest du die Versandaufträge an, bearbeitest diese bei Bedarf oder lässt dir spezielle Versandaufträge anzeigen.

Zur effizienten Bearbeitung von Aufträgen und anderen Geschäftsvorfällen kannst du außerdem <<automatisierung/prozesse/prozesse-einrichten#, Prozesse>> anlegen und diese automatisiert ablaufen lassen. Prozesse bieten den höchsten Grad der Automatisierung in plentymarkets. Darüber hinaus stehen dir noch <<automatisierung/ereignisaktionen#, Ereignisaktionen>> und der <<automatisierung/aktionsmanager#, Aktionsmanager>> zur Verfügung, um deine Auftragsabwicklung durch Automatismen zu erleichtern.
