= plentymarkets Changelog
:lang: de
include::{includedir}/_header.adoc[]
:author: none
:sectnums!:
:position: 150
:url: changelog
:id:
:startWeekDate: 20. Februar 2020
:endWeekDate: 26. Februar 2020
:nav-alias: Changelog 26. Februar 2020

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Wochen für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite <<basics/admin-aufgaben/versionszyklus#, Versionszyklus>>. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

== stable

In diesem Bereich findest du alles, was in der letzten Woche auf *stable* veröffentlicht wurde.

=== Behoben

[discrete]
==== PO-Lieferschein

* Bei der Generierung eines PO-Lieferscheines in einer Umbuchung wurde unter Umständen der falsche Standort für die Steuersätze gesucht, was zu einem Fehler führte. Dies wurde behoben.

[discrete]
==== Royal Mail

* Die fest integrierte Schnittstelle zu Royal Mail und die fest integrierte Schnittstelle zu Royal Mail über NetDespatch wurden aus dem plentymarkets Backend entfernt. Die Funktionalität, Pakete über Royal Mail zu versenden, wurde vom Anbieter NetDespatch schon vor längerer Zeit eingestellt.
+
Zukünftig wird ein Plugin zur Verfügung stehen, an dem wir aktuell arbeiten.

[discrete]
==== Spezialexport Collmex

* Wenn Rechnungen einen Präfix in der Rechnungsnummer haben, wurden stornierte Rechnungen nicht im Export ausgegeben, denn es kam zu einem Fehler im Abgleich der Rechnungsnummer (einmal mit und einmal ohne den Präfix).

[discrete]
==== Webshop

* Wenn sich Kunden im Webshop anmelden, wird ab sofort die *primäre Rechnungsadresse* vorausgewählt. Falls keine Rechnungsadresse als primär definiert ist, wird wie bisher die zuerst angelegte Adresse vorausgewählt.
+
Weitere Informationen zu primären Adressen findet ihr auf der Seite <<crm/kontakte-verwalten#, Kontakte verwalten>>.

== early

In diesem Bereich findest du alles, was in der letzten Woche auf *early* veröffentlicht wurde.



== Plugin-Updates

Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name
|Version
|To-do

|link:https://marketplace.plentymarkets.com/plugins/integration/dhlwunschpaket_5435[DHL Wunschpaket^]
|1.1.5
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].
