= plentymarkets Changelog
:lang: de
include::{includedir}/_header.adoc[]
:author: kevin-stederoth
:sectnums!:
:position: 150
:url: changelog
:id:
:startWeekDate: 12. März 2020
:endWeekDate: 18. März 2020
:nav-alias: Changelog 18. März 2020

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Wochen für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite <<basics/admin-aufgaben/versionszyklus#, Versionszyklus>>. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[.tabs]
====
stable::
+
--
[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *stable* veröffentlicht.

[discrete]
=== Datenbereinigung

* In der Bereinigungs-UI im Menü *Einrichtung » Einstellungen » Daten » Bereinigung* wurde das neue Eingabefeld *Löschung von Newsletter-Registrierungen (nach Tagen)* hinzugefügt. Hier wird die Löschung der abgelaufenen und nicht bestätigten Newsletter-Anmeldungen nach Tagen eingestellt. Täglich werden Newsletter-Einträge gelöscht, die älter sind als die konfigurierten Tage.

[discrete]
=== Import

* Für den Sync-Typ *Gutschein-Code* wurden die beiden Zuordnungsfelder *Anzahl der Einlösungen* und *Eingelöster Betrag* hinzugefügt.
* Für den Sync-Typ *Kontakte, Firmen und Adressen* wurde das Zuordnungsfeld *Ansprechpartner* in den Kontaktoptionen hinzugefügt.
* Wir haben in der Status-UI eine neue Datumsauswahl implementiert, so dass ihr die Importe einfacher und schneller filtern könnt.

[discrete]
=== Plugin-Übersicht

* Du kannst ab jetzt die Inhalte deiner Plugin-Sets in der neuen Plugin-UI einsehen. Öffne dazu das Menü *Plugins » Plugin-Set-Übersicht (Alpha)* und klicke auf die Schaltfläche Plugin-Set bearbeiten.
+
Du kannst momentan folgende Aktionen in der neuen UI ausführen:
** Plugin-Set-Name ändern
** Plugin-Set bereitstellen
** Plugin aktivieren
** Plugin deaktivieren
** Konfigurationen aller Plugins in einem Plugin-Set gesammelt exportieren
** Konfigurationen aller Plugins in einem Plugin-Set gesammelt importieren

+
Wir freuen uns bereits auf dein Feedback. Wenn du die neue UI erkundest und dir etwas auffällt, das gut, schlecht oder auch total unverständlich ist, freuen wir uns auf eine entsprechende Rückmeldung link:https://forum.plentymarkets.com/t/feedback-neue-plugin-ui-feedback-for-new-plugin-ui/579903[im zugehörigen Thema in der Forumskategorie Plugin-Einrichtung^].

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *stable* veröffentlicht.

[discrete]
=== Aktionen

* Bei Aktionen (*Einrichtung » Aufträge » Aktionen*), kann nun auch eine tägliche Ausführung zwischen 24 und 7 Uhr gewählt werden.

[discrete]
=== Benutzerrechte

* Die Benutzerrechte für das Menü *Einrichtung » Mandant » Mandant wählen » E-Mail* wurden angepasst. Bisher war es im Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer* im Bereich *Berechtigungen* nur möglich, eine Berechtigung für den gesamten Bereich *E-Mail* zu setzen. Demnach wurden alle weitere Unterpunkte (Zugangsdaten, Signatur, Infodienst, Newsletter, Vorlagen, Automatischer Versand und HTML-Design) automatisch mit vergeben.
+
Dieses Verhalten wurde angepasst, sodass du nun für jeden Backend-Benutzer die einzelnen Unterberechtigungen aktivieren bzw. deaktivieren kannst.
+
Benutzer, die bereits den Bereich *E-Mail* aktiviert hatten, haben diesen Bereich sowie alle dazugehörigen Unterpunkte immer noch aktiviert. Wenn diese Benutzer alle E-Mail-Bereiche bearbeiten können sollen, musst du nichts anpassen.
+
[IMPORTANT]
.To-Do
======
Für Backend-Benutzer, die nicht alle Berechtigungen im Bereich *E-Mail* bearbeiten können sollen, musst du diese anpassen. Gehe dazu in das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer* und öffne den zu bearbeitenden Benutzer und deaktiviere im Bereich *Berechtigungen* die Berechtigungen wie gewünscht.
======

[discrete]
=== OTTO

:otto-master-date: 13.03.2020
:otto-master-link: https://plentymarkets-discourse.s3.dualstack.eu-central-1.amazonaws.com/original/3X/1/f/1f4896c4208f67da83de57eb350532b1499eddd0.xlsx

include::changelog/_textblocks/otto-master-file.adoc[]

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *stable* behoben.

[discrete]
=== Auftragsdokumente

* Bei Auftragsdokumenten ist es in seltenen Konstellation beim Verwenden von zwei oder mehr Mandanten und Dokumenten ohne oder mit gleichem Präfix dazu gekommen, das diese überschrieben wurden. Dieser Fall konnte aber nur eintreten, wenn Dokumente des gleichen Typs zur gleichen Zeit geschrieben wurden. Dies wurde behoben.

[discrete]
=== Ereignisaktionen

* In der Übersicht der Ereignisaktionen wurde bei einigen Aktionen und Filtern unnötigerweise *not yet implemented* angezeigt. Das wurde entfernt.

[discrete]
=== Nachbestellungen

* Innerhalb einer Nachbestellung oder Umbuchung gelangt man durch die Betätigung des Links der Artikel-ID in die jeweilige Artikel-Detailsansicht. Über den Tab *Bestand* des Artikels und die dortige Betätigung des Links des physischen Warenbestandes, öffnet die Warenbewegungen der jeweils ausgewählten Variante.
+
Dieses Verhalten führte bisher zu einem Fehler (Meldung: `Beim Öffnen der Warenbewegung ist ein Fehler aufgetreten.`), der in Zusammenhang mit dem beschriebenen Workflow steht. Es wurde eine Anpassung für beta7 zur Verfügung gestellt, die diesen Fehler behebt, so dass zukünftig die Warenbewegungen der Varianten problemlos geöffnet werden können.
+
Durch die Anpassung des Fehlverhaltens wird zukünftig bei der Betätigung des Links der Artikel-ID (in der Artikel-Liste der Nachbestellung) nicht mehr der Tab *Global* geöffnet, sondern stattdessen die jeweilige Detailsansicht der Variante.

[discrete]
=== PO-Lieferschein

* Die PDF-Vorlage beim PO Lieferschein wird nun korrekt erkannt und benutzt.

--

early::
+
--
[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *early* veröffentlicht.



'''



'''



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name
|Version
|To-do

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/widgets/notificationbar_6767[Ceres Beautifier: Notification Bar^]
|1.0.0
|-

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/widgets/cookieposition_6768[Ceres Beautifier: Cookie Position^]
|1.0.1
|-

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/widgets/cfourcontainerpopup_5932[Container Popup^]
|1.1.0
|-

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/widgets/cfourstructureddata_5114[Erweiterte Strukturierte Daten^]
|1.1.1
|-

|link:https://marketplace.plentymarkets.com/plugins/sales/marketing/wesiocatalog_6759[Kataloggenerator^]
|1.0.0
|-

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/widgets/cfourcategorytabswidget_5842[Kategorie Reiter Widget^]
|1.0.6
|-

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/widgets/cfourseochecktool_5157[SEO Check Frontend Tool^]
|1.2.1
|-

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/shopbuilder-widgets/d2gpmpluginshippingicons_6756[Versand Icons Widget^]
|1.0.0
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].
--
====
