= plentymarkets Changelog
:lang: de
include::{includedir}/_header.adoc[]
:author: kevin-stederoth
:sectnums!:
:position: 150
:url: changelog
:id:
:startWeekDate: 08. Juli 2020
:endWeekDate: 15. Juli 2020
:nav-alias: Changelog 15. Juli 2020

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Wochen für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite <<business-entscheidungen/systemadministration/versionszyklus#, Versionszyklus>>. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^]{nbsp}icon:external-link[].

Wähle, welchen Changelog du sehen möchtest.

[.tabs]
====
stable::
+
--
[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *stable* veröffentlicht.

[discrete]
=== Amazon

* Der neue Gutschriftenimport für VCS kann nun auch:
** Gutschriften erzeugen, in denen nur Versandkosten erstattet werden.
** Für VCS Amazon interne Gutschriftendokumente erzeugen, für den Fall, dass Amazon in seinen VCS-Bericht keine Gutschriftennummer bereitstellt, weil Amazon dies bei bestimmten Konstellationen nicht muss.

[discrete]
=== Ticketsystem

* Wir haben im Menü *Einrichtung » CRM » Ticketsystem » Ereignisse* die Ereignisaktion *Neue Nachricht vom Mitarbeiter* erweitert:
** Der Filter *Gastbestellung* wurde hinzugefügt.
** In der Aktion *E-Mail versenden* wurde in der Dropdown-Liste die Einstellung *Rechnungsadresse - Auftrag* hinzugefügt, damit die E-Mail an die Rechnungsadresse aus dem Auftrag gesendet wird.
** Außerdem wurde in der Aktion *E-Mail versenden* die Einstellung *der Kunde* umbenannt in *Kontakt (CRM)*.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *early* veröffentlicht.

[discrete]
=== Amazon

* Wenn die folgenden zwei Optionen entweder über die Einstellungen oder den Assistenten beide aktiviert sind, werden Gutschriften nicht mehr über die Finances API importiert, sondern über die entsprechenden Berichte für VCS bzw. VCS Lite.
** Über die Einstellungen (*Einrichtung » Märkte » Amazon » Einstellungen » _Konto öffnen_*):
. Option *Rechnung erzeugen* mit der Auswahl _VCS Amazon_ oder _VCS plentymarkets_ unter *Tab: Einstellungen » Bereich: Basiseinstellungen*
. Option *Gutschriftenimport* unter *Einrichtung » Märkte » Amazon » Einstellungen » _Konto öffnen_ » Tab: Auftragseinstellungen » Bereich: Eigener Versand (MFN)*
** Über den Assistenten (*Einrichtung » Assistenten » Omni-Channel » Amazon Grundeinstellungen » _Konto öffnen_*):
. Option *Wer soll Rechnungen für Amazon-Bestellungen erzeugen?* mit der Auswahl _Amazon-Rechnungsservice_ oder _plentymarkets Rechnungsservice_ mit Daten von Amazon im Schritt *Automatische Datenübertragung*.
. Option *Möchtest du FBA-Gutschriften in plentymarkets importieren?* im Schritt *Versand durch Amazon (FBA)*.

+
Das bedeutet, dass die Gutschriften nicht mehr erst über die Finances API importiert und dann im Nachgang korrigiert werden. Stattdessen werden die Gutschriften direkt vollständig und korrekt gemäß VCS-Bericht importiert und die externe Gutschriftennummer ergänzt bzw. das interne Gutschriftendokument erzeugt und zu Amazon hochgeladen.
+
Es wird natürlich weiterhin vorab geprüft, ob die Gutschrift bereits existiert, weil sie bereits automatisch importiert oder manuell erzeugt wurde. Die Kriterien zur Zuordnung bleiben dabei unverändert, außer dass nach der ersten Zuordnung die Transaktions-ID an der Gutschrift gespeichert wird, um die nächste Zuordnung zu vereinfachen (Order Property Type 79). Falls eine Gutschrift bereits existiert, wird dann nur die Gutschrift korrigiert, wenn eine Abweichung zu den Berichtsdaten vorliegt.
+
[IMPORTANT]
.Achtung!
======
Eine Gutschrift wird nicht importiert, wenn der entsprechende Auftrag nicht zugeordnet werden konnte. Folgende Voraussetzungen müssen für eine Zuordnung gegeben sein:

. Der ursprüngliche Auftrag muss importiert sein und die Auftragsnummer von Amazon als externe Auftragsnummer hinterlegt sein.
. Nur bei FBA-Aufträgen: Der Standort des Auftragslagers muss mit dem Versandland aus dem VCS-Bericht übereinstimmen.
. Die Auftragsartikel müssen anhand einer ID oder SKU aus dem VCS-Bericht zuzuordnen sein.
* Bei VCS Amazon wird anhand der SKU zugeordnet:
** Dem Auftragsartikel ist eine Variante zugeordnet, die eine SKU oder zusätzliche SKU für Amazon hat, die der SKU aus dem Bericht entspricht.
** Der Auftragsartikel wurde nicht zugeordnet, aber im Artikelnamen steht die SKU in eckigen Klammern zu Beginn, z.B. `[02040040-M2_py_sc] Toller Artikelname`.
* Bei VCS Lite/ VCS plentymarkets wird anhand der Externen Auftragsartikel-ID (Order Property Type 17) zugeordnet, die am Auftrag vorliegen muss.
. Die Aufträge müssen eine ausreichende Menge der Artikel aufweisen, damit eine Gutschrift möglich ist. Dabei wird ebenfalls berücksichtigt, ob bereits Gutschriften erzeugt werden.

*Beispiel für Punkt 4:*
Daten aus dem Bericht: SKU 1234, Menge 2

Fälle:

. Auftrag mit SKU 1234, Menge 1 => Keine Zuordnung
. Auftrag mit SKU 1234, Menge 2 => Zuordnung
. Auftrag mit SKU 1234, Menge 2 und bereits exitsierende Gutschrift für Menge 1 => keine Zuordnung
. Auftrag mit SKU 1234, Menge 3 und bereits exitsierende Gutschrift für Menge 1 => Zuordnung
======

[discrete]
=== eBay

* Die Preise für das automatische annehmen bzw. ablehnen eines Preisvorschlags werden im Listing nicht mehr in jedem Fall in Euro angegeben. Ab jetzt muss der Preis in der Währung eingegeben werden, die für die eBay-Plattform gilt. Zuvor konnte es durch die Umwandlung vom Euro-Preis zum Plattform-Preis zu Rundungen kommen, die teilweise nicht den gewünschten Wert an eBay übermittelt haben.
+
[IMPORTANT]
.To-Do
======
Im Zuge des Updates musst du folgende Schritte durchführen:

. Schaue nach bei welchen internationalen Listings du einen Preisvorschlag anbietest.
. Korrigiere den Preis für das automatische annehmen/ablehnen auf den Wert für die entsprechende Währung.
. Aktualisiere diese Listings mit der Option *Menge, Preis und Varianten*.
======

[discrete]
=== Listings

* Die Werte für die Dauer werden nun in Abhängigkeit vom Listing-Typ und Listing-Marktplatz angezeigt. Vorher wurden immer alle Werte angezeigt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *early* behoben.

[discrete]
=== Aufträge

* Wenn Kontaktinformationen geändert wurden, wurde diese Änderungen nur dann in einer Nachbestellung übernommen, wenn man die Seite aktualisiert hat. Dies wurde nun behoben, die geänderten Daten werden automatisch übernommen.
* In den Breadcrumbs in der Nachbestellung wurde der gleiche Auftrag manchmal zweimal angezeigt, wodurch zwei gleiche Einträge in den *Details* entstanden sind. Dies wurde nun behoben.

[discrete]
=== Ereignisaktionen
* Das Ereignis *Paketnummer* löst nun nicht mehr aus, wenn alle Pakete entfernt werden.
* Das Ereignis *Paketnummer* löst nun nicht mehr doppelt aus.


--

early::
+
--

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *early* veröffentlicht.

[discrete]
=== Amazon

* Der neue Gutschriftenimport für VCS kann nun auch:
** Gutschriften erzeugen, in denen nur Versandkosten erstattet werden.
** Für VCS Amazon interne Gutschriftendokumente erzeugen, für den Fall, dass Amazon in seinen VCS-Bericht keine Gutschriftennummer bereitstellt, weil Amazon dies bei bestimmten Konstellationen nicht muss.

[discrete]
=== Ticketsystem

* Wir haben im Menü *Einrichtung » CRM » Ticketsystem » Ereignisse* die Ereignisaktion *Neue Nachricht vom Mitarbeiter* erweitert:
** Der Filter *Gastbestellung* wurde hinzugefügt.
** In der Aktion *E-Mail versenden* wurde in der Dropdown-Liste die Einstellung *Rechnungsadresse - Auftrag* hinzugefügt, damit die E-Mail an die Rechnungsadresse aus dem Auftrag gesendet wird.
** Außerdem wurde in der Aktion *E-Mail versenden* die Einstellung *der Kunde* umbenannt in *Kontakt (CRM)*.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *early* veröffentlicht.

[discrete]
=== Amazon

* Wenn die folgenden zwei Optionen entweder über die Einstellungen oder den Assistenten beide aktiviert sind, werden Gutschriften nicht mehr über die Finances API importiert, sondern über die entsprechenden Berichte für VCS bzw. VCS Lite.
** Über die Einstellungen (*Einrichtung » Märkte » Amazon » Einstellungen » _Konto öffnen_*):
. Option *Rechnung erzeugen* mit der Auswahl _VCS Amazon_ oder _VCS plentymarkets_ unter *Tab: Einstellungen » Bereich: Basiseinstellungen*
. Option *Gutschriftenimport* unter *Einrichtung » Märkte » Amazon » Einstellungen » _Konto öffnen_ » Tab: Auftragseinstellungen » Bereich: Eigener Versand (MFN)*
** Über den Assistenten (*Einrichtung » Assistenten » Omni-Channel » Amazon Grundeinstellungen » _Konto öffnen_*):
. Option *Wer soll Rechnungen für Amazon-Bestellungen erzeugen?* mit der Auswahl _Amazon-Rechnungsservice_ oder _plentymarkets Rechnungsservice_ mit Daten von Amazon im Schritt *Automatische Datenübertragung*.
. Option *Möchtest du FBA-Gutschriften in plentymarkets importieren?* im Schritt *Versand durch Amazon (FBA)*.

+
Das bedeutet, dass die Gutschriften nicht mehr erst über die Finances API importiert und dann im Nachgang korrigiert werden. Stattdessen werden die Gutschriften direkt vollständig und korrekt gemäß VCS-Bericht importiert und die externe Gutschriftennummer ergänzt bzw. das interne Gutschriftendokument erzeugt und zu Amazon hochgeladen.
+
Es wird natürlich weiterhin vorab geprüft, ob die Gutschrift bereits existiert, weil sie bereits automatisch importiert oder manuell erzeugt wurde. Die Kriterien zur Zuordnung bleiben dabei unverändert, außer dass nach der ersten Zuordnung die Transaktions-ID an der Gutschrift gespeichert wird, um die nächste Zuordnung zu vereinfachen (Order Property Type 79). Falls eine Gutschrift bereits existiert, wird dann nur die Gutschrift korrigiert, wenn eine Abweichung zu den Berichtsdaten vorliegt.
+
[IMPORTANT]
.Achtung!
======
Eine Gutschrift wird nicht importiert, wenn der entsprechende Auftrag nicht zugeordnet werden konnte. Folgende Voraussetzungen müssen für eine Zuordnung gegeben sein:

. Der ursprüngliche Auftrag muss importiert sein und die Auftragsnummer von Amazon als externe Auftragsnummer hinterlegt sein.
. Nur bei FBA-Aufträgen: Der Standort des Auftragslagers muss mit dem Versandland aus dem VCS-Bericht übereinstimmen.
. Die Auftragsartikel müssen anhand einer ID oder SKU aus dem VCS-Bericht zuzuordnen sein.
* Bei VCS Amazon wird anhand der SKU zugeordnet:
** Dem Auftragsartikel ist eine Variante zugeordnet, die eine SKU oder zusätzliche SKU für Amazon hat, die der SKU aus dem Bericht entspricht.
** Der Auftragsartikel wurde nicht zugeordnet, aber im Artikelnamen steht die SKU in eckigen Klammern zu Beginn, z.B. `[02040040-M2_py_sc] Toller Artikelname`.
* Bei VCS Lite/ VCS plentymarkets wird anhand der Externen Auftragsartikel-ID (Order Property Type 17) zugeordnet, die am Auftrag vorliegen muss.
. Die Aufträge müssen eine ausreichende Menge der Artikel aufweisen, damit eine Gutschrift möglich ist. Dabei wird ebenfalls berücksichtigt, ob bereits Gutschriften erzeugt werden.

*Beispiel für Punkt 4:*
Daten aus dem Bericht: SKU 1234, Menge 2

Fälle:

. Auftrag mit SKU 1234, Menge 1 => Keine Zuordnung
. Auftrag mit SKU 1234, Menge 2 => Zuordnung
. Auftrag mit SKU 1234, Menge 2 und bereits exitsierende Gutschrift für Menge 1 => keine Zuordnung
. Auftrag mit SKU 1234, Menge 3 und bereits exitsierende Gutschrift für Menge 1 => Zuordnung
======

[discrete]
=== eBay

* Die Preise für das automatische annehmen bzw. ablehnen eines Preisvorschlags werden im Listing nicht mehr in jedem Fall in Euro angegeben. Ab jetzt muss der Preis in der Währung eingegeben werden, die für die eBay-Plattform gilt. Zuvor konnte es durch die Umwandlung vom Euro-Preis zum Plattform-Preis zu Rundungen kommen, die teilweise nicht den gewünschten Wert an eBay übermittelt haben.
+
[IMPORTANT]
.To-Do
======
Im Zuge des Updates musst du folgende Schritte durchführen:

. Schaue nach bei welchen internationalen Listings du einen Preisvorschlag anbietest.
. Korrigiere den Preis für das automatische annehmen/ablehnen auf den Wert für die entsprechende Währung.
. Aktualisiere diese Listings mit der Option *Menge, Preis und Varianten*.
======

[discrete]
=== Listings

* Die Werte für die Dauer werden nun in Abhängigkeit vom Listing-Typ und Listing-Marktplatz angezeigt. Vorher wurden immer alle Werte angezeigt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *early* behoben.

[discrete]
=== Aufträge

* Wenn Kontaktinformationen geändert wurden, wurde diese Änderungen nur dann in einer Nachbestellung übernommen, wenn man die Seite aktualisiert hat. Dies wurde nun behoben, die geänderten Daten werden automatisch übernommen.
* In den Breadcrumbs in der Nachbestellung wurde der gleiche Auftrag manchmal zweimal angezeigt, wodurch zwei gleiche Einträge in den *Details* entstanden sind. Dies wurde nun behoben.

[discrete]
=== Ereignisaktionen
* Das Ereignis *Paketnummer* löst nun nicht mehr aus, wenn alle Pakete entfernt werden.
* Das Ereignis *Paketnummer* löst nun nicht mehr doppelt aus.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name
|Version
|To-do

|link:https://marketplace.plentymarkets.com/backmarket_6485[Backmarket^]
|1.0.10
|-

|link:https://marketplace.plentymarkets.com/payuponpickup_4757[Barzahlung^]
|2.0.2
|-

|link:https://marketplace.plentymarkets.com/d2gpmplugincoronavat_6846[Ceres Corona VAT 2020 Plugin^]
|1.0.0
|-

|link:https://marketplace.plentymarkets.com/dpdshippinguk_5121[DPD Shipping UK^]
|2.0.1
|-

|link:https://marketplace.plentymarkets.com/gaxsys_5992[gaxsys Connector^]
|2.2.1
|-

|link:https://marketplace.plentymarkets.com/reviewconverter_6843[Google Shopping Produktbewertungen (Sterne)^]
|1.0.1
|-

|link:https://marketplace.plentymarkets.com/cfourhtmlwidget_6845[HTML Widget]
|1.0.1
|-

|link:https://marketplace.plentymarkets.com/wesiocatalog_6759[Kataloggenerator - Kataloge schnell und einfach erstellen^]
|1.0.1
|-

|link:https://marketplace.plentymarkets.com/parceloneshipping_6277[ParcelOne Shipping^]
|1.0.7
|-

|link:https://marketplace.plentymarkets.com/payever_5623[Payever^]
|1.9.0
|-

|link:https://marketplace.plentymarkets.com/trustedshops_4962[Trusted Shops Reviews Toolkit^]
|2.0.1
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^]{nbsp}icon:external-link[].
--

====
