= plentymarkets Changelog
:lang: de
include::{includedir}/_header.adoc[]
:author: kevin-stederoth
:sectnums!:
:position: 10150
:url: changelog
:id:
:startWeekDate: 09. September 2021
:endWeekDate: 15. September 2021
:nav-alias: Changelog 15. September 2021

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Woche für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite <<business-entscheidungen/systemadministration/versionszyklus#, Versionszyklus>>. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^]{nbsp}icon:external-link[].

Wähle, welchen Changelog du sehen möchtest.

[.tabs]
====
stable::
+

--

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *stable* veröffentlicht.

[discrete]
=== Aufträge

* Zu den Standardeinstellungen für die neue Auftragsanlage (Beta) wurde eine neue Einstellung für Auftragsvorlagen hinzugefügt. Im Menü *Einrichtung » Aufträge » Auftragstypen » Auftrag [Beta]* kannst du eine Standard-Auftragsvorlage definieren, die immer auf einen neuen Auftrag angewendet wird.

* Im Menü *Aufträge » Neue Zahlungen (Testphase)* wurde die neue Komponente *Filter bookmarks* hinzugefügt. Diese Komponente ermöglicht das Speichern und Wiederverwenden von Filtern direkt im Menü.

[discrete]
=== plentyBI

* Die Funktionalität *Dimension* kann jetzt auch in Tortendiagrammen verwendet werden.

* Es wurden für jeden Graphen, für jede Kachel und für jede Tabelle welche neu in ein Dashboard gezogen wird die gängigsten Standardeinstellungen hinterlegt. Dies erlaubt ein schnelleres Vorankommen bei der Neuanlage eines Dashboards. Selbstverständlich können die Einstellungen manuell angepasst werden.

* In der Kennzahlen-Übersicht wurde eine neue Spalte hinzugefügt, welche visualisiert ob eine Kennzahl kostenpflichtig ist oder nicht.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *stable* veröffentlicht.

[discrete]
=== Aufträge

* In der Auftrags-UI lässt sich nun auch das Adressfeld 4 (`address4`) editieren.

[discrete]
=== plentyBI

* In der Komponente *Globales Zeitintervall* gab es kleinere Änderungen. Die Überschrift sowie die Funktionalität zum Ein- und Ausklappen wurden ausgebaut. Desweiteren wurde das Styling so angepasst, das die Komponenten jetzt deutlich weniger Platz einnimmt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *stable* behoben.

[discrete]
=== Aufträge

* Beim manuellen Eintragen von Daten in einem Datumsfeld in der Nachbestellung wurde das falsche Format vorgegeben. Dies wurde behoben. Statt mm.dd.yyyy wird nun wieder korrekt dd.mm.yyyy übernommen.

* Die folgenden Fehler in den Eigenschaften an Auftragspositionen wurden in der neuen Auftragsanlage (Beta) und den Abonnements behoben:

** Duplizierte Aufrufe und Einträge von Eigenschaften an Auftragspositionen wurden behoben.
** Die zweite Zeilenebene der Tabelle war nicht korrekt.

* In der neuen Auftragsanlage (Testphase) konnten keine Auftragsvorlagen ausgewählt werden. Dies ist nun behoben.

* Nur die erste Umbuchung, die geöffnet wird, wurde korrekt geladen. Für alle weiteren Umbuchung konnten die Daten nicht korrekt gesetzt werden. Dies wurde behoben, alle Umbuchungen werden wieder korrekt geladen.

* Es konnte vorkommen, dass bei der Auftragsanlage der Eigner nicht korrekt ermittelt wurde. Dieses Verhalten wurde behoben.

* Beim Import konnte es zu Problemen beim Setzen des Versandprofils kommen.

[discrete]
=== CRM

* Wenn bei einer Benutzerrolle nur die Berechtigung *CRM > Kampagne > Anzeigen* aktiviert war, konnte diese Rolle trotzdem Gutscheincodes erstellen, Gutscheinen Kampagnen zuweisen, Gutscheine bearbeiten und Gutscheine aktivieren und deaktivieren. Dieses Verhalten wurde behoben.

[discrete]
=== plentyBI

* Es wurde ein Problem behoben, welches bei englischsprachigen System auftreten konnte. Die Legende von Graphen interpretiert Tausender- und Dezimaltrennzeichen jetzt korrekt.

* In der Benutzeroberfläche *Rohdaten* gab es ein Problem bei der Paginierung. Dieses wurde behoben und man kann nun wie gewollt sämtliche Seiten durchlaufen.


--

early::
+
--

[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *early* veröffentlicht.

[discrete]
=== Aufträge

* Im Menü *Aufträge » Abonnements (Testphase)* sowie in der Artikelsuche von Abonnements wurde die neue Komponente *Filter bookmarks* hinzugefügt. Diese Komponente ermöglicht das Speichern und Wiederverwenden von Filtern direkt im Menü.

* Im Menü *Waren » Bestellung » Umbuchung* wurde die neue Komponente *Filter bookmarks* hinzugefügt. Diese Komponente ermöglicht das Speichern und Wiederverwenden von Filtern direkt im Menü.

* Die neue Komponente *Filter bookmarks* wurde in der Artikelsuche in der neuen Auftragsanlage (Testphase) hinzugefügt. Diese Komponente ermöglicht das Speichern und Wiederverwenden von Filtern direkt im Menü.

* In der Auftragsübersicht der Nachbestellungen und Umbuchungen wurde die alte Filterkomponente durch die neue ersetzt.

[discrete]
=== CRM

* Im EmailBuilder wurde die Variantennummer im Widget *Auftragspositionen* hinzugefügt. Du kannst die Variantennummer nun also in den Einstellungen des Widgets wählen, sodass diese in der Tabelle des Widgets angezeigt wird.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *early* behoben.

[discrete]
=== CRM

* Im Auftrag im Tab *Mail > E-Mail-Vorlagen > E-Mail-Vorlagen anderer Benutzer* wurde in der Vorschau in manchen Fällen der falsche Titel in der Vorlage angezeigt. Dieses Verhalten wurde behoben.

* Neue E-Mail-Vorlagen, die im EmailBuilder erstellt wurden, konnten nicht aus der Nachbestellungs-UI über den E-Mail-Service versendet werden. Dieses Verhalten wurde behoben.

[discrete]
=== Prozesse

* Noch offenen Lieferaufträgen wurde nach dem Teilen von Aufträgen in der Artikelerfassung innerhalb der Prozesse kein neuer Status zugeordnet. Dieses Verhalten wurde behoben.


--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name |Version |To-do

|link:https://marketplace.plentymarkets.com/rewe_5901[REWE^]
|1.26.4
|-

|link:https://marketplace.plentymarkets.com/plugins/sales/berichte-analysen/econdatagmanager-47820_54876[econda Tag Manager^]
|6
|-

|link:https://marketplace.plentymarkets.com/ebaymarketing_5158[eBay Marketing^]
|1.0.8
|-

|link:https://marketplace.plentymarkets.com/shopify_4944[Shopify.com^]
|2.9.9
|-

|link:https://marketplace.plentymarkets.com/woocommerce_5102[woocommerce.com^]
|2.9.2
|-

|link:https://marketplace.plentymarkets.com/ebayreviewwidget_54926[eBay Review Widget - echte Bewertungen von echten Käufern präsentieren^]
|1.0.1
|-

|link:https://marketplace.plentymarkets.com/hermesshippinginterface_5437[Hermes^]
|1.0.20
|-

|link:https://marketplace.plentymarkets.com/plugins/sales/berichte-analysen/econdausabilityanalytics-47820_54860[econda Usability Analytics^]
|5
|-

|link:https://marketplace.plentymarkets.com/plugins/sales/berichte-analysen/econdaaudiencerelationshipplatform-47820_54871[econda Audience Relationship Platform^]
|4
|-

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/rechtliches/econdaprivacyprotection-47820_54875[econda Privacy Protection^]
|3
|-

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/widgets/econdacrosssell-47820_54870[econda Cross Sell^]
|3
|-

|link:https://marketplace.plentymarkets.com/plugins/sales/berichte-analysen/econdaanalytics-47820_54861[econda Analytics^]
|3
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^]{nbsp}icon:external-link[].

--

plentymarkets App::
+
--
App-Update 1.11.20: Anfang der Kalenderwoche 37 veröffentlichen wir die Version 1.11.20 der plentymarkets App für Android im PlayStore.

[discrete]
== Behoben

* v.1.11.20: Bei einigen Android-Versionen verursachte die Version 1.11.18 Probleme bzgl. der Kommunikation mit TSE und/oder plentyBase. Dieses Verhalten sollte mit der Version 1.11.20 behoben sein.
--

====
