= plentymarkets Changelog
:lang: de
include::{includedir}/_header.adoc[]
:sectnums!:
:position: 150
:url: changelog
:id: 
:nav-alias: Changelog 29. Januar 2020

Erfahre, was sich diese Woche bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Wochen für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite <<basics/admin-aufgaben/versionszyklus#, Versionszyklus>>.

== stable

In diesem Bereich findest du alles, was in der letzten Woche auf *stable* veröffentlicht wurde.

=== Geändert

[discrete]
==== Benutzerrechte Listings

* Damit Variable Nutzer ein Listing anlegen können, müssen sie nun die Rechte *Listing erstellen* und *Market-Listing erstellen* erhalten.

[discrete]
==== plentymarkets System

* Es ist uns gelungen, die Ladezeit des Backends nach dem Anmelden um 58% zu reduzieren.

== early

In diesem Bereich findest du alles, was in der letzten Woche auf *early* veröffentlicht wurde.

==== Neu

==== Geändert

==== Behoben

==== Gelöscht

== Plugin-Updates

Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name
|Version
|To-do

|link:https://marketplace.plentymarkets.com/plugins/integration/addresscheckpro_6432[AddressCheck Pro^]
|1.0.8
|-

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/widgets/customforms_6318[Benutzerdefinierte Formulare^]
|1.0.6
|-

|link:https://marketplace.plentymarkets.com/plugins/sales/online-shops/io_4696[IO^]
|4.5.1
|-

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/widgets/cfourproductwall_5762[Produktwand Widget^]
|1.0.6
|-

|link:https://marketplace.plentymarkets.com/plugins/individualisierung/widgets/staticpagesmapper_6371[Statische Seiten im ShopBuilder]
|1.0.3
|-

|===
