= plentymarkets Changelog
:lang: de
include::{includedir}/_header.adoc[]
:author: kevin-stederoth
:sectnums!:
:position: 150
:url: changelog
:id:
:startWeekDate: 16. November 2020
:endWeekDate: 02. Dezember 2020
:nav-alias: Changelog 02. Dezember 2020

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Wochen für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite <<business-entscheidungen/systemadministration/versionszyklus#, Versionszyklus>>. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^]{nbsp}icon:external-link[].

Wähle, welchen Changelog du sehen möchtest.

[.tabs]
====
stable::
+

--

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *stable* veröffentlicht.

[discrete]
=== Kataloge

* Bis die neue Filterkomponente eingebaut werden kann, haben wir vorübergehend den alten Filter wieder eingebaut.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *stable* behoben.

[discrete]
=== Aufträge

* Der Zahlungsstatus von Gutschriften in Fremdwährung wurde bei der Zahlungszuordnung nicht korrekt ermittelt. Dies wurde nun entsprechend für alle neuen Zuordnungen angepasst.
+

[IMPORTANT]
.To-Do
======
Gutschriften mit bereits zugeordneten Zahlungen werden nicht korrigiert. Bei Bedarf kann die Zuordnung gelöst und die Zahlung neu zugeordnet werden.
======
* Es wurden die Auftragssummen teilweise nicht richtig berechnet. Der Fehler ist nur in Beta/Early aufgetreten.
* Beim Erstellen von Adressetiketten bei Aufträgen mit Set-Artikeln kam es zur Fehlermeldung `missing warehouseId` (fehlende Lagerangabe). Das wurde behoben.
* Es konnten die Adressdaten von gesperrten Aufträgen nicht mehr geändert werden. Der Fehler ist nur auf Beta/Early aufgetreten.

--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name
|Version
|To-do

|link:https://marketplace.plentymarkets.com/conradextension_6948[Conrad^]
|1.1.2
|-

|link:https://marketplace.plentymarkets.com/feed4ceresaccountpacktwo_6992[Feed4CeresAccountPackTwo^]
|1.0.0
|-

|link:https://marketplace.plentymarkets.com/cfourgoogletagmanager5_6984[Google Tag Manager 5^]
|2.1.0
|-

|link:https://marketplace.plentymarkets.com/groupon_4878[Groupon^]
|1.1.5
|-

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^]{nbsp}icon:external-link[].

--

====
