= plentymarkets Changelog
:lang: de
include::{includedir}/_header.adoc[]
:author: kevin-stederoth
:sectnums!:
:position: 150
:url: changelog
:id:
:startWeekDate: 16. April 2020
:endWeekDate: 22. April 2020
:nav-alias: Changelog 22. April 2020

Erfahre, was sich in der Woche vom {startWeekDate} bis zum {endWeekDate} bei plentymarkets getan hat. Im Folgenden findest du alle Changelog-Einträge der letzten Wochen für stable- und early-Systeme.

Wenn du mehr zu den einzelnen Versionen erfahren oder auf eine andere Version wechseln möchtest, siehe die Handbuchseite <<basics/admin-aufgaben/versionszyklus#, Versionszyklus>>. Um die Informationen, die auf dieser Seite gesammelt sind, in Echtzeit zu erhalten, abonniere die link:https://forum.plentymarkets.com/c/changelog[Kategorie Changelog in unserem Forum^].

Wähle, welchen Changelog du sehen möchtest.

[.tabs]
====
stable::
+
--
[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *stable* veröffentlicht.

[discrete]
=== Aufträge

* In der Auftragsübersicht unter dem Tab *Einstellungen* wurde das Feld für die Paketnummern überarbeitet. Es ist nun möglich, Pakete direkt aus der UI heraus anzulegen.

[discrete]
=== Import

* Ab sofort wird der Status des jeweiligen Imports direkt angezeigt.

[discrete]
=== Nachbestellungen

* Bei der UI der Nachbestellung wird nun die Währung die am Lieferanten hinterlegt ist vorausgewählt. Diese Währung wird im Kontakt im Bereich *Firma* hinterlegt.
* Bei dem Hinzufügen von Positionen in der Nachbestellungs-UI wird der *EK in Bestellwährung* von der Verknüpfung Variation/Lieferant genutzt.
* Bei der UI der Nachbestellung gibt es nun die Möglichkeit alle offenen Mengen auf einmal zu stornieren.

'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *stable* veröffentlicht.

[discrete]
=== Aufträge

* In der Anzeige der Auftragssumme in der Auftragssuche werden stornierte Gutschriften (im Statusbereich 8) nicht mehr berücksichtigt.

[discrete]
=== Elastischer Export

* Aufgrund mehrerer Fehlverhalten bei den Importformaten *Stock* und *Warehouse*, mussten wir für diese Formate, das Limit wieder auf 10.000 setzen. Ihr könnt weiterhin diese Exporte in 6000er Schritten über den Dynamischen Export ziehen.

[discrete]
=== Paketnummern

* Paketnummern wurden bisher in verschiedenen Tabellen gespeichert. Dies hatte zur Folge, dass beispielsweise im elastischen Export teilweise Paketnummern nicht enthalten waren. Dies wurde nun vereinheitlicht, in dem aus allen Bereichen die Paketnummern nur noch in eine Tabelle geschrieben werden. In dem Zusammenhang wird eine Migration durchgeführt, welche die Paketnummern der letzten 6 Monate aus der alten Tabelle in die neue überführt.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *stable* behoben.

[discrete]
=== Import

* Aufgrund eines Fehlers funktionierten die Filter mit dem Operator Oder nicht. Diesen Fehler haben wir behoben.

[discrete]
=== Nachbestellungen

* In der UI der Nachbestellung, ist es durch mehrfaches Klicken auf die Schaltfläche *Vollständige Lieferung anlegen* dazu gekommen, dass Warenbewegungen mehrfach angelegt wurden. Dieses Verhalten wurde korrigiert.

--

early::
+
--
[discrete]
== Neu

Folgende Neuerungen wurden in den letzten 7 Tagen auf *early* veröffentlicht.



'''

[discrete]
== Geändert

Folgende Änderungen wurden in den letzten 7 Tagen auf *early* veröffentlicht.

'''

[discrete]
== Behoben

Folgende Probleme wurden in den letzten 7 Tagen auf *early* behoben.



--

Plugin-Updates::
+
--
Folgende Plugins wurden in den letzten 7 Tagen in einer neuen Version auf plentyMarketplace veröffentlicht:

.Plugin-Updates
[cols="2, 1, 2"]
|===
|Plugin-Name
|Version
|To-do

|link:https://marketplace.plentymarkets.com/plugins/sales/online-shops/ceres_4697[Ceres]
|5.0.1
|Aufgrund von Änderungen an bestehenden Widgets müssen die ShopBuilder-Inhalte im Menü *CMS » ShopBuilder* über die Schaltfläche Inhalte neu generieren aktualisiert werden.

|===

Wenn du dir weitere neue oder aktualisierte Plugins anschauen möchtest, findest du eine link:https://marketplace.plentymarkets.com/plugins?sorting=variation.createdAt_desc&page=1&items=50[Übersicht direkt auf plentyMarketplace^].
--
====
