= CMS
:lang: de
include::{includedir}/_header.adoc[]
:position: 150

**plentymarkets » CMS**

== Inhalt dieses Kapitels

In diesem Kapitel erhalten Sie einen Überblick darüber, wie Sie Ihren Webshop gestalten und das Design nach Ihren Vorstellungen verändern können. Erläuterungen dazu finden Sie im Kapitel <<cms/webdesign#, **Webdesign**  >>. +
Weiterhin wird die Verwendung der <<cms/bilder-galerie#, **Bilder-Galerie**  >> erklärt. In die Bilder-Galerie laden Sie Bilder, die in Ihrem Webshop angezeigt werden sollen. Diese können Sie dort in Ordnern strukturiert verwalten.

Mit dem **<<cms/webspace#, Webspace  >>-Tool** hinterlegen Sie u.a. die Elemente für Ihr Design, z.B. Bilder, Logos oder JavaScript-Dateien. Diese verwalten Sie dort auf Datei-Ebene.

Eine weitere Möglichkeit, Ihren Kunden Dateien zur Verfügung zu stellen, wird auf der Seite <<cms/dokumente#, **Dokumente**  >> erklärt. Hier erfahren Sie, wie Sie Dokumente per Upload hinterlegen, die dann für den Versand per E-Mail zur Verfügung stehen.

Wenn Sie in Ihrem Onlineshop einen <<cms/blog-weblog#, **Blog**  >> einrichten möchten, erhalten Sie auf der Seite Blog die nötigen Informationen.

Die Seite <<cms/faq#, **FAQ**  >> zeigt Ihnen die Einrichtung eines Bereichs in Ihrem Webshop, der __**Frequently Asked Questions**__, häufig gestellte Fragen, beantwortet.

Die Konfiguration von <<crm/newsletter-versenden#, **Newslettern**  >>, die Sie automatisch versenden und mit denen Sie viele potentielle Käufer erreichen können, erklären wir Ihnen ebenfalls in diesem Kapitel.

== Webdesign in plentymarkets

Sie lernen, mit dem integrierten __**Content-Management-System**__ zu arbeiten und damit Inhalte, wie z.B verschiedene **Templates**, anzupassen, die das Design Ihres Onlineshops bestimmen. Außerdem erfahren Sie, wie Sie mit Platzhaltern verschiedene Inhalte in Ihren Webshop einfügen, die dann dynamisch angepasst werden. Dazu gehört z.B. die Anzeige von Preisen und Verfügbarkeiten. Mit <<cms-syntax/grundlagen/if#, **if-Abfragen**  >> fügen Sie Fallunterscheidungen nach dem Wenn-dann-Prinzip ein und steuern Aktionen anhand von Bedingungen.

Mit**CSS** steuern Sie übergreifende Formatierungen und können Anpassungen Ihrer Styles mit wenigen Mausklicks durchführen.

Weitere Details zum Thema erhalten Sie auf der Handbuchseite <<cms/webdesign#, **Webdesign**  >>.

== Videotutorials

Erfahren Sie mehr zum Menü **CMS** im folgenden Videotutorial:

[.linkBox]
link:https://www.plentymarkets.eu/a-3129/[CMS, window="_blank"]

== Wichtige Seiten zum Thema direkt aufrufen

* <<cms/webdesign#, **Webdesign**  >>
* <<cms/webdesign/benutzeroberflaeche#, **Benutzeroberfläche**  >>
* <<cms/webdesign/syntax#, **Grundlagen der Syntax**  >>
* <<cms-syntax/grundlagen/if#, **if-Abfragen**  >>
* <<cms/webdesign/syntax/listendarstellung#, **Listendarstellung**  >>
* **<<cms/webdesign/webdesign-bearbeiten#, Webdesign bearbeiten  >>**
* <<cms/best-practice/ssl-verschluesselung#, **SSL-Verschlüsselung**  >>
* <<cms-syntax/webdesign/pagedesign/link-ajaxbasket#, **Warenkorb per Ajax**  >>

