= CRM
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kundendaten verwalten, Ticketsystem nutzen, E-Mails versenden, Newsletter versenden
:description: Erfahren Sie, wie Sie Kundendaten verwalten, das Ticketsystem für Ihre Kundenkommunikation nutzen und E-Mails und Newsletter versenden.
:position: 60
:nav-alias: Übersicht

In diesem Themenbereich finden Sie alle Informationen zum Erstellen und Bearbeiten von <<crm/kundendaten-verwalten#800, **Kundendatensätzen**>> - von der Anschrift über Aufträge bis hin zu Tickets, Dokumenten, <<basics/statistik/kundenstatistiken#, **Statistiken**>> u.v.m. Erstellen Sie <<crm/kundendaten-verwalten#100, **Kundenklassen**>>, <<crm/kundendaten-verwalten#300, **Kundentypen**>> und nutzen Sie das <<crm/kundendaten-verwalten#3900, **Rabattsystem**>> in plentymarkets.

Erfahren Sie außerdem, wie Sie das <<crm/ticketsystem-nutzen#, **Ticketsystem**>> für Ihre Kundenkommunikation nutzen und wie Sie mit Hilfe der <<crm/kundendaten-verwalten#3600, **OP-Liste**>> die Kontrolle über noch unbezahlte Aufträge behalten.

Alle E-Mails, die über plentymarkets versendet werden, basieren auf E-Mail-Vorlagen. Für alle E-Mail-Vorlagen können Sie bis zu zwei Anhänge definieren. Erfahren Sie in diesem Themenbereich, wie Sie <<crm/e-mails-versenden#1200, **E-Mail-Vorlagen erstellen**>>.

Richten Sie einen <<crm/newsletter-versenden#, **Newsletter**>> ein, um Ihre Kunden in regelmäßigen Abständen über Neuerungen in Ihrem Webshop zu informieren. Zu diesem Zweck steht Ihnen ein in plentymarkets integrierter Newsletter zur Verfügung oder Sie richten die Schnittstelle zu <<crm/newsletter-versenden#1700, **CleverReach**>> oder <<crm/newsletter-versenden#2100, **Newsletter2Go**>> ein.

Erfahren Sie mehr über den Bereich der Kundendaten, das Ticketsystem und E-Mail-Vorlagen in den folgenden Videotutorials:

[.row]
====
[.col-md-6]
=====
video::108555145[vimeo]
=====

[.col-md-6]
=====
video::62027532[vimeo]
=====
====
video::78421965[vimeo]

[.row]
====
[.col-md-6]
.Kundendaten verwalten
=====
* <<crm/kundendaten-verwalten#100, **Kundenklasse erstellen**>>
* <<crm/kundendaten-verwalten#300, **Kundentyp erstellen**>>
* <<crm/kundendaten-verwalten#800, **Kundendatensatz erstellen**>>
* <<crm/kundendaten-verwalten#3600, **Offene Posten anzeigen**>>
* <<crm/kundendaten-verwalten#3900, **Rabattsystem nutzen**>>
=====

[.col-md-6]
.Ticketsystem nutzen
=====
* <<crm/ticketsystem-nutzen#700, **Rolle hinzufügen**>>
* <<crm/ticketsystem-nutzen#800, **Typ hinzufügen**>>
* <<crm/ticketsystem-nutzen#900, **Status hinzufügen**>>
* <<crm/ticketsystem-nutzen#1100, **Thema hinzufügen**>>
* <<crm/ticketsystem-nutzen#1600, **Ticket erstellen**>>
=====
====

[.row]
====
[.col-md-6]
.E-Mails versenden
=====
* <<crm/e-mails-versenden#100, **E-Mail-Server-Zugangsdaten speichern**>>
* <<crm/e-mails-versenden#200, **Verschlüsselung der E-Mail-Kommunikation wählen**>>
* <<crm/e-mails-versenden#1200, **E-Mail-Vorlage erstellen**>>
* <<crm/e-mails-versenden#1300, **Template-Variablen und Template-Funktionen verwenden**>>
=====

[.col-md-6]
.Newsletter versenden
=====
* <<crm/newsletter-versenden#100, **Internen Newsletter nutzen**>>
* <<crm/newsletter-versenden#2100, **Newsletter2Go nutzen**>>
* <<crm/newsletter-versenden#1700, **CleverReach nutzen**>>
=====
====

'''
