= CRM
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kundendaten verwalten, Ticketsystem nutzen, E-Mails versenden, Newsletter versenden
:description: Erfahren Sie, wie Sie Kundendaten verwalten, das Ticketsystem für Ihre Kundenkommunikation nutzen und E-Mails und Newsletter versenden.
:position: 50
:url: crm
:nav-alias: Übersicht

In diesem Themenbereich finden Sie alle Informationen zum Erstellen und Bearbeiten von <<crm/kontakte-verwalten#100, Kontaktdatensätzen>> - von der Adresse über Aufträge bis hin zu Tickets, Dokumenten u.v.m. Erstellen Sie <<crm/kontakte-verwalten#15, Kundenklassen>>, <<crm/kontakte-verwalten#20, Typen>> und nutzen Sie das <<crm/kontakte-verwalten#25, Rabattsystem>> in plentymarkets.

Erfahren Sie außerdem, wie Sie das <<crm/ticketsystem-nutzen#, Ticketsystem>> für Ihre Kundenkommunikation nutzen und wie Sie mit Hilfe der <<crm/kontakte-verwalten#5200, OP-Liste>> die Kontrolle über noch unbezahlte Aufträge behalten.

Alle E-Mails, die über plentymarkets versendet werden, basieren auf E-Mail-Vorlagen. Für alle E-Mail-Vorlagen können Sie bis zu 2 Anhänge definieren. Erfahren Sie in diesem Themenbereich, wie Sie <<crm/e-mails-versenden#1200, E-Mail-Vorlagen erstellen>>.

Richten Sie einen <<crm/newsletter-versenden#, Newsletter>>-Dienst in Ihrem System ein, um Ihre Kunden in regelmäßigen Abständen automatisch über Neuerungen in Ihrem Webshop zu informieren.


[.col-md-6]
.Kontakte verwalten
=====
* <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>
* <<crm/kontakte-verwalten#20, Typ erstellen>>
* <<crm/kontakte-verwalten#100, Kontakt erstellen>>
* <<crm/kontakte-verwalten#5200, Offene Posten anzeigen>>
* <<crm/kontakte-verwalten#25, Rabattsystem nutzen>>
=====


[.col-md-6]
.Ticketsystem nutzen
=====
* <<crm/ticketsystem-nutzen#700, Rolle hinzufügen>>
* <<crm/ticketsystem-nutzen#800, Typ hinzufügen>>
* <<crm/ticketsystem-nutzen#900, Status hinzufügen>>
* <<crm/ticketsystem-nutzen#1100, Thema hinzufügen>>
* <<crm/ticketsystem-nutzen#1600, Ticket erstellen>>
=====

[.row]

[.col-md-6]
.E-Mails versenden
=====
* <<crm/e-mails-versenden#100, E-Mail-Server-Zugangsdaten speichern>>
* <<crm/e-mails-versenden#200, Verschlüsselung der E-Mail-Kommunikation wählen>>
* <<crm/e-mails-versenden#1200, E-Mail-Vorlage erstellen>>
* <<crm/e-mails-versenden#1300, Template-Variablen und Template-Funktionen verwenden>>
=====

[.col-md-6]
.Newsletter versenden
=====
* <<crm/newsletter-versenden#, Newsletter versenden>>
=====
