= CRM
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kundendaten, Kontaktdaten, Ticketsystem, E-Mails, Emails, EmailBuilder, Newsletter, Schnellsuche, Messenger, Nachrichten, Firmen, Firma
:description: Erfahre, wie du Kontakt- und Firmendaten verwaltest, das Ticketsystem für deine Kundenkommunikation nutzt und E-Mails und Newsletter versendest.
:position: 50
:url: crm
:id: IWIIOPV
:nav-alias: Übersicht
:author: team-crm

In diesem Themenbereich findest du alle Informationen zum Erstellen und Bearbeiten von <<crm/kontakte-verwalten#100, Kontaktdatensätzen>> – von der Adresse über Aufträge bis hin zu Tickets, Dokumenten u.v.m. Erstelle <<crm/kontakte-verwalten#15, Kundenklassen>> und <<crm/kontakte-verwalten#20, Typen>> und nutze das <<crm/kontakte-verwalten#25, Rabattsystem>> in plentymarkets. Verwalte deine <<crm/firmen#, Firmen>> und verknüpfe Kontakte mit den Firmen.

Über die <<crm/schnellsuche#, Schnellsuche>> kannst du alle Informationen eines Kontakts oder die Adressdaten einer Gastbestellung auf einen Blick aufrufen. In diesem Bereich kannst du außerdem DSGVO-gemäß alle Daten zu einem Kontakt oder einer Gastbestellung herunterladen und Datensätze anonymisieren.

Nutze den <<crm/messenger#, Messenger>>, um Nachrichten zu erstellen, die deinen Kontakten zugeordnet werden. Diese Nachrichten sind nur in deinem plentymarkets Backend sichtbar und können nicht von deinen Kontakten aufgerufen werden.

Alle E-Mails, die über plentymarkets versendet werden, basieren auf E-Mail-Vorlagen. Erfahre, wie du <<crm/e-mails-versenden#1200, E-Mail-Vorlagen erstellst>> und wie du den <<crm/e-mails-versenden#2300, automatischen Versand>> für deine E-Mail-Vorlagen einrichtest. Nutze den <<crm/emailbuilder-testphase#, neuen EmailBuilder>>, um deine Vorlagen noch schneller und intuitiver zu erstellen.

Erfahre außerdem, wie du das <<crm/ticketsystem-nutzen#, Ticketsystem>> für deine Kundenkommunikation nutzt und wie du mit Hilfe der <<crm/op-liste#, OP-Liste>> die Kontrolle über noch unbezahlte Aufträge behältst.

Richte einen <<crm/newsletter-versenden#, Newsletter>>-Dienst in deinem System ein, um deine Kund:innen in regelmäßigen Abständen automatisch über Neuerungen in deinem Webshop zu informieren.

[.row]
====
[.col-md-6]
.Kontakte und Firmen verwalten
======
* <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>
* <<crm/kontakte-verwalten#20, Typ erstellen>>
* <<crm/kontakte-verwalten#100, Kontakt erstellen>>
* <<crm/kontakte-verwalten#300, Kontakt bearbeiten>>
* <<crm/kontakte-verwalten#25, Rabattsystem nutzen>>
* <<crm/op-liste#, Offene Posten anzeigen>>
* <<crm/firmen#, Firmen verwalten>>
======

[.col-md-6]
.E-Mails versenden
======
* <<crm/e-mails-versenden#100, E-Mail-Server-Zugangsdaten speichern>>
* <<crm/e-mails-versenden#200, Verschlüsselung der E-Mail-Kommunikation wählen>>
* <<crm/e-mails-versenden#1200, E-Mail-Vorlage erstellen>>
* <<crm/emailbuilder-testphase#, E-Mail-Vorlage mit dem neuen EmailBuilder erstellen>>
======
====

[.row]
====
[.col-md-6]
.Ticketsystem nutzen
======
* <<crm/ticketsystem-nutzen#700, Rolle hinzufügen>>
* <<crm/ticketsystem-nutzen#800, Typ hinzufügen>>
* <<crm/ticketsystem-nutzen#900, Status hinzufügen>>
* <<crm/ticketsystem-nutzen#1100, Thema hinzufügen>>
* <<crm/ticketsystem-nutzen#1600, Ticket erstellen>>
======

[.col-md-6]
.Newsletter einrichten
======
* <<crm/newsletter-versenden#, Newsletter versenden>>
======
====

[.row]
====
[.col-md-6]
.Datensätze finden
======
* <<crm/schnellsuche#, Schnellsuche verwenden>>
======

[.col-md-6]
.Nachrichten verwalten
======
* <<crm/messenger#, Messenger verwenden>>
======
====
