= Datenaustausch
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenaustausch, Datenformate, Datenexport, Datenimport, SOAP-API, REST-API, API-Log
:description: Erfahren Sie, welche Datenformate Sie für den Export und Import nutzen, welche Schnittstellen es gibt und wie Sie Protokolle einsehen.
:position: 90

Dieser Themenbereich befasst sich mit dem Datenaustausch in plentymarkets. Daten können automatisch oder manuell ausgetauscht werden. Für den Austausch von Daten zwischen Ihrem plentymarkets System und externen Systemen stehen Ihnen die **<<datenaustausch/soap-api#, SOAP-API  >>** und Untermenüs im Menü **Datenaustausch** zur Verfügung. Die SOAP-API und die REST-API dienen dem automatischen Datenaustausch. Das Menü **Datenaustausch** dient dem manuellen Austausch von Daten. Im API-Log können Sie anhand von **<<datenaustausch/api-log#, Log-Einträgen  >>** den Datenaustausch nachvollziehen.

video::135966846[vimeo]
Nutzen Sie den Datenaustausch außerdem, um auch systemintern Einstellungen einfach und zeitsparend anzupassen. Einfach Daten zu Artikeln, Kunden, Warenbeständen oder Aufträgen in eine CSV-Datei exportieren, in der Datei anpassen und anschließend importieren.

[.row]
====
[.col-md-4]
.Manueller Datenaustausch
=====
* <<datenaustausch/datenformate#, **Datenformate**  >>
* <<datenaustausch/daten-exportieren#, **Daten exportieren**  >>
* <<datenaustausch/daten-importieren#, **Daten importieren**  >>
=====

[.col-md-4]
.Schnittstellen
=====
* <<datenaustausch/soap-api#, **SOAP-API**  >>
* link:http://showcase.plentymarkets.com/[**REST-API**, window="_blank"]
=====

[.col-md-4]
.Protokolle einsehen
=====
* <<datenaustausch/api-log#, **API-Log**  >>
=====
====
link::/[Zurück zur Übersicht]

