= Daten
:lang: de
include::{includedir}/_header.adoc[]
:position: 90
:nav-alias: Übersicht

Dieser Themenbereich befasst sich mit dem Datenaustausch in plentymarkets. Daten können automatisch oder manuell ausgetauscht werden. Für den Austausch von Daten zwischen Ihrem plentymarkets System und externen Systemen stehen Ihnen die link:https://developers.plentymarkets.com/[REST-API^] und Untermenüs im Menü **Datenaustausch** zur Verfügung. Das Plugin **ElasticSync** dient dem manuellen Austausch von Daten. Im API-Log können Sie anhand von <<basics/datenaustausch/api-log#, Log-Einträgen>> den Datenaustausch nachvollziehen.

Nutzen Sie den Datenaustausch außerdem, um systemintern Einstellungen einfach und zeitsparend anzupassen. Einfach Daten zu Artikeln, Kunden, Warenbeständen oder Aufträgen in eine CSV-Datei exportieren, in der Datei anpassen und anschließend importieren.

[.row]
====
[.col-md-4]
.Datenaustausch
=====
* <<daten/daten-importieren/ElasticSync#, Daten mit ElasticSync importieren>>
* <<daten/daten-exportieren/FormatDesigner#, Datenformate mit FormatDesigner erstellen>>
* <<daten/daten-exportieren/elastischer-export#, Daten mit dem Elastischen Export exportieren>>
* <<daten/report/report#, Rohdaten exportieren>>
=====

[.col-md-4]
.Schnittstellen
=====

* link:https://developers.plentymarkets.com/[REST-API^]
* *Deprecated*: link:{imagesdir}/basics/assets/SOAP-Version-200-Documentation-2016-07-14.zip[SOAP API]
=====

[.col-md-4]
.Protokolle

* *Deprecated* <<daten/api-log#, API-Log>>
=====
====
