[glossary]
= Glossar
:lang: de
include::{includedir}/_header.adoc[]
:description: Glossar für plentymarkets
:position: 300
:url: glossar

[glossary]

[#aktionsgutschein]
Aktionsgutschein:: Eine Art des Gutscheintyps *Gutschein*. Gewährt einen Rabatt. +
Der andere Gutscheintyp in plentymarkets ist der Voucher. Die andere Gutscheinart ist der <<#verkaufsgutschein, Verkaufsgutschein>>.

[#berechnungstyp]
Berechnungstyp:: Findet in der <<portotabelle#, Portotabelle>> eines <<versandprofil#, Versandprofils>> Anwendung. Es gibt 6 Berechnungstypen, die unterschiedliche Möglichkeiten bieten, die Versandkosten je nach Artikel zu berechnen.

[#fulfillment]
Fulfillment:: Beschreibt alle Aktivitäten und Abläufe, die nach Abschluss eines Artikelkaufs der Belieferung des Kunden und der Erfüllung sonstiger Vertragspflichten dienen.

[#handelsvertreter]
Handelsvertreter:: Vermittelt als selbstständiger Gewerbetreibender Geschäfte für ein anderes Unternehmen oder schließt Geschäfte in dessen Namen ab.

[#kundenklasse]
Kundenklasse:: Ermöglicht die Unterteilung des Kundenstamms nach unterschiedlichen Kriterien. Anschließend können unterschiedliche Rabatte für die Kundenklassen vergeben werden.

[#kundentyp]
Kundentyp:: Dient der Einordnung und Unterscheidung von Kontakten.

[#offene-posten]
Offene Posten:: Auch OP-Liste genannt. Zeigt eine Übersicht über Kunden mit unbezahlten Aufträgen (Anzahl der offenen Posten plus Höhe der Forderung) an.

[#plugin]
Plugin:: Eine Erweiterung für das plentymarkets System. Kann auf plentyMarketplace gekauft oder über Git und die Tools plentyDrive und plentyDevTool in das System eingebunden werden.

[#plugin-set]
Plugin-Set:: Eine Sammlung von Plugins. Kann mit Mandanten und Backend-Benutzerkonten verknüpft werden.

[#portotabelle]
Portotabelle:: xxx

[#verkaufsgutschein]
Verkaufsgutschein:: Eine der beiden Arten des Gutscheintyps *Gutschein*. Wird als Anzahlung des Rechnungsbetrags gesehen. Die zweite Gutscheinart ist der <<#aktionsgutschein, Aktionsgutschein>>.

[#versandprofil]
Versandprofil:: xxx
