[glossary]
= Glossar
:lang: de
include::{includedir}/_header.adoc[]
:description: Glossar für plentymarkets
:position: 300
:url: glossar

[glossary]

[#abgleich]
Abgleich:: Bestimmt, anhand welcher Daten beim Datenimport identifiziert werden soll, ob bereits ein Datensatz besteht.

[#aktionsgutschein]
Aktionsgutschein:: Eine der beiden Arten des Gutscheintyps *Gutschein*. Gewährt einen Rabatt. Beim Aktionsgutschein wird der Gutscheinwert zuerst abgezogen und dann der Restbetrag besteuert. +
 Die andere verfügbare Gutscheinart ist der <<verkaufsgutschein, Verkaufsgutschein>>. Der andere verfügbare Gutscheintyp in plentymarkets ist der <<voucher, Voucher>>.

[#artikel]
Artikel:: Artikel können als _Datencontainer_ verstanden werden. Sie beinhalten immer eine oder mehrere <<#variante, Varianten>>, d.h. eine oder mehrere verkaufbare Ausführungen eines Produkts. Wird zum Beispiel ein Hemd in den Größen 50, 52 und 54 angeboten, bilden alle Größen zusammen den Artikel. Jede einzelne Größe ist eine Variante dieses Artikels. +
* Weitere Informationen im Handbuch: <<artikel/einleitung/struktur#, Artikel vs. Varianten>>. +
* Synonyme: Produkte, Güter, Ware

[#artikelpaket]
Artikelpaket:: Eine Möglichkeit, Produkte zu _kombinieren und als eine Verkaufseinheit_ anzubieten. Artikelpakete bestehen aus unterschiedlichen <<#variante, Varianten>>, die zusammengefasst und zu einem Paketpreis angeboten werden. Bestellt werden kann nur das komplette Paket. Die einzelnen Bestandteile können nicht gewählt werden. Beispiel: ein Küchen-Starterset bestehend aus einer Pfanne, einem Topf und einem Pfannenwender. +
* Weitere Informationen im Handbuch: <<artikel/anwendungsfaelle/multipacks-pakete-sets#, Multipacks, Artikelpakete und Sets>>. +
* Synonyme: Artikel-Pack, Bundle

[#attribut]
Attribut:: Manche Artikel, wie Schuhe und T-Shirts, werden in verschiedenen Größen und Farben verkauft. Solche Charakteristiken werden in plentymarkets als Attribute bezeichnet. Mit Hilfe von Attributen kannst du deine Produkte charakterisieren und gleichzeitig auch verkaufbare <<#variante, Varianten>> erzeugen, wie z.B. das T-Shirt in der Farbe rot und in Größe S. +
* Weitere Informationen im Handbuch: <<artikel/einstellungen/attribute#, Attribute>>. +
* Synonyme: Charakteristik

[#auftragsnotiz]
Auftragsnotiz:: Wird zur Hinterlegung von Informationstexten zu einem Auftrag genutzt.

[#backend]
Backend:: Bereich des Systems, in dem die Funktionen hinterlegt sind und für Anwender bereitgestellt werden.

[#backend-plugin-set]
Backend-Plugin-Set:: <<plugin-set,Plugin-Set>>, das mit einem Benutzerkonto verknüpft ist. Die in dem Plugin-Set enthaltenen <<plugin,Plugins>> können das <<backend,Backend>> um Menüs und Funktionen erweitern. Jedes Benutzerkonto ist immer mit genau einem Plugin-Set verknüpft.

[#barcode]
Barcode:: Barcodes dienen zur eindeutigen Kennzeichnung von Produkten. Sie werden häufig z.B. auf Artikeletiketten oder auf Dokumenten wie Rechnungen und Lieferscheinen dargestellt. Es gibt verschiedene Typen von Barcodes, z.B. GTIN, ISBN, UPC oder QR Barcodes. +
* Weitere Informationen im Handbuch: <<artikel/einstellungen/barcodes#, Barcodes und Etiketten>>. +
* Synonyme: Strichcode

[#berechnungstyp]
Berechnungstyp:: Findet in der <<portotabelle, Portotabelle>> eines <<versandprofil, Versandprofils>> Anwendung. Es gibt 6 Berechnungstypen, die unterschiedliche Möglichkeiten bieten, die Versandkosten je nach Artikel zu berechnen.

[#click-and-collect]
Click & Collect:: Mit dieser Methode wird Kunden die Abholung und Bezahlung über den Webshop oder über Marktpläzte bestellter Ware direkt im <<pos/pos-einrichten#4100, Ladengeschäft>> ermöglicht.

[#cross-selling]
Cross-Selling:: Beim Cross-Selling werden Kunden subtil dazu ermutigt, mehr Geld auszugeben. Dies geschieht, indem weitere Produkte angeboten werden, die sich auf das gekaufte Produkt beziehen. Der Verkäufer in einem Elektronikgeschäft schlägt z.B. eine Speicherkarte vor, die mit der Digitalkamera funktionieren würde.
* Weitere Informationen im Handbuch: <<artikel/webshop/cross-selling#, Cross-Selling>>.

[#dep-export]
DEP-Export:: Als JSON-Datei bereitgestelltes Datenerfassungsprotokoll. In Österreich muss der <<pos/pos-einrichten#880, DEP-Export>> laut Gesetz für jede Registrierkasse verfügbar sein.

[#eigenschaft]
Eigenschaft:: Manche Artikel stechen aus der Masse heraus. Sei es eine Uhr, die wasserdicht ist, oder ein Lautsprecher, der mit Bluetooth ausgestattet ist. Solche Charakteristiken werden in plentymarkets als _Eigenschaften_ und _Merkmale_ bezeichnet. Sie heben die technischen Features eines Produkts hervor. Der Unterschied besteht darin, dass Eigenschaften spezifische Varianten charakterisieren, während <<#merkmal, Merkmale>> ganze Artikel charakterisieren. Eigenschaften und Merkmale unterscheiden sich auch von <<#attribut, Attributen>>, insofern dass sie Produkte charakterisieren, _ohne_ dabei verkaufbare Varianten zu bilden. +
* Weitere Informationen im Handbuch: <<artikel/einstellungen/eigenschaften#, Merkmale und Eigenschaften>>. +
* Synonyme: Charakteristik

[#einlage]
Einlage:: Physische Ergänzung des Bargeldbestandes im Kassenbereich, um beispielsweise Wechselgeld vorrätig zu halten. <<pos/pos-kassenbenutzer#190, Einlagen>> werden in der plentymarkets App oder im Backend verbucht und können verschiedenen Buchungskonten zugewiesen werden.

[#einlösung]
Einlösung:: Die Einlösung des <<gutschein, Gutscheins>> erfolgt während des Bestellvorgangs. Dabei wird der entsprechende Rabattwert direkt angezeigt.

[#einlieferungsliste]
Einlieferungsliste:: Enthält die Paketnummer, die Lieferadresse, den Betrag des Auftrags sowie die Auftrags-ID. Bei Abholung der Pakete unterschreibt der Fahrer die Liste, die als Abholbeleg dient.

[#einzelkommissionierung]
Einzelkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Jeder Auftrag wird einzeln aufgenommen und abgearbeitet.

[entnahme]
Entnahme:: Physische Reduzierung des Bargedlbestandes, um beispielsweise Beträge von der Kasse auf andere Konten zu transferieren. <<pos/pos-kassenbenutzer#200. Entnahhmen>> werden in der plentymarkets App oder im Backend verbucht und können verschiedenen Buchungskonten zugewiesen werden.

[#facettensuche]
Facettensuche:: Filtermöglichkeiten, mit denen Suchergebnisse im Webshop nach bestimmten Kriterien, also Facetten, verfeinert werden. Beispielsweise können die Suchergebnisse so verfeinert werden, dass sie nur eine bestimmte Preisspanne oder bestimmte Markennamen, Größen oder Farben enthalten. +
* Weitere Informationen im Handbuch: <<artikel/frontend-artikelsuche-verwalten#, Suchfunktion im Webshop>>. +
* Synonyme: Facettennavigation, Filtersuche, Artikelsuche

[#feinkommissionierung]
Feinkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Die einzelnen Artikel eines Auftrags werden individuell gepickt, verpackt und versendet.

[#frontend]
Frontend:: Beinhaltet den Webshop, also all das, was ein Kunde sehen kann.

[#fulfillment]
Fulfillment:: Beschreibt alle Aktivitäten und Abläufe, die nach Abschluss eines Artikelkaufs der Belieferung des Kunden und der Erfüllung sonstiger Vertragspflichten dienen.

[#grobkommissionierung]
Grobkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Mehrere Aufträge werden zusammengefasst und auf einmal bearbeitet.

[#grundpreis]
Grundpreis:: Der Preis eines Artikels pro Pfund, Liter oder andere Maßeinheit. Der Grundpreis wird z.B. in den Regalen von Supermärkten aufgeführt. Berechnet wird er auf Grundlage von <<artikel/einstellungen/einheiten#, Einheit>>, Inhalt und Preis des Artikels. Dargestellt werden kann er im Webshop, auf Vertriebskanälen wie eBay oder Netto und auf Artikeletiketten.

[#gutschein]
Gutschein:: Einer der beiden Gutscheintypen in plentymarkets. Gewährt einen Rabatt in deinem Webshop. +
Der andere verfügbare Gutscheintyp ist der <<voucher, Voucher>>. +
Ein Gutschein enthält einen Code, der einer <<gutscheinkampagne, Gutscheinkampagne>> angehört und entweder nur einmal oder mehrfach eingelöst werden kann. Gutscheine können als Code in einer E-Mail versendet werden oder als Artikel erstellt und verkauft werden. Der Käufer erhält in letzterem Fall den Gutschein dann als PDF-Dokument.

[#gutscheinkampagne]
Gutscheinkampagne:: Jeder Gutschein gehört einer Kampagne an. Über die Kampagne kann z.B. die Laufzeit des Gutscheins sowie die Anzahl der möglichen Einlösungen eingestellt werden.

[#handelsvertreter]
Handelsvertreter:: Vermittelt als selbstständiger Gewerbetreibender Geschäfte für ein anderes Unternehmen oder schließt Geschäfte in dessen Namen ab.

[#hauptvariante]
Hauptvariante:: Die erste <<#variante, Variante>> eines Artikels wird als Hauptvariante bezeichnet. Hat ein Artikel mehrere Varianten, kann die Hauptvariante entweder selbst ein verkaufbares Produkt sein oder rein virtuell bestehen, um die weiteren Untervarianten des Artikels anhand von <<#vererbung, Vererbung>> zu verwalten.

[#hauptmandant]
Hauptmandant:: Siehe <<standard-mandant,Standard-Mandant>>.

[#idea-export]
IDEA-Export:: GoBD-konformer Export der Kassenvorgänge, der im Rahmen einer Prüfung durch das Finanzamt angefordert werden kann. Die Exportdateien können pro Jahr als ZIP-Datei heruntergeladen werden.

[#kassenjournal]
Kassenjournal:: Beinhaltet alle verfügbaren Kassenbewegungen und ist als PDF- oder CSV-Datei exportierbar. Im <<pos/pos-einrichten#400, Kassenjournal>> können Kassenvorgänge gesucht und angezeigt werden.

[#kategorie]
Kategorie:: In plentymarkets können Kategorien sowohl im Sinne von _Warengruppen_ als auch im Sinne von den _Content-Seiten_ eines Webshops verstanden werden. Der Kategorietyp bestimmt, wie die Kategorie zu verstehen ist.
* Weitere Informationen im Handbuch: <<artikel/einstellungen/kategorien#, Kategorien>>.

[#kassensturz]
Kassensturz:: Der Kassensturz dient zur Dokumentation des Bargeldbestandes, der in der Kasse verfügbar ist. Er erfolgt in Form einer physischen Zählung des Geldbestandes mithilfe der plentymarkets App. <<pos/pos-kassenbenutzer#450b, Kassensturzberichte>> können gedruckt werden und werden im Dokumentenarchiv gespeichert.

[#kundenklasse]
Kundenklasse:: Ermöglicht die Unterteilung des Kundenstamms nach unterschiedlichen Kriterien. Anschließend können unterschiedliche Rabatte für die Kundenklassen vergeben werden.

[#kundentyp]
Kundentyp:: Dient der Einordnung und Unterscheidung von Kontakten.

[#lager]
Lager:: Raum, in dem Ware gelagert wird. Ein Lager kann beispielsweise aus einer Halle bestehen, in der sich Regale mit Regalböden und konkreten Lagerorten befinden.

[#lagerort]
Lagerort:: Konkreter Ort, an dem sich ein Artikel im Lager befindet (Bsp. Halle 1, Regal 4, Regalboden 2, Lagerort 6).

[#lagerreichweite]
Lagerreichweite:: Zeitraum (in Tagen), für den der Warenbestand bis zur nächsten Nachbestellung reichen soll.

[#laufweg]
Laufweg:: Weg, nach dem das Lager beim Picken von Ware abgelaufen wird.

[#lieferanschriftenliste]
Lieferanschriftenliste:: Exportdatei mit Sendungsinformationen, die du dem Versanddienstleister, über den du deine Ware versendest, bereitstellst, damit dir dieser wiederum gültige Versandlabels für deine Pakete zur Verfügung stellen kann.

[#mandant]
Mandant:: Eine Instanz von plentymarkets. Es ist möglich, mehrere Mandanten in einem einzelnen System zu verwalten.

[#markierung]
Markierung:: Markierungen sind visuelle Unterstützungen. Sie helfen dir, die richtigen Artikel auf einen Blick zu finden. Weise jedem deiner Artikel eine oder zwei Markierungen zu. Diese Markierungen siehst du, wenn du deine Artikel im plentymarkets Backend betrachtest. Du kannst auch gezielt nach Artikeln suchen, die eine bestimmte Markierung oder Kombination von Markierungen haben. +
* Weitere Informationen im Handbuch: <<artikel/einstellungen/markierungen#, Tags und Markierungen>>. +
* Synonyme: Flag

[#merkmal]
Merkmal:: Manche Artikel stechen aus der Masse heraus. Sei es eine Uhr, die wasserdicht ist, oder ein Lautsprecher, der mit Bluetooth ausgestattet ist. Solche Charakteristiken werden in plentymarkets als _Merkmale_ und _Eigenschaften_ bezeichnet. Sie heben die technischen Features eines Produkts hervor. Der Unterschied besteht darin, dass Merkmale ganze Artikel charakterisieren, während <<#eigenschaft, Eigenschaften>> spezifische Varianten charakterisieren. Merkmale und Eigenschaften unterscheiden sich auch von <<#attribut, Attributen>>, insofern dass sie Produkte charakterisieren, _ohne_ dabei verkaufbare Varianten zu bilden. +
* Weitere Informationen im Handbuch: <<artikel/einstellungen/eigenschaften#, Merkmale und Eigenschaften>>. +
* Synonyme: Charakteristik

[#multipack]
Multipack:: Eine Möglichkeit, Produkte zu _kombinieren und als eine Verkaufseinheit_ anzubieten. Multipacks sind verschiedene Stückzahlen derselben <<#variante, Variante>>. Beispiel: eine Flasche Wasser, eine Packung mit 6 Flaschen und eine Packung mit 12 Flaschen. +
* Weitere Informationen im Handbuch: <<artikel/anwendungsfaelle/multipacks-pakete-sets#, Multipacks, Artikelpakete und Sets>>.

[#nachnahme]
Nachnahme:: Zahlungsart, die du in deinem Webshop anbieten kannst. Der Versanddienstleister transportiert die Pakete zum Empfänger und übernimmt den Zahlungsvorgang für dich. Die Sendung wird dem Empfänger erst nach Bezahlung ausgehändigt.

[#offene-posten]
Offene Posten:: Auch OP-Liste genannt. Zeigt eine Übersicht über Kunden mit unbezahlten Aufträgen (Anzahl der offenen Posten plus Höhe der Forderung) an.

[#packliste]
Packliste:: Übersicht von Aufträgen mit allen enthaltenen Auftragspositionen und der Auftrags-ID als Barcode. Kann als PDF generiert werden, wenn eine Dokumentenvoralge eingerichtet wurde.

[#paketnummer]
Paketnummer:: Auch als Sendungsnummer bekannt. Sendungsspezifische Nummer, über die man den Status des Pakets einsehen kann.

[#plugin]
Plugin:: Eine Erweiterung für das plentymarkets System. Kann auf link:https://marketplace.plentymarkets.com[plentyMarketplace^] gekauft oder über Git und die Tools plentyDrive und plentyDevTool in das System eingebunden werden.

[#plugin-set]
Plugin-Set:: Eine Sammlung von Plugins. Kann mit Mandanten und <<backend-plugin-set,Backend-Benutzerkonten>> verknüpft werden.

[#portotabelle]
Portotabelle:: Enthält die Versandkosten des <<versandprofil#, Versandprofils>>. Für jede Region, die im Versandprofil enthalten ist – also jedes Lieferland, das aktiviert wurde und ggf. mit mehreren anderen Lieferländern in eine Region zusammengefasst wurde – müssen die Versandkosten gespeichert werden.

[#preis]
Preis:: In plentymarkets wird zwischen _Verkaufspreisen_ und _Preisen_ unterschieden. Der Preis ist der tatsächliche monetäre Betrag, zu dem eine Variante verkauft wird, wenn die durch den <<#verkaufspreis, Verkaufspreis>> definierten Bedingungen erfüllt sind. Der Preis wird Kunden in Rechnung gestellt, wenn die Bedingungen erfüllt sind, die in den Verkaufspreiseinstellungen definiert wurden. +
* Weitere Informationen im Handbuch: <<artikel/einstellungen/preise#, Verkaufspreise und Preiskalkulation>>.

[#preiskalkulation]
Preiskalkulation:: Preiskalkulationen dienen dazu, die <<#preis, Preise>> von Varianten anhand bestimmter Kriterien automatisch zu berechnen und zu aktualisieren. Dabei können Anwender diverse, an der Variante gespeicherten Kosten zu einem Verkaufspreis addieren, z.B. Transportkosten, Lagerkosten, Zoll, Mehrwertsteuer. Weiterhin können Anwender individuelle Beträge zum Preis addieren oder vom Preis subtrahieren, z.B. plus 5% oder mal 1,05. +
* Weitere Informationen im Handbuch: <<artikel/einstellungen/preise#, Verkaufspreise und Preiskalkulation>>.

[#pruefziffer]
Prüfziffer:: Die letzte Ziffer eines GTIN <<#barcode, Barcodes>>.

[#rollende-kommissionierung]
Rollende Kommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Mehrere Aufträge werden gleichzeitig gepickt, verpackt und versandfertig vorsortiert and den Packtisch geliefert. Auch als "rollende Boxenkommissionierung" bekannt.

[#rücksendeschein]
Rücksendeschein:: Wird vom Kunden für Artikel benutzt, die zurückgeschickt werden sollen. Liegt entweder dem Paket bei oder kann von Kunden ausgedruckt werden, sobald eine Dokumentenvorlage dafür im System hinterlegt wurde.

[#sammelkommissionierung]
Sammelkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Mehrere Aufträge werden auf einmal bearbeitet. Alle Artikel werden in nur einen Behälter kommissioniert und erst am Packtisch werden die Artikel den einzelnen Aufträgen zugeordnet.

[#seriennummer]
Seriennummer:: Eine Seriennummer ist eine alphanumerische Zeichenkette, die ein einzelnes Exemplar eines Artikels eindeutig kennzeichnet. Seriennummern ermöglichen die Rückverfolgbarkeit eines verkauften Artikels im Fehler- oder Problemfall und erleichtern somit das Aufspüren von gestohlenen oder gefälschten Produkten. Beispiele für Artikel mit Seriennummern sind Autos, Elektronik und Haushaltsgeräte.
* Weitere Informationen im Handbuch: <<artikel/anwendungsfaelle/seriennummern#, Seriennummern>>.

[#set]
Set:: Eine Möglichkeit, Produkte zu _kombinieren und als eine Verkaufseinheit_ anzubieten. Artikelsets bestehen aus unterschiedlichen <<#artikel, Artikeln>>. Für jeden Artikel kann die gewünschte <<#variante, Variante>> gewählt werden. Beispiel: ein Küchen-Starterset bestehend aus einer Pfanne (entweder in der Farbe rot oder schwarz), ein Topf (entweder in der Farbe silber oder schwarz) und ein Pfannenwender (entweder aus Plastik oder aus Holz). +
* Weitere Informationen im Handbuch: <<artikel/anwendungsfaelle/multipacks-pakete-sets#, Multipacks, Artikelpakete und Sets>>.

[#shop-aktion]
Shop-Aktion:: Eine Möglichkeit, bestimmte Artikel im Webshop hervorzuheben. Zum Beispiel, um einzelne Artikel als Bestseller, Sonderangebote oder Neuheiten zu kennzeichnen. +
* Weitere Informationen im Handbuch: <<artikel/webshop/shop-aktionen#, Shop-Aktionen>>.

[#stammdaten]
Stammdaten:: Grundinformationen eines Benutzers (z.B. Kontaktdaten wie Firmenname, Anschrift, Telefonnummer etc.).

[#skontofrist]
Skontofrist:: Anzahl der Tage, in denen der Kontakt skontiert offene Forderungen bezahlen kann.

[#skontosatz]
Skontosatz:: Wert in Prozent, den der Kontakt bei Einhaltung der <<skontofrist, Skontofrist>> in Abzug bringen kann.

[#standard-mandant]
Standard-Mandant:: Der <<mandant,Mandant>>, der mit dem Vertrag des Systems verbunden ist. Einige Funktionen sind nur über den Hauptmandanten möglich. Dazu gehören z.B. Ereignisaktionen und Aufrufe über die REST-API.

[#tag]
Tag:: Tags sind eine Möglichkeit, bestimmte Datensätze hervorzuheben. Tags können z.B. auf einzelne Varianten, Kundendatensätze, Bestellungen, Tickets usw. angewendet werden. +
* Weitere Informationen im Handbuch: <<basics/arbeiten-mit-plentymarkets/tags#, Tags>>.

[#tagesabschlussbericht]
Tagessabschlussbericht:: Auch als Z-Report bekannt. Dokumentiert im Kassenbetrieb die seit dem letzten Tagesabschluss getätigten Umsätze. <<pos/pos-kassenbenutzer#230, Tagesabschlussberichte>> werden nach Erzeugung im Dokumentenarchiv gespeichert und gelten gegenüber dem Finanzamt als Nachweis.

[#template-funktion]
Template-Funktion:: Vordefinierte Funktion für E-Mail-Vorlagen. Beim Versand der E-Mail wird die Funktion automatisch durch die tatsächliche URL ersetzt, z.B. die URL zum Warenkorb (*{%Link_Basket()%}*) oder zu den AGB des Webshops (*{%Link_TermsConditions()%}*).

[#template-variable]
Template-Variable:: Vordefinierte Variable für E-Mail-Vorlagen. Beim Versand der E-Mail wird die Variable automatisch durch den tatsächlichen Inhalt ersetzt, wenn die entsprechenden Voraussetzungen erfüllt sind.

[#treueprogramm]
Treueprogramm:: Kann mit eBay Plus oder Amazon verwendet werden. Wird im <<versandprofil, Versandprofil>> aktiviert.

[#ustidnr]
USt-IdNr.:: Kurzform für Umsatzsteuer-Identifikationsnummer. Ist eine eindeutige Kennzeichnung einer umsatzsteuerpflichtigen Person oder eines Unternehmens innerhalb der EU im umsatzsteuerlichen Sinne.

[#variante]
Variante:: Eine verkaufbare Ausführung eines Produkts. Wird zum Beispiel ein Hemd in den Größen 50, 52 und 54 angeboten, dann ist jede einzelne Größe eine Variante dieses Hemdes. Alle Größen zusammen bilden den <<#artikel, Artikel>>. +
* Weitere Informationen im Handbuch: <<artikel/einleitung/struktur#, Artikel vs. Varianten>>.

[#vererbung]
Vererbung:: Die <<#hauptvariante, Hauptvariante>> eines Artikels unterscheidet sich von den Untervarianten dadurch, dass ihre Daten weitergegeben, also _vererbt_ werden können. Die Hauptvariante ist also eine Elternvariante, die bestimmte Daten an ihre Kinder vererbt. Die Vererbungsfunktion ist standardmäßig aktiviert. Wenn eine neue Variante eines Artikels erstellt wird, erbt diese Variante Einstellungen der Hauptvariante, solange keine davon abweichenden Daten gespeichert werden. +
* Weitere Informationen im Handbuch: <<artikel/einleitung/vererbung#, Was ist Vererbung?>>.

[#verkaufsgutschein]
Verkaufsgutschein:: Eine der beiden Arten des Gutscheintyps *Gutschein*. Wird als Anzahlung des Rechnungsbetrags gesehen. Die zweite Gutscheinart ist der <<#aktionsgutschein, Aktionsgutschein>>.

[#verkaufspreis]
Verkaufspreis:: In plentymarkets wird zwischen _Verkaufspreisen_ und _Preisen_ unterschieden. Die Verkaufspreise sind Datencontainer. Sie ermöglichen das zentrale Verwalten von Bedingungen, die auf Preise zutreffen sollen. Verkaufspreise bestimmen also in welchen Situationen eine Variante zu einem bestimmten <<#preis, Preis>> verkauft wird. +
* Weitere Informationen im Handbuch: <<artikel/einstellungen/preise#, Verkaufspreise und Preiskalkulation>>. +

[#versandauftrag]
Versandauftrag:: Ist der Auftrag, der bei einem Versanddienstleister angemeldet wird.

[#versandprofil]
Versandprofil:: Enthält Versandkombinationen, die die Kunden im Checkout wählen können oder die bereits bestimmten Auftragsarten automatisch zugewiesen werden. Zum Beispiel können im Versandprofil Zahlungsarten und Kundenklassen gesperrt werden oder es kann ein Inselzuschlag gespeichert werden. Dieser Aufpreis greift also immer dann, wenn eine Lieferung auf eine Insel, z.B. Helgoland, erfolgt. Dies bedeutet, dass zusätzlich zu den eigentlichen Versandkosten noch ein weiterer Betrag fällig wird.

[#verkaufsgutschein]
Verkaufsgutschein:: Eine der beiden Arten des Gutscheintyps *Gutschein*. Beim Verkaufsgutschein wird der Gutscheinwert vom Gesamtbetrag inklusive Steuern abgezogen. +
Die andere verfügbare Gutscheinart ist der <<aktionsgutschein, Aktionsgutschein>>. Der andere verfügbare Gutscheintyp in plentymarkets ist der <<voucher, Voucher>>.

[#voucher]
Voucher:: Einer der beiden Gutscheintypen in plentymarkets. Wird bei Drittanbietern eingelöst, z.B. in der Hotellerie. +
Der andere verfügbare Gutscheintyp ist der <<gutschein, Gutschein>>.

[#warenausgang]
Warenausgang:: Ware wird aus dem System ausgebucht und der Warenbestand wird reduziert.

[#warenbestand]
Warenbestand:: Menge der Ware, die aktuell im Lager vorhanden ist.

[#wareneingang]
Wareneingang:: Ware wird in das System eingebucht und der Warenbestand wird erhöht.

[#zahlungseingang]
Zahlungseingang:: Bezeichnet den Eingang einer Zahlung für einen Auftrag. Zahlungen können automatisch eingehen oder manuell gebucht werden und werden direkt im Auftrag vermerkt.

[#zuordnung]
Zuordnung:: Legt beim Datenimport fest, welche Spalte einer CSV-Datei welchem Datenfeld in plentymarkets entspricht.

[#zwischenbericht]
Zwischenbericht:: Auch als X-Bericht bekannt. Enthält vielfältige Informationen über die Umsätze, die im laufenden Betrieb und seit dem letzten Tagesabschluss über die Kasse generiert wurden. <<pos/pos-kassenbenutzer#220, Zwischenberichte>> werden nicht als Dokumente im plentymarkets Backend hinterlegt und gelten nicht als Nachweise gegenüber dem Finanzamt.
