[glossary]
= Glossar
:lang: de
include::{includedir}/_header.adoc[]
:description: Glossar für plentymarkets
:position: 300
:url: glossar

[glossary]

[#abgleich]
Abgleich:: Bestimmt, anhand welcher Daten beim Datenimport identifiziert werden soll, ob bereits ein Datensatz besteht.

[#aktionsgutschein]
Aktionsgutschein:: Eine der beiden Arten des Gutscheintyps *Gutschein*. Gewährt einen Rabatt. Beim Aktionsgutschein wird der Gutscheinwert zuerst abgezogen und dann der Restbetrag besteuert. +
 Die andere verfügbare Gutscheinart ist der <<verkaufsgutschein, Verkaufsgutschein>>. Der andere verfügbare Gutscheintyp in plentymarkets ist der <<voucher, Voucher>>.

[#auftragsnotiz]
Auftragsnotiz:: Wird zur Hinterlegung von Informationstexten zu einem Auftrag genutzt.

[#backend]
Backend:: Bereich des Systems, in dem die Funktionen hinterlegt sind und für Anwender bereitgestellt werden.

[#backend-plugin-set]
Backend-Plugin-Set:: <<plugin-set,Plugin-Set>>, das mit einem Benutzerkonto verknüpft ist. Die in dem Plugin-Set enthaltenen <<plugin,Plugins>> können das <<backend,Backend>> um Menüs und Funktionen erweitern. Jedes Benutzerkonto ist immer mit genau einem Plugin-Set verknüpft.

[#berechnungstyp]
Berechnungstyp:: Findet in der <<portotabelle, Portotabelle>> eines <<versandprofil, Versandprofils>> Anwendung. Es gibt 6 Berechnungstypen, die unterschiedliche Möglichkeiten bieten, die Versandkosten je nach Artikel zu berechnen.

[#einlösung]
Einlösung:: Die Einlösung des <<gutschein, Gutscheins>> erfolgt während des Bestellvorgangs. Dabei wird der entsprechende Rabattwert direkt angezeigt.

[#einlieferungsliste]
Einlieferungsliste:: Enthält die Paketnummer, die Lieferadresse, den Betrag des Auftrags sowie die Auftrags-ID. Bei Abholung der Pakete unterschreibt der Fahrer die Liste, die als Abholbeleg dient.

[#einzelkommissionierung]
Einzelkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Jeder Auftrag wird einzeln aufgenommen und abgearbeitet.

[#feinkommissionierung]
Feinkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Die einzelnen Artikel eines Auftrags werden individuell gepickt, verpackt und versendet.

[#frontend]
Frontend:: Beinhaltet den Webshop, also all das, was ein Kunde sehen kann.

[#fulfillment]
Fulfillment:: Beschreibt alle Aktivitäten und Abläufe, die nach Abschluss eines Artikelkaufs der Belieferung des Kunden und der Erfüllung sonstiger Vertragspflichten dienen.

[#grobkommissionierung]
Grobkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Mehrere Aufträge werden zusammengefasst und auf einmal bearbeitet.

[#gutschein]
Gutschein:: Einer der beiden Gutscheintypen in plentymarkets. Gewährt einen Rabatt in deinem Webshop. +
Der andere verfügbare Gutscheintyp ist der <<voucher, Voucher>>. +
Ein Gutschein enthält einen Code, der einer <<gutscheinkampagne, Gutscheinkampagne>> angehört und entweder nur einmal oder mehrfach eingelöst werden kann. Gutscheine können als Code in einer E-Mail versendet werden oder als Artikel erstellt und verkauft werden. Der Käufer erhält in letzterem Fall den Gutschein dann als PDF-Dokument.

[#gutscheinkampagne]
Gutscheinkampagne:: Jeder Gutschein gehört einer Kampagne an. Über die Kampagne kann z.B. die Laufzeit des Gutscheins sowie die Anzahl der möglichen Einlösungen eingestellt werden.

[#handelsvertreter]
Handelsvertreter:: Vermittelt als selbstständiger Gewerbetreibender Geschäfte für ein anderes Unternehmen oder schließt Geschäfte in dessen Namen ab.

[#hauptmandant]
Hauptmandant:: Siehe <<standard-mandant,Standard-Mandant>>.

[#kundenklasse]
Kundenklasse:: Ermöglicht die Unterteilung des Kundenstamms nach unterschiedlichen Kriterien. Anschließend können unterschiedliche Rabatte für die Kundenklassen vergeben werden.

[#kundentyp]
Kundentyp:: Dient der Einordnung und Unterscheidung von Kontakten.

[#lager]
Lager:: Raum, in dem Ware gelagert wird. Ein Lager kann beispielsweise aus einer Halle bestehen, in der sich Regale mit Regalböden und konkreten Lagerorten befinden.

[#lagerort]
Lagerort:: Konkreter Ort, an dem sich ein Artikel im Lager befindet (Bsp. Halle 1, Regal 4, Regalboden 2, Lagerort 6).

[#lagerreichweite]
Lagerreichweite:: Zeitraum (in Tagen), für den der Warenbestand bis zur nächsten Nachbestellung reichen soll.

[#laufweg]
Laufweg:: Weg, nach dem das Lager beim Picken von Ware abgelaufen wird.

[#lieferanschriftenliste]
Lieferanschriftenliste:: Exportdatei mit Sendungsinformationen, die du dem Versanddienstleister, über den du deine Ware versendest, bereitstellst, damit dir dieser wiederum gültige Versandlabels für deine Pakete zur Verfügung stellen kann.

[#mandant]
Mandant:: Eine Instanz von plentymarkets. Es ist möglich, mehrere Mandanten in einem einzelnen System zu verwalten.

[#nachnahme]
Nachnahme:: Zahlungsart, die du in deinem Webshop anbieten kannst. Der Versanddienstleister transportiert die Pakete zum Empfänger und übernimmt den Zahlungsvorgang für dich. Die Sendung wird dem Empfänger erst nach Bezahlung ausgehändigt.

[#offene-posten]
Offene Posten:: Auch OP-Liste genannt. Zeigt eine Übersicht über Kunden mit unbezahlten Aufträgen (Anzahl der offenen Posten plus Höhe der Forderung) an.

[#paketnummer]
Paketnummer:: Auch als Sendungsnummer bekannt. Sendungsspezifische Nummer, über die man den Status des Pakets einsehen kann.

[#plugin]
Plugin:: Eine Erweiterung für das plentymarkets System. Kann auf link:https://marketplace.plentymarkets.com[plentyMarketplace^] gekauft oder über Git und die Tools plentyDrive und plentyDevTool in das System eingebunden werden.

[#plugin-set]
Plugin-Set:: Eine Sammlung von Plugins. Kann mit Mandanten und <<backend-plugin-set,Backend-Benutzerkonten>> verknüpft werden.

[#portotabelle]
Portotabelle:: Enthält die Versandkosten des <<versandprofil#, Versandprofils>>. Für jede Region, die im Versandprofil enthalten ist – also jedes Lieferland, das aktiviert wurde und ggf. mit mehreren anderen Lieferländern in eine Region zusammengefasst wurde – müssen die Versandkosten gespeichert werden.

[#rollende kommissionierung]
Rollende Kommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Mehrere Aufträge werden gleichzeitig gepickt, verpackt und versandfertig vorsortiert and den Packtisch geliefert. Auch als "rollende Boxenkommissionierung" bekannt.

[#rücksendeschein]
Rücksendeschein:: Wird vom Kunden für Artikel benutzt, die zurückgeschickt werden sollen. Liegt entweder dem Paket bei oder kann von Kunden ausgedruckt werden, sobald eine Dokumentenvorlage dafür im System hinterlegt wurde.

[#sammelkommissionierung]
Sammelkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Mehrere Aufträge werden auf einmal bearbeitet. Alle Artikel werden in nur einen Behälter kommissioniert und erst am Packtisch werden die Artikel den einzelnen Aufträgen zugeordnet.

[#stammdaten]
Stammdaten:: Grundinformationen eines Benutzers (z.B. Kontaktdaten wie Firmenname, Anschrift, Telefonnummer etc.).

[#skontofrist]
Skontofrist:: Anzahl der Tage, in denen der Kontakt skontiert offene Forderungen bezahlen kann.

[#skontosatz]
Skontosatz:: Wert in Prozent, den der Kontakt bei Einhaltung der <<skontofrist, Skontofrist>> in Abzug bringen kann.

[#standard-mandant]
Standard-Mandant:: Der <<mandant,Mandant>>, der mit dem Vertrag des Systems verbunden ist. Einige Funktionen sind nur über den Hauptmandanten möglich. Dazu gehören z.B. Ereignisaktionen und Aufrufe über die REST-API.

[#template-funktion]
Template-Funktion:: Vordefinierte Funktion für E-Mail-Vorlagen. Beim Versand der E-Mail wird die Funktion automatisch durch die tatsächliche URL ersetzt, z.B. die URL zum Warenkorb (*{%Link_Basket()%}*) oder zu den AGB des Webshops (*{%Link_TermsConditions()%}*).

[#template-variable]
Template-Variable:: Vordefinierte Variable für E-Mail-Vorlagen. Beim Versand der E-Mail wird die Variable automatisch durch den tatsächlichen Inhalt ersetzt, wenn die entsprechenden Voraussetzungen erfüllt sind.

[#treueprogramm]
Treueprogramm:: Kann mit eBay Plus oder Amazon verwendet werden. Wird im <<versandprofil, Versandprofil>> aktiviert.

[#ustidnr]
USt-IdNr.:: Kurzform für Umsatzsteuer-Identifikationsnummer. Ist eine eindeutige Kennzeichnung einer umsatzsteuerpflichtigen Person oder eines Unternehmens innerhalb der EU im umsatzsteuerlichen Sinne.

[#verkaufsgutschein]
Verkaufsgutschein:: Eine der beiden Arten des Gutscheintyps *Gutschein*. Wird als Anzahlung des Rechnungsbetrags gesehen. Die zweite Gutscheinart ist der <<#aktionsgutschein, Aktionsgutschein>>.

[#versandauftrag]
Versandauftrag:: Ist der Auftrag, der bei einem Versanddienstleister angemeldet wird.

[#versandprofil]
Versandprofil:: Enthält Versandkombinationen, die die Kunden im Checkout wählen können oder die bereits bestimmten Auftragsarten automatisch zugewiesen werden. Zum Beispiel können im Versandprofil Zahlungsarten und Kundenklassen gesperrt werden oder es kann ein Inselzuschlag gespeichert werden. Dieser Aufpreis greift also immer dann, wenn eine Lieferung auf eine Insel, z.B. Helgoland, erfolgt. Dies bedeutet, dass zusätzlich zu den eigentlichen Versandkosten noch ein weiterer Betrag fällig wird.

[#verkaufsgutschein]
Verkaufsgutschein:: Eine der beiden Arten des Gutscheintyps *Gutschein*. Beim Verkaufsgutschein wird der Gutscheinwert vom Gesamtbetrag inklusive Steuern abgezogen. +
Die andere verfügbare Gutscheinart ist der <<aktionsgutschein, Aktionsgutschein>>. Der andere verfügbare Gutscheintyp in plentymarkets ist der <<voucher, Voucher>>.

[#voucher]
Voucher:: Einer der beiden Gutscheintypen in plentymarkets. Wird bei Drittanbietern eingelöst, z.B. in der Hotellerie. +
Der andere verfügbare Gutscheintyp ist der <<gutschein, Gutschein>>.

[#warenausgang]
Warenausgang:: Ware wird aus dem System ausgebucht und der Warenbestand wird reduziert.

[#warenbestand]
Warenbestand:: Menge der Ware, die aktuell im Lager vorhanden ist.

[#wareneingang]
Wareneingang:: Ware wird in das System eingebucht und der Warenbestand wird erhöht.

[#zuordnung]
Zuordnung:: Legt beim Datenimport fest, welche Spalte einer CSV-Datei welchem Datenfeld in plentymarkets entspricht.
