[glossary]
= Glossar
:lang: de
include::{includedir}/_header.adoc[]
:description: Glossar für plentymarkets
:position: 300
:url: glossar

[glossary]

[#abgleich]
Abgleich:: Bestimmt, anhand welcher Daten beim Datenimport identifiziert werden soll, ob bereits ein Datensatz besteht.

[#aktionsgutschein]
Aktionsgutschein:: Eine Art des Gutscheintyps *Gutschein*. Gewährt einen Rabatt. +
Der andere Gutscheintyp in plentymarkets ist der Voucher. Die andere Gutscheinart ist der <<verkaufsgutschein, Verkaufsgutschein>>.

[#backend]
Backend:: Systemnahe Schicht des IT-Systems, in der die Funktionalität im Vordergrund steht.

[#backend-plugin-set]
Backend-Plugin-Set:: <<plugin-set,Plugin-Set>>, das mit einem Benutzerkonto verknüpft ist. Die in dem Plugin-Set enthaltenen <<plugin,Plugins>> können das <<backend,Backend>> um Menüs und Funktionen erweitern. Jedes Benutzerkonto ist immer mit genau einem Plugin-Set verknüpft.

[#berechnungstyp]
Berechnungstyp:: Findet in der <<portotabelle, Portotabelle>> eines <<versandprofil, Versandprofils>> Anwendung. Es gibt 6 Berechnungstypen, die unterschiedliche Möglichkeiten bieten, die Versandkosten je nach Artikel zu berechnen.

[#einzelkommissionierung]
Einzelkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Jeder Auftrag wird einzeln aufgenommen und abgearbeitet.

[#feinkommissionierung]
Feinkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Die einzelnen Artikel eines Auftrags werden individuell gepickt, verpackt und versendet.

[#frontend]
Frontend:: Anwendernahe Schicht des IT-Systems, in der das Visuelle im Vordergrund steht.

[#fulfillment]
Fulfillment:: Beschreibt alle Aktivitäten und Abläufe, die nach Abschluss eines Artikelkaufs der Belieferung des Kunden und der Erfüllung sonstiger Vertragspflichten dienen.

[#grobkommissionierung]
Grobkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Mehrere Aufträge werden zusammengefasst und auf einmal bearbeitet.

[#handelsvertreter]
Handelsvertreter:: Vermittelt als selbstständiger Gewerbetreibender Geschäfte für ein anderes Unternehmen oder schließt Geschäfte in dessen Namen ab.

[#hauptmandant]
Hauptmandant:: Siehe <<standard-mandant,Standard-Mandant>>.

[#kundenklasse]
Kundenklasse:: Ermöglicht die Unterteilung des Kundenstamms nach unterschiedlichen Kriterien. Anschließend können unterschiedliche Rabatte für die Kundenklassen vergeben werden.

[#kundentyp]
Kundentyp:: Dient der Einordnung und Unterscheidung von Kontakten.

[#lager]
Lager:: Raum, in dem Ware gelagert wird. Ein Lager kann beispielsweise aus einer Halle bestehen, in der sich Regale mit Regalböden und konkreten Lagerorten befinden.

[#lagerort]
Lagerort:: Konkreter Ort, an dem sich ein Artikel im Lager befindet (Bsp. Halle 1, Regal 4, Regalboden 2, Lagerort 6).

[#lagerreichweite]
Lagerreichweite:: Zeitraum (in Tagen), für den der Warenbestand bis zur nächsten Nachbestellung reichen soll.

[#laufweg]
Laufweg:: Weg, nach dem das Lager beim Picken von Ware abgelaufen wird.

[#mandant]
Mandant:: Eine Instanz von plentymarkets. Es ist möglich, mehrere Mandanten in einem einzelnen System zu verwalten.

[#offene-posten]
Offene Posten:: Auch OP-Liste genannt. Zeigt eine Übersicht über Kunden mit unbezahlten Aufträgen (Anzahl der offenen Posten plus Höhe der Forderung) an.

[#plugin]
Plugin:: Eine Erweiterung für das plentymarkets System. Kann auf link:https://marketplace.plentymarkets.com[plentyMarketplace^] gekauft oder über Git und die Tools plentyDrive und plentyDevTool in das System eingebunden werden.

[#plugin-set]
Plugin-Set:: Eine Sammlung von Plugins. Kann mit Mandanten und <<backend-plugin-set,Backend-Benutzerkonten>> verknüpft werden.

[#portotabelle]
Portotabelle:: xxx

[#rollende kommissionierung]
Rollende Kommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Mehrere Aufträge werden gleichzeitig gepickt, verpackt und versandfertig vorsortiert and den Packtisch geliefert. Auch als "rollende Boxenkommissionierung" bekannt.

[#sammelkommissionierung]
Sammelkommissionierung:: Methode der Zusammenstellung von Artikeln aus Aufträgen. Mehrere Aufträge werden auf einmal bearbeitet. Alle Artikel werden in nur einen Behälter kommissioniert und erst am Packtisch werden die Artikel den einzelnen Aufträgen zugeordnet.

[#stammdaten]
Stammdaten:: Grundinformationen eines Benutzers (z.B. Kontaktdaten wie Firmenname, Anschrift, Telefonnummer etc.).

[#standard-mandant]
Standard-Mandant:: Der <<mandant,Mandant>>, der mit dem Vertrag des Systems verbunden ist. Einige Funktionen sind nur über den Hauptmandanten möglich. Dazu gehören z.B. Ereignisaktionen und Aufrufe über die REST-API.

[#verkaufsgutschein]
Verkaufsgutschein:: Eine der beiden Arten des Gutscheintyps *Gutschein*. Wird als Anzahlung des Rechnungsbetrags gesehen. Die zweite Gutscheinart ist der <<#aktionsgutschein, Aktionsgutschein>>.

[#versandprofil]
Versandprofil:: xxx

[#warenausgang]
Warenausgang:: Ware wird aus dem System ausgebucht und der Warenbestand wird reduziert.

[#warenbestand]
Warenbestand:: Menge der Ware, die aktuell im Lager vorhanden ist.

[#wareneingang]
Wareneingang:: Ware wird in das System eingebucht und der Warenbestand wird erhöht.

[#zuordnung]
Zuordnung:: Legt beim Datenimport fest, welche Spalte einer CSV-Datei welchem Datenfeld in plentymarkets entspricht.
