[glossary]
= Glossar
:lang: de
include::{includedir}/_header.adoc[]
:description: Glossar für plentymarkets
:position: 300
:url: glossar

[glossary]
Fulfillment:: Beschreibt alle Aktivitäten und Abläufe, die nach Abschluss eines Artikelkaufs der Belieferung des Kunden und der Erfüllung sonstiger Vertragspflichten dienen.
Handelsvertreter:: Vermittelt als selbstständiger Gewerbetreibender Geschäfte für ein anderes Unternehmen oder schließt Geschäfte in dessen Namen ab.
Kundenklasse:: Ermöglicht die Unterteilung des Kundenstamms nach unterschiedlichen Kriterien. Anschließend können unterschiedliche Rabatte für die Kundenklassen vergeben werden.
Kundentyp:: Dient der Einordnung und Unterscheidung von Kontakten.
Offene Posten:: Auch OP-Liste genannt. Zeigt eine Übersicht über Kunden mit unbezahlten Aufträgen (Anzahl der offenen Posten plus Höhe der Forderung) an. 
Plugin:: Eine Erweiterung für das plentymarkets System. Kann auf plentyMarketplace gekauft oder über Git und die Tools plentyDrive und plentyDevTool in das System eingebunden werden.
Plugin-Set:: Eine Sammlung von Plugins. Kann mit Mandanten und Backend-Benutzerkonten verknüpft werden.
