= Handbuch
:lang: de
include::{includedir}/_header.adoc[]
:description: Mit unserem Online-Handbuch erhältst einen ausführlichen Leitfaden durch jeden Bereich deines plentymarkets Systems. Jetzt lesen!
:position: 10

== plentymarkets zum Nachlesen und Verstehen

[.row]
====
[.col-md-6]
=====
Das plentymarkets Handbuch unterstützt Sie von den ersten Schritten bis zur Einrichtung komplexer Prozesse. Die Funktionen Ihres plentymarkets Systems werden thematisch und menüübergreifend beschrieben. So sind z.B. alle Schritte zur Einrichtung eines Marktplatzes, von A wie Artikel bis Z wie Zahlung, auf einer Handbuchseite beschrieben. Ergänzend finden Sie im Handbuch unsere Video-Tutorials, die Sie einleitend oder zusätzlich zu den thematischen Inhalten des Handbuchs nutzen können.
Die neue Themenstruktur orientiert sich an den von plentymarkets angebotenen Modulen und enthält Erläuterungen zum Einrichten in plentymarkets 7. Diese Erläuterungen können Sie auch über den Verzeichnisbaum links aufrufen. Erläuterungen zu plentymarkets 6 sind nur links über den Verzeichnisbaum aufrufbar.
=====

[.col-md-6]
=====
video::204176670[vimeo]
=====
====
[.tileList]
* <<basics/versionswechsel#,icon:seven[set=plenty]plentymarkets 7  >>
* <<basics/arbeiten-mit-plentymarkets#,icon:plenty-p[set=plenty]Arbeiten mit plentymarkets >>
* <<artikel#,icon:item[set=plenty]Artikel >>
* <<multi-channel#,icon:multi-channel[set=plenty]Multi-Channel >>
* <<payment#,icon:banknote[set=plenty]Payment  >>
* <<warenwirtschaft#,icon:europallet[set=plenty]Warenwirtschaft  >>
* <<fulfillment#,icon:deliveryman[set=plenty]Fulfillment  >>
* <<crm#,icon:people[set=plenty]CRM  >>
* <<basics/datenaustausch#,icon:data-exchange[set=plenty]Datenaustausch  >>
* <<plentymarkets-pos#,icon:plenty-app[set=plenty]POS  >>
* <<basics/plugins#,icon:puzzle-piece[set=plenty]Plugins  >>
[.collapseBox]
.Aufbau des Handbuchs – Handbuchkonventionen
--
Das Handbuch richtet sich an Anwender der Software, d.h. an Personen mit Zugriff auf das plentymarkets Backend. plentymarkets wird stetig weiterentwickelt und Entwicklungen werden regelmäßig veröffentlicht. Die Beschreibungen in diesem Handbuch können deshalb von Ihrem Backend abweichen. In diesem Handbuch werden nicht pauschal alle Einstellungen aufgeführt oder erläutert. Insbesondere wird bewusst darauf verzichtet, selbsterklärende Einstellungen wie Name, Straße usw. zu erläutern. Das Handbuch liefert außerdem keine Informationen zum Leistungsumfang von Partnern, sondern beschreibt lediglich, wie Schnittstellen eingerichtet werden. Informieren Sie sich vor der Einrichtung einer Schnittstelle über den Partner und das Leistungsangebot.

[.row]
=====
[.col-md-6]
.Formatierungen
======
* Menüpfade sowie Begriffe, die auf der Softwareoberfläche vorkommen, werden **fett** dargestellt.
* Bild- und Tabellenunterschriften werden __kursiv__ dargestellt.
* Rote Boxen weisen auf Gefahren wie Datenverlust hin.
* Gelbe Boxen weisen auf mögliche Fehlkonfigurationen und Fehlerquellen hin.
* Grüne Boxen beschreiben Beispiele oder alternative Einstellungen. Bei diesen Hinweisen besteht in der Regel kein Handlungsbedarf.
======

[.col-md-6]
.Abbildungen
======
Wenn in diesem Handbuch Webseiten und Eingabemasken abgebildet werden, handelt es sich um eine Darstellung, wie sie die Webbrowser Mozilla Firefox oder Google Chrome unter dem Betriebssystem Mac OS X liefern. Wenn Sie ein anderes Betriebssystem oder einen anderen Webbrowser verwenden, kann sich die Darstellung von der hier gezeigten unterscheiden. Die in den Abbildungen dargestellten Einstellungen stellen nur Möglichkeiten dar und können von Ihrem Anwendungsfall abweichen.
======
=====

[.row]
=====
[.col-md-6]
.Suche
======
Ein Eingabefeld für Suchbegriffe finden Sie rechts oben im Handbuch.
======

[.col-md-6]
.Ereignisaktion einrichten
======
Klicken Sie auf die Überschrift, um diese häufig wiederkehrende Handlungsanweisung aufzuklappen und die einzelnen Schritte zu sehen.
======
=====
--

[.row]
====
[.col-md-12]
.plentymarkets Changelog
=====
Im Changelog erhalten Sie einen Überblick über alle Neuerungen, Änderungen und Optimierungen der aktuellen plentymarkets Version. Außerdem erfahren Sie, an welchen Stellen Sie die Konfiguration prüfen sollten, um die optimale Funktion zu gewährleisten.

link:https://forum.plentymarkets.com/c/changelog?order=created[Zum Changelog ]
=====
====
