= Kassensystem/POS
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, POS, Kassensystem, plentymarkets Kasse, plentymarkets Kassensystem, plentymarkets App, Gutscheine, Gutscheine Kasse, Click and Collect
:position: 120
:url: pos
:nav-alias: Übersicht
:id: 8OEUR6U

[#100]
== Was ist plentymarkets POS?

plentymarkets POS (*P*oint *of* *Sale*) ist unser eigens entwickeltes Kassensystem, mit dem du den stationären Handel im Ladengeschäft mühelos abwickelst. Dieser  Handbuchbereich bietet dir einen Überblick über alle Informationen zur Einrichtung und optimalen Nutzung von plentymarkets POS.

[TIP]
.POS Demo-Modus
====
Du interessierst dich für plentymarkets POS und möchtest dir selbst einen unverbindlichen Eindruck von den Funktionen verschaffen? Dann findest du <<pos/demo#, hier>> eine ausführliche Anleitung zur Nutzung des Demo-Modus von plentymarkets POS.
====

[#200]
== Welche Schritte gehören zur Einrichtung?

Du hast dich bereits entschieden, plentymarkets POS als Kassensystem in deinem Ladengeschäft zu nutzen? Prima! Schaue dich auf den folgenden Seiten um, um Anleitungen und Kontakt zu unseren Servicepartnern zu erhalten.

* link:https://www.plentypos.de/[Passende Hardware auswählen^]
* <<pos/pos-einrichten#, plentymarkets POS einmalig einrichten>>
* <<pos/pos-kassenbenutzer#, plentymarkets POS als Kassenpersonal nutzen>>

[#300]
== Welche Funktionen stehen dir zur Verfügung?

Dein fertig eingerichtetes plentymarkets POS System bietet dir umfassende Möglichkeiten, dein Tagesgeschäft im stationären Handel komfortabel abzuwickeln.

** <<pos/pos-kassenbenutzer#30, Kassieren>>
** <<pos/pos-best-practice#10, Gutscheine verkaufen und einlösen>>
** <<pos/pos-kassenbenutzer#173, Stornierungen und Retouren>>
** <<pos/pos-best-practice#100, Online-Bestellungen an der Kasse abschließen (Click & Collect)>>
** <<pos/pos-kassenbenutzer#180, Einlagen und Entnahmen>>
** <<pos/pos-kassenbenutzer#210, Tagesabschluss und Kassensturzbericht>>

[#400]
== Auf dem Laufenden bleiben

Wartest du sehnsüchtig auf ein neues Feature für plentymarkets POS? Wir informieren dich gerne über Änderungen an der Software! Änderungen werden link:https://forum.plentymarkets.com/c/changelog/changelog-app[in einem Changelog^] veröffentlicht. Abonniere den Changelog und bleibe immer auf dem Laufenden.
