= Schnelleinstieg
:lang: de
include::{includedir}/_header.adoc[]
:position: 10

////

Diese Seite enthält den alten Einleitungstext!

TO DO:
Komplett umschreiben!

////


Dieser Schnelleinstieg unterstützt Sie dabei, Ihren Webshop einzurichten und im Internet zu veröffentlichen. Alle Themen sind noch ausführlicher in den Kapiteln des Handbuchs beschrieben, zu denen Sie z.B. über die Verlinkungen gelangen.

Der Schnelleinstieg ist in die Kapitel <<#10, Basiseinstellungen>>, <<#250, Artikelkatalog aufbauen>>, <<#500, Webshop einrichten>> und <<#750, Automatismen einrichten>> untergliedert, die jeweils einen Teilbereich der Einrichtung Ihres Webshops abdecken. Arbeiten Sie diese Kapitel in der bestehenden Reihenfolge durch, da die Kapitel aufeinander aufbauen. Die schnelle Einrichtung eines funktionsfähigen Webshops steht im Vordergrund, weshalb nur die dafür notwendigen Funktionen beschrieben sind.

Die Unterkapitel *Vorbereitung* beinhalten wichtige Voraussetzungen sowie Vorarbeiten. In den nachfolgenden Unterkapiteln wird die eigentliche Einrichtung des Systems beschrieben, wobei jeder Schritt ausführlich erläutert und übersichtlich dargestellt wird. Die anschließende Checkliste gibt Ihnen Gelegenheit zu prüfen, ob die wesentlichen Schritte durchgeführt wurden.

Der <<#1000, Final Check>> ist der Abschlusstest vor der endgültigen Live-Schaltung Ihres plentymarkets Systems. Führen Sie den Final Check sorgfältig durch, damit Sie kaufwillige Besucher nicht zu unfreiwilligen Betatestern umfunktionieren, sondern dann bereits erste Umsätze verbuchen können. Machen Sie sich außerdem mit den rechtlichen Rahmenbedingungen des Online-Handels vertraut und achten Sie auf die Einhaltung der Vorschriften, da Ihnen sonst kostspielige Abmahnungen Ihrer Konkurrenten drohen können.
