= Start
:lang: de
include::{includedir}/_header.adoc[]
:position: 103

**plentymarkets » Start**

== Inhalt dieses Kapitels

In diesem Kapitel finden Sie Erläuterungen zu verschiedenen Tools zur Organisation Ihres plentymarkets-Systems, z.B. das umfangreiche **Statistikmodul** und den **Kalender**. Diese Bereiche helfen Ihnen bei der Auswertung und Planung Ihrer Geschäfte.

Im Kapitel **plentymarkets-Konto** finden Sie ausführliche Informationen zum **Service-Center**, in dem Sie Eckdaten Ihres Systems und Ihres Vertrages einsehen und teilweise direkt anpassen können. Auch den Bereich **Update** finden Sie dort.

Weitere Seiten in diesem Kapitel mit Informationen zu unserem **Support** erläutern die Vorgehensweise, wenn Sie bei Fragen oder Problemen über das Telefon oder ein Ticket Kontakt zu uns aufnehmen möchten.

== Videotutorials

Hier finden Sie Videos zu Themen, die in diesem Handbuchkapitel beschrieben werden.

Erfahren Sie mehr zum Menü **Statistik** im folgenden Videotutorial:

[.linkBox]
link:https://www.plentymarkets.eu/a-2355/[Einführung Statistik, window="_blank"]

