= Warenwirtschaft
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Waren, Wareneingang, Warenausgang, Warenwirtschaft, Bestand, Bestandsautomatik, Warenbestand
:position: 40
:url: warenwirtschaft
:id: 200DET3
:nav-alias: Übersicht

Die in plentymarkets integrierte Warenwirtschaft unterstützt dich dabei, den Überblick über deine aktuellen Bestände, den Zulauf und Ausgang zu behalten. Die Warenwirtschaft ermöglicht das Pflegen mehrerer Lager, das Reservieren von Beständen sowie automatisierte Bestandsaktualisierungen.
In diesem Themenbereich findest du Informationen zum Erstellen und Bearbeiten von Lagern, Einbuchen und Zuordnen von Beständen sowie zum Nachbestellen von Waren.
Nur wenn du Bestände führst, kann dein System Bestand reservieren und automatisch reduzieren, sobald der Warenausgang für einen Auftrag gebucht wird. Reservierungen verhindern, dass bereits verkaufte Ware doppelt verkauft wird.

Grob gilt folgende Reihenfolge für das Einrichten der Warenwirtschaft:

* Lager erstellen
* Lieferanten erstellen
* Wareneingang buchen
* Nachbestellung erstellen

Für eine funktionierende Warenwirtschaft spielen viele Punkte eine Rolle. Dazu gehören das Pflegen von Meldebeständen und Mindestabnahmen für Varianten, das Kontrollieren von Beständen oder von Zuläufen aus Bestellungen sowie Retouren, aber auch Inventuren. Ein weiterer Punkt ist das Reservieren von Bestand für Listings - auch das ist möglich. Wie du für Listings Bestand reservierst, wird auf den Seiten der Listingplattformen beschrieben. Rund um das Thema Warenwirtschaft schließen sich noch viele Themen an, z.B. das Erstellen von Picklisten. Wie du deine Picklisten korrekt erstellst und alle weiteren Schritte, die für den Versand notwendig sind, erfährst du im Bereich Fulfillment.

[.row]
====
[.col-md-6]
.Lager planen und einrichten
=====
* <<warenwirtschaft/lager-einrichten#100, Lager planen>>
* <<warenwirtschaft/lager-einrichten#200, Lager einrichten>>
* <<warenwirtschaft/lager-einrichten#700, Packen vorbereiten>>
* <<warenwirtschaft/lager-einrichten#800, Lagerorte scannen ermöglichen>>
=====

[.col-md-6]
.Warenmengen erfassen und einbuchen
=====
* **<<crm/kontakte-verwalten#20, Lieferanten anlegen>>**
* **<<warenwirtschaft/wareneingaenge-verwalten#100, Lieferanten einer Variante zuordnen>>**
* **<<warenwirtschaft/wareneingaenge-verwalten#200, Lagerort einer Variante angeben>>**
* **<<warenwirtschaft/wareneingaenge-verwalten#500, Wareneingang und Mengen erfassen>>**
* **<<warenwirtschaft/wareneingaenge-verwalten#1200, Bestand auf Varianten buchen>>**
* **<<warenwirtschaft/warenbestaende-verwalten#1300, Warenbewegung durch Wareneingang einsehen>>**
=====

[.col-md-6]
.Bestände überblicken und nachbestellen
=====
* **<<warenwirtschaft/warenbestaende-verwalten#100, Welche Bestände gibt es?>>**
* **<<warenwirtschaft/warenbestaende-verwalten#200, Wann wird Bestand reserviert?>>**
* **<<warenwirtschaft/warenbestaende-verwalten#500, Bestand umbuchen>>**
* **<<warenwirtschaft/nachbestellungen-verwalten#500, Meldebestand für Varianten pflegen>>**
* **<<warenwirtschaft/nachbestellungen-verwalten#600, Mindestabnahme für Varianten pflegen>>**
* **<<warenwirtschaft/nachbestellungen-verwalten#300, Nachbestellungsdokument erstellen>>**
* **<<warenwirtschaft/nachbestellungen-verwalten#900, Varianten unter Meldebestand nachbestellen>>**
* **<<warenwirtschaft/nachbestellungen-verwalten#1800, Bestellte Ware stornieren>>**
* **<<warenwirtschaft/nachbestellungen-verwalten/nachbestellungen-in-arbeitsschritte-gliedern#, Nachbestellungen in Arbeitsschritte gliedern>>**
* **<<warenwirtschaft/nachbestellungen-verwalten/rueckstandsliste-verwalten#, Warenzulauf prüfen>>**
* **<<warenwirtschaft/inventur-vornehmen#, Inventur vornehmen>>**
=====

[.col-md-6]
.Waren ausbuchen
=====
* **<<warenwirtschaft/waren-ausbuchen#2, Warenausgang automatisieren>>**
* **<<warenwirtschaft/waren-ausbuchen#3, Stornierungen, Retouren und Gewährleistungen bearbeiten>>**
* **<<warenwirtschaft/waren-ausbuchen#4, Warenausgang manuell vornehmen>>**
=====

[.col-md-6]
.Mindesthaltbarkeitsdatum (MHD) und Chargen
=====
* **<<warenwirtschaft/mhd-charge-verwalten#, Übersicht>>**
* **<<warenwirtschaft/wareneingaenge-verwalten#200, MHD/Charge aktivieren>>**
* **<<warenwirtschaft/wareneingaenge-verwalten#810, Wareneingang>>**
* **<<warenwirtschaft/warenbestaende-verwalten#500, Umbuchen>>**
* **<<warenwirtschaft/waren-ausbuchen#600, Retoure>>**
* **<<auftraege/auftragsdokumente/pickliste#, Pickliste>>**
* **<<auftraege/auftragsdokumente/packliste#, Packliste>>**
* **<<auftraege/auftragsdokumente/lager-pickliste#, Lager-Pickliste>>**
=====


====

'''
