= Entwurf_Amazon
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

[#3100]
== Herstellerartikeldaten von Amazon importieren

Sie haben hier die Möglichkeit, Ihre Artikel im Amazon-Datenformat als CSV-Datei in Ihr plentymarkets System zu importieren. Dabei werden die folgend beschriebenen Spaltenkopfbezeichnungen vorausgesetzt. Nur bei entsprechender Benennung kann ein erfolgreicher Import gewährleistet werden. Das Format dient ausschließlich zum Import.

.Herstellerartikeldaten von Amazon importieren
[cols="a,a"]
|====
|Spaltenkopfbezeichnung |Erklärung

|**variation_no**
|Variantennummer. Mit Hilfe dieser Nummer können Artikelvarianten identifiziert werden.

|**vendor_external_id**
|Externe Artikel-ID. über diese ID wird der Artikel identifiziert. Falls der Artikel nicht bereits in plentymarkets existiert, wird er angelegt.

|**item_no**
|Frei wählbare Artikelnummer.

|**ean_upc_code**
|EAN- bzw. UPC-Wert des Artikels oder der Variante.

|**fedas**
|

|**brand_name**
|Name des Herstellers.

|**product_type**
|Modellname

|**product_title**
|Artikelname

|**attribute_1**
|Das erste Attribut der Variante. Beispiel: Größe. +
Die Attributwerte **attribute_1** und **attribute_2** müssen beide vorhanden sein oder beide fehlen. Wenn nur ein Attribut angegeben ist, wird dieses ignoriert und der Artikel wird so behandelt, als hätte er keine Varianten.

|**attribute_2**
|Das zweite Attribut der Variante. Beispiel: Farbe. +
Die Attributwerte **attribute_1** und **attribute_2** müssen beide vorhanden sein oder beide fehlen. Wenn nur ein Attribut angegeben ist, wird dieses ignoriert und der Artikel wird so behandelt, als hätte er keine Varianten.

|**list_price**
|Einkaufspreis (EK) des Artikels oder der Variante.

|**expected_street_price**
|Unverbindliche Preisempfehlung (UVP) des Herstellers.

|**detail_info_1 +
... +
detail_info_5**
|Fünf Felder mit Informationen über den Artikel oder die Variante. Diese Felder werden zusammengefügt und als Artikelbeschreibung gespeichert.

|**description**
|Vorschautext

|**free_1 +
... +
free_20**
|Freitextfelder 1 bis 20.

|**asin**
|Artikel- oder Varianten-ASIN-Nummer von Amazon.

|**isbn**
|Artikel- oder Varianten-ISBN.

|**fsk**
|FSK-Wert des Artikels oder der Variante. +
Mögliche Werte: +
**0**: Keine Einschränkung +
**3**,**6**,**9**,**12**,**16** oder **18**: FSK 3, 6, ... 18 +
**50**: nicht gekennzeichnet +
**88**: nicht erforderlich
|====

[IMPORTANT]
.Spaltenkonfiguration
====
Die Reihenfolge der Spalten ist nur für die ersten beiden Spalten ('variation_no' und 'vendor_external_id') in der CSV-Datei wichtig, denn diese dienen der Identifizierung des Formats. Spalten dürfen nicht fehlen, können aber leer gelassen werden. Dies gilt jedoch nicht für die zweite Spalte 'vendor_external_id'. Fehlt dieser Wert, kann der Artikel nicht eindeutig identifiziert werden und wird somit nicht importiert.
====

[WARNING]
.Varianten
====
Wenn eine Variante einen anderen Preis als der Artikel hat, wird trotzdem der Artikelpreis übernommen. Die Differenz muss dann manuell als Markup in ein Attribut geschrieben werden.
====

Beim Starten des dynamischen Imports können Sie wählen, welches Feldtrennzeichen die CSV-Datei enthält. Die Namen der Attribute können aus den in Ihrem plentymarkets System enthaltenen Attributen gewählt werden. Achten Sie darauf, nicht zweimal das gleiche Attribut zu wählen.

**FBA-Aktionspreis** = Um Aktionspreise bei Amazon anzubieten, m&amp;uuml;ssen eine Startzeit und eine Endzeit als Merkmale eingetragen sein. Diese Merkmale werden im Men&amp;uuml; **Einstellungen &amp;raquo; Artikel &amp;raquo; Merkmale &amp;raquo; Tab: Neues Merkmal** in der Spalte **Amazon-Verkn&amp;uuml;pfung** erstellt. Weitere Details zu Merkmalen bei Amazon finden Sie auf der Handbuchseite link::/[**Merkmalverkn&amp;uuml;pfung**].

=== Repricing einstellen

Repricing in plentymarkets wird &amp;uuml;ber unseren Technologiepartner **link:https://ssw.starsellersworld.com/[starsellersworld^]** erm&amp;ouml;glicht. Dazu werden Artikel und Preisinformationen automatisiert an Starsellersworld &amp;uuml;bergeben. F&amp;uuml;r die Einrichtung von Starsellersworld finden Sie eine umfangreiche Anleitung &amp;uuml;ber diesen **link:http://www.starsellersworld.com/doc/starsellersworld-%5Bknowledge-&amp;amp;-best-practice-KIT%5D-Leitfaden-PlentyMarkets.pdf[Link^]**. +
Um Repricing in plentymarkets nutzen zu k&amp;ouml;nnen, ist auch die Einrichtung des Datenexports im Men&amp;uuml; link::/[**Einstellungen &amp;raquo; M&amp;auml;rkte &amp;raquo; Amazon &amp;raquo; Datenaustausch &amp;raquo; Datenexport**] erforderlich. Weitere Details zur Einrichtung des Datenexports finden Sie auf der Handbuchseite link::/[**Datenexport**].

[cols="a,a"]
|====
|Einstellung |Erl&amp;auml;uterung

|**Exporttyp**
|W&amp;auml;hlen, welche Artikel beim Export an Amazon &amp;uuml;bertragen werden sollen. **ALLE** oder **Nur Artikel mit positivem Warenbestand** w&amp;auml;hlen. +
Dazu auch den Eintrag zur Einstellung **Menge f&amp;uuml;r Artikel ohne Bestandsbindung** in Tabelle 3 beachten.

|**Preisspalte Mindestpreis**
|Wenn innerhalb von starsellersworld keine dynamische Berechnung des Verkaufspreises erfolgen soll, kann ein Mindestverkaufspreis &amp;uuml;bergeben werden. Dazu muss bei der Option **Preisspalte Mindestpreis** eine Preisspalte ausgew&amp;auml;hlt werden, die den Mindestverkaufspreis brutto enth&amp;auml;lt.

|**Netto-Einkaufspreis**
|Wenn der Einkaufspreis &amp;uuml;bergeben wird, kann eine dynamische Berechnung des Verkaufspreises bei starsellersworld vorgenommen werden. Die daf&amp;uuml;r n&amp;ouml;tigen Regeln werden direkt bei starsellersworld hinterlegt. Wurde f&amp;uuml;r einen Artikel kein Einkaufspreis definiert oder sollen keine Einkaufspreise &amp;uuml;bergeben werden, wird der Preis aus der Spalte &amp;uuml;bergeben, die bei **Preisspalte Mindestpreis** definiert wurde.

|**Preisspalte Festpreis**
|Sofern Artikel mit Preisbindung angeboten werden, kann mittels der Option **Preisspalte Festpreis** eine Preisspalte eingestellt werden, die einen Festpreis enth&amp;auml;lt. Wenn bei einem Artikel in dieser Preisspalte ein Wert gr&amp;ouml;&amp;szlig;er Null enthalten ist, wird kein Repricing f&amp;uuml;r diesen Artikel vorgenommen.

|**Festpreisverwendung**
|**Variante 1 f&amp;uuml;r alle Artikel** = Der gew&amp;auml;hlte Festpreis wird verwendet. +
**Variante 2 f&amp;uuml;r alle Artikel** = Der Festpreis wird verwendet, wenn der vom Repricing ermittelte Preis oberhalb des Festpreises liegt. Anderenfalls wird der regul&amp;auml;re Artikelpreis verwendet. +
**Variante 3 f&amp;uuml;r alle Artikel** = Der Festpreis wird verwendet, wenn der vom Repricing ermittelte Preis unterhalb des Festpreises liegt. +
Optional kann ein link::/[**Freitextfeld**] mit individuell definierten Varianten 1, 2 oder 3 angegeben werden.

|**Versandkosten**
|W&amp;auml;hlen, ob Versandkosten f&amp;uuml;r den Artikel f&amp;uuml;r das Repricing &amp;uuml;bertragen werden sollen oder nicht.

|**Freitext 1**; +
**Freitext 2**
|link::/[**Freitextfelder**] f&amp;uuml;r zus&amp;auml;tzliche Informationen w&amp;auml;hlen, die beim Repricing &amp;uuml;bertragen werden sollen.

|**Datenlink**
|URL muss komplett markiert und bei starsellersworld eingef&amp;uuml;gt werden, um die &amp;Uuml;bergabe der Artikelstammdaten an starsellersworld zu erm&amp;ouml;glichen.
|====

__Tab. 5: Einstellungen im Tab **Repricing**__

[#4550]
== Amazon Business einrichten

Mit Amazon Business registrieren verkaufen Sie Ihre Artikel an gewerbliche Kunden. Bevor Sie Einstellungen in plentymarkets vornehmen, registrieren Sie sich bei Amazon für das Verkäuferprogramm. Damit Ihre Artikel als B2B-Artikel an Amazon übermittelt werden, muss Amazon Business für das Amazon-Konto freigeschalten werden und Verkaufspreise für B2B angelegt sowie mit dem Artikel verknüpft sein. Nehmen Sie die im Folgenden beschriebenen Einstellungen vor, um B2B-Artikel an Amazon zu übermitteln.

[#4555]
=== B2B freischlaten

Im Menü **System » Märkte » Amazon » Einstellungen** schalten Sie das Amazon-Konto für Amazon Business frei.

[.instruction]
Amazon-Konto für B2B freischalten:

. Öffnen Sie das Menü **System » Märkte » Amazon » Einstellungen » Konto öffnen » Tab: Einstellungen**.
. Setzen Sie ein Häkchen bei der Option **B2B**.
. **Speichern** Sie die Einstellungen.

[#4560]
=== Verkaufspreis konfigurieren

Nachdem das Amazon-Konto für B2B freigeschalten wurde, müssen Sie Verkaufspreise für B2B-Artikel anlegen und verknüpfen. Sie können neben dem Standardpreis für Artikel ab Menge 1 bis zu 5 weitere Preise für Mengenrabatte anlegen. Dabei können Preise für Mengenrabatt als Festpreis oder prozentual angelegt werden.

[#4565]
==== Verkaufspreis anlegen

Legen Sie zunächst einen Standardpreis für B2B-Artikel an. Dabei müssen im Menü **System » Artikel » Verkaufspreise** die Option **Ab Menge**, die **Herkunft** und das **Amazon-Konto** eingestellt werden.

[.instruction]
Standardverkaufspreis für B2B-Artikel anlegen:

. Öffnen Sie das Menü **System » Artikel » Verkaufspreise**.
. Klicken Sie auf **Neu**. +
→ Das Tab **Neu** wird geöffnet.
. Tragen Sie bei der Option **Ab Menge** eine **1** ein.
. Wählen Sie die Herkunft **Amazon Germany B2B**.
. Wählen Sie das **Amazon-Konto**, das für Amazon B2B freigeschalten ist.
. Nehmen Sie weitere Einstellungen gemäß Tabelle 10 auf der Seite **<<artikel/artikel-verwalten#880, Artikel verwalten>>** vor.
. **Speichern** Sie die Einstellungen.

[#4570]
==== Verkaufspreis für Mengenrabatt anlegen

Gehen Sie wie im folgenden beschreiben vor, um B2B-Kunden Mengenrabatt anzubieten.

[.instruction]
Verkaufspreis für Mengenrabatt anlegen:

. Öffnen Sie das Menü **System » Artikel » Verkaufspreise**.
. Klicken Sie auf **Neu**. +
→ Das Tab **Neu** wird geöffnet.
. Tragen Sie bei der Option **Ab Menge** die Mege ein, ab welcher der Verkaufspreis gelten soll. Die Menge muss größer als 1 sein.
. Wählen Sie die Herkunft **Amazon Germany B2B**.
. Wählen Sie das **Amazon-Konto**, das für Amazon B2B freigeschalten ist.
. Nehmen Sie weitere Einstellungen gemäß Tabelle 10 auf der Seite **<<artikel/artikel-verwalten#880, Artikel verwalten>>** vor.
. **Speichern** Sie die Einstellungen.

Alternativ lassen sich bis zu 5 Verkaufspreise für den Mengenrabatt auch prozentual über Merkmalverknüpfungen darstellen. Dafür wird beim Anlegen des Merkmals vom Typ **Auswahl** oder **Text** die Amazon-Verküpfung **quantity_price_type** gewählt und bei der Artikelverknüpfung der Wert **percent** eingegeben. Zusätzlich müssen Merkmale mit den Amazon-Verknüpfungen **quantity_lower_bound1-5** für die Rabattmenge und **quantity_price1-5** für die Prozentzahl angelegt werden.

[.instruction]
Merkmal quantity_price_type anlegen:

. Öffnen Sie das Menü **System » Artikel » Merkmale**.
. Klappen Sie das Merkmal auf, das Sie für Amazon verwenden möchten. +
→ Der Bearbeitungsbereich des Merkmals wird geöffnet.
. Wählen Sie bei **Amazon-Verknüpfung** den Produkttyp. +
→ Ein neues Dropdown-Menü erscheint.
. Wählen Sie im Dropdown-Menü das Amazon-Feld **quantity_price_type**.
. Klicken Sie auf **Hinzufügen**. +
→ Die Verknüpfung wird angelegt.

Aktivieren Sie als nächstes das <<artikel/artikel-verwalten#80, **Merkmal**>> in den Artikeleinstellungen und hinterlegen Sie den Wert **percent**.

[.instruction]
Merkmal am Artikel aktivieren:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab **Merkmale**.
. Setzen Sie bei dem Merkmal ein Häkchen, um das Merkmal zu aktivieren.
. **Speichern** Sie die Einstellungen. +
→ Das Feld für die Eingabe des Wertes wird angelegt.
. Tragen Sie den Wert **percent** ein.
. **Speichern** Sie die Einstellungen.

Legen Sie die Merkmale mit den Amazon-Verknüpfungen **quantity_lower_bound1-5** und **quantity_price1-5** analog an. Wählen Sie dabei für **quantity_lower_bound1-5** Merkmale vom Typ **ganze Zahl** und für **quantity_price1-5** Merkmale vom Typ **ganze Zahl** oder **Kommazahl**.

Versand durch Amazon (FBA) **Aktiv** Durch setzen des Häkchens wird der stündliche FBA-Auftragsimport aktiviert und alle weiteren FBA-Einstellungen freigeschalten. **Herkunft** Wählen, ob nur Aufträge von Amazon mit FBA abgewickelt werden oder ob auch Aufträge von anderen <<omni-channel/auftragsherkunft#, **Herkünften**>> mit FBA abgewickelt werden können. **Retourenimport**; +
**Bestandsimport** Keine Übertragung oder je ein Intervall für den Import wählen. **Status**<<auftragsabwicklung/auftraege/auftraege-verwalten#, **Status**>> der Aufträge wählen, die von Amazon importiert wurden. **Lager** Wählen, welches <<omni-channel/multi-channel/amazon/amazon-einrichten#10, **Lager**>> für den Versand durch Amazon verwendet werden soll. **Warenausgang** Wählen, ob der Warenausgang als gebucht markiert werden soll oder nicht. Die Option **Als gebucht markieren** erzeugt keine Warenbewegung. Um eine Warenbewegung zu erzeugen, muss die Option **Nicht als gebucht markieren** eingestellt sein und eine Ereignisaktion eingerichtet werden. **Status für übertragene Aufträge**<<auftragsabwicklung/auftraege/auftraege-verwalten#, **Auftragstatus**>> für Aufträge wählen, die erfolgreich an FBA übertragen wurden. **Versandkategorie****Standard** = normaler Versand, **Expedited** = Schnellversand oder **Priority** = bevorzugt (schnellster Versand) wählen.

**HTML-Tags erlauben** Die folgenden Tooltips sind zugelassen: &lt; br &gt;, &lt; b &gt;, &lt; i &gt;, &lt; p &gt; ,&lt; ul &gt;, &lt; li &gt;, &lt; table &gt;, &lt; tr &gt;, &lt; td &gt;, &lt; th &gt;, &lt; tbody &gt; und &lt; strong &gt;.

[#2900]
===  Voraussetzung im Seller Central-Portal prüfen

Damit das Abrufen der Aufträge via Schnittstelle möglich ist, muss im Seller Central eine bestimmte Voraussetzung erfüllt sein, die Sie vorab kontrollieren sollten.

Melden Sie sich im Seller Central-Portal an. In den Bestellberichten muss ein Text wie der folgende enthalten sein: **Sie erhalten derzeit geplante Bestellberichte über XML.** Ist dies nicht der Fall bzw. steht dort ein anderer Hinweis, kontaktieren Sie bitte den Amazon-Support, da Sie die notwendigen Einstellungen nicht selbst vornehmen können.

[WARNING]
.Bericht NICHT anfordern
====
Sie dürfen im Bereich **Bestellbericht anfordern** NICHT auf die gelbe Schaltfläche **Bericht anfordern** klicken, da sonst die geplanten Bestellberichte über XML nicht mehr funktionieren. Haben Sie es dennoch versehentlich getan, kontaktieren Sie den Amazon-Support, um die ursprüngliche Einstellung wiederherzustellen.
====

===
