= Entwurf_Lena_2
:lang: de
include::{includedir}/_header.adoc[]
:position: 23

Google Shopping ist ein Dienst von Google mit dem Produkteinträge von Kaufinteressierten auf Google schnell und einfach gefunden werden können. Mit plentymarkets können Artikel automatisch an Google Shopping übergeben werden. Die Übertragung der Artikel an Google erfolgt mittels FTP. Um Google Shopping nutzen zu können, benötigen Sie ein Konto für das Google Merchant Center. Google selbst sagt über das **link:https://support.google.com/merchants/answer/188493?hl=de[Merchant Center, window="_blank"]**: "Google Merchant Center ist ein Tool, mit dem Sie Ihre Händler- und Produktdaten auf Google hochladen und in Google Shopping und anderen Google-Diensten verfügbar machen können."

== Authentifizierung

Erstellen Sie zunächst ein link:http://www.google.de/merchants[**Konto**, window="_blank"] für das Google Merchant Center, um Google Shopping nutzen zu können. Danach müssen Sie Ihren Shop noch authentifizieren. Wählen Sie hierfür die Authentifizierung über den Meta-Tag und fügen Sie diesen Meta-Tag in Ihr Webdesign ein. Sie finden den Meta-Tag im Google Merchant Center.

=== Meta-Tag ins Webdesign einfügen

Das Meta-Tag muss in die Startseite Ihres Shops eingefügt werden. Welches Design für Ihre Startseite verwendet wird, sehen Sie im Tab **Einstellungen** der Kategorie Ihrer Startseite. Meist wird das Template **PageDesignContent** oder das Template **PageDesignCustom** verwendet, weshalb hier exemplarisch das Einfügen in das Template **PageDesignContent** erklärt wird.

[.instruction]
Meta-Tag in PageDesignContent einfügen:

. Öffnen Sie das Menü **CMS » Webdesign » Layout » PageDesign » PageDesignContent**.
. Fügen Sie den Meta-Tag im Tab **PageDesignContentHtmlStructure** ein.
. Klicken Sie auf **Speichern**, um die Einstellungen zu sichern.  +
→ Nun kann Google Ihre Seite authentifizieren.

Die Authentifizierung gilt 1 Jahr und muss dann erneuert werden, indem Sie das neue von Google bereitgestellte Meta-Tag einfügen.

[#1]
== Exportformat anlegen

Bevor Sie ein Exportformat anlegen, beachten Sie die Erläuterungen zur Einrichtung eines **link::/[**Exportformates**]**.

[.instruction]
Exportformat Google Shopping bearbeiten:

. Legen Sie unter **link::/[Einstellungen » Märkte » Preisportale » Exporte » Tab: Neuer Export]** ein neues Exportformat an.  +
→ Im Tab **Exporte** entsteht das entsprechende Untermenü.
. Öffnen Sie im Tab **Exporte** das Untermenü zu **Google Shopping**.
. Nehmen Sie die Einstellungen gemäß Tabelle 1 vor.
. Klicken Sie auf **Speichern**, um die Einstellungen zu sichern.

[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

|**Datenformat**
|Goggle Shopping Deutschland oder Goggle Shopping International als Datenformat wählen.

|**Name**
|Einen Namen für das Exportformat eintragen.  +
Unter diesem Namen wird das Exportformat im Tab **Exporte** als Untermenü angelegt und kann dort bearbeitet werden.

|**Auftragsherkunft**
|Eine Auftragsherkunft für **Google Shopping** wählen.  +
Dadurch wird die URL um den Parameter erweitert. Gelangt ein Kunde über die Preissuchmaschine in Ihren Shop und kauft dort einen Artikel, wird in der Bestellung die URL mit der Auftragsherkunft hinterlegt.  +
Google Shopping gehört zu den Standard-Herkünften. Die Standard-Herkunft für Google Shopping hat die ID 7. Es können auch weitere <<auftragsabwicklung/auftraege/einstellungen/auftragsherkunft#, **Herkünfte**  >> für Google Shopping angelegt und eingestellt werden, um so für jeden Mandanten eine andere Google Shopping-Herkunft zu hinterlegen. So lässt sich leichter nachvollziehen, von welchem Mandanten der Auftrag stammt.

|**Preisspalte**
|Eine Preisspalte wählen. +
**Standard-Preis** = Der Preis, der im Tab **Base** eines Artikels unter **Preis** eingetragen ist, wird übertragen.  +
**Automatisch** = Der Preis, der in der Auftragsherkunft hinterlegt wurde, wird übertragen.

|**Versandkosten übernehmen aus der Versandkostenberechnung**
|**Konfiguration 1** oder **2** wählen. Diese Optionen beziehen sich auf die Standard-Konfigurationen, die im Menü link::/[**Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandkosten berechnen**] für Preisportale hinterlegt sind.  +
Dort sind auch die Einstellungen für die Standard-Zahlungsart für den Export zu Preisportalen hinterlegt. Für die Einstellung hier im Menü besteht für ein Exportformat die Wahl zwischen einer der im Tab **Versandkosten berechnen** hinterlegten Varianten oder der Einstellung **Standard/Vorkasse**.  +
**Wichtig:** Die Zahlungsart **Vorkasse** sollte eingestellt werden, wenn die vorher gewählte **Konfiguration (1 oder 2)** diese Zahlungsart nicht enthält. Bei Ablehnung der hinterlegten Zahlungsarten sollte die Vorkasse als Alternative in jedem Fall angeboten werden, um Fehler bei der Auftragsabwicklung zu vermeiden.

|**Versandkosten überschreiben**
|Einen Betrag eintragen und **Häkchen setzen**, um die Option zu aktivieren. Wenn die Option aktiviert ist, gelten die unter **Versandkosten übernehmen aus der Versandkostenberechnung** vorgenommenen Einstellungen nicht mehr.

|**URL-Parameter**
|Suffix (Anhang) für die Artikel-URL eintragen, wenn dies für den jeweiligen Export erforderlich ist.

|**Cache-Datei generieren**
|Die Cache-Datei wird über Nacht generiert und stellt automatisch einen vollständigen Datenexport zum Download vom Server bereit.  +
Es werden maximal für 20 Exportformate Cache-Dateien erzeugt. Im Standardhosting werden maximal 52.000 Zeilen je Exportformat erzeugt.

2+|Google Shopping Einstellungen

|**Sichtbarkeit**
|Wählen, ob die Sichtbarkeit für **Google Shopping 1** oder **Google Shopping 2** übertragen werden soll.

|**Zielland**
|Land, in dem die Artikel vertrieben werden sollen, wählen.  +
**Google Shopping Deutschland** = Deutschland wird automatisch als Zielland eingestellt.  +
**Google Shopping International** = Ein Zielland aus dem Dropdown-Menü wählen.

|**Dateiname**
|Eine Datei für den Upload wählen.

|**Google FTP-Benutzername**
|FTP-Benutzernamen, wie von Google erhalten, eintragen.

|**Google FTP-Passwort**
|FTP-Passwort, wie von Google erhalten, eintragen.  +
**Achtung:** Die Angaben unter **Google FTP-Benutzername** und **Google FTP-Passwort** nicht mit den Zugangsdaten zu Google verwechseln!

|**Grundpreis übertragen  +
__(nur Google Shopping International)__**
|Angeben, ob der Grundpreis übertragen werden soll und wo er angezeigt werden soll oder den Grundpreis nicht übertragen.  +
Diese Option wird nur angezeigt, wenn es sich bei dem Zielland nicht um ein EU-Land oder die Schweiz handelt.

|**Artikelverfügbarkeit 1-10**
|Die Nummerierung entspricht der in plentymarkets. Einen Text wählen, der am besten zu den an Artikeln hinterlegten Verfügbarkeitstexten passt. Die Auswahltexte hier sind von Google vorgegeben.

|**Sonderangebotspreis**
|Wählen ob der Preis übertragen werden soll und wenn ja welcher Preis übertragen werden soll. Der Sonderangebotspreis wird allerdings nur übertragen, wenn er tatsächlich kleiner ist als der normale Preis.  +
Der Sonderangebotszeitraum, für den der Preis gilt, wird als Merkmal des Typs **Text** im Menü **Einstellungen » Artikel » Merkmale** angelegt und dieses Merkmal muss anschließend mit dem Artikel verknüpft werden.

|**Automatisierter Upload (täglich)**
|**Häkchen setzen** = Der tägliche automatische Upload ist __**aktiviert**__.

2+|Filter

|**Nur Artikel mit Markierung**
|Eine Markierung oder eine der anderen Optionen wählen. +
**Alle Artikel** = Alle Artikel sowohl mit als auch ohne Markierung werden exportiert +
**Alle Artikel mit Markierung** = Nur Artikel, die eine Markierung haben, werden exportiert +
**Alle Artikel ohne Markierung** = Nur Artikel, die keine Markierung haben, werden exportiert.

|**Mandant (Shop)**
|Einen Webshop wählen. Entweder **Standard**-Webshop, einen **Mandant (Shop)** oder **Alle** Webshops.

|**Artikelauswahl (inklusive Varianten)**
|Die zu exportierenden Artikel wählen. Standard: **1-50000**. Wenn mehr als 50.000 Artikel im System sind, werden weitere Optionen auswählbar.

|**Bestand**
|**Alle Artikel** = Alle Artikel werden exportiert.  +
**Nur Artikel mit Bestand oder wo kein Warenbestand geführt wird** = Es werden nur Artikel mit Warenbestand und solche, für die kein Warenbestand geführt wird, exportiert.  +
**Nur Artikel mit Bestand oder keine Bestandsbeschränkung** = Es werden nur Artikel mit Warenbestand und solche ohne **link::/[Bestandsbeschränkung]** exportiert.  +
**Nur Artikel mit Bestand** = Es werden nur Artikel mit Warenbestand exportiert.

2+|Formatierung

|**Bilder exportieren**
|Wählen, welche der hinterlegten Bilder exportiert werden.

|**Artikelname**
|Wählen, welcher der drei hinterlegten Namen exportiert wird.

|**Artikelbeschreibung**
|Wählen, ob die **Beschreibung**, der **Vorschautext** oder die **Technischen Daten** als Beschreibungstext angezeigt wird. Dazu eine **Maximale Zeichenlänge** festlegen.

|**URL**
|URL für die Preissuchmaschinen.

|**Artikel jetzt exportieren**
|Auf diesen Link klicken, um die Artikel zu exportieren.
|====

__Tab. 1: Einstellungen für Google Shopping in plentymarkets__

Nachdem Sie das Exportformat angelegt haben, legen Sie noch die **<<_entwurfsseiten/entwurf-lena/entwurf-lena-2#2, Kategorieverknüpfungen >>** für das Google Shopping-Datenformat an.

[#2]
== Kategorieverknüpfungen für Google Shopping anlegen

In plentymarkets können Sie Kategorieverknüpfungen für Google Shopping Deutschland und Google Shopping International anlegen. Die Bedingungen für Artikel, die an Google Shopping übertragen werden sollen, gelten für beide.

[.subhead]
Welche Artikel werden an Google übertragen?
Grundsätzlich werden Artikel an Google übertragen, die für den Webshop sichtbar sind und bei denen die Optionen **Web-API** und **Google Shopping**aktiviert wurden.

Da Google mindestens einen Bilder-Link pro Artikel verlangt, werden Artikel ohne Bilder-Link nicht übertragen. Beachten Sie dazu auch die Hinweise in Kapitel 3.

Für eine korrekte Funktion müssen bei den Artikeln die Parameter **EAN**, **Hersteller** und **Modell** hinterlegt sein.

In dem von Ihnen angelegten Export für **Google Shopping** legen Sie fest, von welchem Mandant (Shop) die Artikel an Google übertragen werden sollen. Entweder alle Artikel werden mit Link auf den Standard-Shop an Google übergeben oder nur die Artikel aus einem bestimmten Webshop.

=== Google Shopping Deutschland

Die Verknüpfung Ihrer Kategorien mit den Kategorien in Google Shopping erfolgt im Menü **Einstellungen » Märkte » Preisportale » Google Shopping DE**.

[.instruction]
Webshop- und Google-Produktkategorien verknüpfen:

. Öffnen Sie das Menü **Einstellungen » Märkte » Preisportale » Google Shopping DE**.
. Wählen Sie einen **Mandanten**.  +
→ Die Namen der **Kategorien** werden angezeigt.
. Ermitteln Sie die zu Ihren Kategorien passenden Google-Produktkategorien.  +
→ Mehr zum **link:https://support.google.com/merchants/answer/160081?hl=de[Kategorisieren von Produkten bei Google, window="_blank"]** .
. Tragen Sie die Google-Produktkategorien unter **Google Shopping-Verknüpfung** ein. +
**Wichtig:** Die Google-Kategoriebenennungen müssen ohne Anführungszeichen eingetragen werden.
. Klicken Sie auf **Speichern**, um die Einstellungen zu sichern.

=== Kategorieverknüpfungen für Google Shopping International anlegen

Die Verknüpfung Ihrer Kategorien mit den Kategorien in Google Shopping erfolgt im Menü **Einstellungen » Märkte » Preisportale » Google Shopping Int.**

[.instruction]
Webshop- und Google-Produktkategorien verknüpfen:

. Öffnen Sie das Menü **Einstellungen » Märkte » Preisportale » Google Shopping Int.**.
. Wählen Sie einen **Mandanten**.  +
→ Die Namen der **Kategorien** werden angezeigt.
. Ermitteln Sie die zu Ihren Kategorien passenden Google-Produktkategorien.  +
→ Mehr zum **link:https://support.google.com/merchants/answer/160081?hl=en[Kategorisieren von Produkten bei Google, window="_blank"]** .
. Tragen Sie die Google-Produktkategorien unter **Google Shopping-Verknüpfung** ein.  +
**Wichtig:** Die Google-Kategoriebenennungen müssen ohne Anführungszeichen eingetragen werden.
. Klicken Sie auf **Speichern**, um die Einstellungen zu sichern.

[IMPORTANT]
.Kategorieverknüpfungen für Google Shopping International
====
Für Google Shopping International werden nur englische Kategorien verknüpft. Diese sind international gültig und werden von Google automatisch im Länderexport umgesetzt, sodass nicht für jedes Land eine eigene Verknüpfung erstellt werden muss.

Der Beschreibungstext von Artikeln muss in der Sprache des Landes hinterlegt sein, in dem der Artikel verkauft werden soll. Andernfalls erfolgt keine Übertragung.
====

== Verknüpfung der plentymarkets Attribute mit Google Shopping Werten

=== Variantenartikel

Für Variantenartikel müssen Sie alle Attribute mit den passenden Werten bei Google Shopping verknüpfen.

[.instruction]
Verknüpfung der Attribute:

. Öffnen Sie im Menü **<<omni-channel/online-shop/standard/buchhaltung#, Einstellungen » Artikel » Attribute  >>** die jeweiligen Attributeinstellungen.
. Wählen Sie im Tab **Marktplatzvariation** die Option **Google Shopping** aus dem Dropdown-Menü.
. Wählen Sie aus dem Google Shopping-Dropdown-Menü den Wert für Google Shopping, der dem Attribut Ihres Webshops am besten entspricht.
. Klicken Sie auf **Speichern**, um die Einstellungen zu sichern.

=== Weitere Produktinformationen übertragen

Um weitere Produktinformationen, insbesondere für Artikel ohne Varianten, an Google Shopping zu übertragen, legen Sie **link::/[Merkmale]** an. Diese müssen als Merkmale vom Merkmaltyp **Text** angelegt werden.

[IMPORTANT]
.Attribute werden überschrieben
====
Merkmale haben eine höhere Priorität als Attribute, d.h. Merkmale überschreiben Attribute.
====

Bei Google Shopping sind folgende Merkmale Pflicht:

* **Altersgruppe** - Werte: **Erwachsene** und **Kinder**
* **Farbe**
* **Geschlecht** - Werte: **Herren**, **Damen**, **Unisex**
* **Größe**

Neben den Pflichtmerkmalen sind in der Merkmalkonfiguration noch die Merkmale **Material**, **Muster** und **Sonderaktionszeitraum** einstellbar. Der Preis für eine Sonderaktion wird im <<_entwurfsseiten/entwurf-lena/entwurf-lena-2#1, **Exportformat** >> festgelegt.

[.instruction]
Beachten Sie zur Konfiguration folgende Links:

* link:http://support.google.com/merchants/bin/answer.py?hl=de&answer=188494#DE[**Produkt-Feed-Spezifikationen**, window="_blank"]
* link:http://support.google.com/merchants/bin/answer.py?hl=de&answer=188479[**Anzeigen mit Produktinformationen**, window="_blank"]

== Sichtbarkeit der Artikel für Google Shopping einstellen

In den Artikelstammdaten steht Ihnen im Tab **Verfügbar** die Option **Google Shooping** zur Verfügung.

[NOTE]
.Verfügbarkeit einstellen:
====
Setzen Sie für alle Artikel, die Sie für **Google Shopping** sichtbar stellen möchten, ein Häkchen bei der gleichnamigen Option und bei der Option **Web-API** im Menü **link::/[Artikel » Artikel bearbeiten » Tab: Verfügbar]**, sodass der Artikel für Google Shopping verfügbar ist.
====

== Produkt-Feed-Spezifikationen

Seit September 2011 gibt es seitens Google eine Reihe von Änderungen an den Feed-Spezifikationen und Richtlinien für Google Shopping, die die Händler und Nutzer des Merchant Center betreffen. Google gibt dazu kurze Informationen, diese finden Sie **link:http://googlehaendlerblog.blogspot.com/2011/07/fur-merchant-center-nutzer-wichtige.html[hier, window="_blank"]**. Beachten Sie zu dem Thema außerdem unseren link:https://www.plentymarkets.eu/blog/Wichtige-Auml-nderungen-fuer-Google-Products/b-708/[**Blog-Beitrag**]. Wir haben hier die wichtigsten Hinweise für Sie zusammengefasst:

* Beachten Sie die **link:https://support.google.com/merchants/answer/188494?hl=de&hlrm=de#DE[Produkt-Feed-Spezifikationen, window="_blank"]**
* Für Artikel ohne eindeutige Produktkennzeichnung, wie z.B. Antiquitäten, die u.a. keine EAN besitzen, gibt es das Attribut **Kennzeichnung existiert** und den Wert **FALSE**. Dieses Attribut und der Wert werden passenden Artikeln in plentymarkets beim Datenexport automatisch zugeordnet.
* Verwenden Sie keine Datenfeeds mit HTML-Code.
* Die Länge des Produkttitels ist auf 70 Zeichen beschränkt.

== Google Shopping 2

Mit Google Shopping 2 können Sie Ihre Artikel von einem Drittanbieter aufbereiten lassen bevor die Artikel auf Google Shopping platziert werden. Setzen Sie für alle Artikel, die Sie von einem Drittanbieter aufbereiten lassen wollen, ein Häkchen bei der Option **Google Shopping 2** und bei der Option **Web-API** im Menü **link::/[Artikel » Artikel bearbeiten » Tab: Verfügbar]**. Ihre Artikel werden zunächst dem Drittanbieter zur Verfügung gestellt, bevor sie bei Google Shopping platziert werden.

Um für Google Shopping 2 ein Datenformat anzulegen, nehmen Sie die Einstellungen wie unter **Exportformat anlegen** beschrieben vor. Setzen Sie dafür im Untermenü **Google Shopping-Einstellungen** die Option **Sichtbarkeit** auf **Google Shopping 2.**

