= Entwurf_Lena_5
:lang: de
include::{includedir}/_header.adoc[]
:position: 30

[#4550]
== Amazon Business einrichten

Mit Amazon Business verkaufen Sie Ihre Artikel an gewerbliche Kunden. Bevor Sie Einstellungen in plentymarkets vornehmen, link:https://services.amazon.de/programme/b2b-verkaufen/merkmale-und-vorteile.html[registrieren, window="_blank"] Sie sich bei Amazon für das Verkäuferprogramm. Damit Ihre Artikel als B2B-Artikel an Amazon Business übermittelt werden, muss Amazon Business für das Amazon-Konto freigeschalten werden und Verkaufspreise und Mengenrabatte für Amazon Business müssen angelegt sowie mit dem Artikel verknüpft sein. Nehmen Sie die im Folgenden beschriebenen Einstellungen vor, um Artikel an Amazon Business zu übermitteln.

[#4555]
=== Amazon Business freischalten

Im Menü **Einstellungen » Märkte » Amazon » Grundeinstellungen** schalten Sie das Amazon-Konto für Amazon Business frei.

[.instruction]
Amazon-Konto für Amazon Business freischalten:

.  Öffnen Sie das Menü **Einstellungen » Märkte » Amazon » Grundeinstellungen » Konto öffnen » Tab: Einstellungen**.
.  Setzen Sie ein Häkchen bei der Option **B2B**.
. **Speichern** Sie die Einstellungen.

[#4560]
=== Verkaufspreis konfigurieren

Nachdem das Amazon-Konto für Amazon Business freigeschalten wurde, müssen Sie Verkaufspreise für B2B-Artikel anlegen und verknüpfen. Sie können neben dem Standardpreis für Artikel ab Menge 1 bis zu 5 weitere Preise für Mengenrabatte anlegen. Dabei können Preise für Mengenrabatt als Festpreis oder prozentual angelegt werden.

[#4565]
==== Verkaufspreis anlegen

Legen Sie zunächst einen Standardpreis für B2B-Artikel an. Dabei müssen im Menü **Einstellungen » Artikel » Verkaufspreise** die Option **Ab Menge**, die **Herkunft** und das **Amazon-Konto** eingestellt werden.

[.instruction]
Standardverkaufspreis für B2B-Artikel anlegen:

. Öffnen Sie das Menü **Einstellungen » Artikel » Verkaufspreise**.
. Klicken Sie auf **Neu**. +
→ Das Tab **Neu** wird geöffnet.
. Tragen Sie bei der Option **Ab Menge** eine **1** ein.
. Wählen Sie die Herkunft **Amazon Germany B2B**.
. Wählen Sie das **Amazon-Konto**, das für Amazon B2B freigeschalten ist.
. Nehmen Sie weitere Einstellungen gemäß Tabelle 10 auf der Seite **<<artikel/artikel-verwalten#880, Artikel verwalten>>** vor.
. **Speichern** Sie die Einstellungen.

[#4570]
==== Verkaufspreis für Mengenrabatt anlegen

Gehen Sie wie im folgenden beschrieben vor, um Amazon Business Kunden Mengenrabatt anzubieten.

[.instruction]
Verkaufspreis für Mengenrabatt anlegen:

. Öffnen Sie das Menü **Einstellungen » Artikel » Verkaufspreise**.
. Klicken Sie auf **Neu**. +
→ Das Tab **Neu** wird geöffnet.
. Tragen Sie bei der Option **Ab Menge** die Mege ein, ab welcher der Verkaufspreis gelten soll. Die Menge muss größer als 1 sein.
. Wählen Sie die Herkunft **Amazon Germany B2B**.
. Wählen Sie das **Amazon-Konto**, das für Amazon B2B freigeschalten ist.
. Nehmen Sie weitere Einstellungen gemäß Tabelle 10 auf der Seite **<<artikel/artikel-verwalten#880, Artikel verwalten>>** vor.
. **Speichern** Sie die Einstellungen.

Alternativ lassen sich bis zu 5 Verkaufspreise für den Mengenrabatt auch prozentual über Merkmalverknüpfungen darstellen. Dafür wird beim Anlegen des Merkmals vom Typ **Auswahl** oder **Text** die Amazon-Verküpfung **quantity_price_type** gewählt und bei der Artikelverknüpfung der Wert **percent** eingegeben. Zusätzlich müssen Merkmale mit den Amazon-Verknüpfungen **quantity_lower_bound1-5** für die Rabattmenge und **quantity_price1-5** für die Prozentzahl angelegt werden.

[.instruction]
Merkmal quantity_price_type anlegen:

.  Öffnen Sie das Menü **Einstellungen » Artikel » Merkmale**.
.  Klappen Sie das Merkmal auf, das Sie für Amazon verwenden möchten. +
→ Der Bearbeitungsbereich des Merkmals wird geöffnet.
.  Wählen Sie bei **Amazon-Verknüpfung** den Produkttyp. +
→ Ein neues Dropdown-Menü erscheint.
.  Wählen Sie im Dropdown-Menü das Amazon-Feld **quantity_price_type**.
.  Klicken Sie auf **Hinzufügen**. +
→ Die Verknüpfung wird angelegt.

Aktivieren Sie als nächstes das <<artikel/artikel-verwalten#80, **Merkmal**>> in den Artikeleinstellungen und hinterlegen Sie den Wert **percent**.

[.instruction]
Merkmal am Artikel aktivieren:

.  Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
.  Öffnen Sie den Artikel.
.  Wechseln Sie in das Tab **Merkmale**.
.  Setzen Sie bei dem Merkmal ein Häkchen, um das Merkmal zu aktivieren.
. **Speichern** Sie die Einstellungen. +
→ Das Feld für die Eingabe des Wertes wird angelegt.
.  Tragen Sie den Wert **percent** ein.
. **Speichern** Sie die Einstellungen.

Legen Sie die Merkmale mit den Amazon-Verknüpfungen **quantity_lower_bound1-5** und **quantity_price1-5** analog an. Wählen Sie dabei für **quantity_lower_bound1-5** Merkmale vom Typ **ganze Zahl** und für **quantity_price1-5** Merkmale vom Typ **ganze Zahl** oder **Kommazahl**.

