= Entwurf_Lena_4
:lang: de
include::{includedir}/_header.adoc[]
:position: 27

[#1600]
==  Fahrzeugverwendungsliste einrichten

Mit link:http://pages.ebay.de/help/sell/fitment.html[**Fahrzeugverwendungslisten**, window="_blank"] können Sie Verknüpfungen zwischen den passenden Fahrzeugen und dem zu verkaufenden Artikel erstellen. Das erhöht die Verkaufschancen, da die Artikel mit der Fahrzeugverwendungsliste bevorzugt in den Suchergebnissen angezeigt werden. Im Menü **Einstellungen » Märkte » eBay » Fahrzeugverwendungsliste** erstellen, bearbeiten und löschen Sie Fahrzeugverwendungslisten.

[.instruction]
Neue Fahrzeugverwendungsliste erstellen:

.  Öffnen Sie das Menü **Einstellungen » Märkte » eBay » Fahrzeugverwendungsliste**.
. Klicken Sie auf **Neue Fahrzeugverwendungsliste**.  +
→ Das Fenster **Neue Fahrzeugverwendungsliste** wird geöffnet.
.  Tragen Sie einen Namen für Ihre Liste ein. +
→ Der Name kann im Nachhinein geändert werden.
.  Wählen Sie eine **eBay-Plattform** für die Liste.
. Wählen Sie eine **Kategorie**.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dabei die Erläuterungen in den Tabelle X.
. **Speichern** Sie die Einstellungen

.Einstellungen für neue Fahrzeugverwendungsliste
[cols="a,a"]
|====
| Einstellung | Erläuterung

2+| Suche

|**Marke/Jahr; +
Modell; +
Plattform/CCM**
| Wählen Sie die passenden Suchfilter. +
**Marke/Jahr**: Keine Mehrfachauswahl möglich. +
Bei Auswahl der eBay-Plattform **Motors** erscheint der Suchfilter **Jahr** an Stelle von **Marke**.  +
**Plattform/CCM**: Bei Auswahl der Kategorie **Motorrad** erscheint der Suchfilter **CCM** an Stelle von **Plattform**.

|**K-Type-Nr.**
| Erscheint nur bei Auswahl der Kategorie **Auto**. Wird hier die K-Type-Nr. hinzugefügt, werden die Suchfilter nicht berücksichtigt.

2+| Liste

|**Fahrzeugliste**
| Alle verfügbaren Varianten eines Fahrzeugs werden in der Liste erfasst. Die Liste ist auf 1000 Einträge begrenzt. Bei mehr als 1000 Einträgen muss eine weitere Liste für den Artikel angelegt werden.
|

|**Hinweise**
| Hinweis eintragen. Anstatt einen Hinweis einzeln für jedes Fahrzeug in der Liste einzutragen, kann der Hinweis über den grünen Pfeil rechts für alle Fahrzeuge übernommen werden.
|====

[.instruction]
Fahrzeugverwendungsliste einem Listing zuordnen:

.  Öffnen Sie das Menü **Listings » Listings bearbeiten**.
.  Öffnen Sie ein Market-Listing, um diesem eine Fahrzeugverwendungsliste zuzuordnen.
.  Öffnen Sie das Tab **Marktplatz** des gewählten Listings.
.  Klicken Sie unter **Fahrzeugverwendungsliste** auf **Hinzufügen**. +
→ Das Fenster **Fahrzeugverwendungsliste wählen** wird geöffnet.
.  Tragen Sie den Namen einer Liste oder einen Teil des Namens ein und wählen Sie eine Liste.
.  Klicken Sie auf **Auswählen**, um die Liste dem Market-Listing zuzuordnen.

[#1650]
===  Fahrzeugverwendungsliste suchen

Suchen Sie nach angelegten Fahrzeugverwendungslisten mithilfe der Filtereinstellungen im Menü **Einstellungen » Märkte » eBay » Fahrzeugverwendungsliste**. Dabei stehen Ihnen die Filtermöglichkeiten **ID**, **Name**, **Kategorie** und **eBay-Plattform** zur Verfügung.

