= Entwurf_Lena_1
:lang: de
include::{includedir}/_header.adoc[]
:position: 20

**link:http://de.dawanda.com[DaWanda^]** ist ein Online-Marktplatz für Unikate, handgemachte, individualisierte und maßgeschneiderte Produkte und Kleinserien. Massenprodukte oder Importware dürfen auf DaWanda nicht verkauft werden. In den Spezialkategorien Material und Vintage können auch industriell hergestellte Produkte angeboten werden. Diese Produkte müssen den **link:http://de.dawanda.com/cms/c/de/Verkauferportal/42-Richtlinien/p430-DaWanda-Richtlinien#allowed_products[Produktrichtlinien^]** von DaWanda entsprechen.

[#10]
== Bei DaWanda registrieren

Bevor du DaWanda in plentymarkets einrichtest, musst du dich auf **link:https://de.dawanda.com/account/register[DaWanda^]** registrieren und dein Sortiment zur Produktprüfung verlinken. Wenn du bereits bei DaWanda verkaufst, beantrage deinen **link:https://docs.google.com/forms/d/1NdTmxnQ1zgUDZQM-rPh5wVSqmMghGKsqCu4nygv3z8Q/viewform?c=0&w=1[API-Schlüssel^]** unter Angabe deines DaWanda-Shops.

[#20]
== DaWanda in plentymarkets einrichten

Um Artikel auf DaWanda anzubieten, richte DaWanda in plentymarkets ein. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
DaWanda in plentymarkets einrichten:

. Öffne das Menü **System » Märkte » DaWanda » Einstellungen**.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in Tabelle 1.
. **Speichere** die Einstellungen.

[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Automatischen Datenaustausch aktivieren**
|Ist der Datenaustausch aktiviert, findet ein täglicher Artikelexport, ein stündlicher Bestandsabgleich und ein stündlicher Auftragsimport statt.

|**API-Schlüssel**
|API- Schlüssel eintragen, wie von DaWanda erhalten.  +
Nach dem Speichern wird der API-Schlüssel geprüft. Nach erfolgreicher Prüfung werden die Felder für die Optionen **Shop-ID** und **Shop-Name** automatisch ausgefüllt.

|**Shop-ID**
|ID des DaWanda-Shops; wird nach erfolgreicher Prüfung des API-Schlüssels automatisch ausgefüllt.

|**Shop-Name**
|Name des DaWanda-Shops; wird nach erfolgreicher Prüfung des API-Schlüssels automatisch ausgefüllt.

|**Artikelname**
|**Name 1**, **Name 2** oder **Name 3** wählen. Dieser Artikelname wird an DaWanda übertragen.

|**Artikelkurzbeschreibung**
|**Vorschautext**, **Name 1**, **Name 2** oder **Name 3** wählen. Diese Artikelkurzbeschreibung wird an DaWanda übertragen.

|**Artikelbeschreibung**
|**Artikeltext** aus dem Tab **Texte** des Artikels wählen oder eine der Beschreibungen aus dem Tab **Felder** des Artikels wählen. Diese Artikelbeschreibung wird an DaWanda übertragen.
|====

__Tab. 1: Grundeinstellungen des Marktplatzes DaWanda__

[IMPORTANT]
.Varianten werden als einzelne Artikel an DaWanda übertragen
====
Bei DaWanda können keine Varianten eingestellt werden. Für jede Variante wird daher bei DaWanda ein einzelner Artikel erstellt. Farbe und Größe werden dabei automatisch an den Titel angehängt. +
Tipp: Artikelnamen dürfen bei DaWanda höchstens 50 Zeichen lang sein. Längere Artikelnamen werden abgeschnitten. Wenn deine Artikelnamen mit Angabe von Farbe und Größe zu lang werden, nutze **Name 1**, **Name 2** oder **Name 3** im Tab **Texte** des Artikels und übertrage diese Artikelnamen an DaWanda.
====

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* täglicher Artikelexport
* stündlicher Bestandsabgleich
* stündlicher Auftragsimport

[TIP]
.Artikelbild
====
Zu DaWanda können maximal 4 Artikelbilder hochgeladen werden.
====

[#30]
== Artikelverfügbarkeit einstellen

Artikel, die du auf DaWanda verkaufen möchtest, müssen im Menü link::/[**Artikel » Artikel bearbeiten**] im Tab **link::/[Verfügbar]** aktiviert werden.

[.instruction]
Artikelverfügbarkeit für DaWanda einstellen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Wechsle in das Tab **Verfügbar**.
. Wähle aus dem Dropdown-Menü **Webshop-Sichtbarkeit** die Option **Sichtbar**.
. Aktiviere die Option **Web-API**.
. Aktiviere die Option **DaWanda**.
. **Speichere** die Einstellungen. +
→ Der Artikel ist auf DaWanda verfügbar.

[#40]
== Kategorien verknüpfen

Verknüpfe deine Webshop-Kategorien mit den Kategorien von DaWanda, damit deine Artikel in diesen DaWanda-Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[#50]
== Merkmale anlegen

Nutze link::/[**Merkmale**], um Eigenschaften, die du für die Einrichtung des Marktplatzes DaWanda benötigst, mit deinen Artikeln zu verknüpfen. Du verknüpfst damit bei Bedarf Kategorien direkt am Artikel. Über Merkmalfilter übermittelst du außerdem Artikelinformationen an DaWanda und legst Filter für die Artikelsuche auf DaWanda fest.

Lege die Merkmale zunächst an und verknüpfe diese dann mit den Artikeln. Gehe dazu wie im Folgenden beschrieben vor.

[#100]
== Aufträge automatisch in den Status "Abgeschlossen" setzen

Richte eine **<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>** ein, um Aufträge automatisch in den DaWanda-Status "Abgeschlossen" zu setzen. Da dieser Status bei DaWanda nicht genau definiert ist, bestimmst du selbst, wann du Aufträge in den Status "Abgeschlossen" setzt. Sowohl du als auch deine Kunden können Aufträge in diesen Status setzen. Du kannst den Auftrag z.B. zu dem Zeitpunkt in den Status "Abgeschlossen" setzen, zu dem du die Versandbestätigung an DaWanda sendest.
