= Dokumente
:lang: de
include::{includedir}/_header.adoc[]
:position: 50

Im Menü **Dokumente** eines Standorts unter **plentymarkets » Einstellungen » Mandant (Shop) » Shop wählen » Standorte** konfigurieren und verwalten Sie alle Einstellungen für auftragsbezogene Dokumente, z.B. **Rechnungen**, **Lieferscheine** und **Auftragsbestätigungen**.

toc::[]
== Standortbezogene Verwaltung

Die Dokumente werden pro Standort angelegt und befinden sich jeweils im Unterordner **Dokumente** eines Standorts. Sie erfahren in den Erläuterungen auf der Handbuchseite <<auftraege/einstellungen/dokumente#, **Dokumente**  >>, wie Sie die Standardeinstellungen der Dokumente anpassen oder die Einstellungen eines Dokuments auf eine andere Vorlage übertragen. Des Weiteren wird erläutert, wie Sie Geschäftspapier als PDF-Vorlagen erstellen und mit den Dokumenten verknüpfen. Auch das Anlegen und Verwalten von Nummernkreisen wird erklärt. Schließlich folgen Informationen mit steuerrechtlicher Relevanz für Dokumente.

== Benutzerrechte

Den Zugriff auf die Dokumente regeln Sie unter <<arbeiten-mit-plentymarkets/benutzer-verwalten#, **Einstellungen » Grundeinstellungen » Benutzer**  >> pro Benutzer im Tab **Berechtigungen**, Tab <<arbeiten-mit-plentymarkets/benutzer-verwalten#90., **Menü** >>.

== Weitere Dokumente

Die nicht standortbezogenen Dokumente, z.B. Adressetiketten und Picklisten, richten Sie unter <<auftraege/einstellungen/dokumente#, **Einstellungen » Aufträge » Dokumente**  >> ein.

