= Webshop
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop-Einstellungen
:position: 20

**plentymarkets » Einstellungen » Mandant (Shop) » Standard » Webshop**

== Inhalt dieses Kapitels

In diesem Kapitel erhalten Sie wichtige Informationen zu verschiedenen Menüs Ihres Webshops. Neben **<<mandant-shop/standard/webshop/grundeinstellungen#, Grundeinstellungen  >>** zum Webshop erfahren Sie in diesem Kapitel, wie Sie Einstellungen unter **<<mandant-shop/standard/webshop/multilingualismus#, Multilingualismus  >>** vornehmen, um Ihren Webshop mehrsprachig aufzubauen und wie Sie im Menü **<<payment/waehrungen#, Währung  >>** die entsprechenden Währungen verwalten. Darüber hinaus können Sie in diesem Menü Ihren **<<mandant-shop/standard/webshop/webshop-sperren#, Webshop sperren  >>** oder mobile **<<mandant-shop/standard/webshop/weiterleitung#, Weiterleitungen  >>** hinterlegen. Auch **<<mandant-shop/standard/webshop/rechtliche-angaben#, rechtliche Angaben  >>** wie zu den AGB oder zum Widerrufsrecht hinterlegen Sie in diesem Bereich Ihres plentymarkets-Systems.

== Verbindungen zu anderen Menüs

Mit den Einstellungen im Menü **Währung** hinterlegen Sie z.B. die Grundlagen für Ihre **<<payment/zahlungen-verwalten#70., Zahlungseingänge >>** innerhalb der **<<auftraege#, Aufträge  >>**. Sie haben hier die Möglichkeit, einer Sprache jeweils eine Währung zur **<<payment/zahlungen-verwalten#, Zahlung  >>** zuzuordnen, um so einen **<<mandant-shop/best-practice/mehrsprachiger-webshop#, mehrsprachigen Webshop  >>** optimal einsetzen zu können.

== Videotutorials

Erfahren Sie mehr über das Einpflegen eines **Impressums** bzw. von **AGB** im folgenden Videotutorial:

[.linkBox]
link:https://www.plentymarkets.eu/a-3144/[Impressum &amp; AGB einpflegen, window="_blank"]

== Wichtige Seiten zum Thema direkt aufrufen

* <<mandant-shop/standard/webshop/grundeinstellungen#, **Grundeinstellungen**  >>
* <<mandant-shop/standard/webshop/multilingualismus#, **Multilingualismus**  >>
* <<payment/waehrungen#, **Währung**  >>
* **<<mandant-shop/standard/webshop/webshop-sperren#, Webshop sperren  >>**
* <<mandant-shop/standard/webshop/weiterleitung#, **Weiterleitung**  >>
* <<mandant-shop/standard/webshop/rechtliche-angaben#, **Rechtliche Angaben**  >>
* <<mandant-shop/standard/webshop/content-seiten#, **Seiten**  >>

