= What to do when you exceed a delivery threshold?
:lang: en
include::{includedir}/_header.adoc[]
:position: 50
:url: orders/faq/exceeding-delivery-threshold
:id: 2SGCUHA
:keywords: exceeding delivery threshold, pass delivery threshold, delivery threshold, taxes, tax configuration, VAT rate, location, EU country, VAT configuration, VAT number, tax identification number
:author: team-order-payment

You exceeded the delivery threshold in a country and have to correct orders and invoices now? If so, follow the steps listed below. Proceed with care because editing a VAT configuration is no longer possible once it is actively used. Therefore, be sure and check that you entered the correct data.

* *Step 1*: Cancelling invoices +
Create an <<automation/event-procedures#100, event procedure>> so that a cancellation document is generated for orders you move into a separate status. Filter all required orders and move them into this <<orders/managing-orders#1230, separate status>>. By doing this, the invoices are cancelled and the orders are unlocked.

* *Step 2*: Create a new VAT configuration +
Set up a new VAT configuration for the required country in the location from which you have exceeded the delivery threshold. +
_Example_: You are delivering from the location Germany to France and exceed the delivery threshold in France. In this case you go to the location Germany and set up a new VAT configuration for France with the corresponding VAT rates. Remember to enter the correct VAT number, in this case the VAT number for France.

[.instruction]
Creating a new VAT configuration:

. Go to *System » Client » [Select client] » Locations » [Select location] » Accounting*.
. Change to the VAT rates tab.
. Click on *New configuration*.
. Select a *country*.
. Enter the highest VAT rate as *VAT rate A*. Enter further VAT rates in descending order.
. Enter your *VAT number* for the required country.
. Select a start date from which on the VAT rates will be valid. In this case, select the day on which you exceeded the delivery threshold.
. *Save* (icon:save[role="green"]) the settings.

If the delivery threshold was also exceeded in other clients or locations, you have to set up a VAT configuration for those as well. If this is the case, repeat the instructions in step 2.

* *Step 3*: Recalculation of order +
Recalculate the orders which you have moved to a new status. This way, the new VAT rates are applied. +
Usually, orders are recalculated when a new invoice is generated. But by doing this, orders are also locked. Alternatively, you can go to the *Settings* tab in an order and save the order there. This way, the order is updated without being locked. If you have to recalculate a lot of orders, contact the plenty Support, they can take over.

* *Step 4*: Generating new invoices +
Proceed similarly to step 1. Create a new event procedure, so that the status change triggers the generation of a new invoice for each order. Move the orders into a further separate status. The invoices generated by this are updated because of the setup of the new VAT configuration and the recalculation of the orders.

Because of the new VAT configuration as described in step 2, all orders which are created or imported are calculated with the new VAT rates from the date set in the configuration. If you have further questions, you can contact our supporters in the link:https://forum.plentymarkets.com/[forum].
