= Entwurf_sina3
:lang: de
include::{includedir}/_header.adoc[]
:position: 12

== Netto- oder Brutto-Rechnung ausstellen / Rechnungsstellung beeinflussen

Die Einstellungen zur Rechnungsstellung sind standortabhängig. Ihr plentymarkets System verhält sich bei der Rechnungsstellung für Standorte in Ländern, die nicht in der Europäischen Union liegen, anders als bei Standorten in Ländern, die Mitgliedsstaaten der EU sind.

Folgende Unterscheidung gilt für Nicht-EU-Länder:

*  Bei Versand innerhalb des Landes wird eine Brutto-Rechnung ausgestellt.
*  Für den Versand in andere Länder kann eingestellt werden, ob die Rechnung brutto oder netto ausgestellt wird.

Folgende Unterscheidung gilt für EU-Länder:

*  Bei Versand innerhalb des Landes und an Privatpersonen in anderen EU-Länderen wird eine Brutto-Rechnung ausgestellt.
*  Für den Versand in Länder außerhalb der EU kann eingestellt werden, ob die Rechnung brutto oder netto ausgestellt wird.
*  Für den Versand an Warenempfänger mit einer Ust.-ID in anderen EU-Mitgliedsstaaten kann eingestellt werden, ob die Rechnung brutto oder netto ausgestellt wird.

[.instruction]
Rechnungsstellung festlegen:

.  Öffnen Sie das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung » Tab: Grundeinstellungen**.
.  Nehmen Sie die Einstellungen gemäß Tabelle 1 vor.
.  *Speichern* Sie die Einstellungen.

[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Umsatzsteuer-ID**
|Gilt nur für Lieferungen innerhalb der EU.  +
**Netto-Rechnung** = Rechnungen bei Kunden, bei denen eine Umsatzsteuer-ID eingetragen ist, werden netto, d.h. ohne Umsatzsteuer, ausgestellt.  +
Wenn ein Händler Artikel an einen Kunden mit gültiger Umsatzsteuer-ID im europäischen Ausland versendet, entfällt die Umsatzsteuer; der Auftrag wird also netto ausgeführt. Liegt die Lieferadresse dieses Kunden jedoch innerhalb Deutschlands, wird für den Auftrag Umsatzsteuer berechnet. Per Gesetz ist es jedoch zulässig, bei Kunden mit gültiger Umsatzsteuer-ID im europäischen Ausland auch bei einer deutschen Lieferadresse den Auftrag netto auszuführen, wenn dem Auftrag eine <<omni-channel/online-shop/mandanten-einrichten/dokumente/gelangensbestaetigung#, **Gelangensbestätigung**>> beigelegt wird. Daher gibt es im Menü **<<crm/kundendaten-verwalten#1900, Lieferanschriften>>** die Option **Gelangensbestätigung**. Wird die Option **Gelangensbestätigung** aktiviert (Häkchen gesetzt), werden Lieferungen ins EU-Ausland mit deutscher Lieferanschrift wie eine EU-Auslandssendung behandelt. Ob die Rechnung brutto oder netto ausgestellt wird, ist dann von den Einstellungen **Umsatzsteuer-ID** und **Ausfuhrlieferung** in diesem Menü abhängig. Ist die Option **Gelangensbestätigung** nicht aktiviert, werden diese Aufträge brutto berechnet. +
**Brutto-Rechnung** = Alle Rechnungen werden brutto ausgestellt.

|**Ausfuhrlieferung**
|**Netto-Rechnung** = Rechnungen für Ausfuhrlieferungen werden ohne Umsatzsteuer ausgestellt. +
**Brutto-Rechnung** = Die Umsatzsteuer wird auf Rechnungen für Ausfuhrlieferungen ausgewiesen. +
Wenn ein Umsatzsteuersatz für ein Ausfuhr-Lieferland eingestellt wurde, erfolgt immer eine Brutto-Rechnung.

|**Umsatzsteuer der Versandkosten auf Rechnung ausweisen**
|Wählen, wann die Umsatzsteuer der Versandkosten einzeln ausgewiesen werden soll. +
**Immer** = Die Umsatzsteuer der Versandkosten wird immer ausgewiesen. +
**Nur Inland und EU** = Die Umsatzsteuer wird bei einer Ausfuhrlieferung aus der EU nicht ausgewiesen.

|**Kleinunternehmer (nur Deutschland)**
|Häkchen setzen, wenn auf der Rechnung und im Webshop-Bestellvorgang keine Umsatzsteuer ausgewiesen werden soll. +
Diese Einstellung betrifft Kleinunternehmer nach § 19 UstG, d.h. Unternehmer, die aufgrund geringer Einnahmen von der Umsatzsteuerpflicht befreit sind. Die Option ist freiwillig. Die Umsatzsteuer kann auch bei geringem Umsatz ausgewiesen werden, wenn dies Vorteile hat. Dazu die einschlägigen Hinweise beachten, z.B. unter folgendem link:http://www.banktip.de/rubrik2/20085/6/die-regelung-des-19-ustg.html[**Link**].
|====

__Tab. 1: Tab **Grundeinstellungen**__

.Gerundete Gesamtbeträge
[cols="1,3,3,3,3,3,3,3,3,3"]
|====
| |Anzahl Bahnen |Variante |Einzelpreis netto |Einzelpreis brutto |Mwst. |Gesamtpreis brutto |Gesamtpreis netto |Mehrwertsteuer gesamt |Errechnete Gesamtbeträge

|
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,187  +
2,1870  +
2,18
|2,6025  +
2,6025  +
2,60
|0,4155  +
0,4155  +
0,42
|18,2175  +
18,22  +
18,20
|15,309  +
15,31  +
15,26
|2,9085  +
2,91  +
2,94
|

|
|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|3,645 +
3,645  +
3,65
|4,3376  +
4,3376  +
4,34
|0,6926  +
0,6926  +
0,69
|34,700  +
34,70  +
34,72
|29,16  +
29,16  +
29,20
|5,5404 +
5,54  +
5,52
|

|Gesamtbeträge
8+|
|Summen der Gesamtbeträge

|Netto-Warenwert
|
|
|
|
|
|
|
|
|**44,47** +
44,47  +
44,46

|19 % Mehrwertsteuer
|
|
|
|
|
|
|
|
|**8,45** +
8,45  +
8,46

|Rechnungsbetrag
|
|
|
|
|
|
|
|
|52,92 +
52,92  +
52,92
|====

-------------------------------------------------------------- .Gerundete Gesamtbeträge
[cols="1,3,3,3,3,3,3,3,3,3"]
|====
| |Anzahl Bahnen |Variante |Einzelpreis netto |Einzelpreis brutto |Mwst. |Gesamtpreis brutto |Gesamtpreis netto |Mehrwertsteuer gesamt |

|
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,187  +
2,1870  +
2,18
|2,6025  +
2,6025  +
2,60
|0,4155  +
0,4155  +
0,42
|18,2175  +
18,22  +
18,20
|15,309  +
15,31  +
15,26
|2,9085  +
2,91  +
2,94
|

|
|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|3,645 +
3,645  +
3,65
|4,3376  +
4,3376  +
4,34
|0,6926  +
0,6926  +
0,69
|34,700  +
34,70  +
34,72
|29,16  +
29,16  +
29,20
|5,5404 +
5,54  +
5,52
|

|Gesamtbeträge
8+|
|Summen der Gesamtbeträge

|Netto-Warenwert
|
|
|
|
|
|
|
|
|**44,47** +
44,47  +
44,46

|19 % Mehrwertsteuer
|
|
|
|
|
|
|
|
|**8,45** +
8,45  +
8,46

|Rechnungsbetrag
|
|
|
|
|
|
|
|
|52,92 +
52,92  +
52,92
|====

------------------------------------------------------------------ .Gerundete Gesamtbeträge
[cols="1,3,3,3,3,3,3,3,3,3,3"]
|====
| |Anzahl Bahnen |Variante |Berechnungsvariante |Einzelpreis netto |Einzelpreis brutto |Mwst. |Gesamtpreis brutto |Gesamtpreis netto |Mehrwertsteuer gesamt |Gesamtbeträge

.3+|
.3+|7
.3+|Sommerwiese, Baumwolle, Grasgrün
| Gerundete Gesamtbeträge
|2,1870
|2,6025
|0,4155
|18,2175
|15,309
|2,9085
| Netto-Warenwert **44,47** +
Mehrwertsteuer **8,45** +
Rechnungsbetrag **52,92**

| Gerundete Auftragspositionen
| 2,1870
|2,6025
| 0,4155
| 18,22
| 15,31
| 2,91
| Netto-Warenwert 44,47  +
Mehrwertsteuer 8,45  +
Rechnungsbetrag 52,92

| Gerundete Einzelbeträge
| 2,18
| 2,60
| 0,42
| 18,20
| 15,26
| 2,94
| Netto-Warenwert 44,46  +
Mehrwertsteuer 8,46  +
Rechnungsbetrag 52,92

.3+|
.3+|8
.3+|Sommerwiese, Baumwolle, Sonnenuntergangsrot
| Gerundete Gesamtbeträge
|3,645
|4,3376
|0,6926
|34,700
|29,16
|5,5404

| Gerundete Auftragspositionen
| 3,645
| 4,3376
| 0,6926
| 34,70
|29,16
| 5,54

| Gerundete Einzelbeträge
| 3,65
| 4,34
| 0,69
| 34,72
| 29,20
| 5,52

|Gesamtbeträge
8+|
|Summen der Gesamtbeträge

|Netto-Warenwert
|
|
|
|
|
|
|
|
|**44,47** +
44,47  +
44,46

|19 % Mehrwertsteuer
|
|
|
|
|
|
|
|
|**8,45** +
8,45  +
8,46

|Rechnungsbetrag
|
|
|
|
|
|
|
|
|52,92 +
52,92  +
52,92
|====

----------------------------------------------------- .Berechnungsvarianten im Vergleich
[cols="1,3,3,3,3,3,3,3,3,3,3,3"]
|====
|Berechnungsvariante |Anzahl Bahnen |Variante |Einzelpreis brutto |Einzelpreis netto |Mwst. Einzelposition |Gesamtpreis brutto |Gesamtpreis netto |Mehrwertsteuer Auftragsposition |Nettowarenwert |Mehrwertsteuer gesamt |Rechnungsbetrag

.2+|Gerundete Gesamtbeträge
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,6025
|2,187
|0,4155
|18,2175
|15,309
|2,9085
.2+|gerundet 44,47
.2+|gerundet 8,45
.2+|52,92

|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|4,3376
|3,645
|0,6926
|34,700
|29,16
|5,5404

.2+|Gerundete Auftragspositionen
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,6025
|2,187
|0,4155
|gerundet 18,22
|gerundet 15,31
|2,91
.2+|44,47
.2+|8,45
.2+|52,92

|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|4,3376
|3,645
|0,6926
|gerundet 34,70
|gerundet 29,16
|5,54

.2+|Gerundete Einzelbeträge
|7
|Sommerwiese, Baumwolle, Grasgrün
|gerundet 2,60
|gerundet 2,18
|0,42
|18,20
|15,26
|2,94
.2+|44,46
.2+|8,46
.2+|52,92

|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|gerundet 4,34
|gerundet 3,65
|0,69
|34,72
|29,20
|5,52
|====

Erfahren Sie welche Einstellungen, die die Buchhaltung beeinflussen, es in plentymarkets gibt und in welchem Menü diese sich befinden. Hierzu zählen in plentymarkets Umsatzsteuersätze, Währungen, Umrechnungskurse und Preise, aber auch Dokumente. Die genaue Einrichtung von Dokumenten wird jedoch an anderer Stelle ausführlich beschrieben.

== Speichern und Runden von Auftragspreisen

Es gibt 2 Einstellungen in plentymarkets, die es Ihnen erlauben das Speichern und Runden von Auftragspreisen zu beeinflussen. Mithilfe der Einstellungen lassen sich folgende Ergebnisse erreichen:

*  Gerundete Einzelpreise
*  Gerundete Auftragspositionssummen
*  Gerundete Gesamtbeträge

=== Speichern und Runden einstellen

Das Menü, in dem die 2 Einstellungen, sich befinden sowie eine Erläuterung der Einstellungen.

[.instruction]
Speichern und Runden einstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung**.  +
Das Tab **Grundeinstellungen** wird geöffnet.
. Nehmen Sie die Einstellung vor. Beachten Sie die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen.

.Speicher- und Rundungseinstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Anzahl Nachkommstellen bei Preisen**
|2 oder 4 Nachkommastellen wählen  +
**2** = Preise im Auftrag werden mit nur 2 Nachkommastellen gespeichert. Dadurch wird indirekt auch erreicht, dass der Einzelpreis gerundet wird. Die weitere Berechnung der Summen und des Rechnungsbetrages erfolgt dann basierend auf den gerundeten Einzelpreisen.  +
**4** = Preise werden im Auftrag mit 4 Nachkommastellen gespeichert. Wenn 4 Nachkommstellen gewählt werden, werden standardmäßig die Summen von Auftragsposition gerundet. Im Hintergrund werden die Summen jedoch ungerundet mit 4 Nachkommastellen gespeichert, so dass es möglich bleibt, später auch nur die Gesamtbeträge zu runden. Durch ein Häkchen bei **Nur Gesamtpreise runden** wird das standardmäßige Rundungsverhalten bei 4 Nachkommastellen aufgehoben und erst zu einem späteren Zeitpunkt gerundet.

|**Nur Gesamtpreise runden**
|Häkchen setzen, um das standardmäßge Runden bei 4 Nachkommastellen außer Kraft zu setzen und stattdessen erst die Gesamtbeträge zu runden. Gesamtbeträge bezieht sich auf den Warenwert eines Auftrages. Bezogen auf die Dokumenteinstellungen einer Rechnung sind das die Werte, die unter der Überschrift Summen aufgeführt werden.  +
Bei 4 Nachkommastellen werden ohne das Häkchen die Summen der Auftragspositionen gerundet.  +
Bei 2 Nachkommastellen hat das Häkchen keine Auswirkungen, da bereits der Einzelpreis gerundet wird.
|====

////
<strong class="subhead">Grundlagen der Berechnung in plentymarkets</strong>

<p>Die Preisberechnung in Aufträgen beruht auf dem Bruttopreis der Varianten. Ausgehend von diesem Bruttopreis wird der Nettopreis der Varianten für den Auftrag errechnet. Es wird nicht pauschal der Nettopreis verwendet, der in den Artikeldaten gespeichert ist. Die Auftragspositionsummen errechnen sich durch Multiplikation der Einzelpreise mit der gekauften Anzahl. Die Bruttosumme einer Auftragsposition errechnet sich also aus dem Bruttoeinzelpreis mal der Anzahl. Die Nettosumme einer Auftragsposition errechnet sich aus dem errechneten und auf 4 Nachkommastellen gerundeten Nettoeinzelpreis multipliziert mit der gekauften Anzahl. Der Umsatzsteuerbetrag für eine Auftragsposition ist die Differenz aus Bruttosumme minus Nettosumme.</p>

////
=== Beispielberechnungen

Im folgenden wird eine Rechnung mit genauen, also ungerundeten, Beträgen dargestellt. Diese Rechnung dient als Grundlage für die Erläuterung der Kombination der Einstellungen und ihrer Auswirkungen auf die Rechnungsbeträge.
Verkauft wurden Stoffe. Es wurde mehrere Bahnen des gleichen Stoffs in einer Breite von 50 Zentimeter und in 30 Zentimeter gekauft. Die 50-Zentimeterbahn wurde 8 mal gekauft und die 30-Zentimeterbahn 7 mal. 30 Zentimeter kosten 2,187 € und 50 Zentimeter kosten 3,645 €. Die Preise basieren auf einem Meterpreis von 7,29 €. +
Mit genauen Werten gerechnet ergibt sich also folgende Aufstellung:

.Genaue Werte
[cols="1,3,3,3,3,3,3,3"]
|====
| |Anzahl Bahnen |Variante |Einzelpreis netto |Mwst. |Gesamtpreis netto |Mehrwertsteuer gesamt |

|
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,187
|0,41553
|15,309
|2,90871
|

|
|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|3,645
|0,69255
|29,16
|5,5404
|

|Netto-Warenwert
|
|
|
|
|
|
|44,469

|19 % Mehrwertsteuer
|
|
|
|
|
|
|8,44911

|Rechnungsbetrag
|
|
|
|
|
|
|52,91811

|Rechnungsbetrag gerundet
|
|
|
|
|
|
|52,92
|====

Welche Kombination von Einstellungen, welches Ergebnis bringt, folgt jetzt detailliert.

==== Beispiel gerundete Gesamtbeträge

Um gerundete Gesamtbeträge zu erhalten, müssen 4 Nachkommastellen gewählt werden und die Einstellung dass erst die Gesamtpreise gerundet werden. Hierbei handelt es sich um die Standardeinstellungen.

.Gerundete Gesamtbeträge
[cols="1,3,3,3,3,3,3,3,3,3"]
|====
|Gesamtbeträge |Anzahl Bahnen |Variante |Einzelpreis netto |Einzelpreis brutto |Mwst. |Gesamtpreis brutto |Gesamtpreis netto |Mehrwertsteuer gesamt |Errechnete Gesamtbeträge

|
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,187
|2,6025
|0,4155
|18,2175
|15,309
|2,9085
|

|
|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|3,645
|4,3376
|0,6926
|34,700
|29,16
|5,5404
|

|Netto-Warenwert
|
|
|
|
|
|
|
|
|44,469 +
gerundet **44,47**

|19 % Mehrwertsteuer
|
|
|
|
|
|
|
|
|8,4493  +
gerundet **8,45**

|Rechnungsbetrag
|
|
|
|
|
|
|
|
|52,92 +
addiert sich aus dem gerundeten Netto-Warenwert und der gerundeten Mehrwertsteuersumme
|====

==== Beispiel für gerundete Auftragspositionssummen

Um Auftragspositionssummen zu runden, müssen 4 Nachkommastellen gewählt werden.

.Gerundete Auftragspositionen
[cols="1,3,3,3,3,3,3,3,3,3"]
|====
|Gesamtbeträge |Anzahl Bahnen |Variante |Einzelpreis netto |Einzelpreis brutto |Mwst. |Gesamtpreis brutto |Gesamtpreis netto |Mehrwertsteuer gesamt |Errechnete Gesamtbeträge

|
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,1870
|2,6025
|0,4155
|18,2175  +
gerundet **18,22**
|15,309 +
gerundet **15,31**
|2,91 +
Differenz zwischen Bruttowarenwert und Nettowarenwert
|

|
|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|3,645
|4,3376
|0,6926
|34,7008  +
gerundet **34,70**
|29,1600  +
gerundet **29,16**
|5,54  +
Differenz zwischen Bruttowarenwert und Nettowarenwert
|

|Netto-Warenwert
|
|
|
|
|
|
|
|
|44,47 +
addiert sich aus den gerundeten Netto-Warenwerten der beiden Artikelpositionen

|19 % Mehrwertsteuer
|
|
|
|
|
|
|
|
|8,45 +
addiert sich aus den gerundeten Mehrwertsteuersummen der Artikelpositionen

|Rechnungsbetrag
|
|
|
|
|
|
|
|
|52,92
|====

==== Beispiel für gerundete Einzelpreise

Für gerundete Einzelpreise müssen 2 Nachkommstellen gewählt werden.

.Gerundete Einzelpreise
[cols="1,3,3,3,3,3,3,3,3"]
|====
|Gesamtbeträge |Anzahl Bahnen |Variante |Einzelpreis netto |Einzelpreis brutto |Mwst. |Gesamtpreis netto |Mehrwertsteuer gesamt |Errechnete Gesamtbeträge

|
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,18
|2,60
|0,42
|15,26
|2,94  +
Differenz zwischen Bruttowarenwert und Nettowarenwert
|

|
|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|3,65
|4,34
|0,69
|29,20
|5,52  +
Differenz zwischen Bruttowarenwert und Nettowarenwert
|

|Netto-Warenwert
|
|
|
|
|
|
|
|44,46 +
addiert sich aus den Nettowarenwerten der beiden Artikelpositionen

|19 % Mehrwertsteuer
|
|
|
|
|
|
|
|8,46 +
addiert sich aus den Mehrwertsteuersummen der Artikelpositionen

|Rechnungsbetrag
|
|
|
|
|
|
|
|52,92
|====

.Berechnungsvarianten im Vergleich
[cols="1,3,3,3,3,3,3,3,3,3,3,3"]
|====
|Berechnungsvariante |Anzahl Bahnen |Variante |Einzelpreis brutto |Einzelpreis netto |Mwst. Einzelposition |Gesamtpreis brutto |Gesamtpreis netto |Mehrwertsteuer Auftragsposition |Nettowarenwert |Mehrwertsteuer gesamt |Rechnungsbetrag

.2+|Gerundete Gesamtbeträge
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,6025
|2,187
|0,4155
|18,2175
|15,309
|2,9085
.2+|gerundet 44,47
.2+|gerundet 8,45
.2+|52,92

|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|4,3376
|3,645
|0,6926
|34,700
|29,16
|5,5404

.2+|Gerundete Auftragspositionen
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,6025
|2,187
|0,4155
|gerundet 18,22
|gerundet 15,31
|2,91
.2+|44,47
.2+|8,45
.2+|52,92

|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|4,3376
|3,645
|0,6926
|gerundet 34,70
|gerundet 29,16
|5,54

.2+|Gerundete Einzelbeträge
|7
|Sommerwiese, Baumwolle, Grasgrün
|gerundet 2,60
|gerundet 2,18
|0,42
|18,20
|15,26
|2,94
.2+|44,46
.2+|8,46
.2+|52,92

|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|gerundet 4,34
|gerundet 3,65
|0,69
|34,72
|29,20
|5,52
|====

