= Bestellbestätigung
:lang: de
// include::{includedir}/_header.adoc[]
:keywords: Bestellbestätigung,Webdesign,CMS
:position: 40

*CMS » Webdesign » Bestellvorgang » Bestellbestätigung*

== Allgemeines

Die Bestellbestätigung bildet den Abschluss des Bestellvorgangs.

== Bestellbestätigung: Design bearbeiten

Dieser Bereich ist bereits vorkonfiguriert. Du hast jedoch vielfältige Änderungsmöglichkeiten. Die entsprechenden Einstellungen sind in dem neu gestalteten Menü jetzt einfacher möglich. Darüber hinaus bieten die neu gestalteten Menüs u.a. auch die Option, CSS-Anpassungen vorzunehmen, wobei auch hier in einigen Menüs bereits vorkonfigurierte CSS-Regeln hinterlegt sind.

Folgende Bereiche kannst du im Tab *Bestellbestätigung* individuell anpassen:

*Tracking*

Das Untermenü *Tracking* verfügt über die Felder *Head* und *Body*. Die Informationen, die du hier einträgst, bilden jeweils den Head- und Bodybereich der Bestellbestätigung und aller zahlungsartspezifischen Bestellbestätigungen (der nachfolgenden Untermenüs).

*Bestellbestätigung*

Es kann für die Bestellbestätigung die Zeit konfiguriert werden, nach der man in den Mein-Konto-Bereich weitergeleitet wird. Die Option findest du unter *Weiterleitung Mein-Konto*. Standardmäßig ist dort der Wert *Nie* eingestellt. Das heißt, man gelangt nur durch einen Klick zum Auftrag in den Mein-Konto-Bereich. Du kannst dort eine Zeit wählen: *5*, *10* oder *20 Sekunden*.

*Zahlungsarten*

Alle nachfolgend aufgeführten Zahlungsarten verfügen über die gleichen Felder. Dies sind *Text vor*, *Text nach* und *CSS*. In das Feld *Text vor* kannst du Text eintragen, der vor dem Inhalt der Zahlungsart-Schnittstelle angezeigt werden soll. Entsprechend dient das Feld *Text nach* zum Eintragen von Hinweisen, die nach dem Inhalt der Zahlungsart-Schnittstelle erscheinen sollen.

* *Bestellbestätigung*
* *PayPal Express* +
Es ist möglich, die *Weiterleitungsart* von PayPal Express bei der Bestellbestätigung auf *JavaScript* zu ändern. Damit wird ein korrektes Tracking sichergestellt. Die Einstellung findest du im Untermenü *PayPal Express* unter der Option *Weiterleitungsart*.
* *PayPal*
* *Sofortüberweisung*
* *Moneybookers*
* *Klarna*
* *ClickAndBuy*
* *Paymorrow*
* *iclear*
* *Heidelpay*
* *ExperCash*
* *EOS*
* *Santander Consumer Bank* (vorher CCBank) +
Das Untermenü *Santander Consumer Bank* beinhaltet 3 Felder, die bei den anderen Zahlungsarten nicht vorhanden sind. Dies sind die Felder *Händlernummer*, *Linkinhalt* und *Fehlertext*. Da bei der Einrichtung der Zahlungsart Santander im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* keine Schnittstelle zur Santander Consumer Bank eingerichtet wird, musst du hier deine *Händlernummer* eintragen. Bei *Linkinhalt* trägst du ein, was dann als Linktext in der Bestellbestätigung angezeigt werden soll und bei *Fehlertext* hinterlegst du eine Nachricht, die dem Kunden im Fehlerfall angezeigt werden soll bzw. wenn die Zahlungsart nicht nutzbar ist. +
Beachte dazu die Handbuchseite <<payment/zahlungsanbieter/santander-consumer-bank#, Santander Consumer Bank>>.
* *SixCardSaferpay*
* *QPAY*
* *MasterPayment*

== Template-Variablen und -Funktionen in der Bestellbestätigung

Eine Übersicht aller in diesem Bereich verwendbaren Template-Variablen und -Funktionen öffnest du, wenn du auf *Template-Variablen und -Funktionen* klickst. Kopiere die gewünschte Template-Variable bzw. -Funktion z.B. in einen Hinweistext oder in das CSS. Der Inhalt wird dann in der Bestellbestätigung angezeigt.

[TIP]
.Tipp
====
Template-Variablen wie *$ItemAmountNetDot* dienen der Darstellung von Zahlenwerten (Preisen). Der letzte Teil der Template-Variable, hier Dot, gibt das Trennzeichen vor z.B. dem Centbetrag an. Du kannst somit diese Template-Variablen nutzen, um für Sprachen die Anzeige der Preise, Versandkosten etc. anzupassen. So setzt du für das deutsche Layout die Kommaseparierung und für das englische Layout die Punktseparierung bei Geldbeträgen um. +
Wenn du Daten übertragen möchtest, verwende die *Dot*-Variablen, die als einzige Variablen für eine Datenübertragung geeignet sind.
====

=== Template-Variable Auftragsherkunft

Die Template-Variablen *$LastOrderReferrerID* und *$LastOrderReferrerName* sind seit plentymarkets Version 4.4 verfügbar. Wenn ein Kunde über einen externen Link mit dem Parameter *ReferrerID* in den Webshop gelangt, hat der Kunde als Herkunft den Wert von ReferrerID. Dieser Wert ist auch in der Template-Variable$ReferrerIDhinterlegt. Diese Herkunft wird auch für den daraufhin abzuschließenden Auftrag genutzt. Nachdem der Auftrag angelegt wurde, wird die Herkunft auf "Webshop" ($ReferrerID= 1) zurückgesetzt. Möchtest du nun in den Vorlagen der Bestellbestätigung auf die ursprüngliche Herkunft (vor der Auftragsanlage) zugreifen, liefert$ReferrerIDden falschen Wert, denn dieser wurde auf 1 zurückgesetzt. Dafür gibt es in den Vorlagen der Bestellbestätigung die Template-Variablen *$LastOrderReferrerID* und *$LastOrderReferrerName*, die als Inhalt den Wert der Herkunft zum Zeitpunkt der vorhergehenden Auftragsanlage enthalten.

=== Liste aller Template-Variablen im Bereich Bestellbestätigung

Die folgende Tabelle erläutert die Template-Variablen für die Bestellbestätigung:


.Template-Variablen in der Bestellbestätigung
[cols="1,3"]
|====
|Template-Funktion/-Variable |Erläuterung

|*{% Container_ItemViewBasketItemsList() %}* bis *{% Container_ItemViewBasketItemsList2() %}*
|Damit werden die Artikel angezeigt, die sich im Warenkorb befinden.

|*{% Container_ItemViewCrossSellingItemsList2() %}* und *{% Container_ItemViewCrossSellingItemsList3() %}*
|Im Bestellvorgang CrossSelling-Artikel der Artikel anzeigen, die sich im Warenkorb befinden. Dazu muss im Menü *CMS » Webdesign » Layout* im Template *ItemViewCrossSellingItemsList2* bzw. *ItemViewCrossSellingItemsList2* im Tab *Einstellungen* für die Funktion *ItemViewCrossSellingItemsList2_FromBasket* bzw. *ItemViewCrossSellingItemsList3_FromBasket* die Einstellung *JA* gewählt werden.

|*$Currency*
|Währung

|*$CustomerEmail*
|E-Mail-Adresse des Kunden

|*$CustomerID*
|Kunden-ID

|*$CustomerName*
|Name des Kunden

|*$GtcTrans*
|Auftrags- und Artikelparameter +
Herkömmlicher Tracking-Code von <<omni-channel/online-shop/webshop-einrichten/_cms/webdesign/webdesign-bearbeiten/bestellvorgang/bestellbestaetigung#3, Google Analytics>>

|*$GtcTransAsync*
|Auftrags- und Artikelparameter, Asynchroner Code +
Beim asynchronen Tracking-Code von <<omni-channel/online-shop/webshop-einrichten/_cms/webdesign/webdesign-bearbeiten/bestellvorgang/bestellbestaetigung#3, Google Analytics>> handelt es sich um ein verbessertes JavaScript-Code-Snippet, bei dem der Tracking-Code ga.js im Hintergrund geladen wird. Zu den Vorteilen gehört u.a. eine kürzere Ladezeit.

|*$ItemAmountGrossComma*
|Artikelwert brutto; Nachkommazahlen werden durch ein Komma getrennt.

|*$ItemAmountGrossDot*
|Artikelwert brutto; Nachkommazahlen werden durch einen Punkt getrennt.

|*$ItemAmountNetComma*
|Artikelwert netto; Nachkommazahlen werden durch ein Komma getrennt.

|*$ItemAmountNetDot*
|Artikelwert netto; Nachkommazahlen werden durch einen Punkt getrennt.

|*$ItemIDListComma*
|Auflistung der Artikel-IDs; zwischen den IDs steht ein Komma als Trennzeichen.

|*$ItemIDListPipe*
|Auflistung der Artikel-IDs; zwischen den IDs steht ein senkrechter Strich als Trennzeichen.

|*$ItemQuantity*
|Anzahl der Artikel

|*$IsNet*
|Diese Template-Variable liefert die Werte *TRUE*, wenn der Inhalt des Warenkorbes zu einer Netto-Bestellung wird (abhängig von den Einstellungen des Systems), und *FALSE*, wenn es eine Brutto-Bestellung wird.

|*$LastOrderReferrerID*
|ID der vorhergehenden bzw. ursprünglichen Herkunft

|*$LastOrderReferrerName*
|Name der vorhergehenden bzw. ursprünglichen Herkunft

|*$OrderID*
|Auftrags-ID

|*$MethodOfPayment*
|Zahlungsart

|*$MethodOfPaymentID*
|ID der Zahlungsart

|*$ReferrerID*
|Herkunfts-ID

|*$ReferrerName*
|Herkunftsname

|*$ShippingCostsGrossComma*
|Versandkosten brutto; Nachkommazahlen werden durch ein Komma getrennt.

|*$ShippingCostsGrossDot*
|Versandkosten brutto; Nachkommazahlen werden durch einen Punkt getrennt.

|*$ShippingCostsNetComma*
|Versandkosten netto; Nachkommazahlen werden durch ein Komma getrennt.

|*$ShippingCostsNetDot*
|Versandkosten netto; Nachkommazahlen werden durch einen Punkt getrennt.

|*$ShippingCountry*
|Lieferland

|*$ShippingCountryID*
|ID des Lieferlandes

|*$ShippingProfile*
|Versandprofil

|*$ShippingProfileID*
|ID des Versandprofils

|*$ShippingProvider*
|Versanddienstleister

|*$ShippingProviderID*
|ID des Versanddienstleisters

|*$TotalAmountGrossComma*
|Gesamtsumme brutto; Nachkommazahlen werden durch ein Komma getrennt.

|*$TotalAmountGrossDot*
|Gesamtsumme brutto; Nachkommazahlen werden durch einen Punkt getrennt.

|*$TotalAmountNetComma*
|Gesamtsumme netto; Nachkommazahlen werden durch ein Komma getrennt.

|*$TotalAmountNetDot*
|Gesamtsumme netto; Nachkommazahlen werden durch einen Punkt getrennt.
|====
