= Weiterleitung
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, Weiterleitung
:position: 50

Im Menü **plentymarkets » Einstellungen » Mandant (Shop) » Standard » Webshop » Weiterleitung** konfigurieren Sie Einstellungen zur Weiterleitung Ihres Webshops auf mobile Endgeräte. Weiterhin legen Sie fest, was passieren soll, wenn die URL einer Kategorieseite oder eines Artikels nicht mehr aktuell ist und eine 404-Fehlermeldung ausgegeben wird. Beachten Sie auch unseren Blog-Eintrag zum Thema link:https://www.plentymarkets.eu/blog/Neue-Sitemap-vermeiden-Sie-404-Fehler-in-Ihrem-Online-Shop/b-1277/[**404-Fehler vermeiden**].

== Weiterleitung auf mobile Endgeräte einrichten

Für eine mobile Variante Ihres Online-Shops hinterlegen Sie im Menü **Einstellungen » Mandant (Shop) » Standard » Webshop » Weiterleitung** zwei Ziel-URLs. Mit der Option **Ziel-URL (Kategorie)** steuern Sie den Zugriff auf die Kategorien. Mit der Option **Ziel-URL (Artikelseite)** richten Sie eine Weiterleitung auf einen bestimmten Artikel ein. Die eingerichtete Weiterleitung wird anhand des HTTP-Requests eines mobilen Browsers beim Aufruf des Webshops über ein mobiles Endgerät veranlasst. Gehen Sie wie unten beschrieben vor, um eine Weiterleitung auf mobile Endgeräte einzurichten.

[.instruction]
Weiterleitung auf mobile Endgeräte einrichten:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Webshop » Weiterleitung**.
. Nehmen Sie die Einstellungen gemäß Tabelle 1 vor.
. **Speichern** Sie die Einstellungen.

[cols="a,a"]
|====
|Einstellungen |Erläuterung

|**Weiterleitung**
|Ermöglicht die optimierte Anzeige des Webshops auf mobilen Endgeräten, z. B. über **<<omni-channel/multi-channel/shopgate#, Shopgate  >>** oder ähnliche Anbieter. **Aktiv** wählen, um die Weiterleitungen auf die eingefügten URLs zu aktivieren.

|**Ziel-URL (Kategorie)**
|URL der mobilen Variante des Webshops eintragen, z.B. **http://mobile.ihrplentyshop.de**. Auf diese URL werden Kunden weitergeleitet, die mit einem mobilen Endgerät auf den Webshop zugreifen. +
**Tipp**: Mit der Template-Variable **$ReferrerID** in der URL kann nachvollzogen werden, woher Kunden weitergeleitet wurden. Die URL sieht dann z.B. so aus: **http://mobile.testshop.de/?referrerId=$referrerId**

|**Ziel-URL (Artikelseite)**
|URL eintragen, auf die Kunden weitergeleitet werden, die ein mobiles Endgerät nutzen, um z.B. von einem Artikel in einem Preisportal direkt zum Artikel im Webshop zu gelangen. Eine solche Artikel-URL kann wie folgt aussehen: **http://mobile.ihrplentyshop.de/?itemNumber=$itemId**. Mit der Template-Variablen **$ItemID** in der URL ist jeder Artikel erreichbar. +
**Tipp**: Mit der Template-Variablen **$ReferrerID** in der URL kann nachvollzogen werden, woher Kunden weitergeleitet wurden. Die URL könnte wie folgt aussehen: **http://mobile.ihrplentyshop.de/?itemNumber=$itemId&amp;referrerId=$referrerId** +
**Hinweis**: Wenn hier keine URL eingetragen wird, erfolgt keine Weiterleitung von Preisportalen etc. zu den Artikeln im Webshop.
|====

__Tab. 1: Optionen für die Weiterleitung bei mobilen Endgeräten__

== Verhalten im 404-Fehlerfall festlegen

In der Vergangenheit wurden ungültige URLs nicht sofort aus der Sitemap gelöscht. Daher kam es bei Änderung einer Kategorie- oder Artikelseite zu einem 404-Fehler. Die Seite wurde nicht gefunden. Mit der Sitemap-Funktion werden die Inhalte täglich neu pro Mandant generiert und ungültige Einträge fallen heraus. Nur die jeweils aktuellen und sichtbaren Inhalte werden in die Sitemaps übernommen. Mit den Einstellungen für das Verhalten im 404-Fehlerfall legen Sie fest, welche Suche dabei ausgeführt werden soll. Gleichzeitig wird direkt die HTTP-Statusmeldung 301 (Moved Permanently) ausgegeben. Dies hat zur Folge, dass nicht mehr aktuelle URL aus den Suchmaschinen gelöscht wird.

[TIP]
.Wann automatisch suchen?
====
Eine automatische Suche ist sinnvoll, wenn die neue URL gleiche oder zumindest ähnliche Bezeichnungen enthält und sie voraussichtlich einfach gefunden werden kann. Ist dies nicht der Fall, kann eine automatische Suche zu einem sogenannten Soft-404-Fehler führen. Wenn Sie im Regelfall ähnliche Inhalte anbieten, können Sie somit diese Weiterleitung verwenden. Besprechen Sie den Einsatz mit Ihrer SEO-Agentur.
====

[.instruction]
Weiterleitung bei 404-Fehler einrichten:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Webshop » Weiterleitung**.
. Nehmen Sie die Einstellungen gemäß Tabelle 2 vor.
. **Speichern** Sie die Einstellungen.

[cols="a,a"]
|====
|Einstellungen |Erläuterung

|**Umleitung bei Kategorie**
|**Inaktiv** (Standard) = Keine Weiterleitung +
**Content-Suche ausführen** = Wenn eine Kategorie-URL nicht mehr gültig ist, wird eine Suche nach einer passenden Kategorieseite ausgeführt. +
**Artikelsuche ausführen** = Wenn eine Kategorie-URL nicht mehr gültig ist, wird eine Suche nach einem passenden Artikel ausgeführt. +
**Wichtig**: Wenn diese Funktion aktiviert ist, wird eine unter **Einstellungen » Mandant (Shop) » Standard » Webshop » Seiten** als **404-Fehlerseite** hinterlegte Kategorieseite nicht angezeigt.

|**Umleitung bei Artikelseite**
|**Inaktiv** (Standard) = Keine Weiterleitung +
**Content-Suche ausführen** = Wenn eine Artikel-URL nicht mehr gültig ist, wird eine Suche nach einer passenden Kategorieseite ausgeführt. +
**Artikelsuche ausführen** = Wenn eine Artikel-URL nicht mehr gültig ist, wird eine Suche nach einem passenden Artikel ausgeführt. +
**Wichtig**: Wenn diese Funktion aktiviert ist, wird eine unter **Einstellungen » Mandant (Shop) » Standard » Webshop » Seiten** als **Seite "Artikel nicht gefunden"** hinterlegte Kategorieseite nicht angezeigt.
|====

__Tab. 2: Optionen für die Weiterleitung bei 404-Fehler (Seite nicht gefunden)__

