= Kalender
:lang: de
include::{includedir}/_header.adoc[]
:position: 100

Der plentymarkets Kalender ist ein voll integriertes Kalendermodul im Menü **Start » Kalender** Ihres plentymarkets Systems. Der Kalender bietet Ihnen die Möglichkeit, Termine zu planen, um Ihre zeitliche Organisation und die Ihrer Mitarbeiter zu steuern und interne Abläufe zu verbessern.

== Aufbau des Kalenders

Der Kalender enthält die eigenen Termine sowie die Termine der Benutzer, deren Kalender für den angemeldeten Benutzer sichtbar gestellt und im **Filter** aktiviert wurden.

Sie können zwischen der Anzeige des **Tages**, der **Woche** und des **Monats** wählen. Links oben im Kalender befindet sich die Schaltfläche **Heute**. Durch Klick auf diese Schaltfläche wechseln Sie immer zurück zur Ansicht des aktuellen Tages.

Im Filter wird eine Liste der Benutzer angezeigt, für die der angemeldete Benutzer mindestens Leserechte hat. Durch Setzen eines Häkchens werden die Termine dieses Benutzers im Kalender angezeigt.

== Benutzer als Eigner einstellen

Bis auf die Klassen **API** und **Variabel** sind alle <<basics/admin-aufgaben/benutzer-verwalten#, Benutzerklassen>> automatisch Eigner eines Kalenders. Für die Benutzerklasse **Variabel** muss die Kalendernutzung wie unten beschrieben aktiviert werden. Für die Benutzerklasse **API** ist keine Aktivierung des Kalenders möglich. Die Berechtigung kann im Tab **Eigner** eines Benutzers wieder deaktiviert werden.

[.instruction]
Benutzer als Eigner aktivieren:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Öffnen Sie den Benutzer.
. Öffnen Sie das Tab **Eigner**.
. Setzen Sie ein Häkchen bei der Option **Kalender**.
. *Speichern* Sie die Einstellungen. +
→ Der Benutzer kann Termine anlegen und bearbeiten.

Nach dem Speichern als Eigner für den Kalender wird das neue Tab **Kalender** angelegt und kann konfiguriert werden.

== Kalendereinstellungen vornehmen

Gehen Sie wie unten beschrieben vor, um die Kalendereinstellungen und Berechtigungen zu konfigurieren.

[.instruction]
Kalendereinstellungen vornehmen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Öffnen Sie den Benutzer.
. Öffnen Sie das neue Tab **Kalender**.
. Nehmen Sie die Einstellungen gemäß Tabelle 1 vor.
. *Speichern* Sie die Einstellungen.

[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Serveradresse**; +
**Serverpfad**; +
**Port**
|Wird automatisch vom System eingetragen. +
Server-Adresse und Server-Pfad sind für die Konfiguration eines externen Kalender-Tools (z.B. Google Calendar) erforderlich.

|**Neues Passwort**
|Beim Einrichten des Kalender-Accounts wird ein Passwort benötigt, das von externen Kalender-Tools abgefragt wird. Das Passwort ist hier jederzeit änderbar. +
**Hinweis:** Das Passwort wird nach dem Speichern nicht mehr angezeigt und kann nicht wiederhergestellt werden. Daher das Passwort an einem sicheren Ort notieren. +
Bei Verwendung externer Kalender-Tools muss bei einer Änderung des Passworts dort das Passwort ggf. erneut eingegeben werden.

|**Passwort wiederholen**
|Zuvor eingegebenes neues Passwort erneut eingeben, um es zu bestätigen.

|**Beschreibung**
|Die Beschreibung wird bei den Informationen bzw. Einstellungen des Kalenders angezeigt.

|**Berechtigung**
|Wählen, welche Benutzer Zugriff auf den Kalender dieses Eigners haben sollen und welche Zugriffsrechte diese Benutzer haben sollen. Um den Kalender sehen zu können, müssen Benutzer mindestens Leserechte haben. +
**Kein Zugriff** = Der Benutzer hat weder Lese- noch Schreibzugriff auf den Kalender dieses Eigners. +
**Lesen** = Der Kalender ist für den Benutzer sichtbar. +
**Schreiben** = Der Benutzer darf Termine im Kalender bearbeiten.
|====

__Tab. 1: Optionen im Tab **Kalender**__

== Termine anlegen und bearbeiten

Gehen Sie wie unten beschrieben vor, um Termine anzulegen, zu bearbeiten oder zu löschen. Abhängig von Ihren Zugriffsrechten können Sie auch Termine für anderen Benutzer anlegen oder Termine anderer Benutzer bearbeiten.

=== Termine anlegen

Sie können nur Termine für Benutzer anlegen, für die Sie Schreibrechte haben. Benutzer, für die Sie nicht über Schreibrechte verfügen, stehen beim Erstellen eines Termins nicht zur Auswahl. Gehen Sie wie unten beschrieben vor, um einen Termin anzulegen.

[.instruction]
Termin anlegen:

. Wählen Sie einen Zeitpunkt oder einen Zeitraum. Um einen Zeitpunkt zu wählen, klicken Sie bei der gewünschten Uhrzeit in das Feld. Einen Zeitraum wählen Sie, indem Sie in das Feld der gewünschten Startzeit klicken und den Cursor mit gedrückter Maustaste bis zur gewünschten Endzeit ziehen.
. Nehmen Sie die Einstellungen gemäß Tabelle 2 vor.
. *Speichern* Sie die Einstellungen.

[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Titel**
|Wird in der Kalenderübersicht angezeigt.

|**Ganztägig**
|Legt fest, dass der Termin den ganzen Tag dauert. Vor allem für Termine über mehrere Tage zu empfehlen. Termine werden dann in der Tages- und Wochenansicht in der oberen Leiste angezeigt und der Kalender bleibt übersichtlich.

|**Von / Bis**
|Datum und Uhrzeit sind voreingestellt, können jedoch angepasst werden.

|**Typ**
|Art des Termins aus der Dropdown-Liste wählen.

|**Kalender**
|Wählen, für welchen Eigner der Termin angelegt werden soll.

|**Beschreibung**
|Beschreibung eintragen, z.B. Details zum Termin. Diese Beschreibung wird auch anderen Benutzern mit Zugriffsrechten auf den Kalender in den Termininformationen angezeigt.
|====

__Tab. 2: Termininformationen__

=== Termininformationen anzeigen und ändern

Klicken Sie auf einen Termin, um die Termininformationen einzusehen. Klicken Sie rechts oben im Fenster **Termininformationen** auf das **X**, um die Detailansicht zu schließen. Sie können alle Informationen eines bestehenden Termins ändern. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Einen Termin ändern:

. Klicken Sie auf den Termin, den Sie ändern möchten. +
→ Die Termininformationen werden angezeigt.
. Nehmen Sie die gewünschten Änderungen vor.
. Klicken Sie auf **Speichern**, um die Änderungen zu sichern.

=== Termine löschen

In den Termininformationen ist auch eine Löschfunktion verfügbar. Gehen Sie wie unten beschrieben vor, um einen Termin zu löschen.

[.instruction]
Einen Termin löschen:

. Klicken Sie auf den Termin, den Sie löschen möchten. +
→ Die Termininformationen werden angezeigt.
. Klicken Sie auf **Löschen**. +
→ Der Termin wird gelöscht.

== Kalender mit externen Kalender-Tools synchronisieren

Über eine link:https://de.wikipedia.org/wiki/CalDAV[CalDAV^]-Schnittstelle synchronisieren Sie Ihren Kalender mit externen Kalender-Tools. Sie können den Kalender z.B. mit Mac Kalender oder iPad Kalender synchronisieren. Im Benutzerprofil des Benutzers muss dazu wie oben beschrieben im Tab **Eigner** die Funktion **Kalender** aktiviert sein. Sie benötigen außerdem die Einstellungen des Benutzers, die im Tab **Kalender** des Benutzers hinterlegt wurden. Informationen dazu, wie Sie Ihren Kalender mit externen Kalender-Tools synchronisieren, finden Sie in der Dokumentation des externen Kalender-Tools.
