= mailbox.org-Migration
:lang: de
include::{includedir}/_header.adoc[]
:keywords: mailbox.org, mailbox, Migration, Postfächer, Postfächer migrieren
:description: Hier erfahren Sie, wie Sie ihre von plentymarkets gehosteten Postfächer zu mailbox.org migrieren.
:position: 70

[TIP]
.Nur für plentymarkets Bestandskunden
====
Die hier beschriebene Migration ist nur für plentymarkets Kunden mit Systemen, die vor dem 23. Juni 2016 erstellt wurden relevant, für die plentymarkets bisher das Hosting ihrer E-Mail-Konten übernommen hat.
====

Seit Januar 2017 bietet plentymarkets Kunden kein E-Mail-Hosting mehr an. Als externen Anbieter empfehlen wir link:https://mailbox.org/business/[mailbox.org^]. Wenn Sie bisher von plentymarkets gehostete E-Mail-Konten verwendet haben, müssen Sie noch benötigte Postfächer zu mailbox.org migrieren.

Die Migration der E-Mail-Konten Ihrer Systembenutzer starten Sie über das Menü **System » Einstellungen » Benutzer » Konten**. Bei der Migration werden alle Ihre von plentymarkets gehosteten E-Mail-Konten gleichzeitig auf mailbox.org umgestellt. Pro plentymarkets E-Mail-Konto wird ein Postfach bei mailbox.org angelegt. Für plentymarkets E-Mail-Konten mit mehr als einer E-Mail-Adresse wählen Sie vor der Migration eine Haupt-E-Mail-Adresse. Für alle weiteren mit diesem E-Mail-Konto verbundenen E-Mail-Adressen werden Alias für das mailbox.org-Postfach erstellt. Sie wählen für jedes Postfach einen Tarif. Die Abrechnung erfolgt pro Postfach über Ihren plentymarkets Vertrag.

[TIP]
.Tipp: Leitfaden zur Migration
====
Einen detaillierten Leitfaden zur Migration zu mailbox.org finden Sie auch im link:https://forum.plentymarkets.com/t/umzug-zu-mailbox-org-leitfaden/25678[plentymarkets Forum^].
====

[WARNING]
.Provider-Wechsel umfasst nicht die Migration Ihrer E-Mails
====
Bei diesem Provider-Wechsel werden die in Ihren plentymarkets E-Mail-Konten gespeicherten E-Mail-Nachrichten nicht zu mailbox.org migriert. Sie können außerdem nicht mehr auf die alten plentymarkets Postfächer zugreifen. Wie Sie Ihre lokal gespeicherten E-Mails migrieren, erfahren Sie im Kapitel <<basics/arbeiten-mit-plentymarkets/_mailbox-migration#48, E-Mail-Nachrichten zu mailbox.org migrieren>>.
====

[#10]
== Migration vorbereiten

Treffen Sie die folgenden Vorbereitungen, bevor Sie das Hosting Ihrer E-Mail-Konten von plentymarkets zu mailbox.org migrieren.

* Die plentymarkets Tarife für das Hosting bei mailbox.org gelten pro Postfach. Prüfen Sie vor der Migration, ob Sie alle in plentymarkets gespeicherten E-Mail-Konten benötigen. Löschen Sie nicht benötigte E-Mail-Konten vor der Migration.
* Auch die Anzahl der zusätzlichen E-Mail-Adressen (Alias) pro Postfach beeinflusst Ihren Tarif. Prüfen Sie vor der Migration, ob Sie alle E-Mail-Adressen benötigen.

[#20]
== E-Mail-Postfächer zu mailbox.org migrieren

Nachdem Sie die Vorbereitungen abgeschlossen haben, migrieren Sie Ihre E-Mail-Postfächer zu mailbox.org. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
E-Mail-Postfächer zu mailbox.org migrieren:

. Melden Sie sich als Admin-Benutzer im plentymarkets Backend an.
. Öffnen Sie das Menü **System » Einstellungen » Benutzer » Konten**.
. Klicken Sie auf **Mein Konto**.
. Wechseln Sie in das Tab **E-Mail**. +
→ Eine Liste aller Ihrer von plentymarkets gehosteten E-Mail-Konten wird angezeigt.
. Klicken Sie auf **E-Mail-Provider wechseln**. +
→ Das Fenster **E-Mail-Provider wechseln** wird angezeigt.
. Klicken Sie auf **Fortfahren**. +
→ Für E-Mail-Konten mit mehreren E-Mail-Adressen werden in der Spalte **Haupt-E-Mail-Adresse** Dropdown-Listen wählbar.
. Wählen Sie pro E-Mail-Konto eine E-Mail-Adresse, z.B. die E-Mail-Adresse, an die der Systembenutzer die meisten E-Mails empfängt. +
→ Alle weiteren dem E-Mail-Konto zugeordneten E-Mail-Adressen werden als Alias migriert.
. Klicken Sie auf **Adresswahl übernehmen und fortfahren**. +
→ Die Postfächer werden aufgelistet. Postfächer, für die weitere Einstellungen erforderlich sind, sind rot gekennzeichnet.
. Klicken Sie auf das erste rot gekennzeichnete Postfach. +
→ Ein Fenster wird geöffnet.
. Prüfen Sie die Felder **Vorname** und **Nachname** und passen Sie die Informationen ggf. an.
. Geben Sie ein **Passwort** ein.
. Wiederholen Sie die Eingabe im Feld **Passwort wiederholen**.
. Wählen Sie den Tarif für dieses Postfach.
. **Speichern** Sie die Einstellungen.
. Wiederholen Sie den Vorgang für alle weiteren Postfächer, die rot gekennzeichnet sind.
. Klicken Sie auf **Kosten akzeptieren und Provider wechseln**. +
→ Die Migration Ihrer Postfächer wird gestartet. Die Postfächer und Alias werden auf dem mailbox.org-Server erstellt.

[#30]
== Auf mailbox.org-Postfächer zugreifen

Nach der Migration haben Sie über die link:https://mailbox.org/[Website von mailbox.org^] Zugriff auf Ihre neuen Postfächer. Eine Beschreibung, wie Sie bzw. andere Systembenutzer das neue mailbox.org-Postfach in Ihrem lokalen E-Mail-Programm einrichten, finden Sie z.B. in der link:https://support.mailbox.org/knowledge-base/articles/e-mail-einrichtung[mailbox.org-Wissendatenbank^].

[#40]
== Zugangsdaten für E-Mail-Server in plentymarkets ändern

Damit plentymarkets weiterhin E-Mails, z.B. Auftragsbestätigungen, versenden kann, hinterlegen Sie im Menü **System » Mandant » Mandant wählen » E-Mail » Zugangsdaten** die neuen <<crm/e-mails-versenden#100, Zugangsdaten>> des mailbox.org-Postfachs, über das Sie diese E-Mails versenden möchten.

[#50]
== Grundtarif ändern

Standardmäßig werden Postfächer nach der Migration mit dem Grundtarif **Grundtarif Business Reseller** von mailbox.org angelegt. Dieser Grundtarif gilt für alle Postfächer Ihres plentymarkets Systems inklusive aller Mandanten. Der Grundtarif ist für Sie kostenlos, umfasst jedoch keinen Support von mailbox.org. Den Grundtarif können Sie jederzeit <<basics/admin-aufgaben/benutzer-verwalten#46a, anpassen>>.

[#60]
== Alte E-Mail-Nachrichten zu mailbox.org migrieren

Die bisher auf dem plentymarkets E-Mail-Server gespeicherten E-Mails werden nicht automatisch in Ihre neuen Postfächer bei mailbox.org migriert und sind nicht mehr zugänglich. Sie können Ihre E-Mails nur noch migrieren, wenn die E-Mails in einem lokalen E-Mail-Programm gespeichert sind:

* IMAP: Sie kopieren Ihre E-Mails über ein lokales E-Mail-Programm (z.B. Mozilla Thunderbird) per IMAP-Übertragungsprotokoll auf den mailbox.org-Server.
* POP3: Sie leiten Ihre E-Mails von Ihrem lokalen E-Mail-Programm aus an den mailbox.org-Server weiter.

Diese Vorgehensweisen werden nachfolgend beschrieben.

[#70]
=== E-Mails über lokales E-Mail-Programm und IMAP migrieren

Wenn Sie keinen professionellen Anbieter beauftragen möchten, haben Sie die Möglichkeit, Ihre E-Mails über ein lokales E-Mail-Programm selbst von Ihrem plentymarkets E-Mail-Konto zu Ihrem neuen mailbox.org-Konto zu migrieren. Dazu empfehlen wir die folgende Vorgehensweise, die anhand des E-Mail-Programms link:https://www.mozilla.org/de/thunderbird/[Mozilla Thunderbird^] beschrieben wird. Beachten Sie, dass die Migration abhängig von Anzahl und Größe der E-Mails sehr viel Zeit in Anspruch nehmen kann. Wenn Ihre E-Mails in Unterordnern einsortiert sind, sollten Sie daher die Ordner einzeln kopieren.

[.instruction]
E-Mails über Thunderbird migrieren, IMAP:

. Öffnen Sie Mozilla Thunderbird.
. Ändern Sie die <<basics/arbeiten-mit-plentymarkets/_mailbox-migration#460, Server-Einstellungen>> in ihrem lokalen plentymarkets Postfach.
. Richten Sie wie link:https://support.mailbox.org/knowledge-base/article/einrichtung-mit-mozilla-thunderbird[hier^] beschrieben zusätzlich zum plentymarkets Postfach das neue mailbox.org-Postfach in Mozilla Thunderbird ein.
. Wählen Sie das Übertragungsprotokoll **IMAP**.
. Klappen Sie in der Ansicht links alle Unterordner Ihres plentymarkets Postfachs aus.
. Klicken Sie auf den ersten Unterordner und ziehen Sie ihn bei gedrückter Maustaste in das neue Postfach. +
→ Mozilla Thunderbird synchronisiert Ihre lokalen Daten mit dem mailbox.org-Postfach und lädt die E-Mails auf den IMAP-Server von mailbox.org.
. Wiederholen Sie den Vorgang, bis Sie alle Ordner des Postfachs kopiert haben.

[#80]
=== E-Mails über lokales E-Mail-Programm und POP3 migrieren

Wenn Sie das veraltete Übertragungsprotokoll POP3 für die Kommunikation eines lokalen E-Mail-Programms mit dem mailbox.org-Server wählen, ist eine Synchronisation Ihrer E-Mails über ein lokales E-Mail-Programm nicht ohne weiteres möglich. Grund dafür ist, das POP3 nur das Abrufen von Serverdaten zulässt. Wenn Sie sich dennoch für POP3 entscheiden, empfehlen wir folgende Vorgehensweise.

[.instruction]
E-Mails über Thunderbird migrieren, POP3:

. Öffnen Sie Mozilla Thunderbird.
. Ändern Sie die <<basics/arbeiten-mit-plentymarkets/_mailbox-migration#460, Server-Einstellungen>> in ihrem lokalen plentymarkets Postfach.
. Richten Sie wie link:https://support.mailbox.org/knowledge-base/article/einrichtung-mit-mozilla-thunderbird[hier^] beschrieben zusätzlich zum plentymarkets Postfach das neue mailbox.org-Postfach in Mozilla Thunderbird ein.
. Wählen Sie das Übertragungsprotokoll **POP3**.
. Klappen Sie in der Ansicht links alle Unterordner Ihres plentymarkets Postfachs aus.
. Klicken Sie auf den ersten Unterordner und ziehen Sie ihn bei gedrückter Maustaste in das neue Postfach. +
→ Die E-Mails werden lokal in Ihrem neuen Postfach gespeichert, jedoch nicht mit dem mailbox.org-Server synchronisiert, da über das Übertragungsprotokoll POP3 keine E-Mails auf den Server geladen werden können.
. Wiederholen Sie den Vorgang, bis Sie alle Ordner des Postfachs kopiert haben.
. Wenn die E-Mails auch auf dem mailbox.org-Server gespeichert werden sollen, leiten Sie die E-Mails an die E-Mail-Adresse bei mailbox.org weiter. Um bei der Weiterleitung Absender und Inhalt der Nachricht beizubehalten, stehen Tools wie z.B. das kostenlose Thunderbird-Add-On link:http://mailredirect.sourceforge.net/index.html[mailredirect^] zur Verfügung.
