= Allgemeine Funktionen nutzen
:lang: de
include::{includedir}/_header.adoc[]
:description: Arbeiten mit plentymarkets: Fügen Sie Menüs als Favoriten hinzu, passen Sie die Menüansicht an und nutzen Sie weitere allgemeine Funktionen.
:position: 40

Diese Handbuchseite beschreibt Funktionen in plentymarkets, die übergreifend oder in mehreren Bereichen des Systems zu finden sind.

[#10]
== Schnellzugriff auf allgemeine Funktionen

Folgende Buttons (von links nach rechts) ermöglichen den Schnellzugriff auf wichtige Bereiche aus der Kopfzeile des plentymarkets Administrationsbereichs heraus:

* *Webshop aufrufen* +
Auf die plenty-ID rechts oben im Menü klicken, um die Startseite Ihres Webshops aufzurufen.
* *Kundensuche* +
Unter *CRM » Schnellsuche* finden Sie die Kundensuche. Setzen Sie mindestens einen Filter, um die Suchfunktion zu nutzen. Klicken Sie auf *Suchen*, um nach Kunden zu suchen.
* **Statistik** +
Mit dem Statistikmodul können Sie eine Vielzahl von Auswertungen anzeigen lassen. Klicken Sie auf *plentymarkets Logo » Statistik*, um das <<basics/statistik#, Statistikmodul>> zu öffnen.
* *Support* +
Unter *Support* können Sie verschiedene Supportangebote und sämtliche Partnerangebote aufrufen. +
*Service* +
- *Handbuch* öffnet die link:/[**Startseite**] des plentymarkets Handbuchs, in dem alle Funktionen ausführlich beschrieben sind.
- *Video Tutorials* öffnet eine Übersicht der plentymarkets Video-Tutorials zu verschiedenen Funktionen.
- *Forum* öffnet die Startseite des plentymarkets Forums zum Austausch mit unseren Mitarbeitern.
- *Support-Hotline* öffnet eine Support-Webseite. Dort können Sie Termine buchen und ihre gebuchten Termine einsehen.
- *Entwicklerdoku* öffnet plentyDevelopers. Dort sind umfangreiche Informationen für Entwickler gesammelt. +
*Partnerangebot* +
- *Agentursuche* öffnet eine Seite zur Suche von Partneragenturen. Geben Sie dort ihre Postleitzahl ein, um Partneragenturen in Ihrem Umkreis zu finden.
- *Service buchen* öffnet eine Übersicht der von plentymarkets angebotenen Services.
- *Projektbörse* öffnet *plentyMarketplace » Tab: Projekte*. Melden Sie sich an, um

[#20]
== Menüansicht anpassen

Sie können sowohl die gesamte Menüansicht als auch die Übersicht innerhalb eines Menüs anpassen. Außerdem können Sie die Positionen der Menüansicht sortieren.

[#30]
=== Menüansicht wechseln

Wählen Sie zwischen der horizontalen Menüansicht und der vertikalen Menüansicht. Wechseln Sie die Ansicht mit einem Klick auf den Pfeil in der oberen linken Ecke Ihrer Startseite.

[#40]
=== Menüansicht einrichten

Sie können die Ansicht innerhalb eines Menüs, d.h. die Spalten der Parameter, die angezeigt werden sollen, individuell pro Menü einrichten. Bild 2 zeigt als Beispiel die Übersicht des Menüs **Artikel » Artikel bearbeiten**.

[.instruction]
Ansicht eines Menüs einrichten:

. Zeigen Sie mit der Maus auf die Titelzeile des Menüs.  +
→ Der Button **Ansicht einrichten** wird angezeigt.
. Klicken Sie auf **Ansicht einrichten**.  +
→ Das Fenster **Ansicht einrichten** wird geöffnet.
. Aktivieren Sie die Parameter, die in der Menüansicht angezeigt werden sollen.  +
→  Wenn ein Parameter nicht mehr angezeigt werden soll, deaktivieren Sie den Parameter.
. **Speichern** Sie die Einstellungen.

[#50]
=== Positionen der Menüansicht sortieren

Gehen Sie wie im Folgenden beschrieben vor, um die Positionen der Menüansicht anhand einer Spalte alphabetisch bzw. numerisch aufsteigend oder absteigend zu sortieren.

[.instruction]
Positionen der Menüansicht sortieren:

. Zeigen Sie mit der Maus auf die Überschrift der Spalte, nach der Sie sortieren möchten. +
→ Ein kleines Dreieck wird angezeigt.
. Klicken Sie auf das Dreieck, um die Einträge anhand dieser Spalte zu sortieren. +
→ Wenn das Dreieck nach unten zeigt, werden die Spalteneinträge aufsteigend sortiert (der größte Wert steht oben). Zeigt das Dreieck nach oben, wird absteigend sortiert.

[#60]
== Kontextmenü über Rechtsklick aufrufen

Der Rechtsklick in plentymarkets auf ausgewählte Tabs und Buttons ermöglicht es Ihnen, schnell gezielte Aktionen auszuführen.

Mit einem Rechtsklick im Menü **Artikel » Kategorien** auf eine Kategorie z.B. haben Sie die Möglichkeit, die Kategorie zu bearbeiten, zu verschieben, zu kopieren, zu löschen, eine Unterkategorie oder einen neuen Artikel zu erstellen. Im Menü **CMS » Bilder-Galerie** können Sie z.B. mit einem Rechtsklick auf die Bilderordner im Verzeichnisbaum auf der linken Seite komplette Ordner mit Inhalt löschen.

[#70]
== Favoriten verwalten

Favoriten dienen dazu, häufig gebrauchte Menüpunkte schnell aufzurufen. Favoriten werden rechts oben im Menü unter dem Stern-Symbol angezeigt. Fahren Sie mit der Maus über das Stern-Symbol, um Ihre Favoriten anzuzeigen.

[.instruction]
Menü zu Favoriten hinzufügen:

. Öffnen Sie das Menü, das Sie als Favorit hinzufügen wollen.
. Klicken Sie in der Dropdown-Liste des Menüs auf **Link zu Favoriten hinzufügen**. +
. Prüfen Sie im Menü **System » Einstellungen » Benutzer » Konten** unter **Mein Konto** im Tab **Persönliche Einstellungen » Favoriten**, ob das Menü zu den Favoriten hinzugefügt wurde.  +
→ **__Hinweis__**: Favoriten sind im Menü erst sichtbar, wenn Sie mindestens einen Favoriten gespeichert haben.

[.instruction]
Menü aus Favoriten entfernen:

. Fahren Sie mit der Maus über das Stern-Symbol rechts oben im Menü.
→ In der Dropdown-Liste werden Ihre gespeicherten Favoriten angezeigt. +
. Klicken Sie im Menü auf das *x*, um das Menü aus den Favoriten zu entfernen.
. Prüfen Sie im Menü **System » Einstellungen » Benutzer » Konten** unter **Mein Konto** im Tab **Persönliche Einstellungen » Favoriten**, ob das Menü aus den Favoriten entfernt wurde.
→ **__Hinweis__**: Klicken sie in der Dropdown-Liste auf *Alle Favoriten löschen* und bestätigen Sie das Pop-up Fenster mit *Löschen*, um alle Favoriten zu löschen.

[#80]
== Mehrere Optionen wählen

Wenn Sie in Auswahlfeldern die Möglichkeit haben, mehrere Optionen gleichzeitig zu wählen, drücken Sie die Strg-Taste (Windows) bzw. die cmd-Taste (Mac) und klicken auf die Optionen. Optionen, die beim Öffnen eines Auswahlfensters ausgegraut sind, wurden bereits gespeichert. Sie können nun per Strg- bzw. cmd-Taste und Mausklick weitere Optionen dazuwählen. Alternativ können Sie per Mausklick die bereits gewählten Optionen deaktivieren. Während der Bearbeitung werden alle gewählten Optionen - auch diejenigen, die vorher ausgegraut waren - blau angezeigt.

[#90]
== Zugriff auf Drucker einrichten

Installieren Sie zunächst das *plentyBase-Plugin*, um den Zugriff auf Drucker zu ermöglichen. Das Plugin ist im link:https://marketplace.plentymarkets.com/plugins/markets[*plentyMarketplace*^] verfügbar.

Sobald Sie das Plugin installiert haben, öffnen Sie das Menü *System » Einstellungen » Drucker*, um lokal oder in ihrem Netzwerk installierte Drucker in Ihrem plentymarkets System einzurichten. Mehr Informationen zur Einrichtung und Konfiguration von Druckern finden Sie link:https://knowledge.plentymarkets.com/basics/arbeiten-mit-plentymarkets/drucker[*hier*^].

[#100]
== Drag &amp; Drop-Funktion nutzen

Sie können Bilder und Dateien per Drag &amp; Drop-Funktion in Ihr plentymarkets System ziehen und auf diese Weise dort speichern. Das folgende Videotutorial veranschaulicht die Anwendung der Drag &amp; Drop-Funktion in einem Beispiel:

video::41029698[vimeo]

[#110]
== Ungesicherte Änderungen anzeigen

In den Menüs **CMS » Webdesign » Layout** und **Artikel » Kategorien** z.B. werden Tabs durch eine rote Markierung gekennzeichnet, wenn Sie Änderungen vorgenommen, diese jedoch noch nicht gespeichert haben. Diese Markierung wird auch links im Menübaum angezeigt.

Wenn Sie eine Kategorie schließen, ohne die Änderungen gespeichert zu haben, erscheint ein Hinweisfenster, das Sie aktiv bearbeiten müssen, um fortzufahren.

* Klicken Sie auf **Schließen**, um die Kategorie zu schließen, ohne die Änderungen zu speichern.
* Klicken Sie auf **Abbrechen**, um die Änderungen zu speichern oder weitere Anpassungen vorzunehmen.

Wenn Sie solche Meldungen nicht mehr angezeigt bekommen möchten, deaktivieren Sie die Funktion.

[.instruction]
Meldungen deaktivieren:

. Öffnen Sie das Menü **System » Einstellungen » Benutzer » Konten**.
. Klicken Sie auf **Mein Konto**.
. Wechseln Sie in das Tab **Persönliche Einstellungen » Allgemein**.
. Deaktivieren Sie die Option **Warnen, wenn Tabs offen sind und das Fenster geschlossen wird**.
. **Speichern** Sie die Einstellungen.
