= Aufgaben und Kalender verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Aufgabe, Aufgaben, Kalender, Termin
:description: xx
:position: 50

allgemeine einleitung
Nutzen Sie das Menü *Start » Aufgaben*, um Tätigkeiten für alle Benutzer des Systems zu verwalten, z.B. "Rechnung 123 korrigieren" oder "Kunde Mustermann anrufen". Sie sehen den Fortschritt einer Aufgabe und können weitere Abläufe für Ihr Geschäft planen sowie interne Abläufe verbessern.

Sie können Aufgaben nicht nur in diesem Menü erstellen, sondern auch in einem Ticket im <<crm/ticketsystem-nutzen#4000, Ticketsystem>>. So können Sie z.B. zu einer telefonischen Kundenanfrage direkt eine Aufgabe erstellen.

==  Aufgabe erstellen

Eine Aufgabe konfigurieren Sie nach Klick auf die Aufgabe in der Übersicht. Die Optionen werden in <<tabelle-neue-aufgabe>> erläutert. Die ID wird automatisch vergeben und kann nicht geändert werden. Wenn eine Ticket-ID aus dem Ticketsystem hinterlegt wurde, gelangen Sie über den Link direkt zum Ticket.

[IMPORTANT]
.Aufgaben und Tickets
====
Um Aufgaben einem Ticket zuzuordnen, muss die Aufgabe im *Ticket* angelegt werden. Jedes Ticket hat ein Tab *Aufgaben*, in dem eine *Neue Aufgabe* angelegt wird. Aufgaben, die im Ticket angelegt wurden, werden ebenfalls hier in der Aufgabenübersicht angezeigt.
====

Gehen Sie wie im Folgenden beschrieben vor, um eine Aufgabe zu erstellen.

[.instruction]
Aufgabe erstellen:

.  Öffnen Sie das Menü *Start » Aufgaben*.
.  Klicken Sie auf *Neue Aufgabe*. +
→ Das Tab *Neue Aufgabe* wird geöffnet.
.  Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-aufgabe-erstellen>>.
.  *Speichern* Sie die Einstellungen.

[[tabelle-aufgabe-erstellen]]
.Aufgabe erstellen
[cols="a,a"]
|====
| Einstellung | Erläuterung

|*Titel*
| Titel für die Aufgabe eingeben.

|*Priorität*
| Priorität wählen. Die Prioritäten reichen von *0 = grauer Stern* bis *5 = zwei gelbe Sterne*.

|*Fortschritt*
| Prozentsatz wählen. Dieser zeigt an, wie weit die Aufgabe fortgeschritten ist. Der Fortschritt muss je nach Fortschreiten der Aufgabe vom Bearbeiter manuell angepasst werden.

|*Markierung*
| Markierung wählen. Die Markierung hilft, Aufgaben später wiederzufinden.

|*Eigner*
|Eigner wählen. Der Eigner ist der Verantwortliche für die Aufgabe.

|*Beschreibung*
| Beschreibung der Aufgabe eingeben und Text ggf. formatieren. Details zum Editor finden Sie auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-werkzeuge-editor, Editor>>.
|====



==  Aufgabenübersicht aufrufen

Die Aufgabenübersicht wird beim Öffnen des Menüs angezeigt. Wenn Sie bereits Aufgaben angelegt haben, werden alle bestehende Aufgaben in absteigender ID-Reihenfolge aufgeführt. Sie können bis zu 100 Aufgaben pro Seite anzeigen lassen.

[NOTE]
.Aufgaben bearbeiten
====
Klicken Sie in der Übersicht in die Zeile der Aufgabe, um diese zu öffnen. Beachten Sie die Erläuterungen zu den Einstellungen in <<tabelle-aufgabe-erstellen>>.
====

[TIP]
.Standard-Filter zeigen eigene unerledigte Aufgaben
====
Durch die Standard-Einstellung der Filter *Fortschritt &gt;100%* und der aktive Benutzer bei *Eigner* werden beim Aufruf des Menüs alle eigenen unerledigten Aufgaben gelistet. Klicken Sie auf *Reset* und dann auf *Suchen*, um die Filter zu entfernen und alle Aufgaben im System anzeigen zu lassen oder setzen Sie eigene Filter für Ihre Suche (Kapitel 3.1).
====

==  Aufgaben suchen

Nutzen Sie die *Suchfilter*, um auch bei einer großen Anzahl an Aufgaben den Überblick zu behalten und gezielt Aufgaben zu suchen. Für jede Einstellung, die Sie bei einer neuen Aufgabe vornehmen können, stehen Ihnen Filter zur Verfügung. Zusätzlich haben Sie Filter für Parameter wie das *Erstellungsdatum* oder die *Aufgaben-ID*.


[.instruction]
Aufgaben suchen:

.  Öffnen Sie das Menü *Start » Aufgaben*.
.  Wählen Sie die *Filter* entsprechend der Erläuterungen in <<tabelle-aufgabe-suchen>>.
.  Klicken Sie auf *Suchen*, um die Suche auszuführen.

[[tabelle-aufgabe-suchen]]
.Aufgabe suchen
[cols="a,a"]
|====
| Filter | Erläuterung

|*Titel/Beschreibung*
|  Text eingeben, um nach diesem zu filtern. Es handelt sich um eine Volltextsuche, die den *Titel* und die *Beschreibung* der Aufgaben durchsucht. Tragen Sie mindestens 4 Zeichen für die Suche ein.

|*ID*
|  ID eingeben, um die Aufgabe mit dieser ID zu suchen. Die Aufgaben-IDs werden automatisch vom System vergeben und sind fortlaufend.

|*Ticket-ID*
|  Ticket-ID eingeben, um die Aufgabe(n) zu suchen, die zu diesem Ticket gehören.

|*Fortschritt*
|  Operator und Fortschritt wählen. So lassen sich z.B. alle Aufgaben suchen, die bereits zu 60 % oder mehr erledigt sind.

|*Priorität*
|  Operator und Priorität wählen. So lassen sich z.B. alle Aufgaben suchen, die Priorität 2 oder höher haben.

|*Datum der Erstellung*
|  Operator und Datum wählen. So lassen sich z.B. alle Aufgaben suchen, die vor einem bestimmten Tag angelegt wurden.

|*Eigner*
|  Eigner wählen, um nur die Aufgaben dieses Eigners zu suchen.

|*Markierung*
|  Markierung wählen, um nur Aufgaben mit dieser Markierung zu suchen.
|====

== Kalender


Der plentymarkets Kalender ist ein voll integriertes Kalendermodul im Menü *Start » Kalender* Ihres plentymarkets Systems. Der Kalender bietet Ihnen die Möglichkeit, Termine zu planen, um Ihre zeitliche Organisation und die Ihrer Mitarbeiter zu steuern und interne Abläufe zu verbessern.


Der Kalender enthält die eigenen Termine sowie die Termine der Benutzer, deren Kalender für den angemeldeten Benutzer sichtbar gestellt und im *Filter* aktiviert wurden.

Sie können zwischen der Anzeige des *Tages*, der *Woche* und des *Monats* wählen. Links oben im Kalender befindet sich der Button *Heute*. Durch Klick auf diesen Button wechseln Sie immer zurück zur Ansicht des aktuellen Tages.

Im Filter wird eine Liste der Benutzer angezeigt, für die der angemeldete Benutzer mindestens Leserechte hat. Durch Setzen eines Häkchens werden die Termine dieses Benutzers im Kalender angezeigt.

== Benutzer als Eigner einstellen

Bis auf die Klassen *API* und *Variabel* sind alle <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#, Benutzerklassen>> automatisch Eigner eines Kalenders. Für die Benutzerklasse *Variabel* muss die Kalendernutzung wie unten beschrieben aktiviert werden. Für die Benutzerklasse *API* ist keine Aktivierung des Kalenders möglich. Die Berechtigung kann im Tab *Eigner* eines Benutzers wieder deaktiviert werden.

[.instruction]
Benutzer als Eigner aktivieren:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den Benutzer.
. Öffnen Sie das Tab *Eigner*.
. Aktivieren Sie die Option *Kalender*.
. *Speichern* Sie die Einstellungen. +
→ Der Benutzer kann Termine anlegen und bearbeiten.

Nach dem Speichern als Eigner für den Kalender wird das neue Tab *Kalender* angelegt und kann konfiguriert werden.

== Kalendereinstellungen vornehmen

Gehen Sie wie unten beschrieben vor, um die Kalendereinstellungen und Berechtigungen zu konfigurieren.

[.instruction]
Kalendereinstellungen vornehmen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den Benutzer.
. Öffnen Sie das neue Tab *Kalender*.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-kalendereinstellungen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-kalendereinstellungen]]
.Kalendereinstellungen vornehmen
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Serveradresse*; +
*Serverpfad*; +
*Port*
|Wird automatisch vom System eingetragen. +
Server-Adresse und Server-Pfad sind für die Konfiguration eines externen Kalender-Tools (z.B. Google Calendar) erforderlich.

|*Neues Passwort*
|Beim Einrichten des Kalender-Accounts wird ein Passwort benötigt, das von externen Kalender-Tools abgefragt wird. Das Passwort ist hier jederzeit änderbar. +
*Hinweis:* Das Passwort wird nach dem Speichern nicht mehr angezeigt und kann nicht wiederhergestellt werden. Daher das Passwort an einem sicheren Ort notieren. +
Bei Verwendung externer Kalender-Tools muss bei einer Änderung des Passworts dort das Passwort ggf. erneut eingegeben werden.

|*Passwort wiederholen*
|Zuvor eingegebenes neues Passwort erneut eingeben, um es zu bestätigen.

|*Beschreibung*
|Die Beschreibung wird bei den Informationen bzw. Einstellungen des Kalenders angezeigt.

|*Berechtigung*
|Wählen, welche Benutzer Zugriff auf den Kalender dieses Eigners haben sollen und welche Zugriffsrechte diese Benutzer haben sollen. Um den Kalender sehen zu können, müssen Benutzer mindestens Leserechte haben. +
*Kein Zugriff* = Der Benutzer hat weder Lese- noch Schreibzugriff auf den Kalender dieses Eigners. +
*Lesen* = Der Kalender ist für den Benutzer sichtbar. +
*Schreiben* = Der Benutzer darf Termine im Kalender bearbeiten.
|====

== Termine anlegen und bearbeiten

Gehen Sie wie im Folgenden beschrieben vor, um Termine anzulegen, zu bearbeiten oder zu löschen. Abhängig von Ihren Zugriffsrechten können Sie auch Termine für anderen Benutzer anlegen oder Termine anderer Benutzer bearbeiten.

=== Termine anlegen

Sie können nur Termine für Benutzer anlegen, für die Sie Schreibrechte haben. Benutzer, für die Sie nicht über Schreibrechte verfügen, stehen beim Erstellen eines Termins nicht zur Auswahl. Gehen Sie wie unten beschrieben vor, um einen Termin anzulegen.

[.instruction]
Termin anlegen:

. Wählen Sie einen Zeitpunkt oder einen Zeitraum. Um einen Zeitpunkt zu wählen, klicken Sie bei der gewünschten Uhrzeit in das Feld. Einen Zeitraum wählen Sie, indem Sie in das Feld der gewünschten Startzeit klicken und den Cursor mit gedrückter Maustaste bis zur gewünschten Endzeit ziehen.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-termininformationen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-termininformationen]]
.Kalendereinstellungen vornehmen
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Titel*
|Wird in der Kalenderübersicht angezeigt.

|*Ganztägig*
|Legt fest, dass der Termin den ganzen Tag dauert. Vor allem für Termine über mehrere Tage zu empfehlen. Termine werden dann in der Tages- und Wochenansicht in der oberen Leiste angezeigt und der Kalender bleibt übersichtlich.

|*Von / Bis*
|Datum und Uhrzeit sind voreingestellt, können jedoch angepasst werden.

|*Typ*
|Art des Termins aus der Dropdown-Liste wählen.

|*Kalender*
|Wählen, für welchen Eigner der Termin angelegt werden soll.

|*Beschreibung*
|Beschreibung eingeben, z.B. Details zum Termin. Diese Beschreibung wird auch anderen Benutzern mit Zugriffsrechten auf den Kalender in den Termininformationen angezeigt.
|====

=== Termininformationen anzeigen und ändern

Klicken Sie auf einen Termin, um die Termininformationen einzusehen. Klicken Sie rechts oben im Fenster *Termininformationen* auf das *X*, um die Detailansicht zu schließen. Sie können alle Informationen eines bestehenden Termins ändern. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Einen Termin ändern:

. Klicken Sie auf den Termin, den Sie ändern möchten. +
→ Die Termininformationen werden angezeigt.
. Nehmen Sie die gewünschten Änderungen vor.
. Klicken Sie auf *Speichern*, um die Änderungen zu sichern.

=== Termin löschen

In den Termininformationen ist auch eine Löschfunktion verfügbar. Gehen Sie wie unten beschrieben vor, um einen Termin zu löschen.

[.instruction]
 Termin löschen:

. Klicken Sie auf den Termin, den Sie löschen möchten. +
→ Die Termininformationen werden angezeigt.
. Klicken Sie auf *Löschen*. +
→ Der Termin wird gelöscht.

== Kalender mit externen Kalender-Tools synchronisieren

Über eine link:https://de.wikipedia.org/wiki/CalDAV[CalDAV^]-Schnittstelle synchronisieren Sie Ihren Kalender mit externen Kalender-Tools. Sie können den Kalender z.B. mit Mac Kalender oder iPad Kalender synchronisieren. Im Benutzerprofil des Benutzers muss dazu wie oben beschrieben im Tab *Eigner* die Funktion *Kalender* aktiviert sein. Sie benötigen außerdem die Einstellungen des Benutzers, die im Tab *Kalender* des Benutzers hinterlegt wurden. Informationen dazu, wie Sie Ihren Kalender mit externen Kalender-Tools synchronisieren, finden Sie in der Dokumentation des externen Kalender-Tools.
