= Aufgaben und Kalender verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Aufgabe, Aufgaben, Ticketaufgabe, Ticketaufgaben, Ticket-Aufgabe, Kalender, Termin, Eigner, Berechtigung, Zugriffsrecht, Leserecht, Schreibrecht, CalDAV, caldav, CALDAV, CalDAV-Schnittstelle, Kalender synchronisieren, externes Kalender-Tool,
:description: Erfahren Sie, wie Sie Aufgaben und Kalender in plenytmarkets verwalten.
:position: 50

Erfahren Sie auf dieser Handbuchseite, wie Sie <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#100, Aufgaben>> und <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#600, Kalender>> verwalten.

[#100]
== Aufgaben verwalten

Nutzen Sie das Menü *Start » Aufgaben*, um Tätigkeiten für alle Benutzer des Systems zu verwalten, z.B. "Kunde xy anrufen". Sie sehen den Fortschritt einer Aufgabe und können weitere Abläufe für Ihr Geschäft planen sowie interne Abläufe verbessern.

Sie können Aufgaben nicht nur im Menü *Start » Aufgaben* erstellen, sondern auch in einem Ticket im <<crm/ticketsystem-nutzen#4000, Ticketsystem>>. So können Sie z.B. zu einer telefonischen Kundenanfrage direkt eine Aufgabe erstellen. Aufgaben, die Sie im Menü *CRM » Ticketsystem » Ticket öffnen » Tab: Aufgaben* erstellen, sind mit dem Ticket verknüpft. Diese Verknüpfung wird auch in der Aufgabenübersicht im Menü *Start » Aufgaben* angezeigt.

[#200]
=== Sichtbarkeit der Aufgaben für variablen Benutzer einstellen

Damit für Benutzer mit der Benutzerklasse *Variabel* das Menü *Start » Aufgaben* sichtbar ist, muss das Menü im Benutzerkonto freigeschaltet werden.

[.instruction]
Sichtbarkeit der Aufgaben für variablen Benutzer einstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den Benutzer mit der Benutzerklasse *Variabel*, für den Sie die Sichtbarkeit des Menüs aktivieren möchten.
. Wechseln Sie in das Tab *Berechtigung*.
. Wechseln Sie in das Tab *Menü*.
. Klappen Sie den Bereich *Start* auf.
. Aktivieren Sie die Option *Aufgaben*.
. *Speichern* Sie die Einstellungen.

[#300]
=== Aufgabe erstellen

Gehen Sie wie im Folgenden beschrieben vor, um eine Aufgabe zu erstellen. Die Aufgaben-ID wird automatisch vergeben und kann nicht geändert werden.

[.instruction]
Aufgabe erstellen:

. Öffnen Sie das Menü *Start » Aufgaben*. +
→ *_Tipp:_* Zeigen Sie dazu mit der Maus auf das plentymarkets Logo oben links.
. Klicken Sie auf *Neue Aufgabe*. +
→ Das Tab *Neue Aufgabe* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-aufgabe-erstellen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-aufgabe-erstellen]]
.Aufgabe erstellen
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Titel*
| Titel für die Aufgabe eingeben.

|*Priorität*
| Priorität wählen. Die Prioritäten reichen von *0 = grauer Stern* bis *5 = zwei gelbe Sterne*.

|*Fortschritt*
| Prozentsatz wählen. Dieser zeigt an, wie weit die Aufgabe fortgeschritten ist. Der Fortschritt muss je nach Fortschreiten der Aufgabe vom Bearbeiter manuell angepasst werden.

|*Markierung*
| Markierung wählen. Die Markierung hilft, Aufgaben später wiederzufinden.

|*Eigner*
|Eigner wählen. Der Eigner ist eine Pflichteinstellung. Der Eigner ist der Verantwortliche für die Aufgabe.

|*Beschreibung*
|Beschreibung der Aufgabe eingeben und Text ggf. formatieren.
|====

[#400]
=== Aufgaben suchen

Beim Öffnen des Menüs *Start » Aufgaben* werden standardmäßig alle Aufgaben mit einem Fortschritt unter 100% des aktuell aktiven Benutzers angezeigt. Wenn Sie eine Aufgabe über das <<crm/ticketsystem-nutzen#4000, Ticketsystem>> erstellt haben, wird ebenfalls die Ticket-ID sowie der Tickettitel in der Übersicht angezeigt. Mit einem Klick auf die Ticket-ID gelangen Sie direkt zum Ticket.

Nutzen Sie die Suchfilter, um auch bei einer großen Anzahl an Aufgaben den Überblick zu behalten und gezielt Aufgaben zu suchen.

[.instruction]
Aufgaben suchen:

. Öffnen Sie das Menü *Start » Aufgaben*. +
→ Alle eigenen unerledigten Aufgaben werden angezeigt, da beim Öffnen des Menüs standardmäßig der Filter für den Fortschritt auf *< 100%* gesetzt und in der Dropdown-Liste *Eigner* der aktive Benutzer vorausgewählt ist.
. Klicken Sie auf *Reset*, um die Filter zu entfernen.
. Wählen Sie die Filter. Beachten Sie dazu die Erläuterungen in <<tabelle-aufgabe-suchen>>.
. Klicken Sie auf *Suchen*. +
→ Die Aufgaben, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

[[tabelle-aufgabe-suchen]]
.Aufgabe suchen
[cols="1,3"]
|====
| Filter | Erläuterung

|*Titel/Beschreibung*
|Text eingeben, um nach diesem zu filtern. Es handelt sich um eine Volltextsuche, die den *Titel* und die *Beschreibung* der Aufgaben durchsucht. Mindestens 4 Zeichen für die Suche eingeben.

|*ID*
|ID eingeben, um die Aufgabe mit dieser ID zu suchen. Die Aufgaben-IDs werden automatisch vom System vergeben und sind fortlaufend. Die ID kann nicht geändert werden.

|*Ticket-ID*
|Ticket-ID eingeben, um die Aufgabe(n) zu suchen, die zu diesem Ticket gehören.

|*Fortschritt*
|Operator und Fortschritt wählen. So lassen sich z.B. alle Aufgaben suchen, die bereits zu 60 % oder mehr erledigt sind.

|*Priorität*
|Operator und Priorität wählen. So lassen sich z.B. alle Aufgaben suchen, die Priorität 2 oder höher haben.

|*Datum der Erstellung*
|Operator und Datum wählen. So lassen sich z.B. alle Aufgaben suchen, die vor einem bestimmten Tag angelegt wurden.

|*Eigner*
|Eigner wählen, um nur die Aufgaben dieses Eigners zu suchen.

|*Markierung*
|Markierung wählen, um nur Aufgaben mit dieser Markierung zu suchen.
|====

[#500]
=== Aufgabe bearbeiten

Sie können Aufgaben jederzeit bearbeiten, um z.B. den Fortschrittsbalken anzupassen oder die Beschreibung zu ergänzen.

[.instruction]
Aufgabe bearbeiten:

. Öffnen Sie das Menü *Start » Aufgaben*. +
→ Alle eigenen unerledigten Aufgaben werden angezeigt, da beim Öffnen des Menüs standardmäßig der Filter für den Fortschritt auf *< 100%* gesetzt und in der Dropdown-Liste *Eigner* der aktive Benutzer vorausgewählt ist. +
. Klicken Sie auf *Reset*, um die Filter zu entfernen.
. Wählen Sie die Filter. Beachten Sie die Erläuterungen in <<tabelle-aufgabe-suchen>> im Kapitel <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#400, Aufgabe suchen>>. +
→ Die Aufgaben, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile der Aufgabe. +
→ Die Aufgabe wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-aufgabe-erstellen>> im Kapitel <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#300, Aufgabe erstellen>>.
. *Speichern* Sie die Einstellungen.

[#550]
=== Aufgaben auf dem Dashboard anzeigen

Sie können Ihre unerledigten Aufgaben auf dem Dashboard anzeigen lassen. Auf diese Weise sehen Sie direkt zu Arbeitsbeginn, welche Aufgaben noch erledigt werden müssen.

Setzen Sie auf dem Dashboard direkt bei der Aufgabe ein Häkchen, wenn Sie diese erledigt haben. Diese Aufgabe wird dann auch im Menü *Start » Aufgaben* aktualisiert und erhält den Status *100%*.


[.instruction]
Aufgaben auf dem Dashboard anzeigen:

. Öffnen Sie Ihr plentymarkets System. +
→ Das Dashboard wird angezeigt.
. Wählen Sie aus der Dropdown-Liste das Element *Meine Aufgaben*. +
→ Der Bereich *Meine Aufgaben* wird Ihnen ab sofort auf dem Dashboard angezeigt, wenn Sie Ihr plentymarkets System öffnen.

Mit einem Klick auf *ToDo eingeben* im Bereich *Meine Aufgaben* gelangen Sie direkt in das Menü *Start » Aufgaben* und können dort eine neue <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#300, Aufgabe erstellen>>.

Welche Elemente Sie außerdem auf dem Dashboard anzeigen können, ist auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#, Benutzerkonto personalisieren>> im Kapitel <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#70, Dashboard personalisieren>> beschrieben.

[#600]
== Kalender verwalten

Der Kalender im Menü *Start » Kalender* Ihres plentymarkets Systems bietet Ihnen die Möglichkeit, Termine zu planen, um Ihre zeitliche Organisation und die Ihrer Mitarbeiter zu steuern und interne Abläufe zu verbessern.

Der Kalender enthält die eigenen Termine sowie die Termine der Benutzer, deren Kalender für den angemeldeten Benutzer sichtbar gestellt und im *Filter* aktiviert wurden.

Sie können zwischen der Anzeige des Tages, der Woche und des Monats wählen. Durch Klick auf den Button *Heute* wechseln Sie zurück zur Ansicht des aktuellen Tages.

Im Filter wird eine Liste der Benutzer angezeigt, für die der angemeldete Benutzer mindestens Leserechte hat. Durch Setzen eines Häkchens werden die Termine dieses Benutzers im Kalender angezeigt. Sie können die Kalender mehrerer Benutzer gleichzeitig anzeigen.

[#650]
=== Sichtbarkeit des Kalenders für variablen Benutzer einstellen

Damit für Benutzer mit der Benutzerklasse *Variabel* das Menü *Start » Kalender* sichtbar ist, muss das Menü im Benutzerkonto freigeschaltet werden.

[.instruction]
Sichtbarkeit des Kalenders für variablen Benutzer einstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den Benutzer mit der Benutzerklasse *Variabel*, für den Sie die Sichtbarkeit des Menüs aktivieren möchten.
. Wechseln Sie in das Tab *Berechtigung*.
. Wechseln Sie in das Tab *Menü*.
. Klappen Sie den Bereich *Start* auf.
. Aktivieren Sie die Option *Kalender*.
. *Speichern* Sie die Einstellungen.

[#700]
=== Variablen Benutzer als Eigner einstellen

Bis auf die Klassen *API* und *Variabel* sind alle <<basics/admin-aufgaben/benutzer-verwalten#10, Benutzerklassen>> automatisch Eigner eines Kalenders. Für die Benutzerklasse *API* ist keine Aktivierung des Kalenders möglich. Für die Benutzerklasse *Variabel* muss die Kalendernutzung wie im Folgenden beschrieben aktiviert werden.

Die Berechtigung kann im Tab *Eigner* eines Benutzers jederzeit wieder deaktiviert werden.

[.instruction]
Variablen Benutzer als Eigner einstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den Benutzer mit der Benutzerklasse *Variabel*, den Sie als Eigner des Kalenders einstellen möchten.
. Wechseln Sie in das Tab *Eigner*.
. Aktivieren Sie die Option *Kalender*.
. *Speichern* Sie die Einstellungen. +
→ Das neue Tab *Kalender* ist sichtbar und kann wie im nächsten Kapitel beschrieben konfiguriert werden.

[#800]
=== Grundeinstellungen im Kalender vornehmen und Zugriffsrechte für Benutzer einstellen

Gehen Sie wie im Folgenden beschrieben vor, um Grundeinstellungen im Kalender wie z.B. die Vergabe des Passwort vorzunehmen und die Zugriffsrechte für Benutzer einzustellen. Sie können zwischen den Einstellungen *Kein Zugriff*, *Lesen* und *Lesen & Schreiben* wählen.

[.instruction]
Grundeinstellungen im Kalender vornehmen und Zugriffsrechte für Benutzer einstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den Benutzer.
. Öffnen Sie das Tab *Kalender*.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-kalender-grundeinstellungen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-kalender-grundeinstellungen]]
.Grundeinstellungen im Kalender vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Serveradresse*; +
*Serverpfad*; +
*Port*
|Wird automatisch vom System gespeichert. +
Die Server-Adresse und der Server-Pfad sind für die Konfiguration eines externen Kalender-Tools (z.B. Google Calendar) erforderlich.

|*Neues Passwort*
|Beim Einrichten des Kalender-Accounts wird ein Passwort benötigt, das von externen Kalender-Tools abgefragt wird. Das Passwort kann jederzeit geändert werden. +
*_Wichtig:_* Das Passwort wird nach dem Speichern nicht mehr angezeigt und kann nicht wiederhergestellt werden. +
Bei Verwendung externer Kalender-Tools muss bei einer Änderung des Passworts dort das Passwort ggf. erneut eingegeben werden.

|*Passwort wiederholen*
|Zuvor eingegebenes neues Passwort durch erneute Eingabe bestätigen.

|*Beschreibung*
|Die Beschreibung wird bei den Informationen bzw. Einstellungen des Kalenders angezeigt.

|*Berechtigung*
|Wählen, welche Benutzer Zugriff auf den Kalender dieses Eigners haben sollen und welche Zugriffsrechte diese Benutzer haben sollen. Um den Kalender sehen zu können, müssen Benutzer mindestens Leserechte haben. +
*Kein Zugriff* = Der Benutzer hat weder Lese- noch Schreibzugriff auf den Kalender dieses Eigners. +
*Lesen* = Der Kalender ist für den Benutzer sichtbar. +
*Schreiben* = Der Benutzer darf Termine im Kalender bearbeiten und löschen.
|====

[#900]
=== Termin erstellen

Gehen Sie wie im Folgenden beschrieben vor, um einen Termin zu erstellen. Abhängig von Ihren Zugriffsrechten, die gemäß <<tabelle-kalender-grundeinstellungen>> eingestellt werden, können Sie auch Termine für andere Benutzer erstellen. Sie können nur Termine für Benutzer erstellen, für die Sie Schreibrechte haben. Benutzer, für die Sie nicht über Schreibrechte verfügen, stehen beim Erstellen eines Termins nicht zur Auswahl.

[.instruction]
Termin erstellen:

. Öffnen Sie das Menü *Start » Kalender*. +
→ *_Tipp:_* Zeigen Sie dazu mit der Maus auf das plentymarkets Logo oben links.
. Wählen Sie den Zeitpunkt des Termins mit einem Klick in das Feld bei der Uhrzeit. +
→ *_Tipp:_* Wählen Sie den Zeitraum des Termins mit einem Klick in das Feld der Startzeit und ziehen Sie den Cursor bis zur Endzeit des Termins.
. Nehmen Sie die Einstellungen im Bereich *Termininformationen* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-termin-erstellen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-termin-erstellen]]
.Termin erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Titel*
|Wird in der Kalenderübersicht angezeigt.

|*Ganztägig*
|Legt fest, dass der Termin den ganzen Tag dauert. Termine werden dann in der Tages- und Wochenansicht in der oberen Leiste angezeigt und der Kalender bleibt übersichtlich.

|*Von / Bis*
|Datum und Uhrzeit sind voreingestellt, können jedoch angepasst werden.

|*Typ*
|Art des Termins aus der Dropdown-Liste wählen.

|*Kalender*
|Wählen, für welchen Eigner der Termin angelegt werden soll.

|*Beschreibung*
|Beschreibung eingeben, z.B. Details zum Termin. Diese Beschreibung wird auch anderen Benutzern mit Zugriffsrechten auf den Kalender in den Termininformationen angezeigt.
|====

[#1000]
=== Termin bearbeiten

Klicken Sie auf einen Termin, um die Termininformationen zu öffnen und diese zu ändern.

[.instruction]
Termin bearbeiten:

. Öffnen Sie das Menü *Start » Kalender*.
. Klicken Sie auf den Termin, den Sie ändern möchten. +
→ Das Fenster *Termininformationen* wird geöffnet.
. Nehmen Sie die Änderungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-termin-erstellen>>.
. *Speichern* Sie die Einstellungen.

[#1100]
=== Termin löschen

Löschen Sie Termine, wenn diese fälschlicherweise erstellt wurden oder die Termine hinfällig geworden sind.

[.instruction]
Termin löschen:

. Öffnen Sie das Menü *Start » Kalender*.
. Klicken Sie auf den Termin, den Sie löschen möchten. +
→ Das Fenster *Termininformationen* wird geöffnet.
. Klicken Sie auf *Löschen*. +
→ Der Termin wird gelöscht und aus der Kalenderübersicht entfernt.

[#1200]
=== Kalender mit externen Kalender-Tools synchronisieren

Über eine link:https://de.wikipedia.org/wiki/CalDAV[CalDAV^]-Schnittstelle synchronisieren Sie Ihren Kalender mit externen Kalender-Tools. Sie können den Kalender z.B. mit dem Mac-Kalender oder iPad-Kalender synchronisieren.

Im Benutzerprofil des Benutzers muss dazu wie im Kapitel <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#700, Variablen Benutzer als Eigner einstellen>> beschrieben im Tab *Eigner* die Option *Kalender* aktiviert sein. Sie benötigen außerdem die Einstellungen des Benutzers, die im Tab *Kalender* des Benutzers gespeichert sind.

Informationen dazu, wie Sie Ihren plentymarkets Kalender mit externen Kalender-Tools synchronisieren, finden Sie in der Dokumentation des externen Kalender-Tools.
