= Aufgaben und Kalender
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Aufgabe, Aufgaben, Ticketaufgabe, Ticketaufgaben, Ticket-Aufgabe, Kalender, Termin, Eigner, Berechtigung, Zugriffsrecht, Leserecht, Schreibrecht, CalDAV, caldav, CALDAV, CalDAV-Schnittstelle, Kalender synchronisieren, externes Kalender-Tool,
:description: Erfahre, wie du Aufgaben und Kalender in plenytmarkets verwaltest.
:position: 50
:url: basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:id: U0UVIS6

Erfahre auf dieser Handbuchseite, wie du <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#100, Aufgaben>> und <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#600, Kalender>> verwaltest.

[#100]
== Aufgaben verwalten

Nutze das Menü *Start » Aufgaben*, um Tätigkeiten für alle Benutzer des Systems zu verwalten, z.B. "Kunde xy anrufen". Du siehst den Fortschritt einer Aufgabe und kannst weitere Abläufe für dein Geschäft planen sowie interne Abläufe verbessern.

Du kannst Aufgaben nicht nur im Menü *Start » Aufgaben* erstellen, sondern auch in einem Ticket im <<crm/ticketsystem-nutzen#4000, Ticketsystem>>. So kannst du z.B. zu einer telefonischen Kundenanfrage direkt eine Aufgabe erstellen. Aufgaben, die du im Menü *CRM » Ticketsystem » Ticket öffnen » Tab: Aufgaben* erstellst, sind mit dem Ticket verknüpft. Diese Verknüpfung wird auch in der Aufgabenübersicht im Menü *Start » Aufgaben* angezeigt.

[#200]
=== Benutzerrechte für Backend-Benutzer vergeben

Nutzer vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs in plentymarkets. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter mit diesem Nutzertyp das Menü *Start » Aufgaben* sehen können, muss ein Nutzer vom Typ *Admin* das im folgenden beschriebene Recht für diesen Benutzer vergeben.

[.instruction]
Sichtbarkeit für Backend-Benutzer einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne den zu bearbeitenden Benutzer.
. Klappe das Menü *Berechtigungen: Start* auf.
. Wähle die Einstellung *Aufgaben*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#300]
=== Aufgabe erstellen

Gehe wie im Folgenden beschrieben vor, um eine Aufgabe zu erstellen. Die Aufgaben-ID wird automatisch vergeben und kann nicht geändert werden.

[.instruction]
Aufgabe erstellen:

. Öffne das Menü *Start » Aufgaben*. +
→ *_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links.
. Klicke auf *Neue Aufgabe* (icon:plus-square[role="green"]). +
→ Das Tab *Neue Aufgabe* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-aufgabe-erstellen>>.
. *Speichere* die Einstellungen.

[[tabelle-aufgabe-erstellen]]
.Aufgabe erstellen
[cols="1,3"]
|====
|Einstellung | Erläuterung

|*Titel*
|Titel für die Aufgabe eingeben.

|*Priorität*
|Priorität wählen. Die Prioritäten reichen von *0 = grauer Stern* bis *5 = 2 gelbe Sterne*.

|*Fortschritt*
|Prozentsatz wählen. Dieser zeigt an, wie weit die Aufgabe fortgeschritten ist. Der Fortschritt muss je nach Fortschreiten der Aufgabe vom Bearbeiter manuell angepasst werden.

|*Markierung*
|Markierung wählen. Die Markierung hilft, Aufgaben später wiederzufinden.

|*Eigner*
|Eigner wählen. Der Eigner ist eine Pflichteinstellung. Der Eigner ist der Verantwortliche für die Aufgabe.

|*Beschreibung*
|Beschreibung der Aufgabe eingeben und Text ggf. formatieren.
|====

[#400]
=== Aufgaben suchen

Beim Öffnen des Menüs *Start » Aufgaben* werden standardmäßig alle Aufgaben mit einem Fortschritt unter 100% des aktuell aktiven Benutzers angezeigt. Wenn du eine Aufgabe über das <<crm/ticketsystem-nutzen#4000, Ticketsystem>> erstellt hast, wird ebenfalls die Ticket-ID sowie der Tickettitel in der Übersicht angezeigt. Mit einem Klick auf die Ticket-ID gelangst du direkt zum Ticket.

Nutze die Suchfilter, um auch bei einer großen Anzahl an Aufgaben den Überblick zu behalten und gezielt Aufgaben zu suchen.

[.instruction]
Aufgaben suchen:

. Öffne das Menü *Start » Aufgaben*. +
→ Alle eigenen unerledigten Aufgaben werden angezeigt, da beim Öffnen des Menüs standardmäßig der Filter für den Fortschritt auf *< 100%* gesetzt und in der Dropdown-Liste *Eigner* der aktive Benutzer vorausgewählt ist.
. Klicke auf icon:undo[role="orange"], um die Filter zu entfernen.
. Wähle die Filter. Beachte dazu die Erläuterungen in <<tabelle-aufgabe-suchen>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Aufgaben, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

[[tabelle-aufgabe-suchen]]
.Aufgabe suchen
[cols="1,3"]
|====
| Filter | Erläuterung

|*Titel/Beschreibung*
|Text eingeben, um nach diesem zu filtern. Es handelt sich um eine Volltextsuche, die den *Titel* und die *Beschreibung* der Aufgaben durchsucht. Mindestens 4 Zeichen für die Suche eingeben.

|*ID*
|ID eingeben, um die Aufgabe mit dieser ID zu suchen. Die Aufgaben-IDs werden automatisch vom System vergeben und sind fortlaufend. Die ID kann nicht geändert werden.

|*Ticket-ID*
|Ticket-ID eingeben, um die Aufgabe(n) zu suchen, die zu diesem Ticket gehören.

|*Fortschritt*
|Operator und Fortschritt wählen. So lassen sich z.B. alle Aufgaben suchen, die bereits zu 60 % oder mehr erledigt sind.

|*Priorität*
|Operator und Priorität wählen. So lassen sich z.B. alle Aufgaben suchen, die Priorität 2 oder höher haben.

|*Datum der Erstellung*
|Operator und Datum wählen. So lassen sich z.B. alle Aufgaben suchen, die vor einem bestimmten Tag angelegt wurden.

|*Eigner*
|Eigner wählen, um nur die Aufgaben dieses Eigners zu suchen.

|*Markierung*
|Markierung wählen, um nur Aufgaben mit dieser Markierung zu suchen.
|====

[#500]
=== Aufgabe bearbeiten

Du kannst Aufgaben jederzeit bearbeiten, um z.B. den Fortschrittsbalken anzupassen oder die Beschreibung zu ergänzen.

[.instruction]
Aufgabe bearbeiten:

. Öffne das Menü *Start » Aufgaben*. +
→ Alle eigenen unerledigten Aufgaben werden angezeigt, da beim Öffnen des Menüs standardmäßig der Filter für den Fortschritt auf *< 100%* gesetzt und in der Dropdown-Liste *Eigner* der aktive Benutzer vorausgewählt ist. +
. Klicke auf icon:undo[role="orange"], um die Filter zu entfernen.
. Wähle die Filter. Beachte dazu die Erläuterungen in <<tabelle-aufgabe-suchen>> im Kapitel <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#400, Aufgabe suchen>>. +
→ Die Aufgaben, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile der Aufgabe. +
→ Die Aufgabe wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-aufgabe-erstellen>> im Kapitel <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#300, Aufgabe erstellen>>.
. *Speichere* die Einstellungen.

[#550]
=== Aufgaben auf dem Dashboard anzeigen

Du kannst deine unerledigten Aufgaben auf dem Dashboard anzeigen lassen. Auf diese Weise siehst du direkt zu Arbeitsbeginn, welche Aufgaben noch erledigt werden müssen.

Setze auf dem Dashboard direkt bei der Aufgabe ein Häkchen, wenn du die Aufgabe erledigt hast. Die Aufgabe wird dann auch im Menü *Start » Aufgaben* aktualisiert und erhält den Status *100%*.

[.instruction]
Aufgaben auf dem Dashboard anzeigen:

. Öffne dein plentymarkets System. +
→ Das Dashboard wird angezeigt.
. Wähle aus der Dropdown-Liste das Element *Meine Aufgaben*. +
→ Der Bereich *Meine Aufgaben* wird dir ab sofort auf dem Dashboard angezeigt, wenn du dein plentymarkets System öffnest.

Mit einem Klick auf *ToDo eingeben* im Bereich *Meine Aufgaben* gelangst du direkt in das Menü *Start » Aufgaben* und kannst dort eine neue <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#300, Aufgabe erstellen>>.

Welche Elemente du außerdem auf dem Dashboard anzeigen kannst, ist auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#, Benutzerkonto personalisieren>> im Kapitel <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#70, Dashboard personalisieren>> beschrieben.

[#600]
== Kalender verwalten

Der Kalender im Menü *Start » Kalender* deines plentymarkets Systems bietet dir die Möglichkeit, Termine zu planen, um deine zeitliche Organisation und die deiner Mitarbeiter zu steuern und interne Abläufe zu verbessern.

Der Kalender enthält die eigenen Termine sowie die Termine der Benutzer, deren Kalender für den angemeldeten Benutzer sichtbar gestellt und im *Filter* aktiviert wurden.

Du kannst zwischen der Anzeige des Tages, der Woche und des Monats wählen. Durch Klick auf die Schaltfläche *Heute* wechselst du zurück zur Ansicht des aktuellen Tages.

Im Filter wird eine Liste der Benutzer angezeigt, für die der angemeldete Benutzer mindestens Leserechte hat. Durch Setzen eines Häkchens werden die Termine dieses Benutzers im Kalender angezeigt. Du kannst die Kalender mehrerer Benutzer gleichzeitig anzeigen.

[#650]
=== Benutzerrechte für Backend-Benutzer vergeben

Nutzer vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs in plentymarkets. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter mit diesem Nutzertyp das Menü *Start » Kalender* sehen können, muss ein Nutzer vom Typ *Admin* das im folgenden beschriebene Recht für diesen Benutzer vergeben.

[.instruction]
Sichtbarkeit für Backend-Benutzer einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne den zu bearbeitenden Benutzer.
. Klappe das Menü *Berechtigungen: Start* auf.
. Wähle die Einstellung *Kalender*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#700]
=== Backend-Benutzer als Eigner einstellen

Für Personen mit dem Zugang *Backend* muss die Kalendernutzung wie im Folgenden beschrieben aktiviert werden. Für Personen mit dem Zugang *REST-API* ist keine Aktivierung des Kalenders möglich.

Die Berechtigung kann im Tab *Eigner* eines Benutzerkontos jederzeit wieder deaktiviert werden.

[.instruction]
Backend-Benutzer als Eigner einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*.
. Öffne das Benutzerkonto mit dem Zugang *Backend*.
. Wechsele in das Tab *Eigner*.
. Aktiviere die Option *Kalender*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das neue Tab *Kalender* ist sichtbar und kann wie im nächsten Kapitel beschrieben eingerichtet werden.

[#800]
=== Grundeinstellungen im Kalender vornehmen und Zugriffsrechte für Benutzer einstellen

Gehe wie im Folgenden beschrieben vor, um Grundeinstellungen im Kalender wie z.B. die Vergabe des Passwort vorzunehmen und die Zugriffsrechte für Benutzer einzustellen. Du kannst zwischen den Einstellungen *Kein Zugriff*, *Lesen* und *Lesen & Schreiben* wählen.

[.instruction]
Grundeinstellungen im Kalender vornehmen und Zugriffsrechte für Benutzer einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*.
. Öffne den Benutzer.
. Öffne das Tab *Kalender*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-kalender-grundeinstellungen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-kalender-grundeinstellungen]]
.Grundeinstellungen im Kalender vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Serveradresse*; +
*Serverpfad*; +
*Port*
|Wird automatisch vom System gespeichert. +
Die Server-Adresse und der Server-Pfad sind für die Konfiguration eines externen Kalender-Tools (z.B. Google Calendar) erforderlich.

|*Neues Passwort*
|Beim Einrichten des Kalender-Accounts wird ein Passwort benötigt, das von externen Kalender-Tools abgefragt wird. Das Passwort kann jederzeit geändert werden. +
*_Wichtig:_* Das Passwort wird nach dem Speichern nicht mehr angezeigt und kann nicht wiederhergestellt werden. +
Bei Verwendung externer Kalender-Tools muss bei einer Änderung des Passworts dort das Passwort ggf. erneut eingegeben werden.

|*Passwort wiederholen*
|Zuvor eingegebenes neues Passwort durch erneute Eingabe bestätigen.

|*Beschreibung*
|Die Beschreibung wird bei den Informationen bzw. Einstellungen des Kalenders angezeigt.

|*Berechtigung*
|Wählen, welche Benutzer Zugriff auf den Kalender dieses Eigners haben sollen und welche Zugriffsrechte diese Benutzer haben sollen. Um den Kalender sehen zu können, müssen Benutzer mindestens Leserechte haben. +
*Kein Zugriff* = Der Benutzer hat weder Lese- noch Schreibzugriff auf den Kalender dieses Eigners. +
*Lesen* = Der Kalender ist für den Benutzer sichtbar. +
*Schreiben* = Der Benutzer darf Termine im Kalender bearbeiten und löschen.
|====

[#900]
=== Termin erstellen

Gehe wie im Folgenden beschrieben vor, um einen Termin zu erstellen. Abhängig von deinen Zugriffsrechten, die gemäß <<tabelle-kalender-grundeinstellungen>> eingestellt werden, kannst du auch Termine für andere Benutzer erstellen. Du kannst nur Termine für Benutzer erstellen, für die du Schreibrechte hast. Benutzer, für die du nicht über Schreibrechte verfügst, stehen beim Erstellen eines Termins nicht zur Auswahl.

[.instruction]
Termin erstellen:

. Öffne das Menü *Start » Kalender*. +
→ *_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links.
. Wähle den Zeitpunkt des Termins mit einem Klick in das Feld bei der Uhrzeit. +
→ *_Tipp:_* Wähle den Zeitraum des Termins mit einem Klick in das Feld der Startzeit und ziehe den Cursor bis zur Endzeit des Termins.
. Nimm die Einstellungen im Bereich *Termininformationen* vor. Beachte dazu die Erläuterungen in <<tabelle-termin-erstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-termin-erstellen]]
.Termin erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Titel*
|Wird in der Kalenderübersicht angezeigt.

|*Ganztägig*
|Legt fest, dass der Termin den ganzen Tag dauert. Termine werden dann in der Tages- und Wochenansicht in der oberen Leiste angezeigt und der Kalender bleibt übersichtlich.

|*Von / Bis*
|Datum und Uhrzeit sind voreingestellt, können jedoch angepasst werden.

|*Typ*
|Art des Termins aus der Dropdown-Liste wählen.

|*Kalender*
|Wählen, für welchen Eigner der Termin angelegt werden soll.

|*Beschreibung*
|Beschreibung eingeben, z.B. Details zum Termin. Diese Beschreibung wird auch anderen Benutzern mit Zugriffsrechten auf den Kalender in den Termininformationen angezeigt.
|====

[#1000]
=== Termin bearbeiten

Klicke auf einen Termin, um die Termininformationen zu öffnen und diese zu ändern.

[.instruction]
Termin bearbeiten:

. Öffne das Menü *Start » Kalender*.
. Klicke auf den Termin, den du ändern möchtest. +
→ Das Fenster *Termininformationen* wird geöffnet.
. Nimm die Änderungen vor. Beachte dazu die Erläuterungen in <<tabelle-termin-erstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#1100]
=== Termin löschen

Lösche Termine, wenn diese fälschlicherweise erstellt wurden oder die Termine hinfällig geworden sind.

[.instruction]
Termin löschen:

. Öffne das Menü *Start » Kalender*.
. Klicke auf den Termin, den du löschen möchtest. +
→ Das Fenster *Termininformationen* wird geöffnet.
. Klicke auf *Löschen* (icon:minus-square[role="red"]). +
→ Der Termin wird gelöscht und aus der Kalenderübersicht entfernt.

[#1200]
=== Kalender mit externen Kalender-Tools synchronisieren

Über eine link:https://de.wikipedia.org/wiki/CalDAV[CalDAV^]-Schnittstelle synchronisierst du deinen Kalender mit externen Kalender-Tools. Du kannst den Kalender z.B. mit dem Mac-Kalender oder iPad-Kalender synchronisieren.

Im Benutzerprofil des Benutzers muss dazu wie im Kapitel <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#700, Backend-Benutzer als Eigner einstellen>> beschrieben im Tab *Eigner* die Option *Kalender* aktiviert sein. Du benötigst außerdem die Einstellungen des Benutzers, die im Tab *Kalender* des Benutzers gespeichert sind.

Informationen darüber, wie du deinen plentymarkets Kalender mit externen Kalender-Tools synchronisierst, findest du in der Dokumentation des externen Kalender-Tools.
