= Backend-URLs
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Backend, Zugriff auf Backend, URL, key, Key, UI-Action, ui action, uiaction, Parameter, Terra, Variable, abgesicherter modus
:description: Erfahren Sie, wie Sie anhand von URLs in bestimmte Backend-Bereiche gelangen.
:position: 20

[#10]
== Backend-Bereiche mit URLs direkt aufrufen

Einige Bereiche des Backends können mithilfe von UI-Aktionen direkt aufgerufen werden. Das spart Zeit, da eine Vielzahl von Klicks im Backend mit einem einzigen Seitenaufruf ersetzt wird. In diesem Abschnitt sind die Variablen und Parameter aufgeführt, die hierfür verwendet werden können.

[IMPORTANT]
.Hinweis
====
Sie müssen eingeloggt sein, um einen Backend-Bereich mit einer URL aufrufen zu können. Beachten Sie außerdem Groß- und Kleinschreibung in der URL.
====

== Einen Backend-Bereich mit einer URL aufrufen

. Geben Sie als ersten Teil des Pfads https://plentymarkets-cloud-de.com ein.
. Tragen Sie nach einem */* Ihre plenty-ID ein.
. Fahren Sie mit der Abfragezeichenfolge fort. Diese beginnt mit einem *?*.
. Fügen Sie die UI-Aktion mit *uiAction=* hinzu.
. Tragen Sie den Schlüssel für die UI-Aktion und die Parameter mit den entsprechenden IDs ein. Beachten Sie die Erläuterungen in <<tabelle-keys-ui-actions-parameter>>.
. Rufen Sie die URL mit allen Informationen auf, um in den gewünschten Backend-Bereich zu gelangen.

[TIP]
.Beispiel
====
Um die Varianten-Detailansicht zu öffnen, muss sich der Pfad aus den folgenden Parametern zusammensetzen: +
plentymarkets-cloud-de.com/1234?uiAction=ITEM_VARIATION_DETAIL&itemId=102&variationId=1111
====

[[tabelle-keys-ui-actions-parameter]]
.Keys für UI-Actions und Parameter
[cols="1,2"]
|====
|Schlüssel |Erläuterung

|*ITEM_DETAIL* +
 *itemId*
|Öffnet die Artikeldetailansicht für die angegebene Artikel-ID (itemId ist Pflichtparameter).

|*ITEM_VARIATION_DETAIL* +
 *itemId* +
 *variationId*
|Öffnet die Variantendetailansicht für die angegebene Artikel-ID und Varianten-ID (itemId und variationId sind Pflichtparameter).

|*ORDER_DETAIL* +
 *orderId*
|Öffnet die Auftragsdetailansicht für die angegebene Auftrags-ID (orderId ist Pflichtparameter).

|*REORDER_DETAIL* +
 *reorderId* +
 *itemId* +
 *reorderItemId*
|Öffnet die Nachbestellungsdetailansicht für die angegebene Nachbestellungs-ID, die Artikel-ID oder die Artikel-ID einer Nachbestellung (Hier darf nur einer der drei Parameter angegeben werden).

|*TICKET_DETAIL_VIEW* +
 *ticketId*
|Öffnet die Ticketdetailansicht für die angegebene Ticket-ID (ticketId ist Pflichtparameter).

|*CUSTOMER_DETAIL* +
 *customerID*
|Öffnet die Kundendetailansicht für die angegebene Kunden-ID (customerId ist Pflichtparameter).
|====

[#20]
== Abgesicherter Modus

Im abgesicherten Modus können Sie das Backend mit deaktivierten Plugins aufrufen. Dies kann notwendig sein, wenn Sie nach der Installation oder dem Aktualisieren eines Plugins beim regulären Einloggen eine Fehlermeldung erhalten. Im abgesicherten Modus können Sie das Plugin auf *Inaktiv* setzen.

Wenn Sie sich im abgesicherten Modus einloggen möchten, verwenden Sie die URL https://plentymarkets-cloud-de.com/?safemode=1.