= Boards verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Board, Boards
:description: Erfahre auf dieser Handbuchseite, wie du Boards in plentymarkets verwaltest.
:position: 40
:url: basics/arbeiten-mit-plentymarkets/boards

Durch das Verwenden von Boards kannst du den Workflow eines Projekts oder Arbeitsprozesses innerhalb deines Unternehmens visualisieren. Gängige Boards bestehen aus 3 Spalten: _Zu tun_, _In Arbeit_ und _Erledigt_. Du entscheidest jedoch selbst, wie du das Board gestaltest und wieviele Spalten du verwendest.

[#5]
== Sichtbarkeit für Backend-Benutzer einstellen

Damit für Benutzer mit dem Zugang *Backend* das Menü *Start » Boards* sichtbar ist und der Benutzer mit den Boards arbeiten kann, muss die Menü-Sichtbarkeit im Benutzerkonto freigeschaltet werden.

[.instruction]
Sichtbarkeit für Backend-Benutzer einstellen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Übersicht wird geöffnet.
. *_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das Konto, für das du die Sichtbarkeit des Menüs und die Berechtigungen aktivieren möchtest. +
→ Die Ansicht *Rechte* wird geöffnet.
. Klappe im Bereich *Menü-Sichtbarkeiten* die Option *Start* auf.
. Aktiviere die Option *Boards*. +
→ *_Hinweis:_* Im Bereich *Berechtigungen* wird die Option unter *Start > Boards* automatisch mit aktiviert.
. *Speichere* die Einstellungen. +
→ Das Menü *Start » Boards* ist für den Backend-Benutzer sichtbar und bearbeitbar.

[#10]
== Board erstellen

Gehe wie im Folgenden beschrieben vor, um ein Board zu erstellen.

[.instruction]
Board erstellen:

. Öffne das Menü *Start » Boards*. +
→ *_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links.
. Das Tab *Boards* wird in einem neuen Tab geöffnet.
. Klicke auf *Neues Board erstellen*. +
→ Das Fenster *Neues Board erstellen* wird geöffnet.
. Gib den Namen des Boards ein.
. *Speichere* die Einstellungen. +
→ Das Board wird erstellt und der Liste hinzugefügt.

[#20]
== Spalte hinzufügen

Gehe wie im Folgenden beschrieben vor, um Spalten zu dem Board hinzuzufügen. Du kannst beliebig viele Spalten hinzufügen.

[.instruction]
Spalte hinzufügen:

. Öffne das Menü *Start » Boards*. +
→ *_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links.
. Das Tab *Boards* wird in einem neuen Tab geöffnet.
. Klicke auf das Board, das du bearbeiten möchtest.
. Klicke auf *Neue Spalte hinzufügen*. +
→ Die Spalte wird auf der linken Seite hinzugefügt.
. Gib den Namen für die Spalte ein.
. Füge weitere Spalten analog hinzu, bis du die gewünschte Anzahl an Spalten für das Board hast. +
→ *_Tipp:_* Du kannst die Position der Spalten auch verschieben.

[#30]
== Karte hinzufügen

Gehe wie im Folgenden beschrieben vor, um Karten zu dem Board hinzuzufügen. Du kannst beliebig viele Karten hinzufügen.

[.instruction]
Karte hinzufügen:

. Öffne das Menü *Start » Boards*. +
→ *_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links.
. Das Tab *Boards* wird in einem neuen Tab geöffnet.
. Klicke auf das Board, das du bearbeiten möchtest.
. Klicke in der Spalte, in der du eine neue Karte hinzufügen möchtest, auf *Neue Karte hinzufügen*.
. Gib den Namen für die Karte ein.
. Klicke auf *Neue Karte speichern*.
. Füge weitere Karten analog hinzu, bis du die gewünschte Anzahl an Karten für das Board hinzugefügt hast.

[#40]
== Karte bearbeiten

Du kannst die Karten auf dem Board jederzeit bearbeiten. Verknüpfe die Karte z.B. mit einem Kontakt, einem Auftrag und einem Ticket oder füge Eigner und Tags hinzu. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Karte bearbeiten:

. Öffne das Menü *Start » Boards*. +
→ *_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links.
. Das Tab *Boards* wird in einem neuen Tab geöffnet.
. Klicke auf das Board, das du bearbeiten möchtest.
. Klicke in der Karte, die du bearbeiten möchtest, auf den Pfeil rechts. +
→ Das Einstellungsmenü öffnet sich.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-boards-karte-bearbeiten>>.

[[tabelle-boards-karte-bearbeiten]]
.Einstellungen im Menü *Start » Boards*
[cols="1,3"]
|====
|Einstellung| Erläuterung

|*Karte bearbeiten*
|Text zur Karte eingeben und ggf. formatieren.

|*Karte löschen*
|Mit einem Klick auf *Karte löschen* die Karte löschen.

|*Kontakt verknüpfen*
|Kontakt-ID eingeben, um die Karte mit dem Kontakt zu verknüpfen. +
*_Hinweis:_* Wenn die Karte mit dem Kontakt verknüpft ist, wird ein Symbol auf der Karte angezeigt. Über dieses Symbol den Kontakt direkt im Menü *CRM » Kontakte* öffnen oder die Verknüpfung zum Kontakt löschen.

|*Ticket verknüpfen*
|Ticket-ID eingeben, um die Karte mit dem Ticket zu verknüpfen. +
*_Hinweis:_* Wenn die Karte mit dem Ticket verknüpft ist, wird ein Symbol auf der Karte angezeigt. Über dieses Symbol das Ticket direkt im Menü *CRM » Ticketsystem* öffnen oder die Verknüpfung zum Ticket löschen.

|*Auftrag verknüpfen*
|Auftrags-ID eingeben, um die Karte mit dem Auftrag zu verknüpfen. +
*_Hinweis:_* Wenn die Karte mit dem Auftrag verknüpft ist, wird ein Symbol auf der Karte angezeigt. Über dieses Symbol den Auftrag direkt im Menü *Aufträge » Aufträge bearbeiten* öffnen oder die Verknüpfung zum Auftrag löschen.

|*Benutzer hinzufügen*
|Eigner aus der Liste wählen, um diesen Eigner der Karte hinzuzufügen. +
Wenn der Eigner der Karte hinzugefügt ist, wird ein Symbol mit den Initialen bzw. dem Anfangsbuchstaben des Eigners auf der Karte angezeigt. +
*_Tipp:_* Um den Benutzer zu entfernen, den Mauszeiger über das Symbol bewegen und auf *Benutzer entfernen* klicken.

|*Tag hinzufügen*
|Tag aus der Liste wählen, um dieses Tag der Karte hinzuzufügen. +
*_Wichtig:_* In der Liste stehen nur Tags zur Verfügung, die zuvor im Menü *System » Systemeinstellungen » Einstellungen » Tags* erstellt wurden. Weitere Informationen finden Sie auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/tags#, Tags>>.

|====

[#50]
== Board bearbeiten

Beim Öffnen des Menüs *Start » Boards* siehst du auf jedem erstellten Board in der Liste die Anzahl der Karten und Spalten, den Namen des Boards sowie den Zeitraum der letzten Änderung. Klicke auf *Board umbenennen*, um einen neuen Namen für das Board einzugeben. Klicke auf *Board löschen*, um das Board zu löschen.

Um das Board zu bearbeiten, klicke auf den Namen des Boards. Dort kannst du neue Spalten und Karten hinzufügen und die Karten bearbeiten. Beachte dazu die Erläuterungen in <<tabelle-boards-karte-bearbeiten>>.

[#60]
== Ereignisaktionen einrichten

Im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Ereignisse* erstellst du Ereignisaktionen, die z.B. die Karten auf deinen Boards automatisch in eine von dir festgelegte Spalte verschieben, sobald ein bestimmtes Ereignis eintritt. Auch das Verschieben von Karten auf ein anderes Board ist möglich. Außerdem kannst du für neu erstellte Karten einen Präfix wählen oder Karten löschen, sobald ein bestimmtes Ereignis eintritt.

Weitere Informationen zum Erstellen von Ereignisaktionen findest du im Kapitel <<crm/ticketsystem-nutzen#2900, E-Mail-Vorlage automatisch versenden>> auf der Handbuchseite <<crm/ticketsystem-nutzen#, Ticketsystem nutzen>>.
