= Boards verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Board, Boards
:description: Erfahren Sie auf dieser Handbuchseite, wie Sie Boards in plentymarkets verwalten.
:position: 120

Durch das Verwenden von Boards können Sie den Workflow eines Projekts oder Arbeitsprozesses innerhalb Ihres Unternehmens visualisieren. Die gängigsten Boards bestehen aus drei Spalten: _Zu tun_, _In Arbeit_ und _Erledigt_. Sie entscheiden jedoch selbst, wie Sie das Board gestalten und wieviele Spalten Sie verwenden.

[#10]
== Board erstellen

TEXT

[.instruction]
Board erstellen:

. Öffnen Sie das Menü *Start » Boards*. +
→ *_Tipp:_* Zeigen Sie dazu mit der Maus auf das plentymarkets Logo oben links.
. Das Tab *Boards* wird in einem neuen Tab geöffnet.
. Klicken Sie auf *Neues Board erstellen*. +
→ Ein Fenster wird geöffnet.
. Geben Sie den Namen des Boards ein.
. *Speichern* Sie die Einstellungen. +
→ Das Board wird erstellt.


[#20]
== Spalte hinzufügen

[#30]
== Karte hinzufügen

[#40]
== Board bearbeiten

In der Board-Übersicht

////
TODO
Ereignisaktionen - Denise
Tags - Auf der Tag-Seite einen Link einfügen, wenn die Seite live ist
Wenn Karte erstellt ist: Optionen beschreiben
