= Boards verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Board, Boards
:description: Erfahren Sie auf dieser Handbuchseite, wie Sie Boards in plentymarkets verwalten.
:position: 120

Durch das Verwenden von Boards können Sie den Workflow eines Projekts oder Arbeitsprozesses innerhalb Ihres Unternehmens visualisieren. Gängige Boards bestehen aus drei Spalten: _Zu tun_, _In Arbeit_ und _Erledigt_. Sie entscheiden jedoch selbst, wie Sie das Board gestalten und wieviele Spalten Sie verwenden.

[#10]
== Board erstellen

Gehen Sie wie im Folgenden beschrieben vor, um ein Board zu erstellen.

[.instruction]
Board erstellen:

. Öffnen Sie das Menü *Start » Boards*. +
→ *_Tipp:_* Zeigen Sie dazu mit der Maus auf das plentymarkets Logo oben links.
. Das Tab *Boards* wird in einem neuen Tab geöffnet.
. Klicken Sie auf *Neues Board erstellen*. +
→ Das Fenster *Neues Board erstellen* wird geöffnet.
. Geben Sie den Namen des Boards ein.
. *Speichern* Sie die Einstellungen. +
→ Das Board wird erstellt und der Liste hinzugefügt.


[#20]
== Spalte hinzufügen

Gehen Sie wie im Folgenden beschrieben vor, um Spalten zu dem Board hinzuzufügen. Sie können beliebig viele Spalten hinzufügen.

[.instruction]
Spalte hinzufügen:

. Öffnen Sie das Menü *Start » Boards*. +
→ *_Tipp:_* Zeigen Sie dazu mit der Maus auf das plentymarkets Logo oben links.
. Das Tab *Boards* wird in einem neuen Tab geöffnet.
. Klicken Sie auf das Board, das Sie bearbeiten möchten.
. Klicken Sie auf *Neue Spalte hinzufügen*. +
→ Die Spalte wird auf der linken Seite hinzugefügt.
. Geben Sie den Namen für die Spalte ein.
. Fügen Sie weitere Spalten analog hinzu, bis Sie die gewünschte Anzahl an Spalten für das Board haben. +
→ *_Tipp:_* Sie können die Position der Spalten auch verschieben.

[#30]
== Karte hinzufügen


Gehen Sie wie im Folgenden beschrieben vor, um Karten zu dem Board hinzuzufügen. Sie können beliebig viele Karten hinzufügen.

[.instruction]
Karte hinzufügen:

. Öffnen Sie das Menü *Start » Boards*. +
→ *_Tipp:_* Zeigen Sie dazu mit der Maus auf das plentymarkets Logo oben links.
. Das Tab *Boards* wird in einem neuen Tab geöffnet.
. Klicken Sie auf das Board, das Sie bearbeiten möchten.
. Klicken Sie in der Spalte, in der Sie eine neue Karte hinzufügen möchten, auf *Neue Karte hinzufügen*.
. Geben Sie den Namen für die Karte ein.
. Klicken Sie auf *Neue Karte speichern*.
. Fügen Sie weitere Karten analog hinzu, bis Sie die gewünschte Anzahl an Karten für das Board hinzugefügt haben.

[#40]
== Karte bearbeiten

Sie können die Karten auf dem Board jederzeit bearbeiten. Verknüpfen Sie die Karte z.B. mit einem Kontakt, einem Auftrag und einem Ticket oder fügen Sie Eigner und Tags hinzu. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Karte bearbeiten:

. Öffnen Sie das Menü *Start » Boards*. +
→ *_Tipp:_* Zeigen Sie dazu mit der Maus auf das plentymarkets Logo oben links.
. Das Tab *Boards* wird in einem neuen Tab geöffnet.
. Klicken Sie auf das Board, das Sie bearbeiten möchten.
. Klicken Sie in der Karte, die Sie bearbeiten möchten, auf den Pfeil rechts. +
→ Das Einstellungsmenü öffnet sich.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-boards-karte-bearbeiten>>.

[[tabelle-boards-karte-bearbeiten]]
.Einstellungen im Start » Boards
[cols="1,3"]
|====
|Einstellung| Erläuterung

|*Karte bearbeiten*
|Text zur Karte eingeben und ggf. formatieren.

|*Karte löschen*
|Mit einem Klick auf *Karte löschen* die Karte löschen.

|*Kontakt verknüpfen*
|Kontakt-ID eingeben, um die Karte mit dem Kontakt zu verknüpfen. +
*_Hinweis:_* Nach der Verknüpfung wird ein Symbol auf der Karte angezeigt. Über dieses Symbol den Kontakt direkt im Menü *CRM » Kontakte* öffnen oder die Verknüpfung zum Kontakt löschen.

|*Ticket verknüpfen*
|Ticket-ID eingeben, um die Karte mit dem Ticket zu verknüpfen. +
*_Hinweis:_* Nach der Verknüpfung wird ein Symbol auf der Karte angezeigt. Über dieses Symbol das Ticket direkt im Menü *CRM » Ticketsystem* öffnen oder die Verknüpfung zum Ticket löschen.

|*Auftrag verknüpfen*
|Auftrags-ID eingeben, um die Karte mit dem Auftrag zu verknüpfen. +
*_Hinweis:_* Nach der Verknüpfung wird ein Symbol auf der Karte angezeigt. Über dieses Symbol den Auftrag direkt im Menü *Aufträge » Aufträge bearbeiten* öffnen oder die Verknüpfung zum Auftrag löschen.

|*Benutzer hinzufügen*
|Eigner aus der Liste wählen, um diesen Eigner der Karte hinzuzufügen. +
Nach dem Hinzufügen wird ein Symbol mit den Initialen bzw. dem Anfangsbuchstaben des Eigners auf der Karte angezeigt. +
*_Tipp:_* Um den Benutzer zu entfernen, den Mauszeiger über das Symbol bewegen und auf *Benutzer entfernen* klicken.

|*Tag hinzufügen*
|Tag aus der Liste wählen, um dieses Tag der Karte hinzuzufügen. +
*_Wichtig:_* In der Liste stehen nur Tags zur Verfügung, die zuvor im Menü *System » Einstellungen » Tags* erstellt wurden. Weitere Informationen finden Sie auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/tags#, Tags>>.

|====

[#50]
== Board bearbeiten

Beim Öffnen des Menüs *Start » Boards* sehen Sie auf jedem erstellten Board in der Liste die Anzahl der Karten und Spalten, den Namen des Boards sowie den Zeitraum der letzten Änderung. Klicken Sie auf *Board umbenennen*, um einen neuen Namen für das Board einzugeben. Klicken Sie auf *Board löschen*, um das Board zu löschen.

Um das Board zu bearbeiten, klicken Sie auf den Namen des Boards. Dort können Sie neue Spalten und Karten hinzufügen und die Karten bearbeiten. Beachten Sie dazu die Erläuterungen in <<tabelle-boards-karte-bearbeiten>>.

[#60]
== Ereignisaktionen einrichten

Im Menü *System » CRM » Ticketsystem » Ereignisse* erstellen Sie Ereignisaktionen, die z.B. die Karten auf Ihren Boards automatisch in eine von Ihnen festgelegte Spalte verschiebt, sobald ein bestimmtes Ereignis eintritt. Auch das Verschieben von Karten auf ein anderes Board ist möglich. Außerdem können Sie für neu erstellte Karten einen Präfix wählen oder Karten löschen, sobald ein bestimmtes Ereignis eintritt.

Weitere Informationen zum Erstellen von Ereignisaktionen finden Sie im Kapitel <<crm/ticketsystem-nutzen#2900, E-Mail-Vorlage automatisch versenden>> auf der Handbuchseite <<crm/ticketsystem-nutzen#, Ticketsystem nutzen>>.
