= Datenbereinigung durchführen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Bereinigung, Daten-Bereinigung, Datenbereinigung, automatisch löschen, Adressen löschen, ungenutzte Adressen löschen
:description: Erfahren Sie, wie Sie in plentymarkets automatisch Daten bereinigen.
:position: 55


Auf dieser Handbuchseite wird beschrieben, wie Sie im Menü *System » Einstellungen » Daten » Bereinigung* bestimmte Datensätze nach Ablauf eines Zeitraums, den Sie selbst festlegen, automatisch löschen.


== Sichtbarkeit des Menüs für variablen Benutzer einstellen

Damit für Benutzer mit der Benutzerklasse *Variabel* das Menü *System » Einstellungen » Daten » Bereinigung* sichtbar ist, muss dieses Menü im Benutzerkonto freigeschaltet werden.

Außerdem müssen Berechtigungen im Bereich *REST-API* aktiviert werden.

[.instruction]
Sichtbarkeit des Menüs für variablen Benutzer einstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den Benutzer mit der Benutzerklasse *Variabel*, für den Sie die Sichtbarkeit des Menüs aktivieren möchten.
. Wechseln Sie in das Tab *Berechtigung*.
. Wechseln Sie in das Tab *Menü*.
. Klappen Sie den Bereich *Einstellungen » Grundeinstellungen » Daten* auf.
. Aktivieren Sie die Option *Bereinigung*.
. Wechseln Sie in das Tab *REST-API*.
. Klappen Sie den Bereich *Datenbereinigung* auf.
. Aktivieren Sie die Optionen *Konfiguration anzeigen* und *Konfiguration speichern*.
. *Speichern* Sie die Einstellungen.

== Löschwerte eingeben

Damit Datensätze nach Ablauf eines bestimmten Zeitraums automatisch aus Ihrem plentymarkets System gelöscht werden, müssen Sie Werte für diesen Zeitraum eingeben. Gehen Sie dazu wie im Folgenden beschrieben vor.

[NOTE]
.Weitere Funktionen in diesem Menü werden sukzessive ergänzt
====
Aktuell können Sie unzugeordnete Adressen automatisch löschen. Sukzessive werden weitere Bereiche in diesem Menü ergänzt.
====

[.instruction]
Löschwerte eingeben:

. Öffnen Sie das Menü *System » Einstellungen » Daten » Bereinigung*.
. Geben Sie im Eingabefeld einen Wert ein. Beachten Sie die Erläuterungen in <<tabelle-einstellungen-daten-bereinigung>>.
. Aktivieren Sie den Toggle-Button.
. *Speichern* Sie die Einstellungen.


[[tabelle-einstellungen-daten-bereinigung]]
.Einstellungen im System » Einstellungen » Daten » Bereinigung
[cols="1,3"]
|====
|Einstellung| Erläuterung

|Löschung ungenutzter Adressen (nach Tagen)
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden ungenutzte Adressen automatisch aus dem plentymarkets System gelöscht. Ungenutzte Adressen sind Adressen, die nicht mit einem Kontakt, einem Auftrag, einem POS oder einem Lager verknüpft sind. +
|Löschung ungenutzter Kontakte (nach Tagen)
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden ungenutzte Kontakte automatisch aus dem plentymarkets System gelöscht. Ungenutzte Kontakte sind Kontakte, die nicht mit Wareneingängen, Tickets oder Aufträgen verknüpft sind. +
|Löschung von Aufträgen (nach Tagen)
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden Aufträge automatisch aus dem plentymarkets System gelöscht. Aufträge werden mit den dazugehörigen Dokumenten gelöscht. +
|Löschung der Historie (nach Tagen)
|Zahl in Tagen eingeben. Nach diesem Zeitraum werde Einträge in der link:https://knowledge.plentymarkets.com/de/basics/dsgvo#_%C3%A4nderungshistorie_f%C3%BCr_kontaktdaten[Historie^] automatisch aus dem plentymarkets System gelöscht. In der Historie werden Änderungen an Daten geloggt. +
|Löschung von IP-Adressen am Auftrag (nach Tagen)
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden am Auftrag gespeicherte IP-Adressen automatisch aus dem plentymarkets System gelöscht. +
|====

[IMPORTANT]
.Toggle-Button aktivieren
====
Daten werden nur gelöscht, wenn der Toggle-Button aktiviert und die Einstellung gespeichert wurde. +
Wenn die Daten nicht mehr nach Ablauf des eingegebenen Wertes gelöscht werden sollen, Toggle-Button deaktivieren und Einstellungen erneut speichern.
====


[NOTE]
.Anzahl der zu löschenden Datensätzen
====
Aktuell werden bis zu 5000 Datensätze pro Tag gelöscht. plentymarkets wird dieses Verhalten beobachten und ggf. ebenfalls auf einen höheren Wert anpassen.
====

== Tickets automatisch löschen

Löschen Sie Tickets automatisch aus Ihrem Ticketsystem. Diese Einstellung nehmen Sie nicht im Menü *System » Einstellungen » Daten » Bereinigung* vor, sondern über den Aktionsmanager im Ticketsystem im Menü *System » CRM » Ticketsystem » Aktionen*.

Weitere Informationen über das Ticketsystem sowie ein Beispielszenario zum Löschen von Tickets finden Sie auf der Handbuchseite <<crm/ticketsystem-nutzen#3000, Ticketsystem nutzen>>.

== Log einsehen

Alle Änderungen, die im Menü *System » Einstellungen » Daten » Bereinigung* vorgenommen werden, werden im Menü *Daten » Log* für 30 Tage gespeichert. So können Sie einsehen, welcher Benutzer wann den alten Wert in den neuen Wert geändert hat.

Weitere Informationen zum Log finden Sie auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/datenlog#, Datenlog>>.
