= Editoren
:lang: de
include::{includedir}/_header.adoc[]
:position: 90



== Bereiche aktivieren

In der Standardeinstellung sind in allen Bereichen die Editoren **Editor**, **Syntax-Editor** und **Textfeld** aktiviert. Diese können für jeden Bereich deaktiviert werden. Im Menü **System » Einstellungen » Editoren » Tab: Bereiche** wählen Sie, welche Editoren im Dropdown-Menü des jeweiligen Bereichs angezeigt werden sollen.



== CSS des Editors

In der Standardeinstellung wird für den **<<omni-channel/online-shop/cms#webdesign-werkzeuge-editor, Editor>>** das CSS des Bereichs **CSSContent** verwendet. Wenn dort z.B. ein Hintergrundbild verwendet wird und das bei der Bearbeitung im Editor stört, können Sie das CSS in diesem Menü anpassen. Alternativ steht ein weißer Hintergrund zur Verfügung oder die Möglichkeit, ein eigenes CSS zu erstellen, in dem Sie auch die Formatierung weiterer Inhalte, z.B. Schriften, individuell festlegen können.

== Konfiguration



Die folgende Tabelle erläutert die Optionen im Menü **System » Einstellungen » Editoren**:

[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Wie im Webshop**
|Das <<omni-channel/online-shop/cms#webdesign-webdesign-bearbeiten-css, **Webshop-CSS**>> wird in den Editor geladen. Dieses CSS befindet sich im Menü **CMS » Webdesign » Layout » CSS » CSSContent**.

|**Standard**
|Ein einfaches Standard-CSS wird in den Editor geladen. Die Hintergrundfarbe ist weiß.

|**Benutzerdefiniert**
|Das einfache Standard-CSS wird in einem Bearbeitungsfenster angezeigt und kann mit dem <<omni-channel/online-shop/cms#webdesign-werkzeuge-syntax-editor, **Syntax-Editor**>> angepasst werden. Bei Klick auf **Zurücksetzen** wird das CSS wieder auf das Standard-CSS zurückgesetzt.
|====

__Tab 1: Menü **Editoren**; Konfiguration__
