= Tags verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Tag, Tags, Tag erstellen
:description: Erfahre auf dieser Handbuchseite, wie du Tags in plentymarkets verwaltest.
:position: 60
:url: basics/arbeiten-mit-plentymarkets/tags

Tags sind Schlagworte, mit denen Datensätze in plentymarkets markiert werden. Tags werden zentral im Menü *System » Systemeinstellungen » Einstellungen » Tags* erstellt und verwaltet. Diese Tags können mit Datensätzen in den folgenden Bereichen von plentymarkets verknüpft werden:

* Board
* Kategorie
* Ticket
* Kontakt
* Variante
* Auftrag


[#50]
== Sichtbarkeit für Backend-Benutzer einstellen

Damit für Benutzer mit dem Zugang *Backend* das Menü *System » Systemeinstellungen » Einstellungen » Tags* sichtbar ist, muss die Menü-Sichtbarkeit sowie weitere REST-Berechtigungen im Benutzerkonto freigeschaltet werden.

[.instruction]
Sichtbarkeit für Backend-Benutzer einstellen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Übersicht wird geöffnet.
. *_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das Konto, für das du die Sichtbarkeit des Menüs und die Berechtigungen aktivieren möchtest. +
→ Die Ansicht *Rechte* wird geöffnet.
. Klappe im Bereich *Menü-Sichtbarkeiten* die Option *System > Systemeinstellungen > Einstellungen* auf.
. Aktiviere die Option *Tag*. +
→ *_Hinweis:_* Im Bereich *Berechtigungen* wird die Option unter *Tag > Tag anzeigen* automatisch mit aktiviert.
. *Speichere* die Einstellungen.

[#100]
== Tag erstellen

Gehe wie im Folgenden beschrieben vor, um ein Tag zu erstellen.

[.instruction]
Tag erstellen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Tags*.
. Klicke auf *Neues Tag erstellen*. +
→ Rechts wird ein Fenster geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-tag-einstellungen>>.
. *Speichere* die Einstellungen. +
→ Das Tag wird erstellt und der Liste hinzugefügt.

[[tabelle-tag-einstellungen]]
.Tag erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name DE*
|Namen für den Tag eingeben. +
*_Tipp:_* Tag-Namen können Leerzeichen enthalten, um zum Beispiel ein Tag zu erstellen, das aus zwei Worten besteht.

|*Farbe*
|*_Optional:_* Farbe für das Tag als Hexadezimalwert eingeben. Für die 16 Grundfarben kann statt des Hexadezimalwerts die englische Bezeichnung der Farbe eingegeben werden (black, red, silver, white etc.) +
*_Tipp:_* Auf das Quadrat rechts klicken, um den Farbwähler zu öffnen.

|*Bereich*
|Bereiche wählen, in denen das Tag verfügbar sein soll. +
*Board* = Tag kann mit Aufgabenkarten auf Boards des Menüs *Start » Boards* verknüpft werden. +
*Kategorie* = Tag kann mit Kategorien verknüpft werden. +
*Ticket* = Tag kann mit Tickets des Ticketsystems verknüpft werden. +
*Kontakt* = Tag kann mit Kontakten verknüpft werden. +
*Variante* = Tag kann mit Varianten verknüpft werden. +

|Name in anderen Sprachen
|Tag-Namen in weiteren Sprachen eingeben. Weitere Informationen findest du im Kapitel <<basics/arbeiten-mit-plentymarkets/tags#200, Weitere Sprachen zu Tags hinzufügen>>.
|====

[#200]
== Tag-Namen in weiteren Sprachen hinzufügen

Gehe wie im Folgenden beschrieben vor, um zu einem bereits erstellten Tag Namen in weiteren Sprachen hinzuzufügen.

[.instruction]
Tag-Namen in weiteren Sprachen hinzufügen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Tags*.
. Klicke auf *Suchen*. +
→ Alle Tags werden angezeigt.
. Kicke auf das Tag. +
→ Rechts wird ein Fenster geöffnet.
. Gib in die Felder der gewünschten Sprachen die Übersetzung ein.
. *Speichere* die Einstellungen.

[#300]
== Tags filtern

Tags können nach *Name*, *Bereich* und *Sprache* gefiltert werden. Gehe wie unten beschrieben vor, um Tags anhand dieser Kriterien zu filtern.

[.instruction]
Tags filtern:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Tags*.
. Wähle einen oder mehrere Filter. Beachte dazu die Erläuterungen in <<tabelle-tag-filter>>.
. Klicke auf *Suchen*. +
→ Die Tags, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

[[tabelle-tag-filter]]
.Tag-Filter
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
|Name des Tags eingeben. +
*_Tipp:_* Wenn alle Sprachen gewählt wurden, werden alle Sprachen berücksichtigt. Angezeigt wird jedoch der unter *Name DE* eingegebene Wert.

|*Bereich*
|Einen oder mehrere Bereiche wählen, um nur für diese Bereiche aktivierte Tags anzuzeigen.

|*Sprache*
|Einen oder mehrere Sprachen wählen, um nur Tags mit Namen in diesen Sprachen anzuzeigen.
|====
