= Tags
:lang: de
include::{includedir}/_header.adoc[]
:position: 110

Tags sind Schlagworte, mit denen Texte und Seiten markiert werden können. In plentymarkets werden Tags zentral in einem Menü angelegt und verwaltet und stehen dann in verschiedenen Bereichen, z.B. für die Kategorien und das Ticketsystem, zur Verfügung. Sie können Tags auch mit Leerzeichen anlegen. Wenn ein Tag z.B. aus zwei Worten besteht, ist ein Leerzeichen dazwischen möglich.

== Tag erstellen

Im Folgenden wird erklärt, wie Sie Tags erstellen.

[.instruction]
Tag erstellen:

. Öffnen Sie das Menü *System » Einstellungen » Tags*.
. Klicken Sie auf *Neues Tag erstellen*. +
→ Ein Fenster wird geöffnet.
. Geben Sie den *Namen* für das Tag ein.
. Wählen Sie ggf. eine Farbe.
. Wählen Sie den *Bereich*, in dem das Tag verwendet werden soll, oder *Alle*.
. *Speichern* Sie die Einstellungen. +
→ Das Tag wird der Liste hinzugefügt.

Es besteht die Möglichkeit, Tags in anderen Sprachen anzulegen. Gehen Sie dazu, wie im Folgenden beschrieben vor.

[.instruction]
Tag in weiterer Sprache hinzufügen:

. Öffnen Sie das Menü *System » Einstellungen » Tags*.
. Klicken Sie auf *Suchen*. +
→ Alle erstellten Tags werden angezeigt.
. Wählen Sie das Tag aus der Liste.
. Aktivieren Sie die *Sprache* in der Dropdown-Liste.
. Klicken Sie auf der rechten Seite in die Zeile der Sprache und geben Sie die Übersetzung ein.
. *Speichern* Sie die Einstellungen.

<<tabelle-tag-einstellungen>> erläutert die Einstellungen eines Tags:

[[tabelle-tag-einstellungen]]
.Tag-Einstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
|Zeigt den Namen des Tags. Dieser Name ist *_keiner_* Sprache zugeordnet.

|*Farbe*
|Ggf. eine Farbe für das Tag wählen.

|*Bereich*
|Einen Bereich, wie *Kategorie* oder *Ticket*, oder *Alle* wählen, damit das Tag in diesem Bereich verfügbar ist.

|*Name der Sprache*
|Tag in weiteren Sprachen erstellen oder Tag für eine Sprache ändern.
|====

== Tags filtern

Es stehen drei Filter zur Verfügung, um Tags zu filtern. Es können der *Name*, der *Bereich* und die *Sprache* gefiltert werden.

<<tabelle-tag-filter>> erläutert die Filter für Tags:

[[tabelle-tag-filter]]
.Tag-Filter
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
|Name des Tags eingeben. Wenn alle Sprachen gewählt wurden, werden hierbei alle Sprachen berücksichtigt. Angezeigt wird jedoch der unter *Name* eingegebene Wert.

|*Bereich*
|Einen Bereich oder *Alle* wählen.

|*Sprache*
|Eine Sprache oder *Alle* wählen.

|====
