= Tags verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Tag, Tags, Tag erstellen
:description: Erfahren Sie auf dieser Handbuchseite, wie Sie Tags in plentymarkets verwalten.
:position: 60

Tags sind Schlagworte, mit denen Texte und Seiten markiert werden können. In plentymarkets werden Tags zentral in einem Menü erstellt und verwaltet und stehen dann in verschiedenen Bereichen, z.B. *Kategorien* und *Ticketsystem*, zur Verfügung. Sie können Tags auch mit Leerzeichen erstellen. Wenn ein Tag z.B. aus zwei Worten besteht, ist ein Leerzeichen dazwischen möglich.

[#100]
== Tag erstellen

Im Folgenden wird erklärt, wie Sie Tags erstellen. Sie legen fest, ob die Tags in allen verfügbaren Bereichen oder nur in bestimmten Bereichen von plentymarkets sichtbar sind.

[.instruction]
Tag erstellen:

. Öffnen Sie das Menü *System » Einstellungen » Tags*.
. Klicken Sie auf *Neues Tag erstellen*. +
→ Ein Fenster wird auf der rechten Seite geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-tag-einstellungen>>.
. *Speichern* Sie die Einstellungen. +
→ Das Tag wird erstellt und der Liste hinzugefügt.

[[tabelle-tag-einstellungen]]
.Tag-Einstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
|Zeigt den Namen des Tags. Dieser Name ist *_keiner_* Sprache zugeordnet.

|*Farbe*
|Optional Farbe für das Tag wählen.

|*Bereich*
|Bereich, wie *Kategorie* oder *Ticket*, oder *Alle* wählen, damit das Tag in diesem Bereich verfügbar ist.

|*Name der Sprache*
|Tag in weiteren *Sprachen* erstellen oder Tag für eine Sprache ändern. Weitere Informationen finden Sie im Kapitel <<basics/arbeiten-mit-plentymarkets/tags#200, Weitere Sprachen hinzufügen>>.
|====

[#200]
== Weitere Sprachen hinzufügen

Sie haben die Möglichkeit, bestehenden Tags weitere Sprachen hinzuzufügen. Gehen Sie dazu, wie im Folgenden beschrieben vor.

[.instruction]
Weitere Sprachen hinzufügen:

. Öffnen Sie das Menü *System » Einstellungen » Tags*.
. Klicken Sie auf *Suchen*. +
→ Alle erstellten Tags werden angezeigt.
. Wählen Sie das Tag aus der Liste. +
→ Ein Fenster wird auf der rechten Seite geöffnet.
. Klicken Sie in die Zeile der Sprache und geben Sie die Übersetzung ein.
. *Speichern* Sie die Einstellung.

Wiederholen Sie diese Schritte, um weitere Sprachen hinzuzufügen.

[#300]
== Tags filtern

Es stehen drei Filter zur Verfügung, um Tags zu filtern. Es können der *Name*, der *Bereich* und die *Sprache* gefiltert werden.

[.instruction]
Tags filtern:

. Öffnen Sie das Menü *System » Einstellungen » Tags*.
. Wählen Sie einen oder mehrere Filter. Beachten Sie dazu die Erläuterungen in <<tabelle-tag-filter>>.
. Klicken Sie auf *Suchen*. +
→ Die Tags, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

[[tabelle-tag-filter]]
.Tag-Filter
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
| Name des Tags eingeben. Wenn alle Sprachen gewählt wurden, werden alle Sprachen berücksichtigt. Angezeigt wird jedoch der unter *Name* eingegebene Wert.


|*Bereich*
|Einen Bereich oder *Alle* wählen.

|*Sprache*
|Eine Sprache oder *Alle* wählen.

|====
