= IT-Recht Kanzlei
:lang: de
include::{includedir}/_header.adoc[]
:position: 160

[NOTE]
.Alt: CMS & Webshop
====
Diese Handbuchseite widmet sich Funktionen des alten plentymarkets Webshops *Callisto*. Informationen zum Webshop-Template *Ceres* finden Sie <<omni-channel/online-shop/ceres-einrichten#0, hier>>.
====

Die link:http://www.it-recht-kanzlei.de/schutzpakete.html[IT-Recht Kanzlei^]
bietet Ihnen für die <<omni-channel/online-shop/webshop-einrichten#rechtliche-angaben, Rechtstexte>>
Ihres Webshops einen Update-Service, der Ihre rechtlichen Angaben immer aktuell hält.

== Benutzerkonto einrichten

Ihr plentymarkets System wird über die SOAP-Schnittstelle mit der Dienstleistung der IT-Recht Kanzlei verbunden, d.h., Sie benötigen das SOAP-Modul. Für den Zugriff benötigt dieser Dienst einen Benutzer mit Zugriffsrechten auf die API Ihres Systems.

[.instruction]
Neuen Benutzer anlegen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Klicken Sie auf *Neu*. +
→ Das Bearbeitungsfenster *Neuen Benutzer anlegen* wird angezeigt.
. Tragen Sie den *Benutzernamen*, den *realen Namen* und das *Passwort* ein.
. Wiederholen Sie das Passwort.
. Tragen Sie die E-Mail-Adresse des Benutzers ein, damit der Benutzer Benachrichtigungen des Systems empfängt.
. Wählen Sie die Benutzerklasse *API* oder *Variabel*.
. *Speichern* Sie die Einstellungen.

Folgende Calls müssen für den Benutzer freigegeben werden:

* GetServerTime
* GetPlentyMarketsVersion
* GetMultiShops
* GetTermsAndCancellation
* SetTermsAndCancellation
* GetLegalInformation
* SetLegalInformation

Beachten Sie dazu die Handbuchseite <<omni-channel/online-shop/webshop-einrichten/extras/it-recht-kanzlei#4, Einführung SOAP-API>>.

== Rechtstexte automatisch übertragen

Damit Rechtstexte automatisch von der IT-Recht-Kanzlei übertragen werden, müssen Sie in Ihrem Konto bei der IT-Recht Kanzlei eine Datenschnittstelle einrichten. Folgende Informationen benötigt die IT-Recht Kanzlei von Ihnen für die Anbindung an Ihr System:

* Login-Daten, Benutzername und Passwort für den Benutzer
* URL der SOAP API WSDL +
Die URL finden Sie im Menü *System » Einstellungen » API » Daten* unter <<basics/datenaustausch/api-daten#, SOAP WSDL>>.
