= YOOCHOOSE
:lang: de
include::{includedir}/_header.adoc[]
:keywords: yoochoose, Cross-Selling, Empfehlungen
:position: 310

[NOTE]
.Alt: CMS & Webshop
====
Diese Handbuchseite widmet sich Funktionen des alten plentymarkets Webshops *Callisto*. Informationen zum Webshop-Template *Ceres* finden Sie <<omni-channel/online-shop/ceres-einrichten#0, hier>>.
====

Der externe Dienstleister YOOCHOOSE stellt eine Alternative zum plentymarkets Cross-Selling dar. YOOCHOOSE liefert Ihren Webshop-Kunden Cross-Selling-Vorschläge, die auf Basis statistischer Auswertungen des Nutzverhaltens individuell zugeschnitten sind. Die YOOCHOOSE Recommender Engine liefert personalisierte Produktempfehlungen, indem Sie das Wissen über Ihre Produkte mit dem Benutzerverhalten Ihrer Anwender kombiniert und individualisierte Empfehlungen ausspricht. Das Spektrum der Empfehlungen reicht dabei vom simplen Amazon-Ansatz „Andere Leute kauften auch …“ bis hin zu individuell personalisierten und selbstlernenden Empfehlungen.

YOOCHOOSE bietet die folgenden Features:

* *Empfehlungen berechnen:*Neueste patentierte Algorithmen, die zielgenaue Empfehlungen aus der Kombination des Nutzungsverhaltens und der Kenntnis Ihres Produktkatalogs berechnen.
* *Situationsabhängige Ausspielung:* Die Platzierung und der Kontext auf Haupt- und Detailseiten entscheiden darüber, welche Algorithmen und Filter zum Einsatz kommen.
* *Optimierung über Filter:* Durch geeignete Filter auf Kategorien, Dubletten, Zeitfenster oder bereits gezeigte Empfehlungen wird die Qualität der Empfehlungen deutlich gesteigert.
* *Fallback-Verfahren:* Sollten noch keine Nutzungs- oder Profildaten zu Produkten oder Anwendern vorliegen, werden automatisch Fallback-Verfahren genutzt, um bewährte Empfehlungen auszuspielen.
* *Statistische Auswertung:* Statistische Auswertungen über Nutzung und Akzeptanz.

== Bei YOOCHOOSE registrieren

Gehen Sie wie unten beschrieben vor, um sich bei YOOCHOOSE zu registrieren.

[.instruction]
Bei YOOCHOOSE registrieren:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Dienste » Yoochoose*.
. Klicken Sie auf den Link *Jetzt registrieren*. +
→ Die Registrierungsseite von YOOCHOOSE wird geöffnet.
. Registrieren Sie sich wie auf der externen Registrierungsseite beschrieben. +
→ Sie erhalten eine Kundennummer und einen Lizenzschlüssel für die Einrichtung in plentymarkets.
. Wechseln Sie zurück ins plentymarkets Backend.
. Nehmen Sie die weiteren Einstellungen gemäß <<tabelle-registrierung-yoochoose>> vor.
. *Speichern* Sie die Einstellungen.

[[tabelle-registrierung-yoochoose]]
.YOOCHOOSE; Registrierung
[cols="1,3"]
|====
|Option |Erläuterung

|*Registrierung*
|Link zur Webseite von YOOCHOOSE. Auf den Link klicken, um die Registrierung durchzuführen.

|*Kundennummer*
|Bei der Registrierung erhaltene Kundennummer eingeben.

|*Lizenzschlüssel*
|Bei der Registrierung erhaltenen Lizenzschlüssel eingeben.

|*Tracking aktiviert*
|*Ja* = Benutzerbezogene Daten des Webshops werden an YOOCHOOSE übertragen.

|*Empfehlungen abrufen*
|*Ja* = Artikeldaten für das Cross-Selling werden von YOOCHOOSE abgerufen.
|====

== YOOCHOOSE in plentymarkets einrichten

Nachdem Sie sich bei YOOCHOOSE registriert haben, werden weitere Tabs eingeblendet, über die Sie YOOCHOOSE in plentymarkets einrichten.

=== Empfehlungen und Layout konfigurieren

Entscheiden Sie, welche Artikel Kunden als Cross-Selling-Artikel angeboten werden. Während die Optionen der Kategorieansicht mehr allgemeine Ergebnisse liefern, sind die Möglichkeiten der Artikelansicht spezieller.

[.instruction]
Empfehlungen und Layout konfigurieren:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Dienste » Yoochoose*.
. Öffnen Sie das Tab *Konfiguration*.
. Nehmen Sie die Einstellungen gemäß <<tabelle-konfiguration-yoochoose>> vor.
. *Speichern* Sie die Einstellungen.

[[tabelle-konfiguration-yoochoose]]
.Konfiguration
[cols="1,3"]
|====
|Option |Erläuterung

|*Empfehlungen für Kategorieansicht*
|Option für die Kategorieansicht wählen.

|*Layout*
|Template für die Gestaltung der Cross-Selling-Artikelansichten im Webshop wählen.

|*Empfehlungen für Artikelansicht*
|Option für die Artikelansicht wählen.

|*Layout*
|Template für die Gestaltung der Cross-Selling-Artikelansichten im Webshop wählen. Standardmäßig ist das Template *ArticleListCrossSelling* eingestellt. Sie können die Variante *ArticleListCrossSelling2* dieses Templates wählen und in diesem Template z.B. abweichende Einstellungen hinterlegen. So haben Sie die Möglichkeit, je nach Bedarf verschiedene Ansichten einzustellen.
|====

=== Kaufhistorie exportieren

Mit der Funktion *Kaufhistorie exportieren* erstellen Sie einmalig einen Datensatz mit Informationen zu den Artikeln, die bisher in Ihrem Webshop verkauft wurden. Auf Grundlage dieser Daten kann YOOCHOOSE ohne umfangreiche Lernphase Empfehlungen erstellen.

[IMPORTANT]
.Kaufhistorie nur einmal exportieren
====
Führen Sie die Funktion *Kaufhistorie exportieren* nur einmal zu Beginn Ihrer Zusammenarbeit mit YOOCHOOSE aus, da Informationen sonst mehrfach bei YOOCHOOSE eingehen und das Ergebnis verfälschen.
====

[.instruction]
Kaufhistorie exportieren:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Dienste » Yoochoose*.
. Öffnen Sie das Tab *Kaufhistorie*.
. Wählen Sie den Zeitraum, für den die Kaufhistorie erstellt werden soll.
. Klicken Sie auf das *Zahnrad*, um die Daten zu exportieren. +
→ Die Daten werden an YOOCHOOSE übermittelt. +
*_Tipp:_* YOOCHOOSE importiert die Daten zeitversetzt. YOOCHOOSE informiert Sie, wenn der Import abgeschlossen ist.

=== Statistik abrufen

Gehen Sie wie unten beschrieben vor, um eine Auflistung der Ereignisse und Klicks abzurufen, die mit YOOCHOOSE erfolgt sind.

[.instruction]
Statistiken abrufen:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Dienste » Yoochoose*.
. Öffnen Sie das Tab *Statistik*. +
→ Die Statistik wird nach Datum sortiert angezeigt.

=== Relevante Template-Variablen und -Funktionen

==== Container_YOOCHOOSE_Recommendations

*Container_YOOCHOOSE_Recommendations* entspricht dem Template *Container_ItemViewCrossSellingItemsList* bzw. *Container_ItemViewCrossSellingItemsList2*, nutzt jedoch die von YOOCHOOSE empfohlenen Artikel.

==== Link_CrossSellingItem()

Das Ziel des Links entspricht der Template-Funktion *Link_Item()*, jedoch wird hier noch ein Parameter angehängt, der den angesehenen Artikel nach dem Klicken des Links als CrossSelling-Artikel identifizierbar macht. Das ist für das Sammeln der Daten für YOOCHOOSE nötig, ist aber auch für andere Anwendungen verwendbar. Der übergebene Parameter heißt *from_crossselling* und hat den Wert *1*.

==== Zusätzliche Pflichtparameter für die Template-Funktion Link_CrossSellingItem()

Diese zusätzlichen Pflichtparameter für die Template-Funktion Link_CrossSellingItem() gewährleisten die korrekte Übertragung der Kategorien. Beachten Sie, dass der Code weder Leerzeichen noch Zeilenumbrüche enthalten darf.

*[Link_CrossSellingItem()_]&amp;yc1=[Request_CategoryId_Level1]&amp;yc2=[Request_CategoryId_Level2]&amp;yc3=[Request_CategoryId_Level3]&amp;yc4=[Request_CategoryId_Level4]&amp;yc5=[Request_CategoryId_Level5]&amp;yc6=[Request_CategoryId_Level6]*

==== Zusätzliche Pflichtparameter für die Template-Funktion Link_Item()

Diese zusätzlichen Pflichtparameter für die Template-Funktion Link_Item() gewährleisten die korrekte Übertragung der Kategorien. Beachten Sie, dass der Code weder Leerzeichen noch Zeilenumbrüche enthalten darf.

*{% Link_CrossSellingItem($_itemID) %}&amp;yc1=$Request_CategoryId[Level1]&amp;yc2=$Request_CategoryId[Level2]&amp;yc3=$Request_CategoryId[Level3]&amp;yc4=$Request_CategoryId[Level4]&amp;yc5=$Request_CategoryId[Level5]&amp;yc6=Request_CategoryId[Level6]*

Die Parameter für *Link_Item()* müssen im Webshop-Design in allen Artikellisten (z.B. ItemViewCategoriesList) ergänzt werden.
