= Twitter
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Twitter, Social Media
:position: 20

**plentymarkets » Einstellungen » Mandant (Shop) » Globale Einstellungen » Dienste » Twitter**

== Twitter

Nutzen Sie bereits den Mikroblogging-Dienst **link:http:///www.twitter.com[Twitter, window="_blank"]**? Als angemeldeter Benutzer können Sie Textnachrichten mit maximal 140 Zeichen senden und die Nachrichten von anderen Benutzern empfangen.

Die Nachrichten werden Tweets (engl. to tweet = zwitschern) genannt. Das soziale Netzwerk von Twitter beruht darauf, dass man die Nachrichten anderer Benutzer abonniert, wobei Abonnenten bzw. Personen, die Ihnen
folgen als Follower (engl. to follow = folgen) bezeichnet werden und Personen, denen Sie folgen, unter Following geführt werden. Auf der Twitter-Startseite können Sie Nachrichten eingeben und die Nachrichten der Personen, denen Sie folgen, chronologisch sortiert sehen.

Mit plentymarkets werden Tweets direkt an Twitter übergeben. Zu Artikeln, Blog-Beiträgen und Content-Seiten werden automatisch Tweet-Vorschläge generiert. +
Zudem ist es möglich, die URLs, die in den Vorschlägen enthalten sind, direkt vom Kurz-URL-Dienst **link:http://bit.ly/[bit.ly, window="_blank"]** kürzen zu lassen, um Ihren Worten mehr Raum zu geben. Weitere Details zur Konfiguration von bit.ly finden Sie auf der Handbuchseite <<mandant-shop/globale-einstellungen/externe-dienste/bit-ly#, **bit.ly**  >>.

[TIP]
.Tipp
====
Motivieren Sie Ihre Kunden und Interessenten dazu, Ihren Twitter-Blog zu abonnieren, damit Sie ihnen Produktneuerungen und Sonderangebote per Twitter schicken können.
====

Weitere Details zur Konfiguration von Twitter, finden Sie auf der Handbuchseite <<mandant-shop/globale-einstellungen/externe-dienste/twitter#, **Twitter**  >>

