= Datenbank-Backup durchführen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Backup, Daten sichern, Rücksicherung, Datensicherung, rücksichern, Wiederherstellung, wiederherstellen
:description: Erfahre, wie du in plentymarkets Daten sicherst und einspielst.
:position: 60
:url: daten/backup

Mit der Backup-Funktion des Menüs **System » Systemeinstellungen » Einstellungen » Daten » Backup** setzt du Daten in der Datenbank auf einen früheren Stand zurück oder stellst gelöschte Daten wieder her.

[IMPORTANT]
.Einschränkungen
====
Die Backup-Funktion ist nur innerhalb der gleichen plentymarkets Version verfügbar. Du kannst also kein Backup einer älteren Version von plentymarkets einspielen. Außerdem handelt es sich bei dieser Funktion um ein Backup der Datenbank. In der Cloud gespeicherte Inhalte wie Auftragsdokumente oder Artikelbilder können mit dieser Funktion *nicht* wiederhergestellt werden.
====

== Backup und Wiederherstellung

Das Menü **System » Systemeinstellungen » Einstellungen » Daten » Backup**  bietet eine Übersicht über die durchgeführten Backups. Dort werden die Backups, die automatisch einmal täglich erstellt werden, mit dem entsprechenden Datum aufgelistet.

=== Backup lokal speichern

Du kannst Backup-Dateien als zusätzliche Sicherung lokal abspeichern. Gehe dazu wie folgt vor.

[.instruction]
Backup lokal speichern:

. Öffne das Menü **System » Systemeinstellungen » Einstellungen » Daten » Backup**.
. Wähle das Backup, das du herunterladen möchtest.
. Klicke auf **Backup herunterladen**. +
→ Das Backup wird lokal in komprimierter Form heruntergeladen.

[TIP]
.Warten auf Backup
====
Bei größeren Dateien dauert der Download länger. Sobald der Vorgang abgeschlossen ist, wird die Schaltfläche zum Downloaden aktiviert.
====

=== Backup einspielen

Du kannst dein System jederzeit auf den Stand eines beliebigen Backups zurücksetzen.

[WARNING]
.Möglicher Datenverlust
====
Beachte, dass durch das Importieren eines Backups aktuelle Daten überschrieben werden und Daten, die seit der letzten Backup-Erstellung verändert wurden, unwiderruflich verloren gehen können.
====

[.instruction]
Backup einspielen:

. Öffne das Menü **System » Systemeinstellungen » Einstellungen » Daten » Backup**.
. Klicke auf **Backup einspielen**. +
→ Das Fenster zum Einspielen von Backups wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Einstellungen in <<tabelle-import-optionen>> und <<tabelle-backup-typen>>.
. Klicke auf **Backup einspielen**, um das Backup einzuspielen. +
→ Das Backup wird eingespielt.

Im Dropdown-Menü gibt es zwei verschiedene Import-Optionen.

[[tabelle-import-optionen]]
.Import-Optionen
[cols="1,2"]
|====
|Import-Option |Erläuterung

|**Datenbank teilweise importieren**
|Hier können die Bereiche ausgewählt werden, die eingespielt werden sollen.

|**Datenbank komplett importieren**
|Hier werden sämtliche vorhandene Daten berücksichtigt und wiederhergestellt.
|====


Wähle den Bereich des Systems, der zurückgesetzt werden soll oder in dem gelöschte Daten wiederhergestellt werden sollen.

[[tabelle-backup-typen]]
.Backup-Typen
[cols="1,2"]
|====
|Backup-Typ |Erläuterung

|**Account** +
|Firma, Kontakt und Adresse +

|**Category** +
|Kategorien des Menüs **Artikel » Kategorien**

|**Listing** +
|Informationen zu Listings und Market-Listings, aktiven Listings, Listing-Einstellungen für eBay, hood und ricardo, Verkaufsplanern, Listing-Verzeichnissen, Listing-Texten und Übersetzungen

|**Order**
|Auftrag und Auftragspositionsdaten

|**Process**
|Mit plentyBase automatisierte Abläufe +

|**Reorder**
|Nachbestellungen unter **Waren » Nachbestellungen**

|**Ticket**
|Ticket

|**User**
|Im System registrierte Nutzer und die von diesen vorgenommenen Einstellungen

|**Warehouse**
|Lager und Lageraufbau, wie z.B. Dimensionen und Lagerorte; *_Hinweis:_* Beinhaltet nicht den Warenbestand! Jedoch kann der link:https://knowledge.plentymarkets.com/warenwirtschaft/best-practices-warenbestand[Warenbestand täglich gesichert] und somit ein Backup erstellt werden.

|**FacetDefinition**
|Facetten für die Suche unter *System » Systemeinstellungen » Mandant » Global » Dienste » Facettensuche*

|**Item**
|Artikelstammdaten, vorwiegend im Tab *Global*

|**ItemAttribute**
|Attribute der Artikel unter **System » Systemeinstellungen » Artikel » Attribute**

|**ItemBarcodeDefinition**
|Verknüpfung des Barcodes an der Variante

|**ItemCharacterDefinition**
|Merkmale am Artikel

|**ItemCharacterValues**
|Werte der Merkmalverknüpfungen

|**ItemPriceCalculation**
|Preiskalkulationen, die an der Variante hinterlegt sind

|**ItemManufacturer**
|Hersteller des Artikels

|**ItemSalesPriceDefinition**
|Verkaufspreisverknüpfung an der Variante

|**ItemUnit**
|Einheit der Variante

|**ItemVariation**
|Varianten des Artikels

|**ItemVariationCategoryValues**
|Kategorieverknüpfungen der Varianten

|**ItemVariationSalesPriceValues**
|Werte aus den Preisverknüpfungen der Varianten
|====

=== Backup-Logs anzeigen

Mit Klick auf die Schaltfläche in der Toolbar werden Backup-Logs und eventuelle Fehlermeldungen angezeigt.

[.instruction]
Backup-Logs anzeigen:

. Gehe zu *System » Systemeinstellungen » Einstellungen » Daten » Backup*.
. Klicke auf *Zeige Backup-Logs*. +
→ Das Fenster mit den Backup-Logs wird geöffnet.

Mehr Informationen findest du auf der Handbuchseite zum <<basics/arbeiten-mit-plentymarkets/datenlog#, Daten-Log>>.
