= Daten exportieren
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Export, ElasticExport
:description: Erfahren Sie, wie Sie das Plugin ElasticExport nutzen, um Daten aus plentymarkets zu exportieren.
:position: 20
:url: daten/daten-exportieren
:id: FGTSSBX
:author: team-elasticsync

Es gibt viele Gründe, Daten aus deinem plentymarkets System zu exportieren.
Vielleicht willst du z.B.:

* deine Artikel- und Variantendaten an Marktplätze übertragen.
* eine CSV-Datei exportieren, die mit Produktdaten, Lagerdaten, Auftragsdaten usw. gefüllt ist.
Diese Datei kannst du anschließend überarbeiten und wieder importieren.

Diese Seite stellt die unterschiedliche Tools dafür kurz vor. Klicke auf die Links, um ausführlichere Informationen über die Tools zu lesen.

== Elastischer Export

Der elastische Export ist ein kostenloses Plugin, das du von plentyMarketplace herunterladen und zu deinem System hinzufügen kannst.
////
Mit dem elastischen Export-Plugin kannst du, z.B.:

* deine Artikel- und Variantendaten an Marktplätze übertragen.
* eine CSV-Datei exportieren, die mit Produktdaten, Lagerdaten, Auftragsdaten usw. gefüllt ist.
Diese Datei kannst du anschließend überarbeiten und wieder importieren.
////
Je nachdem, was du erreichen willst, gehst du unterschiedlich vor:

[.tabs]
====
Produkte an Marktplätze übertragen::
+
--

. Lade die nötigen Plugins herunter:
.. Elastischer Export
.. Sogenannte Datenformat-Plugins für deine gewünschten Marktplätze
. Richte den elastischen Export ein.
Wähle dabei das Datenformat für den entsprechenden Marktplatz aus.
. Exportiere die CSV-Datei und übertrage diese an den Marktplatz.

//Danach verwendest du den <<daten/daten-exportieren/elastischer-export#, Elastischen Export>>, um deine Artikel- und Variantendaten an Marktplätze übertragen.


--
Daten exportieren, überarbeiten, neu importieren::
+
--

. Lade die nötigen Plugins herunter:
.. Elastischer Export
.. FormatDesigner
. Erstelle sogenannte Datenformate mit Hilfe des FormatDesigners.
//Mit anderen Worten entscheidest du, welche Daten exportiert werden sollen.
. Richte den elastischen Export ein.
Wähle dabei das soeben erstellte Datenformat aus.
. Exportiere die CSV-Datei, überarbeite diese und importiere sie wieder in plentymarkets.

--
====

[discrete]
=== Vorteile und Nachteile des elastischen Exports

* *_Vorteil_*: Kann mit vielen verschiedenen Marktplätzen verwendet werden.

* *_Nachteil_*: Ältere Technologie, die schrittweise durch den Katalog ersetzt wird.


[discrete]
=== Weiterführende Informationen

[.row]
====
[.col-md-6]
.Elastischer Export
=====
* link:https://marketplace.plentymarkets.com/plugins/sales/marktplaetze/elasticexport_4763[Plugin: Elastischer Export^]{nbsp}icon:external-link[]
* <<daten/daten-exportieren/elastischer-export#, Einrichung und Verwendung>>
* #<<Liste der verfügbaren Datenformate>>#
* <<daten/daten-exportieren/best-practices-elastischer-export#, Fehlerbehebung>>
* <<daten/daten-exportieren/dropshipping-elasticexport-bp#, Praxisbeispiel>>
=====

[.col-md-6]
.FormatDesigner
=====
* link:https://marketplace.plentymarkets.com/formatdesigner_6483[Plugin: FormatDesigner^]{nbsp}icon:external-link[]
* <<daten/daten-exportieren/FormatDesigner#, Eigene Datenformate erstellen>>
* <<daten/daten-exportieren/FormatDesigner/format-typen#, Liste der verfügbaren Formattypen>>
=====
====

== Kataloge

Der Katalog ist ein relativ neues Tool in plentymarkets.

Verwende Kataloge, um den Export von Variantendaten an Marktplätze und andere Verkaufskanäle durchzuführen. Aktuell kannst du Kataloge nutzen, um Daten an die Marktplätze REWE, Etsy, Metro und OTTO Market zu übertragen.

Kataloge dienen dazu, Variantendaten für den Export an einen Verkaufskanal vorzubereiten.

Der Katalog ermöglicht es dir, deine Produkte schnell und einfach auf Marktplätzen zu platzieren.
Otto, Metro.de, Etsy, Rewe, Amazon

Der Katalog ist eine Möglichkeit, um eure Artikeldaten so anzureichern, so dass dise für Marktplätze wie Otto, Metro entsprechend exportieren könnte.
Der Katalog ist dafür da, um Marktplatz-Exporte durchfürhen zu können.

Vorteile:

* Verkaufskanal gibt Datenstruktur vor. Wenn ihr ein Katalog anlegt, z.B. wollt ihr euere Produkte auf einen bestimmten Kategorie auf Otto verkaufen, dann erwartet der Marktplatz entsprechende Artikeldaten. Und diese Artikeldaten müsst ihr mit euren plentymarkets-Datenfeldern verknüpfen. Das heißt, jeder Marktplatz und auch jede Kategorie davon des Marktplatzes gibt die Datenstruktur vor. Händler bekommen den Datenstruktur von den Marktplatz und müssen dieser einfach nur mit den plentymarkets Datenfeldern zuordnen.
* Einfache Zuordnung
* Du bestimmst, welche Daten auf dem Verkaufskanal veröffentlicht werden. Beispielsweise, Artikelname 1 hast du gepflegt für eBay. Und du möchtest, dass jetzt an Otto Name 2 exportiert werden soll. Dann ist das möglich. Also du bestimmst, welche Daten exportiert werden.
* Ausweich-Datenfelder hinterlegen. Also wenn ein bestimmtes Datenfeld nicht vorhanden ist in plenty, dann kannst du ein weiteres Datenfeld hinterlegen, was quasi als Ersatz genommen wird.
* Datenfelder verknüpfen. Du kannst Datenfelder mit einander verknüpfen. Z.B. du möchtest, dass in Kombination Name 1 und Name 2 exportiert werden sollen. Dann kannst du die Datenfelder miteinander verknüpfen und kannst auch bestimmen, welches Trennzeichen zwischen den einzelnen Datenfledern hinterlegt werden.

Nachteile:

* Noch nicht mit allen Märkten kompatibel
* Noch wenige Standardformate


Der Katalog soll auf langer Sicht gesehen, den Ersatz für den Elastischen Export werden. Das bedeutet, sobald wir alle Standardformate inklusive Exportfilter in den Katalog implementiert haben, fliegt der elastischer Export weg.
1 Model, 2 Exportwege. Das heißt, Händler können den Katalog für beides verwenden: einmal für Marktplatzexporte und für die "normale" Datenexporte wie Auftragsdaten, Artikeldaten, Eigenschaften, etc.
