= Datenbereinigung durchführen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Bereinigung, Daten-Bereinigung, Datenbereinigung, automatisch löschen, Adressen löschen, ungenutzte Adressen löschen, ungenutzte Kontakte löschen, Aufträge löschen, Historie löschen, IP-Adressen löschen
:description: Erfahren Sie, wie Sie in plentymarkets automatisch Daten bereinigen.
:position: 50

Auf dieser Handbuchseite wird beschrieben, wie Sie im Menü *System » Einstellungen » Daten » Bereinigung* bestimmte Datensätze nach Ablauf eines Zeitraums, den Sie selbst festlegen, automatisch löschen. +


Für das Löschen von Daten mithilfe der Datenbereinigung gibt es 2 Hauptgründe. Als Händler müssen Sie gemäß der DSGVO personenbezogene Daten aus Ihrem System löschen. Außerdem können Sie die Datenbereinigung nutzen, um den Speicherverbrauch zu reduzieren. Dies kann beispielsweise helfen, wenn Sie den kostenlos in Ihrem plentymarkets Tarif enthaltenen Speicherplatz überschreiten.  

[#100]
== Sichtbarkeit des Menüs für variablen Benutzer einstellen

Damit für Benutzer mit der Benutzerklasse *Variabel* das Menü *System » Einstellungen » Daten » Bereinigung* sichtbar ist, muss dieses Menü im Benutzerkonto freigeschaltet werden.

Außerdem müssen Berechtigungen im Bereich *REST-API* aktiviert werden.

[.instruction]
Sichtbarkeit des Menüs für variablen Benutzer einstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den Benutzer mit der Benutzerklasse *Variabel*, für den Sie die Sichtbarkeit des Menüs aktivieren möchten.
. Wechseln Sie in das Tab *Berechtigung*.
. Wechseln Sie in das Tab *Menü*.
. Klappen Sie den Bereich *Einstellungen » Grundeinstellungen » Daten* auf.
. Aktivieren Sie die Option *Bereinigung*.
. Wechseln Sie in das Tab *REST-API*.
. Klappen Sie den Bereich *Datenbereinigung* auf.
. Aktivieren Sie die Optionen *Konfiguration anzeigen* und *Konfiguration speichern*.
. *Speichern* Sie die Einstellungen.

[#200]
== Löschwerte eingeben

Damit Datensätze nach Ablauf eines bestimmten Zeitraums automatisch aus Ihrem plentymarkets System gelöscht werden, müssen Sie Werte für diesen Zeitraum eingeben. Gehen Sie dazu wie im Folgenden beschrieben vor.

[NOTE]
.Weitere Funktionen in diesem Menü werden sukzessive ergänzt
====
Aktuell können Sie unzugeordnete Adressen, ungenutzte Kontakte, Aufträge, die Historie sowie IP-Adressen am Auftrag automatisch löschen. Sukzessive werden weitere Bereiche in diesem Menü ergänzt.
====

[.instruction]
Löschwerte eingeben:

. Öffnen Sie das Menü *System » Einstellungen » Daten » Bereinigung*.
. Geben Sie im Eingabefeld einen Wert ein. Beachten Sie die Erläuterungen in <<tabelle-einstellungen-daten-bereinigung>>.
. Aktivieren Sie den Toggle-Button.
. *Speichern* Sie die Einstellungen.

[[tabelle-einstellungen-daten-bereinigung]]
.Einstellungen im System » Einstellungen » Daten » Bereinigung
[cols="1,3"]
|====
|Einstellung| Erläuterung

|*Löschung ungenutzter Adressen (nach Tagen)*
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden ungenutzte Adressen automatisch aus dem plentymarkets System gelöscht. Ungenutzte Adressen sind Adressen, die nicht mit einem Kontakt, einem Auftrag, einem POS oder einem Lager verknüpft sind. +
|*Löschung ungenutzter Kontakte (nach Tagen)*
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden ungenutzte Kontakte automatisch aus dem plentymarkets System gelöscht. Ungenutzte Kontakte sind Kontakte, die nicht mit Wareneingängen, Tickets oder Aufträgen verknüpft sind. +
|*Löschung von Aufträgen (nach Tagen)*
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden Aufträge automatisch aus dem plentymarkets System gelöscht. Aufträge werden mit den dazugehörigen Dokumenten gelöscht. Minimalwert: 60 Tage. +
*_Wichtig:_* Es handelt sich um steuerrechtlich relevante Daten, die nicht wiederhergestellt werden können. +
*_Hinweis_:* Aufträge, die ein Dokument mit der letzten Nummer des Nummernkreises enthalten, werden nicht gelöscht, bis ein neueres Dokument in einem anderen Auftrag generiert wurde.
|*Löschung der Historie (nach Tagen)*
|Zahl in Tagen eingeben. Nach diesem Zeitraum werde Einträge in der <<crm/kontakte-verwalten#5100, Historie>> automatisch aus dem plentymarkets System gelöscht. In der Historie werden Änderungen an Daten geloggt. Maximalwert: 365 Tage. +
|*Löschung von IP-Adressen am Auftrag (nach Tagen)*
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden am Auftrag gespeicherte IP-Adressen automatisch aus dem plentymarkets System gelöscht. +
|====

[IMPORTANT]
.Toggle-Button aktivieren
====
Daten werden nur gelöscht, wenn der Toggle-Button aktiviert und die Einstellung gespeichert wurde. +
Wenn die Daten nicht mehr nach Ablauf des eingegebenen Wertes gelöscht werden sollen, Toggle-Button deaktivieren und Einstellungen erneut speichern. +
*Ausnahme*: Die Löschung der Historie erfolgt auch bei einer Deaktivierung des Toggle-Buttons, dafür wird der Maximalwert von 365 Tagen beachtet.
====

[NOTE]
.Anzahl der zu löschenden Datensätzen
====
Aktuell werden bis zu 5000 Datensätze pro Tag gelöscht. plentymarkets wird dieses Verhalten beobachten und ggf. ebenfalls auf einen höheren Wert anpassen.
====

[#300]
== Tickets automatisch löschen

Löschen Sie Tickets automatisch aus Ihrem Ticketsystem. Diese Einstellung nehmen Sie nicht im Menü *System » Einstellungen » Daten » Bereinigung* vor, sondern über den Aktionsmanager im Ticketsystem im Menü *System » CRM » Ticketsystem » Aktionen*.

Weitere Informationen über das Ticketsystem sowie ein Beispielszenario zum Löschen von Tickets finden Sie auf der Handbuchseite <<crm/ticketsystem-nutzen#3000, Ticketsystem nutzen>>.

[#400]
== Log einsehen

Alle Änderungen, die im Menü *System » Einstellungen » Daten » Bereinigung* vorgenommen werden, werden im Menü *Daten » Log* für 30 Tage gespeichert. So können Sie einsehen, welcher Benutzer wann den alten Wert in den neuen Wert geändert hat.

Weitere Informationen zum Log finden Sie auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/datenlog#, Datenlog>>.
