= Datenbereinigung durchführen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Bereinigung, Daten-Bereinigung, Datenbereinigung, automatisch löschen, Adressen löschen, ungenutzte Adressen löschen, ungenutzte Kontakte löschen, Aufträge löschen, Historie löschen, IP-Adressen löschen
:description: Erfahre, wie du in plentymarkets automatisch Daten bereinigst.
:position: 50
:url: daten/datenbereinigung

Auf dieser Handbuchseite ist beschrieben, wie du im Menü *System » Systemeinstellungen » Einstellungen » Daten » Bereinigung* bestimmte Datensätze nach Ablauf eines Zeitraums, den du selbst festlegst, automatisch löschst. +

Für das Löschen von Daten mithilfe der Datenbereinigung gibt es 2 Hauptgründe. Als Händler musst du gemäß der DSGVO personenbezogene Daten aus deinem System löschen. Außerdem kannst du die Datenbereinigung nutzen, um den Speicherverbrauch zu reduzieren. Dies kann beispielsweise helfen, wenn du den kostenlos in deinem plentymarkets Tarif enthaltenen Speicherplatz überschreitest.

[#100]
== Benutzerrechte vergeben

Nutzer vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs im plentymarkets Backend. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter mit dem Zugang *Backend* die Datenbereinigung nutzen können, muss ein Nutzer vom Typ *Admin* zumindest die im folgenden beschriebenen Rechte für Benutzer mit dem Zugang *Backend* vergeben.

[.instruction]
Benutzerrechte für Backend-Benutzer vergeben:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion und öffne den zu bearbeitenden Benutzer.
. Klappe das Menü *Berechtigungen: Daten: Datenbereinigung* auf.
. Wähle die Einstellungen *Datenbereinigung bearbeiten*.
. *Speichere* die Einstellungen.

[#200]
== Löschwerte eingeben

Damit Datensätze nach Ablauf eines bestimmten Zeitraums automatisch aus deinem plentymarkets System gelöscht werden, musst du Werte für diesen Zeitraum eingeben. Gehe dazu wie im Folgenden beschrieben vor.

[NOTE]
.Weitere Funktionen in diesem Menü werden sukzessive ergänzt
====
Aktuell kannst du unzugeordnete Adressen, ungenutzte Kontakte, Aufträge, die Historie sowie IP-Adressen am Auftrag automatisch löschen. Sukzessive werden weitere Bereiche in diesem Menü ergänzt.
====

[.instruction]
Löschwerte eingeben:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Daten » Bereinigung*.
. Gib im Eingabefeld einen Wert ein. Beachte dazu die Erläuterungen in <<tabelle-einstellungen-daten-bereinigung>>.
. Aktiviere die Umschaltfläche.
. *Speichere* die Einstellungen.

[[tabelle-einstellungen-daten-bereinigung]]
.Einstellungen im Menü *System » Systemeinstellungen » Einstellungen » Daten » Bereinigung*
[cols="1,3"]
|====
|Einstellung| Erläuterung

|*Löschung ungenutzter Adressen (nach Tagen)*
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden ungenutzte Adressen automatisch aus dem plentymarkets System gelöscht. Ungenutzte Adressen sind Adressen, die nicht mit einem Kontakt, einem Auftrag, einem POS oder einem Lager verknüpft sind. +
|*Löschung ungenutzter Kontakte (nach Tagen)*
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden ungenutzte Kontakte automatisch aus dem plentymarkets System gelöscht. Ungenutzte Kontakte sind Kontakte, die nicht mit Wareneingängen, Tickets oder Aufträgen verknüpft sind. +
|*Löschung von Aufträgen (nach Tagen)*
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden Aufträge automatisch aus dem plentymarkets System gelöscht. Aufträge werden mit den dazugehörigen Dokumenten gelöscht. Minimalwert: 60 Tage. +
*_Wichtig:_* Es handelt sich um steuerrechtlich relevante Daten, die nicht wiederhergestellt werden können. +
*_Hinweis_:* Aufträge, die ein Dokument mit der letzten Nummer des Nummernkreises enthalten, werden nicht gelöscht, bis ein neueres Dokument in einem anderen Auftrag generiert wurde.
|*Löschung der Historie (nach Tagen)*
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden Einträge in der <<crm/kontakte-verwalten#5100, Historie>> automatisch aus dem plentymarkets System gelöscht. In der Historie werden Änderungen an Daten geloggt. Maximalwert: 365 Tage. +
|*Löschung von IP-Adressen am Auftrag (nach Tagen)*
|Zahl in Tagen eingeben. Nach diesem Zeitraum werden am Auftrag gespeicherte IP-Adressen automatisch aus dem plentymarkets System gelöscht. +
|====

[IMPORTANT]
.Umschaltfläche aktivieren
====
Daten werden nur gelöscht, wenn die Umschaltfläche aktiviert und die Einstellung gespeichert wurde. +
Wenn die Daten nicht mehr nach Ablauf des eingegebenen Wertes gelöscht werden sollen, Umschaltfläche deaktivieren und Einstellungen erneut speichern. +
*Ausnahme*: Die Löschung der Historie erfolgt auch bei einer Deaktivierung des Umschaltflächen, dafür wird der Maximalwert von 365 Tagen beachtet.
====

[NOTE]
.Anzahl der zu löschenden Datensätzen
====
Aktuell werden bis zu 5000 Datensätze pro Tag gelöscht. plentymarkets wird dieses Verhalten beobachten und ggf. ebenfalls auf einen höheren Wert anpassen.
====

[#300]
== Tickets automatisch löschen

Lösche Tickets automatisch aus deinem Ticketsystem. Diese Einstellung nimmst du nicht im Menü *System » Systemeinstellungen » Einstellungen » Daten » Bereinigung* vor, sondern über den Aktionsmanager im Ticketsystem im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Aktionen*.

Weitere Informationen über das Ticketsystem sowie ein Beispielszenario zum Löschen von Tickets findest du auf der Handbuchseite <<crm/ticketsystem-nutzen#3000, Ticketsystem nutzen>>.

[#400]
== Log einsehen

Alle Änderungen, die im Menü *System » Systemeinstellungen » Einstellungen » Daten » Bereinigung* vorgenommen werden, werden im Menü *Daten » Log* für 30 Tage gespeichert. So kannst du einsehen, welcher Benutzer wann den alten Wert in den neuen Wert geändert hat.

Weitere Informationen zum Log findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/datenlog#, Datenlog>>.
