= Procedural documentation
:lang: en
include::{includedir}/_header.adoc[]
:description: On this page you can download the technical system documentation of plentymarkets which serves plentymarkets users only as basis for creating their procedural documentation. ¤:keywords: GoBD, GOBD, gobd, fiscal, tax law, system documentation, procedural documentation, procedure, used software
:position: 10
:url: basics/legal-requirements/procedural-documentation
:id: JMGHYFQ

On this manual page we provide you with the technical system documentation of plentymarkets. This system documentation serves as basis for creating your own procedural documentation.

== Legally secure working with plentymarkets

According to GoBD (German regulation), sellers are, among other things, obliged to describe the procedure of the software they are using. This has to be done in form of a procedural documentation which has to be submitted in case of a tax audit. We support plentymarkets users in creating a procedural documentation by providing a technical system documentation. This documentation includes the detailed breakdown of all working methods of plentymarkets relevant in terms of tax law that can be used as a basis for a procedural documentation.

== Download link
Download the technical system documentation of plentymarkets link:https://github.com/plentymarkets/template-procedure-document/releases[here^]. +

[IMPORTANT]
.Further software solutions
====
plentymarkets is generally only a part of the (software) solutions that have to be described. Please clarify with your tax consultant which additional information have to be described in the procedural documentation in your particular case.
====
