= Geschenkverpackung anbieten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, Geschenk-Service, Geschenkverpackung, Artikel verpacken, Verpackung
:position: 30

Mit dem Geschenk-Service bieten Sie Kunden die Möglichkeit, bestellte Artikel in Geschenkpapier einpacken zu lassen. Hier erfahren Sie, wie Sie den Geschenk-Service in plentymarkets einrichten.

== Artikel für Geschenkverpackung erstellen

Legen Sie für jede Art der Geschenkverpackung, die Sie im Bestellvorgang anbieten möchten, einen Artikel an.

[.instruction]
Artikel für Geschenkverpackung erstellen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Klicken Sie auf **Neu**.
. Geben Sie einen **Namen** ein, z.B. Geschenkfolie.
. Geben Sie einen **Preis** ein.
. Wenn Sie die Geschenkverpackung in verschiedenen Farben anbieten möchten, legen Sie Varianten an.
. **Speichern** Sie die Einstellungen.

[TIP]
.Tipp
====
Tragen Sie den **Bestand** ausreichend hoch ein, damit der Service immer zur Verfügung steht.
====

== Artikel verknüpfen und Funktion aktivieren

Verknüpfen Sie nun die Geschenkartikel, die Sie im Bestellvorgang anbieten möchten, mit dem Geschenk-Service und aktivieren Sie die Funktion. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Artikel für Geschenkverpackung verknüpfen und Geschenk-Service aktivieren:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Mandant öffnen » Globale Einstellungen » Geschenk-Service**.
. Geben Sie den Namen ein, der im Bestellvorgang angezeigt werden soll.
. Geben Sie die ID des Artikels für die Geschenkverpackung ein.
. Stellen Sie die Option **Aktiv** auf **Ja**.
. **Speichern** Sie die Einstellungen. +
→ Die Geschenkartikel werden Kunden im Bestellvorgang angeboten.

== Anzeige im Warenkorb

Im Bestellvorgang werden die verfügbaren Artikel für Geschenkverpackung angezeigt, nachdem Kunden auf den Link **Geschenkservice auswählen** klicken.

== Anzeige in der Auftragsübersicht und auf der Rechnung

In der Auftragsübersicht und auf der Rechnung steht die Artikelposition der Geschenkverpackung direkt unterhalb der Artikelposition des Artikels, für den die Geschenkverpackung bestellt wurde.
