= Aktualität von Artikeldaten prüfen
:lang: de
include::{includedir}/_header.adoc[]
:position: 50
:url: artikel/artikeldaten-status-pruefen
:id: 4

Wenn du viele Artikeldaten gleichzeitig änderst oder viele neue Artikel gleichzeitig erstellst, sind diese Änderungen aufgrund des technischen Aufbaus von plentymarkets in den folgenden Bereichen von plentymarkets nicht sofort verfügbar:

* Artikelanzeige in Ceres
* Artikelsuche in Ceres
* Artikeldaten im Elastischen Export

Wie groß diese Verzögerung ist, hängt davon ab, wie viele Artikel erstellt und/oder geändert wurden:

* Wenn du einen oder wenige Artikel manuell im plentymarkets Backend erstellst oder aktualisierst, dauert es ungefähr 15 Minuten, bis die Änderungen im Shop sichtbar ist und im Elastischen Export berücksichtigt werden.
* Wenn du viele Artikel erstellst oder aktualisierst, zum Beispiel per Stapelverarbeitung oder Import, dauert es unter Umständen sehr lang, bis die Änderungen im Webshop sichtbar sind und im Elastischen Export berücksichtigt werden. Wie lang der Vorgang tatsächlich dauert, ist davon abhängig, welche Änderungen vorgenommen wurden und wie viele Varianten von den Änderungen betroffen sind.

== Technischer Hintergrund zur Aktualität von Artikeldaten

Die Artikeldaten werden in einer Datenbank gespeichert. Da das Auslesen dieser Daten aber zu lang dauern würde, werden diese Daten in ElasticSearch zwischengespeichert. Die Artikelansicht und Artikelsuche in Ceres und der Elastische Export beziehen Artikeldaten nicht aus der Datenbank, sondern aus ElasticSearch. So werden im Webshop Suchergebnisse schneller gefunden und Artikeldaten schneller geladen. Auch der Elastische Export wird durch ElasticSearch beschleunigt. Die Dauer der Aktualisierung der Daten in ElasticSearch hängt von der Anzahl der geänderten Artikel ab.

== Aktualität von Artikeldaten prüfen

Gehe wie unten beschrieben vor, um die Aktualität von Artikeldaten zu prüfen. Die Anzeige informiert über die Aktualität der folgenden Artikeldaten:

* Artikeldaten im Elastischen Export
* Artikelsuche in Ceres
* Artikelanzeige in Ceres

[.instruction]
Aktualität der Artikeldaten prüfen:

. Öffne das Menü *Daten » Status*. +
→ Das Menü *Status* wird angezeigt. +
→ Im Bereich *Artikeldaten in ElasticSearch* wird angezeigt, wie viel Prozent der Variantendaten aktuell sind. <<tabelle-aktualitaet-status>> erläutert die verschiedenen Status. +
. Die Statusanzeige wird nicht automatisch aktualisiert. Klicke auf *Neu laden*, um den Fortschritt zu beobachten. +
*_Hinweis:_* Der plentymarkets Support hat keinen Einfluss darauf, wie schnell die Daten aktualisiert werden.


[[tabelle-aktualitaet-status]]
.Status der Artikeldaten
[cols="1,3"]
|====
|Status |Erläuterung

|*Aktuell*
|Die Artikeldaten sind aktuell.

|*Geändert*
|Vorhandene Artikel wurden geändert. +
→ Die Änderungen sind im Ceres Webshop und im Elastischen Export noch nicht verfügbar.

|*Neu*
|Neue Artikel wurden erstellt. +
→ Die neuen Artikel sind im Ceres Webshop und im Elastischen Export noch nicht verfügbar.
|====

== Vorschau von Artikeln oder Varianten anzeigen

Nutze die Vorschaufunktion, um einzelne Artikel oder Varianten auch sofort nach dem Erstellen oder einer Änderung anzuzeigen.

[.instruction]
Vorschau von Artikeln oder Varianten anzeigen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel. +
→ Das Tab *Einstellungen* der Hauptvariante wird geöffnet.
. Um eine Vorschau des Artikels anzuzeigen, klicke in der Speicherzeile des Artikels auf das Augensymbol.
. Um eine Vorschau einer Variante anzuzeigen, wechsele in das Tab der Variante und klicke in der Speicherzeile der Variante auf das Augensymbol. +
→ Das Fenster *Mandant (Shop)* wird angezeigt. +
.. Wähle in der Dropdown-Liste das *Plugin Set*, in dem du die Vorschau anzeigen möchtest.
.. Wähle in der Dropdown-Liste den *Mandant (Shop)*, in dem du die Vorschau anzeigen möchtest. +
*_Tipp:_* Die Einstellungen bleiben erhalten, wenn du die Vorschau das nächste Mal öffnest.
. Klicke auf *Ausführen*. +
→ Eine Vorschau des Artikels oder der Variante wird angezeigt.
