= Aktualität von Artikeldaten prüfen
:lang: de
include::{includedir}/_header.adoc[]
:position: 50

Wenn Sie viele Artikeldaten gleichzeitig ändern oder viele neue Artikel gleichzeitig erstellen, sind diese Änderungen aufgrund des technischen Aufbaus von plentymarkets in den folgenden Bereichen von plentymarkets nicht sofort verfügbar:

* Artikelanzeige in Ceres
* Artikelsuche in Ceres
* Artikeldaten im Elastischen Export

Wie groß diese Verzögerung ist, hängt davon ab, wie viele Artikel erstellt und/oder geändert wurden:

* Wenn Sie einen oder wenige Artikel manuell im plentymarkets Backend erstellen oder aktualisieren, dauert es ungefähr 15 Minuten, bis die Änderungen im Shop sichtbar ist und im Elastischen Export berücksichtigt werden.
* Wenn Sie viele Artikel erstellen oder aktualisieren, zum Beispiel per Stapelverarbeitung oder Import, dauert es unter Umständen sehr lang, bis die Änderungen im Webshop sichtbar sind und im Elastischen Export berücksichtigt werden. Wie lang der Vorgang tatsächlich dauert, ist davon abhängig, welche Änderungen vorgenommen wurden und wie viele Varianten von den Änderungen betroffen sind.

== Technischer Hintergrund zur Aktualität von Artikeldaten

Die Artikeldaten werden in einer Datenbank gespeichert. Da das Auslesen dieser Daten aber zu lang dauern würde, werden diese Daten in ElasticSearch zwischengespeichert. Die Artikelansicht und Artikelsuche in Ceres und der Elastische Export beziehen Artikeldaten nicht aus der Datenbank, sondern aus ElasticSearch. So werden im Webshop Suchergebnisse schneller gefunden und Artikeldaten schneller geladen. Auch der Elastische Export wird durch ElasticSearch beschleunigt. Die Dauer der Aktualisierung der Daten in ElasticSearch hängt von der Anzahl der geänderten Artikel ab.

== Aktualität von Artikeldaten prüfen

Gehen Sie wie unten beschrieben vor, um die Aktualität von Artikeldaten zu prüfen. Die Anzeige informiert über die Aktualität der folgenden Artikeldaten:

* Artikeldaten im Elastischen Export
* Artikelsuche in Ceres
* Artikelanzeige in Ceres

[.instruction]
Aktualität der Artikeldaten prüfen:

. Öffnen Sie das Menü *Daten » Status*. +
→ Das Menü *Status* wird angezeigt. +
→ Im Bereich *Artikeldaten in ElasticSearch* wird angezeigt, wie viel Prozent der Variantendaten aktuell sind. <<tabelle-aktualitaet-status>> erläutert die verschiedenen Status. +
. Die Statusanzeige wird nicht automatisch aktualisiert. Klicken Sie auf *Neu laden*, um den Fortschritt zu beobachten. +
*_Hinweis:_* Der plentymarkets Support hat keinen Einfluss darauf, wie schnell die Daten aktualisiert werden.


[[tabelle-aktualitaet-status]]
.Status der Artikeldaten
[cols="1,3"]
|====
|Status |Erläuterung

|*Aktuell*
|Die Artikeldaten sind aktuell.

|*Geändert*
|Vorhandene Artikel wurden geändert. +
→ Die Änderungen sind im Ceres Webshop und im Elastischen Export noch nicht verfügbar.

|*Neu*
|Neue Artikel wurden erstellt. +
→ Die neuen Artikel sind im Ceres Webshop und im Elastischen Export noch nicht verfügbar.
|====

== Vorschau von Artikeln und Varianten anzeigen

[.instruction]
Vorschau von Artikeln und Varianten anzeigen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel. +
→ Das Tab *Einstellungen* der Hauptvariante wird geöffnet.
. Um eine Vorschau des Artikels anzuzeigen, klicken Sie in der Speicherzeile des Artikels auf das Augensymbol.
. Um eine Vorschau des Artikels anzuzeigen, klicken Sie in der Speicherzeile der Variante auf das Augensymbol.
→ Das Fenster *Mandant (Shop)* wird angezeigt. +
. Wählen Sie in der Dropdown-Liste *Plugin Set*, in welchem Plugin-Set Sie die Vorschau anzeigen möchten.
. Wählen Sie in der Dropdown-Liste *Mandant (Shop)*, in welchem Mandanten Sie die Vorschau anzeigen möchten.
. Klicken Sie auf *Ausführen*.
