= Artikel manuell anlegen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Cross-Selling, Hersteller, Barcodes
:description: Erfahre, wie du Artikel in plentymarkets erstellst und verwaltest.
:position: 25
:url: artikel/artikel-verwalten
:id: ZVYHQWL

Nachdem du alle <<artikel/einstellungen#, vorbereitenden Einstellungen>> in plentymarkets konfiguriert hast, bist du bereit, deine Artikeldaten in plentymarkets einzupflegen. Diese Seite zeigt dir, wie du <<artikel/artikel-verwalten#20, Artikel manuell anlegst>>.

Es ist aber auch möglich, Artikel- und Variantendaten mit Hilfe eines <<basics/assistenten#, Assistenten>> zu importieren oder Produktdaten zwischen deinem plentymarkets System und anderen, externen Systemen auszutauschen. Du kannst Artikeldatensätze z.B.:

* aus vorhandenen <<maerkte/ebay/ebay-einrichten#11000, eBay-Listings>> importieren.
* in CSV-Dateien pflegen und mit <<daten/daten-importieren/ElasticSync#, ElasticSync>> importieren.
* aus externen Systemen mit der <<basics/admin-aufgaben/rest-api#, REST-API>> importieren.
* mit dem <<daten/daten-exportieren/FormatDesigner#, FormatDesigner>> aus plentymarkets exportieren.


[#20]
== Artikel des Typs Standard erstellen

Mit dem Erstellen von Kategorien ist die Voraussetzung geschaffen, um deine Produkte zu sortieren. Beim Erstellen eines neuen Artikels des Typs **Standard** wird automatisch die erste Variante erstellt. Diese Variante ist die Hauptvariante und sie ist fest mit dem Artikel des Typs **Standard** verbunden. Die Hauptvariante kann nur zusammen mit dem Standard-Artikel erstellt oder gelöscht werden. Erstelle nun neue Standardartikel.

[.instruction]
Artikel des Typs Standard erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Typ *Standard*.
. Gib einen Namen ein.
. Gib den Inhalt ein.
. Wähle eine Kategorie.
. *_Optional:_* Nimm weitere Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-standardartikel-erstellen>>.
. *Speichere* die Einstellungen. +
→ Der Artikel des Typs *Standard* mit Hauptvariante wird erstellt. +
→ Die Hauptvariante des Artikels wird in einem neuen Tab geöffnet.
*_Hinweis:_* Neue Artikel und Änderungen an Artikeldaten sind nicht sofort im Webshop und den Exporten verfügbar. +
*_Tipp:_* Zeige eine Vorschau des Artikels an:
  .. Klicke in der Speicherzeile des Artikels auf das Augensymbol. +
  → Das Fenster *Mandant (Shop)* wird angezeigt. +
  .. Wähle in der Dropdown-Liste das *Plugin Set*, in dem du die Vorschau anzeigen möchtest.
  .. Wähle in der Dropdown-Liste den *Mandant (Shop)*, in dem du die Vorschau anzeigen möchtest. +
  *_Tipp:_* Die Einstellungen bleiben erhalten, wenn du die Vorschau das nächste Mal öffnest.
  .. Klicke auf *Ausführen*. +
  → Eine Vorschau des Artikels wird angezeigt.

Statt im Menü *Artikel » Artikel bearbeiten* erstellst du einen neuen Artikel des Typs *Standard*, indem du im Menü *Artikel » Kategorien* auf den Pfeil neben einer <<artikel/einstellungen/kategorien#, Kategorie>> klickst. Klicke dann im eingeblendeten Kontextmenü auf *Neuen Artikel erstellen*.

[TIP]
.Artikel des Typs **Standard** in Übersicht anzeigen
====
Der neue Artikel des Typs **Standard** ist noch inaktiv. Um neue Artikel nach dem Erstellen in der Übersicht im Menü **Artikel » Artikel bearbeiten** anzuzeigen, wähle auf der linken Seite für den Filter **Aktiv** die Option **ALLE** und klicke auf **Suchen**. Wie du deine Artikel und Varianten für den Webshop aktivierst, erfährst du im Kapitel <<artikel/artikel-verwalten#180, Verfügbarkeit einstellen>>.
====

[[tabelle-standardartikel-erstellen]]
.Artikel des Typs **Standard** erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Artikeldaten*

|*Typ*
|Artikeltyp *Standard* wählen. +
*Standard* = Erstellt einen Artikel mit Hauptvariante. +
*Multipack* = Erstellt einen <<artikel/anwendungsfaelle/multipacks-pakete-sets#1000, Multipack-Artikel>>. +
*Set* = Erstellt einen <<artikel/anwendungsfaelle/multipacks-pakete-sets#3000, Setartikel>>. Setartikel können aktuell noch nicht im Webshop dargestellt werden. Daher wird das Erstellen von Setartikeln nicht empfohlen.

|**ID**
|Die Artikel-ID ist eine eindeutige, fortlaufende Zahl, die plentymarkets zur exklusiven Zuordnung jedes Artikels benötigt. Wird dieses Feld freigelassen, vergibt plentymarkets automatisch die nächste freie ID.

|**Hersteller**
|Hersteller wählen. Wie du Hersteller erstellst und verknüpfst, erfährst du unter <<artikel/einstellungen/hersteller#, Hersteller verwalten>>.

|**Name**
|Artikelname eingeben. Der Artikelname ist eine Pflichteingabe. Wie du den Artikelnamen änderst, erfährst du im Kapitel <<artikel/artikel-verwalten#50, Artikeltexte eingeben>>.

|**Markierung**
|Markierung wählen. Artikel können mit Hilfe von Markierungen gefiltert werden. Wie du Markierungen bearbeitest und verknüpfst, erfährst du unter <<artikel/einstellungen/markierungen#, Markierungen einrichten>> und <<artikel/artikel-verwalten#810, Artikel mit Markierungen versehen>>.

|**Warentyp**
|**Lagerware** (Standardeinstellung), **Produktionsware**, **Colli** oder **Bestellware** wählen. +
**Colli** = Wählen, wenn der Artikel in mehreren Packstücken versendet wird. Weitere Packstücke müssen als eigene Artikel mit dem Warentyp Colli in plentymarkets erstellt werden, sollten aber nicht für den Webshop aktiviert werden.

2+|*Variantendaten*

|**Variantenname**
|Variantenname für die Hauptvariante eingeben.

|**Variantennr.**
|Die Variantennummer wird automatisch nach dem im Menü **Einrichtung » Artikel » Einstellungen** festgelegten Muster vergeben. Variantennummern sind nachträglich im Tab **Einstellungen** einer Variante änderbar.

|**Externe Varianten-ID**
|Externe Varianten-ID eingeben, die für die Hauptvariante des Artikels verwendet wird. Die externe Varianten-ID ist eine optionale Eingabe, die die Übernahme von Artikeln und Varianten aus einem externen System erleichtert. Externe Varianten-IDs sind nachträglich im Tab **Einstellungen** einer Variante änderbar.

|**Inhalt**
|Standardmäßig sind die Menge *1* und die <<artikel/einstellungen/einheiten#, Einheit>> *Stück* eingestellt. Einstellungen bei Bedarf anpassen. Der Inhalt ist eine Pflichteingabe.

|**Attribute**
|Attribute für die Hauptvariante wählen. Werden Attribute für die Hauptvariante gewählt, sind die gewählten Attribute für alle Varianten des Artikels verfügbar. Wenn ein Artikel des Typs **Standard** erstellt wird, ohne Attribute für die Hauptvariante zu wählen, können beim <<artikel/artikel-verwalten#160, Erstellen von Varianten>> alle im System verfügbaren Attribute gewählt werden. Sobald eine Variante mit Attributen erstellt wurde, können weitere Varianten nur noch mit diesen Attributen oder ohne Attribute erstellt werden.

|**Verkaufspreise**
|<<artikel/einstellungen/preise#, Verkaufspreise>> verknüpfen und Werte für verknüpfte Preise eingeben.
|====

[#30]
== Artikel des Typs Standard bearbeiten

Ein Artikel des Typs **Standard** setzt sich mindestens aus den globalen Einstellungen und den Daten der Hauptvariante zusammen. Optional erstellst du weitere Varianten. In diesem Kapitel erfährst du, wie du Artikel bearbeitest und welche Artikeldaten du variantenübergreifend pflegst.

=== Anzeige von Artikeldaten in Artikel-Tabs personalisieren

Standardmäßig wird in den Tabs von Artikeln die Artikel-ID angezeigt. Statt die Artikel-ID im Tab anzuzeigen, kannst du den Namen oder die Nummer der Hauptvariante des Artikels anzeigen lassen. Gehe wie unten beschrieben vor, um die angezeigten Artikeldaten zu ändern.

[.instruction]
Anzeige von Artikeldaten in Artikel-Tabs personalisieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne einen Artikel. +
→ Das Tab *Einstellungen* der Hauptvariante wird geöffnet.
. Zeige mit der Maus auf das Tab des Artikels.
. Klicke auf die rechte Maustaste. +
→ Eine Dropdown-Liste wird angezeigt.
. Klicke auf *Umbenennen*. +
→ Das Fenster *Tab-Titel wählen* wird angezeigt.
. Wähle, ob im Tab-Titel von Artikeln die *Artikel-ID*, der *Variantenname der Hauptvariante* oder die *Variantennummer der Hauptvariante* angezeigt werden soll.
. Klicke auf **Umbenennen**. +
→ Die gewählten Artikeldaten werden in allen Tabs angezeigt. +
→ Wenn *Variantenname der Hauptvariante* oder *Variantennummer der Hauptvariante* eingestellt wird und diese Daten für einen Artikel nicht gespeichert sind, wird stattdessen die *Artikel-ID* angezeigt. +
**__Tipp:__** Die Anzeige im Tab des aktuell geöffneten Artikels ändert sich erst, nachdem der Artikel neu geladen wird.

[#40]
=== Artikeldaten anpassen

Im Tab **Global** passt du die Artikeldaten an und nimmst Einstellungen für den Artikel des Typs **Standard** vor. Globale Einstellungen sind für alle Varianten des Artikels des Typs **Standard** gültig. Hier wählst du den Zustand des Artikels des Typs **Standard** und den <<artikel/einstellungen/hersteller#, Hersteller>>. Zudem aktivierst du hier <<fulfillment/versand-vorbereiten#1000, Versandprofile>> und <<artikel/webshop/shop-aktionen#, Shop-Aktionen>> für den Artikel des Typs **Standard**.

[TIP]
.Änderungen nicht sofort sichtbar
====
Neue Artikel und Änderungen an Artikeldaten sind nicht sofort im Webshop und den Exporten verfügbar. Wie du prüfst, ob die Artikeldaten aktuell sind, erfährst du auf der Handbuchseite <<artikel/anwendungsfaelle/artikeldaten-status-pruefen#, Aktualität von Artikeldaten prüfen>>.
====

[.instruction]
Artikeldaten anpassen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Klicke in der Zeile des Artikels auf **Artikel bearbeiten**. +
→ Das Tab **Global** des Artikels wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-globale-artikeleinstellungen>>.
. **Speichere** die Einstellungen. +
*_Hinweis:_* Neue Artikel und Änderungen an Artikeldaten sind nicht sofort im Webshop und den Exporten verfügbar. +
*_Tipp:_* Zeige eine Vorschau des Artikels an:
 .. Klicke in der Speicherzeile des Artikels auf das Augensymbol. +
 → Das Fenster *Mandant (Shop)* wird angezeigt. +
 .. Wähle in der Dropdown-Liste das *Plugin Set*, in dem du die Vorschau anzeigen möchtest.
 .. Wähle in der Dropdown-Liste den *Mandant (Shop)*, in dem du die Vorschau anzeigen möchtest. +
 *_Tipp:_* Die Einstellungen bleiben erhalten, wenn du die Vorschau das nächste Mal öffnest.
 .. Klicke auf *Ausführen*. +
 → Eine Vorschau des Artikels wird angezeigt.

[[tabelle-globale-artikeleinstellungen]]
.Globale Einstellungen am Artikel vornehmen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Grundeinstellungen*

|*Zustand*; +
*Zustand API*
|Zustand des Artikels wählen. Standardmäßig ist **Neu** eingestellt. Die Einstellung *Zustand API* wird für den Marktplatz <<maerkte/amazon/amazon-einrichten#, Amazon>> verwendet.

|**Warentyp**
|**Lagerware** (Standardeinstellung), **Produktionsware**, **Colli** oder **Bestellware** wählen. +
**Colli** = Wählen, wenn ein Artikel des Typs **Standard** in mehreren Packstücken versendet wird. Weitere Packstücke müssen als eigene Artikel des Typs **Standard** mit dem Warentyp Colli in plentymarkets erstellt werden, sollten aber nicht für den Webshop aktiviert werden.

|**Hersteller**
|<<artikel/einstellungen/hersteller#, Hersteller>> wählen.

|**Herstellungsland**
|Land wählen, in dem der Artikel des Typs **Standard** hergestellt wurde.

|**Zolltarifnummer**
|Zolltarifnummer eingeben. Weitere Informationen findest du zum Beispiel auf der Webseite von link:http://auskunft.ezt-online.de/ezto/Welcome.do[EZT-Online^].

|**Erlöskonto**
|<<auftraege/buchhaltung#650, Erlöskonto>> eingeben.

|*Max. Bestellmenge*
|Wert eingeben, um die Gesamtanzahl aller Varianten des Artikels zu begrenzen, die pro Auftrag bestellt werden können. +
0 = Pro Variante gilt die maximale Bestellmenge, die im Tab *Einstellungen* der Variante für die Option *Max. Bestellmenge* gespeichert wurde. +
Wert größer 0 = Pro Auftrag kan maximal diese Gesamtmenge aller Varianten des Artikels bestellt werden. Kommawerte sind möglich, um zum Beispiel Bestellungen nach Gewicht oder Länge abzubilden. Dieser Wert hat Priorität gegenüber der maximalen Bestellmenge der einzelnen Varianten des Artikels.

|**Altersfreigabe**
|Altersfreigabe für den Artikel des Typs **Standard** wählen. Für den Versand von Artikeln mit **Altersfreigabe 18** muss ein <<fulfillment/versand-vorbereiten#1000, Versandprofil>> verknüpft sein, bei dem die Option **PostIdent** aktiviert ist.

|*Aktionsgutschein/POS-Rabatt*
|*Möglich* = Beim Kauf einer Variante des Artikels kann ein Aktionsgutschein eingelöst werden. Beim Verkauf über plentymarkets POS kann Kassenpersonal einen Rabatt auf den Artikel geben. Kundenklassenrabatte werden automatisch angewendet. +
*Verboten* = Beim Kauf einer Variante des Artikels können keine Aktionsgutscheine eingelöst werden. Beim Verkauf über plentymarkets POS kann Kassenpersonal keinen Rabatt auf den Artikel geben. Kundenklassenrabatte werden nicht angewendet. +
*Nur mit Aktionsgutschein kaufbar* = Die Variant des Artikels kann nur gekauft werden, wenn der Code eines Aktionsgutscheins eingegeben wird. +
Weitere Informationen zu Aktionsgutscheinen findest du auf der Handbuchseite <<auftraege/gutscheine#, Gutscheine>>.

|**Abonnement**
|Wählen, ob ein Abonnement für den Artikel des Typs **Standard** verfügbar ist. Abonnements werden mit dem Scheduler abgebildet. Der Scheduler ist ein eigenes Modul in plentymarkets und ermöglicht das regelmäßige Zusenden von Artikeln. Das Menü für den Scheduler wird erst in plentymarkets sichtbar, wenn du das **link:http://www.plentymarkets.eu/preise/[Modul gebucht]** hast. Wie du Abonnements einrichtest, erfährst du auf der Handbuchseite <<auftraege/scheduler#scheduler-auftraege, Scheduler-Aufträge>>.

|**Versandpaket**
|Versandpaket verwenden. Versandpakete haben festgelegte Maße. Wenn du die Maße des Artikels im Tab **Einstellungen** einer Variante eingibst, erfolgt automatisch die Zuordnung des passenden Versandpakets. Wie du Versandpakete einrichtest, erfährst du auf der Handbuchseite <<fulfillment/versand-vorbereiten#1900, Versandpakete>>.

|**Seriennummer**
|Sollte es möglich sein, die <<artikel/anwendungsfaelle/seriennummern#800, Seriennummer dieses Artikels während eines Prozesses>> zu scannen?

2+|*Versandprofile*

|**Versandprofile**
|Ein, mehrere oder **ALLE** <<fulfillment/versand-vorbereiten#1000, Versandprofile>> aktivieren. Standardmäßig ist kein Versandprofil aktiviert. Pro Artikel mindestens ein Versandprofil aktivieren, da sonst ungewollte Effekte bei der Versandkostenberechnung auftreten können. Wenn ein Auftrag Artikel enthält, bei denen kein Versandprofil aktiviert wurde, wird das Standard-Versandprofil aus dem Standard-Webshop für die Artikel verwendet. Wenn kein Standard-Versandprofil festgelegt ist, wird das Versandprofil mit der höchsten Priorität verwendet.

2+|*Webshop*

|*Shop-Aktion*
|Shop-Aktion oder *Keine* wählen. Artikel können als <<artikel/webshop/shop-aktionen#, Shop-Aktionen in deinem Webshop>> dargestellt werden. +
*Sonderangebot* = Stellt eine Liste von Sonderangeboten dar. +
*Neuheit* = Stellt eine Liste der neuesten Artikel dar. +
*Top-Artikel* = Stellt eine Liste der meistverkauften Artikel dar.

|**Artikelbewertung**
|Erstbewertung von **1** bis **5** oder **1** bis **10** für den Artikel eingeben. Wenn du Artikelbewertungen verwendest, wird der eingegebene Wert als Erstbewertung des Artikels angezeigt. Der Wert wird nach jeder Bewertung automatisch auf einen Durchschnittswert angepasst. Den Bewertungsbereich legst du im Menü **Einrichtung » Mandant » Global » Feedback » Tab: Artikel** unter **Maximale Bewertungspunkte** fest.

2+|*Artikelbild*

|**Artikelbild**
|Auf das Bild klicken, um das Tab **Bilder** aufzurufen.
|====


[#610]
=== Hersteller verknüpfen

Hersteller verknüpfst du entweder beim <<artikel/artikel-verwalten#20, Erstellen eines Artikels des Typs Standard>> oder bei bestehenden Artikeln des Typs **Standard** im Tab **Global**.

[.instruction]
Hersteller verknüpfen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Klicke in der Zeile des Artikels des Typs **Standard** auf **Artikel bearbeiten**. +
→ Das Tab **Global** des Artikels des Typs **Standard** wird geöffnet.
. Wähle im Bereich **Grundeinstellungen** den **Hersteller** aus der Dropdown-Liste.
. **Speichere** die Einstellungen. +
→ Der Hersteller wird mit dem Artikel des Typs **Standard** verknüpft.

[#45]
=== Marktplatzeinstellungen am Artikel des Typs Standard vornehmen

Im Tab **Multi-Channel** nimmst du Einstellungen für die Marktplätze <<maerkte/amazon/amazon-einrichten#, Amazon>>, <<maerkte/ebay/ebay-einrichten#, eBay>> und <<maerkte/neckermann/neckermann-at-einrichten#, Neckermann.at>> vor. Zudem verknüpfst du hier deine Kategorien mit den Kategorien von Marktplätzen. Einstellungen dieses Bereichs werden im Themenbereich <<maerkte#, Multi-Channel>> verwendet und bei den Marktplätzen näher erläutert.

[IMPORTANT]
.Marktplätze: nur Artikel des Typs Standard
====
Auf Marktplätzen können nur Artikel des Typs **Standard** angeboten werden. Artikel des Typs **Set** können nicht an Marktplätze übertragen werden.
====

[#50]
=== Artikeltexte eingeben

Im Tab **Texte** gibst du die Artikeltexte ein. Neben dem Vorschautext gibst du die Artikelbeschreibung und weitere Texte ein, zum Beispiel technische Daten und Keywords.

[.instruction]
Artikeltexte eingeben:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Wechsele in das Tab **Texte**.
. Wähle die Sprache.
. Gib die Artikeltexte ein. Beachte dazu die Erläuterungen in <<tabelle-artikeltexte-eingeben>>.
. **Speichere** die Einstellungen.

[[tabelle-artikeltexte-eingeben]]
.Artikeltexte eingeben
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Sprache**
|Sprache unter **Sprache öffnen** wählen, um Artikeltexte in dieser Sprache einzugeben. Unter **Sprache speichern** wird automatisch die gleiche Sprache eingestellt. Um Texte einer Sprache auch in einer anderen Sprache zu verwenden, unter **Sprache speichern** eine andere Sprache wählen.

|**Texte für Sprache löschen**
|Texte der unter **Sprache öffnen** gewählten Sprache löschen. Alle Textfelder werden geleert.

|**Name 1; +
Name 2; +
Name 3**
|Name des Artikels eingeben. +
**Name 1** = Standardname des Artikels, der im Webshop und bei Artikeln des Typs **Standard** auch auf Marktplätzen verwendet wird. +
**Name 2**; **3** = Alternativer Artikelname, der zum Beispiel für Marktplätze verwendet werden kann. +
Die Länge des Artikelnamens ist auf 240 Zeichen begrenzt. Der Artikelname wird für den Aufbau der Artikel-URL verwendet. Weitere Informationen zur Artikel-URL findest du in unserem <<webshop/webshop-einrichten/cms-syntax#fallbeispiele-seo-guide, SEO-Guide>>.

|**Vorschautext**
|Vorschautext eingeben. Der Vorschautext ist ein kurzer Text, der in Artikellisten angezeigt werden kann. Der Vorschautext kann im HTML-Format oder als Klartext eingegeben werden.

|**Artikeltext**
|Artikeltext eingeben. Der Artikeltext ist ein detaillierter Text, der in der Artikelansicht im Webshop angezeigt wird.

|**Technische Daten**
|Technische Daten des Artikels eingeben.

|**URL-Pfad**
|URL-Pfad des Artikels im Webshop. Der URL-Pfad setzt sich standardmäßig aus Kategorien und Artikelname zusammen. Der Pfad wird beim Erstellen des Artikels automatisch von plentymarkets vergeben und als Teil der Artikel-URL angezeigt, wenn der Artikel im Webshop aufgerufen wird.

|**Meta-Beschreibung**
|Beschreibung eingeben, mit der der Artikel leichter von Suchmaschinen gefunden wird (max. 350 Zeichen).

|**Meta-Keywords**
|Schlüsselwörter eingeben, mit denen der Artikel leichter von Suchmaschinen gefunden wird.

|**Artikelvorlage**
|<<artikel/webshop/callisto-vorlagen#, Artikelvorlage>> wählen, um das Aussehen der Artikelansicht zu bestimmen.
|====

[#60]
=== Artikeltexte suchen und ersetzen

Im Menü **Suchen &amp; Ersetzen** suchst du Artikeltexte in der Datenbank und ersetzt die Ergebnisse mit neuen Texten.

[.instruction]
Artikeltexte suchen und ersetzen:

. Öffne das Menü **Artikel » Suchen &amp; Ersetzen**.
. Wähle das Datenbankfeld.
. Gib den Text in das Suchfeld ein. Beachte die Groß-/Kleinschreibung.
. Gib den neuen Text in das Feld **Ersetzen mit** ein.
. Klicke auf **Suchen**. +
→ Die Anzahl der gefundenen Artikel wird angezeigt.
. Klicke auf **Alle ersetzen**. +
→ Alle Texte werden durch die neuen Texte ersetzt.

[#70]
=== Freitextfelder aktivieren

Füge Freitextfelder in die Artikelansicht von Artikeln des Typs **Standard** ein. In Freitextfelder können bei einer Bestellung Werte eingegeben werden, zum Beispiel ein Zusatzwunsch oder Maße. Definiere zunächst die Freitextfelder.

[.instruction]
Freitextfelder definieren:

. Öffne das Menü **Einrichtung » Artikel » Freitextfelder**.
. Gib eine Feldbezeichnung ein.
. Wähle den Datentyp. Beachte dazu die Erläuterungen in <<tabelle-freitextfelder-definieren>>.
. Gib die Zeichenlänge ein.
. **Speichere** die Einstellungen.

[[tabelle-freitextfelder-definieren]]
.Freitextfelder definieren
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Feldbezeichnung**
|Bezeichnung für das Freitextfeld eingeben. Die Feldbezeichnung darf keine Sonderzeichen enthalten. Wenn die Feldbezeichnung eines Freitextfeldes geändert wird, wird der Inhalt des Freitextfeldes nicht automatisch gelöscht. Der Feldinhalt muss manuell oder per CSV-Datei angepasst werden.

|**Datentyp**
|Datentyp wählen. +
**Kleine Zahl** = Für numerische Werte von 0 bis ± 127. +
**Zahl** = Für numerische Werte von 0 bis ± 2147483647. +
**Zeichenkette** = Für alphanumerische Werte bis zu einer Länge von 142 Zeichen. +
**Text** = Für Texteingaben bis zu einer Länge von 65535 Zeichen. +
**Checkbox** = Bedienelement zum Aktivieren und Deaktivieren von Funktionen.

|**Zeichenlänge**
|Maximale Zeichenlänge eingeben. Die Zeichenlänge ist besonders für Zeichenketten wichtig. Bei größerer Zeichenlänge verlangsamt sich die Suche nach Werten in diesem Datenfeld. Hier sollte nicht pauschal die maximal verfügbare Zeichenlänge eingegeben werden, sondern eine realistische Länge, um Datenbankressourcen zu schonen.
|====

Nachdem du Freitextfelder definiert hast, aktiviere diese Freitextfelder im Tab **Felder** eines Artikels des Typs **Standard**.

[.instruction]
Freitextfelder aktivieren:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**.
. Wechsele in das Tab **Felder**.
. Gib Werte in die benötigten Freitextfelder ein.
. **Speichere** die Einstellungen.

[#80]
=== Merkmale aktivieren

<<artikel/einstellungen/eigenschaften#100, Merkmale sind Artikelcharakteristiken>>, die du im Tab **Merkmale** aktivierst. Verknüpfe beliebig viele Merkmale mit einem Artikel des Typs **Standard**. Anhand der verknüpften Merkmale ist die Merkmalsuche im Webshop möglich.

[.instruction]
Merkmal mit Artikel des Typs Standard verknüpfen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**.
. Wechsele in das Tab **Merkmale**.
. Aktiviere Merkmale unter **Weitere Merkmale aktivieren**.
. **Speichere** die Einstellungen. +
→ Die Merkmale werden im Bereich **Merkmale** angezeigt.
. *_Optional:_* Nimm weitere Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-merkmal-verknuepfen>>.
. **Speichere** die Einstellungen.

[[tabelle-merkmal-verknuepfen]]
.Merkmal mit Artikel des Typs Standard verknüpfen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Name**
|Merkmalgruppe und Name des Merkmals werden angezeigt. Bei Merkmalen, die keiner Merkmalgruppe zugeordnet sind, wird nur der Name des Merkmals angezeigt.

|**Typ**
|Typ des Merkmals.

|**Standardsprache**
|Wert eingeben, der dem Merkmal zugeordnet wird. Der Merkmalwert ist entweder voreingestellt oder muss hier eingegeben werden. Merkmalwerte werden in der Artikelansicht im Webshop angezeigt.

|Sprachwahl
|Sprache wählen, um eine Übersetzung des Werts einzugeben. Eingabe ist nur für den Merkmaltyp **Text** möglich. Standardmaßig wird die Standardsprache zur Bearbeitung angezeigt.

|**Cross-Selling**
|Aktivieren, um Cross-Selling zwischen diesem Artikel des Typs **Standard** und anderen Artikeln des Typs **Standard** mit dem gleichen Merkmal und Merkmalwert zu ermöglichen.

|**Aufpreis**
|Wenn für das Merkmal oder den Merkmalwert ein Aufpreis eingegeben wurde, wird der Aufpreis angezeigt.
|====


[#90]
=== Artikelbilder hochladen

Im Tab **Bilder** des Artikels lädst du Artikelbilder hoch. Die für Bilder unterstützten Dateiformate sind **PNG**, **JPG**, **GIF** und **SVG**.

[NOTE]
.Zulässige Zeichen für Dateinamen
====
Die Dateinamen von Bildern dürfen folgende Zeichen enthalten:

* Buchstaben (a-z, A-Z) ohne Umlaute
* Zahlen (0-9)
* Unterstriche (_)
* Bindestriche (-)

Leerzeichen und Sonderzeichen sind nicht zulässig. Beim Hochladen der Bilddatei werden Leerzeichen und Sonderzeichen durch Bindestriche (-) ersetzt.
====

Ziehe neue Bilder entweder per Drag &amp; Drop-Funktion in den Bereich **Neues Bild einfügen** oder lade die Bilder wie folgt hoch.

[.instruction]
Artikelbild hochladen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Wechsele in das Tab **Bilder**.
. Klicke auf **Dateien auswählen**.
. Wähle die Datei, die du hochladen möchtest.
. Klicke auf **Öffnen**. +
→ Die Datei wird hochgeladen und in der Übersicht angezeigt.
. Nimm weitere Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-artikelbild-hochladen>>.
. **Speichere** die Einstellungen. +
→ Das Bild wird hochgeladen und kann mit den Varianten des Artikels verknüpft werden.

[[tabelle-artikelbild-hochladen]]
.Artikelbild hochladen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Position**
|Positionsnummer des Bildes eingeben. Bilder werden anhand der Position im Webshop sortiert.

|**Verfügbarkeit**
|Option ist nur bei Artikeln des Typs **Standard** wählbar. Marktplätze aktivieren, um den Bilderexport und die Sichbarkeit für die <<maerkte#, Marktplätze>> zu ermöglichen.

|**Marktplatzattributverknüpfung**
|Attributwert wählen, um das Artikelbild für Marktplätze mit diesem Attributwert zu verknüpfen. Das Bild wird nur für Artikelvarianten mit diesem Attributwert an Marktplätze übertragen. +
__**Hinweis:**__ Option wird nur angezeigt, wenn das Bild mit mindestens einer Variante verknüpft ist.

|**Alternativtext; +
Name**
|*_Optional:_* Alternativtext und Name eingeben. Eingaben in den beiden Feldern verbessern die Indizierung durch Suchmaschinen für die Artikel. Passende Keywords in den Bildnamen verwenden, um die Bilder SEO-technisch aufzubereiten. Dadurch wird auch der Traffic der Seite erhöht, wenn das Bild zum Beispiel über die Google-Bildersuche gefunden wird.

|**Größe**
|Zeigt die Größe des Bildes in Pixeln und in Kilobytes an.
|====

[IMPORTANT]
.Größe des Artikelbilds beachten
====
Für jedes hochgeladene Artikelbild legt plentymarkets folgende Versionen an:

* Artikelbild mit hoher Auflösung
* Mittelgroßes Artikelbild
* Artikelattributbild
* Zwei Vorschaubilder

Das Quellbild muss mindestens die unter <<artikel/einstellungen/bilder#500, Größen>> festgelegte Bildgröße haben, da plentymarkets Bilder nicht größer rechnet. Größere Bilder werden auf die festgelegte Größe skaliert.
====

Große Mengen an Bildern kannst du statt im plentymarkets Backend auch <<artikel/einstellungen/bilder#600, per FTP-Server hochladen>>.

[#100]
=== Cross-Selling aktivieren

Im Tab <<artikel/webshop/cross-selling#, Cross-Selling>> verknüpfst du Artikel des Typs **Standard** mit beliebig vielen ähnlichen Artikeln aus deinem Sortiment.

[#110]
=== Dateien zum Download bereitstellen

NOTE: Im Tab *Media* hochgeladene Dateien können für den Ceres-Webshop nicht genutzt werden.

Im Tab *Media* fügst du Dateien zum Artikel hinzu. Dateien wie Produktinformationen oder Datenblätter stellst du im Bereich **Mein Konto** oder in der Artikelansicht im Webshop zum Download bereit. Für Dateien, die du im Tab **Media** hochlädst, gelten folgende Voraussetzungen:

* Alten Webshop Callisto
* *Zulässige Dateiformate:* PDF, EXCEL, X_EXCEL, DOC, DOCX, MSWORD, RTF, TEXT, RICHTEXT, ZIP, HTML, SWF
* *Maximale Dateigröße:* 10 MB pro Datei
* *Maximale Dateianzahl:* 10 Dateien pro Artikel (davon maximal 1 Datei im SWF-Format)

[#120]
==== Dateien hochladen

Um Dateien im Tab *Media* hochzuladen, gehe wie folgt vor. Lege dann fest, in welchen Bereichen die Dateien verfügbar sein sollen.

[.instruction]
Datei hochladen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Media*.
. Klicke auf *Dateien auswählen*.
. Wähle die Datei, die du hochladen möchtest.
. Klicke auf *Öffnen*. +
icon:map-signs[] *_Oder:_* Ziehe eine oder mehrere Dateien per Drag &amp; Drop-Funktion in den Bereich *Neues Dokument einfügen*. +
→ Die Datei wird hochgeladen und in der Übersicht angezeigt.
. Nimm die Einstellungen vor. Beachte <<tabelle-datei-hochladen>>.
. *Speichere* die Einstellungen.

[[tabelle-datei-hochladen]]
.Datei hochladen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Titel**
|Titel der Datei bei Bedarf ändern.

|**Größe**
|Hier wird die Dateigröße angezeigt.

|**E-Mail**
|Diese Einstellung ist ohne Funktion.

|**Mein Konto**
|Aktivieren, um die Datei im Bereich **Mein Konto** zum Download bereitzustellen.

|**CMS**
|Aktivieren, um die Datei im alten Webshop Callisto verfügbar zu machen.
|====

[#130]
==== Download-Link im Webshop einbinden

Um Download-Links zu den im Tab **Media** gespeicherten Dateien im Webshop bereitzustellen, verwende im alter Webshop Callisto die Template-Funktion **GetDocumentLinks()**. Diese Template-Funktion kann in den Templates im Ordner **ItemView** verwendet werden. Die Funktion liefert eine Liste mit Links, über die die gespeicherten Dokumente heruntergeladen werden können.

[.instruction]
Template-Funktion einfügen:

. Öffne das Menü **CMS » Webdesign**.
. Öffne ein Template im Ordner **Layout » ItemView**.
. Füge das Code-Beispiel in das Template ein.
. **Speichere** die Einstellungen. +
→ Eine Liste der Download-Links wird an dieser Stelle im Webshop angezeigt.

[source,plenty]
----
include::assets/EX-DE-GetDocumentLinks.html[]

----
[TIP]
.Tipp: Liste der Download-Links auf bestimmte Dateitypen beschränken
====
Beschränke die Liste der Download-Links auf bestimmte Dateitypen, indem du eine Dateiendung angibst. Die Template-Funktion **GetDocumentLinks(".pdf")** liefert zum Beispiel nur Download-Links der gespeicherten PDF-Dateien.
====

[#140]
=== Artikelstatistik anzeigen

Im Tab **Statistik** hast du die Möglichkeit, statistische Daten zum Artikel des Typs **Standard** auszuwerten. Zum Beispiel stehen Statistiken zur Verfügung, mit denen du die Umsätze des Artikels des Typs **Standard** anhand verschiedener Kriterien beurteilen kannst. Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#90, Artikelstatistiken>>.

[#810]
=== Artikel des Typs Standard mit Markierungen versehen

Versehe Artikel des Typs **Standard** mit bis zu zwei <<artikel/einstellungen/markierungen#, Markierungen>>.

////
[TIP]
.Tags verwenden
====
Markierungen können nur für Artikel verwendet werden. Verwende statt Markierungen die flexibleren <<artikel/artikel-verwalten#150, Tags>>, die du mit Varianten verknüpfen kannst.
====
////

[.instruction]
Artikel des Typs Standard mit Markierung versehen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**.
. Klicke in der Symbolleiste rechts auf die ausgegraute Schaltfläche. +
→ Eine Dropdown-Liste wird geöffnet.
. Wähle die Markierung aus der Dropdown-Liste.
. **Speichere** die Einstellungen.

[#155]
== Mehrere Artikel bearbeiten

Mehrere Artikel bearbeitest du per **Artikel-Gruppenfunktion** oder per **Stapelverarbeitung** im Menü **Artikel**. Bei der Gruppenfunktion werden zuvor gewählte Artikel bearbeitet. Bei der Stapelverarbeitung werden zuvor gefilterte Artikel bearbeitet.

[TIP]
.Welche Methode anwenden?
====
Je nachdem, welche und wie viele Artikel du bearbeiten möchtest, ist entweder die Gruppenfunktion oder die Stapelverarbeitung die geeignetere und schnellere Methode. Wenn du zum Beispiel die Artikel eines bestimmten Herstellers anpassen möchtest, verwende die **Stapelverarbeitung** mit dem Filter **Hersteller**. So kannst du alle Artikel eines Herstellers bearbeiten, ohne diese Artikel vorher zu wählen. Wenn mehrere Artikel angepasst werden sollen, die nicht durch einen **Filter** gruppiert werden können, verwende die **Gruppenfunktion**.
====

[.instruction]
Artikel-Gruppenfunktion ausführen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Wähle die zu bearbeitenden Artikel.
. Klicke auf **Artikel-Gruppenfunktion**. +
→ Das Fenster **Artikel-Gruppenfunktion** wird geöffnet.
. Nimm die Einstellungen gemäß <<tabelle-mehrere-artikel-bearbeiten>> vor.
. Klicke auf **Ausführen**, um die Einstellungen auf die Artikel anzuwenden.

[[tabelle-mehrere-artikel-bearbeiten]]
.Artikel per **Gruppenfunktion** oder per **Stapelverarbeitung** bearbeiten
[cols="1,2"]
|====
| Einstellung | Erläuterung

2+| *Multi-Channel*

|**Multi-Channel**
|Einstellungen dieses Bereichs werden im Themenbereich <<maerkte#, Multi-Channel>> verwendet und bei den Marktplätzen erläutert.

2+| *Merkmale*

|**Verknüpfung erstellen**
|Merkmalverknüpfung aktivieren oder deaktivieren. Die Merkmalverknüpfung kann außerdem für **Cross-Selling** aktiviert werden.

2+| *Aktionen*

|**Artikel löschen**
|Aktivieren, um die gewählten Artikel samt Varianten zu löschen.

|**Artikelbilder löschen**
|Aktivieren, um alle Artikelbilder der gewählten Artikel zu löschen.

|**Zweites Artikelbild löschen**
|Aktivieren, um das zweite Artikelbild der gewählten Artikel zu löschen.

|**Listing anlegen**
|Aktivieren, um für die gewählten Artikel Listings zu erstellen.

2+| *Versand*

|**Alte Versandprofile löschen**
|Aktivieren, um alte Versandprofile zu löschen.

|**Zolltarifnummer**
|Aktivieren und Nummer eingeben, um diese Nummer für die gewählten Artikel zu speichern.

|**Herstellungsland**
|Aktivieren und Land wählen, in dem die Artikel hergestellt wurden.

|**Versandkonfiguration**
|Aktivieren und ein, mehrere oder **ALLE** Versandprofile aktivieren. Bereits aktivierte Profile mit der Einstellung **Alte Versandprofile löschen** entfernen.

|**Zustand**
|Aktivieren und Zustand der Artikel wählen.

2+| *Global*

|**Seriennummer**
|Aktivieren und **Ja** wählen, um Seriennummern zur eindeutigen Kennzeichung der verkauften Artikel zu verwenden.

|**Artikelvorlage**
|Aktivieren und Artikelvorlage wählen.

|**Hersteller**
|Aktivieren und Hersteller wählen.

|**Markierung 1; +
Markierung 2**
|Aktivieren und Markierung wählen.

|**Erlöskonto**
|Aktivieren und Erlöskonto eingeben.

2+| *Freitextfelder*

|**Freitextfeld**
|Aktivieren und Wert eingeben, um diesen Wert für die gewählten Artikel zu speichern.
|====

[.instruction]
Stapelverarbeitung ausführen:

. Öffne das Menü **Artikel » Stapelverarbeitung**.
. Wähle die Filter gemäß <<tabelle-stapelverarbeitung-filter>>.
. Nimm die Einstellungen gemäß <<tabelle-mehrere-artikel-bearbeiten>> vor.
. Klicke auf **Anwenden**, um die Einstellungen an den Artikeln vorzunehmen.

[[tabelle-stapelverarbeitung-filter]]
.Filteroptionen für die **Stapelverarbeitung**
[cols="1,2"]
|====
| Einstellung | Erläuterung

|**Artikel-ID**
| Operator wählen und eine ID eingeben, um nach dem Artikel mit dieser ID zu suchen.

|**Markierung 1; +
Markierung 2**
| Markierung wählen, um nur Artikel mit dieser Markierung zu bearbeiten.

|**Hersteller**
| Einen Hersteller oder **ALLE** wählen, um nur Artikel zu bearbeiten, die vom gewählten Hersteller stammen.

|**Zustand**
|Zustand wählen, um nur Artikel mit diesem Zustand zu bearbeiten.

|**Ohne Kategorie**
|Aktivieren, um nur Artikel zu bearbeiten, die nicht mit einer Kategorie verknüpft sind. In früheren plentymarkets Versionen konnten Artikel ohne Kategorieverknüpfung erstellt werden.

|**Kategorien**
|Kategorie wählen, um nur Artikel dieser Kategorie zu bearbeiten.
|====

[#160]
== Varianten erstellen

Beim Erstellen eines Artikels des Typs **Standard** wird immer eine Hauptvariante erstellt. Die Hauptvariante ist fest mit dem Artikel des Typs **Standard** verbunden und sie kann nicht gelöscht werden. Informationen der Hauptvariante wie Verkaufspreise und Verfügbarkeit werden von Artikelvarianten geerbt. Du kannst jede Variante aber auch individuell anpassen. Erfahre zunächst, wie du Varianten erstellst.

[.instruction]
Varianten erstellen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**.
. Wechsele in das Tab **Varianten**.
. Klicke auf **Neu**. +
→ Das Fenster **Neue Variante erstellen** wird geöffnet.
. Gib den Inhalt ein.
. Wähle ein oder mehrere Attribute. +
→ Unter **Kombinationen** wird angezeigt, wie viele unterschiedliche Varianten erstellt werden.
. Klicke auf **Varianten erstellen**. +
→ Die Varianten werden erstellt und in der Variantenübersicht angezeigt. +
*_Hinweis:_* Neue Varianten und Änderungen an Variantendaten sind nicht sofort im Webshop und den Exporten verfügbar. +
*_Tipp:_* Zeige eine Vorschau der Variante an:
 .. Klicke in der Speicherzeile der Variante auf das Augensymbol. +
 → Das Fenster *Mandant (Shop)* wird angezeigt. +
 .. Wähle in der Dropdown-Liste das *Plugin Set*, in dem du die Vorschau anzeigen möchtest.
 .. Wähle in der Dropdown-Liste den *Mandant (Shop)*, in dem du die Vorschau anzeigen möchtest. +
 *_Tipp:_* Die Einstellungen bleiben erhalten, wenn du die Vorschau das nächste Mal öffnest.
 .. Klicke auf *Ausführen*. +
 → Eine Vorschau der Variante wird angezeigt.

[TIP]
.Attribute für Varianten wählen
====
Wenn du für die Hauptvariante Attribute wählst, sind diese gewählten Attribute für alle Varianten des Artikels verfügbar. Wenn du einen Artikel erstellst, ohne Attribute für die Hauptvariante zu wählen, können beim Erstellen von Varianten alle im System verfügbaren Attribute gewählt werden. Sobald eine Variante mit Attributen erstellt wurde, können weitere Varianten nur noch mit diesen Attributen oder ohne Attribute erstellt werden.

Lösche alle Varianten eines Artikels, dessen Hauptvariante keine Attribute besitzt, dann stehen dir beim Erstellen neuer Varianten wieder alle im System verfügbaren Attribute zur Auswahl. Somit musst du lediglich die Varianten und nicht den Artikel löschen, wenn du ein für den Artikel relevantes Attribut nachträglich hinzufügst. Die mit dem Artikel verknüpften Attribute können nach dem Erstellen von Varianten nicht mehr gelöscht oder hinzugefügt werden. Um Attribute zu löschen oder hinzuzufügen, müssen zunächst alle Varianten mit Attributen gelöscht werden.
====

[#170]
== Varianten bearbeiten

Hier erfährst du, wie du Variantendaten speicherst und bearbeitest.

=== Anzeige der Variantendaten in Varianten-Tabs personalisieren

Standardmäßig wird in den Tabs von Varianten die Varianten-ID angezeigt. Stattdessen kannst du den Variantennamen oder die Variantennummer anzeigen lassen. Gehe wie unten beschrieben vor, um die angezeigten Variantendaten zu ändern.

[.instruction]
Anzeige der Variantendaten in Varianten-Tabs personalisieren:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne einen Artikel. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Zeige mit der Maus auf das Tab der Variante.
. Klicke auf die rechte Maustaste. +
→ Eine Dropdown-Liste wird angezeigt. +
**__Tipp:__** Wenn die Dropdown-Liste nicht angezeigt wird, Wechsele in das Tab der Hauptvariante.
. Klicke auf *Umbenennen*. +
→ Das Fenster *Tab-Titel wählen* wird angezeigt.
. Wähle, ob im Tab-Titel von Varianten die *Varianten-ID*, der *Variantenname* oder die *Variantennummer* angezeigt werden soll.
. Klicke auf **Umbenennen**. +
→ Die gewählten Variantendaten werden in allen Tabs angezeigt. +
→ Wenn *Variantenname* oder *Variantennummer* eingestellt wird und diese Daten für eine Variante nicht gespeichert sind, wird stattdessen die *Varianten-ID* angezeigt. +
**__Tipp:__** Die Anzeige im Tab der aktuell geöffneten Variante ändert sich erst, nachdem der Artikel neu geladen wird.

=== Grundeinstellungen an der Hauptvariante vornehmen

Bearbeite Variantendaten in der Hauptvariante, um die geänderten Daten an alle Varianten zu vererben. Du kannst die Vererbung auch deaktivieren, um jede Variante individuell anzupassen.

[TIP]
.Änderungen nicht sofort sichtbar
====
Neue Varianten und Änderungen an Variantendaten sind nicht sofort im Webshop und den Exporten verfügbar. Wie du prüfst, ob die Variantendaten aktuell sind, erfährst du auf der Handbuchseite <<artikel/anwendungsfaelle/artikeldaten-status-pruefen#, Aktualität von Artikeldaten prüfen>>.
====

[.instruction]
Grundeinstellungen an der Hauptvariante vornehmen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel des Typs *Standard*. +
→ Das Tab *Einstellungen* der Hauptvariante wird geöffnet.
. Nimm die Einstellungen im Bereich *Grundeinstellungen* vor. Beachte dazu die Erläuterungen in <<tabelle-hauptvariante-grundeinstellungen>>.
. *Speichere* die Einstellungen. +
*_Hinweis:_* Neue Varianten und Änderungen an Variantendaten sind nicht sofort im Webshop und den Exporten verfügbar. +
*_Tipp:_* Zeige eine Vorschau der Variante an:
  .. Klicke in der Speicherzeile der Variante auf das Augensymbol. +
  → Das Fenster *Mandant (Shop)* wird angezeigt. +
  .. Wähle in der Dropdown-Liste das *Plugin Set*, in dem du die Vorschau anzeigen möchtest.
  .. Wähle in der Dropdown-Liste den *Mandant (Shop)*, in dem du die Vorschau anzeigen möchtest. +
  *_Tipp:_* Die Einstellungen bleiben erhalten, wenn du die Vorschau das nächste Mal öffnest.
  .. Klicke auf *Ausführen*. +
  → Eine Vorschau der Variante wird angezeigt.

[[tabelle-hauptvariante-grundeinstellungen]]
.Grundeinstellungen an der Hauptvariante vornehmen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Variantenname**
|Name für die Hauptvariante eingeben.

|**Variantennummer**
|Variantennummer wird automatisch nach dem im Menü **Einrichtung » Artikel » Einstellungen** festgelegten Muster vergeben. Variantennummern sind nachträglich im Tab **Einstellungen** einer Variante änderbar.

|**Externe Varianten-ID**
|Externe Varianten-ID eingeben. Die externe Varianten-ID ist eine optionale Eingabe, die dir die Übernahme von Artikeln und Varianten aus einem externen System erleichtert.

|**Modell**
|Modell der Hauptvariante eingeben. Das Modell wird an alle Varianten vererbt.

|**Position**
|Positionsnummer für die Variante eingeben. Varianten werden aufsteigend nach Positionsnummern sortiert. +
**__Hinweis:__** Wenn im Menü **Einrichtung » Mandant » Mandant wählen » Artikelansichten » Einstellungen** für die Einstellung **Automatische Sortierung nach monatlichen Verkäufen** die Option **Ja** eingestellt ist, werden manuell eingegebene Positionsnummern überschrieben.
|====

[#180]
=== Verfügbarkeit einstellen

Aufgrund gesetzlicher Vorgaben muss für alle Artikel, die du anbietest, die Lieferfrist im Webshop angeben werden. In plentymarkets stehen zehn Verfügbarkeitsangaben zur Auswahl.

[#190]
==== Verfügbarkeitsangaben festlegen

Die Verfügbarkeit stellst du im Tab einer Variante ein. Die Verfügbarkeitstexte gibst du einmalig im plentymarkets Backend ein. Auch die Verfügbarkeitssymbole kannst du durch eigene Symbole ersetzen.

[.instruction]
Verfügbarkeitsangaben festlegen:

. Öffne das Menü **Einrichtung » Artikel » Verfügbarkeit**.
. Nimm die Einstellungen gemäß <<tabelle-verfuegbarkeitsangaben-festlegen>> vor.
. **Speichere** die Einstellungen.

[[tabelle-verfuegbarkeitsangaben-festlegen]]
.Verfügbarkeitsangaben festlegen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Backend-Symbol**
|Hier werden die systemseitigen Verfügbarkeitssymbole angezeigt. Die Symbole sind standardmäßig eingestellt und können durch eigene Symbole ersetzt werden.

|**Name**
|Name oder Beschreibung für die Lieferzeit eingeben.

|**Sprache**
|Sprache aus der Dropdown-Liste wählen. Standardmäßig ist die Sprache eingestellt, die beim Erstellen des Systems Systemsprache gewählt wurde.

|**Durchschnittliche Lieferzeit**
|Durchschnittliche Lieferzeit in Tagen eingeben. Diese Werte werden von Suchmaschinen ausgewertet. Realistische Werte für die durchschnittliche Lieferzeit eingeben, da diese Angaben als Zusage gewertet werden und auch wettbewerbsrechtlich relevant sind.

|**Webshop-Symbol hochladen**
|Eigenes Webshop-Symbol hochladen. Das Symbol wird anstelle des Backend-Symbols im Webshop angezeigt. +
Mögliche Bildformate: **PNG**, **JPG** und **GIF**. Ideale Bildgröße: **16 x 16 Pixel**.

|**Webshop-Symbol löschen**
|Eigenes Webshop-Symbol löschen. Nach dem Löschen wird das systemseitige Symbol im Webshop angezeigt.
|====

[#200]
==== Alter Webshop: Verfügbarkeit im Callisto Webshop anzeigen

Die Verfügbarkeit wird in Callisto standardmäßig über das Template <<webshop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewsingleitem, ItemViewSingleItem>> im Webshop angezeigt. Über die Template-Variablen **$AvailabilityString** und **$AvailabilityIcon** werden Verfügbarkeitstext und -symbol im Webshop dargestellt. Diese Template-Variablen sind standardmäßig im Template **ItemViewSingleItem** der plentymarkets Standard-Designs enthalten.

[IMPORTANT]
.Fehlerhafte Anzeige der Verfügbarkeit im Webshop
====
Wenn du eigene Webshop-Symbole für die Verfügbarkeit verwendest, lade für alle Verfügbarkeiten ein Symbol hoch, da bei fehlendem Symbol ein leerer Rahmen im Design angezeigt wird. +
Wenn die Webshop-Symbole nach Änderungen nicht korrekt im Webshop angezeigt werden, lösche den Cache deines Browsers und lade die Seite neu.
====

[#220]
==== Verfügbarkeitsangaben im Webshop deaktivieren

Standardmäßig sind alle Verfügbarkeitsangaben aktiviert und im Webshop sichtbar. Nur Produkte mit aktivierten Verfügbarkeitsangaben können im Webshop bestellt werden. Wenn du Produkte mit einer bestimmten Verfügbarkeit im Webshop ausblenden möchtest, deaktiviere die zugehörige Verfügbarkeitsangabe. Produkte mit deaktivierter Verfügbarkeit stehen weiterhin für Marktplätze zur Verfügung. Gehe wie unten beschrieben vor, um die Verfügbarkeitsangaben für deinen Standard-Webshop zu aktivieren. Die Verfügbarkeitsangaben weiterer Mandanten (Shops) aktivierst du analog dazu.

[.instruction]
Verfügbarkeitsangaben für den Webshop aktivieren:

. Öffne das Menü **Einrichtung » Mandant » Mandant wählen » Artikelansichten » Verfügbarkeit**.
. Aktiviere die Verfügbarkeiten mit gedrückter Strg- oder Cmd-Taste.
. **Speichere** die Einstellungen. +
→ Die markierten Verfügbarkeitsangaben werden für den Webshop dieses Mandanten (Shops) aktiviert.

Varianten, deren Verfügbarkeit nicht wie beschrieben aktiviert ist, sind nicht im Webshop bestellbar. Ob die Variante im Webshop sichtbar ist, hängt davon ab, welche Art der Prüfung im Menü <<webshop/webshop-einrichten/artikelansichten#, Einrichtung » Mandant » Mandant wählen » Artikelansichten » Einstellungen>> für die Attribut-Verfügbarkeit gewählt wurde:

* Wenn für die Option **Attribut-Verfügbarkeit** die Einstellung **Server-Prüfung** gewählt wurde, ist die Variante sichtbar und wählbar. Die Verfügbarkeit wird erst bei Auswahl des letzten Attributwerts im Bestellvorgang geprüft.
* Bei der Einstellung **Client-Prüfung** wird die Variante nicht im Webshop angezeigt oder ausgegraut.

[#230]
==== Verfügbarkeit von Varianten einstellen

Die Verfügbarkeit und Sichtbarkeit einer Variante stellst du im Tab **Einstellungen** der Variante ein.

[.instruction]
Verfügbarkeit der Hauptvariante einstellen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Nimm die Einstellungen im Bereich **Verfügbarkeit** gemäß <<tabelle-hauptvariante-verfuegbarkeit>> vor.
. **Speichere** die Einstellungen.

[[tabelle-hauptvariante-verfuegbarkeit]]
.Verfügbarkeit der Hauptvariante einstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Aktiv**
|Variante aktivieren, um die Variante im Webshop und bei Artikeln des Typs **Standard** auch auf Marktplätzen anzubieten. Varianten werden erst im Webshop angezeigt, wenn die Varianten aktiv sind. Bei der Artikelsuche werden inaktive Varianten nicht mit den Standardeinstellungen der Suche angezeigt. Im Filter **Aktiv** die Option **Nein** wählen, um nach inaktiven Varianten zu suchen.

|**Verfügbarkeit**
|Verfügbarkeitsstufe wählen. 10 Verfügbarkeitsstufen stehen zur Auswahl. +
*_Hinweis:_* Die Verfügbarkeitsstufe ist eine statische Einstellung. Das heißt, dass sich die gewählte Verfügbarkeitsstufe unabhängig vom tatsächlichen Warenbestand nicht ändert. Die Einstellung ist nur relevant, wenn keine automatische Warenbestandsanzeige eingestellt ist.

|*Anzeige im Webshop:* +
*Verfügbar wenn Netto-WB positiv*; +
*Nicht verfügbar wenn kein Netto-WB*
|Aktivieren, damit die Variante bei positivem Nettowarenbestand verfügbar und käuflich wird oder nicht käuflich wird, wenn kein Nettowarenbestand vorhanden ist. Diese beiden Funktionen ergänzen sich und funktionieren im Zusammenspiel mit der Einstellung **Auf Netto-WB** unter **Beschränkung**. Die Verfügbarkeit im Webshop wird automatisch von plentymarkets geregelt. Varianten müssen nicht manuell unsichtbar gestellt werden, wenn kein Bestand vorhanden ist.

|*Mandant:* +
*Automatisch sichtbar wenn Netto-WB positiv*; +
*Automatisch unsichtbar wenn kein Netto-WB*
|Aktivieren, damit die Variante bei positivem Nettowarenbestand automatisch im Webshop sichtbar wird und unsichtbar wird, wenn kein Nettowarenbestand vorhanden ist. Diese beiden Funktionen ergänzen sich und greifen nur, wenn die Option *Beschränkung* auf *Auf Netto-WB* gestellt ist. Wenn die Optionen aktiviert sind und kein Netto-Warenbestand verfügbar ist, kann die Variante auch nicht mehr über die direkte URL aufgerufen werden.

|*Artikelauflistung* +
(Automatisierung funktioniert derzeit nur in Callisto, Umsetzung in Ceres folgt)
|*Immer unsichtbar* (frühere Option *Unsichtbar: in Artikelauflistung*) = Aktivieren, um die Variante in der Artikelauflistung des Webshops unsichtbar zu stellen. Wenn die Option aktiviert ist kann die Variante nur über die direkte URL aufgerufen werden. Die Variante wird nicht in den Kategorien, in den Suchergebnissen und in den Artikellisten, also in Shop-Aktionen, Cross-Selling-Listen und in Listen der zuletzt gesehenen Artikel, angezeigt. +
*Automatisch sichtbar wenn Netto-WB positiv*; +
*Automatisch unsichtbar wenn kein Netto-WB* = Aktivieren, damit die Variante bei positivem Nettowarenbestand in der Artikelauflistung sichtbar wird und unsichtbar wird, wenn kein Nettowarenbestand vorhanden ist. Diese beiden Funktionen ergänzen sich und greifen nur, wenn die Option *Beschränkung* auf *Auf Netto-WB* gestellt ist. Wenn die Optionen aktiviert sind und kein Netto-Warenbestand verfügbar ist, kann die Variante nur noch über die direkte URL aufgerufen werden. Die Variante wird nicht in den Kategorien, in den Suchergebnissen und in den Artikellisten, also in Shop-Aktionen, Cross-Selling-Listen und in Listen der zuletzt gesehenen Artikel, angezeigt. +
*_Hinweis:_* Die Optionen *Mandant: Automatisch sichtbar wenn Netto-WB positiv* und *Mandant: Automatisch unsichtbar wenn kein Netto-WB* haben Priorität. Wenn diese Optionen aktiviert sind und kein Netto-Warenbestand verfügbar ist, kann die Variante also auch nicht über die direkte URL aufgerufen werden. Daher ist es sinnvoll, die Sichtbarkeit entweder über die Webshop-Sichtbarkeit oder über die Artikelauflistungssichtbarkeit zu steuern und diese Einstellungen nicht zu kombinieren.

|**Im Zulauf**
|Zeigt das voraussichtliche Lieferdatum von bestellten Varianten an. Weitere Informationen zu Nachbestellungen im Zulauf findest du unter <<warenwirtschaft/nachbestellungen-verwalten/rueckstandsliste-verwalten#, Rückstandsliste nutzen>>.

|**Beschränkung**
|**Keine**, **Auf Netto-WB** oder **Keinen WB für diese Variante führen** wählen. +
**Keine** = Der Warenbestand wird nicht beschränkt. Die Verfügbarkeit der Variante wird nicht automatisch geprüft. +
**Auf Netto-WB** = Der Warenbestand wird auf den Nettowarenbestand beschränkt. Die Verfügbarkeit der Variante wird automatisch geprüft. +
**Keinen WB für diese Variante führen** = Wenn diese Einstellung gewählt wird, werden im Tab **Bestand** der Variante die Tabs **Korrektur**, **Warenbestand**, **Zulauf** und **Warenbewegung** ausgeblendet.

|**Max. Bestellmenge**
|Maximale Bestellmenge eingeben, die pro Bestellung möglich ist. Kommawerte sind möglich, um zum Beispiel Bestellungen nach Gewicht oder Länge abzubilden. Standardmäßig ist der Wert **0** voreingestellt. Die maximale Bestellmenge ist bei dem Wert **0** unbegrenzt. Die maximale Bestellmenge kann zum Beispiel bei Vorbestellungen eingesetzt werden, um zu verhindern, dass Varianten zum günstigen Einführungspreis von anderen Händlern aufgekauft werden.

|**Min. Bestellmenge**
|Mindestbestellmenge eingeben. Kommawerte sind möglich, um zum Beispiel Bestellungen nach Gewicht oder Länge abzubilden.

|**Intervallbestellmenge**
|Eingeben, in welchen Mengenintervallen die Variante bestellbar ist. Kommawerte sind möglich, um zum Beispiel Bestellungen nach Gewicht oder Länge abzubilden.

|**Erscheinungsdatum**
|Datum wählen, ab dem die Variante verfügbar sein wird. Die Variante kann vor diesem Datum bereits im Webshop sichtbar sein und vorbestellt werden. Bei manueller Dateneingabe das Datumsformat (DD.MM.YYYY) beachten. +
Weitere Informationen zu Vorbestellungen findest du auf der Handbuchseite <<auftraege/auftraege-verwalten#1100, Vorbestellungen>>.

|**Verfügbar bis**
|Datum des letzten Tages der Variantenverfügbarkeit aus dem Kalender wählen. Bei manueller Dateneingabe das Datumsformat (DD.MM.YYYY) beachten.
|====

==== Verfügbarkeit für Mandanten einstellen

Für welche Mandanten (Shops) die Variante verfügbar ist, legst du im Tab **Verfügbarkeit** der Variante fest.

[.instruction]
Hauptvariante für Mandanten verfügbar machen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel. +

. Öffne die Hauptvariante.
. Wechsele in das Tab **Verfügbarkeit**.
. Wähle im Bereich **Mandant (Shop)** die Mandanten.
. **Speichere** die Einstellungen. +
→ Die Variante ist für die gewählten Mandanten verfügbar.

[NOTE]
.Verfügbarkeit/Sichtbarkeit wenn kein Nettowarenbestand
====
Ob eine Variante ohne positiven Nettowarenbestand für die gewählten Mandanten tatsächlich sichtbar oder verfügbar ist, hängt von den Einstellungen zur Nettowarenbestandsabhängigkeit im Bereich **Verfügbarkeit** des Tabs **Einstellungen** ab. +
Ist die Option **Nicht verfügbar wenn kein Netto-WB** oder **Nicht sichtbar wenn kein Netto-WB** aktiviert und kein Nettowarenbestand für die Variante vorhanden, ist die Mandantenauswahl deaktiviert. Klicke auf das Schloss, um die Auswahl trotz negativem Nettowarenbestand zu aktivieren. Wenn du die Auswahl aktivierst und einen Mandanten wählst, ist die Variante unabhängig von der eingestellten Verfügbarkeit/Sichtbarkeit bei Nettowarenbestand in den gewählten Mandanten verfügbar. Diese Einstellung gilt, bis neuer Wareneingang für die Variante gebucht wird. Danach greifen die Einstellungen zur Nettowarenbestandsabhängigkeit erneut.
====

[#235]
==== Verfügbarkeit für Marktplätze einstellen

Im Tab **Verfügbarkeit** aktivierst du <<maerkte#, Marktplätze>> und nimmst Einstellungen an den SKUs vor.

[#240]
=== Verkaufspreise verknüpfen

Verknüpfe <<artikel/einstellungen/preise#, Verkaufspreise>> mit den Hauptvarianten von Artikeln des Typs **Standard**, um Preise zu speichern. Du kannst Preise eingeben oder anhand einer <<artikel/einstellungen/preise#500, Preiskalkulation>> errechnen lassen. Die an der Hauptvariante gespeicherten Kombinationen aus Verkaufspreis und Preis werden von der Hauptvariante an die Varianten des Artikels vererbt, wenn die Vererbung nicht an der Variante deaktiviert ist.

[.instruction]
Verkaufspreis mit Hauptvariante verknüpfen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Wähle im Bereich **Verkaufspreise** den Verkaufspreis aus der Dropdown-Liste.
. Wähle, ob der Preis ein Brutto- oder Nettopreis ist.
. Klicke auf **Hinzufügen**. +
→ Der Verkaufspreis wird hinzugefügt und in der Liste angezeigt.
. Gib einen Wert in das Feld **Preis** ein.
. **Speichere** die Einstellungen.

[.instruction]
Verkaufspreis mit Preiskalkulation mit Hauptvariante verknüpfen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Wähle im Bereich **Verkaufspreise** den Verkaufspreis aus der Dropdown-Liste.
. Wähle, ob der Preis ein Brutto- oder Nettopreis ist.
. Wähle die Preiskalkulation aus der Dropdown-Liste.
. **Speichere** die Variante. +
→ Der Verkaufspreis wird hinzugefügt und der Preis berechnet. +
**__Tipp:__** Lade das Tab der Variante neu, um die Preisanzeige zu aktualisieren.

Wenn du eigene Verkaufspreise an den Varianten pflegen möchtest, deaktiviere die Vererbung im Tab der Variante und verknüpfe anschließend den Verkaufspreis. Um Verkaufspreise zu löschen, klicke in der Hauptvariante oder der Variante in der Zeile des Verkaufspreises auf **Löschen**.

[#250]
=== Barcodes verknüpfen

Barcodes wie GTIN, ISBN, UPC und QR dienen zur Kennzeichnung von Artikeln in plentymarkets. Verknüpfe <<artikel/einstellungen/barcodes#, Barcodes>> mit deinen Artikelvarianten.

[.instruction]
Barcode mit Hauptvariante verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel. +
→ Das Tab *Einstellungen* der Hauptvariante wird geöffnet.
. Wähle im Bereich *Barcodes* den Barcode aus der Dropdown-Liste.
. Klicke auf *Hinzufügen*. +
→ Der Barcode wird hinzugefügt und in der Liste angezeigt.
. Gib den Code in das Feld *Code* ein. +
icon:map-signs[] *_Oder:_* Klicke auf *GTIN generieren*, um einen durch den <<artikel/einstellungen/barcodes#200, Nummernkreis>> generierten Code einzufügen.
. *Speichere* die Einstellungen.

[#260]
=== ASIN und ePID verknüpfen

Die ASIN (Amazon Standard Identification Number) ist eine Produktkennzeichnung von <<maerkte/amazon/amazon-einrichten#, Amazon>>. Die ePID (eBay Product ID) ist eine Produktkennzeichnung von <<maerkte/ebay/ebay-einrichten#, eBay>>. Die ASIN besteht aus 10 Buchstaben und/oder Ziffern. Bei Büchern entspricht die ASIN der ISBN-Nummer. Die ASIN findest du auf der Produktseite bei Amazon. Die ePID wird von eBay zur Verfügung gestellt. Verknüpfe ASIN und ePID mit Varianten.

[.instruction]
ASIN oder ePID mit Hauptvariante verknüpfen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Klicke im Bereich **ASIN/ePID** auf **Hinzufügen**. +
→ Ein neuer Eintrag wird hinzugefügt und in der Liste angezeigt.
. Wähle die Länderplattform aus der Dropdown-Liste.
. Wähle **ASIN** oder **ePID** aus der Dropdown-Liste.
. Gib die ASIN oder ePID in das Feld ein.
. **Speichere** die Einstellungen.

[#265]
=== Pakete

Wähle Einstellungen im Bereich *Pakete* aus, um das <<artikel/artikel-verwalten#270, Gewicht>> und den <<artikel/artikel-verwalten#280, Einkaufspreis>> automatisch für <<artikel/anwendungsfaelle/multipacks-pakete-sets#2500, Artikelpakete berechnen zu lassen>>.

[#270]
=== Artikelmaße angeben

Im Bereich **Maße** gibst du die Länge, Breite und Höhe eines Artikels des Typs **Standard** an. Zudem definierst du das Gewicht und den Inhalt.

[.instruction]
Maße der Hauptvariante angeben:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Nimm die Einstellungen im Bereich **Maße** gemäß <<tabelle-haupvariante-masse>> vor.
. **Speichere** die Einstellungen.

[[tabelle-haupvariante-masse]]
.Maße der Hauptvariante angeben
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Inhalt**
|Inhalt eingeben und <<artikel/einstellungen/einheiten#, Einheit>> aus der Dropdown-Liste wählen.

|**Länge/Breite/Höhe**
|Maße der Variante in Millimeter eingeben.

|*Gewicht brutto*
|Bruttogewicht der Variante in Gramm oder Kilogramm eingeben. Bei einzeln verpackten Varianten ist das Bruttogewicht das Gewicht der Variante inklusive Verpackung. Der hier eingegebene Wert wird für die Berechnung der Versandpakete und für gewichtsabhängige Einstellungen der Versandkosten verwendet. +
Für Artikelpakete lässt sich das Bruttogewicht <<artikel/anwendungsfaelle/multipacks-pakete-sets#2500, automatisch anhand der Bestandteile berechnen>>.

|*Gewicht netto*
|Gewicht der Variante ohne Verpackung der Variante in Gramm oder Kilogramm eingeben. +
Für Artikelpakete lässt sich das Nettogewicht <<artikel/anwendungsfaelle/multipacks-pakete-sets#2500, automatisch anhand der Bestandteile berechnen>>.

|**VPE**
|Verpackungseinheit (VPE) ist die Zusammenfassung mehrerer Verkaufseinheiten. Standardeinstellung: **1**. +
**__Hinweis:__** Diese VPE wird aktuell nicht in Berechnungen berücksichtigt. +
Die Berechnung von Grundpreisen, zum Beispiel pro Kilogramm, erfolgt auf der Basis des Gewichtes, das unter **Inhalt** eingetragen ist und der Einstellung unter **Einheit** in Verbindung mit dem **Preis**. Der Eintrag bei der Option **VPE** hat keinen Einfluss auf die Berechnung eines Grundpreises.

|*Grundpreisanzeige*
|Wählen, ob der Grundpreis der Variante im Webshop angezeigt werden soll. +
*Aktiviert* = Der Grundpreis der Variante wird im Webshop angezeigt, wenn die entsprechende Logik im Design hinterlegt ist. +
*Nicht aktiviert* = Der Grundpreis der Variante wird nicht im Webshop angezeigt. +
*_Tipp:_* Der Grundpreis ist der auf eine Standardmenge bezogene Preis, zum Beispiel der Preis pro kg oder Liter. Der Grundpreis wird angegeben, um Verbrauchern einen einfachen Preisvergleich zu ermöglichen. Die deutsche Grundpreisverordnung schreibt vor, dass für Produkte, die nach Gewicht, Volumen, Länge oder Fläche verkauft werden, der Grundpreis in unmittelbarer Nähe des Endpreises anzugeben ist.
|====

[#280]
=== Kosten angeben

Im Bereich **Kosten** gibst du den Umsatzsteuersatz und den Einkaufspreis der Variante ein. Auch Zusatzkosten für Transport und Lagerung werden hier erfasst. Diese Angaben verwendest du für <<artikel/einstellungen/preise#500, Preiskalkulationen>> deiner Verkaufspreise.

[.instruction]
Kosten für die Hauptvariante angeben:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Nimm die Einstellungen im Bereich **Kosten** gemäß <<tabelle-hauptvariante-kosten>> vor.
. **Speichere** die Einstellungen.

[[tabelle-hauptvariante-kosten]]
.Kosten der Hauptvariante angeben
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Einstandspreis**
|Einstandspreis in Brutto oder Netto anzeigen. Der Einstandspreis ist das Ergebnis der Beschaffungskalkulation. Ausgehend vom Rechnungspreis des Lieferanten werden Rabatte und Boni abgezogen. Außerbetriebliche Beschaffungskosten für Transport, Versicherungen, Verpackung werden addiert.

|**Umsatzsteuer**
|<<auftraege/buchhaltung#550, Umsatzsteuersatz>> für die Variante wählen.

|*EK netto*
|Der Nettoeinkaufspreis. Abhängig von den Einstellungen im Menü *Einrichtung » Waren » Warenbestand » Wareneingang* wird der Einkaufspreis berechnet oder manuell gepflegt. +
Der Nettoeinkaufspreis wird u.a. für die *Preiskalkulation* verwendet. +
Für Artikelpakete lässt sich der Nettoeinkaufspreis <<artikel/anwendungsfaelle/multipacks-pakete-sets#2500, automatisch anhand der Bestandteile berechnen>>.

|*GLD EK netto*
|Der *gleitende Durchschnittseinkaufspreis* (GLD EK netto). Der GLD EK netto wird bei jedem Wareneingang neu aus den Einkaufspreisen aller im Lager verfügbaren Bestände einer Variante berechnet. +
*_Hinweis_*: Bei der Berechung wird nur Wareneingang in die *Lager für gleitenden Durchschnittspreis* berücksichtigt, die im Menü *Einrichtung » Waren » Warenbestand » Wareneingang* aktiviert wurden. Wenn keine Lager aktiviert sind, erfolgt keine Berechnung. +
Für Artikelpakete lässt sich der gleitende Durchschnittseinkaufspreis <<artikel/anwendungsfaelle/multipacks-pakete-sets#2500, automatisch anhand der Bestandteile berechnen>>.

|**Transport netto**
|Nettotransportkosten für die Variante eingeben. Dieser Wert wird für **Preiskalkulationen** und die Berechnung des Einstandspreises verwendet.

|**Lager netto**
|Nettolagerkosten für die Variante eingeben.

|**Zoll**
|Wert in Prozent für den Zoll eingeben.

|**Betriebskosten**
|Wert in Prozent für die Betriebskosten eingeben.
|====

[#290]
=== Versanddaten angeben

Zusätzlich zu den globalen Versandinformationen, die du im Tab *Global* aktivierst, gibst du weitere Daten wie Lager und Aufschläge im Bereich **Versand** der Variante an.

[.instruction]
Versanddaten für die Hauptvariante angeben:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Nimm die Einstellungen im Bereich **Versand** gemäß <<tabelle-hauptvariante-versanddaten>> vor.
. **Speichere** die Einstellungen.

[[tabelle-hauptvariante-versanddaten]]
.Versanddaten der Hauptvariante eingeben
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Kommissionierung**
|**Einzelkommissionierung möglich**, **Keine Einzelkommissionierung möglich** oder **Von Pickliste ausschließen** wählen, um die Art der Kommissionierung festzulegen. Wenn die Kommissionierung nicht spezifiziert werden soll, leere Option wählen.

|**Hauptlager**
|Hauptlager der Variante wählen.

|**Lademittel**
|Lademittel wählen.

|**Packstücke**
|Anzahl der Packstücke und Art der Verpackung wählen, wenn ein Artikel aus mehreren Paketen besteht. +
Wenn ein Artikel unabhängig von der Anzahl immer in einem einzigen Paket verschickt werden soll, den Wert **0** wählen. Diese Einstellung greift auch bei unterschiedlichen Artikeln. Alle Artikel eines Auftrags mit Wert **0** werden in ein Paket verpackt.

|**Portoaufschlag 1; +
Portoaufschlag 2**
|Wert für die Berechnung des Portoaufschlags für den 1. und 2. Artikel eingeben. Weitere Informationen findest du unter <<fulfillment/versand-vorbereiten#1000, Versandprofil erstellen>>.
|====

[#300]
=== Zusätzliche Kategorien verknüpfen

Im Tab **Kategorien** verknüpfst du zusätzliche Kategorien mit deinen Varianten. Die Varianten werden in allen gewählten Kategorien im Webshop geführt. Im Bereich **Standardkategorien** aktivierst du zudem die Standardkategorie für die Variante. Die Standardkategorie definiert den Kategoriepfad in der Breadcrumb-Leiste im Webshop. Wenn eine Variante in mehreren Kategorien geführt wird, wird in der Breadcrumb-Leiste immer der Kategoriepfad der Standardkategorie angezeigt.

[.instruction]
Zusätzliche Kategorien verknüpfen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Öffne die Variante.
. Wechsele in das Tab **Kategorien**.
. Klicke auf **Kategorie verknüpfen**. +
→ Das Fenster **Kategorie verknüpfen** wird geöffnet.
. Wähle eine Kategorie oder Unterkategorie.
. Klicke auf **Kategorie verknüpfen**. +
→ Die Kategorie wird verknüpft und im Bereich **Verknüpfte Kategorien** angezeigt.

Kategorieverknüpfungen werden von der Hauptvariante an Varianten vererbt. Du kannst Kategorieverknüpfungen auch für jede Variante einzeln ändern. Deaktiviere im Tab **Kategorien** der Variante die Vererbung und nimm die Einstellungen analog vor.

[.instruction]
Standardkategorie festlegen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**.
. Öffne die Variante.
. Wechsele in das Tab **Kategorien**.
. Wähle aus der Dropdown-Liste die **Standardkategorie** für den Mandanten.
. **Speichere** die Einstellungen. +
→ Die Standardkategorie wird festgelegt.

[#4800]
=== Eigenschaften und Texte verknüpfen

<<artikel/einstellungen/eigenschaften#500, Eigenschaften>> werden zentral im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* verwaltet und mit den Varianten von Artikeln des Typs *Standard* verknüpft. Eigenschaften des Bereichs *Artikel* werden in zwei verschiedenen Tabs mit Varianten verknüpft:

* Eigenschaften der Typen *Ganze Zahl*, *Kommazahl*, *Auswahl*, *Datum* und *Datei* aktivierst du im Tab *Eigenschaften* einer Variante.
* Eigenschaften der Typen *Kurztext* und *Text* verknüpfst du im Tab *Texte* der Variante.

[NOTE]
.Vererbung von Verknüpfungen und Werten
====
Standardmäßig ist die Vererbung der Varianteneigenschaften und Variantentexte aktiviert. Die Kombinationen aus Eigenschaften und Werten, die in den Tabs *Eigenschaften* und *Texte* an der Hauptvariante gespeichert werden, werden also geschlossen an alle Varianten des Artikels vererbt, für die die Vererbung nicht deaktiviert ist. Wenn du eigene Eigenschaften an den Varianten des Artikels pflegen möchtest, deaktiviere die Vererbung im Tab der Variante und verknüpfe dann die Eigenschaft.
====

[#4900]
==== Eigenschaft verknüpfen und Wert speichern

Gehe wie unten beschrieben vor, um eine Eigenschaft der Typen *Ganze Zahl*, *Kommazahl*, *Auswahl*, *Datum* oder *Datei* mit einer Hauptvariante zu verknüpfen und einen Wert zu speichern.

[.instruction]
Eigenschaft mit Hauptvariante verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel des Typs *Standard*. +
→ Das Tab *Einstellungen* der Hauptvariante wird angezeigt.
. Wechsele in das Tab *Eigenschaften*. +
→ Bereits mit der Variante verknüpfte Eigenschaften werden angezeigt.
. Klicke in das Eingabefeld *Eigenschaften*. +
→ Eine Dropdown-Liste mit den verfügbaren Eigenschaften wird angezeigt.
. Aktiviere die Eigenschaft. +
*_Tipp:_* Du kannst beliebig viele oder alle Eigenschaften auf einmal mit der Variante verknüpfen.
. Klicke auf *Hinzufügen*. +
→ Die Eigenschaften werden im Bereich *Eigenschaften* angezeigt.
. Gib einen Wert für die Eigenschaft an. Beachte die Erläuterungen in <<tabelle-eigenschaften-verknuepfen>>.
. *Speichere* die Einstellungen.

[[tabelle-eigenschaften-verknuepfen]]
.Eigenschaft verknüpfen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Name*
|Zeigt den Namen der Eigenschaft an.

|*Typ*
|Zeigt den Typ der Eigenschaft an. +
*int* = *Ganze Zahl* +
*float* = *Kommazahl* +
*select* = *Auswahl* +
*date* = *Datum* +
*file* = *Datei* +
*empty* = *Kein*

|*Wert*
|Wert angeben. Wie der Wert angegeben wird, hängt vom Eigenschaftstyp ab. +
*int* = Ganze Zahl eingeben. +
*float* = Kommazahl eingeben. +
*select* = Option aus der Dropdown-Liste wählen. +
*date* = Datum eingeben oder wählen. +
*file* = Datei hochladen. +
*empty* = Für den Typ *Kein* kann kein Wert eingegeben werden.
|====

[#5000]
==== Text verknüpfen und Wert speichern

Gehe wie unten beschrieben vor, um eine Eigenschaft des Typs *Kurztext* oder *Text* mit einer Hauptvariante zu verknüpfen und einen Wert zu speichern.

[.instruction]
Text mit Hauptvariante verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel des Typs *Standard*. +
→ Das Tab *Einstellungen* der Hauptvariante wird angezeigt.
. Wechsele in das Tab *Texte*. +
→ Die bereits mit der Variante verknüpften Texte werden angezeigt.
. Klicke in das Eingabefeld *Eigenschaften*. +
→ Eine Dropdown-Liste mit den verfügbaren Eigenschaften wird angezeigt.
. Aktiviere die Eigenschaft. +
*_Tipp:_* Du kannst beliebig viele oder alle Eigenschaften auf einmal mit der Variante verknüpfen.
. Klicke auf *Hinzufügen*. +
→ Die Eigenschaften werden im Bereich *Texte* angezeigt. +
→ Standardmäßig wird die Standardsprache zur Bearbeitung angezeigt.
. Gib den Wert ein. Beachte die Erläuterungen in <<tabelle-texte-verknuepfen>>.
. *Speichere* die Einstellungen.
. Gib auf Wunsch den Text in weiteren Sprachen ein. +
*_Tipp:_* Klicke auf *Multilingualität*, um eine mehrsprachige Bearbeitungsansicht zu öffnen.
. *Speichere* die Einstellungen.

[[tabelle-texte-verknuepfen]]
.Texte verknüpfen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Name*
|Zeigt den Namen der Eigenschaft an.

|*Typ*
|Eigenschaften des Typs *Kurztext* werden im oberen Bereich des Tabs angezeigt. Wert in Textfeld eingeben. +
Eigenschaften des Typs *Text* werden im unteren Bereich des Tabs in einer Editoransicht mit weiteren Formatierungsmöglichkeiten angezeigt. +
→ Standardmäßig wird die Standardsprache zur Bearbeitung angezeigt.
|====

[#5010]
==== Verknüpfung und Wert löschen

Um eine Eigenschaftsverknüpfung zu löschen, klicke im Tab *Eigenschaften* oder *Texte* in der Variante in der Zeile der Eigenschaft auf *Löschen*. Beim Löschen einer Eigenschaftsverknüpfung greift die folgende Vererbungslogik:

* Wenn du die Eigenschaft einer Hauptvariante löschst, werden die Verknüpfung und der Wert für alle Varianten des Artikels gelöscht, die die Eigenschaften der Hauptvariante erben.
* Wenn du die Eigenschaft einer Variante löschst, für die die Vererbung aktiviert ist, wird die Vererbung deaktiviert und die verbleibenden Eigenschaften werden direkt an der Variante gespeichert. +
*_Hinweis:_* Die Eigenschaften und Werte des Tabs *Eigenschaften* und des Tabs *Texte* werden gemeinsam vererbt. Du kannst nur alle oder keine Werte vererben.

[#310]
=== Lieferanten zur Variante hinzufügen

// include erscheint auch hier warenwirtschaft/wareneingaenge-verwalten#100
include::_textblocks/einstellungen/lieferant.adoc[]

[#312]
=== Lager für die Variante hinzufügen

Im Tab **Lager** einer Variante wählst du Lager für das Produkt und gibst <<warenwirtschaft/wareneingaenge-verwalten#200, Lagerinformationen wie Melde- und Maximalbestand>> an.


[#314]
=== Warenbestand der Variante verwalten

Im Tab **Bestand** verwaltest du deinen Warenbestand, buchst neue Wareneingänge, korrigierst Bestände und überblickst Zuläufe und Warenbewegungen. Weitere Informationen findest du auf der Handbuchseite <<warenwirtschaft#, Warenwirtschaft>>.

[#320]
=== Artikelpakete nutzen

<<artikel/anwendungsfaelle/multipacks-pakete-sets#2000, Artikelpakete>> bestehen aus mehreren Artikeln des Typs **Standard**. Der Paketpreis kann dabei günstiger sein als die Summe der Einzelpreise.

=== Artikelbilder mit Varianten verknüpfen

Die Bildeinstellungen verwaltest du im Tab **Bilder** des Artikels. Die dort gespeicherten Bilder weist du durch Verknüpfen den Varianten des Artikels zu. Du hast zwei Möglichkeiten, Bilder mit Varianten zu verknüpfen:

* Im Tab **Bilder** des Artikels verknüpfst du Bilder mit mehreren Varianten des Artikels.
* Im Tab **Bilder** einer Variante verknüpfst du Bilder mit der geöffneten Variante.

Beide Vorgehensweisen werden nachfolgend beschrieben.

==== Bilder mit mehreren Varianten verknüpfen

Im Tab **Bilder** eines Artikels verknüpfst du am Artikel gespeicherte Bilder mit einer oder mehreren Varianten. Gehe dazu wie unten beschrieben vor.

[.instruction]
Artikelbilder mit mehreren Varianten verknüpfen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Wechsele in das Tab **Bilder**. +
→ Eine Vorschau der am Artikel gespeicherten Bilder wird angezeigt.
. Setze ganz links ein Häkchen bei den Bildern, die du verknüpfen möchtest.
. Klicke auf **Variantenverknüpfung**. +
→ Das Fenster **Varianten verknüpfen** wird angezeigt.
. *_Optional:_* Filtere die Varianten über den Filter links.
. Wähle die Varianten, die du mit den gewählten Bildern verknüpfen möchtest.
. Klicke auf **Verknüpfen**. +
→ Die Bilder werden mit den gewählten Varianten verknüpft.

Gehe wie unten beschrieben vor, um die Bildverküpfungen mit mehreren Varianten zu lösen.

[.instruction]
Bildverknüpfung mit mehreren Varianten lösen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Wechsele in das Tab **Bilder**. +
→ Eine Vorschau der am Artikel gespeicherten Bilder wird angezeigt.
. Klicke unterhalb des Bilds, für das du Verknüpfungen zu Varianten lösen möchtest, auf das Plus neben **Variantenverknüpfung**. +
→ Eine Liste der mit diesem Bild verknüpften Varianten wird eingeblendet.
. Wähle die Varianten, für die du die Verknüpfung mit diesem Bild lösen möchtest.
. Klicke auf **Lösen**. +
→ Die Verknüpfungen mit den Varianten werden gelöst.

==== Artikelbilder mit geöffneter Variante verknüpfen

Im Tab **Bilder** einer Variante verknüpfst du am Artikel gespeicherte Bilder mit der geöffneten Variante. Gehe dazu wie unten beschrieben vor.

[.instruction]
Artikelbilder mit geöffneter Variante verknüpfen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Öffne die Variante.
. Wechsele in das Tab **Bilder**. +
→ Eine Vorschau aller am Artikel gespeicherter Bilder wird angezeigt. Mit der Variante verknüpfte Bilder sind grün umrandet. Nicht mit der Variante verknüpfte Bilder sind ausgegraut.
. Zeige mit der Maus auf das Bild, das du verknüpfen möchtest.
. Klicke auf **Verknüpfen**. +
→ Das Bild wird mit dieser Variante verknüpft.

Gehe wie unten beschrieben vor, um Bildverknüpfungen mit der geöffneten Variante zu lösen.

[.instruction]
Bildverknüpfung mit geöffneter Variante lösen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Öffne die Variante.
. Wechsele in das Tab **Bilder**. +
→ Eine Vorschau aller am Artikel gespeicherter Bilder wird angezeigt. Mit der Variante verknüpfte Bilder sind grün umrandet. Nicht mit der Variante verknüpfte Bilder sind ausgegraut.
. Zeige mit der Maus auf das Bild, für das du die Verknüpfung lösen möchtest.
. Klicke auf **Lösen**. +
→ Die Verknüpfung mit der Variante wird gelöst.

[#150]
=== Variante mit Tag verknüpfen

Wenn du <<basics/arbeiten-mit-plentymarkets/tags#, Tags>> für den Bereich *Artikel* verfügbar gemacht hast, kannst du Varianten mit einer beliebigen Anzahl von Tags verknüpfen. Tags, die du mit der Hauptvariate verknüpfst, werden an die anderen Varianten des Artikels vererbt. Wenn du pro Variante eigene Tags speichern möchtest, deaktiviere die Vererbung und speichere eigene Tags an den Varianten.

[NOTE]
.Vererbung von Tags
====
Wenn du alle Tags einer Variante entfernst, wird die Vererbung nicht wie beim Vererben anderer Daten automatisch aktiviert. Stattdessen wird die Variante ohne Tags gespeichert.
====


[.instruction]
Tag hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne die Variante. +
→ Das Tab *Einstellungen* der Variante wird geöffnet.
. *_Optional:_* Wenn die Vererbung aktiviert ist, Klicke auf *Vererbung deaktivieren*.
. Klicke rechts im Bereich *Tags* in das Textfeld.
. Gib den Namen des Tags ein. +
*_Tipp:_* Den ersten Buchstaben des Tags eingeben und dann die Autovervollständigung nutzen. +
icon:map-signs[] *_Oder:_* Wähle das Tag aus der Liste.
. *Speichere* die Variante. +
→ Das Tag wird mit der Variante verknüpft. +
→ In der Artikelübersicht wird die Variante über den Tag-Filter gefunden.

// Vererbung ist anders: Wenn man alle löscht, geht die vererbung nicht an!!!
// Was kann man mit Tags machen?

// Tags entfernen

[#2090]
=== Notiz an der Variante speichern

Im Tab **Notizen** kannst du zu einer Variante Notizen speichern. Notizen sind nur in deinem plentymarkets Backend sichtbar. Notizen werden also nicht im Webshop angezeigt.

[.instruction]
Notiz speichern:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Suche den Artikel oder die Variante anhand der <<artikel/einleitung/suche#100, Filtereinstellungen>>.
. Öffne die Variante.
. Wechsele in das Tab **Notizen**.
. Gib die Notiz ein. +
. *_Optional:_* Formatiere die Notiz mit den Funktionen in der Symbolleiste.
. **Speichere** die Notiz. +
→ Die Notiz wird an der Variante gespeichert. +
→ Varianten mit Notiz werden in der Spalte **Aktionen** der Artikelübersicht mit einem Notiz-Icon dargestellt. Varianten ohne Notiz sind am grünen Plus auf dem Notiz-Icon erkennbar.

[TIP]
.Notizen in der Artikelübersicht
====
In der Spalte **Aktionen** der Artikelübersicht ist erkennbar, ob bereits eine Notiz an der Variante gespeichert ist. Varianten ohne Notiz erkennst du an dem grünen Plus auf dem Notiz-Icon. Wenn du die Artikelübersicht nach dem Tabellentyp **Artikel** filterst, werden nur Notizen angezeigt, die an der Hauptvariante des Artikels gespeichert sind. Wenn du in der Tabellenansicht **Artikel** eine neue Notiz am Artikel erstellst, wird diese Notiz an der Hauptvariante gespeichert.
====

Wenn du die Informationen, die du in der Notiz gespeichert hast, nicht mehr benötigst, entferne die Notiz mit einem Klick auf **Löschen**.

[#330]
== Mehrere Varianten bearbeiten

Mehrere Varianten bearbeitest du per **Varianten-Gruppenfunktion** oder per **Stapelverarbeitung** im Menü **Artikel**. Bei der Gruppenfunktion werden zuvor in der Artikelübersicht gewählte Varianten bearbeitet. Bei der Stapelverarbeitung werden zuvor gefilterte Varianten bearbeitet.

[.instruction]
Varianten-Gruppenfunktion ausführen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Wähle in der Suche unter **Tabellentyp** die Option **Varianten**.
. Wähle die zu bearbeitenden Varianten.
. Klicke auf **Varianten-Gruppenfunktion**. +
→ Das Fenster **Varianten-Gruppenfunktion** wird geöffnet.
. Aktiviere das Kontrollkästchen links neben der Option, die du bearbeiten möchtest. Beachte <<tabelle-mehrere-varianten-bearbeiten>>.
. Lege fest, ob die Option an den markierten Varianten aktiviert oder deaktiviert werden soll. +
→ Um die Option an der Variante zu aktivieren, aktiviere das Kontrollkästchen rechts neben der Option. +
→ Um die Option an der Variante zu deaktivieren, lasse das Kontrollkästchen rechts neben der Option leer. +
**__Hinweis:__** Vererbungseinstellungen können nur einzeln ausgeführt werden. Daher werden alle weiteren Einstellungen ausgegraut, wenn du eine Vererbungseinstellung markierst.
. Klicke auf **Ausführen**, um die Einstellungen an den Varianten zu ändern. +
**__Tipp:__** Bei der Vererbung werden Hauptvarianten, die in der Artikelübersicht markiert wurden, beim Ausführen der Gruppenfunktion ignoriert.

[[tabelle-mehrere-varianten-bearbeiten]]
.Varianten per **Gruppenfunktion** oder per **Stapelverarbeitung** bearbeiten
[cols="1,2"]
|====
| Einstellung | Erläuterung

2+| *Marktplatz-Verfügbarkeit*

|**Märkte aktivieren**
|Einstellungen dieses Bereichs werden im Themenbereich <<maerkte#, Multi-Channel>> verwendet und bei den Marktplätzen erläutert.

2+| *Aktionen*

|*Variante löschen*
|Aktivieren, um gewählte Varianten zu löschen. +
*_Hinweis:_* Wenn Hauptvarianten gewählt wurden, werden diese Hauptvarianten nicht gelöscht.

2+| *Tags*

|*Tags hinzufügen*
|Aktivieren, um Tags mit den gewählten Varianten zu verknüpfen. In das Feld klicken und die Tags wählen, die mit den Varianten verknüpft werden sollen.

|*Tags entfernen*
|Aktivieren, um Tag-Verknüpfungen für die gewählten Varianten zu entfernen. In das Feld klicken und die Tags wählen, die von den Varianten entfernt werden sollen.

|*Alle Tags entfernen*
|Aktivieren, um für die gewählten Varianten alle Tag-Verknüpfungen zu entfernen.

2+| *Mandant (Shop) zuordnen*

|**Verknüpfung erstellen**
|Aktivieren und einen oder mehrere Mandanten (Shops) aktivieren, um die gewählten Varianten in diesen Webshops verfügbar zu machen.

2+| *Preise*

|**Preiskalkulation**
|Aktivieren und Preiskalkulation wählen.

|**Preisänderung**
|Aktivieren und Einstellungen vornehmen, um einen Preis der gewählten Varianten zu bearbeiten. Um nur die Operatoren auf einen Preis anzuwenden, für Quelle und Ziel denselben Verkaufspreis wählen. +
**Absolut** = Operator wählen und einen absoluten Wert eingeben. +
= Der eingegebene Wert wird als neuer Preis gespeichert. +
+ Der bisherige Preis wird um den eingegebenen Betrag erhöht. +
- Der bisherige Preis wird um den eingegebenen Betrag gesenkt. +
/ Der bisherige Preis wird durch den eingegebenen Wert geteilt. +
* Der bisherige Preis wird mit dem eingegebenen Wert multipliziert. +
**Prozentual** = Operator wählen und einen Prozentwert eingeben. +
+ Der bisherige Preis wird um den eingegebenen Prozentwert erhöht. +
- Der bisherige Preis wird um den eingegebenen Prozentwert gesenkt. +
**Quellpreis** = Den Verkaufspreis aus der Dropdown-Liste wählen, dessen Preis übernommen werden soll. +
**Zielpreis** = Den Verkaufspreis aus der Dropdown-Liste wählen, der aktualisiert werden soll. +
→ Wenn für den Zielverkaufspreis noch kein Preis an der Variante gespeichert ist, wird der Verkaufspreis verknüpft und der neue Preis gespeichert. +
→ Bei aktivierter Vererbung wird die Vererbung aller Preise für die gewählten Varianten deaktiviert und alle Preise werden direkt an der Variante gespeichert.

2+| *Versand*

|**Portoaufschlag 1; +
Portoaufschlag 2**
|Aktivieren und Wert eingeben, um den Portoaufschlag für die gewählten Varianten zu speichern.

2+| *Sonstiges*

|**GTIN generieren**
|Aktivieren und GTIN-Typ wählen, um für die gewählten Varianten GTINs dieses Typs aus <<artikel/einstellungen/barcodes#200, Nummernkreis>> zu generieren.

|**Gewicht brutto; +
Gewicht netto**
|Aktivieren und Wert eingeben, um dieses Gewicht für die gewählten Varianten zu speichern.

2+| *Verfügbarkeit*

|**Aktiv**
|Aktivieren, um die Varianten im Webshop und auf Marktplätzen anzubieten. Varianten werden erst im Webshop angezeigt, wenn die Varianten aktiv sind.

|Verfügbarkeitssymbole
|Aktivieren und Verfügbarkeitsstufe für die Varianten wählen.

|*Unsichtbar: in Artikelauflistung*
|Aktivieren, um die Varianten in der Artikelauflistung des Webshops unsichtbar zu stellen. Die Varianten werden dann weder über die Kategorien noch über die Suche angezeigt. Die Varianten sind nur über die URL der Variante aufrufbar.

|*Artikelauflistung: sichtbar wenn Netto-WB positiv*;
*Artikelauflistung: unsichtbar wenn kein Netto-WB*
|Aktivieren, damit die Varianten bei positivem Nettowarenbestand in der Artikelauflistung sichtbar sind und unsichtbar gestellt werden, wenn kein Nettowarenbestand vorhanden ist. +
Wenn die Optionen aktiviert sind und kein Netto-Warenbestand verfügbar ist, können die Varianten nur über die direkte URL aufgerufen werden. Die Variante wird nicht in den Kategorien, in den Suchergebnissen und in den Artikellisten (Shop-Aktionen, Cross-Selling, zuletzt gesehene Artikel) angezeigt.

2+| *Bestand*

|**Beschränkung**
|Aktivieren und Beschränkung des Warenbestands wählen.

|**Hauptlager**
|Aktivieren und Hauptlager für die gewählten Varianten wählen.

|**Meldebestand**
|Aktivieren, Lager wählen und Wert eingeben, bei dem eine Nachbestellung für die gewählten Varianten erfolgen soll.

|**Maximalbestand**
|Aktivieren, Lager wählen und Wert eingeben, um den Bestand der gewählten Varianten zu begrenzen.

|**Lagerreichweite**
|Aktivieren, Lager wählen und Zeitraum in Tagen eingeben, den der Warenbestand der gewählten Varianten bis zur nächsten Nachbestellung reichen soll.

|**Lagerorttyp**
|Aktivieren, Lager wählen und Lagerorttyp je nach Größe der gewählten Varianten wählen.

|**Zone**
|Aktivieren, Lager wählen und Zone für die gewählten Varianten wählen, wenn das Lager in Zonen eingeteilt ist.

|*Verfügbar bei positivem Netto-WB*; +
*Nicht verfügbar bei keinem Netto-WB*
|Aktivieren, damit die gewählten Varianten bei positivem Nettowarenbestand verfügbar und kaufbar werden oder nicht kaufbar werden, wenn kein Nettowarenbestand vorhanden ist. Diese beiden Funktionen ergänzen sich und funktionieren im Zusammenspiel mit der Einstellung **Auf Netto-WB** unter **Beschränkung**.

|*Webshop: sichtbar bei positivem Netto-WB*; +
*Webshop: unsichtbar bei keinem Netto-WB*
|Aktivieren, damit die gewählten Varianten bei positivem Nettowarenbestand im Webshop sichtbar werden oder unsichtbar werden, wenn kein Nettowarenbestand vorhanden ist. Diese beiden Funktionen ergänzen sich und funktionieren im Zusammenspiel mit der Einstellung Auf Netto-WB unter Beschränkung.

2+| *Kategorie*

|**Kategorie**
|Aktivieren und Kategorie wählen. Die gewählten Varianten werden mit der Kategorie verknüpft. Bereits vorhandene Kategorieverknüpfungen bleiben bestehen.

|**Alte Kategorieverknüpfung löschen**
|Aktivieren, um alte Kategorieverknüpfungen der gewählten Varianten zu löschen.

2+|*Automatisch aus Paketbestandteilen berechnen*

|*EK netto*
|Nettoeinkaufspreis automatisch berechnen. +
Diese Einstellung ist nur für <<artikel/anwendungsfaelle/multipacks-pakete-sets#2500, Artikelpakete>> relevant.

|*GLD EK netto*
|Gleitenden Nettoeinkaufspreis automatisch berechnen. +
Diese Einstellung ist nur für <<artikel/anwendungsfaelle/multipacks-pakete-sets#2500, Artikelpakete>> relevant.

|*Gewicht brutto*
|Bruttogewicht automatisch berechnen. +
Diese Einstellung ist nur für <<artikel/anwendungsfaelle/multipacks-pakete-sets#2500, Artikelpakete>> relevant.

|*Gewicht netto*
|Nettogewicht automatisch berechnen. +
Diese Einstellung ist nur für <<artikel/anwendungsfaelle/multipacks-pakete-sets#2500, Artikelpakete>> relevant.

2+| *Vererbung* (nur **Varianten-Gruppenfunktion**)

|**Preise**
|Aktivieren, um die Vererbung der Preise der Hauptvariante an die in der Artikelübersicht markierten Varianten zu ändern. +
Kontrollkästchen rechts neben **Preise** aktiviert = Aktiviert die Vererbung der Preise der Hauptvariante an die markierten Varianten. Bisher an der Variante gespeicherte Preise werden überschrieben. +
Kontrollkästchen rechts neben **Preise** nicht aktiviert = Deaktiviert die Vererbung der Preise der Hauptvariante an die in der Artikelübersicht markierten Varianten. Die Preise der Hauptvariante werden an der Variante gespeichert. +
**__Hinweis:__** Diese Gruppenfunktion steuert die Vererbung aller Preise der Hauptvariante. Eine Vererbung einzelner Preise an eine Variante ist nicht möglich.

|**Verfügbarkeit**
|Aktivieren, um die Vererbung der Verfügbarkeitsstufen der Hauptvariante an die in der Artikelübersicht markierten Varianten zu ändern. +
Kontrollkästchen rechts neben **Verfügbarkeit** aktiviert = Aktiviert die Vererbung der Verfügbarkeitsstufe der Hauptvariante an die markierten Varianten. Die bisherige Verfügbarkeitsstufe der Variante wird überschrieben. +
Kontrollkästchen rechts neben **Verfügbarkeit** nicht aktiviert = Deaktiviert die Vererbung der Verfügbarkeitsstufe der Hauptvariante an die in der Artikelübersicht markierten Varianten. Die Verfügbarkeitsstufe der Hauptvariante wird an der Variante gespeichert.

|**Märkte**
|Aktivieren, um die Vererbung der Marktplatzverfügbarkeit der Hauptvariante an die in der Artikelübersicht markierten Varianten zu ändern. +
Kontrollkästchen rechts neben **Märkte** aktiviert = Aktiviert die Vererbung der Märkte der Hauptvariante an die markierten Varianten. Die bisher aktivierten Märkte der Variante werden überschrieben. +
Kontrollkästchen rechts neben **Märkte** nicht aktiviert = Deaktiviert die Vererbung der Märkte der Hauptvariante an die in der Artikelübersicht markierten Varianten. Die aktivierten Märkte der Hauptvariante werden an der Variante gespeichert. +
**__Hinweis:__** Diese Gruppenfunktion steuert die Vererbung aller Märkte der Hauptvariante. Eine Vererbung einzelner Märkte an eine Variante ist nicht möglich.

|**Mandanten (Shops)**
|Aktivieren, um die Vererbung der Mandantenverfügbarkeit der Hauptvariante an die in der Artikelübersicht markierten Varianten zu ändern. +
Kontrollkästchen rechts neben **Mandanten (Shops)** aktiviert = Aktiviert die Vererbung der Mandanten (Shops) der Hauptvariante an die markierten Varianten. Die bisher aktivierten Mandanten (Shops) der Variante werden überschrieben. +
Kontrollkästchen rechts neben **Mandanten (Shops)** nicht aktiviert = Deaktiviert die Vererbung der Mandanten (Shops) der Hauptvariante an die in der Artikelübersicht markierten Varianten. Die aktivierten Mandanten (Shops) der Hauptvariante werden an der Variante gespeichert. +
**__Hinweis:__** Diese Gruppenfunktion steuert die Vererbung aller Mandanten (Shops) der Hauptvariante. Eine Vererbung einzelner Mandanten (Shops) an eine Variante ist nicht möglich.

|**Lieferanten**
|Aktivieren, um die Vererbung der Lieferanten der Hauptvariante an die in der Artikelübersicht markierten Varianten zu ändern. +
Kontrollkästchen rechts neben **Lieferant** aktiviert = Aktiviert die Vererbung der Lieferanten der Hauptvariante an die markierten Varianten. Die bisher aktivierten Lieferanten der Variante werden überschrieben. +
Kontrollkästchen rechts neben **Lieferant** nicht aktiviert = Deaktiviert die Vererbung der Lieferanten der Hauptvariante an die in der Artikelübersicht markierten Varianten. Die aktivierten Lieferanten der Hauptvariante werden an der Variante gespeichert. +
**__Hinweis:__** Diese Gruppenfunktion steuert die Vererbung aller Lieferanten der Hauptvariante. Eine Vererbung einzelner Lieferanten an eine Variante ist nicht möglich.

|**Kategorien**
|Aktivieren, um die Vererbung der Kategorien der Hauptvariante an die in der Artikelübersicht markierten Varianten zu ändern. +
Kontrollkästchen rechts neben **Kategorien** aktiviert = Aktiviert die Vererbung der Kategorien der Hauptvariante an die markierten Varianten. Die bisher aktivierten Kategorien der Variante werden überschrieben. +
Kontrollkästchen rechts neben **Kategorien** nicht aktiviert = Deaktiviert die Vererbung der Kategorien der Hauptvariante an die in der Artikelübersicht markierten Varianten. Die aktivierten Kategorien der Hauptvariante werden an der Variante gespeichert. +
**__Hinweis:__** Diese Gruppenfunktion steuert die Vererbung aller Kategorien der Hauptvariante. Eine Vererbung einzelner Kategorien an eine Variante ist nicht möglich.

|**Lager**
|Aktivieren, um die Vererbung der Lager der Hauptvariante an die in der Artikelübersicht markierten Varianten zu ändern. +
Kontrollkästchen rechts neben **Lager** aktiviert = Aktiviert die Vererbung der Lager der Hauptvariante an die markierten Varianten. Die bisher aktivierten Lager der Variante werden überschrieben. +
Kontrollkästchen rechts neben **Lager** nicht aktiviert = Deaktiviert die Vererbung der Lager der Hauptvariante an die in der Artikelübersicht markierten Varianten. Die aktivierten Lager der Hauptvariante werden an der Variante gespeichert. +
**__Hinweis:__** Diese Gruppenfunktion steuert die Vererbung aller Lager der Hauptvariante. Eine Vererbung einzelner Lager an eine Variante ist nicht möglich.

|**Eigenschaften**
|Aktivieren, um die Vererbung der Eigenschaften der Hauptvariante an die in der Artikelübersicht markierten Varianten zu ändern. +
Kontrollkästchen rechts neben **Eigenschaften** aktiviert = Aktiviert die Vererbung der Eigenschaften der Hauptvariante an die markierten Varianten. Die bisher aktivierten Eigenschaften der Variante werden überschrieben. +
Kontrollkästchen rechts neben **Eigenschaften** nicht aktiviert = Deaktiviert die Vererbung der Eigenschaften der Hauptvariante an die in der Artikelübersicht markierten Varianten. Die aktivierten Eigenschaften der Hauptvariante werden an der Variante gespeichert. +
**__Hinweis:__** Diese Gruppenfunktion steuert die Vererbung aller Eigenschaften der Tabs *Einstellungen* und *Texte* der Hauptvariate. Eine Vererbung einzelner Eigenschaften an eine Variante ist nicht möglich.

|*Tags*
|Aktivieren, um die Vererbung der Tags der Hauptvariante an die in der Artikelübersicht markierten Varianten zu ändern. +
Kontrollkästchen rechts neben *Tags* aktiviert = Aktiviert die Vererbung der Tags der Hauptvariante an die markierten Varianten. Die bisher mit der Variante verknüpften Tags werden überschrieben. +
Kontrollkästchen rechts neben *Tags* nicht aktiviert = Deaktiviert die Vererbung der Tags der Hauptvariante an die in der Artikelübersicht markierten Varianten. Die verlinkten Tags werden entfernt. Die Variante wird ohne Tags gespeichert. +
*_Hinweis:_* Diese Gruppenfunktion steuert die Vererbung aller Tags der Hauptvariante. Eine Vererbung einzelner Tags an eine Variante ist nicht möglich.
|====

[.instruction]
Stapelverarbeitung ausführen:

. Öffne das Menü **Artikel » Stapelverarbeitung**.
. Wechsele in das Tab **Varianten**.
. Wähle die Filter gemäß <<tabelle-variantenfilter-stapelverarbeitung>>.
. Nimm die Einstellungen gemäß <<tabelle-mehrere-varianten-bearbeiten>> vor.
. Klicke auf **Anwenden**, um die Einstellungen an den Varianten vorzunehmen.

[[tabelle-variantenfilter-stapelverarbeitung]]
.Filteroptionen für die **Stapelverarbeitung** von Varianten
[cols="1,2"]
|====
| Einstellung | Erläuterung

|**Varianten-ID**
| Operator wählen und eine ID eingeben, um nach der Variante mit dieser ID zu suchen.

|**Artikel-ID**
| Operator wählen und eine ID eingeben, um nach dem Artikel mit dieser ID zu suchen. Ermöglicht es, alle Varianten eines Artikels zu bearbeiten.

|**Markierung 1; +
Markierung 2**
| Markierung wählen, um nur Varianten mit dieser Markierung zu bearbeiten.

|**Hersteller**
| Einen Hersteller oder **ALLE** wählen, um nur Varianten zu bearbeiten, die vom gewählten Hersteller stammen.

|**Zustand**
|Zustand wählen, um nur Varianten mit diesem Zustand zu bearbeiten.

|**Hauptvarianten**
|Aktivieren, um nur Hauptvarianten zu bearbeiten.

|**Ohne Kategorie**
|Aktivieren, um nur Varianten zu bearbeiten, die nicht mit einer Kategorie verknüpft sind.

|**Kategorien**
|Kategorie wählen, um nur Varianten dieser Kategorie zu bearbeiten.

|**Tags**
|Tags wählen, um nur Varianten zu bearbeiten, die mit diesen Tags verknüpft sind. +
// xxx Reihenfolge prüfen!
|====


[#1090]
== Artikel und Varianten kopieren

In diesem Kapitel erfährst du, wie du Artikel und Varianten kopierst. Wenn du einen Artikel kopierst, wird eine Kopie des Artikels und seiner Varianten erstellt. Folgende Informationen werden kopiert:

* Artikeldaten, die du im Tab **Global** eingibst
* Artikeltexte
* Freitextfelder
* Merkmale
* Bilder
* Cross-Selling-Einstellungen
* Verkaufspreise samt hinterlegter Werte
* Barcodes samt hinterlegter Werte
* Artikelpakete
* Eigenschaften

Nicht kopiert werden:

* Listings
* Media-Dateien
* Verfügbarkeit der Hauptvariante
* Maße
* Kosten


Die Variantennummern der Hauptvariante und Varianten des kopierten Artikels werden neu vergeben. Diese Variantennummern änderst du im Tab <<artikel/artikel-verwalten#170, Einstellungen>> einer Variante. Nach dem Kopieren kann der neue <<artikel/artikel-verwalten#30, Artikel>> bearbeitet werden. Um einen Artikel zu kopieren, gehe wie folgt vor.

[.instruction]
Artikel kopieren:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Klicke in der Symbolleiste des Artikels auf **Kopieren**. +
→ Das Fenster **Kopieren** wird geöffnet.
. Klicke auf **Kopieren**. +
→ Der Artikel wird kopiert. +
→ Die Kopie wird in einem neuen Tab geöffnet.

Kopiere eine Artikelvariante, um diese Variante in verschiedenen Mengen anzubieten. Sämtliche Variantendaten werden beim Kopieren übernommen. Hauptvarianten können nicht kopiert werden.

[.instruction]
Variante kopieren:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**.
. Öffne die Variante.
. Klicke in der Symbolleiste der Variante auf **Kopieren**. +
→ Das Fenster **Kopieren** wird geöffnet.
. Gib den Inhalt ein.
. *_Optional:_* Wähle eine Einheit.
. Klicke auf **Kopieren**. +
→ Die Variante wird kopiert. +
→ Die Kopie wird in einem neuen Tab geöffnet.

[IMPORTANT]
.Verkaufspreise und Barcodes prüfen
====
Prüfe nach dem Kopieren die <<artikel/artikel-verwalten#240, Verkaufspreise>> und <<artikel/artikel-verwalten#250, Barcodes>> und passe die Werte bei Bedarf an.
====

// NEXT: 4400
