= Vorbereitende Einstellungen
:lang: de
include::{includedir}/_header.adoc[]
:description: Bereite dein plentymarkets System auf den Verkauf von Artikeln vor. Treffe vorbereitende Einstellungn, die später mit deinen Artikeln und Varianten verknüpft werden.
:url: artikel/einstellungen
:icons: font
:position: 20
:docinfodir: /workspace/manual-adoc
:docinfo1:

//Text mit includes ersetzen, Textteile stammen aus der Seite "artikel/einleitung" und aus "artikel/einleitung/struktur"

Zu deinen Artikeldaten gehören diverse Angaben, wie z.B. Kategorien, Preise, Hersteller, Beschreibungstexte und Bilder. Manchmal ist allerdings ein bisschen Vorarbeit nötig.

Bevor du einen Artikel in eine bestimmte Kategorie einsortieren kannst, muss die Kategorie erst einmal in plentymarkets existieren. Bevor du den Hersteller eines Artikels auswählen kannst, müssen die Herstellerdaten in plentymarkets vorhanden sein.

Solche vorbereitende Systemeinstellungen werden zuerst im Menü *Einrichtung* verwaltet und anschließend mit Artikeln oder Varianten verknüpft.

Zu den wichtigsten Systemeinstellungen gehören:

* <<artikel/einstellungen/kategorien#, Kategorien>>, die deine Produkte gruppieren.
* <<artikel/einstellungen/einheiten#, Einheiten>>, die den Inhalt deiner Varianten definieren.
* <<artikel/einstellungen/attribute#, Attribute>>, die deine Produkte charakterisieren und dabei Varianten bilden.
* <<artikel/einstellungen/eigenschaften#, Merkmale und Eigenschaften>>, die deine Produkte charakterisieren, _ohne_ dabei Varianten zu bilden.
* <<fulfillment/versand-vorbereiten#1000, Versandprofile>>, die deine angebotenen Versandservices und Portokosten definieren.
* <<artikel/einstellungen/hersteller#, Hersteller>>, die die Namen, Kontaktdaten, IDs und Provisionen deiner Hersteller beinhalten.
* <<artikel/einstellungen/preise#, Verkaufspreise>>, die die Bedingungen definieren, unter denen eine Variante zu einem bestimmten Preis verkauft wird.
