= Frontend-Artikelsuche verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Facetten, Webshopsuche, Facettensuche
:position: 800

Die Frontend-Artikelsuche ermöglicht es Ihren Kundinnen und Kunden, Ihr Produktsortiment im Webshop zu durchsuchen. Im Template-Plugin Ceres ist für die Artikelsuche im Webshop standardmäßig die Facettensuche aktiviert. Im alten Design Callisto wird die Facettensuche im Menü *System » Mandant » Mandant wählen » Webshop » Artikelsuche* aktiviert.

Hier erfahren Sie, wie Sie Facetten und Facettenwerte erstellen und wie Sie diese Facetten in Callisto und Ceres nutzen.

[NOTE]
.Callisto mit Standard-Suche
====
Bei Webshops mit dem alten Design Callisto, für die im Menü *System » Mandant » Mandant wählen » Webshop » Artikelsuche* die Option *Standard-Suche* aktiviert ist, wird der Index der Backend-Artikelsuche auch für die Artikelsuche im Frontend verwendet.
====

[#90]
== Facettensuche einrichten

Facetten sind die Filtermöglichkeiten, mit denen Suchergebnisse im Webshop nach bestimmten Kriterien, also Facetten, verfeinert werden. Der Vorteil der Facettensuche ist, dass das Suchergebnis nicht zwangsweise analog zur Auswahl des Kriteriums reduziert wird, sondern immer wieder die gesamte Datenbank nach dem Kriterium durchsucht wird. Dies ermöglicht eine intuitive Benutzerführung durch die Suche und vermeidet, dass Suchergebnisse durch eine ungünstige Vorauswahl verfälscht werden.

Die Filternavigation richten Sie flexibel ein. Die angezeigten Artikel in einer Kategorie können mit Facetten nicht nur nach Merkmalen/Eigenschaften, sondern auch nach folgenden Kriterien weiter eingeschränkt werden:

* Nach Attributen, Merkmalen und Eigenschaften
* Nach Herstellern
* Nach der Verfügbarkeit der Artikel
* Nach Preissegment

Diese vier Facettentypen verbinden Sie in plentymarkets mit verschiedenen Werten, die das Filterergebnis bestimmen. Je mehr Facetten Sie erstellen und mit Werten verknüpfen, desto umfangreicher wird die im Webshop dargestellte Filterauswahl.

Die Konfiguration besteht aus mehreren Schritten. Zunächst werden Facetten erstellt, anschließend durch weitere Einstellungen näher bestimmt und schließlich mit den gewünschten Werten verknüpft. Zudem muss im Menü *System » Mandant » Mandant wählen » Webshop » Artikelsuche* die Option *Facettensuche* eingestellt sein.

[TIP]
.Artikel mit Facetten verknüpfen
====
Eine direkte Verknüpfung von Artikeln mit den einzelnen Facetten ist nicht nötig. Die Zuordnung Ihrer Artikel zu Facetten erfolgt automatisch durch die <<artikel/frontend-artikelsuche-verwalten#140, Verknüpfung der Facette mit Werten>>, die am Artikel hinterlegt sein müssen.
====

[#100]
=== Facette erstellen

Für die Facettensuche erstellen Sie zunächst Facetten, zum Beispiel die Facette "Farbe" des Typs *Attribut/Merkmal*.

[.instruction]
Facette erstellen:

. Öffnen Sie das Menü *System » Mandant » Global » Dienste » Facettensuche*.
. Klicken Sie auf *Neu*.
. Tragen Sie einen *Namen* für die Facette in der Systemsprache ein. Dieser Name wird im Webshop angezeigt.
. Wählen Sie einen *Typ* aus der Dropdown-Liste. Beachten Sie die Erläuterungen in <<tabelle-verfuegbare-facettentypen>>.
. Tragen Sie die *Position* ein, an der die Facette im Webshop angezeigt werden soll.
. *Speichern* Sie die Einstellungen. +
→ Die Facette wird erstellt.


[[tabelle-verfuegbare-facettentypen]]
.Verfügbare Facettentypen
[cols="1,3"]
|====
|Facettentyp |Erläuterung

|*Preis*
|Facetten des Typs *Preis* müssen nicht mit Werten verknüpft werden, da der Filter vom kleinsten bis zum größten Preis einer Kategorie individuell eingeschränkt werden kann.

|*Attribut/Merkmal*
|Facetten des Typs *Attribut/Merkmal* werden mit Attributen, Merkmalen und Eigenschaften im System verknüpft und stellen so vielfältige Filtermöglichkeiten her, zum Beispiel nach Farben, Größen etc.

|*Verfügbarkeit*
|Facetten des Typs *Verfügbarkeit*, zum Beispiel "Kurzfristig lieferbar", werden mit den im Menü <<artikel/artikel-verwalten#180, System » Artikel » Verfügbarkeit>> erstellten Verfügbarkeiten verknüpft.

|*Hersteller*
|Facetten des Typs *Hersteller*, zum Beispiel "Adidas", werden mit den im Menü <<artikel/artikel-verwalten#560, System » Artikel » Hersteller>> erstellten Herstellern verknüpft.
|====

[#110]
=== Facette bearbeiten

Nachdem Sie eine Facette erstellt haben, wird die Facette geöffnet. Es stehen vier Tabs zur Verfügung, um weitere Einstellungen vorzunehmen und Werte zu verknüpfen.

[#120]
==== Facetteneinstellungen vornehmen

Im Tab *Einstellungen* Nehmen Sie die Einstellungen wie unten beschrieben vor.

[.instruction]
Facette bearbeiten:

. Öffnen Sie das Menü *System » Mandant » Global » Dienste » Facettensuche*.
. Öffnen Sie die Facette. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-facetten-bearbeiten>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-facetten-bearbeiten]]
.Facetten bearbeiten; Tab *Einstellungen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Typ*
|Zeigt den beim Erstellen der Facette gewählten Typen an. Der Typ ist nicht änderbar.

|*Sortierung*
|Legt die Sortierung des Suchergebnisses fest. Je nach Auswahl werden die Artikel nach der *Trefferquote*, der *Position* oder alphabetisch von *A-Z* sortiert.

|*Position*
|Zeigt die Position an, die beim Erstellen der Facette eingegeben wurde. Die Position ist änderbar.

|*CSS-Klasse*
|Einen CSS-Namen hinterlegen. Dieser Name wird als Template-Variable im CMS-Bereich zur Verfügung gestellt, sodass zu jeder Facette eine eigene Klasse hinterlegt werden kann.

|*Auswahlart*
|Die Auswahlart wählen. +
*Einschränkend* = Schränkt den Filter mit dem gewählten Wert weiter ein. Alle Artikel werden angezeigt, die diesen Wert besitzen und die Filterkriterien vorher gewählter Filter erfüllen. +
*Mehrfach* = Lässt eine Mehrfachauswahl von Ergebnissen zu, zum Beispiel die Auswahl mehrerer Hersteller, deren Artikel gemeinsam angezeigt werden. +

|*Minimale Trefferanzahl*
|Legt fest, wie viele Ergebnisse es für einen Facettenwert mindestens geben muss, damit der Facettenwert im Webshop angezeigt wird.

|*Maximal angezeigte Facettenwerte*
|Legt fest, wie viele Facettenwerte pro Facette höchstens angezeigt werden. 250 Facettenwerte können maximal angezeigt werden.
|====

[#130]
==== Facettenname in zusätzlicher Sprache speichern

Beim Erstellen einer Facette geben Sie einen Namen in der Standardsprache des Systems ein. Dieser Name wird im Webshop angezeigt. Wenn Sie zusätzlichen Sprachen anbieten, geben Sie im Tab *Name* den Namen der Facette in diesen Sprachen ein. Gehen Sie dazu wie unten beschrieben vor.


[.instruction]
Facettenname in zusätzlicher Sprache speichern:

. Öffnen Sie das Menü *System » Mandant » Global » Dienste » Facettensuche*.
. Öffnen Sie die Facette. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechseln Sie in das Tab *Name*.
. Geben Sie einen Namen für die gewünschte Sprache ein.
. *Speichern* Sie die Einstellungen.

[#140]
=== Facette mit Wert verknüpfen

Im Tab *Werte* einer Facette verknüpfen Sie die Facette mit verschiedenen Werten. Im Beispiel der Facette Farbe des Typs *Attribut/Merkmal* erstellen Sie zum Beispiel die Werte weiß, schwarz, rot, blau etc. und verknüpfen diese Werte mit den vorhandenen Attributen, Merkmalen und Eigenschaften im System. Gehen Sie dazu wie unten beschrieben vor.

[#150]
==== Wert erstellen

[.instruction]
Wert erstellen:

. Öffnen Sie das Menü *System » Mandant » Global » Dienste » Facettensuche*.
. Öffnen Sie die Facette.
. Wechseln Sie in das Tab *Werte*.
. Klicken Sie links unten auf das *grüne Plus*. +
→ Das Fenster *Wert erstellen* wird angezeigt.
. Geben Sie einen *Namen* für den Wert in der Systemsprache ein.
. Geben Sie eine *Position* ein.
. *Speichern* Sie die Einstellungen. +
→ Der neue Wert wird erstellt.
. *_Optional:_* Geben Sie im Tab *Name* Übersetzungen für den Namen des Werts ein.
. *_Optional:_* Geben Sie im Tab *Einstellungen* eine CSS-Klasse ein.

[#160]
==== Wert verknüpfen

Verknüpfen Sie nun den Wert mit den Daten im System. Sie können einem Facettenwert mehrere Backend-Werte zuordnen. Zum Beispiel können Sie bei Facetten des Typs *Attribut/Merkmal* Attribute, Merkmale und Eigenschaften im System in einem Filter zusammenfassen und so zusammen in einem Ergebnis ausgegeben.

[.instruction]
Facettenwert mit Backend-Wert verknüpfen:

. Öffnen Sie das Menü *System » Mandant » Global » Dienste » Facettensuche*.
. Öffnen Sie die Facette.
. Wechseln Sie in das Tab *Werte*.
. Klicken Sie auf den Wert.
. Wechseln Sie in das Tab *Verknüpfung*.
. Klicken Sie auf den Backend-Wert, der verknüpft werden soll.
. Klicken Sie links unten auf *Verknüpfen*. +
→ Der Backend-Wert wird mit dem Wert der Facette verknüpft.
. *_Optional:_* Verknüpfen Sie weitere Werte.
. *Speichern* Sie die Einstellungen.

[#170]
=== Facetten mit Bildern verknüpfen

Im Tab *Bilder* verknüpfen Sie Facetten und Facettenwerte mit Bildern. Verknüpfen Sie zum Beispiel die Hersteller in Ihrem Webshop mit Bildern, wenn Sie nicht den Namen der Herstellers, sondern das Logo des Herstellers anzeigen möchten.

[#180]
==== Bild hochladen

[.instruction]
Bild hochladen:

. Öffnen Sie das Menü *System » Mandant » Global » Dienste » Facettensuche*.
. Öffnen Sie die Facette.
. Wechseln Sie in das Tab *Bilder*.
. Klicken Sie auf *Dateien hochladen*.
. Navigieren Sie zum Speicherort der Bilddatei.
. Wählen Sie die Bilddatei. +
→ Die Bilddatei wird hochgeladen.
. *Speichern* Sie die Einstellungen.

[#190]
==== Bild verknüpfen

Verknüpfen Sie nun das Bild mit den Daten im System. Pro Bild kann ein Wert verknüpft werden.

[.instruction]
Bild verknüpfen:

. Öffnen Sie das Menü *System » Mandant » Global » Dienste » Facettensuche*.
. Öffnen Sie die Facette.
. Wechseln Sie in das Tab *Bilder*.
. Zeigen Sie mit dem Cursor auf das Bild. +
→ Im unteren Bereich des Bilds wird eine Dropdown-Liste mit Werten angezeigt.
. Klicken Sie in der Dropdown-Liste auf den Wert.
. *Speichern* Sie die Einstellungen. +
→ Das Bild wird mit dem Wert verknüpft. +
→ Das verknüpfte Bild wird mit rotem Rand dargestellt. +
→ Der Name des Werts wird im Bild angezeigt.

[#200]
=== Facetten mit Mandant verknüpfen

Nachdem Sie Facetten erstellt haben, verknüpfen Sie im Menü *System » Mandant » Mandant wählen » Dienste » Facettenverknüpfungen* diese Facetten mit dem Mandanten, in dem die Facetten als Filter zur Verfügung stehen sollen. Sie wählen pro Mandant, welche Facetten für den Shop relevant sind und welche nicht. Änderungen, die Sie vornehmen, werden in Echtzeit übertragen. Gehen Sie wie unten beschrieben vor, um Facetten mit einem Mandanten zu verknüpfen.

[NOTE]
.Facette des Typs Preis
====
Pro Mandant kann nur eine Facette des Typs Preis verknüpft werden.
====

[.instruction]
Facetten im Webshop verknüpfen:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Dienste » Facettenverknüpfungen*.
. Klicken Sie in der Liste links auf die Facette, die Sie mit diesem Shop verknüpfen möchten.
. Klicken Sie links unten auf *Facette verknüpfen*.
. *_Optional:_* Aktivieren Sie die Option *Bilder bereitstellen*, um mit den Facetten verknüpfte Bilder im Webshop anzuzeigen.
. Wiederholen Sie den Vorgang für alle weiteren Facetten, die verknüpft werden sollen.
. *Speichern* Sie die Einstellungen. +
→ Die Facette wird im Webshop verknüpft.

[#210]
== Facettensuche im alten Design Callisto nutzen

Im alte Design Callisto kann für die Frontend-Suche verschiedene Suchen genutzt werden. Welche Suche verwendet wird, legen Sie im Menü *System » Mandant » Mandant wählen » Webshop » Artikelsuche* fest. Die folgenden Optionen sind verfügbar:

* *Standard-Suche* +
→ Wenn die Option *Standard-Suche* aktiviert ist, wird für die Artikelsuche im Frontend der <<artikel/artikel-verwalten#385, Index der Backend-Artikelsuche>> verwendet.
* *Findologic* +
→ Wie Sie die Artikelsuche über Findologic einrichten, erfahren Sie auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/extras/findologic#, Findologic>>.
* *Facettensuche* +
→ Wie Sie die alte Facettensuche einrichten, erfahren Sie im Kapitel <<artikel/frontend-artikelsuche-verwalten#220, Callisto mit alter Facettensuche nutzen>>.
* *Facettensuche (ElasticSearch - BETA)* +
→ Wie Sie die neue Facettensuche (ElasticSearch - BETA) einrichten, erfahren Sie im Kapitel <<artikel/frontend-artikelsuche-verwalten#270, Callisto mit Facettensuche (Elastic Search- BETA) nutzen>>.

[#220]
=== Callisto mit alter Facettensuche nutzen

Die alte Facettensuche nutzen Sie, indem Sie im Menü *System » Mandant » Mandant wählen » Webshop » Artikelsuche* die Option *Facettensuche* aktivieren. Richten Sie die Facettensuche wie im Kapitel <<artikel/frontend-artikelsuche-verwalten#90, Facettensuche einrichten>> ein und gehen Sie dann wie unten beschrieben vor, um die alte Facettensuche in Callisto zu nutzen.

[#230]
==== Callisto + alte Facettensuche: Such-Index definieren

Im Tab *Such-Index* legen Sie Kriterien für eine verbesserte Suche im Webshop fest. Eine facettenbasierte Suche bietet eine hohe Fehlertoleranz. Suchbegriffe werden also auch bei Tippfehlern erkannt. Artikelnamen oder Herstellernamen müssen nicht exakt eingegeben werden, um zu einem Ergebnis zu führen. Zum Beispiel werden Produkte des Herstellers "adidas" auch bei fehlerhaften Eingaben wie "addidas" oder "adids" gefunden. Konfigurieren Sie dafür die folgenden 3 Tabs:

* Im Tab *Felder* aktivieren Sie die Felder, die bei der Suche berücksichtigt werden sollen, bestimmen die Gewichtung und legen fest, welche Felder für die unscharfe Suche berücksichtigt werden sollen.
* Im Tab *Einstellungen* nehmen Sie Einstellungen für die unscharfe Suche vor.
* Im Tab *Volltext* legen Sie fest, welche Artikeldaten bei einer Volltextsuche berücksichtigt werden.

[#240]
==== Callisto + alte Facettensuche: Felder zum Suchindex hinzufügen

Gehen Sie wie unten beschrieben vor, um Felder zum Suchindex hinzuzufügen. Bei der Suche im Webshop werden nur aktivierte Felder durchsucht.

[.instruction]
Suchfelder definieren:

. Öffnen Sie das Menü *System » Mandant » Global » Dienste » Facettensuche*.
. Wechseln Sie in das Tab *Such-Index*. +
→ Das Tab *Felder* wird angezeigt.
. Aktivieren Sie in der Spalte *Aktiv* die Felder, die bei der Suche berücksichtigt werden sollen.
. Geben Sie für die aktivierten Felder eine Gewichtung zwischen 1 und 1000 ein. +
→ Je höher die Zahl, desto höher die Priorität im Suchergebnis, wenn in mehreren Feldern mit dem Suchbegriff übereinstimmende Ergebnisse gefunden werden. Ergebnisse aus dem Feld mit der höchsten Zahl werden also zuerst gelistet.
. *_Optional:_* Aktiveren Sie für die aktivierten Felder die Option *Unscharfe Suche*.
. *_Optional:_* Aktivieren Sie die Option *Volltext*.
. *Speichern* Sie die Einstellungen.

[#250]
==== Callisto + alte Facettensuche: Unscharfe Suche anpassen

Passen Sie nun die Einstellungen für die unscharfe Suche an.

[.instruction]
Unscharfe Suche anpassen:

. Öffnen Sie das Menü *System » Mandant » Global » Dienste » Facettensuche*.
. Wechseln Sie in das Tab *Such-Index*. +
→ Das Tab *Felder* wird angezeigt.
. Wechseln Sie in das Tab *Einstellungen*.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-unscharfe-suche>>.
. *Speichern* Sie die Einstellungen.


[[tabelle-unscharfe-suche]]
.Einstellungen für unscharfe Suche
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Zeichenlänge*
|Anzahl der Zeichen eingeben, ab der unscharf gesucht wird.

|*Unscharfe Suche ab*
|Zahl eingeben. Wenn die Suche weniger als diese Anzahl von Suchergebnissen liefert, wird eine unscharfe Suche durchgeführt.

|*Volltextsuche ab*
|Zahl eingeben. Wenn die Suche weniger als diese Anzahl von Suchergebnissen liefert, wird eine Volltextsuche durchgeführt.
|====

[#260]
==== Callisto + alte Facettensuche: Felder für Volltextsuche aktivieren

Im Tab *Volltext* legen Sie fest, welche Artikeldaten durchsucht werden, wenn im Tab *Felder* die Option *Volltext* aktiviert ist.

[.instruction]
Felder für Volltextsuche aktivieren:

. Öffnen Sie das Menü *System » Mandant » Global » Dienste » Facettensuche*.
. Wechseln Sie in das Tab *Such-Index*. +
→ Das Tab *Felder* wird angezeigt.
. Wechseln Sie in das Tab *Volltext*.
. Aktivieren Sie die Felder, die durchsucht werden, wenn im Tab *Felder* die Option *Volltext* aktiviert ist.
. *Speichern* Sie die Einstellungen.

[#270]
=== Callisto mit Facettensuche (Elastic Search - BETA) nutzen

Die neue Facettensuche auf Basis von ElasticSearch nutzen Sie, indem Sie im Menü *System » Mandant » Mandant wählen » Webshop » Artikelsuche* die Option *Facettensuche (Elastic Search- BETA)* aktivieren. Richten Sie die Facettensuche wie im Kapitel <<artikel/frontend-artikelsuche-verwalten#90, Facettensuche einrichten>> ein und gehen Sie dann wie unten beschrieben vor, um die neue Facettensuche in Callisto zu nutzen.

[#280]
==== Callisto + Facettensuche (Elastic Search- BETA): Felder für die Suche aktivieren

In den Sucheinstellungen legen Sie fest, welche Felder bei der ElasticSearch-Suche berücksichtigt werden. Bei einer Suche im Webshop werden also nur die Daten der aktivierten Felder durchsucht. In der Spalte *Boost* geben Sie ein, mit welcher Gewichtung das Feld zur Bewertung von Suchergebnissen beitragen soll. Je höher die eingegebene Zahl, desto höher wird der Inhalt des Felds für das Suchergebnis priorisiert. Als Boost-Wert kann eine beliebig hohe Zahl eingegeben werden. Die Standardeinstellungen sind für die meisten Anwendungsfälle sinnvoll. Diese Standardeinstellungen priorisieren die Varianten-ID und die Artikel-ID sehr hoch. Wenn Kunden also nach einer Zahl suchen, werden Suchergebnisse für diese Zahl in den ID-Feldern priorisiert. Gehen Sie wie unten beschrieben vor, um die Standardeinstellungen zu ändern.

[.instruction]
Felder für die Suche aktivieren:

. Öffnen Sie das Menü *System » Artikel » Suche » Frontend » Sucheinstellungen*.
. Aktivieren Sie in der Spalte *Aktiv* die Felder, die bei der Suche berücksichtigt werden sollen.
. Geben Sie für die aktivierten Felder in der Spalte *Boost* eine Gewichtung ein. Je höher die Zahl, desto höher die Priorität im Suchergebnis. +
*_Tipp:_* Sie können eine beliebig hohe Zahl eingeben.
. *Speichern* Sie die Einstellungen.

==== Callisto + Facettensuche (Elastic Search - BETA): Sprachen ändern

Die Facettensuche kann für bis zu drei Sprachen aktiviert werden. Standardmäßig sind die Sprachen *Deutsch*, *Englisch* und *Französisch* aktiviert. Wenn Sie Webshops in anderen Sprachen betreiben, können Sie die Sprachen ändern. Gehen Sie dazu wie unten beschrieben vor.

[IMPORTANT]
.Suchindex wird bei Änderungen vollständig neu gebaut
====
Wenn Sie die Spracheinstellungen ändern, wird der Suchindex komplett neu aufgebaut. Das bedeutet, dass alle Artikel erneut zum Index hinzugefügt werden. Je nachdem, wie viele Artikel Sie haben, kann dieser Vorgang bis zu mehrere Tage dauern.
====

[.instruction]
Sprachen ändern:

. Öffnen Sie das Menü *System » Artikel » Suche » Frontend » Sprachen*.
. Deaktivieren Sie eine Sprache, die Sie nicht benötigen.
. Aktivieren Sie eine Sprache. +
*_Hinweis:_* Pro System können nur drei Sprachen aktiviert werden.
. *Speichern* Sie die Einstellungen. +
→ Die Artikel werden zum Suchindex für die aktivierten Sprachen hinzugefügt.

[#290]
=== Facettensuche in Callisto einbinden

Im alten Design Callisto wird die Facettensuche im Template *NavigationFacetsList* definiert. Das Template *NavigationFacetsList* des Designs Callisto Light enthält fertigen Code, mit dem Sie eine Facettensuche erstellen. Dieser Code ist natürlich ausbaubar. Über die Template-Funktion <<omni-channel/online-shop/cms-syntax#webdesign-navigation-container-navigationfacetslist, Container_NavigationFacetsList>> fügen Sie das Template *NavigationFacetsList* in den gewünschten Bereich des Webshops ein. Gehen Sie dazu wie unten beschrieben vor.

[TIP]
.Empfohlene Templates
====
Wir empfehlen, die Template-Funktion *Container_NavigationFacetsList* innerhalb von *ItemViewCategoriesList* und *ItemViewSearchResultsList* zu verwenden. Diese Templates finden Sie im Menü *CMS » Webdesign » Ordner: Layout » Ordner: ItemView*.
====

[.instruction]
Facettensuche in Callisto einbinden:

. Öffnen Sie das Menü *CMS » Webdesign*.
. Öffnen Sie das gewünschte Template.
. Fügen Sie die Template-Funktion *Container_NavigationFacetsList* in das Template ein, um die Facettensuche anzuzeigen.
. *Speichern* Sie die Einstellungen.
. Wiederholen Sie optional den Vorgang, um die Template-Funktion in weitere Templates einzufügen.

[#300]
== Facettensuche in Ceres nutzen

Ceres setzt standardmäßig die Facettensuche in Kombination mit ElasticSearch ein. Richten Sie die Facettensuche wie im Kapitel <<artikel/frontend-artikelsuche-verwalten#90, Facettensuche einrichten>> ein und gehen Sie dann wie unten beschrieben vor, um die Facettensuche in Ceres zu nutzen.

[#310]
=== Ceres: Felder für die Suche aktivieren

In den Sucheinstellungen legen Sie fest, welche Felder bei der ElasticSearch-Suche berücksichtigt werden. Bei einer Suche im Webshop werden also nur die Daten der aktivierten Felder durchsucht. In der Spalte *Boost* geben Sie ein, mit welcher Gewichtung das Feld zur Bewertung von Suchergebnissen beitragen soll. Je höher die eingegebene Zahl, desto höher wird der Inhalt des Felds für das Suchergebnis priorisiert. Als Boost-Wert kann eine beliebig hohe Zahl eingegeben werden. Die Standardeinstellungen sind für die meisten Anwendungsfälle sinnvoll. Diese Standardeinstellungen priorisieren die Varianten-ID und die Artikel-ID sehr hoch. Wenn Kunden also nach einer Zahl suchen, werden Suchergebnisse für diese Zahl in den ID-Feldern priorisiert. Gehen Sie wie unten beschrieben vor, um die Standardeinstellungen zu ändern.

[.instruction]
Felder für die Suche aktivieren:

. Öffnen Sie das Menü *System » Artikel » Suche » Frontend » Sucheinstellungen*.
. Aktivieren Sie in der Spalte *Aktiv* die Felder, die bei der Suche berücksichtigt werden sollen.
. Geben Sie für die aktivierten Felder in der Spalte *Boost* eine Gewichtung ein. Je höher die Zahl, desto höher die Priorität im Suchergebnis. Ergebnisse aus dem Feld mit der höchsten Zahl werden also zuerst gelistet. +
*_Tipp:_* Sie können eine beliebige Zahl eingeben.
. *Speichern* Sie die Einstellungen.

[#320]
=== Ceres: Sprachen ändern

Die Facettensuche kann für bis zu drei Sprachen aktiviert werden. Standardmäßig sind die Sprachen *Deutsch*, *Englisch* und *Französisch* aktiviert. Wenn Sie Webshops in anderen Sprachen betreiben, können Sie die Sprachen ändern. Gehen Sie dazu wie unten beschrieben vor.

[IMPORTANT]
.Suchindex wird bei Änderungen vollständig neu gebaut
====
Wenn Sie die Spracheinstellungen ändern, wird der Suchindex komplett neu aufgebaut. Das bedeutet, dass alle Artikel erneut zum Index hinzugefügt werden. Je nachdem, wie viele Artikel Sie haben, kann dieser Vorgang bis zu mehrere Tage dauern.
====

[.instruction]
Sprache ändern:

. Öffnen Sie das Menü *System » Artikel » Suche » Frontend » Sprachen*.
. Deaktivieren Sie eine Sprache, die Sie nicht benötigen.
. Aktivieren Sie eine Sprache. +
*_Hinweis:_* Pro System können nur drei Sprachen aktiviert werden.
. *Speichern* Sie die Einstellungen. +
→ Die Artikel werden zum Suchindex für die aktivierten Sprachen hinzugefügt.

[#330]
=== Ceres: Facettensuche einbinden

Wie Sie die Facettensuche in Ceres nutzen, erfahren Sie auf der Handbuchseite <<omni-channel/online-shop/ceres-einrichten#330, Ceres einrichten>>.
