= Frontend-Artikelsuche verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Facetten, Webshopsuche, Facettensuche
:position: 60
:url: artikel/frontend-artikelsuche-verwalten
:id: NKJXE3I

Die Frontend-Artikelsuche ermöglicht es, dein Produktsortiment im Webshop zu durchsuchen. Im Template-Plugin Ceres ist für die Artikelsuche im Webshop standardmäßig die Facettensuche aktiviert. Im alten Webshop-Design Callisto wird die Facettensuche im Menü *Einrichtung » Mandant » Mandant wählen » Webshop » Artikelsuche* aktiviert.

Auf dieser Handbuchseite erfährst du, wie du Facetten und Facettenwerte erstellst und wie du diese Facetten in Callisto und Ceres nutzt.

[NOTE]
.Alter Webshop: Callisto mit Standard-Suche
====
Bei Webshops mit dem alten Design Callisto, für die im Menü *Einrichtung » Mandant » Mandant wählen » Webshop » Artikelsuche* die Option *Standard-Suche* aktiviert ist, wird für die Artikelsuche im Frontend der <<artikel/artikel-verwalten#385, Index der Backend-Artikelsuche>> verwendet.
====

[#90]
== Facettensuche einrichten

Facetten sind die Filtermöglichkeiten, mit denen Suchergebnisse im Webshop nach bestimmten Kriterien, also Facetten, verfeinert werden. Der Vorteil der Facettensuche ist, dass das Suchergebnis nicht zwangsweise analog zur Auswahl des Kriteriums reduziert wird, sondern immer wieder die gesamte Datenbank nach dem Kriterium durchsucht wird. Dies ermöglicht eine intuitive Suche und vermeidet, dass Suchergebnisse durch eine ungünstige Vorauswahl verfälscht werden.

Die Filternavigation richtest du flexibel ein. Die angezeigten Artikel in einer Kategorie können mit Facetten nicht nur nach Merkmalen/Eigenschaften, sondern auch nach folgenden Kriterien weiter eingeschränkt werden:

* Nach Attributen, Merkmalen und Eigenschaften
* Nach Herstellern
* Nach der Verfügbarkeit der Artikel
* Nach Preissegment

Diese vier Facettentypen verbindest du in plentymarkets mit verschiedenen Werten, die das Filterergebnis bestimmen. Je mehr Facetten du erstellst und mit Werten verknüpfst, desto umfangreicher wird die im Webshop dargestellte Filterauswahl.

Die Konfiguration besteht aus mehreren Schritten. Zunächst werden Facetten erstellt, anschließend durch weitere Einstellungen näher bestimmt und schließlich mit den gewünschten Werten verknüpft. Zudem muss im Menü *Einrichtung » Mandant » Mandant wählen » Webshop » Artikelsuche* die Option *Facettensuche* eingestellt sein.

[TIP]
.Artikel mit Facetten verknüpfen
====
Eine direkte Verknüpfung von Artikeln mit den einzelnen Facetten ist nicht nötig. Die Zuordnung deiner Artikel zu Facetten erfolgt automatisch durch die <<artikel/frontend-artikelsuche-verwalten#140, Verknüpfung der Facette mit Werten>>, die am Artikel hinterlegt sein müssen.
====

[#100]
=== Facette erstellen

Für die Facettensuche erstellst du zunächst Facetten, zum Beispiel die Facette "Farbe" des Typs *Attribut/Merkmal*.

[.instruction]
Facette erstellen:

. Öffne das Menü *Einrichtung » Mandant » Global » Dienste » Facettensuche*.
. Klicke auf *Neu*.
. Trage einen *Namen* für die Facette in der Systemsprache ein. Dieser Name wird im Webshop angezeigt.
. Wähle einen *Typ* aus der Dropdown-Liste. Beachte die Erläuterungen in <<tabelle-verfuegbare-facettentypen>>.
. Trage die *Position* ein, an der die Facette im Webshop angezeigt werden soll.
. *Speichere* die Einstellungen. +
→ Die Facette wird erstellt.


[[tabelle-verfuegbare-facettentypen]]
.Verfügbare Facettentypen
[cols="1,3"]
|====
|Facettentyp |Erläuterung

|*Preis*
|Facetten des Typs *Preis* müssen nicht mit Werten verknüpft werden, da der Filter vom kleinsten bis zum größten Preis einer Kategorie individuell eingeschränkt werden kann.

|*Attribut/Merkmal*
|Facetten des Typs *Attribut/Merkmal* werden mit Attributen, Merkmalen und Eigenschaften im System verknüpft und stellen so vielfältige Filtermöglichkeiten her, zum Beispiel nach Farben, Größen etc.

|*Verfügbarkeit*
|Facetten des Typs *Verfügbarkeit*, zum Beispiel "Kurzfristig lieferbar", werden mit den im Menü <<artikel/artikel-verwalten#180, Einrichtung » Artikel » Verfügbarkeit>> erstellten Verfügbarkeiten verknüpft.

|*Hersteller*
|Facetten des Typs *Hersteller*, zum Beispiel "Adidas", werden mit den im Menü <<artikel/artikel-verwalten#560, Einrichtung » Artikel » Hersteller>> erstellten Herstellern verknüpft.
|====

[#110]
=== Facette bearbeiten

Nachdem du eine Facette erstellt hast, wird die Facette geöffnet. Es stehen vier Tabs zur Verfügung, um weitere Einstellungen vorzunehmen und Werte zu verknüpfen.

[#120]
==== Facetteneinstellungen vornehmen

Im Tab *Einstellungen* nimmst du die Einstellungen wie unten beschrieben vor.

[.instruction]
Facette bearbeiten:

. Öffne das Menü *Einrichtung » Mandant » Global » Dienste » Facettensuche*.
. Öffne die Facette. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte die Erläuterungen in <<tabelle-facetten-bearbeiten>>.
. *Speichere* die Einstellungen.

[[tabelle-facetten-bearbeiten]]
.Facetten bearbeiten; Tab *Einstellungen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Typ*
|Zeigt den beim Erstellen der Facette gewählten Typen an. Der Typ ist nicht änderbar.

|*Sortierung*
|Legt die Sortierung des Suchergebnisses fest. Je nach Auswahl werden die Artikel nach der *Trefferquote*, der *Position* oder alphabetisch von *A-Z* sortiert.

|*Position*
|Zeigt die Position an, die beim Erstellen der Facette eingegeben wurde. Die Position ist änderbar.

|*CSS-Klasse*
|Einen CSS-Namen hinterlegen. Dieser Name wird als Template-Variable im CMS-Bereich zur Verfügung gestellt, sodass zu jeder Facette eine eigene Klasse hinterlegt werden kann.

|*Auswahlart*
|Die Auswahlart wählen. +
*Einschränkend* = Schränkt den Filter mit dem gewählten Wert weiter ein. Alle Artikel werden angezeigt, die diesen Wert besitzen und die Filterkriterien vorher gewählter Filter erfüllen. +
*Mehrfach* = Lässt eine Mehrfachauswahl von Ergebnissen zu, zum Beispiel die Auswahl mehrerer Hersteller, deren Artikel gemeinsam angezeigt werden. +

|*Minimale Trefferanzahl*
|Legt fest, wie viele Ergebnisse es für einen Facettenwert mindestens geben muss, damit der Facettenwert im Webshop angezeigt wird.

|*Maximal angezeigte Facettenwerte*
|Legt fest, wie viele Facettenwerte pro Facette höchstens angezeigt werden. 250 Facettenwerte können maximal angezeigt werden.
|====

[#130]
==== Facettenname in zusätzlicher Sprache speichern

Beim Erstellen einer Facette gibst du einen Namen in der Standardsprache des Systems ein. Dieser Name wird im Webshop angezeigt. Wenn du zusätzlichen Sprachen anbietest, gibst du im Tab *Name* den Namen der Facette in diesen Sprachen ein. Gehe dazu wie unten beschrieben vor.


[.instruction]
Facettenname in zusätzlicher Sprache speichern:

. Öffne das Menü *Einrichtung » Mandant » Global » Dienste » Facettensuche*.
. Öffne die Facette. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechsele in das Tab *Name*.
. Gib einen Namen für die gewünschte Sprache ein.
. *Speichere* die Einstellungen.

[#140]
=== Facette mit Wert verknüpfen

Im Tab *Werte* einer Facette verknüpfst du die Facette mit verschiedenen Werten. Im Beispiel der Facette Farbe des Typs *Attribut/Merkmal* erstellst du zum Beispiel die Werte weiß, schwarz, rot, blau etc. und verknüpfst diese Werte mit den vorhandenen Attributen, Merkmalen und Eigenschaften im System. Gehe dazu wie unten beschrieben vor.

[#150]
==== Wert erstellen

[.instruction]
Wert erstellen:

. Öffne das Menü *Einrichtung » Mandant » Global » Dienste » Facettensuche*.
. Öffne die Facette.
. Wechsele in das Tab *Werte*.
. Klicke links unten auf das grüne Plus. +
→ Das Fenster *Wert erstellen* wird angezeigt.
. Gib einen *Namen* für den Wert in der Systemsprache ein.
. Gib eine *Position* ein.
. *Speichere* die Einstellungen. +
→ Der neue Wert wird erstellt.
. *_Optional:_* Gib im Tab *Name* Übersetzungen für den Namen des Werts ein.
. *_Optional:_* Gib im Tab *Einstellungen* eine CSS-Klasse ein.

[#160]
==== Wert verknüpfen

Verknüpfe nun den Wert mit den Daten im System. Du kannst einem Facettenwert mehrere Backend-Werte zuordnen. Zum Beispiel kannst du bei Facetten des Typs *Attribut/Merkmal* Attribute, Merkmale und Eigenschaften im System in einem Filter zusammenfassen und so zusammen in einem Ergebnis ausgeben.

[.instruction]
Facettenwert mit Backend-Wert verknüpfen:

. Öffne das Menü *Einrichtung » Mandant » Global » Dienste » Facettensuche*.
. Öffne die Facette.
. Wechsele in das Tab *Werte*.
. Klicke auf den Wert.
. Wechsele in das Tab *Verknüpfung*.
. Klicke auf den Backend-Wert, der verknüpft werden soll.
. Klicke links unten auf *Verknüpfen*. +
→ Der Backend-Wert wird mit dem Wert der Facette verknüpft.
. *_Optional:_* Verknüpfe weitere Werte.
. *Speichere* die Einstellungen.

[#170]
=== Facetten mit Bildern verknüpfen

Im Tab *Bilder* verknüpfst du Facetten und Facettenwerte mit Bildern. Verknüpfe zum Beispiel die Hersteller in deinem Webshop mit Bildern, wenn du nicht den Namen der Herstellers, sondern das Logo des Herstellers anzeigen möchtest.

[#180]
==== Bild hochladen

[.instruction]
Bild hochladen:

. Öffne das Menü *Einrichtung » Mandant » Global » Dienste » Facettensuche*.
. Öffne die Facette.
. Wechsele in das Tab *Bilder*.
. Klicke auf *Dateien hochladen*.
. Navigiere zum Speicherort der Bilddatei.
. Wähle die Bilddatei. +
→ Die Bilddatei wird hochgeladen.
. *Speichere* die Einstellungen.

[#190]
==== Bild verknüpfen

Verknüpfe nun das Bild mit den Daten im System. Pro Bild kann ein Wert verknüpft werden.

[.instruction]
Bild verknüpfen:

. Öffne das Menü *Einrichtung » Mandant » Global » Dienste » Facettensuche*.
. Öffne die Facette.
. Wechsele in das Tab *Bilder*.
. Zeige mit dem Cursor auf das Bild. +
→ Im unteren Bereich des Bilds wird eine Dropdown-Liste mit Werten angezeigt.
. Klicke in der Dropdown-Liste auf den Wert.
. *Speichere* die Einstellungen. +
→ Das Bild wird mit dem Wert verknüpft. +
→ Das verknüpfte Bild wird mit rotem Rand dargestellt. +
→ Der Name des Werts wird im Bild angezeigt.

[#200]
=== Facetten mit Mandant verknüpfen

Nachdem du Facetten erstellt hast, verknüpfe im Menü *Einrichtung » Mandant » Mandant wählen » Dienste » Facettenverknüpfungen* diese Facetten mit dem Mandanten, in dem die Facetten als Filter zur Verfügung stehen sollen. Wähle pro Mandant, welche Facetten für den Shop relevant sind und welche nicht. Änderungen, die du vornimmst, werden in Echtzeit übertragen. Gehe wie unten beschrieben vor, um Facetten mit einem Mandanten zu verknüpfen.

[NOTE]
.Facette des Typs Preis
====
Pro Mandant kann nur eine Facette des Typs Preis verknüpft werden.
====

[.instruction]
Facetten im Webshop verknüpfen:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Dienste » Facettenverknüpfungen*.
. Klicke in der Liste links auf die Facette, die du mit diesem Shop verknüpfen möchtest.
. Klicke links unten auf *Facette verknüpfen*.
. *_Optional:_* Aktiviere die Option *Bilder bereitstellen*, um mit den Facetten verknüpfte Bilder im Webshop anzuzeigen.
. Wiederhole den Vorgang für alle weiteren Facetten, die verknüpft werden sollen.
. *Speichere* die Einstellungen. +
→ Die Facette wird im Webshop verknüpft.

[#210]
== Facettensuche in Callisto nutzen

Im alte Design Callisto können für die Frontend-Suche verschiedene Suchen genutzt werden. Welche Suche verwendet wird, legst du im Menü *Einrichtung » Mandant » Mandant wählen » Webshop » Artikelsuche* fest. Die folgenden Optionen sind verfügbar:

* *Standard-Suche* +
→ Wenn die Option *Standard-Suche* aktiviert ist, wird für die Artikelsuche im Frontend der <<artikel/artikel-verwalten#385, Index der Backend-Artikelsuche>> verwendet.
* *Findologic* +
→ Wie du die Artikelsuche über Findologic einrichtest, erfährst du auf der Handbuchseite <<webshop/webshop-einrichten/extras/findologic#, Findologic>>.
* *Facettensuche* +
→ Wie du die Facettensuche einrichtest, erfährst du im Kapitel <<artikel/frontend-artikelsuche-verwalten#270, Callisto mit Facettensuche nutzen>>.

[#270]
=== Callisto mit Facettensuche nutzen

Die neue Facettensuche auf Basis von ElasticSearch nutzt du, indem du im Menü *Einrichtung » Mandant » Mandant wählen » Webshop » Artikelsuche* die Option *Facettensuche* aktivierst. Richte die Facettensuche wie im Kapitel <<artikel/frontend-artikelsuche-verwalten#90, Facettensuche einrichten>> ein. Gehe dann wie unten beschrieben vor, um die neue Facettensuche in Callisto zu nutzen.

[#280]
==== Callisto + Facettensuche: Felder für die Suche aktivieren

In den Sucheinstellungen legst du fest, welche Felder bei der ElasticSearch-Suche berücksichtigt werden. Bei einer Suche im Webshop werden also nur die Daten der aktivierten Felder durchsucht. In der Spalte *Boost* gibst du ein, mit welcher Gewichtung das Feld zur Bewertung von Suchergebnissen beitragen soll. Je höher die eingegebene Zahl, desto höher wird der Inhalt des Felds für das Suchergebnis priorisiert. Als Boost-Wert kann eine beliebig hohe Zahl eingegeben werden. Die Standardeinstellungen sind für die meisten Anwendungsfälle sinnvoll. Diese Standardeinstellungen priorisieren die Varianten-ID und die Artikel-ID sehr hoch. Wenn in deinem Webshop also nach einer Zahl gesucht wird, werden Suchergebnisse für diese Zahl aus den ID-Feldern priorisiert. Gehe wie unten beschrieben vor, um die Standardeinstellungen zu ändern.

[.instruction]
Felder für die Suche aktivieren:

. Öffne das Menü *Einrichtung » Artikel » Suche » Frontend » Sucheinstellungen*.
. Aktiviere in der Spalte *Aktiv* die Felder, die bei der Suche berücksichtigt werden sollen.
. Gib für die aktivierten Felder in der Spalte *Boost* eine Gewichtung ein. Je höher die Zahl, desto höher die Priorität im Suchergebnis. +
*_Tipp:_* Du kannst eine beliebig hohe Zahl eingeben.
. *Speichere* die Einstellungen.

==== Callisto + Facettensuche: Sprachen ändern

Die Facettensuche kann für bis zu drei Sprachen aktiviert werden. Standardmäßig sind die Sprachen *Deutsch*, *Englisch* und *Französisch* aktiviert. Wenn du Webshops in anderen Sprachen betreibst, kannst du die Sprachen ändern. Gehe dazu wie unten beschrieben vor.

[IMPORTANT]
.Suchindex wird bei Änderungen vollständig neu gebaut
====
Wenn du die Spracheinstellungen änderst, wird der Suchindex komplett neu aufgebaut. Das bedeutet, dass alle Artikel erneut zum Index hinzugefügt werden. Je nachdem, wie viele Artikel du hast, kann dieser Vorgang bis zu mehrere Tage dauern.
====

[.instruction]
Sprachen ändern:

. Öffne das Menü *Einrichtung » Artikel » Suche » Frontend » Sprachen*.
. Deaktiviere eine Sprache, die du nicht benötigst.
. Aktiviere eine Sprache. +
*_Hinweis:_* Pro System können nur drei Sprachen aktiviert werden.
. *Speichere* die Einstellungen. +
→ Die Artikel werden zum Suchindex für die aktivierten Sprachen hinzugefügt.

[#290]
=== Facettensuche in Callisto einbinden

Im alten Design Callisto wird die Facettensuche im Template *NavigationFacetsList* definiert. Das Template *NavigationFacetsList* des Designs Callisto Light enthält fertigen Code, mit dem du eine Facettensuche erstellst. Dieser Code ist natürlich ausbaubar. Über die Template-Funktion <<webshop/webshop-einrichten/cms-syntax#webdesign-navigation-container-navigationfacetslist#, Container_NavigationFacetsList>> fügst du das Template *NavigationFacetsList* in den gewünschten Bereich des Webshops ein. Gehe dazu wie unten beschrieben vor.

[TIP]
.Empfohlene Templates
====
Wir empfehlen, die Template-Funktion *Container_NavigationFacetsList* innerhalb von *ItemViewCategoriesList* und *ItemViewSearchResultsList* zu verwenden. Diese Templates findest du im Menü *CMS » Webdesign » Ordner: Layout » Ordner: ItemView*.
====

[.instruction]
Facettensuche in Callisto einbinden:

. Öffne das Menü *CMS » Webdesign*.
. Öffne das gewünschte Template.
. Füge die Template-Funktion *Container_NavigationFacetsList* in das Template ein, um die Facettensuche anzuzeigen.
. *Speichere* die Einstellungen.
. Wiederhole optional den Vorgang, um die Template-Funktion in weitere Templates einzufügen.

[#300]
== Facettensuche in Ceres nutzen

Ceres setzt standardmäßig die Facettensuche in Kombination mit ElasticSearch ein. Richte die Facettensuche wie im Kapitel <<artikel/frontend-artikelsuche-verwalten#90, Facettensuche einrichten>> ein und gehe dann wie unten beschrieben vor, um die Facettensuche in Ceres zu nutzen.

[#310]
=== Ceres: Felder für die Suche aktivieren

In den Sucheinstellungen legst du fest, welche Felder bei der ElasticSearch-Suche berücksichtigt werden. Bei einer Suche im Webshop werden also nur die Daten der aktivierten Felder durchsucht. In der Spalte *Boost* gibst du ein, mit welcher Gewichtung das Feld zur Bewertung von Suchergebnissen beitragen soll. Je höher die eingegebene Zahl, desto höher wird der Inhalt des Felds für das Suchergebnis priorisiert. Als Boost-Wert kann eine beliebig hohe Zahl eingegeben werden. Die Standardeinstellungen sind für die meisten Anwendungsfälle sinnvoll. Diese Standardeinstellungen priorisieren die Varianten-ID und die Artikel-ID sehr hoch. Wenn in deinem Webshop also nach einer Zahl gesucht wird, werden Suchergebnisse für diese Zahl in den ID-Feldern priorisiert. Gehe wie unten beschrieben vor, um die Standardeinstellungen zu ändern.

[.instruction]
Felder für die Suche aktivieren:

. Öffne das Menü *Einrichtung » Artikel » Suche » Frontend » Sucheinstellungen*.
. Aktiviere in der Spalte *Aktiv* die Felder, die bei der Suche berücksichtigt werden sollen.
. Gib für die aktivierten Felder in der Spalte *Boost* eine Gewichtung ein. Je höher die Zahl, desto höher die Priorität im Suchergebnis. Ergebnisse aus dem Feld mit der höchsten Zahl werden also zuerst gelistet. +
*_Tipp:_* Du kannst eine beliebige Zahl eingeben.
. *Speichere* die Einstellungen.

[#320]
=== Ceres: Sprachen ändern

Die Facettensuche kann für bis zu drei Sprachen aktiviert werden. Standardmäßig sind die Sprachen *Deutsch*, *Englisch* und *Französisch* aktiviert. Wenn du Webshops in anderen Sprachen betreibst, kannst du die Sprachen ändern. Gehe dazu wie unten beschrieben vor.

[IMPORTANT]
.Suchindex wird bei Änderungen vollständig neu gebaut
====
Wenn du die Spracheinstellungen änderst, wird der Suchindex komplett neu aufgebaut. Das bedeutet, dass alle Artikel erneut zum Index hinzugefügt werden. Je nachdem, wie viele Artikel du hast, kann dieser Vorgang bis zu mehrere Tage dauern.
====

[.instruction]
Sprache ändern:

. Öffne das Menü *Einrichtung » Artikel » Suche » Frontend » Sprachen*.
. Deaktiviere eine Sprache, die du nicht benötigst.
. Aktiviere eine Sprache. +
*_Hinweis:_* Pro System können nur drei Sprachen aktiviert werden.
. *Speichere* die Einstellungen. +
→ Die Artikel werden zum Suchindex für die aktivierten Sprachen hinzugefügt.

[#330]
=== Ceres: Facettensuche einbinden

Wie du die Facettensuche in Ceres nutzt, erfährst du auf der Handbuchseite <<webshop/ceres-einrichten#330, Ceres einrichten>>.
