= Kategorien verwalten
:lang: de
include::{includedir}/_header.adoc[]
:position: 10
:url: artikel/kategorien-verwalten
:id: YXK0NOR

Kategorien in plentymarkets sind einerseits das, was dir aus anderen Systemen als Warengruppen oder Artikelkategorien bekannt sind. Andererseits sind Kategorien deine Content-Seiten für den Bereich **CMS**. Die verschiedenen Kategorietypen haben generell eine große Schnittmenge an Einstellungen. Zu diesen Gemeinsamkeiten zählt z.B. die Verwaltung in einer Ordnerstruktur. Eine Ordnerstruktur entsteht durch das Erstellen von Hauptkategorien und bis zu 5 Unterkategorien. Eine weitere Gemeinsamkeit ist, dass üblicherweise Texte wie Beschreibung, Kurzbeschreibung, Meta-Beschreibung sowie grafische Elemente hinterlegt werden. Deshalb werden diese Kategorietypen in plentymarkets gemeinsam als Kategorien verwaltet.

////
* SEO für Content + Artikel!
* CANONICAL
* MANDANTEN
* SITEMAP
////

Unterscheiden lassen sich Kategorien in plentymarkets einfach anhand des Typs. Hierfür gibt es die Typen **Artikel**, **Content** und **Container**.

[[tabelle-kategorietypen]]
.Kategorietypen
[cols="1,2,1"]
|====
|Typ |Erläuterung |Ordnerfarbe im Backend

|**Artikel**
|Unterteilung der Artikel im Webshop, z.B. **Herren » Oberteile » T-Shirts**
|Blau

|**Content**
|Content-Seiten für den Bereich **CMS**, z.B. Informationsseiten wie AGBs, Zahlungs- und Versandinformationen.
|Gelb

|**Container**
|Der Inhalt einer Kategorie des Typs **Container** kann ähnlich wie der von Freitextfeldern über Template-Funktionen auf anderen Seiten angezeigt werden, z.B. in einer anderen Kategorie. Außerdem werden damit die Bestellschritte des <<webshop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-individueller-bestellvorgang, Individuellen Bestellvorgangs>> realisiert.
|Rot

|**Blog**
|Aktuell ohne Funktion
|Gelb
|====

== Vorbereitungen

=== Kategorieebenen festlegen

Lege zunächst fest, wie viele Kategorieebenen im Webshop angezeigt werden sollen. Diese Einstellung nimmst du pro Mandanten (Shop) vor. Wenn du z.B. 4 Ebenen wählst, können keine Kategorien auf der 5. Ebene erstellt werden. Diese Einstellung gilt für den gesamten Kategoriebaum, also für alle Kategorietypen.

[.instruction]
Kategorieebenen festlegen:

. Öffne das Menü **Einrichtung » Mandant » Mandant wählen » Kategorien » Einstellungen**.
. Wähle die maximal mögliche Ebenentiefe in der Kategorienavigation.
. **Speichere** die Einstellung.

=== Struktur der Artikelkategorien planen

Erarbeite wenn möglich eine sinnvolle Kategoriestruktur, bevor du mit dem Erstellen der Kategorien beginnst. Überlege vor dem Erstellen von Artikelkategorien, welche Produkte dein Portfolio beinhaltet und leite daraus Kategorien und Unterkategorien ab. <<tabelle-kategoriestrukturen-beispiele>> zeigt zwei stark vereinfachte Beispiele für verschiedene Artikelstrukturen.

[[tabelle-kategoriestrukturen-beispiele]]
.Beispiele für verschiedene Artikelkategoriestrukturen
[cols="2,2"]
|====
|Beispielstruktur 1 |Beispielstruktur 2

a|
* Damen
  ** Schuhe
  ** Accessoires
  ** ...

* Herren
  ** Schuhe
  ** Accessoires
  ** ...

* Kinder
  ** Schuhe
  ** Accessoires
  ** ...

a|
* Schuhe
  ** Damen
  ** Herren
  ** Kinder

* Accessoires
  ** Damen
  ** Herren
  ** Kinder

* ...
  ** Damen
  ** Herren
  ** Kinder
|====

== Kategorie erstellen

Neue Kategorien erstellst du entweder als Hauptkategorie oder als Unterkategorie. Hauptkategorien sind Kategorien der ersten Ebene. Unterkategorien sind Kategorien aller weiterer Ebenen des Kategoriebaums. Wie du Haupt- und Unterkategorien erstellst, wird unten getrennt beschrieben.

[TIP]
.Standard-Kategorie "Content"
====
Eine Kategorie mit dem Namen **Content** ist standardmäßig im System gespeichert. Eigene Kategorien mit dem Namen **Content** können nicht erstellt werden. Name und URL-Name der Kategorie **Content** sind nicht änderbar. Nicht namensbezogene Optionen dieser Kategorie, z.B. die Position, sind änderbar.
====

=== Hauptkategorie erstellen

Gehe wie unten beschrieben vor, um eine Hauptkategorie zu erstellen.

[.instruction]
Hauptkategorie erstellen:

. Öffne das Menü **Artikel » Kategorien**.
. Klicke links unten auf **Neue Kategorie**. +
→ Das Fenster **Neue Kategorie erstellen** wird geöffnet.
. Gib einen Namen für die Kategorie ein.
. Wähle **Hauptkategorie** als Kategorieebene.
. Klicke auf **Erstellen**. +
→ Die Kategorie wird erstellt und im Verzeichnisbaum links angezeigt. +
**__Tipp:__** Neue Kategorien haben standardmäßig den Kategorietyp **Artikel**. Ändere bei Bedarf den Kategorietyp.

=== Unterkategorie erstellen

Um eine Unterkategorie zu erstellen, muss eine Hauptkategorie vorhanden sein. Unten wird beschrieben, wie du eine Unterkategorie der zweiten Ebene erstellst. Um eine Unterkategorie der 3. oder 4. Ebene zu erstellen, klicke die Unterkategorien an, bis du die Kategorie erreicht hast, zu der du eine Unterkategorie erstellen möchtest. Du hast zwei Möglichkeiten, Unterkategorien zu erstellen:

[.instruction]
Unterkategorie über Schaltfläche *Neue Kategorie* erstellen:

. Öffne das Menü **Artikel » Kategorien**.
. Klicke links unten auf **Neue Kategorie**. +
→ Das Fenster **Neue Kategorie erstellen** wird geöffnet.
. Gib einen Namen für die Kategorie ein.
. Wähle **Unterkategorie** als Kategorieebene. +
→ Die Kategorieebenen werden auswählbar.
. Wähle die Hauptkategorie, der die neue Kategorie untergeordnet werden soll.
. Klicke auf **Erstellen**. +
→ Die Kategorie wird erstellt und im Verzeichnisbaum links als Unterkategorie angezeigt. +
**__Tipp:__** Neue Kategorien haben standardmäßig den Kategorietyp **Artikel**. Ändere bei Bedarf den Kategorietyp.

[.instruction]
Unterkategorie über das Kontextmenü erstellen:

. Öffne das Menü **Artikel » Kategorien**.
. Öffne die Kategorie, zu der du eine Unterkategorie erstellen möchtest.
. Klicke mit der rechten Maustaste auf die Kategorie. +
→ Das Kontextmenü wird geöffnet.
. Klicke auf **Unterkategorie erstellen**. +
→ Das Fenster **Neue Unterkategorie erstellen** wird geöffnet.
. Gib einen Namen für die Unterkategorie ein.
. Klicke auf **Erstellen**. +
→ Die Kategorie wird erstellt und im Verzeichnisbaum links als Unterkategorie angezeigt. +
**__Tipp:__** Neue Kategorien haben standardmäßig den Kategorietyp **Artikel**. Ändere bei Bedarf den Kategorietyp.

== Kategorie bearbeiten

Neue Kategorien werden im Verzeichnisbaum links angezeigt. Öffne eine Kategorie, indem du die Kategorie anklickst oder indem du mit der rechten Maustaste das Kontextmenü öffnest. Dieses Menü ermöglicht dir den Schnellzugriff auf bestimmte Funktionen, um die Kategorie zu bearbeiten, zu verschieben, zu kopieren oder zu löschen. Du kannst außerdem einen neuen Artikel oder eine Unterkategorie erstellen.

Das Bearbeitungsfenster einer Kategorie besteht aus den folgenden Elementen:

* Symbolleiste
* Tab **Einstellungen**
* Tab **Beschreibung 1**
* Tab **Beschreibung 2**
* Tab **Dokumente**
* Tab **Notiz**

=== Kategorieeinstellungen vornehmen

Das Tab **Einstellungen** wird automatisch geöffnet, wenn du eine Kategorie öffnest.

[.instruction]
Kategorieeinstellungen vornehmen:

. Öffne die Kategorie links im Kategorieverzeichnis.
. Nimm die Einstellungen vor. Beachte <<tabelle-kategorieeinstellungen>>. +
**__Tipp:__** Die verfügbaren Einstellungen sind von dem Kategorietyp abhängig.
. **Speichere** die Einstellungen.

[[tabelle-kategorieeinstellungen]]
.Kategorieeinstellungen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Symbolleiste

|Kategoriepfad/ Brotkrumennavigation
|Zeigt den Pfad der geöffneten Kategorie an. Auf eine der übergeordneten Kategorien klicken, um diese Kategorie zu öffnen.

|**Speichern**
|Speichert Änderungen an der Kategorie.

|**ID**
|Die Kategorie-ID wird automatisch vergeben und ist nicht änderbar.

|**Vorschau**
|Öffnet eine Vorschau der Kategorie.

|**Inline-Edit-Vorschau**
|Öffnet eine Vorschau, die auch Bearbeitungsmöglichkeiten bietet.

|**Bilder-Galerie**
|Option ist nicht mehr verfügbar.

|**Template-Variablen und -Funktionen**
|Öffnet eine Übersicht der <<webshop/webshop-einrichten/cms-syntax#grundlagen-template-variablen, Template-Variablen>> und <<webshop/webshop-einrichten/cms-syntax#grundlagen-template-funktionen, Template-Funktionen>>, die in die Beschreibung eingefügt werden können. +
Beispiele für Funktionen: +
**&lbrace;% Link(Kategorie-ID) %}** = Verlinkt auf eine andere Kategorieseite +
**&lbrace;% Link_ShippingCosts() %}** = Verlinkt auf die Informationen zu den Versandkosten

|**Multilingualität**
|Öffnet eine zweisprachige Ansicht der Kategorie. Die dargestellten Sprachen sind per Dropdown-Liste wählbar. +
**__Tipp:__** In der zweisprachigen Ansicht können auch Sprachen angezeigt werden, für die noch keine Inhalte gespeichert wurden. Die Standard-Sprache muss nicht geöffnet sein.

|**Kategorie-Einstellungen übertragen**
|Optionen wählen, die von dieser Kategorie auf eine andere Kategorie mit der gleichen Kategorie-ID anderer Mandanten sowie anderer Sprachen kopiert werden sollen.

|**Link**
|Die Template-Funktion zum Einfügen dieser Kategorie. Die Funktion enthält immer die Kategorie-ID zur eindeutigen Zuordnung.

|**Timestamp**
|Zeigt den Zeitpunkt der letzten Bearbeitung und den Bearbeiter an.

2+|Tab: **Einstellungen**

|**Typ**
|Zwischen **Artikel**, **Content** und **Container** wählen.

|**Name**
|Einen Namen für die Kategorie eingeben. +
__**Hinweis:**__ Der gleiche Kategoriename kann in unterschiedlichen Kategorien auf derselben Ebene verwendet werden. Innerhalb einer Kategorie darf der Name jedoch pro Ebene nur einmal verwendet werden. +
__**SEO-Tipp:**__ Für Kategorien des gleichen Namens unterschiedliche Meta-Titel und Meta-Beschreibungen speichern.

|**Tags**
|<<basics/arbeiten-mit-plentymarkets/tags#, Tags>> wählen, um der Kategorie Themengebiete zuzuordnen.

|**URL-Name**
a|Ggf. den Namen ändern, der für die URL verwendet werden soll. Beim Erstellen einer Kategorie wird als URL-Name automatisch der Kategoriename verwendet. Der gleiche URL-Name darf in unterschiedlichen Kategorien auch auf derselben Ebene verwendet werden. Innerhalb einer Kategorie darf der URL-Name jedoch nur einmal pro Ebene verwendet werden. +
**__SEO-Tipp:__** Da beim Erstellen der Kategorie kein Mandant gewählt ist, wird die automatisch erstellte URL nicht von Suchmaschinen indiziert. SEO-technisch ist es ratsam, den URL-Namen nicht mehr zu ändern, nachdem die Kategorie für einen Mandanten aktiviert wurde. +

__**Wichtig:**__

* Der URL-Name darf keine Sonderzeichen enthalten. Daher ausschließlich ASCII-Code verwenden.
* Folgende Zeichenfolgen dürfen zu Beginn eines URL-Namens nicht verwendet werden: +
a-, b-, c-, f-, fa-, p-, t- +
Diese Anfangszeichen werden automatisch entfernt. Aus "a-klasse" wird z.B. automatisch "klasse". Für eine Kategorie mit dem Namen A-Klasse also z.B. den URL-Namen "aklasse" eingeben.

|**URL**
|Die URL der Kategorie. Die URL wird automatisch aus dem vollständigen Pfad der Kategorie erstellt, also aus Domain, Kategorieebenen und URL-Namen.

|**Canonical**
|Ggf. die URL einer Kategorie eingeben, die den gleichen Inhalt enthält, um <<webshop/webshop-einrichten/cms-syntax#110, Duplicate Content>> zu verhindern.

|**Kurzbeschreibung**
|Eine Kurzbeschreibung der Kategorie eingeben. Die Kurzbeschreibung wird über Template-Variablen in das Design des Webshops eingebunden.

|**Position**
|Zahl eingeben, um die Reihenfolge der Kategorien und Unterkategorien einer Kategorie der gleichen Ebene festzulegen. Die Sortierreihenfolge wird im Menü <<webshop/webshop-einrichten/artikelansichten#, Einrichtung » Mandant » Mandant wählen » Artikelansichten » Einstellungen>> festgelegt. Standardmäßig wird nach aufsteigender Position sortiert. +
**__Tipp:__** Positionsnummern in Zehnerschritten vergeben, damit neue Kategorien dazwischen eingefügt werden können.

|**Mandant (Shop)**
|Einen, mehrere oder alle Mandanten wählen, damit die Kategorie in diesen Mandanten sichtbar ist. +
Wenn in einer Unterkategorie ein Mandant gewählt wird und dieser Mandant in den übergeordneten Kategorien nicht gewählt ist, wird die Auswahl auf die übergeordneten Kategorien übertragen. Wenn in übergeordneten Kategorien bereits andere Mandanten gewählt sind, wird der Mandant zusätzlich gewählt. Die Wahl der anderen Mandanten bleibt erhalten. +
**Sichtbarkeit auf Unterkategorien übertragen** +
Die Option wird nur angezeigt, wenn Unterkategorien vorhanden sind. +
Häkchen setzen, um die Mandantensichtbarkeit auf alle Unterkategorien der Kategorie zu übertragen. Die Funktion bezieht sich nur auf den aktuellen Speichervorgang, also, das Häkchen muss für jeden Vorgang neu gesetzt werden. +
Wenn eine Sichtbarkeit entfernt wird (Häkchen bei Mandanten entfernen und speichern), wird diese Einstellung auch auf die Unterkategorien übertragen, wenn die Funktion nicht aktiviert ist. +
Beim Hinzufügen einer Sichtbarkeit wird diese Sichtbarkeit automatisch auch für die übergeordneten Kategorien gesetzt.

|**Meta-Titel**
|Meta-Titel eintragen. Der Meta-Titel wird sowohl als Tab-Titel im Webbrowser als auch als Suchergebnis in Suchmaschinen angezeigt. Wird das Feld leer gelassen, wird der Kategoriename als Titel verwendet. +
*_SEO-Tipp:_* Auf die Länge des Titels achten. Längere Titel werden in Tabs abgekürzt. Aktueller Richtwert: max. 50 Zeichen

|**Meta-Beschreibung**
|Eine Meta-Beschreibung mit maximal 350 Zeichen eingeben. Die Meta-Beschreibung wird von Suchmaschinen ausgewertet und ist daher besonders für die Startseite wichtig. +
*_SEO-Tipp:_* Die Meta-Beschreibung soll den wesentlichen Inhalt in einem Satz enthalten.

|**Meta-Keywords**
|Stichwörter eingeben, die potentielle Kunden in Suchmaschinen eingeben und die den Inhalt der Kategorie widerspiegeln.

|**Sitemap**
|Zwischen **Anzeigen** und **Nicht anzeigen** wählen. +
**Anzeigen** = Kategorie wird in die Sitemap aufgenommen. +
**Nicht anzeigen** = Kategorie wird nicht in die Sitemap aufgenommen.

|**Robots**
|Zwischen **all**, **index**, **nofollow**, **noindex** und **nofollow, noindex** wählen. Werte des Meta-Elements Robots werden von Suchmaschinen-Crawlern ausgewertet. Dem Crawler wird mit diesen Werten mitgeteilt, wie er mit der Seite und den Links auf dieser Seite verfahren soll. +
**all** = Webseite der Kategorie in den Suchmaschinenindex aufnehmen und Links auf der Seite folgen. +
**index** = In Suchmaschinenindex aufnehmen. +
**nofollow** = Links auf der Seite nicht folgen. +
**noindex** = Nicht in den Suchmaschinenindex aufnehmen. +
**nofollow, noindex** = Den Links nicht folgen und die Webseite der Kategorie nicht in den Suchmaschinenindex aufnehmen.

|**Template-Seite**
|Ein Template wählen. Das hier gewählte Template bildet den Rahmen für die Kategorie. Option steht für Kategorien des Typs **Container** nicht zur Verfügung.

|**Template-Liste**
|Ein Template wählen. Das Template bestimmt, wie die Kategorieübersicht der aktuellen Kategorie aussieht. Option steht nur für Kategorien des Typs **Artikel** zur Verfügung.

|**Template-Produkt**
|Ein Template wählen. Das Template bestimmt die Einzelansicht der Artikel dieser Kategorie. Option steht nur für Kategorien des Typs **Artikel** zur Verfügung.

|**Volltextsuche**
|Wählen, ob die Kategorie zum Suchindex der Kategoriesuche im Webshop hinzugefügt werden soll. +
*_Hinweis:_* Das Template-Plugin Ceres und die Suche FINDOLOGIC berücksichtigen diese Einstellung nicht. +
**Ja** = Wenn im Menü *Einrichtung » Mandant » Mandant öffnen » Webshop » Weiterleitung* die Option *Umleitung bei Kategorie* auf *Content-Suche ausführen* eingestellt ist, werden die Kategoriedaten durchsucht, wenn versucht wird, eine nicht mehr gültige Kategorie-URL zu öffnen. +
Die Kategoriedaten werden außerdem zum Suchindex der Kategoriesuche im Webshop hinzugefügt. Wenn im Webshop ein Suchbegriff eingegeben wird, werden der Kategoriename, Beschreibung 1, Beschreibung 2 und der Meta-Titel der Kategorie nach diesem Suchbegriff durchsucht. +
*_Hinweis:_* Um eine Kategoriesuche zu ermöglichen, sind Code-Anpassungen im Template *CategoryViewContentSearchResultsList* erforderlich. +
**Nein** = Die Kategorie wird nicht zum Suchindex der Kategoriesuche hinzugefügt. +

|**In Linkliste**
|Zwischen **Anzeigen** und **Nicht anzeigen** wählen. +
**Anzeigen** = Kategorie wird in der Navigation im Webshop angezeigt. +
**Nicht anzeigen** = Kategorie wird nicht in der Navigation im Webshop angezeigt.

|**Sichtbar**
|Zwischen **Öffentlich** und **Nach Login** wählen. +
**Öffentlich** = Kategorie ist für alle Besucher des Webshops sichtbar. +
**Nach Login** = Kategorie samt aller Unterkategorien ist nur für eingeloggte Besucher des Webshops sichtbar. Nicht eingeloggte Besucher werden auf die Login-Seite umgeleitet.

|**Elmar-Kategorie**
|Elmar-Kategorie wählen.

|**Template-Variablen und -Funktionen übersetzen**
|Zwischen **Ja**, **Nur Link-Template-Variablen und -Funktionen** und **Nein** wählen. +
**Ja** = Alle Template-Variablen und -Funktionen werden übersetzt. +
**Nur Link-Template-Variablen und -Funktionen** = Nur Link-Template-Variablen und -Funktionen werden übersetzt. +
**Nein** = Keine Template-Variablen und -Funktionen werden übersetzt.
|====

=== Beschreibung speichern

In den Tabs **Beschreibung 1** und **Beschreibung 2** fügst du Text ein und formatierst diesen Text. In das Webdesign deines Shops sowie an anderen Stellen fügst du diese Beschreibung über <<webshop/webshop-einrichten/cms-syntax#grundlagen-template-variablen, Template-Variablen>> und <<webshop/webshop-einrichten/cms-syntax#grundlagen-template-funktionen, Template-Funktionen>> ein. Mit **Beschreibung 1** und **2** hast du die Möglichkeit, zwei Texte zu einer Kategorie zu verfassen und an unterschiedlichen Stellen einer Webseite anzuzeigen. So kannst du **Beschreibung 1** z.B. oberhalb einer Artikelübersicht und **Beschreibung 2** darunter anzeigen.

Über die Dropdown-Liste rechts über dem Eingabefeld wähle den Editor, mit dem du die Beschreibung bearbeiten möchtest. Zur Verfügung stehen der <<webshop/webshop-einrichten/cms#webdesign-werkzeuge-editor, Editor>>, der HTML-Editor **Textfeld** und der <<webshop/webshop-einrichten/cms#webdesign-werkzeuge-syntax-editor, Syntax-Editor>>. Für den Typ **Container** stehen nur der HTML-Editor **Textfeld** und der **Syntax-Editor** zur Verfügung.

[#10]
=== Dokumente hochladen

Im Tab **Dokumente** lädst du Dokumente hoch, die zu dieser Kategorie gehören.

Zulässig sind Datenformate wie JPEG, PNG, GIF, TIFF, PDF, DOC, ODC, OTH, XLS, XML, HTML, HTM, CSS, JavaScript, ZIP, JSON und GZIP.

[NOTE]
.Dokumente hochladen
====
Dokumente fügst du entweder über **Datei hochladen** oder per Drag-and-Drop-Funktion zum Tab hinzu.
====

Bei einer Kategorie vom Typ **Artikel** legst du bis zu zwei Kategoriebilder fest. Du kannst weitere Dokumente und Bilder hochladen und so z.B. das Kategoriebild regelmäßig ändern, ohne das alte Bild zu löschen. Gehe wie unten beschrieben vor, um Kategoriebilder festzulegen.

[.instruction]
Kategoriebilder für Kategorie des Typs Artikel festlegen:

. Öffne die **Kategorie**.
. Wechsele in das Tab **Dokumente**.
. Zeige mit der Maus auf das gewünschte Bild.
. Setze ein Häkchen in der **Auswahlbox** des Bildes.
. Klicke auf **Bild 1**.
. **Speichere** die Einstellungen. +
→ Das Bild erhält einen roten Rahmen mit einer **1**.

Verfahre für das 2. Kategoriebild genauso und klicke in Schritt 5 auf **Bild 2**. Die Auswahl eines Kategoriebilds hebst du auf, indem du ein Häkchen in der Auswahlbox des Bildes setzt und erneut auf **Bild 1** oder **Bild 2** klickst.

Die ausgegrauten Schaltflächen der Symbolleiste werden wählbar, sobald ein oder mehrere Bilder durch Setzen eines Häkchens gewählt wurden. Dies ermöglicht es, die Vorschau für mehrere Bilder gleichzeitig zu öffnen, Bilder gleichzeitig herunterzuladen oder gemeinsam zu löschen.

[TIP]
.Anzeige der Kategoriebilder im Webshop
====
Standardmäßig wird nur Kategoriebild 1 im Webshop angezeigt. Hierfür wurde eine <<webshop/webshop-einrichten/cms-syntax#grundlagen-if, if-Abfrage>> mit der Template-Variable <<webshop/webshop-einrichten/cms-syntax#webdesign-navigation, $CurrentCategoryImageUrl>> in das Template **ItemViewCategoriesList** eingefügt. Damit auch Kategoriebild 2 angezeigt wird, füge eine zweite if-Abfrage in das Template ein.
====

=== Notiz speichern

Im Tab **Notiz** speicherst du Anmerkungen zu einer Kategorie. Hier kannst du z.B. festhalten, woher eine Information stammt, oder vermerken, dass bestimmte Abschnitte nicht geändert werden dürfen. Die in diesem Tab gespeicherten Informationen sind nur in plentymarkets sichtbar und werden nicht im Webshop ausgegeben. Notizen können nicht gelöscht werden.

[.instruction]
Notiz speichern:

. Öffne das Menü **Artikel » Kategorien**.
. Öffne die Kategorie.
. Gib die Notiz in das Bearbeitungsfeld ein.
. **Speichere** die Notiz. +
→ Die Notiz wird gespeichert und in einer gelben Sprechblase angezeigt. +
*_Hinweis:_* Notizen können nicht gelöscht werden.

== Mehrsprachige Kategorieseiten erstellen

Um dein Webshop in mehreren Sprachen verfügbar zu machen, erstellst du die Kategorien in diesen Sprachen. In diesem Kapitel wird daher erläutert, wie du mehrsprachige Kategorien des Typs **Content**, des Typs **Artikel** und des Typs **Container** erstellst. Dabei wird davon ausgegangen, dass diese Kategorien bereits in der Standardsprache des Shops vorliegen. Weitere Informationen zu Voraussetzungen für einen mehrsprachigen Webshop findest du auf der Handbuchseite <<webshop/webshop-einrichten/mehrsprachiger-webshop#, Multilingualismus>>.

Es gibt zwei Vorgehensweisen zum Erstellen von mehrsprachigen Kategorien. Du wählst zwischen einer mehrsprachigen und einer einsprachigen Bearbeitungsansicht. In der einsprachigen Ansicht bearbeitest du eine Sprachversion nach der anderen. In der mehrsprachigen Ansicht bearbeitest du zwei Sprachen parallel. Beide Vorgehensweisen werden unten beschrieben.

=== Mehrsprachige Kategorie über einsprachige Ansicht erstellen

Eine Sprachvariante einer bestehenden Kategorie erstellst du wie im Folgenden beschrieben.

[IMPORTANT]
.Sichtbarkeit der Kategorien im Menü "Artikel » Kategorien"
====
Damit die Kategorien im Verzeichnisbaum des Menüs **Artikel » Kategorien** angezeigt werden, müssen die Kategorien in der Standardsprache des Systems erstellt werden. Das heißt, die Kategorie muss in der Standardsprache zumindest einen Seitennamen haben.
====

[.instruction]
Sprachvariante einer Kategorie erstellen (einsprachig):

. Öffne das Menü **Artikel » Kategorien**.
. Öffne die Kategorie, für die du eine Sprachvariante erstellen möchtest.
. Stelle in der Kopfzeile die Option **Sprache** auf die gewünschte Sprache ein, z. B. **Englisch**.
. Gib unter **Name** eine Bezeichnung für die Seite ein.
. Wähle eine **Template-Seite**, eine **Template-Liste**, ein **Template-Produkt** und eine Option zur **Volltextsuche**. Beachte dabei die Einstellungen der Kategorie in der Standardsprache.
. **Speichere** die Einstellungen. +
→ Der Eintrag wird gespeichert. +
→ Der Pfad der Seite wird erstellt und wird in der Zeile **URL** angezeigt.
. Füge die Inhalte in der gewählten Sprache ein.
. **Speichere** die Einstellungen.

=== Mehrsprachige Kategorie über mehrsprachige Ansicht erstellen

Um eine Sprachvariante einer Kategorie in der mehrsprachigen Ansicht hinzuzufügen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Sprachvariante einer Kategorie erstellen (mehrsprachig):

. Öffne das Menü **Artikel » Kategorien**.
. Klicke im Verzeichnisbaum auf die gewünschte Kategorie. +
→ Die Kategorie wird geöffnet.
. Klicke auf das Symbol **Multilingualität**. +
→ Die mehrsprachige Ansicht der Kategorie wird in einem neuen Tab geöffnet. +
**__Tipp:__** Standardmäßig wird links die Standardsprache des Webshops und rechts Englisch angezeigt.
. Wähle rechts die gewünschte **Sprache**.
. Gib in die Felder **Name**, **URL-Name** und **Meta-Titel** die gewünschten Bezeichnungen ein.
. Trage die fremdsprachigen Texte und Inhalte in das Feld **Beschreibung 1** ein.
. **Speichere** die Einstellungen. +
→ Die Kategorie wird in der gewählten Sprache erstellt.

[TIP]
.Tipp: Zwei neue Sprachen in der zweisprachigen Ansicht öffnen
====
Du kannst in der zweisprachigen Ansicht auch neue Sprachen öffnen, für die noch keine Inhalte gespeichert wurden. Die Standardsprache muss nicht geöffnet sein.
====

== Kategorie aktivieren

Kategorien sind erst im Webshop eines Mandanten (Shops) sichtbar, nachdem die Kategorien aktiviert wurden. Du kannst einzelne Kategorien oder mehrere Kategorien gleichzeitig aktivieren.

Folgende Voraussetzungen müssen erfüllt sein, damit eine Kategorie im Webshop angezeigt wird:

. Die Kategorie muss für den Mandanten aktiviert werden.
. Für den Mandanten muss mindestens eine Variante mit der Kategorie verknüpft sein.
. Im Tab **Kategorien** einer Variante muss mindestens die Kategorie für den gewünschten Mandanten auf **Verfügbar** stehen.
. Die Variante muss verfügbar sein. Der Warenbestand muss also positiv sein und für die Variante muss im Tab **Verfügbarkeit** die Option **Webshop** auf **Sichtbar** gestellt sein.

=== Eine Kategorie aktivieren

Gehe wie unten beschrieben vor, um eine Kategorie zu aktivieren.

[.instruction]
Eine Kategorie aktivieren:

. Öffne das Menü **Artikel » Kategorien**.
. Öffne die Kategorie. +
→ Das Tab **Einstellungen** der Kategorie wird geöffnet.
. Wähle im Bereich **Mandant (Shop)** die Mandanten, in denen die Kategorie aktiv sein soll.
. **Speichere** die Einstellung. +
→ Die Kategorie wird für die gewählten Mandanten (Shops) sichtbar gestellt.


=== Mehrere Kategorien aktivieren

Das Menü **Einrichtung » Mandant » Mandant wählen » Kategorien » Aktivieren** bietet dir die Möglichkeit, mehrere oder alle Kategorien eines Mandanten gleichzeitig zu aktivieren oder zu deaktivieren.

[.instruction]
Mehrere Kategorien für Mandanten gleichzeitig aktivieren:

. Öffne das Menü **Einrichtung » Mandant » Mandant wählen » Kategorien » Aktivieren**.
. Markiere die Kategorien, die du aktivieren möchtest. +
**__Tipp:__** Mit **Alle auswählen** markierst du alle Kategorien. Mit **Alle abwählen** hebst du die Markierung aller markierten Kategorien auf.
. **Speichere** die Einstellungen.
. Prüfe die Anzeige der Kategorien und Artikel im Webshop. +
**__Tipp:__** Es kann etwas dauern, bis eine aktivierte Kategorie im Webshop sichtbar ist. Prüfe bei Problemen alle Einstellungen und lade die Anzeige des  Webshops neu.

== Kategorien verwalten

=== Kategorien filtern

Kategorien können nach dem Mandanten, der Sprache und dem Typ gefiltert werden. Die Filter befinden sich oberhalb des Kategorieverzeichnisses. Ob eine Kategorie in der gewählten Kombination verfügbar ist, erkennst du am Schriftschnitt. Normal dargestellte Kategorien sind in der Kombination verfügbar. Für kursiv dargestellte Kategorien ist für die gewählte Filterkombination aus Mandant, Sprache und Typ keine Konfiguration vorhanden.

=== Kategorie suchen

Die Suchfunktion über dem Kategoriebaum hilft dir, eine Kategorie schnell zu finden. Gib den Namen der gesuchten Kategorie in das Textfeld ein. Bereits während der Eingabe werden die Suchergebnisse angezeigt.

=== Kategorie kopieren

Die Option **Kategorien kopieren** bietet die Möglichkeit, die gleiche Kategorie als Unterkategorie zu verschiedenen übergeordneten Kategorien zu erstellen. Eine Kategorie zu kopieren ist z.B. sinnvoll, wenn du bei Bekleidung zwischen Damen, Herren, Kindern unterscheiden, aber bei allen dreien die Kategorie Hosen benötigen. Dazu die Kategorie mit sämtlichen Einstellungen kopieren und anschließend den Namen und die Beschreibung anpassen.

[.instruction]
Kategorie kopieren:

. Öffne das Menü **Artikel » Kategorien**.
. Zeige mit der Maus auf eine Kategorie.
. Klicke rechts neben der Kategorie auf das Dreieck nach unten. +
→ Ein **Kontextmenü** wird geöffnet.
. Klicke auf **Kategorie kopieren**. +
→ Die Menüübersicht **Kategorie kopieren** wird geöffnet.
. Wähle **Hauptkategorie**, um die Kopie in der Hauptkategorieebene zu speichern. Wähle **Unterkategorie**, um die Kopie in einer Unterkategorieebene zu speichern.
. Wähle die Kategorie, unter der die Kopie eingeordnet werden soll.
. Klicke auf **Kopieren**. +
→ Die Kategorie wird links im Verzeichnisbaum unter der gewählten Kategorie angezeigt.
. *_Optional:_* Passe die Position der Kategorie an, um die Kategorie korrekt einzuordnen.

=== Kategorie verschieben

Kategorien werden im Bereich **Artikel » Kategorien** in der gewählten Struktur dargestellt. Aus der Kategoriestruktur und den Kategorienamen ergibt sich das Navigationsmenü, das im Webshop dargestellt wird. Die Struktur ergibt sich einmal aus den Haupt- und Unterkategorien und der Zuordnung dieser Kategorien zueinander. Das sind die sogenannten Ebenen. Zum anderen ergibt sich die Struktur aus den Positionen. Mit der Position einer Kategorie legst du die Reihenfolge innerhalb einer Kategorieebene fest. Mit der Funktion **Kategorie verschieben** verschiebst du eine Kategorie nachträglich in der Ebene.

[.instruction]
Kategorie in Hauptkategorieebene verschieben:

. Öffne das Menü **Artikel » Kategorien**.
. Zeige mit der Maus auf eine Kategorie.
. Klicke rechts neben der Kategorie auf das Dreieck nach unten. +
→ Ein **Kontextmenü** wird geöffnet.
. Klicke auf **Kategorie verschieben**. +
→ Die Menüübersicht **Kategorie verschieben** wird geöffnet.
. Wähle **Hauptkategorie**.
. Klicke auf **Verschieben**. +
→ Die Kategorie wird links im Verzeichnisbaum in der obersten Ebene angezeigt.
. *_Optional:_* Passe die Position der Kategorie an, um die Kategorie korrekt einzuordnen.

[.instruction]
Kategorie in Unterkategorieebene verschieben:

. Öffne das Menü **Artikel » Kategorien**.
. Zeige mit der Maus auf eine Kategorie.
. Klicke rechts neben der Kategorie auf das Dreieck nach unten. +
→ Ein **Kontextmenü** wird geöffnet.
. Klicke auf **Kategorie verschieben**. +
→ Die Menüübersicht **Kategorie verschieben** wird geöffnet.
. Wähle **Unterkategorie**.
. Wähle die Kategorie, unter der die Kategorie eingeordnet werden soll.
. Klicke auf **Verschieben**. +
→ Die Kategorie wird links im Verzeichnisbaum unter der gewählten Kategorie angezeigt.
. *_Optional:_* Passe die Position der Kategorie an, um die Kategorie korrekt einzuordnen.

=== Kategorien löschen

Du kannst Kategorien entweder vollständig löschen oder eine angezeigte Kombination aus Mandant (Shop) und Sprache. Beide Vorgehensweisen werden nachfolgend beschrieben.

==== Kategorie vollständig löschen

Kategorien können entweder über das Kontextmenü oder über die Symbolleiste der Kategorie gelöscht werden. Dabei wird die Kategorie in allen Mandanten und Sprachen aus dem System gelöscht.

[.instruction]
Kategorie über Kontextmenü löschen:

. Öffne das Menü **Artikel » Kategorien**.
. Zeige mit der Maus auf eine Kategorie.
. Klicke rechts neben der Kategorie auf das Dreieck nach unten. +
→ Das **Kontextmenü** wird geöffnet.
. Klicke auf **Kategorie löschen**. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicke auf **Löschen**. +
→ Die Kategorie wird gelöscht.

[.instruction]
Kategorie über Symbolleiste löschen:

. Öffne das Menü **Artikel » Kategorien**.
. Wähle in den Filtereinstellungen den Mandanten und die Sprache. +
→ Die Kategorien dieser Filterkombination werden angezeigt.
. Öffne die Kategorie.
. Klicke in der Symbolleiste der Kategorie auf **Löschen**. +
→ Das Fenster **Löschen** wird angezeigt.
. Klicke auf **Kategorie löschen**, um die Kategorie vollständig zu löschen. +
→ Die Kategorie wird vollständig gelöscht.

==== Kombination aus Sprache und Mandanten (Shop) löschen

Statt eine Kategorie vollständig zu löschen, kann auch nur Beschreibung und Einstellungen für eine bestimmte Sprache eines Mandanten gelöscht werden. Gehe dazu wie unten beschrieben vor.

[.instruction]
Kombination aus Sprache und Mandanten (Shop) löschen:

. Öffne das Menü **Artikel » Kategorien**.
. Wähle in den Filtereinstellungen den Mandanten und die Sprache. +
→ Die Kategorien dieser Filterkombination werden angezeigt.
. Öffne die Kategorie.
. Klicke in der Symbolleiste der Kategorie auf **Löschen**. +
→ Das Fenster **Löschen** wird angezeigt.
. Klicke auf **Sprache für Mandant löschen**, um die angezeigte Kombination aus Sprache und Mandant zu löschen. +
→ Die Kategorie wird für diese Kombination aus Sprache und Mandant gelöscht.

== Kategorien in Webshop-Design einbinden

=== Kategorie des Typs Content einbinden

Es gibt mehrere Möglichkeiten, Kategorien des Typs **Content** in den Webshop einzubinden. Unten werden beispielhaft zwei dieser Möglichkeiten beschrieben.

==== Einzelne Kategorie einbinden

Zunächst wird beschrieben, wie du eine einzelne Kategorie einbindest.

[.instruction]
Einzelne Kategorie in Design einbinden:

. Öffne das Menü **CMS » Webdesign » Layout**.
. Wähle das Layout, in das die Kategorie eingebunden werden soll.
. Wechsele in das Tab **PageDesignContentMainFrame**.
. Füge die Template-Funktion **&lbrace;Link(ID) %}** an der gewünschten Stelle im Layout ein.
. Ersetze **ID** durch die ID der Kategorie.
. **Speichere** die Einstellungen.

==== Kategorie in anderer Kategorie anzeigen

Um den Inhalt einer Kategorie über eine Template-Funktion in einer anderen Kategorie anzuzeigen, füge die Template-Funktion **&lbrace;CategoryContentBody(ID) %}** an der gewünschten Stelle der Seite ein und ersetze **ID** durch die ID der Content-Kategorie, die angezeigt werden soll. So kannst du z.B. die AGBs in einer anderen Kategorie anzeigen.

==== Alle Kategorien des Typs Content einbinden

[.instruction]
Alle Kategorien des Typs Content in Design einbinden:

. Öffne das Menü **CMS » Webdesign » Layout**.
. Wähle die Vorlage, in die die Kategorien eingebunden werden sollen.
. Wechsele in das Tab **PageDesignContentMainFrame**.
. Füge die Template-Funktion **&lbrace;Container_NavigationCategories() %}** an der gewünschten Stelle im Layout ein.
. Füge die Template-Funktion der Navigation ein, die du für Kategorien des Typs **Content** eingestellt hast.
. **Speichere** die Einstellungen.

[IMPORTANT]
.Kategorietyp für die Navigation einstellen
====
Im Menü **CMS » Webdesign » Layout » Navigation** stehen verschiedene Designs für die Kategorienavigation zur Verfügung. Stelle bei dem Design, das du für die Kategorien des Typs **Content** verwendest, unbedingt im Tab **Einstellungen** auch den Typ **Content** ein. +
Wenn du ein plentymarkets Standard-Design verwendest, ist **NavigationCategories4** für Kategorien des Typs **Content** vorgesehen. Diese Einstellung kannst du jederzeit ändern.
====

=== Kategorie des Typs Container in Webshop-Design einbinden

Kategorien des Typs **Container** werden über Template-Funktionen in den Webshop eingebunden.

==== Kategorie anzeigen

Um den Inhalt einer Kategorie des Typs **Container** über Template-Funktionen anzuzeigen, z.B. in einer anderen Kategorie, fügst du die Template-Funktion **&lbrace;CategoryContentBody(ID) %}** an der gewünschten Stelle der Seite ein und ersetzt **ID** durch die ID der Kategorie des Typs **Container**, die angezeigt werden soll.

==== Kategorie verknüpfen

Für die Bestellschritte des <<webshop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-individueller-bestellvorgang, Individuellen Bestellvorgangs>> werden die Kategorien des Typs **Container** in den **Design-Einstellungen** im Tab **Bestellvorgang** verknüpft.

== Kategorierabatte speichern

Im Menü **Einrichtung » Mandant » Mandant wählen » Kategorien » Rabatte** hinterlegst du Mengenrabatte für einzelne Artikelkategorien. Pro Kategorie sind bis zu drei Mengenrabatte möglich. Die gespeicherten Rabatte werden automatisch angewendet, wenn bei einer Bestellung die rabattfähige Menge an Produkten aus einer Kategorie erreicht oder überschritten wird. Die eingegebenen Rabatte gelten jedoch nur für die Standardkategorie einer Variante.

[.instruction]
Kategorierabatte speichern:

. Öffne das Menü **Einrichtung » Mandant » Mandant wählen » Kategorien » Rabatte**.
. Nimm die Einstellungen vor. Beachte <<tabelle-kategorierabatte-speichern>>.
. **Speichere** die Einstellungen. +
→ Der Rabatt wird automatisch im Webshop angewendet, wenn die rabattfähige Menge bestellt wird. +
**__Hinweis:__** Die Rabatte gelten nur für die Standardkategorie einer Variante.

[[tabelle-kategorierabatte-speichern]]
.Kategorierabatte speichern
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Rabatt 1 (%)**; +
**Rabatt 2 (%)**; +
**Rabatt 3 (%)**
|Rabatt in Prozent eingeben, der angewendet werden soll, wenn die eingegebene Menge an Varianten erreicht wird.

|**ab Menge**
|Menge der Varianten eingeben, die aus dieser Kategorie bestellt werden müssen, damit der Rabatt angewendet wird.
|====
