= Multipacks, Artikelpakete und Sets verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Varianten gruppieren, Produkte zusammenfassen, Kombiangebote, Varianten kombinieren
:description: Erfahre, wie du Varianten in plentymarkets kombinierst, um sie im Paket zu verkaufen.
:position: 30
:url: artikel/multipacks-pakete-sets-verwalten
:id: 2

plentymarkets bietet verschiedene Möglichkeiten, Produkte zu kombinieren und als eine Verkaufseinheit anzubieten. Bei einer Bestellung wird dann gleichzeitig mehr als ein Produkt in den Warenkorb gelegt. <<tabelle-produkte-zusammenfassen>> zeigt die verschiedenen Möglichkeiten, mehrere Produkte kombiniert zu verkaufen.

[TIP]
.Schon mit der Artikelverwaltung vertraut?
====
Die Informationen auf dieser Seite richten sich an Benutzerinnen und Benutzer von plentymarkets, die bereits mit der Artikelverwaltung vertraut sind. Grundlegende Informationen dazu, wie du Artikel und Varianten erstellst und verwaltest, findst du auf der Handbuchseite <<artikel/artikel-verwalten#, Artikel verwalten>>.
====

[[tabelle-produkte-zusammenfassen]]
.Mehrere Produkte gleichzeitig verkaufen
[cols="1,5,1"]
|====
|Art |Erläuterung |Artikeltyp

|<<#1000, Multipack>>
a|* Multipacks bestehen aus derselben Variante in verschiedenen Stückzahlen.
* Die Hauptvariante entspricht der Menge 1 der weiteren Varianten des Artikels.
* Der Bestand wird nur an der Hauptvariante verwaltet.
* Die Varianten des Artikels entsprechen den verschiedenen Mengen der Hauptvariante.
|Multipack

|<<#2000, Paket>>
a|* Pakete bestehen aus je einer Variante verschiedener Artikel.
* Bestellt werden kann nur das komplette Paket, die einzelnen Bestandteile können also nicht gewählt werden.
|Standard

|<<#3000, Set>>
a|*_Hinweis:_* Sets können zurzeit zwar erstellt, aber noch nicht im Webshop dargestellt werden.

* Sets bestehen aus mehreren Artikeln.
* Für jeden Artikel des Sets kann bei der Bestellung eine Variante des Artikels gewählt werden.
* Die Hauptvariante selbst ist virtuell, kann also nicht verkauft werden.
|Set
|====


[#1000]
== Multipack einrichten

Bei einem Artikel des Typs *Multipack* entspricht die Hauptvariante der kleinsten Verkaufseinheit des Produkts. Alle weiteren Varianten des Artikels sind Kombinationen dieser kleinsten Verkaufseinheit. Der Bestand wird nur an der Hauptvariante gepflegt. Alle Varianten des Artikels haben dieselben Attribute. Das heißt, dass bei der Bestellung nicht zum Beispiel zwischen verschiedenen Farben oder Größen des Produkts gewählt werden kann. Im Onlineshop kann nur zwischen den verschiedenen Varianten gewählt werden, die der Anzahl des Produktes entspricht.

[#1100]
=== Artikel des Typs Multipack erstellen

Beim Erstellen eines neuen Multipacks wird wie bei Artikeln des Typs *Standard* automatisch eine Hauptvariante erstellt. Diese Hauptvariante ist fest mit dem Artikel des Typs *Multipack* verbunden und kann nur zusammen mit dem Artikel erstellt oder gelöscht werden. Die Hauptvariante selbst entspricht der kleinsten Verkaufseinheit des Produkts.

[.instruction]
Artikel des Typs Multipack erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Typ *Multipack*.
. Nimm die weiteren Einstellungen vor. Beachte <<tabelle-multipack-erstellen>>.
. *Speichere* die Einstellungen. +
→ Der Artikel des Typs *Multipack* wird erstellt. +
→ Die Hauptvariante wird in einem neuen Tab geöffnet.

[TIP]
.Neuen Artikel des Typs *Multipack* in Übersicht anzeigen
====
Der neue Artikel des Typs *Multipack* ist nicht aktiv. Um neu erstellte Artikel in der Übersicht im Menü *Artikel » Artikel bearbeiten* anzuzeigen, wähle auf der linken Seite für den Filter *Aktiv* die Option *ALLE*. Klicke dann auf *Suchen*. Wie du Artikel und Varianten für den Webshop aktivierst, erfährst du im Kapitel <<artikel/artikel-verwalten#180, Verfügbarkeit einstellen>>.
====

[[tabelle-multipack-erstellen]]
.Artikel des Typs Multipack erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Artikeldaten*

|*Typ*
|Artikeltyp *Multipack* wählen. +
*Standard* = Erstellt einen Artikel des Typs *Standard* mit Hauptvariante. +
*Set* = Erstellt einen Artikel des Typs *Set*.
*Multipack* = Erstellt einen Artikel des Typs *Multipack*.

|*ID*
|Die Artikel-ID ist eine eindeutige, fortlaufende Zahl, die plentymarkets zur exklusiven Zuordnung jedes Artikels benötigt. Wird dieses Feld freigelassen, vergibt plentymarkets automatisch die nächste freie ID.

|*Name*
|Namen für das Multipack eingeben. Der Name ist eine Pflichteingabe. Wie du den Namen änderst, erfährst du im Kapitel <<artikel/artikel-verwalten#50, Artikeltexte eingeben>>.

2+|*Variante » Kategorieverknüpfung*

|Kategoriewahl
|Die Kategorie wählen, in der das Multipack veröffentlicht werden soll. Alternativ auf *Neue Kategorie* klicken, um eine neue Kategorie zu erstellen.
|====

[#1300]
=== Artikel des Typs Multipack bearbeiten

Nachdem du den Artikel des Typs *Multipack* erstellt hast, nimm die weiteren Einstellungen vor. Diese Einstellungen sind identisch mit den Einstellungen für <<artikel/artikel-verwalten#30, Artikel des Typs Standard>>.

[#1400]
=== Multipack-Variante erstellen

Beim Erstellen eines Artikels des Typs *Multipack* wird immer eine Hauptvariante erstellt. Die Hauptvariante ist fest mit dem Artikel verbunden. Die Hauptvariante kann nicht gelöscht werden. Diese Hauptvariante entspricht der kleinsten Verkaufseinheit des Produkts. Alle weiteren Varianten des Artikels entsprechen dieser kleinsten Verkaufseinheit mal x. Der Bestand aller Varianten wird nur an der Hauptvariante gepflegt. Im Tab *Bestand* der weiteren Varianten des Artikels wird nur der theoretische Bestand angezeigt. Wenn sich der Bestand der Hauptvariante ändert, wird der Bestand für die anderen Varianten des Artikels neu berechnet.

[.instruction]
Multipack-Variante erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel des Typs *Multipack*.
. Wechsele in das Tab *Varianten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neue Variante erstellen* wird geöffnet.
. Gib als Inhalt eine Stückzahl der Hauptvariante ein. +
*_Tipp:_* Einheit und Attribute sind nicht änderbar.
. Klicke auf *Variante erstellen*. +
→ Die Variante wird erstellt. +
→ Die Variante wird in der Variantenübersicht angezeigt.

Die Einstellungen der Variante bearbeitest du genauso wie <<artikel/artikel-verwalten#170, Varianten von Artikeln des Typs Standard>>. Beachte jedoch die folgenden Besonderheiten von Multipack-Varianten:

* Deaktiviere die Vererbung des Verkaufspreises und speichere einen eigenen Preis.
* Der Tab *Bestand* ist rein informativ. Der Bestand wird nur an der Hauptvariante gepflegt.

[#2000]
== Artikelpaket einrichten

Ein Artikelpaket besteht aus mehreren Produkten. Der Paketpreis eines Artikelpakets kann dabei günstiger sein als die Summe der Einzelpreise. Pakete filterst du im Menü *Artikel » Artikel bearbeiten* mit dem Filter *Paket*.

[#2100]
=== Artikelpaket erstellen

Im Tab *Paket* eines Artikels des Typs *Standard* erstellst du ein Artikelpaket, das sich aus mehreren Bestandteilen, den Basisartikeln, zusammensetzt. Wenn du dem geöffneten Artikel weitere Varianten hinzufügst, wird daraus ein Paket. Die Bestandteile des Pakets werden im Tab *Paket-Bestandteile* angezeigt und werden dort auch bearbeitet und gelöscht.

[.instruction]
Artikelpaket erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Typ *Standard*.
. Gib einen Namen ein.
. Gib den Inhalt ein.
. Wähle eine Kategorie.
. Nimm bei Bedarf weitere Einstellungen vor. Beachte dazu die Erläuterungen zu Artikeln des Typs *Standard* auf der Handbuchseite <<artikel/artikel-verwalten#tabelle-standardartikel-erstellen, Artikel verwalten>>.
. *Speichere* die Einstellungen. +
→ Der Artikel wird erstellt. +
→ Die Hauptvariante wird in einem neuen Tab geöffnet.
. Öffne die Variante.
. Wechsele in das Tab *Paket » Variante hinzufügen*.
. Setze Häkchen bei Varianten, die du als Paketbestandteile hinzufügen möchtest.
. Klicke auf *Variante hinzufügen*. +
→ Die Bestandteile werden zum Artikelpaket hinzugefügt und im Tab *Paket-Bestandteile* angezeigt.

Verknüpfe anschließend einen Verkaufspreis mit dem Artikelpaket und gib einen Preis ein. Wie du Verkaufspreise verknüpfst, erfährst du im Kapitel <<artikel/artikel-verwalten#240, Verkaufspreise verknüpfen>>. In der Auftragsabwicklung wird dann nur der Paketpreis angegeben und die Paketbestandteile ohne Einzelpreise.

[NOTE]
.Vorhandenen Artikel als Paketartikel einrichten
====
Anstatt einen neuen Paketartikel zu erstellen, kannst du auch einen vorhandenen Artikel verwenden und diesem Paketbestandteile hinzufügen. Beachte, dass der Paketartikel, dem du Bestandteile hinzufügst, keinen eigenen Bestand haben darf.
====

[#2200]
=== Paketbestandteile bearbeiten oder löschen

Im Tab *Paket-Bestandteile* änderst du die Menge der im Artikelpaket enthaltenen Varianten, siehst den Nettowarenbestand der Varianten und löschst nicht mehr benötigte Paket-Bestandteile.

[.instruction]
Paketbestandteil löschen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Wähle für den Filter *Paket* die Einstellung *Ja*.
. Klicke auf *Suchen*. +
→ Alle Paketartikel werden in der Übersicht angezeigt.
. Öffne den Paketartikel.
. Öffne die Variante.
. Wechsele in das Tab *Paket » Paket-Bestandteile*.
. Setze Häkchen bei den Paketbestandteilen, die du löschen möchtest.
. Klicke auf *Paket-Bestandteile löschen*. +
→ Die Paketbestandteile werden aus dem Artikelpaket gelöscht.

[#2300]
=== Mehrere Pakete in einem Artikel abbilden

Artikelvarianten können zu Paketen mit verschiedenen Bestandteilen werden. Auf diese Weise gestaltest du Artikelpakete komplex und vielseitig nach Ihren Anforderungen.

[.subhead]
Beispiel für Paketvarianten: du möchtest je ein Handtuch und ein Badetuch im Paket in unterschiedlichen Farben verkaufen. Hierfür sind folgende Schritte notwendig:

* <<artikel/artikel-verwalten#400, Attribut erstellen>> mit den notwendigen Werten, zum Beispiel rot und blau
* <<artikel/artikel-verwalten#20, Artikel erstellen>>, der als Paketartikel dient, zum Beispiel Handtuchpaket
* <<artikel/artikel-verwalten#160, Varianten erstellen>> und dabei die Attributwerte verknüpfen
* Artikel für Paketbestandteile erstellen, zum Beispiel Handtuch und Badetuch
* Varianten für Paketbestandteile erstellen, zum Beispiel rotes Handtuch, blaues Handtuch etc.
* <<#2100, Paketbestandteile>> zu den Varianten des Artikelpakets hinzufügen

Auf diese Weise bietest du in deinem Webshop den Artikel *Handtuchpaket* als Paket in den Farben *Rot* und *Blau* an.

[#2400]
=== Warenbestand von Artikelpaketen einstellen

Der Warenbestand des Pakets richtet sich nach dem Paketbestandteil mit dem geringsten Bestand. Der Warenbestand dieses Paketbestandteils wird in der Artikelübersicht im Menü *Artikel » Artikel bearbeiten* in der Spalte *WB netto* angezeigt. Am Paketartikel selbst pflegst du keinen Bestand. Im Paketbestandteil im Tab *Bestand* verwaltest du den Warenbestand, buchst neue Wareneingänge, korrigierst Bestände und überblickst Zuläufe und Warenbewegungen. Weitere Informationen findest du auf der Handbuchseite <<warenwirtschaft#, Warenwirtschaft>>.


[#3000]
== Set einrichten (nicht verkaufbar)

[#3100]
=== Artikel des Typs Set erstellen

[WARNING]
.Artikel des Typs Set sind nicht im Webshop darstellbar
====
Zurzeit kannst du Artikel des Typs *Set* zwar erstellen, aber noch nicht im Webshop darstellen. Daher kannst du die Option *Aktiv* für Artikel des Typs *Set* nicht wählen.
====

Ein Setartikel besteht aus mehreren Artikeln. Bei Artikeln des Typs *Set* kann bei der Bestellung aus den verschiedenen Varianten der darin enthaltenen Artikel ein Set zusammengezustellt werden. Anders als bei Artikelpaketen kann also bei Artikelsets für die im Set enthaltenen Produkte eine von mehreren Varianten gewählt werden. Sets filterst du im Menü *Artikel » Artikel bearbeiten* mit dem Filter *Typ*.

[#3200]
=== Setbestandteile vorbereiten

Erstelle zunächst einen <<artikel/artikel-verwalten#880, Verkaufspreis>> des Typs *Preisset*. Verlinke diesen Verkaufspreis dann mit den Varianten von Artikeln des Typs *Standard*, die du zu einem Set hinzufügen möchtest, und speichere einen Preis.

[#3300]
=== Artikel des Typs Set erstellen

Beim Erstellen eines neuen Sets wird wie bei Artikeln des Typs *Standard* automatisch eine Hauptvariante erstellt. Diese Hauptvariante ist fest mit dem Artikel des Typs *Set* verbunden und kann nur zusammen mit dem Artikel erstellt oder gelöscht werden. Anders als bei Artikeln des Typs *Standard* ist die Hauptvariante eines Artikels des Typs *Set* jedoch nur virtuell. Die Hauptvariante selbst entspricht also keinem physischen Produkt. Die Hauptvariante eines Artikels des Typs *Set* dient lediglich als Datencontainer, zu dem du die Setbestandteile hinzufügst, und dazu, Einstellung für das gesamte Set vorzunehmen, das sich aus der Summe der einzelnen Bestandteile ergibt.

[.instruction]
Artikel des Typs Set erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Typ *Set*.
. Nimm die weiteren Einstellungen vor. Beachte <<tabelle-setartikel-erstellen>>.
. *Speichere* die Einstellungen. +
→ Der Artikel des Typs *Set* wird erstellt. +
→ Die Hauptvariante wird in einem neuen Tab geöffnet.

[TIP]
.Neuen Artikel des Typs *Set* in Übersicht anzeigen
====
Der neue Artikel des Typs *Set* ist noch inaktiv. Um neue Artikel nach dem Erstellen in der Übersicht im Menü *Artikel » Artikel bearbeiten* anzuzeigen, wähle auf der linken Seite für den Filter *Aktiv* die Option *ALLE*. Klicke dann auf *Suchen*. Wie du Artikel und Varianten für den Webshop aktivierst, erfährst du im Kapitel <<artikel/artikel-verwalten#180, Verfügbarkeit einstellen>>.
====

[[tabelle-setartikel-erstellen]]
.Artikel des Typs Set erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Artikeldaten*

|*Typ*
|Artikeltyp *Set* wählen. +
*Standard* = Erstellt einen Artikel des Typs *Standard* mit Hauptvariante. +
*Set* = Erstellt einen Artikel des Typs *Set*.

|*ID*
|Die Artikel-ID ist eine eindeutige, fortlaufende Zahl, die plentymarkets zur exklusiven Zuordnung jedes Artikels benötigt. Wird dieses Feld freigelassen, vergibt plentymarkets automatisch die nächste freie ID.

|*Name*
|Namen für das Set eingeben. Der Name ist eine Pflichteingabe. Wie du den Namen änderst, erfährst du im Kapitel <<artikel/artikel-verwalten#50, Artikeltexte eingeben>>.

2+|*Variante » Kategorieverknüpfung*

|Kategoriewahl
|Die Kategorie wählen, in der das Set veröffentlicht werden soll. Alternativ auf *Neue Kategorie* klicken, um eine neue Kategorie zu erstellen.
|====

[#3400]
=== Artikel des Typs Set bearbeiten

Nachdem du den Artikel des Typs *Set* erstellt hast, nimm nun die weiteren Einstellungen vor.

[.instruction]
Artikel des Typs Set bearbeiten:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel des Typs *Set*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-setartikel-bearbeiten>>.
. *Speichere* die Einstellungen.

[[tabelle-setartikel-bearbeiten]]
.Artikel des Typs Set bearbeiten
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Tab: Global*

|*Erlöskonto*
|Erlöskonto eingeben. Weitere Informationen zum Erlöskonto findest du auf der Handbuchseite <<auftraege/buchhaltung#90, Buchhaltung>>.

|*Altersfreigabe*
|Altersfreigabe für den Artikel des Typs *Set* wählen. Dabei die Altersfreigabe der Variante mit der höchsten Altersfreigabe wählen. Für den Versand von Artikeln mit *Altersfreigabe 18* muss ein <<fulfillment/versand-vorbereiten#1000, Versandprofil>> verknüpft sein, bei dem die Option *PostIdent* aktiviert ist.

|*Gutschein*
|Wählen, ob Gutscheine für das Set *möglich* oder *verboten* sind, oder ob das Set *nur mit Gutschein kaufbar* ist. Weitere Informationen zu Gutscheinen findest du auf der Handbuchseite <<auftraege/gutscheine#, Gutscheine>>.

|*Versandpaket*
|Versandpaket verwenden. Versandpakete haben festgelegte Maße. Wenn du die Maße des Artikels im Tab *Einstellungen* des Artikels des Typs *Set* eingibst, erfolgt automatisch die Zuordnung des passenden Versandpakets. Wie du Versandpakete einrichtest, erfährst du auf der Handbuchseite <<fulfillment/versand-vorbereiten#1900, Versandpakete>>.

|*Seriennummer*
|Seriennummern zur eindeutigen Kennzeichnung jedes verkauften Sets verwenden. Seriennummern gewährleisten die Rückverfolgbarkeit von Artikeln im Fehler- oder Problemfall. Wie du Seriennummern einrichtest, erfährst du unter <<artikel/artikel-verwalten#820, Seriennummern verwenden>>.

|*Versandprofile*
|Ein, mehrere oder *ALLE* <<fulfillment/versand-vorbereiten#1000, Versandprofile>> aktivieren. Standardmäßig ist kein Versandprofil aktiviert. Mindestens ein Versandprofil aktivieren, da sonst ungewollte Effekte bei der Versandkostenberechnung auftreten können. Wenn ein Auftrag Artikel enthält, bei denen kein Versandprofil aktiviert wurde, wird das Standard-Versandprofil aus dem Standard-Webshop für die Artikel verwendet. Wenn kein Standard-Versandprofil festgelegt ist, wird das Versandprofil mit der höchsten Priorität verwendet.

|*Shop-Aktion*
|Shop-Aktion oder *Keine* wählen. Sets können als Shop-Aktionen in deinem Webshop dargestellt werden. Wie du Shop-Aktionen einbindest, erfährst du unter <<artikel/artikel-verwalten#1010, Artikel als Top-Artikel präsentieren>>. +
*Sonderangebot* = Stellt eine Liste von Sonderangeboten dar. +
*Neuheit* = Stellt eine Liste der neuesten Artikel dar. +
*Top-Artikel* = Stellt eine Liste der meistverkauften Artikel dar.

|*Artikelbewertung*
|Erstbewertung von *1* bis *5* oder *1* bis *10* für das Set eingeben. Wenn du Artikelbewertungen verwendest, wird der eingegebene Wert als Erstbewertung des Sets angezeigt. Der Wert wird nach jeder Bewertung automatisch auf einen Durchschnittswert angepasst. Den Bewertungsbereich legst du im Menü *System » Systemeinstellungen » Mandant » Global » Feedback » Tab: Artikel* unter *Maximale Bewertungspunkte* fest.

|*Artikelbild*
|Auf das Bild klicken, um das Tab *Bilder* aufzurufen.

2+|*Tab: Set*

|*Tab: Einstellungen* +
*Tab: Artikel hinzufügen*
|Artikel <<#3500, hinzufügen>>, <<#3600, ändern>> und <<#3900, löschen>>.

2+|*Tab: Varianten-ID*

|*Tab: Einstellungen*
|Einstellungen entsprechen den Einstellungen für Artikel des Typs *Standard*, siehe <<artikel/artikel-verwalten#230, Verfügbarkeit von Varianten einstellen>> und <<artikel/artikel-verwalten#250, Barcodes verknüpfen>>. Auf das Bild klicken, um das Tab *Bilder* aufzurufen.

|*Tab: Kategorien*
|Einstellungen entsprechen den Einstellungen für Artikel des Typs *Standard*, siehe <<artikel/artikel-verwalten#300, Zusätzliche Kategorien verknüpfen>>.

|*Tab: Verfügbarkeit*
|In der Spalte *Verfügbar* Häkchen bei den Mandanten setzen, in denen das Set verfügbar sein soll.

2+|*Tab: Texte*

|Texte
|Einstellungen entsprechen den Einstellungen für Artikel des Typs *Standard*, siehe <<artikel/artikel-verwalten#50, Artikeltexte eingeben>>.

2+|*Tab: Bilder*

|Bilder
|Bilder des Sets hochladen. Im Webshop werden außerdem die Bilder der Varianten des Sets angezeigt. Die weiteren Einstellungen entsprechen den Einstellungen für Artikel des Typs *Standard*, siehe <<artikel/artikel-verwalten#90, Artikelbilder hochladen>>.

2+|*Tab: Media*

|Media
|Einstellungen entsprechen den Einstellungen für Artikel des Typs *Standard*, siehe <<artikel/artikel-verwalten#110, Dateien zum Download bereitstellen>>.
|====

[#3500]
=== Bestandteile zum Set hinzufügen

Füge nun die Artikel des Typs *Standard* zu dem Setartikel hinzu, die du als Set anbieten möchtest. Wenn du einen Artikel mit mehreren Varianten hinzufügst, wird bei der Bestellung im Webshop eine dieser Varianten als Bestandteil des Sets gewählt. Bei Artikeln, die nur eine Hauptvariante, d.h. keine weiteren Varianten haben, gibt es keine Wahlmöglichkeit. Lediglich die Hauptvariante wird zum Set hinzugefügt.

[.instruction]
Bestandteile zum Setartikel hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Setartikel.
. Öffne das Tab *Set*.
. Öffne das Tab *Artikel hinzufügen*. +
→ Eine Liste der Artikel wird angezeigt.
. Wähle die Artikel, die Bestandteile des Sets sein sollen.
. *Speichere* die Einstellungen. +
→ Die Artikel werden zum Setartikel hinzugefügt.

[#3600]
=== Menge eines Setbestandteils ändern

Im Tab *Set » Einstellungen* eines Setartikels sind die Bestandteile eines Setartikels aufgelistet. In der Spalte *Menge* gibst du an, wie viele Exemplare der gewählten Variante des Artikels Bestandteil des Sets sein sollen. Standardmäßig ist die Menge *1*.

[.instruction]
Menge eines Setbestandteils ändern:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Setartikel.
. Öffne das Tab *Set*.
. Öffne das Tab *Einstellungen*. +
→ Eine Liste der Bestandteile des Sets wird angezeigt.
. Gib in der Spalte *Menge* die gewünschte Menge ein.
. *Speichere* die Einstellungen. +
→ Die Menge wird geändert.

[#3700]
=== Rabatt für Setartikel festlegen

Standardmäßig ergibt sich der Preis eines Artikelsets aus der Summe der Einzelpreise der Setbestandteile. Du hast jedoch die Möglichkeit, einen Rabatt in % auf den Gesamtpreis des Sets zu gewähren.

[.instruction]
Rabatt für Setartikel festlegen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Setartikel.
. Öffne das Tab *Set*.
. Öffne das Tab *Einstellungen*. +
→ Eine Liste der Bestandteile des Sets wird angezeigt.
. Trage in das Feld *Rabatt* den Prozentsatz ein, um den der Gesamtpreis rabattiert werden soll.
. *Speichere* die Einstellungen. +
→ Der Rabatt wird angewendet.

[#3800]
=== Warenbestand von Sets

Der Warenbestand eines Setartikels richtet sich nach der Variante des Sets mit dem geringsten Bestand. Der Warenbestand dieser Variante wird in der Artikelübersicht im Menü *Artikel » Artikel bearbeiten* in der Spalte *WB netto* angezeigt. Am Artikel des Typs *Set* selbst pflegst du keinen Bestand. Den Warenbestand verwaltest du stattdessen im Tab *Bestand* der Setbestandteile. Weitere Informationen findest du auf der Handbuchseite <<warenwirtschaft#, Warenwirtschaft>>.

[#3900]
=== Setbestandteile entfernen

Gehe wie unten beschrieben vor, um nicht mehr benötigte Bestandteile aus dem Setartikel zu entfernen.

[.instruction]
Setbestandteile entfernen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Setartikel.
. Öffne das Tab *Set*.
. Öffne das Tab *Einstellungen*. +
→ Eine Liste der Bestandteile des Sets wird angezeigt.
. Setze Häkchen bei den Artikeln, die du aus dem Setartikel entfernen möchten.
. Klicke auf *Bestandteile löschen*. +
→ Die Artikel werden aus dem Setartikel entfernt.
