= IncomingItems
:lang: en
include::{includedir}/_header.adoc[]
:keywords: data format, special format, data import
:description: Special format IncomingItems for booking new incoming items
:position: 107

The **IncomingItems** special format is used to import incoming items. This data format is available as a special format in the **Data » Dynamic import** menu. You may want to import the current stock if you are using an external stock management system and you simply want to compare the stock with plentymarkets.

With the **IncomingItems** data format, you only import certain incoming items data records and not the entire stock. If you want to import the entire stock, refer to the <<basics/data-exchange/export-import/importing-data#120, Importing stock>> chapter on the <<basics/data-exchange/export-import/importing-data#, Importing data>> page of the manual.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the **IncomingItems** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

[cols="1,3,3"]
|====
|Field name |Explanation |Filter

|**AttributeValueSetID**
|ID of the item variation
|

|**ItemEAN**
|EAN code for an item
|

|**ItemID**
|Unique item ID; numerical value, 2^31 at maximum
|

|**ItemNo**
|Item number. Letters and numbers are possible.
|

|**LocationID**
|Storage location ID
|

|**PurchasePrice**
|Purchase price
|

|**Stock**
|Imported stock of an item (incoming items)
|

|**VariationEAN**
|EAN of the item variation
|

|**VariationID**
|ID of the item variation
|

|**VariationNo**
|Number of the item variation
|

|**WarehouseID**
|Warehouse ID
|Activate the filter and select the warehouse from the drop-down list.
|====

__Table 1: data fields of the **IncomingItems** data format__

== Overview of the mandatory fields

The following mandatory fields must be available for the data format **IncomingItems** and need to have a valid value saved for them:

Mandatory fields for individual items:

* **Stock**
* **WarehouseID**
* as well as one **Item** format

Mandatory fields for item variations:

* **Stock**
* **WarehouseID**
* **AttributeValueSetID**
* as well as one **Item** format

or

* **Stock**
* **WarehouseID**
* as well as one **Variation** format (e.g. **VariationID**)
