= EASYMARKETING
:lang: de
include::{includedir}/_header.adoc[]
:keywords: easymarketing, Mandant, Webshop
:position: 50

*System » Mandant » Mandant wählen » Dienste » Easymarketing*

== Allgemeines über EASYMARKETING

EASYMARKETING organisiert Online-Werbung vollautomatisiert. Das System analysiert Ihren Webshop und ermittelt die relevanten Keywords. Es setzt anschließend die Kampagnen auf, setzt CPCs und erstellt Anzeigen. Diese werden stetig optimiert, um so die Ergebnisse zu verbessern. (Quelle: vgl. link:https://easymarketing.de/[easymarketing.de^])

Mithilfe der Schnittstelle zu EASYMARKETING werden Bestellungen in Ihrem Webshop getrackt und es wird eine google site verification ausgeführt.

== EASYMARKETING einrichten

Registrieren Sie sich zunächst bei link:https://easymarketing.de/users/new?website_url=&expected_conversion_rate=&advertising_strategy=aggressive&webshop_or_other=other&daily_budget=13[EASYMARKETING^]. Sie erhalten einen Token, den Sie in plentymarkets eintragen.

[.instruction]
EASYMARKETING-Einstellungen konfigurieren:

. Öffnen Sie das Menü *Easymarketing* (Pfad siehe oben).
. Tragen Sie Ihren *Access Token* ein, den Sie von EASYMARKETING erhalten haben.
. Setzen Sie ein Häkchen bei *Aktiv*.
. Klicken Sie auf *Speichern*, um Ihre Einstellungen zu sichern.
