= Händlerbund
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Rechtliche Angaben, Händlerbund
:description: plentymarkets Integration: Richten Sie die Schnittstelle zu Händlerbund und das Bewertungstool in plentymarkets ein.
:position: 90

Der Händlerbund e.V. mit Sitz in Leipzig ist der größte Onlinehandelsverband Europas und einer der führenden Anbieter von <<omni-channel/online-shop/mandanten-einrichten/webshop#rechtliche-angaben, **Rechtstexten**  >> im Internet. Mit der AGB-Schnittstelle des Händlerbundes können Sie anwaltlich erstellte Rechtstexte auch per Mausklick in Ihr plentymarkets System einbinden. Eine Aktualisierung der Rechtstexte, die z.B. durch eine Gesetzesänderung erforderlich wird, kann somit ohne großen Aufwand vorgenommen werden.

== Beim Händlerbund registrieren

Damit Sie die Leistungen des Händlerbunds für Ihr plentymarkets-System nutzen können, müssen Sie sich zuerst link:http://www.haendlerbund.de/mitgliedschaft/details[**registrieren**].

[IMPORTANT]
.SOAP-API für plentymarkets Zero nicht verfügbar
====
Beachten Sie, dass das Modul **SOAP-API**, das für die Einrichtung der Schnittstelle zu Händlerbund benötigt wird, für plentymarkets Zero nicht zur Verfügung steht.
====

== Benutzer für Händlerbund einrichten

Ihr plentymarkets-System wird über die SOAP-Schnittstelle mit dem Händlerbund verbunden. Für den Zugriff wird zunächst ein eigenes <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#10, **Benutzerkonto** >> mit Zugriffsrechten auf die API in ihrem System eingerichtet.

[.instruction]
Benutzerkonto einrichten:

. Öffnen Sie das Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten**.
. Klicken Sie auf **Neu**. +
→ Das Fenster **Neuen Benutzer anlegen** wird geöffnet.
. Geben Sie den **Benutzernamen**, den **realen Namen** und das **Passwort** ein.
. Wiederholen Sie das Passwort.
. Geben Sie die E-Mail-Adresse des Benutzers ein, damit er Benachrichtigungen des Systems empfängt.
. Wählen Sie die Benutzerklasse **API**.
. **Speichern** Sie die Einstellungen.

Anschließend aktivieren Sie im Benutzerprofil im Tab **Berechtigung » Tab: SOAP-API** folgende Calls. Diese Calls werden für Händlerbund benötigt:

* **Item » GetItemsImages**
* **Orders » SearchOrders**
* **Webshop » SetLegalInformation**
* **Webshop » SetTermsAndCancellation**
* **Webshop » GetMultiShops**
* **Others » SetContentPage**

== Bewertungstool einrichten

Der Händlerbund bietet für Mitglieder das Bewertungstool **Käufersiegel Kundenbewertung** an. Voraussetzung für die Nutzung ist die Mitgliedschaft beim Händlerbund. Für die link:https://www.kaeufersiegel.de/bewertung/register.php[**Registrierung**] der Kundenbewertung benötigen Sie eine Händlerbund-Mitgliedsnummer. Für die Konfiguration im Käufersiegel-Backend benötigen Sie die Zugangsdaten des zuvor erstellten Benutzerkontos, also den **Benutzernamen** und das **Passwort**, sowie die **URL** des plentymarkets Systems, mit dem Sie das Bewertungstool nutzen möchten.

Weitere Informationen über die Einstellungen im Backend von Händlerbund und die Hinterlegung der Zugangsdaten finden Sie in der link:http://wiki.kaeufersiegel.de/index.php/Plentymarkets[**Anleitung Käufersiegel**].

[IMPORTANT]
.Server-URL
====
Die **Server-URL**, die im Käufersiegel-Backend hinterlegt wird, ist die **URL des plentymarkets Systems**.
====

