= IT-Recht Kanzlei
:lang: de
include::{includedir}/_header.adoc[]
:position: 160

Die link:http://www.it-recht-kanzlei.de/schutzpakete.html[**IT-Recht Kanzlei**, window="_blank"]
bietet Ihnen für die <<omni-channel/online-shop/webshop-einrichten#rechtliche-angaben, **Rechtstexte**>>
Ihres Webshops einen Update-Service, der Ihre rechtlichen Angaben immer aktuell hält.

== Benutzerkonto einrichten

Ihr plentymarkets System wird über die SOAP-Schnittstelle mit der Dienstleistung der IT-Recht Kanzlei verbunden, d.h., Sie benötigen das SOAP-Modul. Für den Zugriff benötigt dieser Dienst einen Benutzer mit Zugriffsrechten auf die API Ihres Systems.

[.instruction]
Neuen Benutzer anlegen:

. Öffnen Sie das Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten**.
. Klicken Sie auf **Neu**. +
→ Das Bearbeitungsfenster **Neuen Benutzer anlegen** wird angezeigt.
. Tragen Sie den **Benutzernamen**, den **realen Namen** und das **Passwort** ein.
. Wiederholen Sie das Passwort.
. Tragen Sie die E-Mail-Adresse des Benutzers ein, damit er Benachrichtigungen des Systems empfängt.
. Wählen Sie die Benutzerklasse **API** oder **Variabel**.
. **Speichern** Sie die Einstellungen.

Folgende Calls müssen für den Benutzer freigegeben werden:

* GetServerTime
* GetPlentyMarketsVersion
* GetMultiShops
* GetTermsAndCancellation
* SetTermsAndCancellation
* GetLegalInformation
* SetLegalInformation

Beachten Sie dazu die Handbuchseite **<<omni-channel/online-shop/extras/it-recht-kanzlei#4, Einführung SOAP-API>>**.

== Rechtstexte automatisch übertragen

Damit Rechtstexte automatisch von der IT-Recht-Kanzlei übertragen werden, müssen Sie in Ihrem Konto bei der IT-Recht Kanzlei eine Datenschnittstelle einrichten. Folgende Informationen benötigt die IT-Recht Kanzlei von Ihnen für die Anbindung an Ihr System:

* Login-Daten, Benutzername und Passwort für den Benutzer
* URL der SOAP API WSDL +
Die URL finden Sie im Menü **Einstellungen » Grundeinstellungen » API » Daten** unter **<<basics/datenaustausch/api-daten#, SOAP WSDL>>**.
