= Arbeiten mit plentymarkets
:lang: de
include::{includedir}/_header.adoc[]
:description: Arbeiten mit plentymarkets: Hier finden Sie die Seiten Benutzer verwalten, allgemeine Funktionen, Benutzerkonto personalisieren und den Schnelleinstieg.
:position: 20

Willkommen im Themenbereich **Arbeiten mit plentymarkets**

In diesem Themenbereich wird beschrieben, wie Sie einen Benutzer einrichten, denn ohne einen Benutzer können Sie nicht mit plentymarkets arbeiten. Sie finden Informationen über Funktionen, die für die Arbeit mit Ihrem plentymarkets System hilfreich sind. So wird z.B. zur Erleichterung der täglichen Arbeit die Einrichtung von Shortcuts etc. unter den Allgemeinen Funktionen erläutert. Außerdem stellen wir Ihnen mit unserem Schnelleinstieg ein Kapitel zur Verfügung, in dem alle Funktionen zusammengetragen sind, die für einen ersten funktionalen Shop notwendig sind.

[.row]
====
[.col-md-6]
.Voraussetzungen schaffen
=====
* **<<basics/erste-schritte/systemvoraussetzungen#, Systemvoraussetzungen  >>**
* **<<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#, Benutzer verwalten  >>**
* **<<basics/arbeiten-mit-plentymarkets/allgemeine-funktionen#, Allgemeine Funktionen nutzen  >>**
* **<<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#, Eigenes Benutzerkonto personalisieren  >>**
=====

[.col-md-6]
.System kennenlernen
=====
* <<basics/erste-schritte/schnelleinstieg#, **Schnelleinstieg vornehmen**  >>
=====
====

'''

link::/[Zurück zur Übersicht]

