= Datenaustausch
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenaustausch, Datenformate, Datenexport, Datenimport, SOAP-API, REST-API, API-Log
:description: Erfahren Sie, welche Datenformate Sie für den Export und Import nutzen, welche Schnittstellen es gibt und wie Sie Protokolle einsehen.
:position: 30
:nav-alias: Übersicht

Dieser Themenbereich befasst sich mit dem Datenaustausch in plentymarkets. Daten können automatisch oder manuell ausgetauscht werden. Für den Austausch von Daten zwischen Ihrem plentymarkets System und externen Systemen stehen Ihnen die link:https://developers.plentymarkets.com/[REST-API^] und Untermenüs im Menü **Datenaustausch** zur Verfügung. Das Plugin **ElasticSync** dient dem manuellen Austausch von Daten. Im API-Log können Sie anhand von <<basics/datenaustausch/api-log#, Log-Einträgen>> den Datenaustausch nachvollziehen.

Nutzen Sie den Datenaustausch außerdem, um systemintern Einstellungen einfach und zeitsparend anzupassen. Einfach Daten zu Artikeln, Kunden, Warenbeständen oder Aufträgen in eine CSV-Datei exportieren, in der Datei anpassen und anschließend importieren.

[.row]
====
[.col-md-4]
.Manueller Datenaustausch
=====
* <<basics/datenaustausch/ElasticSync#, ElasticSync>>
* <<basics/datenaustausch/export-import/daten-exportieren#, Daten über dynamischen Export exportieren>>
* <<basics/datenaustausch/export-import/daten-importieren#, Daten über dynamischen Import importieren>>
* <<basics/datenaustausch/export-import/datenformate#, Datenformate>>
=====

[.col-md-4]
.Schnittstellen
=====

* link:https://developers.plentymarkets.com/[REST-API^]
* *Deprecated*: link:{imagesdir}/basics/assets/SOAP-Version-200-Documentation-2016-07-14.zip[SOAP API]
=====

[.col-md-4]
.Protokolle einsehen
=====
* <<basics/datenaustausch/api-log#, API-Log>>
=====
====
