= DSGVO
:lang: de
include::{includedir}/_header.adoc[]
:description: Laden Sie über diese Seite einen Auszug des Verzeichnisses der Verarbeitungstätigkeiten innerhalb der Software plentymarkets gemäß der DSGVO herunter.
:keywords: DSGVO, dsgvo, Datenschutz, Datenschutzgrundverordnung, Datenschutzgrund-Verordnung, Verfahrensverzeichnis, verarbeitende Tätigkeiten, Verzeichnis, 25. Mai 2018, personenbezogene Daten, Verfahrensdokumentation
:position: 100

Auf dieser Handbuchseite stellen wir unseren Händlern einen Auszug des Verzeichnisses der Verarbeitungstätigkeiten gemäß der DSGVO, deren Übergangsfrist am 25. Mai 2018 endet, zur Verfügung.

== Was ist die DSGVO?

Am 25. Mai 2018 tritt die link:https://www.bfdi.bund.de/SharedDocs/Publikationen/Infobroschueren/INFO6.pdf%3F__blob%3DpublicationFile%26v%3D24[Datenschutzgrundverordnung^] offiziell und europaweit geltend in Kraft und löst somit nationale Regelungen ab.

Die DSGVO gilt für alle Unternehmen, die in der EU tätig sind und personenbezogene Daten wie Namen, Bankdaten und Adressdaten verarbeiten. Daher müssen Unternehmen ihre Prozesse, bei denen personenbezogene Daten verarbeitet werden, DSGVO-konform gestalten und dokumentieren.

== Wichtige Hinweise

Bitte beachten Sie, dass in diesem Verzeichnis lediglich die verarbeitenden Tätigkeiten innerhalb der Software plentymarkets beschrieben sind. Die Auflistung und Beschreibung weiterer verarbeitenden Tätigkeiten, die in Ihrem Unternehmen Anwendung finden (wie z.B. Lohnbuchhaltung oder Verfahren innerhalb einer anderen eingesetzten Software), obliegen dem eigenen Verantwortungsbereich des Händlers.

plentymarkets möchte ausdrücklich darauf hinweisen, dass dieses Verzeichnis keinen Anspruch auf Vollständigkeit und Richtigkeit erhebt und als Ergänzung zur eigenen Verarbeitungsverzeichnisses verwendet werden kann.  

Bitte beachten Sie, dass plentymarkets Systeme erst *ab plentymarkets 7* DSGVO-konform sind. Das plentymarkets 7 Webshop-Plugin *Ceres* wird mit der Einbindung der Checkbox zur Einwilligung der Datenübertragung an Versanddienstleister *ab Version 2.9.0* DSGVO-konform sein.

== Link zum Download

Laden Sie als Ergänzung Ihres eigenen Verzeichnisses der Verarbeitungstätigkeiten das Dokument link:https://github.com/plentymarkets/template-processing-directory/releases[hier^] herunter. Dieses Dokument beschreibt lediglich die verarbeitenden Tätigkeiten innerhalb der Software plentymarkets.  

== DSGVO Best Practices

link:https://knowledge.plentymarkets.com/basics/best-practices-callisto-dsgvo#best-practices-callisto-kontaktformular[Kontaktformular DSGVO-konform in Callisto anpassen^]

link:https://knowledge.plentymarkets.com/basics/best-practices-callisto-dsgvo#best-practices-callisto-newsletter-anmeldung[Newsletter-Anmeldung auf der Startseite anpassen^]
