= Versionswechsel
:lang: de
include::{includedir}/_header.adoc[]
:position: 10

In diesem Handbuchbereich finden Sie wichtige Informationen zu der Migration auf plentymarkets 7 und den nötigen Vorbereitungen sowie eine kurze Übersicht der Änderungen. +
Auf dieser Handbuchseite sind Bereiche aufgeführt, die noch nicht in plentymarkets 7 migriert wurden. Wie bereits angekündigt, stehen Ihnen bei Fragen zur neuen Artikelarchitektur auch unsere Entwickler gern mit Rat und Tat zur Seite. Auch Feedback nehmen sie in unserem Forum gern entgegen.

== Migrationsstand Märkte

Wir haben bereits die relevantesten Märkte in plentymarkets 7 migriert. Selbstverständlich werden alle weiteren Märkte zeitnah in plentymarkets 7 zur Verfügung gestellt. Märkte, die über SOAP an plentymarkets angebunden sind, werden erst nach der Migration des SOAP-Bereichs zur Verfügung stehen. Der folgenden Tabelle entnehmen Sie den aktuellen Status der einzelnen Märkte.

[cols="a,a,a"]
|====
|Migriert |Migration folgt in Kürze |Migration erfolgt durch Online-Marktplatz

|Amazon (außer BMVD) +
Allyouneed +
Cdiscount +
DaWanda +
eBay +
Flubit +
Fruugo +
Gimahhot +
real.de/Hitmeister +
Hood +
Kauflux +
La Redoute +
Mercateo +
OTTO +
Plus.de +
Rakuten +
ricardo +
Shopgate +
Yatego +
Zalando +
Neckermann +
PIXmania +
Preisportale
|
| grosshandel.eu +
Hertie +
Restposten.de +
SumoNet
|====

__Tab. 1: Migrationsstatus der Märkte__

== Migrationshinweis Mention-Schnittstelle

Die Mention-Schnittstelle ist momentan noch nicht auf plentymarkets 7 migriert.

