= Welcome to plentymarkets
:lang: en
include::{includedir}/_header.adoc[]
:position: 10010
:url: videos/basics/welcome-to-plentymarkets
:id: AFRFWQD
:author: team-cloud

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|This introductory video is geared towards new plentymarkets users. It takes you on a quick tour of your system and shows you how to navigate through the menu structure. Once you've mastered these topics, scroll down to see the other videos in this introductory course!
|<<videos/basics/welcome-to-plentymarkets-first-login#video, Logging in for the first time (0:07)>>

<<videos/basics/welcome-to-plentymarkets-menu-structure#video, Exploring the menu structure (0:40)>>

<<videos/basics/welcome-to-plentymarkets-change-user-name-password#video, Changing your user name and password (1:59)>>

<<videos/basics/welcome-to-plentymarkets-plugins-dashboard-support-options#video, Plugins and dashboard and support options (2:44)>>

|===
//end::einleitung[]

video::257090153[vimeo]

// tag::transkript[]
[.collapseBox]
.Transcript
--
Welcome to plentymarkets. Let me show you around and take you on a tour of your new system. All you need to get started is the welcome email that you received from plentymarkets. It contains the information that you'll need to log in. Once you're ready, click on the link in that email to access the plentymarkets login screen. Here, enter the plentymarkets ID, user name and password as they were specified in your email. The connection is encrypted, which makes every login secure.

Welcome to your new plentymarkets system!
It's brimming with features and functions that are just waiting to be explored.
The main navigation bar is up here and you'll notice that drop-down menus appear when you move your mouse over it. For example, you can see information about your contract or any other services that you've booked, you can see an overview of all the orders that your business has received or you can edit text and information about your products.

You'll notice that most of the menus in plentymarkets are composed of search filters on the left which you can use to narrow down the results that are displayed on the right. If you find yourself working with a menu on a regular basis, then just add it to your list of personal favorites. Even though plentymarkets includes tons of functions, you'll never have to worry about getting lost in the complexity. You can find all of your favorite menus saved under the little star here on the right.

Also worth noting is this "System" menu here.
This is where you go to configure the tools and functions in your plentymarkets system. For example, it's where you go to link your eBay account with plentymarkets or to create user accounts for any other staff members who also need access to your plentymarkets system. But there's also another nifty way to access your user account.
Just click on the name of the user who you're currently logged in with and voilà! Here you are!

You'll notice that right now you're logged into plentymarkets with the account data that we sent you via email. This demo user is great for the first time you log in and start learning your way around. But it's not very safe either. What if someone hacks your emails? They'd have access to your plentymarkets system and sensitive business data. The smart thing to do is change this automatically generated login data to your own login data.
So in this menu here, just change the user name, actual name and password to values you've thought up yourself.

The next time you log in, you'll be able to use your own, personalised access data, instead of the randomly generated values that were sent in the welcome email.

Did you know that you can add even more functions and tools to your system?
It's true! Just head on over to the plentyMarketplace and browse through the wide range of plugins that you can add on to your plentymarkets system.

Did you notice this dashboard tab when you logged in? You can think of the dashboard as the home screen in plentymarkets. But the best thing about it? You can customise which information is included on the page, so you always see whichever facts and figures are most important to your business right when you log in.

Have fun browsing through the menus and finding your way around plentymarkets. Don't worry if you run into a question or two. We're always happy to help! Just check out our support materials and get the answers you're looking for! Our introductory video course is a great place to start. It's targeted towards new plentymarkets users and helps you get your bearings.

So what are you waiting for? Take your first steps with plentymarkets and discover the wide range of functions and tools that will take your business to the next level!
--
//end::transkript[]
