Items have to be available for Amazon country platforms. This is done in the *Availability* tab of an item within the *Item » Edit item » [Open item] » [Open variation]* menu.

[TIP]
.Use group function or batch processing
====
You can edit the availability of several variations at once by using either the <<item/managing-items#330, variation group function>> or <<item/managing-items#330, batch processing>>.
====

[.instruction]
Activating the variation availability for an Amazon country platform:

. Go to *Item » Edit item » [Open item] » [Open variation]*. +
→ The tab *Settings* of the variation is shown. +
*_Tip:_* To sell all variations of an item on the Amazon platform, carry out the settings for the item’s main variation. This activates the availability of all variations of the item.
. In the *Availability* area, activate the option *Active*.
. Click on the *Availability* tab.
. In the *Markets* area, click in the selection field. +
→ A list of all available markets is displayed.
. Select the Amazon country platform(s) for which the variation should be available.
. Activate the option *Web API*.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The market is added.
. *Save* (icon:save[role="green"]) the settings.
. Click on the *Multi-Channel* tab.
. Carry out the settings in the *Amazon* area. Pay attention to the explanations given in <<#item-availability-amazon>>.
. *Save* (icon:save[role="green"]) the settings.

[[item-availability-amazon]]
.Activating the variation availability for Amazon
//tag::table[]
[cols="1,3a"]
|====
| Setting | Explanation

| *Product type*
|Select the <<data/export-import/data-formats/item#50, Amazon product type>>.

| *FBA Fulfillment*
| Select one of the Amazon marketplaces *AMAZON_EU* (Europe), *AMAZON_FE* (Far East), *AMAZON_NA* (North America).

| *Amazon FBA*
| Activate if the FBA function should be used and FBA stock and Multi-Channel stock should be imported. +
If you activate the *Amazon FBA* option, then the FBA stock of this item can be imported into plentymarkets and Amazon Multi-Channel orders that are shipped with FBA can be booked.
|====
//end::table[]

[IMPORTANT]
.Variation availability for MFN and FBA
====
In order to set up variations for MFN as well as FBA, select the Amazon country platform *Amazon country* and the platform *Amazon country FBA*.
====
