The *Amazon* payment method is used for orders that were placed on Amazon and transferred to your plentymarkets system. Do not confuse this with *Amazon Pay*, which is a way for customers to use the Amazon checkout process when placing orders in your plentyShop.

Activate the <<payment/managing-payment-methods#, payment method>> *Amazon* as described below.

[.instruction]
Activating the Amazon payment method:

. Go to *Setup » Orders » Payment » Methods*.
. Activate the option *Also show inactive*.
. Click on the folder *International > Amazon*. +
→ The settings for the Amazon payment method are displayed.
. Place a check mark next to the option *Active*.
. Carry out additional settings as desired.
. *Save* (icon:save[role="green"]) the settings.

[TIP]
.Permitting the payment method in customer classes
====
Go to *Setup » CRM » Classes* to activate or deactivate *permitted payment methods*. +
For further information, refer to the <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>> page of the manual.
====

For further information, refer to the <<payment/managing-payment-methods#, Managing payment methods>> page.
