[#tag-magagement]
== Tags für {area} verwalten

Mit Tags kannst du Datensätze kennzeichnen. {tag-purpose}

[.collapseBox]
.Was sind Tags und in welchen plentymarkets Bereichen kann ich Tags verwenden?
--
Tags sind Schlagworte, mit denen du Datensätze in plentymarkets hervorheben kannst.
Tags sind vielseitig einsetzbar.

Beispielsweise helfen dir Tags:

* den Überblick über große Datenmengen im Backend zu behalten.
Das heißt, du markierst spezifische Kunden, Varianten, Kategorien, Nachrichten usw.
* Produkte im Frontend hervorzuheben.
Das heißt, du versiehst spezifische Varianten mit Schlagworten.

Im Wesentlichen besteht der Ablauf aus nur zwei Schritten.
Erstens, <<willkommen/allgemeine-funktionen/tags#100, erstelle die Tags>>.
Zweitens, <<willkommen/allgemeine-funktionen/tags#400, verknüpfe die Tags>> mit den passenden Datensätzen.

Nachdem du deine Tags erstellt hast, kannst du sie mit Datensätzen verknüpfen. Du kannst deine Tags mit Datensätzen in den folgenden Bereichen von plentymarkets nutzen:

[cols="1,3"]
|====
| Tag-Bereich | Wie werden solche Tags verknüpft?

| Board
| <<willkommen/system-personalisieren#380, Tags werden manuell mit Aufgabenkarten auf Boards verknüpft>>.

| Kategorie
| <<artikel/einstellungen/kategorien#700, Tags werden manuell mit Kategorien im Backend verknüpft>>.

| Ticket
| <<crm/ticketsystem-nutzen#1800, Tags werden manuell mit Tickets im Ticketsystem verknüpft>>.

| Kontakt
| <<crm/kontakte-verwalten#300, Tags werden manuell mit Kontakten verknüpft>>.

| Variante
a| * <<artikel/artikel-verwalten#268, Tags können manuell mit Varianten verknüpft werden>>.
* <<daten/daten-importieren/sync-typen/elasticSync-artikel#2290, Tag-Verknüpfungen können importiert werden>>.

| Nachrichten
| <<crm/messenger#nachricht-erstellen, Tags werden manuell mit Nachrichten im Messenger verknüpft>>.

| Nachricht (kostenpflichtig)
| <<crm/messenger#nachricht-erstellen, Tags werden manuell mit kostenpflichtigen Nachrichten im Messenger verknüpft>>.
|====

--

[#50]
=== Voraussetzung: Benutzerrechte für Tags

:rights-purpose: sinnvoll mit Tags arbeiten können
:right-one: *Einrichtung > Tag > Aktualisieren*
:right-two: *Einrichtung > Tag > Anzeigen*
:right-three: *Einrichtung > Tag > Erstellen*
:right-four: *Einrichtung > Tag > Löschen*
:right-five: *Einrichtung > Tag > Tag-Verknüpfung > Aktualisieren*
:right-six: *Einrichtung > Tag > Tag-Verknüpfung > Anzeigen*
:right-seven: *Einrichtung > Tag > Tag-Verknüpfung > Erstellen*
:right-eight: *Einrichtung > Tag > Tag-Verknüpfung > Löschen*

include::../../_includes/textblocks/instructions/rechte.adoc[]

[#tag-creation]
=== Tag erstellen

//tag::neue-tags-erstellen[]
Erstelle zunächst die Tags, die du für deine Produkte, Kunden, Aufträge, Tickets usw. verwenden möchtest.

[.instruction]
Tag erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Tags*.
. Klicke auf *Neues Tag erstellen* (icon:plus[role="green"]). +
→ Rechts wird ein Fenster geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-tag-settings>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Tag wird erstellt und der Liste hinzugefügt. +
→ Du kannst die Tag-Einstellungen jederzeit anpassen. +
*_Tipp:_* Verwende die Suche, um Tags zu finden. Mit den optionalen Filtern grenzt du das Suchergebnis ein. Filtere nach dem *Bereich*, der *Sprache* oder dem *Namen* des Tags. Du kannst nur nach Namen in der Hauptsprache deines plentymarkets Systems filtern.

[.collapseBox]
.
--
[[table-tag-settings]]
.Tag erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *ID*
| Die Tag-ID wird automatisch vergeben und ist nicht änderbar.
Sie dient zur eindeutigen Kennzeichnung deiner Tags.

*_Anwendungsfall_*: Tag-Verknüpfungen können importiert werden.
Während du also z.B. Artikel- und Variantendaten importierst, kannst du die passenden Tags auch direkt verknüpfen.
Dies geschieht z.B. durch Angabe der Tag-ID.

| *Name DE* +
[red]#(Pflichtfeld)#
| Gib einen Namen für das Tag ein.
Der Name ist das Schlagwort, das den Datensatz hervorhebt.

*_Tipp_*: Der Name darf Leerzeichen enthalten. Der Name kann also auch aus mehreren Wörtern bestehen.

| *Farbe*
a| Welche Hintergrundfarbe soll der Tag-Text haben?
Es gibt drei Möglichkeiten, die Farbe zu wählen:

* Gib die Farbe als Hexadezimalwert ein.
* Gib die englische Bezeichnung einer der 16 Grundfarben ein (black, red, silver, white etc.) +
* Klicke auf das Quadrat rechts und klicke in das Farbspektrum.

|[#intable-bereich]*Bereich*
a| Welche Arten von Datensätzen wirst du mit diesem Tag verknüpfen?
Wähle alle zutreffenden Bereiche (icon:check-square[role="blue"]).

[cols="1,3"]
!===
! Bereich ! Anwendungsbeispiel

! *Board*
! Willst du bestimmte Aufgabenkarten auf Boards markieren? +
*_Beispiel:_* Gib an, dass manche Aufgaben eine hohe oder niedrige Priorität haben.

! *Kategorie*
! Willst du bestimmte Kategorien im Backend markieren? +
*_Beispiel:_* Gib an, dass eine Kategorie nur für saisonale Angebote verwendet werden soll.

*_Hinweis_*: Kategorie-Tags sind für Kund:innen im Webshop _nicht sichtbar_.

! *Ticket*
! Willst du bestimmte Tickets im Ticketsystem markieren? +
*_Beispiel:_* Gib an, dass sich das Ticket auf einen bestimmten Verkaufskanal bezieht, zum Beispiel Amazon oder eBay.

! *Kontakt*
! Willst du bestimmte Kontakte markieren? +
*_Beispiel:_* Gib die vom Kunden bevorzugte Kommunikationsmethode an.

! *Variante*
! Willst du bestimmte Varianten markieren? +
*_Beispiel:_* Wenn du z.B. Leitern verkaufst, kannst du angeben, dass einige Leitern TÜV-zertifiziert sind.

*_Hinweis_*: Varianten-Tags können für Kunden im Webshop _sichtbar_ gemacht werden.
<<willkommen/allgemeine-funktionen/tags#intable-mandant, Wähle dazu den entsprechenden Mandanten>> weiter unten.

! *Auftrag*
! Tags können derzeit für diesen Bereich erstellt werden, aber noch nicht mit Aufträgen verknüpft werden.
Diese Option ist daher zur Zeit ohne Funktion.

! *Nachrichten*
! Willst du bestimmte Nachrichten im Messenger markieren? +
*_Beispiel:_* Gib an, dass sich die Nachricht auf einen bestimmten Vertriebskanal bezieht, zum Beispiel Amazon oder eBay.

! *Nachrichten (kostenpflichtig)*
! Schreibst du manchmal kostenpflichtige Nachrichten im Messenger?
Sollen also die Minuten, die beim Schreiben der Nachricht verstrichen sind, in Rechnung gestellt werden?

Beim Schreiben einer kostenpflichtigen Nachricht musst du mindestens ein Tag dieses Bereichs wählen.
Andernfalls kann die Nachricht nicht erstellt werden.
!===

|[#intable-mandant]*Mandant* +
(ab Ceres 5.0 wirksam)
| In welchen Webshops soll das Tag für Kund:innen sichtbar sein?
Wähle alle zutreffenden Webshops (icon:check-square[role="blue"]).

*_Hinweis_*: Diese Option wird nur angezeigt, wenn du oben <<willkommen/allgemeine-funktionen/tags#intable-bereich, den Bereich Variante gewählt>> hast.

| *Name EN* +
*Name FR* +
*Name IT* +
usw.
| Übersetze den Tag-Namen in weitere Sprachen.

*_Anwendungsbeispiel_*: Varianten-Tags können für Kund:innen im Webshop sichtbar gemacht werden.
Wenn dein Webshop in mehreren Sprachen verfügbar ist, sollten auch die Tag-Namen in diesen Sprachen erscheinen.
|====
--
//end::neue-tags-erstellen[]

////
[#tag-links]
=== Tag mit {area} verknüpfen
