= Editing categories
:lang: en
include::{includedir}/_header.adoc[]
:keywords: categories, item, content
:position: 10

**plentymarkets » Item » Categories**

== Setting the category levels

First decide how many category levels should be displayed in your online store. For example, if you enter 4, then no categories can be created on the 5th level.

[.instruction]
Setting the category levels:

. Go to **Settings » Client (store) » Standard » Categories » Basic settings**.
. Select the maximum number of levels in the category navigation.
. **Save** the setting.

== Creating a category

Create a category whenever you want to add a new item category or a page with information to your online store. You must have created a main category before you can create subcategories underneath it. Some categories are already in your system by default. One of these default categories is the category **Content**.

[IMPORTANT]
.Default category "Content"
====
You cannot change the name or the URL name of the category **Content**. You can change settings that do not relate to the name, e.g. the position. You can not create additional categories called **Content**.
====

Learn more about creating categories in the following video tutorial:

[.linkBox]
link:https://www.plentymarkets.co.uk/a-3409/[Creating categories, window="_blank"]

[TIP]
.Tip: Planning a structure
====
Set up a logical category structure before you begin creating categories. +
Before you begin creating item categories, consider which products are included in your portfolio and divide these products into groups of categories and subcategories. +
For example, you could use Women's clothing and Men's clothing as parent categories and then use Shoes as a subcategory of each one. Or you could set up categories the other way around. You could use Shoes as a parent category and have it include the subcategories Women's and Men's. Set up the categories that best match your portfolio.
====

=== Creating a main category

The following section explains how to create new main categories.

[.instruction]
Creating a main category:

. Go to **Item » Categories**.
. Click on the **New category** button in the lower left corner. +
→ The **Create new category** window will open.
. Enter a **name** for the category.
. Select **Main category** as the category level.
. Click on **Create** to create the category. +
→ The category will be created and displayed in the directory tree on the left.

[TIP]
.Category type
====
New categories are assigned the category type **Item** by default (table 2).
====

=== Creating a subcategory

There are two different ways to create subcategories.

[.instruction]
Creating a subcategory using the button:

. Go to **Item » Categories**.
. Click on the **New category** button in the lower left corner. +
→ The **Create new category** window will open.
. Enter a **name** for the category.
. Select **Subcategory** as the category level.
. Select which main category this new subcategory should be included in.
. Click on **Create** to create the category. +
→ The category will be created and displayed as a subcategory in the directory tree on the left.
. Click on a main category to display its subcategories.

[.instruction]
Creating a new subcategory with the context menu:

. Go to **Item » Categories**.
. Open the category to which you want to add a subcategory.
. Use your mouse to right-click on a category. +
→ The context menu will open.
. Click on **Create subcategory**. +
→ The **Create new subcategory** window will open.
. Enter a **name** for the subcategory.
. Click on **Create** to create the category. +
→ The category will be created and displayed as a subcategory in the directory tree on the left.
. Click on a main category to display its subcategories.

If you want to create a subcategory on the 3rd or 4th level, click on the categories until you have reached the category that should include the new subcategory.

[IMPORTANT]
.Activate categories
====
You have to activate a category in order for it to be visible in the online store. Go to **Settings » Client (store) » Standard » Categories » Activate** to activate the categories.
====

== Editing a category

Categories that were already created are found in the directory tree on the left. They can now be edited. Click on a category to open it. Or right-click on a category to open its context menu. The context menu gives you quick access to certain functions, e.g. to edit, move, copy or delete a category. You can also create a new item or a subcategory.

[IMPORTANT]
.Copying a category
====
The **Copy category** function allows you to create the same subcategory in several different parent categories. For example, this is useful if you want to have categories for women's, men's and children's clothing, and all three categories should include pants as a subcategory. Copy the category with all of its settings and then make changes to the name and the description as needed.
====

The editing window is divided into 5 tabs. These tabs are: **Settings**, **Description 1**, **Description 2**, **Documents** and **Note**. A toolbar is located above the tabs. This toolbar is described in table 1.

[cols="a,a"]
|====
|Settings |Explanation

|**Category path**
|Click on the link to open parent categories.

|**Save**
|Saves the settings or any changes made to a category page.

|**ID**
|Will be assigned automatically and displayed here.

|**Preview**
|Opens a preview of the category.

|**Inline edit preview**
|Opens a preview that can also be edited.

|**Image gallery**
|Opens the **<<omni-channel/online-store/cms/image-gallery#, image gallery  >>** in a new tab. Images can be uploaded here. You can then copy an image's URL and link it in the category page using the editor.

|**Template variables and template functions**
|Opens the <<omni-channel/online-store/cms-syntax/basics/template-variables#, **template variables**  >> and <<omni-channel/online-store/cms-syntax/basics/template-functions#, **template functions**  >> sorted by system area. These can be copied and inserted into the page. +
Examples for template functions: +
**{% Link(xxx) %}** = links to another category page (xxx = the page's ID) +
**{% Link_Help() %}** = links to the help page +
**{% Link_ShippingCosts() %}** = links to information about shipping costs +
__**Important**__: These functions can not be used in newsletters or item descriptions. You have to put the absolute URL in these types of documents.

|**Multilingualism**
|Opens a bilingual editor. You can select which two languages should be displayed.

|**Apply category settings**
|Select any of the category's options that you want to apply to another category with the same category ID of one or more clients or one or more languages. This makes it easier and quicker to edit categories for several clients and languages at once.

|**Link**
|The category's template function. This always includes the category ID so that it can be uniquely identified.

|**Timestamp**
|Displays the time when changes were last made and the person who made these changes.
|====

__Table 1: icons of the category's toolbar__

=== Tab: Settings

The **Settings** tab is automatically opened when a category is opened.

[cols="a,a"]
|====
|Setting |Explanation

|**Type**
|Select **Item**, **Content** or **Container**. +
In the directory tree, categories of the type **Item** are blue. Categories of the type **Content** are yellow and categories of the type **Container** are red.

|**Name**
|Enter a name for the category. +
You can re-use category names as long as they are used in different categories or on different levels. Within one category, however, the names may only be used once per level. This makes it possible to save different meta descriptions etc. for categories with the same name.

|**Tags**
|Select the tags that match the category. Suggestions are automatically displayed while you type. Tags show that a category relates to a specific topic. Go to <<basics/working-with-plentymarkets/tags#, **Settings » Basic settings » Tags**  >> to create tags.

|**URL name**
|Enter a name that should be used for the URL. +
The name will automatically be used as the URL name when the category is crated. However, the URL name can still be changed here. The automatic URL will not be indexed at first because a client is not selected when the category is created. +
You can re-use URL names as long as they are used in different categories or on different levels. Within one category, however, the URL names may only be used once per level. +
__**Important:**__ Only use **ASCII code**. This is because the URL name may not contain special characters. The following character strings may not be used as prefixes to URL names: a-, b-, c-, f-, fa-, p-, t-. These prefixes will be removed automatically if entered. For instance, a-class will be changed to class automatically. However, the URL name aclass can be used for a category named A-class.

|**URL**
|The category URL will be displayed. +
It is automatically created and entered. It includes the complete path, i.e. the domain, the category levels and the URL name.

|**Canonical**
|Enter the URL of the category that contains the same content. This will avoid **link::/[duplicate content]**.

|**Short description**
|Enter a short description of the category. Template variables are used to insert the short description into the store's design.

|**Position**
|Enter a number to specify which order the categories and subcategories should be displayed in on the same level. Go to **<<omni-channel/online-store/standard/item-layouts/basic-settings#, Settings » Client (store) » Standard » Item layouts » Basic settings  >>** to specify the pages' sorting order. Pages are sorted in ascending position order by default. +
**__Tip:__** Count by tens when creating position numbers. This will allow you to easily add new categories in between.

|**Client (store)**
|Select one, several or all of the clients. The category will then be available in these clients. +
If a client is activated for a subcategory but it was not yet activated for the category above it, then the parent category will automatically be activated as well. If other clients are already activated for parent categories, then the new client will be activated as well. Previously selected clients continue to be activated. +
**Apply visibility to subcategories** +
This option will only be displayed if subcategories exist. +
Place a check mark to apply the category's client visibility to all of its subcategories. This function is only activated until the next time you save the category. This means that you have to place the check mark again every time you want to apply a category's visibility to its subcategories. +
If a visibility is removed (i.e. a check mark is removed from any of the clients and the category is saved), then this will be applied to the subcategories even if the function is not activated. +
If a visibility is added, then this visibility will also automatically be set for any parent categories.

|**Meta title**
|Enter a name. This name will be displayed as the title of a tab in the web browser and as a search result in search engines. +
If you leave this field blank, the Name will be used as the title. +
Pay attention to the length of the title. Short titles are better for tabs. Longer titles will be cut off after a certain length. (Standard value up to 50 characters)

|**Meta description**
|Enter a meta description. This will be analyzed by search engines. As such, it is especially important for the homepage. The meta description should contain the most important content in one sentence. (Standard value up to 140 characters)

|**Meta keywords**
|Enter concrete keywords that users would likely enter into search engines.

|**Sitemap**
|Choose between **Display** and **Do not display**. +
**Display** = Category will be included in the sitemap. +
**Do not display** = Category will not be included in the sitemap.

|**Robots**
|Choose between **all**, **index**, **nofollow**, **noindex** and **nofollow, noindex**. Values from the meta element Robots are analyzed by Web crawlers. These values tell the crawler what it should do with this page and with the links on this page. +
**all** = Include this category in the search engine index and follow the links on the page. +
**index** = Include in the search engine index. +
**nofollow** = Do not follow the links on the page. +
**noindex** = Do not include in the search engine index. +
**nofollow, noindex** = Do not follow the links and do not include the category in the search engine index.

|**Template page**
|Select a template. The template that is selected here provides the framework for the category. This option is not available for categories of the type **Container**.

|**Template list**
|Select a template. The template determines what the category overview will look like for the current category. The option is only available for **categories of the type item**.

|**Template product**
|Select a template. The template determines the appearance of the single item design for this category. The option is only available for **categories of the type item**.

|**Full text search**
|Choose between **Yes** and **No**. +
**Yes** = Complete text will be searched. +
**No** = Text will not be completely searched.

|**in link list**
|Choose between **Display** and **Do not display**. +
**Display** = Category will be displayed in the store's navigation. +
**Do not display** = Category will not be displayed in the store's navigation.

|**Visible**
|Choose between **Public** and **After login**. +
**Public** = Category is visible to all visitors of the online store. +
**After login** = Category and all of its subcategories are only visible to visitors of the online store that have logged in. Visitors that are not logged in will be redirected to the login page.

|**Elmar category**
|Select an Elmar category.

|**Translate template variables and template functions**
|Choose between **Yes**, **No** and **Template variables and template functions for links only**. +
**Yes** = All template variables and template functions will be translated. +
**Template variables and template functions for links only** = Only template variables and template functions for links will be translated. +
**No** = No template variables and template functions will be translated.
|====

__Table 2: explanations for the **Settings** tab__

=== Tabs: Description 1 and 2

Enter and format text in the tabs **Description 1** and **2**. Use <<omni-channel/online-store/cms-syntax/basics/template-variables#, **template variables**  >> and <<omni-channel/online-store/cms-syntax/basics/template-functions#, **template functions**  >> to insert this description into your store's web design or other areas. **Description 1** and **2** allow you to write two texts per category and display them in different areas within a website. For example, you could display **Description 1** above and **Description 2** below an overview of items.

In the drop-down menu above the entry field to the right, you can select which editor you want to use for editing the template. You can use the **<<omni-channel/online-store/cms/web-design/tools/editor#, Editor  >>**, the HTML editor **Text field** or the <<omni-channel/online-store/cms/web-design/tools/syntax-editor#, **Syntax editor**  >>. Categories of the type **Container** can only be edited with the HTML editor **Text field** and the **Syntax editor**.

[#10]
=== Tab: Documents

Use the **Documents** tab to upload documents. All of the files that belong to the category can be saved here. This makes files easier to find.

You can upload the data formats JPEG, PNG, GIF, TIFF, PDF, DOC, ODC, OTH, XLS, XML, HTML, HTM, CSS, JavaScript, ZIP, JSON and GZIP.

[NOTE]
.Uploading documents
====
Click on the **Upload file** button or simply add documents with the drag and drop function.
====

You can define **two** category images for categories of the type Item. You can upload other documents and images as well. This allows you to regularly change the category image without having to delete the old image. Proceed as described below to define category images.

[.instruction]
Defining category images for a category of the type item:

. Open the **category**.
. Click on the **Documents** tab.
. Point your cursor over the desired image.
. Select the image with a **check mark**.
. Click on **Image 1**.
. **Save** the settings. +
→ The image will be outlined in red and designated with the number **1**.

Proceed the same way for image 2. Click on the **Image 2** button in step 5. Deselect a category image by placing a check mark for the image and clicking on the **Image 1** or **Image 2** button a second time.

You can click on the buttons that are grayed out in the toolbar once you have selected one or more images with a check mark. By selecting images with check marks, you can see a preview, download or delete several images at the same time.

[TIP]
.Displaying category images in the online store
====
Only category image 1 is displayed in the online store by default. An <<omni-channel/online-store/cms-syntax/basics/if#, **if-query**  >> was inserted to the **ItemViewCategoriesList** template with the template variable <<omni-channel/online-store/cms-syntax/web-design/navigation#3, **$CurrentCategoryImageUrl** >>. You have to insert a second if-query to the template in order for category image 2 to be displayed.
====

=== Tab: Note

Save helpful information about a category in the **Note** tab. For example, you can specify which sources your information comes from or let colleagues know that changes should not be made to specific paragraphs. The information saved in this tab is only visible in plentymarkets and will not be displayed in the online store. Notes cannot be deleted.

=== Filtering categories

Categories can be filtered by client, language and type. The filters are located above the directory tree. The font indicates whether a category is available in the selected combination. Categories that are displayed in normal font are available in the selected combination. Categories displayed in italic font are not available in the selected filter combination of client, language and type.

=== Searching for a category

The search function helps you find categories quickly. Enter the name of the category that you are searching for into the text field. Search results will appear while you are entering the name.

== Moving a category

Categories are displayed in the selected structure under **Item » Categories**. The category structure and category names form the basis for the navigation menu displayed in the online store. On the one hand, the structure is determined by the main and subcategories and by the relationship of the categories one another. These are the so-called levels. On the other hand, the structure is determined by the position numbers. Use the category positions to specify the order within a category level. Use the **Move category** function to move a category to a different level after it was created.

[.instruction]
Moving a category to the main category level:

. Go to **Item » Categories**.
. Point your cursor over a category.
. Click on the triangle to the right of a category. +
→ A **context menu** will open.
. Click on **Move category**. +
→ The **Move category** window will open.
. Select **Main category**.
. Click on **Move**. +
→ The category will be displayed in the top level of the directory tree.
. If necessary, change the category's position to sort it correctly.

[.instruction]
Moving a category to a subcategory level:

. Go to **Item » Categories**.
. Point your cursor over a category.
. Click on the triangle to the right of a category. +
→ A **context menu** will open.
. Click on **Move category**. +
→ The **Move category** window will open.
. Select **Subcategory**.
. Select which category it should be sorted under.
. Click on **Move**. +
→ The category will be displayed under the selected category in the directory tree.
. If necessary, change the category's position to sort it correctly.

== Activating several categories of a client (store)

You can activate and/or deactivate categories of a client (store) centrally in the **Settings » Client (store) » Standard » Categories » Activate** menu.

[.instruction]
Activating several categories of a client (store):

. Go to **Settings » Client (store) » Standard » Categories » Activate**.
. Check the category that you want to activate. +
**__Tip:__** Click on **Select all** to place check marks next to all of the categories. Click on **Deselect all** to remove the check marks from all of the selected categories.
. **Save** the settings.
. Check whether categories and items are displayed correctly in the online store. +
**__Tip:__** It might take some time until an activated category is visible in the online store. If problems occur, check the settings and reload the page of your store.

