= Editing categories of the type Item
:lang: en
include::{includedir}/_header.adoc[]
:position: 20

Create categories of the type Item to organize your items in the online store. Consider which products are included in your portfolio and divide these products into groups of categories and subcategories. For example, you could use **Women's clothing** and **Men's clothing** as main categories and then use **Shoes** as a subcategory of each one. Or you could set up categories the other way around. You could use **Shoes** as a main category and have it include the subcategories **Women's** and **Men's**. Set up the categories that best match your portfolio. +
For further information about creating **main categories** and **subcategories**, refer to the **<<item/categories/editing-categories#, Editing categories  >>** page of the manual. This page also includes additional settings that apply to other category types, i.e. to Item, Content and Container.

[TIP]
.Category type Item
====
Categories of the type Item are easily recognized by their blue folder and page symbols.
====

== Editing categories of the type Item

The following configuration only focuses on those settings that are absolutely necessary for categories of the type **Item** and that differ from the settings for categories of the type **Content**. For further information about the remaining settings, refer to table 2 on the **<<item/categories/editing-categories#, Editing categories  >>** page of the manual.

[.instruction]
Editing categories of the type Item:

. Open the category in the directory tree on the left.
. Select **Item** as the type. +
→ New categories will automatically be assigned to the type **Item** (default).
. Select a design for the **Template list**.
. Select a design for the **Template product**.
. Select an **Elmar category**.
. Click on the **save icon** to save the settings.

Once you have created the category, you will still have to link items to it. This is done in the item's **Categories** tab.

[IMPORTANT]
.Changing the category type
====
If a category is already linked to items and you change the category type from **Item** to **Content**, then the links will not automatically be deleted. However, the category will no longer be displayed for the item.
====

Learn more about linking items to categories in the following video tutorial:

video::122644529[vimeo]
