= beta: Zahlungseingänge bearbeiten
:lang: de
include::{includedir}/_header.adoc[]
:description: Payments in plentymarkets: Erfahre alles über das Bearbeiten von Zahlungen.
:position: 25
:url: payment/beta-zahlungen-verwalten
:id: VBZTVJ8
:keywords: Zahlung, Zahlungen, Zahlungsverkehr, Zahlungseingang, Zahlungseingänge, Payment, automatische Zuordnung, Zahlungszuordnung, Properties, Zahlungsdaten, Auftragszuordnung, Zahlung zuordnen, Zahlungsübersicht, Zahlungsinformationen, Zahlung aufteilen, Zahlung teilen, Teilzahlung
:author: team-order-payment

Diese Seite beschreibt das Verwalten von Zahlungen mit der neuen Benutzeroberfläche. Diese Funktionen sind derzeit in _beta_, die alte Benutzeroberfläche steht parallel aber ebenfalls zur Verfügung. Beachte, dass die Informationen in den Kapiteln <<payment/zahlungen-verwalten#10, Grundeinstellungen für Zahlungseingänge vornehmen>> sowie <<payment/zahlungen-verwalten#20, Zahlungen buchen>> auch für das Arbeiten mit der neuen Benutzeroberfläche gelten.

[#10]
== Neue Zahlungen im System

Nach der Buchung in plentymarkets werden die Zahlungen Aufträgen über eine unscharfe Suche automatisch zugeordnet. Wenn die Zuordnung fehlschlägt, können Buchungen Aufträgen manuell zugeordnet werden. Zahlungen kann man im Menü *Aufträge » Zahlungsverkehr* bearbeiten. Unzugeordnete Zahlungen sind mit einem *grünen Pfeil* (icon:payment_assign[set=plenty,role="green"]) gekennzeichnet.
In der Übersicht werden dir Zahlungen in deiner gewählten <<payment/waehrungen#30, Systemwährung>> angezeigt. Wurde die Zahlung in einer Fremdwährung getätigt, wird dir dieser Betrag hinter der Systemwährung in Klammern ebenfalls angezeigt.

[TIP]
.Ereignisaktionen für Zahlungseingänge einrichten
====
Der Zahlungseingang als Ereignis spielt in der Auftragsbearbeitung eine wichtige Rolle, da der Versand häufig erst nach Zahlungseingang erfolgt. In plentymarkets wechselt der Status der meisten Aufträge mit dem Eintreffen der Zahlung von *Status [3] - Warten auf Zahlung* in *Status [5] - Freigabe Versand*. Richte <<automatisierung/ereignisaktionen#, Ereignisaktionen>> ein, um die Auftragsbearbeitung zu automatisieren und den Versand nach Zahlungseingang auszulösen.
====

[#20]
== Zahlungen suchen

Zahlungen suchst du in der Übersichtsansicht im Menü *Aufträge » Zahlungsverkehr*. Diese Tabelle ist anpassbar. Das bedeutet, dass du selbst entscheiden kannst, welche Informationen dir in den Tabellenspalten angezeigt werden. Gehe dafür folgendermaßen vor:

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (icon:cog[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle aus, welche Spalten angezeigt werden sollen.
. Verschiebe (icon:drag_sort_handle[set=plenty]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

Für die Suche (icon:filter[]) kannst du verschiedene Filter setzen und sie kombinieren, um beispielsweise nach unzugeordneten Zahlungen der letzten Woche zu suchen. Setze die Filter nach Bedarf und führe die Suche aus.

[.instruction]
Zahlungen suchen:

. Öffne das Menü *Aufträge » Zahlungsverkehr*.
. Öffne die Suche (icon:filter[]).
. Wähle die *Filter* und beachte dazu die Erläuterungen in <<tabelle-zahlungen-suchen>>.
. Klicke auf *Suchen*, um die Suche auszuführen.

[[tabelle-zahlungen-suchen]]
.Zahlungen suchen
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Auftrags-ID*
|Suche anhand von Auftrags-IDs nach Aufträgen, denen eine Zahlung zugeordnet ist.

|*Transaktions-ID*
|Die Transaktions-ID wird vom Zahlungsanbieter vergeben, damit sich die Zahlung dem Anbieter zuordnen lässt. Gib eine Transaktions-ID ein, um nach einer Zahlung mit dieser Transaktions-ID zu suchen.

|*Transaktionscode*
|Der Transaktionscode beschreibt die Transaktion selbst. Gib einen Transaktionscode ein, um nach einer Zahlung mit diesem Code zu suchen.

|*Referenz-ID*
|Eine Referenz-ID verknüpft Zahlungen, z.B. eine Zahlung und eine Erstattung, miteinander. Gib eine Referenz-ID ein, um nach einer Zahlung mit dieser Referenz-ID zu suchen.

|*Zahlungs-ID*
|Gib eine Zahlungs-ID ein, um nach der Zahlung mit dieser ID zu suchen.

|*Zahlungsart*
|Gib eine bestimmte Zahlungsart ein, um nach Zahlungen zu suchen, die mit dieser Zahlungsart getätigt wurden.

|*Verwendungszweck*
|Gib entweder den ganzen Verwendungszweck oder einen Teil des Verwendungszwecks ein, um nach Zahlungen mit diesem Zweck zu suchen.

|*Absender der Zahlung*
|Gib den Namen der Person ein, die die Zahlung getätigt hat, um nach Zahlungen von dieser Person zu suchen.

|*H/S*
|Wähle zwischen *H* (Haben) oder *S* (Soll). +
*Haben* = Alle Zahlungseingänge mit positivem Wert werden angezeigt. +
*Soll* = Alle Zahlungseingänge mit negativem Wert werden angezeigt.

|*Wert*
|Wähle einen Operator und gib eine Summe ein. +
*_Beispiel_*: Wähle *Größer als oder gleich* und gib 300 als *Wert* ein, um alle Zahlungen mit einem Zahlbetrag von 300 oder mehr anzuzeigen.

|*Zuordnung*
|Du kannst zwischen *Zugeordnet* oder *Unzugeordnet* wählen. +
*Zugeordnet* = Zeigt dir nur Zahlungen, die bereits einem Auftrag zugeordnet wurden. +
*Unzugeordnet* = Zeigt dir nur Zahlungen, die keinem Auftrag zugeordnet wurden.

|*Status*
|Wähle einen Status aus, um nach Zahlungen mit diesem Status zu suchen.

|*Transaktionstyp*
|Wähle einen Transaktionstyp aus, um nach Zahlungen mit diesem Transaktionstyp zu suchen.

|*Währung*
|Wähle eine Währung aus, um nach Zahlungen in dieser Währung zu suchen.

|*Datumstyp*
|Wähle aus, nach welchem Datumstyp in Verbindung mit der Datumsauswahl darunter gesucht werden soll. Du kannst wählen zwischen *Importdatum*, *Eingangsdatum* und *Zuordnungsdatum*. Angezeigt werden dann alle Zahlungen, die in dem gewählten Zeitraum entsprechend importiert wurden, eingegangen sind oder zugeordnet wurden.

|*Datum von und Datum bis*
|Wähle in Verbindung mit *Datumstyp* einen Zeitraum aus, um nach Zahlungen zu suchen, die in diesem Zeitraum importiert wurden, eingegangen sind oder zugeordnet wurden, je nach Auswahl.

|*Reset*
|Auf *Reset* klicken, um Filter zurückzusetzen. Erneut auf *Suchen* klicken, um alle Zahlungseingänge anzuzeigen.

|*Suchen*
|Führt die Suche aus.

|====

[#30]
== Zahlungen zuordnen

Es gibt zwei Möglichkeiten, um unzugeordnete Zahlungen einem Auftrag zuzuordnen. Im Menü *Aufträge » Zahlungsverkehr* kannst du Zahlungen entweder direkt in der Übersicht zuordnen oder du gehst in die Detailansicht einer Zahlung.
Eine Zuordnung in der Übersicht funktioniert über die direkte Eingabe der Auftrags-ID. Dies ist ein einfacher und schneller Weg, wenn du schon weißt welchem Auftrag die Zahlung zugeordnet werden soll, sonst keine weiteren Informationen zur Zahlung benötigst und die Auftrags-ID zur Hand hast.
Gehe wie im Folgenden beschrieben vor, um eine Zahlung in der Übersicht zuzuordnen.

[.instruction]
Zahlung direkt anhand der Auftrags-ID in der Übersicht zuordnen:

. Öffne das Menü *Aufträge » Zahlungsverkehr*.
. Suche (icon:filter[]) anhand der <<payments/beta-zahlungen-verwalten#20, Filtereinstellungen>> die gewünschte Zahlung.
. Gib in der Zeile der unzugeordneten Zahlung im Feld *Auftrags-ID* direkt die entsprechende ID des Auftrages, dem die Zahlung zugeordnet werden soll, ein. +
. Drücke die *Entertaste* zum Speichern. +
→ Die Zahlung ist zugeordnet und die Übersicht wird aktualisiert.

Wenn eine schnelle Zuordnung in der Übersicht nicht möglich ist oder du detailliertere Informationen zu einer Zahlung brauchst, gehe in die Detailansicht einer Zahlung. Klicke dafür in der Übersicht auf die Zeile der entsprechenden Zahlung oder direkt auf die Zahlungs-ID. Wenn du in der Übersichtstabelle auf die Aktion *Zuordnen* (icon:payment_assign[set=plenty,role="green"]) klickst, wird ebenfalls die Detailansicht der Zahlung geöffnet.
Um eine Zahlung aus der Detailansicht heraus zuzuordnen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Zahlung in Detailansicht zuordnen:

. Öffne das Menü *Aufträge » Zahlungsverkehr*.
. Suche (icon:filter[]) anhand der <<payments/beta-zahlungen-verwalten#20, Filtereinstellungen>> die gewünschte Zahlung.
. Öffne die Zahlung, indem du entweder in der Zeile der unzugeordneten Zahlung, die du zuordnen möchtest, auf die Payment-ID oder auf auf *Zuordnen* (icon:payment_assign[set=plenty,role="green"]) klickst. +
→ Du wirst weitergeleitet zum Bereich *Zuordnung* dieser Zahlung. +
→ Die Aufträge mit der höchsten Übereinstimmung werden dort angezeigt.
. Wähle den passenden Auftrag aus und klicke auf *Zahlung zuordnen* (icon:payment_assign[set=plenty,role="green"]). +
→ Die Zahlung ist nun dem ausgewählten Auftrag zugeordnet. Es wird nur noch die ausgewählte Zuordnung angezeigt.

Die Übereinstimmungen zwischen Zahlungen und Aufträgen werden anhand einer Matrix im Hintergrund überprüft. Diese Überprüfung wird ausgelöst, sobald du die Tabelle *Zuordnung* in der Detailansicht einer Zahlung öffnest. Dann werden dir absteigend maximal die 10 Aufträge mit den höchsten Übereinstimmungsraten angezeigt.
Sobald du eine Zahlung zugeordnet hast, wird in dieser Tabelle nur noch diese Zuordnung angezeigt. Nur wenn die Zahlung vom Auftrag <<payments/beta-zahlungen-verwalten#40, gelöst>> wird, werden hier wieder die höchsten Übereinstimmungen angezeigt.

Einem Auftrag können mehrere Zahlungen zugeordnet werden. Dies kann z.B. vorkommen, wenn mit der ersten Zahlung nicht der gesamte Betrag abgedeckt wurde. Sind einem Auftrag bereits Zahlungen zugeordnet und du möchtest eine weitere zuordnen, muss dies in einer Abfrage bestätigt werden.

Diese Tabelle ist anpassbar. Das bedeutet, dass du selbst entscheiden kannst, welche Informationen dir in den Tabellenspalten angezeigt werden. Gehe dafür folgendermaßen vor:

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (icon:cog[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle aus, welche Spalten angezeigt werden sollen.
. Verschiebe (icon:drag_sort_handle[set=plenty]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

[#40]
== Zahlungen lösen

Es gibt zwei Möglichkeiten, Zahlungen von einem Auftrag zu lösen. Im Menü *Aufträge » Zahlungsverkehr* kannst du Zuordnung der Zahlungen entweder direkt in der Übersicht oder in der Detailansicht einer Zahlung aufheben.
Gehe wie im Folgenden beschrieben vor, um die Zuordnung einer Zahlung in der Übersicht zu lösen.

[.instruction]
Zahlung in der Übersicht lösen:

. Öffne das Menü *Aufträge » Zahlungsverkehr*.
. Suche (icon:filter[]) anhand der <<payments/beta-zahlungen-verwalten#20, Filtereinstellungen>> die gewünschte Zahlung.
. Klicke in der Zeile der Zahlung, für die du die Zuordnung lösen möchtest, auf *Zahlung lösen* (icon:undo[role="orange"]). +
→ Die Zahlung wird vom Auftrag gelöst und wird wieder als unzugeordnete Zahlung angezeigt.

Eine Zahlung lässt sich auch in der Detailansicht lösen. Gehe dafür wie im Folgenden beschrieben vor:

[.instruction]
Zahlungseingang in Detailansicht lösen:

. Öffne das Menü *Aufträge » Zahlungsverkehr*.
. Suche (icon:filter[]) anhand der <<payments/beta-zahlungen-verwalten#20, Filtereinstellungen>> die gewünschte Zahlung.
. Klicke in die Zeile der Zahlung, für die du die Zuordnung lösen möchtest. +
→ Du wirst weitergeleitet zur Detailansicht dieser Zahlung.
. Öffne die Tabelle *Zuordnung*. +
→ Wenn sich die Tabelle öffnet wird die bestehende Auftragszuordnung wird angezeigt.
. Klicke auf *Zahlung lösen* (icon:undo[role="orange"]). +
→ Die Zahlung wird vom Auftrag gelöst. Es werden wieder die höchsten Übereinstimmungen für diese Zahlung angezeigt.

[IMPORTANT]
.Beachten beim Lösen von Zahlungen
====
Das Lösen von Zahlungen von einem Auftrag ist technisch zu jedem Zeitpunkt möglich, auch wenn die Auftragsbearbeitung schon fortgeschritten oder sogar abgeschlossen ist. Das Lösen von Zahlungen sollte aber nur möglichst gezielt geschehen, da durch wiederholtes Zuordnen und Lösen Fehler entstehen können, z.B., dass der Auftrag nicht mehr vollständig durch die Zahlung gedeckt wird. Beachte zudem, dass das Lösen einer Zahlung auch Änderungen an dem Auftrag, von dem die Zahlung gelöst wurde, bewirkt, wie z.B. eine Neuberechnung der Zahlung im Auftrag oder einen Statuswechsel.
====

[#50]
== Zahlungen teilen

Manuell gebuchte Zahlungseingänge, importierte Bankbuchungen sowie EBICS-Zahlungen können geteilt werden. Das bedeutet, dass der Betrag einer Zahlung auf mehrere Aufträge aufgeteilt werden kann. Dies machst du im Menü *Aufträge » Zahlungsverkehr*. Beachte, dass Vormerkposten von der Zahlungsaufteilung ausgenommen sind. Um Zahlungen aufzuteilen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Zahlung aufteilen:

. Öffne das Menü *Aufträge » Zahlungsverkehr*.
. Suche (icon:filter[]) anhand der <<payments/beta-zahlungen-verwalten#20, Filtereinstellungen>> die gewünschte Zahlung.
. Klicke in der Zeile der gewünschten Zahlung auf das Icon *Zahlung aufteilen* (icon:item_variation_distribute_quantity[set=plenty,role="yellow"]). +
→ Du wirst weitergeleitet zu einer eigenen Ansicht, in der du das Teilen vornimmst.
. Suche (icon:filter[]) anhand der Filter *Auftrags-ID*, *Rechnungsnummer*, *Kunden-ID* und *Externe Auftrags-ID* nach den entsprechenden Aufträgen. Du kannst mehrere IDs/Nummern eingeben, indem du sie durch ein Komma separierst.
. Wähle aus den Suchergebnissen die Aufträge aus, auf die du die Zahlung aufteilen möchtest.
. Klicke auf *Speichern* (icon:save[role=green]). +
→ Die Zahlung wird aufgeteilt und den ausgewählten Aufträgen in der Reihenfolge der Tabelle von oben nach unten zugeordnet und du wirst zur Zahlungsübersicht zurückgeleitet. Hier lassen sich die entstandenen Teilzahlungen wie in den anderen Kapiteln beschrieben bearbeiten.

Beim Aufteilen einer Zahlung wird der Betrag dieser Zahlung immer um den jeweiligen Zahlungsbetrag der Aufträge, die beim Aufteilen ausgewählt werden, reduziert. Sowohl der ursprüngliche Gesamtbetrag der Zahlung als auch der Restbetrag werden dir in dieser Ansicht angezeigt. Wenn ein Restbetrag entsteht, kann dieser bei Bedarf erneut aufgeteilt werden.

_Als Beispiel_: Stell dir vor, du willst eine Zahlung mit dem Betrag von 120 Euro aufteilen auf Auftrag A, mit einem offenen Rechnungsbetrag von 80 Euro, und Auftrag B, mit einem offenen Rechnungsbetrag von 20 Euro. Durch das Aufteilen und die Auswahl von genau diesen Aufträgen werden Auftrag A = 80 Euro und Auftrag B = 20 Euro zugewiesen. Die durch das Teilen entstehenden Zahlungen sind durch deine Auswahl diesen Aufträgen zugeordnet worden. Es bleibt ein Restbetrag von 20 Euro als unzugeordneter Eintrag übrig. Diesen Restbetrag kannst du einem anderen Auftrag zuordnen oder bei Bedarf ebenfalls aufteilen.

[IMPORTANT]
.Aufteilen einer Zahlung rückgängig machen ist nicht möglich
====
Das Aufteilen einer Zahlung kann nicht rückgängig gemacht werden. Um den ursprünglichen Zahlungseingang wiederherzustellen, lösche alle Teilzahlungen. Wird eine Teilzahlung gelöscht, wird der Betrag wieder zur ursprünglichen Zahlung hinzugerechnet. Vor dem Löschen müssen die Teilzahlungen vom Auftrag gelöst werden, da nur unzugeordnete Zahlungen gelöscht werden können.
====

[#60]
== Zahlungen löschen

Du kannst eine Zahlung nur löschen, wenn sie keinem Auftrag zugeordnet ist. Das Löschen kann entweder direkt in der Übersicht oder in der Detailansicht des Zahlung vorgenommen werden. Um eine Zahlung aus der Übersicht zu löschen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Zahlung aus der Übersicht löschen:

. Öffne das Menü *Aufträge » Zahlungsverkehr*.
. Klicke in der Zeile eines Zahlungseingangs auf *Löschen* (icon:minus-circle[role=red]). +
→ Die Bestätigung *Löschen der Zahlung bestätigen* wird geöffnet.
. Klicke auf *Zahlung löschen*. +
→ Die Zahlung wird gelöscht und die Übersicht aktualisiert.

Des Weiteren steht dir die Funktion *Löschen* auch in der Detailansicht einer Zahlung zur Verfügung. Gehe dafür wie im Folgenden beschrieben vor.

[.instruction]
Zahlung aus der Detailansicht heraus löschen:

. Öffne das Menü *Aufträge » Zahlungsverkehr*.
. Klicke in die Zeile der Zahlung, die gelöscht werden soll, um sie zu öffnen. +
→ Du wirst weitergeleitet zur Detailansicht dieser Zahlung.
. Klicke über den Zahlungsdetails auf *Zahlung löschen* (icon:minus-circle[role=red]).
. Klicke in der Abfrage auf *Ja*. +
→ Die Zahlung wird gelöscht und du wirst zur aktualisierten Übersicht zurückgeleitet.

[#70]
== Gruppenfunktion nutzen

Mit der Gruppenfunktion bearbeitest du beliebig viele Zahlungen gleichzeitig. Um die Gruppenfunktion nutzen zu können, muss mindestens eine Zahlung ausgewählt sein. Nutze die Suche, um die gewünschten Zahlungen zu filtern. Nachdem du die gewünschten Zahlungen ausgewählt hast, kannst du diese entweder alle auf einmal automatisch zuordnen oder sie alle auf einmal löschen. Denk daran, dass nur unzugeordnete Zahlungen gelöscht werden können.

Gehe wie im Folgenden beschrieben vor, um Zahlungen mit der Gruppenfunktion automatisch zuzuordnen oder zu löschen.

[.instruction]
Zahlungen per Gruppenfunktion bearbeiten:

. Öffne das Menü *Aufträge » Zahlungsverkehr*.
. Wähle die Zahlungseingänge aus, die du zuordnen oder löschen möchtest, indem du ein Häkchen setzt.
. Klicke über der Übersichtstabelle entweder auf *Zahlungen löschen* (icon:trash[set=plenty]) oder auf *Zahlungen automatisch zuordnen* (icon:payment_assign[set=plenty,role="green"]). +
→ Du musst das Löschen oder die Zuordnung in einer Abfrage bestätigen oder ablehnen.
. Nach der Ausführung wird dir angezeigt, wieviele der ausgewählten Zahlungen automatisch zugeordnet oder gelöscht wurden.

Nach Ausführen der Gruppenfunktion wird dir angezeigt, wieviele der ausgewählten Zahlungen gelöscht oder zugeordnet werden konnten. Es kann vorkommen, dass nicht die gesamte Auswahl bearbeitet werden konnte. Zum Beispiel könnte eine oder mehrere der Zahlungen, die du löschen möchtest, einem Auftrag zugeordnet sein, dann sind Zahlungen nicht löschbar. Möchtest du aufgrund der Anzeige genauere Informationen haben, kannst du diese im Log einsehen. Gehe dafür ins Menü *Daten » Log*.

Für die automatische Zuordnung ist zu beachten, dass diese von der Einstellung *Übereinstimmung für automatische Zuordnung (0.7 - 1.0)* im Menü *Einrichtung » Aufträge » Zahlung » Eingänge* abhängt. Der Wert 0.7 steht für 70% Übereinstimmung, der Wert 1.0 für 100% Übereinstimmung. Wird bei der automatischen Zuordnung per Gruppenfunktion dann mehr als ein Auftrag mit der gleichen Übereinstimmungsrate ermittelt, kann die Zahlung nicht zugeordnet werden. Umgekehrt bedeutet dies, dass eine Zahlung nur automatisch zugeordnet wird, wenn ein einziger Auftrag mit der gewählten Übereinstimmungsrate ermittelt wird.

[#80]
== Weitere Anzeigen in der Detailansicht

Neben den Funktionen <<payment/beta-zahlungen-verwalten#30, Zahlungen zuordnen>>, <<payment/beta-zahlungen-verwalten#40, Zahlungen lösen>> und <<payment/beta-zahlungen-verwalten#60, Zahlungen löschen>> bietet dir die Detailansicht einer Zahlung einen Überblick über alle mit dieser Zahlung verknüpften Informationen.
Im oberen Bereich siehst du auf einen Blick die wichtigen Informationen, wie z.B. den Betrag, die Zahlungsart oder von wem die Zahlung kam.

Der Bereich *Zuordnung* bietet dir eine Auflistung der höchsten Übereinstimmungen mit Aufträgen für unzugeordnete Zahlungen. Ist eine Zahlung bereits zugeordnet, wird hier nur dieser entsprechende Eintrag angezeigt.

Die *Zahlungshistorie* bietet dir eine Übersicht über alle Aktionen, die in Zusammenhang mit dieser Zahlung ausgeführt wurden. Angezeigt wird auch, wer die Aktion zu welchem Zeitpunkt ausgeführt hat, so dass eine Nachvollziehbarkeit immer gewährleistet ist.

Die *Eigenschaften* (Properties) im unteren Bereich zeigen dir alle weiteren Informationen, die die Zahlung betreffen. Diese Informationen gehen in der Regel über die Details im oberen Bereich hinaus. Welche Informationen hier angezeigt werden, hängt von der Zahlung selber, z.B. der Zahlungsart und welche Informationen vom Zahlungsanbieter übermittelt werden, ab.
