= Zahlungen verwalten
:lang: de
include::{includedir}/_header.adoc[]
:description: Payment in plentymarkets: Erfahren Sie alles über Zahlungseingänge und Zahlungsausgänge.
:position: 20

Zahlungen erreichen Ihr System aus verschiedenen Quellen. Im Menü *Aufträge » Zahlungsverkehr* verwalten Sie sämtliche Zahlungseingänge unabhängig von der Zahlungsquelle. Grundsätzlich wird zwischen zwei Arten von Zahlungsmöglichkeiten unterschieden: Zahlungen mit und Zahlungen ohne Zahlungsanbieter. Zahlungen per PayPal oder Vorkasse in Form einer Vorab-Überweisung erfordern einen Zahlungsanbieter, auch Payment Provider genannt. Barzahlungen benötigen keinen Zahlungsanbieter. Weitere Informationen zu Zahlungsarten und Payment-Plugins finden Sie im Bereich <<payment#, Payment>>.

[#10]
== Grundeinstellungen für Zahlungseingänge vornehmen

In diesem Menü nehmen Sie Einstellungen für die automatische Zuordnung sowie die Zahlungskulanz vor. Es sind bereits Standardeinstellungen im System hinterlegt, die aus Erfahrungswerten gewonnen wurden und sich in der Praxis bewährt haben. Um diese Einstellungen zu ändern, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Grundeinstellungen ändern:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Eingänge*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-grundeinstellungen-zahlungseingang>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-grundeinstellungen-zahlungseingang]]
.Grundeinstellungen für Zahlungseingänge vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Übereinstimmung für automatische Zuordnung*
|Zwischen *0.7* (nicht so genaue Übereinstimmung zur Zuordnung nötig) und *1.0* (genaue Übereinstimmung nötig) wählen. Ist dieser Wert höher eingestellt, kann das Problem auftreten, dass Zahlungen nicht zugeordnet werden können. Daher ist in der *Standard-Einstellung* ein Wert von *0,75* eingestellt.

|*Zahlungskulanz*
|Damit z.B. interne Nachkommabeträge (ab der dritten Nachkommastelle) nicht zu falschen Buchungen führen, sollte ein *Mindestbetrag* von *0,01* eingetragen sein (Standard-Einstellung). Wenn z.B. *0,05* eingestellt ist, werden Fehlbeträge bis 5 Cent trotzdem als korrekte Buchung behandelt.

|*Kundenbankdaten importieren*
|Wählen, ob die *Bankdaten* des Kunden beim Zahlungseingang *importiert* und in den jeweiligen *Kundendaten* hinterlegt werden sollen oder nicht. +
*_Wichtig:_* Da Bankdaten nur mit Zustimmung des Kunden importiert und gespeichert werden dürfen, ist hier standardmäßig *Nein* voreingestellt. Vor dem Aktivieren die Rechtslage zu diesem Thema beachten, ggf. auch im jeweiligen Lieferland.

|*PayPal Zahlung nur entsprechendem eBay Listing zuordnen, sofern an der Zahlung hinterlegt*
|Falls Sie ebay Listings in Kombination mit der Zahlungsart PayPal verwenden, empfehlen wir, bei dieser Option *JA* auszuwählen. So wird sichergestellt, dass entsprechende PayPal-Zahlungen den dazugehörigen Aufträgen von eBay korrekt zugeordnet werden. Sollte an einer PayPal Zahlung eine eBay Listing-ID hinterlegt sein, so wird bei aktivierter Option diese Zahlung nur dem Auftrag zugeordnet, der über eine übereinstimmende eBay Listing-ID verfügt. +
*_Hinweis:_* Diese Funktionalität bezieht sich ausschließlich auf die PayPal-Schnittstelle für plentymarkets Callisto-Shops und *nicht* auf das PayPal-Plugin!

|*WooCommerce PayPal Zahlung ignorieren*
|Wählen Sie die Option *JA*, um bei Aufträgen mit der Zahlungsart PayPal, die über WooCommerce importiert werden, den automatischen Zahlungsimport zu deaktivieren. +
*_Hinweis:_* Diese Funktionalität bezieht sich ausschließlich auf die PayPal-Schnittstelle für plentymarkets Callisto-Shops und *nicht* auf das PayPal-Plugin!

|====

[#20]
== Zahlungen buchen

Zahlungen gehen entweder automatisch im System ein oder werden manuell eingebucht. Zahlungen gehen z.B. automatisch ein, wenn Sie Payment-Plugins in Ihrem plentymarkets System nutzen. Einige Zahlungsanbieter leiten den Kunden zur Abwicklung des Zahlungsvorgangs auf die eigenen Seiten weiter. Bei anderen Anbietern werden in Ihrem Shop die Zahlungsdaten entgegengenommen und im Hintergrund an den Provider weitergeleitet. In beiden Fällen erhält plentymarkets nach erfolgter Zahlung eine Rückmeldung des Anbieters und vermerkt den Zahlungseingang direkt im Auftrag. Manuell importieren Sie z.B. Bankbuchungen für Zahlungen, die unabhängig von einem Zahlungsanbieter ablaufen.

[#30]
=== Bankbuchungen importieren

Zahlungsvorgänge bei der Zahlungsart Vorkasse und sonstigen Überweisungen fallen in Form von Bankbuchungen an. Bei diesen Zahlungsarten müssen die auf Ihrem Konto gebuchten Zahlungen an das System gemeldet und den Aufträgen korrekt zugeordnet werden. Importieren Sie Bankbuchungen im CSV-Format in Ihr plentymarkets System. Beachten Sie dabei die Reihenfolge der Parameter, die von Ihrem Bankprogramm abhängt. Legen Sie zunächst die Spaltenreihenfolge für den Import fest.

[.instruction]
Spaltenreihenfolge festlegen:

. Öffnen Sie das Menü *Aufträge » Zahlungsverkehr*. +
→ Das Tab *Zahlungsverkehr* wird angezeigt.
. Wechseln Sie in das Tab *Bankbuchungen » Tab: Einstellungen Datenformat*.
. Wählen Sie ein *Bankkonto*.
. Klicken Sie auf *Bearbeiten*. +
→  Die Tabelle *Felderbelegung* wird angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-spaltenreihenfolge-festlegen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-spaltenreihenfolge-festlegen]]
.Spaltenreihenfolge festlegen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Bankkonto*
|*Standard-Konto* oder *Konto 2* wählen. Wenn unterschiedliche Konfigurationen benötigt werden, alternative Einrichtung für *Konto 2* vornehmen.

|*Ab Zeile*
|Wählen, ab welcher Zeile die Buchungsdaten importiert werden. Häufig beginnen CSV-Dateien mit einer Kopfzeile, in diesem Fall hier den Wert *2* wählen.

|*Inhalt*
|Inhalt wählen und die Reihenfolge der Spalten in der CSV-Datei festlegen.
|====

Importieren Sie anschließend Ihre Bankbuchungsdatei.

[.instruction]
Import durchführen:

. Öffnen Sie das Menü *Aufträge » Zahlungsverkehr*. +
→ Das Tab *Zahlungsverkehr* wird angezeigt.
. Wechseln Sie in das Tab *Bankbuchungen » Tab: Importieren*.
. Wählen Sie das *Bankkonto* aus der Dropdown-Liste.
. Wählen Sie das *Feldtrennzeichen*.
. Klicken Sie unter *Buchungsdatei* auf *Datei auswählen*. +
→ Ein Fenster wird geöffnet.
. Wählen Sie die CSV-Datei.
. Klicken Sie *Import*. +
→ Die Buchungsdatei wird importiert.

Sie können diesen Vorgang mehrfach wiederholen. Dabei werden Duplikate, d.h. doppelt eingelesene Datensätze, verworfen. Im Anschluss an den Import wird ein Durchlauf mit automatischer Zuordnung zu Aufträgen gestartet.

[#40]
=== Zahlungen manuell buchen

Wenn Sie eine Zahlung oder Teilzahlung manuell im Auftrag buchen möchten, weil z.B. Ihr Kunde die Ware bei Abholung bar bezahlt hat oder weil eine Zahlung nicht in der Übersicht zu finden ist, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Zahlung buchen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag, in dem Sie eine Zahlung buchen möchten. +
→ Das Tab *Übersicht* wird geöffnet.
. Wechseln Sie in das Tab *Zahlung*.
. Klicken Sie auf *Zahlung buchen*. +
→ Das Fenster *Zahlung buchen* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-zahlungen-manuell-buchen>>.
. Klicken Sie auf *Zahlung buchen*. +
→ Die Zahlung wird gebucht und in der Zahlungsübersicht angezeigt. Die Beträge in der Kopfzeile der Übersicht werden angepasst.

[[tabelle-zahlungen-manuell-buchen]]
.Zahlungen manuell buchen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Betrag*
|Vollen Betrag oder Teilbetrag eingeben, der gebucht werden soll.

|*Haben/Soll*
|*Haben* oder *Soll* wählen. Die Auswahl richtet sich nach dem offenen Betrag. Standardmäßig ist *Haben* gewählt. Bei negativen offenen Beträgen, z.B. bei einer Überzahlung, ist *Soll* gewählt. Die Auswahl kann bei Bedarf geändert werden.

|*Währung*
|Währung wählen, in der die Zahlung vorgenommen werden soll.

|*Wechselkurs*
|Bei Bedarf einen von der aktuellen System-Wechselkurs-Konfiguration abweichenden Wechselkurs eingeben. +
*_Wichtig_*: Wenn die Zahlung in einer anderen Währung als der für die Zahlung eingestellten Währung (Standard-Währung) gebucht werden soll, z.B. in US-Dollar, unter *Währung* die Option *USD* wählen und unter *Betrag* den erhaltenen Betrag eingeben. +
Wenn der Wechselkurs im Menü <<payment/waehrungen#, System » Systemeinstellungen » Aufträge » Zahlung » Währungen>> ermittelt wurde und verwendet werden soll, unter *Wechselkurs* nichts eingeben, da dieser Kurs automatisch angewendet wird. Die Option *Wechselkurs* wird nur benötigt, wenn ein anderer Wechselkurs für diese Zahlung angewendet werden soll, z.B. der Kurs zum Zeitpunkt des Zahlungseingangs. In diesem Fall den zu diesem Zeitpunkt zutreffenden Wechselkurs eingeben.

|*Verwendungszweck*
|Hier ist die Auftrags-ID voreingetragen, dieser Eintrag kann angepasst werden.

|*Zahlungseingang*
|Datum des Zahlungseingangs wählen. Standardmäßig ist das aktuelle Datum voreingestellt.
|====

Manuell gebuchte Zahlungseingänge erkennen Sie an dem Symbol *Manuelle Buchung*.

[#50]
=== Nicht buchbare Zahlungen

Es gibt Fälle, in denen Zahlungen in der Übersicht keinen Aufträgen mehr zugeordnet werden können. Das sind zum Beispiel Vormerkposten, zu denen die eigentliche Zahlung bereits gebucht wurde. Die Zahlungen werden in der Übersicht mit *Nicht verbuchbare Zahlung* gekennzeichnet.

[#60]
== Zahlungen zuordnen

Nach der Buchung in plentymarkets werden die Zahlungen Aufträgen über eine unscharfe Suche automatisch zugeordnet. Wenn die Zuordnung fehlschlägt, können Buchungen Aufträgen <<payment/zahlungen-verwalten#80, manuell zugeordnet>> werden. Unzugeordnete Zahlungen sind mit einem *grünen Pfeil* gekennzeichnet.

[TIP]
.Ereignisaktionen für Zahlungseingänge einrichten
====
Der Zahlungseingang als Ereignis spielt in der Auftragsbearbeitung eine wichtige Rolle, da der Versand häufig erst nach Zahlungseingang erfolgt. In plentymarkets wechselt der Status der meisten Aufträge mit dem Eintreffen der Zahlung von *Status [3] - Warten auf Zahlung* in *Status [5] - Freigabe Versand*. Richten Sie <<automatisierung/ereignisaktionen#, Ereignisaktionen>> ein, um die Auftragsbearbeitung zu automatisieren und den Versand nach Zahlungseingang auszulösen.
====

Sie haben zwei Möglichkeiten, unzugeordnete Zahlungseingänge zuzuordnen. Zum einen, einzelne Zahlungseingänge manuell zuzuordnen, zum anderen, mehrere Zahlungen automatisch zuzuordnen. Wie Sie die Übereinstimmungsquote für Zahlungseingänge festlegen, finden Sie unter <<payment/zahlungen-verwalten#10, Grundeinstellungen für Zahlungseingänge vornehmen>>.

[#70]
=== Zahlungseingänge manuell zuordnen

Gehen Sie wie im Folgenden beschrieben vor, um Zahlungseingänge manuell zuzuordnen.

[.instruction]
Zahlungseingang manuell zuordnen:

. Öffnen Sie das Menü *Aufträge » Zahlungsverkehr*.
. Klicken Sie in der Zeile eines unzugeordneten Zahlungseingangs auf *Zahlung zuordnen*. +
→ Ein Fenster wird geöffnet.
. Wählen Sie den Auftrag, dem die Zahlung zugeordnet werden soll.
. Wenn nicht automatisch ein passender Auftrag angezeigt wird, geben Sie die *Auftrags-ID* oder die zugehörige *Rechnungsnummer* in das Eingabefeld ein.
. Klicken Sie auf *Zuordnen*, um den Auftrag zuzuordnen.

[#80]
=== Zahlungseingänge automatisch per Gruppenfunktion zuordnen

Mit der Gruppenfunktion bearbeiten Sie beliebig viele Zahlungen gleichzeitig. Gehen Sie wie im Folgenden beschrieben vor, um Zahlungseingänge mit der Gruppenfunktion automatisch zuzuordnen.

[.instruction]
Zahlungseingänge automatisch zuordnen:

. Öffnen Sie das Menü *Aufträge » Zahlungsverkehr*.
. Filtern Sie die Zahlungseingänge, die Sie zuordnen möchten.
. Setzen Sie ein Häkchen bei den zuzuordnenden Zahlungseingängen.
. Klicken Sie auf *Gruppenfunktion*. +
→ Das Fenster *Gruppenfunktion* wird geöffnet.
. Aktivieren Sie *Automatische Zuordnung*.
. Klicken Sie auf *Ausführen*. +
→ Die Zahlungseingänge werden zugeordnet.

[#90]
=== Zuordnung von Zahlungseingängen aufheben

Sie können entweder nur die Zuordnung aufheben und anschließend den Zahlungseingang erneut einem Auftrag zuordnen oder die Zuordnung aufheben und den Zahlungseingang löschen. Dies ist ebenfalls im Tab *Zahlung* eines Auftrags möglich.

[.instruction]
Zuordnung aufheben:

. Öffnen Sie das Menü *Aufträge » Zahlungsverkehr*.
. Klicken Sie in der Zeile eines zugeordneten Zahlungseingangs auf *Auftragszuordnung aufheben*. +
→ Die Zuordnung wird aufgehoben und ein *grüner Pfeil* wird angezeigt.

[.instruction]
Zuordnung aufheben und Zahlungseingang löschen:

. Öffnen Sie das Menü *Aufträge » Zahlungsverkehr*.
. Klicken Sie in der Zeile eines zugeordneten Zahlungseingangs auf *Auftragszuordnung aufheben*. +
→ Die Zuordnung wird aufgehoben und ein *grüner Pfeil* wird angezeigt.
. Klicken Sie am Ende der Zeile des Zahlungseingangs auf *Löschen*. +
→ Der Zahlungseingang wird gelöscht.

[#100]
==  Zahlungen suchen

Sie können die Suche nach Zahlungen nutzen, um Zahlungen eines Zahlungsanbieters zu prüfen oder unzugeordnete Zahlungen zu finden. Dazu steht das Tab *Filter* zur Verfügung.

[.instruction]
Zahlungen suchen:

.  Öffnen Sie das Menü *Aufträge » Zahlungsverkehr*.
. Wählen Sie die *Filter*. Beachten Sie dazu die Erläuterungen in <<tabelle-zahlungen-suchen>>.
.  Klicken Sie auf *Suchen*, um die Suche auszuführen.

[[tabelle-zahlungen-suchen]]
.Zahlungen suchen
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Reset*
| Auf *Reset* klicken, um Filter zurückzusetzen. Erneut auf *Suchen* klicken, um alle Zahlungseingänge anzuzeigen.

|*ID*
| ID eingeben, um nach der Zahlung mit dieser ID zu suchen.

|*Auftrags-ID*
| ID des Auftrags eingeben, dem eine Zahlung zugeordnet ist.

|*Verwendungszweck*
| Verwendungszweck oder einen Teil des Verwendungszwecks eingeben, um nach Zahlungen mit diesem Zweck zu suchen.

|*Kontoinhaber*
| Kontoinhaber eingeben, um nach Zahlungen mit diesem Kontoinhaber zu suchen.

|*Zuordnung*
|*Zugeordnet*, *Unzugeordnet* oder *ALLE* wählen. +
*Zugeordnet* = Nur Zahlungen anzeigen, die bereits einem Auftrag zugeordnet wurden. +
*Unzugeordnet* = Nur Zahlungen anzeigen, die keinem Auftrag zugeordnet wurden.

|*Zahlungsart*
| Eine Zahlungsart oder *ALLE* wählen, um nach Zahlungen mit dieser Zahlungsart zu suchen.

|*S/H*
|*Haben*, *Soll* oder *ALLE* wählen. +
*Haben* = Alle Zahlungseingänge mit positivem Wert werden angezeigt. +
*Soll* = Alle Zahlungseingänge mit negativem Wert werden angezeigt.

|*Status*
| Einen Status oder *ALLE* wählen, um nach Zahlungen mit diesem Status zu suchen.

|*Transaktionstyp*
| Einen Transaktionstyp oder *ALLE* wählen, um nach Zahlungen mit diesem Transaktionstyp zu suchen.

|*Währung*
| Eine Währung oder *ALLE* wählen, um nach Zahlungen mit dieser Währung zu suchen.

|*Wert*
|Operator wählen und eine Summe eingeben. +
*_Beispiel_*: *&gt;=* wählen und 300 als *Wert* eingeben, um alle Zahlungen mit einem Zahlbetrag von 300 EUR oder mehr anzuzeigen.

|*Eingangsdatum von; +
Eingangsdatum bis*
| Datum wählen, um nach Zahlungen zu suchen, die in diesem Zeitraum eingegangen sind.

|*Importdatum von; +
Importdatum bis*
| Datum wählen, um nach Zahlungen zu suchen, die in diesem Zeitraum importiert wurden.

|*Zuordnungsdatum von; +
Zuordnungsdatum bis*
| Datum wählen, um nach Zahlungen zu suchen, die in diesem Zeitraum zugeordnet wurden.
|====

[#110]
== Zahlungen bearbeiten

Zahlungen bearbeiten Sie entweder im Menü *Zahlungsverkehr* oder direkt im Auftrag. Bei zugeordneten Zahlungen ist der Auftrag über die ID neben dem gelben Pfeil in der Spalte *Zuordnung* verknüpft. Klicken Sie auf die ID, um den Auftrag zu öffnen. Im Auftrag finden Sie im Tab *Zahlung* alle mit diesem Auftrag verbundenen Zahlungen. Dort stehen die gleichen Funktionen zur Verfügung wie im Menü *Zahlungsverkehr*. Zusätzlich können Sie direkt <<payment/zahlungen-verwalten#20, Zahlungen buchen>>.

[#120]
=== Zahlungsinformationen abrufen

In der Übersicht im Tab *Zahlung* eines Auftrags werden ganz oben im Tab folgende Informationen zu den Beträgen angezeigt:

* *Gesamtbetrag* = Summe des Auftrags.
* *Bezahlt* = Summe, die bereits bezahlt wurde.
* *Offen* = Summe, die noch nicht bezahlt wurde.

[#130]
=== Zahlungen aufteilen

Manuell gebuchte Zahlungseingänge, importierte Bankbuchungen sowie EBICS-Zahlungen teilen Sie im Menü *Aufträge » Zahlungsverkehr* auf. Auf diese Weise können Sie eine Zahlung mehreren Aufträgen zuordnen. Beachten Sie, dass Vormerkposten von der Zahlungsaufteilung ausgenommen sind. Um Zahlungen aufzuteilen, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Zahlung aufteilen:

. Öffnen Sie das Menü *Aufträge » Zahlungsverkehr*.
. Klicken Sie in der Zeile eines Zahlungseingangs auf *Zahlung aufteilen*. +
→ Das Fenster *Zahlung aufteilen* wird geöffnet und eine Liste mit allen offenen Aufträgen wird angezeigt.
. Filtern Sie ggf. die Aufträge.
. Setzen Sie Häkchen bei den Aufträgen, die Sie der Zahlung zuordnen möchten.
. Klicken Sie auf *Ausführen*. +
→ Die Zahlung wird den gewählten Aufträgen zugeordnet.

[NOTE]
.Neue zugeordnete Zahlungen in der Übersicht nach Aufteilung einer Zahlung
====
Nach einem Klick auf *Neu laden* werden neue Einträge in der Übersicht des Zahlungsverkehrs erstellt, die den zuvor gewählten Aufträgen zugeordnet sind, sowie ggf. ein unzugeordneter Eintrag mit dem Restbetrag des Zahlungseingangs. Der unzugeordnete Eintrag kann wiederum gesplittet werden. Um den ursprünglichen Zahlungseingang wiederherzustellen oder zu löschen, löschen Sie zunächst alle per Splitting zugeordneten Zahlungen.
====

[#140]
=== Zahlungen löschen

Um eine Zahlung aus der Übersicht zu löschen, gehen Sie wie im Folgenden beschrieben vor.

. Öffnen Sie das Menü *Aufträge » Zahlungsverkehr*.
. Klicken Sie in der Zeile eines Zahlungseingangs auf *Löschen*. +
→ Das Fenster *Löschen der Zahlung bestätigen* wird geöffnet.
. Klicken Sie auf *Zahlung löschen*. +
→ Die Zahlung wird gelöscht und die Übersicht aktualisiert.

[#150]
=== Teilzahlungen bearbeiten

Es kommt vor, dass Kunden nicht die gesamte Auftragssumme zahlen. Der Eingang einer Teilzahlung führt im Auftrag zu einem Wechsel in den Status 3.3 (Versandfertig, Warten auf Zahlung). Sobald ein Auftrag komplett bezahlt ist, wechselt der Status in 4 (Versandvorbereitung, warten auf Auffüllung des Warenbestands) oder 5 (Freigabe Versand). Richten Sie eine Ereignisaktion ein, über die Kunden automatisch per E-Mail aufgefordert werden, den Restbetrag zu entrichten.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß Tabelle 5.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 5 vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von E-Mails bei Zahlungseingang
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Zahlung: Teilzahlung*
|

|*Aktion*
|*Kunde &gt; E-Mail versenden*
| Auftrag: Teilzahlung erhalten;  +
Kunde
|====

[.subhead]
E-Mail-Vorlage anpassen

Passen Sie die <<crm/e-mails-versenden#, E-Mail-Vorlage>> *Teilzahlung erhalten* mit Ihren Unternehmensdaten an, bevor Sie die Ereignisaktion einrichten. <<tabelle-email-template-zahlungseingang>> erläutert relevante Template-Variablen für die E-Mail-Vorlage *Teilzahlung erhalten*.

[[tabelle-email-template-zahlungseingang]]
.E-Mail-Template-Variablen für Zahlungseingänge
[cols="1,3"]
|====
|Template-Variablen |Erläuterung

|*$PaidAmount*
|Gesamtbetrag der eingegangenen Zahlungen

|*$OpenAmount*
|Fehlbetrag

|*$InvoiceTotal*
|Rechnungsbetrag
|====

[#160]
=== Überzahlungen bearbeiten

Wenn ein Auftrag überbezahlt wurde, erhält der Auftrag den Status 3.2 (In Warteposition). So können Sie vor dem Versand mit dem Kunden noch klären, wieso er zu viel bezahlt hat, oder ihm den zu viel gezahlten Betrag zurückzahlen.

[#170]
== Zahlungseingänge auf der Startseite anzeigen

Auf der Startseite Ihres plentymarkets Backends können Sie das Element *Zahlungen* hinzufügen. In diesem Element finden Sie Informationen zu unzugeordneten Zahlungen sowie alle Zahlungseingänge von gestern und heute. Wenn Sie auf die Anzahl der Zahlungen klicken, gelangen Sie direkt zur Übersicht über die Zahlungen. Möchten Sie dieses Element nicht auf Ihrer Startseite verwenden, gelangen Sie über *Aufträge » Zahlungsverkehr* und durch die Verwendung der Filter in der Suche zu den gleichen Ergebnissen.

Es empfiehlt sich, vor der Auftragsbearbeitung einen Blick auf die unzugeordneten Zahlungen zu werfen. Prüfen Sie, ob Zahlungseingänge aus *Vorkasse* darunter sind, die aufgrund von Betrag und Buchungstext zweifelsfrei einem Auftrag zugeordnet werden können. Dies erspart Ihren Kunden längere Wartezeiten und Ihnen unliebsame Reklamationen.

Die unzugeordneten Zahlungen sollten Sie mindestens einmal wöchentlich bearbeiten und bereinigen, damit Ihnen der Überblick im Tagesgeschäft nicht verloren geht. Wie Sie nicht zugeordnete Zahlungen und Buchungen den Aufträgen zuweisen, erfahren Sie unter <<payment/zahlungen-verwalten#70, Zahlungen zuordnen>>.

[TIP]
.Tipp
====
Zahlungen von SOFORT Überweisung werden unmittelbar nach dem Zahlungsvorgang per Schnittstelle bestätigt, tauchen dann aber erneut als Bankbuchungen im System auf. Diese Bankbuchungen können Sie ohne Bedenken aus der Liste der unzugeordneten Zahlungen löschen, da den Aufträgen die Zahlung ja bereits zugewiesen wurde.
====
