= Zahlungsarten verwalten
:lang: de
include::{includedir}/_header.adoc[]
:description: Payment in plentymarkets: Richte Zahlungsarten in deinem plentymarkets System ein und aktiviere diese.
:position: 10
:url: payment/zahlungsarten-verwalten
:id: MVDQHNC
:keywords: Zahlungsart, Zahlungsarten, Schnittstellen, Kundenklassen, Marktplatz-Zahlungsart, Standardzahlungsart, Standard-Zahlungsart, SSL, Verschlüsselung, SSL-Verschlüsselung, Rabatt, Gastbestellung, Zahlungseingang, Warenbestand, Ceres, Plugin, plentyMarketplace, Marketplace
:author: team-order-payment

Zahlungsarten werden über Plugins eingebunden. Die einzelnen Payment-Plugins sowie Anleitungen zur Einrichtung findest du im entsprechenden Bereich des link:https://marketplace.plentymarkets.com/plugins/payment[plentyMarketplace^]{nbsp}icon:external-link[].
Auf dieser Handbuchseite erfährst du, wie du Zahlungsarten verwaltest und welche Einstellungen du vornimmst. Weiterhin findest du eine Übersicht der Marktplatz-Zahlungsarten. Eine detaillierte Beschreibung zur Aktivierung von Marktplatz-Zahlungsarten findest du auf den Handbuchseiten der <<maerkte#, Marktplätze>>.

[#25]
== Standard-Zahlungsart festlegen

Gehe wie im Folgenden beschrieben vor, um die Zahlungsart festzulegen, die standardmäßig im Bestellvorgang in deinem Webshop voreingestellt ist.

[.instruction]
Standard-Zahlungsart festlegen:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Aufträge*.
. Wähle unter *Standard-Zahlungsart* eine Zahlungsart aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#30]
== Zahlungsart in Kundenklasse erlauben

In den Grundeinstellungen deiner Kundenklassen müssen Zahlungsarten erlaubt sein. Diese Einstellungen betreffen z.B. auch die *Standard-Endkunden*. Neue Zahlungsarten müssen den erlaubten Zahlungsarten hinzugefügt werden. Genauso kannst du hier Zahlungsarten für bestimmte Kundenklassen ausschließen, indem du die Zahlungsarten aus der Liste entfernst. Prüfe die Einstellungen unter *Erlaubte Zahlungsarten* deiner Kundenklassen, nachdem du eine neue Zahlungsart in deinem System eingerichtet hast. Weitere Details dazu findest du auf der Handbuchseite <<crm/kontakte-verwalten#15, Kundenklassen>>.

[TIP]
.SSL-Zertifikat und Verschlüsselung
====
Wir empfehlen dir grundsätzlich, wenn du mit Zahlungs- und Kundendaten arbeiten, eine <<business-entscheidungen/systemadministration/ssl-zertifikat_bestellen#, SSL-Verschlüsselung>> für deinen Webshop. Für Zahlungsarten, die mit einem iframe arbeiten, ist dies zwingend.
====

[#50]
== Rabatt auf Zahlungsart gewähren

Du kannst für deine Kund:innen Rabatt auf Zahlungsarten gewähren. Dies ist eine Einstellung in den Kundenklassen, die es ermöglicht im Webshop einen Rabatt auf bestimmte Zahlungsarten anzubieten. Wie du einen Rabatt auf eine Zahlungsart in einer Kundenklasse festlegst, erfährst du im Kapitel <<crm/kontakte-verwalten#28, Rabatt auf Zahlungsart einrichten>>.

[#60]
==  Versand ohne Zahlungseingang

Bei einigen Zahlungsarten, z.B. der Zahlung auf Rechnung, erfolgt der Versand bereits vor dem Zahlungseingang. Bei Beschränkung des <<warenwirtschaft/warenbestaende-verwalten#, Warenbestands>> auf Netto-Warenbestand prüft das System, ob Bestand vorhanden ist, und versetzt den Auftrag je nach Bestandsverfügbarkeit in den Status 4 oder 5. Hierfür im Menü <<auftraege/grundeinstellungen#, Einrichtung » Aufträge » Einstellungen>> die Einstellung *Statuswechsel auf 4 statt 5, wenn Warenbestand fehlt* auf *JA* setzen. Wenn keine Beschränkung des Warenbestands eingestellt ist, wird der Auftrag direkt zum Versand freigegeben, d.h. er wird in Status 5 versetzt.

Bei folgenden Zahlungsarten erfolgt der Versand vor dem Zahlungseingang:

*  Rechnung
*  Lastschrift
*  Nachnahme
*  Amazon

Beachte dazu auch die Handbuchseite <<warenwirtschaft/warenbestaende-verwalten#, Warenbestände>>.

[#70]
== Marktplatz-Zahlungsarten

Marktplatz-Zahlungsarten sind Zahlungsarten, die in Verbindung mit der Einrichtung eines Marktplatzes zur Kennzeichnung von Zahlungseingängen genutzt werden. Die Zahlungsarten der Marktplätze werden in der Regel nicht vollständig eingerichtet, sondern lediglich aktiviert. Ohne eine Aktivierung können Probleme bei der Zahlungsabwicklung auftreten. Wie du Marktplatz-Zahlungsarten aktivierst, erfährst du auf der jeweiligen Handbuchseite der Märkte. Eine Übersicht findest du in der nachfolgenden Tabelle.

.Übersicht über Marktplatz-Zahlungsarten
[cols="1,3"]
|====
|Zahlungsart |Erläuterung

| *Amazon*
|Zahlungsart für Aufträge, die über den Marktplatz Amazon in dein plentymarkets System importiert werden. Zahlungsart als Plugin im Marketplace herunterladen.

| *BOL.com*
|Zahlungsart für Aufträge, die über den Marktplatz bol.com in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/bol-com#650, BOL.com>> aktivieren.

| *Cdiscount*
|Zahlungsart für Aufträge, die über den Marktplatz Cdiscount in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/cdiscount#900, Cdiscount>> aktivieren.

| *Check24*
|Zahlungsart für den Marktplatz Check24. Zahlungsart <<maerkte/check24#700, Check24>> aktivieren.

| *eBay-Rechnungskauf*
|Zahlungsart für Kauf auf Rechnung bei eBay. Zahlungsart <<maerkte/ebay/ebay-einrichten#2250, eBay-Rechnungskauf>> aktivieren.

| *Flubit*
|Zahlungsart für Aufträge, die über den Marktplatz Flubit in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/flubit#370, Flubit>> aktivieren.

| *Fruugo*
|Zahlungsart für Aufträge, die über den Marktplatz Fruugo in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/fruugo#600, Fruugo>> aktivieren.

| *idealo Direktkauf*
|Zahlungsart für den Marktplatz idealo Direktkauf. Zahlungsart <<maerkte/idealo/idealo-einrichten#1100, idealo Direktkauf>> einrichten.

| *Neckermann Payment*
|Zahlungsart für den Marktplatz Neckermann.at. Zahlungsart <<maerkte/neckermann/neckermann-at-einrichten#1600, Neckermann.at>> aktivieren.

| *Netto*
|Zahlungsart für den Marktplatz Netto. Zahlungsart <<maerkte/plus-gartenxxl#400, Netto>> aktivieren.

| *OTTO Payment*
|Zahlungsart für die Schnittstelle OTTO. Zahlungsart <<maerkte/otto/otto-market425, OTTO Payment>> aktivieren.

| *PIXmania Payment*
|Zahlungsart für den Marktplatz PIXmania. Zahlungsart <<maerkte/pixmania#800, PIXmania>> aktivieren.

| *Rakuten*
|Zahlungsart für den Marktplatz Rakuten. Zahlungsart <<maerkte/rakuten/rakuten-einrichten#1500, Rakuten>> aktivieren.

| *real.de Payment*
|Zahlungsart für den Marktplatz real.de. Zahlungsart <<maerkte/real-de/real-de-einrichten#800, real.de>> aktivieren.

| *Shopgate Payment*
|Zahlungsart für den Marktplatz Shopgate. Zahlungsart <<maerkte/shopgate#450, Shopgate>> aktivieren.

| *Yatego Rechnung*
|Zahlungsart für den Marktplatz Yatego. Zahlungsart <<maerkte/yatego#900, Yatego Rechnung>> aktivieren.

| *Zalando Payment*
|Zahlungsart für den Marktplatz Zalando. Zahlungsart <<maerkte/zalando#800, Zalando Payment>> aktivieren.
|====
