= Zahlungsarten verwalten
:lang: de
include::{includedir}/_header.adoc[]
:description: Payment in plentymarkets: Richte Zahlungsarten in deinem plentymarkets System ein und aktiviere diese.
:position: 10
:url: payment/zahlungsarten-verwalten
:id: MVDQHNC
:keywords: Zahlungsart, Zahlungsarten, Schnittstellen, Marktplatz-Zahlungsart, Standardzahlungsart, Standard-Zahlungsart, SSL, Verschlüsselung, SSL-Verschlüsselung, Rabatt, Plugin, plentyMarketplace, Marketplace, plugin-zahlungsart, Zahlungsartenübersicht
:author: team-order-payment

Zahlungsarten werden über Plugins eingebunden. Die einzelnen Payment Plugins kannst du im entsprechenden Bereich des link:https://marketplace.plentymarkets.com/plugins/payment[plentyMarketplace^]{nbsp}icon:external-link[] herunterladen. Anleitungen zur Einrichtung findest du ebenfalls im Marketplace oder im Bereich <<payment/payment-plugins#, Payment Plugins>> im Handbuch. +
Auf dieser Handbuchseite erfährst du, welche Einstellungen für Zahlungsarten du beachten solltest. Weiterhin findest du eine <<payment/zahlungsarten-verwalten#65, Übersicht der Zahlungsarten in deinem System>> sowie der zur Verfügung stehenden <<payment/zahlungsarten-verwalten#70, Marktplatz-Zahlungsarten>>. Diese Zahlungsarten sind automatisch in deinem plentymarkets System verfügbar, sobald du ein aktives Konto für den entsprechenden Marktplatz hast.

[#25]
== Standard-Zahlungsart festlegen

Gehe wie im Folgenden beschrieben vor, um die Zahlungsart festzulegen, die standardmäßig im Bestellvorgang in deinem Webshop voreingestellt ist.

[.instruction]
Standard-Zahlungsart festlegen:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Aufträge*.
. Wähle unter *Standard-Zahlungsart* eine Zahlungsart aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#30]
== Zahlungsart in Kundenklasse erlauben

In den Grundeinstellungen deiner Kundenklassen müssen Zahlungsarten erlaubt sein. Diese Einstellungen betreffen z.B. auch die *Standard-Endkunden*. Neue Zahlungsarten müssen den erlaubten Zahlungsarten hinzugefügt werden. Genauso kannst du hier Zahlungsarten für bestimmte Kundenklassen ausschließen, indem du die Zahlungsarten aus der Liste entfernst. Prüfe die Einstellungen unter *Erlaubte Zahlungsarten* deiner Kundenklassen, nachdem du eine neue Zahlungsart in deinem System eingerichtet hast. Weitere Details dazu findest du auf der Handbuchseite <<crm/kontakte-verwalten#15, Kundenklassen>>.

[TIP]
.SSL-Zertifikat und Verschlüsselung
====
Wir empfehlen dir grundsätzlich, wenn du mit Zahlungs- und Kundendaten arbeiten, eine <<business-entscheidungen/systemadministration/ssl-zertifikat_bestellen#, SSL-Verschlüsselung>> für deinen Webshop. Für Zahlungsarten, die mit einem iframe arbeiten, ist dies zwingend.
====

[#50]
== Rabatt auf Zahlungsart gewähren

Du kannst für deine Kund:innen Rabatt auf Zahlungsarten gewähren. Dies ist eine Einstellung in den Kundenklassen, die es ermöglicht im Webshop einen Rabatt auf bestimmte Zahlungsarten anzubieten. Wie du einen Rabatt auf eine Zahlungsart in einer Kundenklasse festlegst, erfährst du im Kapitel <<crm/kontakte-verwalten#28, Rabatt auf Zahlungsart einrichten>>.

[#60]
==  Versand ohne Zahlungseingang

Bei einigen Zahlungsarten, z.B. der Zahlung auf Rechnung, erfolgt der Versand bereits vor dem Zahlungseingang. Bei Beschränkung des <<warenwirtschaft/warenbestaende-verwalten#, Warenbestands>> auf Netto-Warenbestand prüft das System, ob Bestand vorhanden ist, und versetzt den Auftrag je nach Bestandsverfügbarkeit in den Status 4 oder 5. Möchtest du diese Einstellung anwenden, setze im Menü <<auftraege/grundeinstellungen#, Einrichtung » Aufträge » Einstellungen>> die Einstellung *Statuswechsel auf 4 statt 5, wenn Warenbestand fehlt* auf *JA*. Ist für diese Einstellung *NEIN* ausgewählt, ist keine Beschränkung des Warenbestands eingestellt. Der Auftrag wird dann direkt zum Versand freigegeben, d.h. er wird in Status 5 versetzt.

Bei folgenden Zahlungsarten erfolgt der Versand vor dem Zahlungseingang:

*  Rechnung
*  Lastschrift
*  Nachnahme
*  Amazon

Beachte dazu auch die Handbuchseite <<warenwirtschaft/warenbestaende-verwalten#, Warenbestände>>.

[#65]
== Übersicht der Zahlungsarten im System

Im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* findest du eine Übersicht über die Zahlungsarten und deren IDs in deinem plentymarkets System. Standardmäßig werden dir hier die Plugin-Zahlungsarten angezeigt. Möchtest du alle im System vorhandenen Zahlungsarten einsehen, nutze den Toggle (icon:toggle-on[role="green"]) über der Tabelle.

In der Übersicht lassen sich keine Zahlungsarten aktivieren. Möchtest du Zahlungsarten in dein plentymarkets System einbinden und deinen Kund:innen zur Verfügung stellen, musst du das entsprechende Plugin im link:https://marketplace.plentymarkets.com/plugins/payment[plentyMarketplace^]{nbsp}icon:external-link[] herunterladen. Anleitungen zur Einrichtung findest du ebenfalls im Marketplace oder im Bereich <<payment/payment-plugins#, Payment Plugins>> im Handbuch.

[[table-payment-methods-overview]]
.Übersicht der Zahlungsarten
[cols="1,3"]
|====
|Tabellenspalte |Erläuterung

|*ID*
|Die eindeutige ID der Zahlungsart. +
Dies ist eine Standardspalte.

|*Zahlungsart*
|Der Name der Zahlungsart. +
Dies ist eine Standardspalte.

|*Suchbar im Backend*
|Ist eine Zahlungsart suchbar im Backend, wird sie an allen Stellen im System, an denen du eine Zahlungsart auswählen kannst, angezeigt. Zum Beispiel in Dropdown-Listen in Ereignisaktionen etc. +
icon:check-square[role="green"] = Die Zahlungsart ist suchbar im Backend. +
icon:minus-circle[role="red"] = Die Zahlungsart ist nicht suchbar im Backend. +
Dies ist eine Standardspalte.

|*Aktiv im Backend*
|Ist eine Zahlungsart im Backend aktiv, kann sie einem Auftrag bei manueller Auftragserstellung zugewiesen werden. Zudem ist sie auch suchbar im Backend, d.h. sie wird an allen Stellen im System, an denen du eine Zahlungsart auswählen kannst, angezeigt. Zum Beispiel in Dropdown-Listen in Ereignisaktionen etc. +
icon:check-square[role="green"] = Die Zahlungsart ist im Backend aktiv. +
icon:minus-circle[role="red"] = Die Zahlungsart ist nicht im Backend aktiv. +
Dies ist eine Standardspalte.

|*pluginKey* und *paymentKey*
|Dies sind eindeutige Werte, mit denen man eine Zahlungsart systemweit identifizieren kann. Sie werden beim Registrieren einer Zahlungsart durch die Entwickler:in bestimmt. Nutzbar sind diese Werte vor allem für Entwickler:innen, z.B. wenn man die ID einer Zahlungsart aus dem System auslesen möchte. +
Dies ist keine Standardspalte.

|====

[#70]
== Marktplatz-Zahlungsarten

Marktplatz-Zahlungsarten sind Zahlungsarten, die in Verbindung mit der Einrichtung eines Marktplatzes zur Kennzeichnung von Zahlungseingängen genutzt werden. Diese Zahlungsarten sind automatisch in deinem plentymarkets System verfügbar, sobald du ein aktives Konto für den entsprechenden Marktplatz hast. Eine Übersicht findest du in der nachfolgenden Tabelle.

.Übersicht über Marktplatz-Zahlungsarten
[cols="1,3"]
|====
|Zahlungsart |Erläuterung

| *Amazon*
|Zahlungsart für Aufträge, die über den Marktplatz Amazon in dein plentymarkets System importiert werden.

| *BOL.com*
|Zahlungsart für Aufträge, die über den Marktplatz bol.com in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/bol-com#650, BOL.com>> aktivieren.

| *Cdiscount*
|Zahlungsart für Aufträge, die über den Marktplatz Cdiscount in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/cdiscount#900, Cdiscount>> aktivieren.

| *Check24*
|Zahlungsart für den Marktplatz Check24. Zahlungsart <<maerkte/check24#700, Check24>> aktivieren.

| *eBay-Rechnungskauf*
|Zahlungsart für Kauf auf Rechnung bei eBay. Zahlungsart <<maerkte/ebay/ebay-einrichten#2250, eBay-Rechnungskauf>> aktivieren.

| *Flubit*
|Zahlungsart für Aufträge, die über den Marktplatz Flubit in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/flubit#370, Flubit>> aktivieren.

| *Fruugo*
|Zahlungsart für Aufträge, die über den Marktplatz Fruugo in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/fruugo#600, Fruugo>> aktivieren.

| *idealo Direktkauf*
|Zahlungsart für den Marktplatz idealo Direktkauf. Zahlungsart <<maerkte/idealo/idealo-einrichten#1100, idealo Direktkauf>> einrichten.

| *Neckermann Payment*
|Zahlungsart für den Marktplatz Neckermann.at. Zahlungsart <<maerkte/neckermann/neckermann-at-einrichten#1600, Neckermann.at>> aktivieren.

| *Netto*
|Zahlungsart für den Marktplatz Netto. Zahlungsart <<maerkte/plus-gartenxxl#400, Netto>> aktivieren.

| *OTTO Payment*
|Zahlungsart für die Schnittstelle OTTO. Zahlungsart <<maerkte/otto/otto-market425, OTTO Payment>> aktivieren.

| *PIXmania Payment*
|Zahlungsart für den Marktplatz PIXmania. Zahlungsart <<maerkte/pixmania#800, PIXmania>> aktivieren.

| *Rakuten*
|Zahlungsart für den Marktplatz Rakuten. Zahlungsart <<maerkte/rakuten/rakuten-einrichten#1500, Rakuten>> aktivieren.

| *Kaufland.de Payment*
|Zahlungsart für den Marktplatz Kaufland.de. Zahlungsart <<maerkte/real-de/real-de-einrichten#800, Kaufland.de Payment>> aktivieren.

| *Shopgate Payment*
|Zahlungsart für den Marktplatz Shopgate. Zahlungsart <<maerkte/shopgate#450, Shopgate>> aktivieren.

| *Yatego Rechnung*
|Zahlungsart für den Marktplatz Yatego. Zahlungsart <<maerkte/yatego#900, Yatego Rechnung>> aktivieren.

| *Zalando Payment*
|Zahlungsart für den Marktplatz Zalando. Zahlungsart <<maerkte/zalando#800, Zalando Payment>> aktivieren.
|====
