= Zahlungsarten verwalten
:lang: de
include::{includedir}/_header.adoc[]
:description: Payment in plentymarkets: Richte Zahlungsarten in deinem plentymarkets System ein und aktiviere diese.
:position: 10
:url: payment/zahlungsarten-verwalten

[IMPORTANT]
.Einrichtung der Zahlungsarten nur für Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Zahlungsarten-Schnittstellen für Callisto Shops. In Ceres Shops werden die Zahlarten über Plugins eingebunden. Die einzelnen Payment-Plugins sowie Anleitungen zur Einrichtung findest du im entsprechenden Bereich des link:https://marketplace.plentymarkets.com/plugins/payment[plentyMarketplace^].
====

Auf dieser Handbuchseite erfährst du, wie du Zahlungsarten einrichtest. Weiterhin erhältst du einen Überblick über vertragsfreie Zahlungsarten, z.B. *Rechnung* oder *Vorkasse*, sowie weiterführende Informationen zu diesen Zahlungsarten. Die Einrichtung von Schnittstellen zu Zahlungsarten und Zahlungsanbietern ist jeweils auf einer eigenen Handbuchseite beschrieben, die du über den Themenbereich <<payment#, Payment>> erreichst. Schließlich findest du eine Übersicht der Marktplatz-Zahlungsarten. Eine detaillierte Beschreibung zur Aktivierung von Marktplatz-Zahlungsarten findest du auf den Handbuchseiten der <<maerkte#, Marktplätze>>.

[#10]
== Zahlungsart suchen

plentymarkets bietet dir ein breites Sortiment an vertragsfreien und vertragspflichtigen Zahlungsarten. Finde deine gesuchte Zahlungsart einfach über die Suchfunktion.

[.instruction]
Zahlungsart suchen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Gib in das Suchfeld den Namen des Zahlungsanbieters oder der Zahlungsart ein. +
→ Die Suchergebnisse werden aufgelistet.
. Klicke zum Öffnen auf den Zahlungsanbieter oder die Zahlungsart.

Die Symbole des Verzeichnisbaums haben folgende Bedeutung:

* *Häkchen* = Aktive Zahlungsart.
* *X* = Inaktive Zahlungsart. Inaktive Zahlungsarten können ein- und ausgeblendet werden.
* *Ordner* = Zahlungsanbieter, die mehrere Zahlungsarten anbieten. Aufklappen, um Zahlungsarten zu sehen.
* *Ordner mit Fragezeichen* = Ordner, die aktive und inaktive Zahlungsarten enthalten.

[#20]
==  Zahlungsart einrichten

Richte eine Zahlungsart ein wie im Folgenden beschrieben. Beachte, dass Zahlungsarten anschließend in einem anderen Menü für Kundenklassen erlaubt werden müssen. Weitere Informationen findest du im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.

[.instruction]
Zahlungsart einrichten:

.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
.  Aktiviere die Einstellung *Auch inaktive zeigen*.
.  Öffne den Ordner *DE* bzw. *International*.
.  Klicke auf die Zahlungsart. +
→ Das Tab *Einstellungen* wird geöffnet.
.  Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-einstellungen-zahlungsart>>.
.  Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* die Einstellungen.

[[tabelle-einstellungen-zahlungsart]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Sprache*
| Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit ist es möglich, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
| Namen eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
| Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
| Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
| Lieferland wählen. +
*_Hinweis:_* Lieferländer nur wählen, wenn die Zahlungsart im Webshop verwendet wird. Bei Marktplatz-Zahlungsarten keine Lieferländer wählen. Eine Marktplatz-Zahlungsart wird nicht im Webshop verwendet. Deshalb wird die Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig konfiguriert.

|*Mandant (Shop)*
| Mandant wählen.

|*Logo*
| Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG, JPG. Maximale Größe: 100 x 25 Pixel.

|*Priorität*
| Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. +
*Inland (Aufpreis)*: Pauschalen oder prozentualen Wert eingeben, der bei Aufträgen berücksichtigt wird, bei denen das Systemland gewählt wurde. Diese Kosten werden im Bestellvorgang bei der Wahl der Zahlungsart zum Auftrag addiert. Der Betrag fließt in die Gesamtsumme des Auftrags ein und wird nicht einzeln ausgewiesen. +
*Ausland (Aufpreis)*: Pauschalen oder prozentualen Wert eingeben, der bei Aufträgen berücksichtigt wird, bei denen nicht das Systemland gewählt wurde. Diese Kosten werden im Bestellvorgang bei der Wahl der Zahlungsart zum Auftrag addiert. Der Betrag fließt in die Gesamtsumme des Auftrags ein und wird nicht einzeln ausgewiesen. +
*Inland (Statistik)*: Pauschalen oder prozentualen Wert eingeben, der bei Aufträgen berücksichtigt wird, bei denen das Systemland gewählt wurde. +
*Ausland (Statistik)*: Pauschalen oder prozentualen Wert eingeben, der bei Aufträgen berücksichtigt wird, bei denen nicht das Systemland gewählt wurde. +
Weitere Informationen im Themenbereich <<basics/arbeiten-mit-plentymarkets/statistik#, Statistik>> und <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#80, Renner und Penner>>. +
*_Wichtig_*: Nicht in beide Felder einen Wert eingeben. Die Vertragsbedingungen des Zahlungsanbieters beachten. Einige Zahlungsanbieter untersagen die Weitergabe der Gebühren an den Endkunden.
|====

[TIP]
.Beispiel für pauschale und prozentuale Kosten
====
Wenn du einen Aufpreis eingeben möchtest, gib einen positiven Wert ein. Für einen Aufpreis von 1 Prozent gibst du einen prozentualen Wert von 1 ein. Für einen Aufpreis von 1 EUR gibst du einen pauschalen Wert von 1 ein. Wenn du einen Rabatt eingeben möchtest, gib einen negativen Wert ein, z.B. -2 für einen Rabatt von 2 Prozent. +
*Inland* entspricht dem unter *System » Systemeinstellungen » Einstellungen » Stammdaten* bei der Einstellung *Firmensitz für FiBu* festgelegten Land. Bei Mandanten (Shops) hast du auch die Möglichkeit, dein *Standard-Lieferland* automatisch als *Land des Firmensitzes* zu verwenden. Diese Einstellung findest du unter *System » Systemeinstellungen » Mandant » Mandant wählen » Bestellvorgang » Einstellungen*. Detailliertere Einstellungssmöglichkeiten von Rabatten auf Zahlungsarten sind über das Rabattsystem in plentymarkets möglich. Beachte dazu die Handbuchseite <<crm/kontakte-verwalten#25, Rabatt auf Zahlungsart>>.
====

[#25]
== Standard-Zahlungsart festlegen

Gehe wie im Folgenden beschrieben vor, um die Zahlungsart festzulegen, die standardmäßig im Bestellvorgang in deinem Webshop voreingestellt ist.

[.instruction]
Standard-Zahlungsart festlegen:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Aufträge*.
. Wähle unter *Standard-Zahlungsart* eine Zahlungsart aus der Dropdown-Liste.
. *Speichere* die Einstellungen.

[#30]
== Zahlungsart in Kundenklasse erlauben

In den Grundeinstellungen deiner Kundenklassen müssen Zahlungsarten erlaubt sein. Diese Einstellungen betreffen z.B. auch die *Standard-Endkunden*. Neue Zahlungsarten müssen den erlaubten Zahlungsarten hinzugefügt werden. Genauso kannst du hier Zahlungsarten für bestimmte Kundenklassen ausschließen, indem du die Zahlungsarten aus der Liste entfernst. Prüfe die Einstellungen unter *Erlaubte Zahlungsarten* deiner Kundenklassen, nachdem du eine neue Zahlungsart in deinem System eingerichtet hast. Weitere Details dazu findest du auf der Handbuchseite <<crm/kontakte-verwalten#15, Kundenklassen>>.

[TIP]
.SSL-Zertifikat und Verschlüsselung
====
Wir empfehlen dir grundsätzlich, wenn du mit Zahlungs- und Kundendaten arbeiten, eine <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Verschlüsselung>> für deinen Webshop. Für Zahlungsarten, die mit einem iframe arbeiten, ist dies zwingend.
====

[#50]
== Rabatt auf Zahlungsart gewähren

Der Rabatt auf eine Zahlungsart ist eine Art Skonto-Umsetzung in plentymarkets. Du gewährst Kunden damit einen Rabatt auf die Verwendung einer oder mehrerer Zahlungsarten. Wie du diese Rabattart einrichtest, erfährst du unter <<crm/kontakte-verwalten#25, Rabatt auf Zahlungsart>>. Angaben zu *Skonto* und *Valuta* kannst du auch direkt im <<crm/kontakte-verwalten#100, Datensatz eines Kontakts>> vornehmen.

[#40]
== Vertragsfreie Zahlungsarten

Als vertragsfreie Zahlungsarten werden hier Zahlungsarten bezeichnet, die du ohne Einrichtung von Schnittstellen in deinem Webshop verwenden kannst. Eine Übersicht findest du in der nachfolgenden Tabelle.

.Übersicht über vertragsfreie Zahlungsarten
[cols="1,3"]
|====
|Zahlungsart |Erläuterung

|*Bar bei Übergabe*
|Diese Zahlungsart verwenden, um Kunden die Möglichkeit zu bieten, im Falle einer Selbstabholung die Ware bar zu bezahlen. Den Zahlungseingang anschließend manuell im System buchen. Anschließend die Zahlung einem Auftrag zubuchen.

|*Barverkauf / EC-Karte*
|Die Zahlungsart *Barverkauf / EC-Karte* wird z.B. für das plentymarkets Kassensystem im stationären Ladengeschäft genutzt, damit Kunden bar oder mit EC-Karte zahlen können. Zahlungseingänge werden über ein EC-Terminal oder das plentymarkets POS an das Backend übermittelt.

|*Kreditkarte*
|Der Käufer hinterlegt seine Kreditkartendaten beim Verkäufer, z.B. im Webshop. Nach Eingang des Betrags wird die Ware verschickt. +
*_Wichtig_*: Für die Zahlungsart *Kreditkarte (manuelle Abwicklung)* ist aus Datenschutzgründen keine Abwicklung in einem plentymarkets Webshop vorgesehen. Im Webshop eine andere Zahlungsart oder eine für die Kunden individuell abgestimmte Lösung verwenden.

|*Lastschrift*
|Der Verkäufer erhält die Bankdaten des Käufers und die Erlaubnis, fällige Beträge vom Konto des Käufers einzuziehen. Die Zahlungsart global anbieten oder gezielt nur <<crm/kontakte-verwalten#100, für einzelne Kunden erlauben>>. +
*_Wichtig_*: Kunden können Lastschriften bei ihrer Bank widerrufen.

|*Nachnahme*
|Der Käufer bezahlt die Ware bei Erhalt. Der fällige Betrag wird vom Zusteller kassiert und quittiert. +
*_Wichtig_*: Bei Bestellungen per Nachnahme fallen Gebühren an.

|*Rechnung*
|Bei dieser Zahlungsart bestellt der Kunde die Ware auf Rechnung. Die Zahlung erfolgt nach Erhalt der Ware. Der Kunde erhält zum Begleichen des fälligen Betrags eine Rechnung mit den Bankdaten des Verkäufers. Zahlungseingänge werden <<payment/zahlungen-verwalten#30, importiert>> und anschließend Aufträgen im plentymarkets System zugeordnet. Die Zahlungsart global anbieten oder gezielt nur <<crm/kontakte-verwalten#100, für einzelne Kunden erlauben>>. Weitere Informationen zu dieser Zahlungsart unter <<payment/zahlungsarten-verwalten#55, Einstellungen für den Rechnungskauf vornehmen>>.

|*Vorkasse*
|Bei dieser Zahlungsart erhält der Käufer eine Nachricht mit den Daten zum Kauf sowie den Kontodaten des Verkäufers. Nachdem er die Ware bezahlt hat, die Zahlung ins plentymarkets System<<payment/zahlungen-verwalten#30, importieren>>. Im Anschluss erfolgt die Auslieferung. Mehr dazu, wie dem Kunden die Bankdaten zur Verfügung gestellt werden, unter <<payment/bankdaten-verwalten#, Bankdaten angeben>>.
|====

[.subhead]
Einstellungen für den Rechnungskauf vornehmen

In den erweiterten Einstellungen der Zahlungsart *Rechnung* legst du z.B. fest, dass Gastkunden nicht auf Rechnung bestellen können. Gehe wie im Folgenden beschrieben vor, um Einstellungen für die Zahlungsart *Rechnung* vorzunehmen.

[IMPORTANT]
.Erweiterte Einstellungen
====
Beachte, dass für die Verwendung der erweiterten Einstellungen des Rechnungskaufs in plentymarkets folgende Bedingungen erfüllt sein müssen:

* Verwendung des Standard-Designs Callisto (ab Version 3.5)
* Verwendung der plentymarkets CMS-Tools (ab Version 1.0.18)
* Nutzung des Individuellen Bestellvorgangs
====

[.instruction]
Einstellungen für den Rechnungskauf vornehmen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
. Klicke auf *Rechnung*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechsle in das Tab *Schnittstelle*.
. Klappen den Mandanten auf.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-einstellungen-zahlungsart-rechnung>>.
. *Speichere* die Einstellungen.

[[tabelle-einstellungen-zahlungsart-rechnung]]
.Einstellungen für die Zahlungsart *Rechnung*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Grundeinstellungen

|*Bankdaten anzeigen*
|Bankdaten im Bestellvorgang und in der Auftragshistorie anzeigen. Weitere Informationen dazu unter <<payment/bankdaten-verwalten#40, Bankdaten im Bestellvorgang anzeigen>>.

|*Verwendungszweck anzeigen*
|Verwendungszweck im Bestellvorgang und in der Auftragshistorie anzeigen. Weitere Informationen dazu unter <<payment/bankdaten-verwalten#40, Bankdaten im Bestellvorgang anzeigen>>.

2+|Erweiterte Einstellungen

|*Rechnungsadresse gleich Lieferadresse*
|Aktivieren, wenn Rechnungs- und Lieferadresse beim Kauf auf Rechnung übereinstimmen sollen.

|*Kauf auf Rechnung für Gastbestellungen verbieten*
|Aktivieren, um den Kauf auf Rechnung nur für angemeldete Kunden zu erlauben.

|*Mindestanzahl an Bestellungen*
|Mindestanzahl an Bestellungen eingeben, die ein Kunde mit einer anderen Zahlungsart abschließen muss, bevor der Kauf auf Rechnung verwendet werden kann.

|*Maximalbetrag für Kauf auf Rechnung*
|Betrag eingeben, der beim Kauf auf Rechnung nicht überschritten werden darf.

|*Mindestbetrag für Kauf auf Rechnung*
|Betrag eingeben, der beim Kauf auf Rechnung nicht unterschritten werden darf.
|====

[#60]
==  Versand ohne Zahlungseingang

Bei einigen Zahlungsarten, z.B. der Zahlung auf Rechnung, erfolgt der Versand bereits vor dem Zahlungseingang. Bei Beschränkung des <<warenwirtschaft/warenbestaende-verwalten#, Warenbestands>> auf Netto-Warenbestand prüft das System, ob Bestand vorhanden ist, und versetzt den Auftrag je nach Bestandsverfügbarkeit in den Status 4 oder 5. Hierfür im Menü <<auftraege/grundeinstellungen#, System » Systemeinstellungen » Aufträge » Einstellungen>> die Einstellung *Statuswechsel auf 4 statt 5, wenn Warenbestand fehlt* auf *JA* setzen. Wenn keine Beschränkung des Warenbestands eingestellt ist, wird der Auftrag direkt zum Versand freigegeben, d.h. er wird in Status 5 versetzt.

Bei folgenden Zahlungsarten erfolgt der Versand vor dem Zahlungseingang:

*  Rechnung
*  Lastschrift
*  Nachnahme
*  Amazon
*  Kreditkarte (manuelle Abwicklung)
*  Coupon
*  RatePAY Rechnung
*  MeinPaket Payments
*  Hitmeister Payment
*  PAYONE Nachnahme
*  PAYONE Rechnung

Beachte dazu auch die Handbuchseite <<warenwirtschaft/warenbestaende-verwalten#, Warenbestände>>.

[#70]
== Marktplatz-Zahlungsarten

Marktplatz-Zahlungsarten sind Zahlungsarten, die in Verbindung mit der Einrichtung eines Marktplatzes zur Kennzeichnung von Zahlungseingängen genutzt werden. Die Zahlungsarten der Marktplätze werden in der Regel nicht vollständig eingerichtet, sondern lediglich aktiviert. Ohne eine Aktivierung können Probleme bei der Zahlungsabwicklung auftreten. Wie du Marktplatz-Zahlungsarten aktivierst, erfährst du auf der jeweiligen Handbuchseite der Märkte. Eine Übersicht findest du in der nachfolgenden Tabelle.

.Übersicht über Marktplatz-Zahlungsarten
[cols="1,3"]
|====
|Zahlungsart |Erläuterung

|*Amazon*
|Zahlungsart für Aufträge, die über den Marktplatz Amazon in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/amazon/amazon-einrichten#4500, Amazon>> aktivieren.


|*Amazon Pay*
|Zahlungsart im Webshop für Kunden, die über den Marktplatz Amazon im Webshop einkaufen. Zahlungsart <<payment/zahlungsanbieter/amazon-pay#, Amazon Pay>> aktivieren.

|*Cdiscount*
|Zahlungsart für Aufträge, die über den Marktplatz Cdiscount in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/cdiscount#90, Cdiscount>> aktivieren.

|*eBay-Rechnungskauf*
|Zahlungsart für Kauf auf Rechnung bei eBay. Zahlungsart <<maerkte/ebay/ebay-einrichten#2250, eBay-Rechnungskauf>> aktivieren.

|*Flubit*
|Zahlungsart für Aufträge, die über den Marktplatz Flubit in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/flubit#, Flubit>> aktivieren.

|*Fruugo*
|Zahlungsart für Aufträge, die über den Marktplatz Fruugo in dein plentymarkets System importiert werden. Zahlungsart <<maerkte/fruugo#60, Fruugo>> aktivieren.

|*GartenXXL.de*
|Zahlungsart für den Marktplatz GartenXXL.de. Zahlungsart <<maerkte/plus-de/plus-gartenxxl einrichten#40, GartenXXL.de>> aktivieren.

|*Neckermann Payment*
|Zahlungsart für den Marktplatz Neckermann.at. Zahlungsart <<maerkte/neckermann/neckermann-at-einrichten#160, Neckermann.at>> aktivieren.

|*Otto Payment*
|Zahlungsart für den Marktplatz Otto. Zahlungsart <<maerkte/otto#30, OTTO>> aktivieren.

|*PIXmania Payment*
|Zahlungsart für den Marktplatz PIXmania. Zahlungsart <<maerkte/pixmania#80, PIXmania>> aktivieren.

|*Plus.de Payment*
|Zahlungsart für den Marktplatz Plus.de. Zahlungsart <<maerkte/plus-de/plus-gartenxxl einrichten#40, Plus.de Payment>> aktivieren.

|*Rakuten*
|Zahlungsart für den Marktplatz Rakuten. Zahlungsart <<maerkte/rakuten/rakuten-einrichten#150, Rakuten>> aktivieren.

|*real.de Payment*
|Zahlungsart für den Marktplatz real.de. Zahlungsart <<maerkte/real-de/real-de-einrichten#80, real.de>> aktivieren.

|*Shopgate Payment*
|Zahlungsart für den Marktplatz Shopgate. Zahlungsart <<maerkte/shopgate#60, Shopgate>> aktivieren.

|*Yatego Rechnung*
|Zahlungsart für den Marktplatz Yatego. Zahlungsart <<maerkte/yatego#80, Yatego Rechnung>> aktivieren.

|*Zalando Payment*
|Zahlungsart für den Marktplatz Zalando. Zahlungsart <<maerkte/zalando#80, Zalando Payment>> aktivieren.
|====

[#80]
== Rundungsdifferenzen

Manche Zahlungsanbieter verlangen die Angabe der Artikelmenge pro Artikelposition sowie den Einzelpreis auf zwei Stellen nach dem Komma genau. Wenn auf Artikel *Rabatte* gewährt werden, kann dies besonders bei größeren Artikelmengen bei Artikeln mit niedrigen Preisen pro Artikelposition zu Rundungsdifferenzen zwischen der Berechnung in plentymarkets und der Berechnung des Zahlungsanbieters führen. In solchen Fällen wird beim Zahlungsanbieter der Rabatt pro Einzelpreis des Artikels berechnet und dann auf die Artikelmenge hochgerechnet, im plentymarkets System wird der Rabatt jeweils auf die Gesamtmenge des Artikels angesetzt. <<tabelle-rundungsdifferenz-rabatte>> gibt dir eine genaue Übersicht über die Berechnung eines Rabatts von 5 Prozent für größere Artikelmengen und zu welchen Ergebnissen bzw. Rundungsdifferenzen dies jeweils führt, wenn einmal der Rabatt pro Einzelartikel berechnet wird – die Berechnungsweise des Zahlungsanbieters – und einmal der Rabatt pro Summe des rabattierten Warenwertes angerechnet wird – die Berechnungsweise von plentymarkets.

[[tabelle-rundungsdifferenz-rabatte]]
.Rundungsdifferenzen bei Rabatten
[cols="a,a,a,a,a,a,a,a,a"]
|====
|Menge |Einzel- +
preis |Gesamt- +
preis |Einzelpreis abzüglich 5% Rabatt |Rabattierter Einzelpreis, gerundet |Zahlungs- +
anbieter |Gesamtpreis abzüglich 5% Rabatt |Rabattierter Gesamtpreis, gerundet |plentymarkets

|*10*
|2,25
|22,50
|2,25 - 0,1125 = 2,1375
|2,14
|21,40
|22,50 - 1,125 = 21,375
|21,38
|

|*15*
|3,75
|56,25
|3,75 - 0,1875 = 3,5625
|3,56
|53,40
|56,25 - 1,875 = 53,4375
|53,44
|

|
|
|
|
|*Summe:*
|*74,80*
|*Summe:* *74,8125* (Basis für plentymarkets)
|*Summe:*
|*74,81*
|====

In diesem Fall beträgt die gesamte Differenz 1 Cent. Nur der erste Artikel ergäbe eine Differenz von 2 Cent, nur der zweite Artikel eine Differenz von 4 Cent.

[WARNING]
.Transaktion verweigert
====
Bei solchen Differenzen, auch wenn sie gering sind, ist es möglich, dass der Zahlungsanbieter die Transaktion verweigert.
====

[TIP]
.Alternative Zahlungsanbieter oder Artikelpakete anbieten
====
Bei derartigen Problemen kannst du alternative Zahlungsarten anbieten, bei denen dieses Problem nicht auftritt, oder ggf. anbieten, den jeweiligen Zahlungsanbieter bezüglich einer Lösung zu kontaktieren. Alternativ kannst du für Artikel, bei denen diese Rundungsdifferenz auftritt (Artikel mit niedrigem Preis) <<artikel/artikel-verwalten#920, Artikelpakete>> anbieten, um diesen Effekt zu vermeiden.
====
