= bol.com
:lang: de
include::{includedir}/_header.adoc[]
:keywords: bol.com, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz bol.com in Ihrem plentymarkets System ein.
:position: 28

Der niederländische Online-Marktplatz **link:http://bol.com[bol.com^]** hat sich zum führenden Online-Marktplatz der Benelux entwickelt und vertreibt eine breite Angebotspalette inklusive Elektronik, Multimedia, Spielzeug etc.

[#100]
== Bei bol.com registrieren

Bevor Sie bol.com in plentymarkets einrichten, müssen Sie sich auf **link:https://bol.com.[bol.com^]**. registrieren

[#200]
== bol.com in plentymarkets einrichten

Um Artikel auf bol.com anzubieten, richten Sie bol.com in plentymarkets ein. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
bol.com in plentymarkets einrichten:

. Öffnen Sie das Menü **System » Märkte » bol.com » Einstellungen**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen.

.Grundeinstellungen des Marktplatzes bol.com
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Automatischen Datenaustausch aktivieren**
|Ist der Datenaustausch aktiviert, findet ein täglicher Artikelexport, ein stündlicher Bestandsabgleich und ein stündlicher Auftragsimport statt.

|**öffentlicher API-Schlüssel**
|API-Schlüssel eintragen, wie von bol.com erhalten.

|**privater API-Schlüssel**
|API-Schlüssel eintragen, wie von bol.com erhalten.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* Auftragsimport alle 20 Minuten

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit bol.com verknüpfen können, muss im Menü **System » Aufträge » Auftragsherkunft** die Auftragsherkunft bol.com aktiviert werden.

[.instruction]
Auftragsherkunft für bol.com aktivieren:

. Öffnen Sie das Menü **System » Aufträge » Auftragsherkunft**.
. Setzen Sie bei **bol.com** ein Häkchen.
. **Speichern** Sie die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf bol.com verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID**>> im Tab **Verfügbarkeit** aktiviert werden.

[.instruction]
Artikelverfügbarkeit für bol.com einstellen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen**.
. Aktivieren Sie die Hauptvariante im Bereich **Verfügbarkeit**.
. Wechseln Sie in das Tab **Verfügbarkeit**.
. Klicken Sie im Bereich **Märkte** in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktivieren Sie die Option **bol.com**.
. Klicken Sie auf **Hinzufügen**. +
→ Der Marktplatz wird hinzugefügt.
. **Speichern** Sie die Einstellungen. +
→ Der Artikel ist auf bol.com verfügbar.

Die Verfügbarkeit für Varianten kann im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit** individuell angepasst werden.

Beachten Sie, dass alle Artikeldaten in englisch zu bol.com exportiert werden müssen.

[#400]
== Kategorien verknüpfen

Verknüpfen Sie Ihre Webshop-Kategorien mit den Kategorien von bol.com, damit Ihre Artikel in diesen bol.com-Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffnen Sie das Menü **System » Märkte » bol.com » Kategorieverknüpfung**.
. Klicken Sie auf **Suchen**.  +
→ Das Fenster **Kategorie wählen** wird geöffnet.
. Wählen Sie die bol.com-Kategorie, die am besten zu Ihrer Webshop-Kategorie passt.
. Klicken Sie auf **Übernehmen**. +
→ Die Bezeichnung der bol.com-Kategorie und der Kategoriepfad werden angezeigt.
. Wenn Sie die Bezeichnung der bol.com-Kategorie bereits kennen, geben Sie sie in das Feld **Marktplatzkategorie** ein, um sie mit Ihrer Webshop-Kategorie zu verknüpfen.
. **Speichern** Sie die Einstellungen.

[#450]
== Merkmale erstellen

Als nächstes erstellen Sie <<artikel/artikel-verwalten#480, **Merkmale**>> und verknüpfen diese mit den bol.com-Merkmalen.

[.instruction]
Merkmal erstellen:

. Öffnen Sie in das Menü **System » Artikel » Merkmale**.
. Öffnen Sie das Tab **Neues Merkmal**.
. Geben Sie unter **Backendname** einen Namen für das Merkmal ein.
. Wählen Sie aus dem Dropdown-Menü **Sprache** für Niederländisch **nl**.
. Geben Sie in das Feld **Name** den niederländischen Namen des Merkmals ein.
. Wählen Sie aus dem Dropdown-Menü im Feld **Merkmaltyp** die Option **Text**.
. Tragen Sie in der Zeile **bol.com-Merkmal** das bol.com-Merkmal ein.
. **Speichern** Sie die Einstellungen.

**bol_fulfillment** ist ein Pflichtfeld für den Angebotsexport. Dabei geben Sie an, ob der Artikel direkt von Ihnen oder von bol.com versendet wird. Tragen Sie dazu in der Zeile **bol.com-Merkmal** das bol.com-Merkmal **bol_filfillment** ein.

Wenn Sie gebrauchte Artikel über bol.com verkaufen möchten, müssen Sie dies über das Merkmal **bol_used** angeben. Tragen Sie dazu in der Zeile **bol.com-Merkmal** das bol.com-Merkmal **bol_used** ein.

[#500]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft bol.com einen Verkaufspreis festzulegen. Dieser Preis wird auf bol.com angezeigt.

[.instruction]
Verkaufspreis für bol.com festlegen:

. Öffnen Sie das Menü **System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen**.
. Setzen Sie ein Häkchen bei der Herkunft **bol.com**.
. **Speichern** Sie die Einstellungen.

[#600]
== Artikel- und Angebotsexport einrichten

In diesem Kapitel wird beschrieben, wie Sie Ihre Artikel und Angebote zu bol.com übertragen. Der Export erfolgt über den elastischen Export. Zunächst legen Sie das Datenformat BolItemExport und BolOfferExport an und übermitteln im Anschluss die CSV-Dateien zu bol.com. Beide Dateien müssen an bol.com übergeben werden, damit Ihre Artikel bei bol.com verkauft werden können.

Folgende Pflichtfelder müssen für den Artikelexport mitgegeben werden:

* EAN
* SKU
* Name
* Kategorien
* Artikelbeschreibung
* Bild
* Hersteller

Folgende Pflichtfelder müssen für den Angebotsexport mitgegeben werden:

* EAN
* SKU
* Bestand
* Preis
* Artikelzustand
* Versandverfügbarkeit
* Versand durch

[.instruction]
Export einrichten:

. Öffnen Sie das Menü **Datenaustausch » Export » Elastischer Export**.
. Klicken Sie auf **Neuer Export**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 2
. Nehmen Sie weitere Einstellungen für Artikelfilter und Formateinstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 5 auf der Handbuchseite <<basics/datenaustausch/daten-exportieren#60, **Daten exportieren**>>
. **Speichern** Sie die Einstellungen. +
→ Eine ID für das Exportformat wird vergeben und das Exportformat erscheint in der Übersicht **Exporte**.

.Einstellungen für Artikelexport
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

|**Name**
|Name eingeben. Unter diesem Namen erscheint das Exportformat in der Übersicht im Tab **Exporte**.

|**Typ**
|Typ aus dem Dropdown-Menü wählen. Aktuell ist nur die Auswahl **Artikel** verfügbar. Weitere Auswahlmöglichkeiten folgen.

|**Format**
|Format **BolItemExport** für den Artkelexport wählen oder **BolOfferExport** für den Angebotsexport aus dem Dropdown-Menü wählen.

|**Limit**
|Zahl eingeben. Wenn mehr als 10000 Datensätze an bol.com übertragen werden sollen, wird die Ausgabedatei für 24 Stunden nicht noch einmal neu generiert, um Ressourcen zu sparen.

|**Bereitstellung**
|**FTP** wählen.

|**Dateiname**, +
**Server**, +
**Port**, +
**Benutzername**, +
**Passwort**, +
**Pfad**
|Parameter eingeben. Die Zugangsdaten für den Server inklusive Passwort und Benutzername werden von bol.com zur Verfügung gestellt. Der Standard-FTP-Port ist **21**. Der Dateiname beim BolOfferExport hat den Aufbau &lt;SellerID&gt;.csv. Die Datei muss im Ordner **Inbound** hinterlegt werden.

|**Übertragung**
|**Täglich** für den Artikelexport wählen, da bol.com nur maximal 4 Exporte pro Tag zulässt. **Stündlich** für den Angebotsexport.
|====

[#700]
== Versandbestätigungen automatisch senden

Richten Sie eine **<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>** ein, um Versandbestätigungen automatisch an bol.com zu senden, nachdem ein Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **System » Aufträge » Ereignisaktionen**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 3.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 3 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an bol.com
[cols="a,a,a"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Auftragsänderung: Warenausgang gebucht**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|**bol.com**

|**Aktion**
|**Versand &gt; Versandbestätigung an bol.com senden**
|
|====

[#900]
== Retourenstatus automatisch senden

Richten Sie eine **<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>** ein, um bol.com automatisch über den Status einer Retoure zu informieren. Bei Retouren muss ein Status an bol.com übertragen werden. Folgende Stornierungsgründe können an bol.com übertragen werden:

* Retoure erhalten
* Repariert oder ersetzt
* Retoure unvollständig
* Rückerstattung ohne Rücksendung

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **System » Aufträge » Ereignisaktionen**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 5.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 5 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Retourenstatus an bol.com
[cols="a,a,a"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Neue Retoure**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Retoure**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|**bol.com**

|**Aktion**
|**Auftrag &gt; Retourenstatus an bol.com senden**
|**Status wählen**
|====

[#900]
== Stornierungen automatisch senden

Richten Sie eine **<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>** ein, um bol.com automatisch über Stornierungen zu informieren. Bei Stornierungen muss ein Grund für die Stornierung an bol.com übertragen werden. Erstellen Sie im Menü **<<auftragsabwicklung/auftraege/auftraege-verwalten#, System » Aufträge » Auftragsstatus>>** ggf. zusätzliche Auftragsstatus. Folgende Stornierungsgründe können an bol.com übertragen werden:

* Artikel nicht vorrätig
* Stornierung durch Kunden

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **System » Aufträge » Ereignisaktionen**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 6.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 6 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an bol.com
[cols="a,a,a"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Statuswechsel: [8.1] Storniert durch Kunden**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|**bol.com**

|**Aktion**
|**Auftrag &gt; Stornierung an bol.com senden**
|**Stornierung durch Kunden**
|====

[#1000]
== API-Log abrufen

Im Menü **<<basics/datenaustausch/api-log#, Datenaustausch » API-Log>>** finden Sie eine Historie über Vorgänge, die über die bol.com-Schnittstelle ausgeführt wurden.

[.instruction]
API-Log abrufen:

.  Öffnen Sie das Menü **Datenaustausch » API-Log » Tab: API-Log**.
.  Wählen Sie das Format **bol.com** aus dem Dropdown-Menü **Vorgang**.
.  Wählen Sie ggf. ein **Datum**, um nur Einträge eines bestimmten Tages zu erhalten.
.  Klicken Sie auf **Suchen**, um die Suche auszuführen. +
→ Die Vorgänge werden angezeigt.
