= bol.com
:lang: de
include::{includedir}/_header.adoc[]
:keywords: bol.com, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz bol.com in Ihrem plentymarkets System ein.
:position: 70

Der niederländische Online-Marktplatz link:http://bol.com[bol.com^] hat sich zum führenden Online-Marktplatz der Benelux entwickelt und vertreibt eine breite Angebotspalette inklusive Elektronik, Multimedia, Spielzeug etc.

[#100]
== Bei bol.com registrieren

Bevor Sie bol.com in plentymarkets einrichten, müssen Sie sich auf link:https://bol.com.[bol.com^]. registrieren

[#200]
== bol.com in plentymarkets einrichten

Um Artikel auf bol.com anzubieten, richten Sie bol.com in plentymarkets ein. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
bol.com in plentymarkets einrichten:

. Öffnen Sie das Menü *System » Märkte » bol.com » Einstellungen*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<grundeinstellungen-bol>>.
. *Speichern* Sie die Einstellungen.

[[grundeinstellungen-bol]]
.Grundeinstellungen des Marktplatzes bol.com
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Automatischen Datenaustausch aktivieren*
|Ist der Datenaustausch aktiviert, findet ein täglicher Artikelexport, ein stündlicher Bestandsabgleich und ein stündlicher Auftragsimport statt.

|*öffentlicher API-Schlüssel*
|API-Schlüssel eintragen, wie von bol.com erhalten.

|*privater API-Schlüssel*
|API-Schlüssel eintragen, wie von bol.com erhalten.

|*Mandant*
|Mandanten wählen. Aufträge werden beim Auftragsimport mit diesem Mandanten verknüpft.

|*Lagerauswahl*
|Bestandsmenge für den Angebotsexport wählen. Eine der folgenden Optionen wählen: +
*Summe der Bestandsmengen aller Vertriebslager verwenden* +
*Hauptlager des Artikels verwenden* +
*Lager auswählen* = Ein oder mehrere Lager wählen. +
*Wichtig:* Die Option *Lagerauswahl* beeinflusst den Artikelexport. Wenn ein Artikel nicht mit den hier gewählten Lagern verknüpft ist, wird dieser Artikel nicht exportiert.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* Auftragsimport stündlich

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit bol.com verknüpfen können, muss im Menü *System » Aufträge » Auftragsherkunft* die Auftragsherkunft bol.com aktiviert werden.

[.instruction]
Auftragsherkunft für bol.com aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Auftragsherkunft*.
. Setzen Sie bei *bol.com* ein Häkchen.
. *Speichern* Sie die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf bol.com verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für bol.com einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktivieren Sie die Option *bol.com*.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen. +
→ Der Artikel ist auf bol.com verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

Beachten Sie, dass alle Artikeldaten in niederländisch zu bol.com exportiert werden müssen.

[#400]
== Kategorien verknüpfen

Verknüpfen Sie Ihre Webshop-Kategorien mit den Kategorien von bol.com, damit Ihre Artikel in diesen bol.com-Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffnen Sie das Menü *System » Märkte » bol.com » Kategorieverknüpfung*.
. Klicken Sie auf *Suchen*.  +
→ Das Fenster *Kategorie wählen* wird geöffnet.
. Wählen Sie die bol.com-Kategorie, die am besten zu Ihrer Webshop-Kategorie passt.
. Klicken Sie auf *Übernehmen*. +
→ Die Bezeichnung der bol.com-Kategorie und der Kategoriepfad werden angezeigt.
. Wenn Sie die Bezeichnung der bol.com-Kategorie bereits kennen, geben Sie sie in das Feld *Marktplatzkategorie* ein, um sie mit Ihrer Webshop-Kategorie zu verknüpfen.
. *Speichern* Sie die Einstellungen.

[#450]
== Merkmale erstellen

Als nächstes erstellen Sie <<artikel/artikel-verwalten#480, Merkmale>> und verknüpfen diese mit den bol.com-Merkmalen. Die passenden Merkmale zu einer bol.com-Kategorie entnehmen Sie der bol.com-Datei Datamodel. Die bol.com Datamodel-Datei können Sie link:https://developers.bol.com/datamodel/[hier^] herunterladen.

[.instruction]
Merkmal erstellen:

. Öffnen Sie in das Menü *System » Artikel » Merkmale*.
. Öffnen Sie das Tab *Neues Merkmal*.
. Geben Sie unter *Name (intern)* einen Namen für das Merkmal ein.
. Wählen Sie aus der Dropdown-Liste *Sprache* für Niederländisch *nl*.
. Geben Sie in das Feld *Name* den niederländischen Namen des Merkmals ein.
. Wählen Sie aus der Dropdown-Liste im Feld *Merkmaltyp* die Option *Text*.
. Tragen Sie in der Zeile *bol.com-Merkmal* das bol.com-Merkmal ein, wie aus der Datamodel-Datei in der Spalte *Attribute name* entnommen.
. *Speichern* Sie die Einstellungen.

*bol_fulfillment* ist ein Pflichtfeld für den Angebotsexport. Dabei geben Sie an, ob der Artikel direkt von Ihnen oder von bol.com versendet wird. Tragen Sie dazu in der Zeile *bol.com-Merkmal* das bol.com-Merkmal *bol_filfillment* ein.

Wenn Sie gebrauchte Artikel über bol.com verkaufen möchten, müssen Sie den gebrauchten Zustand der Artikel über das Merkmal *bol_used* angeben. Tragen Sie dazu in der Zeile *bol.com-Merkmal* das bol.com-Merkmal *bol_used* ein.

[#500]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft bol.com einen Verkaufspreis festzulegen. Dieser Preis wird auf bol.com angezeigt.

[.instruction]
Verkaufspreis für bol.com festlegen:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setzen Sie ein Häkchen bei der Herkunft *bol.com*.
. *Speichern* Sie die Einstellungen.

[#600]
== Artikel- und Angebotsexport einrichten

In diesem Kapitel wird beschrieben, wie Sie Ihre Artikel und Angebote zu bol.com übertragen. Artikel und Angebote werden über den elastischen Export zu bol.com übertragen. Zunächst legen Sie das Datenformat *BolItemExport* und *BolOfferExport* an und übermitteln im Anschluss die Dateien zu bol.com. Beide Dateien müssen an bol.com übergeben werden, damit Ihre Artikel bei bol.com verkauft werden können.

Folgende Pflichtfelder müssen für den Artikelexport mitgegeben werden:

* EAN
* SKU
* Name
* Kategorien
* Artikelbeschreibung
* Bild
* Hersteller

Folgende Pflichtfelder müssen für den Angebotsexport mitgegeben werden:

* EAN
* SKU
* Bestand
* Preis
* Artikelzustand
* Versandverfügbarkeit
* Versand durch

[.instruction]
Export einrichten:

. Öffnen Sie das Menü *Daten » Elastischer Export*.
. Klicken Sie auf *Neuer Export*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<einstellungen-artikelexport-bol>>.
. Nehmen Sie weitere Einstellungen für Artikelfilter und Formateinstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 5 auf der Handbuchseite <<basics/datenaustausch/export-import/daten-exportieren#60, Daten über dynamischen Export exportieren>>.
. *Speichern* Sie die Einstellungen. +
→ Eine ID für das Exportformat wird vergeben und das Exportformat erscheint in der Übersicht *Exporte*.

[[einstellungen-artikelexport-bol]]
.Einstellungen für Artikelexport
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

|*Name*
|Name eingeben. Unter diesem Namen erscheint das Exportformat in der Übersicht im Tab *Exporte*.

|*Typ*
|Typ *Artikel* aus der Dropdown-Liste wählen.

|*Format*
|Format *BolItemExport* für den Artkelexport wählen oder *BolOfferExport* für den Angebotsexport aus der Dropdown-Liste wählen.

|*Limit*
|Zahl eingeben. Wenn mehr als 10000 Datensätze an bol.com übertragen werden sollen, wird die Ausgabedatei für 24 Stunden nicht noch einmal neu generiert, um Ressourcen zu sparen.

|*Bereitstellung*
|*FTPS* wählen.

|*Dateiname*, +
*Server*, +
*Port*, +
*Benutzername*, +
*Passwort*, +
*Pfad*
|Parameter eingeben. Die Zugangsdaten für den Server inklusive Passwort und Benutzername werden von bol.com zur Verfügung gestellt. Der Dateiname beim BolOfferExport hat den Aufbau &lt;SellerID&gt;.csv. Der Dateiname beim BolItemExport hat den Aufbau &lt;SellerID&gt;.txt. +
Die Datei für das Format *BolItemExport* muss im Ordner */SQUARE/feed* gespeichert werden. +
Die Datei für das Format *BolOfferExport* muss im Ordner */inbound* gespeichert werden.

|*Übertragung*
|*Täglich* für den Artikelexport wählen, da bol.com nur maximal 4 Exporte pro Tag zulässt. *Stündlich* für den Angebotsexport.
|====

[#650]
== Zahlungsart aktivieren

Aktivieren Sie die <<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsart>> *BOL.com*, wie im Folgenden beschrieben.

[.instruction]
bol.com-Zahlungsart aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
. Klicken Sie auf *BOL.com*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<einstellungen-zahlungsart-bol>>.
. Setzen Sie ein Häkchen bei der Option *Aktiv*.
. *Speichern* Sie die Einstellungen.

[[einstellungen-zahlungsart-bol]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit haben Sie die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
|Kein Lieferland wählen. +
Sie können die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig konfiguriert.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen finden Sie auf der Handbuchseite <<basics/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten finden Sie auf der Handbuchseite <<auftragsabwicklung/payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » CRM » Kundenklassen* aktivieren oder deaktivieren Sie *erlaubte Zahlungsarten*. +
Weitere Informationen finden Sie im Kapitel <<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen finden Sie auf der Handbuchseite <<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#700]
== Versandbestätigungen automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an bol.com zu senden, nachdem ein Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-versandbestätigung-bol>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-versandbestätigung-bol>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-versandbestätigung-bol]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an bol.com
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*bol.com*

|*Aktion*
|*Versand &gt; Versandbestätigung an bol.com senden*
|
|====

[#800]
== Retourenstatus automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um bol.com automatisch über den Status einer Retoure zu informieren. Bei Retouren muss ein Status an bol.com übertragen werden. Folgende Stornierungsgründe können an bol.com übertragen werden:

* Retoure erhalten
* Repariert oder ersetzt
* Retoure unvollständig
* Rückerstattung ohne Rücksendung

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-retourenstatus-bol>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-retourenstatus-bol>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-retourenstatus-bol]]
.Ereignisaktion zum automatischen Senden von Retourenstatus an bol.com
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*bol.com*

|*Aktion*
|*Auftrag &gt; Retourenstatus an bol.com senden*
|*Status wählen*
|====

[#900]
== Stornierungen automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um bol.com automatisch über Stornierungen zu informieren. Bei Stornierungen muss ein Grund für die Stornierung an bol.com übertragen werden. Erstellen Sie im Menü *System » Aufträge » Auftragsstatus* ggf. zusätzliche Auftragsstatus. Folgende Stornierungsgründe können an bol.com übertragen werden:

* Artikel nicht vorrätig
* Stornierung durch Kunden

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-stornierungen-bol>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-stornierungen-bol>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-stornierungen-bol]]
.Ereignisaktion zum automatischen Senden von Stornierungen an bol.com
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Statuswechsel: [8.1] Storniert durch Kunden*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*bol.com*

|*Aktion*
|*Auftrag &gt; Stornierung an bol.com senden*
|*Stornierung durch Kunden*
|====

[#1000]
== API-Log abrufen

Im Menü <<basics/datenaustausch/api-log#, Daten » API-Log>> finden Sie eine Historie über Vorgänge, die über die bol.com-Schnittstelle ausgeführt wurden.

[.instruction]
API-Log abrufen:

.  Öffnen Sie das Menü *Daten » API-Log » Tab: API-Log*.
.  Wählen Sie das Format *bol.com* aus der Dropdown-Liste *Vorgang*.
.  Wählen Sie ggf. ein *Datum*, um nur Einträge eines bestimmten Tages zu erhalten.
.  Klicken Sie auf *Suchen*, um die Suche auszuführen. +
→ Die Vorgänge werden angezeigt.
