= Cdiscount
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Cdiscount, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz Cdiscount in Ihrem plentymarkets System ein.
:position: 80

Cdiscount war der erste elektronische Marktplatz Frankreichs und ist noch heute einer der beliebtesten und am meisten genutzten französischen Online-Verkaufsplattformen. Um Artikel auf Cdiscount anzubieten, muss der Artikelkatalog komplett auf Französisch vorliegen.

[#100]
== Bei Cdiscount registrieren

Bevor Sie Cdiscount in plentymarkets einrichten können, müssen Sie sich bei Cdiscount registrieren. Füllen Sie das link:https://seller.cdiscount.com/Account_creation.html[Registrierungsformular^] aus und übermitteln Sie Ihre Daten an Cdiscount. Ein Support-Mitarbeiter des Marktplatzes wird Sie kontaktieren, um die Registrierung zu verifizieren.

Bevor Sie die hier hinterlegten Daten in Ihrem plentymarkets System speichern, ändern Sie Ihr API-Passwort. Ein neues Passwort wird Ihnen in der Mailbox Ihres Händler-Backends zugesandt.

[#200]
== Cdiscount in plentymarkets einrichten

Nachdem Sie sich bei Cdiscount registriert haben, verwenden Sie die dort hinterlegten Daten, um den Marktplatz in plentymarkets einzurichten. Gehen Sie dazu wie im Folgenden beschrieben vor.

[IMPORTANT]
.Zugangsdaten
====
Verwenden Sie für die Konfiguration die API-Zugangsdaten. Die API-Zugangsdaten entsprechen nicht Ihren Zugangsdaten zum Händler-Backend von Cdiscount. Der Benutzername kann im Händler-Backend von Cdiscount eingesehen werden und das Passwort kann dort generiert oder angepasst werden.
====

[.instruction]
Cdiscount in plentymarkets einrichten:

. Öffnen Sie das Menü *System » Märkte » Cdiscount.com » Tab: Einstellungen*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<grundeinstellungen-cdiscount>>.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Zugangsdaten
====
Verwenden Sie für die Konfiguration die API-Zugangsdaten (Benutzername und Passwort). Der Benutzername hat das Suffix api. Die Login-Zugangsdaten sind dagegen zum Login in das Backend bei Cdiscount bestimmt.
====

[[grundeinstellungen-cdiscount]]
.Grundeinstellungen des Marktplatzes Cdiscount
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Produkterstellung anfordern*
|Aktivieren, um den automatischen Bestandsabgleich und Auftragsimport über die API-Schnittstelle zu aktivieren. Wenn die Option *Produkterstellung anfordern* nicht aktiviert wurde, werden lediglich Angebote zu bereits bestehenden Artikeln auf Cdiscount generiert.

|*Preise und Bestände aktualisieren und Auftragsimport aktivieren*
|Aktivieren, um den Artikelkatalog über die CSV-Schnittstelle zu übertragen. Der Bestandsabgleich wird weiterhin automatisch über die API-Schnittstelle übertragen. +
Ist diese Einstellung zusammen mit der Einstellung *Produkterstellung anfordern* aktiviert, findet der automatische Datenaustausch nur über die API-Schnittstelle statt.

2+|*Vertriebspartner-Information*

|*Firmenname*
|Firmenname eingeben, wie bei Cdiscount registriert (optional).

|*API-Benutzername*
|API-Benutzername eingeben, wie von Cdiscount erhalten.

|*API-Passwort*
|API-Passwort eingeben, wie von Cdiscount erhalten.

2+|*Auftragseinstellungen*

|*Cdiscount C Logistique-Auftragsstatus*
|Status für C Logistique-Aufträge. *Status [7] Warenausgang gebucht* ist hier standardmäßig voreingestellt. Dabei wird aber kein Bestand vom Lager abgezogen. Für zukünftige Auftragsimporte kann der Status nach Belieben geändert werden. Dabei ist jedoch zu beachten, dass sobald der Auftrag einmal in Status 7 war, der Auftrag dann nicht mehr in einen kleineren Status geschoben werden kann.

2+|*Artikeleinstellungen*

|*Artikelname*
|Wählen, welches Feld an Cdiscount als Artikelname übertragen wird.

|*Artikelkurzbeschreibung*
|Wählen, welches Feld an Cdiscount als Artikelkurzbeschreibung übertragen wird.

|*Artikelbeschreibung*
|Wählen, welches Feld an Cdiscount als Artikelbeschreibung übertragen wird.

|*Artikel-Marketing-Beschreibung*
|Wählen, welcher Text als Marketing-Beschreibung übertragen werden soll oder *Nicht übertragen* wählen.

|*Variantenmaße übertragen*
|Häkchen setzen, wenn die Variantenmaße übertragen werden sollen.

|*Bestandsmenge für Artikel ohne Bestandsbeschränkung und ohne positiven Nettowarenbestand*
|Wert eingeben. Die eingegebene Bestandsmenge wird übertragen, wenn der Artikel keine Bestandsbeschränkung und keinen positiven Nettowarenbestand hat.

|*Lager*
|Wählen, welches Lager verwendet werden soll. Ein Lager, mehrere Lager oder *Summe aus allen Lagern* wählen.

|*Mindestpreis*
|Wählen, welcher Preis der Mindestpreis für einen Artikel sein soll. +
*Wichtig:* Der Mindestpreis darf nicht der am Artikel gespeicherte Verkaufspreis sein, da in diesem Fall kein Mindestpreis übertragen wird.

2+|*Versandvorbereitungszeit (in Tagen)*

|*Standard-Versandvorbereitungszeit*
|*Pflichtfeld* +
Standard-Versandvorbereitungszeit in Tagen eingeben. Der hier eingegebene Wert wird zu Cdiscount übertragen und von Cdiscount um einen Wert auf Basis der Versandart erhöht. +
*Wichtig:* Nur Werte von 1-10 eingeben.

|*Verfügbarkeit 1-10*
|Verfügbarkeit von 1-10 eingeben. Die Verfügbarkeit entspricht der Variantenverfügbarkeit im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Bereich *Verfügbarkeit*. Der hier eingegebene Wert wird zu Cdiscount übertragen und von Cdiscount um einen Wert auf Basis der Versandart erhöht. +
Wenn hier kein Wert eingegeben wird, wird die *Standard-Versandvorbereitungszeit* zu Cdiscount übertragen.

2+|*Versandkosten*

|*Versandkosten aus der Versandkostenberechnung übernehmen*
|*Konfiguration 1* oder *Konfiguration 2* sowie *Zahlungsart* wählen. Die Standardversandkosten werden mit dieser Konfiguration an Cdiscount übertragen.  +
Die hier wählbaren Optionen sind die im Menü <<auftragsabwicklung/fulfillment/versand-vorbereiten#1700, System » Aufträge » Versand » Optionen » Tab: Versandkosten berechnen>> gewählten Einstellungen für Konfiguration 1 und Konfiguration 2.

|*Versandkosten überschreiben*
|Festpreis für den Versand eingeben. Die hier eingegebene Versandkosten werden anstatt der am Artikel hinterlegten Versandkosten an Cdiscount übermittelt.

|*Artikel-ID für die Ratengebühr*
|ID des Artikels, über den Kunden ggf. die Gebühr für den Ratenkauf, die Cdiscount erhebt, in Rechnung gestellt wird. Dazu einen Artikel in plentymarkets erstellen und die ID hier eingeben.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierten Funktionen bereit:

* Täglicher Artikelexport
* Stündlicher Bestandsabgleich
* Stündlicher Auftragsimport

Beim stündlichen Auftragsimport werden zunächst keine Rechnungs- und Lieferdaten von Cdiscount übermittelt. Der Auftrag bleibt solange in Status [3]. Es kann bis zu 48 Stunden dauern, bis die Rechnungs- und Lieferdaten übermittelt werden, da Cdiscount in dieser Zeit eine Bonitätsprüfung für den Endkunden durchführt.

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit Cdiscount verknüpfen können, muss im Menü *System » Aufträge » Auftragsherkunft* die Auftragsherkunft Cdiscount aktiviert werden.

[.instruction]
Auftragsherkunft für Cdiscount aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Auftragsherkunft*.
. Setzen Sie bei *Cdiscount* ein Häkchen.
. *Speichern* Sie die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf Cdiscount verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Cdiscount einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktivieren Sie die Option *Cdiscount*.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen. +
→ Der Artikel ist auf Cdiscount verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

Die Verfügbarkeit für mehrere Varianten kann entweder über die link:https://knowledge.plentymarkets.com/artikel/artikel-verwalten#330[Varianten-Gruppenfunktion^], die link:https://knowledge.plentymarkets.com/artikel/artikel-verwalten#330[Stapelverarbeitung^] oder den dynamischen Ex- und Import des Formats link:https://knowledge.plentymarkets.com/basics/datenaustausch/export-import/datenformate/variationmarketlink[VariationMarketLink^] bearbeitet werden.

[#350]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügen Sie, wenn nötig, marktplatzspezifische SKUs hinzu.

[IMPORTANT]
.Automatische SKU-Generierung
====
Wenn im Menü *System » Märkte » Cdiscount.com » Tab: Einstellungen* die Einstellung *Produkterstellung anfordern* aktiv ist, werden beim nächtlichen Übertragungsprozess für jede Variante, die exportiert wird automatisch eine SKU generiert, die der Varianten-ID entspricht.
====

[IMPORTANT]
.SKUs von bereits existierenden Produkten
====
Wenn bereits Angebote/Produkte auf Cdiscount manuell oder über andere Softwaresysteme angelegt wurden, dann können diese Produkte mit Varianten in plentymarkets verknüpft werden. Dazu muss in plentymarkets die Kennzeichnung als SKU hinterlegt werden, die bei Cdiscount im Händler-Backend bei dem jeweiligen Angebot/Produkt als *Your reference* zu finden ist.
====

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechseln Sie in das Tab *Verfügbarkeit*.
.  Klicken Sie im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
.  Wählen Sie die Herkunft *Cdiscount.com*.
.  Geben Sie die SKU ein.
.  Klicken Sie auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#400]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft Cdiscout einen Verkaufspreis festzulegen. Dieser Preis wird auf Cdiscount angezeigt.

[.instruction]
Verkaufspreis für Cdiscount festlegen:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setzen Sie ein Häkchen bei der Herkunft *Cdiscount*.
. *Speichern* Sie die Einstellungen.

link:https://knowledge.plentymarkets.com/artikel/artikel-verwalten#240[Verknüpfen^] Sie den Verkaufspreis im Anschluss mit den gewünschten Varianten falls noch nicht verknüpft.

==  Barcode festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft Cdiscount einen Barcode festzulegen. Dieser Barcode wird für die Variante  zu Cdiscount übertragen. Der Barcode muss vom Typ GTIN 13 sein.

[.instruction]
Barcode für Cdiscount festlegen:

.  Öffnen Sie das Menü *System » Artikel » Barcode » Barcode öffnen*.
.  Setzen Sie ein Häkchen bei der Herkunft *Cdiscount*.
. *Speichern* Sie die Einstellungen.

link:https://knowledge.plentymarkets.com/artikel/artikel-verwalten#250[Verknüpfen^] Sie den Barcode im Anschluss mit den gewünschten Varianten falls noch nicht verknüpft.

[#500]
== Kategorien verknüpfen

Um Ihre Kategorien mit denen von Cdiscount zu verknüpfen, laden Sie zunächst die Kategorieliste von Cdiscount herunter. Verknüpfen Sie dann Ihre eigenen Kategorien mit den passenden Cdiscount-Kategorien.

[.instruction]
Kategorieliste herunterladen:

. Öffnen Sie das Menü *System » Märkte » Cdiscount.com » Tab: Kategorieliste*.
. Klicken Sie auf das Zahnrad *Kategorieliste aktualisieren*. +
→ Die Kategorieliste wird mit Code und Kategorienamen unten angezeigt.

Die hier angezeigten Codes benötigen Sie, um Ihre Kategorien mit denen von Cdiscount zu verknüpfen. Gehen Sie dazu wie folgt vor.

[.instruction]
Kategorien verknüpfen:

. Öffnen Sie das Menü *System » Märkte » Cdiscount.com » Tab: Kategorieverknüpfung*.
. Geben Sie unter *Kategorieverknüpfung* den Code der zur Webshop-Kategorie passenden Cdiscount-Kategorie ein.
. *Speichern* Sie die Einstellungen.

[#600]
== Attribute verknüpfen

Wenn Sie <<artikel/artikel-verwalten#390, Attribute>> im plentymarkets System erstellt haben, müssen diese Attribute mit Cdiscount verknüpft werden. Nachfolgend wird beschrieben, wie Sie das Attribut Farbe mit Cdiscount verknüpfen. Verknüpfen Sie weitere Attribute auf die gleiche Weise.

[.instruction]
Attribute verknüpfen:

. Öffnen Sie das Menü *System » Artikel » Attribute*. +
→ Eine Übersicht aller erstellten Attribute wird geöffnet.
. Klappen Sie das Attribut *Farbe* auf.
. Wechseln Sie in das Tab *Marktplatzvariation*.
. Wählen Sie in der Dropdown-Liste *Marktplatz* die Option *Cdiscount.com*. +
→ Eine zusätzliche Dropdown-Liste *Cdiscount* wird angezeigt.
. Wählen Sie in der Dropdown-Liste *Cdiscount.com* das Attribut *Farbe*.
. Geben Sie die zu Ihren Attributwerten passenden Cdiscount-Attributwerte im Bereich Marktplatzvariation ein.
. *Speichern* Sie die Einstellungen.

[#700]
== Merkmale erstellen

Als nächstes erstellen Sie <<artikel/artikel-verwalten#480, Merkmale>> und verknüpfen die erstellten Merkmale mit den Cdiscount-Merkmalen. Beachten Sie, dass Ihre Merkmale hierfür auf Französisch erstellt sein müssen.

[.instruction]
Merkmal erstellen:

. Öffnen Sie in das Menü *System » Artikel » Merkmale*.
. Öffnen Sie das Tab *Neues Merkmal*.
. Geben Sie unter *Name (intern)* einen Namen für das Merkmal ein.
. Wählen Sie aus der Dropdown-Liste *Sprache* für Französisch *fr*.
. Geben Sie in das Feld *Name* den französischen Namen des Merkmals ein.
. Wählen Sie aus der Dropdown-Liste im Feld *Merkmaltyp* die Option *Text*.
. Wählen Sie aus der Dropdown-Liste im Feld *Cdiscount.com-Merkmal* das Cdiscount-Merkmal.
. *Speichern* Sie die Einstellungen.

[#800]
== Hersteller verknüpfen

Erstellen Sie nun Herstellerverknüpfungen, damit Ihre Artikel auf Cdiscount zum Verkauf angezeigt werden. Laden Sie zunächst die Herstellerliste von Cdiscount herunter und verknüpfen Sie dann Ihre eigenen Hersteller mit den passenden Cdiscount-Herstellern, indem Sie die Cdiscount-Hersteller-ID im System hinterlegen. Dabei entspricht die Cdiscount-Hersteller-ID dem Namen des Herstellers.

[.instruction]
Herstellerliste herunterladen:

. Öffnen Sie das Menü *System » Märkte » Cdiscount.com » Tab: Herstellerliste*.
. Klicken Sie auf *Herstellerliste aktualisieren*. +
→ Die Herstellerliste wird mit Code und Herstellernamen unten angezeigt.
. Markieren und kopieren Sie den Hersteller in die Zwischenablage.
. *Tipp:* Laden Sie die Herstellerliste als CSV-Datei herunter. Diese Datei können Sie gezielt nach Herstellern durchsuchen. +
Klicken Sie dazu im Menü *System » Märkte » Cdiscount.com » Tab: Herstellerliste* auf *Herstellerliste als CSV Datei herunterladen*.

Gehen Sie nun wie folgt vor, um den Hersteller zu verknüpfen.

[.instruction]
Hersteller verknüpfen:

. Öffnen Sie das Menü *System » Artikel » Hersteller*.
. Öffnen Sie den Hersteller, den Sie mit Cdiscount verknüpfen möchten.
. Fügen Sie den Namen des Herstellers aus der Zwischenablage in das Feld *Cdiscount.com-ID* ein.
. *Speichern* Sie die Einstellungen.

[#900]
==  Zahlungsart aktivieren

Aktivieren Sie die <<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsart>> *Cdiscount*, wie im Folgenden beschrieben.

[.instruction]
Cdiscount-Zahlungsarten aktivieren:

.  Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
.  Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
.  Öffnen Sie den Ordner *International*.
.  Klicken Sie auf *Cdiscount*. +
→ Das Tab *Einstellungen* wird geöffnet.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<einstellungen-zahlungsart-cdiscount>>.
.  Setzen Sie ein Häkchen bei der Option *Aktiv*.
. *Speichern* Sie die Einstellungen.

[[einstellungen-zahlungsart-cdiscount]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Sprache*
| Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit haben Sie die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
| Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
| Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
| Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
| Kein Lieferland wählen. +
Sie können die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig konfiguriert.

|*Logo*
| Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
| Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
| Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben. +
Weitere Informationen finden Sie auf der Handbuchseite <<basics/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten finden Sie auf der Handbuchseite <<auftragsabwicklung/payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » CRM » Kundenklassen* aktivieren oder deaktivieren Sie *erlaubte Zahlungsarten*. +
Weitere Informationen finden Sie im Kapitel <<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen finden Sie auf der Handbuchseite <<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

==  Datenaustausch konfigurieren

Um die Schnittstelle so zu konfigurieren, dass der Artikelexport, der Bestandsabgleich und der Auftragsimport funktionieren, sind mindestens die Eingaben gemäß der folgenden Tabelle notwendig.

[IMPORTANT]
.Produkterstellung auf Cdiscount
====
Die Produkterstellung dient zur Anfrage der Aufnahme eines neuen Produktes in die Produktdatenbank von Cdiscount. Sobald eines Ihrer Produkte durch Cdiscount freigegeben und in die Produktdatenbank aufgenommen wurde, können Sie die Produktdaten für gewöhnlich nicht mehr weiter bearbeiten. Prüfen sie deshalb vor der Übertragung des Produktes, das wirklich alle Daten gepflegt haben, die für den erfolgreichen Verkauf wichtig sind. Die Checkliste dient lediglich zur Auflistung der Mindestanforderungen für die Produkterstellung.
====

[IMPORTANT]
.Angebotserstellung auf Cdiscount
====
Auf Cdiscount wird jedes angelegte Produkt in einer Datenbank abgespeichert. Jedes Produkt kann anhand mindestens einer EAN identifiziert werden. Die Kennzeichnung der Produkte mit EANs ermöglicht es Händlern, Angebote zu diesen Produkten zur Verfügung zu stellen. Im Vergleich zur vorherigen Produkterstellung ist der Konfigurationsaufwand wesentlich geringer und erleichtert den Einstieg bei Cdiscount. +
Sowohl die Erstellung als auch die Aktualisierung (Bestandsabgleich) der Angebote werden über eine Datei gesteuert. +
Die folgenden Checkliste listet die mindestens notwendigen Einstellungen auf, damit ein Artikel in dieser Datei übertragen wird.
====

[[pflichteinstellungen-cdiscount]]
.Pflichteinstellungen für Cdiscount
[cols="1,3"]
|====
| Einstellungsbereich  | Einstellungen

2+|*Angebotserstellung / Bestandsabgleich*

| Grundeinstellungen des Marktplatzes
a|
* *Preise und Bestände aktualisieren und Auftragsimport aktivieren* ist aktiviert.
* *API-Benutzername* ist eingetragen.
* *API-Passwort* ist eingetragen.
* *Versandvorbereitungszeit (in Tagen)* ist gesetzt.
* *Versandkosten aus der Versandkostenberechnung übernehmen* oder *Versandkosten überschreiben* ist konfiguriert.

| Konfiguration der Variante
a|
*  Die Variante ist *aktiv*
*  Die *Verfügbarkeit* der Variante wurde konfiguriert.
*  Ein *Verkaufspreis* ist konfiguriert und verknüpft.
*  Ein *Barcode* ist konfiguriert und verknüpft.
*  Eine *SKU* ist festgelegt worden.

2+|*Produkterstellung*

| Grundeinstellungen des Marktplatzes
a|
* *Preise und Bestände aktualisieren und Auftragsimport aktivieren* ist aktiviert.
* *API-Benutzername* ist eingetragen.
* *API-Passwort* ist eingetragen.

| Konfiguration des Artikels
a|
*  Die *Artikeltexte* sind in Französisch gepflegt.
*  Ein *Hersteller* ist am Artikel hinterlegt und mit Cdiscount verknüpft worden.

| Konfiguration der Variante bei Einzelartikeln
a|
*  Die Variante ist *aktiv*
*  Die *Verfügbarkeit* der Variante wurde konfiguriert.
*  Ein *Barcode* ist konfiguriert und verknüpft.
*  Eine *SKU* ist festgelegt worden.
*  Mindestens eine mit Cdiscount verknüpfte *Kategorie* ist am Artikel hinterlegt.
*  Mindestens eine der *Kategorien*, die mit Cdiscount verknüpft ist, ist für den Standard-Mandanten freigegeben.
*  Mindestens ein *Bild* ist am Artikel hinterlegt und für Cdiscount freigegeben

| Zusätzliche Konfiguration der Variante bei Variantenartikeln
a|
*  Die *Attribute* der Variante sind mit Cdiscount verknüpft.

2+|*Auftragsimport*

| Grundeinstellungen des Marktplatzes
a|
* *Preise und Bestände aktualisieren und Auftragsimport aktivieren* ist aktiviert.
* *API-Benutzername* ist eingetragen.
* *API-Passwort* ist eingetragen.

| Zahlungsarten
a|
*  Die *Zahlungsart Cdiscount* ist aktiviert.

| Konfiguration der Variante
a|
*  Eine *SKU* ist festgelegt worden.

|====

[#1000]
=== Artikelkatalog und Bestandsabgleich herunterladen

Im Tab *Archiv* laden Sie den Artikelkatalog oder den Bestandsabgleich als ZIP-Datei herunter. Das Herunterladen der ZIP-Dateien ist nötig, damit Sie die Dateien Ihrem Cdiscount-Ansprechspartner übermitteln können, wenn es z.B. zu Störungen beim Importieren kommt. So kann Cdiscount den Sachverhalt schneller prüfen und die Störungen beseitigen.

[.instruction]
Bestandsabgleich an Cdiscount übermitteln:

. Öffnen Sie das Menü *System » Märkte » Cdiscount.com » Tab: Archiv*.
. Klicken Sie auf *Bestandsabgleich herunterladen*.
. Speichern Sie die Datei auf Ihrer Festplatte, um sie ggf. an Cdiscount per E-Mail zu senden.

[#1100]
=== Artikelkatalog über CSV-Datei exportieren

Da es in seltenen Fällen zu Problemen beim automatischen Artikelexport kommen kann, können Sie Ihren auf französisch hinterlegten Artikelkatalog unter <<basics/datenaustausch/export-import/daten-exportieren#, Daten » Elastischer Export>> auch als CSV-Datei an Cdiscount exportieren. Nachdem Sie alle dafür notwendigen Einstellungen wie unten beschrieben gespeichert haben, müssen Sie die komplette URL kopieren und an Cdiscount übermitteln. Bestände werden weiterhin stündlich automatisch abgeglichen.

[.instruction]
Export erstellen:

. Öffnen Sie das Menü *System » Märkte » Cdiscount.com » Tab: Einstellungen*.
. Aktivieren Sie die Option *Preise und Bestände aktualisieren und Auftragsimport aktivieren*. +
*Wichtig:* Die Option *Produkterstellung anfordern* darf nicht aktiviert sein, da Daten sonst automatisch über die API-Schnittstelle übertragen werden.
. *Speichern* Sie die Einstellungen.
. Wechseln Sie in das Menü *Daten » Elastischer Export*.
. Öffnen Sie das Tab *Neuer Export*.
. Wählen Sie *Cdiscount.com* aus der Dropdown-Liste *Datenformat*.
. Geben Sie einen Namen für den Export ein.
. Nehmen Sie die Einstellungen gemäß  der Handbuchseite <<basics/datenaustausch/export-import/daten-exportieren#20, Daten exportieren>> vor.
. *Speichern* Sie die Einstellungen. +
→ Der Export erscheint als Unterordner im Tab *Exporte* und die URL wird erstellt.
. Öffnen Sie das Tab *Exporte* und dort den Unterordner *Cdiscount.com*.
. Kopieren Sie die *URL* und übermitteln Sie die URL an Cdiscount.

[NOTE]
.Merkmale für CSV-Datei verknüpfen
====
Wenn Sie Ihren Artikelkatalog über eine CSV-Datei an Cdiscount übermitteln, müssen im Menü <<artikel/artikel-verwalten#480, System » Artikel » Merkmale>> die Merkmale *Geschlecht*, *Hauptfarbe*, *Hinweis*, *Kommentar*, *Marketing-Beschreibung*, *Publikum* und *Sport* verknüpft werden.
====

[#1200]
== Retouren automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Retouren automatisch an Cdiscount zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-retouren-cdiscount>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-retouren-cdiscount>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-retouren-cdiscount]]
.Ereignisaktion zum automatischen Senden von Retouren an Cdiscount
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*CDiscount.fr*

|*Aktion*
|*Retoure &gt; Retoure an Cdiscount senden*
|
|====

[#1300]
== Auftragsstatus automatisch aktualisieren

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um den Auftragsstatus bei Cdiscount automatisch zu aktualisieren, wenn bestimmte Ereignisse eintreten. Sie haben die Möglichkeit, Aufträge bei Cdiscount per Ereignisaktion automatisch in die
folgenden Status zu setzen:

* Vom Händler abgelehnt
* Vom Händler versendet
* Versand vom Händler verweigert

Beispielhaft wird eine Ereignisaktion beschrieben, mit der Sie Cdiscount darüber informieren, dass Sie die bestellte Ware an den Kunden verschickt haben. Andere Ereignisaktionen richten Sie auf die gleiche Weise ein.

Damit die Versandbestätigung erfolgreich übermittelt wird, müssen folgende Daten am Auftrag gepflegt sein:

* Versanddienstleister
* Warenausgang muss gebucht sein
* externe Auftragsnummer

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-auftragsstatus-cdiscount>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-auftragsstatus-cdiscount>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-auftragsstatus-cdiscount]]
.Ereignisaktion zum automatischen Aktualisieren von Auftragsstatus bei Cdiscount
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel &gt; Warenausgang gebucht* +
*_Oder:_* *Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*CDiscount.fr*

|*Aktion*
|*Auftrag &gt; Auftragsänderung an Cdiscount melden*
|*Vom Händler versendet*
|====

[IMPORTANT]
.Status: Vom Händler akzeptiert
====
Der Status *Vom Händler akzeptiert* muss nicht per Ereignisaktion verschickt werden. Jeder Auftragseingang löst eine automatische Benachrichtigung über diesen Status an Cdiscount aus.
====

[#1400]
== API-Log abrufen

Im Menü *Daten » API-Log* finden Sie eine Historie über Vorgänge, die über die Cdiscount-Schnittstelle ausgeführt wurden. Das Format *Cdiscount.com* steht Ihnen für Cdiscount zur Verfügung.

[.instruction]
API-Log abrufen:

.  Öffnen Sie das Menü *Daten » API-Log » Tab: API-Log*.
.  Wählen Sie das Format *Cdiscount.com* aus der Dropdown-Liste *Vorgang*.
.  Wählen Sie ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
.  Wählen Sie die Anzahl der Ergebnisse pro Seite.
.  Klicken Sie auf *Suchen*, um die Ergebnisse anzuzeigen.
