= PIXmania
:lang: de
include::{includedir}/_header.adoc[]
:keywords: PIXmania, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz PIXmania in Ihrem plentymarkets System ein.
:position: 210

link:http://www.pixmania.de/index.html[PIXmania^] ist ein Online-Marktplatz mit einem breiten Angebot an Produkten der Bereiche Consumer-Eletronik, Haus und Garten, Spielzeug und mehr. Mit plentymarkets können Sie Ihre neuen oder auch gebrauchten Artikel bei PIXmania anbieten und damit Ihre Reichweite vergrößern und neue Kunden generieren.

[#100]
== Bei PIXmania registrieren

Um die Schnittstelle zu PIXmania einzurichten, registrieren Sie sich zunächst als Händler bei link:https://www.pixmania.de/edito/verkaufen-auf-pixmaniacom/584e6ffe3c446c7fc88fa40d[PIXmania^]. Sie erhalten die nötigen Zugangsdaten, die Sie für die Einstellungen in plentymarkets benötigen.

[#200]
== PIXmania in plentymarkets einrichten

Bedingungen für die Nutzung von PIXmania in Ihrem plentymarkets System:

* Artikel für PIXmania müssen den Hersteller und mindestens ein Artikelbild hinterlegt haben.
* Sie benötigen einen Händlerschlüssel von PIXmania, den Sie nach der Registrierung bei diesem Marktplatz erhalten.

Nachdem Sie Ihren Händlerschlüssel gespeichert haben, erscheint die Auswahl der Länderplattformen.

[.instruction]
PIXmania in plentymarkets einrichten:

. Öffnen Sie das Menü *System » Märkte » PIXmania » Einstellungen*.
. Klappen Sie den Bereich *Grundeinstellungen* auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<grundeinstellungen-pixmania>>.
. *Speichern* Sie die Einstellungen.

[[grundeinstellungen-pixmania]]
.Grundeinstellungen des Marktplatzes PIXmania
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Automatischen Datenaustausch aktivieren*
|Aktivieren, um Daten automatisch mit PIXmania auszutauschen. +
Zum Datenaustausch zählen der tägliche Artikelexport, der viertelstündliche Bestandsabgleich, der viertelstündliche Preisabgleich und der viertelstündliche Auftragsimport.

|*PIXmania-Händlerschlüssel*
|Händlerschlüssel eingeben, wie von PIXmania erhalten.

|*Verkaufsländer*
|Länderplattformen aktivieren, auf denen Sie verkaufen möchten. Die Länderauswahl wird erst sichtbar, nachdem Sie Ihren Händlerschlüssel eingegeben und gespeichert haben.

|*Zahlungseingang*
|Wählen, ob Aufträge mit einem *offenen* Zahlungseingang oder mit *gebuchtem* Zahlungseingang in Ihr plentymarkets System übertragen werden sollen. Zahlungen von PIXmania werden gebündelt übertragen. Wird die Einstellung *gebucht* gewählt, werden Aufträge, für die noch keine Zahlung von PIXmania eingegangen ist, bereits als bezahlt ins System übertragen.

|*Herkunft*
|*PIXmania* wählen.

2+|Lieferzeit in vollen Tagen

|*Standard*
|Lieferzeit in Tagen eingeben. Diese Lieferzeit ist die Standardlieferzeit, die Sie für die meisten Ihrer Sendungen benötigen.

|*Verfügbarkeit 1 - 5*
|Lieferzeit in Tagen bei jeder Option für *Inland* und *Ausland* eingeben. Nur die hier eingegebenen Tage werden als Lieferzeit an PIXmania übertragen. 0 als Anzahl von Tagen ist nicht erlaubt. Sie müssen eine natürliche Zahl eingeben. Die Optionen für Artikelverfügbarkeit werden im Menü <<artikel/artikel-verwalten#190, System » Artikel » Verfügbarkeit>> eingerichtet.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierten Funktionen bereit:

* Täglicher Artikelexport
* Viertelstündlicher Bestandsabgleich
* Viertelstündlicher Preisabgleich
* Viertelstündlicher Auftragsimport

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit PIXmania verknüpfen können, muss im Menü *System » Aufträge » Auftragsherkunft* die Auftragsherkunft PIXmania aktiviert werden.

[.instruction]
Auftragsherkunft für PIXmania aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Auftragsherkunft*.
. Setzen Sie bei *PIXmania* ein Häkchen.
. *Speichern* Sie die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf PIXmania verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden. Zusätzlich müssen Artikel für PIXmania den Hersteller und mindestens ein Artikelbild hinterlegt haben.

[.instruction]
Artikelverfügbarkeit für PIXmania einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Setzen Sie ein Häkchen neben der Option *PIXmania*.
. Setzen Sie ein Häkchen neben der Option *Web-API*.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen. +
→ Der Artikel ist auf PIXmania verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

[#400]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft PIXmania einen Verkaufspreis festzulegen. Dieser Preis wird auf PIXmania angezeigt.

[.instruction]
Verkaufspreis für PIXmania festlegen:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setzen Sie ein Häkchen bei der Herkunft *PIXmania*.
. *Speichern* Sie die Einstellungen.

[#500]
== Brand-IDs importieren

Sie benötigen die Brand-IDs von PIXmania, die Sie folgendermaßen erhalten.

[.instruction]
Datenformat exportieren:

. Öffnen Sie das Menü *Daten » Dynamischer Export » Tab: Neues Datenformat*.
. Wählen Sie unter *Datenformat-Typ* die Einstellung *Producer*.
. Geben Sie einen Namen ein.
. Aktivieren Sie die Felder *ProducerID*, *ProducerName* und *ProducerPixmaniaID*.
. *Speichern* Sie die Einstellungen. +
→ Das Tab *Datenformat bearbeiten* wird geöffnet.
. Klappen Sie das Datenformat auf.
. Klicken Sie auf das Zahnrad *Daten exportieren*.
. Speichern Sie die CSV-Datei auf Ihrem Rechner.

Senden Sie die CSV-Datei an den PIXmania-Kundenservice. Sie erhalten darauf von PIXmania eine Excel-Datei, aus der Sie eine CSV-Datei erzeugen, die dem Datenformat *Producer* entspricht.

[.instruction]
Datenformat importieren:

. Öffnen Sie das Menü *Daten » Dynamischer Import*.
. Wählen Sie das Feldtrennzeichen.
. Wählen Sie unter *Format* Ihr Datenformat.
. Klicken Sie auf *Datei auswählen*.
. Öffnen Sie die CSV-Datei.
. Klicken Sie auf das Zahnrad *Import*. +
→ Nach dem Import der Brand-IDs finden Sie die PIXmania-ID eines Herstellers im Menü *System » Artikel » Hersteller*.

[#600]
== Kategorien verknüpfen

Um Ihre Kategorien mit denen von PIXmania zu verknüpfen, laden Sie zunächst die Kategorieliste direkt von PIXmania herunter. Verknüpfen Sie dann Ihre eigenen Kategorien mit den passenden PIXmania-Kategorien.

[.instruction]
PIXmania-Kategorien importieren:

. Öffnen Sie das Menü *System » Märkte » PIXmania » Kategorieverknüpfung*.
. Klicken Sie auf *Datei auswählen*.
. Wählen Sie das *Feldtrennzeichen*.
. Klicken Sie auf *Speichern*. +
→ Die Kategorieliste wird importiert.

Um Ihre Kategorien mit denen von PIXmania zu verknüpfen, gehen Sie wie folgt vor.

[.instruction]
Kategorien verknüpfen:

. Öffnen Sie das Menü *System » Märkte » PIXmania » Kategorieverknüpfung*.
. Klicken Sie im Bereich *PIXmania-Verknüpfung* auf das *Zahnrad*. +
→ Die PIXmania-Kategorien werden im Bereich *Kategorien* angezeigt.
. Klappen Sie die Kategorie auf.
. Wählen Sie die Unterkategorie. +
→ Die verknüpfte Kategorie wird im Bereich *Auswahl* angezeigt.
. Klicken Sie auf *Neu laden*. +
→ Die Verknüpfungen werden unter *PIXmania-Verknüpfung* angezeigt.

[IMPORTANT]
.*Kategorieverknüpfung löschen*
====
Sie können Kategorieverknüpfungen im Bereich *Auswahl* löschen.
====

Nach der Verknüpfung Ihrer Kategorien mit den PIXmania-Kategorien exportieren Sie diese Daten zu PIXmania.

[.instruction]
Kategorieverknüpfungen exportieren:

. Öffnen Sie das Menü *System » Märkte » PIXmania » Kategorieverknüpfung*.
. Klicken Sie auf das Zahnrad *Verknüpfung exportieren*. +
→ Eine CSV-Datei wird erstellt.
. Speichern Sie die CSV-Datei auf Ihrem Rechner.
. Senden Sie die CSV-Datei an PIXmania.

[#700]
== Attribute verknüpfen

Wenn Sie <<artikel/artikel-verwalten#390, Attribute>> im plentymarkets System erstellt haben, müssen diese Attribute mit PIXmania verknüpft werden. Nachfolgend wird beschrieben, wie Sie das Attribut Farbe mit PIXmania verknüpfen. Verknüpfen Sie weitere Attribute auf die gleiche Weise.

[.instruction]
Attribute verknüpfen:

. Öffnen Sie das Menü *System » Artikel » Attribute*. +
→ Eine Übersicht aller erstellten Attribute wird geöffnet.
. Klappen Sie das Attribut *Farbe* auf.
. Wechseln Sie in das Tab *Marktplatzvariation*.
. Wählen Sie in der Dropdown-Liste *Marktplatz* die Option *Pixmania*. +
→ Eine zusätzliche Dropdown-Liste *Pixmania* wird angezeigt.
. Wählen Sie in der Dropdown-Liste *Pixmania* das Attribut *Farbe*.
. *Speichern* Sie die Einstellungen.

[#800]
==  Zahlungsart aktivieren

Aktivieren Sie die <<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsart>> *PIXmania Payment*, wie im Folgenden beschrieben.

[.instruction]
PIXmania-Zahlungsarten aktivieren:

.  Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
.  Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
.  Öffnen Sie den Ordner *International*.
.  Klicken Sie auf *PIXmania Payment*. +
→ Das Tab *Einstellungen* wird geöffnet.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<einstellungen-zahlungsart-pixmania>>.
.  Setzen Sie ein Häkchen bei der Option *Aktiv*.
. *Speichern* Sie die Einstellungen.

[[einstellungen-zahlungsart-pixmania]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Sprache*
| Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit haben Sie die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
| Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
| Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
| Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
| Kein Lieferland wählen. +
Sie können die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig konfiguriert.

|*Logo*
| Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
| Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
| Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben. +
Weitere Informationen finden Sie auf der Handbuchseite <<basics/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten finden Sie auf der Handbuchseite <<auftragsabwicklung/payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » CRM » Kundenklassen* aktivieren oder deaktivieren Sie *erlaubte Zahlungsarten*. +
Weitere Informationen finden Sie im Kapitel <<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen finden Sie auf der Handbuchseite <<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#900]
== Exportverlauf abrufen

Im Menü *System » Märkte » PIXmania » Exportverlauf* wird Ihnen eine Übersicht über den Exportverlauf Ihrer PIXmania-Artikel angezeigt. Sowohl Exportvorgänge *in Bearbeitung* als auch *abgeschlossene* Exportvorgänge werden angezeigt.
