= Netto Marken-Discount, GartenXXL.de und GartenXXL.at
:lang: de
include::{includedir}/_header.adoc[]
:keywords: GartenXXL.de, GartenXXL.at, Netto, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zu den Marktplätzen Netto Marken-Discount und GartenXXL.de in Ihrem plentymarkets System ein.
:position: 220

link:https://shop.netto-online.de/[Netto Marken-Discount] bietet Produkte aus den Kategorien Lebensmittel, Drogerie, Wohnen, Haushalt, Garten und Freizeit an (Quelle: https://shop.netto-online.de).

link:http://www.gartenxxl.de/[GartenXXL^] ist eine Marke der Tengelmann E-Stores GmbH. Auf GartenXXL werden Geräte bekannter Firmen und wissenswerte Informationen zur Gartenpflege angeboten (Quelle: www.gartenxxl.de).

[#100]
== Bei Netto eStores registrieren

Bevor Sie Netto eStores in Ihrem plentymarkets System einrichten, müssen Sie sich zunächst bei Netto eStores registrieren. Ansprechpartner für die Registrierung: +
Katrin.Beer@netto-online.de +
Christian.Mertens@netto-online.de

[IMPORTANT]
.Artikelexport mit Produkt-XML 4.0
====
plentymarkets überträgt Artikeldaten mit der Produkt-XML 4.0 zu den Marktplätzen der Netto eStores GmbH. Informieren Sie Netto eStores bei Ihrer Registrierung darüber, da ansonsten Artikel nicht exportiert werden können.
====

[#200]
== Netto eStores in plentymarkets einrichten

Um Artikel auf Netto Marken-Discount, GartenXXL.de und GartenXXL.at verkaufen zu können, müssen Sie den Marktplatz zunächst in plentymarkets einrichten. Gehen Sie dazu wie im Folgenden beschrieben vor:

[.instruction]
Netto Marken-Discount/GartenXXL.de/GartenXXL.at in plentymarkets einrichten:

. Öffnen Sie das Menü *System » Märkte » Netto eStores*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<einstellungen-plus>>.
. *Speichern* Sie die Einstellungen.

[[einstellungen-plus]]
.Einstellungen für die Marktplätze Netto Marken-Discount, GartenXXL.de und GartenXXL.at
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Automatischen Datenaustausch aktivieren*
|*Ja* wählen, um den automatischen Datenaustausch zu aktivieren oder *Nein*, um den Datenaustausch zu deaktivieren. +
Wenn Sie *Ja* wählen, werden der Bestandsabgleich, der Artikelexport und der Auftragsimport aktiviert.

|*Artikelexport aktivieren*
|*Ja* wählen, um den automatischen Artikelexport zu aktivieren oder *Nein*, um den automatischen Artikelexport zu deaktivieren.

|*Bestandsabgleich aktivieren*
|*Ja* wählen, um den automatischen Bestandsabgleich zu aktivieren oder *Nein*, um den automatischen Bestandsabgleich zu deaktivieren.

2+|Vertriebspartner-Information

|*Lieferantennummer*
|Lieferantennummer eingeben, wie von Netto eStores erhalten.

2+|Artikeleinstellungen

|*Artikelname*
|Artikelnamen wählen, der an Netto eStores übertragen wird.

|*Variantenname*
|Variantennamen wählen, der an Netto eStores übertragen wird. +
*Variantenname* = Der Variantenname wird übertragen. +
*Attributswerte der Variante anhängen* = Die Attributswerte werden durch Leerzeichen getrennt an den Variantennamen angehängt (Beispiel: "T-Shirt rot XL").

|*Artikelkurzbeschreibung*
|Artikelkurzbeschreibung wählen, die an Netto eStores übertragen wird.

|*Artikelbeschreibung*
|Artikelbeschreibung wählen, die an Netto eStores übertragen wird.

|*Bildposition für das Energieetikett*
|Ziffer der Bildposition des Artikelbildes eingeben, wenn das Energieetikett nicht als Merkmal, sondern als Artikelbild erstellt wurde. Details zum Energieetikett siehe Kapitel <<Energieeffizienz-Merkmale erstellen, Energieeffizienz-Merkmale erstellen>>.

|*Menge für Artikel ohne Bestandsbindung*
|Bei Artikeln mit der Einstellung *keine Beschränkung* wird der Maximalwert aus realem Bestand und der hier definierten Menge übermittelt. +
Beispiel: Einstellung 0, Nettowarenbestand 8. plentymarkets übermittelt 8. +
Artikel mit der Einstellung *Beschränkung auf Nettowarenbestand* werden hier nicht berücksichtigt.

|*Menge für Artikel ohne Bestandsbeschränkung, falls der Bestand 0 ist*
|Zahl eingeben, die als Bestand für Artikel ohne Bestandsbeschränkung, bei denen der Bestand 0 ist, übertragen werden soll.

|*Standardlieferzeiten*
|Durchschnittliche Lieferzeit in Tagen eingeben.

|*Artikel-Lieferzeit 1 - 10*
|Durchschnittliche Lieferzeiten in Tagen für die Artikelverfügbarkeiten 1 - 5 eingeben. +
*Wichtig:* Nur eindeutige Angaben sind möglich (d.h. keine Zeiträume wie 2-3).

|*Standardprovision in Prozent*
|Provisionswert eingeben, der mit Netto eStores vereinbart wurde.

|*Standardversandkosten*
|Versandkosten in Euro eingeben. Der eingegebene Wert wird als Standardversandkosten für alle Artikel übertragen.

|*Preis für EK/VK-Modell*
|Preis für das EK/VK-Modell wählen. In der Dropdown-Liste können alle Preise gewählt werden, die für Plus freigegeben sind. Wenn der gewählte Preis an allen Varianten eines Artikels gespeichert ist, wird der Preis als Einkaufspreis für Plus übertragen. Andernfalls wird der unter *Standardprovision in Prozent* eingestellte Provisionssatz übertragen. +
*Wichtig:* Der hier gewählte Preis darf nicht der Verkaufspreis sein, sonst wird kein Preis für das EK/VK-Modell übertragen.

2+|Bestelleinstellungen

|*Mindestbestellmenge*
|Artikelanzahl eingeben, wenn eine Mindestbestellmenge gewünscht ist.

|*Maximale Bestellmenge*
|Artikelanzahl eingeben, wenn eine maximale Bestellmenge gewünscht ist.

|*Artikelnamen in Auftragspositionen*
|Wählen, ob der Artikelname in den Auftragspositionen von Netto eStores oder aus dem Shop übernommen werden soll.

2+|SFTP-Einstellungen

|*Benutzername*
|Benutzername eingeben, wie von Netto eStores erhalten.
|====

[IMPORTANT]
.EK/VK nur nach Absprache mit Verkaufskanal ändern
====
Ändern Sie die Einstellungen zur *Standard-Provision in Prozent* und zum *Preis für EK/VK-Modell* nur in Absprache mit dem Verkaufskanal. Netto eStores empfiehlt, als Standard ein Provisionsmodell mit dem Provisionswert einzustellen, der mit Netto eStores vereinbart wurde.
====

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

- täglicher Artikelexport
- täglicher Preisabgleich
- stündlicher Bestandsabgleich
- stündlicher Auftragsimport

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit Netto Marken-Discount, GartenXXL.de und GartenXXL.at verknüpfen können, muss im Menü *System » Aufträge » Auftragsherkunft* die Auftragsherkunft aktiviert werden. Im Folgenden wird beispielhaft beschrieben, wie Sie die Auftragsherkunft für Netto aktivieren. Aktivieren Sie die Auftragsherkünfte für GartenXXL.de und GartenXXL.at analog dazu.

[.instruction]
Auftragsherkunft für Netto aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Auftragsherkunft*.
. Setzen Sie ein Häkchen bei *Netto*.
. *Speichern* Sie die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf den Marktplätzen Netto Marken-Discount, GartenXXL.de und GartenXXL.at verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden. Stellen Sie die Artikelverfügbarkeiten für die Marktplätze Netto Marken-Discount, GartenXXL.de und GartenXXL.at einzeln ein, je nachdem, auf welchen Marktplätzen Sie Ihre Artikel verkaufen wollen. +

Im Folgenden wird beispielhaft beschrieben, wie Sie die Artikelverfügbarkeit für Plus.de einstellen. Nehmen Sie die Einstellungen für die weiteren Marktplätze auf die gleiche Weise vor. +

[.instruction]
Artikelverfügbarkeit für Plus.de einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Setzen Sie ein Häkchen neben der Option *Plus.de*.
. Setzen Sie ein Häkchen neben der Option *Web-API*.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen. +
→ Der Artikel ist auf Plus.de verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden. +

[#330]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügen Sie, wenn nötig, marktplatzspezifische SKUs hinzu. +

Wenn Sie SKUs hinzufügen, gilt die Herkunft *Plus.de* für die Marktplätze Netto Marken-Discount, GartenXXL.de und GartenXXL.at.

[.instruction]
SKU hinzufügen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wählen Sie die Herkunft *Plus.de*.
. Geben Sie die SKU ein.
. Klicken Sie auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#350]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft Plus.de einen Verkaufspreis festzulegen. Der Preis für die Auftragsherkunft *Plus.de* wird auf den Marktplätzen Netto Marken-Discount, GartenXXL.de und GartenXXL.at angezeigt.

[.instruction]
Verkaufspreis für Netto Marken-Discount/GartenXXL.de/GartenXXL.at festlegen:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setzen Sie ein Häkchen bei der Herkunft *Plus.de*. +
→ Für die Marktplätze Netto Marken-Discount, GartenXXL.de und GartenXXL.at wird derselbe Preis exportiert.
. *Speichern* Sie die Einstellungen.

[#400]
== Zahlungsart aktivieren

Aktivieren Sie die <<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsart>> *Netto* wie im Folgenden beschrieben. Nehmen Sie anschließend die Einstellungen für die Zahlungsarten *GartenXXL.de* und *GartenXXL.at* auf die gleiche Weise vor.

[.instruction]
Zahlungsart Netto aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive anzeigen*.
. Klicken Sie auf den Ordner *DE &gt; Netto*. +
→ Die Einstellungen für die Netto-Zahlungsart werden angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<einstellungen-zahlungsart>>.
. Setzen Sie ein Häkchen bei der Option *Aktiv*.
. *Speichern* Sie die Einstellungen.

[[einstellungen-zahlungsart]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit haben Sie die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
|Kein Lieferland wählen. +
Sie können die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig konfiguriert.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. Wichtig: Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen finden Sie auf der Handbuchseite <<basics/statistik#, Statistik>>. Ein Beispiel für pauschale und prozentuale Kosten finden Sie auf der Handbuchseite <<auftragsabwicklung/payment/zahlungsarten-verwalten#20, Grundeinstellungen>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » CRM » Kundenklassen* aktivieren oder deaktivieren Sie *erlaubte Zahlungsarten*. +
Weitere Informationen finden Sie im Kapitel <<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen finden Sie auf der Handbuchseite <<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#500]
== Kategorien verknüpfen

Damit Ihre Artikel auf den Marktplätzen Netto Marken-Discount, GartenXXL.de und GartenXXL.at zum Verkauf angezeigt werden, müssen Sie Kategorieverknüpfungen erstellen. Die dafür erforderlichen Kategorie-IDs für Netto Marken-Discount, GartenXXL.de und GartenXXL.at erhalten Sie von Netto eStores. Erstellen Sie wie im Folgenden beschrieben Verknüpfungen, damit Ihre Artikel in den <<artikel/kategorien-verwalten#, Kategorien>> auf den Marktplätzen angezeigt werden.

[.instruction]
Kategorien verknüpfen:

. Öffnen Sie das Menü *System » Märkte » Netto eStores*.
. Wechseln Sie in das Tab *Kategorien aktivieren*.
. Geben Sie in den Spalten *Netto-Kategorienverknüpfung*/*GartenXXL.de-Kategorienverknüpfung*/*GartenXXL.at-Kategorienverknüpfung* die IDs der Kategorien ein, die am besten zu Ihren Webshop-Kategorien passen. +
→ Die Kategorie-IDs der Marktplätze entnehmen Sie den Kategoriedateien, die Sie von Netto eStores erhalten haben.
. Aktivieren Sie die Kategorien.
. *Speichern* Sie die Einstellungen.

[#700]
== Merkmale erstellen

Mit <<artikel/artikel-verwalten#480, Merkmalen>> verknüpfen Sie bestimmte Eigenschaften, die Sie für die Einrichtung der Marktplätze Netto Marken-Discount, GartenXXL.de und GartenXXL.at benötigen, mit Ihren Artikeln. Sie tragen bei Bedarf von den Standardeinstellungen abweichende Provisionen und Kategorieverknüpfungen auf Artikelebene ein. Über Merkmalfilter übermitteln Sie außerdem Artikelinformationen und legen Filter für die Artikelsuche auf den Marktplätzen fest.

Wie im Kapitel <<Kategorien verknüpfen, Kategorien verknüpfen>> beschrieben, geben Sie im Menü *System » Märkte » Netto eStores* im  Tab *Kategorien aktivieren* die Standardkategorieverknüpfungen ein. Um bestimmten Artikeln bei Bedarf eine andere Kategorie zuzuweisen, verwenden Sie die <<artikel/artikel-verwalten#480, Merkmale>> *Artikel-Kategorieverknüpfung für Netto*, *Artikel-Kategorieverknüpfung für GartenXXL.de* oder *Artikel-Kategorieverknüpfung für GartenXXL.at*.

[.instruction]
Merkmal erstellen:

. Öffnen Sie das Menü *System » Artikel » Merkmale*.
. Wechseln Sie in das Tab *Neues Merkmal*.
. Geben Sie einen Namen unter *Name (intern)* ein.
. Wählen Sie den Merkmaltyp *Text*.
. Wählen Sie aus der Dropdown-Liste *Netto eStores-Merkmal* das Merkmal *Artikel-Kategorieverknüpfung für Netto* / *Artikel-Kategorieverknüpfung für GartenXXL.de* / *Artikel-Kategorieverknüpfung für GartenXXL.at*.
. *Speichern* Sie die Einstellungen.

[#800]
=== Provisionssätze auf Artikelebene einstellen

Im Menü *System » Märkte » Netto eStores* geben Sie für die Marktplätze einen Standardprovisionssatz ein. Da für bestimmte Netto eStores-Warengruppen jedoch andere Provisionen gelten können, haben Sie die Möglichkeit, auf Artikelebene einen abweichenden Provisionssatz einzugeben. Einen abweichenden Provisionssatz geben Sie mit dem <<artikel/artikel-verwalten#480, Merkmal>> *Provision in Prozent* an. Diese Einstellung hat Priorität gegenüber der eingegebenen Standardprovision. Beachten Sie, dass Sie diesen Prozentsatz im Vorfeld mit Netto eStores abstimmen müssen.

[.instruction]
Merkmal erstellen:

. Öffnen Sie das Menü *System » Artikel » Merkmale*.
. Wechseln Sie in das Tab *Neues Merkmal*.
. Geben Sie einen Namen unter *Name (intern)* ein.
. Wählen Sie den Merkmaltyp *Text*.
. Wählen Sie das Netto eStores-Merkmal *Provision in Prozent* aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen.

[TIP]
.Merkmale: Filter
====
Filter haben bei Netto eStores zwei Funktionen: Sie übermitteln damit Artikelinformationen an Netto eStores und können den Artikel bei Netto eStores über diesen Filter finden. Nach Auswahl eines Filters wird eine weitere Dropdown-Liste angezeigt. Wählen Sie hier das Filtermerkmal, das einem Artikel zugeordnet werden soll. +
Hinweis: Das Merkmal *Energieeffizienz* ist nur für den Marktplatz Netto eStores verfügbar.
====

[#900]
=== Energieeffizienz-Merkmale erstellen

Für die Auszeichnung Ihrer Artikel für die Marktplätze der Netto eStores GmbH gemäß der neuen Verordnung der EU zur Energieeffizienzrichtlinie sind ab 1.1.2015 Angaben zur Energieeffizienz sowie die Bereitstellung von Produktdatenblättern vorgeschrieben. Erstellen Sie dazu die folgenden drei <<artikel/artikel-verwalten#500, Merkmale>>: *Energieeffizienzklasse*, *Energieetikett* und *Produktdatenblatt*.

[.instruction]
Merkmal Energieeffizienzklasse erstellen:

. Öffnen Sie das Menü *System » Artikel » Merkmale*.
. Wechseln Sie in das Tab *Neues Merkmal*.
. Geben Sie einen Namen unter *Name (intern)* ein.
. Wählen Sie den Merkmaltyp *Kein*.
. Wählen Sie die Option *Energieeffizienz* aus der Dropdown-Liste *Netto eStores-Merkmal*. +
→ Eine weitere Dropdown-Liste wird geöffnet.
. Wählen Sie die Energieeffizienzklasse.
. *Speichern* Sie die Einstellungen.

Für die Merkmale Energieetikett und Produktdatenblatt wählen Sie den Merkmaltyp *Datei*. In der Dropdown-Liste *Netto eStores-Merkmal* wählen Sie dann die Option *Energieetikett* bzw. *Produktdatenblatt*. Im Folgenden wird beispielhaft beschrieben, wie Sie das Merkmal Energieetikett erstellen. Erstellen Sie anschließend das Merkmal Produktdatenblatt auf die gleiche Weise.

[.instruction]
Merkmal Energieetikett erstellen:

. Öffnen Sie das Menü *System » Artikel » Merkmale*.
. Wechseln Sie in das Tab *Neues Merkmal*.
. Geben Sie einen Namen unter *Name (intern)* ein.
. Wählen Sie den Merkmaltyp *Datei*.
. Wählen Sie die Option *Energieetikett* aus der Dropdown-Liste *Netto eStores-Merkmal*.
. *Speichern* Sie die Einstellungen.

Die Merkmale verknüpfen Sie dann wie im Folgenden beschrieben im Tab <<artikel/artikel-verwalten#80, Merkmale>> eines Netto eStores-Artikels.

[.instruction]
Energieeffizienz-Merkmale mit Netto eStores-Artikel verknüpfen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab *Merkmale*.
. Aktivieren Sie die soeben erstellten Merkmale *Energieeffizienzklasse*, *Energieetikett* und *Produktdatenblatt*.
. *Speichern* Sie die Einstellungen. +
→ Die Merkmale werden mit dem Artikel verknüpft und sind im Bereich *Merkmale* sichtbar.
. Laden Sie beim Merkmal *Energieetikett* die Bilddatei des Energieetiketts hoch.
. Laden Sie beim Merkmal *Produktdatenblatt* die PDF-Datei des Produktdatenblatts hoch.
. *Speichern* Sie die Einstellungen.

*_Oder:_* Speichern Sie das Energieetikett im Tab <<artikel/artikel-verwalten#90, Bilder>> des Artikels. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Energieetikett im Tab Bilder speichern:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab *Bilder*.
. Fügen Sie die Bilddatei des Energieetiketts entweder über *Dateien auswählen* oder per Drag &amp; Drop-Funktion hinzu.
. *Speichern* Sie die Einstellungen.
. Öffnen Sie das Menü *System » Märkte » Netto eStores*.
. Geben Sie die Positionsnummer des Bildes im Tab *Einstellungen* bei der Option *Bildposition für das Energieetikett* ein (Tabelle 1).
. *Speichern* Sie die Einstellungen.

[#1000]
== Versandbestätigungen automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an Netto eStores zu senden, nachdem ein Warenausgang gebucht wurde. Die Versandbestätigung wird automatisch an Netto eStores gesendet, wenn der Auftrag in Status *[7] Warenausgang gebucht* wechselt. Der Käufer wird durch Netto eStores über den Versand benachrichtigt.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-versandbestaetigung>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-versandbestaetigung>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-versandbestaetigung]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an Netto eStores
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Netto*, *GartenXXL.de* und *GartenXXL.at*

|*Aktion*
|*Versand &gt; Versandbestätigung an Netto eStores senden*
|
|====

[#1100]
== Stornierungen automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Stornierungen automatisch an Netto eStores zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-stornierung>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-stornierung>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-stornierung]]
.Ereignisaktion zum automatischen Senden von Stornierungen an Netto eStores
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel &gt; [8] Storniert*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Netto*, *GartenXXL.de* und *GartenXXL.at*

|*Aktion*
|*Zahlungsarten &gt; Stornierung an Netto eStores senden*
|
|====

[#1200]
== Retouren automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Retouren automatisch an Netto eStores zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<ereignisaktion-retouren>>.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<ereignisaktion-retouren>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-retouren]]
.Ereignisaktion zum automatischen Senden von Retouren an Netto eStores
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Netto*, *GartenXXL.de* und *GartenXXL.at*

|*Aktion*
|*Retoure &gt; Retoure an Netto eStores senden*
|
|====

[#1250]
== Unbezahlte Aufträge nach 30 Tagen automatisch stornieren

Aufträge, die vom Kunden nicht bezahlt wurden, werden bei Netto Marken-Discount/Garten XXL.de/GartenXXL.at automatisch nach 30 Tagen storniert. Richten Sie eine Aktion im <<basics/automatisierung/aktionsmanager#, Aktionsmanager>> ein, um unbezahlte Aufträge von Netto Marken-Discount/GartenXXL.de/GartenXXL.at in Ihrem plentymarkets System nach 30 Tagen automatisch zu stonieren, damit die reservierten Bestände wieder freigegeben werden.

[.instruction]
Aktion einrichten

. Öffnen Sie das Menü *System » Aufträge » Aktionen » Tab: Neue Aktion*.
. Öffnen Sie das Tab *Einstellungen*.
. Setzen Sie ein Häkchen bei *Aktiv*.
. Wählen Sie aus der Dropdown-Liste *Täglich ausführen um* eine Uhrzeit, zu der die Aktion ausgeführt werden soll. Wir empfehlen, für diese Aktion die Uhrzeit *24:00 Uhr* zu wählen.
. Geben Sie einen Namen ein.
. Wechseln Sie in das Tab *Filter*.
. Wählen Sie die Filter gemäß <<unbezahlte-aufträge>>.
. Wechseln Sie in das Tab *Aktion*.
. Wählen Sie aus der Dropdown-Liste *Ändere Auftragsstatus* einen Status, z.B. *[8.1] Storniert durch Kunden*. Weitere Informationen zur Statuswahl finden Sie in der Infobox.
. *Speichern* Sie die Einstellungen.
→ Die Aktion wird erstellt und im Tab *Aktionen* angezeigt.

[TIP]
.Status wählen
====
Wählen Sie für die Aktion *Ändere Auftragsstatus* einen Status, den Sie unter *System » Aufträge » Einstellungen* für die Option *Status stornierter Aufträge (Keine Reservierung von Beständen)* gespeichert haben, um Reservierungen aufzuheben. Wählen Sie hier außerdem keinen Status, der eine Ereignisaktion auslöst, die eine Stornierung an Netto eStores meldet.
====

[[unbezahlte-aufträge]]
.Filter für die Aktion zum automatischen Stornieren von unbezahlten Aufträgen nach 30 Tagen
[cols="1,3"]
|====
| Filter | Auswahl

|*Status*
|*[3] Warten auf Zahlung*

|*Auftragstyp*
|*Auftrag*

|*Auftragseingang*
|*vor 30 Tagen*

|*Auftragsherkunft*
|*Netto*, *GartenXXL.de* und *GartenXXL.at*
|====

[#1350]
== Lieferscheine und Rücksendescheine erstellen

Die folgenden Informationen gelten nur für Lieferscheine und Rücksendescheine bei Netto Marken-Discount, GartenXXL.de und GartenXXL.at. Sie sind für andere Marktplätze nicht gültig.

[IMPORTANT]
.Rechnungen werden von den Marktplätzen versendet
====
Netto Marken-Discount/GartenXXL.de/GartenXXL.at versenden die Rechnung an den Kunden. Deshalb erhalten Sie von diesen Marktplätzen die Lieferadresse, aber nicht die Rechnungsadresse des Kunden. Die von Netto Marken-Discount/GartenXXL.de/GartenXXL.at übertragene Lieferadresse wird in plentymarkets als Liefer- und Rechnungsadresse hinterlegt. Sie schicken die Ware an diese Adresse.
====

Gehen Sie wie im Folgenden beschrieben vor, um <<auftragsabwicklung/auftraege/auftragsdokumente#170, PDF-Vorlagen>> für Lieferscheine und Rücksendescheine für Netto Marken-Discount, GartenXXL.de und GartenXXL.at zu erstellen. Im Folgenden wird das Anlegen eines Lieferscheins für Netto eStores beispielhaft beschrieben. Gehen Sie anschließend auf die gleiche Weise vor, um einen Rücksendeschein für Netto eStores anzulegen. Alle PDF-Vorlagen, die Sie erstellen, müssen das Logo von Netto Marken-Discount oder GartenXXL.de bzw. GartenXXL.at enthalten. Fordern Sie die Logos direkt bei Netto eStores an. +

Hier laden Sie Vorlagendateien für link:https://www.plentymarkets.eu/documents/category/3507/Template-Netto.pdf[Netto Marken-Discount^], link:https://www.plentymarkets.eu/documents/category/3507/Template-GartenXXL-de.pdf[GartenXXL.de^] und link:https://www.plentymarkets.eu/documents/category/3507/Template-GartenXXL-at.pdf[GartenXXL.at^] herunter.

[.instruction]
Lieferschein für Netto eStores erstellen:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Standorte » Deutschland (Standard) » Dokumente » Lieferschein*.
. Wechseln Sie in das Tab *PDF-Vorlage*.
. Klicken Sie auf *Vorlage hinzufügen*. +
→ Das Bearbeitungsfenster *Neue PDF-Vorlage hochladen* wird geöffnet.
. Wählen Sie aus der Dropdown-Liste *Zahlungsart* die Option *Netto*/*GartenXXL.de*/*GartenXXL.at*.
. Wählen Sie aus der Dropdown-Liste *Sprache* eine Sprache aus.
. Klicken Sie in der Zeile *Vorlage* auf *Vorlage auswählen*.  +
→ Laden Sie die PDF-Vorlage hoch.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Pflichtangabe auf Dokumenten
====
Die externe Auftragsnummer und die externe Kundennummer sind Pflichtangaben auf Dokumenten, die zu einem Auftrag der Herkunft Netto, GartenXXL.de oder GartenXXL.at gehören. Normalerweise können Sie diese Angaben im Menü *System » Mandant » Mandant wählen » Standorte » Germany (Standard) » Dokumente » Lieferschein* bzw.*Rücksendeschein* im Tab *Vorlage* im Bereich *Optionale Elemente unter Artikelpositionstabelle* ausblenden, indem Sie die Option *NEIN* wählen. +
Bei Netto Marken-Discount, GartenXXL.de und GartenXXL.at werden die externe Auftragsnummer und die externe Kundennummer jedoch auch eingeblendet, wenn hier die Option *NEIN* gewählt wurde.
====

[IMPORTANT]
.Hinweistext wird ausgeblendet
====
Den Hinweistext, den Sie im Menü *System » Mandant » Mandant wählen » Standorte » Germany (Standard) » Dokumente » Lieferschein* bzw. *Rücksendeschein* im Tab *Vorlage* im Bereich *Optionale Elemente unter Artikelpositionstabelle* im Feld *Hinweis* eingeben können, wird auf Dokumenten mit der Auftragsherkunft Netto Marken-Discount, GartenXXL.de und GartenXXL.at ausgeblendet. Das Ausblenden des Hinweistextes ist von Netto eStores so gewünscht.
====
