= Plus.de und GartenXXL.de
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plus.de, GartenXXL.de, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zu den Marktplätzen Plus.de und GartenXXL.de in Ihrem plentymarkets System ein.
:position: 190

link:https://www.plus.de/[**Plus.de**^] bietet umfangreiche Sortimente aus den Bereichen Wohnen, Garten und Baumarkt, Freizeit, Wellness, Haushalt, Multimedia und Wein (Quelle: www.plus.de). Seit April 2014 sind die E-Commerce-Aktivitäten der Plus Online GmbH unter der neuen Firmierung Tengelmann E-Stores GmbH zusammengefasst.

link:http://www.gartenxxl.de/[**GartenXXL**^] ist eine Marke der Tengelmann E-Stores GmbH. Auf GartenXXL werden Geräte bekannter Firmen und wissenswerte Informationen zur Gartenpflege angeboten (Quelle: www.gartenxxl.de).

[#100]
== Bei Plus.de registrieren

Bevor Sie Plus.de in Ihrem plentymarkets System einrichten, müssen Sie sich zunächst auf der link:https://www.plus.de/is-bin/INTERSHOP.enfinity/WFS/Plus-PlusDE-Site/de_DE/-/EUR/ViewData-Start/1263070838?JumpTarget=ViewUser-New&=&=&=[**Webseite von Plus.de**^] registrieren. Ansprechpartner für die Registrirung: +
Katrin.Beer@netto-online.de +
Christian.Mertens@netto-online.de

[#200]
== Plus.de in plentymarkets einrichten

Um Artikel auf Plus.de verkaufen zu können, müssen Sie den Marktplatz zunächst in plentymarkets einrichten. Gehen Sie dazu wie im Folgenden beschrieben vor:

[.instruction]
Plus.de in plentymarkets einrichten:

. Öffnen Sie das Menü **System » Märkte » Plus.de**. +
→ Das Tab **Einstellungen** wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen.

.Einstellungen des Marktplatzes Plus.de
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Automatischen Datenaustausch aktivieren**
|**Ja** wählen, um den automatischen Datenaustausch zu aktivieren oder **Nein**, um ihn zu deaktivieren.

////|**Artiklexport aktivieren**
|**Ja** wählen, um den automatischen Artikelexport zu aktivieren oder **Nein**, um ihn zu deaktivieren.

|**Bestandsabgleich aktivieren**
|**Ja** wählen, um den automatischen Bestandsableich zu aktivieren oder **Nein**, um ihn zu deaktivieren.////

2+|Vertriebspartner-Information

|**Lieferantennummer**
|Lieferantennummer eingeben, wie von Plus.de erhalten.

2+|Artikeleinstellungen

|**Artikelname**
|Artikelname wählen, der an Plus.de übertragen wird.

|**Artikelkurzbeschreibung**
|Artikelkurzbeschreibung wählen, die an Plus.de übertragen wird.

|**Artikelbeschreibung**
|Artikelbeschreibung wählen, die an Plus.de übertragen wird.

|**Artikel-EAN**
|Artikel-EAN wählen, die an Plus.de übertragen wird.

|**Varianten-EAN**
|Varianten-EAN wählen, die an Plus.de übertragen wird.

|**Bildposition für das Energieetikett**
|Ziffer der Bildposition des Artikelbildes eingeben, wenn das Energieetikett nicht als Merkmal, sondern als Artikelbild erstellt wurde. Details zum Energieetikett siehe Kapitel <<omni-channel/multi-channel/plus-gartenxxl#90, **Energieeffizienz-Merkmale erstellen**>>.

|**Menge für Artikel ohne Bestandsbindung**
|Bei Artikeln mit der Einstellung **keine Beschränkung** wird der Maximalwert aus realem Bestand und der hier definierten Menge übermittelt. +
Beispiel: Einstellung 0, Nettowarenbestand 8. plentymarkets übermittelt 8. +
Artikel mit der Einstellung **Beschränkung auf Nettowarenbestand** werden hier nicht berücksichtigt.

|**Menge für Artikel ohne Bestandsbeschränkung, falls der Bestand 0 ist**
|Zahl eingeben, die als Bestand für Artikel ohne Bestandsbeschränkung, bei denen der Bestand 0 ist, übertragen werden soll.

|**Standardlieferzeiten**
|Durchschnittliche Lieferzeit in Tagen eingeben.

|**Artikel-Lieferzeit 1 - 5**
|Durchschnittliche Lieferzeiten in Tagen für die Artikelverfügbarkeiten 1 - 5 eingeben. +
**Wichtig:** Nur eindeutige Angaben sind möglich (d.h. keine Zeiträume wie 2-3).

|**Standardprovision in Prozent**
|Provisionswert eingeben, der mit Plus.de vereinbart wurde.

2+|Zusatztexte

|**Zum Merkmal ...**
|Zusatzinformationen zu Merkmalen eingeben (optional). Merkmale werden erst angezeigt, nachdem Sie sie im Menü **System » Artikel » Merkmale** erstellt haben.

2+|Bestelleinstellungen

|**Mindestbestellmenge**
|Artikelanzahl eingeben, wenn eine Mindestbestellmenge gewünscht ist.

|**Maximale Bestellmenge**
|Artikelanzahl eingeben, wenn eine maximale Bestellmenge gewünscht ist.

|**Artikelnamen in Auftragspositionen**
|Wählen, ob der Artikelname in den Auftragspositionen von Plus.de oder aus dem Shop übernommen werden soll.

2+|SFTP-Einstellungen

|**Benutzername**
|Benutzername eingeben, wie von Plus.de erhalten.
|====

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit Plus.de verknüpfen können, muss im Menü **System » Aufträge » Auftragsherkunft** die Auftragsherkunft Plus.de aktiviert werden.

[.instruction]
Auftragsherkunft für Plus.de aktivieren:

. Öffnen Sie das Menü **System » Aufträge » Auftragsherkunft**.
. Setzen Sie bei **Plus.de** ein Häkchen.
. **Speichern** Sie die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf Plus.de verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID**>> im Tab **Verfügbarkeit** aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Plus.de einstellen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen**.
. Aktivieren Sie die Hauptvariante im Bereich **Verfügbarkeit**.
. Wechseln Sie in das Tab **Verfügbarkeit**.
. Klicken Sie im Bereich **Märkte** in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktivieren Sie die Option **Plus.de**.
. Wenn Sie den Artikel auch auf **GartenXXL** verkaufen möchten, aktivieren Sie außerdem die Option **GartenXXL.de**.
. Aktivieren Sie die Option Web-API.
. Klicken Sie auf **Hinzufügen**. +
→ Der Marktplatz wird hinzugefügt.
. **Speichern** Sie die Einstellungen. +
→ Der Artikel ist auf Plus.de verfügbar.

Die Verfügbarkeit für Varianten kann im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit** individuell angepasst werden.

[#330]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID**>> im Tab **Verfügbarkeit** fügen Sie, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen**.
.  Wechseln Sie in das Tab **Verfügbarkeit**.
.  Klicken Sie im Bereich **SKU** auf **Hinzufügen**. +
→ Das Bearbeitungsfenster **Neue SKU** wird angezeigt.
.  Wählen Sie die Herkunft **Plus.de**.
.  Geben Sie die SKU ein.
.  Klicken Sie auf **Hinzufügen**. +
→ Die SKU wird gespeichert und angezeigt.

[#350]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft Plus.de bzw. GartenXXL einen Verkaufspreis festzulegen. Dieser Preis wird auf Plus.de bzw. GartenXXL angezeigt.

[.instruction]
Verkaufspreis für Plus.de bzw. GartenXXL festlegen:

. Öffnen Sie das Menü **System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen**.
. Setzen Sie ein Häkchen bei der Herkunft **Plus.de** bzw. **GartenXXL**.
. **Speichern** Sie die Einstellungen.

[#400]
== Zahlungsart aktivieren

Aktivieren Sie die **<<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsart>>****Plus.de**, wie im Folgenden beschrieben. Nehmen Sie anschließend die Einstellungen für die Zahlungsart **GartenXXL.de** auf die gleiche Weise vor.

[.instruction]
Zahlungsart Plus.de aktivieren:

. Öffnen Sie das Menü **System » Aufträge » Zahlung » Zahlungsarten**.
. Klicken Sie auf den Ordner **DE &gt; Plus.de**. +
→ Die Einstellungen für die Plus.de-Zahlungsart wird angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 2.
. Setzen Sie ein Häkchen bei der Option **Aktiv**.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Zahlungsart
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Sprache**
|Folgende Optionen werden sprachabhängig gespeichert: **Name**, **Infoseite**, **Infoseite (Intern)**, **Logo** und **Logo hochladen**. Damit ist es möglich, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|**Name**
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|**Infoseite**
|Als Information zur Zahlungsart eine Kategorieseite vom Typ **Content** oder die URL einer Webseite eingeben.

|**Infoseite (Extern)**
|Wenn unter **Infoseite** die Einstellung **Infoseite (Extern)** gewählt wurde, hier die URL der Infoseite eingeben.

|**Lieferländer**
|Kein Lieferland wählen. +
Sie können die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig konfiguriert.

|**Logo**
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
**Standardlogo anzeigen** = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
**Kein Logo anzeigen** = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
**Upload-Logo anzeigen** = Blendet die Optionen **Logoansicht** und **Logo hochladen** ein.

|**Logoansicht**
|Wenn unter **Logo** die Option **Upload-Logo anzeigen** gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|**Logo hochladen**
|Wenn unter **Logo** die Option **Upload-Logo anzeigen** gewählt wurde, hier ein externes Logo hochladen. +
Auf **Dateien hochladen** klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|**Priorität**
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|**Kosten: Pauschal oder Prozentual**
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. Wichtig: Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen finden Sie auf den Handbuchseiten **<<basics/statistik#, Statistik>>** und **<<basics/statistik/allgemeine-statistiken/artikel/renner-und-penner#, Renner und Penner>>**. Ein Beispiel für pauschale und prozentuale Kosten finden Sie auf der Handbuchseite **<<auftragsabwicklung/payment/zahlungsarten-verwalten#20, Grundeinstellungen>>**.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü **System » CRM » Kundenklassen** aktivieren oder deaktivieren Sie **erlaubte Zahlungsarten**. +
Weitere Informationen finden Sie im Kapitel **<<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Zahlungsarten und Kundenklassen>>**.
====

Weitere Informationen finden Sie auf der Handbuchseite **<<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsarten>>**.

[#500]
== Kategorien verknüpfen

Damit Ihre Artikel auf den Marktplätzen Plus.de und GartenXXL.de zum Verkauf angezeigt werden, müssen Sie Kategorieverknüpfungen erstellen. Die dafür erforderlichen Plus.de- und GartenXXL.de-Kategorie-IDs erhalten Sie von Plus.de. Erstellen Sie wie im Folgenden beschrieben Verknüpfungen, damit Ihre Artikel in den <<artikel/kategorien#, **Kategorien**>> bei Plus.de und GartenXXL.de angezeigt werden.

[.instruction]
Kategorien verknüpfen:

. Öffnen Sie das Menü **System » Märkte » Plus.de**.
. Wechseln Sie in das Tab **Kategorien aktivieren**.
. Geben Sie in den Spalten **Plus.de-Kategorienverknüpfung** und **GartenXXL.de-Kategorienverknüpfung** die IDs der Kategorien ein, die am besten zu Ihren Webshop-Kategorien passen. +
→ Die Plus.de- und GartenXXL.de-Kategorie-IDs entnehmen Sie den Kategoriedateien, die Sie von Plus.de erhalten haben.
. Aktivieren Sie die Kategorien.
. **Speichern** Sie die Einstellungen.

[#600]
== Hersteller verknüpfen

Damit Ihre Artikel auf den Marktplätzen Plus.de und GartenXXL.de zum Verkauf angezeigt werden, müssen Sie Ihre <<artikel/artikel-verwalten#560, **Hersteller**>> verknüpfen. Sie erhalten von Plus.de eine Datei mit Hersteller-IDs.

[.instruction]
Hersteller verknüpfen:

. Öffnen Sie das Menü **System » Artikel » Hersteller**.
. Öffnen Sie den Hersteller.
. Geben Sie im Feld **Plus.de-ID** die ID ein. +
→ Die Plus.de-Hersteller-ID entnehmen Sie der Datei, die Sie von Plus.de erhalten haben.
. **Speichern** Sie die Einstellungen.

[#700]
== Merkmale erstellen

Mit <<artikel/artikel-verwalten#480, **Merkmalen**>> verknüpfen Sie bestimmte Eigenschaften, die Sie für die Konfiguration des Marktplatzes Plus.de benötigen, mit Ihren Artikeln. Sie tragen bei Bedarf von den Standardeinstellungen abweichende Provisionen und Kategorieverknüpfungen auf Artikelebene ein. Über Merkmalfilter übermitteln Sie außerdem Artikelinformationen an Plus.de und legen Filter für die Artikelsuche auf Plus.de fest.

Wie im Kapitel **<<omni-channel/multi-channel/plus-gartenxxl#50, Kategorien verknüpfen>>** beschrieben, geben Sie im Menü **System » Märkte » Plus.de** im  Tab **Kategorien aktivieren** die Standardkategorieverknüpfungen ein. Um bestimmten Artikeln bei Bedarf eine andere Kategorie zuzuweisen, verwenden Sie das **<<artikel/artikel-verwalten#480, Merkmal>>****Artikel-Kategorieverknüpfung für GartenXXL.de** bzw. **Artikel-Kategorieverknüpfung für Plus.de**.

[.instruction]
Merkmal erstellen:

. Öffnen Sie das Menü **System » Artikel » Merkmale**.
. Wechseln Sie in das Tab **Neues Merkmal**.
. Geben Sie einen Namen unter **Backendname** ein.
. Wählen Sie den Merkmaltyp **Text**.
. Wählen Sie das Plus.de-Merkmal **Artikel-Kategorieverknüpfung für GartenXXL.de** oder **Artikel-Kategorieverknüpfung für Plus.de** aus dem Dropdown-Menü.
. **Speichern** Sie die Einstellungen.

[#800]
=== Provisionssätze auf Artikelebene einstellen

Im Menü **System » Märkte » Plus.de** geben Sie für den Marktplatz Plus.de einen Standardprovisionssatz ein. Da für bestimmte Plus.de-Warengruppen jedoch andere Provisionen gelten können, haben Sie die Möglichkeit, auf Artikelebene einen abweichenden Provisionssatz einzugeben. Dies wird mit dem **<<artikel/artikel-verwalten#480, Merkmal>>****Provision in Prozent** umgesetzt. Diese Einstellung hat Priorität gegenüber der eingegebenen Standardprovision. Beachten Sie, dass Sie diesen Prozentsatz im Vorfeld mit Plus.de abstimmen müssen.

[.instruction]
Merkmal erstellen:

. Öffnen Sie das Menü **System » Artikel » Merkmale**.
. Wechseln Sie in das Tab **Neues Merkmal**.
. Geben Sie einen Namen unter **Backendname** ein.
. Wählen Sie den Merkmaltyp **Text**.
. Wählen Sie das Plus.de-Merkmal **Provision in Prozent** aus dem Dropdown-Menü.
. **Speichern** Sie die Einstellungen.

[TIP]
.Merkmale: Filter
====
Filter haben bei Plus.de zwei Funktionen: Sie übermitteln damit Artikelinformationen an Plus.de und können den Artikel bei Plus.de über diesen Filter finden. Nach Auswahl eines Filters wird ein weiteres Dropdown-Menü angezeigt. Wählen Sie hier das Filtermerkmal, das einem Artikel zugeordnet werden soll. +
Hinweis: Das Merkmal **Energieeffizienz** ist nur für den Marktplatz Plus.de verfügbar.
====

[#900]
=== Energieeffizienz-Merkmale erstellen

Für die Auszeichnung Ihrer Artikel für Plus.de gemäß der neuen Verordnung der EU zur Energieeffizienzrichtlinie sind ab 1.1.2015 Angaben zur Energieeffizienz sowie die Bereitstellung von Produktdatenblättern vorgeschrieben. Erstellen Sie dazu die folgenden drei <<artikel/artikel-verwalten#500, **Merkmale**>>: **Energieeffizienzklasse**, **Energieetikett** und **Produktdatenblatt**.

[.instruction]
Merkmal Energieeffizienzklasse erstellen:

. Öffnen Sie das Menü **System » Artikel » Merkmale**.
. Wechseln Sie in das Tab **Neues Merkmal**.
. Geben Sie einen Namen unter **Backendname** ein.
. Wählen Sie den Merkmaltyp **Kein**.
. Wählen Sie die Option **Energieeffizienz** aus dem Dropdown-Menü **Plus.de-Merkmal**. +
→ Ein weiteres Dropdown-Menü wird geöffnet.
. Wählen Sie die Energieeffizienzklasse.
. **Speichern** Sie die Einstellungen.

Für die Merkmale Energieetikett und Produktdatenblatt wählen Sie den Merkmaltyp **Datei**. Im Dropdown-Menü **Plus.de-Merkmal** wählen Sie dann die Option **Energieetikett** bzw. **Produktdatenblatt**. Im Folgenden wird beispielhaft beschrieben, wie Sie das Merkmal Energieetikett erstellen. Erstellen Sie anschließend das Merkmal Produktdatenblatt auf die gleiche Weise.

[.instruction]
Merkmal Energieetikett erstellen:

. Öffnen Sie das Menü **System » Artikel » Merkmale**.
. Wechseln Sie in das Tab **Neues Merkmal**.
. Geben Sie einen Namen unter **Backendname** ein.
. Wählen Sie den Merkmaltyp **Datei**.
. Wählen Sie die Option **Energieetikett** aus dem Dropdown-Menü **Plus.de-Merkmal**.
. **Speichern** Sie die Einstellungen.

Die Merkmale verknüpfen Sie dann wie im Folgenden beschrieben im Tab <<artikel/artikel-verwalten#80, **Merkmale**>> eines Plus.de-Artikels.

[.instruction]
Energieeffizienz-Merkmale mit Plus.de-Artikel verknüpfen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab **Merkmale**.
. Aktivieren Sie die soeben erstellten Merkmale **Energieeffizienzklasse**, **Energieetikett** und **Produktdatenblatt**.
. **Speichern** Sie die Einstellungen. +
→ Die Merkmale werden mit dem Artikel verknüpft und sind im Bereich **Merkmale** sichtbar.
. Laden Sie beim Merkmal **Energieetikett** die Bilddatei des Energieetiketts hoch.
. Laden Sie beim Merkmal **Produktdatenblatt** die PDF-Datei des Produktdatenblatts hoch.
. **Speichern** Sie die Einstellungen.

Alternativ zur Verknüpfung mit dem Merkmal **Energieetikett** können Sie das Energieetikett im Tab <<artikel/artikel-verwalten#90, **Bilder**>> des Artikels speichern. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Energieetikett alternativ im Tab Bilder speichern:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab **Bilder**.
. Fügen Sie die Bilddatei des Energieetiketts entweder über **Dateien auswählen** oder per Drag &amp; Drop-Funktion hinzu.
. **Speichern** Sie die Einstellungen.
. Öffnen Sie das Menü **System » Märkte » Plus.de**.
. Geben Sie die Positionsnummer des Bildes im Tab **Einstellungen** bei der Option **Bildposition für das Energieetikett** ein (Tabelle 1).
. **Speichern** Sie die Einstellungen.

[#1000]
== Versandbestätigungen automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, **Ereignisaktion**>> ein, um Versandbestätigungen automatisch an Plus.de zu senden, nachdem ein Warenausgang gebucht wurde. Die Versandbestätigung an Plus.de erfolgt automatisch mit dem Wechsel auf Status **[7] Warenausgang gebucht**. Der Käufer wird durch Plus.de über den Versand benachrichtigt.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **System » Aufträge » Ereignisse**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 3.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 3 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an Plus.de
[cols="a,a,a"]
|====
| Einstellung | Option | Auswahl

|**Ereignis**
|**Auftragsänderung: Warenausgang gebucht**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|**Plus.de** und **GartenXXL.de**

|**Aktion**
|**Versand &gt; Versandbestätigung an Plus.de senden**
|
|====

[#1100]
== Stornierungen automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, **Ereignisaktion**>> ein, um Stornierungen automatisch an Plus.de zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **System » Aufträge » Ereignisse**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 4.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 4 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an Plus.de
[cols="a,a,a"]
|====
| Einstellung | Option | Auswahl

|**Ereignis**
|**Auftragsänderung: Statuswechsel &gt; [8] Storniert**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|**Plus.de** und **GartenXXL.de**

|**Aktion**
|**Zahlungsarten &gt; Stornierung an Plus.de senden**
|
|====

[#1200]
== Retouren automatisch senden

Richten Sie eine **<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>** ein, um Retouren automatisch an Plus.de zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **System » Aufträge » Ereignisse**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 5.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 5 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Retouren an Plus.de
[cols="a,a,a"]
|====
| Einstellung | Option | Auswahl

|**Ereignis**
|**Auftragsanlage: Neue Retoure**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Retoure**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|**Plus.de** und **GartenXXL.de**

|**Aktion**
|**Retoure &gt; Retoure an Plus.de senden**
|
|====

[#1300]
== Lieferscheine und Rücksendescheine erstellen

Die folgenden Informationen gelten nur für Lieferscheine und Rücksendescheine bei Plus.de und GartenXXL.de. Sie sind für andere Marktplätze nicht gültig.

[IMPORTANT]
.Rechnungen werden von Plus.de versendet
====
Plus.de versendet die Rechnung an den Kunden. Deshalb erhalten Sie von Plus.de die Lieferadresse, aber nicht die Rechnungsadresse des Kunden. Die von Plus.de übertragene Lieferadresse wird in plentymarkets als Liefer- und Rechnungsadresse hinterlegt. Sie schicken die Ware an diese Adresse.
====

Gehen Sie wie im Folgenden beschrieben vor, um **<<auftragsabwicklung/auftraege/auftragsdokumente#170, PDF-Vorlagen>>** für Lieferscheine und Rücksendescheine für Plus.de und GartenXXL.de zu erstellen. Im Folgenden wird das Anlegen eines Lieferscheins für Plus.de beispielhaft beschrieben. Gehen Sie anschließend auf die gleiche Weise vor, um einen Rücksendeschein für Plus.de anzulegen und um diese beiden Dokumente auch für GartenXXL.de anzulegen. Alle PDF-Vorlagen, die Sie erstellen, müssen das Logo von Plus.de bzw. GartenXXL.de enthalten. Fordern Sie die Logos direkt bei Plus.de an.

[.instruction]
Lieferschein für Plus.de erstellen:

. Öffnen Sie das Menü **System » Mandant » Mandant wählen » Standorte » Germany (Standard) » Dokumente » Lieferschein**.
. Wechseln Sie in das Tab **PDF-Vorlage &gt; Neue Vorlage**.
. Wählen Sie aus dem Dropdown-Menü **Zahlungsart** die Option **Plus.de**.
. Klicken Sie in der Zeile **Datei** auf **Datei auswählen**.  +
→ Laden Sie die PDF-Vorlage hoch.
. **Speichern** Sie die Einstellungen.

[IMPORTANT]
.Pflichtangabe auf Dokumenten für Plus.de und GartenXXL.de
====
Die externe Auftragsnummer und die externe Kundennummer sind Pflichtangaben auf Dokumenten, die zu einem Auftrag der Herkunft Plus.de oder GartenXXL.de gehören. Normalerweise können Sie diese Angaben im Menü **System » Mandant » Mandant wählen » Standorte » Germany (Standard) » Dokumente » Lieferschein** bzw.**Rücksendeschein** im Tab **Vorlage** im Bereich **Optionale Elemente unter Artikelpositionstabelle** ausblenden, indem Sie die Option **NEIN** wählen. +
Bei Plus.de und GartenXXL.de werden die externe Auftragsnummer und die externe Kundennummer jedoch auch eingeblendet, wenn hier die Option **NEIN** gewählt wurde.
====

[IMPORTANT]
.Hinweistext wird ausgeblendet
====
Den Hinweistext, den Sie im Menü **System » Mandant » Mandant wählen » Standorte » Germany (Standard) » Dokumente » Lieferschein** bzw. **Rücksendeschein** im Tab **Vorlage** im Bereich **Optionale Elemente unter Artikelpositionstabelle** im Feld **Hinweis** eingeben können, wird auf Dokumenten mit der Auftragsherkunft Plus.de und GartenXXL.de ausgeblendet. Dies ist von Plus.de so gewünscht.
====
