= Creating eBay properties
:lang: en
include::{includedir}/_header.adoc[]
:keywords: listing, ElasticSync, eBay, eBay property, property, ItemSpecifics
:position: 40
:url: data/importing-data/elasticsync-best-practices/best-practices-elasticsync-listing-properties
:id: AAQM038

In this best practice you will learn how to add eBay properties to your listings with ElasticSync.

== Exporting listings

First export the listings that you want to add properties to. You need a CSV file containing your listings in order to add the eBay properties. To do so, use the dynamic export in the *Data » Dynamic export* menu to create a data format of the type *ItemListingMarketEbay*. The properties can then be exported with this data format. +

The fields *EbayItemSpecificsName* and *EbayItemSpecificsValue* are required to create eBay properties.

[instruction]
Creating a data format:

. Go to *Data » Dynamic export*.
. Click on *New data format*. +
→ A view for editing the data format opens.
. Select *ItemListingMarketEbay* from the *Data format type* drop-down list.
. Enter a *Data format name*.
. Place check marks next to *EbayItemSpecificsName*, *EbayItemSpecificsValue*, and *MLID*. These fields are required to export listing properties.
. *Save* the data format after you have carried out further settings, if desired.

After having created the data format *ItemListingMarketEbay*, click on *Export data* to generate the CSV file. +

Save the CSV that you have created on your computer and edit it.

[TIP]
.Pay attention to the format of the CSV file
====
Pay attention to the format of the entries in the CSV file that should be imported into plentymarkets. +
Multiple entries have to be separated by comma. +
_Example:_ Enter the values "Colour", "Size" into the *name* column separated by comma. Enter the corresponding values "Green", "XXL" into the *value* column separated by comma.
====

== Importing eBay properties into plentymarkets with ElasticSync

ElasticSync enables you to import the CSV file containing the new properties into plentymarkets. This is done in the *Data » ElasticSync* menu. To import the properties, create a sync of the type *Market listing*.

[instruction]
Creating a sync:

. Go to *Data » Elastic Sync*.
. Click on *Add sync*. +
→ A section in which the sync can be edited opens.
. Enter a name for the sync.
. Select *Market listing* from the *Type* drop-down list.
. In the *Import* section, you can leave the settings as they are.
. In the *Separator* section, select the option *Tab* instead of the semicolon.
. In the *Source* section, select the option *HTTP*. +
→ Three further lines are displayed.
. Select the option *Data upload* from the *HTTP options* drop-down list.
. In the line *URL*, click on the button with the three dots (*Select file*). +
→ A new window opens.
. Click on *Upload file*, select the CSV file with the eBay properties that you have created, and click on *Open*.
. Place a check mark in the line of the file and click once in the line of the file. +
→ _Important:_ The line must be clicked a second time. Once the line is displayed in blue, you can upload it by clicking on *Select*. +
→ The URL – i.e. the path that you uploaded the CSV file from – is now displayed in grey in the field *URL*.
. *Save* the settings.

You have uploaded the CSV file successfully. Next, carry out the matching and mapping settings.

[instruction]
Carrying out the matching settings:

. Click on *Matching* on the left-hand side.
. Select *MLID* for the matching field *Market listing ID*.
. In the *Import options* section, select the option *Only import new data*.
. Select the decimal number and the date format, if required.
. *Save* the settings.

Next, carry out the settings for mapping.

[instruction]
Carrying out the mapping settings:

. Click on *Mapping* on the left-hand side.
. Click on the plus sign (*Add mapping*).
. Enter a *name*.
. *Save* the settings. +
→ The *Import data / plentymarkets data fields* section opens.

In this area, you assign the fields from your CSV file to the data fields in plentymarkets. +

In the *Import data* section on the left-hand side, you can see the header names from your CSV file. plentymarkets has taken these names automatically from your CSV file. In the *plentymarkets data fields* section on the right-hand side, you have to select the corresponding counterpart from the list.

[instruction]
Example: Assigning sources for eBay properties to the appropriate plentymarkets data fields

. On the left side, you can see the source *MLID*. Click in the same line on the right-hand side and assign the *MLID* data field by placing a check mark.
. Assign the data field *Market listing property / Name* to the source *EbayItemSpecificsName* by placing a check mark.
. Assign the data field *Market listing property / Value* to the source *EbayItemSpecificsValue* by placing a check mark.
. Activate all lines with the toggle button *Activate row* on the left-hand side. +
→ _Important:_ The data fields to be imported must all be activated in order for the mapping to work correctly.
. *Save* the settings.
. Click on *Preview* in order to display a preview of the file and to check the content.
. Click on *Run Sync* in order to import the properties into plentymarkets.
