= Best Practices: Property links
:lang: en
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, import, items, best practice, automated, properties, property links
:position: 40

== Exporting and importing property links

This chapter describes how to export and import property links.

NOTE: To benefit from this best practice, you should be familiar the basic functionality of ElasticSync. Check the <<basics/data-exchange/ElasticSync/ElasticSync-plugin#, Importing data with ElasticSync>> page of the manual for general information about how the plugin works.


[#export_property_links]
=== Exporting property links

==== Creating the format in the FormatDesigner

The properties currently linked to variations can be exported using the FormatDesigner. To do so, go to *Data » FormatDesigner* and create a new format of the type *Item*.

After that, select the data fields:

* To allow mapping during import, from the *Item* area select the *ID* of the item or from the *Variation* area select the *ID* or the *Number* of the variation.

* You then add the actual property links in the *VariationProperty* area:

You can select between 3 values:

- *value*: Returns the value of the property mapped in the format.
- *all*: Returns all linked properties of an item with values.
- *allIds*: Returns all linked property IDs of an item without any values.

After you have saved the format, you can set up the export in the elastic export.

==== Setting up the export in the elastic export

Go to *Data » Elastic export* to set up the export of the format you created.

To do so, click on *New export* and save a name, the type *Item*, the format you created, a limit and a file name.

[TIP]
.Exporting the file in CSV format
====
If you want to download the file in CSV format, specify the suffix *.csv* as part of the file name.
====

Once you save the format, you are done setting it up.

==== Exporting data

There are several ways of exporting the data:

* In the export, click *Download*.
* Open the URL in a browser.
* In the export overview, click *Download*.

[#import_property_links]
=== Importing property links

==== Creating the sync in ElasticSync

To import the property links, you can go to *Data » ElasticSync* and create a sync of the type *Item*. Alternatively, you can add the fields to an existing sync.

The synchronisation can be based on a variation-specific field, for example the *Variation number*, or based on the *item ID* if the links are created using a separate sync.

In the mapping of the sync, you can select different fields to create or edit the links. For example, you can add the fields *ID, Value and Language* (you need to add all 3 fields) or instead the field *Property combination*. The latter must be structured as follows in the file:

*InternalName1:Value1:Language;InternalName2:Value2:Language*

If you want to delete property links, use the field *Delete (Yes/No)*. In the file, the value *1* must be specified if the links are to be deleted. Specify the value *0* if you do not want to delete the link.

That is all you need for the link. The sync is now ready to go and you can start linking properties.
