= Contact data
:lang: en
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, import, best practice, automated, contacts, contact, customer, customers, customer data
:position: 60
:url: data/importing-data/elasticsync-best-practices/best-practices-elasticsync-contact-data

[#contact-data]
== Importing contact data

In this chapter, we describe how to import contact data in plentymarkets. You need a CSV file with the data that you would like to import. Save this file on your computer. Then, proceed as follows.

[TIP]
.Structure of the file: Example with sample data.
====
Click on this link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/ElasticSync_BestPractice/BP_Musterdaten_Kontaktdaten.csv.zip[link^] to open an example file with sample data that you can use to test the import of contact data.
====

[.instruction]
Carrying out the basic settings:

. Go to *Data » Elastic Sync NEW*.
. Click on the plus sign (*Add sync*).
. Enter a name in the area *Basic data*.
. Select from the drop-down list *Type* the option *Contacts, companies, addresses*.
. In the area *Import*, you can leave the settings as they are.
. In the area *Separator*, select the option *Tab* instead of the semicolon.
. In the area *Source*, select the option *HTTP*. +
→ Three further lines are displayed.
. Select from the drop-down list *HTTP options* the options *Data upload*.
. Click in the line *URL* on the button with the three dots (*Select file*). +
→ A new window opens.
. Click on *Upload file*, select the CSV file with the contact data that you would like to import and click on *Open*.
. Place a check mark in the line of the file and click once in the line of the file. +
→ *_Important:_* The line must be clicked a second time. Only when the line is displayed in blue can you upload it by clicking on *Select*. +
→ The URL – i.e. the path from that you uploaded the CSV file – is now displayed in grey in the field *URL*.
. *Save* the settings.

You have uploaded the CSV file successfully. In the following, carry out the matching and mapping settings.

[.instruction]
Setting the matching:

. Click on *Matching* on the left side.
. In the area *Matching*, you must assign at least one of the four available options to one of the fields from the CSV file. +
*_Note:_* If there is no contact ID available yet, it makes sense to carry out the matching via the email address.
. In the area *Import options*, select the option *Only import new data*.
. Select the decimal number and the date format, if required.
. *Save* the settings.

Now adjust the settings for mapping.

[.instruction]
Setting the mapping:

. Click on *Maping* on the left side.
. Click on the plus sign (*Add mapping*).
. Enter a name.
. *Save* the settings. +
→ The area *Import data/ plentymarkets data fields* opens.

In this area, you assign the fields from your CSV file to the fields in plentymarkets. On the left side in the area *Import data* you can see the header names from your CSV file. plentymarkets has already taken these names automatically from your CSV file.

On the right side in the area *plentymarkets data fields*, you have to select the corresponding counterpart from the list.

[TIP]
.Mandatory fields for contact data
====
When importing contact options the fields *Type* and *Referrer* are mandatory fields. These two fields are marked with an asterisk (***).
====

[.instruction]
Example: Assigning the source *First name* to the appropriate plentymarkets data field

. On the left side, you can see the source *First name*. Click on the right side in the same line and enter *First name* in the search field.
. Click on *First name*.
. Click on the green tick (*Select*) below the list.
. Activate the toggle button in this line on the left (*Activate line*). +
*_Important:_* The data fields to be imported must all be activated in order for the mapping to work correctly.
. Click on the button *Field* on the bottom left side.
. Select from the drop-down list *Own value*.
. Enter the value 0 or 1. +
→ 0 is the referrer *Manual entry* and 1 is the referrer *Online store*.
. Enter *Referrer* on the right side in the search field.
. Click on *Referrer**.
. Click on the green tick (*Select*) below the list.
. Activate the toggle button in this line on the left side (*Activate line*). +
. *Save* the settings.

Click on *Preview* in order to display a preview of the file and to check the content.

Last, but not least: click on the play button (*Execute sync*). Depending on the data volume to be imported, this may take a while. Once the sync is carried out, the message *Sync finished* is displayed.

Now go to the *CRM » Contacts* menu in order to check whether the contact data was successfully imported.
