= Bestellvorgang
:lang: de
// include::{includedir}/_header.adoc[]
:keywords: Bestellvorgang, Webdesign, CMS
:position: 80

*CMS » Webdesign » Bestellvorgang*

== Inhalt dieser Seite

In den folgenden Kapiteln erhalten Sie allgemeine Informationen zum Webdesign sowie zu wichtigen Aspekten dieses Bereichs im Webshop.

== Struktur des Bestellvorgangs

Der Bestellvorgang bezeichnet den Prozess des Kaufens im Webshop von dem Augenblick an, in dem der Kunde einen Artikel in den Warenkorb legt, bis zu dem Moment, in dem der Kunde die Bestellung abschickt. Dieser Prozess wird in 3 Bereiche unterteilt, den <<omni-channel/online-shop/webshop-einrichten/_cms/webdesign/webdesign-bearbeiten/bestellvorgang/warenkorb#, Warenkorb>>, die anschließende <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-kaufabwicklung, Kaufabwicklung>> und die abschließende <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-bestellbestaetigung, Bestellbestätigung>>. Diese Bereiche sind auch hier im Bereich *Layout* abgebildet. Sie haben hinsichtlich der Gestaltung vielfältige Möglichkeiten, die wir in diesem Kapitel beschreiben.

[WARNING]
.Gesetzliche Anforderungen
====
Beachten Sie die seit 1.8.2012 geltenden gesetzlichen Anforderungen für den Bestellvorgang. Sie finden auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-kaufabwicklung, Kaufabwicklung>> in den Kapiteln 2 und 3 sowie auf der Seite <<omni-channel/online-shop/webshop-einrichten/_cms/webdesign/webdesign-bearbeiten/buttons/anpassung-an-die-button-loesung#, Anpassung an die Button-Lösung>>weitere Hinweise dazu. Hier finden Sie auch Details zu den Möglichkeiten, die Sie mit plentymarkets diesbezüglich haben. Beachten Sie dazu auch unseren link:https://www.plentymarkets.eu/blog/Onlinehandel-in-Deutschland-Buttonloesung-und-neue-Informationspflichten/b-882/[Blog].
====

== Grundeinstellungen

Sie können den Bereich *Bestellvorgang* individuell konfigurieren und z.B. entscheiden, welche Elemente dort angezeigt bzw. welche Funktionen aktiv sein sollen. Diese Einstellungen nehmen Sie im Menü <<omni-channel/online-shop/webshop-einrichten/bestellvorgang#, System » Mandant » Mandant wählen » Bestellvorgang » Einstellungen>> vor. In der Grundeinstellung Ihres Webshops ist bereits eine Standardkonfiguration hinterlegt.

[IMPORTANT]
.jQuery
====
In diesem Bereich sind jQuery-Funktionen integriert. Wenn Sie diese Funktionen anpassen oder erweitern möchten, beachten Sie die Hinweise auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/_cms/webdesign/syntax/jquery#, jQuery>>.
====

== Tracking-Funktionen

Durch die Integration von Tracking-Funktionen über Template-Variablen in Verbindung mit Tracking-Dienstleistern können Sie sich mit Hilfe detaillierter Statistiken einen Überblick zum Nutzungsverhalten der Besucher Ihres Webshops verschaffen und daraus geeignete Rückschlüsse für die Gestaltung und Entwicklung Ihres Webshops ziehen.

Nutzen Sie den Service von <<omni-channel/online-shop/webshop-einrichten/extras/universal-analytics#, Google Analytics>> oder anderen Tracking-Dienstleistern, wie <<omni-channel/online-shop/extras/conversion-tracking/etracker#, etracker>>, um diese Funktionen in Ihren Webshop zu integrieren.
