= plentymarkets CMS library
:lang: en
// include::{includedir}/_header.adoc[]
:position: 120

The link:https://github.com/plentymarkets/plenty-cms-library[plentymarkets CMS library^] is an open source project developed by plentymarkets. The project moves the logical JavaScript elements of the plentymarkets CMS to GitHub repository files. As such, it facilitates a clearer separation of layout and logic. The project's main goals were increased modularisation, testability, internationalisation and independence of JavaScript frameworks. +
You can find the project files on link:https://github.com/plentymarkets/plenty-cms-library[GitHub.com^]. You can download the files for free and contribute at any time. This page describes how to update the version of the plentymarkets CMS library used in your plentymarkets CMS.

== Updating the version of plentymarketsCMStools

All files of the plentymarkets CMS library are consolidated in the JavaScript file plentymarketsCMStools-x.x.x.js. You can find this file in the GitHub project folder */dist*. x.x.x stands for the current file version. You can check which version you are currently using in the <<omni-channel/online-store/setting-up-clients/cms#webspace, CMS » Webspace>> menu. Open the folder *layout » Your design » js » plenty*. Proceed as described below to update the version of the *plentymarketsCMStools-x.x.x.js* file in your plentymarkets CMS.

[WARNING]
.Compatibility
====
plentymarketsCMStools versions *0.9.x* are not compatible with versions *1.x.x*. If you already use a design in which the JavaScript file *plentymarketsCMStools-x.x.x.js* is embedded,
you can not update from *0.9.x* versions to any *1.x.x* versions.
====

=== Downloading the new version

Proceed as described below to download the latest version of the plentymarketsCMStools-x.x.x.js file from the GitHub repository.

[.instruction]
Downloading the new version:

. Open the GitHub repository link:https://github.com/plentymarkets/plenty-cms-library[plentymarkets CMS library^].
. Open the folder *dist*.
. Click on the file *plentymarketsCMStools-x.x.x.js*. +
→ The file's content is displayed.
. Right click on *Raw*.
. Select the option *Save target as...*.
. Save the file on your computer.

Download the file *plentymarketsCMStools-x.x.x.min.js* in the same way.

=== Uploading the new version

Proceed as described below to upload the new version of plentymarketsCMStools-x.x.x.js and plentymarketsCMStools-x.x.x.min.js into the webspace of your plentymarkets system.

[.instruction]
Uploading the new version:

. Go to *CMS » Webspace*.
. Open the folder *layout » Your design » js » plenty*. +
→ Expand the folders by clicking on the small plus sign on the left.
. Click on *Upload files*.
. Select the file *plentymarketsCMStools-x.x.x.js*, which you downloaded in the previous step. +
→ The file will be uploaded and displayed.

Upload the file *plentymarketsCMStools-x.x.x.min.js* in the same way.

=== Editing the version number in the JSON file

The dependencies of the Callisto Light design are saved in a JSON file. This file is in the same folder as the file plentymarketsCMStools-x.x.x.js. To use the latest version of the plentymarkets CMS library, you need to update its version number saved in this file. This JSON file is usually named *scripts-3.5.json*. However, for older plentymarkets designs this file is named *scripts.json* or *dependencies.json*. The content of these files is identical. Proceed as described below to update the version number.

[.instruction]
Editing the version number in the JSON file:

. Download the file *scripts-3.5.json* from your plentymarkets system.
. Open the file in a text editor.
. Edit the version number of plentymarketsCMStools-x.x.x.js to the version of the file you uploaded to the webspace.
. Save the edited file.
. Upload the updated file to the same folder of your plentymarkets system. +
→ Due to caching, it might take up to an hour before the new file version is displayed in the webspace.
