= Webspace
:lang: en
// include::{includedir}/_header.adoc[]
:position: 30

The webspace tool of the *CMS » Webspace* menu allows you to upload data to the plentymarkets server and make this data available to your customers. You can upload images, PDF documents and other files that are to be made available online for all visitors. Use this tool if you want to manage images for your design on the file level. For each design, create a subfolder of the *layout/* folder.

== Upload limitations

The following limitations apply to uploads:

* You can not upload PHP file types.
* You can only upload 10 MB at one time.

== Creating a new folder

You can expand the available folder structure by creating additional folders. To do so, proceed as follows.

[.instruction]
Creating a new folder:

. Select the desired target folder or the lowest level (= /).
. Click on *New folder*.
. Enter a *name* for the new folder.
. *Save* the settings.

== Uploading files

Proceed as described below to upload files to a folder.

[.instruction]
Uploading files:

. Select the target folder.
. Click on *Upload files*.
. Select the file(s) that you would like to upload.
. Click on *Open*.

== Alternatives to the webspace upload

You can also manage individual images using the <<omni-channel/online-store/setting-up-clients/cms#image-gallery, Image gallery>> menu. Alternatively, you can upload images and documents to the to the <<item/managing-categories#, Documents>> tab of the category where they are to be used.
