= Konstanten
:lang: de
// include::{includedir}/_header.adoc[]
:position: 90

In die Textfelder des Menüs *CMS » Konstanten* tragen Sie wiederkehrende Inhalte ein, die in das Design Ihres Webshops eingebunden werden können. Es stehen 25 Konstanten zur Verfügung. Die Verknüpfung über eine Konstante ermöglicht es, Inhalte wiederzuverwenden und zentral in diesem Menü zu bearbeiten anstatt diese Inhalte einzeln im Design anzupassen. Die Inhalte können HTML-Code oder JavaScript-Code enthalten. Auch <<omni-channel/online-shop/webshop-einrichten/_cms/einstellungen/artikel-galerie#, Artikel-Galerien>> werden mit Konstanten verknüpft.

== Konstanten definieren

Zunächst hinterlegen Sie einen Wert für die Konstante. Gehen Sie dazu wie unten beschrieben vor. Wenn Sie eine Konstante mit einer Artikel-Galerie verknüpfen, wird automatisch Code als *Wert* der Konstanten eingefügt. Tragen Sie deshalb für <<omni-channel/online-shop/webshop-einrichten/_cms/einstellungen/artikel-galerie#, Artikel-Galerien>> keinen Wert ein.

[.instruction]
Konstanten definieren:

. Öffnen Sie das Menü *CMS » Konstanten*.
. Tragen Sie die Inhalte in das Textfeld der gewünschten Konstante ein.
. *Speichern* Sie die Einstellungen. +
→ Die Inhalte können nun über die Konstante in den Webshop eingebunden werden.

[TIP]
.PHP-Skripte einbinden
====
PHP-Skripte können nicht als Konstante gespeichert werden. Legen Sie PHP-Skripte extern ab, z.B. auf einem FTP-Server. Hinterlegen Sie die Verlinkung zu diesem Skript als *Wert* der Konstanten, um das Skript so aufzurufen.
====

== Konstanten in Design einfügen

Binden Sie nun die Konstante in Ihren Webshop ein. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Konstante in Design einfügen:

. Öffnen Sie das Menü *CMS » Webdesign » Layout*.
. Öffnen Sie das gewünschte Template.
. Fügen Sie die Konstante an der Position in das Template ein, an der die Inhalte angezeigt werden sollen.
. *Speichern* Sie die Einstellungen.

Analog können Konstanten auch in Kategorien eingebunden werden.
