= plentymarkets CMS library
:lang: de
// include::{includedir}/_header.adoc[]
:position: 120

Die link:https://github.com/plentymarkets/plenty-cms-library[plentymarkets CMS library^] ist ein von plentymarkets entwickeltes Open-Source-Projekt.
Das Projekt lagert die logischen JavaScript-Elemente des plentymarkets CMS aus und ermöglicht so eine bessere Trennung von Layout und Logik. Innerhalb des Projekts wurde
Wert auf Modularisierung, Testbarkeit, Internationalisierung und Unabhängigkeit von JavaScript-Frameworks gelegt. +
Das Projekt liegt auf link:https://github.com/plentymarkets/plenty-cms-library[GitHub.com^] und kann kostenlos heruntergeladen und weiterentwickelt werden. Hier erfahren Sie, wie Sie neue Versionen der plentymarkets CMS library in Ihr plentymarkets CMS einbinden.

== plentymarketsCMStools Version aktualisieren

Das Projekt plentymarkets CMS library führt die Projektdateien in der JavaScript-Datei plentymarketsCMStools-x.x.x.js zusammen, die Sie im GitHub-Projektordner */dist* finden. Dabei steht x.x.x für die Dateiversion. Welche Version Sie aktuell verwenden, prüfen Sie im Menü <<omni-channel/online-shop/webshop-einrichten/_cms/webspace#, CMS » Webspace>> und dort im Ordner *layout » Ihr Design » js » plenty*. Gehen Sie wie unten beschrieben vor, um eine neue Version der Datei *plentymarketsCMStools-x.x.x.js* einzubinden. +

[WARNING]
.Kompatibilität
====
plentymarketsCMStools Versionen *0.9.x* sind nicht mit Versionen *1.x.x* kompatibel. Wenn Sie bereits ein Design verwenden, das die JavaScript-Datei *plentymarketsCMStools-x.x.x.js* einbindet,
ist es daher nicht möglich, von einer Version *0.9.x* auf Versionen *1.x.x* zu aktualisieren.
====

=== Neue Version herunterladen

Gehen Sie wie unten beschrieben vor, um die neue Version der plentymarketsCMStools-x.x.x.js aus dem GitHub-Repository herunterzuladen.

[.instruction]
Neue Version herunterladen:

. Öffnen Sie das GitHub-Repository link:https://github.com/plentymarkets/plenty-cms-library[plentymarkets CMS library^].
. Öffnen Sie den Order *dist*.
. Klicken Sie auf die Datei *plentymarketsCMStools-x.x.x.js*. +
→ Der Inhalt der Datei wird angezeigt.
. Rechtsklicken Sie auf *Raw*.
. Wählen Sie die Option *Ziel speichern unter...*
. Speichern Sie die Datei auf Ihrem Rechner.

Laden Sie die Datei * plentymarketsCMStools-x.x.x.min.js analog herunter.

=== Neue Version hochladen

Gehen Sie wie unten beschrieben vor, um die neue Version der plentymarketsCMStools-x.x.x.js und der plentymarketsCMStools-x.x.x.min.js in den Webspace Ihres plentymarkets Systems hochzuladen.

[.instruction]
Neue Version hochladen:

. Öffnen Sie das Menü *CMS » Webspace*.
. Öffnen Sie den Ordner *layout » Ihr Design » js » plenty*. +
→ Ordner klappen Sie auf, indem Sie links in der Übersicht auf das kleine Plus klicken.
. Klicken Sie auf *Dateien hochladen*.
. Wählen Sie die Datei *plentymarketsCMStools-x.x.x.js*, die Sie im vorherigen Schritt heruntergeladen haben. +
→ Die Datei wird hochgeladen und angezeigt.

Laden Sie die Datei plentymarketsCMStools-x.x.x.min.js analog hoch.

=== Versionsnummer in der JSON-Datei anpassen

Die Abhängigkeiten des Callisto Light Designs sind in einer JSON-Datei hinterlegt, die sich im selben Ordner wie die Datei plentymarketsCMStools-x.x.x.js befindet. Um die neueste Version der plentymarkets CMS library nutzen zu können, müssen Sie die in dieser Datei gespeicherte Versionnummer aktualisieren. Der Name dieser JSON-Datei lautet aktuell *scripts-3.5.json*, bei älteren plentymarkets Designs jedoch *scripts.json* oder *dependencies.json*. Der Inhalt der Dateien ist identisch. Gehen Sie wie unten beschrieben vor, um die Versionsnummer zu aktualisieren.

Nach diesem Schritt ist es nicht mehr notwendig die Skripte, die in der *scripts-3.5.json* vorkommen, durch ein script-Tag separat einzubinden. Das Skript *ScriptLoader.js* erzeugt die notwendigen script-Tags automatisch.

[.instruction]
Versionsnummer in der JSON-Datei anpassen:

. Öffnen Sie das Menü *CMS » Webspace*.
. Öffnen Sie den Ordner *layout » Ihr Design » js » plenty*. +
→ Ordner klappen Sie auf, indem Sie links in der Übersicht auf das kleine Plus klicken.
. Laden Sie die Datei *scripts-3.5.json* herunter.
. Öffnen Sie die Datei in einem Texteditor.
. Ändern Sie die Versionsnummer von plentymarketsCMStools-x.x.x.js auf die Version der Datei, die Sie in den Webspace hochgeladen haben.
. Speichern Sie die geänderte Datei.
. Laden Sie die aktualisierte Datei an derselben Stelle in Ihrem plentymarkets System wieder hoch. +
→ Aufgrund des Cachings dauert es bis zu eine Stunde, bis die neue Dateiversion im Webspace angezeigt wird.
