If you selected the options *Create sales price*, *Create barcode* and/or *Create property* in the assistant, these prices, barcodes and/or properties are created automatically. You need to link these newly created sources with the variations that you want to export to the market. This is described on the *Item* pages of the manual:

* Learn how to link sales prices to variations in the <<item/managing-items#240, Linking sales prices>> chapter.
* Learn how to link barcodes to variations in the <<item/managing-items#250, Linking barcodes>> chapter.
* Learn how to link properties to variations in the <<item/managing-items#4900, Linking properties and saving a value>> chapter. +
*_Tip:_* Properties created in the assistant are automatically added to the property group *{property-group}* of the *Setup » Settings » Properties » Groups* menu. Open this group to see what new properties need to be mapped.

////
[#link-sources]
== Linking sources created in the assistant with variations

:property-group:

include::../../_textblocks/instructions/assistant-link-sources.adoc[]
////
