ifdef::do-not-map-fields[]
[IMPORTANT]
====
Do not map plentymarkets data fields to the following marketplace data fields for the market {marketplace}:

*{do-not-map-fields}*
====
endif::[]

////
If more than one data field:

:do-not-map-fields: Field 1 + \
Field 2 + \
Field 3
////

[.instruction]
Creating a catalogue in the assistant:

. Open the menu {catalogue-path}.
. Click on the assistant *{catalogue-assistant-name}*.
. Follow the instructions on the screen. If you need additional information about one of the options, expand the {number-of-boxes} below (icon:chevron-down[role="darkGrey"]).
. In the step *Summary*, check your settings to makes sure they are correct. +
*_Tip:_* Click on the arrow (icon:chevron-down[role="darkGrey"]) to show the settings.
. If everything is as it should be, click on icon:check[role="green"] *Finalise*. +
→ The catalogue is created.
. Map <<{anchor-additional-fields}, the fields>> in the *Data » Catalogues* menu. +
*_Note:_* {catalogue-note}

////
:catalogue-assistant-name:
:number-of-boxes: info box(es)
:anchor-additional-fields: #600
:catalogue-path:
:catalogue-note: You need a separate catalogue for each OTTO category group.
:do-not-map-this-field:

include::../../_textblocks/instructions/catalogue-assistant-config.adoc[]
////
