After you have created a catalogue, map the market's data fields to item data saved in plentymarkets. Check the documentation of the sales channel to find out what data the market expects for the individual data fields.

[TIP]
.Using properties
====
Use <<item/managing-items#4800, properties>> to export values for marketplace data fields that have no corresponding field in plentymarkets.
====

[.instruction]
Mapping data fields in the catalogue:

. Go to *Data » Catalogues*.
. Click on the catalogue. +
→ The *Mapping* tab with the market data fields opens. +
→ In the left-hand column, the market's data fields are listed. +
*_Tip:_* Mandatory fields are flagged with an asterisk (*).
. To the right of the first marketplace data field, click on *Add data field*. +
→ To the left, the plentymarkets data fields are listed in groups.
. Click on a group to expand the associated data fields. +
→ The data fields are shown.
. Next to the data field you want to select, click on the plus. +
→ The data field is added to the view. +
*_Optional:_* Do you want to export a fixed value for every variation for one of the market data fields?
    .. Click on the plus next to *Own value*. +
    → The field for the own value is added to the view.
    .. Enter a value into the input field.
. Click on the X to close the editing mode. +
→ The data field is mapped.
. *_Optional:_* Do you want to export two or more plentymarkets fields for a single marketplace data field?
    .. To the right of the data field you just mapped, click on *Add data field* (icon:link[rotate=90]).
    .. Map an additional plentymarkets data field to the marketplace data field as described above.
    .. To the right of the column, click on *Settings* (icon:cog[]).
    .. Select a separator from the drop-down list *Separator* or add a custom separator.
    .. *Save* the settings. +
    → The additional data field is mapped. During the export, the content of the two plentymarkets data fields is combined and exported as one field.
. *_Optional:_* Click on *Add fallback data field* to select a data field that is exported in case another one is not available or empty. You can also add more than one fallback data field. +
*_Note:_* Even if you assign a fallback data field to a market data field, only one value is exported. The fields are checked in the order in which you mapped them. This means that if the first data field does not provide a value, the first fallback data field is exported etc.
. Repeat this mapping for all data fields of the market that you want to export. +
*_Note:_* All fields flagged with asterisks (*) are mandatory and must be mapped to a plentymarkets data field.
. *Save* (icon:save[role="green"]) the settings. +
→ The mappings are saved.

ifdef::do-not-map-fields[]
[IMPORTANT]
====
Do not map plentymarkets data fields to the following marketplace data fields for the market {marketplace}:

*{do-not-map-fields}*

You can ignore the warning shown when you save the mapping.
====
endif::[]

////
If more than one data field:

:do-not-map-fields: Field 1 + \
Field 2 + \
Field 3
////

////
[#map-data-fields]
=== Mapping data fields in the catalogue

include::../../_textblocks/instructions/catalogue-map-data-fields.adoc[]
////
