After you have created a catalogue, map the market's data fields to item data saved in plentymarkets. Check the documentation of the sales channel to find out what data the market expects for the individual data fields.

[TIP]
.Using properties
====
Use <<item/managing-items#3000, properties>> to export values for data fields that have no corresponding item data saved in plentymarkets.
====

[.instruction]
Mapping data fields in the catalogue:

. Go to *Data » Catalogues*.
. Click on the catalogue. +
→ The *Mapping* tab with the market data fields opens. +
→ In the left-hand column, the market's data fields are listed. +
*_Tip:_* Mandatory fields are flagged with an asterisk (*).
. To the right of the first market data field, klick on *Add data field*. +
→ To the left, the plentymarkets data fields are listed in groups.
. Click on a group to expand the associated data fields. +
→ The data fields are shown.
. Next to the data field you want to select, klick on the Plus. +
→ The data field is added to the view. +
*_Tip:_* Do you want to export a fixed value for every variation for one of the market data fields? Click on the plus next to *Own value*. +
→ The field for the own value is added to the view.
. Enter a value into the input field.
. Click on the X to close the editing mode.
. *_Optional:_* Click on *Add fallback data field* to select a data field that is exported in case another one is not available or empty. You can also add more than one fallback data field. +
*_Note:_* Even if you assign more than one plentymarkets data field to a market data field, only one value is exported. The fields are checked in the order in which you mapped them. This means that if the first data field does not provide a value, the second data field is exported etc.
. Repeat this mapping for all data fields of the market that you want to export.
*_Note:_* All fields flagged with asterisks (*) are mandatory and must be mapped to a plentymarkets data field.
. *Save* (icon:save[role="green"]) the settings. +
→ The mappings are saved.

////
[#map-data-fields]
=== Mapping data fields in the catalogue

include::../../_textblocks/instructions/catalogue-map-data-fields.adoc[]
////
