[.instruction]
Creating a catalogue:

. Go to *Data » Catalogues*.
. Click on *Create catalogue*.
. Enter a name for the catalogue.
. In the drop-down list *Export type*, select the option *{catalogue-template-name}*. +
ifdef::catalogue-plugin[]
*_Note:_* The export type *{catalogue-template-name}* is only shown when the plugin {plugin} is installed.
endif::[]
. In the drop-down list *Format type*, select the option *Item*.
ifdef::one-per-category[]
. In the drop-down list *Format*, select a category of the marketplace.
endif::[]
ifndef::one-per-category[]
. In the drop-down list *Format*, select the option *{catalogue-template-name}*. +
*_Tip:_* You can only create one catalogue for this market. Thus, the only format you can select is the name of the market.
endif::[]
. *Save* (icon:save[role="green"]) the settings. +
→ The catalogue is created. +
→ The catalogue is opened for editing.

[TIP]
.Other catalogue settings are optional
====
In addition to the basic settings, the catalogue settings also contain options for *Format settings*, *Export settings* and *Download settings*. These optional settings allow you to create a file with the item data that is exported to the market at regular intervals. If you do not want to create such a file, you can ignore the settings. These settings do not impact the export to the market.
====

////
:catalogue-template-name: xxxx

include::_textblocks/instructions/creating-catalogues.adoc[]
////
