Item data is exported to OTTO Market via catalogue templates. Use the assistant *Create catalogues - OTTO Market* to create one catalogue for every OTTO category group. Is this your first time working with catalogues? Then read up on the basic principle of <<en/data/exporting-data/managing-catalogues, catalogues first>>.
For further information about the plentymarkets data sources that can be linked, refer to the <<data/exporting-data/managing-catalogues#_mapping_data_sources, Mapping data sources>> chapter.

[TIP]
.Items cannot be deleted at OTTO Market
====
An item cannot be deleted at OTTO Market, neither by plentymarkets nor by OTTO. It is only possible to mark the item as *not available* at OTTO Market. Therefore, make extra sure that the correct sources are mapped in the catalogue prior to transferring your items.
====

=== Creating a catalogue in the assistant

[.instruction]
Creating a catalogue in the assistant:

. Go to *Setup » Assistants » Omni-Channel*.
. Click on the assistant *Create catalogues - OTTO Market*.
. Follow the instructions on the screen. +
*_Tip:_* If you need additional information about one of the options, expand the info box below (icon:chevron-down[role="darkGrey"]).
. Check the summary for any errors.
. If everything is as it should be, click on icon:check[role="green"] *Finalise*. +
→ The catalogue is created.
. Open the catalogue in the *Data » Catalogues* menu to map <<#600, additional data fields>>. +
*_Note:_* You need a separate catalogue for each OTTO category group.

[.collapseBox]
.Step: *Name and category group*
--
[[table-otto-market-catalogue-assistant]]
[width="100%"]
[cols="1,2"]
|====
| Setting | Explanation

| *Enter a name for the catalogue.*
a| Enter a name for the catalogue.

| *Select the OTTO category group that should be added to the catalogue.*
| Select an OTTO category group from the drop-down list. +
*_Note:_* You need a separate catalogue for each OTTO category group.
|====
--

[.collapseBox]
.Step: *Required fields*
--
In this step of the assistant, you decide which variation data saved in plentymarkets you want to send to the market. To do so, you are going to map each mandatory field of the market with the source in plentymarkets that contains the data that you want to export to the market. Each market specifies their own mandatory fields. Instead of mapping an existing data source, you can also create a new data source for some fields.

'''
*Parent SKU* = From the drop-down list, select the data field in plentymarkets that contains the parent SKU.

'''
*SKU* = From the drop-down list, select the data field in plentymarkets that contains the SKU.

'''
*Select data source* = A data source that already exists in plentymarkets will be exported to OTTO Market. Select the data source from the drop-down list *Data source*. +
*_Note:_* The mappings you create will not be checked in terms of logic. As such, check your mappings carefully before starting the export.

'''
*Create property* = Creates a property and maps this property to the data field. This automatically created property will be saved in the <<welcome/general-functions/properties#table-create-property, Setup » Settings » Properties » Configuration>> menu.

The property is created with the following settings:

* Area = Item
* Property type = _depending on the market’s requirements_
* Language = German
* Name = Field of the OTTO category group
* Group = OTTO Market

'''
*Creating a sales price* = Creates a sales price and maps this sales price to the data field. You can check and edit this sales price in the <<en/item/settings/prices#400, Setup » Item » Sales prices>> menu.

The sales price is created with the following settings:

* Subscription interval = None
* Internal name = OTTO Market
* External name = OTTO Market
* Minimum quantity = 1
* Live conversion = No
* Currency = Euro
* Display = Always display for new items
* Client = ALL
* Class = ALL
* Country = Germany

'''
*Create barcode* = Creates the barcode *OTTO Market* and maps this barcode with the data field. If a barcode with the name *OTTO Market* already exists in the system, that barcode is mapped instead. You can check and edit this barcode in the <<en/item/settings/barcodes#100, Setup » Item » Barcodes>> menu.
--

[.collapseBox]
.Step: *Summary*
--
[[table-otto-market-catalogue-assistant]]
[width="100%"]
[cols="1,2"]
|====
| Setting | Explanation

| Summary
| Shows a summary of the catalogue settings. Expand (icon:chevron-down[role="darkGrey"]) and check your settings.

|====
--

[#600]
=== Mapping additional data fields in the catalogue (not in assistant)

You have already mapped important mandatory fields for the OTTO category group in the assistant. However, after you have completed the assistant, you need to map additional data fields to send more information regarding your products to OTTO Market.

TIP: Link at least the data fields *Brand*, *Delivery type* and *Category* with a plentymarkets data source.

[.instruction]
Mapping additional data fields:

. Go to *Data » Catalogues*. +
→ The catalogues are listed.
. Click on the OTTO Market catalogue. +
→ The catalogue opens. +
→ The market's data fields are displayed on the left-hand side. +
*_Tip:_* Mandatory fields are marked with an asterisk. +
→ On the right are the fields in plentymarkets that you can select as a data source. +
. Select a plentymarkets data source for the desired market's data fields from the drop-down list.
. *_Optional:_* Click on *Add source* to assign another plentymarkets data source to a data field. +
→ A new line is displayed. +
*_Note:_* Only one value is exported even if you assign more than one data source to a data field. The data is checked in the order in which you assigned it. This means that if the first data field does not provide a value, the second data field is exported etc.
. Map the desired data fields.
. *Save* (icon:save[role="green"]) the settings.

[#602]
==== _Example:_ Mapping the data field "Stock"

An example of how to map the data field *Stock* to item data saved in plentymarkets is provided below. Use the data field *Stock* to select from which warehouse stock is to be exported to OTTO Market.

[.instruction]
Mapping the data field "Stock":

. Go to *Data » Catalogues*.
. Click on the catalogue. +
→ The catalogue opens.
. Select a plentymarkets data source for the OTTO Market data field from the *Source* drop-down list. To do so, expand the plentymarkets data source *Stock*. +
→ All warehouses saved in plentymarkets are displayed in the drop-down list.
. Select the warehouse from which you want to export the stock to OTTO Market.
. Click on *Select* (icon:check-square[role="green"]). +
*_Optional:_* To transfer stock from multiple warehouses to OTTO Market, click on *Add source* (icon:link[role="yellow"]) and add more warehouses.
*_Note:_* If you do not map the data field *Stock* to a warehouse, then the sum of the net stock of all distribution warehouses (data source *Virtual warehouse*) will be exported to OTTO Market.
. *Save* (icon:save[role="green"]) the settings. +
