Item data is exported to REWE via marketplace catalogues. The assistant *Creating REWE catalogues* helps you to create a catalogue for a specific product category. Is this your first time working with catalogues? Then read up on the basic principle of <<en/data/exporting-data/managing-catalogues, catalogues first>>. For further information about the plentymarkets data sources that can be linked, refer to the <<data/exporting-data/managing-catalogues#_mapping_data_sources, Mapping data sources>> chapter.

At present, the REWE plugin allows you to create catalogues for the following REWE product categories:

* *Household*
* *Multimedia*
* *Drugstore*
* *Fashion*
* *Leisure/sports*
* *Stationary*
* *Toys*
* *Garden*
* *Food*

*_Information for the food product category:_*

* Food specifications must always be made for 100g.
* Energy information must be provided in kcal.
* If the *Nutrition information for prepared and non-prepared foods* field is not linked, the value *non-prepared* is transferred to REWE by default.

=== Creating a catalogue in the assistant

[.instruction]
Creating a catalogue in the assistant:

. Go to *Setup » Assistants » Plugins »*_Open client_.
. Click on the assistant *Create REWE catalogue*.
. Follow the instructions on the screen. +
*_Tip:_* If you need additional information about one of the options, expand the info box below (icon:chevron-down[role="darkGrey"]).
. In the step *Summary*, check your settings to makes sure they are correct. +
*_Tip:_* Click on the arrow (icon:chevron-down[role="darkGrey"]) to show the settings.
. If everything is as it should be, click on icon:check[role="green"] *Finalise*. +
→ The catalogue is created.
. Open the catalogue in the *Data » Catalogues* menu to map <<#600, additional data fields>>. +
*_Note:_* You need a separate catalogue for each Product category.

[.collapseBox]
.Step *Settings*
--
[[table-rewe-catalogue-assistant]]
[width="100%"]
[cols="1,2"]
|====
| Setting | Explanation

| *Select the REWE product category that should be added to the catalogue.*
| Select a product category from the drop-down list. +
*_Note:_* You need a separate catalogue for each Product category.

| *Enter a name for the REWE catalogue.*
a| Enter a name for the catalogue. The catalogue will be listed under this name in the *Data » Catalogues* menu.
|====
--

[.collapseBox]
.Step *Mapping basic data fields*
--
In this step of the assistant, you decide which variation data saved in plentymarkets you want to send to the market. To do so, you are going to map each field of the market with the source in plentymarkets that contains the data that you want to export to the market. Instead of mapping an existing data source, you can also create a new data source for some fields.
'''
*SKU* = From the drop-down list, select the data field in plentymarkets that contains the SKU. +
*_Tip:_* We recommend to link the data field *SKU* with the plentymarkets data source *Variation ID* because the variation ID is clearly assigned to the variation.

'''
*Select data source* = A data source that already exists in plentymarkets will be exported to REWE. Select the data source from the drop-down list *Data source*. +
*_Note:_* The mappings you create will not be checked in terms of logic. As such, check your mappings carefully before starting the export.

'''
*Create property* = Creates a <<item/settings/properties#500, property>> and maps this property to the data field. <<item/settings/properties#500, Properties>> make it possible to export values for data fields that have no corresponding item data saved in plentymarkets, such as *Durchmesser* (diameter).

The automatically created property will be saved in the <<welcome/general-functions/properties#table-create-property, Setup » Settings » Properties » Configuration>> menu.

The property is created with the following settings:

* Availability = Item
* Property type = _depending on the market’s requirements_
* Language = German
* Name = Name of the product category
* Group = REWE

'''
*Creating a sales price* = Creates a sales price and maps this sales price to the data field. You can check and edit this sales price in the <<en/item/settings/prices#400, Setup » Item » Sales prices>> menu.

The sales price is created with the following settings:

* Subscription interval = None
* Internal name = REWE
* External name = REWE
* Minimum quantity = 1
* Live conversion = No
* Currency = Euro
* Display = Always display for new items
* Client = ALL
* Class = ALL
* Country = Germany

'''
*Create barcode* = Creates a barcode *REWE* and maps this barcode to the data field. If a barcode with the name *REWE* already exists in the system, that barcode is mapped instead. You can check and edit this barcode in the <<en/item/settings/barcodes#100, Setup » Item » Barcodes>> menu.
--

[#600]
=== Mapping additional data fields in the catalogue (not in assistant)

You have already mapped important mandatory fields for the REWE product category in the assistant. However, after you have completed the assistant, you need to map additional data fields to send more information regarding your products to REWE.

[.instruction]
Mapping additional data fields:

. Go to *Data » Catalogues*. +
→ The catalogues are listed.
. Click on the REWE catalogue. +
→ The catalogue opens. +
→ The market's data fields are displayed on the left-hand side. +
*_Tip:_* Mandatory fields are marked with an asterisk. +
→ On the right are the fields in plentymarkets that you can select as a data source. +
. Select a plentymarkets data source for the desired market's data fields from the drop-down list.
. *_Optional:_* Click on *Add source* to assign another plentymarkets data source to a data field. +
→ A new line is displayed. +
*_Note:_* Only one value is exported even if you assign more than one data source to a data field. The data is checked in the order in which you assigned it. This means that if the first data field does not provide a value, the second data field is exported etc.
. Map the desired data fields.
. *Save* (icon:save[role="green"]) the settings.

[#602]
=== _Example:_ Mapping the data field "Product description"

An example of how you can link the mandatory field *Produktbeschreibung* (product description) to data saved in plentymarkets is described below.

. Go to *Data » Catalogues*.
. Click on the catalogue. +
→ The catalogue opens.
. Select a plentymarkets data source for the REWE catalogue field *Produktbeschreibung* (product description) from the drop-down list, e.g. *Item text > Name 1, Name 2, Name 3* that should be displayed on REWE as the product description.
. Link the other data fields in the same way. Link at least all mandatory fields.
. *Save* (icon:save[role="green"]) the settings.

[#701]
== Linking sources created in the assistant with variations

If you selected the options *Create sales price*, *Create barcode* and/or *Create property* in the assistant, these prices, barcodes and/or properties are created automatically. You need to link these newly created sources with the variations that you want to export to REWE. This is described on the *Item* pages of the manual:

* Learn how to link sales prices to variations in the <<item/managing-items#240, Linking sales prices>> chapter.
* Learn how to link barcodes to variations in the <<item/managing-items#250, Linking barcodes>> chapter.
* Learn how to link properties to variations in the <<item/managing-items#4900, Linking properties and saving a value>> chapter. +
*_Tip:_* Properties created in the assistant are automatically added to the property group *REWE* of the *Setup » Settings » Properties » Groups* menu. Open this group to see what new properties need to be mapped.
