Add SKUs manually for specific referrers in the *Item » Edit item » [Open item] » Tab: Variation ID » Tab: Availability* menu if needed.

ifdef::sku-cdiscount[]
[IMPORTANT]
.Automatic SKU generation
====
If the *Request product creation* setting is activated in the *Setup » Markets » Cdiscount.com » Tab: Settings* menu, an SKU is generated which matches the variation ID for each variation during the export that takes place at night.
====

[IMPORTANT]
.SKUs of already existing items
====
Items with variations in plentymarkets can be linked to already existing items on Cdiscount. The SKU serves as the identification in plentymarkets. The SKU can be found as *Your reference* in the Cdiscount seller back end.
====
endif::sku-cdiscount[]

ifdef::sku-netto[]
The referrer *Plus.de* also covers the market Netto Marken-Discount if you add SKUs.
endif::sku-netto[]

[.instruction]
Adding SKU:

. Go to *Item » Edit item » [Open item] » Tab: Variation ID » Tab: Settings*.
. Click on the *Availability* tab.
. In the *SKU* area, click on *Add* (icon:plus-square[role="green"]). +
→ The *New SKU* window opens.
. Select the referrer *{referrer-sku}*.
ifdef::sku-account[]
. Select the corresponding marketplace account.
endif::[]
. Enter the SKU.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The SKU is saved and displayed.

////
:referrer-sku: xxxx
////
