= Online store
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Store settings
:position: 20

**plentymarkets » Settings » Client (store) » Standard » Online store**

== Content of this chapter

This chapter gives important information about the various menus of your online store. Along with the **<<omni-channel/online-store/standard/online-store/basic-settings#, basic settings  >>** of your online store, you learn how to carry out settings in the **<<omni-channel/online-store/standard/online-store/multilingualism#, Multilingualism  >>** menu in order to set up a multilingual online store and how to manage currencies in the **<<order-processing/payment/currencies#, Currency  >>** menu. Furthermore, this chapter teaches you how to **<<omni-channel/online-store/standard/online-store/lock-store#, lock your online store  >>** and how to set up mobile **<<omni-channel/online-store/standard/online-store/forwarding#, forwarding  >>**. You will also learn how to save **<<omni-channel/online-store/standard/online-store/legal-information#, legal information  >>**, e.g. terms and conditions or cancellation rights.

== Links to other menus

The settings that are saved in the **Currency** menu directly relate to the **<<order-processing/payment/managing-payments#10, incoming payments >>** within your **<<order-processing/orders#, orders  >>**. You can also assign a **<<order-processing/payment/managing-payments#, payment  >>** currency to a language in order to get the most out of working with a **<<omni-channel/online-store/best-practice/multilingual-online-store#, multilingual online store  >>**.

== Direct access to important pages of the manual

* <<omni-channel/online-store/standard/online-store/basic-settings#, **Basic settings**  >>
* <<omni-channel/online-store/standard/online-store/multilingualism#, **Multilingualism**  >>
* <<order-processing/payment/currencies#, **Currency**  >>
* **<<omni-channel/online-store/standard/online-store/lock-store#, Lock store  >>**
* <<omni-channel/online-store/standard/online-store/forwarding#, **Forwarding**  >>
* <<omni-channel/online-store/standard/online-store/legal-information#, **Legal information**  >>
* <<omni-channel/online-store/standard/online-store/content-pages#, **Content pages**  >>

