= ItemParcelServicePreset
:lang: de
include::{includedir}/_header.adoc[]
:description: Spezialformat ItemParcelServicePreset
:position: 165

Mit dem Spezialformat **ItemParcelServicePreset** importieren Sie Versandprofile, die beim Artikel im Tab **Global** aktiviert sind. Dieses Datenformat steht Ihnen im Menü **Datenaustausch » Import » Dynamischer Import** ausschließlich zum Import zur Verfügung. Wie Sie das Datenformat importieren, ist auf der Handbuchseite <<basics/datenaustausch/daten-importieren#, Daten importieren>> beschrieben. Ein Exportformat erstellen Sie im Menü <<basics/datenaustausch/daten-exportieren#30, Datenaustausch » Export » Elastischer Export>>.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **ItemParcelServicePreset** in alphabetischer Reihenfolge.

[cols="a,a"]
|====
|Feldname |Erläuterung

|**item_id**
|Artikel-ID

|**parcel_service_preset_id - parcel_service_preset_id5**
|IDs der Versandprofile, die in den Artikeleinstellungen aktiviert sind
|====

__Tab. 1: Datenfelder des Datenformats **ItemParcelServiceSet**__
