= ItemImageName
:lang: de
include::{includedir}/_header.adoc[]
:position: 152

Mit dem Datenformat **ItemImageName** bearbeiten oder löschen Sie Artikelbildnamen und Alternativnamen von im Tab **Bilder** eines Artikels verknüpften Artikelbildern. Mit wenig Aufwand passen Sie so große Mengen an verknüpften Bildern bzw. deren Parameter an. Sie erstellen und exportieren das Datenformat im Menü **Datenaustausch » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Datenaustausch » Datenimport » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten **<<basics/datenaustausch/daten-exportieren#, Daten exportieren  >>** und **<<basics/datenaustausch/daten-importieren#, Daten importieren  >>** beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **ItemImageName** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

[cols="a,a,a"]
|====
|Feldname |Erläuterung |Filter

|**ItemImageID**
|Artikelbild-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**ItemImageItemID**
|Artikel-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**ItemImageLanguage**
|Sprache des Artikelbildnamens
|Filter aktivieren und Sprache wählen.

|**ItemImageName**
|Name des Artikelbildes
|

|**ItemImageNameAlternate**
|Alternativname; verbessert die Indizierung durch Suchmaschinen für die Artikel.
|

|**ItemImageNameDelete**
|**1** = Bildnamen löschen +
Löscht Artikelbildnamen unwiederbringlich, wenn der Wert 1 eingegeben wird. Weitere Informationen zu Filtern, siehe Handbuchseite **<<basics/datenaustausch/daten-exportieren#20, Daten exportieren >>**.
|

|**ItemImageURL**
|Artikelbild-URL
|
|====

__Tab. 1: Datenfelder des Datenformats **ItemImageName**__

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<basics/datenaustausch/daten-importieren#25, **Datenabgleich** >> zur Verfügung. Bei Pflichtabgleichfeldern (P) muss für die **Importaktion** die Option **Abgleich** gewählt werden.

[cols="a,a,a"]
|====
|Feldname |Erläuterung |Abgleich

|**ItemImageID**
|Artikelbild-ID
|P

|**ItemImageLanguage**
|Sprache des Artikelbildnamens
|P
|====

__Tab. 2: Datenfelder mit Einstellung auf die Option **Abgleich**__

