= SerialKeys
:lang: de
include::{includedir}/_header.adoc[]
:description: Datenformat
:position: 215

Das Datenformat **SerialKeys** wird verwendet, um Seriennummern zu exportieren, zu bearbeiten und zu importieren. Nutzen Sie dieses Datenformat, um mit geringem Aufwand eine Vielzahl an Seriennummern für einen Artikel in plentymarkets zu importieren. Sie können die Seriennummern Ihrer Artikel auch exportieren, diese in der Datei bearbeiten und wieder importieren. Sie erstellen und exportieren das Datenformat im Menü **Daten » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<basics/datenaustausch/daten-exportieren#, Daten exportieren>> und <<basics/datenaustausch/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **SerialKeys** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

.Datenfelder des Datenformats **SerialKeys**
[cols="a,a,a"]
|====
|Feldname |Erläuterung |Filter

|**ItemID**
|Artikel-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**OrderID**
|Auftrags-ID
|

|**OrderRowID**
|Auftrags-ID der Artikelposition
|

|**SerialKey**
|Seriennummer
|

|**ID**
|ID der Seriennummer
|
|====

== Übersicht der Pflichtfelder

Das folgende Pflichtfeld muss für das Datenformat **SerialKeys** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* ItemID

== Übersicht der Abgleichfelder

Das in Tabelle 2 aufgelistete Datenfeld steht zum <<basics/datenaustausch/daten-importieren#25, Datenabgleich>> zur Verfügung. Bei diesem Pflichtabgleichfeld muss für die **Importaktion** die Option **Abgleich** gewählt werden.

.Datenfelder mit Einstellung auf die Option **Abgleich**
[cols="a,a"]
|====
|Feldname |Erläuterung

|**ID**
|ID der Seriennummer
|====
