= VariationBarcode
:lang: de
include::{includedir}/_header.adoc[]
:description: VariationBarcode
:position: 240

Das Datenformat **VariationBarcode** wird verwendet, um die im Menü **System » Artikel » Barcode** erstellten Barcodes zu exportieren, zu bearbeiten und zu importieren. Sie erstellen und exportieren das Datenformat im Menü **Datenaustausch » Export » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Datenaustausch » Import » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten **<<basics/datenaustausch/daten-exportieren#, Daten exportieren>>** und **<<basics/datenaustausch/daten-importieren#, Daten importieren>>** beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

Tabelle 1 erläutert die Datenfelder des Datenformats **VariationBarcode** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

[cols="a,a,a"]
|====
|Feldname |Erläuterung |Filter

|**BarcodeID**
|ID des Barcodes
|Filter aktivieren und Wert aus dem Dropdown-Menü wählen.

|**BarcodeName**
|Barcode-Name
|

|**BarcodeType**
|Barcode-Typ
|Filter aktivieren und Wert aus dem Dropdown-Menü wählen.

|**Code**
|Code
|

|**VariationNumber**
|(früher VariationCustomNumber) Variantennummer
|

|**VariationID**
|ID der Variante
|Filter aktivieren, Operator wählen und Wert eingeben.
|====

__Tab. 1: Datenfelder des Datenformats **VariationBarcode**__

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<basics/datenaustausch/daten-importieren#25, **Datenabgleich**>> zur Verfügung. Es handelt sich um Pflichtabgleichfelder. Bei Pflichtabgleichfeldern muss für die **Importaktion** die Option **Abgleich** gewählt werden. Wählen Sie mindestens eines der Datenfelder aus der Tabelle zum Abgleich.

[cols="a,a"]
|====
|Feldname |Erläuterung

|**VariationCustomNumber**
|Variantennummer
|====

__Tab. 2: Datenfelder mit Einstellung auf die Option **Abgleich**__

