= Kategorien
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Kategorien
:position: 80
:url: daten/daten-importieren/sync-typen/elasticSync-kategorien
:id: GV1MLXQ

Kategorien helfen dir Produkte übersichtlich zu gruppieren. Wie sollen deine Artikel im Webshop strukturiert werden? Welche Warengruppen passen zu deinem Produktkatalog?
Beantworte diese Fragen für dein eigenes Unternehmen und erstelle die notwendigen Kategorien.

##fix intro: you can use it to import lots of new categories at once or to update lots of category info at once##

Grundsätzlich gibt es zwei Möglichkeiten, Kategorien zu erstellen.
Wenn du _nur wenige Kategorien_ anlegen willst, empfiehlt sich die <<artikel/einstellungen/kategorien#200, manuelle Erstellung>>. Hast du aber dagegen _eine Vielzahl an Kategorien_, dann ist es wahrscheinlich schneller, deine Kategoriedaten zu importieren.
Darum geht es auf dieser Seite. Hier lernst du, Kategorieinformationen in plentymarkets zu importieren.

[TIP]
.Voraussetzungen
====
Diese Seite setzt voraus, dass du bereits eine <<artikel/einstellungen/kategorien#100, sinnvolle Kategoriestruktur>> überlegt hast und dass du Grundkenntnisse über das <<daten/daten-importieren/ElasticSync#, ElasticSync-Tool>> hast.
====

== Praxisbeispiel

Stell dir mal vor, du verkaufst Kleidung in deinem Webshop. Du bist ganz neu bei plentymarkets und möchtest alle deine Kategoriedaten auf einmal importieren. Du hast deine Kategorien wie folgt strukturiert:

[cols="3*^", grid=cols, frame=none, stripes=none]
|====

a|* Damen
** Accessoires
** Schuhe
** Bekleidung
*** Jeans
*** Tops
a|* Herren
** Accessoires
** Schuhe
** Bekleidung
*** Jeans
*** Tops
a|* Kinder
** Accessoires
** Schuhe
** Bekleidung
*** Jeans
*** Tops
|====

//Ausgangssituationen - welche Kategorien und welche Info hängt an die Kategorien

=== CSV-Datei einrichten

Übertrage zunächst diese Kategoriestruktur in eine CSV-Datei.
//Dies ist die Datei, die du in plentymarkets importieren wirst.
In unserem Beispiel würden die Kategorien in der CSV-Datei so aussehen:

##image##

//Deine Datei benötigt drei Spalten.
Die Namen der Spaltenüberschriften können frei gewählt werden.
In diesem Beispiel habe ich folgende Kategorieinformationen in die Spalten eingefügt:

* *Multiname* = Der vollständige Kategoriepfad. _Nutze Kommas_, um die einzelnen Kategorieebenen zu trennen.
* *Parentname* = Wenn dies eine Hauptkategorie ist, dann lass dieses Feld leer. Wenn dies eine Unterkategorie ist, dann gib den Pfad der direkt darüber liegenden Kategorie an. _Nutze Semikolons_, um die einzelnen Kategorieebenen zu trennen.
* *Name* = Der Name der Kategorie.

//Wie muss man die CSV Datei machen?

[discrete]
==== Zusätzliche Kategorie-Infos ergänzen

Wahrscheinlich willst du viel mehr als nur eine nackte Kategoriestruktur schaffen. Vielleicht willst du ja Beschreibungstexte oder SEO-relevante Metadaten ebenfalls ergänzen.
//Oder vielleicht willst du einige Kategorien nur für eingeloggte Benutzer zugänglich machen.

Füge ganz einfach weitere Spalten zu deiner CSV-Datei hinzu und verwende diese, um zusätzliche Kategorieinformationen anzugeben.
Zum Beispiel so:
//Füge deiner CSV-Datei ein paar zusätzliche Spalten hinzu und benutze sie, um deine Kategorien individuell anzupassen.

##image##

Die Namen der Spaltenüberschriften können frei gewählt werden.
Du kannst einige oder alle der in <<tabelle-Zuordnungsfelder-Kategorie>> aufgeführten Kategorieinformationen hinzufügen.
In diesem Beispiel habe ich mich entschieden, folgende Informationen zu ergänzen:

//* *Typ* = Kategorien können in plentymarkets auf verschiedene Weise verstanden werden. Ob jede Kategorie im Sinne einer Warengruppe oder im Sinne einer Content-Seite im Webshop verstanden werden soll. ##what happens if i leave this blank? Item is default?##
* *Beschreibung* = Eine Beschreibung jeder Kategorie.
* *Keywords* = SEO-relevante Keywords für jede Kategorie. ##_Nutze Kommas_##, um die einzelnen Keywords zu trennen.
* *Linkliste* = Ob die einzelnen Kategorien in der Navigation des Webshops angezeigt werden sollen. +
1 = ja
* *Right* = Ob die einzelnen Kategorien nur für eingeloggte Nutzer sichtbar sein sollen. +
customer = nur für eingeloggte Nutzer
* *Aktiv* = Ob die Kategorie bereits beim Import für den Webshop aktiviert sein soll. +
1 = ja

=== Sync-Einstellungen wählen

//Nachdem du alle deine Kategorieinformationen in einer CSV-Datei zusammengestellt hast, bist du bereit, <<daten/daten-importieren/ElasticSync#1210, ein neues Sync>> zu erstellen.
<<daten/daten-importieren/ElasticSync#1210, Erstelle ein neues Sync>>.
Die meisten Einstellungen können frei gewählt werden.
Da du jedoch Kategoriedaten importieren wirst, stelle sicher, dass du den *Typ* auf *Kategorien* gesetzt hast.

////
Da du jedoch Kategoriedaten importieren wirst, gibt es einige Einstellungen, die du wie folgt konfigurieren musst.

[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Typ*
|Wähle die Option *Kategorien*.

|separator?
|do all or only some work?

|anything else?
|?
|====
////

//Welche Sync-Einstellungen wählt man?

=== Abgleich-Einstellungen wählen

Während des Imports prüft plentymarkets, ob die Kategorie bereits existiert.
Dies geschieht mit Hilfe eines sogenannten Abgleichfeldes.

Da wir in diesem Beispiel _neue Kategorien_ importieren möchten, konfiguriere die Einstellungen wie folgt.

[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Kategoriename kombiniert*
|In welcher Spalte deiner CSV-Datei ist der vollständige Kategoriepfad aufgeführt? Wähle diese Spaltenüberschrift aus. In unserem Beispiel würde ich also die Spalte *Multiname* wählen.

|*Import Optionen*
|Da du neue Kategorien importieren wirst, wähle die Option *Nur neue Daten importieren* oder *Neue Daten importieren, vorhandene aktualisieren*.
|====

//Welche Abgleich Einstellungen wählt man?

=== Zuordnung-Einstellungen wählen

Deine CSV-Datei ist bereits mit einer Menge Kategorieinformationen gefüllt. Überlege als nächstes, wo jede dieser Informationen in plentymarkets erscheinen soll, nachdem die Datei importiert wurde.

Da wir in diesem Beispiel die Kategoriestruktur und einige Zusatzinformationen importieren möchten, konfiguriere die Einstellungen wie folgt.

##image##

//Würdest du also die <<Kategorie manuell in plentymarkets konfigurieren>>, welche Einstellungen würdest du wählen?

//Welche Zuordnung Einstellungen wählt man?

=== Hat es funktioniert?

Bereit, deine Kategorien zu importieren? Führe den Sync aus und kontrolliere, dass die Daten korrekt in plentymarkets importiert wurden.

[.instruction]
Sync ausführen und Ergebnis prüfen:

. Aktiviere die zu importierenden Zeilen (icon:toggle-on[role="green"]).
. Führe den Sync aus (icon:play-circle-o[role="darkGrey"]). +
*_Hinweis:_* Dies kann einige Minuten dauern.
. Öffne das Menü *Artikel » Kategorien*.
. Prüfe, ob deine Kategorien richtig strukturiert wurden. +
*_Hinweis:_* Klicke ganz links auf das Ordner-Symbol (icon:folder[role="darkGrey"]) einer Kategorie, um die darin enthaltenen Unterkategorien zu sehen.
. Öffne einige Kategorien und prüfe ihre Einstellungen.

//Sync ausführen und hinterher prüfen, ob alles geklappt hat

[#2110]
== Felder für den Kategorieabgleich

In <<tabelle-Abgleichfelder-Kategorie>> werden Felder erläutert, die für den Abgleich von Kategoriedaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Abgleichfelder-Kategorie]]
.Abgleichfelder für Kategorieimport
[cols="1,2"]
|====
|Einstellung |Erläuterung

|KategorieId
|ID der Kategorie

|Kategoriename Kombiniert
|Aus der zweiten Dropdown-Liste das Trennzeichen wählen.

|Kategoriename Ebene 1 - 6
|
|====

[#2120]
== Felder für die Kategoriezuordnung

In <<tabelle-Zuordnungsfelder-Kategorie>> werden Felder erläutert, die für die Zuordnung von Kategoriedaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Zuordnungsfelder-Kategorie]]
.Zuordnungsfelder für Kategorieimport
[cols="1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

3+|*Kategorie*

|*Elternkategorie ID*
|Nummerisch (interne ID)
|

|*Elternkategorie Name*
|Alphanummerisch
|

|*Typ*
|item +
container +
content +
blog
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, <<artikel/einstellungen/kategorien#700, welcher Kategorietyp>> beim Import vergeben wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Typ* gesetzt wurde.

* item = Artikel
* container = Container
* content = Content
* blog = Blog

|*In Linkliste anzeigen*
|0 +
1
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie in der Webshop-Navigation angezeigt>> wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *In Linkliste* gesetzt wurde.


* 0 = Nicht anzeigen
* 1 = Anzeigen

|*right*
|all +
customer
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie nur für eingeloggte Benutzer sichtbar>> sein wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Sichtbar* gesetzt wurde.

* all = Öffentlich
* customer = Nach Login

|*Sichtbar*
|0 +
1
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie in die Sitemap>> aufgenommen wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Sitemap* gesetzt wurde.

* 0 = Nicht anzeigen
* 1 = Anzeigen

|*Kategorie löschen*
|0 +
1
a|Möchtest du einige Kategorien löschen und andere aktualisieren? Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob die Kategorie gelöscht werden soll.

* 0 = Nein
* 1 = Ja

|*Elternkategorie anlegen wenn nicht vorhanden*
|
|

3+|*Details* (Zuordnung pro Kombination aus Sprache und Mandant (Shop))

|*Name* +
(Pflichtwert)
|Alphanummerisch
|Gib den <<artikel/einstellungen/kategorien#700, Namen der Kategorie>> in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass dieser Name in das Feld *Name* eingetragen wurde.

|*Beschreibung 1*
|Alphanummerisch
|Gib eine <<artikel/einstellungen/kategorien#800, Beschreibung der Kategorie>> in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest, siehst du, dass dieser Text im Tab *Beschreibung 1* eingetragen wurde.

|*Beschreibung 2*
|Alphanummerisch
|Gib eine <<artikel/einstellungen/kategorien#800, Beschreibung der Kategorie>> in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest, siehst du, dass dieser Text im Tab *Beschreibung 2* eingetragen wurde.

|*Kurzbeschreibung*
|Alphanummerisch
|

|*Meta-Keywords*
|Alphanummerisch
|

|*Meta-Beschreibung*
|Alphanummerisch
|

|*Meta-Titel*
|Alphanummerisch
|

|*URL-Name*
|Alphanummerisch
|

|*Position*
|Nummerisch
|

|*Template-Liste*
|Alphanummerisch
|

|*Template-Produkt*
|Alphanummerisch
|

|*Template-Seite*
|Alphanummerisch
|

|*Volltextsuche*
|0 = Nein +
1 = Ja
|

|*Robots*
|Alphanummerisch
|*all* = Webseite der Kategorie in Suchmaschinenindex aufnehmen und Links auf Seite folgen. +
*index* = In Suchmaschinenindex aufnehmen. +
*nofollow* = Links auf der Seite nicht folgen. +
*noindex* = Nicht in den Suchmaschinenindex aufnehmen. +
*nofollow_noindex* = Links nicht folgen und Webseite der Kategorie nicht in Suchmaschinenindex aufnehmen.

|*Platzhalter übersetzen*
|Alphanummerisch
|*Y* = Ja +
*N* = Nein +
*L* = Nur Link-Template-Variablen und -Funktionen werden übersetzt

|*Canonical*
|Alphanummerisch
|URL einer Kategorie mit dem gleichen Inhalt, max. 256 Zeichen

3+|*Elmar* (Zuordnung pro Mandant)

|*Elmar-Kategorie*
|
|

|*Verknüpfung löschen*
|
|

3+|*Mandant (Shop)* (Zuordnung pro Mandant)

|*Aktiv*
|0 = Nein +
1 = Ja
|
|====


////
[.subhead]
Beispiel 1: Preis- und Bestandsabgleich einer Variante

Mithilfe eines einfachen Syncs können Preise und Bestand einer Variante aktuell gehalten werden. Nachdem zunächst die Zuordnung im Sync vorgenommen wurde, muss ein Mapping erstellt werden. Dafür werden im Bereich Werte bestimmen des Mappings die plentymarkets Felder VariationSalesPrice und VariationStock gewählt. Nachdem die Werte bestimmt wurden, muss für VariationSalesPrice zunächst der zu aktualisierende Verkaufspreis (Preis, UVP) bestimmt werden. Es können auch mehrere Verkaufspreise mit nur einem Sync aktualisiert werden. Im nächsten Schritt wird die tatsächliche Verknüpfung mit einem Feld der Datenquelle vorgenommen. Beim Bestand kann neben dem Lager auch der Lagerort gewählt werden. Für VariationStock wird das Lager gewählt, für welches Bestand gebucht werden soll. Optional kann hier auch der Lagerort bestimmt werden. Um die Menge aus der Datenquelle zu übernehmen, muss noch das plentymarkets Feld quantity und das zugehörige Feld der Datenquelle verknüpft werden. Dabei wird immer eine Bestandskorrektur vorgenommen.

[.subhead]
Beispiel 2: Artikelbeschreibungen importieren

Für einen Artikel sollen Name, technische Daten und Meta-Keywords importiert werden. Dafür müssen zunächst diese plentymarkets Felder im Bereich Werte bestimmen des Mappings ausgewählt und übernommen werden. Für Artikelbeschreibungen wird im nächsten Schritt die Sprache gewählt. Eine Mehrfachauswahl ist möglich. Die Felder Name, Technische Daten und Meta-Keywords werden nun mit den gewünschten Feldern der Datenquelle verknüpft. Das heißt, dass die in den Datensätzen der Datenquelle vorhandenen Einträge für die zuvor gewählten plentymarkets Felder importiert werden. Zusätzlich kann der Import durch Filter weiter bestimmt oder eingegrenzt werden. So kann zum Beispiel eigestellt werden, dass die Artikelbeschreibungen nur importiert werden sollen, wenn der Artikel einer bestimmten Marke entspricht.
////
