= Gutschein-Codes
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Gutschein-Codes
:position: 68
:url: daten/daten-importieren/sync-typen/elasticSync-gutschein-codes

Mit einem Sync des Typs *Gutschein-Code* importieren Sie Daten zu Gutschein-Codes.

[#100]
== Felder für den Abgleich von Gutschein-Codes

Die folgenden Felder stehen für den Abgleich von Gutschein-Codes zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

* Kampagnen-ID

[#200]
== Felder für die Zuordnung von Gutschein-Codes

In <<tabelle-zuordnungsfelder-gutschein-codes>> werden Felder erläutert, die für den Datenabgleich von Gutschein-Codes zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-gutschein-codes]]
.Zuordnungsfelder für den Import von Gutschein-Codes
[cols="1,3"]
|====
|Zuordnungsfeld |Erläuterung

|Kampagnen-ID
|ID der Kampagne

|Gutschein-Code
|Gutschein-Code

|Rabattwert
|Rabattwert des Gutscheins

|====
