= Notizen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Notizen
:position: 90

Mit einem Sync des Typs *Notizen* importieren Sie Notizen. Je nach Abgleichfeld werden die Notizen am Kontakt, an der Variante, am Auftrag oder an der Kategorie gespeichert.

[#2110]
== Felder für den Abgleich

In <<tabelle-abgleichfelder-notizen>> werden Felder erläutert, die für den Abgleich von Notizen zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Das Abgleichfeld, das Sie angeben, entscheidet auch darüber, an welchem Datensatz die Notiz beim Import gespeichert wird. Pro Notiztyp muss also ein eigener Sync erstellt werden.

[[tabelle-abgleichfelder-notizen]]
.Abgleichfelder für Notizenimport
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Kontakt-ID
|Die Notizen des Syncs werden an dem Kontakt mit der im Abgleichfeld angegebenen ID gespeichert.

|Varianten-ID
|Die Notizen des Syncs werden an der Variante mit der im Abgleichfeld angegebenen ID gespeichert.

|Auftrags-ID
|Die Notizen des Syncs werden an dem Auftrag mit der im Abgleichfeld angegebenen ID gespeichert.

|Kategorie-ID
|Die Notizen des Syncs werden an der Kategorie mit der im Abgleichfeld angegebenen ID gespeichert.

|====

[#2120]
== Felder für die Notizzuordnung

In <<tabelle-zuordnungsfelder-notizen>> werden Felder erläutert, die für die Zuordnung von Notizen zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-notizen]]
.Zuordnungsfelder für Notizenimport
[cols="1,1,2"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Benutzer-ID +
(Pflichtfeld)
|Nummerisch (interne ID)
|Die ID der Person, die die Notiz anlegt.

|Text
|Alphanummerisch
|Der Notiztext

|Sichtbar für Kunden
|0 = Nein +
1 = Ja
|Gilt für Auftragsnotizen

|====
