= Zuordnung Zolltarifnummer
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Zuordnung Zolltarifnummer, Taric, Umsatzsteuer
:position: 160
:url: daten/daten-importieren/sync-typen/elasticSync-zuordnung-zolltarifnummer
:id: SOPEBTH
:author: team-order-payment

Mit einem Sync des Typs *Zuordnung Zolltarifnummer* importierst du Daten für die Zolltarifnummerntabelle im Menü *Einrichtung » Mandant » Global » Zolltarifnummern*. Um Zolltarifnummern an Varianten per Import zu hinterlegen, gehe zum <<daten/daten-importieren/sync-typen/elasticSync-artikel#2300, Sync-Typ Artikel>>.

[#10]
== Felder für den Abgleich

Die folgenden Felder stehen für den Abgleich der Zuordnung der Zolltarifnummern zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

* Zolltarifnummer
* Land

[#20]
== Felder für die Zuordnung

In <<tabelle-Zuordnungsfelder-Zuordnung-Zolltarifnummer>> werden Felder erläutert, die für die Zuordnung von Daten zur Zuordnung von Zolltarifnummern zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Zuordnungsfelder-Zuordnung-Zolltarifnummer]]
.Zuordnungsfelder für die Zuordnung Zolltarifnummer
[cols="1,1,2"]
|====
|Zuordnungsfeld |Zulässige Importwert |Erläuterung

| *Zuordnung / Umsatzsteuer*
|Numerisch
|Die Umsatzsteuersätze, die den Zolltarifnummern und Ländern zugeordnet wird.

| *Zuordnung / löschen*
|0 +
1
a|Der Umsatzsteuersatz für die hinterlegte Zolltarifnummer und das ausgewählte Land wird gelöscht. +

* 0 = Nein +
* 1 = Ja
|====
