= Attribute
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Attribute
:position: 20
:url: daten/daten-importieren/sync-typen/elasticSync-attribute

Mit einem Sync des Typs *Attribute* importierst du Attribute und Attributwerte. Die importieren Daten werden im Menü *System » Systemeinstellungen » Artikel » Attribute* gespeichert.

[#2490]
== Felder für den Attributabgleich

Die folgenden Felder stehen für den Abgleich von Attributen zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

* Attribut-ID
* ID des Attributwerts
* Attributname
* Name des Attributwertes

[#2500]
== Felder für die Attributzuordnung

In <<tabelle-Zuordnungsfelder-attribute>> werden Felder erläutert, die für die Zuordnung von Attributdaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Zuordnungsfelder-attribute]]
.Zuordnungsfelder für Attributimport
[cols="1,1,2"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

3+|*Attribut*

|Interner Name
|Alphanumerisch
a|include::../../../artikel/_textblocks/tabelle/interne-name.adoc[]

|Position
|Numerisch
a|include::workspace/manual-adoc/de/artikel/_textblocks/tabelle/position.adoc[]

|Bildverknüpfung möglich
|0 = Nein +
1 = Ja
a|include::../../../artikel/_textblocks/tabelle/bildverknuepfung.adoc[]

|Attributauswahl im Webshop
|dropdown +
image +
box
a|include::../../../artikel/_textblocks/tabelle/attribut-auswahl.adoc[]

|Gruppierbar in Artikellisten
|0 = Nein +
1 = Ja
a|include::../../../artikel/_textblocks/tabelle/gruppierbar.adoc[]

|Attribut löschen
|0 = Nein +
1 = Ja
|

3+|*Wert*

|Interner Name
|Alphanummerisch
|

|Position
|Nummerisch
|

|Bemerkung
|Alphanummerisch
|

|Prozentualer Anteil
|Nummerisch
|Prozentwerte für die automatische Mengenverteilung von Attributwerten

|Attributwert löschen
|0 = Nein +
1 = Ja
|

3+|*Attributname*

|Name
|Alphanummerisch
|Die Zuordnung erfolgt pro Sprache.

3+|*Attributwertname*

|Name
|Alphanummerisch
|Die Zuordnung erfolgt pro Sprache.
|====
