= Lager
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Lager, Lagerimport, Sync, Sync-Typ
:position: 100
:url: daten/daten-importieren/sync-typen/elasticSync-lager
:id: IS31LNZ
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Mit einem Sync des Typs *Lager* importierst du neue Lagerorte oder aktualisierst bestehende.

Um Lagerorte per ElasticSync zu erstellen oder zu aktualisieren, musst du ein Lager angelegt haben.

[#2231]
== Felder für den Lagerortabgleich

In <<tabelle-abgleichfelder-lagerorte>> werden Felder erläutert, die für den Abgleich von Lagerorten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

Weitere Informationen zu den Begrifflichkeiten Dimensionen, Ebenen und Lagerorte findest du auf der Handbuchseite link:https://knowledge.plentymarkets.com/warenwirtschaft/lager-einrichten[Lager einrichten^].

[[tabelle-abgleichfelder-lagerorte]]
.Abgleichfelder für Lagerortimport
[cols="2,2"]
|====
|Abgleichfeld |Erläuterung

|Level name
|Name der Ebene, z.B. R01

|Level ID
|ID der Ebene

|WarehouseLocationId
|ID des Lagerorts

|WarehouseLocationName
|Name des Lagerorts ohne Pfad
|====

[#2232]
== Felder für die Lagerortzuordnung

In <<tabelle-zuordnungsfelder-lagerorte>> werden Felder erläutert, die für die Zuordnung von Lagerortdaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

Weitere Informationen zu den Begrifflichkeiten Dimensionen, Ebenen und Lagerorte findest du auf der Handbuchseite link:https://knowledge.plentymarkets.com/warenwirtschaft/lager-einrichten[Lager einrichten^].


[[tabelle-zuordnungsfelder-lagerorte]]
.Zuordnungsfelder für Lagerortimport
[cols="2,2"]
|====
|Zuordnungsfeld |Erläuterung

2+^|*Lagerorte*

|Lagerort-ID +
(nur bei bestehenden Lagerorten)
|ID des Lagerorts

|Ebenen-ID
|ID der Ebene

|Lagerortname
|Name des Lagerorts ohne Pfad

|Verwendungszweck
|Verwedungszweck des Lagerorts, z.B. Entnahme

|Status
|Status des Lagerorts, z.B. aktiv, inaktiv

|Position
|Position des Lagerorts (Laufweg)

|Notizen
|Notizen zum Lagerort

|Lagerort löschen
|Löschfunktion für den Lagerort

2+^|*Ebenen der Lagerorte*

|ID der Elternebene
|ID der Elternebene

|Dimension ID
|ID der Dimension, z.B. Regal

|Position der Ebene
|Position der Ebene

|Name der Ebene
|Name der Ebene, z.B. R01, R02 usw.

|====

[IMPORTANT]
.Ebenen-ID der kleinsten Dimension verwenden
====
Beim Import von Lagerorten muss die Ebenen-ID die der kleinsten Dimension sein. In der folgenden Tabelle ist dies beispielsweise die Ebenen-ID 309. +
Wählt man hingegen die ID einer höheren Dimension, sind die Lagerorte nicht mehr sichtbar und die vorhandene Struktur geht verloren.
====

[[tabelle-ebenen-id]]
.Ebenen-IDs und Ebenen-Namen
[cols="2,2,2,2,2"]
|====
| |Ebene 1 |Ebene 2 |Ebene 3 |Lagerort

|*Name der Ebene*
|Regal 1
|Boden 5
|Fach 17
|102

|*Ebenen-ID*
|8
|22
|*309*
|
|====

[#2240]
== Lagerort anpassen

Du kannst mit ElasticSync Lagerorte anpassen und z.B. den Namen oder die Position des Lagerortes ändern.

[.instruction]
Lagerort anpassen:

. Öffne das Menü *Daten » ElasticSync*.
. Klicke in der Sync-Übersicht auf den Sync. +
→ Die Einstellungen werden geöffnet.
. Wechsele in das Tab *Abgleich*.
. Aktiviere das Feld *Warehouse Location ID*.
. Wähle bei den *Importoptionen* die gewünschte Option.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Klicke auf *Zuordnung*.
. Öffne die Zuordnung aus der Übersicht.
. Klappe auf der rechten Seite den Bereich *Lagerort* auf.
. Aktiviere die Felder *Lagerortname* und *Position*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#2250]
== Lagerort erstellen

Du kannst mit ElasticSync neue Lagerorte erstellen. Beachte, dass die Struktur des Lagers dafür im Vorhinein definiert und somit bereits mindestens ein Lagerort vorhanden sein muss.

[.instruction]
Lagerort erstellen:

. Öffne das Menü *Daten » ElasticSync*.
. Klicke in der Sync-Übersicht auf den Sync. +
→ Die Einstellungen werden geöffnet.
. Wechsele in das Tab *Abgleich*.
. Wähle das Feld *Level-ID*.
. Wähle bei den *Importoptionen* die gewünschte Option.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Klicke auf *Zuordnung*.
. Öffne die Zuordnung aus der Übersicht.
. Aktiviere die Zeilen, in denen die Werte *Lagerortname*, *Verwendungszweck*, *Position* und *Status* zu finden sind und wähle die entsprechende Quelle.
. Klappe auf der rechten Seite den Bereich *Lagerort* auf und weise die Felder *Lagerortname*, *Verwendungszweck*, *Position* und *Status* zu. Die *Lagerort-ID* ist optional - wenn sie nicht gewählt wird, wird automatisch die nächsthöhere ID vergeben.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#2250]
== Lagerort löschen

Du kannst mit ElasticSync Lagerorte löschen.

[.instruction]
Lagerort löschen:

. Öffne das Menü *Daten » ElasticSync*.
. Klicke in der Sync-Übersicht auf den Sync. +
→ Die Einstellungen werden geöffnet.
. Wechsele in das Tab *Abgleich*.
. Wähle das Feld *Warehouse Location ID*.
. Wähle bei den *Importoptionen* die gewünschte Option.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Klicke auf *Zuordnung*.
. Öffne die Zuordnung aus der Übersicht.
. Klappe auf der rechten Seite den Bereich *Lagerort* auf.
. Aktiviere das Feld *Lagerort löschen*.
. Es können alle oder nur bestimmte Lagerorte gelöscht werden. Nimm die entsprechenden Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-lagerorte-loeschen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-lagerorte-loeschen]]
.Alle oder nur bestimmte Lagerorte löschen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Alle Lagerorte löschen
|Alle Lagerort-IDs, die in der CSV-Datei vorhanden sind, werden gelöscht. +
 Hier wird als Wert für Lagerort löschen *Eigener Wert* ausgewählt. +
 Anschließend wählt man *Yes* oder *No*.

|Nur bestimmte Lagerorte löschen
|Hier gibt es 2 Werte in der CSV-Datei: einmal die Lagerort-IDs und einmal die Werte *Yes* und *No*, durch die bestimmt werden kann, ob der Wert gelöscht werden soll oder nicht.
|====
