= Kontakte, Firmen und Adressen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Kontakte, Firmen, Adressen
:position: 90
:url: daten/daten-importieren/sync-typen/elasticSync-kontakte-firmen-adressen
:id: SMSK85D
:author: team-crm

Diese Seite erläutert die Abgleich- und Zuordnungsfelder, die dir beim Importieren von Kontakten, Firmen und Adressen zur Verfügung stehen. Diese Seite dient lediglich als Referenz und setzt voraus, dass du bereits Grundkenntnisse über das <<daten/daten-importieren/ElasticSync#, Import-Tool>> hast.

[TIP]
.Praxisbeispiel: Kontaktdaten importieren
====
Stell dir mal vor, du bist ganz neu bei plentymarkets und möchtest alle deine Kontaktdaten auf einmal importieren. Wie geht so etwas? Wirf einen Blick auf <<daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-kontaktdaten#, dieses praktische Beispiel>>, welches dich Schritt für Schritt durch den Prozess führt.
====

[#abgleichfelder]
== Abgleichfelder

In <<#table-matching-fields-contacts-accounts-addresses>> werden Felder erläutert, die für den Abgleich von Kontakt-, Firmen- und Adressdaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-matching-fields-contacts-accounts-addresses]]
.Abgleichfelder für den Import von Kontakt-, Firmen- und Adressdaten
[cols="1,3"]
|===
|Einstellung |Erläuterung

|Kontakt-ID
|In welcher Spalte der CSV-Datei werden Kontakt-IDs aufgelistet? Wähle diese Spalte hier. Diese Option ist sinnvoll, wenn du die Kontaktoptionen _bestehender Kontakte aktualisieren_ möchtest. +
Wenn du neue Kontakte importieren möchtest, lasse dieses Feld leer. Beim Import werden die IDs für die Kontakte automatisch vergeben.

*_Hintergrund-Info:_* Jeder neu angelegte Kontakt erhält automatisch eine ID, die nicht geändert werden kann. Die ID dient zur eindeutigen Kennzeichnung des Kontakts. Da die ID eindeutig ist, lässt sich damit gut prüfen, ob der importierte Datensatz bereits in plentymarkets vorhanden ist.

|E-Mail
|In welcher Spalte der CSV-Datei werden die E-Mail-Adressen aufgeführt? Wähle diese Spalte hier. Diese Option ist sinnvoll, wenn du _bestehende Kontakte aktualisieren_ möchtest. +
// Empfohlenes Abgleichfeld.

|Rechnungsadress-ID
|In welcher Spalte der CSV-Datei werden die IDs der Rechnungsadresse aufgelistet? Wähle diese Spalte hier. Diese Option ist sinnvoll, wenn du bestehende Rechnungsadressen _bestehender Kontakte aktualisieren_ möchtest.


|Lieferadress-ID
|In welcher Spalte der CSV-Datei werden die IDs der Lieferadresse aufgelistet? Wähle diese Spalte hier. Diese Option ist sinnvoll, wenn du bestehende Lieferadressen _bestehender Kontakte aktualisieren_ möchtest.


|===

[#zuordnungsfelder]
== Zuordnungsfelder

In diesem Kapitel werden Felder erläutert, die für die Zuordnung von Kontakt-, Firmen- und Adressdaten zur Verfügung stehen. Mithilfe dieser Felder legst du fest, welche _Spalte deiner Datei_ welchem _Datenfeld in deinem System_ entspricht.

[.instruction]
Grundlegende Vorgehensweise:

. *_In deiner CSV-Datei_*: Gib einen zulässigen Importwert in eine Spalte ein.
. *_In plentymarkets_*: Ordne diese Spalte dem passenden Zuordnungsfeld zu.
. *_Nach dem Import_*: Prüfe das Ergebnis im Backend.

[TIP]
.Kein Zuordnungsfeld? Standardwert greift!
====
Wenn du eine bestimmte Information nicht in deine CSV-Datei aufnimmst, d.h. wenn du ein bestimmtes Zuordnungsfeld _nicht verwendest_, dann erhält dein Kontakt den Standardwert.
====

[#zuordnungsfeld-kontakt]
=== Kontakt

[#zuordnungsfeld-kontakt-externe-nummer]
==== Externe Nummer

Gib die externe Nummer in deine CSV-Datei ein. Dies kann z.B. die Kundennummer aus einem anderen System sein, um die Zuordnung nicht zu verlieren, wenn du deine Daten in plentymarkets importiert.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-nummer]
==== Nummer

Dies ist eine zusätzliche Nummer für den Kontakt, die du selbst vergeben kannst.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch, maximale Zeichenlänge: 128

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-typ]
==== Typ

icon:warning[role="red"] [red]#Pflichtwert#

Welchen Typen möchtest du dem Kontakt zuweisen? Typen dienen der Einordnung und Unterscheidung von Kontakten. Gib die ID des Typs in die CSV-Datei ein.

[TIP]
Die IDs 1 bis 6 sind fest vorgegeben und können nicht geändert werden. Du kannst weitere Typen im Menü *Einrichtung » CRM » Typen* erstellen und einen dieser Typen dem Kontakt beim Import zuweisen.

*_Standardwert:_* `1`

*_Mögliche Importwerte:_* Numerisch (interne ID)

[[table-mapping-fields-contact-type]]
[cols="1,1"]
|===

|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`1`
|Kunde

|`2`
|Interessent

|`3`
|Handelsvertreter

|`4`
|Lieferant

|`5`
|Hersteller

|`6`
|Partner

|`weitere IDs`
|Namen der Typen, die du selbst erstellt hast

|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Dropdown-Liste: Typ>>.

'''

[#zuordnungsfeld-kontakt-vorname]
==== Vorname

Wie lautet der Vorname des Kontakts? Gib den Vornamen in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Feld: Vorname>>.

'''

[#zuordnungsfeld-kontakt-nachname]
==== Nachname

Wie lautet der Nachname des Kontakts? Gib den Nachnamen in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Feld: Nachname>>.

'''

[#zuordnungsfeld-kontakt-geschlecht]
==== Geschlecht

Gib in der CSV-Datei die Anrede des Kontakts ein.

*_Standardwert:_* leere Option bzw. `0`

[[table-mapping-fields-contacts-form-of-address]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|Leere Option oder `0`
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz ist leer.

| `female` oder `1`
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz zeigt *Frau* an.

| `male` oder `2`
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz zeigt *Herr* an.

| `diverse` oder `2`
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz zeigt *Divers* an.

|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Dropdown-Liste: Anrede>>.

'''

[#zuordnungsfeld-kontakt-titel]
==== Titel

Hat der Kontakt einen Titel? Gib den Titel des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Feld: Titel>>.

'''

[#zuordnungsfeld-kontakt-newsletter]
==== Newsletter

Gib das Datum der Newsletter-Registrierung des Kontakts in deiner CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datum im Format tt.mm.jjjj

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Feld: Newsletter>>.

'''

[#zuordnungsfeld-kontakt-kundenklasse]
==== Kundenklasse

icon:warning[role="red"] [red]#Pflichtwert#, wenn du Kundenklassen in plentymarkets gespeichert hast.

Soll der Kontakt einer Kundenklasse zugeordnet werden?

[TIP]
Wenn Kundenklassen im System gespeichert sind, _muss_ das Feld in der CSV-Datei mit der ID der Kundenklasse befüllt sein. Andernfalls wird der Kontakt nicht in dein plentymarkets System importiert.
Wenn du keine Kundenklassen im System erstellt hast, kannst du dieses Feld für den Import ignorieren.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Dropdown-Liste: Kundenklasse>>.

'''

[#zuordnungsfeld-kontakt-gesperrt]
==== Gesperrt

Entscheide, ob der Kontakt für den ihm zugewiesenen Mandanten gesperrt ist oder nicht.

[TIP]
Beim Erstellen eines neuen Kontaktdatensatz wird automatisch der Standardmandant zugewiesen.

*_Standardwert:_* `0`

[[table-mapping-fields-contacts-blocked]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|nicht gesperrt

|`1`
|gesperrt
|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Einstellung: Kontakt gesperrt>>.

'''

[#zuordnungsfeld-kontakt-bewertung]
==== Bewertung

Welche interne Bewertung möchtest du dem Kontakt geben? Gib eine Zahl zwischen -5 für die schlechteste Bewertung und 5 für die beste Bewertung ein. Die Bewertung des Kontakts dient ausschließlich der internen Verwendung und kann nicht von dem Kunden eingesehen werden.

*_Standardwert:_* `0`

[[table-mapping-fields-contacts-rating]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|5 graue Sterne. Keine Bewertung für den Kontakt gespeichert.

|`5`
|5 gelbe Sterne (beste Bewertung)

|`4`
|4 gelbe Sterne

|`3`
|3 gelbe Sterne

|`2`
|2 gelbe Sterne

|`1`
|1 gelber Stern

|`-1`
|1 roter Stern

|`-2`
|2 rote Sterne

|`-3`
|3 rote Sterne

|`-4`
|4 rote Sterne

|`-5`
|5 rote Sterne (schlechteste Bewertung)


|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Dropdown-Liste: Bewertung>>.

'''

[#zuordnungsfeld-kontakt-debitorenkonto]
==== Debitorenkonto

Das Debitorenkonto ist eine zusätzliche Nummer, die meist der Kundennummer oder der Debitorennummer des Kontakts in der Buchhaltung entspricht.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Feld: Debitorenkonto>>.

'''

[#zuordnungsfeld-kontakt-sprache]
==== Sprache

Gib die Sprache des Kontakts in deine CSV-Datei ein.

[TIP]
Wenn du später im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Vorlagen* Vorlagen in der hier gewählten Sprache erstellst, z.B. `nl`, werden die E-Mail-Vorlagen in dieser Sprache (in unserem Beispiel in Niederländisch) an den Kontakt versendet.

[TIP]
<<daten/interne-IDs#10, Auf dieser Handbuchseite>> findest du eine Liste mit den Sprachkürzeln.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Sprachkürzel nach dem Schema `nl`, `de`, `ro` etc.

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Dropdown-Liste: Sprache>>.

'''

[#zuordnungsfeld-kontakt-herkunft]
==== Herkunft

icon:warning[role="red"] [red]#Pflichtwert#

// Beschreibung ergänzen - Test mit Asad: aktuell funktioniert die Herkunft 1 = Webshop oder Marktplätze. Mit 0 hat der Import nicht funktioniert. Team Multi-Channel arbeitet gerade an einer Lösung, dass auch die IDs der Marktplätze mit angegeben werden können.

*_Standardwert:_* `1`

////
[[table-mapping-fields-herkunft]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|manuelle Anlage

|`1`
|Webshop und Marktplätze

|===
////

'''

[#zuordnungsfeld-kontakt-plenty-id]
==== plenty ID

Welcher plentymarkets ID (welchem Mandanten) soll der Kontakt zugewiesen werden? Gib die plentymarkets ID in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)


Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Dropdown-Liste: Mandant>>.

'''

[#zuordnungsfeld-kontakt-eigner-id]
==== Eigner-ID

Welchem Eigner soll der Kontakt zugewiesen werden? Gib die ID des Eigners in deine CSV-Datei ein.

[TIP]
Es können nur Eigner über die ID zugewiesen werden, bei denen im Benutzerkonto im Tab *Eigner* die Option *Kunde* aktiviert ist. Die IDs der Eigner findest du im Benutzerkonto im Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>

'''

[#zuordnungsfeld-kontakt-geburtsdatum]
==== Geburtsdatum

Gib das Geburtsdatum des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datum im Format jjjj-mm-tt

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Feld: Geburtstag>>.

'''

[#zuordnungsfeld-kontakt-valuta]
==== Valuta

// Dieser Eintrag muss entfernt werden, sobald die Entwickler das Feld aus dem Code entfernt haben

Dieses Zuordnungsfeld ist aktuell ohne Funktion und kann nicht für den Import von Kontakten verwendet werden. Du kannst aber einen Valuta-Wert für die <<#zuordnungsfeld-firma-valuta, Firma>> importieren.

'''

[#zuordnungsfeld-kontakt-skontofrist]
==== Skontofrist

// Dieser Eintrag muss entfernt werden, sobald die Entwickler das Feld aus dem Code entfernt haben

Dieses Zuordnungsfeld ist aktuell ohne Funktion und kann nicht für den Import verwendet werden. Du kannst aber einen Wert für die Skontofrist für die <<#zuordnungsfeld-firma-skonto-tage, Firma>> importieren.

'''

[#zuordnungsfeld-kontakt-skontosatz]
==== Skontosatz

// Dieser Eintrag muss entfernt werden, sobald die Entwickler das Feld aus dem Code entfernt haben

Dieses Zuordnungsfeld ist aktuell ohne Funktion und kann nicht für den Import verwendet werden. Du kannst aber einen Wert für den Skontosatz für die <<#zuordnungsfeld-firma-rabattsatz, Firma>> importieren.

'''


[#zuordnungsfeld-kontakt-zahlungsziel]
==== Zahlungsziel

// Dieser Eintrag muss entfernt werden, sobald die Entwickler das Feld aus dem Code entfernt haben

Dieses Zuordnungsfeld ist aktuell ohne Funktion und kann nicht für den Import verwendet werden. Du kannst aber einen Wert für das Zahlungsziel für die <<#zuordnungsfeld-firma-zahlungsziel, Firma>> importieren.

'''


[#zuordnungsfeld-kontakt-handelsvertreter-id]
==== Handelsvertreter-ID

// die Zuordnung hat nicht geklappt (Test mit Asad) - geprüft!

Gib die ID des Handelsvertreters, der dem Kontakt zugewiesen werden soll, in deine CSV-Datei ein.

[TIP]
Der Handelsvertreter muss als Typ *Handelsvertreter* im Kontaktdatensatz gespeichert sein, um diesem einem Kontakt zuzuweisen.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-kontakt-kontakt-id]
==== Kontakt-ID

Wenn du nur die Daten eines bestimmten Kontakts aktualisieren möchtest, gib die ID des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

'''

[#zuordnungsfeld-kontaktoptionen]
=== Kontaktoptionen

[#zuordnungsfeld-kontaktoptionen-telefon-privat]
==== Telefon Privat

Gib die private Telefonnummer des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-telefon-geschaeftlich]
==== Telefon Geschäftlich

Gib die geschäftliche Telefonnummer des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-mobiltelefon-privat]
==== Mobiltelefon Privat

Gib die private Mobiltelefonnummer des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-mobiltelefon-geschaeftlich]
==== Mobiltelefon Geschäftlich

Gib die geschäftliche Mobiltelefonnummer des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''
[#zuordnungsfeld-kontaktoptionen-e-mail-privat]
==== E-Mail privat

Gib die private E-Mail-Adresse des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-e-mail-geschaeftlich]
==== E-Mail Geschäftlich

Gib die geschäftliche E-Mail-Adresse des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-e-mail-paypal]
==== E-Mail PayPal

Gib die PayPal-E-Mail-Adresse des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-fax-privat]
==== Fax Privat

Gib die private Faxnummer des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-fax-geschaeftlich]
==== Fax Geschäftlich

Gib die geschäftliche Faxnummer des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-homepage-privat]
==== Homepage Privat

Gib die private Homepage des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-homepage-geschaeftlich]
==== Homepage Geschäftlich

Gib die geschäftliche Homepage des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-marktplatz-ebay]
==== Marktplatz eBay

Gib den eBay-Namen des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-marktplatz-amazon]
==== Marktplatz Amazon

Gib den Amazon-Namen des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-identifikationsnummer-klarna]
==== Identifikationsnummer Klarna

Wie lautet die Klarna Identifikationsnummer deines Kontakts? Gib die Nummer in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-identifikationsnummer-dhl]
==== Identifikationsnummer DHL

Wie lautet die DHL Kundennummer deines Kontakts? Gib die Nummer in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-payment-paypal]
==== Payment PayPal

// Beschreibung fehlt noch

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-payment-klarna]
==== Payment Klarna

Gib die Klarna-Kundennummer deines Kontakts in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-payment-standard]
==== Payment Standard

Gib die ID einer verfügbaren Zahlungsart in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#65#, Auf dieser Handbuchseite>> findest du die IDs für Zahlungsarten, Zahlungsarten-Schnittstellen und Martkplatz-Zahlungsarten. Die Zahlungsarten werden im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* gespeichert.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-benutzername-privat]
==== Benutzername Privat

Gib den privaten Benutzernamen des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-benutzername-geschaeftlich]
==== Benutzername Geschäftlich

Gib den geschäftlichen Benutzernamen des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-benutzername-forum]
==== Benutzername Forum

Falls du ein Forum nutzt, kannst du den Benutzernamen, den der Kontakt in diesem Forum verwendet, in deine CSV-Datei eingeben.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-gastzugang]
==== Gastzugang

Diese Option steht für alle Gastzugänge und Marktplätze zur Verfügung, nicht aber für Ceres-Gastbestellungen. Entscheide, welche Zugangsart der Kontaktdatensatz beim Import erhalten soll und die gib die entsprechende ID in deine CSV-Datei ein.

*_Standardwert:_* `0`

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|0
|regulärer Zugang

|1
|Gastzugang

|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-ansprechpartner]
==== Ansprechpartner

Gib den Ansprechpartner des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-briefanrede-privat]
==== Briefanrede Privat

Gib die private Briefanrede des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-briefanrede-geschaeftlich]
==== Briefanrede Geschäftlich

Gib die geschäftliche Briefanrede des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alhpanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-rechnungsadresse]
=== Rechnungsadresse

[#zuordnungsfeld-rechnungsadresse-adress-id]
==== Adress-ID

Gib die ID der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-name1]
==== Name1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name2* und *Name3* keine Werte importierst.

Gib den Firmennamen der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-name2]
==== Name2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name3* keine Werte importierst.

Gib den Vornamen des Kontakts aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-name3]
==== Name3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name2* keine Werte importierst.

Gib den Nachnamen des Kontakts aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-name4]
==== Name4

Gib eine Zusatzangabe zum Kontakt in deine CSV-Datei ein, z.B. "z.Hd. Herrn Max Mustermann".

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-adresse1]
==== Adresse1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse2* und *Adresse3* keine Werte importierst.

Gib die Straße aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-adresse2]
==== Adresse2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse3* keine Werte importierst.

Gib die Hausnummer aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-adresse3]
==== Adresse3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse2* keine Werte importierst.

Gib einen Adresszusatz zu der Rechnungsadresse in deine CSV-Datei ein, z.B. "Apartment 12a".

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-adresse4]
==== Adresse4

Gib weitere Zusatzinformationen ein. Dieses Feld steht dir zur freien Verfügung.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-postleitzahl]
==== Postleitzahl

Gib die Postleitzahl der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-ort]
==== Ort

icon:warning[role="red"] [red]#Pflichtwert#

Gib den Ort der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-laender-id]
==== Länder-ID* (oder ISO)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-staaten-id]
==== Staaten-ID

Gib die ID der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#30#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen IDs.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-rechnungsadresse-ueberprueft-am]
==== Überprüft am

// Es handelt sich vermutlich um die Bonität. Die Bonität kann nicht mehr im Backend geprüft werden, weshalb dieses Feld wohl entfernt werden muss --> Thomas fragen!

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datum im Format jjjj-mm-tt

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-titel]
==== Titel

Gib den Titel aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-rechnungsadresse-ansprechpartner]
==== Ansprechpartner

Gib den Ansprechpartner aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-rechnungsadresse-laender-iso-code]
==== Länder-ISO-Code* (oder ID)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-staaten-iso-code]
==== Staaten-ISO-Code

Gib den ISO-Code der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#30#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen IDs.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse]
=== Optionen der Rechnungsadresse

[#zuordnungsfeld-optionen-rechnungsadresse-umsatzsteuernummer]
==== Umsatzsteuernummer

Gib die Umsatzsteueridentifikationsnummer in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-externe-adress-id]
==== Externe Adress-ID

Gib die externe Adress-ID in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''
[#zuordnungsfeld-optionen-rechnungsadresse-gelangensbestaetigung]
==== Gelangensbestätigung

// was soll man denn von der Logik her hier eingeben? eine ID kann es ja nicht sein. Jedenfalls funktioniert ein alphanumerischer Import.

[TIP]
Um beim Versand in ein anderes Land der EU von der Umsatzsteuer befreit zu werden, müssen Händler anhand der Gelangensbestätigung nachweisen, dass die Ware aus Deutschland in einem anderen EU-Mitgliedstaat angekommen ist.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-telefon]
==== Telefon

Gib die Telefonnummer aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-e-mail]
==== E-Mail

Gib die E-Mail-Adresse der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-postnummer]
==== Postnummer

Bei der Postnummer handelt es sich um die Kundennummer von DHL. Gib die Postnummer in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-personennummer]
==== Personennummer

Gib die Personennummer des Kontakts in deine CSV-Datei ein.

// Identitätsnummer in Schweden

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-fsk]
==== FSK

Gib einen Wert für die Altersfreigabe in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-geburtstag]
==== Geburtstag

Gib das Geburtsdatum aus der Rechnungsadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datumsangabe im Format jjjj-mm-tt

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-titel]
==== Titel

Gib den Titel in der Rechnungsadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-ansprechpartner]
==== Ansprechpartner

Gib den Ansprechpartner in der Rechnungsadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-lieferadresse]
=== Lieferadresse

[#zuordnungsfeld-lieferadresse-adress-id]
==== Adress-ID

Gib die ID der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-name1]
==== Name1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name2* und *Name3* keine Werte importierst.

Gib den Firmennamen der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-name2]
==== Name2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name3* keine Werte importierst.

Gib den Vornamen des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-name3]
==== Name3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name2* keine Werte importierst.

Gib den Nachnamen des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-name4]
==== Name4

Gib eine Zusatzangabe zum Kontakt in deine CSV-Datei ein, z.B. "z.Hd. Herrn Max Mustermann".

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-adresse1]
==== Adresse1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse2* und *Adresse3* keine Werte importierst.

Gib die Straße des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-adresse2]
==== Adresse2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse3* keine Werte importierst.

Gib die Hausnummer des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-adresse3]
==== Adresse3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse2* keine Werte importierst.

Gib einen Adresszusatz zu der Lieferadresse in deine CSV-Datei ein, z.B. "Apartment 12a".

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-adresse4]
==== Adresse4

Gib weitere Zusatzinformationen zur Adresse ein. Dieses Feld steht dir zur freien Verfügung.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-postleitzahl]
==== Postleitzahl

Gib die Postleitzahl der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-ort]
==== Ort

icon:warning[role="red"] [red]#Pflichtwert#

Gib den Ort der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-laender-id]
==== Länder-ID* (oder ISO)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-staaten-id]
==== Staaten-ID

Gib die ID der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#30#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen IDs.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-ueberprueft-am]
==== Überprüft am

// Es handelt sich vermutlich um die Bonität. Die Bonität kann nicht mehr im Backend geprüft werden, weshalb dieses Feld wohl entfernt werden muss --> Thomas fragen!

[#zuordnungsfeld-lieferadresse-titel]
==== Titel

Gib den Titel aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-lieferadresse-laender-iso-code]
==== Länder-ISO-Code* (oder ID)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-lieferadresse-staaten-iso-code]
==== Staaten-ISO-Code

Gib den ISO-Code der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#30#, Auf dieser Handbuchseite>> findest du ein Liste mit den ISO-Codes.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adresse>>.

'''

[#zuordnungsfeld-optionen-lieferadresse]
=== Optionen der Lieferadresse

[#zuordnungsfeld-optionen-lieferadresse-umsatzsteuernummer]
==== Umsatzsteuernummer

Gib die Umsatzsteueridentifikationsnummer in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.
'''

[#zuordnungsfeld-optionen-lieferadresse-externe-adress-id]
==== Externe Adress-ID

Gib die externe Adress-ID in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.
'''

[#zuordnungsfeld-optionen-lieferadresse-gelangensbestaetigung]
==== Gelangensbestätigung

// Beschreibung ergänzen. was soll man denn von der Logik her hier eingeben? eine ID kann es ja nicht sein. Jedenfalls funktioniert ein alphanumerischer Import.

[TIP]
Um beim Versand in ein anderes Land der EU von der Umsatzsteuer befreit zu werden, müssen Händler anhand der Gelangensbestätigung nachweisen, dass die Ware aus Deutschland in einem anderen EU-Mitgliedstaat angekommen ist.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-telefon]
==== Telefon

Gib die Telefonnummer aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-e-mail]
==== E-Mail

Gib die E-Mail-Adresse der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-postnummer]
==== Postnummer

Bei der Postnummer handelt es sich um die Kundennummer von DHL. Gib die Postnummer in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-personennummer]
==== Personennummer

// Identitätsnummer in Schweden

Gib die Personennummer des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-fsk]
==== FSK

// Freiwillige Selbstkontrolle, Altersfreigabe

Gib einen Wert für die Altersfreigabe in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-geburtstag]
==== Geburtstag

Gib das Geburtsdatum aus der Lieferadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datumsangabe im Format jjjj-mm-tt

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-titel]
==== Titel

Gib den Titel in der Lieferadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-ansprechpartner]
==== Ansprechpartner

Gib den Ansprechpartner in der Lieferadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Adresse öffnen » Bereich: Adressoptionen>>.

'''

[#zuordnungsfeld-firma]
=== Firma

[#zuordnungsfeld-firma-firmen-id]
==== Firmen-ID

Gib die ID der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-nummer]
==== Nummer

// wo soll diese Nummer stehen? Habe eine Nummer im Import angegeben, aber die Nummer taucht in der Firma nicht auf.

Zusätzliche Nummer für die Firma. Diese Nummer kann selbst vergeben werden. Maximale Zeichenlänge: 128. Gib die ID der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-firmenname]
==== Firmenname

icon:warning[role="red"] [red]#Pflichtwert#

Gib den Namen der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-steuer-id]
==== Steuer-ID

Gib die Umsatzsteueridentifikationsnummer der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

*_Beispiel:_* Für Deutschland: DE123456789

'''

[#zuordnungsfeld-firma-valuta]
==== Valuta

Gib die Valuta der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-skonto-tage]
==== Skonto Tage

Gib die Skontofrist der Firma in Tagen in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-rabattsatz]
==== Rabattsatz

Gib den Skontosatz der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-zahlungsziel]
==== Zahlungsziel

Gib das Zahlungsziel der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-handelsvertreter-id]
==== Handelsvertreter-ID

// das scheint nicht zu funktionieren

Gib die ID des Handelsvertreters der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-eigner-id]
==== Eigner-ID

Gib die ID des Eigners in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-lieferzeit]
==== Lieferzeit

Gib die Lieferzeit in Tagen für den Typ *Lieferant* in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-mindestbestellwert]
==== Mindestbestellwert

Gib den Mindestbestellwert in der Systemwährung für den Typ *Lieferant* in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-lieferantenwaehrung]
==== Lieferantenwährung

Gib den dreistelligen ISO-Code für die Währung für den Typ *Lieferant* in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#36#, Auf dieser Handbuchseite>> findest du ein Liste mit den ISO-Codes.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

*_Beispiele:_* `EUR` für Euro, `AUD` für australische Dollar.

[#zuordnungsfeld-handelsvertreter]
=== Handelsvertreter

[#zuordnungsfeld-handelsvertreter-region-id]
==== Region-ID

Gib die ID der Region in deine CSV-Datei ein.

// ? Die ID der Region sieht man im Kontaktdatensatz eines HV gar nicht.

[TIP]
<<daten/interne-IDs#30#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen IDs.

// ?

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

////
Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.
////

'''

[#zuordnungsfeld-handelsvertreter-plz-bereich]
==== PLZ-Bereich

Gib den Postleitzahlenbereich, in dem der Handelsvertreter tätig ist, in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Handelsvertreter>>.

*_Beispiel:_* `34117-34131` oder `34-35`

'''

[#zuordnungsfeld-handelsvertreter-laender-id]
==== Länder-ID

// noch prüfen

Gib die ID des Landes in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Handelsvertreter>>.

'''

[#zuordnungsfeld-erlaubte-zahlungsarten]
=== Erlaubte Zahlungsarten

[#zuordnungsfeld-erlaubte-zahlungsarten-lastschrift-erlauben]
==== Lastschrift erlauben

Möchtest du die Zahlungsart Lastschrift für den Kontakt erlauben?

[TIP]
Die Zahlungsart muss im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* aktiviert sein.

*_Standardwert_*: `0`

[[table-mapping-contacts-allow-debit]]
[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Zahlungsart Lastschrift ist _nicht_ erlaubt.

|`1`
|Zahlungsart Lastschrift ist erlaubt.
|====

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Einstellung: Lastschrift erlauben>>.

'''

[#zuordnungsfeld-erlaubte-zahlungsarten-rechnung-erlauben]
==== Rechnung erlauben

Möchtest du die Zahlungsart Rechnung für den Kontakt erlauben?

[TIP]
Die Zahlungsart muss im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* aktiviert sein.

*_Standardwert_*: `0`

[[table-mapping-contacts-allow-invoice]]
[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Zahlungsart Rechnung ist _nicht_ erlaubt.

|`1`
|Zahlungsart Rechnung ist erlaubt.
|====

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details » Einstellung: Rechnung erlauben>>.

'''

[#zuordnungsfeld-eigenschaften]
=== Eigenschaften

[#zuordnungsfeld-eigenschaften-eigenschafts-id]
==== Eigenschafts-ID

Gib die ID der Eigenschaft in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

'''

[#zuordnungsfeld-eigenschaften-eigenschaftstyp]
==== Eigenschaftstyp

icon:warning[role="red"] [red]#Pflichtwert#

Gib den Eigenschaftstyp in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

[[table-mapping-fields-contacts-property-type]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|Kein
|

|Ganze Zahl
|

|Auswahl
|

|Mehrfachauswahl
|

|Kurztext
|

|Text
|

|Datum
|

|Datei
|

|===


Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

'''

[#zuordnungsfeld-eigenschaften-eigenschaftswert]
==== Eigenschaftswert

Gib den Wert der Eigenschaft in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

*_Beispiel:_* Wenn du als Eigenschaftstyp *xx* gewählt hast, würde im Kontaktdatensatz z.B. xxx angezeigt werden.

'''

[#zuordnungsfeld-eigenschaften-kontakt-id]
==== Kontakt-ID

Gib die ID des Kontakts, der mit der Eigenschaft verknüpft ist, in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.
'''

[#zuordnungsfeld-eigenschaften-sprache]
==== Sprache

Gib das Sprachkürzel, z.B. *en* oder *fr* in deine CSV-Datei ein, wenn die Eigenschaft in anderen Sprachen als in der Systemsprache hinzugefügt werden soll.

[TIP]
<<daten/interne-IDs#10, Auf dieser Handbuchseite>> findest du eine Liste mit den Sprachkürzeln.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

'''

[#zuordnungsfeld-eigenschaften-loeschen]
==== Löschen (Ja/Nein)

Möchtest du die Eigenschaft löschen?

*_Standardwert_*: `0`

// noch testen

[[table-mapping-contacts-delete-property]]
[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Eigenschaft wird _nicht_ gelöscht

|`1`
|Eigenschaft wird gelöscht
|====

'''
