= Kategorien
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Kategorien
:position: 80
:url: daten/daten-importieren/sync-typen/elasticSync-kategorien
:id: GV1MLXQ

Kategorien helfen dir Produkte übersichtlich zu gruppieren. Sie bestimmen, wie deine Artikel im Webshop strukturiert werden.

//Wie sollen deine Artikel im Webshop strukturiert werden? Welche Warengruppen passen zu deinem Produktkatalog?
//Beantworte diese Fragen für dein eigenes Unternehmen und erstelle die notwendigen Kategorien.
//##fix intro: you can use it to import lots of new categories at once or to update lots of category info at once##
Grundsätzlich gibt es zwei Möglichkeiten, Kategorien zu erstellen oder zu aktualisieren.
Wenn du _nur wenige Kategorien_ anlegen oder modifizieren willst, empfiehlt es sich, dies <<artikel/einstellungen/kategorien#200,manuell zu tun>>.
//Wenn du _nur wenige Kategorien_ anlegen oder bearbeiten willst, empfiehlt sich die <<artikel/einstellungen/kategorien#200, manuelle Erstellung>>.
Hast du aber dagegen _eine Vielzahl an Kategorien_, dann ist es wahrscheinlich schneller, deine Kategoriedaten zu importieren.

Darum geht es auf dieser Seite. Hier lernst du, Kategorieinformationen in plentymarkets zu importieren.
Dies ist sinnvoll, wenn du viele neue Kategorien auf einmal erstellen willst oder wenn du viele bestehende Kategorien auf einmal aktualisieren willst.
//Normalerweise importierst du Kategorien, weil du entweder viele neue Kategorien auf einmal erstellen willst, oder weil du viele Kategorien auf einmal aktualisieren willst.

[TIP]
.Voraussetzungen
====
Diese Seite setzt voraus, dass du bereits eine <<artikel/einstellungen/kategorien#100, sinnvolle Kategoriestruktur>> überlegt hast und dass du Grundkenntnisse über das <<daten/daten-importieren/ElasticSync#, ElasticSync-Tool>> hast.
====

== Praxisbeispiel

Stell dir mal vor, du verkaufst Kleidung in deinem Webshop. Du bist ganz neu bei plentymarkets und möchtest alle deine Kategoriedaten auf einmal importieren. Du hast deine Kategorien wie folgt strukturiert:

[cols="3*^", grid=cols, frame=none, stripes=none]
|====

a|* Damen
** Accessoires
** Schuhe
** Bekleidung
*** Jeans
*** Tops
a|* Herren
** Accessoires
** Schuhe
** Bekleidung
*** Jeans
*** Tops
a|* Kinder
** Accessoires
** Schuhe
** Bekleidung
*** Jeans
*** Tops
|====

//Ausgangssituationen - welche Kategorien und welche Info hängt an die Kategorien

=== CSV-Datei einrichten

Übertrage zunächst diese Kategoriestruktur in eine CSV-Datei.
//Dies ist die Datei, die du in plentymarkets importieren wirst.
In unserem Beispiel würden die Kategorien in der CSV-Datei so aussehen:

##image##

//Deine Datei benötigt drei Spalten.
Die Namen der Spaltenüberschriften können frei gewählt werden.
In diesem Beispiel habe ich folgende Kategorieinformationen in die Spalten eingefügt:

* *Name* = Der Name der Kategorie.
* *Parentname* = Wenn dies eine Hauptkategorie sein soll, d.h. eine Kategorie auf der ersten Ebene, dann lass dieses Feld leer. Wenn dies eine Unterkategorie sein soll, dann gib den Pfad der direkt darüber liegenden Kategorie an. _Nutze Semikolons_, um die einzelnen Kategorieebenen zu trennen.
* *Multiname* = Der vollständige Kategoriepfad, d.h. sowohl der Parentname als auch der Name. _Nutze Kommas_, um die einzelnen Kategorieebenen zu trennen.

//Wie muss man die CSV Datei machen?

[discrete]
==== Zusätzliche Kategorie-Infos ergänzen

Wahrscheinlich willst du viel mehr als nur eine nackte Kategoriestruktur schaffen. Vielleicht willst du ja Beschreibungstexte oder SEO-relevante Metadaten ebenfalls ergänzen.
//Oder vielleicht willst du einige Kategorien nur für eingeloggte Benutzer zugänglich machen.

Füge ganz einfach weitere Spalten zu deiner CSV-Datei hinzu und verwende diese, um zusätzliche Kategorieinformationen anzugeben.
Zum Beispiel so:
//Füge deiner CSV-Datei ein paar zusätzliche Spalten hinzu und benutze sie, um deine Kategorien individuell anzupassen.

##image##

Die Namen der Spaltenüberschriften können frei gewählt werden.
Du kannst einige oder alle der in <<tabelle-Zuordnungsfelder-Kategorie>> aufgeführten Kategorieinformationen hinzufügen.
In diesem Beispiel habe ich mich entschieden, folgende Informationen zu ergänzen:

//* *Typ* = Kategorien können in plentymarkets auf verschiedene Weise verstanden werden. Ob jede Kategorie im Sinne einer Warengruppe oder im Sinne einer Content-Seite im Webshop verstanden werden soll. ##what happens if i leave this blank? Item is default?##
* *Beschreibung* = Eine Beschreibung jeder Kategorie.
* *Keywords* = SEO-relevante Keywords für jede Kategorie. ##_Nutze Kommas_##, um die einzelnen Keywords zu trennen.
* *Linkliste* = Ob die einzelnen Kategorien in der Navigation des Webshops angezeigt werden sollen. +
1 = ja
* *Right* = Ob die einzelnen Kategorien nur für eingeloggte Nutzer sichtbar sein sollen. +
customer = nur für eingeloggte Nutzer
* *Aktiv* = Ob die Kategorie bereits beim Import für den Webshop aktiviert sein soll. +
1 = ja

=== Sync-Einstellungen wählen

//Nachdem du alle deine Kategorieinformationen in einer CSV-Datei zusammengestellt hast, bist du bereit, <<daten/daten-importieren/ElasticSync#1210, ein neues Sync>> zu erstellen.
<<daten/daten-importieren/ElasticSync#1210, Erstelle ein neues Sync>>.
Die meisten Einstellungen können frei gewählt werden.
Da du jedoch _Kategoriedaten_ importieren wirst, stelle sicher, dass du den *Typ* auf *Kategorien* gesetzt hast.

////
Da du jedoch Kategoriedaten importieren wirst, gibt es einige Einstellungen, die du wie folgt konfigurieren musst.

[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Typ*
|Wähle die Option *Kategorien*.

|separator?
|do all or only some work?

|anything else?
|?
|====
////

//Welche Sync-Einstellungen wählt man?

=== Abgleich-Einstellungen wählen

Während des Imports prüft plentymarkets, ob die Kategorie bereits existiert.
Dies geschieht mit Hilfe eines sogenannten Abgleichfeldes.

Da wir in diesem Beispiel _neue Kategorien_ importieren möchten, konfiguriere die Einstellungen wie folgt.

[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Kategoriename kombiniert*
|In welcher Spalte deiner CSV-Datei ist der vollständige Kategoriepfad aufgeführt? Wähle diese Spaltenüberschrift aus der ersten Dropdown-Liste. In unserem Beispiel wähle ich also die Spalte *Multiname*. +
Wähle das Trennzeichen aus der zweiten Dropdown-Liste. ##In unserem Beispiel wähle ich _Semikolon_.##

|*Import Optionen*
|Da du neue Kategorien importieren wirst, wähle die Option *Nur neue Daten importieren* oder *Neue Daten importieren, vorhandene aktualisieren*.
|====

//Welche Abgleich Einstellungen wählt man?

=== Zuordnung-Einstellungen wählen

Deine CSV-Datei ist bereits mit einer Menge Kategorieinformationen gefüllt. Überlege als nächstes, wo jede dieser Informationen in plentymarkets erscheinen soll, nachdem die Datei importiert wurde.

Da wir in diesem Beispiel die Kategoriestruktur und einige Zusatzinformationen importieren möchten, habe ich die Einstellungen wie folgt konfiguriert.

##image##

//Würdest du also die <<Kategorie manuell in plentymarkets konfigurieren>>, welche Einstellungen würdest du wählen?

//Welche Zuordnung Einstellungen wählt man?

=== Hat es funktioniert?

Bereit, deine Kategorien zu importieren? Führe den Sync aus und kontrolliere, dass die Daten korrekt in plentymarkets importiert wurden.

[.instruction]
Sync ausführen und Ergebnis prüfen:

. Aktiviere die zu importierenden Zeilen (icon:toggle-on[role="green"]).
. Führe den Sync aus (icon:play-circle-o[role="darkGrey"]). +
*_Hinweis:_* Dies kann einige Minuten dauern.
. Öffne das Menü *Artikel » Kategorien*.
. Prüfe, ob deine Kategorien richtig strukturiert wurden. +
*_Hinweis:_* Klicke ganz links auf das Ordner-Symbol (icon:folder[role="darkGrey"]) einer Kategorie, um die darin enthaltenen Unterkategorien zu sehen.
. Öffne einige Kategorien und prüfe ihre Einstellungen.

//Sync ausführen und hinterher prüfen, ob alles geklappt hat

[#2110]
== Felder für den Kategorieabgleich

In <<tabelle-Abgleichfelder-Kategorie>> werden Felder erläutert, die für den Abgleich von Kategoriedaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Abgleichfelder-Kategorie]]
.Abgleichfelder für Kategorieimport
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Kategorie-ID*
|In welcher Spalte der CSV-Datei werden Kategorie-IDs aufgelistet? Wähle diese Spalte hier.
Diese Option ist sinnvoll, wenn du _bestehende Kategorien aktualisieren_ möchtest.
//Wir empfehlen diese Option, wenn du bestehende Kategorien aktualisieren möchten.

*_Hintergrund-Info_*: Jede neu angelegte Kategorie erhält automatisch eine ID, die nicht geändert werden kann.
Die ID dient zur eindeutigen Kennzeichnung der Kategorie.
Da die ID eindeutig ist, lässt sich damit gut prüfen, ob der importierte Datensatz bereits in plentymarkets vorhanden ist.
//Pflegst du die gleiche Kategorie in mehrere Sprachen oder in mehrere Webshops? Jede Mandant- und Sprachversion der Kategorie hat die selbe ID.

|*Kategoriename Kombiniert*
|In welcher Spalte der CSV-Datei wird der vollständige Kategoriepfad aufgeführt? Wähle diese Spalte aus der ersten Dropdown-Liste und das Trennzeichen aus der zweiten Dropdown-Liste.
Diese Option ist sinnvoll, wenn du _neue Kategorien anlegen_ möchtest.

|*Kategoriename Ebene 1 - 6*
|In welcher Spalte der CSV-Datei wird der Kategoriename für diese Ebene aufgeführt? Wähle diese Spalte hier.
|====

[#2120]
== Felder für die Kategoriezuordnung

In <<tabelle-Zuordnungsfelder-Kategorie>> werden Felder erläutert, die für die Zuordnung von Kategoriedaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Zuordnungsfelder-Kategorie]]
.Zuordnungsfelder für Kategorieimport
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

3+|*Kategorie*

|*Elternkategorie ID*
|Nummerisch (interne ID)
|

|*Elternkategorie Name*
|Alphanummerisch
|

|*Typ*
|item +
container +
content +
blog
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, <<artikel/einstellungen/kategorien#700, welcher Kategorietyp>> beim Import vergeben wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Typ* gesetzt wurde.

* item = Artikel
* container = Container
* content = Content
* blog = Blog

|*In Linkliste anzeigen*
|0 +
1
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie in der Webshop-Navigation angezeigt>> wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *In Linkliste* gesetzt wurde.


* 0 = Nicht anzeigen
* 1 = Anzeigen

|*right*
|all +
customer
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie nur für eingeloggte Benutzer sichtbar>> sein wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Sichtbar* gesetzt wurde.

* all = Öffentlich
* customer = Nach Login

|*Sichtbar*
|0 +
1
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie in die Sitemap>> aufgenommen wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Sitemap* gesetzt wurde.

* 0 = Nicht anzeigen
* 1 = Anzeigen

|*Kategorie löschen*
|0 +
1
a|Möchtest du einige Kategorien löschen und andere aktualisieren? Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob die Kategorie gelöscht werden soll.

* 0 = Nein
* 1 = Ja

|*Elternkategorie anlegen wenn nicht vorhanden*
|
|

3+|*Details*

|*Name* +
[red]#(Pflichtwert)#
|Alphanummerisch
|Gib den <<artikel/einstellungen/kategorien#700, Namen der Kategorie>> in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass dieser Name in das Feld *Name* eingetragen wurde.

|*Beschreibung 1*; +
*Beschreibung 2*
|Alphanummerisch
|Gib eine <<artikel/einstellungen/kategorien#800, Beschreibung der Kategorie>> in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest, siehst du, dass dieser Text im Tab *Beschreibung 1* bzw. im Tab *Beschreibung 2* eingetragen wurde.

|*Kurzbeschreibung*; +
*Meta-Keywords*; +
*Meta-Beschreibung*; +
*Meta-Titel*; +
*URL-Name*
|Alphanummerisch
|Gib den Text in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass dieser Text <<artikel/einstellungen/kategorien#700, in das entsprechende Feld eingetragen>> wurde.

|*Position*
|Nummerisch
|Gib eine <<artikel/einstellungen/kategorien#700, Positionsnummer>> in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass diese Nummer in das Feld *Position* eingetragen wurde.

|*Template-Liste*; +
*Template-Produkt*; +
*Template-Seite* +
(nur für den alten Callisto-Webshop relevant)
|Alphanummerisch
|Gib den <<artikel/einstellungen/kategorien#700, Namen der gewünschten Vorlage>> in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass diese Vorlage ausgewählt wurde.

|*Volltextsuche*
|0 +
1
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie zum Suchindex der Kategoriesuche im Webshop>> hinzugefügt wird.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Volltextsuche* gesetzt wurde.

* 0 = Nein
* 1 = Ja

|*Robots*
|all +
index +
nofollow +
noindex +
nofollow_noindex
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie <<artikel/einstellungen/kategorien#700, Suchmaschinen-Crawlern>> mit der Seite und den Links auf dieser Seite verfahren werden.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Robots* gesetzt wurde.

* *all* = Webseite der Kategorie in Suchmaschinenindex aufnehmen und Links auf Seite folgen. +
* *index* = In Suchmaschinenindex aufnehmen. +
* *nofollow* = Links auf der Seite nicht folgen. +
* *noindex* = Nicht in den Suchmaschinenindex aufnehmen. +
* *nofollow_noindex* = Links nicht folgen und Webseite der Kategorie nicht in Suchmaschinenindex aufnehmen.

|*Platzhalter übersetzen*
|Y +
N +
L
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob <<artikel/einstellungen/kategorien#700, Template-Variablen und -Funktionen übersetzt>> werden.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Template-Variablen und -Funktionen übersetzen* gesetzt wurde.

* Y = Ja
* N = Nein
* L = Nur Link-Template-Variablen und -Funktionen

|*Canonical*
|Alphanummerisch
|Gibt es eine andere Kategorie mit dem gleichen Inhalt? Falls ja, gib <<artikel/einstellungen/kategorien#700, die URL für diese Kategorie>> in deine CSV-Datei ein.
Die URL ist auf max. 256 Zeichen begrenzt.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass diese URL in das Feld *Canonical* eingetragen wurde.

3+|*Elmar*

|*Elmar-Kategorie*
|Alphanummerisch
|Gib den <<artikel/einstellungen/kategorien#700, Namen der Elmar-Kategorie>> in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass diese Elmar-Kategorie ausgewählt wurde.

|*Verknüpfung löschen*
|0 +
1
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Verknüpfung der Elmar-Kategorie>> gelöscht werden soll.
Stell im Bereich *Zuordnung* auch den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass die *Elmar-Kategorie* überall dort gelöscht wurde, wo die Zahl 1 eingetragen wurde.

* 0 = Nicht löschen
* 1 = Löschen

3+|*Mandant (Shop)*

|*Aktiv*
|0 +
1
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie für einen bestimmten Webshop aktiviert>> werden soll.
Stell im Bereich *Zuordnung* auch den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Mandant (Shop)* gesetzt wurde.

* 0 = Für den angegebenen Mandanten _nicht aktiviert_.
* 1 = Für den angegebenen Mandanten _aktiviert_.
|====


////
[.subhead]
Beispiel 1: Preis- und Bestandsabgleich einer Variante

Mithilfe eines einfachen Syncs können Preise und Bestand einer Variante aktuell gehalten werden. Nachdem zunächst die Zuordnung im Sync vorgenommen wurde, muss ein Mapping erstellt werden. Dafür werden im Bereich Werte bestimmen des Mappings die plentymarkets Felder VariationSalesPrice und VariationStock gewählt. Nachdem die Werte bestimmt wurden, muss für VariationSalesPrice zunächst der zu aktualisierende Verkaufspreis (Preis, UVP) bestimmt werden. Es können auch mehrere Verkaufspreise mit nur einem Sync aktualisiert werden. Im nächsten Schritt wird die tatsächliche Verknüpfung mit einem Feld der Datenquelle vorgenommen. Beim Bestand kann neben dem Lager auch der Lagerort gewählt werden. Für VariationStock wird das Lager gewählt, für welches Bestand gebucht werden soll. Optional kann hier auch der Lagerort bestimmt werden. Um die Menge aus der Datenquelle zu übernehmen, muss noch das plentymarkets Feld quantity und das zugehörige Feld der Datenquelle verknüpft werden. Dabei wird immer eine Bestandskorrektur vorgenommen.

[.subhead]
Beispiel 2: Artikelbeschreibungen importieren

Für einen Artikel sollen Name, technische Daten und Meta-Keywords importiert werden. Dafür müssen zunächst diese plentymarkets Felder im Bereich Werte bestimmen des Mappings ausgewählt und übernommen werden. Für Artikelbeschreibungen wird im nächsten Schritt die Sprache gewählt. Eine Mehrfachauswahl ist möglich. Die Felder Name, Technische Daten und Meta-Keywords werden nun mit den gewünschten Feldern der Datenquelle verknüpft. Das heißt, dass die in den Datensätzen der Datenquelle vorhandenen Einträge für die zuvor gewählten plentymarkets Felder importiert werden. Zusätzlich kann der Import durch Filter weiter bestimmt oder eingegrenzt werden. So kann zum Beispiel eigestellt werden, dass die Artikelbeschreibungen nur importiert werden sollen, wenn der Artikel einer bestimmten Marke entspricht.
////
