= Artikel
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Artikel, Artikelanlage
:position: 10
:url: daten/daten-importieren/sync-typen/elasticSync-artikel
:id: QUGDW1A
:author: none

Diese Seite erläutert die Abgleich- und Zuordnungsfelder, die dir beim Importieren von Artikel- und Variantendaten zur Verfügung stehen. Diese Seite dient lediglich als Referenz und setzt voraus, dass du bereits Grundkenntnisse über das <<daten/daten-importieren/ElasticSync#, ElasticSync-Tool>> hast.

[IMPORTANT]
.Voraussetzungen
====
Um Artikeldaten per ElasticSync zu importieren, müssen die folgenden Datensätze in plentymarkets vorhanden sein:

* Kategorien (Menü *Artikel » Kategorien*)
* Verkaufspreise (Menü *Einrichtung » Artikel » Verkaufspreise*)

Um Variantendaten mit Attributen per ElasticSync zu importieren, müssen die folgenden Datensätze in plentymarkets vorhanden sein:

* Attribute und Attributwerte (Menü *Einrichtung » Artikel » Attribute*)
====

[TIP]
.Praxisbeispiel: Neue Artikel importieren
====
Stell dir mal vor, du bist ganz neu bei plentymarkets und möchtest alle deine Artikel und Varianten auf einmal importieren. Wie geht so etwas? Wirf einen Blick auf <<daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-variantenanlage#, dieses praktische Beispiel>>, welches dich Schritt für Schritt durch den Prozess führt.
====

[#1910]
== Felder für den Artikelabgleich

In <<tabelle-Abgleichfelder-Artikel>> werden Felder erläutert, die für den Abgleich von Artikeldaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Abgleichfelder-Artikel]]
.Abgleichfelder für Artikelimport
[cols="1,3"]
|====
|Abgleichfeld |Erläuterung

|Varianten-ID
|

|Variantennr.
|

|Externe Varianten-ID
|

|Barcode
|Aus der zweiten Dropdown-Liste den Barcode-Typ wählen.

|Artikel-ID
|Bei Varianten mit Attributen dieses Feld nur in Kombination mit Attributauswahlkombination nutzen.


|Attributauswahlkombination
|Bei Varianten mit Attributen dieses Feld nur in Kombination mit Artikel-ID nutzen.
Aus der zweiten Dropdown-Liste das Format wählen, in dem die Daten in der Datei vorliegen.

|Lieferanten-Artikel-Nr.
|

|====

[#1920]
== Felder für die Artikelzuordnung

//rewrite. Something along the lines of: In den folgenden Kapitel werden Felder erläutert, die für die Zuordnung von Artikel- und Variantendaten zur Verfügung stehen.
//since there are many different fields, the explainations have been divided into sub-chapters.
##In diesem Kapitel werden Felder erläutert##, die für die Zuordnung von Artikeldaten zur Verfügung stehen.

[TIP]
.Kein Zuordnungsfeld? Standardwert greift!
====
Wenn du eine bestimmte Information nicht in deine CSV-Datei aufnimmst, d.h. wenn du ein bestimmtes Zuordnungsfeld _nicht verwendest_, dann erhält dein Artikel bzw. deine Variante den Standardwert.
====

[#2260]
=== Artikel

In <<table-mapping-fields-items>> werden Felder erläutert, die für die Zuordnung von Artikeldaten zur Verfügung stehen.
##Diese Zuordnungsfelder entsprechen dem Tab *Global* innerhalb## des Artikeldatensatzes.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Artikeldatensatz nach dem Import öffnest, siehst du, dass die Einstellungen ##im Tab *Global*## wie folgt konfiguriert wurden.

//Für den Artikelimport stehen die in <<tabelle-Zuordnungsfelder-Artikel>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Zuordnungsfelder-Artikel]]
.Felder für Artikelimport
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Warentyp
|0 +
1 +
2 +
3
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Typ>>

* 0 = Lagerware
* 1 = Produktionsware
* 2 = Colli
* 3 = Bestellware

|Shop-Aktion
|0 +
1 +
2 +
3
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Webshop » Option: Shop-Aktion>>

* 0 = Keine
* 1 = Sonderangebot
* 2 = Neuheit
* 3 = Top-Artikel

|##Eigner##
|Nummerisch (interne User-ID)
|
|ID der Eigner siehe *Einrichtung » Einstellungen » Benutzer » Konten*

|Hersteller-ID
|Nummerisch (interne ID)
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Hersteller>>

Die Zuordnung erfolgt über die Hersteller-ID im Menü *Einrichtung » Artikel » Hersteller*.

|Herstellungsland
|Nummerisch (interne ID); +
0 = unbekannt
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Herstellungsland>>

Die Zuordnung erfolgt über die <<basics/interne-IDs#20, Liste der Länder-IDs>>.

|Zolltarifnummer
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Zolltarifnummer>>

|##Erlöskonto##
|0 = Nein +
1 = Ja
|
|

|Aktionsgutschein
|0 +
1 +
2
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Aktionsgutschein/POS-Rabatt>>

* 0 = Möglich
* 1 = Verboten
* 2 = Nur mit Gutschein kaufbar

|Zustand
|0 +
1 +
2 +
3 +
4
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Zustand>>

* 0 = Neu
* 1 = Gebraucht
* 2 = Neu und originalverpackt
* 3 = Neu mit Etikett
* 4 = B-Ware

|Zustand API
|0 +
1 +
2 +
3 +
4 +
5
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Zustand API>>

* 0 = Neu
* 1 = Gebraucht wie neu
* 2 = Gebraucht sehr gut
* 3 = Gebraucht gut
* 4 = Gebraucht annehmbar
* 5 = B-Ware

|Abonnement (Ja/Nein)
|0 +
1
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Abonnement>>

* 0 = Nein
* 1 = Ja

|Seriennummer (Ja/Nein)
|0 +
1
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Seriennummer>>

* 0 = Nein
* 1 = Ja

|Versandpaket (Ja/Nein)
|0 +
1
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Versandpaket>>

* 0 = Nein
* 1 = Ja

|Amazon-Abwicklung (FBA)
|0 +
1 +
2 +
3 +
-1
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Amazon » Option: FBA-Abwicklung>>

* 0 = Nicht verwenden
* 1 = AMAZON_EU
* 2 = AMAZON_FE
* 3 = AMAZON_NA
* -1 = FBA und SellerCentral

|Versand durch Amazon (FBA)
|0 +
1
|
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Amazon » Option: Amazon FBA>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Amazon-Produkttyp
|Nummerisch
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Amazon » Option: Produkttyp>>

Die Zuordnung erfolgt über die <<basics/interne-IDs#130, Wertetabelle amazon_product_type>>.

|##Amazon-FEDAS##
//0 und 1 macht dafür gar kein Sinn
|0 = Nein +
1 = Ja
|
|FEDAS-Warengruppenschlüssel

|Listing-Vorlage
|Nummerisch (interne ID)
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Listing-Voreinstellungen » Option: Listing-Vorlage>>

Die Zuordnung erfolgt über die Listing-Vorlage-ID im Menü *Listings » Listings*.

|Listing Kategorie 1; +
Listing Kategorie 2
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Listing-Voreinstellungen » Option: Kategorie 1>>

|Listing Shop-Kategorie 1; +
Listing Shop-Kategorie 2
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Listing-Voreinstellungen » Option: Kategorie 1>>


|Rakuten.de-Kategorien
|Nummerisch (interne ID)
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Kategorieverknüpfung » Option: Rakuten.de>>

|Markierung 1; +
Markierung 2
|Nummerisch (interne ID)
|
|Entspricht der <<artikel/einstellungen/markierungen#, Markierung des Artikels>>.

Die Zuordnung erfolgt über die ID der Markierung im Menü *Einrichtung » Artikel » Makierungen » Tab: Markierung 1 bzw. Markierung 2*

|Altersfreigabe
|0 +
3 +
6 +
12 +
16 +
18 +
50 +
88 +
99
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Altersfreigabe>>

* 0 = Keine verfügbar
* 3 = FSK 3
* 6 = FSK 6
* 12 = FSK 12
* 16 = FSK 16
* 18 = FSK 18
* 50 = Nicht gekennzeichnet
* 88 = Nicht erforderlich
* 99 = Noch nicht bekannt

|Artikelbewertung
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Webshop » Option: Artikelbewertung>>

|Feld 1; +
Feld 2; +
Feld 3; +
... +
Feld 20
|Alphanummerisch
|
|Entspricht den Freitextfeldern 1 bis 20 unter: +
<<artikel/artikel-verwalten#70, Tab: Felder>>

|Max. Artikelbestellmenge
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Max. Bestellmenge>>

|##Typ##
//geht auch set? kann man nicht nachträglich ändern, oder?
|standard = Artikel des Typs *Standard* +
multipack = Artikel des Typs *Multipack* +
|
|Wenn kein Artikeltyp angegeben wird, wird automatisch der Typ *Standard* angenommen.


|Herstellername
|Alphanummerisch
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Hersteller>>

Die Zuordnung erfolgt über den Herstellernamen. Wenn der Herstellerdatensatz nicht bereits im System vorhanden ist, wird ein neuer Herstellerdatensatz angelegt.

//wo findet man Artikelvorlage?
//|Artikelvorlage
//|Nummerisch
//|
//|ID der Kategorie der <<artikel/artikel-verwalten#720, Artikelvorlage>> +
//*_Hinweis:_* Artikelvorlagen gibt es nur im alten Webdesign Callisto.

|Artikel löschen
|0 +
1
|
a|Möchtest du einige Artikel löschen und andere aktualisieren? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob der Artikel gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====

[#3000]
=== ##Artikelsets##

Für den Import von Artikelsets stehen die in <<tabelle-zuordnungsfelder-artikelsets>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-artikelsets]]
.Felder für Import von Artikelsets
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Bestandteile hinzufügen (IDs, kommasepariert)
|Alphanummerisch
|
|IDs und Anzahl der Artikel, die zum Set hinzugefügt werden +
Format: *artikelID:menge,artikelID:menge*

|Bestandteile entfernen (IDs, kommasepariert)
|Alphanummerisch
|
|IDs der Artikel, die aus dem Set entfernt werden

|Rabatt
|Dezimalzahl
|
|Rabatt auf den Gesamtpreis des Sets in %
|====

[#2310]
=== ##Cross-Selling##

Für den Import von Cross-Selling-Verknüpfungen stehen die in <<tabelle-zuordnungsfelder-crossselling>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-crossselling]]
.Felder für Import von Cross-Selling-Verknüpfungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Alle Cross-Selling-Verknüpfungen löschen
|0 = Nein +
1 = Ja
|
|

|Cross-Selling-Verknüpfungen hinzufügen
|Alphanummerisch
|
|Cross-Selling-Verknüpfung im Format +
*Artikel-ID:Beziehungstyp;Artikel-ID:Beziehungstyp;etc.* +
Verfügbare Beziehungstypen: +
Accessory = Zubehör +
ReplacementPart = Ersatzteil +
Similar = Ähnlich +
Bundle = Artikelpaket

|Cross-Selling-Verknüpfungen löschen
|Nummerisch
|
|Zu löschende Cross-Selling-Verknüpfungen im Format +
 *Artikel-ID;Artikel-ID;etc.*
|====


[#2270]
=== Artikelbeschreibung

Für den Import der Artikelbeschreibungen stehen die in <<tabelle-zuordnungsfelder-artikelbeschreibung>> aufgelisteten Felder zur Verfügung. Pro Sprache wird eine Zuordnung erstellt. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-artikelbeschreibung]]
.Felder für Import von Artikelbeschreibungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Name; +
Name 2; +
Name 3
|Alphanummerisch
|
|Gib einen Namen für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Name 1, 2, 3>>

|Vorschautext
|Alphanummerisch
|
|Gib einen Vorschautext für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Vorschautext>>

|Meta-Beschreibung
|Alphanummerisch
|
|Gib eine Meta-Beschreibung für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Meta-Beschreibung>>

|Artikeltext
|Alphanummerisch
|
|Gib einen Artikeltext für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Artikeltext>>

|Technische Daten
|Alphanummerisch
|
|Gib technische Daten für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Technische Daten>>

|URL-Pfad
|Link
|
|Gib einen URL-Pfad für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: URL-Pfad>>

|Meta-Keywords
|Alphanummerisch
|
|Gib Meta-Keywords für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Meta-Keywords>>
|====

[#2280]
=== ##Versandprofil##

Für den Import von Versandprofilen stehen die in <<tabelle-zuordnungsfelder-versandprofile>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-versandprofile]]
.Abgleichfelder für Versandprofile
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Versandprofil-ID
|Nummerisch
|
|

|Versandprofile (kommasepariert)
|Profil-ID1,Profil-ID2,...
|
|Ermöglicht den Import von mehr als einem Versandprofil

|Versandprofilverknüpfungen löschen (Profil-IDs, kommasepariert)
|Alphanummerisch
|
|
|====


[#2300]
=== Varianten

Für den Import von Variantendaten stehen die in <<tabelle-zuordnungsfelder-varianten>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-varianten]]
.Abgleichfelder für Varianten
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|##ID##
|Nummerisch
|
|Entspricht der ID der Variante.

|##Artikel-ID##
|Nummerisch
|
|Entspricht der ID des Artikels.

|Position
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Position>>

|Aktiv
|0 +
1
|
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Aktiv>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Variantennr.
|Alphanummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Variantennr.>>

|Modell
|Alphanummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Modell>>

|Externe Varianten-ID
|Alphanummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Ext. Varianten-ID>>

|Verfügbarkeit
|Nummerisch (interne ID)
|
|Entspricht den Verfügbarkeitssymbolen 1 bis 10 unter: +
<<artikel/artikel-verwalten#190, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Verfügbarkeit>>

|EK netto
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: EK netto>>

|GLD EK netto
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: GLD EK netto>>

|##Preiskalkulation##
|Nummerisch (interne ID)
|
|

|WB-Beschränkung
|0 +
1 +
2
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#190, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Beschränkung>>

* 0 = Keine
* 1 = Auf Netto-WB
* 2 = Keinen WB für diese Variante führen

|Sichtbarkeit Mandant: Automatisch sichtbar, wenn Netto-WB positiv; +
Sichtbarkeit Mandant: Automatisch unsichtbar, wenn kein Netto-WB
|0 +
1
|
a|Entspricht der gleichnamigen Checkbox unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Verfügbarkeit Webshop: Automatisch verfügbar, wenn Netto-WB positiv; +
Verfügbarkeit Webshop: Automatisch nicht verfügbar, wenn kein Netto-WB
|0 +
1
|
a|Entspricht der gleichnamigen Checkbox unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

* 0 = Kein Häkchen
* 1 = Häkchen

//|Sichtbarkeit Artikelauflistung: Immer unsichtbar
//|0 = Nein +
//1 = Ja
//|
//|Entspricht die gleiche <<artikel/artikel-verwalten#230, Verfügbarkeitseinstellung>> in der Artikelübersicht.

|Sichtbarkeit Artikelauflistung: Automatisch sichtbar, wenn Netto-WB positiv; +
Sichtbarkeit Artikelauflistung: Automatisch unsichtbar, wenn kein Netto-WB
|0 = Nein +
1 = Ja
|
a|Entspricht der gleichnamigen Checkbox unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Hauptlager
|Nummerisch (interne ID)
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#190, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Hauptlager>>

Die Zuordnung erfolgt anhand der Lager-ID im Menü *Einrichtung » Waren » Lager » Lager öffnen » Einstellungen*.

|Max. Bestellmenge
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Max. Bestellmenge>>

|Min.-Bestellmenge
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Min.-Bestellmenge>>

|Intervallbestellmenge
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Intervallbestellmenge>>

|Verfügbar bis
|Datum +
(DD.MM.YYYY)
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Verfügbar bis>>

|Erscheinungsdatum
|Datum +
(DD.MM.YYYY)
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Erscheinungsdatum>>

|Name
|Alphanummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Variantenname>>

|Gewicht brutto g; +
Gewicht netto g
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Gewicht brutto bzw. Gewicht netto>>

Achte darauf, dass du das _Gewicht in Gramm_ anstatt in Kilogramm angibst.

|Breite mm; +
Länge mm; +
Höhe mm
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Länge/Breite/Höhe>>

Achte darauf, dass du die _Maße in Millimetern_ angibst.

|Portoaufschlag 1; +
Portoaufschlag 2
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#290, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Portoaufschlag 1 bzw. Portoaufschlag 2>>

|##VPE##
|Nummerisch
|
|Verpackungseinheit; Standard = 1

|Anzahl der Packstücke
|0 +
1 +
2 +
... +
20
|
|Entspricht der _ersten Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#290, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Packstücke>>

Verwende dieses Zuordnungsfeld zusammen mit *Einheit der Packstücke*.

|Einheit der Packstücke
|0 +
1 +
2 +
... +
39
|
a|Entspricht der _zweiten Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#290, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Packstücke>>

Verwende dieses Zuordnungsfeld zusammen mit *Anzahl der Packstücke*.

* 0 = unverpackt
* 1 = Ballen
* 2 = Behälter
* 3 = Bund
* 4 = Rollpalette
* 5 = Colli
* 6 = Container
* 7 = Eimer
* 8 = Fass
* 9 = Flaschen
* 10 = Euro Pool Flachpalette
* 11 = Gestell
* 12 = Gasflasche
* 13 = Gitterboxpalette
* 14 = Hobbock
* 15 = Halbe Palette
* 16 = Lebensmittelpalette
* 17 = Holzuntersetzer
* 18 = IBC Container
* 19 = Kanne
* 20 = Korbflasche
* 21 = Kiste
* 22 = Kanister
* 23 = Kundenpalette
* 24 = Karton
* 25 = Kombinationsverpackung
* 26 = Pack
* 27 = Ring
* 28 = Rolle
* 29 = Sack
* 30 = Stück
* 31 = Tank
* 32 = Trommel
* 34 = Verschlag
* 35 = Viertelpalette
* 36 = sonstige Paletten
* 37 = Kasten
* 38 = Einwegpalette
* 39 = Folientüte

|Transportkosten netto
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Transport netto>>

|Lagerkosten netto
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Lager netto>>

|Zoll
|Nummerisch
(Prozentwert)
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Zoll>>

|Betriebskosten
|Nummerisch
(Prozentwert)
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Betriebskosten>>

|##Umsatzsteuer##
|Nummerisch
(Prozentwert)
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Umsatzsteuer>>

|##Paketart##
|bundle = Variante ist Paket +
bundle_item = Variante ist Paketbestandteil
|
|

|##Sichtbarkeit Artikelauflistung: Immer unsichtbar##
|0 = Nein +
1 = Ja
|
|

|Grundpreis anzeigen
|0 +
1
|
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Grundpreisanzeige>>

* 0 = Nein
* 1 = Ja

|Gewicht brutto aus Paketbestandteilen berechnen; +
Gewicht netto aus Paketbestandteilen berechnen; +
EK netto aus Paketbestandteilen berechnen; +
GLD EK netto aus Paketbestandteilen berechnen
|0 +
1
|
a|Entspricht den Checkboxen unter: +
<<artikel/artikel-verwalten#265, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Paket » Option: Automatisch aus Paketbestandteilen berechnen>>

* 0 = Nein
* 1 = Ja

*_Hinweis_*: Diese Checkboxen sind nur für <<artikel/anwendungsfaelle/multipacks-pakete-sets#, Artikelpakete>> sichtbar.

|Kommissionierung
|single_picking +
no_single_picking +
exclude_from_picklist
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Kommissionierung>>

* single_picking = Einzelkommissionierung möglich
* no_single_picking = Keine Einzelkommissionierung möglich
* exclude_from_picklist = Von Pickliste ausschließen

|Variante löschen
|0 +
1
|
a|Möchtest du einige Varianten löschen und andere aktualisieren? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Variante gelöscht werden soll.

* 0 = Nein
* 1 = Ja

|##Nummer der Hauptvariante##
//in wie fern unterscheidet sich das von der Variantennr. ganz oben?
|Alphanummerisch
|
|

//|tagVariationId
//|Nummerisch
//|
//|
|====

[#2320]
=== ##Barcodes##

Für den Import von Barcode-Daten stehen die in <<tabelle-zuordnungsfelder-barcodes>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Barcode-Typ.

[[tabelle-zuordnungsfelder-barcodes]]
.Felder für Import von Barcodes
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Code
|Alphanummerisch
|
|

|Barcode löschen
|0 = Nein +
1 = Ja
|
|
|====

[#2330]
=== ##Variantenpreise##

Für den Import von Variantenpreisen stehen die in <<tabelle-zuordnungsfelder-preis>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Verkaufspreis.

[[tabelle-zuordnungsfelder-preis]]
.Felder für Import von Variantenpreisen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Preis
|Nummerisch
|
|Verkaufspreis aus der Dropdown-Liste rechts wählen, der dem Import zugewiesen werden soll.

|Preis löschen
|0 = Nein +
1 = Ja
|
|Löscht einen zugeordneten Preis.

|Nettopreis (Ja/Nein)
|0 = Nein +
1 = Ja
|
|Wählen, ob der Preis als Nettopreis importiert werden soll.
|====

[#2340]
=== ##Kategorien##

Für den Import von Kategoriedaten stehen die in <<tabelle-zuordnungsfelder-kategorien>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-kategorien]]
.Felder für Import von Kategorien
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID der Kategorie
|Nummerisch (interne ID)
|
|Alternativ Name der Kategorie übergeben.

|Position
|Nummerisch
|
|

|Ist Neckermann.de Hauptkategorie
|0 = Nein +
1 = Ja
|
|

|Name der Kategorie
|Alphanummerisch
|
a|
* Vollständigen Kategoriepfad, semikolongetrennt (z.B. Schuhe;Unisex) +
oder
* ID der Kategorie

*_Tipp:_* Für weitere Kategorien zusätzliche Mappings erstellen.

|Alle Kategorieverknüpfungen löschen
|0 = Nein +
1 = Ja
|
|Löst alle verknüpften Kategorien.

|Kategorie-IDs (kommasepariert)
|Alphanummerisch
|
|IDs der Kategorien, die mit der Variante verknüpft werden sollen.

|Kategorienamen (kommasepariert)
|Alphanummerisch
|
|Name der Kategorien, die mit der Variante verknüpft werden sollen.

|Verknüpfungen löschen (Kategorie-IDs, kommasepariert)
|Alphanummerisch
|
|IDs der Kategorien, die von der Variante gelöst werden sollen.

|Verknüpfungen löschen (Kategorienamen, kommasepariert)
|Alphanummerisch
|
|Namen der Kategorien, die von der Variante gelöst werden sollen.

|Nicht gefundene Kategorien anlegen
|0 = Nein +
1 = Ja
|
|
|====

[#2345]
=== ##Standardkategorien##

Für den Import von Standardkategoriedaten stehen die in <<tabelle-zuordnungsfelder-standardkategorien>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-standardkategorien]]
.Felder für Import von Standardkategorien
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID der Kategorie
|Nummerisch (interne ID)
|
|ID der Standardkategorie

|Name der Kategorie
|Alphanummerisch
|
|Name der Standardkategorie

|Nicht gefundene Kategorien anlegen
|0 = Nein +
1 = Ja
|
|
|====

[#2350]
=== ##Bestand##

Für den Import von Bestandsdaten stehen die in <<tabelle-zuordnungsfelder-bestand>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-bestand]]
.Felder für Import von Bestand
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Lager
|Nummerisch (interne ID)
|
|Kann nur in Kombination mit Menge und Lagerort übergeben werden.

|Menge
|Nummerisch
|
|Kann nur in Kombination mit Lager und Lagerort übergeben werden.

|Lagerort
|Nummerisch (interne ID)
|
|Kann nur in Kombination mit Lager und Menge übergeben werden.
|====

[#2360]
=== ##Mandant (Shop)##

Für den Import der Mandantenverfügbarkeit stehen die in <<tabelle-zuordnungsfelder-mandant>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Mandant.

[[tabelle-zuordnungsfelder-mandant]]
.Abgleichfelder für Import von Mandantenverfügbarkeiten
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Aktiv
|0 = Nein +
1 = Ja
|
|
|====

[#2370]
=== ##Märkte##

Für den Import der Marktplatzverfügbarkeiten stehen die in <<tabelle-zuordnungsfelder-maerkte>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Marktplatz.

[[tabelle-zuordnungsfelder-maerkte]]
.Felder für Import von Marktplatzverfügbarkeiten
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Aktiv
|0 = Nein +
1 = Ja
|
|
|====

[#2380]
=== ##Attribute##

Für den Import von Attributverknüpfungen stehen die in <<tabelle-zuordnungsfelder-attribute>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Format.

[[tabelle-zuordnungsfelder-attribute]]
.Felder für Import von Attributverknüpfungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Attributauswahlkombination
|Alphanummerisch
|
|Kombination aus *Attributname (intern)* und *Attributwert (intern)* im Format +
*Attributname:Wertname;* oder *Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;* +
Import von mehr als zwei Attributverknüpfungen. +
*_Hinweis:_* Jede Attributauswahlkombination muss pro Variante einzigartig sein.

|Attribute ID
|Nummerisch
|
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die IDs in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine weitere im Format *Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;* erstellen und die separaten Spalten zuordnen.

|Attribute Name
|Alphanummerisch
|
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die Namen in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine weitere im Format *Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;* erstellen und die separaten Spalten zuordnen.

|Wert Name
|Alphanummerisch
|
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die Namen in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine weitere im Format *Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;* erstellen und die separaten Spalten zuordnen.

|Wert ID
|Nummerisch
|
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die IDs in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine weitere im Format *Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;* erstellen und die separaten Spalten zuordnen.

|Erstell nicht existierende Werte
|0 = Nein +
1 = Ja
|
|
|====

[#2390]
=== ##Artikelbilder##

Für den Import von Artikelbildern stehen die in <<tabelle-zuordnungsfelder-bilder>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-bilder]]
.Abgleichfelder für Import von Artikelbildern
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID des Bildes
|Nummerisch (interne ID)
|
|

|Position
|Nummerisch
|
|

|Dateiname
|Alphanummerisch
|
|

|Base64 Data
|Alphanummerisch
|
|

|URL
|Alphanummerisch
|
|Link zum Artikelbild

|Multi-URL (kommasepariert)
|Alphanummerisch
|
|Mehrere Bild-URLs im Format +
*image1url;positionImage1,* +
*image2url;positionImage2* +
Wenn keine Position übergeben wird, entspricht die Position der Reihenfolge der URLs.

|Bilder löschen
|0 = Nein +
1 = Ja
|
|1 löscht alle Bilder des Artikels. Bilder, die erhalten bleiben sollen, müssen als URL im Sync angegeben werden.

|Mit Variante verknüpfen
|0 = Nein +
1 = Ja
|
|1 verknüpft das Bild mit der Variante. +
0 löscht eine vorhandene Verknüpfung.

|Verfügbarkeit Mandant (Shop)
|Nummerisch (interne ID)
|
|ID des Mandanten, siehe *Einrichtung » Mandant » Mandant öffnen » Einstellungen* +
*-1* aktiviert alle Mandanten

|Verfügbarkeit Herkünfte
|Nummerisch (interne ID)
|
|ID der Auftragsherkunft, IDs siehe <<basics/interne-IDs#90, IDs der Auftragsherkünfte>> +
Mehrere Herkünfte können kommasepariert angegeben werden. +
*-1* aktiviert alle Herkünfte

|Verfügbarkeit Listings
|Nummerisch (interne ID)
|
|*-1* aktiviert alle Listings

|Namen
|Alphanummerisch
|
|Name des Artikelbilds im Format *Name:Sprache1,Name:Sprache2* +
Alternativtext des Artikelbilds im Format *Name:Sprache1:Alternativtext,Name:Sprache2:Alternativtext*

|Alternative Namen
|name1:sprache1,name2:sprache2
|
|

|Marktplatzattributverknüpfung (Attibutwert-ID)
|Nummerisch (interne ID)
|
|ID des Attributwerts

|Alle Verfügbarkeiten entfernen
|0 = Nein +
1 = Ja
|
|
|====

[#2400]
=== ##Merkmale##

Für den Import von Merkmalverknüpfungen stehen die in <<tabelle-zuordnungsfelder-merkmale>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-merkmale]]
.Felder für Import von Merkmalverknüpfungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID
|Nummerisch (interne ID)
|
|IDs siehe *Einrichtung » Artikel » Merkmale*

|Merkmalkombination
|Alphanummerisch
|
|Kombination aus Backend-Name, Wert und Sprache im Format +
*Name1:Wert1:Sprache1;Name2:Wert2:Sprache2* etc.

|Interner Name
|Alphanummerisch
|
|

|Wert
|Alphanummerisch
|
|

|Auswahl-ID
|Nummerisch (interne ID)
|
|Nur bei Merkmalen des Typs *Auswahl*. Verknüpft die Auswahlwerte eines Merkmals über die ID. +
Auswahl-IDs siehe *Einrichtung » Artikel » Merkmale » Merkmal öffnen*.

|Sprache
|Buchstaben
|
|Nur bei Merkmalen des Typs *Text* +
Codes siehe <<basics/interne-IDs#10, Sprachen>>

|Löschen (Ja/Nein)
|0 = Nein +
1 = Ja
|
|
|====

[#2410]
=== ##Eigenschaften##

Für den Import von Eigenschaftsverknüpfungen stehen die in <<tabelle-zuordnungsfelder-eigenschaften>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-eigenschaften]]
.Felder für Import von Eigenschaftsverknüpfungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID
|Nummerisch (interne ID)
|
|IDs siehe *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*

|Sprache
|Buchstaben
|
|Nur bei Eigenschaften des Typs *Text* oder *Kurztext* +
Codes siehe <<basics/interne-IDs#10, Sprachen>>

|Wert
|Alphanummerisch
|
|

|Beschreibung
|Alphanummerisch
|
|

|Interner Name
|Alphanummerisch
|
|

|Eigenschaftenkombination
|Alphanummerisch
|
|Kombination aus Name, Wert und Sprache im Format +
*Name1:Wert1:Sprache1;Name2:Wert2:Sprache2* etc.

|Auswahleigenschaftkombination (Namen)
|propertyName:selectionName:language;propertyName:selectionName:language
|
|

|Auswahleigenschaftkombination (IDs)
|propertyID:selectionID:language;propertyID:selectionID:language
|
|

|Auswahl-ID
|Nummerisch (interne ID)
|
|Nur bei Eigenschaften des Typs *Auswahl*. Verknüpft die Auswahlwerte einer Eigenschaft über die ID. +
Auswahl-IDs siehe *Einrichtung » Einstellungen » Eigenschaften » Konfiguration » Eigenschaft öffnen » Werte*.

|Löschen (Ja/Nein)
|0 = Nein +
1 = Ja
|
|
|====

[#2290]
=== Varianten-Tags

Für den Import von Tag-Verknüpfungen stehen die in <<tabelle-zuordnungsfelder-tags>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-tags]]
.Felder für Import von Tags-Verknüpfungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|##Tag-ID##
//kann man mehrere Tag IDs auch kommasepariert eingeben?
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib eine Tag-ID in die CSV-Datei ein.
Die Tag-IDs findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

|Tag-Name
|Alphanummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib einen Namen für das Tag in die CSV-Datei ein.
Die Tag-Namen findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

|Tag-Namen +
(kommasepariert)
|Alphanummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib die Namen von mehreren Tags in die CSV-Datei ein. Verwende Kommas, um die Namen wie folgt zu trennen: +
name1,name2,name3...

Die Tag-Namen findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

|Alle Tag-Verknüpfungen löschen
|0 +
1
|
a|Möchtest du _alle Tags_ von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Tag-Verknüpfungen gelöscht werden sollen.

* 0 = Nein
* 1 = Ja

*_Hinweis_*: Die Tags selbst werden nicht gelöscht. Die Tags werden lediglich von der Variante entfernt.

|Tag-Verknüpfung löschen (Name, kommasepariert)
|Alphanummerisch
|
a|Möchtest du _einige der Tags_ von einer Variante entfernen?
Gib die Namen der zu entfernenden Tags in die CSV-Datei ein. Verwende Kommas, um die Namen wie folgt zu trennen: +
name1,name2,name3…​

Die Tag-Namen findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

*_Hinweis_*: Die Tags selbst werden nicht gelöscht. Die Tags werden lediglich von der Variante entfernt.

|Tag-Verknüpfung löschen (ID, kommasepariert)
|Alphanummerisch
|
a|Möchtest du _einige der Tags_ von einer Variante entfernen?
Gib die IDs der zu entfernenden Tags in die CSV-Datei ein. Verwende Kommas, um die IDs wie folgt zu trennen: +
id1,id2,id3…​

Die Tag-IDs findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

*_Hinweis_*: Die Tags selbst werden nicht gelöscht. Die Tags werden lediglich von der Variante entfernt.


|Tag-Verknüpfung löschen (ID)
|
|
|Deprecated. Dieses Feld wird zukünftig entfernt. Verwende stattdessen das Zuordnungsfeld *Tag-Verknüpfung löschen (ID, kommasepariert)*.
|====

[#2420]
=== Vererbung

Für den Import von Vererbungen stehen die in <<tabelle-zuordnungsfelder-vererbung>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-vererbung]]
.Felder für Import von Vererbungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Kategorie
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Verknüpfte Kategorien>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Märkte
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Märkte>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Mandant
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#_verfügbarkeit_für_mandanten_einstellen, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Mandant (Shop)>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Verkaufspreis
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#240, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verkaufspreise>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Lieferant
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Lager
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Verfügbarkeit
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#240, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Eigenschaften
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#4800, Tab: ID einer Variante » Tab: Eigenschaften>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Tags
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert
|====

[#2420a]
=== Inhalt

Für den Import des Inhalts stehen die in <<tabelle-zuordnungsfelder-inhalt>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-inhalt]]
.Felder für Import des Inhalts
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Inhalt Einheit
|Nummerisch
(interne ID)
|
|Entspricht der _Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Inhalt>>

Gib die ID der Einheit in die CSV-Datei ein.
Die Einheit-IDs findest du im Menü *Einrichtung » Artikel » Einheiten*.

*_Hinweis_*: Verwende dieses Zuordnungsfeld in Kombination mit *Inhalt Menge*.

//IDs siehe <<basics/interne-IDs#40, IDs der Einheiten>> +
//Alternativ *Inhalt Maßeinheit (ISO)* übergeben

|Inhalt Menge
|Nummerisch
|
|Entspricht dem _Eingabefeld_ unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Inhalt>>

Gib den numerischen Inhalt in die CSV-Datei ein.

*_Hinweis_*: Verwende dieses Zuordnungsfeld in Kombination mit *Inhalt Einheit* oder *Inhalt Maßeinheit (ISO)*.

|Inhalt Maßeinheit (ISO)
|Alphanummerischer ISO-Code
|
|Entspricht der _Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Inhalt>>

Gib den ISO-Code für die Einheit in die CSV-Datei ein.
Die ISO-Codes findest du im Menü *Einrichtung » Artikel » Einheiten*.

*_Hinweis_*: Verwende dieses Zuordnungsfeld in Kombination mit *Inhalt Menge*.

|====

[#2430]
=== ##ASIN/ePID##

Für den Import von ASIN/ePID stehen die in <<tabelle-zuordnungsfelder-ASIN-ePID>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-ASIN-ePID]]
.Felder für Import von ASIN/ePID
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Land
|Nummerisch (interne ID)
|
|IDs siehe <<basics/interne-IDs#20, Länder-IDs>>

|Typ
|ASIN; ePID
|
|

|Position
|Nummerisch
|
|

|Wert
|Alphanummerisch
|
|

|Löschen (IDs, kommasepariert)
|Nummerisch (interne ID)
|
|ASIN-IDs oder ePID-IDs im Format +
ASIN-ID1,ASIN-ID2,ASIN-ID3 etc.
|====

[#2440]
=== Lager

Für den Import von Lagerdaten stehen die in <<tabelle-zuordnungsfelder-lager>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Lager.

[[tabelle-zuordnungsfelder-lager]]
.Felder für Import von Lagerdaten
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|##Zone##
|Nummerisch
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Zone>>

//wo kann man die Zone-ID nachschlagen? Also in welchem Menü?
Die Zuordnung erfolgt anhand der Zone-ID im Menü Einrichtung » Waren » Lager » Lager öffnen » Einstellungen.

|Lagerorttyp
|none +
small +
medium +
large +
europallet
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Lagerorttyp>>

* none = Kein Typ ausgewählt
* small = Klein
* medium = Mittel
* large = Groß
* europallet = Europalette

|Meldebestand
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Meldebestand>>

|Maximalbestand
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Maximalbestand>>

|Lagerreichweite (in Tagen)
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Lagerreichweite>>

|Lagerort
|Nummerisch (interne ID)
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Lagerortvorschlag>>

Die Zuordnung erfolgt anhand der Lagerort-ID im Menü *Einrichtung » Waren » Lager » Lager öffnen » Lagerorte*.

|Bestandspuffer
|Nummerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Bestandspuffer>>

|Charge (ja/nein)
|0 +
1
|
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Charge>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Mindeshaltbarkeitsdatum (ja/nein)
|0 +
1
|
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: MHD>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Lagerverknüpfung löschen
|0 +
1
|
a|Möchtest du das Lager von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob das Lager gelöscht werden soll.

* 0 = Nein
* 1 = Ja

*_Hinweis_*: Das Lager selbst wird nicht gelöscht. Das Lager wird lediglich von der Variante entfernt.
|====

[#2450]
=== ##Lieferant##

Für den Import von Lieferantendaten stehen die in <<tabelle-zuordnungsfelder-lieferant>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-lieferant]]
.Felder für Import von Lieferantendaten
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Lieferantenverknüpfungs-ID
|Nummerisch
|
|ID der Verknüpfung zwischen Variante und Lieferant. +
Diese ID wird automatisch von plentymarkets erzeugt. Die ID ist _nicht_ im plentymarkets Backend sichtbar. Sondern wird die ID lediglich im Hintergrund gespeichert. Möchtest du die ID trotzdem sehen, musst du diese Information zunächst aus deinem plentymarkets-System exportieren. Verwende dazu das Exportformat <<daten/daten-exportieren/FormatDesigner#385, VariationSupplier in FormatDesigner>>. +
Das Zuordnungsfeld *Lieferantenverknüpfungs-ID* ist <<daten/daten-importieren/sync-typen/elasticSync-artikel#1930, je nach Anwendungsfall>> eine Pflichtangabe. Beispielsweise wird dieses Feld benötigt, um Lieferanten direkt beim Artikelimport anzulegen.

|##EK in Systemwährung##
|0 = Nein +
1 = Ja
//0 und 1 macht kein Sinn dafür
|
|

//evtl das hier?
//|EK
//|Nummerisch
//|
//|Einkaufspreis der Variante

|Mindestabnahme
|Nummerisch
|
|

|Lieferanten-Artikel-Nr.
|Alphanummerisch
|
|Externe Artikelnummer, die der Lieferant der Variante zuweist

|Letzte Preisanfrage
|Datum
|
|Datum der letzten Preisverhandlungen

|Lieferzeit in Tagen
|Nummerisch
|
|

|Rabatt
|Nummerisch
|
|Prozent

|Rabattfähigkeit
|0 = Nein +
1 = Ja
|
|

|Verpackungseinheit
|Nummerisch
|
|

|EK in Bestellwährung
|Kommazahl
|
|

|Lieferanten-Artikel-Bezeichnung
|Alphanummerisch
|
|

|Lieferanten-ID
|Nummerisch
|
|Kontakt-ID des Lieferanten, siehe *CRM » Kontakte* +
*_Tipp:_* Filter *Typ* auf *Lieferant* stellen, um nur Kontakte des Typs *Lieferant* anzuzeigen.

|Lieferantenname
|Alphanummerisch
|
|Name des Lieferanten, siehe *CRM » Kontakte* +
*_Tipp:_* Filter *Typ* auf *Lieferant* stellen, um nur Kontakte des Typs *Lieferant* anzuzeigen.

|Lieferantenverknüpfung löschen
|0 = Nein +
1 = Ja
|
|Hebt die Verknüpfung zwischen Lieferant und Variante auf.
|====

[#2460]
=== SKU

Für den Import von SKUs stehen die in <<tabelle-zuordnungsfelder-SKU>> Felder Abgleichfelder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-SKU]]
.Felder für Import von SKUs
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Marktplatz-ID
|Nummerisch
|
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: Herkunft>>

Die Zuordnung erfolgt anhand der Auftragsherkunft-ID im Menü *Einrichtung » Aufträge » Auftragsherkunft*.

|Account-ID
|Nummerisch
|
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: Konto>>

Die Zuordnung erfolgt anhand der Marktplatzkonto-ID. +
Amazon siehe *Einrichtung » Märkte » Amazon » Einstellungen* +
eBay siehe *Einrichtung » Märkte » eBay » Einstellungen » Kontoeinstellungen*

|SKU
|Alphanummerisch
|
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: SKU>>

Gib die SKU in deine CSV-Datei ein.

|Parent-SKU
|Alphanummerisch
|
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: Parent-SKU>>

Gib die Parent-SKU in deine CSV-Datei ein.

|SKU löschen
|0 +
1
|
a|Möchtest du die SKU von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die SKU gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====

[#3000]
=== ##Zusätzliche SKU##

Für den Import von zusätzlichen SKUs stehen die in <<tabelle-zuordnungsfelder-zusaetzliche-SKU>> Felder Abgleichfelder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-zusaetzliche-SKU]]
.Felder für Import von zusätzlichen SKUs
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID
|Nummerisch
|
|Eine existierende SKU ID

|Marktplatz-ID
|Nummerisch
|
|ID der Auftragsherkunft, IDs siehe <<basics/interne-IDs#90, IDs der Auftragsherkünfte>>

|Account-ID
|Nummerisch
|
|ID des Marktplatzkontos +
Amazon siehe *Einrichtung » Märkte » Amazon » Einstellungen* +
eBay siehe *Einrichtung » Märkte » eBay » Konten*

|SKU
|Alphanummerisch
|
|

|Existierende SKU
|##Nummerisch?##
|
|Der aktuelle Wert einer SKU
//was für ein Wert?

|Abgleich anhand von ID oder existierender SKU
|0 = Nein +
1 = Ja
|
|

//|Parent-SKU
//|Alphanummerisch
//|
//|

|Zusätzliche SKU löschen
|0 = Nein +
1 = Ja
|
|
|====

[#2470]
=== ##Paket##

Für den Import von Artikelpaketen stehen die in <<tabelle-zuordnungsfelder-paket>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-paket]]
.Felder für Import von Paketen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Paketbestandteile
|Alphanummerisch
|
|Fügt Bestandteile zu einem Paket hinzu. Varianten-ID und Menge des Paketbestandteils eingeben. Varianten-ID und Menge durch Doppelpunkt trennen. Mehrere Bestandteile durch Semikolon trennen. Beispiel: +
Varianten-ID:Menge;Varianten-ID:Menge;etc.

|Paketbestandteile (Variantennummer)
|Alphanummerisch
|
|Fügt Bestandteile zu einem Paket hinzu. Variantennummer und Menge des Paketbestandteils eingeben. Variantennummer und Menge durch Doppelpunkt trennen. Mehrere Bestandteile durch Semikolon trennen. Beispiel: +
Variantennummer:Menge;Variantennummer:Menge;etc.

|Paketbestandteile löschen
|Alphanummerisch
|
|Löscht Bestandteile aus einem Paket raus. Varianten-ID des zu löschenden Paketbestandteils eingeben. Mehrere Varianten-IDs durch Semikolon trennen. Beispiel: +
Varianten-ID;Varianten-ID

|Paket löschen
|0 = Nein +
1 = Ja
|
|Löscht _alle_ Bestandteile aus einem Paket raus. Die Varianten-IDs der einzelne Bestandteile müssen nicht angegeben werden, da alle Paketbestandteile gleichzeitig gelöscht werden.
|====

[#sync-seriennummer]
=== ##Seriennummer##

Für den Import von Seriennummern stehen die in <<tabelle-zuordnungsfelder-seriennummer>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-zuordnungsfelder-seriennummer]]
.Felder für Import von Seriennummern
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID
|Nummerisch
|
|ID der Seriennummer

|Nummer
|Nummerisch
|
|Seriennummer

|Seriennummer löschen
|0 = Nein +
1 = Ja
|
|
|====


[#1930]
== Pflichtwerte für Artikel-Sync-Aktionen

<<tabelle-Aktionen-Artikel-Sync>> listet mögliche Aktionen für Syncs des Typs Artikel und erläutert die Werte, die zum Ausführen dieser Aktionen unbedingt angegeben werden müssen.

[[tabelle-Aktionen-Artikel-Sync]]
.Aktionen für Artikel-Sync
|====
|Aktion |Erforderliche Werte

2+|*Artikelbeschreibung*

|Artikelbeschreibung aktualisieren
a|
* Name

2+|*Versandprofil*

|Versandprofil aktualisieren
a|
* Versandprofil-ID

2+|*Varianten-Tags*

|Alle Tag-Verknüpfungen lösen
a|
* Alle verknüpften Tags löschen = 1

|Tag verknüpfen
a|Ein Tag:

* Tag-ID +
oder
* Tag-Name +

Mehrere Tags: +

* Tag-Namen (kommasepariert)

2+|*Varianten*

|Variante erstellen
a|
* ID der Standardkategorie +
oder
* Name der Standardkategorie

|Variante zu Artikel hinzufügen
a|
* Inhalt Menge
* Inhalt Einheit +
    oder
* Inhalt Menge
* Inhalt Maßeinheit (ISO)

und

* Artikel-ID +
    oder
* Nummer der Hauptvariante

Bei Varianten mit Attributen außerdem:

* Attributauswahlkombination +
    oder
* Attribute (Name oder ID)
* Wert (Name oder ID)

|Inhalt aktualisieren
a|
* Inhalt Menge
* Inhalt Einheit +
oder
* Inhalt Menge
* Inhalt Maßeinheit (ISO)

2+|*Barcodes*

|Barcode ändern
a|
* Code über Barcode-Zuordnung

2+|*Kategorien*

|Kategorie verknüpfen
a|
* ID der Kategorie +
oder
* Name der Kategorie

*_Tipp:_* Für weitere Kategorien zusätzliche Mappings erstellen.

|Verknüpfung aktualisieren
a|
* ID der Kategorie +
oder
* Name der Kategorie

2+|*Variantenpreise*

|Preis ändern
a|
* Preis über Verkaufspreiszuordnung

2+|*Standardkategorien*

|Standardkategorie verknüpfen
a|
* ID der Kategorie +
oder
* Name der Kategorie

|Standardkategorie aktualisieren
a|
* ID der Kategorie +
oder
* Name der Kategorie

2+|*Bestand*

|Bestand aktualisieren
a|
* Lager
* Menge
* Lagerort

2+|*Artikel-Bilder*

|Vor dem Hochladen alle Bilder löschen
a|
* Bilder löschen = 1

|Bilder speichern
a|
* Multi-URL +
oder
* URL +
oder
* Dateiname
* Base64 Data

|Bilder aktualisieren
a|
* ID des Bildes

|Bild mit Variante verknüpfen
a|
* Multi-URL +
oder
* URL

2+|*Merkmale*

|Merkmale speichern
a|
* Merkmalkombination +
oder
* Interner Name
* Sprache
* Wert +
oder
* ID
* Sprache
* Wert

|Merkmale aktualisieren
a|
* Merkmalkombination +
oder
* Interner Name
* Sprache
* Wert +
oder
* ID
* Sprache
* Wert

2+|*Eigenschaften*

|Eigenschaft verknüpfen
a|
* ID

* Sprache

* Wert

2+|*Lieferant*

|Lieferant verknüpfen
a|
* EK
* Lieferantenverknüpfungs-ID (für neue Verknüpfungen leer lassen)

und

* Lieferanten-ID +
    oder
* Lieferanten-Name

|Lieferant aktualisieren
a|
* EK
* Lieferantenverknüpfungs-ID

und

* Lieferanten-ID +
    oder
* Lieferanten-Name

2+|*SKU*

|SKU hinzufügen
a|
* Marktplatz-ID
* SKU

Bei eBay/Amazon außerdem:

* Account-ID

|SKU aktualisieren
a|
* Marktplatz-ID
* SKU

Bei eBay/Amazon außerdem:

* Account-ID

2+|*Paket*

|Paket erstellen
a|
* Paketbestandteile

|Paketbestandteile löschen
a|
* Paketbestandteile löschen

|Paket löschen
a|
* Paket löschen = 1

|====
