= Artikel
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Artikel, Artikelanlage
:position: 10
:url: daten/daten-importieren/sync-typen/elasticSync-artikel
:id: QUGDW1A
:author: none

Diese Seite erläutert die Abgleich- und Zuordnungsfelder, die dir beim Importieren von Artikel- und Variantendaten zur Verfügung stehen. Diese Seite dient lediglich als Referenz und setzt voraus, dass du bereits Grundkenntnisse über das <<daten/daten-importieren/ElasticSync#, ElasticSync-Tool>> hast.

[IMPORTANT]
.Voraussetzungen
====
Um Artikeldaten per ElasticSync zu importieren, müssen die folgenden Datensätze in plentymarkets vorhanden sein:

* Kategorien (Menü *Artikel » Kategorien*)
* Verkaufspreise (Menü *Einrichtung » Artikel » Verkaufspreise*)

Um Variantendaten mit Attributen per ElasticSync zu importieren, müssen die folgenden Datensätze in plentymarkets vorhanden sein:

* Attribute und Attributwerte (Menü *Einrichtung » Artikel » Attribute*)
====

[TIP]
.Praxisbeispiel: Neue Artikel importieren
====
Stell dir mal vor, du bist ganz neu bei plentymarkets und möchtest alle deine Artikel und Varianten auf einmal importieren. Wie geht so etwas? Wirf einen Blick auf <<daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-variantenanlage#, dieses praktische Beispiel>>, welches dich Schritt für Schritt durch den Prozess führt.
====

[#1910]
== Felder für den Artikelabgleich

In <<table-matching-fields-item>> werden Felder erläutert, die für den Abgleich von Artikeldaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-matching-fields-item]]
.Abgleichfelder für Artikelimport
[cols="1,3"]
|====
|Abgleichfeld |Erläuterung

|Varianten-ID
|

|Variantennr.
|

|Externe Varianten-ID
|

|Barcode
|Aus der zweiten Dropdown-Liste den Barcode-Typ wählen.

|Artikel-ID
|Bei Varianten mit Attributen dieses Feld nur in Kombination mit Attributauswahlkombination nutzen.


|Attributauswahlkombination
|Bei Varianten mit Attributen dieses Feld nur in Kombination mit Artikel-ID nutzen.
Aus der zweiten Dropdown-Liste das Format wählen, in dem die Daten in der Datei vorliegen.

|Lieferanten-Artikel-Nr.
|

|====

[#1920]
== Felder für die Artikelzuordnung

//rewrite. Something along the lines of: In den folgenden Kapitel werden Felder erläutert, die für die Zuordnung von Artikel- und Variantendaten zur Verfügung stehen.
//since there are many different fields, the explainations have been divided into sub-chapters.
##In diesem Kapitel werden Felder erläutert##, die für die Zuordnung von Artikeldaten zur Verfügung stehen.

[TIP]
.Kein Zuordnungsfeld? Standardwert greift!
====
Wenn du eine bestimmte Information nicht in deine CSV-Datei aufnimmst, d.h. wenn du ein bestimmtes Zuordnungsfeld _nicht verwendest_, dann erhält dein Artikel bzw. deine Variante den Standardwert.
====

[#2260]
=== Artikel
//evtl Tab Global und aaaa und bbbb anstatt die obere Tab-Leiste

In <<table-mapping-fields-items>> werden Felder erläutert, die für die Zuordnung von _Artikeldaten_ zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also der ##<<artikel/einleitung/struktur#200, oberen Tab-Leiste>>## innerhalb eines Artikeldatensatzes.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Artikeldatensatz nach dem Import öffnest, siehst du, dass die Einstellungen in der ##oberen Tab-Leiste## wie folgt konfiguriert wurden.

[[table-mapping-fields-items]]
.Felder für Artikelimport
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Warentyp
|0 +
1 +
2 +
3
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Typ>>

* 0 = Lagerware
* 1 = Produktionsware
* 2 = Colli
* 3 = Bestellware

|Shop-Aktion
|0 +
1 +
2 +
3
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Webshop » Option: Shop-Aktion>>

* 0 = Keine
* 1 = Sonderangebot
* 2 = Neuheit
* 3 = Top-Artikel

|Hersteller-ID
|Numerisch (interne ID)
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Hersteller>>

Die Zuordnung erfolgt über die Hersteller-ID im Menü *Einrichtung » Artikel » Hersteller*.

|Herstellungsland
|Numerisch (interne ID); +
0 = unbekannt
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Herstellungsland>>

Die Zuordnung erfolgt über die <<basics/interne-IDs#20, Liste der Länder-IDs>>.

|Zolltarifnummer
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Zolltarifnummer>>

|Erlöskonto
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Erlöskonto>>

|Aktionsgutschein
|0 +
1 +
2
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Aktionsgutschein/POS-Rabatt>>

* 0 = Möglich
* 1 = Verboten
* 2 = Nur mit Gutschein kaufbar

|Zustand
|0 +
1 +
2 +
3 +
4
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Zustand>>

* 0 = Neu
* 1 = Gebraucht
* 2 = Neu und originalverpackt
* 3 = Neu mit Etikett
* 4 = B-Ware

|Zustand API
|0 +
1 +
2 +
3 +
4 +
5
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Zustand API>>

* 0 = Neu
* 1 = Gebraucht wie neu
* 2 = Gebraucht sehr gut
* 3 = Gebraucht gut
* 4 = Gebraucht annehmbar
* 5 = B-Ware

|Abonnement (Ja/Nein)
|0 +
1
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Abonnement>>

* 0 = Nein
* 1 = Ja

|Seriennummer (Ja/Nein)
|0 +
1
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Seriennummer>>

* 0 = Nein
* 1 = Ja

|Versandpaket (Ja/Nein)
|0 +
1
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Versandpaket>>

* 0 = Nein
* 1 = Ja

|Amazon-Abwicklung (FBA)
|0 +
1 +
2 +
3 +
-1
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Amazon » Option: FBA-Abwicklung>>

* 0 = Nicht verwenden
* 1 = AMAZON_EU
* 2 = AMAZON_FE
* 3 = AMAZON_NA
* -1 = FBA und SellerCentral

|Versand durch Amazon (FBA)
|0 +
1
|
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Amazon » Option: Amazon FBA>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Amazon-Produkttyp
|Numerisch
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Amazon » Option: Produkttyp>>

Die Zuordnung erfolgt über die <<basics/interne-IDs#130, Wertetabelle amazon_product_type>>.

|##Amazon-FEDAS##
//0 und 1 macht dafür gar kein Sinn
|0 = Nein +
1 = Ja
|
|FEDAS-Warengruppenschlüssel

|Listing-Vorlage
|Numerisch (interne ID)
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Listing-Voreinstellungen » Option: Listing-Vorlage>>

Die Zuordnung erfolgt über die Listing-Vorlage-ID im Menü *Listings » Listings*.

|Listing Kategorie 1; +
Listing Kategorie 2
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Listing-Voreinstellungen » Option: Kategorie 1>>

|Listing Shop-Kategorie 1; +
Listing Shop-Kategorie 2
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Listing-Voreinstellungen » Option: Kategorie 1>>


|Rakuten.de-Kategorien
|Numerisch (interne ID)
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Kategorieverknüpfung » Option: Rakuten.de>>

|Markierung 1; +
Markierung 2
|Numerisch (interne ID)
|
|Entspricht der <<artikel/einstellungen/markierungen#, Markierung des Artikels>>.

Die Zuordnung erfolgt über die ID der Markierung im Menü *Einrichtung » Artikel » Makierungen » Tab: Markierung 1 bzw. Markierung 2*

|Altersfreigabe
|0 +
3 +
6 +
12 +
16 +
18 +
50 +
88 +
99
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Altersfreigabe>>

* 0 = Keine verfügbar
* 3 = FSK 3
* 6 = FSK 6
* 12 = FSK 12
* 16 = FSK 16
* 18 = FSK 18
* 50 = Nicht gekennzeichnet
* 88 = Nicht erforderlich
* 99 = Noch nicht bekannt

|Artikelbewertung
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Webshop » Option: Artikelbewertung>>

|Feld 1; +
Feld 2; +
Feld 3; +
... +
Feld 20
|AlphaNumerisch
|
|Entspricht den Freitextfeldern 1 bis 20 unter: +
<<artikel/artikel-verwalten#70, Tab: Felder>>

|Max. Artikelbestellmenge
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Max. Bestellmenge>>

|##Typ##
//geht auch set?
|standard +
multipack +
set
|standard
a|_Beim Erstellen eines neuen Artikels_, entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#20, Tab zum Erstellen eines neuen Artikels » Bereich: Artikeldaten » Option: Typ>>

* standard = Artikel des Typs *Standard*
* multipack = Artikel des Typs *Multipack*
* set = Artikel des Typs *Set*


|Herstellername
|AlphaNumerisch
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Hersteller>>

Die Zuordnung erfolgt über den Herstellernamen. Wenn der Herstellerdatensatz nicht bereits im System vorhanden ist, wird ein neuer Herstellerdatensatz angelegt.

//wo findet man Artikelvorlage?
//|Artikelvorlage
//|Numerisch
//|
//|ID der Kategorie der <<artikel/artikel-verwalten#720, Artikelvorlage>> +
//*_Hinweis:_* Artikelvorlagen gibt es nur im alten Webdesign Callisto.

|Artikel löschen
|0 +
1
|
a|Möchtest du einige Artikel löschen und andere aktualisieren? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob der Artikel gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====

[#3000]
=== Artikelsets

In <<table-mapping-fields-item-sets>> werden Felder erläutert, die für die Zuordnung von Artikelsets zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/anwendungsfaelle/multipacks-pakete-sets#3500, Bestandteile zu einem Setartikel hinzuzufügen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Setartikel nach dem Import öffnest, siehst du, dass die Einstellungen im Tab *Set* wie folgt konfiguriert wurden.

//Für den Import von Artikelsets stehen die in <<table-mapping-fields-item-sets>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-item-sets]]
.Felder für Import von Artikelsets
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Bestandteile hinzufügen (IDs, kommasepariert)
|AlphaNumerisch
|- k.A. -
|IDs und Anzahl der Artikel, die zum Set hinzugefügt werden +
Format: *artikelID:menge,artikelID:menge*

|Bestandteile entfernen (IDs, kommasepariert)
|AlphaNumerisch
|- k.A. -
|IDs der Artikel, die aus dem Set entfernt werden

|Rabatt
|Dezimalzahl
|- k.A. -
|Rabatt auf den Gesamtpreis des Sets in %
|====

[#2310]
=== Cross-Selling

In <<table-mapping-fields-cross-selling>> werden Felder erläutert, die für die Zuordnung von Cross-Selling-Artikeln zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/webshop/cross-selling#, zusätzliche Verkäufe mittels Cross-Selling zu erzielen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Artikel nach dem Import öffnest, siehst du, dass die Cross-Selling-Verbindungen wie folgt konfiguriert wurden.

//Für den Import von Cross-Selling-Verknüpfungen stehen die in <<table-mapping-fields-cross-selling>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-cross-selling]]
.Felder für Import von Cross-Selling-Verknüpfungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Alle Cross-Selling-Verknüpfungen löschen
|0 +
1
|
a|Möchtest du <<artikel/webshop/cross-selling#600, alle Cross-Selling-Verbindungen aus dem Artikeldatensatz löschen>>? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Cross-Selling-Verbindungen gelöscht werden sollen.

* 0 = Nein
* 1 = Ja

|Cross-Selling-Verknüpfungen hinzufügen
|AlphaNumerisch
|
a|Möchtest du <<artikel/webshop/cross-selling#300, neue Cross-Selling-Verbindungen erstellen>>? Gib Informationen über die Verbindung in diesem Format ein:

*Artikel-ID:Beziehungstyp;Artikel-ID:Beziehungstyp;etc.*

Verfügbare Beziehungstypen:

* Accessory = Zubehör
* ReplacementPart = Ersatzteil
* Similar = Ähnlich
* Bundle = Artikelpaket

|Cross-Selling-Verknüpfungen löschen
|Numerisch
|
|Möchtest du <<artikel/webshop/cross-selling#600, einige der Cross-Selling-Verbindungen aus dem Artikeldatensatz löschen>>? Gib die zu löschende Cross-Selling-Verknüpfungen in diesem Format ein:

*Artikel-ID;Artikel-ID;etc.*
|====


[#2270]
=== Artikelbeschreibung

In <<table-mapping-fields-item-description>> werden Felder erläutert, die für die Zuordnung von Artikelbeschreibungen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also den <<artikel/artikel-verwalten#50, Einstellungen im Artikeltext-Tab>>.

Gib die Texte in deine CSV-Datei ein. Pro Sprache wird eine Zuordnung erstellt.
Wenn du den Artikel nach dem Import öffnest, siehst du, dass diese Texte für den Artikel gespeichert wurden.

//Für den Import der Artikelbeschreibungen stehen die in <<table-mapping-fields-item-description>> aufgelisteten Felder zur Verfügung. Pro Sprache wird eine Zuordnung erstellt. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-item-description]]
.Felder für Import von Artikelbeschreibungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Name; +
Name 2; +
Name 3
|AlphaNumerisch
|
|Gib einen Namen für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Name 1, 2, 3>>

|Vorschautext
|AlphaNumerisch
|
|Gib einen Vorschautext für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Vorschautext>>

|Meta-Beschreibung
|AlphaNumerisch
|
|Gib eine Meta-Beschreibung für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Meta-Beschreibung>>

|Artikeltext
|AlphaNumerisch
|
|Gib einen Artikeltext für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Artikeltext>>

|Technische Daten
|AlphaNumerisch
|
|Gib technische Daten für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Technische Daten>>

|URL-Pfad
|Link
|
|Gib einen URL-Pfad für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: URL-Pfad>>

|Meta-Keywords
|AlphaNumerisch
|
|Gib Meta-Keywords für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Meta-Keywords>>
|====

[#2280]
=== Versandprofil

In <<table-mapping-fields-shipping-profile>> werden Felder erläutert, die für die Zuordnung von Versandprofilen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#40, Versandprofile mit Artikeln zu verknüpfen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Artikel nach dem Import öffnest, siehst du, dass die Versandprofile wie folgt verknüpft wurden.

//Für den Import von Versandprofilen stehen die in <<table-mapping-fields-shipping-profile>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-shipping-profile]]
.Abgleichfelder für Versandprofile
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Versandprofil-ID
|Numerisch
|
|Gib die ID des Versandprofils ein, das mit dem Artikel verknüpft werden soll.

Versandprofil-IDs können im Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versandprofile* nachgeschlagen werden.

|Versandprofile (kommasepariert)
|Numerisch
|
|Möchtest du mehr als nur einem Versandprofil verknüpfen? Gib die IDs aller Versandprofile ein, die mit dem Artikel verknüpft werden sollen.
Gib die IDs in diesem Format ein:

*Profil-ID1,Profil-ID2,...*

Versandprofil-IDs können im Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versandprofile* nachgeschlagen werden.

|Versandprofilverknüpfungen löschen (Profil-IDs, kommasepariert)
|AlphaNumerisch
|
|Möchtest du einige Verknüpfungen löschen? Gib die IDs aller Versandprofile ein, die _nicht mehr_ mit dem Artikel verknüpft werden sollen.
Gib die IDs in diesem Format ein:

*Profil-ID1,Profil-ID2,...*

Versandprofil-IDs können im Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versandprofile* nachgeschlagen werden.
|====


[#2300]
=== Varianten
//evtl Tab Einstellungen einer Variante anstatt die untere Tab-Leiste

In <<table-mapping-fields-variations>> werden Felder erläutert, die für die Zuordnung von Variantendaten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also der ##<<artikel/einleitung/struktur#200, unteren Tab-Leiste>>## innerhalb eines Artikeldatensatzes.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen in der ##unteren Tab-Leiste## wie folgt konfiguriert wurden.

//Für den Import von Variantendaten stehen die in <<table-mapping-fields-variations>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-variations]]
.Abgleichfelder für Varianten
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|##ID##
|Numerisch
|
|Entspricht der ID der Variante.

|##Artikel-ID##
|Numerisch
|
|Entspricht der ID des Artikels.

|Position
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Position>>

|Aktiv
|0 +
1
|
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Aktiv>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Variantennr.
|AlphaNumerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Variantennr.>>

|Modell
|AlphaNumerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Modell>>

|Externe Varianten-ID
|AlphaNumerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Ext. Varianten-ID>>

|Verfügbarkeit
|Numerisch (interne ID)
|
|Entspricht den Verfügbarkeitssymbolen 1 bis 10 unter: +
<<artikel/artikel-verwalten#190, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Verfügbarkeit>>

|EK netto
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: EK netto>>

|GLD EK netto
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: GLD EK netto>>

|##Preiskalkulation##
|Numerisch (interne ID)
|
|

|WB-Beschränkung
|0 +
1 +
2
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#190, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Beschränkung>>

* 0 = Keine
* 1 = Auf Netto-WB
* 2 = Keinen WB für diese Variante führen

|Sichtbarkeit Mandant: Automatisch sichtbar, wenn Netto-WB positiv; +
Sichtbarkeit Mandant: Automatisch unsichtbar, wenn kein Netto-WB
|0 +
1
|
a|Entspricht der gleichnamigen Checkbox unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Verfügbarkeit Webshop: Automatisch verfügbar, wenn Netto-WB positiv; +
Verfügbarkeit Webshop: Automatisch nicht verfügbar, wenn kein Netto-WB
|0 +
1
|
a|Entspricht der gleichnamigen Checkbox unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

* 0 = Kein Häkchen
* 1 = Häkchen

//|Sichtbarkeit Artikelauflistung: Immer unsichtbar
//|0 = Nein +
//1 = Ja
//|
//|Entspricht die gleiche <<artikel/artikel-verwalten#230, Verfügbarkeitseinstellung>> in der Artikelübersicht.

|Sichtbarkeit Artikelauflistung: Automatisch sichtbar, wenn Netto-WB positiv; +
Sichtbarkeit Artikelauflistung: Automatisch unsichtbar, wenn kein Netto-WB
|0 = Nein +
1 = Ja
|
a|Entspricht der gleichnamigen Checkbox unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Hauptlager
|Numerisch (interne ID)
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#190, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Hauptlager>>

Die Zuordnung erfolgt anhand der Lager-ID im Menü *Einrichtung » Waren » Lager » Lager öffnen » Einstellungen*.

|Max. Bestellmenge
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Max. Bestellmenge>>

|Min.-Bestellmenge
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Min.-Bestellmenge>>

|Intervallbestellmenge
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Intervallbestellmenge>>

|Verfügbar bis
|Datum +
(DD.MM.YYYY)
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Verfügbar bis>>

|Erscheinungsdatum
|Datum +
(DD.MM.YYYY)
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Erscheinungsdatum>>

|Name
|AlphaNumerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Variantenname>>

|Gewicht brutto g; +
Gewicht netto g
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Gewicht brutto bzw. Gewicht netto>>

Achte darauf, dass du das _Gewicht in Gramm_ anstatt in Kilogramm angibst.

|Breite mm; +
Länge mm; +
Höhe mm
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Länge/Breite/Höhe>>

Achte darauf, dass du die _Maße in Millimetern_ angibst.

|Portoaufschlag 1; +
Portoaufschlag 2
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#290, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Portoaufschlag 1 bzw. Portoaufschlag 2>>

|##VPE##
|Numerisch
|
|Verpackungseinheit; Standard = 1

|Anzahl der Packstücke
|0 +
1 +
2 +
... +
20
|
|Entspricht der _ersten Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#290, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Packstücke>>

Verwende dieses Zuordnungsfeld zusammen mit *Einheit der Packstücke*.

|Einheit der Packstücke
|0 +
1 +
2 +
... +
39
|
a|Entspricht der _zweiten Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#290, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Packstücke>>

Verwende dieses Zuordnungsfeld zusammen mit *Anzahl der Packstücke*.

* 0 = unverpackt
* 1 = Ballen
* 2 = Behälter
* 3 = Bund
* 4 = Rollpalette
* 5 = Colli
* 6 = Container
* 7 = Eimer
* 8 = Fass
* 9 = Flaschen
* 10 = Euro Pool Flachpalette
* 11 = Gestell
* 12 = Gasflasche
* 13 = Gitterboxpalette
* 14 = Hobbock
* 15 = Halbe Palette
* 16 = Lebensmittelpalette
* 17 = Holzuntersetzer
* 18 = IBC Container
* 19 = Kanne
* 20 = Korbflasche
* 21 = Kiste
* 22 = Kanister
* 23 = Kundenpalette
* 24 = Karton
* 25 = Kombinationsverpackung
* 26 = Pack
* 27 = Ring
* 28 = Rolle
* 29 = Sack
* 30 = Stück
* 31 = Tank
* 32 = Trommel
* 34 = Verschlag
* 35 = Viertelpalette
* 36 = sonstige Paletten
* 37 = Kasten
* 38 = Einwegpalette
* 39 = Folientüte

|Transportkosten netto
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Transport netto>>

|Lagerkosten netto
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Lager netto>>

|Zoll
|Numerisch
(Prozentwert)
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Zoll>>

|Betriebskosten
|Numerisch
(Prozentwert)
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Betriebskosten>>

|##Umsatzsteuer##
|Numerisch
(Prozentwert)
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Umsatzsteuer>>

|##Paketart##
|bundle = Variante ist Paket +
bundle_item = Variante ist Paketbestandteil
|
|

|##Sichtbarkeit Artikelauflistung: Immer unsichtbar##
|0 = Nein +
1 = Ja
|
|

|Grundpreis anzeigen
|0 +
1
|
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Grundpreisanzeige>>

* 0 = Nein
* 1 = Ja

|Gewicht brutto aus Paketbestandteilen berechnen; +
Gewicht netto aus Paketbestandteilen berechnen; +
EK netto aus Paketbestandteilen berechnen; +
GLD EK netto aus Paketbestandteilen berechnen
|0 +
1
|
a|Entspricht den Checkboxen unter: +
<<artikel/artikel-verwalten#265, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Paket » Option: Automatisch aus Paketbestandteilen berechnen>>

* 0 = Nein
* 1 = Ja

*_Hinweis_*: Diese Checkboxen sind nur für <<artikel/anwendungsfaelle/multipacks-pakete-sets#, Artikelpakete>> sichtbar.

|Kommissionierung
|single_picking +
no_single_picking +
exclude_from_picklist
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Kommissionierung>>

* single_picking = Einzelkommissionierung möglich
* no_single_picking = Keine Einzelkommissionierung möglich
* exclude_from_picklist = Von Pickliste ausschließen

|Variante löschen
|0 +
1
|
a|Möchtest du einige Varianten löschen und andere aktualisieren? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Variante gelöscht werden soll.

* 0 = Nein
* 1 = Ja

|##Nummer der Hauptvariante##
//in wie fern unterscheidet sich das von der Variantennr. ganz oben?
|AlphaNumerisch
|
|

//|tagVariationId
//|Numerisch
//|
//|
|====

[#2320]
=== Barcodes

In <<table-mapping-fields-barcodes>> werden Felder erläutert, die für die Zuordnung von Barcode-Daten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/einstellungen/barcodes#300, Barcodes zu Artikeln zuordnen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Artikel nach dem Import öffnest, siehst du, dass die Barcodes wie folgt verknüpft wurden.

//Für den Import von Barcode-Daten stehen die in <<table-mapping-fields-barcodes>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Barcode-Typ.

[[table-mapping-fields-barcodes]]
.Felder für Import von Barcodes
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Code
|AlphaNumerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Barcode » Option: Code>>

Gib den alphanumerischen Code in deine CSV-Datei ein.
Wähle den Barcode-Typ aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Barcode löschen
|0 +
1
|
a|Willst du einen Barcode aus dem Artikeldatensatz löschen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob der Barcode gelöscht werden soll.

* 0 = Nein
* 1 = Ja

Wähle den zu löschenden Barcode-Typ aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.
|====

[#2330]
=== Variantenpreise

In <<table-mapping-fields-prices>> werden Felder erläutert, die für die Zuordnung von Preisen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#240, Preise für Varianten zu speichern>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Preise wie folgt hinterlegt wurden.

//Für den Import von Variantenpreisen stehen die in <<table-mapping-fields-prices>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Verkaufspreis.

[[table-mapping-fields-prices]]
.Felder für Import von Variantenpreisen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Preis
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verkaufspreise » Option: Preis>>

Gib den Geldbetrag in deine CSV-Datei ein.
Wähle den <<artikel/einstellungen/preise#, Verkaufspreis>> aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Preis löschen
|0 +
1
|
a|Willst du einen Preis aus dem Artikeldatensatz löschen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob der Preis gelöscht werden soll.

* 0 = Nein
* 1 = Ja

Wähle den zu löschenden <<artikel/einstellungen/preise#, Verkaufspreis>> aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Nettopreis (Ja/Nein)
|0 +
1
|
a|Ist der Geldbetrag als Nettopreis zu verstehen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob der Preis ein Nettopreis sein soll.

* 0 = Nein (es handelt sich um einen Bruttopreis)
* 1 = Ja (es handelt sich um einen Nettopreis)

Wähle den <<artikel/einstellungen/preise#, Verkaufspreis>> aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.
|====

[#2340]
=== ##Kategorien##

In <<table-mapping-fields-categories>> werden Felder erläutert, die für die Zuordnung von Kategoriedaten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/einstellungen/kategorien#1300, Artikel in Kategorien einzusortieren>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Kategorien wie folgt verknüpft wurden.

//Für den Import von Kategoriedaten stehen die in <<table-mapping-fields-categories>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-categories]]
.Felder für Import von Kategorien
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID der Kategorie
|Numerisch (interne ID)
|
|Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Verknüpfte Kategorien » Option: ID>>

Gib eine Kategorie-ID in die CSV-Datei ein. Die Kategorie-IDs findest du im Menü *Artikel » Kategorien* (ID erscheint beim Mouseover).

|Position
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Verknüpfte Kategorien » Option: Position>>

Gib die Positionsnummer in die CSV-Datei ein.

|##Ist Neckermann.de Hauptkategorie##
|0 = Nein +
1 = Ja
|
|

|Name der Kategorie
|AlphaNumerisch
|
|Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Verknüpfte Kategorien » Option: Kategorie>>

Gib den vollständigen Kategoriepfad, durch Semikolons getrennt, ein. Zum Beispiel: +
*Schuhe;Unisex*

|Alle Kategorieverknüpfungen löschen
|0 = Nein +
1 = Ja
|
|Löst alle verknüpften Kategorien.

|Kategorie-IDs (kommasepariert)
|AlphaNumerisch
|
|IDs der Kategorien, die mit der Variante verknüpft werden sollen.

|Kategorienamen (kommasepariert)
|AlphaNumerisch
|
|Name der Kategorien, die mit der Variante verknüpft werden sollen.

|Verknüpfungen löschen (Kategorie-IDs, kommasepariert)
|AlphaNumerisch
|
|IDs der Kategorien, die von der Variante gelöst werden sollen.

|Verknüpfungen löschen (Kategorienamen, kommasepariert)
|AlphaNumerisch
|
|Namen der Kategorien, die von der Variante gelöst werden sollen.

|Nicht gefundene Kategorien anlegen
|0 = Nein +
1 = Ja
|
|
|====

[#2345]
=== ##Standardkategorien##

Für den Import von Standardkategoriedaten stehen die in <<table-mapping-fields-default-categories>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-default-categories]]
.Felder für Import von Standardkategorien
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID der Kategorie
|Numerisch (interne ID)
|
|ID der Standardkategorie

|Name der Kategorie
|AlphaNumerisch
|
|Name der Standardkategorie

|Nicht gefundene Kategorien anlegen
|0 = Nein +
1 = Ja
|
|
|====

[#2350]
=== ##Bestand##

Für den Import von Bestandsdaten stehen die in <<table-mapping-fields-stock>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-stock]]
.Felder für Import von Bestand
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Lager
|Numerisch (interne ID)
|
|Kann nur in Kombination mit Menge und Lagerort übergeben werden.

|Menge
|Numerisch
|
|Kann nur in Kombination mit Lager und Lagerort übergeben werden.

|Lagerort
|Numerisch (interne ID)
|
|Kann nur in Kombination mit Lager und Menge übergeben werden.
|====

[#2360]
=== Mandant (Shop)

In <<table-mapping-fields-client>> wird das Feld erläutert, das für die Zuordnung der Mandantenverfügbarkeit verwendet wird.
Dieses Zuordnungsfeld entspricht also deine Möglichkeit, die <<artikel/artikel-verwalten#_verfügbarkeit_für_mandanten_einstellen, Variante für bestimmte Mandanten verfügbar zu machen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Mandantenverfügbarkeit wie folgt hinterlegt wurde.

//Für den Import der Mandantenverfügbarkeit stehen die in <<table-mapping-fields-client>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Mandant.

[[table-mapping-fields-client]]
.Abgleichfelder für Import von Mandantenverfügbarkeiten
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Aktiv
|0 +
1
|
a|Willst du die Variante für einen bestimmten Mandanten (Shop) verfügbar machen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob ein Häkchen (icon:check-square[role="blue"]) neben dem Mandanten gesetzt wird.

* 0 = Nein
* 1 = Ja

Wähle den zu aktivierenden Webshop aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.
|====

[#2370]
=== Märkte

In <<table-mapping-fields-markets>> wird das Feld erläutert, das für die Zuordnung der Marktplatzverfügbarkeiten verwendet wird.
Dieses Zuordnungsfeld entspricht also deinen Möglichkeiten, die <<artikel/artikel-verwalten#235, Variante für bestimmte Marktplätze verfügbar zu machen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Marktplatzverfügbarkeiten wie folgt hinterlegt wurden.

//Für den Import der Marktplatzverfügbarkeiten stehen die in <<table-mapping-fields-markets>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Marktplatz.

[[table-mapping-fields-markets]]
.Felder für Import von Marktplatzverfügbarkeiten
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Aktiv
|0 +
1
|
a|Willst du die Variante für bestimmte Märkte verfügbar machen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob der Markt in die folgende Liste aufgenommen wird: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Märkte>>

* 0 = Nein
* 1 = Ja

Wähle den zu aktivierenden Markt aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.
|====

[#2380]
=== ##Attribute##
////
In <<table-mapping-fields-attributes>> werden Felder erläutert, die für die Zuordnung von Attributverknüpfungen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#240, Preise für Varianten zu speichern>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Preise wie folgt hinterlegt wurden.

//Für den Import von Variantenpreisen stehen die in <<table-mapping-fields-prices>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Verkaufspreis.

////
Für den Import von Attributverknüpfungen stehen die in <<table-mapping-fields-attributes>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Format.

[[table-mapping-fields-attributes]]
.Felder für Import von Attributverknüpfungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Attributauswahlkombination
|AlphaNumerisch
|
|Kombination aus *Attributname (intern)* und *Attributwert (intern)* im Format +
*Attributname:Wertname;* oder *Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;* +
Import von mehr als zwei Attributverknüpfungen. +
*_Hinweis:_* Jede Attributauswahlkombination muss pro Variante einzigartig sein.

|Attribute ID
|Numerisch
|
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die IDs in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine weitere im Format *Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;* erstellen und die separaten Spalten zuordnen.

|Attribute Name
|AlphaNumerisch
|
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die Namen in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine weitere im Format *Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;* erstellen und die separaten Spalten zuordnen.

|Wert Name
|AlphaNumerisch
|
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die Namen in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine weitere im Format *Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;* erstellen und die separaten Spalten zuordnen.

|Wert ID
|Numerisch
|
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die IDs in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine weitere im Format *Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;* erstellen und die separaten Spalten zuordnen.

|Erstell nicht existierende Werte
|0 = Nein +
1 = Ja
|
|
|====

[#2390]
=== ##Artikelbilder##

Für den Import von Artikelbildern stehen die in <<table-mapping-fields-item-images>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-item-images]]
.Abgleichfelder für Import von Artikelbildern
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID des Bildes
|Numerisch (interne ID)
|
|

|Position
|Numerisch
|
|

|Dateiname
|AlphaNumerisch
|
|

|Base64 Data
|AlphaNumerisch
|
|

|URL
|AlphaNumerisch
|
|Link zum Artikelbild

|Multi-URL (kommasepariert)
|AlphaNumerisch
|
|Mehrere Bild-URLs im Format +
*image1url;positionImage1,* +
*image2url;positionImage2* +
Wenn keine Position übergeben wird, entspricht die Position der Reihenfolge der URLs.

|Bilder löschen
|0 = Nein +
1 = Ja
|
|1 löscht alle Bilder des Artikels. Bilder, die erhalten bleiben sollen, müssen als URL im Sync angegeben werden.

|Mit Variante verknüpfen
|0 = Nein +
1 = Ja
|
|1 verknüpft das Bild mit der Variante. +
0 löscht eine vorhandene Verknüpfung.

|Verfügbarkeit Mandant (Shop)
|Numerisch (interne ID)
|
|ID des Mandanten, siehe *Einrichtung » Mandant » Mandant öffnen » Einstellungen* +
*-1* aktiviert alle Mandanten

|Verfügbarkeit Herkünfte
|Numerisch (interne ID)
|
|ID der Auftragsherkunft, IDs siehe <<basics/interne-IDs#90, IDs der Auftragsherkünfte>> +
Mehrere Herkünfte können kommasepariert angegeben werden. +
*-1* aktiviert alle Herkünfte

|Verfügbarkeit Listings
|Numerisch (interne ID)
|
|*-1* aktiviert alle Listings

|Namen
|AlphaNumerisch
|
|Name des Artikelbilds im Format *Name:Sprache1,Name:Sprache2* +
Alternativtext des Artikelbilds im Format *Name:Sprache1:Alternativtext,Name:Sprache2:Alternativtext*

|Alternative Namen
|name1:sprache1,name2:sprache2
|
|

|Marktplatzattributverknüpfung (Attibutwert-ID)
|Numerisch (interne ID)
|
|ID des Attributwerts

|Alle Verfügbarkeiten entfernen
|0 = Nein +
1 = Ja
|
|
|====

[#2400]
=== ##Merkmale##

Für den Import von Merkmalverknüpfungen stehen die in <<table-mapping-fields-characteristics>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-characteristics]]
.Felder für Import von Merkmalverknüpfungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID
|Numerisch (interne ID)
|
|IDs siehe *Einrichtung » Artikel » Merkmale*

|Merkmalkombination
|AlphaNumerisch
|
|Kombination aus Backend-Name, Wert und Sprache im Format +
*Name1:Wert1:Sprache1;Name2:Wert2:Sprache2* etc.

|Interner Name
|AlphaNumerisch
|
|

|Wert
|AlphaNumerisch
|
|

|Auswahl-ID
|Numerisch (interne ID)
|
|Nur bei Merkmalen des Typs *Auswahl*. Verknüpft die Auswahlwerte eines Merkmals über die ID. +
Auswahl-IDs siehe *Einrichtung » Artikel » Merkmale » Merkmal öffnen*.

|Sprache
|Buchstaben
|
|Nur bei Merkmalen des Typs *Text* +
Codes siehe <<basics/interne-IDs#10, Sprachen>>

|Löschen (Ja/Nein)
|0 = Nein +
1 = Ja
|
|
|====

[#2410]
=== ##Eigenschaften##

Für den Import von Eigenschaftsverknüpfungen stehen die in <<table-mapping-fields-properties>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-properties]]
.Felder für Import von Eigenschaftsverknüpfungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID
|Numerisch (interne ID)
|
|IDs siehe *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*

|Sprache
|Buchstaben
|
|Nur bei Eigenschaften des Typs *Text* oder *Kurztext* +
Codes siehe <<basics/interne-IDs#10, Sprachen>>

|Wert
|AlphaNumerisch
|
|

|Beschreibung
|AlphaNumerisch
|
|

|Interner Name
|AlphaNumerisch
|
|

|Eigenschaftenkombination
|AlphaNumerisch
|
|Kombination aus Name, Wert und Sprache im Format +
*Name1:Wert1:Sprache1;Name2:Wert2:Sprache2* etc.

|Auswahleigenschaftkombination (Namen)
|propertyName:selectionName:language;propertyName:selectionName:language
|
|

|Auswahleigenschaftkombination (IDs)
|propertyID:selectionID:language;propertyID:selectionID:language
|
|

|Auswahl-ID
|Numerisch (interne ID)
|
|Nur bei Eigenschaften des Typs *Auswahl*. Verknüpft die Auswahlwerte einer Eigenschaft über die ID. +
Auswahl-IDs siehe *Einrichtung » Einstellungen » Eigenschaften » Konfiguration » Eigenschaft öffnen » Werte*.

|Mehrfachauswahl-IDs (kommasepariert)
|
|
|

|Löschen (Ja/Nein)
|0 = Nein +
1 = Ja
|
|
|====

[#2290]
=== Varianten-Tags

In <<table-mapping-fields-tags>> werden Felder erläutert, die für die Zuordnung von Tags zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#150, Tags mit Varianten zu verknüpfen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Tags wie folgt verknüpft wurden.

//Für den Import von Tag-Verknüpfungen stehen die in <<table-mapping-fields-tags>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-tags]]
.Felder für Import von Tags-Verknüpfungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Tag-ID
//hinweis - es gibt keine Möglichkeit, mehrere Tag IDs auch kommasepariert eingeben - das ginge nur über den Tag-Namen
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib eine Tag-ID in die CSV-Datei ein.
Die Tag-IDs findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

|Tag-Name
|AlphaNumerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib einen Namen für das Tag in die CSV-Datei ein.
Die Tag-Namen findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

|Tag-Namen +
(kommasepariert)
|AlphaNumerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib die Namen von mehreren Tags in die CSV-Datei ein. Verwende Kommas, um die Namen wie folgt zu trennen: +
name1,name2,name3...

Die Tag-Namen findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

|Alle Tag-Verknüpfungen löschen
|0 +
1
|
a|Möchtest du _alle Tags_ von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Tag-Verknüpfungen gelöscht werden sollen.

* 0 = Nein
* 1 = Ja

*_Hinweis_*: Die Tags selbst werden nicht gelöscht. Die Tags werden lediglich von der Variante entfernt.

|Tag-Verknüpfung löschen (Name, kommasepariert)
|AlphaNumerisch
|
a|Möchtest du _einige der Tags_ von einer Variante entfernen?
Gib die Namen der zu entfernenden Tags in die CSV-Datei ein. Verwende Kommas, um die Namen wie folgt zu trennen: +
name1,name2,name3…​

Die Tag-Namen findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

*_Hinweis_*: Die Tags selbst werden nicht gelöscht. Die Tags werden lediglich von der Variante entfernt.

|Tag-Verknüpfung löschen (ID, kommasepariert)
|AlphaNumerisch
|
a|Möchtest du _einige der Tags_ von einer Variante entfernen?
Gib die IDs der zu entfernenden Tags in die CSV-Datei ein. Verwende Kommas, um die IDs wie folgt zu trennen: +
id1,id2,id3…​

Die Tag-IDs findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

*_Hinweis_*: Die Tags selbst werden nicht gelöscht. Die Tags werden lediglich von der Variante entfernt.
|====

[#2420]
=== Vererbung

In <<table-mapping-fields-inheritance>> werden Felder erläutert, die für die Zuordnung von Vererbungen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/einleitung/vererbung#, Daten mit der Vererbungsfunktion weiter zu geben>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Vererbungsfunktionen wie folgt aktiviert oder deaktiviert wurden.

//Für den Import von Vererbungen stehen die in <<table-mapping-fields-inheritance>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-inheritance]]
.Felder für Import von Vererbungen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Kategorie
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Verknüpfte Kategorien>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Märkte
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Märkte>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Mandant
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#_verfügbarkeit_für_mandanten_einstellen, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Mandant (Shop)>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Verkaufspreis
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#240, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verkaufspreise>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Lieferant
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Lager
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Verfügbarkeit
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#240, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Eigenschaften
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#4800, Tab: ID einer Variante » Tab: Eigenschaften>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Tags
|0 +
1
|
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert
|====

[#2420a]
=== Inhalt

In <<table-mapping-fields-content>> werden Felder erläutert, die für die Zuordnung von Inhalten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, den <<artikel/artikel-verwalten#270, Inhalt und Einheit einer Variante>> anzugeben.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Inhalte wie folgt gespeichert wurden.

//Für den Import des Inhalts stehen die in <<table-mapping-fields-content>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-content]]
.Felder für Import des Inhalts
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Inhalt Einheit
|Numerisch
(interne ID)
|
|Entspricht der _Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Inhalt>>

Gib die ID der Einheit in die CSV-Datei ein.
Die Einheit-IDs findest du im Menü *Einrichtung » Artikel » Einheiten*.

*_Hinweis_*: Verwende dieses Zuordnungsfeld in Kombination mit *Inhalt Menge*.

//IDs siehe <<basics/interne-IDs#40, IDs der Einheiten>> +
//Alternativ *Inhalt Maßeinheit (ISO)* übergeben

|Inhalt Menge
|Numerisch
|
|Entspricht dem _Eingabefeld_ unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Inhalt>>

Gib den numerischen Inhalt in die CSV-Datei ein.

*_Hinweis_*: Verwende dieses Zuordnungsfeld in Kombination mit *Inhalt Einheit* oder *Inhalt Maßeinheit (ISO)*.

|Inhalt Maßeinheit (ISO)
|AlphaNumerischer ISO-Code
|
|Entspricht der _Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Inhalt>>

Gib den ISO-Code für die Einheit in die CSV-Datei ein.
Die ISO-Codes findest du im Menü *Einrichtung » Artikel » Einheiten*.

*_Hinweis_*: Verwende dieses Zuordnungsfeld in Kombination mit *Inhalt Menge*.

|====

[#2430]
=== ASIN/ePID

In <<table-mapping-fields-ASIN-ePID>> werden Felder erläutert, die für die Zuordnung von ASIN/ePIDs zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#260, ASIN/ePIDs für Varianten zu speichern>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen im *Tab: Einstellungen » Bereich: ASIN/ePID* wie folgt gespeichert wurden.

//Für den Import von ASIN/ePID stehen die in <<table-mapping-fields-ASIN-ePID>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-ASIN-ePID]]
.Felder für Import von ASIN/ePID
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Land
|Numerisch (interne ID)
|
|Entspricht der _ersten_ Dropdown-Liste unter: +
<<artikel/artikel-verwalten#260, Tab: ID einer Variante » Tab: Einstellungen » Bereich: ASIN/ePID>>

Mit anderen Worten: Entspricht der _Länderplattform_, z.B. Amazon Deutschland, eBay Frankreich, eBay UK, usw.

Gib die Länder-ID in deine CSV-Datei ein. Die Länder-IDs findest du im Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Lieferländer*.

Eine <<basics/interne-IDs#20, Liste von IDs ist auch im Online-Handbuch>> zu finden.

|Typ
|ASIN +
ePID
|
|Entspricht der _zweiten_ Dropdown-Liste unter: +
<<artikel/artikel-verwalten#260, Tab: ID einer Variante » Tab: Einstellungen » Bereich: ASIN/ePID>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob es sich um eine ASIN oder ePID handelt.

|##Position##
|Numerisch
|
|

|Wert
|AlphaNumerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#260, Tab: ID einer Variante » Tab: Einstellungen » Bereich: ASIN/ePID>>

Gib die ASIN oder ePID in deine CSV-Datei ein.

|Löschen (IDs, kommasepariert)
|Numerisch (interne ID)
|
a|Möchtest du einige ASINs oder ePIDs von einer Variante entfernen?
Gib die IDs der zu entfernenden ASINs oder ePIDs in die CSV-Datei ein. Verwende Kommas, um die IDs wie folgt zu trennen: +
ASIN-ID1,ASIN-ID2,ASIN-ID3 etc.

//gibt es ein Menü, wo man die ASIN bzw ePID-IDs findet?
|====

[#2440]
=== Lager

In <<table-mapping-fields-warehouse>> werden Felder erläutert, die für die Zuordnung von Lagerdaten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, anzugeben, <<artikel/artikel-verwalten#312, wo eine bestimmte Variante gelagert ist>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen im Tab *Lager* wie folgt gespeichert wurden.

//Für den Import von Lagerdaten stehen die in <<table-mapping-fields-warehouse>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Lager.

[[table-mapping-fields-warehouse]]
.Felder für Import von Lagerdaten
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|##Zone##
|Numerisch
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Zone>>

//wo kann man die Zone-ID nachschlagen? Also in welchem Menü?
Die Zuordnung erfolgt anhand der Zone-ID im Menü Einrichtung » Waren » Lager » Lager öffnen » Einstellungen.

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Lagerorttyp
|none +
small +
medium +
large +
europallet
|
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Lagerorttyp>>

* none = Kein Typ ausgewählt
* small = Klein
* medium = Mittel
* large = Groß
* europallet = Europalette

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Meldebestand
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Meldebestand>>

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Maximalbestand
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Maximalbestand>>

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Lagerreichweite (in Tagen)
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Lagerreichweite>>

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Lagerort
|Numerisch (interne ID)
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Lagerortvorschlag>>

Die Zuordnung erfolgt anhand der Lagerort-ID im Menü *Einrichtung » Waren » Lager » Lager öffnen » Lagerorte*.

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Bestandspuffer
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Bestandspuffer>>

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Charge (ja/nein)
|0 +
1
|
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Charge>>

* 0 = Kein Häkchen
* 1 = Häkchen

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Mindeshaltbarkeitsdatum (ja/nein)
|0 +
1
|
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: MHD>>

* 0 = Kein Häkchen
* 1 = Häkchen

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Lagerverknüpfung löschen
|0 +
1
|
a|Möchtest du das Lager von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob das Lager gelöscht werden soll.

* 0 = Nein
* 1 = Ja

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

*_Hinweis_*: Das Lager selbst wird nicht gelöscht. Das Lager wird lediglich von der Variante entfernt.
|====

[#2450]
=== Lieferant

In <<table-mapping-fields-supplier>> werden Felder erläutert, die für die Zuordnung von Lieferantendaten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#312, Lieferanten zu Varianten hinzuzufügen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen im Tab *Lieferant* wie folgt gespeichert wurden.

//Für den Import von Lieferantendaten stehen die in <<table-mapping-fields-supplier>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-supplier]]
.Felder für Import von Lieferantendaten
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Lieferantenverknüpfungs-ID
|Numerisch
|
|ID der Verknüpfung zwischen Variante und Lieferant. +
Diese ID wird automatisch von plentymarkets erzeugt. Die ID ist _nicht_ im plentymarkets Backend sichtbar. Sondern wird die ID lediglich im Hintergrund gespeichert. Möchtest du die ID trotzdem sehen, musst du diese Information zunächst aus deinem plentymarkets-System exportieren. Verwende dazu das Exportformat <<daten/daten-exportieren/FormatDesigner#385, VariationSupplier in FormatDesigner>>. +
Das Zuordnungsfeld *Lieferantenverknüpfungs-ID* ist <<daten/daten-importieren/sync-typen/elasticSync-artikel#1930, je nach Anwendungsfall>> eine Pflichtangabe. Beispielsweise wird dieses Feld benötigt, um Lieferanten direkt beim Artikelimport anzulegen.

|EK in Systemwährung
|Kommazahl
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: EK in Systemwährung>>

Gib die Zahl in deine CSV-Datei ein.

|Mindestabnahme
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Mindestabnahme>>

Gib die Menge in deine CSV-Datei ein.

|Lieferanten-Artikel-Nr.
|AlphaNumerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Lieferanten-Artikel-Nr.>>

Gib die externe Artikelnummer in deine CSV-Datei ein.

|Letzte Preisanfrage
|Datum
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Letzte Preisanfrage>>

Gib das Datum der letzten Preisverhandlung in deine CSV-Datei ein.

|Lieferzeit in Tagen
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Lieferzeit in Tagen>>

Gib die Anzahl an Tagen in deine CSV-Datei ein.

|Rabatt
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Rabatt>>

Gib den prozentualen Rabatt in deine CSV-Datei ein.

*_Hinweis_*: Der Rabatt wird in Nachbestellungen nur berücksichtigt, wenn auch die Rabattfähigkeit aktiviert wurde.

|Rabattfähigkeit
|0 +
1
|
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Rabattfähigkeit>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob das Häkchen gesetzt wird.

* 0 = Kein Häkchen
* 1 = Häkchen

|Verpackungseinheit
|Numerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Verpackungseinheit>>

Gib den numerischen Wert in deine CSV-Datei ein.

|EK in Bestellwährung
|Kommazahl
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: EK in Bestellwährung>>

Gib die Zahl in deine CSV-Datei ein.

|Lieferanten-Artikel-Bezeichnung
|AlphaNumerisch
|
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Lieferanten-Artikel-Bez.>>

Gib den den externen Namen in deine CSV-Datei ein.

|Lieferanten-ID
|Numerisch
|
|Entspricht der Kontakt-ID des Lieferanten, wie im Menü *CRM » Kontakte* aufgeführt.

*_Tipp_*: Setze den Filter *Typ* auf *Lieferant*, um nur Kontakte des Typs *Lieferant* anzuzeigen.

|Lieferantenname
|AlphaNumerisch
|
|Entspricht den Namen des Lieferanten, wie im Menü *CRM » Kontakte* aufgeführt.

*_Tipp_*: Setze den Filter *Typ* auf *Lieferant*, um nur Kontakte des Typs *Lieferant* anzuzeigen.

|Lieferantenverknüpfung löschen
|0 +
1
|
a|Möchtest du die Verknüpfung zwischen Lieferant und Variante aufheben? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Verknüpfung gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====

[#2460]
=== SKU

In <<table-mapping-fields-SKU>> werden Felder erläutert, die für die Zuordnung von SKUs zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#235, SKUs für Varianten zu speichern>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen im *Tab: Verfügbarkeit » Bereich: SKU* wie folgt gespeichert wurden.

//Für den Import von SKUs stehen die in <<table-mapping-fields-SKU>> Felder Abgleichfelder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-SKU]]
.Felder für Import von SKUs
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Marktplatz-ID
|Numerisch
|
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: Herkunft>>

Die Zuordnung erfolgt anhand der Auftragsherkunft-ID im Menü *Einrichtung » Aufträge » Auftragsherkunft*.

Eine <<basics/interne-IDs#90, Liste von IDs ist auch im Online-Handbuch>> zu finden.

|Account-ID
|Numerisch
|
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: Konto>>

Die Zuordnung erfolgt anhand der Marktplatzkonto-ID. +
Amazon siehe *Einrichtung » Märkte » Amazon » Einstellungen* +
eBay siehe *Einrichtung » Märkte » eBay » Einstellungen » Kontoeinstellungen*

|SKU
|AlphaNumerisch
|
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: SKU>>

Gib die SKU in deine CSV-Datei ein.

|Parent-SKU
|AlphaNumerisch
|
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: Parent-SKU>>

Gib die Parent-SKU in deine CSV-Datei ein.

|SKU löschen
|0 +
1
|
a|Möchtest du die SKU von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die SKU gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====

[#3000]
=== Zusätzliche SKU

In <<table-mapping-fields-additional-SKU>> werden Felder erläutert, die für die Zuordnung von zusätzlichen SKUs zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#235, zusätzliche SKUs für Varianten zu speichern>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen im *Tab: Verfügbarkeit » Bereich: Zusätzliche SKU* wie folgt gespeichert wurden.

//Für den Import von zusätzlichen SKUs stehen die in <<table-mapping-fields-additional-SKU>> Felder Abgleichfelder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-additional-SKU]]
.Felder für Import von zusätzlichen SKUs
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|##ID##
|Numerisch
|
|Eine existierende SKU ID

|Marktplatz-ID
|Numerisch
|
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Zusätzliche SKU » Option: Herkunft>>

Die Zuordnung erfolgt anhand der Auftragsherkunft-ID im Menü *Einrichtung » Aufträge » Auftragsherkunft*.

Eine <<basics/interne-IDs#90, Liste von IDs ist auch im Online-Handbuch>> zu finden.

|Account-ID
|Numerisch
|
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Zusätzliche SKU » Option: Konto>>

Die Zuordnung erfolgt anhand der Marktplatzkonto-ID. +
Amazon siehe *Einrichtung » Märkte » Amazon » Einstellungen* +
eBay siehe *Einrichtung » Märkte » eBay » Einstellungen » Kontoeinstellungen*

|SKU
|AlphaNumerisch
|
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Zusätzliche SKU » Option: SKU>>

Gib die SKU in deine CSV-Datei ein.

|##Existierende SKU##
|##Numerisch?##
|
|Der aktuelle Wert einer SKU
//was für ein Wert?

|##Abgleich anhand von ID oder existierender SKU##
|0 = Nein +
1 = Ja
|
|

//|Parent-SKU
//|AlphaNumerisch
//|
//|

|Zusätzliche SKU löschen
|0 +
1
|
a|Möchtest du die zusätzliche SKU von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die zusätzliche SKU gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====

[#2470]
=== Paket

In <<table-mapping-fields-bundle>> werden Felder erläutert, die für die Zuordnung von Artikelpaketen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/anwendungsfaelle/multipacks-pakete-sets#2000, Bestandteile zu einem Paket hinzuzufügen>> und Bestandteile wieder aus einem Paket zu entfernen.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du das Paket nach dem Import öffnest, siehst du, dass die Bestandteile wie folgt hinzugefügt oder entfernt wurden.

//Für den Import von Artikelpaketen stehen die in <<table-mapping-fields-bundle>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-bundle]]
.Felder für Import von Paketen
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Paketbestandteile
|AlphaNumerisch
|
|Fügt Bestandteile zu einem Paket hinzu.
Gib die Varianten-ID und Menge des Paketbestandteils in deine CSV-Datei ein.
Trenne die Varianten-ID und Menge durch einen Doppelpunkt.
Trenne mehrere Bestandteile durch einen Semikolon. Beispiel: +
*Varianten-ID:Menge;Varianten-ID:Menge;etc.*

|Paketbestandteile (Variantennummer)
|AlphaNumerisch
|
|Fügt Bestandteile zu einem Paket hinzu.
Gib die Variantennummer und Menge des Paketbestandteils in deine CSV-Datei ein.
Trenne die Variantennummer und Menge durch einen Doppelpunkt.
Trenne mehrere Bestandteile durch einen Semikolon. Beispiel: +
*Variantennummer:Menge;Variantennummer:Menge;etc.*

|Paketbestandteile löschen
|AlphaNumerisch
|
|Löscht Bestandteile aus einem Paket raus.
Gib die Varianten-ID des zu löschenden Paketbestandteils in deine CSV-Datei ein.
Trenne mehrere Varianten-IDs durch einen Semikolon. Beispiel: +
*Varianten-ID;Varianten-ID*

|Paket löschen
|0 = Nein +
1 = Ja
|
|Löscht _alle_ Bestandteile aus einem Paket raus. Die Varianten-IDs der einzelne Bestandteile müssen nicht angegeben werden, da alle Paketbestandteile gleichzeitig gelöscht werden.
|====

[#sync-seriennummer]
=== Seriennummer

In <<table-mapping-fields-serial-number>> werden Felder erläutert, die für die Zuordnung von Seriennummern zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/anwendungsfaelle/seriennummern#100, einen Pool von Seriennummern im Artikeldatensatz aufzubauen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Seriennummer-Einstellungen wie folgt gespeichert wurden.

//Für den Import von Seriennummern stehen die in <<table-mapping-fields-serial-number>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-serial-number]]
.Felder für Import von Seriennummern
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID
|Numerisch
|
|Entspricht dem Feld unter: +
<<artikel/anwendungsfaelle/seriennummern#200, Seriennummern-Symbol in die obere Leiste (icon:item_serial_number[set=plenty]) » Bereich: Seriennummern » Option: ID>>

Gib die ID der Seriennummer in deine CSV-Datei ein.

|Nummer
|Numerisch
|
|Entspricht dem Feld unter: +
<<artikel/anwendungsfaelle/seriennummern#200, Seriennummern-Symbol in die obere Leiste (icon:item_serial_number[set=plenty]) » Bereich: Seriennummern » Option: Seriennummer>>

Gib die Seriennummer in deine CSV-Datei ein.

|Seriennummer löschen
|0 +
1
|
a|Möchtest du die Seriennummer von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Seriennummer gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====


[#1930]
== Pflichtwerte für Artikel-Sync-Aktionen

<<table-procedures-item-sync>> listet mögliche Aktionen für Syncs des Typs Artikel und erläutert die Werte, die zum Ausführen dieser Aktionen unbedingt angegeben werden müssen.

[[table-procedures-item-sync]]
.Aktionen für Artikel-Sync
|====
|Aktion |Erforderliche Werte

2+|*Artikelbeschreibung*

|Artikelbeschreibung aktualisieren
a|
* Name

2+|*Versandprofil*

|Versandprofil aktualisieren
a|
* Versandprofil-ID

2+|*Varianten-Tags*

|Alle Tag-Verknüpfungen lösen
a|
* Alle verknüpften Tags löschen = 1

|Tag verknüpfen
a|Ein Tag:

* Tag-ID +
oder
* Tag-Name +

Mehrere Tags: +

* Tag-Namen (kommasepariert)

2+|*Varianten*

|Variante erstellen
a|
* ID der Standardkategorie +
oder
* Name der Standardkategorie

|Variante zu Artikel hinzufügen
a|
* Inhalt Menge
* Inhalt Einheit +
    oder
* Inhalt Menge
* Inhalt Maßeinheit (ISO)

und

* Artikel-ID +
    oder
* Nummer der Hauptvariante

Bei Varianten mit Attributen außerdem:

* Attributauswahlkombination +
    oder
* Attribute (Name oder ID)
* Wert (Name oder ID)

|Inhalt aktualisieren
a|
* Inhalt Menge
* Inhalt Einheit +
oder
* Inhalt Menge
* Inhalt Maßeinheit (ISO)

2+|*Barcodes*

|Barcode ändern
a|
* Code über Barcode-Zuordnung

2+|*Kategorien*

|Kategorie verknüpfen
a|
* ID der Kategorie +
oder
* Name der Kategorie

*_Tipp:_* Für weitere Kategorien zusätzliche Mappings erstellen.

|Verknüpfung aktualisieren
a|
* ID der Kategorie +
oder
* Name der Kategorie

2+|*Variantenpreise*

|Preis ändern
a|
* Preis über Verkaufspreiszuordnung

2+|*Standardkategorien*

|Standardkategorie verknüpfen
a|
* ID der Kategorie +
oder
* Name der Kategorie

|Standardkategorie aktualisieren
a|
* ID der Kategorie +
oder
* Name der Kategorie

2+|*Bestand*

|Bestand aktualisieren
a|
* Lager
* Menge
* Lagerort

2+|*Artikel-Bilder*

|Vor dem Hochladen alle Bilder löschen
a|
* Bilder löschen = 1

|Bilder speichern
a|
* Multi-URL +
oder
* URL +
oder
* Dateiname
* Base64 Data

|Bilder aktualisieren
a|
* ID des Bildes

|Bild mit Variante verknüpfen
a|
* Multi-URL +
oder
* URL

2+|*Merkmale*

|Merkmale speichern
a|
* Merkmalkombination +
oder
* Interner Name
* Sprache
* Wert +
oder
* ID
* Sprache
* Wert

|Merkmale aktualisieren
a|
* Merkmalkombination +
oder
* Interner Name
* Sprache
* Wert +
oder
* ID
* Sprache
* Wert

2+|*Eigenschaften*

|Eigenschaft verknüpfen
a|
* ID

* Sprache

* Wert

2+|*Lieferant*

|Lieferant verknüpfen
a|
* EK
* Lieferantenverknüpfungs-ID (für neue Verknüpfungen leer lassen)

und

* Lieferanten-ID +
    oder
* Lieferanten-Name

|Lieferant aktualisieren
a|
* EK
* Lieferantenverknüpfungs-ID

und

* Lieferanten-ID +
    oder
* Lieferanten-Name

2+|*SKU*

|SKU hinzufügen
a|
* Marktplatz-ID
* SKU

Bei eBay/Amazon außerdem:

* Account-ID

|SKU aktualisieren
a|
* Marktplatz-ID
* SKU

Bei eBay/Amazon außerdem:

* Account-ID

2+|*Paket*

|Paket erstellen
a|
* Paketbestandteile

|Paketbestandteile löschen
a|
* Paketbestandteile löschen

|Paket löschen
a|
* Paket löschen = 1

|====
