= Kontakte, Firmen und Adressen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, TYP
:position: 90
:url: daten/daten-importieren/sync-typen/elasticSync-kontakte-firmen-adressen
:id:
:author: team-crm

Diese Seite erläutert die Abgleich- und Zuordnungsfelder, die dir beim Importieren von Kontakten, Firmen und Adressen zur Verfügung stehen. Diese Seite dient lediglich als Referenz und setzt voraus, dass du bereits Grundkenntnisse über das Import-Tool hast.

[TIP]
.Praxisbeispiel: Kontaktdaten importieren
====
Stell dir mal vor, du bist ganz neu bei plentymarkets und möchtest alle deine Kontaktdaten auf einmal importieren. Wie geht so etwas? Wirf einen Blick auf <<daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-kontaktdaten#, dieses praktische Beispiel>>, welches dich Schritt für Schritt durch den Prozess führt.
====

== Abgleichfelder

In <<table-matching-fields-contacts-accounts-addresses>> werden Felder erläutert, die für den Abgleich von Kontakt-, Firmen- und Adressdaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-matching-fields-contacts-accounts-addresses]]
.Abgleichfelder für den Import von Kontakt-, Firmen- und Adressdaten
[cols="1,3"]
|===
|Einstellung |Erläuterung

|Kontakt-ID
|
//TODO: Frage ergänzen
ID des Kontakts

|E-Mail
|
//TODO: Frage ergänzen
E-Mail-Adresse des Kontakts

|Rechnungsadress-ID
|
//TODO: Frage ergänzen
ID der Rechnungsadresse

|Lieferadress-ID
|
//TODO: Frage ergänzen
ID der Lieferadresse

|===


== Zuordnungsfelder

In diesem Kapitel werden Felder erläutert, die für die Zuordnung von Kategoriedaten zur Verfügung stehen. Mithilfe dieser Felder legst du fest, welche _Spalte deiner Datei_ welchem _Datenfeld in deinem System_ entspricht.

[.instruction]
Grundlegende Vorgehensweise:

. *_In deiner CSV-Datei_*: Gib einen zulässigen Importwert in eine Spalte ein.
. *_In plentymarkets_*: Ordne diese Spalte dem passenden Zuordnungsfeld zu.
. *_Nach dem Import_*: Prüfe das Ergebnis im Backend.

[TIP]
.Kein Zuordnungsfeld? Standardwert greift!
====
Wenn du eine bestimmte Information nicht in deine CSV-Datei aufnimmst, d.h. wenn du ein bestimmtes Zuordnungsfeld _nicht verwendest_, dann erhält deine Kategorie den Standardwert.
====


=== Kontakt

==== Externe Nummer

Gib die externe Nummer in deine CSV-Datei ein. Dies kann z.B. die Kundennummer aus einem anderen System sein, um die Zuordnung nicht zu verlieren, wenn du deine Daten in plentymarkets importiert.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''


==== Nummer

// Wenn es sich bei dem Feld um ein Pflichtfeld handelt.
icon:warning[role="red"] [red]#Pflichtwert#

// Wenn das Feld nur für Callisto-Systeme relevant ist.
icon:warning[role="red"] [red]#Nur für den alten Callisto-Webshop relevant#

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Typ

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Typs in die CSV-Datei ein.

[TIP]
Die IDs 1 bis 6 sind fest vorgegeben und können nicht geändert werden. Du kannst weitere Typen im Menü XXX erstellen.

*_Standardwert:_* `0`

*_Mögliche Importwerte:_* Numerisch (interne ID)

[[table-mapping-fields-contact-type]]
[cols="1,1"]
|===

|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Kein

|`1`
|Kunde

|`2`
|Interessent

|`3`
|Handelsvertreter

|`4`
|Lieferant

|`5`
|Hersteller

|`6`
|Partner

|`weitere ganze Zahlen`
|xxxx

|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''


==== Vorname

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

==== Nachname

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

==== Geschlecht

Gib in der CSV-Datei das Geschlecht des Kontakts ein.

*_Standardwert:_* leere Option

[[table-mapping-fields-contacts-form-of-address]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|Leere Option
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz ist leer.

|female
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz zeigt *Frau* an.

|male
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz zeigt *Herr* an.

|diverse
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz zeigt *Divers* an.

|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

==== Titel

Gib den Titel des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

==== Newsletter

//nur möglich für alten Webshop Callisto?

Gib das Datum der Newsletter-Registrierung des Kontakts in deiner CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Datumsformat


Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

==== Kundenklasse

// Wenn es sich bei dem Feld um ein Pflichtfeld handelt.
icon:warning[role="red"] [red]#Pflichtwert#

// Wenn das Feld nur für Callisto-Systeme relevant ist.
icon:warning[role="red"] [red]#Nur für den alten Callisto-Webshop relevant#

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_* Numerisch (interne ID)


[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Gesperrt

Entscheide, ob der Kontakt für den Mandanten gesperrt ist oder nicht.

*_Standardwert:_* `0`


[[table-mapping-fields-categories-contacts-blocked]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|nicht gesperrt

|`1`
|gesperrt
|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

==== Bewertung

Welche interne Bewertung möchtest du dem Kontakt geben? Gib eine Zahl zwischen -5 für die schlechteste Bewertung und 5 für die beste Bewertung ein. Die Bewertung des Kontakts dient ausschließlich der internen Verwendung und kann nicht von deinen Kunden eingesehen werden.

*_Standardwert:_* `0`

[[table-mapping-fields-contacts-rating]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|5 graue Sterne. Keine Bewertung für den Kontakt gespeichert.

|`5`
|5 gelbe Sterne (beste Bewertung)

|`4`
|4 gelbe Sterne

|`3`
|3 gelbe Sterne

|`2`
|2 gelbe Sterne

|`1`
|1 gelber Stern

|`-1`
|1 roter Stern

|`-2`
|2 rote Sterne

|`-3`
|3 rote Sterne

|`-4`
|4 rote Sterne

|`-5`
|5 rote Sterne (schlechteste Bewertung)


|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

==== Debitorenkonto

// Füge eine Beschreibung des Felds ein.

Zusätzliche Nummer, die generell der Kundennummer oder der Debitorennummer des Kontakts in der Buchhaltung entspricht.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

==== Sprache

[TIP]
<<daten/interne-IDs#10, Auf dieser Handbuchseite>> findest du eine Liste mit den Sprachkürzeln.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

==== Herkunft

icon:warning[role="red"] [red]#Pflichtwert#

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_* Numerisch (interne ID)

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== plenty ID

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_* Numerisch (interne ID)


// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Eigner-ID


// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Numerisch (interne ID)

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Geburtsdatum

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datum im Format dd.mm.yyyy

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

==== Valuta

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Skontofrist

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Skontosatz

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Zahlungsziel

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_*

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Handelsvertreter-ID

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Kontakt-ID

// Wenn es sich bei dem Feld um ein Pflichtfeld handelt.
icon:warning[role="red"] [red]#Pflichtwert#

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_* Numerisch (interne ID)

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

=== Kontaktoptionen

==== Telefon Privat


(Typ 1 Subtyp 4)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

==== Telefon Geschäftlich


(Typ 1 Subtyp 1)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

==== Mobiltelefon Privat
(Typ 1 Subtyp 2)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

==== Mobiltelefon Geschäftlich
(Typ 1 Subtyp 3)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

==== E-Mail privat
(Typ 2 Subtyp 4)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

==== E-Mail Geschäftlich
(Typ 2 Subtyp 1)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

==== E-Mail PayPal
(Typ 2 Subtyp 5)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

==== Fax Privat
(Typ 3 Subtyp 4)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Numerisch


Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

==== Fax Geschäftlich
(Typ 3 Subtyp 1)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Numerisch


Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

==== Homepage Privat
(Typ 1 Subtyp 2)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

==== Homepage Geschäftlich
(Typ 1 Subtyp 2)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

==== Marktplatz eBay
(Typ 5 Subtyp 6)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Marktplatz Amazon
(Typ 5 Subtyp 7)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''


==== Identifikationsnummer Klarna
(Typ 6 Subtyp 8)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Identifikationsnummer DHL
(Typ 6 Subtyp 9)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Payment PayPal
(Typ 7 Subtyp 5)




// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Payment Klarna
(Typ 7 Subtyp 8)




// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Payment Standard
(Typ 7 Subtyp 14)




// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Benutzername Privat
(Typ 8 Subtyp 4)




// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch


// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Benutzername Geschäftlich
(Typ 8 Subtyp 1)




// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch


// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Gastzugang
(Typ 10 Subtyp 11)

icon:warning[role="red"] [red]#Nur für den alten Callisto-Webshop relevant#


// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* 0

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.



[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|0
|regulärer Zugang

|1
|Gastzugang

|===



// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Ansprechpartner
(Typ 11 Subtyp 12)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Briefanrede Privat
(Typ 12 Subtyp 4)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert



*_Mögliche Importwerte:_* Text

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

==== Briefanrede Geschäftlich
(Typ 12 Subtyp 1)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Text

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

=== Rechnungsadresse

==== Adress-ID

Gib die ID der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Name1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name2* und *Name3* keine Werte importierst.

Gib den Firmennamen der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Name2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name3* keine Werte importierst.

Gib den Vornamen des Kontakts aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Name3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name2* keine Werte importierst.

Gib den Nachnamen des Kontakts aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Name4

Gib eine Zusatzangabe zum Kontakt in deine CSV-Datei ein, z.B. "z.Hd. Herrn Max Mustermann".

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Adresse1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse2* und *Adresse3* keine Werte importierst.

Gib die Straße des Kontakts aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Adresse2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse3* keine Werte importierst.

Gib die Hausnummer des Kontakts aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Adresse3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse2* keine Werte importierst.

Gib einen Adresszusatz zu der Rechnungsadresse in deine CSV-Datei ein, z.B. "Apartment 12a".

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Adresse4

Gib weitere Zusatzinformationen ein. Dieses Feld steht dir zur freien Verfügung.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Postleitzahl

Gib die Postleitzahl der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Ort

icon:warning[role="red"] [red]#Pflichtwert#

Gib den Ort der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Länder-ID* (oder ISO)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Staaten-ID

Gib die ID der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

// Link zu den State-IDs einfügen

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Überprüft am

Möchtest du das Datum eingeben, wann die Rechnungsadresse geprüft wurde?

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datum im Format dd.mm.yyyy

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Titel

Gib den Titel aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Ansprechpartner

Gib den Ansprechpartner aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''
==== Länder-ISO-Code* (oder ID)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.


*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Staaten-ISO-Code

Gib den ISO-Code der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#30#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen IDs.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

=== Optionen der Rechnungsadresse

==== Umsatzsteuernummer

(Typ 1)

Gib die Umsatzsteueridentifikationsnummer der Firma in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''


==== Externe Adress-ID

 (Typ 2)


Gib XXXXX der Firma in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Gelangensbestätigung

 (Typ 3)

Um beim Versand in ein anderes Land der EU von der Umsatzsteuer befreit zu werden, müssen Händler anhand der Gelangensbestätigung nachweisen, dass die Ware aus Deutschland in einem anderen EU-Mitgliedstaat angekommen ist.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_*

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''


==== Telefon

 (Typ 4)

Gib die Telefonnummer aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== E-Mail

 (Typ 5)

Gib die E-Mail-Adresse der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== Postnummer

 (Typ 6)

Bei der Postnummer handelt es sich um die Kundennummer von DHL. Gib die Postnummer in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== Personennummer

 (Typ 7)

Identitätsnummer in Schweden

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== FSK

 (Typ 8)

Freiwillige Selbstkontrolle, Altersfreigabe

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== Geburtstag

 (Typ 9)

Gib das Geburtsdatum aus der Rechnungsadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datumsangabe im Format dd.mm.yyyy

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== Titel

 (Typ 11)

Gib den Titel in der Rechnungsadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== Ansprechpartner

 (Typ 12)

Gib den Ansprechpartner in der Rechnungsadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

=== Lieferadresse

==== Adress-ID

Gib die ID der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Name1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name2* und *Name3* keine Werte importierst.

Gib den Firmennamen der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Name2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name3* keine Werte importierst.

Gib den Vornamen des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Name3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name2* keine Werte importierst.

Gib den Nachnamen des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Name4

Gib eine Zusatzangabe zum Kontakt in deine CSV-Datei ein, z.B. "z.Hd. Herrn Max Mustermann".

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Adresse1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse2* und *Adresse3* keine Werte importierst.

Gib die Straße des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Adresse2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse3* keine Werte importierst.

Gib die Hausnummer des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Adresse3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse2* keine Werte importierst.

Gib einen Adresszusatz zu der Lieferadresse in deine CSV-Datei ein, z.B. "Apartment 12a".

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Adresse4

Gib weitere Zusatzinformationen ein. Dieses Feld steht dir zur freien Verfügung.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Postleitzahl

Gib die Postleitzahl der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Ort

icon:warning[role="red"] [red]#Pflichtwert#

Gib den Ort der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Länder-ID* (oder ISO)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.


*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Staaten-ID

Gib die ID der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

// Link zu den State-IDs einfügen

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Überprüft am

==== Titel

Gib den Titel aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''
==== Länder-ISO-Code* (oder ID)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.


*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

==== Staaten-ISO-Code

Gib den ISO-Code der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#30#, Auf dieser Handbuchseite>> findest du ein Liste mit den ISO-Codes.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

=== Optionen der Lieferadresse

==== Umsatzsteuernummer

(Typ 1)

Gib die Umsatzsteueridentifikationsnummer der Firma in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Externe Adress-ID

 (Typ 2)

Gib XXXXX der Firma in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Gelangensbestätigung

 (Typ 3)

Um beim Versand in ein anderes Land der EU von der Umsatzsteuer befreit zu werden, müssen Händler anhand der Gelangensbestätigung nachweisen, dass die Ware aus Deutschland in einem anderen EU-Mitgliedstaat angekommen ist.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_*

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== Telefon

 (Typ 4)

Gib die Telefonnummer aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== E-Mail

 (Typ 5)

Gib die E-Mail-Adresse der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== Postnummer

 (Typ 6)

Bei der Postnummer handelt es sich um die Kundennummer von DHL. Gib die Postnummer in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== Personennummer

 (Typ 7)

Identitätsnummer in Schweden

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== FSK

 (Typ 8)

Freiwillige Selbstkontrolle, Altersfreigabe

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== Geburtstag

 (Typ 9)

Gib das Geburtsdatum aus der Lieferadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datumsangabe im Format dd.mm.yyyy

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== Titel

 (Typ 11)

Gib den Titel in der Lieferadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

==== Ansprechpartner

 (Typ 12)

Gib den Ansprechpartner in der Lieferadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

=== Firma

==== Firmen-ID

Gib die ID der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Nummer

Zusätzliche Nummer für die Firma. Diese Nummer kann selbst vergeben werden. Maximale Zeichenlänge: 128. Gib die ID der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Firmenname

icon:warning[role="red"] [red]#Pflichtwert#

Gib den Namen der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Steuer-ID

Gib die Umsatzsteueridentifikationsnummer der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

*_Beispiel:_* Für Deutschland: DE123456789

'''

==== Valuta

Gib die Valuta der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Skonto Tage

Gib die Skontofrist der Firma in Tagen in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Rabattsatz

Gib den Skontosatz der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Zahlungsziel

Gib das Zahlungsziel der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Handelsvertreter-ID

Gib die ID des Handelsvertreters der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Eigner-ID

Gib die ID des Eigners in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Lieferzeit

Gib die Lieferzeit in Tagen für den Typ *Lieferant* in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Mindestbestellwert

Gib den Mindestbestellwert in der Systemwährung für den Typ *Lieferant* in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

==== Lieferantenwährung



=== Handelsvertreter

==== Region-ID

Gib die ID der Region in deine CSV-Datei ein.

// Link zu plenty Regionen einfügen

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''


==== PLZ-Bereich

Gib den Postleitzahlenbereich, in dem der Handelsvertreter tätig ist, in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

*_Beispiel:_* 34117-34131

'''

==== Länder-ID


Gib die ID des Landes in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs.


*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

=== Erlaubte Zahlungsarten

==== Lastschrift erlauben

Möchtest du die Zahlungsart Lastschrift für den Kontakt erlauben?

[TIP]
Die Zahlungsart muss im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* aktiviert sein.

*_Standardwert_*: `0`

[[table-mapping-contacts-allow-debit]]
[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Zahlungsart Lastschrift ist _nicht_ erlaubt.

|`1`
|Zahlungsart Lastschrift ist erlaubt.
|====

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

==== Rechnung erlauben

Möchtest du die Zahlungsart Rechnung für den Kontakt erlauben?

[TIP]
Die Zahlungsart muss im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* aktiviert sein.

*_Standardwert_*: `0`

[[table-mapping-contacts-allow-debit]]
[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Zahlungsart Rechnung ist _nicht_ erlaubt.

|`1`
|Zahlungsart Rechnung ist erlaubt.
|====

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

=== Eigenschaften

==== Eigenschafts-ID

Gib die ID der Eigenschaft in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

'''

==== Eigenschaftstyp

Gib den Eigenschaftstyp in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

[[table-mapping-fields-contacts-property-type]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|Kein
|

|Ganze Zahl
|

|Auswahl
|

|Mehrfachauswahl
|

|Kurztext
|

|Text
|

|Datum
|

|Datei
|

|===


Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

'''

==== Eigenschaftswert

Gib den Wert der Eigenschaft in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

*_Beispiel:_* Wenn du als Eigenschaftstyp *xx* gewählt hast, würde im Kontaktdatensatz z.B. xxx angezeigt werden.

'''

==== Kontakt-ID

Gib die ID des Kontakts, der mit der Eigenschaft verknüpft ist, in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.
'''

==== Sprache

Gib das Sprachkürzel, z.B. *en* oder *fr* in deine CSV-Datei ein, wenn die Eigenschaft in anderen Sprachen als in der Systemsprache hinzugefügt werden soll.

[TIP]
<<daten/interne-IDs#10, Auf dieser Handbuchseite>> findest du eine Liste mit den Sprachkürzeln.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

'''

==== Löschen (Ja/Nein)

Möchtest du die Eigenschaft löschen?

*_Standardwert_*: xxx?

[[table-mapping-contacts-delete-property]]
[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Eigenschaft wird _nicht_ gelöscht

|`1`
|Eigenschaft wird gelöscht
|====

'''
