= Kontakte, Firmen und Adressen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Kontakte, Firmen, Adressen
:position: 90
:url: daten/daten-importieren/sync-typen/elasticSync-kontakte-firmen-adressen
:id: SMSK85D
:author: team-crm

Diese Seite erläutert die Abgleich- und Zuordnungsfelder, die dir beim Importieren von Kontakten, Firmen und Adressen zur Verfügung stehen. Diese Seite dient lediglich als Referenz und setzt voraus, dass du bereits Grundkenntnisse über das <<daten/daten-importieren/ElasticSync#, Import-Tool>> hast.

[TIP]
.Praxisbeispiel: Kontaktdaten importieren
====
Stell dir mal vor, du bist ganz neu bei plentymarkets und möchtest alle deine Kontaktdaten auf einmal importieren. Wie geht so etwas? Wirf einen Blick auf <<daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-kontaktdaten#, dieses praktische Beispiel>>, welches dich Schritt für Schritt durch den Prozess führt.
====

[#abgleichfelder]
== Abgleichfelder

In <<#table-matching-fields-contacts-accounts-addresses>> werden Felder erläutert, die für den Abgleich von Kontakt-, Firmen- und Adressdaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-matching-fields-contacts-accounts-addresses]]
.Abgleichfelder für den Import von Kontakt-, Firmen- und Adressdaten
[cols="1,3"]
|===
|Einstellung |Erläuterung

|Kontakt-ID
|In welcher Spalte der CSV-Datei werden Kontakt-IDs aufgelistet? Wähle diese Spalte hier. Diese Option ist sinnvoll, wenn du _bestehende Kontakte aktualisieren_ möchtest.

*_Hintergrund-Info:_* Jeder neu angelegte Kontakt erhält automatisch eine ID, die nicht geändert werden kann. Die ID dient zur eindeutigen Kennzeichnung des Kontakts. Da die ID eindeutig ist, lässt sich damit gut prüfen, ob der importierte Datensatz bereits in plentymarkets vorhanden ist.

|E-Mail
|In welcher Spalte der CSV-Datei werden die E-Mail-Adressen aufgeführt? Wähle diese Spalte hier.
// Diese Option ist sinnvoll, wenn du neue Kontakte anlegen möchtest. --> Stimmt das?

|Rechnungsadress-ID
|In welcher Spalte der CSV-Datei werden die IDs der Rechnungsadresse aufgelistet? Wähle diese Spalte hier. Diese Option ist sinnvoll, wenn du die Rechnungsadressen _bestehender Kontakte aktualisieren_ möchtest.
//prüfen lassen

|Lieferadress-ID
|In welcher Spalte der CSV-Datei werden die IDs der Lieferadresse aufgelistet? Wähle diese Spalte hier. Diese Option ist sinnvoll, wenn du die Lieferadressen _bestehender Kontakte aktualisieren_ möchtest.
//prüfen lassen

|===

[#zuordnungsfelder]
== Zuordnungsfelder

In diesem Kapitel werden Felder erläutert, die für die Zuordnung von Kontakt-, Firmen- und Adressdaten zur Verfügung stehen. Mithilfe dieser Felder legst du fest, welche _Spalte deiner Datei_ welchem _Datenfeld in deinem System_ entspricht.

[.instruction]
Grundlegende Vorgehensweise:

. *_In deiner CSV-Datei_*: Gib einen zulässigen Importwert in eine Spalte ein.
. *_In plentymarkets_*: Ordne diese Spalte dem passenden Zuordnungsfeld zu.
. *_Nach dem Import_*: Prüfe das Ergebnis im Backend.

[TIP]
.Kein Zuordnungsfeld? Standardwert greift!
====
Wenn du eine bestimmte Information nicht in deine CSV-Datei aufnimmst, d.h. wenn du ein bestimmtes Zuordnungsfeld _nicht verwendest_, dann erhält dein Kontakt den Standardwert.
====

[#zuordnungsfeld-kontakt]
=== Kontakt

[#zuordnungsfeld-kontakt-externe-nummer]
==== Externe Nummer

Gib die externe Nummer in deine CSV-Datei ein. Dies kann z.B. die Kundennummer aus einem anderen System sein, um die Zuordnung nicht zu verlieren, wenn du deine Daten in plentymarkets importiert.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-nummer]
==== Nummer

Dies ist eine zusätzliche Nummer für den Kontakt, die du selbst vergeben kannst.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch, maximale Zeichenlänge: 128

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-typ]
==== Typ

icon:warning[role="red"] [red]#Pflichtwert#

Welchen Typen möchtest du dem Kontakt zuweisen? Typen dienen der Einordnung und Unterscheidung von Kontakten. Gib die ID des Typs in die CSV-Datei ein.

[TIP]
Die IDs 1 bis 6 sind fest vorgegeben und können nicht geändert werden. Du kannst weitere Typen im Menü *Einrichtung » CRM » Typen* erstellen.

*_Standardwert:_* `1`

*_Mögliche Importwerte:_* Numerisch (interne ID)

[[table-mapping-fields-contact-type]]
[cols="1,1"]
|===

|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`1`
|Kunde

|`2`
|Interessent

|`3`
|Handelsvertreter

|`4`
|Lieferant

|`5`
|Hersteller

|`6`
|Partner

|`weitere IDs`
|Von dir erstellte Typen

|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-vorname]
==== Vorname

Wie lautet der Vorname des Kontakts? Gib den Vornamen in deine CSV-Datei ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-nachname]
==== Nachname

Wie lautet der Nachnname des Kontakts? Gib den Nachnamen in deine CSV-Datei ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-geschlecht]
==== Geschlecht

Gib in der CSV-Datei das Geschlecht des Kontakts ein.

*_Standardwert:_* leere Option

[[table-mapping-fields-contacts-form-of-address]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|Leere Option
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz ist leer.

|female
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz zeigt *Frau* an.

|male
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz zeigt *Herr* an.

|diverse
|Die Dropdown-Liste *Anrede* im Kontaktdatensatz zeigt *Divers* an.

|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-titel]
==== Titel

Hat der Kontakt einen Titel? Gib den Titel des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-newsletter]
==== Newsletter

//nur möglich für alten Webshop Callisto?

Gib das Datum der Newsletter-Registrierung des Kontakts in deiner CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datum im Format tt.mm.jjjj

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-kundenklasse]
==== Kundenklasse

Soll der Kontakt einer Kundenklasse zugeordnet werden?

[TIP]
Wenn Kundenklassen im System gespeichert sind, _muss_ das Feld in der CSV-Datei mit der ID der Kundenklasse befüllt sein. Andernfalls wird der Kontakt nicht in dein plentymarkets System importiert.
Wenn du keine Kundenklassen im System erstellt hast, kannst du dieses Feld für den Import ignorieren.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-gesperrt]
==== Gesperrt

Entscheide, ob der Kontakt für den Mandanten gesperrt ist oder nicht.

// für welchen Mandanten?

*_Standardwert:_* `0`

[[table-mapping-fields-categories-contacts-blocked]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|nicht gesperrt

|`1`
|gesperrt
|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-bewertung]
==== Bewertung

Welche interne Bewertung möchtest du dem Kontakt geben? Gib eine Zahl zwischen -5 für die schlechteste Bewertung und 5 für die beste Bewertung ein. Die Bewertung des Kontakts dient ausschließlich der internen Verwendung und kann nicht von dem Kunden eingesehen werden.

*_Standardwert:_* `0`

[[table-mapping-fields-contacts-rating]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|5 graue Sterne. Keine Bewertung für den Kontakt gespeichert.

|`5`
|5 gelbe Sterne (beste Bewertung)

|`4`
|4 gelbe Sterne

|`3`
|3 gelbe Sterne

|`2`
|2 gelbe Sterne

|`1`
|1 gelber Stern

|`-1`
|1 roter Stern

|`-2`
|2 rote Sterne

|`-3`
|3 rote Sterne

|`-4`
|4 rote Sterne

|`-5`
|5 rote Sterne (schlechteste Bewertung)


|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-debitorenkonto]
==== Debitorenkonto

Das Debitorenkonto ist eine zusätzliche Nummer, die meist der Kundennummer oder der Debitorennummer des Kontakts in der Buchhaltung entspricht.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-sprache]
==== Sprache

Sprache des Kontakts in deine CSV-Datei eingeben.
Wenn du im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Vorlagen* Vorlagen in der hier gewählten Sprache erstellt hast, werden die E-Mail-Vorlagen in dieser Sprache an den Kontakt versendet.

[TIP]
<<daten/interne-IDs#10, Auf dieser Handbuchseite>> findest du eine Liste mit den Sprachkürzeln.

*_Standardwert:_* xxx

*_Mögliche Importwerte:_* xxx

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-herkunft]
==== Herkunft

icon:warning[role="red"] [red]#Pflichtwert#

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_* Numerisch (interne ID)

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontakt-plenty-id]
==== plenty ID

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_* Numerisch (interne ID)


// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontakt-eigner-id]
==== Eigner-ID

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontakt-geburtsdatum]
==== Geburtsdatum

Gib das Geburtsdatum des Kontakts in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datum im Format tt.mm.jjjj

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-kontakt-valuta]
==== Valuta

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-kontakt-skontofrist]
==== Skontofrist

Möchtest du dem Kontakt die Möglichkeit einer Skontofrist einräumen? Gib die Anzahl der Tage in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-kontakt-skontosatz]
==== Skontosatz

Möchtest du dem Kontakt einen Skontosatz erlauben, der bei Einhaltung der Skontofrist in Abzug gebracht werden kann? Gib einen Wert in Prozent in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-kontakt-zahlungsziel]
==== Zahlungsziel

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_*

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-kontakt-handelsvertreter-id]
==== Handelsvertreter-ID

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontakt-kontakt-id]
==== Kontakt-ID

// Wenn es sich bei dem Feld um ein Pflichtfeld handelt.
icon:warning[role="red"] [red]#Pflichtwert#

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_* Numerisch (interne ID)



'''

[#zuordnungsfeld-kontaktoptionen]
=== Kontaktoptionen


[#zuordnungsfeld-kontaktoptionen-telefon-privat]
==== Telefon Privat


(Typ 1 Subtyp 4)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-telefon-geschaeftlich]
==== Telefon Geschäftlich

(Typ 1 Subtyp 1)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-mobiltelefon-privat]
==== Mobiltelefon Privat
(Typ 1 Subtyp 2)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-mobiltelefon-geschaeftlich]
==== Mobiltelefon Geschäftlich
(Typ 1 Subtyp 3)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''
[#zuordnungsfeld-kontaktoptionen-e-mail-privat]
==== E-Mail privat
(Typ 2 Subtyp 4)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-e-mail-geschaeftlich]
==== E-Mail Geschäftlich
(Typ 2 Subtyp 1)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''
[#zuordnungsfeld-kontaktoptionen-e-mail-paypal]
==== E-Mail PayPal
(Typ 2 Subtyp 5)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-fax-privat]
==== Fax Privat
(Typ 3 Subtyp 4)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Numerisch


Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-fax-geschaeftlich]
==== Fax Geschäftlich
(Typ 3 Subtyp 1)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-homepage-privat]
==== Homepage Privat
(Typ 1 Subtyp 2)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-homepage-geschaeftlich]
==== Homepage Geschäftlich
(Typ 1 Subtyp 2)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Kontaktoptionen>>.

'''

[#zuordnungsfeld-kontaktoptionen-marktplatz-ebay]
==== Marktplatz eBay
(Typ 5 Subtyp 6)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-marktplatz-amazon]
==== Marktplatz Amazon
(Typ 5 Subtyp 7)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-identifikationsnummer-klarna]
==== Identifikationsnummer Klarna
(Typ 6 Subtyp 8)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-identifikationsnummer-dhl]
==== Identifikationsnummer DHL
(Typ 6 Subtyp 9)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-payment-paypal]
==== Payment PayPal
(Typ 7 Subtyp 5)




// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-payment-klarna]
==== Payment Klarna
(Typ 7 Subtyp 8)




// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-payment-standard]
==== Payment Standard
(Typ 7 Subtyp 14)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_*

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-benutzername-privat]
==== Benutzername Privat
(Typ 8 Subtyp 4)


// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch


// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-benutzername-geschaeftlich]
==== Benutzername Geschäftlich
(Typ 8 Subtyp 1)




// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch


// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-gastzugang]
==== Gastzugang
(Typ 10 Subtyp 11)

icon:warning[role="red"] [red]#Nur für den alten Callisto-Webshop relevant#


// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* 0

// Wenn die Importwerte keine eindeutige Entsprechung im Backend haben. Das heißt sie umfassen z.B. alle alphanumerischen Zeichen.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|0
|regulärer Zugang

|1
|Gastzugang

|===



// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-ansprechpartner]
==== Ansprechpartner
(Typ 11 Subtyp 12)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert

*_Mögliche Importwerte:_*

// Wenn die Importwerte eine eindeutige Entsprechung im Backend haben. Das sind z.B. Optionen in einer Dropdown-Liste. Wenn möglich, kannst du das Ergebnis genauer beschreiben.

[[table-mapping-fields-categories]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|
|
|===

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-briefanrede-privat]
==== Briefanrede Privat
(Typ 12 Subtyp 4)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert



*_Mögliche Importwerte:_* Text

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-kontaktoptionen-briefanrede-geschaeftlich]
==== Briefanrede Geschäftlich
(Typ 12 Subtyp 1)

// Füge eine Beschreibung des Felds ein.

*_Standardwert:_* Kein Standardwert


*_Mögliche Importwerte:_* Text

// Beschreibe das Ergebnis im Backend genauer. Dazu gehört z.B. die Angabe, in welchem Menü das Ergebnis zu finden ist.

*_Beispiel:_*

'''

[#zuordnungsfeld-rechnungsadresse]
=== Rechnungsadresse

[#zuordnungsfeld-rechnungsadresse-adress-id]
==== Adress-ID

Gib die ID der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-name1]
==== Name1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name2* und *Name3* keine Werte importierst.

Gib den Firmennamen der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-name2]
==== Name2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name3* keine Werte importierst.

Gib den Vornamen des Kontakts aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-name3]
==== Name3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name2* keine Werte importierst.

Gib den Nachnamen des Kontakts aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-name4]
==== Name4

Gib eine Zusatzangabe zum Kontakt in deine CSV-Datei ein, z.B. "z.Hd. Herrn Max Mustermann".

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-adresse1]
==== Adresse1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse2* und *Adresse3* keine Werte importierst.

Gib die Straße des Kontakts aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-adresse2]
==== Adresse2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse3* keine Werte importierst.

Gib die Hausnummer des Kontakts aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-adresse3]
==== Adresse3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse2* keine Werte importierst.

Gib einen Adresszusatz zu der Rechnungsadresse in deine CSV-Datei ein, z.B. "Apartment 12a".

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-adresse4]
==== Adresse4

Gib weitere Zusatzinformationen ein. Dieses Feld steht dir zur freien Verfügung.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-postleitzahl]
==== Postleitzahl

Gib die Postleitzahl der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-ort]
==== Ort

icon:warning[role="red"] [red]#Pflichtwert#

Gib den Ort der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-laender-id]
==== Länder-ID* (oder ISO)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-staaten-id]
==== Staaten-ID

Gib die ID der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

// Link zu den State-IDs einfügen

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-ueberprueft-am]
==== Überprüft am

Möchtest du das Datum eingeben, wann die Rechnungsadresse geprüft wurde?

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datum im Format dd.mm.yyyy

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-titel]
==== Titel

Gib den Titel aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-ansprechpartner]
==== Ansprechpartner

Gib den Ansprechpartner aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-laender-iso-code]
==== Länder-ISO-Code* (oder ID)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.


*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-rechnungsadresse-staaten-iso-code]
==== Staaten-ISO-Code

Gib den ISO-Code der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#30#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen IDs.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse]
=== Optionen der Rechnungsadresse

[#zuordnungsfeld-optionen-rechnungsadresse-umsatzsteuernummer]
==== Umsatzsteuernummer

(Typ 1)

Gib die Umsatzsteueridentifikationsnummer der Firma in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-externe-adress-id]
==== Externe Adress-ID

 (Typ 2)


Gib XXXXX der Firma in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''
[#zuordnungsfeld-optionen-rechnungsadresse-gelangensbestaetigung]
==== Gelangensbestätigung

 (Typ 3)

Um beim Versand in ein anderes Land der EU von der Umsatzsteuer befreit zu werden, müssen Händler anhand der Gelangensbestätigung nachweisen, dass die Ware aus Deutschland in einem anderen EU-Mitgliedstaat angekommen ist.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_*

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-telefon]
==== Telefon

 (Typ 4)

Gib die Telefonnummer aus der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-e-mail]
==== E-Mail

 (Typ 5)

Gib die E-Mail-Adresse der Rechnungsadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-postnummer]
==== Postnummer

 (Typ 6)

Bei der Postnummer handelt es sich um die Kundennummer von DHL. Gib die Postnummer in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-personennummer]
==== Personennummer

 (Typ 7)

Identitätsnummer in Schweden

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-fsk]
==== FSK

 (Typ 8)

Freiwillige Selbstkontrolle, Altersfreigabe

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-geburtstag]
==== Geburtstag

 (Typ 9)

Gib das Geburtsdatum aus der Rechnungsadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datumsangabe im Format dd.mm.yyyy

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-titel]
==== Titel

 (Typ 11)

Gib den Titel in der Rechnungsadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-rechnungsadresse-ansprechpartner]
==== Ansprechpartner

 (Typ 12)

Gib den Ansprechpartner in der Rechnungsadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-lieferadresse]
=== Lieferadresse

[#zuordnungsfeld-lieferadresse-adress-id]
==== Adress-ID

Gib die ID der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-name1]
==== Name1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name2* und *Name3* keine Werte importierst.

Gib den Firmennamen der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-name2]
==== Name2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name3* keine Werte importierst.

Gib den Vornamen des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-name3]
==== Name3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Name1* und *Name2* keine Werte importierst.

Gib den Nachnamen des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-name4]
==== Name4

Gib eine Zusatzangabe zum Kontakt in deine CSV-Datei ein, z.B. "z.Hd. Herrn Max Mustermann".

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-adresse1]
==== Adresse1* (oder 2/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse2* und *Adresse3* keine Werte importierst.

Gib die Straße des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-adresse2]
==== Adresse2* (oder 1/3)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse3* keine Werte importierst.

Gib die Hausnummer des Kontakts aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-adresse3]
==== Adresse3* (oder 1/2)

icon:warning[role="red"] [red]#Pflichtwert#, wenn du für  *Adresse1* und *Adresse2* keine Werte importierst.

Gib einen Adresszusatz zu der Lieferadresse in deine CSV-Datei ein, z.B. "Apartment 12a".

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-adresse4]
==== Adresse4

Gib weitere Zusatzinformationen ein. Dieses Feld steht dir zur freien Verfügung.

*_Standardwert:_* kein Standardwert


*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-postleitzahl]
==== Postleitzahl

Gib die Postleitzahl der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-ort]
==== Ort

icon:warning[role="red"] [red]#Pflichtwert#

Gib den Ort der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-laender-id]
==== Länder-ID* (oder ISO)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.


*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-staaten-id]
==== Staaten-ID

Gib die ID der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#30#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen IDs.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-ueberprueft-am]
==== Überprüft am

TEXT

[#zuordnungsfeld-lieferadresse-titel]
==== Titel

Gib den Titel aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-laender-iso-code]
==== Länder-ISO-Code* (oder ID)

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Landes oder den ISO-Code in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs und den ISO-Codes.


*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-lieferadresse-staaten-iso-code]
==== Staaten-ISO-Code

Gib den ISO-Code der Region, des Bezirks, des Bundeslands, des Kantons etc.in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#30#, Auf dieser Handbuchseite>> findest du ein Liste mit den ISO-Codes.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Adressen>>.

'''

[#zuordnungsfeld-optionen-lieferadresse]
=== Optionen der Lieferadresse

[#zuordnungsfeld-optionen-lieferadresse-umsatzsteuernummer]
==== Umsatzsteuernummer

(Typ 1)

Gib die Umsatzsteueridentifikationsnummer der Firma in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-externe-adress-id]
==== Externe Adress-ID

(Typ 2)

Gib XXXXX der Firma in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-gelangensbestaetigung]
==== Gelangensbestätigung

(Typ 3)

Um beim Versand in ein anderes Land der EU von der Umsatzsteuer befreit zu werden, müssen Händler anhand der Gelangensbestätigung nachweisen, dass die Ware aus Deutschland in einem anderen EU-Mitgliedstaat angekommen ist.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_*

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-telefon]
==== Telefon

(Typ 4)

Gib die Telefonnummer aus der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-e-mail]
==== E-Mail

(Typ 5)

Gib die E-Mail-Adresse der Lieferadresse in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-postnummer]
==== Postnummer

(Typ 6)

Bei der Postnummer handelt es sich um die Kundennummer von DHL. Gib die Postnummer in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-personennummer]
==== Personennummer

(Typ 7)

Identitätsnummer in Schweden

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-fsk]
==== FSK

(Typ 8)

Freiwillige Selbstkontrolle, Altersfreigabe

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-geburtstag]
==== Geburtstag

(Typ 9)

Gib das Geburtsdatum aus der Lieferadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Datumsangabe im Format dd.mm.yyyy

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-titel]
==== Titel

(Typ 11)

Gib den Titel in der Lieferadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-optionen-lieferadresse-ansprechpartner]
==== Ansprechpartner

(Typ 12)

Gib den Ansprechpartner in der Lieferadresse an.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-firma]
=== Firma

[#zuordnungsfeld-firma-firmen-id]
==== Firmen-ID

Gib die ID der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-nummer]
==== Nummer

Zusätzliche Nummer für die Firma. Diese Nummer kann selbst vergeben werden. Maximale Zeichenlänge: 128. Gib die ID der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-firmenname]
==== Firmenname

icon:warning[role="red"] [red]#Pflichtwert#

Gib den Namen der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-steuer-id]
==== Steuer-ID

Gib die Umsatzsteueridentifikationsnummer der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

*_Beispiel:_* Für Deutschland: DE123456789

'''

[#zuordnungsfeld-firma-valuta]
==== Valuta

Gib die Valuta der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-skonto-tage]
==== Skonto Tage

Gib die Skontofrist der Firma in Tagen in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-rabattsatz]
==== Rabattsatz

Gib den Skontosatz der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-zahlungsziel]
==== Zahlungsziel

Gib das Zahlungsziel der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-handelsvertreter-id]
==== Handelsvertreter-ID

Gib die ID des Handelsvertreters der Firma in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-eigner-id]
==== Eigner-ID

Gib die ID des Eigners in die CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-lieferzeit]
==== Lieferzeit

Gib die Lieferzeit in Tagen für den Typ *Lieferant* in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-mindestbestellwert]
==== Mindestbestellwert

Gib den Mindestbestellwert in der Systemwährung für den Typ *Lieferant* in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Firma>>.

'''

[#zuordnungsfeld-firma-lieferantenwaehrung]
==== Lieferantenwährung

TEXT

[#zuordnungsfeld-handelsvertreter]
=== Handelsvertreter

[#zuordnungsfeld-handelsvertreter-region-id]
==== Region-ID

Gib die ID der Region in deine CSV-Datei ein.

// Link zu plenty Regionen einfügen

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-handelsvertreter-plz-bereich]
==== PLZ-Bereich

Gib den Postleitzahlenbereich, in dem der Handelsvertreter tätig ist, in deine CSV-Datei ein.

// 34117-34131 ?

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

*_Beispiel:_* 34117-34131

'''

[#zuordnungsfeld-handelsvertreter-laender-id]
==== Länder-ID

Gib die ID des Landes in deine CSV-Datei ein.

[TIP]
<<daten/interne-IDs#20#, Auf dieser Handbuchseite>> findest du ein Liste mit den internen Länder-IDs.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: xxx>>.

'''

[#zuordnungsfeld-erlaubte-zahlungsarten]
=== Erlaubte Zahlungsarten


[#zuordnungsfeld-erlaubte-zahlungsarten-lastschrift-erlauben]
==== Lastschrift erlauben

Möchtest du die Zahlungsart Lastschrift für den Kontakt erlauben?

[TIP]
Die Zahlungsart muss im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* aktiviert sein.

*_Standardwert_*: `0`

[[table-mapping-contacts-allow-debit]]
[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Zahlungsart Lastschrift ist _nicht_ erlaubt.

|`1`
|Zahlungsart Lastschrift ist erlaubt.
|====

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-erlaubte-zahlungsarten-rechnung-erlauben]
==== Rechnung erlauben

Möchtest du die Zahlungsart Rechnung für den Kontakt erlauben?

[TIP]
Die Zahlungsart muss im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* aktiviert sein.

*_Standardwert_*: `0`

[[table-mapping-contacts-allow-debit]]
[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Zahlungsart Rechnung ist _nicht_ erlaubt.

|`1`
|Zahlungsart Rechnung ist erlaubt.
|====

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Details>>.

'''

[#zuordnungsfeld-eigenschaften]
=== Eigenschaften

[#zuordnungsfeld-eigenschaften-eigenschafts-id]
==== Eigenschafts-ID

Gib die ID der Eigenschaft in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

'''

[#zuordnungsfeld-eigenschaften-eigenschaftstyp]
==== Eigenschaftstyp

icon:warning[role="red"] [red]#Pflichtwert#

Gib den Eigenschaftstyp in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

[[table-mapping-fields-contacts-property-type]]
[cols="1,1"]
|===
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|Kein
|

|Ganze Zahl
|

|Auswahl
|

|Mehrfachauswahl
|

|Kurztext
|

|Text
|

|Datum
|

|Datei
|

|===


Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

'''

[#zuordnungsfeld-eigenschaften-eigenschaftswert]
==== Eigenschaftswert

Gib den Wert der Eigenschaft in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

*_Beispiel:_* Wenn du als Eigenschaftstyp *xx* gewählt hast, würde im Kontaktdatensatz z.B. xxx angezeigt werden.

'''

[#zuordnungsfeld-eigenschaften-kontakt-id]
==== Kontakt-ID

Gib die ID des Kontakts, der mit der Eigenschaft verknüpft ist, in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.
'''

[#zuordnungsfeld-eigenschaften-sprache]
==== Sprache

Gib das Sprachkürzel, z.B. *en* oder *fr* in deine CSV-Datei ein, wenn die Eigenschaft in anderen Sprachen als in der Systemsprache hinzugefügt werden soll.

[TIP]
<<daten/interne-IDs#10, Auf dieser Handbuchseite>> findest du eine Liste mit den Sprachkürzeln.

*_Standardwert:_* kein Standardwert

*_Mögliche Importwerte:_* Text

Das Ergebnis des Imports findest du im Backend im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen » Bereich: Eigenschaften>>.

'''

[#zuordnungsfeld-eigenschaften-loeschen]
==== Löschen (Ja/Nein)

Möchtest du die Eigenschaft löschen?

*_Standardwert_*: xxx?

[[table-mapping-contacts-delete-property]]
[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Eigenschaft wird _nicht_ gelöscht

|`1`
|Eigenschaft wird gelöscht
|====

'''
