= Kategorien
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Kategorien
:position: 80
:url: daten/daten-importieren/sync-typen/elasticSync-kategorien
:id: GV1MLXQ
:author: team-item

Diese Seite erläutert die Abgleich- und Zuordnungsfelder, die dir beim Importieren von Kategorien zur Verfügung stehen. Diese Seite dient lediglich als Referenz und setzt voraus, dass du bereits Grundkenntnisse über das <<daten/daten-importieren/ElasticSync#, ElasticSync-Tool>> hast.

[TIP]
.Praxisbeispiel: Neue Kategorien importieren
====
Stell dir mal vor, du bist ganz neu bei plentymarkets und möchtest alle deine Kategoriedaten auf einmal importieren. Wie geht so etwas? Wirf einen Blick auf <<daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-kategorien#, dieses praktische Beispiel>>, welches dich Schritt für Schritt durch den Prozess führt.
====

[#2110]
== Felder für den Kategorieabgleich

In <<table-matching-fields-categories>> werden Felder erläutert, die für den Abgleich von Kategoriedaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-matching-fields-categories]]
.Abgleichfelder für Kategorieimport
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Kategorie-ID*
|In welcher Spalte der CSV-Datei werden Kategorie-IDs aufgelistet? Wähle diese Spalte hier.
Diese Option ist sinnvoll, wenn du _bestehende Kategorien aktualisieren_ möchtest.

*_Hintergrund-Info_*: Jede neu angelegte Kategorie erhält automatisch eine ID, die nicht geändert werden kann.
Die ID dient zur eindeutigen Kennzeichnung der Kategorie.
Da die ID eindeutig ist, lässt sich damit gut prüfen, ob der importierte Datensatz bereits in plentymarkets vorhanden ist.

| *Kategoriename Kombiniert*
|In welcher Spalte der CSV-Datei wird der vollständige Kategoriepfad aufgeführt? Wähle diese Spalte aus der ersten Dropdown-Liste und das Trennzeichen aus der zweiten Dropdown-Liste.
Diese Option ist sinnvoll, wenn du _neue Kategorien anlegen_ möchtest.

| *Kategoriename Ebene 1 - 6*
|In welcher Spalte der CSV-Datei wird der Kategoriename für diese Ebene aufgeführt? Wähle diese Spalte hier.
|====

[#2120]
== Felder für die Kategoriezuordnung

In <<table-mapping-fields-categories>> werden Felder erläutert, die für die Zuordnung von Kategoriedaten zur Verfügung stehen.

[TIP]
.Kein Zuordnungsfeld? Standardwert greift!
====
Wenn du eine bestimmte Information nicht in deine CSV-Datei aufnimmst, d.h. wenn du ein bestimmtes Zuordnungsfeld _nicht verwendest_, dann erhält deine Kategorie den Standardwert.
====

[[table-mapping-fields-categories]]
.Zuordnungsfelder für Kategorieimport
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

4+| *Kategorie*

| *Elternkategorie ID*
|Nummerisch (interne ID)
| - k.A. -
|Wird in einer Spalte deiner CSV-Datei die ID der übergeordneten Kategorie aufgeführt? Falls ja, dann ordne die Spalte diesem Datenfeld zu.

| *Elternkategorie Name*
|Alphanummerisch
| - k.A. -
|Wird in einer Spalte deiner CSV-Datei der Name der übergeordneten Kategorie aufgeführt? Falls ja, dann ordne die Spalte diesem Datenfeld zu.

| *Typ*
|item +
container +
content +
blog
|item
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, <<artikel/einstellungen/kategorien#700, welcher Kategorietyp>> beim Import vergeben wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Typ* gesetzt wurde.

* item = Artikel (Standardeinstellung)
* container = Container
* content = Content
* blog = Blog

| *In Linkliste anzeigen*
|0 +
1
|0
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie in der Webshop-Navigation angezeigt>> wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *In Linkliste* gesetzt wurde.

* 0 = Nicht anzeigen
* 1 = Anzeigen

| *right*
|all +
customer
|all
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie nur für eingeloggte Benutzer sichtbar>> sein wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Sichtbar* gesetzt wurde.

* all = Öffentlich
* customer = Nach Login

| *Sichtbar*
|0 +
1
|0
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie in die Sitemap>> aufgenommen wird.

Mit anderen Worten: Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Sitemap* gesetzt wurde.

* 0 = Nicht anzeigen
* 1 = Anzeigen

| *Kategorie löschen*
|0 +
1
|0
a|Möchtest du einige Kategorien löschen und andere aktualisieren? Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob die Kategorie gelöscht werden soll.

* 0 = Nein
* 1 = Ja

| *Elternkategorie anlegen wenn nicht vorhanden*
|0 +
1
|0
a|Möchtest du die übergeordnete Kategorie erstellen, falls sie noch nicht existiert?
Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Elternkategorie mit erstellt werden soll.

* 0 = Nein
* 1 = Ja

4+| *Details*

| *Name* +
[red]#(Pflichtwert)#
|Alphanummerisch
| - k.A. -
|Gib den <<artikel/einstellungen/kategorien#700, Namen der Kategorie>> in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass dieser Name in das Feld *Name* eingetragen wurde.

| *Beschreibung 1*; +
*Beschreibung 2*
|Alphanummerisch
| - k.A. -
|Gib eine <<artikel/einstellungen/kategorien#800, Beschreibung der Kategorie>> in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest, siehst du, dass dieser Text im Tab *Beschreibung 1* bzw. im Tab *Beschreibung 2* eingetragen wurde.

| *Kurzbeschreibung*; +
*Meta-Keywords*; +
*Meta-Beschreibung*; +
*Meta-Titel*; +
*URL-Name*
|Alphanummerisch
|URL-Name = Kategoriename
|Gib den Text in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass dieser Text <<artikel/einstellungen/kategorien#700, in das entsprechende Feld eingetragen>> wurde.

| *Position*
|Nummerisch
|0
|Gib eine <<artikel/einstellungen/kategorien#700, Positionsnummer>> in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass diese Nummer in das Feld *Position* eingetragen wurde.

| *Template-Liste*; +
*Template-Produkt*; +
*Template-Seite* +
(nur für den alten Callisto-Webshop relevant)
|Alphanummerisch
|ItemViewCategoriesList; +
ItemViewSingleItem; +
PageDesignContent
|Gib den <<artikel/einstellungen/kategorien#700, Namen der gewünschten Vorlage>> in die CSV-Datei ein.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass diese Vorlage ausgewählt wurde.

| *Volltextsuche*
|0 +
1
|0
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie zum Suchindex der Kategoriesuche im Webshop>> hinzugefügt wird.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Volltextsuche* gesetzt wurde.

* 0 = Nein
* 1 = Ja

| *Robots*
|all +
index +
nofollow +
noindex +
nofollow_noindex
|all
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie <<artikel/einstellungen/kategorien#700, Suchmaschinen-Crawlern>> mit der Seite und den Links auf dieser Seite verfahren werden.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Robots* gesetzt wurde.

* *all* = Webseite der Kategorie in Suchmaschinenindex aufnehmen und Links auf Seite folgen. +
* *index* = In Suchmaschinenindex aufnehmen. +
* *nofollow* = Links auf der Seite nicht folgen. +
* *noindex* = Nicht in den Suchmaschinenindex aufnehmen. +
* *nofollow_noindex* = Links nicht folgen und Webseite der Kategorie nicht in Suchmaschinenindex aufnehmen.

| *Platzhalter übersetzen*
|Y +
N +
L
|Y
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob <<artikel/einstellungen/kategorien#700, Template-Variablen und -Funktionen übersetzt>> werden.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Template-Variablen und -Funktionen übersetzen* gesetzt wurde.

* Y = Ja
* N = Nein
* L = Nur Link-Template-Variablen und -Funktionen

| *Canonical*
|Alphanummerisch
| - k.A. -
|Gibt es eine andere Kategorie mit dem gleichen Inhalt? Falls ja, gib <<artikel/einstellungen/kategorien#700, die URL für diese Kategorie>> in deine CSV-Datei ein.
Die URL ist auf max. 256 Zeichen begrenzt.
Stell im Bereich *Zuordnung* auch die Sprache und den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass diese URL in das Feld *Canonical* eingetragen wurde.

4+| *Elmar*

| *Elmar-Kategorie*
|Alphanummerisch
| - k.A. -
|Gib den <<artikel/einstellungen/kategorien#700, Namen der Elmar-Kategorie>> in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass diese Elmar-Kategorie ausgewählt wurde.

| *Verknüpfung löschen*
|0 +
1
|0
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Verknüpfung der Elmar-Kategorie>> gelöscht werden soll.
Stell im Bereich *Zuordnung* auch den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass die *Elmar-Kategorie* überall dort gelöscht wurde, wo die Zahl 1 eingetragen wurde.

* 0 = Nicht löschen
* 1 = Löschen

4+| *Mandant (Shop)*

| *Aktiv*
|0 +
1
|0
a|Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die <<artikel/einstellungen/kategorien#700, Kategorie für einen bestimmten Webshop aktiviert>> werden soll.
Stell im Bereich *Zuordnung* auch den Webstore ein.

Wenn du die Kategorie nach dem Import öffnest und den Tab *Einstellungen* betrachtest, siehst du, dass einer der folgenden Werte für die Einstellung *Mandant (Shop)* gesetzt wurde.

* 0 = Für den angegebenen Mandanten _nicht aktiviert_.
* 1 = Für den angegebenen Mandanten _aktiviert_.
|====


////
[.subhead]
Beispiel 1: Preis- und Bestandsabgleich einer Variante

Mithilfe eines einfachen Syncs können Preise und Bestand einer Variante aktuell gehalten werden. Nachdem zunächst die Zuordnung im Sync vorgenommen wurde, muss ein Mapping erstellt werden. Dafür werden im Bereich Werte bestimmen des Mappings die plentymarkets Felder VariationSalesPrice und VariationStock gewählt. Nachdem die Werte bestimmt wurden, muss für VariationSalesPrice zunächst der zu aktualisierende Verkaufspreis (Preis, UVP) bestimmt werden. Es können auch mehrere Verkaufspreise mit nur einem Sync aktualisiert werden. Im nächsten Schritt wird die tatsächliche Verknüpfung mit einem Feld der Datenquelle vorgenommen. Beim Bestand kann neben dem Lager auch der Lagerort gewählt werden. Für VariationStock wird das Lager gewählt, für welches Bestand gebucht werden soll. Optional kann hier auch der Lagerort bestimmt werden. Um die Menge aus der Datenquelle zu übernehmen, muss noch das plentymarkets Feld quantity und das zugehörige Feld der Datenquelle verknüpft werden. Dabei wird immer eine Bestandskorrektur vorgenommen.

[.subhead]
Beispiel 2: Artikelbeschreibungen importieren

Für einen Artikel sollen Name, technische Daten und Meta-Keywords importiert werden. Dafür müssen zunächst diese plentymarkets Felder im Bereich Werte bestimmen des Mappings ausgewählt und übernommen werden. Für Artikelbeschreibungen wird im nächsten Schritt die Sprache gewählt. Eine Mehrfachauswahl ist möglich. Die Felder Name, Technische Daten und Meta-Keywords werden nun mit den gewünschten Feldern der Datenquelle verknüpft. Das heißt, dass die in den Datensätzen der Datenquelle vorhandenen Einträge für die zuvor gewählten plentymarkets Felder importiert werden. Zusätzlich kann der Import durch Filter weiter bestimmt oder eingegrenzt werden. So kann zum Beispiel eigestellt werden, dass die Artikelbeschreibungen nur importiert werden sollen, wenn der Artikel einer bestimmten Marke entspricht.
////
