= Plugins
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: Plugins in plentymarkets: Plugins verwalten und plentymarkets erweitern.
:position: 85

In diesem Themenbereich finden Sie alle Informationen zu Plugins. plentymarkets Plugins sind optionale Module, die Ihr plentymarkets System verändern und/oder erweitern. Diese Module können entweder von plentymarkets selbst oder von Drittanbietern zur Verfügung gestellt und auf dem plentyMarketplace gekauft werden. Plugins ermöglichen Ihnen, plentymarkets noch flexibler an Ihre Anforderungen anzupassen. In diesem Themenbereich wird erklärt, wie Sie Plugins auf dem plentyMarketplace kaufen, wie Sie Plugins installieren und bereitstellen, und welche Möglichkeiten der Individualisierung von Plugins zur Verfügung stehen.

[.row]
====
[.col-md-6]
.Plugins verwalten
=====
* <<basics/erste-schritte/plugins#10, Plugins kaufen>>
* <<basics/erste-schritte/plugins#20, Plugins installieren>>
* <<basics/erste-schritte/plugins#50, Plugins bereitstellen>>
* <<basics/erste-schritte/plugins#60, Plugins aktualisieren>>
* <<basics/erste-schritte/plugins#70, Plugins bearbeiten>>
* <<basics/erste-schritte/plugins#80, Plugins löschen>>
=====

[.col-md-6]
.Plugins entwickeln
=====
* link:https://developers.plentymarkets.com/tutorials/helloworld[Erste Schritte^]
* <<basics/erste-schritte/plugins#40, Plugins hinzufügen>>
* <<basics/erste-schritte/plugins#tabelle-stage-vs-productive, Stage vs. Productive>>
* <<basics/erste-schritte/plugins#100, Git-basierte Versionsverwaltung>>
* link:https://developers.plentymarkets.com/[plentyDevelopers^]
* link:https://help.github.com/categories/bootcamp/[GitHub Bootcamp^]
=====
====

'''
