= Plugins verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: So verwalten Sie Plugins im plentymarkets Backend.
:position: 30

Über das Menü **Plugins** verwalten und veröffentlichen Sie im link:https://marketplace.plentymarkets.com/[plentyMarketplace^] erworbene Plugins sowie selbsterstellte Plugins. Installieren Sie neue Plugins, ändern Sie den Zustand vorhandener Plugins, um sie zu veröffentlichen, und löschen Sie Plugins. Wie Sie Plugins selbst erstellen, erfahren Sie auf link:http://developers.plentymarkets.com/[plentyDevelopers^].

[NOTE]
.Ausbau der Plugin-Fähigkeit
====
Die Plugin-Fähigkeit von plentymarkets und die Bearbeitungsmöglichkeiten werden suk­zes­si­ve ausgebaut. Auch das Angebot an Plugins wird nach und nach erweitert.
====

[#10]
== Marketplace-Plugins kaufen

link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^] ist die neue Plattform für die Distribution von hauseigenen und externen plentymarkets Software-Erweiterungen. Diese Plattform ermöglicht Ihnen einen leichten Zugang zu Plugins, damit Sie schnell und einfach von allen Vorteilen profitieren. Gehen Sie wie im Folgenden beschrieben vor, um ein Plugin zu kaufen.

[.instruction]
Plugin kaufen:

. Öffnen Sie den link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^].
. Klicken Sie auf *Anmelden*.
. Geben Sie Ihre E-Mail-Adresse oder PlentyID ein. +
→ Nutzen Sie Ihre Zugangsdaten aus dem Service-Center.
. Geben Sie Ihr Passwort ein.
. Klicken Sie auf **Anmelden**.
. Wählen Sie ein Plugin aus einer Kategorie.
. Klicken Sie in der Detailansicht des Plugins auf **Plugin kaufen**. +
→ Das Fenster **Kasse** wird geöffnet.
. Nehmen Sie die Nutzungsbedingungen zur Kenntnis.
. Klicken Sie auf **Jetzt kaufen**. +
→ Das gekaufte Plugin ist im Menü **Plugins » Plugin-Übersicht** verfügbar.

[TIP]
.Filter verwenden
====
Verwenden Sie Filter, um z.B. nur *nicht installierte* Plugins in der Plugin-Übersicht anzuzeigen. Wählen Sie dazu aus der Dropdown-Liste *Installiert* den Filter *Nicht installiert*. Klicken Sie auf *Suchen*.
Weitere Informationen zu Filtern finden Sie unter <<basics/erste-schritte/plugins#80, Plugins suchen>>.
====

[#20]
== Plugin Übersicht - Plugin-Sets verwalten

Ein Plugin-Set ist eine Sammlung von verschiedenen Plugins, die für einen oder für mehrere Mandanten zentral in der *Plugin Übersicht* verwaltet werden können. Plugin-Sets können ein Plugin oder mehrere Plugins enthalten und beinhalten darüber hinaus ebenfalls die Einstellungen der Plugin-Konfiguration und Layout-Container. Plugin-Sets eignen sich insbesondere für Händler, die mehrere Webshops gleichzeitig über plentymarkets verwalten, da unterschiedliche Plugin-Sets für unterschiedliche Mandanten gesondert aktiviert und konfiguriert werden können.

[#30]
=== Plugin-Sets erstellen

[.instruction]
Plugin-Sets erstellen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin-Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin-Set ein.
. Klicken Sie auf *Von Plugin-Set kopieren*, um Einstellungen aus einem existierenden Plugin-Set zu übernehmen.
. *Speichern* Sie die Einstellungen.

[#40]
=== Plugin-Sets bearbeiten

[.instruction]
Plugin-Sets bearbeiten:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie bei einem Plugin-Set auf *Bearbeiten*. +
→ Das Fenster *Plugin-Set bearbeiten* wird geöffnet.
. Bearbeiten Sie den Namen des Plugin-Sets.
. *Speichern* Sie die Einstellungen.

[#50]
=== Plugin-Sets löschen

[.instruction]
Plugin-Sets löschen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie bei einem Plugin-Set auf *Löschen*. +
→ Das Fenster *Plugin-Set löschen* wird geöffnet.
. Bestätigen Sie die Löschung. +
→ Das Plugin-Set wird gelöscht.

[#53]
=== Plugins installieren

[.instruction]
Plugins installieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Nutzen Sie die Filterfunktion indem Sie das Kontrollkästchen *Nicht installiert* aktivieren und auf *Suchen* klicken. Möchten Sie Plugins installieren, die Sie über ein Git-Repository oder einen lokalen Speicher hinzugefügt haben, müssen Sie vor der Suche auch das Kontrollkästchen *Git* beziehungsweise *Local* auswählen.
→ Die Plugin-Übersicht wird entsprechend aktualisiert.
. Wenn Sie ein Plugin installieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Plugin installieren*. +
→ Ein Fenster zur Auswahl der zu installierenden Version öffnet sich. Wählen Sie aus dem Dropdown-Menü *Zu installierende Version* die Version des Plugins aus, die Sie installieren möchten. Standardmäßig ist die neuste Version ausgewählt. In einem Textfeld unterhalb des Dropdown-Menüs wird der Changelog der aktuell ausgewählten Version angezeigt. Wenn Sie sich für eine Version entschieden haben, klicken Sie auf die Schaltfläche *Installieren*. +
→ Das Plugin wird installiert und ist in der Plugin-Übersicht des Plugin-Sets verfügbar. Eine Ansicht mit allen installierten Plugins wird angezeigt.

[TIP]
.Urprung der Plugins
==
Der Ursprung eines Plugins kann in der Spalte *Herkunft* eingesehen werden.
==

[#54]
=== Plugins aktualisieren

[.instruction]
Plugins aktualisieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Nutzen Sie die Filterfunktion indem Sie das Kontrollkästchen *Installiert* aktivieren und klicken auf *Suchen* klicken.
→ Die Plugin-Übersicht wird entsprechend aktualisiert.
. Wenn ein Update für ein Plugin verfügbar ist, wird in der entsprechenden Zeile in der Spalte *Aktion* die Schaltfläche *Aktualisieren* farbig gekennzeichnet. Klicken Sie auf diese Schaltfläche, um das Plugin zu aktualisieren. +
→ Ein Fenster zur Auswahl der zu installierenden Version öffnet sich. Wählen Sie aus dem Dropdown-Menü *Zu installierende Version* die Version des Plugins aus, die Sie installieren möchten. Standardmäßig ist die neuste Version ausgewählt. In einem Textfeld unterhalb des Dropdown-Menüs wird der Changelog der aktuell ausgewählten Version angezeigt. Wenn Sie sich für eine Version entschieden haben, klicken Sie auf die Schaltfläche *Installieren*. +
→ Das Plugin wird aktualisiert.

[TIP]
.
==
Wenn keine neue Version für ein Plugin verfügbar ist, wird in der entsprechenden Zeile in der Spalte *Aktion* stattdessen die Schaltfläche *Keine Aktualisierung verfügbar* ausgegraut angezeigt.
==

[#55]
=== Plugins aktivieren

[.instruction]
Plugins aktivieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Nutzen Sie die Filterfunktion indem Sie die Kontrollkästchen *Installiert* und *Nicht Aktiv* aktivieren und auf *Suchen* klicken.
→ Die Plugin-Übersicht wird entsprechend aktualisiert.
. Wenn Sie ein Plugin aktivieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktiv* auf die Schaltfläche *inaktiv*. +
→ Aktive Plugins werden in Frontend und Backend geladen.

[#56]
=== Position von Plugins ändern

[.instruction]
Position von Plugins ändern:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Nutzen Sie die Filterfunktion indem Sie das Kontrollkästchen *Installiert* aktivieren und auf *Suchen* klicken.
→ Die Plugin-Übersicht wird entsprechend aktualisiert.
. Wenn Sie die Position eines Plugins verändern möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Position festlegen*. +
→ Das Fenster *Plugin-Position* öffnet sich. Geben Sie in das Textfeld die gewünschte Position des Plugins ein und klicken Sie auf *save*.
→ Die Position des Plugins wird aktualisiert.

[TIP]
.Positionsnummern der Plugins
==
Die installierten Plugins müssen in einer bestimmten Reihenfolge geladen werden, damit sämtliche Routen des Webshops korrekt aufgerufen werden. Das Plugin IO stellt die Logik für die Webshop-Routen zur Verfügung. Das Plugin erhält daher die höchste Positionsnummer und wird somit zuletzt geladen. Das Webshop-Plugin Ceres erhält eine niedrigere Position, als das Plugin IO. Das Plugin Vorkasse hat bereits die Positionsnummer 0 und damit die niedrigste Position.
==

[#57]
=== Plugins deaktivieren

[.instruction]
Plugins deaktivieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Nutzen Sie die Filterfunktion indem Sie das Kontrollkästchen *Aktiv* aktivieren und auf *Suchen* klicken.
→ Die Plugin-Übersicht wird entsprechend aktualisiert.
. Wenn Sie ein Plugin deaktivieren möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktiv* auf die Schaltfläche *aktiv*. +
→ Inaktive Plugins werden in Frontend und Backend nicht geladen.

[#59]
=== Plugins löschen

[.instruction]
Plugins löschen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das Plugin-Set, das Sie bearbeiten möchten. +
→ Der Bereich, in dem Sie das ausgewählte Plugin-Set bearbeiten können, wird geöffnet.
. Nutzen Sie die Filterfunktion indem Sie das Kontrollkästchen *Installiert* aktivieren und auf *Suchen* klicken.
→ Die Plugin-Übersicht wird entsprechend aktualisiert.
. Wenn Sie ein Plugin löschen möchten, klicken Sie in der entsprechenden Zeile in der Spalte *Aktion* auf die Schaltfläche *Löschen*. +
→ Gelöschte Plugins werden von dem Plugin-Set entfernt.

[#60]
=== Plugins als Vorschau öffnen

[.instruction]
Plugins als Vorschau öffnen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf ein Plugin-Set. +
→ Das Fenster *Plugin-Set Details* wird geöffnet.
. Klicken Sie auf *Plugin-Set Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. Das ausgewählte Plugin-Set muss zuvor über den Button *Speichern & Plugin-Set bereitstellen* bereitgestellt werden. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

[#70]
=== Plugin-Sets aktivieren

Das Aktivieren eines Plugin-Sets für einen Mandanten veröffentlicht alle Plugins im Plugin-Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin-Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es aktivieren.

[.instruction]
Plugin-Sets aktivieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Plugin-Set aktivieren*. +
→ Das Fenster *Plugin-Set aktivieren* wird geöffnet.
. Wählen Sie das Plugin-Set, das Sie in Ihrem Webshop aktivieren wollen.
. *Speichern* Sie die Einstellungen.

[#80]
=== Plugins suchen

Um gezielt nach Plugins zu suchen, kann ein Filter gesetzt werden. Es besteht die Möglichkeit, nach Name, Herkunft, installierten bzw. nicht installierten sowie aktiven bzw. nicht aktiven Plugins zu filtern.

[.instruction]
Plugins suchen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Wählen Sie einen Filter.
. Geben Sie den Namen des Plugins ein oder wählen Sie eine Option aus dem Dropdown-Menü.
. Klicken Sie auf *Suchen*. +
→ Die gewünschten Plugins werden angezeigt.

[[tabelle-plugin-uebersicht]]
.Tabellenansicht des Menüs *Plugin » Plugin-Übersicht*
[cols="1,3"]
|====
|Bezeichnung |Erläuterung

|*Neues Plugin Set erstellen*
|Öffnet ein Fenster zur Erstellung eines neuen Plugin-Sets. +
*Speichern*: Speichert das neue Plugin-Set.
*Plugin Set Name*: Der Name des Plugin-Sets.
*Plugin Set kopieren*: Wählt bestehendes Plugin-Set aus Dropdown-Menü aus, um Einstellungen zu übernehmen.

|*Plugin Set aktivieren*
|Aktiviert das ausgewählte Plugin-Set.

|Name des Plugin-Sets
|Lädt die Plugin-Übersicht des Plugin-Sets.

|*Plugin Set löschen*
|Löscht das Plugin-Set. Bestätigung notwendig.

|Filter
|*Suchen*: Lädt für das ausgewählte Plugin-Set in der Plugin-Übersicht alle Plugins, die die gewählten Filtereinstellungen erfüllen. +
*Reset*: Setzt die Filtereinstellungen auf die Standardeinstellungen zurück. +
*Name*: Filtert nach Plugins, deren Namen die eingegebene Zeichenfolge beinhaltet. +
*plentyMarketplace*: Filtert nach Plugins, die dem System über plentyMarketplace hinzugefügt wurden. +
*Git*: Filtert nach Plugins, die dem System über ein Git-Repository hinzugefügt wurden. +
*Local*: Filtert nach Plugins, die dem System über einen lokalen Speicher hinzugefügt wurden. +
*Installiert*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set installiert sind. +
*Nicht installiert*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set nicht installiert sind. +
*Aktiv*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set aktiv sind. +
*Nicht Akitv*: Filtert nach Plugins, die in dem ausgewählten Plugin-Set nicht aktiv sind.

|*Aktiv*
|Zeigt an, ob das Plugin aktiv oder inaktiv ist.

|*Name*
|Der Name des Plugins. Wenn installiert, klicken um Informationen und Einstellungsmöglichkeiten anzuzeigen.

|*Zu installierende Version*
|Die neuste Version des Plugins, die installiert ist. Ein Symbol zeigt an, wenn eine neuere Version des Plugins existiert.

|*Version aktiv*
|Die Version des Plugins, die aktiv ist und für das ausgewählte Plugin in Frontend und Backend geladen wird.

|*Herkunft*
|Die Herkunft des Plugins, also plentyMarkets, Git oder ein lokaler Speicher.

|*Aktion*
|*Plugin installieren*: Installiert das Plugin. Ein Fenster öffnet sich, in dem die zu installierende Version ausgewählt und der Changelog eingesehen werden kann. Wird nur angezeigt, wenn das Plugin nicht installiert ist. +
*Aktualisieren*: Aktualisiert das Plugin auf eine neuere Version. Ein Fenster öffnet sich, in dem die zu installierende Version ausgewählt und der Changelog eingesehen werden kann. Wird nur angezeigt, wenn eine neuere Version vorhanden ist. +
*Keine Aktualisierung verfügbar*: Die neuste Version des Plugins ist installiert. +
*Position festlegen*: Legt die Reihenfolge fest, in der Plugins geladen werden. Plugins mit niedrigerer Position werden zuerst ausgeführt. +
*Löschen*: Entfernt das Plugin aus dem Plugin-Set. Bestätigung notwendig.

|*plentyMarketplace*
|Öffnet plentyMarketplace in einem neuen Tab.
|===

[#100]
== Plugin-Set Backend Switch

Plugins können Backend-Funktionen wie Menü-Items und Benutzerinterfaces hinzufügen. Sie können das Plugin-Set ändern, das für Ihr Backend geladen wird. Um dies zu tun, müssen Sie ein Plugin-Set für Ihren Benutzer wählen.

[.instruction]
Ein Plugin-Set für Ihren Benutzer wählen:

. Klicken Sie im plentymarkets Backend oben rechts auf das Benutzersymbol.
. Klicken Sie auf *Backend Plugin-Set*. +
→ Das Fenster *Plugin-Set* wird geöffnet.
. Klicken Sie auf ein Plugin-Set.
. *Speichern* Sie die Einstellungen.

[#110]
== Eigene Git-Plugins hinzufügen

Alternativ zum plentyMarketplace können Sie der Oberfläche Ihres plentymarkets Systems auch eigene Plugins hinzufügen. Gehen Sie wie unten beschrieben vor, um ein über die <<basics/erste-schritte/plugins#90, Git-Versionierung>> verwaltetes Plugin in plentymarkets hinzuzufügen.

[.instruction]
Git-Repository zur plentymarkets Oberfläche hinzufügen:

. Öffnen Sie das Menü *Plugins » Git*.
. Klicken Sie links auf *Neues Repository hinzufügen*. +
→ Die Optionen für die Repository-Einstellungen werden angezeigt.
. Geben Sie die erforderlichen Daten für das Git-Repository ein. Beachten Sie dazu die Erläuterungen in <<tabelle-git-plugins-hinzufuegen>>.
. *Speichern* Sie die Einstellungen. +
→ Die Verbindung zum Git-Repository wird geprüft und hergestellt. Es erscheint die Meldung *Repository gespeichert*.

[[tabelle-git-plugins-hinzufuegen]]
.Git-Plugins hinzufügen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Repository URL*
|HTTPS oder HTTP URL des Git-Repositorys

|*Benutzername*
|Der Benutzername ist Bestandteil der Benutzerdaten des Anbieters (z.B. GitHub) für das Git-Repository. +
Bei öffentlichen Repositories einen Wert in das Feld eingeben, z.B. *Gast*.

|*Passwort oder Token*
|Das Passwort ist Bestandteil der Benutzerdaten des Anbieters (z.B. GitHub) für das Git-Repository. +
Bei öffentlichen Repositories einen Wert in das Feld eingeben, z.B. *Gast*. +
Ein Token wird benötigt, wenn die Zwei-Faktor-Authentifizierung beim Anbieter aktiviert wurde.

|*Branchname*
|Das Git-Repository muss eine valide Plugin.json enthalten. Die Eingabe ist für die Erstinstallation notwendig.
|====


=== Git-Repository löschen

Im Menü *Plugins » Git* können Repositories über den *Löschen*-Button gelöscht werden, wenn das Plugin in allen Sets deaktiviert wurde.
