= Plugins
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: So verwalten Sie Plugins im plentymarkets Backend.
:position: 30

Über das Menü **Plugins** verwalten und veröffentlichen Sie im link:https://marketplace.plentymarkets.com/[**plentyMarketplace**, window="_blank"] erworbene Plugins sowie selbsterstellte Plugins. Installieren Sie neue Plugins, ändern Sie den Zustand vorhandener Plugins, um sie zu veröffentlichen, und löschen Sie Plugins. Wie Sie Plugins selbst erstellen, erfahren Sie auf **link:http://developers.plentymarkets.com/[plentyDevelopers, window="_blank"]**.

[NOTE]
.Ausbau der Plugin-Fähigkeit
====
Die Plugin-Fähigkeit von plentymarkets und die Bearbeitungsmöglichkeiten werden suk­zes­si­ve ausgebaut. Auch das Angebot an Plugins wird nach und nach erweitert.
====

[#10]
== Plugins kaufen

**link:http://marketplace.plentymarkets.com/de/[plentyMarketplace, window="_blank"]** ist die neue Plattform für die Distribution von hauseigenen und externen plentymarkets Software-Erweiterungen. Diese Plattform ermöglicht Ihnen einen leichten Zugang zu Plugins, damit Sie schnell und einfach von allen Vorteilen profitieren. Gehen Sie wie im Folgenden beschrieben vor, um ein Plugin zu kaufen.

[.instruction]
Plugin kaufen:

. Öffnen Sie den **link:http://marketplace.plentymarkets.com/de/[plentyMarketplace, window="_blank"]**.
. Klicken Sie auf **Anmelden**.
. Geben Sie Ihre E-Mail-Adresse und Ihr Passwort ein. +
→ Nutzen Sie Ihre Zugangsdaten aus dem Service-Center.
. Klicken Sie auf **Anmelden**.
. Wählen Sie ein Plugin aus einer Kategorie.
. Klicken Sie in der Detailansicht des Plugins auf **Plugin kaufen**. +
→ Das Fenster **Kasse** wird geöffnet.
. Nehmen Sie die Nutzungsbedingungen zur Kenntnis.
. Klicken Sie auf **Jetzt kaufen**. +
→ Das gekaufte Plugin ist im Menü **Plugins » Einkäufe** verfügbar.

[#20]
== Plugins installieren

Nachdem Sie das Plugin im plentyMarketplace gekauft haben, ist es im Menü **Plugins » Einkäufe** verfügbar und kann dort installiert werden.

[.instruction]
Plugin installieren:

. Öffnen Sie das Menü **Plugins » Einkäufe**. +
→ Alle im plentyMarketplace erworbenen Plugins werden hier angezeigt.
. Klicken Sie in der Zeile des Plugins auf **Plugin installieren**. +
→ Das Fenster **Plugin installieren** wird geöffnet.
. Wählen Sie die Version des Plugins aus dem Dropdown-Menü. +
→ Die neueste Version des Plugins ist vorausgewählt.
.  Klicken Sie auf **Installieren**. +
→ Das Plugin wird installiert und ist in der Plugin-Übersicht verfügbar.

[#30]
== Plugins verwalten

Das Menü **Plugins » Plugin-Übersicht** zeigt eine Übersicht der Plugins in der plentymarkets Inbox. In der Kartenansicht werden die Plugins in Form von Karten dargestellt. Eine Plugin-Karte enthält folgende Informationen:

* Status
* Verfügbare Updates
* Symbol
* Name
* Version
* Quelle
* Autor

Alternativ zur Kartenansicht können Sie zur Tabellenansicht wechseln. Die folgende Tabelle erläutert die in den Spalten der Tabellenansicht gezeigten Informationen.

.Tabellenansicht des Menüs **Plugins » Plugin-Übericht**
[cols="a,a"]
|====
|Spalte |Erläuterung

|**Name**
|Name des Plugins

|**Version**
|Version des Plugins in der Inbox. Diese Version kann von der Version des in **Stage** oder **Productive** bereitgestellten Plugins abweichen. Wenn eine neue Version eines Plugin der Quelle **plentyMarketplace** zur Verfügung steht, wird der Button **Aktualisieren** eingeblendet.

|**Aktiv**
|Plugin in Stage bzw. Productive aktivieren. Aktivierte Plugins werden erst nach Klick auf **Plugins in Stage bereitstellen** bzw. **Plugins in Productive bereitstellen** im jeweiligen Modus bereitgestellt. +
Graues Symbol = Plugin ist nicht aktiv. +
Blaues Symbol = Plugin ist aktiv. Die Version des bereitgestellten Plugins wird angezeigt.

|**Stage**
|Zustand des Plugins in Stage.

|**Productive**
|Zustand des Plugins in Productive.

|**Quelle**
|Die Quelle des Plugins, z.B. **Git** oder **plentyMarketplace**.

|**Typ**
|Plugin-Typ. +
**template** = Plugins, die Routen registrieren und den Inhalt von Templates ausgeben. +
**export** = Plugins, die Exportformate für den Export von CSV-Dateien beinhalten.

|**Mandant**
|Plugin für Mandanten aktivieren. +
Auf die Lupe klicken, um die verfügbaren Mandanten anzuzeigen. +
Die Mandanten aus der Liste wählen, für die das Plugin bereitgestellt werden soll. +
→ Aktivierte Plugins werden bei der nächsten Bereitstellung für die gewählten Mandanten bereitgestellt.

|**Hinzugefügt**
|Datum, an dem das Plugin zum Menü **Plugins » Plugin-Übersicht** hinzugefügt wurde.

|**Autor**
|Autor des Plugins

|**Aktionen**
|**Löschen** = Löscht Plugins aus der Liste und der plentymarkets Inbox. +
__**Hinweis:**__ Aktive Plugins werden erst bei der nächsten Bereitstellung aus Stage/Productive gelöscht. +
**Position festlegen** = Bestimmt die Reihenfolge der Plugins in der Listenansicht und bei der Bereitstellung.
|====

[#40]
== Eigene Plugins hinzufügen

Alternativ zum plentyMarketplace können Sie der Inbox Ihres plentymarkets Systems auch eigene Plugins hinzufügen. Gehen Sie wie unten beschrieben vor, um ein über die <<basics/erste-schritte/plugins#90, **Git-Versionierung** >> verwaltetes Plugin-Repository in die plentymarkets Inbox zu kopieren und im plentymarkets Backend zu verwalten.

Fügen Sie ein Git-Repository zur plentymarkets Inbox hinzu, um von der Versionsverwaltung zu profitieren und Plugins, die über Git-Repositorys verwaltet werden, bereitzustellen. Gehen Sie wie unten beschrieben vor.

[.instruction]
Git-Repository zur plentymarkets Inbox hinzufügen:

. Öffnen Sie das Menü **Plugins » Git**.
. Klicken Sie auf **New plugin**. +
→ Das Fenster **Settings** wird angezeigt.
. Geben Sie die Zugangsdaten für das Git-Repository ein. Beachten Sie Tabelle 2.
. Klicken Sie auf **Test connection**. +
→ Die Verbindung zum Git-Repository wird geprüft und hergestellt.
. Wählen Sie den Branch des Repositorys aus dem Dropdown-Menü.
. Klicken Sie auf **Save**, um die Einstellungen zu speichern. +
→ Das Plugin-Repository wird in die plentymarkets Inbox kopiert und in der Plugin-Übersicht angezeigt. +
→ Das Plugin wird im Menü **Git** angezeigt.

[#45]

.Git-Plugins hinzufügen
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Remote URL**
|Die URL des Git-Repositorys eingeben.

|**User name**
|Benutzernamen eingeben. Der Benutzername ist Bestandteil der Benutzerdaten des Hosting-Anbieters (z.B. GitHub) für das Git-Repository. Diese Benutzerdaten sind nur für das Hinzufügen von privaten Repositorys notwendig. Bei öffentlichen Repositorys einen Wert in das Feld eingeben, z.B. **Gast**.

|**Password**
|Passwort eingeben. Das Passwort ist Bestandteil der Benutzerdaten des Hosting-Anbieters (z.B. GitHub) für das Git-Repository.  Diese Benutzerdaten sind nur für das Hinzufügen von privaten Repositorys notwendig. Bei öffentlichen Repositorys einen Wert in das Feld eingeben, z.B. **Gast**.

|**Test connection**
|Verbindung zum Git-Repository prüfen und herstellen.

|**Branch**
|Erst wählbar, nachdem die Verbindung zum Git-Repository über **Test connection** geprüft wurde. Den Branch wählen, von dem eine Kopie in der plentymarkets Inbox erstellt werden soll.

|**Auto fetch**
|Aktivieren, um Änderungen automatisch abzurufen, die in das Git-Repository gepusht werden. Die Änderungen werden abgerufen, jedoch nur in der Commit-Liste angezeigt, nicht gemergt. +
__**Hinweis**__: Die Autofetch-Funktion kann leichte Performance-Einbußen verursachen.
|====

[#50]
== Plugins bereitstellen

Plugins werden von der Inbox des Menüs **Plugins » Plugin-Übersicht** aus in Stage bzw. Productive getrennt bereitgestellt. Dabei entspricht Stage einem Vorschaumodus. Bei der Bereitstellung in Stage werden alle Plugins bereitgestellt, die für den Modus Stage aktiviert wurden. Bei der Bereitstellung in Productive werden alle Plugins bereitgestellt, die für den Modus Productive aktiviert wurden. Plugins, die in Productive bereitgestellt werden, sind ggf. für Ihre Kunden und Anwender sichtbar. Die folgende Tabelle verdeutlicht das Konzept von Stage und Productive.

[#55]

.Stage vs. Productive
[cols="a,a"]
|====
|Modus |Erläuterung

|**Stage**
|Stage entspricht einem Vorschaumodus. Stellen Sie Plugins in Stage bereit, um ihr Verhalten und ggf. die von Ihnen daran vorgenommenen Anpassungen zu testen, bevor Sie sie in Productive bereitstellen und so veröffentlichen. Der Stage-Modus wird für die Plugin-Entwicklung empfohlen. Ressourcen des Plugins, z.B. Bilder oder CSS-Dateien, werden direkt geladen und vorgenommene Anpassungen werden sofort nach dem Bereitstellen angezeigt.

|**Productive**
|In Productive bereitgestellte Plugins werden für die gewählten Mandanten veröffentlicht. Das bedeutet, dass sie in Ihrem Produktivsystem verwendet werden und ggf. für Ihre Kunden sichtbar sind. Daher sollten Sie Plugins ausgiebig testen, bevor Sie sie in Productive bereitstellen.
|====

Eine Bereitstellung der Plugins ist in folgenden Fällen erforderlich:

* Neue Plugins wurden hinzugefügt.
* Plugins wurden aktiviert.
* Plugins wurden aktualisiert.
* Plugins wurden bearbeitet.
* Plugins wurden deaktiviert.
* Fehler wurden behoben.

[WARNING]
.Lese- und Schreibrechte von in Stage bereitgestellten Plugins auf die Datenbank
====
In Stage bereitgestellte Plugins befinden sich im Vorschaumodus, können aber mit den entsprechenden Berechtigungen auf Daten in der Datenbank des produktiven plentymarkets Systems zugreifen, Daten verändern oder sogar löschen. Beachten Sie, dass auch Änderungen am Plugin in Stage zu Datenverlust im Live-System führen können.
====

Gehen Sie wie unten beschrieben vor, um die Plugins bereitzustellen. Tabelle 4 erläutert die erforderlichen Optionen der Menüleiste.

[.instruction]
Plugins in Stage bereitstellen:

. Öffnen Sie das Menü **Plugins » Plugin-Übersicht**.
. Aktivieren bzw. deaktivieren Sie die gewünschten Plugins für den Modus **Stage**. +
→ Noch nicht bereitgestellte Änderungen werden in der Menüleiste hervorgehoben.
. Zeigen Sie mit der Maus auf den Button **Mehr**. +
→ Das Kontextmenü wird geöffnet.
. Klicken Sie auf **Mandanten wählen**. +
→ Das Fenster **Mandanten wählen** wird geöffnet.
. Aktivieren Sie die Mandanten.
. **Speichern** Sie die Einstellungen. +
→ Die aktivierten Mandanten werden verknüpft.
. Klicken Sie in der Menüleiste auf **Plugins in Stage bereitstellen**. +
→ Die aktivierten Plugins werden geprüft und die Bereitstellung wird gestartet. +
→ Das Symbol in Stage bereitgestellter Plugins wird grün angezeigt.

[.instruction]
Plugins in Productive bereitstellen:

. Öffnen Sie das Menü **Plugins » Plugin-Übersicht**.
. Aktivieren bzw. deaktivieren Sie die gewünschten Plugins für den Modus **Productive**. +
→ Noch nicht bereitgestellte Änderungen werden in der Menüleiste hervorgehoben.
. Zeigen Sie mit der Maus auf den Button **Mehr**. +
→ Das Kontextmenü wird geöffnet.
. Klicken Sie auf **Mandanten wählen**. +
→ Das Fenster **Mandanten wählen** wird geöffnet.
. Aktivieren Sie die Mandanten.
. **Speichern** Sie die Einstellungen. +
→ Die aktivierten Mandanten werden verknüpft.
. Klicken Sie in der Menüleiste auf **Plugins in Productive bereitstellen**. +
→ Die aktivierten Plugins werden geprüft und die Bereitstellung wird gestartet. +
→ Das Symbol in Productive bereitgestellter Plugins wird grün angezeigt.

.Bereitstellungsoptionen der Menüleiste
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Zur Tabellenansicht wechseln; +
Zur Kartenansicht wechseln**
|Klicken, um zwischen Kartenansicht und Tabellenansicht zu wechseln.

|**Plugins in Stage bereitstellen**
|Prüft alle aktivierten Plugins und stellt sie dann im Vorschaumodus **Stage** bereit. In diesem Modus wird eine Vorschau der aktiven Plugins bereitgestellt und ihre Funktion kann getestet werden. Noch nicht bereitgestellte Änderungen werden gelb hervorgehoben. +
**__Hinweis__**: Bei der Bereitstellung werden alle aktivierten Plugins nacheinander für Stage kompiliert. Dieser Vorgang kann einige Minuten dauern. Bei Fehlern wird keines der Plugins bereitgestellt.

|**Plugin-Log (Stage)**
|Übersicht der Bereitstellungsvorgänge der Plugins in Stage. Fehlgeschlagene Vorgänge werden farblich hervorgehoben. Aufgetretene Fehler beim letzten Bereitstellungsvorgang werden in einer Liste angezeigt.

|Plugins in Productive bereitstellen
|Prüft alle Plugins und stellt sie dann im produktiven Modus **Productive** bereit. In diesem Modus werden die aktiven Plugins ausgeführt und veröffentlicht. Noch nicht bereitgestellte Änderungen werden gelb hervorgehoben. +
**__Hinweis__**: Bei der Bereitstellung werden alle aktivierten Plugins nacheinander für Productive kompiliert. Dieser Vorgang kann einige Minuten dauern. Bei Fehlern wird keines der Plugins bereitgestellt.

|**Plugin-Log (Productive)**
|Übersicht der Bereitstellungsvorgänge der Plugins in Productive. Fehlgeschlagene Vorgänge werden farblich hervorgehoben. Aufgetretene Fehler beim letzten Bereitstellungsvorgang werden in einer Liste angezeigt.

|**Zu Stage wechseln; +
Zu Productive wechseln**
|**Zu Stage wechseln** = Vom Produktivmodus Productive in den Vorschaumodus Stage wechseln. Alle in Stage bereitgestellten Plugins werden beim Aufrufen der URL des Webshops angezeigt. Die Plugins sind nur für die Benutzer Ihres plentymarkets Systems sichtbar. Der Modus wird nach 120 Minuten automatisch wieder auf Productive gestellt. +
**__Wichtig:__** Bereitgestellte Plugins wechseln zwar in den Vorschaumodus, die Datenbank wird aber nicht gewechselt. Mit den entsprechenden Berechtigungen können diese Plugins auf Daten in der Datenbank des Produktivsystems zugreifen, Daten verändern oder sogar löschen. +
**Zu Productive wechseln** = Modus von Stage zurück in Productive wechseln.

|**Automatisch bereitstellen**
|Aktivieren, um Plugins bei Aktualisierung automatisch in **Stage** bereitzustellen. Plugins müssen bereits in **Stage** aktiv sein.
|====

[#60]
== Plugins aktualisieren

Plugin-Aktualisierungen werden sowohl im plentyMarketplace als auch im plentymarkets Backend angezeigt. Neue verfügbare Versionen werden die Markierung **Plugin aktualisieren** in der rechten oberen Ecke einer Plugin-Karte in der Plugin-Übersicht angezeigt. Um eine neue Version eines im plentyMarketplace erworbenen Plugins zu installieren, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Plugin aktualisieren:

. Öffnen Sie das Menü **Plugins » Plugin-Übersicht**.
. Zeigen Sie mit der Maus auf den Button **Mehr**. +
→ Das Kontextmenü wird geöffnet.
. Klicken Sie auf **Plugin aktualisieren**. +
→ Das Fenster **Plugin aktualisieren** wird geöffnet.
. Wählen Sie die Version aus dem Dropdown-Menü.
. Klicken Sie auf **Plugin aktualisieren**. +
→ Das Plugin wird auf die neue Version aktualisiert.

[NOTE]
.Keine Aktualisierung auf ältere Version
====
Bei einer Plugin-Aktualisierung können Sie nur eine neuere Version des Plugins installieren. Um das Plugin auf eine ältere Version zurückzusetzen, löschen Sie das Plugin zunächst und installieren es mit der gewünschten Version erneut.
====

[#70]
== Plugins bearbeiten

Die Dateien eines Plugins können direkt in der plentymarkets Inbox bearbeitet werden. Welche Dateien bearbeitbar sind, hängt von der Art des Plugins ab. Gehen Sie wie unten beschrieben vor, um Plugin-Dateien zu bearbeiten.

[IMPORTANT]
.Anwender ohne Programmier- bzw. Layout-Erfahrung
====
Bearbeiten Sie als Anwender ohne Programmier- bzw. Layout-Erfahrung die Plugin-Dateien nicht selbst. Wenden Sie sich stattdessen an einen unserer zertifizierten Dienstleister.
====

[.instruction]
Plugins bearbeiten:

. Öffnen Sie das Menü **Plugins » Plugin-Übersicht**.
. Doppelklicken Sie auf das Plugin. +
→ Die Plugin-Detailansicht wird geöffnet, in der die Plugin-Dateien bearbeitet werden können.
. Nehmen Sie die Änderungen vor.
. **Speichern** Sie die Änderungen.
. Bei Plugins, die mit einem Git-Repository verknüpft sind, pushen Sie die Änderungen über das Menü **Git**.
. Stellen Sie aktive Plugins erneut bereit, um die Änderungen zu veröffentlichen.

[#80]
== Plugins löschen

Löschen Sie Plugins, die weder in Stage noch in Productive aktiv sind. Gehen Sie wie unten beschrieben vor, um ein nicht mehr benötigtes Plugin zu löschen.

[.instruction]
Plugins löschen:

. Öffnen Sie das Menü **Plugins » Plugin-Übersicht**.
. Prüfen Sie den Zustand des Plugins in Stage und Productive.
. Zeigen Sie mit der Maus auf den Button **Mehr**. +
→ Das Kontextmenü wird geöffnet.
. Klicken Sie auf **Plugin löschen**. +
→ Das Fenster **Plugin löschen** wird geöffnet.
. Klicken Sie auf **Plugin löschen**. +
→ Das Plugin wird aus der Liste entfernt. +
→ Die Plugin-Dateien werden aus der plentymarkets Inbox gelöscht. +
→ Ist das Plugin mit einem Git-Repository verknüpft, wird das Repository aus der Liste im Menü **Git** entfernt.

[#90]
== Plugin-Log aufrufen

Im Plugin-Log finden Sie eine Historie über Bereitstellungsvorgänge Ihrer Plugins. Jeder Vorgang wird einzeln aufgezeichnet. Im Falle einer fehlgeschlagenen Bereitstellung finden Sie unter **Ergebnis** detaillierte Informationen über den letzten Vorgang. Die Plugin-Logs für den Vorschaumodus **Stage** und den Produktivmodus **Productive** werden getrennt voneinander aufgezeichnet.

[.instruction]
Plugin-Log aufrufen:

. Öffnen Sie das Menü **Plugins » Plugin-Übersicht**.
. Klicken Sie auf **Plugin-Log (Stage)** bzw. **Plugin-Log (Productive)**. +
→ Das Plugin-Log wird geöffnet.
. Klicken Sie in der Zeile des letzten Vorgangs auf den Button **Mehr**. +
→ Die Detailansicht des Logs wird geöffnet.

[#100]
== Git-basierte Versionsverwaltung

Zur Versionsverwaltung von Plugins steht Ihnen im Menü **Plugins » Git** ein einfacher Git-Client zur Verfügung. Die plentymarkets Versionsverwaltung basiert auf dem verteilten Versionsverwaltungssystem **link:https://git-scm.com/[Git, window="_blank"]**. Sie ermöglicht es, Änderungen, die Sie oder andere Nutzer an Plugin-Dateien vornehmen, über ein Git-Repository zu verwalten.

Die Versionsverwaltung bietet folgende Vorteile:

* Protokollierung: Änderungen werden in Commits protokolliert und können jederzeit nachvollzogen werden.
* Wiederherstellung: Jeder Stand jeder Datei kann wiederhergestellt werden. Änderungen können also jederzeit rückgängig gemacht werden.
* Zusammenarbeit: Mehrere Anwender können gemeinsam an einem Repository arbeiten.
* Fehlersuche: Fehler sind leichter nachvollziehbar und korrigierbar.

[TIP]
.Englischsprachige Benutzeroberfläche
====
Viele plentymarkets Anwender sind mit anderen Git-Clients mit englischsprachiger Benutzeroberfläche vertraut. Daher ist das Menü **Plugins » Git** derzeit nur auf Englisch verfügbar. Die Terminologie orientiert sich an GitHub. Definitionen finden Sie z.B. im **link:https://help.github.com/articles/github-glossary/[GitHub-Glossar, window="_blank"]**.
====

[#110]
=== Workflow-Beispiel

Wenn Sie noch nicht mit Git oder einer ähnlichen verteilten Versionsverwaltung gearbeitet haben, machen Sie sich zunächst mit den grundlegenden Konzepten vertraut. Einen sinnvollen Einstieg bietet z.B. das **link:https://help.github.com/categories/bootcamp/[GitHub Bootcamp, window="_blank"]**. Um Ihnen den Einstieg in die Versionsverwaltung in plentymarkets zu erleichtern, wird nachfolgend ein grundlegender Workflow mit Git beschrieben, der als Grundlage für Ihre eigenen Arbeitsabläufe dienen kann.

. Git-Repository erstellen.
. Lokale Kopie des Git-Repositorys auf der Festplatte ablegen.
. Dateien lokal bearbeiten. Dabei ggf. Änderungen anderer Anwender regelmäßig aus dem Git-Repository in die Versionshistorie Ihres lokalen Repositorys kopieren.
. Lokale Änderungen in das Git-Repository pushen.
. Git-Repository über das Menü **Plugins » Git** in die plentymarkets Inbox kopieren.
. Plugin über die plentymarkets Inbox in Stage bereitstellen.
. Plugin in Stage testen.
. Plugin ggf. lokal anpassen und Vorgang wiederholen.
. Fertiges Plugin in Productive bereitstellen.

[#120]
=== Inbox-Repository aktualisieren

Gehen Sie wie unten beschrieben vor, um die aktuellste Version des Git-Repositorys entweder über **Fetch** oder **Pull** in ihr Inbox-Repository zu kopieren.

[.instruction]
Git-Repository in Inbox-Repository kopieren:

. Öffnen Sie das Menü **Plugins » Git**.
. Klicken Sie auf das gewünschte Repository.
. Klicken Sie entweder auf **Fetch** oder auf **Pull**. Beachten Sie Tabelle 5. +
→ Die neuen Commits werden in der Commit-Liste angezeigt.

.Fetch vs. Pull
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Fetch**
|Ruft die neuesten Commits vom Git-Repository ab und speichert sie, ohne sie zu mergen. Der aktuelle Stand der Repository-Dateien in der Inbox ändert sich nicht. Noch nicht committete Änderungen werden nicht überschrieben.

|**Pull**
|Synchronisiert das Inbox-Repository mit dem Git-Repository. Der Stand der Repository-Dateien in der Inbox wird mit dem aktuellen Stand des Git-Repositorys überschrieben. Änderungen am Inbox-Repository, die noch nicht ins Git-Repository gepusht wurden, werden nach einer Sicherheitsabfrage überschrieben.
|====

[#130]
=== Commit-Informationen aufrufen

In der Commit-Liste eines Repositorys des Menüs **Plugins » Git** werden Informationen zu bisher ausgeführten Commits angezeigt. Der Commit, auf dessen Stand sich das Repository aktuell befindet, ist mit einem Häkchen gekennzeichnet. Die folgende Tabelle erläutert die Ansicht.

.Git-Verwaltung
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Fetch**
|Ruft Commits von Git-Repository ab, ohne sie in das Inbox-Repository zu mergen.

|**Pull**
|Ruft Commits von Git-Repository ab und mergt sie direkt in das Inbox-Repository.

|**Pull to Stage**
|Ruft Commits von Git-Repository ab, mergt sie direkt in das Inbox-Repository und startet die Bereitstellung in Stage.

|**Pull to Productive**
|Ruft Commits von Git-Repository ab, mergt sie direkt in das Inbox-Repository und startet die Bereitstellung in Productive.

|**Push**
|Veröffentlicht die Änderungen, die im Inbox-Repository vorgenommen wurden, im Git-Repository.

|**Settings**
|<<basics/erste-schritte/plugins#45, **Verbindungseinstellungen** >> des Repositorys

|**Uncommitted changes**
|Nur sichtbar, wenn Änderungen am Inbox-Repository vorgenommen, aber noch nicht gepusht wurden.

|**Description**
|Commit-Message, die für den Commit eingegeben wurde.

|**ID**
|ID des Commits. Wird automatisch vom System vergeben und ist nicht änderbar.

|**Information**
|Detaillierte Commit-Informationen: +
**Author** = Name des Commit-Autors. +
**__Tipp:__** Optional E-Mail-Adresse des Autors mit **link:https://en.gravatar.com/[Gravatar, window="_blank"]** verknüpfen. Bei Autoren ohne Gravatar wird rechts das Gravatar-Logo angezeigt. +
**Commit-ID** = ID des Commits. Wird automatisch vom System vergeben und ist nicht änderbar. +
**Parent-ID** = ID des Vorgänger-Commits, d.h. des Commits, der bearbeitet wurde, um diesen Commit zu erzielen. +
**Description** = Vollständige Commit-Message.

|**Author**
|Name des Nutzers, der den Commit ins Git-Repository gespeichert hat. Entspricht dem beim Git-basierten Versionsverwaltungssystem (z.B. GitHub, Bitbucket) hinterlegten Benutzername. +

|**Datum**
|Datum, an dem der Commit in das Git-Repository gemergt wurde.

|**Files**
|Zeigt die Dateien an, die in diesem Commit geändert wurden. Auf den Dateinamen klicken, um rechts die Änderungen anzuzeigen. +
Rot = Löschungen +
Grün = Hinzufügungen +
Wurde mehr als eine Datei geändert, in der **File**-Liste auf eine andere Datei klicken, um die Änderungen an dieser Datei anzuzeigen.
|====

[#140]
=== Inbox-Repository auf einen anderen Commit setzen

In Ihrer Inbox befinden sich sämtliche Versionen des Repositorys, die über einen Commit gespeichert wurden. Sie haben die Möglichkeit, die Inbox-Dateien eines Repositorys auf den Stand eines beliebigen Commits der Commit-Liste zu setzen. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Inbox-Repository auf einen anderen Commit setzen:

. Öffnen Sie das Menü **Plugins » Git**.
. Klicken Sie auf das gewünschte Repository. +
→ Den Commit, auf dessen Stand sich das Repository aktuell befindet, erkennen Sie an dem Häkchen. +
→ Eine Liste aller Commits des Repositorys wird angezeigt.
. Klicken Sie auf den Commit, auf den Sie Ihr Inbox-Repository setzen möchten. +
→ Im Bereich **File** links unten wird eine Liste der in diesem Commit geänderten Dateien angezeigt. Rechts unten werden die in der Datei vorgenommenen Änderungen angezeigt. Wurde mehr als eine Datei geändert, klicken Sie in der **File**-Liste auf eine andere Datei, um die Änderungen darin anzuzeigen.
. Klicken Sie mit der rechten Maustaste auf den Commit.
. Klicken Sie auf **Set to selected commit** (Auf gewählten Commit setzen). +
→ Die Dateien des Inbox-Repositorys werden auf den Stand dieser Version gesetzt.
. Stellen Sie die Plugins in Stage bzw. Productive neu bereit.
