= Plugins
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: So verwalten Sie Plugins im plentymarkets Backend.
:position: 30

Über das Menü **Plugins** verwalten und veröffentlichen Sie im link:https://marketplace.plentymarkets.com/[plentyMarketplace^] erworbene Plugins sowie selbsterstellte Plugins. Installieren Sie neue Plugins, ändern Sie den Zustand vorhandener Plugins, um sie zu veröffentlichen, und löschen Sie Plugins. Wie Sie Plugins selbst erstellen, erfahren Sie auf link:http://developers.plentymarkets.com/[plentyDevelopers^].

[NOTE]
.Ausbau der Plugin-Fähigkeit
====
Die Plugin-Fähigkeit von plentymarkets und die Bearbeitungsmöglichkeiten werden suk­zes­si­ve ausgebaut. Auch das Angebot an Plugins wird nach und nach erweitert.
====

[#10]
== Plugins kaufen

link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^] ist die neue Plattform für die Distribution von hauseigenen und externen plentymarkets Software-Erweiterungen. Diese Plattform ermöglicht Ihnen einen leichten Zugang zu Plugins, damit Sie schnell und einfach von allen Vorteilen profitieren. Gehen Sie wie im Folgenden beschrieben vor, um ein Plugin zu kaufen.

[.instruction]
Plugin kaufen:

. Öffnen Sie den link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^].
. Klicken Sie auf *Anmelden*.
. Geben Sie Ihre E-Mail-Adresse oder PlentyID ein. +
→ Nutzen Sie Ihre Zugangsdaten aus dem Service-Center.
. Geben Sie Ihr Passwort ein.
. Klicken Sie auf **Anmelden**.
. Wählen Sie ein Plugin aus einer Kategorie.
. Klicken Sie in der Detailansicht des Plugins auf **Plugin kaufen**. +
→ Das Fenster **Kasse** wird geöffnet.
. Nehmen Sie die Nutzungsbedingungen zur Kenntnis.
. Klicken Sie auf **Jetzt kaufen**. +
→ Das gekaufte Plugin ist im Menü **Plugins » Plugin-Übersicht** verfügbar.

[TIP]
.Filter verwenden
====
Verwenden Sie Filter, um z.B. nur *nicht installierte* Plugins in der Plugin-Übersicht anzuzeigen. Wählen Sie dazu aus der Dropdown-Liste *Installiert* den Filter *Nicht installiert*. Klicken Sie auf *Suchen*.
Weitere Informationen zu Filtern finden Sie unter <<basics/erste-schritte/plugins#80, Plugins suchen>>.
====

[#20]
== Plugin Sets verwalten

Ein Plugin Set ist eine Sammlung von verschiedenen Plugins, die für einen oder für mehrere Mandanten zentral in der *Plugin Übersicht* verwaltet werden können. Plugin Sets können ein Plugin oder mehrere Plugins enthalten und beinhalten darüber hinaus ebenfalls die Einstellungen der Plugin-Konfiguration und Layout-Container. Plugin Sets eignen sich insbesondere für Händler, die mehrere Webshops gleichzeitig über plentymarkets verwalten, da unterschiedliche Plugin Sets für unterschiedliche Mandanten gesondert aktiviert und konfiguriert werden können.

[#30]
=== Plugin Sets erstellen

[.instruction]
Plugin Sets erstellen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin Set ein.
. Klicken Sie auf *Von Plugin Set kopieren*, um Einstellungen aus einem existierenden Plugin Set zu übernehmen.
. *Speichern* Sie die Einstellungen.

[#40]
=== Plugin Sets bearbeiten

[.instruction]
Plugin Sets bearbeiten:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie bei einem Plugin Set auf *Bearbeiten*. +
→ Das Fenster *Plugin Set bearbeiten* wird geöffnet.
. Bearbeiten Sie den Namen des Plugin Sets.
. *Speichern* Sie die Einstellungen.

[#50]
=== Plugin Sets löschen

[.instruction]
Plugin Sets löschen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie bei einem Plugin Set auf *Löschen*. +
→ Das Fenster *Plugin Set löschen* wird geöffnet.
. Bestätigen Sie die Löschung. +
→ Das Plugin Set wird gelöscht.

[#60]
=== Plugins als Vorschau öffnen

[.instruction]
Plugins als Vorschau öffnen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf ein Plugin Set. +
→ Das Fenster *Plugin Set Details* wird geöffnet.
. Klicken Sie auf *Plugin Set Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. Das ausgewählte Plugin Set muss zuvor über den Button *Speichern & Plugin Set bereitstellen* bereitgestellt werden. +
→ Der gewählte Webshop wird mit dem gewählten Plugin Set in einem neuen Browser-Tab geöffnet.

[#70]
=== Plugin Sets aktivieren

Das Aktivieren eines Plugin Sets für einen Mandanten veröffentlicht alle Plugins im Plugin Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es aktivieren.

[.instruction]
Plugin Sets aktivieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Plugin Set aktivieren*. +
→ Das Fenster *Plugin Set aktivieren* wird geöffnet.
. Wählen Sie das Plugin Set, das Sie in Ihrem Webshop aktivieren wollen.
. *Speichern* Sie die Einstellungen.

[#80]
== Plugins suchen

Um gezielt nach Plugins zu suchen, kann ein Filter gesetzt werden. Es besteht die Möglichkeit, nach Name, Herkunft, installierten bzw. nicht installierten sowie aktiven bzw. nicht aktiven Plugins zu filtern.

[.instruction]
Plugins suchen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Wählen Sie einen Filter.
. Geben Sie den Namen des Plugins ein oder wählen Sie eine Option aus dem Dropdown-Menü.
. Klicken Sie auf *Suchen*. +
→ Die gewünschten Plugins werden angezeigt.

[#90]
== Plugins verwalten

Klicken Sie in *Plugins » Plugin-Übersicht* auf das Plugin Set, das Sie verwalten möchten. +
Die Plugins, die in der Übersicht aufgeführt sind, enthalten die folgenden Informationen:

[[tabelle-plugin-uebersicht]]
.Tabellenansicht des Menüs *Plugins » Plugin-Übersicht*
[cols="1,3"]
|====
|Spalte |Erläuterung

|*Aktiv*
|Zeigt an, ob das Plugin aktiv oder inaktiv ist.

|*Name*
|Name des Plugins

|*Version installiert*
|Die Version des Plugins ist installiert, aber nicht aktiv.

|*Version aktiv*
|Die Version des Plugins ist aktiv und wird im Frontend und im Backend geladen.

|*Herkunft*
|Die Herkunft des Plugins, z.B. *Git* oder *plentyMarketplace*.

|*Aktion*
|*Update*: Wenn ein Update vorhanden ist, können Sie das Plugin auf die neueste Version updaten. +
 *Position*: Legen Sie fest, in welcher Reihenfolge die Plugins geladen werden sollen. Sollte ein Plugin nicht richtig funktionieren, kann es helfen, die Position auf eine höhere Zahl zu ändern. +
 *Löschen*: Das Plugin vom Plugin Set löschen. +
 *Installieren*: Installiert das Plugin.
|====

[#100]
== Plugin Set Backend Switch

Plugins können Backend-Funktionen wie Menü-Items und Benutzerinterfaces hinzufügen. Sie können das Plugin Set ändern, das für Ihr Backend geladen wird. Um dies zu tun, müssen Sie ein Plugin Set für Ihren Benutzer wählen.

[.instruction]
Ein Plugin Set für Ihren Benutzer wählen:

. Klicken Sie im plentymarkets Backend oben rechts auf das Benutzersymbol.
. Klicken Sie auf *Backend Plugin Set*. +
→ Das Fenster *Plugin Set* wird geöffnet.
. Klicken Sie auf ein Plugin Set.
. *Speichern* Sie die Einstellungen.

[#110]
== Eigene Plugins hinzufügen

Alternativ zum plentyMarketplace können Sie der Inbox Ihres plentymarkets Systems auch eigene Plugins hinzufügen. Gehen Sie wie unten beschrieben vor, um ein über die <<basics/erste-schritte/plugins#90, Git-Versionierung>> verwaltetes Plugin-Repository in die plentymarkets Inbox zu kopieren und im plentymarkets Backend zu verwalten.

Fügen Sie ein Git-Repository zur plentymarkets Inbox hinzu, um von der Versionsverwaltung zu profitieren und Plugins, die über Git-Repositorys verwaltet werden, bereitzustellen. Gehen Sie wie unten beschrieben vor.

[.instruction]
Git-Repository zur plentymarkets Inbox hinzufügen:

. Öffnen Sie das Menü **Plugins » Git**.
. Klicken Sie auf **New plugin**. +
→ Das Fenster **Settings** wird angezeigt.
. Geben Sie die Zugangsdaten für das Git-Repository ein. Beachten Sie <<tabelle-git-plugin>>.
. Klicken Sie auf **Test connection**. +
→ Die Verbindung zum Git-Repository wird geprüft und hergestellt.
. Wählen Sie den Branch des Repositorys aus der Dropdown-Liste.
. *Speicher* Sie die Einstellungen. +
→ Das Plugin-Repository wird in die plentymarkets Inbox kopiert und in der Plugin-Übersicht angezeigt. +
→ Das Plugin wird im Menü **Git** angezeigt.

[[tabelle-git-plugin]]
.Git-Plugins hinzufügen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Remote URL**
|Die URL des Git-Repositorys eingeben.

|**User name**
|Benutzernamen eingeben. Der Benutzername ist Bestandteil der Benutzerdaten des Hosting-Anbieters (z.B. GitHub) für das Git-Repository. Diese Benutzerdaten sind nur für das Hinzufügen von privaten Repositorys notwendig. Bei öffentlichen Repositorys einen Wert in das Feld eingeben, z.B. **Gast**.

|**Password**
|Passwort eingeben. Das Passwort ist Bestandteil der Benutzerdaten des Hosting-Anbieters (z.B. GitHub) für das Git-Repository.  Diese Benutzerdaten sind nur für das Hinzufügen von privaten Repositorys notwendig. Bei öffentlichen Repositorys einen Wert in das Feld eingeben, z.B. **Gast**.

|**Test connection**
|Verbindung zum Git-Repository prüfen und herstellen.

|**Branch (veraltet)**
|Erst wählbar, nachdem die Verbindung zum Git-Repository über **Test connection** geprüft wurde. Den Branch wählen, von dem eine Kopie in der plentymarkets Inbox erstellt werden soll.

|**Auto fetch**
|Aktivieren, um Änderungen automatisch abzurufen, die in das Git-Repository gepusht werden. Die Änderungen werden abgerufen, jedoch nur in der Commit-Liste angezeigt, nicht gemergt. +
__**Hinweis**__: Die Autofetch-Funktion kann leichte Performance-Einbußen verursachen.
|====

[#120]
== Plugins bearbeiten

Die Dateien eines Plugins können direkt in der plentymarkets Inbox bearbeitet werden. Welche Dateien bearbeitbar sind, hängt von der Art des Plugins ab. Gehen Sie wie unten beschrieben vor, um Plugin-Dateien zu bearbeiten.

[IMPORTANT]
.Anwender ohne Programmier- bzw. Layout-Erfahrung
====
Bearbeiten Sie als Anwender ohne Programmier- bzw. Layout-Erfahrung die Plugin-Dateien nicht selbst. Wenden Sie sich stattdessen an einen unserer zertifizierten Dienstleister.
====

[.instruction]
Plugins bearbeiten:

. Öffnen Sie das Menü **Plugins » Plugin-Übersicht**.
. Doppelklicken Sie auf das Plugin. +
→ Die Plugin-Detailansicht wird geöffnet, in der die Plugin-Dateien bearbeitet werden können.
. Nehmen Sie die Änderungen vor.
. **Speichern** Sie die Änderungen.
. Bei Plugins, die mit einem Git-Repository verknüpft sind, pushen Sie die Änderungen über das Menü **Git**.
. Stellen Sie aktive Plugins erneut bereit, um die Änderungen zu veröffentlichen.

[#130]
== Plugin-Log aufrufen

Im Plugin-Log finden Sie eine Historie über Bereitstellungsvorgänge Ihrer Plugins. Jeder Vorgang wird einzeln aufgezeichnet. Im Falle einer fehlgeschlagenen Bereitstellung finden Sie unter **Ergebnis** detaillierte Informationen über den letzten Vorgang.

[.instruction]
Plugin-Log aufrufen:

. Öffnen Sie das Menü **Daten » Log**.
. Wählen Sie *Plenty\Modules\Plugin\Commands\BuildPlugins* aus der *Integration* Dropdown-Liste +
→ Die Detailansicht des Logs wird geöffnet.

[#140]
== Git-basierte Versionsverwaltung

Zur Versionsverwaltung von Plugins steht Ihnen im Menü **Plugins » Git** ein einfacher Git-Client zur Verfügung. Die plentymarkets Versionsverwaltung basiert auf dem verteilten Versionsverwaltungssystem link:https://git-scm.com/[Git^]. Sie ermöglicht es, Änderungen, die Sie oder andere Nutzer an Plugin-Dateien vornehmen, über ein Git-Repository zu verwalten.

Die Versionsverwaltung bietet folgende Vorteile:

* Protokollierung: Änderungen werden in Commits protokolliert und können jederzeit nachvollzogen werden.
* Wiederherstellung: Jeder Stand jeder Datei kann wiederhergestellt werden. Änderungen können also jederzeit rückgängig gemacht werden.
* Zusammenarbeit: Mehrere Anwender können gemeinsam an einem Repository arbeiten.
* Fehlersuche: Fehler sind leichter nachvollziehbar und korrigierbar.

[TIP]
.Englischsprachige Benutzeroberfläche
====
Viele plentymarkets Anwender sind mit anderen Git-Clients mit englischsprachiger Benutzeroberfläche vertraut. Daher ist das Menü **Plugins » Git** derzeit nur auf Englisch verfügbar. Die Terminologie orientiert sich an GitHub. Definitionen finden Sie z.B. im link:https://help.github.com/articles/github-glossary/[GitHub-Glossar^].
====

[#150]
=== Workflow-Beispiel

Wenn Sie noch nicht mit Git oder einer ähnlichen verteilten Versionsverwaltung gearbeitet haben, machen Sie sich zunächst mit den grundlegenden Konzepten vertraut. Einen sinnvollen Einstieg bietet z.B. das link:https://help.github.com/categories/bootcamp/[GitHub Bootcamp^]. Um Ihnen den Einstieg in die Versionsverwaltung in plentymarkets zu erleichtern, wird nachfolgend ein grundlegender Workflow mit Git beschrieben, der als Grundlage für Ihre eigenen Arbeitsabläufe dienen kann.

. Git-Repository erstellen.
. Lokale Kopie des Git-Repositorys auf der Festplatte ablegen.
. Dateien lokal bearbeiten. Dabei ggf. Änderungen anderer Anwender regelmäßig aus dem Git-Repository in die Versionshistorie Ihres lokalen Repositorys kopieren.
. Lokale Änderungen in das Git-Repository pushen.
. Git-Repository über das Menü **Plugins » Git** in die plentymarkets Inbox kopieren.
. Plugin in der Plugin-Übersicht installieren.
. Plugin ggf. lokal anpassen und Vorgang wiederholen.
. Fertiges Plugin aktivieren.

[#160]
=== Inbox-Repository aktualisieren

Gehen Sie wie unten beschrieben vor, um die aktuellste Version des Git-Repositorys entweder über **Fetch** oder **Pull** in ihr Inbox-Repository zu kopieren.

[.instruction]
Git-Repository in Inbox-Repository kopieren:

. Öffnen Sie das Menü **Plugins » Git**.
. Klicken Sie auf das gewünschte Repository.
. Klicken Sie entweder auf **Fetch** oder auf **Pull**. Beachten Sie <<tabelle-fetch-pull>>. +
→ Die neuen Commits werden in der Commit-Liste angezeigt.

[[tabelle-fetch-pull]]
.Fetch vs. Pull
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Fetch**
|Ruft die neuesten Commits vom Git-Repository ab und speichert sie, ohne sie zu mergen. Der aktuelle Stand der Repository-Dateien in der Inbox ändert sich nicht. Noch nicht committete Änderungen werden nicht überschrieben.

|**Pull**
|Synchronisiert das Inbox-Repository mit dem Git-Repository. Der Stand der Repository-Dateien in der Inbox wird mit dem aktuellen Stand des Git-Repositorys überschrieben. Änderungen am Inbox-Repository, die noch nicht ins Git-Repository gepusht wurden, werden nach einer Sicherheitsabfrage überschrieben.
|====

[#170]
=== Commit-Informationen aufrufen

In der Commit-Liste eines Repositorys des Menüs **Plugins » Git** werden Informationen zu bisher ausgeführten Commits angezeigt. Der Commit, auf dessen Stand sich das Repository aktuell befindet, ist mit einem Häkchen gekennzeichnet. <<tabelle-git-verwaltung>> erläutert die Ansicht.

[[tabelle-git-verwaltung]]
.Git-Verwaltung
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Fetch**
|Ruft Commits von Git-Repository ab, ohne sie in das Inbox-Repository zu mergen.

|**Pull**
|Ruft Commits von Git-Repository ab und mergt sie direkt in das Inbox-Repository.

|**Pull to Stage**
|Veraltet

|**Pull to Productive**
|Veraltet

|**Push**
|Veröffentlicht die Änderungen, die im Inbox-Repository vorgenommen wurden, im Git-Repository.

|**Settings**
|<<basics/erste-schritte/plugins#tabelle-git-plugin, Verbindungseinstellungen>> des Repositorys

|**Uncommitted changes**
|Nur sichtbar, wenn Änderungen am Inbox-Repository vorgenommen, aber noch nicht gepusht wurden.

|**Description**
|Commit-Message, die für den Commit eingegeben wurde.

|**ID**
|ID des Commits. Wird automatisch vom System vergeben und ist nicht änderbar.

|**Information**
|Detaillierte Commit-Informationen: +
**Author** = Name des Commit-Autors. +
**__Tipp:__** Optional E-Mail-Adresse des Autors mit link:https://en.gravatar.com/[Gravatar^] verknüpfen. Bei Autoren ohne Gravatar wird rechts das Gravatar-Logo angezeigt. +
**Commit-ID** = ID des Commits. Wird automatisch vom System vergeben und ist nicht änderbar. +
**Parent-ID** = ID des Vorgänger-Commits, d.h. des Commits, der bearbeitet wurde, um diesen Commit zu erzielen. +
**Description** = Vollständige Commit-Message.

|**Author**
|Name des Nutzers, der den Commit ins Git-Repository gespeichert hat. Entspricht dem beim Git-basierten Versionsverwaltungssystem (z.B. GitHub, Bitbucket) hinterlegten Benutzername. +

|**Datum**
|Datum, an dem der Commit in das Git-Repository gemergt wurde.

|**Files**
|Zeigt die Dateien an, die in diesem Commit geändert wurden. Auf den Dateinamen klicken, um rechts die Änderungen anzuzeigen. +
Rot = Löschungen +
Grün = Hinzufügungen +
Wurde mehr als eine Datei geändert, in der **File**-Liste auf eine andere Datei klicken, um die Änderungen an dieser Datei anzuzeigen.
|====

[#180]
=== Inbox-Repository auf einen anderen Commit setzen

In Ihrer Inbox befinden sich sämtliche Versionen des Repositorys, die über einen Commit gespeichert wurden. Sie haben die Möglichkeit, die Inbox-Dateien eines Repositorys auf den Stand eines beliebigen Commits der Commit-Liste zu setzen. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Inbox-Repository auf einen anderen Commit setzen:

. Öffnen Sie das Menü **Plugins » Git**.
. Klicken Sie auf das gewünschte Repository. +
→ Den Commit, auf dessen Stand sich das Repository aktuell befindet, erkennen Sie an dem Häkchen. +
→ Eine Liste aller Commits des Repositorys wird angezeigt.
. Klicken Sie auf den Commit, auf den Sie Ihr Inbox-Repository setzen möchten. +
→ Im Bereich **File** links unten wird eine Liste der in diesem Commit geänderten Dateien angezeigt. Rechts unten werden die in der Datei vorgenommenen Änderungen angezeigt. Wurde mehr als eine Datei geändert, klicken Sie in der **File**-Liste auf eine andere Datei, um die Änderungen darin anzuzeigen.
. Klicken Sie mit der rechten Maustaste auf den Commit.
. Klicken Sie auf **Set to selected commit** (Auf gewählten Commit setzen). +
→ Die Dateien des Inbox-Repositorys werden auf den Stand dieser Version gesetzt.
. Stellen Sie die Plugins neu bereit.
