= Plugins
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plugins, Erweiterungen, Funktionen
:description: So verwalten Sie Plugins im plentymarkets Backend.
:position: 30

Über das Menü **Plugins** verwalten und veröffentlichen Sie im link:https://marketplace.plentymarkets.com/[plentyMarketplace^] erworbene Plugins sowie selbsterstellte Plugins. Installieren Sie neue Plugins, ändern Sie den Zustand vorhandener Plugins, um sie zu veröffentlichen, und löschen Sie Plugins. Wie Sie Plugins selbst erstellen, erfahren Sie auf link:http://developers.plentymarkets.com/[plentyDevelopers^].

[NOTE]
.Ausbau der Plugin-Fähigkeit
====
Die Plugin-Fähigkeit von plentymarkets und die Bearbeitungsmöglichkeiten werden suk­zes­si­ve ausgebaut. Auch das Angebot an Plugins wird nach und nach erweitert.
====

[#10]
== Marketplace-Plugins kaufen

link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^] ist die neue Plattform für die Distribution von hauseigenen und externen plentymarkets Software-Erweiterungen. Diese Plattform ermöglicht Ihnen einen leichten Zugang zu Plugins, damit Sie schnell und einfach von allen Vorteilen profitieren. Gehen Sie wie im Folgenden beschrieben vor, um ein Plugin zu kaufen.

[.instruction]
Plugin kaufen:

. Öffnen Sie den link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^].
. Klicken Sie auf *Anmelden*.
. Geben Sie Ihre E-Mail-Adresse oder PlentyID ein. +
→ Nutzen Sie Ihre Zugangsdaten aus dem Service-Center.
. Geben Sie Ihr Passwort ein.
. Klicken Sie auf **Anmelden**.
. Wählen Sie ein Plugin aus einer Kategorie.
. Klicken Sie in der Detailansicht des Plugins auf **Plugin kaufen**. +
→ Das Fenster **Kasse** wird geöffnet.
. Nehmen Sie die Nutzungsbedingungen zur Kenntnis.
. Klicken Sie auf **Jetzt kaufen**. +
→ Das gekaufte Plugin ist im Menü **Plugins » Plugin-Übersicht** verfügbar.

[TIP]
.Filter verwenden
====
Verwenden Sie Filter, um z.B. nur *nicht installierte* Plugins in der Plugin-Übersicht anzuzeigen. Wählen Sie dazu aus der Dropdown-Liste *Installiert* den Filter *Nicht installiert*. Klicken Sie auf *Suchen*.
Weitere Informationen zu Filtern finden Sie unter <<basics/erste-schritte/plugins#80, Plugins suchen>>.
====

[#20]
== Plugin Übersicht - Plugin Sets verwalten

Ein Plugin Set ist eine Sammlung von verschiedenen Plugins, die für einen oder für mehrere Mandanten zentral in der *Plugin Übersicht* verwaltet werden können. Plugin Sets können ein Plugin oder mehrere Plugins enthalten und beinhalten darüber hinaus ebenfalls die Einstellungen der Plugin-Konfiguration und Layout-Container. Plugin Sets eignen sich insbesondere für Händler, die mehrere Webshops gleichzeitig über plentymarkets verwalten, da unterschiedliche Plugin Sets für unterschiedliche Mandanten gesondert aktiviert und konfiguriert werden können.

[#30]
=== Plugin Sets erstellen

[.instruction]
Plugin Sets erstellen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Plugin Set erstellen* wird geöffnet.
. Geben Sie einen Namen für das Plugin Set ein.
. Klicken Sie auf *Von Plugin Set kopieren*, um Einstellungen aus einem existierenden Plugin Set zu übernehmen.
. *Speichern* Sie die Einstellungen.

[#40]
=== Plugin Sets bearbeiten

[.instruction]
Plugin Sets bearbeiten:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie bei einem Plugin Set auf *Bearbeiten*. +
→ Das Fenster *Plugin Set bearbeiten* wird geöffnet.
. Bearbeiten Sie den Namen des Plugin Sets.
. *Speichern* Sie die Einstellungen.

[#50]
=== Plugin Sets löschen

[.instruction]
Plugin Sets löschen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie bei einem Plugin Set auf *Löschen*. +
→ Das Fenster *Plugin Set löschen* wird geöffnet.
. Bestätigen Sie die Löschung. +
→ Das Plugin Set wird gelöscht.

[#60]
=== Plugins als Vorschau öffnen

[.instruction]
Plugins als Vorschau öffnen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf ein Plugin Set. +
→ Das Fenster *Plugin Set Details* wird geöffnet.
. Klicken Sie auf *Plugin Set Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. Das ausgewählte Plugin Set muss zuvor über den Button *Speichern & Plugin Set bereitstellen* bereitgestellt werden. +
→ Der gewählte Webshop wird mit dem gewählten Plugin Set in einem neuen Browser-Tab geöffnet.

[#70]
=== Plugin Sets aktivieren

Das Aktivieren eines Plugin Sets für einen Mandanten veröffentlicht alle Plugins im Plugin Set. Dies geschieht mit sofortiger Wirkung. Testen Sie das Plugin Set ausgiebig und sehen Sie sich die Vorschau an, bevor Sie es aktivieren.

[.instruction]
Plugin Sets aktivieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf *Plugin Set aktivieren*. +
→ Das Fenster *Plugin Set aktivieren* wird geöffnet.
. Wählen Sie das Plugin Set, das Sie in Ihrem Webshop aktivieren wollen.
. *Speichern* Sie die Einstellungen.

[#80]
=== Plugins suchen

Um gezielt nach Plugins zu suchen, kann ein Filter gesetzt werden. Es besteht die Möglichkeit, nach Name, Herkunft, installierten bzw. nicht installierten sowie aktiven bzw. nicht aktiven Plugins zu filtern.

[.instruction]
Plugins suchen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Wählen Sie einen Filter.
. Geben Sie den Namen des Plugins ein oder wählen Sie eine Option aus dem Dropdown-Menü.
. Klicken Sie auf *Suchen*. +
→ Die gewünschten Plugins werden angezeigt.

[#90]
=== Plugins verwalten

Klicken Sie in *Plugins » Plugin-Übersicht* auf das Plugin Set, das Sie verwalten möchten. +
Die Plugins, die in der Übersicht aufgeführt sind, enthalten die folgenden Informationen:

[[tabelle-plugin-uebersicht]]
.Tabellenansicht des Menüs *Plugins » Plugin-Übersicht*
[cols="1,3"]
|====
|Spalte |Erläuterung

|*Aktiv*
|Zeigt an, ob das Plugin aktiv oder inaktiv ist.

|*Name*
|Name des Plugins

|*Version installiert*
|Die Version des Plugins ist installiert, aber nicht aktiv.

|*Version aktiv*
|Die Version des Plugins ist aktiv und wird im Frontend und im Backend geladen.

|*Herkunft*
|Die Herkunft des Plugins, z.B. *Git* oder *plentyMarketplace*.

|*Aktion*
|*Update*: Wenn ein Update vorhanden ist, können Sie das Plugin auf die neueste Version updaten. +
 *Position*: Legen Sie fest, in welcher Reihenfolge die Plugins geladen werden sollen. Sollte ein Plugin nicht richtig funktionieren, kann es helfen, die Position auf eine höhere Zahl zu ändern. +
 *Löschen*: Das Plugin vom Plugin Set löschen. +
 *Installieren*: Installiert das Plugin.
|====

[#100]
== Plugin Set Backend Switch

Plugins können Backend-Funktionen wie Menü-Items und Benutzerinterfaces hinzufügen. Sie können das Plugin Set ändern, das für Ihr Backend geladen wird. Um dies zu tun, müssen Sie ein Plugin Set für Ihren Benutzer wählen.

[.instruction]
Ein Plugin Set für Ihren Benutzer wählen:

. Klicken Sie im plentymarkets Backend oben rechts auf das Benutzersymbol.
. Klicken Sie auf *Backend Plugin Set*. +
→ Das Fenster *Plugin Set* wird geöffnet.
. Klicken Sie auf ein Plugin Set.
. *Speichern* Sie die Einstellungen.

[#110]
== Eigene Git-Plugins hinzufügen

Alternativ zum plentyMarketplace können Sie der Oberfläche Ihres plentymarkets Systems auch eigene Plugins hinzufügen. Gehen Sie wie unten beschrieben vor, um ein über die <<basics/erste-schritte/plugins#90, Git-Versionierung>> verwaltetes Plugin in plentymarkets hinzuzufügen.

[.instruction]
Git-Repository zur plentymarkets Oberfläche hinzufügen:

. Öffnen Sie das Menü *Plugins » Git*.
. Klicken Sie links auf *Neues Repository hinzufügen*. +
→ Die Optionen für die Repository-Einstellungen werden angezeigt.
. Geben Sie die erforderlichen Daten für das Git-Repository ein. Beachten Sie dazu die Erläuterungen in <<tabelle-git-plugins-hinzufügen>>.
. *Speichern* Sie die Einstellungen. +
→ Die Verbindung zum Git-Repository wird geprüft und hergestellt. Es erscheint die Meldung *Repository gespeichert*.

[[tabelle-git-plugins]]
.Git-Plugins hinzufügen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Repository URL*
|HTTPS oder HTTP URL des Git-Repositorys

|*Benutzername*
|Der Benutzername ist Bestandteil der Benutzerdaten des Anbieters (z.B. GitHub) für das Git-Repository. +
Bei öffentlichen Repositories einen Wert in das Feld eingeben, z.B. *Gast*.

|*Passwort oder Token*
|Das Passwort ist Bestandteil der Benutzerdaten des Anbieters (z.B. GitHub) für das Git-Repository. +
Bei öffentlichen Repositories einen Wert in das Feld eingeben, z.B. *Gast*. +
Ein Token wird benötigt, wenn die Zwei-Faktor-Authentifizierung beim Anbieter aktiviert wurde.

|*Branchname*
|Das Git-Repository muss eine valide Plugin.json enthalten. Die Eingabe ist für die Erstinstallation notwendig.
|====


=== Git-Repository löschen

Im Menü *Plugins » Git* können Repositories über den *Löschen*-Button gelöscht werden, wenn das Plugin in allen Sets deaktiviert wurde.
