= Systemvoraussetzungen
:lang: de
include::{includedir}/_header.adoc[]
:position: 10

Auf dieser Seite erfahren Sie welche Voraussetzungen Ihr PC und Ihre Internetverbindung erfüllen müssen, damit Sie plentymarkets nutzen können.

==  Vorausgesetzte Hardware, Betriebssysteme und Browser

Die folgenden Angaben geben Mindeststandards wieder, um mit plentymarkets optimal arbeiten zu können. Wenn Sie die angegebenen Werte unterschreiten, müssen Sie mit einer eingeschränkten Performance bis hin zu technischen Problemen, aufgrund mangelnder Kompatibilität, rechnen. Wenn Sie außerdem sehr alte Hardware oder einen schlecht gewarteten PC nutzen, sind dauerhafte Leistungsprobleme möglich. Die Angaben beziehen sich auf plentymarkets Systeme ab plentymarkets 6.

[cols="a,a"]
|====
| |Voraussetzung

|**Prozessor**
|2 x 2 GHz +
Bei Rechnern mit Windows-Betriebssystem mindestens Intel Core 2

|**Arbeitsspeicher**
|4 GB

|**Monitorauflösung**
|1280 x 720

|**Internetverbindung**
|permante Verbindung über DSL mit einer Datenübertragungsrate von 1000 kB und mehr +
**Hinweis:** Die Bandbreite sollte immer im Verhältnis zur Anzahl der Nutzer stehen.
|====

__Tab. 1: Generelle NutzungsVoraussetzungen__

=== plentymarkets im Browserbetrieb nutzen

Die folgende Tabelle enthält Vorraussetzungen, die Sie bei der Verwendung von plentymarkets in einem Browser, beachten müssen. Wenn Sie die hier angegebenen Werte unterschreiten, sind Einschränkungen möglich. Zusätzlich gelten die in Tablle 1 aufgeführten Angaben.

[cols=""]
|====
| | Voraussetzung

|**Betriebssystem**
a| 64-Bit
*  Windows 7 und höher
*  Mac OS X 10.10 und höher
*  Linux

**Info:** Wenn Sie andere Betriebssysteme, Server-Betriebssysteme oder virtuelle Maschinen nutzen, sind Einschränkungen möglich.

|**Browser**
a|
* link:http://www.google.com/chrome/[**Google Chrome**, window="_blank"] Version 46 oder höher
* link:http://www.mozilla.com/[**Mozilla Firefox**, window="_blank"] Version 43 oder höher
* link:http://www.apple.com/de/safari/[**Apple Safari**, window="_blank"] Version 9

|====

__Tab. 2: Voraussetzungen für den Browserbetrieb__

Die Browservoraussetzungen gelten nicht für Ihre Kunden. Ihre Kunden können jederzeit mit einem W3C-konformen Browser in Ihrem Shop einkaufen.

=== plentymarkets Client nutzen

Wenn Sie den plentymarkets Client nutzen, sollten Sie die folgenden Voraussetzungen erfüllen, neben den in Tabelle 1 aufgeführten Voraussetzungen.

[cols=""]
|====
| | Voraussetzung

|**Betriebssystem**
a|
*  Windows 7 und höher
*  Mac OS X 10.10 und höher

**Info:** Wenn Sie Linux nutzen, ist die Verwendung des plenymarkets Client nicht möglich. +
**Info:** Wenn Sie andere Betriebssysteme, Server-Betriebssysteme oder virtuelle Maschinen nutzen, sind Einschränkungen möglich.
|====

__Tab. 3: Voraussetzungen für die Nutzung des plentymarkets Client__

=== plentymarkets App nutzen

Welche Hardware die plentymarkets App unterstützt, finden Sie hier in der Tabelle.

[cols=""]
|====
| | Voraussetzung

|**Betriebssystem**
a|
*  Android-Geräte mit OS-Version 4.2.2 oder höher
*  iOS-Geräte mit Version 8 oder höher

|====

__Tab. 4: Voraussetzungen für die Nutzung der plentymarkets App__

== Probleme beheben

Wenn Sie Probleme bei der Nutzung von plentymarkets haben, können folgende Punkte Ursache dafür sein:

*  Ihr Browser ist nicht aktuell. Prüfen Sie die Version Ihres Browsers und ob es eine neuere gibt.
*  Ihre CPU ist ausgelastet. Wenn Ihre CPU durch den Regelbetrieb bereits voll ausgelastet ist, schließen Sie nicht benötigte Programme.
*  Ihr Arbeitsspeicher ist zu klein. Prüfen Sie die Größe Ihres Arbeitsspeichers. Wir empfehlen eine Mindestgröße von 4 GB.
*  Ihr Java-Version ist nicht aktuell. Prüfen Sie die installierte Java-Version und ob es eine neuere gibt. Installieren Sie die aktuelle Version.
*  Ihre Festplatte ist zu mehr als 70% mit Daten belegt und wurde seit Jahren nicht mehr ausgetauscht. Je nach Betriebssystem und Qualität der Hardware sind ab einer Laufzeit von mehr als zwei Jahren deutliche Leistungseinbußen feststellbar. Löschen Sie unnötige Dateien oder setzen Sie das System direkt neu auf. Eine aktuelle und leistungsfähige Festplatte/SSD wäre ebenfalls eine kostengünstige Option.

Fragen stellen oder Probleme melden können Sie jederzeit im link:https://forum.plentymarkets.com/[**Forum**, window="_blank"].
