= Systemvoraussetzungen
:lang: de
include::{includedir}/_header.adoc[]
:position: 10

Auf dieser Seite erfahren Sie, welche Voraussetzungen Ihr PC und Ihre Internetverbindung erfüllen müssen, damit Sie plentymarkets nutzen können.

==  Vorausgesetzte Hardware, Betriebssysteme und Browser

Die folgenden Angaben geben Mindeststandards wieder, um mit plentymarkets optimal arbeiten zu können. Wenn Sie die angegebenen Werte unterschreiten, müssen Sie mit einer eingeschränkten Performance bis hin zu technischen Problemen, aufgrund mangelnder Kompatibilität, rechnen. Wenn Sie außerdem sehr alte Hardware oder einen schlecht gewarteten PC nutzen, sind dauerhafte Leistungsprobleme möglich. Die Angaben beziehen sich auf plentymarkets Systeme ab plentymarkets 6.

[[tabelle-generelle-voraussetzungen]]
.Generelle Nutzungsvoraussetzungen
[cols="a,a"]
|====
| |Voraussetzung

|**Prozessor**
|2 x 2 GHz +
Bei Rechnern mit Windows-Betriebssystem mindestens Intel Core 2

|**Arbeitsspeicher**
|6 GB

|**Monitorauflösung**
|1280 x 720

|**Internetverbindung**
|permanente Verbindung über DSL mit einer Datenübertragungsrate von 1000 kB und mehr +
**__Hinweis:__** Die Bandbreite sollte immer im Verhältnis zur Anzahl der Nutzer stehen.
|====

=== plentymarkets im Browser-Betrieb nutzen

Die folgende Tabelle enthält Vorraussetzungen, die Sie bei der Verwendung von plentymarkets in einem Browser beachten müssen. Wenn Sie die hier angegebenen Werte unterschreiten, sind Einschränkungen möglich. Zusätzlich gelten die in <<tabelle-generelle-voraussetzungen>> aufgeführten Angaben.

[[tabelle-voraussetzungen-browser-betrieb]]
.Voraussetzungen für den Browser-Betrieb
[cols=""]
|====
| | Voraussetzung

|**Betriebssystem**
a| * 64-Bit
*  Windows 7 und höher
*  Mac OS X 10.10 und höher
*  Linux

Wenn Sie andere Betriebssysteme, Server-Betriebssysteme oder virtuelle Maschinen nutzen, sind Einschränkungen möglich.

|**Browser**
a|
* link:http://www.google.com/chrome/[Google Chrome^] Version 46 oder höher
* link:http://www.mozilla.com/[Mozilla Firefox^] Version 43 oder höher

|====

Die Browservoraussetzungen gelten nicht für Ihre Kunden. Ihre Kunden können jederzeit mit einem W3C-konformen Browser in Ihrem Shop einkaufen.

=== plentymarkets Client nutzen

Wenn Sie den plentymarkets Client nutzen, sollten Sie die folgenden Voraussetzungen erfüllen neben den in <<tabelle-generelle-voraussetzungen>> aufgeführten Voraussetzungen.

[[tabelle-voraussetzungen-client]]
.Voraussetzungen für die Nutzung des plentymarkets Client
[cols=""]
|====
| | Voraussetzung

|**Betriebssystem**
a|
*  Windows 7 und höher
*  Mac OS X 10.10 und höher

Wenn Sie Linux nutzen, ist die Verwendung des plentymarkets Client nicht möglich. Wenn Sie andere Betriebssysteme, Server-Betriebssysteme oder virtuelle Maschinen nutzen, sind Einschränkungen möglich.
|====

=== plentymarkets App nutzen

Die plentymarkets App bietet umfassende Funktionen für das Abrufen von Kennzahlen sowie für die Kunden-, Artikel- und Auftragssuche. Für diese Funktionen benötigen Sie ein mobiles Android- oder iOS-Gerät. Die plentymarkets App stellt außerdem Funktionen für die mobile Warenwirtschaft sowie das Kassensystem plentymarkets POS bereit. Hier erfahren Sie, welche Hardware Sie benötigen, um diese Funktionen zu nutzen.

==== Geschäftsdaten mit der plentymarkets App verwalten

<<tabelle-voraussetzungen-plenty-app>> erläutert die Hardware-Voraussetzungen für die plentymarkets App zum Abrufen von Kennzahlen und Geschäftsdaten.

[[tabelle-voraussetzungen-plenty-app]]
.Voraussetzungen für die Nutzung der plentymarkets App
[cols=""]
|====
|Voraussetzungen |App-Download

|Android-Geräte mit OS-Version 4.2.2 oder höher
|link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=de[plentymarkets App bei Google Play^]

|iOS-Geräte mit Version 8 oder höher
|link:https://itunes.apple.com/de/app/plentymarkets/id957702618[plentymarkets App bei iTunes^]
|====

==== Warenbestand mit der plentymarkets App verwalten

Für die Warenwirtschaft mit der plentymarkets App empfehlen wir die folgende Hardware:

.Warenwirtschaft mit der plentymarkets App
[cols="1,2"]
|====
|Hardware |Bezugsquelle

|HM3 SM10 Mobile Computer +
(Android 5.1)
|link:https://www.sundsits.de/M3SM10[www.sundsits.de/M3SM10^] +

SundS ITS +
Beselerstr. 2-6 +
50354 Hürth +
info@sundsits.de +
Tel.: +49(0)2233-7064010 +
Fax: +49(0)2233-7064011 +
link:https://www.sundsits.de[www.sundsits.de^]

|Honeywell Dolphin 75e +
(Android 4.4.4)
|link:http://www.globos.de/produkte/honeywell-dolphin-75e-mobilecomputer[www.globos.de/produkte/honeywell-dolphin-75e-mobilecomputer^]

GLOBOS Logistik- und Informationssysteme GmbH +
Ahrensburger Straße 1 +
30659 Hannover +
vertrieb@globos.de +
Tel.: +49 (511) 76920-0 +
Fax: +49 (511) 76920-250 +
link:http://www.globos.de[www.globos.de^]
|====

==== Kassensystem plentymarkets POS nutzen

Das Kassensystem plentymarkets POS wird über die plentymarkets App bereitgestellt. Beachten Sie jedoch, dass für den Einsatz von plentymarkets POS zusätzliche Hardware-Voraussetzungen bestehen. Weitere Informationen finden Sie auf der Handbuchseite <<omni-channel/pos/pos-einrichten#10, POS einrichten>>.

== Probleme beheben

Wenn Sie Probleme bei der Nutzung von plentymarkets haben, können folgende Punkte Ursache dafür sein:

*  Ihr Browser ist nicht aktuell. Prüfen Sie die Version Ihres Browsers und ob es eine neuere gibt.
*  Ihre CPU ist ausgelastet. Wenn Ihre CPU durch den Regelbetrieb bereits voll ausgelastet ist, schließen Sie nicht benötigte Programme.
*  Ihr Arbeitsspeicher ist zu klein. Prüfen Sie die Größe Ihres Arbeitsspeichers. Wir empfehlen eine Mindestgröße von 4 GB.
*  Ihr Java-Version ist nicht aktuell. Prüfen Sie die installierte Java-Version und ob es eine neuere gibt. Installieren Sie die aktuelle Version.
*  Ihre Festplatte ist zu mehr als 70% mit Daten belegt und wurde seit Jahren nicht mehr ausgetauscht. Je nach Betriebssystem und Qualität der Hardware sind ab einer Laufzeit von mehr als zwei Jahren deutliche Leistungseinbußen feststellbar. Löschen Sie unnötige Dateien oder setzen Sie das System direkt neu auf. Eine aktuelle und leistungsfähige Festplatte/SSD wäre ebenfalls eine kostengünstige Option.

Fragen stellen oder Probleme melden können Sie jederzeit im link:https://forum.plentymarkets.com/[Forum^].
