= Orders
:lang: en
include::{includedir}/_header.adoc[]
:position: 10

**Orders**

== Content of this chapter

An order is created in plentymarkets for every new incoming order from a market or your online store. Orders can be generated from your __**online store**__ or are imported from other __**markets**__ such as eBay, Amazon or Yatego. All orders have the same format and are collected in the **Orders** menu. You can either list all of the orders or use various filter settings to only view specific orders. Each order receives an individual and unique **order ID**. Along with normal orders (the customer purchases items), plentymarkets can also handle various other __**types of orders**__ that help you deal with typical e-commerce processes, e.g. credit notes, returns, etc.

== Processing orders in plentymarkets

Use the **Orders** menu to manage current orders, incoming payments and shipments. plentymarkets distinguishes between the following types of orders:

* The **order** is the most common type (customer purchases item).
* The customer receives an **offer**.
* The customer orders items that are not available yet or that are currently not available with **<<order-processing/orders/managing-sales-orders#advance-order, advance orders>>**.
* An order is split into **<<order-processing/orders/managing-sales-orders#delivery-order, delivery orders>>**.
* A **<<order-processing/orders/managing-sales-orders#warranty, warranty>>** is created if the customer returns faulty items.
* An order of the type **<<order-processing/orders/managing-sales-orders#repair, repair>>** is created when a return was received and the item has to be repaired and sent back to the customer.
* With a **<<order-processing/orders/managing-sales-orders#credit-note, credit note>>**, part of the price or the full price of an order will be refunded to the customer.
* A **<<order-processing/orders/managing-sales-orders#return, return>>** is created when the customer returns items.
* Several orders are put together in a **<<order-processing/orders/multi-orders#, multi-order>>** (Enterprise version only).

== Links to other menus

Depending on which sales strategy you choose, orders from different **<<omni-channel/order-referrer#, Referrers>>** will be transferred to your plentymarkets system once this has been set up. Apart from your own online store, these referrers will primarily be the different markets that you configured in the **<<omni-channel/multi-channel#, System » Markets>>** menu of your plentymarkets system.

plentymarkets e.g. provides a comprehensive interface to **<<omni-channel/multi-channel/amazon#, [Amazon]>>** that does not only ensure the automated exchange with **link::/[Seller Central]**, but also covers further offers by Amazon such as **<<omni-channel/multi-channel/amazon#, Fulfillment by Amazon>>** and **<<omni-channel/multi-channel/amazon#, Amazon Multi-Channel>>**.

Thanks to the full **__eBay interface__** in plentymarkets, you can e.g. start listings and display eBay shop items on eBay, retrieve orders, automatically post evaluations and dun purchasers. For detailed information about the eBay interface, refer to the pages of the manual in the **<<omni-channel/multi-channel/ebay#, eBay>>** chapter.

Moreover, there are interfaces to many additional markets, such as **<<omni-channel/multi-channel/amazon#yatego, Yatego>>**, **MeinPaket** or **Hitmeister**, from which you can generate orders. The **<<omni-channel/order-referrer#, referrer>>** of the order is easily recognizable by the Referrer ID in the order overview.

After receiving orders, you can let **<<basics/automation/event-procedures#, event procedures>>** automatically create necessary documents such as <<order-processing/orders/order-documents/generating-invoices#, **Invoices**>> and <<order-processing/orders/order-documents/generating-delivery-notes#, **Delivery notes**>> and automatically inform your customers about the status of their orders using prepared **<<crm/sending-emails#, email templates>>**. plentymarkets also provides the necessary documents, e.g. <<order-processing/orders/order-documents/pick-list#, **pick lists**>> and <<order-processing/orders/order-documents/packing-list#, **packing lists**>>, to ensure that fulfillment is achieved as quickly as possible.

Afterwards, you register shipping orders, edit them if necessary or view special shipping orders in the **<<order-processing/fulfilment/shipping-centre#, Shipping center>>**.

In order to process orders efficiently in your plentymarkets system, you can also create **<<basics/automation/processes#, Processes>>** and have them run automatically. This way, you process one or several filtered orders as quickly as possible and in accordance with your company's internal processes. For further details refer to the **<<basics/automation/processes/work-steps#single-sales-order-processing, Single order processing>>** and **<<basics/automation/processes/work-steps#order-processing, Order processing>>** pages of the manual.

== Direct access to important pages of the manual

* **<<order-processing/payment#, SEPA payments>>**
* <<order-processing/orders/managing-sales-orders#order-search, **Search orders**>>
* <<order-processing/orders/managing-sales-orders#new-order, **New order**>>
* <<order-processing/orders/managing-sales-orders#changing-order, **Changing an order**>>
* **<<order-processing/payment#, Incoming payments>>**
* <<order-processing/orders/order-documents/generating-invoices#, **Generate invoices**>>
* <<order-processing/orders/order-documents/generating-delivery-notes#, **Generate delivery notes**>>
* <<order-processing/orders/order-documents/pick-list#, **Pick list**>>
* <<order-processing/orders/order-documents/packing-list#, **Packing list**>>
* **<<order-processing/fulfilment/shipping-centre#, Shipping center>>**
* <<order-processing/orders/coupons#, **Coupons**>>
