= Hinweise zur Senkung der Mehrwertsteuer (01.07.2020)
:lang: de
:keywords: Webshop, Mandant, Standard, Ceres, Plugin, Ceres, HowTo, Einrichtung, Plugin-Sets, Mehrwertsteuer, VAT, Senkung
:position: 100
:author: team-webshop

Zum 01.07.2020 wird der gesetzliche Mehrwertsteuersatz gesenkt. Hierbei kann es zu Problemfällen kommen, wenn Bestellungen vor dem 01.07. getätigt werden (bei denen also der vorherige Satz greift und im Webshop angezeigt wurde), aber erst nach dem 01.07. versendet werden (und demnach unter den gesenkten Satz fallen müssten). Um diesen Problemfällen entgegenzuwirken, empfehlen wir, einerseits sämtliche explizite Verweise auf den anzuwendenden Mehrwertsteuersatz aus dem Webshop zu entfernen und andererseits auch alle Auflistungen von Nettopreisen zu entfernen, da diese als Berechnungsgrundlage für die zugrundeliegenden Steuersätze genutzt werden können. +

Weitere Informationen zur Rechtsgrundlage findet ihr link:https://legal.trustedshops.com/blog/2020/06/12/mehrwertsteuersenkung-ab-1.-juli-darauf-muessen-sie-unbedingt-achten?uuid=311ded301b1da873edd8ab27a986bdb5&utm_source=email&utm_medium=newsletter&utm_campaign=country_de&utm_content=26-2020[im Blog von Trusted Shops^]{nbsp}icon:external-link[]. +

Wenn du ein eigenes Theme im Einsatz hast, ist es möglich, dass du weitere Stellen im Webshop anpassen musst, an denen Nettopreise oder Mehrwertsteuersätze ausgegeben werden. Diese individuellen Fälle können wir in diesem Best Practice nicht abbilden.


[NOTE]
====
Du solltest die folgenden Anpassungen in einer Kopie deines aktiven Plugin-Sets durchführen. Du kannst die angepasste Plugin-Set-Kopie dann vor dem Stichtag aktivieren und später, nachdem alle Bestellungen bearbeitet wurden, die vor dem Stichtag getätigt, aber erst nach dem Stichtag versendet wurden, auf dein altes Plugin-Set wechseln, damit Nettopreise und explizite Mehrwertsteuersätze wieder im Webshop angezeigt werden. Weitere Informationen zur Arbeit mit Plugin-Sets <<plugins/hinzugefuegte-plugins-installieren#, findest du hier>>.
====


== CSS-Anpassungen 

Um sämtliche Verweise auf Nettopreise in eurem Webshop auszublenden, muss das CSS angepasst werden. Am einfachsten ist es, dafür link:https://marketplace.plentymarkets.com/plugins/storefront/widgets/cfourcustomcssjs_5143[das Plugin Custom CSS/JS im Frontend]{nbsp}icon:external-link[] zu verwenden.

Füge das Plugin deinem plentymarkets System hinzu <<plugins/plugins-system-hinzufuegen#, wie hier beschrieben>>. Danach <<plugins/hinzugefuegte-plugins-installieren#, installierst du das Plugin>>.

Nachdem das Plugin installiert wurde, öffnest du die Plugin-Einstellungen über die Aktion **Einstellungen**. Im Tab **Stylesheets** findest du ein Textfeld für **CSS**, in welches du den folgenden Code-Schnipsel einfügst:

[source,plenty]
----
include::assets/vat-css-snippet.txt[]

----

**Speichere** deine Änderungen.
Nach dem erneuten Bereitstellen deines Plugin-Sets werden keine Nettopreise mehr in deinem Webshop angezeigt.


== Anpassungen im ShopBuilder

Im ShopBuilder musst du 3 Seiten anpassen: den Warenkorb, die Bestellbestätigung und den Checkout. Auf diesen Seiten musst du jeweils ein Text-Widget einfügen. 

=== Text-Widgets platzieren

Um deinen Webshop auch in der Übergangszeit rechtssicher zu betreiben, musst du einen Hinweis ausgeben, dass sich die angezeigten Preise inklusive Mehrwertsteuer verstehen. Damit dieser Hinweis auch automatisch in anderen Sprachen, die du pflegst, ausgegeben wird, verwenden wir dafür den Eintrag **Ceres::Template.itemInclVAT** aus der Mehrsprachigkeit. Ein "Inkl. ges. MwSt." reicht aus, aber es steht dir natürlich frei, diesen Text anzupassen.

[instruction]
. Öffne das Menü *CMS » Mehrsprachigkeit*.
. Klappe den Bereich *Artikel* aus.
. Überprüfe den Text im Eintrag **itemInclVAT** und passe diesen ggf. in deinen Webshop-Sprachen an.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Öffne nun den ShopBuilder unter **CMS » ShopBuilder**. Auf deinen Inhalten für den Warenkorb, die Bestellbestätigung und den Checkout musst du nun ein Text-Widget unterhalb der Summen-Widgets platzieren. Für jedes dieser 3 Text-Widgets befolgst du nun die folgenden Schritte: +

[instruction]

. Öffne das **Inline-Editing**, indem du auf das Stiftsymbol (icon:prencil[role="blue"]) auf dem Widget klickst. +
→ Der Text-Editor wird geöffnet.
. Gib ein beliebiges Wort ein und wähle es mit dem Cursor aus. +
→ Das Kontextmenü wird geöffnet.
. Klicke auf das Sprechblasen-Symbol ganz rechts im Kontextmenü. +
→ Das Eingabefeld **Übersetzungsschlüssel eingeben** wird geöffnet.
. Gib **Ceres::Template.itemInclVAT** ein.
. Bestätige die Eingabe durch Klick auf den grünen Haken in der rechten Ecke des Eingabefelds. +
→ Dein in Schritt 2 eingegebenes Wort wird durch den Text ersetzt, den du in der Mehrsprachigkeit hinterlegt hast, bspw. "Inkl. ges. MwSt."
. **Speichere** (icon:save[role="green"]) die Änderungen an deinem ShopBuilder-Inhalt.


== Anpassungen an Ceres-Templates

Es gibt 2 Stellen im Webshop, auf denen der Mehrwertsteuer-Hinweis nicht über den ShopBuilder eingefügt werden kann: die Auftragshistorie und die Warenkorbvorschau. Um trotzdem rechtssicher verkaufen zu können, kannst du 3 kleine Code-Stellen im Ceres-Plugin anpassen, um den Hinweis auch auf diesen Seiten ausgeben zu lassen. Die Anpassungen am Code, sorgen dafür, dass der gleiche Text aus der Mehrsprachigkeit genommen wird, der auch in den Text-Widgets erscheint, die ihr vorher im ShopBuilder hinzugefügt habt. +

Die 3 Anpassungen sind im Folgenden detailliert aufgeführt. Wir haben zusätzlichen einen Pull Request offen, in dem du die Code-Änderungen direkt nachverfolgen kannst. Diesen Pull Request findest du link:https://github.com/plentymarkets/plugin-ceres/compare/fix/vat_changes?expand=1[auf GitHub]{nbsp}icon:external-link[]. Scrolle auf der Seite weiter nach unten, um die Datei-Änderungen einzusehen.

=== Auftragshistorie anpassen

Um den Hinweis zur Mehrwersteuer auch in der Auftragshistorie im Mein Konto-Bereich anzuzeigen, musst du ein Code-Schnipsel in einer Template-Datei einfügen. Gehe dafür wie im Folgenden beschrieben vor:

[instruction]
. Öffne das Menü **Plugins » Plugin-Set-Übersicht**.
. Klicke in der Zeile deiner Plugin-Set-Kopie auf die Aktion **Plugin-Set bearbeiten**. +
→ Das Plugin-Set wird geöffnet.
. Klicke in der Zeile des Plugins **Ceres** auf die Aktion **Einstellungen**. +
→ Die Ceres-Einstellungen werden geöffnet.
. Klicke links im Navigationsbaum auf den Reiter **Dateien**. +
→ Die Dateistruktur des Plugins wird geöffnet.
. Klicke auf den Ordner **resources**.
. Klicke darin auf den Ordner **views**.
. Klicke darin auf den Ordner **Checkout**.
. Klicke darin auf den Ordner **Macros**.
. Klicke auf die Datei **OrderTotals.twig**. +
→ Die Datei wird im Editor geöffnet.
. Füge den folgenden Code nach dem `{% endif %}`-Element in Zeile 186 in einer neuen Zeile ein: `<dt class="w-100">{{ trans("Ceres::Template.itemInclVAT") }}</dt>`
. **Speichere** (icon:save[role="green"]) deine Änderungen.

Durch diese Anpassung wird der Text, der in der Mehrsprachigkeit im Eintrag **itemInclVAT** hinterlegt ist, auch in der Auftragshistorie angezeigt.


=== Standard-Header anpassen

Für ShopBuilder-Inhalte, bei denen du keinen eigenen Header verwendest, muss der Standard-Header angepasst werden, damit der Hinweis zur Mehrwertsteuer auch in der Warenkorbvorschau angezeigt wird. Gehe dafür wie im Folgenden beschrieben vor:

[instruction]
. Öffne das Menü **Plugins » Plugin-Set-Übersicht**.
. Klicke in der Zeile deiner Plugin-Set-Kopie auf die Aktion **Plugin-Set bearbeiten**. +
→ Das Plugin-Set wird geöffnet.
. Klicke in der Zeile des Plugins **Ceres** auf die Aktion **Einstellungen**. +
→ Die Ceres-Einstellungen werden geöffnet.
. Klicke links im Navigationsbaum auf den Reiter **Dateien**. +
→ Die Dateistruktur des Plugins wird geöffnet.
. Klicke auf den Ordner **resources**.
. Klicke darin auf den Ordner **views**.
. Klicke darin auf den Ordner **PageDesign**.
. Klicke darin auf den Ordner **Partials**.
. Klicke darin auf den Ordner **Header**.
. Klicke auf die Datei **DefaultHeader.twig**. +
→ Die Datei wird im Editor geöffnet.
. Füge den folgenden Code nach Zeile 119 in einer neuen Zeile ein: `{{ trans("Ceres::Template.itemInclVAT") }}`
. **Speichere** (icon:save[role="green"]) deine Änderungen.

Durch diese Anpassung wird der Text, der in der Mehrsprachigkeit im Eintrag **itemInclVAT** hinterlegt ist, auch in der Warenkorbvorschau des Standard-Headers angezeigt.



=== Eigenen Header anpassen

Für ShopBuilder-Inhalte, für die du einen eigenen Header angelegt hast, muss der Code des Top Bar-Widgets angepasst werden, damit der Hinweis zur Mehrwertsteuer auch in der Warenkorbvorschau angezeigt wird. Gehe dafür wie im Folgenden beschrieben vor:

[instruction]
. Öffne das Menü **Plugins » Plugin-Set-Übersicht**.
. Klicke in der Zeile deiner Plugin-Set-Kopie auf die Aktion **Plugin-Set bearbeiten**. +
→ Das Plugin-Set wird geöffnet.
. Klicke in der Zeile des Plugins **Ceres** auf die Aktion **Einstellungen**. +
→ Die Ceres-Einstellungen werden geöffnet.
. Klicke links im Navigationsbaum auf den Reiter **Dateien**. +
→ Die Dateistruktur des Plugins wird geöffnet.
. Klicke auf den Ordner **resources**.
. Klicke darin auf den Ordner **views**.
. Klicke darin auf den Ordner **Widgets**.
. Klicke darin auf den Ordner **Header**.
. Klicke auf die Datei **TopBarWidget.twig**. +
→ Die Datei wird im Editor geöffnet.
. Füge den folgenden Code nach Zeile 212 in einer neuen Zeile ein: ` {{ Twig.print('trans("Ceres::Template.itemInclVAT")') }}`
. **Speichere** (icon:save[role="green"]) deine Änderungen.

Durch diese Anpassung wird der Text, der in der Mehrsprachigkeit im Eintrag **itemInclVAT** hinterlegt ist, auch in der Warenkorbvorschau von Headern angezeigt, die ihr selbst im ShopBuilder bearbeitet habt. +

Alternativ hast du die Möglichkeit, die Warenkorbvorschau über die Einstellungen des Top Bar-Widgets komplett auszublenden. Dadurch würdest du dir diese eine Template-Anpassung sparen.


[NOTE]
====
Sowohl das **Reparieren** des Ceres-Plugins als auch ein Update des Ceres-Plugins machen diese Template-Anpassungen wieder rückgängig. 
====