= Bessere Werte bei Google Page Speed Insights erzielen
:lang: de
:keywords: Webshop, Mandant, Standard, Ceres, Plugin, Ceres, HowTo, Einrichtung, Plugin-Sets, Google, PSI, page speed, Page Speed, Index, Pages Speed Index, Performance, Geschwindigkeit, Optimierung, Optimieren, 
:position: 110
:author: team-webshop

In diesem Best Practice lernst du, auf welche Dinge du achten musst, um deine Performance-Werte bei link:https://developers.google.com/speed/pagespeed/insights/?hl=de[Google Page Speed Insights] zu verbessern. Im ersten Schritt zeigen wir dir, wie du mit den Mitteln, die plentyShop Ceres bereits mitbringt, höhere PSI-Werte erzielen kannst. Zu einem späteren Zeitpunkt wird diese Anleitung auch Anpassungen enthalten, die du mit einem eigenen Theme umsetzen kannst, um von Google PSI besser bewertet zu werden. Die hier aufgeführten Maßnahmen erfordern keinerlei Programmierungskenntnisse.

[IMPORTANT]
====
Die Maßnahmen, die wir hier vorschlagen, können deinen PSI-Wert nur in einem bedingten Maß verbessern. Mit dem Release von plentyShop Ceres 6.0 werden wir eine Reihe von Änderungen vornehmen, die sich positiv auf deine PSI-Werte auswirken werden. Wir sind bemüht, die Performance von plentyShop Ceres in jeder Version weiter zu verbessern.
====

Im Folgenden sind einige Anpassungen aufgeführt, die du für deinen plentyShop durchführen kannst, um die von Google erfassten Werte zu verbessern:
    
== Live-Modus im Ceres-Plugin aktivieren

Im Plugin Ceres hast du die Möglichkeit, zwischen dem *Entwicklungsmodus* und dem *Live-Modus* zu wählen. Im Entwicklungsmodus kannst du Debugging-Optionen nutzen und die Dateien des Plugins werden nicht minimiert und gebündelt, was sich negativ auf die Webshop-Performance auswirkt. Wir raten dir daher, den Live-Modus zu verwenden, um deinen Webshop performanter zu machen. Gehe wir im Folgenden beschrieben vor, um den Live-Modus zu aktivieren:

[.instruction]
Live-Modus aktivieren:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht*. +
. Wähle das Plugin-Set aus deines Webshops aus.
. Klicke auf *Plugin-Set bearbeiten*.
. Klicke in der Zeile des Plugins Ceres auf icon:cog[role="darkGrey"] *Einstellungen*.
→ Die Ceres-Einstellungen werden geöffnet.
. Klicke auf das Tab *Logging und Performance*.
. Wähle für die Einstellung *Performance-Level* die Option *Live-Modus*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


Dadurch, dass du diese Einstellung aktiviert hast, werden die Ceres-Dateien gebündelt und minimiert, was zu einer schnelleren Auslieferungszeit der Seiten im Webshop führt.

== Bilder-Widgets optimal einstellen

Bilddateien sind eine der größeren Problemquellen für einen performanten Webshop. Du solltest also darauf achten, dass du nur so viele Bilder-Widgets in deinen Seiten verbaust, wie für deine Zwecke nötig sind. Eine geringere Zahl von Bilder-Widgets wird sich positiv auf die Webshop-Geschwindigkeit auswirken. +

=== Moderne Bildformate verwenden

Darüber hinaus raten wir dir, die Bilder, die du im Webshop anzeigen willst, in möglichst modernen Bildformaten abzulegen. Wir empfehlen dir, in den Widgets *Bilderbox*, *Bilderkarussell* und *Hintergrundbild* das Feld *Bildauswahl* zu nutzen, um dort Bilder im *WebP-Format* zu hinterlegen. Wenn du eine WebP-Datei nutzt, wird dir zusätzlich die Option *Bildauswahl für ältere Browser* eingeblendet, um Bilder auch in Browsern anzuzeigen, die bisher keine WebP-Formate unterstützen. Dort solltest du nach Möglichkeit das Format JPEG verwenden. +

=== Lazy Loading aktivieren

Weiterhin emfehlen wir dir, für sämtliche Widgets, die Bilder beinhalten, die Option *Nur sichtbare Inhalte laden* in den Widget-Einstellungen zu aktivieren. Diese Option, das sogenannte "Lazy Loading", sorgt dafür, dass die Bilddateien, die sich beim ersten Aufruf der Seite nicht im aktuellen Sichtbereich befindet, zu einem späteren Zeitpunkt nachgeladen wird. Dies wirkt sich positiv auf die Performance des Webshops aus.

== Anzahl der Widgets reduzieren

Die Zahl der Widgets, die du auf deinen Webshop-Seiten verbaust, können die Performance deines Webshops negativ beeinflussen: Je mehr Widgets du pro Seite nutzt, desto langsamer lädt diese Seite. Dies gilt insbesondere für Bilder-Widgets und für Widgets, die eine große Menge an Artikeldaten enthalten. Jedes zusätzliche Widget beinträchtigt die Zeit bis zur ersten vollständigen Interaktivität der Seite. +
Wir empfehlen dir daher, nur so viele Widgets pro Seite zu verwenden, wie für deine Zwecke nötig sind. Vor allem auf Kategorieseiten, auf denen große Datenmengen und komplexes Javascript geladen werden muss, solltest du, wenn möglich, die Anzahl der dargestellten Artikel reduzieren und dadurch die Ladezeit verbessern. 

== Unsichtbaren Text durch eigene Schriftarten vermeiden

Falls du eigene Schriftarten einbindest, ohne dabei auf die Design-Einstellungen des ShopBuilders zurückzugreifen, kann es dazu kommen, dass manche Browser versuchen, den Text darzustellen, bevor die betroffene Font-Datei geladen wurde. Dadurch kommt es zu einem sogenannten *Flash of invisible text (FOIT)*, also einer kurzen Zeit, in der der darzustellende Text vom Browser nicht angezeigt werden kann. +
Um dies zu vermeiden, kannst du über eine CSS-Anweisung vorübergehend eine Systemschriftart anzeigen lassen, bis die betroffene Schriftart geladen wurde. Dazu fügst du in deinem eigenen CSS (beispielsweise über das Plugin link:https://marketplace.plentymarkets.com/plugins/storefront/widgets/cfourcustomcssjs_5143[Custom CSS/JS im Frontend]) die Anweisung *font-display: swap* in deinen *@font-face* Styles ein. Dadurch vermeidest du unangenehme FOIT, was sich positiv auf den PSI-Wert deines Webshops auswirkt.

== ShopBooster aktivieren

Die Time-to-first-Byte (TTFB) ist ebenfalls Bestandteil der PSI-Erfassung, auch wenn sie nur einen geringen Teil der Wertung darstellt. Um deine TTFB zu verbessern, kannst du für deinen plentyShop Ceres das kostenpflichtige Zusatzmodul ShopBooster aktivieren. Dadurch werden Seiteninhalte von Ceres Webshops bei einem zweiten Aufruf in den Cache geschrieben, um dadurch deutlich bessere Ladezeiten für deine Nutzer:innen zu erzielen.

[IMPORTANT]
.Zusätzliche Kosten
====
Durch das Aktivieren des ShopBoosters fallen *pro Mandant* zusätzliche Kosten in Höhe von 0,004 € pro 100 Seitenaufrufe und -änderungen an. Ein Seitenaufruf ist der Vorgang, bei dem ein Shop-Besucher oder ein Webcrawler eine URL des Online-Shops aufruft; eine Seitenänderung wird durch folgende Vorgänge ausgelöst:

- Aktualisieren von Kategorien- und Artikeldaten
- Aktualisieren von ShopBuilder-Seiten
- Bereitstellen von Plugins
- Speichern von Einstellungen in der Ceres Konfiguration
- Invalidieren des Caches bei Deaktivierung des ShopBoosters

Die Zusatzkosten des ShopBoosters betragen monatlich *maximal* 100€ pro Mandant.
====

[.instruction]
ShopBooster aktivieren:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Webshop » ShopBooster*.
. Klicke auf *ShopBooster aktivieren*. +
→ Ein Fenster öffnet sich, welches dich auf entsprechende zusätzliche Kosten hinweist.
. Klicke auf *Bestätigen* um den ShopBooster zu aktivieren. +
→ Die Meldung *ShopBooster wurde aktiviert* wird eingeblendet.

Auf die gleiche Weise kannst du den ShopBooster wieder deaktivieren.

[.instruction]
ShopBooster deaktivieren:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Webshop » ShopBooster*.
. Klicke auf *ShopBooster deaktivieren*. +
→ Ein Fenster öffnet sich, welches dich auf zusätzliche Kosten hinweist.
. Klicke auf *Bestätigen* um den ShopBooster zu deaktivieren. +
→ Die Meldung *ShopBooster wurde deaktiviert* wird eingeblendet.

== Javascript in Code-Widgets vermeiden

Im ShopBuilder steht dir ein Code-Widget zur Verfügung, über das du zusätzliche Anpassungen vornehmen kannst, die der ShopBuilder nicht von selbst bereitstellt. Wenn du eigenen Code einbinden möchtest, raten wir dir dazu, eigenes Javascript nicht über Code-Widgets zu realisieren, sondern beispielsweise über das Plugin link:https://marketplace.plentymarkets.com/plugins/storefront/widgets/cfourcustomcssjs_5143[Custom CSS/JS im Frontend] oder ein eigenes Theme. Zusätzliches Javascript in Code-Widgets zu verarbeiten, wirkt sich negativ auf die Ladezeit der Seite aus. +
Falls du eigenes Javascript über ein Plugin oder ein Theme einbindest, empfehlen wir dir, das Javascript ganz am Ende des HTML-Body zu verbauen.


== Plugins für Zahlungsarten richtig verknüpfen

Wenn du Plugin-Zahlungsarten für deinen plentyShop verwendest, die eine große Menge an eigenen Daten beinhalten, wie beispielsweise AmazonPay oder PayPal, ist es für die Performance deines Webshops unerlässlich, dass du diese Plugins mit den richtigen Layout-Containern verknüpfst. In Ceres 5.0 wurden neue Layout-Container hinzugefügt, um Javascript und CSS der Zahlungsplugins nur an den Stellen zu laden, an denen sie wirklich gebraucht werden. +
Die Plugin-Beschreibungen der jeweiligen Zahlungsarten, z.B. link:https://marketplace.plentymarkets.com/paypal_4690#80.[PayPal], enthalten bereits detaillierte Anleitungen, wie du die Plugins mit den richtigen Containern verknüpfst. Generell gilt, dass du das Javascript der jeweiligen Zahlungsart mit dem Container *Checkout.AfterScriptsLoaded* und nicht mehr mit dem Container *ScriptLoade.AfterScriptsLoaded* verknüpfen solltest, um die Performance deines Webshops zu verbessern.
