= Ceres-Checkout in Callisto einrichten
:lang: de
:keywords: Webshop, Mandant, Standard, Ceres, Plugin, Checkout, Kaufabwicklung, Callisto
:position: 40

Du willst den neuen Checkout mit seiner Plugin-Fähigkeit und individuellen Anpassbarkeit in deinem Callisto-Webshop nutzen? Kein Problem – im Folgenden erfährst du Schritt für Schritt, was dafür nötig ist. Solltest du noch weitere Unterstützung bei der Integration des Ceres-Checkouts in Callisto brauchen, schau bei unserem Service-Angebot auf dem link:https://marketplace.plentymarkets.com/services/CeresCheckout4Callisto_5475[Marketplace^] vorbei.

[#standard]

== Ceres-Checkout für Callisto-Webshops mit *Standard-Bestellvorgang*

[NOTE]
.Das Wichtigste vorab …
====
* Dieses Best Practice beschreibt die Einrichtung des Ceres-Checkouts in einen Callisto-Webshop. Kopiere dir bitte dein Design und führe keine Anpassungen an deinem *aktiven* Layout durch.
* Um den Ceres-Checkout zu nutzen, benötigst du neben deinem Callisto-Webshop die aktuellen Versionen der Plugins link:https://marketplace.plentymarkets.com/plugins/templates/Ceres_4697[Ceres^] und link:https://marketplace.plentymarkets.com/plugins/templates/IO_4696[IO^]. Beide findest du im plentyMarketplace. Die Plugins müssen in einer Plugin-Set-Kopie installiert und aktiviert sein.
* Um deine Zahlungsanbieter im Ceres-Checkout benutzen zu können, musst du die jeweiligen Plugins aus dem link:https://marketplace.plentymarkets.com/plugins/payment[Marketplace] laden und installieren. Bitte beachte, dass es Zahlungsanbieter gibt, die bislang kein Plugin zur Verfügung stellen und auf deren Leistungen du daher mit dem Ceres-Checkout nicht zurückgreifen kannst.
====

[IMPORTANT]
.Callisto-URL-Struktur für Artikel aktivieren
====
Wenn du einen Callisto-Webshop mit Ceres-Checkout nutzen möchtest, raten wir dir von der Option *Callisto-URL-Struktur für Artikel aktivieren* Gebrauch zu machen, um deine SEO-Werte nicht negativ zu beinflussen. Du findest die Einstellung im Menü *Plugin-Übersicht » Ceres » Konfiguration » Global*.
====

[IMPORTANT]
.In einer Plugin-Set-Kopie arbeiten
====
Damit der Live-Betrieb des Webshops beim Testen des Ceres Checkouts nicht beeinträchtigt wird, bietet es sich an, die Änderungen in einem separaten Plugin-Set zu testen. Wie du eine Kopie deines Plugin-Sets erstellst, erfährst du in <<webshop/best-practices#_plugin_set_kopieren, diesem Best Practice>>. Führe die Änderungen zuerst im <<plugins/plugin-sets#, Vorschaumodus>> aus, bevor du sie in deinen Webshop übernimmst.
====

Wenn du einen Callisto-Shop betreibst, der den *Standard-Bestellvorgang* nutzt, musst du mit der Einbindung des Ceres-Checkouts etwas früher beginnen: der Standard-Bestellvorgang wird zum 05.08.2019 abgestellt. Wie du erfährst, welchen Bestellvorgang du verwendest, findest du in <<webshop/best-practices#bp-ceres-EOL, diesem Kapitel>>. +

Wenn du die folgenden Anweisungen Schritt für Schritt durcharbeitest, kannst du deinen Callisto-Shop mit wenigen Handgriffen mit dem Ceres-Checkout ausstatten.

=== Routen verwalten
Ceres baut auf der Logik des Plugins IO auf. Um den Checkout so zu nutzen, dass alle Links zwischen Callisto und Ceres korrekt funktionieren, gehst du wie folgt vor:

[.instruction]
Einstellungen im Plugin IO vornehmen:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Klicke auf *IO*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*.
. Wechsle in das Tab *Routing*.
. Entferne das Häkchen neben *Routen aktivieren*. +
→ Alle Routen werden deaktiviert.
. Aktiviere die Routen */basket*, */checkout*, */confirmation*, */login*, */register*, */password-reset*, sowie */place-order* & */execute-payment*.
. *Speichere* die Einstellungen.

[.instruction]
Einstellungen im Plugin Ceres vornehmen:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Klicke auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*. +
→ Das Tab *Global* ist bereits vorausgewählt.
. Klicke auf *Callisto-URL-Struktur für Artikel aktivieren*. +
→ Die Callisto-Routen werden aktiviert.
. *Speichere* die Einstellungen. +
→ Der Ceres-Checkout ist in Ihrem Callisto-Webshop aktiv.

Für einen Großteil der Kunden sind dies bereits alle notwendigen Schritte um den Ceres-Checkout in ihren Callisto-Shop einzubinden. <<plugins/new-plugins#, Kaufe und installiere>> in deinem Plugin-Set die betreffenden Plugins für Versanddienstleister und Zahlungsanbieter und teste deine neue Kaufabwicklung gründlich, bevor du das Plugin-Set für den Mandanten aktivierst. +

Kunden, die zusätzliche individuelle Anpassungen an ihrem Layout vorgenommen haben, müssen überprüfen an welchen Stellen sie ihre Kunden zur Kaufabwicklung weiterleiten. Diese Stellen müssen so angepasst werden, dass sie auf die Route */checkout* verlinken. Wir können diese individuellen Anpassungen nicht abfangen und sie können von Kunde zu Kunde anders ausfallen.

Der Ceres-Checkout wird sich von deinem bisherigen Callisto-Layout optisch unterscheiden. Du kannst Header und Footer des Checkouts und des Warenkorbs global über den <<webshop/shop-builder#95, ShopBuilder>> bearbeiten. Den Checkout selbst wirst du mit Ceres Version 3.1.0 über den ShopBuilder bearbeiten können. Weiterhin kannst du eigene Anpassungen über ein <<#theme, Theme>> realisieren.

Passe nun noch die Pfade für deine rechtlichen Angaben an.

=== Rechtliche Angaben anpassen

Die vier rechtlich relevanten Angaben *AGB*, *Datenschutzerklärung*, *Impressum* und *Widerrufsrecht* müssen neu verknüpft werden, um weiterhin korrekt angezeigt zu werden.

[.instruction]
AGB anpassen:

. Öffne das Menü *Artikel » Kategorien*.
. Klappe deine Callisto-Kategorie, in der die rechtlichen Angaben liegen, auf.
. Kopiere die Kategorie *AGB* als Hauptkategorie. +
→ Die neue Hauptkategorie *AGB* wird geöffnet.
. Gib als *URL-Name* der Kategorie *gtc* ein.
. *Speichere* die Einstellungen.

[.instruction]
Datenschutzerklärung anpassen:

. Öffne das Menü *Artikel » Kategorien*.
. Klappe deine Callisto-Kategorie, in der die rechtlichen Angaben liegen, auf.
. Kopiere die Kategorie *Datenschutz* als Hauptkategorie. +
→ Die neue Hauptkategorie *Datenschutz* wird geöffnet.
. Gib als *URL-Name* der Kategorie *privacy-policy* ein.
. *Speichere* die Einstellungen.

[.instruction]
Impressum anpassen:

. Öffne das Menü *Artikel » Kategorien*.
. Klappe deine Callisto-Kategorie, in der die rechtlichen Angaben liegen, auf.
. Kopiere die Kategorie *Impressum* als Hauptkategorie. +
→ Die neue Hauptkategorie *Impressum* wird geöffnet.
. Gib als *URL-Name* der Kategorie *legal-disclosure* ein.
. *Speichere* die Einstellungen.

[.instruction]
Widerrufsrecht anpassen:

. Öffne das Menü *Artikel » Kategorien*.
. Klappe deine Callisto-Kategorie, in der die rechtlichen Angaben liegen, auf.
. Kopiere die Kategorie *Widerrufsrecht* als Hauptkategorie. +
→ Die neue Hauptkategorie *Widerrufsrecht* wird geöffnet.
. Gib als *URL-Name* der Kategorie *cancellation-rights* ein.
. *Speichere* die Einstellungen.

Wenn du deine rechtlichen Angaben gespeichert hast, die Routen wie beschrieben aktiviert wurden und du alle für deinen Shop relevanten Zahlungs- und Versanddienstleister über Plugins eingebunden hast, ist dein Ceres-Checkout einsatzfähig und du hast die Hürden des Callisto EOLs gemeistert.

[#individueller-bestellvorgang]

== Ceres-Checkout für Callisto-Webshops mit *individuellem Bestellvorgang*

[NOTE]
.Das Wichtigste vorab …
====
* Dieses Best Practice beschreibt die Einrichtung des Ceres-Checkouts in einen Callisto-Webshop. Kopiere dir bitte dein Design und führe keine Anpassungen an deinem *aktiven* Layout durch.
* Um den Ceres-Checkout zu nutzen, benötigst du neben deinem Callisto-Webshop die aktuellen Versionen der Plugins link:https://marketplace.plentymarkets.com/plugins/templates/Ceres_4697[Ceres^] und link:https://marketplace.plentymarkets.com/plugins/templates/IO_4696[IO^]. Beide findest du im plentyMarketplace. Die Plugins müssen in einer Plugin-Set-Kopie installiert und aktiviert sein.
* Um deine Zahlungsanbieter im Ceres-Checkout benutzen zu können, musst du die jeweiligen Plugins aus dem link:https://marketplace.plentymarkets.com/plugins/payment[Marketplace] laden und installieren. Bitte beachte, dass es Zahlungsanbieter gibt, die bislang kein Plugin zur Verfügung stellen und auf deren Leistungen du daher mit dem Ceres-Checkout nicht zurückgreifen kannst.
====

[IMPORTANT]
.Callisto-URL-Struktur für Artikel aktivieren
====
Wenn du einen Callisto-Webshop mit Ceres-Checkout nutzen möchtest, raten wir dir von der Option *Callisto-URL-Struktur für Artikel aktivieren* Gebrauch zu machen, um deine SEO-Werte nicht negativ zu beinflussen. Du findest die Einstellung im Menü *Plugin-Übersicht » Ceres » Konfiguration » Global*.
====

[IMPORTANT]
.In einer Plugin-Set-Kopie arbeiten
====
Damit der Live-Betrieb des Webshops beim Testen des Ceres Checkouts nicht beeinträchtigt wird, bietet es sich an, die Änderungen in einem separaten Plugin-Set zu testen. Wie du eine Kopie deines Plugin-Sets erstellst, erfährst du in <<webshop/best-practices#_plugin_set_kopieren, diesem Best Practice>>. Führe die Änderungen zuerst im <<plugins/plugin-sets#, Vorschaumodus>> aus, bevor du sie in deinen Webshop übernimmst.
====

Wenn du in deinem Callisto-Shop den *individuellen Bestellvorgang* nutzt, musst du den Ceres-Checkout bis spätestens 01.09.2019 eingebunden haben, da ansonsten keine Bestellungen mehr über deinen Webshop abgeschlosen werden können. +

Wie du erfährst, welchen Bestellvorgang du verwendest, findest du in <<webshop/best-practices#bp-ceres-EOL, diesem Kapitel>>. +

Wenn du die folgenden Anweisungen Schritt für Schritt durcharbeitest, kannst du deinen Callisto-Shop mit wenigen Handgriffen mit dem Ceres-Checkout ausstatten.

=== Routen verwalten
Ceres baut auf der Logik des Plugins IO auf. Um den Checkout so zu nutzen, dass alle Links zwischen Callisto und Ceres korrekt funktionieren, verfährst du wie folgt:

[.instruction]
Einstellungen in IO vornehmen:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Klicke auf *IO*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*.
. Wechsle in das Tab *Routing*.
. Entferne das Häkchen neben *Routen aktivieren*. +
→ Alle Routen werden deaktiviert.
. Aktiviere die Routen */checkout*, */confirmation*, */login*, */register*, *password-reset* sowie */place-order & /execute-payment*.
. *Speichere* die Einstellungen.

[.instruction]
Einstellungen in Ceres vornehmen:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Klicke auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*. +
→ Das Tab *Global* ist bereits vorausgewählt.
. Klicke auf *Callisto-URL-Struktur für Artikel aktivieren*. +
→ Die Callisto-Routen werden aktiviert.
. *Speichere* die Einstellungen. +
→ Der Ceres-Checkout ist in Ihrem Callisto-Webshop aktiv.

=== Bestellabwicklung anpassen

Für die Bestellabwicklung müssen Änderungen an deinen Kategorien vorgenommen werden. Gehe dazu wie folgt vor:

[.instruction]
Kategorien erstellen:

. Öffne das Menü *Artikel » Kategorien*.
. Erstelle eine neue Hauptkategorie mit dem Namen *login*.
. Öffne die Kategorie *login*.
. Wähle den Kategorietyp *Container*.
. *Speichere* die Einstellungen.
. Erstelle eine neue Hauptkategorie mit dem Namen *checkout*.
. Öffne die Kategorie *checkout*.
. Wähle den Kategorietyp *Container*.
. *Speichere* die Einstellungen.

Anschließend verknüpfst du die neuen Kategorien mit den Bestellschritten von Callisto.

[.instruction]
Bestellvorgang anpassen:

. Öffne das Menü *CMS » Webdesign*.
. Klicke auf *Einstellungen*. +
→ Das Menü *Design-Einstellungen* wird geöffnet.
. Wechsle in das Tab *Mandanten*.
. Wähle den Mandanten, für den du die Änderungen vornehmen willst.
. Wechsle in das Tab *Bestellvorgang*.
. Klicke neben *2. Bestellschritt* auf *Suchen*.
. Wähle die zuvor erstellte Kategorie *login*.
. Klicke neben *3. Bestellschritt* auf *Suchen*.
. Wähle die zuvor erstellte Kategorie *checkout*.
. *Speichere* die Einstellungen.

Wenn du nun aus dem Warenkorb zur Kasse gehst, wirst du auf den Ceres-Checkout weitergeleitet, der alle neuen Funktionen wie z.B. Payment-Plugins wie PayPal ermöglicht.

=== Backlinks setzen

Damit ein nicht angemeldeter Benutzer nach dem Klick auf *Zur Kasse* vom Login weiter zur Bestellabwicklung geleitet wird, müssen Änderungen am Callisto-Code vorgenommen werden. Gehe dazu vor wie im Folgenden beschrieben:

[.instruction]
Backlinks für den Warenkorb setzen:

. Öffne das Menü *Artikel » Kategorien*.
. Klappe deine Callisto-Kategorie auf.
. Klicke auf die Kategorie *Warenkorb*.
. Wechsle in das Tab *Beschreibung 1*.
. Suche den folgenden Code: `{% if ( $CustomerID ) { Link_Checkout(3); } else { Link_Checkout(2); } %}`
. Ersetze den Code durch: `$_check.$_backlink`
. *Speichere* die Einstellungen.

In der Zeile vor dem gerade eingefügten `$_check.$_backlink` musst du nun noch den folgenden Code einfügen:

[source,plenty]
----
include::assets/checkout_snippet.txt[]

----

*Speichere* deine Änderungen am Code. +
Das *de* in der Zeile `{% if $Lang !== 'de' %}` bezieht sich hier auf die Standardprache des Webshops. Falls die Standardsprache nicht Deutsch ist, muss das Sprachkürzel entsprechend angepasst werden.


[.instruction]
Backlinks für die Warenkorbvorschau setzen:

. Öffne das Menü *CMS » Webdesign » Layout » ItemView » ItemViewBasketPreviewList*.
. Suche den folgenden Code: `{% if( $CustomerID ) { Link_Checkout(3); } else { Link_Checkout(2); } %}`
. Ersetze den Code durch `$_check.$_backlink`
. *Speichere* die Einstellungen.

In der Zeile vor dem gerade eingefügten `$_check.$_backlink` musst du nun noch den folgenden Code einfügen:

[source,plenty]
----
include::assets/checkout_snippet.txt[]

----

*Speichere* deine Änderungen am Code. +
Das *de* in der Zeile `{% if $Lang !== 'de' %}` bezieht sich hier auf die Standardprache des Webshops. Falls die Standardsprache nicht Deutsch ist, muss das Sprachkürzel entsprechend angepasst werden.

[.instruction]
Backlinks für das Warenkorb-Overlay setzen:

. Öffne das Menü *CMS » Webdesign » Layout » ItemView » ItemViewItemToBasketConfirmationOverlay*.
. Suche den folgenden Code: `{% if( $CustomerID ) { Link_Checkout(3); } else { Link_Checkout(2); } %}`
. Ersetze den Code durch: `$_check.$_backlink`
. *Speichere* die Einstellungen.

In der Zeile vor dem gerade eingefügten `$_check.$_backlink` musst du nun noch den folgenden Code einfügen:

[source,plenty]
----
include::assets/checkout_snippet.txt[]

----

*Speichere* deine Änderungen am Code. +
Das *de* in der Zeile `{% if $Lang !== 'de' %}` bezieht sich hier auf die Standardprache des Webshops. Falls die Standardsprache nicht Deutsch ist, muss das Sprachkürzel entsprechend angepasst werden. +


Kunden, die zusätzliche individuelle Anpassungen an ihrem Layout vorgenommen haben, müssen überprüfen an welchen Stellen sie ihre Kunden zur Kaufabwicklung weiterleiten. Diese Stellen müssen so angepasst werden, dass sie auf die Route */checkout* verlinken. Wir können diese individuellen Anpassungen nicht abfangen, da sie von Kunde zu Kunde anders ausfallen können. +

Der Ceres-Checkout wird sich von deinem bisherigen Callisto-Layout optisch unterscheiden. Du kannst Header und Footer des Checkouts und des Warenkorbs global über den <<webshop/shop-builder#95, ShopBuilder>> bearbeiten. Den Checkout selbst wirst du mit Ceres Version 3.1.0 über den ShopBuilder bearbeiten können. Weiterhin kannst du eigene Anpassungen über ein <<#theme, Theme>> realisieren.

Passe nun noch die Pfade für deine rechtlichen Angaben an.

=== Rechtliche Angaben anpassen

Die vier rechtlich relevanten Angaben *AGB*, *Datenschutzerklärung*, *Impressum* und *Widerrufsrecht* müssen neu verknüpft werden, um weiterhin korrekt angezeigt zu werden.

[.instruction]
AGB anpassen:

. Öffne das Menü *Artikel » Kategorien*.
. Klappe deine Callisto-Kategorie, in der die rechtlichen Angaben liegen, auf.
. Kopiere die Kategorie *AGB* als Hauptkategorie. +
→ Die neue Hauptkategorie *AGB* wird geöffnet.
. Gib als *URL-Name* der Kategorie *gtc* ein.
. *Speichere* die Einstellungen.

[.instruction]
Datenschutzerklärung anpassen:

. Öffne das Menü *Artikel » Kategorien*.
. Klappe deine Callisto-Kategorie, in der die rechtlichen Angaben liegen, auf.
. Kopiere die Kategorie *Datenschutz* als Hauptkategorie. +
→ Die neue Hauptkategorie *Datenschutz* wird geöffnet.
. Gib als *URL-Name* der Kategorie *privacy-policy* ein.
. *Speichere* die Einstellungen.

[.instruction]
Impressum anpassen:

. Öffne das Menü *Artikel » Kategorien*.
. Klappe deine Callisto-Kategorie, in der die rechtlichen Angaben liegen, auf.
. Kopiere die Kategorie *Impressum* als Hauptkategorie. +
→ Die neue Hauptkategorie *Impressum* wird geöffnet.
. Gib als *URL-Name* der Kategorie *legal-disclosure* ein.
. *Speichere* die Einstellungen.

[.instruction]
Widerrufsrecht anpassen:

. Öffne das Menü *Artikel » Kategorien*.
. Klappe deine Callisto-Kategorie, in der die rechtlichen Angaben liegen, auf.
. Kopiere die Kategorie *Widerrufsrecht* als Hauptkategorie. +
→ Die neue Hauptkategorie *Widerrufsrecht* wird geöffnet.
. Gib als *URL-Name* der Kategorie *cancellation-rights* ein.
. *Speichere* die Einstellungen.

Wenn du deine rechtlichen Angaben gespeichert hast, die Routen wie beschrieben aktiviert wurden, die Kategorien angepasst wurden, die Backlinks gesetzt sind und du alle für deinen Shop relevanten Zahlungs- und Versanddienstleister über Plugins eingebunden hast, ist dein Ceres-Checkout einsatzfähig und du hast die Hürden des Callisto EOLs gemeistert.

[#theme]
== Theme

Du hast deinen Callisto-Webshop bereits nach deinen individuellen Bedürfnissen gestaltet und befürchtest, dass das Ceres-Design nicht damit harmoniert? Es ist ein Leichtes, das link:https://marketplace.plentymarkets.com/plugins/storefront/themes/cerescoconut_6120[Coconut-Theme^] für Ceres herunterzuladen und dein Design darin zu hinterlegen, um deinen gesamten Shop in der gewohnten Optik erstrahlen zu lassen.
