= Umstieg von Callisto auf Ceres
:lang: de
:keywords: Webshop, Mandant, Standard, Ceres, Plugin, Callisto, Ceres, Umstieg, Umzug, HowTo, Produktiv, Einrichtung, Plugin Sets
:position: 50

In diesem Best Practice erfährst du, welche Dinge du beachten musst, damit dein Callisto Webshop ohne Probleme weiterlaufen kann, während du deinen <<omni-channel/online-shop/ceres-einrichten#, Ceres Shop>> einrichtest.

== Neues Plugin Set anlegen

Damit du einen Ceres Shop im Vorschau-Modus aufsetzen kannst, ohne dass dein Callisto Shop in irgendeiner Weise davon betroffen ist, musst du zunächst ein neues <<basics/erste-schritte/plugins#30, Plugin Set>> erstellen.

[.instruction]
Plugin Set erstellen:
. Öffne das Menü *Plugins » Plugin Übersicht*.
. Klicke in der linken oberen Ecke auf *Neues Plugin Set erstellen*. +
→ Das Menü *Neues Plugin Set* wird geöffnet.
. Gib einen Namen für dein Plugin Set ein.
. *Speichere* die Einstellung. +
→ Das Plugin Set wurde erstellt.

[WARNING]
====
Damit der Callisto-Webshop von den vorgenommenen Änderungen unberührt bleibt, darf das erstellte Plugin Set *nicht* für einen Mandanten aktiviert werden.
====

In dem erstellten Plugin Set kannst du nun damit beginnen, deinen Ceres Webshop einzurichten, ohne dass dein Callisto-Shop im produktiven Betrieb beeinträchtigt wird.

== Plugin Set einrichten

Nachdem du die Plugins *Ceres* und *IO* link:https://marketplace.plentymarkets.com/plugins/templates[gekauft^] hast, *installierst und aktivierst* du diese nun für das erstellte Plugin Set.

[.instruction]
Plugin Set einrichten:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Klicke auf das zuvor erstellte Plugin Set. +
→ Das Fenster *Plugin Set Details* wird geöffnet.
. Wähle die Option *Alle* bei den Suchfiltern *Herkunft*, *Installiert* und *Aktiv*.
. Klicke auf *Suchen*. +
→ Alle gekauften Plugins werden angezeigt.
. Klicke in der Zeile des Plugins *Ceres* auf *Plugin installieren* in der Spalte *Aktion*. +
→ Das Installationsfenster wird geöffnet. +
→ Die aktuellste Version des Plugins ist vorausgewählt.
. Klicke auf *Installieren*.
. Wiederhole die Schritte 5 und 6 für das Plugin *IO*.
. Klicke auf *Speichern & Plugins veröffentlichen*. +
→ Die Erfolgsmeldung *Plugin Set fertiggestellt* wird angezeigt.

Damit sind die Vorarbeiten geleistet und du kannst damit beginnen, deinen Ceres Shop einzurichten. Ziehe hierzu die Handbuchseiten <<basics/erste-schritte/schnelleinstieg#570, Schnelleinstieg>> und <<omni-channel/online-shop/ceres-einrichten#20, Ceres einrichten>> zu Rate.
Wie du Änderungen an deinem Webshop im Vorschaumodus testest, erfährst du im Folgenden.

== Ceres Webshop im Vorschaumodus testen

Damit du deine Änderungen jederzeit im Webshop nachverfolgen kannst, bietet dir die *Plugin Übersicht* die Option, deinen Shop im Vorschaumodus aufzurufen.
Bevor du deinen Ceres Shop im Vorschaumodus aufrufst, solltest du dein Plugin Set erneut über den Button *Speichern & Plugin Set veröffentlichen* bereitstellen.

[.instruction]
Plugin Set als Vorschau öffnen:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Klicke auf das zuvor erstellte Plugin Set. +
→ Das Fenster *Plugin Set Details* wird geöffnet.
. Klicke auf *Plugin Set Vorschau*.
→ Der Webshop wird mit dem gewählten Plugin Set in einem neuen Browser-Tab geöffnet.

[NOTE]
====
Beachte, dass du <<basics/erste-schritte/schnelleinstieg#70, Popups>> erlaubt haben solltest, damit der Shop im neuen Browser-Tab geöffnet werden kann.
====

== Ceres Webshop produktiv schalten

Wenn alle deine Tests im Vorschaumodus abgeschlossen sind und du nun deinen Callisto Shop durch Ceres ersetzen willst, aktivierst du das Plugin Set für den jeweiligen Mandanten. Diese Verknüpfung kann, falls nötig, auch wieder aufgehoben werden. Du kannst also jederzeit zu deinem alten Webshop zurückwechseln.

[.instruction]
Plugin Set für einen Mandanten aktivieren:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Klicke auf das zuvor erstellte Plugin Set. +
→ Das Fenster *Plugin Set Details* wird geöffnet.
. Klicke in der linken oberen Ecke auf *Plugin Set aktivieren*. +
→ Das Fenster *Plugin Set Aktivieren* wird geöffnet.
. Wähle das Plugin Set aus der Dropdown-Liste, das du mit dem jeweiligen Mandanten verknüpfen willst. +
→ Die Erfolgsmeldung *Plugin Set X ist für Mandant Y aktiv* wird angezeigt.

Damit ist der Ceres Webshop prduktiv geschaltet und ersetzt deinen Callisto Webshop.
