= Dokumente erzeugen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Versandlabel, Versandetikett, Adressetikett, Lieferanschriftenliste, Paketnummernimport, Paketnummer, Paketnummern, Einlieferungsliste, Barcodescanner
:description: Erfahren Sie, wie Sie die Lieferanschriftenliste exportieren, Paketnummern importieren, Adressetiketten einrichten und Einlieferungslisten generieren.
:position: 30

Auf dieser Handbuchseite wird beschrieben, wie Sie die Lieferanschriftenliste zu Ihrem Versanddienstleister exportieren und anschließend die Paketnummern, die Sie von Ihrem Versanddienstleister erhalten, importieren. Versandlabels können Sie drucken, nachdem Sie Ihre Aufträge online bei Ihrem Versanddienstleister angemeldet haben. Außerdem erfahren Sie, wie Sie Adressetiketten per Vorlage einrichten und Einlieferungslisten generieren.

Wie Sie die anderen in plentymarkets verfügbaren Dokumente wie z.B. Rechnung, Auftragsbestätigung oder Lieferschein einrichten, erfahren Sie im Bereich <<auftragsabwicklung/auftraege#, Aufträge>>.

[#200]
== Lieferanschriftenliste exportieren

Wenn Sie Pakete über einen Versanddienstleister versenden, benötigen Sie eine Lieferanschriftenliste. Die Lieferanschriftenliste ist eine Exportdatei mit Sendungsinformationen, die Sie dem Versanddienstleister anschließend bereitstellen, so dass der Versanddienstleister Ihnen wiederum gültige Versandlabels für Ihre Pakete zur Verfügung stellen kann. Mit diesem Export können Sie schnell und einfach größere Mengen an Paketen für den Versand vorbereiten. Im Folgenden wird beschrieben, wie Sie die Lieferanschriften Ihrer Aufträge in eine Datei, die Sie für die Software Ihres Versanddienstleisters benötigen, exportieren.

Bei Fragen zum Dateiimport in die Software des Versanddienstleisters oder zur Benutzung der Software kontaktieren Sie den Anbieter.

[.instruction]
Lieferanschriftenliste exportieren:

. Öffnen Sie das Menü *Aufträge » Fulfillment*.
. Klappen Sie den Bereich *Lieferanschriftenliste* auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-lieferanschriftenliste-exportieren>>.
. Klicken Sie auf das Zahnrad. +
→ Sie erhalten eine Datei, die Sie auf Ihrem Computer speichern.
. Importieren Sie die Datei anschließend in die Software Ihres Versanddienstleisters.

[[tabelle-lieferanschriftenliste-exportieren]]
.Einstellungen im Menü *Aufträge » Fulfillment » Bereich: Lieferanschriftenliste*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Suchfilter

|*Auftragsstatus*
|Auftragsstatus wählen.

|*Eigner*
|Eigner wählen.

|*Zahlungsart*
|Zahlungsart wählen.

|*Versandart*
|Versandart wählen.

|*Zahlungseingang*
|Zahlungseingang wählen.

|*Datenformat*
|Datenformat der Software Ihres Versanddienstleisters wählen. +
Wenn für die bearbeiteten Aufträge mehrere Versanddienstleister relevant sind, den Exportprozess nacheinander für alle Datenformate durchführen.

|*Trennzeichen*
|Trennzeichen wählen. +
Dieses Trennzeichen auch beim Import der Datei in die Software Ihres Versanddienstleisters wählen.

2+|Aktion

|*Ändere Auftragsstatus*
|Auftragsstatus wählen, der den Aufträgen beim Export zugewiesen werden soll.
|====

[TIP]
.Datenformat UPS WorldShip 11
====
Wenn Sie eine Lieferanschriftenliste mit dem Datenformat UPS WorldShip 11 generieren, wird der Inhalt des Feldes *Adresszusatz* der Lieferanschrift in den Spalten *Str2* bzw. *Str3* ausgegeben. Der Adresszusatz wird in Teilen zu je 35 Zeichen fortlaufend auf diese Spalten verteilt, soweit die Spalten leer sind. Sind die Spalten nicht leer, wird der Adresszusatz nicht ausgegeben.
====

[#800]
== Paketnummern importieren

Mit einem Paketnummernimport im Menü *Aufträge » Fulfillment » Tab: Import Paketnummern* können Sie auch größere Mengen an Paketnummern komfortabel in Ihrem plentymarkets System bearbeiten.

Das Tab *Import Paketnummern* ist in die Bereiche *CSV-Import* und *Listen-Import* unterteilt. Im Bereich *CSV-Import* laden Sie eine Datei Ihres Versanddienstleisters in Ihr plentymarkets System. Im Bereich *Listen-Import* haben Sie die Möglichkeit, die Paketnummern mit Hilfe eines <<auftragsabwicklung/fulfillment/dokumente-erzeugen#1010, Barcodescanners>> zu importieren oder die Paketnummern manuell einzugeben.

[#900]
=== Paketnummern per CSV-Datei importieren

Gehen Sie wie im Folgenden beschrieben vor, um die Paketnummern per CSV-Datei zu importieren. Die CSV-Datei, die Sie importieren, wurde von einer Software Ihres Versanddienstleisters generiert.

[.instruction]
Paketnummern per CSV-Datei importieren:

. Öffnen Sie das Menü *Aufträge » Fulfillment*.
. Wechseln Sie in das Tab *Import Paketnummern*.
. Nehmen Sie die Einstellungen im Bereich *CSV-Import* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-paketnummern-importieren-csv>>.
. Klicken Sie auf *Import*. +
→ Die Paketnummern werden in Ihr plentymarkets System importiert.

[[tabelle-paketnummern-importieren-csv]]
.Einstellungen im Menü *Aufträge » Fulfillment » Tab: Import Paketnummern*
[cols="1,3"]
|====
|*Einstellung* |*Erläuterung*

|Option in der Dropdown-Liste
|Option aus der Dropdown-Liste wählen, z.B. *Auftrags-ID*. Spalte der CSV-Datei wählen, in der z.B. die *Auftrags-ID* oder eine andere Option enthalten ist, die zur Identifizierung der Pakete verwendet werden soll. +
Die Auftrags-ID sowie die Versandpaket-ID wird vom plentymarkets System generiert. Das *Zeichen Kunde* wird im Tab *Einstellungen* eines Auftrags gespeichert. +
Verfügbar sind folgende Optionen:

* Auftrags-ID
* Barcode Auftrags-ID
* Versandpaket-ID
* Auftrags- und Versandpaket-ID
* Zeichen Kunde

|*Paketnummer*
|Spalte der CSV-Datei wählen, in der die Paketnummer enthalten ist.

|*Feldtrennzeichen*
|Trennzeichen wählen.

|*Datei*
|Nach Klick auf *Datei auswählen* die CSV-Datei des Versanddienstleisters für den Import der Paketnummern wählen.
|====

[#1000]
=== Paketnummern manuell importieren

Im Menü *Aufträge » Fulfillment » Tab: Import Paketnummern* im Bereich *Listen-Import* haben Sie die Möglichkeit, die Paketnummern mit der Auftrags-ID manuell einzugeben. Alternativ können Sie diese mit einem Barcodescanner von der Packliste abscannen. Wie Sie dabei vorgehen müssen, wird im nächsten Kapitel beschrieben.

[#1010]
=== Paketnummern mit Hilfe eines Barcodescanners importieren

Wenn ein Auftrag fertig gepackt wurde, sollte in plentymarkets der Warenausgang gebucht werden. Der *Status [7] Warenausgang gebucht* und das aktuelle Datum als Warenausgangsdatum werden am Auftrag gespeichert. Dieser Vorgang kann beispielsweise durch Abscannen des Barcodes auf der Rechnung, Lieferschein, Packliste oder dem Adressetikett durchgeführt werden. Stellen Sie sicher, dass Ihr Barcodescanner korrekt eingerichtet ist.

Im Folgenden wird der Scan-Vorgang beispielhaft anhand der Packliste beschrieben.

[.instruction]
Paketnummern mit Hilfe eines Barcodescanners importieren:

. Öffnen Sie das Menü *Aufträge » Fulfillment*.
. Klappen Sie den Bereich *Rechnungen erzeugen* auf.
. Erzeugen Sie eine oder mehrere Rechnungen. Beachten Sie dazu die Erläuterungen auf der Handbuchseite <<auftragsabwicklung/auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnungen erzeugen>>.
. Erstellen Sie aus diesen Rechnungen eine Packliste aller Aufträge, die nun verpackt werden müssen. Beachten Sie dazu die Erläuterungen auf der Handbuchseite <<auftragsabwicklung/auftraege/auftragsdokumente/packliste#, Packliste>>.
. Sobald ein Paket gepackt wurde, markieren Sie diesen Auftrag auf der Packliste.
. Kleben Sie außerdem unterhalb des Barcodes der Auftrags-ID einen kleinen Aufkleber mit der Paketnummer (Lightlabel) auf.
. Öffnen Sie das Menü *Aufträge » Fulfillment*.
. Wechseln Sie in das Tab *Import Paketnummern*.
. Platzieren Sie den Cursor im ersten Feld im Bereich *Listen-Import*.
. Scannen Sie zunächst die Auftrags-ID und anschließend die Paketnummer. +
→ Durch einen Klick auf *Speichern* werden die Paketnummern bei allen Aufträgen im Tab *Einstellungen* gespeichert.

Richten Sie im Menü *System » Aufträge » Ereignisse* eine Ereignisaktion ein und wählen Sie für das Ereignis *Auftragsänderung &gt; Paketnummer* die Aktion *Auftrag &gt; Warenausgang buchen*. Zudem können Sie Ihren Kunden eine E-Mail-Vorlage mit der Paketnummer und einem Link zu Paketverfolgung senden. Weitere Informationen zu Ereignisaktionen finden Sie auf der Handbuchseite <<basics/automatisierung/ereignisaktionen#, Ereignisaktionen>>.

[#300]
== Adressetikett einrichten

Im Gegensatz zu Versandlabels können Sie für Adressetiketten in plentymarkets genau festlegen, welche Informationen an welcher Stelle enthalten sein sollen. Da Sie Adressetiketten nicht vorgefertigt von einem Versanddienstleister erhalten, ist weder das Porto bereits abgerechnet, noch eine Sendungsnummer enthalten. Die Verwendung von Adressetiketten eignet sich besonders für Warensendungen, z.B. den Versand von Büchern, die Sie durch den individuellen Aufdruck Büchersendung u.U. günstiger versenden können als über das Gewicht des Pakets. Sie können in plentymarkets die Adressetikettenvorlage einrichten, eine PDF-Datei erzeugen und mit dieser dann Etiketten drucken.

[TIP]
.Wann Paketdienst-Software nutzen?
====
Das Generieren von Adressetiketten in plentymarkets ist speziell für Warensendungen vorgesehen. Wenn das Paket über einen Paketdienst versendet wird, nutzen Sie die Software dieses Paketdienstes, um Versandlabels zu drucken. plentymarkets unterstützt den Datenaustausch mit verschiedenen Paketdiensten.
====

Wenn Sie bereits eine Adressetikettenvorlage erstellt und eine PDF-Vorlage gespeichert haben, fahren Sie fort mit Kapitel <<auftragsabwicklung/fulfillment/dokumente-erzeugen#700, Adressetikett erzeugen>>.

[#400]
=== Adressetikettenvorlage erstellen

Bevor Adressetiketten gedruckt werden können, müssen Sie eine Vorlage erstellen. Gehen Sie wie im Folgenden beschrieben vor, um eine neue Vorlage zu erstellen.

[.instruction]
Adressetikettenvorlage erstellen:

. Öffnen Sie das Menü *System » Aufträge » Dokumente » Adressetikett*.
. Wechseln Sie in das Tab *Neue Vorlage*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-adressetikettenvorlage-erstellen>>.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Positionierung durch Koordinaten
====
Die Inhalte eines Etiketts werden durch Eingabe von Koordinaten (X, Y) positioniert. Die obere linke Ecke eines Etiketts ist der Ausgangspunkt.
====

[[tabelle-adressetikettenvorlage-erstellen]]
.Einstellungen im Menü *System » Aufträge » Dokumente » Adressetikett*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Layout-Titel*
|Name der Adressetikettenvorlage. Dieser Name wird in Dropdown-Listen zur Auswahl der Vorlage angezeigt.

|*Zeichensatz*
|*Unicode* oder *ISO-8859-1* wählen. Das Generieren von PDF-Dokumenten kann länger dauern, wenn der Zeichensatz Unicode verwendet wird.

|*Seite*
|Werte (in mm) für die *Breite* und die *Höhe* des verwendeten Etikettenpapiers eingeben.

|*Seitenrand*
|Werte (in mm) für den linken und den oberen Seitenrand eingeben. +
Der rechte und der untere Seitenrand müssen beim Druck ebenfalls beachtet werden. In der Regel sind die Abstände die gleichen wie der linke und der obere Rand. Dazu ggf. die Angaben des Etikettenherstellers beachten.

|*Etikett*
|Werte (in mm) für die *Breite* und die *Höhe* der verwendeten Etiketten eingeben. +
Die genauen Maße sind beim Etikettenpapier angegeben. Die Seitenränder sowie die Maße des verwendeten Druckpapiers beachten.

|*Zeilen pro Seite*
|Anzahl der Zeilen, die pro Seite erzeugt werden sollen, eingeben.

|*Spalten pro Seite*
|Anzahl der Spalten, die pro Seite erzeugt werden sollen, eingeben.

|*Reihenfolge von Ort und Postleitzahl*
|Reihenfolge aus der Dropdown-Liste wählen.

|*Ort und Land in Lieferanschrift in Großbuchstaben ausgeben*
|Wählen, ob Ort und Land in der Lieferanschrift in Großbuchstaben ausgegeben werden soll.

|*Land des Online-Shops in Lieferanschrift ausgeben*
|Wählen, ob das Land des Online-Shops in der Lieferanschrift ausgegeben werden soll.

|Weitere Optionen wie z.B. *Lieferanschrift*, *Rechnungsanschrift*, *Name* und *Kunden-ID*
|Zahlen für die Positionierung eingeben.

|*Artikelauflistung*
|Die Artikelauflistung bestimmt, wie die Artikeldaten auf dem Etikett angezeigt werden. Es gibt 2 Typen: *Standard* und *Individuell*. Eine Erläuterung zu diesen beiden Typen finden Sie im Kapitel <<auftragsabwicklung/fulfillment/dokumente-erzeugen#600, Artikelauflistung>>.

|*Inhalt der Auftrags-ID*
|*Auftrags-ID des Hauptauftrages* oder *Auftrags-ID des Lieferauftrages* wählen.

|*Barcode horizontal*
|Koordinaten zur Positionierung des Barcodes und Maße eingeben.

|*Infoleiste*
|Die Infoleiste beinhaltet alle wichtigen Informationen. Diese Informationen werden in einer Zeile zusammengefasst, was folgendermaßen aussieht: +
RG:Rechnungs.NR / ZA: (Zahlungsart) / SU: Preissumme / Datum

|*Kundeneigenschaften*
|Die Koordinaten zur Positionierung der Kundeneigenschaften eingeben. Die <<crm/kontakte-verwalten#4000, Eigenschaft>> aus der Dropdown-Liste wählen. Auf den Adressetiketten wird der Text angezeigt, der im Menü <<crm/kontakte-verwalten#4000, CRM » Kontakte » Kontakt öffnen » Ansicht: Eigenschaften>> gespeichert wurde.

|*Freitextfelder 1 bis 10*
|Freitextfelder ermöglichen das Anzeigen beliebiger Texte, die dort eingegeben wurden. +
*_Beispiel_*: Ein verbreitetes Anwendungsbeispiel ist das Speichern des Absenders.
|====

Bereits erstellte Vorlagen können Sie im Menü *System » Aufträge » Dokumente » Adressetikett » Tab: Vorlagen* aus der Dropdown-Liste *Vorlage* wählen und bearbeiten. Sie haben auch die Möglichkeit, eine Vorschau des Etiketts anzuzeigen und die Vorlage im Vorschaumodus direkt zu drucken. Wenn Sie die Vorlage löschen, wird auch die Verknüpfung der PDF-Vorlage gelöscht.

Der Bereich *PDF-Vorlage* wird erst nach dem Speichern einer Vorlage sichtbar und dient dazu, dem Dokument optional eine PDF-Vorlage zu speichern. Wie Sie die PDF-Vorlage speichern, wird im nächsten Kapitel beschrieben.

[#500]
=== PDF-Vorlage speichern

Wenn Sie eine Adressetikettenvorlage erstellt haben, wird im Menü *System » Aufträge » Dokumente » Adressetikett* über dem Bereich *Einstellungen* der Bereich *PDF-Vorlage* sichtbar. Sie können dort pro Adressetikettenvorlage eine PDF-Vorlage speichern, um z.B. für Ihre Adressetiketten ein bestimmtes Layout zu speichern.

[.instruction]
PDF-Vorlage speichern:

. Öffnen Sie das Menü *System » Aufträge » Dokumente » Adressetikett*.
. Wählen Sie die *Vorlage*.
. Klicken Sie bei *Upload* auf *Datei auswählen*.
. Wählen Sie die PDF-Datei von Ihrem Computer.
. *Speichern* Sie die Einstellungen.

Nach erneutem Öffnen der Adressetikettenvorlage ist unter *Vorlage* der Link *Vorlage anzeigen* sichtbar. Über diesen Link können Sie die PDF-Vorlage, die für diese Adressetikettenvorlage gespeichert ist, ansehen. Wenn Sie eine andere PDF-Vorlage speichern möchten, laden Sie, wie zuvor beschrieben, eine neue PDF-Datei hoch. Die bestehende PDF-Vorlage wird überschrieben.

[#600]
=== Artikelauflistung

Die Artikelauflistung bestimmt, wie die Artikeldaten auf dem Etikett angezeigt werden. Sie können den Typ *Standard* oder *Individuell* wählen.

[.subhead]
Typ: Standard

Wenn Sie die Option *Standard* wählen, müssen Sie die Koordinaten der Artikelauflistung, die Schriftgröße und den Schriftschnitt eingeben. Sie bestimmen damit die Position der gesamten Artikelauflistung auf den Etiketten. Die einzelnen Textelemente, wie z.B. Artikel-ID bzw. Varianten-Nr., Name und Menge, werden im Gegensatz zur Option *Individuell* jedoch automatisch positioniert.

[.subhead]
Typ: Individuell

Wenn Sie die Option *Individuell* wählen, werden weitere Optionen eingeblendet, für die Sie individuell die Positionen auf dem Etikett einstellen können. Geben Sie die Koordinaten der Artikelauflistung, die Schriftgröße und den Schriftschnitt ein. Sie bestimmen damit die Position der gesamten Artikelauflistung auf den Etiketten. Entscheiden Sie außerdem, welche Textelemente, d.h. *Menge*, *Name*, *Artikel-ID* bzw. *Varianten-Nr.*, *Gewicht (kg)*, *Wert*, *Zolltarifnummer*, *Herstellerland*, *Lagerort* und *Limit* auf den Etiketten angezeigt werden sollen und positionieren Sie diese Elemente. Anhand der X-Koordinate, des Schriftschnitts und der Breite legen Sie fest, wie die einzelnen Elemente der Artikelauflistung aussehen sollen. Die Option *Breite* legt fest, bis zu welcher Textbreite (in mm) jede der Optionen angezeigt werden soll.

[#700]
=== Adressetikett erzeugen

Nachdem Sie eine Vorlage für das Adressetikett erstellt und gespeichert haben, drucken Sie das Etikett über das Menü *Aufträge » Fulfillment » Adressetiketten*.

[.instruction]
Adressetikett erzeugen:

. Öffnen Sie das Menü *Aufträge » Fulfillment*.
. Klappen Sie den Bereich *Adressetiketten* auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-adressetikett-erzeugen>>.
. Klicken Sie auf das Zahnrad. +
→ Das Adressetikett wird in einem separaten Fenster geöffnet und kann dann gedruckt werden.

[[tabelle-adressetikett-erzeugen]]
.Einstellungen im Menü *Aufträge » Fulfillment » Bereich: Adressetiketten*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Suchfilter

|*Etiketten-Vorlage*
|Vorlage aus der Dropdown-Liste wählen.

|*Auftragsstatus*
|Status wählen, in dem sich die Aufträge befinden, für die Adressetiketten gedruckt werden sollen.

|*Auftrags-ID*
|Eine oder mehrere Auftrags-IDs eingeben. Adressetiketten werden dann ausschließlich für die eingegebenen Aufträge generiert. Mehrere IDs kommagetrennt eingeben.

|*Kunden-ID*
|Eine oder mehrere Kunden-IDs eingeben. Adressetiketten werden dann ausschließlich für die eingegebenen Kunden generiert. Mehrere IDs kommagetrennt eingeben.

|*Artikel*
|Eine oder mehrere Artikel-IDs eingeben. Adressetiketten werden dann ausschließlich für die eingegebenen Artikel generiert. Mehrere IDs kommagetrennt eingeben.

|*Typ*
|Typ aus der Dropdown-Liste wählen. Option *Auftrag* wählen, um Adressetiketten nur für Aufträge zu generieren. Option *ALLE* wählen, um Adressetiketten für alle Auftragstypen, wie z.B. auch Gutschriften und Retouren, zu generieren.

|*Versanddienstleister*
|Versanddienstleister aus der Dropdown-Liste wählen, um Adressetiketten nur für einen Versanddienstleister zu generieren. Option *ALLE* wählen, um Adressetiketten für alle Versanddienslteister zu generieren.

|*Mandant (Shop)*
|Mandant (Shop) aus der Dropdown-Liste wählen, um Adressetiketten nur für einen Mandaten zu generieren. Option *ALLE* wählen, um Adressetiketten für alle Mandanten zu generieren.

|*Lager*
|Lager aus der Dropdown-Liste wählen, um Adressetiketten nur für ein Lager zu generieren. Option *ALLE* wählen, um Adressetiketten für alle Lager zu generieren.

|*starten ab Zeile*
|Zahl eingeben, ab welcher Zeile der Druck starten soll. +
Diese Option ist hilfreich, wenn Sie Etikettenpapier verwenden. Wenn Sie z.B. letzten Druckvorgang nur die ersten 3 Zeilen auf einer Seite Etikettenpapier benutzt haben, könnten Sie den nächsten Druckvorgang ab Zeile 4 starten. Somit können Sie noch die restlichen Etiketten auf der Seite verwenden.

|*Sortierung*
|Wählen, nach welchem Erkennungsmerkmal die erzeugten Adressetiketten sortiert werden sollen. Option *KEINE* wählen, wenn keine spezielle Sortierung gewünscht ist.

|*Gruppierung*
|Wählen, nach welchem Kriterium die erzeugten Adressetiketten generiert und gruppiert werden sollen. Eine der folgenden Optionen wählen: +
*Ein Etikett pro Auftrag* = Wird das Adressetikett vom Auftrag aus generiert, wird nur ein Etikett für den gesamten Auftrag erzeugt. +
*Ein Etikett pro Auftragsposition* = Für jede Position im Auftrag wird im PDF ein Etikett erzeugt. +
*Ein Etikett pro Artikel* = Für jeden Artikel im Auftrag wird im PDF ein Etikett erzeugt. +
*Ein Etikett pro Versandpaket* = Für jedes Versandpaket wird im PDF ein Etikett erzeugt. Gemeint sind die <<auftragsabwicklung/fulfillment/versand-vorbereiten#1900, Versandpakete>> des Auftrags, wie diese im Versand-Center zu sehen sind.

|*Limit*
|Wählen, wie viele Aufträge pro Durchgang bearbeitet werden sollen. +
Pro Durchgang kann höchstens das maximal einstellbare Limit an Aufträgen bearbeitet werden. Wenn die Anzahl der Aufträge, die bearbeitet werden sollen, größer ist als das höchste einstellbare Limit, muss der Prozess entsprechend oft wiederholt werden. In der Grundeinstellung ist in manchen der Untermenüs das geringste Limit eingestellt, um eine optimale Systemleistung zu gewährleisten.

2+|Aktion

|*Ändere Auftragsstatus*
|Status wählen, der den Aufträgen nach erfolgreichem Rechnungsabruf zugewiesen werden soll.
|====

[NOTE]
.Etikettendrucker verwenden
====
Die Verwendung von Etikettendruckern ist möglich. Dabei kommen meist Etikettenrollen zum Einsatz. Die dafür benötigten Etiketten können Sie im Menü *System » Aufträge » Dokumente » Adressetikett* erzeugen. Geben Sie *1* bei den Optionen *Zeilen pro Seite* und *Spalten pro Seite* ein. Dadurch erhalten Sie pro PDF-Seite ein Etikett. Die Maße des Etiketts würden in dem Fall denen der Seite entsprechen.
====

[#1100]
== Einlieferungsliste generieren

Im Menü *Aufträge » Fulfillment » Bereich: Einlieferungsliste* nehmen Sie Einstellungen vor, mit denen Sie definieren, welche Pakete sich auf der anschließend zu generierenden Einlieferungsliste befinden sollen. Durch Auswahl der Suchfilter können Sie z.B. eine Einlieferungsliste für alle Aufträge, die sich im *Status [6] Gerade im Versand* befinden, generieren.

[.instruction]
Einlieferungsliste generieren:

. Öffnen Sie das Menü *Aufträge » Fulfillment*.
. Klappen Sie den Bereich *Einlieferungsliste* auf.
. Nehmen Sie die Einstellungen für die Suchfilter vor. Beachten Sie dazu die Erläuterungen in <<tabelle-einlieferungsliste-generieren>>.
. Klicken Sie auf das Zahnrad, um die Einlieferungsliste zu generieren. +
→ Eine Datei mit den Daten, die den von Ihnen gewählten Suchkriterien entsprechen, wird generiert.

[[tabelle-einlieferungsliste-generieren]]
.Einstellungen im Menü *Aufträge » Fulfillment » Bereich: Einlieferungsliste*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Auftragsstatus*
|Status der zu suchenden Aufträge wählen. Nur Aufträge mit diesem Status werden in die Einlieferungsliste miteinbezogen.

|*Eigner*
|Eigner der zu suchenden Aufträge oder die Option *ALLE* wählen.

|*Warenausgang*
|Mit einem Klick in das Feld wird ein Kalender eingeblendet. Datum aus dem Kalender wählen oder Datum manuell eingeben, um die Aufträge der Einlieferungsliste einzugrenzen. Aufträge werden nur in die Einlieferungsliste miteinbezogen, wenn der Warenausgang an diesem Tag gebucht wurde. Wenn kein Datum gewählt bzw. eingegeben wird, wird nach Aufträgen, in denen kein Warenausgang gebucht wurde, gesucht.

|*Versandart*
|Versanddienstleister der zu suchenden Aufträge oder die Option *ALLE* wählen.

|*Listennummer*
|Nummer der Einlieferungsliste eingeben. Diese Zahl wird auf der generierten Einlieferungsliste angezeigt. Wenn die Einlieferungsliste zum ersten Mal generiert wird, steht standardmäßig die Zahl 1 in diesem Feld. Jedes Mal, wenn eine Einlieferungsliste generiert wird, erhöht sich dieser Wert automatisch um 1.

|*Kundennummer*
|Kundennummer eingeben. Diese Zahl wird auf der generierten Einlieferungsliste angezeigt.

|*Titel*
|Titel für die Einlieferungsliste eingeben. Der Titel wird auf der generierten Einlieferungsliste angezeigt.

|*Name*
|Name eingeben. Der Name sowie die Kontaktdaten (Anschrift, PLZ und Ort) werden auf der generierten Einlieferungsliste angezeigt.

|*Anschrift*
|Eigene Anschrift eingeben.

|*PLZ / Ort*
|PLZ und Ort eingeben.

|*Ausgabeformat*
|Wählen, in welchem Format die Einlieferungsliste generiert werden soll. Zur Auswahl stehen *PDF* und *CSV*.
|====
