= Versand vorbereiten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Versanddienstleister, Fulfillment-Dienstleister, Lieferländer, Regionen, Versandprofile, Portotabelle, Versandpakete, Versandkosten, DHL-Packstation, Tracking-URL
:description: Erfahren Sie, wie Sie Versandprofile, Versandpakete und Versanddienstleister in plentymarkets einrichten.
:position: 10

In plentymarkets haben Sie als Händler die Möglichkeit, für den Versand Ihrer Artikel einen Dienstleister zu beauftragen, der je nach Vertrag die Waren bei Ihnen abholt und versendet und dann den Status an Ihr plentymarkets System zurückmeldet.

plentymarkets ermöglicht genau abgestimmte Versandprozesse, die in hohem Maß automatisiert ablaufen. Von der Verknüpfung der Artikel mit den Versandprofilen über die Versandanmeldung bis zur Ausgabe eines Versandlabels steuert Ihr plentymarkets System die gesamten Abläufe - und das besonders effizient mit den Prozessen des **<<basics/automatisierung/plentymarkets-client#, plentymarkets Client>>**. Der anfängliche Konfigurationsaufwand zahlt sich durch eine reibungslose Abwicklung aus, die ein sorgfältig eingestelltes System ermöglicht.

Auf dieser Handbuchseite wird beschrieben, wie Sie den Versand vorbereiten und <<auftragsabwicklung/fulfillment/versand-vorbereiten#2500, **versanddienstleisterspezifische Einstellungen**>> vornehmen. Einige Dienstleister bieten einen kompletten Service an, der die Lagerung der Artikel einschließt. Weitere Informationen dazu finden Sie im Kapitel **<<auftragsabwicklung/fulfillment/versand-vorbereiten#4700, Fulfillment-Dienstleister im Überblick>>**.

[#100]
== Lieferländer einrichten

Im Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Lieferländer** richten Sie die Länder ein, die Sie beliefern möchten. Die Übersicht enthält alle in plentymarkets verfügbaren Lieferländer. In der Spalte **Standardname** ist die Systembezeichnung des Landes dargestellt. Der Standardname kann nicht geändert werden und wird Ihren Kunden nicht angezeigt. In der Spalte **Name** geben Sie den Namen ein, der Ihren Kunden angezeigt werden soll.

[#200]
=== Lieferländer bearbeiten und aktivieren

Im Tab **Übersicht** bearbeiten und aktivieren Sie die Lieferländer.

[.instruction]
Lieferländer bearbeiten und aktivieren:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Lieferländer » Tab: Übersicht**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen.

.Übersicht der Lieferländer im Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Lieferländer**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**ID**
|Interne ID des Lieferlandes. Wird automatisch vergeben und kann nicht geändert werden.

|**Name (xy)**
|Ländername eingeben, wie er im Webshop und auf Dokumenten erscheinen soll. +
__**Wichtig**__: Der Name des Lieferlandes kann in verschiedenen Sprachen eingegeben werden. Dazu im Tab **Filter** im Dropdown-Menü **Sprache (Name)** das Sprachkürzel wählen und auf **Suchen** klicken. Die eingegebenen Namen der Sprache werden angezeigt. Die Bezeichnungen in der Spalte **Name (xy)** in der Übersicht nach Wunsch anpassen oder ergänzen und speichern.

|**Standardname**
|Systembezeichnung des Lieferlandes. Kann nicht geändert werden.

|**Aktiv**
|Eine der folgenden Optionen wählen: +
**Aktiv** = Lieferland steht zur Verfügung. +
**Inaktiv** = Lieferland steht nicht zur Verfügung. +
**Backoffice aktiv** = Lieferländer mit dieser Eigenschaft sind nur im plentymarkets System und nicht im Webshop sichtbar. +
**Lieferant aktiv** = Lieferländer mit dieser Eigenschaft stehen für die Einstellung als **Standardlieferland** im Menü **<<omni-channel/online-shop/webshop-einrichten/bestellvorgang#, Einstellungen » Mandant (Shop) » Standard » Bestellvorgang » Grundeinstellungen>>** nicht zur Verfügung.

|**Lager**
|Lager wählen, das dem Lieferland als Hauptlager zugeordnet werden soll und z.B. in Aufträgen automatisch eingestellt sein soll. **ALLE** wählen, wenn alle Lager dem Lieferland zugeordnet werden sollen. In diesem Fall wird für Aufträge automatisch das Lager mit der kleinsten ID gewählt. Dazu auch die <<auftragsabwicklung/auftraege/_grundeinstellungen#, **Lagereinstellungen**>> im Menü **Einstellungen » Aufträge » Grundeinstellungen** beachten.

|**Sprache**
|Festlegen, welches Lieferland für welche Sprache das Standardlieferland sein soll. Einem Lieferland kann nur eine Sprache zugeordnet werden.
|====

[#300]
=== Lieferländer suchen und anzeigen

Standardmäßig werden alle Lieferländer im Tab **Übersicht** angezeigt. Im Tab **Filter** können Sie die Auswahl der angezeigten Lieferländer anhand verschiedener Parameter filtern und damit entscheiden, welche Lieferländer in der Übersicht angezeigt werden sollen.

[.instruction]
Lieferländer suchen und anzeigen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Lieferländer » Tab: Filter**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 2.
. Klicken Sie auf **Suchen**. +
→ Die gefundenen Lieferländer werden im Tab **Übersicht** angezeigt.

.Filteroptionen für Lieferländer
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**ID**
|Filtert Lieferländer anhand der internen ID des Lieferlandes.

|**Name**
|Filtert Lieferländer anhand des Namens des Lieferlandes.

|**Standardname**
|Filtert Lieferländer anhand des Standardnamens des Lieferlandes.

|**Lager**
|Lager wählen, wenn nur die Lieferländer eines Lagers angezeigt werden sollen.

|**Aktiv**
|**Inaktiv** = Nur die Lieferländer anzeigen, die nicht aktiviert sind. +
**Aktiv** = Nur die Lieferländer anzeigen, die aktiviert sind. +
**Backoffice aktiv** = Nur Lieferländer mit der Eigenschaft **Backoffice aktiv** anzeigen. +
**Lieferant aktiv** = Nur Lieferländer mit der Eigenschaft **Lieferant aktiv** anzeigen.

|**Sprache (Name)**
|Sprache wählen.
|====

[#400]
== Region erstellen

Unter einer Region fassen Sie Lieferländer zusammen, für die gemeinsame Versandkosten gelten.

Im Tab **Neue Region** erstellen Sie die Regionen, indem Sie jeder Region die passenden Lieferländer zuordnen. Die Regionen sind dann im Tab **Übersicht** verfügbar und können dort angepasst werden. Überlegen Sie sich vor dem Erstellen, in wie viele und in welche Regionen sich Ihre Lieferländer sinnvoll zusammenfassen lassen, da in den Versandprofilen die Versandkosten pro Region und nicht für jedes Lieferland eingegeben werden. Aus europäischer Sicht sind z.B. mindestens die 3 folgenden Regionen sinnvoll: Inland, Europa und Welt.

[TIP]
.Sind alle benötigten Lieferländer aktiviert?
====
Bevor Sie Regionen erstellen können, müssen Sie alle Lieferländer aktivieren, die Sie für den Versand benötigen. Ein Lieferland kann nur einer Region zugeordnet werden und ist dann für weitere Regionen nicht mehr verfügbar.
====

[.instruction]
Region erstellen:

. Klicken Sie auf das Tab **Neue Region**. +
→ Unter **Verfügbare Länder** sehen Sie alle Lieferländer, die noch keiner Region zugeordnet wurden.
. Wählen Sie die Lieferländer unter **Verfügbare Länder**.
. Verwenden Sie die Pfeile, um die markierten Lieferländer in das Fenster **Ausgewählte Länder** zu verschieben. Die Doppelpfeil-Buttons verschieben alle Länder eines Fensters in das andere Fenster.
. Geben Sie in der Zeile **Name** den Namen für die Region ein.
. **Speichern** Sie die Einstellungen. +
→ Die neu angelegte Region wird im Tab **Übersicht** angezeigt.
. Legen Sie nach gleichem Muster ggf. weitere Regionen an, bis alle Lieferländer einer Region zugeordnet sind und die Liste der verfügbaren Länder im Fenster **Verfügbare Länder** vollständig leer ist.

[IMPORTANT]
.Alle Lieferländer verteilen
====
Alle Lieferländer müssen einer Region zugeordnet werden, da sonst kein gültiges Versandprofil erstellt werden kann.
====

[.subhead]
Region bearbeiten

Gehen Sie wie im Folgenden beschrieben vor, um die Region zu bearbeiten.

[.instruction]
Region bearbeiten:

. Öffnen Sie die Region im Tab **Übersicht**.
. Passen Sie die Einstellungen ein.
. **Speichern** Sie die Einstellungen.

[IMPORTANT]
.Bedingungen zum Löschen einer Region
====
Eine Region kann nur gelöscht werden, wenn sie in den Versandprofilen nicht mehr verwendet wird. Wenn Sie beim Löschen einer Region eine Fehlermeldung erhalten, prüfen Sie, ob in den Portotabellen noch Einstellungen zu dieser Region vorhanden sind. Eine Region kann erst gelöscht werden, wenn diese Querverbindungen vollständig entfernt wurden.
====

[#500]
== Artikelpakete und Absenderdaten eingeben

Im Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » Grundeinstellungen** entscheiden Sie, welche Daten zum Versanddienstleister übermittelt werden sollen, wenn <<artikel/artikel-verwalten#920, **Artikelpakete**>> zum Einsatz kommen. Sie können entweder die Versanddaten der Basisartikel oder des Artikelpakets übermitteln. Die Einstellung zu Artikelpaketen gilt für alle Versanddienstleister in Ihrem plentymarkets System. Außerdem speichern Sie in diesem Menü Absenderdaten für alle in Ihrem plentymarkets System erstellten <<warenwirtschaft/lager-einrichten#, **Lager**>>. Die Absenderdaten werden pro Lager gespeichert. Sie finden in diesem Menü die Lager aller aktiven Lieferländer aufgelistet.

[.instruction]
Artikelpakete und Absenderdaten eingeben:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » Grundeinstellungen**.
. Wählen Sie die Einstellung für **Artikelpakete**.
. Klappen Sie das Lager im Bereich **Absenderdaten** auf.
. Geben Sie die Daten ein.
. **Speichern** Sie die Einstellungen.

[#600]
== Beim Versanddienstleister registrieren

Um die Schnittstelle zum Versanddienstleister in plentymarkets einzurichten, registrieren Sie sich zunächst bei dem Versanddienstleister. Informieren Sie sich auf der Website des Versanddienstleisters.

[#700]
== Schnittstelle zum Versanddienstleister  einrichten

Die Schnittstelle eines Versanddienstleisters richten Sie nach dem folgenden Schema ein. Welche Daten Sie im Menü des Versanddienstleisters eingeben müssen, erfahren Sie in den Unterkapiteln des Kapitels **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2500, Versanddienstleister im Überblick>>**.

[.instruction]
Schnittstelle zum Versanddienstleister einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister**.
. Öffnen Sie das Menü des Versanddienstleisters.
. Geben Sie die Daten ein.
. Beachten Sie die Informationen zum Versanddienstleister in den Unterkapiteln des Kapitels **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2500, Versanddienstleister im Überblick>>**.
. **Speichern** Sie die Einstellungen.

[#800]
== Versanddienstleister erstellen

Erstellen Sie den Versanddienstleister nach folgendem Schema.

[.instruction]
Versanddienstleister erstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versanddienstleister**.
. Klicken Sie im Tab **Übersicht** auf **Neu**. +
→ Ganz unten wird eine neue Zeile hinzugefügt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 3.
. **Speichern** Sie die Einstellungen.

.Übersicht im Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versanddienstleister**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**ID**
|Interne ID des Versanddienstleisters. Wird automatisch vergeben und kann nicht geändert werden.

|**Name (xy)**
|Name des Versanddienstleisters eingeben, wie er im Warenkorb und auf der Rechnung erscheinen soll. Den tatsächlichen Namen des Versanddienstleisters oder eine allgemeine Bezeichnung eingeben, z.B. Versicherter Versand. Dieser Name ist für Kunden sichtbar.

|**Name (Backend)**
|Name des Versanddienstleisters eingeben, wie er systemintern erscheinen soll. Den tatsächlichen Namen des Versanddienstleisters oder eine alternative Bezeichnung, die den Dienstleister charakterisiert, z.B. Pakete Schweiz, eingeben. Dieser Name ist für Kunden nicht sichtbar.

|**Versanddienstleister**
|Versanddienstleister wählen. Dies ist besonders wichtig, wenn unter **Name** eine abweichende Bezeichnung eingegeben und/oder keine Tracking-URL verwendet wurde.

|**Tracking-URL**
|Tracking-URL des Versanddienstleisters eingeben.
|====

[TIP]
.Tracking-URL
====
Viele Versanddienstleister bieten eine Sendungsverfolgung mittels Tracking-URL an. Kunden sehen die Tracking-URL während der Auftragsabwicklung oder erhalten die URL in einer E-Mail zur Versandmitteilung. Fügen Sie dazu die Template-Variable **$TrackingURL** in Ihre E-Mail-Vorlage ein.

Eine funktionsfähige Tracking-URL enthält die Paketnummer und oftmals die Postleitzahl des Empfängers. Beachten Sie daher, dass die Template-Variablen **$PaketNr** und ggf. **$PLZ** in der Tracking-URL enthalten sind. Wenden Sie sich an Ihren Versanddienstleister, um die Tracking-URL zu erfahren. Links zu den Websites der Versanddienstleister finden Sie in den Unterkapiteln des Kapitels **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2500, Versanddienstleister im Überblick>>**.
====

[#900]
== Versanddienstleister suchen

Standardmäßig werden alle erstellten Versanddienstleister im Tab **Übersicht** angezeigt. Im Tab **Filter** können Sie die Auswahl der angezeigten Versanddienstleister anhand verschiedener Parameter filtern und damit entscheiden, welche Versanddienstleister in der Übersicht angezeigt werden sollen. Sie können die Versanddienstleister jederzeit im Tab **Übersicht** bearbeiten.

[.instruction]
Versanddienstleister suchen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versanddienstleister**.
. Nehmen Sie die Einstellungen im Tab **Filter** vor. Beachten Sie dazu die Erläuterungen in Tabelle 4.
. Klicken Sie auf **Suchen**. +
→ Die gefundenen Versanddienstleister werden im Tab **Übersicht** angezeigt.

.Filteroptionen für Versanddienstleister
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Suchen**
|Suche ausführen. Die Versanddienstleister, die mit den eingestellten Filterkriterien übereinstimmen, werden im Tab **Übersicht** aufgelistet.

|**Reset**
|Eingestellte Filterkriterien zurücksetzen.

|**ID**
|Filter Versanddienstleister anhand der internen ID des Versanddienstleisters.

|**Name**
|Filtert Versanddienstleister anhand des Namens des Versanddienstleisters

|**Standardname**
|Filtert Versanddienstleister anhand des Standardnamen des Versanddienstleisters.

|**Tracking-URL**
|Filtert Versanddienstleister anhand der Tracking-URL des Versanddienstleisters.

|**Versanddienstleister**
|Filtert Versanddienstleister anhand der Option, die im Dropdown-Menü **Versanddienstleister** gewählt wurde.

|**Sprache**
|Filtert Versanddienstleister anhand der Sprache.
|====

[#1000]
== Versandprofil erstellen

In den Versandprofilen stellen Sie Versandmöglichkeiten ein, die Ihre Kunden in der Kaufabwicklung wählen können oder die der Webshop bestimmten Auftragsarten automatisch zuweist. Zum Beispiel können Sie Ihren Kunden einen günstigen Standardversand und einen Expressversand gegen Aufpreis anbieten. Für eBay-Listings können Sie ein weiteres Versandprofil speichern, das Ihr Shop dann ausschließlich für Aufträge vom Marktplatz eBay verwendet. In den Unterkapiteln finden Sie Tipps und Tricks, die Sie beim Erstellen Ihrer Versandprofile anwenden können. Im Anschluss daran wird beschrieben, wie Sie in den Versandprofilen für jeden Versanddienstleister passende <<auftragsabwicklung/fulfillment/versand-vorbereiten#1500, **Portotabellen**>> für Ihre Regionen erstellen.

Erfahren Sie mehr zu Versandoptionen und Versandprofilen in den folgenden Videotutorials:

[.row]
====
[.col-md-6]
=====
video::77441308[vimeo]
=====

[.col-md-6]
=====
video::78421037[vimeo]
=====
====
Erstellen Sie nun das Versandprofil für den Versanddienstleister. Die Anzahl der Versandprofile ist abhängig von den benötigten Versandservices. Erstellen Sie also pro Versandservice ein eigenes Versandprofil.

[.instruction]
Versandprofil erstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Klicken Sie auf **Neu**.
. Wählen Sie den eben erstellten Versanddienstleister aus dem Dropdown-Menü.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 5.
. **Speichern** Sie die Einstellungen. +
→ Das Tab **Portotabelle** wird angezeigt.

.Grundeinstellungen eines Versandprofils
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**ID**
|Die ID des Versandprofils wird vom System vergeben und kann nicht geändert werden. Die ID wird nach dem Speichern des Versandprofils im Tab **Übersicht** angezeigt.

|**Versanddienstleister**
|Den zuvor erstellten Versanddienstleister aus dem Dropdown-Menü wählen.

|**Name**
|Der Name in diesem Feld wird im Webshop angezeigt. Name wählen, der dem Kunden angezeigt werden soll, z.B. Standard oder Express. Wenn der Webshop in mehreren Sprachen betrieben wird, das Dropdown-Menü verwenden, um den Namen in jeder benötigten Sprache zu speichern.

|**Name (Backend)**
|Name für das Versandprofil eingeben. Der Name erscheint nur im System und ist nicht für Kunden sichtbar.

|**Markierung**
|Icon wählen, das in der Auftragsübersicht angezeigt wird. Anhand der Markierung ist auf den ersten Blick sichtbar, welches Versandprofil hinterlegt ist.

|**Priorität**
|Bestimmt die Reihenfolge, in der Versandprofile einer Region aufgelistet werden.

|**Kategorie**
|Ermöglicht eine zusätzliche Priorisierung der Versandprofile im Warenkorb. Standardmäßig ist immer Kategorie **1** eingestellt, d.h. alle Versandprofile werden gleichwertig angezeigt. Weitere Informationen sowie ein Beispiel finden Sie im Kapitel **<<auftragsabwicklung/fulfillment/versand-vorbereiten#1300, Tipps und Tricks: Kategorie>>**.

|**Artikel-Portoaufschlag**
|Aktivieren, um die im Artikeldatensatz gespeicherten Portoaufschläge zu aktivieren. Bis zu 2 Portoaufschläge können bei der Hauptvariante eines Artikels im Bereich **Versand** eingegeben werden. **Portoaufschlag 1** fügt den Versandkosten den dort gespeicherten Preis für den ersten Artikel hinzu, **Portoaufschlag 2** gilt ab dem zweiten Artikel. Portoaufschläge bieten sich für größere oder sperrige Artikel an, deren Versand teurer ist. +
Weitere Informationen finden Sie im Kapitel **<<auftragsabwicklung/fulfillment/versand-vorbereiten#1100, Tipps und Tricks: Portoaufschläge>>**.

|**PostIdent**
|Legitimationsprüfung durch die Deutsche Post AG. Dient zur Verifizierung von Personen, z.B. im Zusammenhang mit dem nötigen Altersnachweis für FSK 18-Artikel. Zur Aktivierung Häkchen setzen. +
Für den Versand von FSK 18-Artikeln müssen diese Artikel mit einem Versandprofil verknüpft sein, bei dem die PostIdent-Funktion aktiviert ist.

|**Bei neuen Artikeln aktivieren**
|Aktivieren, wenn das Versandprofil neuen Artikeln automatisch zugeordnet werden soll. +
Diese Option sollte bei mindestens einem Versandprofil gewählt sein, damit neuen Artikeln immer automatisch dieses Versandprofil zugewiesen wird. Ist ein Artikel nicht mit mindestens einem Versandprofil verknüpft, kann dieser Artikel auch nicht versendet werden.

|**Inselzuschlag**
|Viele Versanddienstleister verlangen für den Versand in Inselregionen höhere Gebühren. Auf diesen Kosten sollte der Händler nicht sitzenbleiben. Daher pro Versandprofil einen pauschalen Aufschlag für den Versand in Inselregionen festlegen. Eine Liste der Postleitzahlen, für die Inselzuschlag berechnet wird, sollte ggf. beim Versanddienstleister erhältlich sein. Die Postleitzahlen der Inselregionen sind systemseitig hinterlegt. Der Abgleich mit dem Auftrag erfolgt automatisch. Bei Aktivierung des Inselzuschlags erfolgt eine Berechnung nur, wenn die Postleitzahl im System als Inselregion erkannt wird. +
Beim Berechnungstyp **Artikelporto** gilt der Inselzuschlag pro Stück.

|**Mandanten (Shops)**
|Eine der Optionen oder die Option **ALLE** wählen, wenn das Versandprofil für alle Webshops gelten soll. +
Diese Option wird nur angezeigt, wenn mindestens ein Mandant (Shop) eingerichtet ist.

|**Auftragsherkunft**
|Eine oder mehrere der Optionen wählen, um mögliche Auftragsherkünfte für dieses Versandprofil zu bestimmen, oder die Auswahl auf **ALLE** lassen, um alle Herkünfte freizugeben.

|**Gesperrte Zahlungsarten**
|Alle Zahlungsarten wählen, die für das Versandprofil nicht angeboten werden sollen. Bei Versandprofilen, die keine Nachnahmeoption enthalten oder bei denen Nachnahme nicht gewünscht wird, alle Optionen wählen, die mit Nachnahme in Verbindung stehen.

|**Gesperrte Kundenklassen**
|Eine oder mehrere Kundenklassen für das Versandprofil sperren.

|**Letzte Änderung**
|Bei Änderungen an den Einstellungen wird hier das Datum aktualisiert.

|**Versandgruppen**
|Wenn für Ihre Versandprofile Gruppen angelegt werden sollen, hier einen Namen für die Versandgruppe eingeben und auf **Hinzufügen** klicken. Diesen Namen in jedem Versandprofil, das zu dieser Gruppe gehören soll, eingeben. Es entstehen damit verschiedene Gruppen, die unterschiedliche Versandprofile enthalten. +
**__Beispiel__**: Versandgruppe A enthält die Versandprofile 1 und 2. Versandgruppe B enthält die Versandprofile 3 und 4. Wenn einem Artikel nun die Versandprofile 3 und 4 zugewiesen werden sollen, am Artikel im Tab **Global** im Bereich **Versandprofile** die Versandgruppe B im Dropdown-Menü wählen. +
Mit dieser Funktion können sehr einfach die Versandprofile für neue Artikel zugewiesen werden.

|**Versandkennung**
|Dieses Feld ist derzeit ohne Funktion.

2+|eBay

|**Konto**
|Ein oder mehrere eBay-Konten oder die Option **ALLE** wählen. +
__**Wichtig**__: Es müssen mindestens zwei Konten angelegt sein, andernfalls ist diese Option nicht sichtbar. Weitere Informationen finden Sie im Kapitel **<<auftragsabwicklung/fulfillment/versand-vorbereiten#1200, Tipps und Tricks: Versandkosten von Bestellungen über eBay>>**.

|**Listingtyp**
|Festlegen, für welchen Listing-Typ bei eBay dieses Versandprofil freigegeben werden soll.

2+|Weitere Optionen

|**Expressversand**
|Aktivieren, wenn dieses Versandprofil für einen Expressversand genutzt werden soll. +
__**Wichtig**__: Prüfen, ob Expressversand vom Service des Versanddienstleisters unterstützt wird. Nur dann kann die Option genutzt werden.

|**Treueprogramm**
|Ein oder mehrere Treueprogramme wählen. Die Treueprogramme können Sie mit <<omni-channel/multi-channel/ebay#6600, **eBay Plus**>> oder <<omni-channel/multi-channel/amazon#4200, **Amazon**>> verwenden. +
__**Wichtig**__: Versandprofile, bei denen hier ein Treueprogramm gewählt wurde, können ausschließlich für Aufträge des Marktplatzes genutzt werden und nicht für den Webshop. Wenn in einem Versandprofil z.B. die Option **eBay Plus** aktiviert ist, wird das Versandprofil nur noch für Aufträge von **eBay Plus** verwendet. Es gilt daher die Empfehlung, für die Nutzung eines Treueprogramms ein eigenes Versandprofil anzulegen.
|====

[#1100]
=== Tipps und Tricks: Portoaufschläge

Bei der Bestellung von Artikeln mit verschiedenen Portoaufschlägen werden die folgenden Teilbeträge addiert:

* Die im Versandprofil eingegebenen Versandkosten (Grundporto)
* Der Portoaufschlag 1 des Artikels mit dem höchsten eingegebenen Portoaufschlag
* Der Portoaufschlag 2 für jeden weiteren Artikel

[.subhead]
Beispiel: Portoaufschläge unterschiedlicher Artikel addieren

In diesem Beispiel bestellt ein Kunde 2 PCs und 2 Monitore. Für die Artikel sind folgende Versandkosten eingegeben:

**Artikel 1: PC**

* Grundporto (Versandprofil) = 3,99 EUR
* Portoaufschlag 1 = 5,00 EUR
* Portoaufschlag 2 = 3,00 EUR

**Artikel 2: Monitor**

* Grundporto (Versandprofil) = 3,99 EUR
* Portoaufschlag 1 = 4,00 EUR
* Portoaufschlag 2 = 2,00 EUR

Der Kunde bestellt 2 PCs und 2 Monitore. Bei der Bestellung ergeben sich folgende Versandkosten:

* 3,99 EUR (Grundporto) + 5,00 EUR (PC: Portoaufschlag 1) + 3,00 EUR (PC: Portoaufschlag 2) + 2,00 EUR (Monitor: Portoaufschlag 2) + 2,00 EUR (Monitor: Portoaufschlag 2) = 15,99 EUR

[.subhead]
Beispiel: Portoaufschläge für mehrere Exemplare des gleichen Artikels

In diesem Beispiel bestellt ein Kunde einmal einen PC, dann 2 PCs und dann 3 PCs. Für den Artikel sind folgende Versandkosten eingegeben:

**Artikel 1: PC**

* Grundporto (Versandprofil) = 3,99 EUR
* Portoaufschlag 1 = 5,00 EUR
* Portoaufschlag 2 = 3,00 EUR

Der Kunde bestellt einen PC, dann 2 PCs, dann 3 PCs. Bei der Bestellung ergeben sich folgende Versandkosten:

* Bei 1 PC: 3,99 EUR (Grundporto) + 5,00 EUR (Portoaufschlag 1) = 8,99 EUR
* Bei 2 PCs: 3,99 EUR (Grundporto) + 5,00 EUR (Portoaufschlag 1) + 3,00 EUR (Portoaufschlag 2) = 11,99 EUR
* Bei 3 PCs: 3,99 EUR (Grundporto) + 5,00 EUR (Portoaufschlag 1) + 3,00 EUR (Portoaufschlag 2) + 3,00 EUR (Portoaufschlag 2) = 14,99 EUR

[TIP]
.Versand nur über Aufschläge berechnen
====
Sie können die Funktion **Portoaufschlag** auch nutzen, um Ihre Versandkosten ausschließlich auf Basis der bestellten Ware berechnen zu lassen. Dazu müssen Sie allerdings Ihre Versandkosten pro Artikel in den Artikelstammdaten eingeben und im Versandprofil alle Portobeträge auf den Wert **Null** setzen.
====

[#1200]
=== Tipps und Tricks: Versandkosten von Bestellungen über eBay

Wir empfehlen, die von eBay ermittelten Versandkosten nicht zu übernehmen, sondern diese Versandkosten von plentymarkets ermitteln zu lassen. Dies hat den Vorteil, dass beim Kauf weiterer Artikel die Versandkosten ebenfalls korrekt ermittelt werden können. Auch kommt es in einigen Fällen vor, dass von eBay keine Versandkosten übermittelt werden. Dieser Fall wäre ebenfalls gelöst, indem plentymarkets die richtigen Versandkosten für Sie ermittelt.

[NOTE]
.eBay-Versandkostenermittlung einstellen
====
Wählen Sie im Menü **Einstellungen » Listings » Kaufabwicklung** bei der Option **Versandkosten neuer eBay-Aufträge** die Einstellung **von plentymarkets berechnen lassen**.
====

Sollen für eBay andere Versandkosten berechnet werden als bei Bestellungen über den Webshop, muss dafür ein eigenes Versandprofil erstellt werden. Bei diesem Versandprofil muss bei der Option **Auftragsherkunft** ausschließlich **eBay** eingestellt werden. Bei jedem Artikel, für den diese Einstellung gelten soll, muss dieses Versandprofil aktiviert werden. Demzufolge sind für diese Artikel mindestens zwei Versandprofile aktiviert: Einmal das Versandprofil mit den "normalen" Versandkosten und einmal das Versandprofil mit den eBay-Versandkosten.

[IMPORTANT]
.Eigenes Versandprofil pro eBay-Konto
====
Wenn Sie in Ihrem plentymarkets System mehrere eBay-Konten aktiviert haben, können Sie für jedes eBay-Konto ein eigenes Versandprofil festlegen. Die Konten können Sie dann unter der Option **eBay-Konto** im Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile » Tab: Base** wählen.
====

[#1300]
=== Tipps und Tricks: Kategorie

Die Kategorieoption ermöglicht eine zusätzliche Priorisierung der Versandprofile. Sie können damit bestimmen, welche Versandprofile im Warenkorb angezeigt werden. In der Grundeinstellung ist immer die Kategorie **1** eingestellt, d.h. es werden alle Versandprofile gleichwertig angezeigt.

Folgende Regeln gelten:

* Es wird immer das Versandprofil mit der niedrigsten Kategorie angezeigt.
* Bei mehreren Artikeln wird das gemeinsame Versandprofil mit der niedrigsten Kategorie angezeigt.
* Haben die Artikel kein gemeinsames Versandprofil, wird das Versandprofil mit der niedrigsten Kategorie gewählt.

[TIP]
."Ausfall-Versandprofil" erstellen
====
Erstellen Sie ein Versandprofil, dessen Kategorie höher ist als die der anderen Versandprofile. Dieses "Ausfall-Versandprofil" wird nur gewählt, wenn alle anderen Versandprofile nicht greifen bzw. nicht gewählt werden können.
====

[.subhead]
Beispiel: FSK 18-Artikel zusammen mit anderen Artikeln verkaufen

Mit der Kategorieeinstellung können Sie Artikel mit dem Versandprofil **Übergabe eigenhändig** (z.B. FSK 18-Artikel) auch zusammen mit anderen Artikeln verkaufen. Dies lösen Sie wie folgt:

**Artikel A**

* Versandprofil 1 (Kategorie 1)
* Versandprofil 2 (Kategorie 2)

**Artikel B** (FSK 18-Artikel)

* Versandprofil 2 (Kategorie 2)
* Versandprofil 3 (Kategorie 5)

Wenn nur der Artikel A gekauft wird, wird das Versandprofil 2 nicht angezeigt, da ein Versandprofil mit niedrigerer Kategorie vorhanden ist. Wenn Artikel A und B zusammen gekauft werden, hat Versandprofil 2 die niedrigste gemeinsame Kategorie und wird somit ausschließlich angezeigt.

[#1400]
=== Tipps und Tricks: Versandprofilkombinationen zur Fehlervermeidung

Achten Sie darauf, dass bei allen Artikeln, die zusammen gekauft werden können, mindestens ein übereinstimmendes Versandprofil gespeichert ist. Befinden sich zwei oder mehr Artikel im Warenkorb, die kein gemeinsames Versandprofil haben, wird das Porto von beiden Versandprofilen addiert. Allerdings wird nur der Versanddienstleister mit der höheren Priorität im Warenkorb angezeigt. Solch eine Versandprofilkombination ist nicht vorgesehen und führt zu unerwünschten Ergebnissen.

Um diese Fehlverhalten zu vermeiden, können Sie z.B. für alle Artikel ein DHL-Versandprofil speichern und nur für bestimmte Artikel ein zusätzliches Versandprofil.

[.subhead]
Beispiel: Kein gemeinsames Versandprofil

Es befinden sich zwei Artikel im Warenkorb, die kein gemeinsames Versandprofil haben.

**Artikel A**

* Versandprofil von DPD
* Pauschales Porto von 3,95 EUR

**Artikel B**

* Versandprofil von DHL
* Pauschales Porto von 2,95 EUR

Die Portobeträge der Versandprofile werden dann in der Kaufabwicklung im Webshop addiert. Der Kunde sieht also ein Gesamtporto von 6,90 EUR. Jedoch wird dem Kunden nur der Versanddienstleister mit der höheren Priorität im Warenkorb angezeigt.

[#1500]
== Portotabelle erstellen

Speichern Sie nun die Versandkosten für das Versandprofil im Tab **Portotabelle**. Speichern Sie die Portoeinstellungen für jede Region, die Sie im Versandprofil verwenden möchten. Wählen Sie zuerst den Berechnungstyp und das Porto. Nachdem Sie die Portotabelle gespeichert und neu geladen haben, sehen Sie ggf. weitere versanddienstleisterspezifische Einstellungen. Nehmen Sie daher zunächst die allgemeinen Einstellungen vor. Beachten Sie die Erläuterungen in Tabelle 6.

[IMPORTANT]
.Versandservices nicht bei jedem Versanddienstleister vorhanden
====
Nicht für alle Versanddienstleister ist die Auswahl eines Versandservices vorgesehen. Wenn vorhanden, werden die Versandservices in der Portotabelle des Versanddienstleisters angezeigt, nachdem Sie die Portotabelle gespeichert und neu geladen haben. Öffnen Sie das Versandprofil im Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**. Wechseln Sie in das Tab **Portotabelle** und klappen die Region auf. Im unteren Teil der Portotabelle werden die Versandservices angezeigt.
====

Erfahren Sie mehr über das Erstellen von Portotabellen und die <<auftragsabwicklung/fulfillment/versand-vorbereiten#1600, **Berechnungstypen**>> im folgenden Videotutorial:

video::180302214[vimeo]
[.instruction]
Portotabelle erstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie das Versandprofil.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Wählen Sie einen Berechnungstyp aus dem Dropdown-Menü. +
→ Je nachdem, welchen Berechnungstyp Sie wählen, werden im Folgenden unterschiedliche Feldnamen angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 6.
. **Speichern** Sie die Einstellungen.
. Laden Sie die Portotabelle neu. +
→ Wenn vorhanden, werden nun die Versandservices angezeigt.
. Wählen Sie den Versandservice aus dem Dropdown-Menü.

.Portotabelle eines Versandprofils
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Speichern**
|Einstellungen speichern.

|**Einstellungen kopieren nach**
|Überträgt die Einstellungen einer Region auf eine andere Region. Ein Fenster wird geöffnet mit einem Dropdown-Menü, das die Regionen zur Auswahl enthält. Region wählen und auf **Ausführen** klicken.

|**Verknüpfung löschen**
|Setzt alle Einstellungen zurück. Diese Funktion ist z.B. nötig, bevor eine Region gelöscht werden kann.

|**Berechnungstyp**
|**<<auftragsabwicklung/fulfillment/versand-vorbereiten#1600, Berechnungstyp>>** wählen. Der Berechnungstyp bildet die Grundlage für die Berechnung der Versandkosten.

2+|Versandkosten

|**Pauschales Porto**
|Versandkosten eingeben. +
Der angezeigte Feldname ist abhängig vom gewählten Berechnungstyp.

2+|Pauschalen

|**Versandkostenfrei ab Warenwert**
|Warenwert eingeben, ab dem die Lieferung für den Kunden versandkostenfrei erfolgt.

|**Ab Warenwert ... ; +
... pauschale Versandkosten von**
|In das Feld **Ab Warenwert ...** den Warenwert eingeben, ab dem die Lieferung zu einer festen Pauschale erfolgt. Die Pauschale im Feld **... pauschale Versandkosten von** eingeben. +
Dieser Betrag darf nicht höher sein als der Betrag für die Pauschale **Versandkostenfrei ab Warenwert**, da der Versand ab diesem Wert bereits kostenfrei ist.

2+|Beschränkungen

|**Beschränkungstyp**
|Beschränkungstyp wählen. +
Die Standardwährung wird verwendet, wenn eine Beschränkung anhand des Warenwerts gewählt wurde. +
Das beim Artikel gespeicherte Bruttogewicht wird verwendet, wenn eine Beschränkung anhand des Gewichts gewählt wurde.

|**Mindestwert**
|Wert eingeben. Erst ab diesem Wert, bezogen auf den angegebenen Beschränkungstyp, ist das Versandprofil gültig. +
Wenn unter **Beschränkungstyp** die Einstellung **Maximum (Kubikmeter)** gewählt wurde, muss der Wert hier in mm eingegeben werden.

|**Maximalwert**
|Wert eingeben. Bis zu diesem Wert, bezogen auf den angegebenen Beschränkungstyp, ist das Versandprofil gültig. +
Wenn unter **Beschränkungstyp** die Einstellung **Maximum (Kubikmeter)** gewählt wurde, muss der Wert hier in mm eingegeben werden.

2+|Allgemeine Konfiguration

|**Standardpaket**
|<<auftragsabwicklung/fulfillment/versand-vorbereiten#1900, **Versandpaket**>> wählen, das als Standardpaket für dieses Versandprofil verwendet werden soll. +
Diese Option wird erst sichtbar, nachdem die Portotabelle gespeichert und neu geladen wurde.

2+|Versanddienstleisterspezifische Einstellungen

|z.B. **DHL Intraship/Versenden**
|Die Einstellungen des Versanddienstleisters werden erst sichtbar, nachdem die Portotabelle gespeichert und neu geladen wurde.

2+|Weitere Konfigurationen

|**Amazon Prime**
|Nur verfügbar bei Buchung des Moduls Multi-Channel.
|====

[#1600]
== Berechnungstyp in der Portotabelle wählen

Die Berechnungstypen im Tab **Portotabelle** bieten unterschiedliche Möglichkeiten, Versandkosten je nach Artikel zu berechnen. So können Sie eine gewichts- oder volumenabhängige Versandkostenberechnung oder eine mengenabhängige Staffelung hinterlegen. Pro Region können Sie einen eigenen Berechnungstyp wählen. Im Folgenden wird jeder Berechnungstyp kurz erläutert. In Tabelle 7 finden Sie Hinweise, die generell für die Berechnungstypen gelten.

.Allgemeine Einstellungen zu den Berechnungstypen
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Maximumwerte**
|Wird der maximal hinterlegte Wert (Volumen, Gewicht, Preis, Menge) überschritten, können keine Versandkosten ermittelt werden. Daher sollte immer ein ausreichend hohes Maximum vorhanden sein.

|**Pauschalen**
|Zusätzlich kann ab einem bestimmten Warenwert ein pauschaler Versandkostenbetrag hinterlegt werden. Erreicht die Bestellung diesen Warenwert oder wird dieser Warenwert überschritten, wird der pauschale Versandkostenbetrag berechnet. Diese Pauschalen sind dominant gegenüber den Werten der hinterlegten Gewichts-, Volumen- oder Mengentabellen.

|**Beschränkungen**
|Beschränkungen ermöglichen die Festlegung von Minimum- und Maximumwerten pro Versandprofil. Wenn ein Auftrag die eingegebenen Werte über- oder unterschreitet, kann das Versandprofil nicht für den Auftrag verwendet werden. Als Ausweichmöglichkeit für solche Fälle kann ein weiteres Versandprofil, z.B. von einem anderen Versanddienstleister, erstellt werden, das einen an die Beschränkungen anschließenden Wertebereich bereitstellt.
|====

[TIP]
.Template-Variablen
====
Zu den verschiedenen Berechnungstypen finden Sie <<omni-channel/online-shop/cms-syntax#grundlagen-template-variablen, **Template-Variablen**>> im Menü <<omni-channel/online-shop/cms-syntax#webdesign-itemview-container-itemviewsingleitem, **CMS » Webdesign » Layout » ItemView » ItemViewSingleItem**>>. Die Template-Variable **$Volumen** gibt dabei keine Maße zurück, sondern das Volumen in Kubikmeter.
====

[#1610.subhead]
Berechnungstyp: Pauschal

Bei diesem Berechnungstyp stellen die eingegebenen Versandkosten die Gesamtsumme dar, d.h. unabhängig davon, wie viele Artikel der Kunde kauft, er bezahlt nur die hier eingegebenen Versandkosten.

Einen Aufschlag für jeden weiteren Artikel können Sie bei diesem Berechnungstyp einstellen, indem Sie am Artikel im Bereich **Versand** <<artikel/artikel-verwalten#290, **Portoaufschläge**>> eingeben und im Tab **Base** des Versandprofils die Option **Artikel-Portoaufschlag** aktivieren.

[#1620.subhead]
Berechnungstyp: Gewichtsabhängig

Bei dem Berechnungstyp **Gewichtsabhängig** werden in die Spalte **Maximum (g)** Grenzwerte für das Bruttogewicht in Gramm eingefügt und in die Spalte **Betrag (EUR)** die dazugehörigen Versandkostenbeträge. Sie erstellen so eine Staffelung der Portokosten nach Gewicht. Mit einem Klick auf **Hinzufügen** fügen Sie weitere Staffelpreise hinzu.

[#1630.subhead]
Berechnungstyp: Volumenabhängig

Bei dem Berechnungstyp **Volumenabhängig** werden in die Spalte **Maximum (Kubikmeter)** Grenzwerte für das Volumen in Kubikmeter eingefügt und in die Spalte **Betrag (EUR)** die dazugehörigen Versandkostenbeträge. Sie erstellen so eine Staffelung der Portokosten nach dem Volumen eines Artikels. Mit einem Klick auf **Hinzufügen** fügen Sie weitere Staffelpreise hinzu.

[WARNING]
.Maße müssen am Artikel gespeichert werden
====
Volumen werden nur korrekt berechnet, wenn Sie im Menü **Artikel » Artikel bearbeiten » Artikel öffnen** im Tab **Einstellungen** der Hauptvariante und dort im Bereich **<<artikel/artikel-verwalten#270, Maße>>** die Länge, Breite und Höhe des Artikels eingegeben haben. Fehlen diese Angaben, wird kein Volumen berechnet und die Berechnung der Versandkosten kann ebenfalls nicht erfolgen.
====

[#1640.subhead]
Berechnungstyp: Mengenabhängig

Bei dem Berechnungstyp **Mengenabhängig** werden in die Spalte **Maximum (Stk.)** Grenzwerte für die Stückzahlen eingefügt und in die Spalte **Betrag (EUR)** die dazugehörigen Versandkostenbeträge. Sie erstellen so eine Staffelung der Portokosten nach Stückzahlen. Mit einem Klick auf **Hinzufügen** fügen Sie weitere Staffelpreise hinzu.

[#1650.subhead]
Berechnungstyp: Preisabhängig

Bei dem Berechnungstyp **Preisabhängig** werden in die Spalte **Maximum (EUR)** Grenzwerte für die Gesamtsumme eines Auftrags eingefügt und in die Spalte **Betrag (EUR)** die dazugehörigen Versandkostenbeträge. Sie erstellen so eine Staffelung der Portokosten nach Einkaufswert des Artikels. Wenn alle eingekauften Artikel das gleiche Versandprofil verwenden, dann erhalten Sie eine Staffelung der Portokosten für den gesamten Einkauf.

[#1660.subhead]
Berechnungstyp: Artikelporto

Bei dem Berechnungstyp **Artikelporto** sind die Versandkosten abhängig von der Anzahl der Artikel. Je nachdem, welchen Betrag Sie im Feld **Jeder weitere Artikel** eingeben, erhöhen sich die Versandkosten für jeden weiteren Artikel um diesen Betrag.

[#1700]
== Versandkosten berechnen

Im Tab **Versandkosten berechnen** konfigurieren Sie die Versandkosten, die für den Artikelexport an Preisportale benötigt werden. Die allgemeinen Versandprofile werden für Preisportale nicht herangezogen. Konfigurieren Sie Einstellungen, die zu allen Artikeln, die Sie an Preisportale exportieren möchten, passen. Werden diese Einstellungen nicht konfiguriert, werden die Versandkosten fehlerhaft oder mit dem Eintrag "0" exportiert.

Weitere Informationen finden Sie auf der Handbuchseite <<basics/datenaustausch/daten-exportieren#, **Daten exportieren**>> im Kapitel <<basics/datenaustausch/daten-exportieren#30, **Datenformate für Preissuchmaschinen exportieren**>>.

Wählen Sie die Standardherkunft möglichst allgemein, z.B. **Mandant (Shop)**. Wählen Sie für die Standardversandregion eine Region, die alle Lieferländer der zu exportierenden Artikel enthält.

[TIP]
.Zahlungsart Vorabüberweisung/Vorkasse
====
Wählen Sie in jedem Fall auch die Zahlungsart **vorab Überweisung/Vorkasse** aus einem der Dropdown-Menüs, damit diese Zahlungsart bei Ablehnung anderer Zahlungsarten als Alternative verwendet werden kann.
====

[.instruction]
Versandkosten berechnen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandkosten berechnen**.
. Wählen Sie für beide Konfigurationen die **Standardherkunft**, **Standardversandregion**, **Zahlungsart 1** und **Zahlungsart 2**.
. **Speichern** Sie die Einstellungen.

Erfahren Sie mehr zur Versandkostenberechnung im folgenden Videotutorial:

video::180302434[vimeo]
[#1800]
== Versandprofil aktivieren

Das Versandprofil muss am Artikel aktiviert werden, um einen Artikel mit den im Versandprofil gespeicherten Einstellungen zu versenden. Aktivieren Sie pro Artikel mindestens ein Versandprofil, da es sonst zu ungewollten Effekten bei der Versandkostenberechnung kommen kann.

[.instruction]
Versandprofil aktivieren:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab **Global**.
. Aktivieren Sie die Versandprofile.
. **Speichern** Sie die Einstellungen.

[IMPORTANT]
.Standardversandprofil
====
Wenn ein Auftrag Artikel enthält, bei denen kein Versandprofil aktiviert wurde, wird das Standardversandprofil aus dem Standard-Webshop für die Artikel verwendet. Das Standardversandprofil wählen Sie im Menü <<omni-channel/online-shop/webshop-einrichten/bestellvorgang#, **Einstellungen » Mandant (Shop) » Standard » Bestellvorgang » Grundeinstellungen**>>. Wenn kein Standardversandprofil eingerichtet ist, wird das Versandprofil mit der höchsten Priorität verwendet.
====

[#1900]
== Versandpaket erstellen

Im Menü **Einstellungen » Aufträge » Versand » Versandpakete** erstellen Sie Versandpakete für Ihre Versandprozesse. Sie können Versandpakete mit definierten Größen erstellen oder die Größe  von Ihrem plentymarkets System aus den Artikeldaten automatisch bestimmen lassen. Wenn Sie kein Versandpaket erstellen und einem Auftrag zuordnen, wird bei der Anmeldung automatisch ein Standardpaket eingestellt, dessen Volumen aus den Artikeldaten berechnet wird.

[TIP]
.Beispiele: Definierte Versandpakete und flexible Verpackung
====
Definierte Versandpakete: Ein Händler verschickt seine Artikel mit zwei verschiedenen Kartongrößen. Er legt dazu zwei Versandpakete an. Das Volumen ergibt sich aus den Abmessungen. +
Versandpaket 1: 30 cm x 25 cm x 40 cm +
Versandpaket 2: 50 cm x 50 cm x 25 cm

Flexible Verpackung: Für den Versand von Möbeln verwendet ein Händler Verpackungsmaterial, das je nach Größe des Versandguts individuell angepasst wird (Wellpappe, Folie etc.). Das Volumen wird dabei aus den Artikeldaten berechnet.
====

Gehen Sie wie im Folgenden beschrieben vor, um ein Versandpaket zu erstellen.

[.instruction]
Versandpaket erstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandpakete**.
. Wechseln Sie in das Tab **Neues Versandpaket**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 8.
. **Speichern** Sie die Einstellungen.

.Einstellungen im Tab **Neues Versandpaket**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Bezeichnung**
|Name eingeben.

|**Volumenangabe**
|**vom Versandpaket beziehen** (Länge, Breite, Höhe) oder **von Artikeldaten beziehen (summiert)** wählen. +
Wenn die Option **von Artikeldaten beziehen (summiert)** gewählt wird, sind die Zeilen **Länge**, **Breite** und **Höhe** nicht mehr sichtbar.

|**Länge**, **Breite**, **Höhe**
|Maße des Versandpakets in Abhängigkeit zur Einheit eingeben.

|**Einheit**
|Einheit aus dem Dropdown-Menü wählen.

|**Maximales Gewicht (KG)**
|Maximales Gewicht in Kilogramm eingeben.

|**Maximales Volumen (summiert)**
|Maximales Volumen in Kubikmeter eingeben. +
Dieser Wert bezieht sich auf das Gesamtvolumen des Versandpakets und setzt sich zusammen aus den Volumina der enthaltenen Artikel. Sie haben mit dieser Angabe einen Richtwert und können besser abschätzen, ob die Artikel eines Auftrags in das Versandpaket passen.

|**Mandant (Shop)**
|Mandant (Shop) aus dem Dropdown-Menü wählen. Die Option **ALLE** wählen, wenn das Versandpaket für alle Webshops verfügbar sein soll.
|====

Wie Sie Versandpakete bearbeiten, hinzufügen oder löschen, ist auf der Handbuchseite <<auftragsabwicklung/fulfillment/versand-center#, **Versand-Center nutzen**>> beschrieben.

[#2300]
== Versandprozess mit dem plentymarkets Client steuern

Mit dem <<basics/automatisierung/plentymarkets-client#, **plentymarkets Client**>> steht Ihnen ein Werkzeug zur Verfügung, mit dem Sie den gesamten Versandprozess abbilden können. Eine detaillierte und individuelle Einrichtung der Prozesse ist nötig, damit diese dann automatisiert ablaufen. Für die Versandabwicklung stehen z.B. die Aktionen <<basics/automatisierung/prozesse/aktionen#340, **Polling**>>, <<basics/automatisierung/prozesse/aktionen#380, **Retourenetikett**>>, <<basics/automatisierung/prozesse/aktionen#390, **Rücksendeschein**>> und <<basics/automatisierung/prozesse/aktionen#430, **Versand-Center**>> zur Verfügung.

[#2400]
== API-Log abrufen

Im Menü **Datenaustausch » API-Log » Tab: Versand Center API-Log** finden Sie Meldungen zu Sendungen, die Sie im Menü **Aufträge » Versand-Center** angemeldet haben. Wählen Sie den Versanddienstleister aus dem Dropdown-Menü **Vorgang** sowie ein Datum und die angezeigten Vorgänge pro Seite. Nach einem Klick auf **Suchen** werden die Vorgänge angezeigt.

Weitere Informationen zu den API-Log-Einträgen von DHL Fulfillment und DPD Cloud Webservice finden Sie auf der Handbuchseite <<basics/datenaustausch/api-log#, **API-Log**>>.

[#2500]
== Versanddienstleister im Überblick

Tabelle 9 listet die in plentymarkets verfügbaren Versanddienstleister auf. Mit einem Klick auf den Dienstleister in der Tabelle gelangen Sie in das Unterkapitel, in dem die versanddienstleisterspezifischen Einstellungen beschrieben sind.

[IMPORTANT]
.Versandservices nicht bei jedem Versanddienstleister vorhanden
====
Nicht für alle Versanddienstleister ist die Auswahl eines Versandservices vorgesehen. Wenn vorhanden, werden die Versandservices in der Portotabelle des Versanddienstleisters angezeigt, nachdem Sie die Portotabelle gespeichert und neu geladen haben. Öffnen Sie das Versandprofil im Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**. Wechseln Sie in das Tab **Portotabelle** und klappen die Region auf. Im unteren Teil der Portotabelle werden die Versandservices angezeigt.
====

.In plentymarkets verfügbare Versanddienstleister im Überblick
[cols="a,a"]
|====
|Versanddienstleister |Erläuterung

|**<<auftragsabwicklung/fulfillment/versand-vorbereiten#2600, c.b.c. logistics>>**
|Für Händler innerhalb Deutschlands. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#2700, **DHL Easylog**>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#2800, **DHL Freight**>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#2900, **DHL Intraship/Versenden**>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#3000, **DHL plentymarkets Import**>>
|Pollingformat. Für Händler innerhalb Deutschlands. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#3100, **DHL Retoure Beilegeretiketten**>>
|Für Händler innerhalb Deutschlands. Retoure: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#3200, **DHL Retoure Online**>>
|Für Händler innerhalb Deutschlands. Retoure: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#3300, **DHL Supply Chain**>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#3400, **DHL UK**>>
|Für Händler innerhalb des Vereinigten Königreichs. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#3500, **DPD Cloud Webservice**>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#3600, **DPD DELISprint**>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#3700, **EasyPAK**>>
|Für Händler innerhalb Österreichs. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#3800, **GLS Germany**>>
|Für Händler innerhalb Deutschlands. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#3900, **Hermes 2-Mann-Handling**>>
|Für Händler innerhalb Deutschlands. Versand: Deutschland und Europa.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#4000, **Hermes ProfiPaketService**>>
|Für Händler innerhalb Deutschlands. Versand: Deutschland und Europa.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#4100, **MyDPD Business / iloxx**>>
|Für Händler innerhalb Deutschlands. Versand: Deutschland und Europa.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#4210, **Royal Mail (via NetDespatch)**>>
|Für Händler innerhalb des Vereinigten Königreichs. Versand: international.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#4230, **UK Mail (via NetDespatch)**>>
|Für Händler innerhalb des Vereinigten Königreichs. Versand: Vereinigtes Königreich.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#4300, **Swiss Post**>>
|Für Händler innerhalb der Schweiz. Versand: Schweiz.

|<<auftragsabwicklung/fulfillment/versand-vorbereiten#4400, **UPS**>>
|Für Händler innerhalb Deutschlands. Versand: international.
|====

[#2600]
=== c.b.c. logistics

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://cbc-logistics.com/[**c.b.c. logistics**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » CBC Logistics**.
. Geben Sie Benutzer und Passwort ein, wie von c.b.c. logistics erhalten.
. **Speichern** Sie die Einstellungen.

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich **CBC Logistics** vor. Beachten Sie dazu die Erläuterungen in Tabelle 10.
. **Speichern** Sie die Einstellungen.

.Versandservices von c.b.c. logistics im Tab **Portotabelle**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Profil**
|Profil aus dem Dropdown-Menü wählen.

|**Absender**
|Absender aus dem Dropdown-Menü wählen.

|**Versanddienstleister**
|Versanddienstleister aus dem Dropdown-Menü wählen.

|**Produkt**
|Produkt aus dem Dropdown-Menü wählen.

|**Services**
|Einen Service oder **ALLE** wählen.
|====

[#2700]
=== DHL Easylog

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://www.dhl.de/de/paket/geschaeftskunden/versandsoftware.html[**DHL Easylog**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » DHL Easylog**.
. Geben Sie die Daten ein, wie von DHL erhalten.
. **Speichern** Sie die Einstellungen.

[IMPORTANT]
.Absenderreferenznummern und Nachnahmeservice
====
Als Standardwert wird für das Datenfeld der Absenderreferenznummern, **POOL_V_ABS_REFNR**, die Ziffer 1 ausgegeben. Es sind auch andere Absenderreferenznummern möglich, z.B. für die Zahlungsart **Nachnahme**. Stimmen Sie diese Einstellungen ggf. mit dem DHL-Support ab. +
Wählen Sie für den Nachnahmeservice für Inland die ID 114 oder 134. Für Ausland ist die ID 5311 die Standardeinstellung.
====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich **DHL Easylog** vor. Beachten Sie dazu die Erläuterungen in Tabelle 11.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu DHL Easylog
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**DHL-Verfahren**
|Die Verfahrensnummer legt fest, ob es sich um einen nationalen, europäischen, internationalen oder Expressversand handelt.

|**DHL-Produkt**
|Je nach Verfahren stehen unterschiedliche Produkte zur Verfügung.

|**DHL-Service**
|Je nach Verfahren stehen unterschiedliche Services, wie z.B. Rückschein oder Transportversicherung, zur Verfügung.

|**DHL-Teilnahme**
|Bei der DHL-Teilnahme handelt es sich um eine Art Vertrag über die Transportdienstleistung.
|====

[IMPORTANT]
.Berechnung des Nachnahmebetrags
====
Wenn bei einem Auftrag eine Paketanzahl größer gleich 1 gespeichert wurde, wird an DHL als Nachnahmebetrag der Rechnungsbetrag geteilt durch die Anzahl der Pakete übermittelt.
====

[#2800]
=== DHL Freight

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dhl.de/de/logistik/frachttransport/land-schienentransport.html[**DHL Freight**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » DHL Freight**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 12.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu DHL Freight
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Niederlassung**
|Dreistellige Abkürzung eingeben, wie von DHL erhalten.

|**Absenderdaten**
|Firmenname eingeben.

|**Beschreibung der Güter**
|Beschreibung der Branche eingeben.

|**Versendernummer, FTP-Benutzer, FTP-Passwort**
|Daten eingeben, wie von DHL erhalten.

|**FTP-In/Out-Verzeichnis**
|Aktivieren, um die FTP-Verzeichnisstruktur von DHL Freight zu nutzen.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich **DHL Freight** vor. Beachten Sie dazu die Erläuterungen in Tabelle 13.
. **Speichern** Sie die Einstellungen.

.Versandservices von DHL Freight im Tab **Portotabelle**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**DHL-Produkt**
|Eines der folgenden Produkte aus dem Dropdown-Menü wählen: +
**Standard** +
**Express nächster Tag** +
**Express, Zustellung nächster Tag vor 10 Uhr** +
**Express, Zustellung nächster Tag vor 12 Uhr** +
**Europlus**

|**DHL-Frankatur**
|Eine der folgenden Frankaturen aus dem Dropdown-Menü wählen: +
**Unfrei** +
**Freigrenze Versandland** +
**Freigrenze Empfangsland** +
**Frei Haus unverzollt/unversteuert** +
**Frei Haus verzollt/unversteuert** +
**Frei Haus verzollt/versteuert**
|====

[#2900]
=== DHL Intraship/Versenden

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Weiter unten in diesem Kapitel wird beschrieben, wie Sie DHL-Exportdokumente erzeugen.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dhl.de/de/paket/geschaeftskunden/versandsoftware.html[**DHL Intraship/Versenden**, window="_blank"] in plentymarkets einzurichten.

[IMPORTANT]
.Umbenennung der Schnittstelle zu DHL Versenden
====
DHL bietet seit einiger Zeit den neuen Service "Versenden" im Geschäftskundenportal an (VLS API). Aktuell gibt es diesen Service in plentymarkets noch nicht, da die VLS-Schnittstelle noch nicht ausreichend dokumentiert ist. Dies ist jedoch in Vorbereitung. In der Übergangsphase wird der Versanddienstleister in plentymarkets unter **DHL Intraship/Versenden** geführt. Diese Schnittstelle sowie Einstellungen, die DHL Intraship/Versenden in anderen Menüs betreffen, gelten sowohl für bestehende DHL Intraship-Kunden als auch für Neukunden bei DHL Versenden.
====

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » DHL Intraship/Versenden**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 14.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu DHL Intraship/Versenden
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|Stammdaten

|**Abrechnungsnummern**
|Gemäß des DHL-Vertrages Abrechnungsnummern eingeben. Pro Abrechnungsnummer können eigene Absenderdaten gepflegt werden. Die 14-stellige DHL Intraship/Versenden-Abrechnungsnummer setzt sich wie folgt zusammen: +
**EKP** = Kundennummer; besteht aus den ersten 10 Ziffern der Abrechnungsnummer. +
**Verfahren** = Legt das DHL-Produkt fest, das für diese Abrechnungsnummer gilt. Dies sind die mittleren beiden Ziffern der Abrechnungsnummer. +
**__Wichtig__**: Beachten Sie dazu die Erläuterungen in der Box unterhalb der Tabelle. +
**Teilnahme** = Die letzten beiden Zeichen der Abrechnungsnummer (nur Ziffern oder Buchstaben sind zulässig).

|**Login-Name**
|Login-Name darf keine Umlaute enthalten. Die Verwendung von Umlauten kann zu einer Abweisung über die Schnittstelle führen, auch wenn die Webseite den Login-Namen akzeptiert.

|**Passwort**
|Passwort darf maximal 20 Zeichen lang sein. Zwar ist bei DHL die Verwendung eines längeren Passworts möglich, über die plentymarkets Schnittstelle erlaubt DHL jedoch maximal 20 Zeichen. Ein Passwort mit mehr als 20 Zeichen führt zu Fehlern bei der SOAP-Übergabe.

|**Alternative Telefonnummer für Auslandskunden**
|Bei Auslandssendungen wird die Telefonnummer des Empfängers standardmäßig von DHL auf dem Etikett gedruckt, damit DHL diesen bei Bedarf erreichen kann. Wenn das nicht gewünscht ist, hier z.B. eine Folge von Nullen oder "Keine Tel.-Nr." eingeben. Dieser Eintrag überschreibt dann die Telefonnummer von Auslandskunden. +
Die Option ist auch wichtig für den Fall, dass im Layout die Telefonnummer für Auslandskunden nicht als Pflichtfeld markiert wurde und die Sendung somit von DHL abgelehnt würde.

|**Etiketterzeugung erzwingen**
|Festlegen, ob bei der Anmeldung einer Sendung im Versand-Center über DHL Intraship/Versenden auch dann ein Versandetikett erzeugt werden soll, wenn keine oder unvollständige Daten für die Adresse vorhanden sind. +
**Ja** = DHL führt die Korrektur der fehlerhaften Daten durch und berechnet dies (Standardeinstellung). +
**Nein** = Nicht kodierbare Sendungen werden bei der Anmeldung bei DHL Intraship/Versenden mit einer Fehlermeldung abgelehnt. Der Auftrag wird nicht angemeldet und in plentymarkets wird kein Versandetikett generiert.

|**Empfänger-E-Mail**
|Wählen, ob die E-Mail-Adresse des Empfängers übertragen werden soll.

2+|Absenderdaten

|**Firma, Absenderadresse, Kontaktperson, Bankdaten**
|Absenderdaten eingeben.

|**Mischkalkulation**
|Wählen, ob die Mischkalkulation aktiviert werden soll.

|**Frankatur bei Ausfuhrsendungen**
|Wählen, ob Zoll und Steuern vom Kunden (DAP) oder vom Händler (DDP) bezahlt werden.

|**Versandetikett**
|**Logo** = Die Dateigröße eines Logos ist auf 100 KB begrenzt. Das Logo sollte einem Seitenverhältnis von 3:4 und einer effektiven Größe von 15 x 20 mm entsprechen (Höhe x Breite). +
**__Wichtig__**: Die URL des Logos darf nur mit **http://** hinterlegt werden. +
**Alternativ benutze Adressdaten von folgender Abrechnungsnummer** = Eine zuvor gespeicherte Abrechnungsnummer aus dem Dropdown-Menü wählen, um die Daten zu übernehmen.
|====

[IMPORTANT]
.DHL-Abrechnungsnummer
====
Die mittleren beiden Ziffern der Abrechnungsnummer **Verfahren** stehen für folgende DHL-Produkte: DHL Paket (01), Regionalpaket AT (02), DHL Europaket (54), DHL Paket International (53), DHL Domestic Express (71) und DHL Officepack (72). +
**__Wichtig__**: DHL Intraship/Versenden nutzt für das Verfahren Regionalpaket AT die 01. Da es in plentymarkets zu Konflikten mit DHL Paket kommt, benutzen wir intern die 02. Für DHL Domestic Express wird die 71 benutzt, damit es nicht zu Konflikten mit DHL Officepack kommt. An DHL wird selbstverständlich die korrekte Nummer gesendet.
====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich **DHL Intraship/Versenden** vor. Beachten Sie dazu die Erläuterungen in Tabelle 15.
. **Speichern** Sie die Einstellungen.

.Versandservices von DHL Intraship/Versenden im Tab **Portotabelle**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**DHL-Abrechnungsnummer**
|Abrechnungsnummer aus dem Dropdown-Menü wählen.

|**DHL-Service**
|Einen, mehrere oder **ALLE** Services wählen.
|====

[.subhead]
DHL-Exportdokumente erzeugen

DHL-Exportdokumente werden ausschließlich für Aufträge erzeugt, die mit dem Produkt **DHL Paket International** versendet werden und bei denen es sich um Ausfuhrlieferungen handelt. DHL Paket International kann auch für Sendungen innerhalb der EU genutzt werden, allerdings werden dann keine Exportdokumente erzeugt.

Sendungen an Länder außerhalb der EU dürfen maximal 5 Artikelpositionen enthalten und es werden die einzelnen Parameter pro Artikelposition gemeldet (Gewicht, Zolltarifnummer, Herstellerland). Damit Aufträge für die Erzeugung der Exportdokumente gefunden werden können, müssen diese zuvor erfolgreich über das Menü **Aufträge » Versand-Center** bei DHL Intraship/Versenden angemeldet worden sein.

[.instruction]
DHL-Exportdokument erzeugen:

. Öffnen Sie das Menü **Aufträge » Fulfillment**.
. Klappen Sie das Untermenü **DHL Intraship-Exportdokumente erzeugen** auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 16.
. Klicken Sie auf das Zahnrad.  +
→ Die Exportdokumente werden als PDF erzeugt.

.DHL Intraship-Exportdokumente erzeugen
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Auftragsstatus**
|Auftragsstatus der Daten, für die Exportdokumente erzeugt werden sollen, wählen.

|**Versanddatum**
|Versanddatum, für das die Daten gesucht werden sollen, wählen.

|**Limit**
|Limit für die Dokumenterzeugung wählen.
|====

[TIP]
.Warenausgang per Ereignisaktion buchen
====
Wenn Sie mit dem Generieren der Exportdokumente gleichzeitig den Warenausgang buchen möchten, können Sie das über eine Ereignisaktion im Menü **Einstellungen » Aufträge » Ereignisaktionen** erledigen. Weitere Informationen finden Sie auf der Handbuchseite **<<basics/automatisierung/ereignisaktionen#, Ereignisaktionen>>**.
====

[#3000]
=== DHL plentymarkets Import

Das <<basics/automatisierung/prozesse/aktionen#340, **Pollingformat**>> DHL plentymarkets Import bietet Ihnen die Möglichkeit, DHL mit einer link:https://www.dhl.de/de/paket/information/geschaeftskunden/service-alterssichtpruefung.html[**Alterssichtprüfung**, window="_blank"] bei der Lieferung Ihrer Artikel, wie z.B. Liquids für E-Zigaretten, zu beauftragen. Mit diesem Pollingformat erzeugen Sie eine CSV-Datei für den Datenimport zu DHL. Die Datei wird dann im DHL Geschäftskundenportal hochgeladen, um die Sendungen anzumelden und Labels zu erhalten. Die Konfiguration im DHL Geschäftskundenportal ist Bedingung für die Nutzung der Services in plentymarkets. Dort geben Sie auch die Referenzen an, die Sie beim Einrichten der Portotabellen in plentymarkets benötigen.

Nehmen Sie die im Folgenden beschriebenen Einstellungen vor, um den DHL-Service **Alterssichtprüfung** einzurichten:

* Einstellungen im DHL Geschäftskundenportal vornehmen
* Merkmal erstellen
* Grundeinstellung vornehmen
* Merkmal am Artikel verknüpfen
* Versandoption wählen
* CSV-Datei erzeugen und zu DHL hochladen

[TIP]
.Aufträge mit Altersgrenzen
====
Sind in einem Auftrag Artikel mit unterschiedlichen Altersgrenzen enthalten, "sticht" die 18. Sobald mindestens eine Artikelposition im Auftrag eine Prüfung auf 18 verlangt, gilt diese Altersgrenze für den gesamten Auftrag.
====

[.subhead]
Einstellungen im DHL Geschäftskundenportal vornehmen

Nehmen Sie zunächst die Einstellungen im link:https://www.dhl-geschaeftskundenportal.de/webcenter/portal/gkpExternal?_afrLoop=2465780077903302#!%40%40%3F_afrLoop%3D2465780077903302%26_adf.ctrl-state%3D11moofew5r_4[**DHL Geschäftskundenportal**, window="_blank"] vor.

[.subhead]
Merkmal erstellen

Erstellen Sie im Menü **Einstellungen » Artikel » Merkmale** ein Merkmal vom Merkmaltyp **Auswahl**. Speichern Sie für die Auswahl zur Altersgrenze 16 Jahre den Wert **A16** und zur Altersgrenze 18 Jahre den Wert **A18**.

Weitere Informationen finden Sie im Themenbereich **<<artikel#, Artikel>>** im Kapitel **<<artikel/artikel-verwalten#500, Merkmale erstellen>>**.

[.subhead]
Grundeinstellung vornehmen

Wählen Sie das soeben erstellte Merkmal im Menü **Einstellungen » Artikel » Grundeinstellungen** im Dropdown-Menü **Artikelmerkmal zur Alterssichtprüfung**. **Speichern** Sie die Einstellungen.

[.subhead]
Merkmal am Artikel verknüpfen

Verknüpfen Sie das Merkmal bei jedem Artikel, der die Alterssichtprüfung erhalten soll.

[.instruction]
Merkmal am Artikel verknüpfen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Merkmale**.
. Aktivieren Sie das soeben erstellte Merkmal im Bereich **Weitere Merkmale aktivieren**.
. **Speichern** Sie die Einstellungen. +
→ Das Merkmal wird im Bereich **Merkmale** angezeigt.
. Wählen Sie den Wert für den Artikel gemäß der Altersfreigabe wie oben erstellt aus dem Dropdown-Menü.
. **Speichern** Sie die Einstellungen.

Weitere Informationen finden Sie im Themenbereich **<<artikel#, Artikel>>** im Kapitel **<<artikel/artikel-verwalten#80, Merkmale aktivieren>>**.

[.subhead]
Versandoption wählen

Der Service **Alterssichtprüfung** ist in der Portotabelle verfügbar.

[.instruction]
Versandoption wählen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen**.
. Wechseln Sie in das Tab **Versandprofile**.
. Öffnen Sie das Versandprofil von DHL.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Wählen Sie im Bereich **DHL plentymarkets Import** im Dropdown-Menü **Produkt** die Option **DHL Paket**.
. Aktivieren Sie unter **Services** die Option **Alterssichtprüfung**.
. **Speichern** Sie die Einstellungen.

[.subhead]
CSV-Datei erzeugen und zu DHL hochladen

Erzeugen Sie nun die CSV-Datei im plentymarkets Client oder im Menü **Aufträge » Versand-Center » Tab: Polling**. Speichern Sie Datei und laden Sie sie im DHL Geschäftskundenportal hoch.

[#3100]
=== DHL Retoure Beilegeretiketten

Mit DHL Retoure Beilegeretiketten erzeugen Sie Etiketten für Aufträge, die über DHL innerhalb Deutschlands ausgeliefert werden. Ihr Kunde erhält schon bei der Lieferung ein komplett vorbereitetes Retourenlabel. Im Fall der Rücksendung, z.B. aufgrund von Gewährleistungen oder Reparaturen, muss die Ware nur noch eingepackt und das Label angebracht werden. Die Etiketten werden per Ereignisaktion eingerichtet und sind dann im Versand-Center zum Abruf und Ausdruck verfügbar.

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://www.dhl.de/de/paket/geschaeftskunden/ab-200-pakete/nationaler-versand/retoure.html[**DHL Retoure Beilegeretiketten**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » DHL RETOURE Beilegeretiketten**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 17.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu DHL Retoure Beilegeretiketten
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Empfänger**
|Daten des Empfängers eingeben.

|**Abrechnungsnummer**
|Abrechnungsnummer eingeben, wie von DHL erhalten.

|**Kundenkennung**
|Kundenkennung eingeben, wie von DHL erhalten.

|**Leitcode-Sequenz**
|Daten eingeben. Straßencode und Hausnummer immer dreistellig eingeben, d.h. die Zahl 10 als 010.

|**Service**
|Service wählen.
|====

Richten Sie nun eine **<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>** ein, um die Retourenetiketten automatisch zu erzeugen.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
. Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das **Ereignis** gemäß Tabelle 18.
. **Speichern** Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß Tabelle 18 vor.
. Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Erstellen von Retourenetiketten für DHL
[cols="a,a,a"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Auftragsanlage: Neuer Auftrag**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**; ggf. weitere wie Gewährleistung und Reparatur

|**Filter 2**
|**Versand &gt; Lieferland**
|**Deutschland**

|**Filter 3**
|**Auftrag &gt; Auftragslager** (optional)
|

|**Filter 4**
|**Auftrag &gt; Herkunft** (optional)
|

|**Aktion 1**
|**Retoure &gt; DHL Retouren-Label generieren**
|**DHL Retoure Beileger**

|**Aktion 2**
|**Auftrag &gt; Status ändern** (optional)
|
|
|====

Erfahren Sie mehr über Retourenbeileger und das Retoureportal im folgenden Videotutorial:

video::128242762[vimeo]
[#3200]
=== DHL Retoure Online

DHL Retoure Online ermöglicht das Erzeugen von Retourenetiketten für Aufträge aus verschiedenen Lieferländern. Die Etiketten sind dann im Menü **Aufträge » Versand-Center » Tab: Retoure** verfügbar. Die Etiketten können auch dem Endkunden im **Mein Konto**-Bereich des Webshops verfügbar gemacht werden.

Sie benötigen ein Lager, um die Informationen, die Sie von DHL für Retouren erhalten, zu hinterlegen. In plentymarkets gibt es verschiedenen Lagertypen. Für Retouren eignet sich insbesondere der Lagertyp **Reparatur**. Das Reparaturlager kann dann über die Einstellung **Zugeordnetes Reparaturlager** im Menü **Einstellungen » Waren » Lager » Lager öffnen » Einstellungen** einem Hauptlager vom Typ **Vertrieb** zugeordnet werden. Wenn später ein Retourenetikett erzeugt wird, wird anhand des Lagers des Auftrags das zugehörige Vertriebs- oder Reparaturlager verwendet.

Wenn Sie noch kein Lager erstellt haben, erstellen Sie zunächst ein Lager oder ein Vertriebs- und Reparaturlager im Menü **Einstellungen » Waren » Lager**. Wie Sie ein Lager erstellen, ist auf der Handbuchseite <<warenwirtschaft/lager-einrichten#, **Lager einrichten**>> beschrieben.

[IMPORTANT]
.Verfügbare Lagertypen für DHL Online Retoure
====
Nur Lager der Typen **Vertrieb** und **Reparatur** stehen für DHL Online Retoure zur Verfügung.
====

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dhl.de/de/paket/geschaeftskunden/ab-200-pakete/nationaler-versand/retoure.html[**DHL Retoure Online**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » DHL Retoure Online**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 19.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu DHL Retoure Online
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Portal-ID, Benutzername, Passwort**
|Daten eingeben, wie von DHL erhalten.

|**Gültigkeit zugeordneter Etiketten**
|Dauer der Gültigkeit von zugeordneten Etiketten aus dem Dropdown-Menü wählen. +
Zugeordnet heißt, dass die Etiketten bereits einer Retoure zugeordnet sind. Nach dem gewählten Zeitraum sind die Etiketten nicht mehr zum Download verfügbar.

|**Gültigkeit unzugeordneter Etiketten**
|Dauer der Gültigkeit von unzugeordneten Etiketten aus dem Dropdown-Menü wählen. Nach dem gewählten Zeitraum sind die Etiketten nicht mehr zum Download verfügbar.

|**Retourenempfänger**
|Lager aufklappen. Die Einstellungen für die Länder, wie von DHL erhalten, bei dem Lager eingeben. Wenn in einem Reparaturlager keine Einträge stehen und das Lager einem Vertriebslager zugeordnet ist, werden die Einstellungen des Vertriebslagers verwendet. +
Das Eingeben der Informationen im Vertriebslager dient somit der Sicherheit und ist nicht zwingend notwendig. Die Auswahl des Retourenempfängers erfolgt anhand des Auftragslagers. Es stehen nur Lager der Typen **Vertrieb** und **Reparatur** zur Verfügung.
|====

Legen Sie nun fest, ob Sie Ihrem Kunden erlauben, Retouren in seinem Konto selbst anzulegen oder nicht.

[.instruction]
Retourenanlage erlauben:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Shop wählen » Mein-Konto » Grundeinstellungen**.
. Wählen Sie in der Zeile **Retoure** eine Option aus dem Dropdown-Menü. Beachten Sie dazu die Erläuterungen in Tabelle 20.
. **Speichern** Sie die Einstellungen.

.Retourenanlage im Menü **Einstellungen » Mandant (Shop) » Shop wählen » Mein-Konto » Grundeinstellungen** erlauben
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Retoure**
|**aktiviert** = Kunde kann Retouren anlegen. Etiketten werden jedoch nicht bereitgestellt. Wie Sie weiter verfahren, wenn der Kunde eine Retoure anmeldet, bleibt Ihnen überlassen. Sie können dem Kunden z.B. ein Etikett per E-Mail zusenden. +
Wenn Sie erlauben, dass Kunden Retouren selbst anlegen können, stehen die <<auftragsabwicklung/auftraege/auftraege-verwalten#retoure, **Retourengründe**>>, die Sie eingegeben haben, auch im **Mein-Konto**-Bereich zur Auswahl. +
**DHL Retoure Online** = Kunde kann Retoure anlegen und kann anschließend das Retourenetikett von DHL herunterladen und ausdrucken. +
**deaktiviert** = Kunde kann keine Retoure anlegen. Wie Sie Retouren stattdessen handhaben, müssen Sie selbst entscheiden. Kunden können z.B. auch telefonisch oder per E-Mail Retouren bei Ihnen melden.
|====

[#3300]
=== DHL Supply Chain

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dhl.de/de/logistik/supply-chain-loesungen.html[**DHL Supply Chain**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » DHL Supply Chain**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 21.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu DHL Supply Chain
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Versender-ID, FTP-Host, FTP-Benutzer, FTP-Passwort**
|Daten eingeben, wie von DHL erhalten.

|**Service**
|Service aus dem Dropdown-Menü wählen.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Wählen Sie im Bereich **DHL Supply Chain** in der Zeile **DHL-Produkt** die Option **Einmann-Handling** oder **Zweimann-Handling** aus dem Dropdown-Menü.
. **Speichern** Sie die Einstellungen.

[#3400]
=== DHL UK

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dhl.co.uk/en.html[**DHL UK**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » DHL UK**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 22.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu DHL UK
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|Stammdaten

|**Site-ID**
|Daten eingeben, wie von DHL erhalten.

|**Passwort**
|Passwort eingeben, wie von DHL erhalten.

2+|Absenderkonten

|**Abrechnungsinformationen**
|Abrechnungsinformationen eingeben.

|**Absenderadresse**
|Absenderdaten eingeben.
|====

[TIP]
.Absenderkonten hinzufügen
====
Nachdem Sie im Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » DHL UK** die Daten in den Bereichen **Abrechnungsinformationen** und **Absenderadresse** eingegeben haben und diese Daten gespeichert haben, wird ein neues Tab im Bereich **Absenderkonten** hinzugefügt. Dieses Tab wird nach der Absender-Kontonummer benannt, die Sie im Bereich **Abrechnungsinformationen** eingegeben haben. Fügen Sie beliebig viele Absenderkonten über das Tab **Neu** hinzu.
====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich **DHL UK** vor. Beachten Sie dazu die Erläuterungen in Tabelle 23.
. **Speichern** Sie die Einstellungen.

.Versandservices von DHL UK im Tab **Portotabelle**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Absender-Kontonummer**
|Absender-Kontonummer aus dem Dropdown-Menü wählen.

|**Handelsbedingungen**
|Handelsbedingung aus dem Dropdown-Menü wählen.
|====

[#3500]
=== DPD Cloud Webservice

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

[TIP]
.Automatische Zuordnung des Anmeldedatums zum nächsten Werktag
====
Wenn der Tag, an dem der Auftrag angemeldet wird, kein für DPD gültiger Werktag ist, wird automatisch der nächste Werktag gewählt. +
Wenn der Auftrag über das Versand-Center im Menü **Aufträge » Versand-Center » Tab: Anmelden** angemeldet wird, darf unter **Versanddatum** kein Datum gewählt werden. Andernfalls kann die automatische Zuordnung zum nächsten Werktag nicht erfolgen.
====

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://esolutions.dpd.com/entwickler/dpd-cloud-webservice.aspx[**DPD Cloud Webservice**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » DPD Cloud Webservice**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 24.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu DPD Cloud Webservice
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**User-ID**
|User-ID eingeben, wie von DPD erhalten.

|**User-Token**
|User-Token eingeben, wie von DPD erhalten.

|**Adresszusatz auf Label**
|Wählen, ob der Adresszusatz, der in der Lieferanschrift eingegeben wurde, auf dem DPD-Versandlabel ausgegeben werden soll. DPD begrenzt die Zeichenlänge auf 35. +
**Hinter Name ergänzen** = Der Adresszusatz wird hinter dem Namen ausgegeben. +
**In Referenz 1 ausgeben** = Der Adresszusatz wird unter **Referenz 1** ausgegeben. +
**Nicht ausgeben** = Der Adresszusatz wird nicht ausgegeben.
|====

Das folgende Videotutorial veranschaulicht das Erstellen des Versandprofils für DPD Cloud Webservice:

video::152570205[vimeo]
Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Wählen Sie im Bereich **DPD Cloud Webservice** in der Zeile **Versandservice** einen Service aus dem Dropdown-Menü.
. **Speichern** Sie die Einstellungen.

Beachten Sie die Meldungen zu Sendungen, die Sie später über das <<auftragsabwicklung/fulfillment/versand-center#700, **Versand-Center**>> bei DPD Cloud Webservice anmelden. Diese Meldungen finden Sie im Menü **Datenaustausch » API-Log » Tab: Versand Center API-Log**. Weitere Informationen zu den API-Log-Einträgen von DPD Cloud Webservice finden Sie auf der Handbuchseite <<basics/datenaustausch/api-log#, **API-Log**>>.

[#3600]
=== DPD DELISprint

Bevor Sie die Schnittstelle zu DPD DELISprint in plentymarkets einrichten, registrieren Sie sich bei link:https://www.dpd.com/portal_de[**DPD**, window="_blank"]. Mit dem Programm DPD DELISprint erstellen Sie als DPD-Kunde DPD-Paketscheine.

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://www.dpd.com/ch/home/esolutions/clientloesungen/delisprint_6[**DPD DELISprint**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » DPD DELISprint**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 25.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu DPD DELISprint
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Versandart**
|Versandart aus dem Dropdown-Menü wählen. +
**NP - Normalpaket** = CLASSIC-Versand von Normalpaketen +
**KP - Kleinpaket** = CLASSIC-Versand von Kleinpaketen +
**NCP - B2C Normalpaket** = gewerblicher Versand von Normalpaketen +
**SCP - B2C Kleinpaket** = gewerblicher Versand von Kleinpaketen

|**Flex/Predict aktiv**
|Aktivieren, um bei DPD den kostenpflichtigen Vorankündigungsservice link:https://www.dpd.com/de/home/produkte_services/zusatzleistungen/national/predict[**Predict**, window="_blank"] (ehemals Flexzustellung) anzumelden. In der CSV-Datei wird dann der Zusatz **PRO** ausgegeben.
|====

[TIP]
.Zahlungsart Nachnahme
====
Bei Aufträgen mit der Zahlungsart **Nachnahme**, die über DPD versendet werden sollen, wird der Nachnahme-Service automatisch gewählt. Es sind keine zusätzlichen Einstellungen erforderlich.
====

[#3700]
=== EasyPAK

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://www.post.at/geschaeftlich_paket_easypak_versandsoftware.php[**EasyPAK**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » EasyPAK**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 26.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu EasyPAK
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Absender-Referenz-Nr., Mandanten-Referenz-Nr., IBAN**
|Daten eingeben, wie von EasyPAK erhalten.  +
Wenn die Versandart Nachnahme genutzt wird, ist die Angabe der IBAN eine Pflichtangabe.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich **PAT Easypak** vor. Beachten Sie dazu die Erläuterungen in Tabelle 27.
. **Speichern** Sie die Einstellungen.

.Versandservices von EasyPak im Tab **Portotabelle**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Vertragstyp**
|Vertragstyp wählen.

|**Produkte**
|Produkt wählen.

|**Zusatzleistungen**
|Eine oder mehrere Zusatzleistungen wählen.
|====

[#3800]
=== GLS Germany

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://gls-group.eu/DE/de/home[**GLS Germany**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » GLS Germany**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 28.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu GLS Germany
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Internationale Kundennummer, +
Nationale Kundennummer, Annahmestelle**
|Daten eingeben, wie von GLS erhalten.
|====

////
div class="plentyInfoBox plentyIsMessage">
<div class="plentyInfoBoxHeader">Semikolon als Trennzeichen für CSV-Export</div>
<div class="plentyInfoBoxContent">
<p>Für einen korrekten Datenexport zu GLS Germany im Menü <strong>Aufträge » Fulfillment » Lieferanschriftenliste</strong> stellen Sie als Trennzeichen beim CSV-Export das Semikolon ein.</p>
</div>
</div
////
[#3900]
=== Hermes 2-Mann-Handling

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Damit Ihr Kunde im Bestellvorgang wählen kann, ob er den Montageservice von link:https://www.hermesworld.com/de/unsere-dienstleistungen/distribution/2-mann-handling/2-mann-handling/[**Hermes (2-Mann-Handling)**, window="_blank"] nutzen möchte, müssen Sie diesen Service als Bestellmerkmal anlegen. Legen Sie ein Bestellmerkmal mit den Optionen **Ja** und **Nein** an. Je nach Wahl der Option **Merkmaltyp** sind mehrere Möglichkeiten der Auswahl im Webshop konfigurierbar.

[TIP]
.Schnittstelle nur für Bestandskunden
====
Die Schnittstelle zu Hermes 2-Mann-Handling kann nur noch von Bestandskunden genutzt werden. Neukunden werden gebeten, sich an die link:https://www.hermesworld.com/de/unsere-dienstleistungen/distribution/2-mann-handling/2-mann-handling/[**HERMES Einrichtungs Service GmbH &amp; Co.KG**, window="_blank"] zu wenden.
====

[.instruction]
Montageservice als Bestellmerkmal anlegen:

. Öffnen Sie das Menü **Einstellungen » Artikel » Merkmale » Tab: Neues Merkmal**.
. Geben Sie einen Namen ein, z.B. Montageservice.
. Aktivieren Sie die Option **Bestellmerkmal**.
. Wählen Sie als **Merkmaltyp** die Einstellung **Auswahl**. +
→ Weitere Optionen werden angezeigt.
. **Speichern** Sie die Einstellungen. +
→ Das Merkmal wird angelegt.
. Wechseln Sie in das Tab **Merkmale** und öffnen Sie das zuvor angelegte Merkmal.
. Geben Sie bei der Option **Name** unterhalb des Merkmaltyps **Ja** ein.
. **Speichern** Sie die Einstellungen. +
→ Ein weiteres Namensfeld wird angezeigt.
. Geben Sie in dieses Namensfeld **Nein** ein.
. **Speichern** Sie die Einstellungen.

Verknüpfen Sie nun das Bestellmerkmal mit dem Artikel.

[.instruction]
Merkmal mit dem Artikel verknüpfen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab **Merkmale**.
. Aktivieren Sie das zuvor angelegte Merkmal.
. **Speichern** Sie die Einstellungen.

Wenn ein Kunde den Artikel in den Warenkorb legt, werden die Optionen **Ja** und **Nein** des Bestellmerkmals in einem Dropdown-Menü zur Auswahl angeboten.

[IMPORTANT]
.Montageservice nur bei Versand mit Hermes
====
Das Bestellmerkmal ist mit dem Artikel und nicht mit dem Versanddienstleister verknüpft. Wenn für den Artikel mehr als eine Versandart bzw. andere Versanddienstleister als Hermes hinterlegt sind, fügen Sie für die Endkunden einen Hinweis in den Webshop ein, dass der Montageservice nur bei Versand mit Hermes erfolgt.
====

Gehen Sie nun wie im Folgenden beschrieben vor, um die Schnittstelle zu Hermes 2-Mann-Handling in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » Hermes (2-Mann-Handling)**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 29.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu Hermes (2-Mann-Handling)
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Mandanten-Nr., FTP-Host, FTP-Benutzer, FTP-Passwort**
|Daten eingeben, wie von Hermes erhalten.

|**Montageservice**
|Montageservice aus dem Dropdown-Menü wählen. Erst sichtbar, wenn wie oben beschrieben, das Bestellmerkmal angelegt und mit dem Artikel verknüpft wurde.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich **Hermes 2-Mann-Handling** vor. Beachten Sie dazu die Erläuterungen in Tabelle 30.
. **Speichern** Sie die Einstellungen.

.Versandservices von Hermes (2-Mann-Handling) im Tab **Portotabelle**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Versandtyp**
|**Normalversand** oder **48-Stunden-Service** wählen.  +
Eine Unterteilung in diese zwei Versandprofile ist sinnvoll, da auch beim Versanddienstleister selbst sich die Preise für diese zwei Versandmöglichkeiten unterscheiden und so die Kosten an die Kunden weitergegeben werden können.
|====

[#4000]
=== Hermes ProfiPaketService

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://profipaketservice.hlg.de/wps/portal/PROPS_DEU/Home/Start/[**Hermes ProfiPaketService**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » Hermes (ProfiPaketService)**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 31.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu Hermes (ProfiPaketService)
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|Stammdaten

|**Zugangsdaten**
|Interner Name, Login-Name und Passwort eingeben, wie von Hermes erhalten.

|**Abrechnung zum Staffelpreis**
|AGB von Hermes sowie den Hinweis auf die Limitierung des Paketwerts akzeptieren. +
Die beiden Häkchen setzen. Andernfalls steht der Hermes-Dienst nicht zur Verfügung. Die AGB können über den Link aufgerufen werden.

2+|Verfügbare Produkte

|**Interner Name, Paketklasse, Max. Paketgewicht, Nettopreis, Lieferländer**
|Hier werden die Daten, wie über die Schnittstelle von Hermes erhalten, angezeigt.
|====

[#4100]
=== MyDPD Business / iloxx

Der Versanddienstleister iloxx gehört jetzt zu DPD und firmiert unter dem Namen DPD iloxx DPD eService GmbH. Bestehende iloxx-Schnittstellen in plentymarkets sind davon nicht berührt. Die neue Schnittstelle heißt jetzt MyDPD Business / iloxx.

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:http://www.dpd.iloxx.de/home.aspx[**MyDPD Business / iloxx**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » MyDPD Business / iloxx**.
. Geben Sie **User-ID** und **User-Token** ein, wie von MyDPD Business / iloxx erhalten.
. **Speichern** Sie die Einstellungen.

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Wählen Sie im Bereich **MyDPD Business/iloxx** in der Zeile **Versandservice** einen Service aus dem Dropdown-Menü.
. **Speichern** Sie die Einstellungen.

[TIP]
.Versandetiketten drucken
====
Sobald der Auftrag den Status **[5] Freigabe Versand** hat, können Sie im Versand-Center im Tab **Label** das Versandetikett drucken. Die Versandetiketten werden im Format DIN A-6 generiert.
====

[#4200]
=== NetDespatch

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie in den folgenden Unterkapiteln beschrieben vor, um link:http://www.royalmail.com/[**Royal Mail**, window="_blank"] und link:https://www.ukmail.com/[**UK Mail**, window="_blank"] über die integrierte Schnittstelle zu link:http://www.netdespatch.com/[**NetDespatch**, window="_blank"] in plentymarkets einzurichten.

[#4210]
==== Royal Mail

Gehen Sie wie im Folgenden beschrieben vor, um link:http://www.royalmail.com/[**Royal Mail**, window="_blank"] über die integrierte Schnittstelle zu link:http://www.netdespatch.com/[**NetDespatch**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » NetDespatch**.
. Klappen Sie den Bereich **Royal Mail Einstellungen** auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 32.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu NetDespatch (Royal Mail)
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|Inländisch

|**Schnittstelle aktiv**
|Häkchen setzen, um die Schnittstelle zu aktivieren.

|**Modus**
|**Testsystem** oder **Produktivsystem** wählen.

|**Benutzername**
|Benutzername eingeben.

|**Passwort**
|Passwort eingeben.

2+|International

|**Schnittstelle aktiv**
|Häkchen setzen, um die Schnittstelle zu aktivieren.

|**Modus**
|**Testsystem** oder **Produktivsystem** wählen.

|**Benutzername**
|Benutzername eingeben.

|**Passwort**
|Passwort eingeben.

2+|Royal Mail Konto ID

|**Konto-ID**
|Konto-ID eingeben.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich **NetDespatch** vor. Beachten Sie dazu die Erläuterungen in Tabelle 33.
. **Speichern** Sie die Einstellungen.

.Versandservices von NetDespatch (Royal Mail) im Tab **Portotabelle**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Versanddienstleister**
|**Royal Mail** aus dem Dropdown-Menü wählen.

|**Versandgebiet**
|**Royal Mail International** oder **Royal Mail Inländisch** aus dem Dropdown-Menü wählen.

|**Produktgruppe**
|Produktgruppe aus dem Dropdown-Menü wählen.

|**Versandservice**
|Versandservice aus dem Dropdown-Menü wählen. Abhängig vom gewählten Versandservice wird der zugehörige Code unter **Service-Code** in der nächsten Zeile automatisch angezeigt.

|**Service-Code**
|Der Service-Code wird in Abhängigkeit zum vorher gewählten Versandservice hier automatisch angezeigt.

|**Nichtzustellbarkeitsanweisung**
|Eine Option aus dem Dropdown-Menü wählen. Das Dropdown-Menü wird nur angezeigt, wenn unter **Versandgebiet** die Einstellung **Royal Mail International** gewählt wurde. Mit Wahl dieser Option wird festgelegt, wie vorgegangen werden soll, wenn das Paket nicht zugestellt werden kann. Bei CN23-Formularen ist die Auswahl einer Option eine Pflichtauswahl.
|====

[#4230]
==== UK Mail

Gehen Sie wie im Folgenden beschrieben vor, um link:https://www.ukmail.com/[**UK Mail**, window="_blank"] über die integrierte Schnittstelle zu link:http://www.netdespatch.com/[**NetDespatch**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » NetDespatch**.
. Klappen Sie den Bereich **UK Mail Einstellungen** auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 34.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu NetDespatch (UK Mail)
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|Inländisch

|**Schnittstelle aktiv**
|Häkchen setzen, um die Schnittstelle zu aktivieren.

|**Modus**
|**Testsystem** oder **Produktivsystem** wählen.

|**Benutzername**
|Benutzername eingeben.

|**Passwort**
|Passwort eingeben.

2+|UK Mail Konto ID

|**Konto-ID**
|Konto-ID eingeben.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich **NetDespatch** vor. Beachten Sie dazu die Erläuterungen in Tabelle 35.
. **Speichern** Sie die Einstellungen.

.Versandservices von NetDespatch (UK Mail) im Tab **Portotabelle**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Versanddienstleister**
|**UK Mail** aus dem Dropdown-Menü wählen.

|**Versandgebiet**
|**Inländisch** aus dem Dropdown-Menü wählen.

|**Produktgruppe**
|Produktgruppe aus dem Dropdown-Menü wählen.

|**Versandservice**
|Versandservice aus dem Dropdown-Menü wählen. Abhängig vom gewählten Versandservice wird der zugehörige Code unter **Service-Code** in der nächsten Zeile automatisch angezeigt.

|**Service-Code**
|Der Service-Code wird in Abhängigkeit zum vorher gewählten Versandservice hier automatisch angezeigt.

|**Nichtzustellbarkeitsanweisung**
|Diese Option ist nur bei internationalem Versand relevant und daher für UK Mail nicht verfügbar.
|====

[#4300]
=== Swiss Post

Bevor Sie die Schnittstelle zu link:https://www.post.ch/de/geschaeftlich/themen-a-z/swiss-post-gls[**Swiss Post**, window="_blank"] in plentymarkets einrichten, registrieren Sie sich bei Swiss Post.

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Richten Sie für Swiss Post einen technischen Benutzer ein. Dazu benötigen Sie den Webservice Barcode. Diesen Webservice müssen Sie bei der Schweizerischen Post beauftragen, da er standardmäßig nicht vorhanden ist. Dieser Webservice ist kostenlos. Wenn der Webservice zur Verfügung steht, können Sie den Technischen Benutzer einrichten.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu Swiss Post in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » Swiss Post**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 36.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu Swiss Post
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Swiss Post Benutzer, Swiss Post Passwort, Frankierlizenz-Nr.**
|Daten eingeben, wie von Swiss Post erhalten.

|**Nachnahmebetrag**
|**Mit dem ersten Versandpaket** oder **Auf Versandpakete verteilen** wählen.

|**Neuen Webservice-Endpoint nutzen**
|**JA** wählen. Aufgrund einer Umstellung bei Swiss Post wird die Schnittstelle angepasst. Alle Kunden erhalten neue Zugangsdaten. Diese Zugangsdaten hier eingeben. Bei Problemen mit der neuen Konfiguration Swiss Post direkt kontaktieren.
|====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 37.
. **Speichern** Sie die Einstellungen.

.Versandservices von Swiss Post im Tab **Portotabelle**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Service-Gruppe**
|Service-Gruppe im Bereich **Die Schweizerische Post** aus dem Dropdown-Menü wählen. Je nachdem, welche Service-Gruppe gewählt wird, erscheinen weitere Einstellungsmöglichkeiten. +
**__Wichtig__**: Die Service-Gruppen stehen erst nach dem Einrichten des technischen Benutzers zur Verfügung.

|**Validierung**
|Auf **Ausführen** klicken, damit die gewählten Werte von der Schweizerischen Post validiert werden.
|====

[#4400]
=== UPS

Wie Sie Versanddienstleister und Versandprofile einrichten und welche Einstellungen Sie außerdem vornehmen müssen und können, ist in den Kapiteln **<<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>** bis **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2400, API-Log abrufen>>** beschrieben. Die dort beschriebenen Einstellungen bilden die Voraussetzung, um nun versanddienstleisterspezifische Einstellungen vorzunehmen. Nehmen Sie daher die Einstellungen in den genannten Kapiteln zuerst vor. Fahren Sie anschließend mit diesem Kapitel fort.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu link:https://www.ups.com/one-to-one/register?sysid=myups&loc=de_DE&WT.svl=Footer[**UPS**, window="_blank"] in plentymarkets einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versanddienstleister » UPS**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 38.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu UPS
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**UPS-Benutzer, UPS-Passwort, UPS-Kundennummer, Zugriffsschlüssel**
|Daten eingeben, wie von UPS erhalten.

|**Anmeldung**
|Wählen, wie Versandaufträge mit mehreren Paketen bei UPS angemeldet werden sollen. +
**Gesammelt anmelden** = Alle Pakete werden zusammenhängend angemeldet und erreichen gleichzeitig den Empfänger. +
**__Wichtig__**: Die Einstellung **Gesammelt anmelden** ist Pflicht bei Nachnahmeaufträgen mit mehreren Paketen. +
**Separat anmelden** = Jedes Versandpaket wird einzeln als Versandauftrag angemeldet. Die Pakete können den Empfänger zeitlich versetzt erreichen.
|====

[IMPORTANT]
.Zahlungsart Nachnahme
====
Bei Nachnahmesendungen per UPS sind nur Schecks erlaubt. Sollen Schecks nicht berücksichtigt werden, muss im UPS-Versandprofil die Zahlungsart Nachnahme verboten werden, damit Sendungen dieser Art nicht über UPS angemeldet werden können.
====

[WARNING]
.Telefonnummer des Empfängers bei Auslandssendungen angeben
====
Geben Sie in den Absenderdaten die Telefonnummer des Empfängers generell auf Sendungen ins Ausland an.
====

Nehmen Sie nun die versanddienstleisterspezifischen Einstellungen der Versandservices in der Portotabelle vor. Diese Services sind erst in der Portotabelle sichtbar, nachdem Sie die Einstellungen im Versandprofil gespeichert haben.

[.instruction]
Versanddienstleisterspezifische Services einstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Öffnen Sie den Versanddienstleister.
. Wechseln Sie in das Tab **Portotabelle**.
. Klappen Sie die Region auf.
. Nehmen Sie die Einstellungen im Bereich **UPS Service** vor. Beachten Sie dazu die Erläuterungen in Tabelle 39.
. **Speichern** Sie die Einstellungen.

.Versandservices von UPS im Tab **Portotabelle**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Api Service**
|Versandart aus dem Dropdown-Menü wählen.

|**alternative Telefonnummer**
|Alternative Telefonnummer eingeben.
|====

[#4500]
== DHL-Packstation einrichten

DHL unterhält ein Netz von Packstationen, die rund um die Uhr verfügbar sind. Eine DHL-Packstation oder eine DHL-Postfiliale kann von Ihren Kunden optional als Lieferadresse angegeben werden. Nehmen Sie die Einstellungen für DHL-Packstationen im Menü **Einstellungen » Mandant (Shop) » Standard » Bestellvorgang » DHL-Packstation** vor.

Beachten Sie, dass die Angabe einer Packstation nur als Lieferanschrift möglich ist.

[.instruction]
DHL-Packstation einrichten:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Bestellvorgang » DHL-Packstation**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 40.
. **Speichern** Sie die Einstellungen.

.Optionen für DHL-Packstationen
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Packstation in Lieferadressen erlauben**
|Wählen, ob die Angabe einer Packstation in einer Lieferadresse im Webshop grundsätzlich erlaubt sein soll oder nicht. Wenn diese Option aktiviert ist, ist für den Webshop auch der DHL-Postfinder verfügbar. Mit dem Postfinder können Sie Packstationen und Postfilialen in den Lieferanschriftformularen suchen. +
Details zur Konfiguration des Postfinder finden Sie im Kapitel <<auftragsabwicklung/fulfillment/versand-vorbereiten#4600, **DHL-Postfinder einrichten**>>.

|**Maximalbestellwert bei Packstation**
|Maximalbestellwert eingeben. Wenn der Bestellwert höher liegt als der festgelegte Grenzwert, bekommt der Kunde eine Fehlermeldung beim Versuch, die Bestellung abzuschließen. +
**__Wichtig__**: Der Eintrag 0,00 (Standard) bedeutet, dass es keine Einschränkung des Bestellwertes gibt.

|**Packstationsvalidierung**
|Wählen, ob die Validierung von DHL-Packstationen erfolgen soll (aktiv) oder nicht (inaktiv). Der bei der Validierung vorgenommene Datenabgleich dient der zusätzlichen Sicherheit und kann Betrugsfälle verhindern. Es werden dabei die Adressdaten des Kunden (Rechnungsanschrift und E-Mail-Adresse) mit der Postnummer abgeglichen. Bei Unstimmigkeiten, z.B. die Postnummer passt nicht zum Kunden oder der Kunde ist gesperrt, kommt es zu einer Fehlermeldung.

|**Postnummer in Adressdaten abfragen**
|Käufer haben im Webshop auch die Möglichkeit, ihre Postnummer des DHL-Services **Postfinder** zu hinterlegen. Wählen, ob die Postnummer im Bestellvorgang abgefragt werden soll. +
Die Bezeichnungen, die im Bestellvorgang angezeigt werden, werden im Menü **CMS » Webdesign » Bestellvorgang » Kaufabwicklung** in den Untermenüs **Kundenregistrierung**, **Rechnungsanschrift** und **Lieferanschrift** hinterlegt.
|====

[WARNING]
.Rechnungsadresse
====
Es muss eine gültige Rechnungsadresse für den Kunden existieren. Die Angabe der Packstation wird mit den Daten der Rechnungsanschrift abgeglichen. +
Es kann somit auch keine Packstation als Lieferadresse angegeben werden, für die die Person in der Rechnungsanschrift nicht registriert ist. +
**Ausnahme**: Dies gilt nicht für die Auftragsbearbeitung. Sie können hier Lieferadressen speichern, es erfolgt keine Validierung.
====

Nachdem Sie die Option **Packstation in Lieferadressen erlauben** auf **JA** gestellt haben, können sowohl Ihre Kunden im Webshop als auch der Sie selbst im Adminbereich eine Packstation als Lieferanschrift angeben.

[.instruction]
Packstation beim Kunden als Lieferadresse eingeben:

. Öffnen Sie das Menü **Kunde » Kunde bearbeiten**.
. Öffnen Sie den Kunden, dessen Lieferanschrift Sie durch eine Packstation ersetzen möchten.
. Wechseln Sie in das Tab **Lieferanschriften**.
. Klicken Sie auf **Lieferanschrift bearbeiten**.
. Klicken Sie auf **DHL Packstation**.
. Geben Sie Postnummer, Packstation, PLZ und Ort der Packstation ein.
. **Speichern** Sie die Einstellungen.

[#4600]
== DHL-Postfinder einrichten

Mit dem DHL-Postfinder werden Ihren Kunden im Mein Konto-Bereich bei der <<omni-channel/online-shop/cms#webdesign-webdesign-bearbeiten-bestellvorgang-kaufabwicklung, **Kaufabwicklung**>> anhand der Postleitzahl die in der Nähe liegenden Postfilialen und Packstation angezeigt. Ihre Kunden haben dann die Möglichkeit, die Auswahl direkt in die Lieferanschrift zu übernehmen.

Um den DHL-Postfinder zu nutzen, müssen Sie Einstellungen in mehreren Menüs vornehmen. Diese Einstellungen sind auf der Handbuchseite <<omni-channel/online-shop/cms#webdesign-webdesign-bearbeiten-bestellvorgang-dhl-postfinder, **DHL-Postfinder**>> zusammengefasst.

[#4700]
== Fulfillment-Dienstleister im Überblick

In plentymarkets haben Sie als Händler die Möglichkeit, Ihren Warenbestand einem externen Dienstleister anzuvertrauen, der für Sie den Warenbestand oder einen Teil davon verwaltet, den Status an Ihr plentymarkets System zurückmeldet und auch den Versand der Artikel übernimmt. Und das alles automatisch, ohne dass Sie viel tun müssen. plentymarkets bietet auch Lösungen, um Ihren Versand über mehrere Dienstleister und Lager abzubilden.

In Tabelle 41 finden Sie die in plentymarkets verfügbaren Fulfillment-Dienstleister aufgelistet. Mit einem Klick auf den Dienstleister in der Tabelle gelangen Sie in das Unterkapitel, in dem dienstleisterspezifische Einstellungen beschrieben sind.

.Fulfillment-Dienstleister im Überblick
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**<<auftragsabwicklung/fulfillment/versand-vorbereiten#4800, DHL Fulfillment>>**
|Für Händler innerhalb Deutschlands. Versand: international.

|**<<auftragsabwicklung/fulfillment/versand-vorbereiten#5400, IDS Logistik>>**
|Für Händler innerhalb Deutschlands. Versand: international.

|**<<auftragsabwicklung/fulfillment/versand-vorbereiten#5500, iLOPACK>>**
|Für Händler innerhalb Deutschlands. Versand: international.

|**<<auftragsabwicklung/fulfillment/versand-vorbereiten#5600, Fulfillment by Amazon>>**
|Für Händler innerhalb Deutschlands. Versand: international.
|====

[#4800]
=== DHL Fulfillment

Dieses Kapitel beschreibt, wie Sie link:http://www.dhl.de/fulfillment[**DHL Fulfillment**, window="_blank"] in plentymarkets einrichten. Dazu gehört als Vorbereitung das Erstellen von Lagern sowie verschiedener Auftragsstatus und Retourengründe, bevor Sie die Einstellungen an der Schnittstelle vornehmen. Gehen Sie wie im Folgenden beschrieben vor.

[IMPORTANT]
.Klarna-Aufträge werden nicht an DHL Fulfillment übertragen
====
Die Auftragsübergabe von mit <<auftragsabwicklung/payment/klarna#, **Klarna**>> bezahlten Aufträgen an DHL Fulfillment ist noch nicht möglich. Es können nur Aufträge mit einem vorhandenen Rechnungsdokument an DHL Fulfillment übertragen werden. Klarna übermittelt die Rechnung jedoch erst nach Warenausgang an plentymarkets.
====

Die Sendungsanmeldung an DHL Fulfillment erfolgt automatisch über die Schnittstelle. Meldungen zu Sendungen, die bei DHL Fulfillment angemeldet wurden, finden Sie im Menü **Datenaustausch » API-Log**. Weitere Informationen zu den API-Log-Einträgen von DHL Fulfillment finden Sie auf der Handbuchseite <<basics/datenaustausch/api-log#, **API-Log**>>.

[#4900.subhead]
Lager für DHL Fulfillment erstellen

Erstellen Sie zunächst im Menü **Einstellungen » Waren » Lager** die Lager für die von DHL Fulfillment verwalteten Artikel. Geben Sie bei allen Lagern den gleichen Namen ein, z.B. DHL Fulfillment. Wählen Sie diese Lager dann auch als Hauptlager für die von DHL Fulfillment verwalteten Artikel. Öffnen Sie dazu den Artikel im Menü **Artikel » Artikel bearbeiten** und wählen Sie das Hauptlager im Bereich **Versand**. Weitere Informationen zum Erstellen von Lagern finden Sie auf der Handbuchseite <<warenwirtschaft/lager-einrichten#, **Lager einrichten**>>.

Erstellen Sie für die Konfiguration von DHL Fulfillment folgende **Lagertypen**:

* **Vertrieb**
* **Vorrat**
* **Reparatur**
* **Sonstiges**

Für die korrekte Abwicklung über die DHL Fulfillment-Schnittstelle benötigen Sie mindestens ein Lager des Lagertyps **Vertrieb** mit dem Logistiktyp **DHL Fulfillment**. Bis zu 4 Lager sind möglich. Die Zuordnung erfolgt seitens DHL anhand der von DHL verwendeten Bestandstypen. Dem Vertriebslager ordnet DHL z.B. Waren des Bestandstyps **Prime Selection** zu. Diese Waren sind direkt zum Verkauf bestimmt. Waren des Bestandstyps **Second Quality** sind nicht für den Verkauf bestimmt und benötigen ein separates Lager, z.B. des Lagertyps **Vorrat**. Werden solche Waren nach Prüfung für gut befunden, erhalten sie den Bestandstyp **Prime Selection** und somit die Zuordnung zum Vertriebslager.

[WARNING]
.Lagerzuordnung erfolgt durch DHL
====
Die Zuordnung zu den für DHL Fulfillment konfigurierten Lagern wird von DHL vorgenommen. Nehmen Sie selbst keine Änderungen an den Beständen, die für DHL Fulfillment bestimmt sind, vor.
====

Folgende Bestandstypen werden von DHL Fulfillment verwendet:

* **Prime Selection**: Erste Wahl, für den Verkauf bestimmt, Zuordnung zum Vertriebslager
* **Second Quality**: Zweite Wahl, nicht für den Verkauf bestimmt, Zuordnung zum Vorratslager
* **Damaged**: Beschädigte Ware, nicht für den Verkauf bestimmt, Zuordnung zum Reparaturlager
* **Blocked** und **Clearing**: Gesperrte Waren und Waren, deren Zustand geprüft werden muss, kein Verkauf, Zuordnung zum Sonderlager (Lagertyp: Sonstiges)

Beschädigte Waren können Retouren sein, aber auch Artikel, die z.B. bei der Bewegung im Lager beschädigt werden oder beschädigt geliefert wurden.

[#5000.subhead]
Auftragsstatus erstellen

Zur Zuordnung legen Sie im Menü **Einstellungen » Aufträge » Auftragsstatus** zwei <<auftragsabwicklung/auftraege/auftraege-verwalten#, **Auftragsstatus**>> für die an DHL Fulfillment übermittelten Aufträge an. Nachfolgend zwei Beispiele:

* [6.5] Beim Fulfillment-Dienstleister im Versand +
→ Für korrekt angemeldete Aufträge

* [5.6] Fehler beim Fulfillment-Dienstleister +
→ Für Aufträge, die DHL Fulfillment aufgrund fehlerhafter Auftragsdaten nicht verarbeiten kann. Beispiel: Artikelstammdaten wurden noch nicht an DHL Fulfillment übergeben.

[TIP]
.Aufträge im Statusbereich 5.x
====
Alle Aufträge im **Statusbereich 5.x**, für die Rechnungen erzeugt wurden, werden zu den definierten Übertragungszeiten (in der Regel viertelstündlich) automatisch an DHL Fulfillment übermittelt. Einzige Ausnahme ist der Auftragsstatus, der für die Option **Auftragsstatus bei Fehler** festgelegt wurde. Aufträge in diesem Status werden nicht an DHL Fulfillment übermittelt.

Meldungen zu Sendungen, die bei DHL Fulfillment angemeldet wurden, finden Sie im Menü **Datenaustausch » API-Log**. Weitere Informationen zu den API-Log-Einträgen von DHL Fulfillment finden Sie auf der Handbuchseite <<basics/datenaustausch/api-log#, **API-Log**>>.
====

Soll ein eigener Workflow für den Auftragsdurchlauf der DHL Fulfillment-Aufträge hinterlegt werden, empfiehlt sich die Einführung eines weiteren Status, z.B. **5.4 Vorbereitung für Fulfillment-Dienstleister**, um DHL Fulfillment-Aufträge bereits vor der Übertragung an DHL von anderen Aufträgen abzugrenzen.

[#5100.subhead]
Retourengründe anlegen

Wenn die Retouren von DHL Fulfillment in Ihr plentymarkets System importiert werden sollen, benötigen Sie Retourengründe. Diese Retourengründe legen Sie im Menü **<<auftragsabwicklung/auftraege/auftraege-verwalten#retoure, Einstellungen » Aufträge » Auftragstypen » Retoure>>** an. Verknüpfen Sie dann die von Ihnen konfigurierten Retourengründe mit den von DHL Fulfillment vorgegebenen Gründen im Menü **Einstellungen » Aufträge » Versand » Fulfillment-Dienstleister » DHL Fulfillment**.

[#5200.subhead]
Schnittstelle einrichten

In den Schnittstelleneinstellungen speichern Sie die Login-Daten, ordnen die Auftragsstatus zu und verknüpfen die Retourengründe.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Fulfillment-Dienstleister » DHL Fulfillment**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 42.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu DHL Fulfillment
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Schnittstelle aktiv**
|Häkchen setzen, um die Schnittstelle zu aktivieren. Schnittstelle erst aktivieren, wenn die oben beschriebene Lagerkonfiguration durchgeführt wurde.

|**Mandantenkennung**
|DHL Fulfillment-Mandantenkennung, d.h. Kundennummer, eingeben.

|**FTP-Zugang**
|Bevor die Schnittstelle produktiv genutzt werden kann, ist ein Testbetrieb vorgesehen. Zum Testen der Schnittstelle hier die Option **Testbetrieb** wählen und die von DHL erhaltenen Zugangsdaten eingeben. Diese sind für Test- und Produktivbetrieb unterschiedlich. +
Die Zugangsdaten für den Produktivbetrieb werden von DHL nach erfolgreichem Testbetrieb zur Verfügung gestellt. Nach Wahl der Option **Produktivbetrieb** wird die Option **Testdaten zurücksetzen** angezeigt. Aktivieren, wenn die Testdaten gelöscht werden sollen.

|**FTP-Login**
|Login-Name für das FTP-Verzeichnis eingeben.

|**FTP-Passwort**
|Passwort für das FTP-Verzeichnis eingeben.

|**Auftragsstatus nach Meldung**
|Auftragsstatus wählen, der für die Meldung bei DHL Fulfillment verwendet werden soll. +
__**Wichtig**__: Der hier gewählte Auftragsstatus hat Auswirkungen auf die Anmeldung neuer Aufträge an DHL Fulfillment, d.h. neue Aufträge mit diesem Status werden bei der Anmeldung nicht berücksichtigt.

|**Auftragsstatus bei Fehler**
|Auftragsstatus wählen, der bei Fehlern verwendet werden soll.

|**Aufbau Produktnummer**
|Wählen, wie die Produktnummer an DHL Fulfillment übermittelt werden soll. +
**SKU** = (Standardeinstellung) Die SKU besteht aus der Artikel-ID, der Preis-ID und der Varianten-ID. +
**Variantennummer** = Ist erforderlich, wenn mit DHL Fulfillment bereits eine andere Software verwendet wurde und die dortigen Bestände korrekt auf plentymarkets Artikel abgebildet werden sollen.

|**Produktname**
|**Artikelname;Attribut;Variante** (Standardeinstellung) oder **Variantenname** wählen. Dieser Produktname wird dann an DHL Fulfillment übermittelt.

|**Mindesthaltbarkeitsdatum, Originalkarton, Zerbrechlich, Seriennummer**
|Merkmalverknüpfung zur Übermittlung der Artikeleigenschaft an DHL Fulfillment. Details dazu im Abschnitt **<<auftragsabwicklung/fulfillment/versand-vorbereiten#5300, Merkmale an DHL Fulfillment übermitteln>>**.

|**Retourengründe**
|Retourengründe von DHL Fulfillment mit den im Menü **<<auftragsabwicklung/auftraege/auftraege-verwalten#retoure, Einstellungen » Aufträge » Auftragstypen » Retoure>>** angelegten Retourengründen verknüpfen.
|====

[#5300.subhead]
Merkmale an DHL Fulfillment übermitteln

Erstellen Sie im Menü **Einstellungen » Artikel » Merkmale** Eigenschaften wie z.B. "Zerbrechlich" oder "Originalkarton", die Sie anschließend an DHL Fulfillment übermitteln, damit die Artikel logistisch entsprechend vorbereitet werden können. Wie Sie ein Merkmal erstellen, ist auf der Handbuchseite <<artikel/artikel-verwalten#, **Artikel verwalten**>> im Kapitel **<<artikel/artikel-verwalten#500, Merkmale erstellen>>** beschrieben. Die folgenden Merkmale können an DHL Fulfillment übermittelt werden:

* **Mindesthaltbarkeitsdatum**: Der Artikel wird als MHD-pflichtiger Artikel im Lager bei DHL Fulfillment geführt. Beim Wareneingang erfasst DHL Fulfillment für Artikel mit diesem Merkmal ein Mindesthaltbarkeitsdatum.
* **Originalkarton**: Der Artikel wird von DHL Fulfillment einzeln im Originalkarton versendet.
* **Zerbrechlich**: Der Artikel wird von DHL Fulfillment mit zusätzlichem Füllmaterial am Packplatz verpackt.
* **Seriennummer**: Die am Packplatz erfassten Seriennummern werden mit der Versandmeldung (Auftragsrückmeldung) an plentymarkets von DHL Fulfillment zurückgespielt, damit die Seriennummer z.B. auf die Rechnung gedruckt und vom Kunden für weitere Verwendungen (z.B. Dokumentation, Gutscheinfreigabe) verwendet werden kann.

[IMPORTANT]
.Korrekten Merkmaltyp für die Merkmale wählen
====
Erstellen Sie im Menü **Einstellungen » Artikel » Merkmale** die folgenden drei Merkmale mit dem Merkmaltyp **Kein**:

* **Mindesthaltbarkeitsdatum**
* **Originalkarton**
* **Zerbrechlich**

Erstellen Sie das Merkmal **Seriennummer** mit dem Merkmaltyp **Auswahl** und speichern Sie die folgenden drei Werte:

* **SN** (Erfassung der Seriennummer eines Artikels)
* **SNK** (Erfassung von Seriennummernbereichen pro Artikel)
* **SNK2** (Erfassung von Seriennummernbereichen pro Auftragsposition)

Weitere Informationen zu Merkmalen finden Sie auf der Handbuchseite <<artikel/artikel-verwalten#, **Artikel verwalten**>> im Kapitel **<<artikel/artikel-verwalten#480, Merkmale verwalten>>**.
====

Nachdem Sie die Merkmale erstellt haben, **<<artikel/artikel-verwalten#80, aktivieren>>** Sie die Merkmale am Artikel im Tab **Merkmale**. Abschließend ordnen Sie die Merkmale in der Schnittstellenkonfiguration im Menü **Einstellungen » Aufträge » Versand » Fulfillment-Dienstleister » DHL Fulfillment** zu.

Vor der Übertragung des Auftrags an DHL Fulfillment findet eine Prüfung der Empfängeradresse auf Richtigkeit der Form und Struktur statt, d.h. plentymarkets prüft z.B., ob alle Pflichtfelder wie beispielsweise der Name ausgefüllt wurden. +
Sollten fehlerhafte HTML-Zeichen bzw. für die API ungültige Zeichen in der Adresse enthalten sein, werden diese korrigiert. Wenn dennoch ein nicht korrigierbarer Fehler in der Adresse enthalten ist, wird der Auftrag nicht übermittelt. Dies verhindert eine Störung im Prozess, da DHL Fulfillment keine ungültigen bzw. fehlerhaften XML-Dateien von dem FTP-Server abholen kann.

[#5400]
=== IDS Logistik

Bevor Sie die Schnittstelle zu IDS Logistik einrichten, registrieren Sie sich bei link:http://www.ids-logistik.de[**IDS Logistik**, window="_blank"].

Erstellen Sie dann im Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versanddienstleister** den Fulfillment-Dienstleister. Wählen Sie in der Spalte **Versanddienstleister** die Option **Nicht bestimmt** aus dem Dropdown-Menü. Weitere Informationen finden Sie im Kapitel **<<auftragsabwicklung/fulfillment/versand-vorbereiten#800, Versanddienstleister erstellen>>**.

Richten Sie anschließend das Versandprofil im Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile** ein. Wie Sie dazu vorgehen, ist im Kapitel **<<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, Versandprofil erstellen>>** beschrieben.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu IDS Logistik einzurichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Fulfillment-Dienstleister » IDS Logistik**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 43.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu IDS Logistik
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Depotnummer, Standard 800**
|Depotnummer eingeben, wie von IDS Logistik erhalten. Standard: 800

|**Versender-Kundennummer, Feld: VKDNR (vierstellig)**
|4-stellige Kundennummer des Versenders eingeben.

|**Sendungsnummer (vierstellig)**
|4-stellige Sendungsnummer eingeben, wie von IDS Logistik erhalten.

|**Lieferscheinnummer**
|Wählen, welcher Wert als Lieferscheinnummer übermittelt werden soll oder ob kein Wert als Lieferscheinnummer übermittelt werden soll. +
Eine der folgenden Optionen wählen: +
**Artikel-ID +
Artikelnummer +
Externe Artikel-ID +
Nicht übermitteln +
[Freitextfeld 1 bis 20]**

|**Inhalt**
|Wählen, welcher Wert als Inhalt übermittelt werden soll oder ob kein Wert als Inhalt übermittelt werden soll. +
Optionen: +
**Artikel-ID +
Artikelnummer +
Externe Artikel-ID +
Nicht übermitteln +
[Freitextfeld 1 bis 20]**

|**Empfänger-Kundennummer, Feld: KDNR**
|**Kundennummer** oder **Auftragsnummer** des Empfängers wählen.

|**Übertragene Artikel (Maximum 99)**
|Anzahl der zu übertragenden Artikel eingeben (maximal 99).

|**Hinweistextschlüssel 1 / 2**
|Festlegen, ob und ggf. welcher Hinweistext an IDS Logistik übermittelt werden soll.

|**Auftragstyp**
|**Abholauftrag** oder **Zustellauftrag** wählen.

|**Mobiltelefonnummern übertragen**
|Festlegen, ob die Mobiltelefonnummern der Empfänger an IDS Logistik übertragen werden sollen oder nicht.

|**Anzahl Ziffern für AUFTRAGSNR, Minimum 16**
|Die Auftragsnummer wird mit der <<auftragsabwicklung/fulfillment/dokumente-erzeugen#200, **Lieferanschriftenliste**>> in eine CSV-Datei exportiert und enthält folgende Parameter: +
- IDS-spezifische ID (3 Ziffern) +
- Kundennummer (4 Ziffern) +
- Lieferscheinnummer (6 Ziffern) +
- Anzahl der Colli (2 Stellen) +
- Prüfziffer (1 Stelle) +
**Beispiel**: 800 6913 000001 00 0 +
Im Standard ist 16 voreingetragen, was für bis zu 6-stellige Lieferscheinnummern ausreichend ist. +
Wenn die Anzahl der Ziffern nicht ausreicht, z.B. wenn 7-stellige Lieferscheinnummern verwendet werden, den jeweils benötigten höheren Wert eingeben, z.B. 17.
|====

[#5500]
=== iLOPACK

Bevor Sie die Schnittstelle zu iLOPACK einrichten, registrieren Sie sich bei link:http://www.ilopack.de/[**iLOPACK**, window="_blank"].

Erstellen Sie dann im Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versanddienstleister** den Fulfillment-Dienstleister. Wählen Sie in der Spalte **Versanddienstleister** die Option **Nicht bestimmt** aus dem Dropdown-Menü. Weitere Informationen finden Sie im Kapitel **<<auftragsabwicklung/fulfillment/versand-vorbereiten#800, Versanddienstleister erstellen>>**.

Richten Sie anschließend das Versandprofil im Menü **Einstellungen » Aufträge » Versand » Versandoptionen** ein. Wie Sie dazu vorgehen, ist im Kapitel **<<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, Versandprofil erstellen>>** beschrieben.

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu iLOPACK einzurichten. Unterhalb der Tabelle wird beschrieben, wie Sie die Datenübergabe zu iLOPACK einrichten.

[.instruction]
Schnittstelle einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Fulfillment-Dienstleister » iLopack**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 44.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Schnittstelle zu iLOPACK
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**iLopack-User-ID**
|User-ID eingeben, wie von iLOPACK erhalten.

|**Standardlager**
|Standardlager für Aufträge wählen, die mit iLOPACK versendet werden.

|**Nach Hauptlager filtern**
|Aktivieren, wenn nur Ware berücksichtigt werden soll, für die das unter Standardlager gewählte Lager das Hauptlager ist.
|====

[.subhead]
Datenübergabe zu iLOPACK einrichten

Im Menü **Aufträge » Fulfillment » iLOPACK-Datenübergabe** richten Sie die Datenübergabe zum Fulfillment-Dienstleister iLOPACK ein. Bei der Datenübergabe werden CSV-Dateien für iLOPACK generiert und automatisch in einem Ordner auf dem FTP-Server gespeichert. iLOPACK greift dann auf diesen Ordner zu.

[.instruction]
Datenübergabe zu iLOPACK einrichten:

. Öffnen Sie das Menü **Aufträge » Fulfillment » iLOPACK-Datenübergabe**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 45.
. Klicken Sie auf das Zahnrad, um die CSV-Datei zu erzeugen.

.Einstellungen im Menü **Aufträge » Fufillment » iLOPACK-Datenübergabe**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Daten**
|Wählen, ob **Aufträge** oder **Artikelstammdaten** übertragen werden sollen.

|**Mandant (Shop)**
|Einen Mandant (Shop) oder **ALLE** wählen.

|**Auftragsstatus**
|Auftragsstatus der Daten, die exportiert werden sollen, wählen.

|**Lager**
|Ein Lager oder **ALLE** wählen.

|**Ändere Auftragsstatus**
|Auftragsstatus einstellen, in den die Daten nach der Datenübergabe wechseln sollen.
|====

[#5600]
=== Fulfillment by Amazon

FBA ist das Kürzel für Fulfillment by Amazon, einem Service von Amazon, bei dem Amazon die Lagerhaltung sowie die gesamte Logistik übernimmt. Welche Einstellungen Sie vornehmen müssen, um diesen Service zu nutzen, lesen Sie auf der Handbuchseite von <<omni-channel/multi-channel/amazon#, **Amazon**>> im Kapitel **<<omni-channel/multi-channel/amazon#3300, FBA-Service von Amazon nutzen>>**.

== Amazon Prime

Sie haben in plentymarkets die Möglichkeit, Filter einzustellen, damit Aufträge mit den Versandbedingungen von Amazon Prime gesondert behandelt werden. Außerdem können Sie Versandlabel für Amazon Prime-Aufträge über die Amazon Merchant Fulfillment API generieren. Welche Einstellungen Sie vornehmen müssen, ist auf der Handbuchseite von <<omni-channel/multi-channel/amazon#, **Amazon**>> im Kapitel <<omni-channel/multi-channel/amazon#4200, **Amazon Prime-Aufträge bearbeiten**>> beschrieben.

Erfahren Sie mehr über Amazon Prime im folgenden Videotutorial:

video::158480475[vimeo]
