= Standorte
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Standorte, Buchhaltung, Firmensitz
:position: 20

Auf dieser Handbuchseite wird die Konfiguration von Standorten mit den Buchhaltungseinstellungen beschrieben, die im Menü **Einstellungen » Mandant (Shop) » Shop wählen » Standorte** konfiguriert werden.

== Buchhaltung pro Standort

Die <<auftragsabwicklung/auftraege/_buchhaltung#, **Buchhaltung**  >> in plentymarkets ist für Mandanten nach Standorten getrennt möglich. Damit können Sie pro Mandant mehrere Firmensitze in verschiedenen Ländern verwalten. Jeder Mandant hat standardmäßig mindestens einen Standort, und zwar den Standort des Firmensitzes des Unternehmens. Das zugehörige Menü ist das erste unter **Standorte** und trägt die Bezeichnung des Landes des Standortes, z.B. Deutschland.

Die Konfiguration gliedert sich pro Mandant und pro Standort in die Untermenüs **Einstellungen** und <<auftragsabwicklung/auftraege/_buchhaltung#, **Buchhaltung**  >>. Für jeden neuen Standort kann die Buchhaltung individuell konfiguriert werden.

== Neuen Standort anlegen

Gehen Sie wie im Folgenden beschrieben vor, um einen neuen Standort anzulegen.

[.instruction]
Neuen Standort anlegen:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Shop wählen » Standorte**.
. Zeigen Sie mit dem Cursor auf den Menüpunkt **Standorte**. +
→ Rechts wird ein Pfeil eingeblendet.
. Klicken Sie auf den **Pfeil**. +
→ Die Option **Neuer Standort** wird eingeblendet.
. Klicken Sie auf **Neuer Standort**. +
→ Ein Bearbeitungsfenster wird angezeigt.
. Tragen Sie unter **Name** eine Bezeichnung für den neuen Standort ein.
. Wählen Sie das **Land** des neuen Standorts aus dem Dropdown-Menü.
. Klicken Sie auf **Speichern**, um die Einstellungen zu sichern.

== Einstellungen

Für jeden Standort ist ein Untermenü **Einstellungen** verfügbar, in dem Sie die Bezeichnung des Standortes ändern oder
den Standort löschen können. Um Fehler zu vermeiden, ist das Land eines Standortes nicht änderbar. Legen Sie daher bei
Änderung des Landes eines Standortes einen neuen Standort an. Ein Standort, in der Regel der Firmensitz des Unternehmens,
wird im Menü <<omni-channel/online-shop/mandanten-einrichten#grundeinstellungen, **Grundeinstellungen**  >> als **Standard-Standort** festgelegt.

Sie können einen Standort nur löschen, wenn ein weiterer Standort vorhanden ist. Ein Standort,
der im Menü <<omni-channel/online-shop/mandanten-einrichten#grundeinstellungen, **Grundeinstellungen**  >>
 als **Standard-Standort** hinterlegt ist, kann nicht gelöscht werden.

[.instruction]
Standort löschen:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Shop wählen » Standorte**.
. Öffnen Sie das Untermenü **Einstellungen** des zu löschenden Standorts.
. Klicken Sie auf **Löschen**. +
→ Der Standort wird nach einer Sicherheitsabfrage gelöscht.
