= Allyouneed einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Allyouneed, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz Allyouneed in Ihrem plentymarkets System ein.
:position: 1

Auf dieser Handbuchseite finden Sie Informationen zur Einrichtung des Marktplatzes *Allyouneed* in plentymarkets. Sie erfahren, wie Sie die Schnittstelle einrichten, die Kategorien verknüpfen und Ihre Artikel zu Allyouneed exportieren.

[#100]
==  Bei Allyouneed registrieren

Um die Schnittstelle zu *Allyouneed* einzurichten, registrieren Sie sich zunächst als Händler bei link:http://de.allyouneed.com/de/dealer/page/selfsignup/step1[*Allyouneed*^]. Sie erhalten die nötigen Zugangsdaten, die Sie für die Einstellungen in plentymarkets benötigen.

[#200]
==  Allyouneed in plentymarkets einrichten

Nachdem Sie sich bei Allyouneed registriert haben, verwenden Sie Ihre Zugangsdaten, um den Marktplatz in plentymarkets einzurichten. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Allyouneed in plentymarkets einrichten:

.  Öffnen Sie das Menü *System » Märkte » Allyouneed » Einstellungen*.
.  Nehmen Sie die Einstellungen gemäß Tabelle 1 vor.
. *Speichern* Sie die Einstellungen.

.Grundeinstellungen des Marktplatzes Allyouneed.
[cols="1,3"]
|====
| Einstellung | Erläuterung

2+| Zugangsdaten

|*E-Mail-Adresse*
| E-Mail-Adresse eingeben.

|*Passwort*
| Passwort des Allyouneed-Kontos eingeben.

|*Testkonto*
|*Ja* für *Testmodus*. +
Testumgebung von Allyouneed aktivieren. Damit wird der Artikelupload getestet und Testaufträge in das System importiert. Für ein Testkonto sind andere Zugangsdaten nötig. Registrieren Sie sich bei Allyouneed für ein link:https://portal.allyouneed.com/funktionsuebersicht/testsystem.html[*Testsystem*^].

2+| Grundkonfiguration

|*Artikelname*
| Name wählen, der für Allyouneed-Artikel verwendet wird.

|*Zuordnung Mandant (Shop)*
| Wählen, für welche Shops die Einstellungen gelten.

|*Artikelverfügbarkeit*
| Verfügbarkeit wählen. Artikel mit den gewählten Verfügbarkeiten werden übertragen. Die Optionen für Artikelverfügbarkeit werden im Menü <<artikel/artikel-verwalten#190, *System » Artikel » Verfügbarkeit*>> eingerichtet.

|*Lieferzeit*
| Lieferzeit wählen oder die Einstellung *Nicht übertragen*.

|*Aufschlag*
| Anzahl an Tagen eingeben, die zum Wert unter *Lieferzeit* hinzuaddiert werden.

|*Lagerauswahl*
|*Hauptlager* oder *maximaler Bestandsmenge aller Vertriebslager* wählen.

|*Bestands- und Preisänderungen automatisch übertragen*
| Wählen, ob Bestands- und Preisänderungen automatisch übertragen werden. +
*JA* = Die geänderten Preise und Bestände werden einmal pro Stunde an Allyouneed übertragen. +
*NEIN* = Bestands- und Preisänderungen werden nur abgeglichen, wenn der komplette Artikel zu Allyouneed übertragen wird. Preise und Bestände werden dann etwa alle 7 Tage abgeglichen.

2+| Erweiterte Optionen

|*Auftrag als bezahlt markieren*
|*Ja* wählen, um den Auftrag nach dem Auftragsimport als bezahlt zu makieren.

|*Technische Daten der Beschreibung anhängen*
|*JA* wählen, um den Eintrag unter *Technische Daten* im Tab *Texte* der Artikeldaten dem Eintrag unter *Beschreibung* des Artikels hinzuzufügen.

|*Bestandspuffer*
| Zahlenwert als Bestandspuffer eingeben, z. B. *4*. In diesem Fall werden 4 Artikel für Allyouneed reserviert und vom Bestand im System abgezogen.

|*Menge für Artikel ohne Bestandsbindung*
| Artikelmenge eingeben, die für Artikel ohne Bestandsbindung bei Allyouneed als *Bestand* geführt wird.

|*Grenzwert für Artikel-Upload*
| Oberen Grenzwert für die Artikelmenge eingeben, d.h. wieviel Stück pro Artikel hochgeladen werden dürfen.

|*Regelsteuersatz*
| Den Regelsteuersatz wählen.

|*Ermäßigter Steuersatz*
| Verwendeten *ermäßigten Steuersatz* wählen, wenn zutreffend. +
Einstellungen zu Steuersätzen im Menü <<auftraege/buchhaltung#, *Buchhaltung*>> beachten.

|*Artikelnamen um Variantennamen erweitern*
|*Ja* wählen, um die Artikelnamen zu erweitern. +
*Beispiel*: Poloshirt [Farbe:Dunkelblau; Größe:L].

|*Hersteller übertragen*
| Option für die Übertragung der *Hersteller* wählen. Damit Artikel zu Allyouneed exportiert werden, ist die Angabe des Herstellers zwingend erforderlich.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierten Funktionen bereit:

* Tägliche Übertragung von neuen Artikeln und Artikeländerungen
* Stündlicher Abgleich von Auftragsstatus
* Stündlicher Auftragsimport
* Stündliche Versandbestätigung für Aufträge, bei denen der Warenausgang gebucht wurde
* Stündliche Stornierung von Aufträgen mit einem Status größer [8] und kleiner [9]
* Täglicher Bestandsabgleich von allen Beständen
* stündlicher Abgleich von Angebotsdaten (z.B. geänderte Bestände, Preise)
* Tägliche Löschung von nicht mehr vorhandenen Artikeln auf dem Marktplatz

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit Allyouneed verknüpfen können, muss im Menü *System » Aufträge » Auftragsherkunft* die Auftragsherkunft Allyouneed aktiviert werden.

[.instruction]
Auftragsherkunft für Allyouneed aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Auftragsherkunft*.
. Setzen Sie bei *Allyouneed* ein Häkchen.
. *Speichern* Sie die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf Allyouneed verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID*>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Allyouneed einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Setzen Sie ein Häkchen neben der Option *Allyouneed*.
. Setzen Sie ien Häkchen neben der Option *Web-API*.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen. +
→ Der Artikel ist auf Allyouneed verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

Um Ihre Artikel für den Export zu Allyouneed vorzubereiten, sind die folgend beschriebenen Einstellungen nötig. Außerdem gibt es Vorgaben von Allyouneed, die Sie beachten müssen, damit die Artikel korrekt exportiert werden. Folgende Felder sind bei der Vorbereitung für den Artikel-Export Pflichtfelder in der Artikelbearbeitung:

* *Name*: Text in das Feld *Name 1* im Tab *Texte* eingeben. Der eingegebene Text wird als Artikelname zu Allyouneed übertragen.
* *Preis*: Wert größer 0,00 eingeben.
* *Hersteller*: Text in das Feld *Hersteller* im Tab *Global* eingeben.
* *Kategorie*: Kategorien verknüpfen. Weitere Informationen finden Sie im Kapitel <<artikel/artikel-verwalten#300, Kategorien verknüpfen>>.
* *Beschreibung (lang)*: Text in das Feld *Artikeltext* im Tab *Texte* eingeben. Der eingegebene Text wird als lange Produktbeschreibung zu Allyouneed übertragen.
* *Beschreibung (kurz)*: Text in das Feld *Vorschautext* im Tab *Texte* eingeben. Der eingegebene Text wird als kurze Produktbeschreibung zu Allyouneed übertragen. Die maximale Länge beträgt 200 Zeichen. Wird kein Vorschautext eingegeben, wird automatisch der Artikelname als Text eingesetzt.

Folgende Felder sind bei der Vorbereitung für den Artikel-Export optional:

* *Artikelbilder*: Artikelbilder werden nur mit einer Mindestgröße von 500 x 500 px bei einer Auflösung von 72 dpi in den Formaten JPG, GIF und PNG von Allyouneed akzeptiert.
* *Technische Daten*: Text in das Feld *Technische Daten*im Tab *Texte* eingeben. Der eingegebene Text wird mit der normalen Beschreibung angezeigt, wenn in den Grundeinstellungen die Option *Technische Daten der Beschreibung anhängen* aktiviert ist.

[NOTE]
.Artikel "offline" schalten
====
Soll der Artikel nicht mehr exportiert werden, öffnen Sie den Artikel im Menü *Artikel » Artikel bearbeiten* und deaktivieren Sie im Tab *Verfügbar* die Option *Allyouneed*. Beim nächsten Durchgang der Warenbestandsautomatik wird der Artikel dann in Allyouneed "offline" gesetzt.
====

[#350]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft Allyouneed einen Verkaufspreis festzulegen. Dieser Preis wird auf Allyouneed angezeigt.

[.instruction]
Verkaufspreis für Allyouneed festlegen:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setzen Sie ein Häkchen bei der Herkunft *Allyouneed*.
. *Speichern* Sie die Einstellungen.

[#400]
==  Kategorien verknüpfen

Zur Verknüpfung Ihrer Artikelkategorien mit den Kategorien von Allyouneed stehen etwa 3000 Produktkategorien bei Allyouneed zur Auswahl. Kategorien werden bis in die letzte Ebene bei Allyouneed zugeordnet. Prüfen Sie Ihre Kategorien und erstellen Sie ggf. weitere Unterkategorien, die zur Verknüpfung mit Allyouneed besser geeignet sind.

[TIP]
.Erweiterbare Allyouneed-Kategorien
====
Die Kategorien bei Allyouneed sind flexibel erweiterbar. Nehmen Sie dazu Kontakt mit *link:https://portal.allyouneed.com/verkaufen-mit-allyouneed.html[Allyouneed.com^]* auf.
====

[.instruction]
Kategorien verknüpfen:

.  Öffnen Sie das Menü *System » Märkte » Allyouneed » Kategorieverknüpfung*.
.  Wählen Sie aus der Dropdown-Liste *Allyouneed-Kategorie* eine passende Hauptkategorie. +
→ Das Fenster *Kategorieauswahl* wird geöffnet.
. Wählen Sie eine Unterkategorie. +
→ Die *Kategorie-ID* wird erst angezeigt, wenn die unterste Kategorieebene erreicht ist.
.  Klicken Sie auf das *Zahnrad*, um die Verknüpfung zu sichern. +
→ Das Bearbeitungsfenster wird geschlossen.
. *Speichern* Sie die Einstellungen.

[#500]
== Attribute verknüpfen

Sie können auch Variantenartikel zu Allyouneed exportieren, d.h. Artikel, die bestimmte Attribute aufweisen. Wenn Sie <<artikel/artikel-verwalten#390, *Attribute*>> im plentymarkets System erstellt haben, müssen diese Attribute mit Allyouneed verknüpft werden. Nachfolgend wird beschrieben, wie Sie das Attribut *Farbe* der Gruppe *Oberbekleidung* mit Allyouneed verknüpfen. Verknüpfen Sie weitere Attribute auf die gleiche Weise. Informationen zu den Vorgaben für die Parameter und zu den für Allyouneed verwendbaren Attributwerten finden Sie in der link:https://portal.allyouneed.com/support/downloadbereich/allyouneed.html[*Allyouneed-Dokumentation*^].

[.instruction]
Attribute verknüpfen:

. Öffnen Sie das Menü *System » Artikel » Attribute*. +
→ Eine Übersicht aller erstellten Attribute wird geöffnet.
. Klappen Sie das Attribut *Farbe* auf.
. Wechseln Sie in das Tab *Marktplatzvariation*.
. Wählen Sie in der Dropdown-Liste *Marktplatz* die Option *Allyouneed*. +
→ Eine zusätzliche Dropdown-Liste *Allyouneed* wird angezeigt.
. Wählen Sie in der Dropdown-Liste *Gruppe* die Option *Oberbekleidung*.
. Wählen Sie in der Dropdown-Liste *Attribut* die Option *Farbe*.
. Geben Sie ggf. eine Einheit ein.
. Geben Sie die zu Ihren Attributwerten passenden Allyouneed-Attributwerte im Bereich Marktplatzvariation ein.
. *Speichern* Sie die Einstellungen.

[NOTE]
.Optional: Einheit
====
Unter den beiden Pflichtoptionen *Gruppe* und *Attribut* erscheint die dritte Option *Einheit* nur bei manchen Gruppen bzw. Attributen, z.B. bei *Abmessungen*. Geben Sie optional einen Wert ein, z.B. *dpt* (Dioptrien) für die Stärke von Kontaktlinsen.
====

[#600]
==  Merkmale erstellen

Merkmale benötigen Sie für die Angabe des Zustands sowie der Versandangaben. Erstellen Sie zuvor eine <<artikel/artikel-verwalten#490, *Merkmalgruppe*>> für Allyouneed, die Sie dann für die Zuordnung der Merkmale verwenden. Hier werden nur die für Allyouneed wichtigen Optionen genannt. Weitere Details finden Sie auf der Handbuchseite <<artikel/artikel-verwalten#480, *Merkmale verwalten*>>.

[#700]
===  Merkmal für Zustand erstellen

Allyouneed hat einen Extrabereich für den link:https://portal.allyouneed.com/verkaufen-mit-allyouneed/highlights-vorteile/b-ware.html[Verkauf von B-Ware^]. Um dort zu listen, haben Sie zwei unterschiedliche Möglichkeiten:

*  Sie wählen unter *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Global* im Bereich *Grundeinstellungen* den Wert *B-Ware* aus der Dropdown-Liste *Zustand API*.
*  Sie erstellen ein <<artikel/artikel-verwalten#500, *Merkmal*>> für den Zustand. Ein Merkmal hat den Vorteil, dass auch andere Zustände unterstützt werden, z.B. *Demoware*.

Wenn der Verkauf eines Artikels als B-Ware durch eine der beiden Möglichkeiten aktiviert wurde, werden die drei Felder *EAN*, *Hersteller* und *Herstellernummer* nicht mehr übertragen. Damit soll verhindert werden, dass B-Ware mit den normalen Produkten in der Suche vermischt wird.

[.instruction]
Merkmal für Zustand erstellen:

. Öffnen Sie das Menü *System » Artikel » Merkmale*.
. Wechseln Sie in das Tab *Neues Merkmal*.
. Geben Sie unter *Name (intern)* einen Namen ein.
. Wählen Sie eine *Merkmalgruppe*, wenn Sie diese erstellt haben.
. Wählen Sie unter *Merkmaltyp* die Option *Auswahl*. +
→ Der Bereich *Neue Auswahl* wird geöffnet.
. Geben Sie in das Feld *Name* den Namen *B-Ware* ein.
. Wählen Sie unter *Allyouneed-Merkmal* die Option *B-Ware*.
. *Speichern* Sie die Einstellungen. +
→ Das Merkmal wird erstellt.
. Wechseln Sie in das Tab *Merkmale*.
. Klappen Sie das Merkmal auf.
. Geben Sie im Bereich *Auswahl* in das nächste Auswahlfeld den Namen *Refurbished* ein.
. *Speichern* Sie die Einstellungen.
. Wiederholen Sie die Schritte 11 und 12 für die Auswahlfelder *Verpackungsschäden* und *Demoware*.

[#800]
===  Merkmal für Versandangaben erstellen

Ebenfalls über ein Merkmal können die *Versandangaben* für einen Artikel erstellt werden. Ein Merkmal für Versandangaben zu erstellen, ist z.B. sinnvoll, wenn der Artikel per Spedition verschickt werden muss und die Lieferkosten daher von den allgemeinen Einstellungen auf Allyouneed abweichen.

[.instruction]
Merkmal für Versandangaben erstellen:

. Öffnen Sie das Menü *System » Artikel » Merkmale*.
. Wechseln Sie in das Tab *Neues Merkmal*.
. Geben Sie unter *Name (intern)* einen Namen ein.
. Wählen Sie eine *Merkmalgruppe*, wenn Sie diese erstellt haben.
. Wählen Sie unter *Merkmaltyp* die Option *Kommazahl*.
. Wählen Sie unter *Allyouneed-Merkmal* die Option *Versandkosten*.
. *Speichern* Sie die Einstellungen. +
→ Das Merkmal wird erstellt.

[NOTE]
.Fixe Versandkosten
====
Für das Merkmal *Fixe Versandkosten* geben Sie den Namen *Fixe Versandkosten* ein, wählen den Merkmaltyp *ganze Zahl* und das Allyouneed-Merkmal *Fixe Versandkosten*.
====

[#900]
===  Merkmal für Lieferart erstellen

Erstellen Sie zudem das Merkmal *Lieferart* für einen Artikel.

[.instruction]
Merkmal für Lieferart erstellen:

. Öffnen Sie das Menü *System » Artikel » Merkmale*.
. Wechseln Sie in das Tab *Neues Merkmal*.
. Geben Sie unter *Name (intern)* einen Namen ein.
. Wählen Sie eine *Merkmalgruppe*, wenn Sie diese erstellt haben.
. Wählen Sie unter *Merkmaltyp* die Option *Auswahl*. +
→ Der Bereich *Neue Auswahl* wird geöffnet.
. Geben Sie in das Feld *Name* den Namen *BULK_GOODS* ein.
. Geben Sie in das Feld *Beschreibung* die Beschreibung *Sperrgut* ein
. Wählen Sie unter *Allyouneed-Merkmal* die Option *Lieferart*.
. *Speichern* Sie die Einstellungen. +
→ Das Merkmal wird erstellt.
. Wechseln Sie in das Tab *Merkmale*.
. Klappen Sie das Merkmal auf.
. Geben Sie im Bereich *Auswahl* in das nächste Auswahlfeld den Namen *FORWARDING_AGENCY* ein.
. Geben Sie die Beschreibung *Speditionsware* ein.
. *Speichern* Sie die Einstellungen.
. Wiederholen Sie die Schritte 12 bis 14 für das Auswahlfeld *BOOK_RATE* mit der Beschreibung *Büchersendung* und das Auswahlfeld *CONSIGNMENT_OF_GOODS* mit der Beschreibung *Warensendung*.

[#1000]
==  Zahlungsart aktivieren

Aktivieren Sie die *<<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsart>>**Allyouneed Payments*, wie im Folgenden beschrieben.

[.instruction]
Allyouneed-Zahlungsart aktivieren:

.  Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
.  Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
.  Öffnen Sie den Ordner *DE*.
.  Klicken Sie auf *Allyouneed Payments*. +
→ Das Tab *Einstellungen* wird geöffnet.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 5.
.  Setzen Sie ein Häkchen bei der Option *Aktiv*.
. *Speichern* Sie die Einstellungen.

.Einstellungen der Zahlungsart
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Sprache*
| Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit haben Sie die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
| Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
| Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
| Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
| Kein Lieferland wählen. +
Sie können die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
| Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
| Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
| Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben. +
Weitere Informationen finden Sie auf der Handbuchseite *<<basics/statistik#, Statistik>>*. Ein Beispiel für pauschale und prozentuale Kosten finden Sie auf der Handbuchseite *<<payment/zahlungsarten-verwalten#20, Grundeinstellungen>>*.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » CRM » Kundenklassen* aktivieren oder deaktivieren Sie *erlaubte Zahlungsarten*. +
Weitere Informationen finden Sie im Kapitel *<<payment/zahlungsarten-verwalten#30, Zahlungsarten und Kundenklassen>>*.
====

Weitere Informationen finden Sie auf der Handbuchseite *<<payment/zahlungsarten-verwalten#, Zahlungsarten>>*.

[#1100]
==  Versand einrichten

Der Versand von Bestellungen über Allyouneed ist nur mit *DHL* bzw. *Deutsche Post* erlaubt. Nur mit diesen Versanddienstleistern gewährleistet Ihnen Allyouneed den vollen Zahlungsschutz. Für Speditionsware gelten Ausnahmen beim Versand.

[.instruction]
Versand für Allyouneed einrichten:

. Öffnen Sie das Menü *System » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Öffnen Sie ein Versandprofil.
. Aktivieren Sie unter *Auftragsherkunft* die Einstellung *Allyouneed*.
. Deaktivieren Sie unter *Gesperrte Zahlungsarten* die Einstellung *Allyouneed*.
. *Speichern* Sie die Einstellungen.

Nach Bearbeitung des Auftrags wird von plentymarkets der Versand bei Allyouneed bestätigt und die Paketnummer übertragen. Dabei ist wichtig, dass Sie die Paketnummer unmittelbar nach Buchung des Warenausgangs am Auftrag hinterlegen, damit sie mit der Versandbestätigung übertragen wird und der Käufer sie von Allyouneed erhalten kann.

[#1150]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID*>> im Tab *Verfügbarkeit* fügen Sie, wenn nötig, manuell marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechseln Sie in das Tab *Verfügbarkeit*.
.  Klicken Sie im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
.  Wählen Sie die Herkunft *Allyouneed.com*.
.  Geben Sie die SKU ein.
.  Klicken Sie auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#1160]
== Retouren automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Retouren automatisch an Allyouneed zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
[.instruction]
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Tragen Sie einen Namen ein.
. Wählen Sie das Ereignis gemäß Tabelle <<tabelle-ereignisaktion-retoure>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß Tabelle <<tabelle-ereignisaktion-retoure>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[tabelle-ereignisaktion-retoure]]
.Ereignisaktion zum automatischen Senden von Retouren an Allyouneed
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag > Herkunft*
|*Allyouneed*

|*Aktion*
|*Retoure > Retoure an Allyouneed senden*
|
|====

[#1170]
== Gutschriften automatisch senden

Wenn Sie eine Zahlung bereits erhalten haben und dem Kunden das Geld per Gutschrift erstatten möchten, richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Gutschriften automatisch an Allyouneed zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
[.instruction]
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Tragen Sie einen Namen ein.
. Wählen Sie das Ereignis gemäß Tabelle <<tabelle-ereignisaktion-gutschrift>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß  Tabelle <<tabelle-ereignisaktion-gutschrift>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[tabelle-ereignisaktion-gutschrift]]
.Ereignisaktion zum automatischen Senden von Gutschriften an Allyouneed
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Gutschrift*
|

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Gutschrift*

|*Filter 2*
|*Auftrag > Herkunft*
|*Allyouneed*

|*Aktion*
|*Zahlungsarten > Gutschrift an Allyouneed senden*
|
|====

[#1200]
==  FAQ

[#130]
===  Fehlermeldungen vom Typ PRODUCT_NOT_FOUND

[.collapseBox]
.Das Produkt wurde nicht gefunden. (Code: 1005) / Das Produkt konnte nicht angelegt werden. Es existiert keine Beschreibung für dieses Produkt. (Code: 1040)
--
Diese Meldungen besagen, dass Allyouneed zu dieser EAN noch keine Daten gespeichert hat und der Artikel somit nicht ohne Beschreibung erstellt werden kann. +
→ Geben Sie eine Beschreibung ein und verknüpfen Sie die Kategorien.
--

[.collapseBox]
.Das Produkt konnte nicht eindeutig zugeordnet werden. Bitte fügen Sie weitere Identifikatoren hinzu. (Code: 4026)
--
Diese Meldung besagt, dass der Artikel bereits durch mehrere Händler mit unterschiedlichen Angaben gelistet wurde. +
→ Wenden Sie sich an Allyouneed und bitten Sie darum, dass die Produkte zusammengefasst werden oder übertragen Sie Ihre Beschreibung und Kategorieverknüpfung mit. +
Eine weitere Ursache kann sein, dass Sie in plentymarkets mehrere Preissets für den Artikel erstellt haben. +
→ Sie können nur ein Preisset übertragen. Löschen Sie die weiteren Preissets in plentymarkets, entfernen Sie den Artikel auf Allyouneed und übertragen Sie den Artikel erneut.
--

[#140]
===  Fehlermeldungen vom Typ INVALID_MODIFICATION

[.collapseBox]
.Es ist nicht möglich das Produkt zu aktualisieren oder zu erstellen, auf Grund zweideutiger Identifikatoren für das Produkt. (Code: 4010)
--
Diese Meldung besagt, dass die Herstellerangaben nicht zur übertragenden EAN passen. Zum Beispiel wurde als Hersteller "Gigaset" übertragen, im Allyouneed-Katalog ist dieses aber mit "Siemens AG" gespeichert. +
→ Prüfen Sie Ihre Herstellerangaben und nehmen Sie notfalls Kontakt mit Allyouneed auf.
--

[.collapseBox]
.Ein Produkt mit identischen Herstellerangaben wurde gefunden. (Code: 4025)
--
Diese Fehlermeldung besagt, dass die Herstellerangaben falsch sind. Nehmen Sie im Zweifelsfall Kontakt mit Allyouneed auf.
--

[.collapseBox]
.Produkt 'xxx' mit AllyouneedID 'xxx' konnte nicht mit Produkt 'xxx' gematched werden. (Code: 4023)
--
Diese Fehlermeldung besagt, dass der Artikel im Allyouneed-Katalog enthalten ist und die Zuordnung hierzu fehlschlug, da das Produkt bereits mit diesem Konto gelistet ist. +
→ Löschen Sie den Artikel aus dem Allyouneed-Konto. Bei einer erneuten Übertragung sollte der Artikel problemlos gelistet werden.
--

[.collapseBox]
.Marketplace category cannot be mapped because you are not the originator of this product.
--
Diese Fehlermeldung besagt, dass der Artikel mit dieser EAN bereits im Allyouneed-Katalog enthalten, aber in einer anderen Kategorie gelistet ist. +
→ Sofern auf diese Meldung kein "PRODUCT_NOT_FOUND" folgt, ist diese Meldung eher eine Warnung, da das Produkt trotzdem gelistet wird. Allerdings nicht mit Ihrer Beschreibung, sondern der im Allyouneed-Katalog.
--

[.collapseBox]
.Diese EAN wird bereits verwendet. Sie können EANs nur mehrfach verwenden, wenn die Produkte unterschiedliche Herstellerangaben oder Variantenattribute enthalten. (Code: 4027)
--
Diese Fehlermeldung besagt, dass der Artikel bereits mit diesem Konto zu Allyouneed übertragen wurde. Jedoch stimmen die angegebenen IDs ("Eigene Produktnummer") nicht überein. +
→ Löschen Sie den Artikel aus dem Konto bei Allyouneed. Bei einer erneuten Übertragung sollte der Artikel problemlos gelistet werden.
--

[.collapseBox]
.Das Produkt xxx konnte der Variantengruppe xxx nicht zugeordnet werden, da Pflichtattributwerte nicht gefunden wurden. (Code: 5019)
--
Diese Fehlermeldung besagt, dass der Artikel bereits von einem anderen Händler mit Varianten übertragen wurde und bei Ihrem Artikel aber keine oder andere Varianten hinterlegt sind.
--

[.collapseBox]
.Die EAN kann nicht geändert werden. Sie sind nicht der Urheber des Produktes 'xxx' (mpid: xxx). (Code: 4002)
--
Diese Fehlermeldung besagt, dass der Artikel bereits mit einem Artikel aus dem Katalog von Allyouneed verknüpft wurde und daher ist eine Änderung der EAN nicht möglich. +
→ Löschen Sie den Artikel aus dem Konto bei Allyouneed oder wenden Sie sich an Allyouneed.
--

[.collapseBox]
.Not possible to update physical product. Product with the same ManufacturerName and AID found in the system.
--
Löschen Sie den Artikel aus dem Konto bei Allyouneed. Bei einer erneuten Übertragung sollte der Artikel problemlos gelistet werden.
--

[.collapseBox]
.An unknown error occurred, please contact Allyouneed support, with this xmlfile.
--
Diese Meldung besagt, dass die Attributverknüpfungen nicht stimmen. Beispielsweise wenn nur Zahlen als Werte erlaubt sind, aber auch Buchstaben angegeben wurden. Oder wenn die Kombination der Attribute nicht zusammen passt, z.B. wenn ein Attribut für "Schuhe" mit einem Attribut für Hüte kombiniert wurde.
--

[.collapseBox]
.Ungültige Variantenattribute für das Produkt 'xyz'. Bitte prüfen Sie, ob die Variantengruppe/Attributkonfiguration Ihren Produktdaten entspricht. (Code: 5008)
--
Diese Fehlermeldung besagt, dass für Allyouneed keine Attribut-Gruppe dem Attribut zugeordnet wurde. +
→ Führen Sie die unter *<<artikel/artikel-verwalten#390, Attribute verknüpfen>>* aufgeführten Schritte aus.
--

[#150]
===  Fehlermeldungen vom Typ MARKETPLACE_CATEGORY_NOT_FOUND

[.collapseBox]
.Die Marktplatz-Kategorie 'c' wurde nicht gefunden. (Code: 1003)
--
Diese Fehlermeldung besagt, dass bei der Kategorieverknüpfung ein Fehler aufgetreten ist. +
→ Überprüfen Sie, ob die eingegebene Kategorie-ID richtig ist. Wenn Sie die ID direkt eingegeben haben, handelt es sich vielleicht um einen Tippfehler.
--

[#160]
===  Fehlermeldungen vom Typ VARIANT_GROUP_NOT_FOUND

[.collapseBox]
.Die Variantengruppe 'xxx' wurde nicht gefunden. (Code: 5009)
--
Diese Fehlermeldung ist ein Folgefehler von "Das Anlegen der Variantengruppe ist fehlgeschlagen (Code: 50026)". +
→ Nehmen Sie Kontakt zu Allyouneed auf.
--

[#170]
===  Fehlermeldungen vom Typ INVALID_DATA

[.collapseBox]
.Not valid or missing required variant attribute values for DescriptionProduct with code 'xxx'. Variant group: xxx. Required attribute 'memoryCapacity'.
--
Diese Fehlermeldung besagt, dass die Attributverknüpfung fehlerhaft ist oder der Artikel bereits von einem anderen Händler mit Varianten übertragen wurde, jedoch bei Ihrem Artikel keine Varianten hinterlegt sind.
--

[.collapseBox]
.Ungültiger Preis &lt;0&gt;. Der Preis muss eine positive Dezimalzahl sein. (Code: 1015)
--
Diese Fehlermeldung besagt, dass kein Preis hinterlegt wurde. +
→ Geben Sie für den Artikel einen Preis in den Artikeldaten ein.
--

[.collapseBox]
.Duplicate variant attribute values found for physical product with code $xyz inside a variant group - code: xyz
--
Diese Fehlermeldung besagt, dass Attribut-Werte doppelt vorhanden sind oder dass mehrere Attribute eines Artikels mit unterschiedlichen und nicht kompatiblen Allyouneed-Attribut-Gruppen verknüpft wurden. +
→ Weitere Informationen zu Allyouneed-Gruppen finden Sie unter *<<artikel/artikel-verwalten#390, Attribute verknüpfen>>*.
--

[#180]
===  Fehlermeldungen vom Typ plenty

[.collapseBox]
.missing "marketplaceCategory"
--
Diese Fehlermeldung besagt, dass weder eine EAN noch eine Beschreibung/Kategorieverknüpfung vorhanden ist, mit der der Artikel gelistet werden kann. +
→ Geben Sie eine EAN und Beschreibung in den Artikeldaten ein und verknüpfen Sie die Kategorien.
--

[.collapseBox]
.missing "name"
--
Diese Fehlermeldung besagt, dass der Artikel keinen Namen hat. +
→ Geben Sie einen Namen in den Artikeldaten ein.
--

[.collapseBox]
.missing "productId"
--
Diese Fehlermeldung besagt, dass eine ID fehlt. +
→ Wenden Sie sich an plentymarkets.
--

[.collapseBox]
.missing "attribute group code"
--
Diese Fehlermeldung besagt, dass für Allyouneed keine Attribut-Gruppe dem Attribut zugeordnet wurde. +
→ Führen Sie die unter *<<artikel/artikel-verwalten#390, Attribute verknüpfen>>* aufgeführten Schritte aus.
--
