////
==== Vollständige Retoure: Alle Artikel eines Auftrags zurücknehmen

[.instruction]
Alle Artikel eines Auftrags zurücknehmen:

. Tippen Sie im Menü *POS* auf *Retoure*. +
→ Die Retourenansicht wird geöffnet.
. Tippen Sie auf *Auftrag suchen*. +
→ Die Auftragssuche wird geöffnet.
. Geben Sie in das Feld *Externe Auftragsnummer* die Belegnummer ein.
. Tippen Sie auf *Suchen*. +
→ Die Auftragsdaten werden angezeigt.
. Prüfen Sie, dass Sie alle Auftragspositionen tatsächlich erhalten haben.
. Streichen Sie auf dem Kassenbeleg die zurückgegebenen Artikel durch.
. Tippen Sie auf *Retoure erstellen*. +
→ Im plentymarkets Backend wird eine Retoure erstellt und mit dem Hauptauftrag verknüpft. +
→ Im plentymarkets Backend wird eine Gutschrift erstellt und mit dem Hauptauftrag verknüpft.
. Zahlen Sie den Retourenbetrag aus.


==== Teilretoure: Retourenartikel scannen

[.instruction]
Teilretoure, Retourenartikel scannen:

. Tippen Sie im Menü *POS* auf *Retoure*. +
→ Die Retourenansicht wird geöffnet.
. Tippen Sie auf *Auftrag suchen*. +
→ Die Auftragssuche wird geöffnet.
. Geben Sie in das Feld *Externe Auftragsnummer* die Belegnummer ein.
. Tippen Sie auf *Suchen*. +
→ Die Auftragsdaten werden angezeigt. +
→ Alle Auftragspositionen des Auftrags werden für die Retoure vorgemerkt.
. Scannen Sie den Barcode der Artikel, die die Kundin zurückgeben möchte. +
*_Hinweis:_* Sobald Sie einen Artikel scannen, werden alle anderen Artikel aus der Retoure entfernt. Der gescannte Artikel wird mit der Menge *1* zur Retoure hinzugefügt. Jeder Artikel, der zurückgegeben werden soll, muss also einzeln gescannt werden.
. Streichen Sie auf dem Kassenbeleg die zurückgegebenen Artikel durch.
. Tippen Sie auf *Retoure erstellen*. +
→ Im plentymarkets Backend wird eine Retoure erstellt und mit dem Hauptauftrag verknüpft. +
→ Im plentymarkets Backend wird eine Gutschrift erstellt und mit dem Hauptauftrag verknüpft.
. Zahlen Sie den Retourenbetrag aus.

==== Teilretoure: Retourenartikel manuell wählen

Wenn Sie im Bereich *Retoure* einen Auftrag öffnen, werden alle Auftragspositionen des Auftrags für die Retoure vorgemerkt. Sie müssen also die Auftragspositionen aus der Retoure entfernen, die die Kundin nicht zurückgeben möchte.

[.instruction]
Teilretoure, Retourenartikel manuell wählen:

. Tippen Sie im Menü *POS* auf *Retoure*. +
→ Die Retourenansicht wird geöffnet.
. Tippen Sie auf *Auftrag suchen*. +
→ Die Auftragssuche wird geöffnet.
. Geben Sie in das Feld *Externe Auftragsnummer* die Belegnummer ein.
. Tippen Sie auf *Suchen*. +
→ Die Auftragsdaten werden angezeigt. +
→ Alle Auftragspositionen werden für die Retoure vorgemerkt.
. Entfernen Sie die Artikel aus der Retoure, die nicht zurückgegeben werden sollen. +
  .. Um die gesamte Menge einer Auftragsposition aus der Retoure zu entfernen: +
    1. Tippen Sie auf den Papierkorb neben der Auftragsposition. +
  .. Um eine Teilmenge einer Auftragsposition aus der Retoure zu entfernen:
    1. Tippen Sie auf die Auftragsposition. +
    → Weitere Optionen werden eingeblendet.
    2. Tippen Sie auf *Menge ändern*. +
    → Das Fenster *Menge ändern* wird angezeigt.
    3. Geben Sie die Anzahl des Artikels ein, die zurückgegeben wird. +
→ Die Menge der Auftragsposition wird aktualisiert.
. Ändern Sie bei Bedarf die Menge weiterer Auftragspositionen.
. Streichen Sie auf dem Kassenbeleg die zurückgegebenen Artikel durch.
. Tippen Sie auf *Retoure erstellen*.  +
→ Im plentymarkets Backend wird eine Retoure erstellt und mit dem Hauptauftrag verknüpft. +
→ Im plentymarkets Backend wird eine Gutschrift erstellt und mit dem Hauptauftrag verknüpft.
. Zahlen Sie den Retourenbetrag aus.
////
