= Entwurf CDN
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:position:

//Ersetzt das bisherige Kapitel "Artikelbilder verwalten" auf der Seite "Artikel verwalten"

[#660]
== Artikelbilder verwalten

Artikelbilder werden auf S3 gespeichert und über den CDN-Service CloudFront von AWS ausgeliefert. CDN steht für Content Delivery Network und ermöglicht eine komplett skalierbare Auslieferung der Artikelbilder. Dank CDN wird nun nur das Originalbild gespeichert. Erst wenn das Bild aufgerufen wird, wird es in den definierten Dimensionen erstellt und im CDN-Cache von CloudFront gespeichert.

Erfahren Sie, welche Einstellungen Sie für Ihre Artikelbilder vornehmen können und wie Sie Bilder per FTP hochladen.

[#670]
=== Artikelbilder einrichten

Im Menü *System » Artikel » Bilder » Einstellungen* nehmen Sie die folgenden Einstellungen für Artikelbilder vor:

* Import und Export
* Platzhalterbilder
* Größe von Attributbildern
* Bildnamen

[.instruction]
Einstellungen für Artikelbilder vornehmen:

. Öffnen Sie das Menü *System » Artikel » Bilder » Einstellungen*.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-bildeinstellungen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-bildeinstellungen]]
.Bildeinstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Einstellungen*

|*Exportiere Artikelbild-Position*
|Positionsnummer des Artikelbildes für den Bildexport wählen, z.B. für den Export zu einem Marktplatz. +
Die Position wird im Tab <<artikel/artikel-verwalten#90, Bilder>> des Artikels eingestellt.

|*Import von Bildern per FTP*
|Wählen, ob importierte Bilder ergänzt werden sollen (Grundeinstellung) oder ob vorhandene Bilder vor dem Import der neuen Bilder gelöscht werden sollen.

|*Bildernamen des FTP-Imports*
|Wählen, ob die Dateinamen von per FTP-Server importierten Bilder die *Artikel-ID* oder die *Varianten-Nr.* enthalten. Weitere Informationen finden Sie im Kapitel <<artikel/artikel-verwalten#680, Artikelbilder per FTP-Server importieren>>.

|*Platzhalterbild-URL*
|URL für ein Platzhalterbild eingeben. Das Platzhalterbild wird angezeigt, wenn Artikelbilder nicht angezeigt werden können. Platzhalterbild in der <<omni-channel/online-shop/webshop-einrichten/cms#bilder-galerie, Bildergalerie>> hochladen.

|*Platzhaltervorschaubild-URL*
|URL für ein Platzhalterbild für Vorschaubilder eingeben. Das Platzhalterbild wird angezeigt, wenn Vorschaubilder nicht angezeigt werden können. Platzhalterbild in der <<omni-channel/online-shop/webshop-einrichten/cms#bilder-galerie, Bildergalerie>> hochladen.

2+|*Attributbilder*

|*Max. Höhe in Pixeln*
|Maximale Höhe in Pixeln für Attributbilder eingeben. Standardmäßig ist der Wert *40* eingestellt.

|*Max. Breite in Pixeln*
|Maximale Breite in Pixeln für Attributbilder eingeben. Standardmäßig ist der Wert *40* eingestellt.

2+|Name

|*Originalname*; +
*Artikel-ID*; +
*Artikel-Nr.*; +
*Name 1* - *Name 3*; +
*Keywords*; +
*Model*; +
*Freitextfeld 1* - *Freitextfeld 20*; +
*Eigenes Präfix*
|Parameter wählen, die im Namen des Bildes enthalten sein sollen und die Position festlegen, an der der Parameter im Namen geführt wird. Parameter werden im Bildnamen durch Bindestriche getrennt. Die Angabe der *Artikel-ID* oder der *Artikelnummer* ist Pflicht. Der Bildname ist auf eine Länge von 32 Zeichen beschränkt.

|*Präfix*
|Ein eigenes Präfix eingeben, das in Bildnamen eingefügt wird. +
*_Hinweis:_* Das eingegebene Präfix wird nur in den Bildnamen eingefügt, wenn in der Dropdown-Liste *Präfix* eine Position gewählt wurde.
|====

[#670b]
=== Größe von Artikelbildern festlegen

Im Menü *System » Artikel » Bilder » Größen* nehmen Sie Einstellungen für jede Bildgröße fest.

* *preview* = Vorschaubild
* *secondPreview* = Zweites Vorschaubild
* *middle* = Mittlere Bildgröße
* *full* = Volle Bildgröße

[.instruction]
Größe von Artikelbildern festlegen:

. Öffnen Sie das Menü *System » Artikel » Bilder » Größen*.
. Nehmen Sie für jede Bildgröße die Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-bildgroessen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-bildgroessen]]
.Bildgrößen festlegen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Bezeichnung*
|Interne Bezeichnung eingeben, die für diese Größe verwendet wird.

|*Ordnername*
|Der Ordnername für diese Bildgröße. Der Ordnername ist nicht änderbar und ist Bestandteil der URL des Artikelbilds.

|*Höhe in Pixeln*
|Höhe in Pixeln eingeben, in der Bilder dieser Größe ausgeliefert werden.

|*Breite in Pixeln*
|Breite in Pixeln eingeben, in der Bilder dieser Größe ausgeliefert werden.

|*Max. Cache-Lebensdauer in Tagen*
|Anzahl der Tage eingeben, die erstellte Bilder im CloudFront-Cache gespeichert werden. Der Zeitpunkt gilt ab dem ersten Aufruf des Bildes in dieser Größe.

|*Metadaten (EXIF, XMP, IPTC) vom Orginalbild übernehmen*
|Wählen, ob die Metadaten des Originalbilds übernommen werden. +
Metadaten sind z.B. Beschreibungstexte, Geodaten (GPS) und Rotation. +
Aktiviert = Für skalierte Bilder dieser Größe werden die Metadaten des Originalbilds übernommen. +
*_Tipp:_* Besonders für Vorschaubilder kann es sinnvoll sein, die Metadaten nicht mit auszuliefern, um Ladezeit und Datenvolumen zu optimieren.

|*Nicht vergrößern*
|Wählen, ob Originalbilder vergrößert werden. +
Aktiviert = Wenn das Originalbild kleiner ist als die für diese Größe definierten Dimensionen, wird das Bild auf diese Größe skaliert.

2+|JPG

|*Qualität in Prozent*
|Die Komprimierung von Originalbildern im JPG-Format in Prozent eingeben. Eine Komprimierung verringert die Ladezeiten und trägt zu besseren Pagespeed-Werten bei. +
*_Tipp:_* Eine Komprimierung von 80&#160;% führt in der Regel zu keinem sichtbaren Qualitätsverlust.

|*Progressiv*
|Wählen, ob Bilder dieser Größe bei Aufruf der Seite sofort angezeigt werden. +
Aktiviert = Beim Aufruf der Seite ist das Bild sofort in geringer Auflösung verfügbar. Die Qualität des Bildes wird während des Seitenaufbaus nach und nach verbessert.

2+|PNG

|*Komprimierungslevel (0-9)*
|Komprimierungslevel für PNG-Dateien wählen. +
0 = Geringste Komprimierung +
9 = Höchste Komprimierung +
PNG ist ein verlustfreies Format. Deshalb werden Bilder im PNG-Format immer in derselben Qualität dargestellt. Bei einem höheren Komprimierungslevel benötigt der Browser aber mehr Zeit, um die Komprimierung des Bildes wiederherzustellen.

|*Progressiv*
|Wählen, ob Bilder dieser Größe bei Aufruf der Seite sofort angezeigt werden. +
Aktiviert = Beim Aufruf der Seite ist das Bild sofort in geringer Auflösung verfügbar. Die Qualität des Bildes wird während des Seitenaufbaus nach und nach verbessert.
|====

[NOTE]
.CDN-Cache invalidieren
====
Wenn Sie im Menü *System » Artikel » Bilder* Änderungen vornehmen, kann es sein, dass die Bilder noch immer mit den alten Einstellungen angezeigt werden, da sich die Änderungen im Cache befinden. Klicken Sie in diesem Fall auf *CDN-Cache invalidieren*, um die Änderungen schneller anzuzeigen. Die Cache-Invalidierung erfolgt durch CloudFront.
Nach dem Invalidieren des Caches wird jedes Bild bzw. jede Größe beim nächsten Aufruf neu erstellt.
====

[#680]
=== Artikelbilder per FTP-Server hochladen

Jedes plentymarkets System verfügt über einen eigenen <<basics/datenaustausch/ftp-zugang#, FTP-Server>>. Auf diesem FTP-Server liegt der Ordner *upload_article_image_XXXX* (XXXX = plentyID), in den Sie Artikelbilder laden können. Der Ordner wird alle 60 Minuten auf Änderungen geprüft. Neue, korrekt benannte Bilder werden automatisch den richtigen Artikeln zugeordnet. Zum Hochladen von Dateien benötigen Sie ein FTP-Programm und Ihre FTP-Login-Daten.

[#bilder-benennen]
==== Artikelbilddateien für den FTP-Import benennen

Im Menü *System » Artikel » Bilder » Einstellungen* legen Sie über die Option *Bildernamen des FTP-Imports* fest, ob die Dateinamen von Artikelbildern die Artikel-ID oder die Varianten-Nr. enthalten. Abhängig von dieser Einstellung benennen Sie die Dateien entweder mit der Artikel-ID oder der Variantennummer.

[NOTE]
.Zulässige Zeichen für Dateinamen
====
Die Dateinamen von Bildern dürfen folgende Zeichen enthalten:

* Buchstaben (a-z, A-Z) ohne Umlaute
* Zahlen (0-9)
* Unterstriche (_)
* Bindestriche (-)

Leerzeichen und andere Sonderzeichen sind nicht zulässig. Beim Hochladen der Bilddatei werden Leerzeichen und Sonderzeichen durch Bindestriche (-) ersetzt.
====

Wenn Sie mehrere Bilder pro Artikel hochladen möchten, nummerieren Sie die Dateien über ein Suffix durch. Dabei muss die Bildnummer der Artikel-ID bzw. Varianten-Nr. mit drei Bindestrichen, also mit *---*, nachgestellt werden. Pro Artikel sind bis zu 100 Bilder bei einer Nummerierung von 0 bis 99 möglich.

[.instruction]
Beispiel:

Sie möchten Bilder für einen Artikel mit der Artikel-ID 4562 und der Variantennummer AQ3957 hochladen.

.Beispiele für FTP-konforme Benennung von Artikelbildern
[cols="a,a,a"]
|====
|Einstellung |Benennung 1 Bild pro Artikel |Benennung &gt; 1 Bild pro Artikel

|*Bildernamen des FTP-Imports* = *Artikel-ID*
a|
* 4562.jpg
* 4562.png
* 4562.gif
* 4562.svg

a|
* 4652---0.jpg
* 4652---1.jpg
* 4652---2.gif

|*Bildernamen des FTP-Imports* = *Varianten-Nr.*
a|
* AQ3957.jpg
* AQ3957.png
* AQ3957.gif
* AQ3957.svg

a|
* AQ3957---0.png
* AQ3957---19.png

|====

[#685]
==== Artikelbilder per FTP-Server importieren

Gehen Sie wie hier beschrieben vor, um Artikelbilder per FTP-Server zu importieren.

[.instruction]
Artikelbilder per FTP importieren:

. Kopieren Sie die Artikelbilder, die Sie hochladen möchten, in einen Ordner auf Ihrer Festplatte.
. Prüfen Sie die <<bilder-benennen, Namen der Bildateien>>.
. Passen Sie die Namen der Bilddateien wenn nötig an.
. Wählen Sie in Ihrem FTP-Programm den Zielordner *upload_article_image_XXXX* (XXXX = plentyID).
. Wählen Sie im Bereich *Upload* des FTP-Programms die Dateien.
. Starten Sie den Upload. +
→ Die Bilder werden den Artikeln zugeordnet und nach maximal 60 Minuten im Webshop angezeigt.

[TIP]
.Upload-Zeit berücksichtigen
====
Pro Durchlauf werden 200 Bilder bzw. bei eigenem Server 2000 Bilder verarbeitet. Daher kann der Upload je nach Datenmenge bis zu mehrere Stunden dauern, auch wenn Sie über einen leistungsfähigen Rechner und eine schnelle Datenverbindung verfügen. Planen Sie daher den Dateien-Upload so, dass Sie dadurch nicht in Ihrem Tagesgeschäft eingeschränkt werden.
====
