== Inventur über die plentymarkets App durchführen

Eine Inventur der Ware kann auch über die plentymarkets App durchgeführt werden. Voraussetzung ist, dass der Anwender die Berechtigung für die Inventur hat.

[TIP]
.Hardware für plentymarkets App
====
Hardware-Empfehlungen für Inventuren über die plentymarkets App finden Sie auf der Handbuchseite **<<erste-schritte/systemvoraussetzungen#_warenbestand_mit_der_plentymarkets_app_verwalten, Systemvoraussetzungen>>**.
====

=== Berechtigungen für Inventur erteilen

Anwender mit Admin-Rechten haben standardmäßig die Berechtigungen, um Inventuren über die App vorzunehmen. Benutzern der Benutzerklasse **Variabel** und **Logistik** müssen Sie diese Berechtigungen erteilen.

[.instruction]
Benutzern Berechtigungen für die Inventur erteilen:

. Öffnen Sie das Menü **System » Einstellungen » Benutzer**.
. Öffnen Sie das Konto des Benutzers.
. Wechseln Sie in das Tab **Berechtigung**.
. Öffnen Sie das Tab **Mobile**.
. Aktivieren Sie im Bereich **Sichtbare Funktionen** die Berechtigung **Inventur**.
. **Speichern** Sie die Einstellungen.

=== Inventur über die plentymarkets App personalisieren

In der plentymarkets App können Benutzer weitere Einstellungen vornehmen, um den Inventurvorgang zu personalisieren.

[.instruction]
Inventur über die plentymarkets App personalisieren:

. Melden Sie sich bei der plentymarkets App an.
. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **Einstellungen**.
. Tippen Sie auf **Inventur**. +
→ Das Einstellungsmenü **Inventur** wird angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie Tabelle xxx. +
**__Tipp:__** Die Einstellungen werden gespeichert, wenn Sie das Menü verlassen.

.Inventur; App-Einstellungen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Lagerortsuche

|**Fokus auf Barcode setzen**
|Aktivieren, um in der Lagerortsuche den Fokus in das Feld **Barcode** zu setzen. Bei gelabelten Lagerorten können Benutzer mit Bluetooth-Scannern direkt das Lagerort-Label scannen.

2+|Artikelsuche

|**Fokus auf Barcode setzen**
|Aktivieren, um in der Artikelsuche den Fokus in das Feld **Barcode** zu setzen. Bei gelabelten Lagerorten können Benutzer mit Bluetooth-Scannern direkt das Artikel-Label scannen.

|**Inkrementelles Scannen**
|Wählen, ob die Menge per Scan oder über das Tastenfeld erfasst wird. +
Aktiviert = Jeder Artikel muss einzeln gescannt werden.
Deaktiviert = Nachdem ein Artikel gescannt wird, gibt der Benutzer die gezählte Menge über das Tastenfeld ein.
|====

=== Inventur über die plentymarkets App durchführen

[TIP]
.Lagerorte labeln
====
Noch schneller geht die Inventur, wenn Sie Ihre **<<warenwirtschaft/lager-einrichten#800, Lagerorte labeln>>**. Bei der Inventur scannen Sie dann einfach die Labels des Lagerorts.
====

[.instruction]
Jeden Artikel einzeln scannen:

. Öffnen Sie die plentymarkets App.
. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **Inventur**. +
→ Die Ansicht **Inventur** wird angezeigt.
. Scannen Sie das Label des Lagerorts. +
→ Der Lagerort wird ermittelt. Erfasste Artikel werden auf diesen Lagerort gebucht.
. Scannen Sie das Label jedes einzelnen Artikels, bis Sie alle Artikel des Lagerorts erfasst haben.
**__Tipp:__** Wenn Sie verschiedene Artikel an einem Lagerort lagern, wird beim Scannen automatisch die Menge des korrekten Artikels erhöht.
**__Hinweis:__** Um die gescannte Menge manuell zu korrigieren, tippen Sie auf den Artikel und geben Sie die korrekte Menge ein.
. Um die Zählung abzuschließen, scannen Sie das Label des Lagerorts erneut oder tippen Sie auf **Bestand speichern**. +
→ Der gezählte Bestand wird gespeichert. +
→ Der gezählte Bestand wird im Menü **Waren » Lagerort-Verwaltung** des plentymarkets Backend angezeigt. +
→ Der Bestand wird im Menü **Artikel » Artikel verwalten** an der Variante gespeichert.




[.instruction]
Gezählte Menge eingeben:

. Öffnen Sie die plentymarkets App.
. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **Inventur**. +
→ Die Ansicht **Inventur** wird angezeigt.
. Scannen Sie das Label des Lagerorts. +
→ Der Lagerort wird ermittelt. Erfasste Artikel werden auf diesen Lagerort gebucht.
. Scannen Sie das Label des Artikels.





. Tippen Sie auf das Häkchen.
**__Tipp:__** Sie können die Menge auch manuell korrigieren, wenn Sie jeden Artikel einzeln scannen. Tippen Sie auf den Artikel und geben Sie die korrekte Menge ein.
. Geben Sie die gezählte Menge für den Artikel ein.
→ Der gezählte Bestand wird erfasst.
