= Entwurf_Kathrin_Item
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

== Rundungsverhalten bei Preisen in Aufträgen einstellen

Beträge werden auf mit plentymarkets POS generierten Kassenbons grundsätzlich mit 2 Nachkommastellen dargestellt. Über die Einstellungen im plentymarkets Backend steuern Sie, ob die Preise in den Aufträge auch im Hintergrund auf 2 Nachkommastellen gerundet oder ob mit 4 Nachkommastellen gearbeitet werden soll. Es gibt drei verschiedene Rundungseinstellungen:

* 2 Nachkommastellen
* 4 Nachkommastellen, Einzelpreise runden
* 4 Nachkommastellen, nur Gesamtpreise runden

Abhängig davon, ob im Hintergrund mit 2 oder 4 Nachkommastellen gerechnet wird, kommt es zu unterschiedlichen Zwischen- und Endbeträgen, wenn Beträge bei der Berechnung gerundet werden müssen. Detaillierte Informationen und Rechnungsbeispiele zum Rundungsverhalten finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/buchhaltung#, **Buchhaltung**>>.

[NOTE]
.Title
====
Für das Rundungsverhalten bei Aufträgen, die über plentymarkets POS generiert werden, ist außerdem relevant, welche Einstellung Sie für die Option **Identische Auftragspositionen** des Menüs **Einstellungen » Mandant (Shop) » Standard » POS » Tab: Beleg** der Kasse wählen. Wenn Sie für die Option **Identische Auftragspositionen** die Einstellung **Zusammenfassen** wählen, empfehlen wir, nach 2 Nachkommastellen zu runden, da es sonst zu erheblichen Abweichungen bei der Addition der Einzelpreise kommt.
====

