= Entwurf_Client
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

//  p><a href="plentymarkets://12263/item/" target="_blank">plentymarkets://12263/item/</a></p
Hier finden Sie Infos zu tollen Sachen, die Sie in plenty machen können.

//  p>SEITE plentymarkets Client</p
== plentymarkets Client

Der plentymarkets Client ermöglicht die optimale Verknüpfung von plentymarkets mit lokal installierten Endgeräten. Sie können z.B. Drucker direkt mit dem System verbinden und haben somit über nur eine Software Zugriff auf alle Funktionen und müssen nicht zwischen unterschiedlichen Programmen wechseln. Der Client ermöglicht darüber hinaus die Konfiguration von Prozessen, mit denen Sie detaillierte Abläufe Ihres Unternehmens automatisieren.

Der plentymarkets Client wird nicht in das plentymarkets System integriert, sondern als Software auf Ihrem Rechner installiert. Einen Link zum Download des plentymarket Client finden Sie auf unserer link:https://www.plentymarkets.eu/software/downloads/plentymarkets-client/[**Website**].

Der plentymarkets Client wird kontinuierlich weiterentwickelt. Der Client prüft beim Start automatisch, ob Updates verfügbar sind.

Erfahren Sie mehr über den plentymarkets-Client im folgenden Videotutorial:

video::84490424[vimeo]
=== Systemvoraussetzungen Mac OS

Voraussetzungen für die Installation und den Betrieb des plentymarkets Client unter Mac OS:

* Internetverbindung
* plentymarkets System Version 5.000 oder höher
* Mac OS X 10.9 und höhere Versionen
* Java VM, 32-Bit-Version

=== Systemvoraussetzungen Windows

Voraussetzungen für die Installation und den Betrieb des plentymarkets Client unter Windows:

* Internetverbindung
* plentymarkets System Version 5.000 oder höher
* Windows 7 oder Windows 8, 32- oder 64-Bit
* Java VM, 32-Bit-Version

Führen Sie die Installation als Administrator aus. Klicken Sie dazu mit der rechten Maustaste auf die exe-Datei und wählen Sie die Option **Als Administrator ausführen**.

==== Windows 32 Bit bzw. ältere Systeme

Für die Installation unter Windows 32 Bit bzw. ältere Systeme werden außerdem folgende Erweiterungen (Packages) benötigt:

* **link:http://www.microsoft.com/de-de/download/details.aspx?id=30653[Microsoft.Net Framework 4.5^]**
* Microsoft Visual C++ 2010 Redistributable Package **link:http://www.microsoft.com/de-de/download/details.aspx?id=5555[32-Bit-Version^]**
* Microsoft Visual C++ 2010 Redistributable Package **link:http://www.microsoft.com/de-de/download/details.aspx?id=14632[64-Bit-Version^]**

Prüfen Sie in Ihrem Windows-Betriebssystem im Menü **Systemsteuerung » Programme » Programme und Funktionen** (Windows 7), ob diese Erweiterungen installiert sind. Wenn diese Erweiterungen nicht installiert sind, laden Sie sie über die oben bereitgestellten Links herunter und installieren Sie sie, bevor Sie den plentymarkets Client installieren.

==== Troubleshooting: Programmverknüpfung unter Windows

Bei der Installation des plentymarkets Client unter Windows kann es vorkommen, dass die automatisch angelegte Verknüpfung nicht funktioniert. Der plentymarkets Client wird dann nicht gestartet. Wird der plentymarkets Client über die Verknüpfung nicht gestartet, löschen Sie die alte Verknüpfung und legen Sie eine neue Verknüpfung an.

[.instruction]
Verknüpfung löschen:

. Öffnen Sie das Windows-Startmenü.
. Klicken Sie mit der rechten Maustaste auf den plentymarkets Client.
. Wählen Sie **Aus Liste entfernen** aus dem Kontextmenü. +
→ Die Verknüpfung wird gelöscht.

[.instruction]
Neue Verknüpfung erstellen:

. Öffnen Sie das Menü, in der sich die Anwendungsdatei zum Start des Clients befindet, z.B. C:/Programme/plentymarkets.
. Klicken Sie mit der rechten Maustaste auf die Anwendungsdatei.
. Wählen Sie **Verknüpfung erstellen** aus dem Kontextmenü. +
→ Eine Verknüpfung auf dem Desktop Ihres Rechners wird erstellt.
. Ziehen Sie die Verknüpfung ggf. auf **Start**, um den plentymarkets Client über **Start » plentymarkets** starten können.

=== Client mit plentymarkets verbinden

Nachdem Sie den plentymarkets Client installiert und gestartet haben, verbinden Sie den Client mit Ihrem plentymarkets System.

[.instruction]
Client mit plentymarkets verbinden:

. Öffnen Sie den plentymarkets Client.
. Klicken Sie im Login-Fenster in das Dropdown-Menü **URL**.
. Klicken Sie auf den Eintrag **Neue URL eingeben**. +
→ Das Fenster **Neue URL eingeben** wird geöffnet.
. Geben Sie die URL Ihres plentymarkets Systems ein. +
→ **https://** = Client kommuniziert verschlüsselt. +
→ **http://** = Client kommuniziert unverschlüsselt.
. Klicken Sie auf **Speichern**.
. Geben Sie den **Benutzernamen** und das **Passwort** für das System ein.
. Klicken Sie auf **Login**.

=== Troubleshooting: Cache löschen

Im Cache des plentymarkets Client werden Daten zwischengespeichert, um Inhalte schneller anzuzeigen. Dies führt jedoch dazu, dass nicht immer die aktuellsten Inhalte angezeigt werden. Löschen Sie in folgenden Fällen den Cache:

* Aktuelle Inhalte werden nicht angezeigt
* Probleme beim Login-Vorgang

[.instruction]
Cache löschen

. Öffnen Sie das Menü **plentymarkets Client » Extras**.
. Klicken Sie auf **Cache leeren**. +
→ Der Cache wird gelöscht.

//  p>SEITE plentymarkets URL-Schema</p

////
h3>Link für Zugriff auf Inhalte über Client erstellen</h3>

<p>Über Links öffnen Sie Menüs oder Datensätze in Ihrem plentymarkets System direkt im Client. Der Aufbau der URL entspricht dem folgenden Muster:</p>

<ul>
<li>plentymarkets://<strong>plentyID/Bereich/ID</strong></li>
</ul>

<p>Die folgende Tabelle erläutert die Bestandteile dieses URL-Schemas.</p>

<table>
<caption>Bestandteile des URL-Schemas</caption>
<tr>
<th>URL-Bestandteil</th>
<th>Erläuterung</th>
</tr>
<tr>
<td><b>plentyID</b></td>
<td>ID des plentymarkets Systems (empfohlen)<br />
<b><i>Hinweis:</i></b> Die plentyID wird im Menü <strong>System » Einstellungen » API-Daten</strong> angezeigt.</td>
</tr>
<tr>
<td><b>Bereich</b></td>
<td>Bereich in plentymarkets (Pflicht)</td>
</tr>
<tr>
<td><b>ID</b></td>
<td>ID eines bestimmten Datensatzes (optional)</td>
</tr>
</table>

<p>Beispiel:</p>
<ul>
<li><strong>plentymarkets://1000/ticket/1234/</strong><br />
→ Der Client öffnet das Ticket 1234 des plentymarkets Systems 1000.</li>
</ul>

<p>Beachten Sie folgende Besonderheiten des URL-Schemas:</p>

<ul>
<li>Wenn in der URL keine plentyID angegeben ist, öffnet der Client das nächste dem Client bekannte System.</li>
<li>Wenn keine ID übergeben wird, wird der Menübereich geöffnet.</li>
</ul>

<p>Folgende Menüs können per URL-Schema über den Client geöffnet werden:</p>

<table>
<caption>URL-Schema zum Öffnen von Menüs</caption>
<tbody>
<tr>
<th>Bezeichnung/URL</th>
<th>Menü</th>
</tr>
<tr>
<td>category</td>
<td><b>Artikel » Kategorien</b></td>
</tr>
<tr>
<td>customer</td>
<td><b>Kunden » Kunden bearbeiten</b></td>
</tr>
<tr>
<td>item</td>
<td><b>Artikel » Artikel bearbeiten</b></td>
</tr>
<tr>
<td>order</td>
<td><b>Aufträge » Aufträge bearbeiten</b></td>
</tr>
<tr>
<td>ticket</td>
<td><b>Kunden » Ticketsystem</b></td>
</tr>
</tbody>
</table>

</p>
<h4>Login-Verhalten</h4>
<p>Bei Klick auf einen Link bei nicht geöffnetem Client wird der Client geöffnet. Der Client loggt sich direkt in das System ein.<br />
Bei Klick auf einen Link bei geöffnetem Client navigiert dieser zu dem Inhalt oder Bereich, sofern er bereits im System eingeloggt ist. Ist der Client in ein anderes System eingeloggt, öffnet sich ein neues Fenster für das System.
</p>

<p>Folgende Voraussetzung müssen erfüllt sein, damit der direkte Login per URL funktioniert:</p>

<ul>
<li>Der Benutzer hat sich schon einmal mit der aktuellen Version des Clients im System eingeloggt.</li>
<li>Der Client kennt das System.</li>
<li>Die ID der URL ist im System vorhanden.</li>
</ul>

<h4>Fallback bei unbekannter plenty-ID</h4>
<p>Bei Klick auf einen Link mit einer plenty-ID, die dem Client nicht bekannt ist, gelangen Sie zur Login-Seite dieses Systems.</p>

<p>Beispiele:</p>
<ul>
<li><strong>plentymarkets://1111/order</strong><br />
→ Das System mit der plenty-ID 1111 ist dem Client nicht bekannt, also wird die Login Seite geöffnet. Nach dem Login wird das Menü <strong>Aufträge</strong> geöffnet.</p>
<li><strong>plentymarkets://1111/order/1234</strong><br />
→ Das System mit der plenty-ID 1111 ist dem Client nicht bekannt, also wird die Login Seite geöffnet. Nach dem Login wird, falls vorhanden, der Auftrag mit der ID 1234 geöffnet.</li>
</ul
////
=================================================================================================

=================================================================================================

=================================================================================================

== Drucken mit dem plentymarkets Client

SEITE Handbuch » System » Einstellungen » Drucker Der plentymarkets Client ermöglicht die optimale Verknüpfung von plentymarkets mit lokal installierten Endgeräten. In Ihrem Netzwerk installierte Drucker richten Sie im Menü **System » Einstellungen » Drucker** des plentymarkets Client ein.

=== Drucker hinzufügen

Gehen Sie wie im Folgenden beschrieben vor, um einen Drucker hinzuzufügen.

[.instruction]
Drucker hinzufügen:

. Öffnen Sie den plentymarkets Client.
. Öffnen das Menü **System » Einstellungen » Drucker**.
. Klicken Sie auf das Kontextmenü im Menübaum. +
→ Der Button **Neuer Drucker** wird eingeblendet.
. Klicken Sie auf **Neuer Drucker**. +
→ Das Konfigurationsmenü wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle xx.
. **Speichern** Sie die Einstellungen. +
→ Der Drucker wird im Menübaum angezeigt.

.Drucker einrichten
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Testseite**
|Druckt eine Testseite zur Überprüfung der Druckereinstellungen.

|**Name**
|Druckernamen eingeben. Der Name ist frei wählbar, mehrere gleiche Drucker können also unterschiedlich benannt werden.

|**Drucker**
|Zeigt die Drucker, die lokal oder im Netzwerk verfügbar sind.

|**Drucker-Dialog**
|Wählen, ob der Drucker-Dialog vor dem Ausdrucken geöffnet werden soll. +
**öffnen**= Ausrichtung und weitere Einstellungen müssen vor jedem Druck vorgenommen werden. +
**nicht öffnen**= Ausrichtung und weitere Einstellungen werden in diesem Menü vorgenommen und für jeden Druck verwendet.

|**Papierfach** (nur Windows)
|Papierfach wählen. Die Optionen sind vom gewählten Drucker abhängig.  +
Mehrere Drucker für denselben Drucker im System anlegen, um mit verschiedenen Papierformaten zu arbeiten. +
**__Beispiel:__** Es sollen Rechnungen im DIN-A4-Format und Etiketten im DIN-A6-Format gedruckt werden. +
Dazu einen Drucker mit dem Papierformat DIN A4 und einen weiteren Drucker mit dem Papierformat DIN A6 einrichten und für beide denselben Drucker wählen.

|**Papierformat**
|Papierformat wählen. Bei Wahl eines benutzerdefinierten Papierformats (z.B. **Custom**) werden Eingabefelder für die Breite und Höhe des Druckmediums eingeblendet. Die Papierformate werden vom Drucker bereitgestellt, daher können die Bezeichnungen abweichen.  +
Wenn mehrere Formate benötigt werden, weitere Drucker einrichten und diesen Druckern die unterschiedlichen Formate zuordnen.

|**Doppelseitiger Druck**
|Derzeit vom Client nicht unterstützt.

|**Skalierung**
|Skalierung wählen.  +
**Auf Seitengröße (Proportion nicht berücksichtigen)** = Ausdruck wird auf die Gesamtgröße des Druckbereichs skaliert. Kann zu verzerrter Darstellung führen.  +
**Auf Seitengröße (Proportion berücksichtigen)** = Ausdruck wird innerhalb des Druckbereichs auf die größtmögliche Größe skaliert, bei der keine Verzerrung auftritt.  +
**Keine** = Ausdruck wird nicht skaliert.

|**Ausrichtung**
|Ausrichtung wählen, um nur in einer Ausrichtung zu drucken. Die angezeigten Optionen werden vom Drucker bereitgestellt, daher können die Bezeichnungen abweichen.  +
**portrait** = Ausrichtung im Hochformat  +
**landscape** = Ausrichtung im Querformat  +
**Automatische Seitenausrichtung** (unterhalb der weiteren Optionen) = Ausrichtung erfolgt automatisch.

|**Oben, Unten, Links, Rechts**
|Optional Abstände in mm eintragen, um die Positionierung des Inhalts auf der Seite zu bestimmen.

|**Automatische Seitenausrichtung**
|Aktivieren, um den Seiteninhalt automatisch auf der Seite auszurichten.
|====

=== Druckereinstellungen bearbeiten

Gehen Sie wie hier beschrieben vor, um die Einstellungen eines Druckers zu ändern.

[.instruction]
Druckereinstellungen bearbeiten:

. Öffnen Sie den plentymarkets Client.
. Öffnen das Menü **System » Einstellungen » Drucker**.
. Klicken Sie auf den Drucker. +
→ Das Konfigurationsmenü wird geöffnet.
. Passen Sie die Einstellungen an. Beachten Sie dazu die Erläuterungen in Tabelle xx.
. **Speichern** Sie die Einstellungen.

=== Drucker löschen

Gehen Sie wie hier beschrieben vor, um einen Drucker zu löschen.

[.instruction]
Drucker löschen:

. Öffnen Sie den plentymarkets Client.
. Öffnen das Menü **System » Einstellungen » Drucker**.
. Klicken Sie auf den Drucker. +
→ Das Konfigurationsmenü wird geöffnet.
. Klicken Sie rechts oben auf **Löschen**.
. Bestätigen Sie die Sicherheitsabfrage. +
→ Der Drucker wird aus dem Client gelöscht.

Erfahren Sie mehr über das Einrichten von Druckern im folgenden Videotutorial:

video::84490521[vimeo]
[#30]
=== Drucker freigeben

Drucker werden lokal für den Benutzer gespeichert. Sie stehen also nicht für weitere Benutzer zur Verfügung. Wenn ein Druckerprofil auch für andere Benutzer zur Verfügung stehen soll, muss das Profil freigegeben werden. Die Freigabe erfolgt auf Ihrem Rechner und nicht in plentymarkets.

Wie Sie Drucker auf Ihrem Rechner freigeben, finden Sie in der Hilfe für Ihr Betriebssystem.

* Für Windows z.B. **link:http://windows.microsoft.com/de-de/windows/share-printer#1TC=windows-7[hier^]**
* Für Mac z.B. **link:https://support.apple.com/de-de/HT4670[hier^]**

[#40]
=== Troubleshooting: Fehlerursachen beheben

Hier erhalten Sie anhand von Fehlercodes Informationen zu Fehlern, die beim Einrichten des Druckers auftreten können.

.Fehlermeldungen im Menü **Drucker**
[cols="a,a,a,a"]
|====
|Code |Fehler |Ursache |Fehler beheben

|2000
|Unter Mac OS X: Kein CUPS Drucker gefunden.
|Kein angeschlossener Drucker verfügt über eine Netzwerkfreigabe. Diese Freigabe ist für die Druckerkommunikation über CUPS erforderlich.
|<<_entwurfsseiten/kathrin/entwurf-automatisierung#30, **Drucker freigeben**>>

|2001
|Unter Mac OS X: Unbekannter CUPS Drucker.
|Unter dem angegebenen Namen konnte kein Drucker im Netzwerk gefunden werden.
|<<_entwurfsseiten/kathrin/entwurf-automatisierung#30, **Drucker freigeben**>>

|2100
|Testseite konnte nicht gedruckt werden.
|Falsche Client-Version. Benötigt wird mindestens Version 121.
|link:https://www.plentymarkets.eu/produkt/prozesse/plentymarkets-client/[**Aktuellen Client herunterladen**]

|2101
|Fehler beim Drucken.
|Verschiedene Ursachen möglich.
|

|2102
|Drucker wurde nicht gefunden.
|Der Drucker ist im System nicht mehr vorhanden. Konfiguration ggf. nicht mehr korrekt.
|Neuen Drucker hinzufügen oder anderen Drucker verwenden.
|====

[#50]
=== Etiketten drucken

Zum Drucken von Etiketten werden spezielle Etikettendrucker eingesetzt, die das schnelle Ausdrucken großer Etikettenmengen ermöglichen. Dazu sind Etikettendrucker mit Etikettenrollen und teilweise mit einer Schneidevorrichtung ausgestattet. In den Einstellungen des Client-Menüs **System » Einstellungen » Drucker** legen Sie die exakte Größe eines Etiketts fest. In den Druckereinstellungen finden Sie dazu unter der Option **Papierformat** Standardformate sowie eine benutzerdefinierte Option (z.B. **Custom**), um eigene Größen zu hinterlegen (Tabelle 1).

Die Druckfunktionen des Clients sind mit üblichen Etikettendruckern kompatibel und wurden für Etikettendruckermodelle des Herstellers link:http://www.zebra.com[**Zebra**^] optimiert. Diese Modelle sind optimal für große Etikettenmengen geeignet. Für den Einsatz als Desktop-Drucker empfehlen wir das Modell link:http://www.zebra.com/gb/en/products-services/printers/printer-type/desktop/g-series-gc.html[**Zebra GC420d**^].

[#60]
==== Zebra GC420d auf Ihrem Rechner installieren

Nachfolgend erhalten Sie Informationen zur Installation des Druckermodells Zebra GC420d unter Windows und Mac OSX.

[.instruction]
Zebra GC420d auf Ihrem Rechner installieren:

. Laden Sie die **link:http://www.zebra.com/gb/en/support-downloads/desktop/gx430t.html#mainpartabscontainer_999b=drivers[Zebra Setup Utilities^]**-Datei auf Ihren Rechner herunter.
. Installieren Sie diese Datei.
. Durchlaufen Sie den Installationsassistenten. +
→ Achten Sie unter Windows darauf, den Drucker ZDesigner GC420d zu wählen. Hier ist der Druckertreiber ZPL eingestellt. +
→ Stellen Sie für Apple-Rechner zunächst auch den Druckertreiber ZPL ein. Die Treibereinstellung muss jedoch für jede Etikettengröße einzeln getestet werden.

[#70]
==== Etiketten einrichten

Die Größe und Breite Ihrer Etiketten richten Sie im plentymarkets Client ein. Fügen Sie hierfür den Etikettendrucker zur Druckerliste hinzu. Gehen Sie dazu wie unten beschrieben vor. Beschrieben wird die Einrichtung beispielhaft für Etiketten mit einer Höhe von 150 und einer Breite von 150 cm.

[.instruction]
Drucker mit Etikett 100 x 150 hinzufügen:

. Öffnen Sie den plentymarkets Client.
. Öffnen Sie das Menü **System » Einstellungen » Drucker » Neuer Drucker**.
. Tragen Sie einen Namen ein.
. Wählen Sie im Dropdown-Menü **Drucker** den Etikettendrucker.
. Wählen Sie für den **Druckerdialog****nicht öffnen**.
. Wählen Sie für das **Papierfach** die Option **Ungültige Auswahl**.
. Wählen Sie für das **Papierformat** die Option **Custom**.
. Tragen Sie **150** als **Papierhöhe** ein.
. Tragen Sie **104** als **Papierbreite** ein.
. Lassen Sie die Option einseitig für doppelseitigen Druck.
. Wählen Sie **auf Seitengröße (Proportion nicht beachten)** für die **Skalierung**.
. Wählen Sie **Hochformat** für die **Ausrichtung**.
. **Speichern** Sie die Einstellungen.

Wenn Sie verschiedene Etikettengrößen verwenden, können Sie entweder Papierhöhe und Papierbreite beim Wechsel der Etikettengröße anpassen oder pro Etikettengröße einen eigenen Drucker anlegen.

[#80]
==== Troubleshooting: Fehlerhaften Etikettendruck korrigieren

Wenn der Druck leicht versetzt ist, der Hauptteil auf dem Label jedoch erkennbar ist, empfehlen wir Ihnen, die Ausrichtung über die Angaben **Oben**, **Links**, **Unten** und **Rechts** anzupassen.

Wenn nur ein kleiner Teil der Angaben auf dem Etikett gedruckt wird oder Ihr Etikett komplett leer bleibt, passen Sie den Druckertreiber an. Insbesondere auf Apple-Rechnern hängt der korrekte Druck häufig vom Treiber ab, aber auch bei Windows-Computern kann dies die Fehlerursache sein.  +
Für Windows empfehlen wir Ihnen, den Drucker ZDesigner GC420d mit dem Treiber ZPL zu installieren. In einigen Fällen kann aber der ZDesigner GC420d (EPL) mit dem Druckertreiber EPL bessere Druckergebnisse liefern.

Wenn das Etikett wieder korrekt gedruckt wird, legen Sie sich einen Drucker mit den korrekten Einstellungen für das Etikett an, so dass Sie die Einstellungen wiederverwenden können. Wir empfehlen dazu, den Drucker mehrfach mit verschiedenen Treibern auf Ihrem Rechner zu installieren, denn so können Sie, wenn ein Etikett nicht korrekt gedruckt wird, den Druck schnell mit einem anderen Treiber noch einmal versuchen.

Eine weitere Ursache für einen fehlerhaften Druck kann sein, dass der Prozess statt auf die Etiketteneinstellungen in plentymarkets auf die Etikettenparameter Ihres Druckers zugreift. Tragen Sie eventuell Etikettenparameter in Ihren Druckereinstellungen nach.

[#90]
=== Druckverlauf anzeigen

Im Druckverlauf werden Ihre Druckaufträge der letzten Tage und Wochen angezeigt. Die Anzahl der angezeigten Druckaufträge beträgt maximal 10.000. Wenn diese Zahl überschritten wird, werden die ältesten 100 Einträge aus dem Verlauf entfernt. Die Druckaufträge werden zwischengespeichert, um sie an den Drucker weiterzuleiten. Sobald der Druckauftrag zwischengespeichert wurde, wird der Druck im Druckverlauf aufgeführt. Wenn z.B. Papier fehlt oder andere Probleme mit dem Drucker auftreten, kann es also sein, dass Druckaufträge im Verlauf stehen, die nicht gedruckt wurden.

[.instruction]
Druckverlauf anzeigen:

. Öffnen Sie den plentymarkets Client.
. Öffnen Sie das Menü **Extras**.
. Klicken Sie auf **Druckverlauf öffnen**. +
→ Der Druckverlauf wird geöffnet.

Im Druckverlauf haben Sie die Möglichkeit, Dokumente erneut zu drucken oder Druckaufträge aus dem Verlauf zu löschen. Beim Öffnen des Verlaufs werden standardmäßig 20 Einträge pro Seite angezeigt. Sie können aber auch 50 oder 100 Einträge pro Seite anzeigen lassen. Markieren Sie die Druckaufträge, um sie zu löschen oder erneut zu drucken. Es können alle Aufträge einer Seite oder einzelne Aufträge gewählt werden.

