= migrationsleitfaden-shopware
:lang: de
include::{includedir}/_header.adoc[]
:position: 45

== XXX

=== Externe Shops prüfen

In plentymarkets 6 wurden für die Shopware-Integration externe Shops bereitgestellt. In plentymarkets 7 wird diese Anbindung an Shopware jedoch über reguläre Mandanten (Shops) realisiert. Bei der Migration auf plentymarkets 7 werden externe Shops daher in vollwertige Mandanten (Shops) umwandelt. Diese Mandanten können über den plentymarkets Connector an Shopware angebunden werden. Beachten Sie jedoch, dass vollwertige Mandanten kostenpflichtig sind. Prüfen Sie daher vor der Migration, ob in Ihrem System externe Shops vorhanden sind. Externe Shops, die Sie nicht mehr benötigen, sollten Sie vor der Migration löschen.

[TIP]
.Externe Shops ohne Shopware-Anbindung
====
Technisch war es in plentymarkets 6 möglich, externe Shops für andere Zwecke als für die Anbindung an Shopware zu nutzen. Prüfen Sie daher auch, ob externe Shops in Ihrem System vorhanden sind, wenn Sie den Shopware Connector nicht verwenden. Diese Prüfung ist vor allem wichtig, wenn Sie die externen Mandanten nicht für die Anbindung von Shopware, sondern für andere Anwendungsfälle verwenden, z.B. für Marktplatzverfügbarkeiten, Nummernkreise oder Rechnungsstellung.
====

////
ul>
<li>Prüfen Sie, ob externe Shops in ihrem System vorhanden sind.</li>
<li>Prüfen Sie, ob Sie die externen Shops benötigen, die in ihrem System angelegt sind.</li>
<li>Prüfen Sie, ob Sie für diese Zwecke einen vollwertigen eigenen Mandanten benötigen oder ob Sie die Basisfunktionen von plentymarkets dafür nutzen können.</li>
<li>Löschen Sie externe Shops, die Sie nicht mehr benötigen.</li>
<li>Externe Shops, die Sie weiter nutzen möchten, werden automatisch migriert. Es besteht erst Handlungsbedarf, wenn Sie Drittsysteme oder andere Funktionen über den Mandanten nutzen möchten.</li>
</ul
////
==== System auf externe Shops prüfen

Externe Shops haben den Webstore-Typ **shopware** oder **extern** und haben außerdem keine eigene plenty ID. Gehen Sie wie unten beschreiben vor, um zu prüfen, ob externe Shops in Ihrem System vorhanden sind:

. Öffnen Sie das Menü **System » Mandant**.
. Klicken Sie auf das Plus des ersten Mandanten (Shops). +
→ Das Mandantenmenü wird eingeblendet.
. Öffnen Sie das Menü **System » Mandant » Mandant öffnen » Grundeinstellungen** des Mandanten.
. Prüfen Sie den **Webstore-Typ**. +
→ Shops des Typs **shopware** oder **extern** sind externe Shops. +
**__Tipp:__** Bei externen Shops ist außerdem die Option **plenty ID** leer. +
→ Wenn es sich um einen externen Shop handelt, prüfen Sie, ob er aktiv verwendet wird. +
→ Löschen Sie den externen Shop, wenn Sie ihn nicht benötigen.
. Prüfen Sie alle weiteren in Ihrem System angelegten Mandanten (Shops) auf dieselbe Weise.

==== Nicht benötigte externe Shops löschen

Gehen Sie wie unten beschrieben vor, um nicht mehr benötigte externe Shops vor der Migration zu löschen.

. Öffnen Sie das Menü **System » Mandant**.
. Zeigen Sie mit der Maus auf den externen Shop, den Sie löschen möchten. +
→ Ein Pfeil nach unten wird eingeblendet.
. Klicken Sie auf den Pfeil, um das Kontextmenü zu öffnen.
. Klicken Sie im Kontextmenü auf **Löschen**. +
→ Eine Sicherheitsabfrage wird geöffnet.
. Klicken Sie in der Sicherheitsabfrage auf **Löschen**. +
→ Der externe Shop wird gelöscht.

==== plentymarkets an Shopware anbinden

Bei der Migration Ihres Systems zu plentymarkets 7 werden die Daten Ihrer externen Shops in vollwertige Mandanten (Shops) überführt. Die Integration Ihres externen Shopware-Systems mit dem link:https://github.com/plentymarkets/plentymarkets-shopware-connector/releases[**plentyConnector**^] nehmen Sie nach der Migration vor. Informationen dazu finden Sie in der link:https://docs.google.com/document/d/1yPr_SrBshsT0IJSuI8DmA7Berr275ZY6qDMMiqavbQI/edit[**Dokumentation**^].

