== Inventur über die plentymarkets App durchführen

Eine Inventur der Ware kann über die plentymarkets App durchgeführt werden. Voraussetzung ist, dass der Benutzer die Berechtigung für die Inventur hat. Benutzer benötigen außerdem ein mobiles Gerät mit Bluetooth-Scanner.

[TIP]
.Hardware für plentymarkets App
====
Hardware-Empfehlungen für Inventuren mit der plentymarkets App finden Sie auf der Handbuchseite *<<erste-schritte/systemvoraussetzungen#_warenbestand_mit_der_plentymarkets_app_verwalten, Systemvoraussetzungen>>*.
====

=== Berechtigungen für Inventur erteilen

Benutzer mit Admin-Rechten haben standardmäßig die Berechtigungen, um Inventuren über die App vorzunehmen. Benutzern der Benutzerklasse *Variabel* und *Logistik* müssen Sie diese Berechtigungen erteilen.

[.instruction]
Benutzern Berechtigungen für die Inventur erteilen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer*.
. Öffnen Sie das Konto des Benutzers.
. Wechseln Sie in das Tab *Berechtigung*.
. Öffnen Sie das Tab *Mobile*.
. Aktivieren Sie im Bereich *Sichtbare Funktionen* die Berechtigung *Inventur*.
. *Speichern* Sie die Einstellungen.

=== Inventur über die plentymarkets App personalisieren

In der plentymarkets App können Benutzer weitere Einstellungen vornehmen, um den Inventurvorgang zu personalisieren.

[.instruction]
Inventur über die plentymarkets App personalisieren:

. Melden Sie sich bei der plentymarkets App an.
. Tippen Sie in der Menüleiste auf das *Menüsymbol*.
. Tippen Sie auf *Einstellungen*.
. Tippen Sie auf *Inventur*. +
→ Das Einstellungsmenü *Inventur* wird angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie Tabelle xxx. +
*_Tipp:_* Die Einstellungen werden gespeichert, wenn Sie das Menü verlassen.

.Inventur; App-Einstellungen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Lagerortsuche

|*Fokus auf Barcode setzen*
|Aktivieren, um in der Lagerortsuche den Fokus in das Feld *Barcode* zu setzen. Bei gelabelten Lagerorten können Benutzer mit Bluetooth-Scannern direkt das Lagerort-Label scannen.

2+|Artikelsuche

|*Fokus auf Barcode setzen*
|Aktivieren, um in der Artikelsuche den Fokus in das Feld *Barcode* zu setzen. Bei gelabelten Lagerorten können Benutzer mit Bluetooth-Scannern direkt das Artikel-Label scannen.

|*Inkrementelles Scannen*
|Wählen, ob die Menge per Scan oder über das Tastenfeld erfasst wird. +
Aktiviert = Jedes Exemplar des Artikels muss einzeln gescannt werden.
Deaktiviert = Nachdem ein Artikel-Label gescannt wird, geben Benutzer die gezählte Menge über das Tastenfeld ein.
|====

=== Inventur über die plentymarkets App durchführen

[TIP]
.Lagerorte labeln
====
Noch schneller geht die Inventur, wenn Sie Ihre *<<warenwirtschaft/lager-einrichten#800, Lagerorte labeln>>*. Bei der Inventur scannen Sie dann einfach die Labels des Lagerorts.
====

==== Jedes Exemplar eines Artikels einzeln scannen

Benutzer müssen den Bestand nicht selbst zählen, sondern können die Labels jedes einzelnen Exemplars des Artikels einzeln scannen, bis alle Exemplare am Lagerplatz gescannt wurden. Die Zählung erfolgt inkrementell im Hintergrund. Für diese Art der Bestandskorrektur muss in den App-Einstellungen des Benutzers die Option *Inkrementelles Scannen* aktiviert sein.

[.instruction]
Jedes Exemplar eines Artikels einzeln scannen:

. Öffnen Sie die plentymarkets App.
. Tippen Sie in der Menüleiste auf das *Menüsymbol*.
. Tippen Sie auf *Inventur*. +
→ Die Ansicht *Inventur* wird angezeigt.
. Scannen Sie das Label des Lagerorts. +
→ Der Lagerort wird ermittelt. Erfasste Artikel werden auf diesen Lagerort gebucht.
. Scannen Sie das Label jedes einzelnen Exemplars, bis Sie alle Artikel des Lagerorts erfasst haben.
*_Tipp:_* Wenn sich verschiedene Artikel an einem Lagerort befinden, wird beim Scannen automatisch die Menge des korrekten Artikels erhöht.
*_Hinweis:_* Um die gescannte Menge manuell zu korrigieren, tippen Sie auf den Artikel und geben die korrekte Menge ein.
. Um die Zählung abzuschließen, scannen Sie das Label des Lagerorts erneut oder tippen Sie auf *Bestand speichern*. +
→ Der gezählte Bestand wird gespeichert. +
→ Der gezählte Bestand wird im Menü *Waren » Lagerort-Verwaltung* des plentymarkets Backend angezeigt. +
→ Der Bestand wird im Menü *Artikel » Artikel verwalten* an der Variante gespeichert.

==== Gezählte Stückzahl eingeben

Statt das Label jedes einzelnen Exemplars eines Artikels am Lagerplatz zu scannen, können Benutzer zählen, wie viele Exemplar eines Artikels am Lagerort vorhanden sind, und das Zählergebnis eingeben. Für diese Art der Bestandskorrektur muss in den App-Einstellungen des Benutzers die Option *Artikel einzeln scannen* deaktiviert sein.

[.instruction]
Gezählte Menge eingeben:

. Öffnen Sie die plentymarkets App.
. Tippen Sie in der Menüleiste auf das *Menüsymbol*.
. Tippen Sie auf *Inventur*. +
→ Die Ansicht *Inventur* wird angezeigt.
. Scannen Sie das Label des Lagerorts. +
→ Der Lagerort wird ermittelt. Erfasste Artikel werden auf diesen Lagerort gebucht.
. Scannen Sie das Label eines Artikels. +
→ Das Fenster *Menge eingeben* wird angezeigt.
. Geben Sie die gezählte Menge für den Artikel ein.
. Um die Zählung abzuschließen, scannen Sie das Label des Lagerorts erneut oder tippen Sie auf *Bestand speichern*. +
→ Der gezählte Bestand wird gespeichert. +
→ Der gezählte Bestand wird im Menü *Waren » Lagerort-Verwaltung* des plentymarkets Backend angezeigt. +
→ Der Bestand wird im Menü *Artikel » Artikel verwalten* an der Variante gespeichert.
