= Entwurf_Kathrin_Beta7-Migration
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

[#200]
== Voraussetzungen für die Migration

Beachten Sie die folgenden Voraussetzungen für eine Migration Ihres Systems auf plentymarkets 7.

* **Hosting**: Ihr System muss auf AWS gehostet sein. plentymarkets 7 kann nicht auf einem eigenen Server oder der plentymarkets eigenen Cloud (Cluster) genutzt werden. +
→ Sie können Ihr System vor der Migration auf AWS <<basics/arbeiten-mit-plentymarkets/plentymarkets-konto/umzug#, **umziehen**>>, wenn die Hauptdomain bei plentymarkets gehostet ist.
* **SOAP**: Eigene SOAP-Anbindungen und SOAP-Anbindungen von Partnern oder Agenturen müssen vor der Migration auf ihre Stable 7-Tauglichkeit geprüft werden. Fragen Sie den Entwickler oder die Agentur, ob die Anbindung Stable 7-fähig ist.
* **Shopware-Connector**: plentymarkets 7 ist aktuell nicht mit externen Mandanten und dem shopware Connector kompatibel. Wenn Sie einen externen Mandanten bzw. den shopware Connector verwenden, ist daher ein Wechsel auf plentymarkets 7 aktuell nicht möglich.
* **Externe Mandanten**: plentymarkets 7 ist aktuell nicht mit externen Mandanten kompatibel. Wenn Sie einen externen Mandanten verwenden, ist daher ein Wechsel auf plentymarkets 7 aktuell nicht möglich.
* **plentymarkets Shipping**: plentymarkets Shipping ist nicht mit plentymarkets 7 kompatibel und wird nicht mehr unterstützt. Wechseln Sie auf den aktuellen link:https://www.plentymarkets.eu/software/downloads/plentymarkets-client[**plentymarkets-Client**].
* **Marktplätze**: In plentymarkets 7 sind noch nicht alle Marktplätze funktionsfähig. Prüfen Sie vor der Migration die <<basics/versionswechsel#, **Liste**>> der noch nicht migrierten Marktplätze.
* **Vorbereitungen**: Arbeiten Sie diesen Migrationsleitfaden durch und treffen Sie die darin beschriebenen Vorbereitungen.

[#210]
== Termin für Migration vereinbaren

Einen Termin für die Migration auf plentymarkets 7 vereinbaren Sie über unser Ticket-System. Gehen Sie wie unten beschrieben vor, um ein Ticket zu erstellen.

[.instruction]
Termin für Migration vereinbaren:

. Öffnen Sie das Menü **Start » Support-Ticket**.
. Klicken Sie im Bereich **Ticket** auf **Neues Ticket anlegen**.
. Geben Sie einen Titel ein, der Ihre Anfrage kurz definiert.
. Wählen Sie **Auf plentymarkets 7 wechseln** aus der Dropdown-Liste. +
→ Weitere Optionen werden eingeblendet.
. Wählen Sie das plentymarkets System aus der Dropdown-Liste, das migriert werden soll.
. Wählen Sie, ob Sie **plentymarkets 7 Stable** oder **plentymarkets 7 Beta** nutzen möchten.
. Klicken Sie auf **Anlegen**, um das Ticket zu erstellen. +
→ Das Ticket wird erstellt und ein plentymarkets Mitarbeiter wird Sie über das weitere Vorgehen informieren.

[IMPORTANT]
.Systemerreichbarkeit während der Migration
====
Während der Migration ist Ihr System nicht erreichbar. Bei kleineren Systemen dauert die Migration ca. 15 Minuten. Bei großen Systemen ist Ihr System bis zu mehrere Stunden nicht erreichbar.
====
