= Entwurf POS-plentyBase
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:position: 10

BLAHBLAHBLAH plentyBase in der App toll toll BLAHBLAHBLAH

[#970]
==== plentymarkets App mit plentyBase verbinden

Das Plugin plentyBase bietet eine Schnittstelle, über die Sie auf die Drucker eines Computers zugreifen.

* Das Plugin plentyBase muss auf dem lokalen Rechner installiert sein.
* In der plentymarkets App müssen die Verbindungsdaten des Rechners gespeichert werden, auf dem plentyBase installiert ist.
* Der Rechner, auf dem plentyBase installiert ist, muss erreichbar sein.

[#980]
===== plentyBase Daten in plentymarkets App speichern

Halten Sie die folgenden Daten bereit, um die plentyBase Verbindungsdaten in der plentymarkets App zu speichern:

* IP-Adresse des Rechners, auf dem plentyBase installiert ist
* Server-Port, der plentyBase auf dem Rechner zugewiesen wurde

Nachdem Sie die plentyBase Verbindungsdaten in der plentymarkets App gespeichert haben, können Sie:

* In der App Dokumente über alle Drucker ausdrucken, auf die über den Rechner zugegriffen werden kann, auf dem plentyBase installiert ist.
* Plugins in der App nutzen, die plentyBase benötigen, z.B. Pick-by-light oder POS-Kauf auf Rechnung

[TIP]
.Bon-Drucker
====
Der Bon-Drucker wird über die IP-Adresse an die plentymarkets App angebunden. Daher ist plentyBase für einen Bon-Drucker nicht erforderlich.
====


[.instruction]
plentyBase Verbindungsdaten in plentymarkets App speichern:

. Melden Sie sich bei der plentymarkets App an.
. Tippen Sie in der Menüleiste oben links auf das *Menüsymbol*.
. Tippen Sie auf *Einstellungen*.
. Tippen Sie auf *plentyBase*. +
→ Das Einstellungsmenü *plentyBase* wird angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie <<tabelle-App-plentyBase>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-App-plentyBase]]
.plentyBase; App-Einstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Verbindung

|*IP-Adresse*
|Die IP-Adresse des Rechners eingeben, auf dem plentyBase installiert ist. Wenn plentyBase in einem Netzwerk installiert und für andere Rechner freigegeben ist, die IP-Adresse des Host-Rechners eingeben.

|*Port*
|Den Port eingeben, der plentyBase auf dem Rechner zugeordnet wurde. Standardmäßig ist der Port 7331 angegeben. Den Port Auf das plentyBase Icon in der Taskleiste des Rechners und dann auf *Konfiguration öffnen* klicken, um den Server-Port anzuzeigen.

|*Verbindung testen*
|Tippen, um zu testen, ob eine Verbindung zum plentyBase Rechner hergestellt werden kann.

2+|Authentifizierung

|*Access-Token*
|Access-Token eingeben, der in plentyBase für den Rechner gespeichert ist.
*_Tipp:_* Der Access-Token wird im Menü *Start » plentyBase » Ansicht: Einstellungen* des plentymarkets Backend als QR-Code dargestellt. Um den QR-Code einzuscannen, oben rechts in der App auf das QR-Code-Symbol klicken und den QR-Code scannen.

|*Access-Token generieren*
|Klicken, um ein neues Access-Token zu generieren. +
*_Hinweis:_* Wenn ein Access-Token in der plentymarkets App generiert wird, muss dieses Token auch in den Einstellungen des plentyBase Tools gespeichert werden.
|====

[#990]
=== plentyBase-Drucker für Kassenbelege festlegen

Standardmäßig werden alle Kassenbelege über den Bondrucker gedruckt, den Sie in den Kasseneinstellungen des Menüs *plentymarkets App » Einstellungen » POS* festlegen. Optional können jedoch weitere Drucker an die Kasse angebunden werden. Die Anbindung erfolgt über das Plugin link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyBase^]. plentyBase stellt eine Verbindung zwischen der plentymarkets App und einem lokalen Rechner her. Die Kasse kann dann auf die Drucker zugreifen, die auch der lokale Rechner zugreifen kann. Damit die Drucker für die plentymarkets App verfügbar sind, müssen die folgenden Vorraussetzungen erfüllt sein:

* plentyBase muss auf dem Rechner installiert sein. +
→ Die Installationsdatei laden Sie im link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyMarketplace^] herunter.
* plentyBase muss auf dem Rechner korrekt konfiguriert sein. +
→ Die Konfigurationsanleitung finden Sie in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyBase^].
* plentyBase muss auf dem Rechner gestartet sein. +
→ Es wird empfohlen, plentyBase beim Starten des Rechners automatisch zu starten.
* plentyBase muss in der App korrekt konfiguriert sein. +
→ Die Konfigurationsanleitung

Gehen Sie wie unten beschrieben vor, um festzulegen, welche Kassenbelege über welchen Drucker gedruckt werden.

[.instruction]
Drucker pro Belegart festlegen:

. Öffnen Sie die plentymarkets App.
. Öffnen Sie das Menü *plentymarkets App » Einstellungen » POS*.
. Nehmen Sie im Bereich *Drucker* die Einstellungen vor. Beachten Sie <<tabelle-POS-drucker>>.
. **Speichern** Sie die Einstellungen.

[[tabelle-POS-drucker]]
.Andere Drucker für Kassenbelege festlegen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Standard-Drucker*
|In der Dropdown-Liste den Standard-Drucker für die Kasse wählen. Standardmäßig ist der Bondrucker vorausgewählt. +
*_Hinweis:_* In der Dropdown-Liste werden der Bondrucker und Drucker im Netzwerk angezeigt, auf die die Kasse Zugriff hat. Für den Zugriff auf diese weiteren Drucker ist das Plugin link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyBase^] erforderlich.

|*Kaufbeleg*; +
*Tagesabschluss*; +
*Zwischenbericht*; +
*Kassensturz*; +
*Stornierungsbeleg*; +
*Einlage und Entnahme*; +
*Gutscheinbeleg*; +
*Retourenbeleg*; +
*Gutschriftbeleg*
|In den Dropdown-Listen der Belege den Drucker wählen, auf dem der Beleg gedruckt wird. Der Standard-Drucker ist vorausgewählt. Wenn der gewählte Drucker beim Starten eines Druckvorgangs nicht verfügbar ist, wird der Beleg stattdessen auf dem Standard-Drucker gedruckt.
|====

==== Troubleshooting bei plentyBase-Druckern

Festgelegte Drucker, die nicht erreichbar sind, werden mit einem Ausrufezeichen gekennzeichnet. Wenn der Drucker eigentlich erreichbar sein sollte, prüfen Sie die folgenden



plentyBase



* Stimmen die plentyBase-Einstellungen in der App?
*

Der Drucker wurde für den Druck einer oder mehrerer Belege ausgewählt und die Einstellungen gespeichert. Der Drucker ist mit einem Dreieck gekennzeichnet und nicht erreichbar.

* Ist der Rechner an, auf dem plentyBase installiert ist?
* Ist plentyBase auf dem Rechner gestartet?
* Ist der Drucker mit dem Rechner verbunden?
* Ist der Drucker an und funktionsbereit?
* Wurde der Access Token vor Kurzem geändert?
