= Container_CheckoutOrderParamsList
:lang: en
// include::{includedir}/_header.adoc[]
:keywords: Container_CheckoutOrderParamsList
:position: 258

//  auto generated content Thu, 06 Jul 2017 00:02:17 +0200
== Short description

Returns the content of the container for selecting order properties.

== Description of this function

[source,plenty]
----

Container_CheckoutOrderParamsList( string $itemID  , string $quantity  , string $basketItemID  ) : string

----

== Template CheckoutOrderParamsList

=== CheckoutOrderParamsListBasketItem

==== Variables

These variables are available in this container.

* $CheckoutOrderParamsListBasketItemID — Contains the ID of the shopping cart item for listing the order properties.
* $CheckoutOrderParamsListBasketItemItemID — Contains the item's ID for listing the order properties.
* $CheckoutOrderParamsListBasketItemQuantity — Contains the order quantity of the shopping cart items for listing the order properties.

=== CheckoutOrderParamsListGroupItem

==== Variables

These variables are available in this container.

* $OrderParamsGroupItemID — Contains the property group's ID.
* $OrderParamsGroupItemInputName — Contains the form name for selecting the property groups. This name is relevant for groupings of the type "single selection".
* $OrderParamsGroupItemName — Contains the name of the property group.
* $OrderParamsGroupItemPosition — Contains the position of the property group.
* $OrderParamsGroupItemSelectedValues — Contains the selected values of the property group. Use this data for the groupings "Single selection" and "Multiple selection".
* $OrderParamsGroupItemType — Contains the property group's type. Is comparable to the template variable$ORDER_PARAMS_GROUP_TYPE_X.

=== CheckoutOrderParamsListValueItem

==== Variables

These variables are available in this container.

* $OrderParamsValueItemID — Contains the property group's ID.
* $OrderParamsValueItemInputName — Contains the form name for entering the property value.
* $OrderParamsValueItemIsSelected — Flags whether the property has been selected.
* $OrderParamsValueItemMarkup — Contains the property's surcharge.
* $OrderParamsValueItemName — Contains the name of the property.
* $OrderParamsValueItemPosition — Contains the position of the property.
* $OrderParamsValueItemSelectList — Contains the values of properties of the type "Selection".
* $OrderParamsValueItemType — Contains the property type.
* $OrderParamsValueItemValue — Contains the property value. This property value should be specified as "value" in form elements.

