= Neue Buchungen importieren
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Buchungsimport, Bankbuchungsimport, Zahlungsimport, Bankbuchung
:position: 25
:url: daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-buchungen
:id: 8X2XPH8
:author: team-order-payment

Zahlungsvorgänge der Zahlungsart Vorkasse und sonstige Überweisungen fallen als Bankbuchungen an. Dabei gehen die Zahlungen auf deinem Konto ein. Um sie weiter bearbeiten zu können, musst du sie nach Zahlungseingang in dein plentymarkets System importieren. Nach dem Import von Buchungen in dein System kannst du die Zahlungen dann zum Beispiel Aufträgen zuweisen.

Du kannst den Import-Typ *Buchungen* nutzen, um neue Buchungen in dein System zu importieren. Du kannst den Import-Typ auch zur Aktualisierung von bereits bestehenden Buchungen nutzen. Auf dieser Seite wird der Import von neuen Buchungen, die noch nicht in deinem System vorhanden sind, erklärt. Grundkenntnisse über das <<daten/daten-importieren/ElasticSync#, Import-Tool>> sind hilfreich beim Erstellen deines Buchungs-Imports. In diesem Best Practice wird dennoch Schritt für Schritt erklärt, wie du vorgehen solltest.

== Importdatei vorbereiten

Daten werden in plentymarkets immer mithilfe einer CSV-Datei importiert. Deswegen musst du als erstes diese CSV-Datei vorbereiten. Die CSV-Datei sollte alle wichtigen Informationen über die Buchungen enthalten.

== Importeinstellungen wählen

== Abgleicheinstellungen wählen

== Zuordnungseinstellungen wählen

== Import testen und durchführen
- ZahlungsUI checken;
