= Integrating POS
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, POS, point of sale, POS system, points of sale, IDEA export, IDEA, GoBD, cash journal, POS journal, RKSV, DEP export, mobile POS, smartphone POS, plentyPOS
:position: 10

The mobile POS solution plentymarkets POS allows you to integrate your bricks and mortar store seamlessly both with your online presence and your plentymarkets system. The point of sale system plentymarkets POS is an optional component of the plentymarkets app.

[IMPORTANT]
.Do not change POS settings while POS is in use
====
Do not change POS settings while the POS is in use. If you have to make changes to the POS settings, tell POS users to log out of the app and log back in. Otherwise, discrepancies may occur to totals especially if you make changes to the rounding settings.
====

[#10]
== Supported hardware for plentymarkets POS

The point of sale system plentymarkets POS is an optional component of the plentymarkets app. However, there are additional hardware requirements for using plentymarkets POS. For further information about the system requirements for the plentymarkets app and plentymarkets POS, refer to the <<basics/first-steps/system-requirements#50, System requirements>> page of the manual.

Download the free plentymarkets app from the following app stores:

* link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=en[plentymarkets App in Google Play^]

* link:https://itunes.apple.com/app/plentymarkets/id957702618[plentymarkets App in iTunes^]

== Supported currencies

plentymarkets POS can be operated in Euro (EUR), Swiss Franks (CHF) and Pound Sterling (GBP). However, you can only operate the POS in the <<payment/currencies#30, system currency>>. The system currency is set in the *System » System settings » Orders » Payment » Currencies* menu.

[#20]
== Booking a plentymarkets POS

To use plentymarkets POS, you need to book one or more POS in plentymarkets. Visit our plentymarkets POS product page to get further information on prices and terms and conditions.

[#30]
== Setting up a POS for a client

Once you have booked a POS, you configure these points of sale in the plentymarkets back end. First, you assign a POS to a client by creating and configuring a POS in the **System » System settings » Client » Select client » POS** menu. To do so, proceed as described below.

[#40]
=== Creating a POS for a client

First, create a POS for the client (store) in the plentymarkets back end.

[.instruction]
Creating a POS for a client:

. Go to **System » System settings » Client » Select client » POS**.
. Click on **New POS**. +
→ The window **New POS** is displayed.
. Enter a name for the POS.
. **Save** the settings. +
→ A referrer is assigned to the POS. +
→ The POS is created and the settings are displayed.

<<table-POS-menu-bar>> describes the menu bar of a POS.

[[table-POS-menu-bar]]
.Menu bar of a POS
[cols="1,2"]
|====
|Setting |Explanation

|**ID**
|Unique ID of this POS. The ID is assigned automatically across clients and cannot be changed.

|**Copy**
|Creates a new POS with the settings of the POS currently displayed. Only the name and the referrer are changed. +
**__Note:__** You can only copy a POS if you have booked a sufficient number of POS.

|**Device**
|If this POS is linked to a device, the unique ID of that device is displayed.

|**Delete**
|Deletes the POS from the system.
|====

[#50]
=== Basic settings for POS

Now, carry out the additional settings in the **Basic settings** Tab of the POS and save these settings. Note <<table-POS-basic-settings>>.

[[table-POS-basic-settings]]
.*Basic settings* tab of a POS
[cols="1,2"]
|====
|Setting |Explanation

|*Name*
|Enter a name for the POS.

|*Referrer*
|When you book a POS, a new referrer is generated automatically. This allows you to identify orders generated with this POS. The POS is assigned to an available POS referrer (103.01 to 103.99) automatically.

|*Default customer*
|Select the <<pos/integrating-plentymarkets-pos#90, default customer created for POS orders>> to which you want to assign orders generated with this POS.

2+|*Item filters*

|*Apply market availability*
|Select if the market availability is to be applied as a filter for this POS. The market availability is activated in the **Markets** area of the variation's **Availability** tab. +
Check mark = Only variations are available in this POS for which the POS's referrer has been activated in the **Markets** area of the **Availability** tab of the variation. +
No check mark = Variations for which the POS's referrer has not been activated also are available for this POS and can be accessed and sold.

|*Include active variations only*
|Select if active variations only are to be made available for this POS. Variations are activated in the **Settings** tab of the variation. +
Check mark = Only variations are available in this POS for which the option <<item/managing-items#230, Active>> is activated in the **Settings** tab of the variation. +
No check mark = Active and inactive variations are available for this POS and can be accessed and sold.

2+|*Location*

|*Name 1-4*; +
*Address 1-4*; +
*Postcode*; +
*Town*; +
*Country*
|Enter the company name and the address of the retail outlet in which the POS is to be operated. +
*_Note:_* In Germany and other countries, saving the address is a legal requirement. Contact your tax consultant for legal advice. Your tax consultant can advise you on the correct location details. +
*_Location Austria:_* Once a start receipt has been created for the POS, the location country can no longer be changed.

2+|*Sales warehouse*

|*Sales warehouse*
|Select the sales warehouse to which you want to book orders generated with this POS. +
*_Note:_* In the POS shopping cart, items with no net stock are shown in red but can be sold. As such, mathematical overselling can occur.

2+|*Returns*

|*Default repair warehouse*
|Select the warehouse that is suggested for returned items by default.

|*Default rack*
|Select the rack of the warehouse that is suggested for returned items by default.

|*Default repair storage location*
|Select the storage location that is suggested for returned items by default. +
*_Tipp:_* Click the arrow key of your keyboard twice to show a list of storage locations.

|*Refund customer with gift card* +
|Select if POS users are allowed to hand out a gift card to the value of the refund amount instead of paying out the amount in cash.

|*Variation ID of return item* +
|Enter the ID of the variation that serves as the gift card item for refunds.

2+|*Item movement*

|*Reverse stock if order is cancelled*
|Activate to reverse stock automatically if the order is cancelled.

|*External order: Book outgoing items automatically* +
(version 1.9.2 and higher)
|Select if outgoing items are booked automatically for external items that are payed for at the POS. +
Activated (default setting) = Items are booked out automatically. The *Book outgoing items* button is not shown. +
Not activated = Items are booked out only if the POS user taps the *Book outgoing items* button. +
*_Tip:_* Deactivate the option if your customers do not receive their goods at the POS.

|*Outgoing items for external orders: Book items out of POS sales warehouse* +
(version 1.9.2 and higher)
|Select from which warehouse the order items are to be booked out when external orders are completed at the POS. +
Not activated (default setting) = The order items are booked out of the warehouse that was assigned to the order when the order was created. +
Activated = The order items are booked out of the *Sales warehouse* saved for the POS. The warehouse originally saved for the order is overwritten.

2+|*Operation*

|*Query price if price is 0.00*
|Activate to enter the price manually if an item with a price of 0 is added to a POS order.

|*Add favourites with quantity 1*
|Activate to select a quantity of 1 for favourites added to a POS order. Add the item to shopping cart again to increase the quantity. +
*_Tip:_* The quantity of favourites that were added via the item search must still be entered manually.

|*Numpad (tablet view): Show quick buttons for quantity and exact payment*
a|Activate to show quick buttons for the numpad. +
Not activated = The numpad quick buttons are not shown. +
Activated = The following numpad quick buttons are shown as an additional row of the POS’s number pad:

* *X* = POS users can enter a quantity before scanning an item or selecting a favourites item. If no quantity is entered before scanning, the scanned item is added to a POS order with a quantity of 1.
* *Exact cash amount* = If customers pay the exact amount in cash, POS users can tap this button instead of entering the amount. The *Received* field is filled with the amount due.

|*Return for a main order: Manually select order items for return*
|Select if order items should be selected for return when a main order opens. +
Not activated = Default setting. All order items are selected for return when you open the order. POS staff removes those items from the return that the customer does not want to return. +
Activated = No order items are selected for return when the order opens. POS staff adds those items to the return that the customer wants to return. +
*_Tipp:_* Activate this option if your POS does not have a scanner and if your orders typically contain a large number of order items.

2+|*Loyalty card*

|*Customer identification* +
(version 1.9.2 and higher)
|Select what contact data is to be searched when a barcode with a plus sign prefix (+) is scanned. +
*Contact ID* (default setting) = Select if barcodes contain the contact ID. +
*Customer number* = Select if barcodes contain the customer number. +
*_Tip:_* If you select *Customer number*, this allows you to print loyalty cards with barcodes in advance. The barcode code minus the plus sign is then entered into the *Customer number* field of the contact.

2+|*Austria*

|*AES key* +
(new POS with location in Austria only)
|Enter the AES key to be used for encrypting the POS's revenue counter. You can enter any AES key. However, once a start receipt has been created for the POS, the AES key can no longer be changed. +
*_Tipp:_* Click **Generate key** to generate a random key. +
*_Note:_* Existing POS cannot be made tamper-proof. Create a new POS to activate the signature unit.

|**Certifier** +
(new POS with location in Austria only)
|Enter the name of the signature service provider (Vertrauensdiensteanbieter) you bought the certificate from. +
**__Note:__** Existing POS cannot be made tamper-proof. Create a new POS and deactivate the old POS to activate the signature unit.

|**Certification number** +
(new POS with location in Austria only)
|Enter the serial number of the signature certificate. You can find this serial number in the documentation you received from the service provider (Vertrauensdiensteanbieter). +
*_Note:_* Existing POS cannot be made tamper-proof. Create a new POS and deactivate the old POS to activate the signature unit.
|====

[#60]
=== Managing favourites

You can add variations to the favourites list. This allows POS users to add frequently sold variations to the POS shopping cart more quickly.

[#70]
==== Saving variations as favourites

Proceed as described below to save variations as favourites.

[.instruction]
Saving variations as favourites:

. Go to **System » System settings » Client » Select client » POS**.
. Open the POS.
. Click on the **Favourites** tab.
. Click on the **Add variation** tab. +
→ A list of the variations is displayed.
. *_Optional:_* If necessary, use the filter to limit the number of variations shown.
. Click on **Add variations**. +
→ The variations are added to the list of favourites and displayed in the **Favourites** tab. +
→ Next time the POS is synchronised, the favourites are sent to the POS.

[TIP]
.POS users' favourites take priority
====
POS users can create their own favourites in plentymarkets POS. The POS user's favourites take priority over those favourites saved in the plentymarkets back end.
====

[#80]
==== Changing the order of favourites

You can change the priority of favourites using the arrow symbols in the **Favourites** tab. Move your most sold variations to the top of the list. The first variation on the list also is the first one displayed in the favourites list of POS users. Proceed as described below to set the order in which favourites are displayed.

[.instruction]
Changing the order of favourites:

. Go to **System » System settings » Client » Select client » POS**.
. Open the POS.
. Open the **Favourites** tab. +
→ A list of the variations of the favourites list is displayed.
. In the **Actions** column, click on the arrow of the variation you want to move. +
→ Use the up arrow to increase the priority of a variation. +
→ Use the down arrow to decrease the priority of a variation.

[#90]
==== Copying the favourites list to another POS

You can copy the favourites list of one POS to one or several other POS of the same client. This action does not delete existing favourites from the target POS. To do so, proceed as described below.

[.instruction]
Copying favourites to another POS:

. Go to **System » System settings » Client » Select client » POS**.
. Open the POS.
. Open the **Favourites** tab. +
→ A list of the variations of the favourites list is displayed.
. Click on **Copy favourites**. +
→ The **Copy favourites** window is displayed.
. Place check marks next to the POS to which you want to copy the favourites of this POS.
. **Save** the settings. +
→ The favourites are copied to the selected POS.

[#110]
==== Deleting variations from the favourites list

Proceed as described below to delete variations from the favourites list. Variations you delete from the list are deleted from the POS's favourites list during the next synchronisation.

[.instruction]
Deleting variations from the favourites list:

. Go to **System » System settings » Client » Select client » POS**.
. Open the POS.
. Open the **Favourites** tab. +
→ A list of the variations of the favourites list is displayed.
. In the variation's column, click on **Delete**. +
→ The variation is deleted from the favourites list.

[#120]
=== Editing the receipt template

In the **Receipt** tab of the POS settings, you specify the data to be displayed on receipts. Upload an image (optional) and specify the information to be displayed in the header and footer of receipts. By default, the header contains the information saved in the **System » System settings » Settings » Master data**. You can customise this information for each POS. Use the footer for any additional information. For example, tell your customers about special offers or your online store.

[.instruction]
Editing the receipt template:

. Go to **System » System settings » Client » Select client » POS**.
. Open the POS.
. Click on the **Receipt** tab.
. Place a check mark next to the components to be shown on the POS's receipts.
. Carry out the settings. Note <<table-POS-receipt-template>>.
. **Save** the settings. +
→ The receipt template is created.

[[table-POS-receipt-template]]
.Editing the receipt template
[cols="1,2"]
|====
|Setting |Explanation

2+|Receipt settings

|**Print and save gift card receipt**
a|Select if a gift card receipt is printed and saved in the document archive. +

Not activated (default) = No gift card receipt is printed. +
Activated = A gift card receipt is printed when a gift card is sold or partially redeemed. +
→ The gift card receipt is created and saved in the document archive. +
→ If the option *Automatic printing* is activated in the *plentymarkets App » Settings » POS*, the gift card receipt is printed after the POS receipt is printed. +
→ If the option *Automatic printing* is not activated in the *plentymarkets App » Settings » POS*, the POS user can print the gift card receipt manually after completing the order. +
The gift card receipt shows the following information about the gift card:

* Gift card value
* Gift card code
* For partially redeemed gift cards: redeemed amount and remaining amount

*_Note:_* Irrespective of the setting you select, the gift card code is always printed on the normal POS order receipt when a gift card is sold.

2+|Receipt content

|**Image**
|Activate the option and select a PNG file to display on the receipts generated by the POS. The file must have been uploaded to the **CMS » Image gallery** menu.

|**Header**
|If the component is selected, the field's content is displayed as a header on all receipts issued by the POS. By default, the header contains the information saved in the **System » System settings » Settings » Master data**. Make changes as needed.

|**Footer**
|Activate option and enter additional text.

|**List identical order items**
|Select how to list several identical variations on receipts. +
**Individually** = Every variation is shown individually irrespective of the quantity being sold. Example: +
---------------------------------------------------- +
Cat food CaTasty Deluxe           6.99 GBP +
Cat food CaTasty Deluxe           6.99 GBP +
Cat food CaTasty Deluxe           6.99 GBP +
---------------------------------------------------- +
**In aggregate** = Identical variations are shown in aggregate. Example: +
---------------------------------------------------- +
Cat food CaTasty Deluxe           20.97 GBP +
3 x 6.99 GBP +
---------------------------------------------------- +
|====

[#130]
== Managing user accounts for POS

The following preparations are necessary to allow POS users access to plentymarkets POS:

* Create a user account of the user class **Variable**
* Activate rights for POS visibility
* Activate rights for POS functions (optional)
* Activate rights for the REST API
* Activate rights for visibility of key figures (optional)

The settings you need to create a user account for a POS user are described below. For general information about user accounts, refer to the <<basics/admin-tasks/manage-users#, Managing user accounts>> page of the manual.

[TIP]
.Tip: Create a role for POS users
====
To simplify rights management for POS users, create a <<basics/admin-tasks/manage-users#70, role>> with those rights your POS users need, and link this role to the user accounts of POS users.
====

[#140]
=== Creating user accounts for POS users

To give new POS users access to plentymarkets POS, create a <<basics/admin-tasks/manage-users#, user account>> of the user class **Variable** in the plentymarkets back end. To do so, proceed as described below.

[.instruction]
Creating user accounts for POS users:

. Go to *System » System settings » Settings » User » Accounts*.
. Click on *New*. +
→ The *Create new user* window opens.
. Enter the *User name*.
. Enter the *Real name*.
. Enter the *Password*.
. Repeat the password.
. Enter a *New app PIN* with between 4 and 12 numbers.
. Re-enter the app PIN.
. Enter the user's email address. This allows the user to receive messages from the system.
. Select the user class *Variable*.
. *Save* the settings.

[TIP]
.App PIN for quickly switching user accounts
====
The app PIN allows users to quickly switch between user accounts in some of the views of the plentymarkets app. Users always need to enter their password to log into the app for the first time. As such, your POS users need a password and a PIN.
====

[#150]
=== Activating REST API rights for POS users

The **REST API** tab allows you to assign rights for the communication between plentymarkets POS and the plentymarkets back end via the REST API.

[.instruction]
Activating REST API rights:

. Go to **System » System settings » Settings » User » Accounts**.
. Open the variable user.
. Click on the **Right** tab.
. Click on the **REST API** tab.
. Activate the rights listed in <<table-POS-REST-rights>>.
. **Save** the settings.

[[table-POS-REST-rights]]
.Activating REST API rights for variable POS users
[cols="1,3"]
|====
|Section |Right

|*Comments*
a|* *Create comments*

|*Mobile*
a|* *POS* +
→ The required sub-rights are selected automatically.

|*Company*
a|* *Order summary » Show order summary*
* *Contact » Address » Show*
* *Contact » Address » Type » Show*
* *Contact » Show*

|*Orders*
a|* *Create orders*
* *Show orders*

|*warehouseLocation*
a|* *show*

|*Coupon* » Campaign » Code (optional)
a|* *Campaign » Code » Create*
* *Delete code* +
* *Show code*

*_Note:_* These code rights are only required if you want to sell gift cards.
|====

[#160]
=== Activating POS visibility for POS users

In the *Mobile* tab, you define which functions and key figures are visible to variable users in the plentymarkets App.

[.instruction]
Activating the rights for mobile access:

. Go to *System » System settings » Settings » User » Accounts*.
. Open a user account.
. Click on the *Right* tab.
. Open the *Mobile* tab.
. In the *Visible functions* area, activate the option *POS*.
. Activate <<pos/integrating-plentymarkets-pos#170, additional rights>> if you want to allow the user to access other areas of the plentymarkets App.
. *Save* the settings. +
→ The user is able to access plentymarkets POS and can create POS orders.

[#170]
=== Activating rights for optional POS functions

For POS users to edit prices, rename order items and/or give discounts, you need to assign the appropriate rights to POS users. Find out how to create roles and assign them to users <<basics/admin-tasks/manage-users#, here>>. You also activate additional App functions for users.

By assigning roles in the plentymarkets back end, you determine the POS functions that POS users are allowed to use. You also define which additional functions and key figures are visible in the plentymarkets App.

[.instruction]
Activating rights for POS functions:

. Go to **System » System settings » Settings » User » Accounts**.
. Open a user account.
. Click on the **Right** tab.
. Click on the **Mobile** tab.
. Activate the POS functions that the POS user should have access to. Note <<table-POS-rights>>.
. **Save** the settings.

[[table-POS-rights]]
.Mobile rights for POS users
[cols="1,2"]
|====
|Setting |Explanation

2+|Visible functions

|**POS**
|Allows POS user access to plentymarkets POS.

2+|POS functions

|**Edit price**
|Allows POS user to edit prices of order items.

|**Rename order item**
|Allows POS user to change the name of order items.

|*Give discount*
|Allows POS user to give discounts on order items or complete orders. +
*_Note:_* Items with the option *Promotional coupons/POS discount* set to *Not permitted* cannot be discounted.

|**POS**
|Allows POS user to check out items.

|**Lock POS**
|Allows POS user to lock a POS.

|**Deposits and withdrawals**
|Allows POS user to deposit and withdraw cash from the POS.

|**Cash up**
|Allows POS user to record the result of till counts.

|**Z report**
a|Allows POS user to create z reports. +
Z reports contain the following information: +

* Cash on hand: Initial cash on hand, withdrawals, deposits, expected cash on hand, actual cash on hand
* Revenue: since last Z report (sum) and since creation of POS (grand total)
* VAT report: VAT rate, VAT amount and net revenue
* Payment methods: Revenue by payment method
* Returned items: Quantity and total
* Cancellations: Quantity and total
* Discounted items: Quantity and total
* Sold gift cards: Quantity and total
* User: Revenue, cancellations and returns by user

|**X report**
a|Allows POS user to create x reports. +
X reports contain the following information: +

* Cash on hand: Withdrawals, deposits, expected cash on hand
* Revenue: since last Z report (sum) and since creation of POS (grand total)
* VAT report: VAT rate, VAT amount and net revenue
* Payment methods: Revenue by payment method
* Returned items: Quantity and total
* Cancellations: Quantity and total
* Discounted items: Quantity and total
* Sold gift cards: Quantity and total
* User: Revenue, cancellations and returns by user

|**Item synchronisation**
|Allows POS user to synchronise item data with the POS.

|**Upload orders**
|Allows POS user to upload POS orders to the plentymarkets back end.

|**Create return**
|Allows POS user to book returns.

|**Select customer**
|Allows POS user to look up customer data from the POS shopping cart and to select an existing customer for the order. +
**__Note:__** For this right to come into effect, you must also activate the right **Account » Contact » Address » Show address** in the **REST API** tab.

|**Cancellation**
|Allows POS user to cancel orders.
|====

=== Unlocking a POS user

If an incorrect password is entered several times in succession, the login is blocked for a certain amount of time. As a user with admin rights, you can unlock the user manually in the plentymarkets back end.

[.instruction]
Unlocking a user:

. Go to **System » System settings » Settings » User » Accounts » Open user**.
. Click on **Unblock login**. +
→ The POS user is able to log into the plentymarkets App.

[#700]
== Activating payment methods for POS orders

To take payment for orders generated in plentymarkets POS, activate those payment methods you want to allow. As a minimum, you need to activate the payment method **Pay upon pickup** so customers can pay cash. All other payment methods are optional.

=== Activating plentymarkets payment methods

Now activate the payment methods you need for POS orders. Note that payment methods must be permitted for customer classes in another menu. For further information, refer to <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>>.

Activate the following payment methods to process POS orders correctly:

* **4 » Pay upon pickup** for cash payments
* **11 » Cash sale/cash card** for card payments via external payment terminals
* **1700 » Coupon** for gift card purchases

Proceed as described below to activate these payment methods.

[.instruction]
Activating payment methods for POS orders:

. Go to **System » System settings » Orders » Payment » Methods**.
. Place a check mark next to the setting **Also show inactive**.
. Open the folder **International**.
. Click on the payment method. +
→ The **Settings** tab opens.
. Carry out the settings. Pay attention to the information given in <<table-POS-payment-methods>>.
. Place a check mark next to the option **Active**.
. **Save** the settings.

[[table-POS-payment-methods]]
.Settings of payment methods for POS orders
[cols="1,2"]
|====
|Setting |Explanation

|**Language**
|Select a language. The following options are saved for the language selected: Name, Info page, Info page (internal), Logo and Upload logo.

|**Name**
|Enter the external name that should be displayed on the POS receipt, in the online store and on invoices. If no name is saved, the back end name of the payment method is displayed on the POS receipt. +
__**Tip:**__ The external name is printed on the receipt in the language that the POS user selects when logging into the POS.

|**Info page**
|Only change the default setting **---** if the payment method is also used in an online store.

|**Countries of delivery**
|Select one or more countries of delivery. +
**__Note:__** Only select countries of delivery if the payment method is also used in an online store.

|**Client**
|Select the client of the POS.

|**Logo**
|Only change the default setting **Show standard logo** if the payment method is also used in an online store.

|**Costs: Flat rate or percentage**
|Enter **0.00** for all costs to make sure no surcharges are applied to POS orders.
|====

[TIP]
.Payment method Cash sale/cash card
====
For the payment method **11 » Cash sale/cash card**, also go to **System » System settings » Client » Select client » POS » Open POS » Tab: Payment method** and select **Unconnected device** in the **POS terminal** section.
====

[#1070]
=== Linking payment terminals

Some card terminals can be linked to plentymarkets POS by provisioning plugins in the plentymarkets back end. plentymarkets POS currently support the following card terminals:

* link:https://marketplace.plentymarkets.com/en/plugins/payment/ingenicozvt_5140[Ingenico devices via ZVT interface^]
* link:https://marketplace.plentymarkets.com/en/plugins/payment/sumup_5141[SumUp Air^]
* link:https://marketplace.plentymarkets.com/en/plugins/payment/VerifoneZVT_5504[Verifone devices via ZVT interface^]

Check the user guide of the plugin for details on how to use these plugins in plentymarkets POS.

[#1080]
=== Offering payment by invoice

If you want to allow existing customers to buy on account, you need the following plugin:

* link:https://marketplace.plentymarkets.com/en/plugins/payment/PosInvoice_5590[POS Invoice^]

Check the user guide of the plugin for details on how to use this plugin in plentymarkets POS.

[#950]
== Saving booking accounts for plentymarkets POS events

Orders generated in plentymarkets POS are assigned to the <<orders/accounting#800, revenue accounts>> saved in plentymarkets. Because deposits, withdrawals and till count discrepancies are not orders, you can save booking accounts for these POS events. This helps you to manage which booking accounts to associate with different POS deposits and withdrawals. In addition, you can save booking accounts for discrepancies resulting from till counts.

=== Saving booking accounts for till count discrepancies

If the actual cash on hand differs from the expected cash on hand after the count, you either need to balance the discrepancy or book the difference. When the difference is booked, the actual cash on hand is saved as the new expected cash on hand. At the same time, either a deposit (+) or a withdrawal (-) is saved depending on whether the difference is positive or negative: Proceed as described below to assign discrepancies resulting from till counts to booking accounts.

[.instruction]
Saving booking accounts for till count discrepancies:

. Go to *System » System settings » Client » Select client » Locations » Select location » Accounting*. +
→ The *Settings* tab opens.
. Click on the *Accounts* tab. +
→ The *Posting key* tab opens.
. Click on the *POS events* tab.
. Go to the *Withdrawal* area. In the row *Till count*, go to the *Account* column.
. Enter the account that you want to assign to withdrawals that occur if there is more cash in the till than expected.
. Go to the *Deposit* area. In the row *Till count*, go to the *Account* column.
. Enter the account that you want to assign to deposits that occur if there is less money in the till than expected.
. *Save* the settings. +
→ The booking accounts are saved. +
→ Deposits and withdrawals that result from till count discrepancies are booked to this account automatically.

=== Saving booking accounts for general deposits and withdrawals

When POS users deposit or withdraw cash from a plentymarkets POS, they select a POS event to save a reason for the booking. By default, one POS event *Withdrawal* and one POS event *Deposit* are saved in the system. These events cannot be deleted. If you want to book deposit and/or withdrawal amounts to specific booking accounts, you can save booking accounts for these events. Proceed as described below to save accounts for these events. You also can save additional accounts if you want to assign different booking accounts to different events.

[.instruction]
Saving booking accounts for deposits and withdrawals:

. Go to *System » System settings » Client » Select client » Locations » Select location » Accounting*. +
→ The *Settings* tab opens.
. Click on the *Accounts* tab. +
→ The *Posting key* tab opens.
. Click on the *POS events* tab.
. Go to the *Withdrawal* area. In the row *Withdrawal*, go to the *Account* column.
. Enter the account that you want to assign to general withdrawals.
. Go to the *Deposit* area. In the row *Deposit*, go to the *Account* column.
. Enter the account that you want to assign to general deposits.
. *Save* the settings. +
→ The booking accounts are saved. +
→ Deposits or withdrawals are assigned to this account.

=== Saving additional booking accounts for deposits and withdrawals

If you want to assign plentymarkets POS deposits and withdrawals to different booking accounts depending on the reason for the cash transfer, you can save additional POS events. POS users can select these POS events when they withdraw or deposit cash from the POS. Proceed as described below to save additional combinations of POS events and booking accounts.

[.instruction]
Saving additional booking accounts for deposits and withdrawals:

. Go to *System » System settings » Client » Select client » Locations » Select location » Accounting*. +
→ The *Settings* tab opens.
. Click on the *Accounts* tab. +
→ The *Posting key* tab opens.
. Click on the *POS events* tab.
. Click on *New deposit* or *New withdrawal*. +
→ A new line is inserted.
. Enter a *name* that POS users can select from the drop-down list when they deposit or withdraw cash.
. Enter the booking account that you want to associate with the deposit or withdrawal. +
**__Tip:__** Select the order in which the events are shown in the drop-down list by clicking on the arrows to the left of the account name.
. *Save* the settings. +
→ The booking account is saved. +
→ POS users can select the event from the drop-down list during deposits and withdrawals.


[#180]
== Creating the shipping method Pickup

For POS orders to be processed in plentymarkets correctly, you need to allow the shipping method **Self pickup** for those items you want to bill through plentymarkets POS. The following preparations are necessary:

* Creating a shipping service provider for pickup
* Creating a shipping profile for pickup
* Activating a shipping profile for an item

These preparations are described below.

[#190]
=== Creating a shipping service provider for pickup

Proceed as described below to create shipping service provider **Self pickup**. Only settings necessary to configure this shipping service provider are described. For general information about shipping service providers, refer to the <<fulfilment/preparing-the-shipment#800, Preparing the shipment>> page of the manual.

[.instruction]
Creating a shipping service provider for pickup:

. Go to **System » System settings » Orders » Shipping » Settings » Tab: Shipping service provider**.
. Click on **New**. +
→ A new line is added at the bottom of the overview.
. Carry out the settings. Pay attention to the information given in <<table-POS-shipping-provider-pickup>>.
. **Save** the settings.

[[table-POS-shipping-provider-pickup]]
.Creating a shipping service provider for pickup
[cols="1,2"]
|====
|Setting |Explanation

|**Name (en)**
|Enter a name, for example **Pickup**.

|**Name (back end)**
|Enter an internal name, for example **Pickup**.

|**Shipping service provider**
|Select the option **Self pickup** from the dropdown list.
|====

[#200]
=== Creating a shipping profile for pickup

Now create a shipping profile for pickup. Only settings necessary to configure this shipping profile are described. For general information about shipping profiles, refer to the <<fulfilment/preparing-the-shipment#1000, Preparing the shipment>> page of the manual.

[.instruction]
Creating a shipping profile for pickup:

. Go to **System » System settings » Orders » Shipping » Settings » Tab: Shipping profiles**.
. Click on **New**.
. Select the shipping service provider that you just created from the drop-down list.
. Carry out the settings. Pay attention to the information given in <<table-POS-shipping-profile-pickup>>.
. **Save** the settings. +
→ The **Table of shipping charges** tab is displayed.
. **Save** the settings of the **Table of shipping charges** tab without making changes.

[[table-POS-shipping-profile-pickup]]
.Creating a shipping profile for pickup
[cols="1,2"]
|====
|Setting |Explanation

|**Shipping service provider**
|Select the shipping service provider **Self pickup** from the dropdown list.

|**Clients (stores)**
|This option is only displayed if at least one client is set up. Select client(s) or **ALL** if you want to use the shipping profile for all online stores.

|**Order referrer**
|Select plentymarkets POS as the order referrer.

|**Blocked payment methods**
|Select the payment methods that should not be offered for the shipping profile **Self pickup**.
|====

[#210]
=== Activating a shipping profile for an item

Now activate the shipping profile **Self pickup** for those items you want to sell at the POS.

[.instruction]
Activating a shipping profile for pickup:

. Go to **Item » Edit item**.
. Open the item.
. Click on the **Global** tab.
. Activate the shipping profile **Self pickup**.
. **Save** the settings.

You can activate the shipping profile for a large number of items simultaneously. To do so, use the <<item/managing-items#155, item group function>>.

[#100]
== Managing prices for POS orders

You need at least one <<item/managing-items#870, sales price>> for which the POS referrer is activated to save POS prices for variations. Sales prices are created and managed centrally. Save prices for variations by linking variations to the sales price and saving a price.

[#750]
=== Creating a sales price for POS orders

If you have created sales prices with the right characteristics for POS orders already, you just need to activate the relevant POS referrer for this sales price. Proceed as described below to create a sales price for POS orders. Only settings necessary to configure the POS referrers are described.

[.instruction]
Creating a sales price for POS orders:

. Go to **System » System settings » Item » Sales prices**.
. Click on **New**. +
→ The **New** tab opens.
. Pay attention to the information given in <<table-POS-sales-price>>.
. **Save** the settings.

[[table-POS-sales-price]]
.Creating a sales price for POS orders
[cols="1,2"]
|====
|Setting |Explanation

|**Position**
|Enter the position number. Sales prices are sorted in ascending order in the **Sales prices** area of item variations.

|**Internal name EN**
|Enter the internal name. The internal name is used in the plentymarkets back end only and is not visible for the customers.

|**External name EN**
|Enter the external name. The external name is displayed in the online store and is visible to customers.

|**Minimum quantity**
|Enter a quantity value. Sales prices with different minimum quantities can be used to create a quantity based graduation of prices in plentymarkets.

|**Currency**
|Activate the currency in which POS orders are paid.

|**Price type**
|Activate a price type for the sales price. +
**UVP** = Activate if the sales price is a recommended retail price (RRP). If the RRP and another sales price are linked with a variation, the RRP is displayed in the online store as red strike-through text next to the sales price. +
**Special offer** = Activate to mark the sales price as a special offer.

|**Client**
|Activate the clients (stores) for this sales price.

|**Country**
|Activate the country in which the POS is to be used.

|**Referrer**
|Activate one or several plentymarkets POS referrers. The sales price is activated for the activated referrers.
|====

[#550]
=== Linking a sales price with variations

Now link the POS sales price with the main variations of the items you want to sell with your POS. The sales prices of the main variation are passed on to variations. You can also link individual sales prices with your variations.

[.instruction]
Linking a sales price with the main variation:

. Go to **Item » Edit item**.
. Open the item. +
→ The **Settings** tab of the main variation opens.
. Go to the **Sales prices** area and select the sales price from the drop-down list.
. Select whether the price is net or gross.
. *_Optional:_* Select a price calculation.
. Click on **Add**. +
→ The sales price is added and displayed in the list.
. Enter a value into the **Price** field.
. **Save** the settings. +
→ The prices are passed to the variations of the item. Save a different price for variations with a different price.

[#800]
=== Specifying rounding behaviour for POS orders

Totals are always shown with 2 decimal places on plentymarkets POS receipts. However, the settings in the plentymarkets back end determine if order prices are rounded to 2 decimal places or if 4 decimal places are used for calculations. The rounding behaviour for orders generated in plentymarkets POS is determined by the following 3 options:

.Options to set rounding behaviour for POS orders
[cols="10,1,1"]
|====
|Menu |Option |Possible settings

|System » System settings » Client » Select client » Locations » Select location » Accounting
|Number of decimal places
a|
* 2
* 4

|System » System settings » Client » Select client » Locations » Select location » Accounting
|Round totals only
a|
* Yes
* No

|System » System settings » Client » Select client » POS » Open POS » Tab: Receipt
|List identical order items
a|
* Individually
* In aggregate
|====

These settings result in 6 combinations of settings:

* Show order items individually, round individual prices to 2 decimal places
* Show order items individually, round individual prices to 4 decimal places
* Show order items individually, round totals to 4 decimal places
* Show order items in aggregate, round individual prices to 2 decimal places
* Show order items in aggregate, round individual prices to 4 decimal places
* Show order items in aggregate, round totals to 4 decimal places

Total sums differ depending on the settings you select. Note that these discrepancies increase the more sums requiring rounding are present in a POS order.

==== Example calculation

<<table-POS-rounding>> shows an example calculation that illustrates rounding discrepancies resulting from different combinations of settings.

The example calculation is based on the following data:

. Calculation base: Item at a price of 4.545 GBP
. Calculation 1: 10 items sold
. Calculation 2: 10 items sold at 5% discount

[[table-POS-rounding]]
.Example calculation for an item price with 4 decimal places
[cols="2,1,1"]
|====
|Selected settings |Calculation 1 (4.545 GBP x 10) Total on receipt |Calculation 2 (4.545 GBP x 10 - 5 %) Total on receipt

|Number of decimal places = 2  +
List identical order items = Individually
|45.50 GBP
|43.20 GBP

|Number of decimal places = 4  +
Round totals only = No +
List identical order items = Individually
|45.45 GBP
|43.18 GBP

|Number of decimal places = 4 +
Round totals only = Yes +
List identical order items = Individually
|45.45 GBP
|43.18 GBP

|Number of decimal places = 2 +
List identical order items = In aggregate
|43.50 GBP
|43.50 GBP

|Number of decimal places = 4 +
Round totals only = No +
List identical order items = In aggregate
|45.45 GBP
|43.18 GBP

|Number of decimal places = 4 +
Round totals only = Yes +
List identical order items = In aggregate
|45.45 GBP
|43.18 GBP
|====

For more detailed information and additional rounding examples, refer to the <<orders/accounting#, Accounting>> page of the manual.

[#95]
== Creating a default customer for POS orders

For POS orders to be saved in plentymarkets correctly, every order must be associated with a customer. As such, you need to create an anonymous default user for casual customers. Proceed as described to create a default customer for POS orders. Only settings necessary to configure the default customer for POS orders are described. For general information about creating customers, refer to the <<crm/managing-contacts#, Managing contacts>> page of the manual.

[IMPORTANT]
.Agree on your settings for the default customer for POS orders with your tax adviser.
====
Before setting up default customers for POS orders, discuss the settings to be used with your tax adviser.
====

[.instruction]
Creating a default customer for POS orders:

. Go to **CRM » Contacts**.
. Click on **Create new contact**.
. Carry out the settings. Pay attention to the information given in <<table-POS-default-customer>>.
. **Save** the settings.
. Go to **System » System settings » Client » Select client » POS » Open POS » Basic settings**.
. Enter the ID of the default customer into the **Default customer** field.
. **Save** the settings.

[[table-POS-default-customer]]
.Creating a default customer for POS orders
[cols="1,2"]
|====
|Setting |Explanation

|**Company**
|Enter a company name, for example plentymarkets POS.

|**Form of address**
|Select the option **Company** from the dropdown list.

|**Street; +
Postcode**; +
**Town**
|Enter the customer's street, postcode and town.

|**Country**
|Select the country in which the POS is to be used from the dropdown list. Default setting is based on the option **Where is the company based (for financial accounting purposes)** in the <<basics/first-steps/master-data#, System » System settings » Settings » Master data>> menu.

|**Client**
|Select a client from the dropdown list if you do not want to assign this POS to the default client.

|**Type**
|Select the option **Customer** from the dropdown list.
|====

[#220]
== Creating a dummy item

You may find that items are to be sold for which no data record exists in plentymarkets. For instance, it is often too labour intensive to create data records for miscellaneous items or remnants. Create a dummy item to be able to sell these items anyway. POS users can then add the dummy item to the POS shopping cart and modify the price and/or the name of the order item.

The following preparations are required to work with dummy items.

* Create a dummy item for each VAT rate you need for your product portfolio. As such, if you sell items with 19% and 7% VAT, you need two dummy items.
* Activate the option *Query price if price is 0* so POS users can enter the price manually.
* Assign POS users the right to edit prices.
* Assign POS users the right to rename order items (optional).

The required settings are described in <<table-POS-dummy-item>>. The subheadings indicate the menu in which the settings are carried out.

[[table-POS-dummy-item]]
.Recommended settings for dummy items
[cols="1,2"]
|====
|Setting |Explanation

2+|*Item » Edit Item » Edit item » Create new item » Tab: Settings*

|**Limitation**
|Select **Do not administer stock for this variation**.

|**Price**
|Select the sales price used for the POS and enter the price *0.00*.

|**VAT**
|Enter the VAT rate to be used for the dummy item.

2+|*System » System settings » Client » Select client » POS » Open POS*

|**Query price if price is 0**
|Activate option.

2+|*System » System settings » Settings » User » Accounts » Open account » Tab: Right » Tab: Mobile » POS functions*

|**Edit price**
|Activate the right for POS users to allow them to edit prices.

|**Rename order item**
|Activate the right for POS users if you want POS users to be able to edit the name of dummy items.
|====

[#2100]
== Preparing gift card sales

You can sell and redeem gift cards in plentymarkets POS gift cards. When you sell a gift card item, you provide customers with a gift card code. Customers only can redeem a gift card code if their gift card code is saved in the plentymarkets back end at the time the customer tries to redeem it. You either can generate gift card codes automatically or work with your own gift card codes.

The following preparations in the plentymarkets back end are necessary to sell gift cards via plentymarkets POS.

* Create a coupon campaign of the type **Gift card**.
* Create a free text field for the campaign and link it in the *System » System settings » Orders » Coupons* menu.
* Create gift card items with a VAT rate of 0% and link them to the coupon campaign.
* *_Optional:_* Generate gift card codes or save your own gift card codes in the back end.
* *_Optional:_* Create gift card templates and make them available to POS users.
* *_Optional:_* Make gift card codes available to POS users.

These steps are described below. Find more detailed information on creating campaigns and gift cards on the <<orders/coupons#, Coupons>> page of the manual.

[NOTE]
.More than one POS
====
Do you have more than one POS and create your own gift card codes? Divide the printed gift card codes between the different POS or create a separate gift card campaign and gift card items to make sure that each gift card code is sold only once.
====

=== Preparing the free text field

To sell gift cards, you need to link the gift card item to a free text field. You define this free text field and assign the field to a coupon campaign. A free text field needs to be defined only once.

[#820]
==== Defining the free text field

Define the free text field to be used for campaigns.

[.instruction]
Defining the free text field:

. Go to **System » System settings » Item » Free text fields**.
. In the *Field name* field, enter **Kampagne ID**. +
*_Note:_* Pay attention to the correct spelling. The name **Kampagne ID** is valid only as specified here.
. Select the data type **number**.
. Enter the character length.
. **Save** the settings. +
→ The free text field is activated over night and available the next day.

==== Selecting a free text field

Now, go to **System » System settings » Orders » Coupons**. Select this free text field and link the field to a coupon campaign. You only need to do this once for all campaigns.

[.instruction]
Selecting a free text field:

. Go to **System » System settings » Orders » Coupons**.
. Select the campaign field **Campaign ID** from the drop-down list.
. **Save** the settings. +
→ The **Kampagne ID** field is shown in the <<item/managing-items#75, Fields>> tab of the item.

[#830]
=== Creating a campaign for POS gift cards

Now, create one or several campaigns for selling gift cards in plentymarkets POS. You have the following options:

* You create one campaign for all gift cards you sell in plentymarkets POS.
* You create one campaign for each gift card value. +
*_Example:_* You want to sell gift cards for 10 GBP, 25 GBP and 50 GBP and a gift card with a flexible value that POS users enter during the transaction. As such, you create 3 campaigns with the discount values 10, 25 and 50 GBP and a campaign with an amount of your choice.

If you operate more than one POS and want to use your own gift card codes it also may make sense to create separate campaigns for each POS. Proceed as described below to create a campaign for gift cards:

[.instruction]
Creating a campaign for POS gift cards:

. Go to **Orders » Coupons**.
. Click on **New campaign**.
. Carry out the settings. Note <<table-POS-gift-card-campaigns>>.
. **Save** the settings. +
→ The new campaign is created and appears in the overview.

[[table-POS-gift-card-campaigns]]
.Settings for POS gift card campaigns
[cols="1,2"]
|====
|Setting |User input

2+|Campaign

|**Name**
|Enter a name for the campaign. +
*_Tip_*: The name should contain the name of the POS and the gift card value.

|**Description**
|Enter a description (optional).

|**Concept: Code**
|Select **Several codes** so that each gift card code can be redeemed only once and any remaining balance is calculated correctly when the gift card is redeemed.

|**Concept: Redemptions**
|Select **One-time redemption until the value is depleted**.

|**Use**
|Select **Single orders**, <<orders/scheduler#, Subscriptions>> or both.

|**Minimum order value**
|Do not enter a value. This is because gift cards are to be treated as a payment method. As such, they cannot be subject to a minimum order value.

2+|Validity

|**Start date**
|The date when the campaign is activated.

|**End date**
|The date when the campaign is deactivated.

|**Code validity in weeks**
|Enter *0*.

2+|Coupon

|**Coupon type**
|Select **Coupon**.

|**Type of coupon**
|Select **Gift card**.

|**Code length**
|Select the number of characters to generate for gift card codes.

|**Discount type**
|Select **Fixed amount**.

|**Discount value**
|Enter the gift card value, for example 10.00 = 10 GBP. +
**__Note:__** Do not change the discount value once the first gift card has been sold. +
*_Tip:_* This value is assigned to codes automatically when you **Generate gift card codes manually** in the **Codes** tab without entering an amount in the **Value** field. +

|**Incl. Shipping costs**
|Do not activate option.

2+|Filter

|**Items coming from price comparison portals**
|Select **Do not permit** because plentymarkets POS is not connected to a price comparison portal.

|**Categories**
|Select the categories in which the gift card can be redeemed. The sub-categories of a selected category are included automatically.

|**Items**
|Do not enter a value. This is because gift cards are to be treated as a payment method. As such, they cannot be limited to specific items.

|**Clients (stores)**
|Select the clients (stores) for the gift cards of the campaign.

|**Customer classes**
|Select the customer class for the gift cards of the campaign.

|**Customer types**
|Select the customer type for the gift cards of the campaign.
|====

[#850]
=== Managing gift card codes

To redeem gift cards in plentymarkets POS, POS users enter the gift card code. A gift card code must be present in the plentymarkets back end at the time it is redeemed.

From the point of view of POS users, the configuration options in plentymarkets result in three possible scenarios when selling gift cards:

* The gift card code is generated automatically at the POS.
* The POS user is issued with a list of gift card codes for each gift card value that have been saved in plentymarkets. The POS user enters a code. The value of the gift card code is retrieved.
* The POS user is issued with a list of gift card codes that have not been saved in plentymarkets. The POS user enters a code and a value.

Find out how to configure gift card codes for these different scenarios below.

[#2200]
==== Automatically generating gift card codes at POS

Administratively, it is easiest if POS users generate a <<pos/plentymarkets-pos-for-pos-users#250, random gift card code>> when they sell a gift card in plentymarkets POS. When the POS order is uploaded, the gift card code and the associated gift card value are then imported to the campaign that is linked to the gift card item. The gift card code is printed on the receipt. A gift card receipt is printed (optional). In addition, POS users can write down the gift card code on a decorative gift card.

[#2300]
==== Working with your own gift card codes

Your administrative work increases if you want to hand out gift card codes to POS users for them to enter when they sell items. However, it also has advantages. For instance, you can create decorative gift cards that already contain the gift card code or the gift card code and the gift card value. POS users can then simply hand out these gift cards.

Gift card codes can be saved in the system either before they are sold or at the time they are sold.

To save gift card codes in the plentymarkets back end before selling them:

* You generate gift card codes with fixed values in a campaign before you start selling gift cards.
* You save gift card codes with fixed values in a campaign before you start selling gift cards.

In both cases, you provide POS users with a list of these gift card codes and the gift card value associated with them.

To save gift card codes when they are sold:

* POS users enter a gift card code that is not yet saved in plentymarkets and the associated gift card value when selling a gift card.

In such cases, you provide POS users with a list of gift card codes. POS users enter the gift card value during the transaction. This value becomes the price at which the gift card is sold.

[NOTE]
.Take note of creation date
====
You have handed out gift card codes generated in plentymarkets to POS users already and want to generate additional gift card codes? Then take note of the gift card codes' creation dates. Gift card codes are not flagged as sold in plentymarkets. To ensure that each gift card code is only sold once, only circulate the codes you created on a particular date. We recommend that you generate gift card codes in the **Orders » Coupons** menu and export these gift card codes to a CSV file. Filter the CSV file by the creation date, i.e. the column *GeneratedOn*. This leaves you with a list of the newly created gift card codes.
====

[#2400]
==== Generate gift card codes manually

Use the coupon generator in the **Codes** tab of a campaign to create one or more gift card codes automatically.

[.instruction]
Generating gift card codes with a fixed value:

. Go to **Orders » Coupons**.
. Click on the campaign for which you want to generate gift card codes.
. Click on the **Codes** tab.
. In the **Generate gift card codes manually** area to the left, enter the number of gift card codes you want to generate.
. *_Optional:_* In the **Value** field, enter the value to be assigned to the gift card code. +
*_Tip:_* If you leave the **Value** field empty, the discount value of the campaign is assigned.
. **Save** the data. +
→ The gift card codes are created and added to the list of gift card codes.
. Click on *Export* to export the gift card codes. +
→ A CSV export of all gift card codes of the campaign is created.
. Filter the *GeneratedOn* column of the CSV file by the current date. This results in a list of all newly created gift card codes. +
. Provide POS users with the gift card codes and their value. +
*_Note:_* Do not circulate duplicate gift card codes. If you operate more than one POS, either split the gift card codes or create separate campaigns for each POS.

[#2500]
==== Saving your own gift card codes with a fixed value

Instead of generating gift card codes in plentymarkets, you also can save your own gift card codes in plentymarkets before selling them. Valid characters for gift card codes are lower and upper case letters, numbers, underscores (_) and hyphens (-).

[.instruction]
Saving your own gift card codes with a fixed value:

. Go to **Orders » Coupons**.
. Click on the campaign for which you want to generate a gift card code.
. Click on the **Codes** tab.
. In the **Enter gift card code manually** area to the right, enter a code with 6 to 24 characters.
. **Save** the data. +
→ The gift card code is saved and added to the list of gift card codes. +
*_Tip:_* Use the data format **CampaignCoupon** to import several gift card codes at once. The **Discount value** is imported as the gift card value. As such, you need to create one campaign for each gift card value if you want to use the data format.
. Provide POS users with the gift card codes and their value. +
*_Note:_* Do not circulate duplicate gift card codes. If you operate more than one POS, either split the gift card codes or create separate campaigns for each POS.

[#3900]
=== Activating the printing and saving of gift card receipts

A gift card receipt can be created and printed. The gift card receipt shows the following information about the gift card:

* Gift card value
* Gift card code
* For partially redeemed gift cards:
	** Redeemed amount
	** Remaining amount

[.instruction]
Activating printing of gift card receipts:

. Go to *System » System settings » Client » Select client » POS*.
. Open the POS.
. Click on the *Receipt* tab.
. Activate the option *Print and save gift card receipt*.
. **Save** the settings. +
→ A gift card receipt is printed when a gift card is sold or partially redeemed. +
→ The gift card receipt is saved in the document archive. +
→ If the option *Automatic printing* is activated in the *plentymarkets App » Settings » POS*, the gift card receipt is printed after the POS receipt is printed. +
→ If the option *Automatic printing* is not activated in the *plentymarkets App » Settings » POS*, the POS user can print the gift card receipt manually after completing the order. +
*_Note:_* Irrespective of the setting you select, the gift card code is always printed on the normal POS order receipt when a gift card is sold.


[#840]
=== Creating a gift card item

Now, create one or more gift card items. Because the campaign ID is linked at the item level, you cannot use variations to create gift cards. For further information about creating items, refer to the <<item/managing-items#, Managing items>> page of the manual. Only settings needed for creating gift card items are described here.

==== Creating gift card items with a fixed value

POS users are not prompted to enter a price when selling gift card items with a fixed price. This speeds up the transaction but also offers less flexibility.

When working with existing gift card codes:

* The value of the existing gift card code must match the price of the item. As such, the gift card item must be linked to the campaign with the gift card codes of the correct values. If you create one campaign for each gift card value, each campaign is linked to one item only. If you create a campaign with different gift card values, this campaigns is linked to more than one gift card item.

[.instruction]
Creating gift card items with a fixed value:

. Go to **Item » Edit item**.
. Click on **New**. +
→ The **New item** tab opens.
. Select the type **Default**.
. Enter a name. +
*_Tip_*: The name should include the gift card value.
. Enter the content **1 piece**.
. Select a category.
. Select a sales price from the drop-down list. +
*_Note_*: The sales price must be linked to the order referrer of the POS.
. Enter the gift card value as the price.
. **Save** the settings. +
→ The item is created and opened for editing.
. Carry out the additional settings. Note <<table-POS-gift-cards-item-settings>>.
. **Save** the settings.

[#2600]
==== Creating gift card items with a flexible value

Gift card items with flexible value are items with a price of 0.00 GBP. You can control the price at which these gift cards are sold at the POS in two different ways:

* POS users enter a gift card code saved in plentymarkets. The value of the gift card code becomes the price of the gift card.
* POS users either generate a code or save a gift card code and enter the gift card value.

[.instruction]
Creating a gift card item with a flexible price:

. Go to **Item » Edit item**.
. Click on **New**. +
→ The **New item** tab opens.
. Select the type **Default**.
. Enter a name.
. Enter the content **1 piece**.
. Select a category.
. Select a sales price from the drop-down list. +
*_Note_*: The sales price must be linked to the order referrer of the POS.
. Enter a price of **0.00** GBP.
. **Save** the settings. +
→ The item is created and opened for editing.
. Carry out the additional settings. Note <<table-POS-gift-cards-item-settings>>.
. **Save** the settings. +
→ *_With existing gift card code:_* POS users enter a gift card code of the campaign linked to this item. The item is billed at the value of the gift card code. +
→ *_Without existing gift card code:_* POS users are prompted to enter a price when they place the item in the POS shopping basket.

[[table-POS-gift-cards-item-settings]]
.Item settings for gift cards with fixed or flexible values
[cols="1,2"]
|====
|Setting |Explanation

2+|*Item » Edit item » Open item » Open variation » Tab: Settings*

|**Active**
|Activate option.

|**Limitation**
|Select **None**.

|**VAT**
|Select **0%**.

2+|*Item » Edit item » Open item » Open variation » Tab: Availability*

|**Markets**
|Select those POS at which you want to sell the gift card items from the drop-down list.

|**Client**
|Select the POS's client (store).

2+|*Item » Edit item » Open item » Tab: Fields*

|**Campaign ID**
|Enter the ID of the gift card campaign to link the item to the campaign.
|====

[#3800]
=== Assigning rights for selling gift cards

Users with admin rights are able to create gift cards by default. *Variable* users must be assigned this right.

[.instruction]
Assigning rights for selling gift cards:
. Go to *System » System settings » Settings » User » Accounts*.
. Open the variable user account.
. Click on the *Right* tab.
. Click on the *REST API* tab.
. Open the area *Coupon » Campaign » Code*.
. Activate the following rights:
	** Create code
	** Delete code
	** Show code
. *Save* the settings.

[#2700]
=== Notes on selling gift cards

* Revenue does not increase when a gift card is sold.
* Sold gift cards are shown separately on the Z report. The cash on hand only increases if the gift card is paid for in cash.

[#2800]
=== Notes on redeeming gift cards

* The value of the gift card is deducted from the gross total.
* The revenue is increased by the redeemed gift card amount.
* On the Z report, redeemed gift cards are shown with the payment method *Gift card*.
* The cash on hand does not increase when a gift card is redeemed.

[#3600]
== Preparing returns

To accept returns, all you need to do is select a default repair storage location for returns in the POS settings and set appropriate user rights for those POS users that are allowed to handle returns. No other settings are necessary to return items in plentymarkets POS if you want to pay out refunds in cash. Note the <<pos/integrating-plentymarkets-pos#2000, information on handling returns>>. If you want to be able to convert the refund into a gift card, also prepare <<pos/integrating-plentymarkets-pos#3100, refund gift cards>>.


[#2000]
=== Return information

Note the following information on handling returns in plentymarkets POS:

* For technical reasons, refunds can only be paid out in cash.
* Customers cannot return gift cards.
* You can book returns for all orders saved in the system. As such, customers also can return order items they bought from other referrers, such as the online store or a market. The POS staff decides if a customer can return an item. As such, you should inform your POS staff about any referrers that are excluded from POS returns.
* By default, POS users are shown the storage location that in the *Basic settings* tab of the POS is set up as the *Default storage location*. POS users can select a different storage location for returned items. The possible storage locations are shown in the following order:
  .. Storage location from order = The storage location of the item at the time it was sold.
  .. Default repair storage location = The *Default repair storage location* selected in the *Basic settings* tab of the POS.
  .. Suggested storage locations = The storage location suggestions of the warehouses linked to the variation.
  .. Used storage locations = The storage locations in which the variation is stored already.
Tell your POS staff which storage location to select for returned items.
* If the main order included shipping costs, your POS staff decides whether or not those shipping costs are refunded during the return process. As such, you should train your staff to make sure they know when to refund shipping costs.
* Instruct your POS staff to cross out returned items on the original receipt. This helps to ensure that customers do not return items more than once.
* If the customer was issued an invoice for the original order, they only receive money back if the price of the items they want to return is higher than the invoice amount they already paid.
* The refund amount can be converted into a gift card instead of paid out in cash. If you want to do so, train POS users so your staff knows when to pay out refunds in cash and when to issue a gift card for the amount instead.

[#3100]
=== Preparing refund gift cards

Instead of paying the refund amount in cash, a gift card can be issued for the refund amount. In these cases, the refund amount is paid out theoretically only and a gift card is bought from the amount at the same time. As such, when a refund is converted into a gift card, a return, a credit note and a new order are created.

The following preparations in the plentymarkets back end are necessary to create gift cards for refunds.

* Create a coupon campaign of the type *Gift card*.
* Create gift card items with a VAT rate of 0% and link them to the coupon campaign.
* Link gift card item for refunds with the POS.
* Assign REST API rights to variable user accounts.


These steps are described below. Find more detailed information on creating campaigns and gift cards on the <<orders/coupons#, Coupons>> page of the manual.


[#3200]
==== Creating a campaign for refund gift cards

Proceed as described below to create a campaign for gift cards for refunds:

[.instruction]
Creating a campaign for refund gift cards:

. Go to *Orders » Coupons*.
. Click on *New campaign*.
. Carry out the settings. Note <<table-POS-refund-campaign>>.
. *Save* the settings. +
→ The new campaign is created and appears in the overview.

[[table-POS-refund-campaign]]
.Settings for gift cards for refunds
[cols="1,2"]
|====
|Setting |User input

2+|Campaign

|*Name*
|Enter a name for the campaign.

|*Description*
|Enter a description (optional).

|*Concept: Code*
|Select *Several codes*.

|*Concept: Redemptions*
|Select *One-time redemption until the value is depleted*.

|*Use*
|Select *Single orders*, <<orders/scheduler#, Subscriptions>> or both.

|*Minimum order value*
|Do not enter a value.

2+|Validity

|*Start date*
|The date when the campaign is activated.

|*End date*
|The date when the campaign is deactivated.

|*Code validity in weeks*
|Enter *0*.

2+|Coupon

|*Coupon type*
|Select *Coupon*.

|*Type of coupon*
|Select *Gift card*.

|*Code length*
|Select the number of characters to generate for gift card codes.

|*Discount type*
|Select *Fixed amount*.

|*Discount value*
|Enter a gift card value, for example 1.00.

|*Incl. Shipping costs*
|Do not activate option.

2+|Filter

|*Items coming from price comparison portals*
|Select *Do not permit*.

|*Categories*
|Select the categories in which the gift card can be redeemed. The sub-categories of a selected category are included automatically.

|*Item*
|Do not enter a value.

|*Clients (stores)*
|Select the clients (stores) for the gift cards of the campaign.

|*Customer classes*
|Select the customer class for the gift cards of the campaign.

|*Customer types*
|Select the customer type for the gift cards of the campaign.
|====

[#3300]
==== Managing gift card codes

Codes for refund gift cards are managed like other gift card codes. You have the following options:

* <<#2200, The POS automatically generates a gift card code.>>
* <<#2300, The POS user enters a code that is not saved in plentymarkets.>>


[#4000]
==== Activating the printing and saving of gift card receipts

A gift card receipt can be created and printed. The gift card receipt shows the following information about the gift card:

* Gift card value
* Gift card code
* For partially redeemed gift cards:
	** Redeemed amount
	** Remaining amount

[.instruction]
Activating printing of gift card receipts:

. Go to *System » System settings » Client » Select client » POS*.
. Open the POS.
. Click on the *Receipt* tab.
. Activate the option *Print and save gift card receipt*.
. **Save** the settings. +
→ A gift card receipt is printed when a gift card is sold or partially redeemed. +
→ The gift card receipt is saved in the document archive. +
→ If the option *Automatic printing* is activated in the *plentymarkets App » Settings » POS*, the gift card receipt is printed after the POS receipt is printed. +
→ If the option *Automatic printing* is not activated in the *plentymarkets App » Settings » POS*, the POS user can print the gift card receipt manually after completing the order. +
*_Note:_* Irrespective of the setting you select, the gift card code is always printed on the normal POS order receipt when a gift card is sold.

[#840]
==== Creating gift card item for refunds

Create a gift card item with a price of 0.00 GBP. Only settings needed for creating gift card items for refunds are described here.

[.instruction]
Creating gift card item for refunds:

. Go to *Item » Edit item*.
. Click on *New*. +
→ The *New item* tab opens.
. Select the type *Default*.
. Enter a name.
. Enter the content *1 piece*.
. Select a category.
. Select a sales price from the drop-down list. +
*_Note_*: The sales price must be linked to the order referrer of the POS.
. Enter a price of *0.00* GBP.
. *Save* the settings. +
→ The item is created and opened for editing.
. Carry out the additional settings. Note <<table-POS-refunds-gift-cards-item-settings>>.
. *Save* the settings.
. Jot down the ID of the variation.

[[table-POS-refunds-gift-cards-item-settings]]
.Item settings for gift cards for refunds
[cols="1,2"]
|====
|Setting |Explanation

2+|*Item » Edit item » Open item » Open variation » Tab: Settings*

|*Active*
|Activate option.

|*Limitation*
|Select *None*.

|*VAT*
|Select *0%*.

2+|*Item » Edit item » Open item » Open variation » Tab: Availability*

|*Markets*
|Select one or more POS from the drop-down list.

|*Client*
|Select the POS's client (store).

2+|*Item » Edit item » Open item » Tab: Fields*

|*Campaign ID*
|Enter the ID of the gift card campaign to link the item to the campaign.
|====

[#3400]
==== Linking gift card item for refunds with POS

[.instruction]
Linking gift card item for refunds with POS:

. Go to **System » System settings » Client » Select client » POS**.
. Open the POS. +
→ The *Basic settings* tab opens.
. Activate the option *Refund customer with gift card*. +
. In the *Variation ID of refund gift card* field, enter the ID of the variation you set up for gift card refunds. +
→ The gift card item is selected automatically during a return.




[#3700]
==== Assigning rights for refund gift cards

Users with admin rights are able to create refund gift cards by default. *Variable* users must be assigned this right.

[.instruction]
Assigning rights for refund gift cards:

. Go to *System » System settings » Settings » User » Accounts*.
. Open the variable user account.
. Click on the *Right* tab.
. Click on the *REST API* tab.
. Open the area *Coupon » Campaign » Code*.
. Activate the following rights:
	** Create code
	** Delete code
	** Show code
. *Save* the settings.

[#3500]
==== Additional information for refunds with gift cards

* In the POS journal, refund gift cards are shown as new orders with the note *Gift card due to return*. Just like when you pay out refunds in cash, a credit note is created. The cash on hand is reduced by the credit note. However, it immediately increases due to the new order. As such, the total cash on hand remains the same.
* On z reports, returned items refunded as gift cards are shown as cash refunds.
* Gift cards due to refunds are shown as gift card sales on the Z report. The total cash on hand remains the same.

[#4100]
== Preparing pickup and payment of online orders (click & collect)

Items ordered in your online store, on markets or via other sales channels can be paid for online and picked up at the retail store or picked up and paid for in the store.

The following preparations for the POS are necessary if you want your customers to be able to pick up and pay for online orders at your retail outlet.

* The order ID is needed to search for orders at the POS. +
→ Ensure that your order confirmations contain the order ID. → Make sure that your order confirmations state the order ID clearly and that customers are aware that they need this order ID to pick up their order at your retail outlet.
* Train POS users to verify the identity of customers who come to pick up orders that were paid for online. Otherwise your POS users may hand over paid items to the wrong person by mistake.
* Do you use processes and/or event procedures to automatically process orders generated in the online store and/or on markets? +
→ Check your event procedures and processes before you offer store pickups. → Make sure that orders are only set to the status *Outgoing items booked* by an event procedure or a process after the customer has picked up the ordered items from the retail outlet. +
→ The POS shows that a customer has received the goods they ordered after the items have been booked out in plentymarkets. → If problems occur and a customer insists that they have not received the items, check the order in the plentymarkets back end. The items may have been booked out too early.

Also note the following information and limitations regarding payment and pickup of online orders at the retail outlet:

* Online orders cannot be edited at the POS. POS users can only book payments or save order notes. +
* Online orders can be paid for at the POS using gift cards in app version 1.9.2 and higher. However, gift cards can only be used if no payment has been made for the order and no invoice document has been created yet.
* Online orders cannot be cancelled at the POS.
* Payments that are booked at the POS to clear online orders do not increase the POS’s revenue. +
→ Payments that are not revenue relevant for the POS are saved as POS events of the type *Payment* in the Cash Journal.
* The option *External order: Book outgoing items automatically* of the POS settings allows you to specify if the order items are booked out of the warehouse automatically. This option is activated by default for POS created on or after the 05th of March 2019. If you deactivate this option, explain to your POS users in what cases they need to manually book outgoing items.

[#2900]
[#3000]
== Booking outgoing items automatically

The stock is not reduced automatically when you sell an item. Create the event procedure described below to book outgoing items when a POS order is created: For further information about managing stock, refer to the <<stock-management/outgoing-items#, Booking items out>> page of the manual.

[.collapseBox]
.Booking outgoing items for POS orders
--
. Go to **System » System settings » Orders » Events**.
. Click on **Add event procedure**. +
→ The **Create new event procedure** window opens.
. Enter a name.
. Select the **event** listed in <<table-POS-event-procedure-outgoing-items>>.
. **Save** the settings.
. Carry out the settings. Pay attention to the information given in <<table-POS-event-procedure-outgoing-items>>.
. Place a check mark next to the option **Active**.
. **Save** the settings.
--

[[table-POS-event-procedure-outgoing-items]]
.Event procedure for booking outgoing items for POS orders
[cols="1,3,3"]
|====
|Setting |Option |Selection

|**Event**
|**Documents: Receipt generated**
|

|**Filter 1**
|**Order &gt; Order type**
|**Order**

|**Filter 2**
|**Order &gt; Referrer**
|Select the POS referrers to book outgoing items for.

|**Procedure**
|**Order &gt; Book outgoing items**
|
|====

[#600]
== Installing the plentymarkets app on a device

Now, install the plentymarkets App on the device on which the POS is to be operated.

* link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=en[plentymarkets App in Google Play^]

* link:https://itunes.apple.com/app/plentymarkets/id957702618[plentymarkets App in iTunes^]

[WARNING]
.Offline orders are deleted when you uninstall the app
====
If your internet connection is down, POS orders are saved on your device and uploaded to plentymarkets once connection returns. If you uninstall the app on your device before all orders were uploaded to plentymarkets, the orders saved on your device are deleted permanently and cannot be recovered by you or the plentymarkets support team. As such, check that no offline orders exist on the device before you uninstall the app.
====

[#230]
== Linking a POS to a device

Now, connect the POS with the device on which the POS is to be operated.

=== Linking a POS to a device

Proceed as described below to link a POS to the device on which the POS is to be operated.

[IMPORTANT]
.Set date and time automatically
====
To correctly synchronise POS orders and z reports with the plentymarkets back end, the date and time of the device must be set correctly. As such, we recommend that you let the device set the date and time automatically to prevent z report inconsistencies.
====

[.instruction]
Linking a POS to a device:

. Open the plentymarkets App on the device that you want to link to this POS.
. Go to **plentymarkets App » Settings » POS**.
. Carry out the settings. Note <<table-POS-link-device>>.
. **Save** the settings. +
→ Device and POS are linked.

[[table-POS-link-device]]
.Linking a POS to a device
[cols="1,2"]
|====
|Setting |Explanation

|**Client**
|Select the client for which the POS was created.

|**POS**
|Select POS.

|**Price**
|Select if orders are to be created gross or net.

|**Receipt printer**
|Enter the IP address of the receipt printer. +
**__Tip:__** Tap **Print test receipt** to print a receipt with test data.

|**Printer**
|You can also operate <<1000, additional printers>> using the plugin plentyBase.

|**Automatic printing**
|**On** = Default setting. POS receipts and documents are printed automatically once a process is complete. +
**Off** = POS users must trigger printing of POS receipts and documents manually.

|**Schema** +
(tablets only)
|**Smartphone** = Optimised view for smartphones; landscape or portrait. +
**Tablet** = Optimised view for tablets; landscape only.

|**Create start receipt** +
(new POS with location in Austria only)
|Select to <<pos/integrating-plentymarkets-pos#900, create the start receipt>> (Startbeleg). This will activate the tamper-proof signature unit for the POS. After the start receipt is created, the location country of the POS cannot be changed.

|**Create end receipt** +
(POS with location in Austria and activated signature unit only)
|Select to <<pos/integrating-plentymarkets-pos#920, create the end receipt>> (Endbeleg). This will deactivate the tamper-proof signature unit for the POS. Once an end receipt has been created, the POS can no longer be operated.
|====

[#240]
=== Unlinking a POS from a device

You can unlink a POS from a device. Instead, either link a different POS to the device or select no POS.

[.instruction]
Unlinking a POS from a device:

. Open the plentymarkets App.
. Go to **plentymarkets App » Settings » POS**.
. For the setting **POS**, select a different POS or the empty option.
. **Save** the settings. +
→ Device and POS are unlinked.

[IMPORTANT]
.Unlinking is only possible on the device
====
You can only unlink a POS from a device in the settings of the device itself. Contact the plentymarkets Support to unlink the device in case of device failure or loss.
====

[#250]
== Emailing receipts to existing customers

plentymarkets allows you to set up an event procedure that automatically emails POS receipts to the email address saved for a customer record. First create an email template with the PDF attachment **Receipt**. Then, you create an event procedure. Note that for POS orders created in offline mode, the event procedure only takes effect once the POS order is uploaded to the plentymarkets back end. Before activating an event procedure for automatic emails, check the current legal restrictions regarding emailing customers.

[#260]
=== Creating an email template

First, create an <<crm/sending-emails#1200, email template>> that is sent when a receipt is generated.

[.instruction]
Creating an email template:

. Go to **System » System settings » Client » Select client » Email » Templates**.
. Click on **New email template**. +
→ The **New email template** window opens.
. Enter a name for the template.
. Select an owner or the setting **All** from the drop-down list **Owner**.
. **Save** the settings. +
→ The email template is created and saved in one of the three folders based on the owner you selected.
. Select the PDF attachment **Receipt**.
. Carry out the additional settings. Pay attention to the information on <<crm/sending-emails#1200, creating a new email template>>.
. **Save** the settings.

[#270]
=== Creating an event procedure for automatic emails

Now, create an event procedure that triggers an email to the customer when a receipt is generated.

[.collapseBox]
.Creating an event procedure for automatic emails
--
. Go to **System » System settings » Orders » Events**.
. Click on **Add event procedure**. +
→ The **Create new event procedure** window opens.
. Enter a name.
. Select the **event** listed in <<table-POS-event-procedure-send-receipt>>.
. **Save** the settings.
. Carry out the settings. Pay attention to the information given in <<table-POS-event-procedure-send-receipt>>.
. Place a check mark next to the option **Active**.
. **Save** the settings.
--

[[table-POS-event-procedure-send-receipt]]
.Event procedure for automatically sending receipts
[cols="1,3,3"]
|====
|Setting |Option |Selection

|**Event**
|**Documents: Receipt generated**
|

|**Filter 1**
|**Order &gt; Order type**
|**Order** +
**Return**

|**Filter 2**
|**Order &gt; Referrer**
|Select the POS for which you want to email receipts.

|**Procedure**
|**Customer &gt; Send email**
|**Template**: Select the email template you set up for sending receipts +
**Recipient**: Select the option **Customer**
|====

[#1000]
== Setting up printing of POS receipts on other printers

By default, all POS receipts are printed on the receipt printer that you specify in the *plentymarkets App » Settings » POS* menu, option *Receipt printer*. However, you can also print POS receipts on other printers. For example, you might like to print receipts that need to be archived for longer periods on an A4 printer instead of on a thermal printer.

To use additional printers, you need a printer that can be accessed via the network that is connected to one or more printers on which you want to print the POS receipts. On this computer, you install the plugin link:https://marketplace.plentymarkets.com/en/plugins/integration/plentyBase_5053[plentyBase^]. plentyBase establishes a connection between the plentymarkets app and the local computer. This allows the POS to access any printers that the local computer can also access. Go to the plentymarkets back end menu *System » System settings » Settings » Printers* to configure these printers.

[TIP]
.Receipt printer does not require plentyBase
====
The receipt printer is connected to the plentymarkets app via the printer’s IP address. As such, you do not need plentyBase to operate the receipt printer. This means that you only need plentyBase if you want to use other printers with plentymarkets POS.
====

[#1010]
=== Installing and setting up plentyBase

plentyBase is a plugin developed by plentymarkets. Unlike many other plentymarkets plugin, plentyBase is not activated in the plentymarkets back end. Instead, you install and run plentyBase on a local computer. plentyBase establishes an interface that allows you to use the printers that are connected to the computer in the plentymarkets back end and/or the plentymarkets app.

The following steps are necessary to make the printers available to the plentymarkets app:

* plentyBase must be installed on the computer. +
→ To download the installation file, go to the link:https://marketplace.plentymarkets.com/en/plugins/integration/plentyBase_5053[plentyMarketplace^].
* plentyBase must be configured on the computer. +
→ Find out how to configure plentyBase in the plugin description of the plugin link:https://marketplace.plentymarkets.com/en/plugins/integration/plentyBase_5053#140.[plentyBase^]. +
*_Note:_* During configuration, activate the option *HTTP server*. This ensures that plentymarkets POS can communicate with plentyBase.
* plentyBase must be running on the computer. +
*_Recommendation:_* Configure plentyBase to run automatically when the computer is started up.
* The plentyBase connection data must be saved in the plentymarkets app: +
→ Find out how to save the plentyBase connection data in the plugin description of the plugin link:https://marketplace.plentymarkets.com/en/plugins/integration/plentyBase_5053#140.[plentyBase^].
* The printers must be configured in the plentymarkets back end menu *System » System settings » Settings » Printers*.

[#1020]
=== Saving printers for POS receipts

After you have set up plentyBase, you can select the printers that were configured in the plentymarkets back end from the drop-down lists of the *Printers* area in the *plentymarkets App » Settings » POS* menu.

Proceed as described below to select the printers for printing individual types of receipts.

[.instruction]
Selecting a printer for each type of receipt:

. Open the plentymarkets App.
. Go to *plentymarkets App » Settings » POS*.
. Configure the settings in the *Printers* area. Pay attention to <<table-POS-printers>>.
. **Save** the settings.

[[table-POS-printers]]
.Selecting printers for POS receipts
[cols="1,3"]
|====
|Setting |Explanation

|*Default printer*
|Select the default printer for the POS from the drop-down list. The receipt printer is selected by default. +
*_Note:_* The drop-down list shows the receipt printer and those printers in the network that the POS can access.
If you can only select the receipt printer or the default printer from the drop-down list, perform a <<1040, troubleshooting>>.

|*Purchase receipt*; +
*Z report*; +
*X report*; +
*Cash up*; +
*Cancellation receipt*; +
*Deposits and withdrawals*; +
*Coupon receipt*; +
*Return receipt*; +
*Credit note receipt*
|The default printer is selected by default. If you want to print all receipts on the default printer, you do not need to change any settings. If you want to print on different printers, select the printers on which you want to print the individual receipts from the drop-down menu. +
*_Note:_* The drop-down lists show the receipt printer and those printers in the network that the POS can access.
If you can only select the receipt printer or the default printer from the drop-down lists, perform a <<1040, troubleshooting>>.
|====

[#1060]
=== Printing a test page

Proceed as described below to print a test page.

[.instruction]
Printing a test page:

. Open the plentymarkets App.
. Go to *plentymarkets App » Settings » POS*.
. Tap the menu symbol at the top right of the screen.
. Tap *Test print*. +
→ The *Test print* window is displayed.
. From the drop-down list, select the receipt for which you want to print a test page.
. Tap *Print test page*. +
→ A test page is printed. +
→ If no test page is printed, check the settings as described in the <<1050, troubleshooting case 2>>.

[#1030]
=== Troubleshooting: Trouble printing

[#1040]
==== Case 1: You are unable to select any printers in the POS settings.

So far, you have not saved any additional printers in the POS settings. Only the receipt printer and the default printer can be selected from the drop-down lists of the *Printers* area. Note that in this case, the receipt printer and the default printer are identical.

* Did you install plentyBase on a computer in the network? +
→ To download the installation file, go to the link:https://marketplace.plentymarkets.com/en/plugins/integration/plentyBase_5053[plentyMarketplace^].
* Did you configure plentyBase correctly? +
→ Find out how to configure plentyBase in the plugin description of the plugin link:https://marketplace.plentymarkets.com/en/plugins/integration/plentyBase_5053#140.[plentyBase^]. +
*_Tip:_* Did you activate the option *HTTP server* and specify an HTTP port?
* Did you save the plentyBase settings in the app? +
→ Find out how to save the plentyBase connection data in the plugin description of the plugin link:https://marketplace.plentymarkets.com/en/plugins/integration/plentyBase_5053#140.[plentyBase^]. +
*_Tip:_* Did you save the right HTTP port in the app?
* Is plentyBase running on the computer? +
*_Recommendation:_* Configure plentyBase to run automatically when the computer is started up.
* Has the printer been <<basics/admin-tasks/printer#, saved and configured>> in the plentymarkets back end?

[#1050]
==== Case 2: Printers are saved in the POS settings but are not available

A printer was selected for printing one or more types of receipts and the selection was saved. However, the printer is now flagged with a warning symbol and printing is not possible.

* Is the computer running on which plentyBase is installed?
* Is the printer switched on and ready?
* Is the printer connected to the computer?
* Is plentyBase running on the computer?
* Did someone recently change the plentyBase configuration settings, for example the HTTP port or the access token? +
→ If so, did you save the new settings in the plentymarkets app?
* Was the printer configuration removed from the plentymarkets back end? +
→ Go to the plentymarkets back end menu *System » System settings » Settings » Printers* to configure printers.

[#1090]
== Setting up printing of item labels

For further information about creating label templates and printing the labels in the item search of the plentymarkets app, refer to <<item/manage-items#760, Setting up labels>>.

[IMPORTANT]
.Configuring plentyBase
====
To print labels, you need the free plugin plentyBase. plentyBase establishes an interface that allows you to use the printers that are connected to the computer in the plentymarkets back end and/or the plentymarkets app. → Find out how to install and configure plentyBase in the plugin description of the plugin link:https://marketplace.plentymarkets.com/en/plugins/integration/plentyBase_5053[plentyBase^].
====


[#400]
== Searching POS transaction in the cash journal

All POS transactions are documented in plentymarkets. Use the **Orders » POS » Cash journal** menu to search, show or export POS transactions. Use the filters in the **Filters** tab to limit the number of POS transactions shown in the cash journal to those meeting specific criteria. The POS transactions found are listed in the **Cash journal** tab. By default, results are sorted by date. Proceed as described below to search POS transactions in the POS journal.

[.instruction]
Searching for POS transaction in the cash journal:

. Go to **Orders » POS » Cash journal**.
. Select filters. Pay attention to the information given in <<table-POS-cash-journal-menu>>.
. Click on **Search**. +
→ The POS transactions that correspond to the search criteria entered are listed in the **Cash journal** tab.

[[table-POS-cash-journal-menu]]
.Menu *Cash journal*
[cols="1,2"]
|====
|Setting |Explanation

2+|Tab: Filter

|*Search*
|Click on *Search* without selecting any filter settings. This displays all POS transactions. +
*_Or:_* Limit the search results by using filters and click on *Search*. The POS transactions found are listed in the *Cash journal* tab.

|**Reset**
|Resets the selected filter criteria.

|**Receipt number: from**; +
**Receipt number: to**
|Enter the receipt numbers of the first and last receipt to search for receipts of a specific receipt number range. To show a single receipt, enter the same receipt number in the field **Receipt number: from** and the field **Receipt number: to**.

|**POS**
|Select a POS from the drop-down list to limit the results to POS transactions that were carried out with a specific POS.

|**Client**
|Select a client (store) from the drop-down list to limit the results to POS transactions that were carried out for a specific client.

|**User**
|Select a user from the drop-down list to limit the results to POS transactions that were carried out by a specific user.

|**Payment method**
|Select a payment method from the drop-down list to limit the results to POS transactions that were carried out using a specific payment method. Only active payment methods are listed.

|**Period**
|Select a period to limit the POS transactions shown to those that were created during this period. +
To only show receipts of a custom period, select **Date selection**. Then select the starting date from the calendar in the **from** field and the ending date from the calendar in the **to** field.

|**Type**
|Select a type from the drop-down list to limit the results to POS transactions of this type.

2+|Tab: Cash journal

|**Date**
|Date and time of the POS event

|**Event**
|Indicates if the POS transaction can be categorised as revenue (**R**) or as spending (**S**).

|**Amount**
|The value of the POS transaction

|**Receipt number**
|The number of the receipt created for the POS transaction. Click on the receipt number to open a PDF file of the receipt.

|**Type**
|The type of the POS transaction

|**Cash on hand**
|The cash on hand after the POS transaction was completed

|**Order ID**
|The ID of the order created in plentymarkets.

|**VAT rate**
|The VAT rates that apply for the order

|**VAT**
|The VAT amount of the order

|**Booking text**
|The booking text for the POS transaction. For deposits and withdrawals, the booking text is the reason entered for the cash movement.
|====

[#300]
== Documenting POS transactions for German tax authorities

In many countries, POS transactions must be documented in a read-only electronic format to comply with local tax laws. These records must be accessible electronically during the legally stipulated retention period. plentymarkets provides several export formats to allow you to comply with these legal requirements. These exports are designed to conform to German tax laws. Talk to your tax consultant to determine what data you need to export and archive to comply with local tax laws.

=== Exporting POS transactions to a PDF/CSV file

You can export the POS transactions shown in the cash journal to a PDF or CSV file. Only POS transactions that match the selected search criteria are exported. Proceed as described below to export POS transactions. Once you have started the export, you need to wait two minutes before you can start another cash journal export.

[.instruction]
Exporting POS transactions to a PDF file:

. Go to **Orders » POS » Cash journal**.
. Select filters. Pay attention to the information given in <<table-POS-cash-journal-menu>>.
. Click on **Search**. +
→ The POS transactions that correspond to the search criteria entered are listed in the **Cash journal** tab.
. Click on **PDF export**. +
→ A PDF file of the filtered POS transactions is generated. This may take several minutes depending on the number of records to be exported. +
→ The PDF file opens in a separate browser window.
. **Save** the PDF file.

[.instruction]
Exporting POS transactions to a CSV file:

. Go to **Orders » POS » Cash journal**.
. Select filters. Pay attention to the information given in <<table-POS-cash-journal-menu>>.
. Click on **Search**. +
→ The POS transactions that correspond to the search criteria entered are listed in the **Cash journal** tab.
. Click on **CSV export**.
. Select and confirm a storage location for the CSV file. +
→ A CSV file of the filtered POS transactions is generated. This may take several minutes depending on the number of records to be exported. +
→ The CSV file is saved.

[#500]
=== Creating an IDEA export

German tax laws stipulate that you need to document all POS data and provide access to this data upon request. As a further requirement, the data must contain the meta information necessary for automated evaluation (see Grundsätze zur ordnungsmäßigen Führung und Aufbewahrung von Büchern, Aufzeichnungen und Unterlagen in elektronischer Form sowie zum Datenzugriff, GoBD for details). As such, plentymarkets provides a GoBD compliant export of the POS transactions. The export files allow tax auditors comprehensive and efficient analyses of your POS data. Proceed as described below to create an IDEA export.

[.instruction]
Exporting the IDEA files:

. Go to **Orders » POS » IDEA export**.
. Select the calendar year for which you want to export the data.
. Click on the gear-wheel icon to generate the export. +
→ The export is generated over night. +
→ Once data generation is complete, the status changes to **Done**.
. Click on the download icon in the **Actions** column.
. Select a storage location and confirm your selection. +
→ The IDEA files are exported and saved as a ZIP file.

[#960]
== Changing POS orders in the plentymarkets back end

An order is created for POS orders in the plentymarkets back end. After the order has been created, legally relevant order details can no longer be changed. Only order details that change in the course of processing and fulfilling orders or that document the order history can be changed:

* Language
* Status
* Amount paid
* Payment status
* Reasons for return
* Assign order to a multi-order
* Delivery address
* Emailing
* Order note
* Shipped on
* Return date

[#910]
== Decommissioning a POS

Delete a POS to permanently take the POS out of commission. After deletion, the transactions generated with the POS remain saved in the system and can be analysed for tax purposes at any time.

[NOTE]
.Points of sale in Austria
====
To take a POS with location in Austria out of commission, you need to create an end receipt (Endbeleg) once the signature unit was activated for the POS. This deletes the POS automatically.
====

[.instruction]
Deleting a POS:

. Go to **Settings » Client » Standard » POS**.
. Click on the POS. +
→ The **Basic settings** tab of the POS opens.
. In the top left corner, click **Delete**. +
→ The POS is deleted. +
**__Note:__** If the POS is located in Austria and the signature unit is activated, an <<pos/integrating-plentymarkets-pos#920, end receipt must be created in the app>>. This deletes the POS automatically.

[#860]
== Operating plentymarkets POS in Austria

According to the Cash Register Directive (Registrierkassensicherheitsverordnung, RKSV) points of sale located in Austria must be equipped with a technical signature unit that ensures that POS transaction data is temper-proof, i.e. cannot be deleted or edited. The QR code on the POS receipts provides visual proof that the POS is tamper-proof. Find out how to put a POS in operation that is to be operated in Austria.

[#870]
=== Overview: Implementing the POS

For POS located in Austria, the steps described in <<table-activating-POS-Austria>> are necessary to activate the signature unit required by the RKSV. Check the website of the link:https://english.bmf.gv.at/taxation/Cash_register_folder.html[Austrian Federal Ministry of Finance^] for detailed information on these legal requirements. This page of the manual describes only those steps necessary to implement a plentymarkets POS located in Austria. This description does not form legal or fiscal advice.

[[table-activating-POS-Austria]]
.Putting POS in operation in Austria
[cols="1,2,3"]
|====
|Order |Step |Explanation

|1.
|Get a signature card and a signature card reader
a|* plentymarkets tests with the Feitian smartcard reader link:https://en.cryptoshop.com/feitian-br301-bluetooth-reader.html[bR301^].
* plentymarkets tests with the signature cards of the service provider link:https://www.prime-sign.com/[PrimeSign^].

|2.
|Initialise the tamper-proof POS
|See <<pos/plentymarkets-pos-for-pos-users#50, Basic settings for POS>>

|3.
|Create the start receipt (Startbeleg)
|See <<pos/integrating-plentymarkets-pos#900, Creating the start receipt (Austria)>>

|4
|Register the signature card and POS at FinanzOnline
a|After creating the start receipt, register the signature card and POS at FinanzOnline. You need the following information to complete the registration process: +

Signature card (documents relating to the signature card): +

* The signature certificate's serial number
* The name of the service provider (Vertrauensdiensteanbieter) you bought the certificate from
* The signature certificate's PIN

POS (**System » System settings » Client » Standard » POS » Open POS » Tab: Basic settings**): +

* The POS identification number of the plentymarkets POS. Go to **System » System settings » Client » Standard » POS » Open POS » Tab: Basic settings** to find the **POS identification number**.
* Go to the **System » System settings » Client » Standard » POS » Open POS » Tab: Basic settings** to find the **User key AES-256**.

|5.
|Scan the start receipt with the BMF receipt validation app
|After registering the POS at FinanzOnline, scan the QR code of the start receipt. The app checks if the signature on the POS receipts is valid. +
**__Tip:__** You need to scan the start receipt within a week after registering the signature card and the POS at FinanzOnline.
|====

[IMPORTANT]
.Existing POS in Austria
====
Existing POS cannot be made tamper-proof. If you already operate a plentymarkets POS point of sale in Austria, you need to create a new POS and decommission the old POS.
====

[#900]
=== Creating the start receipt (Austria)

Now create the start receipt (Startbeleg) to put the POS into operation. You need the PIN of the signature certificate to create the start receipt. You should have received this PIN from your certificate service provider (Vertrauensdiensteanbieter) together with your signature card. Go to the POS menu of the plentymarkets app to create the start receipt. After the start receipt is created, the location country of the POS cannot be changed.

[.instruction]
Creating the start receipt (Startbeleg):

. Open the plentymarkets App.
. Go to **plentymarkets App » Settings » POS**.
. Enter the PIN of the signature certificate. You should have received this PIN from your certificate service provider (Vertrauensdiensteanbieter) together with your signature card.
. Tap **Create start receipt**. +
→ The start receipt is printed. +
→ The start receipt is saved in the cash journal and in the document archive. +
→ You can start using the POS. +
→ Receipts contain the electronic signature and the QR code. +
→ Transactions are saved in the data export protocol (DEP).

[#880]
=== Documenting POS transactions for Austrian tax authorities

The Austrian Registrierkassensicherheitsverordnung (RKSV) stipulates that receipts must be electronically signed and furnished with a QR code. This QR code contains all relevant receipt data, an encrypted revenue counter and information on the previous receipt. This reference to the previous receipt ensures that preceding receipts cannot be manipulated or deleted. In addition, a data collection protocol (Datenerfassungsprotokoll, DEP) must be kept for each POS. You need to be able to export this DEP to a local storage medium at any time.

plentymarkets provides several export formats to allow you to comply with these legal requirements. These exports are designed to conform to German tax laws. Talk to your tax consultant to determine what data you need to export and archive to comply with local tax laws.

[#890]
==== Creating a DEP export

According to §7 of the Austrian Registrierkassensicherheitsverordnung (RKSV), a data collection protocol (Datenerfassungsprotokoll, DEP) must be kept for every POS. At a minimum, the DEP must contain the signatures of any receipts resulting from cash sales and cash cancellations. The concatenation of the receipt signatures means that the DEP data is temper-proof. A separate DEP must be kept for each POS.

The DEP report is exported as a JSON file. It contains the following receipt data:

* Receipt group (Beleg-Gruppe)
* Signature certificate
* Certification authorities (Zertifizierungsstellen)
* Compact receipts (Belege-kompakt)

You must be able to export the DEP of a POS to an external disk and hand it over to tax inspectors at any time. Proceed as described below to create a DEP export:

[.instruction]
Exporting the DEP files:

. Go to **Orders » POS » DEP export**.
. Select the client (store).
. Select the POS.
. Select the first date of the range you want to export.
. Select the last date of the range you want to export.
. Click on *Download*. +
→ The file is saved in the default download folder set for the browser. +
*_Tip:_* The file name contains the export range, for example the file depExport_9-1-2017-9-2-2017.json contains data from the 9th of January to the 9th of February 2017.

==== Creating a Z2 receipt (Austria)

A Z2 receipt is a monthly signed control receipt with an amount of zero (0.00 Euro). The RKSV requires you to create a Z2 receipt at the end of each month. The Z2 report for the month of December also serves as an end of year report. You need to print and archive this yearly receipt every year and scan the barcode with the BMF receipt validation app.

===== Assigning users the right to create Z2 receipts

Users with admin rights are able to create Z2 receipts by default. *Variable* users must be assigned this right.

[.instruction]
Assigning users the right to create Z2 receipts:

. Go to *System » System settings » Settings » User*.
. Open the account of the user.
. Click on the *Right* tab.
. Click on the *Mobile* tab.
. In the *POS functions* section, activate the right *Z2 receipt (AT)*.
. *Save* the settings. +
→ The POS user <<pos/plentymarkets-pos-for-pos-users#270, can create Z2 receipts in plentymarkets POS>>.


=== SOS: The signature unit has failed. What do I need to do?

The RKSV stipulates how you need to proceed if the signature unit of the POS fails:

* If the signature unit fails, you need to move on to a POS with a functioning signature unit.
* If no other POS is available, you can temporarily use the one with the failed signature unit.
* If the signature unit fails for more than 48 hours, you need to inform the tax authorities about the beginning and end of the failure via FinanzOnline within a week.
* All unsigned receipts must be marked *Signatureinrichtung ausgefallen* (Signature unit failed). +
→ In plentymarkets POS, receipts are marked with this text automatically if the signature unit fails.
* As soon as the signature unit functions again, a collective receipt (Sammelbeleg) must be created. The signature of this receipt must contain all transactions that were generated with the POS while the signature unit was not in operation. +
→ plentymarkets POS creates a collective receipt automatically once the signature unit functions again.

[#930]
=== Creating a Kontrollbeleg (control receipt) for tax authorities

In the case of a POS inspection by Austrian tax authorities, you need to be able to generate a zero amount control receipt (Kontrollbeleg) on the spot. This control receipt allows tax inspectors to validate the signature on the POS receipts on site in your store using an app. All POS users can create such a <<pos/plentymarkets-pos-for-pos-users#270, control receipt on demand>>. No additional user rights are necessary to create the control receipt.

[#920]
=== Decommissioning a POS (Austria)

To permanently decommission a POS located in Austria, you need to create an end receipt. An end receipt is an electronically signed control receipt with an amount of zero (0.00). An end receipt can be created for POS for which a start receipt has already been created. Go to the POS menu of the plentymarkets app to create the end receipt. Once an end receipt is created, the POS can no longer be operated.

[.instruction]
Creating an end receipt (Endbeleg):

. Open the plentymarkets App.
. Go to **plentymarkets App » Settings » POS**.
. Tap **Create end receipt**. +
→ The end receipt is printed. +
→ The end receipt is saved in the cash journal and in the document archive. +
→ The POS can no longer be operated.
. Inform tax authorities that you decommissioned the POS.

//  Next: #3800
