= Integrating plentymarkets POS
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, POS, till, till system
:position: 10

plentymarkets POS allows you to integrate your bricks and mortar shop seamlessly both with your online presence and your plentymarkets system.

toc::[]
[#10]
== Supported hardware

plentymarkets POS supports the following hardware.

.POS - Supported hardware
[cols="a,a"]
|====
|Device type |Tested devices

|**Operating systems**
a|
* Android devices with OS version 4.2.2 and higher
* iOS devices (iPad, iPhone, iPod) with OS version 8 and higher

|**Scanners**
a|
* Honeywell Dolphin 75e
* Grabba S-9420f (Sled)
* Grabba 5420d (Sled)

|**Receipt printers**
a|
* EPSON TM-T88 V
* EPSON TM-T88 V-i
* EPSON TM-P80

|**Combined devices (scanner/printer)**
a|
* metric.mobile POS

|====

[#20]
== Booking a plentymarkets POS

To use plentymarkets POS, you need to book one or more POS in plentymarkets. Visit our plentymarkets POS product page to find further information on prices and conditions.

[#30]
== Setting up a POS for a client

Once you have booked a POS, you configure it in the plentymarkets back end. You assign a POS to a client by creating and configuring a POS in the **Settings » Client (store) » Standard » POS** menu. To do so, proceed as described below.

[#40]
=== Creating a POS for a client

First, create a POS for the client (store) in the plentymarkets back end.

[.instruction]
Creating a POS for a client:

. Go to **Settings » Client (store) » Standard » POS**.
. Click on **New POS**. +
→ The window **New POS** will be displayed.
. Enter a name for the POS.
. **Save** the settings. +
→ A referrer will be assigned to the POS. +
→ The POS will be created and the settings will be displayed.

Table 1 describes the menu bar of a POS.

.Menu bar of a POS
[cols="a,a"]
|====
|Setting |Explanation

|**ID**
|Unique ID of this POS. The ID is assigned automatically across clients and cannot be changed.

|**Copy**
|Creates a new POS with the settings of the POS currently displayed. Only the name and the referrer are changed. +
**__Note:__** You can only copy a POS if you have booked a sufficient number of POS.

|**Device**
|If this POS is linked to a device, the unique ID of that device is displayed.

|**Delete**
|Deletes the POS from the system.
|====

[#50]
=== Carrying out the basic settings

Now, carry out the additional settings in the **Basic settings** Tab of the POS and save these settings. Pay attention to the information given in table 3.

.**Basic settings** tab of a POS
[cols="a,a"]
|====
|Setting |Explanation

|**Name**
|Enter a name for the POS.

|**Referrer**
|When you book a POS, a new referrer is generated automatically. This allows you to identify orders generated with this POS. The POS is assigned to an available POS referrer (103.01 to 103.99) automatically.

|**Default customer**
|Select the <<pos/integrating-plentymarkets-pos#90., **Default customer created for POS orders** >> to which you want to assign orders generated with this POS.

2+|Item filters

|**Apply market availability**
|Select if the market availability is to be applied as a filter for this POS. The market availability is activated in the **Markets** area of the variation's **Availability** tab. +
Check mark = Only variations are available in this POS for which the POS's referrer has been activated in the **Markets** area of the **Availability** tab of the variation. +
No check mark = Variations for which the POS's referrer has not been activated also are available for this POS and can be accessed and sold.

|**Include active variations only**
|Select if active variations only are to be made available for this POS. Variations are activated in the **Settings** tab of the variation. +
Check mark = Only variations are available in this POS for which the option <<item/managing-items#230., **Active** >> is activated in the **Settings** tab of the variation. +
No check mark = Active and inactive variations are available for this POS and can be accessed and sold.

2+|Location

|**Name 1-4**; +
**Address 1-4**; +
**Postcode**; +
**Town**; +
**Country**
|Enter the company name and the address of the retail outlet in which the POS is to be operated. +
**__Note:__** In some countries, saving the address is a legal requirement. Contact your tax consultant for legal advice. Contact your tax consultant to provide you with legal advice as necessary.

2+|Sales warehouse

|**Sales warehouse**
|Select the sales warehouse to which you want to book orders generated with this POS. +
**__Note:__** In the POS shopping cart, items with no net stock are shown in red but can be sold. As such, mathematical overselling can occur.

2+|Repair warehouse

|**Repair warehouse**
|Select the warehouse to which you want to book returns.

|**Rack**
|Select the rack of the warehouse to which you want to book damaged returns.

|**Storage location**
|Select the storage location of the warehouse to which you want to book damaged returns. +
**__Tip:__** Click the arrow key of your keyboard twice to show a list of storage locations.
|====

[#60]
=== Managing favourites

You can add variations to the favourites list. This allows POS users to add frequently sold variations to the POS shopping cart more quickly.

[#70]
==== Saving variations as favourites

Proceed as described below to save variations as favourites.

[.instruction]
Saving variations as favourites:

. Go to **Settings » Client (store) » Standard » POS**.
. Open the POS.
. Click on the **Favourites** tab.
. Click on the **Add variation** tab. +
→ A list of the variations is displayed. If necessary, use the filter to limit the number of variations shown.
. Click on **Add variations**. +
→ The variations will be added to the list of favourites and displayed in the **Favourites** tab. +
→ Next time the POS is synchronised, the favourites are sent to the POS.

[TIP]
.POS users' favourites take priority
====
POS users can create their own favourites in plentymarkets POS. The POS user's favourites take priority over those favourites saved in the plentymarkets back end.
====

[#80]
==== Changing the order of favourites

You can change the priority of favourites using the arrow symbols in the **Favourites** tab. Move your most sold variations to the top of the list. The first variation on the list will also be the first one displayed in the favourites list of POS users. Proceed as described below to set the order in which favourites are displayed.

[.instruction]
Changing the order of favourites:

. Go to **Settings » Client (store) » Standard » POS**.
. Open the POS.
. Click on the **Favourites** tab.
. Click on the **Favourites** tab. +
→ A list of the variations of the favourites list is displayed.
. In the **Actions** column, click on the arrow of the variation you want to move. +
→ Use the up arrow to increase the priority of a variation. +
→ Use the down arrow to decrease the priority of a variation.

[#90]
==== Copying the favourites list to another POS

You can copy the favourites list of one POS to one or several other POS of the same client. This action does not delete existing favourites from the target POS. To do so, proceed as described below.

[.instruction]
Copying favourites to another POS:

. Go to **Settings » Client (store) » Standard » POS**.
. Open the POS.
. Click on the **Favourites** tab.
. Click on the **Favourites** tab. +
→ A list of the variations of the favourites list is displayed.
. Click on **Copy favourites**. +
→ The **Copy favourites** window is displayed.
. Place check marks next to the POS to which you want to copy the favourites of this POS.
. **Save** the settings. +
→ The favourites will be copied to the selected POS.

[#110]
==== Deleting variations from the favourites list

Proceed as described below to delete variations from the favourites list. Variations you delete from the list will be deleted from the POS's favourites list during the next synchronisation.

[.instruction]
Deleting variations from the favourites list:

. Go to **Settings » Client (store) » Standard » POS**.
. Open the POS.
. Click on the **Favourites** tab.
. Click on the **Favourites** tab. +
→ A list of the variations of the favourites list is displayed.
. In the variation's column, click on **Delete**. +
→ The variation will be deleted from the favourites list.

[#120]
=== Editing the receipt template

In the **Receipt** tab of the POS settings, you specify the data to be displayed on receipts. Upload an image (optional) and specify the information to be displayed in the header and footer of receipts. By default, the header contains the information saved in the **Settings » Basic settings » Master data**. You can customise this information for each POS. Use the footer for any additional information. For example, inform you customers about special offers or your online store.

[.instruction]
Editing the receipt template:

. Go to **Settings » Client (store) » Standard » POS**.
. Open the POS.
. Click on the **Receipt** tab.
. Place a check mark next to the components to be shown on the POS's receipts.
. Carry out the settings as desired. Pay attention to the explanations given in table 4.
. **Save** the settings. +
→ The receipt template will be created.

.Editing receipt template
[cols="a,a"]
|====
|Setting |Explanation

|**Image**
|Activate the option and select a PNG file to display on the receipts generated by the POS. The file must have been uploaded to the **CMS » Image gallery** menu.

|**Header**
|If the component is selected, the field's content is displayed as a header on all receipts issued by the POS. By default, the header contains the information saved in the **Settings » Basic settings » Master data**. Adjust the data if needed.

|**Footer**
|Activate option and enter additional text.

|**List identical order items**
|Select how to list several identical variations on receipts. +
**Individually** = Every variation is shown individually irrespective of the quantity being sold: +
---------------------------------------------------- +
Cat food CaTasty Deluxe           6.99 GBP +
Cat food CaTasty Deluxe           6.99 GBP +
Cat food CaTasty Deluxe           6.99 GBP +
---------------------------------------------------- +
**In aggregate** = Identical variations are shown in aggregate: +
---------------------------------------------------- +
Cat food CaTasty Deluxe          20.97 GBP +
3 x 6.99 GBP +
----------------------------------------------------
|====

[#130]
== Managing user accounts for POS

The following preparations are necessary to allow POS users access to plentymarkets POS:

* Create a user account of the user class **Variable**
* Activate rights for POS visibility
* Activate rights for POS functions (optional)
* Activate rights for the REST API
* Activate rights for visibility of key figures (optional)

The settings you need to create a user account for a POS user are described below. For general information about user accounts, refer to the <<working-with-plentymarkets/manage-users#, **Managing user accounts**  >> page of the manual.

[TIP]
.Tip: Create a role for POS users
====
To simplify rights management for POS users, create a <<working-with-plentymarkets/manage-users#70., **role** >> with those rights your POS users will need, and link this role to the user accounts of POS users.
====

[#140]
=== Creating user accounts for POS users

To give new POS users access to plentymarkets POS, create a **<<working-with-plentymarkets/manage-users#, user account  >>** of the user class **Variable** in the plentymarkets back end. To do so, proceed as described below.

[.instruction]
Creating a new POS user:

. Go to **Settings » Basic settings » User » Accounts**.
. Click on **New**. +
→ The **Create new user** window will open.
. Enter the **User name**, **Actual name** and **Password**.
. Repeat the password.
. Enter the user's email address. This will allow the user to receive messages from the system.
. Select the user class **Variable**.
. **Save** the settings.

[#150]
=== Activating REST API rights for POS users

The **REST API** tab allows you to assign rights for the communication between plentymarkets POS and the plentymarkets back end via the REST API.

[.instruction]
Activating REST API rights:

. Go to **Settings » Basic settings » User » Accounts**.
. Open a user account.
. Click on the **Right** tab.
. Click on the **REST API** tab.
. In the **Mobile** area, select the option **POS**. +
→ The necessary sub-rights are selected automatically.
. In the **Company** area, select the right **Order summary » Show order summary**.
. To give the POS user access to customer data in the POS shopping cart, also activate the following rights. +
**Account » Contact » Address » Show** +
**Account » Contact » Address » Type » Show** +
**Account » Contact » Show**
. **Save** the settings.

[#160]
=== Activating POS visibility for POS users

In the **Mobile** tab, you define which functions and key figures will be visible to users of the plentymarkets App.

[.instruction]
Activating the rights for mobile access:

. Go to **Settings » Basic settings » User » Accounts**.
. Open a user account.
. Click on the **Right** tab.
. Click on the **Mobile** tab.
. In the **Visible functions** area, activate the option **POS (beta)**.
. Activate additional rights if you want to allow the user to access other areas of the plentymarkets App.
. **Save** the settings. +
→ The user will be able to access plentymarkets POS and can create POS orders.

[#170]
=== Activating rights for optional POS functions

For POS users to edit prices, rename order items and/or give discounts, you need to assign the appropriate rights to POS users. Find out how to create roles and assign them to users **<<working-with-plentymarkets/manage-users#, here  >>**. You also activate additional App functions for users.

By assigning roles in the plentymarkets back end, you determine the POS functions that POS users are allowed to use. You also define which additional functions and key figures will be visible in the plentymarkets App.

[.instruction]
Activating rights for POS functions:

. Go to **Settings » Basic settings » User » Accounts**.
. Open a user account.
. Click on the **Right** tab.
. Click on the **Mobile** tab.
. Activate the POS functions that the POS user should have access to. Pay attention to the explanations given in table 5.
. **Save** the settings.

.Mobile rights for POS users
[cols="a,a"]
|====
|Setting |Explanation

2+|Visible functions

|**POS (beta)**
|Allows POS user access to plentymarkets POS.

2+|POS functions

|**Edit price**
|Allows POS user to edit prices of order items.

|**Rename order item**
|Allows POS user to change the name of order items.

|**Give discount**
|Allows POS user to give discounts on order items or complete orders.

|**POS**
|Allows POS user to check out items.

|**Lock POS**
|Allows POS user to lock a POS.

|**Deposits and withdrawals**
|Allows POS user to deposit and withdraw cash from the POS.

|**Cash up**
|Allows POS user to record the result of till counts.

|**Z report**
a|Allows POS user to create z reports. +
Z reports contain the following information: +

* Cash on hand: Initial cash on hand, withdrawals, deposits, expected cash on hand, actual cash on hand
* Revenue: since last Z report (sum) and since creation of POS (grand total)
* VAT report: VAT rate, VAT amount and net revenue
* Payment methods: Revenue by payment method
* Cancellations: Quantity and total
* Discounted items: Quantity and total

|**X report**
a|Allows POS user to create x reports. +
X reports contain the following information: +

* Cash on hand: Withdrawals, deposits, expected cash on hand
* Revenue: since last Z report (sum) and since creation of POS (grand total)
* VAT report: VAT rate, VAT amount and net revenue
* Payment methods: Revenue by payment method
* Cancellations: Quantity and total
* Discounted items: Quantity and total

|**Item synchronisation**
|Allows POS user to synchronise item data with the POS.

|**Upload orders**
|Allows POS user to upload POS orders to the plentymarkets back end.

|**Create return**
|Allows POS user to book returns.

|**Select customer**
|Allows POS user to look up customer data from the POS shopping cart and to select an existing customer for the order. +
**__Note:__** For this right to come into effect, you must also activate the right **Account » Contact » Address » Show address** in the **REST API** tab.

|**Cancellation**
|Allows POS user to cancel orders.
|====

=== Unlocking a POS user

If an incorrect password is entered several times in succession, the login will be blocked for the user for a certain time. As a user with admin rights, you can unlock the user manually in the plentymarkets back end.

[.instruction]
Unlocking a user:

. Go to **Settings » Basic settings » User » Accounts » Open user**.
. Click on **Unblock login**. +
→ The user will be able to log into the plentymarkets App.

[#700]
== Activating payment methods for POS orders

Now activate the payment methods you need for POS orders. Note that payment methods must be permitted for customer classes in another menu. For further information, refer to **<<payment/managing-payment-methods#30., Permitting the payment method in a customer class >>**.

Activate the following payment methods to process POS orders correctly:

* **4 » Pay upon pickup** for cash payments
* **11 » Cash sale / cash card** for card payments via external payment terminals
* **1700 » Coupon** for gift card purchases

Proceed as described below to activate these payment methods.

[.instruction]
Setting up payment methods for POS orders:

. Go to **Settings » Orders » Payment » Payment methods**.
. Place a check mark next to the setting **Also show inactive**.
. Open the folder **International**.
. Click on the payment method. +
→ The **Settings** tab will open.
. Carry out the settings. Pay attention to the information given in table 6.
. Place a check mark next to the option **Active**.
. **Save** the settings.

.Settings of payment methods for POS orders
[cols="a,a"]
|====
|Setting |Explanation

|**Language**
|Select a language. The following options are saved for the language selected: Name, Info page, Info page (internal), Logo and Upload logo.

|**Name**
|Enter the external name that should be displayed on the POS receipt and in the online store and on invoices. If no name is saved, the back end name of the payment method is displayed on the POS receipt. +
__**Tip:**__ The external name is printed on the receipt in the language that the POS user selects when logging into the POS.

|**Info page**
|Only change the default value **---** if the payment method is also used in an online store.

|**Countries of delivery**
|Select a country of delivery. +
**__Note:__** Only select countries of delivery if the payment method is also used in an online store.

|**Client (store)**
|Select the clients (stores) of the POS.

|**Logo**
|Only change the default setting **Show standard logo** if the payment method is also used in an online store.

|**Costs: Flat rate or percentage**
|Enter **0.00** for all costs to make sure no surcharges are applied to POS orders.
|====

[TIP]
.Payment method Cash sale/cash card
====
For the payment method **11 » Cash sale/cash card**, also go to **Settings » Client (store) » Standard » POS » Open POS » Tab: Payment method** and select **Unconnected device** in the **POS terminal** section.
====

[#180]
== Creating the shipping method Pickup

For POS orders to be processed in plentymarkets correctly, you need to allow the shipping method **Self pickup** for those items you want to bill through plentymarkets POS. The following preparations are necessary:

The following preparations are necessary to allow POS users access to plentymarkets POS:

* Creating a shipping service provider for **pickup**
* Creating a shipping profile **Pickup**
* Activating a shipping profile for an item

[#190]
=== Creating a shipping service provider for pickup

Proceed as described below to create shipping service provider **Self pickup**. Only settings necessary to configure this shipping service provider are described. For general information about shipping service providers, refer to the <<fulfilment/preparing-the-shipment#800., **Preparing the shipment** >> page of the manual.

[.instruction]
Creating a shipping service provider for pickup:

. Go to **Settings » Orders » Shipping » Shipping options » Tab: Shipping service provider**.
. Click on **New**. +
→ A new line will be added at the bottom of the overview.
. Carry out the settings as desired. Pay attention to the information given in table 7.
. **Save** the settings.

.Creating a shipping service provider for **pickup**
[cols="a,a"]
|====
|Setting |Explanation

|**Name (en)**
|Enter a name, e.g. **Pickup**.

|**Name (back end)**
|Enter an internal name, e.g. **Self pickup**.

|**Shipping service provider**
|Select the option **Self pickup** from the dropdown list.
|====

[#200]
=== Creating a shipping profile for pickup

Now create a shipping profile for pickup. Only settings necessary to configure this shipping profile are described. For general information about shipping profiles, refer to the <<fulfilment/preparing-the-shipment#1000., **Preparing the shipment** >> page of the manual.

[.instruction]
Creating a shipping profile for pickup:

. Go to **Settings » Orders » Shipping » Shipping options » Tab: Shipping profiles**.
. Click on **New**.
. Select the shipping service provider that you have just created from the drop-down menu.
. Carry out the settings as desired. Pay attention to the information given in table 8.
. **Save** the settings. +
→ The **Table of shipping charges** tab will be displayed.
. **Save** the settings of the **Table of shipping charges** tab without making changes.

.Creating a shipping profile **Pickup**
[cols="a,a"]
|====
|Setting |Explanation

|**Shipping service provider**
|Select the shipping service provider **Self pickup** from the dropdown list.

|**Clients (stores)**
|This option will only be displayed if at least one client (store) is set up. Select client(s) or **ALL** if you want to use the shipping profile for all online stores.

|**Order referrer**
|Select plentymarkets POS as the order referrer.

|**Blocked payment methods**
|Select the payment methods that should not be offered for the shipping profile **Self pickup**.
|====

[#210]
=== Activating a shipping profile for pickup

Now activate the shipping profile **Self pickup** for those items you want to sell with your POS.

[.instruction]
Activating a shipping profile for pickup:

. Go to **Item » Edit item**.
. Open the item.
. Click on the **Global** tab.
. Activate the shipping profile **Self pickup**.
. **Save** the settings.

You can activate the shipping profile for a large number of items simultaneously. To do so, use the <<item/managing-items#155., **item group function** >>.

[#100]
== Managing prices for POS orders

You need at least one <<item/managing-items#870., **sales price** >> for which the POS referrer is activated to save POS prices for variations. Sales prices are created and managed centrally. Save prices for your variations by linking variations to the sales price and saving a price.

[#700]
=== Creating a sales price for POS orders

If you have created sales prices with the right characteristics for POS orders already, you just need to activate the relevant POS referrer for this sales price. Proceed as described below to create a sales price for POS orders. Only settings necessary to configure POS referrers are described.

[.instruction]
Creating a sales price for POS orders:

. Go to **Settings » Item » Sales prices**.
. Click on **New**. +
→ The **New** tab will open.
. Pay attention to the explanations given in table 9 and carry out the settings as desired.
. **Save** the settings.

.Creating a sales price for POS orders
[cols="a,a"]
|====
|Setting |Explanation

|**Position**
|Enter the position number. Sales prices are sorted in ascending order in the **Sales prices** area of item variations.

|**Internal name EN**
|Enter the internal name. The internal name is used in the plentymarkets back end only and is not visible for the customers.

|**External name EN**
|Enter the external name. The external name is displayed in your online store and is visible to customers.

|**Minimum quantity**
|Enter a quantity value. Sales prices with different minimum quantities can be used to create a quantity based graduation of prices in plentymarkets.

|**Currency**
|Activate the currency in which POS orders are paid.

|**Price type**
|Activate a price type for the sales price. +
**RRP** = Activate if the sales price is the recommended retail price (RRP). If the RRP and another sales price are linked with a variation, the RRP will be displayed in the online store as red strike-through text next to the sales price. +
**Special offer** = Activate to mark the sales price as a special offer.

|**Client**
|Activate the clients (stores) for this sales price.

|**Country**
|Activate the country in which the POS is to be used.

|**Referrer**
|Activate one or several POS referrers. The sales price will be linked with the activated referrers.
|====

[#550]
=== Linking a sales price with variations

Now link the POS sales price with the main variations of the items you want to sell with your POS. The sales prices of the main variation are passed on to variations. You can also link individual sales prices with your variations.

[.instruction]
Linking a sales price with the main variation:

. Go to **Item » Edit item**.
. Open the item. +
→ The **Settings** tab of the main variation will open.
. Go to the **Sales prices** area and select the sales price from the drop-down menu.
. Select whether the price is net or gross.
. Select a price calculation if needed.
. Click on **Add**. +
→ The sales price will be added and displayed in the list.
. Enter a value into the **Price** field.
. **Save** the settings. +
→ The prices are passed to the variations of the item. Save a different price for variations with a different price.

[#90]
== Creating a default customer for POS orders

For POS orders to be saved in plentymarkets correctly, every order must be associated with a customer. As such, you need to create an anonymous default user. Proceed as described to create a default customer for POS orders. Only settings necessary to configure the default customer are described. For general information about creating customers, refer to the <<crm/managing-customer-data#, **Managing customer data**  >> page of the manual.

[IMPORTANT]
.Agree on your settings for the default customer for POS orders with your tax adviser.
====
Before setting up default customers for POS orders, discuss the settings to be used with your tax adviser.
====

[.instruction]
Creating a default customer for POS orders:

. Go to **Customers » Edit customers**.
. Click on **New**.
. Carry out the settings as desired. Pay attention to the information given in table 10.
. **Save** the settings.
. Go to **Settings » Client (store) » Standard » POS » Open POS » Basic settings**.
. Enter the ID of the default customer into the **Default customer** field.
. **Save** the settings.

.Creating a default customer for POS orders
[cols="a,a"]
|====
|Setting |Explanation

|**Company**
|Enter a company name, e.g. plentymarkets POS.

|**Form of address**
|Select the option **Company** from the dropdown list.

|**Street, +
Postcode**, +
**Town**
|Enter the customer's street, postcode and town.

|**Country**
|Select the country in which the POS is to be used from the dropdown list. Default setting is based on the option **Where is the company based (for financial accounting purposes)** in the **<<working-with-plentymarkets/basic-settings/master-data#, Settings » Basic settings » Master data  >>** menu.

|**Client**
|Select a client from the dropdown list if you do not want to assign this POS to the default client.

|**Type**
|Select the option **Customer** from the dropdown list.
|====

[#220]
== Creating a dummy item for cash sales

You may find that items are to be sold that do not have a data record in plentymarkets. Create a dummy item to be able to sell these items anyway. The POS user then adds the dummy item to the POS shopping cart and edits the name and price of the item. To do so, you need a dummy item for each of the VAT rates that apply to the products in your portfolio. When you create this item, go to the **Settings** tab of the variation and for the option **Limitation** select the setting **Do not administer stock for this variation**. Save the item for this setting to take effect. For further information about creating items, refer to the <<item/managing-items#, **Managing items**  >> page of the manual.

[IMPORTANT]
.Activating rights for POS functions
====
To allow POS users to work with dummy items, go to **Settings » Basic settings » User » Accounts » Open account » Tab: Right » Tab: Mobile**. In the **POS functions** area, activate the rights **Edit price** and **Rename order item**.
====

== Booking outgoing items automatically

You can automate <<stock-management/outgoing-items#, **stock management**  >> by setting up event procedures.

=== Book outgoing items

Create the event procedure described below to book outgoing items when a POS order is created:

[.collapseBox]
.Booking outgoing items for POS orders:
--
. Go to **Settings » Orders » Event procedures**.
. Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
. Enter the name.
. Select the **Event** listed in table 11.
. **Save** the settings.
. Carry out the settings as desired. Pay attention to the information given in table 11.
. Place a check mark next to the option **Active**.
. **Save** the settings.
--
.Event procedure for booking outgoing items for POS orders
[cols="a,a,a"]
|====
|Setting |Option |Selection

|**Event**
|**Documents: Receipt generated**
|

|**Filter 1**
|**Order &gt; Order type**
|**Order**

|**Filter 2**
|**Order &gt; Referrer**
|Select the POS referrers to book outgoing items for.

|**Procedure**
|**Order &gt; Book outgoing items**
|
|====

[#600]
== Installing the plentymarkets app

Now, install the plentymarkets App on your mobile device.

[WARNING]
.Offline orders are deleted when you uninstall the app
====
If your internet connection is down, POS orders are saved on your device and uploaded to plentymarkets once connection returns. If you uninstall the app on your device before all orders were uploaded to plentymarkets, the orders saved on your device will be deleted permanently and cannot be recovered by you or the plentymarkets support team. As such, check that no offline orders exist on your device before uninstalling the app.
====

[#230]
== Linking a POS to a device

=== Linking a POS to a device

Proceed as described below to link a POS to a device.

[.instruction]
Linking a POS to a device:

. Open the plentymarkets App on the device that you want to link to this POS.
. Go to **plentymarkets App » Settings » POS beta**.
. Carry out the settings as desired. Pay attention to the information given in table 12.
. **Save** the settings. +
→ Device and POS will be linked.

.Linking a POS to a device
[cols="a,a"]
|====
|Setting |Explanation

|**Client (store)**
|Select the client for which the POS was created.

|**POS**
|Select POS.

|**Price**
|Select if orders are to be created gross or net.

|**Printer**
|Enter the IP address of the receipt printer. +

//  b><i>Tipp:</i></b> Auf <strong>Testbeleg drucken</strong> tippen, um einen Testbeleg zu drucken.</strong

|**Automatic printing**
|**Off** = Printing of POS receipts must be triggered manually. +
**On** = Default setting. POS receipts are printed automatically once a payment process is complete.

|**Schema** +
(tablets only)
|**Smartphone** = Optimised view for smartphones; landscape or portrait. +
**Tablet** = Optimised view for tablets; landscape only.
|====

[#240]
=== Unlinking a POS from a device

You can unlink a POS from a device. Instead, either link a different POS to the device or select no POS.

[.instruction]
Unlinking a POS from a device:

. Open the plentymarkets App.
. Go to **plentymarkets App » Settings » POS beta**.
. For the setting **POS**, select a different POS or the empty option.
. **Save** the settings. +
→ Device and POS will be unlinked.

[IMPORTANT]
.Unlinking is only possible on the mobile device
====
You can only unlink a POS from a device in the settings of the mobile device. Contact the plentymarkets Support to unlink the device in case of device failure or loss.
====

[#250]
== Emailing receipts to customers

plentymarkets allows you to set up an event procedure that automatically emails POS receipts to the email address saved for a customer record. First create an email template with the PDF attachment **Receipt**. Then, you create an event procedure. Note that for POS orders created in offline mode, the event procedure will only take effect once the POS order is uploaded to the plentymarkets back end.

[#260]
=== Creating an email template

First, create an <<crm/sending-emails#1200., **email template** >> that is sent when a receipt is generated.

[.instruction]
Creating an email template:

. Go to **Settings » Client (store) » Standard » Email » Templates**.
. Click on **New email template**. +
→ The **New email template** window will open.
. Enter a name for the template.
. Select an owner or the setting **All** from the drop-down list **Owner**.
. Click on **Save**. +
→ The email template is created and saved in one of the three folders based on the owner you selected.
. Select the PDF attachment **Receipt**.
. Carry out the additional settings. Pay attention to the information on <<crm/sending-emails#1200., **creating a new creating a new email template** >>.
. **Save** the settings.

[#270]
=== Creating an event procedure

Now, create an event procedure that triggers an email to the customer when a receipt is generated.

[.collapseBox]
.Setting up an event procedure
--
. Go to **Settings » Orders » Event procedures**.
. Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
. Enter a name.
. Select the **event** listed in table 13.
. **Save** the settings.
. Carry out the settings as desired. Pay attention to the information given in table 13.
. Place a check mark next to the option **Active**.
. **Save** the settings.
--
.Event procedure for automatically sending receipts
[cols="a,a,a"]
|====
|Setting |Option |Selection

|**Event**
|**Documents: Receipt generated**
|

|**Filter 1**
|**Order &gt; Order type**
|**Order** +
**Return**

|**Filter 2**
|**Order &gt; Referrer**
|Select the POS for which you want to email receipts.

|**Procedure**
|**Customer &gt; Send email**
|**Template**: Select the email template you set up for sending receipts +
**Recipient**: Select the option **Customer**
|====

[#400]
== Searching POS transaction in the cash journal

plentymarkets documents all POS transactions to allow you to comply to German legal requirements. Use the **Orders » POS » Cash journal** menu to search, show or export POS transactions. Use the filters in the **Filters** tab to limit the number of POS transactions shown in the cash journal to those meeting specific criteria. The POS transactions found are listed in the **Cash journal** tab. By default, results are sorted by date. Proceed as described below to search POS transactions in the POS journal.

[.instruction]
Searching for POS transaction in the cash journal:

. Go to **Orders » POS » Cash journal**.
. Select the filters. Pay attention to the information given in table 14.
. Click on **Search**. +
→ The POS transactions that correspond to the search criteria entered will be listed in the **Cash journal** tab.

.**Cash journal** menu
[cols="a,a"]
|====
|Setting |Explanation

2+|Tab: Filter

|**Search**
|Click on **Search** without selecting any filter settings. This will display all POS transactions. Alternatively, limit the search results by using filters and click on **Search**. The POS transactions found are listed in the **Cash journal** tab.

|**Reset**
|Resets the selected filter criteria.

|**Receipt number: from**; +
**Receipt number: to**
|Enter the receipt numbers of the first and last receipt to search for receipts of a specific receipt number range. To show a single receipt, enter the same receipt number in the field **Receipt number: from** and the field **Receipt number: to**.

|**POS**
|Select a POS from the drop-down list to limit the results to POS transactions that were carried out with a specific POS.

|**Client (store)**
|Select a client (store) from the drop-down list to limit the results to POS transactions that were carried out for a specific client.

|**User**
|Select a user from the drop-down list to limit the results to POS transactions that were carried out by a specific user.

|**Payment method**
|Select a payment method from the drop-down list to limit the results to POS transactions that were carried out using a specific payment method. Only active payment methods are listed.

|**Period**
|Select a period to limit the POS transactions shown to those that were created during this period. +
To only show receipts of a custom period, select **Date selection**. Then select the starting date from the calendar in the **from** field and the ending date from the calendar in the **to** field.

|**Type**
|Select a type from the drop-down list to limit the results to POS transactions of this type.

2+|Tab: Cash journal

|**Date**
|Date and time of the POS event

|**Event**
|Indicates if the POS transaction can be categorised as revenue (**R**) or as spending (**S**).

|**Amount**
|The value of the POS transaction

|**Receipt number**
|The number of the receipt created for the POS transaction. Click on the receipt number to open a PDF file of the receipt.

|**Type**
|The type of the POS transaction

|**Cash on hand**
|The cash on hand after the POS transaction was completed

|**Order ID**
|The ID of the order created in plentymarkets.

|**VAT rate**
|The VAT rates that apply for the order

|**VAT**
|The VAT amount of the order

|**Booking text**
|The booking text for the POS transaction. For deposits and withdrawals, the booking text is the reason entered for the cash movement.
|====

[#300]
== Documenting POS transactions for German tax authorities

In many countries, POS transactions must be documented in a read-only electronic format to comply with local tax laws. These records must be accessible electronically during the legally stipulated retention period. plentymarkets provides several export formats to allow you to comply with these legal requirements. These exports are designed to conform to German tax laws. Talk to your tax consultant to determine what data you need to export and archive to comply with local tax laws.

=== Exporting POS transactions to a PDF/CSV file

You can export the POS transactions shown in the cash journal to a PDF or CSV file. Only POS transactions that match the selected search criteria are exported. Proceed as described below to export POS transactions. Once you have started the export, you need to wait two minutes before you can start another cash journal export.

[.instruction]
Exporting POS transactions to a PDF file:

. Go to **Orders » POS » Cash journal**.
. Select filters. Pay attention to the information given in table 14.
. Click on **Search**. +
→ The POS transactions that correspond to the search criteria entered will be listed in the **Cash journal** tab.
. Click on **PDF export**. +
→ A PDF file of the filtered POS transactions is generated. This may take several minutes depending on the number of records to be exported. +
→ The PDF file opens in a separate browser window.
. **Save** the PDF file.

[.instruction]
Exporting POS transactions to a CSV file:

. Go to **Orders » POS » Cash journal**.
. Select filters. Pay attention to the information given in table 14.
. Click on **Search**. +
→ The POS transactions that correspond to the search criteria entered will be listed in the **Cash journal** tab.
. Click on **CSV export**.
. Select and confirm a storage location for the CSV file. +
→ A CSV file of the filtered POS transactions is generated. This may take several minutes depending on the number of records to be exported. +
→ The CSV file is saved.

[#500]
=== Creating an IDEA export

German tax laws stipulate that you need to document all POS data and provide access to this data upon request. As a further requirement, the data must contain the meta information necessary for automated evaluation (see Grundsätze zur ordnungsmäßigen Führung und Aufbewahrung von Büchern, Aufzeichnungen und Unterlagen in elektronischer Form sowie zum Datenzugriff, GoBD for details). As such, plentymarkets provides a GoBD compliant export of your POS transactions. The export files allow tax auditors comprehensive and efficient analyses of your POS data. Proceed as described below to create an IDEA export.

[.instruction]
Exporting the IDEA files:

. Go to **Orders » POS » IDEA export**.
. Select the calendar year for which you want to export the data.
. Click on the gear-wheel icon to generate the export. +
→ The export is generated over night. +
→ Once data generation is complete, the status changes to **Done**.
. Click on the download icon in the **Actions** column.
. Select a storage location and confirm your selection. +
→ The IDEA files are exported and saved as a ZIP file.

//  Next: 800.
