= Best Practices: POS
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, POS, plentyPOS, Gift cards, selling gift cards, best practice
:position: 30
:url: pos/pos-best-practice

Best practices for the POS can be found on this page.

[#100]
== Completing online orders at the POS (click & collect)

Click & collect means that customers can order online and pick up at the retail store. The order is loaded into plentymarkets POS and completed at the POS. As such, the following scenarios are possible at the POS:

* The order was placed and paid for online. The items are picked up at the retail outlet.
* The order was placed online. The items are picked up and paid for at the retail outlet.

This best practice describes the preparations necessary for completing online orders at the POS.

=== Shipping settings

If you already have a POS, you have already created a shipping service provider *Self pickup* and a shipping profile *Self pickup*. However, we recommend that you create a separate shipping service provider and shipping profile for click & collect.

[#190]
==== Creating a shipping service provider for store pickup

Proceed as described below to create shipping service provider for store pickup. In this best practice, we’ll call this shipping service provider *Store pickup*. Of cause you can also use a different name.

[.instruction]
Creating a shipping service provider for store pickup:

. Go to *System » System settings » Orders » Shipping » Settings » Tab: Shipping service provider*.
. Click on *New*. +
→ A new line is added at the bottom of the overview.
. In the *Name (en)* row, enter the name *Store pickup*.
. In the *Name (back end)* row, enter the name *Store pickup*.
. Select *Self pickup* from the *Shipping service provider* drop-down list.
. *Save* the settings.

[#200]
==== Creating a shipping profile for store pickup

Now create a shipping profile for store pickup. In this best practice, we’ll call this shipping profile *Store pickup*. Of cause you can also use a different name.

[.instruction]
Creating a shipping profile for store pickup:

. Go to *System » System settings » Orders » Shipping » Settings » Tab: Shipping profiles*.
. Click on *New*.
. From the drop-down list *Store pickup*, select the shipping service provider you just created.
. For the *Name (en)* option, enter the name *Store pickup*.
. For the *Name (back end)* option, enter the name *Store pickup*.
. Activate the *Client (store)* for which you want to allow store pickups.
. Activate the *Order referrer*. We recommend the referrers *0 Manual entry* and the *Client (store)*.
. **Save** the settings. +
→ The **Table of shipping charges** tab is displayed. +
*_Note:_* No shipping costs are usually charged for store pickup. As such, we won’t save any <<fulfilment/preparing-the-shipment#1000, shipping costs>> in this best practice.
. *Save* the settings of the *Table of shipping charges* tab without making changes.


[#210]
==== Activating the shipping profile for store pickup for an item

Now activate the shipping profile *Store pickup* for those items that can be ordered online and picked up at the retail store.

[.instruction]
Activating the shipping profile for store pickup for an item:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Global* tab.
. Activate the shipping profile *Self pickup*.
. *Save* the settings.

You can activate the shipping profile for a large number of items simultaneously. To do so, use the <<item/managing-items#155, item group function>>.

=== Activating payment method for payment at pickup

Now activate the payment method *Cash payment* to allow customers to pay for online orders at the time of pickup.

* Provision the plugin link:https://marketplace.plentymarkets.com/en/plugins/payment/payuponpickup_4757[Pay upon pickup] for the client. +
→ By default, the payment method is called Cash payment in the online store. However, you can change the name of the payment method, for example to Store pickup.

=== Specifying stock movements (version 1.9.2 and higher)

Now specify how stock levels of online orders are to be treated when they are picked up at the retail store.

[.instruction]
Specifying stock movements for online orders:

. Go to *System » System settings » Client » Select client » POS*.
. Open the POS. +
→ The *Settings* tab opens.
. The option *External order: Book outgoing items automatically* is activated by default. As such, items are booked out of the warehouse automatically after payment has been received. Deactivate the option to book out items only if the POS user taps the *Book outgoing items* button. +
*_Tip:_* Only deactivate the option if you have a separate pickup station for items, i.e. if you do not hand over items at the POS directly after payment. Educate POS users on when they should tap the button.
. If items are to be booked out of the sales warehouse of the POS, activate the option *Outgoing items for external orders: Book items out of POS sales warehouse*. +
→ If you do not activate the option, the items are booked out of the warehouse that was assigned to the order when the order was created.
. *Save* the settings.

////
== Stock management

Event procedures for outgoing items

* When delivering to retail store
* When handing items over to customer
* When retail store = warehouse

Items are booked out: The items are booked out of the warehouse specified in the order.

Auftrag sollte nicht in den Prozessen verarbeitet werden.

Nicht bearbeiten: Im Prozess nach Versandprofil filtern und Selbstabholer ausschließen, damit Warenausgang nicht gebucht wird.
////
