= Importing data with the dynamic import
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Importing data, import data, data import, synchronise, synchronisation, data format, data formats, dynamic import, mapping, matching, import option, import data
:description: Learn how to create data formats and how to use the dynamic import.
:position: 20
:url: data/export-import/importing-data
:id: XS9XT6R

This page of the manual describes different ways of manually importing data using the dynamic import. Importing data is recommended if you want to add new items, customer data or stock etc. to your plentymarkets system and you already have this data available in digital format.


[TIP]
.Use ElasticSync
====
The import mechanisms described on this page are outdated. Use <<en/data/importing-data/ElasticSync#, ElasticSync>> to import data into plentymarkets.
====


[#5]
== Importing data with the dynamic import


[#10]
== Creating data formats

The data format that you want to import must correspond with the configuration of the data format in plentymarkets. This ensures that your data is assigned correctly. This also includes that the spelling of the data fields matches the spelling in plentymarkets. You find the names of the data fields on the sub-pages of the <<data/export-import/data-formats#, Data formats>> page of the manual. Pay attention to the information about mandatory fields and matching fields. You can create the import file with the help of a spreadsheet program.

You can facilitate this work step considerably by exporting the data format in a file in advance. Then you edit your data in the file and re-import it into your system. This procedure is only possible for data formats that are suitable for both import and export. For further information about handling export and import files, refer to the chapter <<data/export-import/exporting-data#05, Customising a file for data exchange>> on the <<data/export-import/exporting-data#, Exporting data>> page of the manual. Proceed as described below to export your data in a file:

[.instruction]
Creating a data format:

. Go to *Data » Dynamic export*.
. Click on the *New data format* tab.
. Select a *Data format type* from the drop-down list.
. If needed, change the *Data format name* that is automatically created.
. Activate the data fields that should be contained in the export file.
. Select an *import procedure* per data field. +
→ Information about the matching fields can be found on the sub-pages of the <<data/export-import/data-formats#, Data formats>> page of the manual.
. If needed, select *Filters* or *Procedures*.
. *Save* the data format. +
→ The order of the data fields will change according to the values in the *Position* column.

[#25]
[TIP]
.Matching and mapping
====
For the data fields of a data format, the import procedures *Synchronisation* and *Import* are available.  +
With the setting *Import*, the data is imported regardless of whether data is already available in the system or not. This means that data might be overwritten during the import. With the setting *Synchronisation*, the data field is synchronised with the data that is already available in the system before the import is carried out. This means that data is only imported if no data is available in the system at all.
====

[#20]
== Carrying out the dynamic import

The dynamic data import takes place within the *Data exchange » Import » Dynamic import* menu. Here, you can import either data formats that you created in the *Data exchange » Export » Dynamic export* menu (so called customer formats) or data formats that you created yourself. In addition to the customer formats, two special import formats are available in the *Data » Dynamic import* menu in the drop-down menu *Format*:

* the *ItemParcelServicePreset* special format that you use to import shipping profiles
* the *IncomingItems* special format that you use to import incoming items

The special formats are import formats and are therefore only available in the *Data exchange » Import » Dynamic import* menu. You import the special formats exactly the same way as you import the other data formats. How to import data formats is described in the following.

[NOTE]
.Check and adjust names in the column headers
====
If you want to import data from an external system or a file that you created yourself, the column headers in the file must exactly match the spelling of the data fields (field names) in plentymarkets. +
If plentymarkets cannot assign the import to the selected export type, the import is cancelled and an error message is displayed. You find the error message in the *Processing status* area. Check the column headers that are listed in the file to be imported and make changes to these headers if necessary.
====

[.instruction]
Importing data with the dynamic import:

. Go to *Data » Dynamic import*.
. Carry out the settings. Pay attention to the information given in <<table-settings-menu-data-dynamic-import>>. +
*_Note:_* A maximum of 6000 data records can be imported during a single import.
. Click on *Import*.
. Check whether the imported data was saved in the system.

[IMPORTANT]
.processing status
====
After you have imported the file, you receive a message in the *Processing status* area. In case the data lines were successfully imported, the number of the imported lines is displayed. If an error occurs, the entry *0* is displayed along with an error message. Check the field separator or encoding of the file. The file should always be UTF-8 encoded.
====

Note that the available settings depend on the data format you have selected for the import. For the data format *Stock* e.g., you select a *warehouse* and the *barcode* instead of a mapping option. The settings as they are described in <<table-settings-menu-data-dynamic-import>> are displayed for most of the data formats.

[[table-settings-menu-data-dynamic-import]]
.Settings in the *Data » Dynamic import* menu¤[cols="1,3"]
|====
|Setting |Explanation

|*Field separator*
|Select the field separator that is set in the import file.

|*Format*
|Select the data format that you prepared for the data import. +
*_Note:_* Depending on which date format you select here, change the following settings.

|*If there is no match during the synchronisation*
|Select one of the following options:  +
*Create a new data record* = If the data that you want to import does not exist in the system yet. +
*Skip data record* = If existing data should not be overwritten during the synchronisation.

|*File*
|Select the import file from your computer.
|====





[#210]
== Importing eBay listings

You import eBay listing in the *Data » eBay listings* menu. Both a set of item master data and a listing are created in plentymarkets. The *Processing status* area gives you access to the current status of the process during import. How to import listings is described on the <<omni-channel/multi-channel/ebay/ebay-setup#, eBay>> page of the manual in the <<omni-channel/multi-channel/ebay/ebay-setup#11000, Importing eBay listings>> chapter.


////
== Example of use: Creating items and editing item data

Use the *Data* menu to create items or to edit existing item data. This function is useful if you want to import item lists from your supplier into plentymarkets or adjust your item prices. First, create the data format *Item* in the *Data » Dynamic export* menu. Then export the data in a file and edit the data within the file. Afterwards, go to *Data » Dynamic import* and import the file.






[#120]
== Example of use: Importing stock

You can also import the entire stock and thus overwrite the current physical stock in your plentymarkets system. To do so, use the data format <<data/export-import/data-formats/stock#, Stock>>.

[WARNING]
.Stock is deleted
====
During this process, the current physical stock is replaced with the data that is imported. In other words, your entire stock is deleted. Reserved stock remains unaffected.

If you do not want to import your entire stock, but would rather add incoming stock via data import, use the special format *IncomingItems*.
====

If you plan on editing the import file before you import it, use the explanations on the data fields given below as a reference. <<table-data-fields-data-format-stock>> lists some of the data fields that are contained in the exported file.

[[table-data-fields-data-format-stock]]
.Dynamic import; data fields of the data format *Stock*
[cols="1,3"]
|====
|Field name |Explanation

|*ItemID*
|Item ID

|*VariationEAN*
|EAN code of the variation

|*PurchasePrice*
|Purchase price

|*VariationNo*
|Variation number

|*LocationID*
|Storage location ID +
Enter the number 0 here if no storage location is available or if you do not want it to be assigned.

|*Stock*
|Stock

|*WarehouseID*
|Warehouse ID

|*VariationString*
|System name hash of the attributes and values. +
*_Example:_*"Colour:Blue;Size:XXL" +
The names of the attributes and values are used.
|====

[.instruction]
Carrying out the data import:

. Go to *Data » Dynamic import*.
. Carry out the settings. Pay attention to the information given in <<table-import-options-data-format-stock>>.
. Click on *Import*.

[[table-import-options-data-format-stock]]
.Dynamic import; import options for the data format *Stock*
[cols="1,3"]
|====
|Setting |Explanation

|*Field separator*
|Select the separator.

|*Format*
|Select the data format *Stock* for the import.

|*Warehouse*
|Select the warehouse for the import.

|*Barcode*
|Select the barcode for the import.

|*File*
|Select the file for the import.
|====

You receive a detailed message about the data import in the *Processing status* section in the *Data exchange » Import » Dynamic import* menu. The format, file name, user name and import date e.g. are displayed in this section.
////
