= Setting up a catalog for exporting variation data to Amazon (BETA)
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Amazon, item export, variation export, Amazon catalog, Amazon catalogue, Export Amazon, Amazon Export, variation export, exporting item data to Amazon, exporting variation data to Amazon
:description: Multi-Channel in plentymarkets: Create a catalogue to export variation data to the market Amazon.
:position: 12
:url: markets/amazon/variation-data-export
:id: EABQJ7Y
:author: team-multi-channel

The Amazon catalogue is here! Amazon is the first big market to be offered for variation export via catalogues. However, if you prefer you can still use the old export.

[#100]
== Why catalogues?

* Your catalogues will quickly become the control centre for all your variation exports.
* The catalogue provides the data structure of the flatfile. As such, you know exactly which variation data is necessary to sell your products on Amazon.
* You decide what variation data is exported for each flatfile and each platform. At the same time, suggestions help you to set up additional catalogues more quickly: Because once you have mapped a source to a field, this mapping is suggested to you next time.
* You can transmit data more flexibly because you can map fields in any way you like.

[IMPORTANT]
.Amazon catalogues are a new feature!
====
Catalogues for exporting variation data to Amazon are a new feature.
====

[#200]
== Important information on Amazon catalogues

* A separate catalogue is created for each combination of an Amazon account, an Amazon platform and a flatfile.
* Characteristics and free text fields cannot be transmitted to Amazon in catalogues. You can create properties for the mandatory field of a flatfile in the assistant for the Amazon catalogue. You can create and map additional properties at any time.
* A separate flatfile exists for Amazon Business (B2B). As such, you need to create a separate catalogue for Amazon Business.
* BMVD export categories are ignored in the catalogues.
* All mandatory fields of the flatfile are mapped in the assistant. You can map additional fields in the *Data » Catalogues* menu after the catalogue is created.
* Do you already sell on Amazon and export variation data to the market? The old variation export for the combination of Amazon account, Amazon platform and flatfile is deactivated automatically when you activate an Amazon catalogue for this combination.

[#300]
== Important preparation

* Go through the assistant *Base settings - Amazon*, before you create the first catalogue. In that catalogue, you save the Amazon account, and select the country platforms on which you want to sell your products.
* Before you create your first Amazon catalogue, familiarise yourself with <<daten/daten-exportieren/kataloge-verwalten#, how catalogues are used in plentymarkets>>.

////
[#1300]
== Linking categories

include::_textblocks/instructions/amz-link-categories.adoc[]
////

[#400]
== Creating a catalogue for variation export

Amazon catalogues are created with the *Creating catalogues - Amazon* assistant in the *Setup » Assistants » Omni-Channel* menu. Experts can create catalogues in the *Data » Catalogues* menu.

* A separate catalogue is created for each combination of an Amazon account, an Amazon platform and a flatfile.
* All mandatory fields of the flatfile are mapped in the assistant.
* Optional fields are mapped in the *Data » Catalogue* menu once the catalogue has been created.

[IMPORTANT]
.Free text fields and characteristics are not supported
====
Catalogues do not support free text fields or characteristics. Only properties can be transmitted to Amazon in catalogues. You can create properties for all mandatory fields of a flatfile in the assistant.
====

[#500]
=== Creating a catalogue in the assistant

The assistant *Create catalogues - Amazon* allows you to create a catalogue for exporting your variation data to Amazon in a few easy steps. You specify a name for the catalogue and decide on the flatfiles and the Amazon platform to use. You also map all mandatory fields in the catalogue.

[TIP]
.One catalogue per account, plattform and flatfile
====
You need a separate catalogue for each combination of Amazon account, Amazon platform and flatfile. This is made easy thanks to suggestions: Because once you have mapped a source to a field, this mapping is suggested to you next time.
====

[.instruction]
Creating a catalogue in the assistant:

. Go to *Setup » Assistants » Omni-Channel*.
. Click on the assistant *Create catalogues - Amazon*.
. Click on *New configuration* (icon:plus[role="green"]). +
*_Tip:_* The step *New configuration* is skipped when you create the first catalogue.
. Follow the instructions on the screen. If you need additional information about one of the options, expand the info box below (icon:chevron-down[role="darkGrey"]).
. Check the summary for any possible errors and click on icon:check[role="green"] *Finalise*. +
→ The catalogue is created.
. *_Optional:_* Map additional, <<#600, optional fields>> in the *Daten » Kataloge* menu.

[.collapseBox]
.Options in the assistent
--
[[table-amazon-catalogue-assistant]]
[width="100%"]
[cols="1,3"]
|====
|Setting |Explanation

2+|Step: User account

| *User account*
a| Select the amazon account from the drop-down list. A separate catalogue is created for each combination of one Amazon account, one Amazon platform and one Amazon flatfile. You can only select Amazon accounts that are saved in your plentymarkets system. If the account is not shown, go to *Setup » Markets » Amazon » Settings* and create a <<markets/amazon/amazon-setup#300, new account>> or use the assistant *Base settings - Amazon*.

*_Note_*\: <<crm/managing-contacts#15, Create the necessary customer classes>> in advance, if they don’t already exist in your plentymarkets system.

2+|Step: Name, flatfile and platform

| *Name*
| Enter a name for the catalogue. If no name is entered, a name is generated automatically.

| *Activate item export*
| Activates the export. The export is deactivated by default. +
*_Note:_* Check all mappings before activating the export. You can also activate the catalogue later in the *Data » Catalogue* menu.

| *Fulfilment method*
| Select if only MFN variations, only FBA variations or both are to be exported in this catalogue. +
*Transmit MFN and FBA variations* (default setting) = MFN variations and FBA variations are transmitted (recommended). +
*Only transmit MFN variations* = Only variations that you ship yourself are transmitted. As such, a separate catalogue must be created for FBA variations. +
*Only transmit FBA variations* = Only variations shipped by Amazon are transmitted. As such, you need to create a separate catalogue for variations that you ship yourself. +
*_Tip:_* We recommend that you manage both fulfilment methods in the same catalogue.

| *Amazon flatfile*
| Select the flatfile to use for this catalogue. +
A flatfile is a file template for specific product categories provided by Amazon. This file template specifies the variation and stock data that needs to be exported to Amazon. +
*_Note:_* Only flatfiles for platforms that are activated for the Amazon account that you selected in step 1 are shown. If necessary, activate <<markets/amazon/amazon-setup#300, additional platforms for the Amazon account>>.

| *Amazon platform* +
(only shown once a flatfile is selected)
| Select the Amazon platform from the drop-down list. +
*_Note:_* Only Amazon platforms that are activated for the Amazon account that you selected in step 1 are shown. If necessary, activate <<markets/amazon/amazon-setup#300, additional platforms for the Amazon account>>.

| *Flatfile version*
| Indicates the version of the flatfile used.

2+|Step: Setting up the catalogue

| *Setting up the catalogue*
a| Map plentymarkets data fields with the data fields of the selected Amazon flatfile. All data fields shown in this step are mandatory fields and need to be mapped. You can map additional fields in the *Data » Catalogue* menu when the assistant is completed.

* *Create property* = Creates a new property and maps this property to the data field. The properties are grouped in the property group *Amazon Catalog* of the *Setup » Settings » Properties » Groups* menu. The name of the property is based on the source in the flatfile. +
* *Select data source* = A data field in plentymarkets is transmitted to Amazon. Select the data field from the drop-down list *Select source*. +
*_Note:_* Fields with the option *Map data source manually* cannot be mapped in the assistant. These fields must be mapped manually once the catalogue has been created.
* *Manually map data source* = These fields are not linked in the assistant. You need to map these fields in the catalogue after it is created.

*_Tip:_* If you have created a catalogue already, suggestions are shown in every catalogue after that. For each field the source that you mapped to it most often is suggested.

2+|Step: Summary

| Summary
| Shows a summary of the catalogue settings. Expand (icon:chevron-down[role="darkGrey"]) and check your settings.
|====
--

[#600]
=== Mapping optional data fields (not in catalogue)

The assistant allows you to map all mandatory fields for the selected flatfile. However, you can also map additional fields to send even more information about your products to Amazon.

[.instruction]
Mapping optional data fields:

. Go to *Data » Catalogues*. +
→ The catalogues are listed.
. Click on the catalogue. +
→ The catalogue opens. +
*_Note:_* The catalogue appears to be empty at first. Some flatfiles contain a lot of data. As such, it can take several minutes before the data fields of a flatfile are loaded and shown in the catalogue.
. Map additional fields to sources.
. *Save* (icon:save[set=plenty]) the catalogue.

[#700]
== Lining properties created in the assistant to variations

Find out how to link properties to variations on the <<item/managing-items#4900, Manually creating items>> page of the manual.

[TIP]
.Use property groups
====
Properties created in the assistant are automatically added to the property group *Amazon catalog* of the *Setup » Settings » Properties » Groups* menu. Check this group to see if you need to link any new properties to your variations.
====

[#800]
== Activating the variation export

You have checked all mappings and now want to start the export of your variation data to Amazon?

* <<#900, Activating a catalogue for an existing export>>
* <<#1000, Activating a catalogue for a new export>>

[#900]
=== Activating a catalogue for an existing export

If you created a catalogue for a combination of Amazon account, Amazon platform and flatfile that you already use, the export is automatically switched to catalogue as soon as you activate the catalogue.

[.instruction]
Activating a catalogue for an existing export:

. Go to *Data » Catalogues*. +
→ The catalogues are listed.
. Find the row of the catalogue and move the toggle button (icon:fa-toggle-on[]) in the *Active/Inactive* column to the right. +
→ The catalogue is active. +
→ The data is transmitted to Amazon once a day at night. +
*_Tip:_* If incorrect data was transmitted to Amazon during the automatic export, you can correct the mappings in the catalogue, <<#2800, export a CSV file of the catalogue>> and then manually upload the file to Amazon.

[#1000]
=== Activating a catalogue for a new export

When you create a catalogue for a Amazon account, platform and flatfile that you are not currently using already, some additional settings are necessary.

[.instruction]
Activating a catalogue for a new export:

. Go to *Data » Catalogues*. +
→ The catalogues are listed.
. Find the row of the catalogue and move the toggle button (icon:fa-toggle-on[]) in the *Active/Inactive* column to the right. +
→ The catalogue is active. +
*_Tip:_* If incorrect data was transmitted to Amazon during the automatic export, you can correct the mappings in the catalogue, <<#1100, export a CSV file of the catalogue>> and then manually upload the file to Amazon.
. Also check the settings listed below:

[.tabs]
====
In the assistant *Base settings - Amazon*::
+
--
Carry out the following settings in the assistant *Base settings - Amazon* bevor activating the export of a new catalogue.

[.instruction]
Settings for new catalogues in the assistant Base settings - Amazon:

. Go to *Setup » Assistants » Omni-Channel*.
. Click on *Base settings - Amazon*.
. Open the assistant for the Amazon account. +
→ The assistant opens.
. Carry out the settings as described in <<#assistant-base-settings>>.
. Complete the assistant.

[[assistant-base-settings]]
.Settings for new catalogues in the assistant
[cols="1,3"]
|======
|Setting |Explanation

2+| Step: *Basic settings*

| *Select the Amazon platforms that you would like to sell your items on.*
| The platforms specified for the catalogue must be activate.

2+| Step: *Activate Amazon user account*

| *Activate user account*
| The Amazon user account specified for the catalogue must be active.

2+| Step: *Automatic data transfer*

| *Select the Amazon platforms that your item data should be transferred to.*
| The variation export for the Amazon platforms must be active. +
*_Note:_* The step *Automatic data transfer* is only visible after you activate the option *Show extended settings* in the step *Marketplace setup*.
|======

--

In the *Setting » Markets » Amazon*::
+
--
Carry out the following settings before you activate the export for a new catalogue.

[.instruction]
Settings in the setup menu:

. Go to Setup » Markets » Amazon » Settings.
. Select the Amazon account.
. Carry out the settings described in <<#assistant-menu>>.
. Save the settings.


[[assistant-menu]]
.Settings for new catalogues in the menu
[cols="1,3"]
|======
|Setting |Explanation

2+| Tab *Settings*

| *Active*
| In the *Access data* area, place a check mark for the option *Active*.

2+| Tab *Item settings*

| *Item export*
| From the drop-down list, select the option *Daily*.

| *Export categories*;
*BMVD export categories*
| Activate the flatfiles that you created a catalogue for.
|======

--
====

[#1100]
== Exporting the Amazon catalogue to a CSV file

You can download the catalogue before transmitting the data to Amazon, for example to check the mappings you created. You can export up to 30,000 variations. If you have more variations, you can filter them by item ID, tag ID and/or manufacturer.

[.instruction]
Exporting the Amazon catalogue to a CSV file:

. Go to *Setup » Markets » Amazon » Data exchange » Data export*.
. In the *Export catalogue* area, select the catalogue from the drop-down list.
. *_Optional:_* Enter item IDs and/or tag IDs separated by commas to filter the data to exported.
. *_Optional:_* Select a manufacturer from the drop-down list to filter the data to be exported.
. Click on *Export* (icon:box_plus[set=plenty]). +
→ The export starts. +
*_Note:_* Leave the browser window open whilst the export file is generated. Some flatfiles contain a lot of data. As such, the export can take several minutes.
. Scroll down to the *Download CSV of the catalogue export* area.
. In the column to the right, click on *Download* for the catalogue.
. Save the file on your computer. +
*_Note:_* The CSV file cannot be imported in plentymarkets. As such, you need to make any changes in the catalogue for them to take effect during the export.

[#1200]
== Troubleshooting

[qanda]
I mapped fields incorrectly and thus exported incorrect data to Amazon. What can I do?::
  First, correct the incorrect mappings in the catalogue. The data is transmitted to Amazon once a day at night. If you need to change something before this automatic export, you can export the corrected catalogue to a <<#1100, CSV file> and manually upload this CSV file to Amazon Seller Central.

[qanda]
I have switched from my old, reliable export to the new catalogues and it’s not working correctly. What can I do?::
  Don’t panic. Go to the *Data » Catalogues* menu and set the catalogue to inactive. Your variation data is transmitted to Amazon with the old export and you can check and correct your settings. Our support team is here to help you if you run into problems or have questions.
