= Best practice: Error Request is throttled
:lang: en
:keywords: Amazon, Prime, order
:position: 30

This best practice deals with the error “Request is throttled” and how to solve it.

[discrete]
==== What does the error message “Request is throttled” mean?

The number of requests for each process, such as order import, stock synchronisation, shipping confirmations etc., is limited by Amazon (Maximum Request Quota). If the maximum number of requests is exceeded, the process is blocked and further requests are rejected by Amazon. After a while, new capacities are unlocked a bit at a time (The Leaky Bucket Algorithm), and data transfer is enabled once again.

For more information, refer to link:http://docs.developer.amazonservices.com/en_DE/dev_guide/DG_Throttling.html[Throttling: Limits to how often you can submit requests^].

[discrete]
====  Major cause of the error

If you use a European marketplace account at Amazon, this error often occurs because a configuration in plentymarkets results in too many requests being sent to this Amazon account at once.

*Background*: In the *System » System settings » Markets » Amazon » Settings* menu, several Amazon accounts were linked to different platforms. However, those platforms all "access" the same European marketplace account. The accounts always have the same merchant ID. Various processes were activated in one/some of these accounts.

Amazon platforms which are mostly summarised in one European marketplace account (as of 15 May 2017):

Amazon.de, Amazon.fr, Amazon.it, Amazon.es, Amazon.co.uk

[IMPORTANT]
====
This error can also occur if you use further external programs which access your Amazon account and “overflow” it in combination with plentymarkets.
====

[discrete]
==== How to solve the error:

If you use a European Amazon marketplace account, it is useful to activate the processes only for one marketplace account in the *System » System settings » Markets » Amazon » Settings* menu. Otherwise, the data traffic of those processes will be transferred for every single Amazon account with the same merchant ID.

[TIP]
.Processes which often cause this error and which should therefore not be activated twice:
====
- Order import
- Stock synchronisation
- Stock changes
====

*P.S.:* An Amazon.com account does not belong to a European marketplace account.
