= Basic Price Search Engine
:lang: en
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: price search engine, price comparison, compare prices, price comparison portals, price search engine export, export to price search engines, price search engines, export for price search engines
:description: Multi-Channel in plentymarkets: Set up a basic item data export to price search engines in your plentymarkets system.
:position: 10
:url: markets/price-search-engines/basic-price-search-engine
:id: NXJDHNS
:url-export:

Use the format *Basic Price Search Engine* to export item data for any price search engine. You can use it to map the item data expected by most price search engines.

TIP: Before setting up the export, you might want to check if plentymarkets or a third party provides a direct interface to the price search engine on which you want to sell your products. You can find additional integrations in the link::https://marketplace.plentymarkets.com/plugins/sales/preisportale[plentyMarketplace].

[#100-0]
== _Alternative 1 (deprecated):_ Setting up the export with the export format BasicPriceSearchEngine-Plugin

NOTE: No new features are planned for the Elastic Export and the export formats. As such, we recommend that you <<#900, create catalogues instead>>.

In the past, the export format BasicPriceSearchEngine for the Elastic Export was used to export item data to price search engines. This export method is deprecated and has been replaced with the catalogue export. At the moment, you can still use the export format BasicPriceSearchEngine. However, this technology is no longer maintained and will not be supported for much longer.

[#100-1]
=== Installing the BasicPriceSearchEngine plugin

:price-search-engine: price search engines
:plugin-name: Basic Price Search Engine
:plugin-link: https://marketplace.plentymarkets.com/en/plugins/channels/preisportale/elasticexportbasicpricesearchengine_4777

include::../_textblocks/explanations/plugin-download.adoc[]

[#100-1]
=== Setting up the format BasicPriceSearchEngine-Plugin in plentymarkets

By installing this plugin, you will receive the export format *BasicPriceSearchEngine-Plugin*. Use this export format to transfer item data to price search engines via the elastic export. You also need to install the plugin *Elastic export* from the plentyMarketplace first before you can use the format in plentymarkets.

Once both plugins are installed in your plentymarkets system, you can create the export format *BasicPriceSearchEngine-Plugin*. For more information on export formats, see the <<data/exporting-data/elastic-export#, elastic export>> page.

[.instruction]
Creating a new export format:

. Go to *Data » Elastic export*.
. Click on *New export* (icon:plus-square[role="green"]).
. Carry out the desired settings. Pay attention to the explanations given in <<#settings-basic-price-search-engine>>.
. Save (icon:save[set=plenty]) the settings. +
→ The export format *BasicPriceSearchEngine-Plugin* is given an ID. +
→ The export format is shown in the *Exports* overview.

<<#settings-basic-price-search-engine>> lists details for settings, format settings and recommended item filters for the format *BasicPriceSearchEngine-Plugin*.

[[settings-basic-price-search-engine]]
.Format settings for BasicPriceSearchEngine-Plugin
[cols="1,3a"]
|====
| Setting | Explanation

2+| *Settings*

| *Format*
| Select *BasicPriceSearchEngine-Plugin*.

| *Provisioning*
| Select *URL*.

| *File name*
| The file name must have the ending *.csv* or *.txt* so that the file can be imported successfully by the price search engine or a comparable interface.

2+| *Item filter*

| *Add item filters*
a|Select an item filter from the drop-down list and click on *Add*. There are no filters set by default. It is possible to add multiple item filters from the drop-down list one after the other. +

* *Active* = Select *Active*. +
* *Markets* = Select one or more order referrers. The selected order referrer has to be active at the variation for the item to be exported.

2+| *Format settings*

| *Order referrer*
|Select the order referrer that should be assigned during the order import from the drop-down list.

| *VAT note*
| This setting does not affect this format.
|====

[#200]
=== Available columns for the export format

:export-format: BasicPriceSearchEngine plugin

include::../../markets/_textblocks/instructions/download_export-file.adoc[]

[[columns-export-file-basic-price-search-engine]]
.Available columns of the export file for the export format *BasicPriceSearchEngine-Plugin*
[cols="1,3a"]
|====
| Column header | Explanation

|article_id
|The *Item ID*.

|deeplink
|The *URL path* according to the format settings *Product URL*, *Client*, and *Order referrer*.

|name
|According to the format setting *Item name*.

|short_description
|According to the format setting *Preview text*.

|description
|According to the format setting *Description*.

|article_no
|The *Variation number*.

|producer
|The *manufacturer* of the item. The *external name* saved in the *Setup » Item » Manufacturers* menu is preferred if existing.

|model
|The model as per *Item » Edit item » [Open item] » [Open variation] » Settings » Basic settings*.

|availability
|The *name of the item availability* saved in the *Setup » Item » Availability* menu or the translation according to the format setting *Overwrite item availability*.

|ean
|According to the format setting *Barcode*.

|isbn
|According to the format setting *Barcode*.

|unit
|The *unit* of the evaluated base price information.

|price
|The *sales price* of the variation, according to the format setting *Order referrer*.

|price_old
|The *offer price* of the variation, according to the format setting *Order referrer*.

|weight
|The *weight* of the variation.

|category1
|The *first category level of the default category* for the configured *client* in the format settings.

|category2
|The *second category level of the default category* for the configured *client* in the format settings.

|category3
|The *third category level of the default category* for the configured *client* in the format settings.

|category4
|The *fourth category level of the default category* for the configured *client* in the format settings.

|category5
|The *fifth category level of the default category* for the configured *client* in the format settings.

|category6
|The *sixth category level of the default category* for the configured *client* in the format settings.

|category_concat
|The *category path of the default category* for the *Client* configured in the format settings.

|image_url_preview
|The *preview image* of the first image of the variation.

|image_url
|The *image* of the first image of the variation.

|shipment_and_handling
|The *shipping costs* saved for the item.

|unit_price
|The *base price information* in the format "price / unit" (example: 10.00 EUR / kilogram)

|unit_price_value
|The *price* from the evaluated *base price information*.

|unit_price_lot
|The *content* from the evaluated *base price information*.

|variation_id
|The Variation ID.
|====

[#100-0]
== _Alternative 2 (recommended):_ Export with catalogue format

Exporting using catalogue formats provides you with a long-term and flexible way to export your items for price search engines. You create one catalogue for each price search engine. You can create export files in CSV or in TXT formats. To export your item data to a price search engine, send the URL of the catalogue download to the price search engine.

[#902]
=== Creating a catalogue

Item data is exported using a marketplace format. To export your items to a price search engine, create a catalogue in the *Data » Catalogue* menu. Link the data fields in the catalogue with item data saved in plentymarkets in the marketplace format afterwards.

* Is this your first time working with catalogues? Then read up on the <<en/data/exporting-data/managing-catalogues, basic concept of the plentymarkets catalogues first>>.

:catalogue-template-name: Basic Price Search Engine
:catalogue-plugin:

include::../_textblocks/instructions/creating-catalogues.adoc[]

[#file-format]
=== Carrying out the format settings

Now carry out the format settings. This marketplace format allows you to export item data either as a CSV file or a TXT file. Select other format settings, such as field separators or text delimiters, based on the requirements of the price search engine.

* Check the page <<data/exporting-data/managing-catalogues#140, Managing catalogues>> to find out more about the format settings.

[#filter-export]
=== Setting filters for export

Now, set filters to only export specific items for the price search engine.

* Check the page <<data/exporting-data/managing-catalogues#257, Managing catalogues>> to find out how to set filters.

[#data-field-mappings]
=== Mapping data fields in the catalogue

Now, map the data fields in the catalogue to the item data saved in plentymarkets.

include::../_textblocks/instructions/catalogue-map-data-fields.adoc[]

[#recommended-mappings]
=== Recommendations for data field mappings

To help you with mapping your data fields for the catalogue, we have created a list of recommended data field mappings. Note that these mappings are recommendations only. Depending on how you manage your item data, other mappings may be more appropriate than the recommendation given here.

[.collapseBox]
.List of recommended data field mappings
--
include::_../textblocks/catalogue-mappings/basicpricesearchengine-recommended-mappings.adoc[]
--

[#catalogue-url]
=== Transferring the catalogue data to the price search engine

Unlike with other marketplace formats, you cannot just activate the catalogue to start the export to a price search engine. Instead, you need to make the URL of the catalogue export available to the price search engine.

* Check the page <<data/exporting-data/managing-catalogues#290, Managing catalogues>> to find out how to generate the URL for the download.
