[#faq-integration]
=== Integration

[.collapseBox]
.Wie kann ich am Partnerprogramm von Zalando teilnehmen?
--
Um am Partnerprogramm von Zalando teilzunehmen, wende dich direkt an link:https://www.zalando.de/zms/zalando-partner-program/[Zalando^].
--

[.collapseBox]
.Wie geht es nach der Registrierung beim Zalando-Partnerprogramm weiter?
--
Melde dich im Foren-Thread link:https://forum.plentymarkets.com/t/sammelthema-collective-thread-csv-formular-zum-abgleichen-von-artikeln-silhouetten-csv-form-for-synchronization-of-articles-silhouettes/669460[CSV-Formular zum Abgleichen von Artikeln/Silhouetten anfordern^]. +
Dort erhältst du von unserem Support-Team ein Formular im CSV-Format. Dieses Formular enthält die folgenden Informationen:
* Routen für Artikel
* Benutzernamen und Kennwort
* Zugangsdaten zum plentymarkets FTP-Server für Silhouetten +
_*Hinweis:*_ Auf diesen FTP-Server sendet Zalando deine Silhouetten, damit sie in dein System importiert werden können. plentymarkets importiert die Silhouetten jeden Mittwoch. +
Leite das ausgefüllte Formular an deine:n Zalando-Ansprechpartner:in weiter.
Durchlaufe den Assistenten *Kontoeinstellungen - Zalando* in deinem plentymarkets System.
Richte die Schnittstelle zu Zalando wie auf dieser Seite beschreiben in deinem plentymarkets System ein.
Aktiviere dein Zalando-Konto im Assistenten. (<<#1500, Wie?>>)
--

[.collapseBox]
.Wo finde ich die CSV-Datei für Zalando?
--
Wir stellen dir die Datei im Forum per PN bereit. Dazu gibt es das link:https://forum.plentymarkets.com/t/sammelthema-collective-thread-csv-formular-zum-abgleichen-von-artikeln-silhouetten-csv-form-for-synchronization-of-articles-silhouettes/669460[Sammelthema zum Abgleichen von Artikeln/Silhouetten^]. Bitte beachte, auch deine PID in deinem Beitrag anzugeben, falls sie von deiner PID im Benutzerkonto deines Foren-Accounts abweicht.
--

[.collapseBox]
.Mein Konto wurde noch nicht aktiviert.
--
Um die zDirect-API-Schnittstelle von Zalando zu aktivieren, muss dein Zalando-Konto mit dem plentymarkets Entwicklungskonto verknüpft werden. Diese Verknüpfung findet während der Integration automatisch statt. Allerdings muss plentymarkets in einem zusätzlichen Schritt Zugangsdaten für die API generieren und diese Zugangsdaten in deinem plentymarkets System speichern. Diese Zugangsdaten dürfen nicht von dir einsehbar sein. Deshalb kann plentymarkets dir die Zugangsdaten nicht bereitstellen. +
Melde dich in diesem link:https://forum.plentymarkets.com/t/sammelthema-aktivierung-neuer-zalando-konten/600409[Forum-Thread^], um die Freischaltung deines Kontos zu erbitten.
--

[#faq-artikeldatenexport]
=== Artikeldatenexport

[.collapseBox]
.Welche Einstellungen müssen vorgenommen werden, damit ein Artikel zu Zalando exportiert werden kann?
--
Die folgenden Einstellungen müssen für den Artikelexport zu Zalando vorgenommen werden: +
* Im *Tab: Verfügbarkeit* der jeweiligen Variante müssen die Verfügbarkeiten *Zalando* und *WEB-API* aktiviert sein. (<<#300, Wie?>>)
* Die Variante muss *aktiv* sein.
* Die Variante hat einen für Zalando definierten Verkaufspreis. (<<#350, Wie?>>)
* Die Artikel sind mindestens mit allen Pflichtmerkmalen verknüpft. (<<#600, Welche?>>)
--

[.collapseBox]
.Warum werden meine Artikel nicht zu Zalando exportiert?
--
Entweder sind nicht alle Grundeinstellungen vorgenommen worden oder die Pflichtfelder für Zalando wurden nicht gepflegt. +
Die Pflichtfelder für Zalando sind folgende: +

* 1 Farbcode
* Altersgruppe(n)
* Geschlecht
* Größenregister
* Hersteller-Code
* Herstellerfarbe
* Jahreszeiten-Code
* Silhouetten-Typ +

Um zu prüfen, ob es Fehler für deine Varianten gibt, stehen dir die unten aufgelisteten Berichte zur Verfügung. Dort kannst du (je nach Bericht) die Fehler deiner Artikel ausfindig machen.
--

[.collapseBox]
.Warum werden meine Artikel nicht aktualisiert?
--
Bei Zalando gibt es den Sonderfall, dass nachträgliche Änderungen von Artikeldaten wie beispielsweise Texte nicht automatisch importiert werden. Hier benötigt man zwingend die Rücksprache mit Zalando und eine entsprechende Freigabe.
--

[#faq-berichte-fehlermeldungen]
=== Berichte und Fehlermeldungen

[.collapseBox]
.Wo finde ich die Berichte von Zalando?
--
Die Berichte findest du in deinem plentymarkets System im Menü *Einrichtung » Märkte » Zalando » Einstellungen » Tab: Verarbeitungsberichte*. +
--

[.collapseBox]
.Export Log *zalandoArticleExportLog.txt*
--
Das Export-Log *zalandoArticleExportLog.txt* enthält Log-Einträge für Varianten. Das Export-Log wird einmal pro Nacht automatisch generiert. Die Datei enthält Einträge für erfolgreich exportierte Varianten und für Varianten, die nicht zu Zalando exportiert werden konnten. So kannst du das <<#905, Export-Log herunterladen>>.+
--

[.collapseBox]
.Artikelstatusberichte *ProductErrorReport.csv* und *ProductLiveReport.csv*
--
Die Artikelstatusberichte werden einmal täglich über Nacht von Zalando generiert. Die Berichte enthalten nur Informationen zu Varianten, die erfolgreich zu Zalando exportiert wurden. So kannst du die <<#910, Produkt-Statusberichte herunterladen>>. +
Der Bericht *ProductErrorReport.csv* enthält Varianten, die seit dem letzten Export nicht auf Zalando verkauft werden können. Der Bericht wird einmal pro Nacht automatisch generiert. +
Der Bericht *ProductLiveReport.csv* enthält Varianten, die seit dem letzten Export auf Zalando verkauft werden können, sowie Bestand und Preis jeder Variante auf den Zalando-Channels (DE, FR usw.) zu dem Zeitpunkt, zu dem die Datei generiert wurde. Der Bericht wird einmal pro Nacht automatisch generiert.
--

[.collapseBox]
.Fehlermeldungen im Bericht *zalandoArticleExportlog.txt*
--
[.collapseBox]
.errors (1234567) (ValueId:12345): silhouetteId
----
Das Merkmal *Zalando » Silhouettenname* für die VariantenID (=ValueID) fehlt.
----

[.collapseBox]
.errors (1234567) (ValueId:12345): brand
----
Das Merkmal *Zalando » Hersteller-Code* für die VariantenID (=ValueID) fehlt.
----

[.collapseBox]
.errors (1234567) (ValueId:12345): ageGroups
----
Das Merkmal *Zalando » Altersgruppe* für die VariantenID (=ValueID) fehlt.
----

[.collapseBox]
.errors (1234567) (ValueId:12345): sizeRegister
----
Das Merkmal *Zalando » Größen-Register* fehlt oder wurde nicht korrekt angelegt. +

* Fall 1: Das Merkmal fehlt. +
Das Merkmal muss hinzugefügt und mit dem entsprechenden Größenregister gepflegt werden. +

* Fall 2: Das Merkmal ist gepflegt. +
Hierbei muss zwingend das Format von Zalando eingehalten werden. Prüfe deshalb das Größenregister auf Richtigkeit. +
_*Hinweis:*_ Händisch angelegte Größenregister werden von Zalando nicht erkannt.
----

[.collapseBox]
.errors (1234567) (ValueId:12345): mainColorCode
----
Das Merkmal *Zalando » 1. Farbcode* für die VariantenID (=ValueID) fehlt.
_Ausnahme:_ Die Variante hat ein Farbattribut. Dann wird die Farbe über Attributverknüpfungen gepflegt.
----

[.collapseBox]
.errors (1234567) (ValueId:12345): supplierColor
----
Das Merkmal *Zalando » Hersteller-Farbe* oder die 2. Attributsverknüpfung fehlt oder ist nicht korrekt für die VariantenID (=ValueID) hinterlegt.
----

[.collapseBox]
.errors (1234567) (ValueId:12345): genders
----
Das Merkmal *Zalando » Geschlecht* für die VariantenID (ValueID) fehlt.
----

[.collapseBox]
.errors (1234567) (ValueId:12345): season
----
Das Merkmal *Zalando » Jahreszeiten-Code* für die VariantenID (ValueID) fehlt.
----

[.collapseBox]
.errors (1234567) (ValueId:12345): size
----
Das Merkmal *Zalando » Geschlecht* für die VariantenID (ValueID) fehlt.
----

[.collapseBox]
.errors (1234567) (ValueId:12345): ean
----
Die Variante benötigt eine *GTIN 13* im *Tab: Einstellungen » Barcode*, welche für die Herkunft *Zalando* freigegeben ist.
Die Herkunft prüfst du im Menü *Einrichtung » Artikel » Barcode*.
----

[.collapseBox]
.errors (1234567) (ValueId:12345): image
----
Die Variante muss mindestens ein Bild haben, welches für die Verfügbarkeit *Zalando* freigegeben wurde.
----
--

[.collapseBox]
.Fehlermeldungen im Bericht *ProductErrorReport.csv*
--
[.collapseBox]
.ZANOS_01 - Please send stock for this article to push it back online.
----
Siehe dazu den Punkt unter *Allgemeine Fragen und Antworten zum Bestandsabgleich*:
----

[.collapseBox]
.ZABLO_15 - Article blocked due to old season. Please delete the article from the feed or reach out to the Operations Team to adjust the season.
----
Wenn du diesen Artikel auch in der neuen Saison anbieten kannst, dann kannst du das Merkmal *Jahreszeiten-Code* in der Merkmal-Auswahl des Artikels auf die neue Saison legen. Wenn dir die neue Saison nicht angezeigt wird, dann melde dich bei Zalando, denn dort müssen anschließend die Silhouetten aktualisiert werden. +
Siehe dir anschließend diese Frage an: Die Silhouetten wurden in Plenty noch nicht aktualisiert/importiert?
----

[.collapseBox]
.PSERR_133 - Submitted size isn’t an allowed value for the size chart being submitted by the partner. Or the submitted size isn’t an allowed value for the partner article’s already existing size chart.
----
Du übermittelst eine Größe aus einem Größenregister, welche nicht für dich freigeschaltet ist. Beispielweise hat dir Zalando die Größen S-L zugeteilt, du versucht jedoch einen Artikel in XL zu listen. Wende dich dazu an Zalando und lass die Größen innerhalb der Größenregister für dich anpassen. +
Siehe dir anschließend diese Frage an: Die Silhouetten wurden in Plenty noch nicht aktualisiert/importiert?
----

[.collapseBox]
.PSERR_118 - EAN rejected because the sum of the material composition is not 100%. Please review the sum of material composition within the attribute.
----
Mit Merkmalen speicherst du am Artikel die Materialangaben. Mit einem Markemal vom Typ *Text* gibst du an, zu wie viel Prozent der Artikel aus dem gewähltem Material besteht. +
_*Hinweis:*_ Du musst abschließend immer auf 100% kommen. Die Materialangaben werden im Export jedoch in 100,00% erwartet. Die bedeutet, dass du z.B. bei 80% Polyester und 20% Baumwolle die folgenden Werte eintragen musst: +

* Polyester: “8000”
* Baumwolle: “2000”

Bei 100% Baumwolle wäre dies der Wert: “10000”.
----
--

[#faq-preisabgleich]
=== Preisabgleich

[.collapseBox]
.Wie kann ich die Übertragung der Preise prüfen?
--
Für eine Übersicht der von Zalando empfangenen Preis-Updates der letzten 7 Tage und deren Bearbeitungsstatus kannst du im Menü *Einrichtung » Märkte » Zalando » Tab: Verarbeitungsberichte » Preis-Berichte* entsprechende Berichte herunterladen. Beachte, dass Zalando den Preis erst im Status *Submitted* übernommen hat. Den Bericht kannst du jederzeit aktualisieren, der Zeitraum ist aber fest definiert. +
Solltest Du darüber hinaus Preis-Updates vermissen oder die übertragenen Werte Dir nicht richtig erscheinen, kannst Du dies zusätzlich im Log prüfen. Öffne dazu das Menü *Daten » Log*.

Stelle die folgenden Filter ein:

* *Integration*: Plenty\Modules\Zalando\Prices\Services\PriceUpdateService
* *Identifikator*: Zalando

Als Referenztyp kannst du zum Beispiel die *Varianten-ID* oder die *EAN* wählen. Trage dazu als Referenztyp den Wert *variationID* oder *ean* ein und verwende den entsprechenden Value als Referenzwert.

Öffne anschließend den Logeintrag und klicke auf *Alle expandieren*, um den Inhalt des jeweiligen Requests einzusehen.

Ob Zalando diese Meldung erfolgreich angenommen hat, sehen wir im Response. Dieser wird in einem separaten Log geschrieben. Du findest im folgenden Screenshot eine *jobId*:

Nutze diese und filtere erneut im Log danach.

Du wirst nun Meldungen dieser Art finden:

Öffne den im Screenshot oben markierten Logeintrag:

Du siehst nun innerhalb der *Description* die Rückmeldung von Zalando.
--

[.collapseBox]
.Wie kann ich eine erneute Preisübertragung für eine oder mehrere Varianten auslösen?
--
Dazu musst du den Zalando-Verkaufspreis der Variante anpassen. Du kannst eine kleine Preisänderung vornehmen, zum Beispiel änderst du den Preis auf + 0,01 EUR und danach wieder zurück (- 0,01 EUR). Der Preis wird anschließend innerhalb von 15 Minuten an Zalando übermittelt. +
Die Übertragung kann jederzeit im Log nachvollzogen werden. Siehe dazu auch: Wie kann ich die Übertragung der Preise überprüfen? +
Welcher Preis als regulärer Verkaufspreis an Zalando übertragen wird, hast du zu Beginn im Zalando-Einrichtungs-Assistenten festgelegt.
--

[.collapseBox]
.Wie kann ich eine erneute Preisübertragung für alle Varianten auslösen?
--
Um erneut alle Preise an Zalando zu übertragen, muss die Preisübertragung ausgelöst werden. Dies kann zum Beispiel über den Zalando-Einrichtungs-Assistenten geschehen. Dazu muss lediglich eine Anpassung im Bereich *Preise für Deutschland* und/oder *Preise für Österreich* vorgenommen werden. Welche Änderung du vornimmst, spielt dabei keine Rolle. Die Änderung kann anschließend wieder rückgängig gemacht werden. Innerhalb von 15 Minuten werden dann sämtliche Preise an Zalando übertragen. +
Die Übertragung kann jederzeit im Log nachvollzogen werden. Siehe dazu auch: Wie kann ich die Übertragung der Preise überprüfen?

Bei der Übertragung aller Varianten ist zu beachten, dass je nach Menge der Varianten sowie Verkaufskanäle die Übertragung verzögert laufen kann. Dies liegt an der Limitierung der API-Calls, welche Zalando vorgibt. Somit kann es vorkommen, dass die Übertragung in mehreren Paketen versendet wird und daher mehr Zeit in Anspruch nimmt. Es kann auch passieren, dass Varianten desselben Artikels in unterschiedlichen Paketen übermittelt werden. Jedes Paket kann bis zu 1000 Varianten beinhalten, welches wiederum einem Request entspricht. Pro Minute sind 20 Requests möglich. Ein Paket erkennst du im Log an der sogenannten *jobId*. Siehe dazu auch: Wie kann ich die Übertragung der Preise überprüfen?
--

[#faq-bestandsabgleich]
=== Bestandsabgleich

[.collapseBox]
.Wie kann ich die Übertragung der Bestände überprüfen?
--
Öffne das Menü *Daten » Log*.

Stelle die folgenden Filter ein:

* *Integration*: Plenty\Modules\Zalando\Stock\Services\StockUpdateService +
* *Identifikator*: Zalando

Als Referenztyp kannst du zum Beispiel die *Varianten-ID* oder die *EAN* wählen. Trage dazu als Referenztyp den Wert *variationID* oder *ean* ein und verwende den entsprechenden Value als Referenzwert.

Öffne den Logeintrag und klicke auf *Alle expandieren*, um den Inhalt des jeweiligen Requests einzusehen.

Als *quantity* wird der übermittelte Bestand angezeigt.

Ob Zalando diese Meldung erfolgreich angenommen hat, sehen wir im Response. Dieser wird in einem separaten Log geschrieben. Du findest im folgenden Screenshot eine *jobId*:

Nutze diese und filtere erneut im Log danach.

Prüfe sowohl die markierte Info-Meldung, als auch eventuelle Error-Meldungen.

Innerhalb der *Description* findest du den Ablehnungsgrund von Zalando.

Die Fehlermeldung „Request contains duplicate combinations of stock quantities.“ wird in der Regel ausgeworfen, wenn einzelne Varianten doppelt übergeben wurden. Dies erkennt Zalando zum Beispiel an einer mehrfach vergebenen EAN. Eine Übergabe des Bestands ist somit nicht möglich.
--

[.collapseBox]
.Wie kann ich eine erneute Bestandsübertragung für eine/wenige Varianten auslösen?
--
Dazu musst du den Bestand der jeweiligen Variante anpassen. Du kannst z.B. eine Bestandskorrektur von “- 1 Stück” auf “+ 1 Stück” über eine Bestandskorrektur vornehmen. Der Bestand wird anschließend innerhalb von 15 Minuten an Zalando übermittelt. +
Die Übertragung kann jederzeit im Log nachvollzogen werden. Siehe dazu: Wie kann ich die Übertragung der Bestände überprüfen?
Welche Lagerbestände an Zalando übertragen werden, hast du zu Beginn im Zalando-Einrichtungs-Assistenten festgelegt.
--

[.collapseBox]
.Wie kann ich eine erneute Bestandsübertragung für alle Varianten auslösen?
--
Um erneut alle Bestände an Zalando zu übertragen, die Bestandsübertragung ausgelöst werden. Dies kann zum Beispiel über den Zalando-Einrichtungs-Assistenten geschehen. Dazu muss lediglich eine Anpassung im Bereich *Bestände für Deutschland* und/oder *Bestände für Österreich* vorgenommen werden. Welche Änderung du vornimmst, spielt dabei keine Rolle. Die Änderung kann anschließend wieder rückgängig gemacht werden. Innerhalb von 15 Minuten werden dann sämtliche Bestände an Zalando übertragen. +
Die Übertragung kann jederzeit im Log nachvollzogen werden. Siehe dazu auch: Wie kann ich die Übertragung der Bestände überprüfen?

Bei der Übertragung aller Varianten ist zu beachten, dass je nach Menge der Varianten sowie Verkaufskanäle die Übertragung verzögert laufen kann. Dies liegt an der Limitierung der API-Calls, welche Zalando vorgibt. Somit kann es vorkommen, dass die Übertragung in mehreren Paketen versendet wird und daher mehr Zeit in Anspruch nimmt. Es kann auch passieren, dass Varianten desselben Artikels in unterschiedlichen Paketen übermittelt werden. Jedes Paket kann bis zu 1000 Varianten beinhalten, welches wiederum einem Request entspricht. Pro Minute sind 20 Requests möglich. Ein Paket erkennst du im Log an der sogenannten *jobId*. Siehe dazu auch: Wie kann ich die Übertragung der Bestände überprüfen?
--

[#faq-auftragsbearbeitung]
=== Auftragsbearbeitung

In einigen Fällen kann es unter Umständen zu Fehlermeldungen bei der Verarbeitung der Aufträge kommen. Mögliche Ursachen und häufige Fehler werden hier beschrieben.

Um den Verlauf deines Auftrags einzusehen, kannst du im Menü *Daten » Log* die folgenden Filter verwenden:

* *Identifikator*: Zalando
* *Referenztyp*: orderId / externalOrderId
* *Referenzwert*: deine Order-ID / deine externe Order-ID

[.collapseBox]
.Die Versandbestätigung für meine Aufträge fehlen oder wurden nicht an Zalando gemeldet. Wo finde ich die Fehler dazu im Log?
--
Wenn eine Versandbestätigung nicht an Zalando gesendet wurde, öffne das Menü *Daten » Log*.

Stelle die folgenden Filter ein:

* *Integration*: Plenty\Modules\Zalando\Orders\Procedures\OrderShippingProcedure
* *Identifikator*: Zalando
* *Level*: error

Bei Bedarf kann zusätzlich nach der Order-ID oder der externen Order-ID gefiltert werden:

* *Referenztyp*: orderId / externalOrderId
* *Referenzwert*: deine Order-ID / deine externe Order-ID
--

[.collapseBox]
.Fehlermeldungen zur Auftragsbearbeitung
--
[.collapseBox]
.Keine Rücksendenummer gefunden.
----
Hierfür kann es zwei Gründe geben:

Erstens: Für den Auftrag existiert zwar eine Paketnummer, aber keine Retouren-Tracking-Number (Retourenlabel). +
_*Analyse:*_ Überprüfe dies im Menü *Aufträge » Versand-Center*.
Retourenlabels werden nach der Suche des jeweiligen Auftrags im *Tab: Retourenetiketten* angezeigt.
_*Lösung:*_ Sollte kein Etikett vorliegen, muss dieses Etikett nachträglich erstellt werden und der Versand erneut gemeldet werden.

Zweitens: Es existiert ein Retourenlabel. +
_*Analyse:*_ Prüfe den Zeitpunkt der Erstellung des Retourenlabels sowie den Zeitpunkt der Versandmeldung an Zalando.
Wenn das Retourenlabel bereits vorhanden ist, kann es sein, dass das Label nicht vor der Versandmeldung an Zalando vorlag.
_*Lösung:*_ Löse die Versandmeldung erneut aus, indem du die Ereignisaktion noch einmal startest. Je nach gewähltem Ereignis innerhalb deiner Aktionen solltest du entsprechend vorgehen. Wenn es nicht möglich ist, dieses Ereignis auszulösen, kannst du als Fallback auch eine neue Ereignisaktion mittels Statuswechsel anlegen.
----
--

[#faq-allgemein]
=== Allgemeine FAQ

[.collapseBox]
.Die Silhouetten wurden in plentymarkets noch nicht aktualisiert/importiert.
--
Zalando sendet (neue) Silhouetten auf den plentymarkets FTP-Server, damit sie in dein plentymarkets System importiert werden können. Neue Silhouetten werden wöchentlich (mittwochs) von uns aktualisiert und können anschließend von dir in Merkmale konvertiert werden.

Nutze dazu die Funktion *in Merkmale konvertieren*.

Solltest du diesen Step zum ersten Mal durchlaufen und es sieht folgendermaßen aus:

Dann liegt es entweder daran, dass

* Zalando noch keine Silhouetten für dich übersendet hat oder
* der Import deiner Silhouetten durch plentymarkets noch nicht erfolgt ist.

Liegen Silhouetten für dein System vor und du möchtest diese in Merkmale konvertieren/aktualisieren, so sieht die Ansicht wie folgt aus:

Wähle die gewünschten Gruppen und klicke auf *in Merkmale konvertieren*.

_*TIPP:*_ Wähle nur die Gruppen, zu denen du tatsächlich einen Verkauf starten möchtest, um die Anzahl der Merkmale so gering wie möglich zu halten.

Zusätzlich findest du hier das Kapitel aus dem Handbuch zu diesem Thema.
--

[.collapseBox]
.Wo finde ich die Auftragsdokumente, die Zalando anfordert?
--
Sämtliche Dokumente, welche Zalando von dir einfordert, müssten selbstständig gemäß den Anforderungen konfiguriert werden. Die PDF-Vorlagen (Templates) stellt dir Zalando bereit.

_*Achtung:*_ da Zalando an dieser Stelle gewisse Anforderungen hat und du die Einstellungen der Dokumente nur global konfigurieren kannst, solltest du unter Umständen einen separaten Mandanten ausschließlich für Zalando anlegen, um deine bestehenden Einstellungen nicht zu überschreiben. Pro Mandant hast du anschließend die Möglichkeit, die Dokumente individuell zu gestalten.

Einen zusätzlichen Mandanten buchst du unter *START » Mein-Konto » Verträge*.

Wie die Einrichtung deiner Dokumente funktioniert, erfährst du hier.
--