= Limitation of simultaneously logged in users in the back end
:lang: en
include::{includedir}/_header.adoc[]
:keywords: simultaneously logged in, user, tariff, tariff model, tariff change, several users, too many users, back end
:position: 10

Due to the new tariff models, for customers making a new contract or a tariff change, a modification concerning the simultaneously logged in users has been made. Depending on the tariff, there is now a limitation in the number of those. *Customers with an existing tariff are not concerned.*

== Exceeding the maximal number of simultaneously logged in users

Is the number of simultaneously logged in users reached or exceeded, the user gets one of the two following error messages:

*For variable users*:
Too many users. Only %d users can be logged in simultaneously in the back end. Try again soon or contact your admin.

*For admins*:
Too many users. Only %d users can be logged in simultaneously in the back end. Upgrade your contract or go to session management.

[[table-limitation-per-tariff]]
.Limitation depending on the tariff
[cols="1,3"]
|====
|Tariff|Maximal number of logged in users

|*STARTER Zero*
|up to 3

|*STARTER Basic*
|up to 5

|*STARTER Advanced*
|up to 10

|*PRO Classic*
|up to 50

|*PRO Flex*
|up to 100

|*PLUS*
|no limitation
|====

== What has to be done if the maximal number of simultaneously logged in users has been reached?

Via the link in the error message, the admin is directly forwarded to the session management. This allows the admin to terminate the currently running sessions so he can enable the login of another user. The login is valid for 10 minutes. Afterwards, the admin is automatically logged out. +
The admin can access the Session Management in the back end via *System » Settings » User* as well as via the user icon on the top right.
