= ItemView
:lang: en
// include::{includedir}/_header.adoc[]
:position: 40

*CMS » Web design » Layout » ItemView*

==  Content of this page

The following chapters describe the item layouts in plentymarkets, i.e. the page structure that is controlled with the templates under *ItemView*. This chapter provides you with basic information about using the templates as well as information about the HTML structure. The practical examples also provide more detailed information.

[IMPORTANT]
.Basic structures in the plentymarkets CMS
====
You will need to have basic knowledge of HTML and CSS in order to edit the templates in the plentymarkets CMS. Furthermore, we recommend that you first read and understand the information given in the <<omni-channel/online-store/setting-up-clients/cms#web-design, Web design>> chapter. Pay special attention to the chapter <<omni-channel/online-store/setting-up-clients/cms-syntax#, Basic information about syntax>> before you make changes to the templates. The <<omni-channel/online-store/setting-up-clients/cms#web-design-basic-information-about-syntax-page-structure, Page structure>> chapter gives you an overview of the template structure in plentymarkets.
====

==  General information about item layouts

*ItemViewSingleItem* is the basic template for displaying items. Moreover, the ItemView folder contains a variety of templates to design item lists, e.g. item search results in the online store or the display of items after using filters. There are also special templates for cross-selling items or special offers.

The following example shows an excerpt of the *ItemViewSingleItem* template's code including an item detail view.

[TIP]
.Example item characteristics
====
Following is a simple example of how you can design item characteristics such as *Name*, *Price* with a *CurrencySign*, *VATHint* and *VAT* and a link to the *Shipping costs* page in the code.

&lt;h1&gt;$Name[1]&lt;/h1&gt;

&lt;span class="price"&gt;$Price$CurrencySign&lt;/span&gt; +
&lt;span class="smallText"&gt;$VATHint$VAT% &lt;a href="{&amp;#037; Link_ShippingCosts()  &amp;#037;}" title="Versandkosten"&gt;Versandkosten&lt;/a&gt;
====

The different parameters of an item, such as *Name* or *Price* are implemented using their corresponding <<omni-channel/online-store/setting-up-clients/cms-syntax#basics-template-variables, template variables>>.

==  Item layouts: Templates

The menu provides you with a variety of templates that you can use to design your item layouts. The most important templates are listed below as examples. You can find more detailed information in the <<omni-channel/online-store/setting-up-clients/cms-syntax#, CMS syntax>> chapter, especially on the <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview, ItemView>> page of the manual.

[.subhead]
ItemViewSingleItem

Displays the <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewsingleitem, Detailed item layout>> in the online store.

[.subhead]
ItemViewSearchResultsList

Displays the item search results in the online store as a list.

[.subhead]
ItemViewFilterResultsList

Displays a list of items that were found by using a filter. One example is the characteristics filter.

[.subhead]
ItemViewCategoriesList

Displays a list of items found in the selected <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcategorieslist, category>>.

[.subhead]
ItemViewCrossSellingItemsList

Displays a list of <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewcrosssellingitemslist, Cross-selling items>>.

[.subhead]
ItemViewTopSellersList

Displays a list of <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewtopsellerslist, Top selling items>>.

[.subhead]
ItemViewSpecialOffersList

Displays a list of <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-getitemviewspecialofferslist, Special offers>>.

[.subhead]
ItemViewLatestItemsList

Displays a list of the latest <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlatestitemslist, items added>> to the online store.

[.subhead]
ItemViewItemsByPositionList

Displays a list of the <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewitemsbypositionlist, top selling items>>. Will be updated over night.

[.subhead]
ItemViewLastSeenList

Displays a list of the customer's <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewlastseenlist, last seen items>>.

[.subhead]
ItemViewRandomList

Displays a list of <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-itemview-container-itemviewrandomlist, random items>> selected by the system.

[.subhead]
ItemViewItemImagesList

Displays a list of item images.
