= Order process
:lang: en
// include::{includedir}/_header.adoc[]
:keywords: Order process, Web design, CMS
:position: 80

*CMS » Web design » Order process*

== Content of this page

The following chapters provide you with general information about web design and highlight some important aspects of this area in the online store.

== How the order process is structured

The order process refers to the process that a customer goes through when buying something in the online store. It begins the moment a customer puts an item in their shopping cart and it continues until the moment that the order is sent. This process is divided into 3 areas: first the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-shopping-cart, shopping cart>>, then the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-checkout, checkout>> and finally the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-order-confirmation, order confirmation>>. These areas are displayed in the *layout* section as well. In this chapter, we will describe the various possibilities that you have for making changes to the design.

[WARNING]
.Legal regulations
====
If your online store is run in Germany, then please make sure that you comply with the legal regulations for the order process that went into effect on August 1st, 2012. Further information can be found on the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-checkout, checkout>> page of the manual, listed within sections 2 and 3 as well as on the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-buttons-complying-with-the-shopping-cart-solution, complying with the shopping cart solution>> page. Here you will also find information about the possibilities that plentymarkets provides you. For further information (in German), refer to our link:https://www.plentymarkets.co.uk/blog/Onlinehandel-in-Deutschland-Buttonloesung-und-neue-Informationspflichten/b-882/[blog^].
====

== Basic settings

You can individually configure the *order process*. For example, you can decide which elements you would like to have displayed and which functions you would like to activate. Go to <<omni-channel/online-store/setting-up-clients/order-process#, Setup » Client » Select client » Order process » Basic settings>> to carry out these settings. A standard configuration has already been saved by default.

[IMPORTANT]
.jQuery
====
jQuery functions are integrated in this area. For further information about working with or expanding these functions, refer to the <<omni-channel/online-store/setting-up-clients/cms#web-design-basic-information-about-syntax-jquery, jQuery>> page of the manual.
====

== Tracking functions

You can integrate tracking functions into your online store with the help of template variables and corresponding tracking service providers. Doing so will provide you with detailed statistics about the ways that visitors use your store and can help you make appropriate decisions about how your store's design can be improved.

You can integrate these functions into your online store by making use of the services provided by <<omni-channel/online-store/setting-up-clients/extras/universal-analytics#, Google Analytics>>  or a different tracking service provider, such as <<omni-channel/online-store/setting-up-clients/extras/etracker#, etracker>>.
