= Managing user accounts
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Owner, User, User accounts, User account, Roles, Rights, Right
:description: Working with plentymarkets: Manage user accounts, create new user accounts and edit existing user accounts in the plentymarkets system.
:position: 20

Create accounts for new users and edit existing user accounts in the user menu. Furthermore, assign roles and classes to users. Depending on the workflow, they are important for other areas in the system. Roles are used for grouping users and assigning the same rights to multiple user accounts in a very convenient way. Classes on the other hand allow you to assign rights to specific users and interfaces. For example, assign API calls to users of the API class individually.

Five free user accounts are included in every plentymarkets system. If you need additional user accounts, book them in the link:https://www.plentymarkets.co.uk/prices/[configurator].

[#35]
== Setting the password strength

In the menu *System » Settings » User » Security*, you manage the criteria for new passwords entered by users. Proceed as follows to activate the criteria.

[.instruction]
Setting the password strength:

. Go to *System » Settings » User » Security*.
. Carry out the settings. Pay attention to the information given in <<table-setting-password-security>>.
. *Save* the settings. +
→ New passwords need to comply with the criteria to be valid.

[[table-setting-password-security]]
.Setting the password strength
[cols="1,3"]
|====
|Setting |Description

|*Activate password security*
|If this option is active, new passwords must meet the criteria set for password security.

|*Minimum length*
|Enter the minimum number of characters for new passwords. +
*_Note:_* For security reasons, the minimum length is 8 characters.

|*Password criteria*
|Activate the criteria for new passwords. +
*_Note:_* For security reasons, at least 3 criteria must be activated.

|*Minimum amount of fulfilled criteria*
|Select the minimum number of criteria that new passwords need to meet. +
*_Note:_* For security reasons, at least 3 criteria must be activated.

|*Number of latest passwords*
|Enter the number of previously used passwords that users cannot use again. If the user tries to enter a previously used password, the user is asked to enter a different password. If you do not want to use this function, enter 0 or leave blank. +
*_Note:_* The number of passwords to be saved must be 20 or less.

|*Password validity period (in days)*
|The user account is locked at the end of this period. If you do not want to use this function, enter 0 or leave blank.
|====

[#10]
== Creating a user account

When using your plentymarkets system for the first time, a default user account of the **Admin** class with administrative rights is already set up in the system. You need at least one admin user account. As such, either create a new user account of the **Admin** class and delete the default user account afterwards or edit the existing user account. Proceed as described below to create a new user of any class.

[.instruction]
Creating a user account:

. Go to **System » Settings » User » Accounts**.
. Click on **New**. +
→ The **Create new user** window opens.
. Enter the **User name**.
. Enter the **Real name**.
. Enter the **Password**.
. Repeat the password.
. Enter the user's email address. This allows the user to receive messages from the system.
. Select a **User class**. Pay attention to the information given in <<table-available-user-classes>>.
. **Save** the settings.

The user name must not contain any spaces and must have at least 5 characters.

Click on **My account** to open your own user account.

The user classes are preset and the classes' settings cannot be changed. The following table includes detailed information about preset rights and rights that you can assign individually:

[[table-available-user-classes]]
.Available user classes
[cols="1,3"]
|====
|Class |Explanation

|**Admin**
|Class with all rights and no restrictions. Must be assigned to at least one user account because only an admin can create, edit and manage user accounts without any restrictions. When using multiple admin accounts, these accounts all have equal rights.

|**Variable**
|Class with individual rights for <<basics/working-with-plentymarkets/manage-users#100, menu>> and <<basics/working-with-plentymarkets/manage-users#110, functions>> that can be assigned in the **Rights** tab.

|**Call centre**
a|Class with access rights for the following menus:

* Homepage
* Calendar
* Ticket system (pending tickets, synchronise eBay messages)
* Search and edit orders
* Create new orders
* Edit customers

|**API**
|Class for <<basics/working-with-plentymarkets/manage-users#120, API calls>> that can be assigned in the user account. API calls are activated individually. REST API calls are not assigned to user accounts by default.

|**Logistics**
a|Class with access rights for the following menus:

* Homepage
* Calendar
* Search and edit stock
* Search and edit incoming items
* Calculate stock
* Import and export data
* Storage location management
* Search and edit orders
* Fulfilment

|**Blog**
a|Class with access rights for the following menus:

* Homepage
* Calendar
* Blog

|**Newsletter2Go**
|Class automatically used when a <<crm/sending-newsletters#2100, Newsletter2Go>> interface is set up.
|====

[#20]
== Editing a user account

After creating a user account, the new account is displayed in the user account overview. User accounts are listed alphabetically. Select a user account to edit the account settings. You may not be able to see all of the settings. The settings that are visible depend on your own user class and on the user class of the user account that is being edited. Edit multiple user accounts with the *Group function in the User* menu.

[.instruction]
Editing a user account:

. Go to **System » Settings » User » Accounts**.
. Click on **Open user**. +
→ The user account opens in a new tab.
. Pay attention to the explanations given in <<table-user-account-master-data>> and carry out the settings as desired.
. **Save** the settings.

[TIP]
.Password is saved
====
The password you entered when creating your user account will not be visible in editing mode later on, but it is saved. You do not have to re-enter the password when editing the user account.
====

[#30]
=== Entering the master data

Enter information and change the settings of a user account in the **Master data** tab. Only users with administrative rights can edit the **user name**, **IP restriction**, **user class** and **roles**. All other master data can also be changed by a user in their own account. In this tab, it is also possible to block a user account.

[[table-user-account-master-data]]
.A user account's master data
[cols="1,3"]
|====
|Setting |Explanation

|**Title bar**
|The title bar displays the **user ID** and **user name** as well as the **date** and **time** when changes were last made to the user account. +
The user ID is a unique identification number. It is assigned by the system and cannot be changed.

|*User blocked*
|Activate to block the user account. The user will no longer be able to log into the system.

|**User name**
|Enter a name without spaces. The user name is a mandatory entry and is needed for the login. The user name must not contain any spaces and must have at least 5 characters.

|**Actual name**
|Actual name of the user displayed in the title bar of the plentymarkets backend.

|**Email**
|Enter the user account's email address. The email address is important for system notifications, notifications from event procedures and group communication within the system.

|**Google Mail**
|If using Gmail, enter the user’s Gmail address.

|**Skype name**
|If using Skype, enter the user’s Skype name.

|**Colour**
|Define a colour in the editing window by selecting a colour, entering a hexadecimal colour code or the RGB value. The colour makes it easier to identify the user account in other menus, e.g. the <<basics/working-with-plentymarkets/tasks-and-calendars#600, Calendar>>.

|**Time zone**
|Select the user’s time zone.

|**Image URL**
|Enter an image URL here, e.g. to insert a thumbnail image used for blog entries.

|**UI language**
|Select the language for the admin area. This is the default language that is used when logging in.

|**IP restriction**
|Enter the user's IP address. The user will only be allowed to log into plentymarkets with this IP address.

|**User class**
|Select the user class for the user account. You can choose from the following classes: **Admin**, **Variable**, **Call centre**, **API**, **Logistics**, **Blog** and **Newsletter2Go**.

|**Roles**
|Select roles for the user account. <<basics/working-with-plentymarkets/manage-users#70, Roles>> must have already been created before they can be selected here.

|**New password**
|Enter a new password to give the user account this password.

|**Repeat password**
|Enter the password again.

|*New app PIN*
|For users that operate the plentymarkets app, you can enter a PIN with between 4 and 12 numbers to activate this user for quick account switching. If you save a PIN, users can quickly switch to a different user account in the plentymarkets app. However, the user can also log into the plentymarkets app using their password. +
*_Tipp:_* After the PIN is saved, the field contains 4 dots. These dots show that an app PIN has been saved for the user account. The actual PIN might consist of more numbers. +
When switching users, any user account for which a PIN has been saved can be selected. To remove the PIN, e.g. because the user no longer works with the app, delete the 4 dots and save the user account. +
*_Note: 

|*Repeat app PIN*
|Re-enter the PIN.
|====

////
h3>Farbe für Benutzer einrichten</h3>
<p>Satz zur Farbe</p>

<h5>
Assigning a colour to a user:</h5>
<ol>
<li>
Go to <strong>System » Settings » User » Accounts</strong>.</li>
<li>
Click on a user account to open the editing menu.</li>
<li>
Click on the <strong>Colour</strong> row.<br />
→ An editing window for selecting the colour opens.</li>
<li>
Select the desired colour by moving the small circle.</li>
<li>
Alternative: Enter a hexadecimal or RGB value.</li>
<li>
<strong>Save</strong> the settings.</li>
</ol
////

[IMPORTANT]
.Locking of the account or system
====
The maximum number of login attempts is 5 per user account or 25 per IP address. If the maximum number of login attempts was exceeded, then the following message will be displayed: You have exceeded the maximum number of invalid login attempts. Your account has been temporarily locked. In such a case, a new login attempt can first be carried out after 24 hours.
====

[#40]
=== Activating owners

In the **Owner** tab, determine the areas in which the user should be available as an owner. For example, if you create a calendar, then you have to set up users as owners of the calendar. Activate the **Calendar** menu in the **Owner** tab.

[.instruction]
Setting a user as owner:

. Go to **System » Settings » User » Accounts**.
. Open a user account.
. Click on the **Owner** tab.
. Activate the areas in which the user should be available as an owner.
. **Save** the settings.

// ACHTUNG!!!! Aus der GUI wird auf die Kapitel zu E-Mail-Postfächern verlinkt. Falls diese Inhalte verschoben werden, bitte Ziyad oder einem anderen Mitglied des Cloud-Teams Bescheid sagen, damit der Link angepasst wird. Danke.

[#42]
=== Managing mailboxes

If plentymarkets manages your domains, then you can go to **Settings » Basic settings » User » Accounts » Open account » Tab: Email** to create and manage mailboxes for system users. You need admin rights to manage mailboxes. These mailboxes are created and hosted by the third party email provider link:https://mailbox.org/business/[mailbox.org^]. You will learn how you create mailboxes and additional email addresses (aliases) for these mailboxes.

[IMPORTANT]
.Mailboxes with other provider
====
The configuration described is only relevant for plentymarkets customers with domains managed by plentymarkets who want to use the external provider link:https://mailbox.org/business/[mailbox.org^]. If you manage your email account with a different provider and want the plentymarkets system to send emails from this provider too, you do not need to set up mailbox.org. However, you still need to refer to chapter <<crm/sending-emails#100, Saving the email server's access data>> on the <<crm/sending-emails#, Sending emails>> page of the manual.
====

[#44]
==== Create mailbox

Proceed as described below to create mailbox.org mailboxes for system users. You need admin rights to create mailboxes and aliases.

[.instruction]
Creating a new mailbox:

. Go to **System » Settings » User » Accounts**.
. Click on **My account**.
. Click on the **Email** tab.
. Click on **New**. +
→ The **Create mailbox** window opens.
. Select the email address type **Mailbox**.
. Carry out the additional settings. Pay attention to the information given in <<table-settings-creating-a-mailbox>>.
. Click on **Create mailbox**. +
→ The mailbox is created on the servers of the external provider mailbox.org.

[[table-settings-creating-a-mailbox]]
.Creating a mailbox
[cols="1,3"]
|====
|Setting |Explanation

|**Email address type**
|Select the email address type **Mailbox**. +
**Mailbox** = A new mailbox is created. +
**Alias** = An additional email address for an existing mailbox is created. Select the mailbox for this alias by selecting the option **Target mailbox**.

|**Email address**
|Enter the email address that you want to assign to this mailbox. Enter the local part of the email address left of the @ sign. Select the domain part of the email address from the dropdown list. +
**__Note:__** You cannot create mailboxes for test domains (e.g. @plenty-test-drive) or for external domains that are not hosted by plentymarkets. +
**__Note:__** After an email address is deleted, this address is locked for 48 hours. You need to wait until the end of this period before you can create an email address with this name again.

|**First name** +
**Last name**
|Enter the first name and last name of the person with this user account. This name will be displayed with the email address as part of the sender information.

|**System user**
|Select the user account you want to assign the mailbox to.

|**Forwarding**
|Enter one or more email addresses if you want to forward emails sent to this address to a different mailbox. Separate multiple email addresses by commas, e.g. customer@your-plentystore.co.uk,consultant@your-plentystore.co.uk.

|**Save emails in mailbox**
|Option becomes selectable once a forwarding address is entered. +
 Activated = Emails are forwarded to the target email addresses. Copies of the forwarded emails will be saved in this mailbox. +
Not activated = Emails are forwarded to the target email addresses directly. No emails are saved in this mailbox.

|**Password**; +
**Repeat password**
|Enter a password and re-enter it for confirmation. +
**__Note:__** The password must contain at least 8 characters and a combination of upper case letters, lower case letters and numbers.

|**Fees**
|Select a fee model. All prices shown are subject to VAT. Your plentymarkets contract will be updated after the mailbox is created.
|====

==== Saving the mailbox.org server's access data in plentymarkets

For plentymarkets to send emails such as order confirmations on your behalf, you need to save the link:https://kb.mailbox.org/display/MBOKBEN/Setup+other+e-mail+clients+manually[access data^] of the mailbox.org mailbox from which you want to send these emails in the *<<crm/sending-emails#100, Settings » Client (store) » Standard » Email » Access data>>* menu.

[#46]
==== Creating an additional email address (alias) for a mailbox

Create an alias for the mailbox if you want the mailbox to be linked to more than one email address. The number of email addresses you can create per mailbox depends on the fee you select. Proceed as described below to create an additional email address for a mailbox.

[.instruction]
Creating an additional email address for a mailbox:

. Go to **System » Settings » User » Accounts**.
. Click on **My account**.
. Click on the **Email** tab.
. Click on **New**. +
→ The **Create mailbox** window opens.
. Select the email address type **Alias**.
. Carry out the additional settings. Pay attention to the information given in <<table-setting-create-additional-address>>.
. Click on **Create mailbox**. +
→ The additional email address is created.

[[table-setting-create-additional-address]]
.Creating an additional email address for a mailbox
[cols="1,3"]
|====
|Setting |Explanation

|**Email address type**
|Select the email address type **Alias**. +
**Mailbox** = A new mailbox is created. +
**Alias** = An additional email address for an existing mailbox is created. Select the mailbox for this alias by selecting the option **Target mailbox**.

|**Email address**
|Enter the email address that you want to assign to this mailbox. Enter the local part of the email address left of the @ sign. Select the domain part of the email address from the dropdown list. +
**__Note:__** After an email address is deleted, this address is locked for 48 hours. You need to wait until the end of this period before you can create an email address with this name again.

|**Target mailbox**
|Select the mailbox that emails to this alias address are to be sent to.
|====

[#46a]
==== Select basic fee

By default, the basic fee **Business Reseller** applies to the hosting of mailboxes by mailbox.org through plentymarkets. This basic fee is free. However, it does not include support by mailbox.org. You can change your basic fee at any time. Change your basic fee model if you want to receive support from mailbox.org or want to extend the services you receive from mailbox.org. The selected basic fee applies to all mailboxes in your plentymarkets system including all clients.

[.instruction]
Changing your basic fee model:

. Go to **System » Settings » User » Accounts**.
. Click on **My account**.
. Click on the **Email** tab.
. Click on **Change basic fee**. +
→ The **Select basic fee** window opens.
. Check the specifications of the different basic fee models.
. Select the basic fee you want to book.
. Click on **Change basic fee**. +
→ The fee is saved and your plentymarkets contract is updated. mailbox.org will send you an email with additional information.

[#47]
==== Deleting a mailbox

Proceed as described below to delete a mailbox. You need admin rights to delete mailboxes/aliases. After deleting a mailbox/alias, you need to wait 48 hours before you can create a new mailbox/alias with the email address that you just deleted.

[WARNING]
.Emails can no longer be accessed after deleting a mailbox
====
After deleting a mailbox, you can no longer access the emails saved in the mailbox via mailbox.org. Make sure that you have saved local copies of any emails you still need access to before deleting the mailbox.
====

[.instruction]
Deleting a mailbox:

. Go to **System » Settings » User » Accounts**.
. Click on **My account**.
. Click on the **Email** tab. +
→ A list of the mailboxes is displayed.
. Click on the mailbox in this list that you want to delete.
. Click on **Delete**. +
→ The mailbox and all associated aliases are deleted on the mailbox.org server. +
→ Your plentymarkets contract is updated.

[#50]
=== Additional user settings

In addition to the tabs described above, you find other tabs in the editing window of a user account. These tabs and the corresponding settings are described on other pages of the manual. Further information about the tabs can be found by following the links in the right column.

[[table-further-tabs-editing-window]]
.Other tabs in the editing window of a user account
[cols="1,3"]
|====
|Tab |Explanation

|**Complimentary close**
|In this tab, enter a text that you want to add automatically at the end of your messages and comments in the ticket system. This text is added as a <<basics/working-with-plentymarkets/customise-user-account#10, complimentary close>>.

|**Signature**
|In this tab, enter a text that you want to add automatically at the end of your messages and comments in the ticket system. This text is added as a <<basics/working-with-plentymarkets/customise-user-account#20, signature>>.

|**Right**
|For further information about this tab, refer to the <<basics/working-with-plentymarkets/manage-users#90, Assigning rights>> chapter.

|**Personal settings**
|In this area, you can change the settings of the user account currently logged into the system. Therefore, you can only see this tab in your own user account. The tab is divided into the <<basics/working-with-plentymarkets/customise-user-account#40, General>>, <<basics/working-with-plentymarkets/customise-user-account#50, Shortcuts>> and <<basics/working-with-plentymarkets/customise-user-account#60, Favourites>> tabs with settings that only apply to you personally.

|**Calendar**
|Make changes to the <<basics/working-with-plentymarkets/tasks-and-calendars#600, Calendar>> settings in this tab.
|====

[#85]
== Editing multiple user accounts

Edit multiple user accounts with the **Group function** in the **User** menu. The group function edits previously selected user accounts.

[.instruction]
Carrying out the group function:

. Go to **System » Settings » User » Accounts**.
. Select the users that you want to edit.
. Click on **Group function**. +
→ The **Group function** window opens.
. Pay attention to the explanations given in <<table-editing-multiple-user-accounts>> and carry out the settings as desired.
. Click on **Apply** to apply the settings to the user accounts.

[[table-editing-multiple-user-accounts]]
.Editing user accounts using the **Group function**
[cols="1,3"]
|====
|Setting |Explanation

|**Delete**
|Activate to delete the selected user accounts.

|**Send email**
|Activate to send an email to the selected user accounts. The email program will open. The email addresses of the user accounts are entered in the recipient field.

|**Skype**
|Activate and select **Instant message**, **Call** or **Video call** to contact users via Skype.

|**Roles**
|Activate and select one, several or **ALL** roles to link the selected users with these roles.
|====

[#90]
== Assigning rights

Define which menus in plentymarkets are visible to the user and what they may edit. You can assign rights to every user account individually or to multiple user accounts via roles. This chapter explains how to use rights correctly. In the following, you will learn how to create roles. The rights menus for user accounts and roles have the same structure. Go to the **Right** tab in a user account. The tab is composed of several tabs for determining the individual rights. Depending on the user account's class, different tabs with different rights may be visible. The Variable class offers the most extensive range of rights settings for user accounts.

[#100]
=== Setting visibilities

In the **Visibility** tab, you define which functions and options are visible to users when opening a menu. Without visibility rights, a warehouse or orders of a certain status, for example, are invisible to the user.

.A variable user account's **Rights** tab; **Visibility** tab
[cols="1,3"]
|====
|Setting |Explanation

|**Sales warehouse; +
Repair warehouse; +
Storage warehouse; +
Transit warehouse; +
Distribution warehouse; +
Special warehouse**
|Give rights for warehouses to the user. Only previously created warehouse types are available. For further information about warehouse types, refer to the <<stock-management/setting-up-a-warehouse#300, Setting up a warehouse>> page of the manual. +
+
+
+
A special warehouse is a warehouse of the warehouse type **Other**.

|**Visible order status**
|Select which order statuses should be **visible** to the user. The user will see orders that are in this status only.

|**Selectable order status**
|Select which order statuses the user should be allowed to apply.

|**Clients (stores)**
|Select one, several or all clients visible to the user. Users will only be able to see those areas that they were given access to in the Rights tab. If no client is selected, then specific rights such as the right to access certain **menus** will not go into effect. This is because the user will not have access to any of the clients. +
**All** = The user has access to all clients. +
**Default** = The user has access to the default store.

|**Ticket status**
|Select ticket statuses. Users will be able to view and edit tickets that are in these statuses. +
**Invisible** = The user will not see tickets with this status. +
**Visible** = The user will see all tickets that are in this status. +
**Own only** = The user will only see tickets that are in this status and that they own. +
All tickets are listed in the ticket overview, i.e. also those tickets that are not visible to the user account. However, the user is unable to open invisible tickets.
|====

[#110]
=== Activating menus

The structure of the **Menu** tab corresponds to the menu structure in plentymarkets in order to facilitate finding the desired functions. Activate a menu to activate all of the submenus that it contains. If you want to activate individual submenus only, then you have to do so within the lowest level of this menu.

Assign every user account of the **Variable** class only those rights required for their field of work. This way, security is increased and errors can be prevented in your plentymarkets system.

[.instruction]
Activating the rights to menus:

. Go to **System » Settings » User » Accounts**.
. Open a user account.
. Click on the **Right** tab.
. Click on the **Menu** tab.
. Activate the menus that the user account should have access to.
. **Save** the settings.

[#115]
=== Activating REST API rights

In the **REST API** tab, you specify which rights for the REST API are granted to a user account of the **Variable** class. No REST API rights are activated by default. User accounts of the **Admin** class have all rights. Rights are granted separately for different modules and sub-modules of the REST API. Under **Authorisation**, for example, you define whether the REST API user account can display rights or display, create and delete user roles.

[.instruction]
Activating REST API areas:

. Go to **System » Settings » User » Accounts**.
. Open a user account.
. Click on the **Right** tab.
. Click on the **REST API** tab.
. Activate entire areas or expand areas to activate individual rights that the user account should have access to.
. **Save** the settings.

Subsequently added, subordinated rights of a main module will be activated automatically for a user account if the main module is activated. You can deactivate this function and manually activate new, subordinated rights.

[.instruction]
Manually activate new, subordinated rights:

. Go to **System » Settings » User » Accounts**.
. Open a user account.
. Click on the **Right** tab.
. Click on the **REST API** tab.
. Click on **Activate new, subordinated rights manually**.
. **Save** the settings.

[#120]
=== Activating SOAP API calls

In the **SOAP API** tab, specify which of the SOAP API link:{imagesdir}/basics/assets/SOAP-Version-200-Documentation-2016-07-14.zip[calls] the user should be allowed to edit. No API rights are assigned by default. Not even for user accounts that are assigned to the **API** class.

[.instruction]
Activating SOAP API areas:

. Go to **System » Settings » User » Accounts**.
. Open a user account.
. Click on the **Right** tab.
. Click on the **SOAP API** tab.
. Activate entire areas or expand areas to activate individual calls that the user account should have access to.
. **Save** the settings.

[#130]
=== Apply rights

The **Transfer** tab allows you to transfer an individual user account’s rights to another user account that belongs to the user class **Variable** or **Admin**. The settings that were saved in the Right tab will then be transferred to the selected user account. You will see the user accounts to which rights can be transferred.

[.instruction]
Transferring rights:

. Go to **System » Settings » User » Accounts**.
. Open a user account.
. Click on the **Right** tab.
. Click on the **Transfer** tab.
. Activate the areas that you want to transfer.
. Activate the users to whom you want to transfer.
. Click on **Apply the selected rights to the users**.

[#140]
=== Activating app rights

In the **Mobile** tab, you define which functions and key figures are visible to variable user accounts in the plentymarkets app.

[.instruction]
Activating the rights for mobile access:

. Go to **System » Settings » User » Accounts**.
. Open a user account.
. Click on the **Right** tab.
. Open the **Mobile** tab.
. Activate the functions and key figures that the user account should have access to in the app.
. **Save** the settings.

[#145]
=== Unblocking the login

Once an incorrect password is entered several times in succession, the login is blocked for the user account for a certain time. The login can be unblocked by an administrator in the menu **System » Settings » User » Accounts » Open user** by clicking on the button **Unblock login**.

[#70]
== Create roles

Roles are used for grouping user accounts and assigning the same rights to multiple user accounts without making changes to every single user account.

[.instruction]
Creating a new role:

. Go to **System » Settings » User » Roles**.
. Click on **New role**. +
→ The **New Role** window opens.
. Enter a **Name** for the role.
. **Save** the settings. +
→ The role opens in a new tab and can be edited.

A role must be edited in order to define rights that are assigned to user accounts with this role. Therefore, edit the role after creating it.

[#80]
== Edit roles

After creating a role, it will open in a new tab for editing. The role is also added to the role overview so that you can open and edit it later. Roles are listed alphabetically in the overview. Every role is divided into 3 tabs. In the **Settings** tab, you can change the role's name. In the **User** tab, you link user accounts to this role. In the **Rights** tab, you assign rights to the role. The same settings used for user accounts of the Variable class are also available for roles. For further information about rights, refer to the <<basics/working-with-plentymarkets/manage-users#90, Assigning rights>> chapter.

Users of the Admin and Variable classes can create roles. User accounts of the Variable class must have the corresponding rights to do so.

[.instruction]
Linking user accounts to roles:

. Go to **System » Settings » User » Roles**.
. Open a role.
. Click on the **User** tab.
. Select user accounts from the **Available users** column.
. Click on the **single arrow pointed to the right** to transfer the selected user accounts to the **Assigned users** column.
. Alternative: Drag and drop a user account to the **Assigned users** column.
. **Save** the settings.

[TIP]
.Moving several user accounts at once
====
Press and hold **Ctrl** or **cmd**, then select multiple users by left clicking on them to assign them at the same time. The lower arrow buttons will transfer all users.
====

The role is assigned to the user accounts in the **Assigned users** column. The **roles** in the **Master data** tab of a user account automatically match the settings made here. Assigned roles can be changed in both places of the system.

[.instruction]
Linking roles to a user account:

. Go to **System » Settings » User » Accounts**.
. Open a user account.
. Select one, several or all of the roles in the **Roles** setting.
. **Save** the settings.

[TIP]
.Linking user roles to users of the Admin class
====
Administrators have all rights. However, it is important that roles are assigned to administrators for some processes. For example, administrators only receive role-specific emails when linked to the corresponding role.
====

[.subhead]
Example of use

The administrator of the company MyStore creates multiple roles. All the rights to be assigned to every user account are included in the Employee role. With this role, it is no longer necessary to assign these rights to every single user. Also, changes to rights concerning all user accounts can be made in the Employee role. In addition to this role, the administrator creates the Warehouse technician and Accounting roles - specific roles for a small group of users only.

[[table-example-for-roles]]
.Example for roles
[cols="1,3,3"]
|====
|Role |Rights: Visibility |Rights: Menu

|**Employees**
|Clients (stores) » Standard
|Start » Webmail +
Start » Forum

|**Warehouse technician**
|Warehouse
|System » Stock » Warehouse +
Stock +
Orders » Fulfilment

|**Accounting**
|
|Start » Vacation +
System » Client » Select client » Accounting
|====

Mr. Doe is a logistics specialist at MyStore and receives the Employee and Warehouse technician roles. If a user account has several roles, the user rights are added up. Therefore, Mr. Doe receives the rights **Clients (stores)**, **Webmail** and **Forum** from the Employee role as well as the rights **Warehouse**, **Stock** and **Fulfilment** from the Warehouse technician role. However, he doesn't have the **Vacation** and **Accounting** rights because the Accounting role wasn't assigned to his user account.

== Copying roles

If you need an additional role which slightly differs from an existing role, copy the existing role and make changes in the **Right** tab of the copy.

[.instruction]
Copying a role:

. Go to **System » Settings » User » Roles**.
. Select a role.
. Click on **Copy** in the toolbar. +
→ The **Copy role** window opens.
. Enter a name.
. **Save** the settings. +
→ The role is copied and the new role opens.

== Sending an email to all user accounts of a role:

Roles allow you to send emails to all user accounts of a specific role. For this purpose, an email address must be saved in the user account.

[.instruction]
Sending an email to all user accounts of a role:

. Go to **System » Settings » User » Roles**.
. Select a role.
. Click on **Send email** in the toolbar. +
→ The email program opens. The email addresses of all user accounts of this role are entered in the recipient field.

[#60]
== Searching user accounts

Filters help you to search for user accounts. Use the **Class** filter to display only user accounts of a certain class, e.g. **Variable**. If no filters are used, all user accounts are displayed in the overview. The following elements and functions are available in the **User** menu.

[[filter-options-for-users]]
.Filter options for users
[cols="1,3"]
|====
|Setting |Explanation

|**Search**
|Perform a search. Select appropriate filter options for the search beforehand.

|**Reset**
|Reset the filters to their original settings.

|**ID**
|Enter an ID to search for the user account that has this ID.

|**Name**
|Enter the name to search for the user accounts with this name.

|**Class**
|Select a class to search for user accounts with this specific class.

|**Roles**
|Select one, several or all roles to search for user accounts with these roles.
|====

[#150]
== Linking roles and processes

You can also use roles for the <<automation/processes/setting-up-processes#, processes>>.

[.instruction]
Linking roles and processes:

. Go to **System » Processes » Per role**.
. Click on the **arrow** in the line of a particular **role**. Then click on **New process** (image 1).
. Enter a **Name** for the role.
. Select the setting **Role** from the **Visibility** drop-down list. +
→ The option **Role** is displayed.
. Select a **Role** from the drop-down list.
. Select whether you want owners assigned to this role to be able to **change** the settings.
. Select the **warehouse** for the process and a **colour**.
. **Save** the settings.

The processes are displayed for the selected role. Due to the visibility setting, the process will be available to user accounts with the corresponding role only.

== Creating an account for the plentymarkets forum

The plentymarkets forum is a knowledge base that keeps on growing. It already contains many solved support queries. Our developers and other plentymarkets customers will help you solve technical queries you might have. In addition, you will find tips for working with plentymarkets and can exchange ideas with other plentymarkets customers. Proceed as described below to create an account for the plentymarkets forum. **Admin** class user accounts can also create forum accounts for other user accounts using this method.

[.instruction]
Creating an account for the plentymarkets forum:

. Go to **System » Settings » User » Accounts**.
. Click on **Open user**. +
→ The user account opens in a new tab.
. In the **plentymarkets Forum** area, click on **Create account** +
→ The forum account is created.

[#160]
== Limitation of simultaneously logged in users in the back end

Due to the new tariff models, for customers making a new contract or a tariff change, a modification concerning the simultaneously logged in users has been made. Depending on the tariff, there is now a limitation in the number of those. *Customers with an existing tariff are not concerned.*

=== Exceeding the maximum number of simultaneously logged in users

Is the maximum number of simultaneously logged in users reached or exceeded, the user gets an error message.
Via the link in the error message, the admin is directly forwarded to the session management. This allows the admin to terminate the currently running sessions so he can enable the login of another user. The login is valid for 10 minutes. Afterwards, the admin is automatically logged out. +
The admin can access the Session Management in the back end via *System » Settings » User » Session management* as well as via the user icon on the top right.
In order to terminate one or more sessions, select the desired sessions and click *Terminate selected sessions*.
