= Setting up REST API
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:description: Use REST API to communicate with external systems.
:position: 40
:url: basics/admin-tasks/rest-api

The term REST API is made up of two acronyms. REST stands for _Representational State Transfer_, API for _application programming interface_. Essentially this means that you can use external calls to communicate with your plentymarkets system in certain ways. This allows you to, for example, retrieve the data of all your contacts at once.

Even if you do not intend to use REST API in general, you may still want to use plugins that utilize these so-called routes to interact with your system. Some examples include link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/ebayoauth2_4787[eBay OAuth2^] and link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/etsy_4689[Etsy^]. For these plugins to work properly, you must grant them certain permissions.

[#end-users]
== For end users

If you want to use plugins that require REST routes, you must grant them permission to access certain parts of your system. To do so, first create a new user of the class Variable.

[.instruction]
Creating a Variable user account:

. Go to *System » System settings » Settings » User » Accounts*.
. Click on *New*. +
→ The *Create new user* window opens.
. Enter the *User name*.
. Enter the *Real name*.
. Enter the *Password*.
. Repeat the password.
. Select the User class *Variable*.
. *Save* the settings.

The user name must not contain any spaces and must have at least 5 characters.

You can specify which rights to grant the user in the REST API tab of the user’s account settings. No REST API rights are activated by default. Rights are granted separately for different modules and sub-modules of the REST API. Under Authorisation, for example, you define whether the REST API user account can display rights or display, create and delete user roles.

[.instruction]
Activating REST API areas:

. Go to *System » System settings » Settings » User » Accounts*.
. Open a user account.
. Click on the *Right* tab.
. Click on the *REST API* tab.
. Activate entire areas or expand areas to activate individual rights that the user account should have access to.
. *Save* the settings.

Subsequently added, subordinated rights of a main module will be activated automatically for a user account if the main module is activated. You can deactivate this function and manually activate new, subordinated rights.

[.instruction]
Manually activate new, subordinated rights:

. Go to *System » System settings » Settings » User » Accounts*.
. Open a user account.
. Click on the *Right* tab.
. Click on the *REST API* tab.
. Click on *Activate new, subordinated rights manually*.
. *Save* the settings.

For information on which rights to grant an account, see the plugin’s user guide.

[#developers]
== For developers

If you are interested in developing and selling a plugin that utilizes REST API, you can upload it to the link:https://marketplace.plentymarkets.com/en[plentyMarketplace^] free of charge. In addition to plentymarkets plugins, it is also possible to integrate external offers. link:https://www.plentymarkets.co.uk/company/be-our-plentymarketplace-partner/[Register here to become a partner.^]

See our developers site for link:https://developers.plentymarkets.com/rest-doc/gettingstarted[general information^] on the plentymarkets REST API as well as the link:https://developers.plentymarkets.com/rest-doc[available routes^]. You can also check our tutorials for some examples of how to implement them:
====
* link:https://developers.plentymarkets.com/tutorials/customerdata[Create a contact and an account^]
* link:https://developers.plentymarkets.com/tutorials/order-data[Retrieve order data^]
* link:https://developers.plentymarkets.com/tutorials/item-data[Create an item^]
* link:https://developers.plentymarkets.com/tutorials/bulk-routes[Use bulk routes^]
====