= Your plentymarkets account
:lang: en
include::{includedir}/_header.adoc[]
:position: 10
:url: basics/admin-tasks/your-account
:id: AIXO9P7
:author: team-cloud

Open the menu *plentymarkets Logo (Start) » My account* to see information about your plentymarkets system. You can make changes to the information saved here.
For example, you can:

* view and edit your contract with plentymarkets.
* book an additional client (store).
* modify your contact information.
* grant partner agencies access to your system.

[#20]
== Your contract with plentymarkets

Open the menu *plentymarkets Logo (Start) » My account » Contracts* to see and edit information about your contract with plentymarkets.
For example, you can:

* <<basics/admin-tasks/your-account#30, switch to a different rate>>
* <<basics/admin-tasks/your-account#40, view your booked services and cancel them as needed>>
* <<basics/legal-requirements/gdpr#500, view documents that are relevant to GDPR>>

[TIP]
.Service Centre is being phased out
====
Perhaps you can remember previously looking at your contract information in the menu *plentymarkets Logo (Start) » Service centre*. The Service Centre is being phased out.
Therefore, we recommend that you get acquainted with the “My account” area before the Service Centre is completely removed.
====

[#30]
=== Changing your contract

plentymarkets grows along with your needs.
You can decide, e.g. which modules your company needs and approximately how many orders you’ll process with plentymarkets each month.
We will provide you with the necessary system performance.

You can use the “My account” area to make changes to your plentymarkets contract any time, i.e. even while the system is up and running.
It makes sense to change your contract e.g. if you generate more orders than are included in your current rate. It is possible to book a higher rate at any time. If you book a lower rate, the change will go into effect once the regular duration of your current contract has ended.

[.instruction]
Changing the contract:

. Go to *plentymarkets Logo (Start) » My account*. +
*_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen. +
→ The “My account” area opens in a new browser tab.
. Click on icon:file-text[role="darkGrey"] *Contracts*. +
→ You will see information about your current contracts.
. Click on icon:pencil[role="darkGrey"] *Edit contract*. +
→ The configurator appears.
. Make changes to the contract information as desired.

[#40]
=== Viewing services and cancelling them as needed

You can see all of your billed services in the “My account” area. If needed, you can cancel individual modules or your entire contract with plentymarkets.

[.instruction]
Viewing and cancelling services:

. Go to *plentymarkets Logo (Start) » My account*. +
*_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen. +
→ The “My account” area opens in a new browser tab.
. Click on icon:file-text[role="darkGrey"] *Contracts*. +
→ You will see information about your current contracts.
. Expand the contract information (icon:chevron-down[role="darkGrey"]). +
→ Click on icon:ban[role="red"] [red]#Cancel contract# in the upper right corner to request that your entire contract be cancelled. +
→ Click on icon:trash[role="darkGrey"] *Cancel now* next to a specific module to only cancel this one specific service.


[#370]
=== Practical example: Booking an additional store

In plentymarkets, the term <<online-store#, client (store)>> refers to an additional online store, which is managed with the same plentymarkets system as the default store.
Existing online stores are displayed in the “My account” area. You can book additional stores as needed.

[IMPORTANT]
.Domain settings for clients (stores)
====
You need to have a <<basics/admin-tasks/plentymarkets-account#, domain>> before you can order a client (store). You have to create this domain for the main system beforehand.
====

[.instruction]
Ordering a client (store):

. Go to *plentymarkets Logo (Start) » My account*. +
*_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen. +
→ The “My account” area opens in a new browser tab.
. Click on icon:file-text[role="darkGrey"] *Contracts*. +
→ You will see information about your current contracts.
. Click on icon:pencil[role="darkGrey"] *Edit contract*. +
→ The configurator appears.
. Make changes to the contract information as desired.

[#440]
== Granting certified agencies access to the system

Open the menu *plentymarkets Logo (Start) » My account » Agencies* to grant certified service providers access to your system.
It makes sense to grant a service provider access to your system, e.g. if you hired a design agency to create your website or if you work with a consultant.
The service provider will be given unlimited access to your system, i.e. admin access.

[TIP]
.Decide which functions and menus should be accessible!
====
When giving an agency access to your system, you grant it unlimited, admin access.

If you would prefer to only give the agency access to specific functions or menus, then <<basics/admin-tasks/manage-users#, create a new user account>>, e.g. a back end account, and customise its access rights.
====

[discrete]
==== Granting access

Proceed as described below to grant an agency and/or consultant access to your system:

[.instruction]
Assigning service providers:

. Go to *plentymarkets Logo (Start) » My account*. +
*_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen. +
→ The “My account” area opens in a new browser tab.
. Click on icon:handshake-o[role="darkGrey"] *Agencies*. +
→ You will see information about the agencies that you already work with.
. Click on icon:plus[role="darkGrey"] *Add agency*. +
→ You will see a list of certified service providers.
. Click on icon:plus[role="darkGrey"] *Add* next to whichever agency should be given access to your system.

*_Note_*: You can revoke this access at any time.
