= OTTO market
:lang: de
include::{includedir}/_header.adoc[]
:keywords: OTTO market, OTTO, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zu OTTO market in deinem plentymarkets System ein.
:position: 20
:url: maerkte/otto/otto-market
:id: SMKVRT7

Auf dieser Handbuchseite erhältst du Informationen zu OTTOs Marktplatzmodell OTTO market.

[#100]
== OTTO market

OTTO market ist das Marktplatzmodell von OTTO. Du wirst als Verkäufer an deinen Produkten angezeigt und die Kundenkommunikation wird von dir selbst verwaltet.

[#200]
== OTTO market in plentymarkets einrichten

OTTO market wird im Menü *Einrichtung » Assistenten* mit zwei Assistenten eingerichtet. Durchlaufe im Menü *Einrichtung » Assistenten* die folgenden Assistenten, um den Marktplatz in deinem plentymarkets System einzurichten:

* *OTTO market Grundeinstellungen*: Mit diesem Assistenten richtest du dein OTTO market-Konto in plentymarkets ein.
* *OTTO market Kataloge erstellen*: Mit diesem Assistenten erstellst du Kataloge und Katalog-Templates für OTTO market. Mit Katalogen werden deine Artikel zu OTTO market exportiert. Weitere Informationen zu Katalogen erhältst du auf der Handbuchseite <<daten/daten-exportieren/kataloge-verwalten#, Kataloge verwalten>>.

[#250]
=== Weitere Einstellungen in plentymarkets

Damit du OTTO market in plentymarkets nutzen kannst, sind nachdem du die Assistenten durchlaufen hast noch einige wenige Einstellungen an deinen Artikeln nötig, damit alle Daten korrekt übertragen werden können.

* Varianten eines Artikels im Tab *Einstellungen* einer Variante aktivieren
* Varianten müssen mit der Eigenschaft für OTTO market-Kategoriegruppen verknüpft sein

Die Anbindung von OTTO market stellt folgende automatisierte Prozesse bereit:

* Auftragsimport alle 15 Minuten
* Preis- und Bestandsabgleich alle 15 Minuten
* Artikeldaten werden einmal täglich aktualisiert

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die du auf OTTO market verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für OTTO market einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *OTTO market*.
. Aktiviere die Option *Web-API*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Artikel ist auf OTTO market verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

[#350]
== Verfügbarkeit am Bild einstellen

Damit Artikelbilder auf OTTO market angezeigt werden, muss im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Bilder* die Verfügbarkeit *OTTO market* am Bild hinzugefügt werden.

[.instruction]
Verfügbarkeit am Bild einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Bilder*.
. Aktiviere in der Dropdown-Liste *Verfügbarkeit* die Option *OTTO market*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Bild wird am Artikel auf OTTO market angezeigt.

[#400]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft OTTO market einen Verkaufspreis festzulegen. Dieser Preis wird auf OTTO market angezeigt.

[.instruction]
Verkaufspreis für OTTO market festlegen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *OTTO market*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#500]
== Ereignisaktionen einrichten

Richte <<automatisierung/ereignisaktionen#, Ereignisaktionen>> ein, um OTTO market automatisch über Änderungen des Auftragsstatus zu informieren. Folgende Ereignisaktionen stehen für OTTO market zur Verfügung:

* Auftragsbestätigung an OTTO melden
* Versandinformation an OTTO melden
* Auftragsstornierung an OTTO melden
* Retoure an OTTO melden
* Ablehnung der Retoure an OTTO melden

 In den folgenden Kapiteln werden Ereignisaktionen zum Generieren eines DHL-Retourenlabels und zum Senden einer Auftragsbestätigung an OTTO market beschrieben. Richte weitere Ereignisaktionen auf die gleiche Weise ein.

[#550]
=== DHL-Retourenlabel generieren

Wenn OTTO market-Aufträge in dein plentymarkets System importiert wurden, müssen für diese Aufträge DHL-Retourenlabels generiert werden, bevor du die Aufträge bei OTTO market bestätigst. Mit der Aktion *DHL Retoure Online-Label generieren* wird automatisch eine Tracking-Nummer für eine Retoure (retTrackingNumber) erstellt, die am Auftrag hinterlegt wird. Dadurch kann sichergestellt werden, dass es eine Tracking-Nummer für eine Retoure gibt, falls Kunden einen Artikel zurücksenden möchten. +

Damit die Tracking-Nummer zusammen mit der Versandbestätigung an OTTO market gesendet wird, musst du zwei Ereignisaktionen erstellen, die hintereinander ausgelöst werden: 1. *DHL Retoure Online-Label generieren* und 2. *Auftragsbestätigung an OTTO melden*.

*Hinweis:* Das Retourenlabel kann momentan nur mit DHL generiert werden. Weitere Versanddienstleister folgen.

[TIP]
.Plugin DHL Retoure Online installieren
====
Um ein DHL-Retouren-Label generieren zu können, muss das Plugin *DHL Retoure Online* in deinem plentymarkets System installiert, aktiviert und eingerichtet sein. Das Plugin erhältst du im link:https://marketplace.plentymarkets.com/plugins/integration/dhlretoureonline_6714[plentyMarketplace^].
====

Wie du die Ereignisaktion einrichtest, mit der ein DHL-Retourenlabel generiert wird, ist im Folgenden beschrieben.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<dhl-retouren-label-otto>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<dhl-retouren-label-otto>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[dhl-retouren-label-otto]]
.Ereignisaktion zum Erstellen eines DHL-Retourenlabels
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Neuer Auftrag*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*OTTO market*

|*Aktion*
|*Plugins > DHL Retoure Online-Label generieren*
|
|====

[#600]
=== Auftragsbestätigung an OTTO melden

Die Ereignisaktion, mit der du die Auftragsbestätigung an OTTO meldest, muss ausgelöst werden, nachdem ein DHL-Retourenlabel generiert wurde. Wie du die Ereignisaktion zur Auftragsbestätigung einrichtest, ist im Folgenden beschrieben.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<auftragsbestaetigung-otto>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<auftragsbestaetigung-otto>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[auftragsbestaetigung-otto]]
.Ereignisaktion um Auftragsbestätigung an OTTO zu melden
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Statuswechsel: beliebigen Status vor Versand wählen*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*OTTO market*

|*Aktion*
|*Plugins > Auftragsbestätigung an OTTO melden*
|
|====
