= OTTO market
:lang: de
include::{includedir}/_header.adoc[]
:keywords: OTTO market, OTTO, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zu OTTO market in deinem plentymarkets System ein.
:position: 20
:url: maerkte/otto/otto-market
:id: SMKVRT7

Auf dieser Handbuchseite erhältst du Informationen zu OTTOs Marktplatzmodell OTTO market.

== OTTO market

OTTO market ist das Marktplatzmodell von OTTO. Du wirst als Verkäufer an deinen Produkten angezeigt und die Kundenkommunikation wird von dir selbst verwaltet.

== OTTO market in plentymarkets einrichten

OTTO market wird mit Assistenten eingerichtet. Durchlaufe im Menü *Einrichtung » Assistenten* die folgenden Assistenten, um den Marktplatz in deinem plentymarkets System einzurichten:

* *OTTO market Grundeinstellungen*: Mit diesem Assistenten richtest du dein OTTO market-Konto in plentymarkets ein.
* *OTTO market Kataloge erstellen*: Mit diesem Assistenten erstellst du Kataloge und Katalog-Templates für OTTO market. Mit Katalogen werden deine Artikel zu OTTO market exportiert. Weitere Informationen zu Katalogen erhältst du auf der Handbuchseite <<daten/daten-exportieren/kataloge-verwalten#, Kataloge verwalten>>.

=== Weitere Einstellungen in plentymarkets

Damit du OTTO market in plentymarkets nutzen kannst, sind nachdem du die Assistenten durchlaufen hast noch einige wenige Einstellungen an deinen Artikeln nötig, damit alle Daten korrekt übertragen werden können.

* Artikelverfügbarkeit im Tab *Einstellungen* eines Artikels einstellen
* Varianten eines Artikels im Tab *Einstellungen* einer Variante aktivieren
* Varianten müssen mit der Eigenschaft für OTTO market-Kategoriegruppen verknüpft sein

Die Anbindung von OTTO market stellt folgende automatisierte Prozesse bereit:

* Auftragsimport alle 15 Minuten
* Preis- und Bestandsabgleich alle 15 Minuten
* Artikeldaten werden einmal täglich aktualisiert

== Ereignisaktionen einrichten

Richte <<automatisierung/ereignisaktionen#, Ereignisaktionen>> ein, um OTTO market automatisch über Änderungen des Auftragsstatus zu informieren. Folgende Ereignisaktionen stehen für OTTO market zur Verfügung:

* Auftragsbestätigung an OTTO melden
* Versandinformation an OTTO melden
* Auftragsstornierung an OTTO melden
* Retoure an OTTO melden
* Ablehnung der Retoure an OTTO melden

Beispielhaft wird eine Ereignisaktion beschrieben, mit der du die Auftragsbestätigung an OTTO meldest. Richte weitere Ereignisaktionen auf die gleiche Weise ein.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-auftragsbestätigung-otto>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-auftragsbestätigung-otto>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-auftragsbestätigung-otto]]
.Ereignisaktion um Auftragsbestätigung an OTTO zu melden
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Neuer Auftrag*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*OTTO market*

|*Aktion*
|*Plugins > Auftragsbestätigung an OTTO melden*
|
|====

[.subhead]
Ereignisaktion erstellen: DHL-Retouren-Label generieren

Wenn du einen OTTO market-Auftrag in deinem plentymarkets System angelegt hast, musst du für diesen Auftrag ein DHL-Retourenlabel generieren, bevor du den Auftrag bestätigst. Mit der Ereignisaktion *DHL-Retouren-Label generieren* wird eine Tracking-Nummer für eine Retoure (retTrackingNumber) erstellt, die am Auftrag hinterlegt wird. Dadurch kann sichergestellt werden, dass es eine Tracking-Nummer gibt, falls der Kunde den Artikel zurücksenden möchte.

[TIP]
.DHL-Zugangsdaten hinterlegen
====
Um ein DHL-Retouren-Label generieren zu können, musst du *DHL Retoure Online* im Menü *Einrichtung » Aufträge » Versand » Dienstleister » DHL Retoure Online* vollständig eingerichtet haben. Dazu musst du u.a. auch deine DHL-Zugangsdaten, bestehend aus Benutzername und Passwort, hinterlegen.
====


//Ereignisaktion erstellen: DHL-Retouren-Label generieren
//zwischen Auftragsanlage und Auftragsbestätigung muss ein DHL-Retourenlabel generiert werden (zukünftig: Hermes oder DPD), damit retTrackingNumber generiert und zum Auftrag hinzugefügt werden kann (damit es eine return tracking number gibt, falls der Kunde die Ware zurückschickt)
