= OTTO
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: Otto Direktversand, Otto Cooperation, Otto Integration, Otto interface
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz OTTO in deinem plentymarkets System ein.
:position: 10
:url: maerkte/otto/otto-interface
:id: VM4QQ6Y

Auf dieser Handbuchseite erhältst du Informationen zu OTTO.

== OTTO

link:https://www.otto.de/[OTTO^]{nbsp}icon:external-link[] ist Teil der Otto Group und eines der erfolgreichsten Online-Versandhandelsunternehmen Deutschlands. +

Bei OTTO handelt es sich um einen Online-Shop, das heißt, du verkaufst im Namen von OTTO. Auch die Kommunikation mit Kund:innen wird von OTTO übernommen.

* OTTO bietet außerdem das <<maerkte/otto/otto-market#, Marktplatzmodell OTTO Market>> an. Bei OTTO Market wirst du als Verkäufer:in an deinen Produkten angezeigt. Die Kommunikation mit Kund:innen läuft aber über OTTO. Mit plentymarkets kannst du auch Produkte auf OTTO Market verkaufen. +

IMPORTANT: Aus Datenschutzgründen ist der Inhalt der Handbuchseite OTTO nur für Kund:innen zugänglich, die einen OTTO-Vertrag haben. Die OTTO-Handbuchseite steht dir als OTTO-Partner:in im plentymarkets link:https://forum.plentymarkets.com/[Forum^]{nbsp}icon:external-link[] innerhalb der OTTO-Kategorie zur Verfügung.
