= Benutzerkonto personalisieren
:lang: de
include::{includedir}/_header.adoc[]
:description: Arbeiten mit plentymarkets: Richten Sie sich z.B. eigene Shortcuts und eine Signatur ein und personalisieren Sie so Ihr eigenes Benutzerkonto im plentymarkets System.
:position: 50

Diese Handbuchseite beschreibt Einstellungen in plentymarkets, die Sie einmalig vornehmen, um Ihr Benutzerkonto zu personalisieren. Selbstverständlich haben Sie die Möglichkeit, Ihre Angaben und Einstellungen jederzeit anzupassen.

toc::[]
[#10]
== Grußformel einrichten

Im Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten** im Bereich **Mein Konto** geben Sie einen Text ein, der Ihren Nachrichten und Kommentaren im Ticketsystem automatisch als Grußformel angefügt wird. Dieser besteht in der Regel nur aus einem Briefabschluss sowie Ihrem Namen. Beim Versenden von E-Mails aus dem Ticketsystem wird erst die Grußformel und dann die Signatur  automatisch an die E-Mail angehängt. Wie Sie die Signatur einrichten, wird im folgenden Kapitel beschrieben.

[.instruction]
Grußformel einrichten:

. Öffnen Sie das Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten**.
. Öffnen Sie **Mein Konto**.
. Wechseln Sie in das Tab **Grußformel**.
. Geben Sie Ihre Grußformel ein.
. **Speichern** Sie die Einstellungen.

[#20]
== Signatur einrichten

Im Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten** im Bereich **Mein Konto** geben Sie einen Text ein, der Ihren Nachrichten und Kommentaren im Ticketsystem automatisch als Signatur angefügt wird. Diese besteht in der Regel aus Ihren Kontaktdaten sowie Angaben zum Amtsgericht und Handelsregisternummer. Je nach Rechtsform des Unternehmens gehört die Angabe des Firmennamens, des Geschäftsführers sowie ggf. der USt-IdNr. zu den Pflichtangaben. Beim Versenden von E-Mails aus dem Ticketsystem wird erst die Grußformel  und dann die Signatur  automatisch an die E-Mail angehängt.

[TIP]
.Template-Variable für die Signatur
====
Die Template-Variablen **$Signature** bzw. **$SignatureHTML** beinhalten die Grußformel.
====

[.instruction]
Signatur einrichten:

. Öffnen Sie das Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten**.
. Öffnen Sie **Mein Konto**.
. Wechseln Sie in das Tab **Signatur**.
. Geben Sie Ihre Signatur ein.
. **Speichern** Sie die Einstellungen.

[WARNING]
.Pflichtangaben in E-Mails
====
In Deutschland entsprechen seit Anfang 2007 die Pflichtangaben in E-Mails denen der Geschäftsbriefe des Unternehmens. Bei Nichtbeachtung besteht die Gefahr eines Zwangsgeldes oder einer kostenpflichtigen Abmahnung durch einen Mitbewerber. +
Informieren Sie sich also über die rechtlichen Vorschriften zur Signatur in Ihrem Land und befragen Sie bei Bedarf Ihren Rechtsbeistand.
====

[#30]
== Persönliche Einstellungen im Bereich Mein Konto vornehmen

Im Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten** im Bereich **Mein Konto » Persönliche Einstellungen** nehmen Sie Einstellungen vor, die nur für den im System angemeldeten Benutzer gelten. Deshalb ist das Tab für Sie auch nur in Ihrem eigenen Benutzerkonto sichtbar. Das Tab unterteilt sich in 3 Tabs mit Einstellungen, die nur Sie persönlich betreffen. Diese Tabs sind **Allgemein**, **Shortcuts** und **Favoriten**.

[#40]
=== Allgemeine Einstellungen vornehmen

Legen Sie im Tab **Allgemein** fest, ob Sie beim Schließen eines Fensters gewarnt werden möchten, wenn noch Tabs offen sind. Außerdem können Sie hier die benutzerspezifischen Einstellungen zurücksetzen.

[cols="a,a"]
|====
|Button |Erläuterung

|**Meldungen zurücksetzen**
|Meldungen, z.B. die Meldung zum Neuladen von plentymarkets für Aktualisierungen, können durch einen Klick deaktiviert werden. Diese Einstellung wird benutzerabhängig gespeichert. Durch erneuten Klick werden alle relevanten Einstellungen des Benutzers wieder zurückgesetzt, d.h. alle deaktivierten Meldungen werden wieder angezeigt.

|**Alles zurücksetzen**
|Setzt alle benutzerabhängig gespeicherten Einstellungen, z.B. die oben genannten Meldungen, Spaltengrößen und Spalteninhalte bei Tabellen, gewählte Favoriten etc. zurück.

|**Warnen, wenn Tabs offen sind und das Fenster geschlossen wird**
|**Aktivieren** = Beim Schließen eines Fensters wird eine Warnung ausgegeben, wenn noch Tabs geöffnet sind. +
**Deaktivieren** = Das Fenster wird ohne Warnung geschlossen.
|====

__Tab. 1: Optionen im Tab **Persönliche Einstellungen » Allgemein**__

[#50]
=== Shortcuts einrichten

In diesem Tab sind Standard-Shortcuts hinterlegt, die Sie für verschiedene wiederkehrende Funktionen nutzen, z.B. das Öffnen von wichtigen Menüs in plentymarkets und das Wechseln zwischen Tabs und Tab-Ebenen. So wird zum Beispiel mit der Tastenkombination **Alt + I** die Artikelübersicht geöffnet. Mit **Alt + W** wird das Tab wieder geschlossen.

Erfahren Sie mehr über Shortcuts im folgenden Videotutorial:

video::99954261[vimeo]
[IMPORTANT]
.Shortcuts sind benutzerspezifisch und nicht alle Kombinationen sind möglich
====
Das Tab ist nur für den eigenen Benutzer sichtbar und kann nur von diesem Benutzer bearbeitet werden.

Verwenden Sie keine systemspezifischen Shortcut-Kombinationen. Diese Shortcut-Kombinationen sind je nach Betriebssystem unterschiedlich. Beispiel: die **F**-Tasten. +
Die Kombination **cmd / Strg + W** ist nicht möglich, da sie vom Browser reserviert ist.
====

[cols="a,a"]
|====
|Shortcut |Erläuterung

2+|Globale Shortcuts

|**Alt + W**
|Schließt das aktive Tab.

|**Shift + Alt + DOWN (Pfeiltaste nach unten)**
|Wechselt eine Tab-Ebene nach unten.

|**Shift + Alt + UP (Pfeiltaste nach oben)**
|Wechselt eine Tab-Ebene nach oben.

|**Shift + Alt + RIGHT (Pfeiltaste nach rechts)**
|Wechselt ein Tab nach rechts.

|**Shift + Alt + LEFT (Pfeiltaste nach links)**
|Wechselt ein Tab nach links.

|**Alt + R**
|Lädt das aktive Tab neu.

|**Alt + ESC**
|Loggt den Benutzer aus und sperrt das Backend.

2+|Bereiche öffnen

|**Alt + I**
|Öffnet das Menü **Artikel » Artikel bearbeiten**.

|**Alt + O**
|Öffnet das Menü **Aufträge » Aufträge bearbeiten**.

|**Alt + Y**
|Öffnet das Menü **Artikel » Kategorien**.

|**Alt + C**
|Öffnet das Menü **Kunden » Kunden bearbeiten**.

|**Alt + T**
|Öffnet das Menü **Kunden » Ticketsystem**.

|**Alt + N**
|Öffnet das Menü **Kunden » Kunden bearbeiten** und öffnet das Tab **Neuer Kunde**.

|**Alt + M**
|Öffnet die **Kundenkarte**.

|**Alt + S**
|Öffnet den **Webshop**.

|**Alt + E**
|Öffnet den Webshop mit aktivierter Inline-Editing-Funktion.

|**Alt + P**
|Nur im plentymarkets Client verfügbar. Öffnet das Menü **Prozesse**.

2+|Auftrag bearbeiten

|**Shift + Alt + N**
|Öffnet im Auftrag die Kundennotizen; in allen Tabs des Auftrags möglich.

|**Shift + Alt + A**
|Öffnet im Auftrag die Auftragsnotizen; in allen Tabs des Auftrags möglich.
|====

__Tab. 2: **Shortcuts**__

[NOTE]
.Einstellungen können geändert werden
====
Die Standard-Shortcuts für die Optionen können geändert werden. Kombinieren Sie dazu die Tastenkombination neu und klicken Sie auf **Speichern**.

Änderungen werden über **Shortcuts zurücksetzen** wieder auf die Standardeinstellungen zurückgesetzt.
====

[#60]
=== Favoriten anzeigen

In diesem Tab werden die Menüpfade angezeigt, die Sie als Favoriten angelegt haben. Die Favoriten können hier auch gelöscht sowie mit den **Aufwärts**- und **Abwärts**-Pfeilen sortiert werden. Das Tab ist nur beim eigenen Benutzer sichtbar. Weitere Information zum Hinzufügen und Entfernen von Favoriten finden Sie auf der Handbuchseite **<<arbeiten-mit-plentymarkets/allgemeine-funktionen#80., Allgemeine Funktionen einrichten >>**.

