= Grundeinstellungen
:lang: de
include::{includedir}/_header.adoc[]
:position: 10

Im Menü **plentymarkets » Einstellungen » Grundeinstellungen** nehmen Sie verschiedene Grundeinstellungen zur Arbeit mit plentymarkets vor. Sie hinterlegen die **<<arbeiten-mit-plentymarkets/grundeinstellungen/stammdaten#, Stamm-  >>** und <<payment/bankdaten-verwalten#, **Bankdaten**  >> Ihres Unternehmens. Außerdem können Sie <<arbeiten-mit-plentymarkets/benutzer-verwalten#, **Benutzer**  >> anlegen und verwalten. Sie haben außerdem die Möglichkeit, **<<arbeiten-mit-plentymarkets/grundeinstellungen/tags#, Tags  >>** zu hinterlegen. Wenn Sie den **<<tools/plentymarkets-client#, plentymarkets Client  >>** nutzen, konfigurieren Sie hier außerdem Ihren **<<arbeiten-mit-plentymarkets/grundeinstellungen/drucker#, Drucker  >>**.

== Verbindungen zu anderen Menüs

Sowohl Stamm- als auch Bankdaten werden über Syntaxvariablen z.B. in **<<crm/e-mails-versenden#1200., E-Mail-Vorlagen >>** ausgegeben.

Tags sind Schlagworte, mit denen Texte und Seiten markiert werden können. In plentymarkets werden Tags zentral in einem Menü angelegt und verwaltet. Sie stehen dann in verschiedenen Bereichen, z.B. **<<artikel/kategorien#, Kategorien  >>**, und im **<<crm/ticketsystem-nutzen#, Ticketsystem  >>** zur Verfügung.

== Videotutorials

Eine Einführung zum Menü **Benutzer** erhalten Sie im folgenden Videotutorial:

[.linkBox]
link:https://www.plentymarkets.eu/a-2719/[Benutzerverwaltung, window="_blank"]

== Wichtige Seiten zum Thema direkt aufrufen

* <<arbeiten-mit-plentymarkets/benutzer-verwalten#, **Benutzerkonten verwalten**  >>
* **<<arbeiten-mit-plentymarkets/grundeinstellungen/stammdaten#, Stammdaten  >>**
* **<<payment/bankdaten-verwalten#, Bank  >>**
* **<<arbeiten-mit-plentymarkets/grundeinstellungen/api-daten#, API-Daten  >>**
* **<<arbeiten-mit-plentymarkets/grundeinstellungen/tags#, Tags  >>**

