= Managing payments
:lang: en
include::{includedir}/_header.adoc[]
:description: Payments in plentymarkets: Get to know everything about working with and editing payments.
:position: 25
:url: payment/beta-managing-payments
:id: VBZTVJ8
:keywords: payments, incoming payments, assigning payments, automatic assignment, auto-assign, split payment, splitting payments, partial payments, mapping payments
:author: team-order-payment

This page of the manual describes and explains how to manage payments. You receive payments in your system from different sources. Independent of the payment source, you can manage all incoming payments in the *Orders » Payments* menu.

[#basic-settings]
== Carrying out basic settings for incoming payments

First, carry out basic settings for automatically assigning payments to orders and for giving goodwill on payments. Default settings are already saved in the system. These default values are generally recommended. To change these settings, proceed as follows.

[.instruction]
Changing the basic settings:

. Go to *Setup » Orders » Payment » Incoming*.
. Carry out the settings as described in <<table-settings-incoming-payments>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-settings-incoming-payments]]
.Basic settings for incoming payments
[cols="1,3"]
|====
|Setting |Explanation

| *Match for automatic assignment*
|Choose between *0.7* (no exact match required for assignment) and *1.0* (exact match required). If you enter a relatively high value, then it may not be possible to assign some payments. Therefore, the value *0.75* is set by *default*.

| *Goodwill on payment*
|You can ensure that, e.g. internal decimal amounts (starting with the third decimal place) do not lead to incorrect bookings by entering a *minimum amount* of *0.01* (default setting). If you set *0.05*, then amounts that are incorrect by 5 cents or less will still be treated as correct bookings.

| [#intable-import-customer-bank-data]*Import customer bank data*
|Select whether or not the customer's *bank data* should be *imported* and saved in the *customer data* when incoming payments are received. +
*_Important:_* The customer has to agree to having their bank data imported and saved. Therefore, this function is set to *No* by default. Before activating the function, contact a legal adviser to discuss the legality of doing so. You may need to consider the laws that relate to several different countries of delivery.

| *Only assign incoming PayPal payment to corresponding eBay listing if attached to the payment*
|*_Note:_* This functionality only applies to the old PayPal interface for Callisto online shops in plentymarkets, *not* for the PayPal plugin! +
If you use eBay listings in combination with the payment method PayPal, we recommend to set this option to *Yes*. This way, it is made sure that incoming payments effected via PayPal are correctly assigned to the corresponding eBay order. If an eBay listing ID is attached to a PayPal payment and the option is activated, the payment is only assigned to the order with a corresponding eBay listing ID.

| *Ignore WooCommerce PayPal transactions*
|*_Note:_* This functionality only applies to the old PayPal interface for Callisto online shops in plentymarkets, *not* for the PayPal plugin! +
Select the option *Yes* to deactivate the automatic import of payments belonging to orders imported from WooCommerce with the payment method PayPal.

|*Exclude orders with the following payment methods from automatic assignment*
|Select those payment methods for which no payments are incoming. They are then ignored for payment assignment. +
Use the keyboard to select multiple payment methods.

|*Exclude orders with the following referrers from automatic assignment*
|Select those referrers for which no payments are incoming. They are then ignored for payment assignment. +
Use the keyboard to select multiple referrers.

|====

[#10]
== New payments in the system

Payments can either come into your system automatically or they can be booked manually. After payments are booked in plentymarkets, they are automatically assigned to orders with a fuzzy search. If the payment cannot be assigned to the order automatically, then you can still manually assign the payment to an order. Edit and manage payments in the *Orders » Payments* menu. Unassigned payments are marked with a *green arrow* (icon:payment_assign[set=plenty,role="green"]). +
In this overview, payments are displayed in your <<payment/currencies#30, system currency>>. If the payment is in a different currency, this amount is displayed in brackets next to the system currency.

[TIP]
.Setting up event procedures for incoming payments
====
Payment receipt is an important event when it comes to processing orders because items are not typically shipped until the payment was received. In most cases, the order status in plentymarkets changes from *status [3] - waiting for payment* to *status [5] - cleared for shipping* as soon as the payment was received. Create <<automation/event-procedures#, event procedures>> to automatically process orders and ship the items once payment is received.
====

[#15]
=== Manually booking payments

In order to manually book a payment or partial payment in the order, e.g. because the customer picked up the item and paid the item in cash or because a payment cannot be found in the overview, proceed as follows.

[.instruction]
Booking a payment:

. Go to *Orders » Edit orders*.
. Open the order for which you want to book a payment. +
→ The *Overview* tab opens.
. Open the *Payment* tab.
. Click on *Book payment*. +
→ The *Book payment* window opens.
. Carry out the settings according to the information given in <<table-manually-booking-payments>>.
. Click on *Book payment*. +
→ The payment is booked and displayed in the payment overview.

[[table-manually-booking-payments]]
.Manually booking payments
[cols="1,3"]
|====
|Setting |Explanation

| *Amount*
|Enter the full or partial amount that you want to book.

| *Credit/Debit*
|Select *Credit* or *Debit*. The selection depends on the pending amount. *Credit* is selected by default. *Debit* is selected for negative pending amounts, e.g. overpaid payments. This selection can be changed if needed.

| *Currency*
|Select the currency in which the payment should be made.

| *Exchange rate*
|If needed, enter a different exchange rate than what is currently configured in the system. +
*_Important_*: In some cases, you may want to book a payment in a different currency than is currently selected for the payment (default currency), e.g. in US dollars. In this case, select the option *USD* under *Currency* and enter the amount received under *Amount*. +
If you calculated the <<payment/currencies#20, exchange rate>> in the *Setup » Orders » Payment » Currencies* menu and you want to use this exchange rate, then you do not have to enter anything under *Exchange rate*, because the exchange rate is automatically used. You will need to make an entry under *Exchange rate* if you want to use a different exchange rate for this payment, e.g. the exchange rate at the exact moment when the payment is received. In this case, enter the exchange rate that is applicable at this moment.

| *Designated use*
|The order ID is entered by default. The entry can be changed.

| *Incoming payment*
|Select a date for the incoming payment. The current date is selected by default.
|====

You can recognise manually booked payments by the *Manual booking* icon.

[bank-postings-import]
=== Importing bank postings

The payment method cash in advance and other transfers take the form of bank postings. With these payment methods, the payments that were booked into your bank account have to be reported to the system and then they need to be assigned to the orders. Use the import type <<data/importing-data/sync-types/elasticSync-bank-postings, Bank postings>> to import your bank postings into your plentymarkets system. After the import, the bank postings are treated as other payments and are automatically assigned to orders. Accordingly, editing and managing of these payments is also done in the *Orders » Payments* menu.

[#20]
== Searching for payments

You can search for payments in the *Orders » Payments* menu. This table is customisable. This means that you can decide which information is displayed in the table columns. To do so, proceed as follows:

[.instruction]
Customise table:

. Click on *Configure columns* (icon:cog[]). +
→ The window *Configure columns* opens.
. Select which columns are to be displayed.
. Move (icon:drag_sort_handle[set=plenty]) the columns so that they are displayed in the order you need them.
. Click on *Confirm* to save your settings.

You can select and combine different filters for the search (icon:filter[]), for example to search for unassigned payments of the last week.

There are several ways of using the search. You can enter a value in the search field and then select the required filter. For example, if you enter a number, available filters for this like IDs or variation numbers are suggested. Enter the value in full and then select the required filter from the suggestions. Repeat this to combine filters. Click on icon:search[set=material] to carry out the search. +
If you first want to select a filter from the available ones, click on the filter list and enter a value in the required filter. Click on *Search* once you have set all needed filters. +
Remove the chip if you want to delete a set filter. Available filters are explained in <<table-searching-payments>>.

Additionally, you can save selected filters in the UI by using the *Saved filters* (icon:bookmarks[set=material]) component. The saved filters can then be selected from this component every time you open or work with this menu, similar to bookmarks. Every user can save own filter sets.

[.instruction]
Saving filters:

. Set the filters with the required values.
. Carry out the search.
. Click on *Saved filters* (icon:bookmarks[set=material]).
. Click on *Save current filter*. +
→ The window *Save filter* opens.
. Enter a *Filter name*.
. Decide if this filter set should be available to all users.
. *Save* the settings.

[[table-searching-payments]]
.Searching for payments
[cols="1,3"]
|====
| Setting | Explanation

|*Order ID*
|Search for orders to which a payment has been assigned by entering the order IDs. You can enter several IDs by separating them with a comma.

|*Transaction ID*
|The transaction ID is assigned by the payment provider so that the payment can be correctly allocated to this provider. Enter a transaction ID to search for a payment with this specific transaction ID. You can enter several IDs by separating them with a comma.

|*Transaction code*
|The transaction code describes the transaction itself. Enter a transaction code to search for a payment with this specific code.

|*Reference ID*
|A reference ID links payments, e.g. a payment and a refund. Enter a reference ID to search for payments with this specific transaction ID.

|*Payment ID*
|Enter the payment ID to search for the exact payment with this ID.

|*Payment method*
|Enter a specific payment method to search for payments done with this payment method.

|*Reason for payment*
|Enter the reason for payment, either entirely or partly, to search for payments with this designated use.

|*Sender of payment*
|Enter the name of the person who sent the money to search for all payments of this person.

|*Cr/Dr*
|Choose between *Cr* (Credit) and *Dr* (Debit). +
*Credit* = All incoming payments with a positive value are displayed. +
*Debit* = All incoming payments with a negative value are displayed.

|*Value*
|Choose an operator and enter an amount. +
*_Example_*: Select *Greater than or equal to* and enter 300 as the *Amount* in order to have all payments with an amount of 300 and more displayed.

|*Assignment*
|You can choose between *Assigned* and *Unassigned*. +
*Assigned* = Shows you only payments which were already assigned to an order. +
*Unassigned* = Shows you only payments which were not assigned to an order yet.

|*Status*
|Select a status to search for payments with this specific status.

|*Transaction type*
|Select a transaction type to search for payments that have this transaction type.

|*Currency*
|Select a currency to search for payments carried out in this currency.

|*Date type*
|Select a date type and combine it with a date range. You can choose between *Imported*, *Received* and *Assigned*. Displayed are all payments which were either imported, received or assigned in the chosen date range.

|*Date from and Date to*
|In connection with *Date type*, choose a date range to search for payments which were either imported, received or assigned, depending on what you selected.

|*Reset*
|Click on *Reset* to reset all selected filters. Then, click on *Search* again, to have all incoming payments displayed.

|*Search*
|Executes the search.

|====

[#30]
== Assigning payments

There are two ways to assign unassigned payments to an order. In the *Orders » Payments* menu you can either assign payments directly in the overview or you open the detail view of a payment and assign it from there.
Assigning in the overview is done by entering the corresponding order ID. This is an easy and fast way to assign when you already know which order a payment is to be assigned to, do not need any further information about the payment and have the order ID ready.
Proceed as follows to assign a payment in the overview.

[.instruction]
Assigning a payment in the overview with the order ID:

. Go to *Orders » Payments*.
. Search (icon:filter[]) for the payment with the <<payment/beta-managing-payments#20, search filters>>.
. Enter the order ID of the order to which the payment is to be assigned in the *Order ID* field in the row of the unassigned payment. +
. Press *Enter* to save it. +
→ The payment is assigned and the overview is updated.

If a fast assignment in the overview is not possible and you need more information about a payment, open the detail view of a payment. To do so, click into the row of the payment in the overview table or directly click on the payment ID. You can also click on the action *Assign* (icon:payment_assign[set=plenty,role="green"]) in the overview table to open the detail view of a payment.
To assign a payment in the detail view, proceed as follows.

[.instruction]
Assigning a payment in the detail view:

. Go to *Orders » Payments*.
. Search (icon:filter[]) for the payment with the <<payment/beta-managing-payments#20, search filters>>.
. Open the payment by clicking either into the row of the unassigned payment you want to assign, on the payment ID or on *Assign* (icon:payment_assign[set=plenty,role="green"]). +
→ You are redirected to the *Assignment* area of the payment. +
→ The orders with the highest matching rates are displayed there.
. Select the correct order and click on *Assign payment* (icon:payment_assign[set=plenty,role="green"]). +
→ The payment is assigned to the selected order. Only the selected assignment is shown.

The matching between payments and orders are checked on the basis of a background matrix. This check is initiated as soon as you open the *Assignment* table in the detail view of a payment. A maximum of 10 orders with the highest matching rates are displayed in descending order.
As soon as you assigned the payment only the selected match will be displayed in this table. Only when the payment is detached from the order, will the matchings with the highest rates be displayed again.

Several payments can be assigned to the same order. This can happen, for instance, if the first payment did not cover the whole order amount. If one or several payments are already assigned to an order and you want to assign another one, you have to confirm this assignment.

This table is customisable. This means that you can decide which information is displayed in the table columns. To do so, proceed as follows:

[.instruction]
Customise table:

. Click on *Configure columns* (icon:cog[]). +
→ The window *Configure columns* opens.
. Select which columns are to be displayed.
. Move (icon:drag_sort_handle[set=plenty]) the columns so that they are displayed in the order you need them.
. Click on *Confirm* to save your settings.

[#40]
== Detaching payments

There are two ways to detach a payment from an order. In the *Orders » Payments* menu you can either detach payments directly in the overview or you open the detail view of a payment and detach it from there.
Proceed as follows to detach a payment in the overview.

[.instruction]
Detaching a payment in the overview:

. Go to *Orders » Payments*.
. Search (icon:filter[]) for the payment with the <<payment/beta-managing-payments#20, search filters>>.
. Click on *Detach payment* (icon:undo[role="orange"]) in the row of the payment you want to detach from an order. +
→ The payment is detached from the order and is displayed again as an unassigned payment.

A payment can also be detached from the detail view. To do so, proceed as follows:

[.instruction]
Detaching a payment in the detail view:

. Go to *Orders » Payments*.
. Search (icon:filter[]) for the payment with the <<payment/beta-managing-payments#20, search filters>>.
. Click in the row of the payment you want to detach and open it. +
→ The detail view of the payment opens.
. Open the *Assignment* table. +
→ When the table opens, the existing order assignment is shown.
. Click on *Detach payment* (icon:undo[role="orange"]). +
→ The payment is detached from the order. The highest matching rates for this payment are once again shown.

[IMPORTANT]
.Detaching payments
====
Detaching a payment from an order is technically possible at all times, even when order processing has advanced or is completed. But detaching a payment should only be done cautiously and with good reason since errors, for example that a payment no longer covers an open order amount, are likely to occur when a payment is detached and assigned repeatedly. Further note that detaching a payment also causes changes to the order it was detached from, for example a recalculation of the payment of an order or a status change.
====

[#50]
== Splitting payments

Manually booked incoming payments, imported bank postings as well as EBICS payments can be split. This means that the amount of a payment can be split and assigned to several orders. This is done in the *Orders » Payments* menu. Note that Provisional postings cannot be split. To split payments, proceed as follows.

[.instruction]
Splitting a payment:

. Go to *Orders » Payments*.
. Search (icon:filter[]) for the payment with the <<payment/beta-managing-payments#20, search filters>>.
. Click on *Split payment* (icon:item_variation_distribute_quantity[set=plenty]) in the row of the payment you want to split. +
→ You are redirected to another view to proceed with splitting the payment.
. Search (icon:filter[]) for the required orders with the search filters *Order ID*, *External order ID*, *Invoice number*, *Contact ID* and *Name*. You can enter several IDs/numbers by separating them with a comma.
. Select the orders between which you want to split the payment from the search results.
. Click on *Save* (icon:save[role="green"]). +
→ The payment is split and assigned to the selected orders in the order in which they are shown in the table, from the top down and you are redirected to the payments overview. Here, the created partial payments can be edited in the same way as the other payments.

When splitting a payment, the amount of the payment is reduced by the corresponding amounts of the orders that were selected during the division of the payment. Both, the original total amount of the payment as well as the leftover open amount are displayed in this view. When a leftover open amount is created by splitting a payment, this amount could be split again.

_An example_: Imagine you want to split a payment with the amount of 120 Euros into order A, which has an open amount of 80 Euros, and into order B, which has an open amount of 20 Euros. By splitting the payment and selecting these two orders, order A is assigned 80 Euros and order B 20 Euros. The payments created by splitting the original payment are automatically assigned to the selected orders. An amount of 20 Euros is left from the original payment. You can now assign this leftover amount to another order or, if required, can split it again.

[IMPORTANT]
.Splitting a payment cannot be reversed
====
Once you split a payment, this cannot be reversed. In order to restore the original payment, delete all partial payments. When a partial payment is deleted, the amount is added again to the original payment. Before deleting a partial payment, it has to be detached from the order because only unassigned payments can be deleted.
====

In the split view of a payment, info boxes provide you with a quick overview of the most important information: amount, the date the payment was received and the reason for payment. The amount info box is displayed in green when the amount is above zero, otherwise the box is grey.

[.collapseBox]
.*Customising the table*
--

The table in the splitting payments area is customisable. This means that you can decide which table columns are displayed in which order. The following table columns are selected by default when you go to the payments menu:

* Order ID
* External order ID
* Invoice number
* Contact ID
* Name

Adapt the table according to your requirements and your workflow. When you have adapted the table, these settings are saved. The table remains editable, you can change it any time.

[.instruction]
Customise table:

. Click on *Configure columns* (icon:cog[]). +
→ The window *Configure columns* opens.
. Select which columns are to be displayed.
. Move (icon:drag_sort_handle[set=plenty]) the columns, so that they are displayed in the order you need them.
. Click on *Confirm* to save your settings.

--

[#60]
== Deleting payments

You can only delete payments when they are not assigned to an order. Deleting a payment can be carried out either directly in the overview table or in the detail view of an opened payment. Proceed as follows to delete a payment in the overview.

[.instruction]
Deleting a payment in the overview:

. Go to *Orders » Payments*.
. Click on *Delete payment* (icon:minus-circle[role="red"]) in the row of the payment you want to delete. +
→ The confirmation *Confirm deletion of payment* opens.
. Click on *Delete payment*. +
→ The payment is deleted and the overview updated.

Moreover, the function *Delete* (icon:minus-circle[role="red"]) is also available to you in the detail view of a payment. To do so, proceed as follows.

[.instruction]
Deleting a payment in the detail view:

. Go to *Orders » Payments*.
. Click into the row of the payment you want to delete to open it. +
→ The detail view of the payment opens.
. Click on *Delete payment* (icon:minus-circle[role=red]), above the details of the payment.
. Click on *Yes* in the enquiry which opens. +
→ The payment is deleted and you are redirected to the updated overview.

[#70]
== Carrying out the group function

You can edit several payments at the same time by using the group function. In order to use the group function, at least one payment has to be selected. Use the search to filter for the required payments. After selecting the payments you can either auto-assign them all at the same time or delete them all at the same time. Remember that only unassigned payments can be deleted.

Proceed as follows to either assign or delete payments by using the group function.

[.instruction]
Editing payments by using the group function:

. Go to *Orders » Payments*.
. Select the payments you want to auto-assign or delete by placing a check mark next to them.
. Click either on *Delete payments* (icon:trash[set=plenty]) or on *Auto-assign payments* (icon:payment_assign[set=plenty,role="green"]) above the payments overview table. +
→ You have to confirm or deny the deletion or the assignment of the payments.
. After executing the group function, messages display how many of the selected payments could be auto-assigned or deleted.

After executing the group functions, massages display how many of the selected payments could be auto-assigned or deleted. Sometimes, not the whole selection can be edited. For example, if one or several of the selected payments are assigned to an order, they cannot be deleted. If you need further information why a payment could not be auto-assigned or deleted, you can refer to the log. For this, fo to the *Data » Log* menu.

Note that the auto-assignment depends on the setting *Match for automatic assignment (0.7 - 1.0)* in the *Setup » Orders » Payment » Incoming* menu. The value 0.7 stands for a 70% match and the value 1.0 stands for a 100% match. If two orders are found with the same matching rate while auto-assigning payments, the payment cannot be assigned. This also means that a payment can only be auto-assigned when just one order with the corresponding matching rate was found.

[#80]
== Further information in the detail view

Besides the functions <<payment/beta-managing-payments#30, assigning payments>>, <<payment/beta-managing-payments#40, detaching payments>> and <<payment/beta-managing-payments#69, deleting payments>>, the detail view offers you an overview of all information connected to a payment. Info boxes provide a quick overview of the most important information. The *Amount* info box is displayed in green when the amount is above zero, otherwise it is grey. The status is also expressed by the infobox colour:

* Green = The payment was processed, it either means approved, captured or refunded.
* Orange = The payment is being processed, it either means waiting for approval, partially captured or awaiting renewal.
* Red = The payment was not processed, it either means refused, cancelled or expired.

The *Assignment* area offers you a list of the orders with the highest matching rate for an unassigned payment. If a payment is already assigned, only the order which it is assigned to is displayed here.

The *History* offers you an overview over all actions executed for this payment. It is also shown who initiated an action at what time so that transparency is ensured.

The *Properties* in the lower area show all information regarding the payment. These information usually exceed the information given in the details. Which information are shown in the Properties depends on the payment itself, for example which payment method was used or which information a payment provider transfers.

[#100]
== Displaying incoming payments on the dashboard

You can add the element *Payments* to the <<welcome/customise-system#110, dashboard>> of your plentymarkets back end. This element displays information about unassigned payments as well as about all incoming payments from yesterday and today. If you don't want to use this element on your dashboard, you can get the same results by going to *Orders » payments* and using the search filters.

It is recommended that you take a look at the unassigned payments before editing orders. You should see whether incoming *cash in advance* payments are among them, which can usually be assigned to an order without a doubt thanks to the amount and the booking text. This saves your customers long waiting times and it saves you unpleasant complaints.

At least once a week, you should edit and sort out the unassigned payments so that you don't lose track of them in your day-to-day business. For further information about assigning unassigned payments and bookings to orders, refer to <<payment/beta-managing-payments#30, Assigning payments>>.

[TIP]
.Tip
====
Sofortbanking payments will be confirmed via an interface immediately after the payment process. They will then appear again in the system as bank postings. You can delete these bank postings from the list of unassigned payments without concern because the orders in question have already been assigned to the payment.
====
