= Managing currencies
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Currency, Standard currency, Live conversion
:description: Payment in plentymarkets: Organize and manage currencies in your plentymarkets system and change the display options of currencies in the online store.
:position: 40

If you want to offer your items for sale in different countries, working with various currencies is essential. This page describes the necessary settings you have to carry out in your plentymarkets system for this purpose.
plentymarkets allows you to work with a variety of currencies. This is especially useful if you sell your items in several different countries. This page describes the currency settings that affect all clients (stores) in your plentymarkets system. In addition, this page enumerates further currency settings that are needed if only one online store is used.

[#10]
== Supported currencies

Your plentymarkets system currently supports the currencies listed in <<table-supported-currencies>>.

[[table-supported-currencies]]
.Currencies in plentymarkets
[cols="1,3"]
|====
|ISO |Currency

|*AED*
|United Arab Emirates dirham

|*ARS*
|Argentine peso

|*AUD*
|Australia, Australian dollar

|*BGN*
|Bulgaria, Bulgarian lev

|*BHD*
|Bahraini dinar

|*BRL*
|Brazil, Brazilian real, plural: Reais

|*CAD*
|Canada, Canadian dollar

|*CHF*
|Switzerland, Swiss franc

|*CNY*
|People's Republic of China, Renminbi

|*CZK*
|Czech Republic, Czech koruna

|*DKK*
|Denmark, Danish krone

|*EUR*
|Euro

|*GBP*
|Great Britain, Pound Sterling

|*HKD*
|Hong Kong dollar

|*HRK*
|Croatian kuna

|*HUF*
|Hungary, forint

|*IDR*
|Indonesian rupiah

|*INR*
|India, Indian rupee

|*JPY*
|Japan, Japanese yen

|*MXN*
|Mexico, Mexican peso

|*MYR*
|Malaysian ringgit

|*NOK*
|Norway, Norwegian krone

|*NZD*
|New Zealand dollar

|*PHP*
|Philippine peso

|*PLN*
|Poland, zloty

|*QAR*
|Qatari riyal

|*RON*
|Romania, Romanian leu

|*RUB*
|Russian Federation, ruble

|*SEK*
|Sweden, Swedish krona

|*SGD*
|Singapore dollar

|*THB*
|Thai baht

|*TRY*
|Turkey, Turkish lira

|*TWD*
|New Taiwan dollar

|*UAH*
|Ukrainian hryvnia

|*USD*
|USA, US dollar

|*VND*
|Vietnamese dong

|*XCD*
|Eastern Caribbean dollar

|*ZAR*
|South African rand
|====

[#20]
== Converting currencies

Go to <<item/managing-items#870, *System » System settings » Item » Sales prices*>> and activate the option *Currency: Live conversion* to determine if the currency conversion in the online store is carried out automatically. +
In addition, carry out general currency settings for all incoming orders in the menu *System » System settings » Orders » Payment » Currencies*. To do so, proceed as described below.

[.instruction]
Converting currencies:

. Go to *System » System settings » Orders » Payment » Currencies*.
. Carry out the settings according to <<table-settings-currencies>>.
. *Save* the settings.

[[table-settings-currencies]]
.Currency settings
[cols="1,3"]
|====
|Setting |Explanation

|*Standard currency*
|Select the <<payment/currencies#30, System currency>> from the drop-down list.

|*Automatically update conversion factors daily*
|This option specifies whether or not the conversion factors are automatically updated on a daily basis. +
*Yes* = The conversion factors will be updated automatically over night. The option *Last automatic update* appears below the option for automatic updates of conversion factors. +
*No* = a *reload icon* is displayed for each currency. Use this icon to manually update the current conversion rates any time.

|*Last automatic update*
|Displays the time of the last automatic update of the conversion factors. This field is only visible if the option *Automatically update conversion factors daily* is set to *Yes*.

|*Conversion factor for standard currency into AED, ARS, AUD, ...*
|The exchange rates are already displayed when opening the menu *System » System settings » Orders » Payment » Currencies*, but might need to be updated. Click on *Reload* next to the respective currency to manually update the exchange rates. Alternatively, set the option *Automatically update conversion factors daily* to *Yes*.
|====

[#30]
== Defining the system currency

If you are working with several currencies, you have to select one of those currencies as the standard currency of your plentymarkets system. The standard currency is automatically selected as the default currency whenever no other currency is selected. By default, the standard currency in your system is *EUR* (Euro). +
In plentymarkets, orders are always created in the standard currency. In addition, the currency selected by your customers during the order process is always with every single incoming order. If an order was placed in a currency different from the standard currency, the current exchange rate is also saved with the order. Thus, these values are permanently available and can be used to analyse order data or to e.g. send automatic notifications.

[.instruction]
Defining the system currency:

. Go to *System » System settings » Orders » Payment » Currencies*.
. Select a currency for the option *Standard currency*.
. *Save* the settings.

[IMPORTANT]
.System currency vs. Online store currency
====
This setting is not necessarily identical to the currency <<payment/currencies#60, displayed in your online store>>. You can define a different standard currency for each online store and each language. Further information on these settings are provided below on this manual page.
====

[#40]
== Carrying out settings for the online store

After having carried out the necessary settings regarding <<payment/currencies#20, currency conversion>> and <<payment/currencies#30, system currency>>, you can determine a standard currency for your online store. In addition, you can decide whether customers are allowed to change the currency during the order process in the online store. +
The settings differ depending on whether you run a <<payment/currencies#50, Ceres>> or <<payment/currencies#60, Callisto>> online store.

[#50]
=== Ceres online stores

If you run your online store using the link:https://marketplace.plentymarkets.com/en/plugins/templates/Ceres_4697[Ceres plugin] in plentymarkets 7, the <<omni-channel/online-store/setting-up-ceres#201, Ceres online store>> page of the manual provides information on all necessary currency settings.

[#60]
=== Callisto online stores

The following chapters explain the necessary currency settings for Callisto online stores.

[#70]
==== Callisto: Displaying the currency symbol in the order process

Select whether currencies are displayed as ISO codes or as symbols in the online store. For example, Euro would be displayed as the ISO code *EUR* or as the *€* symbol. This setting determines how the currency is displayed during the *order process* and in the *My account* area in the online store. <<payment/currencies#70, Template variables and functions>> are used to display the currency in other areas of the online store.

[.instruction]
Displaying the currency symbol in the order process:

. Go to *System » System settings » Client » Select client » Online store » Currency*.
. Select the option *Symbol* from the *Symbol* drop-down list.
. *Save* the settings.

[#80]
==== Callisto: Defining a standard currency for the online store

If you offer different languages for your online store, you can define a standard currency for every language. If you work with several clients (stores), you can carry out the settings for each store individually. If you want to carry out these settings for a different store, then replace the menu point *Standard* with the name of the store.

[.instruction]
Defining a standard currency for the online store:

. Go to *System » System settings » Client » Select client » Online store » Currency*.
. Select a *Standard currency* for each language offered in the online store.
. *Save* the settings.

[#90]
==== Callisto: Customising the currency displayed in the online store

You can allow your customers to switch from one currency to another. If, for example, you run a German store in which your items are sold in EUR and a Swiss store in which items are sold in CHF, this setting is useful. The following template functions allow customers to switch from one currency to another in the online store:

*$Link_Currency(EUR)* +
*$Link_Currency(CHF)* +
*$Link_Currency (USD)*

These template functions are inserted with the following codes:

*&lt;a href="$Link_Currency(EUR)"&gt;EUR&lt;/a&gt;* +
*&lt;a href="$Link_Currency(CHF)"&gt;CHF&lt;/a&gt;* +
*&lt;a href="$Link_Currency(USD)"&gt;USD&lt;/a&gt;*

[.instruction]
Inserting template functions:

. Go to *CMS » Web design*.
. Open the folder *Layout » PageDesign*.
. Open a template, e.g. *PageDesignContent*.
. Copy the desired code as provided above and insert it into the desired location within the template.
. *Save* the settings.

[TIP]
.Replacing currency symbols
====
If you previously worked with currency symbols, replace them with the template variable *$Currency*. The template variable *$Currency* always contains the currency that is currently selected in the online store.
====
