= Managing payment methods
:lang: en
include::{includedir}/_header.adoc[]
:description: Payment in plentymarkets: Set up and activate payment methods in your plentymarkets system.
:position: 10
:url: payment/managing-payment-methods
:id: MVDQHNC
:keywords: payment, payment method, ceres, plugins, plentymarketplace, marketplace, plenty-marketplace, customer classes, SSL, SSL-certificate, encryption, default payment method, discount, payment methods for markets
:author: team-order-payment

For Ceres stores, payment methods are integrated via plugins. To access the available payment plugins as well as instructions on how to install them, visit the payment section in the link:https://marketplace.plentymarkets.com/en/plugins/payment[plentyMarketplace^]{nbsp}icon:external-link[].
On this page, you will find information on how to manage payment methods and which settings to select. Moreover, you will find an overview of market payment methods. For a detailed description on how to activate market payment methods, refer to the pages of the corresponding <<markets#, markets>>.

[#25]
== Specifying the default payment method

Proceed as follows to specify the payment method to be set by default in the order process in your online store.

[.instruction]
Specifying the default payment method:

. Go to *Setup » Client » [Select client] » Orders*.
. Select a payment method from the *Default payment method* drop-down list.
. *Save* (icon:save[role="green"]) the settings.

[#30]
== Permitting the payment method in a customer class

You need to permit payment methods in the basic settings of your customer classes. These settings also relate to the *standard end customers*. New payment methods need to be added to the list of permitted payment methods. Vice versa, you can exclude payment methods from this list to prevent the payment methods from being used by a particular customer class. After having set up a new payment method in your system, check the settings under *Permitted payment methods* for each of your customer classes. For further information, refer to the <<crm/managing-contacts#15, Creating a customer class>> page.

[TIP]
.SSL certificate and encryption
====
We generally recommend that you use <<business-decisions/system-administration/domains#, SSL encryption>> for your online store if you work with payment data and customer data. This is required for payment methods that work with an iframe.
====

[#50]
== Offering a discount based on a payment method

You can offer your customers a discount when they use a specific payment method. This is a customer class setting which enables you to offer a discount on payment methods in the webshop. For information on how to set this up, refer to the chapter <<crm/managing-contacts#28, Setting up a discount based on the method of payment>> of the manual.

[#60]
==  Shipping without payment

Some payment methods require items to be shipped before the payment was received, e.g. with payment on invoice. If the <<stock-management/managing-stocks#, stock>> is limited to net stock, then the system will check whether stock is available and will set the corresponding order in status 4 or 5. To solve this, go to <<orders/basic-settings#, Setup » Orders » Settings>> and select *YES* for the option *Status changes to 4 instead of 5 if stock is missing*. If there is no limitation set up for the stock, then the order will be placed directly in status 5.

The following payment methods require shipping before payment:

*  Invoice
*  Debit
*  Cash on delivery
*  Amazon

For further information, refer to the <<stock-management/managing-stocks#, Stocks>> page of the manual.

[#70]
== Payment methods for markets

Payment methods for markets are payment methods which are necessary to flag incoming payments from integrated markets. In general, the market payment methods do not have to be completely set up. They only have to be activated. Not activating the payment method can cause problems during payment processing. Learn how to activate the payment methods for markets on the respective markets' pages. <<table-overview-payment-method-markets>> provides an overview.

[[table-overview-payment-method-markets]]
.Overview of payment methods for markets
[cols="1,3"]
|====
|Payment method |Explanation

| *Amazon*
|Payment method for orders that are imported into your plentymarkets system from Amazon. Activate the <<markets/amazon/amazon-setup#4500, Amazon>> payment method.

| *BOL.com*
|Payment method for orders that are imported into your plentymarkets system from bol.com. Activate the <<markets/bol-com#650, BOL.com>> payment method.

| *Cdiscount*
|Payment method for orders that are imported into your plentymarkets system from Cdiscount. Activate the <<markets/cdiscount#900, Cdiscount>> payment method.

| *Check24*
|Payment method for market Check24. Activate the <<markets/check24#700, Check24>> payment method.

| *eBay purchase on invoice*
|Payment method for purchase on invoice on eBay. Activate the <<markets/ebay/ebay-setup#2250, eBay purchase on invoice>> payment method.

| *Flubit*
|Payment method for orders that are imported into your plentymarkets system from Flubit. Activate the <<markets/flubit#370, Flubit>> payment method.

| *Fruugo*
|Payment method for orders that are imported into your plentymarkets system from Fruugo. Activate the <<markets/fruugo#600, Fruugo>> payment method.

| *idealo Checkout*
|Payment method for the market idealo Direktkauf. Activate the <<markets/idealo-checkout/idealo-setup#1100, idealo Checkout>> payment method.

| *Neckermann payment*
|Payment method for the Neckermann.at market. Activate the <<markets/neckermann/neckermann-at-setup#1600, Neckermann.at>> payment method.

| *Netto*
|Payment method for the market Netto. Activate the <<markets/plus-gartenxxl#400, Netto>> payment method.

| *OTTO Payment*
|Payment method for the OTTO interface. Activate the <<markets/otto/otto-market#425, OTTO Payment>> payment method.

| *PIXmania Payment*
|Payment method for the PIXmania market. Activate the <<markets/pixmania#800, PIXmania>> payment method.

| *real.de Payment*
|Payment method for the real.de market. Activate the <<markets/real-de/real-setup#800, real.de>> payment method.

| *Shopgate Payment*
|Payment method for the Shopgate market. Activate the <<markets/shopgate#600, Shopgate>> payment method.

| *Yatego invoice*
|Payment method for the Yatego market. Activate the <<markets/yatego#900, Yatego invoice>> payment method.

| *Zalando payment*
|Payment method for the Zalando market. Activate the <<markets/zalando#800, Zalando payment>> payment method.
|====
