// tag::zuordnung-stornierung[]
. Klicke auf *Neuen Eintrag hinzufügen*. +
→ Eine Zeile wird eingefügt.
. Wähle aus der Dropdown-Liste links den plentymarkets Status.
. Wähle aus der Dropdown-Liste rechts einen Grund für die Stornierung von {marketplace}. +
Die folgenden Gründe können an {marketplace} übertragen werden: +

* `34` = Stornierung: Fehlbestellung
* `35` = Stornierung: Unerwünschte Zahlungsbedingung
* `37` = Stornierung: Zu lange Lieferzeit
* `39` = Vereinbarung zwischen Käufer und Verkäufer getroffen
// end::zuordnung-stornierung[]

// tag::zuordnung-datenfelder[]
include::../instructions/katalog-mirakl-zuordnungen.adoc[]

In der ZIP-Datei link:{valid-values-zip}[{marketplace}: Gültige Werte^] findest du CSV-Dateien für jedes Marktplatzattribut. Innerhalb einer CSV-Datei sind die gültigen Werte für das Attribut abgebildet. Den zu übertragenden Wert findest du immer in der Spalte *Code*.
// end::zuordnung-datenfelder[]

// tag::automatisierung-zusammenfassung[]
* Auftragsbestätigung an {marketplace} melden
* Auftragsablehnung an {marketplace} melden
* Versandbestätigung an {marketplace} melden
* Auftragsstornierung an {marketplace} melden
* Rückerstattung an {marketplace} melden
// end::automatisierung-zusammenfassung[]

// tag::automatisierung-details[]
[#1000]
=== Auftragsbestätigung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-auftragsbestaetigung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-auftragsbestaetigung]
.Ereignisaktion, um Auftragsbestätigungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [3] *Warten auf Zahlung*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Auftrag annehmen*
|
|===

[#1005]
=== Auftragsablehnung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-auftragsablehnung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-auftragsablehnung]
.Ereignisaktion, um Auftragsablehnung an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[8] Storniert*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Auftrag ablehnen*
|
|===

[#1010]
=== Versandbestätigung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-versandbestaetigung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-versandbestaetigung]
.Ereignisaktion, um Versandbestätigungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [7] *Warenausgang gebucht*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion 1*
| *Plugins > {marketplace}: Aktualisieren der Carrier Tracking Informationen für eine bestimmte Bestellung*
|

| *Aktion 2*
| *Plugins > {marketplace}: Versand eines Auftrags validieren*
|
|===

[#1020]
=== Auftragsstornierung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-auftragsstornierung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-auftragsstornierung]
.Ereignisaktion, um Stornierungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[8] Storniert*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Stornieren Sie die Auftragsposition*
|
|===

[#1030]
=== Rückerstattung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-rueckerstattung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-rueckerstattung]
.Ereignisaktion, um Rückerstattungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[11] Gutschrift*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Rückerstattungs-Bestellzeilen*
|
|===

[#1100]
== Nicht bestätigte Aufträge archivieren

Wenn ein Auftrag abgelehnt oder storniert wurde, oder für einen Auftrag eine Gutschrift ausgeschrieben wurde, solltest du den Auftrag archivieren. Dies kannst du automatisch über den Aktionsmanager machen.

Du musst für jeden Status eine eigene Aktion einrichten.

[#1110]
=== Abgelehnte Aufträge archivieren

[.collapseBox]
.Aktion einrichten
--
[.instruction]
Aktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Öffne das Tab *Neue Aktion*.
 Nimm die gewünschten Einstellungen anhand der Informationen in <<#{marketplace}-aktionsmanager-abgelehnte-auftraege>> vor.
. Öffne das Tab *Filter*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{marketplace}-aktionsmanager-abgelehnte-auftraege>> vor.
. Öffne das Tab *Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{marketplace}-aktionsmanager-abgelehnte-auftraege>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Aktion wird erstellt.

--

[#{marketplace}-aktionsmanager-abgelehnte-auftraege]
.Einstellungen Aktionsmanager
[cols="1,3a"]
|===
|Tab |Einstellung

| *Status*
| Aktiviere die Option *Aktiv*. +
Stelle ein, wann die Aktion jeden Tag ausgeführt werden soll. +
Gib einen Namen ein.

| *Auftragstyp*
| Wähle aus der Dropdown-Liste *Status* die Option *[7] Warenausgang gebucht*. +
Wähle aus der Dropdown-Liste *Letzter Statuswechsel* die Option *Tage eingeben*. Gib den Wert `2` in das neue Textfeld ein. +
Wähle aus der Liste *Auftragsherkunft* die Option {marketplace}.

| *Aktion*
| Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* einen endgültigen Status, z.B. 7.99.

|===

[#1120]
=== Stornierte Aufträge archivieren

[.collapseBox]
.Aktion einrichten
--
[.instruction]
Aktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Öffne das Tab *Neue Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{marketplace}-aktionsmanager-stornierte-auftraege>> vor.
. Öffne das Tab *Filter*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{marketplace}-aktionsmanager-stornierte-auftraege>> vor.
. Öffne das Tab *Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{marketplace}-aktionsmanager-stornierte-auftraege>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Aktion wird erstellt.

--

[#{marketplace}-aktionsmanager-stornierte-auftraege]
.Einstellungen Aktionsmanager
[cols="1,3a"]
|===
|Tab |Einstellung

| *Status*
| Aktiviere die Option *Aktiv*. +
Stelle ein, wann die Aktion jeden Tag ausgeführt werden soll. +
Gib einen Namen ein.

| *Auftragstyp*
| Wähle aus der Dropdown-Liste *Status* die Option *[8] Storniert*. +
Wähle aus der Dropdown-Liste *Letzter Statuswechsel* die Option *Tage eingeben*. Gib den Wert `2` in das neue Textfeld ein. +
Wähle aus der Liste *Auftragsherkunft* die Option {marketplace}.

| *Aktion*
| Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* einen endgültigen Status, z.B. 8.99.

|===

[#1130]
=== Aufträge mit Gutschriften archivieren

[.collapseBox]
.Aktion einrichten
--
[.instruction]
Aktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Öffne das Tab *Neue Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{marketplace}-aktionsmanager-gutschriften>> vor.
. Öffne das Tab *Filter*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{marketplace}-aktionsmanager-gutschriften>> vor.
. Öffne das Tab *Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{marketplace}-aktionsmanager-gutschriften>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Aktion wird erstellt.

--

[#{marketplace}-aktionsmanager-gutschriften]
.Einstellungen Aktionsmanager
[cols="1,3a"]
|===
|Tab |Einstellung

| *Status*
| Aktiviere die Option *Aktiv*. +
Stelle ein, wann die Aktion jeden Tag ausgeführt werden soll. +
Gib einen Namen ein.

| *Auftragstyp*
| Wähle aus der Dropdown-Liste *Status* die Option *[11] Gutschrift*. +
Wähle aus der Dropdown-Liste *Letzter Statuswechsel* die Option *Tage eingeben*. Gib den Wert `2` in das neue Textfeld ein. +
Wähle aus der Liste *Auftragsherkunft* die Option {marketplace}.

| *Aktion*
| Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* einen endgültigen Status, z.B. 11.99.

|===
// end::automatisierung-details[]

// tag::voraussetzungen-produktdaten-uebertragen[]
=== Voraussetzungen

* Die Plugins {*name*} sowie *Mirakl Connector* wurden im Marktplatz gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
// Link zum Plugin einfügen
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {marketplace} und Mirakl aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {marketplace/extension}* wurde die Grundeinrichtung vorgenommen. Für die Produktübertragung muss die Option *Produkte exportieren* im Schritt Datenaustausch aktiv sein.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurden die Mirakl sowie {marketplace/extension} Auftragsherkünfte an einem bestehenden Preis aktiviert *oder* es wurde ein neuer Verkaufspreis erstellt, bei dem Mirakl und {marketplace/extension} Auftragsherkünfte aktiviert wurden.
* Du hast bereits einen Katalog für die Übertragung der Daten erstellt. - LINK zum Kapitel Kataloge
// end::voraussetzungen-produktdaten-uebertragen[]

// tag::voraussetzungen-angebotsdaten-uebertragen[]
=== Voraussetzungen

* Die Plugins {*marketplace*} sowie *Mirakl Connector* wurden im plentyMarketplace gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
// Link zum Marktplatz einfügen
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {*marketplace*} und *Mirakl* aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {marketplace}* wurde die Grundeinrichtung vorgenommen
** *Bestand synchronisieren* ist im Datenaustausch-Schritt aktiviert, damit die Angebot korrekt übertragen werden
* Im Menü *Einrichtung » Artikel » Verkaufspreise* sind an einem bestehenden Preis die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert *_oder_* ein neuer Verkaufspreis ist erstellt, in dem die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert wurden.

Die Angebotsübertragung findet alle 15 Minuten statt. Es werden nur Artikel übertragen, die die folgenden Voraussetzungen erfüllen:
* An der Variante sind die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert.
* An der Variante ist ein Preis aktiv, der für *{marketplace}*, *Mirakl* und *WEB-API* aktiviert wurde.
* An dem Artikel (bzw. an der Variante) ist ein Versandprofil aktiv, das für *{marketplace}*, *Mirakl* und *WEB-API* wurde.
* An der Variante ist ein Wert als Marktplatz-SKU für *{marketplace}* hinterlegt.
* An der Variante hat in den letzten 15 Minuten eine Änderung an dem Bestand oder Preis stattgefunden
** Das Setzen eines neuen Zeitstempels über die Gruppenfunktion oder Stapelverarbeitung, führt auch zu einer Übertragung der Variante und somit muss an der Variante die Warenbestandsbeschränkung „Auf Netto-WB“ oder" „Keine“ ausgewählt sein und die Variante muss positiven Bestand haben
// end::voraussetzungen-angebotsdaten-uebertragen[]

// tag::attributsuche-tool[]
==== Attributsuche durchführen

Das sogenannte Attribut-Hilfetool ermöglicht es dir, nach den verschiedenen Attributen zu suchen und gibt die aktuell dafür gültigen Werte an. Um das Tool nutzen zu können, muss der Assistent {marketplace/extension} bereits eingerichtet sein.
Das Tool findest du unter der folgenden URL: {domain}/marketplace_extension/attribute_values
Trage anstelle von {domain} deine plenty Domain ein. Würde deine plenty Domain beispielsweise https://www.meine-plenty-domain.de lauten, wäre die URL wie folgt aufgebaut: https://www.meine-plenty-domain.de/marketplace_extension/attribute_values.

==== Das Attribut-Hilfetool verwenden

Im Katalog findest du die Benennungen der Marktplatzattribute, wie z.B. *Marke*.

Um die für ein Attribut gültigen Werte herauszufinden, gehe vor wie folgt:

[.instruction]
Das Attribut-Hilfetool verwenden:

. Rufe die wie oben beschriebene URL auf.
. Gib den Namen des Attributes in die Suche ein oder nutze Strg+F bzw. Cmd+F, um die Ergebnisliste zu durchsuchen. +
→ In der Spalte *Attribute Label* ist das Attribut zu sehen. +
→ In der Spalte *Value Code* sind die gültigen Werte aufgeführt, die für die Attributwerte in der Spalte *Value Label* übertragen werden müssen. +
*_Hinweis:_* Die gültigen Werte für *Umsatzsteuerklasse* können über das Attribut-Hilfetool nicht abgerufen werden. Diese Werte kannst du der folgenden Tabelle entnehmen:
// Tabelle einfügen
Die Tabelle der gültigen Attributwerte wird jeweils über Nacht aktualisiert.
// end::attributsuche-tool[]
