// tag::marktplatz-daten[]
:market: Conrad
:keywords: {market}, Marktplatz, {market}.de, {market} einrichten, {market} Marktplatz, Multi-Channel, Multichannel, Multi-Channel {market}, Multichannel {market}, Multi Channel {market}
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz {market} in deinem plentymarkets System ein.
:marketplace-url: https://marketplace.plentymarkets.com/conradextension_6948
:assistant-name: ConradExtension
:market-info: pass:quotes[Über das Conrad-Plugin wird der B2B-Marktplatz Conrad mit deinem plentymarkets System verbunden. Durch das Plugin wird der automatische Austausch von Artikel- und Auftragsdaten zwischen plentymarkets und dem Marktplatz Conrad ermöglicht. Dadurch kannst du deine Artikel auf Conrad listen.]
:market-webinar-id: zI1_7iF8U0o
:market-registration: pass:quotes[Du benötigst die Conrad-Zugangsdaten bestehend aus Nutzername und Passwort. Diese Daten erhältst du von Conrad. Hierzu musst du zunächst bei link:https://www.conrad.de/de/service/bestellung-und-beschaffung/marketplace.html[Conrad^] ein Mitgliedskonto erstellen.]
:category-example: VHS Kassetten
//:web-api:
:do-not-map-fields: Produktgruppe + \
Produktbild 1 + \
Produktbild 2 + \
Produktbild 3 + \
Produktbild 4 + \
Produktbild 5
:valid-values-zip: https://drive.google.com/file/d/1VUBBNaTuOfiuWtpKl2TrAV54gm-bR2aW/view?usp=sharing

// end::marktplatz-daten[]

// tag::verbindung-einrichten[]
Um die Verbindung zu {market} einzurichten, kannst du entweder der Anleitung auf dieser Seite folgen oder dir folgendes Webinar ansehen:

video::{market-webinar-id}[youtube]
// end::verbindung-einrichten[]

// tag::zuordnung-stornierung[]
. Klicke auf *Neuen Eintrag hinzufügen*. +
→ Eine Zeile wird eingefügt.
. Wähle aus der Dropdown-Liste links den plentymarkets Status.
. Wähle aus der Dropdown-Liste rechts einen Grund für die Stornierung von {market}. +
Die folgenden Gründe können an {market} übertragen werden: +

* `34` = Stornierung: Fehlbestellung
* `35` = Stornierung: Unerwünschte Zahlungsbedingung
* `37` = Stornierung: Zu lange Lieferzeit
* `39` = Vereinbarung zwischen Käufer und Verkäufer getroffen
// end::zuordnung-stornierung[]

// tag::zuordnung-datenfelder[]
include::../instructions/katalog-mirakl-zuordnungen.adoc[]

In der ZIP-Datei link:{valid-values-zip}[{market}: Gültige Werte^] findest du CSV-Dateien für jedes Marktplatzattribut. Innerhalb einer CSV-Datei sind die gültigen Werte für das Attribut abgebildet. Den zu übertragenden Wert findest du immer in der Spalte *Code*.
// end::zuordnung-datenfelder[]

// tag::automatisierung-zusammenfassung[]
* Auftragsbestätigung an {market} melden
* Auftragsablehnung an {market} melden
* Versandbestätigung an {market} melden
* Auftragsstornierung an {market} melden
* Rückerstattung an {market} melden
// end::automatisierung-zusammenfassung[]

// tag::automatisierung-details[]
[#1000]
=== Auftragsbestätigung an {market} melden

:table-event-procedure: <<#{market}-ereignisaktion-auftragsbestaetigung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{market}-ereignisaktion-auftragsbestaetigung]
.Ereignisaktion, um Auftragsbestätigungen an {market} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [3] *Warten auf Zahlung*.

| *Filter*
| *Auftrag > Herkunft*
| *{market}*

| *Aktion*
| *Plugins > {market}: Auftrag annehmen*
|
|===

[#1005]
=== Auftragsablehnung an {market} melden

:table-event-procedure: <<#{market}-ereignisaktion-auftragsablehnung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{market}-ereignisaktion-auftragsablehnung]
.Ereignisaktion, um Auftragsablehnung an {market} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[8] Storniert*.

| *Filter*
| *Auftrag > Herkunft*
| *{market}*

| *Aktion*
| *Plugins > {market}: Auftrag ablehnen*
|
|===

[#1010]
=== Versandbestätigung an {market} melden

:table-event-procedure: <<#{market}-ereignisaktion-versandbestaetigung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{market}-ereignisaktion-versandbestaetigung]
.Ereignisaktion, um Versandbestätigungen an {market} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [7] *Warenausgang gebucht*.

| *Filter*
| *Auftrag > Herkunft*
| *{market}*

| *Aktion 1*
| *Plugins > {market}: Aktualisieren der Carrier Tracking Informationen für eine bestimmte Bestellung*
|

| *Aktion 2*
| *Plugins > {market}: Versand eines Auftrags validieren*
|
|===

[#1020]
=== Auftragsstornierung an {market} melden

:table-event-procedure: <<#{market}-ereignisaktion-auftragsstornierung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{market}-ereignisaktion-auftragsstornierung]
.Ereignisaktion, um Stornierungen an {market} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[8] Storniert*.

| *Filter*
| *Auftrag > Herkunft*
| *{market}*

| *Aktion*
| *Plugins > {market}: Stornieren Sie die Auftragsposition*
|
|===

[#1030]
=== Rückerstattung an {market} melden

:table-event-procedure: <<#{market}-ereignisaktion-rueckerstattung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{market}-ereignisaktion-rueckerstattung]
.Ereignisaktion, um Rückerstattungen an {market} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[11] Gutschrift*.

| *Filter*
| *Auftrag > Herkunft*
| *{market}*

| *Aktion*
| *Plugins > {market}: Rückerstattungs-Bestellzeilen*
|
|===


[#auftraege-archivieren]
== Nicht bestätigte Aufträge archivieren

Wenn ein Auftrag abgelehnt oder storniert wurde, oder für einen Auftrag eine Gutschrift ausgeschrieben wurde, solltest du den Auftrag archivieren. Dies kannst du automatisch über den Aktionsmanager machen.

Du musst für jeden Status eine eigene Aktion einrichten.

[#1110]
=== Abgelehnte Aufträge archivieren

[.collapseBox]
.Aktion einrichten
--
[.instruction]
Aktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Öffne das Tab *Neue Aktion*.
 Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-abgelehnte-auftraege>> vor.
. Öffne das Tab *Filter*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-abgelehnte-auftraege>> vor.
. Öffne das Tab *Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-abgelehnte-auftraege>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Aktion wird erstellt.

--

[#{market}-aktionsmanager-abgelehnte-auftraege]
.Einstellungen Aktionsmanager
[cols="1,3a"]
|===
|Tab |Einstellung

| *Status*
| Aktiviere die Option *Aktiv*. +
Stelle ein, wann die Aktion jeden Tag ausgeführt werden soll. +
Gib einen Namen ein.

| *Auftragstyp*
| Wähle aus der Dropdown-Liste *Status* die Option *[7] Warenausgang gebucht*. +
Wähle aus der Dropdown-Liste *Letzter Statuswechsel* die Option *Tage eingeben*. Gib den Wert `2` in das neue Textfeld ein. +
Wähle aus der Liste *Auftragsherkunft* die Option {market}.

| *Aktion*
| Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* einen endgültigen Status, z.B. 7.99.

|===

[#1120]
=== Stornierte Aufträge archivieren

[.collapseBox]
.Aktion einrichten
--
[.instruction]
Aktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Öffne das Tab *Neue Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-stornierte-auftraege>> vor.
. Öffne das Tab *Filter*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-stornierte-auftraege>> vor.
. Öffne das Tab *Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-stornierte-auftraege>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Aktion wird erstellt.

--

[#{market}-aktionsmanager-stornierte-auftraege]
.Einstellungen Aktionsmanager
[cols="1,3a"]
|===
|Tab |Einstellung

| *Status*
| Aktiviere die Option *Aktiv*. +
Stelle ein, wann die Aktion jeden Tag ausgeführt werden soll. +
Gib einen Namen ein.

| *Auftragstyp*
| Wähle aus der Dropdown-Liste *Status* die Option *[8] Storniert*. +
Wähle aus der Dropdown-Liste *Letzter Statuswechsel* die Option *Tage eingeben*. Gib den Wert `2` in das neue Textfeld ein. +
Wähle aus der Liste *Auftragsherkunft* die Option {market}.

| *Aktion*
| Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* einen endgültigen Status, z.B. 8.99.

|===

[#1130]
=== Aufträge mit Gutschriften archivieren

[.collapseBox]
.Aktion einrichten
--
[.instruction]
Aktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Öffne das Tab *Neue Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-gutschriften>> vor.
. Öffne das Tab *Filter*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-gutschriften>> vor.
. Öffne das Tab *Aktion*.
. Nimm die gewünschten Einstellungen anhand der Informationen in <<#{market}-aktionsmanager-gutschriften>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Aktion wird erstellt.

--

[#{market}-aktionsmanager-gutschriften]
.Einstellungen Aktionsmanager
[cols="1,3a"]
|===
|Tab |Einstellung

| *Status*
| Aktiviere die Option *Aktiv*. +
Stelle ein, wann die Aktion jeden Tag ausgeführt werden soll. +
Gib einen Namen ein.

| *Auftragstyp*
| Wähle aus der Dropdown-Liste *Status* die Option *[11] Gutschrift*. +
Wähle aus der Dropdown-Liste *Letzter Statuswechsel* die Option *Tage eingeben*. Gib den Wert `2` in das neue Textfeld ein. +
Wähle aus der Liste *Auftragsherkunft* die Option {market}.

| *Aktion*
| Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* einen endgültigen Status, z.B. 11.99.

|===
// end::automatisierung-details[]

// tag::voraussetzungen-produktdaten-uebertragen[]
=== Voraussetzungen für die Produktdatenübertragung

* Die Plugins link:{marketplace-url}[{market}^]{nbsp}icon:external-link[] sowie *Mirakl Connector* wurden im plentyMarketplace gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {market} und Mirakl aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {assistant-name}* wurde die Grundeinrichtung vorgenommen. Für die Produktübertragung muss die Option *Produkte exportieren* im Schritt Datenaustausch aktiv sein.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurden die Auftragsherkünfte *Mirakl* sowie *{assistant-name}* an einem bestehenden Preis aktiviert *_oder_* es wurde ein neuer Verkaufspreis erstellt, bei dem die Auftragsherkünfte *Mirakl* und *{assistant-name}*  aktiviert wurden.
* Du hast bereits einen <<daten/daten-exportieren/kataloge-verwalten#, Katalog>> für die Übertragung der Daten erstellt.
// end::voraussetzungen-produktdaten-uebertragen[]

// tag::voraussetzungen-angebotsdaten-uebertragen[]
=== Voraussetzungen für die Angebotsdatenübertragung

* Die Plugins link:{marketplace-url}[{market}^]{nbsp}icon:external-link[] sowie *Mirakl Connector* wurden im plentyMarketplace gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte *{market}* und *Mirakl* aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {assistant-name}* wurde die Grundeinrichtung vorgenommen.
** *Bestand synchronisieren* ist im Datenaustausch-Schritt aktiviert, damit die Angebote korrekt übertragen werden.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* sind an einem bestehenden Preis die Auftragsherkünfte *Mirakl* und *{market}* aktiviert *_oder_* ein neuer Verkaufspreis ist erstellt, in dem die Auftragsherkünfte *Mirakl* und *{market}* aktiviert wurden.

Die Angebotsübertragung findet alle 15 Minuten statt. Es werden nur Artikel übertragen, die die folgenden Voraussetzungen erfüllen:

* An der Variante sind die Auftragsherkünfte *Mirakl* und *{market}* aktiviert.
* An der Variante ist ein Preis aktiv, der für *{market}*, *Mirakl* und *WEB-API* aktiviert wurde.
* An dem Artikel (bzw. an der Variante) ist ein Versandprofil aktiv, das für *{market}*, *Mirakl* und *WEB-API* wurde.
* An der Variante ist ein Wert als Marktplatz-SKU für *{market}* hinterlegt.
* An der Variante hat in den letzten 15 Minuten eine Änderung an dem Bestand oder Preis stattgefunden
** Das Setzen eines neuen Zeitstempels über die Gruppenfunktion oder Stapelverarbeitung führt auch zu einer Übertragung der Variante. Somit muss an der Variante die Warenbestandsbeschränkung *Auf Netto-WB* oder *Keine* gewählt sein und die Variante muss positiven Bestand haben.
// end::voraussetzungen-angebotsdaten-uebertragen[]

// tag::attributsuche-tool[]
=== Das Attribut-Hilfetool verwenden

Das sogenannte Attribut-Hilfetool ermöglicht es dir, nach den verschiedenen Attributen zu suchen und gibt die aktuell dafür gültigen Werte an. Um das Tool nutzen zu können, muss der Assistent *{assistant-name}* bereits eingerichtet sein.
Das Tool findest du unter der folgenden URL: `domain/marketplace_extension/attribute_values`.
Trage anstelle von `domain` deine plenty Domain ein. Würde deine plenty Domain beispielsweise `https://www.meine-plenty-domain.de` lauten, wäre die URL wie folgt aufgebaut: `https://www.meine-plenty-domain.de/marketplace_extension/attribute_values`. +
Die Tabelle der gültigen Attributwerte wird jeweils über Nacht aktualisiert.

Im Katalog findest du die Benennungen der Marktplatzattribute, wie z.B. *Marke*. Um die für ein Attribut gültigen Werte herauszufinden, gehe vor wie folgt.

[.instruction]
Das Attribut-Hilfetool verwenden:

. Rufe die wie oben beschriebene URL auf.
. Gib den Namen des Attributes in die Suche ein oder nutze Strg+F bzw. Cmd+F, um die Ergebnisliste zu durchsuchen. +
→ In der Spalte *Attribute Label* ist das Attribut zu sehen. +
→ In der Spalte *Value Code* sind die gültigen Werte aufgeführt, die für die Attributwerte in der Spalte *Value Label* übertragen werden müssen.
// end::attributsuche-tool[]

// tag::box-angebotsfelder-produktexportfeld[]
[IMPORTANT]
.Wie hängen die Angebotsfelder, das Produktexportfeld und die Marktplatz-SKU an der Variante zusammen?
====
Die Angebotsfelder *sku* und *product-id* werden grundsätzlich immer mit dem Wert gefüllt, der an der Variante im Feld *Marktplatz-SKU* für den Marktplatz definiert wurde.
Das Angebotsfeld *product-id-type* wird standardmäßig mit dem Wert *SHOP_SKU* übertragen, kann aber mit einem anderen Wert überschrieben werden, z.B. *SKU*.

* Wenn *SKU* gewählt wird, muss die SKU vom Marktplatz als Marktplatz-SKU an der Variante definiert werden.
// * Wenn *EAN* gewählt wird, muss die EAN der Variante als Marktplatz-SKU an der Variante definiert werden. Bitte nicht verwenden, diese Funktion ist noch nicht im Marktplatz aktiv
// * Wenn *ISBN* gewählt wird, muss die ISBN der Variante als Marktplatz-SKU an der Variante definiert werden. Bitte nicht verwenden, diese Funktion ist noch nicht im Marktplatz aktiv

Das Produktexportfeld *Produkt-ID (Artikelnr. des Verkäufers)* wird je nach Einstellung im Katalog gefüllt.
Bei der ersten Übertragung, die über Nacht stattfindet, wird die Marktplatz-SKU an der Variante in plentymarkets automatisch aus der Varianten-ID gebildet. Die Marktplatz-SKU kann alternativ per Import oder manuell definiert werden.
====
// end::box-angebotsfelder-produktexportfeld[]

// tag::werte-uebertragen[]
=== Werte für die Übertragung an den Marktplatz definieren

Die Werte *product-id* und *sku* werden wie folgt übertragen:

* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, muss mit dem Wert der *product-id* in der Angebotsübertragung übereinstimmen.
* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, wird im Katalog definiert.
* Der Wert, der als Marktplatz-SKU an der Variante hinterlegt wird, wird für die Felder *sku* und *product-id* bei der Angebotsübertragung verwendet.
* Wenn du keinen Wert für die Marktplatz-SKU an einer Variante definiert hast, aber die Marktplatzverfügbarkeiten aktiviert wurden, wird die Variante in der Angebotsübertragung ohne *sku* und *product-id* übertragen.

Daraus ergeben sich die folgenden Zuordnungen für die Produktübertragung:

* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* nur die Varianten-ID zugeordnet. Bei der ersten Produktübertragung von dieser Variante wird automatisch (wenn sonst kein Wert vorher definiert wurde) die Varianten-ID als Marktplatz-SKU an der entsprechenden Variante gespeichert.
* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* die SKU zugeordnet und die Varianten-ID als Ausweich-Datenfeld definiert. Vor der ersten Produktübertragung der Variante wird die Marktplatz-SKU an der Variante definiert. Nimmst du diese Einstellung nicht vor,  wird die Varianten-ID nach der ersten Produktübertragung automatisch als Marktplatz-SKU an der Variante hinterlegt.
// end::werte-uebertragen[]

////
Wird noch überarbeitet
// tag::datenfelder-grundpreisangabe[]
[TIP]
.Datenfelder zur Grundpreisangabe pflegen
====
Die beiden Datenfelder *Brutto-Inhaltsmenge für Grundpreisangabe* und *Einheit der Grundpreisangabe* werden zwar nicht als Pflichtfelder markiert, müssen aber hinsichtlich der rechtlichen Situation zur Angabe der Grundpreise gepflegt und übertragen werden.
Für beide Datenfelder gibt es keine Liste von gültigen Werten. Wir empfehlen jedoch dem Attribut *Brutto-Inhaltsmenge für Grundpreisangabe* das plentymarkets Datenfeld *Inhalt Menge* zuzuordnen und für das Attribut *Einheit der Grundpreisangabe* eine Eigenschaft zu erstellen und die Werte an den Varianten zu speichern, z.B. „g“ für *Gramm*.
====
// end::datenfelder-grundpreisangabe[]
////

// tag::produktdaten-aktualisieren[]
=== Produktdaten aktualisieren

Du kannst zu jeder Zeit eine Aktualisierung der Produktdaten vornehmen. Ausgeschlossen davon sind jedoch die folgenden Produktdaten:

* Verpackungseinheiten
* Hersteller-Teilenummer
* Artikelnummer des Verkäufers

Wenn du eines oder mehrere der o.g. Felder ändern möchtest, musst du das Produkt zuerst löschen und dann neu übertragen. Gehe dazu vor wie folgt:

[.instruction]
Produktdaten aktualisieren:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Erstelle eine Eigenschaft vom Typ *Kurztext*.
. Gib einen Namen ein, z.B. *Marktplatz-Produkt löschen*.
. Öffne das Menü *Daten » Kataloge*.
. Öffne den entsprechenden Katalog.
. Ordne dem Datenfeld *Product Invalidierungs Markierung* bzw. *InvalidationFlag* die Eigenschaft zum Löschen des Produkts, die du gerade erstellt hast, zu.
. Öffne den Assistenten.
. Gehe in den Schritt „Zuordnung der Angebots- Eigenschaften“.
. Ordne der Eigenschaft *{market} Update-Delete* das Datenfeld *update-delete* zu.
. Wähle an der zu löschenden Variante den Auswahlwert *delete*. +
*_Hinweis:_* Eine Bestands- oder Preisänderung der Variante kann einige Zeit dauern. Alternativ kannst du diese Änderung manuell vornehmen.
. Warte bis zur nächsten Angebotsübertragung. +
→ Dies kann bis zu 15 Minuten dauern.
. Deaktivere die Marktplatzverfügbarkeit für den Marktplatz und Mirakl an der Variante.
. Entferne die Eigenschaft für die Katalogverknüpfung an der Variante.
. Lösche das Angebot zu dem Produkt manuell im Backend des Marktplatzes.
. Aktiviere an der entsprechenden Variante die Eigenschaft, die du für das Löschen des Produkts erstellt hast, und hinterlege den Wert *kill*.
. Aktiviere die Eigenschaft für die Katalogverknüpfung an der Variante.
. Warte bis zur nächsten Übertragung der Produkte. +
→  Diese findet über Nacht statt.
. Nachdem du das Produkt gelöscht hast, musst du 24 bis 48 Stunden warten, bis du die gleiche Produkt-ID wieder verwenden darfst.
. Entferne nach der Wartezeit die Eigenschaft, die du für das Löschen des Produkts erstellt hast, von der Variante.
. Aktiviere an der Variante die Marktplatzverfügbarkeit für den Marktplatz und Mirakl erneut.
// end::produktdaten-aktualisieren[]



// tag::weitere-datenfelder-angebotsuebertragung[]
[discrete]
=== Weitere Datenfelder, die bei der Angebotsübertragung übermittelt werden

* *sku* und *product-id*: Diese Felder werden automatisch mit dem Wert befüllt, der als Marktplatz-SKU an der Variante hinterlegt wurde.
* *product-id-type*: Dieses Feld wird standardmäßig mit dem Wert *SHOP_SKU* befüllt. Im Assistentenschritt *Zuordnung der Angebots- Eigenschaften* kannst du eine Eigenschaft zuordnen, um pro Variante einen der folgenden Werte zu übertragen: *ISBN*, *SKU* oder *EAN*. Dieses Feature wird weiter unten detaillierter erklärt.
* *price*: Dieses Feld wird automatisch mit dem Wert befüllt, der an der Variante für den am Marktplatz aktivierten Preis definiert wurde. Wurden mehrere Verkaufspreise an der Variante definiert, die ebenfalls für den Marktplatz freigegeben sind, wird der Preis mit der niedrigsten ID exportiert.
* *quantity*: Dieses Feld wird automatisch mit dem Nettobestand oder den summierten Nettobeständen aus den Lagern befüllt, die im Assistent *{assistant-name}* im Schritt *Lagerauswahl* gewählt wurden.
* *min-quantity-alert*: Dieses Feld wird automatisch mit dem Wert *1* übertragen.
* *state*: Dieses Feld wird automatisch mit dem Wert *11* übertragen.
* *available-start-date*: Dieses Feld wird automatisch mit einem Zeitstempel übertragen.
* *discount-ranges*: In diesem Feld werden ein oder mehrere <<artikel/einstellungen/preise#100, Verkaufspreise>> übertragen.
* *allow-quote-requests*: Dieses Feld wird automatisch mit dem Wert *false* übertragen.
// end::weitere-datenfelder-angebotsuebertragung[]


// tag::einleitung-automatisierte-auftragsabwicklung[]
Die Aufträge werden alle 15 Minuten in dein plentymarkets System importiert. Der Auftrag wird vom Händler über eine Ereignisaktion akzeptiert. Die Zahlung wird von Conrad eingezogen. Mit der Zahlungszusicherung werden die Rechnungs- und Lieferadresse am Auftrag in deinem plentymarkets System aktualisiert. Über eine Ereignisaktion wird der Versanddienstleister sowie die Paketnummer am Auftrag in Mirakl aktualisiert. Im nächsten Schritt wird über eine weitere Ereignisaktion die Versandbenachrichtigung an Conrad gemeldet. Die von Conrad erstellte Rechnung wird zum Auftrag in dein plentymarkets System importiert. Du kannst dir ebenfalls Ereignisaktionen für Rückerstattungen und Stornierung von Aufträgen einrichten.
// end::einleitung-automatisierte-auftragsabwicklung[]
