// tag::zuordnung-stornierung[]
. Klicke auf *Neuen Eintrag hinzufügen*. +
→ Eine Zeile wird eingefügt.
. Wähle aus der Dropdown-Liste links den plentymarkets Status.
. Wähle aus der Dropdown-Liste rechts einen Grund für die Stornierung von {marketplace}. +
Die folgenden Gründe können an {marketplace} übertragen werden: +

* `34` = Vor Versand vom Kunden storniert
// end::zuordnung-stornierung[]

// tag::zuordnung-datenfelder[]
include::../instructions/katalog-mirakl-zuordnungen.adoc[]

In der ZIP-Datei link:{valid-values-zip}[{marketplace}: Gültige Werte^] findest du CSV-Dateien für jedes Marktplatzattribut. Innerhalb einer CSV-Datei sind die gültigen Werte für das Attribut abgebildet. Den zu übertragenden Wert findest du immer in der Spalte *Code*.
// end::zuordnung-datenfelder[]

// tag::automatisierung-zusammenfassung[]
* Versandbestätigung an {marketplace} melden
* Rückerstattung an {marketplace} melden
* Auftragsstornierung an {marketplace} senden
// end::automatisierung-zusammenfassung[]

// tag::automatisierung-details[]
[#1010]
=== Versandbestätigung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-versandbestaetigung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-versandbestaetigung]
.Ereignisaktion, um Versandbestätigungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [7] *Warenausgang gebucht*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion 1*
| *Plugins > {marketplace}: Aktualisieren der Carrier Tracking Informationen für eine bestimmte Bestellung*
|

| *Aktion 2*
| *Plugins > {marketplace}: Versand eines Auftrags validieren*
|
|===

[#1020]
=== Auftragsstornierung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-auftragsstornierung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-auftragsstornierung]
.Ereignisaktion, um Stornierungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[8] Storniert*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Stornieren Sie die Auftragsposition*
|
|===

[#1030]
=== Rückerstattung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-rueckerstattung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-rueckerstattung]
.Ereignisaktion, um Rückerstattungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[11] Gutschrift*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Rückerstattungs-Bestellzeilen*
|
|===


// end::automatisierung-details[]


// tag::voraussetzungen-produktdaten-uebertragen[]
=== Voraussetzungen

* Die Plugins {*name*} sowie *Mirakl Connector* wurden im Marktplatz gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
// Link zum Plugin einfügen
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {marketplace} und Mirakl aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {marketplace/extension}* wurde die Grundeinrichtung vorgenommen. Für die Produktübertragung muss die Option *Produkte exportieren* im Schritt Datenaustausch aktiv sein.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurden die Mirakl sowie {marketplace/extension} Auftragsherkünfte an einem bestehenden Preis aktiviert *oder* es wurde ein neuer Verkaufspreis erstellt, bei dem Mirakl und {marketplace/extension} Auftragsherkünfte aktiviert wurden.
* Du hast bereits einen Katalog für die Übertragung der Daten erstellt. - LINK zum Kapitel Kataloge
// end::voraussetzungen-produktdaten-uebertragen[]

// tag::voraussetzungen-angebotsdaten-uebertragen[]
=== Voraussetzungen

* Die Plugins {*marketplace*} sowie *Mirakl Connector* wurden im plentyMarketplace gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
// Link zum Marktplatz einfügen
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {*marketplace*} und *Mirakl* aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {marketplace}* wurde die Grundeinrichtung vorgenommen
** *Bestand synchronisieren* ist im Datenaustausch-Schritt aktiviert, damit die Angebot korrekt übertragen werden
* Im Menü *Einrichtung » Artikel » Verkaufspreise* sind an einem bestehenden Preis die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert *_oder_* ein neuer Verkaufspreis ist erstellt, in dem die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert wurden.

Die Angebotsübertragung findet alle 15 Minuten statt. Es werden nur Artikel übertragen, die die folgenden Voraussetzungen erfüllen:
* An der Variante sind die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert.
* An der Variante ist ein Preis aktiv, der für *{marketplace}*, *Mirakl* und *WEB-API* aktiviert wurde.
* An dem Artikel (bzw. an der Variante) ist ein Versandprofil aktiv, das für *{marketplace}*, *Mirakl* und *WEB-API* wurde.
* An der Variante ist ein Wert als Marktplatz-SKU für *{marketplace}* hinterlegt.
* An der Variante hat in den letzten 15 Minuten eine Änderung an dem Bestand oder Preis stattgefunden
** Das Setzen eines neuen Zeitstempels über die Gruppenfunktion oder Stapelverarbeitung, führt auch zu einer Übertragung der Variante und somit muss an der Variante die Warenbestandsbeschränkung „Auf Netto-WB“ oder" „Keine“ ausgewählt sein und die Variante muss positiven Bestand haben
// end::voraussetzungen-angebotsdaten-uebertragen[]

// tag::mediamarkt-support[]
Die gültigen Werte für die verschiedenen Attribute können vom Mediamarkt Support in Erfahrung gebracht werden.
// end::mediamarkt-support[]

// tag::vorhandene-angebote-nicht-ueberschreiben[]
[discrete]
=== Vorhandene Angebote auf Mediamarkt nicht überschreiben
Wenn du bereits Artikel bei Mediamarkt verkaufst, musst du die Varianten in plentymarkets mit ProductIDs versehen. Dies stellt sicher, dass die vorhandenen Produktdaten nicht überschrieben und nur neue Angebote zu den Produkten erstellt werden. Beim Übertragen von Produktdaten wird also eine ProductID an Mediamarkt übermittelt. Die ProductID ist wichtig, um bei der Übertragung von Angebotsdaten eine Verbindung zwischen Angebot und Produkt herzustellen.

Standardmäßig wird bei der Übertragung eines Produktes, für das noch keine Marktplatz-SKU hinterlegt wurde, automatisch die Varianten-ID als Marktplatz-SKU gespeichert. Später bei der Angebotsübertragung wird der Wert, der als Marktplatz-SKU hinterlegt ist, für sku und product-id verwendet.


Um nur neue Angebote zu Produkten zu erstellen, gehe vor wie folgt:
[.instruction]
Neue Angebote erstellen:

. Öffne das Mediamarkt-Backend
. Lade einen Produktexport aus Mediamarkt herunter.
. Öffne das Menü *Daten » Kataloge*. +
→ Die Katalog-Übersicht wird geöffnet.
. Lade einen Produktexport aus dem jeweiligen Katalog herunter.
. Öffne die Mediamarkt-Datei.
. Suche die Product-ID.
. Öffne die plentymarkets Datei.
. Ordne die Product-ID den entsprechenden Varianten zu.
. Importiere die Product-ID als Marktplatz-SKU (Auftragsherkunft Mediamarkt).
. Öffne den Katalog erneut.
. Ordne die Datenfelder SHOP_SKU und Seller Product ID der Marktplatz-SKU zu.
. Wähle als Ausweich-Datenfeld die Varianten-ID.

Existieren hingegen noch keine Produkte auf dem Marktplatz, verknüpfe im Katalog nur die Varianten-ID als *SHOP_SKU* und *Seller Product ID*. Dadurch stellst du sicher, dass auch der richtige Wert als Marktplatz-SKU an der Variante hinterlegt wird.
Gib im Katalog eine gültige EAN an und übertrage diese an Mediamarkt.
// end::vorhandene-angebote-nicht-ueberschreiben[]
