// tag::marktplatz-daten[]
:market: Mediamarkt
:keywords: {market}, Marktplatz, {market}.de, {market} einrichten, {market} Marktplatz, Multi-Channel, Multichannel, Multi-Channel {market}, Multichannel {market}, Multi Channel {market}
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz {market} in deinem plentymarkets System ein.
:assistant-name: Mediamarkt
:marketplace-url: https://marketplace.plentymarkets.com/mediamarkt_6918
:market-info: pass:quotes[Über das Mediamarkt-Plugin wird der Marktplatz Mediamarkt mit deinem plentymarkets System verbunden. Durch das Plugin wird der automatische Austausch von Artikel- und Auftragsdaten zwischen plentymarkets und dem Marktplatz Mediamarkt ermöglicht. Dadurch kannst du deine Artikel auf Mediamarkt listen.]
:market-registration: pass:quotes[Du benötigst die Mediamarkt-Zugangsdaten bestehend aus Nutzername und Passwort. Diese Daten erhältst du von Mediamarkt. Hierzu musst du zunächst bei link:https://www.mediamarkt.de/de/about-us/marketplace[Mediamarkt^] ein Mitgliedskonto erstellen.]
:category-example: VIDEO CASSETTES
//:web-api:
:do-not-map-fields: Main Product Image + \
Additional Product Image 1 + \
Additional Product Image 2 + \


:valid-values-zip: https://drive.google.com/file/d/1a_QY4VOIuC2-A-9jerGDAOmYP72907Xt/view?usp=sharing
// end::marktplatz-daten[]

// tag::verbindung-einrichten[]
Um die Verbindung zu {market} einzurichten, folge der Anleitung auf dieser Seite.
// end::verbindung-einrichten[]

// tag::zuordnung-stornierung[]
. Klicke auf *Neuen Eintrag hinzufügen*. +
→ Eine Zeile wird eingefügt.
. Wähle aus der Dropdown-Liste links den plentymarkets Status.
. Wähle aus der Dropdown-Liste rechts einen Grund für die Stornierung von {market}. +
Die folgenden Gründe können an {market} übertragen werden: +

* `34` = Vor Versand vom Kunden storniert
// end::zuordnung-stornierung[]

// tag::zuordnung-datenfelder[]
:mirakl-mediamarkt-inhalt-einheit:
:mirakl-csv:
:mirakl-hersteller-teilenummer:
include::../instructions/katalog-mirakl-zuordnungen.adoc[]
// end::zuordnung-datenfelder[]

// tag::automatisierung-zusammenfassung[]
* Versandbestätigung an {market} melden
* Rückerstattung an {market} melden
* Auftragsstornierung an {market} senden
// end::automatisierung-zusammenfassung[]

// tag::automatisierung-details[]
[#1010]
=== Versandbestätigung an {market} melden

:table-event-procedure: <<#{market}-ereignisaktion-versandbestaetigung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{market}-ereignisaktion-versandbestaetigung]
.Ereignisaktion, um Versandbestätigungen an {market} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [7] *Warenausgang gebucht*.

| *Filter*
| *Auftrag > Herkunft*
| *{market}*

| *Aktion 1*
| *Plugins > {market}: Aktualisieren der Carrier Tracking Informationen für eine bestimmte Bestellung*
|

| *Aktion 2*
| *Plugins > {market}: Versand eines Auftrags validieren*
|
|===

[#1020]
=== Auftragsstornierung an {market} melden

:table-event-procedure: <<#{market}-ereignisaktion-auftragsstornierung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{market}-ereignisaktion-auftragsstornierung]
.Ereignisaktion, um Stornierungen an {market} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[8] Storniert*.

| *Filter*
| *Auftrag > Herkunft*
| *{market}*

| *Aktion*
| *Plugins > {market}: Stornieren Sie die Auftragsposition*
|
|===

[#1030]
=== Rückerstattung an {market} melden

:table-event-procedure: <<#{market}-ereignisaktion-rueckerstattung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{market}-ereignisaktion-rueckerstattung]
.Ereignisaktion, um Rückerstattungen an {market} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[11] Gutschrift*.

| *Filter*
| *Auftrag > Herkunft*
| *{market}*

| *Aktion*
| *Plugins > {market}: Rückerstattungs-Bestellzeilen*
|
|===

[#1040]
=== Rechnung an {market} senden

:table-event-procedure: <<#{market}-ereignisaktion-rechnung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{market}-ereignisaktion-auftragsablehnung]
.Ereignisaktion, um Rechnung an {market} zu senden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [7.1] *Auftrag exportiert*.

| *Filter*
| *Auftrag > Herkunft*
| *{market}*

| *Aktion*
| *Plugins > {market}: Rechnung hochladen*
|
|===
// end::automatisierung-details[]


// tag::voraussetzungen-produktdaten-uebertragen[]
=== Voraussetzungen für die Produktdatenübertragung

* Die Plugins link:{marketplace-url}[{market}^]{nbsp}icon:external-link[] sowie *Mirakl Connector* wurden im Marktplatz gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {market} und Mirakl aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {assistant-name}* wurde die Grundeinrichtung vorgenommen. Für die Produktübertragung muss die Option *Produkte exportieren* im Schritt Datenaustausch aktiv sein.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurden die Auftragsherkünfte *Mirakl* sowie *{assistant-name}* an einem bestehenden Preis aktiviert *_oder_* es wurde ein neuer Verkaufspreis erstellt, bei dem die Auftragsherkünfte *Mirakl* und *{assistant-name}* aktiviert wurden.
* Du hast bereits einen <<daten/daten-exportieren/kataloge-verwalten#, Katalog>> für die Übertragung der Daten erstellt.
// end::voraussetzungen-produktdaten-uebertragen[]

// tag::voraussetzungen-angebotsdaten-uebertragen[]
=== Voraussetzungen für die Angebotsdatenübertragung

* Die Plugins link:{marketplace-url}[{market}^]{nbsp}icon:external-link[] sowie *Mirakl Connector* wurden im plentyMarketplace gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte *{market}* und *Mirakl* aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {market}* wurde die Grundeinrichtung vorgenommen
** *Bestand synchronisieren* ist im Datenaustausch-Schritt aktiviert, damit die Angebote korrekt übertragen werden.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* sind an einem bestehenden Preis die Auftragsherkünfte *Mirakl* und *{market}* aktiviert *_oder_* ein neuer Verkaufspreis ist erstellt, in dem die Auftragsherkünfte *Mirakl* und *{market}* aktiviert wurden.

Die Angebotsübertragung findet alle 15 Minuten statt. Es werden nur Artikel übertragen, die die folgenden Voraussetzungen erfüllen:

* An der Variante sind die Auftragsherkünfte *Mirakl* und *{market}* aktiviert.
* An der Variante ist ein Preis aktiv, der für *{market}*, *Mirakl* und *WEB-API* aktiviert wurde.
* An dem Artikel (bzw. an der Variante) ist ein Versandprofil aktiv, das für *{market}*, *Mirakl* und *WEB-API* wurde.
* An der Variante ist ein Wert als Marktplatz-SKU für *{market}* hinterlegt.
* An der Variante hat in den letzten 15 Minuten eine Änderung an dem Bestand oder Preis stattgefunden
** Das Setzen eines neuen Zeitstempels über die Gruppenfunktion oder Stapelverarbeitung führt auch zu einer Übertragung der Variante. Somit muss an der Variante die Warenbestandsbeschränkung *Auf Netto-WB* oder *Keine* gewählt sein und die Variante muss positiven Bestand haben.
// end::voraussetzungen-angebotsdaten-uebertragen[]

// tag::mediamarkt-support[]
Kontaktiere dein:e Ansprechpartner:in bei Mediarmarkt für Informationen zu den gültigen Attributwerten.
// end::mediamarkt-support[]

// tag::vorhandene-angebote-nicht-ueberschreiben[]
[discrete]
=== Vorhandene Angebote auf Mediamarkt nicht überschreiben

Wenn du bereits Artikel bei Mediamarkt verkaufst, musst du die Varianten in plentymarkets mit ProductIDs versehen. Dies stellt sicher, dass die vorhandenen Produktdaten nicht überschrieben und nur neue Angebote zu den Produkten erstellt werden. Beim Übertragen von Produktdaten wird also eine ProductID an Mediamarkt übermittelt. Die ProductID ist wichtig, um bei der Übertragung von Angebotsdaten eine Verbindung zwischen Angebot und Produkt herzustellen.

Standardmäßig wird bei der Übertragung eines Produktes, für das noch keine Marktplatz-SKU hinterlegt wurde, automatisch die Varianten-ID als Marktplatz-SKU gespeichert. Später bei der Angebotsübertragung wird der Wert, der als Marktplatz-SKU hinterlegt ist, für *sku* und *product-id* verwendet.

Gib im Katalog eine gültige EAN an und übertrage diese an Mediamarkt.
// end::vorhandene-angebote-nicht-ueberschreiben[]

// tag::werte-uebertragen[]
=== Werte für die Übertragung an den Marktplatz definieren

Die Werte *product-id* und *sku* werden wie folgt übertragen:

* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, muss mit dem Wert der *product-id* in der Angebotsübertragung übereinstimmen.
* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, wird im Katalog definiert.
* Der Wert, der als Marktplatz-SKU an der Variante hinterlegt wird, wird für die Felder *sku* und *product-id* bei der Angebotsübertragung verwendet.
* Wenn du keinen Wert für die Marktplatz-SKU an einer Variante definiert hast, aber die Marktplatzverfügbarkeiten aktiviert wurden, wird die Variante in der Angebotsübertragung ohne *sku* und *product-id* übertragen.

Daraus ergeben sich die folgenden Zuordnungen für die Produktübertragung:

* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* nur die Varianten-ID zugeordnet. Bei der ersten Produktübertragung von dieser Variante wird automatisch (wenn sonst kein Wert vorher definiert wurde) die Varianten-ID als Marktplatz-SKU an der entsprechenden Variante gespeichert.
* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* die SKU zugeordnet und die Varianten-ID als Ausweich-Datenfeld definiert. Vor der ersten Produktübertragung der Variante wird die Marktplatz-SKU an der Variante definiert. Nimmst du diese Einstellung nicht vor,  wird die Varianten-ID nach der ersten Produktübertragung automatisch als Marktplatz-SKU an der Variante hinterlegt.
// end::werte-uebertragen[]

// tag::weitere-datenfelder-angebotsuebertragung[]
[discrete]
=== Weitere Datenfelder, die bei der Angebotsübertragung übermittelt werden

* *sku* und *product-id*: Diese Felder werden automatisch mit dem Wert befüllt, der als Marktplatz-SKU an der Variante hinterlegt wurde.
* *price*: Dieses Feld wird automatisch mit dem Wert befüllt, der an der Variante für den am Marktplatz aktivierten Preis definiert wurde. Wurden mehrere Verkaufspreise an der Variante definiert, die ebenfalls für den Marktplatz freigegeben sind, wird der Preis mit der niedrigsten ID exportiert.
* *quantity*: Dieses Feld wird automatisch mit dem Nettobestand oder den summierten Nettobeständen aus den Lagern befüllt, die im Assistent *{assistant-name}* im Schritt *Lagerauswahl* gewählt wurden.
* *min-quantity-alert*: Dieses Feld wird automatisch mit dem Wert *1* übertragen.
* *state*: Dieses Feld wird automatisch mit dem Wert *11* übertragen.
* *available-start-date*: Dieses Feld wird automatisch mit einem Zeitstempel übertragen.
* *price-ranges*: In diesem Feld werden ein oder mehrere <<artikel/einstellungen/preise#100, Verkaufspreise>> übertragen.
* *allow-quote-requests*: Dieses Feld wird automatisch mit dem Wert *false* übertragen.
* *logistic-class*: Dieses Feld wird standardmäßig nicht befüllt. Wenn kein Wert übertragen wird, wird die Variante mit dem kostenlosen Versandprofil *Free Shipping (FS)* verknüpft. Im Assistentenschritt *Zuordnung der Angebots-Eigenschaften* kannst du eine Eigenschaft zuordnen, um pro Variante einen anderen Wert zu übertragen. Die gültigen Versandprofilcodes findest du im Mediamarkt-Backend unter *Plattformeinstellungen > Versand*. Diese Codes werden in Klammern dargestellt.
* *leadtime-to-ship*: Dieses Feld ist ein Pflichtfeld und wird standardmäßig nicht befüllt. Im Assistentenschritt *Zuordnung der Angebots-Eigenschaften* kannst du eine Eigenschaft zuordnen, um pro Variante einen anderen Wert zu übertragen. Hier sind nur ganze Zahlen zwischen 1 und 45 gültig.
// end::weitere-datenfelder-angebotsuebertragung[]

// tag::einleitung-automatisierte-auftragsabwicklung[]
Die Aufträge werden alle 15 Minuten in dein plentymarkets System importiert. Der Auftrag wird vom Händler über eine Ereignisaktion akzeptiert. Die Zahlung wird von Mediamarkt eingezogen. Mit der Zahlungszusicherung werden die Rechnungs- und Lieferadresse am Auftrag in deinem plentymarkets System aktualisiert. Über eine Ereignisaktion wird der Versanddienstleister sowie die Paketnummer am Auftrag in Mirakl aktualisiert. Im nächsten Schritt wird über eine weitere Ereignisaktion die Versandbenachrichtigung an Mediamarkt gemeldet.  Über eine Ereignisaktion wird eine Rechnung an Mediamarkt gesendet. Du kannst dir ebenfalls Ereignisaktionen für Rückerstattungen und Stornierung von Aufträgen einrichten.
// end::einleitung-automatisierte-auftragsabwicklung[]

// tag::eigenschaften-erstellen[]
Eigenschaften werden verwendet, um Felder an den Marktplatz zu übergeben, die in plentymarkets standardmäßig nicht definiert sind. Im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* erstellst du die Eigenschaften, die Mediamarkt vorgibt.

Weitere Informationen zu Eigenschaften findest du auf der Seite <<artikel/einstellungen/eigenschaften#500, Merkmale und Eigenschaften>>.

Du benötigst die folgenden Eigenschaften für Mediamarkt:

* Logistikklasse
** Es handelt sich hier um das Verknüpfen einer Variante mit einem bestimmten Marktplatz-Versandprofil. Die Marktplatz-Versandprofile können im Marktplatz-Backend unter *Plattformeinstellungen > Versand* eingesehen werden. Der Wert in Klammern ist der Wert, der übertragen werden muss.
* Versandvorlaufzeit
** Es handelt sich hier um das sogenannte _leadtime-to-ship_, also die Zeit, die ein:e Händer:in von der Auftragsanlage bis zur Versandmeldung benötigt. Hier muss eine ganze Zahl übergeben werden, die zwischen 1 und 45 liegt.
* update-delete
** Die Option, ein Angebot löschen zu können. Wenn an der Variante nichts gewählt wird, wird standardmäßig `update` vom Marktplatz verwendet.
// end::eigenschaften-erstellen[]

// tag::eigenschaft-logistikklasse[]
[discrete]
=== Eigenschaft Logistikklasse erstellen

Für jede Variante muss ein Versandprofil-Code an {market} exportiert werden. Versandprofile konfigurierst du im Mirakl-Backend. Die Liste der Versandprofile wird im Mirakl-Backend im Bereich *Plattformeinstellungen > Versand* angezeigt. Der Code wird in der Spalte *Logistikklasse* in Klammern hinter dem Namen der Logistikklasse angezeigt.

:property: Logistikklasse

include::../../_textblocks/instructions/properties-creation.adoc[]

:property: Logistikklasse
:property-area: Artikel
:property-type: Kurztext
:property-name: {market} Logistikklasse

include::../../_textblocks/instructions/properties-creation-table.adoc[]
// end::eigenschaft-logistikklasse[]

// tag::tabelle-zuordnung-angebotseigenschaften[]
| Zuordnung der Angebots-Eigenschaften
| Wähle aus der Dropdown-Liste *Logistikklasse* die Eigenschaft *{market} Logistikklasse*. +
* *Versandvorlaufzeit*: Es handelt sich hier um das sogenannte _leadtime-to-ship_, also die Zeit, die ein:e Händer:in von der Auftragsanlage bis zur Versandmeldung benötigt. Hier muss eine ganze Zahl übergeben werden, die zwischen 1 und 45 liegt. +
* *Logistikklasse*: Hier handelt es sich um das Verbinden einer Variante mit einem bestimmten Marktplatz-Versandprofil. Die Versandprofile des Marktplatzes sind im Backend unter *Plattformeinstellungen > Versand* aufgeführt. Der Wert in Klammern ist der zu übertragende Wert. +
* *update-delete*: Hier handelt es sich um die Option, ein Angebot löschen zu können. Ist dieses Feld nicht befüllt, wird automatisch *update* verwendet.
// end::tabelle-zuordnung-angebotseigenschaften[]
