// tag::marktplatz-daten[]
:marketplace: Mediamarkt
:keywords: {marketplace}, Marktplatz, {marketplace}.de, {marketplace} einrichten, {marketplace} Marktplatz, Multi-Channel, Multichannel, Multi-Channel {marketplace}, Multichannel {marketplace}, Multi Channel {marketplace}
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz {marketplace} in deinem plentymarkets System ein.
:assistant-name: Mediamarkt
:marketplace-url: https://marketplace.plentymarkets.com/mediamarkt_6918
:marketplace-info: pass:quotes[Über das Mediamarkt-Plugin wird der Marktplatz Mediamarkt mit deinem plentymarkets System verbunden. Durch das Plugin wird der automatische Austausch von Artikel- und Auftragsdaten zwischen plentymarkets und dem Marktplatz Mediamarkt ermöglicht. Dadurch kannst du deine Artikel auf Mediamarkt listen.]
:marketplace-registration: pass:quotes[Du benötigst die Mediamarkt-Zugangsdaten bestehend aus Nutzername und Passwort. Diese Daten erhältst du von Mediamarkt. Hierzu musst du zunächst bei link:https://www.mediamarkt.de/de/about-us/marketplace[Mediamarkt^] ein Mitgliedskonto erstellen.]
:category-example: VIDEO CASSETTES
//:web-api:
:do-not-map-fields: SHOP_SKU
:valid-values-zip: https://drive.google.com/file/d/1a_QY4VOIuC2-A-9jerGDAOmYP72907Xt/view?usp=sharing
// end::marktplatz-daten[]

// tag::verbindung-einrichten[]
Um die Verbindung zu {marketplace} einzurichten, folge der Anleitung auf dieser Seite.
// end::verbindung-einrichten[]

// tag::zuordnung-stornierung[]
. Klicke auf *Neuen Eintrag hinzufügen*. +
→ Eine Zeile wird eingefügt.
. Wähle aus der Dropdown-Liste links den plentymarkets Status.
. Wähle aus der Dropdown-Liste rechts einen Grund für die Stornierung von {marketplace}. +
Die folgenden Gründe können an {marketplace} übertragen werden: +

* `34` = Vor Versand vom Kunden storniert
// end::zuordnung-stornierung[]

// tag::zuordnung-datenfelder[]
include::../instructions/katalog-mirakl-zuordnungen.adoc[]

In der ZIP-Datei link:{valid-values-zip}[{marketplace}: Gültige Werte^] findest du CSV-Dateien für jedes Marktplatzattribut. Innerhalb einer CSV-Datei sind die gültigen Werte für das Attribut abgebildet. Den zu übertragenden Wert findest du immer in der Spalte *Code*.
// end::zuordnung-datenfelder[]

// tag::automatisierung-zusammenfassung[]
* Versandbestätigung an {marketplace} melden
* Rückerstattung an {marketplace} melden
* Auftragsstornierung an {marketplace} senden
// end::automatisierung-zusammenfassung[]

// tag::automatisierung-details[]
[#1010]
=== Versandbestätigung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-versandbestaetigung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-versandbestaetigung]
.Ereignisaktion, um Versandbestätigungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [7] *Warenausgang gebucht*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion 1*
| *Plugins > {marketplace}: Aktualisieren der Carrier Tracking Informationen für eine bestimmte Bestellung*
|

| *Aktion 2*
| *Plugins > {marketplace}: Versand eines Auftrags validieren*
|
|===

[#1020]
=== Auftragsstornierung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-auftragsstornierung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-auftragsstornierung]
.Ereignisaktion, um Stornierungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[8] Storniert*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Stornieren Sie die Auftragsposition*
|
|===

[#1030]
=== Rückerstattung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-rueckerstattung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-rueckerstattung]
.Ereignisaktion, um Rückerstattungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[11] Gutschrift*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Rückerstattungs-Bestellzeilen*
|
|===


// end::automatisierung-details[]


// tag::voraussetzungen-produktdaten-uebertragen[]
=== Voraussetzungen für die Produktdatenübertragung

* Die Plugins *{marketplace}* sowie *Mirakl Connector* wurden im Marktplatz gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
// Link zum Plugin einfügen
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {marketplace} und Mirakl aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {assistant-name}* wurde die Grundeinrichtung vorgenommen. Für die Produktübertragung muss die Option *Produkte exportieren* im Schritt Datenaustausch aktiv sein.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurden die Auftragsherkünfte *Mirakl* sowie *{assistant-name}* an einem bestehenden Preis aktiviert *_oder_* es wurde ein neuer Verkaufspreis erstellt, bei dem die Auftragsherkünfte *Mirakl* und *{assistant-name}* aktiviert wurden.
* Du hast bereits einen <<daten/daten-exportieren/kataloge-verwalten#, Katalog>> für die Übertragung der Daten erstellt.
// end::voraussetzungen-produktdaten-uebertragen[]

// tag::voraussetzungen-angebotsdaten-uebertragen[]
=== Voraussetzungen für die Angebotsdatenübertragung

* Die Plugins *{marketplace}* sowie *Mirakl Connector* wurden im plentyMarketplace gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
// Link zum Marktplatz einfügen
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte *{marketplace}* und *Mirakl* aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {marketplace}* wurde die Grundeinrichtung vorgenommen
** *Bestand synchronisieren* ist im Datenaustausch-Schritt aktiviert, damit die Angebote korrekt übertragen werden.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* sind an einem bestehenden Preis die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert *_oder_* ein neuer Verkaufspreis ist erstellt, in dem die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert wurden.

Die Angebotsübertragung findet alle 15 Minuten statt. Es werden nur Artikel übertragen, die die folgenden Voraussetzungen erfüllen:

* An der Variante sind die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert.
* An der Variante ist ein Preis aktiv, der für *{marketplace}*, *Mirakl* und *WEB-API* aktiviert wurde.
* An dem Artikel (bzw. an der Variante) ist ein Versandprofil aktiv, das für *{marketplace}*, *Mirakl* und *WEB-API* wurde.
* An der Variante ist ein Wert als Marktplatz-SKU für *{marketplace}* hinterlegt.
* An der Variante hat in den letzten 15 Minuten eine Änderung an dem Bestand oder Preis stattgefunden
** Das Setzen eines neuen Zeitstempels über die Gruppenfunktion oder Stapelverarbeitung führt auch zu einer Übertragung der Variante. Somit muss an der Variante die Warenbestandsbeschränkung *Auf Netto-WB* oder *Keine* gewählt sein und die Variante muss positiven Bestand haben.
// end::voraussetzungen-angebotsdaten-uebertragen[]

// tag::mediamarkt-support[]
Die gültigen Werte für die verschiedenen Attribute können vom Mediamarkt Support in Erfahrung gebracht werden.
// end::mediamarkt-support[]

// tag::vorhandene-angebote-nicht-ueberschreiben[]
[discrete]
=== Vorhandene Angebote auf Mediamarkt nicht überschreiben

Wenn du bereits Artikel bei Mediamarkt verkaufst, musst du die Varianten in plentymarkets mit ProductIDs versehen. Dies stellt sicher, dass die vorhandenen Produktdaten nicht überschrieben und nur neue Angebote zu den Produkten erstellt werden. Beim Übertragen von Produktdaten wird also eine ProductID an Mediamarkt übermittelt. Die ProductID ist wichtig, um bei der Übertragung von Angebotsdaten eine Verbindung zwischen Angebot und Produkt herzustellen.

Standardmäßig wird bei der Übertragung eines Produktes, für das noch keine Marktplatz-SKU hinterlegt wurde, automatisch die Varianten-ID als Marktplatz-SKU gespeichert. Später bei der Angebotsübertragung wird der Wert, der als Marktplatz-SKU hinterlegt ist, für *sku* und *product-id* verwendet.

Gib im Katalog eine gültige EAN an und übertrage diese an Mediamarkt.
// end::vorhandene-angebote-nicht-ueberschreiben[]

// tag::werte-uebertragen[]
=== Werte für die Übertragung an den Marktplatz definieren

Die Werte *product-id* und *sku* werden wie folgt übertragen:

* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, muss mit dem Wert der *product-id* in der Angebotsübertragung übereinstimmen.
* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, wird im Katalog definiert.
* Der Wert, der als Marktplatz-SKU an der Variante hinterlegt wird, wird für die Felder *sku* und *product-id* bei der Angebotsübertragung verwendet.
* Wenn du keinen Wert für die Marktplatz-SKU an einer Variante definiert hast, aber die Marktplatzverfügbarkeiten aktiviert wurden, wird die Variante in der Angebotsübertragung ohne *sku* und *product-id* übertragen.

Daraus ergeben sich die folgenden Zuordnungen für die Produktübertragung:

* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* nur die Varianten-ID zugeordnet. Bei der ersten Produktübertragung von dieser Variante wird automatisch (wenn sonst kein Wert vorher definiert wurde) die Varianten-ID als Marktplatz-SKU an der entsprechenden Variante gespeichert.
* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* die SKU zugeordnet und die Varianten-ID als Ausweich-Datenfeld definiert. Vor der ersten Produktübertragung der Variante wird die Marktplatz-SKU an der Variante definiert. Nimmst du diese Einstellung nicht vor,  wird die Varianten-ID nach der ersten Produktübertragung automatisch als Marktplatz-SKU an der Variante hinterlegt.
// end::werte-uebertragen[]

// tag::weitere-datenfelder-angebotsuebertragung[]
[discrete]
=== Weitere Datenfelder, die bei der Angebotsübertragung übermittelt werden

* *sku* und *product-id*: Diese Felder werden automatisch mit dem Wert befüllt, der als Marktplatz-SKU an der Variante hinterlegt wurde.
* *price*: Dieses Feld wird automatisch mit dem Wert befüllt, der an der Variante für den am Marktplatz aktivierten Preis definiert wurde. Wurden mehrere Verkaufspreise an der Variante definiert, die ebenfalls für den Marktplatz freigegeben sind, wird der Preis mit der niedrigsten ID exportiert.
* *quantity*: Dieses Feld wird automatisch mit dem Nettobestand oder den summierten Nettobeständen aus den Lagern befüllt, die im Assistent *{assistant-name}* im Schritt *Lagerauswahl* gewählt wurden.
* *min-quantity-alert*: Dieses Feld wird automatisch mit dem Wert *1* übertragen.
* *state*: Dieses Feld wird automatisch mit dem Wert *11* übertragen.
* *available-start-date*: Dieses Feld wird automatisch mit einem Zeitstempel übertragen.
* *discount-ranges*: In diesem Feld werden ein oder mehrere <<artikel/einstellungen/preise#100, Verkaufspreise>> übertragen.
* *allow-quote-requests*: Dieses Feld wird automatisch mit dem Wert *false* übertragen.
// end::weitere-datenfelder-angebotsuebertragung[]
