:keywords: {marketplace}, Marktplatz, {marketplace}.de, {marketplace} einrichten, {marketplace} Marktplatz, Multi-Channel, Multichannel, Multi-Channel {marketplace}, Multichannel {marketplace}, Multi Channel {marketplace}
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz {marketplace} in deinem plentymarkets System ein.

[IMPORTANT]
.{marketplace}-Plugin herunterladen
====
Die Schnittstelle zu {marketplace} wird über ein Plugin integriert. Um das {marketplace}-Plugin nutzen zu können, lade das Plugin im link:{marketplace-url}[plentyMarketplace^]{nbsp}icon:external-link[] herunter.

Um das {marketplace}-Plugin nutzen zu können, benötigst du das Plugin Mirakl Connector. Du findest Mirakl ebenfalls auf plentyMarketplace.
====

:plugin: Mirakl Connector

[.collapseBox]
.{plugin} installieren
--
include::../../../plugins/_textblocks/instructions/plugin-installieren.adoc[]
--

:plugin: {marketplace}
:priority: 1

[.collapseBox]
.{plugin} installieren
--
include::../../../plugins/_textblocks/instructions/plugin-installieren.adoc[]
--

[#100]
== Über {marketplace}

{marketplace-info}

[#200]
== Bei {marketplace} registrieren

{marketplace-registration}

[#600]
== Auftragsherkunft aktivieren

// Auftragsherkunft aktivieren

:market: {marketplace}
:referrer: {marketplace}
:referrer-option: Option {marketplace}

include::../../_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#500]
== Verkaufspreis festlegen

:referrer-price: {marketplace}

include::../../_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#1200]
== Eigenschaften erstellen

Eigenschaften werden verwendet, um Felder an den Marktplatz zu übergeben, die in plentymarkets standardmäßig nicht definiert sind. Im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* erstellst du die Eigenschaften, die {marketplace} vorgibt.

Weitere Informationen zu Eigenschaften findest du auf der Seite <<artikel/einstellungen/eigenschaften#500, Merkmale und Eigenschaften>>.

Du benötigst die folgenden Eigenschaften für {marketplace}:

* Logistikklasse (<<#1210, so geht's>>)
* Versandvorlaufzeit
* Abzugsverfahren

Die Eigenschaften Versandvorlaufzeit und Abzugsverfahren werden automatisch mit dem Typ *Auswahl* erstellt.

[#1210]
=== Eigenschaft Logistikklasse erstellen

Für jede Variante muss ein Versandprofil-Code an {marketplace} exportiert werden. Versandprofile konfigurierst du im Mirakl-Backend. Die Liste der Versandprofile wird im Mirakl-Backend im Bereich *Informationen » Versandkosten* angezeigt. Der Code wird in der Spalte *Logistikklasse* in Klammern hinter dem Namen der Logistikklasse angezeigt.

:property: Logistikklasse

include::../../_textblocks/instructions/properties-creation.adoc[]

:property: Logistikklasse
:property-area: Artikel
:property-type: Kurztext
:property-name: {marketplace} Logistikklasse

include::../../_textblocks/instructions/properties-creation-table.adoc[]

[#1300]
== API-Schlüssel erzeugen

Um die Verbindung für {marketplace} zwischen plentymarkets und Mirakl herzustellen, benötigst du einen API-Schlüssel. Um den API-Schlüssel zu erzeugen, gehe wie folgt vor:

[.instruction]
API-Schlüssel erzeugen:

. Öffne das Backend von Mirakl.
. Klicke auf das Benutzersymbol (icon:user-circle[]).
. Öffne das Tab *API-Schlüssel*.
. Generiere einen neuen API-Schlüssel für {marketplace}.
. Kopiere den API-Schlüssel in die Zwischenablage. Du benötigst den Schlüssel, um dein {marketplace}-Konto in plentymarkets einzurichten.

[#1400]
== Kontoeinstellungen im Assistenten vornehmen

Mit dem Assistenten *{marketplace} - Wizard* im Menü *Einrichtung » Assistenten » Plugins » _Plugin-Set wählen_* richtest du dein {marketplace}-Konto in plentymarkets ein.

:menu-path: pass:quotes[Einrichtung » Assistenten » Plugins » _Plugin-Set wählen_]
:assistant-name: {marketplace}
:number-of-boxes: Info-Box

include::../../_textblocks/instructions/assistant-basic-instructions.adoc[]

// Je nach Umfang des Assistenten entweder eine einzige ausklappbare Box oder eine ausklappbare Box pro Schritt im Assistenten.

[.collapseBox]
.Erläuterungen zu den Optionen des Assistenten
--
[[table-{marketplace}-basic-settings-assistant]]
[width="100%"]
[cols="1,2"]
|======
|Einstellung |Erläuterung

2+| Schritt *Authentifizierung*

| API Environment
a| Wähle eine API-Umgebung aus der Dropdown-Liste. Welche API-Umgebung du wählen solltest, erfährst du von deinen Ansprechpartner:innen bei {marketplace}. +
*_Hinweis:_* Wenn du die API-Umgebung wechselst, also z.B. vom Test-Modus in den Produktiv-Modus, musst du einen neuen <<#1300, API-Schlüssel>> erzeugen.

| API Key
| Trage den <<#1300, API-Schlüssel>> ein, den du erzeugt hast. +
*_Hinweis:_* Wenn du die API-Umgebung wechselst, also z.B. vom Test-Modus in den Produktiv-Modus wechselst, musst du einen neuen <<#1300, API-Schlüssel>> erzeugen.

2+| Schritt *Datenaustausch*

| Datenaustausch
| Wähle die Prozesse, für die du den Datenaustausch zwischen plentymarkets und Mirakl einrichten möchtest.

2+| Schritt *Zuordnung der Rückerstattung*

| Zuordnung der Rückerstattung
a| Hier ordnest du den Rückerstattungsgründen von {marketplace} plentymarkets Auftragsstatus zu.

. Klicke auf *Neuen Eintrag hinzufügen*. +
→ Eine Zeile wird eingefügt.
. Wähle aus der Dropdown-Liste links den plentymarkets Status.
. Wähle aus der Dropdown-Liste rechts einen der Gründe für die Rückerstattung von {marketplace} ein. +
Die folgenden Gründe können an {marketplace} übertragen werden: +

* `15` = Artikel nicht mehr lieferbar
* `16` = Artikel vom Kunden storniert
* `17` = Artikel wurde zurückgeschickt
* `18` = Kunde hat Artikel nicht erhalten
* `19` = Sonstige Vereinbarung getroffen

// Gründe sind für Conrad, Voelkner und MediaMarkt gleich

2+| Schritt *Zuordnung der Stornierung*

| Zuordnung der Stornierung
a|
ifeval::["{marketplace}" == "Conrad"]
include::./conrad-spezial.adoc[tag=zuordnung-stornierung]
endif::[]

ifeval::["{marketplace}" == "MediaMarkt"]
include::./mediamarkt-spezial.adoc[tag=zuordnung-stornierung]
endif::[]

ifeval::["{marketplace}" == "Voelkner"]
include::./voelkner-spezial.adoc[tag=zuordnung-stornierung]
endif::[]

2+| Schritt *Lagerauswahl*

| Lagerauswahl
| Wähle das Lager, das für den Bestandsexport verwendet werden soll.

2+| Schritt *Zuordnung des Versandprofils*

| Zuordnung des Versandprofils
| Trage für die Versandprofile in plentymarkets die entsprechenden Kürzel der Versanddienstleister ein. Die Kürzel findest du auf Mirakl im Menü *Informationen » Transportunternehmen*.

2+| Schritt *Zuordnung der Angebots-Eigenschaften*

| Zuordnung der Angebots-Eigenschaften
| Wähle aus der Dropdown-Liste *Logistikklasse* die Eigenschaft *{marketplace} Logistikklasse*. +
Die Eigenschaften für *Abzugsverfahren* und *Versandvorlaufzeit* sind bereits vorausgewählt.

|======
--

[#800]
== Informationen zum automatischen Datenaustausch

Nachdem du das Plugin installiert und eingerichtet hast, stehen die in <<#datenaustausch-{marketplace}>> automatisierten Prozesse bereit:

[#datenaustausch-{marketplace}]
[cols="1,3"]
.Häufigkeit des Datenaustauschs
|====
|Daten |Intervall

2+| Artikeldaten

| Artikelexport
| Täglich

| Bestandsabgleich
| Alle 15 Minuten

| Preisabgleich
| Alle 15 Minuten

2+| Auftragsdaten

| Auftragsimport
| Alle 15 Minuten

|====

[#900]
== Artikelexport einrichten

Artikeldaten werden über Marktplatz-Formate zu {marketplace} übertragen. Kataloge erstellst du im Menü *Daten » Kataloge*. Du arbeitest zum ersten Mal mit den Katalogen? Dann solltest du dich zuerst mit dem grundlegenden Prinzip der <<daten/daten-exportieren/kataloge-verwalten#, Kataloge vertraut machen>>.

Für jede Produktkategorie von {marketplace}, in der du Produkte verkaufen möchtest, erstellst du einen eigenen Katalog. Verknüpfe anschließend im Marktplatz-Format die von {marketplace} vorgegebenen Felder mit den in plentymarkets gespeicherten Artikeldaten. Die Katalog-Vorlagen werden automatisch täglich zu {marketplace} exportiert, wenn du den Katalog aktivierst.

[IMPORTANT]
.Fehler-Log
====
Wenn es beim Export Probleme gibt, findest du die zugehörigen Log-Einträge auf Mirakl und nicht im Log von plentymarkets.
====

[#1240]
=== Weitere Eigenschaften erstellen

Wenn du für eine oder alle deine Varianten mehrere <<artikel/einstellungen/attribute#, Attribute>> definiert hast, erstelle eine Eigenschaft, die diese Attribute vereint. Unterscheidest du bei einer Variante z.B. sowohl nach Farbe als auch nach Größe, legst du eine Eigenschaft mit der Benennung "Grau XL" an. <<artikel/einstellungen/eigenschaften#1400, Ordne diese Eigenschaften>> den entsprechenden Varianten zu.

Zusätzlich zu den <<#1200, zuvor beschriebenen Eigenschaften>> benötigst du Eigenschaften für alle Datenfelder des Marktplatzes, für die du Daten übergeben möchtest, die es standardmäßig in plentymarkets nicht gibt. Welche Eigenschaften du benötigst, erfährst du in der Dokumentation des Marktplatzes. Du arbeitest zum ersten Mal mit Eigenschaften? Weitere Informationen findest du auf der Handbuchseite zum Thema <<willkommen/allgemeine-funktionen/eigenschaften#, Eigenschaften>>.

[#902]
=== Katalog im Assistenten erstellen

:catalogue-assistant-name: {marketplace}-Katalog
:number-of-boxes: Info-Box
:mapping-fields: die
:catalogue-path: pass:quotes[*Einrichtung » Assistenten » Plugins »* _Plugin-Set wählen_]
:catalogue-note: pass:quotes[Achte darauf, eine Kategorie der untersten Ebene zu wählen. Eine bessere Übersicht findest du auf Mirakl im Menü *Mein Konto » Meine Produktdaten-Einstellungen*.]

include::../../_textblocks/instructions/catalogue-assistant-config.adoc[]

// Je nach Umfang des Assistenten entweder eine einzige ausklappbare Box oder eine ausklappbare Box pro Schritt im Assistenten.

[.collapseBox]
.Erläuterungen zu den Optionen des Assistenten
--
[[table-{marketplace}-catalogue-assistant]]
[width="100%"]
[cols="1,2"]
|======
|Einstellung |Erläuterung

| Einstellungen
| Wähle die Kategorie, in der du deine Artikel auf {marketplace} verkaufen möchtest. Gib dann einen Namen für die zugehörige Kategorie in plentymarkets ein. +
{catalogue-note}

|======
--

[#datenfelder-zuordnen]
=== Datenfelder im Katalog zuordnen

include::../../_textblocks/instructions/katalog-datenfelder-zuordnen.adoc[]

ifeval::["{marketplace}" == "Conrad"]
include::./conrad-spezial.adoc[tag=zuordnung-datenfelder]
endif::[]

ifeval::["{marketplace}" == "Mediamarkt"]
include::./mediamarkt-spezial.adoc[tag=zuordnung-datenfelder]
endif::[]

ifeval::["{marketplace}" == "Voelkner"]
include::./voelkner-spezial.adoc[tag=zuordnung-datenfelder]
endif::[]

[#475]
== Varianten mit {marketplace} Katalog-Kategorie verknüpfen

Nachdem du mit dem Assistenten *{marketplace}* oder manuell ein Marktplatz-Format für {marketplace} erstellt hast, wird in deinem plentymarkets System die Eigenschaft *{marketplace}* erstellt. Für jede Kategorie, die du im ersten Schritt *Einstellungen* des Assistenten wählst, wird die gewählte Kategorie als neuer Auswahlwert zur Eigenschaft *{marketplace} Kategoriegruppe* hinzugefügt. Damit deine Varianten im gewünschten Katalog exportiert werden, müssen sie im *Tab: Eigenschaften* einer Variante mit der Eigenschaft *{marketplace} Kategoriegruppe* verknüpft werden.

[.instruction]
Variante mit Kategorie verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten »* _Artikel öffnen_.
. Wechsele in das *Tab: Varianten*.
. Öffne die Variante, die du verknüpfen möchtest.
. Wechsele in das *Tab: Eigenschaften*.
. Wähle im Bereich *Varianteneigenschaften* aus der Dropdown-Liste *Eigenschaften* die Eigenschaft *{marketplace} Kategoriegruppe* und klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird hinzugefügt.
. Wähle für die Eigenschaft *{marketplace} Kategoriegruppe* aus der Dropdown-Liste *Wert* die gewünschte Kategorie. +
→ Die Variante wird im zugehörigen Katalog exportiert. +
*_Beispiel:_* Wählst du den Wert *{category-example}*, wird die Variante im Katalog für die Kategorie *{category-example}* exportiert.
. Wiederhole die Schritte 5 und 6 für alle Kategorien, in denen du die Variante verkaufen willst.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

=== Eigenschaften mit Varianten verknüpfen und Werte speichern

include::../../_textblocks/instructions/properties-link.adoc[]

[#{marketplace}]
=== Katalogexport aktivieren

:interval: Täglich
:market: {marketplace}

include::../../_textblocks/instructions/catalogue-activation.adoc[]

[#700]
== Variantenverfügbarkeit einstellen

:market-availability: {marketplace}
:option-availability: {marketplace}

include::../../_textblocks/instructions/variantenverfuegbarkeit.adoc[]

// Beachten: Bei manchen Marktplätzen muss zusätzlich zum Marktplatz auch die Web-API aktiviert werden. Dann :web-api: angeben, damit der Text ausgegeben wird.

[#480]
== Ereignisaktionen einrichten

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um den Auftragsstatus bei {marketplace} automatisch zu aktualisieren, wenn bestimmte Ereignisse eintreten. Folgende Ereignisaktionen können eingerichtet werden:

// Welche Ereignisaktionen es gibt hängt vom Marktplatz ab. Hier die gängigsten. Bei Bedarf anpassen!

ifeval::["{marketplace}" == "Conrad"]
include::./conrad-spezial.adoc[tag=automatisierung-zusammenfassung]
endif::[]

ifeval::["{marketplace}" == "Mediamarkt"]
include::./mediamarkt-spezial.adoc[tag=automatisierung-zusammenfassung]
endif::[]

ifeval::["{marketplace}" == "Voelkner"]
include::./voelkner-spezial.adoc[tag=automatisierung-zusammenfassung]
endif::[]

In den folgenden Kapiteln wird beschrieben, wie du die Ereignisaktionen in plentymarkets einrichtest.

[IMPORTANT]
.Weitere Aktionen vorhanden
====
Zusätzlich zu den oben genannten Ereignisaktionen werden durch das {marketplace}-Plugin noch weitere Ereignisaktionen zu Verfügung gestellt. Es gibt diese Aktionen, da sich die Auftragsverarbeitung in plentymarkets und Mirakl voneinander unterscheiden.

Wir empfehlen allerdings, nur die Aktionen zu verwenden, die hier im Detail beschrieben sind.
====

ifeval::["{marketplace}" == "Conrad"]
include::./conrad-spezial.adoc[tag=automatisierung-details]
endif::[]

ifeval::["{marketplace}" == "Mediamarkt"]
include::./mediamarkt-spezial.adoc[tag=automatisierung-details]
endif::[]

ifeval::["{marketplace}" == "Voelkner"]
include::./voelkner-spezial.adoc[tag=automatisierung-details]
endif::[]

////
TODO:

* Gibt es Besonderheiten im Katalog. Ggf. Include-Dateien anpassen.

////
