Auf dieser Seite erfährst du, wie du die Schnittstelle zu {marketplace} einrichtest. Vorab musst du einige vorbereitende Einstellungen in deinem plentymarkets System vornehmen.

[#auftragsherkunft]
== Auftragsherkunft aktivieren

:market: {marketplace}
:referrer: {marketplace}
:referrer-option: Option {marketplace}

include::../../_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#verkaufspreis]
== Verkaufspreis festlegen

:referrer-price: {marketplace}

include::../../_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#eigenschaften-erstellen]
== Eigenschaften erstellen

Eigenschaften werden verwendet, um Felder an den Marktplatz zu übergeben, die in plentymarkets standardmäßig nicht definiert sind. Im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* erstellst du die Eigenschaften, die {marketplace} vorgibt.

Weitere Informationen zu Eigenschaften findest du auf der Seite <<artikel/einstellungen/eigenschaften#500, Merkmale und Eigenschaften>>.

Du benötigst die folgenden Eigenschaften für {marketplace}:

* Logistikklasse
** Es handelt sich hier um das Verknüpfen einer Variante mit einem bestimmten Marktplatz-Versandprofil. Die Marktplatz-Versandprofile können im Marktplatz-Backend unter *Platform Settings > Shipping* eingesehen werden. Der Wert in Klammern ist der Wert, der übertragen werden muss.
* Versandvorlaufzeit
** Es handelt sich hier um das sogenannte _leadtime-to-ship_, also die Zeit, die ein:e Händer:in von der Auftragsanlage bis zur Versandmeldung benötigt. Hier muss eine ganze Zahl übergeben werden, die zwischen 1 und 45 liegt.
* Abzugsverfahren
** Es handelt sich hier um das so genannte _Reverse-Charge-Verfahren_. Es kann entweder `true` oder `false` übertragen werden.
* update-delete
** Die Option, ein Angebot löschen zu können. Wenn an der Variante nichts gewählt wird, wird standardmäßig `update` vom Marktplatz verwendet.

*_Hinweis_*: Die Eigenschaften Versandvorlaufzeit und Abzugsverfahren werden automatisch mit dem Typ *Auswahl* erstellt. Du musst also nur die Eigenschaft <<#1210, Logistikklasse>> erstellen.

[discrete]
=== Eigenschaft Logistikklasse erstellen

Für jede Variante muss ein Versandprofil-Code an {marketplace} exportiert werden. Versandprofile konfigurierst du im Mirakl-Backend. Die Liste der Versandprofile wird im Mirakl-Backend im Bereich *Platform Settings > Shipping* angezeigt. Der Code wird in der Spalte *Logistikklasse* in Klammern hinter dem Namen der Logistikklasse angezeigt.

:property: Logistikklasse

include::../../_textblocks/instructions/properties-creation.adoc[]

:property: Logistikklasse
:property-area: Artikel
:property-type: Kurztext
:property-name: {marketplace} Logistikklasse

include::../../_textblocks/instructions/properties-creation-table.adoc[]


[#api-schluessel]
== API-Schlüssel erzeugen

Um die Verbindung für {marketplace} zwischen plentymarkets und Mirakl herzustellen, benötigst du einen API-Schlüssel. Um den API-Schlüssel zu erzeugen, gehe wie folgt vor:

[.instruction]
API-Schlüssel erzeugen:

. Öffne das Backend von Mirakl.
. Klicke auf das Benutzersymbol (icon:user-circle[]).
. Öffne das Tab *API-Schlüssel*.
. Generiere einen neuen API-Schlüssel für {marketplace}.
. Kopiere den API-Schlüssel in die Zwischenablage. Du benötigst den Schlüssel, um dein {marketplace}-Konto in plentymarkets einzurichten.

[#marktplatz-assistent-durchlaufen]
== {marketplace} Assistent durchlaufen

Mit dem Assistenten *{assistant-name}* im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen]* richtest du dein {marketplace}-Konto in plentymarkets ein.

:menu-path: pass:quotes *[Einrichtung » Assistenten » Plugins » [Plugin-Set wählen]*]
:number-of-boxes: Info-Box

include::../../_textblocks/instructions/assistant-basic-instructions.adoc[]

// Je nach Umfang des Assistenten entweder eine einzige ausklappbare Box oder eine ausklappbare Box pro Schritt im Assistenten.

[.collapseBox]
.Erläuterungen zu den Optionen des Assistenten
--
[[table-{marketplace}-basic-settings-assistant]]
[width="100%"]
[cols="1,2a"]
|======
|Einstellung |Erläuterung

2+| Schritt *Authentifizierung*

| API Environment
a| Wähle eine API-Umgebung aus der Dropdown-Liste. Welche API-Umgebung du wählen solltest, erfährst du von deinen Ansprechpartner:innen bei {marketplace}. +
*_Hinweis:_* Wenn du die API-Umgebung wechselst, also z.B. vom Test-Modus in den Produktiv-Modus, musst du einen neuen <<#1300, API-Schlüssel>> erzeugen.

| API Key
| Trage den <<#1300, API-Schlüssel>> ein, den du erzeugt hast. +
*_Hinweis:_* Wenn du die API-Umgebung wechselst, also z.B. vom Test-Modus in den Produktiv-Modus wechselst, musst du einen neuen <<#1300, API-Schlüssel>> erzeugen.

2+| Schritt *Datenaustausch*

| Datenaustausch
| Wähle die Prozesse, für die du den Datenaustausch zwischen plentymarkets und Mirakl einrichten möchtest.

2+| Schritt *Zuordnung der Rückerstattung*

| Zuordnung der Rückerstattung
a| Hier ordnest du den Rückerstattungsgründen von {marketplace} plentymarkets Auftragsstatus zu.

. Klicke auf *Neuen Eintrag hinzufügen*. +
→ Eine Zeile wird eingefügt.
. Wähle aus der Dropdown-Liste links den plentymarkets Status.
. Wähle aus der Dropdown-Liste rechts einen der Gründe für die Rückerstattung von {marketplace} ein. +
Die folgenden Gründe können an {marketplace} übertragen werden: +

* `15` = Artikel nicht mehr lieferbar
* `16` = Artikel vom Kunden storniert
* `17` = Artikel wurde zurückgeschickt
* `18` = Kunde hat Artikel nicht erhalten
* `19` = Sonstige Vereinbarung getroffen

// Gründe sind für Conrad, Voelkner und MediaMarkt gleich

2+| Schritt *Zuordnung der Stornierung*

| Zuordnung der Stornierung
a|
ifeval::["{marketplace}" == "Conrad"]
include::./conrad-spezial.adoc[tag=zuordnung-stornierung]
endif::[]

ifeval::["{marketplace}" == "MediaMarkt"]
include::./mediamarkt-spezial.adoc[tag=zuordnung-stornierung]
endif::[]

ifeval::["{marketplace}" == "Voelkner"]
include::./voelkner-spezial.adoc[tag=zuordnung-stornierung]
endif::[]

2+| Schritt *Lagerauswahl*

| Lagerauswahl
| Wähle das Lager, das für den Bestandsexport verwendet werden soll.

2+| Schritt *Zuordnung des Versandprofils*

| Zuordnung des Versandprofils
| Trage für die Versandprofile in plentymarkets die entsprechenden Kürzel der Versanddienstleister ein. Die Kürzel findest du auf Mirakl im Menü *Informationen » Transportunternehmen*.

2+| Schritt *Zuordnung der Angebots-Eigenschaften*

| Zuordnung der Angebots-Eigenschaften
| Wähle aus der Dropdown-Liste *Logistikklasse* die Eigenschaft *{marketplace} Logistikklasse*. +
Die Eigenschaften für *Abzugsverfahren* und *Versandvorlaufzeit* sind bereits vorausgewählt. +
*Abzugsverfahren*: Es handelt sich hier um das so genannte _Reverse-Charge-Verfahren_. Es kann entweder `true` oder `false` übertragen werden. +
*Versandvorlaufzeit*: Es handelt sich hier um das sogenannte _leadtime-to-ship_, also die Zeit, die ein:e Händer:in von der Auftragsanlage bis zur Versandmeldung benötigt. Hier muss eine ganze Zahl übergeben werden, die zwischen 1 und 45 liegt. +
*Logistikklasse*: Hier handelt es sich um das Verbinden einer Variante mit einem bestimmten Marktplatz-Versandprofil. Die Versandprofile des Marktplatzes sind im Backend unter *Informationen > Versandkosten* aufgeführt. Der Wert in Klammern ist der zu übertragende Wert. +
*update-delete*: Hier handelt es sich um die Option, ein Angebot löschen zu können. Ist dieses Feld nicht gefüllt, wird automatisch *update* verwendet.

|======
--
