// ggf. Schaubild einfügen

Auf dieser Seite erfährst du, wie du die Plugins *Mirakl* und *{marketplace}* herunterlädst und installierst. Mirakl ist die Plattform, über die {marketplace} angebunden ist.

[#registrieren]
== Bei {marketplace} registrieren

{marketplace-registration}

[#about]
== Über {marketplace}

{marketplace-info}

Um die Verbindung zu {marketplace} einzurichten, kannst du entweder der Anleitung auf dieser Seite folgen oder dir folgendes Webinar ansehen:

video::{marketplace-webinar-id}[youtube]

[#plugins-herunterladen]
== Plugins Mirakl Connector und {marketplace} herunterladen

Die Schnittstelle zu {marketplace} wird über ein Plugin integriert. Um das {marketplace}-Plugin nutzen zu können, lade das Plugin im link:{marketplace-url}[plentyMarketplace^]{nbsp}icon:external-link[] herunter.

Um das {marketplace}-Plugin nutzen zu können, benötigst du außerdem das Plugin *Mirakl Connector*. Du findest Mirakl ebenfalls auf link:https://marketplace.plentymarkets.com/mirakl_6917[plentyMarketplace^]{nbsp}icon:external-link[].



[#mirakl-plugin-installieren]
== {plugin} installieren

:plugin: Mirakl Connector

Installiere das Plugin *{plugin}* wie im Folgenden beschrieben.

include::../../../plugins/_textblocks/instructions/plugin-installieren.adoc[]

[#marktplatz-plugin-installieren]
== {marketplace}-Plugin installieren

Gehe wie im Folgenden beschrieben vor, um das Plugin *{marketplace}* zu installieren.

:plugin: {marketplace}
:priority: 1

include::../../../plugins/_textblocks/instructions/plugin-installieren.adoc[]
