[#475]
== Varianten mit {marketplace} Katalog-Kategorie verknüpfen

Nachdem du mit dem Assistenten *{marketplace}* oder manuell ein Marktplatz-Format für {marketplace} erstellt hast, wird in deinem plentymarkets System die Eigenschaft *{marketplace}* erstellt. Für jede Kategorie, die du im ersten Schritt *Einstellungen* des Assistenten wählst, wird die gewählte Kategorie als neuer Auswahlwert zur Eigenschaft *{marketplace} Kategoriegruppe* hinzugefügt. Damit deine Varianten im gewünschten Katalog exportiert werden, müssen sie im *Tab: Eigenschaften* einer Variante mit der Eigenschaft *{marketplace} Kategoriegruppe* verknüpft werden.

[.instruction]
Variante mit Kategorie verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen]*.
. Wechsele in das *Tab: Varianten*.
. Öffne die Variante, die du verknüpfen möchtest.
. Wechsele in das *Tab: Eigenschaften*.
. Wähle im Bereich *Varianteneigenschaften* aus der Dropdown-Liste *Eigenschaften* die Eigenschaft *{marketplace} Kategoriegruppe* und klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird hinzugefügt.
. Wähle für die Eigenschaft *{marketplace} Kategoriegruppe* aus der Dropdown-Liste *Wert* die gewünschte Kategorie. +
→ Die Variante wird im zugehörigen Katalog exportiert. +
*_Beispiel:_* Wählst du den Wert *{category-example}*, wird die Variante im Katalog für die Kategorie *{category-example}* exportiert.
. Wiederhole die Schritte 5 und 6 für alle Kategorien, in denen du die Variante verkaufen willst.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

==== Eigenschaften mit Varianten verknüpfen und Werte speichern

include::../../_textblocks/instructions/properties-link.adoc[]

[#{marketplace}]
=== Katalogexport aktivieren

:interval: Täglich
:market: {marketplace}

include::../../_textblocks/instructions/catalogue-activation.adoc[]


// Prüfen, wo dieser Abschnitt am besten hinpasst.
An den Varianten entweder manuell (Variante aufrufen und im Tab *Eigenschaften* die Eigenschaft *{assistant-name} Kategoriegruppe* aktivieren und aus der Auswahlliste den Katalog auswählen, mit dem die Variante exportiert werden soll), per Import (über *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* die Eigenschaft *{assistant-name} Kategoriemapping* aufrufen und auf Werte klicken. Dort sind die Auswahlwert-IDs, die für den Import notwendig sind zu finden) oder REST-API (siehe hier und hier) den Katalog mit der Variante verknüpfen.
*_Hinweis_*: Steht im Assistenten *{assistant-name} Katalog* keine Marktplatzkategorie zur Auswahl, dann ist im Assistenten *{assistant-name} im Schritt *Authentifizierung* ggf. die falsche API-Umgebung ausgewählt.


[#700]
== Variantenverfügbarkeit einstellen

:market-availability: {marketplace}
:option-availability: {marketplace}

include::../../_textblocks/instructions/variantenverfuegbarkeit.adoc[]

// Beachten: Bei manchen Marktplätzen muss zusätzlich zum Marktplatz auch die Web-API aktiviert werden. Dann :web-api: angeben, damit der Text ausgegeben wird.
