// Einleitung zur automatisierten Auftragsabwicklung

ifeval::["{market}" == "Conrad"]
include::./conrad-spezial.adoc[tag=einleitung-automatisierte-auftragsabwicklung]
endif::[]

ifeval::["{market}" == "Mediamarkt"]
include::./mediamarkt-spezial.adoc[tag=einleitung-automatisierte-auftragsabwicklung]
endif::[]

ifeval::["{market}" == "Voelkner"]
include::./voelkner-spezial.adoc[tag=einleitung-automatisierte-auftragsabwicklung]
endif::[]

[#ereignisaktionen]
== Ereignisaktionen einrichten

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um den Auftragsstatus bei {market} automatisch zu aktualisieren, wenn bestimmte Ereignisse eintreten. Folgende Ereignisaktionen können eingerichtet werden:

// Welche Ereignisaktionen es gibt hängt vom Marktplatz ab. Hier die gängigsten. Bei Bedarf anpassen!

ifeval::["{market}" == "Conrad"]
include::./conrad-spezial.adoc[tag=automatisierung-zusammenfassung]
endif::[]

ifeval::["{market}" == "Mediamarkt"]
include::./mediamarkt-spezial.adoc[tag=automatisierung-zusammenfassung]
endif::[]

ifeval::["{market}" == "Voelkner"]
include::./voelkner-spezial.adoc[tag=automatisierung-zusammenfassung]
endif::[]

In den folgenden Kapiteln wird beschrieben, wie du die Ereignisaktionen in plentymarkets einrichtest.

[IMPORTANT]
.Weitere Aktionen vorhanden
====
Zusätzlich zu den oben genannten Ereignisaktionen werden durch das {market}-Plugin noch weitere Ereignisaktionen zu Verfügung gestellt. Es gibt diese Aktionen, da sich die Auftragsverarbeitung in plentymarkets und Mirakl voneinander unterscheiden.

Wir empfehlen allerdings, nur die Aktionen zu verwenden, die hier im Detail beschrieben sind.
====

ifeval::["{market}" == "Conrad"]
include::./conrad-spezial.adoc[tag=automatisierung-details]
endif::[]

ifeval::["{market}" == "Mediamarkt"]
include::./mediamarkt-spezial.adoc[tag=automatisierung-details]
endif::[]

ifeval::["{market}" == "Voelkner"]
include::./voelkner-spezial.adoc[tag=automatisierung-details]
endif::[]

////
TODO:
* Gibt es Besonderheiten im Katalog. Ggf. Include-Dateien anpassen.
////
