Eigenschaften werden verwendet, um Felder an den Marktplatz zu übergeben, die in plentymarkets standardmäßig nicht definiert sind.
ifdef::mediamarkt[]
Im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* erstellst du die Eigenschaften, die MediaMarkt vorgibt.
endif::mediamarkt[]

* Du arbeitest zum ersten Mal mit Eigenschaften? Weitere Informationen zu Eigenschaften findest du auf der Seite <<artikel/einstellungen/eigenschaften#500, Merkmale und Eigenschaften>>.

ifdef::conrad,voelkner[]
Die folgenden Eigenschaften sind automatisch in deinem plentymarkts System vorhanden und werden im Assistenten zugeordnet:
endif::conrad,voelkner[]

ifdef::mediamarkt[]
Du benötigst die folgenden Eigenschaften für MediaMarkt:
endif::mediamarkt[]

* Logistikklasse
** Es handelt sich hier um das Verknüpfen einer Variante mit einem bestimmten Marktplatz-Versandprofil. Die Marktplatz-Versandprofile können im Marktplatz-Backend unter *Plattformeinstellungen > Versand* eingesehen werden. Der Wert in Klammern ist der Wert, der übertragen werden muss.
* Versandvorlaufzeit
** Es handelt sich hier um das sogenannte _leadtime-to-ship_, also die Zeit, die ein:e Händler:in von der Auftragsannahme bis zur Versandmeldung benötigt. Hier muss eine ganze Zahl übermittelt werden, die zwischen 1 und 45 liegt.
ifdef::conrad,voelkner[]
* Abzugsverfahren
** Es handelt sich hier um das so genannte _Reverse-Charge-Verfahren_. Es kann entweder `true` oder `false` übertragen werden.
endif::conrad,voelkner[]
* update-delete
** Die Option, ein Angebot löschen zu können. Wenn an der Variante nichts gewählt wird, wird standardmäßig `update` vom Marktplatz verwendet.

ifdef::mediamarkt[]
[discrete]
=== Eigenschaft Logistikklasse erstellen

Für jede Variante muss ein Versandprofil-Code an {market} exportiert werden. Versandprofile konfigurierst du im Mirakl-Backend. Die Liste der Versandprofile wird im Mirakl-Backend im Bereich *Plattformeinstellungen > Versand* angezeigt. Der Code wird in der Spalte *Logistikklasse* in Klammern hinter dem Namen der Logistikklasse angezeigt.

:property: Logistikklasse

include::../properties/instructions/properties-creation.adoc[]

:property: Logistikklasse
:property-area: Artikel
:property-type: Text
:property-name: {market} Logistikklasse

include::../properties/instructions/properties-creation-table.adoc[]
endif::mediamarkt[]

ifdef::mediamarkt[]
[discrete]
=== Eigenschaft Versandvorlaufzeit erstellen

Du kannst für jede Variante die Versandvorlaufzeit übermitteln. Die Versandvorlaufzeit ist die Zeit in Tagen, die ein:e Händler:in von der Auftragsannahme bis zur Versandanmeldung benötigt. Du kannst hier eine ganze Zahl zwischen 1 und 45 übermitteln.

:property: Versandvorlaufzeit

include::../properties/instructions/properties-creation.adoc[]

:property: Versandvorlaufzeit
:property-area: Artikel
:property-type: Ganze Zahl
:property-name: {market} Versandvorlaufzeit

include::../properties/instructions/properties-creation-table.adoc[]
endif::mediamarkt[]

[#weitere-eigenschaften]
=== Weitere Eigenschaften erstellen

Wenn du für eine oder alle deine Varianten mehrere <<artikel/einstellungen/attribute#, Attribute>> definiert hast, erstelle eine Eigenschaft, die diese Attribute vereint. Unterscheidest du bei einer Variante z.B. sowohl nach Farbe als auch nach Größe, legst du eine Eigenschaft mit der Benennung "Grau XL" an. <<artikel/einstellungen/eigenschaften#1400, Ordne diese Eigenschaften>> den entsprechenden Varianten zu.

Zusätzlich zu den zuvor beschriebenen Eigenschaften benötigst du Eigenschaften für alle Datenfelder des Marktplatzes, für die du Daten übergeben möchtest, die es standardmäßig in plentymarkets nicht gibt. Welche Eigenschaften du benötigst, siehst du anhand der Datenfelder im Katalog.