== Erste Schritte

Einleitungstext (Wie hängen der Marktplatz und der Mirakl Connector zusammen?)
Mirakl ist die Plattform, über die der Marktplatz angebunden ist.

=== Über {marketplace}

{marketplace-info}

Um die Verbindung zu {marketplace} einzurichten, kannst du entweder der Anleitung auf dieser Seite folgen oder dir folgendes Webinar ansehen:

video::{marketplace-webinar-id}[youtube]

Text einfügen

=== Plugin {marketplace} herunterladen

[IMPORTANT]
.{marketplace}-Plugin herunterladen
====
Die Schnittstelle zu {marketplace} wird über ein Plugin integriert. Um das {marketplace}-Plugin nutzen zu können, lade das Plugin im link:{marketplace-url}[plentyMarketplace^]{nbsp}icon:external-link[] herunter.

Um das {marketplace}-Plugin nutzen zu können, benötigst du das Plugin Mirakl Connector. Du findest Mirakl ebenfalls auf plentyMarketplace.
====

:plugin: Mirakl Connector

[.collapseBox]
.{plugin} installieren
--
include::../../../plugins/_textblocks/instructions/plugin-installieren.adoc[]
--

=== {marketplace}-Plugin installieren

:plugin: {marketplace}
:priority: 1

[.collapseBox]
.{plugin} installieren
--
include::../../../plugins/_textblocks/instructions/plugin-installieren.adoc[]
--

== {marketplace} einrichten

Einleitungstext

[#200]
=== Bei {marketplace} registrieren

{marketplace-registration}