// tag::zuordnung-stornierung[]
Diese Einstellung hat bei Voelkner keine Auswirkungen.
// end::zuordnung-stornierung[]

// tag::zuordnung-datenfelder[]
include::../instructions/katalog-mirakl-zuordnungen.adoc[]

In der ZIP-Datei link:{valid-values-zip}[{marketplace}: Gültige Werte^] findest du CSV-Dateien für jedes Marktplatzattribut. Innerhalb einer CSV-Datei sind die gültigen Werte für das Attribut abgebildet. Den zu übertragenden Wert findest du immer in der Spalte *Code*.

[IMPORTANT]
.Fehlende Marken
====
Wenn dir auffällt, dass eine Marke fehlt, wende dich an stefanie.schlosser@re-in.de.
====
// end::zuordnung-datenfelder[]

// tag::automatisierung-zusammenfassung[]
* Versandbestätigung an {marketplace} melden
* Rückerstattung an {marketplace} melden
* Rechnung an {marketplace} senden
// end::automatisierung-zusammenfassung[]

// tag::automatisierung-details[]
[#1010]
=== Versandbestätigung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-versandbestaetigung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-versandbestaetigung]
.Ereignisaktion, um Versandbestätigungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [7] *Warenausgang gebucht*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion 1*
| *Plugins > {marketplace}: Aktualisieren der Carrier Tracking Informationen für eine bestimmte Bestellung*
|

| *Aktion 2*
| *Plugins > {marketplace}: Versand eines Auftrags validieren*
|
|===

[#1020]
=== Rückerstattung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-rueckerstattung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-rueckerstattung]
.Ereignisaktion, um Rückerstattungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[11] Gutschrift*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Rückerstattungs-Bestellzeilen*
|
|===

[#1030]
=== Rechnung an {marketplace} senden

:table-event-procedure: <<#{marketplace}-ereignisaktion-rechnung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-auftragsablehnung]
.Ereignisaktion, um Rechnung an {marketplace} zu senden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [7.1] *Auftrag exportiert*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Rechnung hochladen*
|
|===
// end::automatisierung-details[]

// tag::voraussetzungen-produktdaten-uebertragen[]
=== Voraussetzungen

* Die Plugins {*name*} sowie *Mirakl Connector* wurden im Marktplatz gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
// Link zum Plugin einfügen
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {marketplace} und Mirakl aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {marketplace/extension}* wurde die Grundeinrichtung vorgenommen. Für die Produktübertragung muss die Option *Produkte exportieren* im Schritt Datenaustausch aktiv sein.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurden die Mirakl sowie {marketplace/extension} Auftragsherkünfte an einem bestehenden Preis aktiviert *oder* es wurde ein neuer Verkaufspreis erstellt, bei dem Mirakl und {marketplace/extension} Auftragsherkünfte aktiviert wurden.
* Du hast bereits einen Katalog für die Übertragung der Daten erstellt. - LINK zum Kapitel Kataloge
// end::voraussetzungen-produktdaten-uebertragen[]

// tag::voraussetzungen-angebotsdaten-uebertragen[]
=== Voraussetzungen

* Die Plugins {*marketplace*} sowie *Mirakl Connector* wurden im plentyMarketplace gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
// Link zum Marktplatz einfügen
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {*marketplace*} und *Mirakl* aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {marketplace}* wurde die Grundeinrichtung vorgenommen
** *Bestand synchronisieren* ist im Datenaustausch-Schritt aktiviert, damit die Angebot korrekt übertragen werden
* Im Menü *Einrichtung » Artikel » Verkaufspreise* sind an einem bestehenden Preis die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert *_oder_* ein neuer Verkaufspreis ist erstellt, in dem die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert wurden.

Die Angebotsübertragung findet alle 15 Minuten statt. Es werden nur Artikel übertragen, die die folgenden Voraussetzungen erfüllen:
* An der Variante sind die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert.
* An der Variante ist ein Preis aktiv, der für *{marketplace}*, *Mirakl* und *WEB-API* aktiviert wurde.
* An dem Artikel (bzw. an der Variante) ist ein Versandprofil aktiv, das für *{marketplace}*, *Mirakl* und *WEB-API* wurde.
* An der Variante ist ein Wert als Marktplatz-SKU für *{marketplace}* hinterlegt.
* An der Variante hat in den letzten 15 Minuten eine Änderung an dem Bestand oder Preis stattgefunden
** Das Setzen eines neuen Zeitstempels über die Gruppenfunktion oder Stapelverarbeitung, führt auch zu einer Übertragung der Variante und somit muss an der Variante die Warenbestandsbeschränkung „Auf Netto-WB“ oder" „Keine“ ausgewählt sein und die Variante muss positiven Bestand haben
// end::voraussetzungen-angebotsdaten-uebertragen[]

// tag::attributsuche-tool[]
==== Attributsuche durchführen

Das sogenannte Attribut-Hilfetool ermöglicht es dir, nach den verschiedenen Attributen zu suchen und gibt die aktuell dafür gültigen Werte an. Um das Tool nutzen zu können, muss der Assistent {marketplace/extension} bereits eingerichtet sein.
Das Tool findest du unter der folgenden URL: {domain}/marketplace_extension/attribute_values
Trage anstelle von {domain} deine plenty Domain ein. Würde deine plenty Domain beispielsweise https://www.meine-plenty-domain.de lauten, wäre die URL wie folgt aufgebaut: https://www.meine-plenty-domain.de/marketplace_extension/attribute_values.

==== Das Attribut-Hilfetool verwenden

Im Katalog findest du die Benennungen der Marktplatzattribute, wie z.B. *Marke*.

Um die für ein Attribut gültigen Werte herauszufinden, gehe vor wie folgt:

[.instruction]
Das Attribut-Hilfetool verwenden:

. Rufe die wie oben beschriebene URL auf.
. Gib den Namen des Attributes in die Suche ein oder nutze Strg+F bzw. Cmd+F, um die Ergebnisliste zu durchsuchen. +
→ In der Spalte *Attribute Label* ist das Attribut zu sehen. +
→ In der Spalte *Value Code* sind die gültigen Werte aufgeführt, die für die Attributwerte in der Spalte *Value Label* übertragen werden müssen. +
*_Hinweis:_* Die gültigen Werte für *Umsatzsteuerklasse* können über das Attribut-Hilfetool nicht abgerufen werden. Diese Werte kannst du der folgenden Tabelle entnehmen:
// Tabelle einfügen
Die Tabelle der gültigen Attributwerte wird jeweils über Nacht aktualisiert.
// end::attributsuche-tool[]

// tag::box-angebotsfelder-produktexportfeld
[IMPORTANT]
.Wie hängen die Angebotsfelder, das Produktexportfeld und die Marktplatz-SKU an der Variante zusammen?
====
Die Angebotsfelder *sku* und *product-id* werden grundsätzlich immer mit dem Wert gefüllt, der an der Variante im Feld *Marktplatz-SKU* für den Marktplatz definiert wurde.
Das Angebotsfeld *product-id-type* wird standardmäßig mit dem Wert *SHOP_SKU* übertragen, kann aber mit dem Wert *SKU* überschrieben werden, wenn an der Variante die Eigenschaft für Product ID Type *SKU* ausgewählt ist und im Assistentenschritt *Zuordnung der Angebots-Eigenschaften* die Eigenschaft dem entsprechendem Datenfeld zugeordnet wurde //siehe hier:
// Link zu Angebotsdaten?
====
// tag::box-angebotsfelder-produktexportfeld

// tag::werte-uebertragen[]
Werte für die Übertragung an den Marktplatz definieren
Die Werte product-id und SKU werden wie folgt übertragen:
Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, muss mit dem Wert der *product-id* in der Angebotsübertragung übereinstimmen.
Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, wird im Katalog definiert.
Der Wert, der als Marktplatz-SKU an der Variante hinterlegt wird, wird für die Felder *sku* und *product-id* bei der Angebotsübertragung verwendet.
Wenn du keinen Wert für die Marktplatz-SKU an einer Variante definiert hast, aber die Marktplatzverfügbarkeiten aktiviert wurden, wird die Variante in der Angebotsübertragung ohne *sku* und *product-id* übertragen.
Daraus ergeben sich die folgenden Zuordnungen für die Produktübertragung:
Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* nur die Varianten-ID zugeordnet. Bei der ersten Produktübertragung von dieser Variante wird automatisch (wenn sonst kein Wert vorher definiert wurde) die Varianten-ID als Marktplatz-SKU an der entsprechenden Variante gespeichert.
Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* die SKU zugeordnet und die Varianten-ID als Ausweich-Datenfeld definiert. Vor der ersten Produktübertragung der Variante wird die Marktplatz-SKU an der Variante definiert. Nimmst du diese Einstellung nicht vor,  wird die Varianten-ID nach der ersten Produktübertragung automatisch als Marktplatz-SKU an der Variante hinterlegt.
// end::werte-uebertragen[]
