// tag::marktplatz-daten[]
:marketplace: Voelkner
:keywords: {marketplace}, Marktplatz, {marketplace}.de, {marketplace} einrichten, {marketplace} Marktplatz, Multi-Channel, Multichannel, Multi-Channel {marketplace}, Multichannel {marketplace}, Multi Channel {marketplace}
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz {marketplace} in deinem plentymarkets System ein.
:marketplace-url: https://marketplace.plentymarkets.com/voelknerextension_6949
:marketplace-info: pass:quotes[Über das Voelkner-Plugin wird der Marktplatz Voelkner mit deinem plentymarkets System verbunden. Durch das Plugin wird der automatische Austausch von Artikel- und Auftragsdaten zwischen plentymarkets und dem Marktplatz Voelkner ermöglicht. Dadurch kannst du deine Artikel auf Voelkner listen.]
:marketplace-webinar-id: wPiXwdETXEo
:marketplace-registration: pass:quotes[Du benötigst die Voelkner-Zugangsdaten bestehend aus Nutzername und Passwort. Diese Daten erhältst du von Voelkner. Hierzu musst du zunächst bei link:https://www.voelkner.de/marktplatz-seller.html[Voelkner^] ein Mitgliedskonto erstellen.]
:category-example: VHS Kassetten
:do-not-map-fields: Produktgruppe + \
Produktbild 1 + \
Produktbild 2 + \
Produktbild 3 + \
Produktbild 4 + \
Produktbild 5
:valid-values-zip: https://drive.google.com/file/d/1zs0Cy_08E-qYFbNkCMUX-Zp15QghLvih/view?usp=sharing

// end::marktplatz-daten[]

// tag::zuordnung-stornierung[]
Diese Einstellung hat bei Voelkner keine Auswirkungen.
// end::zuordnung-stornierung[]

// tag::zuordnung-datenfelder[]
include::../instructions/katalog-mirakl-zuordnungen.adoc[]

In der ZIP-Datei link:{valid-values-zip}[{marketplace}: Gültige Werte^] findest du CSV-Dateien für jedes Marktplatzattribut. Innerhalb einer CSV-Datei sind die gültigen Werte für das Attribut abgebildet. Den zu übertragenden Wert findest du immer in der Spalte *Code*.

[IMPORTANT]
.Fehlende Marken
====
Wenn dir auffällt, dass eine Marke fehlt, wende dich an stefanie.schlosser@re-in.de.
====
// end::zuordnung-datenfelder[]

// tag::automatisierung-zusammenfassung[]
* Versandbestätigung an {marketplace} melden
* Rückerstattung an {marketplace} melden
* Rechnung an {marketplace} senden
// end::automatisierung-zusammenfassung[]

// tag::automatisierung-details[]
[#1010]
=== Versandbestätigung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-versandbestaetigung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-versandbestaetigung]
.Ereignisaktion, um Versandbestätigungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [7] *Warenausgang gebucht*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion 1*
| *Plugins > {marketplace}: Aktualisieren der Carrier Tracking Informationen für eine bestimmte Bestellung*
|

| *Aktion 2*
| *Plugins > {marketplace}: Versand eines Auftrags validieren*
|
|===

[#1020]
=== Rückerstattung an {marketplace} melden

:table-event-procedure: <<#{marketplace}-ereignisaktion-rueckerstattung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-rueckerstattung]
.Ereignisaktion, um Rückerstattungen an {marketplace} zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[11] Gutschrift*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Rückerstattungs-Bestellzeilen*
|
|===

[#1030]
=== Rechnung an {marketplace} senden

:table-event-procedure: <<#{marketplace}-ereignisaktion-rechnung>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[#{marketplace}-ereignisaktion-auftragsablehnung]
.Ereignisaktion, um Rechnung an {marketplace} zu senden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [7.1] *Auftrag exportiert*.

| *Filter*
| *Auftrag > Herkunft*
| *{marketplace}*

| *Aktion*
| *Plugins > {marketplace}: Rechnung hochladen*
|
|===
// end::automatisierung-details[]

// tag::voraussetzungen-produktdaten-uebertragen[]
=== Voraussetzungen

* Die Plugins {*name*} sowie *Mirakl Connector* wurden im Marktplatz gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
// Link zum Plugin einfügen
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {marketplace} und Mirakl aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {marketplace/extension}* wurde die Grundeinrichtung vorgenommen. Für die Produktübertragung muss die Option *Produkte exportieren* im Schritt Datenaustausch aktiv sein.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurden die Mirakl sowie {marketplace/extension} Auftragsherkünfte an einem bestehenden Preis aktiviert *oder* es wurde ein neuer Verkaufspreis erstellt, bei dem Mirakl und {marketplace/extension} Auftragsherkünfte aktiviert wurden.
* Du hast bereits einen Katalog für die Übertragung der Daten erstellt. - LINK zum Kapitel Kataloge
// end::voraussetzungen-produktdaten-uebertragen[]

// tag::voraussetzungen-angebotsdaten-uebertragen[]
=== Voraussetzungen

* Die Plugins {*marketplace*} sowie *Mirakl Connector* wurden im plentyMarketplace gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
// Link zum Marktplatz einfügen
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {*marketplace*} und *Mirakl* aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {marketplace}* wurde die Grundeinrichtung vorgenommen
** *Bestand synchronisieren* ist im Datenaustausch-Schritt aktiviert, damit die Angebot korrekt übertragen werden
* Im Menü *Einrichtung » Artikel » Verkaufspreise* sind an einem bestehenden Preis die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert *_oder_* ein neuer Verkaufspreis ist erstellt, in dem die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert wurden.

Die Angebotsübertragung findet alle 15 Minuten statt. Es werden nur Artikel übertragen, die die folgenden Voraussetzungen erfüllen:
* An der Variante sind die Auftragsherkünfte *Mirakl* und *{marketplace}* aktiviert.
* An der Variante ist ein Preis aktiv, der für *{marketplace}*, *Mirakl* und *WEB-API* aktiviert wurde.
* An dem Artikel (bzw. an der Variante) ist ein Versandprofil aktiv, das für *{marketplace}*, *Mirakl* und *WEB-API* wurde.
* An der Variante ist ein Wert als Marktplatz-SKU für *{marketplace}* hinterlegt.
* An der Variante hat in den letzten 15 Minuten eine Änderung an dem Bestand oder Preis stattgefunden
** Das Setzen eines neuen Zeitstempels über die Gruppenfunktion oder Stapelverarbeitung, führt auch zu einer Übertragung der Variante und somit muss an der Variante die Warenbestandsbeschränkung „Auf Netto-WB“ oder" „Keine“ ausgewählt sein und die Variante muss positiven Bestand haben
// end::voraussetzungen-angebotsdaten-uebertragen[]

// tag::attributsuche-tool[]
==== Attributsuche durchführen

Das sogenannte Attribut-Hilfetool ermöglicht es dir, nach den verschiedenen Attributen zu suchen und gibt die aktuell dafür gültigen Werte an. Um das Tool nutzen zu können, muss der Assistent {marketplace/extension} bereits eingerichtet sein.
Das Tool findest du unter der folgenden URL: {domain}/marketplace_extension/attribute_values
Trage anstelle von {domain} deine plenty Domain ein. Würde deine plenty Domain beispielsweise https://www.meine-plenty-domain.de lauten, wäre die URL wie folgt aufgebaut: https://www.meine-plenty-domain.de/marketplace_extension/attribute_values.

==== Das Attribut-Hilfetool verwenden

Im Katalog findest du die Benennungen der Marktplatzattribute, wie z.B. *Marke*.

Um die für ein Attribut gültigen Werte herauszufinden, gehe vor wie folgt:

[.instruction]
Das Attribut-Hilfetool verwenden:

. Rufe die wie oben beschriebene URL auf.
. Gib den Namen des Attributes in die Suche ein oder nutze Strg+F bzw. Cmd+F, um die Ergebnisliste zu durchsuchen. +
→ In der Spalte *Attribute Label* ist das Attribut zu sehen. +
→ In der Spalte *Value Code* sind die gültigen Werte aufgeführt, die für die Attributwerte in der Spalte *Value Label* übertragen werden müssen. +
*_Hinweis:_* Die gültigen Werte für *Umsatzsteuerklasse* können über das Attribut-Hilfetool nicht abgerufen werden. Diese Werte kannst du der folgenden Tabelle entnehmen:
// Tabelle einfügen
Die Tabelle der gültigen Attributwerte wird jeweils über Nacht aktualisiert.
// end::attributsuche-tool[]

// tag::box-angebotsfelder-produktexportfeld
[IMPORTANT]
.Wie hängen die Angebotsfelder, das Produktexportfeld und die Marktplatz-SKU an der Variante zusammen?
====
Die Angebotsfelder *sku* und *product-id* werden grundsätzlich immer mit dem Wert gefüllt, der an der Variante im Feld *Marktplatz-SKU* für den Marktplatz definiert wurde.
Das Angebotsfeld *product-id-type* wird standardmäßig mit dem Wert *SHOP_SKU* übertragen, kann aber mit dem Wert *SKU* überschrieben werden, wenn an der Variante die Eigenschaft für Product ID Type *SKU* ausgewählt ist und im Assistentenschritt *Zuordnung der Angebots-Eigenschaften* die Eigenschaft dem entsprechendem Datenfeld zugeordnet wurde //siehe hier:
// Link zu Angebotsdaten?
====
// tag::box-angebotsfelder-produktexportfeld

// tag::werte-uebertragen[]
=== Werte für die Übertragung an den Marktplatz definieren

Die Werte *product-id* und *SKU* werden wie folgt übertragen:

* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, muss mit dem Wert der *product-id* in der Angebotsübertragung übereinstimmen.
* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, wird im Katalog definiert.
* Der Wert, der als Marktplatz-SKU an der Variante hinterlegt wird, wird für die Felder *sku* und *product-id* bei der Angebotsübertragung verwendet.
* Wenn du keinen Wert für die Marktplatz-SKU an einer Variante definiert hast, aber die Marktplatzverfügbarkeiten aktiviert wurden, wird die Variante in der Angebotsübertragung ohne *sku* und *product-id* übertragen.

Daraus ergeben sich die folgenden Zuordnungen für die Produktübertragung:
* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* nur die Varianten-ID zugeordnet. Bei der ersten Produktübertragung von dieser Variante wird automatisch (wenn sonst kein Wert vorher definiert wurde) die Varianten-ID als Marktplatz-SKU an der entsprechenden Variante gespeichert.
* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* die SKU zugeordnet und die Varianten-ID als Ausweich-Datenfeld definiert. Vor der ersten Produktübertragung der Variante wird die Marktplatz-SKU an der Variante definiert. Nimmst du diese Einstellung nicht vor,  wird die Varianten-ID nach der ersten Produktübertragung automatisch als Marktplatz-SKU an der Variante hinterlegt.
// end::werte-uebertragen[]

// tag::datenfelder-grundpreisangabe[]
[TIP]
.Datenfelder zur Grundpreisangabe pflegen
====
Die beiden Datenfelder *Brutto-Inhaltsmenge für Grundpreisangabe* und *Einheit der Grundpreisangabe* werden zwar nicht als Pflichtfelder markiert, müssen aber hinsichtlich der rechtlichen Situation zur Angabe der Grundpreise gepflegt und übertragen werden.
Für beide Datenfelder gibt es keine Liste von gültigen Werten. Wir empfehlen jedoch dem Attribut *Brutto-Inhaltsmenge für Grundpreisangabe* das plentymarkets Datenfeld *Inhalt Menge* zuzuordnen und für das Attribut *Einheit der Grundpreisangabe* eine Eigenschaft zu erstellen und die Werte an den Varianten zu speichern, z.B. „g“ für *Gramm*.
====
// end::datenfelder-grundpreisangabe[]

// tag::produktdaten-aktualisieren[]
=== Produktdaten aktualisieren

Du kannst zu jeder Zeit eine Aktualisierung der Produktdaten vornehmen. Ausgeschlossen davon sind jedoch die folgenden Produktdaten:
* Verpackungseinheiten
* Hersteller-Teilenummer
* Artikelnummer des Verkäufers

Wenn du eines oder mehrere der o.g. Felder ändern möchtest, musst du das Produkt zuerst löschen und dann neu übertragen. Gehe dazu vor wie folgt:

[.instruction]
Produktdaten aktualisieren:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Erstelle eine Eigenschaft vom Typ *Kurztext*.
. Gib einen Namen ein, z.B. *Marktplatz-Produkt löschen*.
. Öffne das Menü *Daten » Kataloge*.
. Öffne den entsprechenden Katalog.
. Ordne dem Datenfeld *Product Invalidierungs Markierung* bzw. *InvalidationFlag* die Eigenschaft zum Löschen des Produkts, die du gerade erstellt hast, zu.
. Öffne den Assistenten.
. Gehe in den Schritt „Zuordnung der Angebots- Eigenschaften“.
. Ordne der Eigenschaft *{marketplace} Update-Delete* das Datenfeld *update-delete* zu.
. Wähle an der zu löschenden Variante den Auswahlwert *delete*. +
*_Hinweis:_* Eine Bestands- oder Preisänderung der Variante kann einige Zeit dauern. Alternativ kannst du diese Änderung manuell vornehmen.
. Warte bis zur nächsten Angebotsübertragung. +
→ Dies kann bis zu 15 Minuten dauern.
. Deaktivere die Marktplatzverfügbarkeit für den Marktplatz und Mirakl an der Variante.
. Entferne die Eigenschaft für die Katalogverknüpfung an der Variante.
. Lösche das Angebot zu dem Produkt manuell im Backend des Marktplatzes.
. Aktiviere an der entsprechenden Variante die Eigenschaft, die du für das Löschen des Produkts erstellt hast, und hinterlege den Wert *kill*.
. Aktiviere die Eigenschaft für die Katalogverknüpfung an der Variante.
. Warte bis zur nächsten Übertragung der Produkte. +
→  Diese findet über Nacht statt.
. Nachdem du das Produkt gelöscht hast, musst du 24-48h warten, bis du die gleiche Product-ID wieder verwenden darfst.
. Entferne nach der Wartezeit die Eigenschaft, die du für das Löschen des Produkts erstellt hast von der Variante.
. Aktiviere an der Variante die Marktplatzverfügbarkeit für den Marktplatz und Mirakl erneut.
// end::produktdaten-aktualisieren[]

// tag:box-angebotsfelder-voelkner[]
[IMPORTANT]
.Wie hängen die Angebotsfelder, das Produktexportfeld und die Marktplatz-SKU an der Variante zusammen?
====
Die Angebotsfelder *sku* und *product-id* werden grundsätzlich immer mit dem Wert gefüllt, der an der Variante im Feld *Marktplatz-SKU* für den Marktplatz definiert wurde.
Das Angebotsfeld *product-id-type* wird standardmäßig mit dem Wert *SHOP_SKU* übertragen, kann aber mit einem anderen Wert überschrieben werden, z.B. *SKU*. Wähle dazu an der Variante die Eigenschaft für Product ID Type *SKU* und ordne die Eigenschaft im Assistentenschritt *Zuordnung der Angebots-Eigenschaften* dem entsprechende Datenfeld zu.
Das Produktexportfeld *Die eindeutige Nummer (ID) des Artikels im System des Sellers* wird je nach Zuordnung im Katalog gefüllt.
Bei der ersten Übertragung, die über Nacht stattfindet, wird die Marktplatz-SKU an der Variante in plentymarkets automatisch aus der Varianten-ID gebildet. Die Marktplatz-SKU kann alternativ per Import oder manuell definiert werden.
====
*_Tipp:_* Ordne im Katalog dem Datenfeld *Die eindeutige Nummer (ID) des Artikels im System des Sellers* die Marktplatz-SKU zu. Wähle als Ausweich-Datenfeld die *Varianten-ID*.
// end:box-angebotsfelder-voelkner[]

// tag::ean-abgleich[]
=== EAN abgleichen

Voelkner bietet einen EAN-Matching Service an. Bitte dein:e Ansprechpartner:in vom Marktplatz, eine Liste deiner EANs zur Verfügung zu stellen. Falls deine EANs bereits auf Voelkner gelistet werden, bekommst du anschließend eine Tabelle mit den EANs und den dazugehörigen SKUs.
Für diese Varianten ist es nicht notwendig die Produktdaten zu übertragen. Über die zur Verfügung gestellten SKUs kannst du direkt ein Angebot erstellen. Die SKU muss als Marktplatz-SKU an der Variante importiert werden und als *product-id-type* muss an der Variante *SKU* gewählt werden.
// end::ean-abgleich[]

// tag::weitere-datenfelder-angebotsuebertragung[]
[discrete]
=== Weitere Datenfelder, die bei der Angebotsübertragung übermittelt werden

* *sku* und *product-id*: Diese Felder werden automatisch mit dem Wert befüllt, der als Marktplatz-SKU an der Variante hinterlegt wurde.
* *product-id-type*: Dieses Feld wird standardmäßig mit dem Wert *SHOP_SKU* befüllt. Im Assistentenschritt *Zuordnung der Angebots- Eigenschaften* kannst du eine Eigenschaft zuordnen, um pro Variante einen der folgenden Werte zu übertragen: *ISBN*, *SKU* oder *EAN*. Dieses Feature wird weiter unten tiefer erklärt.
* *price*: Dieses Feld wird automatisch mit dem Wert befüllt, der an der Variante für den am Marktplatz aktivierten Preis definiert wurde. Wurden mehrere Verkaufspreise an der Variante definiert, die ebenfalls für den Marktplatz freigegeben sind, wird der Preis mit der niedrigsten ID exportiert.
* *quantity*: Dieses Feld wird automatisch befüllt mit dem Nettobestand oder den summierten Nettobeständen aus den Lagern, die im Assistent *{marketplace}* im Schritt *Lagerauswahl* gewählt wurden.
* *min-quantity-alert*: Dieses Feld wird automatisch mit dem Wert *1* übertragen.
* *state*: Dieses Feld wird automatisch mit dem Wert *11* übertragen.
* *available-start-date*: Dieses Feld wird automatisch mit einem Zeitstempel übertragen.
* *discount-ranges*: In diesem Feld werden ein oder mehrere Staffelpreise übertragen.
// Link zu Verkaufspreise-Kapitel einfügen
* *allow-quote-requests*: Dieses Feld wird automatisch mit dem Wert *false* übertragen.
// end::weitere-datenfelder-angebotsuebertragung[]
