= Rechtssicher arbeiten mit POS
:lang: de
include::{includedir}/_header.adoc[]
:author: none
:keywords: plentymarkets POS, Kasse, POS, plentymarkets Kasse, Rechtssicherheit, GoBD, Finanzexport, Finanzexport Kasse
:position: 30
:url: pos/pos-rechtssicherheit
:id: PRVBBTM



[#280]
== Besonderheiten in Österreich

Österreichische Kassen sind mit einer Signatureinheit ausgestattet. Daraus ergeben sich einige Besonderheiten, die im Folgenden näher beschrieben werden.

[#260]
=== Monatsbeleg erstellen (Österreich)

Monatsbelege sind signierte Kontrollbelege mit einem Betrag von Null (0,00) Euro. Laut RKSV muss am Ende jedes Monats ein Monatsbeleg erstellt werden. Der Monatsbeleg für den Monat Dezember dient gleichzeitig als Jahresbeleg.

[.instruction]
Monatsbeleg erstellen (Österreich):

. Melde dich bei der plentymarkets App an.
. Tippe in der Menüleiste auf das **Menüsymbol**.
. Tippe auf **POS**. +
→ Das POS-Menü wird angezeigt.
. Tippe auf **Monatsbeleg (AT)**. +
→ Der Monatsbeleg wird gedruckt. +
→ Der Monatsbeleg wird in plentymarkets importiert und im Menü **Aufträge » Dokumentenarchiv** gespeichert.

=== Bei Ausfall der Signatureinheit kassieren (Österreich)

Der Gesetzgeber gibt vor, wie du vorgehen sollst, falls die Signatureinheit der Registrierkasse ausfällt.

* Notiere den Zeitpunkt des Ausfalls.
* Weiche wenn möglich auf eine Registrierkasse mit funktionierender Signatureinheit aus.
* Wenn keine andere Kasse verfügbar ist, kannst du trotz ausgefallener Signatureinheit weiter kassieren. Alle Belege werden dann mit dem Hinweis *Sicherheitseinrichtung ausgefallen* versehen.
* Sobald die Signatureinheit wieder funktioniert, wird in plentymarkets POS automatisch ein Sammelbeleg erstellt und gedruckt.

Diese Schritte sind Empfehlungen zum Einhalten der RKSV. Erkundige dich außerdem bei deiner Vorgesetzten, wie du bei einem Ausfall genau vorgehen sollst.

[#270]
=== Kontrollbeleg auf Verlangen der Finanzpolizei erstellen (Österreich)

Bei einer Kassenrückschau durch die Finanzpolizei muss auf Verlangen ein Kontrollbeleg mit dem Betrag Null erstellt werden. Dieser Kontrollbeleg ermöglicht der prüfenden Person, die Gültigkeit der Signatur mit einer Prüf-App direkt vor Ort in deinem Laden zu prüfen. Du benötigst keine zusätzlichen Berechtigungen, um den Kontrollbeleg zu erstellen.

[.instruction]
Kontrollbeleg auf Verlangen erstellen:

. Melde dich bei der plentymarkets App an.
. Tippe in der Menüleiste auf das **Menüsymbol**.
. Tippe auf **POS**. +
→ Das POS-Menü wird angezeigt.
. Tippe auf **Kontrollbeleg**. +
→ Der Kontrollbeleg wird gedruckt. +
→ Der Kontrollbeleg wird in plentymarkets importiert und im Menü **Aufträge » Dokumentenarchiv** gespeichert. +
**__Hinweis:__** Die Finanzpolizei darf den Kontrollbeleg als Beweismittel einbehalten.

[#860]
== plentymarkets POS in Österreich nutzen

Laut Registrierkassensicherheitsverordnung (RKSV) müssen Registrierkassen in Österreich mit einer technischen Sicherheitseinrichtung ausgestattet sein, die dafür sorgt, dass die über die Kasse abgewickelten Kassenvorgänge manipulationssicher, also nicht mehr veränderbar sind. Sichtbares Zeichen für diesen Manipulationsschutz ist der QR-Code auf dem Kassenbeleg. Hier erfährst du, wie du Kassen in Betrieb nimmst und nutzt, die in Österreich betrieben werden sollen.

[#870]
=== Übersicht: Inbetriebnahme der Kasse

Für Kassen mit Standort Österreich sind die in <<tabelle-inbetriebnahme-kasse-österreich>> erläuterten Schritte notwendig, um die von der RKSV vorgeschriebene Sicherheitseinrichtung in Betrieb zu nehmen. Detaillierte Informationen zu diesen rechtlichen Anforderungen findest du auf der Website des österreichischen link:https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/Sicherheitseinrichtung_in_Registrierkassen.html[Bundesministeriums für Finanzen^]. Auf dieser Handbuchseite werden nur die Schritte beschrieben, die erforderlich sind, um eine plentymarkets POS Kasse mit Standort Österreich in Betrieb zu nehmen. Die Beschreibung ersetzt keine rechtliche und steuerrechtliche Beratung.

[[tabelle-inbetriebnahme-kasse-österreich]]
.Kasse in Österreich in Betrieb nehmen
[cols="1,2,3"]
|====
|Reihen- folge |Schritt |Erläuterung

|1.
|Signaturkarte und Signaturkartenleser beschaffen
a|* plentymarkets POS ist für den Einsatz mit dem Feitian Smartcard-Leser link:http://www.cryptoshop.com/feitian-br301-bluetooth-reader.html[bR301^] optimiert.
* plentymarkets testet mit den Signaturkarten des Vertrauensdiensteanbieters link:https://www.prime-sign.com/[PrimeSign^].

|2.
|Manipulationssichere Registrierkasse initialisieren
|Siehe <<pos/pos-einrichten#50, Grundeinstellungen der Kasse vornehmen>>

|3.
|Startbeleg erstellen
|Siehe <<pos/pos-einrichten#900, Startbeleg erstellen>>

|4.
|Signaturkarte und Registrierkasse bei FinanzOnline registrieren
a|Nachdem der Startbeleg erstellt wurde, registrierst du Signaturkarte und Registrierkasse bei FinanzOnline. Für die Registrierung benötigst du die folgenden Daten: +

Signaturkarte (Unterlagen der Signaturkarte): +

* Die Seriennummer des Signaturzertifikats
* Den Namen des Vertrauensdiensteanbieters, bei dem das Zertifikat erworben wurde
* Die PIN des Signaturzertifikats

Registrierkasse (**Einstellungen » Mandant » Standard » POS » Kasse öffnen » Tab: Grundeinstellungen**): +

* Die Kassenidentifikationsnummer der plentymarkets POS Kasse. Die **Kassenidentifikationsnummer** findest du im Menü **Einstellungen » Mandant » Standard » POS » Kasse öffnen » Tab: Grundeinstellungen**.
* Den **Benutzerschlüssel AES-256**, der im Menü **Einstellungen » Mandant » Standard » POS » Kasse öffnen » Tab: Grundeinstellungen** angezeigt wird.

|5.
|Startbeleg mit der BMF-Belegcheck-App scannen
|Scanne den QR-Code auf dem Startbeleg der Kasse, nachdem du die Registrierung bei FinanzOnline abgeschlossen hast. Die App prüft dabei die Gültigkeit der Signatur auf den Belegen der Registrierkasse. +
**__Tipp:__** Zwischen dem Zeitpunkt der Registrierung von Signaturkarte und Registrierkasse über FinanzOnline und der Prüfung des Startbelegs darf nicht mehr als eine Woche liegen.
|====

[IMPORTANT]
.Existierende Kassen mit Standort Österreich
====
Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Wenn du bereits eine plentymarkets POS Kasse in Österreich betreibst, erstellst du eine neue Kasse und nimmst die alte Kasse außer Betrieb.
====

[#900]
=== Startbeleg erstellen (Standort Österreich)

Erstelle nun den Startbeleg, um die Kasse in Betrieb zu nehmen. Du benötigst die PIN für das Signaturzertifikat des Vertrauensdiensteanbieters, um den Startbeleg zu erstellen. Den Startbeleg erstellst du im POS-Menü der plentymarkets App. Nachdem der Startbeleg erstellt wurde, kann das Standortland der Kasse nicht mehr geändert werden.

[.instruction]
Startbeleg erstellen:

. Öffne die plentymarkets App.
. Öffne das Menü **plentymarkets App » Einstellungen » POS**.
. Gib die PIN für das Signaturzertifikat des Vertrauensdiensteanbieters ein.
. Tippe auf **Startbeleg erstellen**. +
→ Der Startbeleg wird gedruckt. +
→ Der Startbeleg wird im Kassenjournal und im Dokumentenarchiv gespeichert. +
→ Die Kasse kann in Betrieb genommen werden. +
→ Belege werden signiert und der QR-Code auf Belegen ausgegeben. +
→ Kassenvorgänge werden DEP-konform im System gespeichert.

[#880]
=== Kassenvorgänge in Österreich belegen

Laut der österreichischen Registrierkassensicherheitsverordnung (RKSV) müssen Belege signiert und mit einem QR-Code versehen werden. Dieser QR-Code enthält die wesentlichen Beleginhalte, einen verschlüsselten Umsatzzähler und einen Verweis auf den letzten Beleg. Dieser Verweis sorgt dafür, dass die vorhergehenden Belege nicht mehr verändert oder gelöscht werden können. Außerdem muss für jede Registrierkasse ein Datenerfassungsprotokoll geführt werden, das jederzeit lokal exportiert werden kann.

Damit du diesen gesetzlichen Anforderungen nachkommen kannst, stellt plentymarkets verschiedene Exportfunktionen bereit. Bespreche mit deinem Steuerbüro, welche Daten du exportieren und archivieren solltest, um rechtssicher zu arbeiten.

[#890]
==== DEP-Export erstellen

Laut §7 der österreichischen Registrierkassensicherheitsverordnung (RKSV) muss jede Registrierkasse über ein Datenerfassungsprotokoll (DEP) verfügen. Im DEP sind mindestens die Signierung von Belegen im Zusammenhang mit Barumsätzen und die Stornierung von Barumsätzen zu speichern. Die Unveränderlichkeitkeit der Daten ergibt sich dabei aus der Signaturverkettung. Pro DEP darf nur eine Kasse abgebildet werden.

Der DEP-Export wird als JSON-Datei bereitgestellt und enthält die folgenden Belegdaten:

* Belege-Gruppe
* Signaturzertifikat
* Zertifizierungsstellen
* Belege-kompakt

Das DEP einer Registrierkasse muss dabei auf Verlangen jederzeit auf einen externen Datenträger im vorgesehenen Exportformat exportiert werden können. Gehe wie unten beschrieben vor, um einen DEP-Export zu erstellen:

[.instruction]
DEP-Dateien exportieren:

. Öffne das Menü **Aufträge » POS » DEP-Export**.
. Wähle den Mandanten (Shop), für den du Daten exportieren möchtst.
. Wähle die Kasse, für die du Daten exportieren möchtst.
. Wähle das Datum, ab dem du Daten exportieren möchtst.
. Wähle das Datum, bis zu dem du Daten exportieren möchtst.
. Klicke auf *Herunterladen*. +
→ Die Datei wird im Standard-Download-Ordner des Browsers gespeichert. +
*_Tipp:_* Der Dateiname enthält den Exportzeitraum, zum Beispiel depExport_9-1-2017-9-2-2017.json für Daten von 9.1. bis 9.2.2017.

[#4200]
==== Monatsbeleg erstellen (Österreich)

Monatsbelege sind signierte Kontrollbelege mit einem Betrag von Null (0,00) Euro. Laut RKSV muss am Ende jedes Monats ein Monatsbeleg erstellt werden. Der Monatsbeleg für den Monat Dezember dient gleichzeitig als Jahresbeleg. Diesen Jahresbeleg musst du jedes Jahr zusätzlich ausdrucken, aufbewahren und den Barcode mit der BMF Belegcheck-App prüfen.

[#4300]
===== Berechtigungen für Monatsbelege erteilen

Kassenpersonal mit Admin-Rechten hat standardmäßig die Berechtigung, Monatsbelege zu erstellen. Kassenpersonal mit der Benutzerklasse *Backend* muss diese Berechtigung erteilt werden.

[.instruction]
Benutzern Berechtigungen für Monatsbelege erteilen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer*.
. Öffne das Konto des Benutzers.
. Öffne das Tab *Mobile*.
. Aktiviere im Bereich *POS-Funktionen* die Berechtigung *Monatsbeleg (AT)*.
. *Speichere* die Einstellungen. +
→ Die Kassenbenutzerin ist berechtigt, <<pos/pos-kassenbenutzer#270, Monatsbelege in plentymarkets POS>> zu erstellen.

[#4400]
=== SOS: Die Signatureinheit ist ausgefallen - was jetzt?

Die RKSV gibt vor, wie du vorgehen musst, falls die Signatureinheit der Registrierkasse ausfällt:

* Wenn die Signatureinheit ausfällt, musst du Geschäftsfälle auf einer anderen Registrierkasse mit funktionierender Signatureinheit erfassen.
* Wenn keine andere Registrierkasse verfügbar ist, kann die Registrierkasse temporär ohne Signatureinheit betrieben werden.
* Dauert der Ausfall der Signatureinheit länger als 48 Stunden, musst du Beginn und Ende des Ausfalls innerhalb einer Woche über FinanzOnline dem Finanzamt melden.
* Sämtliche nicht signierte Belege müssen mit dem Hinweis *Sicherheitseinrichtung ausgefallen* versehen werden. +
→ In plentymarkets POS werden Belege automatisch mit diesem Hinweis versehen, wenn die Signatureinheit ausfällt.
* Sobald die Signatureinheit wieder funktioniert, muss ein signierter Sammelbeleg erstellt werden, der sämtliche Geschäftsvorfälle enthält, die im Ausfallzeitraum über die Registrierkasse abgewickelt wurden. +
→ plentymarkets POS erstellt automatisch einen signierten Sammelbeleg, wenn die Signatureinheit wieder in Betrieb genommen wird.

[#930]
=== Kontrollbeleg auf Verlangen der Finanzpolizei erstellen

Bei einer Kassenrückschau durch die Finanzpolizei muss auf Verlangen ein Kontrollbeleg mit dem Betrag Null erstellt werden. Mit diesem Kontrollbeleg kann die prüfende Person die Gültigkeit der Signatur mit einer Prüf-App direkt vor Ort in deinem Laden prüfen. Jede Kassenkraft kann einen solchen <<pos/pos-kassenbenutzer#270, Kontrollbeleg auf Verlangen>> erstellen. Zum Erstellen des Kontrollbelegs sind keine zusätzlichen Berechtigungen erforderlich.

[#920]
=== Kasse außer Betrieb nehmen (Standort Österreich)

Um eine Kasse mit Standort Österreich dauerhaft außer Betrieb zu nehmen, erstellst du einen Endbeleg. Ein Endbeleg ist ein signierter Kontrollbelege mit einem Betrag von Null (0,00) Euro, der nur erstellt werden kann, wenn für die Kasse auch ein Startbeleg erstellt wurde. Den Endbeleg erstellst du im POS-Menü der plentymarkets App. Nachdem ein Endbeleg für die Kasse erstellt wurde, kann die Kasse nicht mehr verwendet werden.

[.instruction]
Endbeleg erstellen:

. Öffne die plentymarkets App.
. Öffne das Menü **plentymarkets App » Einstellungen » POS**.
. Tippe auf **Endbeleg erstellen**. +
→ Der Endbeleg wird gedruckt. +
→ Der Endbeleg wird im Kassenjournal und im Dokumentenarchiv gespeichert. +
→ Die Kasse kann nicht mehr verwendet werden.
. Melde dem Finanzamt, dass die Kasse außer Betrieb genommen wurde.


