= Best Practices: POS
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, Kasse, POS, Gutscheine, Gutscheine verkaufen, Best Practice
:position: 30

Hier findest du Best Practices rund um das Thema plentymarkets POS.

[#10]
== Gutscheine an der Kasse

Da es bezogen auf den Umgang mit Verkaufsgutscheinen viele Möglichkeiten bei plentymarkets gibt, möchten wir dir hier eine praxisnahe und einfache Variante für den POS-Bereich vorstellen.

=== Ziel

Schneller Verkauf von Gutscheinkarten in variabler Höhe an der Kasse.

=== Vorbereitung

. Sofern noch nicht vorhanden, musst du eine <<pos/pos-einrichten#_gutscheinverkauf_vorbereiten, passende Kampagne>> in plentymarkets erstellen.
. Lege dir einen <<pos/pos-einrichten#_gutscheinartikel_mit_flexiblem_wert_erstellen, Gutscheinartikel mit flexiblem Wert>> für diese Art von Gutscheinen in plentymarkets an.
. Füge diesen Gutscheinartikel dem <<pos/pos-einrichten#70, Favoritenbereich>> deiner Kasse hinzu.
. Beschaffe dir link:http://lmgtfy.com/?q=Barcode-Karten+Druck[Barcode-Karten^] mit vorgefertigten Codes. Die meisten Anbieter erwarten eine CSV-Datei, die die einzelnen Codes enthält, die auf den Karten platziert werden sollen, sowie eine Layout-Vorlage im Photoshop- oder Adobe-Illustrator-Format für das Rahmendesign. +
*_Tipp:_* Wenn du deinen Gutscheincodes das Präfix *#* voranstellst, beschleunigst du später den Einlösungsvorgang, weil plentyPOS dadurch direkt beim Scannen erkennt, dass es sich um einen Gutschein handelt und nicht erst manuell der Button für den Gutscheindialog betätigt werden muss.

=== Videos des Ablaufs

==== Gutschein verkaufen

video::pos/assets/verkauf_best_practice.mp4[width=640]


==== Gutschein einlösen

video::pos/assets/einloesung_best_practice.mp4[width=640]

[#100]
== Online-Bestellungen an der Kasse abschließen (Click & Collect)

Click & Collect bedeutet, dass Kundinnen und Kunden online Ware bestellen und im Laden abholen können. Der Auftrag wird in plentymarkets POS geladen und an der Kasse abgeschlossen. In der Kasse können die folgenden Fälle auftreten:

* Der Auftrag wurde online bestellt und bezahlt. Die Ware wird im Laden abgeholt.
* Der Auftrag wurde online bestellt. Die Ware wird im Laden bezahlt und abgeholt.

In diesem Best Practice erfahren Sie, welche Vorbereitungen Sie treffen müssen, um Online-Bestellungen an der Kasse abzuschließen.

=== Versandeinstellungen

Wenn Sie schon eine Kasse nutzen, haben Sie auch schon einen Versanddienstleister *Selbstabholung* und ein Versandprofil *Selbstabholung*. Wir empfehlen aber, für Click & Collect einen eigenen Versanddienstleister und ein eigenes Versandprofil zu erstellen.

[#190]
==== Versanddienstleister für Abholung in der Filiale erstellen

Gehen Sie wie unten beschrieben vor, um einen Versanddienstleister für die Abholung in der Filiale zu erstellen. In diesem Best Practice nennen wir diesen Versanddienstleister *Abholung in der Filiale*. Natürlich können Sie auch einen anderen Namen verwenden.

[.instruction]
Versanddienstleister für Abholung in der Filiale erstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister*.
. Klicken Sie auf *Neu*. +
→ Ganz unten wird eine neue Zeile hinzugefügt.
. Geben Sie in die Spalte *Namen (de)* den Namen *Abholung in der Filiale* ein.
. Geben Sie in die Spalte *Namen (Backend)* den Namen *Abholung in der Filiale* ein.
. Wählen Sie in der Spalte *Versanddienstleister* die Option *Selbstabholer* aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen.

[#200]
==== Versandprofil für Abholung in der Filiale erstellen

Erstellen Sie nun ein Versandprofil für die Abholung in der Filiale. In diesem Best Practice nennen wir dieses Versandprofil *Abholung in der Filiale*. Natürlich können Sie auch einen anderen Namen verwenden.

[.instruction]
Versandprofil für Abholung in der Filiale erstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Klicken Sie auf *Neu*.
. Wählen Sie den Versanddienstleister *Abholung in der Filiale* aus der Dropdown-Liste, den Sie gerade erstellt haben.
. Geben Sie für die Option *Namen (de)* den Namen *Abholung in der Filiale* ein.
. Geben Sie für die Option *Namen (Backend)* den Namen *Abholung in der Filiale* ein.
. Aktivieren Sie den *Mandanten (Shop)*, für den Sie die Abholung in der Filiale anbieten möchten.
. Aktivieren Sie die *Auftragsherkunft*. Wir empfehlen die Herkünfte *0 Manuelle Eingabe* und den *Mandanten (Shop)*.
. **Speichern** Sie die Einstellungen. +
→ Das Tab **Portotabelle** wird angezeigt. +
*_Hinweis:_* Die Abholung in der Filiale ist in der Regel versandkostenfrei. Daher werden in diesem Best Practice keine <<fulfillment/versand-vorbereiten#1000, Versandkosten gespeichert>>.
. *Speichern* Sie die Einstellungen des Tabs *Portotabelle* ohne Änderungen.


[#210]
==== Versandprofil für Abholung in der Filiale am Artikel aktivieren

Aktivieren Sie nun das Versandprofil *Abholung in der Filiale* bei den Artikeln, die Kunden online bestellen und im Laden abholen können sollen.

[.instruction]
Versandprofil für Abholung in der Filiale am Artikel aktivieren:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab *Global*.
. Aktivieren Sie das Versandprofil *Selbstabholung*.
. *Speichern* Sie die Einstellungen.

Sie möchten das Versandprofil für eine größere Anzahl an Artikeln gleichzeitig aktivieren? Dann nutzen Sie die <<artikel/artikel-verwalten#155, Artikel-Gruppenfunktion>>.

=== Zahlungsart für Zahlung im Laden aktivieren

Aktivieren Sie nun die Zahlungsart *Barzahlung*, damit Online-Aufträge auch im Laden bezahlt werden können.

* Stellen Sie das Plugin link:https://marketplace.plentymarkets.com/plugins/payment/PayUponPickup_4757[Barzahlung] für den Mandanten bereit. +
→ Standardmäßig wird im Webshop der Name der Zahlungsart, also "Barzahlung" angezeigt. Ändern Sie optional den Namen der Zahlungsart, zum Beispiel zu "Bezahlung in der Filiale".

=== Warenbewegungen festlegen (ab Version 1.9.2)

Nun legen Sie fest, wie der Warenbestand von online bestellten Artikeln behandelt werden soll, die im Ladengeschäft abgeholt werden.

[.instruction]
Warenbewegungen für Online-Aufträge festlegen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » POS*.
. Öffnen Sie die Kasse. +
→ Das Tab *Grundeinstellungen* wird geöffnet.
. Die Option *Externer Auftrag: Warenausgang automatisch buchen* ist vorausgewählt. Der Warenausgang wird also nach der Bezahlung immer automatisch gebucht. Deaktivieren Sie die Option, wenn der Warenausgang nur gebucht werden soll, wenn das Kassenpersonal auf den Button *Warenausgang buchen* tippt. +
*_Tipp:_* Deaktivieren Sie die Option nur, wenn Sie eine separate Warenausgabe haben, also die Waren nach der Bezahlung nicht direkt an der Kasse aushändigen. Schulen Sie außerdem das Kassenpersonal, in welchen Fällen der Button betätigt werden soll.
. Wenn die Ware aus dem Vertriebslager der Kasse ausgebucht werden soll, aktivieren Sie die Option *Warenausgang von externen Aufträgen: Ware aus POS-Vertriebslager buchen*. +
→ Wenn Sie die Option nicht aktivieren, wird die Ware aus dem Lager ausgebucht, das dem Auftrag bei der Erstellung zugewiesen wurde.
. *Speichern* Sie die Einstellungen.

////
== Warenwirtschaft

EAs für Warenausgang

* Bei Lieferung in die Filiale
* Bei Übergabe an den Kunden
* Wenn Laden = Lager

Ware wird ausgebucht: Ware wird aus dem Lager ausgebucht, das im Auftrag definiert wurde.

Auftrag sollte nicht in den Prozessen verarbeitet werden.

Nicht bearbeiten: Im Prozess nach Versandprofil filtern und Selbstabholer ausschließen, damit Warenausgang nicht gebucht wird.
////
