= POS einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, POS, Kasse, Kassensystem, Kassen, IDEA-Export, IDEA, GoBD, Kassenjournal, Kassenbuch, GoBD konform, Registrierkasse, RKSV, DEP-Export, mobile Kasse, mobile Registrierkasse, Smartphone-Kasse, Kasse Sicherheitseinrichtung, Vertrauensdiensteanbieter POS, Vertrauensdiensteanbieter Kasse, Registrierkassensicherheitsverordnung, Kasse Österreich, POS Österreich, rechtssichere Kasse, RKSV-konform, plentyPOS, RKSV, Startbeleg, QR-Code, mobile Kassa, Kassasoftware, Kassensoftware, Kassa-Software, Kassen-Software, Laufkundschaft, Laufkunden
:position: 10

Mit dem mobilen Kassensystem plentymarkets POS integrieren Sie den stationären Handel mühelos in plentymarkets. Das Kassensystem plentymarkets POS wird über die plentymarkets App bereitgestellt.

[IMPORTANT]
.POS-Einstellungen nicht im laufenden Betrieb ändern
====
Ändern Sie die POS-Einstellungen nicht im laufenden Betrieb. Wenn Sie dennoch Änderungen an den POS-Einstellungen vornehmen, fordern Sie das Kassenpersonal auf, sich aus der App ausloggen und wieder einloggen, da sonst vor allem bei einer Änderung der Rundungseinstellungen Unstimmigkeiten in den Gesamtbeträgen entstehen.
====

[#10]
== Unterstützte Hardware für plentymarkets POS

Das Kassensystem plentymarkets POS wird über die plentymarkets App bereitgestellt. Für den Einsatz von plentymarkets POS bestehen jedoch zusätzliche Hardware-Voraussetzungen. Informationen zu den Systemvoraussetzungen für die plentymarkets App und plentymarkets POS finden Sie auf der Handbuchseite <<schnelleinstieg/systemvoraussetzungen#50, Systemvoraussetzungen>>.

Die plentymarkets App laden Sie kostenlos über die folgenden Appstores herunter:

* link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=de[plentymarkets App bei Google Play^]

* link:https://itunes.apple.com/de/app/plentymarkets/id957702618[plentymarkets App bei iTunes^]

== Unterstützte Währungen

plentymarkets POS ist für das Kassieren mit den Währungen Euro (EUR), Schweizer Franken (CHF) und Britische Pfund (GBP) vorbereitet. Sie können die Kasse allerdings nur in der <<payment/waehrungen#30, Systemwährung>> betreiben. Die Systemwährung legen Sie im Menü *System » Systemeinstellungen » Aufträge » Zahlung » Währungen* fest.

[#20]
== plentymarkets POS Kasse buchen

Um plentymarkets POS verwenden zu können, buchen Sie zunächst im plentymarkets Konfigurator eine oder mehrere Kassen. Informationen zu den Konditionen finden Sie im Konfigurator oder auf der plentymarkets POS Produktseite.

[#30]
== Kasse einrichten

Nachdem Sie Kassen gebucht haben, richten Sie diese Kassen im plentymarkets Backend ein. Zunächst weisen Sie die Kassen einem Mandanten zu, indem Sie die Kasse im Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS** erstellen und weitere Einstellungen vornehmen. Gehen Sie dazu wie unten beschrieben vor.

[#40]
=== Kasse erstellen

Erstellen Sie zunächst im plentymarkets Backend eine Kasse für den gewünschten Mandanten (Shop).

[.instruction]
Kasse für Mandanten erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Klicken Sie auf **Neue Kasse**. +
→ Das Fenster **Neue Kasse** wird eingeblendet.
. Geben Sie einen Namen für die Kasse ein.
. **Speichern** Sie die Einstellungen. +
→ Der Kasse wird eine Herkunft zugeordnet. +
→ Die Kasse wird gespeichert und zur weiteren Bearbeitung geöffnet.

<<tabelle-POS-menueleiste>> beschreibt die Menüleiste der Kasse.

[[tabelle-POS-menueleiste]]
.Menüleiste der Kasse
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**ID**
|Eindeutige Kennung der Kasse. Diese ID wird automatisch und mandantenübergreifend vergeben und ist nicht änderbar.

|**Kopieren**
|Erstellt eine neue Kasse mit den Einstellungen der geöffneten Kasse. Dabei werden Name und Herkunft neu vergeben. +
**__Hinweis:__** Das Kopieren einer Kasse ist nur möglich, wenn eine ausreichende Anzahl an Kassen gebucht wurde.

|**Gerät**
|Zeigt die eindeutige ID des Geräts an, wenn die Kasse bereits mit einem Gerät gekoppelt ist.

|**Löschen**
|Löscht die Kasse aus dem System.
|====

[#50]
=== Grundeinstellungen der Kasse vornehmen

Nehmen Sie nun im Tab **Grundeinstellungen** der neu erstellten Kasse die weiteren Einstellungen vor und speichern Sie die Einstellungen. Beachten Sie <<tabelle-POS-grundeinstellungen>>.

[[tabelle-POS-grundeinstellungen]]
.Tab *Grundeinstellungen* der Kasse
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Name*
|Einen Namen für die Kasse eingeben.

|*Herkunft*
|Beim Buchen einer Kasse wird automatisch eine Herkunft für diese Kasse generiert, um Aufträge, die über diese Kasse ins System gelangen, eindeutig zu kennzeichnen. Der neuen Kasse wird automatisch eine verfügbare POS-Herkunft (103.01 bis 103.99) zugeordnet.

|*Standardkunde*
|Für Kassenaufträge <<pos/pos-einrichten#90, erstellten Standardkunden>> wählen, dem über diese Kasse generierte Aufträge zugeordnet werden sollen.

2+|*Artikelfilter*

|*Marktplatz-Verfügbarkeit berücksichtigen*
|Wählen, ob für die Kasse die Marktplatz-Verfügbarkeit berücksichtigt werden soll. Die Marktplatz-Verfügbarkeit wird im Tab **Verfügbarkeit**, Bereich **Märkte** der Variante aktiviert. +
Häkchen gesetzt = In der Kasse sind nur Varianten verfügbar, für die im Tab **Verfügbarkeit**, Bereich **Märkte** die Herkunft der Kasse aktiviert ist. +
Häkchen nicht gesetzt = Auch nicht für die Herkunft der Kasse aktivierte Varianten sind in der Kasse verfügbar und können aufgerufen und verkauft werden.

|*Nur aktive Varianten berücksichtigen*
|Wählen, ob für die Kasse nur aktive Varianten berücksichtigt werden sollen. Varianten werden im Tab **Einstellungen** der Variante aktiviert. +
Häkchen gesetzt = In der Kasse sind nur Varianten verfügbar, für die im Tab **Einstellungen** der Variante die Option <<artikel/artikel-verwalten#230, Aktiv>> aktiviert ist. +
Häkchen nicht gesetzt = Aktive und inaktive Varianten sind in der Kasse verfügbar und können aufgerufen und verkauft werden.

2+|*Standort*

|*Name 1-4*; +
*Adresse 1-4*; +
*Postleitzahl*; +
*Ort*; +
*Land*
|Firmennamen und Adresse des Ladengeschäfts eingeben, an dem die Kasse betrieben wird. +
*_Hinweis:_* In Deutschland und anderen Ländern ist die Adresse eine Pflichtangabe, um ein rechtssicheres Arbeiten mit der Kasse zu ermöglichen. Genaue Standortangaben mit Steuerberaterin klären. +
*_Standort Österreich:_* Nachdem der Startbeleg für die Kasse erstellt wurde, kann das Land des Kassenstandorts nicht mehr geändert werden.

2+|*Vertriebslager*

|*Vertriebslager*
|Wählen, für welches Vertriebslager die über diese Kasse genierten Aufträge gebucht werden sollen. +
*_Hinweis:_* Artikel ohne Netto-Warenbestand werden im POS-Warenkorb rot markiert, können aber verkauft werden. Deshalb kann es zu rechnerischen Überverkäufen kommen.

2+|*Retoure*

|*Standard-Reparaturlager*
|Wählen, welches Lager bei Retouren als Standardreparaturlager vorgeschlagen wird.

|*Standard-Regal*
|Wählen, welches Regal bei Retouren vorgeschlagen wird.

|*Standard-Reparaturlagerort*
|Wählen, welcher Lagerort bei Retouren als Standard-Reparaturlagerort vorgeschlagen wird. +
*_Tipp:_* Zweimal die Pfeiltaste drücken, um eine Liste der Lagerorte anzuzeigen.

|*Retourenbetrag als Gutschein auszahlen* +
|Wählen, ob Kassenpersonal einen Gutschein in Höhe des Retourenbetrags aushändigen darf, statt den Betrag bar auszuzahlen.

|*Varianten-ID des Retourenartikels* +
|ID der Variante eingeben, die als Gutscheinartikel für Retouren dient.

2+|*Warenbewegung*

|*Warenbestand bei Stornierung zurückbuchen*
|Aktivieren, um den Warenbestand automatisch zurückzubuchen, wenn ein Auftrag storniert wird.

|*Externer Auftrag: Warenausgang automatisch buchen* +
(ab App-Version 1.9.2)
|Wählen, ob für externe Aufträge, die an der Kasse bezahlt werden, der Warenausgang automatisch gebucht werden soll. +
Aktiviert (Standardeinstellung) = Der Warenausgang wird automatisch gebucht. Die Schaltfläche *Warenausgang buchen* wird Kassenkräften nicht angezeigt. +
Nicht aktiviert = Der Warenausgang wird nur gebucht, wenn das Kassenpersonal auf *Warenausgang buchen* tippt. +
*_Tipp:_* Option deaktivieren, wenn die Ware nicht direkt an der Kasse ausgegeben wird.

|*Warenausgang von externen Aufträgen: Ware aus POS-Vertriebslager buchen* +
(ab App-Version 1.9.2)
|Wählen, aus welchem Lager die Auftragspositionen ausgebucht werden, wenn externe Aufträge an der Kasse abgeschlossen werden. +
Nicht aktiviert (Standardeinstellung) = Die Auftragspositionen werden aus dem Lager gebucht, das dem Auftrag bei der Erstellung zugeordnet wurde. +
Aktiviert = Die Auftragspositionen werden aus dem für die Kasse eingestellten *Vertriebslager* gebucht. Das Lager, das am Auftrag gespeichert ist, wird überschrieben.

2+|*Bedienung*

|*Preisabfrage wenn Artikelpreis 0,00*
|Aktivieren, um die manuelle Preiseingabe zu öffnen, wenn beim Kassieren ein 0-Euro-Artikel gewählt wird.

|*Favoriten mit Menge 1 hinzufügen*
|Aktivieren, um beim Kassieren Favoriten automatisch mit der Menge 1 in den POS-Warenkorb zu legen. Artikel mehrmals in den Warenkorb legen, um die Anzahl zu erhöhen. +
*_Tipp:_* Bei Favoriten, die über die Artikelsuche hinzugefügt werden, wird die Menge weiterhin manuell eingegeben.

|*Numpad (Tablet-Ansicht): Buttons für schnelle Mengeneingabe und passende Zahlung einblenden*
a|Aktivieren, um die Komfortfunktionen auf dem Ziffernblock der Kasse einzublenden. +
Nicht aktiviert = Die Komfortfunktionen werden nicht eingeblendet. +
Aktiviert = Die folgenden Komfortfunktionen werden als zusätzliche Reihe im Ziffernblock der Kasse eingeblendet:

* *Mal* = Kassenbenutzerinnen können die Menge eingeben, bevor sie einen Artikel scannen oder einen Favoritenartikel wählen. Wenn vor dem Scannen keine Menge eingegeben wird, wird der gescannte Artikel mit der Menge 1 in den POS-Warenkorb gelegt.
* *Passend* = Bei passender Barzahlung kann das Kassenpersonal auf diese Schaltfläche tippen, statt den erhaltenen Betrag einzugeben. Das Feld *Erhalten* wird mit dem zu zahlenden Betrag aufgefüllt.

|*Retoure mit Hauptauftrag: Zu retournierende Auftragspositionen manuell wählen*
|Wählen, ob bei Retouren mit Hauptauftrag die Auftragspositionen beim Öffnen des Auftrags vorausgewählt sind. +
Nicht aktiviert = Standardeinstellung. Beim Öffnen des Hauptauftrags sind alle Auftragspositionen für die Retoure vorausgewählt. Das Kassenpersonal entfernt die Artikel, die nicht zurückgegeben werden. +
Aktiviert = Beim Öffnen des Hauptauftrags sind keine Auftragspositionen für die Retoure vorausgewählt. Das Kassenpersonal fügt die Artikel zur Retoure hinzu, die zurückgegeben werden. +
*_Tipp:_* Einstellung für Kassen ohne Scanner aktivieren, über die Aufträge mit vielen Auftragspositionen abgewickelt werden.

2+|*Kundenkarte*

|*Kundenidentifikation* +
(ab App-Version 1.9.2)
|Wählen, welche Kontaktdaten durchsucht werden, wenn ein Barcode mit einem Pluszeichen (+) als Präfix gescannt wird. +
*Kontakt-ID* (Standardeinstellung) = Wählen, wenn Barcodes die Kontakt-ID enthalten. +
*Kundennummer* (empfohlen) = Wählen, wenn Barcodes die Kundennummer enthalten. +
*_Tipp:_* Bei der Einstellung *Kundennummer* können vorab Kundenkarten mit Barcodes gedruckt werden. Der Barcode-Code wird dann ohne das Pluszeichen in dem Feld *Kundennummer* des Kontakts gespeichert.

2+|*Österreich*

|*AES-Schlüssel* +
(nur neue Kassen mit Standort Österreich)
|AES-Schlüssel eingeben, mit dem der Umsatzzähler der Kasse verschlüsselt werden soll. Der AES-Schlüssel ist frei wählbar. Nachdem der Startbeleg für die Kasse erstellt wurde, kann der AES-Schlüssel nicht mehr geändert werden. +
*_Tipp:_* Auf **Schlüssel generieren** klicken, um einen zufälligen Schlüssel zu generieren. +
*_Hinweis:_* Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Neue Kasse erstellen und alte Kasse außer Betrieb nehmen, um Sicherheitseinrichtung einzurichten.

|**Zertifizierer** +
(nur neue Kassen mit Standort Österreich)
|Den Namen des Vertrauensdiensteanbieters eingeben, bei dem das Zertifikat gekauft wurde. +
**__Hinweis:__** Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Neue Kasse erstellen und alte Kasse außer Betrieb nehmen, um Sicherheitseinrichtung in Betrieb zu nehmen.

|**Zertifizierungsnummer** +
(nur neue Kassen mit Standort Österreich)
|Die Seriennummer des Signaturzertifikats eingeben, siehe Unterlagen des Vertrauensdiensteanbieters. +
*_Hinweis:_* Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Neue Kasse erstellen und alte Kasse außer Betrieb nehmen, um Sicherheitseinrichtung in Betrieb zu nehmen.
|====

[#60]
=== Favoriten verwalten

Sie haben die Möglichkeit, Varianten zur Favoritenliste hinzuzufügen. Dadurch kann das Kassenpersonal häufig verkaufte Varianten schneller aufrufen und zum POS-Warenkorb hinzufügen.

[#70]
==== Varianten als Favoriten speichern

Gehen Sie wie unten beschrieben vor, um Varianten als Favoriten zu speichern.

[.instruction]
Varianten als Favoriten speichern:

. Öffnen Sie das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffnen Sie die Kasse.
. Wechseln Sie in das Tab **Favoriten**.
. Öffnen Sie das Tab **Variante hinzufügen**. +
→ Eine Liste der Varianten wird angezeigt.
. *_Optional:_* Nutzen Sie die Filter, um die Anzeige einzuschränken.
. Klicken Sie auf **Varianten hinzufügen**. +
→ Die Varianten werden zur Liste der Favoriten hinzugefügt und im Tab **Favoriten** angezeigt. +
→ Beim nächsten Synchronisieren mit plentymarkets POS werden die Favoriten an die Kasse übertragen.

[TIP]
.Favoriten des Kassenpersonals haben Priorität
====
Kassenpersonal kann eigene Favoriten in plentymarkets POS speichern. Die Favoriten des Kassenpersonals haben dabei Priorität gegenüber den im plentymarkets Backend gespeicherten Favoriten.
====

[#80]
==== Reihenfolge der Favoriten ändern

Die Priorität der Favoriten legen Sie über die Pfeilsymbole des Tabs **Favoriten** fest. Die am häufigsten verkaufte Variante sollte ganz oben in der Liste stehen. Die erste Variante der Liste des Menü wird dem Kassenpersonal auch als erste Variante der Favoritenliste vorgeschlagen. Gehen Sie wie unten beschrieben vor, um die Reihenfolge der Favoriten festzulegen.

[.instruction]
Reihenfolge der Favoriten ändern:

. Öffnen Sie das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffnen Sie die Kasse.
. Öffnen Sie das Tab **Favoriten**. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicken Sie in der Spalte **Aktionen** auf den Pfeil der Variante, deren Position Sie ändern möchten. +
→ Mit dem Pfeil nach oben erhöhen Sie die Priorität der Variante. +
→ Mit dem Pfeil nach unten verringern Sie die Priorität der Variante.

[#90]
==== Favoritenliste auf andere Kassen übertragen

Die Favoritenliste einer Kasse kann auf andere Kassen des Mandanten übertragen werden. Dabei werden in der Zielkasse vorhandene Favoriten nicht gelöscht. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Favoriten auf andere Kassen übertragen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffnen Sie die Kasse.
. Öffnen Sie das Tab **Favoriten**. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicken Sie auf **Favoriten übertragen**. +
→ Das Fenster **Favoriten übertragen** wird angezeigt.
. Setzen Sie Häkchen bei den Kassen, zu denen Sie die Favoriten dieser Kasse kopieren möchten.
. Klicken Sie auf **Speichern**. +
→ Die Favoriten werden auf die gewählten Kassen übertragen.

[#110]
==== Varianten aus Liste der Favoriten löschen

Gehen Sie wie unten beschrieben vor, um Varianten aus der Liste der Favoriten zu löschen. Aus der Liste gelöschte Varianten werden beim nächsten Synchronisieren mit der POS-App aus der Favoritenliste der Kasse entfernt.

[.instruction]
Varianten aus Liste der Favoriten löschen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffnen Sie die Kasse.
. Öffnen Sie das Tab **Favoriten**. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicken Sie in der Spalte der Variante auf **Löschen**. +
→ Die Variante wird aus der Liste der Favoriten entfernt.

[#120]
=== Belegvorlage bearbeiten

Im Tab **Beleg** der Kasseneinstellungen bestimmen Sie die Daten, die auf Belegen ausgegeben werden sollen. Laden Sie optional ein Bild hoch und legen Sie Kopf- und Fußzeile für Belege fest. Standardmäßig ist die Kopfzeile mit den im Menü **System » Systemeinstellungen » Einstellungen » Stammdaten** gespeicherten Daten befüllt. Diese Daten können Sie pro Kasse anpassen. Die Fußzeile gestalten Sie individuell, um zum Beispiel auf Aktionsangebote oder Ihren Onlineshop hinzuweisen.

[.instruction]
Belegvorlage bearbeiten:

. Öffnen Sie das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffnen Sie die Kasse.
. Wechseln Sie in das Tab **Beleg**.
. Setzen Sie Häkchen bei den Komponenten, die auf Belegen der Kasse angezeigt werden sollen.
. Nehmen Sie die Einstellungen vor. Beachten Sie <<tabelle-POS-belegvorlage>>.
. **Speichern** Sie die Einstellungen. +
→ Die Belegvorlage wird erstellt.

[[tabelle-POS-belegvorlage]]
.Belegvorlage bearbeiten
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Belegeinstellungen

|**Gutscheinbeleg drucken und speichern**
a|Wählen, ob ein Gutscheinbeleg gedruckt und im Dokumentenarchiv gespeichert werden soll. +

Nicht aktiviert (Standard) = Kein Gutscheinbeleg wird erstellt. +
Aktiviert = Beim Verkauf oder einer Teileinlösung eines Gutscheins wird ein Gutscheinbeleg erstellt. +
→ Der Gutscheinbeleg wird erstellt und im Dokumentenarchiv gespeichert. +
→ Wenn die Option *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* aktiviert ist, wird der Gutscheinbeleg nach dem Kassenbeleg ausgedruckt. +
→ Wenn *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* nicht aktiviert ist, kann die Kassenbenutzerin den Gutscheinbeleg nach Abschluss des Auftrags manuell drucken. +
Der Gutscheinbeleg enthält die folgenden Informationen zum Gutschein:

* Gutscheinwert
* Gutschein-Code
* Bei Teileinlösung: eingelöster Betrag und Restbetrag

*_Hinweis:_* Beim Verkauf eines Gutscheins wird der Gutschein-Code unabhängig von der gewählten Einstellung immer auf dem normalen Kassenbeleg ausgegeben.

2+|Beleginhalte

|**Bild**
|Option aktivieren und PNG-Datei wählen, die auf Belegen der Kasse ausgeben werden soll. Datei muss vorher im Menü **CMS » Bilder-Galerie** hochgeladen werden.

|**Kopfzeile**
|Wenn die Komponente gewählt wurde, wird Inhalt des Felds als Kopfzeile aller Belege der Kasse ausgegeben. Standardmäßig ist die Kopfzeile mit den im Menü **System » Systemeinstellungen » Einstellungen » Stammdaten** gespeicherten Daten befüllt. Daten bei Bedarf anpassen.

|**Fußzeile**
|Option aktivieren und zusätzlichen Text eingeben.

|**Identische Auftragspositionen**
|Wählen, wie mehrere identische Varianten auf dem Beleg dargestellt werden sollen. +
**Einzeln darstellen** = Unabhängig von der gekauften Stückzahl wird jede gekaufte Variante einzeln aufgeführt. Beispiel: +
---------------------------------------------------- +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
---------------------------------------------------- +
**Zusammenfassen** = Identische Varianten werden zusammengefasst. Beispiel: +
---------------------------------------------------- +
Katzenfutter CaTasty Deluxe          20,97 EUR A +
3 x 6,99 EUR A +
---------------------------------------------------- +
|====

[#130]
== Benutzerkonten für POS verwalten

Um Kassenpersonal den Zugriff auf plentymarkets POS zu ermöglichen, sind die folgenden Vorbereitungen nötig:

* Benutzerkonto der Benutzerklasse **Variabel** erstellen
* Berechtigung für Sichtbarkeit von POS aktivieren
* Berechtigungen für POS-Funktionen aktivieren (optional)
* Berechtigungen für Kommunikation mit plentymarkets Backend über die REST-API aktivieren
* Berechtigungen für Sichtbarkeit von Kennzahlen aktivieren (optional)

Die Einstellungen, die Sie benötigen, um ein Benutzerkonto für Kassenpersonal zu erstellen, werden nachfolgend beschrieben. Allgemeine Informationen zu Benutzerkonten und Berechtigungen finden Sie auf der Handbuchseite <<basics/admin-aufgaben/benutzer-verwalten#, Benutzerkonten verwalten>>.

[TIP]
.Tipp: Rolle für Kassenpersonal erstellen
====
Um die Rechteverwaltung für Kassenpersonal zu vereinfachen, erstellen Sie eine <<basics/admin-aufgaben/benutzer-verwalten#70, Rolle>> mit den Berechtigungen, die Sie Kassenpersonal zuweisen möchten, und verknüpfen diese Rolle mit den Benutzerkonten des Kassenpersonals.
====

[#140]
=== Konto für Kassenpersonal erstellen

Damit neues Kassenpersonal Zugriff auf plentymarkets POS erhält, erstellen Sie zunächst im plentymarkets Backend <<basics/admin-aufgaben/benutzer-verwalten#, Benutzerkonten>> der Benutzerklasse **Variabel** für diese Personen. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Benutzerkonto für Kassenpersonal erstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Klicken Sie auf *Neu*. +
→ Das Fenster *Neuen Benutzer anlegen* wird geöffnet.
. Geben Sie den *Benutzernamen* ein.
. Geben Sie den *realen Namen* ein.
. Geben Sie das *Passwort* ein.
. Wiederholen Sie das Passwort.
. Geben Sie eine *Neue App-PIN* mit 4 bis 12 Ziffern ein.
. Wiederholen Sie die App-PIN.
. Geben Sie die E-Mail-Adresse der Kassenkraft ein, damit die Person Benachrichtigungen des Systems empfängt.
. Wählen Sie die Benutzerklasse *Variabel*.
. *Speichern* Sie die Einstellungen.

[TIP]
.App-PIN für schnellen Kontowechsel
====
Die App-PIN erlaubt einen schnellen Wechsel des Benutzerkontos in bestimmten Menüs der plentymarkets App. Beim ersten Anmelden in der App wird aber das Passwort abgefragt. Ihr Kassenpersonal benötigt also Passwort und PIN.
====

[#150]
=== Berechtigungen für Kassenpersonal aktivieren

Erteilen Sie nun Berechtigungen für die Kommunikation zwischen plentymarkets POS und dem plentymarkets Backend über die REST-API.

[.instruction]
Berechtigungen aktivieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Übersicht wird geöffnet.
. *_Optional:_* Geben Sie in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicken Sie auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicken Sie auf das gewünschte Konto. +
→ Die Ansicht *Rechte* wird geöffnet.
. Aktivieren Sie im Bereich *Berechtigungen* die in <<tabelle-POS-REST-Berechtigungen>> gelisteten Berechtigungen.
. *Speichern* Sie die Einstellungen.

[[tabelle-POS-REST-Berechtigungen]]
.Berechtigungen für variable Konten
[cols="1,3"]
|====
|Bereich |Berechtigung

|*Kommentare*
a|* *Kommentar erstellen*

|*Mobile*
a|* *config* +
→ Die untergeordneten Berechtigungen werden automatisch aktiviert.

|*CRM*
a|* *Auftragszusammenfassung » Auftragszusammenfassung anzeigen*
* *Adresse » Adresse anzeigen*
* *Adresse » Adresstyp » Adresstyp anzeigen*
* *Kontakt » Kontakt anzeigen*

|*Aufträge*
a|* *Aufträge erstellen*
* *Aufträge anzeigen*

|*Warenbestände*
a|* *Lager » Lagerort » Lagerort anzeigen*

|*CRM » Kampagne » Code* (optional)
a|* *Code erstellen*
* *Code löschen* +
* *Code anzeigen*

*_Hinweis:_* Diese Rechte sind nur für den Gutscheinverkauf erforderlich.
|====

[#160]
=== POS-Sichtbarkeit für Kassenpersonal aktivieren

Nun legen Sie fest, welche Bereiche und Kennzahlen für Kassenpersonal der Benutzerklasse *Variabel* in der plentymarkets App sichtbar sein sollen.

[.instruction]
App-Berechtigungen aktivieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Öffnen Sie einen Benutzer.
. Öffnen Sie das Tab *Mobile*.
. Aktivieren Sie im Bereich *Sichtbare Funktionen* die Option *POS*.
. Wenn die Kassenkraft auf weitere Bereiche der plentymarkets App zugreifen soll, aktivieren Sie <<pos/pos-einrichten#170, weitere Berechtigungen>>.
. *Speichern* Sie die Einstellungen. +
→ Die Kassenkraft hat Zugriff auf plentymarkets POS und kann Kassenaufträge erstellen.

[#170]
=== Berechtigungen für optionale POS-Funktionen aktivieren

Damit Kassenpersonal in plentymarkets POS Preise bearbeiten, Auftragspositionen umbenennen und/oder Rabatte gewähren können, müssen Sie die Berechtigungen dazu zuweisen. Wie Sie Rollen einrichten und Benutzern zuweisen, erfahren Sie <<basics/admin-aufgaben/benutzer-verwalten#, hier>>. Dort schalten Sie auch weitere App-Funktionen für Kassenpersonal frei.

Im plentymarkets Backend legen Sie über das Zuweisen von Rollen fest, welche POS-Funktionen Kassenpersonal verwenden darf. Dort legen Sie außerdem fest, welche weiteren Bereiche und Kennzahlen in der plentymarkets App sichtbar sein sollen.

[.instruction]
Berechtigungen für POS-Funktionen aktivieren:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Öffnen Sie einen Benutzer.
. Öffnen Sie das Tab **Berechtigung**.
. Öffnen Sie das Tab **Mobile**.
. Aktivieren Sie die POS-Funktionen, die der Kassenkraft zur Verfügung stehen sollen. Beachten Sie <<tabelle-POS-berechtigungen>>.
. **Speichern** Sie die Einstellungen.

[[tabelle-POS-berechtigungen]]
.Mobile-Berechtigungen für Kassenpersonal
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Sichtbare Funktionen

|**POS**
|Gibt Kassenpersonal Zugang zu plentymarkets POS.

2+|POS-Funktionen

|**Preis bearbeiten**
|Erlaubt Kassenpersonal, Preise in Aufträgen zu bearbeiten.

|**Artikelposition umbenennen**
|Erlaubt Kassenpersonal, Positionen des Auftrags umzubenennen.

|*Rabatt gewähren*
|Erlaubt Kassenpersonal, Rabatte auf Auftragspositionen oder ganze Aufträge zu gewähren. +
*_Hinweis:_* Artikel, bei denen die Option *Aktionsgutschein/POS-Rabatt* auf *Verboten* gestellt ist, können nicht rabattiert werden.

|**Kassieren**
|Erlaubt Kassenpersonal zu kassieren.

|**Kasse sperren**
|Erlaubt Kassenpersonal, die Kasse zu sperren.

|**Einlagen und Entnahmen**
|Erlaubt Kassenpersonal, Einlagen und Entnahmen zu tätigen.

|**Kassensturz**
|Erlaubt Kassenpersonal, Kassenstürze durchzuführen.

|**Tagesabschluss**
a|Erlaubt Kassenpersonal, Tagesabschlüsse zu erzeugen. +
Tagesabschlussberichte enthalten folgende Informationen: +

* Barbestand: Anfangsbarbestand, Entnahmen, Einlagen, Soll-Kassenbestand, Ist-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retournierte Artikel: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufte Gutscheine: Anzahl und Summe
* Benutzer: Umsatz, Stornierungen und Retouren pro Benutzer

|**Zwischenbericht**
a|Erlaubt Kassenpersonal, Zwischenberichte zu erzeugen. +
Zwischenberichte enthalten folgende Informationen: +

* Barbestand: Entnahmen, Einlagen, Soll-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retournierte Artikel: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufte Gutscheine: Anzahl und Summe
* Benutzer: Umsatz, Stornierungen und Retouren pro Benutzer

|**Artikel synchronisieren**
|Erlaubt Kassenpersonal, Artikeldaten mit der Kasse zu synchronisieren.

|**Aufträge hochladen**
|Erlaubt Kassenpersonal, Kassenaufträge in plentymarkets hochzuladen.

|**Retoure anlegen**
|Erlaubt Kassenpersonal, Retouren zu buchen.

|**Kunde auswählen**
|Erlaubt Kassenpersonal, während des Kassierens Kundendaten aufzurufen und einen plentymarkets Bestandskunden zu wählen. +
**__Hinweis:__** Damit dieses Recht greift, muss der Kassenkraft im Tab **REST-API** auch die Berechtigung **Firma » Kontakt » Adresse » Adresse anzeigen** erteilt werden.

|**Stornierung**
|Erlaubt Kassenpersonal, Aufträge zu stornieren.
|====

=== Gesperrte POS-Benutzer entsperren

Wenn Kassenpersonal das Passwort beim Login mehrmals hintereinander falsch eingegeben, wird das Konto eine gewisse Zeit gesperrt. Wenn Sie Admin-Rechte haben, können Sie diese Sperre im plentymarkets Admin-Bereich frühzeitig aufheben.

[.instruction]
Benutzer entsperren:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten » Benutzer öffnen**.
. Klicken Sie auf **Login entsperren**. +
→ Die Kassenkraft kann sich wieder bei der plentymarkets App anmelden.

[#700]
== Zahlungsarten für Kassenaufträge aktivieren

Damit Aufträge über plentymarkets POS kassiert werden können, aktivieren Sie die Zahlungsarten, die Sie über plentymarkets POS erlauben möchten. Mindestens die Zahlungsart **Bar bei Übergabe** muss aktiviert werden, damit Kassenaufträge bar bezahlt werden können. Weitere Zahlungsarten sind optional.

=== plentymarkets Zahlungsarten aktivieren

Aktivieren Sie nun die Zahlungsarten, die Sie benötigen. Beachten Sie, dass Zahlungsarten in einem weiteren Schritt für Kundenklassen erlaubt werden müssen. Weitere Informationen finden Sie unter <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.

Aktiveren Sie die folgenden Zahlungsarten, damit Kassenaufträge korrekt dargestellt werden:

* **4 » Bar bei Übergabe** für Barzahlungen
* **11 » Barverkauf/EC-Karte** für Kartenzahlungen über externe EC-Kartenterminals
* **1700 » Coupon** für Gutscheinzahlungen

Gehen Sie wie unten beschrieben vor, um diese Zahlungsarten zu aktivieren.

[.instruction]
Zahlungsarten für Kassenaufträge einrichten:

. Öffnen Sie das Menü **System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten**.
. Aktivieren Sie die Einstellung **Auch inaktive zeigen**.
. Öffnen Sie den Ordner **International**.
. Klicken Sie auf die Zahlungsart. +
→ Das Tab **Einstellungen** wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-POS-zahlungsarten>>.
. Setzen Sie ein Häkchen bei der Option **Aktiv**.
. **Speichern** Sie die Einstellungen.

[[tabelle-POS-zahlungsarten]]
.Einstellungen der Zahlungsarten für Kassenaufträge
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Sprache**
|Sprache wählen. Folgende Optionen werden sprachabhängig gespeichert: Name, Infoseite, Infoseite (Intern), Logo und Logo hochladen.

|**Name**
|Den externen Namen eingeben, der auf dem Kassenbeleg und im Webshop und auf Rechnungen angezeigt werden soll. Wenn kein Name gespeichert ist, wird der Backend-Name der Zahlungsart für den Kassenbeleg verwendet. +
__**Tipp:**__ Der externe Name wird in der Sprache auf dem Beleg ausgegeben, die das Kassenpersonal bei der Kassenanmeldung wählt.

|**Infoseite**
|Die Standardeinstellung **---** nur ändern, wenn die Zahlungsart auch im Webshop verwendet wird.

|**Lieferländer**
|Ein oder mehrere Lieferländer wählen. +
**__Hinweis:__** Lieferländer nur wählen, wenn die Zahlungsart auch im Webshop verwendet wird.

|**Mandant**
|Den Mandanten der POS-Kassen wählen.

|**Logo**
|Die Standardeinstellung **Standardlogo anzeigen** nur ändern, wenn die Zahlungsart auch im Webshop verwendet wird.

|**Kosten: Pauschal oder Prozentual**
|Für alle Kosten **0,00** eintragen, damit kein Aufpreis für die Zahlungsart berechnet wird.
|====

[TIP]
.Zahlungsart Barverkauf/EC-Karte
====
Stellen Sie für die Zahlungsart **11 » Barverkauf/EC-Karte** außerdem im Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS  » Kasse öffnen » Tab: Zahlungsart** die Option **Ohne Anbindung** im Bereich **EC-Terminal** ein.
====

[#1070]
=== Kartenterminals anbinden

Bestimmte Kartenterminals können über ein Plugin an plentymarkets POS angebunden werden. Aktuell unterstützt plentymarkets POS folgende Anbindungen:

* link:https://marketplace.plentymarkets.com/plugins/payment/ingenicozvt_5140[Ingenico-Geräte über ZVT-Schnittstelle^]
* link:https://marketplace.plentymarkets.com/plugins/payment/sumup_5141[SumUp Air^]
* link:https://marketplace.plentymarkets.com/plugins/payment/VerifoneZVT_5504[Verifone-Geräte über ZVT-Schnittstelle^]

Informationen dazu, wie Sie diese Plugins an plentymarkets POS anbinden, finden Sie in der Beschreibung des Plugins.

[#1080]
=== Kauf auf Rechnung anbieten

Wenn Sie Bestandskunden die Möglichkeit geben möchten, Kassenaufträge per Rechnung zu bezahlen, benötigen Sie das folgende Plugin:

* link:https://marketplace.plentymarkets.com/plugins/payment/PosInvoice_5590[POS Kauf auf Rechnung^]

Informationen dazu, wie Sie das Plugin einbinden, finden Sie in der Beschreibung des Plugins.

[#950]
== Buchungskonten für plentymarkets POS Kassenvorfälle speichern

Aufträge, die über plentymarkets POS generiert werden, werden den in plentymarkets gespeicherten <<auftraege/buchhaltung#800, Erlöskonten>> zugewiesen. Da Einlagen, Entnahmen und Differenzen aus Kassenstürzen keine Aufträge sind, können Sie für diese Kassenvorfälle eigene Buchungskonten speichern. Sie legen also fest, auf welche Buchungskonten Einlagen und Entnahmen gebucht werden, die über plentymarkets POS Kassen getätigt werden. Außerdem speichern Sie Buchungskonten für Differenzen, die sich aus Kassenstürzen ergeben.

=== Buchungskonten für Kassensturzdifferenzen speichern

Wenn beim Kassensturz der Ist-Kassenbestand vom Soll-Kassenbestand abweicht, muss die Differenz entweder ausgeglichen oder gebucht werden. Wenn die Differenz gebucht wird, wird der Ist-Kassenbestand als neuer Soll-Kassenbestand übernommen. Gleichzeitig wird abhängig vom Vorzeichen des Differenzbetrags entweder eine Einlage (+) oder eine Entnahme (-) gebucht. Gehen Sie wie unten beschrieben vor, um Buchungen, die sich aus Kassensturzdifferenzen ergeben, Buchungskonten zuzuweisen.

[.instruction]
Buchungskonten für Kassensturzdifferenzen speichern:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung*. +
→ Das Tab *Grundeinstellungen* wird geöffnet.
. Wechseln Sie in das Tab *Konten*. +
→ Das Tab *Buchungsschlüssel* wird geöffnet.
. Wechseln Sie in das Tab *Kassenvorfälle*.
. Klicken Sie im Bereich *Entnahme* in der Zeile *Kassensturz* in das Feld der Spalte *Konto*.
. Geben Sie das Konto ein, auf das Entnahmen gebucht werden, die entstehen, wenn der Ist-Kassenbestand größer ist als der Soll-Kassenbestand.
. Klicken Sie im Bereich *Einlage* in der Zeile *Kassensturz* in das Feld der Spalte *Konto*.
. Geben Sie das Konto ein, auf das Einlagen gebucht werden, die entstehen, wenn der Soll-Kassenbestand größer ist als der Ist-Kassenbestand.
. *Speichern* Sie die Einstellungen. +
→ Die Buchungskonten werden gespeichert. +
→ Einlagen und Entnahmen, die durch Kassensturzdifferenzen entstehen, werden automatisch auf die gespeicherten Konten gebucht.

=== Buchungskonten für allgemeine Einlagen und Entnahmen speichern

Wenn Kassenpersonal Einlagen und Entnahmen über plentymarkets POS durchführt, wählt die Kassenkraft einen Kassenvorfall als Grund für die Buchung. Systemseitig sind dafür standardmäßig ein Kassenvorfall *Entnahme* und ein Kassenvorfall *Einlage* verfügbar, die nicht gelöscht werden können. Für diese Vorfälle können Sie Buchungskonten speichern, wenn die Beträge auf bestimmte Buchungskonten gebucht werden sollen. Gehen Sie wie unten beschrieben vor, um Konten für diese Vorfälle zu speichern. Optional speichern Sie in einem weiteren Schritt zusätzliche Konten, um mit mehreren Buchungskonten zu arbeiten.

[.instruction]
Buchungskonten für Einlagen und Entnahmen speichern:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung*. +
→ Das Tab *Grundeinstellungen* wird geöffnet.
. Wechseln Sie in das Tab *Konten*. +
→ Das Tab *Buchungsschlüssel* wird geöffnet.
. Wechseln Sie in das Tab *Kassenvorfälle*.
. Klicken Sie im Bereich *Entnahme* in der Zeile *Entnahme* in das Feld der Spalte *Konto*.
. Geben Sie das Konto ein, auf das allgemeine Entnahmen gebucht werden sollen.
. Klicken Sie im Bereich *Einlage* in der Zeile *Einlage* in das Feld der Spalte *Konto*.
. Geben Sie das Konto ein, auf das allgemeine Einlagen gebucht werden sollen.
. *Speichern* Sie die Einstellungen. +
→ Die Buchungskonten werden gespeichert. +
→ Einlagen oder Entnahmen werden diesem Konto zugewiesen.

=== Weitere Buchungskonten für Einlagen und Entnahmen speichern

Wenn plentymarkets POS Einlagen und Entnahmen je nach Grund verschiedenen Buchungskonten zugewiesen werden sollen, legen Sie weitere Kassenvorfälle an. Diese Kassenvorfälle kann das Kassenpersonal wählen, wenn Bargeld aus der Kasse entnommen oder in die Kasse gelegt wird. Gehen Sie wie unten beschrieben vor, um weitere Kombinationen aus Kassenvorfall und Buchungskonto zu speichern.

[.instruction]
Weitere Buchungskonten für Einlagen und Entnahmen speichern:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung*. +
→ Das Tab *Grundeinstellungen* wird geöffnet.
. Wechseln Sie in das Tab *Konten*. +
→ Das Tab *Buchungsschlüssel* wird geöffnet.
. Wechseln Sie in das Tab *Kassenvorfälle*.
. Klicken Sie auf *Neue Einlage* oder *Neue Entnahme*. +
→ Eine leere Zeile wird eingefügt.
. Geben Sie die *Bezeichnung* ein, die Kassenpersonal bei Einlagen oder Entnahmen in einer Dropdown-Liste angezeigt wird.
. Geben Sie das Buchungskonto ein, dem die Einlage oder Entnahme buchhalterisch zugewiesen wird. +
**__Tipp:__** Über die Pfeile steuern Sie die Reihenfolge, in der die Vorfälle in der App angezeigt werden.
. *Speichern* Sie die Einstellungen. +
→ Das Buchungskonto wird gespeichert. +
→ Kassenpersonal kann bei Einlagen oder Entnahmen den Vorfall aus der Dropdown-Liste wählen.


[#180]
== Versandart Selbstabholung einrichten

Damit Kassenaufträge korrekt in plentymarkets verbucht werden, ermöglichen Sie die Versandart **Selbstabholung** für die Artikel, die Sie über plentymarkets POS abrechnen möchten. Dazu sind folgende Vorbereitungen notwendig:

* Versanddienstleister **Selbstabholung** erstellen
* Versandprofil **Selbstabholung** erstellen
* Versandprofil **Selbstabholung** am Artikel aktivieren

Diese Vorbereitungen werden nachfolgend beschrieben.

[#190]
=== Versanddienstleister Selbstabholung erstellen

Gehen Sie wie unten beschrieben vor, um einen Versanddienstleister **Selbstabholung** zu erstellen. Nur die für diesen Versanddienstleister relevanten Einstellungen werden beschrieben. Allgemeine Informationen zu Versanddienstleistern finden Sie auf der Handbuchseite <<fulfillment/versand-vorbereiten#800, Versand vorbereiten>>.

[.instruction]
Versanddienstleister Selbstabholung erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister**.
. Klicken Sie auf **Neu**. +
→ Ganz unten wird eine neue Zeile hinzugefügt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-POS-versanddienstleister-selbstabholung>>.
. **Speichern** Sie die Einstellungen.

[[tabelle-POS-versanddienstleister-selbstabholung]]
.Versanddienstleister **Selbstabholung** erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Name (de)**
|Namen eingeben, zum Beispiel **Selbstabholung**.

|**Name (Backend)**
|Systeminternen Namen eingeben, zum Beispiel **Selbstabholung**.

|**Versanddienstleister**
|Option **Selbstabholer** aus der Dropdown-Liste wählen.
|====

[#200]
=== Versandprofil Selbstabholung erstellen

Erstellen Sie nun ein Versandprofil für die Selbstabholung. Nur die für dieses Versandprofil relevanten Einstellungen werden beschrieben. Allgemeine Informationen zu Versandprofilen finden Sie auf der Handbuchseite <<fulfillment/versand-vorbereiten#1000, Versand vorbereiten>>.

[.instruction]
Versandprofil für Selbstabholer erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile**.
. Klicken Sie auf **Neu**.
. Wählen Sie den eben erstellten Versanddienstleister aus der Dropdown-Liste.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-POS-versandprofil-selbstabholung>>.
. **Speichern** Sie die Einstellungen. +
→ Das Tab **Portotabelle** wird angezeigt.
. **Speichern** Sie die Einstellungen des Tabs **Portotabelle** ohne Änderungen.

[[tabelle-POS-versandprofil-selbstabholung]]
.Versandprofil **Selbstabholung** erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Versanddienstleister**
|Versanddienstleister **Selbstabholung** aus der Dropdown-Liste wählen.

|**Mandanten (Shops)**
|Option wird nur angezeigt, wenn mindestens ein Mandant eingerichtet ist. Mandanten oder die Option **ALLE** wählen, wenn das Versandprofil für alle Webshops gelten soll.

|**Auftragsherkunft**
|plentymarkets POS-Kasse(n) als Auftragsherkunft wählen.

|**Gesperrte Zahlungsarten**
|Die Zahlungsarten wählen, die für das Versandprofil **Selbstabholung** nicht angeboten werden sollen.
|====

[#210]
=== Versandprofil Selbstabholung am Artikel aktivieren

Aktivieren Sie nun das Versandprofil **Selbstabholung** bei den Artikeln, die Sie über die Kasse verkaufen möchten.

[.instruction]
Versandprofil Selbstabholung aktivieren:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab **Global**.
. Aktivieren Sie das Versandprofil **Selbstabholung**.
. **Speichern** Sie die Einstellungen.

Sie möchten das Versandprofil für eine größere Anzahl an Artikeln gleichzeitig aktivieren? Dann nutzen Sie die <<artikel/artikel-verwalten#155, Artikel-Gruppenfunktion>>.

[#100]
== Preise für Kassenaufträge verwalten

Um POS-Preise für Varianten zu hinterlegen, benötigen Sie mindestens einen <<artikel/artikel-verwalten#870, Verkaufspreis>>, bei dem die POS-Herkunft der Kasse aktiviert ist. Verkaufspreise erstellen und verwalten Sie zentral. Preise für Varianten hinterlegen Sie, indem Sie Varianten mit dem Verkaufspreis verknüpfen und einen Preis speichern.

[#750]
=== Verkaufspreis für Kassenaufträge erstellen

Wenn Sie bereits Verkaufspreise erstellt haben, die Ihren Anforderungen für Kassenaufträge entsprechen, aktivieren Sie bei diesen Verkaufspreisen die Herkunft der Kasse. Gehen Sie sonst wie unten beschrieben vor, um einen neuen Verkaufspreis für Kassenaufträge zu erstellen. Nur die für POS-Herkünfte relevanten Einstellungen werden beschrieben.

[.instruction]
Verkaufspreis für Kassenaufträge erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Artikel » Verkaufspreise**.
. Klicken Sie auf **Neu**. +
→ Das Tab **Neu** wird geöffnet.
. Nehmen Sie die Einstellungen gemäß <<tabelle-POS-verkaufspreis>> vor.
. **Speichern** Sie die Einstellungen.

[[tabelle-POS-verkaufspreis]]
.Verkaufspreis für Kassenaufträge erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Position**
|Positionsnummer eingeben. Verkaufspreise werden im Bereich **Verkaufspreise** von Artikelvarianten aufsteigend sortiert.

|**Interner Name DE**
|Internen Namen eingeben. Der interne Name wird nur im plentymarkets Backend angezeigt.

|**Externer Name DE**
|Externen Namen eingeben. Der externe Name wird im Webshop angezeigt.

|**Ab Menge**
|Mengenwert eingeben. Über Verkaufspreise mit verschiedenen Mengenwerten bilden Sie mengenbezogene Preisstaffelungen in plentymarkets ab.

|**Währung**
|Die Währung aktivieren, in der Kassenaufträge kassiert werden.

|**Preistyp**
|Preistyp für den Verkaufspreis aktivieren. +
**UVP** = Aktivieren, wenn der Verkaufspreis ein unverbindlicher Verkaufspreis (UVP) ist. Wird der UVP und ein weiterer Verkaufspreis an der Variante verknüpft, dann wird der UVP im Webshop in rot und durchgestrichen neben dem Verkaufspreis dargestellt. +
**__Hinweis:__** Preise des Typs *UVP* dienen nur dazu, den Preisvergleich zwischen dem UVP und einem Verkaufspreis darzustellen. Varianten können nicht zu diesem UVP-Preis verkauft werden. +
**Aktionspreis** = Aktivieren, um einen Verkaufspreis als Aktionspreis zu kennzeichnen.

|**Mandant**
|Die Mandanten (Shops) aktivieren, mit denen der Verkaufspreis verknüpft wird.

|**Land**
|Das Land aktivieren, in dem die Kasse eingesetzt wird.

|**Herkunft**
|Eine oder mehrere plentymarkets POS Auftragsherkünfte aktivieren, mit denen der Verkaufspreis verknüpft wird.
|====

[#550]
=== Verkaufspreis mit Varianten verknüpfen

Verknüpfen Sie nun den POS-Verkaufspreis mit den Hauptvarianten der Artikel, die Sie über die Kasse verkaufen möchten. Verkaufspreise werden von der Hauptvariante an Varianten vererbt. Sie können Verkaufspreise auch individuell mit Varianten verknüpfen.

[.instruction]
Verkaufspreis mit Hauptvariante verknüpfen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Wählen Sie im Bereich **Verkaufspreise** den Preis aus der Dropdown-Liste.
. Wählen Sie, ob der Preis ein Brutto- oder Nettopreis ist.
. *_Optional:_* Wählen Sie eine Preiskalkulation.
. Klicken Sie auf **Hinzufügen**. +
→ Der Verkaufspreis wird hinzugefügt und in der Liste angezeigt.
. Geben Sie einen Wert in das Feld **Preis** ein.
. **Speichern** Sie die Einstellungen. +
→ Die Preise werden an die Varianten des Artikels vererbt. Speichern Sie für Varianten mit abweichendem Preis einen eigenen Wert.

[#800]
=== Rundungsverhalten für Kassenaufträge festlegen

Beträge werden auf plentymarkets POS Kassenbelegen grundsätzlich mit 2 Nachkommastellen dargestellt. Über die Einstellungen im plentymarkets Backend steuern Sie, ob die Preise in den Aufträge auch im Hintergrund auf 2 Nachkommastellen gerundet oder ob mit 4 Nachkommastellen gerechnet werden soll. Das Rundungsverhalten für Aufträge, die über plentymarkets POS Kassen generiert werden, wird über die folgenden 3 Optionen gesteuert:

.Erforderliche Optionen für Rundungsverhalten bei Kassenaufträgen
[cols="10,1,1"]
|====
|Menü |Option |Mögliche Einstellungen

|System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung
|Anzahl Nachkommstellen bei Preisen
a|
* 2
* 4

|System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung
|Nur Gesamtpreise runden
a|
* Ja
* Nein

|System » Systemeinstellungen » Mandant » Mandant wählen » POS » Kasse öffnen » Tab: Beleg
|Identische Auftragspositionen
a|
* Einzeln darstellen
* Zusammenfassen
|====

Aus diesen Einstellungen ergeben sich 6 Einstellungskombinationen:

* Auftragspositionen einzeln darstellen, Einzelpreise auf 2 Nachkommastellen runden
* Auftragspositionen einzeln darstellen, Einzelpreise auf 4 Nachkommastellen runden
* Auftragspositionen einzeln darstellen, Gesamtpreise auf 4 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Einzelpreise auf 2 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Einzelpreise auf 4 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Gesamtpreise auf 4 Nachkommastellen runden

Abhängig von den gewählten Einstellungen kommt es zu unterschiedlichen Gesamtbeträgen. Beachten Sie, dass sich die Abweichungen potenzieren, je mehr Artikel mit Rundungsbedarf pro Auftrag/Beleg verkauft werden.

==== Beispielrechnung

<<tabelle-POS-rundungsverhalten>> zeigt eine Beispielrechnung, um die Rundungsabweichungen zu verdeutlichen, die durch die verschiedenen Einstellungskombinationen entstehen.

Die Beispielrechnung beruht auf den folgenden Daten:

. Berechnungsbasis: Artikel zum Preis von 4,545 Euro
. Rechnung 1: Verkauf von 10 Artikeln
. Rechnung 2: Verkauf von 10 Artikeln mit 5 % Positionsrabatt

[[tabelle-POS-rundungsverhalten]]
.Beispielrechnung bei einem Artikelpreis mit 4 Nachkommastellen
[cols="2,1,1"]
|====
|Gewählte Einstellungen |Rechnung 1 (4,545 Euro x 10) Gesamtpreis auf Beleg |Rechnung 2 (4,545 Euro x 10 - 5%) Gesamtpreis auf Beleg

|Anzahl Nachkommastellen = 2  +
Auftragspositionen = Einzeln darstellen
|45,50 Euro
|43,20 Euro

|Anzahl Nachkommastellen = 4  +
Nur Gesamtpreise runden = Nein +
Auftragspositionen = Einzeln darstellen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Ja +
Auftragspositionen = Einzeln darstellen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 2 +
Auftragspositionen = Zusammenfassen
|43,50 Euro
|43,50 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Nein +
Auftragspositionen = Zusammenfassen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Ja +
Auftragspositionen = Zusammenfassen
|45,45 Euro
|43,18 Euro
|====

Detaillierte Informationen und weitere Rechnungsbeispiele zum Rundungsverhalten finden Sie auch auf der Handbuchseite <<auftraege/buchhaltung#, Buchhaltung>>.

[#95]
== Standardkunden für Kassenaufträge erstellen

Damit Kassenaufträge korrekt in plentymarkets gespeichert werden, muss jedem Auftrag ein Kontakt zugeordnet sein. Deshalb erstellen Sie einen anonymen Standardkunden für Ihre Laufkundschaft. Gehen Sie wie unten beschrieben vor, um einen Standardkunden für Kassenaufträge anzulegen. Nur die Einstellungen werden beschrieben, die für das Erstellen des Standardkunden für Kassenaufträge relevant sind. Allgemeine Informationen zum Erstellen von Kontakten finden Sie auf der Handbuchseite <<crm/kontakte-verwalten#, Kontakte verwalten>>.

[IMPORTANT]
.Einstellungen für Standardkunden für Kassenaufträge mit Steuerberater abstimmen
====
Klären Sie im Vorfeld mit Ihrem Steuerbüro, welche Einstellungen für Standardkunden für Kassenaufträge sinnvoll sind.
====

[.instruction]
Standardkunden für Kassenaufträge erstellen:

. Öffnen Sie das Menü **CRM » Kontakte**.
. Klicken Sie auf **Neuen Kontakt erstellen**.
. Nehmen Sie die Einstellungen gemäß <<tabelle-POS-standardkunde>> vor.
. **Speichern** Sie die Einstellungen.
. Öffnen Sie das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS » Kasse öffnen » Grundeinstellungen**.
. Geben Sie die ID des Standardkunden in das Feld **Standardkunde** ein.
. **Speichern** Sie die Einstellungen.

[[tabelle-POS-standardkunde]]
.Standardkunden für Kassenaufträge erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Firma**
|Einen Firmennamen eingeben, zum Beispiel plentymarkets Kasse.

|**Anrede**
|Option **Firma** aus der Dropdown-Liste wählen.

|**Straße; +
PLZ**; +
**Ort**
|Straße, Postleitzahl und Ort eingeben.

|**Land**
|Land aus der Dropdown-Liste wählen, in dem die Kasse eingesetzt wird. Standardeinstellung richtet sich nach der Option **Firmensitz für FiBu** im Menü <<schnelleinstieg/schnelleinstieg-basiseinstellungen#100, System » Systemeinstellungen » Einstellungen » Stammdaten>>.

|**Mandant**
|Mandanten aus der Dropdown-Liste wählen, wenn die Kasse nicht dem Standardmandanten zugeordnet ist.

|**Typ**
|Option **Kunde** aus der Dropdown-Liste wählen.
|====

[#220]
== Dummy-Artikel erstellen

Im Tagesgeschäft kommt es vor, dass Artikel verkauft werden sollen, für die es keinen Datensatz im System gibt. Zum Beispiel wird häufig für Diversartikel kein Datensatz erstellt. Um diese Artikel trotzdem kassieren zu können, erstellen Sie Dummy-Artikel. Kassenpersonal fügt dann den Dummy-Artikel zum POS-Warenkorb hinzu und passen den Preis und optional den Namen der Auftragsposition an.

Die folgenden Vorbereitungen sind nötig, um mit Dummy-Artikeln zu arbeiten.

* Einen Dummy-Artikel für jeden Umsatzsteuersatz erstellen, der für die Produkte Ihres Portfolios relevant sind. Wenn Sie Artikel mit 19% und 7% verkaufen, benötigen Sie also zwei Dummy-Artikel.
* Option *Preisabfrage wenn Artikelpreis 0* aktivieren, damit Kassenpersonal den Preis manuell eingeben kann.
* Kassenpersonal Rechte zum Bearbeiten von Preisen erteilen.
* Kassenpersonal Rechte zum Umbenennen von Auftragspositionen erteilen (optional).

Die erforderlichen Einstellungen werden in <<tabelle-POS-dummy-artikel>> kurz erläutert. Die  Zwischenüberschriften der Tabelle geben an, in welchem Menü Sie die Einstellung vornehmen.

[[tabelle-POS-dummy-artikel]]
.Empfohlene Einstellungen für Dummy-Artikel
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Artikel » Artikel bearbeiten » Neuen Artikel erstellen » Tab: Einstellungen*

|**Beschränkung**
|Option **Keinen WB für diese Variante führen** wählen.

|**Preis**
|Verkaufspreis für Kasse wählen und Preis *0,00* Euro eingeben.

|**Umsatzsteuer**
|Umsatzsteuersatz eingeben, der für den Dummy-Artikel gelten soll.

2+|*System » Systemeinstellungen » Mandant » Mandant wählen » POS » Kasse öffnen*

|**Preisabfrage wenn Artikelpreis 0**
|Option aktivieren.

2+|*System » Systemeinstellungen » Einstellungen » Benutzer » Konten » Konto öffnen » Tab: Mobile » POS-Funktionen*

|**Preis bearbeiten**
|Recht für Kassenpersonal aktivieren, damit Kassenpersonal den Preis anpassen kann.

|**Artikelposition umbenennen**
|Recht für Kassenpersonal aktivieren, wenn Kassenpersonal den Namen von Dummy-Artikeln anpassen können soll.
|====

[#2100]
== Gutscheinverkauf vorbereiten

Sie können über plentymarkets POS Verkaufsgutscheine verkaufen und einlösen. Wenn Sie einen Gutscheinartikel verkaufen, händigen Sie zusammen mit dem Kassenbeleg einen Gutschein-Code aus. Ein Gutschein-Code kann nur eingelöst werden, wenn dieser Gutschein-Code zum Zeitpunkt der Einlösung im plentymarkets Backend gespeichert ist. Sie können Gutschein-Codes entweder automatisch generieren oder mit eigenen Gutschein-Codes arbeiten.

Um Verkaufsgutscheine über plentymarkets POS zu verkaufen, sind die folgenden Vorbereitungen im plentymarkets Backend erforderlich.

* Gutscheinkampagne mit Gutscheinart **Verkaufsgutschein** erstellen.
* Freitextfeld für die Kampagne erstellen und im Menü *System » Systemeinstellungen » Aufträge » Gutscheine* verknüpfen.
* Gutscheinartikel mit 0% MwSt. erstellen und mit der Gutscheinkampagne verknüpfen.
* *_Optional:_* Gutschein-Codes generieren oder eigene Codes im Backend speichern.
* *_Optional:_* Gutscheinvordrucke erstellen und Kassenpersonal zur Verfügung stellen.
* *_Optional:_* Gutschein-Codes Kassenpersonal zur Verfügung stellen.

Diese Schritte werden nachfolgend kurz erläutert. Eine detaillierte Anleitung zum Erstellen von Kampagnen und Gutscheinen finden Sie auf der Handbuchseite <<auftraege/gutscheine#, Gutscheine>>.

[NOTE]
.Vorgehensweise bei mehreren Kassen
====
Sie haben mehr als eine Kasse und möchten mit eigenen Gutschein-Codes arbeiten? Dann teilen Sie die ausgedruckten Gutschein-Codes zwischen den Kassen auf oder erstellen Sie für jede Kasse eigene Gutscheinkampagnen und -artikel, damit jeder Gutschein-Code nur einmal verkauft wird.
====

=== Freitextfeld vorbereiten

Um Gutscheine zu verkaufen, muss am Artikel ein Freitextfeld hinterlegt werden. Dieses Freitextfeld definieren Sie einmalig und ordnen das Freitextfeld Gutscheinkampagnen zu.

[#820]
==== Freitextfeld definieren

Definieren Sie das Freitextfeld, das für Kampagnen verwendet werden soll.

[.instruction]
Freitextfeld definieren:

. Öffnen Sie das Menü **System » Systemeinstellungen » Artikel » Freitextfelder**.
. Geben Sie in das Feld *Feldbezeichnung* die Bezeichnung **Kampagne ID** ein. +
*_Hinweis:_* Achten Sie auf die Schreibweise. Der Name **Kampagne ID** ist nur in der Schreibweise mit Leerzeichen gültig.
. Wählen Sie den Datentyp **Zahl**.
. Geben Sie eine Zeichenlänge ein.
. **Speichern** Sie die Einstellungen. +
→ Das Freitextfeld wird über Nacht aktiviert und ist am nächsten Morgen verfügbar.

==== Freitextfeld wählen

Im Menü **System » Systemeinstellungen » Aufträge » Gutscheine** wählen Sie nun einmalig dieses Freitextfeld und ordnen das Freitextfeld so Gutscheinkampagnen zu.

[.instruction]
Freitextfeld wählen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Aufträge » Gutscheine**.
. Wählen Sie das Kampagnenfeld **Kampagne ID** aus der Dropdown-Liste.
. **Speichern** Sie die Einstellungen. +
→ Das Feld **Kampagne ID** wird im Tab <<artikel/artikel-verwalten#75, Felder>> der Artikel angezeigt.

[#830]
=== Kampagne für POS-Verkaufsgutscheine erstellen

Erstellen Sie nun für den Verkauf von Gutscheinen über plentymarkets POS eine oder mehrere eigene Kampagnen. Sie haben folgende Möglichkeiten:

* Sie erstellen eine Kampagne für alle Gutscheine, die Sie über plentymarkets POS verkaufen.
* Sie erstellen eine Kampagne pro Gutscheinwert. +
*_Beispiel:_* Sie möchten Gutscheine im Wert von 10 Euro, 25 Euro und 50 Euro sowie einen Gutschein verkaufen, bei dem Kassenpersonal den Wert frei wählen kann. Sie erstellen also 3 Kampagnen mit den Rabattwerten 10, 25 und 50 Euro sowie eine Kampagne mit einem beliebigen Rabattwert.

Wenn Sie mehr als eine Kasse einsetzen und mit eigenen Gutschein-Codes arbeiten möchten, kann es sinnvoll sein, pro Kasse eigene Kampagnen anzulegen. So erstellen Sie eine Kampagne für Verkaufsgutscheine:

[.instruction]
Kampagne für POS-Verkaufsgutscheine erstellen:

. Öffnen Sie das Menü **Aufträge » Gutscheine**.
. Klicken Sie auf **Neue Kampagne**.
. Nehmen Sie die Einstellungen vor. Beachten Sie <<tabelle-POS-gutscheinkampagnen>>.
. **Speichern** Sie die Einstellungen. +
→ Die neue Kampagne wird erstellt und in der Übersicht angezeigt.

[[tabelle-POS-gutscheinkampagnen]]
.Einstellungen für POS-Verkaufsgutscheinkampagnen
[cols="1,2"]
|====
|Einstellung |Benutzereingabe

2+|Kampagne

|**Name**
|Namen für die Kampagne eingeben. +
*_Tipp_*: Der Name sollte den Namen der Kasse und den Gutscheinwert enthalten.

|**Beschreibung**
|Optional eine Beschreibung eingeben.

|**Konzept: Code**
|**Mehrere Codes** wählen, damit jeder Gutschein-Code nur einmal eingelöst werden kann und Restbeträge bei Teileinlösungen korrekt berechnet werden.

|**Konzept: Einlösungen**
|**Einlösung bis Wert aufgebraucht ist** wählen.

|**Nutzung**
|**Einzelbestellungen** oder <<auftraege/scheduler#, Abonnements>> oder beides wählen.

|**Mindestbestellwert**
|Keinen Wert eingeben, da Verkaufsgutscheine wie Zahlungsmittel zu behandeln sind und keinem Mindestbestellwert unterliegen dürfen.

2+|Gültigkeiten

|**Startdatum**
|Das Datum, ab dem die Kampagne aktiv ist.

|**Enddatum**
|Das Datum, bis zu dem die Kampagne aktiv ist.

|**Code-Gültigkeit in Wochen**
|*0* eingeben.

2+|Gutschein

|**Gutscheintyp**
|**Gutschein** wählen.

|**Gutscheinart**
|**Verkaufsgutschein** wählen.

|**Code-Länge**
|Die Zeichenlänge des Gutschein-Codes wählen.

|**Rabattart**
|**Festbetrag** wählen.

|**Rabattwert**
|Den Gutscheinwert eingeben, zum Beispiel 10,00 = 10 Euro. +
**__Hinweis:__** Den Rabattwert nicht mehr ändern, nachdem der erste Gutschein verkauft wurde. +
*_Tipp:_* Dieser Wert wird Codes automatisch zugewiesen, wenn im Tab **Codes** über **Gutschein-Codes manuell generieren** Codes generiert werden, ohne dass ein Betrag in das Feld **Wert** eingegeben wird. +

|**Inkl. Versandkosten**
|Option nicht aktivieren.

2+|Filter

|**Artikel über Preisportale**
|**Nicht erlauben** wählen, da plentymarkets POS nicht an Preisportale angebunden ist.

|**Kategorien**
|Die Kategorien wählen, in denen der Gutschein einlösbar sein soll. Die Auswahl gilt auch für alle Unterkategorien einer markierten Kategorie.

|**Artikel**
|Keinen Wert eingeben, da Verkaufsgutscheine wie Zahlungsmittel zu behandeln sind und nicht auf bestimmte Artikel beschränkt werden dürfen.

|**Mandanten (Shops)**
|Die Mandanten (Shops) wählen, für die die Gutscheine der Kampagne gelten sollen.

|**Kundenklassen**
|Die Kundenklassen wählen, für die die Gutscheine der Kampagne gelten sollen.

|**Kundentypen**
|Die Kundentypen wählen, für die die Gutscheine der Kampagne gelten sollen.
|====

[#850]
=== Gutschein-Codes verwalten

Verkaufsgutscheine werden in plentymarkets POS eingelöst, indem das Kassenpersonal den Gutschein-Code eingibt. Damit der Gutschein-Code eingelöst werden kann, muss der Code zum Zeitpunkt der Einlösung in einer Kampagne des plentymarkets Backends gespeichert sein.

Aus Sicht des Kassenpersonals ergeben sich aus den Konfigurationsmöglichkeiten in plentymarkets drei mögliche Szenarien beim Verkauf eines Gutscheins:

* Der Gutschein-Code wird automatisch von der Kasse generiert.
* Das Kassenpersonal hat eine Liste mit Gutschein-Codes pro Gutscheinwert, die in plentymarkets gespeichert sind. Die Kassenkraft gibt einen Code ein. Der Gutscheinwert wird abgerufen.
* Das Kassenpersonal hat eine Liste mit Gutschein-Codes, die nicht in plentymarkets gespeichert sind. Die Kassenkraft gibt einen Code und einen Gutscheinwert ein.

Nachfolgend wird beschrieben, wie Sie Gutschein-Codes für diese verschiedenen Szenarien konfigurieren.

[#2200]
==== Automatisch Gutschein-Code beim Verkauf generieren

Am wenigsten administrativen Aufwand haben Sie, wenn Kassenbenutzerinnen beim Verkauf eines Gutscheins über plentymarkets POS einen zufälligen <<pos/pos-kassenbenutzer#250, Gutschein-Code generieren>>. Beim Hochladen des Kassenauftrags werden der Gutschein-Code und der damit verbundene Gutscheinwert in die Kampagne importiert, die mit dem Gutscheinartikel verknüpft ist. Der Gutschein-Code wird auf dem Beleg ausgegeben und optional wird ein Gutscheinbeleg erstellt. Das Kassenpersonal kann den Gutschein-Code außerdem per Hand auf einem dekorativen Gutscheinvordruck eintragen.

[#2300]
==== Mit eigenen Gutschein-Codes arbeiten

Wenn Sie Kassenpersonal Gutschein-Codes aushändigen möchten, die beim Kassieren eingegeben werden sollen, erhöht sich der administrative Aufwand. Sie haben aber auch mehr Möglichkeiten, dekorative Gutscheinvordrucke zu erstellen, auf denen nur der Gutschein-Code oder aber der Gutschein-Code und der Gutscheinwert bereits vermerkt sind. Das Kassenpersonal gibt dann einfach diese Gutscheinvordrucke aus.

Gutschein-Codes können entweder vor dem Verkauf oder beim Verkauf des Gutscheins im System gespeichert werden.

Um Gutschein-Codes vor dem Verkauf im plentymarkets Backend zu speichern:

* Sie generieren vor dem Verkauf Gutschein-Codes mit festem Wert in der Kampagne.
* Sie speichern vor dem Verkauf eigene Gutschein-Codes mit festem Wert in der Kampagne.

In diesen Fällen stellen Sie dem Kassenpersonal eine Liste mit diesen Gutschein-Codes und dem dafür gespeicherten Gutscheinwert bereit.

Um Gutschein-Codes beim Verkauf zu speichern:

* Kassenbenutzerinnen geben beim Verkauf des Gutscheins einen noch nicht in plentymarkets gespeicherten Gutschein-Code und den Gutscheinwert ein.

In diesen Fällen stellen Sie dem Kassenpersonal eine Liste mit den Gutschein-Codes bereit. Den Wert des Gutscheins gibt das Kassenpersonal beim Kassieren als Preis für den Gutschein ein.

[NOTE]
.Erstellungsdatum beachten
====
Sie haben bereits in plentymarkets generierte Gutschein-Codes an das Kassenpersonal ausgehändigt und möchten weitere Gutschein-Codes generieren? Dann achten Sie auf das Erstellungsdatum. In plentymarkets werden Gutschein-Codes nicht als verkauft gekennzeichnet. Um Gutschein-Codes nicht doppelt zu verkaufen, bringen Sie nur die Codes in Umlauf, die Sie an einem bestimmten Datum erstellt haben. Am einfachsten geht das, indem Sie Gutscheine im Menü **Aufträge » Gutscheine** generieren und diese Gutschein-Codes als CSV-Datei exportieren. Die CSV-Datei filtern Sie nach dem Erstellungsdatum, also nach der Spalte *GeneriertAm*. So erhalten Sie nur die neuen Gutschein-Codes.
====

[#2400]
==== Gutschein-Codes manuell generieren

Mit dem Gutschein-Generator im Tab **Codes** einer Kampagne erzeugen Sie einen oder mehrere automatisch generierte Gutschein-Codes.

[.instruction]
Gutschein-Codes mit festem Wert manuell generieren:

. Öffnen Sie das Menü **Aufträge » Gutscheine**.
. Klicken Sie auf die Kampagne, für die Sie Gutschein-Codes erzeugen möchten.
. Öffnen Sie das Tab **Codes**.
. Geben Sie im Bereich **Gutschein-Codes manuell generieren** links die gewünschte Anzahl an Gutschein-Codes ein.
. *_Optional:_* Geben Sie in das Feld **Wert** den Wert ein, der dem Gutschein-Code zugewiesen werden soll. +
*_Tipp:_* Wenn Sie das Feld **Wert** leer lassen, wird dem Code der Rabattwert der Kampagne zugewiesen.
. **Speichern** Sie die Eingabe. +
→ Die Gutschein-Codes werden erzeugt und zur Liste der Gutschein-Codes hinzugefügt.
. Klicken Sie auf *Exportieren*, um die Gutschein-Codes zu exportieren. +
→ Ein CSV-Export aller Gutschein-Codes der Kampagne wird erstellt.
. Filtern Sie die Spalte *GeneriertAm* der CSV-Datei nach dem aktuellen Datum. So erhalten Sie eine Liste aller neu erstellten Gutschein-Codes. +
. Stellen Sie dem Kassenpersonal die Gutschein-Codes und Informationen zum Wert der Codes zur Verfügung. +
*_Hinweis:_* Bringen Sie Gutschein-Codes nicht mehrfach in Umlauf. Teilen Sie bei mehreren Kassen die Gutschein-Codes entweder auf oder erstellen Sie separate Kampagnen pro Kasse.

[#2500]
==== Eigene Gutschein-Codes mit festem Wert speichern

Statt Gutschein-Codes in plentymarkets zu generieren, können Sie auch vor dem Verkauf eigene Gutschein-Codes in plentymarkets speichern. Gültige Zeichen für Gutschein-Codes sind Klein- und Großbuchstaben, Ziffern, Unterstriche (_) und Bindestriche (-).

[.instruction]
Eigenen Gutschein-Code mit festem Wert speichern:

. Öffnen Sie das Menü **Aufträge » Gutscheine**.
. Klicken Sie auf die Kampagne, für die Sie einen Gutschein-Code speichern möchten.
. Öffnen Sie das Tab **Codes**.
. Geben Sie im Bereich **Gutschein-Code manuell eintragen** rechts einen Code mit zwischen 6 und 24 Zeichen ein.
. **Speichern** Sie die Eingabe. +
→ Der Gutschein-Code wird gespeichert und zur Liste der Gutschein-Codes hinzugefügt. +
*_Tipp:_* Mit dem Datenformat **CampaignCoupon** importieren Sie mehrere Gutschein-Codes gleichzeitig. Als Gutscheinwert wird dabei der **Rabattwert** importiert. Legen Sie also pro Gutscheinwert eine eigene Kampagne an, wenn Sie mit dem Datenformat arbeiten möchten.
. Stellen Sie dem Kassenpersonal die Gutschein-Codes und Informationen zum Wert der Codes zur Verfügung. +
*_Hinweis:_* Bringen Sie Gutschein-Codes nicht mehrfach in Umlauf. Teilen Sie bei mehreren Kassen die Gutschein-Codes entweder auf oder erstellen Sie separate Kampagnen pro Kasse.

[#3900]
=== Drucken und Speichern von Gutscheinbelegen aktivieren

Optional kann ein Gutscheinbeleg erstellt und gedruckt werden. Der Gutscheinbeleg enthält die folgenden Informationen zum Gutschein:

* Gutscheinwert
* Gutschein-Code
* Bei Teileinlösung:
	** Eingelöster Betrag
	** Restbetrag

[.instruction]
Drucken von Gutscheinbelegen aktivieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » POS*.
. Öffnen Sie die Kasse.
. Wechseln Sie in das Tab *Beleg*.
. Aktivieren Sie die Option *Gutscheinbeleg drucken und speichern*.
. **Speichern** Sie die Einstellungen. +
→ Beim Verkauf oder einer Teileinlösung eines Gutscheins wird ein Gutscheinbeleg erstellt. +
→ Der Gutscheinbeleg wird im Dokumentenarchiv gespeichert. +
→ Wenn die Option *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* aktiviert ist, wird der Gutscheinbeleg nach dem Kassenbeleg ausgedruckt. +
→ Wenn *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* nicht aktiviert ist, kann die Kassenbenutzerin den Gutscheinbeleg nach Abschluss des Auftrags manuell drucken. +
*_Hinweis:_* Beim Verkauf eines Gutscheins wird der Gutschein-Code unabhängig von der gewählten Einstellung immer auf dem normalen Kassenbeleg ausgegeben.


[#840]
=== Gutscheinartikel erstellen

Erstellen Sie nun einen oder mehrere Gutscheinartikel. Da die Kampagnen-ID auf der Artikelebene zugeordnet wird, können Sie bei Verkaufsgutscheinen nicht mit Varianten arbeiten. Detaillierte Informationen zum Erstellen von Artikeln finden Sie auf der Handbuchseite <<artikel/artikel-verwalten#, Artikel verwalten>>. Hier werden nur die Einstellungen beschrieben, die Sie speziell zum Erstellen von Gutscheinartikeln benötigen.

==== Gutscheinartikel mit festem Preis erstellen

Bei Gutscheinartikeln mit festem Preis erfolgt beim Kassieren keine Preisabfrage. Sie beschleunigen also den Kassiervorgang, sind aber auch weniger flexibel.

Beachten Sie bei vorhandenen Gutschein-Codes:

* Der Wert des vorhandenen Gutschein-Codes muss mit dem Preis des Artikels übereinstimmen. Der Gutscheinartikel muss also mit der Kampagne verknüpft sein, die die Gutschein-Codes mit den korrekten Werten enthält. Bei einer Kampagne pro Gutscheinwert wird also jede Kampagne mit nur einem Artikel verknüpft. Bei einer Kampagne mit verschiedenen Gutscheinwerten wird diese Kampagne mit mehreren Gutscheinartikeln verknüpft.

[.instruction]
Gutscheinartikel mit festem Preis erstellen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Klicken Sie auf **Neu**. +
→ Das Tab **Neuer Artikel** wird geöffnet.
. Wählen Sie den Typ **Standard**.
. Geben Sie einen Namen ein. +
*_Tipp_*: Der Name sollte den Gutscheinwert enthalten.
. Geben Sie als Inhalt **1 Stück** ein.
. Wählen Sie eine Kategorie.
. Wählen Sie einen Verkaufspreis aus der Dropdown-Liste. +
*_Hinweis_*: Der Verkaufspreis muss mit der Auftragsherkunft der Kasse verknüpft sein.
. Geben Sie als Preis den Gutscheinwert ein.
. **Speichern** Sie die Einstellungen. +
→ Der Artikel wird erstellt und zur weiteren Bearbeitung geöffnet.
. Nehmen Sie die weiteren Einstellungen vor. Beachten Sie <<tabelle-POS-verkaufsgutscheine-artikeleinstellungen>>.
. **Speichern** Sie die Einstellungen.

[#2600]
==== Gutscheinartikel mit flexiblem Wert erstellen

Gutscheinartikel mit flexiblem Wert sind Artikel mit einem Preis von 0,00 Euro. Den Preis, zu dem der Gutscheinartikel tatsächlich an der Kasse verkauft wird, steuern Sie auf zwei verschiedene Arten:

* Beim Kassieren gibt das Kassenpersonal einen in plentymarkets vorhandenen Gutschein-Code ein. Der Wert dieses Gutschein-Codes wird zum Preis des Artikels.
* Beim Kassieren generiert die Kassenbenutzerin entweder automatisch einen Code oder speichert einen eigenen Gutschein-Code und gibt einen Gutscheinwert ein.

[.instruction]
Gutscheinartikel mit flexiblem Preis erstellen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Klicken Sie auf **Neu**. +
→ Das Tab **Neuer Artikel** wird geöffnet.
. Wählen Sie den Typ **Standard**.
. Geben Sie einen Namen ein.
. Geben Sie als Inhalt **1 Stück** ein.
. Wählen Sie eine Kategorie.
. Wählen Sie einen Verkaufspreis aus der Dropdown-Liste. +
*_Hinweis_*: Der Verkaufspreis muss mit der Auftragsherkunft der Kasse verknüpft sein.
. Geben Sie als Preis **0,00** Euro ein.
. **Speichern** Sie die Einstellungen. +
→ Der Artikel wird erstellt und zur weiteren Bearbeitung geöffnet.
. Nehmen Sie die weiteren Einstellungen vor. Beachten Sie <<tabelle-POS-verkaufsgutscheine-artikeleinstellungen>>.
. **Speichern** Sie die Einstellungen. +
→ *_Mit vorhandenem Gutschein-Code:_* Das Kassenpersonal gibt den Gutschein-Code einer Kampagne ein, die mit dem Artikel verknüpft ist. Der Artikel wird mit dem Wert des Gutschein-Codes berechnet. +
→ *_Ohne vorhandenen Gutschein-Code:_* Das Kassenpersonal wird aufgefordert, einen Preis einzugeben, wenn der Artikel in den POS-Warenkorb gelegt wird.

[[tabelle-POS-verkaufsgutscheine-artikeleinstellungen]]
.Artikeleinstellungen für Verkaufsgutscheine mit festem und flexiblem Wert
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Einstellungen*

|**Aktiv**
|Option aktivieren.

|**Beschränkung**
|**Keine** wählen.

|**Umsatzsteuer**
|**0%** wählen.

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Verfügbarkeit*

|**Märkte**
|Kasse(n) aus der Dropdown-Liste wählen, über die die Gutscheinartikel verkauft werden sollen.

|**Mandant**
|Mandant der Kasse wählen.

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Felder*

|**Kampagne ID**
|ID der Gutscheinkampagne eingeben, um den Artikel mit der Kampagne zu verknüpfen.
|====

[#3800]
=== Berechtigungen für Gutscheinverkauf erteilen

Benutzer mit Admin-Rechten haben standardmäßig die Berechtigungen, Verkaufsgutschein zu erstellen. Benutzern der Benutzerklasse *Variabel* müssen diese Berechtigungen separat erteilt werden.

[.instruction]
Berechtigungen für Gutscheinverkauf erteilen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*.
. *_Optional:_* Geben Sie in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicken Sie auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicken Sie auf das gewünschte Konto. +
→ Die Ansicht *Rechte* wird geöffnet.
. Aktivieren Sie im Bereich *Berechtigungen* die folgenden Berechtigungen:
	** *Gutschein » Kampagne » Code » Code erstellen*
	** *Gutschein » Kampagne » Code » Code löschen*
	** *Gutschein » Kampagne » Code » Code anzeigen*
. *Speichern* Sie die Einstellungen.

[#2700]
=== Besonderheiten beim Verkauf von Verkaufsgutscheinen

* Der Umsatz erhöht sich beim Verkauf des Verkaufsgutscheins nicht.
* Verkaufte Gutscheine werden auf dem Tagesbericht separat ausgewiesen. Der Barbestand wird nur erhöht, wenn der Gutschein bar bezahlt wurde.

[#2800]
=== Besonderheiten beim Einlösen von Verkaufsgutscheinen

* Der Wert des Verkaufsgutscheins wird vom Gesamtbetrag inkl. Steuern abgezogen.
* Der Umsatz erhöht sich um den eingelösten Gutscheinbetrag.
* Auf dem Tagesbericht wird der eingelöste Gutscheinwert mit der Zahlungsart *Gutschein* ausgewiesen.
* Der Barbestand der Kasse erhöht sich durch die Einlösung des Gutscheins nicht.

[#3600]
== Retouren vorbereiten

In den Kasseneinstellungen wählen Sie einen Standard-Reparaturlagerort für Retouren und legen in den Berechtigungen fest, wer Retouren durchführen darf. Wenn Sie Retourenbeträge nur in bar auszahlen möchten, sind keine weiteren Einstellungen nötig, um Retouren über plentymarkets POS abzuwickeln. Beachten Sie die <<pos/pos-einrichten#2000, Hinweise zu Retouren>>. Wenn Sie die Möglichkeit haben möchten, den Retourenbetrag als Gutschein auszuzahlen, bereiten Sie außerdem <<pos/pos-einrichten#3100, Retourengutscheine>> vor.


[#2000]
=== Hinweise zu Retouren

Beachten Sie die folgenden Hinweise zu Retouren:

* Aus technischen Gründen können Retourenbeträge aktuell nur in bar ausgezahlt werden.
* Verkaufsgutscheine können nicht zurückgegeben werden.
* Über die Kasse können für alle im System gespeicherten Aufträge Retouren gebucht werden. Es können also auch Artikel aus Aufträgen mit anderen Herkünften zurückgegeben werden. Die Entscheidung, ob Artikel zurückgeben werden können, trifft das Kassenpersonal. Informieren Sie deshalb das Kassenpersonal, ob und wenn ja welche Herkünfte von der Retoure ausgeschlossen sind.
* Als Lagerort für Retourenartikel wird Kassenkräften standardmäßig der Lagerort angezeigt, der im Tab *Grundeinstellungen* der Kasse als *Standard-Reparturlagerort* festgelegt ist. Kassenkräfte können optional einen anderen Lagerort für die Retourenartikel wählen. Die möglichen Lagerorte werden in der folgenden Reihenfolge angezeigt:
  .. Lagerort aus Auftrag = Der Lagerort, an dem der Artikel lag, als er verkauft wurde.
  .. Standard-Reparaturlagerort = Der im Tab *Grundeinstellungen* der Kasse festgelegte *Reparturlagerort*.
  .. Lagerortvorschläge = Die Lagerortvorschläge der Lager, die mit der Variante verknüpft sind.
  .. Verwendete Lagerorte = Die Lagerorte, in denen die Variante bereits lagert.
Informieren Sie das Kassenpersonal darüber, an welchen Lagerort Retouren gebucht werden sollen.
* Bei Retouren für einen Hauptauftrag mit Versandkosten entscheidet das Kasselpersonal, ob die Versandkosten erstattet werden. Schulen Sie deshalb das Kassenpersonal, damit Ihre Belegschaft weiß, in welchen Fällen die Versandkosten erstatten werden sollen.
* Weisen Sie das Kassenpersonal an, zurückgegebene Artikel auf dem Kaufbeleg durchzustreichen. So verhindern Sie, dass Artikel mehrmals zurückgegeben werden.
* Bei Kauf auf Rechnung oder Anzahlungen bei einer Retoure erst Geld ausgehändigt, wenn der Preis der zurückgegebenen Artikel höher ist als der Betrag, der bisher bezahlt wurde.
* Der Retourenbetrag kann statt in bar auch in Form eines Gutscheins ausgezahlt werden. Wenn Sie diese Möglichkeit nutzen möchten, schulen Sie das Kassenpersonal, damit Ihre Belegschaft weiß, in welchen Fällen der Retourenbetrag in bar und in welchen Fällen der Betrag als Gutschein ausgezahlt werden soll.

[#3100]
=== Retourengutscheine vorbereiten

Statt den Retourenbetrag in bar auszuzahlen, kann ein Gutschein über den Retourenbetrag erstellt und ausgehändigt werden. Bei einer solchen Retoure wird der Retourenbetrag nur theoretisch ausgezahlt und sofort ein Gutschein über denselben Betrag gekauft. Bei einer Retoure mit Gutschein werden also eine Retoure, eine Gutschrift und ein neuer Auftrag erstellt.

Um Gutscheine für Retouren zu erstellen, sind die folgenden Vorbereitungen im plentymarkets Backend erforderlich:

* Gutscheinkampagne mit Gutscheinart *Verkaufsgutschein* erstellen.
* Gutscheinartikel mit 0% MwSt. erstellen und mit der Gutscheinkampagne verknüpfen.
* Gutscheinartikel für Retouren mit der Kasse verknüpfen.
* Variablen Benutzerkonten Berechtigungen erteilen.


Diese Schritte werden nachfolgend kurz erläutert. Eine detaillierte Anleitung zum Erstellen von Kampagnen und Gutscheinen finden Sie auf der Handbuchseite <<auftraege/gutscheine#, Gutscheine>>.


[#3200]
==== Kampagne für Gutscheine aus Retouren erstellen

Erstellen Sie eine Kampagne für Gutscheine aus Retouren.

[.instruction]
Kampagne für Gutscheine aus Retouren erstellen:

. Öffnen Sie das Menü *Aufträge » Gutscheine*.
. Klicken Sie auf *Neue Kampagne*.
. Nehmen Sie die Einstellungen vor. Beachten Sie <<tabelle-POS-retourenkampagne>>.
. *Speichern* Sie die Einstellungen. +
→ Die neue Kampagne wird erstellt und in der Übersicht angezeigt.

[[tabelle-POS-retourenkampagne]]
.Einstellungen für Gutscheine aus Retouren
[cols="1,2"]
|====
|Einstellung |Benutzereingabe

2+|Kampagne

|*Name*
|Namen für die Kampagne eingeben.

|*Beschreibung*
|Optional eine Beschreibung eingeben.

|*Konzept: Code*
|*Mehrere Codes* wählen.

|*Konzept: Einlösungen*
|*Einlösung bis Wert aufgebraucht ist* wählen.

|*Nutzung*
|*Einzelbestellungen* oder <<auftraege/scheduler#, Abonnements>> oder beides wählen.

|*Mindestbestellwert*
|Keinen Wert eingeben.

2+|Gültigkeiten

|*Startdatum*
|Das Datum, ab dem die Kampagne aktiv ist.

|*Enddatum*
|Das Datum, bis zu dem die Kampagne aktiv ist.

|*Code-Gültigkeit in Wochen*
|*0* eingeben.

2+|Gutschein

|*Gutscheintyp*
|*Gutschein* wählen.

|*Gutscheinart*
|*Verkaufsgutschein* wählen.

|*Code-Länge*
|Die Zeichenlänge des Gutschein-Codes wählen.

|*Rabattart*
|*Festbetrag* wählen.

|*Rabattwert*
|Einen Gutscheinwert eingeben, zum Beispiel 1,00.

|*Inkl. Versandkosten*
|Option nicht aktivieren.

2+|Filter

|*Artikel über Preisportale*
|*Nicht erlauben* wählen.

|*Kategorien*
|Die Kategorien wählen, in denen der Gutschein einlösbar sein soll. Die Auswahl gilt auch für alle Unterkategorien einer markierten Kategorie.

|*Artikel*
|Keinen Wert eingeben.

|*Mandanten (Shops)*
|Die Mandanten (Shops) wählen, für die die Gutscheine der Kampagne gelten sollen.

|*Kundenklassen*
|Die Kundenklassen wählen, für die die Gutscheine der Kampagne gelten sollen.

|*Kundentypen*
|Die Kundentypen wählen, für die die Gutscheine der Kampagne gelten sollen.
|====

[#3300]
==== Gutschein-Codes verwalten

Die Gutschein-Codes für Gutscheine aus Retouren verwalten Sie genauso wie andere Gutschein-Codes. Sie haben folgende Möglichkeiten:

* <<#2200, Die Kasse generiert automatisch einen Gutschein-Code.>>
* <<#2300, Die Kassenkraft gibt einen Code ein, der noch nicht in plentymarkets gespeichert ist.>>


[#4000]
==== Drucken und Speichern von Gutscheinbelegen aktivieren

Optional kann ein Gutscheinbeleg erstellt und gedruckt werden. Der Gutscheinbeleg enthält die folgenden Informationen zum Gutschein:

* Gutscheinwert
* Gutschein-Code
* Bei Teileinlösung:
	** Eingelöster Betrag
	** Restbetrag

[.instruction]
Drucken von Gutscheinbelegen aktivieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » POS*.
. Öffnen Sie die Kasse.
. Wechseln Sie in das Tab *Beleg*.
. Aktivieren Sie die Option *Gutscheinbeleg drucken und speichern*.
. **Speichern** Sie die Einstellungen. +
→ Beim Verkauf oder einer Teileinlösung eines Gutscheins wird ein Gutscheinbeleg erstellt. +
→ Der Gutscheinbeleg wird im Dokumentenarchiv gespeichert. +
→ Wenn die Option *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* aktiviert ist, wird der Gutscheinbeleg nach dem Kassenbeleg ausgedruckt. +
→ Wenn *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* nicht aktiviert ist, kann die Kassenbenutzerin den Gutscheinbeleg nach Abschluss des Auftrags manuell drucken. +
*_Hinweis:_* Beim Verkauf eines Gutscheins wird der Gutschein-Code unabhängig von der gewählten Einstellung immer auf dem normalen Kassenbeleg ausgegeben.

[#840]
==== Gutscheinartikel für Retouren erstellen

Erstellen Sie einen Gutscheinartikel mit einem Preis von 0,00 Euro. Hier werden nur die Einstellungen beschrieben, die Sie zum Erstellen von Gutscheinartikeln für Gutscheine aus Retouren benötigen.

[.instruction]
Gutscheinartikel für Retouren erstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Klicken Sie auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wählen Sie den Typ *Standard*.
. Geben Sie einen Namen ein.
. Geben Sie als Inhalt *1 Stück* ein.
. Wählen Sie eine Kategorie.
. Wählen Sie einen Verkaufspreis aus der Dropdown-Liste. +
*_Hinweis_*: Der Verkaufspreis muss mit der Auftragsherkunft der Kasse verknüpft sein.
. Geben Sie als Preis *0,00* Euro ein.
. *Speichern* Sie die Einstellungen. +
→ Der Artikel wird erstellt und zur weiteren Bearbeitung geöffnet.
. Nehmen Sie die weiteren Einstellungen vor. Beachten Sie <<tabelle-POS-retourengutscheine-artikeleinstellungen>>.
. *Speichern* Sie die Einstellungen.
. Notieren Sie sich die ID der Variante.

[[tabelle-POS-retourengutscheine-artikeleinstellungen]]
.Artikeleinstellungen für Gutscheine für Retouren
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Einstellungen*

|*Aktiv*
|Option aktivieren.

|*Beschränkung*
|*Keine* wählen.

|*Umsatzsteuer*
|*0%* wählen.

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Verfügbarkeit*

|*Märkte*
|Kasse(n) aus der Dropdown-Liste wählen.

|*Mandant*
|Mandant der Kasse wählen.

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Felder*

|*Kampagne ID*
|ID der Gutscheinkampagne eingeben, um den Artikel mit der Kampagne zu verknüpfen.
|====

[#3400]
==== Gutscheinartikel für Retouren mit Kasse verknüpfen

[.instruction]
Gutscheinartikel für Retouren mit Kasse verknüpfen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffnen Sie die Kasse. +
→ Das Tab *Grundeinstellungen* wird angezeigt.
. Aktivieren Sie die Option *Gutschein über Retourenbetrag erzeugen*. +
. Geben Sie in das Feld *Varianten-ID des Retourengutscheins* die Varianten-ID des Retourengutscheins ein. +
→ Der Gutscheinartikel wird bei Retouren automatisch gewählt.




[#3700]
==== Berechtigungen für Retourengutscheine erteilen

Personen mit Admin-Rechten haben standardmäßig die Berechtigung, Retourengutscheine zu erstellen. Konten der Benutzerklasse *Variabel* müssen diese Berechtigungen separat erteilt werden.

[.instruction]
Berechtigungen für Retourengutscheine erteilen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*.
. *_Optional:_* Geben Sie in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicken Sie auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicken Sie auf das gewünschte Konto. +
→ Die Ansicht *Rechte* wird geöffnet.
. Aktivieren Sie im Bereich *Berechtigungen* die folgenden Berechtigungen:
	** *Gutschein » Kampagne » Code » Code erstellen*
	** *Gutschein » Kampagne » Code » Code löschen*
	** *Gutschein » Kampagne » Code » Code anzeigen*
. *Speichern* Sie die Einstellungen.

[#3500]
==== Besonderheiten bei Gutscheinen aus Retouren

* Im Kassenjournal wird ein Gutschein aus einer Retoure als neuer Auftrag mit dem Vermerk *Aus Retoure erzeugter Gutschein* dargestellt. Wie bei der Barauszahlung wird eine Gutschrift erstellt. Der Barbestand wird für die Gutschrift reduziert, für den neuen Auftrag jedoch wieder erhöht und bleibt somit gleich.
* Auf dem Tagesbeleg wird auch ein als Gutschein ausgezahlter Retourenbetrag als Bar-Retoure aufgeführt.
* Gutscheine aus einer Retoure werden auf dem Tagesbericht als verkaufte Gutscheine ausgewiesen. Der Barbestand bleibt gleich.

[#4100]
== Abholen und Bezahlen von Online-Bestellungen vorbereiten (Click & Collect)

Über den Webshop, Marktplätze oder andere Herkünfte bestellte Ware kann auch entweder online bezahlt und im Ladengeschäft abgeholt oder im Ladengeschäft bezahlt und abholt werden.

Die folgenden Vorbereitungen sind POS-seitig nötig, wenn Sie Ihrer Kundschaft anbieten möchten, Online-Bestellungen im Laden abzuholen oder im Laden abzuholen und zu bezahlen:

* Aufträge können nur anhand der Auftrags-ID in die Kasse geladen werden. +
→ Stellen Sie sicher, dass Auftragsbestätigungen die Auftrags-ID enthalten. Weisen Sie Kund*innen explizit darauf hin, dass diese Auftrags-ID benötigt wird, um den Auftrag in der Filiale zu bearbeiten.
* Erklären Sie Ihren Kassenkräften, wie sie die Identität von Personen prüfen müssen, die bezahlte Ware im Ladengeschäft abholen. Sonst besteht Gefahr, dass Kassenkräfte die Ware an Unbefugte aushändigen.
* Sie nutzen Prozesse und/oder Ereignisaktionen, um Aufträge zu bearbeiten, die über den Webshop oder Marktplätze ins System gelangen? +
→ Prüfen Sie diese Ereignisaktionen und Prozesse, bevor Sie eine Abholung im Laden anbieten. Stellen Sie sicher, dass Aufträge erst in den Status *Warenausgang gebucht* gesetzt werden, wenn die Ware im Laden abgeholt wurde. +
→ Die Kasse zeigt an, dass die Ware übergeben wurde, wenn in plentymarkets ein Warenausgang für den Auftrag gebucht wurde. Falls Probleme auftreten und jemand darauf besteht, die Ware noch nicht erhalten zu haben, prüfen Sie den Auftrag im plentymarkets Backend. Möglicherweise wurde der Warenausgang zu früh automatisch gebucht.

Beachten Sie außerdem die folgenden Hinweise und Einschränkungen beim Abholen und Zahlen von Online-Bestellungen im Laden:

* Online-Aufträge können an der Kasse nicht bearbeitet werden. Das Kassenpersonal kann nur Zahlungen anlegen und Notizen zum Auftrag speichern. +
* Online-Aufträge können an der Kasse erst ab App-Version 1.9.2 mit Verkaufsgutscheinen bezahlt werden. Voraussetzung ist, dass für den Auftrag noch keine Zahlung durchgeführt wurde und noch kein Rechnungsdokument für den Auftrag erstellt wurde.
* Kassenkräfte können Online-Aufträge noch nicht an der Kasse stornieren.
* Zahlungen, die an der Kasse getätigt werden, um einen Online-Auftrag zu bezahlen, sind für die Kasse umsatzneutral. +
→ Im Kassenjournal werden Zahlungen, die nicht umsatzrelevant für die Kasse sind, als Kassenvorfall des Typs *Zahlung* gespeichert.
* Über die Option *Externer Auftrag: Warenausgang automatisch buchen* in den Kasseneinstellungen legen Sie fest, ob nach der Bezahlung an der Kasse die Ware automatisch aus dem Lager ausgebucht wird. Diese Option ist bei Kassen, die ab 05.03.2019 erstellt werden, standardmäßig aktiviert. Wenn Sie die Funktion deaktivieren, erklären Sie Ihren Kassenkräften, in welchen Fällen sie den Warenausgang manuell buchen sollen.

[#2900]
[#3000]
== Warenausgang automatisch buchen

Der Warenbestand wird nicht automatisch verringert, wenn Sie einen Artikel verkaufen. Erstellen Sie die unten beschriebene Ereignisaktion, um Waren automatisch auszubuchen, wenn ein Kassenauftrag erstellt wird. Weitere Informationen zum Verwalten von Warenbestand finden Sie auf der Handbuchseite <<warenwirtschaft/waren-ausbuchen#, Waren ausbuchen>>.

[.collapseBox]
.Buchen des Warenausgangs beim Erstellen eines Kassenauftrags
--
. Öffnen Sie das Menü **System » Systemeinstellungen » Aufträge » Ereignisse**.
. Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das **Ereignis** gemäß <<tabelle-POS-ereignisaktion-warenausgang-buchen>>.
. **Speichern** Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<tabelle-POS-ereignisaktion-warenausgang-buchen>> vor.
. Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--

[[tabelle-POS-ereignisaktion-warenausgang-buchen]]
.Ereignisaktion zum automatischen Buchen des Warenausgangs beim Erstellen eines Kassenauftrags
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Dokumente: Kassenbeleg generiert**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|Kassen wählen, für die Warenausgang gebucht werden soll.

|**Aktion**
|**Auftrag &gt; Warenausgang buchen**
|
|====

[#600]
== plentymarkets App auf dem Gerät installieren

Installieren Sie nun die plentymarkets App auf dem Gerät, auf dem die Kasse betrieben werden soll.

* link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=de[plentymarkets App bei Google Play^]

* link:https://itunes.apple.com/de/app/plentymarkets/id957702618[plentymarkets App bei iTunes^]

[WARNING]
.Offline-Aufträge werden beim Deinstallieren der App gelöscht
====
Bei fehlender Internetverbindung werden Aufträge offline gespeichert und erst später synchronisiert. Wenn Sie die App deinstallieren, bevor die Aufträge an plentymarkets übertragen wurden, werden die lokal gespeicherten Aufträge unwiederbringlich gelöscht und können auch vom plentymarkets Support nicht wiederhergestellt werden. Prüfen Sie deshalb vor jedem Deinstallieren der App, dass keine Offline-Aufträge auf dem Gerät vorhanden sind.
====

[#230]
== Kasse mit Gerät verbinden

Verbinden Sie nun die Kasse mit dem Gerät, auf dem die Kasse betrieben werden soll.

=== Kasse mit Gerät koppeln

Gehen Sie wie unten beschrieben vor, um eine Kasse mit dem Gerät zu koppeln, auf dem die Kasse betrieben werden soll.

[IMPORTANT]
.Automatische Datum- und Zeiteinstellung aktivieren
====
Damit Kassenaufträge und Tagesabschlüsse mit dem plentymarkets Backend korrekt synchronisiert werden, müssen Datum und Uhrzeit des Geräts korrekt eingestellt sein. Deshalb wird empfohlen, das Datum und die Uhrzeit des Geräts automatisch einstellen zu lassen, damit keiner zeitlichen Unstimmigkeiten in den Tagesabschlüssen auftreten.
====

[.instruction]
Kasse mit Gerät koppeln:

. Öffnen Sie die plentymarkets App auf dem Gerät, das Sie mit der Kasse koppeln möchten.
. Öffnen Sie das Menü **plentymarkets App » Einstellungen » POS**.
. Nehmen Sie die Einstellungen vor. Beachten Sie <<tabelle-POS-geraet-koppeln>>.
. **Speichern** Sie die Einstellungen. +
→ Das Gerät wird mit der Kasse gekoppelt.

[[tabelle-POS-geraet-koppeln]]
.Kasse mit Gerät koppeln
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Mandant**
|Mandant wählen, für den die Kasse erstellt wurde.

|**POS**
|Kasse wählen.

|**Preis**
|Wählen, ob Aufträge brutto oder netto erstellt werden sollen.

|**Bondrucker**
|IP-Adresse des Bondruckers eingeben. +
**__Tipp:__** Auf **Testbeleg drucken** tippen, um einen Testbeleg zu drucken.

|**Drucker**
|Optional können über das Plugin plentyBase <<1000, weitere Drucker>> angebunden werden.

|**Automatisches Drucken**
|**Ein** = Standardeinstellung. Belege werden automatisch gedruckt, wenn ein Vorgang abgeschlossen wurde. +
**Aus** =  Das Drucken von Belegen muss manuell ausgelöst werden.

|**Darstellung** +
(nur Tablets)
|**Smartphone** =  Für Smartphones optimierte Darstellung; Hoch- oder Querformat. +
**Tablet** = Für Tablets optimierte Darstellung; nur Querformat.

|**Startbeleg erstellen** +
(nur neue Kassen mit Standort Österreich)
|Wählen, um den <<pos/pos-einrichten#900, Startbeleg  zu erstellen>> und so die manipulationssichere Sicherheitseinrichtung für die Kasse zu aktivieren. Nachdem der Startbeleg erstellt wurde, kann das Standortland der Kasse nicht mehr geändert werden.

|**Endbeleg erstellen** +
(nur Kassen mit Standort Österreich und aktivierter Sicherheitseinrichtung)
|Wählen, um <<pos/pos-einrichten#920, den Endbeleg zu erstellen>> und so die manipulationssichere Sicherheitseinrichtung für die Kasse zu deaktivieren. Nachdem der Endbeleg erstellt wurde, kann die Kasse nicht mehr verwendet werden.
|====

[#240]
=== Kasse von Gerät entkoppeln

Sie haben die Möglichkeit, die Koppelung einer Kasse mit dem Gerät aufzuheben. Stattdessen können Sie entweder eine andere Kasse mit dem Gerät verbinden oder keine Kasse wählen.

[.instruction]
Kasse von Gerät entkoppeln:

. Öffnen Sie die plentymarkets App.
. Öffnen Sie das Menü **plentymarkets App » Einstellungen » POS**.
. Wählen Sie für die Einstellung **POS** eine andere Kasse oder wählen Sie den leeren Eintrag.
. **Speichern** Sie die Einstellungen. +
→ Das Gerät wird von der Kasse entkoppelt.

[IMPORTANT]
.Entkoppelung der Kasse nur auf dem Gerät möglich
====
Sie können die Kasse nur über die Einstellungen auf dem Gerät von der Kasse entkoppeln. Wenden Sie sich bei einem Verlust oder Defekt des Geräts an den plentymarkets Support, um die Koppelung aufzuheben.
====

[#250]
== Senden des Kassenbelegs an Bestandskunden einrichten

plentymarkets ermöglicht Ihnen, Kassenbelege per Ereignisaktion automatisch an die am Kundendatensatz gespeicherte E-Mail-Adresse zu senden. Dazu erstellen Sie zunächst eine E-Mail-Vorlage mit dem PDF-Anhang **Kassenbeleg**. Erstellen Sie dann eine Ereignisaktion. Für Kassenaufträge, die im Offline-Modus erstellt werden, wird die Ereignisaktion jedoch erst ausgeführt, wenn die Kassenaufträge in das plentymarkets Backend hochgeladen werden. Prüfen Sie die aktuellen gesetzlichen Bestimmungen zum Versand von E-Mails, bevor Sie die Ereignisaktion aktivieren.

[#260]
=== E-Mail-Vorlage erstellen

Erstellen Sie zunächst eine <<crm/e-mails-versenden#1200, E-Mail-Vorlage>>, die versendet wird, wenn ein Kassenbeleg generiert wird.

[.instruction]
E-Mail-Vorlage erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen**.
. Klicken Sie auf **Neue E-Mail-Vorlage**. +
→ Das Fenster **Neue E-Mail-Vorlage** wird geöffnet.
. Geben Sie einen Namen für die Vorlage ein.
. Wählen Sie einen Eigner oder **Alle** aus der Dropdown-Liste **Eigner**.
. Klicken Sie auf **Speichern**. +
→ Die E-Mail-Vorlage wird erstellt und je nach gewähltem Eigner in einem der drei Ordner gespeichert.
. Wählen Sie den PDF-Anhang **Kassenbeleg**.
. Nehmen Sie die weiteren Einstellungen vor. Beachten Sie die Erläuterungen unter <<crm/e-mails-versenden#1200, Neue E-Mail-Vorlage erstellen>>.
. **Speichern** Sie die Einstellungen.

[#270]
=== Ereignisaktion für automatischen E-Mail-Versand erstellen

Erstellen Sie nun eine Ereignisaktion, über die die E-Mail-Vorlage versendet wird, wenn ein Kassenbeleg generiert wird.

[.collapseBox]
.Ereignisaktion für automatischen E-Mail-Versand erstellen
--
. Öffnen Sie das Menü **System » Systemeinstellungen » Aufträge » Ereignisse**.
. Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das **Ereignis** gemäß <<tabelle-POS-ereignisaktion-beleg-senden>>.
. **Speichern** Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<tabelle-POS-ereignisaktion-beleg-senden>> vor.
. Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--

[[tabelle-POS-ereignisaktion-beleg-senden]]
.Ereignisaktion zum automatischen Senden des Kassenbelegs
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Dokumente: Kassenbeleg generiert**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag** +
**Retoure**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|Kasse wählen, für die Kassenbelege per E-Mail versendet werden sollen.

|**Aktion**
|**Kunde &gt; E-Mail versenden**
|**Vorlage**: Die E-Mail-Vorlage für Kassenbeleg wählen +
**Empfänger**: Option **Kunde** wählen
|====

[#1000]
== Druck von Kassenbelegen über andere Drucker einrichten

Standardmäßig werden alle Kassenbelege über den Bondrucker gedruckt, den Sie im Menü *plentymarkets App » Einstellungen » POS* über die Option *Bondrucker* festlegen. Zusätzlich können Sie aber Kassenbelege auch auf anderen Druckern ausdrucken. Zum Beispiel kann es sinnvoll sein, Belege auf einem DIN-A4-Drucker statt auf Thermopapier zu drucken, die länger aufbewahrt werden müssen.

Um zusätzliche Drucker zu nutzen, benötigen Sie einen im Netzwerk zugänglichen Rechner, der mit einem oder mehreren Druckern verbunden ist, über die Sie die Kassenbelege drucken möchten. Auf diesem Rechner installieren Sie das Plugin link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyBase^]. plentyBase dient dazu, eine Verbindung zwischen der plentymarkets App und dem lokalen Rechner herzustellen. So kann die Kasse auf die Drucker zugreifen, auf die auch der lokale Rechner zugreifen kann. Im plentymarkets Backend konfigurieren Sie diese Drucker im Menü *System » Systemeinstellungen » Einstellungen » Drucker*.

[TIP]
.Bondrucker läuft ohne plentyBase
====
Der Bondrucker wird über die IP-Adresse des Druckers an die plentymarkets App angebunden. Deshalb ist plentyBase für die Nutzung des Bondruckers nicht erforderlich. Sie benötigen plentyBase also nur, wenn Sie andere Drucker an plentymarkets POS anbinden möchten.
====

[#1010]
=== plentyBase installieren und einrichten

plentyBase ist ein von plentymarkets entwickeltes Plugin. Anders als die meisten anderen plentymarkets Plugins wird plentyBase jedoch nicht im plentymarkets Backend aktiviert. Stattdessen wird plentyBase auf einem lokalen Rechner installiert und ausgeführt. plentyBase stellt eine Schnittstelle bereit, über die Sie aus dem plentymarkets Backend und/oder der plentymarkets App die Drucker nutzen können, die an den Computer angeschlossen sind.

Damit die Drucker in der plentymarkets App verfügbar sind, müssen die folgenden Vorraussetzungen erfüllt sein:

* plentyBase muss auf dem Rechner installiert sein. +
→ Die Installationsdatei laden Sie im link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyMarketplace^] herunter.
* plentyBase muss auf dem Rechner konfiguriert sein. +
→ Die Konfigurationsanleitung finden Sie in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyBase^]. +
*_Hinweis:_* Aktivieren Sie beim Konfigurieren die Option *HTTP-Server*. Nur so kann plentymarkets POS mit plentyBase kommunizieren.
* plentyBase muss auf dem Rechner gestartet sein. +
*_Empfehlung:_* Konfigurieren Sie plentyBase so, dass plentyBase beim Starten des Rechners automatisch gestartet wird.
* Die Verbindungsdaten von plentyBase müssen in der plentymarkets App gespeichert sein. +
→ Wie Sie die plentyBase Verbindungsdaten in der App speichern, erfahren Sie in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053#140.[plentyBase^].
* Die Drucker müssen im plentymarkets Backend im Menü *System » Systemeinstellungen » Einstellungen » Drucker* konfiguriert sein.

[#1020]
=== Drucker für Kassenbelege speichern

Nachdem Sie plentyBase eingerichtet haben, können Sie im Menü *plentymarkets App » Einstellungen » POS* im Bereich *Drucker* die im plentymarkets Backend konfigurierten Drucker wählen.

Gehen Sie wie unten beschrieben vor, um festzulegen, welche Kassenbelege über welchen Drucker gedruckt werden sollen.

[.instruction]
Drucker pro Belegart festlegen:

. Öffnen Sie die plentymarkets App.
. Öffnen Sie das Menü *plentymarkets App » Einstellungen » POS*.
. Nehmen Sie im Bereich *Drucker* die Einstellungen vor. Beachten Sie <<tabelle-POS-drucker>>.
. **Speichern** Sie die Einstellungen.

[[tabelle-POS-drucker]]
.Drucker für Kassenbelege festlegen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Standard-Drucker*
|In der Dropdown-Liste den Standard-Drucker für die Kasse wählen. Standardmäßig ist der Bondrucker vorausgewählt. +
*_Hinweis:_* In der Dropdown-Liste werden der Bondrucker und die Drucker im Netzwerk angezeigt, auf die die Kasse Zugriff hat.
Wenn in der Dropdown-Liste außer dem Bondrucker und dem Standarddrucker keine Drucker angezeigt werden, wird es Zeit für ein <<1040, Troubleshooting>>.

|*Kaufbeleg*; +
*Tagesabschluss*; +
*Zwischenbericht*; +
*Kassensturz*; +
*Stornierungsbeleg*; +
*Einlage und Entnahme*; +
*Gutscheinbeleg*; +
*Retourenbeleg*; +
*Gutschriftbeleg*
|Der Standard-Drucker ist vorausgewählt. Wenn alle Kassenbelege auf dem Standard-Drucker gedruckt werden sollen, sind keine weiteren Einstellungen erforderlich. Sonst in den Dropdown-Listen der einzelnen Kassenbelege den Drucker wählen, auf dem der Beleg gedruckt werden soll. +
*_Hinweis:_* In den Dropdown-Listen werden der Bondrucker und die Drucker im Netzwerk angezeigt, auf die die Kasse Zugriff hat.
Wenn in den Dropdown-Listen außer dem Bondrucker und dem Standarddrucker keine Drucker angezeigt werden, wird es Zeit für ein <<1040, Troubleshooting>>.
|====

[#1060]
=== Testseite drucken

Gehen Sie wie unten beschreiben vor, um eine Testseite zu drucken.

[.instruction]
Testseite drucken:

. Öffnen Sie die plentymarkets App.
. Öffnen Sie das Menü *plentymarkets App » Einstellungen » POS*.
. Tippen Sie oben rechts auf das Menü-Symbol.
. Tippen Sie auf *Testdruck*. +
→ Das Fenster *Testdruck* wird angezeigt.
. Wählen Sie in der Dropdown-Liste den Beleg, für den Sie das Drucken testen möchten.
. Tippen Sie auf *Testseite drucken*. +
→ Eine Testseite wird gedruckt. +
→ Wenn keine Testseite gedruckt wird, prüfen Sie die Einstellungen wie im <<1050, Troubleshooting-Fall 2>> beschrieben.

[#1030]
=== Troubleshooting: Fehler bei Druckern

[#1040]
==== Fall 1: In den Kasseneinstellungen können keine Drucker gewählt werden

Sie haben bisher noch keine zusätzlichen Drucker in den POS-Einstellungen gespeichert. In den Dropdown-Listen des Bereichs *Drucker* werden außer dem Bondrucker und dem Standard-Drucker keine Drucker angezeigt. Bondrucker und Standard-Drucker sind in diesem Fall identisch.

* Ist plentyBase auf einem Rechner im Netzwerk installiert? +
→ Die Installationsdatei laden Sie im link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyMarketplace^] herunter.
* Wurde plentyBase korrekt konfiguriert? +
→ Die Konfigurationsanleitung finden Sie in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyBase^]. +
*_Tipp:_* Wurde die Option *HTTP-Server* aktiviert und ein HTTP-Port angegeben?
* Wurden die plentyBase Einstellungen in der App gespeichert? +
→ Wie Sie die plentyBase Verbindungsdaten in der App speichern, erfahren Sie in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053#140.[plentyBase^]. +
*_Tipp:_* Wurde der richtige HTTP-Port in der App gespeichert?
* Ist plentyBase auf dem Rechner gestartet? +
*_Empfehlung:_* Konfigurieren Sie plentyBase so, dass plentyBase beim Starten des Rechners automatisch gestartet wird.
* Wurde der Drucker im plentymarkets Backend <<basics/admin-aufgaben/drucker#, gespeichert und konfiguriert>>?

[#1050]
==== Fall 2: Drucker sind in den Kasseneinstellungen gespeichert, aber nicht erreichbar

Der Drucker wurde für den Druck einer oder mehrerer Belege ausgewählt und die Einstellungen gespeichert. Der Drucker ist aber nun mit einem Dreieck gekennzeichnet und nicht erreichbar.

* Ist der Rechner an, auf dem plentyBase installiert ist?
* Ist der Drucker an und funktionsbereit?
* Ist der Drucker mit dem Rechner verbunden?
* Ist plentyBase auf dem Rechner gestartet?
* Wurden die plentyBase Konfigurationseinstellungen vor kurzem geändert, zum Beispiel der HTTP-Port oder der Access Token? +
→ Wenn ja, wurden die neuen Einstellungen in der plentymarkets App gespeichert?
* Wurde die Druckerkonfiguration aus dem plentymarkets Backend entfernt? +
→ Drucker konfigurieren Sie im Menü *System » Systemeinstellungen » Einstellungen » Drucker*.

[#1090]
== Druck von Artikeletiketten einrichten

Wie Sie Etikettenvorlagen erstellen und Artikeletiketten in der Artikelsuche der plentymarkets App drucken, erfahren Sie unter <<artikel/artikel-verwalten#760, Etiketten einrichten>>.

[IMPORTANT]
.plentyBase konfigurieren
====
Um Etiketten drucken zu können, benötigen Sie das kostenlose Plugin plentyBase. plentyBase stellt eine Schnittstelle bereit, über die Sie aus dem plentymarkets Backend und/oder der plentymarkets App die Drucker nutzen können, die an den Computer angeschlossen sind. Wie Sie plentyBase installieren und konfigurieren erfahren Sie in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyBase^].
====


[#400]
== Kassenvorgänge im Kassenjournal suchen

Alle Kassenvorgänge werden in plentymarkets dokumentiert. Im Menü **Aufträge » POS » Kassenjournal** können Sie Kassenvorgänge suchen, anzeigen und bei Bedarf exportieren. Mit den Filtern des Tabs **Filter** grenzen Sie die im Kassenjournal angezeigten Kassenvorgänge anhand bestimmter Kriterien ein. Die gefundenen Kassenvorgänge werden im Tab **Kassenjournal** aufgelistet. Die Ergebnisse sind standardmäßig nach dem Datum sortiert. Gehen Sie wie unten beschrieben vor, um Kassenvorgänge im Kassenjournal zu suchen.

[.instruction]
Kassenvorgänge im Kassenjournal suchen:

. Öffnen Sie das Menü **Aufträge » POS » Kassenjournal**.
. Wählen Sie die Filter. Beachten Sie die Erläuterungen in <<tabelle-POS-kassenjournal-menue>>.
. Klicken Sie auf **Suchen**. +
→ Die Kassenvorgänge, die den Suchkriterien entsprechen, werden im Tab **Kassenjournal** aufgelistet.

[[tabelle-POS-kassenjournal-menue]]
.Menü *Kassenjournal*
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Tab: Filter

|*Suchen*
|Ohne Filtereinstellungen auf *Suchen* klicken, um alle Kassenvorgänge anzuzeigen. +
*_Oder:_* Die Suchergebnisse durch Filtereinstellungen eingrenzen und auf *Suchen* klicken. Die gefundenen Kassenvorgänge werden im Tab *Kassenjournal* aufgelistet.

|**Reset**
|Eingestellte Filterkriterien zurücksetzen.

|**Belegnummer: von**; +
**Belegnummer: bis**
|Die Belegnummer des ersten und des letzten Belegs eingeben, um Kassenvorgänge einer bestimmten Belegabfolge anzuzeigen. Um nur einen Beleg anzuzeigen, die gesuchte Belegnummer in die Felder **Belegnummer: von** und **Belegnummer: bis** eingeben.

|**Kasse**
|Eine Kasse aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieser Kasse einzugrenzen.

|**Mandant**
|Einen Mandanten (Shop) aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieses Mandanten einzugrenzen.

|**Benutzer**
|Einen Benutzer aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieser Kassenkraft einzugrenzen.

|**Zahlungsart**
|Eine Zahlungsart aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge mit dieser Zahlungsart einzugrenzen. Die Dropdown-Liste enthält nur aktive Zahlungsarten.

|**Zeitraum**
|Eine Zeitspanne wählen, um die angezeigten Kassenvorgänge auf diesen Zeitraum zu beschränken. +
Um Belege eines benutzerdefinierten Zeitraums anzuzeigen, die Option **Datumsauswahl** wählen und im Feld **von** das Startdatum und im Feld **bis** das Enddatum eingeben oder aus dem angezeigten Kalender wählen.

|**Typ**
|Einen Typ aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieses Typs einzugrenzen.

2+|Tab: Kassenjournal

|**Datum**
|Datum und Uhrzeit des Kassenvorgangs

|**Vorgang**
|Zeigt an, ob der Vorgang eine Einnahme (**E**) oder eine Ausgabe (**A**) ist.

|**Betrag**
|Der Wert des Kassenvorgangs

|**Belegnummer**
|Die fortlaufende Nummer des Belegs, der für den Kassenvorgang erstellt wurde. Auf die Belegnummer klicken, um den Beleg im PDF-Format zu öffnen.

|**Typ**
|Der Typ des Kassenvorgangs

|**Barbestand**
|Der Barbestand der Kassen nach Abschluss des Kassenvorgangs

|**Auftrags-ID**
|Die ID des in plentymarkets erstellten Auftrags

|**Steuersatz**
|Die Steuersätze, die für diesen Auftrag zum Tragen kommen.

|**USt.**
|Die im Auftragswert enthaltene Umsatzsteuer

|**Buchungstext**
|Der Buchungstext für den Kassenvorgang. Bei Einlagen und Entnahmen entspricht der Buchungstext dem Grund der Bargeldbewegung.
|====

[#300]
== Kassenvorgänge in Deutschland rechtssicher belegen

Für eine ordnungsgemäße Kassenführung in Deutschland müssen alle Kassenvorgänge elektronisch und unveränderbar aufgezeichnet und für die Dauer des Aufbewahrungszeitraums digital lesbar archiviert werden. Damit Sie diesen gesetzlichen Anforderungen nachkommen können, stellt plentymarkets verschiedene Exportfunktionen bereit. Besprechen Sie mit Ihrem Steuerberater, welche Daten Sie exportieren und archivieren sollten, um rechtssicher zu arbeiten.

=== Kassenvorgänge als PDF-/CSV-Datei exportieren

Die im Kassenjournal angezeigten Kassenvorgänge können Sie entweder als PDF-Datei oder als CSV-Datei exportieren. Exportiert werden die über die Suche gefilterten Kassenvorgänge. Gehen Sie wie unten beschrieben vor, um Kassenvorgänge zu exportieren. Nachdem Sie einen Exportvorgang gestartet haben, ist das Starten weiterer Kassenjournalexporte zwei Minuten lang nicht möglich.

[.instruction]
Kassenvorgänge als PDF-Datei exportieren:

. Öffnen Sie das Menü **Aufträge » POS » Kassenjournal**.
. Wählen Sie die Filter. Beachten Sie die Erläuterungen in <<tabelle-POS-kassenjournal-menue>>.
. Klicken Sie auf **Suchen**. +
→ Die Kassenvorgänge, die den Suchkriterien entsprechen, werden im Tab **Kassenjournal** aufgelistet.
. Klicken Sie auf **PDF-Export**. +
→ Eine PDF-Datei der gefilterten Kassenvorgänge wird generiert. Abhängig von der Anzahl der Datensätze kann dieser Vorgang mehrere Minuten dauern. +
→ Die PDF-Datei wird in einem separaten Browser-Fenster angezeigt.
. **Speichern** Sie die PDF-Datei.

[.instruction]
Kassenvorgänge als CSV-Datei exportieren:

. Öffnen Sie das Menü **Aufträge » POS » Kassenjournal**.
. Wählen Sie die Filter. Beachten Sie die Erläuterungen in <<tabelle-POS-kassenjournal-menue>>.
. Klicken Sie auf **Suchen**. +
→ Die Kassenvorgänge, die den Suchkriterien entsprechen, werden im Tab **Kassenjournal** aufgelistet.
. Klicken Sie auf **CSV-Export**.
. Wählen und bestätigen Sie einen Speicherort für die CSV-Datei. +
→ Eine CSV-Datei der gefilterten Kassenvorgänge wird generiert. Abhängig von der Anzahl der Datensätze kann dieser Vorgang mehrere Minuten dauern. +
→ Die CSV-Datei wird gespeichert.

[#500]
=== IDEA-Export erstellen

Laut den deutschen handels- und steuerrechtlichen Ordnungsvorschriften (GoBD) müssen Sie bei einer Außenprüfung auf Verlangen der Finanzverwaltung nicht nur aufzeichnungs- und aufbewahrungspflichtige Daten vorlegen, sondern auch alle zur Auswertung der Daten notwendigen Strukturinformationen in maschinell auswertbarer Form bereitstellen. Deshalb stellt plentymarkets einen GoBD-konformen Export der Kassenvorgänge bereit. Die Exportdateien ermöglichen Betriebsprüfern, Ihre Kassendaten vollständig und effizient auszuwerten. Gehen Sie wie unten beschrieben vor, um einen IDEA-Export zu erstellen:

[.instruction]
IDEA-Dateien exportieren:

. Öffnen Sie das Menü **Aufträge » POS » IDEA-Export**.
. Wählen Sie das Kalenderjahr, für das Sie die Daten exportieren möchten.
. Klicken Sie auf das Zahnrad, um den Export zu generieren. +
→ Der Export wird über Nacht generiert. +
→ Der Export ist abgeschlossen, wenn der Status **Fertig** angezeigt wird.
. Klicken Sie auf das Download-Symbol in der Spalte **Aktionen**.
. Wählen Sie einen Speicherort und bestätigen Sie die Auswahl. +
→ Die IDEA-Dateien werden exportiert und als ZIP-Datei gespeichert.

[#960]
== Kassenaufträge im plentymarkets Backend ändern

Für Kassenaufträge wird ein Auftrag im plentymarkets Backend erstellt. Nach dem Erstellen des Auftrags können keine nachträglichen Änderungen von rechtlich relevanten Auftragsdaten vorgenommen werden. Ausgenommen hiervon sind Auftragsdaten, die sich im Rahmen der Bearbeitung und Erfüllung von Aufträgen ändern bzw. deren Historie dokumentieren:

* Sprache
* Status
* Bezahlter Betrag
* Zahlungsstatus
* Retourengründe
* Auftrag lässt sich Sammelauftrag zuordnen
* Lieferanschrift
* E-Mail-Versand
* Auftragsnotiz
* Versanddatum
* Rückgabedatum

[#910]
== Kasse außer Betrieb nehmen

Löschen Sie eine Kasse, die Sie nicht mehr benötigen, um diese Kasse dauerhaft außer Betrieb zu nehmen. Die Geschäftsvorfälle, die über die Kasse abgewickelt wurden, bleiben im System gespeichert und können weiter steuerrechtlich ausgewertet werden.

[NOTE]
.Besonderheit bei Kassenstandort Österreich
====
Bei Kassen mit Standort Österreich, bei denen die Sicherheitseinrichtung aktiviert wurde, muss der Endbeleg in der App erstellt werden, um die Kasse dauerhaft außer Betrieb zu nehmen. Dadurch wird die Kasse automatisch gelöscht.
====

[.instruction]
Kasse löschen:

. Öffnen Sie das Menü **Einstellungen » Mandant » Standard » POS**.
. Klicken Sie auf die Kasse. +
→ Das Tab **Grundeinstellungen** der Kasse wird geöffnet.
. Klicken Sie oben links auf **Löschen**. +
→ Die Kasse wird gelöscht. +
**__Hinweis:__** Bei Kassen mit Standort Österreich und aktivierter Sicherheitseinrichtung muss der <<pos/pos-einrichten#920, Endbeleg in der App>> erstellt werden. Dadurch wird die Kasse automatisch gelöscht.

[#860]
== plentymarkets POS in Österreich nutzen

Laut Registrierkassensicherheitsverordnung (RKSV) müssen Registrierkassen in Österreich mit einer technischen Sicherheitseinrichtung ausgestattet sein, die dafür sorgt, dass die über die Kasse abgewickelten Kassenvorgänge manipulationssicher, also nicht mehr veränderbar sind. Sichtbares Zeichen für diesen Manipulationsschutz ist der QR-Code auf dem Kassenbeleg. Hier erfahren Sie, wie Sie Kassen in Betrieb nehmen und nutzen, die in Österreich betrieben werden sollen.

[#870]
=== Übersicht: Inbetriebnahme der Kasse

Für Kassen mit Standort Österreich sind die in <<tabelle-inbetriebnahme-kasse-österreich>> erläuterten Schritte notwendig, um die von der RKSV vorgeschriebene Sicherheitseinrichtung in Betrieb zu nehmen. Detaillierte Informationen zu diesen rechtlichen Anforderungen finden Sie auf der Website des österreichischen link:https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/Sicherheitseinrichtung_in_Registrierkassen.html[Bundesministeriums für Finanzen^]. Auf dieser Handbuchseite werden nur die Schritte beschrieben, die erforderlich sind, um eine plentymarkets POS Kasse mit Standort Österreich in Betrieb zu nehmen. Die Beschreibung ersetzt keine rechtliche und steuerrechtliche Beratung.

[[tabelle-inbetriebnahme-kasse-österreich]]
.Kasse in Österreich in Betrieb nehmen
[cols="1,2,3"]
|====
|Reihen- folge |Schritt |Erläuterung

|1.
|Signaturkarte und Signaturkartenleser beschaffen
a|* plentymarkets POS ist für den Einsatz mit dem Feitian Smartcard-Leser link:http://www.cryptoshop.com/feitian-br301-bluetooth-reader.html[bR301^] optimiert.
* plentymarkets testet mit den Signaturkarten des Vertrauensdiensteanbieters link:https://www.prime-sign.com/[PrimeSign^].

|2.
|Manipulationssichere Registrierkasse initialisieren
|Siehe <<pos/pos-einrichten#50, Grundeinstellungen der Kasse vornehmen>>

|3.
|Startbeleg erstellen
|Siehe <<pos/pos-einrichten#900, Startbeleg erstellen>>

|4.
|Signaturkarte und Registrierkasse bei FinanzOnline registrieren
a|Nachdem der Startbeleg erstellt wurde, registrieren Sie Signaturkarte und Registrierkasse bei FinanzOnline. Für die Registrierung benötigen Sie die folgenden Daten: +

Signaturkarte (Unterlagen der Signaturkarte): +

* Die Seriennummer des Signaturzertifikats
* Den Namen des Vertrauensdiensteanbieters, bei dem das Zertifikat erworben wurde
* Die PIN des Signaturzertifikats

Registrierkasse (**Einstellungen » Mandant » Standard » POS » Kasse öffnen » Tab: Grundeinstellungen**): +

* Die Kassenidentifikationsnummer der plentymarkets POS Kasse. Die **Kassenidentifikationsnummer** finden Sie im Menü **Einstellungen » Mandant » Standard » POS » Kasse öffnen » Tab: Grundeinstellungen**.
* Den **Benutzerschlüssel AES-256**, der im Menü **Einstellungen » Mandant » Standard » POS » Kasse öffnen » Tab: Grundeinstellungen** angezeigt wird.

|5.
|Startbeleg mit der BMF-Belegcheck-App scannen
|Scannen Sie den QR-Code auf dem Startbeleg der Kasse, nachdem Sie die Registrierung bei FinanzOnline abgeschlossen haben. Die App prüft dabei die Gültigkeit der Signatur auf den Belegen der Registrierkasse. +
**__Tipp:__** Zwischen dem Zeitpunkt der Registrierung von Signaturkarte und Registrierkasse über FinanzOnline und der Prüfung des Startbelegs darf nicht mehr als eine Woche liegen.
|====

[IMPORTANT]
.Existierende Kassen mit Standort Österreich
====
Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Wenn Sie bereits eine plentymarkets POS Kasse in Österreich betreiben, erstellen Sie eine neue Kasse und nehmen die alte Kasse außer Betrieb.
====

[#900]
=== Startbeleg erstellen (Standort Österreich)

Erstellen Sie nun den Startbeleg, um die Kasse in Betrieb zu nehmen. Sie benötigen die PIN für das Signaturzertifikat des Vertrauensdiensteanbieters, um den Startbeleg zu erstellen. Den Startbeleg erstellen Sie im POS-Menü der plentymarkets App. Nachdem der Startbeleg erstellt wurde, kann das Standortland der Kasse nicht mehr geändert werden.

[.instruction]
Startbeleg erstellen:

. Öffnen Sie die plentymarkets App.
. Öffnen Sie das Menü **plentymarkets App » Einstellungen » POS**.
. Geben Sie die PIN für das Signaturzertifikat des Vertrauensdiensteanbieters ein.
. Tippen Sie auf **Startbeleg erstellen**. +
→ Der Startbeleg wird gedruckt. +
→ Der Startbeleg wird im Kassenjournal und im Dokumentenarchiv gespeichert. +
→ Die Kasse kann in Betrieb genommen werden. +
→ Belege werden signiert und der QR-Code auf Belegen ausgegeben. +
→ Kassenvorgänge werden DEP-konform im System gespeichert.

[#880]
=== Kassenvorgänge in Österreich belegen

Laut der österreichischen Registrierkassensicherheitsverordnung (RKSV) müssen Belege signiert und mit einem QR-Code versehen werden. Dieser QR-Code enthält die wesentlichen Beleginhalte, einen verschlüsselten Umsatzzähler und einen Verweis auf den letzten Beleg. Dieser Verweis sorgt dafür, dass die vorhergehenden Belege nicht mehr verändert oder gelöscht werden können. Außerdem muss für jede Registrierkasse ein Datenerfassungsprotokoll geführt werden, das jederzeit lokal exportiert werden kann.

Damit Sie diesen gesetzlichen Anforderungen nachkommen können, stellt plentymarkets verschiedene Exportfunktionen bereit. Besprechen Sie mit Ihrem Steuerbüro, welche Daten Sie exportieren und archivieren sollten, um rechtssicher zu arbeiten.

[#890]
==== DEP-Export erstellen

Laut §7 der österreichischen Registrierkassensicherheitsverordnung (RKSV) muss jede Registrierkasse über ein Datenerfassungsprotokoll (DEP) verfügen. Im DEP sind mindestens die Signierung von Belegen im Zusammenhang mit Barumsätzen und die Stornierung von Barumsätzen zu speichern. Die Unveränderlichkeitkeit der Daten ergibt sich dabei aus der Signaturverkettung. Pro DEP darf nur eine Kasse abgebildet werden.

Der DEP-Export wird als JSON-Datei bereitgestellt und enthält die folgenden Belegdaten:

* Belege-Gruppe
* Signaturzertifikat
* Zertifizierungsstellen
* Belege-kompakt

Das DEP einer Registrierkasse muss dabei auf Verlangen jederzeit auf einen externen Datenträger im vorgesehenen Exportformat exportiert werden können. Gehen Sie wie unten beschrieben vor, um einen DEP-Export zu erstellen:

[.instruction]
DEP-Dateien exportieren:

. Öffnen Sie das Menü **Aufträge » POS » DEP-Export**.
. Wählen Sie den Mandanten (Shop), für den Sie Daten exportieren möchten.
. Wählen Sie die Kasse, für die Sie Daten exportieren möchten.
. Wählen Sie das Datum, ab dem Sie Daten exportieren möchten.
. Wählen Sie das Datum, bis zu dem Sie Daten exportieren möchten.
. Klicken Sie auf *Herunterladen*. +
→ Die Datei wird im Standard-Download-Ordner des Browsers gespeichert. +
*_Tipp:_* Der Dateiname enthält den Exportzeitraum, zum Beispiel depExport_9-1-2017-9-2-2017.json für Daten von 9.1. bis 9.2.2017.

[#4200]
==== Monatsbeleg erstellen (Österreich)

Monatsbelege sind signierte Kontrollbelege mit einem Betrag von Null (0,00) Euro. Laut RKSV muss am Ende jedes Monats ein Monatsbeleg erstellt werden. Der Monatsbeleg für den Monat Dezember dient gleichzeitig als Jahresbeleg. Diesen Jahresbeleg müssen Sie jedes Jahr zusätzlich ausdrucken, aufbewahren und den Barcode mit der BMF Belegcheck-App prüfen.

[#4300]
===== Berechtigungen für Monatsbelege erteilen

Kassenpersonal mit Admin-Rechten hat standardmäßig die Berechtigung, Monatsbelege zu erstellen. Kassenpersonal mit der Benutzerklasse *Variabel* muss diese Berechtigung erteilt werden.

[.instruction]
Benutzern Berechtigungen für Monatsbelege erteilen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Einstellungen » Benutzer*.
. Öffnen Sie das Konto des Benutzers.
. Öffnen Sie das Tab *Mobile*.
. Aktivieren Sie im Bereich *POS-Funktionen* die Berechtigung *Monatsbeleg (AT)*.
. *Speichern* Sie die Einstellungen. +
→ Die Kassenbenutzerin ist berechtigt, <<pos/pos-kassenbenutzer#270, Monatsbelege in plentymarkets POS>> zu erstellen.

[#4400]
=== SOS: Die Signatureinheit ist ausgefallen - was jetzt?

Die RKSV gibt vor, wie Sie vorgehen müssen, falls die Signatureinheit der Registrierkasse ausfällt:

* Wenn die Signatureinheit ausfällt, müssen Sie Geschäftsfälle auf einer anderen Registrierkasse mit funktionierender Signatureinheit erfassen.
* Wenn keine andere Registrierkasse verfügbar ist, kann die Registrierkasse temporär ohne Signatureinheit betrieben werden.
* Dauert der Ausfall der Signatureinheit länger als 48 Stunden, müssen Sie Beginn und Ende des Ausfalls innerhalb einer Woche über FinanzOnline dem Finanzamt melden.
* Sämtliche nicht signierte Belege müssen mit dem Hinweis *Sicherheitseinrichtung ausgefallen* versehen werden. +
→ In plentymarkets POS werden Belege automatisch mit diesem Hinweis versehen, wenn die Signatureinheit ausfällt.
* Sobald die Signatureinheit wieder funktioniert, muss ein signierter Sammelbeleg erstellt werden, der sämtliche Geschäftsvorfälle enthält, die im Ausfallzeitraum über die Registrierkasse abgewickelt wurden. +
→ plentymarkets POS erstellt automatisch einen signierten Sammelbeleg, wenn die Signatureinheit wieder in Betrieb genommen wird.

[#930]
=== Kontrollbeleg auf Verlangen der Finanzpolizei erstellen

Bei einer Kassenrückschau durch die Finanzpolizei muss auf Verlangen ein Kontrollbeleg mit dem Betrag Null erstellt werden. Mit diesem Kontrollbeleg kann die prüfende Person die Gültigkeit der Signatur mit einer Prüf-App direkt vor Ort in Ihrem Laden prüfen. Jede Kassenkraft kann einen solchen <<pos/pos-kassenbenutzer#270, Kontrollbeleg auf Verlangen>> erstellen. Zum Erstellen des Kontrollbelegs sind keine zusätzlichen Berechtigungen erforderlich.

[#920]
=== Kasse außer Betrieb nehmen (Standort Österreich)

Um eine Kasse mit Standort Österreich dauerhaft außer Betrieb zu nehmen, erstellen Sie einen Endbeleg. Ein Endbeleg ist ein signierter Kontrollbelege mit einem Betrag von Null (0,00) Euro, der nur erstellt werden kann, wenn für die Kasse auch ein Startbeleg erstellt wurde. Den Endbeleg erstellen Sie im POS-Menü der plentymarkets App. Nachdem ein Endbeleg für die Kasse erstellt wurde, kann die Kasse nicht mehr verwendet werden.

[.instruction]
Endbeleg erstellen:

. Öffnen Sie die plentymarkets App.
. Öffnen Sie das Menü **plentymarkets App » Einstellungen » POS**.
. Tippen Sie auf **Endbeleg erstellen**. +
→ Der Endbeleg wird gedruckt. +
→ Der Endbeleg wird im Kassenjournal und im Dokumentenarchiv gespeichert. +
→ Die Kasse kann nicht mehr verwendet werden.
. Melden Sie dem Finanzamt, dass die Kasse außer Betrieb genommen wurde.

//  Next: [#4500]
