= Best Practices: POS
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, Kasse, POS, Gutscheine, Gutscheine verkaufen, Best Practice
:position: 30
:url: pos/pos-best-practice
:id: X4RBWGB

Hier findest du Best Practices rund um das Thema plentymarkets POS.

[#10]
== Gutscheine an der Kasse

Da es bezogen auf den Umgang mit Verkaufsgutscheinen viele Möglichkeiten bei plentymarkets gibt, möchten wir dir hier eine praxisnahe und einfache Variante für den POS-Bereich vorstellen.

=== Ziel

Schneller <<pos/pos-einrichten#2100, Verkauf von Gutscheinkarten>> in variabler Höhe an der Kasse.

=== Vorbereitung

. Sofern noch nicht vorhanden, musst du eine <<pos/pos-einrichten#830, passende Kampagne>> in plentymarkets erstellen.
. Lege dir einen <<pos/pos-einrichten#840, Gutscheinartikel mit flexiblem Wert>> für diese Art von Gutscheinen in plentymarkets an.
. Füge diesen Gutscheinartikel dem <<pos/pos-einrichten#60, Favoritenbereich>> deiner Kasse hinzu.
. Beschaffe dir link:http://lmgtfy.com/?q=Barcode-Karten+Druck[Barcode-Karten^] mit vorgefertigten Codes. Die meisten Anbieter erwarten eine CSV-Datei, die die einzelnen Codes enthält, die auf den Karten platziert werden sollen, sowie eine Layout-Vorlage im Photoshop- oder Adobe-Illustrator-Format für das Rahmendesign. +
*_Tipp:_* Wenn du deinen Gutscheincodes das Präfix *#* voranstellst, beschleunigst du später den Einlösungsvorgang, weil plentyPOS dadurch direkt beim Scannen erkennt, dass es sich um einen Gutschein handelt und nicht erst manuell die Schaltfläche für den Gutscheindialog betätigt werden muss.

=== Videos des Ablaufs

==== Gutschein verkaufen

video::pos/assets/verkauf_best_practice.mp4[width=640]

==== Gutschein einlösen

video::pos/assets/einloesung_best_practice.mp4[width=640]

[#100]
== Online-Bestellungen an der Kasse abschließen (Click & Collect)

<<pos/pos-kassenbenutzer#450, Click & Collect>> bedeutet, dass Ware online bestellt und im Laden abgeholt werden kann. Der Auftrag wird in plentymarkets POS geladen und an der Kasse abgeschlossen. In der Kasse können die folgenden Fälle auftreten:

* Der Auftrag wurde online bestellt und bezahlt. Die Ware wird im Laden abgeholt.
* Der Auftrag wurde online bestellt. Die Ware wird im Laden bezahlt und abgeholt.

In diesem Best Practice erfährst du, welche Vorbereitungen du treffen musst, um Online-Bestellungen an der Kasse abzuschließen.

=== Versandeinstellungen

Wenn du schon eine Kasse nutzt, hast du auch schon einen Versanddienstleister *Selbstabholung* und ein Versandprofil *Selbstabholung*. Wir empfehlen aber, für Click & Collect einen eigenen Versanddienstleister und ein eigenes Versandprofil zu erstellen.

[#190]
==== Versanddienstleister für Abholung in der Filiale erstellen

Gehe wie unten beschrieben vor, um einen <<fulfillment/versand-vorbereiten#800, Versanddienstleister>> für die Abholung in der Filiale zu erstellen. In diesem Best Practice nennen wir diesen Versanddienstleister *Abholung in der Filiale*. Natürlich kannst du auch einen anderen Namen verwenden.

[.instruction]
Versanddienstleister für Abholung in der Filiale erstellen:

. Öffne das Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versanddienstleister*.
. Klicke auf *Neu*. +
→ Ganz unten wird eine neue Zeile hinzugefügt.
. Gib in die Spalte *Namen (de)* den Namen *Abholung in der Filiale* ein.
. Gib in die Spalte *Namen (Backend)* den Namen *Abholung in der Filiale* ein.
. Wähle in der Spalte *Versanddienstleister* die Option *Selbstabholer* aus der Dropdown-Liste.
. *Speichere* die Einstellungen.

[#200]
==== Versandprofil für Abholung in der Filiale erstellen

Erstelle nun ein <<fulfillment/versand-vorbereiten#1000, Versandprofil>> für die Abholung in der Filiale. In diesem Best Practice nennen wir dieses Versandprofil *Abholung in der Filiale*. Natürlich kannst du auch einen anderen Namen verwenden.

[.instruction]
Versandprofil für Abholung in der Filiale erstellen:

. Öffne das Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Klicke auf *Neu*.
. Wähle den Versanddienstleister *Abholung in der Filiale* aus der Dropdown-Liste, den du gerade erstellt hast.
. Gib für die Option *Namen (de)* den Namen *Abholung in der Filiale* ein.
. Gib für die Option *Namen (Backend)* den Namen *Abholung in der Filiale* ein.
. Aktiviere den *Mandanten (Shop)*, für den du die Abholung in der Filiale anbieten möchtest.
. Aktiviere die *Auftragsherkunft*. Wir empfehlen die Herkünfte *0 Manuelle Eingabe* und den *Mandanten (Shop)*.
. **Speichere** die Einstellungen. +
→ Das Tab **Portotabelle** wird angezeigt. +
*_Hinweis:_* Die Abholung in der Filiale ist in der Regel versandkostenfrei. Daher werden in diesem Best Practice keine Versandkosten gespeichert.
. *Speichere* die Einstellungen des Tabs *Portotabelle* ohne Änderungen.


[#210]
==== Versandprofil für Abholung in der Filiale am Artikel aktivieren

Aktiviere nun das Versandprofil *Abholung in der Filiale* bei den Artikeln, die online bestellt und im Laden abgeholt werden können.

[.instruction]
Versandprofil für Abholung in der Filiale am Artikel aktivieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Global*.
. Aktiviere das Versandprofil *Selbstabholung*.
. *Speichere* die Einstellungen.

[TIP]
.Versandprofil für mehrere Artikeln aktivieren
====
Du möchtest das Versandprofil für eine größere Anzahl an Artikeln gleichzeitig aktivieren? Dann nutze die <<artikel/artikel-verwalten#155, Artikel-Gruppenfunktion>>.
====

=== Zahlungsart für Zahlung im Laden aktivieren

Aktiviere nun die Zahlungsart *Barzahlung*, damit Online-Aufträge auch im Laden bezahlt werden können.

* Stelle das Plugin link:https://marketplace.plentymarkets.com/plugins/payment/PayUponPickup_4757[Barzahlung] für den Mandanten bereit. +
→ Standardmäßig wird im Webshop der Name der Zahlungsart, also "Barzahlung" angezeigt. Ändere optional den Namen der Zahlungsart, zum Beispiel zu "Bezahlung in der Filiale".

=== Warenbewegungen festlegen (ab Version 1.9.2)

Nun legst du fest, wie der Warenbestand von online bestellten Artikeln behandelt werden soll, die im Ladengeschäft abgeholt werden.

[.instruction]
Warenbewegungen für Online-Aufträge festlegen:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » POS*.
. Öffne die Kasse. +
→ Das Tab *Grundeinstellungen* wird geöffnet.
. Die Option *Externer Auftrag: Warenausgang automatisch buchen* ist vorausgewählt. Der Warenausgang wird also nach der Bezahlung immer automatisch gebucht. Deaktiviere die Option, wenn der Warenausgang nur gebucht werden soll, wenn das Kassenpersonal auf *Warenausgang buchen* tippt. +
*_Tipp:_* Deaktiviere die Option nur, wenn du eine separate Warenausgabe hast, also die Waren nach der Bezahlung nicht direkt an der Kasse aushändigst. Schule außerdem das Kassenpersonal, in welchen Fällen die Schaltfläche betätigt werden soll.
. Wenn die Ware aus dem Vertriebslager der Kasse ausgebucht werden soll, aktiviere die Option *Warenausgang von externen Aufträgen: Ware aus POS-Vertriebslager buchen*. +
→ Wenn du die Option nicht aktivierst, wird die Ware aus dem Lager ausgebucht, das dem Auftrag bei der Erstellung zugewiesen wurde.
. *Speichere* die Einstellungen.

////
== Warenwirtschaft

EAs für Warenausgang

* Bei Lieferung in die Filiale
* Bei Übergabe an die Kundschaft
* Wenn Laden = Lager

Ware wird ausgebucht: Ware wird aus dem Lager ausgebucht, das im Auftrag definiert wurde.

Auftrag sollte nicht in den Prozessen verarbeitet werden.

Nicht bearbeiten: Im Prozess nach Versandprofil filtern und Selbstabholer ausschließen, damit Warenausgang nicht gebucht wird.
////
