= POS für Kassenpersonal
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, Kasse, POS, plentymarkets Kasse, Kassenbenutzer, POS-Benutzer, Katzenpersonal, Kassenpersonal, Kassierer
:position: 20

Auf dieser Handbuchseite erfahren Sie, wie Sie die plentymarkets POS Kasse bedienen.

////
p>Noch beschreiben:</p>

<ul>
<li>Artikel oder Variante???</li>
<li>Wie setzt sich die Belegnummer zusammen?</li>
<li>Preis bearbeiten</li>
<li>Dummy-Artikel, wenn Artikel nicht gefunden wird</li>
<li>Favoriten in der App erstellen</li>
<li>Warenbestand prüfen</li>
<li>(Kasse sperren)</li>
<li>(Artikel synchronisieren)</li>
<li>(Aufträge hochladen)</li>
</ul>
////

[#5]
== plentymarkets App installieren

Installieren Sie zunächst die plentymarkets App auf dem mobilen Endgerät.

* **link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=de[plentymarkets App bei Google Play^]**

* **link:https://itunes.apple.com/de/app/plentymarkets/id957702618[plentymarkets App bei iTunes^]**

[WARNING]
.Offline-Aufträge werden beim Deinstallieren der App gelöscht
====
Bei fehlender Internetverbindung werden Aufträge offline gespeichert und erst später synchronisiert. Wenn Sie die App deinstallieren, bevor die Aufträge an plentymarkets übertragen wurden, werden die lokal gespeicherten Aufträge unwiederbringlich gelöscht und können auch vom plentymarkets Support nicht wiederhergestellt werden. Prüfen Sie daher vor jedem Deinstallieren der App, dass keine Offline-Aufträge auf dem Gerät vorhanden sind.
====

[#410]
== Anmelden, abmelden und sperren

[#10]
=== Anmelden

Gehen Sie wie unten beschrieben vor, um sich bei der plentymarkets App anzumelden.

[.instruction]
Bei plentymarkets POS anmelden:

. Melden Sie sich auf dem Mobilgerät an.
. Tippen Sie auf dem Startbildschirm auf das plentymarkets App Symbol. +
→ Der Login-Bildschirm wird angezeigt.
. Geben Sie die Login-Daten ein. Beachten Sie <<tabelle-POS-kassenpersonal-anmeldung>>.
. Tippen Sie auf **Login**. +
→ Der Startbildschirm der plentymarkets App wird angezeigt.
. Tippen Sie oben links auf das Menüsymbol. +
→ Die verfügbaren Menüpunkte werden angezeigt.
. Tippen Sie auf **POS**. +
→ plentymarkets POS wird geöffnet.

[TIP]
.Anmeldung wird gespeichert
====
Sie bleiben angemeldet, bis Sie im Hauptmenü der App oder in der Liste der Benutzerkonten auf *Ausloggen* oder *Sperren* tippen. Sie können also die App schließen und öffnen, ohne sich erneut anmelden zu müssen.
====

[[tabelle-POS-kassenpersonal-anmeldung]]
.Anmeldung
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Sprache
|Sprache wählen, in der plentymarkets POS dargestellt werden soll. Die Benutzeroberfläche von plentymarkets POS ist auf Deutsch und Englisch verfügbar.

|**System (Basis-URL)**
|Domain des plentymarkets Systems ohne führendes https:// oder http:// eingeben, zum Beispiel **ihr-shop.de**.

|**Benutzer**; **Passwort**
|Benutzernamen und Passwort für das plentymarkets System eingeben.
|====

[#310]
=== Benutzerkonto wechseln

Eingeloggte Benutzerkonten müssen nicht abgemeldet werden, damit Sie sich anmelden können. Ein solcher schneller Kontowechsel funktioniert aber nur, wenn gerade ein Benutzerkonto eingeloggt ist. Welches Benutzerkonto angemeldet ist, erkennen Sie an dem Benutzersymbol oben rechts. Das Benutzersymbol enthält die Initialen des realen Namens der eingeloggten Person. Das Symbol hat die Farbe, die für das Benutzerkonto im plentymarkets Backend gespeichert wurde. Der schnelle Kontowechsel ist im Hauptmenü, dem POS-Menü, beim Kassieren und in einer Retoure möglich. Nach dem Wechsel wird derselbe Bereich der App geöffnet. Wenn das neue Benutzerkonto für diesen Bereich keine Rechte hat, wird stattdessen das Hauptmenü der App geöffnet. Gehen Sie wie unten beschrieben vor, um das Benutzerkonto zu wechseln.

[TIP]
.Auftragsdaten bleiben erhalten
====
Wenn Sie das Benutzerkonto beim Erstellen eines Auftrags wechseln, wird auch der neu eingeloggten Kassenkraft dieser Auftrag angezeigt und kann abgeschlossen werden.
====

[.instruction]
Benutzerkonto im laufenden Betrieb wechseln:

. Tippen Sie in der App oben rechts auf das Benutzersymbol. +
→ Eine Liste der realen Namen der Personen wird angezeigt, für die im Benutzerkonto eine App-PIN gespeichert ist. +
*_Hinweis:_* Wenn Ihr Name nicht angezeigt wird, aktualisieren Sie die Ansicht, indem Sie das Fenster nach unten ziehen. Wenn Ihr Name immer noch nicht angezeigt wird, ist im plentymarkets Backend für Ihr Benutzerkonto keine App-PIN gespeichert.
. Tippen Sie auf Ihr Benutzerkonto.
. Wenn Sie sich zum ersten Mal in der App anmelden, geben Sie Ihr Benutzerpasswort ein. Ab dem zweiten Anmelden geben Sie Ihre PIN ein. +
→ Das Benutzerkonto wird gewechselt. +
→ Der Bereich der App wird geöffnet, in dem der Kontowechsel ausgelöst wurde. +
*_Tipp:_* Wenn Sie für diesen Bereich keine Berechtigung haben, wird das Hauptmenü geöffnet.

[#400]
=== Zugriff sperren und entsperren

Wenn Sie sich von der Kasse entfernen, aber weiterhin eingeloggt bleiben möchten, sperren Sie den Zugriff auf die App. Gehen Sie wie unten beschrieben vor, um den Zugriff auf die App zu sperren und zu entsperren.

[.instruction]
Zugriff sperren und entsperren:

. Tippen Sie in der App oben rechts auf das Benutzersymbol. +
→ Eine Liste der realen Namen der Personen wird angezeigt, für die im Benutzerkonto eine App-PIN gespeichert ist.
. Tippen Sie unten links auf das Symbol *Sperren*. +
→ Der Zugriff auf die App wird gesperrt. +
→ Ihr realer Name wird als erster Eintrag in der Liste der Benutzerkonten angezeigt.
. Um den Zugriff auf die App zu entsperren, tippen Sie oben rechts auf das Benutzersymbol.
. Tippen Sie auf Ihr Benutzerkonto.
. Geben Sie Ihre PIN oder Ihr Passwort ein. +
*_Hinweis:_* Zum Entsperren der App ist eine PIN oder ein Passwort erforderlich, wenn Sie die App schließen und erneut öffnen. +
→ Der Zugriff auf die App wird entsperrt. +
*_Tipp:_* Auch bei gesperrtem App-Zugriff können Sie das Benutzerkonto wechseln. Tippen Sie auf ein anderes Benutzerkonto in der Liste, um das Benutzerkonto zu wechseln.

[#390]
=== Abmelden und Login-Daten verwerfen

Gehen Sie wie unten beschrieben vor, um sich von der App abzumelden und die Login-Daten zu verwerfen. Beim nächsten Anmelden müssen dann Sprache, Basis-URL und Benutzerdaten erneut eingegeben werden.

[.instruction]
Abmelden und Login-Daten verwerfen:

. Tippen Sie in der App oben rechts auf das Benutzerkontosymbol. +
→ Eine Liste der realen Namen der Personen wird angezeigt, für die im Benutzerkonto eine App-PIN gespeichert ist.
. Tippen Sie unten rechts auf das Symbol *Ausloggen*. +
→ Das Fenster *Ausloggen* wird angezeigt. +
*_Oder:_* Tippen Sie in der App oben links auf das Menüsymbol und dann auf *Ausloggen*. +
. Deaktivieren Sie die Option *Aktuellen Benutzer automatisch wieder einloggen*. +
*_Hinweis:_* Diese Einstellung wird übernommen und gilt für alle Benutzerkonten der App. +
. Tippen Sie auf *Ausloggen*. +
→ Das Benutzerkonto wird vollständig ausgeloggt und die Anmeldedaten verworfen. +
→ Die Login-Ansicht wird angezeigt. +
→ Beim nächsten Anmelden müssen Sprache, Basis-URL und Benutzerdaten eingegeben werden.

[#420]
=== App beenden und aktuelle Login-Daten merken

Gehen Sie wie unten beschrieben vor, um die App zu beenden und die aktuellen Login-Daten der letzten eingeloggten Person zu merken. Beim nächsten Öffnen der App wird das Benutzerkonto automatisch wieder eingeloggt. Weder PIN noch Passwort sind erforderlich.

[.instruction]
App beenden und aktuelle Login-Daten merken:

. Tippen Sie in der App oben rechts auf das Benutzersymbol. +
→ Eine Liste der realen Namen der Personen wird angezeigt, für die im Benutzerkonto eine App-PIN gespeichert ist.
. Tippen Sie unten rechts auf das Symbol *Ausloggen*. +
→ Das Fenster *Ausloggen* wird angezeigt. +
*_Oder:_* Tippen Sie in der App oben links auf das Menüsymbol und dann auf *Ausloggen*. +
. Aktivieren Sie die Option *Aktuellen Benutzer automatisch wieder einloggen*. +
*_Hinweis:_* Diese Einstellung wird übernommen und gilt für alle Benutzerkonten der App. +
. Tippen Sie auf *Ausloggen*. +
→ Die App wird beendet.  +
→ Das aktive Benutzerkonto wird auf dem Server ausgeloggt.  +
→ Beim nächsten Öffnen der App wird dieses Benutzerkonto automatisch wieder eingeloggt.  +
→ Beim Start der App muss keine PIN und kein Passwort eingegeben werden.

[#290]
== plentymarkets POS personalisieren

In den Einstellungen der plentymarkets App können Sie das Hintergrundbild ändern und für Android-Geräte den Vollbildmodus aktivieren. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Darstellung anpassen:

. Öffnen Sie die plentymarkets App.
. Tippen Sie oben links auf das Menüsymbol. +
→ Das Menü wird angezeigt.
. Tippen Sie auf *Darstellung*.
. Nehmen Sie die Einstellungen vor. Beachten Sie <<tabelle-POS-darstellung>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-POS-darstellung]]
.Darstellung anpassen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Hintergrund wählen*

|*Hintergrund wählen*
|Auf das Bild tippen, das als Hintergrund in der Kasse angezeigt wird.

2+|*Vollbildmodus verwenden*

|*Vollbildmodus* +
(nur Android-Geräte)
|Aktivieren, um die Softkeys des Betriebssystems auszublenden.
|====

[#30]
== Kassieren

Nachdem Sie sich bei plentymarkets POS angemeldet haben, wird das POS-Menü angezeigt. Tippen Sie auf **Kassieren**, um den POS-Warenkorb zu öffnen und Artikel hinzuzufügen.

[#40]
=== Artikel zum POS-Warenkorb hinzufügen

Artikel fügen Sie über die Artikelsuche, die Favoritenliste oder per Etiketten-Scan zum POS-Warenkorb hinzu.

[IMPORTANT]
.MHD-/Chargen-Daten
====
Artikel mit MHD-/Chargen-Daten werden nicht gefunden.
====

[#50]
==== Artikel suchen

Über die Artikelsuche haben Sie Zugriff auf den gesamten Artikelbestand des Mandanten. Eine Suche ist anhand folgender Artikeldaten möglich:

* Artikel-ID
* Variantennummer
* Barcode
* Artikelname
* Varianten-ID
* Lieferanten-Artikel-Nr.

Gehen Sie wie unten beschrieben vor, um Artikel über die Suche zum POS-Warenkorb hinzufügen.

[.instruction]
Artikel über Suche hinzufügen:

. Tippen Sie im POS-Warenkorb auf die Lupe. +
→ Die Artikelsuche wird geöffnet.
. Geben Sie ein Suchkriterium ein.
. Tippen Sie auf **Suchen**. +
→ Die gefundenen Artikel werden aufgelistet. +
*_Hinweis:_* Artikel mit MHD-/Chargen-Daten werden nicht gefunden.
. Tippen Sie auf das grün hinterlegte Häkchen, um einen Artikel in den Warenkorb zu legen. +
→ Das Fenster **Menge eingeben** wird angezeigt.
. Geben Sie die Menge des Artikels ein, die Sie in den Warenkorb legen möchten. +
→ Der Artikel wird in den Warenkorb gelegt und die zu zahlende Summe aktualisiert. +
**__Tipp:__** Artikel ohne Nettowarenbestand werden in roter Schrift dargestellt, können aber verkauft werden.

[#60]
==== Favoritenliste öffnen

Über die Favoritenliste greifen Sie schnell auf als Favoriten gekennzeichnete Artikel zu. plentymarkets Administratoren können eine Favoritenliste für die Kasse hinterlegen. Aber auch Sie selbst können häufig gekaufte Artikel als Favoriten kennzeichnen, um den Kassiervorgang zu beschleunigen. Gehen Sie wie unten beschrieben vor, um Artikel über die Favoritenliste zum POS-Warenkorb hinzufügen.

[.instruction]
Artikel über Favoritenliste hinzufügen:

. Tippen Sie im POS-Warenkorb auf den Stern. +
→ Die Liste der Favoriten wird geöffnet. +
*_Hinweis:_* Artikel mit MHD-/Chargen-Daten werden nicht gefunden. +
. Tippen Sie auf das grün hinterlegte Häkchen, um einen Artikel in den Warenkorb zu legen. +
→ Das Fenster **Menge eingeben** wird angezeigt. +
. Geben Sie die Menge des Artikels ein, die Sie in den Warenkorb legen möchten. +
→ Der Artikel wird in den Warenkorb gelegt und die zu zahlende Summe aktualisiert.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter.

[#70]
==== Artikeletikett scannen

Wenn Sie mit Artikeletiketten arbeiten, können Sie Artikel auch das Etikett eines Artikels scannen, um den Artikel zum POS-Warenkorb hinzufügen. Artikel können Sie über die Kamera des Mobilgeräts oder einen angeschlossenen Bluetooth-Scanner einlesen. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Artikeletikett mit integrierter Gerätekamera scannen:

. Tippen Sie im POS-Warenkorb auf das Etikettensymbol. +
→ Die Kamera des Mobilgeräts wird aktiviert.
. Tippen Sie auf das Kamerasymbol, um das Etikett zu scannen. +
*_Hinweis:_* Artikel mit MHD-/Chargen-Daten werden nicht gefunden. +
→ Der Artikel wird mit einer Menge von 1 in den POS-Warenkorb gelegt. +
→ Die zu zahlende Summe wird aktualisiert. +
*_Tipp:_* Wenn in der untersten Zeile des Ziffernblocks der Kasse der Button *X* eingeblendet ist, können Sie auf diesen Button tippen, die Menge eingeben und dann den Artikel scannen oder einen Favoritenartikel wählen. Der Artikel wird dann mit der eingegebenen Menge in den POS-Warenkorb gelegt. Ein Administrator für die Kasse muss diese Komfortfunktion aktivieren.

[.instruction]
Artikeletikett mit externem Bluetooth-Scanner scannen:

. Öffnen Sie den POS-Warenkorb. +
. Scannen Sie das Etikett des Artikels.  +
*_Hinweis:_* Artikel mit MHD-/Chargen-Daten werden nicht gefunden. +
→ Der Artikel wird mit einer Menge von 1 in den POS-Warenkorb gelegt. +
→ Die zu zahlende Summe wird aktualisiert. +
*_Tipp:_* Wenn in der untersten Zeile des Ziffernblocks der Kasse der Button *X* eingeblendet ist, können Sie auf diesen Button tippen, die Menge eingeben und dann den Artikel scannen oder einen Favoritenartikel wählen. Der Artikel wird dann mit der eingegebenen Menge in den POS-Warenkorb gelegt. Ein Administrator für die Kasse muss diese Komfortfunktion aktivieren.

[#80]
=== Zahlung entgegennehmen

Nachdem Sie alle Artikel des Kunden in den POS-Warenkorb gelegt haben und bei Bedarf Rabatte/Verkaufsgutscheine angewendet haben, buchen Sie die Zahlung. Kundinnen können in bar und je nach den Abläufen in Ihrem Ladengeschäft auch über einen EC-Terminal oder per Gutschein bezahlen.

[NOTE]
.Auftrag stornieren
====
Sie können einen POS-Auftrag direkt stornieren, nachdem Sie die Zahlung gebucht haben. Tippen Sie dazu in der Ansicht *Auftrag erstellt* auf *Auftrag stornieren*. Bereits abgeschlossene Aufträge, die seit dem letzten Tagesabschluss über die Kasse erstellt wurden, stornieren Sie über das Menü <<pos/pos-kassenbenutzer#173, POS » Auftrag stornieren>>.
====


==== Bargeld entgegennehmen

Gehen Sie wie unten beschrieben vor, um Barzahlungen entgegenzunehmen.

[.instruction]
Bargeld entgegennehmen:

. Geben Sie über das Ziffernfeld den Betrag ein, den Sie vom Kunden erhalten haben. +
*_Tipp:_* Wenn der Kunde den Betrag passend in bar zahlt, tippen Sie stattdessen in der untersten Zeile des Ziffernblocks auf der Button *Passend*. Die erhaltene Summe wird dann automatisch in das Feld *Erhalten* eingefügt.
. Tippen Sie auf *Betrag erhalten*. +
→ Die Ansicht *Auftrag erstellt* wird angezeigt. +
→ Der Auftrag wird erstellt. +
→ Ein Beleg wird gedruckt. Tippen Sie sonst auf *Beleg drucken*, um den Beleg zu drucken. +
*_Tipp:_* Über den Button *Auftrag anzeigen* rufen Sie die Auftragsdaten auf.
. Tippen Sie auf *Neuer Auftrag*, um einen neuen POS-Auftrag zu erstellen.

==== Zahlung über EC-Terminal ohne Anbindung entgegennehmen

Eine Zahlung über ein EC-Terminal ohne Anbindung führen Sie durch, wenn das EC-Terminal nicht mit plentymarkets POS verbunden ist. Da keine Verbindung zwischen plentymarkets POS und dem EC-Terminal besteht, sendet plentymarkets POS keine Auftragsdaten an das EC-Terminal. Deshalb geben Sie den Betrag selbst am EC-Terminal ein. Nachdem Sie die Zahlung am EC-Terminal durchgeführt haben, bestätigen Sie in plentymarkets POS manuell, dass der Auftrag bezahlt wurde. Gehen Sie wie unten beschrieben vor, um eine Zahlung über ein EC-Terminal ohne Anbindung entgegenzunehmen.

[.instruction]
Zahlung über EC-Terminal ohne Anbindung entgegennehmen:

. *_Optional:_* Wenn die Kundin nur einen Teilbetrag per EC-Karte zahlen möchte, geben Sie diesen Teilbetrag ein. +
*_Tipp:_* (ab Version 1.8.5) Wenn die Kundin den gesamten Betrag mit nur einer Kartenzahlung begleichen möchte, brauchen Sie den Betrag nicht mehr einzugeben, bevor Sie auf *EC-Terminal* tippen. Der Gesamtbetrag wird automatisch für die EC-Zahlung übernommen.
. Tippen Sie auf *EC-Terminal*. +
→ Die zu zahlende Auftragssumme wird angezeigt.
. Führen Sie die Zahlung am EC-Terminal durch.
. Tippen Sie auf *Betrag erhalten/Zahlung abschließen*, um die Zahlung abzuschließen. +
→ Wenn der Auftrag vollständig bezahlt ist, wird die Ansicht *Auftrag erstellt* angezeigt. +
→ Der Auftrag wird erstellt. +
→ Ein Beleg wird gedruckt. Tippen Sie sonst auf *Beleg drucken*, um den Beleg zu drucken. +
*_Tipp:_* Über den Button *Auftrag anzeigen* rufen Sie die Auftragsdaten auf.
. Tippen Sie auf *Neuer Auftrag*, um einen neuen POS-Auftrag zu erstellen.

==== Zahlung über angebundenes EC-Terminal entgegennehmen

Eine Zahlung über ein angebundenes EC-Terminal führen Sie durch, wenn das EC-Terminal mit plentymarkets POS verbunden ist. Über diese Verbindung sendet plentymarkets POS den zu zahlenden Betrag an das EC-Terminal und startet den Bezahlvorgang. Nachdem die Zahlung erfolgt ist, wird der Auftrag automatisch in plentymarkets erstellt. Gehen Sie wie unten beschrieben vor, um eine Zahlung über ein angebundenes EC-Terminal entgegenzunehmen.

[.instruction]
Zahlung über angebundenes EC-Terminal entgegennehmen:

. *_Optional:_* Wenn die Kundin nur einen Teilbetrag per EC-Karte zahlen möchte, geben Sie diesen Teilbetrag ein. +
*_Tipp:_* (ab Version 1.8.5) Wenn die Kundin den gesamten Betrag mit nur einer Kartenzahlung begleichen möchte, brauchen Sie den Betrag nicht mehr einzugeben, bevor Sie auf *EC-Terminal* tippen. Der Gesamtbetrag wird automatisch für die EC-Zahlung übernommen.
. Tippen Sie auf *EC-Terminal*. +
. Folgen Sie den angezeigten Hinweisen, um die Zahlung über das Terminal abzuschließen. +
→ Wenn der Auftrag vollständig bezahlt wurde, wird die Ansicht *Auftrag erstellt* angezeigt. Buchen Sie sonst weitere Zahlungen. +
→ Der Auftrag wird erstellt. +
→ Die Belege werden gedruckt. Tippen Sie sonst auf *Händlerbeleg drucken* und/oder *Kundenbeleg drucken*, um das Drucken manuell zu starten. +
*_Tipp:_* Über den Button *Auftrag anzeigen* rufen Sie die Auftragsdaten auf.
. Tippen Sie auf *Neuer Auftrag*, um einen neuen POS-Auftrag zu erstellen.

[#160]
==== Verkaufsgutscheine entgegennehmen

Jeder Verkaufsgutschein hat einen einzigartigen Gutschein-Code. Diesen Gutschein-Code geben Sie während des Kassiervorgangs ein, um den Gutschein auf den Einkauf des Kunden anzuwenden. Damit Kunden einen Gutschein-Code einlösen können, muss dieser Gutschein-Code zu dem Zeitpunkt, in dem eine Kundin den Gutschein einlösen möchte, im plentymarkets System gespeichert sein. Ab App-Version 1.8.1 können Kunden pro Kassenvorgang auch mehrere Gutscheine einlösen. Beim Erstellen des Auftrags werden die Gutscheine in der Reihenfolge eingelöst, in der Sie die Gutscheincodes eingeben. Wenn Sie einen Gutscheincode entfernen, bevor der Auftrag erstellt wurde, wird der Restbetrag neu berechnet.

[.instruction]
Verkaufsgutscheine einlösen:

. Legen Sie die Artikel in den POS-Warenkorb, die der Kunde kaufen möchte.
. Tippen Sie unten im POS-Warenkorb auf den grün hinterlegten Pfeil nach rechts. +
→ Eine Zusammenfassung des Auftrags und die verfügbaren Zahlungsmethoden werden angezeigt.
. Tippen Sie auf *Gutschein/Rabatt*.
. Geben Sie in das Feld *Gutscheincode/Rabatt* den Gutscheincode ein.
. Tippen Sie auf *Gutschein*. +
→ Die Gutscheinsumme wird von der Auftragssumme abgezogen. +
→ Die Restsumme wird angezeigt, die der Kunde noch bezahlen muss.
. Wenn der Kunde weitere Gutscheine einlösen möchte, geben Sie diese Gutscheincodes auf dieselbe Art ein. +
*_Hinweis:_* Die Gutscheine werden in der Reihenfolge eingelöst, in der Sie die Gutscheincodes eingeben. Wenn Sie einen Gutscheincode wieder entfernen, wird die Restsumme neu berechnet.
. Tippen Sie auf *Zurück*.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter. +
→ Wenn Sie Rabatte auf den Auftrag oder einzelne Artikel vergeben, nachdem Sie einen oder mehrere Codes eingegeben haben, wird die Restsumme neu berechnet.
. Schließen Sie den POS-Auftrag ab. +
→ Wenn Sie mit Gutscheinbelegen arbeiten und der Gutschein nicht vollständig eingelöst wird, wird ein Gutscheinbeleg erstellt. Händigen Sie dem Kunden dann zusammen mit dem Kaufbeleg auch den Gutscheinbeleg aus. +
*_Tipp:_* Ob der Gutscheinbeleg automatisch gedruckt wird, hängt von den Kasseneinstellungen ab.

[#150]
==== Artikel auf Rechnung verkaufen

Wenn im plentymarkets Backend das Plugin *plentyPOS Kauf auf Rechnung* aktiviert ist, können Sie Bestandskunden auch Artikel auf Rechnung verkaufen. Kunden können Artikel nur auf Rechnung kaufen, wenn ihre Kundendaten im System gespeichert sind. Über plentyPOS können keine neuen Kundendaten erfasst werden.

[TIP]
.Retouren von auf Rechnung gekauften Artikeln
====
Aufträge mit Kauf auf Rechnung können bis zum nächsten Tagesabschluss wie gewohnt storniert werden. Auch die Retoure von auf Rechnung gekauften Artikeln ist möglich. Bei Teilzahlung errechnet die Kasse automatisch, welchen Betrag Kunden zurückbekommen.
====

[.instruction]
Artikel auf Rechnung verkaufen:

. Fügen Sie die Artikel <<40, zum POS-Warenkorb hinzu>>.
. Rufen Sie die <<135, Kundendaten der Kundin>> auf. +
*_Wichtig:_* Vergewissern Sie sich, dass die Kundin wirklich die in den Kundendaten gespeicherte Person ist. +
→ Nachdem ein Kundendatensatz gewählt wurde, wird das Symbol *Rechnungskauf* wählbar.
. Tippen Sie auf das Symbol *Rechnungskauf*. +
→ Ein Fenster mit Auftragsdaten und Kundendaten wird angezeigt.
. Prüfen Sie die Auftragsdaten.
. Tippen Sie auf *Rechnung*. +
→ Die Ansicht *Auftrag erstellt* wird angezeigt. +
→ Der Auftrag wird erstellt. +
→ Die Rechnung wird gedruckt. Tippen Sie sonst auf *Rechnung drucken*, um die Rechnung zu drucken.
. Tippen Sie auf *Neuer Auftrag*, um einen neuen POS-Auftrag zu erstellen.

[#430]
==== Mehrere Zahlungsarten entgegennehmen (ab Version 1.8.5)

Ab Version 1.8.5 der plentymarkets App können Kunden denselben Auftrag auch mit mehreren Zahlungsarten bezahlen. So können Kunden, die nicht genug Bargeld dabei haben, zum Beispiel einen Teil des Auftragswerts in bar und einen Teil mit EC-Karte zahlen.

[IMPORTANT]
.Rechnungskauf bei Teilbeträgen immer zuletzt
====
Wenn Sie auf das Symbol *Rechnungskauf* tippen, wird der Auftrag abgeschlossen und eine Rechnung erstellt. Der noch offene Betrag wird auf der Rechnung ausgewiesen. Wenn die Kundin einen Teil des Auftrags per Rechnung zahlen möchte, buchen Sie deshalb erst alle anderen Zahlungsarten und wählen Sie erst dann die Option *Rechnungskauf*, um den Auftrag abzuschließen.
====

Nachdem für einen Auftrag eine erste Zahlung gebucht wurde, sind die folgenden Änderungen nicht mehr möglich:

* Preise, Rabatte und Artikelposition im Warenkorb können nicht mehr geändert werden.
* Der Kundendatensatz, über den der Auftrag abgewickelt wird, kann nicht mehr geändert werden.
* Verkaufsgutscheine können nicht mehr eingelöst werden.

Stornieren Sie bei Bedarf die gebuchten Zahlungen, um diese Änderungen durchzuführen.

[NOTE]
.Kassieransicht verlassen
====
Nachdem die erste Zahlung für den Auftrag gebucht wurde, kann die Kassieransicht erst verlassen werden, wenn der Auftrag entweder komplett abgeschlossen oder alle Zahlungen storniert wurden.
====

[.instruction]
Mehrere Zahlungsarten entgegennehmen:

. Geben Sie über das Ziffernfeld den Betrag ein, den die Kundin mit der ersten Zahlungsart bezahlen möchte.
. Tippen Sie auf den Button für die Zahlungsart, in der Sie den Betrag erhalten haben. +
*_Hinweis:_* Wenn die Kundin einen Teil des Betrags auf Rechnung bezahlen möchte, buchen Sie zuerst alle anderen Zahlungsarten und wählen Sie erst zuletzt die Option *Rechnungskauf*, um den Restbetrag als Rechnungsbetrag zu übernehmen.
→ Die erste Zahlung wird gebucht.
. Geben Sie über das Ziffernfeld den Betrag ein, den die Kundin mit der nächsten Zahlungsart bezahlen möchte.
. Tippen Sie auf den Button für die Zahlungsart, in der Sie den Betrag erhalten haben. +
*_Tipp:_* Wenn Sie mehr als eine Barzahlung buchen, werden die bar bezahlten Teilsummen zusammengefasst. +
→ Die nächste Zahlung wird gebucht. +
. Nehmen Sie bei Bedarf weitere Zahlungen entgegen, bis der Auftrag vollständig bezahlt ist. +
*_Tipp:_* Tippen Sie auf den Balken *Zahlungen*, um Informationen zu den bereits gebuchten Zahlungen anzuzeigen. +
→ Wenn der gesamte Auftrag bezahlt wurde, wird der Auftrag erstellt.
→ Die Ansicht *Auftrag erstellt* wird angezeigt. +
→ Der Auftrag wird erstellt. +
→ Die Belege werden gedruckt. Tippen Sie sonst auf *Belege drucken*, um die Belege zu drucken. +
. Händigen Sie der Kundin den Beleg aus.
*_Bei Rechnungskauf:_* Ein Händlerbeleg, ein Zahlungsbeleg und eine Rechnung werden erstellt. Händigen Sie der Kundin dann den Zahlungsbeleg und die Rechnung aus.
*_Tipp:_* Über den Button *Auftrag anzeigen* rufen Sie die Auftragsdaten auf.
. Tippen Sie auf *Neuer Auftrag*, um einen neuen POS-Auftrag zu erstellen.


[#90]
=== Optionale Kassiervorgänge

[#250]
==== Verkaufsgutschein verkaufen

Jeder Verkaufsgutschein hat einen einzigartigen Gutschein-Code. Dieser Gutschein-Code wird auf dem Beleg ausgegeben, wenn Sie einen Gutscheinartikel verkaufen. Damit Kunden einen Gutschein-Code einlösen können, muss dieser Gutschein-Code zu dem Zeitpunkt, in dem die Kundin den Gutschein einlösen möchte, im plentymarkets System gespeichert sein. Je nach den Abläufen in Ihrem Ladengeschäft generieren Sie Gutschein-Codes entweder automatisch beim Verkauf des Gutscheins oder Sie arbeiten mit Gutschein-Code-Listen, die Ihnen Ihr Arbeitgeber zur Verfügung stellt. Die Codes auf dieser Liste sind entweder bereits im System gespeichert oder Sie speichern die Codes beim Verkauf. Erkundigen Sie sich bei Ihrem Arbeitgeber, wie Sie beim Verkauf von Gutscheinen vorgehen sollten.

[.instruction]
Verkaufsgutschein verkaufen und automatischen Gutschein-Code generieren:

. Legen Sie den Gutscheinartikel mit dem gewünschten Gutscheinwert in den POS-Warenkorb.
. Wählen Sie die Menge. +
→ Das Fenster **Gutschein wählen** wird angezeigt.
. Tippen Sie auf **Generieren**. +
**__Tipp:__** Wenn Sie mehr als einen Gutschein als Menge wählen, wird dieser Schritt übersprungen.
. *_Optional:_* Geben Sie den Wert des Gutscheins ein. +
→ Bei Gutscheinartikeln mit festem Preis wird der Gutscheinwert automatisch übernommen.
. Schließen Sie den Auftrag wie gewohnt ab. +
→ Der Gutschein-Code wird auf dem Kassenbeleg ausgegeben.
. Händigen Sie dem Kunden den Kassenbeleg aus.
. Wenn Sie auch Gutscheinbelege drucken, händigen Sie dem Kunden auch den Gutscheinbeleg aus. +
*_Hinweis:_* Der Gutschein-Code steht auf dem Gutscheinbeleg und dem Kassenbeleg. Daher sollten Kunden beide Belege mitnehmen, damit niemand sonst den Gutschein einlösen kann.

[.instruction]
Verkaufsgutschein verkaufen und vorhandenen Gutschein-Code eingeben:

. Legen Sie den Gutscheinartikel mit dem gewünschten Gutscheinwert in den POS-Warenkorb.
. Wählen Sie die Menge 1. +
**__Tipp:__** Wenn Sie mehr als einen Gutschein als Menge wählen, werden die Gutschein-Codes automatisch generiert. +
→ Das Fenster **Gutschein wählen** wird angezeigt.
. Geben Sie in das Feld **Gutschein-Code** den Code ein.
. Tippen Sie auf **Vorhandenen**. +
→ Der Gutscheinwert wird im System ermittelt und übernommen.
. Schließen Sie den Auftrag wie gewohnt ab. +
→ Der Gutschein-Code wird auf dem Kassenbeleg ausgegeben.
. Händigen Sie dem Kunden den Kassenbeleg aus.
. Wenn Sie auch Gutscheinbelege drucken, händigen Sie dem Kunden auch den Gutscheinbeleg aus. +
*_Hinweis:_* Der Gutschein-Code steht auf dem Gutscheinbeleg und dem Kassenbeleg. Daher sollten Kunden beide Belege mitnehmen, damit niemand sonst den Gutschein einlösen kann.
. Dokumentieren Sie, welchen Gutschein-Code Sie verkauft haben. +
**__Hinweis:__** Jeder Gutschein-Code darf nur einmal verkauft werden, da der Betrag nur einmal eingelöst werden kann.

[.instruction]
Verkaufsgutschein verkaufen und Gutschein-Code im System speichern:

. Legen Sie den Gutscheinartikel mit dem gewünschten Gutscheinwert in den POS-Warenkorb.
. Wählen Sie die Menge 1. +
**__Tipp:__** Wenn Sie mehr als einen Gutschein als Menge wählen, werden automatisch Gutschein-Codes generiert. +
→ Das Fenster **Gutschein wählen** wird angezeigt.
. Geben Sie in das Feld **Gutschein-Code** den Code ein.
. Tippen Sie auf **Generieren**. +
→ Das Fenster **Gutscheinwert eingeben** wird angezeigt.
. Geben Sie den Wert des Gutscheins ein.
. Schließen Sie den Auftrag wie gewohnt ab. +
→ Der Gutschein-Code wird auf dem Kassenbeleg ausgegeben.
. Händigen Sie dem Kunden den Kassenbeleg aus.
. Wenn Sie auch Gutscheinbelege drucken, händigen Sie dem Kunden auch den Gutscheinbeleg aus. +
*_Hinweis:_* Der Gutschein-Code steht auf dem Gutscheinbeleg und dem Kassenbeleg. Daher sollten Kunden beide Belege mitnehmen, damit niemand sonst den Gutschein einlösen kann.
. Dokumentieren Sie, welchen Gutschein-Code Sie verkauft haben. +
**__Hinweis:__** Jeder Gutschein-Code darf nur einmal verkauft werden, da der Betrag nur einmal eingelöst werden kann.



[#135]
==== Bestandskunde wählen

Standardmäßig wird für Kassiervorgänge der Standardkunde verwendet, der für die Kasse gespeichert wurde. Während des Kassierens haben Sie jedoch auch die Möglichkeit, einen anderen in plentymarkets gespeicherten Kundendatensatz zu wählen. Nachdem Sie den Kassiervorgang abgeschlossen haben, wird für den nächsten POS-Auftrag automatisch wieder der Standardkunde voreingestellt.

Gehen Sie wie unten beschrieben vor, um einen Bestandskunden zu wählen. Eine Suche ist anhand der folgenden Kundeninformationen möglich:

* **Kontakt-ID** = Kontakt-ID des Kunden
* **Kundendaten** = Vorname, Nachname, Firma, Kontaktperson, eBay-Name, Zusatzname, Straße, PLZ, Ort, E-Mail-Adresse, Kundennummer, Externe Kunden-ID, Such-Tags, PostIdent
* **PLZ** = Postleitzahl des Kunden

[.instruction]
Bestandskunde wählen:

. Tippen Sie im POS-Warenkorb unten auf das Kundensymbol. +
→ Die Daten des Standardkunden werden angezeigt.
. Tippen Sie auf die **Lupe**. +
→ Die Ansicht **Kundensuche** wird geöffnet.
. Geben Sie die Kundendaten ein, die Ihnen bekannt sind, um den Kundendatensatz zu suchen.
. Tippen Sie auf **Suchen**. +
→ Die Suchergebnisse werden aufgelistet.
. Tippen Sie auf einen Kundendatensatz. +
→ Die für den Kunden gespeicherten Adressen werden aufgelistet.
. Tippen Sie auf eine Adresse. +
→ Wenn für den Kundendatensatz nur eine Adresse gespeichert ist, ist diese Adresse bereits gewählt.
. Tippen Sie auf **Adresse verwenden**. +
→ Der Kundendatensatz wird gewählt.
. Wenn sich Artikel im POS-Warenkorb befinden, erfolgt die Abfrage **Preise aktualisieren?**. Wenn Sie **Ja** wählen, werden Rabatte, die für die Kundenklasse des gewählten Kunden gelten, auf alle Artikel des Auftrags angewendet. +
→ Die Kundendaten werden übernommen. +
**__Tipp:__** Über das Symbol **Zurücksetzen** können Sie den Standardkunden wiederherstellen.
. Tippen Sie rechts oben auf das **X** oder neben das Fenster, um zurück in den POS-Warenkorb zu springen. +
→ Der gewählte Kunde wird im POS-Warenkorb angezeigt.
. Bearbeiten Sie den Auftrag wie gewohnt weiter. +
→ Nachdem Sie den POS-Auftrag abgeschlossen haben, wird wieder der Standardkunde eingestellt.

[TIP]
.Kassenbeleg per E-Mail an Kunden senden
====
Über eine <<pos/pos-einrichten#70, Ereignisaktion>> kann der Beleg  als Anhang per E-Mail an den Kunden gesendet werden, sobald ein Beleg generiert wird. Bei POS-Aufträgen, die Sie im Offline-Modus abschließen, wird der Beleg jedoch erst versendet, wenn die POS-Aufträge hochgeladen werden.
====

[#100]
==== Notiz zum Auftrag hinzufügen

Um zusätzliche Informationen am Auftrag zu hinterlegen, speichern Sie eine Notiz, bevor Sie den Auftrag abschließen. Notizen werden mit dem Auftrag in das plentymarkets Backend importiert.

[.instruction]
Notiz zum Auftrag hinzufügen:

. Tippen Sie im POS-Warenkorb auf **Notiz**. +
→ Eine Liste der bereits am Auftrag gespeicherten Notizen wird angezeigt.
. Tippen Sie auf **Notiz hinzufügen**. +
→ Das Fenster **Notiz hinzufügen** wird angezeigt.
. Geben Sie den Notiztext ein.
. Tippen Sie auf das Häkchen, um die Notiz am Auftrag zu speichern. +
→ Die Notiz wird in der Liste der Notizen angezeigt und mit dem Auftrag in plentymarkets importiert.
. Tippen Sie auf das **X**, um die Ansicht zu schließen und zurück in die Warenkorbanzeige zu gelangen.

[#110]
==== Kassiervorgang unterbrechen/Bon parken

Wenn sich ein Kassiervorgang verzögert, Sie aber schon Artikel in den POS-Warenkorb gelegt haben, können Sie den aktuellen Stand des Warenkorbs speichern, indem Sie den Bon parken. Auch mehrere Bons können so zwischengespeichert werden.

[#120]
===== Bon parken

Gehen Sie wie unten beschrieben vor, um einen Bon zu parken.

[.instruction]
Bon parken:

. Tippen Sie im POS-Warenkorb oben rechts auf die vertikale Ellipse. +
→ Weitere Optionen werden eingeblendet.
. Tippen Sie auf **Bon parken**. +
→ Das Fenster **Bon parken** wird angezeigt.
. Tippen Sie auf **Ja**. +
→ Der Bon wird gespeichert und ein neuer POS-Warenkorb angezeigt.

[#130]
===== Geparkten Bon laden

Gehen Sie wie unten beschrieben vor, um einen geparkten Bon zu laden und den Kassiervorgang abzuschließen.

[.instruction]
Geparkten Bon laden:

. Tippen Sie im POS-Warenkorb oben rechts auf die vertikale Ellipse. +
→ Weitere Optionen werden eingeblendet.
. Tippen Sie auf **Bon laden**. +
→ Eine Liste der geparkten Bons wird angezeigt.
. Tippen Sie auf den Bon, den Sie laden möchten. +
→ Die geparkten Artikel dieses Bons werden im POS-Warenkorb angezeigt.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter.

[#140]
==== Auftragsposition bearbeiten

//  Diese Einstellungen müssen noch in Einzelkapitel unterteilt und einzeln beschrieben werden.
Sie können Artikel im POS-Warenkorb weiter bearbeiten. Änderungen, die Sie über diese Funktion vornehmen, wirken sich grundsätzlich nur auf diesen Auftrag aus, nicht auf den Datensatz des Artikels im System.

[.instruction]
Auftragspositionen bearbeiten:

. Tippen Sie auf die Auftragsposition im POS-Warenkorb. +
→ Weitere Optionen werden eingeblendet.
. Tippen Sie auf die gewünschte Einstellung. Beachten Sie <<tabelle-POS-kassenpersonal-auftragspositionen-bearbeiten>>.

[[tabelle-POS-kassenpersonal-auftragspositionen-bearbeiten]]
.Auftragspositionen bearbeiten
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Menge ändern**
|Öffnet das Fenster **Menge ändern**. Neue Menge eingeben und auf **OK** tippen, um die Menge des Artikels im Warenkorb anzupassen.

|**Artikelposition umbenennen**
|Neuen Namen eingeben und auf **OK** tippen, um den Namen der Auftragsposition zu ändern. Der Name wird nur in diesem Auftrag geändert. Der Name des Artikels im System bleibt unverändert.

|**Einzelpreis ändern**
|Neuen Preis eingeben und auf **OK** tippen, um den Einzelpreis der gesamten Menge der Auftragspositionen zu ändern. Der Preis wird nur in diesem Auftrag geändert. Der Preis des Artikels im System bleibt unverändert.

|**Gesamtpreis ändern**
|Neuen Preis eingeben und auf **OK** tippen, um den Gesamtpreis der gesamten Menge der Auftragsposition zu ändern. Der Preis wird nur in diesem Auftrag geändert. Der Preis des Artikels im System bleibt unverändert.

|**Artikelpreis zurücksetzen**
|Setzt Preise, die über **Einzelpreis ändern** oder **Gesamtpreis ändern** geändert wurden, auf den ursprünglichen Preis zurück.

|**Rabatt hinzufügen**
|Rabatt in Prozent eingeben und auf **OK** tippen, um einen Rabatt auf die Auftragsposition zu gewähren. Der Preis wird nur in diesem Auftrag geändert. Der Preis des Artikels im System bleibt unverändert. +
*_Hinweis:_* Wenn Rabatte auf einzelne Auftragspositionen hinzugefügt wurden, kann kein Rabatt auf den gesamten POS-Warenkorb eingegeben werden.

|**Rabatt entfernen**
|Setzt Preise, die über **Rabatt hinzufügen** rabattiert wurden, auf den ursprünglichen Preis zurück.

|**Löschen**
|Löscht den Artikel aus dem POS-Warenkorb.
|====


[#170]
==== Rabatt auf gesamten Auftrag anwenden

Statt einzelne Auftragspositionen zu rabattieren, haben Sie auch die Möglichkeit, einen Rabatt auf alle Artikel im POS-Warenkorb anzuwenden, nachdem Sie alle Artikel des Kunden in den POS-Warenkorb gelegt haben. Ein Rabatt auf den gesamten POS-Warenkorb ist allerdings nur möglich, wenn nicht schon ein Rabatt auf einen oder mehrere Artikel im POS-Warenkorb angewendet wurde. Gehen Sie wie hier beschrieben vor, um einen Rabatt auf den gesamten POS-Warenkorb anzuwenden.

[.instruction]
Rabatt auf gesamten Warenkorb anwenden:

. Tippen Sie unten im POS-Warenkorb auf den grün hinterlegten Pfeil nach rechts. +
→ Eine Zusammenfassung des Auftrags und die verfügbaren Zahlungsmethoden werden angezeigt.
. Tippen Sie auf **Gutschein / Rabatt**.
. Geben Sie in das Feld **Gutscheincode/Rabatt** den Rabatt in Prozent ein.
. Tippen Sie auf **Rabatt**. +
→ Die Rabattsumme wird von der Auftragssumme abgezogen und die neue Auftragssumme eingeblendet.
. Tippen Sie auf **Zurück**.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter.

[#450]
=== Online-Bestellungen abschließen (ab Version 1.9)

Viele Unternehmen verkaufen Waren nicht nur im Ladengeschäft, sondern auch über einen Webshop. Waren können also auch über den Webshop bestellt und entweder im Ladengeschäft die bereits bezahlten Artikel abgeholt oder die bestellten Artikel im Ladengeschäft bezahlt und abholt werden. In der Praxis können also die folgenden Fälle auftreten:

* Der Auftrag wurde online bestellt und bezahlt. Die Ware wird im Laden abgeholt.
* Der Auftrag wurde online bestellt. Die Ware wird im Laden bezahlt und abgeholt.

Für das Abschließen von Online-Bestellungen an der Kasse gelten die folgenden Einschränkungen:

* Sie können nur Zahlungen buchen und Notizen speichern. Alle anderen Kassenvorgänge zum Bearbeiten von Online-Bestellungen sind gesperrt.
* Die Aufträge können erst ab App-Version 1.9.2 mit Verkaufsgutscheinen bezahlt werden.
* Die Aufträge können an der Kasse nicht storniert werden.
* Die Auftragsdaten sind nicht änderbar.

[#460]
==== Bezahlte bezahlte Ware aushändigen

* Ein Kunde hat online Artikel bestellt und online bezahlt. Er kommt in den Laden, um die Ware abzuholen. Die Ware ist bereits vollständig bezahlt.

[IMPORTANT]
.Identität prüfen
====
Erkundigen Sie sich, welche Richtlinien es in Ihrem Ladengeschäft gibt, um sicherzustellen, dass Ware, die online bestellt und bezahlt wurde, auch wirklich an die richtige Person ausgehändigt wird.
====

[.instruction]
Bezahlte Online-Bestellung aushändigen:

. Tippen Sie oben rechts im POS-Warenkorb auf das Dreipunktmenü. +
→ Weitere Optionen werden angezeigt.
. Tippen Sie auf *Auftrag laden*. +
→ Die Auftragssuche wird geöffnet.
. Geben Sie in das Feld *Auftrags-ID* die Auftrags-ID ein.
. Tippen Sie auf *Suchen*. +
→ Die Auftragsdaten werden in die Kasse geladen. +
*_Wichtig:_* Vergewissern Sie sich, dass der Kunde wirklich die Person ist, die die Ware bestellt und bezahlt hat. +
. Händigen Sie dem Kunden die Ware aus.
. Tippen Sie auf *Warenausgang buchen*. +
→ Die Ware wird aus dem Lager ausgebucht. +
*_Tipp:_* Um den Auftrag zu verlassen, ohne ihn abzuschließen, tippen Sie auf *Neuer Auftrag*.


[#470]
==== Zahlung für Online-Bestellung buchen (ab Version 1.9)

* Eine Kundin hat online Artikel bestellt. Sie kommt in den Laden, um die Ware abzuholen und vor Ort zu bezahlen.

[.instruction]
Zahlung für Online-Bestellungen buchen:

. Tippen Sie oben rechts im POS-Warenkorb auf das Dreipunktmenü. +
→ Weitere Optionen werden angezeigt.
. Tippen Sie auf *Auftrag laden*. +
→ Die Auftragssuche wird geöffnet.
. Geben Sie in das Feld *Auftrags-ID* die ID des Auftrags ein.
. Tippen Sie auf *Suchen*. +
→ Die Auftragsdaten werden in die Kasse geladen. +
*_Wichtig:_* Vergewissern Sie sich, dass die Kundin die Person ist, die die Ware bestellt hat. +
*_Tipp:_* Um den Auftrag zu verlassen, ohne ihn abzuschließen, tippen Sie oben rechts auf das Dreipunktmenü und dann auf *Neuer Auftrag* oder oben links auf *Zurück*.
. Nehmen Sie wie gewohnt die Zahlung entgegen. +
*_Hinweis:_* Ab App-Version 1.9.2 können Online-Bestellungen auch mit Verkaufsgutscheinen bezahlt werden. +
*_Hinweis:_* Die Auftragsdaten können nicht geändert werden. Sie können nur die Zahlung entgegennehmen und optional eine Auftragsnotiz speichern.
. Händigen Sie der Kundin die Ware aus. +
→ Die Ware wird aus dem Lager ausgebucht. +
*_Hinweis:_* Wenn nach der Zahlung der Button *Warenausgang buchen* angezeigt wird, wird die Ware nur ausgebucht, wenn Sie auf diesen Button tippen. +
→ Erkundigen Sie sich bei Ihrer Vorgesetzten, in welchen Fällen die Ware aus dem Lager ausgebucht werden soll.
. Tippen Sie auf *Neuer Auftrag*, um einen neuen POS-Auftrag zu erstellen.


[#480]
==== Rechnung an der Kasse bezahlen

* Eine Kundin hat einen oder mehrere Artikel entweder im Laden oder online auf Rechnung gekauft. Die Kundin hat die Ware bereits erhalten. Nun möchte sie die Rechnung vor Ort im Laden bezahlen.

[.instruction]
Rechnung an der Kasse bezahlen:

. Tippen Sie oben rechts im POS-Warenkorb auf das Dreipunktmenü. +
→ Weitere Optionen werden angezeigt.
. Tippen Sie auf *Auftrag laden*. +
→ Die Auftragssuche wird geöffnet.
. Geben Sie in das Feld *Auftrags-ID* die ID des Auftrags ein.
. Tippen Sie auf *Suchen*. +
→ Die Auftragsdaten werden in die Kasse geladen. +
*_Hinweis:_* Der Auftrag kann nicht mehr geändert werden. +
*_Tipp:_* Um den Auftrag zu verlassen, ohne ihn abzuschließen, tippen Sie oben rechts auf das Dreipunktmenü und dann auf *Neuer Auftrag* oder oben links auf *Zurück*.
. Nehmen Sie wie gewohnt die Barzahlung und/oder Kartenzahlung entgegen. +
→ Die Ansicht *Auftrag aktualisiert* wird angezeigt. +
. Nehmen Sie wie gewohnt die Zahlung entgegen. +
*_Hinweis:_* Ab App-Version 1.9.2 können Online-Bestellungen auch mit Verkaufsgutscheinen bezahlt werden. +
→ Der Auftrag wird aktualisiert. +
→ Ein Zahlungsbeleg wird gedruckt. Tippen Sie sonst auf *Beleg drucken*, um den Beleg zu drucken. +
Tipp: Über den Button *Auftrag anzeigen* rufen Sie die Auftragsdaten auf.
. Tippen Sie auf *Neuer Auftrag*, um einen neuen POS-Auftrag zu erstellen.


[#173]
== Auftrag stornieren

Über den POS-Menüpunkt **Auftrag stornieren** stornieren Sie abgeschlossene POS-Aufträge, die seit dem letzten Tagesabschluss über die Kasse erstellt wurden. Gehen Sie wie unten beschrieben vor, um einen POS-Auftrag zu stornieren.

[WARNING]
.Stornierung von POS-Aufträgen nur über die Kasse
====
Wenn Sie POS-Aufträge über das plentymarkets Backend stornieren, entstehen Fehler bei den Kassendaten (Tagesabschlüsse, Barbestand etc.). Stornieren Sie POS-Aufträge daher nur über die Kasse und nicht im plentymarkets Backend.
====

[.instruction]
Auftrag stornieren:

. Tippen Sie in der Menüleiste auf das *Menüsymbol*.
. Tippen Sie auf *POS*.
. Tippen Sie auf *Auftrag stornieren*. +
*_Tipp:_* Der Menüpunkt ist nur wählbar, wenn Sie berechtigt sind, Aufträge zu stornieren. +
→ Nicht stornierte Aufträge, die seit dem letzten Tagesabschluss über die Kasse erstellt wurden, werden aufgelistet.
. Tippen Sie in der Zeile des Auftrags auf das Icon *Stornieren*. +
*_Oder:_* Tippen Sie auf den Auftrag, um die Detailansicht zu öffnen, und dort auf das Icon *Stornieren*.
. Bestätigen Sie die Stornierung. +
. *_Je nach Kartenterminal:_* Wählen Sie, ob der stornierte Betrag bar oder über das Terminal zurückerstattet werden soll.
. Zahlen Sie den stornierten Betrag bar aus oder wickeln Sie die Rückzahlung über das Kassenterminal/den Payment-Provider ab. +
*_Hinweis:_* Wenn der Auftrag mit mehr als einer Zahlungsart bezahlt wurde, stornieren Sie jede Zahlung einzeln. +
→ Der Auftrag wird storniert.

[#175]
== Retoure buchen

Wenn Kunden Artikel zurückgeben möchten, haben Sie zwei Möglichkeiten, eine Retoure zu buchen:

* <<#370, Sie öffnen den Hauptauftrag und buchen die Retoure über diesen ursprünglichen Auftrag>>.
* <<#380, Wenn der Hauptauftrag nicht bekannt ist oder nicht geöffnet werden kann, erstellen Sie eine Retoure ohne Hauptauftrag>>.

[IMPORTANT]
.Erstattung nur in bar oder als Gutschein möglich
====
Aus technischen Gründen kann der Retourenbetrag aktuell nur in bar oder als Gutschein an Kunden ausgezahlt werden.
====

[#370]
=== Retoure mit Zuordnung zum Hauptauftrag buchen

Wenn Sie die Auftrags-ID oder die Belegnummer (externe Auftragsnummer) des ursprünglichen Hauptauftrags kennen, rufen Sie diesen Hauptauftrag auf und wickeln die Retoure über diesen Auftrag ab. Gehen Sie wie unten beschrieben vor, um den Hauptauftrag zu öffnen und die Retourenartikel entweder zu <<#330, scannen>> oder <<#340, manuell zu erfassen>>.

[NOTE]
.Verkaufsgutscheine sind von der Retoure ausgeschlossen
====
Kunden können Verkaufsgutscheine nicht zurückgeben. Daher werden Verkaufsgutscheine in der Retourenansicht ausgegraut angezeigt.
====

[#330]
==== Retourenartikel scannen

Wenn Sie mit Scanner arbeiten gehen Sie wie unten beschrieben vor, um Retourenartikel zu erfassen.

[.instruction]
Retourenartikel scannen:

. Tippen Sie im Menü *POS* auf *Retoure*. +
→ Die Retourenansicht wird geöffnet.
. Tippen Sie auf *Auftrag suchen*. +
→ Die Auftragssuche wird geöffnet.
. Geben Sie in das Feld *Externe Auftragsnummer* die Belegnummer ein.
. Tippen Sie auf *Suchen*. +
→ Die Auftragsdaten werden angezeigt. +
→ Je nach Kasseneinstellung sind entweder alle Auftragspositionen oder keine Auftragspositionen für die Retoure vorausgewählt.
. Scannen Sie den Barcode der Artikel, die die Kundin zurückgeben möchte. +
*_Hinweis:_* Der gescannte Artikel wird mit der Menge *1* zur Retoure hinzugefügt. Jeder Artikel, der zurückgegeben werden soll, muss also einzeln gescannt werden. +
→ Als Ziellagerort wird der *Standard-Reparaturlagerort* der Kasse angezeigt.
. *_Optional:_* Wählen Sie einen anderen Ziellagerort: +
  .. Tippen Sie auf den Artikel.
  .. Wählen Sie in der Dropdown-Liste die Option *Ziellagerort ändern*. +
  → Die verfügbaren Lagerorte werden angezeigt.
  .. Scannen Sie den Barcode des Ziellagerorts.
. *_Optional:_* Fügen Sie eine <<pos/pos-kassenbenutzer#100, Notiz zur Retoure hinzu>>.
. Streichen Sie auf dem Kassenbeleg die zurückgegebenen Artikel durch.
. Tippen Sie auf *Abschließen und Bargeld auszahlen* oder auf *Abschließen und Gutschein erstellen*. +
. Wenn der Hauptauftrag Versandkosten enthält, wählen Sie, ob diese Versandkosten erstattet werden sollen. +
→ Im plentymarkets Backend wird eine Retoure erstellt und mit dem Hauptauftrag verknüpft. +
→ Im plentymarkets Backend wird eine Gutschrift erstellt und mit der Retoure verknüpft. +
→ Bei Gutscheinerstellung wird ein neuer Auftrag in Höhe des Retourenbetrags erstellt.
. Zahlen Sie den Retourenbetrag aus oder händigen Sie den Gutschein aus.

[#340]
==== Retourenartikel manuell erfassen

Wenn Sie ohne Scanner arbeiten, erfassen Sie die Retourenartikel manuell. Wie Sie dabei vorgehen ist jedoch davon abhängig, wie die Kasse eingestellt ist. Denn je nach Kasseneinstellung sind beim Öffnen des Auftrags entweder alle Artikel eines Auftrags für die Retoure vorausgewählt oder es sind keine Artikel für die Retoure vorausgewählt. Der Retourenwarenkorb ist also beim Öffnen des Auftrags entweder voll oder leer:

* Alle Auftragspositionen sind vorausgewählt, wenn Sie den Auftrag öffnen. +
→ <<#350, Entfernen Sie die Artikel aus der Retoure, die nicht zurückgegeben werden sollen.>> +
*_Tipp:_* Beim Öffnen des Auftrags wird rechts neben den Auftragspositionen ein Papierkorbsymbol angezeigt, über das Sie die Artikel entfernen.
* Keine Auftragspositionen sind vorausgewählt, wenn Sie den Auftrag öffnen. +
→ <<#360, Fügen Sie die Artikel zur Retoure hinzu, die zurückgegeben werden sollen.>> +
*_Tipp:_* Beim Öffnen des Auftrags sind alle Auftragspositionen ausgegraut. Rechts neben den Auftragspositionen wird ein grünes Plus angezeigt, über das Sie die Artikel hinzufügen.

Ob Sie beim Öffnen des Hauptauftrags einen vollen oder einen leeren Retourenwarenkorb sehen, wird in den Grundeinstellungen der Kasse im plentymarkets Backend über die Funktion *Retoure mit Hauptauftrag: Zu retournierende Auftragspositionen manuell wählen* festgelegt.

[#350]
[.subhead]
Retourenartikel manuell erfassen, Auftragspositionen vorausgewählt

Wenn Sie im Bereich *Retoure* einen Auftrag öffnen, sind alle Auftragspositionen des Auftrags für die Retoure vorgemerkt. Gehen Sie wie unten beschrieben vor, um die Auftragspositionen aus der Retoure entfernen, die die Kundin nicht zurückgeben möchte.

[TIP]
.Sind die Retourenartikel vorausgewählt?
====
Ob Retourenartikel beim Öffnen des Auftrags vorausgewählt sind hängt davon ab, wie die Kasse eingestellt ist. Dass die Retourenartikel vorausgewählt sind erkennen Sie daran, dass rechts neben den Auftragspositionen ein kleiner Papierkorb angezeigt wird. An diesem Papierkorbsymbol erkennen Sie, dass der Retourenwarenkorb voll ist und Sie die Artikel entfernen müssen, die die Kundin nicht zurückgeben möchte.
====

[.instruction]
Retourenartikel manuell erfassen, wenn alle Auftragspositionen vorausgewählt sind:

. Tippen Sie im Menü *POS* auf *Retoure*. +
→ Die Retourenansicht wird geöffnet.
. Tippen Sie auf *Auftrag suchen*. +
→ Die Auftragssuche wird geöffnet.
. Geben Sie in das Feld *Externe Auftragsnummer* die Belegnummer ein.
. Tippen Sie auf *Suchen*. +
→ Die Auftragsdaten werden angezeigt. +
→ Alle Auftragspositionen des Auftrags sind für die Retoure vorausgewählt. +
*_Tipp:_* Wenn der Kunde alle Artikel des Auftrags zurückgeben möchte, tippen Sie einfach sofort auf *Retoure erstellen*.
. Entfernen Sie die Artikel aus der Retoure, die nicht zurückgegeben werden sollen. +
  .. Um die gesamte Menge einer Auftragsposition aus der Retoure zu entfernen: +
    1. Tippen Sie auf den Papierkorb neben der Auftragsposition. +
  .. Um eine Teilmenge einer Auftragsposition aus der Retoure zu entfernen:
    1. Tippen Sie auf die Auftragsposition. +
    → Weitere Optionen werden eingeblendet.
    2. Tippen Sie auf *Menge ändern*. +
    → Das Fenster *Menge ändern* wird angezeigt.
    3. Geben Sie die Anzahl des Artikels ein, die zurückgegeben wird. +
→ Die Menge der Auftragsposition wird aktualisiert. +
→ Als Ziellagerort wird der *Standard-Reparaturlagerort* der Kasse angezeigt.
. *_Optional:_* Wählen Sie einen anderen Ziellagerort für den Artikel: +
  .. Tippen Sie auf den Artikel.
  .. Wählen Sie in der Dropdown-Liste die Option *Ziellagerort ändern*. +
  → Die verfügbaren Lagerorte werden in der folgenden Reihenfolge angezeigt:
    1. Lagerort aus Auftrag = Der Lagerort, an dem der Artikel lag, als er verkauft wurde.
    2. Standard-Reparaturlagerort = Der im Tab *Grundeinstellungen* der Kasse festgelegte *Reparturlagerort*.
    3. Lagerortvorschläge = Die Lagerortvorschläge der Lager, die mit der Variante verknüpft sind.
    4. Verwendete Lagerorte = Die Lagerorte, in denen die Variante bereits lagert.
  .. Tippen Sie auf einen Ziellagerort. +
  → Der Ziellagerort wird geändert. +
  *_Tipp:_* Über die Option *Ziellagerorte ändern* im Menü oben rechts ändern Sie die Ziellagerorte aller Retourenartikel gleichzeitig.
. *_Optional:_* Ändern Sie die Menge und Lagerorte weiterer Auftragspositionen.
. *_Optional:_* Fügen Sie eine <<pos/pos-kassenbenutzer#100, Notiz zur Retoure hinzu>>.
. Streichen Sie auf dem Kassenbeleg die zurückgegebenen Artikel durch.
. Tippen Sie auf *Abschließen und Bargeld auszahlen* oder auf *Abschließen und Gutschein erstellen*. +
. Wenn der Hauptauftrag Versandkosten enthält, wählen Sie, ob diese Versandkosten erstattet werden sollen. +
→ Im plentymarkets Backend wird eine Retoure erstellt und mit dem Hauptauftrag verknüpft. +
→ Im plentymarkets Backend wird eine Gutschrift erstellt und mit der Retoure verknüpft. +
→ Bei Gutscheinerstellung wird ein neuer Auftrag in Höhe des Retourenbetrags erstellt.
. Zahlen Sie den Retourenbetrag aus oder händigen Sie den Gutschein aus.

[#360]
[.subhead]
Retourenartikel manuell erfassen, Auftragspositionen nicht vorausgewählt

Wenn Sie im Bereich *Retoure* einen Auftrag öffnen, sind keine Auftragspositionen des Auftrags für die Retoure vorgemerkt. Gehen Sie wie unten beschrieben vor, um die Auftragspositionen zur Retoure hinzuzufügen, die der Kunde zurückgeben möchte.

[TIP]
.Sind die Retourenartikel vorausgewählt?
====
Ob Retourenartikel beim Öffnen des Auftrags vorausgewählt sind hängt davon ab, wie die Kasse eingestellt ist. Dass die Retourenartikel nicht vorausgewählt sind erkennen Sie daran, dass die Auftragspositionen ausgegraut sind und rechts daneben ein grünes Plus angezeigt wird. An diesem grünen Plus erkennen Sie, dass der Retourenwarenkorb leer ist und Sie die Artikel hinzufügen müssen, die die Kundin zurückgeben möchte.
====

[.instruction]
Retourenartikel manuell erfassen, wenn keine Auftragspositionen vorausgewählt sind:

. Tippen Sie im Menü *POS* auf *Retoure*. +
→ Die Retourenansicht wird geöffnet.
. Tippen Sie auf *Auftrag suchen*. +
→ Die Auftragssuche wird geöffnet.
. Geben Sie in das Feld *Externe Auftragsnummer* die Belegnummer ein.
. Tippen Sie auf *Suchen*. +
→ Die Auftragsdaten werden angezeigt. +
→ Keine Auftragspositionen sind für die Retoure vorausgewählt.
. Fügen Sie die Artikel zur Retoure hinzu, die zurückgegeben werden sollen. +
  .. Um die gesamte Menge einer Auftragsposition zur Retoure hinzuzufügen: +
    1. Tippen Sie auf das grüne Plus neben der Auftragsposition. +
    → Die gesamte Stückzahl wird zur Retoure hinzugefügt. +
    → Als Ziellagerort wird der *Standard-Reparaturlagerort* der Kasse angezeigt.
  .. Um eine Teilmenge einer Auftragsposition zur Retoure hinzuzufügen:
    1. Tippen Sie auf das grüne Plus neben der Auftragsposition. +
  → Die gesamte Stückzahl wird zur Retoure hinzugefügt.
    2. Tippen Sie auf die Auftragsposition. +
    → Weitere Optionen werden eingeblendet.
    3. Tippen Sie auf *Menge ändern*. +
    → Das Fenster *Menge ändern* wird angezeigt.
    4. Geben Sie die Anzahl des Artikels ein, die zurückgegeben wird. +
    → Die Menge der Auftragsposition wird aktualisiert. +
    → Als Ziellagerort wird der *Standard-Reparaturlagerort* der Kasse angezeigt.
. *_Optional:_* Wählen Sie einen anderen Ziellagerort für den Artikel: +
  .. Tippen Sie auf den Artikel.
  .. Wählen Sie in der Dropdown-Liste die Option *Ziellagerort ändern*. +
  → Die verfügbaren Lagerorte werden in der folgenden Reihenfolge angezeigt:
   	1. Lagerort aus Auftrag = Der Lagerort, an dem der Artikel lag, als er verkauft wurde.
   	2. Standard-Reparaturlagerort = Der im Tab *Grundeinstellungen* der Kasse festgelegte *Reparturlagerort*.
   	3. Lagerortvorschläge = Die Lagerortvorschläge der Lager, die mit der Variante verknüpft sind.
   	4. Verwendete Lagerorte = Die Lagerorte, in denen die Variante bereits lagert.
  .. Tippen Sie auf einen Ziellagerort. +
  → Der Ziellagerort wird geändert. +
  *_Tipp:_* Über die Option *Ziellagerorte ändern* im Menü oben rechts ändern Sie die Ziellagerorte aller Retourenartikel gleichzeitig.
. *_Optional:_* Fügen Sie eine <<pos/pos-kassenbenutzer#100, Notiz zur Retoure hinzu>>.
. Streichen Sie auf dem Kassenbeleg die zurückgegebenen Artikel durch.
. Tippen Sie auf *Abschließen und Bargeld auszahlen* oder auf *Abschließen und Gutschein erstellen*. +
. Wenn der Hauptauftrag Versandkosten enthält, wählen Sie, ob diese Versandkosten erstattet werden sollen. +
→ Im plentymarkets Backend wird eine Retoure erstellt und mit dem Hauptauftrag verknüpft. +
→ Im plentymarkets Backend wird eine Gutschrift erstellt und mit der Retoure verknüpft. +
→ Bei Gutscheinerstellung wird ein neuer Auftrag in Höhe des Retourenbetrags erstellt.
. Zahlen Sie den Retourenbetrag aus oder händigen Sie den Gutschein aus.

[#440]
==== Preis von Retourenartikeln ändern

Wenn nicht der volle Kaufpreis erstattet werden soll, zum Beispiel, weil Artikel beschädigt sind, ändern Sie den Preis einer Auftragsposition.

. Tippen Sie in der Retoure auf die Auftragsposition. +
→ Weitere Optionen werden eingeblendet.
. Tippen Sie auf *Einzelpreis ändern*, um den Einzelpreis der Auftragsposition zu ändern, oder auf *Gesamtpreis ändern*, um den Gesamtpreis der Auftragsposition zu ändern. +
→ Der Preis der Auftragsposition wird aktualisiert.
. Schließen Sie die Retoure wie gewohnt ab.

[#320]
==== Hinweise zu Retouren bei Kauf auf Rechnung

Wenn Sie Kunden Anzahlungen oder den Kauf auf Rechnung anbieten kann es vorkommen, dass Kunden Artikel aus Aufträgen zurückgeben möchten, die noch nicht oder nur teilweise bezahlt sind. plentymarkets POS berechnet automatisch, ob Sie dem Kunden Geld auszahlen sollen oder nicht. <<tabelle-POS-Retoure-Rechnung>> verdeutlicht die Berechnung, die im Hintergrund stattfindet, damit Sie Kunden diese Berechnung bei Bedarf erklären können.

[[tabelle-POS-Retoure-Rechnung]]
.Retourenfälle bei Kauf auf Rechnung
[cols="1,3,3"]
|====
|Rechnungsstatus |Teilretoure |Vollretoure

|*Nicht bezahlt*
|Sie zahlen kein Geld aus. +
Im Hintergrund wird eine Gutschrift für zurückgegebenen Artikel erstellt. +
*_Tipp:_* Der Rechnungsbetrag, den der Kunde noch bezahlen muss, steht auf dem Gutschriftsbeleg.
|Der Kunde bekommt kein Geld zurück. +
Im Hintergrund wird eine Gutschrift für den vollen Rechnungsbetrag erstellt.

|*Teilweise bezahlt*
a|Die Kasse errechnet automatisch, ob und wenn ja wie viel Geld der Kunde zurück bekommt. Vereinfacht lautet die Formel: Offener Rechnungsbetrag minus Preis der zurückgegebenen Artikel.

Bei Teilzahlung sind die folgenden Fälle möglich: +

* Zurückgegebene Artikel kosten weniger als der noch offene Rechnungsbetrag = Sie zahlen kein Geld aus. +
Der offene Rechnungsbetrag wird angepasst (Noch offener Betrag minus Preis des zurückgegebenen Artikels). +
Eine Gutschrift über den Preis des zurückgegebenen Artikels wird erstellt. +

* Preis der zurückgegebenen Artikel entspricht dem noch offenen Rechnungsbetrag = Sie zahlen kein Geld aus. +
Eine Gutschrift über den Preis des zurückgegebenen Artikels wird erstellt. +

* Zurückgegebene Artikel kosten mehr als der noch offene Rechnungsbetrag = Sie zahlen die Differenz aus dem offenen Betrag minus dem Preis des zurückgegebenen Artikels aus.  +

Im Hintergrund wird bei der Retoure eine Gutschrift für die zurückgegebenen Artikel erstellt. Dabei stimmen der Gutschriftsbetrag und der ausgezahlte Betrag nicht unbedingt überein. Wenn der ausgezahlte Betrag nicht mit dem Gutschriftsbetrag übereinstimmt, ist der ausbezahlte Betrag auf dem Gutschriftsbeleg vermerkt.

|Sie zahlen den Betrag aus, den der Kunde bisher bezahlt hat. +
Der Gutschriftbetrag ist gleich dem vollen Rechnungsbetrag.
|====

[#380]
=== Retoure ohne Zuordnung zum Hauptauftrag buchen

In Fällen, in denen der Hauptauftrag nicht bekannt ist oder nicht aufgerufen werden kann, bietet plentymarkets POS auch die Möglichkeit, eine Retoure zu erstellen, die keinem Hauptauftrag zugeordnet ist. Das bedeutet, dass datentechnisch keine Verbindung zwischen dem ursprünglichen Auftrag und der Retoure besteht. Gehen Sie wie unten beschrieben vor, um eine Retoure ohne Zuordnung zum Hauptauftrag zu buchen.

[.instruction]
Retoure ohne Zuordnung zum Hauptauftrag buchen:

. Tippen Sie im Menü *POS* auf *Retoure*. +
→ Die Retourenansicht wird geöffnet.
. Fügen Sie die Retourenartikel per Scan oder über die Artikelsuche hinzu. +
*_Hinweis:_* Artikel mit MHD-/Chargen-Daten werden nicht gefunden. +
→ Als Ziellagerort wird der *Standard-Reparaturlagerort* der Kasse angezeigt.
. *_Optional:_* Wählen Sie einen anderen Ziellagerort für den Artikel: +
 .. Tippen Sie auf den Artikel.
 .. Wählen Sie in der Dropdown-Liste die Option *Ziellagerort ändern*. +
 → Die verfügbaren Lagerorte werden in der folgenden Reihenfolge angezeigt:
   1. Lagerort aus Auftrag = Der Lagerort, an dem der Artikel lag, als er verkauft wurde.
   2. Standard-Reparaturlagerort = Der im Tab *Grundeinstellungen* der Kasse festgelegte *Reparturlagerort*.
   3. Lagerortvorschläge = Die Lagerortvorschläge der Lager, die mit der Variante verknüpft sind.
   4. Verwendete Lagerorte = Die Lagerorte, in denen die Variante bereits lagert.
 .. Tippen Sie auf einen Ziellagerort. +
 → Der Ziellagerort wird geändert. +
 *_Tipp:_* Über die Option *Ziellagerorte ändern* im Menü oben rechts ändern Sie die Ziellagerorte aller Retourenartikel gleichzeitig.
 . *_Optional:_* Passen Sie <<pos/pos-kassenbenutzer#140, den Preis des Artikels an>>.
 . *_Optional:_* Fügen Sie eine <<pos/pos-kassenbenutzer#100, Notiz zur Retoure hinzu>>.
. Wenn Sie alle Retourenartikel eingegeben haben, tippen Sie auf den grün hinterlegten Pfeil. +
→ Die Gesamtsumme der Retoure wird angezeigt.
. Tippen Sie auf *Abschließen und Bargeld auszahlen* oder auf *Abschließen und Gutschein erstellen*. +
→ Im plentymarkets Backend wird eine Retoure ohne Hauptauftrag erstellt. +
→ Im plentymarkets Backend wird eine Gutschrift ohne Hauptauftrag erstellt. +
→ Bei Gutscheinerstellung wird ein neuer Auftrag in Höhe des Retourenbetrags erstellt.
. Zahlen Sie den Retourenbetrag aus oder händigen Sie den Gutschein aus.


[#180]
== Einlage oder Entnahme buchen

Auch Bargeldbewegungen aus und in die Kasse, die nicht durch das Buchen von Aufträgen entstehen, müssen erfasst werden. Wird Bargeld in die Kasse gelegt, zum Beispiel um ausreichend Wechselgeld vorzuhalten, findet eine Einlage statt. Wenn Bargeld aus der Kasse entnommen wird, sprechen wir von einer Entnahme. Bargeld wird zum Beispiel aus der Kasse genommen, um das Geld auf der Bank einzuzahlen. Gehen Sie wie unten beschrieben vor, um Einlagen und Entnahmen zu buchen.

[#190]
=== Einlage buchen

Gehen Sie wie unten beschrieben vor, um eine Einlage zu buchen.

[.instruction]
Einlage buchen:

. Tippen Sie in der Menüleiste auf das *Menüsymbol*.
. Tippen Sie auf *POS*. +
→ Das *POS-Menü* wird eingeblendet.
. Tippen Sie auf *Einlagen und Entnahmen*. +
→ Das Menü *Einlage/Entnahme* wird eingeblendet.
. Wählen Sie im Bereich *Grund* die Art des Einlagevorfalls aus der Dropdown-Liste.
. *_Optional:_* Geben Sie in das Feld *Zusätzliche Angaben* weitere Informationen zu der Einlage ein.
. Tippen Sie den Betrag ein, der in die Kasse eingezahlt wird.
. Tippen Sie auf *Einlage*, um die Einlage zu speichern. +
→ Der Ist-Kassenbestand wird aktualisiert. +
→ Ein Beleg für die Einlage wird gedruckt. +
→ Der Beleg wird in plentymarkets importiert und im Menü *Aufträge » Dokumentenarchiv* gespeichert.

[#200]
=== Entnahme buchen

Gehen Sie wie unten beschrieben vor, um eine Entnahme zu buchen.

[.instruction]
Entnahme buchen:

. Tippen Sie in der Menüleiste auf das *Menüsymbol*.
. Tippen Sie auf *POS*. +
→ Das *POS-Menü* wird eingeblendet.
. Tippen Sie auf *Einlagen und Entnahmen*. +
→ Das Menü *Einlage/Entnahme* wird eingeblendet.
. Wählen Sie im Bereich *Grund* die Art des Entnahmevorfalls aus der Dropdown-Liste.
. *_Optional:_* Geben Sie in das Feld *Zusätzliche Angaben* weitere Informationen zu der Entnahme ein.
. Tippen Sie den Betrag ein, der aus der Kasse genommen wird.
. Tippen Sie auf *Entnahme*, um die Entnahme zu speichern. +
→ Der Ist-Kassenbestand wird aktualisiert. +
→ Ein Beleg für die Entnahme wird gedruckt. +
→ Der Beleg wird in plentymarkets importiert und im Menü *Aufträge » Dokumentenarchiv* gespeichert.

[#300]
== Artikeletikett drucken

Wenn Sie mit plentyBase und Etikettendruckern arbeiten, können Sie in der Artikelsuche der plentymarkets App auch Artikeletiketten drucken. Wie das geht, erfahren Sie im Kapitel <<artikel/artikel-verwalten#3340, Etikett in der Artikelsuche der plentymarkets App drucken>>.

[#210]
== Berichte erstellen

In plentymarkets POS können Sie Zwischenberichte und Tagesberichte erstellen.

[#220]
=== Zwischenbericht erstellen

Mit Zwischenberichten informieren Sie sich im laufenden Betrieb über die Umsätze, die seit dem letzten Tagesabschluss über die Kasse generiert wurden. Sie können beliebig viele Zwischenberichte erstellen. Zwischenberichte werden nicht in plentymarkets importiert. Das Erstellen von Zwischenberichten wird also nicht langfristig dokumentiert. Zwischenberichte werden auch als X-Berichte bezeichnet.

Zwischenberichte enthalten folgende Informationen:

* Barbestand: Anfangsbarbestand, Entnahmen, Einlagen, Soll-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retournierte Artikel: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufsgutscheine: Anzahl und Summe verkaufter Gutscheine
* Benutzer: Umsatz, Stornierungen und Retouren pro Benutzer

[.instruction]
Zwischenbericht erstellen:

. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**. +
→ Das **POS-Menü** wird eingeblendet.
. Tippen Sie auf **Zwischenbericht**. +
**__Hinweis:__** Wenn der Menüpunkt ausgegraut ist, benötigen Sie zusätzliche <<pos/pos-einrichten#170, Berechtigungen>>, um Zwischenberichte zu erstellen. +
→ Der Zwischenbericht wird gedruckt.

[#230]
=== Tagesabschluss erstellen

Ein Tagesabschlussbericht dokumentiert die seit dem letzten Tagesabschlussbericht getätigten Umsätze. Durch das Drucken eines Tagesabschlussberichts werden die Tagesumsätze außerdem auf 0 zurückgesetzt. Die Tagesabschlussberichte werden mit einer fortlaufenden Nummer versehen und in plentymarkets gespeichert. Tagesabschlussberichte dienen als Nachweis gegenüber dem Finanzamt. Tagesabschlussberichte werden auch als Z-Berichte bezeichnet.

[TIP]
.Tagesabschlussbericht nachdrucken
====
Tagesabschlussberichte werden im plentymarkets Backend gespeichert. Öffnen Sie das Menü <<auftraege/dokumentenarchiv#_archivierte_pdf_dokumente_suchen, Aufträge » Dokumentenarchiv>>. Filtern Sie nach dem Dokumenttyp *Tagesabschluss*. In der Spalte *Datei* kann der Bericht als PDF-Datei heruntergeladen werden.
====

Tagesabschlussberichte enthalten folgende Informationen:

* Barbestand: Entnahmen, Einlagen, Soll-Kassenbestand, Ist-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retournierte Artikel: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufte Gutscheine: Anzahl und Summe
* Benutzer: Umsatz, Stornierungen und Retouren pro Benutzer


[.instruction]
Tagesabschluss erstellen:

. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**. +
→ Das **POS-Menü** wird eingeblendet.
. Tippen Sie auf **Tagesabschluss**. +
→ Der Soll-Kassenbestand wird eingeblendet.
. Prüfen Sie den tatsächlichen Kassenbestand und geben Sie diesen Ist-Bestand ein.
. Tippen Sie auf **Tagesabschluss erstellen**. +
**__Hinweis:__** Wenn der Menüpunkt ausgegraut ist, benötigen Sie zusätzliche <<pos/pos-einrichten#170, Berechtigungen>>, um Tagesberichte zu erstellen. +
→ Der Tagesabschlussbericht wird in plentymarkets importiert. +
→ Der Tagesabschlussbericht wird im Menü *Aufträge » Dokumentenarchiv* gespeichert. +
→ Der Tagesabschlussbericht wird gedruckt. +
→ Die Tagesumsätze werden auf 0 zurückgesetzt. +
→ Für Kassen mit Standort Österreich wird ein Nullbeleg erstellt und im Kassenjournal gespeichert.

[TIP]
.Tagesabschluss für Kartenzahlungen
====
Wenn Sie ein Karten-Terminal an plentymarkets POS angebunden haben, können Sie bei einigen Terminals gleichzeitig mit dem plentymarkets POS Tagesabschluss einen Tagesabschluss für die Umsätze des Karten-Terminals anstoßen. Beantworten Sie die angezeigte Frage **Gleichzeitig Tagesabschluss für Terminal erstellen?** mit **Ja**, um die Kartenumsätze an den Netzbetreiber zu übermitteln und auf 0 zurückzusetzen.
====

[#450]
=== Kassensturzbericht erstellen

Ein Kassensturz dient dazu, den Kassenbestand zu dokumentieren, also den Bargeldbestand in Form von Geldscheinen und Münzen zu einem bestimmten Zeitpunkt. Dazu wird der Barbestand einer Kasse physisch gezählt. Aus dem Ergebnis der Zählung wird ein Zählprotokoll erstellt. Aktuell ist systemseitig die Eingabe einer Zählung von Münzen und Scheinen in den Währungen Euro, Schweizer Franken und Britische Pfund möglich.

[#460]
==== Kassensturzergebnis erfassen

Wenn Sie einen Kassensturz durchführen und das Ergebnis über plentymarkets POS erfassen, können Sie entweder die Anzahl der einzelnen Münzen und Geldscheine eingeben oder das Ergebnis der Zählung als Gesamtbetrag eingeben. Gehen Sie wie unten beschrieben vor, um das Ergebnis eines Kassensturzes zu dokumentieren.

[.instruction]
Kassensturzergebnis erfassen:

. Melden Sie sich bei der plentymarkets App an.
. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**. +
→ Das POS-Menü wird angezeigt.
. Tippen Sie auf **Kassensturz**. +
→ Das Menü **Kassensturz** wird angezeigt. Die Stückelung **1 Cent** ist automatisch ausgewählt.
. Geben Sie über das Ziffernfeld die Menge der vorhandenen 1-Cent-Stücke ein.
. Tippen Sie auf den grünen Return-Pfeil, um zur nächsten Stückelung zu springen.
. Wiederholen Sie den Vorgang, bis Sie die Menge für alle vorhandenen Münzen und Geldscheine eingegeben haben. +
*_Oder:_* Um statt Stückelung und Menge den Gesamtbetrag einzugeben, tippen Sie in das Feld **Überschreiben** und geben Sie den gezählten Betrag ein.
. Tippen Sie auf **Kassensturz speichern**. +
→ Ein Kassensturzbericht wird erstellt und im Menü **Aufträge » Dokumentenarchiv** gespeichert.
. **__Optional:__** Tippen Sie auf **Kassensturzbericht drucken**, um den Bericht zu drucken.
. Wenn der Ist-Kassenbestand vom Soll-Kassenbestand abweicht, gehen Sie wie unten beschrieben vor, um die Differenz zu buchen.

[#470]
==== Differenz aus Kassensturz buchen

Wenn nach dem Zählen des Barbestands der Ist-Kassenbestand vom Soll-Kassenbestand abweicht, muss die Differenz entweder ausgeglichen oder gebucht werden. Wenn Sie die Differenz buchen, wird der Ist-Kassenbestand als neuer Soll-Kassenbestand übernommen. Gleichzeitig wird abhängig vom Vorzeichen des Differenzbetrags entweder eine Einlage oder eine Entnahme gebucht:

* Ist der Ist-Kassenbestand größer als der Soll-Kassenbestand, wird eine Einlage gebucht.
* Ist ein Minusbetrag in der Kasse, wird eine Entnahme gebucht.

Wenn Sie die Differenz eines Kassensturzes buchen, wird als Grund automatisch **Differenz aus Kassensturz** gespeichert.

[.instruction]
Differenz buchen:

. Tippen Sie nach dem Speichern des Kassensturzes auf **Differenz buchen**, um den Ist-Kassenbestand als neuen Soll-Kassenbestand zu speichern. +
→ Für den Differenzbetrag wird eine Einlage oder eine Entnahme mit dem Grund **Differenz aus Kassensturz** erstellt und im Menü **Aufträge » Dokumentenarchiv » Kassenbeleg** gespeichert. +
→ Der Ist-Kassenbestand wird als neuer Soll-Kassenbestand gespeichert.

[#280]
== Besonderheiten in Österreich

Österreichische Kassen sind mit einer Signatureinheit ausgestattet. Daraus ergeben sich einige Besonderheiten, die im Folgenden näher beschrieben werden.

[#260]
=== Monatsbeleg erstellen (Österreich)

Monatsbelege sind signierte Kontrollbelege mit einem Betrag von Null (0,00) Euro. Laut RKSV muss am Ende jedes Monats ein Monatsbeleg erstellt werden. Der Monatsbeleg für den Monat Dezember dient gleichzeitig als Jahresbeleg.

[.instruction]
Monatsbeleg erstellen (Österreich):

. Melden Sie sich bei der plentymarkets App an.
. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**. +
→ Das POS-Menü wird angezeigt.
. Tippen Sie auf **Monatsbeleg (AT)**. +
→ Der Monatsbeleg wird gedruckt. +
→ Der Monatsbeleg wird in plentymarkets importiert und im Menü **Aufträge » Dokumentenarchiv** gespeichert.

=== Bei Ausfall der Signatureinheit kassieren (Österreich)

Der Gesetzgeber gibt vor, wie Sie vorgehen sollen, falls die Signatureinheit der Registrierkasse ausfällt.

* Notieren Sie sich den Zeitpunkt des Ausfalls.
* Weichen Sie wenn möglich auf eine Registrierkasse mit funktionierender Signatureinheit aus.
* Wenn keine andere Kasse verfügbar ist, können Sie trotz ausgefallener Signatureinheit weiter kassieren. Alle Belege werden dann mit dem Hinweis *Sicherheitseinrichtung ausgefallen* versehen.
* Sobald die Signatureinheit wieder funktioniert, wird in plentymarkets POS automatisch ein Sammelbeleg erstellt und gedruckt.

Diese Schritte sind Empfehlungen zum Einhalten der RKSV. Erkundigen Sie sich außerdem bei Ihrer Vorgesetzten, wie Sie bei einem Ausfall genau vorgehen sollen.

[#270]
=== Kontrollbeleg auf Verlangen der Finanzpolizei erstellen (Österreich)

Bei einer Kassenrückschau durch die Finanzpolizei muss auf Verlangen ein Kontrollbeleg mit dem Betrag Null erstellt werden. Dieser Kontrollbeleg ermöglicht der prüfenden Person, die Gültigkeit der Signatur mit einer Prüf-App direkt vor Ort in Ihrem Laden zu prüfen. Sie benötigen keine zusätzlichen Benutzerrechte, um den Kontrollbeleg zu erstellen.

[.instruction]
Kontrollbeleg auf Verlangen erstellen:

. Melden Sie sich bei der plentymarkets App an.
. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**. +
→ Das POS-Menü wird angezeigt.
. Tippen Sie auf **Kontrollbeleg**. +
→ Der Kontrollbeleg wird gedruckt. +
→ Der Kontrollbeleg wird in plentymarkets importiert und im Menü **Aufträge » Dokumentenarchiv** gespeichert. +
**__Hinweis:__** Die Finanzpolizei darf den Kontrollbeleg als Beweismittel einbehalten.

// Next: [#490]
