= POS einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, POS, Kasse, Kassensystem, Kassen, IDEA-Export, IDEA, GoBD, Kassenjournal, Kassenbuch, GoBD konform, Registrierkasse, RKSV, DEP-Export, mobile Kasse, mobile Registrierkasse, Smartphone-Kasse, Kasse Sicherheitseinrichtung, Vertrauensdiensteanbieter POS, Vertrauensdiensteanbieter Kasse, Registrierkassensicherheitsverordnung, Kasse Österreich, POS Österreich, rechtssichere Kasse, RKSV-konform, plentyPOS, RKSV, Startbeleg, QR-Code, mobile Kassa, Kassasoftware, Kassensoftware, Kassa-Software, Kassen-Software, Laufkundschaft, Laufkunden
:position: 10
:url: pos/pos-einrichten

Mit dem mobilen Kassensystem plentymarkets POS integrierst du den stationären Handel mühelos in plentymarkets. Das Kassensystem plentymarkets POS wird über die plentymarkets App bereitgestellt.

[IMPORTANT]
.POS-Einstellungen nicht im laufenden Betrieb ändern
====
Ändere die POS-Einstellungen nicht im laufenden Betrieb. Wenn du dennoch Änderungen an den POS-Einstellungen vornimmst, fordere das Kassenpersonal auf, sich aus der App auszuloggen und wieder einzuloggen, da sonst vor allem bei einer Änderung der Rundungseinstellungen Unstimmigkeiten in den Gesamtbeträgen entstehen.
====

[#10]
== Unterstützte Hardware für plentymarkets POS

Das Kassensystem plentymarkets POS wird über die plentymarkets App bereitgestellt. Für den Einsatz von plentymarkets POS bestehen jedoch zusätzliche Hardware-Voraussetzungen. Informationen zu den Systemvoraussetzungen für die plentymarkets App und plentymarkets POS findest du auf der Handbuchseite <<schnelleinstieg/systemvoraussetzungen#50, Systemvoraussetzungen>>.

Die plentymarkets App lädst du kostenlos über die folgenden Appstores herunter:

* link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=de[plentymarkets App bei Google Play^]

* link:https://itunes.apple.com/de/app/plentymarkets/id957702618[plentymarkets App bei iTunes^]

== Unterstützte Währungen

plentymarkets POS ist für das Kassieren mit den Währungen Euro (EUR), Schweizer Franken (CHF) und Britische Pfund (GBP) vorbereitet. Du kannst die Kasse allerdings nur in der <<payment/waehrungen#30, Systemwährung>> betreiben. Die Systemwährung legst du im Menü *System » Systemeinstellungen » Aufträge » Zahlung » Währungen* fest.

[#20]
== plentymarkets POS Kasse buchen

Um plentymarkets POS verwenden zu können, buche zunächst im plentymarkets Konfigurator eine oder mehrere Kassen. Informationen zu den Konditionen findest du im Konfigurator oder auf der plentymarkets POS Produktseite.

[#30]
== Kasse einrichten

Nachdem du Kassen gebucht hast, richtest du diese Kassen im plentymarkets Backend ein. Zunächst weist du die Kassen einem Mandanten zu, indem du die Kasse im Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS** erstellst und weitere Einstellungen vornimmst. Gehe dazu wie unten beschrieben vor.

[#40]
=== Kasse erstellen

Erstelle zunächst im plentymarkets Backend eine Kasse für den gewünschten Mandanten (Shop).

[.instruction]
Kasse für Mandanten erstellen:

. Öffne das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Klicke auf **Neue Kasse**. +
→ Das Fenster **Neue Kasse** wird eingeblendet.
. Gib einen Namen für die Kasse ein.
. **Speichere** die Einstellungen. +
→ Der Kasse wird eine Herkunft zugeordnet. +
→ Die Kasse wird gespeichert und zur weiteren Bearbeitung geöffnet.

<<tabelle-POS-menueleiste>> beschreibt die Menüleiste der Kasse.

[[tabelle-POS-menueleiste]]
.Menüleiste der Kasse
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**ID**
|Eindeutige Kennung der Kasse. Diese ID wird automatisch und mandantenübergreifend vergeben und ist nicht änderbar.

|**Kopieren**
|Erstellt eine neue Kasse mit den Einstellungen der geöffneten Kasse. Dabei werden Name und Herkunft neu vergeben. +
**__Hinweis:__** Das Kopieren einer Kasse ist nur möglich, wenn eine ausreichende Anzahl an Kassen gebucht wurde.

|**Gerät**
|Zeigt die eindeutige ID des Geräts an, wenn die Kasse bereits mit einem Gerät gekoppelt ist.

|**Löschen**
|Löscht die Kasse aus dem System.
|====

[#50]
=== Grundeinstellungen der Kasse vornehmen

Nimm nun im Tab **Grundeinstellungen** der neu erstellten Kasse die weiteren Einstellungen vor und speichere die Einstellungen. Beachte <<tabelle-POS-grundeinstellungen>>.

[[tabelle-POS-grundeinstellungen]]
.Tab *Grundeinstellungen* der Kasse
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Name*
|Einen Namen für die Kasse eingeben.

|*Herkunft*
|Beim Buchen einer Kasse wird automatisch eine Herkunft für diese Kasse generiert, um Aufträge, die über diese Kasse ins System gelangen, eindeutig zu kennzeichnen. Der neuen Kasse wird automatisch eine verfügbare POS-Herkunft (103.01 bis 103.99) zugeordnet.

|*Standardkunde*
|Für Kassenaufträge <<pos/pos-einrichten#90, erstellten Standardkunden>> wählen, dem über diese Kasse generierte Aufträge zugeordnet werden sollen.

2+|*Standort*

|*Name 1-4*; +
*Adresse 1-4*; +
*Postleitzahl*; +
*Ort*; +
*Land*
|Firmennamen und Adresse des Ladengeschäfts eingeben, an dem die Kasse betrieben wird. +
*_Hinweis:_* In Deutschland und anderen Ländern ist die Adresse eine Pflichtangabe, um ein rechtssicheres Arbeiten mit der Kasse zu ermöglichen. Genaue Standortangaben mit Steuerberaterin klären. +
*_Standort Österreich:_* Nachdem der Startbeleg für die Kasse erstellt wurde, kann das Land des Kassenstandorts nicht mehr geändert werden.

2+|*Artikelfilter*

|*Marktplatz-Verfügbarkeit berücksichtigen*
|Wählen, ob für die Kasse die Marktplatz-Verfügbarkeit berücksichtigt werden soll. Die Marktplatz-Verfügbarkeit wird im Tab **Verfügbarkeit**, Bereich **Märkte** der Variante aktiviert. +
Häkchen gesetzt = In der Kasse sind nur Varianten verfügbar, für die im Tab **Verfügbarkeit**, Bereich **Märkte** die Herkunft der Kasse aktiviert ist. +
Häkchen nicht gesetzt = Auch nicht für die Herkunft der Kasse aktivierte Varianten sind in der Kasse verfügbar und können aufgerufen und verkauft werden.

|*Nur aktive Varianten berücksichtigen*
|Wählen, ob für die Kasse nur aktive Varianten berücksichtigt werden sollen. Varianten werden im Tab **Einstellungen** der Variante aktiviert. +
Häkchen gesetzt = In der Kasse sind nur Varianten verfügbar, für die im Tab **Einstellungen** der Variante die Option <<artikel/artikel-verwalten#230, Aktiv>> aktiviert ist. +
Häkchen nicht gesetzt = Aktive und inaktive Varianten sind in der Kasse verfügbar und können aufgerufen und verkauft werden.

2+|*Vertriebslager*

|*Vertriebslager*
|Wählen, für welches Vertriebslager die über diese Kasse genierten Aufträge gebucht werden sollen. +
*_Hinweis:_* Artikel ohne Netto-Warenbestand werden im POS-Warenkorb rot markiert, können aber verkauft werden. Deshalb kann es zu rechnerischen Überverkäufen kommen.

2+|*Retoure*

|*Standard-Reparaturlager*
|Wählen, welches Lager bei Retouren als Standardreparaturlager vorgeschlagen wird.

|*Standard-Regal*
|Wählen, welches Regal bei Retouren vorgeschlagen wird.

|*Standard-Reparaturlagerort*
|Wählen, welcher Lagerort bei Retouren als Standard-Reparaturlagerort vorgeschlagen wird. +
*_Tipp:_* Zweimal die Pfeiltaste drücken, um eine Liste der Lagerorte anzuzeigen.

|*Retourenbetrag als Gutschein auszahlen* +
|Wählen, ob Kassenpersonal einen Gutschein in Höhe des Retourenbetrags aushändigen darf, statt den Betrag bar auszuzahlen.

|*Varianten-ID des Retourenartikels* +
|ID der Variante eingeben, die als Gutscheinartikel für Retouren dient.

2+|*Warenbewegung*

|*Warenbestand bei Stornierung zurückbuchen*
|Aktivieren, um den Warenbestand automatisch zurückzubuchen, wenn ein Auftrag storniert wird.

|*Externer Auftrag: Warenausgang automatisch buchen* +
(ab App-Version 1.9.2)
|Wählen, ob für externe Aufträge, die an der Kasse bezahlt werden, der Warenausgang automatisch gebucht werden soll. +
Aktiviert (Standardeinstellung) = Der Warenausgang wird automatisch gebucht. Die Schaltfläche *Warenausgang buchen* wird Kassenkräften nicht angezeigt. +
Nicht aktiviert = Der Warenausgang wird nur gebucht, wenn das Kassenpersonal auf *Warenausgang buchen* tippt. +
*_Tipp:_* Option deaktivieren, wenn die Ware nicht direkt an der Kasse ausgegeben wird.

|*Warenausgang von externen Aufträgen: Ware aus POS-Vertriebslager buchen* +
(ab App-Version 1.9.2)
|Wählen, aus welchem Lager die Auftragspositionen ausgebucht werden, wenn externe Aufträge an der Kasse abgeschlossen werden. +
Nicht aktiviert (Standardeinstellung) = Die Auftragspositionen werden aus dem Lager gebucht, das dem Auftrag bei der Erstellung zugeordnet wurde. +
Aktiviert = Die Auftragspositionen werden aus dem für die Kasse eingestellten *Vertriebslager* gebucht. Das Lager, das am Auftrag gespeichert ist, wird überschrieben.

2+|*Bedienung*

|*Preisabfrage wenn Artikelpreis 0,00*
|Aktivieren, um die manuelle Preiseingabe zu öffnen, wenn beim Kassieren ein 0-Euro-Artikel gewählt wird.

|*Favoriten mit Menge 1 hinzufügen*
|Aktivieren, um beim Kassieren Favoriten automatisch mit der Menge 1 in den POS-Warenkorb zu legen. Artikel mehrmals in den Warenkorb legen, um die Anzahl zu erhöhen. +
*_Tipp:_* Bei Favoriten, die über die Artikelsuche hinzugefügt werden, wird die Menge weiterhin manuell eingegeben.

|*Numpad (Tablet-Ansicht): Buttons für schnelle Mengeneingabe und passende Zahlung einblenden*
a|Aktivieren, um die Komfortfunktionen auf dem Ziffernblock der Kasse einzublenden. +
Nicht aktiviert = Die Komfortfunktionen werden nicht eingeblendet. +
Aktiviert = Die folgenden Komfortfunktionen werden als zusätzliche Reihe im Ziffernblock der Kasse eingeblendet:

* *Mal* = Kassenbenutzerinnen können die Menge eingeben, bevor sie einen Artikel scannen oder einen Favoritenartikel wählen. Wenn vor dem Scannen keine Menge eingegeben wird, wird der gescannte Artikel mit der Menge 1 in den POS-Warenkorb gelegt.
* *Passend* = Bei passender Barzahlung kann das Kassenpersonal auf diese Schaltfläche tippen, statt den erhaltenen Betrag einzugeben. Das Feld *Erhalten* wird mit dem zu zahlenden Betrag aufgefüllt.


//|*Retoure mit Hauptauftrag: Zu retournierende Auftragspositionen manuell wählen*
//|Wählen, ob bei Retouren mit Hauptauftrag die Auftragspositionen beim Öffnen des Auftrags vorausgewählt sind. +
//Nicht aktiviert = Standardeinstellung. Beim Öffnen des Hauptauftrags sind alle Auftragspositionen für die Retoure vorausgewählt. Das Kassenpersonal entfernt die Artikel, die nicht zurückgegeben werden. +
//Aktiviert = Beim Öffnen des Hauptauftrags sind keine Auftragspositionen für die Retoure vorausgewählt. Das Kassenpersonal fügt die Artikel zur Retoure hinzu, die zurückgegeben werden. +
//*_Tipp:_* Einstellung für Kassen ohne Scanner aktivieren, über die Aufträge mit vielen Auftragspositionen abgewickelt werden.

|*Soll-Bestand anzeigen*
|Wählen, ob der Soll-Bestand beim Erstellen eines <<pos/pos-kassenbenutzer#230, Tagesabschlusses>> oder <<pos/pos-kassenbenutzer#450b, Kassensturzes>> sichtbar sein soll. Diese Option ist standardmäßig deaktiviert. Somit sieht das Kassenpersonal beim Zählen _nicht_ wie viel Geld in der Kasse erwartet wird. Es ist sinnvoll, diese Einstellung nicht zu ändern, damit das Kassenpersonal den Bestand wirklich selbst zählt. Ist die Information eingeblendet, kann das Kassenpersonal den Soll-Bestand direkt übernehmen, ohne selbst gezählt zu haben.

2+|*Kundenkarte*

|*Kundenidentifikation* +
(ab App-Version 1.9.2)
|Wählen, welche Kontaktdaten durchsucht werden, wenn ein Barcode mit einem Pluszeichen (+) als Präfix gescannt wird. +
*Kontakt-ID* (Standardeinstellung) = Wählen, wenn Barcodes die Kontakt-ID enthalten. +
*Kundennummer* (empfohlen) = Wählen, wenn Barcodes die Kundennummer enthalten. +
*_Tipp:_* Bei der Einstellung *Kundennummer* können vorab Kundenkarten mit Barcodes gedruckt werden. Der Barcode-Code wird dann ohne das Pluszeichen in dem Feld *Kundennummer* des Kontakts gespeichert.

2+|*Österreich*

|*AES-Schlüssel* +
(nur neue Kassen mit Standort Österreich)
|AES-Schlüssel eingeben, mit dem der Umsatzzähler der Kasse verschlüsselt werden soll. Der AES-Schlüssel ist frei wählbar. Nachdem der Startbeleg für die Kasse erstellt wurde, kann der AES-Schlüssel nicht mehr geändert werden. +
*_Tipp:_* Auf **Schlüssel generieren** klicken, um einen zufälligen Schlüssel zu generieren. +
*_Hinweis:_* Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Neue Kasse erstellen und alte Kasse außer Betrieb nehmen, um Sicherheitseinrichtung einzurichten.

|**Zertifizierer** +
(nur neue Kassen mit Standort Österreich)
|Den Namen des Vertrauensdiensteanbieters eingeben, bei dem das Zertifikat gekauft wurde. +
**__Hinweis:__** Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Neue Kasse erstellen und alte Kasse außer Betrieb nehmen, um Sicherheitseinrichtung in Betrieb zu nehmen.

|**Zertifizierungsnummer** +
(nur neue Kassen mit Standort Österreich)
|Die Seriennummer des Signaturzertifikats eingeben, siehe Unterlagen des Vertrauensdiensteanbieters. +
*_Hinweis:_* Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Neue Kasse erstellen und alte Kasse außer Betrieb nehmen, um Sicherheitseinrichtung in Betrieb zu nehmen.
|====

[#60]
=== Favoriten verwalten

Du hast die Möglichkeit, Varianten zur Favoritenliste hinzuzufügen. Dadurch kann das Kassenpersonal häufig verkaufte Varianten schneller aufrufen und zum POS-Warenkorb hinzufügen.

[#70]
==== Varianten als Favoriten speichern

Gehe wie unten beschrieben vor, um Varianten als Favoriten zu speichern.

[.instruction]
Varianten als Favoriten speichern:

. Öffne das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffne die Kasse.
. Wechsele in das Tab **Favoriten**.
. Öffne das Tab **Variante hinzufügen**. +
→ Eine Liste der Varianten wird angezeigt.
. *_Optional:_* Nutze die Filter, um die Anzeige einzuschränken.
. Klicke auf **Varianten hinzufügen**. +
→ Die Varianten werden zur Liste der Favoriten hinzugefügt und im Tab **Favoriten** angezeigt. +
→ Beim nächsten Synchronisieren mit plentymarkets POS werden die Favoriten an die Kasse übertragen.

[TIP]
.Favoriten des Kassenpersonals haben Priorität
====
Kassenpersonal kann eigene Favoriten in plentymarkets POS speichern. Die Favoriten des Kassenpersonals haben dabei Priorität gegenüber den im plentymarkets Backend gespeicherten Favoriten.
====

[#80]
==== Reihenfolge der Favoriten ändern

Die Priorität der Favoriten legst du über die Pfeilsymbole des Tabs **Favoriten** fest. Die am häufigsten verkaufte Variante sollte ganz oben in der Liste stehen. Die erste Variante der Liste des Menü wird dem Kassenpersonal auch als erste Variante der Favoritenliste vorgeschlagen. Gehe wie unten beschrieben vor, um die Reihenfolge der Favoriten festzulegen.

[.instruction]
Reihenfolge der Favoriten ändern:

. Öffne das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffne die Kasse.
. Öffne das Tab **Favoriten**. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicke in der Spalte **Aktionen** auf den Pfeil der Variante, deren Position du ändern möchtest. +
→ Mit dem Pfeil nach oben erhöhst du die Priorität der Variante. +
→ Mit dem Pfeil nach unten verringerst du die Priorität der Variante.

[#90]
==== Favoritenliste auf andere Kassen übertragen

Die Favoritenliste einer Kasse kann auf andere Kassen des Mandanten übertragen werden. Dabei werden in der Zielkasse vorhandene Favoriten nicht gelöscht. Gehe dazu wie unten beschrieben vor.

[.instruction]
Favoriten auf andere Kassen übertragen:

. Öffne das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffne die Kasse.
. Öffne das Tab **Favoriten**. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicke auf **Favoriten übertragen**. +
→ Das Fenster **Favoriten übertragen** wird angezeigt.
. Setze Häkchen bei den Kassen, zu denen du die Favoriten dieser Kasse kopieren möchten.
. Klicke auf **Speichern**. +
→ Die Favoriten werden auf die gewählten Kassen übertragen.

[#110]
==== Varianten aus Liste der Favoriten löschen

Gehe wie unten beschrieben vor, um Varianten aus der Liste der Favoriten zu löschen. Aus der Liste gelöschte Varianten werden beim nächsten Synchronisieren mit der POS-App aus der Favoritenliste der Kasse entfernt.

[.instruction]
Varianten aus Liste der Favoriten löschen:

. Öffne das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffne die Kasse.
. Öffne das Tab **Favoriten**. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicke in der Spalte der Variante auf **Löschen**. +
→ Die Variante wird aus der Liste der Favoriten entfernt.

[#120]
=== Belegvorlage bearbeiten

Im Tab **Beleg** der Kasseneinstellungen bestimmst du die Daten, die auf Belegen ausgegeben werden sollen. Lade optional ein Bild hoch und lege Kopf- und Fußzeile für Belege fest. Standardmäßig ist die Kopfzeile mit den im Menü **System » Systemeinstellungen » Einstellungen » Stammdaten** gespeicherten Daten befüllt. Diese Daten kannst du pro Kasse anpassen. Die Fußzeile gestaltest du individuell, um zum Beispiel auf Aktionsangebote oder deinen Onlineshop hinzuweisen.

[.instruction]
Belegvorlage bearbeiten:

. Öffne das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffne die Kasse.
. Wechsele in das Tab **Beleg**.
. Setze Häkchen bei den Komponenten, die auf Belegen der Kasse angezeigt werden sollen.
. Nimm die Einstellungen vor. Beachte <<tabelle-POS-belegvorlage>>.
. **Speichere** die Einstellungen. +
→ Die Belegvorlage wird erstellt.

[[tabelle-POS-belegvorlage]]
.Belegvorlage bearbeiten
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Belegeinstellungen

|**Gutscheinbeleg drucken und speichern**
a|Wählen, ob ein Gutscheinbeleg gedruckt und im Dokumentenarchiv gespeichert werden soll. +

Nicht aktiviert (Standard) = Kein Gutscheinbeleg wird erstellt. +
Aktiviert = Beim Verkauf oder einer Teileinlösung eines Gutscheins wird ein Gutscheinbeleg erstellt. +
→ Der Gutscheinbeleg wird erstellt und im Dokumentenarchiv gespeichert. +
→ Wenn die Option *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* aktiviert ist, wird der Gutscheinbeleg nach dem Kassenbeleg ausgedruckt. +
→ Wenn *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* nicht aktiviert ist, kann die Kassenbenutzerin den Gutscheinbeleg nach Abschluss des Auftrags manuell drucken. +
Der Gutscheinbeleg enthält die folgenden Informationen zum Gutschein:

* Gutscheinwert
* Gutschein-Code
* Bei Teileinlösung: eingelöster Betrag und Restbetrag

*_Hinweis:_* Beim Verkauf eines Gutscheins wird der Gutschein-Code unabhängig von der gewählten Einstellung immer auf dem normalen Kassenbeleg ausgegeben.

2+|Beleginhalte

|**Bild**
|Option aktivieren und PNG-Datei wählen, die auf Belegen der Kasse ausgeben werden soll. Datei muss vorher im Menü **CMS » Bilder-Galerie** hochgeladen werden.

|**Kopfzeile**
|Wenn die Komponente gewählt wurde, wird Inhalt des Felds als Kopfzeile aller Belege der Kasse ausgegeben. Standardmäßig ist die Kopfzeile mit den im Menü **System » Systemeinstellungen » Einstellungen » Stammdaten** gespeicherten Daten befüllt. Daten bei Bedarf anpassen.

|*Barcode*
|Sollen Barcodes auf deinen Belege erscheinen? +
Im Falle einer <<pos/pos-kassenbenutzer#175, Retoure>> oder eines <<pos/pos-kassenbenutzer#450, Click-and-Collect-Auftrags>> bringen Kunden typischerweise ihre Kaufbelege mit in den Laden. Wurde ein Barcode auf dem Beleg gedruckt, muss das Kassenpersonal lediglich <<pos/pos-kassenbenutzer#520, den Barcode scannen>>, um den entsprechenden Auftrag aufzurufen. +
Barcodes helfen also dem Kassenpersonal, Aufträge schneller zu finden. Die manuelle Eingabe der Belegnummer oder Auftrags-ID entfällt. +
*_Hinweis_* Die Belegnummer wird als Barcode dargestellt und enthält dabei ein Sternchen (*) als Präfix. Beim Scannen gibt das Sternchen an, dass eine Belegnummer gesucht wird.

|**Fußzeile**
|Option aktivieren und zusätzlichen Text eingeben.

|**Identische Auftragspositionen**
|Wählen, wie mehrere identische Varianten auf dem Beleg dargestellt werden sollen. +
**Einzeln darstellen** = Unabhängig von der gekauften Stückzahl wird jede gekaufte Variante einzeln aufgeführt. Beispiel: +
---------------------------------------------------- +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
---------------------------------------------------- +
**Zusammenfassen** = Identische Varianten werden zusammengefasst. Beispiel: +
---------------------------------------------------- +
Katzenfutter CaTasty Deluxe          20,97 EUR A +
3 x 6,99 EUR A +
---------------------------------------------------- +
|====

[#130]
== Benutzerkonten für POS verwalten

Um Kassenpersonal den Zugriff auf plentymarkets POS zu ermöglichen, sind die folgenden Vorbereitungen nötig:

* Benutzerkonto der Benutzerklasse **Backend** erstellen
* Berechtigung für Sichtbarkeit von POS aktivieren
* Berechtigungen für POS-Funktionen aktivieren (optional)
* Berechtigungen für Kommunikation mit plentymarkets Backend über die REST-API aktivieren
* Berechtigungen für Sichtbarkeit von Kennzahlen aktivieren (optional)

Die Einstellungen, die du benötigst, um ein Benutzerkonto für Kassenpersonal zu erstellen, werden nachfolgend beschrieben. Allgemeine Informationen zu Benutzerkonten und Berechtigungen findest du auf der Handbuchseite <<basics/admin-aufgaben/benutzer-verwalten#, Benutzerkonten verwalten>>.

[TIP]
.Tipp: Rolle für Kassenpersonal erstellen
====
Um die Rechteverwaltung für Kassenpersonal zu vereinfachen, erstelle eine <<basics/admin-aufgaben/benutzer-verwalten#70, Rolle>> mit den Berechtigungen, die du Kassenpersonal zuweisen möchtest, und verknüpfe diese Rolle mit den Benutzerkonten des Kassenpersonals.
====

[#140]
=== Konto für Kassenpersonal erstellen

Damit neues Kassenpersonal Zugriff auf plentymarkets POS erhält, erstelle zunächst im plentymarkets Backend <<basics/admin-aufgaben/benutzer-verwalten#, Benutzerkonten>> der Benutzerklasse **Backend** für diese Personen. Gehe dazu wie unten beschrieben vor.

[.instruction]
Benutzerkonto für Kassenpersonal erstellen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neuen Benutzer anlegen* wird geöffnet.
. Gib den *Benutzernamen* ein.
. Gib den *realen Namen* ein.
. Gib das *Passwort* ein.
. Wiederhole das Passwort.
. Gib eine *Neue App-PIN* mit 4 bis 12 Ziffern ein.
. Wiederhole die App-PIN.
. Gib die E-Mail-Adresse der Kassenkraft ein, damit die Person Benachrichtigungen des Systems empfängt.
. Wähle die Benutzerklasse *Backend*.
. *Speichere* die Einstellungen.

[TIP]
.App-PIN für schnellen Kontowechsel
====
Die App-PIN erlaubt einen schnellen Wechsel des Benutzerkontos in bestimmten Menüs der plentymarkets App. Beim ersten Anmelden in der App wird aber das Passwort abgefragt. Dein Kassenpersonal benötigt also Passwort und PIN.
====

[#150]
=== Berechtigungen für Kassenpersonal aktivieren

Erteile nun Berechtigungen für die Kommunikation zwischen plentymarkets POS und dem plentymarkets Backend über die REST-API.

[.instruction]
Berechtigungen aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Übersicht wird geöffnet.
. *_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das gewünschte Konto. +
→ Die Ansicht *Rechte* wird geöffnet.
. Aktiviere im Bereich *Berechtigungen* die in <<tabelle-POS-REST-Berechtigungen>> gelisteten Berechtigungen.
. *Speichere* die Einstellungen.

[[tabelle-POS-REST-Berechtigungen]]
.Berechtigungen für Backend Konten
[cols="1,3"]
|====
|Bereich |Berechtigung

|*POS*
a|* *POS* +
→ Die untergeordneten Berechtigungen werden automatisch aktiviert.

|*CRM*
a|* *Kampagne » Code » Code anzeigen*
* *Kampagne » Code » Code erstellen*
* *Kampagne » Code » Code löschen*

|*Aufträge*
a|* *Aufträge erstellen*
* *Aufträge anzeigen*
|====

[#160]
=== POS-Sichtbarkeit für Kassenpersonal aktivieren

Nun legst du fest, welche Bereiche und Kennzahlen für Kassenpersonal der Benutzerklasse *Backend* in der plentymarkets App sichtbar sein sollen.

[.instruction]
App-Berechtigungen aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Öffne einen Benutzer.
. Öffne das Tab *Mobile*.
. Aktiviere im Bereich *Sichtbare Funktionen* die Option *POS*.
. Wenn die Kassenkraft auf weitere Bereiche der plentymarkets App zugreifen soll, aktiviere <<pos/pos-einrichten#170, weitere Berechtigungen>>.
. *Speichere* die Einstellungen. +
→ Die Kassenkraft hat Zugriff auf plentymarkets POS und kann Kassenaufträge erstellen.

[#170]
=== Berechtigungen für optionale POS-Funktionen aktivieren

Damit Kassenpersonal in plentymarkets POS Preise bearbeiten, Auftragspositionen umbenennen und/oder Rabatte gewähren können, müsst du die Berechtigungen dazu zuweisen. Wie du Rollen einrichtest und Benutzern zuweist, erfährst du <<basics/admin-aufgaben/benutzer-verwalten#, hier>>. Dort schaltest du auch weitere App-Funktionen für Kassenpersonal frei.

Im plentymarkets Backend legst du über das Zuweisen von Rollen fest, welche POS-Funktionen Kassenpersonal verwenden darf. Dort legst du außerdem fest, welche weiteren Bereiche und Kennzahlen in der plentymarkets App sichtbar sein sollen.

[.instruction]
Berechtigungen für POS-Funktionen aktivieren:

. Öffne das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Öffne einen Benutzer.
. Öffne das Tab **Berechtigung**.
. Öffne das Tab **Mobile**.
. Aktiviere die POS-Funktionen, die der Kassenkraft zur Verfügung stehen sollen. Beachte <<tabelle-POS-berechtigungen>>.
. **Speichere** die Einstellungen.

[[tabelle-POS-berechtigungen]]
.Mobile-Berechtigungen für Kassenpersonal
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Sichtbare Funktionen

|**POS**
|Gibt Kassenpersonal Zugang zu plentymarkets POS.

2+|POS-Funktionen

|**Preis bearbeiten**
|Erlaubt Kassenpersonal, Preise in Aufträgen zu bearbeiten.

|**Artikelposition umbenennen**
|Erlaubt Kassenpersonal, Positionen des Auftrags umzubenennen.

|*Rabatt gewähren*
|Erlaubt Kassenpersonal, Rabatte auf Auftragspositionen oder ganze Aufträge zu gewähren. +
*_Hinweis:_* Artikel, bei denen die Option *Aktionsgutschein/POS-Rabatt* auf *Verboten* gestellt ist, können nicht rabattiert werden.

|**Kassieren**
|Erlaubt Kassenpersonal zu kassieren.

|**Kasse sperren**
|Erlaubt Kassenpersonal, die Kasse zu sperren.

|**Einlagen und Entnahmen**
|Erlaubt Kassenpersonal, Einlagen und Entnahmen zu tätigen.

|**Kassensturz**
|Erlaubt Kassenpersonal, Kassenstürze durchzuführen.

|**Tagesabschluss**
a|Erlaubt Kassenpersonal, Tagesabschlüsse zu erzeugen. +
Tagesabschlussberichte enthalten folgende Informationen: +

* Barbestand: Anfangsbarbestand, Entnahmen, Einlagen, Soll-Kassenbestand, Ist-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retournierte Artikel: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufte Gutscheine: Anzahl und Summe
* Benutzer: Umsatz, Stornierungen und Retouren pro Benutzer

|**Zwischenbericht**
a|Erlaubt Kassenpersonal, Zwischenberichte zu erzeugen. +
Zwischenberichte enthalten folgende Informationen: +

* Barbestand: Entnahmen, Einlagen, Soll-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retournierte Artikel: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufte Gutscheine: Anzahl und Summe
* Benutzer: Umsatz, Stornierungen und Retouren pro Benutzer

|**Artikel synchronisieren**
|Erlaubt Kassenpersonal, Artikeldaten mit der Kasse zu synchronisieren.

|**Aufträge hochladen**
|Erlaubt Kassenpersonal, Kassenaufträge in plentymarkets hochzuladen.

|**Retoure anlegen**
|Erlaubt Kassenpersonal, Retouren zu buchen.

|**Kunde auswählen**
|Erlaubt Kassenpersonal, während des Kassierens Kundendaten aufzurufen und einen plentymarkets Bestandskunden zu wählen. +
**__Hinweis:__** Damit dieses Recht greift, muss der Kassenkraft im Tab **REST-API** auch die Berechtigung **Firma » Kontakt » Adresse » Adresse anzeigen** erteilt werden.

|**Stornierung**
|Erlaubt Kassenpersonal, Aufträge zu stornieren.
|====

=== Gesperrte POS-Benutzer entsperren

Wenn Kassenpersonal das Passwort beim Login mehrmals hintereinander falsch eingegeben, wird das Konto eine gewisse Zeit gesperrt. Wenn du Admin-Rechte hast, kannst du diese Sperre im plentymarkets Admin-Bereich frühzeitig aufheben.

[.instruction]
Benutzer entsperren:

. Öffne das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten » Benutzer öffnen**.
. Klicke auf **Login entsperren**. +
→ Die Kassenkraft kann sich wieder bei der plentymarkets App anmelden.

[#700]
== Zahlungsarten für Kassenaufträge aktivieren

Damit Aufträge über plentymarkets POS kassiert werden können, aktivierst du die Zahlungsarten, die du über plentymarkets POS erlauben möchtest. Mindestens die Zahlungsart **Bar bei Übergabe** muss aktiviert werden, damit Kassenaufträge bar bezahlt werden können. Weitere Zahlungsarten sind optional.

=== plentymarkets Zahlungsarten aktivieren

Aktiviere nun die Zahlungsarten, die du benötigst. Beachte, dass Zahlungsarten in einem weiteren Schritt für Kundenklassen erlaubt werden müssen. Weitere Informationen findest du unter <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.

Aktivere die folgenden Zahlungsarten, damit Kassenaufträge korrekt dargestellt werden:

* **4 » Bar bei Übergabe** für Barzahlungen
* **11 » Barverkauf/EC-Karte** für Kartenzahlungen über externe EC-Kartenterminals
* **1700 » Coupon** für Gutscheinzahlungen

Gehe wie unten beschrieben vor, um diese Zahlungsarten zu aktivieren.

[.instruction]
Zahlungsarten für Kassenaufträge einrichten:

. Öffne das Menü **System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten**.
. Aktiviere die Einstellung **Auch inaktive zeigen**.
. Öffne den Ordner **International**.
. Klicke auf die Zahlungsart. +
→ Das Tab **Einstellungen** wird geöffnet.
. Nimm die Einstellungen vor. Beachte die Erläuterungen in <<tabelle-POS-zahlungsarten>>.
. Setze ein Häkchen bei der Option **Aktiv**.
. **Speichere** die Einstellungen.

[[tabelle-POS-zahlungsarten]]
.Einstellungen der Zahlungsarten für Kassenaufträge
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Sprache**
|Sprache wählen. Folgende Optionen werden sprachabhängig gespeichert: Name, Infoseite, Infoseite (Intern), Logo und Logo hochladen.

|**Name**
|Den externen Namen eingeben, der auf dem Kassenbeleg und im Webshop und auf Rechnungen angezeigt werden soll. Wenn kein Name gespeichert ist, wird der Backend-Name der Zahlungsart für den Kassenbeleg verwendet. +
__**Tipp:**__ Der externe Name wird in der Sprache auf dem Beleg ausgegeben, die das Kassenpersonal bei der Kassenanmeldung wählt.

|**Infoseite**
|Die Standardeinstellung **---** nur ändern, wenn die Zahlungsart auch im Webshop verwendet wird.

|**Lieferländer**
|Ein oder mehrere Lieferländer wählen. +
**__Hinweis:__** Lieferländer nur wählen, wenn die Zahlungsart auch im Webshop verwendet wird.

|**Mandant**
|Den Mandanten der POS-Kassen wählen.

|**Logo**
|Die Standardeinstellung **Standardlogo anzeigen** nur ändern, wenn die Zahlungsart auch im Webshop verwendet wird.

|**Kosten: Pauschal oder Prozentual**
|Für alle Kosten **0,00** eintragen, damit kein Aufpreis für die Zahlungsart berechnet wird.
|====

[TIP]
.Zahlungsart Barverkauf/EC-Karte
====
Stelle für die Zahlungsart **11 » Barverkauf/EC-Karte** außerdem im Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS  » Kasse öffnen » Tab: Zahlungsart** die Option **Ohne Anbindung** im Bereich **EC-Terminal** ein.
====

[#1070]
=== Kartenterminals anbinden

Bestimmte Kartenterminals können über ein Plugin an plentymarkets POS angebunden werden. Aktuell unterstützt plentymarkets POS folgende Anbindungen:

* link:https://marketplace.plentymarkets.com/plugins/payment/ingenicozvt_5140[Ingenico-Geräte über ZVT-Schnittstelle^]
* link:https://marketplace.plentymarkets.com/plugins/payment/sumup_5141[SumUp Air^]
* link:https://marketplace.plentymarkets.com/plugins/payment/VerifoneZVT_5504[Verifone-Geräte über ZVT-Schnittstelle^]

Informationen dazu, wie du diese Plugins an plentymarkets POS anbindest, findest du in der Beschreibung des Plugins.

[#1080]
=== Kauf auf Rechnung anbieten

Wenn du Bestandskunden die Möglichkeit geben möchtest, Kassenaufträge per Rechnung zu bezahlen, benötigst du das folgende Plugin:

* link:https://marketplace.plentymarkets.com/plugins/payment/PosInvoice_5590[POS Kauf auf Rechnung^]

Informationen dazu, wie du das Plugin einbindest, findest du in der Beschreibung des Plugins.

[#950]
== Buchungskonten für plentymarkets POS Kassenvorfälle speichern

Aufträge, die über plentymarkets POS generiert werden, werden den in plentymarkets gespeicherten <<auftraege/buchhaltung#800, Erlöskonten>> zugewiesen. Da Einlagen, Entnahmen und Differenzen aus Kassenstürzen keine Aufträge sind, kannst du für diese Kassenvorfälle eigene Buchungskonten speichern. Du legst also fest, auf welche Buchungskonten Einlagen und Entnahmen gebucht werden, die über plentymarkets POS Kassen getätigt werden. Außerdem speicherst du Buchungskonten für Differenzen, die sich aus Kassenstürzen ergeben.

=== Buchungskonten für Kassensturzdifferenzen speichern

Wenn beim Kassensturz der Ist-Kassenbestand vom Soll-Kassenbestand abweicht, muss die Differenz entweder ausgeglichen oder gebucht werden. Wenn die Differenz gebucht wird, wird der Ist-Kassenbestand als neuer Soll-Kassenbestand übernommen. Gleichzeitig wird abhängig vom Vorzeichen des Differenzbetrags entweder eine Einlage (+) oder eine Entnahme (-) gebucht. Gehe wie unten beschrieben vor, um Buchungen, die sich aus Kassensturzdifferenzen ergeben, Buchungskonten zuzuweisen.

[.instruction]
Buchungskonten für Kassensturzdifferenzen speichern:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung*. +
→ Das Tab *Grundeinstellungen* wird geöffnet.
. Wechsele in das Tab *Konten*. +
→ Das Tab *Buchungsschlüssel* wird geöffnet.
. Wechsele in das Tab *Kassenvorfälle*.
. Klicke im Bereich *Entnahme* in der Zeile *Kassensturz* in das Feld der Spalte *Konto*.
. Gib das Konto ein, auf das Entnahmen gebucht werden, die entstehen, wenn der Ist-Kassenbestand größer ist als der Soll-Kassenbestand.
. Klicke im Bereich *Einlage* in der Zeile *Kassensturz* in das Feld der Spalte *Konto*.
. Gib das Konto ein, auf das Einlagen gebucht werden, die entstehen, wenn der Soll-Kassenbestand größer ist als der Ist-Kassenbestand.
. *Speichere* die Einstellungen. +
→ Die Buchungskonten werden gespeichert. +
→ Einlagen und Entnahmen, die durch Kassensturzdifferenzen entstehen, werden automatisch auf die gespeicherten Konten gebucht.

=== Buchungskonten für allgemeine Einlagen und Entnahmen speichern

Wenn Kassenpersonal Einlagen und Entnahmen über plentymarkets POS durchführt, wählt die Kassenkraft einen Kassenvorfall als Grund für die Buchung. Systemseitig sind dafür standardmäßig ein Kassenvorfall *Entnahme* und ein Kassenvorfall *Einlage* verfügbar, die nicht gelöscht werden können. Für diese Vorfälle kannst du Buchungskonten speichern, wenn die Beträge auf bestimmte Buchungskonten gebucht werden sollen. Gehe wie unten beschrieben vor, um Konten für diese Vorfälle zu speichern. Optional speicherst du in einem weiteren Schritt zusätzliche Konten, um mit mehreren Buchungskonten zu arbeiten.

[.instruction]
Buchungskonten für Einlagen und Entnahmen speichern:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung*. +
→ Das Tab *Grundeinstellungen* wird geöffnet.
. Wechsele in das Tab *Konten*. +
→ Das Tab *Buchungsschlüssel* wird geöffnet.
. Wechsele in das Tab *Kassenvorfälle*.
. Klicke im Bereich *Entnahme* in der Zeile *Entnahme* in das Feld der Spalte *Konto*.
. Gib das Konto ein, auf das allgemeine Entnahmen gebucht werden sollen.
. Klicke im Bereich *Einlage* in der Zeile *Einlage* in das Feld der Spalte *Konto*.
. Gib das Konto ein, auf das allgemeine Einlagen gebucht werden sollen.
. *Speichere* die Einstellungen. +
→ Die Buchungskonten werden gespeichert. +
→ Einlagen oder Entnahmen werden diesem Konto zugewiesen.

=== Weitere Buchungskonten für Einlagen und Entnahmen speichern

Wenn plentymarkets POS Einlagen und Entnahmen je nach Grund verschiedenen Buchungskonten zugewiesen werden sollen, legst du weitere Kassenvorfälle an. Diese Kassenvorfälle kann das Kassenpersonal wählen, wenn Bargeld aus der Kasse entnommen oder in die Kasse gelegt wird. Gehe wie unten beschrieben vor, um weitere Kombinationen aus Kassenvorfall und Buchungskonto zu speichern.

[.instruction]
Weitere Buchungskonten für Einlagen und Entnahmen speichern:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung*. +
→ Das Tab *Grundeinstellungen* wird geöffnet.
. Wechsele in das Tab *Konten*. +
→ Das Tab *Buchungsschlüssel* wird geöffnet.
. Wechsele in das Tab *Kassenvorfälle*.
. Klicke auf *Neue Einlage* oder *Neue Entnahme*. +
→ Eine leere Zeile wird eingefügt.
. Gib die *Bezeichnung* ein, die Kassenpersonal bei Einlagen oder Entnahmen in einer Dropdown-Liste angezeigt wird.
. Gib das Buchungskonto ein, dem die Einlage oder Entnahme buchhalterisch zugewiesen wird. +
**__Tipp:__** Über die Pfeile steuerst du die Reihenfolge, in der die Vorfälle in der App angezeigt werden.
. *Speichere* die Einstellungen. +
→ Das Buchungskonto wird gespeichert. +
→ Kassenpersonal kann bei Einlagen oder Entnahmen den Vorfall aus der Dropdown-Liste wählen.


[#180]
== Versandart Selbstabholung einrichten

Damit Kassenaufträge korrekt in plentymarkets verbucht werden, ermöglichst du die Versandart **Selbstabholung** für die Artikel, die du über plentymarkets POS abrechnen möchtest. Dazu sind folgende Vorbereitungen notwendig:

* Versanddienstleister **Selbstabholung** erstellen
* Versandprofil **Selbstabholung** erstellen
* Versandprofil **Selbstabholung** am Artikel aktivieren

Diese Vorbereitungen werden nachfolgend beschrieben.

[#190]
=== Versanddienstleister Selbstabholung erstellen

Gehe wie unten beschrieben vor, um einen Versanddienstleister **Selbstabholung** zu erstellen. Nur die für diesen Versanddienstleister relevanten Einstellungen werden beschrieben. Allgemeine Informationen zu Versanddienstleistern findest du auf der Handbuchseite <<fulfillment/versand-vorbereiten#800, Versand vorbereiten>>.

[.instruction]
Versanddienstleister Selbstabholung erstellen:

. Öffne das Menü **System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister**.
. Klicke auf **Neu**. +
→ Ganz unten wird eine neue Zeile hinzugefügt.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-POS-versanddienstleister-selbstabholung>>.
. **Speichere** die Einstellungen.

[[tabelle-POS-versanddienstleister-selbstabholung]]
.Versanddienstleister **Selbstabholung** erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Name (de)**
|Namen eingeben, zum Beispiel **Selbstabholung**.

|**Name (Backend)**
|Systeminternen Namen eingeben, zum Beispiel **Selbstabholung**.

|**Versanddienstleister**
|Option **Selbstabholer** aus der Dropdown-Liste wählen.
|====

[#200]
=== Versandprofil Selbstabholung erstellen

Erstelle nun ein Versandprofil für die Selbstabholung. Nur die für dieses Versandprofil relevanten Einstellungen werden beschrieben. Allgemeine Informationen zu Versandprofilen findest du auf der Handbuchseite <<fulfillment/versand-vorbereiten#1000, Versand vorbereiten>>.

[.instruction]
Versandprofil für Selbstabholer erstellen:

. Öffne das Menü **System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile**.
. Klicke auf **Neu**.
. Wähle den eben erstellten Versanddienstleister aus der Dropdown-Liste.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-POS-versandprofil-selbstabholung>>.
. **Speichere** die Einstellungen. +
→ Das Tab **Portotabelle** wird angezeigt.
. **Speichere** die Einstellungen des Tabs **Portotabelle** ohne Änderungen.

[[tabelle-POS-versandprofil-selbstabholung]]
.Versandprofil **Selbstabholung** erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Versanddienstleister**
|Versanddienstleister **Selbstabholung** aus der Dropdown-Liste wählen.

|**Mandanten (Shops)**
|Option wird nur angezeigt, wenn mindestens ein Mandant eingerichtet ist. Mandanten oder die Option **ALLE** wählen, wenn das Versandprofil für alle Webshops gelten soll.

|**Auftragsherkunft**
|plentymarkets POS-Kasse(n) als Auftragsherkunft wählen.

|**Gesperrte Zahlungsarten**
|Die Zahlungsarten wählen, die für das Versandprofil **Selbstabholung** nicht angeboten werden sollen.
|====

[#210]
=== Versandprofil Selbstabholung am Artikel aktivieren

Aktiviere nun das Versandprofil **Selbstabholung** bei den Artikeln, die du über die Kasse verkaufen möchtest.

[.instruction]
Versandprofil Selbstabholung aktivieren:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Wechsele in das Tab **Global**.
. Aktiviere das Versandprofil **Selbstabholung**.
. **Speichere** die Einstellungen.

Du möchtest das Versandprofil für eine größere Anzahl an Artikeln gleichzeitig aktivieren? Dann nutze die <<artikel/artikel-verwalten#155, Artikel-Gruppenfunktion>>.

[#100]
== Preise für Kassenaufträge verwalten

Um POS-Preise für Varianten zu hinterlegen, benötigst du mindestens einen <<artikel/artikel-verwalten#870, Verkaufspreis>>, bei dem die POS-Herkunft der Kasse aktiviert ist. Verkaufspreise erstellst und verwaltest du zentral. Preise für Varianten hinterlegst du, indem du Varianten mit dem Verkaufspreis verknüpfst und einen Preis speicherst.

[#750]
=== Verkaufspreis für Kassenaufträge erstellen

Wenn du bereits Verkaufspreise erstellt hast, die deinen Anforderungen für Kassenaufträge entsprechen, aktiviere bei diesen Verkaufspreisen die Herkunft der Kasse. Gehe sonst wie unten beschrieben vor, um einen neuen Verkaufspreis für Kassenaufträge zu erstellen. Nur die für POS-Herkünfte relevanten Einstellungen werden beschrieben.

[.instruction]
Verkaufspreis für Kassenaufträge erstellen:

. Öffne das Menü **System » Systemeinstellungen » Artikel » Verkaufspreise**.
. Klicke auf **Neu**. +
→ Das Tab **Neu** wird geöffnet.
. Nimm die Einstellungen gemäß <<tabelle-POS-verkaufspreis>> vor.
. **Speichere** die Einstellungen.

[[tabelle-POS-verkaufspreis]]
.Verkaufspreis für Kassenaufträge erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Position**
|Positionsnummer eingeben. Verkaufspreise werden im Bereich **Verkaufspreise** von Artikelvarianten aufsteigend sortiert.

|**Interner Name DE**
|Internen Namen eingeben. Der interne Name wird nur im plentymarkets Backend angezeigt.

|**Externer Name DE**
|Externen Namen eingeben. Der externe Name wird im Webshop angezeigt.

|**Ab Menge**
|Mengenwert eingeben. Über Verkaufspreise mit verschiedenen Mengenwerten bildest du mengenbezogene Preisstaffelungen in plentymarkets ab.

|**Währung**
|Die Währung aktivieren, in der Kassenaufträge kassiert werden.

|**Preistyp**
|Preistyp für den Verkaufspreis aktivieren. +
**UVP** = Aktivieren, wenn der Verkaufspreis ein unverbindlicher Verkaufspreis (UVP) ist. Wird der UVP und ein weiterer Verkaufspreis an der Variante verknüpft, dann wird der UVP im Webshop in rot und durchgestrichen neben dem Verkaufspreis dargestellt. +
**__Hinweis:__** Preise des Typs *UVP* dienen nur dazu, den Preisvergleich zwischen dem UVP und einem Verkaufspreis darzustellen. Varianten können nicht zu diesem UVP-Preis verkauft werden. +
**Aktionspreis** = Aktivieren, um einen Verkaufspreis als Aktionspreis zu kennzeichnen.

|**Mandant**
|Die Mandanten (Shops) aktivieren, mit denen der Verkaufspreis verknüpft wird.

|**Land**
|Das Land aktivieren, in dem die Kasse eingesetzt wird.

|**Herkunft**
|Eine oder mehrere plentymarkets POS Auftragsherkünfte aktivieren, mit denen der Verkaufspreis verknüpft wird.
|====

[#550]
=== Verkaufspreis mit Varianten verknüpfen

Verknüpfe nun den POS-Verkaufspreis mit den Hauptvarianten der Artikel, die du über die Kasse verkaufen möchtest. Verkaufspreise werden von der Hauptvariante an Varianten vererbt. Du kannst Verkaufspreise auch individuell mit Varianten verknüpfen.

[.instruction]
Verkaufspreis mit Hauptvariante verknüpfen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Wähle im Bereich **Verkaufspreise** den Preis aus der Dropdown-Liste.
. Wähle, ob der Preis ein Brutto- oder Nettopreis ist.
. *_Optional:_* Wähle eine Preiskalkulation.
. Klicke auf **Hinzufügen**. +
→ Der Verkaufspreis wird hinzugefügt und in der Liste angezeigt.
. Gib einen Wert in das Feld **Preis** ein.
. **Speichere** die Einstellungen. +
→ Die Preise werden an die Varianten des Artikels vererbt. Speichere für Varianten mit abweichendem Preis einen eigenen Wert.

[#800]
=== Rundungsverhalten für Kassenaufträge festlegen

Beträge werden auf plentymarkets POS Kassenbelegen grundsätzlich mit 2 Nachkommastellen dargestellt. Über die Einstellungen im plentymarkets Backend steuerst du, ob die Preise in den Aufträge auch im Hintergrund auf 2 Nachkommastellen gerundet oder ob mit 4 Nachkommastellen gerechnet werden soll. Das Rundungsverhalten für Aufträge, die über plentymarkets POS Kassen generiert werden, wird über die folgenden 3 Optionen gesteuert:

.Erforderliche Optionen für Rundungsverhalten bei Kassenaufträgen
[cols="10,1,1"]
|====
|Menü |Option |Mögliche Einstellungen

|System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung
|Anzahl Nachkommstellen bei Preisen
a|
* 2
* 4

|System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung
|Nur Gesamtpreise runden
a|
* Ja
* Nein

|System » Systemeinstellungen » Mandant » Mandant wählen » POS » Kasse öffnen » Tab: Beleg
|Identische Auftragspositionen
a|
* Einzeln darstellen
* Zusammenfassen
|====

Aus diesen Einstellungen ergeben sich 6 Einstellungskombinationen:

* Auftragspositionen einzeln darstellen, Einzelpreise auf 2 Nachkommastellen runden
* Auftragspositionen einzeln darstellen, Einzelpreise auf 4 Nachkommastellen runden
* Auftragspositionen einzeln darstellen, Gesamtpreise auf 4 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Einzelpreise auf 2 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Einzelpreise auf 4 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Gesamtpreise auf 4 Nachkommastellen runden

Abhängig von den gewählten Einstellungen kommt es zu unterschiedlichen Gesamtbeträgen. Beachte, dass sich die Abweichungen potenzieren, je mehr Artikel mit Rundungsbedarf pro Auftrag/Beleg verkauft werden.

==== Beispielrechnung

<<tabelle-POS-rundungsverhalten>> zeigt eine Beispielrechnung, um die Rundungsabweichungen zu verdeutlichen, die durch die verschiedenen Einstellungskombinationen entstehen.

Die Beispielrechnung beruht auf den folgenden Daten:

. Berechnungsbasis: Artikel zum Preis von 4,545 Euro
. Rechnung 1: Verkauf von 10 Artikeln
. Rechnung 2: Verkauf von 10 Artikeln mit 5 % Positionsrabatt

[[tabelle-POS-rundungsverhalten]]
.Beispielrechnung bei einem Artikelpreis mit 4 Nachkommastellen
[cols="2,1,1"]
|====
|Gewählte Einstellungen |Rechnung 1 (4,545 Euro x 10) Gesamtpreis auf Beleg |Rechnung 2 (4,545 Euro x 10 - 5%) Gesamtpreis auf Beleg

|Anzahl Nachkommastellen = 2  +
Auftragspositionen = Einzeln darstellen
|45,50 Euro
|43,20 Euro

|Anzahl Nachkommastellen = 4  +
Nur Gesamtpreise runden = Nein +
Auftragspositionen = Einzeln darstellen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Ja +
Auftragspositionen = Einzeln darstellen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 2 +
Auftragspositionen = Zusammenfassen
|43,50 Euro
|43,50 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Nein +
Auftragspositionen = Zusammenfassen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Ja +
Auftragspositionen = Zusammenfassen
|45,45 Euro
|43,18 Euro
|====

Detaillierte Informationen und weitere Rechnungsbeispiele zum Rundungsverhalten findest du auch auf der Handbuchseite <<auftraege/buchhaltung#, Buchhaltung>>.

[#95]
== Standardkunden für Kassenaufträge erstellen

Damit Kassenaufträge korrekt in plentymarkets gespeichert werden, muss jedem Auftrag ein Kontakt zugeordnet sein. Deshalb erstellst du einen anonymen Standardkunden für deine Laufkundschaft. Gehe wie unten beschrieben vor, um einen Standardkunden für Kassenaufträge anzulegen. Nur die Einstellungen werden beschrieben, die für das Erstellen des Standardkunden für Kassenaufträge relevant sind. Allgemeine Informationen zum Erstellen von Kontakten findest du auf der Handbuchseite <<crm/kontakte-verwalten#, Kontakte verwalten>>.

[IMPORTANT]
.Einstellungen für Standardkunden für Kassenaufträge mit Steuerberater abstimmen
====
Kläre im Vorfeld mit deinem Steuerbüro, welche Einstellungen für Standardkunden für Kassenaufträge sinnvoll sind.
====

[.instruction]
Standardkunden für Kassenaufträge erstellen:

. Öffne das Menü **CRM » Kontakte**.
. Klicke auf **Neuen Kontakt erstellen**.
. Nimm die Einstellungen gemäß <<tabelle-POS-standardkunde>> vor.
. **Speichere** die Einstellungen.
. Öffne das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS » Kasse öffnen » Grundeinstellungen**.
. Gib die ID des Standardkunden in das Feld **Standardkunde** ein.
. **Speichere** die Einstellungen.

[[tabelle-POS-standardkunde]]
.Standardkunden für Kassenaufträge erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Firma**
|Einen Firmennamen eingeben, zum Beispiel plentymarkets Kasse.

|**Anrede**
|Option **Firma** aus der Dropdown-Liste wählen.

|**Straße; +
PLZ**; +
**Ort**
|Straße, Postleitzahl und Ort eingeben.

|**Land**
|Land aus der Dropdown-Liste wählen, in dem die Kasse eingesetzt wird. Standardeinstellung richtet sich nach der Option **Firmensitz für FiBu** im Menü <<schnelleinstieg/schnelleinstieg-basiseinstellungen#100, System » Systemeinstellungen » Einstellungen » Stammdaten>>.

|**Mandant**
|Mandanten aus der Dropdown-Liste wählen, wenn die Kasse nicht dem Standardmandanten zugeordnet ist.

|**Typ**
|Option **Kunde** aus der Dropdown-Liste wählen.
|====

[#220]
== Dummy-Artikel erstellen

Im Tagesgeschäft kommt es vor, dass Artikel verkauft werden sollen, für die es keinen Datensatz im System gibt. Zum Beispiel wird häufig für Diversartikel kein Datensatz erstellt. Um diese Artikel trotzdem kassieren zu können, erstellst du Dummy-Artikel. Kassenpersonal fügt dann den Dummy-Artikel zum POS-Warenkorb hinzu und passen den Preis und optional den Namen der Auftragsposition an.

Die folgenden Vorbereitungen sind nötig, um mit Dummy-Artikeln zu arbeiten.

* Einen Dummy-Artikel für jeden Umsatzsteuersatz erstellen, der für die Produkte deines Portfolios relevant sind. Wenn du Artikel mit 19% und 7% verkaufst, benötigst du also zwei Dummy-Artikel.
* Option *Preisabfrage wenn Artikelpreis 0* aktivieren, damit Kassenpersonal den Preis manuell eingeben kann.
* Kassenpersonal Rechte zum Bearbeiten von Preisen erteilen.
* Kassenpersonal Rechte zum Umbenennen von Auftragspositionen erteilen (optional).

Die erforderlichen Einstellungen werden in <<tabelle-POS-dummy-artikel>> kurz erläutert. Die  Zwischenüberschriften der Tabelle geben an, in welchem Menü du die Einstellung vornimmst.

[[tabelle-POS-dummy-artikel]]
.Empfohlene Einstellungen für Dummy-Artikel
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Artikel » Artikel bearbeiten » Neuen Artikel erstellen » Tab: Einstellungen*

|**Beschränkung**
|Option **Keinen WB für diese Variante führen** wählen.

|**Preis**
|Verkaufspreis für Kasse wählen und Preis *0,00* Euro eingeben.

|**Umsatzsteuer**
|Umsatzsteuersatz eingeben, der für den Dummy-Artikel gelten soll.

2+|*System » Systemeinstellungen » Mandant » Mandant wählen » POS » Kasse öffnen*

|**Preisabfrage wenn Artikelpreis 0**
|Option aktivieren.

2+|*System » Systemeinstellungen » Einstellungen » Benutzer » Konten » Konto öffnen » Tab: Mobile » POS-Funktionen*

|**Preis bearbeiten**
|Recht für Kassenpersonal aktivieren, damit Kassenpersonal den Preis anpassen kann.

|**Artikelposition umbenennen**
|Recht für Kassenpersonal aktivieren, wenn Kassenpersonal den Namen von Dummy-Artikeln anpassen können soll.
|====

[#2100]
== Gutscheinverkauf vorbereiten

Du kannst über plentymarkets POS Verkaufsgutscheine verkaufen und einlösen. Wenn du einen Gutscheinartikel verkaufst, händigst du zusammen mit dem Kassenbeleg einen Gutschein-Code aus. Ein Gutschein-Code kann nur eingelöst werden, wenn dieser Gutschein-Code zum Zeitpunkt der Einlösung im plentymarkets Backend gespeichert ist. Du kannst Gutschein-Codes entweder automatisch generieren oder mit eigenen Gutschein-Codes arbeiten.

Um Verkaufsgutscheine über plentymarkets POS zu verkaufen, sind die folgenden Vorbereitungen im plentymarkets Backend erforderlich.

* Gutscheinkampagne mit Gutscheinart **Verkaufsgutschein** erstellen.
* Freitextfeld für die Kampagne erstellen und im Menü *System » Systemeinstellungen » Aufträge » Gutscheine* verknüpfen.
* Gutscheinartikel mit 0% MwSt. erstellen und mit der Gutscheinkampagne verknüpfen.
* *_Optional:_* Gutschein-Codes generieren oder eigene Codes im Backend speichern.
* *_Optional:_* Gutscheinvordrucke erstellen und Kassenpersonal zur Verfügung stellen.
* *_Optional:_* Gutschein-Codes Kassenpersonal zur Verfügung stellen.

Diese Schritte werden nachfolgend kurz erläutert. Eine detaillierte Anleitung zum Erstellen von Kampagnen und Gutscheinen findest du auf der Handbuchseite <<auftraege/gutscheine#, Gutscheine>>.

[NOTE]
.Vorgehensweise bei mehreren Kassen
====
Du hast mehr als eine Kasse und möchtest mit eigenen Gutschein-Codes arbeiten? Dann teile die ausgedruckten Gutschein-Codes zwischen den Kassen auf oder erstelle für jede Kasse eigene Gutscheinkampagnen und -artikel, damit jeder Gutschein-Code nur einmal verkauft wird.
====

=== Freitextfeld vorbereiten

Um Gutscheine zu verkaufen, muss am Artikel ein Freitextfeld hinterlegt werden. Dieses Freitextfeld definierst du einmalig und ordnest das Freitextfeld Gutscheinkampagnen zu.

[#820]
==== Freitextfeld definieren

Definiere das Freitextfeld, das für Kampagnen verwendet werden soll.

[.instruction]
Freitextfeld definieren:

. Öffne das Menü **System » Systemeinstellungen » Artikel » Freitextfelder**.
. Gib in das Feld *Feldbezeichnung* die Bezeichnung **Kampagne ID** ein. +
*_Hinweis:_* Achte auf die Schreibweise. Der Name **Kampagne ID** ist nur in der Schreibweise mit Leerzeichen gültig.
. Wähle den Datentyp **Zahl**.
. Gib eine Zeichenlänge ein.
. **Speichere** die Einstellungen. +
→ Das Freitextfeld wird über Nacht aktiviert und ist am nächsten Morgen verfügbar.

==== Freitextfeld wählen

Im Menü **System » Systemeinstellungen » Aufträge » Gutscheine** wählst du nun einmalig dieses Freitextfeld und ordnest das Freitextfeld so Gutscheinkampagnen zu.

[.instruction]
Freitextfeld wählen:

. Öffne das Menü **System » Systemeinstellungen » Aufträge » Gutscheine**.
. Wähle das Kampagnenfeld **Kampagne ID** aus der Dropdown-Liste.
. **Speichere** die Einstellungen. +
→ Das Feld **Kampagne ID** wird im Tab <<artikel/artikel-verwalten#75, Felder>> der Artikel angezeigt.

[#830]
=== Kampagne für POS-Verkaufsgutscheine erstellen

Erstelle nun für den Verkauf von Gutscheinen über plentymarkets POS eine oder mehrere eigene Kampagnen. Du hast folgende Möglichkeiten:

* Du erstellst eine Kampagne für alle Gutscheine, die du über plentymarkets POS verkaufst.
* Du erstellst eine Kampagne pro Gutscheinwert. +
*_Beispiel:_* Du möchtest Gutscheine im Wert von 10 Euro, 25 Euro und 50 Euro sowie einen Gutschein verkaufen, bei dem Kassenpersonal den Wert frei wählen kann. Du erstellst also 3 Kampagnen mit den Rabattwerten 10, 25 und 50 Euro sowie eine Kampagne mit einem beliebigen Rabattwert.

Wenn du mehr als eine Kasse einsetzt und mit eigenen Gutschein-Codes arbeiten möchtest, kann es sinnvoll sein, pro Kasse eigene Kampagnen anzulegen. So erstellst du eine Kampagne für Verkaufsgutscheine:

[.instruction]
Kampagne für POS-Verkaufsgutscheine erstellen:

. Öffne das Menü **Aufträge » Gutscheine**.
. Klicke auf **Neue Kampagne**.
. Nimm die Einstellungen vor. Beachte <<tabelle-POS-gutscheinkampagnen>>.
. **Speichere** die Einstellungen. +
→ Die neue Kampagne wird erstellt und in der Übersicht angezeigt.

[[tabelle-POS-gutscheinkampagnen]]
.Einstellungen für POS-Verkaufsgutscheinkampagnen
[cols="1,2"]
|====
|Einstellung |Benutzereingabe

2+|Kampagne

|**Name**
|Namen für die Kampagne eingeben. +
*_Tipp_*: Der Name sollte den Namen der Kasse und den Gutscheinwert enthalten.

|**Beschreibung**
|Optional eine Beschreibung eingeben.

|**Konzept: Code**
|**Mehrere Codes** wählen, damit jeder Gutschein-Code nur einmal eingelöst werden kann und Restbeträge bei Teileinlösungen korrekt berechnet werden.

|**Konzept: Einlösungen**
|**Einlösung bis Wert aufgebraucht ist** wählen.

|**Nutzung**
|**Einzelbestellungen** oder <<auftraege/scheduler#, Abonnements>> oder beides wählen.

|**Mindestbestellwert**
|Keinen Wert eingeben, da Verkaufsgutscheine wie Zahlungsmittel zu behandeln sind und keinem Mindestbestellwert unterliegen dürfen.

2+|Gültigkeiten

|**Startdatum**
|Das Datum, ab dem die Kampagne aktiv ist.

|**Enddatum**
|Das Datum, bis zu dem die Kampagne aktiv ist.

|**Code-Gültigkeit in Wochen**
|*0* eingeben.

2+|Gutschein

|**Gutscheintyp**
|**Gutschein** wählen.

|**Gutscheinart**
|**Verkaufsgutschein** wählen.

|**Code-Länge**
|Die Zeichenlänge des Gutschein-Codes wählen.

|**Rabattart**
|**Festbetrag** wählen.

|**Rabattwert**
|Den Gutscheinwert eingeben, zum Beispiel 10,00 = 10 Euro. +
**__Hinweis:__** Den Rabattwert nicht mehr ändern, nachdem der erste Gutschein verkauft wurde. +
*_Tipp:_* Dieser Wert wird Codes automatisch zugewiesen, wenn im Tab **Codes** über **Gutschein-Codes manuell generieren** Codes generiert werden, ohne dass ein Betrag in das Feld **Wert** eingegeben wird. +

|**Inkl. Versandkosten**
|Option nicht aktivieren.

2+|Filter

|**Artikel über Preisportale**
|**Nicht erlauben** wählen, da plentymarkets POS nicht an Preisportale angebunden ist.

|**Kategorien**
|Die Kategorien wählen, in denen der Gutschein einlösbar sein soll. Die Auswahl gilt auch für alle Unterkategorien einer markierten Kategorie.

|**Artikel**
|Keinen Wert eingeben, da Verkaufsgutscheine wie Zahlungsmittel zu behandeln sind und nicht auf bestimmte Artikel beschränkt werden dürfen.

|**Mandanten (Shops)**
|Die Mandanten (Shops) wählen, für die die Gutscheine der Kampagne gelten sollen.

|**Kundenklassen**
|Die Kundenklassen wählen, für die die Gutscheine der Kampagne gelten sollen.

|**Kundentypen**
|Die Kundentypen wählen, für die die Gutscheine der Kampagne gelten sollen.
|====

[#850]
=== Gutschein-Codes verwalten

Verkaufsgutscheine werden in plentymarkets POS eingelöst, indem das Kassenpersonal den Gutschein-Code eingibt. Damit der Gutschein-Code eingelöst werden kann, muss der Code zum Zeitpunkt der Einlösung in einer Kampagne des plentymarkets Backends gespeichert sein.

Aus Sicht des Kassenpersonals ergeben sich aus den Konfigurationsmöglichkeiten in plentymarkets drei mögliche Szenarien beim Verkauf eines Gutscheins:

* Der Gutschein-Code wird automatisch von der Kasse generiert.
* Das Kassenpersonal hat eine Liste mit Gutschein-Codes pro Gutscheinwert, die in plentymarkets gespeichert sind. Die Kassenkraft gibt einen Code ein. Der Gutscheinwert wird abgerufen.
* Das Kassenpersonal hat eine Liste mit Gutschein-Codes, die nicht in plentymarkets gespeichert sind. Die Kassenkraft gibt einen Code und einen Gutscheinwert ein.

Nachfolgend wird beschrieben, wie du Gutschein-Codes für diese verschiedenen Szenarien konfigurierst.

[#2200]
==== Automatisch Gutschein-Code beim Verkauf generieren

Am wenigsten administrativen Aufwand hast du, wenn Kassenbenutzerinnen beim Verkauf eines Gutscheins über plentymarkets POS einen zufälligen <<pos/pos-kassenbenutzer#250, Gutschein-Code generieren>>. Beim Hochladen des Kassenauftrags werden der Gutschein-Code und der damit verbundene Gutscheinwert in die Kampagne importiert, die mit dem Gutscheinartikel verknüpft ist. Der Gutschein-Code wird auf dem Beleg ausgegeben und optional wird ein Gutscheinbeleg erstellt. Das Kassenpersonal kann den Gutschein-Code außerdem per Hand auf einem dekorativen Gutscheinvordruck eintragen.

[#2300]
==== Mit eigenen Gutschein-Codes arbeiten

Wenn du Kassenpersonal Gutschein-Codes aushändigen möchtest, die beim Kassieren eingegeben werden sollen, erhöht sich der administrative Aufwand. Du hast aber auch mehr Möglichkeiten, dekorative Gutscheinvordrucke zu erstellen, auf denen nur der Gutschein-Code oder aber der Gutschein-Code und der Gutscheinwert bereits vermerkt sind. Das Kassenpersonal gibt dann einfach diese Gutscheinvordrucke aus.

Gutschein-Codes können entweder vor dem Verkauf oder beim Verkauf des Gutscheins im System gespeichert werden.

Um Gutschein-Codes vor dem Verkauf im plentymarkets Backend zu speichern:

* Du generierst vor dem Verkauf Gutschein-Codes mit festem Wert in der Kampagne.
* Du speicherst vor dem Verkauf eigene Gutschein-Codes mit festem Wert in der Kampagne.

In diesen Fällen stellst du dem Kassenpersonal eine Liste mit diesen Gutschein-Codes und dem dafür gespeicherten Gutscheinwert bereit.

Um Gutschein-Codes beim Verkauf zu speichern:

* Kassenbenutzerinnen geben beim Verkauf des Gutscheins einen noch nicht in plentymarkets gespeicherten Gutschein-Code und den Gutscheinwert ein.

In diesen Fällen stellst du dem Kassenpersonal eine Liste mit den Gutschein-Codes bereit. Den Wert des Gutscheins gibt das Kassenpersonal beim Kassieren als Preis für den Gutschein ein.

[NOTE]
.Erstellungsdatum beachten
====
Du hast bereits in plentymarkets generierte Gutschein-Codes an das Kassenpersonal ausgehändigt und möchtest weitere Gutschein-Codes generieren? Dann achte auf das Erstellungsdatum. In plentymarkets werden Gutschein-Codes nicht als verkauft gekennzeichnet. Um Gutschein-Codes nicht doppelt zu verkaufen, bringst du nur die Codes in Umlauf, die du an einem bestimmten Datum erstellt hast. Am einfachsten geht das, indem du Gutscheine im Menü **Aufträge » Gutscheine** generierst und diese Gutschein-Codes als CSV-Datei exportierst. Die CSV-Datei filterst du nach dem Erstellungsdatum, also nach der Spalte *GeneriertAm*. So erhaltest du nur die neuen Gutschein-Codes.
====

[#2400]
==== Gutschein-Codes manuell generieren

Mit dem Gutschein-Generator im Tab **Codes** einer Kampagne erzeugst du einen oder mehrere automatisch generierte Gutschein-Codes.

[.instruction]
Gutschein-Codes mit festem Wert manuell generieren:

. Öffne das Menü **Aufträge » Gutscheine**.
. Klicke auf die Kampagne, für die du Gutschein-Codes erzeugen möchtest.
. Öffne das Tab **Codes**.
. Gib im Bereich **Gutschein-Codes manuell generieren** links die gewünschte Anzahl an Gutschein-Codes ein.
. *_Optional:_* Gib in das Feld **Wert** den Wert ein, der dem Gutschein-Code zugewiesen werden soll. +
*_Tipp:_* Wenn du das Feld **Wert** leer lässt, wird dem Code der Rabattwert der Kampagne zugewiesen.
. **Speichere** die Eingabe. +
→ Die Gutschein-Codes werden erzeugt und zur Liste der Gutschein-Codes hinzugefügt.
. Klicke auf *Exportieren*, um die Gutschein-Codes zu exportieren. +
→ Ein CSV-Export aller Gutschein-Codes der Kampagne wird erstellt.
. Filtere die Spalte *GeneriertAm* der CSV-Datei nach dem aktuellen Datum. So erhältst du eine Liste aller neu erstellten Gutschein-Codes. +
. Stelle dem Kassenpersonal die Gutschein-Codes und Informationen zum Wert der Codes zur Verfügung. +
*_Hinweis:_* Bringe Gutschein-Codes nicht mehrfach in Umlauf. Teile bei mehreren Kassen die Gutschein-Codes entweder auf oder erstelle separate Kampagnen pro Kasse.

[#2500]
==== Eigene Gutschein-Codes mit festem Wert speichern

Statt Gutschein-Codes in plentymarkets zu generieren, kannst du auch vor dem Verkauf eigene Gutschein-Codes in plentymarkets speichern. Gültige Zeichen für Gutschein-Codes sind Klein- und Großbuchstaben, Ziffern, Unterstriche (_) und Bindestriche (-).

[.instruction]
Eigenen Gutschein-Code mit festem Wert speichern:

. Öffne das Menü **Aufträge » Gutscheine**.
. Klicke auf die Kampagne, für die du einen Gutschein-Code speichern möchtest.
. Öffne das Tab **Codes**.
. Gib im Bereich **Gutschein-Code manuell eintragen** rechts einen Code mit zwischen 6 und 24 Zeichen ein.
. **Speichere** die Eingabe. +
→ Der Gutschein-Code wird gespeichert und zur Liste der Gutschein-Codes hinzugefügt. +
*_Tipp:_* Mit dem Datenformat **CampaignCoupon** importierst du mehrere Gutschein-Codes gleichzeitig. Als Gutscheinwert wird dabei der **Rabattwert** importiert. Lege also pro Gutscheinwert eine eigene Kampagne an, wenn du mit dem Datenformat arbeiten möchtest.
. Stelle dem Kassenpersonal die Gutschein-Codes und Informationen zum Wert der Codes zur Verfügung. +
*_Hinweis:_* Bringe Gutschein-Codes nicht mehrfach in Umlauf. Teile bei mehreren Kassen die Gutschein-Codes entweder auf oder erstelle separate Kampagnen pro Kasse.

[#3900]
=== Drucken und Speichern von Gutscheinbelegen aktivieren

Optional kann ein Gutscheinbeleg erstellt und gedruckt werden. Der Gutscheinbeleg enthält die folgenden Informationen zum Gutschein:

* Gutscheinwert
* Gutschein-Code
* Bei Teileinlösung:
	** Eingelöster Betrag
	** Restbetrag

[.instruction]
Drucken von Gutscheinbelegen aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » POS*.
. Öffne die Kasse.
. Wechsele in das Tab *Beleg*.
. Aktiviere die Option *Gutscheinbeleg drucken und speichern*.
. **Speichere** die Einstellungen. +
→ Beim Verkauf oder einer Teileinlösung eines Gutscheins wird ein Gutscheinbeleg erstellt. +
→ Der Gutscheinbeleg wird im Dokumentenarchiv gespeichert. +
→ Wenn die Option *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* aktiviert ist, wird der Gutscheinbeleg nach dem Kassenbeleg ausgedruckt. +
→ Wenn *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* nicht aktiviert ist, kann die Kassenbenutzerin den Gutscheinbeleg nach Abschluss des Auftrags manuell drucken. +
*_Hinweis:_* Beim Verkauf eines Gutscheins wird der Gutschein-Code unabhängig von der gewählten Einstellung immer auf dem normalen Kassenbeleg ausgegeben.


[#840]
=== Gutscheinartikel erstellen

Erstelle nun einen oder mehrere Gutscheinartikel. Da die Kampagnen-ID auf der Artikelebene zugeordnet wird, kannst du bei Verkaufsgutscheinen nicht mit Varianten arbeiten. Detaillierte Informationen zum Erstellen von Artikeln findest du auf der Handbuchseite <<artikel/artikel-verwalten#, Artikel verwalten>>. Hier werden nur die Einstellungen beschrieben, die du speziell zum Erstellen von Gutscheinartikeln benötigst.

==== Gutscheinartikel mit festem Preis erstellen

Bei Gutscheinartikeln mit festem Preis erfolgt beim Kassieren keine Preisabfrage. Du beschleunigst also den Kassiervorgang, bist aber auch weniger flexibel.

Beachte bei vorhandenen Gutschein-Codes:

* Der Wert des vorhandenen Gutschein-Codes muss mit dem Preis des Artikels übereinstimmen. Der Gutscheinartikel muss also mit der Kampagne verknüpft sein, die die Gutschein-Codes mit den korrekten Werten enthält. Bei einer Kampagne pro Gutscheinwert wird also jede Kampagne mit nur einem Artikel verknüpft. Bei einer Kampagne mit verschiedenen Gutscheinwerten wird diese Kampagne mit mehreren Gutscheinartikeln verknüpft.

[.instruction]
Gutscheinartikel mit festem Preis erstellen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Klicke auf **Neu**. +
→ Das Tab **Neuer Artikel** wird geöffnet.
. Wähle den Typ **Standard**.
. Gib einen Namen ein. +
*_Tipp_*: Der Name sollte den Gutscheinwert enthalten.
. Gib als Inhalt **1 Stück** ein.
. Wähle eine Kategorie.
. Wähle einen Verkaufspreis aus der Dropdown-Liste. +
*_Hinweis_*: Der Verkaufspreis muss mit der Auftragsherkunft der Kasse verknüpft sein.
. Gib als Preis den Gutscheinwert ein.
. **Speichere** die Einstellungen. +
→ Der Artikel wird erstellt und zur weiteren Bearbeitung geöffnet.
. Nimm die weiteren Einstellungen vor. Beachte <<tabelle-POS-verkaufsgutscheine-artikeleinstellungen>>.
. **Speichere** die Einstellungen.

[#2600]
==== Gutscheinartikel mit flexiblem Wert erstellen

Gutscheinartikel mit flexiblem Wert sind Artikel mit einem Preis von 0,00 Euro. Den Preis, zu dem der Gutscheinartikel tatsächlich an der Kasse verkauft wird, steuerst du auf zwei verschiedene Arten:

* Beim Kassieren gibt das Kassenpersonal einen in plentymarkets vorhandenen Gutschein-Code ein. Der Wert dieses Gutschein-Codes wird zum Preis des Artikels.
* Beim Kassieren generiert die Kassenbenutzerin entweder automatisch einen Code oder speichert einen eigenen Gutschein-Code und gibt einen Gutscheinwert ein.

[.instruction]
Gutscheinartikel mit flexiblem Preis erstellen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Klicke auf **Neu**. +
→ Das Tab **Neuer Artikel** wird geöffnet.
. Wähle den Typ **Standard**.
. Gib einen Namen ein.
. Gib als Inhalt **1 Stück** ein.
. Wähle eine Kategorie.
. Wähle einen Verkaufspreis aus der Dropdown-Liste. +
*_Hinweis_*: Der Verkaufspreis muss mit der Auftragsherkunft der Kasse verknüpft sein.
. Gib als Preis **0,00** Euro ein.
. **Speichere** die Einstellungen. +
→ Der Artikel wird erstellt und zur weiteren Bearbeitung geöffnet.
. Nimm die weiteren Einstellungen vor. Beachte <<tabelle-POS-verkaufsgutscheine-artikeleinstellungen>>.
. **Speichere** die Einstellungen. +
→ *_Mit vorhandenem Gutschein-Code:_* Das Kassenpersonal gibt den Gutschein-Code einer Kampagne ein, die mit dem Artikel verknüpft ist. Der Artikel wird mit dem Wert des Gutschein-Codes berechnet. +
→ *_Ohne vorhandenen Gutschein-Code:_* Das Kassenpersonal wird aufgefordert, einen Preis einzugeben, wenn der Artikel in den POS-Warenkorb gelegt wird.

[[tabelle-POS-verkaufsgutscheine-artikeleinstellungen]]
.Artikeleinstellungen für Verkaufsgutscheine mit festem und flexiblem Wert
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Einstellungen*

|**Aktiv**
|Option aktivieren.

|**Beschränkung**
|**Keine** wählen.

|**Umsatzsteuer**
|**0%** wählen.

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Verfügbarkeit*

|**Märkte**
|Kasse(n) aus der Dropdown-Liste wählen, über die die Gutscheinartikel verkauft werden sollen.

|**Mandant**
|Mandant der Kasse wählen.

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Felder*

|**Kampagne ID**
|ID der Gutscheinkampagne eingeben, um den Artikel mit der Kampagne zu verknüpfen.
|====

[#3800]
=== Berechtigungen für Gutscheinverkauf erteilen

Benutzer mit Admin-Rechten haben standardmäßig die Berechtigungen, Verkaufsgutschein zu erstellen. Benutzern der Benutzerklasse *Backend* müssen diese Berechtigungen separat erteilt werden.

[.instruction]
Berechtigungen für Gutscheinverkauf erteilen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*.
. *_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das gewünschte Konto. +
→ Die Ansicht *Rechte* wird geöffnet.
. Aktiviere im Bereich *Berechtigungen* die folgenden Berechtigungen:
	** *Gutschein » Kampagne » Code » Code erstellen*
	** *Gutschein » Kampagne » Code » Code löschen*
	** *Gutschein » Kampagne » Code » Code anzeigen*
. *Speichere* die Einstellungen.

[#2700]
=== Besonderheiten beim Verkauf von Verkaufsgutscheinen

* Der Umsatz erhöht sich beim Verkauf des Verkaufsgutscheins nicht.
* Verkaufte Gutscheine werden auf dem Tagesbericht separat ausgewiesen. Der Barbestand wird nur erhöht, wenn der Gutschein bar bezahlt wurde.

[#2800]
=== Besonderheiten beim Einlösen von Verkaufsgutscheinen

* Der Wert des Verkaufsgutscheins wird vom Gesamtbetrag inkl. Steuern abgezogen.
* Der Umsatz erhöht sich um den eingelösten Gutscheinbetrag.
* Auf dem Tagesbericht wird der eingelöste Gutscheinwert mit der Zahlungsart *Gutschein* ausgewiesen.
* Der Barbestand der Kasse erhöht sich durch die Einlösung des Gutscheins nicht.

[#3600]
== Retouren vorbereiten

In den Kasseneinstellungen wählst du einen Standard-Reparaturlagerort für Retouren und legst in den Berechtigungen fest, wer Retouren durchführen darf. Wenn du Retourenbeträge nur in bar auszahlen möchtest, sind keine weiteren Einstellungen nötig, um Retouren über plentymarkets POS abzuwickeln. Beachte die <<pos/pos-einrichten#2000, Hinweise zu Retouren>>. Wenn du die Möglichkeit haben möchtest, den Retourenbetrag als Gutschein auszuzahlen, bereitest du außerdem <<pos/pos-einrichten#3100, Retourengutscheine>> vor.


[#2000]
=== Hinweise zu Retouren

Beachte die folgenden Hinweise zu Retouren:

* Aus technischen Gründen können Retourenbeträge aktuell nur in bar ausgezahlt werden.
* Verkaufsgutscheine können nicht zurückgegeben werden.
* Über die Kasse können für alle im System gespeicherten Aufträge Retouren gebucht werden. Es können also auch Artikel aus Aufträgen mit anderen Herkünften zurückgegeben werden. Die Entscheidung, ob Artikel zurückgeben werden können, trifft das Kassenpersonal. Informiere deshalb das Kassenpersonal, ob und wenn ja welche Herkünfte von der Retoure ausgeschlossen sind.
* Als Lagerort für Retourenartikel wird Kassenkräften standardmäßig der Lagerort angezeigt, der im Tab *Grundeinstellungen* der Kasse als *Standard-Reparturlagerort* festgelegt ist. Kassenkräfte können optional einen anderen Lagerort für die Retourenartikel wählen. Die möglichen Lagerorte werden in der folgenden Reihenfolge angezeigt:
  .. Lagerort aus Auftrag = Der Lagerort, an dem der Artikel lag, als er verkauft wurde.
  .. Standard-Reparaturlagerort = Der im Tab *Grundeinstellungen* der Kasse festgelegte *Reparturlagerort*.
  .. Lagerortvorschläge = Die Lagerortvorschläge der Lager, die mit der Variante verknüpft sind.
  .. Verwendete Lagerorte = Die Lagerorte, in denen die Variante bereits lagert.
Informiere das Kassenpersonal darüber, an welchen Lagerort Retouren gebucht werden sollen.
* Bei Retouren für einen Hauptauftrag mit Versandkosten entscheidet das Kasselpersonal, ob die Versandkosten erstattet werden. Schule deshalb das Kassenpersonal, damit deine Belegschaft weiß, in welchen Fällen die Versandkosten erstatten werden sollen.
* Weise das Kassenpersonal an, zurückgegebene Artikel auf dem Kaufbeleg durchzustreichen. So verhinderst du, dass Artikel mehrmals zurückgegeben werden.
* Bei Kauf auf Rechnung oder Anzahlungen bei einer Retoure erst Geld aushändigen, wenn der Preis der zurückgegebenen Artikel höher ist als der Betrag, der bisher bezahlt wurde.
* Der Retourenbetrag kann statt in bar auch in Form eines Gutscheins ausgezahlt werden. Wenn du diese Möglichkeit nutzen möchtest, schule das Kassenpersonal, damit deine Belegschaft weiß, in welchen Fällen der Retourenbetrag in bar und in welchen Fällen der Betrag als Gutschein ausgezahlt werden soll.

[#3100]
=== Retourengutscheine vorbereiten

Statt den Retourenbetrag in bar auszuzahlen, kann ein Gutschein über den Retourenbetrag erstellt und ausgehändigt werden. Bei einer solchen Retoure wird der Retourenbetrag nur theoretisch ausgezahlt und sofort ein Gutschein über denselben Betrag gekauft. Bei einer Retoure mit Gutschein werden also eine Retoure, eine Gutschrift und ein neuer Auftrag erstellt.

Um Gutscheine für Retouren zu erstellen, sind die folgenden Vorbereitungen im plentymarkets Backend erforderlich:

* Gutscheinkampagne mit Gutscheinart *Verkaufsgutschein* erstellen.
* Gutscheinartikel mit 0% MwSt. erstellen und mit der Gutscheinkampagne verknüpfen.
* Gutscheinartikel für Retouren mit der Kasse verknüpfen.
* Backend Benutzerkonten Berechtigungen erteilen.


Diese Schritte werden nachfolgend kurz erläutert. Eine detaillierte Anleitung zum Erstellen von Kampagnen und Gutscheinen findest du auf der Handbuchseite <<auftraege/gutscheine#, Gutscheine>>.


[#3200]
==== Kampagne für Gutscheine aus Retouren erstellen

Erstelle eine Kampagne für Gutscheine aus Retouren.

[.instruction]
Kampagne für Gutscheine aus Retouren erstellen:

. Öffne das Menü *Aufträge » Gutscheine*.
. Klicke auf *Neue Kampagne*.
. Nimm die Einstellungen vor. Beachte <<tabelle-POS-retourenkampagne>>.
. *Speichere* die Einstellungen. +
→ Die neue Kampagne wird erstellt und in der Übersicht angezeigt.

[[tabelle-POS-retourenkampagne]]
.Einstellungen für Gutscheine aus Retouren
[cols="1,2"]
|====
|Einstellung |Benutzereingabe

2+|Kampagne

|*Name*
|Namen für die Kampagne eingeben.

|*Beschreibung*
|Optional eine Beschreibung eingeben.

|*Konzept: Code*
|*Mehrere Codes* wählen.

|*Konzept: Einlösungen*
|*Einlösung bis Wert aufgebraucht ist* wählen.

|*Nutzung*
|*Einzelbestellungen* oder <<auftraege/scheduler#, Abonnements>> oder beides wählen.

|*Mindestbestellwert*
|Keinen Wert eingeben.

2+|Gültigkeiten

|*Startdatum*
|Das Datum, ab dem die Kampagne aktiv ist.

|*Enddatum*
|Das Datum, bis zu dem die Kampagne aktiv ist.

|*Code-Gültigkeit in Wochen*
|*0* eingeben.

2+|Gutschein

|*Gutscheintyp*
|*Gutschein* wählen.

|*Gutscheinart*
|*Verkaufsgutschein* wählen.

|*Code-Länge*
|Die Zeichenlänge des Gutschein-Codes wählen.

|*Rabattart*
|*Festbetrag* wählen.

|*Rabattwert*
|Einen Gutscheinwert eingeben, zum Beispiel 1,00.

|*Inkl. Versandkosten*
|Option nicht aktivieren.

2+|Filter

|*Artikel über Preisportale*
|*Nicht erlauben* wählen.

|*Kategorien*
|Die Kategorien wählen, in denen der Gutschein einlösbar sein soll. Die Auswahl gilt auch für alle Unterkategorien einer markierten Kategorie.

|*Artikel*
|Keinen Wert eingeben.

|*Mandanten (Shops)*
|Die Mandanten (Shops) wählen, für die die Gutscheine der Kampagne gelten sollen.

|*Kundenklassen*
|Die Kundenklassen wählen, für die die Gutscheine der Kampagne gelten sollen.

|*Kundentypen*
|Die Kundentypen wählen, für die die Gutscheine der Kampagne gelten sollen.
|====

[#3300]
==== Gutschein-Codes verwalten

Die Gutschein-Codes für Gutscheine aus Retouren verwaltest du genauso wie andere Gutschein-Codes. Du hast folgende Möglichkeiten:

* <<#2200, Die Kasse generiert automatisch einen Gutschein-Code.>>
* <<#2300, Die Kassenkraft gibt einen Code ein, der noch nicht in plentymarkets gespeichert ist.>>


[#4000]
==== Drucken und Speichern von Gutscheinbelegen aktivieren

Optional kann ein Gutscheinbeleg erstellt und gedruckt werden. Der Gutscheinbeleg enthält die folgenden Informationen zum Gutschein:

* Gutscheinwert
* Gutschein-Code
* Bei Teileinlösung:
	** Eingelöster Betrag
	** Restbetrag

[.instruction]
Drucken von Gutscheinbelegen aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » POS*.
. Öffne die Kasse.
. Wechsele in das Tab *Beleg*.
. Aktiviere die Option *Gutscheinbeleg drucken und speichern*.
. **Speichere** die Einstellungen. +
→ Beim Verkauf oder einer Teileinlösung eines Gutscheins wird ein Gutscheinbeleg erstellt. +
→ Der Gutscheinbeleg wird im Dokumentenarchiv gespeichert. +
→ Wenn die Option *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* aktiviert ist, wird der Gutscheinbeleg nach dem Kassenbeleg ausgedruckt. +
→ Wenn *Automatisches Drucken* im Menü *plentymarkets App » Einstellungen » POS* nicht aktiviert ist, kann die Kassenbenutzerin den Gutscheinbeleg nach Abschluss des Auftrags manuell drucken. +
*_Hinweis:_* Beim Verkauf eines Gutscheins wird der Gutschein-Code unabhängig von der gewählten Einstellung immer auf dem normalen Kassenbeleg ausgegeben.

[#840b]
==== Gutscheinartikel für Retouren erstellen

Erstelle einen Gutscheinartikel mit einem Preis von 0,00 Euro. Hier werden nur die Einstellungen beschrieben, die du zum Erstellen von Gutscheinartikeln für Gutscheine aus Retouren benötigst.

[.instruction]
Gutscheinartikel für Retouren erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Typ *Standard*.
. Gib einen Namen ein.
. Gib als Inhalt *1 Stück* ein.
. Wähle eine Kategorie.
. Wähle einen Verkaufspreis aus der Dropdown-Liste. +
*_Hinweis_*: Der Verkaufspreis muss mit der Auftragsherkunft der Kasse verknüpft sein.
. Gib als Preis *0,00* Euro ein.
. *Speichere* die Einstellungen. +
→ Der Artikel wird erstellt und zur weiteren Bearbeitung geöffnet.
. Nimm die weiteren Einstellungen vor. Beachte <<tabelle-POS-retourengutscheine-artikeleinstellungen>>.
. *Speichere* die Einstellungen.
. Notiere dir die ID der Variante.

[[tabelle-POS-retourengutscheine-artikeleinstellungen]]
.Artikeleinstellungen für Gutscheine für Retouren
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Einstellungen*

|*Aktiv*
|Option aktivieren.

|*Beschränkung*
|*Keine* wählen.

|*Umsatzsteuer*
|*0%* wählen.

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Verfügbarkeit*

|*Märkte*
|Kasse(n) aus der Dropdown-Liste wählen.

|*Mandant*
|Mandant der Kasse wählen.

2+|*Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Felder*

|*Kampagne ID*
|ID der Gutscheinkampagne eingeben, um den Artikel mit der Kampagne zu verknüpfen.
|====

[#3400]
==== Gutscheinartikel für Retouren mit Kasse verknüpfen

[.instruction]
Gutscheinartikel für Retouren mit Kasse verknüpfen:

. Öffne das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » POS**.
. Öffne die Kasse. +
→ Das Tab *Grundeinstellungen* wird angezeigt.
. Aktiviere die Option *Gutschein über Retourenbetrag erzeugen*. +
. Gib in das Feld *Varianten-ID des Retourengutscheins* die Varianten-ID des Retourengutscheins ein. +
→ Der Gutscheinartikel wird bei Retouren automatisch gewählt.




[#3700]
==== Berechtigungen für Retourengutscheine erteilen

Personen mit Admin-Rechten haben standardmäßig die Berechtigung, Retourengutscheine zu erstellen. Konten der Benutzerklasse *Backend* müssen diese Berechtigungen separat erteilt werden.

[.instruction]
Berechtigungen für Retourengutscheine erteilen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*.
. *_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das gewünschte Konto. +
→ Die Ansicht *Rechte* wird geöffnet.
. Aktiviere im Bereich *Berechtigungen* die folgenden Berechtigungen:
	** *Gutschein » Kampagne » Code » Code erstellen*
	** *Gutschein » Kampagne » Code » Code löschen*
	** *Gutschein » Kampagne » Code » Code anzeigen*
. *Speichere* die Einstellungen.

[#3500]
==== Besonderheiten bei Gutscheinen aus Retouren

* Im Kassenjournal wird ein Gutschein aus einer Retoure als neuer Auftrag mit dem Vermerk *Aus Retoure erzeugter Gutschein* dargestellt. Wie bei der Barauszahlung wird eine Gutschrift erstellt. Der Barbestand wird für die Gutschrift reduziert, für den neuen Auftrag jedoch wieder erhöht und bleibt somit gleich.
* Auf dem Tagesbeleg wird auch ein als Gutschein ausgezahlter Retourenbetrag als Bar-Retoure aufgeführt.
* Gutscheine aus einer Retoure werden auf dem Tagesbericht als verkaufte Gutscheine ausgewiesen. Der Barbestand bleibt gleich.

[#4100]
== Abholen und Bezahlen von Online-Bestellungen vorbereiten (Click & Collect)

Über den Webshop, Marktplätze oder andere Herkünfte bestellte Ware kann auch entweder online bezahlt und im Ladengeschäft abgeholt oder im Ladengeschäft bezahlt und abholt werden.

Die folgenden Vorbereitungen sind POS-seitig nötig, wenn du deiner Kundschaft anbieten möchtest, Online-Bestellungen im Laden abzuholen oder im Laden abzuholen und zu bezahlen:

* Aufträge können nur anhand der Auftrags-ID in die Kasse geladen werden. +
→ Stelle sicher, dass Auftragsbestätigungen die Auftrags-ID enthalten. Weise Kund*innen explizit darauf hin, dass diese Auftrags-ID benötigt wird, um den Auftrag in der Filiale zu bearbeiten.
* Erkläre deinen Kassenkräften, wie sie die Identität von Personen prüfen müssen, die bezahlte Ware im Ladengeschäft abholen. Sonst besteht Gefahr, dass Kassenkräfte die Ware an Unbefugte aushändigen.
* Nutzt du Prozesse und/oder Ereignisaktionen, um Aufträge zu bearbeiten, die über den Webshop oder Marktplätze ins System gelangen? +
→ Prüfe diese Ereignisaktionen und Prozesse, bevor du eine Abholung im Laden anbietest. Stelle sicher, dass Aufträge erst in den Status *Warenausgang gebucht* gesetzt werden, wenn die Ware im Laden abgeholt wurde. +
→ Die Kasse zeigt an, dass die Ware übergeben wurde, wenn in plentymarkets ein Warenausgang für den Auftrag gebucht wurde. Falls Probleme auftreten und jemand darauf besteht, die Ware noch nicht erhalten zu haben, prüfe den Auftrag im plentymarkets Backend. Möglicherweise wurde der Warenausgang zu früh automatisch gebucht.

Beachte außerdem die folgenden Hinweise und Einschränkungen beim Abholen und Zahlen von Online-Bestellungen im Laden:

* Online-Aufträge können an der Kasse nicht bearbeitet werden. Das Kassenpersonal kann nur Zahlungen anlegen und Notizen zum Auftrag speichern. +
* Online-Aufträge können an der Kasse erst ab App-Version 1.9.2 mit Verkaufsgutscheinen bezahlt werden. Voraussetzung ist, dass für den Auftrag noch keine Zahlung durchgeführt wurde und noch kein Rechnungsdokument für den Auftrag erstellt wurde.
* Kassenkräfte können Online-Aufträge noch nicht an der Kasse stornieren.
* Zahlungen, die an der Kasse getätigt werden, um einen Online-Auftrag zu bezahlen, sind für die Kasse umsatzneutral. +
→ Im Kassenjournal werden Zahlungen, die nicht umsatzrelevant für die Kasse sind, als Kassenvorfall des Typs *Zahlung* gespeichert.
* Über die Option *Externer Auftrag: Warenausgang automatisch buchen* in den Kasseneinstellungen legst du fest, ob nach der Bezahlung an der Kasse die Ware automatisch aus dem Lager ausgebucht wird. Diese Option ist bei Kassen, die ab 05.03.2019 erstellt werden, standardmäßig aktiviert. Wenn du die Funktion deaktivierst, erkläre deinen Kassenkräften, in welchen Fällen sie den Warenausgang manuell buchen sollen.

[#2900]
[#3000]
== Warenausgang automatisch buchen

Der Warenbestand wird nicht automatisch verringert, wenn du einen Artikel verkaufst. Erstelle die unten beschriebene Ereignisaktion, um Waren automatisch auszubuchen, wenn ein Kassenauftrag erstellt wird. Weitere Informationen zum Verwalten von Warenbestand findest du auf der Handbuchseite <<warenwirtschaft/waren-ausbuchen#, Waren ausbuchen>>.

[.collapseBox]
.Buchen des Warenausgangs beim Erstellen eines Kassenauftrags
--
. Öffne das Menü **System » Systemeinstellungen » Aufträge » Ereignisse**.
. Klicke auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
. Gib einen Namen ein.
. Wähle das **Ereignis** gemäß <<tabelle-POS-ereignisaktion-warenausgang-buchen>>.
. **Speichere** die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-POS-ereignisaktion-warenausgang-buchen>> vor.
. Setze ein Häkchen bei **Aktiv**.
. **Speichere** die Einstellungen.
--

[[tabelle-POS-ereignisaktion-warenausgang-buchen]]
.Ereignisaktion zum automatischen Buchen des Warenausgangs beim Erstellen eines Kassenauftrags
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Dokumente: Kassenbeleg generiert**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|Kassen wählen, für die Warenausgang gebucht werden soll.

|**Aktion**
|**Auftrag &gt; Warenausgang buchen**
|
|====

[#600]
== plentymarkets App auf dem Gerät installieren

Installiere nun die plentymarkets App auf dem Gerät, auf dem die Kasse betrieben werden soll.

* link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=de[plentymarkets App bei Google Play^]

* link:https://itunes.apple.com/de/app/plentymarkets/id957702618[plentymarkets App bei iTunes^]

[WARNING]
.Offline-Aufträge werden beim Deinstallieren der App gelöscht
====
Bei fehlender Internetverbindung werden Aufträge offline gespeichert und erst später synchronisiert. Wenn du die App deinstallierst, bevor die Aufträge an plentymarkets übertragen wurden, werden die lokal gespeicherten Aufträge unwiederbringlich gelöscht und können auch vom plentymarkets Support nicht wiederhergestellt werden. Prüfe deshalb vor jedem Deinstallieren der App, dass keine Offline-Aufträge auf dem Gerät vorhanden sind.
====

[#230]
== Kasse mit Gerät verbinden

Verbinde nun die Kasse mit dem Gerät, auf dem die Kasse betrieben werden soll.

=== Kasse mit Gerät koppeln

Gehe wie unten beschrieben vor, um eine Kasse mit dem Gerät zu koppeln, auf dem die Kasse betrieben werden soll.

[IMPORTANT]
.Automatische Datum- und Zeiteinstellung aktivieren
====
Damit Kassenaufträge und Tagesabschlüsse mit dem plentymarkets Backend korrekt synchronisiert werden, müssen Datum und Uhrzeit des Geräts korrekt eingestellt sein. Deshalb wird empfohlen, das Datum und die Uhrzeit des Geräts automatisch einstellen zu lassen, damit keiner zeitlichen Unstimmigkeiten in den Tagesabschlüssen auftreten.
====

[.instruction]
Kasse mit Gerät koppeln:

. Öffne die plentymarkets App auf dem Gerät, das du mit der Kasse koppeln möchtest.
. Öffne das Menü **plentymarkets App » Einstellungen » POS**.
. Nimm die Einstellungen vor. Beachte <<tabelle-POS-geraet-koppeln>>.
. **Speichere** die Einstellungen. +
→ Das Gerät wird mit der Kasse gekoppelt.

[[tabelle-POS-geraet-koppeln]]
.Kasse mit Gerät koppeln
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Mandant**
|Mandant wählen, für den die Kasse erstellt wurde.

|**POS**
|Kasse wählen.

|**Preis**
|Wählen, ob Aufträge brutto oder netto erstellt werden sollen.

|**Bondrucker**
|IP-Adresse des Bondruckers eingeben. +
**__Tipp:__** Auf **Testbeleg drucken** tippen, um einen Testbeleg zu drucken.

|**Drucker**
|Optional können über das Plugin plentyBase <<1000, weitere Drucker>> angebunden werden.

|**Automatisches Drucken**
|**Ein** = Standardeinstellung. Belege werden automatisch gedruckt, wenn ein Vorgang abgeschlossen wurde. +
**Aus** =  Das Drucken von Belegen muss manuell ausgelöst werden.

|**Darstellung** +
(nur Tablets)
|**Smartphone** =  Für Smartphones optimierte Darstellung; Hoch- oder Querformat. +
**Tablet** = Für Tablets optimierte Darstellung; nur Querformat.

|**Startbeleg erstellen** +
(nur neue Kassen mit Standort Österreich)
|Wählen, um den <<pos/pos-einrichten#900, Startbeleg  zu erstellen>> und so die manipulationssichere Sicherheitseinrichtung für die Kasse zu aktivieren. Nachdem der Startbeleg erstellt wurde, kann das Standortland der Kasse nicht mehr geändert werden.

|**Endbeleg erstellen** +
(nur Kassen mit Standort Österreich und aktivierter Sicherheitseinrichtung)
|Wählen, um <<pos/pos-einrichten#920, den Endbeleg zu erstellen>> und so die manipulationssichere Sicherheitseinrichtung für die Kasse zu deaktivieren. Nachdem der Endbeleg erstellt wurde, kann die Kasse nicht mehr verwendet werden.
|====

[#240]
=== Kasse von Gerät entkoppeln

Du hast die Möglichkeit, die Koppelung einer Kasse mit dem Gerät aufzuheben. Stattdessen kannst du entweder eine andere Kasse mit dem Gerät verbinden oder keine Kasse wählen.

[.instruction]
Kasse von Gerät entkoppeln:

. Öffne die plentymarkets App.
. Öffne das Menü **plentymarkets App » Einstellungen » POS**.
. Wähle für die Einstellung **POS** eine andere Kasse oder wähle den leeren Eintrag.
. **Speichere** die Einstellungen. +
→ Das Gerät wird von der Kasse entkoppelt.

[IMPORTANT]
.Entkoppelung der Kasse nur auf dem Gerät möglich
====
Du kannst die Kasse nur über die Einstellungen auf dem Gerät von der Kasse entkoppeln. Wende dich bei einem Verlust oder Defekt des Geräts an den plentymarkets Support, um die Koppelung aufzuheben.
====

[#250]
== Senden des Kassenbelegs an Bestandskunden einrichten

plentymarkets ermöglicht dir, Kassenbelege per Ereignisaktion automatisch an die am Kundendatensatz gespeicherte E-Mail-Adresse zu senden. Dazu erstellst du zunächst eine E-Mail-Vorlage mit dem PDF-Anhang **Kassenbeleg**. Erstelle dann eine Ereignisaktion. Für Kassenaufträge, die im Offline-Modus erstellt werden, wird die Ereignisaktion jedoch erst ausgeführt, wenn die Kassenaufträge in das plentymarkets Backend hochgeladen werden. Prüfe die aktuellen gesetzlichen Bestimmungen zum Versand von E-Mails, bevor du die Ereignisaktion aktivierst.

[#260]
=== E-Mail-Vorlage erstellen

Erstelle zunächst eine <<crm/e-mails-versenden#1200, E-Mail-Vorlage>>, die versendet wird, wenn ein Kassenbeleg generiert wird.

[.instruction]
E-Mail-Vorlage erstellen:

. Öffne das Menü **System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen**.
. Klicke auf **Neue E-Mail-Vorlage**. +
→ Das Fenster **Neue E-Mail-Vorlage** wird geöffnet.
. Gib einen Namen für die Vorlage ein.
. Wähle einen Eigner oder **Alle** aus der Dropdown-Liste **Eigner**.
. Klicke auf **Speichern**. +
→ Die E-Mail-Vorlage wird erstellt und je nach gewähltem Eigner in einem der drei Ordner gespeichert.
. Wähle den PDF-Anhang **Kassenbeleg**.
. Nimm die weiteren Einstellungen vor. Beachte die Erläuterungen unter <<crm/e-mails-versenden#1200, Neue E-Mail-Vorlage erstellen>>.
. **Speichere** die Einstellungen.

[#270]
=== Ereignisaktion für automatischen E-Mail-Versand erstellen

Erstelle nun eine Ereignisaktion, über die die E-Mail-Vorlage versendet wird, wenn ein Kassenbeleg generiert wird.

[.collapseBox]
.Ereignisaktion für automatischen E-Mail-Versand erstellen
--
. Öffne das Menü **System » Systemeinstellungen » Aufträge » Ereignisse**.
. Klicke auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
. Gib einen Namen ein.
. Wähle das **Ereignis** gemäß <<tabelle-POS-ereignisaktion-beleg-senden>>.
. **Speichere** die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-POS-ereignisaktion-beleg-senden>> vor.
. Setze ein Häkchen bei **Aktiv**.
. **Speichere** die Einstellungen.
--

[[tabelle-POS-ereignisaktion-beleg-senden]]
.Ereignisaktion zum automatischen Senden des Kassenbelegs
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Dokumente: Kassenbeleg generiert**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag** +
**Retoure**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|Kasse wählen, für die Kassenbelege per E-Mail versendet werden sollen.

|**Aktion**
|**Kunde &gt; E-Mail versenden**
|**Vorlage**: Die E-Mail-Vorlage für Kassenbeleg wählen +
**Empfänger**: Option **Kunde** wählen
|====

[#1000]
== Druck von Kassenbelegen über andere Drucker einrichten

Standardmäßig werden alle Kassenbelege über den Bondrucker gedruckt, den du im Menü *plentymarkets App » Einstellungen » POS* über die Option *Bondrucker* festlegst. Zusätzlich kannst du aber Kassenbelege auch auf anderen Druckern ausdrucken. Zum Beispiel kann es sinnvoll sein, Belege auf einem DIN-A4-Drucker statt auf Thermopapier zu drucken, die länger aufbewahrt werden müssen.

Um zusätzliche Drucker zu nutzen, benötigst du einen im Netzwerk zugänglichen Rechner, der mit einem oder mehreren Druckern verbunden ist, über die du die Kassenbelege drucken möchtest. Auf diesem Rechner installierst du das Plugin link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyBase^]. plentyBase dient dazu, eine Verbindung zwischen der plentymarkets App und dem lokalen Rechner herzustellen. So kann die Kasse auf die Drucker zugreifen, auf die auch der lokale Rechner zugreifen kann. Im plentymarkets Backend konfigurierst du diese Drucker im Menü *System » Systemeinstellungen » Einstellungen » Drucker*.

[TIP]
.Bondrucker läuft ohne plentyBase
====
Der Bondrucker wird über die IP-Adresse des Druckers an die plentymarkets App angebunden. Deshalb ist plentyBase für die Nutzung des Bondruckers nicht erforderlich. Du benötigst plentyBase also nur, wenn du andere Drucker an plentymarkets POS anbinden möchtest.
====

[#1010]
=== plentyBase installieren und einrichten

plentyBase ist ein von plentymarkets entwickeltes Plugin. Anders als die meisten anderen plentymarkets Plugins wird plentyBase jedoch nicht im plentymarkets Backend aktiviert. Stattdessen wird plentyBase auf einem lokalen Rechner installiert und ausgeführt. plentyBase stellt eine Schnittstelle bereit, über die du aus dem plentymarkets Backend und/oder der plentymarkets App die Drucker nutzen kannst, die an den Computer angeschlossen sind.

Damit die Drucker in der plentymarkets App verfügbar sind, müssen die folgenden Vorraussetzungen erfüllt sein:

* plentyBase muss auf dem Rechner installiert sein. +
→ Die Installationsdatei lädst du im link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyMarketplace^] herunter.
* plentyBase muss auf dem Rechner konfiguriert sein. +
→ Die Konfigurationsanleitung findest du in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyBase^]. +
*_Hinweis:_* Aktiviere beim Konfigurieren die Option *HTTP-Server*. Nur so kann plentymarkets POS mit plentyBase kommunizieren.
* plentyBase muss auf dem Rechner gestartet sein. +
*_Empfehlung:_* Konfiguriere plentyBase so, dass plentyBase beim Starten des Rechners automatisch gestartet wird.
* Die Verbindungsdaten von plentyBase müssen in der plentymarkets App gespeichert sein. +
→ Wie du die plentyBase Verbindungsdaten in der App speicherst, erfährst du in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053#140.[plentyBase^].
* Die Drucker müssen im plentymarkets Backend im Menü *System » Systemeinstellungen » Einstellungen » Drucker* konfiguriert sein.

[#1020]
=== Drucker für Kassenbelege speichern

Nachdem du plentyBase eingerichtet hast, kannst du im Menü *plentymarkets App » Einstellungen » POS* im Bereich *Drucker* die im plentymarkets Backend konfigurierten Drucker wählen.

Gehe wie unten beschrieben vor, um festzulegen, welche Kassenbelege über welchen Drucker gedruckt werden sollen.

[.instruction]
Drucker pro Belegart festlegen:

. Öffne die plentymarkets App.
. Öffne das Menü *plentymarkets App » Einstellungen » POS*.
. Nimm im Bereich *Drucker* die Einstellungen vor. Beachte <<tabelle-POS-drucker>>.
. **Speichere** die Einstellungen.

[[tabelle-POS-drucker]]
.Drucker für Kassenbelege festlegen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Standard-Drucker*
|In der Dropdown-Liste den Standard-Drucker für die Kasse wählen. Standardmäßig ist der Bondrucker vorausgewählt. +
*_Hinweis:_* In der Dropdown-Liste werden der Bondrucker und die Drucker im Netzwerk angezeigt, auf die die Kasse Zugriff hat.
Wenn in der Dropdown-Liste außer dem Bondrucker und dem Standarddrucker keine Drucker angezeigt werden, wird es Zeit für ein <<1040, Troubleshooting>>.

|*Kaufbeleg*; +
*Tagesabschluss*; +
*Zwischenbericht*; +
*Kassensturz*; +
*Stornierungsbeleg*; +
*Einlage und Entnahme*; +
*Gutscheinbeleg*; +
*Retourenbeleg*; +
*Gutschriftbeleg*
|Der Standard-Drucker ist vorausgewählt. Wenn alle Kassenbelege auf dem Standard-Drucker gedruckt werden sollen, sind keine weiteren Einstellungen erforderlich. Sonst in den Dropdown-Listen der einzelnen Kassenbelege den Drucker wählen, auf dem der Beleg gedruckt werden soll. +
*_Hinweis:_* In den Dropdown-Listen werden der Bondrucker und die Drucker im Netzwerk angezeigt, auf die die Kasse Zugriff hat.
Wenn in den Dropdown-Listen außer dem Bondrucker und dem Standarddrucker keine Drucker angezeigt werden, wird es Zeit für ein <<1040, Troubleshooting>>.
|====

[#1060]
=== Testseite drucken

Gehe wie unten beschreiben vor, um eine Testseite zu drucken.

[.instruction]
Testseite drucken:

. Öffne die plentymarkets App.
. Öffne das Menü *plentymarkets App » Einstellungen » POS*.
. Tippe oben rechts auf das Menü-Symbol.
. Tippe auf *Testdruck*. +
→ Das Fenster *Testdruck* wird angezeigt.
. Wähle in der Dropdown-Liste den Beleg, für den du das Drucken testen möchtest.
. Tippe auf *Testseite drucken*. +
→ Eine Testseite wird gedruckt. +
→ Wenn keine Testseite gedruckt wird, prüfe die Einstellungen wie im <<1050, Troubleshooting-Fall 2>> beschrieben.

[#1030]
=== Troubleshooting: Fehler bei Druckern

[#1040]
==== Fall 1: In den Kasseneinstellungen können keine Drucker gewählt werden

Du hast bisher noch keine zusätzlichen Drucker in den POS-Einstellungen gespeichert. In den Dropdown-Listen des Bereichs *Drucker* werden außer dem Bondrucker und dem Standard-Drucker keine Drucker angezeigt. Bondrucker und Standard-Drucker sind in diesem Fall identisch.

* Ist plentyBase auf einem Rechner im Netzwerk installiert? +
→ Die Installationsdatei lädst du im link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyMarketplace^] herunter.
* Wurde plentyBase korrekt konfiguriert? +
→ Die Konfigurationsanleitung findst du in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyBase^]. +
*_Tipp:_* Wurde die Option *HTTP-Server* aktiviert und ein HTTP-Port angegeben?
* Wurden die plentyBase Einstellungen in der App gespeichert? +
→ Wie du die plentyBase Verbindungsdaten in der App speicherst, erfährst du in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053#140.[plentyBase^]. +
*_Tipp:_* Wurde der richtige HTTP-Port in der App gespeichert?
* Ist plentyBase auf dem Rechner gestartet? +
*_Empfehlung:_* Konfiguriere plentyBase so, dass plentyBase beim Starten des Rechners automatisch gestartet wird.
* Wurde der Drucker im plentymarkets Backend <<basics/admin-aufgaben/drucker#, gespeichert und konfiguriert>>?

[#1050]
==== Fall 2: Drucker sind in den Kasseneinstellungen gespeichert, aber nicht erreichbar

Der Drucker wurde für den Druck einer oder mehrerer Belege ausgewählt und die Einstellungen gespeichert. Der Drucker ist aber nun mit einem Dreieck gekennzeichnet und nicht erreichbar.

* Ist der Rechner an, auf dem plentyBase installiert ist?
* Ist der Drucker an und funktionsbereit?
* Ist der Drucker mit dem Rechner verbunden?
* Ist plentyBase auf dem Rechner gestartet?
* Wurden die plentyBase Konfigurationseinstellungen vor kurzem geändert, zum Beispiel der HTTP-Port oder der Access Token? +
→ Wenn ja, wurden die neuen Einstellungen in der plentymarkets App gespeichert?
* Wurde die Druckerkonfiguration aus dem plentymarkets Backend entfernt? +
→ Drucker konfigurierst du im Menü *System » Systemeinstellungen » Einstellungen » Drucker*.

[#1090]
== Druck von Artikeletiketten einrichten

Wie du Etikettenvorlagen erstellst und Artikeletiketten in der Artikelsuche der plentymarkets App druckst, erfährst du unter <<artikel/artikel-verwalten#760, Etiketten einrichten>>.

[IMPORTANT]
.plentyBase konfigurieren
====
Um Etiketten drucken zu können, benötigst du das kostenlose Plugin plentyBase. plentyBase stellt eine Schnittstelle bereit, über die du aus dem plentymarkets Backend und/oder der plentymarkets App die Drucker nutzen kannst, die an den Computer angeschlossen sind. Wie du plentyBase installierst und konfigurierst erfährst du in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/integration/plentyBase_5053[plentyBase^].
====


[#400]
== Kassenvorgänge im Kassenjournal suchen

Alle Kassenvorgänge werden in plentymarkets dokumentiert. Im Menü **Aufträge » POS » Kassenjournal** kannst du Kassenvorgänge suchen, anzeigen und bei Bedarf exportieren. Mit den Filtern des Tabs **Filter** grenzt du die im Kassenjournal angezeigten Kassenvorgänge anhand bestimmter Kriterien ein. Die gefundenen Kassenvorgänge werden im Tab **Kassenjournal** aufgelistet. Die Ergebnisse sind standardmäßig nach dem Datum sortiert. Gehe wie unten beschrieben vor, um Kassenvorgänge im Kassenjournal zu suchen.

[.instruction]
Kassenvorgänge im Kassenjournal suchen:

. Öffne das Menü **Aufträge » POS » Kassenjournal**.
. Wähle die Filter. Beachte die Erläuterungen in <<tabelle-POS-kassenjournal-menue>>.
. Klicke auf **Suchen**. +
→ Die Kassenvorgänge, die den Suchkriterien entsprechen, werden im Tab **Kassenjournal** aufgelistet.

[[tabelle-POS-kassenjournal-menue]]
.Menü *Kassenjournal*
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Tab: Filter

|*Suchen*
|Ohne Filtereinstellungen auf *Suchen* klicken, um alle Kassenvorgänge anzuzeigen. +
*_Oder:_* Die Suchergebnisse durch Filtereinstellungen eingrenzen und auf *Suchen* klicken. Die gefundenen Kassenvorgänge werden im Tab *Kassenjournal* aufgelistet.

|**Reset**
|Eingestellte Filterkriterien zurücksetzen.

|**Belegnummer: von**; +
**Belegnummer: bis**
|Die Belegnummer des ersten und des letzten Belegs eingeben, um Kassenvorgänge einer bestimmten Belegabfolge anzuzeigen. Um nur einen Beleg anzuzeigen, die gesuchte Belegnummer in die Felder **Belegnummer: von** und **Belegnummer: bis** eingeben.

|*Buchungskonto*
|Ein <<pos/pos-einrichten#950, Buchungskonto>> eingeben, um Kassenvorgänge eines bestimmten Buchungskontos anzuzeigen.

|*Verk. Gutscheine zu Umsatz*
|Möchtest du verkaufte Gutscheine wie Umsätze behandeln? +
*Häkchen gesetzt* = Gutscheinverkäufe zählen zum Umsatz. Die Beträge werden also als "Einnahmen" im Kassenjournal verzeichnet. Gutscheinverkäufe fließen in den Wert rein, der rechts in die Spalte *Betrag* zu sehen ist. Gutscheine werden auch im PDF-Export und CSV-Export wie Umsätze behandelt.

|**Mandant (Shop)**
|Einen Mandanten (Shop) aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieses Mandanten einzugrenzen.

|**Kasse**
|Eine Kasse aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieser Kasse einzugrenzen.

|**Benutzer**
|Einen Benutzer aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieser Kassenkraft einzugrenzen.

|**Zahlungsart**
|Eine Zahlungsart aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge mit dieser Zahlungsart einzugrenzen. Die Dropdown-Liste enthält nur aktive Zahlungsarten.

|**Zeitraum**
|Eine Zeitspanne wählen, um die angezeigten Kassenvorgänge auf diesen Zeitraum zu beschränken. +
Um Belege eines benutzerdefinierten Zeitraums anzuzeigen, die Option **Datumsauswahl** wählen und im Feld **von** das Startdatum und im Feld **bis** das Enddatum eingeben oder aus dem angezeigten Kalender wählen.

|**Typ**
|Einen Typ aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieses Typs einzugrenzen.

2+|Tab: Kassenjournal

|**Datum**
|Datum und Uhrzeit des Kassenvorgangs

|**Vorgang**
|Zeigt an, ob der Vorgang eine Einnahme (**E**) oder eine Ausgabe (**A**) ist.

|**Betrag**
|Der Wert des Kassenvorgangs

|**Belegnummer**
|Die fortlaufende Nummer des Belegs, der für den Kassenvorgang erstellt wurde. Auf die Belegnummer klicken, um den Beleg im PDF-Format zu öffnen.

|**Typ**
|Der Typ des Kassenvorgangs

|**Barbestand**
|Der Barbestand der Kassen nach Abschluss des Kassenvorgangs

|**Auftrags-ID**
|Die ID des in plentymarkets erstellten Auftrags

|**Steuersatz**
|Die Steuersätze, die für diesen Auftrag zum Tragen kommen.

|**USt.**
|Die im Auftragswert enthaltene Umsatzsteuer

|**Buchungstext**
|Der Buchungstext für den Kassenvorgang. Bei Einlagen und Entnahmen entspricht der Buchungstext dem Grund der Bargeldbewegung.
|====

[#300]
== Kassenvorgänge in Deutschland rechtssicher belegen

Für eine ordnungsgemäße Kassenführung in Deutschland müssen alle Kassenvorgänge elektronisch und unveränderbar aufgezeichnet und für die Dauer des Aufbewahrungszeitraums digital lesbar archiviert werden. Damit du diesen gesetzlichen Anforderungen nachkommen kannst, stellt plentymarkets verschiedene Exportfunktionen bereit. Bespreche mit deinem Steuerberater, welche Daten du exportieren und archivieren solltest, um rechtssicher zu arbeiten.

=== Kassenvorgänge als PDF-/CSV-Datei exportieren

Die im Kassenjournal angezeigten Kassenvorgänge kannst du entweder als PDF-Datei oder als CSV-Datei exportieren. Exportiert werden die über die Suche gefilterten Kassenvorgänge. Gehe wie unten beschrieben vor, um Kassenvorgänge zu exportieren. Nachdem du einen Exportvorgang gestartet hast, ist das Starten weiterer Kassenjournalexporte zwei Minuten lang nicht möglich.

[.instruction]
Kassenvorgänge als PDF-Datei exportieren:

. Öffne das Menü **Aufträge » POS » Kassenjournal**.
. Wähle die Filter. Beachte die Erläuterungen in <<tabelle-POS-kassenjournal-menue>>.
. Klicke auf **Suchen**. +
→ Die Kassenvorgänge, die den Suchkriterien entsprechen, werden im Tab **Kassenjournal** aufgelistet.
. Klicke auf **PDF-Export**. +
→ Eine PDF-Datei der gefilterten Kassenvorgänge wird generiert. Abhängig von der Anzahl der Datensätze kann dieser Vorgang mehrere Minuten dauern. +
→ Die PDF-Datei wird in einem separaten Browser-Fenster angezeigt.
. **Speichere** die PDF-Datei.

[.instruction]
Kassenvorgänge als CSV-Datei exportieren:

. Öffne das Menü **Aufträge » POS » Kassenjournal**.
. Wähle die Filter. Beachte die Erläuterungen in <<tabelle-POS-kassenjournal-menue>>.
. Klicke auf **Suchen**. +
→ Die Kassenvorgänge, die den Suchkriterien entsprechen, werden im Tab **Kassenjournal** aufgelistet.
. Klicke auf **CSV-Export**.
. Wähle und bestätige einen Speicherort für die CSV-Datei. +
→ Eine CSV-Datei der gefilterten Kassenvorgänge wird generiert. Abhängig von der Anzahl der Datensätze kann dieser Vorgang mehrere Minuten dauern. +
→ Die CSV-Datei wird gespeichert.

[#500]
=== IDEA-Export erstellen

Laut den deutschen handels- und steuerrechtlichen Ordnungsvorschriften (GoBD) musst du bei einer Außenprüfung auf Verlangen der Finanzverwaltung nicht nur aufzeichnungs- und aufbewahrungspflichtige Daten vorlegen, sondern auch alle zur Auswertung der Daten notwendigen Strukturinformationen in maschinell auswertbarer Form bereitstellen. Deshalb stellt plentymarkets einen GoBD-konformen Export der Kassenvorgänge bereit. Die Exportdateien ermöglichen Betriebsprüfern, deine Kassendaten vollständig und effizient auszuwerten. Gehe wie unten beschrieben vor, um einen IDEA-Export zu erstellen:

[.instruction]
IDEA-Dateien exportieren:

. Öffne das Menü **Aufträge » POS » IDEA-Export**.
. Wähle das Kalenderjahr, für das du die Daten exportieren möchtest.
. Klicke auf das Zahnrad, um den Export zu generieren. +
→ Der Export wird über Nacht generiert. +
→ Der Export ist abgeschlossen, wenn der Status **Fertig** angezeigt wird.
. Klicke auf das Download-Symbol in der Spalte **Aktionen**.
. Wähle einen Speicherort und bestätige die Auswahl. +
→ Die IDEA-Dateien werden exportiert und als ZIP-Datei gespeichert.

[#960]
== Kassenaufträge im plentymarkets Backend ändern

Für Kassenaufträge wird ein Auftrag im plentymarkets Backend erstellt. Nach dem Erstellen des Auftrags können keine nachträglichen Änderungen von rechtlich relevanten Auftragsdaten vorgenommen werden. Ausgenommen hiervon sind Auftragsdaten, die sich im Rahmen der Bearbeitung und Erfüllung von Aufträgen ändern bzw. deren Historie dokumentieren:

* Sprache
* Status
* Bezahlter Betrag
* Zahlungsstatus
* Retourengründe
* Auftrag lässt sich Sammelauftrag zuordnen
* Lieferanschrift
* E-Mail-Versand
* Auftragsnotiz
* Versanddatum
* Rückgabedatum

[#910]
== Kasse außer Betrieb nehmen

Lösche eine Kasse, die du nicht mehr benötigst, um diese Kasse dauerhaft außer Betrieb zu nehmen. Die Geschäftsvorfälle, die über die Kasse abgewickelt wurden, bleiben im System gespeichert und können weiter steuerrechtlich ausgewertet werden.

[NOTE]
.Besonderheit bei Kassenstandort Österreich
====
Bei Kassen mit Standort Österreich, bei denen die Sicherheitseinrichtung aktiviert wurde, muss der Endbeleg in der App erstellt werden, um die Kasse dauerhaft außer Betrieb zu nehmen. Dadurch wird die Kasse automatisch gelöscht.
====

[.instruction]
Kasse löschen:

. Öffne das Menü **System » Systemeinstellungen » Mandant » Standard » POS**.
. Klicke auf die Kasse. +
→ Das Tab **Grundeinstellungen** der Kasse wird geöffnet.
. Klicke oben links auf **Löschen**. +
→ Die Kasse wird gelöscht. +
**__Hinweis:__** Bei Kassen mit Standort Österreich und aktivierter Sicherheitseinrichtung muss der <<pos/pos-einrichten#920, Endbeleg in der App>> erstellt werden. Dadurch wird die Kasse automatisch gelöscht.

[#860]
== plentymarkets POS in Österreich nutzen

Laut Registrierkassensicherheitsverordnung (RKSV) müssen Registrierkassen in Österreich mit einer technischen Sicherheitseinrichtung ausgestattet sein, die dafür sorgt, dass die über die Kasse abgewickelten Kassenvorgänge manipulationssicher, also nicht mehr veränderbar sind. Sichtbares Zeichen für diesen Manipulationsschutz ist der QR-Code auf dem Kassenbeleg. Hier erfährst du, wie du Kassen in Betrieb nimmst und nutzt, die in Österreich betrieben werden sollen.

[#870]
=== Übersicht: Inbetriebnahme der Kasse

Für Kassen mit Standort Österreich sind die in <<tabelle-inbetriebnahme-kasse-österreich>> erläuterten Schritte notwendig, um die von der RKSV vorgeschriebene Sicherheitseinrichtung in Betrieb zu nehmen. Detaillierte Informationen zu diesen rechtlichen Anforderungen findest du auf der Website des österreichischen link:https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/Sicherheitseinrichtung_in_Registrierkassen.html[Bundesministeriums für Finanzen^]. Auf dieser Handbuchseite werden nur die Schritte beschrieben, die erforderlich sind, um eine plentymarkets POS Kasse mit Standort Österreich in Betrieb zu nehmen. Die Beschreibung ersetzt keine rechtliche und steuerrechtliche Beratung.

[[tabelle-inbetriebnahme-kasse-österreich]]
.Kasse in Österreich in Betrieb nehmen
[cols="1,2,3"]
|====
|Reihen- folge |Schritt |Erläuterung

|1.
|Signaturkarte und Signaturkartenleser beschaffen
a|* plentymarkets POS ist für den Einsatz mit dem Feitian Smartcard-Leser link:http://www.cryptoshop.com/feitian-br301-bluetooth-reader.html[bR301^] optimiert.
* plentymarkets testet mit den Signaturkarten des Vertrauensdiensteanbieters link:https://www.prime-sign.com/[PrimeSign^].

|2.
|Manipulationssichere Registrierkasse initialisieren
|Siehe <<pos/pos-einrichten#50, Grundeinstellungen der Kasse vornehmen>>

|3.
|Startbeleg erstellen
|Siehe <<pos/pos-einrichten#900, Startbeleg erstellen>>

|4.
|Signaturkarte und Registrierkasse bei FinanzOnline registrieren
a|Nachdem der Startbeleg erstellt wurde, registrierst du Signaturkarte und Registrierkasse bei FinanzOnline. Für die Registrierung benötigst du die folgenden Daten: +

Signaturkarte (Unterlagen der Signaturkarte): +

* Die Seriennummer des Signaturzertifikats
* Den Namen des Vertrauensdiensteanbieters, bei dem das Zertifikat erworben wurde
* Die PIN des Signaturzertifikats

Registrierkasse (**Einstellungen » Mandant » Standard » POS » Kasse öffnen » Tab: Grundeinstellungen**): +

* Die Kassenidentifikationsnummer der plentymarkets POS Kasse. Die **Kassenidentifikationsnummer** findest du im Menü **Einstellungen » Mandant » Standard » POS » Kasse öffnen » Tab: Grundeinstellungen**.
* Den **Benutzerschlüssel AES-256**, der im Menü **Einstellungen » Mandant » Standard » POS » Kasse öffnen » Tab: Grundeinstellungen** angezeigt wird.

|5.
|Startbeleg mit der BMF-Belegcheck-App scannen
|Scanne den QR-Code auf dem Startbeleg der Kasse, nachdem du die Registrierung bei FinanzOnline abgeschlossen hast. Die App prüft dabei die Gültigkeit der Signatur auf den Belegen der Registrierkasse. +
**__Tipp:__** Zwischen dem Zeitpunkt der Registrierung von Signaturkarte und Registrierkasse über FinanzOnline und der Prüfung des Startbelegs darf nicht mehr als eine Woche liegen.
|====

[IMPORTANT]
.Existierende Kassen mit Standort Österreich
====
Existierende Kassen können nicht nachträglich manipulationssicher gemacht werden. Wenn du bereits eine plentymarkets POS Kasse in Österreich betreibst, erstellst du eine neue Kasse und nimmst die alte Kasse außer Betrieb.
====

[#900]
=== Startbeleg erstellen (Standort Österreich)

Erstelle nun den Startbeleg, um die Kasse in Betrieb zu nehmen. Du benötigst die PIN für das Signaturzertifikat des Vertrauensdiensteanbieters, um den Startbeleg zu erstellen. Den Startbeleg erstellst du im POS-Menü der plentymarkets App. Nachdem der Startbeleg erstellt wurde, kann das Standortland der Kasse nicht mehr geändert werden.

[.instruction]
Startbeleg erstellen:

. Öffne die plentymarkets App.
. Öffne das Menü **plentymarkets App » Einstellungen » POS**.
. Gib die PIN für das Signaturzertifikat des Vertrauensdiensteanbieters ein.
. Tippe auf **Startbeleg erstellen**. +
→ Der Startbeleg wird gedruckt. +
→ Der Startbeleg wird im Kassenjournal und im Dokumentenarchiv gespeichert. +
→ Die Kasse kann in Betrieb genommen werden. +
→ Belege werden signiert und der QR-Code auf Belegen ausgegeben. +
→ Kassenvorgänge werden DEP-konform im System gespeichert.

[#880]
=== Kassenvorgänge in Österreich belegen

Laut der österreichischen Registrierkassensicherheitsverordnung (RKSV) müssen Belege signiert und mit einem QR-Code versehen werden. Dieser QR-Code enthält die wesentlichen Beleginhalte, einen verschlüsselten Umsatzzähler und einen Verweis auf den letzten Beleg. Dieser Verweis sorgt dafür, dass die vorhergehenden Belege nicht mehr verändert oder gelöscht werden können. Außerdem muss für jede Registrierkasse ein Datenerfassungsprotokoll geführt werden, das jederzeit lokal exportiert werden kann.

Damit du diesen gesetzlichen Anforderungen nachkommen kannst, stellt plentymarkets verschiedene Exportfunktionen bereit. Bespreche mit deinem Steuerbüro, welche Daten du exportieren und archivieren solltest, um rechtssicher zu arbeiten.

[#890]
==== DEP-Export erstellen

Laut §7 der österreichischen Registrierkassensicherheitsverordnung (RKSV) muss jede Registrierkasse über ein Datenerfassungsprotokoll (DEP) verfügen. Im DEP sind mindestens die Signierung von Belegen im Zusammenhang mit Barumsätzen und die Stornierung von Barumsätzen zu speichern. Die Unveränderlichkeitkeit der Daten ergibt sich dabei aus der Signaturverkettung. Pro DEP darf nur eine Kasse abgebildet werden.

Der DEP-Export wird als JSON-Datei bereitgestellt und enthält die folgenden Belegdaten:

* Belege-Gruppe
* Signaturzertifikat
* Zertifizierungsstellen
* Belege-kompakt

Das DEP einer Registrierkasse muss dabei auf Verlangen jederzeit auf einen externen Datenträger im vorgesehenen Exportformat exportiert werden können. Gehe wie unten beschrieben vor, um einen DEP-Export zu erstellen:

[.instruction]
DEP-Dateien exportieren:

. Öffne das Menü **Aufträge » POS » DEP-Export**.
. Wähle den Mandanten (Shop), für den du Daten exportieren möchtst.
. Wähle die Kasse, für die du Daten exportieren möchtst.
. Wähle das Datum, ab dem du Daten exportieren möchtst.
. Wähle das Datum, bis zu dem du Daten exportieren möchtst.
. Klicke auf *Herunterladen*. +
→ Die Datei wird im Standard-Download-Ordner des Browsers gespeichert. +
*_Tipp:_* Der Dateiname enthält den Exportzeitraum, zum Beispiel depExport_9-1-2017-9-2-2017.json für Daten von 9.1. bis 9.2.2017.

[#4200]
==== Monatsbeleg erstellen (Österreich)

Monatsbelege sind signierte Kontrollbelege mit einem Betrag von Null (0,00) Euro. Laut RKSV muss am Ende jedes Monats ein Monatsbeleg erstellt werden. Der Monatsbeleg für den Monat Dezember dient gleichzeitig als Jahresbeleg. Diesen Jahresbeleg musst du jedes Jahr zusätzlich ausdrucken, aufbewahren und den Barcode mit der BMF Belegcheck-App prüfen.

[#4300]
===== Berechtigungen für Monatsbelege erteilen

Kassenpersonal mit Admin-Rechten hat standardmäßig die Berechtigung, Monatsbelege zu erstellen. Kassenpersonal mit der Benutzerklasse *Backend* muss diese Berechtigung erteilt werden.

[.instruction]
Benutzern Berechtigungen für Monatsbelege erteilen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer*.
. Öffne das Konto des Benutzers.
. Öffne das Tab *Mobile*.
. Aktiviere im Bereich *POS-Funktionen* die Berechtigung *Monatsbeleg (AT)*.
. *Speichere* die Einstellungen. +
→ Die Kassenbenutzerin ist berechtigt, <<pos/pos-kassenbenutzer#270, Monatsbelege in plentymarkets POS>> zu erstellen.

[#4400]
=== SOS: Die Signatureinheit ist ausgefallen - was jetzt?

Die RKSV gibt vor, wie du vorgehen musst, falls die Signatureinheit der Registrierkasse ausfällt:

* Wenn die Signatureinheit ausfällt, musst du Geschäftsfälle auf einer anderen Registrierkasse mit funktionierender Signatureinheit erfassen.
* Wenn keine andere Registrierkasse verfügbar ist, kann die Registrierkasse temporär ohne Signatureinheit betrieben werden.
* Dauert der Ausfall der Signatureinheit länger als 48 Stunden, musst du Beginn und Ende des Ausfalls innerhalb einer Woche über FinanzOnline dem Finanzamt melden.
* Sämtliche nicht signierte Belege müssen mit dem Hinweis *Sicherheitseinrichtung ausgefallen* versehen werden. +
→ In plentymarkets POS werden Belege automatisch mit diesem Hinweis versehen, wenn die Signatureinheit ausfällt.
* Sobald die Signatureinheit wieder funktioniert, muss ein signierter Sammelbeleg erstellt werden, der sämtliche Geschäftsvorfälle enthält, die im Ausfallzeitraum über die Registrierkasse abgewickelt wurden. +
→ plentymarkets POS erstellt automatisch einen signierten Sammelbeleg, wenn die Signatureinheit wieder in Betrieb genommen wird.

[#930]
=== Kontrollbeleg auf Verlangen der Finanzpolizei erstellen

Bei einer Kassenrückschau durch die Finanzpolizei muss auf Verlangen ein Kontrollbeleg mit dem Betrag Null erstellt werden. Mit diesem Kontrollbeleg kann die prüfende Person die Gültigkeit der Signatur mit einer Prüf-App direkt vor Ort in deinem Laden prüfen. Jede Kassenkraft kann einen solchen <<pos/pos-kassenbenutzer#270, Kontrollbeleg auf Verlangen>> erstellen. Zum Erstellen des Kontrollbelegs sind keine zusätzlichen Berechtigungen erforderlich.

[#920]
=== Kasse außer Betrieb nehmen (Standort Österreich)

Um eine Kasse mit Standort Österreich dauerhaft außer Betrieb zu nehmen, erstellst du einen Endbeleg. Ein Endbeleg ist ein signierter Kontrollbelege mit einem Betrag von Null (0,00) Euro, der nur erstellt werden kann, wenn für die Kasse auch ein Startbeleg erstellt wurde. Den Endbeleg erstellst du im POS-Menü der plentymarkets App. Nachdem ein Endbeleg für die Kasse erstellt wurde, kann die Kasse nicht mehr verwendet werden.

[.instruction]
Endbeleg erstellen:

. Öffne die plentymarkets App.
. Öffne das Menü **plentymarkets App » Einstellungen » POS**.
. Tippe auf **Endbeleg erstellen**. +
→ Der Endbeleg wird gedruckt. +
→ Der Endbeleg wird im Kassenjournal und im Dokumentenarchiv gespeichert. +
→ Die Kasse kann nicht mehr verwendet werden.
. Melde dem Finanzamt, dass die Kasse außer Betrieb genommen wurde.

//  Next: [#4500]
