= Willkommen bei plentymarkets
:lang: de
include::{includedir}/_header.adoc[]
:position: 10
:url: videos/basics/willkommen-bei-plentymarkets

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Dieses Einführungsvideo richtet sich an neuen plentymarkets Nutzer. Es nimmt dich mit auf eine Tour durchs System und zeigt dir, wie man sich durch die Menüstruktur navigiert. Hast du diese Themen erstmal gemeistert, schau dir die weiteren Videos im Basics-Modul an und lerne weiter alles über plentymarkets.
|<<videos/basics/willkommen-bei-plentymarkets-erster-login#video, Log dich das erste Mal ein (0:16)>>

<<videos/basics/willkommen-bei-plentymarkets-menuestruktur#video, Erkunde die Menüstruktur (0:37)>>

<<videos/basics/willkommen-bei-plentymarkets-nutzername-passwort#video, Ändere Nutzernamen und Passwort (2:07)>>

|===
//end::einleitung[]

video::257449279[vimeo]

// tag::transkript[]
[.collapseBox]
.Transkript
--
Grafik - Plenty-Logo animiert Willkommen bei plentymarkets! Auf geht's direkt in dein neues System für eine kleine Tour 
zum Kennenlernen!
Grafik - Show welcome email that the customer receives (block out actual access data)
Du hast von uns deine ganz persönliche Willkommens-E-Mail erhalten. Und genau dort findest du auch alle wichtigen Daten für deinen ersten Login.
Grafik - Arrow appears to show exactly where this link is in the email
Dieser Link ist deine Eintrittskarte...
Fade to central login ..... und bringt dich direkt zum Login-Bereich.
PID is already entered Alles was du brauchst ist die plentymarkets ID...
Enter user name .... Nutzername....
Enter password .... und das generierte Passwort aus der Willkommens-Mail.
Mouseover "Login" Jeder Login ist übrigens verschlüsselt sprich: absolut sicher!
Grafik - Öffnende Tür Wilkommen in deinem neuen plentymarkets System!
Fade to plenty backend home screen Unter der Haube stecken massig Features und Funktionen, die nur darauf warten von dir
erkundet zu werden.
Move mouse from left to right (plenty P to gravatar) then back again
Das hier oben ist deine Hauptnavigation. Hinter all diesen Punkten steckt natürlich auch noch viel mehr. Was genau zeigen dir die Dropdowns, die sich bei Mouseover öffnen und dich zu allen wichtigen Bereichen von plentymarkets führen.
Mouseover plenty p > Service centre through Relocation
Beispielsweise zu deinen Vertragsdaten oder allen anderen gebuchten Services...
Mouseover Orders (don't click) ...oder zur Übersicht aller Aufträge...
Click on Item > Edit item
Link einblenden - Einführung zum Artikel Modul
...oder auch zu deinen angebotenen Artikeln.
Scroll down a bit through search filters and select "Availability = Ships within 24 hours"
Mit diesen Suchfiltern hier auf der linken Seite... Click Search ... kannst du die Liste auf der rechten
Seite in vielen Menüs auf deine gewünschten Ergebnisse eingrenzen.
Click small triangle > Add link to favourites Arbeitest du oft mit bestimmten Menüs und willst dich immer direkt dorthin navigiieren? Dann
markiere sie doch einfach als Favorit!
Mouseover star > Item menu Denn auch wenn plentymarkets massenhaft Funktionen für dich bereit hält, möchten wir ja
nicht, dass du darin verloren gehst. Deine favorisierten Menüs findest du dann unter dem kleinen Sternchen rechts oben.
Click on "System" menu Unser nächster Stop ist das System-Menü!
Hier Enter "ebay" into search and then click eBay >
konfigurierst du und richtest die Tools und Funktionen von plentymarkets ein. Accounts
Beispielsweise bist du hier genau richtig, wenn du dein ebay-Konto mit plenty verbinden möchtest..
Delete "ebay" and then enter "user" and click User > Accounts
Link einblenden - Benutzerkonten
..... oder wenn du für deine Mitarbeiter Benutzekonten einrichten möchtest, damit auch sie Zugang zum System erhalten.
Close "System" menu Aber es gibt natürlich auch noch einen anderen geschickten Weg, um zu deinem
Nutzerbereich zu gelangen.
Mouseover user gravatar > Click on user name Klicke auf den Benutzer, mit dem du gerade eingeloggt bist...
------ .... und voila! Schon bist du da!
Mouseover "User name = py12345"
Mouseover "Actual name = Demo User" Dieser Demo-Benutzer ist auch super für deinen ersten Login und fürs erste Zurechtfinden. Grafik - Dieb will deine Daten klauen Allerdings sollte natürlich dein erster Schritt sein, diesen Nutzer anzupassen. Schließlich
wollen wir ja nicht, dass jemand in deinen Mails dein Passwort auslesen kann und somit Zugang zu deinem System und sensiblen Firmendaten erhält.
Grafik - Passwort und Benutzername verschwinden in eine Rauchwolke und erscheinen danach nur als Punkte/Kreise/Bullets
Das Schlaueste ist also das generierte Passwort und den Nutzer in deine eigenen Daten zu ändern.
Fade back to plenty user menu Schnell und einfach:
Fade to user name "joan_doe" .... ändere d einen Nutzernamen, dabei achte bitte auf Eindeutigkeit,... Fade to actual name "Joan Doe" ....dann den realen Namen, damit du weißt, wer genau sich dahinter verbirgt.....
Fade to password JoanDoe12hi5! .... und schließlich das Passwort.
Save Wenn du dich das nächste Mal einloggst, nutzt du dann einfach diese personalisierten Daten
statt denen aus der Mail.
Grafik - plenty Logo hat ein Magnet und zieht somit diverse Werkzeuge an sich
Wusstest du, dass du sogar noch mehr Tools und Features in dein System bringen kannst?
Fade back to plenty Ja, wirklich!
Click on Plugins > plentyMarketplace
Link einblenden - Einführung zum Plugin Modul
Schau in den plentyMarketplace...
Click on "Markets" and scroll down to show plugins
...und stöbere durch die Plugins, mit denen du dein plentymarkets-System erweitern kannst!
Fade back to plenty backend and mouseover "Dashboard" tab
Oh und übrigens: Ist dir das Dashboard nach dem Login aufgefallen? Dieser Bereich begrüßt dich immer, wenn du dich in dein System einloggst. Und das Beste daran?
Select Elements = Orders, click on green plus Du kannst anpassen wie du Bock hast, welche Informationen auf der Seite angezeigt
werden. Damit hast du direkt nach dem Login alle wichtigen Kennzahlen im Blick!
Mouseover top menu bar left to right (from plenty p through support and into black area where no menus appear)
Also: Klick dich durch die Menüs und erkunde alle Funktionen von plentymarkets!
Mouseover Support; Move mouse down through Manual, Video tutorials, Forum
Und keine Sorge, falls du auf ein oder zwei Fragen stößt! Dann helfen wir dir gerne weiter. Der Supportbereich bietet für jeden Fall, für jede Vorliebe
Click on Video tutorials and scroll down to show Basics module
Unser Video-Basismodul wird dir sicherlich weiterhelfen. Es richtet sich nämlich vor allem an neue Nutzer von plentymarkets und hilft dir bei der Orientierung.
Grafik - plentymarkets entdecken Worauf wartest du noch? Lege los mit plentymarkets und entdecke die vielfältigen
Funktionen und Tools, mit denen du dein Unternehmen noch weiter nach vorne bringst!

--
//end::transkript[]
