= Accounting
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Accounting, Client (store), Settings
:position: 40

Go to **System » Client » Select client » Locations » Select location » Accounting** to carry out important VAT settings. Decide whether VAT should be displayed on your invoices and how it should be displayed. Save VAT rates for your countries of delivery. Furthermore, save posting keys, debtor accounts and revenue accounts.

Each <<omni-channel/online-store/standard/locations#, **location**>> has its own **Accounting** submenu. The accounting settings only apply to this location. The menu also allows you to copy some or all of the settings for a location and apply these settings to one or more additional locations.

The various areas of the menu and the necessary settings are described on this page. You will also find information about the delivery thresholds for EU countries and information about the data export.

[#10]
== Tab: Basic settings

Use the **Basic settings** tab to carry out settings for the VAT on your invoices. The settings that are carried out here relate to the delivery thresholds. As soon as the delivery threshold of a country was exceeded, VAT has to be paid to that country. In this case, you would need a tax number in the country and you would need to save the country's tax rates in plentymarkets. If tax rates are saved for an EU country of delivery, then sellers from this country would receive gross invoices even if you selected net invoice. Pay attention to the notes in the table.

[.instruction]
Carrying out the basic settings:

. Go to **System » Client » Select client » Locations » Select location » Accounting » Tab: Basic settings**.
. Pay attention to the explanations given in table 1 and carry out the settings as desired.
. *Save* the settings.

[cols="1,3"]
|====
|Setting
|Explanation

|**VAT number**
|Only applies to deliveries within the EU. +
**Net invoice** = Invoices will be issued without VAT for customers who have a VAT number. +
VAT is omitted when a German seller ships items to a customer who is in a different European country and has a valid VAT number. The order is issued as net. However, if the customer's delivery address is also in Germany, then VAT will be calculated for the order. German law permits orders to be issued as net for customers from other European countries who have a valid VAT number and provide a German delivery address. In this case, an <<omni-channel/online-store/standard/documents/entry-certificate#, **entry certificate**>> needs to be included with the order. The **<<order-processing/orders/_accounting#10, Delivery addresses>>** menu includes the option **Entry certificate** for this reason. If a check mark is placed next to the **Entry certificate** option, then orders that are placed by customers in other European countries but shipped to a German delivery address will be treated like shipments to foreign EU countries. The settings **VAT number** and **Export shipping** in this menu then determine whether the invoice is issued as gross or net. If no check mark is placed next to the **Entry certificate** option, then these orders will be issued as gross. +
**Gross invoice** = All invoices will be issued as gross.

|**Export shipping**
|**Net invoice** = Invoices for export shipping will be issued without VAT. +
**Gross invoice** = VAT will be displayed on invoices for export shipping. +
If a VAT rate was saved for an export country of delivery, then gross invoices will always be issued.

|**Show VAT for the shipping costs on the invoice**
|Select when the VAT on shipping costs should be displayed individually. +
**Always** = The VAT on shipping costs will always be displayed. +
**Domestic and EU only** = The VAT will not be displayed for export shipping.

|**Business that is exempt from VAT (German law: small business owners 19 UStG)**
|Place a check mark if VAT should neither be displayed on the invoice nor during the online store order process. +
This setting is relevant for small business owners according to § 19 UStG (German VAT Act), i.e. businesses that are exempt from VAT due to their revenue being below the VAT threshold. The option is voluntary. Even small businesses can choose to display the VAT if it is advantageous. Further information about the German tax system can be found online, for example at the following link:http://www.banktip.de/rubrik2/20085/6/die-regelung-des-19-ustg.html[**link**].
|====

__Table 1: **basic settings** tab__

[#20]
== Case example

A German seller runs an online store and created the location **Germany** for the company's headquarters. The company's sales warehouse is also located in Germany. The seller also uses an FBA warehouse in Poland for products that are sold on Amazon. As such, the seller created a second location **Poland**. The seller configured the following tax rates in the accounting settings:

[cols="1,3,3"]
|====
|Location |VAT rate 1 |VAT rate 2

|Germany
|DE (standard VAT rate)
|AT

|Poland
|DE
|PL (standard VAT rate)
|====

__Table 2: example: locations and VAT rates__

The seller exceeded the delivery threshold for Austria. As such, the seller created a VAT rate for Austria as part of the German accounting information. However, the seller has not created a VAT rate for Austria as part of the Polish accounting information. Therefore, the Polish location can not make use of this Austrian VAT rate.

[#30]
=== What happens in the shopping cart and in the order?

Warehouse information is not included in the order process. Therefore, orders automatically use the default location and this location's default VAT rate and warehouse. If the order includes an item that is stored in the Polish FBA warehouse, then this will be visible in the order information. Based on the item's warehouse, the correct location and default VAT rate will be applied to the order. If a location uses a different default VAT rate than is used by the default location, then there may be discrepancies in the VAT rates displayed in the order and on the invoice. In this example, the location Germany uses the Austrian VAT rate for orders that are delivered to Austria. However, it uses the Polish VAT rate for the location Poland.

[#40]
=== Stock

If the seller in this example wants to use the Austrian VAT rate for Austrian customers, then the seller needs to have the item in stock at the German warehouse. Or the seller could set up another location in Austria.

[#50]
== Tab: VAT rates

Use the **VAT rates** tab to save the VAT rates for countries of delivery that you are required to pay VAT for. This is the case if you have exceeded the delivery thresholds (see the section about delivery thresholds further below). In such a case, you receive a VAT number from the tax office in the country of delivery and you have to pay the VAT to the tax office there. Next, you will learn how to save VAT rates.

[TIP]
.VAT rates in Germany
====
Sellers in Germany can get by with two tax rates: +
A: Standard tax rate: 19% +
B: Reduced tax rate: 7%
====

[#60]
=== Saving VAT rates for countries of delivery

Proceed as described below to save VAT rates for the countries of delivery.

[.instruction]
Saving VAT rates:

. Go to **System » Client » Select client » Locations » Select location » Accounting » Tab: VAT rates**.
. Click on **New configuration**.
. Pay attention to the explanations given in table 3 and carry out the settings as desired.
. **Save** the settings. +
→ The configuration will be sorted into the directory tree on the left and it will be opened.

[cols="1,3"]
|====
|Setting
|Explanation

|**Country**
|Use the drop-down list to select which country of delivery VAT rates should be saved for. +
The menu only contains those countries that were set to **Active** under link::/[**System » Orders » Shipping » Settings » Tab: Countries of delivery**].

|**Tax rate A to D in %**
|Enter the VAT rates for the country in percent. The text fields **Name** are only relevant for the accounting software <<order-processing/orders/_accounting#150, **Xero**>>.

|**Margin scheme**
|Specify which tax rate is to be used for stock units to which the margin scheme applies on invoices. If no tax rate is selected, then stock units that the margin scheme applies to can not be displayed on invoices (= basic setting). The margin scheme setting in plentymarkets is an older customized implementation. The tax rate will be applied to the entire amount of the stock units that the margin scheme applies to. In other words the tax rate will not be applied to the difference between sales price and purchase price.

|**VAT number**
|Enter the country-specific VAT number assuming that you have such an ID. +
The standard VAT number is saved in the <<basics/first-steps/master-data#, **System » Settings » Master data**>> menu. This standard VAT number is used if you do not save a country-specific VAT number in the tab **VAT rates**.

|**Valid from**
|Select the date in the calendar. The VAT rates will go into effect on this date. +
**__Important:__** If you enter the date manually, then make sure to enter four digits for the year. Errors may occur if you only enter two digits for the year, e.g. 14 instead of 2014.

|**For digital items only**
|Place a check mark if the VAT rate should only apply to digital items. Pay attention to the explanations given in the following section.
|====

__Table 3: tab: **VAT rates**__

[#70]
=== VAT for digital items

The buyer's VAT rate must be used for digital items. An EU regulation puts these VAT rates into effect starting January 1st, 2015. If a VAT rate is already available for a country of delivery, e.g. because the delivery threshold was exceeded, then it is not necessary to create an additional VAT rate for digital items only. The existing VAT rate will be used. If no VAT rate is set up for one or more countries of delivery, then set up your accounting procedures in plentymarkets as described below. +
The EU regulation applies to B2C revenues. B2B revenue without VAT is not affected.

[.instruction]
Identifying the VAT for digital items:

. Go to **System » Client » Select client » Locations » Select location » Accounting » Tab: VAT rates**.
. Create a **VAT rate** for every country of delivery where the digital items are sold.
. Open the VAT rate and place a check mark next to the option **For digital items only**.
. Create a link::/[**property**] for digital items and give it a name, e.g. **Digital**. The property may not be an order property.
. Go to **System » Item » Settings** and select the property for the option **Item property for identifying digital items**.
. Open every item that should be sold as digital media and save the property in the **<<item/managing-items#480, Properties>>**  tab.

[#80]
=== Saving multiple VAT rates per country

Save an additional VAT rate for a country of delivery if needed. This can be necessary if the laws change in a specific country. For example, if a country's standard tax rate changes from 19% to 20% on January 1st, 2016, then create new VAT rates for this country. To do this, proceed as described above. In our example, you would enter the date 01.01.2016 under **Valid from**. The old tax rate would no longer be applied to new orders starting on this date.

[IMPORTANT]
.Do not delete old VAT rates
====
The date when an order is received determines which VAT rates will be applied. The old tax rate will be applied to all orders that are received before the date that was entered. Therefore, do not delete the old tax rate from the system.
====

[#90]
== Tab: Accounts

Save **posting keys**, **debtor accounts** and **revenue accounts** in the **Accounts** tab.

Debtor accounts are ledger accounts that are used in double-entry bookkeeping and in accounting software. The debtor accounts that are saved make it possible to export data in **link:http://www.datev.de[DATEV^]**/link:http://www.collmex.de[**COLLMEX**^] format. In the customer master data, an individual debtor account (debtor = borrower) can be saved for every customer in plentymarkets. However, defining individual accounts per customer is generally not desired, especially in B2C business transactions. Therefore, plentymarkets can automatically assign debtor accounts according to various rules. These rules are explained below. Before deciding how you would like debtor accounts to be assigned, you should first enter a standard debtor account. This account will then be used when there was neither an account saved for the customer, nor could an account be identified by an automatic procedure.

An individual **revenue account** can be saved for each item in plentymarkets. If this is not done, then plentymarkets will automatically determine a revenue account based on the VAT rate.

[IMPORTANT]
.Have the settings checked by experts
====
The following settings should be clarified with your financial accounting or your tax office.
====

[.instruction]
Carrying out settings in the Accounts tab:

. Go to **System » Client » Select client » Locations » Select location » Accounting » Tab: Accounts**.
. Pay attention to the explanations given in the following table and carry out the settings as desired.
. *Save* the settings.

[cols="1,3"]
|====
|Setting
|Explanation

|
|Tab: Posting key

|**Tax rate A / B / C / D**
|Enter one posting key per tax rate. +
The **posting keys** will be released upon data export and identify the VAT rate. If the invoice is to be issued as gross, then these posting keys will be assigned. The posting keys are: +
Net invoices: **0** +
DATEV standard posting key for **19%** VAT: **3** +
DATEV standard posting key for **7%** VAT: **2** +
plentymarkets automatically determines whether it is dealing with a debit (D) or credit (C) posting. The data export includes a distinct column (debit-credit) for this purpose.

|
|Tab: Debtor accounts » Tab: Basic settings

|**Standard debtor account**
|Save a standard debtor account, which you would like to use if no account was defined for the customer data record or for the procedure that you selected. +
__**Important:**__ If entries or values are missing, then plentymarkets will always export the standard debtor account. If a debtor account has been saved for a customer, then this account will always be exported. +
The debtor account will be saved in the customer data as soon as it has been identified for the first time. Therefore, at least one sales export has to be carried out that displays the debtor accounts, e.g. DATEV or COLLMEX.

|**Save debtor account in the customer master data record**
|Place a check mark to save a debtor account in the customer's master data. This is assuming that no debtor account was already saved there. The debtor account will be saved according to the option that is selected for the **automatic assignment of debtor accounts**. +
If no debtor account is saved for the selected process, then the standard debtor account will be used.

|**Automatic assignment of debtor accounts based on**
|Use the drop-down list to select which process should be used to assign the debtor accounts. +
**Option: Initial letter** +
The customer data for **company**, **surname** and **first name** will be searched by their initial letter in the order that was selected in the drop-down list. A **debtor account** will then be assigned. +
**__Example:__** The order **Company, surname, first name** was selected. If the company name begins with the letter B and the surname begins with the letter D, then the B debtor account will be used. If no company name is entered, then the surname beginning with the letter D will be found and the D debtor account will be used. +
**__Note:__** Consult with your financial accounting department or your tax office when deciding which process to use.

|**Initial letters (A - Z or 0 - 9 Debtor account)**
|Save debtor accounts depending on the **initial letter**.

|**Countries of delivery**
|Save debtor accounts for the countries of delivery saved in your system.

|**Payment methods**
|Save debtor accounts for the payment methods saved in your system.

|
|Tab: Revenue accounts

|**Standard revenue account**
|Define a standard revenue account for each VAT rate. This is used for the DATEV/COLLMEX export if no revenue account was saved in the set of item master data. If you have passed the delivery threshold for a country of delivery and you have applied for an individual tax number, then save the VAT rate for this country of delivery. Afterwards, individual revenue accounts can be defined for this country.

|
|Tab: Revenue exempt from VAT

|**Revenue from EU**
|Save a debtor account for revenue that is exempt from VAT and comes from the EU.

|**Revenue from export**
|Save a debtor account for revenue that is exempt from VAT and comes from export in countries outside of the EU.
|====

__Table 4: **accounts** tab; options__

[#100]
== Copying settings to other locations

Use the **Copy settings** function to copy the settings of the current location and apply these settings to one or more other locations. You can copy all of the settings or only specific settings.

The following settings can be copied:

* **Basic settings**
* **VAT rates**
* **Accounts**

Proceed as described below to copy settings to one or more locations.

[.instruction]
Copying settings to one or more locations:

. Go to **System » Client » Select client » Locations » Select location » Accounting**. Select the location that includes the settings you want to transfer.
. Click on the **gear-wheel icon**.
. Under **Location**, select one or more locations that the settings should be applied to (place check marks).
. Under **Options**, select the settings that should be copied (place check marks).
. Click on **Copy**. +
→ The settings will be applied to the locations.

== Delivery thresholds of EU countries of delivery

If an item is shipped from one EU member state to another by the seller himself or an independent third party, then this is called intra-community shipping. Examples of independent third parties are shipping service providers, forwarders or express mail services.

Taxes only have to be paid in the company's home country as long as certain delivery thresholds are not exceeded. This means that the company's shipments to another member state may not exceed a particular monetary amount during the calendar year. The relevant delivery threshold is always the one determined by the EU member states to which the shipping goes.

As soon as the delivery threshold of a country was exceeded, VAT has to be paid to that country. In this case, you would need a tax number in the country and you would need to save the country's tax rates in plentymarkets. The tax rates of this country have to be used for creating the invoice. Therefore, it is possible to enter individual tax rates for the countries where the delivery threshold has been exceeded in plentymarkets. This can be done in the VAT rates tab.

The EU member states have decided on the following delivery thresholds (as of: March 2014):

[cols="1,3,3"]
|====
|Member state |Delivery threshold for +
shipments |Amount in Euro

|**Belgium**
|35,000 EUR
|

|**Bulgaria**
|70,000 BGN
|35,850 EUR

|**Denmark**
|280,000 DKK
|37,617 EUR

|**Germany**
|100,000 EUR
|

|**Estonia**
|35,000 EUR
|

|**Finland**
|35,000 EUR
|

|**France**
|100,000 EUR
|

|**Greece**
|35,000 EUR

|

|**Ireland**
|35,000 EUR
|

|**Italy**
|35,000 EUR
|

|**Latvia**
|35,000 EUR
|

|**Lithuania**
|125,000 LTL
|36,200 EUR

|**Luxembourg**
|100,000 EUR
|

|**Malta**
|35,000 EUR
|

|**Netherlands**
|100,000 EUR
|

|**Austria**
|35,000 EUR
|

|**Poland**
|160,000 PLN
|38,275 EUR

|**Portugal**
|35,000 EUR
|

|**Romania**
|118,000 RON
|26,727 EUR

|**Sweden**
|320,000 SEK
|35,287 EUR

|**Slovakia**
|35,000 EUR
|

|**Slovenia**
|35,000 EUR
|

|**Spain**
|35,000 EUR
|

|**Czech Republic**
|1,140,000 CZK
|41,484 EUR

|**Hungary**
|8,800,000 HUF
|28,306 EUR

|**United +
Kingdom**
|70,000 GBP
|90,054 EUR

|**Cyprus**
|35,000 EUR
|
|====

__Table 5: delivery thresholds in the EU__

Check the delivery thresholds listed above regularly to make sure that they are still accurate. If you work with monetary values in your own currency, then make sure that you also use the correct conversion rates. The specified values were calculated with a conversion rate at the start of October 2014. Contact your chamber of commerce for current information about the delivery thresholds.

[TIP]
.Tip: Information from the German Federal Central Tax Office
====
For Germany, the link:http://www.bzst.de/EN/Steuern_International/Vorsteuerverguetung/02_Unternehmer_Ausland_EU/FAQ/FAQ_node.html;jsessionid=1318FB4ECBD85DED174407DD1AEAC4D8[**Federal Central Tax Office**^] provides tax information about the European countries of delivery as well as the USA and Japan.
====

== Data export

plentymarkets makes it possible to transfer all postings from invoices of outgoing items and from credit notes to a DATEV compliant accounting program (DATEV interface). In order to keep the rest of the processing as simple and efficient as possible, plentymarkets directly assigns the desired booking keys, debtor accounts and revenue accounts. The settings saved under **System » Client » Select client » Locations » Select location » Accounting » Tab: Accounts** form the basis for this.

Carry out different link::/[**data exports**] after all accounts and posting keys have been saved. To do this, go to **Data exchange » Data export**.

We have tested the following financial accounting solutions to make sure that they can process the operations:

* DATEV iRechnungswesen compact link:http://www.datev.de/[http://www.datev.de/]
* Lexware buchhalter pro link:http://www.lexware.de[http://www.lexware.de/]
* Büro Plus NexT link:http://microtech.de/index.php?id=produkte[http://microtech.de/]
* syska EURO FIBU link:http://syska.de/[http://syska.de/]
* COLLMEX link:http://www.collmex.de/[http://www.collmex.de/]
