= Basic settings
:lang: en
include::{includedir}/_header.adoc[]
:position: 10

Use the *System » Orders » Settings* menu to choose which settings should automatically be set for orders and applied under certain conditions and statuses. For example, define the standard settings for the referrer and the status of orders.

[#100]
== Important prerequisites

Standard values are selected by default in new systems. For example, these are status [9] for returns and status [11] for credit notes. These settings can be changed by selecting a different status. Alternatively, go to *<<order-processing/orders/managing-sales-orders#order-status, System » Orders » Order status>>* and create a new status. Statuses that are created there are displayed in the *Basic settings* menu and can be selected as standard statuses.

[IMPORTANT]
.Saving the basic settings
====
The basic settings in the *System » Orders » Settings* menu have to be saved once when the system is first set up. The settings will not go into effect until they have been saved. Thus, save the settings even if you have not made any changes, i.e. even if you want to use the default configuration.
====

[WARNING]
.Important: User login
====
Whenever you carry out changes in this menu and save them, other users will be logged out automatically and will need to log in again. This ensures that the changes will also apply to the other user profiles. Therefore, it is recommended that you announce changes in advance.
====

[#200]
== Carrying out basic settings

To carry out the basic settings, proceed as described below.

[.instruction]
Carrying out basic settings:

. Go to *System » Orders » Settings*.
. Carry out the settings according to <<table-orders-basic-settings>>.
. *Save* the settings.

[[table-orders-basic-settings]]
.Options in the *System » Orders » Settings* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Default referrer*
|Select a provider, a market or the *online store*. This referrer will automatically be set by default for all orders. Select *Manual entry* if you do not want to use a default setting, i.e. if you want to individually save each order referrer.

|*Standard status for return*
|Select which status should automatically be set for *<<order-processing/orders/managing-orders#400, returns>>*. The status can be changed when creating the return.

|*Standard status for credit note*
|Select which status should automatically be set for *<<order-processing/orders/managing-orders#500, credit notes>>*.

|*Standard status for repairs*
|Select which status should automatically be set for *<<order-processing/orders/managing-orders#500, repairs>>*.

|*Standard status for multi-invoice*
|Select which status should automatically be set for *<<order-processing/orders/managing-orders#800, multi-invoices>>*.

|**Standard status for multi credit note*
|Select which status should automatically be set for *<<order-processing/orders/managing-orders#540, multi credit notes>>*.

|*Standard status for reversal*
|Select which status should automatically be set for reversals.For example, a user-defined status *[6.4] Outgoing items canceled*. +
Select the setting *Last status* if you do not need a specific status. This setting returns the status to whatever it was before the outgoing items were booked.

|*Status of canceled orders*
|Select the status range for canceled orders. +
__**Background**__: As soon as an order enters this status range, stock will no longer be reserved for the items included in the order. In other words, the stock will become available again for other orders. Statuses can be excluded from this automatic function if necessary. For example, if you don't want items to be reversed if they have a particular status. +
__**Important**__: Save the range of statuses in ascending order, e.g. [8.0] to [8.5].

|*Status for order reservation*
|As soon as an order reaches this status, stock will automatically be reserved for the items included in the order. You can set a status up to and including status [6.9]. You can also choose whether the setting should apply to all orders or to paid orders only. For example, select the option *Paid orders only* if you do not want stock to be reserved for unpaid orders.

|*Include the shipping costs in the warranty*
|*YES* = The customer will receive a refund for the shipping costs. +
*NO* = The customer is required to pay the shipping costs even in case of a warranty. The shipping costs will not be refunded.

|*Show in the order/order overview*
|Select whether the *invoice address* or the *delivery address* should be displayed in the order overview.

|*Display of item prices*
|Select whether *gross* or *net* prices should be displayed in the order.

|*Assignment of warehouses*
|Select the warehouse assignment. +
*a) a warehouse can be assigned for each order* = Select this option if you only work with one warehouse or logistics service provider. +
*b) a warehouse can be assigned for each stock unit* = Select this option if you work with multiple warehouses or logistics service providers.

|*Automatic warehouse selection*
|Choose which criterion should be used to select the warehouse. +
*a) depending on the country of delivery* = The warehouse that was saved for the *country of delivery* in the menu *System » Orders » Shipping » Settings » Tab: Countries of delivery*. +
__**Tip:**__ If you select this option, then be sure to check which warehouse is assigned to each country of delivery. +
*b) depending on the item's main warehouse* = The warehouse that was saved as the particular item's main warehouse will be selected. +
__**Important**__: If an item does not have a main warehouse, then the warehouse is selected according to the country of delivery. +
*c) depending on the stock level* = The order will be assigned to the warehouse with the highest stock for the stock unit. +
*d) depending on the warehouse priority and the stock level* = The order will be assigned to a warehouse according to the following criteria. The following information is checked: +
1) Sufficient stock has to be available. +
2) According to the *priority* of the warehouse (option among the warehouse settings). +
In case of sufficient or identical stock in all warehouses, the warehouse will be selected according to priority. The first criterion does not consider the actual amount of stock. Rather, it checks whether enough stock is available or not. Thus, a warehouse is not favored because it has more stock than another but rather because it has a higher priority. Conversely, if a warehouse does not have sufficient stock, then it will not be chosen.

|*Deposit payment on production items*
|Select a value (in percent) for the deposit or select the option *do not offer deposit*.

|*Status changes to 4 instead of 5 if stock is missing*
|Set this option to *Yes* if an order should only be cleared for shipping when there is enough stock in the warehouse. As soon as enough stock was booked, the *<<order-processing/orders/managing-orders#1200, order status>>* changes from *[4]* to *[5]*. +
*Status [4]* = In preparation for shipping +
*Status [5]* = Cleared for shipping

|*Affected status section in status [4.x]*
|You can place limits on the scope of the status if you have created your own variations of status 4. +
Default setting: from *[4] In preparation for shipping* to *[4] In preparation for shipping*.

|*Status [3.2] is also affected*
|*Status [3.2]* indicates that the item is in a waiting position because of partial payment. If a partial payment was made, then the order will automatically be given this status instead of status 4. If the item is in stock, then the order will switch again to status 3.3. +
*Status [3.2]* = In waiting position
|====

[#300]
== Authorising variable users to edit orders

To authosise variable users to open orders, you need to save default statuses for *returns* and *credit notes* here. +
Variable users also need to be given the right to edit orders. Go to *System » Settings » User » Accounts* and open the particular user account. Then click on *<<order-processing/orders/basic-settings#90, Tab: Right » Tab: Menu » Area: Orders>>*.
Furthermore, variable users can only create *returns*, *warranties* and *repairs* if they are also authorized to work with the standard statuses that are saved for these types of orders under *System » Orders » Settings*. Variable users are given the right to work with statuses in the *<<basics/working-with-plentymarkets/manage-users#90, Tab: Visibility>>* in their user profile.



////
== Warehouse options

=== Warehouses in relation to orders and items

In this menu, you will find different basic settings for the configuration of your **link::/[warehouse(s)]** with regards to their assignment to orders or items. Pay attention to the warehouse configurations as well as any links that are set up between countries of deliveries and warehouses. Go to **link::/[System » Stock » Warehouse » Settings]** to configure the settings.

=== Carrying out basic settings for warehouses based on orders or items

Depending on how you configure your plentymarkets system, it is possible to create a variety of useful combinations that prevent errors from occurring. Conversely, incorrect settings can cause mistakes. For example, you would notice a mistake if you selected a main warehouse for an item but this warehouse didn't appear on the order. Such a situation could be the result of the automatic warehouse selection that is based on the country of delivery. The mistake could be that one warehouse was automatically assigned based on the country of delivery, but you actually wanted a different warehouse to be assigned based on the particular item. The situation would be even worse if you didn't save any stock for this particular warehouse. Therefore, these basic settings are very important for ensuring that you can correctly process your orders. Pay attention to any links that exist between the warehouse configuration, the settings that are saved for particular items, the countries of delivery and the basic settings in table 1.

=== Configuration tips

Different settings are offered depending on how many logistic service providers you (would like to) work with.

==== Variation 1 - one warehouse/logistics service provider

Carry out the following settings if you are working with only one warehouse/logistics service provider:

* **Assignment of warehouses** = a) a warehouse can be assigned for each order
* **Automatic warehouse selection** = a) depending on the country of delivery

The whole order is transferred to the logistics service provider, including the stock units that are stored and managed somewhere else.

==== Variation 2 - multiple warehouses/logistics service providers

We recommend that you carry out the following settings if you are working with several warehouses or logistics service providers:

* **Assignment of warehouses** = b) a warehouse can be assigned for each stock unit
* **Automatic warehouse selection** = b) depending on the item's main warehouse

When you receive an order including items from two or more warehouses, only the part of the order that is relevant to this particular warehouse will be transferred to the logistics service provider, not the whole order. Our **<<order-processing/orders/managing-sales-orders#delivery-order, delivery orders>>** feature can be used for this scenario.
////
