= Managing orders
:lang: en
include::{includedir}/_header.adoc[]
:position: 20
:url: orders/managing-orders
:id: 1HDXOGT
:keywords: Order processing, order, orders, order status, order types, delivery order, delivery orders, manual order, contact overview, customer overview, return order, returns, credit note, credit notes, warranty, warranties, repair, repairs, multi-order, multi-orders, scheduler, advance order, order filter, order search, order overview, editing an order, editing orders

Orders depict your sales and the business transactions connected to them. Those different business transactions are represented by order types. Progress during order processing is made visible by order status. The following descriptions will show you how to use order types and order status and thus process orders efficiently. All orders are registered in one central menu and in the same format. The <<orders/managing-orders#1400, order overview>> provides you with access to all important information and enables you to edit orders.

[#100]
== General information on creating orders in plentymarkets

In plentymarkets, an order is automatically created when customers place orders in your online store or on one of your implemented markets. Separate orders with different order types are created for business transactions such as <<orders/managing-order#300, delivery orders>>, <<orders/managing-order#400, returns>>, <<orders/managing-order#500, credit notes>>, <<orders/managing-order#600, warranties>> and <<orders/managing-order#700, repairs>>.  These orders are always linked to the main orders. The  <<orders/managing-order#1400, order overview>> allows you to open and edit orders regardless of the  <<orders/order-referrer#, referrer>>. For many order types, such as <<orders/managing-order#300, delivery orders>>, it makes sense to set up<<automation/event-procedures#, event procedures>> that allow you to automate part of your order processing. You will find some examples for using event procedures during order processing in the following chapters. +
Orders that were not generated in the online store or on a market can be created <<orders/managing-orders#200, manually>> in your system. This can be the required for orders via telephone, email or cash sales.

[NOTE]
.Saving the basic settings
====
Before processing the first orders in your plentymarkets system, adjust the settings in the menu *<<orders/basic-settings#, Setup » Orders » Settings>>*. *Save* (icon:save[role="green"]) those settings once even if you have not changed the default values.
====

[#200]
== Creating orders manually

The following options are available to manually create orders:

* in the *contact overview*
* in the *customer account*
* from an existing *order*
* from a *cash sale*

These options are described below.

[IMPORTANT]
.Emailing
====
When you manually create orders no emails will automatically be sent to the customer. The reason that no emails will be sent is that your system does not know when you are done with all settings for an manual order. To send emails for a manual order you need to open the *<<orders/managing-orders#1550, Email>>* tab and send the emails individually.
====

[#220]
=== Creating an order in the contact overview

The description below shows you how to create an order via the *CRM » Contacts* menu.

[.instruction]
Creating a new order via the contact overview:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that match the search criteria are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *New order* in the context menu. +
→ The *New order* tab opens.
. Click on *Search* to display a list of variations or use the search fields to search (icon:search[role="blue"]) for the *Item ID* or other *Item data*.
. Select the items and the quantities that you want to add to the order.
. *Save* (icon:save[role="green"]) the settings. +
→ The order is created and opens in a new tab.

[#230]
=== Creating an order from an existing order

When you open an individual order the *overview* tab opens and here you can find the *New order* icon. The description below explains how to create an order from an existing order.

[.instruction]
Creating an order from an existing order:

. Go to *Orders » Edit orders*. +
→ The empty *order overview* opens.
. Search for the appropriate orders.
. Click on an order from the customer that you need to create another order for. +
→ The order opens and the *overview* tab is displayed.
. Click on *New order* (icon:plus-square[role="green"]) within the *customer data* section to create an order for this customer. +
→ The *New order* tab opens.
. Click on *Search* (icon:search[role="blue"]) to display a list of variations or use the search fields to search for the *Item ID* or other *Item data*.
. Select the items and the quantities that you want to add to the order.
. Save (icon:save[role="green"]) the settings. +
→ The order is created and opens in a new tab.

[#240]
=== Creating an order for a cash sale

When you open the *CRM » Customer* menu you can register cash sales without assigning them to a specific customer. Instead there is a default customer profile called *cash sale* that you can assign in such a case. This profile is available by default in your plentymarkets system.

[WARNING]
.Payment method and order documents for cash sale
====
Make sure to select the right *payment method* when you create an order for a cash sale. When manually creating a cash sale order the order will not be assigned to a customer. This is why you should manually create *<<order/order-documents#, Order documents>>* such as the invoice right away while entering and processing the cash sale. Order documents can be created in the *Receipts* tab of the order.
====

[.instruction]
Creating a new cash sale order:

. Go to *CRM » Contacts*.
. Enter 100 into the *ID* search field. +
→ A list of all search results is displayed.
. Select *Cash sale* from the *results*. +
→ The customer profile for cash sale opens. This profile has the ID *100*.
. Click on *New order* to create a cash sale order. +
→ The *New order* tab opens.
. Click on *Search* (icon:search[role="blue"])to display a list of variations or use the search fields to search for the *Item ID* or other *Item data*.
. Select the items and the quantities that you want to add to the order.
. Save (icon:save[role="green"]) the settings. +
→ The order is created and opens in a new tab.

[#300]
== Working with delivery orders

*Delivery orders* enable you to create multiple delivery orders for the items included in the main order. This way, items from the main order can be shipped individually or in parts. Thus, delivery orders allow you to immediately ship items that are in stock and ship unavailable items later. Delivery orders can be shipped using one or several shipping providers. +
You can create delivery orders *manually*,  *automatically* or using an *event procedure*. +

[IMPORTANT]
.Same order status
====
The status of the main order is always identical to the status of the delivery order with the lowest status.
For example, if a main order with the status *5.0* has two delivery orders, of which one changes to status *6.5*, the status of the main order is not changed to *6.5* until the second delivery order has also moved to status 6.5.
====

[#310]
=== Characteristics of delivery orders

In general, delivery orders have the following characteristics:

* It is *not* possible to modify the order items included in a delivery order after the delivery order has been created.
* The *price* and *weight* of an order are taken from the main order.
* *Address label*, *delivery note*, *pro forma invoice* and *entry certificate (Gelangensbestätigung)* can be created in the *Receipts* tab of the respective order.
* The *invoice* and all other documents are created centrally in the main order.
* When creating a delivery order, the stock reservation for the quantity included in the delivery order is transferred from the main order to the delivery order.

[#320]
=== Carrying out basic settings for delivery orders

[WARNING]
.Assigning a warehouse for each order item
====
To use delivery orders, you have to select the option *b) a warehouse can be assigned for each stock unit* for the *Assignment of warehouses* in the menu *Setup » Orders » Settings*.
====

Before working with delivery orders, go to *Setup »Orders »Order types » Delivery order* to select an option for splitting up main orders into delivery orders.

[instruction]
Selecting an option for splitting up orders into delivery orders:

. Go to *Setup » Orders » Order types » Delivery order*.
. Carry out the settings according to <<table-order-types-delivery-order-options>>.
. Save (icon:save[role="green"]) the settings.

[[table-order-types-delivery-order-options]]
.Options for splitting up orders into delivery orders:
[cols="1,3"]
|====
|Setting|Explanation

2+|*Split up orders into delivery orders by*

|*Off*
|Orders are not split up into delivery orders. +
*_Note_*: If this option is activated, delivery orders can only be created manually. Automatically creating delivery orders or using event procedures to create delivery orders is not possible with this setting.

|*Warehouse*
|The delivery orders are created according to the different *Warehouses* of the items included in the order.

|*Shipping profile*
|The delivery orders are created according to the different *Shipping profiles* of the items included in the main order.

|*Warehouse and shipping profile*
|The delivery orders are created according to the different *Warehouses and shipping profiles* of the items included in the main order.

|*Warehouse stock and net stock*
|The delivery orders are created according to the different *Warehouse stock and net stock* of the items included in the main order.
|====

[#330]
=== Manually creating delivery orders

If necessary, you can manually create delivery orders via the main order. When you do so, you need to select the item orders and quantities for each delivery order.

[NOTE]
.Always create delivery orders for all order items in the main order
====
We recommend to generally create delivery orders for *all* order items in the main order. If one or several items remain in the main order without being assigned to a delivery order, problems may be caused in your plentymarkets system.

In addition, the quantity you indicate for *DelOrdQua* (quantity to be transferred to the delivery order) must not exceed the quantity indicated for *Unass.Quantity* (unassigned quantity).
====

[.instruction]
Manually creating delivery orders:

. Go to *Orders » Edit orders*.
. Open the order for which delivery orders should be created.
. Open the *Delivery* tab.
. Enter the *Quantity* that should be transferred to the delivery order in the field *DelOrdQua* (quantity to be transferred to the delivery order).
. Click on the *gear-wheel icon* (icon:cog[]) to create the delivery order. +
→ The delivery order is created.
. Repeat the process to create further delivery orders.

[#340]
=== Automatically creating delivery orders

[IMPORTANT]
.Requirement for automatically creating delivery orders
====
This function can only be used if no delivery order has ben created for the main order yet.
====

When automatically creating delivery orders, the criteria for splitting up orders into delivery orders described in <<table-order-types-delivery-order-options>>. apply. Thus, the items and quantities to be included in the delivery orders to not have to be selected manually. Instead, the system applies the selected option and transfers the items and quantities from the main order to the delivery orders.

[.instruction]
Automatically creating delivery orders

. Go to *Orders » Edit orders*.
. Open the order for which delivery orders should be generated.
. Open the *Delivery* tab.
. Click on *Generate delivery orders automatically* (icon:cog[]). +
→ The delivery orders are created.

[#350]
=== Creating delivery orders with an event procedure

An ideal way to create delivery orders is using an event procedure. This way, you can determine when and how delivery orders are created from a main order. Below, three examples for creating delivery orders with an event procedure are described.

Set up one or all of the following event procedures and carry out the described settings.

==== Example A: Event procedure “Create delivery order when order is received”

Use the following settings if you want delivery orders to be generated as soon as a new order enters your plentymarkets system.

Since this event procedure comes into effect directly upon reception of a new order, the status of the main order is not taken into consideration. Thus, delivery orders will also be created for main orders that are in status *3.0* (or *1.0* if you work with auction platforms such as eBay) and will adopt the status of the main order.

:table-event-procedure: <<table-event-procedure-delivery-order-when-new-order>>
include::../_includes/textblocks/instructions/EA.adoc[]

[[table-event-procedure-delivery-order-when-new-order]]
.Options for the event procedure “Create delivery order when order is received”
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*New order*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Order warehouse*
|*Multiple warehouses per order*

|*Procedure*
|*Order > Generate delivery orders*
|

|====

==== Example B: Event Procedure “Create delivery order when order changes to status 5”

Use the following settings if you want delivery orders to be created as soon as an order changes to status 5.

When working with this event procedure, you must not male any changes to the main order at all. Otherwise, the total item quantities included in the delivery orders does not match the item quantity included in the main order.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The window *Create new event procedure* opens.
. Enter a distinct name for the event procedure.
. Select the *event* as listed in <<table-event-procedure-delivery-order-status-5>>.
. Save (icon:save[role="green"]) the settings.
. Carry out the settings as desired. Pay attention to the information provided in  <<table-event-procedure-delivery-order-status-5>>.
. Select the option *Active*.
. Save (icon:save[role="green"]) the settings.
--

[[table-event-procedure-delivery-order-status-5]]
.Options for the event procedure “Create delivery order when order changes to status 5”
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order change > Status change*
|*Cleared for shipping*

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Order warehouse*
|*Multiple warehouses per order*

|*Procedure*
|*Order > Generate delivery orders*
|

|====

==== Example C: Event procedure “Create delivery order when generating an invoice”

Use the following settings if you want delivery orders to be created as soon as an invoice is generated for the main order. +
This allows you to edit the main order as necessary until an invoice is created and the order is cleared for shipping. The following settings are required:

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The window *Create new event procedure* opens.
. Enter a distinct name for the event procedure.
. Select the event as listed in <<table-event-procedure-invoice-generated>>.
. Save (icon:save[role="green"]) the settings.
. Carry out the settings as desired. Pay attention to the information provided in <<table-event-procedure-invoice-generated>>.
. Select the option *Active*.
. Save (icon:save[role="green"]) the settings.
--

[[table-event-procedure-invoice-generated]]
.Options for the event procedure “Create delivery order when generating an invoice”
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Documents > Invoice generated*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Order warehouse*
|*Multiple warehouses per order*

|*Procedure*
|*Order > Generate delivery orders*
|

|====

[#360]
=== Editing main orders and delivery orders

[NOTE]
.User rights required for opening main orders
====
To open main orders, variable users have to be *<<basics/admin-tasks/manage-users#100, authorised>>* to view all warehouses linked to the delivery orders of the main order. Check the settings in the menu  *Setup» Settings » User »Accounts » Tab: Visibility* for this.
====

If you want to delete a main order, the respective delivery orders have to be deleted first. Delivery orders can be deleted individually or with the group function in the order search. The main order can only be deleted after this is done.

Further order items can be added or deleted from the main order. However, you can only delete order items from the main order if they are not included in the delivery orders. Thus, you can increase or reduce the item quantity included in the main order. Make sure to only delete quantities that are not assigned to delivery orders.

[WARNING]
.Deleting order items of a delivery order
====
It is technically possible to delete order items that are already included in a delivery order. But you should avoid this in order to prevent errors.
====

[#400]
== Working with return orders

The order type return depicts the business transaction of receiving returned goods. You and your staff can create return orders manually. In addition, you can allow customers in your online store to register returns in the *My account* area. Registering the return does not book the returned items back into your stock. First, you register the returned items and then you decide whether they should be booked back into the stock or if further steps, for example a repair, are necessary. Return orders are subordinated orders because they are always linked to a main order or a warranty.
Before returns can be registered in your system, you have to set up reasons for returns and item statuses for returned items.

[NOTE]
.Changing the default status for returns
====
The default status for returns is status 9. Every registered return is automatically assigned this status. However, you can change the default status according to your requirements in the menu *Setup » Orders » Settings* by selecting another *<<orders/basic-settings#, default status>>* for returns.
====

[#410]
=== Old online store: Creating reasons for returns

In plentymarkets, you can create up to 20 reasons for returns. When registering returns, you can choose a reason for each returned item. Reasons for returns can help you later to determine whether an item was frequently returned for the same reason.

[.instruction]
Creating reasons for returns:

. Go to the menu *Setup » Orders » Order types » Return*.
. Enter reasons for returns.
. *Save* (icon:save[role=”green”] the settings.

If you allow customers to *<<online-store/setting-up-ceres/#160, register returns themselves>>* in the My account area of the Callisto online store, the return reasons will be displayed as a list for the customers to choose from. If the customer does not select any of the return reasons, the first reason for return will be selected by default.

[#420]
=== Creating statuses for returned items

You can create up to 12 statuses for returned items. You can use these statuses, for example, to display the state of the returned items or the progress of the return process The item statuses are available in the *Overview* tab in a return order. Create the necessary statuses according to your requirements to depict the progress.

[.instruction]
Creating statuses for returned items:

. Go to the menu *Setup » Orders » Order types » Return*.
. Enter the *statuses* that should be assigned to returned items.
. Save (icon:save[role="green"]) the settings.

[#440]
=== Creating and editing returns

You can either manually create a return once you receive the returned goods or you can allow your customers to register returns directly in the My account are of the online store. After a return has been registered, more options for editing become available. For example, the status of the returned items can only be entered after registration.

==== Creating a return

[.instruction]
Creating a return:

. Go to *Orders » Edit orders*.
. Open the order or the warranty for which the return is to be created.
. In the table-settings-return  Overview tab, click on *Return* and select the option *create*. +
→ A window for creating the return opens.
. Carry out the settings according to <<table-settings-return>>.
. Save (icon:save[role="green"]) the settings. +
→ The return is created and opens in a new tab.

[[table-settings-return]]
.Options for creating a return
[cols="1,3"]
|====
|Setting |Explanation

2+|*Settings*

|*Status*
|Select a status for the return. The status defined in the menu *Setup » Orders » Settings* is displayed here by default.

|*Owner*
|Select an owner to be assigned to the return.

|*Package code of the return*
|Enter the package code of the return delivery.

2+|*Item*

|*Transfer return reason*
|Select a reason for return to be applied to all returned items. +
If a reason is selected here, it has priority over all reasons for returns assigned to individual items.

|*Accept*
|Select the items to be included in the return.

|*Quantity*
|Select the item quantity to be included in the return.

|*Reason for return*
|Select an individual reason for return from the drop-down menu. +
*_Note_*: If a reason is selected, it has priority.

|*Item*
|Change the item name, if necessary.
|====

After having created a return, you can select an item status in the Stock units tab of the return. In addition, more editing options become available.

[#450]
=== Creating a return slip

You can include a return slip in every shipment of items sent to your customers. In this case, the return slip should contain blank fields for the reasons of return. Alternatively, you can allow your customers to fill out the return slip in the *My account* area of the online store and to print it after having filled in the reasons for the return. The return slip can then be included in the return delivery.
Before creating return slips, the document template *Return slip* has to be set up in the menu  *Setup » Client » Select client » Locations » Select location » Documents » Return label*.

[TIP]
.Displaying reasons for returns on the document template
====
To include a blank return slip in every shipment regardless whether items will be returned or not, create a return slip directly in the main order.  You can also allow your customers to register returns and select reasons for those returns in the My account area of the online store. Your customer can then print the filled in return slip. No matter which of these options you use: in order to be able to insert reasons for a return, the column including those reasons has to be placed below the list of items.
====

Check the list of returned items and change data if necessary, for example the quantities, *before* creating a return slip in the *Receipts* tab of the return order.

[.instruction]
Creating a return slip manually:

. Open the return order and then the *Receipts* tab.
. Select the option *Return label* from the drop-down list *Create receipt*. +
→ A new window opens.
. Carry out the settings for the return slip.
. *Save* the settings to create the return slip.

[TIP]
.Generating a return slip automatically
====
Set up an event procedure that automatically generates return slips. If you select  the event *New return (by customer)* and the filter *Client (store)*, blank return slips are generated with each incoming return and only have to be provided for downloading.
====

[#460]
=== Reversing stock

Once returned items reach you, you can partly or completely reverse the stock. Alternatively, it is also possible to completely reset the outgoing items that have been booked while processing the main order.

[.instruction]
Reversing stock:

. Go to *Orders » Edit orders*.
. Select the option *Return* from the filter called *type*.
. Click on *Search* (icon:search[role="blue"]). +
→ The return orders are listed.
. Open the return for which you want to reverse stock.
. Open the *Settings* tab.
. Click on *Add items to stock* next to the option *Stock*. +
→ A window for editing opens.
. Carry out the settings according to <<table-reversing-stock-return>>.
. *Save* (icon:search[role="blue"]) the settings.

[NOTE]
.Reversing stock for returns belonging to orders including delivery orders
====
The procedure for reversing stock of returns belonging to orders with delivery orders is the same. The window for editing the stock reversal also shows whether there are delivery orders.
====

[[table-reversing-stock-return]]
.Options for reversing stock
[cols="1,3"]
|====
|Setting |Explanation

|*Reset outgoing items completely*
|Resets outgoing items completely. The date on which the outgoing items were booked is deleted as well.

2+|*Reverse stock*

|*Select entire quantity*
|Transfers the entire quantity of items included in the order to the column *Reverse*.

|*Deselect entire quantity*
|Sets the item quantities in the column *Reversed* to 0.

|*Reverse*
|If items are only to be booked partly, manually enter the item quantities to be booked here.

|*Warehouse*
|Select the warehouse for the items.

|*Storage location*
|Select the storage location for the items.

|*Quantity in the order*
|Displays the item quantity of the order.

*Reversed*
|Displays already booked item quantities.

|*Batch*
|Displays the batch number of the item.

|*BBF*
|Displays the best before date.

|*ID*
|Displays the ID of the item.

|*Item*
| Displays the item name.
|====

[NOTE]
.Incoming items from returns
====
An overview of all incoming items for which returns have already been announced is available in the menu *<<stock-management/managing-reorders/managing-backlog-lists#400, Stock » Returns » Supply>>*.
====

[#500]
== Working with credit note orders

Credit note orders are used for reimbursing your customers, for example after a <<orders/managing-orders#400, return order>>.  A credit note in plentymarkets does not represent a reverse invoice but a refund. Credit note orders are created from an existing main order in the menu *Orders » Edit orders*. Thus, a credit note is always linked to a main order. The credit notes created in a credit note order are included in your financial accounting such as the *DATEV* export.

[#510]
=== Setting a default status for credit notes

Before creating credit note orders, check the default status for credit notes in the menu *<<orders/basic-settings#, Setup » Orders » Settings>>*. Change the default status when necessary and then save your settings.

[#520]
=== Creating a credit note order

A credit note order is always linked to an already existing order in your plentymarkets system. That is why you have to open the main order in the overview first, before creating a credit note order.

[TIP]
.Creating a credit note order in the main order or in a return order
====
If a customer has already paid for an order and then decides against the purchase before you have shipped the goods and booked outgoing items, we recommend creating a credit note including all order items in the main order and to cancel the original main order.

In case payment, outgoing items and delivery have already taken place and a <<orders/managing-orders#400, return order>> or a <<orders/managing-orders#700, repair>> is created, the credit note order is generated directly in the corresponding return order or repair.
====

[.instruction]
Opening an order:

. Go to *Orders » Edit orders*.
. Search (icon:search[role="blue"]) for the order.
. Open the order for which a credit note order should be created. +
→ The order opens in a separate tab.

OrderType Credit notes INSERT TABLE!

[.instruction]
Creating a credit note order:

. Open the *Overview* tab of the order for which a credit note order is to be created.
. Click on the  *Credit note* drop-down list.
. Select an option according to the explanations given in <<tabelle-{ordertype}-anlegen>>.  +
→ The credit note order is created and opened in a separate window.

include::./_textblocks/tables/tabelle-aus-optionen-anlegen.adoc[]

If a credit note order already exists for an order, there will be a note on the right-hand side of the *Overview* tab notifying you that there is a *Credit note available*. In addition, the credit note order is linked in the  *Overview* tab and can be found by using the *Credit note / search*  drop-down list.

[#530]
=== Generating a credit note

[NOTE]
.Setting up a document template
====
Before generating credit notes, you have to set up the *<<orders/order-documents/generating-credit-notes#, document template for credit notes>>*. This is done in the menu *<<orders/order-documents#, Orders » Fulfillment>>*.
====

After creating a credit note order, a credit note has to be created directly in the credit note order. Check the items included in the credit note order and, when necessary, carry out changes before creating the credit note in the *Receipts* tab of the credit note order.

[.instruction]
Generating a credit note:

. Open the credit note order for which a credit note is to be created.
. Select the option *Credit note* from the drop-down list Create receipt.
. Click on *Create receipt*. +
→ The credit note order is created and opened in a separate tab.

[#540]
=== Reversing and correcting a credit note

Once you have generated the credit note for a credit note order, the credit note order will be locked and can no longer be edited. The lock ensures that tax relevant information cannot be changed. If you discover an error in your credit note after the document was created and you wish to correct it, a *Reversal document refund* has to be generated.

==== Setting up a reversal document template

First set up a template for the reversal document. The fastest way to fill all required settings is to apply the settings from the default document template.  +
The following steps describe how to apply the settings from a default document template.

[.instruction]
Setting up a reversal document template:

. Go to *Setup » Client » Select client » Locations » Select location » Documents » Refund reversal*.
. Click on the *Transfer* tab.
. Click on *Accept* to *Apply the settings from default document template*.

Since the information in a reversal document is identical with the information included in an invoice, further information on the required settings can be found on the *<<orders/order-documents/generating-an-invoice, invoice>>* manual page.

==== Correcting a credit note

Correct a credit note by generating a *refund reversal document* first. The reversal of a credit note allows you to make the required changes in the credit note order and a new credit note can be generated. Generating a reversal document does not cancel the credit note order itself.

[NOTE]
.Correcting a credit note:
====
The reversal of a credit note is used for a transparent correction of tax relevant data and *not* for the reversal of the credit note order itself.
====

[.instruction]
Correcting a credit note:

. Go to *Orders » Edit orders*.
. Open the order that contains the credit note you want to reverse.
. Click on the *Receipts* tab.
. Select the option *Refund reversal* from the *Create receipt* drop-down list. +
→ A new window with optional settings opens.
. *Save* (icon:save[role="green"]) the settings.  +
→ The reversal document is generated and the settings of the credit note order are unlocked.
. Edit the data.
. Click on the *Receipts* tab.
. Select the option *Credit note* from the *Create receipt* drop-down list.  +
→ A window with optional settings opens.
. *Save* (icon:save[role="green"]) the settings.  +
→ The reversal document is generated and the settings of the credit note order are locked again.

[#550]
=== Booking refunds

After creating a credit note, the refund of the credited amount has to be booked in your plentymarkets system. Refunds that are transferred via one of the payment providers you have integrated in your system are booked directly in the *Settings* tab of the credit note order. The *Refund to customer* option is only displayed for the payment methods *PayPal*, *ClickandBuy* and *heidelpay*.

[IMPORTANT]
.Requirements for PayPal
====
*PayPal* does not allow you to enter an amount higher than the amount paid for the original order.
====

[.instruction]
Booking a refund in the *Settings* tab:

. Go to *Orders » Edit orders*.
. Open the credit note for which you want to book a refund.
. Open the *Settings* tab.
. Click on the  *payment icon* next to the *Refund* option.
. Check the *Amount* of the refund and adjust it when necessary.
. Click on the *gearwheel* (icon:cog[]) to book the refund. +
→ The refund is booked.

The refund can also be booked in the *Payment* tab of the credit note order. Click on the *Payment* tab to see all payments and partial payments belonging to the order. Using this tab for booking a refund is necessary when the original order has not been paid with a payment provider integrated in your plentymarkets system.

[.instruction]
Booking a refund in the *Payment* tab:

. Go to *Orders » Edit orders*.
. Open the credit note for which you want to book a refund.
. Open the *Payment* tab.
. Click on the icon *Book payment*.
. Enter the *Amount* (Debit) and, if necessary, the *Currency* and the *Designated use*.
. Click on *Book payment*. +
→ The refund is booked and displayed in the *Payment* tab.

[#560]
=== Reversing stock

If outgoing items included in a main order have already been booked and have to be booked back into the warehouse, stock has to be reversed in the *Settings* tab of the credit note order.

[.instruction]
Reversing stock:

. Go to *Orders » Edit orders*.
. Open the credit note order for which you want to reverse stock.
. Open the *Settings* tab.
. Click on the reset link next to the option Outgoing items.
. A separate window opens. Select the required option as described in <<table-settings-reverse-stock>>.
. *Save* (icon:save[role="green"]the settings to carry out the process.

[[table-settings-reverse-stock]]
.Options for reversing stock for credit notes
[cols="1,3"]
|====
|Setting |Explanation

|*Reset outgoing items completely*
|Completely resets the outgoing items. This option also deletes the date of the outgoing items.

|*Reverse stock*
|In this section, items are completely or partially reversed. Outgoing items are *not* reset with this option.

|*Select entire quantity*
|Enters the complete quantity of items into the field *Reverse*.

|*Deselect entire quantity*
|Sets the item quantity listed under *Reverse* to 0.

|*Reverse*
|If reversal should only be carried out for a partial quantity, enter the item quantity that is to be reversed.

|*Warehouse*
|Select the warehouse for the items.

|*Storage location*
|Select the storage location for the items.

|*Quantity in the order*
|Displays the number of items included in the order.

|*Reversed*
|Displays the quantity of items already reversed.

|*Batch*
|Displays the batch number of the items included in the order.

|*BBF*
|Displays the best before date of the items included in the order.

|*ID*
|Displays the the item's ID.

|*Item*
|Displays the item name.
|====

[#600]
== Working with warranties

Warranties are quite similar to <<orders/managing-orders#400, returns>>. In both cases, the items of an order in *status 7* will be sent back to you.   In contrast to a return, customers expect a new delivery or a refund in the form of a <<orders/managing-orders#500, credit note>>.

[NOTE]
.Guarantee vs. Warranty
====
In contrast to a guarantee voluntarily provided by the seller, the warranty represents the *legal obligation* of the seller to eliminate defects and damages that already existed when the item was delivered to the customer free of charge. Depending on the characteristics of the items and the legislation that applies, customers can have a right to claim a warranty up to 2 or 3 years after the purchase of the item. If damages appear more than 6 months after the receipt of the items, the customer has to prove that they already existed upon delivery.
====

If the conditions for a warranty apply, you as the seller can decide whether to refund the customer’s costs or to exchange the damaged item with a new one. Create a *warranty* to replace the damaged item. For refunding the customer, create a refund in the *Overview* tab of the warranty. Go to *<<orders/basic-settings#, Setup » Orders » Settings>>* to determine whether the *shipping costs* should be covered in the warranty.

[TIP]
.Warranty settings
====
If you create a warranty directly within an order, the *shipping profile* of the main order is automatically adopted. However, the settings can be changed in the warranty’s editing window. For *delivery orders*, the correct warehouse is automatically selected as well. The *payment method* for a warranty can be changed.
====

[#610]
=== Creating a warranty

In general, a warranty is created out of a return order. However, it is also possible to create it out of the original main order.

[TIP]
.Creating a warranty in the main order or in the return order
====
We recommend creating the warranty directly in the main order if the customer finds fault with the ordered items after delivery and you decide against proceeding with a return order.

If you wish to proceed with a return order to examine the damaged items, create a return order first and create the warranty in the return order.
====

OrderType Warranties

[.instruction]
Creating a warranty:

. Go to *Orders » Edit orders*.
. Open the *return* or the original main *order* for which you want to create a warranty.
. Click on the  *Warranty* drop-down list.
. Select an option according to the explanations given in <<tabelle-{ordertype}-anlegen>>.
. Save (icon:save[role="green"]) the settings. +
→ The warranty is created and opens in a new tab.

include::./_textblocks/tables/tabelle-aus-optionen-anlegen.adoc[]

[#620]
=== Editing a warranty

Existing warranties are displayed in the overview. Open the warranty to enter an additional *price* if you decide to replace the damaged item by providing the customer with a similar but more expensive one. The quantities of the items included in the warranty can be changed here as well. Proceed as described below to edit a warranty.

[.instruction]
Editing a warranty

. Go to *Orders » Edit orders*.
. In the *Filter* tab, select the option *Warranty* as the *Type*.
. Click on *Search* (icon:search[role="blue"]). +
→ Only warranties are listed.
. Click on the warranty you want to edit. +
→ The warranty opens and can be edited in the *Edit* tab.


[#630]
=== Completing a warranty

In order to complete a warranty for which an additional charge is billed for the replacement, an invoice has to be created within the warranty. In case the customer agrees to a discount on the damaged item instead of proceeding with a return order, you have to create a credit note in the original main order.

Proceed as described below to complete a warranty by replacing items:

[.instruction]
Completing a warranty with a replacement:

. Click on the *Receipts* tab within the warranty.
. Select the option *Invoice* from the *Create receipt* drop-down list. +
→ A window for editing opens. Adjust the settings as needed. +
. Save (icon:save[role="green"]) the settings. +
→ The invoice is created and opened in a separate tab.
. Open the *Settings* tab.
. Click on the icon *Book outgoing items* in the row *Outgoing items.* +
→ The outgoing items are booked and the *status* automatically changes to *[7] Outgoing items booked.*
. Go to *Orders » Edit orders*.
. Change the status manually to *[10] warranty*.
. Save (icon:save[role="green"]) the settings.

[NOTE]
.Booking incoming payments for warranties
====
Generally, incoming payments for warranties only have to be booked it an additional charge has been negotiated with the customer. In this case, book the incoming payment after the customer has made it in the *Payment* tab of the warranty.
====

Proceed as described below to complete a warranty by creating a credit note order and the corresponding receipt.

[.instruction]
Completing a warranty with a credit note:

. Open the main order or the return order for which you want to create a credit note.
. Open the Overview tab.
. Click on the *Credit note* drop-down list and select *create*. +
→ The credit note order is created and opened in a separate window.

All further steps necessary to complete the credit note order are identical to the regular procedure for credit note orders. This is described in detail in the <<orders/managing-orders#500, credit note>> chapter on this manual page.

[#700]
== Working with repairs

In plentymarkets, repairs are represented by a separate order type. Repairs consist of returned items that need to be repaired. Thus, repairs can only be created from <<orders/managing-orders#400, returns>>.

[#710]
=== Creating statuses for repairs

Before using repairs you should set *statuses* for the different steps of the repair process in order to monitor the process in your plentymarkets system in detail.

[.instruction]
Creating statuses for repairs:

. Go to the menu *Settings » Sales orders » Sales order types » Repair*. +
. Enter the statuses you require for processing repairs. +
. *Save* (icon:save[role="green"]) the settings.

[#720]
=== Creating conditions for repairs

*Conditions* are used to precisely describe the items themselves, e.g. if an item needs to be repaired or if it is beyond repair.

[.instruction]
Creating conditions for repairs:

. Go to the menu *Settings » Sales orders » Sales order types » Repair*.
. Enter the different *conditions* you will need for assigning stock units. +
. *Save* (icon:save[role="green"]) the settings.

[#730]
=== Creating a repair

[.instruction]
Proceed as described to create a repair:

. Go to *Orders » Edit orders*.
. Open the return order for which you want to create a repair.
. Open the *Overview* tab.
. Click on the *Repair* drop-down list and select *create*. +
→ A window for editing opens. Enter the  *status* and the *condition* of the repair. Select the *Item*. Enter a *Note*, if you require it.
. *Save* (icon:save[role="green"]) the settings. +
→ The return is created and opened in a separate tab.

[#740]
=== Editing a repair

Depending on the reasons for return and the condition of the items that need repairing, different steps have to be carried out. +
Since repairs constitute a separate order type, you can use the *Overview* tab to proceed with a credit note, a warranty or a return order. The necessary steps for each of these order types such as creating the necessary documents, booking outgoing or incoming items or booking payments are identical to the order types <<working-with-credit-note-orders, credit note>>, <<working-with-warranties, warranty>> and <<working-with-return-orders, return>>.

[#800]
== Working with multi-orders

You can combine unpaid orders in a multi-order. Use the menu *Orders » Edit orders* or the *Orders* tab within a contact to search for such orders with the help of the search filter *Order status*, e.g. by searching for orders in status *[3] Waiting for payment*. Thus, there are two options for creating multi-orders, both described below.
With both options, unpaid orders are combined in a multi-order in the menu *Orders » Multi-orders*. Multi-invoices are then created in the *Receipts* tab of a multi-order.

[#810]
=== Carrying out basic settings for multi-orders

Carry out the basic settings for multi-orders the *Setup » Orders » Order types » Multi-order*. In this menu, you define such details as the order types and order statuses for which multi-orders are to be created.

[.instruction]
Carrying out basic settings for multi-orders:

. Go to *Setup » Orders » Order types » Multi-order*.
. Carry out the settings as described in <<table-multi-order-options>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-multi-order-settings]]
.Basic settings for multi-orders
[cols="1,3"]
|====
|Setting|Explanation

|*Order types*
|Select which order types are to be available for multi-orders. Multiple selections are possible. Only the listed order types *Order*, *Warranty* and *Repair* can be combined in multi-orders.

|*Item text*
|Select which options are used for the *item text* column of the stock units that belong to a multi-order. Multiple selections are possible. The selected options will be listed separately for each individual order within the multi-order. This ensures that the options can easily be connected to the correct customers and orders.

|*Sort orders by*
|Select how individual orders are sorted within a multi-order. Only one selection is possible. Orders can be sorted by their order ID (*Order ID ascending* or *Order ID descending*) or their date of outgoing items (*Outgoing items ascending* or *Outgoing items descending*).

|*Order status of orders*
|Select the status orders have to be in to be considered for multi-orders. Multiple selections are possible. Depending on your workflow, we recommend creating an individual order status to target specific order that are intended for multi-orders.

|*Order status of credit notes*
|Select the status <<orders/managing-orders#510, credit note orders>> have to be in to be considered for multi-orders.  Multiple selections are possible.
|====

Furthermore, go to *<<orders/basic-settings#, Setup » Orders » Settings>>* and use the option *Standard status for multi-order* to specify which order status should be given to multi-orders when they are generated. The status *[13] Multi-order* is available by default. In addition, select a status for multi credit notes. The status *[14] Multi credit note* is available by default.

[#820]
=== Creating a multi-order per customer class

Example: A company may not want to receive an invoice every time one of their employees make a purchase in your online store. Rather, the company prefers one monthly invoice for all of its employees’ purchases. Set up a customer class for this situation. The invoice recipient is specified by saving a customer ID in the customer class. The multi-invoice is generated directly within the corresponding multi-order and sent to this invoice recipient. +

Go to *Orders »Multi-orders* to create a multi-order for a specific customer class and a fixed time period. This way, all unpaid orders belonging to the customer class are combined in one multi-order. Use the option *Customer ID* in the customer class settings to determine a customer who is listed as the owner as well as as the recipient of the multi-invoice for a customer class. According to your workflow, we recommend creating specific <<crm/managing-contacts#15, customer classes>> for multi-orders.

[.instruction]
Creating a multi-order for a customer class:

. Go to *Orders » Multi-orders*.
. Open the submenu *Generate multi-orders*
. Select the *Customer class* and an optional *Period*. The time period refers to the date of the order income.
. Click on the gear-wheel icon (icon:cog[]). +
→ The multi-order is created.

[#830]
=== Creating a multi-order per customer

Customers prefer to pay for their orders once a month or once per quarter instead of paying several separate invoices. +
For these cases, go to *CRM » Contacts* to create a multi-order in the contact data. Open the contact and click on *New multi-order* in the menu on the left. A multi-order including all unpaid orders of the contact is then automatically created.

[TIP]
.Checking orders
====
In order to make sure that suitable orders for creating a multi-order are available, use the *Orders* tab in the contact data to look for unpaid orders.
====

[#840]
=== Generating a multi-invoice

Multi-invoices can only be generated in the corresponding multi-order. The first step consists of setting up a document template for multi-invoices in the menu *Setup » Client » Select client » Locations » Select location » Documents » Multi-invoice*. Here, you can specify detailed settings for the document and also save a <<orders/order-documents#, document template>> as a PDF file. Customise the template as required. Default values are set in the basic settings of the document template. You can also transfer further settings, e.g. from the document template *invoice*, to complete the values. Further information and instructions on setting up the document template are available on the *en/order-processing/orders/order-documents#, Order documents* page of the manual. +
After having set up a document template for multi-invoices, you can generate a multi-invoice in the *Receipts* tab of a multi-order.

[IMPORTANT]
.Incoming payments for multi-orders
====
If a customer pays a multi-invoice and the multi-order is marked as paid, the incoming payment is *not* automatically booked in the separate orders which are combined in the multi-order. You have to book incoming payments manually in the respective orders.
====

Use the event procedures available in your plentymarkets system to automatically generate a multi-invoice as soon as a multi-order is created. To do so, proceed as described below:

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The window *Create new event procedure* opens.
. Enter a distinct name for the event procedure.
. Select the *event* as listed in <<table-event-procedure-multi-invoice-automatic>>.
. *Save* (icon:save[role="green"]) the settings.
. Carry out the settings according to <<table-event-procedure-multi-invoice-automatic>>.
. Place a check mark next to the option *Active* (icon:check-square[role="blue"]).
. *Save* (icon:save[role="green"]) the settings.
--

[[table-event-procedure-multi-invoice-automatic]]
.Event procedure “Automatically generating a multi-invoice”
[cols="1,3"]
|====
|Setting |Selection

|*Event*

|*Order generation > New multi-order*

|*Procedure*

|*Documents > Generate multi-invoice* +

*_Note_*: Within the procedure, you can determine values for *Payment due* as well as *Early payment discount*.
|====

[#845]
=== Generating dunning letters for multi-orders

Just like invoices for multi-orders, you can generate dunning letters for multi-orders in the *Receipts* tab of the respective multi-order. To do so, proceed as follows:

[.instruction]
Generating dunning letters for multi-orders:

. Go to *Orders » Edit orders*.
. Open the multi-order for which you want to generate a dunning-letter.
. Open the *Receipts* tab.
. Select the option *Dunning letter* from the drop-down list *Create receipt*.
. Click on *Create receipt*. +
→ The dunning letter is created and opened in a separate tab.

[#850]
=== Generating a multi credit note

Multi credit note are generated in the menu *Orders » Multi-orders*. +
All credit notes for a customer class are combined in one multi credit note. Depending on your workflow, we recommend creating specific <<crm/managing-contacts#15, customer classes>> for multi credit notes.

[.instruction]
Generating a multi credit note for a customer class:

. Go to *Orders » Multi-orders*.
. Open the submenu *Generate multi credit notes*.
. Select the *Customer class* and an optional *Period*. The time period refers to the date of the order income.
. Click on the gear-wheel icon (icon:cog[]). +
→ The multi credit note is generated.

[#1100]
== Working with advance orders

Advance orders are an important tool in the marketing mix for electronic commerce. Often, items can be ordered at a reduced, introductory price before they actually become available. This represents an unusual case for stock management since items that are not available yet cannot be allocated to a warehouse.

Advance orders are very easily set up in plentymarkets. Just use the order type *advance order* for manually created orders.

To be able to receive advance orders via your online store, you have to enter the release date and availability for the items. Carry out the item settings as described below.

[IMPORTANT]
.Manual order input
====
The order type *advance order* can only be selected when manually entering orders.
====

[#1110]
=== Release date

You find the option  *Release date* within the area for editing items, listed in the *Available* tab. Here, you can use the calendar to enter the date on which the item will become available (this entry is also possible via dynamic import). To do so, proceed as described below.

[.instruction]
Entering the release date

. Go to *Item » Edit item*.
. Open the item you want to offer in advance.
. Open the variation you want to offer in advance.
. Go to the *Settings* tab of the variation and scroll down to the section *Availability*.
. Enter the date on which the item is to be available in the field *Release date*.
. *Save* (icon:save[role="green"]) the settings.

Next, make sure that this date will also be displayed to your customers. To do so, proceed as described below.

[.instruction]
Displaying the release date in the online store:

. Go to the menu *CMS » Web design » Folder: Layout » Folder: ItemView*.
. Open the *ItemViewSingleItem* template.
. Insert the template variable *$ReleaseDate*.
. *Save* (icon:save[role=”green”] the settings.

[#1120]
=== Item availability

Another requirement is to correctly set the *Item availability*. To do so, proceed as described below.

[.instruction]
Setting up item availability for advance orders:

. Go to *Item » Edit item*.
. Open the item you want to offer in advance.
. Open the *Settings* tab.
. Select *No limitation* for the *Limitation* option. +
→  The item can now be ordered and thus purchased, even without actually being in stock yet.

[TIP]
.Maximum order quantity
====
In order to prevent other online sellers from misusing your advance orders to completely buy out your item a reduced price, enter a value for the option *Maximum order quantity* in the *Available* tab. If you enter the value *1* there, the item can only be purchased once per order. If you set the maximum order quantity to *0*, the item will be sold without limitation.
====

[#1130]
=== Setting up a payment request for advance orders

Usually, the option *shipping date* is not used for ordinary orders. However, it can be helpful to use this option for advance orders. If the release date of an item is in the future, the release date will then be saved as the order’s shipping date since deliveries can only take place once the item is released. You can use the shipping date as a filter option in the order search and in the procedure manager.

Advance orders are usually generated some time before an item appears and are not paid for by the customers at the time when they are ordered. That’s why it is useful to inform your customers a few days in advance about the upcoming shipment and request payment from them. Use the procedure manager to automate this process. A few days before shipping takes place, the procedure manager will automatically send the customers a reminder email stating your bank details and providing a link to the checkout. Proceed as described below to set up the automatic payment request.

[.instruction]
Setting up a payment request via email:

. Create a suitable *<<crm/sending-emails#, email template>>*.
. Go to *Setup » Orders » Procedures*.
. Open the New procedure tab.
. Enter a *name* in the *Settings* tab.
. Select a time from the drop-down list next to the option *Execute every day at*.
. Place a check mark next to the option *Active* to activate the procedure.
. Click on the *Filter* tab.
. Set the *status* to *[3] Waiting for payment*.
. Select an option for *Shipped on*, e.g. *in 4 days*.
. Click on the *Procedure* tab.
. Select the previously created email template for the option *Send email template*. With this procedure, this template will automatically be sent to the customer.
. Click on *save* (icon:save[role="green"]) to save the procedure.

[#1200]
== Using the order status

The order statuses visualise the progress of orders during order processing. 19 statuses with 4 decimal places each, so a total of 199999, are available in your plentymarkets system. 28 statuses are set by default. These statuses represent a basis for usual steps of order processing. Some of these 28 statuses are linked to automatic processes in the system and should only be used by you for these designated purposes within the system. The status of an order changes because of these automatic processes in the system, through automatic processes set up by you or can be changed manually. Order statuses also improve the order search.

Roughly go through your order processes and determine when you want to assign a different status to orders to depict the progress of your processing. Set up your statuses after this by entering names for them. But take into account the default statuses which already set up for a specific purpose, mentioned in table

[TIP]
.Pay attention to the user rights
====
Note that elements such as drop-down lists only display those *shops* and *statuses* for which the current user was given rights to. If you do not see a status, it is most likely that you do not have the rights needed for this. Rights can be assigned by admin-users.
====

[#1210]
=== Comprehending default order statuses

The following 28 status entries are available by default in your plentymarkets system and some of them linked to automatic processes in the system. Those statuses linked to an automatic process are not deletable.

[[table-default-statuses]]
.Default statuses and automatic processes within the system
[cols="1,3"]
|====
|Status|Explanation

|**[1]** Incomplete data
|Is assigned automatically when the data of an order are incomplete, e.g. address data. Incomplete data can sometimes occur when they are imported from markets. Orders with this status are not to be processed further. The data will be completed by subsequent imports. The incomplete data are useful for a timely booking of stock.

|**[1.1]** Waiting for payment & activation
.3+|Are not automatically assigned. A use case is the shopping cart which was filled in advance. An order is generated and a link to the shopping cart of the order is sent to the customer for confirmation.

|**[1.2]** Activated, waiting for payment

|**[2]** Waiting for activation

|**[3]** Waiting for payment
|Is assigned automatically to every unpaid regular order.

|**[3.2]** In waiting position
|Is automatically assigned in 3 cases: +
* If a partial payment for an order is booked, but the items are in stock. +
* If partial payment for an order is booked and the items are in stock. +
* If an overpay for an order is booked and the items are in stock.

|**[3.3]** Ready for shipping; waiting for payment
|Is automatically assigned to a regular order if a partial payment or overpayment for an order is booked and the items are in stock.

|**[3.3]** Dunning letter sent
|We recommend this status to indicate that a dunning letter was sent. Set up an automatic process for this by using an event procedure. However, the status is not set by an automatic process within the system.

|**[4]** In preparation for shipping
|Is connected to the stock limitation. If you are not keeping an inventory and do not use the stock limitation, the status is available to be re-assigned. +
When the stock limitation is used, the status is automatically assigned as soon as a regular order is fully paid but the item is not in stock in sufficient number. The item limitation as to be set to net stock. +
If you use stock limitation and this status for insufficient stock, it is possible to have only those delivery notes and invoices generated, which can be processed further.

|**[5]** Cleared for shipping
|Is automatically assigned, when a regular order is paid or the payment method is invoice or cash in advance and the item is either in stock or stock is unlimited.

|**[5.1]** External processing
|We recommend to use this status to indicate that the items are compiled and sent by a fulfillment provider. However, the status is not set by an automatic process within the system.

|**[6]** Currently being shipped
|We recommend to use this status to indicate that orders are transferred to the warehouse to be picked and packed. Set up an automatic process for this by using an event procedure.

|**[7]** Outgoing items booked
|Is automatically assigned when outgoing items of an order were booked. Manually setting this status for an order does not cause the actual booking of outgoing items or the reduction of stock. This is why this status should neither be set manually, nor via an event procedure or an automated process.

|**[7.1]** Order exported
|This field can be used as required. A possible use case is to assign this status after items are exported to be analysed.

|**[8]** Cancelled
|We recommend to use this status to indicate that a regular order was cancelled. Status 8 is the standard status for cancelled orders. However, if required, you can adjust the standard statuses in the menu *Setup » Orders » Settings*. Here, the setting is called *Status of cancelled orders*. If you assign a different status to cancelled orders, you can re-assign status 8 as required.

|**[8.1]** Cancelled by customer
|We recommend to use this status to indicate that an order was cancelled by a customer.

|**[9]** Return
|Is automatically preselected when a return is created.  You can also change this standard status in the menu *Setup » Orders » Settings*.

|**[9.1]** Items are checked
|We recommend to use this status to indicate that returned items are checked.

|**[9.2]** Waiting for return from wholesale dealer
|This status can be used as required.

|**[9.3]** Warranty initiated
|We recommend to use this status to indicate that a warranty of a return is initiated.

|**[9.4]** Exchange initiated
|We recommend to use this status to indicate that an exchange of returned items is initiated.

|**[9.5]** Credit note created
|We recommend to use this status to indicate that a credit note for a return was created.

|**[10]** Warranty
|This status can be used as required. It can be used to identify a completed warranty. When creating a warranty, the corresponding order is switched either to status 4 or 5, depending on your workflow.

|**[11]** Credit note
|This status is automatically assigned to a credit note order, when a credit note is generated. You can change the standard status for this, if required. In order to do this, go to the menu *Setup » Orders » Settings*.

|**[11.1]** Credit note disbursed
|We recommend to use this status to indicate that a credit note was disbursed and is completed.

|**[12]** Repair
|Is automatically preselected when a repair is created. You can change the standard status for this, if required. In order to do this, go to the menu *Setup » Orders » Settings*.

|**[13]** Multi-order
|Is automatically assigned to a multi-order when it is created. You can change the standard status for this, if required. In order to do this, go to the menu *Setup » Orders » Settings*.

|**[14]** Multi credit note
|Is automatically assigned to a multi credit note when it is created. You can change the standard status for this, if required. In order to do this, go to the menu *Setup » Orders » Settings*.
|====

[#1220]
=== Creating and editing order statuses

 You can add statuses to the ones described in <<table-default-statuses>> . Already existing statuses can be edited or renamed. Maintain statuses in different languages in order to inform your customers about the progress via email or in the customer account of the online store. Apart from statuses linked to automated processes within the system, all statuses can be deleted. Statuses linked to automated processes within the system can be renamed. However, you should make sure not to misuse those statuses linked to automated processes within the system.

[TIP]
.Name is not a mandatory field
====
Entering a name is not mandatory. However, if you do not maintain names you will only see a list of apparently empty statuses in the filters and an empty status field in the order overview. Therefore, enter at least the status number also as name in the language you use the most often, German or English. Translations to other languages are only used for display in the customer account of your shop and for customer information via email.
====

[#1230]
==== Adding a status

Add your own statuses.

[.instruction]
Adding a status:

. Go to *Setup » Orders » Status*.
. Click on *Create new status* (icon:plus-square[role="green"]).
. Enter a number for the new status. +
→ The highest possible number is 199999.
. Optionally, enter a name for the new status. +
→ The language in which you are logged in is shown as input field.
. *Save* (icon:save[role=”green”] the settings. +
→ More fields for further settings are shown. +
. Add further languages for the status if required.
. Use the option *colour* to assign an individual colour to the status. +
. *Save* (icon:save[role="green"]) the settings.

[NOTE]
.Decimal places
====
When assigning numbers to new statuses, make sure that they do not end with 0. If the last decimal place is a 0, the system automatically deletes it. Thus, plentymarkets makes no distinction between a status with the number 1.1 and a status with the number 1.10.
====

[#1240]
==== Editing existing order statuses

Proceed as follows in order to edit an already existing status.

[.instruction]
Editing a single order status:

. Go to *Setup » Orders » Status*.
. Click on *Search* (icon:search[role="blue"]). +
→ A list of all existing order statuses opens.
. Select the status you want to edit. +
→ The details of the selected status are opened.
. Change the name of the status.
. Change the *colour* of the status.
. *Save* (icon:save[role="green"]) the settings.

Use the group function in the menu *Setup » Orders » Status* to edit multiple orders statuses at the same time.

[.instruction]
Editing multiple existing order statuses:

. Go to *Setup » Orders » Status*.
. Click on *Search* (icon:search[role="blue"]). +
→ A list of all existing order statuses opens.
. Place a mark next to all statuses you want to edit.
. Click on *Group function* (icon:gear[role="darkGrey", stack="gear,darkGrey", stackPosition="lr"]). +
→ A new editing area is displayed.
. Activate (icon:check-square-o[role="blue"]) the option *New colour* in order to change the colour for the statuses.
. Activate (icon:check-square-o[role="blue"]) the option *Store visibility* and select the required settings from the drop-down list.
. Click on the *gear-wheel* icon (icon:gear[role="darkGrey", stack="long-arrow-right,darkGrey", stackPosition="lr"]) to transfer the settings to the selected order statuses. +
→ You are asked to confirm your decision.
. Confirm the query by clicking on *Change statuses*. +
→ The changes are saved.

[#1300]
== Searching for orders

The search can either be used to compile all the orders or to find specific orders. A search is not automatically conducted as soon as the menu is opened. The filter for date is set by default to *Order received* and shows the received orders of the last 2 months. All other filter options are initially set to **ALL**. Adapt the filter settings to refine your search. Then conduct the search.

[.instruction]


Searching for orders:. Go to *Orders » Edit orders*.
. Adapt the filter settings.
. Check, whether the standard setting of the option *Date* and the time period *from to* meet your requirements.
. Click on *Search* (icon:search[role="blue"]) to have the corresponding orders listed.

For example, all orders which are not yet completed will be listed when you search for orders with a status smaller than (<) 7 (outgoing items are not booked yet) and do not set filter for date.

[NOTE]
.Resetting the search
====
Click on *Reset* (icon:undo[role="orange"]) to reset your filter settings to the default values. Then click on *Search* (icon:search[role="blue"]) again in order to reset the search result as well.
====

[#1310]
=== Filtering by IDs and numbers

In order to filter by IDs or numbers, enter a value in the corresponding field. By entering a *Customer-ID* in the corresponding field, only orders of this customer will be shown, for example.

Or, for example, by entering the number 3 in the field *Order ID* only the order with the ID 3 will be displayed. Accordingly, it is an exact and not a fuzzy search . But it is possible to enter several IDs in the field Order ID and thus to search for several orders at once. Only separate the IDs by commas.

[NOTE]
.Status search filter
====
If you are searching for numbers or IDs it makes sense not to narrow down the status but set it to *All*. Only those orders are displayed which fulfill all the set criteria. If you cannot find an order despite having entered the exact ID, you might have forgotten to set the filter for *Status* to *ALL*.
====

[#1320]
=== Filtering by customer data, item data or invoice numbers

Using the fields *Customer data* and *Item data* is recommended, when you are looking for a specific customer or item. You can either enter terms or numbers, both is allowed. Besides names, you can also enter postcodes but no telephone numbers, into the *Customer data* field. For a search with *Item data*, the fields item ID, item number as well as name are taken into account, but not the descriptive fields like short description, for example. A search for external invoice numbers is also possible when searching for *Invoice numbers*.

[NOTE]
.Only shorten the end of search terms and numbers
====
Quite often it is sufficient to enter only the stem of the word when searching for customers or item data. Just bear in mind that search terms may be truncated almost freely at the end but not the beginning. For example, if you are searching for items with the term packages, you could also enter package or pack. However, searching for ackage would not yield any results. It is the same for all numbers, e.g. postcodes.
====

[#1330]
=== Filtering by order type

Use the filter *Type* to search for the following order types:

* *Order*
* *Credit note order*
* *Multi credit note*
* *Return*
* *Warranty*
* *Offer*
* *Advance order*
* *Delivery order*
* *Repair*
* *Multi-order*
* *Orders, warranties, delivery orders and repairs*
* *Orders and delivery orders*

It is searched only for the selected order type or combination thereof. The filter is set to *ALL* by default, meaning that it will be searched for all order types.

[#1340]
=== Filtering by date

Use the filter *Date* to search for orders that already passed through a specific step of the order processing during the period of time you selected. For this step you can either select *Orders received*, *Incoming payment* or *Outgoing items* in the filter *Date*. After this, choose the start date under *from* and the end date under *to*.
All orders which already went through the chosen step during the selected period of time are displayed. The filter is set by default to *Orders received* and the time period to the last 2 months.
If you do not want to search for orders within the last 2 months, set the required period of time as described above.

[#1350]
=== Filtering by flags

Irrespective of order statuses, you can also assign flags to orders. You can also search for orders by these flags. Flags could be assigned, for example, to problematic orders. This way, someone in charge has to clear them before shipping. This person can search for these orders e.g. once a day by using the filter *Flag*, add information and then reset the flag.

[#1360]
=== Filtering by documents

Use the filter *Document* to search for orders for which a specific *<<orders/order-documents#, order document>>* has already been created. You can either search for a specific *document type* or for a document number.
You can also combine these two search criteria and search for an order for which a specific document type with a specific document number has been created. +
The search for *document type* results in an overview of those orders for which this document type has already been created. The search for specific *document numbers* yields more distinct results, i.e. specific documents and their corresponding orders.

To search for all orders with a specific document, proceed as described:

[.instruction]

. Go to *Orders » Edit orders*.
. Select a *document* from the drop-down list in the *Filter* tab, e.g. *Invoice*.
. Take into account the filter for *Date*. By default this is set to the last 2 months. Adjust the filter if required.
. Click on *Search* (icon:search[role="blue"]). +
→ All orders, for which an invoice has already been generated, are displayed in the search results.

To search for an order which contains a document with a specific number, proceed as described:.

[.instruction]

. Go to *Orders » Edit orders*.
. Select a *document* from the drop-down list in the *Filter* tab, e.g. *Delivery note*.
. Enter the number of the delivery note into the field *Number*.
. Take into account the filter for *Date*. By default this is set to the last 2 months. Adjust the filter if required.
. Click on *Search* (icon:search[role="blue"]). +
→ Only the order to which the delivery note belongs is displayed.

[TIP]
.Selecting a document type not obligatory when searching by number
====
The search for a document number also works when the standard setting for *Document* is not changed, i.e. when no document type is selected. However, if the numbers of different document types are identical, all orders including a document with this number are displayed. This can be the case, if you did not *<<orders/order-documents#1800, define number ranges>>*, for example.
====

[#1370]
=== Filtering by coupon codes

Search for orders containing coupons by entering the *Coupon code* into the corresponding field. Additionally, you can choose between the options *ALL*, *Redeemed* and *Sold*. *ALL* is set by default. Select *Redeemed* if you only want to search for orders containing already redeemed coupons. When you select *Sold*, you are only searching for orders with which a coupon with integrated coupon codes was sold. Select *ALL* to search for orders containing both, sold and redeemed coupons. The filter only works when a coupon code is entered, even if it is set to *ALL*. In other words, you cannot use this filter to search for all orders containing coupons.

[#1400]
== Setting up the order overview

The following tools help you to easily keep track of and manage the search results. +
You can specify how many orders are displayed per page in the order overview. The maximum amount of orders per page is 400, the lowest is 50. +
Use the arrows to switch between pages. You can also enter the required page number directly and press Enter.

[#1410]
=== Item list in the order overview

The item list is displayed by default in the order overview. Thus, the items included in an order and their most important parameters such as *name*, *size* and *price* are immediately available to you. However, the item list can also be hidden, either for individual or for all orders.  To hide the item list of an individual order, use the arrow icon *close item list.* To hide the item list for all orders, proceed as described below.

[.instruction]
Hiding the item lists for all orders:

. Go to *Orders » Edit orders*.
. In the *Filter* tab, select the setting *Do not show* for the option *Stock unit*.
. Click on *Search* (icon:search[role="blue"]). +
→ The item lists will close for all displayed orders.

[#1420]
=== Information and icons in the order overview

Depending on the order’s condition, different icons are displayed in the order overview. Those are explained further below. A tooltip with a brief explanation is displayed when you move the mouse over an icon.

In the header of an order you can see at least how you rated the customer, the *<<orders/managing-orders#1200, order status>>*, the logo of the *<<fulfillment/preparing-the-shipment#, shipping service provider>>* as well as the *<<payment#, payment method>*. Depending on the progress of the order, further icons may be displayed there. For example, when outgoing items are booked, the icon *Book outgoing items* is replaced by the icon *Outgoing items booked*. The order status also changes to status 7 when the outgoing items are booked. The colour of the status display helps you to identify all orders with the same status at a glance.

The following table contains an overview of all possible information that could be displayed. Some icons also allow you to perform actions directly. Note, that only those icons are displayed that correspond with the state the order is in.

.Possible icons in the order overview
[cols="1,3a"]
|====
|Tooltip of the icon|Explanation

|*Order status*
|Shows the status the order is currently in. The order status can be adjusted here. In order to do so, click on the status and select the required one. +
**Important**: When an order has the status >= 7, the status cannot be changed into a status lower than this without reversing the booking of the outgoing items.

|*Shipping service provider*
|This is an individual icon of the assigned provider. However, an icon is only displayed if you set up flags while creating the *<<fulfillment/preparing-the-shipping#1000, shipping profile>>*.

|*DHL Packstation*
|This icon is only displayed when the data for the packstation are correctly recorded within the order. When orders originate from markets, it can happen that data for the packstation are incorrect, e.g. if the market does not provide validation. In this case the icon is not displayed because delivery to a packstation cannot take place due to the incorrect data.

|*Shipping method* or +
 *Shipping service provider*
||*Express shipping* is a service which is displayed by as extra icon.

|*Payment method*
|Customised icon of the payment method.

|*Outgoing items booked*
|Is only displayed, when the outgoing items are booked. If only the status was changed to status 7, the icon is not displayed.

|*Dunning level*
|Dunning levels can be allocated with the procedure manager.

|*Flag*
|Customised marking of orders.

|*Country of delivery*
|ISO-Code for a country of delivery according to ISO-3166 Alpha 2.

|*Currency*
|ISO-Code of the currency according to ISO 4217.

|*Payment status*
|Corresponding with the status of the payment this is displayed as a coloured bar with an additional tooltip showing the percentage value.

|*Create order confirmation*
|Immediately creating an order confirmation.

|*Generate invoice*
|Immediately creating an invoice.

|*Book incoming payment directly*
|Directly booking the payment of an order. The amount is freely adjustable. The amount still to be paid for the order is preset.

|*Create delivery note*
|immediately creating a delivery note.

|*Book outgoing items*
|Allows to immediately book the outgoing items. This leads to a reduction of stock, if you are keeping stock. The order status automatically changes to status 7.

|*Display tracking URL*
|The tracking URL is used to track a shipment. The *<<fulfillment/preparing-the-shipping#800, tracking URL>>* has to be entered and saved when setting up the shipment providers.

|*Create order note*
|Allows you to write a note about an order as well as to read already existing notes. If there is an icon without a plus, there already is a note.

|*Customer notes*
|Allows you to write a note about a customer as well as to read already existing notes.

|*The email address of the customer*
|Allows you to directly write an email to the customer via your email provider.

|*Email service*
|This icon opens the Email templates tab and thus allows you to directly send emails to customers or to read already sent templates.

|*Show existing processes*
|Displays among others a list with returns and credit notes with dates and values.

|**Calculate stock*
|Calculates and opens an overview of your stock of the variations contained in an order. +
Reorders can be done via the shopping cart.

|*Open item list* or *Close item list*
|You can display or hide the item list.

|*Show reorders*
|Opens the reorders for this order in the *Reorder* menu.

|*Invoice number*
|Opens the invoice.

|*Item ID* or *Variation ID*
|Opens the item or the variation in the menu *Item » Edit item*.
|====

[#1500]
== Editing orders

All of your orders are displayed in an overview in the menu *Orders » Edit orders*. Click on an item ID to open the order and edit its settings. You can edit all order settings as long as no document has been generated for the order. The settings are in different tabs that are explained on this page.

[#1510]
=== Information and procedures in the order overview

All of your orders are displayed in the menu *Orders » Edit orders*. Here you can see the most important information about each order. You are provided with information about the customer, the order status and the payment status. You can also tell which items are included in the order, whether the outgoing items were booked and whether an invoice was generated. In other words, you can easily keep track of the most important processes without having to open the order. Move the cursor over the icons to see tooltips with additional information.

Click on an *icon* to open further areas within the order. For example, click on *Calculate stock* to check the current stock of the item or to reorder stock.

Furthermore, use the order overview to change the *status*, the *shipping charges*, the *item data* or the *discount* if required. The information below gives an example of how to change the status.

[.instruction]
Changing the order status in the order overview:

. Click on Status. +
→ A drop-down list with all available statuses is displayed.
. Select the required status. +
. *Save* (icon:save[role="green"]) the settings. +
→ Der Status is updated.

[#1520]
=== Opening and editing an order

Open the menu for editing an order by clicking on the header of an order in the overview. The order opens in a new tab. Every order has several sub-tabs that contain data and information. The tabs are described on this page of the manual. Orders that are open can be identified by their *ID* in the tab's title.

[NOTE]
.Saving the settings or changes
====
Most of the order's tabs do not include a save icon. Settings made in these tabs are saved automatically, e.g. changing the flag or dunning level in the *Overview* tab. You can switch to a different tab or close the order and open it again without losing the changes. However, some tabs include a save icon, e.g. the *Settings* tab. Here, you can switch to a different tab without losing the changes. But you have to save all your changes before closing the order.
====

[IMPORTANT]
.Default settings for editing orders by variable users
====
In order for variable users to be able to open orders, go to the menu *Setup » Orders » Settings* and save default statuses for *returns* and credit notes. No status is saved here as the default setting. Variable users also need to be given the right to edit orders. Go to *Setup » Settings » User » Accounts* in order to carry out the required settings.
====

[TIP]
.Restricted editing options for POS orders
====
The editing options for POS orders are restricted to comply with legal requirements. Only a few settings are editable.
====

[#1530]
=== Tab: Overview

The most important order parameters are found in the *Overview* tab. At a glance, you get information about prices, shipping costs, VAT, status, etc.

[TIP]
.Tip: Changing values
====
You can recognise changeable values by a drop-down list or by the appearing *pencil* icon. Click on the pencil icon to edit the required parameters (e.g. image 16, the *Weight* entry in the top left corner).
====

.Options in the *Overview* tab of an order
[cols="1,2"]
|====
|Setting |Explanation

|*Order ID*
|ID of the order. The ID is automatically assigned and can not be changed.

|*Customer ID*
|ID of the customer.

|*Checkout*
|Opens the order in the *My account* area of the online store.

|*Input*
|The date the order was received, i.e. the date the order was created or imported into the system. The input date can be edited manually as long as no document exists for the order.

|*IP address*
|Displays the customer's IP address if required. +
Go to *<<omni-channel/online-store/setting-up-clients/order-process#, Setup » Client » Select client » Order process » Settings>>* to activate or deactivate the *Purchaser's IP address* option.

|*Flag*
|Assign a flag to an order, if required. Flags are used to categorise orders. This helps you e.g. to find orders with the search filter or to apply automatic functions to them with event procedures.

|*Dunning level*
|Various dunning levels are set here if a customer does not pay for the order. These dunning levels are used for automatic processes within the dunning procedure. +
An example of how to use dunning levels can be found on the *<<payment/payment-providers/mediafinanz#, mediafinanz>>* page of the manual.

|*Estimated shipping*
|The date for estimated shipping is calculated based on the delivery date for a *<<stock-management/managing-reorders/workin-with-reorders#, reorder>>*. In order for the estimated shipping date to be displayed, both the reorder and the item's delivery date have to be confirmed and the order has to be in *status 4*. +
**Important:** The option *Shipped on* in the *Settings* tab has a different function. See table 2.

|*Copy*
|Copies the order and creates a new order with a distinctive ID in a separate tab.

|*Delete*
|Deletes the order. You are asked to confirm your decision.+
The delete icon (icon:minus-square[role="red"]) is not displayed when:+
- The user is not *<<basics/admin-tasks/manage-users#105, authorised>>* to delete orders.+
After outgoing items are booked.+
A delivery order was created.+
Generally, orders should not be deleted. Errors can occur when orders are deleted because the orders are linked to items, shipping settings and other functions such as cancellations and returns. However, newly created orders can be deleted without any problems.

|*Split up*
|Splits the order. You are asked which of the items are to be transferred to the partial order.

|*Return; Credit note; Warranty*
|Click on the drop-down list to create or search for the order document.

|*New order*
|Creates a new order for the customer. Default settings will automatically be used for the order. You may need to change these settings.

|*Invoice address*
|Click on the *small plus* icon to display the invoice address. Additional customer information such as the telephone number, email address and eBay account name are displayed as well.

|*Delivery address*
|Click on the *small plus* icon to display the delivery address. The *delivery address* will be crossed out if it is identical to the invoice address. +
* Click on *New delivery address* to create a new delivery address. Click on *List all delivery addresses* to select a delivery address. +
*Export delivery address* = Exports the delivery address in the format used by the selected shipping service provider.

|*Bank details*
|Click on the *small plus* icon to display and edit the customer’s *<<payment/managing-bank-details#, bank details>>*.

|*Customer notes*
|Displays the notes that were saved for this customer. Click on *New note* to create a note about the customer. Existing notes are displayed in yellow in the editing window. New notes are formatted with the familiar editor functions. Notes that are saved here will be displayed in other orders placed by this customer. They will also be displayed in the *Notes* tab within the customer data record.

|*Order note*
|Displays the notes that were saved for this order. Click on *New note* to create a note about the order. New notes are formatted with the familiar editor functions.

|*Status history*
|Displays a list of all the changes of the order's status.

|*Payment history*
|Shows details about payments such as payment method, currency, payment ID or date.

|*Stock units*
|Displays information about the stock units included in the order.

|*Edit*
|Allows you to edit the item data if required, e.g. item quantity, item details, prices, discounts and VAT rates.

|*Add*
|Use the integrated item search to add other items to the order as required.

|*Assign storage location*
|Assigns a storage location to the stock units. If more than one storage location is saved for an item, then the storage locations will be given priority based on their positions. If no storage location was saved, then the *standard storage location* will be assigned. +
The assignment of a storage location is especially important for pick lists and packing lists. +
*__Tip__*\: You can also use *<<automation/event-procedures#, event procedures>>* to assign storage locations to items.

|*Delete assignment*
|Deletes the current storage location assignment. Click on *Assign storage location* again (see above) to create a new assignment that is better suited to the current warehouse situation.
|====

Splitting orders

To split orders, go to the menu *Orders » Edit orders*. Open the order you want to split and go to the *Overview* tab. Orders are only to be split when the following conditions apply:

* No incoming payment has been booked yet.
* Outgoing items have not been booked yet.
* No invoice was generated yet.

[#1540]
=== Tab: Settings

An order’s basic parameters are saved in the *Settings* tab, e.g. the *Status*, *Referrer* or the *Payment method*.

.Options in the *Settings* tab of an order
[cols="1,2"]
|====
|Setting |Explanation

|*Status+*
*Order type* +
*Owner* +
*Referrer* +
*Client (store)*
|These options are displayed depending on the existing conditions or circumstances. However, they can be changed.

|*Warehouse*
|The warehouse or main warehouse of the order item. If required, click on *Stock correction* to change the warehouse. +
*_Important_*: The option *Stock correction* synchronises the data displayed in the *Settings* tab of the order with the warehouse saved for the order items included in the order. The option is only available when you selected *b) a warehouse can be assigned for each stock unit* in the menu *<<orders/basic settings#, Setup » Orders » Settings>>*. If you manually change the warehouse assigned to an order item and the changed warehouse is not automatically visible in the *Settings* tab of the order, click on *Stock correction* to update the display of the warehouse.

|*Status*
|The order status *[7] Outgoing items booked* can not be changed to a lower status. This is because the items have already been shipped. However, if you still want to do this, then you first need to reset the outgoing items that were booked. It is possible to switch to a lower order status afterwards.

|*Outgoing items*
|Indicates whether outgoing items were booked and displays the corresponding date. +
* Click on *Outgoing items* to manually book the outgoing items, if required.

|*Shipped on*
|This is the *shipping date* that was saved in the item data record. As such, this option is relevant for *<<orders/managing-orders#1100, advance orders>>*. If the order includes several items that were all ordered in advance, then the date that is farthest in the future will be displayed here. The date can be changed manually.

|*Return date*
|Save the date of a return if an item was returned. Serves as information about a return, so that the return does not have to be opened separately.

|*Currency*
|The currency of the order.

|*Payment method* +
*Shipping service provider* +
*Shipping profile & shipping charges*
|These options will be displayed depending on the existing conditions or circumstances. However, they can be changed. +
* In order to carry out changes, select a *payment method* from the drop-down list and click on the *pencil icon* to edit the shipping options.

|*Payment due*
|You can save values for the options *Valute date*, *Early payment discount (days)* and *Early payment discount (%)*. Decide whether to save a value for one of these options or for multiple options, thus creating your terms of payment. If the values were already saved in the <<crm/managing-contacts#100, customer data>> then they will automatically be displayed here. However, they can still be changed.

|*Shipping service provider*
|The shipping service provider that will ship the items for this order.

|*Shipping profile & shipping charges*
|The shipping profile and shipping costs for the order.

|*Ext. order number*
|Enter the external order number for orders that are imported from an external system.

|*Customer reference*
|If the *Your reference* field is visible to customers during the order process, then any text that a customer entered into this field will appear here.
|*Packages*
|Number of packages belonging to this order. +
__**Important**__: This entry is not linked to the number of packages set in the Shipping center. If you want to edit the number of packages, do so in the Shipping centre.

|*Package number*
|Package number of the shipping package. +
If a package number was saved, then the *preview icon* can be used for tracking the package. However, this can only be done if a corresponding tracking code was saved under <<order-process/fulfillment/preparing-the-shipment#, Setup » Orders » Shipping » Shipping options » Tab: Shipping service provider>>. Otherwise the preview icon will not be visible.
|====

[#1550]
=== Tab: Email

The *Email* tab contains all of the email templates that were configured in the menu *<<crm/sending-emails#, Setup » Client » Select client » Email » Templates>>* and that were set up as a type of template that is visible for orders. You can manually send these email templates to customers. This is useful if you unexpectedly need to send an email to a customer, i.e. an email that is not sent with an automatic procedure. Proceed as described below to send an email template.

[.instruction]
Sending an email template:

. Go to *Orders » Edit orders*.
. Open the order.
. Click on the Email tab.
. If required, select the language.
. Click on the *Email templates* tab and select the tab that contains the required email template.
. Select the required template.
. Click on *Direct Emailing*. +
→ The email is sent.
. Wait until you see a message confirming that the process was completed.

Check the *crm/sending-emails#100, access data* if the email was not sent correctly. Go to *<<basics/data-exchange/api-log#, Data » API log>>* and use the *Email* process to see the corresponding error messages.

[IMPORTANT]
.Sending customers a new password
====
The email template *Send customer a new password* cannot be sent from within an order. If you want to send this email template, then do so from within the customer's data record. Click on the *Settings* tab there. You will be able to see the *Password* tab when a customer has registered in the store. This is where you can send the email template.
====

The *Emails sent* tab provides an overview of all the email templates that were sent. You can see the *date*, *recipient* and name of the *email template* as well as the *order ID*. You can see all of the emails sent to the customer, even those from other orders.

[#1560]
=== Tab: Payment

Click on the Payment tab to see all payments and partial payments belonging to the order. Use the filters to search for specific payments of the order. In the *Payments* tab you can see the total invoice amount, the amount paid and the amount that is still pending. Thus, you get a comprehensive overview. Moreover, you can use the *Book payment* icon in this tab to manually book payments.

[TIP]
.Missing incoming payments
====
If there are payments missing in the overview, change the *Received from* filter to adjust the point of time from which on payments should be displayed.
====

Find more detailed information about *<<payment/managing-payments#, managing payments>>* in the manual.

[#1570]
=== Tab: Receipts

Create receipts in the *Receipts* tab, e.g. an order confirmation, a delivery note or an invoice.
Once you have created documents for an order you can no longer edit the input date of the order.
The documents are created with the help of document templates that are saved under *<<orders/order-documents#, Settings » Orders » Documents>>*. Check the document templates to make sure that the settings are right before you create receipts. Check the templates also if you receive an error message.

[TIP]
.Tip: Copying document templates
====
If you want to create a *<<orders/order-documents#300, document template>>* quickly, then simply copy a previously configured document template and make changes to the template as needed.
====

The receipts are configured before they are created. You can specify different parameters for each receipt. For example, when creating an invoice, you can enter the date, specify when the *payment is due*, whether customers should be given an early payment discount and whether the outgoing items should be booked. Furthermore, you can change the status when the receipt is created.

[#1580]
=== Tab: Customer

By clicking on the *Customer* tab, the <<crm/managing-contacts#, contact data record>> opens. These information are editable.

[#1590]
=== Tab: Tickets

The customer's *<<crm/using-the-ticket-system#, tickets>>* are displayed in the *Tickets* tab. You can edit these tickets directly without having to switch to the ticket system.

[#1600]
=== Tab: Orders

Other orders that were also placed by this customer are displayed in the *Orders* tab. All the customer’s orders can be edited here.

[#1610]
=== Tab: Stock

The *Stock* tab displays the *<<stock-management/managing-stocks#, stock data>>* for all of the items that are included in the order.  All of the functions of the *Stock* menu are available in this tab with the exception of the filter functions. You can view stocks and configure them as needed.

[#1620]
=== Tab: Reorder

Select the order items for a reorder in the *Reorder* tab (image 7). Choose whether a reorder is only created for this specific order or whether you want to create a reorder to which items can be added from other orders as well. +
In both cases, the items have to have the same supplier and warehouse. If this does not apply, a separate reorder will be generated for each supplier/warehouse combination.

[NOTE]
.Save the supplier
====
A supplier has to be saved for every variation. Otherwise it is not possible to place a reorder.
====

[#1630]
==== Selecting order items

Proceed as described below to select individual items or all items from an order for the reorder.

[.instruction]
Selecting specific items for the reorder:

. Go to *Orders » Edit orders*.
. Open the required order.
. Click on the *Reorder* tab.
. Select the *variations* you want to reorder.
. Click on *Reorder selected items*. +
→ A general, extendible reorder is generated into which the selected items from the current order as well as those from other orders are transferred if they were selected via this button. The quantity of each variation is displayed in the *Quantity* column.

If you selected specific items for the reorder, the *Reorder all items* button is deactivated and can no longer be selected.

[.instruction]
Selecting all items for a reorder:

. Go to *Orders » Edit orders*.
. Open the required order.
. Click on the *Reorder* tab.
. Click on *Reorder all items*. +
→ A reorder containing all items from this order is generated only for this order. The quantity of each variation is displayed in the *Quantity* column.

[#1640]
==== Placing a reorder

[TIP]
.Information listed under Quantity
====
Listed in the *Quantity* column are the delivered quantity (green numbers), the pending quantity (red numbers) as well as the ordered quantity (white numbers). +
Partial quantities are displayed as *delivered* if they are booked as a partial delivery in the reorder under *Status*. +
====

Place the reorder after you have selected the order items. Proceed as follows:

[.instruction]
Placing a reorder:

. Click on the *shopping cart* (icon:cart-plus[role="green"]) in the *reorder* tab of the order. +
→  The *Reorder* menu opens. Find out which items are included in a reorder by clicking on the *Base* tab and then opening the *Item data* submenu.
. Open the *Basic date* submenu and click on the *gear-wheel icon* (icon:gear[role="darkGrey", stack="long-arrow-right,darkGrey", , stackPosition="lr"]) next to the *Order* option. +
→ The order is placed. The order data are also displayed the *Reorder* tab of the order.

[TIP]
.Adjust the purchase price and quantity
====
Open the *Item data* submenu within the *Base* tab and make changes to the options *Purchase price* and *Quantity* before placing the reorder.
====

For further information about editing a reorder, e.g. booking partial quantities, refer to the *<<stock-management/managing-reorders/working-with-reorders#, Reorders>>* page of the manual.

[#1650]
==== Increasing the number of variations in a reorder

You can increase the quantities of variations in reorders as long as the reorder is still open. This is possible for values where percentages were saved during the *<<item/managing-items#410, distribution>>*. Proceed as follows to increase the quantities of variations:

[.instruction]
Increasing the quantities for variations:

. Select the order for which you want to edit the reorder.
. Open the order's *Reorder* tab.
. Click on *Increase quantities for variations*.
. Select the *reorder ID* and the *item* from the drop-down lists.
. Select the *attribute* and the *value*.
. Enter the *quantity*.
. Click on *Increase quantity*.
. Repeat these steps for every variation for which you want to increase the quantity.

[#1660]
=== Tab: Delivery

*<<orders/managing-orders#300, Delivery orders>>* are created in the *Delivery* tab. There you can see the order's stock units, which were not yet transferred to delivery orders.

[.instruction]
Creating delivery orders manually:

. Go to *Orders » Edit orders*.
. Open the required order.
. Click on the Delivery tab.
. Enter the quantity that should be transferred to the delivery order in the field DelOrdQua (quantity to be transferred to the delivery order). +
→ The quantity entered for *DelOrdQua* must not exceed the quantity entered for *Unass.Quantity* (unassigned quantity).
. Click on the *gear-wheel* icon (icon:gear[role="darkGrey"]) to create the delivery order.

[NOTE]
.Automatically generating delivery orders
====
Click on *Generate delivery orders automatically* to create the delivery orders. They will be created according to the selected settings under *Settings » Orders » Order types » Delivery order* in the Split up orders into delivery orders by drop-down list. All of the order items will be transferred and distributed to delivery orders. You can only use this function if no delivery order exists for the order yet.
====

When creating a delivery order, the stock reservation for the quantity included in the delivery order is transferred from the main order to the delivery order. If delivery orders are created individually and items are still available in the main order, then these items are also reserved.

[TIP]
.Tip: Editing order items in the main order
====
Order items can be added to or deleted from the main order. However, you can only delete order items from the main order if they are not included in the delivery orders. Thus, you can increase or reduce the item quantity included in the main order. However, you should only delete quantities that are not assigned. It is technically possible to delete order items that are already included in a delivery order, but you should avoid doing so.
====

[#1670]
=== Reversing and correcting an invoice

Create a reversal document if you or your customer notice an incorrect information on an invoice and you subsequently want to correct it. Create a new invoice after this.
Reversing an order makes it easy to follow up on changes because the old invoice, the reversal document for the invoice and the new invoice are all available. Use the order status *cancelled* if you want to cancel the entire order. Use the reversal document if you want to edit the order and want to correct some of the information.

[#1680]
==== Setting up a reversal document template

Set up a template for the reversal document first. The fastest way to set up the template is to apply the settings from the default document template or to copy the settings from the invoice document template.  +
The following steps briefly describe how to apply the settings from the default document template.

[.instruction]
Setting up the template:

. Go to *Setup » Client » Select client » Locations » Select location » Documents » Reversal document invoice*.
. Click on the *Transfer* tab.
. Click on *Accept* under *Apply the settings from default document template* (icon:gear[role="darkGrey", stack="long-arrow-right,darkGrey", stackPosition="lr"]).

Since the information in a reversal document is identical with the information included in an invoice, further information on the required settings can be found on the *<<orders/order-documents/generating-an-invoice#, invoice>>* manual page.

[#1690]
==== Correcting an invoice:

You correct an invoice by reversing it. The reversal of an invoice is used for a transparent correction of relevant invoice data and not for the reversal of the order itself. Once the reversal document was created, the order settings are unlocked and can be edited and a new invoice can be created as well.

[.instruction]
Correcting an invoice:

.  Go to *Orders » Edit orders*.
.  Open the order of which you want to reverse the invoice.
.  Click on the *Receipts* tab.
.  Select the option *Reversal document* from the *Create receipt* drop-down list. +
→ A new window with optional settings opens.
. *Save* (icon:save[role="green"]) the settings. +
→ The reversal document is generated and the settings unlocked.
.  Edit the data you want to correct. +
→ For example, add a VAT number.
.  Click on the *Receipts* tab.
.  Select the option *Invoice* from the *Create receipt* drop-down list.  +
→ A new window with optional settings opens.
. *Save* (icon:save[role="green"]) the settings. +
→ The invoice is generated and the settings are locked.

[#1700]
==== Using group functions

plentymarkets offers you a lot of tools to productively manage your order processes. The group functions explained here are among those tools. Carry out one or several processes for one or several orders at the same time. Thus, you avoid a lot of manual inputs and possible input errors.

A practical example illustrates the possible applications of the group functions: A highly demanded item in your shop is temporarily out of stock but you you already received quite a few orders for this particular item. Usually, there is nothing sellers can do about such delivery delays, but the customers have to be informed as soon as possible about the delay. Customers who have already paid in advance are understandably less patient than others.

This task is taken care of in no time at all by using the group functions: Search with the help of the *Item ID* or the *Item name* all orders with the status *ALL < 7* because your process is only relevant for orders which have not outgoing items booked yet. When your system has found all of the orders, click on *group function* and select the option *Email service*. As soon as one of the group functions was selected, a new window with specific settings opens.

In the example, the customer is the recipient of the email. You have to create an email template first. It is not necessary to set a flag, but it is quite useful. Make sure that all required orders are selected by placing a check mark before you run the process by clicking on *Apply*.

[TIP]
.Status >=7
====
 Note that an order status >=7 cannot be set to a lower status without reversing the booking of outgoing items first. For orders with a status from 7 in, you first have to reverse the outgoing items with a group function.
====

You can use the *group function* to carry out processes for several orders at the same time. This means that processes, such as a status change or an email service, will be applied to all selected orders. You can also use the group function to delete specific orders. The group function is particularly recommended if you need to edit a large number of orders and it would be too time consuming to edit each one individually.

An example for using the group function is given below.

[.instruction]
Example for booking the outgoing items with a group function:

. Go to *Orders » Edit orders*.
. Select the *orders* that should have their outgoing items booked with a group function.
. Click on *Group function*.
. Select the option *Book outgoing items*.
. Select the *date* and the *time*. +
→ The current date is selected by default. However, you can change the date if required. You are required to select a date for this group function.
. Click on *Apply* to carry out the procedure.

[IMPORTANT]
.Default settings for editing orders by variable users
====
In order for variable users to be able to open orders, go to the menu *Setup » Orders » Settings* and save default statuses for *returns* and credit notes. No status is saved here as the default setting.
Variable users also need to be given the right to edit orders. Go to *Setup » Settings » User » Accounts* in order to carry out the required settings.
In order for variable users to be able to create *Returns*, *Warranties* and *Repairs*, they have to have the right to edit the three default statuses of these order types. The authorisations are assigned in the user profile of the back end user in the *<<basics/admin-tasks/manage-users#105, Rights » User » Menu visibilities>>*.
====
