= Managing orders
:lang: en
include::{includedir}/_header.adoc[]
:position: 20
:keywords: Order processing, Order, Orders, Order status, Order types, Delivery order, Delivery orders, Manually creating orders, Contacts, Customers, Return, Returns, Credit note, Credit notes, Warranty, Warranties, Repair, Repairs, Multi-order, Multi-orders, Scheduler, Advance order, Order Search, Filter options, Order overview, Edit an order, Edit orders

Orders depict your sales and the business transactions connected to them. Those different business transactions are represented by order types. Progress during order processing is made visible by order status. The following descriptions are designed to show you how to use order types and order status and thus process orders efficiently. All orders are centrally imported into your system and saved in a consistent format. The order overview provides you with access to all important information and enables you to edit orders.

[#100]
== General information on creating orders in plentymarkets

In plentymarkets, an order is automatically created when customers place orders in your online store. Separate orders with different order types are created for business transactions such as <<order-processing/orders/managing-orders#300, Delivery order>>, <<order-processing/orders/managing-orders#400, Return>>, <<order-processing/orders/managing-orders#500, Credit note>>, <<order-processing/orders/managing-orders#600, Warranty>> and <<order-processing/orders/managing-orders#700, Repair>>. These orders are always linked to the main orders. The <<order-processing/orders/managing-orders#1400, Order overview>> allows you to open and edit orders regardless of their origin. For many order types, such as <<order-processing/orders/managing-orders#300, Delivery orders>>, it makes sense to set up <<basics/automating-processes#, Event procedures>> that allow you to automate procedures during order processing. Some examples for using event procedures during order processing are provided in the following chapters. +
Orders that reach you in other ways than via your online store are created <<order-processing/orders/managing-orders#200, manually>> in your plentymarkets system. For example, this is the case for orders placed via phone, email or in the case of a cash sale.

[NOTE]
.Saving basic settings
====
Before processing the first orders in your plentymarkets system, adjust the settings in the *<<order-processing/orders/basic-settings#, Basic settings>>* menu. *Save* those settings once even if you have not changed the default values.
====

[#200]
== Manually creating orders

The following methods are available to manually create an order:

* via the *Contact overview*
* via the *Customer data* of a customer
* via an existing *Order*
* via a *Cash sale*

The necessary procedures for each method are described in the following chapters.

[IMPORTANT]
.Emailing
====
For manually created orders, emails such as order confirmations are not sent automatically to the customer. This is because the system cannot trace the points at which manually created orders have been edited. Therefore, emails to the customers have to be manually sent in the *Mail* tab of the order.
====

[#220]
=== Creating an order in the contact overview

The menu *CRM » Contacts* enables you to create a new order via the contact overview. To create a new order for a contact, proceed as explained below.

[.instruction]
Creating a new order via the contact overview:

. Go to *CRM » Contacts*. +
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *New order* in the context menu to create a new order for the contact. +
→ The tab *New order* opens.
. Click on *Search* to display a list of variations or use the search fields to search for the *Item ID* or further *Item data*.
. Select the variations and corresponding quantities that should be added to the order.
. *Save* the settings. +
→ The order is created and opens in a new tab.

[#230]
=== Creating an order via an existing order

Existing orders contain the icon *New order* in the *Overview* tab. To create a new order via an existing order, proceed as explained below

[.instruction]
Creating a new order via an existing order

. Go to *Orders » Edit orders*. +
→ The *Order overview* opens.
. Click on the order placed by the customer for whom a new order should be created. +
→ The order opens.
. Open the *Overview* tab.
. Open the tab *Customer data* and click on *New order* to create a new order for the customer. +
→ The tab *New order* opens.
. Click on *Search* to display a list of variations or use the search fields to search for the *Item ID* or further *Item data*.
. Select the variations and corresponding quantities that should be added to the order.
. *Save* the settings. +
→ The order is created and opens in a new tab.

[#240]
=== Creating an order for a cash sale

In the menu *CRM » Contacts*, it is possible to process cash sales without assigning them to a specific customers. This is done by creating an order via the customer profile *Barverkauf* (cash sale). This profile is available by default in your plentymarkets system. To create an order for a cash sale, proceed as described below.

[WARNING]
.Payment method and order documents for cash sales
====
When creating an order for a cash sale, make sure to select the correct *Payment method* in the *Order data*. Also, sales orders are not assigned to a specific customer saved in your system. Thus, the necessary *<<order processing/orders/order-documents#, order documents>>*, such as the invoice, have to be manually generated in the *Receipts* tab of the order.
====

[.instruction]
Creating a new order for a cash sale

. Go to *CRM » Contacts*.
. Enter the *ID* 100 in the corresponding search field. +
→ A list of search results opens.
. Select the customer *Barverkauf*. +
→ The customer profile for cash sales is opened. This profile has the *ID* 100.
. Click on *New order* to create a new order for a cash sale. +
→ The tab *New order* opens.
. Click on *Search* to display a list of variations or use the search fields to search for the *Item ID* or further *Item data*.
. Select the variations and corresponding quantities that should be added to the order.
. *Save* the settings. +
→ The order is created and opens in a new tab.

[#300]
== Working with delivery orders

*Delivery orders* enable you to create multiple delivery orders for the items included in the main order. This way, items from the main order can be shipped individually or in parts. For example, delivery orders allow you to immediately ship items that are in stock and ship unavailable items that still have to be ordered later. Delivery orders can be shipped using one or several shipping providers. +
You can create delivery orders *manually*, *automatically* or using an *event procedure*.

[IMPORTANT]
.Common order status
====
The status of the main order is always identical to the status of the delivery order with the lowest status.
For example, if an order in status *5.0* has two delivery orders, of which one is in status *6.5*. the status of the main order is not changed to *6.5* until the second delivery order has also moved to status *6.5*.
====

[#310]
=== Characteristics of delivery orders

In general, delivery orders have the following characteristics:

* It is *not* possible to modify the item quantities included in a delivery order after the delivery order has been created.
* The *price* and *weight* of a variation are transferred to the delivery order from the main order.
* *Address label*, *Delivery note*, *Pro forma invoice* and *Entry certificate (Gelangensbestätigung)* can be generated in the *Receipts* tab of the respective delivery order.
* The *invoice* and all other order documents are generated centrally in the main order.
* Once a delivery order is generated, the stock that is reserved for the item quantities of the delivery order is transferred from the main order to the delivery order.

[#320]
=== Carrying out basic settings for delivery orders

[WARNING]
.Assigning a warehouse for each variation
====
To use delivery orders, you must select the option *b) a warehouse can be assigned for each stock unit* for the *Assignment of warehouses* in the menu *<<order-processing/orders/basic-settings#, System » Orders » Settings>>*.
====

Before working with delivery orders, go to *System » Orders » Order types » Delivery order* to select an option for splitting up main orders into delivery orders.

[instruction]
.Selecting an option for splitting up orders into delivery orders

. Go to *System » Orders » Order types » Delivery order*.
. Carry out the settings according to <<table-order-types-delivery-order-options>>.
. *Save* the settings.

[[table-order-types-delivery-order-options]]
.Options for splitting up orders into delivery orders
[cols="1,3"]
|====
|Setting |Explanation

2+|*Split up orders into delivery orders by*
|*Off*
|Orders are not split up into delivery orders. +
*_Note_*: If this option is activated, delivery orders can only be created manually. Automatically creating delivery orders or using event procedures to create delivery orders is not possible with this setting.

|*Warehouse*
|The delivery orders are created according to the different *Warehouses* of the items included in the main order.

|*Shipping profile*
|The delivery orders are created according to the different *Shipping profiles* of the items included in the main order.

|*Warehouse and shipping profile*
|The delivery orders are created according to the different *Warehouses and shipping profiles* of the items included in the main order.

|*Warehouse stock and net stock*
|The delivery orders are created according to the different *Warehouse stock and net stock* of the items included in the main order.
|====

[#330]
=== Manually creating delivery orders

If necessary, you can manually create delivery orders via the main order. With this method, you need to select the variations and the corresponding quantities individually for each delivery order.

[NOTE]
.Creating delivery orders for all items in the main order
====
We recommend creating delivery orders for *all* items included in the main order. One or several items remaining in the main order without being assigned to a delivery order may cause problems in your plentymarkets system.

In addition, the quantity you indicate for *DelOrdQua* (quantity to be transferred to the delivery order) must not exceed the quantity indicated for *Unass.Quantity* (unassigned quantity).
====

[.instruction]
Manually creating delivery orders:

. Go to *Orders » Edit orders*.
. Open the order for which delivery orders should be generated.
. Open the tab *Delivery*.
. Enter the *Quantity* that should be transferred to the delivery order in the field *DelOrdQua* (quantity to be transferred to the delivery order).
. Click on the *gear-wheel icon* to create the delivery order. +
→ The delivery order is created.
. Repeat the process to create further delivery orders.

[#340]
=== Automatically creating delivery orders

[NOTE]
.Requirement for automatically creating delivery orders
====
This function can only be used if no delivery orders have been created yet for the main order.
====

When automatically creating delivery orders, the criteria for splitting up orders into delivery orders previously described in <<table-order-types-delivery-order-options>> apply. Thus, the items and quantities to be included in the delivery orders do not have to be selected manually. Instead, the system applies the selected option and automatically transfers the items and quantities from the main order to the delivery orders.

[.instruction]
Automatically creating delivery orders

. Go to *Orders » Edit orders*
. Open the order for which delivery orders should be generated.
. Open the tab *Delivery*.
. Click on *Generate delivery orders automatically*.
→ The delivery orders are created.

[#350]
=== Creating delivery orders via an event procedure

An ideal way to create delivery orders in your plentymarkets system is using an event procedure. This way, you can determine when and how delivery orders are created from a main order. Below, three examples for creating delivery orders via an event procedure are described.

According to your particular needs, set up one or all of the following event procedures described below and carry out the described settings.

==== Example A: Event procedure "Create delivery order when order is received"

Use the following settings if you want delivery orders to be generated as soon as a new order enters your plentymarkets system. +

Since this event procedure comes into effect directly upon reception of a new order, the status of the main order is not taken into consideration. Thus, delivery orders will also be created for main orders that are in status *3.0* (or *1.0* if you work with auction platforms such as eBay) and will adopt the status of the main order.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » Orders » Events*.
. Click on *Add event procedure*.
→ The window *Create new event procedure* opens.
. Enter a distinct *Name* for the event procedure.
. Select the *Event* according to <<table-event-procedure-delivery-order-when-new-order>>.
. *Save* the settings.
. Carry out the settings according to <<table-event-procedure-delivery-order-when-new-order>>.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[table-event-procedure-delivery-order-when-new-order]]
.Options for the event procedure "Create delivery order when order is received"
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*New order*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Order warehouse*
|*Multiple warehouses per order*

|*Procedure*
|*Order > Generate delivery orders*
|

|====

==== Example B: Event procedure "Create delivery order when order changes to status 5"

Use the following settings if you want delivery orders to be created as soon as an order changes to status 5. +

When working with this event procedure, you must not make any changes to the main order at all. Otherwise, the total item quantities included in the delivery orders does not match the item quantity included in the main order.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » Orders » Events*.
. Click on *Add event procedure*.
→ The window *Create new event procedure* opens.
. Enter a distinct *Name* for the event procedure.
. Select the *Event* according to <<table-event-procedure-delivery-order-status-5>>.
. *Save* the settings.
. Carry out the settings according to <<table-event-procedure-delivery-order-status-5>>.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[table-event-procedure-delivery-order-status-5]]
.Options for the event procedure "Create delivery order when order changes to status 5"
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order change > Status change*
|*Cleared for shipping*

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Order warehouse*
|*Multiple warehouses per order*

|*Procedure*
|*Order > Generate delivery orders*
|

|====

==== Example C: Event procedure "Create delivery order when generating an invoice"

Use the following settings if you want delivery orders to be created as soon as an invoice is generated for the main order. This method allows you to edit the main order as necessary until an invoice is created and the order is cleared for shipping.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » Orders » Events*.
. Click on *Add event procedure*.
→ The window *Create new event procedure* opens.
. Enter a distinct *Name* for the event procedure.
. Select the *Event* according to <<table-event-procedure-invoice-generated>>.
. *Save* the settings.
. Carry out the settings according to <<table-event-procedure-invoice-generated>>.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[table-event-procedure-delivery-order-invoice-generated]]
.Options for the event procedure "Create delivery order when generating an invoice"
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Documents > Invoice generated*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Order warehouse*
|*Multiple warehouses per order*

|*Procedure*
|*Order > Generate delivery orders*
|

|====

[#360]
=== Editing main orders and delivery orders

[NOTE]
.User rights required for opening main orders
====
To open main orders, variable users, variable users must be *<<basics/admin-tasks/manage-users#100, authorised>>* to view all warehouses linked to the delivery orders of the main order. Thus, check the settings in the *System » Settings » User » Accounts » Tab: Right » Tab: Visibility* menu.
====

If you wish to delete a main order, the respective delivery orders have to be deleted first. Delivery orders can be deleted individually or via the group function in the order search. The main order can only be deleted after the delivery orders have been deleted.

Further variations can be added to or deleted from the main order. However, only variations that are not included in delivery orders can be deleted from the main order. Thus, you can increase or reduce the item quantity included in the main order, but you should only delete quantities that are not assigned to delivery orders.

It is technically possible to delete variations that are already assigned to delivery orders. However, this should be avoided to avoid problems with your plentymarkets system.

[#400]
== Working with return orders

The order type *Return* depicts the process of receiving returned goods. You and your staff can create return orders manually. In addition, you can allow customers in your online store to register returns in the *My account* area. Creating a return does not book the returned items back into your stock, regardless of how a return order is created in your system. The returned items are registered first. Then, you can examine the items and decide whether they should be booked back into the stock or if further steps, such as a repair, are necessary. Return orders are subordinate orders because they are always linked to a main order or to a warranty.
Before returns can be registered in your system, you have to set up reasons for returns and item statuses for returned items. The reasons for return can later be used to determine whether a particular item has been returned exceptionally often for the same reason. The item statuses for returned items allow you to indicate the state of the item upon receipt of the return delivery. This way, you can decide on how to proceed with the item.

[NOTE]
.Standard status for return orders
====
In plentymarkets, the status *9* is assigned to each return by default. However, you can change the standard status according to your requirements in the *<<order-processing/orders/basic-settings#, System » Orders » Settings>>* menu by selecting another *Standard status for return*.
====

[#410]
=== Creating reasons for returns

In plentymarkets, you can create up to 20 reasons for returns. When registering returns, you can choose a reason for each returned item.

[.instruction]
Creating reasons for returns:

. Go to *System » Orders » Order types » Return*.
. Enter the desired reasons for return.
. *Save* the settings.

If you allow customers to *<<omni-channel/online-store/setting-up-clients/my-account#_configuration#, register returns themselves>>* in the *My account* area of the online store, the return reasons will be displayed as a list for the customers to choose from. If the customer does not select any of the return reasons, the first reason for return will be used by default.

[#420]
=== Creating statuses for returned items

You can create up to 12 statuses for returned items. Use these statuses to indicate the state of returned items or to make the progress made with processing returned items visible. The item statuses are available in the *Overview* tab in a return order. Create the necessary statuses according to your requirements to depict the progress.

[.instruction]
Creating statuses for returned items:

. Go to *System » Orders » Order types » Return*.
. Enter the desired statuses that should be assigned to returned items.
. *Save* the settings.

[#440]
=== Creating and editing a return

You can either manually create a return once you receive returned goods, or you can allow your customers to register returns directly in the *My account* area of the online store. After the return has been registered, more options for editing become available in your plentymarkets system. For example, the status of returned items can only be entered after registration of the return delivery.

==== Creating a return

[.instruction]
Creating a return:

. Go to *Orders » Edit orders*.
. Open the order or the warranty for which a return should be created.
. In the *Overview* tab, click on *Return* and select the option *create*. +
→ A window for creating the return opens.
. Carry out the settings according to <<table-settings-return>>.
. *Save* the settings.
→ The return is created and opened in a new tab.

[[table-settings-return]]
.Options for creating a return
[cols="1,3"]
|====
|Setting |Explanation

2+|*Settings*

|*Status*
|Select a status for the return. The standard status defined in the *<<order-processing/orders/basic-settings#, System » Orders » Settings* menu is displayed here by default.

|*Person responsible*
|Select an owner to be assigned to the return. Use this option if you want a specific owner to be responsible for the return. Selecting an owner is optional.

|*Package code of the return*
|Enter the package code of the return delivery.

2+|*Item*

|*Use reason for all items*
|Select a reason for return to be applied to all returned items from the drop-down menu. +
If a reason is selected here, it has priority over all reasons for returns assigned to individual items.

|*Accept*
|Select the items to be included in the return.

|*Quantity*
|Select the item quantity to be included in the return.

|*Reason for return*
|Select an individual reason for return from the drop-down menu.

|*Item*
|Change the item name, if necessary.
|====

After having created a return, you can indicate an *item status* in the *Stock units* tab of the return

[#450]
=== Creating a return slip

You can include a return slip in every shipment of items sent to your customers. In this case, the return slip should contain blank fields for the reasons for return. Alternatively, you can allow your customers to fill out the return slip in the *My account* area of the online store and print it after indicating the return reasons so that it can be included in the return delivery.
Before generating return slips, the document template *<<order-processing/orders/order-documents/generating-return-slips#, Return slip* in the menu *<<order-processing/orders/order-documents#, System » Client » Select client » Locations » Select location » Documents » Return label>>* has to be set up.

[TIP]
.Displaying reasons for returns on the document template
====
To include a blank return slip in every shipment regardless whether items will be returned or not, generate a return slip directly in the main order. You can also allow your customers to indicate the reasons for return in the *My account* area of the online store so that the complete return slip can be printed including the reasons for return. No matter which of these methods you use to provide your customers with a return slip, the column including the return reasons has to be placed below the list of items.
====

Check the list of returned items. If necessary, change data, such as the item quantity, before generating a return slip in the *Receipts* tab of the return order.

[.instruction]
Manually generating a return slip:

. Open the return order and open the *Receipts* tab.
. In the drop-down-list *Create receipt*, select the option *Return label*. +
→ A new window opens.
. Carry out the settings for the return slip.
. *Save* the settings to generate the return slip.

[TIP]
.Automatically generating return slips
====
Set up an event procedure that automatically generates return slips. If you select the event *New return (by customer)* and filter by *Client (store)*, blank return slips are generated with each incoming return and only have to be provided to the customer for downloading.
====

[#460]
=== Reversing stock

Once returned items reach you, you can partly or completely reverse stock accordingly. Alternatively, it is possible to completely reset the outgoing items that have been booked while processing the main order.

[.instruction]
Reversing stock:

. Go to *Orders » Edit orders*.
. For the filter *Type*, select the option *Return*.
. Click on *Search*. +
→ The return orders are listed.
. Open the return for which stock should be reversed.
. Open the *Settings* tab.
. Click on *Add items to stock* next to the *Stock* option. +
→ A new window opens.
. Carry out the settings according to <<table-reversing-stock-return>>.
. *Save* the settings.

[NOTE]
.Reversing stock for returns belonging to orders including delivery orders
====
The procedure for reversing stock is the same for returns belonging to orders that include delivery orders. The editing window displayed during the stock reversal shows whether there are delivery orders.
====

[[table-reversing-stock-return]]
.Options for reversing stock
[cols="1,3"]
|====
|Setting |Explanation

|*Reset outgoing items completely*
|Resets outgoing items completely. The date on which outgoing items were booked is deleted as well.

2+|*Reverse stock*

|*Select entire quantity*
|Transfers the entire quantity of items included in the order to the column *Reverse*.

|*Deselect entire quantity*
|Sets the item quantities in the column *Reversed* to 0.

|*Reverse*
|If items should only be partly booked, manually enter the item quantities that should be booked here.

|*Warehouse*
|Select the warehouse into which the items should be booked.

|*Storage location*
|Select the storage location into which the items should be booked.

|*Quantity in the order*
|Displays the item quantity included in the order.

|*Reversed*
|Displays the item quantities that have already been booked.

|*Batch*
|Displays the batch number of the item.

|*BBF*
|Displays the best before date of the variation.

|*ID*
|Displays the ID of the item.

|*Item*
|Displays the item name.
|====

[NOTE]
.Incoming items from returns
====
An overview of all incoming items for which returns have already been announced is available in the menu *<<stock-management/managing-reorders/managing-backlog-lists#400, Stock » Returns » Supply>>*.
====

[#500]
== Working with credit note orders

Credit note orders are used for reimbursing your customers with a certain amount. This can be the case when processing a <<order-processing/orders/managing-orders#400, return order>>. A credit note in plentymarkets does not represent a reverse invoice but a refund. Credit notes orders are generated from an existing main order in the menu *Orders » Edit orders*. A credit note order is thus always linked to a main order. The credit notes generated in a credit note order are included in your financial accounting such as the *DATEV* export.

[#510]
=== Setting a standard status for credit notes

Before creating credit note orders, go to *<<order-processing/orders/basic-settings#, System » Orders » Settings>>* and check the standard status for credit notes. Change the standard status if necessary and then save your settings.

[#520]
=== Creating a credit note order

A credit note order is always linked to an order that already exists in your plentymarkets system. Thus, open a main order first before creating a credit note order.

[TIP]
.Creating a credit note order in the main order or in a return order
====
If a customer has already paid for an order and decides against the purchase before you have shipped the goods and booked outgoing items, we recommend generating a credit note including all order items in the main order and to cancel the original main order.

In case payment, outgoing items and delivery have already taken place and a <<order-processing/orders/managing-orders#400, return order>> or a <<order-processing/orders/managing-orders#700, repair>> is created, the credit note order is generated directly in the corresponding return order or repair.
====

[.instruction]
Opening an order:

. Go to *Orders » Edit orders*.
. Open the order for which a credit note order should be created. +
→ The order opens in a separate tab.

By selecting the option *Credit note: create* in the *Overview* tab, a new credit note order is created in plentymarkets.

[.instruction]
Creating a credit note order:

. Open the *Overview* tab of the order for which a credit note order should be created.
. Click on the *Credit note* drop-down list and then select the option *create*. +
→ The credit note order opens in a separate tab.

In the *Edit* tab of the credit note order, you can change the options for the items included in the credit note order. You can remove items that should not be included in the credit note order. It is also possible to change the *quantity* of an order item in the credit note order. Options that can be changed are displayed as text fields, drop-down lists or text links. On the right-hand side, the icons *Stock* and *Create reorder* are availabe. The *Delete* icon removes the item from the credit note order.

If a credit note order already exists for an order, there will be a note on the right-hand side of the *Overview* tab notifying you that there is a *Credit note available*. In addition, the credit note order is linked in the *Overview* tab and can be found by using the *Credit note / search* drop-down list.

[#530]
=== Generating a credit note

[NOTE]
.Setting up a document template
====
Before generating credit notes, you have to set up the <<order-processing/orders/order-documents/generating-credit-notes#, document template for credit notes>>. This is done in the menu *<<order-processing/orders/order-documents#, Orders » Fulfilment>>*.
====

After creating a credit note order, a credit note has to be created directly in the credit note order. Check the items included in the credit note order and, if necessary, carry out changes before creating the credit note in the *Receipts* tab of the credit note order.

[.instruction]
Generating a credit note

. Open the credit note order for which a credit note should be generated.
. Select the option *Credit note* from the drop-down list *Create receipt*.
. Click on *Create receipt*.
→ The credit note is generated and opens in a separate tab.

[#540]
=== Reversing and correcting a credit note

Once you have generated the credit note for a credit note order, the credit note order will be locked and can no longer be edited. The lock ensures that tax relevant information cannot be changed. If you discover an error in your credit note after the document was created and you wish to correct it, a *Reversal document refund* has to be generated.

==== Setting up a reversal document template

First set up a template for the reversal document. The fastest way to fill all required settings is to apply the settings from the default document template.  +
The following steps describe how to apply the settings from a default document template.

[.instruction]
Setting up a reversal document template:

. Go to *System » Client » Select client » Locations » Select location » Documents » Refund reversal*.
. Click on the *Transfer* tab.
. Click on *Accept* to *Apply the settings from default document template*.

The information that can be printed on a reversal document is identical with the information included in an invoice. Thus, further information on the required settings can be found on the *<<order-processing/orders/order-documents/generating-an-invoice, invoice>>* manual page.

==== Correcting a credit note

You can correct a credit note only by generating a refund reversal document first. The reversal of a credit note allows you to make the required changes in the credit note order and a new credit note can be generated. Generating a reversal document does not cancel the credit note order itself.

[.instruction]
Correcting a credit note:

. Go to *Orders » Edit orders*.
. Open the order that contains the credit note that you wish to reverse.
. Click on the *Receipts* tab.
. Select the option *Refund reversal* from the *Create receipt* drop-down list.  +
→ A new window with optional settings opens.
. *Save* the settings.  +
→ The reversal document is generated and the settings of the credit note order are unlocked.
. Edit the data that you wish to correct.
. Click on the *Receipts* tab.
. Select the option *Credit note* from the *Create receipt* drop-down list.  +
→ A window with optional settings opens.
. *Save* the settings.  +
→ The credit note document is generated and the settings of the credit note order are locked once again.

[#550]
=== Booking refunds

After creating a credit note, the refund of the credited amount has to be booked in your plentymarkets system. Refunds that are transferred via one of the payment providers you have integrated in your system are booked directly in the *Settings* tab of the credit note order. The *Refund to customer* option is only displayed for the payment methods *PayPal*, *ClickandBuy* and *heidelpay*.

[IMPORTANT]
.Requirement for PayPal
====
*PayPal* does not allow you to enter an amount that is higher than the amount that has been paid with Paypal for the original order.
====

[.instruction]
Booking a refund in the *Settings* tab:

. Go to *Orders » Edit orders*.
. Open the credit note order for which a refund should be booked.
. Open the *Settings* tab.
. Click on the *payment icon* next to the *Refund* option.
. Check the *Amount* of the refund and adjust it if necessary.
. Click on the *gear-wheel icon* to book the refund.

The refund can also be booked in the *Payment* tab of the credit note order. The *payment* tab shows you all payments and partial payments belonging to the credit note order. Booking a refund in this tab is necessary if the original order has not been paid for via a payment provider integrated in your plentymarkets system.

[.instruction]
Booking a refund in the *Payment* tab:

. Go to *Orders » Edit orders*.
. Open the credit note order for which a refund should be booked.+
. Open the *Payment* tab.
. Enter the *Amount* (Debit) and, if necessary, the *Currency* and the *Designated use*.
. Click on *Book payment*. +
→ The refund is booked and is displayed in the *Payment* tab.

[#560]
=== Reversing stock

If outgoing items included in a main order have already been booked and have to be booked back into the warehouse, stock has to be reversed in the *Settings* tab of the credit note order.

[.instruction]
Reversing stock:

. Go to *Orders » Edit orders*.
. Open the credit note order for which stock should be reversed.
. Click on the *Settings* tab.
. Click on the *reset* link next to the *Outgoing items* option.
. A separate window opens. Select the desired option according to <<table-settings-reverse-stock>>.
. *Save* the settings to carry out the process.

[[table-settings-reverse-stock]]
.Options for reversing stock for credit notes
[cols="1,3"]
|====
|Setting |Explanation

|*Reset outgoing items completely*
|Completely resets the outgoing items. This option also deletes the date of the outgoing items.

|*Reverse stock*
|In this section, items are completely or partially reversed. Outgoing items are *not* reset with this option.

|*Select entire quantity*
|Enters the complete quantity of items into the field *Reverse*.

|*Deselect entire quantity*
|Sets the item quantity listed under *Reverse* to 0.

|*Reverse*
|If reversal should only be carried out for a partial quantity, enter the item quantity that should be reversed.

|*Warehouse*
|Select the warehouse that the item should be booked into.

|*Storage location*
|Select the storage location that the item should be booked into.

|*Quantity in the order*
|Displays the number of items included in the order.

|*Reversed*
|Displays the quantity of items already reversed.

|*ID*
|The item ID

|*Item*
|Item name
|====

[#600]
== Working with warranties

Warranties are quite similar to <<order-processing/orders/managing-orders#400, returns>>. In both cases, the items of an order in *status 7* will be sent back to you. In contrast to a return, customers expect a new delivery or a refund in the form of a <<order-processing/orders/managing-orders#500, credit note>>.

[NOTE]
.Guarantee vs. warranty
====
In contrast to a guarantee voluntarily provided by the seller, the warranty represents the *legal obligation* of the seller to eliminate defects and damages that already exist when the item is delivered to the customer free of charge. Depending on the characteristics of the items and the legislation that applies, customers can have a right to claim a warranty up until 2 to 3 years after the purchase of the item. If damages appear more than 6 months after receipts of the goods, the customer has to prove that they already existed upon delivery of the goods.
====

If the conditions for a warranty apply, you as the seller can decide whether to refund the costs to the customer or exchange it for a new item. Proceed with creating a <<order-processing/orders/managing-orders#500, credit note>> to grant the customer a refund. Create a <<order-processing/orders/managing-orders#600, warranty>> in your plentymarkets system to replace the damaged item. Go to *<<order-processing/orders/basic-settings#, System » Orders » Settings>>* to determine whether the *shipping costs* should be covered in the warranty.

[TIP]
.Warranty settings
====
If you create a warranty directly within an order, the *shipping profile* of the main order is automatically adopted. However, the settings can be changed in the warranty's editing window. For *delivery orders*, the correct warehouse is automatically selected as well. The *payment method* for a warranty can be changed.
====

[#610]
=== Creating a warranty

In general, a warranty is created out of a return order. However, it is also possible to create it out of the original main order.

[TIP]
.Creating a warranty in the main order or in the return order
====
We recommend creating the warranty directly in the main order if the customer finds fault with the ordered items after delivery and you decide against proceeding with a return order.

If you wish to proceed with a return order to examine the damaged items, create a return order first and create the warranty in the return order.
====

[.instruction]
Creating a warranty:

. Go to *Orders » Edit orders*.
. Open the *return* or the original main *order* for which a warranty should be created
. Click on the *Warranty* drop-down list and select *create*. +
→ The window *Warranty for the order* opens.
. Place *check marks* next to the desired items.
. *Save* the settings. +
→ The warranty is created and opens in a separate tab.

[#620]
=== Editing a warranty

Existing warranties are displayed in the order overview. Open the warranty to enter an additional *price* if you decide to replace the damaged item by providing the customer with a similar, but more expensive item. If necessary, the quantities of the items included in the warranty can be changed. Proceed as described below to edit a warranty.

[.instruction]
Editing a warranty:

. Go to *Orders » Edit orders*.
. In the *Filter* tab, select the option *Warranty* as the *Type*.
. Click on *Search*. +
→ Only warranties will be listed.
. Click on the warranty that you want to edit. +
→ The warranty opens and can be edited in the *Edit* tab.

[#630]
=== Completing a warranty

If you decide to replace the faulty item with a more expensive one, you have to generate an invoice within the warranty. In case the customer agrees to a discount on the damaged item instead of proceeding with a return order, create a credit note in the original main order.

Proceed as described below to complete a warranty by replacing items:

[.instruction]
Completing a warranty with a replacement:

. Click on the *Receipts* tab in the warranty.
. Select *Invoice* from the *Create receipt* drop-down list. +
→ A new window opens. Adjust the settings if necessary. +
. *Save* the settings.
→ The invoice is generated and opens in a separate tab.
. Click on the *Settings* tab.
. Click on the *Book outgoing items* icon at the end of the line *Outgoing items*. +
→ The outgoing items are booked and the *status* automatically changes to *[7] Outgoing items booked*.
. Change the status manually to *[10] warranty*.
. *Save* the settings.

[NOTE]
.Booking incoming payments for warranties
====
Incoming payments for warranties only have to be booked if an additional charge has been negotiated with the customer. In this case, book the incoming payment after it has reached you in the *Payment* tab of the warranty.
If the replacement consists of the same item with the same price as in the original main order, the generated invoice will automatically show an amount of 0.00.
====

Proceed as described below to complete a warranty by creating a credit note order and the corresponding receipt.

[.instruction]
Completing a warranty with a credit note:

. Open the main order or the return order for which a credit note should be generated.
. Open the *Overview* tab.
. Click on the *Credit note* drop-down list and select *create*. +
→ The credit note order is created and opens in a separate tab.

All further steps necessary to complete the credit note order are identical to the regular procedure for credit note orders. The further steps to be taken are described in detail in the <<order-processing/orders/managing-orders#500, credit note>> chapter on this manual page.

[#700]
== Working with repairs

In plentymarkets, repairs are represented by a separate order type. Repairs consist of returned items that need to be repaired. Thus, repairs can only be created from <<order-processing/orders/managing-orders#400, returns>>.

[#710]
=== Creating statuses for repairs

Before using repairs in, you can save *statuses* for repairs. With the help of these statuses, the stations that items go through during the repair process can be depicted. This allows you to precisely monitor the progress in your system.

[.instruction]
Creating statuses for repairs:

. Go to *Settings » Sales orders » Sales order types » Repair*
. Enter the *statuses* that you require for processing repairs.
. *Save* the settings.

[#720]
=== Creating conditions for repairs

*Conditions* are used to precisely describe the items themselves, e.g. if an item needs to be repaired or if it is beyond repair.

[.instruction]
Creating conditions for repairs:

. Go to *Settings » Sales orders » Sales order types » Repair*
. Enter the different *conditions* that you will need for assigning stock units.
. *Save* the settings.

[#730]
=== Creating a repair

To create a repair, proceed as follows.

[.instruction]
Creating a repair:

. Go to *Orders » Edit orders*.
. Open the return order for which a repair should be created.
. Open the *Overview* tab.
. Click on the *Repair* drop-down list and select *create*. +
→ A new window opens. Enter the desired *Status* and the *Condition* of the repair. Select the *Items* to be included in the repair. Enter a *Note* if necessary.
. *Save* the settings.
→ The repair is created and opens in a separate tab.

[#740]
=== Editing a repair

Depending on the reasons for return and condition of the items that need repairing, different steps have to be carried out. +
Since repairs constitute a separate order type, you can use the *Overview* tab to proceed with a credit note, a warranty or a return order. The necessary steps for each of these order types such as generating the necessary documents, booking outgoing or incoming items or booking payments are identical to the order types <<working-with-credit-note-orders, credit note>>, <<working-with-warranties, warranty>> and <<working-with-return-orders, return>>.

[#800]
== Working with multi-orders

You can combine unpaid orders in a multi-order. Use the menu *Orders » Edit orders* or the tab *Orders* within a contact to search for such orders with the help of the search filter *Order status*, e.g. by searching for orders in status *[3] Waiting for payment*. Thus, there are two different possibilites for creating multi-orders. Both possibilities are described in the following chapters. With both options, unpaid orders are always combined in a multi-order in the menu *Orders » Multi-orders*. Multi-invoices are then created in the *Receipts* tab of a multi-order.

[#810]
=== Carrying out basic settings for multi-orders

Carry out the basic settings for multi-orders in the *System » Orders » Order types » Multi-order*. In this menu, you define details such as the order types and order statuses for which multi-orders can then be created.

[.instruction]
Carrying out basic settings for multi-orders:

. Go to *System » Orders » Order types » Multi-order*.
. Carry out the settings according to <<table-multi-order-options>>.
. *Save* the settings.

[[table-multi-order-options]]
.Basic settings for multi-orders
[cols="1,3"]
|====
|Setting
|Explanation

|*Order types*
|Select which order types should be available for multi-orders. Multiple selections are possible. Only the listed order types *Order*, *Warranty* and *Repair* can be combined in multi-orders.

|*Item text*
|Select which options are used for the *item text* column of the stock units that belong to a multi-order. Multiple selections are possible. The selected options will be listed separately for each individual order within the multi-order. This ensures that the options can easily be connected to the correct customers and orders.

|*Sort orders by*
|Select how individual orders are sorted within a multi-order. Only one selection is possible. Orders can be sorted by their order ID (*Order ID ascending* or *Order ID descending*) or their date of outgoing items (*Outgoing items ascending* or *Outgoing items descending*).

|*Order status of orders*
|Select the status orders have to be in to be considered for multi-orders. Multiple selections are possible. Depending on your work flow, we recommend creating an individual order status to target specific orders that are intended for multi-orders.

|*Order status of credit notes*
|Select the status credit note orders have to be in to be considered for multi-orders. Multiple selections are possible.
|====

Furthermore, go to *<<order-processing/orders/basic-settings#, System » Orders » Settings>>* and use the option *Standard status for multi-order* to specify which order status should be given to multi-orders when they are generated. The status *[13] Multi-order* is available by default. In addition, select a status for multi credit notes. The status *[14] Multi credit note* is available by default.

[#820]
=== Creating a multi-order per customer class

Some companies may not want to receive an invoice every time one of their employees make a purchase in your online store. Rather, the company prefers one monthly invoice for all of its employees' purchases. Set up a special customer class for this situation. The invoice recipient is specified by saving a customer ID in the customer class. The multi-invoice is generated directly within the corresponding multi-order and sent to this invoice recipient. +

Go to *Orders » Multi-orders* to create a multi-order for a specific customer class and a fixed time period. This way, all unpaid orders belonging to the customer class are combined in one multi-order. Use the Option *Customer ID* in the customer class settings to determine a customer representing the customer class and functioning as the recipient of the multi-invoice. According to your work flow, we recommend creating specific <<crm/managing-contacts#15, customer classes>> for multi-orders.

[.instruction]
Creating a multi-order for a customer class:

. Go to *Orders » Multi-orders*.
. Open the *Generate multi-orders* submenu.
. Select the *Customer class* and an optional *Period*. The time period refers to the date when the order was received.
. Click on the *gear-wheel icon*. +
→ The multi-order is created.

[#830]
=== Creating a multi-order per customer

A customer prefers to pay for multiple orders at the same time once a month instead of paying several separate invoices. +
In this case, go to *CRM » Contacts* to create a multi-order in the contact data. Open a specific contact and click on *New multi-order* in the menu on the left. A multi-order including all unpaid orders of the contact is then automatically created.

[TIP]
.Tip: Check orders
====
Use the tab *Orders* in the contact data to look for unpaid orders to make sure that suitable orders are available for creating a multi-order,
====

[#840]
=== Generating a multi-invoice

This chapter explains how to generate multi-invoices. Multi-invoices can only be generated in the corresponding multi-order. +
The first step consists of setting up a document template for multi-invoices in the *System » Client » Select client » Locations » Select location » Documents » Multi-invoice* menu. In this menu, you can specify detailed settings for the document and you can also save a <<order-processing/orders/order-documents#, document template>> in the form of a PDF file. Customize the template as desired. Default values are already available in the basic settings of the document template. If needed, you can transfer further settings, e.g. from the document template *Invoice* to complete the values. Further information and instructions for setting up the document template are available on the <<order-processing/orders/order-documents#, Order documents>> page of the manual. +
After having set up a document template for multi-invoices, you can generate a multi-invoice in the *Receipts* tab of a multi-order.

[IMPORTANT]
.Incoming payments for multi-orders
====
If a customer pays a multi-invoice and the multi-order is marked as paid, the incoming payment is *not* automatically booked in the separate orders that are combined in the multi-order. Thus, you have to book incoming payments manually in the respective orders.
====

Use the event procedures available in your plentymarkets system to automatically generate a multi-invoice as soon as a multi-order is created. Proceed as follows to set up the event procedure:

[.instruction]
Creating an event procedure for multi-invoices:

. Go to *System » Orders » Events*.
. Click on the *green plus* in the lower left corner to create a new event procedure.
. Enter a name in the editing window, e.g. *Generate multi-invoices*.
. Select *Order generation > New multi-order* as the *Event*.
. *Save* the settings. +
→ The event procedure is created.
. Click on the *green plus* to add a procedure of the procedure type *Documents > Generate multi-invoice*. Within this procedure, you can select when the payment is due and determine an early payment discount.
. Place a check mark next to the option *Active*.
. *Save* the settings.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » Orders » Events*.
. Click on *Add event procedure*.
→ The window *Create new event procedure* opens.
. Enter a distinct *Name* for the event procedure.
. Select the *Event* according to <<table-event-procedure-multi-invoice-automatic>>.
. *Save* the settings.
. Carry out the settings according to <<table-event-procedure-multi-invoice-automatic>>.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[table-event-procedure-multi-invoice-automatic]]
.Event procedure "Automatically generating a multi-invoice"
[cols="1,3"]
|====
|Setting |Selection

|*Event*

|*Order generation > New multi-order*

|*Procedure*

|*Documents > Generate multi-invoice* +

*_Important_*: Within the procedure, you can determine values for *Payment due* and an *Early payment discount*.
|====

[#845]
=== Generating dunning letters for multi-orders

Just like invoices for multi-orders, you can generate dunning letters for multi-orders in the *Receipts* tab of the respective multi-order. Proceed as follows:

[.instruction]
Generating a dunning letter for multi-orders:

. Go to *Orders » Edit Orders*.
. Open the multi-order for which a dunning letter should be generated.
. Open the *Receipts* tab.
. Select the option *Dunning letter* from the drop-down list *Create receipt*.
. Click on *Create receipt*. +
→ The dunning letter is generated and opens in a separate tab.

[#850]
=== Generating a multi credit note

Multi credit notes are genereated in the menu *Orders » Multi-orders*. +
All credit notes for a customer class are combined in a multi credit note. Depending on your workflow, we recommend creating specific <<crm/managing-contacts#15, customer classes>> for multi credit notes.

[.instruction]
Generating a multi credit note for a customer class:

. Go to *Orders » Multi-orders*.
. Open the *Generate multi credit notes* submenu.
. Select the *Customer class* and an optional *Period*. The time period refers to the date when the credit note was received.
. Click on the *gear-wheel icon*. +
→ The multi credit note is generated.

[#900]
== Working with schedulers

The *scheduler order* is a subscription module that has to be booked in the menu *Start » Service Center » Tab: Contract*. This module allows your customers to subscribe to certain items in your online store. The module is <<basics/admin-tasks/plentymarkets-account#contract, **an additional add-on**>> and only visible in your plentymarkets system if you booked this module. In the *System » Orders » Scheduler* menu, you can configure the scheduler module for your online store. After configuring the module, the *Orders » Scheduler » Scheduled orders* menu provides you with an overview of your subscriptions.

[IMPORTANT]
.Not for items with order properties
====
The scheduler module is not working for items with *order properties*.
====

[#910]
=== Carrying out basic settings

First, you carry out the basic settings for the scheduler module.

[.instruction]
Configuring the basic settings:

. Go to *System » Orders » Scheduler*.
. Pay attention to the explanations given in table 1 and carry out the settings as desired.
. *Save* the settings.

<<table-basic-settings-scheduler>> explains the settings in the *System » Orders » Scheduler* menu:

[[table-basic-settings-scheduler]]
.Basic settings for the scheduler module
[cols="1,3"]
|====
|Setting
|Explanation

|*Intervals*
|Select the intervals for the subscription function. Press Ctrl+C or cmd+C for multiple selection. The intervals which you select here will be available for customers in the online store. During the order process, this will allow the customer to select the intervals that they want to receive the item in. In order to have the options displayed in the online store, you have to insert the corresponding template variable (section 4).

|*Number of orders*
|Determines how often the subscription is to be processed. Select all of the options that should be available for customers to choose. Press Ctrl+C or cmd+C for multiple selection. The values which you select here will be available for selection in the online store. During the order process, this will allow the customer to select how often they want to receive the item. In order to have the options displayed in the online store, you have to insert the corresponding template variable.

|*Permitted payment methods*
|Select the payment methods that you want to make available for the subscription function. Press Ctrl+C or cmd+C for multiple selection.

|*Changes to items*
|Select whether changes concerning the order options, e.g. the quantity, should be permitted during the order process.

|*Item number per interval*
|Select which quantity of the item is to be delivered in the interval. This is an optional setting which can be used to compensate for missing items. For example, if an item quantity only suffices for one week, yet the customer selected an interval of two weeks, then you could enter 2 as the item number per interval. Of course, this is assuming that you are certain the customer will agree to receiving the corrected quantity.

|*Minimum runtime*
|Select a minimum runtime for the subscription function. It is only possible to subscribe to the item for this period of time or longer. The minimum runtime is optional.

|*Maximum runtime*
|Select the maximum runtime for a subscription. The maximum runtime is optional.

|*Order referrer of generated orders*
|Determine the order referrer for subscriptions.
|====

[#920]
=== Carrying out settings for subscription items

First, carry out the settings for your subscription items. Integrate the subscription items into your stock. Then activate the subscription function. To do so, proceed as follows.

[IMPORTANT]
.Sales price setting *Subscription Interval* not functional
====
The scheduler does not take into account the option *Subscription Interval* of the sales price. It is possible to create sales prices for different subscription intervals. However, the scheduler ignores all intervals except *None*.
====

[#930]
=== Categorizing subscription items

You have different options for integrating subscription items in your stock. We recommend creating a *<<item/managing-categories#, category>>* for subscription items only and link all items desired to this category. Another option is that you create the items again as *<<item/managing-items#320, item bundles>>* so that they are linked to the main item. This is important for reasons of stock-keeping.

[#940]
=== Activating the subscription function

The subscription function first needs to be activated globally and then separately for each item that you wish to offer as a subscription item. The global activation makes it possible for customers to place subscription orders in general. The activation for individual items defines which items customers are allowed to order as subscriptions. In order to activate the subscription function globally, proceed as described below.

[.instruction]
Globally activating the subscription function:

. Go to **<<omni-channel/online-store/setting-up-clients/my-account#, System » Client » Select client » My Account » Settings>>**.
. Select the setting **activated** for the option **Subscriptions**.
. *Save* the settings.

Now activate the subscription function for each item that the customer should be allowed to order as a subscription.

[.instruction]
Activating the subscription function for individual items:

. Go to **Item » Edit item**.
. Open the item.
. Click on the **<<item/managing-items#40, Gobal>>** tab.
. Select the setting **Yes** for the option **Subscription**.
. *Save* the settings.

[IMPORTANT]
.Deactivating the subscription function
====
Set the global function to **deactivated** and set the function within individual items to **No** if you do not want to use the subscription function anymore. Remove the code from your online store's layout (section 4).
====

[#950]
=== Inserting template variables into the online store layout

Before customers can select the subscription function in the online store, you have to insert the template variables and code into your store's layout.

[.instruction]
Inserting template variables:

. Go to *CMS » Web design » Layout » ItemView » ItemViewSingleItem*.
. Insert the template variables and code (example further below) between *$FormOpenOrder* and *$FormCloseOrder*.
. *Save* the settings.

<<table-template-variables-scheduler>> explains the template variables needed to insert the subscription function into the online store:

[[table-template-variables-scheduler]]
.Template variables for the scheduler module
[cols="1,3"]
|====
|Template variable
|Function

|*$IsSubscriptionItem*
|Returns a boolean value (TRUE or FALSE depending on the item's setting). Use this template variable for an IF query in the layout. This will determine whether or not an item is a subscription item. Otherwise the subscription function will be displayed for all of the items instead of only for those items that are actually subscription items. An example with an IF query can be found underneath the table.

|*$SchedulerDateSelector*
|Inserts a calendar selection box, which customers can use to select the date of the first delivery.

|*$SchedulerInterval*
|Inserts a drop-down list for selecting the interval for the subscription. Here you can select the intervals that were saved in the settings (section 2).

|*$SchedulerRepeating*
|Inserts a drop-down list for selecting the number of deliveries. Here you can select the options for the number of orders that were saved in the settings (section 2).
|====

The following code is an example of how to arrange and name the template variables:

[source,xml]
----
{% if $IsSubscriptionItem %}
<!--  Box Filter -->
<div class="ff01_pagenav" style="margin-top:5px;"<h2Subscription</h2></div>
First delivery: $SchedulerDateSelector<br />
Interval: $SchedulerInterval<br />
Deliveries: $SchedulerRepeating<br />
<!--  End Box Filter -->
{% endif %}

----

[#960]
=== The subscription function displayed in the online store

After you have configured the settings described on this page, subscription items are displayed in your online store. The purchaser can customize the timing of the first delivery, the interval and the number of deliveries before placing the item in the shopping cart. If needed, these settings can be changed during the order process and before the order is sent. The example code mentioned above will be displayed in the online store in the following way:

[#970]
=== Scheduled orders

The overview displays your subscriptions, including detailed information about the customers and orders. Use this menu to search for, edit and delete scheduled orders.

It is also possible to generate an order from the subscription. This is done by clicking on the *gear-wheel* icon.
The icon is displayed at the far right of each line. You have to generate an order from the subscription. Otherwise the order will not be included in the order overview. This is carried out manually.

[#980]
=== Searching for scheduled orders

In the *Filter* tab, you can search for scheduled orders according to specific filter criteria. The scheduler data that was found will then be displayed in the *Scheduler* tab.

[.instruction]
Searching for scheduled orders:

. Go to *Orders » Scheduler » Scheduled orders*.
. Enter the search term in the search field or set the desired filter options in the drop-down lists. The filter options are described in <<table-filter-scheduler-search>>.
. Click on *Search*. +
→ The scheduled orders that correspond to the search criteria entered will be listed.

[[table-filter-scheduler-search]]
.Searching for scheduled orders
[cols="1,3"]
|====
|Setting |Explanation

|*Search*
|Click on this button to carry out the search. The scheduled orders that were found will then be displayed in the **Scheduler** tab.

|*Reset*
|Resets the filter criteria that was entered.

|*Scheduler ID*
|Each scheduler data record automatically receives a consecutive and exclusive ID. The ID is always a real number (e.g. "00521" or "ADF8354" are invalid).

|*Customer ID*
|Search by the customer ID.

|*Item ID*
|Search by the item ID of the item that is included in the scheduled order.

|*Customer name*
|Search by the name of the customer. You can search by the customer's first and last name.

|*Start*
|Select which starting dates you want to search for. You can select: +
*All* = No filter +
*No starting date* = Searches for scheduled orders that do not have a starting date. +
*Starting date in the future* = Searches for scheduled orders that have a starting date in the future. +
*Starting date in the past* = Searches for scheduled orders that have a starting date in the past. +
*In the last 7/14/30/80/90 days* = Searches for scheduled orders that have a starting date that is a certain number of days in the past.

|*End*
|Select which ending dates you want to search for. You can select: +
*All* = No filter +
*No ending date* = Searches for scheduled orders that do not have an ending date. +
*Ending date in the future* = Searches for scheduled orders that have an ending date in the future. +
*In the future or no ending date* = Searches for scheduled orders that do not have an ending date or that have an ending date in the future. +
*Ending date in the past* = Searches for scheduled orders that have an ending date in the past. +
*In the last 7/14/30/80/90 days* = Searches for scheduled orders that have an ending date that is a certain number of days in the past.

|*Run*
|Select one of the following filter options for the run: +
*Never* = Searches for scheduled orders in which the run was not carried out. +
*This month* = Searches for scheduled orders in which the run was carried out this month. +
*Last month* = Searches for scheduled orders in which the run was carried out last month.

|*Active*
|Choose between the options *Yes*, *No* and *ALL* if you want to search for all scheduled orders.

|*Owner*
|Select a user to search for the scheduled orders of this owner. The owner must be saved within the customer data.

|*Referrer*
|Select the scheduled order's referrer.

|*Interval*
|You can choose between the option *All* and the intervals that were selected under *System » Orders » Scheduler*.

|*IBAN*
|If you select the setting *Available*, then you will only search for scheduled orders that belong to customers who have an IBAN saved in their *bank data*.

|*Direct debit mandate*
|Searches for customers who *have given* you a SEPA direct debit mandate or for those who have not given you this form.

|*Client (store)*
|Select a client to only display scheduled orders that correspond to this client. +
*Important:* Variable users can only select those clients that they have a right to access. Variable users are given rights under *<<basics/admin-tasks/manage-users#, System » Settings » User » Accounts » Tab: Right>>*.
|====

[#990]
=== Manually creating a scheduled order

Proceed as described below to manually create a scheduled order.

[.instruction]
Manually creating a scheduled order:

. Click on the *gear-wheel icon* on the right in the line of a scheduled order. +
→ The *Create new scheduled order* window will open.
. Click on the *Create order* button. +
→ You will receive a success message once the order was created.

Once a scheduled order was manually started, you will see the date of the last run within the *Last run* column.

An order will be created in the *Orders* menu.

[TIP]
.Tip: The operation could not be carried out successfully: Check the settings
====
Check the settings of the subscription. One possible error could be, e.g. that the starting date is in the future. In this case, adjust the starting date accordingly. Another possible error could be that the payment method was not included in the scheduler's settings. Check the scheduler's settings. You will also receive an error message if an order was already generated for this scheduled order.
====

=== Editing an existing subscription

[.instruction]
Editing a subscription:

. Go to **Orders » Scheduler » Scheduled orders**.
. Find the scheduled order that you want to edit and click on its *pencil* icon. +
→ The scheduled order will open and can be edited.

The editing window is divided into 3 tabs. The settings that are found in the *Base* tab are described in <<table-settings-tab-base>>. The settings in the *Item* tab relate to the subscribed items. The *Customer* tab includes information about the customer from the *Customers* menu.

==== Tab: Base

The following parameters of a subscription are displayed in the *Base* tab:

[[table-settings-tab-base]]
.Settings in the *Base* tab of a scheduler
[cols="1,3"]
|====
|Setting |Explanation

|*Invoice address*
|The address that the invoice is sent to.

|*Change customer*
|Click to change the customer. Either enter the customer ID or the name of the customer. You will see matching results once you have entered at least 3 characters.

|*Delivery address*
|Contains the delivery address if it was saved in the customer data.

|*Change the delivery address*
|If delivery addresses were saved for the customer, then they can be selected here. However, a new delivery address can not be created.

|*Scheduler ID*
|The system automatically assigns the subscription ID. It can not be edited.

|*Active*
|The scheduled order is activated if a check mark has been placed. +
Remove the check mark and *Save* the settings to deactivate the scheduled order.

|*Number of orders*
|The values that you saved in the *Settings* menu are displayed. You can change the number of shipments. +
The number of sent orders is displayed to the left of the forward slash.

|*Start*; +
*End*
|Specify the duration of the scheduled order by selecting a starting and ending date. +
A calendar opens to help you configure the settings. The date that is initially displayed can thus be changed.

|*Start item*; +
*End item*
|Searches for scheduled orders with a starting and ending date that matches the selected options, e.g. starting date in the last seven days.

|*Last run*
|Displays the date of the last order. In other words, this is the date when the most recent order was sent. +
You can use this date to determine when the next scheduled order should be sent. This is useful if you want to manually send the order.

|*Interval*
|You can change the interval for this scheduled order as needed. The values that were saved in the **Settings** menu are available to select here.

|*Coupon*
|You can see whether or not a coupon was used for the scheduled order.

|*Currency*
|The currency for the scheduled order. Select a different currency from the drop-down list if needed.

|*Shipping costs*
|The shipping costs. Enter a different amount if needed.

|**Shipping method**
|The shipping method for the scheduled order. Select a different shipping method from the drop-down list if needed.

|*Payment method*
|The payment method for the scheduled order. Select a different payment method from the drop-down list if needed.

|*Client (store)*
|The client (store) for the scheduled order. Select a different client (store) from the drop-down list if needed. +
The client that is selected determines which <<order-processing/orders/accounting#, VAT rates>> will be available in the *Item* tab.

|*Owner*
|The owner for the scheduled order. Select a different person from the drop-down list if needed.

|**Referrer**
|The referrer for the scheduled order. Select a different referrer from the drop-down list if needed.
|====

==== Tab: Item

The *Item* tab is divided into two submenus. In the *Scheduler item* tab, you can see the items that are currently included in the scheduled order. Here you can edit the *quantity*, *price* and other information about the items. The *VAT rates* that are available here depend on the client selected in the *Base* tab. You can choose from the VAT rates that were saved for the client under <<order-processing/orders/_accounting#, System » Client » Select client » Locations » Select location » Accounting>>.

If you change the item description within the *Item description* field, then this change will not go into effect for the actual item itself.

The *Add item* tab displays the *overview of items*. This lets you select from your entire catalog of items.

The *Start* and *End* options are nearly identical to those for the scheduled order. The only difference is that the duration can be chosen separately for each individual item. This makes it possible, e.g. to offer different items at different times or to offer one item after another in a subscription.

==== Tab: Customer

By clicking the tab *Customer* the contact data record opens within the <<crm/managing-contacts#, CRM » Contacts>> menu.

[#1000]
=== Creating a new subscription

Proceed as follows to create a new subscription.

[.instruction]
Creating a new subscription:

. Go to *Orders » Scheduler » Scheduled orders*.
. Click on *New*.
. Pay attention to the explanations given in <<table-settings-tab-base>> and carry out the settings as desired.
. Click on the save icon to save the settings. +
→ The new subscription will be created.

=== Running scheduled orders

*Upcoming subscription orders* are displayed in this menu. Here, you can start multiple subscription sales orders at one time. This is especially helpful if you need to edit and monitor several subscriptions.

After clicking on one of the two *start run* icons, you will be able to see which *subscription IDs* have *orders* pending for them.

[.instruction]
Selecting and starting the run of scheduled orders

.  Select **filter options** or leave each setting on **ALL** if you would like to have all of the currently pending subscription sales orders be displayed.
.  You can start the **run** function by clicking on one of the icons. +
→ The subscription orders will be created. Afterwards, they will no longer be displayed in the run menu.

[#1100]
== Working with advance orders

Advance orders are an important tool in the marketing mix for electronic commerce. Usually, items can be ordered at a reduced, introductory price before they actually become available. This presents an unusual case for merchandise management, since items that are not yet available can not have any stock.

Advance orders are very easy to set up in plentymarkets. There is even a special order type, *advance order*, which you can use with manually created orders.

You need to save settings for the release date and the item availability before you will be able to receive advance orders from the online store. Carry out the item settings as described below.

[IMPORTANT]
.Manual order input
====
The order type *advance order* can be selected when manually entering orders. The current version does not support the automatic selection of this order type for orders made in the online store.
====

[#1110]
=== Release date

You can find the option *Release date* within the area for editing items, listed in the *Available* tab. Here, you can use the calendar to enter the date that the item will become available (this entry is also possible via dynamic import). To do so, proceed as follows.

[.instruction]
Entering the release date:

. Go to *Item » Edit item*.
. Open the item that you want to allow your customers to order in advance.
. Click on the *Available* tab.
. Enter the date when the item becomes available into the *Release date* field.
. *Save* the settings.

Next, make sure that this date will also be displayed to your customers. To do so, proceed as follows.

[.instruction]
Displaying the release date in the online store:

. Go to *CMS » Web design » Folder: Layout » Folder: ItemView*.
. Open the *ItemViewSingleItem* template.
. Insert the template variable *$ReleaseDate*.
. *Save* the settings.

[#1120]
=== Item availability

Another requirement is correctly setting the *item availability*. To do so, proceed as follows.

[.instruction]
Setting up item availability for advance orders:

. Go to *Item » Edit item*.
. Open the item that you want to allow your customers to order in advance.
. Click on the *Settings* tab.
. Select *No limitation* for the *Limitation* option. +
→ The item can now be sold without real stock, therefore it can also be ordered in advance.

[TIP]
.Maximum order quantity
====
If you are worried that other online sellers might misuse your advance orders to completely buy out your item at a reduced price, then enter a value for the option *Maximum order quantity* within the *Available* tab. If you enter the value *1* there, then the item can only be purchased once per order. If you set the maximum order quantity to *0*, the item will be sold without limitation.
====

[#1130]
=== Setting up a payment request for advance orders

The *shipping date* option usually remains unused for normal orders. However, it can be helpful to use this option for advance orders. If an item will be released in the future, then the release date will be saved as the order's shipping date since deliveries can only take place once the item is released. You can use the shipping date as a filter option in the order search and in the procedure manager.

Advance orders are usually generated some time before an item appears and are not paid for by the customers at the time when they are ordered. As such, it makes sense to inform customers about the upcoming shipment and request them to make a payment. Use the *procedure manager* to automate this process. A few days before shipping takes place, the procedure manager will automatically send the customers a reminder email stating your bank details and providing a link to the checkout. Proceed as described below to set up the automatic payment request.

[.instruction]
Setting up a payment request via email:

. Create an appropriate *<<crm/sending-emails#, email template>>*.
. Go to *System » Orders » Procedures*.
. Open the *New procedure* tab.
. Enter a *name* into the *Settings* tab.
. Select a time from the drop-down list next to the option *Execute every day at*.
. Place a check mark next to the option *Active* to activate the procedure.
. Click on the *Filter* tab.
. Set the status to *[3]*.
. For the option *Shipped on*, e.g. select the option *in 4 days*.
. Click on the *Procedure* tab.
. Select the previously created email template for the option *Send email template*. This template will then automatically be sent to the customer with this procedure.
. Click on the *save icon* to save the procedure.

[#1200]
== Using the order status

**System » Orders » Order status**

An order is always in one of the statuses. The order status changes automatically with certain events (e.g. order processing, incoming payment, invoice printing), however, it can also be changed manually. In general, the order status helps you search for specific orders within the *Orders* menu.

[#1210]
===  Default order statuses

The following status entries are available by default in your plentymarkets system.

[cols=""]
|====
a|
* *[1]* Incomplete data
* *[1.1]* Waiting for payment & activation
* *[1.2]* Activated, waiting for payment

* *[2]* Waiting for activation

* *[3]* Waiting for payment
* *[3.2]* In waiting position
* *[3.3]* Ready for shipping; waiting for payment
* *[3.4]* Dunning letter sent

* *[4]* In preparation for shipping

* *[5]* Cleared for shipping
* *[5.1]* External processing
* *[6]* Currently being shipped

* *[7]* Outgoing items booked
* *[7.1]* Order exported

* *[8]* Canceled
* *[8.1]* Canceled by customer

* *[9]* Return
* *[9.1]* Items are checked
* *[9.2]* Waiting for return from wholesale dealer
* *[9.3]* Warranty initiated
* *[9.4]* Exchange initiated
* *[9.5]* Credit note created

* *[10]* Warranty

* *[11]* Credit note

|====

[TIP]
.Pay attention to the user rights
====
Please note that the drop-down lists only contains those *stores* and *order statuses* that the current user was given rights to.
====

When saving an order, the order status is assigned automatically. If the payment method "cash in advance" was selected, then status *[3]* is assigned to the order. For cash on delivery, status *[5]* is assigned. If an *<<order-processing/payment#, incoming payment>>* was booked for an order with the payment method "cash in advance", the status will change either to *[4]* or to *[5]*.

If orders should only be cleared for shipping when enough stock is available, then go to *<<order-processing/orders/basic-settings#, System » Orders » Settings>>* and set the option *Status changes to 4 instead of 5 if stock is missing* to *YES*. That way, orders remain in status *[4]* until enough stock was booked. The advantage of this is that delivery notes and invoices are only printed for orders that can really be processed.

It is especially helpful to work with order statuses in the menu *<<order-processing/orders/fulfilment#, Orders » Fulfilment>>*. Among other things, invoices are created there. Orders are filtered by their status.

*Possible procedure:* Create invoices of all orders in status *[5]* and change their status to *[6]*. Following this step, shipping labels can be created for all orders in status *[6]*.

The order statuses *[5.1]* and *[7.1]* are used for exchanging data with applications of third party providers.

*Status 5.1:* If invoicing and fulfilment are not carried out with plentymarkets, but using an external solution, then all orders have to be set to the status *[5.1]* before exporting them.

*Status 7.1:* If an export is to be carried out at the end of the order processing (in status *[7]*), then status *[7.1]* should be set.

[#1220]
===  Creating and editing order statuses

Your plentymarkets system comes with 28 default order statuses. You can create new statuses according to your individual requirements.
Default order statuses are linked to automatic processes and thus cannot be deleted. All other statuses can be edited or deleted.

[#1230]
==== Creating a new order status

[.instruction]
Creating a new order status:

. Go to *System » Orders » Status*.
. Click on *Search*. +
→ A list of all existing order statuses opens.
. Click on *Create new status*.
. Enter a decimal number for *New status*. Numbers from 1 to 18 with up to 4 positions after the decimal point are allowed.
. Assign a name to the status in *Name for new status*.
. *Save* the settings. +
→ The details of the newly-created status are opened.
. If needed, add the name of the status in further languages.
. Use the *Color* option to assign an individual color to the status. The default color is yellow. If you click on the yellow field, a colour picker automatically opens in your browser.
. *Save* the settings.

[NOTE]
.Decimal points
====
When assigning numbers to new statuses, make sure that they do not end on 0. If the last decimal point is a 0, the system automatically shortens it. For example, plentymarkets does not distinguish between a status with the number 1.10 and a status with the number 1.1.
====

[#1240]
==== Editing existing order statuses

Proceed as follows to edit a single existing order status.

[.instruction]
Editing a single existing order status:

. Go to *System » Orders » Status*.
. Click on *Search*. +
→ A list of all existing order statuses opens.
. Click on the status that should be edited. +
→ The details of the selected status are opened.
. Change the name of the status.
. Change the *Colour* of the status.
. Click on the *gear-wheel* icon. +
→ The changes are saved.

Use the group function in the *System » Orders » Status* menu to edit multiple order statuses at a time.

[.instruction]
Editing multiple existing order statuses

. Go to *System » Orders » Status*.
. Click on *Search*. +
→ A list of all existing order statuses opens.
. In the status list, place a check mark next to all statuses that should be edited.
. Click on *Group function*. +
→ A new editing area is displayed.
. Activate the option *New colour* in the editing area to change the order status colour.
. Activate the option *Store visibility* in the editing area and select the desired setting from the dropdown menu.
. Click on the *gear-wheel* icon to apply the settings to the selected order statuses. +
→ The changes are saved.

[#1300]
== Searching for orders

Orders are retrieved from different referrers and collected in the order overview listed under *Orders » Edit orders*. You can use the order search to list all of your orders or to find orders. Use the filters to search for orders that meet certain criteria.

Some orders may not be displayed depending on how the rights were configured for the user. This applies to the *Status*, *Client (store)* and *Warehouse* options that can be restricted in the user configuration. These options are found by clicking on the *Rights* tab and then on the *Visibility* tab. If needed, go to *<<basics/admin-tasks/manage-users#90, System » Settings » User>>* and check the settings for users who work with the order search.

The default setting will always display a list of all orders received during the past 2 months because in this setting the different filter options except *Date from to* are set to *ALL*. Change the filter settings to refine your search and to display e.g. orders with a specific status.

Set one or combine several filters to search for orders with specific criteria. To do so, proceed as explained in the following example.

[.instruction]
Searching for orders:

. Go to *Orders » Edit orders*.
. Carry out the filter settings as desired.
. Check whether the default setting for the option *Date* and the given time span under *from to* meets your requirements.
. Click on *Search* to display the orders.

[NOTE]
.Resetting the search
====
Click on *Reset* to reset your filter settings to the default values. Click on *Search* to reset the search result.
====

[#1310]
=== Filtering by IDs and numbers

Change the default filter settings to search for specific orders. One way to find specific orders is to use the search fields. Enter IDs or numbers into these fields to search for orders, customers or items in your system and to find orders that belong to them. For example, if you enter a *Customer ID*, all orders corresponding to this customer ID are displayed.
For example, if you enter the number 3 into the **Order ID** field and click on **Search**, only the order with ID 3 will be displayed in the overview. This way, you can also search for several orders. To do so, enter the *Order IDs* separated by commas. If you search for an *Order ID*, then all of the other filters for entering information will be grayed out.

[NOTE]
.Status search filter
====
If you are searching for one or several orders with the help of one of the search fields, set the search option *Status* correctly. If you are searching for a specific invoice number, we recommend selecting *ALL* as the status option, since the order could have already been delivered or could have a status beyond *7*. Hence, it is important not to forget that only orders which match all selected criteria are displayed. If you can not find an order despite having entered the exact ID, you might have forgotten to select *ALL* for the search option *Status*.
====

[#1320]
=== Filtering by customer data, item data and invoice numbers

If you are searching for specific customer or item data, then it is recommend using the search fields *Customer data* and *Item data*. You can enter search terms as well as numbers into these fields. You can use the *Customer data* field to search for customer names and zip codes. However, you can not search for telephone numbers. Search terms entered into the *Item data* field will be searched for in the fields item ID, item number and name. However, the fields containing description texts (short_description, description) will not be browsed. When searching for *Invoice numbers*, you can also search for external invoice numbers.

[NOTE]
.Only shorten search terms and numbers at the end
====
When searching for customer or item data, it is often sufficient to only enter the word stem into the field. In general, search terms can be shortened to almost any extent at the end of words, but they can not be shortened at the beginning. If you are e.g. searching for items with the search term packages, you could also enter package or pack. Searching for packages, however, would not yield any results. The same is true for all numbers (e. g. customer numbers, zip codes).
====

[#1330]
=== Filtering by order type

Use the *Type* filter in order to search for the following order types:

* *Order*
* *Credit note*
* *Multi credit note*
* *Return*
* *Warranty*
* *Offer*
* *Advance order*
* *Delivery order*
* *Repair*
* *Multi-order*
* *Orders, warranties, delivery orders and repairs*
* *Orders and delivery orders*

The search will only be carried out for the selected order type or combination. The filter is set to *ALL* by default, meaning it will search for all orders if the settings are not modified.

[#1340]
=== Filtering by date

Use the *Date* filter to search for orders that went through a certain step during the time selected. Select this step under *Date*, i.e. *Incoming orders*, *Incoming payment* or *Outgoing items*. Use the *from* and *to* fields to select a starting and ending date for the search. All of the orders that went through the selected step within this time period will be displayed. By default, you will search for orders that were received within the last 2 months. For example, if you search for orders on May 15th, then the default time period will be from *March 15th* to *May 15th* and all orders received within this time period will be displayed.

If you do not want to search for orders with the default 2 month setting, manually select the desired time period.

[.instruction]
Searching orders by date:

. Go to *Orders » Edit orders*.
. Select one of the filter options from the *Date* drop-down list, e.g. *Order received*.
. Use the *from* and *to* fields to select a *start* and *end date* for the search.
. If needed, select additional filter options as described.
. Click on *Search* to list the orders for the selected time period.

[#1350]
=== Filtering by flags

Not only statuses but also flags can be assigned to your orders. You can search for orders in the order overview by these flags. For example, you can assign a certain icon to all orders that you think could be problematic and, therefore, have to be cleared by the person in charge before being shipped. This person could search for flagged orders once a day with the filter *Flag*, enter and save a note for each of them and then reset the flag.

[#1360]
=== Filtering by documents

Use the *Document* filter to search for orders for which an *<<order-processing/orders/order-documents#, order document>>* of a certain type has already been generated.

To search for all orders with a document of a specific type, proceed as described below:

[.instruction]
Searching for orders with a document:

. Go to *Orders » Edit orders*.
. Select a document type from the *Document* drop-down list in the *Filter* tab, e.g. *Invoice*.
. Pay attention to the *Date* filter. The default setting only displays orders from the last 2 months. Adjust the filter as needed.
. Click on *Search*. +
→ All orders for which an invoice was created will be displayed in the search results.

You can also search for an order with a document that has a certain number. To do so, proceed as follows:

[.instruction]
Searching for an order with a document with a specific number:

. Go to *Orders » Edit orders*.
. Select a document type from the *Document* drop-down list in the *Filter* tab, e.g. *Delivery note*.
. Enter the number of the delivery note into the *Number* field.
. Pay attention to the *Date* filter. The default setting only displays orders from the last 2 months. Adjust the filter as needed.
. Click on *Search*. +
→ Only the order to which the delivery note with the number entered belongs will be displayed in the search result.

[TIP]
.Searching for a document without selecting a document type
====
Searching a document number will also work if you keep the default setting *Document* in the drop-down list and do not select a specific type. However, if the numbers of different document types are identical, all orders that include a document with this number will be displayed. This could happen e.g. if you do not use automatic numbering.
====

[#1370]
=== Filtering by coupon codes

It is possible to search for orders that contain a specific *<<order-processing/orders/coupons#, coupon code>>*. This is done by entering the code into the **Coupon code** search field. Then use the drop-down list to choose between the options *All*, *Redeemed* and *Sold*. *All* is selected by default. Select *Redeemed* if you only want to search for orders containing redeemed coupons. Select *Sold* if you only want to search for orders containing coupons that were sold. Select *All* if you want to search for orders containing coupons that were redeemed and orders containing coupons that were sold. The search filter only works if a coupon code is entered. This is true even if you select the setting *All*. In other words, you cannot use the search filter to find all orders that contain coupons.

[#1400]
== Setting up the order overview

The following tools help you to easily keep track of and manage the search results:
You can specify how many orders will be displayed per page in the order overview. You can select different amounts between 50 and 400. Use the blue arrows to switch between pages. If the order overview consists of several pages, the quickest way to switch to a specific page is to enter the page number and press *Enter*.

[#1410]
=== Item list in the order overview

The individual stock units of an order will be displayed in the order overview if the option *Show* was selected for the search filter *Stock unit* (default). This way, the items included in an order and their most important parameters, e.g. *name*, *size* and *price* will be immediately available to you.

[NOTE]
.Opening and closing the item list
====
Click on the blue arrow to display or hide the item list.
====

If the overview contains many orders with long lists of items, then you may find it difficult to scroll through the orders and access the information that you are looking for. Thus, there is an option to close the item lists for all orders at once. When doing so, make sure to not change the other filters for the orders that are displayed. This will ensure that you get the same search results.

[.instruction]
Globally closing item lists in the order overview:

. Go to *Orders » Edit orders*.
. In the *Filter* tab, select *Do not show* for the option *Stock unit*.
. Click on *Search*. +
→ The item lists will close for all orders displayed.

[#1420]
=== Information and icons in the order overview

Different icons will be displayed in the order overview depending on the order's condition. This will be explained further below.
You can see quick information about an order by looking at its title in the overview. You can see the order status and logos that show the *shipping service provider* and the *<<order-processing/payment#, payment method>>*. You may see other icons there as well depending on the configuration and the procedures that were carried out.
The *Book outgoing items* icon will disappear once this procedure has been carried out. It will be replaced with the *Outgoing items booked* icon. At the same time, the status will change to 7. The status background colors make it possible to immediately recognize which orders are in the same status.

The following list gives an overview of the informational icons that display the condition of each order in the overview. The icons will only be displayed if corresponding settings or entries were saved.

* *Order status*
* *Shipping service provider*
* *Shipping method*
* *Payment method*
* *Outgoing items booked*
* *Flag*
* *Country of delivery*
* *Currency*
* *Payment status*

[#150]
=== Functions in the order overview

The following section provides you with details about the functions that can be carried out within the order overview.

[#170]
==== Group functions

plentymarkets provides various tools to process and manage orders as efficiently as possible. The group function described below is one of them. Using this group function, you can edit one or more orders at the same time and avoid time-consuming manual input. That way, you also minimize the risk of possible input errors.

The following example underlines the possibilities you have with the group functions: A popular item from your store is temporarily unavailable. However, there are already numerous orders for it. In most cases, sellers are powerless in case of supply delays. However, they have to inform the affected customers as quickly as possible. Especially customers who have paid in advance will have little patience.

With the group function, you can use the *item ID* or *item name* to search, and select the status filter *ALL &lt; 7* because this procedure is only relevant for orders which have not been shipped yet (=outgoing item not yet recorded). When all orders are listed, go to *Group function* and select the option *Email service* to inform all your customers. As soon as you have selected a group function here, specific settings will appear next to the menu.

In our example, the customer is the recipient. You must have created an *<<crm/sending-emails#, Email template>>* in advance. It is not compulsory to set a *flag*, but this can make sense. Before applying the group function by clicking on *Apply*, make sure that you have selected all of the desired orders with a check mark.

[TIP]
.Status >= 7
====
If the *order status is >= 7*, you cannot lower this status until you have reset the outgoing items that were booked. First use a group function to reset the *outgoing items* for orders that have a status of 7 or higher.
====

[#1500]
== Editing orders

All of your orders are displayed in an overview in the menu *Orders » Edit orders*. Click on an order to open it and edit its settings. The order information is divided into different tabs, which are explained on this page of the manual.

[#1510]
=== Information and procedures in the order overview

All of your orders are displayed in the menu *Orders » Edit orders*. Here you can see the most important information about each order. You are provided with information about the customer, the order status and the payment status. You can also tell which items are included in the order, whether the outgoing items were booked and whether an invoice was generated. In other words, you can easily keep track of the most important processes without having to open the order. Point the cursor over the symbols to see tooltips with additional information.

Click on an *icon* to open further areas within the order. For example, click on *Calculate stock* to check the current stock of the item or to reorder stock.

Furthermore, use the order overview to make changes to the *status*, the *shipping charges*, the *item data* or the *discount* if needed. The information below gives an example of changing the status.

[.instruction]
Adjusting the order status in the order overview:

. Click on the *Status* button. +
→ A list of available statuses will be displayed.
. Select the desired status.
. Click on the *save icon* to save the settings. +
→ The status will be updated.

[TIP]
.Tip: Closing the tooltip without making any changes
====
You have two options for closing the tooltip without making any changes or without saving changes that were already made. Either click on *Cancel* or click with the cursor anywhere outside of the tooltip.
====

[#1520]
=== Opening and editing an order

Open an order by clicking on the order's title line. The order opens in a separate tab. Data and information are saved in several different tabs. The tabs are described on this page of the manual. Orders that are open can be recognized by their *ID* in the tab's title.

[NOTE]
.Saving the settings or changes
====
Most of the order's tabs do not include a save icon. Settings made in these tabs are saved automatically, e.g. changing the flag or dunning level in the *Overview* tab. You can switch to a different tab or close the order and open it again without losing the changes. However, some tabs include a save icon, e.g. the *Settings* tab. Here you can switch to a different tab without losing your changes. However, you will need to save the changes before closing the order.
====

[IMPORTANT]
.Default settings for editing orders (variable user)
====
In order for variable users to be able to open orders, go to *<<order-processing/orders/basic-settings#, **System » Orders » Settings>>* and save default statuses for *returns* and *credit notes*. No status is saved here as the default setting. Variable users also need to be given the right to edit orders. Go to *System » Settings » User » Accounts* and open the particular user account. Then click on *<<order-processing/orders/managing-sales-orders#90, Tab: Right » Tab: Menu » Area: Orders>>*.
====

[#1530]
=== Tab: Overview

The most important order parameters are found in the *Overview* tab. Here, you receive information about the price, shipping costs, VAT, status etc. at a glance. <<table-order-overview-tab-options>> lists the options available in the overview tab of an order.

[TIP]
.Tip: Changing values
====
Some entries can be changed. Such entries either include a drop-down list or a *pencil* icon. Click on the pencil icon to edit the parameter.
====

[[table-order-overview-tab-options]]
.Options in the *overview* tab of an order
[cols="1,3"]
|====
|Setting |Explanation

|*Order ID*
|ID of the order. It is automatically assigned and cannot be changed.

|*Customer ID*
|ID of the customer.

|*Checkout*
|Opens the order in the *My account* area of the store.

|*Input*
|The date when the order was received. This is the date when the order was created or imported into the system.

|*IP address*
|Displays the customer's IP address if desired. +
Go to *<<omni-channel/online-store/setting-up-clients/order-process#, System » Client » Select client » Order process » Settings>>* to activate or deactivate the *Purchaser's IP address* option.

|*Flag*
|Assign a flag to an order. Flags are used to categorise orders. This helps you e.g. find orders with the search filter or apply automatic functions to them with event procedures.

|*Dunning level*
|Various dunning levels are set here if a customer does not pay for the order. These dunning levels are used for automatic processes within the dunning procedure. +
For an example of using dunning levels, refer to the *<<order-processing/payment/mediafinanz#, mediafinanz>>* page of the manual.

|*Estimated shipping*
|This date is calculated based on the delivery deadline that was saved for a *reorder*. In order for the estimated shipping date to be displayed, both the reorder and the item's delivery deadline have to be confirmed and the order has to be in status *[4]*. +
*__Important__*: This option differs from the *Shipped on* option found in the *Settings* tab.

|*Copy*
|Copies the order, gives it a new order ID and places it in a separate order tab.

|*Delete*
|Deletes the order. A security question will follow. +
The delete icon will not be displayed in the following cases: +
- If the user is not <<order-processing/orders/managing-sales-orders#90, **authorised**>> to delete orders +
- If the items have already been booked as outgoing +
- If a delivery order was created +
In general, orders should not be deleted. Errors can occur when orders are deleted because the orders are linked to items, shipping settings and other functions such as cancellations and returns. However, newly created orders can be deleted without any problems.

|*Split up*
|Splits the order. When doing so, you will be asked to assign the items to the newly created orders.

|*Return; Credit note; Warranty*
|Click on the drop-down list to create or search for the order document.

|*New order*
|Creates a new order for the customer. Default settings will automatically be used for the order. You may need to change these settings.

|*Invoice address*
|Click on the *small plus* to display the invoice address. Additional customer information will also be displayed, such as the telephone number, email address and eBay account name.

|*Delivery address*
|Click on the *small plus* to display the delivery address. The *delivery address* will be crossed out if it is identical to the invoice address. +
Click on *New delivery address* to create a new delivery address. Click on *List all delivery addresses* to select a delivery address. +
*Export delivery address* = Exports the delivery address in the export format used by the selected shipping service provider.

|*Bank details*
|Click on the *small plus* to display and edit the customer's *bank details*.

|*Customer notes*
|Displays the notes that were saved for this customer. Click on *New note* to create a note about the customer. Existing notes are displayed in yellow in the editing window. New notes are formatted with the familiar editor functions. Notes that are saved here will be displayed in other orders placed by this customer. They will also be displayed in the *Notes* tab in the customer data record.

|*Order note*
|Displays the notes that were saved for this order. Click on *New note* to create a note about the order. New notes are formatted with the familiar editor functions.

|*Status history*
|Displays a list of all the times when the order's status changed.

|*Payment history*
|Shows details about *<<order-processing/payment#, Payments>>* such as *Payment method*, *Currency*, *Payment ID* or *Date*.

|*Stock units*
|Displays information about the stock units included in the order.

|*Edit*
|Allows you to edit the item data if needed, e.g. item quantity, item details, prices, discounts and VAT rates.

|*Add*
|Use the integrated item search to add other items to the order as needed.

|*Assign storage location*
|Assigns the stock unit to a storage location. If more than one storage location is saved for an item, then the storage locations will be given priority based on their position. If no storage location was saved, then the **standard storage location** will be assigned. +
It is important to assign a storage location for pick lists and packing lists. +
**__Tip:__**: You can also use *<<basics/automation/event-procedures#configuration, event procedures>>* to assign storage locations to items.

|*Delete assignment*
|Deletes the current storage location assignment. Click on *Assign storage location* again (see above) to create a new assignment that is better suited to the current warehouse situation.
|====

[#1540]
=== Tab: Settings

An order's basic parameters are saved in the *Settings* tab, for example the *Status*, *Referrer* and *Payment method*. <<table-order-tab-settings>> lists the available parameters.

[[table-order-tab-settings]]
.Options in the *Settings* tab of an order
[cols="1,3"]
|====
|Setting |Explanation

|**Status; +
Order type; +
Owner; +
Referrer; +
Client (store)**
| +
+
These options will be displayed depending on the existing conditions or circumstances. However, they can be changed.

|*Warehouse*
|The warehouse or main warehouse of the order item. If needed, click on *Stock correction* to change the warehouse. +
*_Important_*: The option *Stock correction* synchronises the data displayed in the *Settings* tab of the order with the warehouse saved for the order items included in the order. The option only appears if you have selected the option *b) are warehouse can be assigned for each stock unit* in the *auftragsabwicklung/auftraege/grundeinstellungen#, System » Orders » Settings* menu. If you manually change the warehouse assigned to an order item and the changed warehouse is not automatically visible in the *Settings* tab of the order, click on *Stock correction* to update the display of the warehouse.

|*Status*
|The order status *[7] Outgoing items booked* can not be changed to a lower status. This is because the items have already been shipped. However, if you still want to do this, then you first need to reset the outgoing items that were booked. It is possible to switch to a lower order status afterwards.

|*Outgoing items*
|Indicates whether outgoing items were booked and displays their posting date. +
Click on *Outgoing items* to manually book the outgoing items.

|*Shipped on*
|This is the *shipping date* that was saved in the item data record. As such, this option is relevant for *<<order-processing/orders/managing-orders#advance-order, advance orders>>*. If the order includes several items that were all ordered in advance, then the date that is farthest in the future will be displayed here. The date can be changed manually.

|*Return date*
|Save the date of a return if an item was returned. Serves as information about a return, so that the return does not have to be opened separately.

|*Currency*
|The order currency.

|*Payment method; Shipping service provider; Shipping profile & shipping charges*
|These options will be displayed depending on the existing conditions or circumstances. However, they can be changed. +
In order to carry out changes, select a *payment method* from the drop-down list and click on the *pencil icon* to edit the shipping options.

|*Payment due*
|You can save values for the options *Value date*, *Early payment discount (days)* and *Early payment discount (%)*. Decide whether to save a value for one of these options or for multiple options, thus creating your terms of payment. If the values were already saved in the customer data, then they will automatically be displayed here. However, they can still be changed.

|*Shipping service provider*
|The shipping service provider that will ship the items for this order.

|*Shipping profile & shipping charges*
|The shipping profile and shipping costs for the order.

|*Ext. Order number*
|Enter the external order number for orders that are imported from an external system.

|*Customer reference*
|If the *Your reference* field is visible to customers during the order process, then any text that a customer entered into this field will appear here. For further information, refer to the notes given in table 1 on the *<<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-checkout, Checkout>>* page of the manual.

|*Packages*
|Number of packages belonging to this order. +
__**Important**__: This entry is not linked to the number of packages set in the Shipping center. If you want to edit the number of packages, do so in the Shipping center.

|*Package number*
|Package number of the shipping package +
If a package number was saved, then the *preview icon* can be used for tracking the package. However, this can only be done if a corresponding tracking code was saved under <<order-process/fulfillment/preparing-the-shipment#, System » Orders » Shipping » Shipping options » Tab: Shipping service provider>>. Otherwise the preview icon will not be visible.
|====

[#1550]
=== Tab: Email

The *Email* tab contains all of the email templates that were configured under <<crm/sending-emails#, System » Client » Select client » Email » Templates>> and that were set up as a type of template that is visible for orders. You can manually send these email templates to customers. This is useful if you unexpectedly need to send an email to a customer, i.e. if you need to send an email that is not taken care of with an automatic procedure. Proceed as described below to send an email template.

[.instruction]
Sending an email template:

. Go to *Orders » Edit orders*.
. Open the order.
. Click on the *Email* tab.
. Select the *language* if needed.
. Click on the *Email templates* tab and then on the tab that contains the email template.
. Select the particular template.
. Click on *Direct Emailing*. +
→ The email will be sent.
. Wait until you see a message confirming that the process was completed.

Check the *access data* if the email was not sent correctly. Go to *<<basics/data-exchange/api-log#, Data » API log>>* and use the *Email* process to see the corresponding error messages.

[IMPORTANT]
.Sending customers a new password
====
The email template *Send customer a new password* cannot be sent from within an order. If you want to send this email template, then do so from within the customer's data record. Click on the *Settings* tab there. You will be able to see the *Password* tab when a customer has registered in the store. This is where you can send the email template.
====

The *Emails sent* tab provides you with an overview of all the email templates that were sent. You can see the *date*, *recipient* and name of the *email template* as well as the *order ID*. You will see all of the emails sent to the customer, even those from other orders.

[#1560]
=== Tab: Payment

Click on the *Payment* tab to see all payments and partial payments that belong to the order. Use the filters to search for specific payments of the order. In the *Payments* tab you can see the total invoice amount, the amount paid and the amount that is still pending. These numbers give you an overview. Moreover, you can use the "Book payment" icon to manually book payments in this tab.

[TIP]
.Missing incoming payments
====
If there are payments missing in the overview, change the *Received from* filter to adjust the time period from which payments should be displayed.
====

[#1570]
=== Tab: Receipts

You can create receipts in the *Receipts* tab, e.g. an order confirmation, a delivery note or an invoice. The documents are created with the help of document templates that are saved under *<<order-processing/orders/order-documents#, Settings » Orders » Documents>>*. Check to make sure that you created the document templates before you create receipts. Check this as well if you receive an error message.

[TIP]
.Tip: Copying document templates
====
If you want to create a <<order-processing/orders/settings/documents#20, document template>> quickly, then copy a previously configured document template and make changes to the template as needed.
====

The receipts are configured before they are created. You can specify different parameters for each receipt. For example, when creating an invoice, you can enter the date, specify when *payment is due*, whether customers should be given an early payment discount and whether the outgoing items should be booked. Furthermore, you can change the status when the receipt is created.

[#1580]
=== Tab: Customer

By clicking the *Customer* tab, the <<crm/managing-contacts#, contact data record>> opens. You can edit this information here.

[#1590]
=== Tab: Tickets

The customer's *<<crm/using-the-ticket-system#, tickets>>* are displayed in the *Tickets* tab. You can edit these tickets directly without having to switch to the ticket system.

[#1600]
=== Tab: Orders

Other orders that were also placed by this customer are displayed in the *Orders* tab. The customer's orders can be edited in this tab.

[#1610]
=== Tab: Stock

The *Stock* tab displays the <*<stock-management/managing-stocks#, stock data>>* for all of the items that are included in the order. All of the functions of the *Stock* menu are available in this tab with the exception of the filter functions. You can view stocks and configure them as needed.

[#1620]
=== Tab: Reorder

Select the order items for a reorder in the *Reorder* tab. Choose whether you want to generate a reorder for the specific order only or whether you want to generate a reorder to which items can be added from other orders as well. +
In both cases the items must all have the same supplier and warehouse. If the order items have different suppliers and warehouses, then a separate reorder will be generated for each supplier/warehouse combination.

[NOTE]
.Save the supplier
====
A supplier has to be saved for every item. Otherwise it is not possible to place a reorder.
====

[#1630]
=== Selecting order items

Proceed as described below to select individual items or all items from an order for the reorder.

[.instruction]
Selecting specific items for the reorder:

. Go to *Orders » Edit orders*.
. Open the desired order.
. Click on the *Reorder* tab.
. Select the *variations* that you want to reorder.
. Click on *Reorder selected items*. +
→ A general and extendible reorder will be generated. The marked items from this order will be in the reorder and other items will be added to it, if they are reordered by clicking on this button. The quantity of each variation is displayed in the *Quantity* column.

If you select certain items for the reorder, then the *Reorder all items* button will be deactivated and can no longer be clicked on.

[.instruction]
Selecting all items for a reorder:

. Go to *Orders » Edit orders*.
. Open the desired order.
. Click on the *Reorder* tab.
. Click on *Reorder all items*. +
→ A reorder that contains all items from this order will be generated. The quantity of each variation is displayed in the *Quantity* column.

[#1640]
==== Placing a reorder

[TIP]
.Meaning of the information listed under Quantity
====
In the *Quantity* column you can see the delivered quantity (green numbers), the pending quantity (red numbers) and the ordered quantity (white numbers). +
Partial quantities are displayed as *delivered* if they were booked as a partial delivery in the reorder under *Status*. +
====

Proceed as follows to place the reorder after selecting the order items:

[.instruction]
Placing a reorder:

. Open the order and click on the *Reorder* tab. Click on a *shopping cart* icon. +
→ The *Reorder* menu opens. You can see which items are included in a reorder by clicking on the *Base* tab and then opening the *Item data* submenu.
. Open the *Basic data* submenu and click on the *gear-wheel icon* next to the *Order* option. +
→ The order will be placed. The order data will also be displayed in the order. This information is displayed in the *Reorder* tab.

[TIP]
.Tip: Adjust the purchase price and quantity
====
You can open the *Item data* submenu within the *Base* tab and make changes to the options *Purchase price* and *Quantity* before placing the reorder.
====

For further information about editing a reorder and booking partial quantities, refer to the *Reorders* page of the manual.

[#1650]
==== Increasing the number of variations in a reorder

You can increase the number of variations in reorders that are still open. This is possible for values where percentages were saved during the *distribution*. Proceed as follows to increase the number of variations:

[.instruction]
Increasing the quantity for variations:

. Click on *Increase quantities for variations*.
. Select the *reorder ID* and the *item* from the drop-down lists.
. Select the *attribute* and the *value*.
. Enter the *quantity*.
. Click on *Increase quantity*.
. Repeat these steps for every variation whose quantity you would like to increase.

[#1660]
=== Tab: Delivery

Delivery orders are created in the **Delivery** tab. There you can see the order's stock units which have not yet been transferred into delivery orders.

[.instruction]
Manually creating delivery orders:

. Go to *Orders » Edit orders*.
. Open the desired order.
. Click on the *Delivery* tab.
. Enter the quantity that should be carried over to the delivery order into the *DelOrdQua* (quantity for the delivery order). +
→ The quantity that was entered must not be larger than the quantity displayed under *Unass.Quantity* (unassigned quantity).
. Click on the *gear-wheel icon* to create the delivery order.

[NOTE]
.Generating delivery orders automatically
====
Click on *Generate delivery orders automatically* to create the delivery orders. They will be created according to the setting that was selected under *<<order-processing/orders/managing-sales-orders#delivery-order, System » Orders » Order types » Delivery order>>* in the *Split up orders into delivery orders by* drop-down list. All of the stock units will be split up into delivery orders. You can only use this function if no delivery order already exists for the order.
====

When creating a delivery order, the stock reservation for the quantity included in the delivery order is transferred from the main order to the delivery order. If delivery orders are created individually and items are still available in the main order, then the items will also be reserved.

[TIP]
.Tip: Editing order items in the main order
====
Stock units can be added to the main order or deleted from the main order. However, you can only delete stock units from the main order if they are not included in the delivery orders. The number of items in the main order can be increased or decreased. However, you should only delete quantities that are not assigned. It is technically possible to delete stock units that are already included in a delivery order. However, you should avoid doing so.
====

[#1700]
=== Group functions

You can use the *group function* to carry out processes for several orders at the same time. This means that processes, such as a status change or an email service, will be applied to all marked orders. You can also use the group function to delete specific orders. The group function is particularly recommended if you need to edit a large number of orders and it would be too time consuming to edit each one individually. Image 12 shows the editing window and the options that it contains.

[IMPORTANT]
.Use the data exchange as an alternative
====
The group function can only be used for the orders that are displayed in the overview (up to a maximum of 400 orders). Use the dynamic *<<basics/data-exchange#, data exchange>>* if you want to edit a larger number of orders or if you want to edit all orders at the same time.
====

An example for using the group function is given below.

[.instruction]
Example for booking outgoing items with a group function:

. Go to *Orders » Edit orders*.
. Mark the *orders* that should have their outgoing items booked with a group function.
. Click on *Group function*.
. Place a check mark next to the option *Book outgoing items*.
. Select the *date* and *time*. +
→ The current date is selected by default. However, you can change the date if needed. You are required to select a date for this group function.
. Click on *Apply*  to carry out the procedure.
