= Order referrer
:lang: en
include::{includedir}/_header.adoc[]
:position: 50
:url: orders/order-referrer
:id: G39SVHL

Omni-channel sale with plentymarkets means for you that you can use many different channels to offer your items to customers and, therefore, generate orders from many different sources.
Some referrers are set up by default and are fixed entries that can not be changed.
Other referrers are automatically added e.g. when you integrate a plugin or plentymarkets POS.
Referrers from plugin can not be deleted either. At last you can also manually set up referrers.
Manually set up referrers are useful to register e.g. orders made via telephone or you can set up referrers for price search engines or affiliate service providers.
Each referrer has a unique ID. Some referrers have sub-referrers. The ID for a sub-referrer is composed of the ID of the main referrer followed by two decimal numbers. *Amazon*, *eBay* and plentymarkets POS are examples for main referrers that have sub-referrers.
Each country platform of eBay and Amazon has a sub-referrer just like every till registered with plentymarkets POS will have a sub-referrer.
All orders, no matter where they were made originally, are collected and displayed in the order menu.
The referrer can be found in the *Settings* tab of an order.

== Activating an order referrer

Default referrers and referrers that were automatically added by plugins still need to be activated.

[.instruction]
Activating an order referrer:

. Go to *Setup » Orders » Order referrer*.
. Select a referrer.
. Place a check mark for this referrer in the check mark column. +
→ Pay also attention to the information given <<table-settings-order-referrers>>.
. *Save* the settings.

== Manually creating an order referrer:

Proceed as described below to manually create a new referrer.

[TIP]
.Referrers are required for affiliate service providers
====
The referrer option is also required for cooperation with affiliate partners. These partners will forward potential customers to you via defined tracking URLs and expect a commission in return when the customer purchases something.
====

[.instruction]
Creating an order referrer:

. Go to *Setup » Orders » Order referrer*.
. Click on *New*. +
A new line will be added to the referrer list and the cursor of your mouse is directly placed in the name column of that line.
. Enter a name for the *referrer*.
. Carry out the settings according to the information provided in <<table-settings-order-referrers>>.
. *Save* the settings.

[[table-settings-order-referrers]]
.Settings for order referrers
[cols="1,3"]
|====
|Setting |Explanation

|*New*
|Click to create a new order referrer.  +
*Note:* If the button is no longer visible, then all Ids reserved for manual order referrers are occupied (see *ID*).

|*ID*
|Every order referrer is given an ID. The system automatically assigns the ID. It can not be edited. The IDs 9 - 100 are available for manually created order referrers. The IDs 1 to 8 as well as 101 and higher are reserved for predefined order referrers in the system. Sub-referrers are represented by a decimal ID, e.g. 2.08.

|*Name*
|The name that was entered can be changed here any time. It will be displayed in the system, e.g. in the order search.

|*Internal name*
|The internal name can not be changed and is not displayed in the system. Only predefined order referrers are given an internal name, not referrers that you created manually.

|*Owner*
|Select which person should automatically be entered as owner of orders that have this referrer. You can choose from all users who were given these rights under *<<basics/admin-tasks/manage-users#, Setup » Settings » User » Accounts>>*.

|*Check mark column for activation*
|Check mark = referrer will be shown in other menus, e.g. in the *Settings* tab of individual orders +
No check mark = referrer will not be shown in other menus

|*Copy online store URL*
|Copies the referrer's URL to the clipboard. +
The URL is required for, e.g. affiliate services. It contains the ID as the referrer ID.

|*Open in the store*
|A click on the preview icon will open the online store with the referrer ID added to it. All prices for the corresponding order referrer will be displayed. +
However, the preview can only function correctly if you have set up sales prices and activated the sales price for the referrer you wish to see a preview for. In addition the sales price also has to be added to a variation and a value for the price must have been saved.

|*Delete*
|Click on the delete icon to delete an order referrer. You can only delete those order referrers that you created manually. Default order referrers in the system can not be deleted.
|====

== Searching orders by order referrer

The order search in the *Order » Edit orders* menu offers many filters to narrow down the number of results. The *Referrer* filter searches for orders that have a specific referrer (Client (store), Amazon, eBay etc.). Amazon and eBay have both general referrers and sub-referrers for each of the country platforms.

For monthly overviews, it makes sense to use a date as an additional filter, e.g. the date when orders were received. The *Statistics* menu provides you with other possibilities for the analysis.

== Identifying the order referrer or an order

The order referrer is displayed in the order overview. The ID of a referrer is displayed in line with further order details. If you point the cursor to the ID, a tooltip with the referrer's name will be displayed.

The *referrer* can also be found in the *Settings* tab of a single order. The referrer can only be changed if it is a manually created referrer and only as long as no invoice was created yet.

== Analysing sales per referrer

The referrer is important for measuring how well your items sell on different platforms. This information tells you which platforms are most profitable. In the orders menu, you can use the referrer and date filters to see the total revenue that was generated by each order referrer during a specific time period. In the *Statistics*
menu, you can also select an order referrer and see the revenue that was generated by each referrer. Based on these figures you can better decide where and how to invest in the future.
