= Package content list
:lang: en
include::{includedir}/_header.adoc[]
:keywords: package content list, package content, pallet, palett, package, unpacked items, packed items, purchase order, inbound, receipt
:description: Learn how to use the package content list in plentymarkets.
:position: 85

On this page, you find detailed information about how to use the package content list in plentymarkets. The package content list informs you about the content of pallets and packages. Such a list is relevant for a fulfilment service provider who stores and sends your items for you. The list informs them about which items are in the packages.

[TIP]
.Notes about the package content list
====
The available functions in the *Orders » Package content list* menu are primarily addressed to employees packing the items in the warehouse. Warehouse employees do not sit directly in front of the computer all the time, but rather move freely when using the barcode scanner and when packing the items,. This is why we intentionally designed the buttons and frames in this menu spaciously.
====

[#100]
== Entering the order ID

Currently, it is only possible to enter the order ID manually. In the near future, it will be possible to scan the order ID using a barcode scanner.

[#200]
== Scanning items

The item is part of the package. The package is part of the pallet.

When scanning the first item, a pallet and a package is automatically created and the item is added to the package.

[#300]
== Editing the pallet

In the following sub-chapters, you learn how to edit pallets.

[#500]
=== Creating a pallet by scanning the items

Once you have scanned the first item, a pallet and a package are automatically created.

However, you can also manually create the pallet.

[#600]
=== Manually adding a pallet

By clicking on *Add pallet*, the pallet is created.

[#700]
=== Closing the pallet

When you close the pallet, the pallet, the packages and the items contained in the packages are closed for further processing. This action cannot be undone.

[#800]
=== Deleting the pallet

When you delete the pallet, the pallet, the packages and the items contained in the packages are deleted.

[#900]
== Editing the package

In the following sub-chapters, you learn how to edit packages.

[#1000]
=== Creating a package by scanning the items

Once you have scanned the first item, a pallet and a package are automatically created.

However, you can also manually create the package.

[#1100]
=== Manually adding a package

By clicking on *Add package*, a new package is created.

[#1200]
=== Closing the package

When you close the package, the package and the items contained in the package are closed for further processing. This action cannot be undone.

[#1300]
=== Deleting the package

When you delete the package, the package and the items contained in the package are deleted.

[#1500]
== Manually adjusting the item quantity

Click on the value in the line *Quantity* of the list in order to adjust the quantity manually. The number of the items that are packed and are not packed yet is automatically adjusted.

[#1600]
== Displaying the barcode

Select the barcode from the drop-down list. The list contains all barcode types that are available in your system. If a barcode was created for the item, this barcode is displayed in the overview.

[#1700]
== Displaying unpacked items

In the *Orders » Package content list* menu, you can see in the top-right corner a large box with the number of the items that are not packed yet.

The number is updated automatically once you add another item to the package.

////
== Downloading and printing the package content list

You can download a complete overview of the package content list that lists the pallets and packages. Afterwards, you can print the list.

////
