= Artikel-, Kunden- und Auftragssuche
:lang: de
include::{includedir}/_header.adoc[]
:description: Die plentymarkets App macht es einfach, unterwegs nach Artikeln zu suchen.
:position: 20
:url: app/funktionen/artikelsuche
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Verschaffe dir auch von unterwegs einen Überblick über dein Business. Willst du neue Bestellungen direkt auf deinem Smartphone verfolgen? Willst du die Adresse oder Telefonnummer eines Kunden nachschlagen? Mit der plentymarkets App bist du auch unterwegs gut ausgerüstet!

[#100]
== Artikelsuche

Die plentymarkets App macht es einfach, unterwegs nach Artikeln zu suchen. Möchtest du den Preis eines Artikels schnell überprüfen? Willst du fix nachsehen, wie viele Exemplare noch auf Lager sind? Oder willst du vielleicht das Artikeletikett direkt über die App ausdrucken? Die plentymarkets App macht es möglich.

Die plentymarkets App beinhaltet eine Artikelsuche, die auf dieser Seite beschrieben wird. <<app/funktionen/artikelsuche#200, Konfiguriere zunächst einige Grundeinstellungen>> und bestimme somit selbst, wie die Suchergebnisse aussehen sollen. Diese Einstellungen greifen dann später, wenn du <<app/funktionen/artikelsuche#300, nach Artikeln suchst>>.

[#200]
=== Artikelsuche individuell anpassen

Wie viele Suchergebnisse möchtest du auf einmal sehen? Welche Informationen sollen in großer oder kleiner Schrift dargestellt werden? Suchst du typischerweise anhand der Artikel-ID, Name oder Barcode? Beantworte diese Fragen, indem du die Standard-Sucheinstellungen anpasst.

[.instruction]
Artikelsuche anpassen:

. <<app/installation#1100, Melde dich bei der plentymarkets App an>>.
. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe auf icon:cog[role="darkGrey"] *Einstellungen*.
. Tippe auf icon:search[role="darkGrey"] *Artikelsuche*.
. Nehme die Einstellungen vor. Beachte <<tabelle-artikelsuche-anpassen>>.
. Tippe auf das Häkchen oben rechts (icon:check[role="blue"]), um die Änderung zu bestätigen.

[[tabelle-artikelsuche-anpassen]]
.Artikelsuche anpassen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Anzahl zu ladender Artikel*
|Wie viele Suchergebnisse möchtest du auf einmal sehen? Wähle eine Zahl aus der Dropdown-Liste.

|*Artikelsuchfelder*
|Welche Informationen nutzt du, um nach Artikeln zu suchen? Verwende die Umschaltflächen, um festzulegen, welche Parameter bei der Suche nach Artikeln verwendet werden dürfen. +
*Aktiviert* (icon:toggle-on[role="green"]) = Es wird möglich sein, Artikel anhand dieses Parameters zu suchen.

|*Fokus auf Suchfeld*
|Suchst du typischerweise anhand eines bestimmten Parameters? Tippe auf deinen am häufigsten verwendeten Parameter. Später wenn du nach Artikeln suchst, wird dein Mauszeiger automatisch in diesem Feld beginnen. Natürlich wird es weiterhin möglich sein, den Mauszeiger manuell in ein anderes Feld zu platzieren.

|*Vorlage*
|Wie sollen die Suchergebnisse aussehen? Die plentymarkets App verfügt bereits über eine Standard-Vorlage, die für die meisten Artikelsuchen geeignet ist. Du kannst allerdings auch <<app/installation#1900, weitere Vorlagen>> im plentymarkets Backend unter *Einrichtung » plenty App » Artikelsuche* erstellen und dann hier in dieser Dropdown-Liste auswählen. +
*_Tipp_*: Mit Vorlagen kannst du z.B. bestimmen, in welcher Reihenfolge und in welcher Schriftgröße die einzelnen Informationen später in den Suchergebnissen und in der Artikeldetailansicht dargestellt werden sollen.

//Sobald die Seite steht, mach ein Link um den Text "Artikeletikett, das du für diesen Zweck gestaltet hast" herum. Es soll zur Kapitel Artikeletikett gestalten linken.
|*Artikeletikett*
|Willst du Artikeletiketten über die plentymarkets App drucken? Wähle das Artikeletikett, das du für diesen Zweck gestaltet hast. +
*_Tipp_*: Dieser Bereich wird nur angezeigt, wenn du die <<app/installation#2050, App mit plentyBase verknüpft>> hast.

|*Drucker*
|Willst du Artikeletiketten über die plentymarkets App drucken? Wähle den Drucker, auf dem die Etiketten gedruckt werden sollen. +
*_Tipp_*: Dieser Bereich wird nur angezeigt, wenn du die <<app/installation#2050, App mit plentyBase verknüpft>> hast.
|====

[#300]
=== Nach Artikeln suchen

Verwende die Artikelsuche und greife auf deinen gesamten Produktkatalog zu.

[.instruction]
Nach Artikeln suchen:

. <<app/installation#1100, Melde dich bei der plentymarkets App an>>.
. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe auf icon:search[role="darkGrey"] *Artikelsuche*. +
→ Die Artikelsuche wird geöffnet.
. Gib ein Suchkriterium ein, z.B. eine Artikel-ID.
. Tippe auf icon:search[role="blue"] *Suchen*. +
→ Die gefundenen Artikel werden aufgelistet.
. Wähle einen Artikel (icon:check[role="green"]). +
→ Die Detailansicht wird angezeigt.

[TIP]
.Bestandsinformationen anzeigen
====
//Umbuchung-Link auch anpassen auf dem bestimmten Kapitel nachdem die Info auf die Umbuchung-Seite ergänzt wurde.
Tippe auf die Kartons (icon:cubes[role="blue"]), um Informationen zum Bestand zu sehen. Tippe anschließend auf die drei Punkte (icon:ellipsis-h[role="blue"]), wenn du den <<app/funktionen/lagerverwaltung/einbuchen-umbuchen#500, Artikel umbuchen>> oder das <<app/funktionen/artikelsuche#400, Etikett des Artikels drucken>> willst.
====

[#400]
=== Etiketten über die plentymarkets App drucken

Mit Hilfe der App kannst du manuell Etiketten für bestimmte Artikel generieren.

[TIP]
.Sind alle Voraussetzungen erfüllt?
====
Bevor du Etiketten über die App drucken kannst, musst du:

//Link zur Etiketten-Seite einbauen, sobald die Seite steht. "Etiketten mit Hilfe von Vorlagen gestalten"
* ein Tool namens <<app/installation#2050, plentyBase herunterladen und mit der App verbinden>>
* deine Etiketten mit Hilfe von Vorlagen gestalten
* angeben, <<app/funktionen/artikelsuche#200, welche Etikettenvorlage und welchen Drucker>> du verwenden willst
====

[.instruction]
Etiketten über die plentymarkets App drucken:

. <<app/funktionen/artikelsuche#300, Suche nach dem Artikel in der App>>.
. Tippe auf die Kartons (icon:cubes[role="blue"]), um Bestandsinformationen zu sehen. +
→ Die Lagerorte des Artikels werden angezeigt.
. Tippe auf die drei Punkte (icon:ellipsis-h[role="blue"]). +
→ Weitere Optionen werden angezeigt.
. Tippe auf icon:print[role="blue"] *Artikeletikett drucken*. +
→ Das Etikett wird gedruckt.

[#500]
== Kundensuche

Die plentymarkets App macht es einfach, unterwegs nach Kunden zu suchen.
Musst du die E-Mail-Adresse oder Telefonnummer eines Kunden nachschlagen?
Willst du prüfen, ob du besondere Zahlungskonditionen für diesen Kunden hinterlegt hast? Zum Beispiel, ob dieser Kunde einen prozentualen Skontoabzug erhält, wenn er innerhalb eines bestimmten Zeitrahmens bezahlt?
Die plentymarkets App macht es möglich.

Die plentymarkets App beinhaltet eine Kundensuche, die auf dieser Seite beschrieben wird. <<app/funktionen/artikelsuche#600, Konfiguriere zunächst einige Grundeinstellungen>> und bestimme somit selbst, wie die Suchergebnisse aussehen sollen. Diese Einstellungen greifen dann später, wenn du <<app/funktionen/artikelsuche#700, nach Kunden suchst>>.

[#600]
=== Kundensuche individuell anpassen

Wie viele Suchergebnisse möchtest du auf einmal sehen?
Suchst du typischerweise anhand der Kunden-ID, Name oder PLZ? Beantworte diese Fragen, indem du die Standard-Sucheinstellungen anpasst.

[.instruction]
Artikelsuche anpassen:

. <<app/installation#1100, Melde dich bei der plentymarkets App an>>.
. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe auf icon:cog[role="darkGrey"] *Einstellungen*.
. Tippe auf icon:address-card-o[role="darkGrey"] *Kundensuche*.
. Nehme die Einstellungen vor. Beachte <<tabelle-kundensuche-anpassen>>.
. Tippe auf das Häkchen oben rechts (icon:check[role="blue"]), um die Änderung zu bestätigen.

[[tabelle-kundensuche-anpassen]]
.Kundensuche anpassen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Anzahl zu ladender Kunden*
|Wie viele Suchergebnisse möchtest du auf einmal sehen? Wähle eine Zahl aus der Dropdown-Liste.

|*Kundensuchfelder*
|Welche Informationen nutzt du, um nach Kunden zu suchen? Verwende die Umschaltflächen, um festzulegen, welche Parameter bei der Suche nach Kunden verwendet werden dürfen. +
*Aktiviert* (icon:toggle-on[role="green"]) = Es wird möglich sein, Kunden anhand dieses Parameters zu suchen.

|*Fokus auf Suchfeld*
|Suchst du typischerweise anhand eines bestimmten Parameters? Tippe auf deinen am häufigsten verwendeten Parameter. Später wenn du nach Kunden suchst, wird dein Mauszeiger automatisch in diesem Feld beginnen. Natürlich wird es weiterhin möglich sein, den Mauszeiger manuell in ein anderes Feld zu platzieren.
|====

[#700]
=== Nach Kunden suchen

Verwende die Kundensuche und greife auf deine gesamte Kundendatenbank zu.

[.instruction]
Nach Kunden suchen:

. <<app/installation#1100, Melde dich bei der plentymarkets App an>>.
. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe auf icon:address-card-o[role="darkGrey"] *Kundensuche*. +
→ Die Kundensuche wird geöffnet.
. Gib ein Suchkriterium ein, z.B. eine Kunden-ID.
. Tippe auf icon:search[role="blue"] *Suchen*. +
→ Die gefundenen Kunden werden aufgelistet.
. Tippe auf einen Kundendatensatz. +
→ Die Detailansicht wird angezeigt.

[TIP]
.Firmen- und Adressdaten anzeigen
====
Tippe auf die Fabrik (icon:industry[role="blue"]), um Firmeninformationen zu sehen.
Hier kannst du beispielsweise prüfen, ob dieser Kunde einen prozentualen Skontoabzug erhält, wenn er innerhalb eines bestimmten Zeitrahmens bezahlt.
Beachte, dass dieser Bereich nur dann Informationen enthält, wenn <<crm/kontakte-verwalten#90, Firmeninformationen im Kundendatensatz>> gespeichert wurden.

Tippe auf die Kartenmarkierung (icon:map-marker[role="blue"]), um Adressinformationen zu sehen.
====

[#800]
== Auftragssuche

Die plentymarkets App beinhaltet eine Auftragssuche, die auf dieser Seite beschrieben wird. <<app/funktionen/artikelsuche#900, Konfiguriere zunächst einige Grundeinstellungen>> und bestimme somit selbst, wie die Suchergebnisse aussehen sollen. Diese Einstellungen greifen dann später, wenn du <<app/funktionen/artikelsuche#1000, nach Aufträgen suchst>>.

[#900]
=== Auftragssuche individuell anpassen

Wie viele Suchergebnisse möchtest du auf einmal sehen? Welche Informationen sollen in großer oder kleiner Schrift dargestellt werden?
Beantworte diese Fragen, indem du die Standard-Sucheinstellungen anpasst.

[.instruction]
Auftragssuche anpassen:

. <<app/installation#1100, Melde dich bei der plentymarkets App an>>.
. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe auf icon:cog[role="darkGrey"] *Einstellungen*.
. Tippe auf icon:list-alt[role="darkGrey"] *Aufträge*.
. Nehme die Einstellungen vor. Beachte <<tabelle-auftragssuche-anpassen>>.
. Tippe auf das Häkchen oben rechts (icon:check[role="blue"]), um die Änderung zu bestätigen.

[[tabelle-auftragssuche-anpassen]]
.Auftragssuche anpassen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Anzahl zu ladender Aufträge*
|Wie viele Suchergebnisse möchtest du auf einmal sehen? Wähle eine Zahl aus der Dropdown-Liste.

|*Vorlage*
|Wie sollen die Auftragsdaten aussehen? Die plentymarkets App verfügt bereits über eine Standard-Vorlage, die für die meisten Auftragssuchen geeignet ist. Du kannst allerdings auch <<app/installation#1900, weitere Vorlagen>> im plentymarkets Backend unter *Einrichtung » plenty App » Auftragsübersicht* erstellen und dann hier in dieser Dropdown-Liste auswählen. +
*_Tipp_*: Mit Vorlagen kannst du z.B. bestimmen, in welcher Reihenfolge und in welcher Schriftgröße die einzelnen Auftrags- und Artikelinformationen später dargestellt werden sollen.
|====

[TIP]
.Häufig verwendete Suchkriterien speichern
====
Wenn du später <<app/funktionen/artikelsuche#1000, nach Aufträgen suchst>>, wird die App standardmäßig deine neuesten Bestellungen laden.
Vielleicht willst du aber auch regelmäßig nach Aufträgen suchen, die sich in einem bestimmten Status befinden oder die von einer bestimmten Verkaufsplattform stammen.
Neben der Möglichkeit, deine <<app/funktionen/artikelsuche#1100, Suchergebnisse mit Hilfe von Filtern einzugrenzen>>, kannst du auch deine am häufigsten verwendeten Suchkriterien speichern, so dass du die Filterparameter nicht bei jeder Suche neu eingeben musst.
====

[#1000]
=== Nach Aufträgen suchen

Verwende die Auftragssuche, um wichtige Informationen zu deinen Bestellungen nachzuschlagen.

[.instruction]
Nach Aufträgen suchen:

. <<app/installation#1100, Melde dich bei der plentymarkets App an>>.
. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe auf icon:list-alt[role="darkGrey"] *Aufträge*. +
→ Deine Aufträge werden geladen.
. Tippe auf einen Auftrag. +
→ Die Detailansicht wird angezeigt.
. Schlage die benötigten Auftragsinformationen nach. Beachte <<tabelle-auftragsbereiche>>.

[[tabelle-auftragsbereiche]]
.Auftragsbereiche
[cols="1,9"]
|====
|Bereich |Erläuterung

|icon:info-circle[role="blue"]
|Grundlegende Informationen über die Bestellung, z.B. die Auftrags-ID und -Status, die Zahlungs- und Versandart, der Preis, das Gewicht, etc. <<app/funktionen/artikelsuche#900, Erstelle eine Vorlage>>, wenn du selbst bestimmen willst, welche Informationen in diesem Bereich angezeigt werden. Tippe auf die drei Punkte (icon:ellipsis-v[role="blue"]), um den Auftragsstatus manuell in die App zu ändern.

|icon:list[role="blue"]
|Informationen über die bestellten Artikel, z.B. Artikelname, Menge und Preis. <<app/funktionen/artikelsuche#900, Erstelle eine Vorlage>>, wenn du selbst bestimmen willst, welche Informationen in diesem Bereich angezeigt werden.

|icon:thumb-tack[role="blue"]
|Notizen, die zu diesem Auftrag bereits gespeichert wurden. Tippe auf die drei Punkte (icon:ellipsis-v[role="blue"]), um eine neue Notiz hinzuzufügen.

|icon:money[role="blue"]
|Zahlungen, die zu diesem Auftrag gehören.

|icon:history[role="blue"]
|Die Statushistorie des Auftrags.
|====

[TIP]
.Kann ich Aufträge auch in der App abwickeln?
====
Es gibt nur begrenzte Möglichkeiten, Aufträge mit der App abzuwickeln. Tippe auf die drei Punkte (icon:ellipsis-v[role="blue"]), wenn du den Auftragsstatus manuell ändern, eine E-Mail an den Kunden senden oder eine Notiz zu dieser Bestellung schreiben möchtest.
====

[#1100]
=== Filters

Wenn du <<app/funktionen/artikelsuche#1000, nach Aufträgen suchst>>, lädt die App standardmäßig deine neuesten Bestellungen.
Vielleicht willst du aber nur Aufträgen suchen, die sich in einem bestimmten Status befinden oder die von einer bestimmten Verkaufsplattform stammen.
Grenze ganz einfach deine Suchergebnisse mit Filtern ein! Speichere zudem deine am häufigsten verwendeten Suchkriterien, so dass du die Filterparameter nicht bei jeder Suche neu eingeben musst.

[.instruction]
Aufträge filtern:

. <<app/installation#1100, Melde dich bei der plentymarkets App an>>.
. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe auf icon:list-alt[role="darkGrey"] *Aufträge*. +
→ Deine Aufträge werden geladen.
. Tippe oben rechts auf das Filtersymbol (icon:filter[role="blue"]). +
→ Die Filtereinstellungen werden angezeigt.
. Wähle die passenden Filter.
. Tippe auf icon:filter[role="blue"] *Anwenden*. +
→ Die Aufträge, die diesen Filterkriterien entsprechen, werden angezeigt.

[TIP]
.Speichere deine am häufigsten verwendeten Suchkriterien
====
Möchtest du diese Filtereinstellungen in Zukunft wiederverwenden? Dann scrolle nach unten und tippe auf die leere Zeile links neben dem Häkchen.
Gib einen Namen für die Filtervorlage ein und tippe auf das Häkchen (icon:check[role="blue"]).

Wenn du zukünftig nach Aufträgen suchst, kannst du diese Filtervorlage ganz einfach aus der Dropdown-Liste oben auswählen und dann auf icon:filter[role="blue"] *Anwenden* tippen.
====
