= DPD Versand-Services
:lang: de
include::{includedir}/_header.adoc[]
:keywords: DPD Versand-Services, DPD Versand Services, DPD Plugin, DPD Versand-Plugin, DPD Versandplugin, DPD Assistent, DPD Assistenten
:description: Erfahre, wie du das Plugin "DPD Versand-Services" in plentymarkets einrichtest.
:position: 400
:url: fulfillment/versanddienstleister-plugins/plugin-dpd-versand-services
:id: 0I6ONMQ
:author: team-fulfillment

[IMPORTANT]
.DPD Versand-Services-Plugin herunterladen
====
Die Schnittstelle zu DPD Versand-Services wird über ein Plugin integriert. Um das DPD Versand-Services-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/plugins/integration/dpdshippingservices_6320[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

[#bei-dpd-registrieren]
== Bei DPD registrieren

Mit dem Plugin *DPD Versand-Services* können Versender schnell und einfach Versandlabels erstellen und die Sendungsverfolgung in plentymarkets nutzen.

Um die Schnittstelle für DPD Deutschland in deinem plentymarkets System einrichten und nutzen zu können, musst du dich bei link:https://www.dpd.com/de/de/[DPD^]{nbsp}icon:external-link[] registrieren und deinen Account für den Webservice freischalten lassen. Um die Zugangsdaten zu erhalten, die du für die Einstellungen in plentymarkets benötigst, wende dich bitte an deinen DPD Vertriebsansprechpartner.

[IMPORTANT]
.Delis ID
====
Um das DPD Versand-Services-Plugin einrichten und nutzen zu können, benötigst du eine Delis ID. Du erhältst die Delis ID von DPD. Beachte, dass aktuell nur Händler mit einem monatlichen Volumen ab 500 Paketen die Delis ID von DPD erhalten.
====

[#dpd-versand-services-einrichten]
== DPD Versand-Services in plentymarkets einrichten

[#vorbereitende-einstellungen]
=== Vorbereitende Einstellungen vornehmen

Zunächst musst du einige vorbereitende Einstellungen im plentymarkets Backend vornehmen:

* <<fulfillment/versand-vorbereiten#100, Lieferländer>> einrichten
* <<fulfillment/versand-vorbereiten#400, Regionen>> erstellen
* den <<fulfillment/versand-vorbereiten#800, Versanddienstleister>> *DPD Versand-Services* erstellen
* <<fulfillment/versand-vorbereiten#1000, Versandprofil>> und <<fulfillment/versand-vorbereiten#1500, Portotabelle>> für *DPD Versand-Services* erstellen

[#assistenten-durchlaufen]
=== Assistenten durchlaufen

Sobald du das Plugin wie oben im aufklappbaren Bereich *Erste Schritte und Anforderungen* beschrieben installiert und das Plugin-Set gespeichert und bereitgestellt hast, sind die Assistenten im Menü *Einrichtung » Assistenten* im Bereich *Integration* sichtbar und du kannst mit dem Einrichten beginnen.

Durchlaufe nun die Assistenten *DPD Versand-Services Grundeinstellungen* und *DPD Versand-Services Einstellungsverknüpfung*, um die Schnittstelle in plentymarkets einzurichten.

[#dpd-paketshop-finder-anzeigen]
== DPD Paketshop-Finder im Ceres-Checkout anzeigen

[IMPORTANT]
.Google Maps API Key benötigt
====
Damit du deinen Kunden im Ceres-Checkout den DPD Paketshop-Finder anbieten kannst, benötigst du einen Google Maps API Key.
====

Aktiviere im Menü *CMS » Container-Verknüpfungen* die folgenden Optionen, damit deine Kunden den DPD Paketshop-Finder im Ceres-Checkout nutzen können.

[.instruction]
DPD Paketshop-Finder im Ceres-Checkout anzeigen:

. Öffne das Menü *CMS » Container-Verknüpfungen*.
. Klappe den Bereich *DPD Parcelshop Finder Javascript (DPDShippingServices)* auf.
. Aktiviere die Option *Script loader: After scripts loaded*.
. Klappe den Bereich *DPD Parcelshop Finder checkout container (DPDShippingServices)* auf.
. Aktiviere die Option *Checkout: After shipping method*.
. Klappe den Bereich *DPD Parcelshop Finder checkout styles (DPDShippingServices)* auf.
. Aktiviere die Option *Checkout: After shipping method*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#verfuegbare-versandarten-und-services]
== Aktuell verfügbare Versandarten und Services

<<#tabelle-verfuegbare-versandarten-services>> listet alle Versandarten und Services auf, die aktuell über das Plugin *DPD Versand-Services* zur Verfügung stehen.

[[tabelle-verfuegbare-versandarten-services]]
.Aktuell verfügbare Versandarten und Services
[cols="1,3"]
|====
|Versandart |Service

| *DPD CLASSIC*
a|
* Ohne Service
* Lieferung ab Werk/Unfrei
* Predict SMS
* Predict E-Mail
* Reifen
* Austauschservice
* Gefahrgut +
*_Wichtig:_* Wenn du den Service _Gefahrgut_ nutzt, müssen für den Artikel bzw. die Variante Eigenschaften verknüpft werden. Beachte dazu die Informationen in der gelben Box unterhalb dieser Tabelle.

| *DPD CLASSIC*
a|
* Ohne Service
* Lieferung ab Werk/Unfrei
* Predict SMS
* Predict E-Mail
* Reifen
* Austauschservice
* Gefahrgut +
*_Wichtig:_* Wenn du den Service _Gefahrgut_ nutzt, müssen für den Artikel bzw. die Variante Eigenschaften verknüpft werden. Beachte dazu die Informationen in der gelben Box unterhalb dieser Tabelle.

| *DPD 8:30*
a|
* Ohne Service
* Lieferung ab Werk/Unfrei

| *DPD 10:00*
a|
* Austauschservice
* Ident-Check

| *DPD 12:00*
a|
* Ohne Service
* Samstagszustellung
* Lieferung ab Werk
* Austauschservice
* Ident-Check

| *DPD 18:00*
a|
* Ohne Service
* Garantie
* Lieferung ab Werk/Unfrei
* Ident-Check

| *DPD EXPRESS*
|Ohne Service

| *DPD ParcelLetter*
| Ohne Service

| *DPD Mail*
|Ohne Service
|====


[IMPORTANT]
.Hinweis zum Gefahrgut-Service
====
Wenn du den Service _Gefahrgut_ nutzt, musst du für den Artikel bzw. die Varianten im Tab *Texte* die folgenden Eigenschaften verknüpfen:

* DPD Versand Services - IdentificationUnNo
* DPD Versand Services - IdentificationClass
* DPD Versand Services - ClassificationCode
* DPD Versand Services - PackingGroup
* DPD Versand Services - Factor
* DPD Versand Services - NotOtherwiseSpecified
====

[#parcel-life-cycle]
== Parcel Life Cycle

Mit Hilfe deiner Delis ID kannst du im Menü *Daten » DPD Parcel Life Cycle* den aktuellen Status deiner Sendungen anhand der folgenden Kriterien anzeigen lassen:

* Paketscheinnummer (von DPD)
* Webnummer (von DPD)
* Auftrags-ID (von plentymarkets)

Gib die gewünschten Daten in die Felder ein und klicke auf *Suchen* (icon:search[role="blue"]).

[discrete]
=== Berechtigung für Backend-Benutzer vergeben

Nutzer vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs im plentymarkets Backend. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter mit diesem Nutzertyp mit dem Parcel Life Cycle arbeiten können, muss ein Nutzer vom Typ *Admin* das im folgenden beschriebene Recht für diesen Benutzer vergeben.

[.instruction]
Sichtbarkeit für Backend-Benutzer einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne den zu bearbeitenden Benutzer.
. Klappe den Bereich *Plugins > DPDShippingServices* auf.
. Wähle die Einstellung *DPD Parcel Life Cycle*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#tagesabschlussliste]
== Tagesabschlussliste

Im Menü *Daten » DPD Tagesabschlussliste* kannst du für ausgewählte oder alle über den Versanddienstleister *DPD Versand-Service* angemeldeten Aufträge eine Tagesabschlussliste erstellen und diese mit einem Klick auf *PDF erstellen* (icon:document[set=plenty]) als PDF-Datei auf deinem Computer speichern.

Klicke auf *Suchen* (icon:search[role="blue"]), um alle bei *DPD Versand-Services* angemeldeten Aufträge anzuzeigen. Über die Datumsauswahl kannst du eingrenzen, welche Aufträge in der Tagesabschlussliste enthalten sein sollen.

Du hast die Möglichkeit über die Dropdown-Liste *Ändere in Auftragsstatus* den Auftragsstatus der angemeldeten Aufträge direkt zu ändern.



[discrete]
=== Berechtigung für Backend-Benutzer vergeben

Nutzer vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs im plentymarkets Backend. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter mit diesem Nutzertyp mit der Tagesabschlussliste arbeiten können, muss ein Nutzer vom Typ *Admin* das im folgenden beschriebene Recht für diesen Benutzer vergeben.

[.instruction]
Sichtbarkeit für Backend-Benutzer einstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne den zu bearbeitenden Benutzer.
. Klappe den Bereich *Plugins > DPDShippingServices* auf.
. Wähle die Einstellung *DPD Tagesabschlussliste*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#ident-check]
== Ident-Check

Damit der Service _Ident-Check_ im Webshop für deine Kunden sichtbar ist, musst du im Menü *CMS » Container-Verknüpfungen* die folgenden Optionen aktivieren.

[.instruction]
Sichtbarkeit des Services _Ident-Check_ im Webshop einstellen: 

. Öffne das Menü *CMS » Container-Verknüpfungen*.
. Aktiviere im Bereich *DPD IdentCheck container (DPDShippingServices)* die Option *Checkout: After shipping method*.
. Aktiviere im Bereich *DPD IdentCheck styles (DPDShippingServices)* die Option *Template: Style*.
. Aktiviere im Bereich *DPD IdentCheck scripts (DPDShippingServices)* die Option *Script loader: After scripts loaded*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +


*_Wichtig:_* Verknüpfe anschließend den Service _Ident-Check_ mit dem Versandprofil für Ident-Check, damit der Service _Ident-Check_ für deine Kunden im Ceres-Checkout zur Verfügung steht.

[#retouren-anmelden]
== Retouren anmelden

Beachte, dass Retouren nur über DPD Versand-Services angemeldet werden können, wenn auch der Hauptauftrag der Retoure mit dem selben Versandprofil für DPD Versand-Services verknüpft ist.

[#retoure-anmelden-versand-center]
=== Retoure im Versand-Center anmelden

Du kannst über das Tab *Retoure* im Menü *Aufträge » Versand-Center* Retouren bei DPD anmelden.

Suche (icon:search[role="blue"]) dazu den Auftrag im Versand-Center im Tab *Suche* und setze ein Häckchen bei diesem Auftrag. Wechsele dann in das Tab *Retoure* und wähle aus der Dropdown-Liste *Retouren-Dienstleister* die Einstellung *DPD Retoure*. Klicke auf *Anmelden* (icon:cog[]), um die Retoure bei DPD anzumelden.

[#retoure-anmelden-prozess]
=== Retoure über einen Prozess anmelden

Ebenso kannst du die Retoure auch über einen Prozess anmelden. Wähle dazu im Prozess als Aktion *Retourenetikett* und anschließend aus der Dropdown-Liste *Retourentyp* die Einstellung *DPD Retoure*.
