= DPD Shipping UK
:lang: de
include::{includedir}/_header.adoc[]
:keywords: DPD Shipping UK, DPD Shipping, DPD UK, DPD für UK-Kunden,
:description: Erfahre, wie du das Plugin "DPD Shipping UK" in plentymarkets einrichtest.
:position: 500
:url: fulfillment/versanddienstleister-plugins/plugin-dpd-shipping-uk
:id: 0PL7WV9
:author: team-fulfillment

[IMPORTANT]
.DPD Shipping UK-Plugin herunterladen
====
Die Schnittstelle zu DPD UK wird über ein Plugin integriert. Um das DPD Shipping UK-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/plugins/integration/dpdshippinguk_5121[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

[#bei-dpd-uk-registrieren]
== Bei DPD UK registrieren

Um die Schnittstelle für DPD Shipping UK in deinem plentymarkets System einzurichten und die DPD-Services zu nutzen, registriere dich zunächst bei link:https://www.dpd.co.uk/content/products_services/uk_services.jsp[DPD UK^]{nbsp}icon:external-link[]. Du erhältst von DPD UK die Daten, die du für die Einstellungen in plentymarkets benötigst.

[#dpd-shipping-uk-einrichten]
== DPD Shipping UK in plentymarkets einrichten

[#vorbereitende-einstellungen]
=== Vorbereitende Einstellungen vornehmen

Zunächst musst du einige vorbereitende Einstellungen im plentymarkets Backend vornehmen:

* <<fulfillment/versand-vorbereiten#100, Lieferländer>> aktivieren
* <<fulfillment/versand-vorbereiten#400, Regionen>> erstellen
* den <<fulfillment/versand-vorbereiten#800, Versanddienstleister>> *DPD Shipping UK* erstellen
* <<fulfillment/versand-vorbereiten#1000, Versandprofil>> und <<fulfillment/versand-vorbereiten#1500, Portotabelle>> für *DPD Shipping UK* erstellen

Anschließend nimmst du die versanddienstleisterspezifischen Einstellungen zum Einrichten der Schnittstelle im plentymarkets Backend über die Benutzeroberfläche des Plugins im Menü *Einrichtung » Aufträge » Versand » DPD Shipping UK* vor.

[#schnittstelle-einrichten]
=== Schnittstelle einrichten

Sobald du das Plugin wie oben im aufklappbaren Bereich *Erste Schritte und Anforderungen* beschrieben installiert und das Plugin-Set gespeichert und bereitgestellt hast, ist das Plugin im Menü *Einrichtung » Aufträge » Versand* sichtbar.

Gehe wie in den folgenden Unterkapiteln beschrieben vor, um die Schnittstelle in plentymarkets einzurichten.

[#dpd-uk-grundeinstellungen]
==== Grundeinstellungen vornehmen

Im Menü *Grundeinstellungen* gibst du deine Zugangsdaten ein.

[.instruction]
Grundeinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Versand » DPD Shipping UK » Grundeinstellungen*.
. Wähle das DPD Produkt aus der Dropdown-Liste.
. Gib den Benutzernamen und das Passwort, wie von DPD erhalten, ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#dpd-uk-absenderdaten]
==== Absenderdaten eingeben

Im Menü *Absenderdaten* gibst du die Absenderadresse sowie Daten zur Kontaktperson ein.

[.instruction]
Absenderdaten eingeben:

. Öffne das Menü *Einrichtung » Aufträge » Versand » DPD Shipping UK » Absenderdaten*.
. Klicke auf *Adresse anlegen* (icon:plus-square[role="green"]).
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-dpd-shipping-uk-absenderdaten>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-dpd-shipping-uk-absenderdaten]]
.Absenderdaten für DPD Shipping UK eingeben
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+| *Firma*

| *Name*
|Firmenname eingeben.

2+| *Absenderadresse*

| *Straße*, *Hausnummer*, *PLZ*, *Stadt*
|Daten des Absenders eingeben.

| *Land*
|Land aus der Dropdown-Liste wählen.

2+| *Kontaktperson*

| *Name*, *E-Mail-Adresse*, *Telefonnummer*
|Daten der Kontaktperson, die bei Rückfragen von DPD kontaktiert werden soll, eingeben.

|====

[#dpd-uk-versandeinstellungen]
==== Versandeinstellungen vornehmen

Im Menü *Versandeinstellungen* verknüpfst du das Versandprofil, die Versandregion, die Absenderadresse und die DPD-Services.

[.instruction]
Versandeinstellungen vornehmen:

. Öffne das Menü *Einrichtung » Aufträge » Versand » DPD Shipping UK » Versandeinstellungen*.
. Klicke auf *Versandeinstellung hinzufügen* (icon:plus-square[role="green"]).
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-dpd-shipping-uk-versandeinstellungen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-dpd-shipping-uk-versandeinstellungen]]
.Versandeinstellungen für DPD Shipping UK vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Zugangsdaten*
|Zugangsdaten aus der Dropdown-Liste wählen.

| *Versanddienstleister*
| *DPD Shipping UK* aus der Dropdown-Liste wählen.

| *Versandprofil*
|Versandprofil aus der Dropdown-Liste wählen.

| *Versandregion*
|Versandregion aus der Dropdown-Liste wählen.

| *Absenderadresse*
|Absenderadresse aus der Dropdown-Liste wählen.

| *Versandservices*
|Versandservice aus der Dropdown-Liste wählen. Diese können je nach DPD-Vertrag variieren.

|====
