= postNL
:lang: de
include::{includedir}/_header.adoc[]
:keywords: postNL, postnl, post.nl, post-nl, Post Niederlande
:description: Erfahre, wie du das Plugin "postNL" in plentymarkets einrichtest.
:position: 600
:url: fulfillment/versanddienstleister-plugins/plugin-post-nl
:id: 97CN7P2
:author: team-fulfillment

[IMPORTANT]
.postNL-Plugin herunterladen
====
Die Schnittstelle zu postNL wird über ein Plugin integriert. Um das postNL-Plugin nutzen zu können, lade das Plugin im link:LINKEINFÜGEN[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

[#bei-post-nl-registrieren]
== Bei postNL registrieren

Mit dem Plugin *postNL* können Versender aus den Niederlanden schnell und einfach Versandlabels erstellen und die Sendungsverfolgung in plentymarkets nutzen.

Um die Schnittstelle für postNL in deinem plentymarkets System einrichten und nutzen zu können, musst du dich bei link:https://www.postnl.be/en/log-in-business/[postNL^]{nbsp}icon:external-link[] registrieren. Du erhältst von postNL die Daten, die du für die Einstellungen in plentymarkets benötigst. Kontaktierte ggf. deinen Account Manager bei postNL.

[#post-nl-einrichten]
== postNL in plentymarkets einrichten

[#vorbereitende-einstellungen]
=== Vorbereitende Einstellungen vornehmen

Zunächst musst du einige vorbereitende Einstellungen im plentymarkets Backend vornehmen:

* <<fulfillment/versand-vorbereiten#100, Lieferländer>> einrichten
* <<fulfillment/versand-vorbereiten#400, Regionen>> erstellen
* den <<fulfillment/versand-vorbereiten#800, Versanddienstleister>> *postNL* erstellen
* <<fulfillment/versand-vorbereiten#1000, Versandprofil>> und <<fulfillment/versand-vorbereiten#1500, Portotabelle>> für *postNL* erstellen

[#assistenten-durchlaufen]
=== Assistent durchlaufen

Sobald du das <<plugins/hinzugefuegte-plugins-installieren#plugin-installieren, Plugin in einem Plugin-Set installiert>> hast, ist der postNL-Assistenten im Menü *Einrichtung » Assistenten* im Bereich *Integration* sichtbar und du kannst mit dem Einrichten beginnen.

Durchlaufe den Assistenten, um die Schnittstelle in plentymarkets einzurichten.

Wenn du den Assistenten abgeschlossen hast und diesen erneut öffnest, werden die folgenden Informationen angezeigt:

* In der Kachelansicht:

** Backend-Name
** Login-Name
** Versandart

* In der Tabellenübersicht:

** Backend-Name
** Login-Name
** Versandart
** Services
** ID des Versandprofils

[#verfuegbare-versandarten-und-services]
== Aktuell verfügbare Versandarten und Services

<<#tabelle-verfuegbare-versandarten-services>> listet alle Versandarten und Services auf, die aktuell über das Plugin *postNL* zur Verfügung stehen.

[[tabelle-verfuegbare-versandarten-services]]
.Aktuell verfügbare Versandarten und Services
[cols="1,3"]
|====
|Versandart |Service

|
|

|
|

|
|

|====
