= postNL
:lang: de
include::{includedir}/_header.adoc[]
:keywords: postNL, postnl, post.nl, post-nl, Post Niederlande
:description: Erfahre, wie du das Plugin "postNL" in plentymarkets einrichtest.
:position: 600
:url: fulfillment/versanddienstleister-plugins/plugin-post-nl
:id: 97CN7P2
:author: team-fulfillment

[IMPORTANT]
.postNL-Plugin herunterladen
====
Die Schnittstelle zu postNL wird über ein Plugin integriert. Um das postNL-Plugin nutzen zu können, lade das Plugin im link:LINKEINFÜGEN[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

// bei plentyMarketplace den Link zum Plugin einfügen - insgesamt 3 Mal auf dieser Seite

[#bei-post-nl-registrieren]
== Bei postNL registrieren

Mit dem Plugin *postNL* können Versender aus den Niederlanden schnell und einfach Versandlabels erstellen und die Sendungsverfolgung in plentymarkets nutzen.

Um die Schnittstelle für postNL in deinem plentymarkets System einrichten und nutzen zu können, musst du dich bei link:https://www.postnl.be/en/log-in-business/[postNL^]{nbsp}icon:external-link[] registrieren. Du erhältst von postNL die Daten, die du für die Einstellungen in plentymarkets benötigst. Kontaktierte ggf. deinen Account Manager bei postNL.

[#post-nl-einrichten]
== postNL in plentymarkets einrichten

[TIP]
.postNL mit Hilfe eines Assistenten einfach einrichten
====
Die Schnittstelle zu postNL wird über ein Plugin integriert. Um das postNL-Plugin nutzen zu können, lade das Plugin im link:LINKEINFÜGEN[plentyMarketplace^]{nbsp}icon:external-link[] herunter. +
Dir steht dann zum einfachen Einrichten ein postNL-Assistent im Menü *Einrichtung » Assistenten » Plugins* im relevanten Plugin-Set zur Verfügung.

Bevor du den postNL-Assistenten durchläufst, durchlaufe den Assistenten *Versandeinstellungen*. Dieser Assistent ist standardmäßig in deinem plentymarkets System im Menü *Einrichtung » Assistenten » Integration* vorhanden. Mit diesem Assistenten nimmst du die folgenden Einstellungen vor:

* der Versandeinstellung (sprich: dem Versandprofil) einen Namen geben
* vorhandene Regionen aktivieren oder eine neue Region erstellen
* die Versandkosten festlegen und den Berechnungstypen wählen
* *_Hinweis:_* Weitere Einstellungen müssen anschließend im Versandprofil im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* vorgenommen werden. Weitere Hinweise dazu findest du weiter unten auf dieser Handbuchseite.

Anschließend durchläufst du den postNL-Assistenten.
====

[#vorbereitende-einstellungen]
== Vorbereitende Einstellungen vornehmen

Zunächst musst du einige vorbereitende Einstellungen vornehmen:

* <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>

** Lieferländer kannst du über den Assistenten *Versandeinstellungen* oder im Backend einrichten.

* <<fulfillment/versand-vorbereiten#400, Regionen erstellen>>
** Regionen kannst du über den Assistenten *Versandeinstellungen* oder im Backend erstellen.

* den <<fulfillment/versand-vorbereiten#800, Versanddienstleister>> *postNL* erstellen
** Versanddienstleister kannst du aktuell nur im Backend und _nicht_ über einen Assistenten erstellen.

* <<fulfillment/versand-vorbereiten#1000, Versandprofile>> und <<fulfillment/versand-vorbereiten#1500, Portotabellen>> für *postNL* erstellen +
** Einige der Versandeinstellungen kannst du über den Assistenten *Versandeinstellungen* einrichten. Die restlichen Einstellungen nimmst du im Backend im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* vor. +
icon:exclamation-triangle[role="red"] *_Wichtig:_* Es wurden noch nicht alle Funktionen und Einstellungen aus dem Versandprofil in den Assistenten *Versandeinstellungen* übernommen. Beachte dazu die Erläuterungen im Kapitel <<#assistent-versandeinstellungen, Assistent *Versandeinstellungen* durchlaufen>>.

[#assistenten-durchlaufen]
== Assistenten durchlaufen

Sobald du das <<plugins/hinzugefuegte-plugins-installieren#plugin-installieren, Plugin in einem Plugin-Set installiert>> hast, ist der postNL-Assistenten im Menü *Einrichtung » Assistenten » Plugins* im relevanten Plugin-Set verfügbar und du kannst mit dem Einrichten beginnen. Der Assistent *Versandeinstellungen* ist standardmäßig in deinem plentymarkets System im Menü *Einrichtung » Assistenten » Integration** vorhanden.

Durchlaufe nun die Assistenten in der folgenden Reihenfolge:

1. *Versandeinstellungen*
2. *postNL*

[#assistent-versandeinstellungen]
=== Assistent *Versandeinstellungen* durchlaufen

Du findest den Assistenten *Versandeinstellungen* im Menü *Einrichtung » Assistenten » Integration*. In diesem Assistenten nimmst du die folgenden Einstellung vor:

* Du gibst der Versandeinstellung einen Backend-Namen und einen Frontend-Namen. Diese Namen können pro Sprache gewählt werden. +
 ** Diesen Namen verknüpfst du später im Assistenten *postNL*.

* Du wählst das Plugin des Versanddienstleisters, für den du die Versandkosten einrichten möchtest. +
 ** Das postNL-Plugin muss im link:LINKEINFÜGEN[plentyMarketplace^]{nbsp}icon:external-link[] heruntergeladen worden sein, damit es dir hier angezeigt wird.

* Du wählst eine Region, gibst die Versandkosten ein und wählst den Berechnungstypen für die gewählten Länder. Außerdem kannst du festlegen, ab welchem Warenwert keine Versandkosten für deine Kund:innen berechnet werden.

[IMPORTANT]
.Weitere Einstellungen für die Versandeinstellung im Backend vornehmen
====
Wenn du den Assistenten *Versandeinstellungen* abgeschlossen hast, wird das Versandprofil auch im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* angezeigt. +
Die folgenden Einstellungen sind mit Abschluss des Assistenten bereits vorhanden:

* der Name des Versandprofils ist gespeichert
* der Versanddienstleister ist gespeichert
* die Option *Bei neuen Artikeln aktiveren* ist aktiviert
* alle Mandanten (Shops) sind aktiviert
* alle Auftragsherkünfte sind aktiviert
* die Versandkosten sind gespeichert
* die Region ist gespeichert

Wenn du weitere Einstellungen vornehmen möchtest wie z.B. das Sperren von Kundenklassen oder Zahlungsarten oder dem Aktivieren der Option zum Einwilligen der Datenübermittlung an Versanddienstleister, musst du diese im entsprechenden Versandprofil im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* vornehmen.

icon:exclamation-triangle[role="red"] Dieses Vorgehen ist notwendig, weil noch nicht alle Funktionen und Einstellungen aus dem Versandprofil in den Assistenten übernommen wurden. Wir ergänzen die fehlenden Einstellungen sukzessive im Assistenten.
====

Wenn du den Assistenten *Versandeinstellungen* abgeschlossen hast und diesen erneut öffnest, werden die folgenden Informationen angezeigt:

* In der Kachelansicht:

** Backend-Name
** Region
** Versanddienstleister

* In der Tabellenübersicht:

** Backend-Name
** Region
** Versanddienstleister
** Frontend-Name
** ID des Versandprofils

[#post-nl-assistenten-durchlaufen]
=== Assistent *postNL* durchlaufen

Du findest den Assistenten *postNL* im Menü *Einrichtung » Assistenten » Plugins* im relevanten Plugin-Set. Im Folgenden werden die einzelnen Schritte, die du in diesem Assistenten durchläufst, beschrieben.

[discrete]
==== Globale Einstellungen

In diesem Schritt legst du fest, ob du die globalen Einstellungen ändern möchtest.

Wenn die Option aktiviert (icon:toggle-on[role="green"]) ist, kannst du jederzeit Änderungen in den Schritten *Zugangsdaten*, *Absenderdaten* und *Angaben auf dem Label* vornehmen. Wenn die Option deaktiviert (icon:toggle-off[role="red"]) ist, ist nur der Schritt *Einstellungsverknüpfung* sichtbar und änderbar.

[discrete]
==== Zugangsdaten

In diesem Schritt gibst du deine Zugangsdaten in Form deines API-Schlüssels ein. Gib jedem API-Schlüssel, den du eingibst, im Feld *Name des API-Schlüssels* einen Namen deiner Wahl. Mit einem Klick auf icon:plus-square[role="green"] fügst du weitere Zugangsdaten hinzu.

[discrete]
==== Absenderdaten

In diesem Schritt gibst du deine Absenderadresse ein. Mit einem Klick auf icon:plus-square[role="green"] fügst du weitere Absenderadressen hinzu.

[discrete]
==== Angaben auf dem Label

In diesem Schritt wählst du, welche Angaben auf dem Versandlabel angezeigt werden sollen. Du kannst die folgenden Werte wählen:

* Keine Angabe
* Auftrags-ID
* Externe Auftrags-ID
* Auftrags-ID + externe Auftrags-ID

[discrete]
==== Einstellungsverknüpfung

In diesem Schritt verknüpfst du die Einstellungen, die du zuvor im Assistenten *Versandeinstellungen* und in den einzelnen Schritten des *postNL*-Assistenten vorgenommen hast. Du verknüpfst deine Versandeinstellung mit deinen Zugangsdaten, den Produkten und Services, der Absenderadresse und der Artikelbeschreibung.

Wenn du ein <<#verfuegbare-versandarten-und-services, Produkt>> wählst, werden in einer Liste darunter die <<#verfuegbare-versandarten-und-services, zugehörigen Services>> geladen, die du dann wählen kannst. Beachte, dass du dich für bestimmte Produkte und Services von deinem Account Manager bei postNL freischalten lassen musst.

Die Artikelbeschreibung bezieht sich auf die Werte, die du im Menü *Artikel » Artikel bearbeiten* » _Artikel öffnen_ im Tab *Texte* in den Feldern *Name 1*, *Name 2*, *Name 3* und *Vorschautext* gespeichert hast. Du kannst in diesem Schritt eines dieser vier Felder wählen.

Außerdem wählst du in diesem Schritt, ob du den Produktivmodus oder den Testmodus aktivieren möchtest.

Wenn du international versendest (icon:toggle-on[role="green"]), musst du zusätzlich noch den Zollerklärungstyp und die Standardzollnummer eingeben.

[discrete]
==== Zusammenfassung

In diesem Schritt wird eine Zusammenfassung aller getätigten Eingaben in den einzelnen Schritten aufgelistet. Du kannst deine Angaben prüfen, in den einzelnen Schritten ggf. Anpassungen vornehmen und den Assistenten danach über die Zusammenfassung abschließen.

Wenn du den Assistenten *postNL* abgeschlossen hast und diesen erneut öffnest, werden die folgenden Informationen angezeigt:

* In der Kachelansicht:

** Versandeinstellung
** Region
** Name des API-Schlüssels

* In der Tabellenübersicht:

** Versandeinstellung
** Region
** Name des API-Schlüssels

[#verfuegbare-versandarten-und-services]
== Aktuell verfügbare Produkte und Services

<<#tabelle-verfuegbare-produkte-services>> listet alle Produkte und Services auf, die aktuell über das Plugin *postNL* zur Verfügung stehen. Beachte, dass du dich für bestimmte Produkte und Services von deinem Account Manager bei postNL freischalten lassen musst.

[[tabelle-verfuegbare-produkte-services]]
.Aktuell verfügbare Produkte und Services
[cols="1,3"]
|====
|Produkt |Service

|Inländische Produkte (Zielort Niederlande)
a|
* Inländische Produkte +
** Standardlieferung +
** Lieferung an die angegebene Adresse +
** Lieferung an den Nachbarn + Retoure bei Nichtantreffen der Person +
** Lieferung an die angegebene Adresse + Retoure bei Nichtantreffen der Person
* Abholstellen +
* Standardabholstellen  +
Dies sind z.B. ausgewählte Supermärkte und Buchhandlungen.
* Briefkastensendung +
* Smarte Retouren +
Deine Kund:innen können über einen Barcode auf dem Smartphone das Retourenlabel in einer postNL-Filiale drucken lassen.
* Abendzustellung +
Die Zustellung erfolgt zwischen 18:00 und 22:00 Uhr.
* Sonntagszustellung +
Die Zustellung erfolgt zwischen 12:00 und 18:00 Uhr.
* Zustellung am selben Tag +
Die Zustellung erfolgt zwischen 18:00 und 22:00 Uhr, wenn die Bestellung vor der Mittagszeit eingegangen ist. Kontaktiere deinen Account Manager bei postNL bezüglich der genauen Zeit.
* Garantierte Zustellung / Morgenzustellung +
** an Werktagen vor 9:00 Uhr +
** an Werktagen vor 10:00 Uhr +
** an Werktagen vor 12:00 Uhr +
** an Werktagen vor 17:00 Uhr


|Zielort EU
|Pakete EU +
Aktuell ist der Versand aus den Niederlanden in 27 Länder möglich. Kontaktiere ggf. deinen Account Manager bei postNL für weitere Informationen.


|Zielort Rest der Welt
|GlobalPack-Produkte

|Internationale Brief- und Paketsendungen
|Internationale Brief- und Paketsendungen +
Mögliche Optionen: +
 _Nachverfolgt_, _Nicht verfolgt_ und _Registriert_


|====

[#auftrag-anmelden]
== Auftrag anmelden

Im Menü *Aufträge » Versand-Center* im Tab *Anmelden* meldest du deine Aufträge bei postNL an und überträgst gleichzeitig die Auftragsdaten an postNL. Gehe wie im Folgenden beschrieben vor.

[.instruction]
. Öffne das Menü *Aufträge » Versand-Center*.
. Wähle aus der Dropdown-Liste *Versandstatus* die Option *offen*.
. Wähle aus der Dropdown-Liste *Versanddienstleister* die Option *postNL*.
. Klicke auf die Lupe (icon:search[role="blue"]). +
→ Die offenen Versandaufträge für postNL werden angezeigt.
. Wechsele in das Tab *Anmelden*.
. Wähle aus der Dropdown-Liste *Versanddienstleister* die Option *postNL*.
. Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* den Auftragsstatus, den die Aufträge nach erfolgreicher Anmeldung erhalten sollen. +
*_Hinweis:_* Diese Funktion kann mit einer <<automatisierung/ereignisaktionen#, Ereignisaktion>>, die z.B. automatisch den Warenausgang bucht, kombiniert werden.
. Aktiviere die Aufträge, die du bei postNL anmelden möchtest.
. Klicke auf *Anmelden* (icon:cog[]), um die Auftragsdaten an postNL zu übertragen.

Weitere Informationen zum Anmelden von Aufträgen findest du auf der Handbuchseite <<fulfillment/versand-center#, Versand-Center nutzen>>.
