= DHL Retoure Online
:lang: de
include::{includedir}/_header.adoc[]
:keywords: DHL Retoure Online, DHL Retoure, DHL return, Retouren anmelden, Retouren mit DHL, Retouren mit DHL anmelden, DHL Retoure Plugin, DHL Retourenlabel, DHL Retourenlabels, DHL Retourenetikett, DHL Retourenetiketten, DHL Retoure Online Assistent
:description: Erfahre, wie du das Plugin "DHL Retoure Online" in plentymarkets einrichtest.
:position: 300
:url: fulfillment/versanddienstleister-plugins/plugin-dhl-retoure-online
:id: QDSZAQP
:author: team-fulfillment

[IMPORTANT]
.DHL Retoure Online-Plugin herunterladen
====
Die Schnittstelle zu DHL Retoure Online wird über ein Plugin integriert. Um das DHL Retoure Online-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/dhlretoureonline_6714[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

[#bei-dhl-registrieren]
== Bei DHL registrieren

DHL Retoure Online ermöglicht das Generieren von Retourenlabels für Aufträge aus verschiedenen Lieferländern. Du kannst die Labels automatisch über eine Ereignisaktion oder Prozesse generieren. Alternativ kannst du die Labels im Versand-Center generieren und herunterladen. Anschließend kannst du dir eine Ereignisaktion einrichten, die die Labels dann automatisiert als Anhang per E-Mail an deine Kunden sendet.

Um die Schnittstelle für DHL Retoure Online in deinem plentymarkets System einrichten und nutzen zu können, musst du dich bei link:https://www.dhl-geschaeftskundenportal.de/webcenter/portal/gkpExternal?_afrLoop=12432432775987711&_adf.ctrl-state=lwx2h5jko_2#!%40%40%3F_afrLoop%3D12432432775987711%26_adf.ctrl-state%3Dlwx2h5jko_6[DHL^]{nbsp}icon:external-link[] registrieren und deinen Account für DHL Retoure freischalten lassen. Du erhältst von DHL die Daten, die du für die Einstellungen in plentymarkets benötigst.

[#dhl-retoure-online-einrichten]
== DHL Retoure Online in plentymarkets einrichten

Du benötigst ein Lager, um die Informationen, die du von DHL für Retouren erhältst, zu speichern. Außerdem legst du fest, wie lange die Labels in deinem Webshop deinen Kunden zum Download zur Verfügung stehen.

[discrete]
=== Assistent durchlaufen

Sobald du das <<plugins/hinzugefuegte-plugins-installieren#plugin-installieren, Plugin in einem Plugin-Set installiert>> hast, ist der Assistent im Menü *Einrichtung » Assistenten* im Bereich *Integration* sichtbar und du kannst mit dem Einrichten beginnen.

Durchlaufe den Assistenten *DHL Retoure Online*, um die Schnittstelle in plentymarkets Schritt für Schritt einzurichten.

[#optionen-retourenlabels-generieren]
== Optionen für das Generieren von Retourenlabels

Für das Generieren von Retourenlabels und die Retourenanmeldung bei DHL Retoure Online stehen dir die folgenden Optionen zur Verfügung:

* *DHL Retoure Online-Label generieren* +
Meldet die Retoure bei DHL Retoure Online an. Unabhängig von der Paketanzahl wird ein Label pro Auftrag generiert.

* *DHL Retoure Online-Label generieren (1 Label/Paket: 1 Datei)* +
Meldet die Retoure bei DHL Retoure Online an. Pro Paket wird ein Label generiert. Wenn mehrere Pakete vorhanden sind, wird eine PDF-Datei mit allen Retourenlabels generiert.

* *DHL Retoure Online-Label generieren (1 Label/Paket: mehrere Dateien)* +
Meldet die Retoure bei DHL Retoure Online an. Pro Paket wird ein Label generiert. Wenn mehrere Pakete vorhanden sind, wird jeweils eine PDF-Datei pro Retourenlabel generiert.

Die oben genannten Optionen kannst du in den folgenden Bereichen des plentymarkets Backend wählen:

* in der Aktionsgruppe *Plugins* der Ereignisaktionen
* als *Retourentyp* in der Aktion *Retourenetikett* in Prozessen
* im Tab *Retoure* des Versand-Centers

[discrete]
=== Internationale Retouren

Es ist möglich, DHL Retoure Online-Labels nicht nur für Retouren aus Deutschland, sondern auch für Retouren aus der Schweiz zu generieren. Das CN23-Formular wird beim Anmelden der Retoure dann als PDF-Datei hinzugefügt.

Außerdem kannst du DHL Retourenbeilegeretiketten für internationale Retouren in den Prozessen und in den Ereignisaktionen generieren:

* In den Prozessen nutzt du die Option *DHL Retoure Beileger international*.
* In den Ereignisaktionen wählst du die Aktion *DHL Retoure Beileger international generieren*.
