= postNL
:lang: de
include::{includedir}/_header.adoc[]
:keywords: postNL, postnl, post.nl, post-nl, Post Niederlande
:description: Erfahre, wie du das Plugin "postNL" in plentymarkets einrichtest.
:position: 600
:url: fulfillment/versanddienstleister-plugins/plugin-post-nl
:id: 97CN7P2
:author: team-fulfillment

[IMPORTANT]
.postNL-Plugin herunterladen
====
Die Schnittstelle zu postNL wird über ein Plugin integriert. Um das postNL-Plugin nutzen zu können, lade das Plugin im link:LINKEINFÜGEN[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

[#bei-post-nl-registrieren]
== Bei postNL registrieren

Mit dem Plugin *postNL* können Versender aus den Niederlanden schnell und einfach Versandlabels erstellen und die Sendungsverfolgung in plentymarkets nutzen.

Um die Schnittstelle für postNL in deinem plentymarkets System einrichten und nutzen zu können, musst du dich bei link:https://www.postnl.be/en/log-in-business/[postNL^]{nbsp}icon:external-link[] registrieren. Du erhältst von postNL die Daten, die du für die Einstellungen in plentymarkets benötigst. Kontaktierte ggf. deinen Account Manager bei postNL.

[#post-nl-einrichten]
== postNL in plentymarkets einrichten

[TIP]
.postNL mit Hilfe eines Assistenten einfach einrichten
====
Die Schnittstelle zu postNL wird über ein Plugin integriert. Um das postNL-Plugin nutzen zu können, lade das Plugin im link:LINKEINFÜGEN[plentyMarketplace^]{nbsp}icon:external-link[] herunter. +
Dir steht dann zum einfachen Einrichten ein postNL-Assistent im Menü *Einrichtung » Assistenten » Plugins* im relevanten Plugin-Set zur Verfügung.

Bevor du den postNL-Assistenten durchläufst, durchlaufe den Assistenten *Versandeinstellungen*. Dieser Assistent ist standardmäßig in deinem plentymarkets System im Menü *Einrichtung » Assistenten » Integration* vorhanden. Mit diesem Assistenten nimmst du die folgenden Einstellungen vor:

* der Versandeinstellung (sprich: dem Versandprofil) einen Namen geben
* vorhandene Regionen aktivieren oder eine neue Region erstellen
* die Versandkosten festlegen und den Berechnungstypen wählen
* *_Hinweis:_* Weitere Einstellungen müssen anschließend im Versandprofil im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* vorgenommen werden. Weitere Hinweise dazu findest du weiter unten auf dieser Handbuchseite.

Anschließend durchläufst du den beiden postNL-Assistenten.
====

[#vorbereitende-einstellungen]
== Vorbereitende Einstellungen vornehmen

Zunächst musst du einige vorbereitende Einstellungen vornehmen:

* <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>

** Lieferländer kannst du über den Assistenten *Versandeinstellungen* oder im Backend einrichten.

* <<fulfillment/versand-vorbereiten#400, Regionen erstellen>>
** Regionen kannst du über den Assistenten *Versandeinstellungen* oder im Backend erstellen.

* den <<fulfillment/versand-vorbereiten#800, Versanddienstleister>> *postNL* erstellen
** Versanddienstleister kannst du aktuell nur im Backend und _nicht_ über einen Assistenten erstellen.

* <<fulfillment/versand-vorbereiten#1000, Versandprofile>> und <<fulfillment/versand-vorbereiten#1500, Portotabellen>> für *postNL* erstellen +
** Einige der Versandeinstellungen kannst du über den Assistenten *Versandeinstellungen* einrichten. Die restlichen Einstellungen nimmst du im Backend im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* vor. +
icon:exclamation-triangle[role="red"] *_Wichtig:_* Es wurden noch nicht alle Funktionen und Einstellungen aus dem Versandprofil in den Assistenten *Versandeinstellungen* übernommen. Beachte dazu die Erläuterungen im Kapitel <<#assistent-versandeinstellungen, Assistent *Versandeinstellungen* durchlaufen>>.


[#assistenten-durchlaufen]
== Assistenten durchlaufen

Sobald du das <<plugins/hinzugefuegte-plugins-installieren#plugin-installieren, Plugin in einem Plugin-Set installiert>> hast, ist der postNL-Assistenten im Menü *Einrichtung » Assistenten » Plugins* im relevanten Plugin-Set verfügbar und du kannst mit dem Einrichten beginnen. Der Assistent *Versandeinstellungen* ist standardmäßig in deinem plentymarkets System im Menü *Einrichtung » Assistenten » Integration** vorhanden.

Durchlaufe nun die Assistenten in der folgenden Reihenfolge:

1. *Versandeinstellungen*
2. *postNL*

[#assistent-versandeinstellungen]
=== Assistent *Versandeinstellungen* durchlaufen

Du findest den Assistenten *Versandeinstellungen* im Menü *Einrichtung » Assistenten » Integration*. In diesem Assistenten nimmst du die folgenden Einstellung vor:

* Du gibst der Versandeinstellung einen Backend-Namen und einen Frontend-Namen. Diese Namen können pro Sprache gewählt werden. +
 ** Diesen Namen verknüpfst du später im Assistenten *postNL*.

* Du wählst das Plugin des Versanddienstleisters, für den du die Versandkosten einrichten möchtest. +
 ** Das postNL-Plugin muss im link:LINKEINFÜGEN[plentyMarketplace^]{nbsp}icon:external-link[] heruntergeladen worden sein, damit es dir hier angezeigt wird.

* Du wählst eine Region, gibst die Versandkosten ein und wählst den Berechnungstypen für die gewählten Länder. Außerdem kannst du festlegen, ab welchem Warenwert keine Versandkosten für deine Kund:innen berechnet werden.

[IMPORTANT]
.Weitere Einstellungen für die Versandeinstellung im Backend vornehmen
====
Wenn du den Assistenten *Versandeinstellungen* abgeschlossen hast, wird das Versandprofil auch im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* angezeigt. +
Die folgenden Einstellungen sind mit Abschluss des Assistenten bereits vorhanden:

* der Name des Versandprofils ist gespeichert
* der Versanddienstleister ist gespeichert
* die Option *Bei neuen Artikeln aktiveren* ist aktiviert
* alle Mandanten (Shops) sind aktiviert
* alle Auftragsherkünfte sind aktiviert
* die Versandkosten sind gespeichert
* die Region ist gespeichert

Wenn du weitere Einstellungen vornehmen möchtest wie z.B. das Sperren von Kundenklassen oder Zahlungsarten oder dem Aktivieren der Option zum Einwilligen der Datenübermittlung an Versanddienstleister, musst du diese im entsprechenden Versandprofil im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* vornehmen.

icon:exclamation-triangle[role="red"] Dieses Vorgehen ist notwendig, weil noch nicht alle Funktionen und Einstellungen aus dem Versandprofil in den Assistenten übernommen wurden. Wir ergänzen die fehlenden Einstellungen sukzessive im Assistenten.
====

Wenn du den Assistenten *Versandeinstellungen* abgeschlossen hast und diesen erneut öffnest, werden die folgenden Informationen angezeigt:

* In der Kachelansicht:

** Backend-Name
** Region
** Versanddienstleister

* In der Tabellenübersicht:

** Backend-Name
** Region
** Versanddienstleister
** Frontend-Name
** ID des Versandprofils

[#post-nl-assistenten-durchlaufen]
=== Assistent *postNL* durchlaufen

Im Folgenden werden die einzelnen Schritte, die du in diesem Assistenten durchläufst, beschrieben.

[discrete]
==== Globale Einstellungen

Text

[discrete]
==== Zugangsdaten

Text

[discrete]
==== Absenderdaten

Text

[discrete]
==== Produkt- und Serviceauswahl

Text

[discrete]
==== Angaben auf dem Label

Text

[discrete]
==== Einstellungsverknüpfung

Text

[discrete]
==== Zusammenfassung

Text






Wenn du den postNL-Assistenten abgeschlossen hast und diesen erneut öffnest, werden die folgenden Informationen angezeigt:

* In der Kachelansicht:

** Backend-Name
** Login-Name
** Versandart

* In der Tabellenübersicht:

** Backend-Name
** Login-Name
** Versandart
** Services
** ID des Versandprofils

[#verfuegbare-versandarten-und-services]
== Aktuell verfügbare Versandarten und Services

<<#tabelle-verfuegbare-versandarten-services>> listet alle Versandarten und Services auf, die aktuell über das Plugin *postNL* zur Verfügung stehen.

[[tabelle-verfuegbare-versandarten-services]]
.Aktuell verfügbare Versandarten und Services
[cols="1,3"]
|====
|Versandart |Service

|
|

|
|

|
|

|====
