= DHL Shipping (Versenden)
:lang: de
include::{includedir}/_header.adoc[]
:keywords: DHL Shipping, DHL Versenden, DHL Shipping (Versenden), DHL Shipping Versenden, DHL Plugin, Plugin DHL, DHL Geschäftskundenportal, DHL GKP, DHL Assistent, DHL Shipping Assistent, DHL Versenden Assistent
:description: Erfahre, wie du das Plugin "DHL Shipping (Versenden)" in plentymarkets einrichtest.
:position: 100
:url: fulfillment/versanddienstleister-plugins/plugin-dhl-shipping-versenden
:id: X5EPVD8
:author: team-fulfillment

[IMPORTANT]
.DHL Shipping (Versenden)-Plugin herunterladen
====
Die Schnittstelle zu DHL Shipping (Versenden) wird über ein Plugin integriert. Um das DHL Shipping (Versenden)-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/plugins/integration/dhlshipping_4871[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

[#bei-dhl-registrieren]
== Bei DHL registrieren

Um die Schnittstelle für DHL Shipping (Versenden) in deinem plentymarkets System einzurichten und die Funktion _Versenden_ im DHL Geschäftskundenportal zu nutzen, musst du bei link:https://www.dhl.de/de/geschaeftskunden/paket/kunde-werden/angebot-dhl-geschaeftskunden-online.html?cid=c_dhl.de_ke_Z353_20190016_5902_A3045[DHL^]{nbsp}icon:external-link[] registriert sein. Du erhältst von DHL die Daten, die du für die Einstellungen in plentymarkets benötigst.

[#dhl-shipping-versenden-einrichten]
== DHL Shipping (Versenden) in plentymarkets einrichten

[IMPORTANT]
.DHL Shipping (Versenden) mit Hilfe von Assistenten einfach einrichten
====
Die Schnittstelle zu DHL Shipping (Versenden) wird über ein Plugin integriert. Um das DHL Shipping (Versenden)-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/plugins/integration/dhlshipping_4871[plentyMarketplace^]{nbsp}icon:external-link[] herunter. +
Dir stehen dann zum einfachen Einrichten zwei DHL Shipping (Versenden)-Assistenten im Menü *Einrichtung » Assistenten* im Bereich *Integration* zur Verfügung.

Bevor du die beiden DHL Shipping (Versenden)-Assistenten durchläufst, durchlaufe den Assistenten *Versandeinstellungen*. Dieser Assistent ist standardmäßig in deinem plentymarkets System im Menü *Einrichtung » Assistenten* im Bereich *Integration* vorhanden. Mit diesem Assistenten nimmst du die folgenden Einstellungen vor:

* der Versandeinstellung (sprich: dem Versandprofil) einen Namen geben
* vorhandene Regionen aktivieren oder eine neue Region erstellen
* die Versandkosten festlegen und den Berechnungstypen wählen
* *_Hinweis:_* Weitere Einstellungen müssen anschließend im Versandprofil im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* vorgenommen werden.

Anschließend durchläufst du die beiden DHL Shipping (Versenden)-Assistenten:

* DHL Shipping (Versenden): Grundeinstellungen +
→ In diesem Assistenten bereitest du alle Daten vor, die du später im Assistenten *DHL Shipping (Versenden): Einstellungsverknüpfung* benötigst.
* DHL Shipping (Versenden): Einstellungsverknüpfung +
→ In diesem Assistenten verknüpfst du die Einstellungen, die du im Assistenten *DHL Shipping (Versenden): Grundeinstellungen* gespeichert hast.


====

Welche Daten du in den Assistenten eingibst, ist weiter unten auf dieser Seite beschrieben.

[#vorbereitende-einstellungen]
== Vorbereitende Einstellungen vornehmen

Zunächst musst du einige vorbereitende Einstellungen vornehmen:

* <<fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>

** Lieferländer kannst du über den Assistenten *Versandeinstellungen* oder im Backend einrichten.

* <<fulfillment/versand-vorbereiten#400, Regionen erstellen>>
** Regionen kannst du über den Assistenten *Versandeinstellungen* oder im Backend erstellen.

* den <<fulfillment/versand-vorbereiten#800, Versanddienstleister>> *DHL Shipping (Versenden)* erstellen
** Versanddienstleister kannst du aktuell nur im Backend und nicht über einen Assistenten erstellen.

* <<fulfillment/versand-vorbereiten#1000, Versandprofile>> und <<fulfillment/versand-vorbereiten#1500, Portotabellen>> für *DHL Shipping (Versenden)* erstellen +
** Einige Versandeinstellungen kannst du über den Assistenten *Versandeinstellungen* einrichten. +
→ *_Wichtig:_* Es wurden noch nicht alle Funktionen und Einstellungen aus dem Versandprofil in den Assistenten *Versandeinstellungen* übernommen. Beachte dazu die Erläuterungen im Kapitel <<fulfillment/versanddienstleister-plugins/plugin-dhl-shipping-versenden#assistent-versandeinstellungen, Assistent *Versandeinstellungen* durchlaufen>>.

[#dhl-assistenten-durchlaufen]
== Assistenten durchlaufen

Sobald du das Plugin installiert und das Plugin-Set gespeichert und bereitgestellt hast, sind die Assistenten *DHL Shipping (Versenden): Grundeinstellungen* und *DHL Shipping (Versenden): Einstellungsverknüpfung* im Menü *Einrichtung » Assistenten* im Bereich *Integration* verfügbar.

Durchlaufe nun die Assistenten in der folgenden Reihenfolge:

* Versandeinstellungen
* DHL Shipping (Versenden): Grundeinstellungen
* DHL Shipping (Versenden): Einstellungsverknüpfung

[#assistent-versandeinstellungen]
=== Assistent *Versandeinstellungen* durchlaufen

In diesem Assistenten nimmst du die folgenden Einstellung vor:

* Du gibst der Versandeinstellung einen Backend-Namen und einen Frontend-Namen. Diese Namen können pro Sprache gewählt werden. +
→ Diesen Namen verknüpfst du später im Assistenten *DHL Shipping (Versenden): Einstellungsverknüpfung*.

* Du wählst das Plugin des Versanddienstleisters, für den du die Versandkosten einrichten möchtest. +
→ Das DHL Shipping (Versenden)-Plugin muss im plentyMarketplace heruntergeladen worden sein, damit es dir hier angezeigt wird.

* Du wählst eine Region, gibst die Versandkosten ein und wählst den Berechnungstypen für die gewählten Länder. Außerdem kannst du festlegen, ab welchem Warenwert keine Versandkosten berechnet werden.

[IMPORTANT]
.Weitere Einstellungen für die Versandeinstellung im Backend vornehmen
====
Wenn du den Assistenten *Versandeinstellungen* abgeschlossen hast, erscheint das Versandprofil auch im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile*. +
Die folgenden Einstellungen sind mit Abschluss des Assistenten bereits vorhanden:

* der Name des Versandprofils ist gespeichert
* der Versanddienstleister ist gespeichert
* die Option *Bei neuen Artikeln aktiveren* ist aktiviert
* alle Mandanten (Shops) sind aktiviert
* alle Auftragsherkünfte sind aktiviert
* die Versandkosten sind gespeichert
* die Region ist gespeichert

Wenn du weitere Einstellungen vornehmen möchtest wie z.B. das Sperren von Kundenklassen oder Zahlungsarten oder dem Aktivieren der Option zum Einwilligen der Datenübermittlung an Versanddienstleister, musst du diese im Versandprofil im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* vornehmen. Dieses Vorgehen ist notwendig, weil noch nicht alle Funktionen und Einstellungen aus dem Versandprofil in den Assistenten übernommen wurden. Wir ergänzen die fehlenden Einstellungen sukzessive im Assistenten.
====

Wenn du den Assistenten *Versandeinstellungen* abgeschlossen hast und diesen erneut öffnest, werden die folgenden Informationen angezeigt:

* In der Kachelansicht:

** Backend-Name
** Versanddienstleister
** Region

* In der Tabellenübersicht:

** Backend-Name
** Versanddienstleister
** Region
** Frontend-Name
** ID des Versandprofils

[#dhl-assistent-grundeinstellungen]
=== Assistent *DHL Shipping (Versenden): Grundeinstellungen* durchlaufen

[discrete]
==== Zugangsdaten

In diesem Schritt speicherst du deine Zugangsdaten zum DHL Geschäftskundenportal. Du hast die Möglichkeit, mehrere Login-Daten zu speichern, wenn du z.B. mehrere Mandanten (Shops) hast und/oder mehr als einen Vertrag mit DHL abgeschlossen hast. Im zweiten Assistenten *DHL Shipping (Versenden): Einstellungsverknüpfung* kannst du diese Daten dann verknüpfen.

Lege außerdem für jeden deiner Logins fest, ob du möchtest, dass Versandlabels immer erzeugt werden, auch wenn Sendungen mit nicht leitkodierbaren Adressen, z.B. wenn die Adressdaten unvollständig oder nicht vorhanden sind, erstellt werden. DHL führt die Korrektur der fehlerhaften Daten durch und berechnet dies. Die Sendung kann anschließend erfolgreich angemeldet werden.

Wenn die Option der Etiketterzeugung nicht aktiviert ist, werden nicht leitkodierbare Sendungen bei der Anmeldung bei DHL Versenden mit einer Fehlermeldung von DHL abgelehnt. Der Auftrag wird nicht angemeldet und in plentymarkets wird kein Versandlabel generiert.

*_Beachte:_*

* Der Login-Name darf keine Umlaute enthalten. Die Verwendung von Umlauten kann zu einer Abweisung über die Schnittstelle führen, auch wenn die Webseite den Login-Namen akzeptiert.

* Das Passwort darf maximal 20 Zeichen lang sein. Zwar ist bei DHL die Verwendung eines längeren Passworts möglich, über die plentymarkets Schnittstelle erlaubt DHL jedoch maximal 20 Zeichen. Ein Passwort mit mehr als 20 Zeichen führt zu Fehlern.

[discrete]
==== Absenderdaten

In diesem Schritt gibst du deine Absenderdaten ein. Die Daten werden als Absenderadresse auf dem Versandlabel angezeigt.

*_Hinweis:_* Die Eingabe der Kontoreferenz und der  Absenderreferenz im Bereich *Polling-Daten anzeigen* ist nur notwendig, wenn die Anmeldung der Sendungen über das _Polling-Format_ erfolgt. Die Kontoreferenz und die Absenderreferenz sind für die Übertragung über die Schnittstelle irrelevant.

[discrete]
==== Abrechnungsnummer

In diesem Schritt speicherst du deine DHL-Abrechnungsnummer gemäß deines DHL-Vertrags.

Das Verfahren - die elfte und zwöfte Ziffer der Abrechnungsnummer - legt das DHL-Produkt, das für diese Abrechnungsnummer gilt, fest. Sie stehen für folgende DHL-Produkte:

* 01 - DHL Paket +
* 53 - DHL Paket International +
* 54 - DHL Europaket +
* 55 - DHL Paket Connect +
* 86 - DHL Paket Austria +
* 87 - DHL Paket Connect (Austria) +
* 82 - DHL Paket Austria International

[discrete]
==== Produkt- und Serviceauswahl

In diesem Schritt wählst du die Produkte und Services. Du führst hier lediglich eine Vorauswahl der Produkte und Services durch. Die gewählten Produkte und Services stehen dir anschließend im Assistenten *DHL Shipping (Versenden): Einstellungsverknüpfung* zur Verfügung. Dort verknüpfst du diese mit den Zugangsdaten, der Abrechnungsnummer, der Absenderadresse und der Versandeinstellung. Beachte, dass du für die gewählten Produkte und Services bei DHL freigeschaltet sein musst.

[IMPORTANT]
.DHL Wunschpaket-Services erst nach Kauf des DHL Wunschpaket-Plugins sichtbar
====
Die DHL Wunschpaket-Services *Wunschtag*, *Wunschort* und *Wunschnachbar* stehen dir in diesem Bereich erst zur Verfügung, wenn du das DHL Wunschpaket-Plugin im link:https://marketplace.plentymarkets.com/plugins/integration/dhlwunschpaket_5435[plentyMarketplace^]{nbsp}icon:external-link[] heruntergeladen und es in einem Plugin-Set gespeichert und bereitgestellt hast. +
Auch für dieses Plugin steht dir ein Assistent im Menü *Einrichtung » Assistenten* im Bereich *Integration* zur Verfügung, damit du deine Services schnell und einfach einrichten kannst.
====

[discrete]
==== Zusammenfassung

In diesem Schritt wird eine Zusammenfassung aller getätigten Eingaben in den einzelnen Schritten aufgelistet. Du kannst deine Angaben prüfen, diese ggf. anpassen und den Assistenten danach abschließen.

[#dhl-assistent-einstellungsverknuepfung]
=== Assistent *DHL Shipping (Versenden): Einstellungsverknüpfung* durchlaufen

In diesem Assistenten verknüpfst du die vorher vorgenommenen Einstellungen. Du verknüpfst deine Zugangsdaten mit der DHL-Abrechnungsnummer, den Services, der Absenderadresse und der Versandeinstellung. Die Versandeinstellungen hast du bereits im Assistenten *Versandeinstellungen* erstellt.

[IMPORTANT]
.Standardversandart und Standardversandprofil prüfen
====
Prüfe ggf. die Einstellungen für die Optionen *Standardversandart* und *Standardversandprofil* im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *Aufträge* und passe diese ggf. an.
====

Wenn du den Assistenten *DHL Shipping (Versenden): Einstellungsverknüpfungen* abgeschlossen hast und diesen erneut öffnest, werden die folgenden Informationen angezeigt:

* In der Kachelansicht:

** Versandart
** Region
** Abrechnungsnummer


* In der Tabellenansicht:

** Versandart
** Region
** Abrechnungsnummer
** Login-Name
** Services
** Versandprofil-ID

[#datenuebermittlung]
== Informationen zur Datenübermittlung

Wenn du im DHL Shipping (Versenden)-Versandprofil im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* die Option *Einwillligung zur Datenübermittlung* aktiviert hast, wird im Ceres-Webshop im Checkout eine Checkbox angezeigt. Die Kunden können dann entscheiden, ob sie der Übertragung ihrer Daten an den Versanddienstleister zustimmen oder nicht.

* Wenn der Kunde der Übertragung der Daten zustimmt, wird die E-Mail-Adresse des Kunden an den Versanddienstleister übertragen.
* Wenn der Kunde der Übertragung der Daten _nicht_ zustimmt, wird die alternative E-Mail-Adresse, die du im Versandprofil eingegeben hast, übertragen.
* Wenn der Kunde der Übertragung der Daten _nicht_ zustimmt und du keine alternative E-Mail-Adresse im Versandprofil eingegeben hast, wird eine Fehlermeldung angezeigt und der Auftrag kann nicht bei DHL angemeldet werden. +
Daher ist es wichtig, dass du alternative Werte für die E-Mail-Adresse und die Telefonnummer im Versandprofil eingibst. Andernfalls ist es bei der Wahl bestimmter Services (z.B. Filialrouting) in den Versandeinstellungen des Plugins nicht möglich, den Auftrag erfolgreich anzumelden.

[IMPORTANT]
.Polling-Datei im Falle einer Störung bei DHL hochladen
====
Sollte es zu einer Störung der Schnittstelle seitens DHL kommen, hast du die Möglichkeit auf das Polling-Format *DHL Shipping (Versenden)* auszuweichen. Erzeuge über einen Prozess und plentyBase oder im Menü *Aufträge » Versand-Center* eine Polling-Datei, die die anzumeldenden Aufträge enthält, und lade diese Datei im DHL Geschäftskundenportal über die Vorlage *DHL-plentymarkets Importformat* hoch. +
Beachte, dass die folgenden Services _nicht_ über das Polling-Format an DHL übermittelt werden können:

* Return immediately, 2nd attempt of delivery, Verpackungsrücknahme, Unzustellbarkeitsnachricht (bei Wahl der Teilnahme DHL Paket National, Verfahren 01) +
* immediate, after deadline abandonment (bei Wahl der Teilnahme DHL Paket International, Verfahren 53) +
* DHL Wunschpaket-Services
====

[#service-filial-routing]
== Service Filial-Routing verwenden

Mit dem Service Filial-Routing erhält deine Sendung im Fall der Unzustellbarkeit (Empfänger konnte nicht ermittelt werden) eine zweite Chance, den Empfänger zu erreichen: Statt die unzustellbare Sendung direkt an dich zurückzuschicken, wird diese in der nächstgelegenen Filiale mit Paketausgabe zur Abholung durch den Empfänger hinterlegt. Der Empfänger wird per E-Mail darüber informiert. Dies spart Kosten und Aufwand auf deiner Seite, die im Falle einer Rücksendung anfallen würden.

Damit deine Kunden den Service Filial-Routing nutzen können, sind die folgenden Einstellungen wichtig:

* Aktiviere im Versandprofil im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* die Option *Einwilligung zur Datenübermittlung* und wähle eine Option für die Übertragung der Daten (E-Mail-Adresse und Telefonnummer).
* Aktiviere im Assistenten *DHL Shipping (Versenden): Grundeinstellungen* im Schritt *Produkt- und Serviceauswahl* den Service *Filial-Routing*.

[#service-ident-check]
== Service Ident-Check verwenden

Stelle sicher, dass deine Pakete nur an den Empfänger persönlich übergeben werden, nachdem der DHL-Fahrer die Identität und das Alter ausweisgestützt und dokumentiert geprüft hat.

Damit deine Kunden den Service Ident-Check (Mindestalter 16 oder 18) nutzen können, ist die folgende Einstellung wichtig:

* Aktiviere im Assistenten *DHL Shipping (Versenden): Grundeinstellungen* im Schritt *Produkt- und Serviceauswahl* den Service *Ident-Check*.

[#service-warenpost]
== Service Warenpost verwenden

Viele Artikel sind zu klein, um sie im Paket oder Päckchen zu verschicken. Wenn du viele solcher Artikel versendest, ist die Warenpost eine komfortable Lösung.

Damit du deinen Kunden den Warenpost-Service anbieten kannst, musst du die folgenden Einstellungen vornehmen:

* An den Varianten, die du mit dem Warenpost-Service versenden möchtest, müssen im Bereich *Maße* unbedingt die folgenden Daten gespeichert werden:

** Gewicht bis 1000 g
** Länge: bis 353 mm, Breite: bis 250 mm, Höhe: bis 50 mm
*** Diese Daten dürfen nicht überschritten werden.

* Wähle im Assistenten *DHL Shipping (Versenden): Grundeinstellungen* im Schritt *Abrechnungsnummer* als Produkt *62 - Warenpost*.

* Wähle im Assistenten *DHL Shipping (Versenden): Grundeinstellungen* im Schritt *Produkt- und Serviceauswahl* für das Produkt *Warenpost* die gewünschten Services.

* Wähle im Assistenten *DHL Shipping (Versenden): Einstellungsverknüpfung* die Abrechnungsnummer für Warenpost und wähle die passenden Services, die du mit dieser Versandeinstellung verknüpfen möchtest.

Die Warenpost kann nur für Sendungen innerhalb Deutschlands verwendet werden.

[#dhl-shipping-benutzerrechte]
== Benutzerrechte für Backend-Benutzer vergeben

Um das DHL Shipping-Plugin nutzen zu können, müssen für Benutzer mit dem Zugang *Backend* im Benutzerkonto bestimmte Bereiche aktiviert werden.

Beachte außerdem, dass die Funktion *Versenden* für den Benutzer im DHL-Geschäftskundenportal freigeschaltet sein muss.

[.instruction]
Benutzerrechte für Backend-Benutzer vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne den zu bearbeitenden Benutzer.
. Aktiviere im Bereich *Berechtigungen* die Berechtigungen anhand von <<#tabelle-benutzerrechte-backend-benutzer>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-benutzerrechte-backend-benutzer]]
.Benutzerrechte für Backend-Benutzer vergeben
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Aufträge > Anzeigen*
|Erlaubt dem Backend-Benutzer, die Aufträge zu sehen.

| *Aufträge > Aktualisieren*
|Erlaubt dem Backend-Benutzer, die Aufträge zu aktualisieren.

| *Aufträge > Versand > Versandpaket*
|Erlaubt dem Backend-Benutzer, die Versandpakete sowie die Artikel im Versandpaket zu sehen, zu aktualisieren, zu erstellen und zu löschen.

| *Aufträge > Versand > Pakettyp > Anzeigen*
|Erlaubt dem Backend-Benutzer, den Pakettyp zu sehen.

| *Aufträge > Auftragseigenschaften > Anzeigen*
|Erlaubt dem Backend-Benutzer, die Auftragseigenschaft zu sehen.

| *Aufträge > Dokumente > Anlegen*
|Erlaubt dem Backend-Benutzer, Dokumente wie Versandetiketten und Exportdokumente über einen Prozess und plentyBase zu erstellen.

|====

[#testmodus-aktivieren]
== Testmodus aktivieren

Standardmäßig ist der Produktivmodus im *DHL Shipping (Versenden)*-Plugin aktiviert. Du kannst den Testmodus für das Plugin aktivieren, um die Einstellungen zu prüfen.

*_Wichtig:_* Zum Testen benötigst du Zugangsdaten zu einem Test-Account (DHL Entwicklerportal).

Gehe wie im Folgenden beschrieben vor, um den Testmodus für das Plugin zu aktivieren.

[.instruction]
Testmodus aktivieren:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht*.
. Klicke in der Zeile des Plugin-Sets, in dem sich das DHL Shipping (Versenden)-Plugin befindet, auf *Plugin-Set bearbeiten* (icon:pencil[role="yellow"]).
. Klicke in der Zeile *DHL Shipping (Versenden)* auf *Einstellungen* (icon:cog[]).
. Klicke auf *Konfiguration > Allgemein*.
. Wähle die Einstellung *Test* aus der Dropdown-Liste *Modus*.
. *Speichere* (icon:save[role="green"]) die Einstellung.
