= Cross-Selling
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Artikel, Cross-Selling
:position: 40
:url: artikel/webshop/cross-selling

Beim Cross-Selling ermutigst du Kunden subtil, mehr Geld auszugeben. Dies geschieht, indem du weitere Produkte anbietest, die sich auf das gekaufte Produkt beziehen.
//Zu einem Artikel werden also weitere passende Artikel angeboten, die eine notwendige Erweiterung oder sinnvolle Ergänzung darstellen.
Hier nur einige Beispiele:

* Die Kassiererin eines Fast-Food-Restaurants fragt, ob du Pommes zu deinem Cheeseburger möchtest.
* Der Verkäufer in einem Elektronikgeschäft schlägt eine Speicherkarte vor, die mit der Digitalkamera funktionieren würde.
* Im Schuhgeschäft fragt der Verkäufer, ob du auch Schuhcreme kaufen willst, damit du deine neuen Schuhe richtig pflegst.

Im Online-Handel kannst du deine Kunden nicht direkt fragen, ob sie zusätzliche Produkte kaufen wollen.
Du kannst jedoch eine Liste mit verwandten Artikeln auf den Produktseiten deines Webshops anzeigen.

##Image##

In nur drei einfachen Schritten kannst du zusätzliche Verkäufe mittels Cross-Selling erzielen.
Stelle zunächst sicher, dass deine Artikel die <<Voraussetzungen für Cross-Selling>> erfüllen.
Erstelle danach <<Cross-Selling-Verbindungen>> in plentymarkets.
Veröffentliche schließlich die <<Liste der verwandten Artikel in deinem Webshop>>.

[TIP]
.Andere Cross-Selling-Dienstleister
====
Der externe Dienstleister <<webshop/webshop-einrichten/extras/yoochoose#, YOOCHOOSE>> ist eine Alternative zum plentymarkets Cross-Selling.
====

[#100]
== Voraussetzungen

Damit direkte Cross-Selling-Artikel im Webshop angezeigt werden können, müssen folgende Bedingungen erfüllt sein:

* <<artikel/webshop/checkliste-kategorien-anzeige#, Die Artikelkategorie des Cross-Selling-Artikels muss aktiviert sein>>.
* <<artikel/webshop/checkliste-artikel-anzeige#, Die Artikel müssen im Shop sichtbar sein>>.

[#200]
== Cross-Selling-Verbindungen

[#300]
=== Neue Verbindungen erstellen
//== Cross-Selling-Artikel hinzufügen

Welche Artikel sollen miteinander verknüpft werden?
//Welche Artikel sollen mit welchen verknüpft werden?
Du kannst einen Artikel mit beliebig vielen anderen Produkten aus deinem Sortiment verknüpfen.
//Auch Zubehörartikel oder Ersatzteile für Artikel können verknüpft werden.
Stell dir zum Beispiel vor, du möchtest eine Gitarre mit einer Packung Ersatzsaiten, einem Liederbuch und einem Gitarrengurt verknüpfen.

[.instruction]
Hauptartikel mit Zubehör verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne den Hauptartikel, z.B. die Gitarre.
. Wechsele in das Tab *Cross-Selling » Artikel hinzufügen*.
. Suche in diesem Tab erneut nach Artikeln.
. Wähle alle Zubehörteile (icon:check-square[role="blue"]), die mit dem Hauptartikel verknüpft werden sollen, z.B. wähle die Ersatzsaiten, das Liederbuch und den Gitarrengurt.
. Klicke auf die passende Beziehung (icon:cubes[role="green"]). Beachte <<tabelle-cross-selling-beziehung>>. +
→ Die Verbindungen werden erstellt und <<können jederzeit geändert werden>>.

[[tabelle-cross-selling-beziehung]]
.Cross-Selling-Beziehungen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Auswahl erweitern* (icon:check-square[role="blue"])
|Wähle diese Option, wenn du <<in die andere Richtung verknüpfen>> möchtest.

|*Ähnlich* (icon:cubes[role="green"])
|Gewählte Artikel sind dem geöffneten Artikel ähnlich.

|*Zubehör* (icon:cubes[role="green"])
|Gewählte Artikel sind Zubehör des geöffneten Artikels.

|*Ersatzteil* (icon:cubes[role="green"])
|Gewählte Artikel sind Ersatzteile des geöffneten Artikels.

|*Artikelpaket* (icon:cubes[role="green"])
|Gewählte Artikel eignen sich dazu, mit dem geöffneten Artikel zusammen als Paket gekauft zu werden.

|*Kopieren* (icon:copy[role="yellow"])
|Klicke auf diesen Button, wenn du die <<Cross-Selling-Verbindungen kopieren>> und auf andere Hauptartikel übertragen möchtest.
|====

[#400]
=== Verbindungen kopieren

<<Die Anleitung oben>> erklärte, wie man _einen Hauptartikel_ mit verschiedenen Zubehör- oder Ersatzteilen verbindet.
Zum Beispiel, wie man eine Gitarre mit einer Packung Ersatzsaiten, einem Liederbuch und einem Gitarrengurt verknüpft.

Was ist aber, wenn du 50 weitere Gitarren im Sortiment hast, die _ebenfalls_ diese Cross-Selling-Artikel haben sollen? Es wird ja ewig dauern, jeden Artikel manuell zu verlinken.

Kopiere stattdessen die fertige Cross-Selling-Verknüpfungen des ersten Hauptartikels und übertrage sie auf alle 50 weitere Hauptartikel gleichzeitig.

[.instruction]
Cross-Selling-Verknüpfungen kopieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne den bereits verknüpften Hauptartikel, z.B. die erste Gitarre.
. Wechsele in das Tab *Cross-Selling » Artikel hinzufügen*.
. Suche in diesem Tab erneut nach Artikeln.
. Wähle alle Hauptartikel (icon:check-square[role="blue"]), die ebenfalls diese Verknüpfungen haben sollen, z.B. die 50 weitere Gitarren.
. Klicke auf das Kopiersymbol (icon:copy[role="yellow"]). +
→ Die Verknüpfungen des geöffneten Artikels werden auf die gewählten Artikel übertragen.

[#500]
=== In die andere Richtung verbinden

//In der Anleitung oben wird ein Hauptartikel mit mehreren Zubehör- oder Ersatzteilen verknüpft.
<<Die Anleitung oben>> erklärte, wie man _einen Hauptartikel_ mit verschiedenen Zubehör- oder Ersatzteilen verbindet.
Zum Beispiel, wie man eine Gitarre mit einer Packung Ersatzsaiten, einem Liederbuch und einem Gitarrengurt verknüpft.

Es ist aber auch genauso möglich, _ein Ersatzteil_ mit mehreren Hauptartikeln zu verknüpfen. Zum Beispiel, eine Packung Ersatzsaiten mit verschiedenen Gitarren zu verknüpfen.
Die Vorgehensweise ist nahezu identisch mit der Anleitung oben.

Suche und öffne zuerst die Ersatzsaiten. Klicke dann auf das Tab *Cross-Selling » Artikel hinzufügen* und suche nach allen Gitarren.
Wähle schließlich die Option *Auswahl erweitern* bevor du auf die passende Beziehung klickst.

[#600]
=== Verbindungen nachträglich anpassen

Die Beziehung der verknüpften Artikel kann jederzeit geändert werden.

Im Tab **Cross-Selling-Artikel** bearbeitest du die Beziehung der verknüpften Artikel und löschst Verknüpfungen.

[#700]
== Cross-Selling-Liste im Webshop darstellen

Mit <<webshop/ceres-einrichten#110, Artikellisten>> lassen sich Artikel gruppieren und im Webshop auf der Startseite und der Einzelansicht eines Artikels hervorheben.
