= Cross-Selling
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Artikel, Cross-Selling
:position: 40
:url: artikel/webshop/cross-selling

Beim Cross-Selling ermutigst du Kunden subtil, mehr Geld auszugeben. Dies geschieht, indem du weitere Produkte anbietest, die sich auf das gekaufte Produkt beziehen.
//Zu einem Artikel werden also weitere passende Artikel angeboten, die eine notwendige Erweiterung oder sinnvolle Ergänzung darstellen.
Hier nur einige Beispiele:

* Die Kassiererin eines Fast-Food-Restaurants fragt, ob du Pommes zu deinem Cheeseburger möchtest.
* Der Verkäufer in einem Elektronikgeschäft schlägt eine Speicherkarte vor, die mit der Digitalkamera funktionieren würde.
* Im Schuhgeschäft fragt der Verkäufer, ob du eine Packung Schuhcreme zu deinen neuen Schuhen kaufen möchtest.

Im Online-Handel kannst du deine Kunden nicht direkt fragen, ob sie zusätzliche Produkte kaufen wollen.
Du kannst jedoch eine Liste mit verwandten Artikeln auf den Produktseiten deines Webshops anzeigen.

##Image##

In nur drei einfachen Schritten kannst du zusätzliche Verkäufe mittels Cross-Selling erzielen.
Stelle zunächst sicher, dass deine Artikel die <<Voraussetzungen für Cross-Selling>> erfüllen.
Erstelle danach <<Cross-Selling-Verbindungen>> in plentymarkets.
Veröffentliche schließlich die <<Liste der verwandten Artikel in deinem Webshop>>.

[TIP]
.Andere Cross-Selling-Dienstleister
====
Der externe Dienstleister <<webshop/webshop-einrichten/extras/yoochoose#, YOOCHOOSE>> ist eine Alternative zum plentymarkets Cross-Selling.
====

== Voraussetzungen

Damit direkte Cross-Selling-Artikel im Webshop angezeigt werden können, müssen folgende Bedingungen erfüllt sein:

* <<artikel/webshop/checkliste-kategorien-anzeige#, Die Artikelkategorie des Cross-Selling-Artikels muss aktiviert sein>>.
* <<artikel/webshop/checkliste-artikel-anzeige#, Die Artikel müssen im Shop sichtbar sein>>.

[#970]
== Cross-Selling-Verbindungen erstellen
//== Cross-Selling-Artikel hinzufügen

Welche Artikel sollen mit welchen anderen Artikeln verknüpft werden? Du kannst einen Artikel mit beliebig vielen anderen Artikeln aus deinem Sortiment verknüpfen.
Auch Zubehörartikel oder Ersatzteile für Artikel können verknüpft werden. Die Beziehung der verknüpften Artikel kann jederzeit geändert werden.

[.instruction]
Cross-Selling-Artikel hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche und öffne einen Artikel>>.
. Wechsele in das Tab *Cross-Selling » Artikel hinzufügen*.
. Setze Häkchen bei den Artikeln, die als Cross-Selling-Artikel hinzugefügt werden sollen.
. Klicke auf die passende *Beziehung*. Beachte dazu die Erläuterungen in <<tabelle-cross-selling-beziehung>>. +
→ Die Artikel werden hinzugefügt und im Tab *Cross-Selling-Artikel* angezeigt.

[[tabelle-cross-selling-beziehung]]
.Cross-Selling-Beziehung wählen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Auswahl erweitern**
|Geöffneten Artikel allen gewählten Artikeln als Cross-Selling-Artikel hinzufügen. Die Verknüpfung wird auch im Tab **Cross-Selling** der gewählten Artikel hinzugefügt.

|**Ähnlich**
|Gewählte Artikel sind dem geöffneten Artikel ähnlich.

|**Zubehör**
|Gewählte Artikel sind Zubehör des geöffneten Artikels.

|**Ersatzteil**
|Gewählte Artikel sind Ersatzteile des geöffneten Artikels.

|**Artikelpaket**
|Gewählte Artikel eignen sich dazu, mit dem geöffneten Artikel zusammen als Paket gekauft zu werden.
|====

Im Tab **Cross-Selling-Artikel** bearbeitest du die Beziehung der verknüpften Artikel und löschst Verknüpfungen.

[#980]
== Cross-Selling-Verknüpfungen kopieren

Kopiere die Cross-Selling-Verknüpfungen des geöffneten Artikels und übertrage die Verknüpfung auf andere Artikel.

[.instruction]
Cross-Selling-Verknüpfungen kopieren:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Wechsele in das Tab **Cross-Selling » Artikel hinzufügen**.
. Setze Häkchen bei Artikeln, auf die die Cross-Selling-Verknüpfungen übertragen werden sollen.
. Klicke auf **Cross-Selling-Einstellungen auf gewählte Artikel übertragen**. +
→ Die Verknüpfungen des geöffneten Artikels werden auf die gewählten Artikel übertragen.


== Webshop

Mit <<webshop/ceres-einrichten#110, Artikellisten>> lassen sich Artikel gruppieren und im Webshop auf der Startseite und der Einzelansicht eines Artikels hervorheben.
