= Cross-Selling
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Artikel, Cross-Selling
:position: 40
:url: artikel/webshop/cross-selling

Beim Cross-Selling wird ein Kunde ermutigt, mehr Geld auszugeben, indem er weitere Produkte angeboten bekommt, die mit dem bereits gekauften zusammenhängen.
//Zu einem Artikel werden also weitere passende Artikel angeboten, die eine notwendige Erweiterung oder sinnvolle Ergänzung darstellen.
Hier nur einige Beispiele:

* Die Kassiererin eines Fast-Food-Restaurants fragt, ob du Pommes zu deinem Cheeseburger möchtest.
* Der Verkäufer in einem Elektronikgeschäft schlägt eine Speicherkarte vor, die mit der Digitalkamera funktionieren würde.
* Im Schuhgeschäft fragt der Verkäufer, ob du eine Packung Schuhcreme zu deinen neuen Schuhen kaufen möchtest.

Auch Ersatzteile können über das Cross-Selling dargestellt werden.

Sicherlich findest du auch für deine Artikeln solche naheliegenden Verbindungen. Diese Zusammenhänge richtest du im Menü **Artikel » Artikel bearbeiten » Cross-Selling** ein und damit lukrative Zusatzverkäufe generieren.

[TIP]
.YOOCHOOSE
====
Der externe Dienstleister <<webshop/webshop-einrichten/extras/yoochoose#, YOOCHOOSE>> ist eine Alternative zum plentymarkets Cross-Selling.
====

Damit direkte Cross-Selling-Artikel im Webshop angezeigt werden können, müssen folgende Bedingungen erfüllt sein:

* Die Artikelkategorie des Cross-Selling-Artikels muss aktiviert sein.
* Die Artikel müssen im Shop sichtbar sein.

Mit <<webshop/ceres-einrichten#110, Artikellisten>> lassen sich Artikel gruppieren und im Webshop auf der Startseite und der Einzelansicht eines Artikels hervorheben.


[#970]
== Cross-Selling-Artikel hinzufügen

Im Tab *Cross-Selling* eines Artikels verknüpfst du den Artikel mit beliebig vielen, ähnlichen Artikeln aus deinem Sortiment. Auch Zubehörartikel oder Ersatzteile für Artikel können verknüpft werden. Die Beziehung der verknüpften Artikel kann jederzeit geändert werden.

[.instruction]
Cross-Selling-Artikel hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Cross-Selling » Artikel hinzufügen*.
. Setze Häkchen bei den Artikeln, die als Cross-Selling-Artikel hinzugefügt werden sollen.
. Klicke auf die passende *Beziehung*. Beachte dazu die Erläuterungen in <<tabelle-cross-selling-beziehung>>. +
→ Die Artikel werden hinzugefügt und im Tab *Cross-Selling-Artikel* angezeigt.

[[tabelle-cross-selling-beziehung]]
.Cross-Selling-Beziehung wählen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Auswahl erweitern**
|Geöffneten Artikel allen gewählten Artikeln als Cross-Selling-Artikel hinzufügen. Die Verknüpfung wird auch im Tab **Cross-Selling** der gewählten Artikel hinzugefügt.

|**Ähnlich**
|Gewählte Artikel sind dem geöffneten Artikel ähnlich.

|**Zubehör**
|Gewählte Artikel sind Zubehör des geöffneten Artikels.

|**Ersatzteil**
|Gewählte Artikel sind Ersatzteile des geöffneten Artikels.

|**Artikelpaket**
|Gewählte Artikel eignen sich dazu, mit dem geöffneten Artikel zusammen als Paket gekauft zu werden.
|====

Im Tab **Cross-Selling-Artikel** bearbeitest du die Beziehung der verknüpften Artikel und löschst Verknüpfungen.

[#980]
== Cross-Selling-Verknüpfungen kopieren

Kopiere die Cross-Selling-Verknüpfungen des geöffneten Artikels und übertrage die Verknüpfung auf andere Artikel.

[.instruction]
Cross-Selling-Verknüpfungen kopieren:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel.
. Wechsele in das Tab **Cross-Selling » Artikel hinzufügen**.
. Setze Häkchen bei Artikeln, auf die die Cross-Selling-Verknüpfungen übertragen werden sollen.
. Klicke auf **Cross-Selling-Einstellungen auf gewählte Artikel übertragen**. +
→ Die Verknüpfungen des geöffneten Artikels werden auf die gewählten Artikel übertragen.
