= Cross-Selling
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Artikel, Cross-Selling
:position: 40
:url: artikel/webshop/cross-selling

Beim Cross-Selling ermutigst du Kunden subtil, mehr Geld auszugeben. Dies geschieht, indem du weitere Produkte anbietest, die sich auf das gekaufte Produkt beziehen. Hier nur einige Beispiele:

* Die Kassiererin eines Fast-Food-Restaurants fragt, ob du Pommes zu deinem Cheeseburger möchtest.
* Der Verkäufer in einem Elektronikgeschäft schlägt eine Speicherkarte vor, die mit der Digitalkamera funktionieren würde.
* Im Schuhgeschäft fragt der Verkäufer, ob du auch eine Schuhcreme kaufen willst, um deine neuen Schuhe richtig zu pflegen.

Im Online-Handel kannst du deine Kunden nicht direkt fragen, ob sie zusätzliche Produkte kaufen wollen. Du kannst jedoch eine Liste mit verwandten Artikeln auf den Produktseiten deines Webshops anzeigen.

In nur drei einfachen Schritten kannst du zusätzliche Verkäufe mittels Cross-Selling erzielen.
Stelle zunächst sicher, dass deine Artikel die <<artikel/webshop/cross-selling#100, Voraussetzungen für Cross-Selling>> erfüllen.
Erstelle danach <<artikel/webshop/cross-selling#200, Cross-Selling-Verbindungen>> in plentymarkets.
Veröffentliche schließlich die <<artikel/webshop/cross-selling#700, Liste der verwandten Artikel in deinem Webshop>>.

[TIP]
.Andere Cross-Selling-Dienstleister
====
Der externe Dienstleister <<webshop/webshop-einrichten/extras/yoochoose#, YOOCHOOSE>> ist eine Alternative zum plentymarkets Cross-Selling.
====

[#100]
== Voraussetzungen

Damit direkte Cross-Selling-Artikel im Webshop angezeigt werden können, müssen folgende Bedingungen erfüllt sein:

* <<artikel/webshop/checkliste-kategorien-anzeige#, Die Artikelkategorie des Cross-Selling-Artikels muss aktiviert sein>>.
* <<artikel/webshop/checkliste-artikel-anzeige#, Die Artikel müssen im Shop sichtbar sein>>.

[TIP]
.Hast du einen Callisto Webshop?
====
Wenn du einen älteren Callisto Webshop verwendest, musst du auch ein paar zusätzliche Einstellungen vornehmen.
Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Webshop » Einstellungen* und lege mit der Einstellung *Cross-Selling* fest, <<webshop/webshop-einrichten/artikelsortierung#_cross_selling_template_einrichten, welche Art von Cross-Selling>> du verwenden möchtest.

Lege dann mit der Einstellung *Dynamisches Cross-Selling* fest, ob du das sogenannte <<webshop/webshop-einrichten/artikelsortierung#_dynamisches_cross_selling_einrichten, dynamische Cross-Selling>> nutzen willst. Dabei werden automatisch Verknüpfungen zwischen Artikeln angelegt, die Kunden gleichzeitig gekauft haben.
Beachte bitte, dass dynamisches Cross-Selling nur mit älteren Callisto Webshops möglich ist.
Mit neueren Ceres-Webshops ist dynamisches Cross-Selling derzeit nicht möglich.
====

[#200]
== Cross-Selling-Verbindungen

[#300]
=== Neue Verbindungen erstellen

Welche Artikel sollen miteinander verknüpft werden? Du kannst einen Artikel mit beliebig vielen anderen Produkten aus deinem Sortiment verknüpfen. Stell dir zum Beispiel vor, du möchtest eine Gitarre mit einer Packung Ersatzsaiten, einem Liederbuch und einem Gitarrengurt verknüpfen.

[.instruction]
Hauptartikel mit Zubehör verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne den Hauptartikel, z.B. die Gitarre.
. Wechsele in das Tab *Cross-Selling » Artikel hinzufügen*.
. Suche in diesem Tab erneut nach Artikeln.
. Wähle alle Zubehörteile (icon:check-square[role="blue"]), die mit dem Hauptartikel verknüpft werden sollen, z.B. wähle die Ersatzsaiten, das Liederbuch und den Gitarrengurt.
. Klicke auf die passende Beziehung (icon:cubes[role="green"]). Beachte <<tabelle-cross-selling-beziehung>>. +
→ Die Verbindungen werden erstellt und <<artikel/webshop/cross-selling#600, können jederzeit geändert werden>>.

[[tabelle-cross-selling-beziehung]]
.Cross-Selling-Beziehungen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Auswahl erweitern* (icon:check-square[role="blue"])
|Wähle diese Option, wenn du <<artikel/webshop/cross-selling#500, in die andere Richtung verknüpfen>> möchtest.

|*Ähnlich* (icon:cubes[role="green"])
|Gewählte Artikel sind dem geöffneten Artikel ähnlich.

|*Zubehör* (icon:cubes[role="green"])
|Gewählte Artikel sind Zubehör des geöffneten Artikels.

|*Ersatzteil* (icon:cubes[role="green"])
|Gewählte Artikel sind Ersatzteile des geöffneten Artikels.

|*Artikelpaket* (icon:cubes[role="green"])
|Gewählte Artikel eignen sich dazu, mit dem geöffneten Artikel zusammen als Paket gekauft zu werden.

|*Kopieren* (icon:copy[role="yellow"])
|Klicke auf diesen Button, wenn du die <<artikel/webshop/cross-selling#400, Cross-Selling-Verbindungen kopieren>> und auf andere Hauptartikel übertragen möchtest.
|====

[#400]
=== Verbindungen kopieren

<<artikel/webshop/cross-selling#300, Die Anleitung oben>> erklärte, wie man _einen Hauptartikel_ mit verschiedenen Zubehör- oder Ersatzteilen verbindet.
Zum Beispiel, wie man eine Gitarre mit einer Packung Ersatzsaiten, einem Liederbuch und einem Gitarrengurt verknüpft.

Was ist aber, wenn du 50 weitere Gitarren im Sortiment hast, die _ebenfalls_ diese Cross-Selling-Artikel haben sollen? Es wird ja ewig dauern, jeden Artikel manuell zu verlinken.

Kopiere stattdessen die fertige Cross-Selling-Verknüpfungen des ersten Hauptartikels und übertrage sie auf alle 50 weitere Hauptartikel gleichzeitig.

[.instruction]
Cross-Selling-Verknüpfungen kopieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne den bereits verknüpften Hauptartikel, z.B. die erste Gitarre.
. Wechsele in das Tab *Cross-Selling » Artikel hinzufügen*.
. Suche in diesem Tab erneut nach Artikeln.
. Wähle alle Hauptartikel (icon:check-square[role="blue"]), die ebenfalls diese Verknüpfungen haben sollen, z.B. die 50 weitere Gitarren.
. Klicke auf das Kopiersymbol (icon:copy[role="yellow"]). +
→ Die Verknüpfungen des geöffneten Artikels werden auf alle gewählten Artikel übertragen.

[#500]
=== In die andere Richtung verbinden

<<artikel/webshop/cross-selling#300, Die Anleitung oben>> erklärte, wie man _einen Hauptartikel_ mit verschiedenen Zubehör- oder Ersatzteilen verbindet.
Zum Beispiel, wie man eine Gitarre mit einer Packung Ersatzsaiten, einem Liederbuch und einem Gitarrengurt verknüpft.

Es ist aber auch genauso möglich, _ein Ersatzteil_ mit mehreren Hauptartikeln zu verknüpfen. Zum Beispiel, eine Packung Ersatzsaiten mit verschiedenen Gitarren zu verknüpfen.
Die Vorgehensweise ist nahezu identisch mit der Anleitung oben.

Suche und öffne zuerst die Ersatzsaiten. Klicke dann auf das Tab *Cross-Selling » Artikel hinzufügen* und suche nach allen Gitarren.
Wähle schließlich die Option *Auswahl erweitern* bevor du auf die passende Beziehung klickst.

[#600]
=== Verbindungen nachträglich anpassen

Sobald du eine <<artikel/webshop/cross-selling#300, Cross-Selling-Verbindung erstellt>> hast, siehst du sie in einer Übersicht innerhalb des Artikeldatensatzes.
Mit anderen Worten, siehst du, welche Zubehör- oder Ersatzteile mit dem jeweiligen Hauptartikel verknüpft wurden.
Die Verknüpfungen können jederzeit geändert oder gelöscht werden.

[.instruction]
Cross-Selling-Verknüpfungen ändern oder löschen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne den Hauptartikel.
. Wechsele in das Tab *Cross-Selling » Cross-Selling-Artikel*. +
→ Eine Liste aller Zubehör- oder Ersatzteile, die mit diesem Artikel verknüpft wurden, wird angezeigt.
. *_Ändern_*: Wähle eine andere Beziehung aus der Dropdown-Liste.
. *_Löschen_*: Wähle die zu löschenden Artikel (icon:check-square[role="blue"]) und klicke auf *Verknüpfung löschen*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#700]
== Cross-Selling-Liste im Webshop darstellen

In stationären Läden können Verkäufer direkt mit ihren Kunden reden und zusätzliche Produkte empfehlen.
Webshops hingegen müssen Zubehör und Ersatzteile anders präsentieren.

[#800]
=== Ceres Webshops

Mit Hilfe von sogenannten _Artikellisten_ kannst du Cross-Selling-Artikel in deinem Webshop darstellen.
Lese weiter und erfahre, wie du <<webshop/ceres-einrichten#110, Cross-Selling-Artikellisten in deinem Ceres-Webshop einrichtest>>.

[#900]
=== Callisto Webshops

Mit Hilfe von _Templates_ kannst du Cross-Selling-Artikel in deinem Webshop darstellen.
Die Templates findest du im Menü *CMS » Webdesign » Ordner: Layout » Ordner: ItemView*. Die folgenden Templates können für Shop-Aktionen verwendet werden:

* <<webshop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewcrosssellingitemslist, ItemViewCrossSellingItemsList>>
* <<webshop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewcrosssellingitemslist2, ItemViewCrossSellingItemsList2>>
* <<webshop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewcrosssellingitemslist3, ItemViewCrossSellingItemsList3>>

Lege die <<webshop/webshop-einrichten/artikelsortierung#, Sortierreihenfolge>> im Tab *Einstellungen* des jeweiligen Templates fest.
Lese weiter und erfahre mehr über die <<webshop/webshop-einrichten/artikelsortierung#_cross_selling_artikel_auf_der_artikelseite_anzeigen, Einrichtung von Cross-Selling-Artikel in deinem Callisto-Webshop>>.
