= Shop-Aktionen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Artikel, Sonderangeboten, Neuheiten, Top-Artikel, Shop-Aktion, Shop-Aktionen, Ceres
:position: 50
:url: artikel/webshop/shop-aktionen

Möchtest du bestimmte Artikel in deinem Webshop hervorheben? Willst du zum Beispiel neue Produkte, Sonderangebote oder meistverkaufte Artikel direkt auf der Homepage darstellen? Dann richte Shop-Aktionen in plentymarkets ein und präsentiere ausgewählte Artikel in deinem Webshop!

[TIP]
.Ceres vs. Callisto Webshop
====
Der Ablauf variiert etwas, je nachdem, ob du einen neueren Ceres-Webshop oder einen älteren Callisto-Webshop verwendest. Beide Verfahren werden auf dieser Seite beschrieben.
====

[#100]
== Shop-Aktionen im Ceres Webshop

Shop-Aktionen werden in Ceres mithilfe von _Tags_ abgebildet. Der Vorgang besteht aus nur drei Schritten:

* <<basics/arbeiten-mit-plentymarkets/tags#, Erstelle die Tags>>, die du für deine Artikel verwenden möchtest, z.B. "Bestseller".
* <<artikel/artikel-verwalten#150, Verknüpfe deine Varianten mit den Tags>>. Versehe zum Beispiel alle deine meistverkauften Artikel mit dem "Bestseller"-Tag.
* <<webshop/ceres-einrichten#110, Erstelle eine Artikelliste>>, um die getaggten Artikel in deinem Webshop anzuzeigen. Vergiss nicht die ID deines "Bestseller"-Tags anzugeben.

[#200]
== Shop-Aktionen im Callisto Webshop

Shop-Aktionen sind mit dem Callisto Webshop _weniger flexibel_ als mit Ceres.

* Mit Callisto ist es nur möglich, ganze Artikel im Webshop hervorzuheben. Mit Ceres kannst du einzelne Varianten hervorheben.
* Mit Callisto ist es nur möglich, Artikel als "Sonderangebot", "Neuheit" oder "Top-Artikel" zu bezeichnen. Mit Ceres kannst du individuelle Bezeichnungen ausdenken.

[#300]
=== Artikel zur Shop-Aktion hinzufügen

Entscheide zunächst, welche Artikel in die Shop-Aktion mit einbezogen werden sollen.

[.instruction]
Artikel zur Shop-Aktion hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne die Artikel, die in der Shop-Aktion vorkommen sollen.
. Wechsele in das Tab *Global*.
. Finde den Bereich *Webshop*. Lege mit der Dropdown-Liste *Shop-Aktion* fest, ob du den Artikel als Sonderangebot, Neuheit oder Top-Artikel kennzeichnen willst.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Andere Möglichkeiten, Artikel hinzuzufügen
====
Die obige Anleitung erklärt, wie du Artikel manuell zu einer Shop-Aktion hinzufügst. Du könntest aber auch die Gruppenfunktion verwenden, um <<artikel/artikel-verwalten#155, mehrere Artikel gleichzeitig hinzuzufügen>>. Oder du könntest den Aktionsmanager verwenden, um <<artikel/webshop/shop-aktionen#400, Artikel automatisch zur Aktion hinzuzufügen>>, z.B. wenn der Preis fällt.
====

[#400]
==== Artikel automatisch zur Shop-Aktion hinzufügen

Nutze den Aktionsmanager, um Artikel automatisch mit Shop-Aktionen zu verknüpfen.

[.instruction]
Aktionsmanager einrichten:

. Öffne das Menü *Einrichtung » Artikel » Aktionen*.
. Wechsele in das Tab *Neue Aktion*.
. Wähle die Aktion *Artikel mit Shop-Aktion verknüpfen*.
. Konfiguriere die Einstellungen für den Aktionsmanager. Beachte <<table-link-store-actions>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-link-store-actions]]
.Artikel automatisch mit dem Aktionsmanager hinzufügen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Tab: Einstellungen*

|*Name*
|Gib einen aussagekräftigen Namen ein.

|*Täglich ausführen um*
|Wähle eine Uhrzeit, zu der die Aktion täglich ausgeführt werden soll.

|*Aktiv*
|Setze ein Häkchen (icon:check-square[role="blue"]) erst, wenn die Aktion in Kraft treten soll. Lass diese Option also so lange deaktiviert, bis du die Einstellungen fertig konfiguriert hast.

2+|*Tab: Filter*

|*Preisfilter*
|Artikel werden automatisch in die Shop-Aktion aufgenommen, wenn ihre Preise den hier angegebenen Kriterien entsprechen. Beispielsweise können alle Artikel verknüpft werden, bei denen die UVP höher ist, als der Preis.

|*Webshop*
|Sollen Artikel nur dann in die Shop-Aktion aufgenommen werden, wenn sie im Webshop sichtbar sind? Verwende die Dropdown-Liste, um plentymarkets deine Wahl mitzuteilen.

|*Nur aktive Artikel*
|Wähle diese Option (icon:check-square[role="blue"]), wenn nur <<artikel/artikel-verwalten#230, aktive Artikel>> zur Shop-Aktion hinzugefügt werden sollen. Nicht aktive Artikel werden nicht verknüpft.

|*Verfügbarkeit*
|Wähle eine <<artikel/artikel-verwalten#230, Verfügbarkeitsstufe>> aus der Dropdown-Liste, wenn nur Artikel mit dieser Verfügbarkeit in die Shop-Aktion aufgenommen werden sollen.

|*Markierung 1; +
Markierung 2*
|Wähle eine oder zwei <<artikel/artikel-verwalten#810, Markierungen>>, wenn nur Artikel mit diesen Markierungen in die Shop-Aktion aufgenommen werden sollen.

2+|*Tab: Aktion*

|*Shop-Aktion*
|Sollen die Artikel als Sonderangebot, Neuheit oder Top-Artikel gekennzeichnet werden? Alle Artikel, die den Filterkriterien entsprechen, erhalten automatisch diese Bezeichnung im Tab *Global*.

|*Kategorie (Artikel)*
|Sollen die Artikel automatisch in eine bestimmte Kategorie aufgenommen werden? Falls ja, wähle diese Kategorie aus der Dropdown-Liste.

|*Kategorie (Artikel) löschen*
|Sollen die Artikel automatisch aus einer bestimmten Kategorie entfernt werden? Falls ja, wähle diese Kategorie aus der Dropdown-Liste.
|====

[#500]
=== Shop-Aktion im Webshop darstellen

Shop-Aktionen werden im Webshop mit Hilfe von Templates angezeigt. Die Templates findest du im Menü *CMS » Webdesign » Ordner: Layout » Ordner: ItemView*. Die folgenden Templates können für Shop-Aktionen verwendet werden:

* Top-Artikel: <<webshop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewtopsellerslist, ItemViewTopSellersList>>
* Sonderangebot: <<webshop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewspecialofferslist, ItemViewSpecialOffersList>>
* Neuheit: <<webshop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewlastseenlist, ItemViewLatestItemsList>>

Lege die <<webshop/webshop-einrichten/artikelsortierung#, Sortierreihenfolge>> im Tab *Einstellungen* des jeweiligen Templates fest.

[#600]
== Callisto: Artikel anhand der Positionsnummer darstellen

Mit <<artikel/webshop/shop-aktionen#, Shop-Aktionen>> kannst du bestimmte Artikel in deinem Webshop hervorheben, z.B. meistverkaufte Artikel oder Sonderangebote. Die _Positionsnummer_ ist eine weitere Möglichkeit, Artikel hervorzuheben. In diesem Fall werden die Artikel mit der höchsten Positionsnummer im Webshop dargestellt.

Du kannst entweder <<artikel/webshop/shop-aktionen#700, manuell Positionsnummern für deine Artikel eingeben>>, d.h. selbst entscheiden, welche Artikel im Webshop hervorgehoben werden sollen, unabhängig von den tatsächlichen Verkaufszahlen. Oder du kannst plentymarkets <<artikel/webshop/shop-aktionen#800, automatisch ermitteln lassen>>, welche Artikel sich am besten verkaufen. Die Darstellung hängt in dem Fall also von den tatsächlichen Verkaufszahlen ab.

[#700]
=== Positionsnummer manuell eingeben

Durch die manuelle Eingabe der Positionsnummer entscheidest du selbst, welche Artikel im Webshop angezeigt werden sollen. Dabei spielt es keine Rolle, ob sich der Artikel tatsächlich gut verkauft.

Der Ablauf erfolgt in drei Schritten. Erstens teilst du plentymarkets mit, dass du Positionsnummern manuell eingeben möchtest. Zweitens trägst du Positionsnummern in deine Artikeldatensätze ein. Drittens verwendest du eine Vorlage, um die <<artikel/webshop/shop-aktionen#900, Artikel in deinem Webshop anzuzeigen>>.

[.instruction]
plentymarkets deine Wahl mitteilen:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Artikelansichten » Einstellungen*.
. Vergewissere dich, dass die Option *Automatische Sortierung nach monatlichen Verkäufen* auf *Nein* gesetzt ist.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[.instruction]
Positionsnummern in deine Artikeldatensätze eintragen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne die Artikel, die in deinem Webshop angezeigt werden sollen.
. Wechsele in das Tab *Einstellungen* der Variante.
. Finde den Bereich *Grundeinstellungen*. Gib eine Zahl in das Feld *Position* ein. +
→ Artikel werden absteigend nach ihrer Positionsnummer angezeigt. Vergib daher die höchste Positionsnummer an die Artikel, die in deinem Webshop angezeigt werden sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#800]
=== Positionsnummer automatisch ermitteln lassen

Einmal täglich kann plentymarkets automatisch ermitteln, welche Artikelvarianten wie oft verkauft wurden. Daraus ergibt sich eine Position. Dem meistverkauften Top-Artikel wird die höchste Positionsnummer zugeordnet.

Der Ablauf erfolgt in zwei Schritten. Erstens teilst du plentymarkets mit, dass die Positionsnummern automatisch ermittelt werden sollen. Zweitens verwendest du eine Vorlage, um die <<artikel/webshop/shop-aktionen#900, Artikel in deinem Webshop anzuzeigen>>.

[.instruction]
plentymarkets deine Wahl mitteilen:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Artikelansichten » Einstellungen*.
. Vergewissere dich, dass die Option *Automatische Sortierung nach monatlichen Verkäufen* auf *Ja* gesetzt ist.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Positionsnummern werden automatisch im Tab *Einstellungen* deiner Varianten eingetragen. Manuell eingegebene Positionsnummern werden dabei überschrieben. Die automatische Vergabe erfolgt anhand der monatlichen Verkaufszahlen und spiegelt also tatsächlich deine meistverkauften Artikel wider.

[#900]
=== Artikel im Webshop darstellen

Artikel werden im Webshop mit Hilfe von einem Template angezeigt. Das Template findest du im Menü *CMS » Webdesign » Ordner: Layout » Ordner: ItemView*. Verwende das Template <<webshop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewitemsbypositionlist, ItemViewItemsByPositionList>>, um deine Artikel absteigend nach ihrer Positionsnummer darzustellen.
