= Shop-Aktionen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Ceres, Callisto, Shop, Online-Shop, Artikel, Variante, Sonderangeboten, Neuheiten, Top-Artikel, Shop-Aktion, Shop-Aktionen, Bestseller, Bestsellers, Tag, Tags
:position: 50
:url: artikel/webshop/shop-aktionen
:id: 3GZXZ0Z
:author: team-item
//ToDo: images einfügen
//ToDo: Position-Info auslagern
//ToDo: final check
//ToDo: EN Übersetzung

////
zuletzt bearbeitet 06.04.2021
////

Möchtest du bestimmte Artikel in deinem plentyShop markieren?
Willst du zum Beispiel neue Produkte, Sonderangebote oder meistverkaufte Artikel in der Kategorieansicht hervorheben?
Shop-Aktionen sind dafür perfekt geeignet.

#image#

[#300]
== Welche Artikel gehören zur Aktion?

[#350]
=== Manuelle Auswahl

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne die Artikel, die in der Shop-Aktion vorkommen sollen.
. Wechsele in das Tab *Global*.
. Finde den Bereich *Webshop*. Lege mit der Dropdown-Liste *Shop-Aktion* fest, ob du den Artikel als Sonderangebot, Neuheit oder Top-Artikel kennzeichnen willst.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Andere Möglichkeiten, Artikel auszuwählen
====
Die obige Anleitung ist nützlich, wenn du _nur wenige Artikel_ auswählen willst.
Was aber, wenn du Hunderte von Artikeln bearbeiten musst?

* <<artikel/import-export-anlage/anlage/massenbearbeitung#, Artikel-Gruppenfunktion oder Stapelverarbeitung>>:
Finde den Bereich *Multi-Channel*.
Aktiviere die Option *Webshop-Aktion* (icon:check-square[role="blue"]) und wähle die passende Shop-Aktion aus der Dropdown-Liste.
* <<daten/daten-importieren/sync-typen/elasticSync-artikel#2260, Import>>: Verwende das Zuordnungsfeld *Artikel / Shop-Aktion*.
====

[#400]
=== Automatische Auswahl

Anstatt Artikel manuell auszuwählen, kannst du sie automatisch zur Shop-Aktion hinzufügen lassen, z.B. wenn der Preis fällt.
Dies wird mit Hilfe des Aktionsmanagers gemacht.

. Öffne das Menü *Einrichtung » Artikel » Aktionen*.
. Wechsele in das Tab *Neue Aktion*.
. Wähle die Aktion *Artikel mit Shop-Aktion verknüpfen*.
. Konfiguriere die Einstellungen für den Aktionsmanager.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[discrete]
==== Einstellungen

[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Name*
|Gib einen aussagekräftigen Namen ein.
Dies ist ein interner Name. Er ist für Kunden nicht sichtbar.

| *Täglich ausführen um*
|Wähle eine Uhrzeit, zu der die Aktion täglich ausgeführt werden soll.

| *Aktiv*
|Setze ein Häkchen (icon:check-square[role="blue"]) erst, wenn die Aktion in Kraft treten soll. Lass diese Option also so lange deaktiviert, bis du die Einstellungen fertig konfiguriert hast.
|====

[discrete]
==== Filter

[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Preisfilter*
|Artikel werden automatisch in die Shop-Aktion aufgenommen, wenn ihre Preise den hier angegebenen Kriterien entsprechen. Beispielsweise können alle Artikel verknüpft werden, bei denen die UVP höher ist, als der Preis.

| *Webshop*
|Sollen Artikel nur dann in die Shop-Aktion aufgenommen werden, wenn sie im Webshop sichtbar sind? Verwende die Dropdown-Liste, um plentymarkets deine Wahl mitzuteilen.

| *Nur aktive Artikel*
|Wähle diese Option (icon:check-square[role="blue"]), wenn nur <<artikel/artikel-verwalten#200, aktive Artikel>> zur Shop-Aktion hinzugefügt werden sollen. Nicht aktive Artikel werden nicht verknüpft.

| *Verfügbarkeit*
|Wähle eine Verfügbarkeitsstufe aus der Dropdown-Liste, wenn nur <<artikel/artikel-verwalten#200, Artikel mit dieser Verfügbarkeit>> in die Shop-Aktion aufgenommen werden sollen.

| *Markierung 1; +
Markierung 2*
|Wähle eine oder zwei Markierungen, wenn nur <<artikel/einstellungen/markierungen#300, Artikel mit diesen Markierungen>> in die Shop-Aktion aufgenommen werden sollen.
|====

[discrete]
==== Aktion

[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Shop-Aktion*
|Sollen die Artikel als Sonderangebot, Neuheit oder Top-Artikel gekennzeichnet werden? Alle Artikel, die den Filterkriterien entsprechen, erhalten automatisch diese Bezeichnung im Tab *Global*.

| *Kategorie (Artikel)*
|Sollen die Artikel automatisch in eine bestimmte Kategorie aufgenommen werden? Falls ja, wähle diese Kategorie aus der Dropdown-Liste.

| *Kategorie (Artikel) löschen*
|Sollen die Artikel automatisch aus einer bestimmten Kategorie entfernt werden? Falls ja, wähle diese Kategorie aus der Dropdown-Liste.
|====

[#500]
== Darstellung im plentyShop

[#520]
=== Standard-Texte umbenennen

Du kannst die Texte an deine Bedürfnisse anpassen.
Zum Beispiel könntest du die Aktion "Top-Artikel" in "Bestseller" umbenennen.

[.instruction]
Texte umbenennen:

. Öffne das Menü *CMS » Mehrsprachigkeit*.
. Wähle eine Ausgangssprache und eine Zielsprache aus den Dropdown-Listen aus. +
*_Hinweis_*: Du kannst in beiden Listen die gleiche Sprache wählen.
. Erweitere den Bereich *Ceres » Shop Aktionen* (icon:chevron-down[role="darkGrey"]).
. Benenne den Text auf der rechten Seite wie gewünscht um. +
*_Beispiel_*: Finde das Feld *STORESPECIALTOP* und ändere den Text von "Top-Artikel" in "Bestseller".
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. <<willkommen/schnelleinstieg/schnelleinstieg-webshop#270, Stelle das Ceres-Plugin bereit>>, um die Änderungen zu übernehmen.

[#540]
=== Sonderangebot vs. % Ersparnis

Für die Shop-Aktion *Sonderangebot* gilt Folgendes:

* Hat der Artikel keinen <<artikel/einstellungen/preise#200, UVP>>, dann wird der Text angezeigt (rechts).
* Hat der Artikel einen <<artikel/einstellungen/preise#200, UVP>>, dann wird die Ersparnis in Prozent angezeigt (links).

#image#

[#570]
== Fragen und Antworten

[.collapseBox]
.*Kann ich die Texte umbenennen? Ich mag "Sonderangebot", "Neuheit" und "Top-Artikel" nicht.*
--

Ja.
Du kannst die Texte an deine Bedürfnisse anpassen.
Zum Beispiel könntest du die Aktion "Top-Artikel" in "Bestseller" umbenennen.
<<artikel/webshop/shop-aktionen#520, Weitere Informationen>>.

--

[.collapseBox]
.*Kann ich einzelne Varianten oder nur ganze Artikel hervorheben?*
--

Shop-Aktionen können nur verwendet werden, um ganze Artikel hervorzuheben.
Shop-Aktionen können _nicht_ auf einzelne Varianten angewendet werden.

*_Möglicher Workaround_*:
Wäre es möglich, stattdessen Tags zu verwenden?
Tags können auf einzelne Varianten angewendet werden.
Erfahre mehr über Tags weiter unten.

--

[.collapseBox]
.*Was sind Tags? Wie verwende ich sie? Wie unterscheiden sie sich von Shop-Aktionen?*
--

Tags sind Schlagwörter oder Phrasen mit denen du _spezifische Varianten_ hervorheben kannst.
Der Vorgang besteht aus drei Schritten:

* <<artikel/einstellungen/markierungen#500, Erstelle die Tags>>, die du für deine Varianten verwenden möchtest, z.B. "Rarität".
Wähle dabei (icon:check-square[role="blue"]) den Bereich *Variante* und den entsprechenden Mandanten.
* <<artikel/artikel-verwalten#268, Verknüpfe deine Varianten mit den Tags>>.
Versehe zum Beispiel deine seltenen Varianten mit dem "Rarität"-Tag.
* <<webshop/shop-builder#_artikelliste, Erstelle eine Artikelliste>>, um die getaggten Varianten in deinem plentyShop anzuzeigen.
Vergiss nicht die ID deines "Rarität"-Tags anzugeben.

Im Gegensatz zu Shop-Aktionen erscheinen Tags _nicht_ in der Kategorieansicht.
Stattdessen erscheinen sie in der Artikel-Detailansicht oder in einer Artikelliste.

--

////
[#600]
== Callisto: Artikel anhand der Positionsnummer darstellen

Mit Shop-Aktionen kannst du bestimmte Artikel in deinem Webshop hervorheben, z.B. meistverkaufte Artikel oder Sonderangebote. Die _Positionsnummer_ ist eine weitere Möglichkeit, Artikel hervorzuheben. In diesem Fall werden die Artikel mit der höchsten Positionsnummer im Webshop dargestellt.

Du kannst entweder <<artikel/webshop/shop-aktionen#700, manuell Positionsnummern für deine Artikel eingeben>>, d.h. selbst entscheiden, welche Artikel im Webshop hervorgehoben werden sollen, unabhängig von den tatsächlichen Verkaufszahlen. Oder du kannst plentymarkets <<artikel/webshop/shop-aktionen#800, automatisch ermitteln lassen>>, welche Artikel sich am besten verkaufen. Die Darstellung hängt in dem Fall also von den tatsächlichen Verkaufszahlen ab.

[#700]
=== Positionsnummer manuell eingeben

Durch die manuelle Eingabe der Positionsnummer entscheidest du selbst, welche Artikel im Webshop angezeigt werden sollen. Dabei spielt es keine Rolle, ob sich der Artikel tatsächlich gut verkauft.

Der Ablauf erfolgt in drei Schritten. Erstens teilst du plentymarkets mit, dass du Positionsnummern manuell eingeben möchtest. Zweitens gibst du Positionsnummern in deine Artikeldatensätze ein. Drittens verwendest du eine Vorlage, um die <<artikel/webshop/shop-aktionen#900, Artikel in deinem Webshop anzuzeigen>>.

[.instruction]
plentymarkets deine Wahl mitteilen:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Artikelansichten » Einstellungen*.
. Vergewissere dich, dass die Option *Automatische Sortierung nach monatlichen Verkäufen* auf *Nein* gesetzt ist.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[.instruction]
Positionsnummern in deine Artikeldatensätze eingeben:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#100, Suche>> und öffne die Artikel, die in deinem Webshop angezeigt werden sollen.
. Wechsele in das Tab *Einstellungen* der Variante.
. Finde den Bereich *Grundeinstellungen*. Gib eine Zahl in das Feld *Position* ein. +
→ Artikel werden absteigend nach ihrer Positionsnummer angezeigt. Vergib daher die höchste Positionsnummer an die Artikel, die in deinem Webshop angezeigt werden sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#800]
=== Positionsnummer automatisch ermitteln lassen

Einmal täglich kann plentymarkets automatisch ermitteln, welche Artikelvarianten wie oft verkauft wurden. Daraus ergibt sich eine Position. Dem meistverkauften Top-Artikel wird die höchste Positionsnummer zugeordnet.

Der Ablauf erfolgt in zwei Schritten. Erstens teilst du plentymarkets mit, dass die Positionsnummern automatisch ermittelt werden sollen. Zweitens verwendest du eine Vorlage, um die <<artikel/webshop/shop-aktionen#900, Artikel in deinem Webshop anzuzeigen>>.

[.instruction]
plentymarkets deine Wahl mitteilen:

. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Artikelansichten » Einstellungen*.
. Vergewissere dich, dass die Option *Automatische Sortierung nach monatlichen Verkäufen* auf *Ja* gesetzt ist.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Positionsnummern werden automatisch im Tab *Einstellungen* deiner Varianten eingetragen. Manuell eingegebene Positionsnummern werden dabei überschrieben. Die automatische Vergabe erfolgt anhand der monatlichen Verkaufszahlen und spiegelt also tatsächlich deine meistverkauften Artikel wider.

[#900]
=== Artikel im Webshop darstellen

Artikel werden im Webshop mit Hilfe von einem Template angezeigt. Das Template findest du im Menü *CMS » Webdesign » Ordner: Layout » Ordner: ItemView*. Verwende das Template <<webshop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewitemsbypositionlist, ItemViewItemsByPositionList>>, um deine Artikel absteigend nach ihrer Positionsnummer darzustellen.
