[#1300]
== Kategorien verknüpfen

include::_textblocks/instructions/amz-kategorien-verknuepfen.adoc[]


[#2000]
== Katalog für Export von Variantendaten erstellen (Beta)

Als neues Feature kannst du auch mit den <<daten/daten-exportieren/kataloge-verwalten, Katalogen>> deine Variantendaten an Amazon übermitteln.

[IMPORTANT]
.Die Amazon-Kataloge sind neu!
====
Kataloge für den Export von Variantendaten an Amazon befinden sich noch in der Pilotphase.
====

[#2100]
=== Allgemeine Hinweise

* Merkmale und Freitextfelder können nicht über Kataloge an Amazon übermittelt werden.
* Eigenschaften können direkt im Assistenten des Amazon-Katalogs erstellt und verknüpft werden.
* Für Amazon Business (B2B) gibt es eine eigene Flatfile. Daher muss auch ein eigener Katalog für Amazon Business erstellt werden.
*BMVD-Export-Kategorien werden in den Katalogen ignoriert.

[#2200]
=== Vorbereitungen

* Durchlaufe den Assistenten *Grundeinstellungen - Amazon*, bevor du den ersten Katalog erstellst. In dem Assistenten für Grundeinstellungen speicherst du dein Amazon-Konto und wählst die Länderplattformen, auf denen du deine Produkte anbieten möchtest.
* Bevor du deinen ersten Amazon-Katalog erstellst, mache dich damit vertraut, <<daten/daten-exportieren/kataloge-verwalten#, wie Kataloge in plentymarkets funktionieren>>.
