= Amazon-Variantenexport per Katalog einrichten (BETA)
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Amazon, Artikelexport, Amazon Katalog, Export Amazon, Amazon Export, Artikelexport, Variantenexport, Artikeldatenexport
:description: Multi-Channel in plentymarkets: Erstelle einen Katalog für den Export von Variantendaten an den Marktplatz Amazon.
:position: 12
:url: maerkte/amazon/variantendaten-exportieren
:id: EABQJ7Y
:author: team-multi-channel

Es ist so weit: Der Amazon-Katalog geht in die Testphase. Mit Amazon ziehen wir den ersten großen Marktplatz auf die Kataloge um. Bis auf weiteres kannst du aber auch weiterhin den alten Export nutzen.

[#100]
== Warum Kataloge?

* Deine Kataloge werden zur Schaltzentrale für alle Einstellungen zum Artikelexport.
* Der Katalog gibt die Datenstruktur des Flatfiles vor. Du weißt also genau, welche Variantendaten nötig sind, um deine Produkte über Amazon anzubieten.
* Du bestimmst für jede Flatfile und jede Plattform ganz individuell, welche Variantendaten übertragen werden. Gleichzeitig reduziert eine Vorschlagsfunktion deinen Aufwand: Denn sobald du ein Feld einer Datenquelle einmal zugeordnet hast, wird dir diese Zuordnung auch beim nächsten Mal vorgeschlagen.
* Daten können flexibler übertragen werden, da Datenfelder frei ausgewählt und verknüpft werden können.

[IMPORTANT]
.Amazon-Kataloge sind neu!
====
Kataloge für den Export von Variantendaten an Amazon befinden sich noch in der Pilotphase.
====

[#200]
== Hinweise zu Amazon-Katalogen

* Pro Kombination aus Amazon-Konto, Amazon-Plattform und Flatfile wird ein eigener Katalog erstellt.
* Merkmale und Freitextfelder können nicht über Kataloge an Amazon übertragen werden. Für Pflichtfelder einer Flatfile kannst du direkt im Assistenten des Amazon-Katalogs Eigenschaften erstellen. Weitere Eigenschaften kannst du später erstellen und verknüpfen.
* Für Amazon Business (B2B) gibt es eine eigene Flatfile. Daher muss auch ein eigener Katalog für Amazon Business erstellt werden.
* BMVD-Export-Kategorien werden in den Katalogen ignoriert.
* Die Pflichtfelder der Flatfile werden schon im Assistenten verknüpft. Weitere Datenfelder werden im Menü *Daten » Kataloge* verknüpft, nachdem der Katalog erstellt wurde.
* Du übermittelst schon Variantendaten an Amazon? Der alte Variantenexport für eine Kombination aus Amazon-Konto, Amazon-Plattform und Flatfile wird automatisch deaktiviert, wenn du einen Amazon-Katalog für diese Kombination aktivierst.

[#300]
== Wichtige Vorbereitungen

* Durchlaufe den Assistenten *Grundeinstellungen - Amazon*, bevor du den ersten Katalog erstellst. In dem Assistenten für Grundeinstellungen speicherst du dein Amazon-Konto und wählst die Länderplattformen, auf denen du deine Produkte anbieten möchtest.
* Bevor du deinen ersten Amazon-Katalog erstellst, mache dich damit vertraut, <<daten/daten-exportieren/kataloge-verwalten#, wie Kataloge in plentymarkets funktionieren>>.

////
[#1300]
== Kategorien verknüpfen

include::_textblocks/instructions/amz-kategorien-verknuepfen.adoc[]
////

[#400]
== Katalog für Variantenexport erstellen

Amazon-Kataloge erstellst du mit dem Assistenten *Amazon Kataloge erstellen* im Menü *Einrichtung » Assistenten » Omni-Channel*. Profis können auch direkt im Menü *Daten » Kataloge* Kataloge erstellen.

* Pro Kombination aus Amazon-Konto, Amazon-Plattform und Flatfile wird ein eigener Katalog erstellt.
* Die Pflichtfelder der Flatfile werden schon im Assistenten verknüpft.
* Optionale Felder werden im erstellten Katalog im Menü *Daten » Kataloge* verknüpft.

[IMPORTANT]
.Freitextfelder und Merkmale werden nicht unterstützt
====
Freitextfelder und Merkmale werden von Katalogen nicht unterstützt. Nur Eigenschaften können per Katalog an Amazon übertragen werden. Für die Pflichtfelder einer Flatfile kannst du direkt im Assistenten Eigenschaften erstellen.
====

[#500]
=== Katalog mit dem Assistenten erstellen

Mit dem Assistenten *Kataloge erstellen - Amazon* erstellst du auf einfache Weise einen Katalog für den Export deiner Variantendaten an Amazon. Du gibst dem Katalog einen eindeutigen Namen und entscheidest, für welche Flatfiles und Amazon-Plattformen der Katalog gelten soll. Außerdem verknüpfst du im Assistenten alle Pflichtfelder.

[TIP]
.Ein Katalog pro Konto, Plattform und Flatfile
====
Für jede Kombination aus einem Amazon-Konto, einer Amazon-Plattform und einer Flatfile benötigst du einen eigenen Katalog. Mit der Vorschlagsfunktion ist das aber kein Problem: Denn sobald du ein Feld einer Datenquelle einmal zugeordnet hast, wird dir diese Zuordnung auch beim nächsten Mal vorgeschlagen.
====

[.instruction]
Katalog mit dem Assistenten erstellen:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Kataloge erstellen - Amazon*.
. Klicke auf *Neue Konfiguration* (icon:plus[role="green"]). +
*_Tipp:_* Wenn du den ersten Katalog erstellst, wird der Schritt *Neue Konfiguration* übersprungen.
. Folge den Anweisungen auf dem Bildschirm. Wenn du zusätzliche Informationen zu einer der Optionen benötigst, klappe die Info-Box unten auf (icon:chevron-down[role="darkGrey"]).
. Überprüfe die Zusammenfassung auf mögliche Fehler und klicke auf icon:check[role="green"] *Abschließen*. +
→ Der Katalog wird erstellt.
. *_Optional:_* Verknüpfe im Menü *Daten » Kataloge* weitere <<#600, optionale Felder>>.

[.collapseBox]
.Informationen zu den Optionen des Assistenten
--
[[table-amazon-catalogue-assistant]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Schritt: Benutzerkonto

| *Benutzerkonto*
a| Amazon-Benutzerkonto aus der Dropdown-Liste wählen. Pro Kombination aus einem Amazon-Konto, einer Amazon-Plattform und einer Flatfile wird ein eigener Katalog erstellt. Du kannst nur Benutzerkonten auswählen, die bereits in deinem plentymarkets System gespeichert sind. Wenn das Benutzerkonto, für das du einen Katalog erstellen möchtest, nicht aufgeführt ist, wechsele in das Menü *Einrichtung » Märkte » Amazon » Einstellungen* und erstelle ein <<maerkte/amazon/amazon-einrichten#300, neues Konto>> oder durchlaufe den Assistenten *Grundeinstellungen - Amazon*.

*_Hinweis_*: <<crm/kontakte-verwalten#15, Erstelle die nötigen Kundenklassen>> im Voraus, falls sie nicht bereits in deinem plentymarkets System vorhanden sind.

2+|Schritt: Name, Flatfile und Plattform

| *Name*
| Name für den Katalog eingeben. Wenn kein Name angegeben wurde, wird automatisch ein Name für den Katalog generiert.

| *Artikelexport aktivieren*
| Aktiviert den Export. Der Export ist standardmäßig deaktiviert. +
*_Hinweis:_* Den Export erst aktivieren, nachdem alle Verknüpfungen vorgenommen und geprüft wurden. Der Katalog kann auch später im Menü *Daten » Kataloge* aktiviert werden.

| *Fulfillment-Methode*
| Wählen, ob nur MFN-Varianten, nur FBA-Varianten oder beide zusammen in diesem Katalog übertragen werden sollen. +
*MFN- und FBA-Varianten übertragen* (Standardeinstellung) = MFN-Varianten und FBA-Varianten werden übertragen (empfohlen). +
*Nur MFN-Varianten übertragen* = Nur Varianten mit eigenem Versand werden übertragen. Für FBA-Varianten muss also ein zusätzlicher Katalog erstellt werden. +
*Nur FBA-Varianten übertragen* = Nur Varianten werden übertragen, die Amazon versendet. Für Varianten mit eigenem Versand muss also ein zusätzlicher Katalog erstellt werden. +
*_Tipp:_* Wir empfehlen, beide Fulfillment-Methoden in nur einem Katalog zu pflegen.

| *Amazon-Flatfile*
| Wählen, welche Flatfile für den Katalog verwendet werden soll. +
Eine Flatfile ist eine Dateivorlage von Amazon für eine bestimmte Produktkategorie. Diese Dateivorlage gibt vor, welche Variantendaten und Lagerbestände an Amazon übertragen werden müssen. +
*_Hinweis_*: Nur Flatfiles für die Plattformen werden angezeigt, die für das Amazon-Benutzerkonto aktiviert sind, das du in Schritt 1 gewählt hast. Aktiviere bei Bedarf <<maerkte/amazon/amazon-einrichten#300, weitere Plattformen für das Amazon-Benutzerkonto>>.

| *Amazon-Plattform* +
(wird nach Wählen einer Flatfile eingeblendet)
| Amazon-Plattform aus der Dropdown-Liste wählen. +
*_Hinweis_*: Nur Amazon-Plattformen werden angezeigt, die für das Amazon-Benutzerkonto aktiviert sind, das du in Schritt 1 gewählt hast. Aktiviere bei Bedarf <<maerkte/amazon/amazon-einrichten#300, weitere Plattformen für das Amazon-Benutzerkonto>>.

| *Flatfile-Version*
| Zeigt an, welche Version der Flatfile genutzt wird.

2+|Schritt: Katalog einrichten

| *Katalog einrichten*
a| plentymarkets Datenfelder mit den Datenfeldern der gewählten Amazon-Flatfile verknüpfen. Alle Datenfelder in diesem Schritt sind Pflichtfelder und müssen verknüpft werden. Im Menü *Daten » Kataloge* können weitere Felder verknüpft werden, nachdem der Assistent abgeschlossen wurde.

* *Eigenschaft anlegen* = Erstellt eine neue Eigenschaft und verknüpft diese Eigenschaft mit dem Datenfeld. Die automatisch erstellten Eigenschaften werden im Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen* in der Gruppe *Amazon Catalog* zusammengefasst dargestellt. +
* *Datenquelle wählen* = Ein Datenfeld in plentymarkets wird an Amazon übertragen. Das Datenfeld aus der Dropdown-Liste *Quelle wählen* wählen. +
*_Hinweis:_* Felder mit der Option *Datenquelle manuell verknüpfen* können nicht automatisch im Assistenten verknüpft werden. Diese Felder müssen also manuell im Katalog verknüpfen werden, nachdem der Katalog erstellt wurde.
* *Datenquelle manuell verknüpfen* = Diese Felder werden nicht automatisch im Assistenten verknüpft und müssen manuell im Katalog verknüpfen musst, nachdem der Katalog angelegt wurde.

*_Tipp:_* Wenn du schon einmal einen Katalog erstellt hast, werden beim nächsten Katalog Vorschläge eingeblendet. Für jedes Feld wird die Quelle vorgeschlagen, die du am häufigsten mit dem Feld verknüpft hast.

2+|Schritt: Zusammenfassung

| Zusammenfassung
| Zeigt eine Zusammenfassung der Katalog-Einstellungen. Einstellungen ausklappen (icon:chevron-down[role="darkGrey"]) und prüfen.
|====
--

[#600]
=== Optionale Datenfelder verknüpfen (nicht im Assistenten)

Mit dem Assistenten verknüpfst du alle Pflichtfelder für die gewählte Flatfile. Du kannst aber auch zusätzliche Felder verknüpfen, um noch mehr Informationen zu deinen Produkten an Amazon zu übermitteln.

[.instruction]
Optionale Datenfelder verknüpfen:

. Öffne das Menü *Daten » Kataloge*. +
→ Eine Liste der Kataloge wird angezeigt.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet. +
*_Hinweis:_* Der Katalog wird zunächst leer angezeigt. Einige Flatfiles enthalten sehr viele Daten. Daher kann es mehrere Minuten dauern, bis die Datenfelder einer Flatfile geladen und im Katalog angezeigt werden.
. Verknüpfe weitere Felder mit Quellen.
. *Speichere* (icon:save[set=plenty]) den Katalog.

[#700]
== Im Assistenten angelegte Eigenschaften mit Varianten verknüpfen

Wie du Eigenschaften mit Varianten verknüpfst, erfährst du auf der Handbuchseite <<artikel/artikel-verwalten#4900, Artikel verwalten>>.

[TIP]
.Eigenschaftengruppe nutzen
====
Eigenschaften, die du im Assistenten anlegst, werden automatisch im Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen* zu der Gruppe *Amazon Catalog* hinzugefügt. Anhand dieser Gruppe kannst du sehen, welche neuen Eigenschaften du mit deinen Varianten verknüpfen musst.
====

[#800]
== Variantenexport aktivieren

Du hast alle Verknüpfungen geprüft und möchtest nun den Export deiner Variantendaten an Amazon starten?

* <<#900, Katalog für vorhandenen Export aktivieren>>
* <<#1000, Katalog für neuen Export aktivieren>>

[#900]
=== Katalog für vorhandenen Export aktivieren

Wenn du einen Katalog für eine Kombination aus einem Amazon-Benutzerkonto, einer Flatfile und einer Amazon-Plattform erstellt hast, die du bereits produktiv im Einsatz hast, wird der Export automatisch auf den Katalog umgestellt, sobald du den Katalog aktivierst.

[.instruction]
Katalog für vorhandenen Export aktivieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Eine Liste der Kataloge wird angezeigt.
. Schiebe in der Zeile des Katalogs in der Spalte *Aktiv/Inaktiv* den Toggle-Button (icon:fa-toggle-on[]) nach rechts. +
→ Der Katalog wird aktiviert. +
→ Die Daten werden einmal täglich nachts an Amazon übertragen. +
*_Tipp:_* Wenn beim automatischen Export falsche Daten an Amazon übertragen wurden, kannst du die Verknüpfung im Katalog korrigieren, eine <<#2800, CSV-Datei des Katalogs exportieren>> und manuell bei Amazon hochladen.

[#1000]
=== Katalog für neuen Export aktivieren

Wenn du einen Katalog für eine Kombination aus einem Amazon-Benutzerkonto, einer Flatfile und einer Amazon-Plattform erstellt hast, die du aktuell noch nicht produktiv im Einsatz hast, sind einige weitere Einstellungen nötig.

[.instruction]
Katalog für neuen Export aktivieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Eine Liste der Kataloge wird angezeigt.
. Schiebe in der Zeile des Katalogs in der Spalte *Aktiv/Inaktiv* den Toggle-Button (icon:fa-toggle-on[]) nach rechts. +
→ Der Katalog wird aktiviert. +
*_Tipp:_* Wenn beim automatischen Export falsche Daten an Amazon übertragen wurden, kannst du die Verknüpfung im Katalog korrigieren, eine <<#1100, CSV-Datei des Katalogs exportieren>> und manuell bei Amazon hochladen.
. Prüfe außerdem die unten aufgeführten Einstellungen:

[.tabs]
====
Im Assistenten *Amazon Grundeinstellungen*::
+
--
Damit deine Varianten an verschiedene Amazon-Plattformen übertragen werden können, müssen die Plattformen aktiviert sein. Diese Einstellung nimmst du im Schritt Grundeinstellungen im Assistenten *Amazon Grundeinstellungen* im Menü *Einrichtung » Assistenten » Omni-Channel* vor.

Der Variantenexport für Amazon muss aktiviert sein.
Diese Einstellung nimmst du im Schritt *Automatische Datenübertragung* unter *An welche Amazon-Plattformen möchtest du deine Artikeldaten übertragen?* vor. +
*_Hinweis:_* Dieser Schritt des Assistenten ist nur sichtbar, wenn du im Schritt *Marktplatz einrichten* die Einstellung *Erweiterte Einstellungen anzeigen* aktiviert hast.

Damit der Katalog zu Amazon exportiert wird, muss das Amazon-Benutzerkonto aktiv sein, für das der Katalog erstellt wurde.
Diese Einstellung nimmst du im Assistenten *Amazon Grundeinstellungen* im Schritt *Amazon-Benutzerkonto aktivieren* im Menü *Einrichtung » Assistenten » Omni-Channel* vor.

--

Im Menü *Einrichtung » Märkte » Amazon*::
+
--
Damit der Katalog zu Amazon exportiert wird, muss das Amazon-Benutzerkonto aktiv sein, für das der Katalog erstellt wurde.

[.instruction]
Amazon-Benutzerkonto aktivieren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen »* _Amazon-Konto wählen_.
. Wechsle in das Tab *Einstellungen*.
. Setze im Bereich *Zugangsdaten* ein Häkchen bei der Option *Aktiv*.
. *Speichere* die Einstellungen.

Aktiviere den Variantenexport für Amazon.

[.instruction]
Variantenexport aktivieren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen »* _Amazon-Konto wählen_.
. Wechsle in das Tab *Artikeleinstellungen*.
. Wähle aus der Dropdown-Liste für den Artikelexport die Einstellung *Täglich*.
. *Speichere* die Einstellungen.

Aktiviere den Export der Flatfile.

[.instruction]
Export-Kategorien aktivieren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen »* _Amazon-Konto wählen_.
. Wechsle in das Tab *Artikeleinstellungen*.
. Navigiere zum Bereich *Exportfilter*.
. Aktiviere unter *Export-Kategorien* und *BMVD-Export-Kategorien* die Flatfiles, für die du Kataloge erstellt hast.
. *Speichere* die Einstellungen.
--
====

[#1100]
== Amazon-Katalog als CSV-Datei exportieren

Lade den Katalog herunter, um zum Beispiel die Verknüpfungen zu prüfen, bevor du sie an Amazon überträgst. Du kannst bis zu 30.000 Varianten exportieren. Falls du mehr Varianten hast, kannst du die Anzahl der Varianten über Artikel-IDs, Tag-IDs und/oder Hersteller filtern.

[.instruction]
Amazon-Katalog als CSV-Datei exportieren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Datenaustausch » Datenexport*.
. Wähle im Bereich *Katalog exportieren* den Katalog aus der Dropdown-Liste.
. *_Optional:_* Gib Artikel-IDs und/oder Tag-IDs kommagetrennt ein, um die exportieren Daten zu filtern.
. *_Optional:_* Wähle einen Hersteller aus der Dropdown-Liste, um die exportieren Daten zu filtern.
. Klicke auf *Exportieren* (icon:box_plus[set=plenty]). +
→ Der Export wird gestartet. +
*_Hinweis:_* Das Browser-Fenster muss geöffnet bleiben, während die Exportdatei generiert wird. Einige Flatfiles enthalten sehr viele Daten. Deshalb kann der Export mehrere Minuten dauern.
. Scrolle zum Bereich *CSV des Katalog-Exports herunterladen*.
. Klicke in der Spalte rechts des Exports auf *Herunterladen*.
. Speichere die Datei auf deinem Rechner. +
*_Hinweis:_* Die CSV-Datei kann nicht in plentymarkets importiert werden. Nimm Änderungen an den Verknüpfungen also direkt im Katalog vor.

[#1200]
== Troubleshooting

[qanda]
Ich habe Felder falsch verknüpft und deshalb falsche Daten an Amazon übertragen. Was kann ich tun?::
  Korrigiere als erstes die falschen Verknüpfungen im Katalog. Die Daten werden einmal täglich nachts an Amazon übertragen. Wenn die Änderung dringend ist und vor diesem automatischen Export Änderungen bei Amazon vornehmen musst, kannst du den korrigierten Katalog in eine <<#1100, CSV-Datei exportieren>> und diese CSV-Datei manuell im Amazon Seller Central hochladen.

[qanda]
Ich habe meinen alten, zuverlässigen Export auf Kataloge umgestellt und jetzt kommt es zu Fehlern. Was kann ich tun?::
  Keine Panik. Stelle den Katalog im Menü *Daten » Kataloge* auf inaktiv. Deine Variantendaten werden dann automatisch wieder über den alten Export an Amazon übertragen und du kannst ganz in Ruhe deine Einstellungen prüfen und korrigieren. Unser Support-Team hilft dir bei Fragen oder Problemen gern weiter.
