= Export von Variantendaten einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Amazon, Artikelexport, Amazon Katalog, Export Amazon, Amazon Export, Artikelexport, Variantenexport, Artikeldatenexport
:description: Multi-Channel in plentymarkets: Erstelle einen Katalog für den Export von Artikeldaten an den Marktplatz Amazon.
:position: 12
:url: maerkte/amazon/variantendaten-exportieren
:id: EABQJ7Y
:author: team-multi-channel

// für beide

dsaf

[#1300]
== Kategorien verknüpfen

include::_textblocks/instructions/amz-kategorien-verknuepfen.adoc[]



[#2000]
== Katalog für Export von Variantendaten erstellen (Beta)

Als neues Feature kannst du auch mit den <<daten/daten-exportieren/kataloge-verwalten, Katalogen>> deine Variantendaten an Amazon übermitteln.

[IMPORTANT]
.Die Amazon-Kataloge sind neu!
====
Kataloge für den Export von Variantendaten an Amazon befinden sich noch in der Pilotphase.
====

[#2100]
=== Allgemeine Hinweise

* Merkmale und Freitextfelder können nicht über Kataloge an Amazon übermittelt werden.
* Eigenschaften können direkt im Assistenten des Amazon-Katalogs erstellt und verknüpft werden.
* Für Amazon Business (B2B) gibt es eine eigene Flatfile. Daher muss auch ein eigener Katalog für Amazon Business erstellt werden.
*BMVD-Export-Kategorien werden in den Katalogen ignoriert.

[#2200]
=== Vorbereitungen

* Durchlaufe den Assistenten *Grundeinstellungen - Amazon*, bevor du den ersten Katalog erstellst. In diesem Assistenten speicherst du dein Amazon-Konto und wählst die Länderplattformen, auf denen du deine Produkte anbieten möchtest.
* Bevor du deinen ersten Amazon-Katalog erstellst, mache dich damit vertraut, <<daten/daten-exportieren/kataloge-verwalten#, wie Kataloge in plentymarkets funktionieren>>.

[#2300]
=== Vorhandene Variantenexporte an Amazon auf Kataloge umstellen

Im plentymarkets Forum findest du eine Anleitung, wie du vorgehst, wenn du bereits Artikel zu Amazon exportierst und diese Exporte auf Kataloge umstellen möchtest.

[#2400]
=== Amazon-Katalog mit dem Assistenten erstellen

Mit dem Assistenten *Kataloge erstellen - Amazon* kannst du auf einfache Weise einen Katalog für den Export deiner Artikeldaten an Amazon erstellen. Während des Prozesses gibst du dem Katalog einen eindeutigen Namen und entscheidest, für welche Flatfiles und Amazon-Plattformen der Katalog gelten soll. Außerdem verknüpfst du im Assistenten alle Pflichtfelder. Danach verknüpfst du optional weitere Felder im Katalog.

[TIP]
.Ein Katalog pro Konto, Plattform und Flatfile
====
Für jede Kombination aus einem Amazon-Konto, einer Amazon-Plattform und einer Flatfile benötigst du einen eigenen Katalog. Mit der Vorschlagsfunktion ist das aber kein Problem: Denn sobald du eine Datenquelle einmal einem Feld zugeordnet hast, wird dir diese Zuordnung auch beim nächsten Mal vorgeschlagen.
====

[.instruction]
Amazon-Katalog mit dem Assistenten erstellen:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Kataloge erstellen - Amazon*.
. Klicke auf *Neue Konfiguration* (icon:plus[role="green"]). +
*_Tipp:_* Wenn du den ersten Katalog erstellst, wird der Schritt *Neue Konfiguration* übersprungen.
. Folge den Anweisungen auf dem Bildschirm. Wenn du zusätzliche Informationen zu einer der Optionen benötigst, klappe die Info-Box unten auf (icon:chevron-down[role="darkGrey"]).
. Überprüfe die Zusammenfassung auf mögliche Fehler und klicke auf icon:check[role="green"] *Abschließen*. +
→ Der Katalog wird erstellt.
. *_Optional:_* Öffne das Menü *Daten » Kataloge*. +
→ Eine Liste der Kataloge wird angezeigt.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet. +
*_Hinweis:_* Der Katalog wird zunächst leer angezeigt. Einige Flatfiles enthalten sehr viele Daten. Daher kann es mehrere Minuten dauern, bis die Datenfelder einer Flatfile geladen und im Katalog angezeigt werden.
. Verknüpfe weitere Felder mit Quellen.
. *Speichere* (icon:save[set=plenty]) den Katalog.


Mit dem Assistenten verknüpfst du die Pflichtfelder einer Flatfile. Weitere Felder verknüpfst du in einem späteren Schritt direkt im Katalog.

Hinweis: Bei einigen Feldern wird als Option Datenquelle manuell verknüpfen angezeigt. Beachte, dass du diese Felder noch manuell im Katalog verknüpfen musst, nachdem der Katalog angelegt wurde, da sie nicht automatisch im Assistenten verknüpft werden.

Alle Datenfelder in diesem Schritt sind Pflichtfelder und müssen verknüpft werden. Verknüpfe nach Abschluss des Assistenten im Menü *Daten » Kataloge* weitere optionale Datenfelder, um deine Artikel detaillierter zu beschreiben.

[.collapseBox]
.Weitere Informationen über die einzelnen Optionen
--

[[table-amazon-catalogue-assistant]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Schritt: Benutzerkonto

| *Benutzerkonto*
a| Amazon-Benutzerkonto aus der Dropdown-Liste wählen. Beachte, dass du pro Kombination aus einer Flatfile und einer Amazon-Plattform einen eigenen Katalog erstellen musst. Du kannst nur Benutzerkonten auswählen, die bereits in deinem plentymarkets System gespeichert sind. Wenn das Benutzerkonto, für das du einen Katalog erstellen möchtest, nicht aufgeführt ist, wechsele in das Menü *Einrichtung » Märkte » Amazon » Einstellungen* und erstelle ein <<maerkte/amazon/amazon-einrichten#300, neues Konto>> oder durchlaufe den Assistenten *Grundeinstellungen - Amazon*.

*_Hinweis_*: <<crm/kontakte-verwalten#15, Erstelle die nötigen Kundenklassen>> im Voraus, falls sie nicht bereits in deinem plentymarkets System vorhanden sind.

2+|Schritt: Name, Flatfile und Plattform

| *Name*
| Name für den Katalog eingeben. Wenn kein Name angegeben wurde, wird automatisch ein Name für den Katalog generiert.

| *Artikelexport aktivieren*
| Aktiviert den Export der in diesem Katalog definierten Artikeldaten an Amazon. Der Export ist standardmäßig deaktiviert. +
*_Hinweis:_* Der Export sollte erst aktiviert werden, nachdem alle Verknüpfungen vorgenommen und geprüft wurden. Der Katalog kann auch im Menü <<#2600, Daten » Kataloge>> aktiviert werden.

| *Fulfillment-Methode*
| Wählen, ob nur MFN-Varianten, nur FBA-Varianten oder beide zusammen in diesem Katalog übertragen werden sollen. +
*MFN- und FBA-Varianten übertragen* (Standardeinstellung) = MFN-Varianten und FBA-Varianten werden übertragen (empfohlen). +
*Nur MFN-Varianten übertragen* = Nur Varianten mit eigenem Versand werden übertragen. Für FBA-Varianten muss also ein zusätzlicher Katalog erstellt werden. +
*Nur FBA-Varianten übertragen* = Nur Varianten werden übertragen, die Amazon versendet. Für Varianten mit eigenem Versand muss also ein zusätzlicher Katalog erstellt werden. +
*_Tipp:_* Wir empfehlen, beide Fulfillment-Methoden in nur einem Katalog zu pflegen.

| *Amazon-Flatfile*
| Wählen, welche Flatfile für den Katalog verwendet werden soll. +
Eine Flatfile ist eine Dateivorlage von Amazon für eine bestimmte Produktkategorie. Diese Dateivorlage gibt vor, welche Artikeldaten und Lagerbestände an Amazon übertragen werden müssen. +
*_Hinweis_*: Nur Flatfiles für die Plattformen werden angezeigt, die für das Amazon-Benutzerkonto aktiviert sind, das du in Schritt 1 gewählt hast. Aktiviere bei Bedarf <<maerkte/amazon/amazon-einrichten#300, weitere Plattformen für das Amazon-Benutzerkonto>>.

| *Amazon-Plattform* +
(wird nach Wählen einer Flatfile eingeblendet)
| Amazon-Plattform aus der Dropdown-Liste wählen. +
*_Hinweis_*: Nur Amazon-Plattformen werden angezeigt, die für das Amazon-Benutzerkonto aktiviert sind, das du in Schritt 1 gewählt hast. Aktiviere bei Bedarf <<maerkte/amazon/amazon-einrichten#300, weitere Plattformen für das Amazon-Benutzerkonto>>.

| *Flatfile-Version*
| Zeigt an, welche Version der Flatfile genutzt wird.

2+|Schritt: Katalog einrichten

| *Katalog einrichten*
a| plentymarkets Datenfelder mit den Datenfeldern der gewählten Amazon-Flatfile verknüpfen. Alle Datenfelder in diesem Schritt sind Pflichtfelder und müssen verknüpft werden. Im Menü *Daten » Kataloge* können weitere verknüpft werden.

* *Eigenschaft anlegen* = Erstellt eine neue Eigenschaft und verknüpft diese Eigenschaft mit dem Datenfeld. +
*_Hinweis:_* Für Preise und Barcodes wird keine neue Eigenschaft erstellt, sondern ein neuer Verkaufspreis bzw. ein neuer Barcode. +
* *Datenquelle wählen* = Ein Datenfeld in plentymarkets wird an Amazon übertragen. Das Datenfeld aus der Dropdown-Liste *Quelle wählen* wählen. +
*_Hinweis:_* Merkmale und Freitextfelder können nicht verknüpft werden. +
*_Hinweis:_* Felder mit der Option *Datenquelle manuell verknüpfen* müssen noch manuell im Katalog verknüpfen werden, nachdem der Katalog erstellt wurde, da sie nicht automatisch im Assistenten verknüpft werden.

*_Tipp:_* Wenn du schon einmal einen Katalog erstellt hast, werden beim nächsten Katalog Vorschläge eingeblendet. Für jedes Feld wird die Quelle vorgeschlagen, die du am häufigsten mit einem Feld verknüpft hast.

2+|Schritt: Zusammenfassung

|
| Zeigt eine Zusammenfassung der Katalog-Einstellungen. Einstellungen ausklappen (icon:chevron-down[role="darkGrey"]) und prüfen.

|====

--

[#2500]
=== Optionale Datenfelder verknüpfen (nicht im Assistenten enthalten)

Mit dem <<#100, Assistenten>> verknüpfst du alle Pflichtfelder für die gewählte Flatfile. Du kannst jedoch auch noch weitere Felder verknüpfen.

[.instruction]
Optionale Datenfelder verknüpfen:

. Öffne das Menü *Daten » Kataloge*. +
→ Eine Liste der Kataloge wird angezeigt.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet. +
*_Hinweis:_* Der Katalog wird zunächst leer angezeigt. Einige Flatfiles enthalten sehr viele Daten. Daher kann es mehrere Minuten dauern, bis die Datenfelder einer Flatfile geladen und im Katalog angezeigt werden.
. Verknüpfe weitere Felder mit Quellen.
. *Speichere* (icon:save[set=plenty]) den Katalog.

[#2600]
=== Export von Artikeldaten an Amazon aktivieren

[.instruction]
Export von Artikeldaten an Amazon aktivieren:

. Öffne das Menü *Daten » Kataloge*. +
→ Eine Liste der Kataloge wird angezeigt.
. Schiebe in der Zeile des Katalogs in der Spalte *Aktiv/Inaktiv* den Toggle-Button (icon:fa-toggle-on[]) nach rechts. +
→ Der Katalog wird aktiviert. +
→ Die Daten werden einmal täglich nachts an Amazon übertragen. +
*_Tipp:_* Wenn beim automatischen Export falsche Daten an Amazon übermittelt wurden, kannst du die Verknüpfung im Katalog korrigieren, eine <<#2800, CSV-Datei des Katalogs exportieren>> und manuell bei Amazon hochladen.

[#2700]
=== Amazon-Katalog bearbeiten

Amazon-Kataloge kannst du auf zwei Arten bearbeiten:

* Über den <<#100, Assistenten>> im Menü *Einrichtung » Assistenten » Omni-Channel*
* Im Menü <<daten/daten-exportieren/kataloge-verwalten#40, Daten » Kataloge>>

[#2800]
=== Amazon-Katalog als CSV-Datei exportieren

Lade den Katalog herunter, um zum Beispiel die Verknüpfungen zu prüfen, bevor du sie an Amazon überträgst. Du kannst bis zu 30.000 Varianten exportieren. Falls du mehr Varianten hast, kannst du die Anzahl der Varianten über Artikel-IDs, Tag-IDs und/oder Hersteller filtern.

[.instruction]
Amazon-Katalog als CSV-Datei exportieren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Datenaustausch » Datenexport*.
. Wähle im Bereich *Katalog exportieren* den Katalog aus der Dropdown-Liste.
. *_Optional:_* Gib Artikel-IDs und/oder Tag-IDs kommagetrennt ein, um die exportieren Daten zu filtern.
. *_Optional:_* Wähle einen Hersteller aus der Dropdown-Liste, um die exportieren Daten zu filtern.
. Klicke auf *Exportieren* (icon:box_plus[set=plenty]). +
→ Der Export wird gestartet. +
*_Hinweis:_* Einige Flatfiles enthalten sehr viele Daten. Deshalb kann der Export mehrere Minuten dauern. Schließe das Browser-Fenster nicht, während die Exportdatei generiert wird.
. Klicke im Bereich *CSV des Katalog-Exports herunterladen* in der Spalte rechts auf *Herunterladen*.
. Speichere die Datei auf deinem Rechner. +
*_Hinweis:_* Die CSV-Datei kann nicht in plentymarkets importiert werden. Nimm Änderungen an den Verknüpfungen also direkt im Katalog vor.

[#2900]
=== Eigenschaften im Assistenten erstellen






== Eigenschaften mit Varianten verknüpfen



* verknüpfen
* bei artikeln aktivieren


[#3000]
=== FAQs: Export von Daten per Katalog

[qanda]
Ich habe Felder falsch verknüpft und deshalb falsche Daten an Amazon übermittelt. Was kann ich tun?::
  Korrigiere die Verknüpfung im Katalog. Die Daten werden einmal täglich nachts an Amazon übermittelt. Um vor diesem automatischen Export Änderungen bei Amazon vorzunehmen, kannst du den korrigierten Katalog in eine <<#2800, CSV-Datei exportieren>> und diese CSV-Datei manuell bei Amazon hochladen.
