= Amazon einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Amazon, FBA, MFN, Prime, NextDay, SecondDay, Marktplatz, SKU, Multi-Channel, Amazon Business
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Amazon in deinem plentymarkets System ein.
:position: 10
:url: maerkte/amazon/amazon-einrichten

link:https://www.amazon.de/[Amazon^] hat sich vom größten Online-Buchhändler zum führenden Universalkaufhaus entwickelt. Unzählige Kunden schätzen die große Auswahl, vertrauen auf eine hohe Warenqualität und erwarten besten Service vom Marktführer wie z.B. eine sehr zeitnahe Warenlieferung. plentymarkets ermöglicht dir die komplette und integrierte Anbindung an Amazon. Erfahre, wie du Artikel verfügbar machst, den Datenaustausch über die Schnittstelle aktivierst, den FBA-Service von Amazon nutzt und vieles mehr. FBA ist das Kürzel für Fulfillment by Amazon, einem Service von Amazon, bei dem Amazon die Lagerhaltung sowie die gesamte Logistik übernimmt.

[#100]
==  Bei Amazon registrieren

Bevor du Einstellungen in plentymarkets vornimmst, registriere dich bei Amazon als Verkäufer. Die zentrale Anlaufstelle für Verkäufer bei Amazon ist die Amazon Seller Central. Händler, die mehr als 40 Artikel im Monat verkaufen, werden bei Amazon als sogenannte Power-Anbieter geführt und haben auch erst ab dieser Stufe die Möglichkeit zum Upload von Artikellisten. Wähle als plentymarkets Nutzer die Option Power-Anbieter, da nur mit diesem Konto Lagerbestand und Angebote durch Automatismen und APIs verwaltet werden können. Bei dieser Option fällt eine monatliche Grundgebühr sowie weitere Gebühren beim Verkauf an. Weitere Informationen dazu findest du auf der link:http://www.amazon.de/b/ref=nav_cs_sell/279-9008302-8223762?ie=UTF8&node=2383621031[Website von Amazon^].

Nachdem du dich registriert hast, richte bei Amazon die link:https://developer.amazonservices.de/gp/mws/index.html[MWS-Schnittstelle^] ein. MWS steht für Marketplace Web Service. Dieser Service unterstützt API-Funktionen und muss daher für den Datenaustausch mit plentymarkets eingerichtet werden. Wähle die MWS-Option, die einer Anwendung den Zugriff auf dein Amazon-Konto ermöglicht. Du benötigst folgende Informationen für die Schnittstelle:

*  Benutzername des Entwicklers: plentymarkets
*  Entwickler-ID EU-Marktplätze: 6860-7675-7360
*  Entwickler-ID Marktplatz USA: 5751-6263-3716

Öffne das Menü *Einstellungen » Benutzerberechtigungen* in der Amazon Seller Central und klicke auf *Entwickler autorisieren*. Um Amazon MWS einzurichten, gib den *Namen des Entwicklers* und die *Entwickler-ID* ein und klicke auf *Weiter*. +

Wenn du Amazon MWS eingerichtet hast, erhältst du die Verkäufer-ID, die du zum Einrichten der Schnittstelle in plentymarkets benötigst.

[#200]
==  Amazon in plentymarkets einrichten

Nimm die folgenden Einstellungen in plentymarkets vor, um die Schnittstelle zu Amazon einzurichten.

[#300]
===  Konto einrichten

Richte zunächst ein neues Konto für Amazon in plentymarkets ein.

[.instruction]
Neues Konto anlegen:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen*.
.  Klicke auf *Neues Konto*. +
→ Das Fenster *Neues Amazon Seller Central-Konto erstellen* wird geöffnet.
.  Wähle eine *Amazon-Plattform* aus.
.  Trage die *E-Mail-Adresse* ein, die du für die Plattform verwendest.
.  Klicke auf *Neues Konto erstellen*. +
→ Das Konto wird angelegt.
.  Klicke links auf das zuvor angelegte Konto in der Kontenübersicht.
.  Nimm die Einstellungen vor. Beachte dabei die Erläuterungen in den Tabellen 1 bis 4.
. *Speichere* die Einstellungen.

[TIP]
.Europäisches Verkäuferkonto
====
"Amazon hat seine europäischen Marktplätze vereint. Dies ermöglicht Ihnen, Produktangebote für alle Amazon-Marktplätze in Deutschland, Frankreich, Großbritannien, Spanien und Italien zu erstellen und zu verwalten. Sie haben die Kontrolle darüber, was Sie wo verkaufen. Ihre Geschäfte wickeln Sie komfortabel über ein einziges Verkäuferkonto ab. Ihr Verkäuferkonto ermöglicht Ihnen automatisch, Ihre Angebote auch auf Amazon.co.uk, Amazon.fr, Amazon.es und Amazon.it zu verkaufen. Sie werden aufgefordert, einen Heimat-Marktplatz zu bestimmen, wobei jeder dieser 4 Marktplätze gewählt werden kann. Wir empfehlen Ihnen, als Heimat-Marktplatz das Land zu wählen, von dem aus Sie operieren und Ihre Bestellungen erfüllen." (Quelle: Amazon) +
Beachte die weiteren link:http://services.amazon.de/programme/verkaufen-bei-amazon/ein-europisches-konto/[Informationen zum europäischen Verkäuferkonto^] sowie die link:https://services.amazon.de/programme/online-verkaufen/faq.html[FAQ^] von Amazon.
====

[#350]
[.subhead]
Amazon-Plattform

Wenn du mit einem europäischen Verkäuferkonto mehrere Amazon-Plattformen nutzt, richte, je nachdem, welche Optionen du nutzen möchtest, für jede Plattform ein neues Konto mit plattformspezifischen Einstellungen in plentymarkets ein. Richte einzelne Konten für den Preisabgleich, den Artikeldatenexport und den Import von ausstehenden Aufträgen ein. Wenn du beispielsweise nur den Bestandsabgleich nutzen möchtest, lege kein eigenes Konto für die unterschiedlichen Länderplattformen an. +
Die Zugangsdaten sind für alle Plattformen gleich.

[TIP]
.Amazon-Plattformen
====
Mit plentymarkets kannst du auf den Amazon-Plattformen Amazon.de, Amazon.co.uk, Amazon.fr, Amazon.it, Amazon.es, Amazon.com, Amazon.ca und Amazon.com.mx verkaufen.
====

[#400]
===  Basiseinstellungen vornehmen

Alle Angaben im Bereich *Zugangsdaten* des Tabs *Einstellungen* sind Pflichtangaben. Trage die Angaben ein und beachte die Erläuterungen in <<einstellungen-zugangsdaten>>.

[[einstellungen-zugangsdaten]]
.Einstellungen für *Zugangsdaten*
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Amazon-Plattform*
| Eine Plattform muss direkt beim Anlegen gewählt werden und kann hier geändert werden. Wenn du ein europäisches Verkäuferkonto hast, kannst dz für jede Plattform, auf der du verkaufen möchtest, eigene Einstellungen vornehmen. Weitere Informationen dazu findest du im Abschnitt <<Konto einrichten, Amazon-Plattform>>.

|*Verkäufer-ID*
| Verkäufer-ID eintragen, wie von Amazon erhalten. Wenn du ein europäisches Verkäuferkonto hast, ist die Verkäufer-ID für jede Plattform die selbe.

|*Händler-Token*
| Händler-Token eintragen, wie im Seller Central zu finden.

|*E-Mail-Adresse*
| E-Mail-Adresse eintragen, die als Benutzername zum Seller Central-Konto verwendet wird.

|*Aktiv*
| Häkchen setzen, um die Schnittstelle zu aktivieren. +
Damit nicht schon im Vorfeld unerwünscht Daten übertragen werden, Schnittstelle erst aktivieren, wenn alle Einstellungen gespeichert wurden.

|*B2B*
| Durch Setzen des Häkchens wird dieses Konto für Amazon Business aktiviert.
|====

Im Bereich *Basiseinstellungen* nimmst du u.a. Einstellungen für den SKU-Aufbau vor. Die SKU (Stock Keeping Unit) ist eine eindeutige Referenznummer für alle Artikel und Artikelvarianten bei Amazon.

[[tab-basiseinstellungen]]
.Einstellungen im Tab *Basiseinstellungen*
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Mandant*
| Mandant wählen, für den Aufträge von Amazon zugeordnet werden.

|*SKU-Aufbau*
| Eine der folgenden Optionen wählen: +
*Varianten-ID* +
*GTIN wenn vorhanden, sonst Varianten-ID* +
*Variantennummer wenn vorhanden, sonst Varianten-ID* +
Die hier gewählte Einstellung greift nur für Artikel, die zum ersten Mal zu Amazon exportiert werden. SKUs sind die Basis, auf der Amazon und plentymarkets Daten austauschen. +
*Wichtig*: Diese Einstellung nicht mehr ändern, nachdem Artikel an Amazon übertragen wurden, da sonst die Kommunikation zwischen plentymarkets und Amazon (z.B. für Bestands-Updates) nicht mehr funktioniert. +
Anmerkung zu *Bereits bestehende SKU-Nummern zuordnen* unterhalb der Tabelle beachten.

|*Katalog wurde mit SSW gelistet*
|*Ja* = Artikel werden auf Amazon mit *link:https://ssw.starsellersworld.com/[starsellersworld^]* gelistet. Beim Auftragsimport wird dann die SKU des Artikels nach dem letzten "-" abgeschnitten, um eine Zuordnung des Artikels im System zu ermöglichen. +
*Nein* = Artikel werden auf Amazon nicht mit starsellersworld gelistet.

|*Rechnung erzeugen*
| Wählen, ob Rechnungen von plentymarkets oder Amazon erzeugt werden sollen. +
*plentymarkets* = Rechnungen werden von plentymarkets erzeugt. +
*VCS plentymarkets* = *Voraussetzung:* Amazon VCS wird genutzt. Amazon-Rechnungen werden automatisch von plentymarkets erzeugt und zu Amazon übertragen. +
*VCS Amazon* = *Voraussetzung:* Amazon VCS wird genutzt. Amazon-Rechnungen werden von Amazon erzeugt.
|====

[TIP]
.SKU-Einstellungen und Warenbestandsabgleich
====
Wenn du bei allen Plattformen die gleichen Einstellungen für SKU-Nummern wählst, kannst du mit einem Warenbestandsabgleich alle Plattformen des europäischen Verkäuferkontos abgleichen. Wenn die Einstellungen unterschiedlich sind, muss der Abgleich für jede Plattform separat durchgeführt werden.

Da der Warenbestand bei einem Europäischen Verkäuferkonto global verwaltet wird, genügt es, beim Heimat-Marktplatz den Bestand zu aktivieren. Voraussetzung dafür ist die Übereinstimmung der SKU-Einstellungen.
====

[IMPORTANT]
.Bereits bestehende SKU-Nummern zuordnen
====
Wenn du bereits auf Amazon verkaufst und nun anfangen möchtest, deine Artikel über plentymarkets auf Amazon zu verkaufen, ordne deine bestehenden SKU-Nummern Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen » Tab: Verfügbarkeit* zu.
====

[IMPORTANT]
.plentymarkets E-Mail-Adressen autorisieren
====
Alle plentymarkets E-Mail-Adressen, über die du Nachrichten an Amazon schickst, müssen zuvor bei Amazon im Seller Central-Bereich autorisiert werden.
====

[#500]
===  Artikeleinstellungen vornehmen

Im Tab *Artikeleinstellungen* nimmst du Einstellungen zum Artikelexport vor. Du legst u.a. Automatismen und Exportfilter fest. Wenn du Exportfilter einstellst, werden nur Artikel mit den gewählten Filtern exportiert.

[[tab-artikeleinstellungen]]
.Einstellungen im Tab *Artikeleinstellungen*
[cols="1,3"]
|====
| Einstellung | Erläuterung

2+| Automatismen

|*Artikelexport; +
Preisänderungen; +
Bestandsabgleich; +
Bestandsänderungen*
| Keine Übertragung oder je ein Intervall für die Übertragung wählen.

2+| Exportfilter

|*Artikelverfügbarkeit; +
Export-Kategorien; +
BMVD-Export-Kategorien; +
Markierung 1; +
Markierung 2; +
Shop-Artikel*
| Nur Artikel mit den gewählten Filtern werden exportiert. +
*Artikelverfügbarkeit* = Wenn ein Parent (Hauptartikel) eine nicht freigegebene Verfügbarkeit hat, findet keine Übertragung statt. +
*Markierung 1* und *2* = Diese Filter greifen nur für den täglichen Export. +
*Shop-Artikel* = Wenn du den Filter *Nur im Webshop sichtbare Artikel*  wählst, müssen die Artikel, die exportiert werden sollen, auch für den Shop aktiviert sein, der für das gewählte Amazon-Konto im Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen » Tab: Einstellungen* für die Option *Mandant* gewählt wurde. Wenn du den Filter *Alle Artikel* wählst, werden alle Artikel exportiert, unabhängig vom gewählten Shop.

2+| Exporteinstellungen

|*Artikelname; +
Artikelbeschreibung*
| Die eingestellten Informationen werden exportiert.

|*HTML-Tags erlauben*
| Die folgenden Tags sind zugelassen: &lt; br &gt;, &lt; b &gt;, &lt; i &gt;, &lt; p &gt; ,&lt; ul &gt;, &lt; li &gt;, &lt; table &gt;, &lt; tr &gt;, &lt; td &gt;, &lt; th &gt;, &lt; tbody &gt; und &lt; strong &gt;.

|*Lagerauswahl*
|*Bestandsmenge des Vertriebslagers mit aktuell größtem Bestand übertragen*, *Hauptlager des Artikels verwenden*, *Summe der Bestandsmengen aller Vertriebslager übertragen* oder *Lager wählen* für den Export wählen. Bei der Option *Lager wählen* erscheint direkt darunter die Einstellung *Lager*, bei der ein oder mehrere Lager gewählt werden.

|*Lager*
| Ein oder mehrere Lager wählen. Diese Einstellung erscheint nur, wenn unter Lagerauswahl die Option *Lager wählen* gewählt wurde. +
Die Bestände der gewählten Lager werden summiert und zu Amazon übermittelt. Dabei werden auch Puffer und Maximalwerte berücksichtigt. Somit können auf bestimmten Amazon-Konten oder Amazon-Plattformen gezielt die Bestände gewisser Lager angeboten werden. +
Wenn unter *Lagerauswahl* die Option *Lager wählen* gewählt wurde, aber kein Lager gewählt wurde, wird der Artikel nicht exportiert, da kein Bestand ermittelt werden kann.

|*Bestandspuffer*
| Ist der Artikel auf Netto-Warenbestand beschränkt, wird der exportierte Bestand um den eingetragenen Wert verringert.

|*Maximaler Warenbestand*
| Bestimmt die obere Grenze des exportierten Bestands für alle Artikel. Diese Einstellung hat Priorität vor der unten beschriebenen Einstellung *Menge für Artikel ohne Bestandsbindung*.

|*Menge für Artikel ohne Bestandsbindung*
| Bei Artikeln mit der Einstellung *keine Beschränkung* wird der Maximalwert aus realem Bestand und der hier definierten Menge übermittelt. +
*Beispiel*: Einstellung 0, Nettowarenbestand 8. plentymarkets übermittelt 8. +
Artikel mit der Einstellung *Beschränkung auf Netto-Warenbestand* werden hier nicht berücksichtigt.

|*Durchschnittliche Lieferzeit*
|*Nicht übertragen*, *"Mittlere Lieferzeit in Tagen" übermitteln* oder *"Mittlere Lieferzeit in Tagen" übermitteln + Lieferverzugsaufschlag* wählen.

|*Bearbeitungszeit*
| Lieferverzugsaufschlag in Tagen eintragen. Wird nur angezeigt, wenn bei *Durchschnittliche Lieferzeit* die Option *"Mittlere Lieferzeit in Tagen" übermitteln + Bearbeitungszeit* gewählt wurde.

|*Artikelnummer des Herstellers*
| Wählen, ob SKU, Variantennummer, GTIN, Varianten-ID, Externe Varianten-ID, Modellnummer oder kein Wert im Feld part_number der CSV-Datei übertragen werden soll.

|*Zusätzliche SKU*
| Datenaustausch für zusätzliche Amazon-SKUs aktivieren. +
*ALLE*, *Bestandsabgleich*, oder *Preisabgleich* für <<Zusätzliche SKUs manuell festlegen, zusätzliche SKUs>> aktivieren.
|====

[#600]
===  Auftragseinstellungen vornehmen

Im Tab *Auftragseinstellungen* nimmst du Einstellungen zum Versand vor. Das Kürzel MFN steht für merchant-fulfilled network, d.h. der Händler wickelt den Kauf ab.

[[tab-auftragseinstellungen]]
.Einstellungen im Tab *Auftragseinstellungen*
[cols="1,3"]
|====
| Einstellung | Erläuterung

2+| Eigener Versand (MFN)

|*Auftragsimport*
| Keine Übertragung oder je ein Intervall für den Import wählen.

|*Versandbestätigung*
| Keine Übertragung oder je ein Intervall für den Export der Versandbestätigung an Amazon wählen.

|*Auftragsposition*
| Bestimmt die Darstellung des Artikelnamens in der Auftragsposition. Eine der folgenden Optionen wählen: +
*Artikelname aus Shop übernehmen* +
*Artikelname von Amazon übernehmen - mit SKU* +
*Artikelname von Amazon übernehmen - ohne SKU*

|*Zahlungseingang*
|*Zahlungseingang gebucht* wählen, wenn der Zahlungseingang bei Auftragsimport als gebucht angezeigt werden soll.

|*Status für übertragene Retouren*
|<<auftraege/auftraege-verwalten#1200, Auftragsstatus>> für Retouren wählen, die erfolgreich an Amazon gemeldet wurden.

|*Status für nicht übertragene Retouren*
|<<auftraege/auftraege-verwalten#1200, Auftragsstatus>> für Retouren wählen, die nicht erfolgreich an Amazon gemeldet wurden.

|*Ausstehende Aufträge*
| Wählen, ob ausstehende Aufträge von Amazon alle 15 Minuten importiert werden sollen, oder nie.

|*Gutschriftenimport*
| Wählen, ob Amazon-Gutschriften in dein plentymarkets System importiert werden sollen. +
*Ja* = Amazon-Gutschriften werden alle 4 Stunden in dein plentymarkets System importiert. +
*Nein* = Gutschriften werden nicht importiert. Wenn du *Nein* wählst, erstelle eine Ereignisaktion, um Retouren als Gutschriften in dein plentymarkets System zu importieren. +
Der Gutschriftenimport ist standardmäßig deaktiviert.

2+| Versand durch Amazon (FBA)

|*Aktiv*
| Häkchen setzen, um den Versand durch Amazon zu aktivieren.

|*Herkunft*
| Wählen, ob nur Aufträge von Amazon mit FBA abgewickelt werden oder ob auch Aufträge von anderen <<omni-channel/auftragsherkunft#, Herkünften>> mit FBA abgewickelt werden können.

|*Status*
|<<auftraege/auftraege-verwalten#1200, Status>> der Aufträge wählen, die von Amazon importiert wurden.

|*Lager*
| Wählen, welches <<Lager für Amazon FBA anlegen, Amazon FBA-Lager>> für den Bestandabgleich des Kontos verwendet werden soll. Dieses Lager wird auch für die FBA-Auftragszuordnung des Kontos verwendet, falls kein FBA-Auftrag aufgrund eines nicht eingerichteten Lagers für das Auftragsland zugeordnet werden konnte.

|*Warenausgang*
| Wählen, ob der Warenausgang als gebucht markiert werden soll oder nicht. Die Option *Als gebucht markieren* erzeugt keine Warenbewegung. Um eine Warenbewegung zu erzeugen, muss die Option *Nicht als gebucht markieren* eingestellt sein und eine Ereignisaktion eingerichtet werden.

|*Retourenimport*
| Keine Übertragung oder *täglichen* Import von Retouren wählen.

|*Gutschein bei Retouren berücksichtigen*
| Wählen, ob Gutscheine bei Retouren berücksichtigt werden sollen oder nicht. Wurde der FBA-Auftrag komplett oder teilweise mit einem Gutschein beglichen, wird der Gutschein bei der Retoure hinzugefügt und verrechnet. Dabei wird kein Mindestbestellwert für den Gutschein berücksichtigt.

|*Bestandsimport*
| Wählen, ob der Bestandsimport *stündlich* oder nie ausgeführt werden soll.

|*Status für übertragene Aufträge*
|<<auftraege/auftraege-verwalten#1200, Auftragsstatus>> für Aufträge wählen, die erfolgreich an FBA übertragen wurden.

|*Artikelpakete Multichannel*
| Wählen, welche Positionen an Amazon übertragen werden sollen. +
*Alle Auftragspositionen übertragen* = Alle Positionen, die sich im Auftrag befinden, an Amazon übertragen. Wenn diese Option gewählt wird, werden die Paketposition und die Paketbestandteile an Amazon übertragen. +
*Nur Paketposition übertragen* = Nur die Paketposition wird an Amazon übertragen. +
*Ohne Paketposition übertragen* = Nur die Paketbestandteile werden an Amazon übertragen.

|*Versandkategorie*
|*Standard* = normaler Versand, *Expedited* = Schnellversand oder *Priority* = bevorzugt (schnellster Versand) wählen.
|====

[#650]
=== Bestellberichte abrufen

Im Tab *Prozessstatus* rufst du Informationen zu den Bestellberichten deiner MFN-Aufträge ab. Über die Schaltfläche *Zeitplan abrufen* werden das Intervall, in dem die Bestellberichte von Amazon generiert werden, und der Zeitpunkt des nächsten Abrufs von deinem plentymarkets Systems angezeigt.

[#660]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit Amazon-Plattformen verknüpfen kannst, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft für die Amazon-Plattformen aktiviert werden.

[.instruction]
Auftragsherkunft für Amazon aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setze bei den gewünschten Amazon-Plattformen ein Häkchen.
. *Speichere* die Einstellungen.


[#700]
==  Artikelverfügbarkeit einstellen

Artikel, die du auf Amazon verkaufen möchtest, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Amazon-Länderplattform einstellen:

.  Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
.  Wechsele in das Tab *Verfügbarkeit*.
.  Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Wähle *Web-API*.
. Klicke auf *Hinzufügen*.
.  Aktiviere in der gleichen Liste die Amazon-Länderplattform(en), für die der Artikel verfügbar sein soll.
.  Klicke auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* die Einstellungen.
.  Wechsele in das Tab *Multi-Channel*.
.  Nimm die Einstellungen im Bereich *Amazon* vor. Beachte dazu die Erläuterungen in Tabelle 5.
. *Speichere* die Einstellungen.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

[[artikelverfügbarkeit-amazon]]
.Artikelverfügbarkeit für Amazon einstellen
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Produkttyp*
|<<daten/export-import/datenformate/item#50, Amazon-Produkttyp>> wählen.

|*FBA-Abwicklung*
| Einen der Amazon-Marktplätze *AMAZON_EU* (Europa), *AMAZON_FE* (Ferner Osten), *AMAZON_NA* (Nordamerika) wählen, wenn der Artikel über FBA vermarktet werden soll.

|*Amazon FBA*
| Aktivieren, wenn die FBA-Funktion genutzt werden soll und wenn FBA-Bestände importiert werden sollen. +
Wenn du die Option *Amazon FBA* aktivierst, können für diesen Artikel FBA-Bestände in plentymarkets importiert werden und Amazon Multi-Channel-Aufträge, die mit FBA versendet werden, können angemeldet werden.
|====

[IMPORTANT]
.Artikelverfügbarkeit für MFN und FBA
====
Wenn du deine Artikel für MFN und FBA verfügbar stellen willst, wähle, am Beispiel für Deutschland, die Amazon Länderplattform *Amazon Germany* und die Länderplattform *Amazon FBA Germany.*
====

[#750]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügst du, wenn nötig, manuell marktplatzspezifische SKUs sowie Parent-SKUs hinzu. Wenn du z.B. bereits  auf Amazon verkaufst und nun anfangen möchtest, deine Artikel über plentymarkets auf Amazon zu verkaufen, ordne deine bestehenden SKU-Nummern in diesem Menü zu. +

*_Oder:_* Importiere SKUs mit dem Datenformat *VariationSKU*.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechsele in das Tab *Verfügbarkeit*.
.  Klicke im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
.  Wähle die Herkunft *Amazon*, um die SKU hinzuzufügen.
.  Wähle das dazugehörige Marktplatzkonto.
.  Gib die SKU ein.
.  Gib die Parent-SKU ein.
.  Klicke auf *Hinzufügen*. +
→ Die SKUs werden gespeichert und angezeigt.

SKUs können nachträglich geändert werden. Beachte allerdings, dass SKU-Änderungen dazu führen können, dass Amazon die Artikel nicht mehr erkennen bzw. zuordnen kann.

[IMPORTANT]
.Parent-SKU
====
Parent-SKUs können sowohl für den Artikel als auch für Varianten hinterlegt werden. Die manuelle SKU-Pflege erlaubt es, für Varianten eines Artikels die Parent-SKU komplett anderer Artikelvarianten zu vergeben. So kann z.B. für einen Artikel mit 5 Varianten 5 mal die Parent-SKU einer Variante, die einem ganz anderen Artikel angehört, vergeben werden. Diese Varianten werden auf Amazon als Varianten des Artikels, mit dessen Parent-SKU sie verknüpft sind, gelistet.  +
Wird bei einer Variante eine andere Parent-SKU vergeben als bei den restlichen Varianten eines Artikels, werden auf Amazon zwei verschiedene Artikel gelistet, aber in plentymarkets muss dafür nur ein Artikel gepflegt werden.
====

[#760]
==  Zusätzliche SKUs manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügst du, wenn nötig, manuell SKUs hinzu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechsele in das Tab *Verfügbarkeit*.
.  Klicke im Bereich *Zusätzliche SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue zusätzliche SKU* wird angezeigt.
.  Wähle die Herkunft *Amazon*, um die SKU hinzuzufügen.
.  Wähle das dazugehörige Marktplatzkonto.
.  Gib die SKU ein.
.  Klicke auf *Hinzufügen*. +
→ Die SKUs werden gespeichert und angezeigt.

SKUs können nachträglich geändert werden.

[.subhead]
Bestands- und Preisabgleich für zusätzliche SKUs aktivieren

Zusätzliche SKUs werden beim Amazon-Auftragsimport automatisch berücksichtigt. Den Bestands- und Preisabgleich für zusätzliche SKUs aktivierst du manuell im Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen » Tab: Artikeleinstellungen*. +

Der Bestands- und Preisabgleich für zusätzliche SKUs läuft zusammen mit dem normalen Bestands- und Preisabgleich in dem Intervall, das du unter *System » Systemeinstellungen » Märkte » Amazon » Einstellungen » Tab: Artikeleinstellungen* im Bereich *Automatismen* für die Optionen *Preisänderungen* und *Bestandabgleich* gewählt hast.

[.instruction]
Bestands- und Preisabgleich aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen » Tab: Artikeleinstellungen*.
. Setze im Bereich *Exporteinstellungen* für die Option *Zusätzliche SKU* ein Häkchen bei *Bestandsabgleich* und *Preisabgleich*, je nachdem, welche Optionen du aktivieren möchtest. *ALLE* aktiviert den Bestandsabgleich und den Preisabgleich.
. *Speichere* die Einstellungen.

[#770]
== ASIN mit Varianten verknüpfen

Die ASIN (= Amazon Standard Identification Number) ist eine eindeutige Produktkennzeichnung auf Amazon, die den Verkauf auf Amazon erleichtert. Um unkompliziert und schnell Produkte auf Amazon verkaufen zu können, die dort bereits gelistet sind, sollte deshalb an jeder Variante eine ASIN gespeichert sein.

//Schreiben, dass man mit ASIN nur noch Preis, Bestand und GTIN angeben muss und keine technischen Daten mehr am Artikel pflegen muss?

[IMPORTANT]
.GTIN an Variante hinterlegen
====
ASINs werden anhand des Barcodes GTIN13 auf Amazon gesucht und in plentymarkets importiert. Stelle deshalb sicher, dass an allen Varianten ein Barcode (GTIN13) hinterlegt ist, da ansonsten keine ASINs gefunden werden können.
====

Durchlaufe zunächst den *Amazon ASIN-Import*-Assistenten im Menü *System » Assistenten*, um passende ASINs zu deinen Varianten in dein plentymarkets System zu importieren. Mit dem Assistenten kannst du außerdem neu importierte ASINs automatisch mit Varianten verknüpfen lassen.

Im Menü *System » Systemeinstellungen » Märkte » Amazon » ASIN-Verknüpfung* erhältst du eine Übersicht zu importierten ASINs und kannst ASINs per Gruppenfunktion mit Varianten verknüpfen.

//Welche ASINs sind hier aufgeführt? Wann werden neue ASINs importiert?

[#773]
=== Importierte ASINs verwalten

Im Menü *System » Systemeinstellungen » Märkte » Amazon » ASIN-Verknüpfung* erhältst du eine Übersicht zu verknüpften und noch nicht verknüpften ASINs. In der Übersicht hast du außerdem die Möglichkeit, einzelne ASINs mit Varianten zu verknüpfen.

[[asin-verknuepfung-uebersicht]]
.Übersicht zu importierten ASINs
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*GTIN*
|Die an der Variante gespeicherte GTIN.

|*Artikelname*
|Der Artikelname der Variante.

|*Attributsname*
|Die mit der Variante verknüpften Attribute.

|*Plattform*
|Die Amazon-Plattform, auf der die Variante eingestellt ist.

|*ASINs*
|Hier stehen die verfügbaren ASINs zu der Variante. Es kann auch mehrere passende ASINs zu einer Variante geben. +
In dieser Spalte können ASINs manuell verknüpft werden. Um eine ASIN mit einer Variante zu verknüpfen, setze ein Häkchen neben der ASIN, die verknüpft werden soll und klicke auf *Speichern*.
//Einzelne Verknüpfung nochmal als separate Handlungsanweisung?

|*Fehler*
|Hier werden Fehlermeldungen aufgeführt, die beim Import der ASIN aufgetreten sind.
//Welche Fehlermeldungen gibt es?

|*Verknüpfung*
|Zeigt an, ob die ASIN bereits mit einer Variante verknüpft ist (Häkchen) oder nicht (X).
|====

[#775]
=== ASINs per Gruppenfunktion verknüpfen

Nutze die Gruppenfunktion im Menü *System » Systemeinstellungen » Märkte » Amazon » ASIN-Verknüpfung*, um mehrere ASINs auf einmal mit Varianten zu verknüpfen.

[.instruction]
Gruppenfunktion ausführen:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » ASIN-Verknüpfung*.
. Klicke auf *Gruppenfunktion*. +
→ Ein Bereich mit den Aktionen der Gruppenfunktion wird ausgeklappt.
. Wähle im Bereich *Gruppenfunktion* die Aktion, die du ausführen möchtest. Beachte dazu die Erläuterungen in <<gruppenfunktion-gtin-asin>>.
. Setze ein Häkchen in den Zeilen der Varianten, die du mit der Gruppenfunktion bearbeiten möchtest.
. Klicke auf *Gruppenfunktion ausführen*.

[[gruppenfunktion-gtin-asin]]
.Aktionen der Gruppenfunktion
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Automatisch die erste ASIN verknüpfen*
|Wenn mehrere passende ASINs zu der Variante gefunden wurden, wird automatisch die erste ASIN verknüpft, die gefunden wurde.

|*Alle verknüpfen*
|Wenn mehrere passende ASINs zu der Variante gefunden wurden, werden alle gefundenen ASINs mit der Variante verknüpft.
|====

[#780]
== Preise festlegen

In diesem Kapitel erfährst du, wie du Verkaufspreise, UVPs und Aktionspreise für Amazon bestimmst.

[IMPORTANT]
.Verkaufspreis ohne Preistyp festlegen
====
Lege einen Verkaufspreis ohne Preistyp (UVP, Aktionspreis, Setpreis) fest, da deine Artikel ansonsten nicht zu Amazon übertragen werden.
====

[#800]
===  Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für Amazon-Länderplattformen einen Verkaufspreis festzulegen. Dieser Preis wird auf den Länderplattformen angezeigt.

[.instruction]
Verkaufspreis für Länderplattformen festlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der gewünschten Amazon-Herkunft.
. Setze ein Häkchen bei dem gewünschten Amazon-Konto.
. Öffne das Tab *Sprache*.
. Gib in die Felder *Interner Name* und *Externer Name* die gewünschten Namen ein. +
→ Wenn diese Felder nicht befüllt sind, wird der Preis nicht berücksichtigt.
. *Speichere* die Einstellungen.

[#820]
=== UVP festlegen

Gehe wie im Folgenden beschrieben vor, um für Amazon-Länderplattformen einen UVP festzulegen. Dieser Preis wird als *List-Price* zu Amazon übertragen.

[.instruction]
UVP für Länderplattformen festlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze in der Zeile *Preistyp* ein Häkchen bei *UVP*.
. Setze ein Häkchen bei der gewünschten Amazon-Herkunft.
. Setze ein Häkchen bei dem gewünschten Amazon-Konto.
. Öffne das Tab *Sprache*.
. Gib in die Felder *Interner Name* und *Externer Name* die gewünschten Namen ein. +
→ Wenn diese Felder nicht befüllt sind, wird der Preis nicht berücksichtigt.
. *Speichere* die Einstellungen.

[#850]
===  Aktionspreis festlegen

Um Aktionspreise an Amazon zu übermitteln, muss zusätzlich zum regulären Verkaufspreis ein weiterer Verkaufspreis vom Preistyp *Aktionspreis* angelegt und mit dem Artikel verknüpft werden. Zudem müssen die Merkmale *SaleStartDate* und *SaleEndDate* angelegt und mit dem Artikel verknüpft sein. Gehe wie im Folgenden beschrieben vor, um für Amazon-Artikel Aktionspreise festzulegen.

[.instruction]
Aktionspreis für Amazon-Länderplattformen festlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze in der Zeile *Preistyp* ein Häkchen bei *Aktionspreis*.
. Setze ein Häkchen bei der gewünschten Amazon-Herkunft.
. Setze ein Häkchen bei dem gewünschten Amazon-Konto.
. Öffne das Tab *Sprache*.
. Gib in die Felder *Interner Name* und *Externer Name* die gewünschten Namen ein. +
→ Wenn diese Felder nicht befüllt sind, wird der Preis nicht berücksichtigt.
. *Speichere* die Einstellungen.

Verknüpfe anschließend diesen Aktionspreis mit dem Artikel im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Einstellungen*.

Als nächstes legst du die Merkmale *SaleStartDate* und *SaleEndDate* an und verknüpfst diese mit dem Amazon-Produkttyp. Gehe wie im Folgenden beschrieben vor, um das Merkmal *SaleStartDate* anzulgen und zu verknüpfen. Gehe beim Merkmal *SaleEndDate* auf die gleiche Weise vor, wobei du als Namen *SaleEndDate* eingeben und  bei der Verknüpfung das Amazon-Feld *sale_end_date* wählst.

[.instruction]
Merkmal für Aktionspreis anlegen und mit Amazon-Produkttyp verknüpfen:

. Öffne das Menü <<artikel/artikel-verwalten#480, System » Systemeinstellungen » Artikel » Merkmale » Tab: Neues Merkmal>>.
. Gib den Namen *SaleStartDate* in der Zeile *Namen (Intern)* ein. +
→ Für das Merkmal darf kein anderer Name benutzt werden, da sonst der Aktionspreis nicht an Amazon übermittelt wird.
. Gib einen *Namen* in der gewünschten Sprache im Bereich *Webshop* ein.
. Wähle als Merkmaltyp *Text* aus der Dropdown-Liste.
. Wähle bei *Amazon-Verknüpfung* den Produkttyp. +
→ Eine neue Dropdown-Liste erscheint.
. Wähle in der Dropdown-Liste das Amazon-Feld *sale_from_date*.
. Klicke auf *Hinzufügen*. +
→ Die Verknüpfung wird angelegt.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend die Merkmale mit dem Artikel und gibst jeweils das Datum im Format *JJJJ-MM-TT* ein.

[#900]
==  Frei definierbare Felder im Amazon-Export Seller Central einrichten

Die frei definierbaren Felder dienen der Anpassung der Daten, die du zu Amazon exportierst. Diese Felder müssen mit <<artikel/artikel-verwalten#70, Freitextfeldern>> verknüpft werden. Die Freitextfelder ermöglichen dir eine individuelle Anpassung der Artikeldaten und somit eine genaue Beschreibung der Artikel.

[#1000]
===  Freitextfelder anlegen

Lege im ersten Schritt die <<artikel/artikel-verwalten#70, Freitextfelder>> an, die du mit den frei definierbaren Feldern bei Amazon verknüpfen möchtest. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Freitextfelder anlegen:

.  Öffne das Menü *System » Systemeinstellungen » Artikel » Freitextfelder*.
.  Trage unter *Feldbezeichnung* den Namen ein.
.  Wähle den *Datentyp* aus der Dropdown-Liste.
.  Trage die maximal mögliche *Zeichenlänge* für das Freitextfeld ein.
. *Speichere* die Einstellungen. +
→ Die Freitextfelder stehen am nächsten Tag im Bearbeitungsfenster der Artikel im Tab *Felder* zur Verfügung. Dort trägst du den eigentlichen Text ein.

[#1100]
===  Freitextfelder verknüpfen

Nachdem du die Freitextfelder eingerichtet hast, verknüpfst du diese wie im Folgenden beschrieben mit den Exportfeldern bei Amazon Seller Central.

[.instruction]
Freitextfelder mit Amazon-Exportfeldern verknüpfen:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Frei definierbare Felder*.
.  Öffne das Untermenü *Frei definierbare Felder im Amazon-Export (Seller Central)*.
.  Klappe die Kategorie auf.
.  Wähle ein *Exportfeld* aus der Dropdown-Liste.
.  Wähle das passende Feld aus der Dropdown-Liste *Freitextfeld*. +
→ Du kannst nur Felder auswählen, die du angelegt hast.
. *Speichere* die Einstellungen.

[#1200]
==  Frei definierbare Felder im Amazon-Export Marketplace einrichten

Frei definierbare Felder im Amazon-Export Marketplace verknüpfst du für die BMVD-Kategorien Bücher, Musik, Video und DVD.

[.instruction]
Freitextfelder verknüpfen:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Frei definierbare Felder*.
.  Öffne das Untermenü *Frei definierbare Felder im Amazon-Export (Marketplace)*.
.  Wähle die Freitextfelder aus den Dropdown-Listen aus.
. *Speichere* die Einstellungen.
.  Öffne das Menü *System » Systemeinstellungen » Artikel » Freitextfelder*.
.  Trage bei den eben gewählten Freitextfeldern unter *Feldbezeichnung* den Namen ein.
.  Wähle aus der Dropdown-Liste in der Spalte *Datentyp* einen Typ aus.
.  Trage die maximal mögliche *Zeichenlänge* für das Freitextfeld ein.
. *Speichere* die Einstellungen. +
→ Am nächsten Tag stehen diese Freitextfelder im Bearbeitungsfenster der Artikel im Tab <<artikel/artikel-verwalten#70, Felder>> zur Verfügung. Dort trägst du die *Ziffern* gemäß <<optionen-item-condition>> und <<optionen-will-ship-internationally>> ein.

[TIP]
.Freitextfelder mit Einschränkung
====
Für die Felder *item-condition* und *will-ship-internationally* sind nur vorgegebene Werte möglich. Das Feld *item-note* kann als Textfeld genutzt und für jeden Artikel neu formuliert werden.
====

[IMPORTANT]
.Amazon-Produkttyp und Artikeldaten eintragen
====
Damit der Export richtig funktioniert, muss im Menü *Artikel » Artikel bearbeiten* im Tab *Multi-Channel* der *Amazon-Produkttyp* ausgewählt sein: *Marketplace - Bücher*, *Marketplace - Musik*, *Marketplace - Video*, *Marketplace - DVD*. Des Weiteren muss in den Artikeldaten entweder eine *EAN*, *UPC* oder *ISBN* eingetragen sein.
====

Folgende Werte sind für das Feld *item-condition* möglich:

[[optionen-item-condition]]
.Optionen für das Feld *item-condition*
[cols="1,3"]
|====
| Ziffer | Bedeutung

|*1*
| Used, Like New (Gebraucht, wie neu)

|*2*
| Used, Very Good (Gebraucht, sehr gut)

|*3*
| Used, Good (Gebraucht, gut)

|*4*
| Used, Acceptable (Gebraucht, annehmbar)

|*5*
| Collectible, Like New (Sammlerstück, wie neu)

|*6*
| Collectible, Very Good (Sammlerstück, sehr gut)

|*7*
| Collectible, Good (Sammlerstück, gut)

|*8*
| Collectible, Acceptable (Sammlerstück, annehmbar)

|*9*
| Not used (Nicht benutzt)

|*10*
| Refurbished (for computers, kitchen &amp; housewares, electronics, and camera &amp; photo only) (B-Ware)

|*11*
| New (Neu)
|====

Folgende Werte sind für das Feld *will-ship-internationally* möglich:

[[optionen-will-ship-internationally]]
.Optionen für das Feld *will-ship-internationally*
[cols="1,3"]
|====
| Ziffer | Bedeutung

|*7*
| Versand innerhalb Deutschlands

|*8*
| Versand innerhalb Europas (auch Nicht-EU-Länder)

|*9*
| Versand innerhalb der EU, der Schweiz und Liechtenstein

|*10*
| Versand weltweit
|====

[#1300]
==  Kategorien verknüpfen

Damit deine Artikel beim Export zum Marktplatz Amazon automatisch in die dort vorhandenen Kategorien einsortiert werden, musst du in plentymarkets bestimmte Informationen in deinen Kategorien eintragen. Amazon stellt dazu Klassifikationslisten bereit, die sogenannten Browse Tree Guides (BTG). Diese Listen im Format MS Excel (.xls) enthalten eindeutige Klassifikationsnummern, die Browse Node IDs, die du deinen Kategorien im Webshop zuweisen musst. Die Listen sind über das Hilfe-Center im Seller Central abrufbar oder über diesen link:https://sellercentral-europe.amazon.com/gp/help/help-folder.html/?ie=UTF8&itemID=1661[Link^].

Mit der Verwendung der offiziellen Amazon.de Browse Tree Guides stellst du sicher, dass deine Produkte schnell und einfach im Katalog von Amazon.de gefunden werden. Die genannten Klassifikationsnummern bilden die Grundlage für die Produktzuordnung sowohl in der Navigation als auch für die Produktsuche. Angesichts der Vielzahl der bei Amazon.de angebotenen Artikel entscheidet eine eindeutige Zuordnung deiner Artikel zu diesen Browse Node IDs darüber, ob Kunden deine Produkte in den entsprechenden Kategorien finden können oder nicht. Nimm dir also für den nächsten Schritt etwas Zeit und wähle die Browse Node IDs sorgfältig aus.

Die Kategorieverknüpfung führst du im Menü *System » Systemeinstellungen » Märkte » Amazon » Kategorieverknüpfung* durch. In plentymarkets kannst du jeder Artikelkategorie bis zu zwei Amazon-Klassifikationsnummern aus den Browse Tree Guides zuweisen.

Die eingetragenen Werte müssen unbedingt pro Zeile separat verknüpft werden.

Die Kategorieverknüpfungen werden nur für Standard-Kategorien berücksichtigt, die im Menü <<artikel/artikel-verwalten#300, Artikel » Artikel bearbeiten » Tab: Kategorien>> des Artikels gewählt wurden.

[.instruction]
Amazon-Kategorien verknüpfen:

.  Rufe über diesen link:https://sellercentral-europe.amazon.com/gp/help/help-folder.html/?ie=UTF8&itemID=1661[Link^] das Hilfe-Center im Seller Central auf.
.  Wähle die Klassifikationsliste, z.B. Bekleidung.
.  Suche in der Spalte *Kategorie* nach der Produktbezeichnung, z.B. Bluse.
.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Kategorieverknüpfung* in deinem plentymarkets Backend.
.  Trage die Browse Node ID aus der Liste in die Tabelle bei der entsprechenden Kategorie ein.
.  Klicke auf das *Zahnrad* in der Zeile der Kategorie, um die Verknüpfungen herzustellen.

[IMPORTANT]
.Export der Browse Node ID
====
Die bei der Kategorieauswahl zugeordnete Browse Node ID wird beim Datenexport in das Feld *RecommendedBrowseNode1* übertragen. Das Feld *RecommendedBrowseNode2* wird nur für mehrfach verknüpfte Kategorien verwendet.
====

[#1350]
== Attribute und Attributwerte verknüpfen

Auch <<artikel/artikel-verwalten#390, Attribute>> müssen verknüpft werden, bevor deine Artikel zu Amazon übertragen werden können. Die Attributverknüpfung ist für Amazon auch mehrsprachig möglich.

[.instruction]
Attribute und Attributwerte verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Attribute*. +
→ Die Übersicht aller in deinem Katalog verwendeten Attribute wird geöffnet.
. Öffne ein Attribut.
. Wechsele in das Tab *Attributverknüpfung*.
. Klicke auf *Amazon*.  +
→ Der Bereich Amazon für die Attributverknüpfung wird geöffnet.
. Wähle die passende Amazon-Kategorie aus dem Drop-Down-Menü.
. Gib die zu deinen Attributwerten passenden Amazon-Attributwerte ein.
. *Speichere* die Einstellungen.
. Wiederhole den Vorgang für alle weiteren Attribute.

Als nächsten Schritt aktivierst du die Attribute in den Artikeleinstellungen.

[IMPORTANT]
.Hauptvariante ohne Attributverknüpfung deaktivieren
====
Wenn ein Artikel Varianten mit Attributverknüpfungen hat, aber die Hauptvariante keine Attributverknüpfung besitzt, muss die Hauptvariante auf inaktiv gestellt werden, damit die Hauptvariante nicht als Einzelartikel exportiert wird. Hat die Hauptvariante eine Attributverknüpfung, muss sie auf aktiv gestellt sein.
====

[#1390]
== Eigenschaften mit Amazon verknüpfen

Mit <<artikel/artikel-verwalten#3000, Eigenschaften>> hast du die Möglichkeit, auf Variantenebene individuelle Angaben zu machen.

Eigenschaften, die du im Menü <<artikel/artikel-verwalten#3100, System » Systemeinstellungen » Einstellungen » Eigenschaften » Konfiguration>> erstellt hast und zu einer Variante hinzugefügt haben, verknüpfst du im Menü *System » Systemeinstellungen » Einstellungen » Eigenschaften » Konfiguration » Tab: Amazon* mit Amazon.

[IMPORTANT]
.Eigenschaften werden beim Export vor Merkmalen priorisiert
====
Wenn du ein Merkmal und eine Eigenschaft mit demselben Amazon-Feld verknüpft hast, wird die Eigenschaft bevorzugt und das Merkmal, das mit diesem Amazon-Feld verknüpft ist, beim Artikelexport mit der Eigenschaft überschrieben.
====

[.instruction]
Eigenschaft mit Amazon verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Eigenschaften » Konfiguration*.
. Öffne die Eigenschaft.
. Klicke auf das Tab *Sichtbarkeit*.
. Aktiviere unter *Herkunft* eine *Amazon-Herkunft*.
. *Speichere* die Einstellungen.
. Wechsele in das Tab *Amazon*.
. Klicke auf *Verknüpfung hinzufügen*.
. Wähle die *Amazon-Plattform*.
. Wähle die Amazon-*Kategorie*.
. Wähle das Amazon-*Feld*.
. *Speichere* die Einstellungen. +
→ Die Eigenschaft ist mit Amazon verknüpft und wird beim nächsten Artikelexport übertragen.

[#1400]
==  Merkmal mit Amazon verknüpfen

Für den Fall, dass du für den Marktplatz Amazon die Definition von Parametern bzw. Eigenschaften für die Artikel benötigst, die du nicht direkt mit plentymarkets einrichten kannst, haben wir die hier beschriebene Lösung entwickelt: Die Integration der Parameter bzw. Werte wird über die Merkmale vorgenommen.

Das Merkmal eines Artikels wird im Menü <<artikel/artikel-verwalten#480, System » Systemeinstellungen » Artikel » Merkmale>> mit dem Amazon-Produkttyp verknüpft. In plentymarkets können maximal 16 Verknüpfungen pro Merkmal gespeichert werden.

[.instruction]
Merkmal mit Amazon-Produkttyp verknüpfen:

.  Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
.  Klappe das Merkmal auf, das du für Amazon verwenden möchtest. +
→ Der Bearbeitungsbereich des Merkmals wird geöffnet.
.  Wähle bei *Amazon-Verknüpfung* die Kategorie. +
→ Eine neue Dropdown-Liste erscheint.
.  Wähle in der Dropdown-Liste das Amazon-Feld.
.  Klicke auf *Hinzufügen*. +
→ Die Verknüpfung wird angelegt.

[TIP]
.Tipp: Merkmal multilingual übertragen
====
Generell können für die Amazon-Verknüpfung alle Merkmaltypen verwendet werden. Mit Merkmalen des Typs *Auswahl* und *Text* hast du die Möglichkeit, die Merkmale multilingual zu übertragen.
====

[.subhead]
Merkmal am Artikel aktivieren

Im letzten Schritt aktivierst du das <<artikel/artikel-verwalten#80, Merkmal>> in den Artikeleinstellungen und trägst einen Wert ein.

[.instruction]
Merkmal am Artikel aktivieren:

.  Öffne das Menü *Artikel » Artikel bearbeiten*.
.  Öffne den Artikel.
.  Wechsele in das Tab *Merkmale*.
.  Setze bei dem Merkmal ein Häkchen, um das Merkmal zu aktivieren.
. *Speichere* die Einstellungen. +
→ Das Feld für die Eingabe des Wertes wird angelegt.
.  Trage einen Wert ein.
. *Speichere* die Einstellungen.

[IMPORTANT]
.EU Compliance-Export
====
EU Compliance-Hinweise werden über Merkmal eingetragen und als eigene Flatfile zu Amazon übetragen. Wähle dazu das Amazon-Feld *EU Compliance* beim jeweiligen Amazon-Produkttyp, verknüpfe das Merkmal mit dem Artikel und wähle in den Amazon Grundeinstellungen im Tab *Artikeleinstellungen* die passende Export-Kategorie.
====

[#1500]
==  Datenaustausch aktivieren

In diesem Bereich werden die Einstellungen zum Datenaustausch zwischen deinem plentymarkets System und dem Marktplatz Amazon beschrieben. Du erhältst Informationen zum Erzeugen eines Datenexports, der alle relevanten Informationen über Artikel und Warenbestände enthält. Außerdem importierst du Amazon-Aufträge automatisch über die XML-Schnittstelle oder manuell über eine CSV-Datei. Du erfährst zudem, wie du Versandbestätigungen an Amazon sendest, FBA-Bestände synchronisierst und Auftragsberichte von Amazon zurücksetzt.

[#1600]
===  Artikeldaten exportieren

Im Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Datenexport* können zwei Datenexporte erzeugt werden. Zum einen der Datenexport Seller Central, der alle relevanten Informationen über Artikel und Warenbestände enthält und anschließend direkt im Seller Central hochgeladen wird. Zum Anderen der Datenexport Marketplace, mit dem du Artikeldaten der BMVD-Kategorien für Amazon exportierst.

[#1700]
====  Datenexport Seller Central einrichten

Im Bereich *Seller Central* dieses Menüs erstellst du manuell einen Datenexport, der alle relevanten Informationen über Artikel und Warenbestände enthält und anschließend direkt im Amazon Seller Central hochgeladen wird. Gehe dazu wie im Folgenden beschrieben vor.

[IMPORTANT]
.Artikel in mehreren Kategorien anbieten
====
Wenn du Artikel in mehreren Kategorien anbietest, musst du nacheinander für die einzelnen Kataloge Exportdateien erzeugen.
====

[.instruction]
Datenexport Seller Central einrichten:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Datenexport*.
.  Nimm die Einstellungen im Bereich *Seller Central* vor. Beachte dazu die Erläuterungen in <<datenexport-seller-central>>.
.  Klicke auf *Datei laden*, um die Daten zu exportieren. +
→ Der Datenexport wird im CSV-Format ausgegeben.
.  Speichere die CSV-Datei zur weiteren Verwendung auf deinem Rechner.

[[datenexport-seller-central]]
.Datenexport Seller Central
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Amazon-Konto*
| Amazon-Konto wählen.

|*Export des Artikelkatalogs*
| Artikelkatalog für den Export wählen. Beim Artikelkatalogexport zu Amazon werden nur noch Artikel berücksichtigt, die jeweils in den vergangenen 24 Stunden geändert wurden. Bestände und Preise werden weiterhin wie gewohnt automatisiert abgeglichen.

|*Nur Artikel mit Markierung*
| Wählen, ob *alle Artikel*, *alle Artikel mit Markierung*, *alle Artikel ohne Markierung* oder Artikel mit einer bestimmten Markierung exportiert werden sollen.

|*Artikel*
| Artikelmenge wählen.

|*Datum (ab)*
| Datum eingeben. +
*Neu:* = Nur ab diesem Datum neu eingestellte Artikel werden exportiert. +
*Geändert:* = Geänderte oder aktualisierte Artikel werden exportiert.

|*Hersteller*
|*ALLE* oder einen bestimmten Hersteller wählen.
|====

[#1800]
====  Datenexport Marketplace einrichten

Im Bereich *Marketplace* dieses Menüs exportierst du Artikeldaten der BMVD-Kategorien zum Austausch mit Amazon. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Datenexport Marketplace einrichten:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Datenexport*.
.  Nimm die Einstellungen im Bereich *Marketplace* gemäß <<datenexport-marketplace>> vor.
.  Klicke auf *Datei laden*, um die Daten zu exportieren. +
→ Der Datenexport wird im CSV-Format ausgegeben.
.  Speichere die CSV-Datei zur weiteren Verwendung auf deinem Rechner.

[[datenexport-marketplace]]
.Datenexport Marketplace
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Amazon-Konto*
| Amazon-Konto wählen.

|*Genre*
| Eine der folgenden BMVD-Kategorien wählen: *Bücher*, *Musik*, *Video* oder *DVD*.

|*Nur Artikel mit Markierung*
| Wählen, ob *alle Artikel*, *alle Artikel mit Markierung*, *alle Artikel ohne Markierung* oder Artikel mit einer bestimmten Markierung exportiert werden sollen.

|*Aktion*
| Aktion für den Export wählen. +
*Artikel aktualisieren/hinzufügen* = Die in der CSV-Datei übermittelten Daten werden von Amazon hinzugefügt/aktualisiert. +
*Angebote entfernen* = Die in der CSV-Datei übermittelten Angebote werden von Amazon entfernt. +
*Daten vollständig aus dem System löschen* = Die in der CSV-Datei übermittelten Daten werden von Amazon vollständig gelöscht.

|*Lieferung*
| Versandart wählen.
|====

[NOTE]
.Lagerbestandsdatei im Seller Central hochladen
====
Beim Hochladen von BMVD-Produktdaten im Seller Central wählst du statt der Option *Textdateivorlagen für alle Kategorien außer BMVD* die Option *Lagerbestands-Assistent*.
====

[#1900]
===  Amazon-Aufträge importieren

Im Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Auftragsimport* richtest du den Import von Amazon-Aufträgen ein. Aufträge können sowohl automatisch über die XML-Schnittstelle als auch manuell über eine CSV-Datei importiert werden. Beide Varianten werden folgend beschrieben.

[#2000]
====  Aufträge automatisch importieren

Gehe wie im Folgenden beschrieben vor, um den automatischen Auftragsimport einzurichten.

[.instruction]
Automatischen Auftragsimport einrichten:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Auftragsimport*.
.  Wähle aus der Dropdown-Liste *Verfahren für Auftragsimport* die Option *XML-Schnittstelle abrufen*. +
→ Eine zweite Dropdown-Liste erscheint.
.  Wähle aus der Dropdown-Liste *Amazon-Account* das Konto.
.  Klicke auf *Vorschau*, um eine Vorschau des Imports anzuzeigen.

[#2100]
====  Aufträge manuell importieren

Gehe wie im Folgenden beschrieben vor, um den manuellen Import von Amazon-Aufträgen einzurichten.

[.instruction]
Manuellen Auftragsimport einrichten:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Auftragsimport*.
.  Wähle aus der Dropdown-Liste *Verfahren für Auftragsimport* die Option *CSV-Datei importieren*. +
→ Der Bereich *Einstellungen* wird geöffnet.
.  Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<auftragsimport-amazon>>.
.  Klicke auf *Vorschau*, um eine Vorschau des Imports anzuzeigen.

[[auftragsimport-amazon]]
.Auftragsimport des Marktplatzes Amazon
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Buche Zahlungseingang*
| Beim Auftragsimport automatisch den Zahlungseingang buchen.

|*Altes Format verwenden*
| Wenn noch das alte Amazon-Importformat verwendet wird, diese Option aktivieren.

|*Mandant*
| Mandanten für den Auftragsimport wählen.

|*Amazon-Account*
| Amazon-Konto wählen.

|*CSV-Datei*
| CSV-Datei für den Auftragsimport einstellen.
|====

[.instruction]
CSV-Datei für den Auftragsimport einstellen:

.  Klicke auf *Datei auswählen*.
.  Wähle die CSV-Datei für den Import.
.  Klicke auf *öffnen*.
.  Klicke dann auf *Vorschau*. +
→ Die verfügbaren Aufträge werden angezeigt.
.  Setze bei den Aufträgen, die importiert werden sollen, ein Häkchen bei der Option *Importieren*.
.  Klicke auf das *Zahnrad*, um den Import durchzuführen.

[TIP]
.Tipp: Importierte Aufträge
====
Sollten Aufträge von Amazon in dein System importiert werden, die du nicht mit plentymarkets eingestellt hast bzw. Aufträge, für die Artikel bisher nicht in plentymarkets angelegt sind, hast du die Möglichkeit, bei diesen Aufträgen manuell die Artikel zuzuordnen und den Status einzustellen.
====

[IMPORTANT]
.Fehlende Rechnungsanschrift
====
Wenn bei den von Amazon abgerufenen Aufträgen die Rechnungsanschrift fehlt, wende dich an den Amazon-Support. Die Einstellung muss von Amazon vorgenommen werden.
====

[TIP]
.Ursprüngliche Währung und Standardwährung sind unterschiedlich
====
Beim Auftragsimport wird zusätzlich die ursprüngliche Währung sowie der ursprüngliche Brutto- und Netto-Betrag an der Artikelposition gespeichert, wenn die Währung nicht die in plentymarkets eingestellte Standardwährung ist.
====

[#2200]
===  Versandbestätigungen an Amazon senden

Sobald der Amazon-Auftrag in deinem plentymarkets System bearbeitet und die Ware verschickt wurde, musst du Amazon über den neuen Status informieren, damit man dort die Umsätze deinem Konto gutschreiben kann. Auch diesen wichtigen Schritt erledigt dein plentymarkets System automatisch über die Schnittstelle.

Folgende Bedingungen müssen bei Aufträgen erfüllt sein, damit die Versandbestätigung automatisch an Amazon gemeldet wird:

*  Herkunft: Amazon oder eine Unterherkunft von Amazon
*  Statusbereich 7 (kleiner als 8)
*  Externe Auftragsnummer
*  Importierter Auftrag (nicht manuell angelegt)
*  Warenausgang gebucht (Uhrzeit darf nicht in der Zukunft liegen)

Sollte die automatische Übermittlung der Versandbestätigung, z.B. aufgrund von kurzfristig nicht erreichbaren Servern, nicht funktionieren oder sollten kurz vor einem Abrechnungsstichtag einzelne Aufträge manuell bestätigt werden, damit diese bei der nächsten Auszahlung berücksichtigt werden, kannst du die Versandbestätigung auch manuell an Amazon senden. Für Prime-Aufträge (Amazon_Prime, Amazon_Prime_SameDay, Amazon_Prime_NextDay und Amazon_Prime_SecondDay) wird keine Versandbestätigung an Amazon gesendet.
[.instruction]
Versandbestätigung manuell an Amazon senden:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Versandbestätigung*.
.  Wähle ein Amazon-Konto aus der Dropdown-Liste.
.  Gib ein Datum bei der Option *Datum Warenausgang* ein. +
→ Der gesamte Warenausgang des hier eingestellten Datums wird an Amazon übertragen.
.  Klicke auf *Versandbestätigung senden*.

[#2300]
===  Amazon-Auftragsberichte bearbeiten

Im Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Berichte* können Amazon-Bestellberichte zeitlich eingestellt und nachträglich zurückgesetzt werden.

[#2350]
====  Intervall für Auftragsberichte setzen

Im Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Berichte » Tab: Geplante Berichte* bestimmst du, in welchem Zeitraum Bestellberichte von Amazon erstellt werden. Beim automatischen Auftragsimport werden Aufträge aus diesen Berichten importiert. Daher empfehlen wir sowohl für die Erstellung von Berichten als auch für den Auftragsimport ein möglichst niedriges Intervall zu setzen. +
MFN-Bestellberichte erkennt man an ihrer Bezeichnung *GET ORDERS DATA*. +

Außerdem hast du in diesem Menü die Möglichkeit, Steuerberichte abzurufen und ein Intervall für den Abruf von FBA-Bestellberichten zu setzen. +

Setze unter *Tax reports* ein Intervall, um Steuerberichte für Amazon Business zu erstellen. Die Steuerberichte können dann in der Amazon Seller Central abgerufen werden. Wenn du in plentymarkets ein Intervall für die Erstellung von Steuerberichten setzt, musst du dazu keine weiteren Einstellungen in der Seller Central vornehmen. +

Wenn du Amazon FBA unter *System » Systemeinstellungen » Märkte » Amazon » Einstellungen » Tab: Auftragseinstellugen* aktiviert hast, werden FBA-Bestellberichte automatisch alle 4 Stunden abgerufen. Unter *FBA orders* kannst du optional ein Intervall setzen, in dem Bestellberichte zusätzlich abgerufen werden sollen.

[.instruction]
Intervall festlegen:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Berichte » Tab: Geplante Berichte*.
.  Wähle ein Amazon-Konto aus der Dropdown-Liste.
.  Wähle ein Intervall für die Erstellung von Auftragsberichten.
. *Speichere* die Einstellungen.

[#2360]
====  Auftragsberichte zurücksetzen

Im Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Berichte » Tab: MFN Berichte* setzt du die Auftragsberichte von Amazon eines bestimmten Datums zurück.

Wenn du die Auftragsberichte bzw. die Bestellberichte eines Tages zurücksetzt, werden diese Berichte für den Import erneut zur Verfügung gestellt. Bei einem erneuten Import werden nur die fehlenden Aufträge eines Tages eingelesen. Hierzu wird die Transaktionsnummer von Amazon abgeglichen. Ist bereits eine Transaktionsnummer vorhanden, wird der Auftrag nicht erneut importiert. So wird eine Doppelung beim Einlesen verhindert.

[.instruction]
MFN-Berichte zurücksetzen:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » Berichte » Tab: MFN Berichte*.
.  Wähle ein Amazon-Konto aus der Dropdown-Liste.
.  Wähle das Datum, für das Sie die MFN-Berichte zurücksetzen möchten.
. *Speichere* die Einstellungen.

[#2400]
===  Bestand abgleichen

Im Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » FBA-Warenbestand* hast du die Möglichkeit, neben dem stündlichen automatischen Bestandsabgleich mit Amazon deinen Bestand mit einer automatischen Aktion oder per CSV-Datei abzugleichen.

[IMPORTANT]
.Nur für Amazon Multi-Channel
====
Dieses Feature ist nur für <<Amazon Multi-Channel einrichten, Amazon Multi-Channel>> vorgesehen.
====

In plentymarkets wird zwischen einem automatischen Bestandsabgleich und einem manuellen Bestandsabgleich unterschieden. Beide Verfahren werden folgend beschrieben.

[#2500]
====  Bestand automatisch abgleichen

Gehe wie im Folgenden beschrieben vor, um einen automatischen Bestandsabgleich durchzuführen.

[.instruction]
Bestand automatisch abgleichen:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » FBA-Warenbestand*.
.  Wähle im Tab *Automatisch* das Amazon-Konto.
.  Klicke auf *Amazon FBA-Bestand synchronisieren*.

Für den Prozess ist eine Zeitspanne von 4 Minuten vorgesehen. Werden die Daten nicht innerhalb dieser Zeitspanne von Amazon zur Verfügung gestellt, dann werden die Bestände nicht abgeglichen. Bei der nächsten Anforderung werden dann die vorher nicht übertragenen Daten verwendet, was zu Fehlern führen kann. Daher ist ein manueller Abgleich per CSV-Datei zu empfehlen wie im folgenden Kapitel beschrieben.

Es werden nur Bestände von Artikeln übernommen, die in den letzten 30 Tagen eine Bestandsänderung auf Amazon erfahren haben. Für den Erstimport empfehlen wir dir den manuellen Abgleich. Die Warenbestände werden gemäß der <<Basiseinstellungen vornehmen, Grundeinstellungen>> abgeglichen.

[#2600]
====  Bestand manuell abgleichen

Bestände werden manuell per CSV-Datei abgeglichen.

[IMPORTANT]
.SKU-Zuordnung
====
Für den manuellen Bestandsabgleich muss die SKU-Zuordnung in den <<Basiseinstellungen vornehmen, Grundeinstellungen>> eingetragen werden.
====

Bevor du diesen Abgleich durchführst, musst du bei Amazon in der Seller Central die entsprechende Berichtsdatei anfordern, herunterladen und die CSV-Datei auf deinem Rechner speichern.

[.instruction]
Bestand manuell abgleichen:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Datenaustausch » FBA Warenbestand*.
.  Wechsele in das Tab *Manuell*.
.  Wähle das Amazon-Konto.
.  Klicke auf *Datei auswählen*, um die soeben gespeicherte CSV-Datei zu wählen.
. *Speichere* die Einstellungen, um den Abgleich durchzuführen.

[#2700]
==  Amazon-Aufträge abrufen

Wenn du bereits mit einem anderen Shopsystem gearbeitet hast, weißt du bestimmt sehr genau, wie zeitaufwändig die tägliche Auftragsbearbeitung im Seller Central-Portal sein kann. Mit plentymarkets wird alles erheblich vereinfacht, denn hier werden alle Aufträge aus allen angeschlossenen Märkten in einem einzigen Auftragsordner für dich gesammelt. Aus Amazon-Aufträgen werden automatisch plentymarkets Aufträge, die du nach dem gewohnten Fulfillment-Schema schnell und effektiv bearbeiten kannst. Nicht einmal um den Import der Aufträge musst du dich noch kümmern, das macht die Schnittstelle für dich im Hintergrund. Damit alles korrekt funktioniert, sind ein paar Voraussetzungen bzw. Einstellungen nötig, die hier zusammengefasst sind.

Aufträge werden im Viertelstundentakt abgerufen. Dennoch kann es unter Umständen bis zu 90 Minuten dauern, bis ein in Amazon generierter Auftrag in deinem plentymarkets System angezeigt wird. Das ist keine Fehlfunktion, sondern aus technischen Gründen nicht anders möglich. Meistens wirst du zuvor durch eine E-Mail von Amazon über den Verkauf informiert und kannst den Auftrag im Seller Central bereits ansehen.

[#2800]
===  Einstellungen der Schnittstelle in plentymarkets vornehmen

Für den Import der Aufträge sind die Einstellungen *Zahlungseingang* sowie *Versandbestätigung* in den Grundeinstellungen relevant. Wir gehen davon aus, dass du Aufträge mit dem Status *[5] Freigabe Versand* übernehmen und die stündliche Versandbestätigung automatisch von deinem plentymarkets System erzeugen lässt. Kontrolliere diese Einstellungen nochmals.

Für den manuellen und automatischen Auftragsimport beachte das Kapitel <<FBA-Auftragsimport, FBA-Auftragsimport>>.

[IMPORTANT]
.Retouren von Amazon-Aufträgen bearbeiten
====
Natürlich musst du auch bei Amazon gelegentlich mit einem Widerruf nach erfolgter Auslieferung rechnen. Die Artikel muss der Kunde direkt an dich zurücksenden. Wie du in plentymarkets eine Retoure anlegst und den Warenausgang wieder zurücksetzt, erfährst du auf der Handbuchseite <<warenwirtschaft/waren-ausbuchen#, Waren ausbuchen>>.
====

[.subhead]
MFN: Rückbuchung manuell über Seller Central erledigen

Da Amazon für dich die Zahlung des Kunden in Empfang genommen hat, muss die Rückbuchung ebenfalls über Amazon erfolgen. Das musst du im Auftragsordner in der Seller Central erledigen.

[IMPORTANT]
.Rückbuchung manuell oder per Ereignisaktion ausführen
====
Die Erstattung des Kaufpreises durch Amazon wird nicht automatisch über die Schnittstelle angestoßen, sondern muss manuell oder über eine Ereignisaktion automatisch ausgeführt werden. Wenn du die manuelle Erstattung oder das Erstellen einer Ereignisaktion zum Erstatten des Kaufpreises vergisst, riskierst du eine Kundenbeschwerde bei Amazon und eine schlechte Bewertung.
====

MFN Retouren (=Händlerversand) kannst du in Form von Gutschriften per Ereignisaktion an Amazon melden. Nur mit Hilfe eines Auftrags vom Typ Gutschrift kann die Rückzahlung der Artikelsumme und den Versandkosten garantiert werden. Gehe dazu wie im Folgenden beschrieben vor.

[.subhead]
Auftragsstatus anlegen

Lege zunächst einen Auftragsstatus für Amazon-Retouren im Menü <<auftraege/auftraege-verwalten#1200, System » Systemeinstellungen » Aufträge » Status>> an, z.B. [9.6] Retoure an Amazon gesendet. Diesen Auftragsstatus benötigst du für die Amazon-Einstellungen.

[.subhead]
Auftragsstatus einstellen

Stelle diesen Auftragsstatus nun in den Amazon-Einstellungen ein wie folgend beschrieben.

[.instruction]
Auftragsstatus für Retoure einstellen:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen*.
.  Öffne das Amazon-Konto.
.  Wechsele in das Tab *Auftragseinstellungen*.
.  Wähle für die Option *Status für übertragene Retouren* den eben eingerichteten Auftragsstatus für Amazon-Retouren.
. *Speichere* die Einstellungen.

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Retouren in Form von Gutschriften automatisch an Amazon zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß <<ereignisaktion-automatische-retoure>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
.  Nimm die weiteren Einstellungen gemäß <<ereignisaktion-automatische-retoure>> vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[TIP]
.Ereignisaktion und Gutschriftenimport
====
Nutze Ereignisaktionen, um Erstattungen aus plentymarkets auszulösen. Der automatische Gutschriftenimport (Option "Gutschriftenimport" in den Auftragseinstellungen) stellt sicher, dass eine Gutschrift nicht zweimal im System existiert. Wenn du aktuell Gutschriften noch manuell oder durch ein Drittsystem auslöst und keine Gutschriften in plentymarkets existieren, wird eine Gutschrift durch den Import angelegt.
====

[[ereignisaktion-automatische-retoure]]
.Ereignisaktion zum automatischen Senden von Retouren an Amazon
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Gutschrift*
|

|*Filter*
|*Auftrag &gt; Herkunft*
|*Amazon* oder die passende Amazon-Unterherkunft, z.B. Amazon France

|*Aktion*
|*Retoure &gt; Retoure bei Amazon anlegen*
|
|====

[IMPORTANT]
.Filter Amazon-Herkunft
====
Wähle für den Filter *Auftrag » Herkunft* keine Amazon FBA-Herkunft, wie z.B. Amazon FBA Germany, wenn du den automatischen Gutschriftenimport nutzt.
====

[#3100]
=== Ausstehende Amazon-Aufträge importieren

Ausstehende Amazon-Aufträge werden in Status *[1] Unvollständige Daten* in dein plentymarkets System importiert und verbleiben in diesem Status bis Amazon den Auftrag freigibt. Bis zur Freigabe werden weder die Rechnungs-/Lieferadresse noch Artikelpreise am Auftrag hinterlegt. Nach der Freigabe durch Amazon wird der Auftrag aktualisiert und die dazugehörigen Adressen und Preise werden hinterlegt. Die Warenbestandsautomatik entscheidet, in welchen Status der Auftrag rutscht.

Falls Amazon den Auftrag nicht freigibt, wird der Auftrag nicht aktualisiert, sondern automatisch in Status *[8] Storniert* verschoben.

[#3110]
==== Warenbestand für ausstehende Aufträge reservieren

Es gibt zwei Möglichkeiten, den Warenbestand für ausstehende Aufträge in plentymarkets zu reservieren. Entweder mit Hilfe einer Ereignisaktion oder direkt in den Auftragsgrundeinstellungen.
Mit der Ereignisaktion wird der Auftrag von Status 1 in einen Status verschoben, bei dem Warenbestand reserviert wird.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß <<ereignisaktion-auftragsstatus-aktualisieren>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
.  Nimm die weiteren Einstellungen gemäß <<ereignisaktion-auftragsstatus-aktualisieren>> vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-auftragsstatus-aktualisieren]]
.Ereignisaktion zum automatischen Aktualisieren von Auftragsstatus
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Neuer unvollständiger Auftrag*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Amazon-Herkünfte*

|*Aktion*
|*Auftrag &gt; Status ändern*
|*Status wählen, in dem der Bestand reserviert wird.*
|====

In den Auftragsgrundeinstellungen wird über die Einstellung *Status Auftragsreservierung* definiert, in welchen Auftragsstatus Warenbestände reserviert werden.

[.instruction]
Auftragsstatus für Warenbestandsreservierung festlegen:

.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Einstellungen*.
.  Wähle bei der Einstellung *Status Auftragsreservierung* die Status, damit für Aufträge, die in diesen Status kommen, Bestand reserviert wird.
. *Speichere* die Einstellungen.

[#3150]
== Amazon VCS in plentymarkets aktivieren

[IMPORTANT]
.Amazon VCS auf Amazon aktivieren
====
Aktiviere Amazon VCS zuerst in der Amazon Seller Central, bevor du den Service in deinem plentymarkets System aktivierst.
====

Amazon VCS (= VAT Calculation Service) ist ein von Amazon angebotener Umsatzsteuerservice, mit dem Amazon die Umsatzsteuer berechnet. Du entscheidest, ob die Amazon-Rechnungen von Amazon oder plentymarkets erzeugt werden sollen. Wenn du Amazon-Rechnungen von plentymarkets erstellen lässt, werden die Rechnungen automatisch zu Amazon übertragen. Aktiviere Amazon VCS im Menü *System » Systemeinstellungen » Märkte » Amazon » Amazon-Konto wählen » Tab: Einstellungen* im Bereich *Basiseinstellungen* in plentymarkets.

[IMPORTANT]
.Rechnungserstellung nicht mehr anders möglich
====
Beachte unbedingt, dass Amazon-Rechnungen nicht mehr anders erstellt werden können (d.h. nicht manuell oder durch eine Ereignisaktion), sobald du die Optionen *VCS plentymarkets* oder *VCS Amazon* aktivierst.
====

[TIP]
.Best Practice zum Thema Amazon VCS
====
Beachte auch die <<maerkte/amazon/best-practices-amazon-vcs#, Best Practice-Seite zum Thema VCS>>. Dort findest du weitere hilfreiche Informationen zur Einrichtung des Amazon-Rechnungsservices VCS in plentymarkets.
====

[.instruction]
Rechnungsservice Amazon VCS in plentymarkets aktivieren:

1. Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Amazon-Konto wählen » Tab: Einstellungen*. +
→ *Wichtig:* Du musst den Rechnungsservice zuerst bei Amazon in der Seller Central aktivieren, bevor du die Einstellungen in plentymarkets vornimmst.
2. Wähle eine Option für die Einstellung *Rechnung erzeugen*. Beachte dazu die Erläuterungen in <<amazon-vcs>>.
3. *Speichere* die Einstellungen.

[[amazon-vcs]]
.Optionen für die Rechnungserstellung bei Amazon VCS
[cols="1,3"]
|====
|Option |Erläuterung

|*plentymarkets*
|Rechnungen werden von plentymarkets erzeugt. +
*Wichtig:* Diese Option nur wählen, wenn Amazon VCS nicht genutzt wird.

|*VCS plentymarkets*
|*Voraussetzung:* Amazon VCS wird genutzt. +
Amazon-Rechnungen werden automatisch von plentymarkets erzeugt und zu Amazon übertragen. +
*Wichtig:* Wenn du diese Option aktivierst, können Amazon-Rechnungen *nicht mehr* manuell oder durch Ereignisaktionen erstellt werden.

|*VCS Amazon*
|*Voraussetzung:* Amazon VCS wird genutzt. +
Amazon-Rechnungen werden von Amazon erzeugt. +
*Wichtig:* Wenn du diese Option aktivierst, können Amazon-Rechnungen *nicht mehr* manuell oder durch Ereignisaktionen erstellt werden.
|====

[#3200]
==  Amazon-Geschenkservice nutzen

Mit der Aktivierung des Amazon-Geschenkservices können Ihre Kunden optional während des Bestellprozesses auf Amazon einen Geschenkpapierservice nutzen und ggf. eine Grußbotschaft eingeben. Diese Optionen werden beim automatischen Auftragsabruf übernommen, ohne dass weitere Einstellungen erforderlich sind. Für jede Auftragsposition mit Geschenkoption wird eine zusätzliche Auftragsposition mit der ID *-2* und Informationen direkt hinter dem bestellten Artikel angefügt. Dazu gehören die Verpackungsart sowie ggf. eine Grußbotschaft.

Aktiviere die Geschenkoptionen in der Amazon Seller Central, um den Geschenkservice zu nutzen.

[TIP]
.Tipp: Mehrere Verpackungsarten und Aufpreise
====
Du kannst mehrere Verpackungsarten hinzufügen und Aufpreise definieren.
====

[#3300]
==  FBA-Service von Amazon nutzen

Das Kürzel FBA steht für Fulfillment by Amazon. Statt die Aufträge selbst zu bearbeiten, die Ware zu verpacken und zu versenden, überlassen Sie beim FBA-Programm Amazon diese Aufgabe. Natürlich müssen Sie zumindest einen Teil Ihrer Waren dann auch bei Amazon einlagern.

[#3400]
===  Lager für Amazon FBA anlegen

Im Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen* im Tab *Auftragseinstellungen* stellst du unter *Lager* u.a. ein, welches Lager für Amazon Fulfillment-Aufträge verwendet werden soll, damit die komplette Funktionalität der Warenwirtschaft auch beim FBA-Programm erhalten bleibt und du die Lagerbestände bei Amazon über dein plentymarkets System im Blick behältst.

[.instruction]
Lager anlegen:

.  Öffne das Menü *System » Systemeinstellungen » Waren » Lager*.
.  Klicke auf *Neues Lager*.
.  Gib einen Namen für das Lager ein.
.  Wähle einen *Lagertyp*.
.  Wähle als *Logistiktyp* die Option *Amazon*.
. *Speichere* die Einstellungen, um das Lager anzulegen. +
→ Das Lager wird alphabetisch sortiert unter Lager angezeigt und geöffnet.
.  Nimm die weiteren Einstellungen gemäß der Erläuterungen auf der Handbuchseite <<warenwirtschaft/lager-einrichten#, Lager einrichten>> vor.
. *Speichere* die Einstellungen.

Ob die mit dem FBA-Service verbundenen Vorteile oder die Nachteile für deine persönliche Situation als Online-Händler überwiegen, kannst du nur selbst einschätzen. Wir möchten hier nur auf einige wichtige Punkte hinweisen:

*  Amazon bearbeitet Aufträge schnell und zuverlässig. Spitzenzeiten vor Weihnachten sind für den Shopbetreiber genauso problemlos wie das Sommerloch während der Urlaubszeit.
*  Dein Listing auf dem Marktplatz verbessert sich, d.h. du kannst mit höheren Verkaufszahlen rechnen.
*  Der FBA-Service ist mit Kosten verbunden, d.h. deine Brutto-Marge sinkt. Für einen umfassenden Vergleich der Kosten bedenke jedoch, dass im FBA-Service der Aufwand für die Lagerhaltung, das Auftragshandling, den Kundenservice etc. enthalten ist und du so von diesem Aufwand entlastet wirst.
*  Ware, die bei Amazon gelagert ist, kann in erster Linie auch nur dort angeboten werden. Für andere Marktplätze benötigst du gesonderte Warenbestände. Mit dem Service Multi-Channel-Fulfillment stellt Amazon jedoch auch eine Variante zur Verfügung, die deine Möglichkeiten diesbezüglich erweitert.
*  Du hast deutlich weniger Ärger mit nicht zustellbaren Sendungen oder verzögerten Auslieferungen. Pakete mit Amazon-Logo werden in der Regel bevorzugt behandelt.

[#3500]
===  FBA-Auftragsimport

Gehe wie im Folgenden beschrieben vor, um einzustellen, dass deine FBA-Aufträge täglich automatisch in dein plentymarkets System importiert werden.

[.instruction]
FBA-Aufträge automatisch importieren:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen*.
. Wähle das Konto.
. Wechsele in das Tab *Auftragseinstellungen*.
. Setze im Bereich *Amazon FBA* ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.

Die Auftragsbearbeitung hat folgenden Ablauf:

*  Der Kunde kauft bei Amazon.
*  Amazon verschickt die Ware.
*  Das plentymarkets System fordert einen Bericht an.
*  Amazon erstellt den Bericht.
*  Am nächsten Tag prüft plentymarkets automatisch, ob Berichte bei Amazon vorliegen. Wenn ja, werden die Berichte importiert.
*  Aus den Berichten werden in plentymarkets Aufträge erzeugt.

[IMPORTANT]
.Hinweis zum Auftragsimport
====
Amazon generiert die Berichte nur einmal täglich. Da Artikel nach bis zu 2 Tagen versendet werden, sind die FBA-Aufträge erst mit einer zeitlichen Verzögerung in deinem System verfügbar. Die von Amazon generierte Auftragsbestätigung ist in der Regel zwei Tage nach Versand der Ware, also insgesamt bis zu 4 Tage nach Bestellung der Ware durch den Käufer, in deinem System verfügbar. Die Lieferpünktlichkeit wird davon jedoch nicht berührt und erfolgt in der von Amazon gewohnten Schnelligkeit.
====

Amazon FBA-Aufträge werden mit den Parametern *Status* und *Herkunft* importiert. Für die Option *Status* legst du den für deinen Prozess passenden Status fest, also zum Beispiel *[7] Warenausgang gebucht*. Die Herkunft wird automatisch auf Amazon FBA oder eine Amazon FBA-Unterherkunft, wie z.B. Amazon FBA USA, gesetzt. Der Warenausgang wird hier in plentymarkets direkt gebucht, so dass keine Reservierung des Bestands der enthaltenen Artikelpositionen stattfindet.

[TIP]
.Ereignisaktionen für Fulfillment
====
Lege die für den Fulfillment-Prozess nötigen Ereignisaktionen an, um eine Rechnung zu erzeugen und per E-Mail automatisch an den Käufer zu senden sowie den Auftrag dann in einen weiteren Status zu setzen. +
Beachte dazu die Handbuchseiten *<<automatisierung/ereignisaktionen#, Ereignisaktionen>>* sowie *<<fulfillment#, Standard-Fulfillment im Detail>>*.
====

[.subhead]
FBA-Teillieferungen

Amazon FBA-Teillieferungen werden von Amazon veranlasst, wenn sich die von Amazon im Kundenauftrag versendete Ware in unterschiedlichen Amazon-Lagern befindet.
Bei den Kunden kommen nach Bestellung demzufolge mehrere Pakete zu einem getätigten Auftrag an. +
In plentymarkets wird jede FBA-Teillieferung anhand des versendenden FBA-Lagers als separater Auftrag im System angelegt. Pro Teillieferung kann eine Sendungsnummer von Amazon importiert und der jeweiligen Teillieferung zugeordnet werden. Pro Teillieferung kann eine separate Rechnung erzeugt werden, was aufgrund der unterschiedlichen zu berechnenden Steuern erforderlich ist, wenn die Amazon-Lager in unterschiedlichen Ländern liegen.

[.subhead]
Europäisches Versandnetzwerk

Amazon erweitert kontinuierlich das europäische Versandnetzwerk für Händler, die Versand durch Amazon nutzen. Eine Voraussetzung ist, dass du in allen Ländern, in denen du FBA-Logistikzentren nutzt, steuerrechtlich registriert sind. Damit für diese neuen Logistikzentren deine Rechnungen auch steuerlich korrekt erstellt werden, kannst du neben deinem Firmensitz im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung* den Lagerstandort als Basis für den Standard-Umsatzsteuersatz wählen und das individuell für jeden deiner Mandanten (Shops). Im gleichen Menü im Tab *Umsatzsteuersätze* erfässt du auch die notwendigen Steuersätze für die Länder.

[TIP]
.Beispiel: Logistikzentrum in Polen mit Versand nach Deutschland
====
Damit für Aufträge, die von einem Logistikzentrum in Polen nach Deutschland verschickt werden, nicht der polnische Steuersatz verwendet wird, muss für den Standort Polen zusätzlich das Land Deutschland mit dem deutschen Steuersatz eingetragen werden. Wähle dafür im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Polen » Buchhaltung » Tab: Umsatzsteuersätze* das Land *Deutschland* und trage den deutschen Steuersatz sowie die gültige USt-IdNr. ein.
====

[#3600]
===  FBA-Retouren automatisch importieren

Im Retourenfall sendet der Käufer die Ware zurück an Amazon. Die Retoure wird in dein plentymarkets System importiert und mit dem Retourenstatus, den du im Menü <<auftraege/grundeinstellungen#200, System » Systemeinstellungen » Aufträge » Einstellungen>> gewählt hast, im Auftragsmenü angelegt.

[IMPORTANT]
.Auftrag nicht ändern
====
Retouren werden nur importiert, wenn der Auftrag mit unveränderter externer Auftragsnummer in plentymarkets vorliegt.
====

Aktiviere wie im Folgenden beschrieben die Importfunktion, um FBA-Retouren automatisch in dein plentymarkets System zu importieren.

[.instruction]
Importfunktion für FBA-Retouren aktivieren:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen*.
.  Öffne das Amazon-Konto.
.  Wechsele in das Tab *Auftragseinstellungen*.
.  Wähle im Bereich *Versand durch Amazon (FBA)* für die Option *Retourenimport* die Einstellung *Täglich*.
. *Speichere* die Einstellungen.

[#3650]
===  FBA-Gutschriften automatisch importieren

Nutze den Gutschriftenimport, um FBA-Gutschriften automatisch in dein plentymarkets System zu importieren. Die Gutschriften werden mit dem Status importiert, der unter *System » Systemeinstellungen » Aufträge » Einstellungen* für die Einstellung *Standard-Status Gutschrift* gewählt wurde. Wenn der Gutschriftenimport aktiviert ist, werden FBA-Gutschriften alle 4 Stunden importiert.

[IMPORTANT]
.FBA-Retouren nicht per Ereignisaktion als Gutschriften anlegen
====
Wenn du den Gutschriftenimport aktivierst, werden FBA-Gutschriften automatisch alle 4 Stunden in dein plentymarkets System importiert. Verwende deshalb in diesem Fall keine Ereignisaktion, um FBA-Retouren als Auftragstyp *Gutschrift* anzulegen.
====

[.instruction]
Automatischen Gutschriftenimport aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen*.
. Öffne das Amazon-Konto.
. Wechsele in das Tab *Auftragseinstellungen*.
. Wähle *Ja* für die Option *Gutschriftenimport*.
. *Speichere* die Einstellungen.

[#3700]
==  Amazon Multi-Channel einrichten

Amazon Multi-Channel bedeutet, dass "Lieferungen im Auftrag des Verkäufers durch Amazon verschickt werden, für Bestellungen, die nicht bei Amazon.de aufgegeben wurden, sondern z.B. auf eBay oder auf der persönlichen Website eines Verkäufers." (Quelle: Amazon)

Die Multi-Channel-Funktion ermöglicht Ihnen also, Artikel bei Amazon zu lagern und von Amazon verschicken zu lassen, die du nicht bei Amazon, sondern auf anderen externen Marktplätzen verkaufst. Du erfährst in diesem Kapitel, welche Einstellungen du in deinem plentymarkets System vornehmen musst, damit diese Aufträge über Amazon abgewickelt werden können.

Die folgenden Schritte sind nötig, um deine Bestandsverwaltung und Artikeldaten für Amazon Multi-Channel einzurichten.

[#3800]
===  Lager für Amazon Multi-Channel anlegen

Lege ein Lager an, falls du noch kein Lager wie im Kapitel <<FBA-Service von Amazon nutzen, FBA-Service von Amazon nutzen>> beschrieben angelegt hast. Wichtig beim Multi-Channel-Versand ist, dass du für jeden landesspezifischen Amazon-Markt ein eigenes Lager mit dem Logistiktyp *Amazon* und das Land als Standort in plentymarkets eingerichtet hast.

[IMPORTANT]
.Beispiel für die übereinstimmung von Amazon-Plattform und Lagerstandort
====
Beim Multi-Channel-Versand über amazon.co.uk muss ein eigenes Lager Amazon UK mit dem Logistiktyp *Amazon* und dem Standort Großbritannien angelegt werden. Die Ware muss also auch tatsächlich vor Ort bei Amazon z.B. in Großbritannien gelagert sein, da sonst keine Versandabwicklung über amazon.co.uk stattfinden kann.
====

[#3900]
===  Artikelverfügbarkeit für Amazon Multi-Channel einstellen

Nimm die im Folgenden beschriebenen Einstellungen an den Artikeln vor, die du für Amazon Multi-Channel verfügbar machen möchtest.

[.instruction]
Artikelverfügbarkeit für Amazon Multi-Channel einstellen:

.  Öffne das Menü *Artikel » Artikel bearbeiten*.
.  Öffne den Artikel.
.  Wechsele in das Tab *Multi-Channel*.
.  Nimm die Einstellungen im Bereich *Amazon* vor. Beachte dazu die Erläuterungen in Tabelle 5 im Kapitel <<maerkte/amazon/amazon-einrichten#700, Artikelverfügbarkeit einstellen>>.
. *Speichere* die Einstellungen.

[#4000]
===  Einstellungen für Amazon Multi-Channel vornehmen

Nimm die im Folgenden beschriebenen Einstellungen im Menü für Amazon vor.

[.instruction]
Amazon Multi-Channel einrichten:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen*.
.  Wechsele in das Tab *Auftragseinstellungen*.
.  Nimm die Einstellungen im Bereich *Versand durch Amazon (FBA)* vor. Beachte dazu die Erläuterungen in <<amazon-multi-channel>>.
. *Speichere* die Einstellungen.

[[amazon-multi-channel]]
.Amazon Multi-Channel einrichten
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Aktiv*
| Häkchen setzen, um den täglichen Auftragsimport zu aktivieren.

|*Herkunft*
|*Nur für Aufträge von Amazon verwenden* = Nur Aufträge von Amazon mit FBA abwickeln. +
*Für alle Aufträge verwendbar* = Alle Aufträge mit FBA abwickeln.

|*Status*
|<<auftraege/auftraege-verwalten#1200, Status>> der Aufträge wählen, die von Amazon importiert wurden.

|*Lager*
| Wählen, welches <<Lager für Amazon FBA anlegen, Lager>> für den Versand durch Amazon verwendet werden soll.

|*Warenausgang*
| Wählen, ob der Warenausgang als gebucht markiert werden soll oder nicht. Die Option *Als gebucht markieren* erzeugt keine Warenbewegung. Um eine Warenbewegung zu erzeugen, muss die Option *Nicht als gebucht markieren* eingestellt sein und eine Ereignisaktion eingerichtet werden.

|*Retourenimport*
|Wählen, ob Retouren *Nie* oder *Täglich* importiert werden sollen.

|*Gutschein bei Retouren berücksichtigen*
|Wählen, ob Gutscheine bei FBA-Retouren berücksichtigt werden sollen oder nicht. Wurde der FBA-Auftrag komplett oder teilweise mit einem Gutschein beglichen, wird der Gutschein bei der Retoure hinzugefügt und verrechnet. Dabei wird kein Mindestbestellwert für den Gutschein berücksichtigt.

|*Bestandsimport*
| Option *Stündlich* wählen, damit der Bestand importiert wird. +
Dabei werden nur Änderungen der Bestandsdaten berücksichtigt. Weitere Möglichkeiten zum Bestandsimport sind in Kapitel <<Bestand abgleichen, Bestand abgleichen>> beschrieben.

|*Status für übertragene Aufträge*
| Bestimmt den Auftragsstatus für Multi-Channel FBA Aufträge, die erfolgreich an FBA übertragen wurden.

|*Artikelpakete Multichannel*
| Wählen, welche Positionen an Amazon übertragen werden sollen. +
*Alle Auftragspositionen übertragen* = Alle Positionen, die sich im Auftrag befinden, an Amazon übertragen. Wenn diese Option gewählt wird, werden die Paketposition und die Paketbestandteile an Amazon übertragen. +
*Nur Paketposition übertragen* = Nur die Paketposition wird an Amazon übertragen. +
*Ohne Paketposition übertragen* = Nur die Paketbestandteile werden an Amazon übertragen.

|*Versandkategorie*
| Versandkategorie wählen. +
*Standard* = Normaler Versand +
*Expedited* = Schnellversand +
*Priority* = Bevorzugt (schnellster Versand)
|====

[#4100]
===  FBA-Versandfreigabe automatisch erteilen

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, damit Amazon automatisch eine Meldung über den Auftrag erhält und den Auftrag bearbeiten sowie den Versand veranlassen kann.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß <<ereignisaktion-fba-versandfreigabe>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
.  Nimm die weiteren Einstellungen gemäß <<ereignisaktion-fba-versandfreigabe>> vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-fba-versandfreigabe]]
.Ereignisaktion zum automatischen Erteilen von FBA-Versandfreigaben an Amazon
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel &gt; [5] Freigabe Versand*
|

|*Filter 1*
|*Auftrag &gt; Auftragslager*
|*Amazon Multi-Channel*

|*Filter 2*
|*Versand &gt; Versand ausschließlich durch FBA*
|

|*Filter 3*
|*Auftrag &gt; Herkunft*
|*Wichtig:* Keine Amazon-Herkunft wählen, da es sonst zu Doppelungen bei FBA-Aufträgen kommen kann.

|*Aktion*
|*Versand &gt; FBA-Versandfreigabe erteilen*
|
|====

Bei Wechsel in Status 5 wird Amazon mit der Ereignisaktion darüber informiert, dass die Ware zum Versand freigegeben ist. Amazon verschickt die Ware und das plentymarkets System erhält intern eine Bestätigung von Amazon. Der Auftrag wechselt in Status 5.1, wie in den <<Auftragseinstellungen vornehmen, Auftragseinstellungen>> festgelegt. Die Paketnummer wird in dein plentymarkets System importiert.

[TIP]
.Import von Paketnummern
====
Paketnummern werden einmal täglich importiert.
====

[#4200]
==  Amazon Prime-Aufträge bearbeiten

Mit Hilfe von Filtern in den Bereichen Auftragssuche und Ereignisaktionen werden Aufträge mit den Versandbedingungen von Amazon Prime gesondert in plentymarkets behandelt. Versandlabel für Amazon Prime-Aufträge werden über die Amazon Merchant Fulfillment API generiert.

[IMPORTANT]
.Pflichtfelder für die Anmeldung von Amazon Prime-Aufträgen
====
Damit Amazon Prime-Aufträge bearbeitet werden können, müssen bestimmte Informationen im Menü *System » Systemeinstellungen » Aufträge » Versand » Dienstleister » Einstellungen* hinterlegt sein. Amazon definiert folgende Pflichtfelder: *Firma*, *Straße*, *Hausnummer*, *PLZ*, *Ort*, *Land*, *Telefon* und *E-Mail*. Diese Pflichtfelder müssen gefüllt sein, damit die Anmeldung Ihrer Amazon Prime-Aufträge ausgeführt werden kann.
====

[#4300]
===  Amazon Prime-Aufträge filtern

Im Menü <<auftraege/auftraege-verwalten#, Aufträge » Aufträge bearbeiten>> werden alle deine Aufträge angezeigt. Diese Aufträge kannst du über <<auftraege/auftraege-verwalten#1300, Filter>> eingrenzen und z.B. nur Amazon Prime-Aufträge anzeigen lassen.

Innerhalb des Filters *Amazon* stehen dir zehn Optionen zur Auswahl:

* *ALLE* filtert alle Amazon-Aufträge.
* *Prime* filtert alle Amazon Prime-Aufträge, außer Prime SameDay, Prime NextDay und Prime SecondDay.
* *Prime (alle)* filtert alle Amazon Prime-Aufträge, auch Prime SameDay, Prime NextDay und Prime SecondDay.
* *Nein* Amazon Prime-Aufträge werden nicht berücksichtigt.
* *Prime SameDay* nur Prime SameDay-Aufträge werden in der Auftragsübersicht gelistet.
* *Prime NextDay* nur Prime NextDay-Aufträge werden in der Auftragsübersicht gelistet.
* *Prime SecondDay* nur Prime SecondDay-Aufträge werden in der Auftragsübersicht gelistet.
* *SameDay* Amazon-Aufträge werden in der Auftragsübersicht gelistet, die nicht zu Amazon-Prime gehören, aber bei denen der Versand dennoch am gleichen Tag erfolgen muss.
* *NextDay* Amazon-Aufträge werden in der Auftragsübersicht gelistet, die nicht zu Amazon-Prime gehören, aber bei denen der Versand dennoch am nächsten Tag erfolgen muss.
* *SecondDay* Amazon-Aufträge werden in der Auftragsübersicht gelistet, die nicht zu Amazon-Prime gehören, aber bei denen der Versand dennoch am übernächsten Tag erfolgen muss.

[#4400]
===  Versandlabel für Amazon Prime-Aufträge generieren

Amazon schreibt vor, dass du Versandlabels für Amazon Prime-Aufträge über die Amazon Merchant Fulfillment API generierst. Dafür stellt Amazon Versanddienstleister mit vergünstigten Konditionen zur Verfügung. Im Folgenden wird beschrieben, wie du zunächst die Versandprofile mit Amazon Prime verknüpfst.

[.instruction]
Versandprofile mit Amazon Prime verknüpfen:

.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
.  Wähle das Versandprofil, das du mit Amazon Prime verknüpfen willst.
.  Wähle den Filter *Amazon Prime* im Bereich *Treueprogramm*.
.  Wechsele in das Tab *Portotabelle*.
.  Wähle bei der Option *Amazon Prime Service* im Bereich *Amazon Prime* die Versandart.
. *Speichere* die Einstellungen.

[TIP]
.Tipp: Versandpaket beachten
====
Beachte das am Versandprofil gespeicherte Versandpaket, damit keine überteuerten Labels generiert werden.
====

Anschließend meldest du im Menü *Aufträge » Versand-Center » Tab: Anmelden* deine Amazon Prime-Aufträge bei dem von dir gewählten Amazon-Versanddienstleister an. Voraussetzung für die Anmeldung ist, dass du zuvor im Tab *Suche* Amazon Prime-Aufträge gesucht hast, die jetzt hier angezeigt werden.

[TIP]
.Tipp: Versanddienstleister beachten
====
Beachte, dass der passende Versanddienstleister eingestellt ist, da sonst die korrekten Amazon Services in den Portotabellen nicht eingestellt werden können.
====

[.instruction]
Amazon Prime-Aufträge anmelden:

.  Öffne das Menü *Aufträge » Versand-Center » Tab: Suchen*.
.  Suche den Amazon Prime-Auftrag, den du anmelden willst.
.  Wechsele in das Tab *Anmelden*.
.  Wähle aus der Dropdown-Liste *Versanddienstleister* die Option *Amazon Prime*.
.  Klicke auf *Anmelden*.
.  Öffne den Auftrag. +
→ Nach erfolgreicher Anmeldung erscheint im Bereich *Übersicht* ein PDF-Symbol, über das du das Versandlabel herunterladen kannst.

[#4500]
==  Zahlungsart Amazon aktivieren

Die Zahlungsart *Amazon* ist für Aufträge, die über den Marktplatz Amazon in dein plentymarkets System kommen und nicht zu verwechseln mit der Zahlungsart *Amazon Pay*, die für Kunden ist, die über den Marktplatz Amazon in deinem Webshop einkaufen.

Aktiviere die <<payment/zahlungsarten-verwalten#, Zahlungsart>> *Amazon*, wie im Folgenden beschrieben.

[.instruction]
Zahlungsart Amazon aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Setze ein Häkchen bei *Auch inaktive anzeigen*.
. Klicke auf den Ordner *International &gt; Amazon*. +
→ Die Einstellungen für die Amazon-Zahlungsart werden angezeigt.
. Setze ein Häkchen bei der Option *Aktiv*.
. Nimm ggf. weitere Einstellungen vor.
. *Speichere* die Einstellungen.

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » Systemeinstellungen » CRM » Kundenklassen* aktivierst oder deaktivierst du *erlaubte Zahlungsarten*. +
Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#4550]
== Amazon Business einrichten

Mit Amazon Business verkaufst du deine Artikel an gewerbliche Kunden. Bevor du Einstellungen in plentymarkets vornimmst, link:https://services.amazon.de/programme/b2b-verkaufen/merkmale-und-vorteile.html[registriere^] dich bei Amazon für das Verkäuferprogramm. Damit deine Artikel als B2B-Artikel an Amazon Business übermittelt werden, muss Amazon Business für das Amazon-Konto freigeschaltet werden. Du kannst einen Standard-Verkaufspreis für Amazon Business erstellen und bis zu 5 weitere Verkaufspreise erstellen, wenn du Mengenrabatte für Amazon Business anbieten willst. Nimm die im Folgenden beschriebenen Einstellungen vor, um Artikel an Amazon Business zu übermitteln.

[IMPORTANT]
.Hinweis zu Amazon Business
====
Aktuell ist Amazon Business nur für die Länderplattformen Amazon.de und Amazon.co.uk verfügbar.
====

[#4555]
=== Amazon Business aktivieren

Im Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen* aktivierst du das Amazon-Konto für Amazon Business.

[.instruction]
Amazon-Konto für Amazon Business aktivieren:

.  Öffne das Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen » Konto öffnen » Tab: Einstellungen*.
.  Setze ein Häkchen bei der Option *B2B*.
. *Speichere* die Einstellungen.

[#4560]
=== Verkaufspreis anlegen

Nachdem das Amazon-Konto für Amazon Business freigeschaltet wurde, hast du die Möglichkeit, Verkaufspreise für B2B-Artikel zu erstellen und zu verknüpfen. Du kannst neben dem Standardpreis für Artikel ab Menge 1 bis zu 5 weitere Preise für Mengenrabatte anlegen. Dabei können Preise für Mengenrabatt als Festpreis oder prozentual angelegt werden. +

Wenn du keinen separaten Verkaufspreis für Amazon Business erstellst, wird der Standard-Verkaufspreis für Amazon übertragen, sofern Amazon Business an diesem Preis aktiviert wurde.

[#4565]
==== Verkaufspreis anlegen

Lege zunächst einen Standardpreis für B2B-Artikel an. Dabei müssen im Menü *System » Systemeinstellungen » Artikel » Verkaufspreise* die Option *Ab Menge*, die *Herkunft* und das *Amazon-Konto* eingestellt werden.

[.instruction]
Standardverkaufspreis für B2B-Artikel anlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise*.
. Klicke auf *Neu*. +
→ Das Tab *Neu* wird geöffnet.
. Trage bei der Option *Ab Menge* eine *1* ein.
. Wählen die Herkunft *Amazon Germany B2B*.
. Wähle das *Amazon-Konto*, das für Amazon B2B freigeschaltet ist.
. Nimm weitere Einstellungen gemäß Tabelle 10 auf der Seite <<artikel/artikel-verwalten#880, Artikel verwalten>> vor.
. *Speichere* die Einstellungen.

[#4570]
==== Verkaufspreis für Mengenrabatt anlegen

Gehe wie im Folgenden beschrieben vor, um Amazon Business-Kunden Mengenrabatte anzubieten.

[.instruction]
Verkaufspreis für Mengenrabatt anlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise*.
. Klicke auf *Neu*. +
→ Das Tab *Neu* wird geöffnet.
. Trage bei der Option *Ab Menge* die Mege ein, ab welcher der Verkaufspreis gelten soll. Die Menge muss größer als 1 sein.
. Wähle die Herkunft *Amazon Germany B2B*.
. Wähle das *Amazon-Konto*, das für Amazon B2B freigeschaltet ist.
. Nimm weitere Einstellungen gemäß Tabelle 10 auf der Seite <<artikel/artikel-verwalten#880, Artikel verwalten>> vor.
. *Speichere* die Einstellungen.

*_Oder:_* Bis zu 5 Verkaufspreise für den Mengenrabatt können auch prozentual über Merkmalverknüpfungen dargestellt werden. Dafür wird beim Anlegen des Merkmals vom Typ *Auswahl* oder *Text* die Amazon-Verküpfung *quantity_price_type* gewählt und bei der Artikelverknüpfung der Wert *percent* eingegeben. Zusätzlich müssen Merkmale mit den Amazon-Verknüpfungen *quantity_lower_bound1-5* für die Rabattmenge und *quantity_price1-5* für die Prozentzahl angelegt werden.

[.instruction]
Merkmal quantity_price_type anlegen:

.  Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
.  Klappe das Merkmal auf, das du für Amazon verwenden möchtest. +
→ Der Bearbeitungsbereich des Merkmals wird geöffnet.
.  Wähle bei *Amazon-Verknüpfung* den Produkttyp. +
→ Eine neue Dropdown-Liste erscheint.
.  Wähle Sie in der Dropdown-Liste das Amazon-Feld *quantity_price_type*.
.  Klicke auf *Hinzufügen*. +
→ Die Verknüpfung wird angelegt.

Aktiviere als nächstes das <<artikel/artikel-verwalten#80, Merkmal>> in den Artikeleinstellungen und hinterlege den Wert *percent*.

[.instruction]
Merkmal am Artikel aktivieren:

.  Öffne das Menü *Artikel » Artikel bearbeiten*.
.  Öffne den Artikel.
.  Wechsele in das Tab *Merkmale*.
.  Setze bei dem Merkmal ein Häkchen, um das Merkmal zu aktivieren.
. *Speichere* die Einstellungen. +
→ Das Feld für die Eingabe des Wertes wird angelegt.
.  Trage den Wert *percent* ein.
. *Speichere* die Einstellungen.

Lege die Merkmale mit den Amazon-Verknüpfungen *quantity_lower_bound1-5* und *quantity_price1-5* auf die gleiche Weise an. Wähle dabei für *quantity_lower_bound1-5* Merkmale vom Typ *ganze Zahl* und für *quantity_price1-5* Merkmale vom Typ *ganze Zahl* oder *Kommazahl*.

[#5700]
==  Amazon Pay einrichten

*Bezahlen mit Amazon* ist eine umfassende Zahlungslösung für Online-Händler. Durch *Bezahlen mit Amazon* gibst du Millionen von Amazon-Kunden die Möglichkeit, sicher auf deiner Website einzukaufen, ohne Versand- und Zahlungsinformationen erneut einzugeben. Kunden können Einkäufe rasch abschließen, ohne Ihre Website zu verlassen.

Die Besonderheit der Advanced-Option von Bezahlen mit Amazon liegt darin, dass sie eine reine Zahlungsabwicklung bietet. Du übermittelst nur den zur Abwicklung der Transaktion notwendigen Zahlungsbetrag – ohne Details zum Warenkorb oder zu Artikeldaten (vgl. Amazon).

Auf der Handbuchseite <<payment/zahlungsanbieter/amazon-pay#, Amazon Pay>> erhältst du wichtige Hinweise zur Integration des Zahlungsanbieters in plentymarkets.

[#6600]
==  API-Log abrufen

Im Menü <<basics/datenaustausch/api-log#, Datenaustausch » API-Log>> findest du eine Historie über Vorgänge, die über die Amazon-Schnittstelle ausgeführt wurden. Folgende Formate stehen dir für Amazon zur Auswahl:

* *Amazoncatalog*
* *AmazonControllerOrders*
* *AmazonFBAOrders*
* *AmazonOrder*
* *AmazonOrderFulfillment*
* *AmazonPayments*
* *AmazonPaymentsAdvanced*
* *AmazonPaymentsFulfillment*
* *AmazonPriceUpdate*
* *AmazonRequestReport*
* *AmazonOrderRefund*
* *AmazonStock*
* *ArticleAmazonCSV*
* *Reader_ArticleAmazonCSV_Execution*

[.instruction]
API-Log abrufen:

.  Öffne das Menü *Daten » API-Log » Tab: API-Log*.
.  Wähle ein Format aus der Dropdown-Liste *Vorgang*.
.  Wähle ggf. ein *Datum*, um nur Einträge eines bestimmten Tages zu erhalten.
.  Klicke auf *Suchen*, um die Suche auszuführen. +
→ Die Vorgänge werden angezeigt.

[#6700]
== FAQ

=== Preis- und Bestandsabgleich

===== Welche Einstellungen muss ich vornehmen, damit Preise an Amazon übermittelt werden?

[.indented]
* *Verkaufspreis* aktivieren: Achte darauf, dass der Verkaufspreis des Artikels im Menü *System » Systemeinstellungen » Artikel » Verkaufspreise* für das Amazon-Konto und die Amazon-Herkunft aktiviert ist.

* Aktiviere den Artikel im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID*. Dazu setzt du zunächst im *Tab: Einstellungen* ein Häkchen bei der Option *Aktiv* im Bereich *Verfügbarkeit*. Aktiviere außerdem im *Tab: Verfügbarkeit* in der Dropdown-Liste im Bereich *Märkte* die Option *Web-API* und die gewünschte *Amazon-Herkunft*.

* *Amazon-Produkttyp*: Im *Tab: Multi-Channel* des Artikels muss im Bereich *Amazon* ein *Produkttyp* ausgewählt sein.

* *SKU*: Füge im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* im Bereich *SKU* eine SKU mit der Herkunft *Amazon* hinzu.

===== Welche Einstellungen muss ich vornehmen, damit Bestände an Amazon übermittelt werden?

[.indented]
* Aktiviere den Artikel im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit*. Dazu setzt du zunächst im *Tab: Einstellungen* ein Häkchen bei der Option *Aktiv* im Bereich *Verfügbarkeit*. Aktiviere außerdem im *Tab: Verfügbarkeit* in der Dropdown-Liste im Bereich *Märkte* die Option *Web-API* und die gewünschte *Amazon-Herkunft*.

* *Amazon Produkttyp*: Im *Tab: Multi-Channel* des Artikels muss im Bereich *Amazon* ein *Produkttyp* ausgewählt sein.

* *SKU*: Füge im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* im Bereich *SKU* eine SKU mit der Herkunft *Amazon* hinzu.

* Exportfilter *Shop-Artikel* beachten: Wenn du unter *System » Systemeinstellungen » Märkte » Amazon » Einstellungen » Tab: Artikeleinstellungen* im Bereich *Exportfilter* für die Einstellung *Shop-Artikel* die Option *Nur im Webshop sichtbare Artikel* gewählt hast, achte darauf, dass der Artikel im *Tab: Einstellungen* auch für den Webshop aktiviert ist.
