= Amazon Business einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Amazon Business, Amazon B2B
:description: Multi-Channel in plentymarkets: Verkaufe deine Artikel über den Marktplatz Amazon an gewerbliche Kunden.
:position:
:url: maerkte/amazon/amazon-business
:id: 2QX9CGL
:author: team-multi-channel

Mit Amazon Business verkaufst du deine Artikel an gewerbliche Kunden. Bevor du Einstellungen in plentymarkets vornimmst, link:https://services.amazon.de/programme/b2b-verkaufen/merkmale-und-vorteile.html[registriere^]{nbsp}icon:external-link[] dich bei Amazon für das Verkäuferprogramm. Damit deine Artikel als B2B-Artikel an Amazon Business übermittelt werden, muss Amazon Business für das Amazon-Konto freigeschaltet werden. Du kannst einen Standard-Verkaufspreis für Amazon Business erstellen und bis zu 5 weitere Verkaufspreise erstellen, wenn du Mengenrabatte für Amazon Business anbieten möchtest. Nimm die im Folgenden beschriebenen Einstellungen vor, um Artikel an Amazon Business zu übermitteln.

[IMPORTANT]
.Hinweis zu Amazon Business
====
Aktuell ist Amazon Business für die Länderplattformen Amazon.co.uk, Amazon.de, Amazon.es, Amazon.fr, Amazon.it, Amazon.es FBA, Amazon.fr FBA und Amazon.it FBA verfügbar.
====

[#4555]
=== Amazon Business aktivieren

Im Menü *Einrichtung » Märkte » Amazon » Einstellungen* aktivierst du das Amazon-Konto für Amazon Business.

[IMPORTANT]
.Amazon Business nur mit Amazon VCS nutzen
====
Zum Erstellen von B2B-Rechnungen benötigst du den <<maerkte/amazon/amazon-einrichten#6800, VCS-Service von Amazon>>, bei dem Amazon die Umsatzsteuer für Amazon-Aufträge berechnet. Aktiviere deshalb die Option *VCS plentymarkets* (VCS Lite) oder *VCS Amazon*, wenn du Amazon Business nutzen möchtest.
====

[.instruction]
Amazon-Konto für Amazon Business aktivieren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen » Konto öffnen » Tab: Einstellungen*.
. Aktiviere die Einstellung *B2B*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
