= Setting up a catalogue of items
:lang: en
include::{includedir}/_header.adoc[]
:position: 80
:url: quick-start/quick-start-item-catalogue
:id: IKOMOQN

IMPORTANT: Have you already set up countries of delivery and divided them into regions, set up the shipping profile and defined shipping costs? Not yet? Return to <<quick-start/quick-start-shipping-options#, setting up shipping options>>.

Now you can add your products to plentymarkets.

[#5]
== Getting prepared

plentymarkets manages some item information centrally and links it to variations. So before you can create variations, you have to save this information in the system. The following item information must exist in the system before you can create items and variations:

* Categories
* Attributes
* Sales prices

Now you will learn how to save this information in plentymarkets.

[#10]
=== Creating categories

You can use categories of the type *item* to structure your product portfolio and organise the items in your online store. Each item must be assigned to at least one category.

The Ceres online store can have either 2 or up to 4 category levels:

* 1 main category + 1 subcategory
  ** The default navigation bar displays a maximum of one other category level below the main categories.
* 1 main category \+ up to 3 subcategories
  ** The mega menu displays up to three more levels below the main category.

[TIP]
.Planning the category structure
====
Think about which categories and subcategories make sense for your products. How should you sort your items so that customers can easily find their way around your store? Before you get started, compile this information. You can use a tree diagram to make finding appropriate product groups easier.
====

To create a main category, proceed as described below.

[.instruction]
Creating a main category:

. Go to *Item » Category*.
. From the drop-down list, select the client you want to create the category for. +
*_Tip:_* The default client is preselected by default.
. Click on *New category* in the bottom left corner. +
→ The *Create new category* window opens.
. Enter a name. +
*_Tip:_* *Main category* is selected by default.
. Click on *Create*. +
→ The category is created. +
→ The *Settings* tab of the category opens. +
. Enter a *position*. The position determines in which order the categories will be displayed in the online store. Every new category has a default position of 0. +
*_Tip:_* Count by tens when creating position numbers. This will allow you to easily add new categories in between.
. Activate the *Client (store)* checkbox to display that category for the respective client.
. Enter a *Meta title*. +
*_Tip:_* The meta title will appear in the browser tab.
. *Save* the settings. +
→ The category is created. +
*_Note:_* The category will only appear in the online store if at least one of the items linked to the category is visible for that client.

Now create a subcategory for your new main category.

[.instruction]
Creating a subcategory:

. Go to *Item » Category*.
. Click on *New category* in the bottom left corner. +
→ The *Create new category* window opens.
. Enter a name. +
. Select *Subcategory*.
. Select the main category you want to create the subcategory for. +
*_Tip:_* If you want to create a subcategory on the third or fourth level, click on the folder icon to open the main category. Open the subcategory folders the same way until you reach the category you want to create a new subcategory for.
. Click on *Create*. +
→ The category is created. +
→ The *Settings* tab of the category opens.
. Enter a *position*. The position determines in which order the categories will be displayed in the online store. Every new category has a default position of 0. +
*_Tip:_* Count by tens when creating position numbers. This will allow you to easily add new categories in between.
. Activate the *Client (store)* checkbox to display that category for the respective client.
. Enter a *Meta title*. +
*_Tip:_* The meta title will appear in the browser tab.
. *Save* the settings. +
→ The category is created. +
*_Note:_* The category will only appear in the online store if at least one of the items linked to the category is visible for that client.


[TIP]
.New categories not showing up in the online store?
====
If your categories do not appear in the online store, have a look at our <<artikel/best-practices/best-practices_kategorien>>check list for category visibility>> (only available in German).
====

[#20]
=== Creating attributes

Attributes are used to create variations. Variations are different models of the same item. They are all similar, but differ in one or multiple properties. Some typical attributes are e.g. colours and sizes. To prevent you from having to create a separate item for each of your products, plentymarkets creates attributes for these properties and assigns them to an item. To give you an example, we will describe how to create a *colour* attribute below.

[TIP]
.Example
====
You want to sell an item in 3 colours. Customers should be able to choose one of the 3 colours when buying the item. Instead of creating 3 items, we will create one item with three variations. We will use attribute values to create these variations.
====

[.instruction]
Creating the "Colour" attribute:

. Go to *System » System settings » Item » Attributes*.
. Click on *New attribute*. +
→ The *New attribute* window opens.
. Enter a *Name (internal)*, e.g. *Colour*. +
*_Tip:_* The internal name will not be visible in the online store.
. *Save* the settings. +
→ The attribute is created. +
→ The *Basic settings* tab of the attribute opens.
. Click on the *Name* tab.
. Enter a name for the attribute for each language you will use in your online store. +
→ This name is shown in the online store.
. *Save* the settings.

Now you can create attribute values for the attribute. As an example, we will create the value “Green”.

[.instruction]
Creating the value “Green” for the “Colour” attribute:

. Click on the *Values* tab.
. Click on *New value*. +
→ The *New value* window opens.
. Enter a *Name (internal)*, e.g. *Green*. +
*_Tip:_* The internal name will not be visible in the online store.
. *Save* the settings. +
→ The value is created. +
→ The value is displayed in the list.
. Enter a name for the value in the *Name* column. +
*_Tip:_* The internal name is used by default. +
→ This name is shown in the online store.
. *_Optional:_* If you offer your products in multiple languages, select the other languages from the *Show language* drop-down list.
. *_Optional:_* Enter the name of the value in this language in the *Name* column. +
→ This name will be shown in the online store later on.
. *Save* the settings.

// Als Beispiel oder allgemein formulieren? Also "Farbe" oder "Attribut"?


[#30]
=== Adjusting the sales price

You can create any number of sales prices and link them to variations. Your system already includes the *Price* sales price, so that you can start selling items as quickly as possible. Check the settings of the *Price* sales price before linking it to variations. Adjust the settings as necessary. Proceed as described below.

[.instruction]
Adjusting the “Price” sales price:

. Go to *System » System settings » Item » Sales prices*. +
→ A list of sales prices opens.
. Click on the *Price* sales price. +
→ The sales price opens.
. Check the settings of the sales price. Pay attention to the information given in <<table-adjust-sales-price>>.
. *Save* the settings.

[[table-adjust-sales-price]]
.Adjusting the *Price* sales price
[cols="1,2"]
|====
|Setting |Explanation

|*Internal name*; +
*External name*
|By default, the sales price is called *Price* in English and *Preis* in German. If you want, you can change these names in the *Language* tab. There you can also enter translations of the name in other languages. +
*_Tip:_* The external name is shown in the online store.

|*Currency*
|All currencies are activated by default. If necessary, limit the sales prices to certain currencies.

|*Client*
|All clients are activated by default. If necessary, limit the sales prices to certain clients.

|*Country*
|All countries are activated by default. If necessary, limit the sales prices to certain countries.

|*Referrer*
|In addition to the standard online store, multiple other referrers are activated by default.
|====

[#40]
== Setting up a catalogue of items

By now you have entered the following information required to create your products in plentymarkets:

* Categories
* Attributes
* Sales price

Before you start entering item data into the system, take a look at the item overview and the item structure. We will explain how the item overview works and introduce you to the example items preconfigured in your new system.

[#50]
=== Understanding the item overview

Go to *Item » Edit item*. This is where you can access all items and variations. In this item overview you can search for items and variations, edit them and create new items.

There are filters in the column on the left. Use them to search for specific subsets of items. When you’re first getting started, the most important filter is the *Active* filter. This filter specifies whether you only want to see the items and variations that are currently visible in your online store. This filter is set to *Yes* by default. Once you have many items and variations, this filter will help you edit your items quicker. However, it can also cause some confusion in the beginning because inactive items will not be displayed when you click on *Search*, unless you have set the filter to *No* or *ALL*.


[#60]
=== Understanding the example items

Your plentymarkets system contains some example items and variations. They will help you understand the structure of items and variations before entering your own data.

We will give you a brief overview of the item structure using these examples.

[#65]
==== Displaying example items

[.instruction]
Displaying example items:

. Go to *Item » Edit item*.
. Click on *Search* in the top left corner. +
→ The item overview displays the example items.
. Open the following items:
  * The single item “Lounge chair Floating Water” (item ID 123)
  * The variation item “Two-seater Paradise Now” (item ID 132)
. Click through the tabs of both the items and the variations to familiarise yourself with the settings. +
→ <<table-example-items>> compares both items.
. Test the inheritance functionality:
  .. Link the variation 1065 of item 132 to another category in the *Categories* tab. +
  → The previously inherited variation category is saved directly. +
  → The inheritance is deactivated.
  .. Click on *Activate inheritance*. +
  → The category you linked is removed. +
  → The category of the main variation is applied.

[[table-example-items]]
.Single and variation items
[cols="1,3,3"]
|====
| |Single item |Variation item

|Item ID
|123
|132

|Name 1
|Lounge chair Floating Water
|Two-seater Paradise Now

|Main variation ID
|1021
|1030

|Main variation purchasable
|Yes +
*_Tip:_* For single items, the product should match the main variation.
|No +
*_Tip:_* For variation items, the main variation should not be a purchasable product. In this case, the main variation only exists to supply the variations of the item with data through inheritance.

|Variation ID
|--
|1065 - red +
1066 - white

|Manufacturer
|A & C Design
|Exclusive Leather

|Sales price
|Price +
RRP
|Price +
RRP +
*_Tip:_* Variations do not inherit prices from the main variation.

|Category
|Living room » Armchairs & Stools
a|Living room » Sofas +
*_Tip:_* Variations inherit the category from the main variation.

|Attribute value combination +
(Attribute:Attribute value)
|---
|1065 - Couch color:red +
1066 - Couch color:white +
*_Tip:_* The main variation is not linked to any attribute.

|Client (store)
|Standard Shop
|Standard Shop +
*_Tip:_* Variations inherit the client from the main variation.
|====


[#90]
=== Deleting the example items

Now that you have examined the example items, they have served their purpose and you can delete them. This way, you can ensure that you start off with a clean system that does not contain any unnecessary data. The fastest way to delete the example items is to use the group function.

[.instruction]
Deleting the example items using the group function:

. Go to *Item » Edit item*.
. Set the *Active* filter to *ALL*.
. Click on *Search*. +
→ All items saved in the system are displayed.
. Click on the checkbox in the top left corner to select all of the displayed items.
. Click on *Item group function*. +
→ The *Item group function* window opens.
. Select *Delete item*.
. Click on *Execute*. +
→ All items are deleted from the system.


[#220]
=== Creating items and variations

It is finally time: You get to enter your very own items in plentymarkets. Depending on how many items you want to start with and how you have managed your item data so far, you have two ways of entering the data into the system:

* <<#100, Create items manually>> +
*_Tip:_* Once you have created your first item, you can work faster by copying this item and modifying the copy.
* <<#120, Import item data from a CSV file>> +
*_Tip:_* Even if you import your items, you should create at least one item manually to become familiar with the item structure. Remember to delete that example item before importing your data.

We will describe both ways below.

[TIP]
.Changes not visible immediately
====
New variations and changes to variation data are not available in the online store and exports immediately. For more information on how to check if the variation data is up to date, see the manual page <<item/checking-data-status#, Checking status of item data>>.
====

[#100]
==== Creating items manually

Now you will create your first item and make it ready for sale. To help you get started as quickly as possible, we will only describe the most necessary settings here to ensure that you can sell the item in your online store.

[.instruction]
Creating items manually:

. Go to *Item » Edit item*.
. Click on *New*. +
→ The *New item* tab opens. +
*_Tip:_* The *Standard* item type is preselected by default.
. Enter a name.
. Enter a number for the content.
. Select a unit for this content from the drop-down list.
. Click on the category. +
→ This will become the default category for the item's main variation.
. Enter a *Price*. +
. *Save* the settings. +
→ The item is created. +
→ A main variation is created. +
→ The item's *Global* tab opens.
. Adjust the other settings as necessary. Pay attention to the information given in <<settings-edit-item>>. +
*_Tip:_* The settings described in <<settings-edit-item>> refer to the various tabs within the item’s editing window. The tab is displayed as a subheading in the table.
. *Save* the settings. +
*_Note:_* New items and changes to item data are not available in the online store and exports immediately. +
*_Tip:_* View of a preview of the item:
 .. Click on the preview icon in the save bar of the item. +
 → The *Client (store)* window is displayed. +
 .. Use the drop-down list to specify which *Plugin Set* you want to see a preview of.
 .. Use the drop-down list to specify which *Client (store)* you want to see a preview of. +
 *_Tip:_* These settings are preselected next time you click on the preview icon.
 .. Click on *Execute*. +
 → A preview of the item is shown.

[[settings-edit-item]]
.Item settings
[cols="1,3"]
|====
|Setting |Explanation

|*ID*
|plentymarkets can automatically assign a consecutive number (recommended). +
Alternatively, you can enter a custom item ID when creating an item. The ID may only contain numbers. IDs must be unique, i.e. they may only be used once per system.

2+|Tab: Global

|*Shipping profiles*
|Activate the *DHL* shipping profile. No shipping profile is selected by default. +
*_Note:_* Activate at least one shipping profile per item. Otherwise the shipping costs will not be calculated correctly.

2+|Tab: Variation ID » Settings

|*Active*
|Activate the item. Items will only be displayed in the online store when they are active.

|*Availability*
|Select the availability level. +
*_Tip:_* You are legally obligated to inform consumers about your products’ delivery periods. Go to *System » System settings » Item » Availability* to find default texts for 5 availability levels. Modify these texts if necessary.

|*Show in online store:* +
*Available automatically if net stock is positive*;
*Not available automatically if net stock is 0 or negative*
|Activate both options. This way, the variation will be available and purchasable if net stock is positive and not purchasable otherwise.

|*Sales price*
|Add *Price* sales price and enter a price.

|*Barcode*
|Add a barcode and enter a code.

|*ASIN/ePID*
|Add ASIN/ePID and enter the ASIN or ePID.

|*Gross weight*; +
*Net weight*
|Enter the weight in grams or kilograms. +
*_Note:_* This information is necessary if you want to calculate shipping costs based on weight.

|*VAT*
|Select the product’s VAT rate. +
*_Tip:_* To maintain the VAT rates, go to *System » System settings » Client » Select client » Location » Select location » Accounting*.

2+|Tab: Variation ID » Availability

|*Client (store): Available*
|Select all clients (stores) where the variation should be available.

2+|Tab: Texts

|*Name 1*
|Enter the item name. +
*_Tip:_* This name is shown in the online store. The name applies for all variations of this item.

|*Item text*
|Enter the item text. The item text is a detailed product description.It is displayed in the online store.
|====

[#110]
==== Creating variations manually

Great! Now you have created your first item. You probably noticed than when creating a new item, you always create a main variation. If you only want to sell single items, the main variation is the same as your product. If you want to group your products as variations of the same item, you should create more variations next.

[TIP]
.Inheritance
====
Any time you create a variation, this variation inherits the following settings from the main variation:

* Availability settings
* Sales price and price
* Category
* Supplier
* Warehouse
* Client availability

Because of this, when creating an item with multiple variations, we recommend that you treat the main variation as a virtual instance and only use it to pass on data to the variations. If you do not want a variation to inherit one or multiple settings, you can disable inheritance for this variation and enter separate data for it.
====

[.instruction]
Creating one or multiple variations:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Variations* tab.
. Click on *New*. +
→ The *Create new variations* window opens.
. Enter a number for the content.
. Select a unit for this content from the drop-down list.
. Select one or multiple attributes. +
→ The *Combinations* information displays how many variations will be created.
. Click on *Create variations*. +
→ The variations are created. +
→ The variation overview displays the variations. +
*_Tip:_* The variations inherit all inheritable settings from the main variation.  +
*_Note:_* New variations and changes to variation data are not available in the online store and exports immediately. +
*_Tip:_* View a preview of the variation:
  .. Click on the preview icon in the save bar of the variation. +
  → The *Client (store)* window is displayed. +
  .. Use the drop-down list to specify which *Plugin Set* you want to see a preview of.
  .. Use the drop-down list to specify which *Client (Store)* you want to see a preview of.
  .. Click on *Execute*. +
  → A preview of the variation is shown.

[TIP]
.Copying an item
====
If you want to sell multiple similar items, you can save time during item creation by copying an item and adjusting it. Click on the *Copy* symbol in the top bar of the item.
====

[#120]
==== Importing items and variations

Of course it is not a problem if you want to import a large number of items all at once. To import items and variations, you need to have this data saved in a CSV file on your computer.

[TIP]
.Create an example item before the import
====
Even if you import your items, you should create at least one item manually to become familiar with the item structure. Remember to delete that example item before importing your data.
====

===== Sample file for initial item import

To make importing your items easier, we have prepared a CSV file which contains all data fields required to important sellable items.

////
To make importing your items easier, we have prepared a sync and a CSV file which contain all data fields required to important sellable items.

Table entry:
|link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/Initialer_Artikelimport.json.zip[Sample sync for initial item import] [Download as ZIP file]
|The sample sync contains the same data fields as the sample CSV file.
////

[[table-item-catalogue-sample-files]]
.Sample file
[cols="1,2"]
|====
|Download |Explanation

|link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/musterdatei_initialer_artikelimport_190226.csv[Sample CSV file for initial item import] [Download]
|The CSV file contains a single item and a variation item with one virtual main variation and 3 more variations. +
*_Tip:_* The column titles have the exact same names as the fields you enter as targets during mapping in ElasticSync.

|====

[#130]
===== Preparing the import file

Now you can prepare the CSV file containing your item data. Download the sample CSV file and familiarise yourself with the file structure.

If you want to import a lot of item data at once, then before you start the import, make sure you have saved all the data in your system that you will need to link items and variations:

* Categories
* Attributes
* Sales prices

[#140]
===== Creating a sync for the initial item import

In plentymarkets, you import data using ElasticSync. First, you create a sync, then you map the fields you want to import data into in plentymarkets.

[.instruction]
Creating a sync for the item import:

. Go to *Data » ElasticSync*.
. Click on *Add sync*. +
→ The editing area *New sync* is displayed.
. Enter *Initial item import* into the *Name* field.
. Select *Item* from the *Type* drop-down list.
. Carry out the settings in the *Import* section. Pay attention to the information in <table-create-sync>.
. Select *HTTP* from the *Source* drop-down list.
. Select *Data upload* from the *HTTP options* drop-down list.
. Click on the More icon in the *URL* field. +
. Click on *Upload file* in the overlay.
. Use the folder navigation to select the file you want to import.
. Click on *Open*. +
→ The file is uploaded.
. Click on the file in the list to select it.
. Click on *Select*. +
*_Tip:_* If the button is greyed out, click on the file in the list. +
→ The file is flagged for import.
. *Save* the settings. +
→ The sync is created. +
→ The matching settings of the sync open.

[[table-create-sync]]
.Creating a sync for the item import
[cols="1,3"]
|====
|Setting |Explanation

2+|*Import*

|*Character set*
|Select the character set of the file or the option *Automatically detect*.
// Umlaute? oder ist *Automatisch* immer OK?

2+|*Separator*

|*Separator*
|Select the field separator that is set in the import file in order to separate the data fields (columns) of a data record from each other. +
Possible separators are *Semicolon*, *Comma*, *Tab* and *Pipe*. +
*_Tip:_* The sample file uses *Semicolon* as its separator.

|*Delimiter*
|Select delimiters within the fields that contain multiple values. +
*"* = Individual values within the same field are separated by double quotation marks. +
*'* = Individual values within the same field are separated by single quotation marks.
|====


[#150]
===== Carrying out sync settings

Once you have created the sync, you can specify how the data is structured in your import file. You also have to map the data in the import file to the data fields in plentymarkets. Mapping in this context means that you tell plentymarkets which data columns to import to which data fields in plentymarkets.

[.instruction]
Carrying out sync settings:

. Go to *Data » ElasticSync*.
. Click on the sync in the sync overview.
. Click on *Matching*. +
. Carry out the settings in the *Matching* and *Import options* sections. Pay attention to the information given in <<table-sync-import-options>>.
. *Save* the settings.
. Click on *Mapping* in the list on the left.
. Enter *Initial item import* as the name.
. *Save* the settings. +
→ There is a *Source* field for each column of the import file. +
*_Tip:_* All fields of the import file are displayed together with a preview of the data in the *Import data* column.
. Check the data in the *Preview* column. +
→ If the data have not been recognised correctly, adjust the import settings.
. Select a target data field from the drop-down list in each row of the *plentymarkets data fields* column. Pay attention to the information given in <<table-sync-import-options>>.
. Use the toggle switches on the far left to activate whichever lines of data should be mapped during the import. +
*_Tip:_* You can also activate all lines of data at once by toggling the switch at the very top, next to the *Import data* column.
. *Save* the settings.
. Click on *Run sync* in the toolbar. +
→ The item data is imported.
. Go to *Item » Edit item*.
. Open some of the imported items.
. Check if all item data was imported correctly. +
*_Note:_* New variations and changes to variation data are not available in the online store and exports immediately.

[[table-sync-import-options]]
.Import options for initial item import
[cols="1,2"]
|====
|Option |Explanation

2+|Matching

|Matching settings
a|Select a matching field. +
The matching field determines which data records are considered similar. During the import, the system checks the contents of the matching fields and determines if the data record you want to import already exists. If the data record already exists, it will be updated. If it does not exist yet, a new data record is created. +
*_Note:_* When importing item data, we recommend using the matching field *Variation no.*.

2+|Import options

|*If no data matched*
a|Select the option *Import new data, update existing data*.

|*Decimal number*
a|Select how decimal separators are used in the import file. +
*German notation* = Decimal numbers are separated by comma, e.g. 9,99. A period functions as thousands separator. +
*English notation* = Decimal numbers are separated by period, e.g. 9.99. A comma functions as thousands separator. +
*_Tip:_* The sample file uses German notation.

|*Date format*
|Enter the date format used in the import file. If the date format used matches the default format of Y-m-d H:i:s, you can leave this field empty. Other formats, however, must be entered here. You can use any link:https://php.net/manual/en/function.date.php[date format consistent with PHP usage].

2+|Mapping

|*Item variations / Number of the main variation*
|If you enter the number of a main variation into this field, the mapping will create a new variation instead of a new single item.

|*Item variations / Variation No.*
|The number of the variation +

|*Item texts / Name 1*
|The name of the variation displayed in the online store. +
→ Use the drop-down list on the right to specify which language the name is saved in.

|*Barcodes / Code*
|The barcode of the variation (GTIN etc.). +
→ Use the drop-down list on the right to specify which type of barcode is saved in the column.

|*Item texts / Item text*
|The description text of the variation. +
→ Use the drop-down list on the right to specify which language the description text is saved in.

|*Item images / URL*
|A link to an online image of the product +
*_Tip:_* If you want to upload more than one image for each variation, select *Multi URL (comma-separated)* instead.

|*Sales prices / Price*
|The price of the variation. +
→ Use the drop-down list on the right to select the *Price* sales price. +
*_Note:_* The sales price must exist in the system.

|*Stock / Warehouse*
|The warehouse to import the stock to.

|*Stock / Storage location*
|The storage location to import the stock to. +
0 = Default storage location +
*_Tip:_* If no storage locations are saved, enter 0 to book the stock to the default storage location.

|*Stock / Quantity*
|The quantity of the variation to be imported as stock.

|*Attributes / Attribute value combination*
|The attribute values to be linked to the variation. +
→ Use the drop-down list on the right to specify how your attribute combinations are formatted. +
*_Note:_* The attribute values must exist in the system.

|*Default categories / Category ID*
|The default category the variation should be linked to. +
*_Note:_* The category must exist in the system.

|*Item variations / Active*
|1 = The variation is selected for sale. +
*_Note:_* You should import a 0 for main variations of variation items if you do not want to sell the main variation itself. +

|*Client (store) / Active*
|1 = The variation is active for the client. +
→ Use the drop-down list on the right to select the client *Standard Shop*.

|*Item variations / Available if net stock is positive*
|1 = The variation is available and can be purchased if net stock is positive.

|*Item variations / Not available if net stock is 0 or negative*
|1 = The variation is not available and cannot be purchased if net stock is 0 or negative.

|*Own value* +
(Optional)
|Select *Own value* as source of the import file and enter a text or number into the *Value* field. The field contents of all variations will be imported to the plentymarkets field selected as target.
|====

[#170]
== Saving item images

When you imported your items, you were able to save a URL for images that are available online. If your item images are not available online, you can save the images manually as described below.

NOTE: If you have already imported your item images during the item import, you can directly go to the <<#200, check list>>.

[#180]
=== Uploading item images

You can save images in the item’s *Images* tab and then link these images to item variations. You can upload up to 25 images per item. These images can be in JPG/JPEG or PNG format.

[TIP]
.Using the FTP upload
====
You should transfer larger quantities of images to the server via FTP upload. Note that the image files are named correctly, so that the images can be assigned to the correct items and variations during upload.
====

[.instruction]
Saving images for an item:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Images* tab of the item.
. Drag and drop new images in the *Insert new image* section. +
*_Or:_* Click on *Select files*.
. Use the *Availability* drop-down list to select the clients and/or referrers for which you want do use the image.
. *Save* the settings.

[#190]
=== Linking item images with variations

Now link the images saved for the item to one or more of its variations. Proceed as described below.

[.instruction]
Linking item images to variations:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Images* tab of the item. +
→ A preview of all images saved for the item is displayed.
. Select the images you want to link to one or multiple variations.
. Click on *Variation link* at the bottom of the page. +
→ The *Variation link* window opens.
. Select the variations you want to link the selected images to.
. Click on *Link*. +
→ The images are linked to the selected variations.


[#200]
== Check list item catalogue

Work through the check list in order to review your settings for the item catalogue.

[%interactive]
* [ ] Did you create appropriate categories for your items?
* [ ] Did you create description texts for all items?
* [ ] Did you set the correct item availability levels?
* [ ] Did you select the availability of all items you want to offer in your online store?
* [ ] Did you check that all prices are displayed correctly in the online store?

[#210]
== More about setting up a catalogue of items

=== Getting prepared

* <<item/managing-categories#, Managing categories>>
* <<item/managing-items#390, Managing attributes>>
* <<item/managing-items#870, Managing sales prices>>

=== Managing items

* <<item/introducing-items#, Introducing items>>
* <<item/managing-items#350, Searching for items and variations>>
* <<item/managing-items#, Managing items>>
* <<item/managing-items#155, Editing multiple items>>
* <<item/managing-items#330, Editing multiple variations>>
* <<item/combining-products#, Managing multipacks, item bundles and sets>>


[TIP]
.Using cross-selling
====
You want to draw attention to other products of interest directly from an item? Set up <<item/managing-items#950, cross-selling>>.
====

=== Managing item images

* <<item/managing-items#680, Uploading item images via FTP server>>

=== Importing data

* <<data/importing-data/ElasticSync#, Creating syncs for other imports>>

TIP: Continue with <<quick-start/quick-start-stock#, Booking stock>>.
