= Carrying out initial settings
:lang: en
include::{includedir}/_header.adoc[]
:keywords: master data, bank data, bank details, emails, e-mails, login details, email template, template, templates, template variables
:description: In this part of the quick start, you learn which initial settings you have to carry out.
:position: 30
:url: quick-start/quick-start-initial-settings
:id: U4A9SAW

IMPORTANT: Have you already allowed pop-ups, added a bookmark for your back end login and checked the system requirements? Not yet? Return to <<quick-start#, Taking off>>.

In this part of the quick start, you find explanations about general settings such as saving master data and bank details as well as explanations about carrying out email settings and setting up email templates. Furthermore, we explain on this page how you order a domain and an SSL certificate for your online store.

[#100]
== Saving master data

In the *System » System settings » Settings » Master data* menu, you centrally save the master data of your company, such as the contact data, the address and the VAT number.

[.instruction]
Saving master data:

. Go to *System » System settings » Settings » Master data*.
. Enter your data.
. *Save* the settings. +
→ The master data is saved.

[IMPORTANT]
.Changing contract information
====
Making changes to this master data will not have any effect on the customer information that is saved in your contract with plentymarkets, e.g. for billing purposes. Contract information must be changed in the *Start » Service centre* menu.
====

[#200]
== Saving bank details

Similarly to the master data, you also save your bank details in a central location in your plentymarkets system. If you make changes in this menu, this will have an effect on the entire system.

Your bank details can be replaced with the corresponding text via so-called template variables in email templates. This means that plentymarkets replaces the variables with the corresponding content in the emails. The template variable *$BankOwner* will be replaced with the name of the account holder and *$BankAccount* will insert the account number.

For further information about template variables, refer to the chapter <<quick-start/quick-start-initial-settings#700, Inserting template variables and template functions>> further down on this page of the manual.

[.instruction]
Saving bank details:

. Go to *System » System settings » Settings » Bank*.
. Enter your bank details. Pay attention to the information given in <<table-save-bank-details>>.
. *Save* the settings.

[[table-save-bank-details]]
.Saving bank details
[cols="1,3"]
|====
|Setting |Explanation

|*Account holder*
|Enter the account holder's first and last name. +
Template variable: *$BankOwner*

|*Account No.*
|Enter the account number. +
Template variable: *$BankAccount*

|*Bank code*
|Enter the bank code. +
Template variable: *$BankCode*

|*Bank*
|Enter the name of the bank. +
Template variable: *$BankName*

|*IBAN*
|Enter the International Bank Account Number. +
Template variable: *$BankIban*

|*BIC*
|Enter the Bank Identifier Code. +
Template variable: *$BankSwift*

|====

Refer to the chapter <<quick-start/quick-start-initial-settings#600, Example: Customising the email template>> further down on this page of the manual to see which template variables are available for the email templates.


[#250]
== Creating a customer class

Use customer classes to categorise your customer base according to specific criteria. You can determine the minimum order quantities, grant discounts and decide whether the prices in your online store are displayed as gross or net prices.

For the beginning, we recommend creating 2 customer classes: B2C for your end customers and B2B for sellers. You may need the customer classes for further settings that you carry out in your plentymarkets system such as saving sales prices.

[.instruction]
Creating a customer class:

. Go to *System » System settings » CRM » Customer classes*.
. Click on the *New customer class* tab.
. Carry out the settings. Pay attention to the information given in <<table-quick-start-create-customer-class>>.
. *Save* the settings.

[[table-quick-start-create-customer-class]]
.Creating a customer class
[cols="1,3"]
|====
|Setting |Explanation

|*Name*
|Enter the name for the customer class, e.g. standard customer or B2C.

|*Discount type*
|If required, select a discount type. For further information about the discount types, refer to the <<crm/managing-contacts#25, Using the discount system>> chapter on the <<crm/managing-contacts#, Managing contacts>> page of the manual.

|*Permitted payment methods*
|Select which methods of payment are permitted for the customer class. These methods of payment will later be available in your online store. By default, all available methods of payment are allowed.

|*Display of the prices in the online store*
|Select whether the prices are displayed as gross or net prices in the online store.

|====

[#300]
== Saving the email signature

Now save the signature of your online store which will automatically be inserted in your email templates once you have inserted the template variable *$SignatureText* at the end of the email templates. To do so, proceed as described below.

[.instruction]
Saving the email signature:

. Go to *System » System settings » Client » Select client » Email » Signature*.
. Enter the signature text. +
→ *_Important:_* Observe the legal requirements regarding the content of an email signature. If in doubt, consult a specialist lawyer.
. *Save* the settings.

[#400]
== Entering the email login details

In the *System » System settings » Client » Select client » Email » Login details* menu, you save the login details of your email account. In another menu of the system, you define events. When this event occurs, your plentymarkets system then automatically generates and sends emails such as order and shipping confirmations to your customers.

Note that it might be necessary to obtain an approval from your email provider so that plentymarkets is allowed to send emails.

[TIP]
.Test mode sends emails only to your email address
====
There is a test mode which is activated by default. When the test mode is activated, emails are only sent to the email address you saved. This allows you to check all settings of the email despatch and the content before you switch to the live mode.
====

To authorise plentymarkets to send emails via your email account, you have to enter the login details of your email program in plentymarkets.

[.instruction]
Entering email login details:

. Go to *System » System settings » Client » Select client » Email » Login details*.
. Carry out the settings according to <<table-enter-email-login-details>>.
. *Save* the settings.

[[table-enter-email-login-details]]
.Entering the email login details
[cols="1,3"]
|====
|Setting |Explanation

|*Test mode*
|*Active* (default setting) = Select this mode during the test phase. This setting only sends emails to your address. +
*Inactive* = Select once the test phase has ended. This setting sends emails to your customers.

|*Name of sender*
|Enter your name or the name of your company/online store as you would like it to be displayed to the recipient.

|*Email address*
|Enter the email address as listed in your email program, e.g. info@mystore.com.

|*Outgoing mail server/SMTP server*
|You can find out about the outgoing mail server from your provider (e.g. smtp.domain.co.uk or mail.domain.co.uk).

|*User name*
|Enter the user name that matches the email address.

|*Password*
|Enter the password that matches the user name and email address.

|*Port (standard port: 25)*
|The value *25* is correct for almost all providers with the encryption *TLS*. If this value is not correct, please ask your provider for the correct port. +
*_mailbox.org:_* For mailbox.org mailboxes, enter the port *465* and select *SSL* as *encryption method*.

|*Encryption*
|*Select SSL*, *TLS* or *No encryption* (default setting). +
*_mailbox.org:_* For mailbox.org mailboxes, enter the port *465* and select *SSL* as *encryption method*.
|====

[TIP]
.Setting up the email information service
====
Once you have deactivated the test mode, it might be useful especially in the beginning to keep an eye on the emails that were sent by the system. You can use the information service for this. This function sends a blind copy (BCC) of all outgoing emails to an address of your choice.

[.instruction]
Setting up the email information service:

. Go to *System » System settings » Client » Select client » Email » Info service*.
. Select *YES* from the first drop-down list to activate the information service for the email address that you enter in the next line.
. Enter the email address to which the blind copy should be sent.
. *Save* the settings.

In order to deactivate the information service, select *NO* from the drop-down list and save the settings.
====

[#500]
== Setting up email templates

plentymarkets generates all emails based on templates. For the beginning, we recommend setting up the email templates listed in <<table-email-templates>>. Go to *System » System settings » Client » Select client » Email » Templates* to create email templates.

You can adapt all email templates to your individual needs. Go to the chapter <<quick-start/quick-start-initial-settings#600, Example: Customising the email template>> further down on this page of the manual, you find an example how to customise the email template *Online store: confirmation of store order*.

[[table-email-templates]]
.Email templates that are already set up in your system
[cols="1,3"]
|====
|Email template |Explanation

|*Order: Invoice as PDF attachment*
|Sends an invoice to the customer as an attachment. +
*_Important:_* An invoice template for the location *Germany* is already pre-configured. You can adapt the template to your individual needs. To do so, go to*System » System settings » Client » Select client » Locations » Select location » Documents » Invoice*. If an invoice already exists for the order and you have set up an event procedure, the invoice will be sent to your customer automatically since the PDF attachment *Invoice* is selected by default in the template *Order: Invoice as PDF attachment*.  +
 For further information refer to the quick start page <<quick-start/quick-start-automating-processes#, Automating processes>>.

|*Order: Shipping confirmation*
|Is sent when the items are shipped. +
*_Tip:_* Create an event procedure with the event *Package number* and add filters and procedures so that the package number that is saved in the order will be inserted via the template variable *$TrackingURL*. For further information, refer to the quick start page <<quick-start/quick-start-automating-processes#, Automating processes>>.

|*Online store: Confirmation of store order*
|Informs the customer that their order has been received. +
*_Important:_* For legal reasons, you should insert the cancellation rights as well as the terms and conditions in this email template. Also, pay close attention to any wording in the email template that relates to the contract between you and your customer. It is therefore recommended that you have your texts checked by a specialist lawyer. +
Save the texts for the cancellation rights and the terms and conditions in the *System » System settings » Client » Select client » Online store » Legal information*. The template variables *$CancellationRightsText* and *$GeneralTermsConditionsText* are automatically replaced with the cancellation rights and the terms and conditions in the email.
|====

[TIP]
====
There are many more email templates that are already available in your plentymarkets system. Adjust these email templates, if required, and link them with an event in the *System » System settings » Client » Select client » Email » Automatic* menu or set up an event procedure. For further information, refer to the quick start page <<quick-start/quick-start-automating-processes#, Automating processes>>.
====

////
[WARNING]
.Do not forget the bank details and contact data
====
Make sure that all of your email templates contain your bank details and that your current contact information is displayed at the end of the email template. You can use <<quick-start/quick-start-initial-settings#700, template variables>> for this.
====
////

[#550]
=== Saving legal information

It is important that you save the legal information for your online store in advance. Legal information include terms and conditions, cancellation rights, privacy policy, legal disclosure and cancellation form. Insert template variables in the email template. The variables will be replaced with the text in the email templates.

We recommend having the texts checked by a specialist lawyer before you use them.

[.instruction]
Saving legal information:

. Go to *System » System settings » Client » Select client » Online store » Legal information*.
. Expand the language *English*.
. Insert the texts in the corresponding tabs in the *Text* tab. +
→  *_Tip:_* Have the texts about the legal information checked by a specialist lawyer.
. *Save* the settings.


[#600]
=== Example: Customising the email template

In this chapter, we explain how you customise an email template based on the email template *Online store: confirmation of store order*.

[.instruction]
Customising the email template:

. Go to *System » System settings » Client » Select client » Email » Templates*.
. Open the *General email templates* folder and click on *Online store: confirmation of store order*. +
→ The *Settings* tab opens.
. If required, change the settings. Pay attention to the information given in <<table-set-up-email-templates>>.
. Click on the tab *Email message » Tab: Content » Tab: Plain text*. +
→ The standard text opens.
. If required, change the text.
. Insert e.g. the template variables *$CancellationRightsText* and *$GeneralTermsConditionText*. By doing so, the texts for the terms and conditions and the cancellation rights will be inserted in the email template. +
→ *_Note:_* You have saved these texts in the system in advance as described in the <<quick-start/quick-start-initial-settings#550, Saving legal information>> chapter.
. Further information about the template variables for legal information can be found in <<table-template-variables-legal-information>> at the end of this chapter.
. Replace the sample contact data at the end of the template with your own contact data. +
→ For this purpose, you can use the template variable *$SignatureText* and insert the data as described in the <<quick-start/quick-start-initial-settings#300, Saving the email signature>> chapter.
. *Save* the settings.

[[table-set-up-email-templates]]
.Setting up email templates
[cols="1,3"]
|====
|Setting |Explanation

2+|Header

|*Save*
|Saves the email template.

|*Template variables and template functions*
|Opens all template variables and template functions that are available in plentymarkets and that you can use in your email templates.

2+|Tab: Settings

|*Owner*
|The setting *All* is selected by default. This means that all users can access this template.

|*Name*
|Name of the email template that is used for internal distinction. This name is not displayed to the recipient. You can add this name.

|*Content*
|Select*Plain text only* (default setting) or *Only in HTML format*.

|*Template type*
|Select*All* (default setting) if you want the email template to be used for all areas. If you want to use the template in only one area of plentymarkets, you can define this area here by selecting the area from the drop-down list.

|*PDF attachment*
|The setting *No PDF attachment* is selected by default. +
*_Note:_* If you want to attach the invoice as PDF file to your emails later on, you have to set up the invoice template in advance. Furthermore, an invoice must exist for the order and it would be best if you set up an event procedure for this event.
|*Document attachment*
|The setting *No PDF attachment* is selected by default. +
*_Note:_* If you would like to attach a brochure or product catalogue, you must upload this document in the *CMS » Documents* menu. The drop-down list *Document attachment* only lists those documents that were uploaded in the *CMS » Documents* menu.

|*Reply to*
|Enter an email address. If someone replies to the email template, their message is sent to this address. +
*_Note:_* If no email address is entered, replies to this email template are sent to the email address that is saved in the *System » System settings » Client » Select client » Email » Login details* menu.

|*Use design*
|You only have to activate this option if you wish to link an HTML design with the email template. This setting is not relevant in this case since we describe only plain text and no HTML-formatted text in the quick start.

|*Client (store)*
|All clients are activated by default.

2+|Tab: Email message

|*Select language*
|The language *en* is selected by default.

|*Subject*
|If required, adapt the standard text of the subject. Choose the subject carefully so that the emails are recognised by the email account and displayed in the customer's inbox instead of their spam folder. +
*_Note:_* It is possible to insert template variables in the subject line.
|====

After you have adjusted and saved the email template *Online store: confirmation of store order*, this template will automatically be sent to your customers when they place an order in your online store. This is because this template is already linked with the event *New order via online store* in the *System » System settings » Client » Select client » Email » Automatic* menu.

[[table-template-variables-legal-information]]
.Template variables for legal information
[cols="1,3"]
|====
|Legal information |Template variable

|*Terms and conditions*
|Template variable for plain text in the *Text* tab: *$GeneralTermsConditionsText*

|*Cancellation rights*
|Template variable for plain text in the *Text* tab: *$CancellationRightsText*

|*Privacy policy*
|Template variable for plain text in the *Text* tab: *$PrivacyPolicyText*

|*Legal disclosure*
|Template variable for plain text in the *Text* tab: *$LegalDisclosureText*

|*Cancellation form*
|Template variable for plain text in the *Text* tab: *$WithdrawalFormText*

|====

[#700]
=== Inserting template variables and template functions

In plentymarkets, email templates always consist of text as well as template functions and template variables. When plentymarkets sends emails, it automatically replaces the template variables and template functions with the corresponding content. The customer's name will appear instead of the template variable *$CustomerFullName*. The customer's email address will appear instead of *$CustomerEmail*. The order number will appear instead of the variable *$OrderID*.

[IMPORTANT]
.Pay attention to the correct spelling of the template variables
====
Since template variables and template functions trigger pre-configured system commands, it is important that you strictly observe the correct spelling. In order to avoid errors by misspelling, copy the variables and functions and insert them in the desired place in the email template.
====

[.instruction]
Inserting template variables and template functions:

. Go to *System » System settings » Client » Select client » Email » Templates*.
. Open the email template into which you would like to insert the template variable.
. Click on *Template variables and template functions*. +
→ The *Template variables and template functions* window opens.
. Copy the variable that you want to insert into the email template.
. Insert the variable in the text field in the *Email message » Tab: Content » Tab: Plain text* tab.
. *Save* the settings.

[TIP]
.Using the template function *{%Link_Checkout()%}*
====
All emails that you send to your customers should contain the template function *{%Link_Checkout()%}*. This function replaces the link to the *My account* area of your online store. Your customers can then click on the link to update their data, see the order history, add further items to the order or track the order status.
====

[#800]
=== Attaching files to email templates

You can add 2 types of files to your email templates:

* a PDF attachment +
* a document attachment

We describe the difference of these 2 attachments in the following.

Possible types of a PDF attachment, e.g. the invoice, are already available in your plentymarkets system. Go to *System » System settings » Client » Select client » Locations » Select location » Documents* to set up these documents.

A document attachment could be for example a product catalogue, instructions or a photo file. Go to *CMS » Documents* to upload these files.

[#900]
==== Creating and attaching PDFs

The documents that you can send as PDF attachment are automatically generated by your plentymarkets system. An example of such a document is the invoice.

It is set up in 3 steps:

1. Create a document template, e.g. in a business letter template including the logo, and save it to your computer
2. Adjust the document settings (in the following, this step is described in detail)
3. Link the document with the email template (in the following, this step is described in detail)

[.instruction]
Adjusting the document settings:

. Go to *System » System settings » Client » Select client » Locations » Select location » Documents*.
. Select the document that you want to edit, e.g. *Invoice*. +
→ The document *Invoice* is already pre-set. If required, adapt the invoice template.
. Click on the *PDF template* tab.
. Click on *Add template*.
. If required, select a *Payment method*. +
→ The setting *Standard* is selected by default.
. Click on *Select template*.
. Open the PDF document template that you previously created.
. *Save* the settings.
. Click on *Preview* to show a document preview.

[.instruction]
Linking a document with the email template:

. Go to *System » System settings » Client » Select client » Email » Templates*.
. Open the email template.
. Select the file that you want to send as attachment from the drop-down list *PDF attachment*.
. *Save* the settings. +
→ The document is attached to the email.

[#1000]
==== Creating and attaching documents

All of the documents you want to attach to an email template have to be uploaded to the server first. An example of such a document are the terms and conditions. This document is often attached with the order confirmation – given that you did not directly insert the terms and conditions in the email template via the template variable *$GeneralTermsConditionsText*.

It is set up in 2 steps. First, you upload the document in the *CMS » Documents* menu. Second, attach the document to an email template. To do so, proceed as described below.

[.instruction]
Uploading a document:

. Go to *CMS » Documents*.
. Click on *Browse...* in the *Upload* tab.
. Select the file that you want to upload and click on *Open*.
. Select one of the options from the *Right* drop-down list. +
The right specifies whether the document should be visible to *Employees* or *Customers* only or to all visitors of your online store (= *Public*).
. If required, enter a name for the folder.
. *Save* the settings.

[.instruction]
Linking a document with an email template:

. Go to *System » System settings » Client » Select client » Email » Templates*.
. Open the email template.
. Select the file that you want to send as attachment from the drop-down list *Document attachment*.
. *Save* the settings. +
→ The file is attached to the email.

[#1100]
== Ordering a domain

The word "domain" refers to an Internet address in the form of a name and an extension, i.e. the top level domain, e.g. *.de*. You can freely select the name. A domain is unique, i.e. the exact same domain may never be used twice. Therefore, when registering a desired domain, e.g. with a hosting service provider, it is necessary to check whether the domain has already been used.

Proceed as described in the following to order a domain and to save the contact data of the domain owner, the so-called domain handle. Afterwards, you receive information about the monthly costs. After you have saved the contact data and the plentymarkets system has been assigned, you order the domain by clicking on *Place order*.

[.instruction]
Ordering a domain:

. Go to *Start » Service Centre*. +
→ *_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen.
. → The Service Centre opens in a new browser tab.
. Click on the blue plus icon of the system. +
→ The available tabs are shown.
. Click on the *Domain* tab.
. Click on *Order a new domain*.
. Enter the desired domain name.
. Select the top level domain from the drop-down list.
. Click on *Check*. +
→ The system checks if the domain is available.
. Expand the domain ID.
. Click on *Domain handle*.
. Enter the contact details of the domain owner.
. *Save* the settings.

If you already have a domain with another provider and want to relocate the domain, proceed as described in the <<basics/admin-tasks/plentymarkets-account#250, Relocating a domain>> chapter on the <<basics/admin-tasks/plentymarkets-account#, Your plentymarkets account>> page of the manual.

[#1200]
== Buying an SSL certificate

An SSL certificate is used to encrypt your website and provides a secure connection to your online store. Your customers can see when you are using an SSL certificate as your website will be accessed via _https_.

It is important that the domain for which you want to order the SSL certificate is set as main domain in the Service centre.

Proceed as described below to order a SSL certificate with costs.

[.instruction]
Buying an SSL certificate:

. Go to *System » System settings » Client » Select client » SSL*. +
→ The certificate of the domain is displayed.
. In the row *Order new SSL for domain: [domain name]*, click on the down arrow to the right. +
→ The SSL certificates that are available for the domain are displayed.
. Click on *Order SSL* in the line of the SSL certificate that you want to book. +
→ The SSL certificate is ordered. +
*_Note:_* It can take up to 2 hours for the SSL certificate to be activated.

[#1300]
== Check list

Work through the check list in order to review your settings for the initial settings.

[%interactive]

* [ ] Did you save the master data and bank details?
* [ ] Did you save your email account data in the system?
* [ ] Did you save your email signature and insert the template variable *$SignatureText* at the end of your email templates?
* [ ] Did you replace the sample data with your own contact data in all email templates?
* [ ] Do all email templates contain the template function *{%Link_Checkout()%}*?
* [ ] Did you order a domain for your online store?
* [ ] Did you buy an SSL certificate?
* [ ] Did you deactivate the test mode after having tested all the settings so that the emails are from now on sent to your customers and not to your email address any longer?

[#1400]
== More about initial settings

* <<crm/sending-emails#100, Saving the email server's login details>>
* <<crm/sending-emails#1200, Creating an email template>>
* <<online-store/setting-up-ceres#300, Saving legal information>>
* <<quick-start/quick-start-automating-processes#10, Automatically sending email templates>>
* <<crm/sending-newsletters#, Sending newsletters>>
* <<crm/using-the-ticket-system#, Using the ticket system>>
* <<basics/admin-tasks/plentymarkets-account#50, Managing domain data>>
* <<basics/admin-tasks/plentymarkets-account#ssl-certificate, Managing the SSL certificate>>
* <<basics/admin-tasks/plentymarkets-account#20, Changing your contract>>

TIP: Continue to <<quick-start/quick-start-stock-management#, Setting up a warehouse and supplier>>
