= Setting up the online store: Introduction
:lang: en
include::{includedir}/_header.adoc[]
:position: 100
:url: quick-start/quick-start-online-store-introduction

IMPORTANT: Have you already set up your eBay interface? Not yet? Return to the <<quick-start/quick-start-ebay#, eBay quick start>>.

After creating your items and possibly setting up an interface to eBay in the previous chapters, we will now incorporate various payment methods in your online store as well as how to change its design. plentymarkets provides these functionalities, as well as others, via plugins.

Go to *Plugins » Plugin overview*.

On the left you can see your plugin sets. Sets are collections of plugins that all impact the design and functionality of your store as a whole. By linking a set to a client, you activate it for the associated store. Later on you can also create new sets without linking them to a client.This allows you to test changes without them impacting your live environment. Throughout this quick start, we will only work with the standard-shop set provided by default, however. First, unlink the set from the client.

[.instruction]
Unlinking a set:

. Click on the *Link plugin sets* button. +
→ The *Link plugin sets* window opens.
. Select the empty row from the drop-down list.
. *Save* the settings to unlink the plugin set.

Right next to the plugin sets, you will find filter settings. You can use these to display a different selection of plugins according to various criteria. When you open a plugin set, it shows all plugins installed in that set by default.

As you can see, there are three plugins installed by default in every plentymarkets system: Ceres, PayPal and IO. We will have a closer look at Ceres and IO later on. For now we want to give customers the possibility to actually pay for their purchases.

TIP: Continue with <</quick-start/quick-start-setting-up-payment-processing#, payment processing>>.
