= Final steps
:lang: en
include::{includedir}/_header.adoc[]
:position: 160
:url: quick-start/quick-start-final-steps

The finish line is in sight. Use the checklist below to ensure that you have completed all necessary steps. Then it is finally time to unlock your store. And last but not least, we want to show you some resources to help you find your way around plentymarkets.

[#10]
== Final check

Have you already...

[%interactive]

* [ ] carried out the link:https://knowledge.plentymarkets.com/en/quick-start/quick-start-initial-settings[initial settings^]?
* [ ] set up your link:https://knowledge.plentymarkets.com/en/quick-start/quick-start-stock-management[warehouse and suppliers^]?
* [ ] set up link:https://knowledge.plentymarkets.com/en/quick-start/quick-start-shipping-options[shipping options^]?
* [ ] set up your link:https://knowledge.plentymarkets.com/en/quick-start/quick-start-item-catalogue[catalogue of items^]?
* [ ] booked link:https://knowledge.plentymarkets.com/en/quick-start/quick-start-booking-stock[stock^]?
// * [ ] integrated Amazon?
* [ ] integrated link:https://knowledge.plentymarkets.com/en/quick-start/quick-start-ebay[eBay^]?
* [ ] set up your link:https://knowledge.plentymarkets.com/en/quick-start/quick-start-online-store[online store^]?
* [ ] set up link:https://knowledge.plentymarkets.com/en/quick-start/quick-start-setting-up-payment-processing[payment processing^]?
* [ ] prepared link:https://knowledge.plentymarkets.com/en/quick-start/quick-start-preparing-order-processing[order processing^]?
* [ ] link:https://knowledge.plentymarkets.com/en/quick-start/quick-start-automating-processes[automated^] your processes?

[#20]
== Unlocking the online store

Now you are almost done. At the beginning of this quick start, we locked the online store and ensured that all emails would be sent to our own address for testing purposes. Before starting business, we have to revert these settings.

[.instruction]
Deactivating the test mode:

. Go to *System » System settings » Client » Standard Shop (Standard) » Email » Access data.*
. Select *Inactive* from the test mode drop-down list.
. *Save* the settings.

[.instruction]
Unlocking the online store:

. Go to *System » System settings » Client » Standard Shop (Standard) » Online store » Lock store.*
. Click on *Unlock online store now*.

*Congratulations! Your store is now online!*

[#30]
== Stay up to date

We constantly work on improving plentymarkets. To make sure you are always well-informed about all updates, we recommend to subscribe to the *Changelog* category in our forum. For this, you first need a forum account.

[.instruction]
Creating an account:

. Go to *System » System settings » Settings » Users » Accounts* » Your user account.
. Click on *Create account*.

[.instruction]
Subscribing to the change log:

. Go to *Support » Forum » Go directly to the forum*. +
→ The forum opens in a new tab.
. Log in with your login details.
. Open your account settings by clicking on your avatar in the upper right corner and clicking on *Settings*.
. Open the *Categories* menu.
. Enter “Version 7” in the *Watched* field and confirm your input with the enter key.
. *Save* the settings.

From now on, you will automatically receive email notifications when a new change log is posted.

[#40]
== More about the manual

As you continue to dive deeper into the plentymarkets system to extend your store, you will probably reference this manual somewhat frequently. There are two ways to navigate it: the navigation tree and the search function. Use the navigation tree on the left to explore the manual or to get an overview of an entire topic. Use the search function to look up specific key words.

[NOTE]
.Versions
====
The manual describes the functionality of plentymarkets systems according to the beta version. However, by default, new systems use the stable version. As a result, some parts of the manual may deviate from your system environment for up to two weeks.

If you want to switch to a different version, open your back end and go to *System » System settings » Client » Standard-Shop (Standard) » Version* for more information.
====

[#50]
== More from plentymarkets

* If you want to add more functionality to your system or online store, go to link:https://marketplace.plentymarkets.com/en[plentyMarketplace^] to check out more plugins.
* You can find news and announcements concerning plentymarkets on our link:https://www.plentymarkets.co.uk/blog/[blog^].
* Ever get stuck? Visit our link:https://forum.plentymarkets.com/[forum^] to receive help and learn useful tips and tricks from our supporters.
* Have a look at our link:https://www.plentymarkets.co.uk/knowledge/video-tutorials/[video tutorials^] if you are more of a visual learner.
* Our consultants will support you with help and advice, just link:https://www.plentymarkets.co.uk/service/system-setup/[make an appointment^].
* Or ask our link:https://www.plentymarkets.co.uk/service/our-partners/[partner agencies^] for professional support when designing your online store.
* Follow us on link:https://www.facebook.com/plentymarkets[Facebook^] and link:https://www.twitter.com/plentymarkets[Twitter^].
