= Setting up payment processing
:lang: en
include::{includedir}/_header.adoc[]
:position: 60
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:url: quick-start/quick-start-setting-up-payment-processing
:id: LKPTJCQ

IMPORTANT: Have you already deactivated the plugin set *standard-shop*? Not yet? Return to <<quick-start/quick-start-online-store-introduction#, Setting up the online store: Introduction>>.

In your Ceres online store, you can offer your customers different payment methods. All payment methods are integrated using the plentymarkets plugin structure. Depending on your individual requirements, you can offer a multitude of payment methods in your online store. +

This page explains how to integrate the payment methods PayPal and Cash in advance in your online store. In addition, we will provide you with information on how to carry out the basic settings that are needed to correctly process payments of all kinds in your plentymarkets system.

[#10]
== Setting up payment methods

In the following, we will introduce the payment methods PayPal and Cash in advance and explain how to offer these payment methods in your online store.

[#20]
=== Setting up PayPal

The PayPal plugin is installed and activated by default in your plentymarkets system. This is shown by the blue globe symbol in the *Plugins » Plugin overview* menu.
To be able to use the PayPal plugin, you need to have a PayPal business account. After setting up a PayPal business account, carry out the following steps to set up the plugin.

[.instruction]
Setting up the PayPal plugin:

. Go to *System » System settings » Orders » Payment » Plugins » PayPal » Account settings*.
. Click on icon:plus-square[role="green"] to add a new PayPal account.
. Enter the email address that you have used to create your PayPal business account.
. Select the option *Live environment*, which activates the business account for payments made by your customers in the online store. +
(icon:map-signs[]) *_Or:_* Select the *Test environment*, which is invisible for customers, and change the setting to the *Live environment* when you finished the setup.
. Activate the option *PayPal PLUS* in case you have activated your PayPal business account for PayPal PLUS.
. Click on *Add*. +
→ You are automatically forwarded to PayPal.
. Carry out the settings as displayed and required by PayPal.
. Click on *Back to plentymarkets*. +
→ You are forwarded to your plentymarkets back end. There, the PayPal Quick setup opens.
. Carry out the desired settings in the PayPal Quick setup. By clicking on the info icons on the right, you can access further information on the individual settings.
. *Save* (icon:save[role="green"]) the settings. +
→ Your PayPal account is set up using the selected settings.

If it becomes necessary to change settings for the PayPal plugin at a later point in time, pay attention to the detailed instruction in the description of the plugin link:https://marketplace.plentymarkets.com/en/plugins/payment/PayPal_4690[here^] in the plentyMarketplace.

[#40]
=== Setting up Cash in advance

With the payment method Cash in advance, your customers are asked to pay the invoice amount via bank transfer during the order process. You only ship the items when you have received payment for the order. As a seller, you are obligated by law to offer your customers a payment method in the online store that is free of additional charges and simple to use. For you as a seller, the Cash in advance plugin does not require you to pay any fees for using the payment method. Thus, we recommend setting up and using this payment method in any case.

[NOTE]
.Default payment method
====
The payment method *Cash in advance* is set as the default payment method for your online store in your plentymarkets system. You can change the default payment method in the *System » System settings » Client » Standard Shop (Standard) » Orders* at a later point in time. However, we recommend keeping the setting as it is.
====

[#50]
==== Carrying out the basic settings

After installing the plugin, you have to carry out further settings to finish the setup process. To do so, proceed as follows.

[.instruction]
Setting up the Cash in advance plugin:

. Go to *System » System settings » Orders » Payment » Plugins » Cash in advance*.
. Select the client *Standard Shop*.
. Carry out the settings according to the information provided in <<table-plugin-cash-in-advance-setup>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-plugin-cash-in-advance-setup]]
.Setting up the payment method *Cash in advance*
[cols="1,3"]
|====
|Setting |Explanation

2+|*Settings*

|*Language*
|Select the language in which the plugin should be set up. All subsequent settings are carried out in the language selected here. We recommend selecting the option *English* if you run your online store in the English language. You can set up additional languages at a later point in time (see the link at the end of this page).

|*Name*
|Enter the name of the payment method as it should be displayed to customers during the checkout process in the online store. The name *Cash in advance* is set here by default.

|*Info page*
|Optional: During the checkout and payment process, a link named “Details” can be displayed next to the name of the payment method. You can use this option to determine if an external or an internal information page containing information on the payment method should be opened when customers click on the link.

|*Info page internal/Info page external*
|Optional: Make sure to select the same option as with the previous setting for the *Info page*. If you have opted for displaying an internal info page before, select the corresponding option here as well. In addition, select the ID of the category in the online store in which the info page should be displayed.

|*Logo*
|We recommend selecting the option *Standard logo* here. Thus, the logo saved in the plugin will automatically be displayed for the payment method Cash in advance during the payment process. To display an individual logo, select the option *Logo URL* and make sure to pay attention to the following option *Logo URL*.

|*Logo-URL*
|If you want to save an individually chosen logo, enter the https URL leading to the logo.

|*Description*
|Enter a descriptive text (150 characters at most) that is displayed for the payment method during the payment process.

|*Countries of delivery*
|Select the countries of delivery for which the payment method should be available. For example, if you only ship orders placed via your online store to Germany, only activate the option *Germany*.

2+|*Display data*

|*Designated use*
|Enter the text that should be displayed as the name for the field containing the designated use on the order confirmation page. The name *Designated use* is set here by default. We recommend adding the element *Order ID %s* in this field. The percentage sign serves as a place holder that displays the individual order ID in the designated use. This way, the payment can be assigned correctly in your plentymarkets system.

|*Show designated use*
|Activate this option to display the designated use for the payment on the order confirmation page.

|*Show bank data*
|Activate this option to display the bank details necessary for transferring the invoice amount on the order confirmation page. This way, the bank details you have saved in the *System » System settings » Settings » Bank* are displayed.
|====

[#60]
==== Determining display options

In the next step, the settings concerning the *Display data* described in <<table-plugin-cash-in-advance-setup>> require some adjustments in your plentymarkets back end. In the following, we will explain the necessary settings for displaying the bank details on the order confirmation page as well as displaying the Cash in advance logo in your online store.

[NOTE]
.Container links
====
The following instructions describe how to link so-called containers so that content is displayed correctly in your online store. Containers are a kind of frame to which certain kinds of content can be linked. You can define in the plugin itself which containers can be used for a plugin. This selection cannot be changed by end users or customers.
====

[.instruction]
Displaying bank details on the order confirmation page:

. Go to *CMS » Container links*.
. From the list, select the *Cash in advance bank details (PrePayment)* area (icon:angle-down[]).
. Activate the container *Order confirmation: Additional payment information*.
. *Save* (icon:save[role="green"]) the settings. +
→ The bank details are displayed on the order confirmation page of your online store.

[.instruction]
Displaying the Cash in advance logo on the home page:

. Go to *CMS » Container links*.
. Select the *Cash in advance icon (PrePayment)* area (icon:angle-down[]).
. Activate the container *Homepage: Payment method container*.
. *Save* (icon:save[role="green"]) the settings. +
→ The logo of the payment method Cash in advance will be displayed on the homepage of your online store.

[#70]
=== Setting up further payment methods

The instructions above described how to set up the payment methods PayPal and Cash in advance. Depending on your wishes and the requirements of your customers, it can make sense to offer further payment methods in the online store at a later point in time. A big selection of further plugins is available in the link:https://marketplace.plentymarkets.com/plugins/payment[Payment^] area of the plentyMarketplace.

[#80]
== Carrying out the basic settings for payments

In addition to setting up the plugins for the payment methods, you have to carry out settings in your plentymarkets back end to make sure that payments are booked and processed correctly in your system. In addition, saving your VAT number is mandatory.

[#90]
=== Determining rules for incoming payments

For incoming orders to be processed as desired, carry out the settings concerning goodwill on payment and importing customer bank details.

[.instruction]
Determining rules for incoming payments:

. Go to *System » System settings » Orders » Payment » Incoming*.
. Carry out the settings according to the information provided in <<table-basic-settings-incoming-payment>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-basic-settings-incoming-payment]]
.Carrying out basic settings for incoming payments
[cols="1,3"]
|====
|Setting |Explanation

|*Match for automatic assignment*
|Select a value between *0.7* (no exact match required for assignment) and *1.0* (exact match required). If this value is set to a higher value, automatic matching of payments may not work properly in your plentymarkets system. Thus, a value of *0.7* is set here by default.

|*Goodwill on payment*
|To avoid faulty payments due to internally calculated order sums (starting from the third decimal place), you should enter a minimal value of *0.01*. This means that payments with a deviation of € 0.01 are still booked as complete payments. If you select the value *0.05*, for example, payments that are up to 5 cents short of the original order amount are booked as complete payments.

|*Import customer bank data*
|Select whether or not the customer's *bank data* should be *imported* and saved in the respective  data record of the customer or not. +
*_Important:_* Because bank details can only be imported and saved after customers have agreed to the process, *No* is selected here by default. Before activating the option *Yes*, familiarise yourself with the current legislation as well as the existing GDPR regulations.

|*Only assign incoming PayPal payment to corresponding eBay listing if attached to the payment*
|We recommend setting this option to *Yes* in any case if you are using eBay listings in combination with the payment method PayPal. If an eBay listing ID is attached to a PayPal ID and the option is activated, the payment is assigned to the exact order that has the respective eBay listing ID.
|====

[#100]
=== Saving a VAT number

The legally determined VAT rates of 19% and 7% are already set by default for the location Germany. In addition, indicating your VAT number is mandatory according to tax regulations. Proceed as described below to save a VAT number for your location.

[.instruction]
Saving a VAT number:

. Go to *System » System settings » Client* » _Select client_ » *Locations* » _Select location_ » *Accounting*.
. Open the *VAT rates* tab.
. Enter your VAT number in the *VAT number* field.
. *Save* (icon:save[role="green"]) the settings.

[IMPORTANT]
.Locations and tax settings
====
The settings on VAT rates and all other options in the *Accounting* tab depend on the selected location. This means that you have to submit the correct VAT rates for each additional delivery country outside the country in which you are located. In case of any questions or insecurities, we generally recommend consulting your tax advisor. For information on further possible accounting settings, pay attention to the links at the end of this page.
====

[#110]
== Check list

Work through the check list in order to review your settings for preparing payment processing.

[%interactive]

* [ ] Did you <<#20, set up>> the PayPal plugin?
* [ ] Did you <<#30, deactivate>> the PayPal plugin in case you do not want to offer this payment method in the online store?
* [ ] Did you <<#50, set up>> the Cash in advance plugin?
* [ ] Did you <<#60, select the appropriate containers>> so that all information regarding the Cash in advance plugin are displayed in the online store?
* [ ] Did you determine the rules for <<#90, incoming payments>>?
* [ ] Did you save your <<#100, VAT number>>?
* [ ] Did you discuss possible questions regarding <<#100, tax settings>> with your tax advisor?

[#120]
== More about payment processing

* <<orders/accounting#, Accounting>>
* <<payment/managing-payments#, Managing payments>>
* <<payment/managing-bank-details#63, Saving the customer’s bank details>>
* <<payment/best_practices_paypal#, Best Practices: PayPal-Plugin>>
* link:https://marketplace.plentymarkets.com/en/plugins/payment/paypal_4690[Further information on the PayPal plugin in the plentyMarketplace^]
* link:https://marketplace.plentymarkets.com/en/plugins/payment/PrePayment_4758[Further information on the Cash in advance plugin in the plentyMarketplace^]

TIP: Continue with <<quick-start/quick-start-shipping-options#, setting up shipping options>>
