= Adding plugins to the system
:lang: en
include::{includedir}/_header.adoc[]
:position: 120
:url: quick-start/quick-start-adding-plugins-to-the-system

IMPORTANT: Have you already created document templates for invoices and reversal documents? Not yet? Return to <<quick-start/quick-start-preparing-order-processing, preparing order processing>>.

As you have already seen, you can extend the functionality of your online store by using plugins. Some plugins are installed on your system by default, but there are many more ways to customise plentymarkets. To illustrate this, we are going to add a new plugin to the system, install it and set it up.

This new plugin will give customers the opportunity to rate the items we offer in our shop. It will also show this feedback to other potential customers. We can accomplish this with the Customer feedback plugin. You can get this plugin for free on plentyMarketplace.

[.instruction]
Adding plugins to the system:

. Go to *Plugins » Plugin overview*.
. Click on *plentyMarketplace*. +
→ The marketplace opens in a new tab.
. Use the search to find the Customer feedback plugin. +
→ The search results are displayed.
. Click on the Customer feedback plugin. +
→ The item detail view opens.
. Click on *Go to checkout*. +
→ The purchase view opens.
. Accept the GTC by checking the box.
. Click on *Order now*. +
→ A message confirms the purchase. A few minutes later, the plugin will appear as an uninstalled plugin in your system.

[TIP]
.Setup methods
====
The item detail view of each plugin describes how to set it up. For the purposes of this quick start, we will also take a look at all necessary settings below.
====

Let us install our new plugin now. The procedure is the same as when you installed the Cash in advance plugin in the previous chapter.

[.instruction]
Installing the Customer feedback plugin in a set:

. If you are not still in this menu, go to *Plugins » Plugin overview*.
. Adjust the filter options and *Search* for *Not installed* plugins.  +
→ You will see a list of all plugins not currently installed in this set.
. In the *Customer feedback* row, click on *Install plugin* in the *Action* column. +
→ A new window opens, allowing you to select the version you want to install. Click on *Install*. +
→ The plugin is installed and is then available in the plugin overview of the plugin set. The overview shows all currently installed plugins.

Once the plugin has been installed, you can start setting it up. However, first we have to activate the plugin, so that it we can actually use it in our online store later on.

[.instruction]
Activating Customer feedback in the set:

. In the Customer feedback row, click on *Inactive* in the *Active* column. +
→ The plugin is activated.

Let us now have a look at the settings. In some cases, like *Cash in advance*, the settings are carried out in the system menu. In others, like *Customer feedback*, you have to carry out the settings directly in the plugin overview.

[.instruction]
Setting up Customer feedback:

. Click on the Customer feedback plugin. +
→ The plugin detail view opens. The *Configuration* tab is already open.
. Select the options *Release feedbacks automatically*, *Show date for the feedback* and *Allow adding feedbacks only if the item was purchased*.
. *Save* the settings.

This way, customers can give feedback for an item after purchasing it. If another customers view the same item, the feedback will be displayed automatically.

Finally, we have to ensure that the feedback is actually visible in our online store. This means we have to create some container links.

[.instruction]
Setting up container links:

. Go to *CMS » Container links*.
. Open the drop-down list *Feedback Javascript (Feedback)*.
. Select *Script loader: Register/load JS*. 
. Open the drop-down list *Feedback CSS (Ceres) (Feedback)*.
. Select *Template: Style*. 
. Open the *Feedback ratings (Feedback*) drop-down list.
. Select *Single item: Container for customer feedback*. 
. Open the *Feedback category ratings (Feedback*) drop-down list.
. Select *Category item list: Before prices container*. 
. *Save* the links.

This concludes the setup. Now customers can rate items after purchasing them. In the next chapter, we will return to one of the default plugins: Ceres. You can use this plugin to change the design of your online store.

== More about plugins

* <<plugins#, Managing plugins>>
* link:https://marketplace.plentymarkets.com/en[plentyMarketplace^]

TIP: Continue with <<quick-start/quick-start-ebay#, eBay>>
