= System requirements
:lang: en
include::{includedir}/_header.adoc[]
:position: 20

This page lists the requirements that your hardware and internet connection need to fulfil if you wish to use plentymarkets.

[#10]
==  Required hardware, operating systems and browsers

<<table-general-requirements>> requirements allow you to work efficiently with plentymarkets. The system’s performance may be limited if you do not meet the specified values. You may experience permanent performance problems if you are using old hardware or a PC that has been poorly maintained. These requirements are for plentymarkets version 6 and higher.

[[table-general-requirements]]
.Requirements
[cols="1,3"]
|====
| |Requirement

|**Processor**
|2 x 2 GHz +
If you are working with a Windows operating system, you need at least an Intel Core 2 processor.

|**Memory**
|6 GB

|**Resolution**
|1280 x 720

|**Internet connection**
|We recommend a permanent DSL Internet connection with data transfer rates of at least 1000 kB. +
*_Note:_* The transfer rate should match the number of users.

|*Operating system*
a| * 64 bit
* Windows 7 or higher
* Mac OS X 10.10 or higher
* Linux

The performance may be limited if you are using other operating systems, server operating systems or virual machines.

|*Browser*
a|
* link:http://www.google.com/chrome/[Google Chrome^] Version 46 or higher
* link:http://www.mozilla.com/[Mozilla Firefox^] Version 43 or higher

*_Note:_* These browser requirements do not apply to your customers. Your customers can use a W3C compliant web browser of their choice in order to purchase items in your store.
|====

[#20]
== Using the plentymarkets app

The plentymarkets app allows you to access key values and search customer, item and order data. You need a mobile Android or iOS device for these functions. In addition, the plentymarkets app allows you to perform stock management tasks and to use the point of sale system plentymarkets POS. The hardware requirements for these functions are listed below.

[#30]
=== Managing business data with the plentymarkets app

If you want to use the plentymarkets app to manage business data and do not want to operate a POS or manage stock, all you need is a mobile Android or iOS device. <<table-requirements-plenty-app>> lists the hardware requirements for the plentymarkets app if you want to access key values and other business data only.

[[table-requirements-plenty-app]]
.Managing business data with the plentymarkets app
[cols=""]
|====
|Requirements |App download

|Android devices with OS version 4.2.2 or higher
|link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=en[plentymarkets App in Google Play^]

|iOS devices with version 8 or higher
|link:https://itunes.apple.com/app/plentymarkets/id957702618[plentymarkets App in iTunes^]
|====

[#40]
=== Managing stock with the plentymarkets app

<<table-stock-app>> shows recommended hardware for managing stock with the plentymarkets app.

[[table-stock-app]]
.Stock management with the plentymarkets app
[cols="1,3"]
|====
|Hardware |Where to buy in Germany

|HM3 SM10 Mobile Computer +
(Android 5.1)
|link:https://www.sundsits.de/M3SM10-Mobile-Computer-WiFi-und-LTE[www.sundsits.de/M3SM10-Mobile-Computer-WiFi-und-LTE^] +

SundS ITS +
Beselerstr. 2-6 +
50354 Hürth +
Germany +
info@sundsits.de +
Phone: +49(0)2233-7064010 +
Fax: +49(0)2233-7064011 +
link:https://www.sundsits.de[www.sundsits.de^]

|Honeywell Dolphin 75e +
(Android 4.4.4)
|link:http://www.globos.de/produkte/honeywell-dolphin-75e-mobilecomputer[www.globos.de/produkte/honeywell-dolphin-75e-mobilecomputer^]

GLOBOS Logistik- und Informationssysteme GmbH +
Ahrensburger Straße 1 +
30659 Hannover +
Germany +
vertrieb@globos.de +
Phone: +49 (511) 76920-0 +
Fax: +49 (511) 76920-250 +
link:http://www.globos.de[www.globos.de^]
|====

[#50]
== Using plentymarkets POS

The point of sale system plentymarkets POS is an optional component of the plentymarkets app. However, please note that there are additional hardware requirements for using plentymarkets POS. <<table-requirements-POS>> shows the hardware that plentymarkets POS supports. The table also shows the devices on which plentymarkets tests new releases before publication.

[[table-requirements-POS]]
.Supported hardware for plentymarkets POS
[cols="1,2,2"]
|====
|Device type |General requirements |Tested devices

|**Operating systems**
a|
* Android devices with OS version 4.2.2 and higher, ARM processor and device classes Small, Normal, Large and X-Large. You can find out the DPI of a mobile device e.g. link:http://dpi.lv/[here^].
* iOS devices (iPad, iPhone, iPod) with OS version 8 and higher +
→ There are some limitations regarding the use of Bluetooth scanners on iOS devices. +
→ POS with location in Austria can be operated on Android devices only.

a|For every regular release

* Elo Touch Solutions I-Series 15I1 - E021201
* Advantech UPOS-211 sundsits edition
* Honeywell Dolphin 75e (Android 4.4.4)
* M3 SM10 (Android 5.1)
* Samsung Galaxy Tab A 6 - SM-T580
* Apple iPad Air 2

Regularly

* Samsung Galaxy Tab A - SM-T555
* Samsung Galaxy Tab 4 - SM-T530
* Apple iPad Mini Retina

Selectively

* Samsung Galaxy S4
* Apple iPhone 6
* Apple iPad Mini

|**Receipt printer**
a|
* ePos-Print API
* Printers with LAN or WLAN only
a|
* EPSON TM-M30
* EPSON TM-T88V-i (QR code printing)

|**Scanners**
a|
* Scanners with USB or Bluetooth only
a|
* Inateck BCST-10 (Bluetooth)
* Albasca USB hand scanner MK-1000 (untested but used by several customers)

|**Customer displays**
a|
* In combination with receipt printer EPSON TM-M30 only
a|
* EPSON DM-D30

|**Card terminals**
a|
* Requires a payment provider contract
a|
* Ingenico iPP480 with printer (operating mode **ZVT**, connection type **TCP/IP**) - requires the link:https://marketplace.plentymarkets.com/en/plugins/payment/ingenicozvt_5140[Ingenico ZVT plugin^]
* Verifone H5000 with printer (operating mode **ZVT**, connection type **TCP/IP**) - requires the link:https://marketplace.plentymarkets.com/en/plugins/payment/VerifoneZVT_5504[Verifone ZVT plugin^]
* CCV VX 680 with printer (operating mode **ZVT**, connection type **TCP/IP**) - requires the link:https://marketplace.plentymarkets.com/en/plugins/payment/VerifoneZVT_5504[Verifone ZVT plugin^]
* SumUp Air - requires the link:https://marketplace.plentymarkets.com/en/plugins/payment/sumup_5141[SumUp plugin^] +
**__Note:__** You need to activate access to location (geolocation positioning) on the mobile device on which the plentymarkets app is installed to use the SumUp Air with plentymarkets POS.
|====

[#60]
== Troubleshooting

The following points can cause problems if you are working with plentymarkets.

* Your Browser is not up-to-date. Check your browser's version. If a newer version is available, update your browser.
* Your CPU is busy. If your CPU is already running at full capacity due to normal operating procedures, then you should close programmes that you do not need at the time.
* Your PC’s memory is too small. Check the size of your memory. We recommend a minimum capacity of 4 GB.
* Your Java version is not up-to-date. Check the Java version installed on your computer and if a later version exists. Install the current version.
* Your hard drive is more than 70% full and has not been switched out in years. Depending on the operating system and the quality of the hardware, you will notice a significant decrease in performance after two years. Delete any unnecessary files or reinstall the system. Another cost-effective solution would be to purchase a newer and more powerful hard drive/SSD.

 
