= Daten importieren
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Daten importieren, Datenimport, ElasticSync, Sync, Elastic Sync, Sync, Synchronisieren, Synchronisation, Datenformat, Datenformate, dynamischer Import, Abgleich, Importoptionen, Zuordnung, Importdaten, Sync-Verlauf
:description: Erfahren Sie, wie Sie Datenformate erstellen und den dynamischen Import nutzen.
:position: 20

Diese Handbuchseite befasst sich mit den verschiedenen Möglichkeiten des Datenimports in plentymarkets. Insbesondere die Möglichkeiten des ElasticSync-Plugins werden erläutert. ElasticSync erlaubt sowohl einmalige manuelle Importe als auch regelmäßige automatisierte Importe.
Außerdem werden die Möglichkeiten des manuellen Datenimport per dynamischen Import beschrieben. Ein Import von Daten ist ratsam, wenn Sie z.B. neue Artikel, Kundendaten oder Lagerbestände in Ihr plentymarkets System einpflegen möchten und die Daten bereits digital vorliegen.

[#1000]
== Daten per ElasticSync importieren

ElasticSync ermöglicht es über das Erstellen von sogenannten Syncs, Datenimporte auszuführen. Ein Import kann manuell oder automatisiert erfolgen. Das ElasticSync-Plugin steht Ihnen kostenlos im link:https://marketplace.plentymarkets.com/plugins/integration/ElasticSync_4750[plentyMarketplace^] zur Verfügung.

[#1100]
=== Allgemeine Beschreibung: Daten per Sync importieren

Die grundsätzliche Funktionsweise zum Erstellen und Importieren eines Syncs ist für alle Sync-Typen gleich und wird hier einmal übergreifend beschrieben. Anschließend folgt für jeden Sync-Typ zusätzlich eine detaillierte Beschreibung.

[#1200]
==== Sync erstellen

Syncs erstellen, bearbeiten und verwalten Sie im Menü **Daten » ElasticSync**. Hier sehen Sie eine Übersicht aller Syncs. Ein Sync dient dazu, die Daten einer per FTP oder HTTP zugänglichen Datei Daten in plentymarkets zuzuordnen und zu importieren. Beim Erstellen des Syncs speichern Sie Informationen zur Datenquelle. Wichtig für einen Sync ist außerdem, dass Sie Daten für den Abgleich festlegen und zuordnen, welche Daten Ihrer Datei welchen Daten in plentymarkets entsprechen. Mit dem Abgleich bestimmen Sie, anhand welcher Daten versucht wird zu identifizieren, ob bereits ein Datensatz besteht oder nicht. Mit der Zuordnung legen Sie fest, welche Spalte Ihrer Datei welchem Datenfeld in plentymarkets entspricht. Am Ende legen Sie ein Importintervall fest. Gehen Sie wie im Folgenden beschrieben vor, um einen Sync zu erstellen.

[NOTE]
.Importintervall am Ende einstellen, damit nicht vorzeitig ein Sync ausgeführt wird
====
Stellen Sie das Importintervall am Ende ein, damit nicht schon ein Sync ausgeführt wird, während Sie noch Abgleich- oder Zuordnungseinstellungen vornehmen.
====

[.instruction]
Sync erstellen:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Klicken Sie auf *Sync hinzufügen*. +
    → Der Bearbeitungsbereich *Neuer Sync* wird angezeigt.
. Nehmen Sie Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-sync-erstellen>>.
. *Speichern* Sie die Einstellungen. +
    → Der Sync wird erstellt und die Abgleicheinstellungen des Syncs werden geöffnet.

[[tabelle-sync-erstellen]]
.Sync erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Grunddaten

|*Name*
|Name eingeben. Dieser Name wird in der Übersicht angezeigt und kann für die Suche genutzt werden.

|*Typ*
a|Typ aus Dropdown-Liste wählen.

* *Kontakte, Firmen und Adressen* = Wählen, um <<basics/datenaustausch/daten-importieren#2200, Kontakt-, Firmen- und Adressdaten>> zu importieren.
* *Artikel* = Wählen, um <<basics/datenaustausch/daten-importieren#1900, Artikeldaten und Variantendaten>>  zu importieren.
* *Kategorien* = Wählen, um <<basics/datenaustausch/daten-importieren#2100, Kategoriedaten>> zu importieren.
* *Attribute* = Wählen, um Attributdaten zu importieren.
* *Merkmale* = Wählen, um Merkmaldaten zu importieren.
* *Notizen* = Wählen, um Notizdaten zu importieren.
* *Auftrag* = Wählen, um <<basics/datenaustausch/daten-importieren#2000, Auftragsdaten>> zu importieren.
* *Warehouse* = Wählen, um Lagerorte zu importieren.
* *Eigenschaften* = Wählen, um Eigenschaften zu importieren.

2+|Import

|*Datentyp*
|Dateiformat der Importdatei wählen. +
Aktuell ist jedoch nur die Auswahl *CSV* verfügbar, da nur CSV-Dateien importiert werden können.

|*Zeichensatz*
|Zeichensatz oder die Option *Automatisch erkennen* wählen.

|*Beginne ab Zeile*
|Wählen, ab welcher Zeile der Datei Daten importiert werden sollen.

|*Kopfzeile enthalten*
|Wählen, ob die Importdatei eine Kopfzeile enthält.

2+|Trennzeichen

|*Trennzeichen*
|Trennzeichen wählen, das in der Importdatei verwendet wird, um die Datenfelder (Spalten) eines Datensatzes voneinander zu trennen.

|*Feldbegrenzungszeichen*
a|Begrenzungszeichen innerhalb von Feldern wählen, die mehrere Werte enthalten können.

* " = einzelne Werte innerhalb eines Feldes sind durch doppelte Anführungszeichen voneinander getrennt.
* ' = einzelne Werte innerhalb eines Feldes sind durch einfache Anführungszeichen voneinander getrennt.


2+|Quelle

|*Quelle*
a|*FTP* oder *HTTP* wählen. +
Je Option werden weitere Einstellungen sichtbar:

*FTP* = Host, Port, Benutzername, Passwort und Dateiname werden als Einstellungen sichtbar.

    * *Host* = Host des FTP-Servers eingeben. +
      *_Tipp:_* plentymarkets FTP-Zugang nutzen.
    * Port = Port des FTP-Servers. Wenn kein Port eingetragen ist, wird der Standard-Port (22) verwendet.
    * *Benutzername* = Benutzer für FTP-Zugang eingeben.
    * *Passwort* = Passwort für FTP-Zugang eingeben.
    * *Dateiname* = Pfad und Name der Datei eingeben, aus der Daten importiert werden sollen.
    * *Datei nach erfolgreichem Import in Archiv verschieben* = Wenn diese Option aktiv ist, wird nach erfolgreichem Import die Importdatei automatisch in einen neuen Ordner *Archiv* auf dem FTP-Verzeichnis verschoben.

[NOTE]
.Wildcards im Dateinamen nutzen
====
Sie können Wildcards imdem Feld *Dateiname* verwenden, in dem Sie z.B. einen Teil des Dateinamens durch ein *** ersetzen. Verwenden Sie Wildcards mit der Option *Datei nach erfolgreichem Import in Archiv verschieben*.
====

*HTTP* = *Externe URL* oder *Dateiupload* aus der Dropdown-Liste *HTTP-Optionen* wählen.

    * *Externe URL*: URL eingeben, unter der die Importdatei erreichbar ist. +
     *_Tipp:_* Datei auf plentymarkets Webspace speichern.
      * Authentifizierung: Wählen, ob für den Zugriff auf die Datei eine Authentifizierung erforderlich ist oder nicht.
        ** *keine* = keine Authentifizierung erforderlich
        ** *HTTP-Authentifizierung* = Authentifizierung per Benutzer und Passwort erforderlich
    * Dateiupload: lokale Datei hochladen +
    *_Wichtig:_* Die Datei wird auf einem öffentlichen Bucket auf S3 gespeichert. Jeder, der die URL zu der Datei kennt, kann somit auf die Datei zugreifen.
|====



[#1300]
==== Importoptionen festlegen

Die Importoptionen befinden sich im Untermenü *Abgleich*. Die Importoptionen gelten sowohl für den Abgleich als auch für die Zuordnung.

[.instruction]
Importoptionen festlegen:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Klicken Sie in der Sync-Übersicht auf den Sync. +
→ Die Abgleichoptionen des Syncs werden angezeigt.
. Legen Sie die Importoptionen fest. Beachten Sie dazu die Erläuterungen in <<tabelle-Sync-Importoptionen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-Sync-Importoptionen]]
.Importoptionen für Syncs
[cols="1,2"]
|====
|Importoption |Erläuterung

|*Wenn keine Daten gefunden wurden*
a|*Überspringen* oder *Erstellen* wählen.

* *Überspringen* = Wenn anhand der Abgleichfelder keine übereinstimmenden Daten gefunden werden, wird der Datensatz nicht importiert.
* *Erstellen* = Wenn anhand der Abgleichfelder keine übereinstimmenden Daten gefunden werden, wird ein neuer Datensatz, z.B. ein neuer Artikel oder ein neuer Auftrag, hinzugefügt.

|*Dezimalzahl*
a|*Deutsche Schreibweise* oder *Englische Schreibweise* wählen.

* *Deutsche Schreibweise* = Dezimalzahlen werden kommasepariert angegeben und ein Punkt dient als Tausendertrennzeichen.
* *Englische Schreibweise* = Dezimalzahlen werden punktsepariert angegeben und ein Komma dient als Tausendertrennzeichen.

|*Datumsformat*
|Datumsformat eingeben. Wenn die Datumsangaben in der Datei dem Standardformat Y-m-d H:i:s entsprechen, müssen Sie nichts eingeben. Andere Formate müssen eingetragen werden. Zulässig sind alle link:http://php.net/manual/de/function.date.php[php-konformen Datumsformate^].

|====

[#1400]
==== Abgleich festlegen

Nachdem Sie einen Sync erstellt haben, öffnen Sie ihn nun, um weitere Einstellungen vorzunehmen. Zunächst wählen Sie die Felder, die zum Abgleichen der Daten verwendet werden sollen. Legen Sie außerdem fest, was passieren soll, wenn durch den Abgleich keine bestehenden Daten gefunden werden.

[NOTE]
.Abgleich ist optional
====
Bei den Abgleichfeldern handelt es sich um optionale Einstellungen. Wenn Sie kein Abgleichfeld wählen, können die Daten Ihrer Datei keinen bestehenden Daten in Ihrem System zugeordnet werden. Sie können eins, mehrere oder alle Abgleichfelder festlegen. Die angezeigten Abgleichfelder unterscheiden sich für jeden Sync-Typ.
====

[.instruction]
Abgleich festlegen:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Klicken Sie in der Sync-Übersicht auf den Sync. +
→ Die Abgleichoptionen des Syncs werden angezeigt.
. Nehmen Sie die Einstellungen vor.
. *Speichern* Sie die Einstellungen.

[#1500]
==== Zuordnung erstellen

Mithilfe einer Zuordnung legen Sie fest, welche Spalte Ihrer Datei welchem Datenfeld in Ihrem System entspricht. Ohne Zuordnung können keine Daten importiert werden.

[.instruction]
Zuordnung festlegen:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Klicken Sie in der Sync-Übersicht auf den Sync. +
→ Die Abgleichoptionen des Syncs werden angezeigt.
. Klicken Sie auf *Zuordnung*. +
→ Eine Übersicht der Zuordnung wird angezeigt. Zunächst ist die Liste leer.
. Klicken Sie auf *Zuordnung hinzufügen*.
. Geben Sie einen Namen für die Zuordnung ein.
. Geben Sie optional eine Position für die Zuordnung ein.
. *Speichern* Sie die Einstellungen. +
→ Die Zuordnung wird der Übersicht hinzugefügt.
. Öffnen Sie eine Zuordnung. +
→ Die verfügbaren Zuordnungsfelder unterscheiden sich je nach Sync-Typ.
. Wählen Sie Datenfelder für die Zuordnung aus, indem Sie Häkchen bei diesen Feldern setzen. +
→ Die gewählten Datenfelder werden zur Zuordnung hinzugefügt.
. Wählen Sie für jedes Datenfeld eine Spalte aus Ihrer Datei oder die Option *Eigener Wert*.
. *Speichern* Sie die Einstellungen.

[NOTE]
.Eigener Wert
====
Die Option *Eigener Wert* erlaubt Ihnen für ein Datenfeld einen festen Wert zu importieren. Dieser feste Wert ist somit für jeden Datensatz, der durch diesen Sync importiert wird, gleich.
====

[#1600]
==== Importdaten eingrenzen

Mithilfe von Filtern können Sie die Daten eingrenzen, die importiert werden. Die Filter finden Sie im Bereich Zuordnung.

[NOTE]
.Mehrere Filter sind durch Und verknüpft
====
Wenn Sie mehrere Filter verwenden, werden nur Datensätze importiert, auf die alle Filter zutreffen. Es handelt sich also um eine Und-Verknüpfung der Filter.
====

[.instruction]
Filter hinzufügen:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Klicken Sie in der Sync-Übersicht auf den Sync. +
→ Die Abgleichoptionen des Syncs werden angezeigt.
. Klicken Sie auf *Zuordnung*. +
→ Eine Übersicht der Zuordnung wird angezeigt.
. Öffnen Sie eine Zuordnung.
. Klicken Sie in der Symbolleiste auf *Filter*.
. Wählen Sie die Spalte aus Ihrer Datei, die Sie filtern möchten.
. Wählen Sie einen Operator.
. Geben Sie einen Wert ein.
. Klicken Sie auf *Filter hinzufügen*. +
→ Der Filter wird gespeichert und Sie können weitere Filter hinzufügen.

[#1620]
=== Sync-Logs einsehen

Für jeden ausgeführten Sync werden Log-Einträge angelegt, die Sie einsehen können.

[.instruction]
Sync-Logs einsehen:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Klicken Sie auf *Logs*. +
→ Die Logs der Syncs werden angezeigt.

[#1630]
=== Sync kopieren

Sie können Syncs einzeln oder mehrere gleichzeitig kopieren. So können Sie bereits gut konfigurierte Syncs nutzen, um schnell einen neuen Sync anzulegen.

[.instruction]
Sync kopieren:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Markieren Sie ein oder mehrere Syncs.
. Klicken Sie auf *Sync kopieren*. +
→ Der Sync wurde kopiert. Einem kopierten Sync wird *(copy)* hinzugefügt.

[#1640]
=== Sync exportieren und importieren

Syncs können importiert und exportiert werden. So können Sie sowohl Syncs lokal sichern als auch Syncs von anderen Nutzern importieren.

[.instruction]
Sync exportieren und importieren:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Markieren Sie ein oder mehrere Syncs.
. Klicken Sie auf *Sync exportieren*. +
→ Der Sync wird automatisch heruntergeladen.
. Klicken Sie auf *Sync importieren*. +
→ Die Option *Sync importieren* wird unterhalb des Menü aufgeklappt.
. Klicken Sie auf *Datei wählen*. +
→ Das Datei-Browser wird geöffnet.
. Klicken Sie auf *Datei hochladen* und wählen Sie die Datei aus.
. Markieren Sie die Datei im Datei-Browser und klicken Sie auf *wählen*. +
→ Die Datei wird hinzugefügt.
. Klicken Sie auf *Import*. +
→ Der Sync wird importiert.

[NOTE]
.Syncs aus einem anderen plentymarkets System importieren
====
Wenn Sie Syncs aus einem anderen plentymarkets System importieren, müssen Sie Ihren Abgleich und die Zuordnung anpassen. Es können nur *.json* Dateien importiert werden.
====

[#1700]
=== Sync testen und Daten importieren

Sie können einen Sync testen und ausführen. Das Testen erlaubt es Ihnen schnell festzustellen, ob Ihre Datei korrekt importiert werden kann.

[NOTE]
.Syncs testen
====
Wenn Sie *Sync testen* wählen, werden nur die ersten zehn Zeilen der Importdatei importiert.
====

[#1710]
=== REST-API

Um ElasticSync per REST-API anzusprechen stehen Ihnen die folgenden Rest calls zur Verfügung:

* Sync anlegen: POST - /rest/elasticsync/sync/{syncId}/import
* Alle Syncs abrufen: GET - /rest/elasticsync/all_syncs

[#1900]
=== Sync vom Typ Artikel einrichten

Mit Syncs des Typs *Artikel* importieren Sie Artikel- und Variantendaten.

Erfahren Sie mehr zum Importieren neuer Artikel im folgenden Videotutorial:

.Artikel per ElasticSync importieren
video::219060209[vimeo]

Um Artikeldaten per ElasticSync zu importieren, müssen die folgenden Datensätze in plentymarkets vorhanden sein:

* Kategorien (Menü *Artikel » Kategorien*)
* Verkaufspreise (Menü *System » Artikel » Verkaufspreise*)

Um Variantendaten mit Attributen per ElasticSync zu importieren, müssen die folgenden Datensätze in plentymarkets vorhanden sein:

* Attribute und Attributwerte (Menü *System » Artikel » Attribute*)

[#1910]
==== Felder für den Artikelabgleich

In <<tabelle-Abgleichfelder-Artikel>> werden Felder erläutert, die für den Abgleich von Artikeldaten zur Verfügung stehen. Anhand des gewählten Feldes wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Abgleichfelder-Artikel]]
.Abgleichfelder für Artikelimport
[cols="1,2"]
|====
|Abgleichfeld |Erläuterung

|Varianten-ID
|

|Variantennr.
|

|Externe Varianten-ID
|

|Barcode
|Aus der zweiten Dropdown-Liste den Barcode-Typ des Barcodes wählen.

|Artikel-ID
|Bei Varianten mit Attributen dieses Feld nur in Kombination mit Attributauswahlkombination nutzen.


|Attributauswahlkombination
|Bei Varianten mit Attributen dieses Feld nur in Kombination mit Artikel-ID nutzen.
Aus der zweiten Dropdown-Liste das Format wählen, in dem die Daten in der Datei vorliegen.

|Lieferanten-Artikel-Nr.
|

|====

[#1920]
==== Felder für die Artikelzuordnung

In <<tabelle-Zuordnungsfelder-Artikel>> werden Felder erläutert, die für den Abgleich von Artikeldaten zur Verfügung stehen. Anhand des gewählten Feldes wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Zuordnungsfelder-Artikel]]
.Abgleichfelder für Artikelimport
[cols="1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

3+|Artikel

|Typ
|0 = Lagerware +
1 = Produktionsware +
2 = Colli +
3 = Bestellware
|

|Shop-Aktion
|0 = keine +
1 = Sonderangebot +
2 = Neuheit +
3 = Top-Artikel
|

|Eigner
|Nummerisch (interne User-ID)
|

|Hersteller-ID
|Nummerisch (interne ID)
|

|Herstellerland
|Nummerisch (interne ID); +
0 = unbekannt
|

|Zolltarifnummer
|Nummerisch
|

|Erlöskonto
|
|

|Aktionsgutschein
|0 = Möglich +
1 = Verboten +
2 = Nur mit Gutschein kaufbar
|

|Zustand
|0 = Neu +
1 = Gebraucht +
2 = Neu und originalverpackt +
3 = Neu mit Etikett +
4 = B-Ware
|Artikelzustand

|Zustand API
|0 = Neu +
1 = Gebraucht wie neu +
2 = Gebraucht sehr gut +
3 = Gebraucht gut +
4 = Gebraucht annehmbar +
5 = B-Ware
|Zustand des Artikels; Übertragung über API an andere Marktplätze

|Abonnement (ja/nein)
|0 = Nein +
1 = Ja
|Kann Artikel als Abo bestellt werden?

|Seriennummer (ja/nein)
|0 = Nein +
1 = Ja
|Seriennummer zuweisen?

|Versandpaket (ja/nein)
|0 = Nein +
1 = Ja
|Versandpaket verwenden?

|Amazon-Abwicklung (FBA)
|0 = Nicht verwenden +
1 = AMAZON EU +
2 = AMAZON FE +
3 = AMAZON NA +
-1 = FBA und SellerCentral
|

|Versand durch Amazon (FBA)
|0 = Nein +
1 = Ja
|FBA-Versand?

|Amazon-Produkttyp
|Nummerisch
|

|Amazon-FEDAS
|
|FEDAS-Warengruppenschlüssel

|Listing-Vorlage
|Nummerisch (interne ID)
|

|Listing Kategorie 1; +
Listing Kategorie 2
|Nummerisch
|

|Listing Shop-Kategorie 1; +
Listing Shop-Kategorie 2
|Nummerisch
|

|Rakuten.de-Kategorien
|Nummerisch (interne ID)
|

|Markierung 1; +
Markierung 2
|
|

|Altersfreigabe
|0 = Keine verfügbar +
3 = FSK 3 +
6 = FSK 6 +
12 = FSK 12 +
16 = FSK 16 +
18 = FSK 18 +
50 = Nicht gekennzeichnet +
88 = Nicht erforderlich +
99 = Noch nicht bekannt
|FSK

|Artikelbewertung
|Nummerisch
|Erstbewertung von 1 bis 5 bzw. 1 bis 10

|Herstellername
|Alphanummerisch
|Wenn nicht im System, wird neuer Hersteller angelegt.

|Artikel löschen
|0 = Nein +
1 = Ja

3+|Artikelbeschreibung (Zuordnung pro Sprache)

|Name
|Alphanummerisch
|

|Name 2; +
Name 3
|Alphanummerisch
|

|Vorschautext
|Alphanummerisch
|

|Meta-Beschreibung
|Alphanummerisch
|

|Artikeltext
|Alphanummerisch
|

|Technische Daten
|Alphanummerisch
|

|URL-Pfad
|Link
|

|Meta-Keywords
|Alphanummerisch
|

3+|Versandprofil

|Versandprofil-ID
|Nummerisch
|

3+|Artikel-Tags

|Tag-ID
|Nummerisch
|

|Tag-Name
|Alphanummerisch
|

|Tag-Namen +
(kommasepariert)
|Alphanummerisch
|Tag-Liste

|Alle verknüpften Tags löschen
|0 = Nein +
1 = Ja
|Alle Verknüpfungen aufheben?

3+|Varianten

|ID
|Nummerisch
|

|Artikel-ID
|Nummerisch
|

|Position
|Nummerisch
|

|Aktiv
|0 = Nein +
1 = Ja
|Ist Variante aktiv, d.h. wird sie im Webshop und ggf. auf Marktplätzen angeboten?

|Variantennr.
|Alphanummerisch
|

|Modell
|Alphanummerisch
|Modellbezeichnung

|Externe Varianten-ID
|Alphanummerisch
|

|Verfügbarkeit
|Nummerisch (interne ID)
|

|EK netto
|Nummerisch
|Einkaufspreis

|Preiskalkulation
|Nummerisch (interne ID)
|

|VPE
|Nummerisch
|Verpackungseinheit; Standard = 1

|Anzahl der Packstücke
|Nummerisch
|

|Einheit der Packstücke
|Nummerisch +
0 = unverpackt +
1 = Ballen +
2 = Behälter +
3 = Bund +
4 = Rollpalette +
5 = Colli +
6 = Container +
7 = Eimer +
8 = Fass +
9 = Flaschen +
10 = Euro Pool Flachpalette +
11 = Gestell +
12 = Gasflasche +
13 = Gitterboxpalette +
14 = Hobbock +
15 = Halbe Palette +
16 = Lebensmittelpalette +
17 = Holzuntersetzer +
18 = IBC Container +
19 = Kanne +
20 = Korbflasche +
21 = Kiste +
22 = Kanister +
23 = Kundenpalette +
24 = Karton +
25 = Kombinationsverpackung +
26 = Pack +
27 = Ring +
28 = Rolle +
29 = Sack +
30 = Stück +
31 = Tank +
32 = Trommel +
34 = Verschlag +
35 = Viertelpalette +
36 = sonstige Paletten +
37 = Kasten +
38 = Einwegpalette +
39 = Folientüte

|Transportkosten netto
|Nummerisch
|

|Lagerkosten netto
|Nummerisch
|

|Zoll
|Nummerisch
|Prozentwert

|Betriebskosten
|Nummerisch
|Prozent

|Umsatzsteuer
|Nummerisch (%)
|

|Paketart
|bundle = Variante ist Paket +
bundle_item = Variante ist Paketbestandteil
|

|Unsichtbar in Artikellisten
|0 = Nein +
1 = Ja
|

|Kommissionierung
|single_picking = Einzelkommissionierung möglich +
no_single_picking = Keine Einzelkommissionierung möglich +
exclude_from_picklist = Von Pickliste ausschließen
|

|WB-Beschränkung
|0 = Keine Beschränkung +
1 = Auf Netto-WB +
2 = Keinen Bestand führen
|

|Webshop: Sichtbar wenn Netto-WB positiv
|0 = Nein +
1 = Ja
|

|Webshop: Unsichtbar wenn kein Netto-WB
|0 = Nein +
1 = Ja
|

|Verfügbar wenn Netto-WB positiv
|0 = Nein +
1 = Ja
|

|Nicht verfügbar wenn kein Netto-WB
|0 = Nein +
1 = Ja
|

|Hauptlager
|Nummerisch (interne ID)
|

|Max. Bestellmenge
|Nummerisch
|

|Min.-Bestellmenge
|Nummerisch
|

|Intervallbestellmenge
|Nummerisch
|

|Grundpreis anzeigen
|0 = Nein +
1 = Ja
|

|Variante löschen
|0 = Nein +
1 = Ja
|

|Nummer der Hauptvariante
|Alphanummerisch
|

|Verfügbar bis
|Datum
|Datum des letzten Tages der Verfügbarkeit

|Erscheinungsdatum
|Datum
|Datum, ab dem die Variante verfügbar ist

|Name
|Alphanummerisch
|Name der Variante

|Gewicht brutto g
|Nummerisch
|

|Gewicht netto g
|Nummerisch
|

|Breite mm
|Nummerisch
|

|Länge mm
|Nummerisch
|

|Höhe mm
|Nummerisch
|

|Portoaufschlag 1; +
Portoaufschlag 2
|Nummerisch

3+|Cross-Selling

|Alle Cross-Selling-Verknüpfungen löschen
|0 = Nein +
1 = Ja
|

|Cross-Selling-Verknüpfungen hinzufügen
|Alphanummerisch im Format +
_Artikel-ID:Beziehungstyp;Artikel-ID:Beziehungstyp;etc._ +
Accessory = Zubehör +
ReplacementPart = Ersatzteil +
Similar = Ähnlich +
Bundle = Artikelpaket
|

|Cross-Selling-Verknüpfungen löschen
|Nummerisch im Format _Artikel-ID;Artikel-ID;etc._
|

3+|Barcodes (Zuordnung pro Barcode-Typ)

|Code
|Alphanummerisch
|

3+|Variantenpreis (Zuordnung pro Verkaufspreis)

|Preis
|Nummerisch
|

3+|Kategorien

|ID der Kategorie
|Nummerisch (interne ID)
|Alternativ Name der Kategorie übergeben.

|Position
|Nummerisch
|

|Ist Neckermann.de Hauptkategorie
|0 = Nein +
1 = Ja
|

|Name der Kategorie
|Alphanummerisch
|Kompletten Kategoriepfad semikolongetrennt angeben (z.B. Schuhe;Unisex)
Alternativ ID der Kategorie übergeben.

3+|Standardkategorien

|ID der Kategorie
|Nummerisch (interne ID)
|

|Automatisch ausgewählt
|N = Nein +
Y = Ja
|

|Name der Kategorie
|Alphanummerisch
|

3+|Bestand

|Lager
|Nummerisch (interne ID)
|Kann nur in Kombination mit Menge und Lagerort übergeben werden.

|Menge
|Nummerisch
|Kann nur in Kombination mit Lager und Lagerort übergeben werden.

|Lagerort
|Nummerisch (interne ID)
|Kann nur in Kombination mit Lager und Menge übergeben werden.

3+|Mandant (Shop) (Zuordnung pro Mandant)

|Aktiv
|0 = Nein +
1 = Ja
|

3+|Märkte (Zuordnung pro Marktplatz)

|Aktiv
|0 = Nein +
1 = Ja
|

3+|Attribute (Zuordnung pro Format)
|Attributauswahlkombination
|Alphanummerisch im Format +
_Attributname:Wertname; oder Attributname<>Wertname<||>_
|Import von mehr als zwei Attributverknüpfungen. +
_*Hinweis:*_ Jede Attributkombination muss pro Variante einzigartig sein.


|Attribute ID
|Nummerisch
|Import von bis zu zwei Attributverknüpfungen. +
_*Tipp:*_ Bei zwei Verknüpfungen müssen die IDs in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine im Format *Attributname<>Wertname<||>* erstellen und die separaten Spalten zuordnen.

|Attribute Name
|Alphanummerisch
|Import von bis zu zwei Attributverknüpfungen. +
_*Tipp:*_ Bei zwei Verknüpfungen müssen die Namen in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine im Format *Attributname<>Wertname<||>* erstellen und die separaten Spalten zuordnen.

|Wert Name
|Alphanummerisch
|Import von bis zu zwei Attributverknüpfungen. +
_*Tipp:*_ Bei zwei Verknüpfungen müssen die Namen in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine im Format *Attributname<>Wertname<||>* erstellen und die separaten Spalten zuordnen.

|Wert ID
|Nummerisch
|Import von bis zu zwei Attributverknüpfungen. +
_*Tipp:*_ Bei zwei Verknüpfungen müssen die IDs in verschiedenen Spalten vorliegen. Eine Zuordnung im Format *Attributname:Wertname;* und eine im Format *Attributname<>Wertname<||>* erstellen und die separaten Spalten zuordnen.

3+|Artikel Bilder

|ID des Bilds
|Nummerisch (interne ID)
|

|Position
|Nummerisch
|

|Dateiname
|Alphanummerisch
|

|Base64 Data
|Alphanummerisch
|

|Verfügbarkeit Mandant (Shop)
|Nummerisch (interne ID)
|*-1* aktiviert alle Mandanten

|Verfügbarkeit Herkünfte
|Nummerisch (interne ID)
|*-1* aktiviert alle Herkünfte

|Verfügbarkeit Listings
|Nummerisch (interne ID)
|*-1* aktiviert alle Listings

|URL
|Link
|

|Name
|Alphanummerisch im Format +
_Name:Sprache1,Name:Sprache2_
|

|Multi-URL (kommasepariert)
|Alphanummerisch im Format +
_image1url;positionImage1,image2url;positionImage2_
|Wenn keine Position übergeben wird, enspricht die Position der Reihenfolge der URLs.

|Bilder löschen
|0 = Nein +
1 = Ja
|1 löscht alle Bilder des Artikels. Bilder, die erhalten bleiben sollen, müssen als URL im Sync angegeben werden.

|Mit Variante verknüpfen
|0 = Nein +
1 = Ja
|1 verknüpft das Bild mit der Variante. +
0 löscht eine vorhandene Verknüpfung.

3+|Merkmale

|ID
|Nummerisch (interne ID)
|

|Wert
|Alphanummerisch
|

|Sprache
|Buchstaben
|Nur bei Text

|Merkmalkombination
|Alphanummerisch
|Kombination aus Backend-Name, Wert und Sprache im Format +
Name1:Wert1:Sprache1;Name2:Wert2:Sprache2 etc.

3+|Inhalt

|Inhalt Einheit
|Nummerisch (interne ID)
|Alternativ *Inhalt Maßeinheit (ISO)* übergeben

|Inhalt Menge
|Nummerisch
|Kann nur in Kombination mit *Inhalt Einheit* oder *Inhalt Maßeinheit (ISO)* übergeben werden.

|Inhalt Maßeinheit (ISO)
|Alphanummerischer ISO-Code
|Alternativ *Inhalt Einheit* übergeben

3+|ASIN/ePID

|Land
|Nummerisch (interne ID)
|

|Typ
|ASIN; ePID
|

|Wert
|Alphanummerisch
|

3+|Lager (Zuordnung pro Lager)

|Zone
|Nummerisch
|

|Lagerorttyp
|none = kein +
small = klein +
medium = mittel +
large = groß +
europallet = Europalette
|

|Meldebestand
|Nummerisch
|

|Maximalbestand
|Nummerisch
|

|Lagerort
|Nummerisch (interne ID)
|

|Bestandspuffer
|Nummerisch
|

3+|Lieferant

|EK
|Nummerisch
|

|Mindestabnahme
|Nummerisch
|

|Lieferanten-Artikel-Nr.
|Alphanummerisch
|

|Letzte Preisabfrage
|Datum
|

|Lieferzeit in Tagen
|Nummerisch
|

|Rabatt
|Nummerisch
|Prozent

|Rabattfähigkeit
|0 = Nein +
1 = Ja
|

|Verpackungseinheit
|Nummerisch
|

|Lieferanten-ID
|Nummerisch
|

|Lieferanten-Name
|Alphanummerisch
|

3+|SKU

|Marktplatz-ID
|Nummerisch
|

|Account-ID
|Nummerisch
|

|SKU
|Alphanummerisch
|

|Parent-SKU
|Alphanummerisch
|

3+|Paket

|Paketbestandteile
|Alphanummerisch
|Varianten-ID:Menge;Varianten-ID:Menge;etc.

|Paketbestandteile löschen
|Alphanummerisch
|Varianten-ID des Paketbestandteils

|Paket löschen
|0 = Nein +
1 = Ja
|

|====

[#1930]
==== Pflichtwerte für Artikel-Sync-Aktionen

<<tabelle-Aktionen-Artikel-Sync>> listet mögliche Aktionen für Syncs des Typs Artikel und erläutert die Werte, die zum Ausführen dieser Aktionen unbedingt angegeben werden müssen.

[[tabelle-Aktionen-Artikel-Sync]]
.Aktionen für Artikel-Sync
|====
|Aktion 	|Erforderliche Werte

2+|Artikelbeschreibung

|Artikelbeschreibung aktualisieren
a|* *Name*

2+|Versandprofil

|Versandprofil aktualisieren
a|* *Versandprofil-ID*

2+|Artikel-Tags

|Alle Tag-Verknüpfungen lösen
a|* *Alle verknüpften Tags löschen* = 1

|Tag verknüpfen
a|Ein Tag:

* *Tag-ID*
oder
* *Tag-Name* +

Mehrere Tags: +

* *Tag-Namen (kommasepariert)*

2+|Varianten

|Variante erstellen
a|
* *ID der Standardkategorie* +
oder
* *Name der Standardkategorie*

|Variante zu Artikel hinzufügen
a|
* *Inhalt Menge*
* *Inhalt Einheit* +
    oder
* *Inhalt Menge*
* *Inhalt Maßeinheit (ISO)*

und

* *Artikel-ID* +
    oder
* *Nummer der Hauptvariante*

Bei Varianten mit Attributen außerdem:

* *Attributauswahlkombination* +
    oder
* *Attribute* (Name oder ID)
* *Wert* (Name oder ID)

|Inhalt aktualisieren
a|
* *Inhalt Menge*
* *Inhalt Einheit* +
oder
* *Inhalt Menge*
* *Inhalt Maßeinheit (ISO)*

2+|Barcodes

|Barcode ändern
a|
* *Code* über Barcode-Zuordnung

2+|Kategorien

|Kategorie verknüpfen
a|
* *ID der Kategorie* +
oder
* *Name der Kategorie*

|Verknüpfung aktualisieren
a|
* *ID der Kategorie* +
oder
* *Name der Kategorie*

2+|Variantenpreise

|Preis ändern
a|
* *Preis über Verkaufspreiszuordnung*

2+|Standardkategorien

|Standardkategorie verknüpfen
a|
* *ID der Kategorie* +
oder
* *Name der Kategorie*

|Standardkategorie aktualisieren
a|
* *ID der Kategorie* +
oder
* *Name der Kategorie*

2+|Bestand

|Bestand aktualisieren
a|
* Lager
* Menge
* Lagerort

2+|Artikel Bilder

|Vor dem Hochladen alle Bilder löschen
a|
* *Bilder löschen* = 1

|Bilder speichern
a|
* *Multi-URL* +
oder
* *URL* +
oder
* *Dateiname*
* *Base64 Data*

|Bilder aktualisieren
a|
* *ID des Bildes*

|Bild mit Variante verknüpfen
a|
* *Multi-URL* +
oder
* *URL*

2+|Merkmale

|Merkmale speichern
a|
* *Merkmalkombination* +
oder
* *Interner Name*
* *Sprache*
* *Wert* +
oder
* *ID*
* *Sprache*
* *Wert*

|Merkmale aktualisieren
a|
* *Merkmalkombination* +
oder
* *Interner Name*
* *Sprache*
* *Wert* +
oder
* *ID*
* *Sprache*
* *Wert*

2+|Lieferant

|Lieferant verknüpfen
a|
* *EK*

und

* *Lieferanten-ID* +
    oder
* *Lieferanten-Name*

|Lieferant aktualisieren
a|
* *EK*

und

* *Lieferanten-ID* +
    oder
* *Lieferanten-Name*

2+|SKU

|SKU hinzufügen
a|
* *Marktplatz-ID*
* *SKU*

Bei eBay/Amazon außerdem:

* *Account-ID*

|SKU aktualisieren
a|
* *Marktplatz-ID*
* *SKU*

Bei eBay/Amazon außerdem:

* *Account-ID*

2+|Paket

|Paket erstellen
a|
* *Paketbestandteile*

|Paketbestandteile löschen
a|
* *Paketbestandteile löschen*

|Paket löschen
a|
* *Paket löschen = 1*

|====

[#2000]
=== Sync vom Typ Aufträge einrichten

Mit Syncs des Typs Aufträge importieren Sie Auftragsdaten.

[#2010]
==== Felder für den Kategorieabgleich

Es gibt derzeit nur ein Abgleichfeld für die Identifizierung von Aufträgen. Das folgende Abgleichfeld steht Ihnen zur Verfügung:

* Auftrags-ID

[#2020]
==== Felder für die Auftragszuordnung

In <<tabelle-Zuordnungsfelder-Auftraege>> werden Felder erläutert, die für den Abgleich von Kategoriedaten zur Verfügung stehen. Anhand des gewählten Feldes wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Zuordnungsfelder-Auftraege]]
.Zuordnungsfelder für Auftragsimport
[cols="1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

3+|Auftrag

|Typ-ID
|Nummerisch
a|Auftragstypen bilden verschiedene Geschäftsvorfälle ab. Folgende Typen stehen zur Verfügung:

* Auftrag = 1
* Lieferauftrag = 2
* Retoure = 3
* Gutschrift = 4
* Garantie = 5
* Reparaturauftrag = 6
* Angebot = 7
* Vorbestellung = 8
* Sammelauftrag = 9
* Sammelgutschrift = 10

|Status-ID
|Nummerisch
|ID des Status. Die IDs vergeben Sie selbst im Bereich von 1,0000 bis 18,9999. Sie finden die Status unter *System » Aufträge » Status*

|Eigner-ID
|Nummerisch
|ID des Eigners. Ein Eigner ist ein Benutzer, der als Eigner zugeordnet wurde. Die ID des Eigners entspricht also der ID des Benutzers. Sie finden die Benutzer-ID unter *System » Einstellungen » Benutzer » Konten*. Aufträge können einem Eigner zugeordnet werden, müssen aber nicht.

|PlentyID
|Nummerisch
|ID des Mandanten. Die PlentyID finden Sie unter *System » Mandant » Mandant wählen » Einstellungen*.

|Standort-ID
|Nummerisch
|ID des Standorts. Standorte finden Sie unter *System » Mandant » Mandant wählen » Standorte*.

3+|Auftragsposition

|Typ
|Nummerisch
a|Die Auftragspositionstypen bilden verschiedene Kostenposten eines Auftrags ab. Die mit den Posten verbundenen Kosten können sowohl negativ als auch positiv sein. Standardmäßig wird hier die ID des Auftragspositionstyps erwartet. Die Typen, die zur Verfügung stehen, sind hier mit Typ-ID aufgeleistet. Wenn Ihre Spalte nicht die IDs enthält, nehmen Sie eine eigene Zuordnung vor.

* Variante = 1
* Artikelpaket = 2
* Paketbestandteil = 3
* Aktionsgutschein = 4
* Geschenkgutschein = 5
* Versandkosten = 6
* Zahlungsaufschlag = 7
* Geschenkverpackung = 8
* Unzugeordnete Variante = 9
* Pfand = 10
* Auftrag = 11

Der Typ Auftrag kommt z.B. in Sammelaufträgen vor.

|Herkunft
|Nummerisch
|Standardmäßig wird hier die ID der Herkunft erwartet. Die IDs finden Sie im Menü *System » Aufträge » Auftragsherkunft*. Wenn Ihre Spalte nicht die IDs enthält, nehmen Sie eine eigene Zuordnung vor.

|Name
|Alphanummerisch
|Spalte wählen, die den Namen der Auftragsposition enthält. Standardmäßig wird davon ausgegangen, dass die Namen in der Systemsprache angegeben sind.

|Attributwert
|Alphanummerisch
|Spalte wählen, die den Namen des Attributwertes enthält. Der Name wird in Systemsprache erwartet.

|Umsatzsteuersatz
|Nummerisch
|Standardmäßig wird hier der Prozentwert des Steuersatzes erwartet. Ob die Zahl kommasepariert oder punktsepariert erwartet wird, hängt von Ihren Importoptionen ab. Die Importoptionen stellen Sie im Abgleich ein.

|Umsatzsteuerbetrag
|Nummerisch
|Spalte wählen, die den Steuerbetrag enthält. Standardmäßig wird der Umsatzsteuerbetrag für die Menge 1 der Auftragsposition erwartet. Ob die Zahl kommasepariert oder punktsepariert erwartet wird, hängt von Ihren Importoptionen ab. Die Importoptionen stellen Sie im Abgleich ein.

|Menge
|Nummerisch
|Spalte wählen, die die Anzahl einer Auftragsposition enthält.

|Varianten-ID
|Nummerisch
|Standardmäßig wird hier die ID der Variante erwartet. Die IDs finden Sie im Menü *Artikel » Artikel bearbeiten*. Wenn Ihre Spalte nicht die IDs enthält, nehmen Sie eine eigene Zuordnung vor.

|Position
|Nummerisch
|Spalte wählen, die die Position der Auftragspositionen enthält. Die Position dient der Sortierung innerhalb des Auftrages. Sie wird jedoch bisher noch nicht beachtet.

|Währung
|Alphanummerisch
|Standardmäßig wird der ISO-Code einer Währung erwartet, z.B. EUR für Euro.

|Wechselkurs
|Nummerisch
|Spalte wählen, die den Wechselkurs enthält. Der Wechselkurs muss den Umrechnungskurs von der Auftragswährung in die Systemwährung enthalten. Ihre Systemwährung finden Sie im Menü *System » Aufträge » Zahlung » Währungen*. Ob die Zahl kommasepariert oder punktsepariert erwartet wird, hängt von Ihren Importoptionen ab. Die Importoptionen stellen Sie im Abgleich ein.

|Einkaufspreis
|Nummerisch
|Spalte wählen, die den Einkaufspreis enthält. Standardmäßig wird der Einkaufspreis für die Menge 1 der Auftragsposition erwartet. Der Einkaufspreis wird im Auftrag nicht direkt angezeigt. Er ermöglicht aber das Errechnen und Anzeigen der Gewinnspanne. Ob die Zahl kommasepariert oder punktsepariert erwartet wird, hängt von Ihren Importoptionen ab. Die Importoptionen stellen Sie im Abgleich ein.

|Bruttopreis
|Nummerisch
|Spalte wählen, die den Bruttopreis enthält. Standardmäßig wird der Bruttopreis für die Menge 1 der Auftragsposition erwartet. Ob die Zahl kommasepariert oder punktsepariert erwartet wird, hängt von Ihren Importoptionen ab. Die Importoptionen stellen Sie im Abgleich ein.

|Nettopreis
|Nummerisch
|Spalte wählen, die den Nettopreis enthält. Standardmäßig wird der Nettopreis für die Menge 1 der Auftragsposition erwartet. Ob die Zahl kommasepariert oder punktsepariert erwartet wird, hängt von Ihren Importoptionen ab. Die Importoptionen stellen Sie im Abgleich ein.

|Preisaufschlag
|Nummerisch
|Spalte wählen, die den Preisaufschlag enthält. Standardmäßig wird der Preisaufschlag für die Menge 1 der Auftragsposition erwartet. Ob die Zahl kommasepariert oder punktsepariert erwartet wird, hängt von Ihren Importoptionen ab. Die Importoptionen stellen Sie im Abgleich ein.

|Rabatt
|Nummerisch
|Spalte wählen, die den Rabatt enthält. Standardmäßig wird der Rabatt für die Menge 1 der Auftragsposition erwartet. Ob die Zahl kommasepariert oder punktsepariert erwartet wird, hängt von Ihren Importoptionen ab. Die Importoptionen stellen Sie im Abgleich ein.

|Prozentualer Rabatt
|Nummerisch
|Spalte wählen, die den Prozentsatz für den Rabatt enthält. Ob die Zahl kommasepariert oder punktsepariert erwartet wird, hängt von Ihren Importoptionen ab. Die Importoptionen stellen Sie im Abgleich ein.

3+|Auftragspositionseigenschaften

|Wert
|Alphanummerisch
a|Eigenschaftstyp wählen und anschließend die Spalte wählen, in der die Eigenschaft enthalten ist. Standardmäßig stehen folgende Eigenschaften für Auftragspositionen zur Verfügung: +

* Lager
* Gewicht
* Breite
* Länge
* Höhe
* Externe Token ID
* Externe Artikel-ID
* Gutscheincode
* Gutscheintyp
* Einheit
* Externe Versandartikel-ID
* Retourengrund
* Artikelstatus
* Externe Auftragspositions-ID

Eigene Eigenschaftstypen für Auftragspositionen können per link:https://developers.plentymarkets.com/api-doc/Order#element_113[Interface^] oder per link:https://developers.plentymarkets.com/rest-doc#/Order/post_rest_orders_properties_types[REST^] angelegt werden. Sie werden jedoch nicht in der UI angezeigt.

3+|Adressrelation

|Adress-ID
|Nummerisch
|Wählen, ob die Adresse die Rechnungsadresse oder die Lieferadresse des Auftrages ist. Anschließend Spalte wählen, die die ID der Adresse enthält. Die Adress-ID dient der Zuordnung zu bereits existierenden Adressen von Kontakten. Wenn es sich um eine neue Adresse handelt, nutzen Sie die Adresszuordnungsfelder.

3+|Auftragseigenschaft

|Wert
|Alphanummerisch
a|Eigenschaftstyp wählen und anschließend die Spalte wählen, in der die Eigenschaft enthalten ist. Standardmäßig stehen folgende Eigenschaften für Aufträge zur Verfügung: +

* Lager
* Versandprofil
* Zahlungsart
* Zahlungsstatus
* Externes Versandprofil
* Sprache in Dokumenten
* Externe Auftrags-ID
* Kundenzeichen
* Mahnstufe
* Verkäuferkonto
* Markierung
* Umsatzsteuer-Identifikationsnummer

Eigene Eigenschaftstypen für Aufträge können per link:https://developers.plentymarkets.com/api-doc/Order#element_113[Interface^] oder per link:https://developers.plentymarkets.com/rest-doc#/Order/post_rest_orders_properties_types[REST^] angelegt werden. Sie werden in der .

3+|Auftragsdatum

|Datum
|
|Datumstyp wählen und anschließend die Spalte wählen, in der das Datum enthalten ist. Das Datumsformat in der Spalte muss in dem Datumsformat angegeben sein, dass Sie in den Importoptionen definiert haben.

3+|Auftragsrelation

|Referenz-ID
|
a|Auftragsrelation wählen und anschließend die Spalte wählen, in der die Referenz-ID enthalten ist. Folgende Relationen stehen zur Verfügung:

* Kontakt - Sender: Die Referenz-ID ist die ID eines bestehenden Kontakts und dieser Kontakt ist Sender des Auftrags
* Kontakt - Empfänger: Die Referenz-ID ist die ID eines bestehenden Kontakts und dieser Kontakt ist Empfänger des Auftrags
* Konto - Sender: Die Referenz-ID ist die ID eines bestehenden Kontos und dieses Konto ist Sender des Auftrags
* Konto - Empfänger: Die Referenz-ID ist die ID eines bestehenden Kontos und dieser Kontos ist Empfänger des Auftrags
* Lager - Sender: Die Referenz-ID ist die ID eines bestehenden Lagers und dieses Lager ist Sender des Auftrags
* Lager - Empfänger: Die Referenz-ID ist die ID eines bestehenden Lagers und dieses Lager ist Empfänger des Auftrags

2+|Adresse
|Egal, welches Adressfeld gewählt wird, müssen Sie zunächst wählen, ob es zu einer Lieferadresse oder einer Rechnungsadresse gehört.

|Name 1 (Firma)
|
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die den Firmennamen enthält.

|Name 2 (Vorname)
|
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die den Vornamen enthält.

|Name 3 (Nachname)
|
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die den Nachnamen enthält.

|Name 4 (Zusatz)
|
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die den Namenszusatz enthält.

|Adresse 1 (Straße)
|
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die den Straßennamen enthält.

|Adresse 2 (Hausnummer)
|
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die die Hausnummer enthält.

|Adresse 3 (Zusatz)
|
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die den Adresszusatz enthält.

|Adresse 4 (Frei)
|
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die freie Adressinformationen enthält.

|Postleitzahl
|
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die die Postleitzahl enthält.

|Stadt
|
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die den Städtenamen enthält.

|Landes-ID
|Nummerisch
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die die ID des Landes enthält. Standardmäßig werden hier die IDs der Lieferländer erwartet. Diese IDs finden Sie im Menü *System » Aufträge » Versand » Optionen*.

|Bundesland-ID
|Nummerisch
|Liste aller Länder, für die Bundesländer verfügbar sind mit den IDs der Bundesländer: link:basics/datenaustausch/assets/Bundeslaender.pdf[Bundesländer]

|USt-IdNr.
|Alphanummerisch
|Umsatzsteueridentifikationsnummer eines Kunden angeben

|Telefon
|Nummerisch
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die die Telefonnummer enthält.

|E-Mail
|
|Rechnungsadresse oder Lieferadresse wählen und anschließend die Spalte wählen, die die E-Mail-Adresse enthält.

2+|Versandpaket
|Egal, welche Paketinformationen gewählt werden, zunächst müssen Sie ein Versandpaket wählen, mit dem diese Informationen abgestimmt werden. Versandpakete richten Sie im Menü *System » Aufträge » Versand » Versandpakete* ein.

|Gewicht
|
|Versandpaket wählen und anschließend die Spalte wählen, die das Gewicht des Paketes enthält.

|Paketnummer
|
|Versandpaket wählen und anschließend die Spalte wählen, die die Paketnummer enthält. Mehrere Paketnummern können kommasepariert in einer Zeile oder über mehrere Zeilen mit je einer Paketnummer pro Zeile angegeben werden.

|Packstückart
|
a|Versandpaket wählen und anschließend die Spalte wählen, die die Packstückart enthält. Standardmäßig wird hier die ID der Packstückart erwartet:

* 0 = unverpackt
* 1 = Ballen
* 2 = Behälter
* 3 = Bund
* 4 = Rollpalette
* 5 = Colli
* 6 = Container
* 7 = Eimer
* 8 = Fass
* 9 = Flaschen
* 10 = Euro-Pool-Flachpalette
* 11 = Gestell
* 12 = Gasflasche
* 13 = Gitterboxpalette
* 14 = Hobbock
* 15 = Halbe Palette
* 16 = Lebensmittelpalette
* 17 = Holzuntersetzer
* 18 = IBC Container
* 19 = Kanne
* 20 = Korbflasche
* 21 = Kiste
* 22 = Kanister
* 23 = Kundenpalette
* 24 = Karton
* 25 = Kombinationsverpackung
* 26 = Pack
* 27 = Ring
* 28 = Rolle
* 29 = Sack
* 30 = Stück
* 31 = Tank
* 32 = Trommel
* 34 = Verschlag
* 35 = Viertelpalette
* 36 = sonstige Paletten
* 37 = Kasten
* 38 = Einwegpalette
* 39 = Folientüte


|====

[#2100]
=== Sync vom Typ Kategorie einrichten

Mit Syncs des Typs Kategorie importieren Sie Kategoriedaten.

[#2110]
==== Felder für den Kategorieabgleich

In <<tabelle-Abgleichfelder-Kategorie>> werden Felder erläutert, die für den Abgleich von Kategoriedaten zur Verfügung stehen. Anhand des gewählten Feldes wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Abgleichfelder-Kategorie]]
.Abgleichfelder für Kategorieimport
[cols="1,2"]
|====
|Einstellung |Erläuterung

|KategorieId
|

|Kategoriename Kombiniert
|Aus der zweiten Dropdown-Liste das Trennzeichen wählen.

|Kategoriename Ebene 1 - 6
|

|====

[#2120]
==== Felder für die Kategoriezuordnung

In <<tabelle-Zuordnungsfelder-Kategorie>> werden Felder erläutert, die für den Abgleich von Kategoriedaten zur Verfügung stehen. Anhand des gewählten Feldes wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Zuordnungsfelder-Kategorie]]
.Zuordnungsfelder für Kategorieimport
[cols="1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

3+|Kategorie

|Elternkategorie ID
|Nummerisch (interne ID)
|

|Elternkategorie Name
|Alphanummerisch
|

|Typ
|item = Artikel +
container = Container +
content = Content +
blog = Blog (nicht in Verwendung)
|

|In Linkliste anzeigen
|0 = Nein +
1 = Ja
|

|right
|all = Kategorie und alle Unterkategorien sind öffentlich sichtbar +
customer = Kategorie und alle Unterkategorien sind nur für eingeloggte Webshop-Besucher sichtbar +
|Entspricht Backend-Einstellung *Sichtbar*


|Sichtbar (Sitemap)
|0 = Nein +
1 = Ja
|Entspricht Backend-Einstellung *Sitemap*

|Kategorie löschen
|0 = Nein +
1 = Ja
|

3+|Details (Zuordnung pro Kombination aus Sprache und Mandant (Shop))

|Name
|Alphanummerisch
|Pflichtwert

|Beschreibung 1
|Alphanummerisch
|

|Beschreibung 2
|Alphanummerisch
|

|Kurzbeschreibung
|Alphanummerisch
|

|Meta-Keywords
|Alphanummerisch
|

|Meta-Beschreibung
|Alphanummerisch
|

|Meta-Titel
|Alphanummerisch
|

|URL-Name
|Alphanummerisch
|

|Position
|Nummerisch
|

|Template-Liste
|Alphanummerisch
|

|Template-Produkt
|Alphanummerisch
|

|Template-Seite
|Alphanummerisch

|Volltextsuche
|0 = Nein +
1 = Ja
|

3+|Mandant (Shop) (Zuordnung pro Mandant)

|Aktiv
|0 = Nein +
1 = Ja
|

|====

[.subhead]
Beispiel 1: Preis- und Bestandsabgleich einer Variante

Mithilfe eines einfachen Syncs können Preise und Bestand einer Variante aktuell gehalten werden. Nachdem zunächst die Zuordnung im Sync vorgenommen wurde, muss ein Mapping erstellt werden. Dafür werden im Bereich Werte bestimmen des Mappings die plentymarkets Felder VariationSalesPrice und VariationStock gewählt. Nachdem die Werte bestimmt wurden, muss für VariationSalesPrice zunächst der zu aktualisierende Verkaufspreis (Preis, UVP) bestimmt werden. Es können auch mehrere Verkaufspreise mit nur einem Sync aktualisiert werden. Im nächsten Schritt wird die tatsächliche Verknüpfung mit einem Feld der Datenquelle vorgenommen. Beim Bestand kann neben dem Lager auch der Lagerort gewählt werden. Für VariationStock wird das Lager gewählt, für welches Bestand gebucht werden soll. Optional kann hier auch der Lagerort bestimmt werden. Um die Menge aus der Datenquelle zu übernehmen, muss noch das plentymarkets Feld quantity und das zugehörige Feld der Datenquelle verknüpft werden. Dabei wird immer eine Bestandskorrektur vorgenommen.

[.subhead]
Beispiel 2: Artikelbeschreibungen importieren

Für einen Artikel sollen Name, technische Daten und Meta-Keywords importiert werden. Dafür müssen zunächst diese plentymarkets Felder im Bereich Werte bestimmen des Mappings ausgewählt und übernommen werden. Für Artikelbeschreibungen wird im nächsten Schritt die Sprache gewählt. Eine Mehrfachauswahl ist möglich. Die Felder Name, Technische Daten und Meta-Keywords werden nun mit den gewünschten Feldern der Datenquelle verknüpft. Das heißt, dass die in den Datensätzen der Datenquelle vorhandenen Einträge für die zuvor gewählten plentymarkets Felder importiert werden. Zusätzlich kann der Import durch Filter weiter bestimmt oder eingegrenzt werden. So kann zum Beispiel eigestellt werden, dass die Artikelbeschreibungen nur importiert werden sollen, wenn der Artikel einer bestimmten Marke entspricht.

[#2200]
=== Sync vom Typ Kontakte, Firmen und Adressen einrichten

Voraussetzung für die Nutzung des Plugins:

* Das Plugin Elastischer Export muss installiert und in Productive bereitgestellt sein.
* Damit die neu importierten oder aktualisierten Lieferländer in einem Kontaktdatensatz in der Kontaktübersicht angezeigt werden, müssen diese Lieferländer im Menü *System » Aufträge » Versand » Optionen » Tab: Lieferländer* aktiviert sein.

Mit Syncs des Typs *Kontakte, Firmen und Adressen* importieren Sie neue Kontaktdaten oder aktualisieren bestehende Datensätze. Diese Daten sind z.B. Daten der Lieferadresse und Rechnungsadresse, das Geburtsdatum des Kontakts, der Kundentyp, Kontaktoptionen wie die private oder geschäftliche E-Mail-Adresse sowie die Firmendaten.

Um Kontaktdaten per ElasticSync zu aktualisieren, müssen die folgenden Datensätze in plentymarkets vorhanden sein:

* Kontakte (Menü *CRM » Kontakte*)
* ggf. Kontaktoptionen wie Telefonnummer und E-Mail-Adresse
* ggf. Adressdaten (Rechnungsadresse, Lieferadresse)
* ggf. Firmendaten wie USt-IdNr. und Zahlungsziel

[#2210]
==== Felder für den Abgleich von Kontakten, Firmen und Adressen

Über die folgenden Links finden Sie die Listen der Felder, die für den Abgleich von Kontaktdaten, Adressdaten und Firmendaten zur Verfügung stehen:

* link:https://developers.plentymarkets.com/rest-doc/account_contact/details#create-a-contact[Kontaktdetails^]
* link:https://developers.plentymarkets.com/rest-doc/account_contact_option/details#list-contact-options-by-the-contact-id[Kontaktoptionen^]
* link:https://developers.plentymarkets.com/rest-doc/account_address/details#get-an-address[Adressdetails^]
* link:https://developers.plentymarkets.com/rest-doc/account_address/details#get-an-address-option[Adressoptionen^]
* link:https://developers.plentymarkets.com/rest-doc/account/details#list-accounts[Firmendetails^]

Anhand der Identifikatoren *Kontakt-ID*, *E-Mail*, *Rechnungsadress-ID* und *Lieferadress-ID* im Bereich Abgleich wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[#2220]
==== Pflichtwerte für Sync-Aktionen von Kontakten, Firmen und Adressen

[[tabelle-Pflichtwerte-Sync-Aktionen-Kontakte]]
.Pflichtwerte für Sync-Aktionen von Kontakten, Firmen und Adressen
[cols="1,2"]
|====
|Aktion |Erforderliche Werte

2+|Kontakte

|Kontakt erstellen
a|
* Herkunft
* Typ

2+|Kontaktoption

|Kontaktoption erstellen
a|
* Wert

|Kontaktoption aktualisieren
a|
* Kontakt-ID
* zu ändernde Felder

2+|Adresse

|Adresse erstellen
a|
* Kontakt-ID
* mindestens eine der folgenden Optionen: Name1, Name2, Name3
* mindestens eine der folgenden Optionen: Adresse1, Adresse2, Adresse3
* mindestens eine der folgenden Optionen: Länder-ID oder Länder-ISO-Code
* Ort

|Adresse aktualisieren
a|
* mindestens eine der folgenden Optionen: Name1, Name2, Name3
* Kontakt-ID
* zu ändernde Felder

2+|Adressoption

|Adressoption erstellen
a|
* Wert

|Adressoption aktualisieren
a|
* Adress-ID
* Kontakt-ID
* zu ändernde Felder

2+|Firma

|Firma erstellen
a|
* Firmenname

|Firma aktualisieren
a|
* Firmenname

|====

[#2230]
=== Sync vom Typ Lager einrichten

Mit Syncs des Typs *Lager* importieren Sie neue Lagerorte oder aktualisieren bestehende.

Um Lagerorte per ElasticSync zu erstellen oder zu aktualisieren, müssen Sie ein Lager angelegt haben.

*Felder für den Abgleich*

Anhand des gewählten Feldes wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

Wenn Sie weitere Informationen zu den Begrifflichkeiten Dimensionen, Ebenen und Lagerorten benötigen, dann können Sie sich hier informieren: https://knowledge.plentymarkets.com/warenwirtschaft/lager-einrichten

[[tabelle-Abgleichfelder-Lagerorte]]
.Abgleichfelder für Lagerortimport
[cols="2,2"]
|====
|Abgleichfeld |Erläuterung

|Warehouse Id
|ID des Lagers

|Level Name
|Name der Ebene z.B. R01

|Level ID
|ID der Ebene

|WarehouseLocationId
|ID des Lagerorts

|WarehouseLocationName
|Name des Lagerorts ohne Pfad
|====


[[tabelle-Zurodnungsfelder-Lagerorte]]
.Zurodnungsfelder für Lagerortimport
[cols="2,2"]
|====
|Zuordnungsfeld |Erläuterung

2+|Lagerorte

|Storage location Id
|ID des Lagerorts

|Level ID
|Id der Ebenen

|Storage location name
|Name des Lagerorts ohne Pfad

|Purpose
|Verwedungszweck des Lagerortes z.B. Entnahme

|Status
|Status des Lagerortes z.B. aktiv, inaktiv

|Position
|Position des Lagerorts (Laufweg)

|Storage location type
|Typ des Lagerortes z.B. klein, mittel, groß

2+|Ebenen der Lagerorte

|Level Parent ID
|Wie soll ich das erklären?

|Dimension ID
|ID der Dimension z.B. Regal

|Level Position
|Position der Ebene

|Level Name
|Name der Ebene z.B. R01, R02 usw.

|====

[#2240]
==== Lagerorte anpassen

Sie können mit ElasticSync Lagerorte anpassen, wie z.B. den Namen oder die Position des Lagerortes.

[.instruction]
Lagerorte anpassen:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Klicken Sie in der Sync-Übersicht auf einen Sync. +
→ Die Abgleichoptionen des Syncs werden angezeigt.
. Wählen Sie die Felder WarehouseID und storage location id.
. Wählen Sie bei Importoption *überspringen*.
. *Speichern* Sie die Einstellungen.
. Klicken Sie auf *Zuordnung* und öffnen Sie eine entsprechende Zurodnung aus der Übersicht.
. Wählen sie aus der rechten Seite aus *Lagerorte* die Felder *Storage Location ID*, *Storage location name* und *Position*.

[#2250]
==== Lagerorte erstellen

Sie können mit ElasticSync neue Lagerorte erstellen.

[.instruction]
Lagerorte anlegen:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Klicken Sie in der Sync-Übersicht auf einen Sync. +
→ Die Abgleichoptionen des Syncs werden angezeigt.
. Wählen Sie die Felder WarehouseID und storage location id.
. Wählen Sie bei Importoption *erstellen*.
. *Speichern* Sie die Einstellungen.
. Klicken Sie auf *Zuordnung* und öffnen Sie eine entsprechende Zurodnung aus der Übersicht.
. Wählen Sie aus der rechten Seite aus *Lagerorte* die Felder *Level ID*, *Storage Location ID*, *Storage location name*, *Purpose*, *Status* und *Position*, *Type*.
. Wählen Sie aus der rechten Seite aus *Ebene der Lagerorte* die Felder *Dimension ID*, *Level Position* und *Level name*.

[#5]
== Daten per dynamischen Import importieren

Beachten Sie, dass pro Import maximal 6000 Datensätze möglich sind. +
In den letzten Kapiteln auf dieser Handbuchseite werden Anwendungsbeispiele beschrieben.

Eine Einführung zum dynamischen Import erhalten Sie im folgenden Videotutorial:

video::119849465[vimeo]

[#10]
== Datenformat erstellen

Das Datenformat, das Sie importieren, muss der Konfiguration des Datenformats in plentymarkets entsprechen, damit die Daten zugeordnet werden. Hierzu gehört auch, dass die Schreibweise der Datenfelder der Schreibweise in plentymarkets entspricht. Auf der Handbuchseite eines <<basics/datenaustausch/datenformate#, Datenformats>> finden Sie die Namen der Datenfelder aufgelistet. Beachten Sie auch die Hinweise zur Angabe von Pflichtfeldern und Abgleichfeldern. Sie haben die Möglichkeit, mit Hilfe eines Tabellenkalkulationsprogramms selbst eine Datei für den Import zu erstellen.

Sie können sich diese Arbeit erheblich erleichtern, indem Sie das Datenformat vorab in eine Datei exportieren, Ihre Daten in der Datei bearbeiten und diese dann wieder importieren. Diese Vorgehensweise ist nur bei Datenformaten möglich, die sowohl einen Import als auch einen Export erlauben. Weitere Informationen zum Umgang mit Export- und Importdateien finden Sie im Kapitel <<basics/datenaustausch/daten-exportieren#05, Datei für den Datenaustausch anpassen>> auf der Handbuchseite <<basics/datenaustausch/daten-exportieren#, Daten exportieren>>. Gehen Sie wie im Folgenden beschrieben vor, um Ihre Daten in eine Datei zu exportieren:

[.instruction]
Datenformat erstellen:

. Öffnen Sie das Menü *Daten » Dynamischer Export*.
. Wechseln Sie in das Tab *Neues Datenformat*.
. Wählen Sie einen *Datenformat-Typ* aus der Dropdown-Liste.
. Ändern Sie ggf. den automatisch vergebenen *Datenformatsname*.
. Aktivieren Sie die Datenfelder, die in der Exportdatei vorhanden sein sollen.
. Wählen Sie eine *Importaktion* pro Datenfeld. +
→ Beachten Sie die Hinweise zu Abgleichfeldern auf den Unterseiten der Handbuchseite <<basics/datenaustausch/datenformate#, Datenformate>>.
. Wählen Sie ggf. *Filter* oder *Aktionen*.
. *Speichern* Sie das Datenformat. +
→ Die Reihenfolge der Datenfelder wird anhand der Werte in der Spalte *Position* gespeichert.

[#25]
[TIP]
.Importaktionen für Datenfelder wählen
====
Bei einem Datenformat stehen für die Datenfelder die Importaktionen *Abgleich* und *Import* zur Verfügung. +
Mit der Einstellung *Import* werden die Daten, importiert - unabhängig davon, ob bereits Daten vorhanden sind oder nicht. Das bedeutet, dass die Daten bei einem Import eventuell überschrieben werden. Mit der Einstellung *Abgleich* wird das Datenfeld vor einem Import mit bereits im System vorhandenen Daten abgeglichen. Die Daten werden nur importiert, wenn noch keine Daten vorhanden sind.
====

[#20]
== Dynamischen Import nutzen

Der dynamische Datenimport erfolgt im Menü *Daten » Dynamischer Import*. Sie können hier selbst erstellte Dateien oder die Datenformate, die Sie im Menü *Daten » Dynamischer Export* erstellt haben (sog. Kundenformate), wieder importieren. Im Menü *Daten » Dynamischer Import* stehen Ihnen neben den Kundenformaten in der Dropdown-Liste *Format* zwei Spezialformate zur Verfügung:

* das Spezialformat *ItemParcelServicePreset*, mit dem Sie Versandprofile importieren
* das Spezialformat *IncomingItems*, mit dem sie Wareneingangsdaten importieren

Die Spezialformate sind reine Importformate und stehen daher nur im Menü *Daten » Dynamischer Import* zur Verfügung. Der Import der Spezialformate funktioniert auf die gleiche Weise, wie Sie auch die anderen Datenformate importieren. Die Vorgehensweise wird im Folgenden beschrieben.

[NOTE]
.Spaltenkopfbezeichnungen prüfen und anpassen
====
Wenn Daten aus einem externen System importiert werden sollen oder Sie Datei selbst erstellt haben, müssen die Spaltenkopfbezeichnungen in der Datei mit der von plentymarkets vorgegebenen Schreibweise der Datenfelder (Feldnamen) exakt übereinstimmen. +
Kann plentymarkets beim Import keine Zuordnung zu einer gewählten Exportvariante herstellen, wird der Import mit einer Fehlermeldung abgebrochen. Die Fehlermeldung finden Sie im Bereich *Bearbeitungsstatus*. Prüfen Sie die Spaltenkopfbezeichnungen der zu importierenden Datei und passen Sie diese bei Bedarf an.
====

[.instruction]
Daten per dynamischen Import importieren:

. Öffnen Sie das Menü *Daten » Dynamischer Import*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-einstellungen-menü-daten-dynamischer-import>>.
. Klicken Sie auf *Import*.
. Prüfen Sie, ob die importierten Daten im System angelegt wurden.

[IMPORTANT]
.Bearbeitungsstatus
====
Nachdem Sie die Datei importiert haben, erhalten Sie eine Meldung im Bereich *Bearbeitungsstatus*. Wenn Datenzeilen erfolgreich importiert wurden, wird die Anzahl der importierten Zeilen angegeben. Im Fehlerfall steht dort der Eintrag *0* und eine Fehlermeldung wird angezeigt. Prüfen Sie das Feldtrennzeichen oder die Codierung der Datei. Die Datei sollte immer UTF-8-codiert sein.
====

Beachten Sie, dass die Einstellungen, die Ihnen angezeigt werden, abhängig sind von dem Datenformat, das Sie für den Import gewählt haben. Für das Datenformat *Stock* z.B. wählen Sie statt einer Abgleichoption das *Lager* und den *Barcode*. Die Einstellungen, die in <<tabelle-einstellungen-menü-daten-dynamischer-import>> beschrieben sind, gelten für die Mehrheit der Datenformate.

[[tabelle-einstellungen-menü-daten-dynamischer-import]]
.Einstellungen im Menü *Daten » Dynamischer Import*
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Feldtrennzeichen*
|Feldtrennzeichen wählen, das in der Importdatei eingestellt ist.

|*Format*
|Datenformat wählen, das Sie für den Datenimport vorbereitet haben. +
*_Hinweis:_* Je nachdem, welches Datenformat Sie hier wählen, ändern sich die folgenden Einstellungen.

|*Wenn beim Abgleich keine Übereinstimmung*
|Eine der folgenden Optionen wählen:  +
*Neuen Datensatz anlegen* = Wenn die zu importierenden Daten noch nicht im System vorhanden sind. +
*Vorhandenen Datensatz überspringen* = Wenn beim Abgleich vorhandene Daten nicht überschrieben werden sollen.

|*Datei*
|Importdatei vom Speicherort wählen.
|====

Erfahren Sie mehr über die Informationen im Bereich *Bearbeitungsstatus*, mögliche Fehlermeldungen und deren Ursachen im folgenden Videotutorial:

video::141644702[vimeo]


[#210]
== eBay-Listings importieren

Im Menü *Daten » eBay-Listings* importieren Sie eBay-Listings. Es wird sowohl ein Artikelstammdatensatz als auch ein Listing in plentymarkets erstellt. Im Bereich *Bearbeitungsstatus* haben Sie während des Importprozesses Einsicht in den aktuellen Verlauf des Imports. Wie Sie die Listings importieren, ist auf der Handbuchseite von <<omni-channel/multi-channel/ebay/ebay-einrichten#, eBay>> im Kapitel <<omni-channel/multi-channel/ebay/ebay-einrichten#11000, eBay-Listings importieren>> beschrieben.

== Anwendungsbeispiel: Artikel erstellen und Artikeldaten anpassen

Im Menü *Daten* erstellen Sie Artikel oder ändern bestehende Artikeldaten. Diese Funktion bietet sich an, wenn Sie z.B. Artikellisten von Ihrem Lieferanten in plentymarkets importieren möchten oder den Preis Ihrer Artikeln anpassen möchten. Erstellen Sie zunächst das Datenformat *Item* im Menü *Daten » Dynamischer Export*. Exportieren Sie dann die Daten in eine Datei und bearbeiten Sie die Daten in der Datei. Abschließend importieren Sie diese Datei im Menü *Daten » Dynamischer Import*.

Erfahren Sie mehr über das Erstellen und Aktualisieren von Artikeldaten im folgenden Videotutorial:

video::140275175[vimeo]
////
[#60]
== Anwendungsbeispiel: Varianten importieren

Der Variantenimport erfolgt nicht automatisch mit dem Import Ihrer Artikel. Die folgenden Voraussetzungen müssen erfüllt sein, damit Sie Varianten erstellen und diese dann in Ihr plentymarkets System importieren können:

* Artikel müssen erstellt sein
* Attribute und Attributwerte müssen erstellt sein
* Attribute müssen mit dem Artikel verknüpft sein

Wenn die drei oben genannten Voraussetzungen erfüllt sind und Sie bereits Artikel, Attribute und Attributwerte erstellt haben und diese miteinander verknüpft haben, fahren Sie fort mit dem Kapitel <<basics/datenaustausch/daten-importieren#100, Varianten erstellen>>.

Wie Sie die genannten Voraussetzungen mit Hilfe von Importen realisieren und welche Datenformate Sie dafür nutzen, erfahren Sie in den folgenden Kapiteln. Im Folgenden finden Sie eine Schnellübersicht der notwendigen Datenformate:

* Datenformat *Item* zum <<basics/datenaustausch/daten-importieren#70, Import von Artikeln>>
* Datenformat *Attribute* zum <<basics/datenaustausch/daten-importieren#80, Import von Attributen und Attributwerten>>
* Datenformat *ItemAttribute* zur <<basics/datenaustausch/daten-importieren#90, Verknüpfung von Artikeln mit Attributen>>

[#70]
=== Artikel importieren

Artikel werden mit dem Datenformat *Item* erstellt. Erstellen Sie das Datenformat im Menü *Daten » Dynamischer Export*. Beachten Sie die Hinweise zu den Pflichtfeldern auf der Handbuchseite <<basics/datenaustausch/datenformate/item#, Item>>.

Importieren Sie nun die Artikel. Die Artikel stehen im Menü *Artikel » Artikel bearbeiten* zur weiteren Bearbeitung zur Verfügung.

[.instruction]
Artikel importieren:

. Öffnen Sie das Menü *Daten » Dynamischer Import*.
. Wählen Sie das Trennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus der Dropdown-Liste *Format* das Datenformat, das Sie für den Artikel angelegt haben.
. Wählen Sie eine Option unter *Wenn beim Abgleich keine Übereinstimmung*.
. Klicken Sie auf *Datei auswählen*.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf *Import*.

[#80]
=== Attribute und Attributwerte importieren

Attribute und Attributwerte werden mit dem Datenformat *Attribute* erstellt. Erstellen Sie das Datenformat im Menü *Daten » Dynamischer Export*. Beachten Sie die Hinweise zu den Pflichtfeldern auf der Handbuchseite <<basics/datenaustausch/datenformate/attribute#, Attribute>>.

Importieren Sie nun die Attribute sowie die Attributwerte. Die Attribute und die Attributwerte stehen im Menü <<artikel/artikel-verwalten#390, System » Artikel » Attribute>> zur weiteren Bearbeitung zur Verfügung.

[.instruction]
Attribute und Attributwerte importieren:

. Öffnen Sie das Menü *Daten » Dynamischer Import*.
. Wählen Sie das Trennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus der Dropdown-Liste *Format* das Datenformat, das Sie für das Attribut angelegt haben.
. Wählen Sie eine Option unter *Wenn beim Abgleich keine Übereinstimmung*.
. Klicken Sie auf *Datei auswählen*.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf *Import*.

[#90]
=== Attribute mit dem Artikel verknüpfen

Das Spezialformat *ItemAttribute* dient ausschließlich zum Import von Verknüpfungen zwischen Attributen und Artikeln. Ein Exportformat ist daher nicht vorhanden. Sie müssen dieses Datenformat nicht erstellen. Es steht als Spezialformat im Menü *Daten » Dynamischer Import* zur Verfügung. Beachten Sie die Erläuterungen zu den Datenfeldern in Tabelle 2.

Die Verknüpfung erfolgt anhand der Pflichtfelder *item_id* und *attribute_list*. Bei der Verknüpfung werden dem Artikel die Attribute zugewiesen und gleichzeitig für den Artikel aktiviert.

.Datenfelder des Datenformats *ItemAttribute*
[cols="a,a"]
|====
|Datenfeld |Erläuterung

|*attribute_list*
|Attributwerte. +
Hash-Aufbau: Attribut1:Wert1:Aufpreis;Attribut2:Wert2:Aufpreis +
*Attribut1* = Name des Attributs. +
*Wert1* = Name des Wertes des Attributs. +
(Optional) *Aufpreis* = Betrag des Aufpreises des Wertes in Euro (Euro und Cent getrennt durch einen Punkt). +
__*Beispiel*__: *Hutgröße:54:2.00* (Backend-Attributname:Backend-Wertname:Aufpreis). Im Attributnamen oder im Namen des Wertes darf kein Doppelpunkt verwendet werden, da dies zu einem fehlerhaften Datenimport führen würde.

|*external_item_id*
|Externe Artikel-ID

|*ean*
|EAN des Artikels zur Artikelbestimmung

|*item_id*
|Artikel-ID

|*item_no*
|Artikelnummer
|====

[IMPORTANT]
.Pflichtfelder
====
Pflichtfelder für den Datenimport: *attribute_list* und *item_id*.
====

[.instruction]
Attribute verknüpfen:

. Öffnen Sie das Menü *Daten » Dynamischer Import*.
. Wählen Sie das Trennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus der Dropdown-Liste *Format* das Spezialformat *ItemAttribute*.
. Wählen Sie eine Option unter *Wenn beim Abgleich keine Übereinstimmung*.
. Klicken Sie auf *Datei auswählen*.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf *Import*.

[#100]
=== Varianten erstellen

Um Varianten zu erstellen, benötigen Sie das Datenformat <<basics/datenaustausch/datenformate/_attributeitemvariation#, AttributeItemVariation>>. Die Datenfelder *ItemID*, *PriceID*, *VariationString* und *EAN* müssen mindestens aktiviert sein.

Die folgenden Voraussetzungen müssen erfüllt sein:

* Der Artikel ist erstellt.
* Die Attribute und Attributwerte sind erstellt.
* Die Attribute sind mit dem Artikel verknüpft und Werte sind am Artikel verknüpft, um eine Variante daraus erzeugen zu können.

[.instruction]
Varianten erstellen:

. Öffnen Sie das Menü *Daten » Dynamischer Import*.
. Wählen Sie das Feldtrennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus der Dropdown-Liste *Format* das Datenformat *AttributeItemVariation*.
. Wählen Sie eine Option unter *Wenn beim Abgleich keine Übereinstimmung*.
. Klicken Sie auf *Datei auswählen*.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf *Import*.

Das folgende Videotutorial veranschaulicht den Umgang mit dem Datenformat *AttributeItemVariation*:

video::139685582[vimeo]
////

[#120]
== Anwendungsbeispiel: Warenbestand importieren

Sie haben auch die Möglichkeit, den kompletten Warenbestand zu importieren, bei dem aktuelle physische Warenbestände in Ihrem plentymarkets System überschrieben werden. Nutzen Sie dazu das Datenformat <<basics/datenaustausch/datenformate/stock#, Stock>>.

[WARNING]
.Warenbestand wird gelöscht
====
Bei diesem Vorgang werden die aktuellen physischen Warenbestände durch den Import ersetzt, d.h. Ihr gesamter Warenbestand wird gelöscht. Reservierte Warenbestände bleiben dabei erhalten.

Wenn Sie nicht den kompletten Warenbestand importieren möchten, sondern nur Wareneingänge per Datenimport hinzufügen möchten, verwenden Sie das Spezialformat *IncomingItems*.
====

Wenn Sie die Importdatei vor dem Import bearbeiten möchten, beachten Sie die folgenden Erläuterungen zu den Datenfeldern. <<tabelle-datenfelder-datenformat-stock>> erläutert eine Auswahl der in der exportierten Datei enthaltenen Datenfelder.

[[tabelle-datenfelder-datenformat-stock]]
.Dynamischer Import; Datenfelder des Datenformats *Stock*
[cols="1,3"]
|====
|Feldname |Erläuterung

|*ItemID*
|Artikel-ID

|*VariationEAN*
|EAN-Code der Variante

|*PurchasePrice*
|Einkaufspreis

|*VariationNo*
|Variantennummer

|*LocationID*
|Lagerort-ID +
Jeweils die Ziffer 0 eingeben, wenn kein Lagerort vorhanden ist oder keine Zuordnung erfolgen soll.

|*Stock*
|Warenbestand

|*WarehouseID*
|ID des Lagers

|*VariationString*
|Systemnamen-Hash der Attribute und Werte. +
*_Beispiel:_* "Farbe:Blau;Größe:XXL" +
Die Namen bzw. Bezeichnungen der Attribute und Werte werden verwendet.
|====

[.instruction]
Datenimport durchführen:

. Öffnen Sie das Menü *Daten » Dynamischer Import*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-importoptionen-datenformat-stock>>.
. Klicken Sie auf *Import*.

[[tabelle-importoptionen-datenformat-stock]]
.Dynamischer Import; Importoptionen des Datenformats *Stock*
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Feldtrennzeichen*
|Trennzeichen wählen.

|*Format*
|Datenformat *Stock* für den Import wählen.

|*Lager*
|Lager für den Import wählen.

|*Barcode*
|Barcode für den Import wählen.

|*Datei*
|Datei für den Import wählen.
|====

Sie erhalten im Menü *Daten » Dynamischer Import* im Bereich *Bearbeitungsstatus* eine detaillierte Meldung des Datenimports. Unter anderem werden das Format, der Dateiname, der Benutzer und das Datum des Imports in diesem Bereich angezeigt.
