= Daten importieren
:lang: de
include::{includedir}/_header.adoc[]
:description: Erfahren Sie, wie Sie Datenformate erstellen und den dynamischen Import nutzen.
:position: 15

Diese Handbuchseite befasst sich mit dem manuellen Datenimport im Menü **Datenaustausch » Import » Dynamischer Import**. Ein Import von Daten ist ratsam, wenn Sie z.B. neue Artikel, Kundendaten oder Lagerbestände in Ihr plentymarkets System einpflegen möchten und die Daten bereits digital vorliegen. Beachten Sie, dass pro Import maximal 6000 Datensätze möglich sind. +
In den letzten Kapiteln auf dieser Handbuchseite werden Anwendungsbeispiele beschrieben.

Eine Einführung zum dynamischen Import erhalten Sie im folgenden Videotutorial:

video::119849465[vimeo]
[#10]
== Datenformat erstellen

Das Datenformat, das Sie importieren, muss der Konfiguration des Datenformats in plentymarkets entsprechen, damit die Daten zugeordnet werden. Hierzu gehört auch, dass die Schreibweise der Datenfelder der Schreibweise in plentymarkets entspricht. Auf der Handbuchseite eines **<<basics/datenaustausch/datenformate#, Datenformats  >>** finden Sie die Namen der Datenfelder aufgelistet. Beachten Sie auch die Hinweise zur Angabe von Pflichtfeldern und Abgleichfeldern. Sie haben die Möglichkeit, mit Hilfe eines Tabellenkalkulationsprogramms selbst eine Datei für den Import zu erstellen.

Sie können sich diese Arbeit erheblich erleichtern, indem Sie das Datenformat vorab in eine Datei exportieren, Ihre Daten in der Datei bearbeiten und diese dann wieder importieren. Diese Vorgehensweise ist nur bei Datenformaten möglich, die sowohl einen Import als auch einen Export erlauben. Weitere Informationen zum Umgang mit Export- und Importdateien finden Sie im Kapitel **<<basics/datenaustausch/daten-exportieren#05, Datei für den Datenaustausch anpassen >>** auf der Handbuchseite **Daten exportieren**. Gehen Sie wie im Folgenden beschrieben vor, um Ihre Daten in eine Datei zu exportieren:

[.instruction]
Datenformat erstellen:

. Öffnen Sie das Menü **Datenaustausch » Export » Dynamischer Export**.
. Wechseln Sie in das Tab **Neues Datenformat**.
. Wählen Sie einen **Datenformat-Typ** aus dem Dropdown-Menü.
. Ändern Sie ggf. den automatisch vergebenen **Datenformatsname**.
. Aktivieren Sie die Datenfelder, die in der Exportdatei vorhanden sein sollen.
. Wählen Sie eine **Importaktion** pro Datenfeld. +
→ Beachten Sie die Hinweise zu Abgleichfeldern auf den Unterseiten der Handbuchseite **<<basics/datenaustausch/datenformate#, Datenformate  >>**.
. Wählen Sie ggf. **Filter** oder **Aktionen**.
. **Speichern** Sie das Datenformat. +
→ Die Reihenfolge der Datenfelder wird anhand der Werte in der Spalte **Position** gespeichert.

[TIP]
.Importaktionen für Datenfelder wählen[#25]
====
Bei einem Datenformat stehen für die Datenfelder die Importaktionen **Abgleich** und **Import** zur Verfügung. +
Mit der Einstellung **Import** werden die Daten, importiert - unabhängig davon, ob bereits Daten vorhanden sind oder nicht. Das bedeutet, dass die Daten bei einem Import eventuell überschrieben werden. Mit der Einstellung **Abgleich** wird das Datenfeld vor einem Import mit bereits im System vorhandenen Daten abgeglichen. Die Daten werden nur importiert, wenn noch keine Daten vorhanden sind.
====

[#20]
== Dynamischen Import nutzen

Der dynamische Datenimport erfolgt im Menü **Datenaustausch » Import » Dynamischer Import**. Sie können hier selbst erstellte Dateien oder die Datenformate, die Sie im Menü **Datenaustausch » Export » Dynamischer Export** erstellt haben (sog. Kundenformate), wieder importieren. Im Menü **Datenaustausch » Import » Dynamischer Import** stehen Ihnen neben den Kundenformaten im Dropdown-Menü **Format** drei Spezialformate zur Verfügung:

* das Spezialformat **IncomingItems**, mit dem sie Wareneingangsdaten importieren
* das Spezialformat **ItemAttribute**, mit dem Sie Artikel und Attribute verknüpfen
* das Spezialformat **ItemParcelServicePreset**, mit dem Sie Versandprofile importieren

Die Spezialformate sind reine Importformate und stehen daher nur im Menü **Datenaustausch » Import » Dynamischer Import** zur Verfügung. Der Import der Spezialformate funktioniert auf die gleiche Weise, wie Sie auch die anderen Datenformate importieren. Die Vorgehensweise wird im Folgenden beschrieben.

[NOTE]
.Spaltenkopfbezeichnungen prüfen und anpassen
====
Wenn Daten aus einem externen System importiert werden sollen oder Sie Datei selbst erstellt haben, müssen die Spaltenkopfbezeichnungen in der Datei mit der von plentymarkets vorgegebenen Schreibweise der Datenfelder (Feldnamen) exakt übereinstimmen. +
Kann plentymarkets beim Import keine Zuordnung zu einer gewählten Exportvariante herstellen, wird der Import mit einer Fehlermeldung abgebrochen. Die Fehlermeldung finden Sie im Bereich **Bearbeitungsstatus**. Prüfen Sie die Spaltenkopfbezeichnungen der zu importierenden Datei und passen Sie diese bei Bedarf an.
====

[.instruction]
Daten per dynamischen Import importieren:

. Öffnen Sie das Menü **Datenaustausch » Import » Dynamischer Import**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. Klicken Sie auf **Import**.
. Prüfen Sie, ob die importierten Daten im System angelegt wurden.

[IMPORTANT]
.Bearbeitungsstatus
====
Nachdem Sie die Datei importiert haben, erhalten Sie eine Meldung im Bereich **Bearbeitungsstatus**. Wenn Datenzeilen erfolgreich importiert wurden, wird die Anzahl der importierten Zeilen angegeben. Im Fehlerfall steht dort der Eintrag **0** und eine Fehlermeldung wird angezeigt. Prüfen Sie das Feldtrennzeichen oder die Codierung der Datei. Die Datei sollte immer UTF-8-codiert sein.
====

Beachten Sie, dass die Einstellungen, die Ihnen angezeigt werden, abhängig sind von dem Datenformat, das Sie für den Import gewählt haben. Für das Datenformat **Stock** z.B. wählen Sie statt einer Abgleichoption das **Lager** und den **Barcode**. Die Einstellungen, die in Tabelle 1 beschrieben sind, gelten für die Mehrheit der Datenformate.

.Einstellungen im Menü **Datenaustausch » Import » Dynamischer Import**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Feldtrennzeichen**
|Feldtrennzeichen wählen, das in der Importdatei eingestellt ist.

|**Format**
|Datenformat wählen, das Sie für den Datenimport vorbereitet haben. +
**__Hinweis__**: Je nachdem, welches Datenformat Sie hier wählen, ändern sich die folgenden Einstellungen.

|**Wenn beim Abgleich keine Übereinstimmung**
|Eine der folgenden Optionen wählen:  +
**Neuen Datensatz anlegen** = Wenn die zu importierenden Daten noch nicht im System vorhanden sind. +
**Vorhandenen Datensatz überspringen** = Wenn beim Abgleich vorhandene Daten nicht überschrieben werden sollen.

|**Datei**
|Importdatei vom Speicherort wählen.
|====

Erfahren Sie mehr über die Informationen im Bereich **Bearbeitungsstatus**, mögliche Fehlermeldungen und deren Ursachen im folgenden Videotutorial:

video::141644702[vimeo]
[#130]
== Amazon-Herstellerartikeldaten importieren

Im Menü **Datenaustausch » Import » Dynamischer Import** im Bereich **Amazon-Herstellerartikeldaten-Import** importieren Sie Ihre Artikel im Amazon-Datenformat in Ihr plentymarkets System. Wie Sie dazu vorgehen, ist auf der Handbuchseite von **<<multi-channel/amazon#, Amazon  >>** im Kapitel **<<multi-channel/amazon#310, Herstellerartikeldaten von Amazon importieren >>** beschrieben.

[#210]
== eBay-Listings importieren

Im Menü **Datenaustausch » Import » eBay-Listings** importieren Sie eBay-Listings. Es wird sowohl ein Artikelstammdatensatz als auch ein Listing in plentymarkets erstellt. Im Bereich **Bearbeitungsstatus** haben Sie während des Importprozesses Einsicht in den aktuellen Verlauf des Imports. Wie Sie die Listings importieren, ist auf der Handbuchseite von **<<multi-channel/ebay#, eBay  >>** im Kapitel **<<multi-channel/ebay#11000, eBay-Listings importieren >>** beschrieben.

== Anwendungsbeispiel: Artikel erstellen und Artikeldaten anpassen

Im Menü **Datenaustausch** erstellen Sie Artikel oder ändern bestehende Artikeldaten. Diese Funktion bietet sich an, wenn Sie z.B. Artikellisten von Ihrem Lieferanten in plentymarkets importieren möchten oder den Preis Ihrer Artikeln anpassen möchten. Erstellen Sie zunächst das Datenformat **Item** im Menü **Datenaustausch » Export » Dynamischer Export**. Exportieren Sie dann die Daten in eine Datei und bearbeiten Sie die Daten in der Datei. Abschließend importieren Sie diese Datei im Menü **Datenaustausch » Import » Dynamischer Import**.

Erfahren Sie mehr über das Erstellen und Aktualisieren von Artikeldaten im folgenden Videotutorial:

video::140275175[vimeo]
[#60]
== Anwendungsbeispiel: Varianten importieren

Der Variantenimport erfolgt nicht automatisch mit dem Import Ihrer Artikel. Die folgenden Voraussetzungen müssen erfüllt sein, damit Sie Varianten erstellen und diese dann in Ihr plentymarkets System importieren können:

* Artikel müssen erstellt sein
* Attribute und Attributwerte müssen erstellt sein
* Attribute müssen mit dem Artikel verknüpft sein

Wenn die drei oben genannten Voraussetzungen erfüllt sind und Sie bereits Artikel, Attribute und Attributwerte erstellt haben und diese miteinander verknüpft haben, fahren Sie fort mit dem Kapitel <<basics/datenaustausch/daten-importieren#100, **Varianten erstellen** >>.

Wie Sie die genannten Voraussetzungen mit Hilfe von Importen realisieren und welche Datenformate Sie dafür nutzen, erfahren Sie in den folgenden Kapiteln. Im Folgenden finden Sie eine Schnellübersicht der notwendigen Datenformate:

* Datenformat **Item** zum <<basics/datenaustausch/daten-importieren#70, **Import von Artikeln** >>
* Datenformat **Attribute** zum <<basics/datenaustausch/daten-importieren#80, **Import von Attributen und Attributwerten** >>
* Datenformat **ItemAttribute** zur <<basics/datenaustausch/daten-importieren#90, **Verknüpfung von Artikeln mit Attributen** >>

[#70]
=== Artikel importieren

Artikel werden mit dem Datenformat **Item** erstellt. Erstellen Sie das Datenformat im Menü **Datenaustausch » Export » Dynamischer Export**. Beachten Sie die Hinweise zu den Pflichtfeldern auf der Handbuchseite **<<basics/datenaustausch/datenformate/item#, Item  >>**.

Importieren Sie nun die Artikel. Die Artikel stehen im Menü **Artikel » Artikel bearbeiten** zur weiteren Bearbeitung zur Verfügung.

[.instruction]
Artikel importieren:

. Öffnen Sie das Menü **Datenaustausch » Import » Dynamischer Import**.
. Wählen Sie das Trennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus dem Dropdown-Menü **Format** das Datenformat, das Sie für den Artikel angelegt haben.
. Wählen Sie eine Option unter **Wenn beim Abgleich keine Übereinstimmung**.
. Klicken Sie auf **Datei auswählen**.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf **Import**.

[#80]
=== Attribute und Attributwerte importieren

Attribute und Attributwerte werden mit dem Datenformat **Attribute** erstellt. Erstellen Sie das Datenformat im Menü **Datenaustausch » Export » Dynamischer Export**. Beachten Sie die Hinweise zu den Pflichtfeldern auf der Handbuchseite **<<basics/datenaustausch/datenformate/attribute#, Attribute  >>**.

Importieren Sie nun die Attribute sowie die Attributwerte. Die Attribute und die Attributwerte stehen im Menü **<<artikel/artikel-verwalten#390, Einstellungen » Artikel » Attribute >>** zur weiteren Bearbeitung zur Verfügung.

[.instruction]
Attribute und Attributwerte importieren:

. Öffnen Sie das Menü **Datenaustausch » Import » Dynamischer Import**.
. Wählen Sie das Trennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus dem Dropdown-Menü **Format** das Datenformat, das Sie für das Attribut angelegt haben.
. Wählen Sie eine Option unter **Wenn beim Abgleich keine Übereinstimmung**.
. Klicken Sie auf **Datei auswählen**.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf **Import**.

[#90]
=== Attribute mit dem Artikel verknüpfen

Das Spezialformat **ItemAttribute** dient ausschließlich zum Import von Verknüpfungen zwischen Attributen und Artikeln. Ein Exportformat ist daher nicht vorhanden. Sie müssen dieses Datenformat nicht erstellen. Es steht als Spezialformat im Menü **Datenaustausch » Import » Dynamischer Import** zur Verfügung. Beachten Sie die Erläuterungen zu den Datenfeldern in Tabelle 2.

Die Verknüpfung erfolgt anhand der Pflichtfelder **item_id** und **attribute_list**. Bei der Verknüpfung werden dem Artikel die Attribute zugewiesen und gleichzeitig für den Artikel aktiviert.

.Datenfelder des Datenformats **ItemAttribute**
[cols="a,a"]
|====
|Datenfeld |Erläuterung

|**attribute_list**
|Attributwerte. +
Hash-Aufbau: Attribut1:Wert1:Aufpreis;Attribut2:Wert2:Aufpreis +
**Attribut1** = Name des Attributs. +
**Wert1** = Name des Wertes des Attributs. +
(Optional) **Aufpreis** = Betrag des Aufpreises des Wertes in Euro (Euro und Cent getrennt durch einen Punkt). +
__**Beispiel**__: **Hutgröße:54:2.00** (Backend-Attributname:Backend-Wertname:Aufpreis). Im Attributnamen oder im Namen des Wertes darf kein Doppelpunkt verwendet werden, da dies zu einem fehlerhaften Datenimport führen würde.

|**external_item_id**
|Externe Artikel-ID

|**ean**
|EAN des Artikels zur Artikelbestimmung

|**item_id**
|Artikel-ID

|**item_no**
|Artikelnummer
|====

[IMPORTANT]
.Pflichtfelder
====
Pflichtfelder für den Datenimport: **attribute_list** und **item_id**.
====

[.instruction]
Attribute verknüpfen:

. Öffnen Sie das Menü **Datenaustausch » Import » Dynamischer Import**.
. Wählen Sie das Trennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus dem Dropdown-Menü **Format** das Spezialformat **ItemAttribute**.
. Wählen Sie eine Option unter **Wenn beim Abgleich keine Übereinstimmung**.
. Klicken Sie auf **Datei auswählen**.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf **Import**.

[#100]
=== Varianten erstellen

Um Varianten zu erstellen, benötigen Sie das Datenformat **<<basics/datenaustausch/datenformate/attributeitemvariation#, AttributeItemVariation  >>**. Die Datenfelder **ItemID**, **PriceID**, **VariationString** und **EAN** müssen mindestens aktiviert sein.

Die folgenden Voraussetzungen müssen erfüllt sein:

* Der Artikel ist erstellt.
* Die Attribute und Attributwerte sind erstellt.
* Die Attribute sind mit dem Artikel verknüpft und Werte sind am Artikel verknüpft, um eine Variante daraus erzeugen zu können.

[.instruction]
Varianten erstellen:

. Öffnen Sie das Menü **Datenaustausch » Import » Dynamischer Import**.
. Wählen Sie das Feldtrennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus dem Dropdown-Menü **Format** das Datenformat **AttributeItemVariation**.
. Wählen Sie eine Option unter **Wenn beim Abgleich keine Übereinstimmung**.
. Klicken Sie auf **Datei auswählen**.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf **Import**.

Das folgende Videotutorial veranschaulicht den Umgang mit dem Datenformat **AttributeItemVariation**:

video::139685582[vimeo]
[#120]
== Anwendungsbeispiel: Warenbestand importieren

Sie haben auch die Möglichkeit, den kompletten Warenbestand zu importieren, bei dem aktuelle physische Warenbestände in Ihrem plentymarkets System überschrieben werden. Nutzen Sie dazu das Datenformat **<<basics/datenaustausch/datenformate/stock#, Stock  >>**.

[WARNING]
.Warenbestand wird gelöscht
====
Bei diesem Vorgang werden die aktuellen physischen Warenbestände durch den Import ersetzt, d.h. Ihr gesamter Warenbestand wird gelöscht. Reservierte Warenbestände bleiben dabei erhalten.

Wenn Sie nicht den kompletten Warenbestand importieren möchten, sondern nur Wareneingänge per Datenimport hinzufügen möchten, verwenden Sie das Spezialformat **IncomingItems** (siehe Kapitel <<basics/datenaustausch/daten-importieren#50, **Wareneingangsdaten importieren** >>).
====

Wenn Sie die Importdatei vor dem Import bearbeiten möchten, beachten Sie die folgenden Erläuterungen zu den Datenfeldern. Tabelle 3 erläutert eine Auswahl der in der exportierten Datei enthaltenen Datenfelder.

.Dynamischer Import; Datenfelder des Datenformats **Stock**
[cols="a,a"]
|====
|Feldname |Erläuterung

|**ItemID**
|Artikel-ID

|**VariationEAN**
|EAN-Code der Variante

|**PurchasePrice**
|Einkaufspreis

|**VariationNo**
|Variantennummer

|**LocationID**
|Lagerort-ID +
Jeweils die Ziffer 0 eingeben, wenn kein Lagerort vorhanden ist oder keine Zuordnung erfolgen soll.

|**Stock**
|Warenbestand

|**WarehouseID**
|ID des Lagers

|**VariationString**
|Systemnamen-Hash der Attribute und Werte. +
__**Beispiel**__: "Farbe:Blau;Größe:XXL" +
Die Namen bzw. Bezeichnungen der Attribute und Werte werden verwendet.
|====

[.instruction]
Datenimport durchführen:

. Öffnen Sie das Menü **Datenaustausch » Import » Dynamischer Import**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 4.
. Klicken Sie auf **Import**.

.Dynamischer Import; Importoptionen des Datenformats **Stock**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Feldtrennzeichen**
|Trennzeichen wählen.

|**Format**
|Datenformat **Stock** für den Import wählen.

|**Lager**
|Lager für den Import wählen.

|**Barcode**
|Barcode für den Import wählen.

|**Datei**
|Datei für den Import wählen.
|====

Sie erhalten im Menü **Datenaustausch » Import » Dynamischer Import** im Bereich **Bearbeitungsstatus** eine detaillierte Meldung des Datenimports. Unter anderem werden das Format, der Dateiname, der Benutzer und das Datum des Imports in diesem Bereich angezeigt.

