= Daten importieren
:lang: de
include::{includedir}/_header.adoc[]
:description: Erfahren Sie, wie Sie Datenformate erstellen und den dynamischen Import nutzen.
:position: 20

Diese Handbuchseite befasst sich mit den verschiedenen Möglichkeiten des Datenimports in plentymarkets. Insbesondere die Möglichkeiten des ElasticSync-Plugins werden erläutert. ElasticSync erlaubt sowohl einmalige manuelle Importe als auch regelmäßige automatisierte Importe.
Außerdem werden die Möglichkeiten des manuellen Datenimport per dynamischen Import beschrieben. Ein Import von Daten ist ratsam, wenn Sie z.B. neue Artikel, Kundendaten oder Lagerbestände in Ihr plentymarkets System einpflegen möchten und die Daten bereits digital vorliegen.

== Daten per ElasticSync importieren

**ElasticSync** ermöglicht es über das Anlegen von sogennanten **Syncs**, Datenimporte
auszuführen. Ein Import kann manuell oder automatisiert erfolgen.

=== Allgemeine Beschreibung: Daten per Sync importieren

Die grundsätzliche Funktionsweise zum Erstellen und Importieren eines Syncs ist für alle Sync-Typen gleich und wird hier einmal übergreifend beschrieben. Anschließend folgt für jeden Sync-Typ zusätzlich eine detaillierte Beschreibung.

==== Sync erstellen

Syncs erstellen, bearbeiten und verwalten Sie im Menü **Daten » ElasticSync**. Ein Sync dient dazu, die Daten einer per FTP oder HTTP zugänglichen Datei Daten in plentymarkets zuzuordnen und zu importieren. Beim Erstellen des Syncs speichern Sie Informationen zur Datenquelle und legen ein Importintervall fest. Wichtig für einen Sync ist außerdem, dass Sie Daten für den Abgleich festlegen und zurodnen welche Daten Ihrer Datei welchen Daten in plentymarkets entsprechen. Mit dem Abgleich legen Sie fest, anhand welcher Daten versucht wird zu identifizieren, ob bereits ein Datensatz besteht oder nicht. Mit der Zuordnung legen Sie fest welche Spalte Ihrer Datei welchem Datenfeld in plentymarkets entspricht. Gehen Sie wie beschrieben vor, um einen Sync zu erstellen.

[.instruction]
Sync erstellen:

. Öffnen Sie das Menü **Daten » ElasticSync**.
. Klicken Sie auf **Sync hinzufügen**. +
    → Der Bearbeitungsbereich **Neuer Sync** wird angezeigt.
. Nehmen Sie Einstellungen vor. Beachten Sie dazu die Angaben in Tabelle 1.
. **Speichern** Sie die Einstellungen. +
    → Der Sync wird erstellt und die Abgleicheinstellungen des Syncs werden direkt geöffnet.

.Sync erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Grunddaten

|Name
|Name eingeben. Dieser Name wird in der Übersicht angezeigt und kann für die Suche genutzt werden.

|Typ
|Typ aus Dropdown-Liste wählen. +
* *Artikel* = Wählen, um Artikeldaten und Variatendaten zu importieren, siehe <a>Sync-Typ Artikel
* *Kategorien* = Wählen, um Kategriedaten zu importieren, siehe <a>Sync-Typ Kategorien
* *Attribute* = Wählen, um Attributdaten zu importieren.
* *Merkmale* = Wählen, um Merkmaldaten zu importieren.
* *Notizen* = Wählen, um Notizdaten zu importieren.
* *Aufträge* = Wählen, um Auftragsdaten zu importieren.
* *Kontakte, Firmen und Adressen* = Wählen, um Kontakt-, Firmen- und Adressdaten zu importieren, siehe <a>Sync-Typ Kontakte, Firmen und Adressen.

2+|Quelle

|Datentyp
|Dateiformat der Importdatei wählen. +
Aktuell ist jedoch nur die Auswahl *CSV* verfügbar, da nur CSV-Dateien importiert werden können.

|Trennzeichen
|Trennzeichen wählen, das in der Importdatei verwendet wird, um die Datenfelder (Spalten) eines Datensatzes voneinander zu trennen.

|Feldbegrenzungszeichen
|Begrenzungszeichen innerhalb von Felder wählen, die mehrere Werte enthalten können.
" = einzelne Werte innerhalb eines Feldes sind durch doppelte Anführungszeichen voneinander getrennt.
' = einzelne Werte innerhalb eines Feldes sind durch einfache Anführungszeichen voneinander getrennt.

|Zeichensatz
|Zeichensatz der Datei oder Automatisch erkennen wählen.

|Beginne ab Zeile
|Wählen, ab welcher Zeile der Datei Daten importiert werden sollen.

|Quelle
|Zwischen FTP und HTTP wählen. +
Je Option werden weitere Einstellungen sichtbar:

*FTP* = Host, Benutzername, Passwort und Dateiname werden als Einstellungen sichtbar

    * Host: Host des FTP-Servers eingegeben +
      Tipp: plentymarkets FTP-Zugang nutzen.
    * Benutzer: Benutzer für FTP-Zugang eingeben
    * Passwort: Passwort für FTP-Zugang eingeben
    * Dateiname: Pfad und Name der Datei eingeben, aus der Daten importiert werden sollen

*HTTP* = Zwischen *Externe URL* und *Dateiupload* wählen

    * Externe URL: URL eingeben, unter der die Importdatei erreichbar ist +
     Tipp: Datei auf plentymarkets Webspace speichern
      ** Authentifizierung: Wählen, ob für den Zugriff auf die Datei eine Authentifizierung erforderlich ist oder nicht.
        ***  keine = keine Authentifizierung erforderlich
        ***  HTTP-Authentifizierung = Authentifizierung per Benutzer und Passwort erforderlich
    * Dateiupload: lokale Datei hochladen +
    Wichtig: Die Datei wird auf einem öffentlichen Bucket auf S3 gespeichert. Jeder der die URL zu der Datei kennt, kann somit auf die Datei zugreifen.
|====

==== Abgleich festlegen

Nachdem Sie einen Sync erstellt haben, öffnen Sie ihn nun, um weitere Einstellungen vorzunehmen. Zunächst wählen Sie die Felder, die zum Abgleichen der Daten verwendet werden sollen. Legen Sie außerdem fest, was passieren soll, wenn durch den Abgleich keine bestehenden Daten gefunden werden.

[NOTE]
.Abgleich ist optional
====
Bei den Abgleichfeldern handelt es sich um optionalle Einstellungen. Wenn Sie kein Abgleichfeld wählen, können die Daten Ihrer Datei keinen bestehenden Daten in Ihrem System zugeordnet werden. Sie können eins, mehrere oder alle Abgleichfelder festlegen. Die angezeigten Abgleichfelder unterscheiden sich für jeden Sync-Typ.
====

[.instruction]
Abgleich festlegen:

. Öffnen Sie das Menü Daten » ElasticSync.
. Klicken Sie in der Sync-Übersicht auf den gewünschten Sync. +
→ Die Abgleichoptionen des Syncs werden angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Angaben in Tabelle 2.
. Speichern Sie die Einstellungen. +
→ Die Einstellungen werden gespeichert.

==== Zuordnung erstellen

Mithilfe einer Zuordnung legen Sie fest welche Spalte Ihrer Datei welchem Datenfeld in Ihrem System entspricht. Ohne Zuordnung können keine Daten importiert werden.

[.instruction]
Zuordnung festlegen:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Klicken Sie in der Sync-Übersicht auf den gewünschten Sync. +
→ Die Abgleichoptionen des Syncs werden angezeigt.
. Klicken Sie auf *Zuordnung*. +
→ Eine Übersicht der Zuorndung wird angezeigt. Zunächst ist die Liste leer.
. Klicken Sie auf *Zuordnung hinzufügen*.
. Geben Sie einen Namen für die Zuordnung ein.
. Geben Sie optional eine Position für die Zuordnung ein.
. *Speichern* Sie die Einstellungen. +
→ Die Zuordnung wird der Übersicht hinzugefügt.
. Öffnen Sie die gewünschte Zuordnung. +
→ Die verfügbaren Zuordnungsfelder unterscheiden sich je nach Sync-Typ.
. Wählen Sie Datenfelder für die Zuordnung aus, indem Sie Häkchen bei diesen Felder setzen. +
→ Die gewählten Datenfelder werden zur Zuordnung hinzugefügt.
. Wählen Sie für jedes Datenfeld eine Spalte aus Ihrer Datei oder die Option *Eigener Wert*.
. *Speichern* Sie die Einstellungen.

[NOTE]
.Eigener Wert
====
Die Option *Eigener Wert* erlaubt Ihnen für ein Datenfeld einen festen Wert zu importieren. Dieser feste Wert ist somit für jeden Datensatz, der durch diesen Sync importiert wird gleich.
====

==== Importdaten eingrenzen

Mithilfe von Filtern können Sie die Daten eingrenzen, die importiert werden. Die Filter finden Sie im Bereich Zuordnung.

[NOTE]
.Mehrere Filter sind durch Und verknüpft
====
Wenn Sie mehrere Filter verwenden, werden nur Datensätze importiert auf die alle Filter zutreffen. Es handelt sich also um eine Und-Verknüpfung der Filter.
====

[.instruction]
Filter hinzufügen:

. Öffnen Sie das Menü *Daten » ElasticSync*.
. Klicken Sie in der Sync-Übersicht auf den gewünschten Sync. +
→ Die Abgleichoptionen des Syncs werden angezeigt.
. Klicken Sie auf *Zuordnung*. +
→ Eine Übersicht der Zuorndung wird angezeigt.
. Öffnen Sie die gewünschte Zuordnung.
. Klicken Sie in der Symbolleiste auf *Filter*.
. Wählen Sie die Spalte aus Ihrer Datei, die Sie filtern möchten.
. Wählen Sie einen Operator.
. Tragen Sie einen Wert ein.
. Klicken Sie auf *Filter hinzufügen*. +
→ Der Filter wird gespeichert und Sie können weitere Filter hinzufügen.

==== Sync testen und Daten importieren

In der Sync-Übersicht können Sie Syncs testen und ausführen. Die Sync-Übersicht erreichen Sie über das Menü *Daten » ElasticSync*.

==== Sync-Verlauf einsehen

In der Sync-Übersicht können Sie den Verlauf Ihrer ausgeführten Syncs einsehen. Die Sync-Übersicht erreichen Sie über das Menü *Daten » ElasticSync*.

=== Sync vom Typ Artikel einrichten

Mit Syncs des Typs *Artikel* importieren Sie Artikel- und Variantendaten.

Erfahren Sie mehr zum Importieren neuer Artikel im folgenden Videotutorial:

.Artikel per ElasticSync importieren
video::219060209[vimeo]

[.subhead]
Felder für den Artikelabgleich

In der Tabelle <<tabelle-Abgleichfelder-Artikel>> werden Ihnen Felder erläutert, die für den Abgleich von Artikeldaten zur Verfügung stehen. Anhand des gewählten Feldes wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Abgleichfelder-Artikel]]
.Abgleichfelder für Artikelimport
[cols="1,2"]
|====
|Abgleichfeld |Erläuterung

|Varianten-ID
|

|Variantennr.
|

|Externe Varianten-ID
|

|Barcode
|Aus der zweiten Dropdown-Liste den Barcode-Typ des Barcodes wählen.

|Artikel-ID
|Bei Varianten mit Attributen dieses Feld nur in Kombination mit Attributauswahlkombination nutzen.


|Attributauswahlkombination
|Bei Varianten mit Attributen dieses Feld nur in Kombination mit Artikel-ID nutzen.
Aus der zweiten Dropdown-Liste das Format wählen, in dem die Daten in der Datei vorliegen.

|Lieferanten-Artikel-Nr.
|

|====

[.subhead]
Felder für die Artikelzuordnung

In der Tabelle <<tabelle-Zuordnungsfelder-Artikel>> werden Ihnen Felder erläutert, die für den Abgleich von Artikeldaten zur Verfügung stehen. Anhand des gewählten Feldes wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-Zuordnungsfelder-Artikel]]
.Abgleichfelder für Artikelimport
[cols="1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

3+|Artikel

|Typ
|0 = Lagerware +
1 = Produktionsware +
2 = Colli +
3 = Bestellware
|

|Shop-Aktion
|0 = keine +
1 = Sonderangebot +
2 = Neuheit +
3 = Top-Artikel
|

|Eigner
|Nummerisch (interne User-ID)
|

|Hersteller-ID
|Nummerisch (interne ID)
|

|Herstellerland
|Nummerisch (interne ID); +
0 = unbekannt
|

|Zolltarifnummer
|Nummerisch
|

|Erlöskonto
|
|

|Aktionsgutschein
|0 = Möglich +
1 = Verboten +
2 = Nur mit Gutschein kaufbar
|

|Zustand
|0 = Neu +
1 = Gebraucht +
2 = Neu und originalverpackt +
3 = Neu mit Etikett +
4 = B-Ware
|Artikelzustand

|Zustand API
|0 = Neu +
1 = Gebraucht wie neu +
2 = Gebraucht sehr gut +
3 = Gebraucht gut +
4 = Gebraucht annehmbar +
5 = B-Ware
|Zustand des Artikels; Übertragung über API an andere Marktplätze

|Abonnement (ja/nein)
|0 = Nein +
1 = Ja 	Kann Artikel als Abo bestellt werden?
Seriennummer (ja/nein) 	0 = Nein
1 = Ja 	Seriennummer zuweisen?
Versandpaket (ja/nein) 	0 = Nein
1 = Ja 	Versandpaket verwenden?
Amazon-Abwicklung (FBA) 	0 = Nicht verwenden
1 = AMAZON EU
2 = AMAZON FE
3 = AMAZON NA
-1 = FBA und SellerCentral
Versand durch Amazon (FBA) 	0 = Nein
1 = Ja 	FBA-Versand?
Amazon-Produkttyp 	Nummerisch
Amazon-FEDAS 		FEDAS-Warengruppenschlüssel
Listing-Vorlage 	Nummerisch (interne ID)
Listing Kategorie 1;
Listing Kategorie 2 	Nummerisch
Listing Shop-Kategorie 1;
Listing Shop-Kategorie 2 	Nummerisch
Rakuten.de-Kategorien 	Nummerisch (interne ID)
Markierung 1;
Markierung 2
Altersfreigabe 	0 = Keine verfügbar
3 = FSK 3
6 = FSK 6
12 = FSK 12
16 = FSK 16
18 = FSK 18
50 = Nicht gekennzeichnet
88 = Nicht erforderlich
99 = Noch nicht bekannt 	FSK
Artikelbewertung 	Nummerisch 	Erstbewertung von 1 bis 5 bzw. 1 bis 10
Herstellername 	Alphanummerisch 	Wenn nicht im System, wird neuer Hersteller angelegt.
Artikel löschen 	0 = Nein
1 = Ja
Artikelbeschreibung (Zuordnung pro Sprache)
Name 	Alphanummerisch
Name 2;
Name 3 	Alphanummerisch
Vorschautext 	Alphanummerisch
Meta-Beschreibung 	Alphanummerisch
Artikeltext 	Alphanummerisch
Technische Daten 	Alphanummerisch
URL-Pfad 	Link
Meta-Keywords 	Alphanummerisch
Versandprofil
Versandprofil-ID 	Nummerisch
Artikel-Tags
Tag-ID 	Nummerisch
Tag-Name 	Alphanummerisch
Tag-Namen (kommasepariert) 	Alphanummerisch 	Tag-Liste
Alle verknüpften Tags löschen 	0 = Nein
1 = Ja 	Alle Verknüpfungen aufheben?
Varianten
ID 	Nummerisch
Artikel-ID 	Nummerisch
Position 	Nummerisch
Aktiv 	0 = Nein
1 = Ja 	Ist Variante aktiv, d.h. wird sie im Webshop und ggf. auf Marktplätzen angeboten?
Variantennr. 	Alphanummerisch
Modell 	Alphanummerisch 	Modellbezeichnung
Externe Varianten-ID 	Alphanummerisch
Verfügbarkeit 	Nummerisch (interne ID)
EK netto 	Nummerisch 	Einkaufspreis
Preiskalkulation 	Nummerisch (interne ID)
VPE 	Nummerisch 	Verpackungseinheit; Standard = 1
Anzahl der Packstücke 	Nummerisch
Einheit der Packstücke 	Nummerisch
0 = unverpackt
1 = Ballen
2 = Behälter
3 = Bund
4 = Rollpalette
5 = Colli
6 = Container
7 = Eimer
8 = Fass
9 = Flaschen
10 = Euro Pool Flachpalette
11 = Gestell
12 = Gasflasche
13 = Gitterboxpalette
14 = Hobbock
15 = Halbe Palette
16 = Lebensmittelpalette
17 = Holzuntersetzer
18 = IBC Container
19 = Kanne
20 = Korbflasche
21 = Kiste
22 = Kanister
23 = Kundenpalette
24 = Karton
25 = Kombinationsverpackung
26 = Pack
27 = Ring
28 = Rolle
29 = Sack
30 = Stück
31 = Tank
32 = Trommel
34 = Verschlag
35 = Viertelpalette
36 = sonstige Paletten
37 = Kasten
38 = Einwegpalette
39 = Folientüte
Transportkosten netto 	Nummerisch
Lagerkosten netto 	Nummerisch
Zoll 	Nummerisch 	Prozentwert
Betriebskosten 	Nummerisch 	Prozent
Umsatzsteuer 	Nummerisch (%)
Paketart 	bundle = Variante ist Paket
bundle_item = Variante ist Paketbestandteil
Unsichtbar in Artikellisten 	0 = Nein
1 = Ja
Kommissionierung 	single_picking = Einzelkommissionierung möglich
no_single_picking = Keine Einzelkommissionierung möglich
exclude_from_picklist = Von Pickliste ausschließen
WB-Beschränkung 	0 = Keine Beschränkung
1 = Auf Netto-WB
2 = Keinen Bestand führen
Webshop: Sichtbar wenn Netto-WB positiv 	0 = Nein
1 = Ja
Webshop: Unsichtbar wenn kein Netto-WB 	0 = Nein
1 = Ja
Verfügbar wenn Netto-WB positiv 	0 = Nein
1 = Ja
Nicht verfügbar wenn kein Netto-WB 	0 = Nein
1 = Ja
Hauptlager 	Nummerisch (interne ID)
Max. Bestellmenge 	Nummerisch
Min.-Bestellmenge 	Nummerisch
Intervallbestellmenge 	Nummerisch
Grundpreis anzeigen 	0 = Nein
1 = Ja
Variante löschen 	0 = Nein
1 = Ja
Nummer der Hauptvariante 	Alphanummerisch
Verfügbar bis 	Datum 	Datum des letzten Tages der Verfügbarkeit
Erscheinungsdatum 	Datum 	Datum, ab dem die Variante verfügbar ist
Name 	Alphanummerisch 	Name der Variante
Gewicht brutto g 	Nummerisch
Gewicht netto g 	Nummerisch
Breite mm 	Nummerisch
Länge mm 	Nummerisch
Höhe mm 	Nummerisch
Portoaufschlag 1;
Portoaufschlag 2 	Nummerisch
Cross-Selling
Alle Cross-Selling-Verknüpfungen löschen 	0 = Nein
1 = Ja
Cross-Selling-Verknüpfungen hinzufügen 	Alphanummerisch im Format Artikel-ID:Beziehungstyp;Artikel-ID:Beziehungstyp;etc.
Accessory = Zubehör
ReplacementPart = Ersatzteil
Similar = Ähnlich
Bundle = Artikelpaket
Cross-Selling-Verknüpfungen löschen 	Nummerisch im Format Artikel-ID;Artikel-ID;etc.
Barcodes (Zuordnung pro Barcode-Typ)
Code 	Alphanummerisch
Variantenpreis (Zuordnung pro Verkaufspreis)
Preis 	Nummerisch
Kategorien
ID der Kategorie 	Nummerisch (interne ID) 	Alternativ Name der Kategorie übergeben.
Position 	Nummerisch
Ist Neckermann.de Hauptkategorie 	0 = Nein
1 = Ja
Name der Kategorie 	Alphanummerisch 	Kompletten Kategoriepfad semikolongetrennt angeben (z.B. Schuhe;Unisex)
Alternativ ID der Kategorie übergeben.
Standardkategorien
ID der Kategorie 	Nummerisch (interne ID)
Automatisch ausgewählt 	N = Nein
Y = Ja
Name der Kategorie 	Alphanummerisch
Bestand
Lager 	Nummerisch (interne ID) 	Kann nur in Kombination mit Menge und Lagerort übergeben werden.
Menge 	Nummerisch 	Kann nur in Kombination mit Lager und Lagerort übergeben werden.
Lagerort 	Nummerisch (interne ID) 	Kann nur in Kombination mit Lager und Menge übergeben werden.
Mandant (Shop) (Zuordnung pro Mandant)
Aktiv 	0 = Nein
1 = Ja
Märkte (Zuordnung pro Marktplatz)
Aktiv 	0 = Nein
1 = Ja
Attribute (Zuordnung pro Format)
Attributauswahlkombination 	Alphanummerisch im Format Attributname:Wertname; oder Attributname<>Wertname<||> 	Import von mehr als zwei Attributverknüpfungen.
Hinweis: Jede Attributkombination muss pro Variante einzigartig sein.
Attribute ID 	Nummerisch 	Import von bis zu zwei Attributverknüpfungen.
Tipp: Bei zwei Verknüpfungen müssen die IDs in verschiedenen Spalten vorliegen. Eine Zuordnung im Format Attributname:Wertname; und eine im Format Attributname<>Wertname<||> erstellen und die separaten Spalten zuordnen.
Attribute Name 	Alphanummerisch 	Import von bis zu zwei Attributverknüpfungen.
Tipp: Bei zwei Verknüpfungen müssen die Namen in verschiedenen Spalten vorliegen. Eine Zuordnung im Format Attributname:Wertname; und eine im Format Attributname<>Wertname<||> erstellen und die separaten Spalten zuordnen.
Wert Name 	Alphanummerisch 	Import von bis zu zwei Attributverknüpfungen.
Tipp: Bei zwei Verknüpfungen müssen die Namen in verschiedenen Spalten vorliegen. Eine Zuordnung im Format Attributname:Wertname; und eine im Format Attributname<>Wertname<||> erstellen und die separaten Spalten zuordnen.
Wert ID 	Nummerisch 	Import von bis zu zwei Attributverknüpfungen.
Tipp: Bei zwei Verknüpfungen müssen die IDs in verschiedenen Spalten vorliegen. Eine Zuordnung im Format Attributname:Wertname; und eine im Format Attributname<>Wertname<||> erstellen und die separaten Spalten zuordnen.
Artikel Bilder
ID des Bilds 	Nummerisch (interne ID)
Position 	Nummerisch
Dateiname 	Alphanummerisch
Base64 Data 	Alphanummerisch
Verfügbarkeit Mandant (Shop) 	Nummerisch (interne ID) 	-1 aktiviert alle Mandanten
Verfügbarkeit Herkünfte 	Nummerisch (interne ID) 	-1 aktiviert alle Herkünfte
Verfügbarkeit Listings 	Nummerisch (interne ID) 	-1 aktiviert alle Listings
URL 	Link
Name 	Alphanummerisch im Format Name:Sprache1,Name:Sprache2
Multi-URL (kommasepariert) 	Alphanummerisch im Format image1url;positionImage1,image2url;positionImage2 	Wenn keine Position übergeben wird, enspricht die Position der Reihenfolge der URLs.
Bilder löschen 	0 = Nein
1 = Ja 	1 löscht alle Bilder des Artikels. Bilder, die erhalten bleiben sollen, müssen als URL im Sync angegeben werden.
Mit Variante verknüpfen 	0 = Nein
1 = Ja 	1 verknüpft das Bild mit der Variante. 0 löscht eine vorhandene Verknüpfung.
Merkmale
ID 	Nummerisch (interne ID)
Wert 	Alphanummerisch
Sprache 	Buchstaben 	Nur bei Text
Merkmalkombination 	Alphanummerisch 	Kombination aus Backend-Name, Wert und Sprache im Format Name1:Wert1:Sprache1;Name2:Wert2:Sprache2 etc.
Inhalt
Inhalt Einheit 	Nummerisch (interne ID) 	Alternativ Inhalt Maßeinheit (ISO) übergeben
Inhalt Menge 	Nummerisch 	Kann nur in Kombination mit Inhalt Einheit oder Inhalt Maßeinheit (ISO) übergeben werden.
Inhalt Maßeinheit (ISO) 	Alphanummerischer ISO-Code 	Alternativ Inhalt Einheit übergeben
ASIN/ePID
Land 	Nummerisch (interne ID)
Typ 	ASIN; ePID
Wert 	Alphanummerisch
Lager (Zuordnung pro Lager)
Zone 	Nummerisch
Lagerorttyp 	none = kein
small = klein
medium = mittel
large = groß
europallet = Europalette
Meldebestand 	Nummerisch
Maximalbestand 	Nummerisch
Lagerort 	Nummerisch (interne ID)
Bestandspuffer 	Nummerisch
Lieferant
EK 	Nummerisch
Mindestabnahme 	Nummerisch
Lieferanten-Artikel-Nr. 	Alphanummerisch
Letzte Preisabfrage 	Datum
Lieferzeit in Tagen 	Nummerisch
Rabatt 	Nummerisch 	Prozent
Rabattfähigkeit 	0 = Nein
1 = Ja
Verpackungseinheit 	Nummerisch
Lieferanten-ID 	Nummerisch
Lieferanten-Name 	Alphanummerisch
SKU
Marktplatz-ID 	Nummerisch
Account-ID 	Nummerisch
SKU 	Alphanummerisch
Parent-SKU 	Alphanummerisch
Paket
Paketbestandteile 	Alphanummerisch 	Varianten-ID:Menge;Varianten-ID:Menge;etc.
Paketbestandteile löschen 	Alphanummerisch 	Varianten-ID des Paketbestandteils
Paket löschen 	0 = Nein
1 = Ja

|====

Um Artikeldaten per ElasticSync zu importieren, müssen die folgenden Datensätze in plentymarkets vorhanden sein:

* Kategorien (Artikel » Kategorien)
* Verkaufspreise (Einstellungen » Verkaufspreise)

Um Variantendaten mit Attributen per ElasticSync zu importieren, müssen die folgenden Datensätze in plentymarkets vorhanden sein:

* Attribute und Attributwerte (Einstellungen » Artikel » Attribute)


---Beachten Sie, dass pro Import maximal 6000 Datensätze möglich sind. +
In den letzten Kapiteln auf dieser Handbuchseite werden Anwendungsbeispiele beschrieben.---


Eine Einführung zum dynamischen Import erhalten Sie im folgenden Videotutorial:

video::119849465[vimeo]
[#10]
== Datenformat erstellen

Das Datenformat, das Sie importieren, muss der Konfiguration des Datenformats in plentymarkets entsprechen, damit die Daten zugeordnet werden. Hierzu gehört auch, dass die Schreibweise der Datenfelder der Schreibweise in plentymarkets entspricht. Auf der Handbuchseite eines <<basics/datenaustausch/datenformate#, Datenformats>> finden Sie die Namen der Datenfelder aufgelistet. Beachten Sie auch die Hinweise zur Angabe von Pflichtfeldern und Abgleichfeldern. Sie haben die Möglichkeit, mit Hilfe eines Tabellenkalkulationsprogramms selbst eine Datei für den Import zu erstellen.

Sie können sich diese Arbeit erheblich erleichtern, indem Sie das Datenformat vorab in eine Datei exportieren, Ihre Daten in der Datei bearbeiten und diese dann wieder importieren. Diese Vorgehensweise ist nur bei Datenformaten möglich, die sowohl einen Import als auch einen Export erlauben. Weitere Informationen zum Umgang mit Export- und Importdateien finden Sie im Kapitel <<basics/datenaustausch/daten-exportieren#05, Datei für den Datenaustausch anpassen>> auf der Handbuchseite **Daten exportieren**. Gehen Sie wie im Folgenden beschrieben vor, um Ihre Daten in eine Datei zu exportieren:

[.instruction]
Datenformat erstellen:

. Öffnen Sie das Menü **Daten » Dynamischer Export**.
. Wechseln Sie in das Tab **Neues Datenformat**.
. Wählen Sie einen **Datenformat-Typ** aus der Dropdown-Liste.
. Ändern Sie ggf. den automatisch vergebenen **Datenformatsname**.
. Aktivieren Sie die Datenfelder, die in der Exportdatei vorhanden sein sollen.
. Wählen Sie eine **Importaktion** pro Datenfeld. +
→ Beachten Sie die Hinweise zu Abgleichfeldern auf den Unterseiten der Handbuchseite <<basics/datenaustausch/datenformate#, Datenformate>>.
. Wählen Sie ggf. **Filter** oder **Aktionen**.
. **Speichern** Sie das Datenformat. +
→ Die Reihenfolge der Datenfelder wird anhand der Werte in der Spalte **Position** gespeichert.

[TIP]
.Importaktionen für Datenfelder wählen[#25]
====
Bei einem Datenformat stehen für die Datenfelder die Importaktionen **Abgleich** und **Import** zur Verfügung. +
Mit der Einstellung **Import** werden die Daten, importiert - unabhängig davon, ob bereits Daten vorhanden sind oder nicht. Das bedeutet, dass die Daten bei einem Import eventuell überschrieben werden. Mit der Einstellung **Abgleich** wird das Datenfeld vor einem Import mit bereits im System vorhandenen Daten abgeglichen. Die Daten werden nur importiert, wenn noch keine Daten vorhanden sind.
====

[#20]
== Dynamischen Import nutzen

Der dynamische Datenimport erfolgt im Menü **Daten » Dynamischer Import**. Sie können hier selbst erstellte Dateien oder die Datenformate, die Sie im Menü **Daten » Dynamischer Export** erstellt haben (sog. Kundenformate), wieder importieren. Im Menü **Daten » Dynamischer Import** stehen Ihnen neben den Kundenformaten in der Dropdown-Liste **Format** drei Spezialformate zur Verfügung:

* das Spezialformat **IncomingItems**, mit dem sie Wareneingangsdaten importieren
* das Spezialformat **ItemAttribute**, mit dem Sie Artikel und Attribute verknüpfen
* das Spezialformat **ItemParcelServicePreset**, mit dem Sie Versandprofile importieren

Die Spezialformate sind reine Importformate und stehen daher nur im Menü **Daten » Dynamischer Import** zur Verfügung. Der Import der Spezialformate funktioniert auf die gleiche Weise, wie Sie auch die anderen Datenformate importieren. Die Vorgehensweise wird im Folgenden beschrieben.

[NOTE]
.Spaltenkopfbezeichnungen prüfen und anpassen
====
Wenn Daten aus einem externen System importiert werden sollen oder Sie Datei selbst erstellt haben, müssen die Spaltenkopfbezeichnungen in der Datei mit der von plentymarkets vorgegebenen Schreibweise der Datenfelder (Feldnamen) exakt übereinstimmen. +
Kann plentymarkets beim Import keine Zuordnung zu einer gewählten Exportvariante herstellen, wird der Import mit einer Fehlermeldung abgebrochen. Die Fehlermeldung finden Sie im Bereich **Bearbeitungsstatus**. Prüfen Sie die Spaltenkopfbezeichnungen der zu importierenden Datei und passen Sie diese bei Bedarf an.
====

[.instruction]
Daten per dynamischen Import importieren:

. Öffnen Sie das Menü **Daten » Dynamischer Import**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. Klicken Sie auf **Import**.
. Prüfen Sie, ob die importierten Daten im System angelegt wurden.

[IMPORTANT]
.Bearbeitungsstatus
====
Nachdem Sie die Datei importiert haben, erhalten Sie eine Meldung im Bereich **Bearbeitungsstatus**. Wenn Datenzeilen erfolgreich importiert wurden, wird die Anzahl der importierten Zeilen angegeben. Im Fehlerfall steht dort der Eintrag **0** und eine Fehlermeldung wird angezeigt. Prüfen Sie das Feldtrennzeichen oder die Codierung der Datei. Die Datei sollte immer UTF-8-codiert sein.
====

Beachten Sie, dass die Einstellungen, die Ihnen angezeigt werden, abhängig sind von dem Datenformat, das Sie für den Import gewählt haben. Für das Datenformat **Stock** z.B. wählen Sie statt einer Abgleichoption das **Lager** und den **Barcode**. Die Einstellungen, die in Tabelle 1 beschrieben sind, gelten für die Mehrheit der Datenformate.

.Einstellungen im Menü **Daten » Dynamischer Import**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Feldtrennzeichen**
|Feldtrennzeichen wählen, das in der Importdatei eingestellt ist.

|**Format**
|Datenformat wählen, das Sie für den Datenimport vorbereitet haben. +
**__Hinweis__**: Je nachdem, welches Datenformat Sie hier wählen, ändern sich die folgenden Einstellungen.

|**Wenn beim Abgleich keine Übereinstimmung**
|Eine der folgenden Optionen wählen:  +
**Neuen Datensatz anlegen** = Wenn die zu importierenden Daten noch nicht im System vorhanden sind. +
**Vorhandenen Datensatz überspringen** = Wenn beim Abgleich vorhandene Daten nicht überschrieben werden sollen.

|**Datei**
|Importdatei vom Speicherort wählen.
|====

Erfahren Sie mehr über die Informationen im Bereich **Bearbeitungsstatus**, mögliche Fehlermeldungen und deren Ursachen im folgenden Videotutorial:

video::141644702[vimeo]


[#210]
== eBay-Listings importieren

Im Menü **Daten » eBay-Listings** importieren Sie eBay-Listings. Es wird sowohl ein Artikelstammdatensatz als auch ein Listing in plentymarkets erstellt. Im Bereich **Bearbeitungsstatus** haben Sie während des Importprozesses Einsicht in den aktuellen Verlauf des Imports. Wie Sie die Listings importieren, ist auf der Handbuchseite von <<omni-channel/multi-channel/ebay-einrichten#, eBay>> im Kapitel <<omni-channel/multi-channel/ebay-einrichten#11000, eBay-Listings importieren>> beschrieben.

== Anwendungsbeispiel: Artikel erstellen und Artikeldaten anpassen

Im Menü **Daten** erstellen Sie Artikel oder ändern bestehende Artikeldaten. Diese Funktion bietet sich an, wenn Sie z.B. Artikellisten von Ihrem Lieferanten in plentymarkets importieren möchten oder den Preis Ihrer Artikeln anpassen möchten. Erstellen Sie zunächst das Datenformat **Item** im Menü **Daten » Dynamischer Export**. Exportieren Sie dann die Daten in eine Datei und bearbeiten Sie die Daten in der Datei. Abschließend importieren Sie diese Datei im Menü **Daten » Dynamischer Import**.

Erfahren Sie mehr über das Erstellen und Aktualisieren von Artikeldaten im folgenden Videotutorial:

video::140275175[vimeo]
////
[#60]
== Anwendungsbeispiel: Varianten importieren

Der Variantenimport erfolgt nicht automatisch mit dem Import Ihrer Artikel. Die folgenden Voraussetzungen müssen erfüllt sein, damit Sie Varianten erstellen und diese dann in Ihr plentymarkets System importieren können:

* Artikel müssen erstellt sein
* Attribute und Attributwerte müssen erstellt sein
* Attribute müssen mit dem Artikel verknüpft sein

Wenn die drei oben genannten Voraussetzungen erfüllt sind und Sie bereits Artikel, Attribute und Attributwerte erstellt haben und diese miteinander verknüpft haben, fahren Sie fort mit dem Kapitel <<basics/datenaustausch/daten-importieren#100, Varianten erstellen>>.

Wie Sie die genannten Voraussetzungen mit Hilfe von Importen realisieren und welche Datenformate Sie dafür nutzen, erfahren Sie in den folgenden Kapiteln. Im Folgenden finden Sie eine Schnellübersicht der notwendigen Datenformate:

* Datenformat **Item** zum <<basics/datenaustausch/daten-importieren#70, Import von Artikeln>>
* Datenformat **Attribute** zum <<basics/datenaustausch/daten-importieren#80, Import von Attributen und Attributwerten>>
* Datenformat **ItemAttribute** zur <<basics/datenaustausch/daten-importieren#90, Verknüpfung von Artikeln mit Attributen>>

[#70]
=== Artikel importieren

Artikel werden mit dem Datenformat **Item** erstellt. Erstellen Sie das Datenformat im Menü **Daten » Dynamischer Export**. Beachten Sie die Hinweise zu den Pflichtfeldern auf der Handbuchseite <<basics/datenaustausch/datenformate/item#, Item>>.

Importieren Sie nun die Artikel. Die Artikel stehen im Menü **Artikel » Artikel bearbeiten** zur weiteren Bearbeitung zur Verfügung.

[.instruction]
Artikel importieren:

. Öffnen Sie das Menü **Daten » Dynamischer Import**.
. Wählen Sie das Trennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus der Dropdown-Liste **Format** das Datenformat, das Sie für den Artikel angelegt haben.
. Wählen Sie eine Option unter **Wenn beim Abgleich keine Übereinstimmung**.
. Klicken Sie auf **Datei auswählen**.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf **Import**.

[#80]
=== Attribute und Attributwerte importieren

Attribute und Attributwerte werden mit dem Datenformat **Attribute** erstellt. Erstellen Sie das Datenformat im Menü **Daten » Dynamischer Export**. Beachten Sie die Hinweise zu den Pflichtfeldern auf der Handbuchseite <<basics/datenaustausch/datenformate/attribute#, Attribute>>.

Importieren Sie nun die Attribute sowie die Attributwerte. Die Attribute und die Attributwerte stehen im Menü <<artikel/artikel-verwalten#390, System » Artikel » Attribute>> zur weiteren Bearbeitung zur Verfügung.

[.instruction]
Attribute und Attributwerte importieren:

. Öffnen Sie das Menü **Daten » Dynamischer Import**.
. Wählen Sie das Trennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus der Dropdown-Liste **Format** das Datenformat, das Sie für das Attribut angelegt haben.
. Wählen Sie eine Option unter **Wenn beim Abgleich keine Übereinstimmung**.
. Klicken Sie auf **Datei auswählen**.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf **Import**.

[#90]
=== Attribute mit dem Artikel verknüpfen

Das Spezialformat **ItemAttribute** dient ausschließlich zum Import von Verknüpfungen zwischen Attributen und Artikeln. Ein Exportformat ist daher nicht vorhanden. Sie müssen dieses Datenformat nicht erstellen. Es steht als Spezialformat im Menü **Daten » Dynamischer Import** zur Verfügung. Beachten Sie die Erläuterungen zu den Datenfeldern in Tabelle 2.

Die Verknüpfung erfolgt anhand der Pflichtfelder **item_id** und **attribute_list**. Bei der Verknüpfung werden dem Artikel die Attribute zugewiesen und gleichzeitig für den Artikel aktiviert.

.Datenfelder des Datenformats **ItemAttribute**
[cols="a,a"]
|====
|Datenfeld |Erläuterung

|**attribute_list**
|Attributwerte. +
Hash-Aufbau: Attribut1:Wert1:Aufpreis;Attribut2:Wert2:Aufpreis +
**Attribut1** = Name des Attributs. +
**Wert1** = Name des Wertes des Attributs. +
(Optional) **Aufpreis** = Betrag des Aufpreises des Wertes in Euro (Euro und Cent getrennt durch einen Punkt). +
__**Beispiel**__: **Hutgröße:54:2.00** (Backend-Attributname:Backend-Wertname:Aufpreis). Im Attributnamen oder im Namen des Wertes darf kein Doppelpunkt verwendet werden, da dies zu einem fehlerhaften Datenimport führen würde.

|**external_item_id**
|Externe Artikel-ID

|**ean**
|EAN des Artikels zur Artikelbestimmung

|**item_id**
|Artikel-ID

|**item_no**
|Artikelnummer
|====

[IMPORTANT]
.Pflichtfelder
====
Pflichtfelder für den Datenimport: **attribute_list** und **item_id**.
====

[.instruction]
Attribute verknüpfen:

. Öffnen Sie das Menü **Daten » Dynamischer Import**.
. Wählen Sie das Trennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus der Dropdown-Liste **Format** das Spezialformat **ItemAttribute**.
. Wählen Sie eine Option unter **Wenn beim Abgleich keine Übereinstimmung**.
. Klicken Sie auf **Datei auswählen**.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf **Import**.

[#100]
=== Varianten erstellen

Um Varianten zu erstellen, benötigen Sie das Datenformat <<basics/datenaustausch/datenformate/_attributeitemvariation#, AttributeItemVariation>>. Die Datenfelder **ItemID**, **PriceID**, **VariationString** und **EAN** müssen mindestens aktiviert sein.

Die folgenden Voraussetzungen müssen erfüllt sein:

* Der Artikel ist erstellt.
* Die Attribute und Attributwerte sind erstellt.
* Die Attribute sind mit dem Artikel verknüpft und Werte sind am Artikel verknüpft, um eine Variante daraus erzeugen zu können.

[.instruction]
Varianten erstellen:

. Öffnen Sie das Menü **Daten » Dynamischer Import**.
. Wählen Sie das Feldtrennzeichen, das Sie bei der Erstellung der Datei eingestellt haben.
. Wählen Sie aus der Dropdown-Liste **Format** das Datenformat **AttributeItemVariation**.
. Wählen Sie eine Option unter **Wenn beim Abgleich keine Übereinstimmung**.
. Klicken Sie auf **Datei auswählen**.
. Wählen Sie die Datei, die importiert werden soll.
. Klicken Sie auf **Import**.

Das folgende Videotutorial veranschaulicht den Umgang mit dem Datenformat **AttributeItemVariation**:

video::139685582[vimeo]
////

[#120]
== Anwendungsbeispiel: Warenbestand importieren

Sie haben auch die Möglichkeit, den kompletten Warenbestand zu importieren, bei dem aktuelle physische Warenbestände in Ihrem plentymarkets System überschrieben werden. Nutzen Sie dazu das Datenformat <<basics/datenaustausch/datenformate/stock#, Stock>>.

[WARNING]
.Warenbestand wird gelöscht
====
Bei diesem Vorgang werden die aktuellen physischen Warenbestände durch den Import ersetzt, d.h. Ihr gesamter Warenbestand wird gelöscht. Reservierte Warenbestände bleiben dabei erhalten.

Wenn Sie nicht den kompletten Warenbestand importieren möchten, sondern nur Wareneingänge per Datenimport hinzufügen möchten, verwenden Sie das Spezialformat **IncomingItems** (siehe Kapitel <<basics/datenaustausch/daten-importieren#50, Wareneingangsdaten importieren>>).
====

Wenn Sie die Importdatei vor dem Import bearbeiten möchten, beachten Sie die folgenden Erläuterungen zu den Datenfeldern. Tabelle 3 erläutert eine Auswahl der in der exportierten Datei enthaltenen Datenfelder.

.Dynamischer Import; Datenfelder des Datenformats **Stock**
[cols="a,a"]
|====
|Feldname |Erläuterung

|**ItemID**
|Artikel-ID

|**VariationEAN**
|EAN-Code der Variante

|**PurchasePrice**
|Einkaufspreis

|**VariationNo**
|Variantennummer

|**LocationID**
|Lagerort-ID +
Jeweils die Ziffer 0 eingeben, wenn kein Lagerort vorhanden ist oder keine Zuordnung erfolgen soll.

|**Stock**
|Warenbestand

|**WarehouseID**
|ID des Lagers

|**VariationString**
|Systemnamen-Hash der Attribute und Werte. +
__**Beispiel**__: "Farbe:Blau;Größe:XXL" +
Die Namen bzw. Bezeichnungen der Attribute und Werte werden verwendet.
|====

[.instruction]
Datenimport durchführen:

. Öffnen Sie das Menü **Daten » Dynamischer Import**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 4.
. Klicken Sie auf **Import**.

.Dynamischer Import; Importoptionen des Datenformats **Stock**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Feldtrennzeichen**
|Trennzeichen wählen.

|**Format**
|Datenformat **Stock** für den Import wählen.

|**Lager**
|Lager für den Import wählen.

|**Barcode**
|Barcode für den Import wählen.

|**Datei**
|Datei für den Import wählen.
|====

Sie erhalten im Menü **Daten » Dynamischer Import** im Bereich **Bearbeitungsstatus** eine detaillierte Meldung des Datenimports. Unter anderem werden das Format, der Dateiname, der Benutzer und das Datum des Imports in diesem Bereich angezeigt.
