= FTP-Zugang
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, FTP-Zugang
:position: 70

Um Bilder, PDF-Dokumente und andere Dateien für Besucher Ihres Online-Shops verfügbar zu machen, müssen diese Dateien in Ihrem plentymarkets System gespeichert werden. Größere Datenmengen laden Sie über das File Transfer Protocol (FTP) hoch. Sie benötigen dazu ein FTP-Programm, auch FTP-Client genannt, und die FTP-Zugangsdaten.

[IMPORTANT]
.Zugriff auf Artikelbilder bei AWS-Systemen
====
Bei auf AWS gehosteten plentymarkets Systemen werden die Artikelbilder vom FTP-Server in den Amazon-Speicher S3 verschoben. Daher können Sie nicht mehr über den FTP-Server auf gespeicherte Artikelbilder zugreifen.
====

[IMPORTANT]
.Ausführen eigener PHP- und CGI-Skripte
====
Das Ausführen von eigenen PHP- und CGI-Skripten ist aus Sicherheitsgründen nicht gestattet. Soll Fremdsoftware installiert werden, kann dies von uns vorgenommen werden. Alternativ greifen Sie auf einen klassischen Webhoster zurück.
====

== FTP-Programme

Programme zum Übertragen von Dateien per FTP erhalten Sie kostenlos oder gegen geringes Entgelt im Internet. Wir haben hier eine kleine Auswahl für Windows und Mac OS X zusammengestellt:

**FTP-Programme für Windows**

* link:http://www.filezilla.de/[FileZilla^]
* link:http://www.smartftp.com/[SmartFTP^]

**FTP-Programme für Mac OS X**

* link:http://cyberduck.ch/[Cyberduck^]
* link:https://filezilla-project.org/download.php/[FileZilla^]

Statt mit einem FTP-Programm zu arbeiten, können Sie auch folgende Optionen nutzen:

* Den integrierten Dateibrowser verwenden
* Eine FTP-Verbindung als Netzwerkressource unter Windows einrichten.

== FTP-Zugang einrichten

Um mit einem FTP-Programm eine Verbindung zu Ihrem plentymarkets System aufzubauen und Dateien zu übertragen, benötigen Sie folgende Daten:

* Host/Server
* Benutzername
* Passwort

Server und Benutzername sind in Ihrem System bereits hinterlegt. Das Passwort wählen Sie selbst.

[.instruction]
FTP-Zugang einrichten:

. Öffnen Sie das Menü **System » Mandant » Global » FTP-Zugang**.
. Notieren Sie sich den Eintrag unter Host (z. B. ftp01.plentymarkets.com).
. Notieren Sie sich den Eintrag in der Zeile **Benutzername**.
. Geben Sie ein Passwort ein.
. **Speichern** Sie die Einstellungen. +
→ Das Passwort wird aktiviert. Nach ca. 60 Minuten erhalten Sie Zugang zum FTP-Server.

[TIP]
.Tipp
====
Statt den Namen des Hosts zu übernehmen, können Sie einen alternativen Hostnamen aus Ihrer Domain ableiten. Beachten Sie dabei die Schreibweise mit dem Punkt: +
URL: http://www.meinshop.de +
FTP: ftp.meinshop.de
====

== Über FTP-Programm Verbindung zum FTP-Server herstellen

Speichern Sie nun die notierten Zugangsdaten in Ihrem FTP-Programm. Wenn Sie beim Einrichten der Verbindung im FTP-Programm nach einem Port gefragt werden, geben Sie den Standardwert **21** ein oder lassen Sie das Feld leer. Nachdem Sie die Zugangsdaten gespeichert haben, bauen Sie eine Verbindung zum Server auf und erhalten Zugriff auf das Dateisystem des Servers. Per FTP können Sie nun Dateien auf den Server hochladen oder vom Server auf Ihren Computer herunterladen. Sie können darüber hinaus Verzeichnisse anlegen und öffnen sowie Verzeichnisse und Dateien umbenennen oder löschen. Nach dem Übertragen von Daten ist es aus Sicherheitsgründen sinnvoll, die FTP-Verbindung zu beenden. Weitere Informationen finden Sie in der Dokumentation des verwendeten FTP-Programms.

[TIP]
.Verbindungsprobleme?
====
Ist keine Verbindung möglich, liegt dies in der Regel an speziellen Netzwerkeinstellungen (z. B. Proxy Server, Firewalls) oder an Besonderheiten Ihres Online-Dienstes. Wenden Sie sich bei Problemen zuerst an Ihren Netzwerkadministrator und/oder an die Hotline Ihres Online-Dienstes.
====

== Über Webspace-Tool auf Daten zugreifen

Alternativ zur Arbeitsweise mit einem FTP-Programm können Sie Daten auch über unser Webspace-Tool austaschen, das Sie über den Bereich **CMS » Webspace** öffnen. Eine Anleitung zur Bedienung des ajaxplorer finden Sie in unserem link:https://www.plentymarkets.eu/-plentymarkets-4-120-Nun-mit-komfortablem-Dateibrowser/b-138/[Blog] zum Thema.
