= Kataloge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Katalog, Kataloge, Katalog-Templates, Marktplatz, Marktplätze, Märkte, Verkaufskanal, Templates, Datenquellen, Zieldaten
:description: Im Menü *Daten » Kataloge* konfigurieren Sie den Export von Variantendaten an Marktplätze.
:position: 70

Kataloge dienen dazu, Variantendaten für den Export an einen Verkaufskanal vorzubereiten. Um einen Katalog für einen Verkaufskanal zu erstellen, benötigen Sie ein Katalog-Template. Katalog-Template werden über das Plugin des Verkaufskanal in das System geladen. Auf dieser Handbuchseite erfahren Sie, wie Sie Kataloge verwalten.


[IMPORTANT]
.Kataloge sind neu!
====
Kataloge sind ein neues Feature für den Export von Variantendaten an Marktplätze und andere Verkaufskanäle. Aktuell können Sie Kataloge nutzen, um Daten an den Marktplatz REWE zu übertragen. plentymarkets arbeitet mit Hochdruck daran, weitere Marktplätze über das neue Katalog-Feature anzubinden.
====

[NOTE]
.Sichtbarkeit des Menüs *Daten » Kataloge*
====
Das Menü *Daten » Kataloge* ist erst sichtbar, wenn Sie ein Plugin bereitstellen, das ein Katalog-Template verfügbar macht.
====

== Was ist ein Katalog?

Jeder Verkaufskanal benötigt unterschiedliche Produktdaten. Häufig werden auch für verschiedene Produktkategorien eines Verkaufskanals unterschiedliche Produktdaten benötigt. Für die Produktkategorie Tierfutter müssen zum Beispiel andere Daten übertragen werden als für die Produktkategorie Spielzeug.

Kataloge ermöglichen es Ihnen, Ihr Produktsortiment ganz auf die Anforderungen und die Zielgruppe eines Verkaufskanals zuzuschneiden. Denn in Katalogen ordnen Sie den einzelnen Datenfeldern eines Verkaufskanals eine passende plentymarkets Datenquelle zu. Beim Übermitteln Ihrer Variantendaten an den Verkaufskanal werden dann die Datenfelder des Verkaufskanal mit den richtigen Daten aus plentymarkets befüllt.

Kataloge bieten die folgenden Vorteile:

* Der Verkaufskanal gibt die Datenstruktur vor. Sie wissen also genau, welche Variantendaten nötig sind, um Ihre Produkte über den Verkaufskanal anzubieten.
* Sie bestimmen pro Verkaufskanal oder sogar pro Template, welche Variantendaten auf dem Verkaufskanal veröffentlicht werden. Über Eigenschaften können Sie z.B. unterschiedliche Namen und Beschreibungen an die verschiedenen Marktplätze übertragen.

[TIP]
.Datenexport? FormatDesigner
====
Kataloge dienen zum Übertragen von Daten an Verkaufskanäle. Katalogdaten können nicht in eine Datei oder ein anderes auslesbares Format exportiert werden. Verwenden Sie den <<basics/datenaustausch/ElasticSync/FormatDesigner#, Formatdesigner>>, um Daten zu exportieren.
====

== Was ist ein Katalog-Template?

Ein Katalog-Template stellt ein Gerüst der Daten bereit, die der Verkaufskanal entgegennehmen kann. Über Katalog-Templates gibt der Verkaufskanal also vor, welche Daten übertragen werden können, um Produkte dort zu verkaufen.

Ein Verkaufskanal kann mehrere Katalog-Templates anbieten, z.B. für verschiedene Produktkategorien (Tiernahrung, Lebensmittel, Non-Food etc.) und/oder für verschiedene Sprachen. Die Katalog-Templates werden über das Plugin des Verkaufskanals in das plentymarkets Backend geladen. Informationen dazu, welche Katalog-Templates für einen Verkaufskanal verfügbar sind, finden Sie in der Dokumentation des Plugins.

[NOTE]
.Kein Katalog-Template ohne Plugin
====
Die Katalog-Templates eines Verkaufskanals werden in das Menü *Daten » Kataloge* geladen, wenn Sie das Plugin des Verkaufskanals bereitstellen.
====

== Kataloge verwalten

Nachdem Sie ein Plugin bereitgestellt haben, das Katalog-Templates verfügbar macht, wird in plentymarkets das Menü *Daten » Kataloge* sichtbar. In diesem Menü erstellen, bearbeiten und löschen Sie Kataloge.

=== Katalog erstellen

Gehen Sie wie unten beschrieben vor, um einen Katalog zu erstellen.

[.instruction]
Katalog erstellen:

. Öffnen Sie das Menü *Daten » Kataloge*. +
→ Die Katalogübersicht wird angezeigt.
. Klicken Sie auf *Katalog erstellen*.
. Geben Sie einen Namen für den Katalog ein.
. Wählen Sie ein Katalog-Template aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen. +
→ Der Katalog wird erstellt. +
→ Der Katalog wird zur weiteren Bearbeitung geöffnet.

=== Datenquellen zuordnen

Nachdem Sie einen Katalog erstellt haben, wird dieser Katalog geöffnet. Links werden die Daten des Verkaufskanals angezeigt. Pflichtfelder sind mit Sternchen gekennzeichnet. Rechts davon sehen Sie für jedes Datenfeld des Verkaufskanals ein Dropdown-Menü. Über diese Dropdown-Menüs ordnen Sie den Datenfeldern des Verkaufskanals ein oder mehrere plentymarkets Datenquellen zu.

Je nachdem, um welche Produktdaten es sich handelt, wird als Datenquelle entweder ein Datenfeld oder ein Wert zugeordnet. Im oberen Bereich der Liste ordnen Sie Datenfelder zu. Sie legen zum Beispiel fest, welches Datenfeld in plentymarkets das Gewicht von Varianten enthält, das an den Verkaufskanal übertragen werden soll. Im unteren Bereich ordnen Sie Werte zu.

Ein Beispiel für eine Wertezuordnung sind die Kategorien. Es genügt nicht, dem Verkaufskanal zu übermitteln, in welchem Datenfeld in plentymarkets die Kategorien einer Variante gespeichert sind. Stattdessen müssen Sie jeder Kategorie des Verkaufskanals eine Kategorie in plentymarkets zuordnen.

Gehen Sie wie unten beschrieben vor, um den Datenfeldern des Verkaufskanals eine plentymarkets Datenquelle zuzuordnen.

[.instruction]
Datenquellen zuordnen:

. Öffnen Sie das Menü *Daten » Kataloge*. +
→ Die Katalogübersicht wird angezeigt.
. Klicken Sie auf den Katalog. +
→ Der Katalog wird geöffnet. +
→ Links werden die Datenfelder des Verkaufskanals angezeigt. +
*_Tipp:_* Pflichtfelder sind mit Sternchen gekennzeichnet. +
→ In der Mitte werden Dropdown-Listen mit plentymarkets Datenquellen angezeigt. +
. Wählen Sie für die Datenfelder des Verkaufskanals eine plentymarkets Quelle aus der Dropdown-Liste. +
*_Hinweis:_* Informationen zu den Zieldatenfeldern erhalten Sie im Plugin des Verkaufskanals. Tabelle <<tabelle-katalog-felder>> enthält Informationen zu den plentymarkets Datenquellen und wie Sie diese Datenquellen zuordnen. +
. Um einem Datenfeld eine weitere plentymarkets Quelle zuzuordnen klicken Sie ganz rechts auf *Quelle hinzufügen*. +
→ Eine neue Zeile wird eingeblendet. +
*_Hinweis:_* Auch wenn Sie einem Datenfeld mehr als eine Datenquelle zuordnen, wird nur ein Wert übertragen. Die Daten werden in der Reihenfolge der Zuordnung geprüft. Wenn also das erste Datenfeld keinen Wert liefert, wird das zweite Datenfeld übertragen usw.
. Nehmen Sie alle gewünschten Zuordnungen vor.
. *Speichern* Sie die Einstellungen. +
→ Die Zuordnungen werden gespeichert.

[[tabelle-katalog-felder]]
.Verfügbare plentymarkets Datenquellen
[cols="1,1,2"]
|====
|Typ |Verfügbare Quellen |Erläuterung

|Texte
a|* *Name 1* +
* *Name 2* +
* *Name 3* +
* *Kurzbeschreibung* +
* *Metabeschreibung* +
* *Beschreibung* +
* *Technische Daten* +
* *URL-Pfad*
|Nach Auswahl der Quelle wird ein Dropdown-Menü für die Auswahl der Sprache eingeblendet.

|Verkaufspreis
a|* Im System gespeicherte Verkaufspreise
|Der für diesen Verkaufspreis an der Variante gespeicherte Preis wird an den Verkaufskanal übermittelt.

|Eigenschaft
a|* Im System gespeicherte Eigenschaften
|Nach Auswahl der Quelle wird ein Dropdown-Menü für die Auswahl der Sprache eingeblendet.

|Bild
|Keine weitere Auswahl
|

|Barcode
a|* Im System gespeicherte Barcodes
|Der für diesen Barcode an der Variante gespeicherte Code wird an den Verkaufskanal übermittelt.

|SKU
|Keine weitere Auswahl
|

|Bestand
a|* *Virtuelles Gesamtlager* +
* Im System gespeicherte Lager
|Der Lagerbestand des gewählten Lagers wird an den Verkaufskanal übermittelt.

|Standardkategorie
a|* *ID* +
* *Name* +
* *Beschreibung* +
* *URL-Name* +
* *Meta-Titel* +
* *Meta-Beschreibung* +
* *Meta-Keywords*
|

|Eigenschaft
a|* Im System gespeicherte Eigenschaften
|

|Variante
a|* *Aktiv* +
* *Ist Hauptvariante* +
* *ID der Hauptvariante* +
* *Webshop: Nicht verfügbar wenn kein Netto-WB* +
* *Verfügbar wenn Netto-WB positiv* +
* *Webshop sichtbar wenn Netto-WB positiv* +
* *automaticClientVisibility* +
* *WB Beschränkung* +
* *Verfügbarkeit* +
* *Verfügbar bis* +
* *Paketart* +
* *Variantennr.* +
* *customsPercent* +
* *Zoll* +
* *Externe Varianten-ID* +
* *Portoaufschlag 1* +
* *Portoaufschlag 2* +
* *Höhe mm* +
* *ID* +
* *Unsichtbar in Artikelisten* +
* *Intervallbestellmenge* +
* *Länge mm* +
* *WB Beschränkung* +
* *Max. Bestellmenge* +
* *Min.-Bestellmenge* +
* *Modell* +
* *Betriebskosten* +
* *Einheit der Packstücke* +
* *Anzahl der Packstücke* +
* *Kommissionierung* +
* *Position* +
* *Ist Hauptvariante* +
* *EK netto* +
* *Erscheinungsdatum* +
* *Lagerkosten netto* +
* *Transportkosten netto* +
* *Lademittel* +
* *VPE* +
* *Name* +
* *Variantennr.* +
* *Gewicht brutto g* +
* *Gewicht netto g* +
* *Breite mm* +
* *Nummer der Hauptvariante* +
* *Grundpreis anzeigen* +
* *GLD EK netto* +
* *Standard Versandkosten*
|Der für das gewählte Datenfeld an der Variante gespeicherte Wert wird an den Verkaufskanal übermittelt.

|Hersteller
a|* Im System gespeicherte Hersteller
|Über Dropdown-Listen für Ziel und Quelle werden die Hersteller des Verkaufskanals einzeln den Hersteller in plentymarkets zugeordnet. Links auf *Hersteller hinzufügen* klicken, um weitere Zielhersteller zuzuordnen. Auf dem Verkaufskanal wird der Herstellername des Verkaufskanals veröffentlicht.

|Attribut
a|* Im System gespeicherte Attributwerte
|

|Kategorie
a|* Im System gespeicherte Kategorien
|Über Dropdown-Listen für Ziel und Quelle werden die Kategorien des Verkaufskanals einzeln den Kategorien in plentymarkets zugeordnet. Links auf *Kategorien hinzufügen* klicken, um weitere Zielkategorien zuzuordnen. Auf dem Verkaufskanal wird der Kategoriename des Verkaufskanals veröffentlicht.
|====

=== Katalog löschen

Gehen Sie wie unten beschrieben vor, um einen Katalog zu löschen.

[.instruction]
Katalog löschen:

. Öffnen Sie das Menü *Daten » Kataloge*. +
→ Die Katalogübersicht wird angezeigt.
. Klicken Sie auf den Katalog. +
→ Der Katalog wird geöffnet. +
. Klicken Sie recht oben auf *Löschen*. +
→ Eine Sicherheitsabfrage wird eingeblendet.
. Bestätigen Sie den Löschvorgang. +
→ Der Katalog wird gelöscht.

== Katalogdaten an Verkaufskanal übertragen

Die Kataloge im Menü *Daten » Kataloge* dienen nur dazu, den Datenfeldern eines Verkaufskanals die korrekten plentymarkets Datenquellen zuzuordnen. Das Übertragen der Variantendaten an den Verkaufskanal aktivieren Sie in den Einstellungen des Plugins des Verkaufskanals.
