= Kataloge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Katalog, Kataloge, Katalog-Templates, Marktplatz, Marktplätze, Märkte, Verkaufskanal, Templates
:position: 70

== Was ist ein Katalog?


Sortiment zusammenstellen???

Im Menü *Daten » Kataloge* konfigurieren Sie den Export von Variantendaten an Verkaufskanäle. Dazu verknüpfen Sie Variantendaten mit den Daten, die der Verkaufskanal benötigt.

In einem solchen Katalog könnt ihr festlegen, welche Daten verknüpft werden müssen, beispielsweise die Marktplatz-Produktkategorien mit plenty-Kategorien oder auch welche plenty-Felder für den Artikelnamen im Marktplatz verwendet werden sollen.

Der Verkaufskanal gibt dabei vor, welche Verknüpfungen verpflichtend und welche optional sind.



Jeder Verkaufskanal benötigt unterschiedliche Produktdaten. Häufig werden auch für unterschiedliche Produktkategorien Ihres Sortiments unterschiedliche Produktdaten benötigt. Mit Katalogen verknüpfen Sie Variantendaten mit den Werten eines Verkaufskanals. Das ermöglicht es Ihnen, Ihr Produktsortiment ganz auf die Anforderungen und die Zielgruppe eines Verkaufskanals zuzuschneiden. Zum Beispiel veröffentlichen Sie pro Verkaufskanal unterschiedliche Produktnamen und -beschreibungen.

Welche Daten an einen Verkaufskanal übertragen werden, legen Sie anhand von Katalog-Templates fest. Das Katalog-Template enthält die Werte, die an den Verkaufskanal übertragen werden können oder müssen. Im Menü *Daten » Kataloge* verknüpfen Sie diese Werte mit den Variantendaten.

Da jeder Verkaufskanal unterschiedliche Daten benötigt, werden Kataloge mithilfe von Katalog-Templates erstellt. Diese Katalog-Templates geben die Produktdaten vor, die an den Verkaufskanal übertragen werden sollen. Die Katalog-Templates geben auch Pflichtwerte vor.

Ein Katalog ist eine Sammlung von Variantendaten, die den Produktdaten eines Verkaufskanals zugeordnet wurden. Pro Verkaufskanal können mehrere Kataloge erstellt werden.

Quelle = plenty Variantendaten
Ziel = Verkaufskanal

[TIP]
.Kein Katalog ohne Katalog-Template
====
Kataloge können nur erstellt werden, wenn ein Katalog-Template ausgewählt ist. Auch der Export eines Katalogs in ein für Sie lesbares Format ist nicht möglich. Verwenden Sie das Plugin ElasticSync, um Daten flexibel und in ein lesbares Format zu exportieren.
====






== Was ist ein Katalog-Template?

Über das Katalog-Template gibt der Verkaufskanal vor, welche Daten für die Datenübermittlung erforderlich sind. Das Katalog-Template stellt also ein Gerüst für die Daten bereit, die an den Verkaufskanal übertragen werden. Bei der Übertragung werden diese Daten korrekt den Werten des Verkaufskanals zugeordnet. Jeder Verkaufskanal kann mehrere Katalog-Templates anbieten, z.B. für verschiedene Produktkategorien (Tiernahrung, Lebensmittel, Non-Food etc.).

Katalog-Templates werden über das Verkaufskanal-Plugin ins plentymarkets Backend geladen. Informationen dazu, welche Katalog-Templates für die Verkaufskanäle verfügbar sind, finden Sie in der Dokumentation der Plugins.

!!!!Kann nach Produkttyp oder nach anderen Dingen unterteilt sein.

Diese Katalog-Templates werden in das Menü Daten » Kataloge geladen, wenn du das Plugin bereitstellst.

== Welche Vorteile bieten Kataloge?

* Das Katalog-Template gibt die Struktur vor. Sie wissen also genau, welche Variantendaten nötig sind, um Ihre Produkte über den Verkaufskanal anzubieten.
* Sie bestimmen pro Verkaufskanal oder sogar pro Template, welche Variantendaten veröffentlicht werden. So können Sie z.B. unterschiedliche Namen und Beschreibungen übermitteln, indem Sie verschiedene Eigenschaften pro Template verknüpfen.


== Warum wird das Menü *Daten » Kataloge* nicht angezeigt?

Das Katalog-Template wird im Menü *Daten » Kataloge* wählbar, wenn das Plugin aktiviert ist. Deshalb wird das Menü *Daten » Kataloge* erst sichtbar, wenn Sie ein Katalog-Plugin installieren und aktivieren.


== Herkünfte aktivierenXXXX

Sie müssen trotzdem die Herkünfte aktivieren

== Katalog erstellen

[.instruction]
Katalog erstellen:

. Öffnen Sie das Menü *Daten » Kataloge*. +
→ Die Katalogübersicht wird angezeigt.
. Klicken Sie auf *Katalog erstellen*.
. Geben Sie einen Namen für den Katalog ein.
. XXXXWählen Sie ein Template aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen. +
→ Der Katalog wird erstellt. +
→ Der Katalog wird zur weiteren Bearbeitung geöffnet.


== Kataloge bearbeiten

Nachdem Sie einen Katalog erstellt haben werden links die Daten des Verkaufskanals angezeigt. Rechts sehen Sie die plentymarkets Variantendaten. Das Ziel, d.h. der Verkaufskanal, ist also links, die Quelle, also die Variantendaten in plentymarkets, werden rechts angezeigt. Links sehen Sie also, welche Daten an den Verkaufskanal übertragen werden. Pflichtwerte sind durch Sternchen gekennzeichnet.

Der Katalog entsteht dadurch, dass Sie nun die Datenvorgaben des Verkaufskanals mit den Variantendaten verknüpfen. Diese Verknüpfung erfolgt auf der konkreten Datenebene. Zum Beispiel wählen Sie aus der Liste der Farben des Verkaufskanals eine Farbe - z.B. Hellblau - und verknüpfen diese Farbe mit der oder den Farben im plentymarkets Backend, die dieser Farbe entsprechen.


[[tabelle-kataloge-farben]]
.Beispiel für das Verknüpfen von Farben
[cols=5,1,5]
|====
|Verkaufskanal (Ziel) | |plentymarkets (Quelle)

3+|Farbe

a|* Hellblau
|*→*
a|* Babyblau
* Himmelblau

a|* Mittelblau
|*→*
a|* Meerblau

a|* Dunkelblau
|*→*
a|* Marine
* Dunkelblau
|====

[TIP]
.Datenübertragung
====
Die Kataloge im Menü *Daten » Kataloge* dienen nur dazu, den Variantendaten eines Verkaufskanals die korrekten Daten von Varianten in plentymarkets zuzuordnen. Ob und wann die Variantendaten an einen Verkaufskanal übertragen werden, legen Sie in den Einstellungen des Plugins des Verkaufskanals fest.
====



[[xxxxx]]
.titel
[cols="1,3,3"]
|====
|Einstellung |Erläuterung |Erläuterung

|isActive
|Aktiv
|

|isMain
|Ist Hauptvariante
|

|mainId
|ID der Hauptvariante
|

|isInvisibleIfNetStockIsNotPositive
|Webshop: unsichtbar wenn kein Netto-WB
|

|isUnavailableIfNetStockIsNotPositive
|Nicht verfügbar wenn kein Netto-WB
|

|isAvailableIfNetStockIsPositive
|Verfügbar wenn Netto-WB positiv
|

|isVisibleIfNetStockIsPositive
|Webshop sichtbar wenn Netto-WB positiv
|

|utomaticClientVisibility
|automaticClientVisibility
|

|stockLimitation
|WB Beschränkung
|

|availability
|Verfügbarkeit
|

|availableUntil
|Verfügbar bis
|

|bundleType
|Paketart
|

|customNumber
|Variantennr.
|

|customsPercent
|customsPercent
|

|customs
|Zoll
|

|externalId
|Externe Varianten-ID
|

|extraShippingCharge1
|Portoaufschlag 1
|

|extraShippingCharge2
|Portoaufschlag 2
|

|heightMM
|Höhe mm
|

|id
|ID
|

|isHiddenInCategoryList
|Unsichtbar in Artikelisten
|

|intervalOrderQuantity
|Intervallbestellmenge
|

|lengthMM
|Länge mm
|

|limitOrderByStockSelect
|WB Beschränkung
|

|maximumOrderQuantity
|Max. Bestellmenge
|

|minimumOrderQuantity
|Min.-Bestellmenge
|

|model
|Modell
|

|operatingCosts
|Betriebskosten
|

|packingUnitTypeId
|Einheit der Packstücke
|

|packingUnits
|Anzahl der Packstücke
|

|picking
|Kommissionierung
|

|position
|Position
|

|isPrimary
|Ist Hauptvariante
|

|purchasePrice
|EK netto
|

|releasedAt
|Erscheinungsdatum
|

|storageCosts
|Lagerkosten netto
|

|transportationCosts
|Transportkosten netto
|

|unitLoadDevice
|Lademittel
|

|unitsContained
|VPE
|

|name
|Name
|

|number
|Variantennr.
|

|weightG
|Gewicht brutto g
|

|weightNetG
|Gewicht netto g
|

|widthMM
|Breite mm
|

|mainVariationNumber
|Nummer der Hauptvariante
|

|mayShowUnitPrice
|Grundpreis anzeigen
|

|movingAveragePrice
|GLD EK netto
|

|defaultShippingCosts
|Standard Versandkosten
|
