= Constants
:lang: en
// include::{includedir}/_header.adoc[]
:position: 90

Use the text fields of the *CMS » Constants* menu to insert recurring content into several pages of your online store. 25 constants are available. Constants allow you to reuse content. Instead of editing each occurrence of a text, you can edit it in this menu once. The content may contain HTML code or e.g. JavaScript code. In addition, <<omni-channel/online-store/setting-up-clients/cms#settings-item-gallery, item galleries>> are linked using constants.

== Defining constants

To define a constant, save a value for this constant first. To do so, proceed as follows. If you link a constant to an item gallery, code will automatically be inserted as the constant's *value*. This is why you do not need to enter a value for constants that you want to link with an <<omni-channel/online-store/setting-up-clients/cms#settings-item-gallery, item gallery>>.

[.instruction]
Defining constants:

. Go to *CMS » Constants*.
. Enter the content into the text field of the constant you want to use.
. *Save* the settings. +
&amp;rarr; The content will be displayed in the online store when the constant is inserted into the design.

[TIP]
.How to include PHP scripts
====
You can not save PHP scripts as constants. Save PHP scripts externally, e.g. on an FTP server. Then save a link to this script as the constant's *Value* to retrieve it.
====

== Inserting constants into design

Now insert the constant into your online store. To do so, proceed as follows.

[.instruction]
Inserting a constant into design:

. Go to *CMS » Web design » Layout*.
. Open the desired template.
. Insert the constant into the template. Position it where you would like the content to be displayed.
. *Save* the settings.

Constants can also be inserted into categories.

