= Stammdaten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Stammdaten
:position: 20

In diesem Menü hinterlegen Sie alle wichtigen Angaben zu Ihrem Unternehmen. Neben Adresse und Kontaktdaten wird hier auch die Umsatzsteuer-ID eingetragen.

== Auswirkung der Konfiguration auf Benutzer

[WARNING]
.Benutzer werden bei Änderungen ausgeloggt
====
Wenn Sie in diesem Menü Änderungen vornehmen, werden andere Benutzer automatisch ausgeloggt und müssen sich neu einloggen, damit die Änderungen auch für diese Benutzerprofile greifen. Kündigen Sie Änderungen daher ggf. weiteren Benutzern an.
====

== Konfiguration

Die Stammdaten, die hier zentral hinterlegt werden, sind im gesamten System mit diesem Menü verknüpft. So brauchen Sie bei Änderung dieser Daten eine Korrektur nur an dieser Stelle vornehmen, da sich diese auf das ganze System auswirkt.

[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Region**
|Die zutreffende Region wählen. Danach stehen die Zeitzonen der Region zur Auswahl zur Verfügung (nächste Option).

|**Zeitzone**
|Die Einstellung ist wichtig für die korrekte Ausgabe des Datums und der Uhrzeit, z.B. in Aufträgen oder in Tickets.

|**Hotline**
|Die Hotline-Telefonnummer eintragen +
Wenn keine spezielle Hotlinenummer vorhanden ist, die obige Telefonnummer auch unter dieser Option nochmals eintragen, da die Ausgabe der Hotlinenummer über die Template-Variable **$CompanyHotline** an verschiedenen Stellen im System vorkonfiguriert ist, z.B. im Standard-Layout des Webshops.

|**Umsatzsteuer-ID**
|Umsatzsteuer-ID des Unternehmens eintragen. Diese wird auch für Mandanten verwendet, bei denen in der <<omni-channel/online-shop/standard/buchhaltung#, **Buchhaltung**  >> keine Umsatzsteuer-ID hinterlegt wurde. Tragen Sie daher auch für Mandanten die zutreffende ID im Menü **Buchhaltung** ein.
|====

__Tab 1: Einstellungen im Menü **Stammdaten**__

[IMPORTANT]
.Vertragsdaten ändern
====
Eine Änderung dieser Stammdaten ändert nicht die hinterlegten Kundenstammdaten Ihres Vertrages bei plentymarkets z.B. für die Rechnungsstellung! Diese Daten passen Sie unter **Start » plentymarkets-Konto » Service-Center** an.
====

[TIP]
.Daten in Webshop-Templates enthalten
====
Alle Felder, die hier konfiguriert werden, können über Template-Variablen z.B. in E-Mail-Vorlagen, sowie im Webshop angezeigt werden und sind dort zum Teil bereits enthalten.
====

