:keywords: {marketplace}, Marktplatz, {marketplace}.de, {marketplace} einrichten, {marketplace} Marktplatz, Multi-Channel, Multichannel, Multi-Channel {marketplace}, Multichannel {marketplace}, Multi Channel {marketplace}
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz {marketplace} in deinem plentymarkets System ein.

[IMPORTANT]
.{marketplace}-Plugin herunterladen
====
Die Schnittstelle zu {marketplace} wird über ein Plugin integriert. Um das {marketplace}-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/{marketplace}_{marketplace}[plentyMarketplace^]{nbsp}icon:external-link[] herunter.

Um das {marketplace}-Plugin nutzen zu können, benötigst du das Plugin Mirakl. Du findest Mirakl ebenfalls auf plentyMarketplace.
====

:plugin: Mirakl

[.collapseBox]
.{plugin} installieren
--
include::../../../plugins/_textblocks/instructions/plugin-installieren.adoc[]
--

:plugin: {marketplace}
:priority: 1

[.collapseBox]
.{plugin} installieren
--
include::../../../plugins/_textblocks/instructions/plugin-installieren.adoc[]
--

[#100]
== Über {marketplace}

{marketplace-info}

[#200]
== Bei {marketplace} registrieren

{marketplace-registration}

== Informationen zum automatischen Datenaustausch

Nachdem du das Plugin installiert und eingerichtet hast, stehen die in <<#datenaustausch-{marketplace}>> automatisierten Prozesse bereit:

[#datenaustausch-{marketplace}]
[cols="1,3"]
.Häufigkeit des Datenaustauschs
|====
|Daten |Intervall

2+| Artikeldaten

| Artikelexport
| Täglich

| Bestandsabgleich
| Alle 15 Minuten

| Preisabgleich
| Alle 15 Minuten

2+| Auftragsdaten

| Auftragsimport
| Alle 15 Minuten

|====

[#600]
== Auftragsherkunft aktivieren

// Auftragsherkunft aktivieren

:market: {marketplace}
:referrer: {marketplace}
:referrer-option: Option {marketplace}

include::../../_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#500]
== Verkaufspreis festlegen

:referrer-price: {marketplace}

include::../../_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#1200]
== Eigenschaften erstellen

Eigenschaften werden verwendet, um Felder an den Marktplatz zu übergeben, die in plentymarkets standardmäßig nicht definiert sind. Im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* erstellst du die Eigenschaften, die {marketplace} vorgibt.

Weitere Informationen zu Eigenschaften findest du auf der Seite <<artikel/einstellungen/eigenschaften#500, Merkmale und Eigenschaften>>.

Du benötigst die folgenden Eigenschaften für {marketplace}:

* Logistikklasse (<<#1210, so geht's>>)
* Versandvorlaufzeit (<<#1220, so geht's>>)
* Reversecharge (<<#1230, so geht's>>)

[#1210]
=== Eigenschaft Logistikklasse erstellen

Für jede Variante muss ein Versandprofil-Code an {marketplace} exportiert werden. Versandprofile konfigurierst du im Mirakl-Backend. Die Liste der Versandprofile wird im Mirakl-Backend im Bereich *Informationen » Versandkosten* angezeigt. Der Code wird in der Spalte *Logistikklasse* in Klammern hinter dem Namen der Logistikklasse angezeigt.

:property: Logistikklasse

include::../../_textblocks/instructions/properties-creation.adoc[]

:property: Logistikklasse
:property-area: Artikel
:property-type: Kurztext
:property-name: {marketplace} Logistikklasse

include::../../_textblocks/instructions/properties-creation-table.adoc[]

[#1220]
=== Eigenschaft Versandvorlaufzeit erstellen

Für jede Variante muss eine Versandvorlaufzeit in Tagen an {marketplace} exportiert werden. Damit informierst du {marketplace} darüber, wie viele Tage du benötigst, um die Variante zu versenden. {marketplace} akzeptiert die Werte 1-45.

:property: Versandvorlaufzeit

include::../../_textblocks/instructions/properties-creation.adoc[]

:property: Versandvorlaufzeit
:property-area: Artikel
:property-type: Kurztext
:property-name: {marketplace} Versandvorlaufzeit

include::../../_textblocks/instructions/properties-creation-table.adoc[]

[#1230]
=== Eigenschaft Reversecharge erstellen

Für jede Variante muss angegeben werden, ob für diese Variante bei grenzüberschreitenden Geschäftsvorgängen das Reverse-Charge-Verfahren Anwendung findet. {marketplace} akzeptiert die Werte *true* und *false*.

* false = Das Reverse-Charge-Verfahren wird nicht angewendet.
* true = Das Reverse-Charge-Verfahren wird angewendet. Nicht du als leistende Unternehmer:in führst also die Umsatzsteuer an das Finanzamt ab, sondern dein:e Kund:in. +
*_Hinweis:_* Beachte die gesetzlichen Vorgaben für das Reverse-Charge-Verfahren und kläre mit deinem Steuerbüro, was es zu beachten gibt.

:property: Reversecharge

include::../../_textblocks/instructions/properties-creation.adoc[]

:property: Reversecharge
:property-area: Artikel
:property-type: Kurztext
:property-name: {marketplace} Reversecharge

include::../../_textblocks/instructions/properties-creation-table.adoc[]

[#1300]
== API-Schlüssel erzeugen

Um die Verbindung für {marketplace} zwischen plentymarkets und Mirakl herzustellen, benötigst du einen API-Schlüssel. Um den API-Schlüssel zu erzeugen, gehe wie folgt vor:

[.instruction]
API-Schlüssel erzeugen:

. Öffne das Backend von Mirakl.
. Klicke auf das Benutzersymbol (icon:user-circle[]).
. Öffne das Tab *API-Schlüssel*.
. Generiere einen neuen API-Schlüssel für {marketplace}.
. Kopiere den API-Schlüssel in die Zwischenablage. Du benötigst den Schlüssel, um dein {marketplace}-Konto in plentymarkets einzurichten.

[#1400]
== Kontoeinstellungen im Assistenten vornehmen

Mit dem Assistenten *{marketplace} - Wizard* im Menü *Einrichtungen » Assistenten » Plugins » _Plugin-Set wählen_* richtest du dein {marketplace}-Konto in plentymarkets ein.

:menu-path: pass:quotes[Einrichtungen » Assistenten » Plugins » _Plugin-Set wählen_]
:assistant-name: {marketplace}
:number-of-boxes: Info-Box

include::../../_textblocks/instructions/assistant-basic-instructions.adoc[]

// Je nach Umfang des Assistenten entweder eine einzige ausklappbare Box oder eine ausklappbare Box pro Schritt im Assistenten.

[.collapseBox]
.Erläuterungen zu den Optionen des Assistenten
--
[[table-{marketplace}-basic-settings-assistant]]
[width="100%"]
[cols="1,2"]
|======
|Einstellung |Erläuterung

| Authentifizierung
| Wähle die API-Umgebung und trage den <<#1300, API-Schlüssel>> ein. Die API-Umgebung kannst du an der URL von deinem Mirakl-Konto erkennen.

| Datenaustausch
| Wähle die Prozesse, für die du den Datenaustausch zwischen plentymarkets und Mirakl einrichten möchtest.

| Zuordnung der Rückerstattung
| Trage den Grund ein, der zu Mirakl übertragen wird, wenn eine Rückerstattung erfolgt. Du kannst für mehrere Status Gründe hinzufügen.

| Zuordnung der Stornierung
a| Trage den Grund ein, der zu Mirakl übertragen wird, wenn eine Stornierung erfolgt. Du kannst für mehrere Status Gründe hinzufügen.
ifeval::["{marketplace}" == "Voelkner"]
 +
*_Hinweis_*: Diese Einstellung hat bei Voelkner keine Auswirkungen.
endif::[]

| Lagerauswahl
| Wähle das Lager, das für den Bestandsexport verwendet werden soll.

| Zuordnung des Versandprofils
| Trage für die Versandprofile in plentymarkets die entsprechenden Kürzel der Versanddienstleister ein. Die Kürzel findest du auf Mirakl im Menü *Informationen » Transportunternehmen*.

| Zuordnung der Angebots-Eigenschaften
| Wähle aus der Dropdown-Liste *Abzugsverfahren* die Eigenschaft *{marketplace} Reversecharge*. +
Wähle aus der Dropdown-Liste *Versandvorlaufzeit* die Eigenschaft *{marketplace} Versandvorlaufzeit*. +
Wähle aus der Dropdown-Liste *Logistikklasse* die Eigenschaft *{marketplace} Logistikklasse*.

|======
--

[#900]
== Artikelexport einrichten

Artikeldaten werden über Marktplatz-Formate zu {marketplace} übertragen. Kataloge erstellst du im Menü *Daten » Kataloge*. Du arbeitest zum ersten Mal mit den Katalogen? Dann solltest du dich zuerst mit dem grundlegenden Prinzip der <<daten/daten-exportieren/kataloge-verwalten#, Kataloge vertraut machen>>.

Für jede Produktkategorie von {marketplace}, in der du Produkte verkaufen möchtest, erstellst du einen eigenen Katalog. Verknüpfe anschließend im Marktplatz-Format die von {marketplace} vorgegebenen Felder mit den in plentymarkets gespeicherten Artikeldaten. Die Katalog-Vorlagen werden automatisch täglich zu {marketplace} exportiert, wenn du den Katalog aktivierst.

[IMPORTANT]
.Fehler-Log
====
Wenn es beim Export Probleme gibt, findest du die zugehörigen Log-Einträge auf Mirakl und nicht im Log von plentymarkets.
====

[#1240]
=== Weitere Eigenschaften erstellen

Zusätzlich zu den <<#1200, zuvor beschriebenen Eigenschaften>> benötigst du Eigenschaften für alle Datenfelder des Marktplatzes, für die du Daten übergeben möchtest, die es standardmäßig in plentymarkets nicht gibt. Welche Eigenschaften du benötigst, erfährst du in der Dokumentation des Marktplatzes. Du arbeitest zum ersten Mal mit Eigenschaften? Weitere Informationen findest du auf der Handbuchseite zum Thema <<willkommen/allgemeine-funktionen/eigenschaften, Eigenschaften>>.

[#902]
=== Katalog im Assistenten erstellen

:catalogue-assistant-name: {marketplace}-Katalog
:number-of-boxes: Info-Box
:mapping-fields: die
:catalogue-path: pass:quotes[*Einrichtung » Assistenten » Plugins »* _Plugin-Set wählen_.]
:catalogue-note: pass:quotes[Achte darauf, eine Kategorie der untersten Ebene zu wählen. Eine bessere Übersicht findest du auf Mirakl im Menü *Mein Konto » Meine Produktdaten-Einstellungen*.]

include::../../_textblocks/instructions/catalogue-assistant-config.adoc[]

////
TODOs:
* Pfad muss in der Include-Datei angepasst werden, da der Assistent im Plugin-Menü und nicht im Omni-Channel-Menü wohnt. +
ACHTUNG: Alle Dateien müssen angepasst werden.
* In der Include-Datei steht "um weitere Felder zu verknüpfen". Da bei Mirakl nur das Katalog-Template im Assistenten erstellt wird, muss das angepasst werden, z.B. in "um die Felder zu verknüpfen". +
ACHTUNG: Alle Dateien müssen angepasst werden.
*
////

// Je nach Umfang des Assistenten entweder eine einzige ausklappbare Box oder eine ausklappbare Box pro Schritt im Assistenten.

[.collapseBox]
.Erläuterungen zu den Optionen des Assistenten
--
[[table-{marketplace}-catalogue-assistant]]
[width="100%"]
[cols="1,2"]
|======
|Einstellung |Erläuterung

| Einstellungen
| Wähle die Kategorie, in der du deine Artikel auf {marketplace} verkaufen möchtest. Gib dann einen Namen für die zugehörige Kategorie in plentymarkets ein. +
{catalogue-note}

|======
--

[#datenfelder-zuordnen]
=== Datenfelder im Katalog zuordnen

include::../../_textblocks/instructions/katalog-datenfelder-zuordnen.adoc[]

ifeval::["{marketplace}" == "Conrad"]
include::../instructions/katalog-mirakl-conrad-zuordnungen.adoc[]

In den folgenden CSV-Dateien kannst du die gültigen Werte für die jeweiligen Felder im Katalog einsehen:

* link:https://docs.google.com/spreadsheets/d/1ZsjMj1mTnASqrgr5UCAhxXUzgqrNVy3vEEmpP32POX8/export?format=csv[Akkus_Batterien^]
* link:https://docs.google.com/spreadsheets/d/17zwR35iT8Pi3xcEVDz6ue4hU0S-sp7X5gI90XedLoj8/export?format=csv[Energieeffizienzklassen^]
* link:https://docs.google.com/spreadsheets/d/1lnV-EPF2bhjEOdEypiZOil5zbGe-1JTIgSQBnkc7JdA/export?format=csv[Gewicht Einheit^]
* link:https://docs.google.com/spreadsheets/d/1arR-ugx3cZho51kI7D8b6h9jaLhf9MUVI4zNFI5xpPA/export?format=csv[Inhalt Mengeneinheit^]
* link:https://docs.google.com/spreadsheets/d/1Ig8_cgVC4XHfJLAMUzfNoDzhReBCHgIJs3b2VS8BZt8/format=csv[Verkaufsmengeneinheit^]
* link:https://docs.google.com/spreadsheets/d/1OxNdAbzGsIv7JY7Xep6lQVfvX8XWrBbpiwAnwK2mmV8/format=csv[Rückerstattung/Stornierung^]
* link:https://docs.google.com/spreadsheets/d/1W5JXuzx110dEO6zTieGokvzaFXrQHMG-EK-lwBb94oI/format=csv[Umsatzsteuer^]
endif::[]

ifeval::["{marketplace}" == "Voelkner"]
include::../instructions/katalog-mirakl-conrad-zuordnungen.adoc[]

In den folgenden CSV-Dateien kannst du die gültigen Werte für die jeweiligen Felder im Katalog einsehen:

* link:https://docs.google.com/spreadsheets/d/1ZsjMj1mTnASqrgr5UCAhxXUzgqrNVy3vEEmpP32POX8/export?format=csv[Akkus_Batterien^]
* link:https://docs.google.com/spreadsheets/d/17zwR35iT8Pi3xcEVDz6ue4hU0S-sp7X5gI90XedLoj8/export?format=csv[Energieeffizienzklassen^]
* link:https://docs.google.com/spreadsheets/d/1lnV-EPF2bhjEOdEypiZOil5zbGe-1JTIgSQBnkc7JdA/export?format=csv[Gewicht Einheit^]
* link:https://docs.google.com/spreadsheets/d/1arR-ugx3cZho51kI7D8b6h9jaLhf9MUVI4zNFI5xpPA/export?format=csv[Inhalt Mengeneinheit^]
* link:https://docs.google.com/spreadsheets/d/1Ig8_cgVC4XHfJLAMUzfNoDzhReBCHgIJs3b2VS8BZt8/format=csv[Verkaufsmengeneinheit^]
* link:https://docs.google.com/spreadsheets/d/1OxNdAbzGsIv7JY7Xep6lQVfvX8XWrBbpiwAnwK2mmV8/format=csv[Rückerstattung/Stornierung^]
* link:https://docs.google.com/spreadsheets/d/1W5JXuzx110dEO6zTieGokvzaFXrQHMG-EK-lwBb94oI/format=csv[Umsatzsteuer^]

[IMPORTANT]
.Fehlende Marken
====
Wenn dir auffällt, dass eine Marke fehlt, wende dich an stefanie.schlosser@re-in.de.
====
endif::[]

////
// Wenn es passt, kann ein Beispiel für ein Feld gegeben werden:

=== _Beispiel:_ Feld "{beispiel-feld}" zuordnen

:beispiel-feld:

include::../../_textblocks/instructions/katalog-beispielfeld.adoc[]
////

[#475]
== Varianten mit {marketplace} Catalog-Kategorie verknüpfen

Nachdem du mit dem Assistenten *{marketplace}* oder manuell ein Marktplatz-Format für {marketplace} erstellt hast, wird in deinem plentymarkets System die Eigenschaft *{marketplace}* erstellt. Für jede Kategorie, die du im ersten Schritt *Einstellungen* des Assistenten wählst, wird die gewählte Kategorie als neuer Auswahlwert zur Eigenschaft *{marketplace} Kategoriegruppe* hinzugefügt. Damit deine Varianten im gewünschten Katalog exportiert werden, müssen sie im *Tab: Eigenschaften* einer Variante mit der Eigenschaft *{marketplace} Kategoriegruppe* verknüpft werden.

[.instruction]
Variante mit Kategorie verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten »* _Artikel öffnen_.
. Wechsele in das *Tab: Varianten*.
. Öffne die Variante, die du verknüpfen möchtest.
. Wechsele in das *Tab: Eigenschaften*.
. Wähle im Bereich *Varianteneigenschaften* aus der Dropdown-Liste *Eigenschaften* die Eigenschaft *{marketplace} Kategoriegruppe* und klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird hinzugefügt.
. Wähle für die Eigenschaft *{marketplace} Kategoriegruppe* aus der Dropdown-Liste *Wert* die gewünschte Kategorie. +
→ Die Variante wird im zugehörigen Katalog exportiert. +
*_Beispiel:_* Wählst du den Wert *{category-example}*, wird die Variante im Katalog für die Kategorie *{category-example}* exportiert.
. Wiederhole die Schritte 5 und 6 für alle Kategorien, in denen du die Variante verkaufen willst.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

=== Eigenschaften mit Varianten verknüpfen und Werte speichern

include::../../_textblocks/instructions/properties-link.adoc[]

[#{marketplace}]
=== Katalogexport aktivieren

:interval: Täglich
:market: {marketplace}

include::../../_textblocks/instructions/catalogue-activation.adoc[]

[#700]
== Variantenverfügbarkeit einstellen

:market-availability: {marketplace}
:option-availability: {marketplace}

include::../../_textblocks/instructions/variantenverfuegbarkeit.adoc[]

// Beachten: Bei manchen Marktplätzen muss zusätzlich zum Marktplatz auch die Web-API aktiviert werden. Dann :web-api: angeben, damit der Text ausgegeben wird.

[#480]
== Ereignisaktionen einrichten

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um den Auftragsstatus bei {marketplace} automatisch zu aktualisieren, wenn bestimmte Ereignisse eintreten. Folgende Ereignisaktionen können eingerichtet werden:

// Welche Ereignisaktionen es gibt hängt vom Marktplatz ab. Hier die gängigsten. Bei Bedarf anpassen!

* Auftragsbestätigung an {marketplace} melden
* Versandbestätigung an {marketplace} melden
* Auftragsstornierung an {marketplace} melden
* Rückerstattung an {marketplace} melden

In den folgenden Kapiteln wird beschrieben, wie du die Ereignisaktionen in plentymarkets einrichtest.

[IMPORTANT]
.Weitere Aktionen vorhanden
====
Zusätzlich zu den oben genannten Ereignisaktionen werden durch das {marketplace}-Plugin noch weitere Ereignisaktionen zu Verfügung gestellt. Es gibt diese Aktionen, da sich die Auftragsverarbeitung in plentymarkets und Mirakl voneinander unterscheiden.

Wir empfehlen allerdings, nur die Aktionen zu verwenden, die hier im Detail beschrieben sind.
====

ifeval::["{marketplace}" == "Conrad"]
include::../automation/mirakl-conrad.adoc[]
endif::[]

ifeval::["{marketplace}" == "Voelkner"]
include::../automation/mirakl-voelkner.adoc[]
endif::[]

////
TODO:

* Gibt es Besonderheiten im Katalog. Ggf. Include-Dateien anpassen.

////
