= Daten über dynamischen Import importieren
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Daten importieren, Datenimport, Synchronisieren, Synchronisation, Datenformat, Datenformate, dynamischer Import, Abgleich, Importoptionen, Zuordnung, Importdaten
:description: Erfahren Sie, wie Sie Datenformate erstellen und den dynamischen Import nutzen.
:position: 20
:url: daten/export-import/daten-importieren

Diese Handbuchseite beschreibt verschiedene Möglichkeiten des manuellen Datenimports über den dynamischen Import. Ein Import von Daten ist ratsam, wenn Sie z.B. neue Artikel, Kundendaten oder Lagerbestände in Ihr plentymarkets System einpflegen möchten und die Daten bereits digital vorliegen.


[TIP]
.Plugin ElasticSync verwenden
====
Die in diesem Bereich beschriebenen Importmöglichkeiten sind veraltet. Verwenden Sie stattdessen das Plugin link:https://marketplace.plentymarkets.com/plugins/integration/ElasticSync_4750[ElasticSync^], um Daten in plentymarkets zu importieren.
====


[#5]
== Daten über dynamischen Import importieren

Eine Einführung zum dynamischen Import erhalten Sie im folgenden Videotutorial:

video::119849465[vimeo]

[#10]
== Datenformat erstellen

Das Datenformat, das Sie importieren, muss der Konfiguration des Datenformats in plentymarkets entsprechen, damit die Daten zugeordnet werden. Hierzu gehört auch, dass die Schreibweise der Datenfelder der Schreibweise in plentymarkets entspricht. Auf der Handbuchseite eines <<daten/export-import/datenformate#, Datenformats>> finden Sie die Namen der Datenfelder aufgelistet. Beachten Sie auch die Hinweise zur Angabe von Pflichtfeldern und Abgleichfeldern. Sie haben die Möglichkeit, mit Hilfe eines Tabellenkalkulationsprogramms selbst eine Datei für den Import zu erstellen.

Sie können sich diese Arbeit erheblich erleichtern, indem Sie das Datenformat vorab in eine Datei exportieren, Ihre Daten in der Datei bearbeiten und diese dann wieder importieren. Diese Vorgehensweise ist nur bei Datenformaten möglich, die sowohl einen Import als auch einen Export erlauben. Weitere Informationen zum Umgang mit Export- und Importdateien finden Sie im Kapitel <<daten/export-import/daten-exportieren#05, Datei für den Datenaustausch anpassen>> auf der Handbuchseite <<daten/export-import/daten-exportieren#, Daten exportieren>>. Gehen Sie wie im Folgenden beschrieben vor, um Ihre Daten in eine Datei zu exportieren:

[.instruction]
Datenformat erstellen:

. Öffnen Sie das Menü *Daten » Dynamischer Export*.
. Wechseln Sie in das Tab *Neues Datenformat*.
. Wählen Sie einen *Datenformat-Typ* aus der Dropdown-Liste.
. Ändern Sie ggf. den automatisch vergebenen *Datenformatsname*.
. Aktivieren Sie die Datenfelder, die in der Exportdatei vorhanden sein sollen.
. Wählen Sie eine *Importaktion* pro Datenfeld. +
→ Beachten Sie die Hinweise zu Abgleichfeldern auf den Unterseiten der Handbuchseite <<daten/export-import/datenformate#, Datenformate>>.
. Wählen Sie ggf. *Filter* oder *Aktionen*.
. *Speichern* Sie das Datenformat. +
→ Die Reihenfolge der Datenfelder wird anhand der Werte in der Spalte *Position* gespeichert.

[#25]
[TIP]
.Abgleich und Import
====
Bei einem Datenformat stehen für die Datenfelder die Importaktionen *Abgleich* und *Import* zur Verfügung. +
Mit der Einstellung *Import* werden die Daten, importiert - unabhängig davon, ob bereits Daten vorhanden sind oder nicht. Das bedeutet, dass die Daten bei einem Import eventuell überschrieben werden. Mit der Einstellung *Abgleich* wird das Datenfeld vor einem Import mit bereits im System vorhandenen Daten abgeglichen. Die Daten werden nur importiert, wenn noch keine Daten vorhanden sind.
====

[#20]
== Dynamischen Import nutzen

Der dynamische Datenimport erfolgt im Menü *Daten » Dynamischer Import*. Sie können hier selbst erstellte Dateien oder die Datenformate, die Sie im Menü *Daten » Dynamischer Export* erstellt haben (sog. Kundenformate), wieder importieren. Im Menü *Daten » Dynamischer Import* stehen Ihnen neben den Kundenformaten in der Dropdown-Liste *Format* zwei Spezialformate zur Verfügung:

* das Spezialformat *ItemParcelServicePreset*, mit dem Sie Versandprofile importieren
* das Spezialformat *IncomingItems*, mit dem sie Wareneingangsdaten importieren

Die Spezialformate sind reine Importformate und stehen daher nur im Menü *Daten » Dynamischer Import* zur Verfügung. Der Import der Spezialformate funktioniert auf die gleiche Weise, wie Sie auch die anderen Datenformate importieren. Die Vorgehensweise wird im Folgenden beschrieben.

[NOTE]
.Spaltenkopfbezeichnungen prüfen und anpassen
====
Wenn Daten aus einem externen System importiert werden sollen oder Sie Datei selbst erstellt haben, müssen die Spaltenkopfbezeichnungen in der Datei mit der von plentymarkets vorgegebenen Schreibweise der Datenfelder (Feldnamen) exakt übereinstimmen. +
Kann plentymarkets beim Import keine Zuordnung zu einer gewählten Exportvariante herstellen, wird der Import mit einer Fehlermeldung abgebrochen. Die Fehlermeldung finden Sie im Bereich *Bearbeitungsstatus*. Prüfen Sie die Spaltenkopfbezeichnungen der zu importierenden Datei und passen Sie diese bei Bedarf an.
====

[.instruction]
Daten per dynamischen Import importieren:

. Öffnen Sie das Menü *Daten » Dynamischer Import*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-einstellungen-menü-daten-dynamischer-import>>. +
*_Hinweis:_* Pro Import können maximal 6000 Datensätze importiert werden.
. Klicken Sie auf *Import*.
. Prüfen Sie, ob die importierten Daten im System gespeichert wurden.

[IMPORTANT]
.Bearbeitungsstatus
====
Nachdem Sie die Datei importiert haben, erhalten Sie eine Meldung im Bereich *Bearbeitungsstatus*. Wenn Datenzeilen erfolgreich importiert wurden, wird die Anzahl der importierten Zeilen angegeben. Im Fehlerfall steht dort der Eintrag *0* und eine Fehlermeldung wird angezeigt. Prüfen Sie das Feldtrennzeichen oder die Codierung der Datei. Die Datei sollte immer UTF-8-codiert sein.
====

Beachten Sie, dass die Einstellungen, die angezeigt werden, von dem Datenformat abhängig sind, das Sie für den Import gewählt haben. Für das Datenformat *Stock* z.B. wählen Sie statt einer Abgleichoption das *Lager* und den *Barcode*. Die Einstellungen, die in <<tabelle-einstellungen-menü-daten-dynamischer-import>> beschrieben sind, gelten für die Mehrheit der Datenformate.

[[tabelle-einstellungen-menü-daten-dynamischer-import]]
.Einstellungen im Menü *Daten » Dynamischer Import*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Feldtrennzeichen*
|Feldtrennzeichen wählen, das in der Importdatei eingestellt ist.

|*Format*
|Datenformat wählen, das Sie für den Datenimport vorbereitet haben. +
*_Hinweis:_* Je nachdem, welches Datenformat Sie hier wählen, ändern sich die folgenden Einstellungen.

|*Wenn beim Abgleich keine Übereinstimmung*
|Eine der folgenden Optionen wählen:  +
*Neuen Datensatz anlegen* = Wenn die zu importierenden Daten noch nicht im System vorhanden sind. +
*Vorhandenen Datensatz überspringen* = Wenn beim Abgleich vorhandene Daten nicht überschrieben werden sollen.

|*Datei*
|Importdatei vom Speicherort wählen.
|====

Erfahren Sie mehr über die Informationen im Bereich *Bearbeitungsstatus*, mögliche Fehlermeldungen und deren Ursachen im folgenden Videotutorial:

video::141644702[vimeo]

[#210]
== eBay-Listings importieren

Im Menü *Daten » eBay-Listings* importieren Sie eBay-Listings. Es wird sowohl ein Artikelstammdatensatz als auch ein Listing in plentymarkets erstellt. Im Bereich *Bearbeitungsstatus* haben Sie während des Importprozesses Einsicht in den aktuellen Verlauf des Imports. Wie Sie die Listings importieren, ist auf der Handbuchseite von <<maerkte/ebay/ebay-einrichten#, eBay>> im Kapitel <<maerkte/ebay/ebay-einrichten#11000, eBay-Listings importieren>> beschrieben.


////
== Anwendungsbeispiel: Artikel erstellen und Artikeldaten anpassen

Im Menü *Daten* erstellen Sie Artikel oder ändern bestehende Artikeldaten. Diese Funktion bietet sich an, wenn Sie z.B. Artikellisten von Ihrem Lieferanten in plentymarkets importieren möchten oder den Preis Ihrer Artikeln anpassen möchten. Erstellen Sie zunächst das Datenformat *Item* im Menü *Daten » Dynamischer Export*. Exportieren Sie dann die Daten in eine Datei und bearbeiten Sie die Daten in der Datei. Abschließend importieren Sie diese Datei im Menü *Daten » Dynamischer Import*.

Erfahren Sie mehr über das Erstellen und Aktualisieren von Artikeldaten im folgenden Videotutorial:

video::140275175[vimeo]


[#120]
== Anwendungsbeispiel: Warenbestand importieren

Sie haben auch die Möglichkeit, den kompletten Warenbestand zu importieren, bei dem aktuelle physische Warenbestände in Ihrem plentymarkets System überschrieben werden. Nutzen Sie dazu das Datenformat <<daten/export-import/datenformate/stock#, Stock>>.

[WARNING]
.Warenbestand wird gelöscht
====
Bei diesem Vorgang werden die aktuellen physischen Warenbestände durch den Import ersetzt, d.h. Ihr gesamter Warenbestand wird gelöscht. Reservierte Warenbestände bleiben dabei erhalten.

Wenn Sie nicht den kompletten Warenbestand importieren möchten, sondern nur Wareneingänge per Datenimport hinzufügen möchten, verwenden Sie das Spezialformat *IncomingItems*.
====

Wenn Sie die Importdatei vor dem Import bearbeiten möchten, beachten Sie die folgenden Erläuterungen zu den Datenfeldern. <<tabelle-datenfelder-datenformat-stock>> erläutert eine Auswahl der in der exportierten Datei enthaltenen Datenfelder.

[[tabelle-datenfelder-datenformat-stock]]
.Dynamischer Import; Datenfelder des Datenformats *Stock*
[cols="1,3"]
|====
|Feldname |Erläuterung

|*ItemID*
|Artikel-ID

|*VariationEAN*
|EAN-Code der Variante

|*PurchasePrice*
|Einkaufspreis

|*VariationNo*
|Variantennummer

|*LocationID*
|Lagerort-ID +
Jeweils die Ziffer 0 eingeben, wenn kein Lagerort vorhanden ist oder keine Zuordnung erfolgen soll.

|*Stock*
|Warenbestand

|*WarehouseID*
|ID des Lagers

|*VariationString*
|Systemnamen-Hash der Attribute und Werte. +
*_Beispiel:_* "Farbe:Blau;Größe:XXL" +
Die Namen bzw. Bezeichnungen der Attribute und Werte werden verwendet.
|====

[.instruction]
Datenimport durchführen:

. Öffnen Sie das Menü *Daten » Dynamischer Import*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-importoptionen-datenformat-stock>>.
. Klicken Sie auf *Import*.

[[tabelle-importoptionen-datenformat-stock]]
.Dynamischer Import; Importoptionen des Datenformats *Stock*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Feldtrennzeichen*
|Trennzeichen wählen.

|*Format*
|Datenformat *Stock* für den Import wählen.

|*Lager*
|Lager für den Import wählen.

|*Barcode*
|Barcode für den Import wählen.

|*Datei*
|Datei für den Import wählen.
|====

Sie erhalten im Menü *Daten » Dynamischer Import* im Bereich *Bearbeitungsstatus* eine detaillierte Meldung des Datenimports. Unter anderem werden das Format, der Dateiname, der Benutzer und das Datum des Imports in diesem Bereich angezeigt.
////
