= Template-Funktionen
:lang: de
// include::{includedir}/_header.adoc[]
:position: 90

== Allgemeines

Die CMS-Syntax unterstützt unterschiedliche Arten von Funktionen, welche entweder global oder nur innerhalb bestimmter Templates verwendet werden können.

== Globale Funktionen

In diesem Bereich sind solche Funktionen zu finden, welche sowohl im Bereich Webdesign als auch in E-Mail-Vorlagen verwendet werden können.

Einige PHP-Funktionen wurden auch in der CMS-Syntax zugänglich gemacht. Die Verwendung ist weitestgehend identisch mit der Verwendung direkt in PHP.

<<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions, PHP Funktionen öffnen>>

== Webdesign

[.row]
====
[.col-md-6]
.PageDesign
=====
Vorranging finden Sie in diesem Bereich Link-Funktionen, welche URLs auf bestimmte Bereiche (u.a. Kategorien, Startseite, Warenkorb) zurückliefern.

<<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-pagedesign, PageDesign öffnen>>
=====

[.col-md-6]
.Navigation
=====
Die unterschiedlichen Container zur Darstellung von Navigationsmenüs (Kategorie-Navigation) werden über Funktionen dieses Bereichs aufgerufen.

<<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-navigation, Navigation öffnen>>
=====
====

[.row]
====
[.col-md-6]
.ItemView
=====
Zur Darstellung von Artikeln (u.a. Produktseite, Suchergebnis) stehen die meisten Container und demzufolge auch die größte Anzahl an Funktionen zur Verfügung.

<<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview, ItemView öffnen>>
=====

[.col-md-6]
.Category
=====
Dieser Bereich verfügt über eine sehr übersichtliche Anzahl an Funktionen. Relevant ist jedoch die Funktion Form(), welche ein Formular zurückliefert.

<<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-category, Category öffnen>>
=====
====
== E-Mail-Vorlagen

Innerhalb von E-Mail-Vorlagen stehen einige Link-Funktionen zur Verfügung.

<<omni-channel/online-shop/webshop-einrichten/cms-syntax#e-mail-email, E-Mail öffnen>>

