= Praxisbeispiele: Prozesse
:lang: de
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: Prozesse, Prozess, Beispielprozesse, Beispiel Prozesse, Beispielprozess, Beispiel Prozess, Prozess Filter, Prozessfilter, plenty Base, plentyBase, Prozesse Anwendungsfall, Anwendungsfall, Best Practice, Praxisbeispiele Prozesse, Praxisbeispiel Prozess
:position: 70
:url: automatisierung/prozesse/best-practices
:id: MMOGYLL

Hier findest du einige Beispielprozesse. Aber auch ein Blick ins plentymarkets Forum lohnt sich: In unserem link:https://forum.plentymarkets.com/c/suche-biete/prozess-basar[Prozessbasar^]{nbsp}icon:external-link[] findest du weitere Beispielprozesse von engagierten Händler:innen.

[IMPORTANT]
.Hinweise zum Umgang mit Beispielprozessen
====
Die im Folgenden verlinkten Beispielprozesse nehmen dir einige Arbeitsschritte ab und helfen dir so, deine Abwicklungsprozesse in plentymarkets einzurichten. Beachte jedoch, dass sie immer nur eine Basis darstellen. Nachdem du einen Beispielprozess importiert hast, musst du noch einige Einstellungen überprüfen und anpassen. Welche dies genau sind, ist bei jedem Beispielprozess auf dieser Seite einzeln vermerkt.
====

[#100]
== Grobkommissionierung über Mobile Pickliste inkl. Label, Rechnung, Lieferschein und Warenausgang

Das folgende Video erklärt, wie du mithilfe der Prozesse für bestimmte Aufträge automatisch eine Mobile Pickliste erzeugst. Die Grob-Kommissionierung erfolgt mithilfe der plentymarkets App. Das Beispiel liefert aktuell nur Aufträge, die aus einer Auftragsposition mit der Artikelmenge 1 bestehen. Wenn du also zuerst solche Aufträge bearbeiten möchtest und danach die komplexeren Aufträge, dann lege einfach zwei unterschiedliche Prozesse an. Importiere dieses Beispiel einfach noch einmal und passe die Filter entsprechend an.

Schau dir das folgende Video an, um die einzelnen Einstellungen genauer nachzuvollziehen. 
link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/plentyprocess/MPickL-Video_2021_04_26_16_33_56.plentyprocess[Klicke außerdem hier^], um den passenden Beispielprozess herunterzuladen und in dein plentymarkets System zu importieren.

video::131830323[vimeo]

[.collapseBox]
.*Wie importiere ich einen Prozess?*
--
Gehe wie unten beschrieben vor, um Prozesse in dein plentymarkets System zu importieren.

[.instruction]
Prozess importieren:

. Öffne das Menü *Einrichtung » Prozesse*.
. Klicke auf *Import*.
. Gib einen Namen für den Prozess ein und klicke auf *Dateien wählen*.
. Wähle die Prozessdatei auf deinem Computer aus und klicke auf *Öffnen*.
→ Der Prozess wird importiert und zur Bearbeitung geöffnet.
--

[WARNING]
.Einstellungen prüfen
====
Prüfe nach dem Import des Prozesses die folgenden Einstellungen und passe sie auf deine Abläufe an:
* Auswahl des Auftragsstatus 
* Speicherort
* Lager
*_Tipp_* Achte auf das rote Käfer-Symbol (icon:debug[role=red]). Dieses wird dir automatisch an den Prozesselementen angezeigt, die zu Problemen führen können und somit vor der Nutzung des Prozesses angepasst werden müssen.
====

[#200]
== Grobkommissionierung über Papier, Feinkommissionierung über Box-Regal inkl. Label, Rechnung, Lieferschein und Warenausgang

Dieser Prozess ist für dich geeignet, wenn du die Grobkommissionierung mit einer traditionellen Papierliste vornehmen möchten. Die Feinkommissionierung erfolgt durch das Scannen von Artikeln, worauf eine Box-Nummer dargestellt wird. Sobald eine Box vollständig kommissioniert wurde, werden die definierten Dokumente (Rechnung, Lieferschein und Label) ausgedruckt und der Warenausgang für den Auftrag gebucht.

Schau dir das folgende Video an, um die einzelnen Einstellungen genauer nachzuvollziehen.
link:https://s3.eu-central-1.amazonaws.com/download.plentybase.de/process_configs/boxkomissionierung_video.plentyprocess[boxkomissionierung_video.plentyprocess]{nbsp}icon:external-link[Klicke außerdem hier^], um den passenden Beispielprozess herunterzuladen und in dein plentymarkets System zu importieren.

video::88665194[vimeo]

[WARNING]
.Einstellungen prüfen
====
Prüfe nach dem Import des Prozesses die folgenden Einstellungen und passe sie auf deine Abläufe an:
* Auswahl des Auftragsstatus 
* Speicherort
* Lager
*_Tipp_* Achte auf das rote Käfer-Symbol (icon:debug[role=red]). Dieses wird dir automatisch an den Prozesselementen angezeigt, die zu Problemen führen können und somit vor der Nutzung des Prozesses angepasst werden müssen.
====

== Grob- & Fein-Kommissionierung über Papier, dann Auftragssuche und Versand

Dieses Beispiel ist eine weitere Alternative zur Versandabwicklung. In diesem Prozess wird zuerst eine Pickliste und dann eine Packliste ausgedruckt. Danach erwartet das System eine Sucheingabe, um dann für den gefundenen Auftrag den weiteren Versandprozess abwickeln lassen zu können.

Die Auftragssuche soll dabei mit einem Barcode-Scanner vorgenommen werden. Auf der Packliste befindet sich dazu der passende Barcode, der die Order-ID enthält und so den gewünschten Auftrag direkt auffindet.

Im Beispiel wird der Vorgang in nur einem zusammenhängenden Prozess bestehend aus zwei Arbeitsschritten dargestellt. Denkbar ist natürlich auch, dass du daraus zwei Prozesse erstellst: Der erste Prozess beinhaltet dann nur den ersten Arbeitsschritt, also den Druck der Pick- und Packliste. Der zweite Prozesse umfasst die Auftragssuche und die weitere Abwicklung. Durch eine Aufteilung kann erreicht werden, dass beispielsweise im Büro ein Stapel Pick- und Packlisten erstellt und dann an die Kolleg:innen im Lager verteilt wird. Im Lager wird die Ware gesammelt und am Packtisch wird nur der zweite Prozess, also Auftragssuche etc., ausgeführt.

Das Beispiel enthält auch die Aktion *Polling* für das Format DHL-Easylog. Dies bedeutet, dass dabei lediglich für den aktuellen Auftrag eine Exportdatei mit den Lieferinformationen im definierten Ordner auf deinem Rechner gespeichert wird. Dieser Ordner sollte von der Software des Packetdienstleisters (z.B. Easylog) überwacht werden, damit neue Dateien direkt importiert (Polling) werden und ein Label erstellt werden kann.

Wenn eine solche Software nicht zum Einsatz kommt, entferne einfach diese Aktion. Füge eine oder mehrere Versand-Center-Aktionen ein, um direkt Label erstellen und drucken lassen zu können.

Ebenfalls besonders an diesem Prozess ist, dass erst nach der Auftragssuche eine Änderung des *Auftragsstatus* vorgenommen wird. Dadurch kannst du immer live sehen, welche Aufträge sich gerade im Versand befinden.

=== Video-Tutorial zum Prozess

video::85295741[vimeo]

=== Importdatei für den Prozess

link:https://s3.eu-central-1.amazonaws.com/download.plentybase.de/process_configs/Packliste_%26_Auftrag_suchen.plentyprocess[Packliste_&_Auftrag_suchen.plentyprocess]{nbsp}icon:external-link[] (1,1 KB)

[TIP]
.Nicht vergessen
====
Nach dem Import müssen die einzelnen Einstellungen geprüft werden (z.B. Auftragsstatus Auswahl, Speicherorte, Lager).
====


== Verschiedene Versanddienstleister, Seriennummern erfassen, Fein-Kommissionierung über Box-Regal

Die Aktion *Filter* ist ein mächtiges Werkzeug, da sich damit sehr komplexe Prozesse bauen lassen, die auf unterschiedliche Zustände reagieren können.

=== Filter

Aus dem Bereich E-Mail-Vorlagen oder CMS kennt ihr bereits IF-ELSE, also Fallunterscheidungen. Die Aktion *Filter* ist genau das: Pro Filter können ein oder mehrere Bedingungen definiert werden. Nur wenn diese Bedingungen zutreffen, werden die darauffolgenden Aktionen ausgeführt.

**Mehr dazu in diesem Video**

video::84490940[vimeo]


=== Versand-Center & Fehler

video::112337730[vimeo]

=== Prozess & Filter

Im folgenden Video wird der Beispielprozess *Unterschiedliche_Versanddienstleister.plentyprocess* genauer erklärt.

video::87317994[vimeo]

=== Importdatei für den Prozess

link:https://s3.eu-central-1.amazonaws.com/download.plentybase.de/process_configs/Unterschiedliche_Versanddienstleister.plentyprocess[Unterschiedliche_Versanddienstleister.plentyprocess]{nbsp}icon:external-link[] (1,7 KB)

[TIP]
.Nicht vergessen
====
Nach dem Import müssen die einzelnen Einstellungen geprüft werden (z.B. Auftragsstatus Auswahl, Speicherorte, Lager).
====
