= plentyBase installieren
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentyBase, Prozesse, Drucken, Drucker installieren, Prozesse ausführen, Automatisierung, Druckverlauf, Druckhistorie, base
:description: plentyBase installieren
:position: 3
:url: automatisierung/prozesse/plentybase-installieren
:id: ZDXC8YS

plentyBase ist ein Tool, was die Kommunikation zwischen deinem eigenen Rechner und plentymarkets ermöglicht.

Das Tool plentyBase muss für die folgenden Abläufe in plentymarkets auf dem Rechner installiert und gestartet sein:

* Prozesse
** Prozesse im plentymarkets Backend erstellen
** Prozesse im plentymarkets Backend ausführen
* Drucken
** Dokumente aus dem plentymarkets Backend drucken
** Druckverlauf im plentymarkets Backend aufrufen
** plentymarkets POS Kassenbelege auf lokalen Druckern drucken
* Speichern
** Dokumente aus dem plentymarkets Backend auf dem lokalen Rechner speichern

Wenn plentyBase auf dem Rechner installiert ist, können diese Abläufe über das plentymarkets Backend ausgeführt werden.

Lerne plentyBase spielerisch kennen:

.plentyBase
video::232837642[vimeo]

Die Installationsdateien und die Dokumentation für plentyBase findest du im link:https://marketplace.plentymarkets.com/plugins/integration/plentybase_5053[plentyMarketplace^].
