= Prozesse ausführen
:lang: de
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: Prozesse ausführen, Prozess starten, Prozess anstoßen
:position: 20
:url: automatisierung/prozesse/prozesse-ausfuehren
:id: OM8HCEJ

[IMPORTANT]
.plentyBase installieren
====
Du benötigst das Tool <<automatisierung/prozesse/plentybase-installieren#, plentyBase>>, um Prozesse im plentymarkets Backend zu erstellen und auszuführen. Die Installationsdateien für plentyBase findest du im link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentyMarketplace^]{nbsp}icon:external-link[].
====

Über das Menü *Prozesse* führst du die Prozesse aus, die im Menü <<automatisierung/prozesse/prozesse-einrichten#, Einrichtung » Prozesse>> erstellt wurden.

[#10]
== Prozess ausführen

Gehe wie unten beschrieben vor, um einen Prozess auszuführen. Beachte, dass nur die Prozesse angezeigt werden, die deinem Benutzerkonto oder deiner Rolle <<automatisierung/prozesse/prozesse-einrichten#10, zugeordnet>> wurden.

[IMPORTANT]
.Sichtbarkeit des Menüs Prozesse
====
Benutzer:innen mit Admin-Rechten haben standardmäßig die Berechtigung, das Menü *Prozesse* aufzurufen und Prozesse auszuführen. Benutzer:innen mit der Benutzerklasse *Backend* musst du diese Berechtigung erteilen. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*. Öffne das Konto und aktiviere in der Ansicht *Rechte* die Menü-Sichtbarkeit *Prozesse*.
====

[.instruction]
Prozess ausführen:

. Öffne das Menü *Prozesse*. +
→ Die verfügbaren Prozesse werden angezeigt.
. Klicke auf einen Prozess. +
→ Der Prozess wird angezeigt und befindet sich im Status *Wartend*.
. Klicke auf *Start*. +
→ Der Prozess wird gestartet. +
→ Die Balken im Tab *Arbeitsschritte* zeigen den Fortschritt der einzelnen Prozessschritte an. +
→ Abhängig vom gewählten Prozess ist während der Ausführung ein Eingreifen der Person erforderlich, die den Prozess ausführt.
