= Prozesse ausführen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Prozesse ausführen, plentyBase, plentymarkets Client
:position: 20

[IMPORTANT]
.plentyBase installieren
====
Sie benötigen das Tool plentyBase, um Prozesse im plentymarkets Backend zu erstellen und auszuführen. Die Installationsdateien für plentyBase finden Sie im link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentyMarketplace^].
====

Über das Menü *Prozesse* führen Sie die Prozesse aus, die im Menü <<automatisierung/prozesse/prozesse-einrichten#, System » Systemeinstellungen » Prozesse>> erstellt wurden.

[#10]
== Prozess ausführen

Gehen Sie wie unten beschrieben vor, um einen Prozess auszuführen. Beachten Sie, dass nur die Prozesse angezeigt werden, die Ihrem Benutzerkonto oder Ihrer Rolle <<automatisierung/prozesse/prozesse-einrichten#10, zugeordnet>> wurden.

[IMPORTANT]
.Sichtbarkeit des Menüs System » Systemeinstellungen » Prozesse
====
Für Konten der Klasse *Variabel* ist das Menü *System » Systemeinstellungen » Prozesse* nur sichtbar, wenn im Profil die <<basics/admin-aufgaben/benutzer-verwalten#, Berechtigung>> dazu erteilt wurde.
====

[.instruction]
Prozess ausführen:

. Öffnen Sie das Menü *Prozesse*. +
→ Die verfügbaren Prozesse werden angezeigt.
. Klicken Sie auf einen Prozess. +
→ Der Prozess wird angezeigt und befindet sich im Status *Wartend*.
. Klicken Sie auf *Start*. +
→ Der Prozess wird gestartet. +
→ Die Balken im Tab *Arbeitsschritte* zeigen den Fortschritt der einzelnen Prozessschritte an. +
→ Abhängig vom gewählten Prozess ist während der Ausführung ein Eingreifen der Person erforderlich, die den Prozess ausführt.
