= Subaktionen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Subaktionen, Prozesse, plentyBase, Prozess, Subaktion, Automatisierung
:description: Übersicht der Subaktionen, die du für Prozesse konfigurieren kannst.
:position: 50
:url: automatisierung/prozesse/subaktionen

Auf dieser Handbuchseite findest du Erläuterungen zu den Subaktionen, die du im Menü **System » Systemeinstellungen » Prozesse** zu den Aktionen deiner Prozesse hinzufügen kannst.

Die Subaktionen sind in alphabetischer Reihenfolge aufgelistet. Der Aufbau der Informationen pro Subaktion folgt diesem Muster:

* Kurze Erläuterung der Subaktion
* Aktionen, für die die Subaktion verfügbar ist
* Einstellungen, die zusätzlich zu den <<automatisierung/prozesse/subaktionen#100, allgemeinen Einstellungen>> für diese Subaktion verfügbar sind

Die Informationen auf dieser Seite dienen als Nachschlagewerk für Benutzerinnen und Benutzer, die mit den Grundprinzipien von plentymarkets Prozessen vertraut sind. Grundlegende Informationen zu Prozessen findest du auf der Handbuchseite <<automatisierung/prozesse/prozesse-einrichten#, Prozesse einrichten>>.

[IMPORTANT]
.Tool plentyBase erforderlich
====
Um Prozesse zu erstellen und auszuführen benötigst du das Tool plentyBase. Die Installationsdateien für plentyBase findest du im link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentyMarketplace^].
====

[#110]
== Allgemeine Einstellungen

Bestimmte Einstellungen sind für alle Subaktionen verfügbar. <<tabelle-subaktion-einstellungen-allgemein>> erläutert diese Einstellungen.

[[tabelle-subaktion-einstellungen-allgemein]]
.Allgemeine Einstellungen für Subaktionen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Position**
|Zeigt die aktuelle Position der Subaktion innerhalb der Aktion an. Die Subaktion mit der niedrigsten Positionsnummer wird als erstes ausgeführt. Andere Position aus der Dropdown-Liste wählen, um die Abfolge der Subaktionen in der Aktion zu ändern.
|====

[#120]
== Artikel scannen

Die Subaktion **Artikel scannen** öffnet eine Eingabemaske zum Scannen von Artikeln mit einem Barcode-Scanner.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#160, Artikelsuche>>

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[#130]
== Auftragsnotizen hinzufügen

Mit der Subaktion **Auftragsnotizen hinzufügen** fügst du einem Auftrag eine Notiz hinzu.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#170, Auftrag>>

[.subhead]
Einstellungen

<<tabelle-subaktion-auftragsnotizen-hinzufuegen>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-auftragsnotizen-hinzufuegen]]
.Subaktion **Auftragsnotizen hinzufügen**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Notiz
|Wählen, welche Art von Notizen zum Auftrag hinzugefügt werden soll. +
**Individuelle Eingabe** = Ermöglicht die Eingabe einer Nachricht durch die Person, die den Prozess ausführt, im Prozessablauf. Die Notiz wird am Auftrag hinterlegt. +
**Vordefinierte Eingabe** = Öffnet ein Fenster, in dem im Bereich **Nachricht** eine Nachricht hinterlegt werden kann, die im Prozessablauf bei Aufträgen automatisch als Notiz hinterlegt wird. +
**Keine** = (Nur bei Aktion im Fehlerfall) Legt keine individuelle oder vorgefertigte Notiz am Auftrag an. Empfohlen, wenn nur die Fehlermeldung als Auftragsnotiz hinterlegt werden soll.

|Fehlermeldung als zusätzliche Notiz hinterlegen
|(Nur bei Aktion im Fehlerfall) Häkchen setzen, um die im Prozess ausgegebene Fehlermeldung als Notiz am Auftrag zu hinterlegen.
|====

[#140]
== Aus Prozess entfernen

Mit der Subaktion **Aus Prozess entfernen** entfernst du Aufträge aus dem Prozess. Der Auftrag wird auch aus Filtern oder angefangenen Boxkommissionierungen entfernt.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#170, Auftrag>>

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[#150]
== Bestellung scannen

Die Subaktion **Bestellung scannen** öffnet eine Maske, über die Bestellungen per Barcode-Scanner eingelesen werden.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#200, Bestellsuche>>

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[#160]
== Buchung durchführen

Mit der Subaktion **Buchung durchführen** wird automatisch der Wareneingang oder Warenausgang gebucht.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#440, Warenausgang>>
* <<automatisierung/prozesse/aktionen#450, Wareneingang (Bestellung)>>

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[#170]
== Buchung zurücksetzen

Mit der Subaktion **Buchung zurücksetzen** wird der gebuchte Warenausgang für die gewählten Aufträge zurückgesetzt.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#440, Warenausgang>>

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[#180]
== Drucken

Für den Druck von Dokumenten, zum Beispiel Lieferscheinen oder Rechnungen, wählst du beim Hinzufügen dieser Subaktion den gewünschten Drucker.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#110, Abhol-/Lieferschein>>
* <<automatisierung/prozesse/aktionen#120, Adressetikett>>
* <<automatisierung/prozesse/aktionen#130, Angebot>>
* <<automatisierung/prozesse/aktionen#150, Artikeletikett>>
* <<automatisierung/prozesse/aktionen#180, Auftragsbestätigung>>
* <<automatisierung/prozesse/aktionen#210, Dokumente>>
* <<automatisierung/prozesse/aktionen#240, Gelangensbestätigung>>
* <<automatisierung/prozesse/aktionen#250, Gutschrift>>
* <<automatisierung/prozesse/aktionen#270, Korrekturbeleg>>
* <<automatisierung/prozesse/aktionen#280, Lager-Pickliste>>
* <<automatisierung/prozesse/aktionen#290, Lieferschein>>
* <<automatisierung/prozesse/aktionen#300, Mahnung>>
* <<automatisierung/prozesse/aktionen#310, Packliste>>
* <<automatisierung/prozesse/aktionen#320, Pickliste>>
* <<automatisierung/prozesse/aktionen#350, Rechnung>>
* <<automatisierung/prozesse/aktionen#360, Reparaturschein>>
* <<automatisierung/prozesse/aktionen#380, Retourenetikett>>
* <<automatisierung/prozesse/aktionen#390, Rücksendeschein>>
* <<automatisierung/prozesse/aktionen#430, Versand-Center>>

[.subhead]
Einstellungen

<<tabelle-subaktion-drucken>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-drucken]]
.Subaktion **Drucken**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Druckereinstellung
|Eines der im Menü **System » Systemeinstellungen » Einstellungen » Drucker** gespeicherten <<basics/admin-aufgaben/drucker#, Druckerprofile>> wählen.

|Kopien
|Anzahl der Kopien pro Ausdruck eingeben.

|Als Sammeldokument
|Häkchen setzen, um alle Dokumente in einem einzigen Dokument zusammenzufassen und gleichzeitig zu drucken.
|====

[#190]
== Eigner ändern

Mit der Subaktion **Eigner ändern** führst du einen Eignerwechsel durch. Auswählbar sind die in Ihrem System hinterlegten Eigner.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#170, Auftrag>>

[.subhead]
Einstellungen

<<tabelle-subaktion-eigner-aendern>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-eigner-aendern]]
.Subaktion **Eigner ändern**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Eigner
|Den Eigner aus der Dropdown-Liste wählen, der durch die Subaktion zugewiesen werden soll. Zur Auswahl stehen alle im System angelegten Eigner.
|====

[#195]
== Entferne Auftrag vom Box

Die Subaktion **Entferne Auftrag vom Box** wird für die <<automatisierung/prozesse/rollende-kommissionierung, rollende Kommissionierung>> verwendet. Mit dieser Subaktion löst du die Verbindung zwischen Auftrag und Box. Somit steht die Box wieder frei zur Verfügung und kann beim nächsten Durchlauf wiederverwendet werden.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#170, Auftrag>>

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[#200]
== Hinweis anzeigen

Die Subaktion **Hinweis** zeigt einen Hinweistext an, den du hinterlegst. Einstellbar ist auch die Zeit, nach der der Hinweis wieder ausgeblendet werden soll.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#260, Hinweis>>

[.subhead]
Einstellungen

<<tabelle-subaktion-hinweis>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-hinweis]]
.Subaktion **Hinweis**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Titel**
|Aussagekräftigen Titel für den Hinweis eingeben, der angezeigt werden soll.

|**Automatisch schließen**
|Festlegen, ob der Hinweis automatisch geschlossen werden soll, nachdem er angezeigt wurde. +
**Nie** = Der Hinweis muss per Klick geschlossen werden. +
**Nach 1 - 5 Sekunden** = Der Hinweis wird danach automatisch geschlossen.

|**Nachricht**
|Text eingeben, der als Hinweis ausgegeben werden soll.
|====

[#210]
== Markierung ändern

Mit der Subaktion **Markierung ändern** führst du eine Änderung der Markierung aus. Auswählbar sind die in Ihrem System hinterlegten Markierungen.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#170, Auftrag>>

[.subhead]
Einstellungen

<<tabelle-subaktion-markierung-aendern>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-markierung-aendern]]
.Subaktion **Markierung ändern**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Markierung
|Markierung aus der Dropdown-Liste wählen, die durch die Subaktion zugewiesen werden soll.
|====

[#230]
== Notizen zum Auftrag

Bei der Subaktion **Notizen zum Auftrag** werden während des Prozesses in Verbindung mit der Aktion <<automatisierung/prozesse/aktionen#260, Hinweis>> die im Menü <<auftraege/auftraege-verwalten#1530, Aufträge » Aufträge bearbeiten » Tab: Übersicht>> hinterlegten Informationen angezeigt und können vom Bearbeiter berücksichtigt werden. Die Notizen können bei der Bestellung angegeben werden. Beispiel:

* Ihren kostenlosen Werbeartikel bitte nicht senden, habe dafür keine Verwendung!

Oder trage Notizen selbst ein. Beispiel:

* Keine Werbeartikel beilegen!

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#260, Hinweis>>

[.subhead]
Einstellungen

<<tabelle-subaktion-notizen-auftrag>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-notizen-auftrag]]
.Subaktion **Notizen zum Auftrag**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Sichtbarkeit
|Wählen, welche Notizen angezeigt werden sollen. +
**ALLE** = Alle Notizen werden angezeigt. +
**Nur Kundennotizen** = Nur Notizen werden angezeigt, die bei einer Bestellung eingegeben wurden. +
**Nur Mitarbeiternotizen** = Nur Notizen werden angezeigt, die Mitarbeiter eingegeben haben.
|====

[#240]
== Notizen zum Kunden

Bei der Subaktion **Notizen zum Kunden** werden während des Prozesses in Verbindung mit der Aktion <<automatisierung/prozesse/aktionen#260, Hinweis>> die im Menü **CRM » Kontakte » Ansicht: Notizen** hinterlegten Informationen angezeigt und können vom Bearbeiter berücksichtigt werden. +
Beispiel:

* Kontakt möchte keine Werbung erhalten.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#260, Hinweis>>

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[#245]
== Online speichern

Mit der Subaktion **Online speichern** speicherst du eine Online-Pickliste, die in der plentymarkets App aufgerufen und abgearbeitet werden kann.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#320, Pickliste>>

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[#250]
== Paketnummer erfassen

Mit der Subaktion **Paketnummer erfassen** erfasst du eine Paketnummer.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#170, Auftrag>>

[.subhead]
Einstellungen

<<tabelle-subaktion-paketnummer-erfassen>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-paketnummer-erfassen]]
.Subaktion **Paketnummer erfassen**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Paketnummern-Format
|Paketnummern-Format aus der Dropdown-Liste wählen.
|====

[#260]
== Seriennummern erfassen

Mit der Subaktion **Seriennummern erfassen** erfasst du im Prozessablauf <<artikel/artikel-verwalten#820, Seriennummern>> per Barcode-Scanner. Wähle, ob du neue Seriennummern erlauben möchtest und ob Seriennummern automatisch gespeichert werden sollen.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#420, Seriennummern>>

[.subhead]
Einstellungen

<<tabelle-subaktion-seriennummern-erfassen>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-seriennummern-erfassen]]
.Subaktion **Seriennummern erfassen**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Neue Seriennummern
|**Erlauben** = Auch Seriennummern, die im Wareneingang noch nicht erfasst wurden, können im Warenausgang eingescannt werden. +
**Nicht erlauben** = Seriennummern müssen bereits beim Wareneingang und beim Warenausgang erneut gescannt werden.

|Automatisches Speichern
|**Ja** = Nach erfolgreicher Erfassung der Seriennummern aller Artikelpositionen eines Artikels wird gespeichert und der Prozess automatisch fortgesetzt. +
**Nein:** Nach erfolgreicher Erfassung der Seriennummern aller Artikelpositionen eines Artikels muss im Prozessablauf auf **Speichern** geklickt werden, bevor der Prozess fortgesetzt wird.
|====

[#270]
== Sounds

Mit der Subaktion **Sounds** gibst du zur Bestätigung, dass eine Aktion ausgeführt wurde, ein akustisches Signal aus.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#110, Abhol-/Lieferschein>>
* <<automatisierung/prozesse/aktionen#120, Adressetikett>>
* <<automatisierung/prozesse/aktionen#130, Angebot>>
* <<automatisierung/prozesse/aktionen#150, Artikeletikett>>
* <<automatisierung/prozesse/aktionen#160, Artikelsuche>>
* <<automatisierung/prozesse/aktionen#170, Auftrag>>
* <<automatisierung/prozesse/aktionen#180, Auftragsbestätigung>>
* <<automatisierung/prozesse/aktionen#210, Dokumente>>
* <<automatisierung/prozesse/aktionen#220, E-Mail>>
* <<automatisierung/prozesse/aktionen#240, Gelangensbestätigung>>
* <<automatisierung/prozesse/aktionen#250, Gutschrift>>
* <<automatisierung/prozesse/aktionen#260, Hinweis>>
* <<automatisierung/prozesse/aktionen#270, Korrekturbeleg>>
* <<automatisierung/prozesse/aktionen#280, Lager-Pickliste>>
* <<automatisierung/prozesse/aktionen#290, Lieferschein>>
* <<automatisierung/prozesse/aktionen#300, Mahnung>>
* <<automatisierung/prozesse/aktionen#310, Packliste>>
* <<automatisierung/prozesse/aktionen#320, Pickliste>>
* <<automatisierung/prozesse/aktionen#340, Polling>>
* <<automatisierung/prozesse/aktionen#350, Rechnung>>
* <<automatisierung/prozesse/aktionen#360, Reparaturschein>>
* <<automatisierung/prozesse/aktionen#380, Retourenetikett>>
* <<automatisierung/prozesse/aktionen#390, Rücksendeschein>>
* <<automatisierung/prozesse/aktionen#400, SEPA Pain001>>
* <<automatisierung/prozesse/aktionen#410, SEPA Pain008>>
* <<automatisierung/prozesse/aktionen#430, Versand-Center>>
* <<automatisierung/prozesse/aktionen#440, Warenausgang>>

[.subhead]
Einstellungen

<<tabelle-subaktion-sounds>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-sounds]]
.Subaktion **Sounds**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Sounds
|Akustisches Signal wählen, das ausgegeben werden soll, wenn eine Aktion ausgeführt wurde.
|====

[#280]
== Speichern

Die Dokumente werden in einem Ordner gespeichert, den du beim Erstellen der Subaktion wählst. Wenn mehrere Personen den Prozess verwenden sollen, gib einen für alle verfügbaren Ordner an.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#110, Abhol-/Lieferschein>>
* <<automatisierung/prozesse/aktionen#120, Adressetikett>>
* <<automatisierung/prozesse/aktionen#130, Angebot>>
* <<automatisierung/prozesse/aktionen#150, Artikeletikett>>
* <<automatisierung/prozesse/aktionen#180, Auftragsbestätigung>>
* <<automatisierung/prozesse/aktionen#210, Dokumente>>
* <<automatisierung/prozesse/aktionen#220, E-Mail>>
* <<automatisierung/prozesse/aktionen#230, FiBu-Export>>
* <<automatisierung/prozesse/aktionen#240, Gelangensbestätigung>>
* <<automatisierung/prozesse/aktionen#250, Gutschrift>>
* <<automatisierung/prozesse/aktionen#270, Korrekturbeleg>>
* <<automatisierung/prozesse/aktionen#280, Lager-Pickliste>>
* <<automatisierung/prozesse/aktionen#290, Lieferschein>>
* <<automatisierung/prozesse/aktionen#300, Mahnung>>
* <<automatisierung/prozesse/aktionen#310, Packliste>>
* <<automatisierung/prozesse/aktionen#320, Pickliste>>
* <<automatisierung/prozesse/aktionen#340, Polling>>
* <<automatisierung/prozesse/aktionen#350, Rechnung>>
* <<automatisierung/prozesse/aktionen#360, Reparaturschein>>
* <<automatisierung/prozesse/aktionen#380, Retourenetikett>>
* <<automatisierung/prozesse/aktionen#390, Rücksendeschein>>
* <<automatisierung/prozesse/aktionen#400, SEPA Pain001>>
* <<automatisierung/prozesse/aktionen#410, SEPA Pain008>>
* <<automatisierung/prozesse/aktionen#430, Versand-Center>>

[.subhead]
Einstellungen

<<tabelle-subaktion-speichern>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-speichern]]
.Subaktion **Speichern**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Zielordner
|Auf den Stift klicken und den Pfad wählen, unter dem die Dokumente gespeichert werden sollen.

|Dateiname
|Wählen, unter welchem Namen die Dokumente gespeichert werden sollen. +
**Standard** = Dateien erhalten den Standardnamen. +
**Benutzerdefiniert** = Eigenen Namen eingeben. Verfügbare Variable: $PlentyID. +
**Unterordner erstellen** = Die Dokumente werden in einem Unterordner angelegt. Dieser Unterordner wird nach dem Muster Zielordner/Typ_Datum_Uhrzeit/ erstellt.

|Als Sammeldokument
|Häkchen setzen, um alle Dokumente in einem Dokument zusammenzufassen und nur dieses Dokument zu speichern.
|====

[#290]
== Status ändern

Mit der Subaktion **Status ändern** führst du einen Statuswechsel durch. Auswählbar sind die in Ihrem System gespeicherten Status.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#170, Auftrag>>

[.subhead]
Einstellungen

<<tabelle-subaktion-status-aendern>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-status-aendern]]
.Subaktion **Status ändern**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Status
|Status aus der Dropdown-Liste wählen, der durch die Subaktion zugewiesen werden soll.
|====

[#300]
== Versanddienstleister ändern

Mit der Subaktion **Versanddienstleister ändern** wechselst du den Versanddienstleister.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#170, Auftrag>>

[.subhead]
Einstellungen

<<tabelle-subaktion-auftrag>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-auftrag]]
.Subaktion **Auftrag**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Versanddienstleister
|Einen Versanddienstleister aus der Dropdown-Liste wählen, um diesen Versanddienstleister durch die Subaktion zuzuweisen. Zur Auswahl stehen alle im System angelegten Versanddienstleister.
|====

[#310]
== Versandpakete

Mit der Subaktion **Versandpakete** legst du Versandpakete an und bearbeitest diese Versandpakete.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#170, Auftrag>>

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[#320]
== Versandprofil ändern

Mit der Subaktion **Versandprofil ändern** wechselst du ein Versandprofil.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#170, Auftrag>>

[.subhead]
Einstellungen

<<tabelle-subaktion-versandprofil-aendern>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-versandprofil-aendern]]
.Subaktion **Versandprofil ändern**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Versandprofil
|Ein Versandprofil aus der Dropdown-Liste wählen, um dieses Versandprofil durch die Subaktion zuzuweisen. Zur Auswahl stehen alle im System angelegten Versandprofile.

|Checkbox
|Häkchen setzen, um andere Versandkosten als die Versandkosten aus dem gewählten Versandprofil zu verwenden.

|Versandkosten
|Versandkosten eingeben. Wenn in der Checkbox ein Häkchen gesetzt ist, werden die eingetragenen Versandkosten verwendet.
|====

[#330]
== Versenden

Mit der Subaktion **Versenden** versendst du die E-Mail-Vorlage, die für die Aktion <<automatisierung/prozesse/aktionen#220, E-Mail>> eingestellt wurde.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#220, E-Mail>>

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[#340]
== Zahlungsart ändern

Mit der Subaktion **Zahlungsart ändern** änderst du die Zahlungsart eines Auftrags.

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#170, Auftrag>>

[.subhead]
Einstellungen

<<tabelle-subaktion-drucken>> erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.

[[tabelle-subaktion-drucken]]
.Subaktion **Drucken**
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Zahlungsart**
|Neue Zahlungsart aus der Dropdown-Liste wählen, die den Aufträgen zugewiesen werden soll.
|====

[#350]
== Zwischenspeichern

Wenn viele Dokumente gespeichert oder gedruckt werden sollen, kann der Prozess sehr lange dauern. Dadurch kommt es zu Wartezeiten im Prozessablauf. Um Wartezeiten zu vermeiden, platziere die Subaktion **Zwischenspeichern** zum Beispiel vor einer Aktion, die mehr Zeit beansprucht als der Speichervorgang. Das Zwischenspeichern läuft dann im Hintergrund ab, während die Aktion ausgeführt wird. Danach kannst du zum Beispiel die Subaktion **Drucken** einbauen. Der Drucker greift dann auf die im Hintergrund geladenen und gespeicherten Dokumente zu und druckt diese Dokumente.

[NOTE]
.Zwischenspeichern nicht mit Aktion für den Fehlerfall kombinieren
====
Konfiguriere die Subaktion Zwischenspeichern nicht für eine Aktion, für die du auch eine Aktion für den Fehlerfall konfigurierst. Da das Zwischenspeichern asynchron läuft, behindern sich diese Vorgänge sonst gegenseitig.
====

[.subhead]
Aktionen

Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<automatisierung/prozesse/aktionen#110, Abhol-/Lieferschein>>
* <<automatisierung/prozesse/aktionen#120, Adressetikett>>
* <<automatisierung/prozesse/aktionen#130, Angebot>>
* <<automatisierung/prozesse/aktionen#150, Artikeletikett>>
* <<automatisierung/prozesse/aktionen#180, Auftragsbestätigung>>
* <<automatisierung/prozesse/aktionen#210, Dokumente>>
* <<automatisierung/prozesse/aktionen#240, Gelangensbestätigung>>
* <<automatisierung/prozesse/aktionen#250, Gutschrift>>
* <<automatisierung/prozesse/aktionen#270, Korrekturbeleg>>
* <<automatisierung/prozesse/aktionen#280, Lager-Pickliste>>
* <<automatisierung/prozesse/aktionen#290, Lieferschein>>
* <<automatisierung/prozesse/aktionen#300, Mahnung>>
* <<automatisierung/prozesse/aktionen#310, Packliste>>
* <<automatisierung/prozesse/aktionen#320, Pickliste>>
* <<automatisierung/prozesse/aktionen#350, Rechnung>>
* <<automatisierung/prozesse/aktionen#360, Reparaturschein>>
* <<automatisierung/prozesse/aktionen#380, Retourenetikett>>
* <<automatisierung/prozesse/aktionen#390, Rücksendeschein>>
* <<automatisierung/prozesse/aktionen#430, Versand-Center>>

[.subhead]
Einstellungen

Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen findest du in <<tabelle-subaktion-einstellungen-allgemein>>.
