= CustomerNote
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenformat CustomerNote, Notizen
:description: Mit dem Datenformat CustomerNote exportieren, bearbeiten und importieren Sie Notizen, die in Kundendaten erstellt wurden.
:position: 70

Mit dem Datenformat **CustomerNote** exportieren, bearbeiten und importieren Sie Notizen, die in Kundendaten erstellt wurden. Notizen befinden sich im gleichnamigen Tab in den Kundendaten. Sie erstellen und exportieren das Datenformat im Menü **Daten » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<basics/datenaustausch/export-import/daten-exportieren#, Daten exportieren>> und <<basics/datenaustausch/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **CustomerNote** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

.Datenfelder des Datenformats **CustomerNote**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**CustomerID**
|ID des Kunden
|Filter aktivieren, Operator wählen und Wert eingeben.

|**Delete**
|Notiz löschen
|

|**NoteID**
|ID der Notiz
|

|**NoteText**
|Notiz in den Kundendaten
|

|**NoteUserID**
|ID des Benutzers, der die Notiz erstellt hat
|Filter aktivieren, Operator wählen und Wert eingeben.

|**Export für Kundenklasse**
|**__Hinweis__**: reine Filtereinstellung
|Filter aktivieren und Kundenklasse aus der Dropdown-Liste wählen. Um Daten für alle Kundenklassen zu exportieren, Filter nicht aktivieren. Kundenklassen werden im Menü <<crm/kontakte-verwalten#15, System » CRM » Kundenklassen>> erstellt.
|====

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat **CustomerNote** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* **CustomerID**
* **NoteText**
* **NoteUserID**

== Übersicht der Abgleichfelder

Das folgende Datenfeld steht zum <<basics/datenaustausch/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Bei diesem Pflichtabgleichfeld muss für die **Importaktion** die Option **Abgleich** gewählt werden.

* **NoteID**
