= IncomingItems
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenformat, Importformat, Wareneingang
:description: Spezialformat IncomingItem zum Buchen von Wareneingängen
:position: 107

Mit dem Spezialformat **IncomingItems** importieren Sie Wareneingangsdaten. Dieses Datenformat steht Ihnen im Menü **Daten » Dynamischer Import** ausschließlich zum Import zur Verfügung. Ein Import von aktuellen Warenbeständen kann interessant sein, wenn die Warenbestände über eine externe Warenwirtschaft geführt werden und nur mit plentymarkets abgeglichen werden sollen.

Verwenden Sie das Datenformat **IncomingItems**, um nur bestimmte Wareneingänge und keinen kompletten Warenbestand zu importieren. Wie Sie den kompletten Warenbestand importieren, ist im Kapitel <<basics/datenaustausch/export-import/daten-importieren#120, Warenbestand importieren>> auf der Handbuchseite <<basics/datenaustausch/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **IncomingItems** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** vornehmen.

[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**AttributeValueSetID**
|ID der Artikelvariante
|

|**ItemEAN**
|EAN-Code eines Artikels
|

|**ItemID**
|Artikel-ID-Kennziffer; Zahlenwert, max. 2^31
|

|**ItemNo**
|Artikelnummer. Buchstaben und Ziffern sind möglich.
|

|**LocationID**
|ID des Lagerortes
|

|**PurchasePrice**
|Einkaufspreis (EK)
|

|**Stock**
|Importierter Bestand eines Artikels (Wareneingang)
|

|**VariationEAN**
|EAN der Artikelvariante
|

|**VariationID**
|ID der Artikelvariante
|

|**VariationNo**
|Nummer der Artikelvariante
|

|**WarehouseID**
|ID des Lagers
|Filter aktivieren und Lager aus der Dropdown-Liste wählen.
|====

__Tab. 1: Datenfelder des Datenformats **IncomingItems**__

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat **IncomingItems** vorhanden sein und ein gültiger Wert muss eingegeben sein.

Pflichtfelder für Einzelartikel:

* **Stock**
* **WarehouseID**
* sowie ein **Item**-Format

Pflichtfelder für Variantenartikel:

* **Stock**
* **WarehouseID**
* **AttributeValueSetID**
* sowie ein **Item**-Format

oder

* **Stock**
* **WarehouseID**
* sowie ein **Variation**-Format (z.B. **VariationID**)
