= Nachbestellungen importieren
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Aufträge, Best Practice, automatisiert, Nachbestellungsimport, Import Nachbestellung, Nachbestellung, Nachbestelung, Nachbestellungs-Import, Beispielexport, Praxisbeispiel
:position: 105
:url: daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-nachbestellungen
:id: KX1VNHI
:author: team-order-payment

In diesem Beitrag wird beschrieben, wie du Nachbestellungen importierst.

NOTE: Für dieses Best Practice solltest du mit der generellen Funktionsweise des Import-Tools vertraut sein. Allgemeine Infos dazu findest du auf der Handbuchseite <<daten/daten-importieren/ElasticSync#, Import-Tool nutzen>>.

Ausgangssituation
Vorbereitungen / CSV-Datei einrichten

[#importeinstellungen]
== Importeinstellungen wählen

<<daten/daten-importieren/ElasticSync#1210, Erstelle einen neuen Import>>. Wähle als *Typ* im Bereich *Grunddaten* aus der Dropdown-Liste *Aufträge* aus. Die weiteren Einstellungen können frei gewählt werden. Richte dich danach, wie du deine CSV-Datei gestaltet hast.

[#abgleich]
== Abgleich



[#zuordnung]
== Zuordnung

Aktive Zuordnungen = Pflichtfelder

Bei den aktiven Zuordnungen handelt es sich um die Pflichtfelder. Aufgelistet sind dies:

Auftrag / PlentyID
Auftrag / ID des Typs (12 = Nachbestellung)
Auftragsrelation / ID der Referenz: „Kontakt - Sender“ (Lieferant)
Auftragsrelation / ID der Referenz: „Lager - Empfänger“ (Lager)
Auftrag / Status
Optional sollte weiterhin folgendes Feld zugeordnet werden:

Auftragseigenschaft / Wert: „Externe Auftrags-ID“ („Händlerzeichen“) (wichtig für den Import von Artikelpositionen)

Import mit Artikelpositionen noch folgende Felder:

Auftragsposition / Währung
Auftragsposition / Menge
Auftragsposition / Typ
Hierbei können zusätzlich noch weitere Felder (siehe Zuordnung oben) zugeordnet werden:

Auftragsposition / Name
Auftragspositionseigenschaften / Wert: „Externe Artikel ID“ (Lieferanten-Artikelnummer)
Auftragsposition / Bruttopreis (Einkaufspreis)

Hinweis: Sollte die Varianten-ID nicht abgeglichen werden, dann handelt es sich beim Preis ebenfalls um ein Pflichtfeld
(Screenshot)


== Hat es funktioniert?

- Wie kann eine Überprüfung am besten stattfinden? Im System sollten die neuen Nachbestellungen sein. Menüpfad, checken. Wenn Nachbestellungen da, dann sollten auch die Daten da drin stimmen. Lieferant, Austragspositionen, etc.
