= billiger.de Asien
:lang: de
include::{includedir}/_header.adoc[]
:keywords: billiger.de, Marktplatz, Asien
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz billiger.de Asien in Ihrem plentymarkets System ein.
:position: 25

Auf dieser Handbuchseite finden Sie Informationen zur Einrichtung von billiger.de Asien in plentymarkets. Sie erfahren, wie Sie die Schnittstelle einrichten, Ihre Artikel zu billiger.de exportieren und Verkaufspreise festlegen.

[#100]
== Bei billiger.de registrieren

Bevor Sie billiger.de Asien in plentymarkets einrichten, müssen Sie sich bei link:https://www.billiger.de/application/register1.html[**billiger.de**^] registrieren.

[#200]
== billiger.de Asien in plentymarkets einrichten

Nehmen Sie die folgenden Einstellungen in plentymarkets vor, um die Schnittstelle zu billiger.de Asien einzurichten.

[.instruction]
billiger.de Asien einrichten:

. Öffnen Sie das Menü **System » Märkte » billiger.de Asien » Einstellungen**.
. Aktivieren Sie den automatischen Datenaustausch.
. Geben Sie den Benutzernamen ein, wie von billiger.de erhalten.
. Geben Sie das Passwort ein, wie von billiger.de erhalten.
. **Speichern** Sie die Einstellungen.

Die Anbindung von billiger.de Asien stellt folgende automatisierte Prozesse bereit:

* stündlicher Auftragsabgleich

Die Aufträge von Billiger.de Asien werden als bezahlt importiert.

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit billiger.de Asien verknüpfen können, muss im Menü **System » Aufträge » Auftragsherkunft** die Auftragsherkunft billiger.de Asien aktiviert werden.

[.instruction]
Auftragsherkunft für billiger.de Asien aktivieren:

. Öffnen Sie das Menü **System » Aufträge » Auftragsherkunft**.
. Setzen Sie bei **billiger.de Asien** ein Häkchen.
. **Speichern** Sie die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf billiger.de Asien verkaufen möchten, müssen über das Merkmal **Delivery to Asia** freigeschalten und im Menü <<artikel/artikel-verwalten#, **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID**>> im Tab **Verfügbarkeit** aktiviert werden. Legen Sie zunächst das Merkmal an und verknüpfen Sie das Merkmal mit dem Artikel.

[.instruction]
Merkmal Delivery to Asia anlegen:

.  Öffnen Sie das Menü <<artikel/artikel-verwalten#480, **System » Artikel » Merkmale » Tab: Neues Merkmal**>>.
.  Geben Sie den **Namen (Intern)** ein.
. Wählen Sie als Merkmaltyp **Kein** aus der Dropdown-Liste.
.  Wählen Sie bei **Billiger.de Asien** das Merkmal **Delivery to Asia**.
.  Klicken Sie auf **Speichern**.

Im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale** verknüpfen Sie anschließend das Merkmal mit dem Artikel. Stellen Sie als nächstes die Artikelverfügbarkeit ein, wie im Folgenden beschrieben.

[.instruction]
Artikelverfügbarkeit für billiger.de einstellen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen**.
. Aktivieren Sie die Hauptvariante im Bereich **Verfügbarkeit**.
. Wechseln Sie in das Tab **Verfügbarkeit**.
. Klicken Sie im Bereich **Märkte** in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktivieren Sie die Option **billiger.de**.
. Aktivieren Sie die Option **Web-API**.
. Klicken Sie auf **Hinzufügen**. +
→ Der Marktplatz wird hinzugefügt.
. **Speichern** Sie die Einstellungen.

Die Verfügbarkeit für Varianten kann im Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit** individuell angepasst werden.

[#400]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft billiger.de einen Verkaufspreis festzulegen. Dieser Preis wird auf billiger.de angezeigt.

[.instruction]
Verkaufspreis für billiger.de festlegen:

. Öffnen Sie das Menü **System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen**.
. Setzen Sie ein Häkchen bei der Herkunft **billiger.de**.
. **Speichern** Sie die Einstellungen.

[#500]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID**>> im Tab **Verfügbarkeit** fügen Sie, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen**.
.  Wechseln Sie in das Tab **Verfügbarkeit**.
.  Klicken Sie im Bereich **SKU** auf **Hinzufügen**. +
→ Das Bearbeitungsfenster **Neue SKU** wird angezeigt.
.  Wählen Sie die Herkunft **billiger.de Asien**.
.  Geben Sie die SKU ein.
.  Klicken Sie auf **Hinzufügen**. +
→ Die SKU wird gespeichert und angezeigt.

[#600]
== Artikelexport einrichten

In diesem Kapitel wird beschrieben, wie Sie Ihre Artikel zu  billiger.de Asien übertragen. Artikel werden anschließend über den elastischen Export exportiert.

[.instruction]
Artikelexport einrichten:

. Öffnen Sie das Menü **Daten » Elastischer Export**.
. Klicken Sie auf **Neuer Export**.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1
. Nehmen Sie weitere Einstellungen für Artikelfilter und Formateinstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 5 auf der Handbuchseite <<basics/datenaustausch/export-import/daten-exportieren#60, **Daten exportieren**>>
. **Speichern** Sie die Einstellungen. +
→ Eine ID für das Exportformat wird vergeben und das Exportformat erscheint in der Übersicht **Exporte**.

.Einstellungen für Artikelexport
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

|**Name**
|Name eingeben. Unter diesem Namen erscheint das Exportformat in der Übersicht im Tab **Exporte**.

|**Typ**
|Typ aus der Dropdown-Liste wählen. Aktuell ist nur die Auswahl **Artikel** verfügbar. Weitere Auswahlmöglichkeiten folgen.

|**Format**
|Format **BilligerDE** aus der Dropdown-Liste wählen.

|**Limit**
|Zahl eingeben. Wenn mehr als 10000 Datensätze an billiger.de übertragen werden sollen, wird die Ausgabedatei für 24 Stunden nicht noch einmal neu generiert, um Ressourcen zu sparen.

|**Bereitstellung**
|**URL** wählen.

|**Token, +
URL**
|Wenn unter **Bereitstellung** die Option **URL** gewählt wurde, auf **Token generieren** klicken. Der Token wird dann automatisch eingetragen. Die URL wird automatisch eingetragen, wenn unter **Token** der Token generiert wurde. Diese URL an billiger.de übergeben, damit die Artikel exportiert werden.
|====

[IMPORTANT]
.Exportinformationen
====
Wenn Sie eine oder mehrere Einstellungen ändern, müssen Sie den neuen Link an billiger.de übergeben.

Pro Export werden maximal 4000 Artikel exportiert. Wenn Sie mehr Artikel exportieren, wird automatisch ein zweiter Export ausgeführt. Um den zweiten Export anzuzeigen, setzen Sie den Parameter **&amp;Page** = im Export-Link auf **2**.

Technische Daten werden in der letzten Spalte der Exportdatei an billiger.de übergeben.
====

[#700]
== Auftragsbestätigungen automatisch senden

Richten Sie eine **<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>** ein, um nach Eingang eines Auftrags automatisch eine Auftragsbestätigung an billiger.de zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **System » Aufträge » Ereignisse**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 2.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 2 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Auftragsbestätigungen an billiger.de Asien
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|**Ereignis**
|**Auftragsanlage: Neuer Auftrag**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|**billiger.de Asien**

|**Aktion**
|**Auftrag &gt; Auftragsbestätigung an billiger.de senden Asien**
|
|====

[#800]
== Versandbestätigungen automatisch senden

Richten Sie eine **<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>** ein, um automatisch eine Versandbestätigung an billiger.de zu senden, nachdem ein Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **System » Aufträge » Ereignisse**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 3.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 3 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
Einstellung.Ereignisaktion zum automatischen Senden von Versandbestätigungen an billiger.de Asien
[cols="1,3"]
|====
| Option | Auswahl

|**Ereignis**
|**Auftragsänderung: Warenausgang gebucht**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|**billiger.de Asien**

|**Aktion**
|**Versand &gt; Versandbestätigung an billieger.de senden Asien**
|
|====

[#1000]
== API-Log abrufen

Im Menü **Daten » API-Log » Tab: API-Log** finden Sie eine Historie über Vorgänge, die über die billiger.de-Schnittstelle ausgeführt wurden. Das Format **billiger.de Asia** steht Ihnen für billiger.de Asien zur Verfügung.

[.instruction]
API-Log abrufen:

.  Öffnen Sie das Menü **Daten » API-Log**.
.  Wählen Sie das Format **billiger.de Asia** aus der Dropdown-Liste **Vorgang**.
.  Wählen Sie ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
.  Wählen Sie die Anzahl der Ergebnisse pro Seite.
.  Klicken Sie auf **Suchen**, um die Ergebnisse anzuzeigen.
