= grosshandel.eu
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: grosshandel.eu, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz grosshandel.eu in deinem plentymarkets System ein.
:position: 90
:url: maerkte/grosshandel

link:http://www.grosshandel.eu/[grosshandel.eu^]{nbsp}icon:external-link[] ist ein reines B2B-Portal, d.h. sowohl Anbieter als auch Nachfrager müssen im Besitz eines gültigen Gewerbenachweises sein. Auf diesem Marktplatz kannst du reguläre Ware und Markenartikel kaufen und verkaufen (Quelle: grosshandel.eu).

[#100]
== Bei grosshandel.eu registrieren

Um dein plentymarkets System für grosshandel.eu einzustellen, link:http://www.grosshandel.eu/registrierung-verkaeufer.php[registriere^]{nbsp}icon:external-link[] dich zunächst im Händlerportal von grosshandel.eu.

[#200]
== Benutzerkonto erstellen

Dein plentymarkets System wird über die SOAP-API mit grosshandel.eu verbunden. Für den Zugriff benötigt der Marktplatz ein eigenes Benutzerkonto mit Zugriffsrechten auf die API in deinem System. Erstelle im Menü <<business-entscheidungen/benutzerkonten-zugaenge#10, Einrichtung » Einstellungen » Benutzer » Konten>> ein neues Benutzerkonto der Benutzerklasse *API* für grosshandel.eu. Aktiviere außerdem den Call *GetCategoryMappingForMarket*. Dieser Call sorgt dafür, dass der Marktplatz später deine Kategorieverknüpfungen auslesen kann.

[.instruction]
Benutzerkonto für grosshandel.eu erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neuen Benutzer erstellen* wird geöffnet.
. Gib die Daten ein.
. Wähle als Benutzerklasse *API*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Benutzer wird erstellt.
. Wähle den Benutzer aus der Liste. +
→ Das Bearbeitungsfenster wird geöffnet.
. Öffne das Tab *Berechtigung » API*.
. Klappe den Bereich *Item* auf.
. Aktiviere den Call *GetCategoryMappingForMarket*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Weitere Informationen findest du auf der Handbuchseite <<business-entscheidungen/benutzerkonten-zugaenge#, Benutzer verwalten>>.

[#300]
== Daten bereitstellen

Für die Anbindung an dein plentymarkets System benötigt grosshandel.eu die folgenden Daten:

* URL der SOAP-API WSDL.  +
→ Du findest die URL im Menü <<basics/datenaustausch/api-daten#, Einrichtung » Einstellungen » API » Daten>> unter *SOAP WSDL*.
* Benutzername und Passwort für das von dir erstellte Benutzerkonto für grosshandel.eu
* Deine Login-Daten für das Händlerportal von grosshandel.eu

[#350]
== Auftragsherkunft aktivieren

:market: grosshandel.eu
:referrer: grosshandel.eu
:referrer-option: pass:quotes[Option *grosshandel.eu*]

include::_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#400]
== Variantenverfügbarkeit einstellen

Artikel, die du auf grosshandel.eu verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[TIP]
.Alle Varianten eines Artikels auf grosshandel.eu verkaufen
====
Wenn du alle Varianten eines Artikels auf grosshandel.eu verkaufen möchtest, nimm die unten beschriebenen Einstellungen an der Hauptvariante vor. Die Einstellungen werden dann an alle Varianten des Artikels vererbt.
====


[.instruction]
Variantenverfügbarkeit für grosshandel.eu einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Öffne die Variante, die du auf grosshandel.eu verkaufen möchtest.
. Aktiviere im Bereich *Verfügbarkeit* die Option *Aktiv*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *grosshandel.eu*.
. Aktiviere die Option *Web-API*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#450]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *grosshandel.eu*.
. Gib die SKU ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die SKU wird gespeichert und angezeigt.

[#500]
== Verkaufspreis festlegen

:referrer-price: grosshandel.eu

include::_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#600]
== Kategorien verknüpfen

Verknüpfe deine Webshop-Kategorien mit den Kategorien von grosshandel.eu, damit deine Artikel in diesen Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » grosshandel.eu*.
. Klappe die Kategorie auf, die du mit einer grosshandel.eu-Kategorie verknüpfen möchten.
. Wähle eine grosshandel.eu-Hauptkategorie aus der Dropdown-Liste. +
→ Ein Fenster mit Unterkategorien wird geöffnet.
. Wähle aus den weiteren Unterkategorien die passende grosshandel.eu-Kategorie aus. +
→ Wenn die tiefste Kategorieebene erreicht ist, erscheint der Kategoriepfad im Textfeld *Kategorie*.
. Klicke auf *Übernehmen*. +
→ Das Kategoriefenster wird geschlossen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[IMPORTANT]
.Verknüpfung bis in die unterste Kategorieebene
====
Verknüpfe deine Kategorien immer bis in die unterste Ebene. Andernfalls ist eine Verknüpfung nicht möglich.
====

[#700]
== Unterkategorien mehrfach verknüpfen

Mit der Funktion *Auswahl für Unterkategorien übernehmen* hast du die Möglichkeit, für alle Unterkategorien einer Kategorie denselben grosshandel.eu-Kategoriepfad zu übernehmen. Denselben grosshandel.eu-Kategoriepfad für alle Unterkategorien einer Kategorie zu übernehmen ist sinnvoll, wenn die Unterkategorien die gleiche Verknüpfung erhalten sollen. Die einzelnen Unterkategorien kannst du bei Bedarf manuell über die Dropdown-Liste ändern.

[.instruction]
Unterkategorien mehrfach verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » grosshandel.eu*.
. Klappe die Kategorie auf, für die du eine Kategorieverknüpfung erstellen möchtest.
. Wähle eine grosshandel.eu-Hauptkategorie aus der Dropdown-Liste in der Zeile *Auswahl für Unterkategorien übernehmen*. +
→ Ein Fenster mit Unterkategorien wird geöffnet.
. Wähle aus den weiteren Unterkategorien den passenden Kategoriepfad aus. +
→ Wenn die tiefste Kategorieebene erreicht ist, erscheint der Kategoriepfad im Textfeld *Kategorie*.
. Klicke auf *Übernehmen*. +
→ Das Kategoriefenster wird geschlossen.
. Klicke auf *Alle auswählen* in der Zeile *Auswahl für Unterkategorien übernehmen*.
. Klicke auf *Reload*. +
→ Der Kategoriepfad wird für alle Unterkategorien übernommen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
