= grosshandel.eu
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: grosshandel.eu, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz grosshandel.eu in deinem plentymarkets System ein.
:position: 90
:url: maerkte/grosshandel

link:http://www.grosshandel.eu/[grosshandel.eu^]{nbsp}icon:external-link[] ist ein reines B2B-Portal, d.h. sowohl Anbieter:in als auch Nachfrager:in müssen im Besitz eines gültigen Gewerbenachweises sein. Auf diesem Marktplatz kannst du reguläre Ware und Markenartikel kaufen und verkaufen (Quelle: grosshandel.eu).

[#100]
== Bei grosshandel.eu registrieren

Um dein plentymarkets System für grosshandel.eu einzustellen, link:http://www.grosshandel.eu/registrierung-verkaeufer.php[registriere^]{nbsp}icon:external-link[] dich zunächst im Händlerportal von grosshandel.eu.

[#200]
== Benutzerkonto erstellen

Dein plentymarkets System wird über die SOAP-API mit grosshandel.eu verbunden. Für den Zugriff benötigt der Marktplatz ein eigenes Benutzerkonto mit Zugriffsrechten auf die API in deinem System. Erstelle im Menü <<business-entscheidungen/benutzerkonten-zugaenge#10, Einrichtung » Einstellungen » Benutzer » Konten>> ein neues Benutzerkonto der Benutzerklasse *API* für grosshandel.eu. Aktiviere außerdem den Call *GetCategoryMappingForMarket*. Dieser Call sorgt dafür, dass der Marktplatz später deine Kategorieverknüpfungen auslesen kann.

[.instruction]
Benutzerkonto für grosshandel.eu erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neuen Benutzer erstellen* wird geöffnet.
. Gib die Daten ein.
. Wähle als Benutzerklasse *API*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Konto wird erstellt.
. Wähle das Konto aus der Liste. +
→ Das Bearbeitungsfenster wird geöffnet.
. Öffne das Tab *Berechtigung » API*.
. Klappe den Bereich *Item* auf.
. Aktiviere den Call *GetCategoryMappingForMarket*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Weitere Informationen findest du auf der Handbuchseite <<business-entscheidungen/benutzerkonten-zugaenge#, Benutzer verwalten>>.

[#300]
== Daten bereitstellen

Für die Anbindung an dein plentymarkets System benötigt grosshandel.eu die folgenden Daten:

* URL der SOAP-API WSDL.  +
*_Tipp:_* Du findest die URL im Menü <<basics/datenaustausch/api-daten#, Einrichtung » Einstellungen » API » Daten>> unter *SOAP WSDL*.
* Benutzername und Passwort für das von dir erstellte Benutzerkonto für grosshandel.eu
* Deine Zugangsdaten für das Händlerportal von grosshandel.eu

[#350]
== Auftragsherkunft aktivieren

:market: grosshandel.eu
:referrer: grosshandel.eu
:referrer-option: pass:quotes[Option *grosshandel.eu*]

include::_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#400]
== Variantenverfügbarkeit einstellen

:market-availability: grosshandel.eu
:option-availability: grosshandel.eu
:web-api:

include::_textblocks/instructions/variantenverfuegbarkeit.adoc[]

// Web-API erforderlich!

[#450]
== _Optional:_ SKU speichern

:referrer-sku: grosshandel.eu

include::_textblocks/instructions/sku-manuell.adoc[]

// Marktplatzkonto nicht erforderlich!

[#500]
== Verkaufspreis festlegen

:referrer-price: grosshandel.eu

include::_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#600]
== Kategorien verknüpfen

Verknüpfe deine plentymarkets Kategorien mit den Kategorien von grosshandel.eu, damit deine Artikel in diesen Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » grosshandel.eu*.
. Klappe die Kategorie auf, die du mit einer grosshandel.eu-Kategorie verknüpfen möchtest.
. Wähle eine grosshandel.eu-Hauptkategorie aus der Dropdown-Liste. +
→ Ein Fenster mit Unterkategorien wird geöffnet.
. Wähle aus den weiteren Unterkategorien die passende grosshandel.eu-Kategorie aus. +
→ Wenn die tiefste Kategorieebene erreicht ist, wird der Kategoriepfad im Textfeld *Kategorie* angezeigt.
. Klicke auf *Übernehmen*. +
→ Das Kategoriefenster wird geschlossen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[IMPORTANT]
.Verknüpfung bis in die unterste Kategorieebene
====
Verknüpfe deine Kategorien immer bis in die unterste Ebene. Andernfalls ist eine Verknüpfung nicht möglich.
====

[#700]
== Unterkategorien mehrfach verknüpfen

Mit der Funktion *Auswahl für Unterkategorien übernehmen* hast du die Möglichkeit, für alle Unterkategorien einer Kategorie denselben grosshandel.eu-Kategoriepfad zu übernehmen. Denselben grosshandel.eu-Kategoriepfad für alle Unterkategorien einer Kategorie zu übernehmen ist sinnvoll, wenn die Unterkategorien die gleiche Verknüpfung erhalten sollen. Die einzelnen Unterkategorien kannst du bei Bedarf manuell über die Dropdown-Liste ändern.

[.instruction]
Unterkategorien mehrfach verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » grosshandel.eu*.
. Klappe die Kategorie auf, für die du eine Kategorieverknüpfung erstellen möchtest.
. Wähle eine grosshandel.eu-Hauptkategorie aus der Dropdown-Liste in der Zeile *Auswahl für Unterkategorien übernehmen*. +
→ Ein Fenster mit Unterkategorien wird geöffnet.
. Wähle aus den weiteren Unterkategorien den passenden Kategoriepfad aus. +
→ Wenn die tiefste Kategorieebene erreicht ist, wird der Kategoriepfad im Textfeld *Kategorie* angezeigt.
. Klicke auf *Übernehmen*. +
→ Das Kategoriefenster wird geschlossen.
. Klicke auf *Alle auswählen* in der Zeile *Auswahl für Unterkategorien übernehmen*.
. Klicke auf *Reload*. +
→ Der Kategoriepfad wird für alle Unterkategorien übernommen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
