= La Redoute
:lang: de
include::{includedir}/_header.adoc[]
:keywords: La Redoute, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz La Redoute in Ihrem plentymarkets System ein.
:position: 170

plentymarkets ermöglicht dir die Anbindung an La Redoute, Frankreichs Marktführer im Versandhandel. Erfahre, wie du die Schnittstelle zu La Redoute einrichten und welche Bedingungen du als Online-Händler erfüllen musst, um deine Artikel auf La Redoute anzubieten.

[#100]
== Bei La Redoute registrieren

La Redoute stellt Bedingungen an jeden Online-Händler, der über den Marktplatz verkaufen will:

. Der Artikelkatalog muss komplett auf Französisch vorliegen.
. Du musst Kundenanfragen per E-Mail auf Französisch beantworten können.
. Außerdem musst du selbstverständlich nach Frankreich versenden wollen und können.

Um dein plentymarkets System für den Marktplatz La Redoute einzurichten, musst du dich zuerst bei La Redoute registrieren. Die Registrierung erfolgt in zwei Schritten. Zunächst nimmst du Kontakt mit dem La Redoute Business Development Team auf:

[[ansprechpartner-laredoute]]
.Ansprechpartner bei La Redoute
[cols="1,3"]
|====
|Ansprechpartner |E-Mail-Adresse

|*Frédéric Maus* +
Head of Business development
|link:mailto:fmaus@redoute.fr[fmaus@redoute.fr]

|*Joseph Farhat* +
Manager Business development - Fashion &amp; accessories
|link:mailto:jfarhat@redoute.fr[jfarhat@redoute.fr]

|*Carlos Cantoni* +
Manager Business development - Home &amp;
electronics
|link:mailto:ccantoni@redoute.fr[ccantoni@redoute.fr]
|====

Anschließend erhältst du von La Redoute eine Excel-Datei, die du mit Informationen über deine Firma befüllst und zurücksendest. Mit der Datei sendest du folgende Unterlagen:

* Eine Kopie deines Handelsregisterauszugs
* Eine Erklärung deiner Bank mit deinen Kontoinformationen (mit Swift und IBAN)

*_Oder:_* Fülle auf der französischen Seite von La Redoute das link:http://www.laredoute.fr/espace-devenir-vendeur-marketplace.aspx[Kontaktformular^] aus. Nachdem du alle nötigen Informationen an La Redoute geschickt hast, erhältst du eine E-Mail von La Redoute, die die CallerID und den CatalogSupplierName beinhaltet. Diese IDs kannst du jetzt in dein plentymarkets System eingeben.

[#200]
== La Redoute in plentymarkets einrichten

Nimm folgende Grundeinstellungen für die Anbindung von La Redoute an dein plentymarkets System vor.

[.instruction]
La Redoute in plentymarkets einrichten:

. Öffne das Menü *System » Systemeinstellungen » Märkte » La Redoute » Einstellungen*.
. Nimm die Einstellungen gemäß <<grundeinstellungen-laredoute>> vor.
. *Speichere* die Einstellungen.

[[grundeinstellungen-laredoute]]
.Grundeinstellungen des Marktplatzes La Redoute
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Schnittstellenmodus*
|Schnittstellenmodus wählen. +
*Testmodus EIN* = Wählen, wenn Einstellungen und Vorbereitungen an Schnittstelle und Artikeln getroffen werden. +
*Aktivmodus EIN* = Wählen, nachdem La Redoute bestätigt hat, dass alle Tests abgeschlossen wurden.

2+|Vertriebspartner-Information

|*VendorId*
|Von La Redoute erhaltene ID eingeben.

2+|Artikeleinstellungen

|*Artikelname*
|Wählen, welches Feld an La Redoute als Artikelname übertragen werden soll. Der Name muss in französischer Sprache sein, sonst findet kein Artikelexport statt.

|*Artikelvorschautext*
|Wählen, welches Feld an La Redoute als Artikelvorschautext übertragen werden soll. Der Artikelvorschautext muss in französischer Sprache sein, sonst findet kein Artikelexport statt.

|*Artikelbeschreibung*
|Wählen, welches Feld an La Redoute als Artikelbeschreibung übertragen werden soll. Die Artikelbeschreibung muss in französischer Sprache sein, sonst findet kein Artikelexport statt.

|*Technische Daten*
|Wählen, ob technische Daten übertragen werden sollen oder nicht. Die technischen Daten müssen in französischer Sprache sein, sonst findet kein Artikelexport statt.

|*Artikel-EAN*
|EAN wählen, die als Artikel-EAN übertragen wird.

|*Varianten-EAN*
|EAN wählen, die als Varianten-EAN übertragen wird.

|*Versandvorbereitung*
|Dauer in Tagen eingeben, die du zum Verpacken und Übergeben der Bestellung an den Versanddienstleister benötigst.

|*Minimum Lieferverzugsaufschlag*
|Dauer in Tagen eingeben. Die Dauer wird zu der normalen Mindestlieferzeit deiner Artikel hinzuaddiert.

|*Maximum Lieferverzugsaufschlag*
|Dauer in Tagen eingeben. Die Dauer wird zu der normalen maximalen Lieferzeit deiner Artikel hinzuaddiert.

|*Versandkosten überschreiben*
|Die hier eingegebenen Versandkosten werden anstatt der am Artikel hinterlegten Versandkosten an La Redoute übermittelt.

2+|Bestelleinstellungen

|*Temporäre Kunden-ID*
|Einen Kunden für La Redoute erstellen und dessen ID hier eingeben (siehe Kapitel 11).

|*Zahlungseingang buchen*
|Wählen, ob Aufträge von La Redoute als *bezahlt* oder *offen* importiert werden sollen, da die Kunden an La Redoute überweisen und La Redoute dir das Geld erst danach auszahlt.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* stündlicher Auftragsimport
* täglicher Artikelexport
* zweistündlicher Bestandsabgleich

[#250]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit La Redoute verknüpfen kannst, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft La Redoute aktiviert werden.

[.instruction]
Auftragsherkunft für La Redoute aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setze bei *La Redoute* ein Häkchen.
. *Speichere* die Einstellungen.

[#300]
== Artikelinformationen übersetzen

Da La Redoute ein französischer Marktplatz ist, muss ein <<artikel/artikel-verwalten#20, Artikel>>, der dort verkauft werden soll, auf Französisch erstellt sein. Eine weitere Voraussetzung für ein Einstellen auf La Redoute ist eine Artikelbeschreibung auf Französisch. Des Weiteren müssen alle Attribute und Merkmale, die mit La Redoute verknüpft werden, ebenfalls auf Französisch vorliegen. Der Artikel muss außerdem über eine EAN und Artikelbilder verfügen.

[.instruction]
Französische Sprachvariante eines bestehenden Artikels erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Texte*.
. Wähle aus der Dropdown-Liste *Öffne Sprache* die Einstellung *fr*.
. Gib im Feld *Name 1* einen französischen Namen für den Artikel ein.
. Gib weitere Texte (Beschreibung, Technische Daten etc.) ein. +
→ Die Beschreibung ist Pflicht für La Redoute.
. *Speichere* die Einstellungen.

[#400]
== Artikelverfügbarkeit einstellen

Artikel, die du auf La Redoute verkaufen möchtest, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für La Redoute einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *La Redoute*.
. Aktiviere die Option *Web-API*.
. Klicke auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* die Einstellungen. +
→ Der Artikel ist auf La Redoute verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

[#450]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *La Redoute*.
. Gib die SKU ein.
. Klicke auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#500]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft La Redoute einen Verkaufspreis festzulegen. Dieser Preis wird auf La Redoute angezeigt.

[.instruction]
Verkaufspreis für La Redoute festlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *La Redoute*.
. *Speichere* die Einstellungen.

[#600]
== Merkmale verknüpfen

Verknüpfe deine <<artikel/artikel-verwalten#480, *Merkmale*>> mit den La Redoute-Merkmalen. Beachte, dass deine Merkmale hierfür auf Französisch erstellt sein müssen. Du erhältst von La Redoute eine XLS-Datei, die die Merkmale enthält. Aus dieser Datei erstellst du für den Merkmalimport eine CSV-Datei.

[IMPORTANT]
.Notwendige Verknüpfungen vornehmen
====
Damit deine Artikel auf dem Marktplatz La Redoute zum Verkauf angezeigt werden, musst du verschiedene Verknüpfungen erstellen. Die Verknüpfung von *Merkmalen*, *Kategorien*, *Attributen und -werten* sowie *Herstellern* ist Pflicht.
====

[.instruction]
Merkmale verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Märkte » La Redoute » Import*.
. Klicke auf *Datei auswählen*.
. Wähle die CSV-Datei mit den Merkmalen.
. Wähle das Feldtrennzeichen.
. *Speichere* die Einstellungen. +
→ Die Datei wird hochgeladen.
. Wechsele in das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Klappe ein Merkmal auf.
. Wähle aus der Dropdown-Liste *Sprache* für Französisch *fr*.
. Gib in das Feld *Name* den französischen Namen des Merkmals ein.
. Wähle aus der Dropdown-Liste im Feld *La Redoute-Merkmal* das La Redoute-Merkmal.
. *Speichere* die Einstellungen.

[#700]
== Kategorien verknüpfen

Damit deine Artikel in den richtigen Kategorien bei La Redoute angezeigt werden, musst du Kategorieverknüpfungen erstellen.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Märkte » La Redoute » Kategorieverknüpfung*.
. Gib in der Spalte *La Redoute-Kategorie-ID* auf der rechten Seite die ID der Kategorie ein, die am besten zu deiner Webshop-Kategorie passt. +
→ Die La Redoute-Kategorie-ID entnimmst du den Kategorie-Dateien, die du von La Redoute erhalten hast.
. *Speichere* die Einstellungen.

[#800]
== Attribute und Attributwerte verknüpfen

Auch <<artikel/artikel-verwalten#390, *Attribute*>> müssen verknüpft werden, bevor deine Artikel zu La Redoute übertragen werden können. Beachte, dass nur die Artikel auf La Redoute angezeigt werden, von denen sämtliche Attribute verknüpft sind.

[.instruction]
Attribute und Attributwerte verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Attribute*. +
→ Die Übersicht aller in deinem Katalog verwendeten Attribute wird geöffnet.
. Klappe ein Attribut auf.
. Wechsele in das Tab *Marktplatzvariation*.
. Wähle die Option *La Redoute* aus der Dropdown-Liste *Marktplatz*. +
→ Eine Dropdown-Liste wird im Bereich *Einstellungen* geöffnet.
. Wähle das passende La Redoute-Attribut aus der Dropdown-Liste.
. Wähle im Bereich *Marktplatzvariation* für deine Attributwerte passende La Redoute-Attributwerte.
. *Speichere* die Einstellungen.
. Wiederhole den Vorgang für alle weiteren Attribute.

[#900]
== Hersteller verknüpfen

Zuletzt verknüpfst du noch deine <<artikel/artikel-verwalten#560, Hersteller>>. Dazu erhältst du von La Redoute eine Datei mit Hersteller-IDs.

[.instruction]
Hersteller verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Hersteller*.
. Öffne einen Hersteller.
. Gib im Feld *La Redoute-ID* die ID ein. +
→ Die La Redoute-Hersteller-ID entnimmst du der Datei, die du von La Redoute erhalten hast.

[#1000]
== Zahlungsart aktivieren

Die Zahlungsart *La Redoute Payment* ist für Aufträge, die über den französischen Marktplatz link:http://www.laredoute.com/[La Redoute^] in dein plentymarkets System kommen.

[.instruction]
Zahlungsart La Redoute Payment aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
. Klicke auf *La Redoute Payment*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-zahlungsart-laredoute>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* die Einstellungen.

[[einstellungen-zahlungsart-laredoute]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn Käufer*innen im Webshop die Sprache wählen.

|*Name*
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
|Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in deinem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistik>>. Ein Beispiel für pauschale und prozentuale Kosten findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Grundeinstellungen>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » Systemeinstellungen » CRM » Kundenklassen* aktivierst oder deaktivierst du *erlaubte Zahlungsarten*. +
Weitere Informationen findest du im Kapitel *<<payment/zahlungsarten-verwalten#30, Zahlungsarten und Kundenklassen>>*.
====

Weitere Informationen findest du auf der Handbuchseite *<<payment/zahlungsarten-verwalten#, Zahlungsarten>>*.

[#1100]
== Temporären Kunden erstellen

Die Aufträge kommen zunächst ohne Kundendaten ins System. Nachdem der Auftrag durch dein plentymarkets System bei La Redoute bestätigt wurde, werden die tatsächlichen Kundendaten übermittelt. Deshalb musst du für La Redoute einen Kunden in deinem System erstellen und die ID dieses Kunden im Feld *Temporäre Kunden-ID* eingeben.

[.instruction]
Neuen Kunden erstellen:

. Öffne das Menü *CRM » Kunden bearbeiten*.
. Klicke auf *Neu*.
. Gib mindestens einen Namen für den temporären Kunden ein.
. *Speichere* die Einstellungen.
. Klicke auf *Suchen*.
. Suche den erstellten Kunden.
. Notiere die *Kunden-ID*.
. Wechsele in das Menü *System » Systemeinstellungen » Märkte » La Redoute » Einstellungen*.
. Gib im Feld *Temporäre Kunden-ID* die ID des La Redoute-Kunden ein.
. *Speichere* die Einstellungen.

[#1200]
== Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an La Redoute zu senden. Die Versandbestätigung wird automatisch an La Redoute gesendet, wenn der Auftrag in den Status *[7] Warenausgang gebucht* wechselt. Käufer*innen werden automatisch durch La Redoute über den Versand benachrichtigt.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<automatische-versandbestätigungen-laredoute>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<automatische-versandbestätigungen-laredoute>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[automatische-versandbestätigungen-laredoute]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an La Redoute
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung &gt; Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*La Redoute*

|*Aktion*
|*Versand &gt; Versandbestätigung an La Redoute senden*
|
|====

[#1300]
== Retouren automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Retouren automatisch an La Redoute zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<automatische-retouren-laredoute>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<automatische-retouren-laredoute>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[automatische-retouren-laredoute]]
.Ereignisaktion zum automatischen Senden von Retouren an La Redoute
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage &gt; Neue Retoure (durch Kunde)*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*La Redoute*

|*Aktion*
|*Retoure &gt; Retoure an La Redoute senden*
|
|====

[#1400]
== Stornierungen melden

Eine Stornierung im eigentlichen Sinne kann nicht an La Redoute gesendet werden. Wenn du einen Auftrag stornieren möchtest, weil du z.B. den Artikel aus dem Sortiment genommen hast, dann musst du eine Retoure erstellen.

Neue Aufträge von La Redoute werden von plentymarkets automatisch akzeptiert, damit die Daten überhaupt in dein plentymarkets System importiert werden. Das Akzeptieren des Auftrags erlaubt dir nicht, den Auftrag hinterher zu stornieren. Buche deshalb zunächst den Warenausgang und erstelle sofort im Anschluss eine Retoure.

[TIP]
.Tipp: E-Mail an Kunden
====
Sende bei einer Stornierung deinerseits zusätzlich eine E-Mail an den Kunden, um den Kunden darüber zu informieren, dass der Artikel z.B. nicht mehr in deinem Sortiment enthalten ist.
====

[#1500]
== Artikel löschen

Um <<artikel/artikel-verwalten#, Artikel>>, die bei La Redoute angeboten werden, endgültig aus deinem plentymarkets System zu entfernen, musst du zunächst diese Artikel aus dem La Redoute-Katalog entfernen.

[.instruction]
Artikel aus dem La Redoute-Katalog entfernen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel, den du löschen möchtest.
. Wechsele in das Tab *Verfügbar*.
. Deaktiviere die Option *La Redoute*.
. *Speichere* die Einstellungen. +
→ Nach diesem Vorgang musst du 24 Stunden warten, bis der Artikel aus dem La Redoute-Katalog entfernt wird.

[WARNING]
.Artikel nie ohne Wartezeit löschen
====
Lösche einen Artikel nicht vor Ablauf der 24 Stunden und auch nicht zuerst in plentymarkets, da du den Artikel im Anschluss nicht mehr bei La Redoute entfernen kannst.
====

[.instruction]
Artikel löschen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke der Zeile des Artikels, den du löschen möchtest, auf *Löschen*. +
→ Der Artikel wird aus dem plentymarkets System entfernt.

[#1600]
==  API-Log abrufen

Im Menü *Daten » API-Log » Tab: API-Log* findest du eine Historie über Vorgänge, die über die La Redoute-Schnittstelle ausgeführt wurden. Das Format *LaRedoute* steht dir für La Redoute zur Verfügung.

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle das Format *LaRedoute* aus der Dropdown-Liste *Vorgang*.
. Wähle ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wähle die Anzahl der Ergebnisse pro Seite.
. Klicke auf *Suchen*, um die Ergebnisse anzuzeigen.
