= La Redoute
:lang: de
include::{includedir}/_header.adoc[]
:keywords: La Redoute, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz La Redoute in Ihrem plentymarkets System ein.
:position: 170

plentymarkets ermöglicht Ihnen die Anbindung an La Redoute, Frankreichs Marktführer im Versandhandel. Erfahren Sie, wie Sie die Schnittstelle zu La Redoute einrichten und welche Bedingungen Sie als Online-Händler erfüllen müssen, um Ihre Artikel auf La Redoute anzubieten.

[#100]
== Bei La Redoute registrieren

La Redoute stellt Bedingungen an jeden Online-Händler, der über den Marktplatz verkaufen will:

. Der Artikelkatalog muss komplett auf Französisch vorliegen.
. Sie müssen Kundenanfragen per E-Mail auf Französisch beantworten können.
. Außerdem müssen Sie selbstverständlich nach Frankreich versenden wollen und können.

Um Ihr plentymarkets System für den Marktplatz La Redoute einzurichten, müssen Sie sich zuerst bei La Redoute registrieren. Die Registrierung erfolgt in zwei Schritten. Zunächst nehmen Sie Kontakt mit dem La Redoute Business Development Team auf:

.Ansprechpartner bei La Redoute
[cols="1,3"]
|====
|Ansprechpartner |E-Mail-Adresse

|*Frédéric Maus* +
Head of Business development
|link:mailto:fmaus@redoute.fr[fmaus@redoute.fr]

|*Joseph Farhat* +
Manager Business development - Fashion &amp; accessories
|link:mailto:jfarhat@redoute.fr[jfarhat@redoute.fr]

|*Carlos Cantoni* +
Manager Business development - Home &amp;
electronics
|link:mailto:ccantoni@redoute.fr[ccantoni@redoute.fr]
|====

Anschließend erhalten Sie von La Redoute eine Excel-Datei, die Sie mit Informationen über Ihre Firma befüllen und zurücksenden. Mit der Datei senden Sie folgende Unterlagen:

* Eine Kopie Ihres Handelsregisterauszugs
* Eine Erklärung Ihrer Bank mit Ihren Kontoinformationen (mit Swift und IBAN)

*_Oder:_* Füllen Sie auf der französischen Seite von La Redoute das link:http://www.laredoute.fr/espace-devenir-vendeur-marketplace.aspx[*Kontaktformular*^] aus. Nachdem Sie alle nötigen Informationen an La Redoute geschickt haben, erhalten Sie eine E-Mail von La Redoute, die die CallerID und den CatalogSupplierName beinhaltet. Diese IDs können Sie jetzt in Ihr plentymarkets System eingeben.

[#200]
== La Redoute in plentymarkets einrichten

Nehmen Sie folgende Grundeinstellungen für die Anbindung von La Redoute an Ihr plentymarkets System vor.

[.instruction]
La Redoute in plentymarkets einrichten:

. Öffnen Sie das Menü *System » Märkte » La Redoute » Einstellungen*.
. Nehmen Sie die Einstellungen gemäß Tabelle 2 vor.
. *Speichern* Sie die Einstellungen.

.Grundeinstellungen des Marktplatzes La Redoute
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Schnittstellenmodus*
|Schnittstellenmodus wählen. +
*Testmodus EIN* = Wählen, wenn Einstellungen und Vorbereitungen an Schnittstelle und Artikeln getroffen werden. +
*Aktivmodus EIN* = Wählen, nachdem La Redoute bestätigt hat, dass alle Tests abgeschlossen wurden.

2+|Vertriebspartner-Information

|*VendorId*
|Von La Redoute erhaltene ID eingeben.

2+|Artikeleinstellungen

|*Artikelname*
|Wählen, welches Feld an La Redoute als Artikelname übertragen werden soll. Der Name muss in französischer Sprache sein, sonst findet kein Artikelexport statt.

|*Artikelvorschautext*
|Wählen, welches Feld an La Redoute als Artikelvorschautext übertragen werden soll. Der Artikelvorschautext muss in französischer Sprache sein, sonst findet kein Artikelexport statt.

|*Artikelbeschreibung*
|Wählen, welches Feld an La Redoute als Artikelbeschreibung übertragen werden soll. Die Artikelbeschreibung muss in französischer Sprache sein, sonst findet kein Artikelexport statt.

|*Technische Daten*
|Wählen, ob Sie technische Daten übertragen möchten oder nicht. Die technischen Daten müssen in französischer Sprache sein, sonst findet kein Artikelexport statt.

|*Artikel-EAN*
|EAN wählen, die als Artikel-EAN übertragen wird.

|*Varianten-EAN*
|EAN wählen, die als Varianten-EAN übertragen wird.

|*Versandvorbereitung*
|Dauer in Tagen eingeben, die Sie zum Verpacken und Übergeben der Bestellung an den Versanddienstleister benötigen.

|*Minimum Lieferverzugsaufschlag*
|Dauer in Tagen eingeben. Die Dauer wird zu der normalen Mindestlieferzeit Ihrer Artikel hinzuaddiert.

|*Maximum Lieferverzugsaufschlag*
|Dauer in Tagen eingeben. Die Dauer wird zu der normalen maximalen Lieferzeit Ihrer Artikel hinzuaddiert.

|*Versandkosten überschreiben*
|Die hier eingegebenen Versandkosten werden anstatt der am Artikel hinterlegten Versandkosten an La Redoute übermittelt.

2+|Bestelleinstellungen

|*Temporäre Kunden-ID*
|Einen Kunden für La Redoute erstellen und dessen ID hier eingeben (siehe Kapitel 11).

|*Zahlungseingang buchen*
|Wählen, ob Aufträge von La Redoute als *bezahlt* oder *offen* importiert werden sollen, da die Kunden an La Redoute überweisen und La Redoute Ihnen das Geld erst danach auszahlt.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* stündlicher Auftragsimport
* täglicher Artikelexport
* zweistündlicher Bestandsabgleich

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit La Redoute verknüpfen können, muss im Menü *System » Aufträge » Auftragsherkunft* die Auftragsherkunft La Redoute aktiviert werden.

[.instruction]
Auftragsherkunft für La Redoute aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Auftragsherkunft*.
. Setzen Sie bei *La Redoute* ein Häkchen.
. *Speichern* Sie die Einstellungen.

[#300]
== Artikelinformationen übersetzen

Da La Redoute ein französischer Marktplatz ist, muss ein *<<artikel/artikel-verwalten#20, Artikel>>*, der dort verkauft werden soll, auf Französisch erstellt sein. Eine weitere Voraussetzung für ein Einstellen auf La Redoute ist eine Artikelbeschreibung auf Französisch. Des Weiteren müssen alle Attribute und Merkmale, die mit La Redoute verknüpft werden, ebenfalls auf Französisch vorliegen. Der Artikel muss außerdem über eine EAN und Artikelbilder verfügen.

[.instruction]
Französische Sprachvariante eines bestehenden Artikels erstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab *Texte*.
. Wählen Sie aus der Dropdown-Liste *Öffne Sprache* die Einstellung *fr*.
. Geben Sie im Feld *Name 1* einen französischen Namen für den Artikel ein.
. Geben Sie weitere Texte (Beschreibung, Technische Daten etc.) ein. +
→ Die Beschreibung ist Pflicht für La Redoute.
. *Speichern* Sie die Einstellungen.

[#400]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf La Redoute verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID*>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für La Redoute einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktivieren Sie die Option *La Redoute*.
. Aktivieren Sie die Option Web-API.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen. +
→ Der Artikel ist auf La Redoute verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

[#450]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID*>> im Tab *Verfügbarkeit* fügen Sie, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechseln Sie in das Tab *Verfügbarkeit*.
.  Klicken Sie im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
.  Wählen Sie die Herkunft *La Redoute*.
.  Geben Sie die SKU ein.
.  Klicken Sie auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#500]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft La Redoute einen Verkaufspreis festzulegen. Dieser Preis wird auf La Redoute angezeigt.

[.instruction]
Verkaufspreis für La Redoute festlegen:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setzen Sie ein Häkchen bei der Herkunft *La Redoute*.
. *Speichern* Sie die Einstellungen.

[#600]
== Merkmale verknüpfen

Verknüpfen Sie Ihre <<artikel/artikel-verwalten#480, *Merkmale*>> mit den La Redoute-Merkmalen. Beachten Sie, dass Ihre Merkmale hierfür auf Französisch erstellt sein müssen. Sie erhalten von La Redoute eine XLS-Datei, die die Merkmale enthält. Aus dieser Datei erstellen Sie für den Merkmalimport eine CSV-Datei.

[IMPORTANT]
.Notwendige Verknüpfungen vornehmen
====
Damit Ihre Artikel auf dem Marktplatz La Redoute zum Verkauf angezeigt werden, müssen Sie verschiedene Verknüpfungen erstellen. Die Verknüpfung von *Merkmalen*, *Kategorien*, *Attributen und -werten* sowie *Herstellern* ist Pflicht.
====

[.instruction]
Merkmale verknüpfen:

. Öffnen Sie das Menü *System » Märkte » La Redoute » Import*.
. Klicken Sie auf *Datei auswählen*.
. Wählen Sie die CSV-Datei mit den Merkmalen.
. Wählen Sie das Feldtrennzeichen.
. *Speichern* Sie die Einstellungen. +
→ Die Datei wird hochgeladen.
. Wechseln Sie in das Menü *System » Artikel » Merkmale*.
. Klappen Sie ein Merkmal auf.
. Wählen Sie aus der Dropdown-Liste *Sprache* für Französisch *fr*.
. Geben Sie in das Feld *Name* den französischen Namen des Merkmals ein.
. Wählen Sie aus der Dropdown-Liste im Feld *La Redoute-Merkmal* das La Redoute-Merkmal.
. *Speichern* Sie die Einstellungen.

[#700]
== Kategorien verknüpfen

Damit Ihre Artikel in den richtigen Kategorien bei La Redoute angezeigt werden, müssen Sie Kategorieverknüpfungen erstellen.

[.instruction]
Kategorien verknüpfen:

. Öffnen Sie das Menü *System » Märkte » La Redoute » Kategorieverknüpfung*.
. Geben Sie in der Spalte *La Redoute-Kategorie-ID* auf der rechten Seite die ID der Kategorie ein, die am besten zu Ihrer Webshop-Kategorie passt. +
→ Die La Redoute-Kategorie-ID entnehmen Sie den Kategorie-Dateien, die Sie von La Redoute erhalten haben.
. *Speichern* Sie die Einstellungen.

[#800]
== Attribute und Attributwerte verknüpfen

Auch <<artikel/artikel-verwalten#390, *Attribute*>> müssen verknüpft werden, bevor Ihre Artikel zu La Redoute übertragen werden können. Beachten Sie, dass nur die Artikel auf La Redoute angezeigt werden, von denen sämtliche Attribute verknüpft sind.

[.instruction]
Attribute und Attributwerte verknüpfen:

. Öffnen Sie das Menü *System » Artikel » Attribute*. +
→ Die Übersicht aller in Ihrem Katalog verwendeten Attribute wird geöffnet.
. Klappen Sie ein Attribut auf.
. Wechseln Sie in das Tab *Marktplatzvariation*.
. Wählen Sie die Option *La Redoute* aus der Dropdown-Liste *Marktplatz*. +
→ Eine Dropdown-Liste wird im Bereich *Einstellungen* geöffnet.
. Wählen Sie das passende La Redoute-Attribut aus der Dropdown-Liste.
. Wählen Sie im Bereich *Marktplatzvariation* für Ihre Attributwerte passende La Redoute-Attributwerte.
. *Speichern* Sie die Einstellungen.
. Wiederholen Sie den Vorgang für alle weiteren Attribute.

[#900]
== Hersteller verknüpfen

Zuletzt verknüpfen Sie noch Ihre <<artikel/artikel-verwalten#560, *Hersteller*>>. Dazu erhalten Sie von La Redoute eine Datei mit Hersteller-IDs.

[.instruction]
Hersteller verknüpfen:

. Öffnen Sie das Menü *System » Artikel » Hersteller*.
. Öffnen Sie einen Hersteller.
. Geben Sie im Feld *La Redoute-ID* die ID ein. +
→ Die La Redoute-Hersteller-ID entnehmen Sie der Datei, die Sie von La Redoute erhalten haben.

[#1000]
== Zahlungsart aktivieren

Die Zahlungsart *La Redoute Payment* ist für Aufträge, die über den französischen Marktplatz *link:http://www.laredoute.com/[La Redoute^]* in Ihr plentymarkets System kommen.

[.instruction]
Zahlungsart La Redoute Payment aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
. Klicken Sie auf *La Redoute Payment*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 3.
. Setzen Sie ein Häkchen bei der Option *Aktiv*.
. *Speichern* Sie die Einstellungen.

.Einstellungen der Zahlungsart
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit haben Sie die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
|Kein Lieferland wählen. +
Sie können die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig konfiguriert.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen finden Sie auf der Handbuchseite *<<basics/statistik#, Statistik>>*. Ein Beispiel für pauschale und prozentuale Kosten finden Sie auf der Handbuchseite *<<payment/zahlungsarten-verwalten#20, Grundeinstellungen>>*.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » CRM » Kundenklassen* aktivieren oder deaktivieren Sie *erlaubte Zahlungsarten*. +
Weitere Informationen finden Sie im Kapitel *<<payment/zahlungsarten-verwalten#30, Zahlungsarten und Kundenklassen>>*.
====

Weitere Informationen finden Sie auf der Handbuchseite *<<payment/zahlungsarten-verwalten#, Zahlungsarten>>*.

[#1100]
== Temporären Kunden erstellen

Die Aufträge kommen zunächst ohne Kundendaten ins System. Nachdem der Auftrag durch Ihr plentymarkets System bei La Redoute bestätigt wurde, werden die tatsächlichen Kundendaten übermittelt. Deshalb müssen Sie für La Redoute einen Kunden in Ihrem System erstellen und die ID dieses Kunden im Feld *Temporäre Kunden-ID* eingeben.

[.instruction]
Neuen Kunden erstellen:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Klicken Sie auf *Neu*.
. Geben Sie mindestens einen Namen für den temporären Kunden ein.
. *Speichern* Sie die Einstellungen.
. Klicken Sie auf *Suchen*.
. Suchen Sie den erstellten Kunden.
. Notieren Sie die *Kunden-ID*.
. Wechseln Sie in das Menü *System » Märkte » La Redoute » Einstellungen*.
. Geben Sie im Feld *Temporäre Kunden-ID* die ID des La Redoute-Kunden ein.
. *Speichern* Sie die Einstellungen.

[#1200]
== Versandbestätigungen automatisch senden

Richten Sie eine *<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>* ein, um Versandbestätigungen automatisch an La Redoute zu senden. Die Versandbestätigung wird automatisch an La Redoute gesendet, wenn der Auftrag in den Status *[7] Warenausgang gebucht* wechselt. Der Käufer wird automatisch durch La Redoute über den Versand benachrichtigt.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß Tabelle 4.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 4 vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an La Redoute
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung &gt; Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*La Redoute*

|*Aktion*
|*Versand &gt; Versandbestätigung an La Redoute senden*
|
|====

[#1300]
== Retouren automatisch senden

Richten Sie eine *<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>* ein, um Retouren automatisch an La Redoute zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß Tabelle 5.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 5 vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Retouren an La Redoute
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage &gt; Neue Retoure (durch Kunde)*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*La Redoute*

|*Aktion*
|*Retoure &gt; Retoure an La Redoute senden*
|
|====

[#1400]
== Stornierungen melden

Eine Stornierung im eigentlichen Sinne kann nicht an La Redoute gesendet werden. Wenn Sie einen Auftrag stornieren möchten, weil Sie z.B. den Artikel aus dem Sortiment genommen haben, dann müssen Sie eine Retoure erstellen.

Neue Aufträge von La Redoute werden von plentymarkets automatisch akzeptiert, damit die Daten überhaupt in Ihr plentymarkets System importiert werden. Das Akzeptieren des Auftrags erlaubt Ihnen nicht, den Auftrag hinterher zu stornieren. Buchen Sie deshalb zunächst den Warenausgang und erstellen sofort im Anschluss eine Retoure.

[TIP]
.Tipp: E-Mail an Kunden
====
Senden Sie bei einer Stornierung Ihrerseits zusätzlich eine E-Mail an den Kunden, um den Kunden darüber zu informieren, dass der Artikel z.B. nicht mehr in Ihrem Sortiment enthalten ist.
====

[#1500]
== Artikel löschen

Um <<artikel/artikel-verwalten#, *Artikel*>>, die bei La Redoute angeboten werden, endgültig aus Ihrem plentymarkets System zu entfernen, müssen Sie zunächst diese Artikel aus dem La Redoute-Katalog entfernen.

[.instruction]
Artikel aus dem La Redoute-Katalog entfernen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel, den Sie löschen möchten.
. Wechseln Sie in das Tab *Verfügbar*.
. Deaktivieren Sie die Option *La Redoute*.
. *Speichern* Sie die Einstellungen. +
→ Nach diesem Vorgang müssen Sie 24 Stunden warten, bis der Artikel aus dem La Redoute-Katalog entfernt wird.

[WARNING]
.Artikel nie ohne Wartezeit löschen
====
Löschen Sie einen Artikel nicht vor Ablauf der 24 Stunden und auch nicht zuerst in plentymarkets, da Sie den Artikel im Anschluss nicht mehr bei La Redoute entfernen können.
====

[.instruction]
Artikel löschen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Klicken in der Zeile des Artikels, den Sie löschen möchten, auf *Löschen*. +
→ Der Artikel wird aus dem plentymarkets System entfernt.

[#1600]
==  API-Log abrufen

Im Menü *Daten » API-Log » Tab: API-Log* finden Sie eine Historie über Vorgänge, die über die La Redoute-Schnittstelle ausgeführt wurden. Das Format *LaRedoute* steht Ihnen für La Redoute zur Verfügung.

[.instruction]
API-Log abrufen:

.  Öffnen Sie das Menü *Daten » API-Log » Tab: API-Log*.
.  Wählen Sie das Format *LaRedoute* aus der Dropdown-Liste *Vorgang*.
.  Wählen Sie ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
.  Wählen Sie die Anzahl der Ergebnisse pro Seite.
.  Klicken Sie auf *Suchen*, um die Ergebnisse anzuzeigen.
