= Restposten.de
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: Restposten, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Restposten.de in deinem plentymarkets System ein.
:position: 200
:url: maerkte/restposten-de

link:http://www.restposten.de/[Restposten.de^]{nbsp}icon:external-link[] ist ein reines B2B-Portal, d.h. sowohl Anbieter:in als auch Nachfrager:in müssen im Besitz eines gültigen Gewerbenachweises sein (Quelle: Restposten.de). +
Auf dieser Seite erfährst du, wie du den Marktplatz Restposten.de an dein plentymarkets System anbindest.

[#100]
== Bei Restposten.de registrieren

Um dein plentymarkets System für Restposten.de einzustellen, musst du dich zuerst im link:https://www.restposten.de/register.php[Händlerportal^]{nbsp}icon:external-link[] von Restposten.de registrieren.

[#200]
== Benutzerkonto erstellen

Dein plentymarkets System wird über die SOAP-API mit Restposten.de verbunden. Für den Zugriff benötigt der Marktplatz ein eigenes Benutzerkonto mit Zugriffsrechten auf die API in deinem plentymarkets System. Erstelle im Menü *Einrichtung » Einstellungen » Benutzer » Konten* ein neues Benutzerkonto der Benutzerklasse *API* für Restposten.de. Aktiviere außerdem den Call *GetCategoryMappingForMarket*. Dieser Call sorgt dafür, dass der Marktplatz später deine Kategorieverknüpfungen auslesen kann.

[.instruction]
Benutzerkonto für Restposten.de erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Konten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neuen Benutzer erstellen* wird geöffnet.
. Gib die Daten ein.
. Wähle als Benutzerklasse *API*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Konto wird erstellt.
. Wähle das Konto aus der Liste. +
→ Das Bearbeitungsfenster wird geöffnet.
. Öffne das Tab *Berechtigung » API*.
. Klappe den Bereich *Item* auf.
. Aktiviere den Call *GetCategoryMappingForMarket*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Weitere Informationen findest du auf der Handbuchseite <<business-entscheidungen/benutzerkonten-zugaenge#, Benutzerkonten verwalten>>.

[#300]
== Daten bereitstellen

Für die Anbindung an dein plentymarkets System benötigt Restposten.de die folgenden Daten:

* URL der SOAP API WSDL. +
→ Du findest die URL im Menü <<basics/datenaustausch/api-daten#, Einrichtung » Einstellungen » API » Daten>> unter *SOAP WSDL*.
* Benutzername und Passwort für das von dir erstellte Benutzerkonto für Restposten.de
* Deine Zugangsdaten für das Händlerportal von Restposten.de.

[#350]
== Auftragsherkunft aktivieren

:market: Restposten
:referrer: Restposten
:referrer-option: pass:quotes[Option *Restposten*]

include::_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#400]
== Variantenverfügbarkeit einstellen

:market-availability: Restposten.de
:option-availability: Restposten
:web-api:

include::_textblocks/instructions/variantenverfuegbarkeit.adoc[]

// Web-API erforderlich!

[#430]
== SKU manuell festlegen

:referrer-sku: Restposten

include::_textblocks/instructions/sku-manuell.adoc[]

// Marktplatzkonto nicht erforderlich!

[#450]
== Verkaufspreis festlegen

:referrer-price: Restposten.de

include::_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#500]
== Merkmale erstellen

Mit <<artikel/einstellungen/eigenschaften#100, Merkmalen>> verknüpfst du bestimmte Eigenschaften, die du für die Einrichtung des Marktplatzes Restposten.de benötigst, mit deinen Artikeln. Das Merkmal muss als *Merkmaltyp* mit der Option *Auswahl* erstellt sein, damit Restposten.de die nötigen Parameter abrufen kann. Stimme mit Restposten.de ab, welche Werte für das Merkmal benötigt werden.

[.instruction]
Merkmal für Restposten.de erstellen:

. Öffne das Menü *Einrichtung » Artikel » Merkmale*.
. Wechsele in das Tab *Neues Merkmal*.
. Gib den Namen unter *Name (intern)* ein.
. Wähle als *Merkmaltyp* die Option *Auswahl*. +
→ Ein Bereich wird geöffnet, in dem du Namen und Bezeichnung eingibst.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Merkmal wird erstellt.
. Wechsele in das Tab *Merkmale*.
. Klappe das Merkmal auf.
. Gib im Bereich *Auswahl* in das nächste Auswahlfeld einen weiteren Namen ein.
. *Speichere* (icon:save[role="green"]) die Einstellung.
. Wiederhole Vorgang 8 und 9, bis alle benötigten Werte erstellt sind.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#600]
== Kategorien verknüpfen

Verknüpfe deine plentymarkets Kategorien mit den <<artikel/einstellungen/kategorien#, Kategorien>> von Restposten.de, damit deine Artikel in diesen Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » Restposten*. +
→ Das Tab *Kategorieverknüpfung* wird angezeigt.
. Klappe die Kategorie auf, die du mit einer Restposten-Kategorie verknüpfen möchtest.
. Wähle eine Restposten-Hauptkategorie aus der Dropdown-Liste. +
→ Ein Fenster mit Unterkategorien wird geöffnet.
. Wähle aus den weiteren Unterkategorien jeweils die passende Restposten-Kategorie. +
→ Der Kategoriepfad wird im Textfeld *Kategorie* angezeigt.
. Klicke auf *Übernehmen*. +
→ Das Kategoriefenster wird geschlossen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[IMPORTANT]
.Verknüpfung bis in die unterste Kategorieebene
====
Verknüpfe deine Kategorien immer bis in die unterste Ebene. Andernfalls ist eine Verknüpfung nicht möglich.
====

[#700]
Retouren

Für Retouren musst du einen Auftrag vom Typ *Retoure* erstellen und keine Gutschrift. Achte auch darauf, den Artikelwert in Prozent in den Artikelpositionen der Retoure anzugeben.
