= Restposten.de
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Restposten, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Restposten.de in deinem plentymarkets System ein.
:position: 200
:url: maerkte/restposten-de
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

link:http://www.restposten.de/[Restposten.de^] ist ein reines B2B-Portal, d.h. sowohl Anbieter als auch Nachfrager müssen im Besitz eines gültigen Gewerbenachweises sein (Quelle: Restposten.de). +
Auf dieser Seite erfährst du, wie du den Marktplatz Restposten.de an dein plentymarkets System anbindest.

[#100]
== Bei Restposten.de registrieren

Um dein plentymarkets System für Restposten.de einzustellen, musst du dich zuerst im link:https://www.restposten.de/register.php[Händlerportal^] von Restposten.de registrieren.

[#200]
== Benutzerkonto erstellen

Dein plentymarkets System wird über die SOAP-API mit Restposten.de verbunden. Für den Zugriff benötigt der Marktplatz ein eigenes Benutzerkonto mit Zugriffsrechten auf die API in deinem plentymarkets System. Erstelle im Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten* ein neues Benutzerkonto der Benutzerklasse *API* für Restposten.de. Aktiviere außerdem den Call *GetCategoryMappingForMarket*. Dieser Call sorgt dafür, dass der Marktplatz später deine Kategorieverknüpfungen auslesen kann.

[.instruction]
Benutzerkonto für Restposten.de erstellen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neuen Benutzer erstellen* wird geöffnet.
. Gib die Daten ein.
. Wähle als Benutzerklasse *API*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Benutzer wird erstellt.
. Wähle den Benutzer aus der Liste. +
→ Das Bearbeitungsfenster wird geöffnet.
. Öffne das Tab *Berechtigung » API*.
. Klappe den Bereich *Item* auf.
. Aktiviere den Call *GetCategoryMappingForMarket*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Weitere Informationen findest du auf der Handbuchseite <<basics/admin-aufgaben/benutzer-verwalten#, Benutzerkonten verwalten>>.

[#300]
== Daten bereitstellen

Für die Anbindung an dein plentymarkets System benötigt Restposten.de die folgenden Daten:

* URL der SOAP API WSDL. +
→ Du findest die URL im Menü <<basics/datenaustausch/api-daten#, System » Systemeinstellungen » Einstellungen » API » Daten>> unter *SOAP WSDL*.
* Benutzername und Passwort für das von dir erstellte Benutzerkonto für Restposten.de
* Deine Login-Daten für das Händlerportal von Restposten.de.

[#350]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit Restposten verknüpfen kannst, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft *Restposten* aktiviert werden.

[.instruction]
Auftragsherkunft für Restposten aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setze bei *Restposten* ein Häkchen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#400]
== Artikelverfügbarkeit einstellen

Artikel, die du auf Restposten.de verkaufen möchtest, müssen im Menü <<artikel/artikel-verwalten#180, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Restposten.de einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Setze ein Häkchen bei der Option *Restposten*.
. Setze ein Häkchen bei der Option *Web-API*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Artikel ist auf Restposten.de verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

[#430]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Restposten*.
. Gib die SKU ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die SKU wird gespeichert und angezeigt.

[#450]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft Restposten.de einen Verkaufspreis festzulegen. Dieser Preis wird auf Restposten.de angezeigt.

[.instruction]
Verkaufspreis für Restposten.de festlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *Restposten*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#500]
== Merkmale erstellen

Mit <<artikel/artikel-verwalten#480, Merkmalen>> verknüpfst du bestimmte Eigenschaften, die du für die Einrichtung des Marktplatzes Restposten.de benötigst, mit deinen Artikeln. Das Merkmal muss als *Merkmaltyp* mit der Option *Auswahl* erstellt sein, damit Restposten.de die nötigen Parameter abrufen kann. Stimme mit Restposten.de ab, welche Werte für das Merkmal benötigt werden.

[.instruction]
Merkmal für Restposten.de erstellen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Wechsele in das Tab *Neues Merkmal*.
. Gib den Namen unter *Name (intern)* ein.
. Wähle als *Merkmaltyp* die Option *Auswahl*. +
→ Ein Bereich wird geöffnet, in dem du Namen und Bezeichnung eingibst.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Merkmal wird erstellt.
. Wechsele in das Tab *Merkmale*.
. Klappe das Merkmal auf.
. Gib im Bereich *Auswahl* in das nächste Auswahlfeld einen weiteren Namen ein.
. *Speichere* (icon:save[role="green"]) die Einstellung.
. Wiederhole Vorgang 8 und 9, bis alle benötigten Werte erstellt sind.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#600]
== Kategorien verknüpfen

Verknüpfe deine Webshop-Kategorien mit den <<artikel/kategorien-verwalten#, Kategorien>> von Restposten.de, damit deine Artikel in diesen Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Restposten*. +
→ Das Tab *Kategorieverknüpfung* wird angezeigt.
. Klappe die Kategorie auf, die Sie mit einer Restposten-Kategorie verknüpfen möchten.
. Wähle eine Restposten-Hauptkategorie aus der Dropdown-Liste. +
→ Ein Fenster mit Unterkategorien wird geöffnet.
. Wähle aus den weiteren Unterkategorien jeweils die passende Restposten-Kategorie. +
→ Der Kategoriepfad erscheint im Textfeld *Kategorie*.
. Klicke auf *Übernehmen*. +
→ Das Kategoriefenster wird geschlossen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[IMPORTANT]
.Verknüpfung bis in die unterste Kategorieebene
====
Verknüpfe deine Kategorien immer bis in die unterste Ebene. Andernfalls ist eine Verknüpfung nicht möglich.
====

[#700]
Retouren

Für Retouren musst du einen Auftrag vom Typ *Retoure* erstellen und keine Gutschrift. Achte auch darauf, den Artikelwert in Prozent in den Artikelpositionen der Retoure anzugeben.
