= bol.com
:lang: de
include::{includedir}/_header.adoc[]
:keywords: bol.com, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz bol.com in deinem plentymarkets System ein.
:position: 30
:url: maerkte/bol-com
:id: 0WQSMLF
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Der niederländische Online-Marktplatz link:http://bol.com[bol.com^] hat sich zum führenden Online-Marktplatz der Benelux entwickelt und vertreibt eine breite Angebotspalette inklusive Elektronik, Multimedia, Spielzeug etc.

[#100]
== Bei bol.com registrieren

Bevor du bol.com in plentymarkets einrichtest, musst du dich auf link:https://bol.com.[bol.com^] registrieren.

[#200]
== bol.com in plentymarkets einrichten

Um Artikel auf bol.com anzubieten, richte bol.com in plentymarkets ein. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
bol.com in plentymarkets einrichten:

. Öffne das Menü *Einrichtung » Märkte » bol.com » Einstellungen*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<grundeinstellungen-bol>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[grundeinstellungen-bol]]
.Grundeinstellungen des Marktplatzes bol.com
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Automatischen Datenaustausch aktivieren*
|Ist der Datenaustausch aktiviert, findet ein täglicher Artikelexport, ein stündlicher Bestandsabgleich und ein viertelstündlicher Auftragsimport statt.

|*öffentlicher API-Schlüssel*
|API-Schlüssel eintragen, wie von bol.com erhalten.

|*privater API-Schlüssel*
|API-Schlüssel eintragen, wie von bol.com erhalten.

|*Mandant*
|Mandanten wählen. Aufträge werden beim Auftragsimport mit diesem Mandanten verknüpft.

|*Lagerauswahl*
|Bestandsmenge für den Angebotsexport wählen. Eine der folgenden Optionen wählen: +
*Summe der Bestandsmengen aller Vertriebslager verwenden* +
*Hauptlager des Artikels verwenden* +
*Lager auswählen* = Ein oder mehrere Lager wählen. +
*Wichtig:* Die Option *Lagerauswahl* beeinflusst den Artikelexport. Wenn ein Artikel nicht mit den hier gewählten Lagern verknüpft ist, wird dieser Artikel nicht exportiert.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* Auftragsimport alle 15 Minuten

[#250]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit bol.com verknüpfen kannst, muss im Menü *Einrichtung » Aufträge » Auftragsherkunft* die Auftragsherkunft bol.com aktiviert werden.

[.instruction]
Auftragsherkunft für bol.com aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Setze bei *bol.com* ein Häkchen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die du auf bol.com verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für bol.com einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *bol.com*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Artikel ist auf bol.com verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

Beachte, dass alle Artikeldaten in niederländisch zu bol.com exportiert werden müssen.

[#400]
== Kategorien verknüpfen

Verknüpfe deine Webshop-Kategorien mit den Kategorien von bol.com, damit deine Artikel in diesen bol.com-Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » bol.com » Kategorieverknüpfung*.
. Klicke auf *Suchen*.  +
→ Das Fenster *Kategorie wählen* wird geöffnet.
. Wähle die bol.com-Kategorie, die am besten zu deiner Webshop-Kategorie passt.
. Klicke auf *Übernehmen*. +
→ Die Bezeichnung der bol.com-Kategorie und der Kategoriepfad werden angezeigt.
. Wenn du die Bezeichnung der bol.com-Kategorie bereits kennst, gib sie in das Feld *Marktplatzkategorie* ein, um sie mit deiner Webshop-Kategorie zu verknüpfen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#450]
== Merkmale erstellen

Als nächstes erstellst du <<artikel/artikel-verwalten#480, Merkmale>> und verknüpfst diese mit den bol.com-Merkmalen. Die passenden Merkmale zu einer bol.com-Kategorie entnimmst du der bol.com-Datei Datamodel. Die bol.com Datamodel-Datei kannst du link:https://developers.bol.com/datamodel/[hier^] herunterladen.

[.instruction]
Merkmal erstellen:

. Öffne das Menü *Einrichtung » Artikel » Merkmale*.
. Öffne das Tab *Neues Merkmal*.
. Gib unter *Name (intern)* einen Namen für das Merkmal ein.
. Wähle aus der Dropdown-Liste *Sprache* für Niederländisch *nl*.
. Gib in das Feld *Name* den niederländischen Namen des Merkmals ein.
. Wähle aus der Dropdown-Liste im Feld *Merkmaltyp* die Option *Text*.
. Trage in der Zeile *bol.com-Merkmal* das bol.com-Merkmal ein, wie aus der Datamodel-Datei in der Spalte *Attribute name* entnommen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

*bol_fulfillment* ist ein Pflichtfeld für den Angebotsexport. Dabei gibst du an, ob der Artikel direkt von dir oder von bol.com versendet wird. Trage dazu in der Zeile *bol.com-Merkmal* das bol.com-Merkmal *bol_filfillment* ein.

Wenn du gebrauchte Artikel über bol.com verkaufen möchtest, musst du den gebrauchten Zustand der Artikel über das Merkmal *bol_used* angeben. Trage dazu in der Zeile *bol.com-Merkmal* das bol.com-Merkmal *bol_used* ein.

[#500]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft bol.com einen Verkaufspreis festzulegen. Dieser Preis wird auf bol.com angezeigt.

[.instruction]
Verkaufspreis für bol.com festlegen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *bol.com*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#600]
== Artikel- und Angebotsexport einrichten

In diesem Kapitel wird beschrieben, wie du deine Artikel und Angebote zu bol.com überträgst. Artikel und Angebote werden über den elastischen Export zu bol.com übertragen. Zunächst legst du das Datenformat *BolItemExport* und *BolOfferExport* an und übermittelst im Anschluss die Dateien zu bol.com. Beide Dateien müssen an bol.com übergeben werden, damit deine Artikel bei bol.com verkauft werden können.

Folgende Pflichtfelder müssen für den Artikelexport mitgegeben werden:

* EAN
* SKU
* Name
* Kategorien
* Artikelbeschreibung
* Bild
* Hersteller

Folgende Pflichtfelder müssen für den Angebotsexport mitgegeben werden:

* EAN
* SKU
* Bestand
* Preis
* Artikelzustand
* Versandverfügbarkeit
* Versand durch

[.instruction]
Export einrichten:

. Öffne das Menü *Daten » Elastischer Export*.
. Klicke auf *Neuer Export*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-artikelexport-bol>>.
. Nimm weitere Einstellungen für Artikelfilter und Formateinstellungen vor. Beachte dazu die Erläuterungen in Tabelle 2 auf der Handbuchseite <<daten/daten-exportieren/elastischer-export#300, Elastischer Export>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Eine ID für das Exportformat wird vergeben und das Exportformat erscheint in der Übersicht *Exporte*. +
→ Klicke im Menü *Daten » Elastischer Export » Tab: Exporte* auf *Herunterladen* (Pfeil-Symbol), um die eben erstellte Datei herunterzuladen.

[[einstellungen-artikelexport-bol]]
.Einstellungen für Artikelexport
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

|*Name*
|Name eingeben. Unter diesem Namen erscheint das Exportformat in der Übersicht im Tab *Exporte*.

|*Typ*
|Typ *Artikel* aus der Dropdown-Liste wählen.

|*Format*
|Format *BolItemExport* für den Artkelexport wählen oder *BolOfferExport* für den Angebotsexport aus der Dropdown-Liste wählen.

|*Limit*
|Zahl eingeben. Wenn mehr als 10000 Datensätze an bol.com übertragen werden sollen, wird die Ausgabedatei für 24 Stunden nicht noch einmal neu generiert, um Ressourcen zu sparen.

|*Bereitstellung*
|*FTPS* wählen.

|*Dateiname*, +
*Server*, +
*Port*, +
*Benutzername*, +
*Passwort*, +
*Pfad*
|Parameter eingeben. Die Zugangsdaten für den Server inklusive Passwort und Benutzername werden von bol.com zur Verfügung gestellt. Der Dateiname beim BolOfferExport hat den Aufbau &lt;SellerID&gt;.csv. Der Dateiname beim BolItemExport hat den Aufbau &lt;SellerID&gt;.txt. +
Die Datei für das Format *BolItemExport* muss im Ordner */SQUARE/feed* gespeichert werden. +
Die Datei für das Format *BolOfferExport* muss im Ordner */inbound* gespeichert werden.

|*Übertragung*
|*Täglich* für den Artikelexport wählen, da bol.com nur maximal 4 Exporte pro Tag zulässt. *Stündlich* für den Angebotsexport.
|====

[#650]
== Zahlungsart aktivieren

Aktiviere die <<payment/zahlungsarten-verwalten#, Zahlungsart>> *BOL.com*, wie im Folgenden beschrieben.

[.instruction]
bol.com-Zahlungsart aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
. Klicke auf *BOL.com*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-zahlungsart-bol>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[einstellungen-zahlungsart-bol]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn Käufer*innen im Webshop die Sprache wählen.

|*Name*
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
|Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *Einrichtung » CRM » Kundenklassen* aktivierst oder deaktivierst du *erlaubte Zahlungsarten*. +
Weitere Informationen findest du im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#700]
== Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an bol.com zu senden, nachdem ein Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-versandbestätigung-bol>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-versandbestätigung-bol>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-versandbestätigung-bol]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an bol.com
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*bol.com*

|*Aktion*
|*Versand &gt; Versandbestätigung an bol.com senden*
|
|====

[#800]
== Retourenstatus automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um bol.com automatisch über den Status einer Retoure zu informieren. Bei Retouren muss ein Status an bol.com übertragen werden. Folgende Stornierungsgründe können an bol.com übertragen werden:

* Retoure erhalten
* Repariert oder ersetzt
* Retoure unvollständig
* Rückerstattung ohne Rücksendung

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-retourenstatus-bol>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-retourenstatus-bol>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-retourenstatus-bol]]
.Ereignisaktion zum automatischen Senden von Retourenstatus an bol.com
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*bol.com*

|*Aktion*
|*Auftrag &gt; Retourenstatus an bol.com senden*
|Wähle einen Status.
|====

[#900]
== Stornierungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um bol.com automatisch über Stornierungen zu informieren. Bei Stornierungen muss ein Grund für die Stornierung an bol.com übertragen werden. Erstelle im Menü *Einrichtung » Aufträge » Auftragsstatus* ggf. zusätzliche Auftragsstatus. Folgende Stornierungsgründe können an bol.com übertragen werden:

* Artikel nicht vorrätig
* Stornierung durch Kunden

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-stornierungen-bol>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-stornierungen-bol>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-stornierungen-bol]]
.Ereignisaktion zum automatischen Senden von Stornierungen an bol.com
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Statuswechsel: [8.1] Storniert durch Kunden*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*bol.com*

|*Aktion*
|*Auftrag &gt; Stornierung an bol.com senden*
|*Stornierung durch Kunden*
|====

[#1000]
== API-Log abrufen

Im Menü <<daten/api-log#, Daten » API-Log>> findest du eine Historie über Vorgänge, die über die bol.com-Schnittstelle ausgeführt wurden.

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle das Format *bol.com* aus der Dropdown-Liste *Vorgang*.
. Wähle ggf. ein *Datum*, um nur Einträge eines bestimmten Tages zu erhalten.
. Klicke auf *Suchen*, um die Suche auszuführen. +
→ Die Vorgänge werden angezeigt.
