= bol.com
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: bol.com, bol, BolItemExport, Marktplatz, bol.com einrichten, bol.com Marktplatz, Multi-Channel, Multichannel, Multi-Channel bol.com, Multichannel bol.com, multi channel bol.com, bol, Marktplatz Niederlande, Marktplatz Holland, bol.nl
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz bol.com in deinem plentymarkets System ein.
:position: 30
:url: maerkte/bol-com
:id: 0WQSMLF

Der niederländische Online-Marktplatz link:http://bol.com[bol.com^]{nbsp}icon:external-link[] hat sich zum führenden Online-Marktplatz der Benelux entwickelt und vertreibt eine breite Angebotspalette inklusive Elektronik, Multimedia, Spielzeug etc.

[IMPORTANT]
.Neue API-Version 3.0
====
Die Version 2.0 der API-Schnittstelle von bol.com wird am 12.5.2020 deaktiviert. Du kannst ab sofort auf Version 3.0 der API-Schnittstelle wechseln. Wie das geht, erfährst du im link:https://forum.plentymarkets.com/t/bol-com-integration-neuer-api-versionen-3-und-4-integration-of-new-api-versions-3-and-4/587773[plentymarkets Forum^]{nbsp}icon:external-link[].
====


[#100]
== Bei bol.com registrieren

Bevor du bol.com in plentymarkets einrichtest, musst du dich auf link:https://bol.com.[bol.com^]{nbsp}icon:external-link[] als Händler registrieren.


[#200]
== bol.com in plentymarkets einrichten

Um Artikel auf dem Marktplatz bol.com anzubieten, richte bol.com in plentymarkets ein. Die Einrichtung von bol.com nimmst du mit dem Assistenten *bol.com Grundeinstellungen* vor.

Alternativ kannst du die Grundeinstellungen im Menü *Einrichtung » Märkte » bol.com » Einstellungen* vornehmen. Beachte jedoch, dass du in diesem Menü keine bol.com-Lieferzeiten verknüpfen kannst. Lieferzeiten müssen im bol.com-Assistenten mit plentymarkets verknüpft werden.

[.tabs]
====
Assistent *bol.com Grundeinstellungen*::
+
--
Die Grundeinstellungen für bol.com nimmst du im Menü *Einrichtung » Assistenten » Omni-Channel* mit dem Assistenten *bol.com Grundeinstellungen* vor. Mit diesem Assistenten richtest du dein bol.com-Konto in plentymarkets ein. Außerdem nimmst du Einstellungen zu Lagern vor und verknüpfst plentymarkets Lieferzeiten mit Lieferzeiten von bol.com. +

Um den Assistenten zu starten, öffne das Menü *Einrichtung » Assistenten » Omni-Channel* und klicke auf den Assistenten *bol.com Grundeinstellungen*. Der Assistent wird geöffnet und du kannst mit der Kontoeinrichtung beginnen.
--

Menü *Einrichtung » Märkte » bol.com » Einstellungen*::
+
--
Im Menü *Einrichtung » Märkte » bol.com » Einstellungen* kannst du Grundeinstellungen für bol.com vornehmen.

[.instruction]
bol.com in plentymarkets einrichten:

. Öffne das Menü *Einrichtung » Märkte » bol.com » Einstellungen*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#grundeinstellungen-bol>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[grundeinstellungen-bol]]
.Grundeinstellungen des Marktplatzes bol.com
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Automatischen Datenaustausch aktivieren*
|Ist der Datenaustausch aktiviert, werden Daten zu Angeboten und Aufträgen mit bol.com ausgetauscht. Weitere Informationen findest du unter <<#prozesse>>.

| *Public key (v2)*
| Public key für API-Version 2.0 eingeben. +
*_Hinweis:_* Die API-Version 2.0 für bol.com wird am 12.5.2020 deaktiviert.

| *Private key (v2)*
| Private key für API-Version 2.0 eingeben. +
*_Hinweis:_* Die API-Version 2.0 für bol.com wird am 12.5.2020 deaktiviert.

| *Client ID (v3)*
| Client ID eingeben. Die Zugangsdaten erzeugst du bei bol.com im Händlerbereich. +
*_Hinweis:_* Client ID und Client Secret benötigst du, wenn du die API-Version 3.0 für bol.com nutzt.

| *Client Secret (v3)*
| Cient Secret eingeben. Die Zugangsdaten erzeugst du bei bol.com im Händlerbereich. +
*_Hinweis:_* Client ID und Client Secret benötigst du, wenn du die API-Version 3.0 für bol.com nutzt.

| *Mandant*
|Mandanten wählen. Aufträge werden beim Auftragsimport mit diesem Mandanten verknüpft.

| *Lagerauswahl*
|Bestandsmenge für den Angebotsexport wählen. Eine der folgenden Optionen wählen: +
*Summe der Bestandsmengen aller Vertriebslager verwenden* +
*Hauptlager des Artikels verwenden* +
*Lager auswählen* = Ein oder mehrere Lager wählen. +
→ Die unter *Lager* aufgelisteten Lager können ausgewählt werden. Häkchen setzen, um ein Lager zu wählen. +
*Wichtig:* Die Option *Lagerauswahl* beeinflusst den Artikelexport. Wenn ein Artikel nicht mit den hier gewählten Lagern verknüpft ist, wird dieser Artikel nicht exportiert.
|====
--
====

[#prozesse]
[discrete]
=== Automatisierte Prozesse

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

Angebote:

* viertelstündlicher Bestandsabgleich
* stündlicher Preisabgleich
* stündliche Aktualisierung von Lieferzeiten, Sichtbarkeit der Angebote etc.
* tägliche Löschung von Angeboten für gelöschte oder deaktivierte Varianten

Aufträge:

* viertelstündlicher Auftragsimport
* stündlicher Import von auf bol.com angemeldeten Retouren +
*_Hinweis:_* Retouren werden automatisch mit dem Status [9.00] importiert.


[#250]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit bol.com verknüpfen kannst, muss im Menü *Einrichtung » Aufträge » Auftragsherkunft* die Auftragsherkunft bol.com aktiviert werden.

[.instruction]
Auftragsherkunft für bol.com aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Aktiviere die Option *bol.com*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[#300]
== Variantenverfügbarkeit einstellen

Varianten, die du auf bol.com verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

*_Tipp:_* Welche Einstellungen an einer Variante gepflegt sein müssen, um sie auf bol.com verkaufen zu können, ist in den <<Voraussetzungen für das Einstellen von Angeboten auf bol.com, FAQ>> beschrieben.

[TIP]
.Alle Varianten eines Artikels auf bol.com verkaufen
====
Wenn du alle Varianten eines Artikels auf bol.com verkaufen möchtest, nimm die unten beschriebenen Einstellungen an der Hauptvariante vor. Die Einstellungen werden dann an alle Varianten des Artikels vererbt.
====

[.instruction]
Variantenverfügbarkeit für bol.com einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Öffne die Variante, die du auf bol.com verkaufen möchtest.
. Aktiviere im Bereich *Verfügbarkeit* die Option *Aktiv*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *bol.com*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
*_Hinweis:_* Alle Artikeldaten müssen in niederländisch zu bol.com exportiert werden.


[#400]
== Kategorien verknüpfen

Verknüpfe deine Webshop-Kategorien mit den Kategorien von bol.com, damit deine Artikel in diesen bol.com-Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » bol.com » Kategorieverknüpfung*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Das Fenster *Kategorie wählen* wird geöffnet.
. Wähle die bol.com-Kategorie, die am besten zu deiner Webshop-Kategorie passt.
. Klicke auf *Übernehmen*. +
→ Die Bezeichnung der bol.com-Kategorie und der Kategoriepfad werden angezeigt.
. Wenn du die Bezeichnung der bol.com-Kategorie bereits kennst, gib sie in das Feld *Marktplatzkategorie* ein, um sie mit deiner Webshop-Kategorie zu verknüpfen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[#450]
== Merkmale erstellen

Als nächstes erstellst du <<artikel/artikel-verwalten#480, Merkmale>> und verknüpfst diese mit den bol.com-Merkmalen. Die passenden Merkmale zu einer bol.com-Kategorie entnimmst du der bol.com-Datei Datamodel. Die bol.com Datamodel-Datei kannst du link:https://developers.bol.com/datamodel/[hier^]{nbsp}icon:external-link[] herunterladen.

[.instruction]
Merkmal erstellen:

. Öffne das Menü *Einrichtung » Artikel » Merkmale*.
. Öffne das Tab *Neues Merkmal*.
. Gib unter *Name (intern)* einen Namen für das Merkmal ein.
. Wähle aus der Dropdown-Liste *Sprache* für Niederländisch *nl*.
. Gib in das Feld *Name* den niederländischen Namen des Merkmals ein.
. Wähle aus der Dropdown-Liste im Feld *Merkmaltyp* die Option *Text*.
. Trage in der Zeile *bol.com-Merkmal* das bol.com-Merkmal ein, wie aus der Datamodel-Datei in der Spalte *Attribute name* entnommen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

*bol_fulfillment* ist ein Pflichtfeld für den Angebotsexport. Dabei gibst du an, ob der Artikel direkt von dir oder von bol.com versendet wird. Trage dazu in der Zeile *bol.com-Merkmal* das bol.com-Merkmal *bol_filfillment* ein.

Wenn du gebrauchte Artikel über bol.com verkaufen möchtest, musst du den gebrauchten Zustand der Artikel über das Merkmal *bol_used* angeben. Trage dazu in der Zeile *bol.com-Merkmal* das bol.com-Merkmal *bol_used* ein.


[#500]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft bol.com einen Verkaufspreis festzulegen. Dieser Preis wird auf bol.com angezeigt.

[.instruction]
Verkaufspreis für bol.com festlegen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Aktiviere die Herkunft *bol.com*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[#600]
== Artikelexport einrichten

In diesem Kapitel wird beschrieben, wie du deine Artikel zu bol.com überträgst. Artikel werden über den elastischen Export zu bol.com übertragen. Zunächst legst du das Datenformat *BolItemExport* an und übermittelst im Anschluss die Datei zu bol.com.

Folgende Pflichtfelder müssen für den Artikelexport mitgegeben werden:

* EAN
* SKU
* Name
* Kategorien
* Artikelbeschreibung
* Bild
* Hersteller

[.instruction]
Artikelexport einrichten:

. Öffne das Menü *Daten » Elastischer Export*.
. Klicke auf *Neuer Export*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#einstellungen-artikelexport-bol>>.
. Nimm weitere Einstellungen für Artikelfilter und Formateinstellungen vor. Beachte dazu die Erläuterungen in Tabelle 2 auf der Handbuchseite <<daten/daten-exportieren/elastischer-export#300, Elastischer Export>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Eine ID für das Exportformat wird vergeben und das Exportformat erscheint in der Übersicht *Exporte*. +
→ Klicke im Menü *Daten » Elastischer Export » Tab: Exporte* auf *Herunterladen* (Pfeil-Symbol), um die eben erstellte Datei herunterzuladen.

[[einstellungen-artikelexport-bol]]
.Einstellungen für Artikelexport
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

| *Name*
|Name eingeben. Unter diesem Namen erscheint das Exportformat in der Übersicht im Tab *Exporte*.

| *Typ*
|Typ *Artikel* aus der Dropdown-Liste wählen.

| *Format*
|Format *BolItemExport* für den Artikelexport aus der Dropdown-Liste wählen.

| *Limit*
|Zahl eingeben. Wenn mehr als 10000 Datensätze an bol.com übertragen werden sollen, wird die Ausgabedatei für 24 Stunden nicht noch einmal neu generiert, um Ressourcen zu sparen.

| *Bereitstellung*
| *FTPS* wählen.

| *Dateiname*, +
*Server*, +
*Port*, +
*Benutzername*, +
*Passwort*, +
*Pfad*
|Parameter eingeben. Die Zugangsdaten für den Server inklusive Passwort und Benutzername werden von bol.com zur Verfügung gestellt. Der Dateiname hat den Aufbau &lt;SellerID&gt;.txt. Die Datei muss im Ordner */SQUARE/feed* gespeichert werden. +

| *Übertragung*
| *Täglich* wählen, da bol.com nur maximal 4 Exporte pro Tag zulässt.
|====


[#650]
== Zahlungsart aktivieren

:paymentmethod: Bol.com
:folder: International

include::_textblocks/instructions/zahlungsart_aktivieren.adoc[tags=!real-name;!real-client]

[#700]
== Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an bol.com zu senden, nachdem ein Warenausgang gebucht wurde.

:table-event-procedure: <<#ereignisaktion-versandbestätigung-bol>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-versandbestätigung-bol]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an bol.com
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsänderung: Warenausgang gebucht*
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *bol.com*

| *Aktion*
| *Versand &gt; Versandbestätigung an bol.com senden*
|
|====


[#800]
== Retourenstatus automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um bol.com automatisch über den Status einer Retoure zu informieren. Bei Retouren muss ein Status an bol.com übertragen werden. Ab API-Version 3.0 können folgende Retourenstatus an bol.com übertragen werden:

////
API-Version 2 (veraltet)

* Repariert oder ersetzt (v2)
////

* *Retoure erhalten (v4)* +
  ** bisher *Retoure erhalten (v2)*
* *Artikel wird umgetauscht (v4)*
* *Retoure entspricht nicht den Anforderungen (v4)* +
  ** bisher *Retoure unvollständig (v2)*
* *Artikel muss repariert werden (v4)*
* *Kunde behält Ware (v4)* +
  ** bisher *Rückerstattung ohne Rücksendung (v2)*
* *Retoure in Rücksprache mit Kunde angenommen (v4)*

:table-event-procedure: <<#ereignisaktion-retourenstatus-bol>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-retourenstatus-bol]]
.Ereignisaktion zum automatischen Senden von Retourenstatus an bol.com
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Neue Retoure*
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Retoure*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *bol.com*

| *Aktion*
| *Auftrag &gt; Retourenstatus an bol.com senden*
|Wähle einen Status.
|====


[#900]
== Stornierungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um bol.com automatisch über Stornierungen zu informieren. Bei Stornierungen muss ein Grund für die Stornierung an bol.com übertragen werden. Erstelle im Menü *Einrichtung » Aufträge » Auftragsstatus* ggf. zusätzliche Auftragsstatus. Ab API-Version 3.0 können folgende Stornierungsgründe an bol.com übertragen werden:

* *Nicht vorrätig (v3)* +
  ** bisher *Ausverkauft (v2)*
* *Stornierung von Kunde angefragt (v3)*
  ** bisher *Stornierung durch Kunden (v2)*
* *Artikel in schlechtem Zustand (v3)*
* *Höhere Versandkosten (v3)*
* *Falscher Preis (v3)*
* *Nicht rechtzeitig lieferbar (v3)*
* *Keine Garantie durch bol.com (v3)*
* *Artikel doppelt bestellt (v3)*
* *Artikel züruckbehalten (v3)*
* *Technisches Problem (v3)*
* *Artikel nicht auffindbar (v3)*
* *Sonstiges (v3)*

:table-event-procedure: <<#ereignisaktion-stornierungen-bol>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-stornierungen-bol]]
.Ereignisaktion zum automatischen Senden von Stornierungen an bol.com
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Statuswechsel: [8.1] Storniert durch Kunden*
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *bol.com*

| *Aktion*
| *Auftrag &gt; Stornierung an bol.com senden*
| *Stornierung durch Kunden*
|====


[#800]
== bol.com über direkte Retouren informieren

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um bol.com automatisch über Retouren zu informieren, die Kund*innen direkt an dich zurückgesendet haben und die Retoure vorher nicht bei bol.com angemeldet haben. Bei Retouren muss ein Status an bol.com übertragen werden. Ab API-Version 3.0 können folgende Retourenstatus an bol.com übertragen werden:

* Retoure erhalten (v4)
* Artikel wird umgetauscht (v4)
* Retoure entspricht nicht den Anforderungen (v4)
* Artikel muss repariert werden (v4)
* Kunde behält Ware (v4)
* Retoure in Rücksprache mit Kunde angenommen (v4)

:table-event-procedure: <<#ereignisaktion-retouren-bol>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-retouren-bol]]
.Ereignisaktion, um bol.com über Retouren zu informieren
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Statuswechsel: [9.5] Gutschrift angelegt*
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Retoure*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *bol.com*

| *Aktion*
| *Auftrag &gt; Retoure bei bol.com anlegen*
|Wähle einen Status.
|====


[#1000]
== Log abrufen

:marktplatz: bol.com
:identifikator: bol.com

include::_textblocks/instructions/logs_abrufen.adoc[]

Nutze die folgenden Referenztypen und Referenzwerte, um die Suchergebnisse zu filtern.

[[tabelle-referenztypen]]
.Referenztypen und Referenzwerte für bol.com
[cols="1,3,3"]
|====
|Referenztyp |Erläuterung |Referenzwerte

| *action*
|Filtert nach Ereignissen.
|Wähle einen Referenzwert, um nach bestimmten Ereignissen zu suchen. +
*shippingConfirmation* = Versandbestätigungen +
*orderImport* = Auftragsimport
|====


[#1100]
== FAQ

[#1200]
=== Voraussetzungen für das Einstellen von Angeboten auf bol.com

===== Welche Einstellungen muss ich an einer Variante vornehmen, um sie als Angebot auf bol.com einzustellen?

[.indented]
Damit deine Varianten als Angebote auf bol.com gelistet werden können, musst du die folgenden Einstellungen an der Varianten pflegen:

* *EAN* oder *ISBN* an der Variante speichern: Im Menü *Einrichtung » Artikel » Barcode* muss eine *EAN* oder *ISBN* eingerichtet und mit der Herkunft *bol.com* verknüpft sein. Außerdem muss die *EAN* oder *ISBN* im Tab *Einstellungen* einer Variante im Bereich *Barcode* hinzugefügt werden.
* *Verkaufspreis* für bol.com: Der <<Verkaufspreis festlegen, Verkaufspreis>> muss im Menü *Einrichtung » Artikel » Verkaufspreise* für Herkunft *bol.com* aktiviert sein und im Tab *Einstellungen* einer Variante im Bereich *Verkaufspreise* hinzugefügt werden.
* *Verfügbarkeit:* Im Tab *Verfügbarkeit* einer Variante müssen im Bereich *Märkte* die Marktplatzverfügbarkeiten *bol.com* oder *bol.com FBB* hinzugefügt werden. Wähle die Herkunft *bol.com*, wenn du deine Artikel selbst versendest. Wenn der Versand durch bol.com erfolgt, wähle die Herkunft *bol.com FBB*.
