= Cdiscount
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Cdiscount, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Cdiscount in deinem plentymarkets System ein.
:position: 40
:url: maerkte/cdiscount
:id: EICIMBX
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Cdiscount war der erste elektronische Marktplatz Frankreichs und ist noch heute einer der beliebtesten und am meisten genutzten französischen Online-Verkaufsplattformen. Um Artikel auf Cdiscount anzubieten, muss der Artikelkatalog komplett auf Französisch vorliegen.

[#100]
== Bei Cdiscount registrieren

Bevor du Cdiscount in plentymarkets einrichten kannst, musst du dich bei Cdiscount registrieren. Fülle das link:https://seller.cdiscount.com/Account_creation.html[Registrierungsformular^] aus und übermittele deine Daten an Cdiscount. Ein Support-Mitarbeiter des Marktplatzes wird dich kontaktieren, um die Registrierung zu verifizieren.

Bevor du die hier hinterlegten Daten in deinem plentymarkets System speicherst, ändere dein API-Passwort. Ein neues Passwort wird dir in der Mailbox deines Händler-Backends zugesandt.

[#200]
== Cdiscount in plentymarkets einrichten

Nachdem du dich bei Cdiscount registriert hast, verwende die dort hinterlegten Daten, um den Marktplatz in plentymarkets einzurichten. Gehe dazu wie im Folgenden beschrieben vor.

[IMPORTANT]
.Zugangsdaten
====
Verwende für die Einrichtung die API-Zugangsdaten. Die API-Zugangsdaten entsprechen nicht deinen Zugangsdaten zum Händler-Backend von Cdiscount. Der Benutzername kann im Händler-Backend von Cdiscount eingesehen werden und das Passwort kann dort generiert oder angepasst werden.
====

[.instruction]
Cdiscount in plentymarkets einrichten:

. Öffne das Menü *Einrichtung » Märkte » Cdiscount.com » Tab: Einstellungen*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<grundeinstellungen-cdiscount>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[IMPORTANT]
.Zugangsdaten
====
Verwende für die Einrichtung die API-Zugangsdaten (Benutzername und Passwort). Der Benutzername hat das Suffix api. Die Login-Zugangsdaten sind dagegen zum Login in das Backend bei Cdiscount bestimmt.
====

[[grundeinstellungen-cdiscount]]
.Grundeinstellungen des Marktplatzes Cdiscount
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Produkterstellung anfordern*
|Aktivieren, um den automatischen Bestandsabgleich und Auftragsimport über die API-Schnittstelle zu aktivieren. Wenn die Option *Produkterstellung anfordern* nicht aktiviert wurde, werden lediglich Angebote zu bereits bestehenden Artikeln auf Cdiscount generiert.

|*Preise und Bestände aktualisieren und Auftragsimport aktivieren*
|Aktivieren, um den Artikelkatalog über die CSV-Schnittstelle zu übertragen. Der Bestandsabgleich wird weiterhin automatisch über die API-Schnittstelle übertragen. +
Ist diese Einstellung zusammen mit der Einstellung *Produkterstellung anfordern* aktiviert, findet der automatische Datenaustausch nur über die API-Schnittstelle statt.

2+|*Vertriebspartner-Information*

|*Firmenname*
|Firmenname eingeben, wie bei Cdiscount registriert (optional).

|*API-Benutzername*
|API-Benutzername eingeben, wie von Cdiscount erhalten.

|*API-Passwort*
|API-Passwort eingeben, wie von Cdiscount erhalten.

2+|*Auftragseinstellungen*

|*Cdiscount C Logistique-Auftragsstatus*
|Status für C Logistique-Aufträge. *Status [7] Warenausgang gebucht* ist hier standardmäßig voreingestellt. Dabei wird aber kein Bestand vom Lager abgezogen. Für zukünftige Auftragsimporte kann der Status nach Belieben geändert werden. Dabei ist jedoch zu beachten, dass sobald der Auftrag einmal in Status 7 war, der Auftrag dann nicht mehr in einen kleineren Status geschoben werden kann.

2+|*Artikeleinstellungen*

|*Artikelname*
|Wählen, welches Feld an Cdiscount als Artikelname übertragen wird.

|*Artikelkurzbeschreibung*
|Wählen, welches Feld an Cdiscount als Artikelkurzbeschreibung übertragen wird.

|*Artikelbeschreibung*
|Wählen, welches Feld an Cdiscount als Artikelbeschreibung übertragen wird. +
HTML-Formatierung ist in der Artikelbeschreibung nicht erlaubt und wird beim Artikelexport entfernt.

|*Artikel-Marketing-Beschreibung*
|Wählen, welcher Text als Marketing-Beschreibung übertragen werden soll oder *Nicht übertragen* wählen. +
Die Artikel-Marketing-Beschreibung darf HTML-Formatierung enthalten.

|*Variantenmaße übertragen*
|Häkchen setzen, wenn die Variantenmaße übertragen werden sollen.

|*Bestandsmenge für Artikel ohne Bestandsbeschränkung und ohne positiven Nettowarenbestand*
|Wert eingeben. Die eingegebene Bestandsmenge wird übertragen, wenn der Artikel keine Bestandsbeschränkung und keinen positiven Nettowarenbestand hat.

|*Lager*
|Wählen, welches Lager verwendet werden soll. Ein Lager, mehrere Lager oder *Summe aus allen Lagern* wählen.

|*Mindestpreis*
|Mindestpreis für einen Artikel wählen. +
*Wichtig:* Der Mindestpreis muss der am Artikel gespeicherte Aktionspreis sein.

2+|*Versandvorbereitungszeit (in Tagen)*

|*Standard-Versandvorbereitungszeit*
|*Pflichtfeld* +
Standard-Versandvorbereitungszeit in Tagen eingeben. Der hier eingegebene Wert wird zu Cdiscount übertragen und von Cdiscount um einen Wert auf Basis der Versandart erhöht. +
*Wichtig:* Nur Werte von 1-10 eingeben.

|*Verfügbarkeit 1-10*
|Verfügbarkeit von 1-10 eingeben. Die Verfügbarkeit entspricht der Variantenverfügbarkeit im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Bereich *Verfügbarkeit*. Der hier eingegebene Wert wird zu Cdiscount übertragen und von Cdiscount um einen Wert auf Basis der Versandart erhöht. +
Wenn hier kein Wert eingegeben wird, wird die *Standard-Versandvorbereitungszeit* zu Cdiscount übertragen.

2+|*Versandkosten*

|*Versandkosten aus der Versandkostenberechnung übernehmen*
|*Konfiguration 1* oder *Konfiguration 2* sowie *Zahlungsart* wählen. Die Standardversandkosten werden mit dieser Konfiguration an Cdiscount übertragen.  +
Die hier wählbaren Optionen sind die im Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versandkosten berechnen* gewählten Einstellungen für Konfiguration 1 und Konfiguration 2.

|*Versandkosten überschreiben*
|Festpreis für den Versand eingeben. Die hier eingegebene Versandkosten werden anstatt der am Artikel hinterlegten Versandkosten an Cdiscount übermittelt.

|*Artikel-ID für die Ratengebühr*
|ID des Artikels, über den Kund*innen ggf. die Gebühr für den Ratenkauf, die Cdiscount erhebt, in Rechnung gestellt wird. Dazu einen Artikel in plentymarkets erstellen und die ID hier eingeben.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierten Funktionen bereit:

* Täglicher Artikelexport
* Stündlicher Bestandsabgleich
* Stündlicher Auftragsimport

Beim stündlichen Auftragsimport werden zunächst keine Rechnungs- und Lieferdaten von Cdiscount übermittelt. Der Auftrag bleibt solange in Status [3]. Es kann bis zu 48 Stunden dauern, bis die Rechnungs- und Lieferdaten übermittelt werden, da Cdiscount in dieser Zeit eine Bonitätsprüfung für Endkund*innen durchführt.

[#250]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit Cdiscount verknüpfen kannst, muss im Menü *Einrichtung » Aufträge » Auftragsherkunft* die Auftragsherkunft Cdiscount aktiviert werden.

[.instruction]
Auftragsherkunft für Cdiscount aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Setze bei *Cdiscount* ein Häkchen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die du auf Cdiscount verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Cdiscount einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *Cdiscount*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Artikel ist auf Cdiscount verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

Die Verfügbarkeit für mehrere Varianten kann entweder über die link:https://knowledge.plentymarkets.com/artikel/artikel-verwalten#330[Varianten-Gruppenfunktion^] oder die link:https://knowledge.plentymarkets.com/artikel/artikel-verwalten#330[Stapelverarbeitung^] bearbeitet werden.

[#350]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu.

[IMPORTANT]
.Automatische SKU-Generierung
====
Wenn im Menü *Einrichtung » Märkte » Cdiscount.com » Tab: Einstellungen* die Einstellung *Produkterstellung anfordern* aktiv ist, werden beim nächtlichen Übertragungsprozess für jede Variante, die exportiert wird automatisch eine SKU generiert, die der Varianten-ID entspricht.
====

[IMPORTANT]
.SKUs von bereits existierenden Produkten
====
Wenn bereits Angebote/Produkte auf Cdiscount manuell oder über andere Softwaresysteme angelegt wurden, dann können diese Produkte mit Varianten in plentymarkets verknüpft werden. Dazu muss in plentymarkets die Kennzeichnung als SKU hinterlegt werden, die bei Cdiscount im Händler-Backend bei dem jeweiligen Angebot/Produkt als *Your reference* zu finden ist.
====

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Cdiscount.com*.
. Gib die SKU ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die SKU wird gespeichert und angezeigt.

[#400]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft Cdiscout einen Verkaufspreis festzulegen. Dieser Preis wird auf Cdiscount angezeigt.

[.instruction]
Verkaufspreis für Cdiscount festlegen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *Cdiscount*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

<<artikel/artikel-verwalten#240, Verknüpfe>> den Verkaufspreis im Anschluss mit den gewünschten Varianten, falls noch nicht verknüpft.

[#450]
== Barcode festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft Cdiscount einen Barcode festzulegen. Dieser Barcode wird für die Variante  zu Cdiscount übertragen. Der Barcode muss vom Typ GTIN 13 sein.

[.instruction]
Barcode für Cdiscount festlegen:

. Öffne das Menü *Einrichtung » Artikel » Barcode » Barcode öffnen*.
. Setze ein Häkchen bei der Herkunft *Cdiscount*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

<<artikel/artikel-verwalten#250, Verknüpfe>> den Barcode im Anschluss mit den gewünschten Varianten, falls noch nicht verknüpft.

[#500]
== Kategorien verknüpfen

Um deine Kategorien mit denen von Cdiscount zu verknüpfen, lade zunächst die Kategorieliste von Cdiscount herunter. Verknüpfe dann deine eigenen Kategorien mit den passenden Cdiscount-Kategorien.

[.instruction]
Kategorieliste herunterladen:

. Öffne das Menü *Einrichtung » Märkte » Cdiscount.com » Tab: Kategorieliste*.
. Klicke auf das Zahnrad *Kategorieliste aktualisieren*. +
→ Die Kategorieliste wird mit Code und Kategorienamen unten angezeigt.

Die hier angezeigten Codes benötigst du, um deine Kategorien mit denen von Cdiscount zu verknüpfen. Gehe dazu wie folgt vor.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » Cdiscount.com » Tab: Kategorieverknüpfung*.
. Gib unter *Kategorieverknüpfung* den Code der zur Webshop-Kategorie passenden Cdiscount-Kategorie ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#600]
== Attribute verknüpfen

Wenn du <<artikel/artikel-verwalten#390, Attribute>> im plentymarkets System erstellt hast, müssen diese Attribute mit Cdiscount verknüpft werden. Nachfolgend wird beschrieben, wie du das Attribut Farbe mit Cdiscount verknüpfst. Verknüpfe weitere Attribute auf die gleiche Weise.

[.instruction]
Attribute verknüpfen:

. Öffne das Menü *Einrichtung » Artikel » Attribute*. +
→ Eine Übersicht aller erstellten Attribute wird geöffnet.
. Klappe das Attribut *Farbe* auf.
. Wechsele in das Tab *Marktplatzvariation*.
. Wähle in der Dropdown-Liste *Marktplatz* die Option *Cdiscount.com*. +
→ Eine zusätzliche Dropdown-Liste *Cdiscount* wird angezeigt.
. Wähle in der Dropdown-Liste *Cdiscount.com* das Attribut *Farbe*.
. Gib die zu deinen Attributwerten passenden Cdiscount-Attributwerte im Bereich Marktplatzvariation ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#700]
== Merkmale erstellen

Als nächstes erstellst du <<artikel/artikel-verwalten#480, Merkmale>> und verknüpfst die erstellten Merkmale mit den Cdiscount-Merkmalen. Beachte, dass deine Merkmale hierfür auf Französisch erstellt sein müssen.

[.instruction]
Merkmal erstellen:

. Öffne in das Menü *Einrichtung » Artikel » Merkmale*.
. Öffne das Tab *Neues Merkmal*.
. Gib unter *Name (intern)* einen Namen für das Merkmal ein.
. Wähle aus der Dropdown-Liste *Sprache* für Französisch *fr*.
. Gib in das Feld *Name* den französischen Namen des Merkmals ein.
. Wähle aus der Dropdown-Liste im Feld *Merkmaltyp* die Option *Text*.
. Wähle aus der Dropdown-Liste im Feld *Cdiscount.com-Merkmal* das Cdiscount-Merkmal.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#800]
== Hersteller verknüpfen

Erstelle nun Herstellerverknüpfungen, damit deine Artikel auf Cdiscount zum Verkauf angezeigt werden. Lade zunächst die Herstellerliste von Cdiscount herunter und verknüpfe dann deine eigenen Hersteller mit den passenden Cdiscount-Herstellern, indem du die Cdiscount-Hersteller-ID im System hinterlegst. Dabei entspricht die Cdiscount-Hersteller-ID dem Namen des Herstellers.

[.instruction]
Herstellerliste herunterladen:

. Öffne das Menü *Einrichtung » Märkte » Cdiscount.com » Tab: Herstellerliste*.
. Klicke auf *Herstellerliste aktualisieren*. +
→ Die Herstellerliste wird mit Code und Herstellernamen unten angezeigt.
. Markiere und kopiere den Hersteller in die Zwischenablage.
. *Tipp:* Lade die Herstellerliste als CSV-Datei herunter. Diese Datei kannst du gezielt nach Herstellern durchsuchen. +
Klicke dazu im Menü *Einrichtung » Märkte » Cdiscount.com » Tab: Herstellerliste* auf *Herstellerliste als CSV Datei herunterladen*.

Gehe nun wie folgt vor, um den Hersteller zu verknüpfen.

[.instruction]
Hersteller verknüpfen:

. Öffne das Menü *Einrichtung » Artikel » Hersteller*.
. Öffne den Hersteller, den du mit Cdiscount verknüpfen möchtest.
. Füge den Namen des Herstellers aus der Zwischenablage in das Feld *Cdiscount.com-ID* ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#900]
== Zahlungsart aktivieren

Aktiviere die <<payment/zahlungsarten-verwalten#, Zahlungsart>> *Cdiscount*, wie im Folgenden beschrieben.

[.instruction]
Cdiscount-Zahlungsarten aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
. Klicke auf *Cdiscount*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-zahlungsart-cdiscount>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[einstellungen-zahlungsart-cdiscount]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Sprache*
| Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn Käufer*innen im Webshop die Sprache wählen.

|*Name*
| Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
| Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
| Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
| Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in deinem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
| Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
| Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
| Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben. +
Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *Einrichtung » CRM » Kundenklassen* aktivierst oder deaktivierst du *erlaubte Zahlungsarten*. +
Weitere Informationen findest du im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#950]
== Datenaustausch einrichten

Um die Schnittstelle so einzurichten, dass der Artikelexport, der Bestandsabgleich und der Auftragsimport funktionieren, sind mindestens die Eingaben gemäß der folgenden Tabelle notwendig.

[IMPORTANT]
.Produkterstellung auf Cdiscount
====
Die Produkterstellung dient zur Anfrage der Aufnahme eines neuen Produktes in die Produktdatenbank von Cdiscount. Sobald eines Ihrer Produkte durch Cdiscount freigegeben und in die Produktdatenbank aufgenommen wurde, kannst du die Produktdaten für gewöhnlich nicht mehr weiter bearbeiten. Prüfe deshalb vor der Übertragung des Produktes, dass du wirklich alle Daten gepflegt hast, die für den erfolgreichen Verkauf wichtig sind. Die Checkliste dient lediglich zur Auflistung der Mindestanforderungen für die Produkterstellung.
====

[IMPORTANT]
.Angebotserstellung auf Cdiscount
====
Auf Cdiscount wird jedes angelegte Produkt in einer Datenbank abgespeichert. Jedes Produkt kann anhand mindestens einer EAN identifiziert werden. Die Kennzeichnung der Produkte mit EANs ermöglicht es Händlern, Angebote zu diesen Produkten zur Verfügung zu stellen. Im Vergleich zur vorherigen Produkterstellung ist der Einrichtungsaufwand wesentlich geringer und erleichtert den Einstieg bei Cdiscount. +
Sowohl die Erstellung als auch die Aktualisierung (Bestandsabgleich) der Angebote werden über eine Datei gesteuert. +
Die folgenden Checkliste listet die mindestens notwendigen Einstellungen auf, damit ein Artikel in dieser Datei übertragen wird.
====

[[pflichteinstellungen-cdiscount]]
.Pflichteinstellungen für Cdiscount
[cols="1,3"]
|====
| Einstellungsbereich  | Einstellungen

2+|*Angebotserstellung / Bestandsabgleich*

| Grundeinstellungen des Marktplatzes
a|
* *Preise und Bestände aktualisieren und Auftragsimport aktivieren* ist aktiviert.
* *API-Benutzername* ist eingetragen.
* *API-Passwort* ist eingetragen.
* *Versandvorbereitungszeit (in Tagen)* ist gesetzt.
* *Versandkosten aus der Versandkostenberechnung übernehmen* oder *Versandkosten überschreiben* ist eingerichtet.

| Einstellungen der Variante
a|
*  Die Variante ist *aktiv*
*  Die *Verfügbarkeit* der Variante wurde eingestellt.
*  Ein *Verkaufspreis* ist angelegt und verknüpft.
*  Ein *Barcode* ist angelegt und verknüpft.
*  Eine *SKU* ist festgelegt worden.

2+|*Produkterstellung*

| Grundeinstellungen des Marktplatzes
a|
* *Preise und Bestände aktualisieren und Auftragsimport aktivieren* ist aktiviert.
* *API-Benutzername* ist eingetragen.
* *API-Passwort* ist eingetragen.

| Einstellungen des Artikels
a|
*  Die *Artikeltexte* sind in Französisch gepflegt.
*  Ein *Hersteller* ist am Artikel hinterlegt und mit Cdiscount verknüpft worden.

| Einstellungen der Variante bei Einzelartikeln
a|
*  Die Variante ist *aktiv*
*  Die *Verfügbarkeit* der Variante wurde eingestellt.
*  Ein *Barcode* ist angelegt und verknüpft.
*  Eine *SKU* ist festgelegt worden.
*  Mindestens eine mit Cdiscount verknüpfte *Kategorie* ist am Artikel hinterlegt.
*  Mindestens eine der *Kategorien*, die mit Cdiscount verknüpft ist, ist für den Standard-Mandanten freigegeben.
*  Mindestens ein *Bild* ist am Artikel hinterlegt und für Cdiscount freigegeben

| Zusätzliche Einstellungen der Variante bei Variantenartikeln
a|
*  Die *Attribute* der Variante sind mit Cdiscount verknüpft.

2+|*Auftragsimport*

| Grundeinstellungen des Marktplatzes
a|
* *Preise und Bestände aktualisieren und Auftragsimport aktivieren* ist aktiviert.
* *API-Benutzername* ist eingetragen.
* *API-Passwort* ist eingetragen.

| Zahlungsarten
a|
*  Die *Zahlungsart Cdiscount* ist aktiviert.

| Einstellungen der Variante
a|
*  Eine *SKU* ist festgelegt worden.

|====

[#1000]
=== Artikelkatalog und Bestandsabgleich herunterladen

Im Tab *Archiv* lädst du den Artikelkatalog oder den Bestandsabgleich als ZIP-Datei herunter. Das Herunterladen der ZIP-Dateien ist nötig, damit du die Dateien deinem Cdiscount-Ansprechspartner übermitteln kannst, wenn es z.B. zu Störungen beim Importieren kommt. So kann Cdiscount den Sachverhalt schneller prüfen und die Störungen beseitigen.

[.instruction]
Bestandsabgleich an Cdiscount übermitteln:

. Öffne das Menü *Einrichtung » Märkte » Cdiscount.com » Tab: Archiv*.
. Klicke auf *Bestandsabgleich herunterladen*.
. Speichere die Datei auf deiner Festplatte, um sie ggf. an Cdiscount per E-Mail zu senden.

[#1100]
=== Artikelkatalog über CSV-Datei exportieren

Da es in seltenen Fällen zu Problemen beim automatischen Artikelexport kommen kann, kannst du deinen auf französisch hinterlegten Artikelkatalog unter <<daten/daten-exportieren/elastischer-export#300, Daten » Elastischer Export>> auch als CSV-Datei an Cdiscount exportieren. Nachdem du alle dafür notwendigen Einstellungen wie unten beschrieben gespeichert hast, musst du die komplette URL kopieren und an Cdiscount übermitteln. Bestände werden weiterhin stündlich automatisch abgeglichen.

[.instruction]
Export erstellen:

. Öffne das Menü *Einrichtung » Märkte » Cdiscount.com » Tab: Einstellungen*.
. Aktiviere die Option *Preise und Bestände aktualisieren und Auftragsimport aktivieren*. +
*Wichtig:* Die Option *Produkterstellung anfordern* darf nicht aktiviert sein, da Daten sonst automatisch über die API-Schnittstelle übertragen werden.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wechsele in das Menü *Daten » Elastischer Export*.
. Öffne das Tab *Neuer Export*.
. Wähle *Cdiscount.com* aus der Dropdown-Liste *Datenformat*.
. Gib einen Namen für den Export ein.
. Nimm die Einstellungen gemäß der Handbuchseite <<daten/daten-exportieren/elastischer-export#300, Elastischer Export>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Export erscheint als Unterordner im Tab *Exporte* und die URL wird erstellt.
. Öffne das Tab *Exporte* und dort den Unterordner *Cdiscount.com*.
. Kopiere die *URL* und übermitteln Sie die URL an Cdiscount.

[NOTE]
.Merkmale für CSV-Datei verknüpfen
====
Wenn du deinen Artikelkatalog über eine CSV-Datei an Cdiscount übermittelst, müssen im Menü <<artikel/artikel-verwalten#480, Einrichtung » Artikel » Merkmale>> die Merkmale *Geschlecht*, *Hauptfarbe*, *Hinweis*, *Kommentar*, *Marketing-Beschreibung*, *Publikum* und *Sport* verknüpft werden.
====

[#1200]
== Retouren automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Retouren automatisch an Cdiscount zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-retouren-cdiscount>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-retouren-cdiscount>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-retouren-cdiscount]]
.Ereignisaktion zum automatischen Senden von Retouren an Cdiscount
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*CDiscount.fr*

|*Aktion*
|*Retoure &gt; Retoure an Cdiscount senden*
|
|====

[#1300]
== Auftragsstatus automatisch aktualisieren

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um den Auftragsstatus bei Cdiscount automatisch zu aktualisieren, wenn bestimmte Ereignisse eintreten. Du hast die Möglichkeit, Aufträge bei Cdiscount per Ereignisaktion automatisch in die
folgenden Status zu setzen:

* Vom Händler abgelehnt
* Vom Händler versendet
* Versand vom Händler verweigert

Beispielhaft wird eine Ereignisaktion beschrieben, mit der du Cdiscount darüber informierst, dass du die bestellte Ware verschickt hast. Andere Ereignisaktionen richtest du auf die gleiche Weise ein.

Damit die Versandbestätigung erfolgreich übermittelt wird, müssen folgende Daten am Auftrag gepflegt sein:

* Versanddienstleister
* Warenausgang muss gebucht sein
* externe Auftragsnummer

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-auftragsstatus-cdiscount>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-auftragsstatus-cdiscount>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-auftragsstatus-cdiscount]]
.Ereignisaktion zum automatischen Aktualisieren von Auftragsstatus bei Cdiscount
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel &gt; Warenausgang gebucht* +
icon:map-signs[] *_Oder:_* *Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*CDiscount.fr*

|*Aktion*
|*Auftrag &gt; Auftragsänderung an Cdiscount melden*
|*Vom Händler versendet*
|====

[IMPORTANT]
.Status: Vom Händler akzeptiert
====
Der Status *Vom Händler akzeptiert* muss nicht per Ereignisaktion verschickt werden. Jeder Auftragseingang löst eine automatische Benachrichtigung über diesen Status an Cdiscount aus.
====

[#1400]
== API-Log abrufen

Im Menü *Daten » API-Log* findest du eine Historie über Vorgänge, die über die Cdiscount-Schnittstelle ausgeführt wurden. Das Format *Cdiscount.com* steht Ihnen für Cdiscount zur Verfügung.

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle das Format *Cdiscount.com* aus der Dropdown-Liste *Vorgang*.
. Wähle ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wähle die Anzahl der Ergebnisse pro Seite.
. Klicke auf *Suchen*, um die Ergebnisse anzuzeigen.
