= Check24
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Check24, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Check24 in deinem plentymarkets System ein.
:position: 50
:url: maerkte/check24
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Auf dieser Handbuchseite findest du Informationen zur Einrichtung des Marktplatzes Check24 in plentymarkets. Du erfährst, wie du die Schnittstelle einrichtest, deine Artikel zu Check24 exportierst und Verkaufspreise festlegst.

[#100]
== Bei Check24 registrieren

Bevor du Check24 in plentymarkets einrichtest, musst du dich bei link:https://merchantcenter.check24.de/landing/partner_info[Check24^] registrieren.

[#200]
== Check24 in plentymarkets einrichten

Nimm die folgenden Einstellungen in plentymarkets vor, um die Schnittstelle zu Check24 einzurichten.

[.instruction]
Check24 einrichten:

. Öffne das Menü *Einrichtung » Märkte » Check24*.
. Aktiviere den automatischen Datenaustausch.
. Gib als Benutzernamen deinen Partnerlogin für den FTP-Zugang ein.
. Gib dein Passwort für den FTP-Zugang ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* stündlicher Auftragsabgleich

[#250]
=== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit Check24 verknüpfen kannst, muss im Menü *Einrichtung » Aufträge » Auftragsherkunft* die Auftragsherkunft Check24 aktiviert werden.

[.instruction]
Auftragsherkunft für Check24 aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Setze bei *Check24* ein Häkchen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#300]
=== Artikelverfügbarkeit einstellen

Artikel, die du auf Check24 verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Check24 einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *Check24*.
. Aktiviere die Option *Web-API*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

[#400]
===  SKU festlegen

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Check24*.
. Wähle das dazugehörige Marktplatzkonto.
. Gib die SKU ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die SKU wird gespeichert und angezeigt.

[#500]
=== Artikelexport einrichten

In diesem Kapitel wird beschrieben, wie du deine Artikel zu Check24 überträgst. Artikel werden über den elastischen Export mit dem Datenformat Check24DE zu Check24 exportiert. Dafür müssen zuvor die Plugins *ElasticExport* und *ElasticExportCheck24DE* installiert worden sein. Lege zunächst das Datenformat Check24DE an und übermittele im Anschluss die URL zu Check24.

[.instruction]
Artikelexport einrichten:

. Öffne das Menü *Daten » Elastischer Export*.
. Klicke auf *Neuer Export*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-artikelexport-check24>>.
. Nimm weitere Einstellungen für Artikelfilter und Formateinstellungen vor. Beachte dazu die Erläuterungen in Tabelle 2 auf der Handbuchseite <<daten/daten-exportieren/elastischer-export#300, Elastischer Export>>. +
  *_Tipp:_* Damit nur Artikel zu Check24 übertragen werden, die für Check24 aktiviert und im Tab *Verfügbarkeit* eines Artikels für den Marktplatz verfügbar sind, wähle den Artikelfilter *Aktiv* und den Artikelfilter *Märkte » Check24*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Eine ID für das Exportformat wird vergeben und das Exportformat erscheint in der Übersicht *Exporte*.

[[einstellungen-artikelexport-check24]]
.Einstellungen für Artikelexport
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

|*Name*
|Name eingeben. Unter diesem Namen erscheint das Exportformat in der Übersicht im Tab *Exporte*.

|*Typ*
|Typ *Artikel* aus der Dropdown-Liste wählen.

|*Format*
|Format *Check24DE* aus der Dropdown-Liste wählen.

|*Limit*
|Zahl eingeben. Wenn mehr als 10000 Datensätze an Check24 übertragen werden sollen, wird die Ausgabedatei für 24 Stunden nicht noch einmal neu generiert, um Ressourcen zu sparen.

|*Bereitstellung*
|*URL* wählen.

|*Token*, +
*URL*
|Wenn unter *Bereitstellung* die Option *URL* gewählt wurde, auf *Token generieren* klicken. Der Token wird dann automatisch eingetragen. Die URL wird automatisch eingetragen, wenn unter *Token* der Token generiert wurde. Diese URL an Check24 übergeben, damit die Artikel exportiert werden.
|====

[IMPORTANT]
.Exportinformationen
====
Wenn du eine oder mehrere Einstellungen änderst, musst du den neuen Link an Check24 übergeben.

Pro Export werden maximal 4000 Artikel exportiert. Wenn du mehr Artikel exportierst, wird automatisch ein zweiter Export ausgeführt. Um den zweiten Export anzuzeigen, setze den Parameter *&amp;Page* = im Export-Link auf *2*.

Technische Daten werden in der letzten Spalte der Exportdatei an Check24 übergeben.
====

[#600]
=== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft Check24 einen Verkaufspreis festzulegen. Dieser Preis wird auf Check24 angezeigt.

[.instruction]
Verkaufspreis für Check24 festlegen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *Check24*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#700]
=== Zahlungsart aktivieren

Aktiviere die <<payment/zahlungsarten-verwalten#, Zahlungsart>> *Check24*, wie im Folgenden beschrieben.

[.instruction]
Zahlungsart Check24 aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive anzeigen*.
. Klicke auf den Ordner *DE &gt; Check24*.  +
→ Die Einstellungen für die Check24-Zahlungsart werden angezeigt.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-zahlungsart-check24>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[einstellungen-zahlungsart-check24]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn Käufer*innen im Webshop die Sprache wählen.

|*Name*
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
|Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in deinem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig:* Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[#950]
== Auftragsimport

Beim stündlichen Auftragsimport wird der Auftrag automatisch in *Status [5] Freigabe Versand* gesetzt. Als Rechnungsadresse wird immer Check24 übermittelt. Die Adresse vom Kunden dient lediglich als Lieferadresse.

[#975]
== Versandbestätigungen senden

Zurzeit ist es über die Schnittstelle noch nicht möglich, Versandbestätigungen automatisch zu senden. Kontaktiere Check24, um automatische Versandbestätigungen einzurichten.

[#1000]
== API-Log abrufen

Im Menü *Daten » API-Log* findest du eine Historie über Vorgänge, die über die Check24-Schnittstelle ausgeführt wurden. Das Format *Check24OrderImportAdapter* steht dir für Check24 zur Verfügung.

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle das Format *Check24OrderImportAdapter* aus der Dropdown-Liste *Vorgang*.
. Wähle ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wähle die Anzahl der Ergebnisse pro Seite.
. Klicke auf *Suchen*, um die Ergebnisse anzuzeigen.
