= Check24
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Check24, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz Check24 in Ihrem plentymarkets System ein.
:position: 50

Auf dieser Handbuchseite finden Sie Informationen zur Einrichtung des Marktplatzes Check24 in plentymarkets. Sie erfahren, wie Sie die Schnittstelle einrichten, Ihre Artikel zu Check24 exportieren und Verkaufspreise festlegen.

[#100]
== Bei Check24 registrieren

Bevor Sie Check24 in plentymarkets einrichten, müssen Sie sich bei link:https://merchantcenter.check24.de/landing/partner_info[Check24^] registrieren.

[#200]
== Check24 in plentymarkets einrichten

Nehmen Sie die folgenden Einstellungen in plentymarkets vor, um die Schnittstelle zu Check24 einzurichten.

[.instruction]
Check24 einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Märkte » Check24*.
. Aktivieren Sie den automatischen Datenaustausch.
. Geben Sie als Benutzernamen Ihren Partnerlogin für den FTP-Zugang ein.
. Geben Sie Ihr Passwort für den FTP-Zugang ein.
. *Speichern* Sie die Einstellungen.

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* stündlicher Auftragsabgleich

[#250]
=== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit Check24 verknüpfen können, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft Check24 aktiviert werden.

[.instruction]
Auftragsherkunft für Check24 aktivieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setzen Sie bei *Check24* ein Häkchen.
. *Speichern* Sie die Einstellungen.

[#300]
=== Artikelverfügbarkeit einstellen

Artikel, die Sie auf Check24 verkaufen möchten, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Check24 einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktivieren Sie die Option *Check24*.
. Aktivieren Sie die Option *Web-API*.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

[#400]
===  SKU festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügen Sie marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechseln Sie in das Tab *Verfügbarkeit*.
.  Klicken Sie im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
.  Wählen Sie die Herkunft *Check24*.
.  Wählen Sie das dazugehörige Marktplatzkonto.
.  Geben Sie die SKU ein.
.  Klicken Sie auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#500]
=== Artikelexport einrichten

In diesem Kapitel wird beschrieben, wie Sie Ihre Artikel zu Check24 übertragen. Artikel werden über den elastischen Export mit dem Datenformat Check24DE zu Check24 exportiert. Dafür müssen zuvor die Plugins *ElasticExport* und *ElasticExportCheck24DE* installiert worden sein. Legen Sie zunächst das Datenformat Check24DE an und übermitteln im Anschluss die URL zu Check24.

[.instruction]
Artikelexport einrichten:

. Öffnen Sie das Menü *Daten » Elastischer Export*.
. Klicken Sie auf *Neuer Export*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<einstellungen-artikelexport-check24>>.
. Nehmen Sie weitere Einstellungen für Artikelfilter und Formateinstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 5 auf der Handbuchseite <<daten/export-import/daten-exportieren#60, Daten über dynamischen Export exportieren>>. +
  *_Tipp:_* Damit nur Artikel zu Check24 übertragen werden, die für Check24 aktiviert und im Tab *Verfügbarkeit* eines Artikels für den Marktplatz verfügbar sind, wählen Sie den Artikelfilter *Aktiv* und den Artikelfilter *Märkte » Check24*.
. *Speichern* Sie die Einstellungen. +
→ Eine ID für das Exportformat wird vergeben und das Exportformat erscheint in der Übersicht *Exporte*.

[[einstellungen-artikelexport-check24]]
.Einstellungen für Artikelexport
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

|*Name*
|Name eingeben. Unter diesem Namen erscheint das Exportformat in der Übersicht im Tab *Exporte*.

|*Typ*
|Typ aus der Dropdown-Liste wählen. Aktuell ist nur die Auswahl *Artikel* verfügbar. Weitere Auswahlmöglichkeiten folgen.

|*Format*
|Format *Check24DE* aus der Dropdown-Liste wählen.

|*Limit*
|Zahl eingeben. Wenn mehr als 10000 Datensätze an Check24 übertragen werden sollen, wird die Ausgabedatei für 24 Stunden nicht noch einmal neu generiert, um Ressourcen zu sparen.

|*Bereitstellung*
|*URL* wählen.

|*Token, +
URL*
|Wenn unter *Bereitstellung* die Option *URL* gewählt wurde, auf *Token generieren* klicken. Der Token wird dann automatisch eingetragen. Die URL wird automatisch eingetragen, wenn unter *Token* der Token generiert wurde. Diese URL an Check24 übergeben, damit die Artikel exportiert werden.
|====

[IMPORTANT]
.Exportinformationen
====
Wenn Sie eine oder mehrere Einstellungen ändern, müssen Sie den neuen Link an Check24 übergeben.

Pro Export werden maximal 4000 Artikel exportiert. Wenn Sie mehr Artikel exportieren, wird automatisch ein zweiter Export ausgeführt. Um den zweiten Export anzuzeigen, setzen Sie den Parameter *&amp;Page* = im Export-Link auf *2*.

Technische Daten werden in der letzten Spalte der Exportdatei an Check24 übergeben.
====

[#600]
=== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft Check24 einen Verkaufspreis festzulegen. Dieser Preis wird auf Check24 angezeigt.

[.instruction]
Verkaufspreis für Check24 festlegen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setzen Sie ein Häkchen bei der Herkunft *Check24*.
. *Speichern* Sie die Einstellungen.

[#950]
== Auftragsimport

Beim stündlichen Auftragsimport wird der Auftrag automatisch in *Status [5] Freigabe Versand* gesetzt. Als Rechnungsadresse wird immer Check24 übermittelt. Die Adresse vom Kunden dient lediglich als Lieferadresse.

[#1000]
== API-Log abrufen

Im Menü *Daten » API-Log* finden Sie eine Historie über Vorgänge, die über die Check24-Schnittstelle ausgeführt wurden. Das Format *Check24OrderImportAdapter* steht Ihnen für Check24 zur Verfügung.

[.instruction]
API-Log abrufen:

.  Öffnen Sie das Menü *Daten » API-Log » Tab: API-Log*.
.  Wählen Sie das Format *Check24OrderImportAdapter* aus der Dropdown-Liste *Vorgang*.
.  Wählen Sie ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
.  Wählen Sie die Anzahl der Ergebnisse pro Seite.
.  Klicken Sie auf *Suchen*, um die Ergebnisse anzuzeigen.
