= Etsy
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:experimental:
:keywords: Etsy, Marktplatz, Etsy einrichten, Etsy Marktplatz, Multi-Channel, Multichannel, Multi-Channel Etsy, Multichannel Etsy, multi channel Etsy, dawanda, Etsy-Plugin, Etsy Plugin
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Etsy in deinem plentymarkets System ein.
:position: 60
:url: maerkte/etsy
:id: J8WLEBE

link:https://www.etsy.com/de/[Etsy^] ist ein amerikanischer Marktplatz für den Kauf und Verkauf von handgemachten Produkten, Vintage und Künstlerbedarf.

[discrete]
===== Hinweis

Der Begriff "Etsy" ist ein Markenzeichen von Etsy, Inc. Diese Anwendung verwendet die Etsy-API, sie wurde jedoch von Etsy weder befürwortet noch zertifiziert.

[IMPORTANT]
.Etsy-Plugin installieren
====
Die Schnittstelle zu Etsy wird über ein link:https://marketplace.plentymarkets.com/plugins/sales/marktplaetze/etsy_4689[Plugin^] integriert. Um das Etsy-Plugin nutzen zu können, lade es im plentyMarketplace herunter.
====

[#100]
== Bei Etsy registrieren

Um das Plugin für Etsy in plentymarkets einrichten zu können, registriere dich zunächst bei Etsy als Händler:in.

[#200]
== Das Etsy-Plugin in plentymarkets installieren

Nachdem du das Etsy-Plugin im plentymarkets Marketplace gekauft hast, installiere das Etsy-Plugin im Menü *Plugins » Plugin-Übersicht*. Wähle den Filter *Nicht installiert* oder *Alle*, um nicht installierte Plugins anzuzeigen und zu installieren. Weitere Informationen zum Herunterladen und Installieren von Plugins erhältst du auf der Seite <<plugins/plugins-system-hinzufuegen#marketplace-plugins#, Plugins dem System hinzufügen>>.

[#250]
=== Schnittstelle freischalten

Im Menü *Einrichtung » Märkte » Etsy » Authentifizierung* muss zunächst die Schnittstelle freigeschaltet werden und plentymarkets Zugriff auf dein Etsy-Konto gewährt werden.

[.instruction]
Schnittstelle freischalten:

. Öffne das Menü *Einrichtung » Märkte » Etsy » Authentifizierung*.
. Klicke auf das Weltkugel-Symbol (icon:globe[role="green"]). +
→ Ein neues Fenster wird geöffnet und du wirst zu Etsy weitergeleitet.
. Gib deine Etsy-Zugangsdaten ein.
. Klicke auf *Gestatte den Zugang*. +
→ Die Schnittstelle zu Etsy ist freigeschaltet und du kannst weitere Einstellungen vornehmen.


[#300]
=== Etsy in plentymarkets einrichten

[IMPORTANT]
.Einstellungen bei Etsy beachten
====
Bevor du das Etsy-Plugin in plentymarkets einrichtest, muss bei Etsy im Menü *Shop-Manager » Artikel » [Artikel öffnen]* die Einstellung *Erneuerungsoptionen* auf *Manuell* gestellt werden, da das Etsy-Plugin sonst nicht korrekt funktioniert.
====

Im Menü *Einrichtung » Märkte » Etsy » Einstellungen* aktivierst du den Datenaustausch.

[.instruction]
Datenaustausch aktivieren:

. Öffne das Menü *Einrichtung » Märkte » Etsy » Einstellungen*
. Aktiviere im Bereich *Prozesse* den *Artikelexport*, *Bestandsabgleich* und *Auftragsimport*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[discrete]
===== Exportsprachen einstellen

Im Bereich *Exportsprachen* nimmst du Einstellungen zu den Exportsprachen vor. Standardmäßig wird die *Shop-Sprache* exportiert. Andere Sprachen werden für Übersetzungen der Angebote verwendet.

[.instruction]
Exportsprachen einstellen:

. Öffne das Menü *Einrichtung » Märkte » Etsy » Einstellungen*.
. Setze Häkchen bei den Sprachen, in denen deine Angebote exportiert werden sollen. *Englisch*, *Deutsch* und *Französisch* stehen zur Verfügung. +
*_Hinweis:_* Die eingestellte *Shop-Sprache* wird bereits standardmäßig exportiert.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[#400]
== Auftragsherkunft aktivieren

:market: Etsy
:referrer: Etsy
:referrer-option: pass:quotes[Option *Etsy*]

include::_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#500]
== Variantenverfügbarkeit einstellen

:market-availability: Etsy
:option-availability: Etsy

include::_textblocks/instructions/variantenverfuegbarkeit.adoc[]

// Web-API NICHT erforderlich!

[#550]
== _Optional:_ Existierende Etsy Listing-ID speichern

Wenn du eine Variante bereits auf Etsy listest, speichere die Etsy Listing-ID als SKU für die Herkunft *Etsy*. So können Varianten beim Export den bereits auf Etsy gelisteten Varianten zugewiesen werden und Überverkäufe werden verhindert. +

[.instruction]
Etsy Listing-ID speichern:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Etsy*.
. Gib die *SKU* im folgenden Format ein: +
  _[Etsy Listing-ID]_-_[plentymarkets-Varianten-ID]_ +
  *_Beispiel:_* 708093072-3467
. Gib die *Parent-SKU* im folgenden Format ein: +
  _[Etsy Listing-ID]_ +
  *_Beispiel:_* 708093072
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die SKU wird gespeichert und angezeigt.

[#600]
== Verkaufspreis festlegen

:referrer-price: Etsy

include::_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#900]
== Artikelexport einrichten

Artikeldaten werden über Kataloge zu Etsy übertragen. Mit dem Marktplatz-Format *Listing - Etsy* erstellst du einen Katalog, über den Daten für alle Etsy-Produktkategorien exportiert werden.

[#700]
=== Katalog erstellen

Artikeldaten werden über das Marktplatz-Format *Listing - Etsy* zu Etsy übertragen. Um deine Artikel zu Etsy zu übertragen, erstellst du im Menü *Daten » Kataloge* einen Katalog. Verknüpfe anschließend im Marktplatz-Format die von Etsy vorgegebenen Felder mit in plentymarkets gespeicherten Artikeldaten. Die Katalogdaten werden automatisch einmal täglich zu Etsy exportiert, wenn du unter *Einrichtung » Märkte » Etsy » Einstellungen* den *Artikelexport* aktiviert hast. Du arbeitest zum ersten Mal mit den Katalogen? Dann solltest du dich zuerst <<daten/daten-exportieren/kataloge-verwalten#, mit dem Prinzip der Kataloge vertraut machen>>.

TIP: Du kannst für Etsy nur einen Katalog anlegen. Mehrere Kataloge werden für Etsy aktuell nicht unterstützt.

:catalogue-template-name: Listing - Etsy

include::_textblocks/instructions/katalog-erstellen.adoc[]

[#datenfelder-zuordnen]
=== Datenfelder im Katalog zuordnen

[IMPORTANT]
.Besonderheiten des Etsy-Marktplatz-Formats
====
Im Datenfeld *Shop-Abteilung* des *Listing - Etsy*-Templates stehen alle Shop-Abteilungen, die du bei Etsy erstellt hast, in der Dropdown-Liste zur Verfügung und können mit Daten aus plentymarkets verknüpft werden.
====

Nachdem du einen Katalog erstellt hast, ordnest du die Datenfelder des Marktplatzes den in plentymarkets gespeicherten Artikeldaten zu. Informationen dazu, welche Daten für welches Datenfeld des Marktplatzes übertragen werden müssen, findest du in der Dokumentation des Marktplatzes.

[TIP]
.Eigenschaften verwenden
====
Verwende <<artikel/artikel-verwalten#4800, Eigenschaften>>, um Werte für Marktplatz-Datenfelder zu übergeben, für die es keine Entsprechung in plentymarkets gibt.
====

include::_textblocks/instructions/katalog-datenfelder-zuordnen.adoc[]

[#800]
== Etsy-Kategorien aktualisieren

Um Etsy-Kategorien in plentymarkets zu aktualisieren, lösche deine Credentials im Menü *Einrichtung » Märkte » Etsy » Authentifizierung* und füge diese neu hinzu.


[.instruction]
Etsy-Kategorien aktualisieren:

. Öffne das Menü *Einrichtung » Märkte » Etsy » Authentifizierung*.
. Klicke auf *Löschen*, um die Credentials zu löschen.
. Klicke auf das Weltkugel-Symbol (icon:globe[role="green"]), um neue Credentials hinzuzufügen. +
→ Du wirst zu Etsy weitergeleitet.
. Klicke bei Etsy auf *Gestatte den Zugang*. +
→ Neue Credentials werden erstellt und in plentymarkets gespeichert. +
→ Die Etsy-Kategorien werden aktualisiert.


[#900]
== Rechtliche Hinweise übertragen

Um rechtliche Hinweise an den Marktplatz Etsy zu übertragen, speichere diese Hinweise in jeder Sprache, in der du dein Sortiment anbietest. Die Hinweise werden der Artikelbeschreibung hinzugefügt.

[.instruction]
Rechtliche Hinweise speichern:

. Öffne das Menü *Einrichtung » Märkte » Etsy » Rechtliche Hinweise*. +
→ Das Fenster *Rechtliche Hinweise* wird geöffnet.
. Wähle die Sprache aus, in der rechtliche Hinweise gespeichert werden sollen.
. Gib deinen Text ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[#1000]
== Zahlungsbestätigung automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Zahlungsbestätigungen automatisch an Etsy zu senden, nachdem ein Zahlungseingang gebucht wurde.

:table-event-procedure: <<#etsy-zahlungsbestaetigung>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[etsy-zahlungsbestaetigung]]
.Zahlungsbestätigungen automatisch an Etsy senden
[cols="1,3,3"]
|====
|Einstellung | Option | Auswahl

| *Ereignis*
| *Zahlung: Vollständig*
|

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Herkunft*
| *Etsy*

| *Aktion*
| *Plugin > Zahlungsbestätigung an Etsy senden*
|
|====


[#1100]
== Versandbestätigung automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an Etsy zu senden, nachdem ein Warenausgang gebucht wurde.

:table-event-procedure: <<#etsy-versandbestaetigung>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[etsy-versandbestaetigung]]
.Versandbestätigungen automatisch an Etsy senden
[cols="1,3,3"]
|====
|Einstellung | Option | Auswahl

| *Ereignis*
| *Auftragsänderung: Warenausgang gebucht*
|

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Herkunft*
| *Etsy*

| *Aktion*
| *Plugin > Versandbestätigung an Etsy senden*
|
|====


[#1200]
== Benutzerrechte vergeben

Damit Benutzer:innen mit dem Zugang *Backend* das Etsy-Plugin nutzen können, müssen Benutzerrechte vergeben werden. Benutzerrechte werden im Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer* zugewiesen.

[.instruction]
Benutzerrechte für Backend-Benutzer:innen vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion und öffne das zu bearbeitende Konto.
. Klappe das Menü *Berechtigungen: Märkte* auf.
. Wähle die Option *Zugangsdaten*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#1300]
== Lizenz

:license-link: https://github.com/plentymarkets/plugin-etsy/blob/master/LICENSE.md

include::_textblocks/explanations/plugin-lizenz.adoc[]
