= Etsy
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: Etsy, Marktplatz, Etsy einrichten, Etsy Marktplatz, Multi-Channel, Multichannel, Multi-Channel Etsy, Multichannel Etsy, multi channel Etsy, dawanda, Etsy-Plugin, Etsy Plugin
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Etsy in deinem plentymarkets System ein.
:position: 60
:url: maerkte/etsy
:id: J8WLEBE

link:https://www.etsy.com/de/[Etsy^] ist ein amerikanischer Marktplatz für den Kauf und Verkauf von handgemachten Produkten, Vintage und Künstlerbedarf.

[.subhead]
Hinweis

Der Begriff "Etsy" ist ein Markenzeichen von Etsy, Inc. Diese Anwendung verwendet die Etsy-API, sie wurde jedoch von Etsy weder befürwortet noch zertifiziert.

[IMPORTANT]
.Etsy-Plugin installieren
====
Die Schnittstelle zu Etsy wird über ein link:https://marketplace.plentymarkets.com/plugins/sales/marktplaetze/etsy_4689[Plugin^] integriert. Um das Etsy-Plugin nutzen zu können, lade es im plentyMarketplace herunter.
====


[#100]
== Bei Etsy registrieren

Um das Plugin für Etsy in plentymarkets einrichten zu können, registriere dich zunächst bei Etsy als Händler.

[#200]
== Das Etsy-Plugin in plentymarkets installieren

Nachdem du das Etsy-Plugin im plentymarkets Marketplace gekauft hast, installiere das Etsy-Plugin im Menü *Plugins » Plugin-Übersicht*. Wähle den Filter *Nicht installiert* oder *Alle*, um nicht installierte Plugins anzuzeigen und zu installieren. Weitere Informationen zum Herunterladen und Installieren von Plugins erhältst du auf der Seite <<plugins/plugins-system-hinzufuegen#marketplace-plugins#, Plugins dem System hinzufügen>>.

[#250]
=== Schnittstelle freischalten

Im Menü *Einrichtung » Märkte » Etsy » Authentifizierung* muss zunächst die Schnittstelle freigeschaltet werden und plentymarkets Zugriff auf dein Etsy-Konto gewährt werden.

[.instruction]
Schnittstelle freischalten:

. Öffne das Menü *Einrichtung » Märkte » Etsy » Authentifizierung*.
. Klicke auf das Weltkugel-Symbol (icon:globe[role="green"]). +
→ Ein neues Fenster wird geöffnet und du wirst zu Etsy weitergeleitet.
. Gib deine Etsy-Zugangsdaten ein.
. Klicke auf *Gestatte den Zugang*. +
→ Die Schnittstelle zu Etsy ist freigeschaltet und du kannst weitere Einstellungen vornehmen.


[#300]
=== Etsy in plentymarkets einrichten

[IMPORTANT]
.Einstellungen bei Etsy beachten
====
Bevor du das Etsy-Plugin in plentymarkets einrichtest, muss bei Etsy im Menü *Shop-Manager » Artikel »* _Artikel öffnen_ die Einstellung *Erneuerungsoptionen* auf *Manuell* gestellt werden, da das Etsy-Plugin sonst nicht korrekt funktioniert.
====

Im Menü *Einrichtung » Märkte » Etsy » Einstellungen* aktivierst du den Datenaustausch.

[.instruction]
Datenaustausch aktivieren:

. Öffne das Menü *Einrichtung » Märkte » Etsy » Einstellungen*
. Aktiviere im Bereich *Prozesse* den *Artikelexport*, *Bestandsabgleich* und *Auftragsimport*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[.subhead]
Exportsprachen einstellen

Im Bereich *Exportsprachen* nimmst du Einstellungen zu den Exportsprachen vor. Standardmäßig wird die *Shop-Sprache* exportiert. Andere Sprachen werden für Übersetzungen der Angebote verwendet.

[.instruction]
Exportsprachen einstellen:

. Öffne das Menü *Einrichtung » Märkte » Etsy » Einstellungen*.
. Setze Häkchen bei den Sprachen, in denen deine Angebote exportiert werden sollen. *Englisch*, *Deutsch* und *Französisch* stehen zur Verfügung. +
→ *Hinweis:* Die eingestellte *Shop-Sprache* wird bereits standardmäßig exportiert.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[#400]
== Auftragsherkunft aktivieren

Damit du Artikel mit Etsy verknüpfen kannst, muss im Menü *Einrichtung » Aufträge » Auftragsherkunft* die Auftragsherkunft Etsy aktiviert werden.

[.instruction]
Auftragsherkunft für Etsy aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Setze bei *Etsy* ein Häkchen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[#500]
== Variantenverfügbarkeit einstellen

Artikel, die du auf Etsy verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten »* _Artikel öffnen_ *» Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[TIP]
.Alle Varianten eines Artikels auf Etsy verkaufen
====
Wenn du alle Varianten eines Artikels auf Etsy verkaufen möchtest, nimm die unten beschriebenen Einstellungen an der Hauptvariante vor. Die Einstellungen werden dann an alle Varianten des Artikels vererbt.
====

[.instruction]
Variantenverfügbarkeit für Etsy einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten »* _Artikel öffnen_ *» Tab: Varianten-ID » Tab: Einstellungen*.
. Öffne die Variante, die du auf Etsy verkaufen möchtest.
. Aktiviere im Bereich *Verfügbarkeit* die Option *Aktiv*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *Etsy*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Artikel ist auf Etsy verfügbar.

Wenn du bereits auf Etsy listest, hinterlege die Etsy Listing-ID im Menü *Artikel » Artikel bearbeiten »* _Artikel öffnen_ *» Tab: Varianten-ID » Tab: Einstellungen » Tab: Verfügbarkeit* als SKU für die Herkunft *Etsy*, damit Artikel beim Artikelexport den bereits auf Etsy gelisteten Artikel zugewiesen werden können und somit keine Überverkäufe entstehen. +

Die Etsy-Listing-ID muss in folgendem Format hinterlegt werden: *Etsy Listing-ID-plentymarkets-Varianten-ID*, zum Beispiel *708093072-3467*.


[#600]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft Etsy einen Verkaufspreis festzulegen. Dieser Preis wird auf Etsy angezeigt.

[.instruction]
Verkaufspreis für Etsy festlegen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise »* _Verkaufspreis öffnen_ *» Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *Etsy*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[#700]
== Katalog erstellen

Artikeldaten werden über Katalog-Templates zu Etsy übertragen. Damit du deine Artikel zu Etsy übertragen kannst, musst du im Menü *Daten » Kataloge* ein Katalog-Template erstellen. Verknüpfe anschließend im Katalog-Template die von Etsy vorgegebenen Felder mit in plentymarkets hinterlegten Artikeldaten. Die Katalog-Vorlagen werden automatisch einmal täglich zu Etsy exportiert, wenn du unter *Einrichtung » Märkte » Etsy » Einstellungen* den *Artikelexport* aktiviert hast. +

Für Etsy verwendest du das Katalog-Template *Listing - Etsy*.

Weitere Informationen zu Katalogen findest du auf der Handbuchseite <<daten/daten-exportieren/kataloge-verwalten#, Kataloge verwalten>>.

[NOTE]
.Sichtbarkeit des Menüs *Daten » Kataloge*
====
Das Menü *Daten » Kataloge* ist erst sichtbar, wenn du ein Plugin bereitstellst, das ein Katalog-Template verfügbar macht.
====

[.instruction]
Katalog erstellen:

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf *Katalog erstellen*.
. Gib einen Namen für den Katalog ein.
. Wähle das Katalog-Template *Listing - Etsy* aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Katalog wird erstellt. +
→ Der Katalog wird zur weiteren Bearbeitung geöffnet.

Nachdem du einen Katalog erstellt hast, verknüpfe die Datenfelder des Marktplatzes mit in plentymarkets gespeicherten Artikeldaten. Weitere Informationen zu den plentymarkets Datenquellen, die du zuordnen kannst, findest du im Kapitel <<daten/daten-exportieren/kataloge-verwalten#, Datenquellen zuordnen>>.

[.instruction]
Datenfelder im Katalog verknüpfen:

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf den erstellten Katalog. +
→ Der Katalog wird geöffnet. +
→ Links werden die Datenfelder des Marktplatzes angezeigt. +
→ *Tipp:* Pflichtfelder sind mit Sternchen gekennzeichnet.
. Wähle für die Datenfelder des Marktplatzes eine plentymarkets Datenquelle aus der Dropdown-Liste.
. Um einem Datenfeld eine weitere plentmarkets Datenquelle zuzuordnen, klicke auf *Quelle hinzufügen*. +
→ Eine neue Zeile wird eingeblendet. +
→ *Hinweis:* Auch wenn du einem Datenfeld mehr als eine Datenquelle zuordnest, wird nur ein Wert übertragen. Die Daten werden in der Reihenfolge der Zuordnung geprüft. Wenn also das erste Datenfeld keinen Wert liefert, wird das zweite Datenfeld übertragen usw.
. Nimm alle gewünschten Zuordnungen vor. +
→ Alle Pflichtfelder müssen mit einer plentymarkets Datenquelle verknüpft werden.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[.subhead]
Besonderheiten des Etsy-Katalog-Templates

Im Datenfeld *Shop-Abteilung* des *Listing - Etsy*-Templates stehen alle Shop-Abteilungen, die du bei Etsy angelegt hast, in der Dropdown-Liste zur Verfügung und können mit Daten aus plentymarkets verknüpft werden.


[#800]
== Etsy-Kategorien aktualisieren

Um Etsy-Kategorien in plentymarkets zu aktualisieren, lösche deine Credentials im Menü *Einrichtung » Märkte » Etsy » Authentifizierung* und füge diese neu hinzu.


[.instruction]
Etsy-Kategorien aktualisieren:

. Öffne das Menü *Einrichtung » Märkte » Etsy » Authentifizierung*.
. Klicke auf *Löschen*, um die Credentials zu löschen.
. Klicke auf das Weltkugel-Symbol (icon:globe[role="green"]), um neue Credentials hinzuzufügen. +
→ Du wirst zu Etsy weitergeleitet.
. Klicke bei Etsy auf *Gestatte den Zugang*. +
→ Neue Credentials werden erstellt und in plentymarkets hinterlegt. +
→ Die Etsy-Kategorien werden aktualisiert.


[#900]
== Rechtliche Hinweise übertragen

Um rechtliche Hinweise an den Marktplatz Etsy zu übertragen, hinterlege diese Hinweise in jeder Sprache, in der du dein Sortiment anbietest. Die Hinweise werden der Artikelbeschreibung hinzugefügt.

[.instruction]
Rechtliche Hinweise hinterlegen:

. Öffne das Menü *Einrichtung » Märkte » Etsy » Rechtliche Hinweise*. +
→ Das Fenster *Rechtliche Hinweise* wird geöffnet.
. Wähle die Sprache aus, in der rechtliche Hinweise hinterlegt werden sollen.
. Gib deinen Text ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[#1000]
== Zahlungsbestätigung automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Zahlungsbestätigungen automatisch an Etsy zu senden, nachdem ein Zahlungseingang gebucht wurde.

:table-event-procedure: <<#etsy-zahlungsbestaetigung>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[etsy-zahlungsbestaetigung]]
.Zahlungsbestätigungen automatisch an Etsy senden
[cols="1,3,3"]
|====
|Einstellung | Option | Auswahl

| *Ereignis*
| *Zahlung: Vollständig*
|

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Herkunft*
| *Etsy*

| *Aktion*
| *Plugin > Zahlungsbestätigung an Etsy senden*
|
|====


[#1100]
== Versandbestätigung automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an Etsy zu senden, nachdem ein Warenausgang gebucht wurde.

:table-event-procedure: <<#etsy-versandbestaetigung>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[etsy-versandbestaetigung]]
.Versandbestätigungen automatisch an Etsy senden
[cols="1,3,3"]
|====
|Einstellung | Option | Auswahl

| *Ereignis*
| *Auftragsänderung: Warenausgang gebucht*
|

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Herkunft*
| *Etsy*

| *Aktion*
| *Plugin > Versandbestätigung an Etsy senden*
|
|====


[#1200]
== Benutzerrechte vergeben

Damit Benutzer mit dem Zugang *Backend* das Etsy-Plugin nutzen können, müssen Benutzerrechte vergeben werden. Benutzerrechte werden im Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer* zugewiesen.

[.instruction]
Benutzerrechte für Backend-Benutzer vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion und öffne den zu bearbeitenden Benutzer.
. Klappe das Menü *Berechtigungen: Märkte* auf.
. Wähle die Einstellung *Zugangsdaten*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[#1300]
== Lizenz

Das gesamte Projekt unterliegt der GNU AFFERO GENERAL PUBLIC LICENSE – weitere Informationen findest du in der link:https://github.com/plentymarkets/plugin-etsy/blob/master/LICENSE.md[LICENSE.md^].
