= Flubit
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Flubit, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Flubit in deinem plentymarkets System ein.
:position: 70
:url: maerkte/flubit

link:https://flubit.com/[Flubit^] ist ein auf das Vereinigte Königreich beschränkter Online-Marktplatz, der keine Provision vom Händler verlangt.

[#100]
== Bei Flubit registrieren

Registriere dich zunächst als Verkäufer bei link:https://sellers.skucloud.co.uk/start-selling[WeFlubit^], der zentralen Flubit-Anlaufstelle für Verkäufer.

[#200]
== Flubit in plentymarkets einrichten

Um Artikel auf Flubit anzubieten, richte Flubit in plentymarkets ein. Du benötigst die Zugangsdaten bestehend aus API-Schlüssel und Sicherheits-Token. Diese Daten erhältst du von Flubit.

[.instruction]
Flubit in plentymarkets einrichten:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Flubit*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<grundeinstellungen-flubit>>.
. *Speichere* die Einstellungen.

[[grundeinstellungen-flubit]]
.Grundeinstellungen des Marktplatzes Flubit
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Automatischen Datenaustausch aktivieren*
|Ist der Datenaustausch aktiviert, findet ein täglicher Artikelexport (nachts), ein stündlicher Bestandsabgleich und ein stündlicher Auftragsimport statt.

|*API-Schlüssel*
|API-Schlüssel (Key) eintragen, wie von Flubit erhalten.

|*Sicherheits-Token*
|Sicherheits-Token (Secret) eintragen, wie von Flubit erhalten.

|*Umgebung*
|*Live* oder *Sandbox* wählen. +
Ist die Option *Live* gewählt, werden die Artikel live gelistet. Die Option *Sandbox* ist ein Testmodus.

|*Artikelname*
|*Name 1*, *Name 2* oder *Name 3* wählen. Dieser Artikelname wird an Flubit übertragen.

|*Artikelbeschreibung*
|*Standardbeschreibung*, *Kurzbeschreibung* oder *Technische Daten* wählen.  +
Diese Artikelbeschreibung wird an Flubit übertragen. Die Artikelbeschreibung muss auf Englisch eingetragen sein, andernfalls wird der Artikel nicht exportiert.

|*Lagerauswahl*
|Bestandsmenge für den stündlichen Bestandsabgleich und täglichen Artikelexport wählen. Eine der folgenden Optionen wählen: +
*Bestandsmenge des Vertriebslagers mit größtem Bestand* +
*Bestandsmenge des Artikel-Hauptlagers* +
*Bestandsmenge aller Vertriebslager*
|====

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

* täglicher Artikelexport
* stündlicher Bestandsabgleich
* stündlicher Auftragsimport
* automatisches Erstellen neuer Kund*innen beim Auftragsimport, wenn diese noch nicht in der Datenbank vorhanden sind

[IMPORTANT]
.Sprache
====
Attribute müssen auf Englisch hinterlegt sein, damit Artikel zu Flubit exportiert werden können.
====

[#250]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit Flubit verknüpfen kannst, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft Flubit aktiviert werden.

[.instruction]
Auftragsherkunft für Flubit aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setze bei *Flubit* ein Häkchen.
. *Speichere* die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die du auf Flubit verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Flubit einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *Flubit*.
. Aktiviere die Option *Web-API*.
. Klicke auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* die Einstellungen. +
→ Der Artikel ist auf Flubit verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

[IMPORTANT]
.Pflichtangaben für den Artikelexport
====
Für einen funktionierenden Artikelexport zu Flubit müssen die folgenden Kriterien erfüllt sein:

* Artikelpreis ist größer als Null
* Artikel hat positiven Bestand
* Artikelbeschreibung ist auf Englisch eingegeben
* Artikel ist sichtbar
* Artikelbild ist vorhanden
* Artikelnummer wird übertragen +
→ Wird als Artikelnummer die MPN übertragen, muss zusätzlich die Marke oder der Hersteller angegeben werden.

Fehlen die oben aufgelisteten Angaben, werden die Artikel nicht exportiert.
====

[#350]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft Flubit einen Verkaufspreis festzulegen. Dieser Preis wird auf Flubit angezeigt.

[.instruction]
Verkaufspreis für Flubit festlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *Flubit*.
. *Speichere* die Einstellungen.

[#370]
== Zahlungsart aktivieren

Aktiviere die <<payment/zahlungsarten-verwalten#, Zahlungsart>> *Flubit*, wie im Folgenden beschrieben.

[.instruction]
Zahlungsart Flubit aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive anzeigen*.
. Klicke auf den Ordner *International &gt; Flubit*.  +
→ Die Einstellungen für die Flubit-Zahlungsart werden angezeigt.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-zahlungsart-flubit>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* die Einstellungen.

[[einstellungen-zahlungsart-flubit]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn Käufer*innen im Webshop die Sprache wählen.

|*Name*
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
|Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in deinem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig:* Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » Systemeinstellungen » CRM » Kundenklassen* aktivierst oder deaktivierst du *erlaubte Zahlungsarten*. +
Weitere Informationen findest du im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#400]
== Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an Flubit zu senden, nachdem ein Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-versandbestätigung-flubit>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-versandbestätigung-flubit>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-versandbestätigung-flubit]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an Flubit
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Flubit*

|*Aktion*
|*Auftrag &gt; Versandbestätigung an Flubit senden*
|
|====

[#500]
== Stornierungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Flubit automatisch über Stornierungen zu informieren. Bei Stornierungen muss ein Grund für die Stornierung an Flubit übertragen werden. Erstelle im Menü *System » Systemeinstellungen » Aufträge » Auftragsstatus* ggf. zusätzliche Auftragsstatus. Folgende Stornierungsgründe können an Flubit übertragen werden:

* Artikel nicht vorrätig
* Artikel nicht mehr im Sortiment
* Ungültige Lieferadresse
* Stornierung durch Kunden
* Gesetzliche Beschränkung
* Sonstiges

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-stornierung-flubit>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-stornierung-flubit>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-stornierung-flubit]]
.Ereignisaktion zum automatischen Senden von Stornierungen an Flubit
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Statuswechsel: [8.1] Storniert durch Kunden*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Flubit*

|*Aktion*
|*Auftrag &gt; Stornierung an Flubit senden*
|*Stornierung durch Kunden*
|====

[#600]
== Retouren automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Flubit automatisch über Retouren zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-retouren-flubit>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-retouren-flubit>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-retouren-flubit]]
.Ereignisaktion zum automatischen Senden von Retouren an Flubit
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Flubit*

|*Aktion*
|*Auftrag &gt; Retoure an Flubit senden*
|
|====

[#700]
== API-Log abrufen

Im Menü <<daten/api-log#, Daten » API-Log>> im Tab *Flubit* findest du eine Historie über Vorgänge, die über die Flubit-Schnittstelle ausgeführt wurden. Folgende Formate stehen dir für Flubit zur Auswahl:

* *FlubitOrderImport* (Auftragsimport)
* *FlubitOrderCancel* (Stornierungen)
* *FlubitOrderDispatch* (Versandbestätigung, Rückerstattung)
* *FlubitProductsFeed* (Datenexport)

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle ein Format aus der Dropdown-Liste *Vorgang*.
. Wähle ein *Datum*, um nur Einträge eines bestimmten Tages zu erhalten.
. Klicke auf *Suchen*, um die Suche auszuführen. +
→ Die Vorgänge werden angezeigt.
. Klicke in der Spalte *Vorgang* auf den Ordner.  +
→ Das Tab *Flubit* wird geöffnet und Fehlermeldungen des Vorgangs werden angezeigt.
