= grosshandel.eu
:lang: de
include::{includedir}/_header.adoc[]
:keywords: grosshandel.eu, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz grosshandel.eu in deinem plentymarkets System ein.
:position: 90
:url: maerkte/grosshandel

link:http://www.grosshandel.eu/[grosshandel.eu^] ist ein reines B2B-Portal, d.h. sowohl Anbieter als auch Nachfrager müssen im Besitz eines gültigen Gewerbenachweises sein. Auf diesem Marktplatz kannst du reguläre Ware und Markenartikel kaufen und verkaufen (Quelle: grosshandel.eu).

[#100]
== Bei grosshandel.eu registrieren

Um dein plentymarkets System für grosshandel.eu einzustellen, link:http://www.grosshandel.eu/registrierung-verkaeufer.php[registriere^] dich zunächst im Händlerportal von grosshandel.eu.

[#200]
== Benutzerkonto erstellen

Dein plentymarkets System wird über die SOAP-API mit grosshandel.eu verbunden. Für den Zugriff benötigt der Marktplatz ein eigenes Benutzerkonto mit Zugriffsrechten auf die API in deinem System. Erstelle im Menü <<basics/admin-aufgaben/benutzer-verwalten#10, System » Systemeinstellungen » Einstellungen » Benutzer » Konten>> ein neues Benutzerkonto der Benutzerklasse *API* für grosshandel.eu. Aktiviere außerdem den Call *GetCategoryMappingForMarket*. Dieser Call sorgt dafür, dass der Marktplatz später deine Kategorieverknüpfungen auslesen kann.

[.instruction]
Benutzerkonto für grosshandel.eu erstellen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neuen Benutzer erstellen* wird geöffnet.
. Gib die Daten ein.
. Wähle als Benutzerklasse *API*.
. *Speichere* die Einstellungen. +
→ Der Benutzer wird erstellt.
. Wähle den Benutzer aus der Liste. +
→ Das Bearbeitungsfenster wird geöffnet.
. Öffne das Tab *Berechtigung » API*.
. Klappe den Bereich *Item* auf.
. Aktiviere den Call *GetCategoryMappingForMarket*.
. *Speichere* die Einstellungen.

Weitere Informationen findest du auf der Handbuchseite <<basics/admin-aufgaben/benutzer-verwalten#, Benutzer verwalten>>.

[#300]
== Daten bereitstellen

Für die Anbindung an dein plentymarkets System benötigt grosshandel.eu die folgenden Daten:

* URL der SOAP-API WSDL.  +
→ Du findest die URL im Menü <<basics/datenaustausch/api-daten#, System » Systemeinstellungen » Einstellungen » API » Daten>> unter *SOAP WSDL*.
* Benutzername und Passwort für das von dir erstellte Benutzerkonto für grosshandel.eu
* Deine Login-Daten für das Händlerportal von grosshandel.eu

[#350]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit grosshandel.eu verknüpfen kannst, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft grosshandel.eu aktiviert werden.

[.instruction]
Auftragsherkunft für grosshandel.eu aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setze bei *grosshandel.eu* ein Häkchen.
. *Speichere* die Einstellungen.

[#400]
== Artikelverfügbarkeit einstellen

Artikel, die du auf grosshandel.eu verkaufen möchtest, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für grosshandel.eu einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Setze ein Häkchen bei *grosshandel.eu*.
. Setze ein Häkchen bei *Web-API*.
. Klicke auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* die Einstellungen. +
→ Der Artikel ist auf grosshandel.eu verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

[#450]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *grosshandel.eu*.
. Gib die SKU ein.
. Klicke auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#500]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft grosshandel.eu einen Verkaufspreis festzulegen. Dieser Preis wird auf grosshandel.eu angezeigt.

[.instruction]
Verkaufspreis für grosshandel.eu festlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *grosshandel.eu*.
. *Speichere* die Einstellungen.

[#600]
== Kategorien verknüpfen

Verknüpfe deine Webshop-Kategorien mit den Kategorien von grosshandel.eu, damit deine Artikel in diesen Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Märkte » grosshandel.eu*.
. Klappe die Kategorie auf, die du mit einer grosshandel.eu-Kategorie verknüpfen möchten.
. Wähle eine grosshandel.eu-Hauptkategorie aus der Dropdown-Liste. +
→ Ein Fenster mit Unterkategorien wird geöffnet.
. Wähle aus den weiteren Unterkategorien die passende grosshandel.eu-Kategorie aus. +
→ Wenn die tiefste Kategorieebene erreicht ist, erscheint der Kategoriepfad im Textfeld *Kategorie*.
. Klicke auf *Übernehmen*. +
→ Das Kategoriefenster wird geschlossen.
. *Speichere* die Einstellungen.

[IMPORTANT]
.Verknüpfung bis in die unterste Kategorieebene
====
Verknüpfe deine Kategorien immer bis in die unterste Ebene. Andernfalls ist eine Verknüpfung nicht möglich.
====

[#700]
== Unterkategorien mehrfach verknüpfen

Mit der Funktion *Auswahl für Unterkategorien übernehmen* hast du die Möglichkeit, für alle Unterkategorien einer Kategorie denselben grosshandel.eu-Kategoriepfad zu übernehmen. Denselben grosshandel.eu-Kategoriepfad für alle Unterkategorien einer Kategorie zu übernehmen ist sinnvoll, wenn die Unterkategorien die gleiche Verknüpfung erhalten sollen. Die einzelnen Unterkategorien kannst du bei Bedarf manuell über die Dropdown-Liste ändern.

[.instruction]
Unterkategorien mehrfach verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Märkte » grosshandel.eu*.
. Klappe die Kategorie auf, für die du eine Kategorieverknüpfung erstellen möchtest.
. Wähle eine grosshandel.eu-Hauptkategorie aus der Dropdown-Liste in der Zeile *Auswahl für Unterkategorien übernehmen*. +
→ Ein Fenster mit Unterkategorien wird geöffnet.
. Wähle aus den weiteren Unterkategorien den passenden Kategoriepfad aus. +
→ Wenn die tiefste Kategorieebene erreicht ist, erscheint der Kategoriepfad im Textfeld *Kategorie*.
. Klicke auf *Übernehmen*. +
→ Das Kategoriefenster wird geschlossen.
. Klicke auf *Alle auswählen* in der Zeile *Auswahl für Unterkategorien übernehmen*.
. Klicke auf *Reload*. +
→ Der Kategoriepfad wird für alle Unterkategorien übernommen.
. *Speichere* die Einstellungen.
