= Kauflux
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kauflux, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Kauflux in deinem plentymarkets System ein.
:position: 120
:url: maerkte/kauflux
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

link:http://www.kauflux.de/[Kauflux.de^] ist ein offener Marktplatz mit unabhängigen Anbietern aus verschiedenen Bereichen. Kauflux.de vermarktet deine Produkte und Dienstleistungen und stellt für dich den direkten Kontakt zum Käufer her.

[#100]
==  Bei Kauflux registrieren

Du musst dich zunächst bei link:http://www.kauflux.de/konto[Kauflux^] registrieren, um dein plentymarkets System für Kauflux einzurichten.

[#200]
==  Kauflux in plentymarkets einrichten

Nimm die folgenden Grundeinstellungen vor, um Artikeldaten an Kauflux zu übergeben.

[.instruction]
Kauflux in plentymarkets einrichten:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Kauflux » Einstellungen*.
. Nimm die Einstellungen gemäß <<grundeinstellungen-kauflux>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[grundeinstellungen-kauflux]]
.Grundeinstellungen für Kauflux
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Umtauschfrist*
|Umtauschfrist der Artikel eingeben. Die Umtauschfrist wird in Tagen angeben. Für den Fall, dass ein Artikel vom Umtausch ausgeschlossen ist, den Wert *0* eingeben.

|*Auftragsherkunft*
|Herkunft der Aufträge für Kauflux wählen.

|*Art der Bestandsführung*
|Wählen, ob der Warenbestand übermittelt werden soll und ob der Warenbestand in diesem Fall *öffentlich* sichtbar sein soll, oder nicht.

|*API-URL für den Auftragsimport*
|Über diesen Link überträgt Kauflux die Aufträge zu plentymarkets. Dieser Link wird für den Auftragsimport von Kauflux benötigt und nicht für die Erstellung des Artikelkatalogs. Der Artikelkatalog wird über den elastischen Export im Menü *Daten » Elastischer Export* erstellt. Weitere Informationen findest du bei Kauflux unter link:http://www.kauflux.de/shop-anmelden/automatischer-auftragsdatenexport[Auftragsdatenexport^].
|====

[#250]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit Kauflux verknüpfen kannst, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft *Kauflux* aktiviert werden.

[.instruction]
Auftragsherkunft für Kauflux aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setze bei *Kauflux* ein Häkchen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die du auf Kauflux verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Kauflux einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *Kauflux*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Artikel ist auf Kauflux verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

[#350]
==  SKU manuell festlegen

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Kauflux*.
. Gib die SKU ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die SKU wird gespeichert und angezeigt.

[#400]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft Kauflux einen Verkaufspreis festzulegen. Dieser Preis wird auf Kauflux angezeigt.

[.instruction]
Verkaufspreis für Kauflux festlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *Kauflux*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#500]
== Merkmale verknüpfen

Um die Merkmale für den Marktplatz Kauflux nutzen zu können, müssen diese in den Einstellungen des jeweiligen Merkmals mit Kauflux verknüpft werden.

[.instruction]
Merkmale verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Klappe ein Merkmal auf.
. Aktiviere die Option *Kauflux*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#600]
== Kategorien verknüpfen

Verknüpfe deine Webshop-Kategorien im Menü *System » Systemeinstellungen » Märkte » Kauflux » Kategorieverknüpfung* mit den Kategorien von Kauflux. Zur Kategorieverknüpfung benötigst du die Kauflux-CSV-Datei. Die CSV-Datei von Kauflux enthält die *Kategorie-IDs* für diesen Marktplatz. Du erhältst die link:http://support.expeedo.de/f/kl/kauflux-Kategorien.xls[Kauflux-CSV-Datei^] im Verkäuferbereich der Kauflux-Website. In den nächsten Schritten werden die Kategorien deines Webshops exportiert, die Kategorien verknüpft und anschließend die verknüpften Kategorien importiert.

[.instruction]
Verknüpfung exportieren:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Kauflux » Kategorieverknüpfung*.
. Klicke auf *Verknüpfung exportieren*. +
*→* Eine CSV-Datei mit deinen Webshop-Kategorien wird erzeugt.
. Öffne die Webshop-CSV-Datei.

[.instruction]
Kategorie-IDs eingeben:

. Öffne die CSV-Datei von Kauflux.
. Suche die zu den Kategorien deinen Webshops passenden *Kategorie-IDs* in der Kauflux CSV-Datei.
. Gib die Kategorie-IDs aus der Kauflux-CSV-Datei in die Webshop-CSV-Datei in die Spalte *KaufluxCat* ein.
. Speichere die Webshop-CSV-Datei auf der Festplatte Ihres PCs.

[.instruction]
Verknüpfung importieren:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Kauflux » Kategorieverknüpfung*.
. Klicke bei *Datei* auf *Datei auswählen*.
. Wähle die Webshop-CSV-Datei von der Festplatte deines Rechners.
. Klicke auf *Öffnen*.
. Klicke auf *Speichern*. +
→ Die Verknüpfungen werden importiert und im Bereich *Verknüpfungen* angezeigt.

[#700]
== Artikel exportieren

Nachdem du Kauflux eingerichtet hast, kannst du deine Artikel unter *Daten » Elastischer Export* exportieren.

Für einen automatischen Artikelexport musst du die komplette URL kopieren und bei Kauflux hinterlegen. Voraussetzung dafür ist, dass du mindestens einen Artikelexport manuell durchgeführt hast und die einzelnen Felder in Kauflux zugeordnet hast. Zudem muss der automatische Artikelexport von Kauflux aktiviert werden.

[#800]
== Varianten exportieren

Varianten werden beim Exportieren als zusätzliche CSV-Felder exportiert. Wenn du diese CSV- bzw. ZIP-Datei bei Kauflux importieren möchtest, wirst du aufgefordert, das Mapping durchzuführen.

[IMPORTANT]
.Beispiel
====
Die Variantenfelder *Farbe*, *Größe* und *Länge* werden im Mapping dargestellt. Bei allen Variantenfeldern musst du *GroupParam* als Mappingfeld wählen, damit diese Felder als Varianten bei Kauflux.de hinterlegt werden können. Das Feld *GroupID* dient ausschließlich zur Identifikation der zusammengehörenden Artikel einer Artikelgruppe.
====

[#900]
== Aufträge importieren

Du kannst deine Aufträge von Kauflux automatisch in dein plentymarkets System einpflegen lassen. Dazu musst du die API-URL, die du unter *System » Systemeinstellungen » Märkte » Kauflux » Einstellungen* findest, bei Kauflux hinterlegen. Nach diesem Schritt werden Aufträge automatisch in dein plentymarkets System eingepflegt und im Menü *Aufträge » Aufträge bearbeiten* angezeigt.

[#1000]
== E-Mail bei Auftragsimport senden

Aktiviere den automatischen E-Mail-Versand beim Importieren von Aufträgen. Dazu erstellst du im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen* eine E-Mail-Vorlage für Kauflux und aktivierst die Vorlage folgendermaßen.

[.instruction]
E-Mail bei Auftragsimport senden:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Automatischer Versand*.
. Wähle bei *Neue Bestellung über Kauflux* die zuvor erstellte E-Mail-Vorlage aus.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Über *E-Mail-Vorlage bearbeiten* wechselst du in das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen* und bearbeitest dort die E-Mail-Vorlage.
