= Kauflux
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kauflux, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz Kauflux in Ihrem plentymarkets System ein.
:position: 120

link:http://www.kauflux.de/[Kauflux.de^] ist ein offener Marktplatz mit unabhängigen Anbietern aus verschiedenen Bereichen. Kauflux.de vermarktet Ihre Produkte und Dienstleistungen und stellt für Sie den direkten Kontakt zum Käufer her.

[#100]
==  Bei Kauflux registrieren

Sie müssen sich zunächst bei link:http://www.kauflux.de/konto[Kauflux^] registrieren, um Ihr plentymarkets System für Kauflux einzurichten.

[#200]
==  Kauflux in plentymarkets einrichten

Nehmen Sie die folgenden Grundeinstellungen vor, um Artikeldaten an Kauflux zu übergeben.

[.instruction]
Kauflux in plentymarkets einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Märkte » Kauflux » Einstellungen*.
. Nehmen Sie die Einstellungen gemäß <<grundeinstellungen-kauflux>> vor.
. *Speichern* Sie die Einstellungen.

[[grundeinstellungen-kauflux]]
.Grundeinstellungen für Kauflux
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Umtauschfrist*
|Umtauschfrist der Artikel eingeben. Die Umtauschfrist wird in Tagen angeben. Für den Fall, dass ein Artikel vom Umtausch ausgeschlossen ist, den Wert *0* eingeben.

|*Auftragsherkunft*
|Herkunft der Aufträge für Kauflux wählen.

|*Art der Bestandsführung*
|Wählen, ob der Warenbestand übermittelt werden soll und ob der Warenbestand in diesem Fall *öffentlich* sichtbar sein soll, oder nicht.

|*API-URL für den Auftragsimport*
|Über diesen Link überträgt Kauflux die Aufträge zu plentymarkets. Dieser Link wird für den Auftragsimport von Kauflux benötigt und nicht für die Erstellung des Artikelkatalogs. Der Artikelkatalog wird über die Preisportale im Menü *System » Systemeinstellungen » Märkte » Preisportale » Exporte* erstellt. Weitere Informationen finden Sie bei Kauflux unter link:http://www.kauflux.de/shop-anmelden/automatischer-auftragsdatenexport[Auftragsdatenexport^].
|====

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit Kauflux verknüpfen können, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft Kauflux aktiviert werden.

[.instruction]
Auftragsherkunft für Kauflux aktivieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setzen Sie bei *Kauflux* ein Häkchen.
. *Speichern* Sie die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf Kauflux verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Kauflux einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktivieren Sie die Option *Kauflux*.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen. +
→ Der Artikel ist auf Kauflux verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

[#350]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügen Sie, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechseln Sie in das Tab *Verfügbarkeit*.
.  Klicken Sie im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
.  Wählen Sie die Herkunft *Kauflux*.
.  Geben Sie die SKU ein.
.  Klicken Sie auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#400]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft Kauflux einen Verkaufspreis festzulegen. Dieser Preis wird auf Kauflux angezeigt.

[.instruction]
Verkaufspreis für Kauflux festlegen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setzen Sie ein Häkchen bei der Herkunft *Kauflux*.
. *Speichern* Sie die Einstellungen.

[#500]
== Merkmale verknüpfen

Um die Merkmale für den Marktplatz Kauflux nutzen zu können, müssen diese in den Einstellungen des jeweiligen Merkmals mit Kauflux verknüpft werden.

[.instruction]
Merkmale verknüpfen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Klappen Sie ein Merkmal auf.
. Aktivieren Sie die Option *Kauflux*.
. *Speichern* Sie die Einstellungen.

[#600]
== Kategorien verknüpfen

Verknüpfen Sie Ihre Webshop-Kategorien im Menü *System » Systemeinstellungen » Märkte » Kauflux » Kategorieverknüpfung* mit den Kategorien von Kauflux. Zur Kategorieverknüpfung benötigen Sie die Kauflux-CSV-Datei. Die CSV-Datei von Kauflux enthält die *Kategorie-IDs* für diesen Marktplatz. Sie erhalten die link:http://support.expeedo.de/f/kl/kauflux-Kategorien.xls[Kauflux-CSV-Datei^] im Verkäuferbereich der Kauflux-Website. In den nächsten Schritten werden die Kategorien Ihres Webshops exportiert, die Kategorien verknüpft und anschließend die verknüpften Kategorien importiert.

[.instruction]
Verknüpfung exportieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Märkte » Kauflux » Kategorieverknüpfung*.
. Klicken Sie *Verknüpfung exportieren*. +
*→* Eine CSV-Datei mit Ihren Webshop-Kategorien wird erzeugt.
. Öffnen Sie die Webshop-CSV-Datei.

[.instruction]
Kategorie-IDs eingeben:

. Öffnen Sie die CSV-Datei von Kauflux.
. Suchen Sie zu den Kategorien Ihres Webshops die passenden *Kategorie-IDs* in der Kauflux CSV-Datei.
. Geben Sie die Kategorie-IDs aus der Kauflux-CSV-Datei in die Webshop-CSV-Datei in die Spalte *KaufluxCat* ein.
. Speichern Sie die Webshop-CSV-Datei auf der Festplatte Ihres PCs.

[.instruction]
Verknüpfung importieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Märkte » Kauflux » Kategorieverknüpfung*.
. Klicken Sie bei *Datei* auf *Datei auswählen*.
. Wählen Sie die Webshop-CSV-Datei von der Festplatte Ihres Rechners.
. Klicken Sie auf *Öffnen*.
. Klicken Sie auf *Speichern*. +
→ Die Verknüpfungen werden importiert und im Bereich *Verknüpfungen* angezeigt.

[#700]
== Artikel exportieren

Nachdem Sie Kauflux eingerichtet haben, können Sie Ihre Artikel unter *System » Systemeinstellungen » Märkte » Preisportale » Exporte* exportieren.

Für einen automatischen Artikelexport müssen Sie die komplette URL kopieren und bei Kauflux hinterlegen. Voraussetzung dafür ist, dass Sie mindestens einen Artikelexport manuell durchgeführt haben und die einzelnen Felder in Kauflux zugeordnet haben. Zudem muss der automatische Artikelexport von Kauflux aktiviert werden.

[#800]
== Varianten exportieren

Varianten werden beim Exportieren als zusätzliche CSV-Felder exportiert. Wenn Sie diese CSV- bzw. ZIP-Datei bei Kauflux importieren möchten, werden Sie aufgefordert, das Mapping durchzuführen.

[IMPORTANT]
.Beispiel
====
Die Variantenfelder *Farbe*, *Größe* und *Länge* werden im Mapping dargestellt. Bei allen Variantenfeldern müssen Sie *GroupParam* als Mappingfeld wählen, damit diese Felder als Varianten bei Kauflux.de hinterlegt werden können. Das Feld *GroupID* dient ausschließlich zur Identifikation der zusammengehörenden Artikel einer Artikelgruppe.
====

[#900]
== Aufträge importieren

Sie können Ihre Aufträge von Kauflux automatisch in Ihr System einpflegen lassen. Dazu müssen Sie die API-URL, die Sie unter *System » Systemeinstellungen » Märkte » Kauflux » Einstellungen* finden, bei Kauflux hinterlegen. Nach diesem Schritt werden Aufträge automatisch in Ihr System eingepflegt und im Menü *Aufträge » Aufträge bearbeiten* angezeigt.

[#1000]
== E-Mail bei Auftragsimport senden

Aktivieren Sie den automatischen E-Mail-Versand beim Importieren von Aufträgen. Dazu erstellen Sie im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen* eine E-Mail-Vorlage für Kauflux und aktivieren die Vorlage folgendermaßen.

[.instruction]
E-Mail bei Auftragsimport senden:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Automatischer Versand*.
. Wählen Sie bei *Neue Bestellung über Kauflux* die zuvor erstellte E-Mail-Vorlage aus.
. *Speichern* Sie die Einstellungen.

Über *E-Mail-Vorlage bearbeiten* wechseln Sie in das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen* und bearbeiten dort die E-Mail-Vorlage.
