= limango
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: limango, Marktplatz, limango.de, limango einrichten, limango Marktplatz, Multi-Channel, Multichannel, Multi-Channel limango, Multichannel limango, Multi Channel limango
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz limango in deinem plentymarkets System ein.
:position: 0
:url: maerkte/limango
:id: ZG3WRBH

[IMPORTANT]
.limango-Plugin herunterladen
====
Die Schnittstelle zu limango wird über ein Plugin integriert. Um das limango-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/limango_7023[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

[#100]
== Über limango

limango ist die Nr. 1 Plattform in Deutschland für junge Familien und ein Unternehmen der Otto-Group. Neben der geschlossenen Onlineshopping-Community betreibt limango auch den offenen link:https://www.limango.de/shop[Shop^]{nbsp}icon:external-link[]. Seit dem Launch des Marktplatzes im Jahr 2017 profitieren Endkunden auch von einem breiten, dauerhaft verfügbaren Sortiment, hinter dem inzwischen mehr als 300 Partner stehen.

[#150]
== Partner:in bei limango werden

Tritt der Nr. 1 Plattform für Familienshopping bei und klicke link:https://entdecke.limango.de/marktplatz-partnerprogramm[hier^]{nbsp}icon:external-link[], um mehr über den limango Marktplatz und unser Partnerprogramm zu erfahren und deine Registrierungsanfrage abzusenden.

Wende dich zur Registrierung alternativ gern auch direkt an das Team des Partnermanagements unter marketplace@limango.de. Ein Partnermanager wird sich bald mit dir in Verbindung setzen und mit dir gemeinsam das Potenzial auf link:https://www.limango.de[limango.de^]{nbsp}icon:external-link[] evaluieren und die nächsten Schritte besprechen.

[#200]
== Übersicht des automatischen Datenaustauschs mit limango

Nachdem du das Plugin installiert und eingerichtet hast, stehen die in <<#datenaustausch-limango>> automatisierten Abläufe bereit:

[[datenaustausch-limango]]
.Häufigkeit des Datenaustauschs
[cols="1,3"]
|====
|Daten |Intervall

2+| Artikeldaten

| Artikelexport
| einmal täglich

| Bestandsabgleich
| stündlich +
*_Tipp:_* Aus technischen Gründen sind kürzere Abstände beim Bestandsabgleich nicht möglich. Lege bei Bedarf einen <<#300, Bestandspuffer>> fest, um Überverkäufe zu verhindern.

| Preisabgleich
| stündlich

2+| Auftragsdaten

| Auftragsimport
| viertelstündlich +
*_Hinweis:_* Kund:innen zahlen an limango. Deshalb werden alle Aufträge mit dem Status *[5] Bezahlt* importiert.
|====

[#220]
== Ablauf einer Bestellung bei limango

* Deine Produkte werden im limango Marktplatz gelistet. Der Name deines Unternehmens wird an deinen Produkten angezeigt.
* Kund:innen geben eine Bestellung auf limango auf.
* Kund:innen zahlen an limango.
* Der Auftrag wird in plentymarkets importiert. +
*_Hinweis:_* Da Kund:innen an limango zahlen, werden Aufträge mit dem Status *[5] Bezahlt* importiert.
* Bei Eingang der Bestellung versendest du die Ware (Dropshipping).
* limango kümmert sich um die gesamte Kommunikation mit Kund:innen und um den Kund:innenservice.

[#170]
== limango-Plugin installieren

Um limango in plentymarkets nutzen zu können, installiere zunächst das link:https://marketplace.plentymarkets.com/limango_7023[limango-Plugin^] in deinem plentymarkets System. Das Plugin findest du im link:https://marketplace.plentymarkets.com/[plentyMarketplace^]{nbsp}icon:external-link[].

[.collapseBox]
.So installierst du das limango-Plugin
--
:plugin: limango

include::../plugins/_textblocks/instructions/plugin-installieren.adoc[]
--

[#300]
== limango einrichten

Nachdem du das limango-Plugin installiert hast, richtest du den Marktplatz in den Plugin-Einstellungen ein.

[.instruction]
limango einrichten:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht*. +
→ Die Liste der Plugin-Sets wird geöffnet.
. Klicke auf das Plugin-Set, in dem du das limango-Plugin installiert hast. +
→ Das Plugin-Set wird geöffnet.
. Klicke auf das Plugin *limango*. +
→ Die Plugin-Einstellungen werden geöffnet.
. Nimm die Einstellungen vor. Beachte die Hinweise in <<#limango-setup>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.


[[limango-setup]]
.limango einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+| *SFTP-Zugangsdaten*

| *Host*
| `ftp-partner.limango.de` eingeben.

| *Port*
| Port `22` eingeben.

| *Benutzername* +
*Passwort*
| Diese Zugangsdaten erhältst du von limango.

2+| *Plugin-Artikeleigenschaften*

| *limango-Kategorieeigenschaft*
| Die ID der Eigenschaft *limangoTemplate*, die automatisch beim Installieren des Plugins erstellt wird. Diese ID wird automatisch eingetragen.

2+| *Durch Plugin erstellte Felder*

| *Durch Plugin erstellte Auftragsherkunft-ID*
| Die ID der Auftragsherkunft *limango*, die automatisch beim Installieren des Plugins erstellt wird. Diese ID wird automatisch eingetragen.

| *Status des letzten Preisexports*
a| * *1* = Die Preise wurden erfolgreich zu limango exportiert. Der Zeitpunkt des Exports wird unter *Zeitpunkt des letzten erfolgreichen Preisexports* angezeigt.
* *2* = Der letzte Preisexport ist fehlgeschlagen.

| *Zeitpunkt des letzten erfolgreichen Preisexports*
| Der Zeitstempel des letzten erfolgreichen Preisexports.

2+| *Bestandsexport*

| *Bestandspuffer*
| Die Bestandssumme aller Lager wird an limango übertragen. Ganze Zahl eingeben, um die übertragene Bestandsmenge um den eingegebenen Wert zu reduzieren. +
*_Hinweis:_* Bestandsdaten werden einmal stündlich an limango übertragen. Aus technischen Gründen sind kürzere Abstände nicht möglich. Der Bestandspuffer hilft dir, Überverkäufe zu verhindern.

|====

[#600]
== Auftragsherkunft aktivieren

:market: limango
:referrer: limango
:referrer-option: pass:quotes[Option *limango*]

include::_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#500]
== Verkaufspreis festlegen

:referrer-price: limango

include::_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#750]
== Variantenverfügbarkeit einstellen

:market-availability: limango
:option-availability: limango

include::_textblocks/instructions/variantenverfuegbarkeit.adoc[]

// Web-API NICHT erforderlich!

[#800]
== Varianten mit Eigenschaft limangoTemplate verknüpfen

Varianten, die du auf limango verkaufen möchtest, müssen mit der Eigenschaft *limangoTemplate* verknüpft werden. Diese Eigenschaft wird in deinem plentymarkets System erstellt, sobald du das limango-Plugin installiert hast.

:property-link: limangoTemplate

include::_textblocks/instructions/properties-link-to-variation.adoc[]

[#900]
== Artikelexport einrichten

Artikeldaten werden über Katalog-Formate zu limango übertragen. Kataloge erstellst du im Menü *Daten » Kataloge*. Du arbeitest zum ersten Mal mit den Katalogen? Dann solltest du dich zuerst <<daten/daten-exportieren/kataloge-verwalten#, mit dem Prinzip der Kataloge vertraut machen>>.

Damit du deine Artikel zu limango exportieren kannst, musst du einen Katalog erstellen. Verknüpfe anschließend im Marktplatz-Format die von limango vorgegebenen Felder mit den in plentymarkets gespeicherten Artikeldaten. Die Katalogdaten werden automatisch in regelmäßigen Abständen zu limango exportiert, wenn du den Katalog aktivierst.

[#901]
=== Besonderheiten der limango-Artikeldatenstruktur

Die Struktur der Artikeldaten von limango unterscheidet sich von der Struktur in plentymarkets. Die limango Artikeldatenstruktur gliedert sich in drei Ebenen:

. *Produktgruppe:* Ein Produkt in allen Ausprägungen
. *Produkt:* Eine Farbvariation des Produkts
. *Variante:* Die Größe / EAN / SKU

Gibt es ein Produkt in nur einer Ausprägung, dann ist Produktgruppe gleich Variante.

[#902]
=== Katalog erstellen

Artikeldaten werden über das Marktplatz-Format *limango* zu limango übertragen. Um deine Artikel zu limango zu übertragen, erstellst du im Menü *Daten » Kataloge* einen Katalog. Verknüpfe dann im Marktplatz-Format die von limango vorgegebenen Felder mit in plentymarkets gespeicherten Artikeldaten. Du arbeitest zum ersten Mal mit den Katalogen? Dann solltest du dich zuerst <<daten/daten-exportieren/kataloge-verwalten#, mit dem Prinzip der Kataloge vertraut machen>>.

TIP: Du kannst für limango nur einen Katalog anlegen. Mehrere Kataloge werden für limango aktuell nicht unterstützt.

:catalogue-template-name: limango
:catalogue-plugin:

include::_textblocks/instructions/katalog-erstellen.adoc[]

[#903]
=== Katalogzuordnungen vornehmen

Nachdem du einen Katalog erstellt hast, ordnest du die Datenfelder des Marktplatzes den in plentymarkets gespeicherten Artikeldaten zu. In diesem Kapitel erfährst du, wie du Datenfelder zuordnest und welche Besonderheiten es bei limango gibt. Außerdem findest du hier Empfehlungen für eine korrekte Zuordnung. Die Informationen sind wie folgt aufgebaut:

* <<#907, Datenfelder im Katalog zuordnen>>
* <<#905, Besonderheiten bei der Zuordnung von Datenfeldern>>
* <<#906, Empfehlungen für limango Datenfeld-Zuordnungen>>

[#907]
==== Datenfelder im Katalog zuordnen

Ordne nun du die Datenfelder von limango den in plentymarkets gespeicherten Artikeldaten zu. Beachte die Informationen zu Besonderheiten und Empfehlungen in diesem Kapitel.

include::_textblocks/instructions/katalog-datenfelder-zuordnen.adoc[]

[#905]
==== Besonderheiten bei der Zuordnung von Datenfeldern

Jeder Marktplatz strukturiert seine Artikeldaten anders. Deshalb treten bei der Zuordnung von Datenfeldern bestimmte Sonderfälle auf. In <<#catalogue-limango-mappings>> findest du Hinweise dazu, was du beim Zuordnen von Datenfeldern für limango beachten solltest.

[[catalogue-limango-mappings]]
.Besonderheiten bei der Katalogzuordnung
[cols="1,3"]
|====
| Marktplatz-Datenfeld | plentymarkets Datenfeld

| *Beschreibung*
a| Wenn du Schuhe auf dem limango-Marktplatz verkaufen möchtest, müssen Informationen zum Material über das Feld *Beschreibung* an limango exportiert werden. Dazu kombinierst du zwei plentymarkets Datenfelder und exportierst sie als ein Feld an limango.

Entscheide zunächst, wie du die Materialangaben am Artikel pflegen möchtest. Materialangaben kannst du auf zwei Arten an die Beschreibung anhängen:

* Du nutzt das Datenfeld *Technische Daten* des Artikels für Materialangaben.

_oder_

* Du erstellst eine Eigenschaft des Typs *Text*. Diese Eigenschaft verknüpfst du mit der Hauptvariante des Artikels und pflegst die Materialangaben in dieser Eigenschaft.

Nun ordnest du das plentymarkets Datenfeld, für das du dich entschieden hast, im Katalog zu:

. Ordne dem Marktplatz-Datenfeld *Beschreibung* das plentymarkets Datenfeld zu, das die Artikelbeschreibung enthält.
. Klicke rechts neben diesem Datenfeld auf *Datenfeld hinzufügen* (icon:link[rotate=90]).
. Ordne das plentymarkets Datenfeld zu, das die Materialangaben enthält. +
*_Tipp:_* Also entweder das Feld *Technische Daten* oder die Eigenschaft, die du für die Materialangaben erstellt hast.
. Klicke ganz rechts in der Zeile auf *Einstellungen* (icon:cog[]).
. Wähle aus der Dropdown-Liste *Trennzeichen* die Option *Leerzeichen*.

| Maßangaben mit Entsprechungen in plentymarkets +
(*Länge*; +
*Breite*; +
*Höhe*; +
etc.)
a| Maßangaben müssen im Format *[Zahlenwert];[Einheit]* zu limango exportiert werden. Zahlenwert und Einheit werden in plentymarkets in unterschiedlichen Datenfeldern gespeichert. Deshalb kombinierst du zwei plentymarkets Datenfelder mit einem Semikolon als Trennzeichen.

[.collapseBox]
.*_Beispiel:_* Länge an limango exportieren
--
. Ordne dem Marktplatz-Datenfeld *Länge* das plentymarkets Datenfeld *Länge mm* zu.
. Klicke rechts neben diesem Datenfeld auf *Datenfeld hinzufügen* (icon:link[rotate=90]).
. Ordne ein Feld *Eigener Wert* zu.
. Gib in dieses Feld *mm* ein.
. Klicke ganz rechts in der Zeile auf *Einstellungen* (icon:cog[]).
. Wähle aus der Dropdown-Liste *Trennzeichen* die Option *Semikolon*.
--

| Maßangaben ohne Entsprechungen in plentymarkets +
(z.B. *Durchmesser*; +
*Schafthöhe*; +
*Absatzhöhe*; +
etc.)
a| Maßangaben müssen im Format *[Zahlenwert];[Einheit]* zu limango exportiert werden. Für Maßangaben, für die es von Haus aus kein Datenfeld in plentymarkets gibt, erstellst du zwei Eigenschaften:

* Eine Eigenschaft des Typs *Kommazahl* für den Zahlenwert.
* Eine Eigenschaft des Typs *Auswahl* für die Einheit.

Diese beiden Eigenschaften kombinierst du mit einem Semikolon als Trennzeichen.

[.collapseBox]
.*_Beispiel:_* Durchmesser an limango exportieren
--
. Erstelle eine Eigenschaft des Typs *Kommazahl* mit dem Namen *Durchmesser*.
. Erstelle eine Eigenschaft des Typs *Auswahl* mit dem Namen *Durchmesser Einheit*.
. Füge zur Eigenschaft *Durchmesser Einheit* alle Einheiten als Eigenschaftswerte hinzu, die du benötigst. +
*_Tipp:_* Wenn du dir sicher bist, dass du für alle deine Artikel nur eine einzige Einheit benötigst, kannst du die Einheit auch als eigenen Wert übergeben (siehe Beispiel *Länge* oben).
. Ordne dem Marktplatz-Datenfeld *Durchmesser* die plentymarkets Eigenschaft *Durchmesser* zu.
. Klicke rechts neben diesem Datenfeld auf *Datenfeld hinzufügen* (icon:link[rotate=90]).
. Ordne die Eigenschaft *Durchmesser Einheit* zu.
. Klicke ganz rechts in der Zeile auf *Einstellungen* (icon:cog[]).
. Wähle aus der Dropdown-Liste *Trennzeichen* die Option *Semikolon*.
--

| Datenfelder im Bereich Materialzusammensetzung
a| Materialangaben werden mit Eigenschaften des Typs *Kurztext* an limango übertragen. Pro Marktplatz-Datenfeld benötigst du eine Eigenschaft. An der Hauptvariante speicherst du alle Bestandteile des Materialmix des Artikels in dieser Eigenschaft.
Die Materialzusammensetzung gibst du im folgenden Format ein:

* *{"material1": "prozentwert","material2": "prozentwert","material3": "prozentwert"}* +
*_Beispiel:_* *{"baumwolle": "90","elastan": "10"}*

Die einzelnen Materialien müssen mit absteigender Prozentangabe eingetragen werden. An erster Stelle steht also das Material mit dem höchsten Prozentanteil, an letzter Stelle das Material mit dem niedrigsten Prozentanteil. Die Summe aller Prozentangaben muss 100 ergeben. Du kannst beliebig viele Materialien angeben.

[.collapseBox]
.*_Beispiel:_* Materialangaben für einen Damenblazer an limango exportieren
--
Als Beispiel wird hier beschrieben, wie du die Materialangaben für einen Blazer für den Export zu limango speicherst.

. Erstelle eine Eigenschaft des Typs *Kurztext* mit dem Namen *Material 1*.
. Ordne dem Marktplatz-Datenfeld *Material 1* die plentymarkets Eigenschaft *Material 1* zu.
. Verknüpfe die Eigenschaft *Material 1* mit der Hauptvariante des Artikels.
. Unser Beispielblazer besteht aus 65% Polyester, 32% Viskose und 3% Elastan. In das Eingabefeld der Eigenschaft gibst du also ein:
  * {"polyester": "65","viskose": "32","elastan": "3"}
. Speichere die Einstellungen.

. Erstelle eine Eigenschaft des Typs *Kurztext* mit dem Namen *Futter 1*.
. Ordne dem Marktplatz-Datenfeld *Futter 1* die plentymarkets Eigenschaft *Futter 1* zu.
. Verknüpfe die Eigenschaft *Futter 1* mit der Hauptvariante des Artikels.
. Das Futter unseres Beispielblazers besteht aus 100% Viskose. In das Eingabefeld der Eigenschaft gibst du also ein:
  * {"viskose": "100"}
. Speichere die Einstellungen.
--
|====

[#910]
==== Empfehlungen für limango Datenfeld-Zuordnungen

Um dich beim Erstellen eines Katalogs für limango zu unterstützen, haben wir eine Liste mit empfohlenen Datenfeld-Zuordnungen für limango zusammengestellt. Beachte, dass es sich hierbei nur um Empfehlungen handelt. Je nachdem, wie du deine Artikeldaten pflegst, können andere Zuordnungen sinnvoller sein als die hier gegebenen Empfehlungen.

[.collapseBox]
.Liste mit empfohlenen Datenfeld-Zuordnungen für limango
--
include::_textblocks/explanations/limango-recommended-mappings.adoc[]
--

[#904]
=== Katalog aktivieren

:interval: einmal täglich nachts
:market: limango

include::_textblocks/instructions/catalogue-activation.adoc[]

== Stornierungen automatisch an limango melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um limango automatisch über Stornierungen zu informieren.

:table-event-procedure: <<#ereignisaktion-stornierung-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-stornierung-limango]]
.Ereignisaktion, um Stornierungen an limango zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[8] Storniert*.

| *Filter*
| *Auftrag > Herkunft*
| *limango*

| *Aktion*
| *Plugins > limango: Auftragsstornierung an limango melden*
|
|===

[#1300]
== Automatische Versandbestätigungen einrichten

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um automatisch eine Versandbestätigung an limango zu senden, nachdem der Warenausgang einer Bestellung gebucht wurde.

:table-event-procedure: <<#ereignisaktion-versandbestätigung-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-versandbestätigung-limango]]
.Ereignisaktion, um Versandbestätigungen an limango zu melden
[cols="1,2,2"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. [7] *Warenausgang gebucht*.

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Herkunft*
| *limango*

| *Aktion*
| *Plugin*
| *Versandinformation an limango melden*
|===

[#1000]
== Retourenverwaltung einrichten

Richte nun die Verwaltung von Retouren für limango ein.

[#1010]
=== Ablauf von Retouren

Der Lieferschein ist gleichzeitig Retourenschein. Eine Retoure läuft bei limango wie folgt ab:

. Kund:innen senden die Ware an dich zurück.
. Du führst die Retoure in plentymarkets aus.
. Du informierst limango darüber, dass du die Ware erhalten hast.
. limango erstattet Käufer:innen den Kaufpreis zurück. +
*_Hinweis:_* Wenn du limango mitteilst, dass die Retoure abgeschlossen ist, wird bei limango eine Gutschrift ausgelöst und Endkund:innen erhalten eine Rückerstattung. Achte deshalb darauf, dass du limango erst über den Abschluss der Retoure informierst, nachdem du die Ware erhalten und geprüft hast.

[#1030]
=== Retourenabschluss automatisch an limango melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um limango automatisch darüber zu informieren, dass eine Retoure abgeschlossen wurde.

:table-event-procedure: <<#ereignisaktion-retouren-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-retouren-limango]]
.Ereignisaktion zum automatischen Melden von Retouren an limango
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Ereignis wählen, z.B. *Auftragsänderung: Statuswechsel* +
*_Hinweis:_* Wähle einen Status, der zu deinem Arbeitsablauf passt. Du kannst dafür beispielsweise den Status *[9.12] Retoure an limango melden* erstellen.
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Retoure*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *limango*

| *Aktion*
| *Auftrag &gt; Retourenabschluss an limango melden* +
*_Hinweis:_* Durch die Aktion *Retourenabschluss an limango melden* wird bei limango eine Gutschrift ausgelöst. Endkund:innen erhalten also eine Rückerstattung. Achte deshalb darauf, dass die Ereignisaktion erst ausgelöst wird, nachdem du die retournierte Ware erhalten und geprüft hast.
|
|====

[#1600]
== Lieferscheine für limango vorbereiten

Auf Lieferscheinen für limango-Aufträge müssen der limango-Briefkopf und ein von limango vorgegebenen Retourenhinweis erscheinen.

* <<#16001, So lädst du eine PDF-Vorlage für Lieferscheine hoch>>
* <<#16001, So gibst du den Retourenhinweis für limango-Lieferscheine ein>>

[#16001]
=== PDF-Vorlage für Lieferscheine hochladen

limango-Lieferscheine müssen das Logo von limango verwenden. Gehe wie unten beschrieben vor, um eine <<auftraege/auftragsdokumente#170, PDF-Vorlage>> für Lieferscheine für limango in plentymarkets hochzuladen.

[.instruction]
PDF-Vorlage für Lieferscheine hochladen:

. Lade die PDF-Vorlage für Lieferscheine von limango herunter und speichere sie auf deinem Rechner:
  ** link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/Lieferschein_Vorlage_limango_Marktplatz.pdf[PDF-Vorlage herunterladen]
. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » Standort: Deutschland » Dokumente » Lieferschein*.
. Wechsele in das Tab *PDF-Vorlage*.
. Klicke auf *Vorlage hinzufügen*. +
→ Das Bearbeitungsfenster *Neue PDF-Vorlage hochladen* wird geöffnet.
. Wähle aus der Dropdown-Liste *Zahlungsart* die Option *Plugin: limango Payment*.
. *_Optional:_* Die Zahlungsart *Plugin: limango Payment* wird nicht in der Dropdown-Liste angezeigt?
  .. Öffne das Menü *Einrichtung » Aufträge » Einstellungen*.
  .. Wähle für die Einstellung *Inaktive Plugin-Zahlungsarten anzeigen* die Option *Ja*.
  .. *Speichere* (icon:save[role="green"]) die Einstellung.
. Wähle in der Dropdown-Liste *Sprache* die Option *de*.
. Klicke in der Zeile *Vorlage* auf *Vorlage auswählen*.
. Wähle die PDF-Vorlage für Lieferscheine von limango.
. Klicke auf *Vorlage hochladen* (icon:save[role="green"]). +
→ Die Vorlage wird hochgeladen.

[#16002]
=== Retourenhinweis für limango-Lieferscheine eingeben

Auf allen limango-Lieferscheinen muss ein von limango vorgegebener Retourenhinweis erscheinen. Gehe wie unten beschrieben vor, um diesen Retourenhinweis auf Lieferscheinen für limango einzugeben.

[.instruction]
Hinweis für limango-Lieferscheine eingeben:

. Klappe die "Textvorlage: Retourenhinweis für limango-Lieferscheine" unterhalb dieser Beschreibung auf.
. Kopiere den Text in die Zwischenablage.
. Öffne das Menü *Einrichtung » Mandant » Standard » Standorte » Deutschland » Dokumente » Lieferschein » Tab: Vorlage*.
. Scrolle im Bereich *Optionale Elemente unter Artikelpositionstabelle* zur Einstellung *Zahlungshinweis*.
. Gehe zu einem Eingabefeld, das noch keine Zahlungshinweise enthält.
. Wähle aus der Dropdown-Liste *Zahlungsart: bitte wählen* dieses Eingabefelds die Option *Plugin: limango Payment*.
. Kopiere den Retourenhinweis von limango in das Eingabefeld.
. Ersetze die beiden Platzhalter "xxx" durch den Namen deines Unternehmens.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#16003]
[.collapseBox]
.Textvorlage: Retourenhinweis für limango-Lieferscheine
--
include::_textblocks/explanations/limango-delivery-note-text.adoc[]
--
