= limango
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: limango, Marktplatz, limango.de, limango einrichten, limango Marktplatz, Multi-Channel, Multichannel, Multi-Channel limango, Multichannel limango, Multi Channel limango
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz limango in deinem plentymarkets System ein.
:position: 225
:url: maerkte/limango
:id: ZG3WRBH

[IMPORTANT]
.limango-Plugin herunterladen
====
Die Schnittstelle zu limango wird über ein Plugin integriert. Um das limango-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/XXXX_XXXX[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

[#100]
== Über limango

Zielgruppe von limango sind junge Familien und Frauen zwischen 25 und 50 Jahren mit Kindern zwischen 0 und 10 Jahren. limango ist die Plattform für Familienshopping in Europa – über eine Million aktive Kund:innen kaufen regelmäßig in unseren Verkaufsaktionen (über 4.500/Jahr), in unserem Shop oder im Marktplatz ein. Als Marktplatzpartner:in werden deine Produkte im limango Marktplatz gelistet. limango kümmert sich um den Kundenservice. Kund:innen zahlen an limango. Beim Eingang einer Bestellung versendest du die Ware (Dropshipping).

limango ist die Plattform für Familienshopping in Europa und kann mit über eine Million aktiven Kund:innen aufwarten. Du wirst als Verkäufer:in an deinen Produkten angezeigt. Die Kommunikation mit Kund:innen und die Bezahlung läuft aber über limango. +

Leistungen von limango:

* Übernahme des Kundenservices
* Übernahme des Zahlungsrisikos
* Simples Datenmapping

[#100]
== Bei limango registrieren

Voraussetzungen für eine Zusammenarbeit mit limango sind:

* Produktfrontansicht als Freisteller
* Deutsche Produktdaten
* Kostenlose Retoure
* Dropshipping

Wenn du diese Voraussetzungen erfüllst, nimm zunächst Kontakt zu limango auf, um dich als Händler:in zu registrieren. Schreibe dazu eine E-Mail an marketplace@limango.com. Nachdem du dich als Händler:in registriert hast, erhältst du Zugangsdaten von limango.

[#150]
=== limango-Plugin installieren

Um limango in plentymarkets nutzen zu können, musst du zunächst das link:XXXX[limango-Plugin^] in deinem plentymarkets System installieren. Das Plugin erhältst du im link:https://marketplace.plentymarkets.com/[plentyMarketplace^]{nbsp}icon:external-link[].

[#200]
== limango in plentymarkets installieren

xxxx

== Übersicht des automatischen Datenaustauschs

Nachdem du das Plugin installiert und eingerichtet hast, stehen die in <<#datenaustausch-limango>> automatisierten Prozesse bereit:

[[datenaustausch-limango]]
.Häufigkeit des Datenaustauschs
[cols="1,3"]
|====
|Daten |Intervall

2+| Artikeldaten

| Artikelexport
| einmal täglich //stimmt das!?!?!

| Bestandsabgleich
| viertelstündlich

| Preisabgleich
| stündlich

2+| Auftragsdaten

| Auftragsimport
| viertelstündlich +
*_Hinweis:_* Kund:innen zahlen an limango. Deshalb werden alle Aufträge mit dem Status *[5] Bezahlt* importiert.
|====


[#300]
=== Zugangsdaten im XXXX-Plugin speichern

Nachdem du das XXXX-Plugin installiert hast, speicherst du deine Zugangsdaten für limango, um den Zugang zur Schnittstelle zu ermöglichen.

[.instruction]
Zugangsdaten im XXXX-Plugin speichern:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht*. +
→ Die Liste der Plugin-Sets wird geöffnet.
. Klicke auf das Plugin-Set, in dem du das xxx-Plugin installiert hast. +
→ Das Plugin-Set wird geöffnet.
. Klicke auf das Plugin *xxxx*. +
→ Die Plugin-Einstellungen werden geöffnet.
. Klicke auf *Konfiguration*.
. Klicke auf *Einstellungen*.
. Gib *Host*, *Port*, *Benutzername* und *Passwort* ein. +
*_Tipp:_* Diese Informationen erhältst du von limango.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#600]
== Auftragsherkunft aktivieren

:market: limango
:referrer: limango
:referrer-option: pass:quotes[Option *limango*]

include::_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#500]
== Verkaufspreis festlegen

:referrer-price: limango

include::../_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#700]
== Variantenverfügbarkeit einstellen

:market-availability: limango
:option-availability: limango

include::_textblocks/instructions/variantenverfuegbarkeit.adoc[]

// Web-API NICHT erforderlich!XXXX?

[#900]
== Artikelexport einrichten

Artikeldaten werden über Katalog-Templates zu limango übertragen. Kataloge erstellst du im Menü *Daten » Kataloge*. Du arbeitest zum ersten Mal mit den Katalogen? Dann solltest du dich zuerst mit dem grundlegenden Prinzip der <<daten/daten-exportieren/kataloge-verwalten#, Kataloge vertraut machen>>.

Damit du deine Artikel zu limango exportieren kannst, musst du für die verschiedenen Produktkategorien von limango Kataloge erstellen. Verknüpfe anschließend im Katalog-Template die von limango vorgegebenen Felder mit den in plentymarkets gespeicherten Artikeldaten. Die Katalog-Vorlagen werden automatisch xxx täglich zu limango exportiert, sobald du den Katalog aktivierst.

[#902]
=== Katalog erstellen

:catalogue-template-name: xxxx
:beispiel-feld: ddddd

include::../../_textblocks/instructions/katalog-erstellen.adoc[]


[#1500]
== Auftragsstatus bei limango automatisch aktualisieren

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um den Auftragsstatus bei limango automatisch zu aktualisieren, wenn bestimmte Ereignisse eintreten. Folgende Ereignisaktionen können eingerichtet werden:

* Versandbestätigung für komplette Lieferung an limango melden(XXXwording)
* Versandbestätigung für Teillieferung an limango melden(XXXwording)
* Retourenabschluss an limango melden

Beispielhaft wird hier eine Ereignisaktion beschrieben, mit der du die Versandbestätigung an XXXX meldest. Richte weitere Ereignisaktionen analog dazu ein.

:table-event-procedure: <<#XXXX-ereignisaktion>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[XXXX-ereignisaktion]]
.Ereignisaktion, um Auftragsstatus an XXXX zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Auftragsänderung: Statuswechsel*
| *Status* wählen.

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Herkunft*
| *XXXX*

| *Aktion*
| *Plugin*
| *Versandbestätigung an XXXX melden*
|===

[#600]
== Zahlungsart aktivieren

:paymentmethod: limango
:folder: InternationalXXXX

include::../_textblocks/instructions/zahlungsart_aktivieren.adoc[]

== Retourenverwaltung einrichten

=== Ablauf von Retouren

////
. Der Kunde kündigt bei limango die retoure an
. Der Händler führt die Retoure manuell in plenty aus
. Der Händler informiert limango darüber, dass die retoure eingegangen ist
. limango erstattet dem Kunden den Kaufpreis zurück
////

[#1200]
=== XXXRetourengründe verknüpfen

Im Menü *xxxx* verknüpfst du die in plentymarkets gespeicherten Retourengründe mit den Retourengründen von XXXX. Wenn du keinen Retourengrund verknüpfst, wird automatisch der Retourengrund *Sonstiges* zu XXXX übertragen. Weitere Informationen zu XXXX-Retourengründen findest du in der Händlerdokumentation, die du von XXXX erhalten hast.

[.instruction]
Retourengründe verknüpfen:

. Öffne das Menü *xxxx*.
. Wähle aus der Dropdown-Liste den XXXX-Retourengrund.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

=== Retourenabschluss automatisch an limango melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um limango automatisch darüber zu informieren, dass eine Retoure abgeschlossen wurde.

[IMPORTANT]
.Retourengründe verknüpfen
====
Für Retouren müssen plentymarkets Retourengründe mit von limango vorgegebenen Retourengründen verknüpft sein. Wenn beispielsweise die Ereignisaktion *Retourenabschluss an limango melden* ausgelöst wird, muss ein Retourengrund gespeichert sein. Weitere Informationen zur Retourengrund-Verknüpfung findest du im Kapitel <<#1200, Retourengründe verknüpfen>>.
====

:table-event-procedure: <<#ereignisaktion-retouren-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-retouren-limango]]
.Ereignisaktion zum automatischen Melden von Retouren an limango
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsanlage: Neue RetoureXXX*
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Retoure*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *limango*

| *Aktion*
| *Auftrag &gt; Retourenabschluss an limango melden* +
*_Hinweis:_* Durch die Aktion *Retourenabschluss an limango melden* wird bei limango eine Gutschrift ausgelöst und Endkund:innen erhalten eine Rückerstattung. Achte deshalb darauf, dass die Ereignisaktion erst ausgelöst wird, wenn du die retournierte Ware erhalten und geprüft hast.
|
|====

////
siehe auch:

[#1050]
== Auftragsbearbeitung bei OTTO Market
Prüfen, ob noch was relevant ist

[#800]
== bol.com über direkte Retouren informieren

[#1000]
== Log-Einträge abrufen

[#800]
== Retourenstatus automatisch senden

Nachdem du mit dem Assistenten OTTO Market Kataloge erstellen oder manuell ein Katalog-Template für OTTO Market erstellt hast, wird in deinem plentymarkets System die Eigenschaft OTTO-Kategoriegruppe erstellt.

11.1. Retourenlabel generieren (otto market)

11.5. Ablehnung der Retoure an OTTO melden
////

TODO

* Save plugin credentials in plugin config
* include info on how to install the plugin - callapsebox?
* add info that all orders are paid and imported with status 5 - where?
* shipping confirmation - how to set up EA for partial delivery and no delivery?
* shipping confirmation for complete shipment
* how to do return in plenty manually?
* return reasons - how to set up and map to limango reasons?
