= limango
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: limango, Marktplatz, limango.de, limango einrichten, limango Marktplatz, Multi-Channel, Multichannel, Multi-Channel limango, Multichannel limango, Multi Channel limango
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz limango in deinem plentymarkets System ein.
:position: 0
:url: maerkte/limango
:id: ZG3WRBH

[IMPORTANT]
.limango-Plugin herunterladen
====
Die Schnittstelle zu limango wird über ein Plugin integriert. Um das limango-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/XXXX_XXXX[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

[#100]
== Über limango

limango ist die Nr. 1 Plattform in Deutschland für junge Familien und ein Unternehmen der Otto-Group. Neben der geschlossenen Onlineshopping-Community betreibt limango auch den offenen <a href="https://www.limango.de/shop" target="_blank" rel="noopener">Shop</a>. Seit dem Launch des Marktplatzes 2017 profitieren Endkunden auch von einem breiten, dauerhaft verfügbaren Sortiment, hinter dem inzwischen mehr als 300 Partner stehen.

[#150]
== Partner:in bei limango werden

Tritt der Nr. 1 Plattform für Familienshopping bei und klicke <a href="https://entdecke.limango.de/marktplatz-partnerprogramm/" target="_blank" rel="noopener">hier</a>, um mehr über den limango Marktplatz und unser Partnerprogramm zu erfahren.

Wende dich zur Registrierung direkt an das Team des Partnermanagements unter <a href="mailto:marketplace@limango.de">marketplace@limango.de</a>. Ein Partnermanager wird sich bald mit dir in Verbindung setzen und mit dir gemeinsam das Potenzial auf <a href="https://www.limango.de" target="_blank" rel="noopener">limango.de</a> evaluieren.

[#200]
== Übersicht des automatischen Datenaustauschs mit limango

Nachdem du das Plugin installiert und eingerichtet hast, stehen die in <<#datenaustausch-limango>> automatisierten Abläufe bereit:

[[datenaustausch-limango]]
.Häufigkeit des Datenaustauschs
[cols="1,3"]
|====
|Daten |Intervall

2+| Artikeldaten

| Artikelexport
| einmal täglich

| Bestandsabgleich
| viertelstündlich//Stündlich???

| Preisabgleich
| stündlich

2+| Auftragsdaten

| Auftragsimport
| viertelstündlich +
*_Hinweis:_* Kund:innen zahlen an limango. Deshalb werden alle Aufträge mit dem Status *[5] Bezahlt* importiert.
|====

[#220]
== Ablauf einer Bestellung bei limango

* Deine Produkte werden im limango Marktplatz gelistet. Der Name deines Unternehmens wirst an deinen Produkten angezeigt.
* Kund:innen geben eine Bestellung auf limango auf.
* Kund:innen zahlen an limango.
* Der Auftrag wird in plentymarkets importiert. +
*_Hinweis:_* Da Kund:innen an limango zahlen, werden Aufträge mit dem Status *[5] Bezahlt* importiert.
* Bei Eingang der Bestellung versendest du die Ware (Dropshipping).
* limango kümmert sich um die gesamte Kommunikation mit Kund:innen und um den Kund:innenservice.

[#170]
== limango-Plugin installieren

Um limango in plentymarkets nutzen zu können, installiere zunächst das link:XXXX[limango-Plugin^] in deinem plentymarkets System. Das Plugin findest du im link:https://marketplace.plentymarkets.com/[plentyMarketplace^]{nbsp}icon:external-link[].

[.collapseBox]
.So installierst du das limango-Plugin
--
include::../plugins/_textblocks/instructions/plugin-installieren.adoc[]
--

[#300]
== Zugangsdaten im limango-Plugin speichern

Nachdem du das limango-Plugin installiert hast, speicherst du deine Zugangsdaten für limango in den Plugin-Einstellungen.

[.instruction]
Zugangsdaten im limango-Plugin speichern:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht*. +
→ Die Liste der Plugin-Sets wird geöffnet.
. Klicke auf das Plugin-Set, in dem du das limango-Plugin installiert hast. +
→ Das Plugin-Set wird geöffnet.
. Klicke auf das Plugin *limango*. +
→ Die Plugin-Einstellungen werden geöffnet.
. Klicke auf *Konfiguration*.
. Klicke auf *Einstellungen*.
. Gib *Host*, *Port*, *Benutzername* und *Passwort* ein. +
*_Tipp:_* Diese Informationen erhältst du von limango.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#600]
== Auftragsherkunft aktivieren

:market: limango
:referrer: limango
:referrer-option: pass:quotes[Option *limango*]

include::_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#700]
== Zahlungsart aktivieren

Kund:innen zahlen an limango. Deshalb werden alle Aufträge mit dem Status *[5] Bezahlt* und der Zahlungsart *limango* importiert.

:paymentmethod: limango
:folder: InternationalXXXX

include::../_textblocks/instructions/zahlungsart_aktivieren.adoc[]

[#500]
== Verkaufspreis festlegen

:referrer-price: limango

include::../_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#750]
== Variantenverfügbarkeit einstellen

:market-availability: limango
:option-availability: limango

include::_textblocks/instructions/variantenverfuegbarkeit.adoc[]

// Web-API NICHT erforderlich!XXXX?

[#900]
== Artikelexport einrichten

Artikeldaten werden über Katalog-Formate zu limango übertragen. Kataloge erstellst du im Menü *Daten » Kataloge*. Du arbeitest zum ersten Mal mit den Katalogen? Dann solltest du dich zuerst mit dem grundlegenden Prinzip der <<daten/daten-exportieren/kataloge-verwalten#, Kataloge vertraut machen>>.

Damit du deine Artikel zu limango exportieren kannst, musst du für die verschiedenen Produktkategorien von limango Kataloge erstellen. Verknüpfe anschließend im Marktplatz-Format die von limango vorgegebenen Felder mit den in plentymarkets gespeicherten Artikeldaten. Die Katalogdaten werden automatisch in regelmäßigen Abständen zu limango exportiert, wenn du den Katalog aktivierst.

[#902]
=== Katalog erstellen

:catalogue-template-name: limango

include::../../_textblocks/instructions/katalog-erstellen.adoc[]

[#903]
=== Datenfelder im Katalog zuordnen

include::../../_textblocks/instructions/katalog-datenfelder-zuordnen.adoc[]

[#904]
=== Katalog aktivieren

:interval: einmal täglich nachts
:market: limango

include::../_textblocks/instructions/catalogue-activation.adoc[]

[#1000]
== Retourenverwaltung einrichten

[#1010]
=== Ablauf von Retouren

Eine Retoure läuft bei limango wie folgt ab:

. Kund:innen kündigen die Retoure bei limango an.
. Du führst die Retoure manuell in plentymarkets aus.
. Kund:innen senden die Ware an dich zurück.
. Du informierst limango darüber, dass du die Ware erhalten hast.
. limango erstattet Käufer:innen den Kaufpreis zurück. +
*_Hinweis:_* Wenn du limango mitteilst, dass die Retoure abgeschlossen ist, wird bei limango eine Gutschrift ausgelöst und Endkund:innen erhalten eine Rückerstattung. Achte deshalb darauf, dass du limango erst informierst, nachdem du die retournierte Ware erhalten und geprüft hast.

[#1020]
=== Retourengründe verknüpfen

Im Menü *xxxx* verknüpfst du die in plentymarkets gespeicherten Retourengründe mit den Retourengründen von limango. Weitere Informationen zu den Retourengründen von limango findest du in der Dokumentation, die du von limango erhalten hast.

[.instruction]
Retourengründe verknüpfen:

. Öffne das Menü *xxxx*.
. Wähle aus der Dropdown-Liste den limango-Retourengrund.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#1030]
=== Retourenabschluss automatisch an limango melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um limango automatisch darüber zu informieren, dass eine Retoure abgeschlossen wurde.

[IMPORTANT]
.Retourengründe verknüpfen
====
Für Retouren müssen plentymarkets Retourengründe mit von limango vorgegebenen Retourengründen verknüpft sein. Wenn beispielsweise die Ereignisaktion *Retourenabschluss an limango melden* ausgelöst wird, muss ein Retourengrund gespeichert sein. Weitere Informationen zur Retourengrund-Verknüpfung findest du im Kapitel <<#1200, Retourengründe verknüpfen>>.
====

:table-event-procedure: <<#ereignisaktion-retouren-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-retouren-limango]]
.Ereignisaktion zum automatischen Melden von Retouren an limango
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Ereignis wählen, z.B. *Auftragsänderung: Statuswechsel* +
*_Hinweis:_* Wähle einen Status, der zu deinem Arbeitsablauf passt. Du kannst dafür beispielsweise den Status *[9.12] Retoure an limango melden* erstellen.
|

| *Filter 1*
| *Auftrag &gt; Auftragstyp*
| *Retoure*

| *Filter 2*
| *Auftrag &gt; Herkunft*
| *limango*

| *Aktion*
| *Auftrag &gt; Retourenabschluss an limango melden* +
*_Hinweis:_* Durch die Aktion *Retourenabschluss an limango melden* wird bei limango eine Gutschrift ausgelöst.  Endkund:innen erhalten also eine Rückerstattung. Achte deshalb darauf, dass die Ereignisaktion erst ausgelöst wird, nachdem du die retournierte Ware erhalten und geprüft hast.
|
|====

[#1300]
== Automatische Versandbestätigungen einrichten

Richte <<automatisierung/ereignisaktionen#, Ereignisaktionen>> ein, um limango automatisch über Lieferungen und Teillieferungen zu informieren. Folgende Ereignisaktionen für den Versandstatus können eingerichtet werden:

* Versandbestätigung für komplette Lieferung an limango melden - so geht's
* Versandbestätigung für Teillieferung an limango melden - so geht's

[#1400]
=== Komplettlieferung an limango melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um automatisch eine Versandbestätigung an limango zu senden, nachdem der Warenausgang aller Artikel einer Bestellung gebucht wurde.

:table-event-procedure: <<#ereignisaktion-versandbestätigung-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-versandbestätigung-limango]]
.Ereignisaktion, um Versandbestätigungen für komplette Lieferungen an limango zu melden
[cols="1,2,2"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Auftragsänderung: Statuswechsel &gt; Warenausgang gebucht* +
oder *Auftragsänderung: Warenausgang gebucht*
|

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Herkunft*
| *limango*

| *Aktion*
| *Plugin*
| *Versandbestätigung für komplette Lieferung an limango melden*
|===

[#1500]
=== Teillieferung an limango melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um automatisch eine Versandbestätigung an limango zu senden, nachdem der Warenausgang nicht aller Artikel einer Bestellung gebucht wurde.

:table-event-procedure: <<#ereignisaktion-teil-versandbestätigung-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-teil-versandbestätigung-limango]]
.Ereignisaktion, um Versandbestätigungen für Teillieferungen an limango zu melden
[cols="1,2,2"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| xxx
|

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Herkunft*
| *limango*

| *Aktion*
| *Plugin*
| *Versandbestätigung für Teillieferung an limango melden*
|===

== Stornierungen automatisch an limango melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um limango automatisch über Stornierungen zu informieren.

:table-event-procedure: <<#ereignisaktion-stornierungen-limango>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-stornierung-limango]]
.Ereignisaktion, um Stornierungen an limango zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, z.B. *[8] Storniert*.

| *Filter*
| *Auftrag > Herkunft*
| *limango*

| *Aktion*
| *Plugins > limango: Auftragsstornierung an limango melden*
|
|===

////



[#1600]
== Log-Einträge abrufen


Nachdem du mit dem Assistenten OTTO Market Kataloge erstellen oder manuell ein Katalog-Template für OTTO Market erstellt hast, wird in deinem plentymarkets System die Eigenschaft OTTO-Kategoriegruppe erstellt.


TODO

* shipping confirmation - how to set up EA for partial delivery and no delivery?
* return reasons - how to set up and map to limango reasons?

////
