= myToys
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: myToys, myToys, mytoys, my toys, mytois, mirapodo, yomonda
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz myToys in deinem plentymarkets System ein.
:position: 0
:url: maerkte/mytoys
:id: CQERJR4

:market: myToys
:mytoys:

Mit mehr als 9 Millionen Bestellungen pro Jahr und über 4 Millionen aktiven Kund:innen ist myToys die führende Plattform für Family-Shopping in Deutschland. myToys bietet dir Verkaufsmöglichkeiten für die 3 Online-Shops myToys, mirapodo und yomonda mit nur einer technischen Integration.

[#150]
== Partner:in bei myToys werden

Klicke link:https://partnerprogramaccess.mytoys.de/Registrierung/[hier^]{nbsp}icon:external-link[], um mehr über den myToys Marktplatz und das Partnerprogramm zu erfahren und deine Registrierungsanfrage abzusenden.

Wende dich zur Registrierung alternativ gern auch direkt an das Team des Partnermanagements unter mailto:partnerteam@mytoys.de. Ein:e Partnermanager:in wird sich bald mit dir in Verbindung setzen und mit dir gemeinsam das Potenzial auf link:https://www.mytoys.de/[mytoys.de^]{nbsp}icon:external-link[] evaluieren und die nächsten Schritte besprechen.

Nach der Registrierung erhältst du Zugangsdaten für myToys. Diese Zugangsdaten benötigst du, um das myToys-Plugin einzurichten.

[#200]
== Übersicht des automatischen Datenaustauschs mit myToys

Nachdem du das Plugin installiert und eingerichtet hast, stehen die in <<#datenaustausch-myToys>> automatisierten Abläufe bereit.

[[datenaustausch-myToys]]
.Häufigkeit des Datenaustauschs
[cols="1,3a"]
|====
|Daten |Intervall

2+| Artikeldaten

| Artikelexport
| täglich +
*_Hinweis:_* Artikel werden ein bis zwei Mal pro Tag exportiert. Der Export beinhaltet auch den Preisabgleich für die enthaltenen Varianten.

| Bestandsabgleich
| alle 15 Minuten

2+| Auftragsdaten

| Auftragsimport
| alle 15 Minuten +
*_Hinweis:_* Kund:innen zahlen an myToys. Deshalb werden alle Aufträge mit dem Status *[5] Bezahlt* importiert. Wenn kein Bestand vorhanden ist oder keine SKU zugerdnet ist, bleibt der Auftrag in Auftragsstatus *[4] In Versandvorbereitung*.

|====

[#250]
== Ablauf einer Bestellung bei myToys

* Deine Produkte werden im myToys Marktplatz gelistet.
* Kund:innen geben eine Bestellung auf myToys auf.
* Kund:innen zahlen an myToys.
* Der Auftrag wird in plentymarkets importiert. +
*_Hinweis:_* Da Kund:innen an myToys zahlen, werden Aufträge mit dem Status *[5] Bezahlt* importiert.
* Bei Eingang der Bestellung versendest du die Ware (Dropshipping).

[#300]
== Plugin installieren

Um myToys in plentymarkets nutzen zu können, installiere zunächst das link:https://marketplace.plentymarkets.com/mytoys_54776[myToys-Plugin^] in deinem plentymarkets System. Dieses und viele andere Plugins findest du im link:https://marketplace.plentymarkets.com/[plentyMarketplace^]{nbsp}icon:external-link[].

:plugin: myToys
include::_textblocks/instructions/plugin-installation.adoc[]

[#300]
== Marktplatz einrichten

Nachdem du das Plugin installiert hast, richtest du den Marktplatz in plentymarkets ein.

[#350]
=== Datenaustausch mit myToys einrichten

Mit dem Assistenten *Grundeinstellungen - myToys* im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen]* richtest du den Datenaustausch mit myToys in plentymarkets ein. Halte dafür die Zugangsdaten bereit, die du von myToys erhalten hast.

:menu-path: pass:quotes[*Einrichtung » Assistenten » Omni-Channel*]
:assistant-name: Grundeinstellungen - myToys
:number-of-boxes: Info-Box

include::_textblocks/instructions/assistant-basic-instructions.adoc[]

[.collapseBox]
.Erläuterungen zu den Optionen des Assistenten
--
[[table-basic-settings-assistant]]
[width="100%"]
[cols="1,2a"]
|======
|Einstellung |Erläuterung

2+| Schritt *API-Einstellungen*

| *Kontonummer*; +
*Benutzername*; +
*Passwort*
| Diese Zugangsdaten erhältst du von myToys.

2+| Schritt *SFTP-Einstellungen*

| *Host*
| `sftp.trade-server.net` eingeben.

| *Port*
| Port `22` eingeben.

| *Benutzername*; +
*Passwort*
| Diese Zugangsdaten erhältst du von myToys.

2+| Schritt *Cron-Einstellungen*

| *Cron für Auftragsimport*
| Aktivieren, um den Auftragsimport zu aktivieren. Aufträge werden alle 15 Minuten importiert.

| *Cron für Produktexport*
| Aktivieren, um den Artikelexport zu aktivieren. +
*_Hinweis:_* Artikel werden ein bis zwei Mal pro Tag exportiert. Der Export beinhaltet auch den Preisabgleich für die enthaltenen Varianten.

| *Cron für Warenbestandsexport*
| Aktivieren, um den Warenbestandsexport zu aktivieren. Der Bestand wird alle 15 Minuten exportiert.

2+| Schritt *Versandprofilverknüpfung*

| Wähle ein oder mehrere bestehende Versandprofile und ordne es myToys zu.
| Welche Versanddienstleister möchtest du Kund:innen für myToys-Aufträge anbieten?

Alle externen Versanddienstleister mit plentymarkets <<fulfillment/versand-vorbereiten#1000#, Versandprofilen>> verknüpfen, die für myToys-Aufträge möglich sein sollen:

. Auf icon:plus-square[role="green"] klicken.
. plentymarkets Versandprofil aus der Dropdown-Liste *Internes Versandprofil* wählen.
. Passenden Versanddienstleister aus der Dropdown-Liste *Externer Versanddienstleister* wählen.

2+| Schritt *Lagerauswahl*

| Wähle die Lager, für die der Bestand mit myToys synchronisiert werden soll.
| Für welche Lager sollen Bestandsdaten an myToys exportiert werden?

Lege ein oder mehrere plentymarkets Lager fest, in denen sich die Artikel befinden, die du auf myToys verkaufen möchtest:

. Auf icon:plus-square[role="green"] klicken.
. plentymarkets Lager aus der Dropdown-Liste *Lagerl* wählen.

2+| Schritt *Mandantenauswahl*

| Wähle einen Mandanten, dem importierte Aufträge zugeordnet werden sollen.
| Wähle den Mandanten, über den du auf myToys verkaufen wirst. +
*_Hinweis:_* Wenn du deine Produkte über den Standardmandanten auf myToys anbieten möchtest, musst du keinen Mandanten wählen.
|====
--

[#400]
=== Auftragsherkunft aktivieren

:referrer: myToys
:referrer-option: pass:quotes[Option *myToys*]

include::_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#450]
=== Verkaufspreis festlegen

:referrer-price: myToys

include::_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#500]
=== Herkunft in Versandprofilen aktivieren

:referrer: myToys

include::_textblocks/instructions/shipping-profile-activate.adoc[]

[#550]
== Artikelexport einrichten

Artikeldaten werden über Katalog-Formate zu myToys exportiert. Kataloge erstellst du im Menü *Daten » Kataloge*.

* Du arbeitest zum ersten Mal mit den Katalogen? Dann mache dich zuerst <<daten/daten-exportieren/kataloge-verwalten#, mit dem Prinzip der Kataloge vertraut>>.

Damit du deine Artikel zu myToys exportieren kannst, musst du Kataloge erstellen. Die Kataloge erstellst du spezifisch pro Kategorie. Je nach gewählter Kategorie variieren bei der Zuordnung sowohl die Pflichtfelder als auch die optionalen Felder. Verknüpfe anschließend im Marktplatz-Format die von myToys vorgegebenen Felder mit den in plentymarkets gespeicherten Artikeldaten. Die Katalogdaten werden automatisch in regelmäßigen Abständen zu myToys exportiert, wenn du einen Katalog aktivierst.
// TODO: Umschreiben

[#600]
=== Besonderheiten der myToys-Artikeldatenstruktur

Die Struktur der Artikeldaten von myToys gleicht der Struktur in plentymarkets. Nur die Benennungen unterscheiden sich:

. Das *Produkt* bei myToys entspricht in plentymarkets dem *Artikel*.
. Der *Artikel* bei myToys entspricht in plentymarkets der *Variante*.

[#650]
=== Katalog mit dem Assistenten erstellen

:catalogue-assistant-name: myToys - Kataloge
:number-of-boxes: Info-Box
:catalogue-path: pass:quotes[*Einrichtung » Assistenten » Plugins » Plugin-Set wählen*]
:catalogue-note: Für jede myToys-Kategorie benötigst du einen eigenen Katalog.
:mapping-fields: weitere

include::_textblocks/catalogues/instructions/catalogue-assistant-config.adoc[]

[#700]
=== Katalogzuordnungen vornehmen

Nachdem du einen Katalog erstellt hast, ordnest du die Datenfelder des Marktplatzes den in plentymarkets gespeicherten Artikeldaten zu. In diesem Kapitel erfährst du, wie du Datenfelder zuordnest und welche Besonderheiten es bei myToys gibt. Außerdem findest du hier Empfehlungen für korrekte Zuordnungen. Die Informationen sind wie folgt aufgebaut:

* <<#750, Datenfelder im Katalog zuordnen>>
* <<#800, Besonderheiten bei der Zuordnung von Datenfeldern>>

[#750]
==== Datenfelder im Katalog zuordnen

Ordne nun die Datenfelder von myToys den in plentymarkets gespeicherten Artikeldaten zu. Beachte die Informationen zu Besonderheiten und Empfehlungen in diesem Kapitel.

include::_textblocks/catalogues/instructions/catalogue-mapping.adoc[]

[#800]
==== Besonderheiten bei der Zuordnung

Jeder Marktplatz strukturiert Artikeldaten anders. In <<#catalogue-mappings>> findest du Hinweise dazu, was du beim Zuordnen von Datenfeldern für myToys beachten solltest.

Beachte außerdem die folgenden allgemeinen Hinweise:

* Ordne mindestens die *Pflichtfelder* zu. Über die Umschaltfläche (icon:toggle-on[role="green"]) *Nur Pflichtfelder anzeigen* kannst du dir auch nur die Pflichtfelder des Marktplatzes anzeigen lassen.

* Für einige Zuordnungen ist es sinnvoll, vorher <<artikel/einstellungen/eigenschaften#500, Eigenschaften>> zu erstellen. Diese Eigenschaften kannst du erst im Katalog zuordnen, nachdem du sie erstellt und gespeichert hast. Stelle daher sicher, dass du alle nötigen Eigenschaften erstellt hast.

* myToys kann keine HTML-Tags verarbeiten. Deshalb werden HTML-Tags beim Export herausgefiltert. Achte darauf, besonders für <<#option-itemtext, Artikelbeschreibungen>> und <<#option-bulletpoints, Aufzählungszeichen>>.
//TODO

[[catalogue-mappings]]
.Besonderheiten bei der Zuordnung
[cols="1,3a"]
|====
| Marktplatz-Datenfeld | Erläuterung

| *Produktname*
| Gib den Produktnamen auf Deutsch an. Die Zeichenzahl für Produktnamen ist technisch nicht limitiert. Achte aber darauf, nicht zu viele Zeichen zu verwenden, da der Produktname systemseitig von myToys sonst abgeschnitten wird. Der Produktname sollte daher so kurz wie möglich sein. +
Hersteller bzw. Eigenmarken müssen nicht im Produktnamen erwähnt werden, diese werden bei myToys gesondert darüber angezeigt. Des Weiteren dürfen Farben, Größen, Geschlechterangaben und Wiederholungen nicht im Produktnamen genannt werden.
//TODO

| *Marke*
| Ordne das plentymarkets Datenfeld *Artikel » Externer Herstellername* zu.

| [option-itemtext]*Texte*
| Ordne das plentymarkets Datenfeld *Artikeltext » Artikeltext* zu. +
Die Artikelbeschreibung darf maximal 4000 Zeichen lang sein. Längerer Text wird nach 4000 Zeichen abgeschnitten und mit `...` versehen. +
*_Hinweis:_* Verwendest du HTML-Tags, um deine Artikeltexte zu formatieren? +
myToys kann keine HTML-Tags verarbeiten. Deshalb werden HTML-Tags beim Export herausgefiltert. Prüfe deshalb deine Artikeltexte. Wenn du viele HTML-Tags verwendest, kann es sinnvoll sein, eine Eigenschaft zuzuordnen, in der du die Artikelbeschreibungen ohne HTML-Formatierung speicherst.

| *Farbe*
| Die Farbe ist in plentymarkets und bei myToys variantenbildend.

Für den Export von Farben gibt es zwei Marktplatz-Datenfelder:

[cols="1,2"]
!===
! *Marktplatz-Datenfeld* ! *Zuordnungsempfehlung*

! *General Attributes > Farbe*
! Ordne dem Marktplatz-Datenfeld *Farbe* ein variantenbildendes Attribut für Farben zu.

! *Farbe > Farbe*
! Ordnest jedem Farbwert von myToys einen Attributwert desselben Attributs für Farbe zu, das du dem Marktplatz-Datenfeld *General Attributes > Farbe* zugeordnet hast.
!===

[.collapseBox]
.Du hast andere Farbabstufungen als myToys?
--
Wenn du andere Farbabstufungen als myToys verwendest, kannst du Ausweich-Datenfelder zuordnen.

*_Beispiel:_* Zusätzlich zu *Rot* hast du die Farbabstufungen *Hellrot*, *Dunkelrot* und *Kirschrot* entweder als Attributwerte oder als Eigenschaftwerte.

Ordne dem Marktplatz-Datenfeld für die Artikelfarbe *Rot* diese Attributwerte/Eigenschaftswerte als Ausweich-Datenfelder zu.

So wird die Variante mit allen drei Begriffen gefunden, wenn Kund:innen auf myToys Produkte nach *Rot* filtern.
--

| *Größe*
| Normalerweise ist die Größe in plentymarkets und bei myToys variantenbildend. Ordne deshalb ein Attribut für Größenangaben zu. +
*_Hinweis:_* Ob die Größe wirklich variantenbildend ist, hängt vom Produktsortiment ab. Wenn deine Varianten ohne Attribute für Größen erstellt wurden, wende dich an das myToys-Integrationsteam, um das weitere Vorgehen zu besprechen.

| *UVP*
| Der <<artikel/einstellungen/preise#, UVP>> muss die Herkunft myToys haben. +
Wenn der Verkaufspreis größer oder genauso groß ist wie der UVP, wird der UVP auf der myToys Artikelseite nicht ausgegeben. Ist der Verkaufspreis niedriger als der UVP, wird der UVP als durchgestrichener Preis ausgegeben. +
*_Hinweis:_* Wenn du keinen UVP hast, zum Beispiel weil du selbst Hersteller:in bist, ordne denselben Verkaufspreis wie für das Marktplatz-Datenfeld *UVP* zu. Bei myToys wird dann kein durchgestrichener Preis ausgegeben.

| [option-bulletpoints]*Aufzählungszeichen*
| Auf der myToys Artikelseite werden zusätzliche Informationen über den Artikel mit Aufzählungszeichen (bullet points) aufgeführt. Hierfür bietet es sich an, dies in plentymarkets über die Eigenschaft *Text* zu pflegen. +
Die Zeichenlimitierung für Bullet Points beträgt 255 Zeichen, danach wird der Text abgeschnitten und mit “...” versehen.

| *Saison*
| Ordne den Saisons die Werte einer plentymarkets Eigenschaft zu. +
*_Tipp:_* Für saisonunabhängige Varianten speicherst du an der Variante den Eigenschaftswert, den du im Katalog dem myToys-Wert *NOOS* zuordnest.

Von myToys verwendete Abkürzungen für Saison:

* NOOS = never out of stock
* FS = Frühling/Sommer
* HW = Herbst/Winter

| *Muster*
| Ordne jedem Muster die Werte einer plentymarkets Eigenschaft zu. +
*_Tipp:_* Für Varianten ohne Muster speicherst du an der Variante den Eigenschaftswert, den du im Katalog dem myToys-Wert *uni* zuordnest.

| *Materialzusammensetzung*
| In bestimmten Kategorien muss die Materialzusammensetzung von Varianten angegeben werden. Das betrifft vor allem Textilien und Schuhe.

Von den fünf zur Verfügung stehenden Feldern muss mindestens ein Feld verknüpft werden. Hierbei handelt es sich um ein mehrdimensionales Mapping: +
- Im 1. Schritt muss der Materialtyp (complex mapping) verknüpft werden, z.B. "Obermaterial". +
- Im 2. Schritt muss die Materialzusammensetzung von “Obermaterial” in folgendem Format eingegeben werden: +
{"material1": "prozentwert","material2": "prozentwert","material3": "prozentwert"} +
*_Beispiel:_* {"WO": "90","EL": "10"} +
*_Hinweis:_* Eine vollständige Liste aller von myToys erlaubten Materialtypen findest du link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/myToys/myToys_Materialien_sortiert.pdf[in diesem Dokument].

////
Für den Export von Materialangaben gibt es mehrere Marktplatz-Datenfelder:

[cols="1,3a"]
|===

! *General Components > Textilzusammensetzung - 1. Materialzusammensetzung Textil* +
bis +
*Textilzusammensetzung - 5. Materialzusammensetzung Textil*
!  

! *Textilkomponente - 1. Materialzusammensetzung Textil* +
bis +
*Textilzusammensetzung - 5. Materialzusammensetzung Textil*
!  

!===


Wir empfehlen die folgenden Zuordnungen:

* Unter *General Components* ordnest du dem Marktplatz-Datenfeld *Farbe* ein variantenbildendes Attribut für Farben zu.
* Für die komplexe Zuordnung unter *Farbe* ordnest du jedem Farbwert von myToys einen Attributwert desselben Attributs für Farbe zu.
////

| *Artikelgewicht*
| Der eingegebene Wert wird in Gramm übertragen.

| *Altersempfehlung*
| Die Altersempfehlung definiert die Zielgruppe. Diese Informationen werden verwendet, um automatisch zu entscheiden, in welchem Shop eine Variante angeboten wird:

* Varianten mit einer Altersempfehlung *bis 16 Jahre* werden in myToys eingestellt.
* Varianten mit einer Altersempfehlung *ab 18 Jahre* werden bei mirapodo/yomonda eingestellt.

Die folgenden Werte sind möglich:

* *new born* = 0-9 Monate +
* *baby* = 9-24 Monate +
* *mini* = 2-8 Jahre +
* *teen* = 8-16 Jahre +
* *adult* = 18-99 Jahre

[.collapseBox]
.Eigenschaft für *Altersempfehlung* erstellen und mit Varianten verknüpfen
--

. Eigenschaft mit den folgenden Einstellungen erstellen:
  ** Name: Altersgruppe
  ** Bereich: Artikel
  ** Typ: Auswahl
  ** Auswahlwerte:
    ** *new born*
    ** *baby*
    ** *mini*
    ** *teen*
    ** *adult*
. Variante im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Hauptvariante öffnen] » Varianten-Tab: Eigenschaften* mit der Eigenschaft verknüpfen.
. Für die Variante passenden Eigenschaftswert wählen.
--

|====

Dir fehlen Marktplatz-Datenfelder für die korrekte Zuordnung deiner Artikel? Dann kontaktiere myToys, um bei Bedarf Marktplatz-Datenfelder hinzufügen zu lassen.

[#850]
=== Katalog aktivieren

:interval:

include::_textblocks/catalogues/instructions/catalogue-activation.adoc[]

[#900]
== Variantenverfügbarkeit einstellen

:market-availability: myToys
:option-availability: myToys

include::_textblocks/instructions/variantenverfuegbarkeit.adoc[]

Beachte zudem, dass im <<maerkte/mytoys#650, Assistenten>> erstellte Kategorien den entsprechenden Varianten im Bereich *Varianteneigenschaften* im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Varianten-Tab: Eigenschaften* zugeordnet werden müssen.

[.instruction]
Erstellte Kategorie einer Variante zuordnen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Varianten-Tab: Eigenschaften*.
. Klicke im Bereich *Varianteneigenschaften* in das Feld *Eigenschaften*. +
→ Eine Dropdown-Liste öffnet sich.
. Wähle aus der Dropdown-Liste *myToys Kategoriegruppe* aus.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ *myToys Kategoriegruppe* wird der Tabelle hinzugefügt.
. Wähle in der Spalte *Wert* eine der im Assistenten angelegten Kategorien aus.
. Speichere (icon:save[set=plenty]) die Einstellungen.

[IMPORTANT]
.Verfügbarkeit für Varianten deaktivieren
====
Wenn du die Marktplatzverfügbarkeit einer Variante für myToys im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen]» Tab: Verfügbarkeit* deaktivierst, wird die Variante auf myToys deaktiviert. Wenn du die Verfügbarkeit wieder aktivierst, wird die Variante erst mit dem nächtlichen Artikelexport auf myToys reaktiviert. +
*_Hinweis:_* Damit die Variante deaktiviert wird, muss im Tab *Eigenschaften* der jeweiligen Variante die Eigenschaft *myToys Kategoriegruppe* hinterlegt bleiben.
====

[#order-processing]
== Auftragsabwicklung automatisieren

Automatisiere die folgenden Aspekte der Auftragsabwicklung:

* Melde Stornierungen automatisch <<#950, Wie?>>
* Informiere myToys automatisch darüber, dass die Ware versendet wurde <<#1000, Wie?>>
* Retourenverwaltung <<#1050, Wie?>>

[#950]
=== Stornierungen automatisch melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um myToys automatisch über Stornierungen zu informieren.

:table-event-procedure: <<#ereignisaktion-stornierung-myToys>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-stornierung-myToys]]
.Ereignisaktion, um Stornierungen an myToys zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, zum Beispiel *[8] Storniert*.

| *Filter*
| *Auftrag > Herkunft*
| *myToys*

| *Aktion*
| *Plugins*
| *Auftragsstornierung an myToys melden*
|===

[#1000]
=== Versandbestätigungen automatisch an myToys senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um myToys automatisch über Versandbestätigungen zu informieren.

:table-event-procedure: <<#ereignisaktion-versandinfo-myToys>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-versandinfo-myToys]]
.Ereignisaktion für Versandbestätigungen
[cols="1,2,2"]
|===
|Einstellung |Option |Auswahl

| *Ereignis*
| *Statuswechsel*
| Ereignis wählen, zum Beispiel *[7] Warenausgang gebucht*.

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag* +
*Lieferauftrag*

| *Filter 2*
| *Auftrag > Herkunft*
| *myToys*

| *Aktion*
| *Plugins*
| *Versandinformation an myToys melden*
|===

[#1050]
=== Retourenverwaltung einrichten

Richte nun die Verwaltung von Retouren für myToys ein.

[#1100]
==== Ablauf von Retouren

Eine Retoure läuft bei myToys wie folgt ab:

. Kund:innen senden die Ware inklusive des ausgefüllten <<#1150, Rücksendescheins>> an dich zurück.
. Du führst die Retoure in plentymarkets aus.
. Du informierst myToys darüber, dass du die Ware erhalten hast.
. myToys erstattet Käufer:innen den Kaufpreis zurück. +
*_Hinweis:_* Wenn du myToys mitteilst, dass die Retoure abgeschlossen ist, wird bei myToys eine Gutschrift ausgelöst und Endkund:innen erhalten eine Rückerstattung. Achte deshalb darauf, dass du myToys erst über den Abschluss der Retoure informierst, nachdem du die Ware erhalten und geprüft hast.


[#1200]
==== Retoure automatisch an myToys melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um myToys automatisch darüber zu informieren, dass eine Retoure abgeschlossen wurde.

:table-event-procedure: <<#ereignisaktion-retouren-myToys>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-retouren-myToys]]
.Ereignisaktion zum automatischen Melden von Retouren an myToys
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| *Neue Retoure*
|

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Retoure*

| *Filter 2*
| *Auftrag > Herkunft*
| *myToys*

| *Aktion*
| *Plugins*
| *Retoure an myToys melden* +
*_Hinweis:_* Durch die Aktion *Retoure an myToys melden* wird bei myToys eine Gutschrift ausgelöst. Endkund:innen erhalten also eine Rückerstattung. Achte deshalb darauf, dass die Ereignisaktion erst ausgelöst wird, nachdem du die retournierte Ware erhalten und geprüft hast.
|====





[#order-documents]
== Auftragsdokumente für myToys vorbereiten

Auf Auftragsdokumenten für myToys-Aufträge muss der myToys-Briefkopf erscheinen. Außerdem müssen die Dokumente bestimmte Angaben enthalten.

* <<#delivery-notes, Lieferscheine vorbereiten>>
* <<#return-notes, Rücksendescheine vorbereiten>>

[#delivery-notes]
=== Lieferscheine vorbereiten

* <<#1300, So lädst du eine PDF-Vorlage für Lieferscheine hoch>>
* <<#16003, So passt du Lieferscheine für myToys an>>

[#1300]
==== PDF-Vorlage für Lieferscheine hochladen

myToys-Lieferscheine müssen das Logo von myToys verwenden. Gehe wie unten beschrieben vor, um eine <<auftraege/auftragsdokumente#170, PDF-Vorlage>> für Lieferscheine für myToys in plentymarkets hochzuladen.

[.instruction]
PDF-Vorlage für Lieferscheine hochladen:

. Lade die PDF-Vorlage für Lieferscheine von myToys herunter und speichere sie auf deinem Rechner:
  ** link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/myToys/myToys_delivery_note_return_note.pdf[PDF-Vorlage herunterladen]
. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » Standort: Deutschland » Dokumente » Lieferschein*.
. Wechsele in das Tab *PDF-Vorlage*.
. Klicke auf *Vorlage hinzufügen*. +
→ Das Bearbeitungsfenster *Neue PDF-Vorlage hochladen* wird geöffnet.
. Wähle aus der Dropdown-Liste *Zahlungsart* die Option *Plugin: myToys Payment*.
. *_Tipp:_* Die Zahlungsart *Plugin: myToys Payment* wird nicht in der Dropdown-Liste angezeigt?
  .. Öffne das Menü *Einrichtung » Aufträge » Einstellungen*.
  .. Wähle für die Einstellung *Inaktive Plugin-Zahlungsarten anzeigen* die Option *Ja*.
  .. Speichere (icon:save[set=plenty]) die Einstellung.
. Wähle in der Dropdown-Liste *Sprache* die Option *de*.
. Klicke in der Zeile *Vorlage* auf *Vorlage auswählen*.
. Wähle die PDF-Vorlage für Lieferscheine von myToys.
. Klicke auf *Vorlage hochladen* (icon:save[set=plenty]). +
→ Die Vorlage wird hochgeladen.

[#16003]
==== Lieferscheine anpassen

Lieferscheine für {myToys}-Aufträge müssen zusätzlich zum myToys-Briefkopf die folgenden Angaben enthalten:

* Externe Auftragsnummer
* Externe Kundennummer
* EAN

[.instruction]
Lieferscheine anpassen:

. Öffne das Menü *Einrichtung » Mandant » Standard » Standorte » Deutschland » Dokumente » Lieferschein » Tab: Vorlage*.
. Scrolle zum Bereich *Spalten Artikelpositionen*.
. Aktiviere für die Einstellung *Artikelbezeichnung* die Option *EAN*.
. Scrolle zum Bereich *Optionale Elemente unter Artikelpositionstabelle*.
. Wähle für die Einstellung *Externe Auftragsnummer* aus der Dropdown-Liste die Option *Ja*.
. Wähle für die Einstellung *Externe Kundennummer* aus der Dropdown-Liste die Option *Ja*.
. Speichere (icon:save[set=plenty]) die Einstellungen. +
→ Die Angaben werden auf Lieferscheinen angezeigt.

[#return-notes]
=== Rücksendescheine vorbereiten

* <<#1150, So lädst du eine PDF-Vorlage für Rücksendescheine hoch>>
* <<#1150-1, So passt du Rücksendescheine für myToys an>>

[#1150]
==== PDF-Vorlage für Rücksendescheine hochladen

Auf Rücksendescheinen für myToys-Aufträge muss der myToys-Briefkopf erscheinen.
Gehe wie unten beschrieben vor, um eine <<auftraege/auftragsdokumente#170, PDF-Vorlage>> für Rücksendescheine für myToys in plentymarkets hochzuladen.

[.instruction]
PDF-Vorlage für Rücksendescheine hochladen:

. Lade die PDF-Vorlage für Rücksendescheine von myToys herunter und speichere sie auf deinem Rechner:
  ** link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/myToys/myToys-Retourenschein.pdf[PDF-Vorlage herunterladen]
. Öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Standorte » Standort: Deutschland » Dokumente » Rücksendescheinschein*.
. Wechsele in das Tab *PDF-Vorlage*.
. Klicke auf *Vorlage hinzufügen*. +
→ Das Bearbeitungsfenster *Neue PDF-Vorlage hochladen* wird geöffnet.
. Wähle aus der Dropdown-Liste *Zahlungsart* die Option *Plugin: myToys Payment*.
. *_Tipp:_* Die Zahlungsart *Plugin: myToys Payment* wird nicht in der Dropdown-Liste angezeigt?
  .. Öffne das Menü *Einrichtung » Aufträge » Einstellungen*.
  .. Wähle für die Einstellung *Inaktive Plugin-Zahlungsarten anzeigen* die Option *Ja*.
  .. Speichere (icon:save[set=plenty]) die Einstellung.
. Wähle in der Dropdown-Liste *Sprache* die Option *de*.
. Klicke in der Zeile *Vorlage* auf *Vorlage auswählen*.
. Wähle die PDF-Vorlage für Lieferscheine von myToys.
. Klicke auf *Vorlage hochladen* (icon:save[set=plenty]). +
→ Die Vorlage wird hochgeladen.

[#1150-1]
==== Rücksendescheine anpassen

Rücksendescheine für {myToys}-Aufträge müssen zusätzlich zum myToys-Briefkopf die folgenden Angaben enthalten:

* Externe Auftragsnummer
* Externe Kundennummer
* EAN

[.instruction]
Rücksendescheine anpassen:

. Öffne das Menü *Einrichtung » Mandant » Standard » Standorte » Deutschland » Dokumente » Rücksendeschein » Tab: Vorlage*.
. Scrolle zum Bereich *Spalten Artikelpositionen*.
. Aktiviere für die Einstellung *Artikelbezeichnung* die Option *EAN*.
. Scrolle zum Bereich *Optionale Elemente unter Artikelpositionstabelle*.
. Wähle für die Einstellung *Externe Auftragsnummer* aus der Dropdown-Liste die Option *Ja*.
. Wähle für die Einstellung *Externe Kundennummer* aus der Dropdown-Liste die Option *Ja*.
. Speichere (icon:save[set=plenty]) die Einstellungen. +
→ Die Angaben werden auf Rücksendescheinen angezeigt.

[#1350]
== Fehlersuche: Log-Einträge abrufen

NOTE: Deine Varianten wurden nicht zu myToys exportiert? Wenn mindestens eine Variante die Anforderungen von myToys nicht erfüllt, werden keine Variantendaten exportiert. Deine Varianten werden also schon bei einer einzigen ungültigen Variante nicht zu myToys übertragen. Um den Fehler zu finden, prüfe die Einträge im Daten-Log.

include::_textblocks/instructions/logs_abrufen.adoc[tag=data-log-intro]

* *Integration* » *myToys*
* *Referenztyp* » *variationId*

include::_textblocks/instructions/logs_abrufen.adoc[tag=data-log-config]

Zusätzlich zur oben beschriebenen Methode kannst du ebenfall auch gezielt überprüfen, bei welchen Varianten Pflichtfelder nicht ausgefüllt wurden. Nimm im Vorfeld die folgenden Einstellungen vor, um diese Informationen einsehen zu können.

[.instruction]
Varianten mit fehlenden Pflichtfeldern finden:

. Öffne das Menü *Daten » Log*.
. Klicke auf *Logs konfigurieren* (icon:cog[]).
. Wähle *myToys* aus der Liste aus.
. Aktiviere die Option *Aktiv*.
. Wähle die *Dauer*, für die das Log-Level aktiv bleiben soll.
. Aktiviere im Dropdown-Menü *Log level* die Option *Debug*.
. *Speichere* (icon:save[set=plenty]) die Einstellungen.

Nachdem du diese Einstellungen vorgenommen hast, kannst du im Menü *Daten » Log* auf Einträge zu *myToys* mit dem Level *Debug* klicken. So werden die Einträge aufgeklappt und genauere Angaben zu fehlenden Pflichtfeldern angezeigt.
