= OTTO
:lang: de
include::{includedir}/_header.adoc[]
:keywords: OTTO, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz OTTO in deinem plentymarkets System ein.
:position: 150
:url: maerkte/otto

Auf dieser Handbuchseite erhalten Sie Informationen zu OTTO und dem Marktplatzmodell OTTO market.

== OTTO

link:https://www.otto.de/[OTTO^] ist Teil der Otto Group und eines der erfolgreichsten Online-Versandhandelsunternehmen Deutschlands.

Bei OTTO handelt es sich um einen Online-Shop, das heißt, du verkaufst im Namen von OTTO. Auch die Kundenkommunikation wird von OTTO übernommen.

Aus Datenschutzgründen ist der Inhalt der Handbuchseite OTTO nur für Kund*innen zugänglich, die einen OTTO-Vertrag haben. Die OTTO-Handbuchseite steht dir als OTTO-Partner im link:https://forum.plentymarkets.com/[Forum^] innerhalb der OTTO-Kategorie zur Verfügung.

[IMPORTANT]
.OTTO verfügt über drei Schnittstellen
====
OTTO verfügt über drei Schnittstellen: *Direktversand*, *Cooperation* und *Integration*. Alle Schnittstellen werden von plentymarkets unterstützt. +
Der Unterschied zwischen den Schnittstellen besteht im Auftragsimport. Bei den Schnittstellen *Direktversand* und *Cooperation* übermittelt OTTO einzelne Aufträge in dein plentymarkets System, die du dann direkt an die Endkund*innen schickst. +
Wenn du die Schnittstelle *Integration* nutzt, übermittelt dein plentymarkets System einmal pro Tag einen Sammelauftrag an OTTO. In diesem Fall schickt OTTO dann die bestellten Artikel an die Endkund*innen.
====

== OTTO market

OTTO market ist das Marktplatzmodell von OTTO. Du wirst als Verkäufer an deinen Produkten angezeigt und die Kundenkommunikation wird von dir selbst verwaltet.

[IMPORTANT]
.Einrichtung von OTTO market über Assistenten
====
OTTO market wird mit den Assistenten *OTTO market Grundeinstellungen* und *OTTO market-Kataloge erstellen* im Menü *Einrichtung » Assistenten* eingerichtet. Mit dem *OTTO market Grundeinstellungen*-Assistenten richtest du dein OTTO market-Konto in plentymarkets ein. Mit dem Assistenten *OTTO market-Kataloge erstellen* erstellst du Kataloge und Katalog-Templates für OTTO market.
====
