= OTTO
:lang: de
include::{includedir}/_header.adoc[]
:keywords: OTTO, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz OTTO in deinem plentymarkets System ein.
:position: 150
:url: maerkte/otto

Der Marktplatz link:https://www.otto.de/[OTTO^] ist Teil der Otto Group und eines der erfolgreichsten Online-Versandhandelsunternehmen Deutschlands. Aus Datenschutzgründen ist der Inhalt der Handbuchseite OTTO nur für Kund*innen zugänglich, die einen OTTO-Vertrag haben.

Die OTTO-Handbuchseite steht dir als OTTO-Partner im link:https://forum.plentymarkets.com/[Forum^] innerhalb der OTTO-Kategorie zur Verfügung.

[IMPORTANT]
.OTTO verfügt über drei Schnittstellen
====
Der Marktplatz OTTO verfügt über drei Schnittstellen: *Direktversand*, *Cooperation* und *Integration*. Alle Schnittstellen werden von plentymarkets unterstützt. +
Der Unterschied zwischen den Schnittstellen besteht im Auftragsimport. Bei den Schnittstellen *Direktversand* und *Cooperation* übermittelt OTTO einzelne Aufträge in dein plentymarkets System, die du dann direkt an die Endkund*innen schickst. +
Wenn du die Schnittstelle *Integration* nutzt, übermittelt dein plentymarkets System einmal pro Tag einen Sammelauftrag an OTTO. In diesem Fall schickt OTTO dann die bestellten Artikel an die Endkund*innen.
====
