= OTTO
:lang: de
include::{includedir}/_header.adoc[]
:keywords: OTTO, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz OTTO in Ihrem plentymarkets System ein.
:position: 150

Der Marktplatz link:https://www.otto.de/[OTTO^] ist Teil der Otto Group und eines der erfolgreichsten Online-Versandhandelsunternehmen Deutschlands. Aus Datenschutzgründen ist der Inhalt der Handbuchseite OTTO nur für Kunden zugänglich, die einen OTTO-Vertrag haben.

Die OTTO-Handbuchseite steht Ihnen als OTTO-Partner im link:https://forum.plentymarkets.com/[Forum^] innerhalb der OTTO-Kategorie zur Verfügung.

[IMPORTANT]
.OTTO verfügt über zwei Schnittstellen
====
Der Marktplatz OTTO verfügt über zwei Schnittstellen: *Cooperation* und *Integration*. Beide Schnittstellen werden von plentymarkets unterstützt. +
Der Unterschied zwischen diesen beiden Schnittstellen besteht im Auftragsimport. Bei der Schnittstelle *Cooperation* übermittelt OTTO einzelne Aufträge in Ihr plentymarkets System, die Sie dann direkt an den Endkunden schicken. +
Wenn Sie die Schnittstelle *Integration* nutzen, übermittelt Ihr plentymarkets System einmal pro Tag einen Sammelauftrag an OTTO. In diesem Fall schickt OTTO dann die bestellten Artikel an den Endkunden.
====
