= Netto Marken-Discount, GartenXXL.de und GartenXXL.at
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Plus.de, GartenXXL.de, GartenXXL.at, Netto, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zu den Marktplätzen Netto Marken-Discount und GartenXXL.de in deinem plentymarkets System ein.
:position: 170
:url: maerkte/plus-gartenxxl

link:https://shop.netto-online.de/[Netto Marken-Discount] bietet Produkte aus den Kategorien Lebensmittel, Drogerie, Wohnen, Haushalt, Garten und Freizeit an (Quelle: https://shop.netto-online.de).

link:http://www.gartenxxl.de/[GartenXXL^] ist eine Marke der Tengelmann E-Stores GmbH. Auf GartenXXL werden Geräte bekannter Firmen und wissenswerte Informationen zur Gartenpflege angeboten (Quelle: www.gartenxxl.de).

[#100]
== Bei Netto eStores registrieren

Bevor du Netto eStores in deinem plentymarkets System einrichtest, musst du dich zunächst bei Netto eStores registrieren. Ansprechpartner für die Registrierung: +
Katrin.Beer@netto-online.de +
Christian.Mertens@netto-online.de

[IMPORTANT]
.Artikelexport mit Produkt-XML 4.0
====
plentymarkets überträgt Artikeldaten mit der Produkt-XML 4.0 zu den Marktplätzen der Netto eStores GmbH. Informiere Netto eStores bei deiner Registrierung darüber, da ansonsten Artikel nicht exportiert werden können.
====

[#200]
== Netto eStores in plentymarkets einrichten

Um Artikel auf Netto Marken-Discount, GartenXXL.de und GartenXXL.at verkaufen zu können, musst du den Marktplatz zunächst in plentymarkets einrichten. Gehe dazu wie im Folgenden beschrieben vor:

[.instruction]
Netto Marken-Discount/GartenXXL.de/GartenXXL.at in plentymarkets einrichten:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Netto eStores*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-plus>>.
. *Speichere* die Einstellungen.

[[einstellungen-plus]]
.Einstellungen für die Marktplätze Netto Marken-Discount, GartenXXL.de und GartenXXL.at
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Automatischen Datenaustausch aktivieren*
|*Ja* wählen, um den automatischen Datenaustausch zu aktivieren oder *Nein*, um den Datenaustausch zu deaktivieren. +
Wenn du *Ja* wählst, werden der Bestandsabgleich, der Artikelexport und der Auftragsimport aktiviert.

|*Artikelexport aktivieren*
|*Ja* wählen, um den automatischen Artikelexport zu aktivieren oder *Nein*, um den automatischen Artikelexport zu deaktivieren.

|*Bestandsabgleich aktivieren*
|*Ja* wählen, um den automatischen Bestandsabgleich zu aktivieren oder *Nein*, um den automatischen Bestandsabgleich zu deaktivieren.

2+|Vertriebspartner-Information

|*Lieferantennummer*
|Lieferantennummer eingeben, wie von Netto eStores erhalten.

2+|Artikeleinstellungen

|*Artikelname*
|Artikelnamen wählen, der an Netto eStores übertragen wird.

|*Variantenname*
|Variantennamen wählen, der an Netto eStores übertragen wird. +
*Variantenname* = Der Variantenname wird übertragen. +
*Attributswerte der Variante anhängen* = Die Attributswerte werden durch Leerzeichen getrennt an den Variantennamen angehängt (Beispiel: "T-Shirt rot XL").

|*Artikelkurzbeschreibung*
|Artikelkurzbeschreibung wählen, die an Netto eStores übertragen wird.

|*Artikelbeschreibung*
|Artikelbeschreibung wählen, die an Netto eStores übertragen wird.

|*Bildposition für das Energieetikett*
|Ziffer der Bildposition des Artikelbildes eingeben, wenn das Energieetikett nicht als Merkmal, sondern als Artikelbild erstellt wurde. Details zum Energieetikett siehe Kapitel <<Energieeffizienz-Merkmale erstellen, Energieeffizienz-Merkmale erstellen>>.

|*Menge für Artikel ohne Bestandsbindung*
|Bei Artikeln mit der Einstellung *keine Beschränkung* wird der Maximalwert aus realem Bestand und der hier definierten Menge übermittelt. +
_Beispiel:_ Einstellung 0, Nettowarenbestand 8. plentymarkets übermittelt 8. +
Artikel mit der Einstellung *Beschränkung auf Nettowarenbestand* werden hier nicht berücksichtigt.

|*Menge für Artikel ohne Bestandsbeschränkung, falls der Bestand 0 ist*
|Zahl eingeben, die als Bestand für Artikel ohne Bestandsbeschränkung, bei denen der Bestand 0 ist, übertragen werden soll.

|*Standardlieferzeiten*
|Durchschnittliche Lieferzeit in Tagen eingeben.

|*Artikel-Lieferzeit 1 - 10*
|Durchschnittliche Lieferzeiten in Tagen für die Artikelverfügbarkeiten 1 - 5 eingeben. +
*Wichtig:* Nur eindeutige Angaben sind möglich (d.h. keine Zeiträume wie 2-3).

|*Standardprovision in Prozent*
|Provisionswert eingeben, der mit Netto eStores vereinbart wurde.

|*Standardversandkosten*
|Versandkosten in Euro eingeben. Der eingegebene Wert wird als Standardversandkosten für alle Artikel übertragen.

|*Preis für EK/VK-Modell*
|Preis für das EK/VK-Modell wählen. In der Dropdown-Liste können alle Preise gewählt werden, die für Plus freigegeben sind. Wenn der gewählte Preis an allen Varianten eines Artikels gespeichert ist, wird der Preis als Einkaufspreis für Plus übertragen. Andernfalls wird der unter *Standardprovision in Prozent* eingestellte Provisionssatz übertragen. +
*Wichtig:* Der hier gewählte Preis darf nicht der Verkaufspreis sein, sonst wird kein Preis für das EK/VK-Modell übertragen.

2+|Bestelleinstellungen

|*Mindestbestellmenge*
|Artikelanzahl eingeben, wenn eine Mindestbestellmenge gewünscht ist.

|*Maximale Bestellmenge*
|Artikelanzahl eingeben, wenn eine maximale Bestellmenge gewünscht ist.

|*Artikelnamen in Auftragspositionen*
|Wählen, ob der Artikelname in den Auftragspositionen von Netto eStores oder aus dem Shop übernommen werden soll.

2+|SFTP-Einstellungen

|*Benutzername*
|Benutzername eingeben, wie von Netto eStores erhalten.
|====

[IMPORTANT]
.EK/VK nur nach Absprache mit Verkaufskanal ändern
====
Ändere die Einstellungen zur *Standard-Provision in Prozent* und zum *Preis für EK/VK-Modell* nur in Absprache mit dem Verkaufskanal. Netto eStores empfiehlt, als Standard ein Provisionsmodell mit dem Provisionswert einzustellen, der mit Netto eStores vereinbart wurde.
====

Die Anbindung des Marktplatzes stellt folgende automatisierte Prozesse bereit:

- täglicher Artikelexport
- täglicher Preisabgleich
- stündlicher Bestandsabgleich
- stündlicher Auftragsimport

[#250]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit Netto Marken-Discount, GartenXXL.de und GartenXXL.at verknüpfen kannst, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft aktiviert werden. Im Folgenden wird beispielhaft beschrieben, wie du die Auftragsherkunft für Netto aktivierst. Aktiviere die Auftragsherkünfte für GartenXXL.de und GartenXXL.at auf die gleiche Weise. +

[IMPORTANT]
.Auftragsherkunft plus.de zusätzlich aktivieren
====
Um eine korrekte Funktionsweise zu gewährleisten, wird die Auftragsherkunft *plus.de* zurzeit noch benötigt. Aktiviere deshalb in jedem Fall zusätzlich die Auftragsherkunft *plus.de*.
====

[.instruction]
Auftragsherkunft für Netto aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setze ein Häkchen bei *Netto*.
. *Speichere* die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die du auf den Marktplätzen Netto Marken-Discount, GartenXXL.de und GartenXXL.at verkaufen möchtest, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden. Stelle die Artikelverfügbarkeiten für die Marktplätze Netto Marken-Discount, GartenXXL.de und GartenXXL.at einzeln ein, je nachdem, auf welchen Marktplätzen du deine Artikel verkaufen willst. +

Im Folgenden wird beispielhaft beschrieben, wie du die Artikelverfügbarkeit für Netto einstellst. Nimm die Einstellungen für die weiteren Marktplätze auf die gleiche Weise vor. +

[.instruction]
Artikelverfügbarkeit für Netto einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Setze ein Häkchen neben der Option *Netto*.
. Setze ein Häkchen neben der Option *Web-API*.
. Klicke auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* die Einstellungen. +
→ Der Artikel ist auf Plus.de verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden. +

[#330]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu. +

Wenn du SKUs hinzufügst, gilt die Herkunft *Plus.de* für die Marktplätze Netto Marken-Discount, GartenXXL.de und GartenXXL.at.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Plus.de*.
. Gib die SKU ein.
. Klicke auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#350]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkünfte Netto, GartenXXL.de und GartenXXL.at einen Verkaufspreis festzulegen. Die Auftragsherkunft *Plus.de* muss am Verkaufspreis aktiviert sein, damit der Preis beim Artikelexport berücksichtigt wird.

[IMPORTANT]
.Mehrere Auftragsherkünfte aktivieren
====
Wir empfehlen, für die Marktplätze Netto, GartenXXL.de und GartenXXL.at einen Verkaufspreis festzulegen, an dem die Auftragsherkünfte *Plus.de*, *Netto*, *GartenXXL.de* und *GartenXXL.at* aktiviert sind, damit der Preis sowohl beim Artikelexport als auch beim Auftragsimport berücksichtigt wird.
====

[.instruction]
Verkaufspreis für Netto Marken-Discount/GartenXXL.de/GartenXXL.at festlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei den Herkünften *Plus.de*, *Netto*, *GartenXXL.de* und *GartenXXL.at*. +
. *Speichere* die Einstellungen.

[#365]
== Grundpreisanzeige einstellen

Für Artikel, die du auf den Marktplätzen Netto und GartenXXL verkaufst, muss verpflichtend angegeben werden, ob der Artikel einen Grundpreis hat. Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen* gibst du mit der Option *Grundpreisanzeige* an, ob ein Artikel einen Grundpreis benötigt.

[instruction]
Grundpreisanzeige aktivieren:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Setze im Bereich *Maße* ein Häkchen bei der Option *Grundpreisanzeige* +
→ Beim Export wird in der XML-Datei das Filterattribut *Grundpreispflicht* auf *ja* gesetzt.

Wenn du die Option *Grundpreisanzeige* nicht aktivierst, wird *nein* übertragen und der Artikel wird als nicht grundpreispflichtig gekennzeichnet.

*_Oder:_* Als Alternative kannst du ein Merkmal für die Grundpreispflicht anlegen. Dieses Merkmal überschreibt die Einstellung für die Option *Grundpreisanzeige*. Weitere Informationen dazu findest du im Kapitel <<Merkmal für Grundpreispflicht erstellen, Merkmal für Grundpreispflicht erstellen>>.

[#400]
== Zahlungsart aktivieren

Aktiviere die <<payment/zahlungsarten-verwalten#, Zahlungsart>> *Netto* wie im Folgenden beschrieben. Nimm anschließend die Einstellungen für die Zahlungsarten *GartenXXL.de* und *GartenXXL.at* auf die gleiche Weise vor.

[.instruction]
Zahlungsart Netto aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive anzeigen*.
. Klicke auf den Ordner *DE &gt; Netto*. +
→ Die Einstellungen für die Netto-Zahlungsart werden angezeigt.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-zahlungsart>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* die Einstellungen.

[[einstellungen-zahlungsart]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn Käufer*innen im Webshop die Sprache wählen.

|*Name*
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
|Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in deinem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig:* Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » Systemeinstellungen » CRM » Kundenklassen* aktivierst oder deaktivierst du *erlaubte Zahlungsarten*. +
Weitere Informationen findest du im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#500]
== Kategorien verknüpfen

Damit deine Artikel auf den Marktplätzen Netto Marken-Discount, GartenXXL.de und GartenXXL.at zum Verkauf angezeigt werden, musst du Kategorieverknüpfungen erstellen. Die dafür erforderlichen Kategorie-IDs für Netto Marken-Discount, GartenXXL.de und GartenXXL.at erhältst du von Netto eStores. Erstelle wie im Folgenden beschrieben Verknüpfungen, damit deine Artikel in den <<artikel/kategorien-verwalten#, Kategorien>> auf den Marktplätzen angezeigt werden.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Netto eStores*.
. Wechsele in das Tab *Kategorien aktivieren*.
. Gib in den Spalten *Netto-Kategorienverknüpfung*/*GartenXXL.de-Kategorienverknüpfung*/*GartenXXL.at-Kategorienverknüpfung* die IDs der Kategorien ein, die am besten zu deinen Webshop-Kategorien passen. +
→ Die Kategorie-IDs der Marktplätze entnimmst du den Kategoriedateien, die du von Netto eStores erhalten hast.
. Aktiviere die Kategorien.
. *Speichere* die Einstellungen.

[#700]
== Merkmale erstellen

Mit <<artikel/artikel-verwalten#480, Merkmalen>> verknüpfst du bestimmte Eigenschaften, die du für die Einrichtung der Marktplätze Netto Marken-Discount, GartenXXL.de und GartenXXL.at benötigst, mit deinen Artikeln. Du trägst bei Bedarf von den Standardeinstellungen abweichende Provisionen und Kategorieverknüpfungen auf Artikelebene ein. Über Merkmalfilter übermittelst du außerdem Artikelinformationen und legst Filter für die Artikelsuche auf den Marktplätzen fest.

Wie im Kapitel <<Kategorien verknüpfen, Kategorien verknüpfen>> beschrieben, gibst du im Menü *System » Systemeinstellungen » Märkte » Netto eStores* im  Tab *Kategorien aktivieren* die Standardkategorieverknüpfungen ein. Um bestimmten Artikeln bei Bedarf eine andere Kategorie zuzuweisen, verwende die <<artikel/artikel-verwalten#480, Merkmale>> *Artikel-Kategorieverknüpfung für Netto*, *Artikel-Kategorieverknüpfung für GartenXXL.de* oder *Artikel-Kategorieverknüpfung für GartenXXL.at*.

[.instruction]
Merkmal erstellen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Wechsele in das Tab *Neues Merkmal*.
. Gib einen Namen unter *Name (intern)* ein.
. Wähle den Merkmaltyp *Text*.
. Wähle aus der Dropdown-Liste *Netto eStores-Merkmal* das Merkmal *Artikel-Kategorieverknüpfung für Netto* / *Artikel-Kategorieverknüpfung für GartenXXL.de* / *Artikel-Kategorieverknüpfung für GartenXXL.at*.
. *Speichere* die Einstellungen.

[#800]
=== Provisionssätze auf Artikelebene einstellen

Im Menü *System » Systemeinstellungen » Märkte » Netto eStores* gibst du für die Marktplätze einen Standardprovisionssatz ein. Da für bestimmte Netto eStores-Warengruppen jedoch andere Provisionen gelten können, hast du die Möglichkeit, auf Artikelebene einen abweichenden Provisionssatz einzugeben. Einen abweichenden Provisionssatz gibst du mit dem <<artikel/artikel-verwalten#480, Merkmal>> *Provision in Prozent* an. Diese Einstellung hat Priorität gegenüber der eingegebenen Standardprovision. Beachte, dass du diesen Prozentsatz im Vorfeld mit Netto eStores abstimmen musst.

[.instruction]
Merkmal erstellen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Wechsele in das Tab *Neues Merkmal*.
. Gib einen Namen unter *Name (intern)* ein.
. Wähle den Merkmaltyp *Text*.
. Wähle das Netto eStores-Merkmal *Provision in Prozent* aus der Dropdown-Liste.
. *Speichere* die Einstellungen.

[TIP]
.Merkmale: Filter
====
Filter haben bei Netto eStores zwei Funktionen: Du übermittelst damit Artikelinformationen an Netto eStores und kannst den Artikel bei Netto eStores über diesen Filter finden. Nach Auswahl eines Filters wird eine weitere Dropdown-Liste angezeigt. Wähle hier das Filtermerkmal, das einem Artikel zugeordnet werden soll. +
*Hinweis:* Das Merkmal *Energieeffizienz* ist nur für den Marktplatz Netto eStores verfügbar.
====

[#900]
=== Energieeffizienz-Merkmale erstellen

Für die Auszeichnung deiner Artikel für die Marktplätze der Netto eStores GmbH gemäß der neuen Verordnung der EU zur Energieeffizienzrichtlinie sind ab 1.1.2015 Angaben zur Energieeffizienz sowie die Bereitstellung von Produktdatenblättern vorgeschrieben. Erstelle dazu die folgenden drei <<artikel/artikel-verwalten#500, Merkmale>>: *Energieeffizienzklasse*, *Energieetikett* und *Produktdatenblatt*.

[.instruction]
Merkmal Energieeffizienzklasse erstellen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Wechsele in das Tab *Neues Merkmal*.
. Gib einen Namen unter *Name (intern)* ein.
. Wähle den Merkmaltyp *Kein*.
. Wähle die Option *Energieeffizienz* aus der Dropdown-Liste *Netto eStores-Merkmal*. +
→ Eine weitere Dropdown-Liste wird geöffnet.
. Wähle die Energieeffizienzklasse.
. *Speichere* die Einstellungen.

Für die Merkmale Energieetikett und Produktdatenblatt wählst du den Merkmaltyp *Datei*. In der Dropdown-Liste *Netto eStores-Merkmal* wählst du dann die Option *Energieetikett* bzw. *Produktdatenblatt*. Im Folgenden wird beispielhaft beschrieben, wie du das Merkmal Energieetikett erstellst. Erstelle anschließend das Merkmal Produktdatenblatt auf die gleiche Weise.

[.instruction]
Merkmal Energieetikett erstellen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Wechsele in das Tab *Neues Merkmal*.
. Gib einen Namen unter *Name (intern)* ein.
. Wähle den Merkmaltyp *Datei*.
. Wähle die Option *Energieetikett* aus der Dropdown-Liste *Netto eStores-Merkmal*.
. *Speichere* die Einstellungen.

Die Merkmale verknüpfst du dann wie im Folgenden beschrieben im Tab <<artikel/artikel-verwalten#80, Merkmale>> eines Netto eStores-Artikels.

[.instruction]
Energieeffizienz-Merkmale mit Netto eStores-Artikel verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Merkmale*.
. Aktiviere die soeben erstellten Merkmale *Energieeffizienzklasse*, *Energieetikett* und *Produktdatenblatt*.
. *Speichere* die Einstellungen. +
→ Die Merkmale werden mit dem Artikel verknüpft und sind im Bereich *Merkmale* sichtbar.
. Lade beim Merkmal *Energieetikett* die Bilddatei des Energieetiketts hoch.
. Lade beim Merkmal *Produktdatenblatt* die PDF-Datei des Produktdatenblatts hoch.
. *Speichere* die Einstellungen.

*_Oder:_* Speichere das Energieetikett im Tab <<artikel/artikel-verwalten#90, Bilder>> des Artikels. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Energieetikett im Tab Bilder speichern:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Bilder*.
. Füge die Bilddatei des Energieetiketts entweder über *Dateien auswählen* oder per Drag &amp; Drop-Funktion hinzu.
. *Speichere* die Einstellungen.
. Öffne das Menü *System » Systemeinstellungen » Märkte » Netto eStores*.
. Gib die Positionsnummer des Bildes im Tab *Einstellungen* bei der Option *Bildposition für das Energieetikett* ein (Tabelle 1).
. *Speichere* die Einstellungen.

[#950]
=== Merkmal für Grundpreispflicht erstellen

Wenn du grundpreispflichtige Artikel nicht über die Option *Grundpreisanzeige* kennzeichnest (siehe Kapitel <<Grundpreisanzeige einstellen, Grundpreisanzeige einstellen>>), kannst du als Alternative die Grundpreispflicht mit einem Merkmal angeben. Das Merkmal überschreibt die Einstellung für die Option *Grundpreisanzeige*. +

Ein Merkmal für die Grundpreisflicht erstellst du im Menü *System » Systemeinstellungen » Artikel » Merkmale*.

[instruction]
Merkmal für Grundpreispflicht erstellen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Wechsele in das Tab *Neues Merkmal*.
. Gib einen Namen unter *Name (intern)* ein.
. Wähle den Merkmaltyp *Auswahl*.
. Wähle *Freitext* aus der Dropdown-Liste *Netto eStores-Merkmal*. +
→ Ein Eingabefeld erscheint.
. Gib *Grundpreispflicht* im Eingabefeld ein.
. *Speichere* die Einstellungen.
. Füge im Bereich Auswahl nacheinander die Auswahlwerte *ja* und *nein* hinzu und *speichere* die Einstellungen.

Das Merkmal *Grundpreispflicht* verknüpfst du dann wie im Folgenden beschrieben im *Tab: Merkmale* eines Netto eStores-Artikels.

[instruction]
Grundpreispflicht-Merkmal mit Netto eStores-Artikel verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Merkmale*.
. Aktiviere das eben erstellte Merkmal *Grundpreispflicht*.
. *Speichere* die Einstellungen. +
→ Das Merkmal wird mit dem Artikel verknüpft und ist im Bereich *Merkmale* sichtbar.
. Wähle in der Dropdown-Liste *Auswahl* *Ja* oder *Nein*, je nachdem, ob der Artikel grundpreispflichtig ist.
. *Speichere* die Einstellungen.

[#1000]
== Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an Netto eStores zu senden, nachdem ein Warenausgang gebucht wurde. Die Versandbestätigung wird automatisch an Netto eStores gesendet, wenn der Auftrag in Status *[7] Warenausgang gebucht* wechselt. Käufer*innen werden durch Netto eStores über den Versand benachrichtigt.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-versandbestaetigung>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-versandbestaetigung>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-versandbestaetigung]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an Netto eStores
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Netto*, *GartenXXL.de* und *GartenXXL.at*

|*Aktion*
|*Versand &gt; Versandbestätigung an Netto eStores senden*
|
|====

[#1100]
== Stornierungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Stornierungen automatisch an Netto eStores zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-stornierung>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-stornierung>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-stornierung]]
.Ereignisaktion zum automatischen Senden von Stornierungen an Netto eStores
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel &gt; [8] Storniert*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Netto*, *GartenXXL.de* und *GartenXXL.at*

|*Aktion*
|*Zahlungsarten &gt; Stornierung an Netto eStores senden*
|
|====

[#1200]
== Retouren automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Retouren automatisch an Netto eStores zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-retouren>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-retouren>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-retouren]]
.Ereignisaktion zum automatischen Senden von Retouren an Netto eStores
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Netto*, *GartenXXL.de* und *GartenXXL.at*

|*Aktion*
|*Retoure &gt; Retoure an Netto eStores senden*
|
|====

[#1250]
== Unbezahlte Aufträge nach 30 Tagen automatisch stornieren

Aufträge, die vom Kunden nicht bezahlt wurden, werden bei Netto Marken-Discount/Garten XXL.de/GartenXXL.at automatisch nach 30 Tagen storniert. Richte eine Aktion im <<automatisierung/aktionsmanager#, Aktionsmanager>> ein, um unbezahlte Aufträge von Netto Marken-Discount/GartenXXL.de/GartenXXL.at in deinem plentymarkets System nach 30 Tagen automatisch zu stonieren, damit die reservierten Bestände wieder freigegeben werden.

[.instruction]
Aktion einrichten

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Aktionen » Tab: Neue Aktion*.
. Öffne das Tab *Einstellungen*.
. Setze ein Häkchen bei *Aktiv*.
. Wähle aus der Dropdown-Liste *Täglich ausführen um* eine Uhrzeit, zu der die Aktion ausgeführt werden soll. Wir empfehlen, für diese Aktion die Uhrzeit *24:00 Uhr* zu wählen.
. Gib einen Namen ein.
. Wechsele in das Tab *Filter*.
. Wähle die Filter gemäß <<unbezahlte-aufträge>>.
. Wechsele in das Tab *Aktion*.
. Wähle aus der Dropdown-Liste *Ändere Auftragsstatus* einen Status, z.B. *[8.1] Storniert durch Kunden*. Weitere Informationen zur Statuswahl findest du in der Infobox.
. *Speichere* die Einstellungen.
→ Die Aktion wird erstellt und im Tab *Aktionen* angezeigt.

[TIP]
.Status wählen
====
Wähle für die Aktion *Ändere Auftragsstatus* einen Status, den du unter *System » Systemeinstellungen » Aufträge » Einstellungen* für die Option *Status stornierter Aufträge (Keine Reservierung von Beständen)* gespeichert hast, um Reservierungen aufzuheben. Wähle hier außerdem keinen Status, der eine Ereignisaktion auslöst, die eine Stornierung an Netto eStores meldet.
====

[[unbezahlte-aufträge]]
.Filter für die Aktion zum automatischen Stornieren von unbezahlten Aufträgen nach 30 Tagen
[cols="1,3"]
|====
| Filter | Auswahl

|*Status*
|*[3] Warten auf Zahlung*

|*Auftragstyp*
|*Auftrag*

|*Auftragseingang*
|*vor 30 Tagen*

|*Auftragsherkunft*
|*Netto*, *GartenXXL.de* und *GartenXXL.at*
|====

[#1350]
== Lieferscheine und Rücksendescheine erstellen

Die folgenden Informationen gelten nur für Lieferscheine und Rücksendescheine bei Netto Marken-Discount, GartenXXL.de und GartenXXL.at. Sie sind für andere Marktplätze nicht gültig.

[IMPORTANT]
.Rechnungen werden von den Marktplätzen versendet
====
Netto Marken-Discount/GartenXXL.de/GartenXXL.at versenden die Rechnung an den Kunden. Deshalb erhältst du von diesen Marktplätzen die Lieferadresse, aber nicht die Rechnungsadresse des Kunden. Die von Netto Marken-Discount/GartenXXL.de/GartenXXL.at übertragene Lieferadresse wird in plentymarkets als Liefer- und Rechnungsadresse hinterlegt. Du schickst die Ware an diese Adresse.
====

Gehe wie im Folgenden beschrieben vor, um <<auftraege/auftragsdokumente#170, PDF-Vorlagen>> für Lieferscheine und Rücksendescheine für Netto Marken-Discount, GartenXXL.de und GartenXXL.at zu erstellen. Im Folgenden wird das Anlegen eines Lieferscheins für Netto eStores beispielhaft beschrieben. Gehe anschließend auf die gleiche Weise vor, um einen Rücksendeschein für Netto eStores anzulegen. Alle PDF-Vorlagen, die du erstellst, müssen das Logo von Netto Marken-Discount oder GartenXXL.de bzw. GartenXXL.at enthalten. Fordere die Logos direkt bei Netto eStores an. +

Hier lädst du Vorlagendateien für link:https://www.plentymarkets.eu/documents/category/3507/Template-Netto.pdf[Netto Marken-Discount^], link:https://www.plentymarkets.eu/documents/category/3507/Template-GartenXXL-de.pdf[GartenXXL.de^] und link:https://www.plentymarkets.eu/documents/category/3507/Template-GartenXXL-at.pdf[GartenXXL.at^] herunter.

[.instruction]
Lieferschein für Netto eStores erstellen:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Deutschland (Standard) » Dokumente » Lieferschein*.
. Wechsele in das Tab *PDF-Vorlage*.
. Klicke auf *Vorlage hinzufügen*. +
→ Das Bearbeitungsfenster *Neue PDF-Vorlage hochladen* wird geöffnet.
. Wähle aus der Dropdown-Liste *Zahlungsart* die Option *Netto*/*GartenXXL.de*/*GartenXXL.at*.
. Wähle aus der Dropdown-Liste *Sprache* eine Sprache aus.
. Klicke in der Zeile *Vorlage* auf *Vorlage auswählen*.  +
→ Lade die PDF-Vorlage hoch.
. *Speichere* die Einstellungen.

[IMPORTANT]
.Pflichtangabe auf Dokumenten
====
Die externe Auftragsnummer und die externe Kundennummer sind Pflichtangaben auf Dokumenten, die zu einem Auftrag der Herkunft Netto, GartenXXL.de oder GartenXXL.at gehören. Normalerweise kannst du diese Angaben im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Germany (Standard) » Dokumente » Lieferschein* bzw.*Rücksendeschein* im Tab *Vorlage* im Bereich *Optionale Elemente unter Artikelpositionstabelle* ausblenden, indem du die Option *NEIN* wählst. +
Bei Netto Marken-Discount, GartenXXL.de und GartenXXL.at werden die externe Auftragsnummer und die externe Kundennummer jedoch auch eingeblendet, wenn hier die Option *NEIN* gewählt wurde.
====

[IMPORTANT]
.Hinweistext wird ausgeblendet
====
Den Hinweistext, den du im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Germany (Standard) » Dokumente » Lieferschein* bzw. *Rücksendeschein* im Tab *Vorlage* im Bereich *Optionale Elemente unter Artikelpositionstabelle* im Feld *Hinweis* eingeben kannst, wird auf Dokumenten mit der Auftragsherkunft Netto Marken-Discount, GartenXXL.de und GartenXXL.at ausgeblendet. Das Ausblenden des Hinweistextes ist von Netto eStores so gewünscht.
====
