= Restposten.de
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Restposten, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz Restposten.de in Ihrem plentymarkets System ein.
:position: 190

link:http://www.restposten.de/[Restposten.de^] ist ein reines B2B-Portal, d.h. sowohl Anbieter als auch Nachfrager müssen im Besitz eines gültigen Gewerbenachweises sein (Quelle: Restposten.de). +
Auf dieser Seite erfahren Sie, wie Sie den Marktplatz Restposten.de an Ihr plentymarkets System anbinden.

[#100]
== Bei Restposten.de registrieren

Um Ihr plentymarkets System für Restposten.de einzustellen, müssen Sie sich zuerst im link:https://www.restposten.de/register.php[Händlerportal^] von Restposten.de registrieren.

[#200]
== Benutzerkonto erstellen

Ihr plentymarkets System wird über die SOAP-API mit Restposten.de verbunden. Für den Zugriff benötigt der Marktplatz ein eigenes Benutzerkonto mit Zugriffsrechten auf die API in Ihrem plentymarkets System. Erstellen Sie im Menü *System » Einstellungen » Benutzer » Konten* ein neues Benutzerkonto der Benutzerklasse *API* für Restposten.de. Aktivieren Sie außerdem den Call *GetCategoryMappingForMarket*. Dieser Call sorgt dafür, dass der Marktplatz später Ihre Kategorieverknüpfungen auslesen kann.

[.instruction]
Benutzerkonto für Restposten.de erstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Klicken Sie auf *Neu*. +
→ Das Fenster *Neuen Benutzer erstellen* wird geöffnet.
. Geben Sie die Daten ein.
. Wählen Sie als Benutzerklasse *API*.
. *Speichern* Sie die Einstellungen. +
→ Der Benutzer wird erstellt.
. Wählen Sie den Benutzer aus der Liste. +
→ Das Bearbeitungsfenster wird geöffnet.
. Öffnen Sie das Tab *Berechtigung » API*.
. Klappen Sie den Bereich *Item* auf.
. Aktivieren Sie den Call *GetCategoryMappingForMarket*.
. *Speichern* Sie die Einstellungen.

Weitere Informationen finden Sie auf der Handbuchseite <<basics/admin-aufgaben/benutzer-verwalten#, Benutzerkonten verwalten>>.

[#300]
== Daten bereitstellen

Für die Anbindung an Ihr plentymarkets System benötigt Restposten.de die folgenden Daten von Ihnen:

* URL der SOAP API WSDL. +
→ Sie finden die URL im Menü <<basics/datenaustausch/api-daten#, System » Einstellungen » API » Daten>> unter *SOAP WSDL*.
* Benutzername und Passwort für das von Ihnen erstellte Benutzerkonto für Restposten.de
* Ihre Login-Daten für das Händlerportal von Restposten.de.

[#350]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit Restposten verknüpfen können, muss im Menü *System » Aufträge » Auftragsherkunft* die Auftragsherkunft Restposten aktiviert werden.

[.instruction]
Auftragsherkunft für Restposten aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Auftragsherkunft*.
. Setzen Sie bei *Restposten* ein Häkchen.
. *Speichern* Sie die Einstellungen.

[#400]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf Restposten.de verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#180, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Restposten.de einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Setzen Sie ein Häkchen bei der Option *Restposten*.
. Setzen Sie ein Häkchen bei der Option *Web-API*.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen. +
→ Der Artikel ist auf Restposten.de verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

[#430]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügen Sie, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wählen Sie die Herkunft *Restposten*.
. Geben Sie die SKU ein.
. Klicken Sie auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#450]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft Restposten.de einen Verkaufspreis festzulegen. Dieser Preis wird auf Restposten.de angezeigt.

[.instruction]
Verkaufspreis für Restposten.de festlegen:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setzen Sie ein Häkchen bei der Herkunft *Restposten*.
. *Speichern* Sie die Einstellungen.

[#500]
== Merkmale erstellen

Mit <<artikel/artikel-verwalten#480, Merkmalen>> verknüpfen Sie bestimmte Eigenschaften, die Sie für die Einrichtung des Marktplatzes Restposten.de benötigen, mit Ihren Artikeln. Das Merkmal muss als *Merkmaltyp* mit der Option *Auswahl* erstellt sein, damit Restposten.de die nötigen Parameter abrufen kann. Stimmen Sie mit Restposten.de ab, welche Werte für das Merkmal benötigt werden.

[.instruction]
Merkmal für Restposten.de erstellen:

. Öffnen Sie das Menü *System » Artikel » Merkmale*.
. Wechseln Sie in das Tab *Neues Merkmal*.
. Geben Sie den Namen unter *Name (intern)* ein.
. Wählen Sie als *Merkmaltyp* die Option *Auswahl*. +
→ Ein Bereich wird geöffnet, in dem Sie Namen und Bezeichnung eingeben.
. *Speichern* Sie die Einstellungen. +
→ Das Merkmal wird erstellt.
. Wechseln Sie in das Tab *Merkmale*.
. Klappen Sie das Merkmal auf.
. Geben Sie im Bereich *Auswahl* in das nächste Auswahlfeld einen weiteren Namen ein.
. *Speichern* Sie die Einstellung.
. Wiederholen Sie Vorgang 8 und 9, bis alle benötigten Werte erstellt sind.
. *Speichern* Sie die Einstellungen.

[#600]
== Kategorien verknüpfen

Verknüpfen Sie Ihre Webshop-Kategorien mit den <<artikel/kategorien-verwalten#, Kategorien>> von Restposten.de, damit Ihre Artikel in diesen Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffnen Sie das Menü *System » Märkte » Restposten*. +
→ Das Tab *Kategorieverknüpfung* wird angezeigt.
. Klappen Sie die Kategorie auf, die Sie mit einer Restposten-Kategorie verknüpfen möchten.
. Wählen Sie eine Restposten-Hauptkategorie aus der Dropdown-Liste. +
→ Ein Fenster mit Unterkategorien wird geöffnet.
. Wählen Sie aus den weiteren Unterkategorien jeweils die passende Restposten-Kategorie. +
→ Der Kategoriepfad erscheint im Textfeld *Kategorie*.
. Klicken Sie auf *Übernehmen*. +
→ Das Kategoriefenster wird geschlossen.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Verknüpfung bis in die unterste Kategorieebene
====
Verknüpfen Sie Ihre Kategorien immer bis in die unterste Ebene. Andernfalls ist eine Verknüpfung nicht möglich.
====

[#700]
Retouren

Für Retouren müssen Sie einen Auftrag vom Typ *Retoure* erstellen und keine Gutschrift. Achten Sie auch darauf, den Artikelwert in Prozent in den Artikelpositionen der Retoure anzugeben.
