= REWE
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: Rewe, Marktplatz, rewe.de, Rewe einrichten, Rewe Marktplatz, Multi-Channel, Multichannel, Multi-Channel Rewe, Multichannel Rewe, Multi Channel Rewe
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz REWE in deinem plentymarkets System ein.
:position: 210
:url: maerkte/rewe
:id: VCPKDKC

[IMPORTANT]
.Rewe-Plugin herunterladen
====
Die Schnittstelle zu Rewe wird über ein Plugin integriert. Um das REWE-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/rewe_5901[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

:plugin: REWE
include::_textblocks/instructions/plugin-installation.adoc[]

[#100]
== Bei REWE registrieren

Der REWE-Marktplatz ist ein geschlossener Marktplatz. Damit du dich als Händler:in bei REWE registrieren kannst, ist eine Prüfung durch REWE erforderlich. Sende dazu eine E-Mail an partnersupport@rewe.de und gib folgende Informationen an:

* Name deines Unternehmens
* Website deines Unternehmens bzw. Onlineshop
* Auflistung deines Sortiments (Anzahl SKUs, Kategorien, verpflichtende Kennzeichnung)
* Kontaktinformationen

Für weitere Informationen zur Prüfung und Registrierung kontaktiere REWE unter partnersupport@rewe.de.

Nachdem du dich als Händler:in registriert hast, erhältst du Zugangsdaten von REWE.


[IMPORTANT]
.Rechte vergeben
====
Achte bei der Erstellung deiner API-Client-Zugangsdaten bei REWE darauf, dass du genügend Rechte vergibst. Wähle die Vorlage *Admin-Client* oder erstelle einen neuen Client und vergib alle verfügbaren Rechte.
====

Nach dem Installieren des REWE-Plugins stehen folgende automatisierte Prozesse bereit:

* täglicher Artikelexport
* viertelstündlicher Bestandsabgleich
* stündlicher Preisabgleich
* viertelstündlicher Auftragsimport

[#200]
== REWE in plentymarkets installieren

Nachdem du das REWE-Plugin im plentyMarketplace gekauft hast, installiere den Marktplatz im Menü *Plugins » Plugin-Übersicht*.

[#300]
=== Authentifizierung durchführen

Nachdem du das REWE-Plugin installiert hast, musst du zunächst eine Authentifizierung durchführen, um den Zugang zur Schnittstelle zu ermöglichen.

[.instruction]
Zugang zur Schnittstelle aktivieren:

. Öffne das Menü *Einrichtung » Märkte » REWE » Konto-Einstellungen*.
. Gib in die Felder *Benutzername*, *Passwort* und *Produktschlüssel* die Zugangsdaten ein, die du von REWE erhalten hast.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#400]
== Automatischen Datenaustausch aktivieren

Richte den Marktplatz REWE im Menü *Einrichtung » Märkte » REWE » Grundeinstellungen* ein. Aktiviere zunächst den Artikelexport, den Bestands- und Preisabgleich und den Auftragsimport in diesem Menü, damit die Daten automatisch mit REWE ausgetauscht werden.

[.instruction]
Automatischen Datenaustausch aktivieren:

. Öffne das Menü *Einrichtung » Märkte » REWE » Grundeinstellungen*.
. Aktiviere die Einstellungen *Artikelexport*, *Bestands- und Preisabgleich* und *Auftragsimport*, um den automatischen Datenaustausch mit REWE zu aktivieren.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#450]
== Bestandsübermittlung festlegen

Standardmäßig werden für jede Variante die Bestandsinformationen übermittelt, die du über die Einstellung *Beschränkung* an der Variante festlegst. Ab Plugin-Version 1.18.0 kannst du diese Einstellung aber ignorieren und für alle Varianten den tatsächlichen Netto-Warenbestand an REWE übermitteln.

[.instruction]
Bestandsübermittlung festlegen:

. Öffne das Menü *Einrichtung » Märkte » REWE » Grundeinstellungen*.
. Wähle eine Option für *Bestand übertragen*. Beachte <<#rewe-bestand>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[rewe-bestand]]
.Bestandsübermittlung festlegen
[cols="1,3a"]
|====
|Einstellung |Erläuterung

| *Bestand übertragen* +
(ab Plugin-Version 1.18.0)
a| * *Varianteneinstellung 'Beschränkung' berücksichtigen* (Standardeinstellung) = Der Bestand wird für jede Variante so übermittelt, wie an der Variante eingestellt. Die Beschränkung des Bestands wird im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Tab: Varianten-ID » Tab: Einstellungen » Bereich: Verfügbarkeit* über die Einstellung *Beschränkung* gesteuert. +
*_Hinweis:_* Für Varianten, bei denen die Einstellung *Beschränkung* auf *Keinen WB für diese Variante führen* gestellt sind, wird ein Bestand von 1000 an REWE übertragen. +
* *Tatsächlichen Netto-Warenbestand übertragen* = Die an der Variante eingestellte *Beschränkung* des Bestands wird für alle Varianten, die an REWE übertragenen werden, ignoriert. Stattdessen wird für jede Variante der tatsächliche Netto-Warenbestand an REWE übermittelt. Den tatsächlichen Netto-Warenbestand findest du im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Tab: Varianten-ID » Tab: Bestand » Tab: Warenbestand* in der Spalte *Netto*. +
*_Hinweis:_* Für Varianten, bei denen die Einstellung *Beschränkung* auf *Keinen WB für diese Variante führen* gestellt sind, wird ein Bestand von 0 an REWE übertragen. Die Variante ist also auf REWE nicht kaufbar. +
*_Tipp:_* Der Netto-Warenbestand ist die Menge der Varianten, die zum Verkauf zur Verfügung steht. Der Netto-Warenbestand ist eine Teilmenge des physischen Bestands. Wenn vom physischen Warenbestand alle Reservierungen abgezogen werden, ergibt sich der Netto-Bestand.

|====

[#500]
== Provision einstellen

[TIP]
.Provisionseinstellungen sind optional
====
Die Einstellungen zur Provision bei REWE sind optional. Wenn du keine Provision einstellst, werden Aufträge mit den Verkaufspreisen, die auf REWE angezeigt werden, in dein plentymarkets System importiert. +
Wenn keine Provision eingestellt wird, werden die Preise auch auf dem Lieferschein ohne Provision angezeigt.
====

Im Menü *Einrichtung » Märkte » REWE » Grundeinstellungen* legst du die Standardprovision fest. Mit der Provision werden provisionsfreie Aufträgsbeträge berechnet.

Provisionsfreie Auftragsbeträge werden folgendermaßen berechnet:

* Verkaufspreis REWE = Verkaufspreis Endkund:in * (1 - Umrechnungsfaktor)
* Umrechnungsfaktor = Provision * (1 + Mehrwertsteuersatz)

Für die Berechnung werden die Prozentsätze für Provision und Mehrwertsteuersatz in den entsprechenden Faktor umgerechnet, also durch 100 geteilt. Der Umrechnungsfaktor wird auf die 3. Nachkommastelle gerundet, wie auch bei REWE.

[.instruction]
Provision einstellen:

. Öffne das Menü *Einrichtung » Märkte » REWE » Grundeinstellungen*.
. Gib im Bereich *Provision* eine Zahl für die Provision in Prozent ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die eingestellte Provision ist die Standardprovision für alle Artikel, außer Varianten, für die eine separate Provision eingestellt wurde.

Für Varianten kann mit der Eigenschaft *REWE Provision* eine separate Provision eingestellt werden. Die Eigenschaft *REWE Provision* wird beim Installieren des REWE-Plugins automatisch erstellt. Um eine separate Provision für eine Variante festzulegen, verknüpfe die Variante mit der Eigenschaft *REWE Provision*.

[.instruction]
Separate Provision für Varianten einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Varianten*.
. Öffne die Variante, für die du eine separate Provision einstellen möchtest.
. Wechsele in das Tab *Eigenschaften* der Variante.
. Wähle aus der Dropdown-Liste *Eigenschaften* die Eigenschaft *REWE Provision*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird mit der Variante verknüpft.
. Gib in das Eingabefeld *Wert* eine Zahl oder Kommazahl für die Provision in Prozent ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#600]
== Auftragsherkunft aktivieren

:market: REWE
:referrer: REWE
:referrer-option: pass:quotes[Option *Rewe*]

include::_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#700]
== Variantenverfügbarkeit einstellen

:market-availability: REWE
:option-availability: REWE

include::_textblocks/instructions/variantenverfuegbarkeit.adoc[]

// Web-API NICHT erforderlich!

[#800]
== Varianten mit Eigenschaft REWE-Produkttyp verknüpfen

Varianten, die du auf REWE verkaufen möchtest, müssen mit der Eigenschaft *REWE-Produkttyp* verknüpft werden. Diese Eigenschaft wird in deinem plentymarkets System erstellt, sobald du das REWE-Plugin installiert hast. Beispiele für REWE-Produkttypen sind:

* Haushalt
* Garten
* Fashion

:property-link: REWE-Produkttyp
:property-selection:
:property-link-info: Als Werte stehen die REWE-Produkttypen zur Auswahl.

include::_textblocks/instructions/properties-link-to-variation.adoc[]

[#900]
== Artikelexport einrichten

Artikeldaten werden über Kataloge zu REWE übertragen. Mit dem Assistenten *REWE-Katalog erstellen* erstellst du einen Katalog pro Produktkategorie. Du arbeitest zum ersten Mal mit den Katalogen? Dann solltest du dich zuerst <<daten/daten-exportieren/kataloge-verwalten#, mit dem Prinzip der Kataloge vertraut machen>>. Dort findest du auch weitere Informationen zu den plentymarkets <<daten/daten-exportieren/kataloge-verwalten#_datenquellen_zuordnen, Datenfeldern>>, die du zuordnen kannst.

Zurzeit kannst du mit dem REWE-Plugin Kataloge für die folgenden REWE-Produktkategorien erstellen:

* *Haushalt*
* *Multimedia*
* *Drogerie*
* *Fashion*
* *Freizeit/Sport*
* *Schreibwaren*
* *Spielwaren*
* *Garten*
* *Babybedarf*
* *Kontaktlinsen*
* *Neue Medien (DVD etc.)*
* *Bücher und Zeitschriften*
* *AFG* (Alkoholfreie Getränke)
* *Alkoholhaltige Getränke*
* *Lebensmittel* +
*_Hinweise zur Produktkategorie Lebensmittel:_* +
  ** Alle Lebensmittelangaben müssen pro 100g angegeben werden.
  ** Energieangaben müssen in kcal angegeben werden.
  ** Wenn dem Feld *Nährwertangaben für zubereitete oder nicht zubereitete Lebensmittel* kein Wert zugeordnet wurde, wird standardmäßig der Wert *unbehandelt* an REWE übertragen.

[#1000]
== Besonderheiten der REWE-Artikeldatenstruktur: Produktgruppen und Varianten

Bei REWE wird zwischen *Produktgruppen* und *Variantengruppen* unterschieden:

[cols="1,5a"]
|====
| Produktgruppe
| Produktgruppenattribute sind Attribute, die das Aussehen des Produkts beeinflussen:

* Die Varianten unterscheiden sich optisch voneinander.
* Deshalb hat jede plentymarkets Variante eigene Bilder.

*_Beispiele:_*

* Ein Artikel wird in unterschiedlichen Farben und/oder mit unterschiedlichen Motiven angeboten.
* Ein Artikel wird in unterschiedlichen Packungsgrößen angeboten, die sich optisch unterscheiden.

*_Entsprechung in plentymarkets:_*

In plentymarkets sind Produktgruppen also Artikel, deren Varianten je nach Produkttyp mindestens ein REWE-Gruppenattribut besitzen.

*_Beispiel für Attribute:_*

Für den Produkttyp Lebensmittel stehen die folgenden *Attribute für Produktgruppe* zur Verfügung (Stand: 05/2021):

* Geschmacksrichtung
* Packungsgröße
* Sorte

*_Besonderheiten bei der Katalog-Zuordnung:_*

Artikel in plentymarkets können mehrere REWE-Gruppenattribute besitzen. Bei der Übertragung zu REWE kann aber nur ein REWE-Gruppenattribut verwendet werden, um Produktgruppen zu bilden. Deswegen muss im Katalog die Option *Attribut für Produktgruppe* so verknüpft werden, dass das erste Attribut immer das Attribut ist, über das du diese Gruppe bilden möchtest. Wenn sich zum Beispiel ein Artikel in Farbe und Motiv unterscheidet und das Motiv das REWE-Gruppenattribut sein soll, muss das Motiv für das Marktplatz-Datenfeld *Attribut für Produktgruppe* als erstes zugeordnet werden und erst dann die Farbe.

*_Tipp:_*

Welche REWE-Gruppenattribute für einen Produkttyp zur Verfügung stehen, siehst du, wenn du einen Katalog mit Template erstellt hast. Öffne dazu im Marktplatz-Format die Dropdown-Liste *Attribut für Produktgruppe*.

| Varianten
| Variantenattribute sind Attribute, die keinen Einfluss auf das Aussehen des Produktes haben:

* Die Varianten unterscheiden sich optisch nicht voneinander.
* Die Bilder sind deshalb für alle Varianten des Artikels gleich.

*_Beispiele:_*

* Ein Artikel wird in verschiedenen Größen angeboten. Optisch unterscheiden sich diese Größen nicht voneinander.
* Ein Artikel wird in verschiedenen Packungsgrößen angeboten. Die Bilder sind jedoch für alle Varianten gleich.

*_Entsprechung in plentymarkets:_*

In plentymarkets sind *Varianten* also Varianten eines Artikels, die je nach Produkttyp höchstens ein REWE-Variantenattribut besitzen.

*_Beispiel für Attribute:_*

Für den Produkttyp Lebensmittel stehen die folgenden *Attribute für Variantengruppe* zur Verfügung (Stand 05/2021):

* Durchmesser
* Abmessungen
* Grösse

*_Besonderheiten bei der Katalog-Zuordnung:_*

* Bei REWE-Variantenattributen kann nur ein Variantenattribut gesetzt sein, zum Beispiel nur Größe oder nur Volumen.
* Ein Artikel sollte nicht mit mehr als einem Attribut verknüpft sein, das im Katalog als REWE-Variantenattribut zugeordnet wurde.

*_Tipp:_*

Welche REWE-Variantenattribute für einen Produkttyp zur Verfügung stehen, siehst du, wenn du einen Katalog mit Template erstellt hast. Öffne dazu im Marktplatz-Format die Dropdown-Liste *Attribut für Variantengruppe*.

|====

[#905]
==== Besonderheiten bei der Zuordnung von Datenfeldern

Jeder Marktplatz strukturiert Artikeldaten anders. Deshalb treten beim Zuordnen von Datenfeldern bestimmte Sonderfälle auf. In <<#catalogue-rewe-mappings>> findest du Hinweise dazu, was du beim Zuordnen von Datenfeldern für REWE beachten solltest.

[[catalogue-rewe-mappings]]
.Besonderheiten bei der Katalogzuordnung
[cols="1,3a"]
|====
| Marktplatz-Datenfeld | plentymarkets Datenfeld

| *Attribut für Produktgruppe*
a|


*_Beispiel:_* Für den Produkttyp Fashion steht die folgenden Attribute für Produktgruppe *Grösse (General size)* zur Verfügung:

* Farbe (Color)
* Geschlecht (Gender)
* Material (Material)
* Motiv (Motive)
* Stück (Piece)

[.collapseBox]
.*_Beispiel:_* Attribute für Produktgruppe für Produkttyp Drogerie zuordnen
--
Als Beispiel wird hier beschrieben, wie du in einem Katalog für den Produkttyp Drogerie Attribute für Produktgruppen korrekt zuordnest.

[.instruction]
Angenommene Ausgangssituation:

Du möchtest deine Varianten in der REWE-Produktkategorie Drogerie anbieten.

Zur Erinnerung: Für den Produkttyp Drogerie stehen die folgenden Attribute für Produktgruppe *Grösse (General size)* zur Verfügung (Stand: 05/2021):

* Farbe (Color)
* Geschlecht (Gender)
* Material (Material)
* Motiv (Motive)
* Stück (Piece)

Die folgenden Produktdaten pflegst du als variantenbildende Attribute:

* Farbe
* Stück

Die folgenden Produktdaten pflegst du als Eigenschaften:

* Material
* Motiv
* Geschlecht

Artikel in plentymarkets können mehrere REWE-Gruppenattribute besitzen. Bei der Übertragung zu REWE kann aber nur ein REWE-Gruppenattribut verwendet werden, um Produktgruppen zu bilden. Deswegen muss im Katalog die Option *Attribut für Produktgruppe* so verknüpft werden, dass das erste Attribut immer das Attribut ist, über das du diese Gruppe bilden möchtest. Wenn zum Beispiel ein Artikel, zum Beispiel ein T-Shirt, sich in Farbe und Motiv unterscheidet und das Motiv das REWE-Gruppenattribut sein soll, muss das Motiv für die Option *Attribut für Produktgruppe* als erstes verknüpft werden und erst dann die Farbe.

Du musst also entscheiden, welches Attribut zur Bildung der Produktgruppe verwendet werden soll.



-


[.instruction]
Attribut für Produktgruppe für Produkttyp Drogerie zuordnen:

. Öffne den REWE-Katalog mit dem Format *Fashion*.
. Navigiere zum Bereich *Attribut für Produktgruppe*.
. Ordne den Marktplatz-Datenfeldern die folgenden plentymarkets Datenfelder zu:
  . Marktplatz-Datenfeld *Farbe*: Feld *Wertname* des Attributs für *Farbe* +
  . Marktplatz-Datenfeld *Geschlecht*: Feld *Wertname* des Attributs für *Farbe* +
  . Marktplatz-Datenfeld *Material*: Feld *Wertname* des Attributs für *Farbe* +
  . Marktplatz-Datenfeld *Motiv*: Feld *Wertname* des Attributs für *Farbe* +
  . Marktplatz-Datenfeld *Stück*: Feld *Wertname* des Attributs für *Farbe* +

. Ordne dem Marktplatz-Datenfeld *Farbwert: green* den plentymarkets Attributwert *Hellgrün* zu.
. Klicke auf *+ Ausweich-Datenfeld hinzufügen*.
. Ordne als erstes Ausweich-Datenfeld den plentymarkets Attributwert *Dunkelgrün* zu.
. Klicke auf *+ Ausweich-Datenfeld hinzufügen*.
. Ordne als zweites Ausweich-Datenfeld den plentymarkets Eigenschaftswert *Neongrün* zu.
. Klicke auf *+ Ausweich-Datenfeld hinzufügen*.
. Ordne als drittes Ausweich-Datenfeld den plentymarkets Eigenschaftswert *Koriander* zu. +
→ Für Händler-Produkt-ID und Produktname wird der in plentymarkets an der Variante gespeicherte Grünton exportiert. +
→ Alle Produkte werden auf limango mit der Farbe "grün" gelistet. +
*_Tipp:_* Die hier gewählte Reihenfolge ist willkürlich. Du kannst die Werte in einer beliebigen Reihenfolge angeben.
--

|====

=== Katalog mit dem Assistenten erstellen

:catalogue-assistant-name: REWE-Katalog erstellen
:number-of-boxes: Info-Boxen
:catalogue-path: pass:quotes[*Einrichtung » Assistenten » Plugins » [Mandant öffnen]*]
:catalogue-note: Für jede Produktkategorie benötigst du einen eigenen Katalog.
:mapping-fields: weitere

include::_textblocks/instructions/catalogue-assistant-config.adoc[]

[.collapseBox]
.Schritt *Einstellungen*
--
[[table-rewe-catalogue-assistant]]
[width="100%"]
[cols="1,2a"]
|====
| Einstellung | Erläuterung

| *Für welche REWE-Produktkategorie möchtest du diesen Katalog erstellen?*
| Eine Produktkategorie aus der Dropdown-Liste wählen. +
*_Hinweis:_* Für jede Produktkategorie benötigst du einen eigenen Katalog.

| *Gib einen Namen für den REWE-Katalog ein.*
a| Name für den Katalog eingeben. Der Katalog wird unter diesem Namen im Menü *Daten » Kataloge* angezeigt.
|====
--

[.collapseBox]
.Schritt *Basisfelder verknüpfen*
--
In diesem Schritt des Assistenten legst du fest, welche in plentymarkets gespeicherten Variantendaten an den Marktplatz gesendet werden sollen. Dazu ordnest du jedes angezeigte Feld des Marktplatzes dem plentymarkets Datenfeld zu, das die Daten enthält, die du an den Marktplatz exportieren möchtest. Statt ein vorhandenes Datenfeld zuzuordnen, kannst du für bestimmte Datenfelder auch ein neues Datenfeld erstellen.

'''
*SKU* = Wähle das Datenfeld aus der Dropdown-Liste, das als SKU übertragen werden soll. +
*_Empfehlung:_* Die Varianten-ID ist der Variante eindeutig zugeordnet. Ordne dem Marktplatz-Datenfeld *SKU* deshalb das plentymarkets Datenfeld *Varianten-ID* zu.

'''
*Datenfeld wählen* = Ein bereits in plentymarkets vorhandenes Datenfeld wird an REWE exportiert. Ein Datenfeld aus der Dropdown-Liste *Datenfeld* wählen. +
*_Hinweis:_* Die Zuordnungen, die du vornimmst, werden nicht auf Sinnhaftigkeit geprüft. Prüfe deshalb die Zuordnungen sorgfältig, bevor du den Export startest.

'''
*Eigenschaft anlegen* = Erstellt eine <<artikel/einstellungen/eigenschaften#500, Eigenschaft>> und ordnet diese Eigenschaft dem Datenfeld zu. Mit Eigenschaften kannst du Werte für Datenfelder übergeben, die in plentymarkets standardmäßig nicht in den Artikeldaten gespeichert werden können, zum Beispiel *Durchmesser*.

Automatisch erstellte Eigenschaften werden im Menü <<artikel/einstellungen/eigenschaften#500, Einrichtung » Einstellungen » Eigenschaften » Konfiguration>> gespeichert.

Automatisch erstellte Eigenschaften haben die folgenden Einstellungen:

* Bereich = Artikel
* Eigenschaftstyp = _je nach Marktplatz-Datenfeld_
* Sprache = Deutsch
* Name = _Name der Produktkategorie_
* Gruppe = REWE

'''
*Verkaufspreis anlegen* = Erstellt einen neuen Verkaufspreis und ordnet diesen Verkaufspreis dem Datenfeld zu. Automatisch erstellte Verkaufspreise können im Menü <<artikel/einstellungen/preise#400, Einrichtung » Artikel » Verkaufspreise>> geprüft und bearbeitet werden.

Automatisch erstellte Verkaufspreise haben die folgenden Einstellungen:

* Abo-Intervall = Keins
* Interner Name = REWE
* Externer Name = REWE
* Ab Menge = 1
* Live umrechnen = Nein
* Währung = Euro
* Darstellung = Bei neuem Artikel immer anzeigen
* Mandant = ALLE
* Klasse = ALLE
* Land = Deutschland

'''
*Barcode anlegen* = Erstellt einen Barcode *REWE* und ordnet diesen Barcode dem Datenfeld zu. Ist bereits ein Barcode mit dem Namen *REWE* im System, wird stattdessen dieser Barcode zugeordnet. Automatisch erstellte Barcodes können im Menü <<artikel/einstellungen/barcodes#100, Einrichtung » Artikel » Barcodes>> geprüft und bearbeitet werden.
--

[#600]
=== Weitere Datenfelder im Katalog zuordnen (nicht im Assistenten)

Mit dem Assistenten hast du bereits wichtige Pflichtfelder für die gewählte Produktkategorie zugeordnet. Nachdem du den Assistenten abgeschlossen hast, musst du aber noch weitere Datenfelder zuordnen, um noch mehr Informationen zu deinen Produkten an REWE zu übermitteln.

include::_textblocks/instructions/katalog-assistent-datenfelder-zuordnen.adoc[]

////
[#605]
=== Besonderheiten bei der Zuordnung von Datenfeldern

Wenn die Varianten eines Artikels unterschiedliche Bilder haben, weil sie sich optisch unterscheiden, wird eine REWE Produktgruppe benötigt. Varianten unterscheiden sich zum Beispiel in den folgenden Fällen optisch:

* Ein Artikel wird in unterschiedlichen Farben angeboten. Jede plentymarkets Variante hat eigene Bilder.
* Ein Artikel wird in unterschiedlichen Packungsgrößen angeboten. Weil sich die Verpackungen unterscheiden, hat jede plentymarkets Variante eigene Bilder.


|====
////

[#602]
=== _Beispiel:_ Datenfeld "Produktbeschreibung" zuordnen

Im Folgenden wird beispielhaft beschrieben, wie du das Pflichtfeld *Produktbeschreibung* den Artikeldaten aus plentymarkets zuordnest.

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet.
. Wähle für das REWE-Datenfeld *Produktbeschreibung* ein plentymarkets Datenfeld aus der Dropdown-Liste.
*_Beispiel:_* *Artikeltext > Name 1*, *Name 2* oder *Name 3*
. Nimm die weiteren Zuordnungen analog vor. Ordne mindestens alle Pflichtfelder zu. +
*_Tipp:_* Pflichtfelder sind mit Sternchen (*) gekennzeichnet.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das gewählte plentymarkets Datenfeld wird auf REWE als Produktbeschreibung angezeigt.

[#701]
== Im Assistenten erstellte Datenfelder mit Varianten verknüpfen

:property-group: REWE

include::_textblocks/instructions/assistent-quellen-verknuepfen.adoc[]

[#2000]
== Katalogexport zu REWE aktivieren

:interval: einmal täglich
:market: REWE
:if-active: pass:quotes[wenn im Menü *Einrichtung » Märkte » REWE » Grundeinstellungen* die Option *Artikelexport* aktiviert ist]

include::_textblocks/instructions/catalogue-activation.adoc[]

[#1100]
== Versanddienstleister verknüpfen

Im Menü *Einrichtung » Märkte » REWE » Versanddienstleister-Verknüpfung* verknüpfst du die in plentymarkets gespeicherten Versanddienstleister mit den Versanddienstleistern von REWE. Wenn du keinen Versanddienstleister verknüpfst, wird automatisch der Versanddienstleister *unknown* zu REWE übertragen.

[.instruction]
Versanddienstleister verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » REWE » Versanddienstleister-Verknüpfung*.
. Wähle aus der Dropdown-Liste den REWE-Versanddienstleister.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#1200]
== Retourengründe verknüpfen

Im Menü *Einrichtung » Märkte » REWE » Retourengrund-Verknüpfung* verknüpfst du die in plentymarkets gespeicherten Retourengründe mit den Retourengründen von REWE. Wenn du keinen Retourengrund verknüpfst, wird automatisch der Retourengrund *Sonstiges* zu REWE übertragen. Weitere Informationen zu REWE-Retourengründen findest du in der Händlerdokumentation, die du von REWE erhalten hast.

[.instruction]
Retourengründe verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » REWE » Retourengrund-Verknüpfung*.
. Wähle aus der Dropdown-Liste den REWE-Retourengrund.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#1300]
== Steuerklassen synchronisieren

Wenn die Steuerklassen bei REWE geändert wurden, musst du die Steuerklassen in plentymarkets synchronisieren. Steuerklassen werden im Menü *Einrichtung » Märkte » REWE » Grundeinstellungen* im Bereich *Steuerklassen* mit REWE synchronisiert.

[.instruction]
Steuerklassen synchronisieren:

. Öffne das Menü *Einrichtung » Märkte » REWE » Grundeinstellungen*.
. Klicke im Bereich *Steuerklassen* auf *Synchronisieren*. +
→ Die Steuerklassen werden mit REWE abgeglichen.

Unter *Letzte Aktualisierung* wird angezeigt, wann die Steuerklassen zuletzt mit REWE abgeglichen wurden.

[WARNING]
.Steuerklassen vor Wechsel auf REWE-Live-System synchronisieren
====
Bevor deine Artikel bei REWE von der Stage-Testumgebung auf das Live-System wechseln, musst du bei plentymarkets die Steuerklassen erneut synchronisieren, da dein Artikelkatalog sonst nicht übertragen wird. Gib für den Wechsel auf das Live-System zunächst deine Zugangsdaten und den Produktschlüssel für das Live-System ein und synchronisiere danach die Steuerklassen. Nachdem du die Steuerklassen synchronisiert hast, musst du sie in deinen REWE-Katalogen neu verknüpfen.
====

[#1400]
== Marken synchronisieren

Marken werden einmal täglich automatisch mit REWE abgeglichen. Außerdem hast du die Möglichkeit, im Menü *Einrichtung » Märkte » REWE » Grundeinstellungen* Marken jederzeit manuell mit REWE abzugleichen.

[.instruction]
Marken manuell synchronisieren:

. Öffne das Menü *Einrichtung » Märkte » REWE » Grundeinstellungen*.
. Klicke im Bereich *Marken* auf *synchronisieren*. +
→ Die Marken werden mit REWE abgeglichen. +
*_Tipp:_* Unter *Letzte Aktualisierung* wird angezeigt, wann die Marken zuletzt mit REWE abgeglichen wurden.

[#1700]
== Kontakterstellung deaktivieren (ab Plugin-Version 1.24.0)

Standardmäßig werden REWE-Aufträge immer dem Kontakt und der Rechnungsadresse von REWE zugeordnet. Optional kannst du die Option *Kontakterstellung deaktivieren* aktivieren, um keinen Kontakt zu pflegen und stattdessen nur die Adressen zu speichern. <<#rewe-kontakterstellung-deaktiveren>> beschreibt die Unterschiede zwischen den beiden Einstellungsmöglichkeiten.

[[rewe-kontakterstellung-deaktiveren]]
.Kontakterstellung deaktivieren
[cols="1,3a"]
|====
|Einstellung |Erläuterung

| *Kontakterstellung deaktivieren*
a|
* _Option deaktiviert_ (Standardeinstellung) = Die Kontakterstellung ist deaktiviert. Beim Import des ersten REWE-Auftrags wird für REWE ein Kontakt erstellt. Alle weiteren REWE-Aufträge werden mit diesem Kontakt verknüpft. Alle Rechnungsadressen werden diesem Kontakt zugeordnet.

  ** Im Auftrag ist das Tab *Kontakt* verfügbar.
  ** Über das Menü *CRM » Kontakte* ist der Kund:innendatensatz auffindbar.
  ** Über das Menü *CRM » Schnellsuche* können die Adresseinträge und der zugehörige Auftrag gefunden werden.

[.collapseBox]
.Ablauf des Auftragsimports im Detail
--
. Es wird geprüft, ob REWE bereits als Firma im System gespeichert ist.
. Wenn die Firma noch nicht im System gespeichert ist, wird die Firma erstellt.
. Es wird geprüft, ob REWE bereits als Kontakt im System gespeichert ist.
. Wenn der Kontakt noch nicht im System gespeichert ist, wird der Kontakt erstellt.
. Wenn ein neuer Kontakt erstellt wird, wird der Kontakt mit der Firma verknüpft.
. Es wird geprüft, ob die Rechnungsadresse bereits im System gespeichert ist.
. Wenn die Rechnungsadresse noch nicht im System gespeichert ist, wird die Rechnungsadresse erstellt.
. Die Rechnungsadresse wird mit dem Kontakt verknüpft.
. Die Rechnungsadresse wird mit dem Auftrag verknüpft.
. Eine Lieferadresse wird erstellt. Dabei wird nicht geprüft, ob die Lieferadresse bereits im System gespeichert ist. Die Lieferadresse wird außerdem nicht mit einem Kontakt verknüpft.
. Die Lieferadresse wird mit dem Auftrag verknüpft.
--

* _Option aktiviert_ = Die Kontakterstellung ist deaktiviert. Beim Import von REWE-Aufträgen wird kein Kontakt erstellt. Rechnungsadresse und Lieferadresse werden erstellt und dem Auftrag zugeordnet.

  ** Im Auftrag entfällt das Tab *Kontakt*.
  ** Über das Menü *CRM » Kontakte* ist der Kund:innendatensatz nicht mehr auffindbar.
  ** Über das Menü *CRM » Schnellsuche* können die Adresseinträge und der zugehörige Auftrag gefunden werden.

[.collapseBox]
.Ablauf des Auftragsimports im Detail
--
. Es wird geprüft, ob die Rechnungsadresse bereits im System gespeichert ist.
. Wenn die Rechnungsadresse noch nicht im System gespeichert ist, wird die Rechnungsadresse erstellt.
. Die Rechnungsadresse wird mit dem Auftrag verknüpft.
. Eine Lieferadresse wird erstellt. Dabei wird nicht geprüft, ob die Lieferadresse bereits im System gespeichert ist. Die Lieferadresse wird außerdem nicht mit einem Kontakt verknüpft.
. Die Lieferadresse wird mit dem Auftrag verknüpft.
--
|====

[.instruction]
Kontakterstellung deaktivieren:

. Öffne das Menü *Einrichtung » Märkte » REWE » Grundeinstellungen*.
. Navigiere zum Bereich *Auftragsimport*.
. Aktiviere die Option *Kontakterstellung deaktivieren*.
. *Speichere* (icon:save[role="green"]) die Einstellung. +
→ Pro Auftrag werden nur Rechnungsadresse und Lieferadresse erstellt und dem Auftrag zugeordnet. +
→ Ein Kontakt wird nicht erstellt.



[#1500]
== Auftragsstatus bei REWE automatisch aktualisieren

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um den Auftragsstatus bei REWE automatisch zu aktualisieren, wenn bestimmte Ereignisse eintreten. Folgende Ereignisaktionen können eingerichtet werden:

* Auftragsposition als nicht vorrätig an REWE melden
* Stornierung durch Käufer an REWE melden
* Stornierung durch Händler an REWE melden
* Versandvorbereitung an REWE melden
* Versandvorbereitungsabschluss an REWE melden
* Versandbestätigung an REWE melden
* Paketzustellung an REWE melden
* Retourenabschluss an REWE melden

Beispielhaft wird hier eine Ereignisaktion beschrieben, mit der du die Versandbestätigung an REWE meldest. Richte weitere Ereignisaktionen analog dazu ein.

:table-event-procedure: <<#rewe-ereignisaktion>>

include::../_includes/textblocks/instructions/EA.adoc[]

[[rewe-ereignisaktion]]
.Ereignisaktion, um Auftragsstatus an REWE zu melden
[cols="1,2,2"]
|===
| *Einstellung*
| *Option*
| *Auswahl*

| *Ereignis*
| *Auftragsänderung: Statuswechsel*
| *Status* wählen.

| *Filter 1*
| *Auftrag > Auftragstyp*
| *Auftrag*

| *Filter 2*
| *Auftrag > Herkunft*
| *Rewe*

| *Aktion*
| *Plugin*
| *Versandbestätigung an REWE melden*
|===

[IMPORTANT]
.Retourengründe verknüpfen
====
Für Retouren müssen plentymarkets Retourengründe mit von REWE vorgegebenen Retourengründen verknüpft sein. Wenn beispielsweise die Ereignisaktion *Retourenabschluss an REWE melden* ausgelöst wird, muss ein Retourengrund gespeichert sein. Weitere Informationen zur Retourengrund-Verknüpfung findest du im Kapitel <<#1200, Retourengründe verknüpfen>>.
====

[#1600]
== REWE-Lieferzeiten

Die Variantenverfügbarkeiten in plentymarkets werden bei REWE Lieferzeiten zugeordnet. Eine Übersicht zu den Lieferzeiten bei REWE und den entsprechenden Verfügbarkeiten in plentymarkets erhältst du in <<#rewe-verfügbarkeit>>.

[[rewe-verfügbarkeit]]
.REWE-Lieferzeiten
[cols="1,2a"]
|===
| *plentymarkets Verfügbarkeit* | *Lieferzeit bei REWE*
|1 |1-3 Werktage
|2 |ca. 3-6 Werktage
|3 |ca. 6-8 Werktage
|4 |ca. 8-10 Werktage
|5 |ca. 10-15 Werktage
|6 |ca. 15-20 Werktage
|7 |ca. 20-30 Werktage
|8 |ca. 30-40 Werktage
|9 |ca. 40-50 Werktage
|10 |ca. 50-60 Werktage
|===

[IMPORTANT]
.Verfügbarkeit bei Fehlern
====
Wenn beim Zuordnen der Verfügbarkeit ein Fehler auftritt, wird bei REWE die Verfügbarkeit *länger als 3 Monate* angezeigt.
====
