= REWE
:lang: de
include::{includedir}/_header.adoc[]
:author: none
:keywords: Rewe, Marktplatz, rewe.de, Rewe einrichten, Rewe Marktplatz, Multi-Channel, Multichannel, Multi-Channel Rewe, Multichannel Rewe, Multi Channel Rewe
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz REWE in deinem plentymarkets System ein.
:position: 210
:url: maerkte/rewe
:id: VCPKDKC

[IMPORTANT]
.Rewe-Plugin herunterladen
====
Die Schnittstelle zu Rewe wird über ein Plugin integriert. Um das REWE-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/rewe_5901[plentyMarketplace^] herunter.
====

[#100]
== Bei REWE registrieren

Der REWE-Marktplatz ist ein geschlossener Marktplatz. Damit du dich als Händler bei REWE registrieren kannst, ist eine Prüfung durch REWE erforderlich. Sende dazu eine E-Mail an partnersupport@rewe.de und gib folgende Informationen an:

* Name deines Unternehmens
* Website deines Unternehmens bzw. Onlineshop
* Auflistung deines Sortiments (Anzahl SKUs, Kategorien, verpflichtende Kennzeichnung)
* Kontaktinformationen

Für weitere Informationen zur Prüfung und Registrierung kontaktiere REWE unter partnersupport@rewe.de.

Nachdem du dich als Händler registriert hast, erhältst du Zugangsdaten von REWE.


[IMPORTANT]
.Rechte vergeben
====
Achte bei der Erstellung deiner API-Client-Zugangsdaten bei REWE darauf, dass du genügend Rechte vergibst. Wähle die Vorlage *Admin-Client* _oder_ erstelle einen neuen Client und vergib alle verfügbaren Rechte.
====

Nach dem Installieren des REWE-Plugins stehen folgende automatisierte Prozesse bereit:

* täglicher Artikelexport
* stündlicher Bestandsabgleich
* stündlicher Preisabgleich
* viertelstündlicher Auftragsimport

[#200]
== REWE in plentymarkets installieren

Nachdem du das REWE-Plugin im plentyMarketplace gekauft hast, installiere den Marktplatz im Menü *Plugins » Plugin-Übersicht*.

[#300]
=== Authentifizierung durchführen

Nachdem du das REWE-Plugin installiert hast, musst du zunächst eine Authentifizierung durchführen, um den Zugang zur Schnittstelle zu ermöglichen.

[.instruction]
Zugang zur Schnittstelle aktivieren:

. Öffne das Menü *Einrichtung » Märkte » REWE » Konto-Einstellungen*.
. Gib in die Felder *Benutzername*, *Passwort* und *Produktschlüssel* die Zugangsdaten ein, die du von REWE erhalten hast.
. *Speichere* (icon:save[]) die Einstellungen.

[#400]
== REWE in plentymarkets einrichten

Richte den Marktplatz REWE im Menü *Einrichtung » Märkte » Rewe » Grundeinstellungen* ein. Aktiviere den Artikelexport, den Bestands- und Preisabgleich und den Auftragsimport in diesem Menü.

[.instruction]
Automatischen Datenaustausch aktivieren:

. Öffne das Menü *Einrichtung » Märkte » Rewe » Grundeinstellungen*.
. Aktiviere die Einstellungen *Artikelexport*, *Bestands- und Preisabgleich* und *Auftragsimport*, um den automatischen Datenaustausch mit REWE zu aktivieren.
. *Speichere* (icon:save[]) die Einstellungen.

[#500]
== Provision einstellen

Im Menü *Einrichtung » Märkte » REWE » Grundeinstellungen* legst du die Standardprovision fest. Mit der Provision werden provisionsfreie Aufträgsbeträge berechnet.

Provisionsfreie Auftragsbeträge werden folgendermaßen berechnet:

* Verkaufspreis REWE = Verkaufspreis Endkunde * (1 - Umrechnungsfaktor)
* Umrechnungsfaktor = Provision * (1 + Mehrwertsteuersatz)

Für die Berechnung werden die Prozentsätze für Provision und Mehrwertsteuersatz in den entsprechenden Faktor umgerechnet, also durch 100 geteilt. Der Umrechnungsfaktor wird auf die 3. Nachkommastelle gerundet, wie auch bei REWE.

[.instruction]
Provision einstellen:

. Öffne das Menü *Einrichtung » Märkte » REWE » Grundeinstellungen*.
. Gib im Bereich *Provision* eine Zahl für die Provision in Prozent ein.
. *Speichere* (icon:save[]) die Einstellungen. +
→ Die eingestellte Provision ist die Standardprovision für alle Artikel, außer Varianten, für die eine separate Provision eingestellt wurde.

Für Varianten kann mit der Eigenschaft *REWE Provision* eine separate Provision eingestellt werden. Die Eigenschaft *REWE Provision* wird beim Installieren des REWE-Plugins automatisch angelegt. Um eine separate Provision für eine Variante festzulegen, verknüpfe die Variante mit der Eigenschaft *REWE Provision*.

[.instruction]
Separate Provision für Varianten einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Varianten*.
. Öffne die Variante, für die du eine separate Provision einstellen möchtest.
. Wechsele in das Tab *Eigenschaften* der Variante.
. Wähle aus der Dropdown-Liste *Eigenschaften* die Eigenschaft *REWE Provision*.
. Klicke auf *Hinzufügen*. +
→ Die Eigenschaft wird mit der Variante verknüpft.
. Gib in das Eingabefeld *Wert* eine Zahl oder Kommazahl für die Provision in Prozent ein.
. *Speichere* (icon:save[]) die Einstellungen.

[#600]
== Auftragsherkunft aktivieren

Die Auftragsherkunft dient dazu, zu kennzeichnen, über welchen Verkaufskanal ein Auftrag generiert wurde. Außerdem musst du die Auftragsherkunft aktivieren, um Artikel, Merkmale etc. mit REWE verknüpfen zu können. Aktviere die Auftragsherkunft im Menü *Einrichtung » Aufträge » Auftragsherkunft*.

[.instruction]
Auftragsherkunft für REWE aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Aktiviere die Einstellung *Rewe*.
. *Speichere* (icon:save[]) die Einstellungen.

[#700]
== Artikelverfügbarkeit einstellen

Artikel, die du auf dem Marktplatz REWE verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* aktiviert werden und für den Marktplatz verfügbar gemacht werden.

[.instruction]
Artikelverfügbarkeit für REWE einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Option *Aktiv* im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *REWE*.
. Klicke auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[]) die Einstellungen. +
→ Der Artikel ist auf REWE verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

[#800]
== Eigenschaft REWE-Produkttyp verknüpfen

Artikel, die du auf REWE verkaufen möchtest, müssen mit der Eigenschaft *REWE-Produkttyp* verknüpft werden. Diese Eigenschaft wird in deinem plentymarkets System angelegt, sobald du das REWE-Plugin installiert hast.

[.instruction]
Artikel mit Eigenschaft REWE-Produkttyp verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Eigenschaften*.
. Klicke im Bereich *Varianteneigenschaften* auf *Hinzufügen* und wähle die Eigenschaft *REWE-Produkttyp*.
. Wähle einen passenden *Wert* aus der Dropdown-Liste. +
→ Als Werte stehen die REWE-Produkttypen zur Auswahl.
. *Speichere* (icon:save[]) die Einstellungen.

[#900]
== Artikelexport einrichten

Artikeldaten werden über Katalog-Templates zu REWE übertragen. Kataloge erstellst du im Menü *Daten » Kataloge*. Weitere Informationen zu Katalogen findest du auf der Handbuchseite <<daten/daten-exportieren/kataloge-verwalten#, Kataloge verwalten>>.

[TIP]
.Sichtbarkeit des Menüs
====
Das Menü *Daten » Kataloge* ist erst sichtbar, wenn du ein Plugin installierst, das ein Katalog-Template verfügbar macht.
====

Damit du deine Artikel zu REWE exportieren kannst, musst du für die verschiedenen REWE-Produktkategorien Kataloge erstellen. Verknüpfe anschließend im Katalog-Template die von REWE vorgegebenen Felder mit in plentymarkets hinterlegten Artikeldaten. Die Katalog-Vorlagen werden automatisch einmal täglich zu REWE exportiert, wenn du unter *Einrichtung » Märkte » Rewe » Grundeinstellungen* den *Artikelexport* aktiviert hast.

Momentan kannst du mit dem REWE-Plugin Kataloge für die folgenden REWE-Produktkategorien erstellen:

* *Haushalt*
* *Multimedia*
* *Drogerie*
* *Fashion*
* *Freizeit/Sport*
* *Schreibwaren*
* *Spielwaren*
* *Garten*
* *Lebensmittel*


*Hinweise zur Produktkategorie Lebensmittel*:

* Alle Lebensmittelangaben müssen pro 100g angegeben werden.
* Energieangaben müssen in kcal angegeben werden.
* Wenn für das Feld *Nährwertangaben für zubereitete oder nicht zubereitete Lebensmittel* kein Wert verknüpft wurde, wird standardmäßig der Wert *unbehandelt* an REWE übertragen.


[.instruction]
Katalog erstellen:

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf *Katalog erstellen*.
. Gib einen Namen für den Katalog ein.
. Wähle ein Katalog-Template aus der Dropdown-Liste.
. *Speichere* (icon:save[]) die Einstellungen.

Nachdem du einen Katalog erstellt hast, verknüpfst du die Datenfelder des Marktplatzes mit in plentymarkets hinterlegten Artikeldaten. Weitere Informationen zu den plentymarkets Datenquellen, die du zuordnen kannst, findest du im Kapitel <<daten/daten-exportieren/kataloge-verwalten#_datenquellen_zuordnen, Datenquellen zuordnen>>.

[.instruction]
Datenfelder im Katalog verknüpfen:

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet. +
→ Links werden die Datenfelder des Marktplatzes angezeigt. +
*_Tipp_*: Pflichtfelder sind mit Sternchen gekennzeichnet.
. Wähle für die Datenfelder des Marktplatzes eine plentymarkets Datenquelle aus der Dropdown-Liste.
. Um einem Datenfeld eine weitere plentmarkets Datenquelle zuzuordnen, klicke auf *Quelle hinzufügen*. +
→ Eine neue Zeile wird eingeblendet. +
*_Hinweis_*: Auch wenn du einem Datenfeld mehr als eine Datenquelle zuordnest, wird nur ein Wert übertragen. Die Daten werden in der Reihenfolge der Zuordnung geprüft. Wenn also das erste Datenfeld keinen Wert liefert, wird das zweite Datenfeld übertragen usw.
. Nimm alle gewünschten Zuordnungen vor. +
*_Hinweis:_* Alle mit * gekennzeichneten Pflichtfelder müssen mit einer plentymarkets Datenquelle verknüpft werden.
. *Speichere* (icon:save[]) die Einstellungen.


[TIP]
.Pflichtfelder beachten
====
Die Pflichtfelder der verschiedenen Templates sind mit * gekennzeichnet. Verknüpfe mindestens die Pflichtfelder, um sicherzustellen, dass REWE deine Artikel für den Verkauf freigibt.
====

[TIP]
.Werte verknüpfen
====
In den Feldern im unteren Bereich der Katalog-Templates verknüpfst du von REWE vorgegebene Werte mit plentymarktes Datenquellen. Für diese Felder werden die Bennenungen von REWE an den Marktplatz übermittelt.
====


Im Folgenden wird beispielhaft beschrieben, wie du das Pflichtfeld *Produktbeschreibung* mit Artikeldaten aus plentymarkets verknüpfst.

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet.
. Wähle für das REWE-Katalogfeld *Produktbeschreibung* eine plentymarkets Datenquelle aus der Dropdown-Liste, zum Beispiel *Artikeltext > Name 1, Name 2, Name 3*, die auf REWE als Produktbeschreibung angezeigt werden soll.
. Nimm die weiteren Zuordnungen analog vor. Verknüpfe mindestens alle Pflichtfelder.
. *Speichere* (icon:save[]) die Einstellungen.

[TIP]
.SKU verknüpfen
====
Wir empfehlen, das Datenfeld *SKU* mit der plentymarkets Datenquelle *Varianten-ID* zu verknüpfen, da die Varianten-ID der Variante eindeutig zugeordnet ist.
====

[TIP]
.Eigenschaften verwenden
====
Verwende <<artikel/artikel-verwalten#3000, Eigenschaften>>, um Werte für Datenfelder zu übergeben, für die es keine entsprechenden Artikeldaten in plentymarkets gibt, zum Beispiel *Durchmesser*.
====

[#1000]
== Produktgruppen und Varianten bei REWE

Bei REWE wird zwischen *Produktgruppen* und *Varianten* unterschieden.

*Produktgruppen* sind in plentymarkets Artikel, deren Varianten je nach Produkttyp mindestens ein REWE-Gruppenattribut besitzen.
*Varianten* sind in plentymarkets Varianten eines Artikels, die je nach Produkttyp höchstens ein REWE-Variantenattribut besitzen.

Bei REWE-Gruppenattributen können mehrere unterschiedliche Attrbute gesetzt werden, zum Beispiel Farbe _und_ Motiv. Bei REWE-Variantenattributen kann nur ein Variantenattribut gesetzt sein, zum Beispiel _nur_ Größe oder _nur_ Volumen.

Welche REWE-Gruppenattribute und REWE-Variantenattribute für den jeweiligen Produkttyp zur Verfügung stehen, kannst du sehen, wenn du einen Katalog mit Template angelegt hast. Öffne dazu im Katalog-Template die Dropdown-Listen *Attribut für Variantengruppe* und *Attribut für Produktgruppe*.

Artikel in plentymarkets können mehrere REWE-Gruppenattribute besitzen. Bei der Übertragung zu REWE kann nur ein REWE-Gruppenattribut verwendet werden, um Produktgruppen zu bilden. Deswegen muss im Katalog die Option *Attribut für Produktgruppe* so verknüpft werden, dass das erste Attribut immer das Attribut ist, über das du diese Gruppe bilden möchtest.

_Beispiel:_
Wenn ein Artikel, z.B. ein T-Shirt, sich in Farbe und Motiv unterscheidet und das Motiv das REWE-Gruppenattribut sein soll, dann muss das Motiv für die Option *Attribut für Produktgruppe* als erstes verknüpft werden und erst danach die Farbe.

Ein Artikel sollte nicht mit mehr als einem Attribut verknüpft sein, das im Katalog als REWE-Variantenattribut zugeordnet wurde.

[#1100]
== Versanddienstleister verknüpfen

Im Menü *Einrichtung » Märkte » REWE » Versanddienstleister-Verknüpfung* verknüpfst du die in plentymarkets gespeicherten Versanddienstleister mit den Versanddienstleistern von REWE. Wenn du keinen Versanddienstleister verknüpfst, wird automatisch der Versanddienstleister *unknown* zu REWE übertragen.

[.instruction]
Versanddienstleister verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » REWE » Versanddienstleister-Verknüpfung*.
. Wähle aus der Dropdown-Liste den REWE-Versanddienstleister.
. *Speichere* (icon:save[]) die Einstellungen.

[#1200]
== Retourengründe verknüpfen

Im Menü *Einrichtung » Märkte » REWE » Retourengrund-Verknüpfung* verknüpfst du die in plentymarkets gespeicherten Retourengründe mit den Retourengründen von REWE. Wenn du keinen Retourengrund verknüpfst, wird automatisch der Retourengrund *Sonstiges* zu REWE übertragen. Weitere Informationen zu REWE-Retourengründen findest du in der Händlerdokumentation, die du von REWE erhalten hast.

[.instruction]
Retourengründe verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » REWE » Retourengrund-Verknüpfung*.
. Wähle aus der Dropdown-Liste den REWE-Retourengrund.
. *Speichere* (icon:save[]) die Einstellungen.

[#1300]
== Steuerklassen synchronisieren

Wenn die Steuerklassen bei REWE geändert wurden, musst du die Steuerklassen in plentymarkets synchronisieren. Steuerklassen werden im Menü *Einrichtung » Märkte » Rewe » Grundeinstellungen* im Bereich *Steuerklassen* mit REWE synchronisiert.

[.instruction]
Steuerklassen synchronisieren:

. Öffne das Menü *Einrichtung » Märkte » Rewe » Grundeinstellungen*.
. Klicke im Bereich *Steuerklassen* auf *Synchronisieren*. +
→ Die Steuerklassen werden mit REWE abgeglichen.

Unter *Letzte Aktualisierung* wird angezeigt, wann die Steuerklassen zuletzt mit REWE abgeglichen wurden.

[WARNING]
.Steuerklassen vor Wechsel auf REWE-Live-System synchronisieren
====
Bevor deine Artikel bei REWE von der Stage-Testumgebung auf das Live-System wechseln, musst du bei plentymarkets die Steuerklassen erneut synchronisieren, da dein Artikelkatalog sonst nicht übertragen wird. Gib für den Wechsel auf das Live-System zunächst deine Zugangsdaten und den Produktschlüssel für das Live-System ein und synchronisiere danach die Steuerklassen. Nachdem du die Steuerklassen synchronisiert hast, musst du sie in deinen REWE-Katalogen neu verknüpfen.
====

[#1400]
== Marken synchronisieren

Marken werden einmal täglich automatisch mit REWE abgeglichen.

Zudem hast du zusätzlich die Möglichkeit, im Menü *Einrichtung » Märkte » REWE » Grundeinstellungen* Marken manuell mit REWE abzugleichen.

[.instruction]
Marken manuell synchronisieren:

. Öffne das Menü *Einrichtung » Märkte » REWE » Grundeinstellungen*.
. Klicke im Bereich *Marken* auf *synchronisieren*. +
→ Die Marken werden mit REWE abgeglichen.

Unter *Letzte Aktualisierung* wird angezeigt, wann die Marken zuletzt mit REWE abgeglichen wurden.

[#1500]
== Auftragsstatus bei REWE automatisch aktualisieren

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um den Auftragsstatus bei REWE automatisch zu aktualisieren, wenn bestimmte Ereignisse eintreten. Folgende Ereignisaktionen können eingerichtet werden:

* Auftragsposition als nicht vorrätig an REWE melden
* Stornierung durch Käufer an REWE melden
* Stornierung durch Händler an REWE melden
* Versandvorbereitung an REWE melden
* Versandvorbereitungsabschluss an REWE melden
* Retourenanfrage an REWE melden
* Retourenabschluss an REWE melden
* Versandbestätigung an REWE melden
* Paketzustellung an REWE melden

Beispielhaft wird eine Ereignisaktion beschrieben, mit der du die Versandbestätigung an REWE meldest. Richte weitere Ereignisaktionen analog dazu ein.

[.instruction]
Ereignisaktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das Ereignis gemäß <<rewe-ereignisaktion>>.
. *Speichere* (icon:save[]) die Einstellungen.
. Nimm die Einstellungen gemäß <<rewe-ereignisaktion>> vor.
. Aktiviere die Option *Aktiv*.
. *Speichere* (icon:save[]) die Einstellungen.

[[rewe-ereignisaktion]]
.Ereignisaktion, um Auftragsstatus an REWE zu melden
[cols="1,2,2"]
|===
|*Einstellung*
|*Option*
|*Auswahl*

|Ereignis
|Auftragsänderung: Statuswechsel
|*Status* wählen.

|Filter 1
|Auftrag > Auftragstyp
|Auftrag

|Filter 2
|Auftrag > Herkunft
|Rewe

|Aktion
|Plugin
|Versandbestätigung an REWE melden
|===

[IMPORTANT]
.Retourengründe verknüpfen
====
Für Retouren müssen plentymarkets Retourengründe mit von REWE vorgegebenen Retourengründen verknüpft sein. Wenn beispielsweise die Ereignisaktion *Retourenabschluss an REWE melden* ausgelöst wird, muss ein Retourengrund gespeichert sein. Weitere Informationen zur Retourengrund-Verknüpfung findest du im Kapitel <<#1200, Retourengründe verknüpfen>>.
====

[#1600]
== REWE-Lieferzeiten

Die Variantenverfügbarkeiten in plentymarkets werden bei REWE Lieferzeiten zugeordnet. Eine Übersicht zu den Lieferzeiten bei REWE und den entsprechenden Verfügbarkeiten in plentymarkets erhältst du in <<rewe-verfügbarkeit>>.

[[rewe-verfügbarkeit]]
.REWE-Lieferzeiten
[cols="1,2"]
|===
|*plentymarkets Verfügbarkeit* |*Lieferzeit bei REWE*
|1 |1-3 Werktage
|2 |ca. 3-6 Werktage
|3 |ca. 6-8 Werktage
|4 |ca. 8-10 Werktage
|5 |ca. 10-15 Werktage
|6 |ca. 15-20 Werktage
|7 |ca. 20-30 Werktage
|8 |ca. 30-40 Werktage
|9 |ca. 40-50 Werktage
|10 |ca. 50-60 Werktage
|===

[IMPORTANT]
.Verfügbarkeit bei Fehlern
====
Wenn es bei der Zuordnung der Verfügbarkeit einen Fehler gibt, wird die Verfügbarkeit bei REWE mit *länger als 3 Monate* angezeigt.
====
