= Spielwiese
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: spielwiese
:description: Testseite für Formatierungen
:position: 0
:url: maerkte/spielwiese
:id: IAGOJV9

Diese Seite ist nicht Teil des Handbuchs. Aber falls du trotzdem auf dieser Seite gelandet bist: Hallo und herzlich willkommen. Diese Seite ist nur eine Testseite, auf der wir Handbuch-Formatierungen ausprobieren - damit unser Handbuch immer besser wird.

== Ab hier geht es los!

:checklist-log-integration: pass:quotes[*bol.com*]
:checklist-log-reference: pass:quotes[
. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen]*.
. Wechsele in das *Tab: Varianten*.
. Öffne die Variante, die du verknüpfen möchtest.
. Wechsele in das *Tab: Eigenschaften*.
. Wähle im Bereich *Varianteneigenschaften* aus der Dropdown-Liste *Eigenschaften* die Eigenschaft *bol.com-Kategorie* und klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird hinzugefügt.
. Wähle für die Eigenschaft *bol.com-Kategorie* aus der Dropdown-Liste *Wert* die gewünschte Kategorie. +
→ Die Variante wird im zugehörigen Katalog exportiert.
. Speichere (icon:save[set=plenty]) die Einstellungen.
]

include::_textblocks/instructions/checklist-variations.adoc[tag=checklist-check-log]
