= Yatego
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Yatego, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Yatego in deinem plentymarkets System ein.
:position: 240
:url: maerkte/yatego
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Du kannst deine Artikel über plentymarkets auf der Verkaufsplattform link:http://www.yatego.com/[Yatego.com^] anbieten. Yatego bietet Händlern umfangreiche Service-Leistungen mit leistungsstarken Komplettlösungen sowie umfassendem technischen Support.

[#100]
== Bei Yatego registrieren

Registriere dich bei link:http://www.yatego.com/doc,yategoverkaufen[Yatego.com^], um deine Zugangsdaten zu erhalten. Du benötigst diese für die Einstellungen in plentymarkets.

[#200]
== Yatego in plentymarkets einrichten

Nachdem du dich bei Yatego registriert hast, verwende deine Zugangsdaten, um den Marktplatz in plentymarkets einzurichten. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Yatego in plentymarkets einrichten:

. Öffne das Menü *Einrichtung » Märkte » Yatego » Einstellungen*.
. Klappe den Bereich *Einstellungen* auf.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<grundeinstellungen-yatego>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[grundeinstellungen-yatego]]
.Grundeinstellungen des Marktplatzes Yatego
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Benutzername (Yatego Shopname)*
|*Benutzername* für den Login bei Yatego.com eingeben.

|*Passwort*
|*Passwort* für den Login bei Yatego.com eingeben.

|*Größe der Artikelbilder*
|*Artikelbild (Standard)*, *Mittelgroßes Artikelbild* oder *Vorschaubild* wählen.

|*Artikelname*
|*Name 1*, *Name 2* oder *Name 3* wählen. Die Namen werden im Tab *Texte* eines Artikel hinterlegt.

|*Versandkosten*
|*Porto pro Artikel aufsummieren* = plentymarkets überträgt hier pro Artikel die für den Webshop gültigen Versandkosten (Inland). Kauft ein Kunde bei Yatego zwei Artikel, werden dabei die Versandkosten der einzelnen Artikel aufsummiert. Zusätzlich dazu werden die in Yatego hinterlegten Versandkosten zu den von plentymarkets übergebenen Versandkosten addiert. +
*Summieren, aber nur einmal bei gleichen Artikeln* = In diesem Fall überträgt plentymarkets ebenfalls die für den Webshop gültigen Versandkosten (Inland). Bei einem Kauf verschiedener Artikel werden die Portokosten summiert, bei zwei oder mehr gleichen Artikeln wird nur einmal Porto berechnet. Das Porto wird anschließend ebenfalls zu den bei Yatego gespeicherten Versandkosten addiert. +
*Verwende Yatego-Portotabelle anhand des Artikelgewichts* = Wenn du diese Option wählst, übergibt plentymarkets keine Versandkosten an Yatego. Auf Basis des in plentymarkets gespeicherten Gewichts, welches auch an Yatego übergeben wird, errechnet Yatego selbst die Versandkosten.

//|*Mandant für Artikelexport*
//|*Standard-Webshop*, *Mandant (Shop)* oder *ALLE* wählen, je nachdem, welcher Webshop für den Artikelexport verwendet werden soll.

//|*Mandant für Auftragsimport*
//|*Standard-Webshop* oder *Mandant (Shop)* für den Auftragsimport wählen.

|*Sortierung der Varianten*
|*Alphabetisch*, *Aufpreis* oder *Keine Sortierung* wählen.

|*UVP übertragen*
|*Ja* = Wert für UVP übertragen, wenn eine *UVP* für Yatego-Artikel eingegeben ist. +
*Nein* = Keinen Wert für UVP übertragen.

|*Automatischer Upload (täglich)*
|Aktivieren, um Artikeldaten automatisch täglich an Yatego zu übertragen.

|*Ausverkaufte Varianten*
|*Sichtbar* = Ausverkaufte Varianten werden bei Yatego angezeigt. +
*Unsichtbar* = Ausverkaufte Varianten werden nicht angezeigt.

|*Yatego-Merkmale*
|*Nicht exportieren* = Merkmale nicht an Yatego exportieren. +
*In den oberen Bereich der Beschreibung setzen* = Merkmale bei Yatego-Artikeln in den oberen Bereich der Beschreibung setzen. +
*In den unteren Bereich der Beschreibung setzen* =Merkmale bei Yatego-Artikeln in den unteren Bereich der Beschreibung setzen.

|*Freitextfelder 1 bis 20*
|*Nicht exportieren* = Freitextfeld nicht an Yatego exportieren. +
*In den oberen Bereich der Beschreibung setzen* = Text bei Yatego-Artikeln in den oberen Bereich der Beschreibung setzen. +
*In den unteren Bereich der Beschreibung setzen* = Text bei Yatego-Artikeln in den unteren Bereich der Beschreibung setzen. +
*In separate Spalte exportieren* = Merkmal beim Artikelexport in eine separate Spalte der CSV-Datei exportieren. +
*Hinweis:* Diese Funktion wird nur noch für Kunden unterstützt, die bereits die Freitextfeld-Funktionen in den Yatego-Einstellungen nutzen. Neue Kunden sind aufgefordert, die beiden folgenden Optionen zu verwenden.

|*Yatego-Lagerberechtigung*
|*Exakt* oder *Einfach* wählen, wenn Ihre Bestandsverwaltung mit den Werten -1, 0, 1 oder 2 möglich ist.

|*Artikelbeschreibung*
|*Standardbeschreibung*, *Technische Daten* oder *Beide* wählen.

|*Artikelkurzbeschreibung*
|*Vorschautext* oder *Technische Daten* für die Artikelkurzbeschreibung bei Yatego wählen.

|*Lager*
|Eigenes Lager, *Artikel-Hauptlager* oder *Übertrage die Bestandsmenge des Vertriebslagers mit dem aktuell größten Bestand* wählen.

|*Alle Artikelbilder vor dem Import aus dem Yatego-Shop löschen?*
|*Ja* = Alle aktuell in Yatego vorhandenen Artikelbilder beim Importieren von neuen Bildern für diesen Artikel löschen. Fehler beim Bilderimport werden verhindert. Ohne das Löschen der alten Bilder würde Yatego bei gleichem Dateinamen das alte Bild nicht durch das neue Bild ersetzen. +
*Nein* = Artikelbilder vor dem Import nicht löschen.

|*Status für alle Kreditkarte-Aufträge*
|*Status 3* (Warten auf Zahlung) oder *Status 5* (Freigabe Versand) wählen.

|*Alle Kreditkarte-Aufträge mit Status 5 als gebucht setzen*
|Wählen, ob Kreditkarte-Aufträge mit Status 5 als gebucht gesetzt werden sollen oder nicht.

|*Status für alle Sofortüberweisung-Aufträge*
|*Status 3* (Warten auf Zahlung) oder *Status 5* (Freigabe Versand) wählen.

|*Alle Sofortüberweisung-Aufträge mit Status 5 als gebucht setzen*
|Wählen, ob Sofortüberweisung-Aufträge mit Status 5 als gebucht gesetzt werden sollen oder nicht.

|*Status für alle PayPal-Aufträge*
|*Status 3* (Warten auf Zahlung) oder *Status 5* (Freigabe Versand) wählen.

|*Alle PayPal-Aufträge mit Status 5 als gebucht setzen*
|Wählen, ob PayPal-Aufträge mit Status 5 als gebucht gesetzt werden sollen oder nicht.

|*Artikel-URL übertragen*
|Wählen, ob die URL der Artikel übertragen werden soll oder nicht.

|*Alle (max. 5) Bilder aus der ausführlichen Beschreibung als Artikelbilder verwenden*
|Wählen, ob alle Artikelbilder eines Artikels verwendet werden sollen oder nicht. Sie können maximal 5 Bilder verwenden.

|*Webshop-Kategorien übertragen*
|*Alle*, *Nur die Standardkategorie* oder *Nein* wählen. +
Die *Standardkategorie* wird im Tab *Kategorien* am Artikel gewählt. Wenn du die Option *Nur die Standardkategorie* wählst, prüfe die Einstellung der Artikel für Yatego im Tab *Kategorien*. Wenn du dort keine Auswahl getroffen hast, wird die erste Kategorieverknüpfung automatisch als *Standardkategorie* gewählt.

|*Webshop-Kategorieebenen*
|Wählen, welche *Kategorieebenen* übertragen werden sollen. Zur Auswahl stehen 3 aufeinanderfolgende Ebenen. Ebenen müssen für alle Yatego-Artikel eingerichtet und verknüpft sein.
|====

[#250]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit Yatego verknüpfen kannst, muss im Menü *Einrichtung » Aufträge » Auftragsherkunft* die Auftragsherkunft Yatego aktiviert werden.

[.instruction]
Auftragsherkunft für Yatego aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Setze bei *Yatego* ein Häkchen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die du auf Yatego verkaufen möchtest, müssen im Menü <<artikel/artikel-verwalten#180, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Yatego einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Setze ein Häkchen neben der Option *Yatego*.
. Setze ein Häkchen neben der Option *Web-API*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Artikel ist auf Yatego verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

[#350]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#180, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Yatego*.
. Gib die SKU ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die SKU wird gespeichert und angezeigt.

[#400]
== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft Yatego einen Verkaufspreis festzulegen. Dieser Preis wird auf Yatego angezeigt.

[.instruction]
Verkaufspreis für Yatego festlegen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *Yatego*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#500]
== Kategorien verknüpfen

Importiere zunächst die offiziellen Yatego-Kategorien.

[.instruction]
Yatego-Kategorien importieren:

. Öffne das Menü *Einrichtung » Märkte » Yatego » Kategorieverknüpfung*.
. Klicke auf *Yatego-Kategorien aktualisieren*. +
→ Die Yatego-Kategorien stehen dir im Bereich *Kategorieverknüpfung* zur Verfügung.

Verknüpfe deine Webshop-Kategorien mit den Kategorien von Yatego, damit deine Artikel in diesen Yatego-Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » Yatego » Kategorieverknüpfung*.
. Klicke unter *Yatego-Verknüpfung* auf das *Zahnrad*.
. Wähle im Bereich *Offizielle Yatego-Kategorien* eine Kategorie. +
→ (icon:map-signs[]) *_Oder:_* Gib unter *Yatego-Kategorie-ID-Verknüpfung* die Kategorie-ID ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Exportiere anschließend deine Webshop-Kategorien im Yatego-Format.

[.instruction]
Webshop-Kategorien in Yatego-Format exportieren:

. Öffne das Menü *Einrichtung » Märkte » Yatego » Kategorieverknüpfung*.
. Klicke auf *Webshop-Kategorien exportieren*. +
→ Ein Fenster wird geöffnet.
. Klicke auf *OK*, um die CSV-Datei zu speichern.
. Importiere die CSV-Datei bei Yatego. +
→ Die Webshop-Kategorien sind nun bei Yatego verfügbar.

[#600]
== Merkmale verknüpfen

Verknüpfe deine <<artikel/artikel-verwalten#480, Merkmale>> mit den Yatego-Merkmalen. Gehe wie im Folgenden beschrieben vor.

[.instruction]
Merkmale verknüpfen:

. Öffne das Menü *Einrichtung » Artikel » Merkmale*.
. Klappe ein Merkmal auf.
. Aktiviere die Option *Yatego*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#700]
== Artikel automatisch übermitteln

Im Menü *Einrichtung » Märkte » Yatego » Einstellungen* nimmst du den Artikelaustausch mit Yatego vor. Die Funktionen dieses Menüs stehen nur nach Eingabe der Zugangsdaten zur Verfügung. Nutze die Vorschaufunktion, um die Daten vor der Übertragung zu prüfen. Der Import bei Yatego kann unter Umständen sehr lange dauern. plentymarkets hat darauf keinen Einfluss.

Um einen reibungslosen Artikelexport zu Yatego zu gewährleisten, stelle sicher, dass die Zugangsdaten zum Yatego Shop gültig sind und aktuell gehalten werden.

[WARNING]
.*Vollständiger Yatego-Import*
====
plentymarkets unterstützt nur den Vollimport der Artikel aus plentymarkets in Yatego. Das bedeutet, dass alle bestehenden Artikel bei Yatego vor dem Import gelöscht werden. Wenn du bereits Artikel bei Yatego hast, pflege diese Artikel vorher in plentymarkets ein und schalte erst danach den Artikelbestand für Yatego für den Export frei.
====

[.instruction]
Artikel an Yatego übermitteln:

. Öffne das Menü *Einrichtung » Märkte » Yatego » Einstellungen*.
. Klappe das Untermenü *Artikelaustausch yatego.com (FTP)* auf.
. Klicke jeweils auf das *Vorschau-Symbol*, um die Daten zu prüfen, die als CSV-Datei bereitgestellt werden.
. Klicke nach Prüfung der Daten auf *Daten übertragen*, um die Daten an Yatego zu übermitteln.

[#800]
== Aufträge importieren

Aufträge werden direkt aus Yatego übernommen, wenn das plentymarkets System mit SSL-Zertifikat gebucht wurde. Aufträge werden ausschließlich per verschlüsselter Verbindung von Yatego an plentymarkets übertragen. Für die Übertragung ist ein SSL-Zertifikat nötig. Wenn kein SSL-Zertifikat gebucht wurde, musst du das SSL-Zertifikat nachträglich buchen.

[TIP]
.Tipp: SSL-Zertifikat buchen
====
Um ein SSL-Zertifikat zu buchen, öffne das Service-Center in deinem plentymarkets System unter *plentymarkets Logo » Service-Center*. Du kannst das SSL-Zertifikat im Tab *Domain* buchen.
====

////
Liegt ein SSL-Zertifikat vor, müssen im Yatego-Backoffice nur noch einige Einstellungen unter *yatego.com » Bestellungen » Bestellanbindungen* vorgenommen werden und zukünftig eintreffende Aufträge werden in plentymarkets übertragen. Achte darauf, dass die richtige URL inkl. *https://* eingegeben wird (also: *https://www.mein-shop.de/*).

[IMPORTANT]
.Artikelexport weiterer Webshops
====
Wird der Artikelexport für einen weiteren Mandanten (Shop) eingerichtet, sind für den Auftragsimport trotzdem die Zugangsdaten (URL mit Zertifikat und *WebToken* aus den plentymarkets API-Daten) des Hauptsystems zu hinterlegen (WebToken = nicht *plentyToken*). +
Den *WebToken* findest du in plentymarkets im Menü *System » Systemeinstellungen » Einstellungen » API » Daten* unter *WebToken*.
====

[IMPORTANT]
.Versandbestätigung
====
Die Versandbestätigung wird nicht automatisch an Yatego gesendet. Der Auftrag muss manuell direkt bei Yatego bestätigt werden.
====
////

[#900]
== Zahlungsart aktivieren

Aktiviere die <<payment/zahlungsarten-verwalten#, Zahlungsart>> *Yatego Rechnung*, wie im Folgenden beschrieben.

[.instruction]
Zahlungsart Yatego Rechnung aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Setze ein Häkchen bei *Auch inaktive zeigen*.
. Klicke auf den Ordner *DE &gt; Yatego Rechnung*. +
→ Die Einstellungen für die Yatego-Zahlungsart werden angezeigt.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<zahlungsart-yatego>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[zahlungsart-yatego]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
|Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in deinem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standard-Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistiken verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *Einrichtung » CRM » Kundenklassen* aktivierst oder deaktivierst du *erlaubte Zahlungsarten*. +
Weitere Informationen findest du im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#1000]
== API-Log abrufen

Im Menü *Daten » API-Log* findest du eine Historie über Vorgänge, die über die Yatego-Schnittstelle ausgeführt wurden. Folgende Formate stehen dir für Yatego zur Auswahl:

* *Yatego(new)* (Artikelkatalog, Varianten, Attribute)
* *OrdersYatego* (Auftragsimport)
* *Writer_OrdersYatego_Execution* (Export)

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle ein Format aus der Dropdown-Liste *Vorgang*.
. Wähle ggf. ein *Datum*, um nur Einträge eines bestimmten Tages zu erhalten.
. Klicke auf *Suchen*, um die Suche auszuführen. +
→ Die Vorgänge werden angezeigt.
. Klicke in der Spalte *Vorgang* auf den Ordner.  +
→ Das Tab *Yatego* wird geöffnet und Fehlermeldungen des Vorgangs werden angezeigt.

[#1100]
== FAQ

===== Wie übermittelt plentymarkets Artikel ohne Bestandsbeschränkung an Yatego?

[.indented]
Artikel, für die im Tab *Bestand* und dort im Tab *Einstellungen* für die Option *Beschränkung* die Einstellung *keine Beschränkung* ausgewählt wurde, werden ebenfalls an Yatego übermittelt. Für diese Artikel sendet plentymarkets den Wert -1, so dass Yatego erkennt, dass es sich um einen unbeschränkt kaufbaren Artikel handelt.

===== Kann ich Aufträge von Yatego in plentymarkets manuell importieren?

[.indented]
Ja. Wenn eine Yatego-Bestellung manuell von Yatego zu plentymarkets übertragen wird, sendet Yatego keine Artikel-ID bzw. Varianten-ID (attribute_value_set_id). Der Artikel kann nicht automatisch zugeordnet werden und wird mit der Artikel ID -2 importiert (unbekannter Artikel). Nicht zugeordnete Artikel erkennst du im Auftrag an einem *grünen Plus-Zeichen*. Die Zuordnung muss dann manuell erfolgen.

===== Woran erkenne ich, dass der Käufer die Bestellung bereits bezahlt hat?

[.indented]
Yatego sendet keine Transaktions-ID für Zahlungen und auch keine sonstigen Informationen, ob die Bestellung bezahlt wurde oder nicht. Daher gibt es bei den Yatego-Einstellungen für einige Zahlungsarten die Option *Aufträge mit Status 5 als gebucht setzen*. Wenn die Funktion der Zahlungsart gewährleistet, dass die Zahlung bei Buchung erfolgt ist, wähle diese Option.

===== Der Link zum Artikel in der Bestellung funktioniert nicht. Was muss ich tun?

[.indented]
Yatego sendet für die Bestellungen einen Link zu dem Artikel auf Yatego. Meistens funktioniert dieser Link nicht, da Yatego an den Namen des Webshops noch "yatego.com" anhängt. Lösche in dem Link die Ergänzung "yatego.com", dann funktioniert der Link. +
*Beispiel*: http://www.yatego.com/SHOPNAME.yatego.com/p,4fcaaf8c8292c,461e2919becf22_4 +
*Korrekt wäre*: http://www.yatego.com/SHOPNAME/p,4fcaaf8c8292c,461e2919becf22_4

===== Ich habe Yatego in plentymarkets eingerichtet. Warum werden meine Bestellungen nicht übertragen?

[.indented]
Wenn ein Webshop den Yatego-Bestellprozess für plentymarkets zum ersten Mal freischaltet, werden meistens die ersten 2-3 Bestellungen nicht automatisch zu plentymarkets übertragen. Diese Bestellungen müssen dann von dem Yatego-System, in der Bestellansicht bei Yatego, nochmals manuell angestoßen werden.

===== Ich möchte einen Artikel mit Attributen anbieten. Warum hat dieser bei Yatego nicht den korrekten Bestand?

[.indented]
Bei mehr als 999 theoretischen Kombinationsmöglichkeiten für Attribute werden die Lager-Datensätze, die plentymarkets für den Artikel sendet, nicht von Yatego verarbeitet. Daher werden für den Artikel alle möglichen Kombinationen von Varianten aktiviert und auf endlosen Bestand gesetzt (das bedeutet für Yatego, dass kein Lager existiert). Wenn du sehr viele Attribute verwenden musst, kontaktiere Yatego, bevor du die betreffenden Artikel exportierst.

===== Warum werden meine an Yatego übertragenen CSV-Dateien nicht sofort bearbeitet?

[.indented]
Die CSV-Dateien, die täglich zu Yatego übertragen werden, werden dort nicht sofort importiert und bearbeitet, sondern in eine Warteschleife gesetzt. Daher kann der Import und Bearbeitungsprozess mehrere Stunden dauern. Du kannst im Yatego-System prüfen, auf welcher Position du dich in der Warteschleife befindest.
