= Zalando
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: Zalando, Marktplatz, zalando.de, Zalando einrichten, Zalando Marktplatz, Multi-Channel, Multichannel, Multi-Channel Zalando, Multichannel Zalando, multi channel zalando
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Zalando in deinem plentymarkets System ein.
:position: 250
:url: maerkte/zalando
:id: H1AGZUB

Durch das Zalando-Partnerprogramm können Online-Händler und Hersteller Zalando als zusätzlichen Absatzkanal für hochwertige Produkte nutzen und von der großen Markenbekanntheit von Zalando profitieren.

[#100]
== Bei Zalando registrieren

Bei Interesse am link:https://www.zalando.de/partner/[Partnerprogramm^]{nbsp}icon:external-link[] wende dich bitte zunächst direkt an Zalando.

[[ansprechpartner]]
.Ansprechpartner
[cols="1,3"]
|====
|Ansprechpartner |E-Mail-Adresse

| *Zalando-Partnerprogramm-Team*
|link:mailto:partner.programm@zalando.de[partner.programm@zalando.de^]{nbsp}icon:external-link[]
|====

[#200]
== Zalando in plentymarkets einrichten

Wenn die Aufnahme in das Partnerprogramm seitens Zalando abgeschlossen ist, stellt dir Zalando ein Handbuch sowie Hilfestellung bei der Einrichtung der Schnittstelle zur Verfügung. In plentymarkets nimmst du folgende Grundeinstellungen vor.

[.instruction]
Zalando in plentymarkets einrichten:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen gemäß <<#grundeinstellungen-zalando>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[grundeinstellungen-zalando]]
.Grundeinstellungen des Marktplatzes Zalando
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Grundkonfiguration

| *Benutzer*
|API-Benutzer wählen. Das Konto für den API-Benutzer wird bei der Ersteinrichtung erstellt.

| *Preisspalte*
|Preisspalte wählen, die für Zalando-Artikel verwendet wird.

| *Artikelname*
| *Name 1*, *Name 2* oder *Name 3* wählen.

| *Zuordnung Mandant (Shop)*
|Mandant (Shop) wählen.

| *Lagerauswahl*
|Lager wählen. +
*Übertrage die Bestandsmenge des Vertriebslagers mit dem aktuell größten Bestand* = Vertriebslager mit aktuell größtem Bestand des Artikels als Lager wählen. +
*Verwende Hauptlager des Artikels* = Hauptlager des Artikels als Lager wählen. +
*Übertrage die Summe der Bestandsmenge aller Vertriebslager* = Bestände aller Vertriebslager werden addiert und die Summe übertragen.

2+|Erweiterte Optionen

| *Bestandspuffer*
|Bestandspuffer in Stück eingeben.

| *Menge für Artikel ohne Bestandsbindung*
|Menge für Artikel ohne Bestandsbindung eingeben.

| *Grenzwert für Artikel-Upload*
|Ziffer eingeben, um den Grenzwert für den Artikel-Upload in Stück pro Artikel festzulegen.

| *Regelsteuersatz*
| *19 %* oder *7 %* wählen.

| *Ermäßigter Steuersatz*
| *19 %* oder *7 %* wählen.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierten Funktionen bereit:

* Täglicher Artikelexport

[#250]
== Auftragsherkunft aktivieren

:market: Zalando
:referrer: Zalando
:referrer-option: pass:quotes[Option *Zalando*]

include::_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#300]
== Variantenverfügbarkeit einstellen

:market-availability: Zalando
:option-availability: Zalando

include::_textblocks/instructions/variantenverfuegbarkeit.adoc[tags=verfuegbarkeit;web-api;!*]

// Web-API erforderlich!

[#330]
== SKU manuell festlegen

:referrer-sku: Zalando

include::_textblocks/instructions/sku-manuell.adoc[tags=sku-man;!*]

// Marktplatzkonto nicht erforderlich!

[#350]
== Verkaufspreis festlegen

:referrer-price: Zalando

include::_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#1100]
== Varianten vorbereiten

Zalando gibt bestimmte Pflichtangaben vor. Das bedeutet, dass nur Varianten an den Marktplatz exportiert werden können, für die diese Angaben gespeichert sind. Die in <<#zalando-varianten-pflicht>> aufgeführten Angaben müssen an allen Varianten gespeichert sein, die an Zalando exportiert werden sollen.

[[zalando-varianten-pflicht]]
.Pflichtfelder an der Variante
[cols="1,3"]
|====
|Pflichtdaten |Erläuterung

| EAN
a| Für jede Variante muss eine EAN gespeichert sein.

* Im Menü *Einrichtung » Artikel » Barcode* muss eine EAN eingerichtet und mit der Herkunft Zalando verknüpft sein.
* Die EAN muss im Tab *Einstellungen* der Variante im Bereich *Barcode* hinzugefügt und ein Barcode-Code eingegeben werden.

| Technische Daten
a| Für jeden Artikel müssen technische Daten gespeichert sein.

* Im Tab *Texte* des Artikels muss im Feld *Technische Daten* Text gespeichert sein.

| Bilder
a| Für jede Variante muss ein Bild gespeichert sein.

* Im Tab *Bilder* des Artikels muss in der Dropdown-Liste *Verfügbarkeit* die Option *Zalando* aktiviert sein.

| Preis
a| Für jede Variante muss ein Preis gespeichert sein.

* Der Verkaufspreis muss im Menü *Einrichtung » Artikel » Verkaufspreise* für Herkunft die Herkunft Zalando aktiviert sein.
* Der Verkaufspreis muss im Tab *Einstellungen* einer Variante im Bereich *Verkaufspreise* hinzugefügt werden.
* Ein Preis muss für den Verkaufspreis gespeichert sein.
|====

[#400]
== Kategorien verknüpfen

Verknüpfe deine Webshop-Kategorien mit den Kategorien von Zalando, damit deine Artikel in diesen Zalando-Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Kategorieverknüpfung*.
. Wähle unter *Zalando-Kategorie* eine Kategorie.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#500]
== Silhouetten in Merkmale konvertieren

Im Menü *Einrichtung » Märkte » Zalando » Einstellungen » Tab: Silhouetten* konvertierst du Zalando-Silhouetten in Artikel-Merkmale. Silhouetten werden bei der Ersteinrichtung von Zalando übertragen.

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*.
. Wechsele in das Tab *Silhouetten*.
. Wähle die *Gruppen* für die Merkmale, die du konvertieren möchtest.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Merkmale werden im plentymarkets System erstellt.

[#600]
== Zalando-Artikelmerkmale exportieren

Die von dir im Bereich *Gruppen* gespeicherten Silhouetten kannst du exportieren.

[.instruction]
Zalando-Artikelmerkmale exportieren:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*.
. Wechsele in das Tab *Silhouetten*.
. Klicke auf *Zalando Artikel-Merkmale exportieren*. +
→ Eine Datei mit den Parametern der Merkmale wird exportiert.
. Öffne die Datei.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#zalando-merkmale>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[zalando-merkmale]]
.Werte für Zalando-Merkmale
[cols="1,3"]
|====
|Spalte |Erläuterung

| *Gruppenname*
|Namen der Merkmalgruppen.

| *Silhouette*
|Werte aller Silhouetten.

| *Merkmal-ID*
|ID des Webshop-Merkmals eingeben. Die ID des Merkmals findest du im Menü *Einrichtung » Artikel » Merkmale*.

| *Merkmal-Typ*
|Merkmaltyp eingeben. Folgende Eingaben sind möglich: +
*empty* = Wenn das Merkmal nicht verwendet wird, diesen Wert eingeben. Wird das Merkmal benötigt, muss *empty* durch *1* ersetzt werden. +
*text* = Wert in Textform eingeben, z.B. "Rot" für Farbe. +
*int* = Zahl eingeben, z.B. die Absatzhöhe. +
*selection* = Auswahl-ID der Option aus der Dropdown-Liste eingeben. Die Auswahl-ID für Merkmale vom Typ *Auswahl* findest du im Menü *Einrichtung » Artikel » Merkmale* unter *Auswahl-ID*.

| *Pflichtangabe*
|Wenn in einer Zelle der Wert *1* steht, muss das Merkmal übertragen werden. Merkmale können auch in Abhängigkeit bereits gewählter Merkmale den Wert *1* erhalten. Beachte hierzu die von Zalando bereitgestellte Dokumentation.

| *Sprache*
| *de* in die von dir verwendeten Zeilen eingeben. Bisher ist nur die deutsche Sprache verfügbar.
|====

[discrete]
=== Merkmale verknüpfen

Die Zalando-Merkmale verknüpfst du mit den Artikeln in deinem plentymarkets System.

Damit deine Varianten an Zalando übertragen werden können, verknüpfe mindestens die folgenden Pflicht-Merkmale:

* 1. Farbcode
* Altersgruppe(n)
* Geschlecht
* Größenregister
* Hersteller-Code
* Herstellerfarbe
* Jahreszeiten-Code
* Silhouetten-Typ

[.instruction]
Merkmal mit Artikel verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Merkmale*.
. Aktiviere im Bereich *Weitere Merkmale aktivieren* das Merkmal.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Merkmale werden im Bereich *Merkmale* angezeigt.
. *_Optional_:* Nimm weitere Einstellungen vor. Beachte dazu die Erläuterungen in Tabelle 5 im Kapitel <<artikel/artikel-verwalten#80, Merkmale aktivieren>> der Artikel-Handbuchseite.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#700]
== Attribute verknüpfen

Wenn du Attribute in deinem plentymarkets System erstellt hast, verknüpfst du diese Attribute mit Zalando. Im Folgenden wird beschrieben, wie du das Attribut Farbe mit Zalando verknüpfst. Verknüpfe anschließend weitere Attribute auf die gleiche Weise.

[.instruction]
Attribute "Farbe" verknüpfen:

. Öffne das Menü *Einrichtung » Artikel » Attribute*. +
→ Eine Übersicht aller erstellten Attribute wird geöffnet.
. Öffne das Attribut *Farbe*.
. Wechsele in das Tab *Marktplatzvariation*.
. Wähle in der Dropdown-Liste *Marktplatz* die Option *Zalando*. +
→ Die Dropdown-Liste *Zalando* wird angezeigt.
. Wähle in der Dropdown-Liste *Zalando* das Attribut *Farbe*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#800]
== Zahlungsart aktivieren

:paymentmethod: Zalando Payment
:folder: International

include::_textblocks/instructions/zahlungsart_aktivieren.adoc[tags=!real-name;!real-client]

[#850]
== Änderungen am Auftragsstatus

Änderungen am Auftragsstatus werden bei Zalando nicht mit Ereignisaktionen übertragen, sondern automatisch per Schnittstelle von Zalando abgerufen. Die folgenden Status werden übertragen: Versandbestätigung, Stornierung und Retoure.

Die Auftragsstatus Versandbestätigung, Stornierung und Retoure werden an Zalando gesendet, wenn die folgenden Kriterien erfüllt sind:

* *Versandbestätigung*: Der Warenausgang wurde gebucht. Außerdem wurde ein Retourenlabel erzeugt und Paketnummern wurden hinzugefügt.

* *Stornierung*: Der Auftrag wurde in *Status [8.X]* verschoben oder die Menge der Auftragsposition wurde auf *0* geändert.

* *Retoure*: Es wurde eine Retoure in plentymarkets angelegt.

[#900]
== Verarbeitungsberichte abrufen

Im Menü *Einrichtung » Märkte » Zalando » Einstellungen » Tab: Verarbeitungsberichte* stehen dir Verarbeitungsberichte sowie das Export-Log für Zalando zur Ansicht zur Verfügung.

[.instruction]
Verarbeitungsberichte abrufen:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*.
. Wechsele in das Tab *Verarbeitungsberichte*.
. Klicke unter *Aktionen* in der Zeile eines Verabeitungsberichts auf *Datei herunterladen*. +
→ Eine CSV-Datei wird heruntergeladen.

Das Export-Log lädst du im Bereich *Export-Log* herunter.

[#1000]
== API-Log abrufen

Im Menü *Daten » API-Log* findest du eine Historie über Vorgänge, die über die Zalando-Schnittstelle ausgeführt wurden. Das Format *ZalandoController* steht dir für Zalando zur Verfügung.

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle das Format *ZalandoController* aus der Dropdown-Liste *Vorgang*.
. Wähle ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wähle die Anzahl der Ergebnisse pro Seite.
. Klicke auf *Suchen* (icon:search[role="blue"]), um die Ergebnisse anzuzeigen.
