= Zalando
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zalando, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz Zalando in Ihrem plentymarkets System ein.
:position: 250
:url: maerkte/zalando

Durch das Zalando-Partnerprogramm können Online-Händler und Hersteller Zalando als zusätzlichen Absatzkanal für hochwertige Produkte nutzen und von der großen Markenbekanntheit von Zalando profitieren.

[#100]
== Bei Zalando registrieren

Bei Interesse am link:https://www.zalando.de/partner/[Partnerprogramm^] wenden Sie sich bitte zunächst direkt an Zalando.

[[ansprechpartner]]
.Ansprechpartner
[cols="1,3"]
|====
|Ansprechpartner |E-Mail-Adresse

|*Zalando-Partnerprogramm-Team*
|link:mailto:partner.programm@zalando.de[partner.programm@zalando.de^]
|====

[#200]
== Zalando in plentymarkets einrichten

Wenn die Aufnahme in das Partnerprogramm seitens Zalando abgeschlossen ist, stellt Ihnen Zalando ein Handbuch sowie Hilfestellung bei der Einrichtung der Schnittstelle zur Verfügung. In plentymarkets nehmen Sie folgende Grundeinstellungen vor.

[.instruction]
Zalando in plentymarkets einrichten:

.  Öffnen Sie das Menü *System » Systemeinstellungen » Märkte » Zalando » Einstellungen*. +
→ Das Tab *Einstellungen* wird geöffnet.
.  Nehmen Sie die Einstellungen gemäß <<grundeinstellungen-zalando>> vor.
. *Speichern* Sie die Einstellungen.

[[grundeinstellungen-zalando]]
.Grundeinstellungen des Marktplatzes Zalando
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Grundkonfiguration

|*Benutzer*
|API-Benutzer wählen. Das Konto für den API-Benutzer wird bei der Ersteinrichtung erstellt.

|*Preisspalte*
|Preisspalte wählen, die für Zalando-Artikel verwendet wird.

|*Artikelname*
|*Name 1*, *Name 2* oder *Name 3* wählen.

|*Zuordnung Mandant (Shop)*
|Mandant (Shop) wählen.

|*Lagerauswahl*
|Lager wählen. +
*Übertrage die Bestandsmenge des Vertriebslagers mit dem aktuell größten Bestand* = Vertriebslager mit aktuell größtem Bestand des Artikels als Lager wählen. +
*Verwende Hauptlager des Artikels* = Hauptlager des Artikels als Lager wählen. +
*Übertrage die Summe der Bestandsmenge aller Vertriebslager* = Bestände aller Vertriebslager werden addiert und die Summe übertragen.

2+|Erweiterte Optionen

|*EAN*
|*EAN*, *EAN 2*, *EAN 3* oder *EAN 4* wählen.

|*Bestandspuffer*
|Bestandspuffer in Stück eingeben.

|*Menge für Artikel ohne Bestandsbindung*
|Menge für Artikel ohne Bestandsbindung eingeben.

|*Grenzwert für Artikel-Upload*
|Ziffer eingeben, um den Grenzwert für den Artikel-Upload in Stück pro Artikel festzulegen.

|*Regelsteuersatz*
|*19 %* oder *7 %* wählen.

|*Ermäßigter Steuersatz*
|*19 %* oder *7 %* wählen.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierten Funktionen bereit:

* Täglicher Artikelexport

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit Zalando verknüpfen können, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft Zalando aktiviert werden.

[.instruction]
Auftragsherkunft für Zalando aktivieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setzen Sie bei *Zalando* ein Häkchen.
. *Speichern* Sie die Einstellungen.

[#300]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf Zalando verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#180, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Zalando einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Setzen Sie ein Häkchen neben der Option *Zalando*.
. Setzen Sie ein Häkchen neben der Option *Web-API*.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen. +
→ Der Artikel ist auf Zalando verfügbar.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

[#330]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#230, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügen Sie, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechseln Sie in das Tab *Verfügbarkeit*.
.  Klicken Sie im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
.  Wählen Sie die Herkunft *Zalando*.
.  Geben Sie die SKU ein.
.  Klicken Sie auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#350]
== Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für die Auftragsherkunft Zalando einen Verkaufspreis festzulegen. Dieser Preis wird auf Zalando angezeigt.

[.instruction]
Verkaufspreis für Zalando festlegen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setzen Sie ein Häkchen bei der Herkunft *Zalando*.
. *Speichern* Sie die Einstellungen.

[#400]
== Kategorien verknüpfen

Verknüpfen Sie Ihre Webshop-Kategorien mit den Kategorien von Zalando, damit Ihre Artikel in diesen Zalando-Kategorien angezeigt werden. Weitere Artikel der verknüpften Kategorien werden dann automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Märkte » Zalando » Kategorieverknüpfung*.
. Wählen Sie unter *Zalando-Kategorie* eine Kategorie.
. *Speichern* Sie die Einstellungen.

[#500]
== Silhouetten in Merkmale konvertieren

Im Menü *System » Systemeinstellungen » Märkte » Zalando » Einstellungen » Tab: Silhouetten* konvertieren Sie Zalando-Silhouetten in Artikel-Merkmale. Silhouetten werden bei der Ersteinrichtung von Zalando übertragen.

. Öffnen Sie das Menü *System » Systemeinstellungen » Märkte » Zalando » Einstellungen*.
. Wechseln Sie in das Tab *Silhouetten*.
. Wählen Sie die *Gruppen* für die Merkmale, die Sie konvertieren möchten.
. *Speichern* Sie die Einstellungen. +
→ Die Merkmale werden im plentymarkets System erstellt.

[#600]
== Zalando-Artikelmerkmale exportieren

Die von Ihnen im Bereich *Gruppen* gespeicherten Silhouetten können Sie exportieren und für den dynamischen Datenimport verwenden.

[.instruction]
Zalando-Artikelmerkmale exportieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Märkte » Zalando » Einstellungen*.
. Wechseln Sie in das Tab *Silhouetten*.
. Klicken Sie auf *Zalando Artikel-Merkmale exportieren*. +
→ Eine Datei mit den Parametern der Merkmale wird exportiert.
. Öffnen Sie die Datei.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<zalando-merkmale>>.
. *Speichern* Sie die Einstellungen.

[[zalando-merkmale]]
.Werte für Zalando-Merkmale
[cols="1,3"]
|====
|Spalte |Erläuterung

|*Gruppenname*
|Namen der Merkmalgruppen.

|*Silhouette*
|Werte aller Silhouetten.

|*Merkmal-ID*
|ID des Webshop-Merkmals eingeben. Die ID des Merkmals finden Sie im Menü *System » Systemeinstellungen » Artikel » Merkmale*.

|*Merkmal-Typ*
|Merkmaltyp eingeben. Folgende Eingaben sind möglich: +
*empty* = Wenn das Merkmal nicht verwendet wird, diesen Wert eingeben. Wird das Merkmal benötigt, muss *empty* durch *1* ersetzt werden. +
*text* = Wert in Textform eingeben, z.B. "Rot" für Farbe. +
*int* = Zahl eingeben, z.B. die Absatzhöhe. +
*selection* = Auswahl-ID der Option aus der Dropdown-Liste eingeben. Die Auswahl-ID für Merkmale vom Typ *Auswahl* finden Sie im Menü *System » Systemeinstellungen » Artikel » Merkmale* unter *Auswahl-ID*.

|*Pflichtangabe*
|Wenn in einer Zelle der Wert *1* steht, muss das Merkmal übertragen werden. Merkmale können auch in Abhängigkeit bereits gewählter Merkmale den Wert *1* erhalten. Beachten Sie hierzu die von Zalando bereitgestellte Dokumentation.

|*Sprache*
|*de* in die von Ihnen verwendeten Zeilen eingeben. Bisher ist nur die deutsche Sprache verfügbar.
|====

Die exportierten Zalando-Merkmale können Sie mittels <<daten/export-import/datenformate/_itemproperties#, Datenformat>> über den *dynamischen Import* mit den Artikeln in Ihrem plentymarkets System verknüpfen.

[#700]
== Attribute verknüpfen

Wenn Sie Attribute in Ihrem plentymarkets System erstellt haben, verknüpfen Sie diese Attribute mit Zalando. Im Folgenden wird beschrieben, wie Sie das Attribut Farbe mit Zalando verknüpfen. Verknüpfen Sie anschließend weitere Attribut auf die gleiche Weise.

[.instruction]
Attribute "Farbe" verknüpfen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Artikel » Attribute*. +
→ Eine Übersicht aller erstellten Attribute wird geöffnet.
. Klappen Sie das Attribut *Farbe* auf.
. Wechseln Sie in das Tab *Marktplatzvariation*.
. Wählen Sie in der Dropdown-Liste *Marktplatz* die Option *Zalando*. +
→ Die Dropdown-Liste *Zalando* wird angezeigt.
. Wählen Sie in der Dropdown-Liste *Zalando* das Attribut *Farbe*.
. *Speichern* Sie die Einstellungen.

[#800]
== Zahlungsart aktivieren

Aktivieren Sie die <<payment/zahlungsarten-verwalten#, Zahlungsart>> *Zalando Payment*, wie im Folgenden beschrieben.

[.instruction]
bol.com-Zahlungsarten aktivieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
. Klicken Sie auf *Zalando Payment*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<einstellungen-zahlungsart>>.
. Setzen Sie ein Häkchen bei der Option *Aktiv*.
. *Speichern* Sie die Einstellungen.

[[einstellungen-zahlungsart]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit haben Sie die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
|Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
|Kein Lieferland wählen. +
Sie können die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben.  +
Weitere Informationen finden Sie auf der Handbuchseite <<basics/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten finden Sie auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » Systemeinstellungen » CRM » Kundenklassen* aktivieren oder deaktivieren Sie *erlaubte Zahlungsarten*. +
Weitere Informationen finden Sie im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen finden Sie auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#900]
== Verarbeitungsberichte abrufen

Im Menü *System » Systemeinstellungen » Märkte » Zalando » Einstellungen » Tab: Verarbeitungsberichte* stehen Ihnen Verarbeitungsberichte sowie das Export-Log für Zalando zur Ansicht zur Verfügung.

[.instruction]
Verarbeitungsberichte abrufen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Märkte » Zalando » Einstellungen*.
. Wechseln Sie in das Tab *Verarbeitungsberichte*.
. Klicken Sie unter *Aktionen* in der Zeile eines Verabeitungsberichts auf *Datei herunterladen*. +
→ Eine CSV-Datei wird heruntergeladen.

Das Export-Log laden Sie im Bereich *Export-Log* herunter.

[#1000]
== API-Log abrufen

Im Menü *Daten » API-Log* finden Sie eine Historie über Vorgänge, die über die Zalando-Schnittstelle ausgeführt wurden. Das Format *ZalandoController* steht Ihnen für Zalando zur Verfügung.

[.instruction]
API-Log abrufen:

.  Öffnen Sie das Menü *Daten » API-Log » Tab: API-Log*.
.  Wählen Sie das Format *ZalandoController* aus der Dropdown-Liste *Vorgang*.
.  Wählen Sie ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
.  Wählen Sie die Anzahl der Ergebnisse pro Seite.
.  Klicken Sie auf *Suchen*, um die Ergebnisse anzuzeigen.
