= Zalando
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: Zalando, Marktplatz, zalando.de, Zalando einrichten, Zalando Marktplatz, Multi-Channel, Multichannel, Multi-Channel Zalando, Multichannel Zalando, multi channel zalando
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Zalando in deinem plentymarkets System ein.
:position: 250
:url: maerkte/zalando
:id: H1AGZUB

Durch das Zalando-Partnerprogramm können Online-Händler:innen und Hersteller:innen Zalando als zusätzlichen Absatzkanal für hochwertige Produkte nutzen und von der großen Markenbekanntheit von Zalando profitieren.

Die Anbindung des Marktplatzes stellt die folgenden automatisierten Funktionen bereit:

* Täglicher Artikelexport

[#100]
== Bei Zalando registrieren

Du möchtest am link:https://www.zalando.de/partner/[Partnerprogramm von Zalando^]{nbsp}icon:external-link[] teilnehmen? Dann wende dich zunächst direkt an Zalando.

[[ansprechpartner]]
.Kontakt
[cols="1,3"]
|====
|Kontakt |E-Mail-Adresse

| *Zalando-Partnerprogramm-Team*
|link:mailto:partner.programm@zalando.de[partner.programm@zalando.de^]{nbsp}icon:external-link[]
|====

[#200]
== Zalando in plentymarkets einrichten

Nachdem Zalando dich als Partner:in in das Programm aufgenommen hat, stellt dir Zalando ein Handbuch und Hilfestellung beim Einrichten der Schnittstelle zur Verfügung. In plentymarkets nimmst du die unten beschriebenen Grundeinstellungen vor.

[.instruction]
Zalando in plentymarkets einrichten:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen gemäß <<#grundeinstellungen-zalando>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[grundeinstellungen-zalando]]
.Grundeinstellungen des Marktplatzes Zalando
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Grundkonfiguration

| *Benutzer*
|API-Benutzerkonto wählen. Das API-Benutzerkonto wird bei der Ersteinrichtung deines plentymarkets Systems erstellt.

| *Artikelname*
| *Name 1*, *Name 2* oder *Name 3* wählen. Der gewählte Name wird zu Zalando exportiert.

| *Zuordnung Mandant (Shop)*
|Mandant (Shop) wählen. Zalando-Aufträge werden diesem Mandanten zugeordnet. Außerdem präsentierst du dich mit diesem Mandanten auf dem Marktplatz Zalando.

| *Lagerauswahl*
a|Nach welcher Logik soll Zalando-Aufträgen ein Lager zugewiesen werden?

* *Übertrage die Bestandsmenge des Vertriebslagers mit dem aktuell größten Bestand* = Das Vertriebslager mit dem aktuell größtem Bestand der Variante als Lager wählen. +
* *Verwende Hauptlager des Artikels* = Das Hauptlager des Artikels als Lager wählen. +
* *Übertrage die Summe der Bestandsmenge aller Vertriebslager* = Die Bestände aller Vertriebslager werden addiert und die Summe an Zalando exportiert.

2+|Erweiterte Optionen

| *Bestandspuffer*
|Bestandspuffer in Stück eingeben. Der Bestand, der an Zalando exportiert wird, wird um den eingegebenen Wert reduziert.

| *Menge für Artikel ohne Bestandsbindung*
|Menge eingeben, die für Varianten ohne Bestandsbindung bei Zalando als Bestand geführt werden soll. Die eingegebene Menge wird für alle Varianten ohne Bestandsbindung an Zalando exportiert. Der tatsächliche Bestand wird also nicht berücksichtigt.

| *Grenzwert für Artikel-Upload*
|Zahl eingeben, um einen Grenzwert für den Export in Stück pro Variante festzulegen. Der Grenzwert definiert den maximalen Bestand, der pro Variante übermittelt wird. +
*_Beispiel:_* Die Variante hat einen Bestand von 20, aber du hast den Grenzwert 10 festgelegt. plentymarkets übermittelt dann einen Bestand von 10 an Zalando.

| *Regelsteuersatz*
| *19 %* oder *7 %* wählen.

| *Ermäßigter Steuersatz*
| *19 %* oder *7 %* wählen.
|====

[#250]
== Auftragsherkunft aktivieren

:market: Zalando
:referrer: Zalando
:referrer-option: pass:quotes[Option *Zalando*]

include::_textblocks/instructions/auftragsherkunft-aktivieren.adoc[]

[#300]
== Variantenverfügbarkeit einstellen

:market-availability: Zalando
:option-availability: Zalando
:web-api:

include::_textblocks/instructions/variantenverfuegbarkeit.adoc[]

// Web-API erforderlich!

[#330]
== SKU manuell festlegen

:referrer-sku: Zalando

include::_textblocks/instructions/sku-manuell.adoc[]

// Marktplatzkonto nicht erforderlich!

[#350]
== Verkaufspreis festlegen

:referrer-price: Zalando

include::_textblocks/instructions/verkaufspreis-festlegen.adoc[]

[#1100]
== Varianten vorbereiten

Zalando gibt bestimmte Pflichtangaben vor. Das bedeutet, dass nur Varianten an den Marktplatz exportiert werden können, für die diese Angaben gespeichert sind. Die in <<#zalando-varianten-pflicht>> aufgeführten Angaben müssen an allen Varianten gespeichert sein, die an Zalando exportiert werden sollen.

[[zalando-varianten-pflicht]]
.Pflichtfelder an der Variante
[cols="1,3"]
|====
|Pflichtdaten |Erläuterung

| EAN
a| Für jede Variante muss eine EAN gespeichert sein.

* Im Menü *Einrichtung » Artikel » Barcode* muss eine EAN eingerichtet und mit der Herkunft Zalando verknüpft sein.
* Die EAN muss im Tab *Einstellungen* der Variante im Bereich *Barcode* hinzugefügt und ein Barcode-Code eingegeben werden.

| Technische Daten
a| Für jeden Artikel müssen technische Daten gespeichert sein.

* Im Tab *Texte* des Artikels muss im Feld *Technische Daten* Text gespeichert sein.

| Bilder
a| Für jede Variante muss ein Bild gespeichert sein.

* Im Tab *Bilder* des Artikels muss in der Dropdown-Liste *Verfügbarkeit* die Option *Zalando* aktiviert sein.

| Preis
a| Für jede Variante muss ein Preis gespeichert sein.

* Der Verkaufspreis muss im Menü *Einrichtung » Artikel » Verkaufspreise* für Herkunft die Herkunft Zalando aktiviert sein.
* Der Verkaufspreis muss im Tab *Einstellungen* einer Variante im Bereich *Verkaufspreise* hinzugefügt werden.
* Ein Preis muss für den Verkaufspreis gespeichert sein.
|====

[#400]
== Kategorien verknüpfen

Verknüpfe deine Webshop-Kategorien mit den Kategorien von Zalando, damit deine Artikel in diesen Zalando-Kategorien angezeigt werden.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Kategorieverknüpfung*. +
→ Eine Liste deiner Kategorien wird angezeigt. +
→ In der Spalte *Zalando-Kategorie* kannst du jeder Kategorie eine Zalando-Kategorie zuordnen.
. Wähle in der Spalte *Zalando-Kategorie* eine Zalando-Kategorie aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Kategorie wird mit der gewählten Zalando-Kategorie verknüpft. +
→ Neue Artikel, die du für die plentymarkets Kategorie erstellst, werden automatisch auch der Zalando-Kategorie zugewiesen.

[#500]
== Silhouetten in Merkmale konvertieren

Silhouetten sind Artikeltypen, mit denen Zalando Produkte gruppiert. Beispiele für Silhouetten sind "Röcke", "Kleider", "Hosen". Im Menü *Einrichtung » Märkte » Zalando » Einstellungen » Tab: Silhouetten* konvertierst du Zalando-Silhouetten in Artikelmerkmale. Silhouetten werden bei der Ersteinrichtung von Zalando in plentymarkets importiert.

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*.
. Wechsele in das Tab *Silhouetten*.
. Wähle die *Gruppen* für die Merkmale, die du konvertieren möchtest.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Merkmale werden im plentymarkets System erstellt.

[#600]
== Merkmale mit Artikeln verknüpfen

Verknüpfe nun die Zalando-Merkmale mit den Artikeln, die du auf Zalando verkaufen möchtest.

Verknüpfe mindestens die folgenden Pflichtmerkmale, damit deine Varianten an Zalando übertragen werden können:

* 1. Farbcode
* Altersgruppe(n)
* Geschlecht
* Größenregister
* Hersteller-Code
* Herstellerfarbe
* Jahreszeiten-Code
* Silhouetten-Typ

[.collapseBox]
.*_Tipp:_* Referenzdatei mit Zalando-Artikelmerkmale exportieren
--
Wenn du die Zalando-Silhouetten in Merkmale konvertierst werden mehrere hundert Merkmale in plentymarkets erstellt. Um dir die Arbeit mit diesen Merkmalen zu erleichtern, kannst du die Merkmale exportieren. So hast du schnellen Zugriff auf die IDs der Zalando-Merkmale, um die Merkmale zum Beispiel <<daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-merkmalverknuepfung#import_merkmalverknüpfungen, per Import>> mit deinen Artikeln zu verknüpfen.

[.instruction]
Zalando-Artikelmerkmale exportieren:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*.
. Wechsele in das Tab *Silhouetten*.
. Klicke auf *Zalando Artikel-Merkmale exportieren*. +
→ Eine Datei mit Informationen zu den Zalando-Merkmalen wird exportiert.
. Speichere die Datei auf deinem Rechner.
*_Tipp:_* <<#zalando-merkmale>> erläutert die Spalten der Datei. Weitere Informationen zu Merkmalen findest du auf der Handbuchseite <<artikel/einstellungen/eigenschaften#100, Merkmale und Eigenschaften>>.

[[zalando-merkmale]]
.Zalando-Merkmale
[cols="1,3"]
|====
|Spalte |Erläuterung

| *Gruppenname*
|Namen der Merkmalgruppen

| *Silhouette*
|Werte aller Silhouetten

| *Merkmal-ID*
|IDs der Merkmale, siehe auch *Einrichtung » Artikel » Merkmale*

| *Merkmal-Typ*
a|Merkmaltyp

* *empty* = Kein Typ +
* *text* = Text +
* *int* = Ganze Zahl +
* *selection* = Auswahl-ID

| *Pflichtangabe*
a|
*0* = Das Merkmal ist optional.
*1* = Das Merkmal muss übertragen werden. Artikel, die nicht mit diesem Merkmal verknüpft sind, können nicht zu Zalando exportiert werden. +
*_Hinweis:_* Merkmale können auch in Abhängigkeit bereits gewählter Merkmale den Wert *1* erhalten. Beachte hierzu die von Zalando bereitgestellte Dokumentation.

| *Sprache*
| Die <<daten/interne-IDs#10, Sprache>> des Merkmals. Aktuell ist nur die deutsche Sprache verfügbar.
|====
--

[.instruction]
Merkmal mit Artikel verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Merkmale*.
. Aktiviere im Bereich *Weitere Merkmale aktivieren* das Merkmal.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Merkmale werden im Bereich *Merkmale* angezeigt.
. *_Optional:_* Nimm weitere Einstellungen vor. Beachte dazu die Erläuterungen zu den <<artikel/artikel-verwalten#80, Merkmalen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#700]
== Attribute verknüpfen

Wenn du Attribute in deinem plentymarkets System erstellt hast, musst du diese Attribute mit Zalando verknüpfen. Im Folgenden wird beschrieben, wie du das Attribut Farbe mit Zalando verknüpfst. Verknüpfe anschließend weitere Attribute auf die gleiche Weise.

[.instruction]
Attribute "Farbe" verknüpfen:

. Öffne das Menü *Einrichtung » Artikel » Attribute*. +
→ Eine Liste der Attribute wird angezeigt.
. Klicke auf das Attribut *Farbe*.
. Wechsele in das Tab *Attributverknüpfung*.
. Klicke in der Marktplatzliste auf *Zalando*.
. Wähle aus der Dropdown-Liste *Kategorie* die Option *Farbe*.
. Wähle für jeden Attributwert aus der Dropdown-Liste *Marktplatz-Attribute* einen Wert. +
*_Beispiel:_* Wähle für die Farbe Lila aus der ersten Dropdown-Liste *dark purple* und aus der zweiten Dropdown-Liste *Lila*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#800]
== Zahlungsart aktivieren

:paymentmethod: Zalando Payment
:folder: International

include::_textblocks/instructions/zahlungsart_aktivieren.adoc[]

[#1100]
== Zalando-Konto aktivieren

Nachdem du Zalando eingerichtet hast, aktivierst du dein Zalando-Konto im Assistenten *Kontoeinstellungen - Zalando* im Menü *Einrichtung » Assistenten » Omni-Channel*.

[.collapseBox]
.Vorgehen bei *Dieses Konto kann nicht aktiviert werden.*
--
Der Datenaustausch mit Zalando ist nicht aktiv. Um die zDirect-API-Schnittstelle von Zalando zu aktivieren, muss dein Zalando-Konto mit dem plentymarkets Entwicklungskonto verknüpft werden. Diese Verknüpfung passiert im Verlauf der Integration automatisch. Allerdings muss plentymarkets in einem zusätzlichen Schritt Zugangsdaten für die API generieren und diese Zugangsdaten in deinem System hinterlegen. Diese Zugangsdaten dürfen nicht von dir einsehbar sein. Deshalb kann plentymarkets dir die Zugangsdaten nicht bereitstellen. link:https://forum.plentymarkets.com/t/sammelthema-aktivierung-neuer-zalando-konten/600409[Melde dich in diesem Forum-Thread, um die Freischaltung deines Kontos zu erbitten.]
Gib in deinem Foren-Post die folgenden Informationen an:

    ** Den Firmen-/ Markennamen, unter dem Du bei Zalando registriert bist
    ** Deine Plenty-ID
    ** Die ID des Zalando-Kontos (accountId) in plentymarkets, das für die Zalando-Schnittstelle freigeschaltet werden soll +
        *_Hinweis:_* Pro Händler:innenkonto bei Zalando kann nur ein Konto bei plentymarkets verknüpft werden.
--

[.instruction]
Zalando-Konto aktivieren:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Kontoeinstellungen - Zalando*.
. Navigiere zum Schritt *Konto-Aktivierung*.
. Aktiviere die Option *Benutzerkonto aktivieren*.
. Schließe den Assistenten wie gewohnt ab. +
→ Die Kontoeinstellungen werden gespeichert. +
→ Der Datenaustausch mit Zalando wird aktiviert.

[#850]
== Änderungen am Auftragsstatus

Änderungen am Auftragsstatus werden Zalando nicht mit Ereignisaktionen mitgeteilt. Stattdessen ruft Zalando den Auftragsstatus automatisch per Schnittstelle ab. Die Auftragsstatus *Versandbestätigung*, *Stornierung* und *Retoure* werden an Zalando gesendet, wenn die in <<#tabelle-zalando-auftragsstatus>> gezeigten Kriterien erfüllt sind:

[[tabelle-zalando-auftragsstatus]]
.Kriterien für Auftragsstatus
[cols="1,3"]
|====
|Auftragsstatus |Kriterien

| *Versandbestätigung*
|Der Warenausgang wurde gebucht. Außerdem wurde ein Retourenlabel erzeugt und Paketnummern wurden hinzugefügt.

| *Stornierung*
|Der Auftrag wurde in *Status [8.X]* verschoben oder die Menge der Auftragsposition wurde auf *0* geändert.

| *Retoure*
|In plentymarkets wurde eine Retoure erstellt.
|====


[#900]
== Berichte abrufen

Im Menü *Einrichtung » Märkte » Zalando » Einstellungen » Tab: Verarbeitungsberichte* kannst du die folgenden Berichte für Zalando herunterladen:

[cols="1,3"]
|====
|Bericht |Erläuterung

| *Export-Log*
a| Das Export-Log enthält Log-Einträge für Varianten, die nicht zu Zalando exportiert werden konnten. Der Bericht wird einmal pro Nacht automatisch generiert. +
<<#905, So rufst du das Export-Log ab>>

| *Produkt-Status-Berichte*
a| Die Produkt-Status-Berichte werden von Zalando generiert. Diese Berichte enthalten deshalb nur Informationen zu Varianten, die erfolgreich zu Zalando exportiert wurden.

* *_ProductErrorReport.csv_*: Enthält Varianten, die seit dem letzten Export nicht auf Zalando verkauft werden können. Der Bericht wird einmal pro Nacht automatisch generiert.
* *_ProductLiveReport.csv_*: Enthält Varianten, die seit dem letzten Export auf Zalando verkauft werden können sowie Bestand und Preis jeder Variante auf den Zalando-Channels (DE, FR usw.) zu dem Zeitpunkt, zu dem die Datei generiert wurde. Der Bericht wird einmal pro Nacht automatisch generiert.

<<#910, So rufst du Produkt-Status-Berichte ab>>
|====

[#905]
=== Export-Log abrufen

Das Export-Log enthält plentymarkets Log-Einträge für Artikel, die nicht zu Zalando exportiert werden konnten.

[.instruction]
Export-Log abrufen:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*.
. Wechsele in das Tab *Verarbeitungsberichte*.
. Klicke im Bereich *Export-Log* auf *Datei herunterladen* (icon:eye[role="blue"]). +
→ Die CSV-Datei wird generiert.
. Speichere die CSV-Datei auf deinem Rechner.

[#910]
=== Produkt-Status-Bericht abrufen

Produkt-Status-Berichte enthalten Informationen zu den Artikeln, die zu Zalando exportiert wurden. Diese Berichte werden von Zalando generiert. Deshalb enthalten die Berichte nur Informationen zu Varianten, die erfolgreich zu Zalando exportiert wurden. Folgende Berichte sind verfügbar:

* *_ProductErrorReport.csv_*: Enthält Varianten, die seit dem letzten Export nicht auf Zalando verkauft werden können. Der Bericht enthält außerdem die ersten fünf Fehlercodes und eine Fehlerbeschreibung. Der Bericht wird einmal pro Nacht automatisch generiert. Wenn du neuere Daten benötigst, klicke vor dem Herunterladen auf *Datei aktualisieren* (icon:cog[]), um aktuelle Daten bei Zalando abzurufen.
* *_ProductLiveReport.csv_*: Enthält Varianten, die seit dem letzten Export auf Zalando verkauft werden können. Der Bericht enthält außerdem Informationen zum Bestand und Preis jeder Variante auf den Zalando-Channels (DE, FR usw.) zu dem Zeitpunkt, zu dem die Datei generiert wurde. Der Bericht wird einmal pro Nacht automatisch generiert. Wenn du neuere Daten benötigst, klicke vor dem Herunterladen auf *Datei aktualisieren* (icon:cog[]), um aktuelle Daten bei Zalando abzurufen.

Produkt-Status-Berichte sind nur verfügbar, wenn im Assistenten *Kontoeinstellungen - Zalando* die Option *Artikelstatusberichte generieren* aktiviert wurde.

[.collapseBox]
.Artikelstatusberichte aktivieren
--
So aktivierst du die Artikelstatusberichte:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Kontoeinstellungen - Zalando*.
. Aktiviere im Schritt *Artikelstatusbericht* die Option *Artikelstatusberichte generieren*.
. Schließe den Assistenten wie gewohnt ab. +
→ Die ersten Berichte werden in der folgenden Nacht generiert.
--

[.instruction]
Produkt-Status-Bericht abrufen:

. Öffne das Menü *Einrichtung » Märkte » Zalando » Einstellungen*.
. Wechsele in das Tab *Verarbeitungsberichte*. +
→ Im Bereich *Produkt-Status-Berichte - Account ID* sind die folgenden Dateien verfügbar:

  * *_ProductErrorReport.csv_* enthält die Varianten, die seit dem letzten Export nicht auf Zalando verkauft werden können.
  * *_ProductLiveReport.csv_* enthält die Varianten, die seit dem letzten Export auf Zalando verkauft werden können.

. *_Optional:_* Standardmäßig wird die Datei einmal pro Nacht aktualisiert. Klicke im Bereich *Produkt-Status-Berichte - Account ID* auf *Datei aktualisieren* (icon:cog[]), um vor dem Herunterladen aktuelle Daten bei Zalando abzurufen.
. Klicke im Bereich *Produkt-Status-Berichte - Account ID* in der Zeile eines Verarbeitungsberichts auf *Datei herunterladen* (icon:eye[role="blue"]). +
→ Die CSV-Datei wird generiert.
. Speichere die CSV-Datei auf deinem Rechner.

[#1000]
== API-Log abrufen

Im Menü *Daten » API-Log* findest du eine Historie über Vorgänge, die über die Zalando-Schnittstelle ausgeführt wurden. Für Zalando steht dir das Format *ZalandoController* zur Verfügung.

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle das Format *ZalandoController* aus der Dropdown-Liste *Vorgang*.
. *_Optional:_* Wähle ein Datum, um nur Einträge eines bestimmten Tags anzuzeigen.
. Wähle die Anzahl der Ergebnisse pro Seite.
. Klicke auf *Suchen* (icon:search[role="blue"]).
→ Die Ergebnisse werden angezeigt.

////
== Kontoeinstellungen im Assistenten vornehmen

Mit dem Assistenten *Kontoeinstellungen - Zalando* im Menü *Einrichtung » Assistenten » Omni-Channel* richtest du dein Zalando-Konto schnell und einfach in plentymarkets ein.

[.instruction]
Kontoeinstellungen im Assistenten vornehmen:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Kontoeinstellungen - Zalando*.
. Folge den Anweisungen auf dem Bildschirm. Wenn du zusätzliche Informationen zu einer der Optionen benötigst, klappe die Info-Boxen unten auf (icon:chevron-down[role="darkGrey"]).
. Prüfe im Schritt *Zusammenfassung* deine Einstellungen noch einmal auf mögliche Fehler. +
*_Tipp:_* Klicke auf den Pfeil nach unten (icon:chevron-down[role="darkGrey"]), um die Einstellungen auszuklappen.
. Wenn alles passt, klicke auf icon:check[role="green"] *Abschließen*. +
→ Die Kontoeinstellungen werden gespeichert.

[.collapseBox]
.Schritt: *Artikelstatusbericht*
--

*Sollen für deine Artikel auf Zalando Statusberichte generiert werden?*

Wenn du die Option *Artikelstatusberichte generieren* aktivierst, stehen im Menü *Einrichtung » Märkte » Zalando » Einstellungen » Tab: Verarbeitungsberichte* die folgenden Artikelstatusberichte im CSV-Format zur Verfügung:

* *_ProductErrorReport_*: Enthält Varianten, die aktuell nicht auf Zalando verkauft werden können. Der Bericht enthält außerdem die ersten fünf Fehlercodes und eine Fehlerbeschreibung.
* *_ProductLiveReport_*: Enthält Varianten, die aktuell auf Zalando verkauft werden können. Der Bericht enthält außerdem Informationen zum Bestand und Preis jeder Variante auf den Zalando-Channels (DE, FR usw.) zu dem Zeitpunkt, zu dem die Datei generiert wurde.

Die Produkt-Status-Berichte werden von Zalando generiert. Die Berichte enthalten deshalb nur Informationen zu Varianten, die erfolgreich zu Zalando exportiert wurden. Beide Dateien werden automatisch einmal pro Nacht aktualisiert. Du kannst die Dateien aber auch manuell aktualisieren.

<<#910, So rufst du Produkt-Status-Berichte ab>>
--

[.collapseBox]
.Schritt: *Konto-Aktivierung*
--

*Möchtest du dein Zalando-Konto jetzt aktivieren?*

* *Benutzerkonto aktivieren*
  ** Aktiviert (icon:toggle-on[role="green"]) = Der Datenaustausch mit Zalando ist aktiv.
  ** Deaktiviert (icon:toggle-off[role="darkGrey"]) = Der Datenaustausch mit Zalando ist nicht aktiv.

* *Dieses Konto kann nicht aktiviert werden.*
Der Datenaustausch mit Zalando ist nicht aktiv. Um die zDirect-API-Schnittstelle von Zalando zu aktivieren, muss dein Zalando-Konto mit dem plentymarkets Entwicklungskonto verknüpft werden. Diese Verknüpfung passiert im Verlauf der Integration automatisch. Allerdings muss plentymarkets in einem zusätzlichen Schritt Zugangsdaten für die API generieren und diese Zugangsdaten in deinem System hinterlegen. Diese Zugangsdaten dürfen nicht von dir einsehbar sein. Deshalb kann plentymarkets dir die Zugangsdaten nicht bereitstellen. link:https://forum.plentymarkets.com/t/sammelthema-aktivierung-neuer-zalando-konten/600409[Melde dich in diesem Forum-Thread, um die Freischaltung deines Kontos zu erbitten.]
Gib in deinem Foren-Post die folgenden Informationen an:

    ** Den Firmen-/ Markennamen, unter dem Du bei Zalando registriert bist
    ** Deine Plenty-ID
    ** Die ID des Zalando-Kontos (accountId) in plentymarkets, das für die Zalando-Schnittstelle freigeschaltet werden soll +
        *_Hinweis:_* Pro Händler:innenkonto bei Zalando kann nur ein Konto bei plentymarkets verknüpft werden.

--

////
