= Best Practice: Bestandsanzeige Amazon FBA für EU und UK
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: Amazon, FBA, Bestand, Bestandsanzeige, Bestand EU, Bestand UK, Bestandsimport
:position: 250
:url: maerkte/amazon/best-practices-amazon-fba.bestandsanzeige
:id: 1X9TX72

Dieses Best Practice soll dich dabei unterstützen, den Gesamtwarenbestand deines europäischen Amazon-Verkäuferkontos jeweils für EU und UK separat im System auf Artikel/Variantenebene darzustellen.
Es kann pro Artikel/Variante der Warenbestand für alle europäischen Lager (Summiert, Gesamtbestand) und der Bestand aller Lager des Vereinigten Königreichs (Summiert, Gesamtbestand) im System dargestellt werden.
Korrekt konfiguriert bedeutet dies, dass ihr an einer Variante/einem Artikel zwei Lager sehen könnt, wobei das eine Lager den FBA EU-Stock und ein Lager den FBA UK-Stock darstellt (wenn Bestand vorhanden).

[.collapseBox]
.*Hintergrund: Brexit*
--
Vor dem Brexit konnte lediglich der gesamte FBA-EU-Bestand eines Artikels, pro Konto, im plentymarkets-System dargestellt werden. Dies umfasste alle europäischen Amazon-Plattformen des Verkäuferkontos, inklusive Amazon.co.uk. Seit dem Brexit wird der FBA-UK-Stock für Amazon.co.uk separat geführt und im System wurde lediglich der gesamte FBA-EU-Stock für einen Artikel dargestellt, jedoch nicht mehr der FBA-UK-Stock.
--

Folgende Konfiguration ist hierfür erforderlich:

Es wird mindestens ein Konto im System benötigt, welches einem europäischen Verkäuferkonto zugeordnet ist und welches hier einen Abruf auf eine europäische Amazon-Plattform tätigen kann. Dies wird in der Konfiguration anhand der gewählten Amazon-Plattform bestimmt.
Hierfür kommt ein angelegtes Konto mit einer Amazon-Plattform für Amazon.de, Amazon.pl, Amazon.fr, Amazon.es, Amazon.it, oder Amazon.nl infrage.
Dieses Konto ruft den Bestand der gesamten FBA EU Bestände ab.


jeweils die gesamten Warenbestände für EU und UK in eurem plentymarkets System abzurufen.
