= Twitter
:lang: en
include::{includedir}/_header.adoc[]
:position: 20

**plentymarkets » Settings » Client (store) » Global settings » Services » Twitter**

== Twitter

Are you already using the microblogging service, **link:http:///www.twitter.com[Twitter, window="_blank"]**? As a registered user, you can send text-based posts of up to 140 characters and you can receive such messages from other users.

The messages are called tweets. Twitter's social network is based on the idea that users can subscribe to the messages that others send. Those who subscribe to your tweets are referred to as your followers. Conversely, you are following someone else if you subscribe to their tweets. You can enter messages on the Twitter homepage and see messages posted by people you follow. Their tweets will be listed in chronological order.

Tweets can be directly transmitted from plentymarkets to Twitter. When sending a tweet from the store, a "suggestion" of what content you could include will automatically be entered into the text box. This will be done for items, blog entries and content pages. +
Furthermore, you can have the URLs that are contained in the suggestions shortened by the URL shortening service, **link:http://bit.ly/[bit.ly, window="_blank"]**. This will give you more room to express yourself. For further information about configuring bit.ly, refer to the <<client-store/global-settings/external-services/bit-ly#, **bit.ly**  >> page of the manual.

[TIP]
.Tip
====
Motivate your customers and other interested parties to subscribe to your Twitter blog so that you can send them information about new products and special offers via Twitter.
====

For further information about configuring Twitter, refer to the <<client-store/global-settings/external-services/twitter#, **Twitter**  >> page of the manual.

