= Zuordnung Zolltarifnummer
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Zuordnung Zolltarifnummer, Taric, Umsatzsteuer
:position: 160
:url: daten/daten-importieren/sync-typen/elasticSync-zuordnung-zolltarifnummer
:id: SOPEBTH
:author: team-order-payment

//optional - add extra sentences between the brackets in einleitung-weitere-info if you want to have further info in your introduction
:einleitung-daten: pass:quotes[Zolltarifnummern]
:einleitung-weitere-info: pass:quotes[]
:abgleich-tabelle: <<Abgleichfelder für Zolltarifnummernimport>>
:abgleich-daten: pass:quotes[Zolltarifnummern]
:zuordnung-daten: pass:quotes[Zolltarifnummern]
:zuordnung-standardwert: pass:quotes[dein Auftrag]

include::./_textblocks/einleitung.adoc[]

Mit einem Import des Typs *Zuordnung Zolltarifnummer* importierst du Daten für die Zolltarifnummerntabelle im Menü *Einrichtung » Mandant » Global » Zolltarifnummern*. Um Zolltarifnummern an Varianten per Import zu hinterlegen, gehe zum <<daten/daten-importieren/sync-typen/elasticSync-artikel#2300, Import-Typ Artikel>>.

[#10]
== Felder für den Abgleich

include::./_textblocks/abgleich.adoc[]

[[table-matching-taric]]
.Abgleichfelder für Zolltarifnummernimport
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Zolltarifnummer*
|In welcher Spalte deiner CSV-Datei werden Zolltarifnummern aufgelistet? Wähle diese Spalte hier. +
Mehr Informationen über Zolltarifnummern findest du im Abschnitt <<auftraege/buchhaltung#620, Zolltarifnummern>> im Handbuch.

|*Land*
|In welcher Spalte deiner CSV-Datei werden Länder aufgelistet? Wähle diese Spalte hier. +
Trage die Länder in deiner CSV-Datei entweder anhand der *Country-ID* oder anhand des *IsoCodes* ein. Beides findest du im Abschnitt <<daten/interne-IDs#20, Länder>>  im Handbuch.

|====

[#20]
== Felder für die Zuordnung

include::./_textblocks/zuordnung.adoc[]

[#30]
=== Zuordnung

[#40]
==== Umsatzsteuer

Welche Umsatzsteuer soll zugewiesen werden? Gib diesen Umsatzsteuersatz in deine CSV-Datei ein. +
Gib den Prozentwert des Steuersatzes ohne Prozentzeichen ein. Ob der Satz kommasepariert oder punktsepariert eingetragen werden muss, hängt von deiner Einstellung im Bereich *Abgleich* des Imports ab.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Numerisch

Das Ergebnis des Imports findest du im Backend im Menü *Einrichtung » Mandant » Global » Zolltarifnummern*.

[#50]
==== Löschen

Entscheide, ob eine bereits bestehende Zuordnung zwischen einem Umsatzsteuersatz, einer Zolltarifnummer und einem Land gelöscht werden soll.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Numerisch

[[table-delete-taric-data]]
[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Optionen in der Dropdown-Liste im Backend

|`0`
|Nicht löschen

|`1`
|Löschen
|====

Das Ergebnis des Imports findest du im Backend im Menü *Einrichtung » Mandant » Global » Zolltarifnummern*.
