= Warenbestand
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Stock, Warenbestand, Import, Sync, Sync-Typ, Warenbestand importieren, Warenbestandsdaten
:position: 140
:url: daten/daten-importieren/sync-typen/elasticSync-warenbestand
:id: BA1OBE6
:author: team-stock

:einleitung-daten: pass:quotes[Warenbestand]
:einleitung-weitere-info: pass:quotes[]
:abgleich-tabelle: <<tabelle-abgleichfelder-warenbestand>>
:abgleich-daten: pass:quotes[Warenbestand]
:zuordnung-daten: pass:quotes[Warenbestand]
:zuordnung-standardwert: pass:quotes[dein Warenbestand]

include::./_textblocks/einleitung.adoc[]

[#100]
== Abgleichfelder

include::./_textblocks/abgleich.adoc[]

[[tabelle-abgleichfelder-warenbestand]]
.Abgleichfelder für Warenbestand
[cols="1,3"]
|====
|Abgleichfeld |Erläuterung

|*ArtikelID*
|ID des Artikels

|*VariantenID*
|ID der Variante

|*Variantennummer*
|Variantennummer

|*Barcode*
|Barcode +
*_Hinweis_*: Stelle sicher, dass im Menü *Artikel » Artikel bearbeiten* im Tab *Einstellungen* der Code für den Barcode eingetragen ist. Außerdem muss im Abgleich des Imports im rechten Abgleichfeld *Barcode* der Name des Barcodes (z.B. GTIN 13) ausgewählt sein.
|====


[#200]
== Zuordnungsfelder

include::./_textblocks/zuordnung.adoc[]

[#210]
==== Lager-ID

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Lagers, in dem der Warenbestand liegt, in deine CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<warenwirtschaft/lager-einrichten#1500, Waren » Wareneingänge » [Suche ausführen] » [Wareneingang wählen] » Tab: Artikel>>.

'''

[#220]
==== Menge

icon:warning[role="red"] [red]#Pflichtwert#

Gib die Menge des Warenbestands in deine CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<warenwirtschaft/wareneingaenge-verwalten#500, Waren » Wareneingänge » [Suche ausführen] » [Wareneingang wählen] » Tab: Artikel>>.

'''

[#230]
==== Lagerort-ID

icon:warning[role="red"] [red]#Pflichtwert#

Gib die ID des Lagerortes, auf dem der Warenbestand liegt, in deine CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<warenwirtschaft/lager-einrichten#1500, Waren » Wareneingänge » [Suche ausführen] » [Wareneingang wählen] » Tab: Artikel>>.

'''

[#240]
==== Mindesthaltbarkeitsdatum

Gib das Mindesthaltbarketisdatum der Ware in deine CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Datum im Format tt.mm.jjjj

Das Ergebnis des Imports findest du im Backend im Menü <<warenwirtschaft/mhd-charge-verwalten#100, Waren » Wareneingänge » [Suche ausführen] » [Wareneingang wählen] » Tab: Artikel>>.

'''

[#250]
==== Charge

Gib die Charge des Warenbestands in deine CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<warenwirtschaft/mhd-charge-verwalten#100, Waren » Wareneingänge » [Suche ausführen] » [Wareneingang wählen] » Tab: Artikel>>.

'''

[#260]
==== Einkaufspreis

Gib den Einkaufspreis des Warenbestands in deine CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Numerisch; verwende die gleiche Dezimalschreibweise wie in den <<daten/daten-importieren/ElasticSync#1300, Importoptionen>>.

Das Ergebnis des Imports findest du im Backend im Menü <<warenwirtschaft/warenbestaende-verwalten#intable-ek, Waren » Wareneingänge » [Suche ausführen] » [Wareneingang wählen] » Tab: Artikel>>.

'''
