= Artikel
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Artikel, Artikelanlage, Variantenanlage
:position: 10
:url: daten/daten-importieren/sync-typen/elasticSync-artikel
:id: QUGDW1A
:author: team-item

Diese Seite erläutert die Abgleich- und Zuordnungsfelder, die dir beim Importieren von Artikel- und Variantendaten zur Verfügung stehen. Diese Seite dient lediglich als Referenz und setzt voraus, dass du bereits Grundkenntnisse über das <<daten/daten-importieren/ElasticSync#, Import-Tool>> hast.

[IMPORTANT]
.Voraussetzungen
====
Um Artikeldaten per Import-Tool zu importieren, müssen die folgenden Datensätze in plentymarkets vorhanden sein:

* Kategorien (Menü *Artikel » Kategorien*)
* Verkaufspreise (Menü *Einrichtung » Artikel » Verkaufspreise*)

Um Variantendaten mit Attributen per Import-Tool zu importieren, müssen die folgenden Datensätze in plentymarkets vorhanden sein:

* Attribute und Attributwerte (Menü *Einrichtung » Artikel » Attribute*)
====

[TIP]
.Praxisbeispiel: Neue Artikel importieren
====
Stell dir mal vor, du bist ganz neu bei plentymarkets und möchtest alle deine Artikel und Varianten auf einmal importieren. Wie geht so etwas? Wirf einen Blick auf <<daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-variantenanlage#, dieses praktische Beispiel>>, welches dich Schritt für Schritt durch den Prozess führt.
====

[#1910]
== Felder für den Artikelabgleich

In <<table-matching-fields-item>> werden Felder erläutert, die für den Abgleich von Artikeldaten zur Verfügung stehen. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-matching-fields-item]]
.Abgleichfelder für Artikelimport
[cols="1,3"]
|====
|Abgleichfeld |Erläuterung

|Varianten-ID
|

|Variantennr.
|

|Externe Varianten-ID
|

|Barcode
|Aus der zweiten Dropdown-Liste den <<artikel/einstellungen/barcodes#100, Barcode-Typ>> wählen.

|Artikel-ID
|Bei Varianten mit Attributen dieses Feld nur in Kombination mit Attributauswahlkombination nutzen.


|Attributauswahlkombination
|Bei Varianten mit Attributen dieses Feld nur in Kombination mit Artikel-ID nutzen.
Aus der zweiten Dropdown-Liste das Format wählen, in dem die Daten in der Datei vorliegen.

|Lieferanten-Artikel-Nr.
|

|====

[#1920]
== Felder für die Artikelzuordnung

//since there are many different fields, the explainations have been divided into sub-chapters.
In diesem Kapitel werden Felder erläutert, die für die Zuordnung von Artikel- und Variantendaten zur Verfügung stehen.

Da für den Import-Typ *Artikel* viele verschiedene Zuordnungsfelder zur Verfügung stehen, wurden die nachfolgenden Erläuterungen in Unterkapitel unterteilt.

[TIP]
.Kein Zuordnungsfeld? Standardwert greift!
====
Wenn du eine bestimmte Information nicht in deine CSV-Datei aufnimmst, d.h. wenn du ein bestimmtes Zuordnungsfeld _nicht verwendest_, dann erhält dein Artikel bzw. deine Variante den Standardwert.
====

[#2260]
=== Artikel
//evtl Tab Global und aaaa und bbbb anstatt die obere Tab-Leiste

In <<table-mapping-fields-items>> werden Felder erläutert, die für die Zuordnung diverser _Artikeldaten_ zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen, z.B. den Tabs <<artikel/artikel-verwalten#40, Global>>, <<artikel/artikel-verwalten#45, Multi-Channel>> und <<artikel/artikel-verwalten#70, Felder>> innerhalb der <<artikel/einleitung/struktur#200, oberen Tab-Leiste>> eines Artikeldatensatzes.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Artikeldatensatz nach dem Import öffnest, siehst du, dass die Einstellungen in der oberen Tab-Leiste wie folgt konfiguriert wurden.

[[table-mapping-fields-items]]
.Felder für Artikelimport
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Warentyp
|0 +
1 +
2 +
3
|0
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Typ>>

* 0 = Lagerware
* 1 = Produktionsware
* 2 = Colli
* 3 = Bestellware

|Shop-Aktion
|0 +
1 +
2 +
3
|0
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Webshop » Option: Shop-Aktion>>

* 0 = Keine
* 1 = Sonderangebot
* 2 = Neuheit
* 3 = Top-Artikel

|Hersteller-ID
|Numerisch (interne ID)
|- k.A. -
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Hersteller>>

Die Zuordnung erfolgt über die Hersteller-ID im Menü *Einrichtung » Artikel » Hersteller*.

|Herstellungsland
|Numerisch (interne ID); +
0
|Deutschland
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Herstellungsland>>

Die Zuordnung erfolgt über die <<daten/interne-IDs#20, Liste der Länder-IDs>>.

* 0 = unbekannt

|Erlöskonto
|Numerisch
|0
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Erlöskonto>>

|Aktionsgutschein
|0 +
1 +
2
|0
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Aktionsgutschein/POS-Rabatt>>

* 0 = Möglich
* 1 = Verboten
* 2 = Nur mit Gutschein kaufbar

|Zustand
|0 +
1 +
2 +
3 +
4
|0
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Zustand>>

* 0 = Neu
* 1 = Gebraucht
* 2 = Neu und originalverpackt
* 3 = Neu mit Etikett
* 4 = B-Ware

|Zustand API
|0 +
1 +
2 +
3 +
4 +
5
|0
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Zustand API>>

* 0 = Neu
* 1 = Gebraucht wie neu
* 2 = Gebraucht sehr gut
* 3 = Gebraucht gut
* 4 = Gebraucht annehmbar
* 5 = B-Ware

|Abonnement (Ja/Nein)
|0 +
1
|0
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Abonnement>>

* 0 = Nein
* 1 = Ja

|Seriennummer (Ja/Nein)
|0 +
1
|0
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Seriennummer>>

* 0 = Nein
* 1 = Ja

|Versandpaket (Ja/Nein)
|0 +
1
|0
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Versandpaket>>

* 0 = Nein
* 1 = Ja

|Amazon-Abwicklung (FBA)
|0 +
1 +
2 +
3 +
-1
|0
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Amazon » Option: FBA-Abwicklung>>

* 0 = Nicht verwenden
* 1 = AMAZON_EU
* 2 = AMAZON_FE
* 3 = AMAZON_NA
* -1 = FBA und SellerCentral

|Versand durch Amazon (FBA)
|0 +
1
|0
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Amazon » Option: Amazon FBA>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Amazon-Produkttyp
|Numerisch
|Unbekannt
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Amazon » Option: Produkttyp>>

Die Zuordnung erfolgt über die <<daten/interne-IDs#130, Wertetabelle amazon_product_type>>.

|Amazon-FEDAS
//0 und 1 macht dafür gar kein Sinn
|0 +
1
|
a|FEDAS-Warengruppenschlüssel

* 0 = Nein
* 1 = Ja

|Listing-Vorlage
|Numerisch (interne ID)
|- k.A. -
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Listing-Voreinstellungen » Option: Listing-Vorlage>>

Die Zuordnung erfolgt über die Listing-Vorlage-ID im Menü *Listings » Listings*.

|Listing Kategorie 1; +
Listing Kategorie 2
|Numerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Listing-Voreinstellungen » Option: Kategorie 1>>

|Listing Shop-Kategorie 1; +
Listing Shop-Kategorie 2
|Numerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Listing-Voreinstellungen » Option: Shop-Kategorie 1>>


|Rakuten.de-Kategorien
|Numerisch (interne ID)
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#45, Tab: Multi-Channel » Bereich: Kategorieverknüpfung » Option: Rakuten.de>>

|Markierung 1; +
Markierung 2
|Numerisch (interne ID)
|- k.A. -
|Entspricht der <<artikel/einstellungen/markierungen#, Markierung des Artikels>>.

Die Zuordnung erfolgt über die ID der Markierung im Menü *Einrichtung » Artikel » Makierungen » Tab: Markierung 1 bzw. Markierung 2*

|Altersfreigabe
|0 +
3 +
6 +
12 +
16 +
18 +
50 +
88 +
99
|0
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Altersfreigabe>>

* 0 = Keine verfügbar
* 3 = FSK 3
* 6 = FSK 6
* 12 = FSK 12
* 16 = FSK 16
* 18 = FSK 18
* 50 = Nicht gekennzeichnet
* 88 = Nicht erforderlich
* 99 = Noch nicht bekannt

|Artikelbewertung
|Numerisch
|0
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Webshop » Option: Artikelbewertung>>

|Feld 1; +
Feld 2; +
Feld 3; +
... +
Feld 20
|Alphanumerisch
|- k.A. -
|Entspricht den Freitextfeldern 1 bis 20 unter: +
<<artikel/artikel-verwalten#70, Tab: Felder>>

|Max. Artikelbestellmenge
|Numerisch
|0
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Max. Bestellmenge>>

|Typ
|standard +
multipack +
set
|standard
a|_Beim Erstellen eines neuen Artikels_, entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#20, Tab zum Erstellen eines neuen Artikels » Bereich: Artikeldaten » Option: Typ>>

* standard = Artikel des Typs *Standard*
* multipack = Artikel des Typs *Multipack*
* set = Artikel des Typs *Set*


|Herstellername
|Alphanumerisch
|- k.A. -
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#40, Tab: Global » Bereich: Grundeinstellungen » Option: Hersteller>>

Die Zuordnung erfolgt über den Herstellernamen. Wenn der Herstellerdatensatz nicht bereits im System vorhanden ist, wird ein neuer Herstellerdatensatz angelegt.

//wo findet man Artikelvorlage?
//|Artikelvorlage
//|Numerisch
//|
//|ID der Kategorie der <<artikel/artikel-verwalten#720, Artikelvorlage>> +
//*_Hinweis:_* Artikelvorlagen gibt es nur im alten Webdesign Callisto.

|Artikel löschen
|0 +
1
|0
a|Möchtest du einige Artikel löschen und andere aktualisieren? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob der Artikel gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====

[#3000]
=== Artikelsets

In <<table-mapping-fields-item-sets>> werden Felder erläutert, die für die Zuordnung von Artikelsets zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/anwendungsfaelle/multipacks-pakete-sets#3700, Bestandteile zu einem Setartikel hinzuzufügen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Setartikel nach dem Import öffnest, siehst du, dass die Einstellungen im Tab *Set* wie folgt konfiguriert wurden.

//Für den Import von Artikelsets stehen die in <<table-mapping-fields-item-sets>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-item-sets]]
.Felder für Import von Artikelsets
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Bestandteile hinzufügen (IDs, kommasepariert)
|Alphanumerisch
|IDs und Anzahl der Artikel, die zum Set hinzugefügt werden +
Format: `artikelID:menge,artikelID:menge`

|Bestandteile entfernen (IDs, kommasepariert)
|Alphanumerisch
|IDs der Artikel, die aus dem Set entfernt werden

|Rabatt
|Dezimalzahl
|Rabatt auf den Gesamtpreis des Sets in %
|====

[#2310]
=== Cross-Selling

In <<table-mapping-fields-cross-selling>> werden Felder erläutert, die für die Zuordnung von Cross-Selling-Artikeln zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/webshop/cross-selling#, zusätzliche Verkäufe mittels Cross-Selling zu erzielen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Artikel nach dem Import öffnest, siehst du, dass die Cross-Selling-Verbindungen wie folgt konfiguriert wurden.

//Für den Import von Cross-Selling-Verknüpfungen stehen die in <<table-mapping-fields-cross-selling>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-cross-selling]]
.Felder für Import von Cross-Selling-Verknüpfungen
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Alle Cross-Selling-Verknüpfungen löschen
|0 +
1
a|Möchtest du <<artikel/webshop/cross-selling#600, alle Cross-Selling-Verbindungen aus dem Artikeldatensatz löschen>>? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Cross-Selling-Verbindungen gelöscht werden sollen.

* 0 = Nein
* 1 = Ja

|Cross-Selling-Verknüpfungen hinzufügen
|Alphanumerisch
a|Möchtest du <<artikel/webshop/cross-selling#300, neue Cross-Selling-Verbindungen erstellen>>? Gib Informationen über die Verbindung in diesem Format ein: +
`Artikel-ID:Beziehungstyp;Artikel-ID:Beziehungstyp;etc.`

Verfügbare Beziehungstypen:

* Accessory = Zubehör
* ReplacementPart = Ersatzteil
* Similar = Ähnlich
* Bundle = Artikelpaket

|Cross-Selling-Verknüpfungen löschen
|Numerisch
|Möchtest du <<artikel/webshop/cross-selling#600, einige der Cross-Selling-Verbindungen aus dem Artikeldatensatz löschen>>? Gib die zu löschende Cross-Selling-Verknüpfungen in diesem Format ein: +
`Artikel-ID;Artikel-ID;etc.`
|====

=== Artikel Ebay Titel

In <<table-mapping-fields-ebay-title>> werden Felder erläutert, die für die Zuordnung von eBay-Listing-Titel zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, bis zu neun <<artikel/artikel-verwalten#_ebay_titel, eBay-Listing-Titel pro Artikel zu verknüpfen>>.

[[table-mapping-fields-ebay-title]]
.Felder für Import von eBay-Listing-Titel
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Titel (kommasepariert)
|Alphanumerisch
| - k.A. -
a|Gib alle neun Listing-Titel kommasepariert in deine CSV-Datei ein.

*_Hinweis_*: Es ist nicht möglich, nur einige der neun Titel zu importieren.
Der Grund dafür ist, dass beim Import alle neun Titel gelöscht und neu hinzugefügt werden.

*_Hinweis_*: Der Import ist auf maximal neun Titel beschränkt. Falls deine CSV-Datei mehr als neun Titel enthält, werden alle Titel über dieses Limit ignoriert.
|====


[#2270]
=== Artikelbeschreibung

In <<table-mapping-fields-item-description>> werden Felder erläutert, die für die Zuordnung von Artikelbeschreibungen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also den <<artikel/artikel-verwalten#50, Einstellungen im Artikeltext-Tab>>.

Gib die Texte in deine CSV-Datei ein. Pro Sprache wird eine Zuordnung erstellt.
Wenn du den Artikel nach dem Import öffnest, siehst du, dass diese Texte für den Artikel gespeichert wurden.

//Für den Import der Artikelbeschreibungen stehen die in <<table-mapping-fields-item-description>> aufgelisteten Felder zur Verfügung. Pro Sprache wird eine Zuordnung erstellt. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-item-description]]
.Felder für Import von Artikelbeschreibungen
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Name; +
Name 2; +
Name 3
|Alphanumerisch
|Gib einen Namen für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Name 1, 2, 3>>

|Vorschautext
|Alphanumerisch
|Gib einen Vorschautext für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Vorschautext>>

|Meta-Beschreibung
|Alphanumerisch
|Gib eine Meta-Beschreibung für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Meta-Beschreibung>>

|Artikeltext
|Alphanumerisch
|Gib einen Artikeltext für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Artikeltext>>

|Technische Daten
|Alphanumerisch
|Gib technische Daten für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Technische Daten>>

|URL-Pfad
|Link
|Gib einen URL-Pfad für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: URL-Pfad>>

|Meta-Keywords
|Alphanumerisch
|Gib Meta-Keywords für den Artikel in deine CSV-Datei ein. Stell im Bereich *Zuordnung* auch die Sprache ein.

Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#50, Tab: Texte » Option: Meta-Keywords>>
|====

[#2280]
=== Versandprofil

In <<table-mapping-fields-shipping-profile>> werden Felder erläutert, die für die Zuordnung von Versandprofilen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#40, Versandprofile mit Artikeln zu verknüpfen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Artikel nach dem Import öffnest, siehst du, dass die Versandprofile wie folgt verknüpft wurden.

//Für den Import von Versandprofilen stehen die in <<table-mapping-fields-shipping-profile>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-shipping-profile]]
.Abgleichfelder für Versandprofile
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Versandprofil-ID
|Numerisch
|Gib die ID des Versandprofils ein, das mit dem Artikel verknüpft werden soll.

Versandprofil-IDs können im Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versandprofile* nachgeschlagen werden.

|Versandprofile (kommasepariert)
|Numerisch
|Möchtest du mehr als nur einem Versandprofil verknüpfen? Gib die IDs aller Versandprofile ein, die mit dem Artikel verknüpft werden sollen.
Gib die IDs in diesem Format ein: +
`Profil-ID1,Profil-ID2,...`

Versandprofil-IDs können im Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versandprofile* nachgeschlagen werden.

|Versandprofilverknüpfungen löschen (Profil-IDs, kommasepariert)
|Alphanumerisch
|Möchtest du einige Verknüpfungen löschen? Gib die IDs aller Versandprofile ein, die _nicht mehr_ mit dem Artikel verknüpft werden sollen.
Gib die IDs in diesem Format ein: +
`Profil-ID1,Profil-ID2,...`

Versandprofil-IDs können im Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Versandprofile* nachgeschlagen werden.
|====


[#2300]
=== Varianten
//evtl Tab Einstellungen einer Variante anstatt die untere Tab-Leiste

In <<table-mapping-fields-variations>> werden Felder erläutert, die für die Zuordnung von Variantendaten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also Angaben in der <<artikel/einleitung/struktur#200, unteren Tab-Leiste>> eines Artikeldatensatzes.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen in der unteren Tab-Leiste wie folgt konfiguriert wurden.

//Für den Import von Variantendaten stehen die in <<table-mapping-fields-variations>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-variations]]
.Abgleichfelder für Varianten
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|ID
//weitere Info hinzufügen
|Numerisch
|- k.A. -
|Entspricht der ID der Variante.

|Artikel-ID
//weitere Info hinzufügen
|Numerisch
|- k.A. -
|Entspricht der ID des Artikels.

|Position
|Numerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Position>>

|Aktiv
|0 +
1
|0
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Aktiv>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Variantennr.
|Alphanumerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Variantennr.>>

|Modell
|Alphanumerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Modell>>

|Externe Varianten-ID
|Alphanumerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Ext. Varianten-ID>>

|Verfügbarkeit
|Numerisch (interne ID)
|1
|Entspricht den Verfügbarkeitssymbolen 1 bis 10 unter: +
<<artikel/artikel-verwalten#190, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Verfügbarkeit>>

|EK netto
|Numerisch
|0
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: EK netto>>

*_Hinweis_*: Verwende die gleiche Dezimal-Schreibweise wie in den <<daten/daten-importieren/ElasticSync#1300, Importoptionen>>.

|GLD EK netto
|Numerisch
|0
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: GLD EK netto>>

*_Hinweis_*: Verwende die gleiche Dezimal-Schreibweise wie in den <<daten/daten-importieren/ElasticSync#1300, Importoptionen>>.

|Preiskalkulation
|Numerisch (interne ID)
|- k.A. -
|icon:warning[role="red"] [red]#Alte Preiskalkulation#

Wendet eine Preiskalkulation auf die für die Variante gespeicherten Preise an. Entspricht also der _dritten_ Dropdown-Liste unter: +
<<artikel/artikel-verwalten#240, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verkaufspreise>>

Die Zuordnung erfolgt anhand der Preiskalkulation-ID im Menü *Einrichtung » Artikel » Preiskalkulation » Preiskalkulation öffnen*.

|Preiskalkulation UUID
|Alphanumerisch
|- k.A. -
|icon:warning[role="red"] [red]#Neue Preiskalkulation#

Gib die UUID einer Preiskalkulation in die CSV-Datei ein.
Dadurch wird die Preiskalkulation auf die für die Variante gespeicherten Preise angewendet.

*_Tipp_*:
Die Preiskalkulation-UUID kannst du kopieren.
Öffne dazu das Menü *Artikel » Preiskalkulation » [Preiskalkulation öffnen]*.
Klicke auf die UUID unten links.
Die UUID wird in die Zwischenablage kopiert.

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/artikel-verwalten#240, Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Verkaufspreise>>

|WB-Beschränkung
|0 +
1 +
2
|1
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#190, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Beschränkung>>

* 0 = Keine
* 1 = Auf Netto-WB
* 2 = Keinen WB für diese Variante führen

|Sichtbarkeit Mandant: Automatisch sichtbar, wenn Netto-WB positiv; +
Sichtbarkeit Mandant: Automatisch unsichtbar, wenn kein Netto-WB
|0 +
1
|0
a|Entspricht der gleichnamigen Checkbox unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Verfügbarkeit Webshop: Automatisch verfügbar, wenn Netto-WB positiv; +
Verfügbarkeit Webshop: Automatisch nicht verfügbar, wenn kein Netto-WB
|0 +
1
|0
a|Entspricht der gleichnamigen Checkbox unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

* 0 = Kein Häkchen
* 1 = Häkchen

//|Sichtbarkeit Artikelauflistung: Immer unsichtbar
//|0 = Nein +
//1 = Ja
//|
//|Entspricht die gleiche <<artikel/artikel-verwalten#230, Verfügbarkeitseinstellung>> in der Artikelübersicht.

|Sichtbarkeit Artikelauflistung: Automatisch sichtbar, wenn Netto-WB positiv; +
Sichtbarkeit Artikelauflistung: Automatisch unsichtbar, wenn kein Netto-WB
|0 +
1
|0
a|Entspricht der gleichnamigen Checkbox unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

* 0 = Kein Häkchen
* 1 = Häkchen

|Hauptlager
|Numerisch (interne ID)
|- k.A. -
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#190, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Hauptlager>>

Die Zuordnung erfolgt anhand der Lager-ID im Menü *Einrichtung » Waren » Lager » [Lager öffnen] » Einstellungen*.

|Max. Bestellmenge
|Numerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Max. Bestellmenge>>

|Min.-Bestellmenge
|Numerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Min.-Bestellmenge>>

|Intervallbestellmenge
|Numerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Intervallbestellmenge>>

|Verfügbar bis
|Datum +
(DD.MM.YYYY)
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Verfügbar bis>>

|Erscheinungsdatum
|Datum +
(DD.MM.YYYY)
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#230, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit » Option: Erscheinungsdatum>>

|Name
|Alphanumerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#_grundeinstellungen_an_der_hauptvariante_vornehmen, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Grundeinstellungen » Option: Variantenname>>

|Gewicht brutto g; +
Gewicht netto g
|Numerisch
|0
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Gewicht brutto bzw. Gewicht netto>>

Achte darauf, dass du das _Gewicht in Gramm_ anstatt in Kilogramm angibst.

*_Hinweis_*: Verwende die gleiche Dezimal-Schreibweise wie in den <<daten/daten-importieren/ElasticSync#1300, Importoptionen>>.

|Breite mm; +
Länge mm; +
Höhe mm
|Numerisch
|0
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Länge/Breite/Höhe>>

Achte darauf, dass du die _Maße in Millimetern_ angibst.

*_Hinweis_*: Verwende die gleiche Dezimal-Schreibweise wie in den <<daten/daten-importieren/ElasticSync#1300, Importoptionen>>.


|Portoaufschlag 1; +
Portoaufschlag 2
|Numerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#290, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Portoaufschlag 1 bzw. Portoaufschlag 2>>

|VPE
|Numerisch
|1
|Verpackungseinheit. Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: VPE>>

|Anzahl der Packstücke
|0 +
1 +
2 +
... +
20
|- k.A. -
|Entspricht der _ersten Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#290, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Packstücke>>

Verwende dieses Zuordnungsfeld zusammen mit *Einheit der Packstücke*.

|Einheit der Packstücke
|0 +
1 +
2 +
... +
39
|- k.A. -
a|Entspricht der _zweiten Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#290, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Packstücke>>

Verwende dieses Zuordnungsfeld zusammen mit *Anzahl der Packstücke*.

* 0 = unverpackt
* 1 = Ballen
* 2 = Behälter
* 3 = Bund
* 4 = Rollpalette
* 5 = Colli
* 6 = Container
* 7 = Eimer
* 8 = Fass
* 9 = Flaschen
* 10 = Euro Pool Flachpalette
* 11 = Gestell
* 12 = Gasflasche
* 13 = Gitterboxpalette
* 14 = Hobbock
* 15 = Halbe Palette
* 16 = Lebensmittelpalette
* 17 = Holzuntersetzer
* 18 = IBC Container
* 19 = Kanne
* 20 = Korbflasche
* 21 = Kiste
* 22 = Kanister
* 23 = Kundenpalette
* 24 = Karton
* 25 = Kombinationsverpackung
* 26 = Pack
* 27 = Ring
* 28 = Rolle
* 29 = Sack
* 30 = Stück
* 31 = Tank
* 32 = Trommel
* 34 = Verschlag
* 35 = Viertelpalette
* 36 = sonstige Paletten
* 37 = Kasten
* 38 = Einwegpalette
* 39 = Folientüte

|Transportkosten netto
|Numerisch
|0
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Transport netto>>

*_Hinweis_*: Verwende die gleiche Dezimal-Schreibweise wie in den <<daten/daten-importieren/ElasticSync#1300, Importoptionen>>.

|Lagerkosten netto
|Numerisch
|0
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Lager netto>>

*_Hinweis_*: Verwende die gleiche Dezimal-Schreibweise wie in den <<daten/daten-importieren/ElasticSync#1300, Importoptionen>>.

|Zoll
|Numerisch
(Prozentwert)
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Zoll>>

|Zolltarifnummer
|Numerisch
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Zolltarifnummer>>

|Betriebskosten
|Numerisch
(Prozentwert)
|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Betriebskosten>>

|Umsatzsteuer
//welcher Standardwert?
|Numerisch
(Prozentwert)
|
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Kosten » Option: Umsatzsteuer>>

|Paketart
//infos ergänzen
|bundle +
bundle_item
|
a|
* bundle = Variante ist Paket +
* bundle_item = Variante ist Paketbestandteil

|Sichtbarkeit Artikelauflistung: Immer unsichtbar
//infos ergänzen
|0 +
1
|
a|
* 0 = Nein +
* 1 = Ja

|Grundpreis anzeigen
|0 +
1
|0
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Grundpreisanzeige>>

* 0 = Nein
* 1 = Ja

|Gewicht brutto aus Paketbestandteilen berechnen; +
Gewicht netto aus Paketbestandteilen berechnen; +
EK netto aus Paketbestandteilen berechnen; +
GLD EK netto aus Paketbestandteilen berechnen
//standardwerte ergänzen
|0 +
1
|
a|Entspricht den Checkboxen unter: +
<<artikel/artikel-verwalten#265, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Paket » Option: Automatisch aus Paketbestandteilen berechnen>>

* 0 = Nein
* 1 = Ja

*_Hinweis_*: Diese Checkboxen sind nur für <<artikel/anwendungsfaelle/multipacks-pakete-sets#, Artikelpakete>> sichtbar.

|Kommissionierung
|single_picking +
no_single_picking +
exclude_from_picklist
|no_single_picking
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Versand » Option: Kommissionierung>>

* single_picking = Einzelkommissionierung möglich
* no_single_picking = Keine Einzelkommissionierung möglich
* exclude_from_picklist = Von Pickliste ausschließen

|Variante löschen
|0 +
1
|0
a|Möchtest du einige Varianten löschen und andere aktualisieren? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Variante gelöscht werden soll.

* 0 = Nein
* 1 = Ja

|Nummer der Hauptvariante
//infos ergänzen
//in wie fern unterscheidet sich das von der Variantennr. ganz oben?
|Alphanumerisch
|
|

|Trotz negativem Nettowarenbestand für Mandanten verfügbar machen
|0 +
1
|0
a|Entspricht dem Schlosssymbol im <<artikel/artikel-verwalten#360, Tab: Verfügbarkeit » Bereich: Mandant (Shop)>>.

*_Hintergund-Info_*: plentymarkets kann Varianten automatisch aus dem Webshop entfernen, wenn sie nicht mehr vorrätig sind. Dieser Automatismus wird durch die Einstellungen im <<artikel/artikel-verwalten#360, Tab: Einstellungen » Bereich: Verfügbarkeit>> gesteuert.

Verwende dieses Zuordnungsfeld, wenn du die Variante manuell im Webshop sichtbar machen möchtest, trotz fehlender Lagerbestände.

Diese Einstellung gilt, bis neuer Wareneingang für die Variante gebucht wird. Danach greifen die Einstellungen zur Nettowarenbestandsabhängigkeit erneut.

* 0 = Variante wird _nicht_ manuell sichtbar gemacht
* 1 = Variante wird manuell sichtbar gemacht
|====

[#2320]
=== Barcodes

In <<table-mapping-fields-barcodes>> werden Felder erläutert, die für die Zuordnung von Barcode-Daten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/einstellungen/barcodes#300, Barcodes zu Artikeln zuordnen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Artikel nach dem Import öffnest, siehst du, dass die Barcodes wie folgt verknüpft wurden.

//Für den Import von Barcode-Daten stehen die in <<table-mapping-fields-barcodes>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Barcode-Typ.

[[table-mapping-fields-barcodes]]
.Felder für Import von Barcodes
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Code
|Alphanumerisch
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Barcode » Option: Code>>

Gib den alphanumerischen Code in deine CSV-Datei ein.
Wähle den Barcode-Typ aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Barcode löschen
|0 +
1
a|Willst du einen Barcode aus dem Artikeldatensatz löschen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob der Barcode gelöscht werden soll.

* 0 = Nein
* 1 = Ja

Wähle den zu löschenden Barcode-Typ aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.
|====

[#2330]
=== Variantenpreise

In <<table-mapping-fields-prices>> werden Felder erläutert, die für die Zuordnung von Preisen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#240, Preise für Varianten zu speichern>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Preise wie folgt hinterlegt wurden.

//Für den Import von Variantenpreisen stehen die in <<table-mapping-fields-prices>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Verkaufspreis.

[[table-mapping-fields-prices]]
.Felder für Import von Variantenpreisen
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Preis
|Numerisch
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#280, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verkaufspreise » Option: Preis>>

Gib den Geldbetrag in deine CSV-Datei ein.
Wähle den <<artikel/einstellungen/preise#, Verkaufspreis>> aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

*_Hinweis_*: Verwende die gleiche Dezimal-Schreibweise wie in den <<daten/daten-importieren/ElasticSync#1300, Importoptionen>>.

|Preis löschen
|0 +
1
a|Willst du einen Preis aus dem Artikeldatensatz löschen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob der Preis gelöscht werden soll.

* 0 = Nein
* 1 = Ja

Wähle den zu löschenden <<artikel/einstellungen/preise#, Verkaufspreis>> aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Nettopreis (Ja/Nein)
|0 +
1
a|Ist der Geldbetrag als Nettopreis zu verstehen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob der Preis ein Nettopreis sein soll.

* 0 = Nein (es handelt sich um einen Bruttopreis)
* 1 = Ja (es handelt sich um einen Nettopreis)

Wähle den <<artikel/einstellungen/preise#, Verkaufspreis>> aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.
|====

[#2340]
=== Kategorien

In <<table-mapping-fields-categories>> werden Felder erläutert, die für die Zuordnung von Kategoriedaten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/einstellungen/kategorien#1300, Artikel in Kategorien einzusortieren>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Kategorien wie folgt verknüpft wurden.

//Für den Import von Kategoriedaten stehen die in <<table-mapping-fields-categories>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-categories]]
.Felder für Import von Kategorien
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|ID der Kategorie
|Numerisch (interne ID)
|Verknüpft _eine_ Kategorie mit der Variante. Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Verknüpfte Kategorien » Option: ID>>

Gib eine Kategorie-ID in die CSV-Datei ein. Die Kategorie-IDs findest du im Menü *Artikel » Kategorien* (ID wird beim Mouseover eingeblendet).

|Position
|Numerisch
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Verknüpfte Kategorien » Option: Position>>

Gib die Positionsnummer in die CSV-Datei ein.

|Ist Neckermann.de Hauptkategorie
//infos ergänzen
|0 +
1
a|

* 0 = Nein +
* 1 = Ja

|Name der Kategorie
|Alphanumerisch
|Verknüpft _eine_ Kategorie mit der Variante. Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Verknüpfte Kategorien » Option: Kategorie>>

Gib den vollständigen Kategoriepfad, durch Semikolons getrennt, ein. Zum Beispiel: +
*Schuhe;Unisex*

|Alle Kategorieverknüpfungen löschen
|0 +
1
a|Willst du _alle_ Kategorieverknüpfungen aus dem Artikeldatensatz löschen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Verknüpfungen gelöscht werden sollen.

* 0 = Nein
* 1 = Ja

*_Hinweis_*: Die Kategorien selbst werden nicht gelöscht. Die Verknüpfungen werden lediglich von der Variante entfernt.

|Kategorie-IDs (kommasepariert)
|Alphanumerisch
|Verknüpft _mehrere_ Kategorien mit der Variante. Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Verknüpfte Kategorien » Option: ID>>

Gib die Kategorie-IDs in die CSV-Datei ein. Trenne die IDs durch Kommas. Zum Beispiel: +
*ID1,ID2,ID3,usw*

Die Kategorie-IDs findest du im Menü *Artikel » Kategorien* (ID wird beim Mouseover eingeblendet).

|Kategorienamen (kommasepariert)
|Alphanumerisch
|Verknüpft _mehrere_ Kategorien mit der Variante. Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Verknüpfte Kategorien » Option: Kategorie>>

Gib den vollständigen Kategoriepfad, durch Semikolons getrennt, ein. Trenne mehrere Kategoriepfade durch Kommas. Zum Beispiel: +
*Schuhe;Unisex,Schuhe;Damen,Schuhe;Herren*

|Verknüpfungen löschen (Kategorie-IDs, kommasepariert)
|Alphanumerisch
|Willst du _einige_ Kategorieverknüpfungen aus dem Artikeldatensatz löschen?
Gib die IDs der zu löschenden Kategorien in deine CSV-Datei ein.
Trenne die IDs durch Kommas. Zum Beispiel: +
*ID1,ID2,ID3,usw*

Die Kategorie-IDs findest du im Menü *Artikel » Kategorien* (ID wird beim Mouseover eingeblendet).

*_Hinweis_*: Die Kategorien selbst werden nicht gelöscht. Die Verknüpfungen werden lediglich von der Variante entfernt.

|Verknüpfungen löschen (Kategorienamen, kommasepariert)
|Alphanumerisch
|Willst du _einige_ Kategorieverknüpfungen aus dem Artikeldatensatz löschen?
Gib die Namen der zu löschenden Kategorien in deine CSV-Datei ein.
Trenne mehrere Kategoriepfade durch Kommas. Zum Beispiel: +
*Schuhe;Unisex,Schuhe;Damen,Schuhe;Herren*

*_Hinweis_*: Die Kategorien selbst werden nicht gelöscht. Die Verknüpfungen werden lediglich von der Variante entfernt.

|Nicht gefundene Kategorien anlegen
|0 +
1
a|Möchtest du die Kategorie erstellen, falls sie noch nicht existiert? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Kategorie erstellt werden soll.

* 0 = Nein
* 1 = Ja
|====

[#2345]
=== Standardkategorien

In <<table-mapping-fields-default-categories>> werden Felder erläutert, die für die Zuordnung von Standardkategoriedaten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, anzugeben, welche Kategorie am passendsten ist.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Standardkategorie wie folgt verknüpft wurde.

//Für den Import von Standardkategoriedaten stehen die in <<table-mapping-fields-default-categories>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-default-categories]]
.Felder für Import von Standardkategorien
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|ID der Kategorie
|Numerisch (interne ID)
|Verknüpft die Standardkategorie mit der Variante. Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Standardkategorien>>

Gib eine Kategorie-ID in die CSV-Datei ein. Die Kategorie-IDs findest du im Menü *Artikel » Kategorien* (ID wird beim Mouseover eingeblendet).

|Name der Kategorie
|Alphanumerisch
|Verknüpft die Standardkategorie mit der Variante. Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Standardkategorien>>

Gib den vollständigen Kategoriepfad, durch Semikolons getrennt, ein. Zum Beispiel: +
*Schuhe;Unisex*

|Nicht gefundene Kategorien anlegen
|0 +
1
a|Möchtest du die Standardkategorie erstellen, falls sie noch nicht existiert? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Standardkategorie erstellt werden soll.

* 0 = Nein
* 1 = Ja
|====

[#2350]
=== Bestand
//info in die einleitung ergänzen

//when you redo this page, also fix the pflichtfelder links here:
//https://knowledge.plentymarkets.com/daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-variantenanlage#1100

Für den Import von Bestandsdaten stehen die in <<table-mapping-fields-stock>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-stock]]
.Felder für Import von Bestand
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Lager
|Numerisch (interne ID)
|Kann nur in Kombination mit Menge und Lagerort übergeben werden.

|Menge
|Numerisch
|Kann nur in Kombination mit Lager und Lagerort übergeben werden.

|Lagerort
|Numerisch (interne ID)
|Kann nur in Kombination mit Lager und Menge übergeben werden.
|====

[#2360]
=== Mandant (Shop)

In <<table-mapping-fields-client>> wird das Feld erläutert, das für die Zuordnung der Mandantenverfügbarkeit verwendet wird.
Dieses Zuordnungsfeld entspricht also deine Möglichkeit, die <<artikel/artikel-verwalten#_verfügbarkeit_für_mandanten_einstellen, Variante für bestimmte Mandanten verfügbar zu machen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Mandantenverfügbarkeit wie folgt hinterlegt wurde.

//Für den Import der Mandantenverfügbarkeit stehen die in <<table-mapping-fields-client>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Mandant.

[[table-mapping-fields-client]]
.Abgleichfelder für Import von Mandantenverfügbarkeiten
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Aktiv
|0 +
1
a|Willst du die Variante für einen bestimmten Mandanten (Shop) verfügbar machen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob ein Häkchen (icon:check-square[role="blue"]) neben dem Mandanten gesetzt wird.

* 0 = Nein
* 1 = Ja

Wähle den zu aktivierenden Webshop aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.
|====

[#2370]
=== Märkte

In <<table-mapping-fields-markets>> wird das Feld erläutert, das für die Zuordnung der Marktplatzverfügbarkeiten verwendet wird.
Dieses Zuordnungsfeld entspricht also deinen Möglichkeiten, die <<artikel/artikel-verwalten#235, Variante für bestimmte Marktplätze verfügbar zu machen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Marktplatzverfügbarkeiten wie folgt hinterlegt wurden.

//Für den Import der Marktplatzverfügbarkeiten stehen die in <<table-mapping-fields-markets>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Marktplatz.

[[table-mapping-fields-markets]]
.Felder für Import von Marktplatzverfügbarkeiten
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Aktiv
|0 +
1
a|Willst du die Variante für bestimmte Märkte verfügbar machen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob der Markt in die folgende Liste aufgenommen wird: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Märkte>>

* 0 = Nein
* 1 = Ja

Wähle den zu aktivierenden Markt aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.
|====

[#2380]
=== Attribute
//die Beschreibungen in der Tabelle könnten noch verständlicher geschrieben werden

In <<table-mapping-fields-attributes>> werden Felder erläutert, die für die Zuordnung von Attributverknüpfungen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, Attribute für Varianten zu speichern.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass sie mit den folgenden Attributen angelegt wurde.

//Für den Import von Attributverknüpfungen stehen die in <<table-mapping-fields-attributes>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Format.

[[table-mapping-fields-attributes]]
.Felder für Import von Attributverknüpfungen
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Attributauswahlkombination
|Alphanumerisch
|Kombination aus *Attributname (intern)* und *Attributwert (intern)* im Format +
`Attributname:Wertname;` oder `Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;` +
Import von mehr als zwei Attributverknüpfungen. +
*_Hinweis:_* Jede Attributauswahlkombination muss pro Variante einzigartig sein.

|Attribute ID
|Numerisch
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die IDs in verschiedenen Spalten vorliegen. Eine Zuordnung im Format `Attributname:Wertname;` und eine weitere im Format `Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;` erstellen und die separaten Spalten zuordnen.

|Attribute Name
|Alphanumerisch
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die Namen in verschiedenen Spalten vorliegen. Eine Zuordnung im Format `Attributname:Wertname;` und eine weitere im Format `Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;` erstellen und die separaten Spalten zuordnen.

|Wert Name
|Alphanumerisch
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die Namen in verschiedenen Spalten vorliegen. Eine Zuordnung im Format `Attributname:Wertname;` und eine weitere im Format `Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;` erstellen und die separaten Spalten zuordnen.

|Wert ID
|Numerisch
|Import von bis zu zwei Attributverknüpfungen. +
*_Tipp:_* Bei zwei Verknüpfungen müssen die IDs in verschiedenen Spalten vorliegen. Eine Zuordnung im Format `Attributname:Wertname;` und eine weitere im Format `Attributname&lt;&gt;Wertname&lt;&#x007C;&#x007C;&gt;` erstellen und die separaten Spalten zuordnen.

|Erstell nicht existierende Werte
|0 +
1
a|Möchtest du die Attributwerte erstellen, falls sie noch nicht existieren? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Werte erstellt werden sollen.

* 0 = Nein
* 1 = Ja
|====

[#2390]
=== Artikelbilder

In <<table-mapping-fields-item-images>> werden Felder erläutert, die für die Zuordnung von Artikelbildern zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#90, Bilder für Artikel>> und <<artikel/artikel-verwalten#_artikelbilder_mit_varianten_verknüpfen, Varianten>> zu speichern.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Artikelbilder wie folgt gespeichert wurden.

[[table-mapping-fields-item-images]]
.Abgleichfelder für Import von Artikelbildern
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|ID des Bildes
|Numerisch (interne ID)
|Die interne ID des Bildes.
Bilder-IDs kannst du z.B. nachschlagen, indem du deine <<daten/daten-exportieren/FormatDesigner/format-typen/artikelbilder#, Artikelbilder exportierst>>.

|Position
|Numerisch
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#300, Tab: Bilder » Option: Position>>

Gib die Positionsnummer in die CSV-Datei ein.

|Dateiname
|Alphanumerisch
|Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#300, Tab: Bilder » Auf das Bild klicken » Dateiname oben>>

Gib die Dateiname in die CSV-Datei ein.

|Base64 Data
//was ist das? Woher weiß man das?
|Alphanumerisch
|

|URL
|Alphanumerisch
|Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#300, Tab: Bilder » URL>>

Gib die URL in die CSV-Datei ein.

|Multi-URL (kommasepariert)
|Alphanumerisch
|Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#300, Tab: Bilder » URL>>

Gib mehrere Bild-URLs und Positionsnummern im folgenden Format in die CSV-Datei ein. +
`image1url;positionImage1,image2url;positionImage2` +
Wenn keine Position übergeben wird, entspricht die Position der Reihenfolge der URLs.

*_Hinweis_*: Wenn du dieses Zuordnungsfeld verwendest, wirst du die Verfügbarkeiten nicht individuell steuern können.
Das heißt, die Bilder werden automatisch für alle Mandanten, Herkünfte und Listings verfügbar sein.
Willst du selbst steuern, für welche Mandanten, Herkünfte und Listings das Bild verfügbar ist, dann verwende stattdessen das Zuordnungsfeld *URL*.

*_Hinweis_*: Es ist _nicht möglich_, dieses Feld in Zusammenhang mit dem Zuordnungsfeld *Artikelbilder / Namen* zu verwenden.

|Bilder löschen
|0 +
1
a|Möchtest du alle Bilder des Artikels löschen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Bilder gelöscht werden sollen.

* 0 = Nein
* 1 = Ja

|Bilder löschen (IDs, kommasepariert)
|Numerisch (interne IDs)
|Möchtest du einige Bilder des Artikels löschen?
Gib die IDs aller zu löschenden Bilder in deine CSV-Datei ein.
Verwende Kommas, um die IDs zu trennen.
Bilder-IDs kannst du z.B. nachschlagen, indem du deine <<daten/daten-exportieren/FormatDesigner/format-typen/artikelbilder#, Artikelbilder exportierst>>.

|Bilder löschen (Urls, kommasepariert)
|Alphanumerisch
|Möchtest du einige Bilder des Artikels löschen?
Gib die URLs aller zu löschenden Bilder in deine CSV-Datei ein.
Verwende Kommas, um die URLs zu trennen.

|Mit Variante verknüpfen
|0 +
1
a|Möchtest du das Bild mit der Variante verknüpfen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein.

* 0 = Löscht eine vorhandene Verknüpfung
* 1 = Verknüpft das Bild mit der Variante

|Verfügbarkeit Mandant (Shop)
|Numerisch (interne ID)
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#300, Tab: Bilder » Option: Verfügbarkeit>>

*_Das Bild für Mandanten verfügbar machen_*:

* Gib die plenty-IDs aller zu aktivierenden Mandanten in deine CSV-Datei ein.
Trenne die IDs durch Kommas.
Die plenty-IDs findest du im Menü *Einrichtung » Mandant » [Mandant wählen] » Einstellungen » Option: Plenty ID*
* Gib alternativ *-1* ein, um alle Mandanten zu aktivieren.

*_Das Bild für Mandanten nicht verfügbar machen_*:

* Gib *0* in deine CSV-Datei ein.
* Lass alternativ die Zeile in die CSV-Datei leer.

*_Hinweis_*: Dieses Zuordnungsfeld ist _nicht_ mit dem Zuordnungsfeld *Multi-URL (kommasepariert)* kombinierbar.
Verwende stattdessen das Feld *URL*.

|Verfügbarkeit Herkünfte
|Numerisch (interne ID)
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#300, Tab: Bilder » Option: Verfügbarkeit>>

*_Das Bild für Herkünfte verfügbar machen_*:

* Gib die IDs aller zu aktivierenden Herkünfte ein. Trenne die IDs durch Kommas.
Die <<daten/interne-IDs#90, Herkunft-IDs>> findest du im Menü *Einrichtung » Aufträge » Auftragsherkunft*
* Gib alternativ *-1* ein, um alle Herkünfte zu aktivieren.

*_Das Bild für Herkünfte nicht verfügbar machen_*:

* Gib *0* in deine CSV-Datei ein.
* Lass alternativ die Zeile in die CSV-Datei leer.

*_Hinweis_*: Dieses Zuordnungsfeld ist _nicht_ mit dem Zuordnungsfeld *Multi-URL (kommasepariert)* kombinierbar.
Verwende stattdessen das Feld *URL*.

|Verfügbarkeit Listings
|Numerisch (interne ID)
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#300, Tab: Bilder » Option: Verfügbarkeit>>

*_Das Bild für Listings verfügbar machen_*:

* Gib die IDs aller zu aktivierenden Listing-Herkünfte ein. Trenne die IDs durch Kommas.
Die <<daten/interne-IDs#90, Listing-Herkunft-IDs>> findest du im Menü *Einrichtung » Aufträge » Auftragsherkunft*
* Gib alternativ *-1* ein, um alle Listings zu aktivieren.

*_Das Bild für Listings nicht verfügbar machen_*:

* Gib *0* in deine CSV-Datei ein.
* Lass alternativ die Zeile in die CSV-Datei leer.

*_Hinweis_*: Dieses Zuordnungsfeld ist _nicht_ mit dem Zuordnungsfeld *Multi-URL (kommasepariert)* kombinierbar.
Verwende stattdessen das Feld *URL*.

|Namen
|Alphanumerisch
a|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#300, Tab: Bilder » Option: Name>>

Gib den Namen des Artikelbildes im folgenden Format in die CSV-Datei ein. +
`Name1:Sprache1:Alternativtext1,Name2:Sprache2:Alternativtext2`

*_Hinweis_*:
Diese Namen brauchen eine Zuordnung zum Bild.
Das heißt, du musst zusätzlich angeben, für welches Bild die Namen gelten.
Dies geschieht:

* entweder durch Angabe der Bild-ID (Zuordnungsfeld *Artikelbilder / ID des Bildes*).
* Oder beim Initialimport mit Hilfe des Zuordnungsfeldes *Artikelbilder / URL*.
Es ist _nicht möglich_, dieses Feld in Zusammenhang mit dem Zuordnungsfeld *Artikelbilder / Multi-URL (kommasepariert)* zu verwenden.

|Alternative Namen
|Alphanumerisch
a|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#300, Tab: Bilder » Option: Alternativtext>>

Gib den Alternativtext des Artikelbildes im folgenden Format in die CSV-Datei ein. +
`Alternativtext1:Sprache1,Alternativtext2:Sprache2`

*_Hinweis_*:
Diese Namen brauchen eine Zuordnung zum Bild.
Das heißt, du musst zusätzlich angeben, für welches Bild die Namen gelten.
Dies geschieht:

* entweder durch Angabe der Bild-ID (Zuordnungsfeld *Artikelbilder / ID des Bildes*).
* Oder beim Initialimport mit Hilfe des Zuordnungsfeldes *Artikelbilder / URL*.
Es ist _nicht möglich_, dieses Feld in Zusammenhang mit dem Zuordnungsfeld *Artikelbilder / Multi-URL (kommasepariert)* zu verwenden.

|Marktplatzattributverknüpfung (Attibutwert-ID)
|Numerisch (interne ID)
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#300, Tab: Bilder » Option: Marktplatzattributverknüpfung>>

Gib die ID des Attributwerts in die CSV-Datei ein.

|Alle Verfügbarkeiten entfernen
|0 +
1
a|Möchtest du alle Verfügbarkeiten entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein.

* 0 = Nein
* 1 = Ja
|====

[#2400]
=== Merkmale

In <<table-mapping-fields-characteristics>> werden Felder erläutert, die für die Zuordnung von Merkmalverknüpfungen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#80, Merkmale mit Artikeln zu verknüpfen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du den Artikel nach dem Import öffnest, siehst du, dass die Merkmale wie folgt verknüpft wurden.

//Für den Import von Merkmalverknüpfungen stehen die in <<table-mapping-fields-characteristics>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-characteristics]]
.Felder für Import von Merkmalverknüpfungen
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|ID
|Numerisch (interne ID)
|Verknüpft das Merkmal mit dem Artikel. Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#80, Tab: Merkmale » Bereich: Merkmale>>

Gib eine Merkmal-ID in die CSV-Datei ein. Die Merkmal-IDs findest du im Menü *Einrichtung » Artikel » Merkmale*.

|Merkmalkombination
|Alphanumerisch
|Gib die Kombination aus Backend-Name, Wert und Sprache in die CSV-Datei ein. Gib diese Informationen im folgenden Format ein: +
`Name1:Wert1:Sprache1;Name2:Wert2:Sprache2` etc.

*_Hinweis_*: Nutze dieses Zuordnungsfeld nicht, wenn z.B. dein Wert eine URL mit Doppelpunkt ist.
Da Doppelpunkte zur Trennung von Name, Wert und Sprache verwendet werden, würde der Doppelpunkt innerhalb einer URL nicht richtig verstanden werden.
Importiere solche Merkmale stattdessen mit drei separaten Feldern: Merkmal / ID, Merkmal / Wert und Merkmal / Sprache.

|Interner Name
|Alphanumerisch
|Verknüpft das Merkmal mit dem Artikel. Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#80, Tab: Merkmale » Bereich: Merkmale>>

Gib den internen Namen in die CSV-Datei ein. Die internen Namen findest du im Menü *Einrichtung » Artikel » Merkmale*.

|Wert
|Alphanumerisch
|Entspricht dem Wert des Merkmals unter: +
<<artikel/artikel-verwalten#80, Tab: Merkmale » Bereich: Merkmale>>

Gib den Wert in die CSV-Datei ein.
Je nach Typ des Merkmals kann der Wert z.B. ein Text oder eine Zahl sein.

|Auswahl-ID
|Numerisch (interne ID)
|Nur bei Merkmalen des Typs *Auswahl*. Verknüpft die Auswahlwerte eines Merkmals über die ID.

Gib eine Auswahl-ID in die CSV-Datei ein. Die Auswahl-IDs findest du im Menü *Einrichtung » Artikel » Merkmale » Merkmal vom Typ Auswahl öffnen*.

|Sprache
|Buchstaben
|Nur bei Merkmalen des Typs *Text*. Gibt an, in welcher Sprache der Text verfasst ist.

Gib einen <<daten/interne-IDs#10, Sprachcode>> in die CSV-Datei ein.

|Löschen (Ja/Nein)
|0 +
1
a|Möchtest du das Merkmal aus dem Artikeldatensatz entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob das Merkmal gelöscht werden soll.

* 0 = Nein
* 1 = Ja

*_Hinweis_*: Das Merkmal selbst wird nicht gelöscht. Das Merkmal wird lediglich vom Artikeldatensatz entfernt.
|====

[#2410]
=== Eigenschaften

In <<table-mapping-fields-properties>> werden Felder erläutert, die für die Zuordnung von Eigenschaftsverknüpfungen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#4800, Eigenschaften mit Varianten zu verknüpfen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Eigenschaften wie folgt verknüpft wurden.

//Für den Import von Eigenschaftsverknüpfungen stehen die in <<table-mapping-fields-properties>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-properties]]
.Felder für Import von Eigenschaftsverknüpfungen
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|ID
|Numerisch (interne ID)
|Verknüpft die Eigenschaft mit der Variante. Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#4800, Tab: ID einer Variante » Tab: Eigenschaften oder Texte>>

Gib eine Eigenschaft-ID in die CSV-Datei ein. Die Eigenschaft-IDs findest du im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.

|Sprache
|Buchstaben
|Nur bei Eigenschaften des Typs *Text* oder *Kurztext*. Gibt an, in welcher Sprache der Text verfasst ist.

Gib einen <<daten/interne-IDs#10, Sprachcode>> in die CSV-Datei ein.

|Wert
//stimmt es, dass die Wert auch für den Typ Text gilt?
|Alphanumerisch
|Entspricht dem Wert der Eigenschaft unter: +
<<artikel/artikel-verwalten#4800, Tab: ID einer Variante » Tab: Eigenschaften oder Texte>>

Gib den Wert in die CSV-Datei ein.
Je nach Eigenschaft-Typ kann der Wert z.B. ein Text oder eine Zahl sein.

|Beschreibung
//info ergänzen
|Alphanumerisch
|

|Interner Name
|Alphanumerisch
|Verknüpft die Eigenschaft mit der Variante. Entspricht den Angaben unter: +
<<artikel/artikel-verwalten#4800, Tab: ID einer Variante » Tab: Eigenschaften oder Texte>>

Gib den internen Namen in die CSV-Datei ein. Die internen Namen findest du im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.

|Eigenschaftenkombination
|Alphanumerisch
|Gib die Kombination aus Backend-Name, Wert und Sprache in die CSV-Datei ein. Gib diese Informationen im folgenden Format ein: +
`Name1:Wert1:Sprache1;Name2:Wert2:Sprache2` etc.

|Auswahleigenschaftkombination (Namen)
|Alphanumerisch
|Nur bei Eigenschaften des Typs *Auswahl*. Gib die Kombination aus Eigenschaft-Name, Auswahlwert-Name und Sprache in die CSV-Datei ein. Gib diese Informationen im folgenden Format ein: +
`EigenschaftName1:AuswahlwertName1:Sprache1;EigenschaftName2:AuswahlwertName2:Sprache2`

|Auswahleigenschaftkombination (IDs)
|Alphanumerisch
|Nur bei Eigenschaften des Typs *Auswahl*. Gib die Kombination aus Eigenschaft-ID, Auswahlwert-ID und Sprache in die CSV-Datei ein. Gib diese Informationen im folgenden Format ein: +
`EigenschaftID1:AuswahlwertID1:Sprache1;EigenschaftID2:AuswahlwertID2:Sprache2`

|Auswahl-ID
|Numerisch (interne ID)
|Nur bei Eigenschaften des Typs *Auswahl*. Verknüpft den Auswahlwert einer Eigenschaft über die ID. Gib die Auswahl-ID in die CSV-Datei ein. +

Die Auswahl-IDs findest du im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration » [Eigenschaft öffnen] » Werte*.

|Mehrfachauswahl-IDs (kommasepariert)
|Numerisch (interne ID)
|Nur bei Eigenschaften des Typs *Mehrfachauswahl*. Verknüpft die Auswahlwerte einer Eigenschaft über die IDs. Gib die Auswahl-IDs kommasepariert in die CSV-Datei ein. +

Die Auswahl-IDs findest du im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration » [Eigenschaft öffnen] » Werte*.

|Löschen (Ja/Nein)
|0 +
1
a|Möchtest du die Eigenschaft aus dem Variantendatensatz entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Eigenschaft gelöscht werden soll.

* 0 = Nein
* 1 = Ja

*_Hinweis_*: Die Eigenschaft selbst wird nicht gelöscht. Die Eigenschaft wird lediglich vom Variantendatensatz entfernt.
|====

[#2290]
=== Varianten-Tags

In <<table-mapping-fields-tags>> werden Felder erläutert, die für die Zuordnung von Tags zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#150, Tags mit Varianten zu verknüpfen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Tags wie folgt verknüpft wurden.

//Für den Import von Tag-Verknüpfungen stehen die in <<table-mapping-fields-tags>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-tags]]
.Felder für Import von Tags-Verknüpfungen
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Tag-ID
//hinweis - es gibt keine Möglichkeit, mehrere Tag IDs auch kommasepariert eingeben - das ginge nur über den Tag-Namen
|Numerisch
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib eine Tag-ID in die CSV-Datei ein.
Die Tag-IDs findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

|Tag-Name
|Alphanumerisch
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib einen Namen für das Tag in die CSV-Datei ein.
Die Tag-Namen findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

|Tag-Namen +
(kommasepariert)
|Alphanumerisch
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib die Namen von mehreren Tags in die CSV-Datei ein. Verwende Kommas, um die Namen wie folgt zu trennen: +
name1,name2,name3...

Die Tag-Namen findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

|Alle Tag-Verknüpfungen löschen
|0 +
1
//|0
a|Möchtest du _alle Tags_ von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Tag-Verknüpfungen gelöscht werden sollen.

* 0 = Nein
* 1 = Ja

*_Hinweis_*: Die Tags selbst werden nicht gelöscht. Die Tags werden lediglich von der Variante entfernt.

|Tag-Verknüpfung löschen (Name, kommasepariert)
|Alphanumerisch
//|- k.A. -
a|Möchtest du _einige der Tags_ von einer Variante entfernen?
Gib die Namen der zu entfernenden Tags in die CSV-Datei ein. Verwende Kommas, um die Namen wie folgt zu trennen: +
name1,name2,name3…​

Die Tag-Namen findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

*_Hinweis_*: Die Tags selbst werden nicht gelöscht. Die Tags werden lediglich von der Variante entfernt.

|Tag-Verknüpfung löschen (ID, kommasepariert)
|Alphanumerisch
//|- k.A. -
a|Möchtest du _einige der Tags_ von einer Variante entfernen?
Gib die IDs der zu entfernenden Tags in die CSV-Datei ein. Verwende Kommas, um die IDs wie folgt zu trennen: +
id1,id2,id3…​

Die Tag-IDs findest du im Menü *Einrichtung » Einstellungen » Tags » Tag öffnen*.

*_Hinweis_*: Die Tags selbst werden nicht gelöscht. Die Tags werden lediglich von der Variante entfernt.
|====

[#2420]
=== Vererbung
//standardwerte ergänzen

In <<table-mapping-fields-inheritance>> werden Felder erläutert, die für die Zuordnung von Vererbungen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/einleitung/vererbung#, Daten mit der Vererbungsfunktion weiter zu geben>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Vererbungsfunktionen wie folgt aktiviert oder deaktiviert wurden.

//Für den Import von Vererbungen stehen die in <<table-mapping-fields-inheritance>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-inheritance]]
.Felder für Import von Vererbungen
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Kategorie
|0 +
1
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#300, Tab: ID einer Variante » Tab: Kategorien » Bereich: Verknüpfte Kategorien>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Märkte
|0 +
1
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Märkte>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Mandant
|0 +
1
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#_verfügbarkeit_für_mandanten_einstellen, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Mandant (Shop)>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Verkaufspreis
|0 +
1
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#240, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verkaufspreise>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Lieferant
|0 +
1
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Lager
|0 +
1
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Verfügbarkeit
|0 +
1
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#240, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Verfügbarkeit>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Eigenschaften
|0 +
1
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#4800, Tab: ID einer Variante » Tab: Eigenschaften>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert

|Tags
|0 +
1
a|Sollte die <<artikel/einleitung/vererbung#, Vererbung>> aktiviert oder deaktiviert sein unter: +
<<artikel/artikel-verwalten#150, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Tags>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Vererbung aktiviert werden soll.

* 0 = Deaktiviert
* 1 = Aktiviert
|====

[#2420a]
=== Inhalt

In <<table-mapping-fields-content>> werden Felder erläutert, die für die Zuordnung von Inhalten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, den <<artikel/artikel-verwalten#270, Inhalt und Einheit einer Variante>> anzugeben.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Inhalte wie folgt gespeichert wurden.

//Für den Import des Inhalts stehen die in <<table-mapping-fields-content>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-content]]
.Felder für Import des Inhalts
[cols="2,1,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Standardwert |Erläuterung

|Inhalt Einheit
|Numerisch
(interne ID)
|Stück
|Entspricht der _Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Inhalt>>

Gib die ID der Einheit in die CSV-Datei ein.
Die Einheit-IDs findest du im Menü *Einrichtung » Artikel » Einheiten*.

*_Hinweis_*: Verwende dieses Zuordnungsfeld in Kombination mit *Inhalt Menge*.

//IDs siehe <<daten/interne-IDs#40, IDs der Einheiten>> +
//Alternativ *Inhalt Maßeinheit (ISO)* übergeben

|Inhalt Menge
|Numerisch
|1
|Entspricht dem _Eingabefeld_ unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Inhalt>>

Gib den numerischen Inhalt in die CSV-Datei ein.

*_Hinweis_*: Verwende dieses Zuordnungsfeld in Kombination mit *Inhalt Einheit* oder *Inhalt Maßeinheit (ISO)*.

*_Hinweis_*: Verwende die gleiche Dezimal-Schreibweise wie in den <<daten/daten-importieren/ElasticSync#1300, Importoptionen>>.

|Inhalt Maßeinheit (ISO)
|Alphanumerischer ISO-Code
|Stück
|Entspricht der _Dropdown-Liste_ unter: +
<<artikel/artikel-verwalten#270, Tab: ID einer Variante » Tab: Einstellungen » Bereich: Maße » Option: Inhalt>>

Gib den ISO-Code für die Einheit in die CSV-Datei ein.
Die ISO-Codes findest du im Menü *Einrichtung » Artikel » Einheiten*.

*_Hinweis_*: Verwende dieses Zuordnungsfeld in Kombination mit *Inhalt Menge*.

|====

[#2430]
=== ASIN/ePID

In <<table-mapping-fields-ASIN-ePID>> werden Felder erläutert, die für die Zuordnung von ASIN/ePIDs zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#260, ASIN/ePIDs für Varianten zu speichern>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen im *Tab: Einstellungen » Bereich: ASIN/ePID* wie folgt gespeichert wurden.

//Für den Import von ASIN/ePID stehen die in <<table-mapping-fields-ASIN-ePID>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-ASIN-ePID]]
.Felder für Import von ASIN/ePID
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Land
|Numerisch (interne ID)
|Entspricht der _ersten_ Dropdown-Liste unter: +
<<artikel/artikel-verwalten#260, Tab: ID einer Variante » Tab: Einstellungen » Bereich: ASIN/ePID>>

Mit anderen Worten: Entspricht der _Länderplattform_, z.B. Amazon Deutschland, eBay Frankreich, eBay UK, usw.

Gib die Länder-ID in deine CSV-Datei ein. Die Länder-IDs findest du im Menü *Einrichtung » Aufträge » Versand » Optionen » Tab: Lieferländer*.

Eine <<daten/interne-IDs#20, Liste von IDs ist auch im Online-Handbuch>> zu finden.

|Typ
|ASIN +
ePID
|Entspricht der _zweiten_ Dropdown-Liste unter: +
<<artikel/artikel-verwalten#260, Tab: ID einer Variante » Tab: Einstellungen » Bereich: ASIN/ePID>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein.
Welchen Wert du wählst, bestimmt, ob es sich um eine ASIN oder ePID handelt.

|Position
//infos ergänzen
|Numerisch
|

|Wert
|Alphanumerisch
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#260, Tab: ID einer Variante » Tab: Einstellungen » Bereich: ASIN/ePID>>

Gib die ASIN oder ePID in deine CSV-Datei ein.

|Löschen (IDs, kommasepariert)
|Numerisch (interne ID)
a|Möchtest du einige ASINs oder ePIDs von einer Variante entfernen?
Gib die IDs der zu entfernenden ASINs oder ePIDs in die CSV-Datei ein. Verwende Kommas, um die IDs wie folgt zu trennen: +
ASIN-ID1,ASIN-ID2,ASIN-ID3 etc.

//gibt es ein Menü, wo man die ASIN bzw ePID-IDs findet?
|====

[#2440]
=== Lager

In <<table-mapping-fields-warehouse>> werden Felder erläutert, die für die Zuordnung von Lagerdaten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, anzugeben, <<artikel/artikel-verwalten#312, wo eine bestimmte Variante gelagert ist>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen im Tab *Lager* wie folgt gespeichert wurden.

//Für den Import von Lagerdaten stehen die in <<table-mapping-fields-warehouse>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist. Die Zuordnung erfolgt pro Lager.

[[table-mapping-fields-warehouse]]
.Felder für Import von Lagerdaten
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Zone
|Numerisch
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Zone>>

//wo kann man die Zone-ID nachschlagen? Also in welchem Menü?
//Die Zuordnung erfolgt anhand der Zone-ID im Menü *Einrichtung » Waren » Lager » [Lager öffnen] » Einstellungen*.

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Lagerorttyp
|none +
small +
medium +
large +
europallet
a|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Lagerorttyp>>

* none = Kein Typ ausgewählt
* small = Klein
* medium = Mittel
* large = Groß
* europallet = Europalette

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Meldebestand
|Numerisch
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Meldebestand>>

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Maximalbestand
|Numerisch
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Maximalbestand>>

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Lagerreichweite (in Tagen)
|Numerisch
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Lagerreichweite>>

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Lagerort
|Numerisch (interne ID)
|Entspricht der Dropdown-Liste unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Lagerortvorschlag>>

Die Zuordnung erfolgt anhand der Lagerort-ID im Menü *Einrichtung » Waren » Lager » [Lager öffnen] » Lagerorte*.

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Bestandspuffer
|Numerisch
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Bestandspuffer>>

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Charge (ja/nein)
|0 +
1
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: Charge>>

* 0 = Kein Häkchen
* 1 = Häkchen

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Mindeshaltbarkeitsdatum (ja/nein)
|0 +
1
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#312, Tab: ID einer Variante » Tab: Lager » Spalte: MHD>>

* 0 = Kein Häkchen
* 1 = Häkchen

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

|Lagerverknüpfung löschen
|0 +
1
a|Möchtest du das Lager von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob das Lager gelöscht werden soll.

* 0 = Nein
* 1 = Ja

Wähle das betreffende Lager aus der zweiten Dropdown-Liste im Bereich *Zuordnung*.

*_Hinweis_*: Das Lager selbst wird nicht gelöscht. Das Lager wird lediglich von der Variante entfernt.
|====

[#2450]
=== Lieferant

In <<table-mapping-fields-supplier>> werden Felder erläutert, die für die Zuordnung von Lieferantendaten zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#312, Lieferanten zu Varianten hinzuzufügen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen im Tab *Lieferant* wie folgt gespeichert wurden.

//Für den Import von Lieferantendaten stehen die in <<table-mapping-fields-supplier>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-supplier]]
.Felder für Import von Lieferantendaten
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Lieferantenverknüpfungs-ID
|Numerisch
//|- k.A. -
|ID der Verknüpfung zwischen Variante und Lieferant. +
Diese ID wird automatisch von plentymarkets erzeugt. Die ID ist _nicht_ im plentymarkets Backend sichtbar. Sondern wird die ID lediglich im Hintergrund gespeichert. Möchtest du die ID trotzdem sehen, musst du diese Information zunächst aus deinem plentymarkets-System exportieren. Verwende dazu das Exportformat <<daten/daten-exportieren/FormatDesigner#385, VariationSupplier in FormatDesigner>>. +
Das Zuordnungsfeld *Lieferantenverknüpfungs-ID* ist <<daten/daten-importieren/sync-typen/elasticSync-artikel#1930, je nach Anwendungsfall>> eine Pflichtangabe. Beispielsweise wird dieses Feld benötigt, um Lieferanten direkt beim Artikelimport anzulegen.

|EK in Systemwährung
|Kommazahl
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: EK in Systemwährung>>

Gib die Zahl in deine CSV-Datei ein.

|Mindestabnahme
|Numerisch
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Mindestabnahme>>

Gib die Menge in deine CSV-Datei ein.

|Lieferanten-Artikel-Nr.
|Alphanumerisch
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Lieferanten-Artikel-Nr.>>

Gib die externe Artikelnummer in deine CSV-Datei ein.

|Letzte Preisanfrage
|Datum +
(Y-m-d H:i:s)
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Letzte Preisanfrage>>

Gib das Datum der letzten Preisverhandlung in deine CSV-Datei ein.

*_Hinweis_*: Gib das Datum in diesem Format ein: +
`2020-04-24 00:00:00` +
Wenn du lieber ein anderes Datumsformat verwenden möchtest, <<daten/daten-importieren/ElasticSync#1300, gib dieses Format in den Importoptionen an>>.

|Lieferzeit in Tagen
|Numerisch
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Lieferzeit in Tagen>>

Gib die Anzahl an Tagen in deine CSV-Datei ein.

|Rabatt
|Numerisch
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Rabatt>>

Gib den prozentualen Rabatt in deine CSV-Datei ein.

*_Hinweis_*: Der Rabatt wird in Nachbestellungen nur berücksichtigt, wenn auch die Rabattfähigkeit aktiviert wurde.

|Rabattfähigkeit
|0 +
1
//|- k.A. -
a|Entspricht der Checkbox unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Rabattfähigkeit>>

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob das Häkchen gesetzt wird.

* 0 = Kein Häkchen
* 1 = Häkchen

|Verpackungseinheit
|Numerisch
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Verpackungseinheit>>

Gib den numerischen Wert in deine CSV-Datei ein.

|EK in Bestellwährung
|Kommazahl
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: EK in Bestellwährung>>

Gib die Zahl in deine CSV-Datei ein.

|Lieferanten-Artikel-Bezeichnung
|Alphanumerisch
//|- k.A. -
|Entspricht dem Eingabefeld unter: +
<<artikel/artikel-verwalten#310, Tab: ID einer Variante » Tab: Lieferant » Spalte: Lieferanten-Artikel-Bez.>>

Gib den externen Namen in deine CSV-Datei ein.

|Lieferanten-ID
|Numerisch
//|- k.A. -
|Entspricht der Kontakt-ID des Lieferanten, wie im Menü *CRM » Kontakte* aufgeführt.

*_Tipp_*: Setze den Filter *Typ* auf *Lieferant*, um nur Kontakte des Typs *Lieferant* anzuzeigen.

|Lieferantenname
|Alphanumerisch
//|- k.A. -
|Entspricht den Namen des Lieferanten, wie im Menü *CRM » Kontakte* aufgeführt.

*_Tipp_*: Setze den Filter *Typ* auf *Lieferant*, um nur Kontakte des Typs *Lieferant* anzuzeigen.

|Lieferantenverknüpfung löschen
|0 +
1
//|- k.A. -
a|Möchtest du die Verknüpfung zwischen Lieferant und Variante aufheben? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Verknüpfung gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====

[#2460]
=== SKU

In <<table-mapping-fields-SKU>> werden Felder erläutert, die für die Zuordnung von SKUs zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#235, SKUs für Varianten zu speichern>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen im *Tab: Verfügbarkeit » Bereich: SKU* wie folgt gespeichert wurden.

//Für den Import von SKUs stehen die in <<table-mapping-fields-SKU>> Felder Abgleichfelder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-SKU]]
.Felder für Import von SKUs
[cols="2,1,4a"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Marktplatz-ID
|Numerisch
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: Herkunft>>

Die Zuordnung erfolgt anhand der Auftragsherkunft-ID im Menü *Einrichtung » Aufträge » Auftragsherkunft*.

Eine <<daten/interne-IDs#90, Liste von IDs ist auch im Online-Handbuch>> zu finden.

|Account-ID
|Numerisch
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: Konto>>

Die Zuordnung erfolgt anhand der Marktplatzkonto-ID.
Beispielsweise findest du Konto-IDs in den folgenden Menüs:

[cols="1,3"]
!===

!Amazon
!*Einrichtung » Märkte » Amazon » Einstellungen*

!eBay
!*Einrichtung » Märkte » eBay » Einstellungen » Kontoeinstellungen*

!Rakuten.de
!*Einrichtung » Märkte » Rakuten.de*

!===

*_Hinweis_*: Nicht jeder Marktplatz hat eine eigene Konto-ID.
Beispielsweise hat Check24 keine Marktplatzkonto-ID.
Gib in solchen Fällen 0 als die Konto-ID ein.

|SKU
|Alphanumerisch
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: SKU>>

Gib die SKU in deine CSV-Datei ein.

|Parent-SKU
|Alphanumerisch
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: SKU » Option: Parent-SKU>>

Gib die Parent-SKU in deine CSV-Datei ein.

|SKU löschen
|0 +
1
a|Möchtest du die SKU von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die SKU gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====

[#2465]
=== Zusätzliche SKU

In <<table-mapping-fields-additional-SKU>> werden Felder erläutert, die für die Zuordnung von zusätzlichen SKUs zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/artikel-verwalten#235, zusätzliche SKUs für Varianten zu speichern>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Einstellungen im *Tab: Verfügbarkeit » Bereich: Zusätzliche SKU* wie folgt gespeichert wurden.

//Für den Import von zusätzlichen SKUs stehen die in <<table-mapping-fields-additional-SKU>> Felder Abgleichfelder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-additional-SKU]]
.Felder für Import von zusätzlichen SKUs
[cols="2,1,4a"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|ID
//infos ergänzen
|Numerisch
|Eine existierende SKU ID

|Marktplatz-ID
|Numerisch
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Zusätzliche SKU » Option: Herkunft>>

Die Zuordnung erfolgt anhand der Auftragsherkunft-ID im Menü *Einrichtung » Aufträge » Auftragsherkunft*.

Eine <<daten/interne-IDs#90, Liste von IDs ist auch im Online-Handbuch>> zu finden.

|Account-ID
|Numerisch
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Zusätzliche SKU » Option: Konto>>

Die Zuordnung erfolgt anhand der Marktplatzkonto-ID.
Beispielsweise findest du Konto-IDs in den folgenden Menüs:

[cols="1,3"]
!===

!Amazon
!*Einrichtung » Märkte » Amazon » Einstellungen*

!eBay
!*Einrichtung » Märkte » eBay » Einstellungen » Kontoeinstellungen*

!Rakuten.de
!*Einrichtung » Märkte » Rakuten.de*

!===

*_Hinweis_*: Nicht jeder Marktplatz hat eine eigene Konto-ID.
Beispielsweise hat Check24 keine Marktplatzkonto-ID.
Gib in solchen Fällen 0 als die Konto-ID ein.

|SKU
|Alphanumerisch
|Entspricht dem Feld unter: +
<<artikel/artikel-verwalten#235, Tab: ID einer Variante » Tab: Verfügbarkeit » Bereich: Zusätzliche SKU » Option: SKU>>

Gib die SKU in deine CSV-Datei ein.

|Existierende SKU
//infos ergänzen
|Numerisch
//ist numerisch richtig?
|Der aktuelle Wert einer SKU
//was für ein Wert?

|Abgleich anhand von ID oder existierender SKU
//infos ergänzen
|0 +
1
a|
* 0 = Nein +
* 1 = Ja

|Zusätzliche SKU löschen
|0 +
1
a|Möchtest du die zusätzliche SKU von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die zusätzliche SKU gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====

[#2470]
=== Paket

In <<table-mapping-fields-bundle>> werden Felder erläutert, die für die Zuordnung von Artikelpaketen zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/anwendungsfaelle/multipacks-pakete-sets#2000, Bestandteile zu einem Paket hinzuzufügen>> und Bestandteile wieder aus einem Paket zu entfernen.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du das Paket nach dem Import öffnest, siehst du, dass die Bestandteile wie folgt hinzugefügt oder entfernt wurden.

//Für den Import von Artikelpaketen stehen die in <<table-mapping-fields-bundle>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-bundle]]
.Felder für Import von Paketen
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|Paketbestandteile
|Alphanumerisch
|Fügt Bestandteile zu einem Paket hinzu.
Gib die Varianten-ID und Menge des Paketbestandteils in deine CSV-Datei ein.
Trenne die Varianten-ID und Menge durch einen Doppelpunkt.
Trenne mehrere Bestandteile durch einen Semikolon. Beispiel: +
*Varianten-ID:Menge;Varianten-ID:Menge;etc.*

|Paketbestandteile (Variantennummer)
|Alphanumerisch
|Fügt Bestandteile zu einem Paket hinzu.
Gib die Variantennummer und Menge des Paketbestandteils in deine CSV-Datei ein.
Trenne die Variantennummer und Menge durch einen Doppelpunkt.
Trenne mehrere Bestandteile durch einen Semikolon. Beispiel: +
*Variantennummer:Menge;Variantennummer:Menge;etc.*

|Paketbestandteile löschen
|Alphanumerisch
|Löscht Bestandteile aus einem Paket raus.
Gib die Varianten-ID des zu löschenden Paketbestandteils in deine CSV-Datei ein.
Trenne mehrere Varianten-IDs durch einen Semikolon. Beispiel: +
*Varianten-ID;Varianten-ID*

|Paket löschen
|0 +
1
a|Löscht _alle_ Bestandteile aus einem Paket raus. Die Varianten-IDs der einzelne Bestandteile müssen nicht angegeben werden, da alle Paketbestandteile gleichzeitig gelöscht werden.

* 0 = Nein
* 1 = Ja
|====

[#sync-seriennummer]
=== Seriennummer

In <<table-mapping-fields-serial-number>> werden Felder erläutert, die für die Zuordnung von Seriennummern zur Verfügung stehen.
Diese Zuordnungsfelder entsprechen also deinen Möglichkeiten, <<artikel/anwendungsfaelle/seriennummern#100, einen Pool von Seriennummern im Artikeldatensatz aufzubauen>>.

Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, wie die Einstellung beim Import konfiguriert wird.

Mit anderen Worten: Wenn du die Variante nach dem Import öffnest, siehst du, dass die Seriennummer-Einstellungen wie folgt gespeichert wurden.

//Für den Import von Seriennummern stehen die in <<table-mapping-fields-serial-number>> aufgelisteten Felder zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[table-mapping-fields-serial-number]]
.Felder für Import von Seriennummern
[cols="2,1,4"]
|====
|Zuordnungsfeld |Zulässige Importwerte |Erläuterung

|ID
|Numerisch
|Entspricht dem Feld unter: +
<<artikel/anwendungsfaelle/seriennummern#200, Seriennummern-Symbol in die obere Leiste (icon:item_serial_number[set=plenty]) » Bereich: Seriennummern » Option: ID>>

Gib die ID der Seriennummer in deine CSV-Datei ein.

|Nummer
|Numerisch
|Entspricht dem Feld unter: +
<<artikel/anwendungsfaelle/seriennummern#200, Seriennummern-Symbol in die obere Leiste (icon:item_serial_number[set=plenty]) » Bereich: Seriennummern » Option: Seriennummer>>

Gib die Seriennummer in deine CSV-Datei ein.

|Seriennummer löschen
|0 +
1
a|Möchtest du die Seriennummer von einer Variante entfernen? Gib einen der zulässigen Importwerte in deine CSV-Datei ein. Welchen Wert du wählst, bestimmt, ob die Seriennummer gelöscht werden soll.

* 0 = Nein
* 1 = Ja
|====


[#1930]
== Pflichtwerte für Artikelimport-Aktionen

<<table-procedures-item-sync>> listet mögliche Aktionen für Importe des Typs Artikel und erläutert die Werte, die zum Ausführen dieser Aktionen unbedingt angegeben werden müssen.

[[table-procedures-item-sync]]
.Aktionen für Artikelimport
|====
|Aktion |Erforderliche Werte

2+| *Artikelbeschreibung*

|Artikelbeschreibung aktualisieren
a|
* Name

2+| *Versandprofil*

|Versandprofil aktualisieren
a|
* Versandprofil-ID

2+| *Varianten-Tags*

|Alle Tag-Verknüpfungen lösen
a|
* Alle verknüpften Tags löschen = 1

|Tag verknüpfen
a|Ein Tag:

* Tag-ID +
oder
* Tag-Name +

Mehrere Tags: +

* Tag-Namen (kommasepariert)

2+| *Varianten*

|Variante erstellen
a|
* ID der Standardkategorie +
oder
* Name der Standardkategorie

|Variante zu Artikel hinzufügen
a|
* Inhalt Menge
* Inhalt Einheit +
    oder
* Inhalt Menge
* Inhalt Maßeinheit (ISO)

und

* Artikel-ID +
    oder
* Nummer der Hauptvariante

Bei Varianten mit Attributen außerdem:

* Attributauswahlkombination +
    oder
* Attribute (Name oder ID)
* Wert (Name oder ID)

|Inhalt aktualisieren
a|
* Inhalt Menge
* Inhalt Einheit +
oder
* Inhalt Menge
* Inhalt Maßeinheit (ISO)

2+| *Barcodes*

|Barcode ändern
a|
* Code über Barcode-Zuordnung

2+| *Kategorien*

|Kategorie verknüpfen
a|
* ID der Kategorie +
oder
* Name der Kategorie

*_Tipp:_* Für weitere Kategorien zusätzliche Mappings erstellen.

|Verknüpfung aktualisieren
a|
* ID der Kategorie +
oder
* Name der Kategorie

2+| *Variantenpreise*

|Preis ändern
a|
* Preis über Verkaufspreiszuordnung

2+| *Standardkategorien*

|Standardkategorie verknüpfen
a|
* ID der Kategorie +
oder
* Name der Kategorie

|Standardkategorie aktualisieren
a|
* ID der Kategorie +
oder
* Name der Kategorie

2+| *Bestand*

|Bestand aktualisieren
a|
* Lager
* Menge
* Lagerort

2+| *Artikel-Bilder*

|Vor dem Hochladen alle Bilder löschen
a|
* Bilder löschen = 1

|Bilder speichern
a|
* Multi-URL +
oder
* URL +
oder
* Dateiname
* Base64 Data

|Bilder aktualisieren
a|
* ID des Bildes

|Bild mit Variante verknüpfen
a|
* Multi-URL +
oder
* URL

2+| *Merkmale*

|Merkmale speichern
a|
* Merkmalkombination +
oder
* Interner Name
* Sprache
* Wert +
oder
* ID
* Sprache
* Wert

|Merkmale aktualisieren
a|
* Merkmalkombination +
oder
* Interner Name
* Sprache
* Wert +
oder
* ID
* Sprache
* Wert

2+| *Eigenschaften*

|Eigenschaft verknüpfen
a|
* ID

* Sprache

* Wert

2+| *Lieferant*

|Lieferant verknüpfen
a|
* EK
* Lieferantenverknüpfungs-ID (für neue Verknüpfungen leer lassen)

und

* Lieferanten-ID +
    oder
* Lieferanten-Name

|Lieferant aktualisieren
a|
* EK
* Lieferantenverknüpfungs-ID

und

* Lieferanten-ID +
    oder
* Lieferanten-Name

2+| *SKU*

|SKU hinzufügen
a|
* Marktplatz-ID
* SKU
* Account-ID

|SKU aktualisieren
a|
* Marktplatz-ID
* SKU
* Account-ID

2+| *Paket*

|Paket erstellen
a|
* Paketbestandteile

|Paketbestandteile löschen
a|
* Paketbestandteile löschen

|Paket löschen
a|
* Paket löschen = 1

|====
