= Kampagnen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Kampagne, Gutschein-Kampagne
:position: 72
:url: daten/daten-importieren/sync-typen/elasticSync-kampagnen
:id: YQ1TVBF
:author: team-crm

Diese Seite erläutert die Abgleich- und Zuordnungsfelder, die dir beim Importieren von Gutscheinkampagnen zur Verfügung stehen. Diese Seite dient lediglich als Referenz und setzt voraus, dass du bereits Grundkenntnisse über das <<daten/daten-importieren/ElasticSync#, Import-Tool>> hast.

[#abgleichfelder]
== Abgleichfelder

Für den Abgleich von Gutscheinkampagnen steht dir das folgende Feld zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.

[[tabelle-abgleichfeld-gutschein-codes]]
.Abgleichfeld für den Import von Gutschein-Codes und Kampagnendaten
[cols="1,3"]
|===
|Einstellung |Erläuterung

|Kampagnen-ID
|In welcher Spalte der CSV-Datei werden Kampagnen-IDs aufgelistet? Wähle diese Spalte hier. Diese Option ist sinnvoll, wenn du _bestehende Kampagnendaten aktualisieren_ möchtest. +
Wenn du z.B. neue Kampagnendaten importieren möchtest, lasse dieses Feld leer. Beim Import werden die IDs für die Kampagnen automatisch vergeben.

*_Hintergrund-Info:_* Jede neu angelegte Kampagne erhält automatisch eine ID, die nicht geändert werden kann. Die ID dient zur eindeutigen Kennzeichnung der Kampagne. Weil die ID eindeutig ist, lässt sich damit gut prüfen, ob der importierte Datensatz bereits in plentymarkets vorhanden ist.
|===

[#zuordnungsfelder]
== Zuordnungsfelder

In diesem Kapitel werden Felder erläutert, die für die Zuordnung von Kampagnendaten zur Verfügung stehen. Mithilfe dieser Felder legst du fest, welche _Spalte deiner Datei_ welchem _Datenfeld in deinem System_ entspricht.

[.instruction]
Grundlegende Vorgehensweise:

. *_In deiner CSV-Datei_*: Gib einen zulässigen Importwert in eine Spalte ein.
. *_In plentymarkets_*: Ordne diese Spalte dem passenden Zuordnungsfeld zu.
. *_Nach dem Import_*: Prüfe das Ergebnis im Backend.

[TIP]
.Kein Zuordnungsfeld? Standardwert greift!
====
Wenn du eine bestimmte Information nicht in deine CSV-Datei aufnimmst, d.h. wenn du ein bestimmtes Zuordnungsfeld _nicht verwendest_, dann erhält deine Kampagne den Standardwert.
====

[#kampagne]
=== Kampagne

[#kampagnen-id]
==== Kampagnen-ID

Wie lautet die ID der Kampagne? Gib die ID der Kampagne in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#kampagne-erstellen, *Aufträge » Gutscheine* in der Kampagnenübersicht>>.

'''

[#externe-id]
==== Externe ID

'''

[#name]
==== Name

Wie lautet der Name der Kampagne? Gib den Namen in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#kampagne-erstellen, *Aufträge » Gutscheine* in der Kampagnenübersicht>>.

'''

[#artikel-ueber-preisportale]
==== Artikel über Preisportale

Möchtest du, dass Gutscheine auch für Artikel über Preisportale gelten? Dies bedeutet, dass die Artikel gleichzeitig auf anderen Marktplätzen angeboten werden.

[TIP]
Preisportale sind alle Herkünfte > 1. Das heißt, neben Preisportalen sind auch Marktplätze und Plattformen inbegriffen. Die Herkünfte *Manuelle Anlage* (Herkunft 0) und *Webshop* (Herkunft 1) sind nicht betroffen.

*_Standardwert:_* `0`

[[table-mapping-campaign-items-price-comparison-portals]]
[cols="1,1"]
|===

|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Die Gutscheine innerhalb der Kampagne sind _nicht_ für Preisportale gültig.

|`1`
|Die Gutscheine innerhalb der Kampagne sind für Preisportale gültig.

|===


Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-artikel-preisportale, *Aufträge » Gutscheine* in der Kampagnenübersicht und in der Kampagne im Bereich *Filter*>>.


'''


[#inkl-versandkosten]
==== Inkl. Versandkosten

Sollen die Versandkosten im Rabattwert eingeschlossen werden?

*_Standardwert:_* `0`

[[table-mapping-campaign-including-shipping-costs]]
[cols="1,1"]
|===

|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Versandkosten werden _nicht_ im Rabattwert eingeschlossen.

|`1`
|Versandkosten werden im Rabattwert eingeschlossen.

|===


Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagne im Bereich *Gutschein*>>.

'''

[#enddatum]
==== Enddatum

Wann endet deine Kampagne? Gib das Datum inklusive Zeitstempel in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Datum mit Zeitstempel

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-enddatum, *Aufträge » Gutscheine* in der Kampagnenübersicht und in der Kampagne im Bereich *Gültigkeiten*>>.


*_Beispiel:_* `2020-12-31 12:00:00`

'''

[#startdatum]
==== Startdatum

Wann startet deine Kampagne? Gib das Datum inklusive Zeitstempel in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Datum mit Zeitstempel

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-startdatum, *Aufträge » Gutscheine* in der Kampagnenübersicht und in der Kampagne im Bereich *Gültigkeiten*>>.


*_Beispiel:_* `2021-01-31 12:00:00`

'''

[#mindestbestellwert]
==== Mindestbestellwert

Möchtest du einen Mindestbestellwert für das Einlösen des Gutscheins definieren? Dieser Wert muss erreicht werden, damit der Gutschein eingelöst werden kann.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-mindestbestellwert, *Aufträge » Gutscheine* in der Kampagnenübersicht und in der Kampagne im Bereich *Kampagne*>>.


'''

[#code-gueltigkeit-in-wochen]
==== Code-Gültigkeit in Wochen

Wie lange sollen die Gutschein-Codes innerhalb der Kampagne gültig sein? Gib eine Zahl in Wochen in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-code-gueltigkeiten-wochen, *Aufträge » Gutscheine* in der Kampagne im Tab *Einstellungen* im Bereich *Gültigkeiten*>>.

*_Beispiel:_* Gib `8` ein, wenn die Gutschein-Codes 8 Wochen lang gültig sein sollen.

'''


[#code-zuweisung]
==== Code-Zuweisung

Möchtest du neue Codes erzeugen oder vorhandene Codes benutzen?

[TIP]
Die Code-Zuweisung steht nur für den <<#gutscheintyp, Gutscheintyp>> *Voucher* zur Verfügung.

// man kann neue erzeugen oder vorhandene benutzen. Import vermutlich mit 1 und 0? steht 1 für neu erzeugen und 0 für vorhandene Codes nutzen?
// wo ist das Ergebnis im Backend?

'''

[#code-laenge]
==== Code-Länge

Aus wie vielen Zeichen sollen deine Codes bestehen? Du kannst aus 4 verschiedenen Werten wählen: 6, 16, 24 oder 32 Zeichen sind möglich.

*_Standardwert:_*
// gibt es einen Standardwert?

*_Zulässige Importwerte:_* 6, 16, 24, 32

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-code-laenge, *Aufträge » Gutscheine* in der Kampagne im Bereich *Gutschein*>>.

'''

[#nutzung]
==== Nutzung

Möchtest du, dass die Gutscheine in deiner Kampagne nur für Einzelbestellungen, nur für Abonnements oder sowohl für Einzelbestellungen als auch für Abonnements genutzt werden können? Gib die Daten in deine CSV-Datei ein.

*_Standardwert:_*
// gibt es einen Standardwert?

// IDs für die zulässigen Importwerte müssen unbedingt geprüft werden.

[[table-mapping-campaign-usage]]
[cols="1,1"]
|===

|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Gutschein kann für Einzelbestellungen und Abonnements genutzt werden.

|`1`
|Gutschein kann _nur_ für Einzelbestellungen genutzt werden.

|`2`
|Gutschein kann _nur_ für Abonnements genutzt werden.

|===

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-nutzung, *Aufträge » Gutscheine* in der Kampagne im Bereich *Kampagne*>>.

'''

[#konzept]
==== Konzept

Möchtest du für deine Kampagne einen Gutschein-Code erzeugen, der mehrmals einlösbar ist oder möchtest du einzelne Gutschein-Codes erzeugen, die nur einmal einlösbar sind? Gib die Daten in deine CSV-Datei ein.

// welchen wert muss man hier eingeben?



'''

[#einloesungen]
==== Einlösungen
////
Mehrere Einlösungen pro Kunde = Ein Kunde kann den Gutscheinbetrag mehrmals abrufen.

Eine Einlösung pro Kunde = Ein Gutschein kann nur einmal pro Kunde vollständig oder in Teilbeträgen abgerufen werden.

Einlösung, bis Wert aufgebraucht ist = Der gesamte Betrag kann insgesamt nur einmal abgerufen werden. Der Gutschein kann nicht durch mehrere Kunden eingelöst werden.

Eine einzige Einlösung = Nur ein Einlösungsvorgang ist möglich.
////

'''

[#rabattart]
==== Rabattart

Welche Rabattart hat dein Gutschein?

Wenn du als <<#gutscheinart, Gutscheinart>> einen Aktionsgutschein wählst, stehen dir die folgenden Rabattarten zur Verfügung:

* Festbetrag
* Prozentwert
* Stück
* Versand

Wenn du als <<#gutscheinart, Gutscheinart>> einen Mehrzweckgutschein wählst, steht dir die Rabattart *Festbetrag* zur Verfügung.

// Standardwert?
// Zulässige Importwerte?

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattart, *Aufträge » Gutscheine* in der Kampagne im Bereich *Gutschein*>>.

'''

[#gutscheinart]
==== Gutscheinart

// text ergänzen

'''

[#gutscheintyp]
==== Gutscheintyp

Welchen Gutscheintyp verkaufst du? Gib den Gutscheintyp in deine CSV-Datei ein.

[TIP]
Gutscheine werden im Webshop eingelöst. Voucher werden nicht im Webshop, sondern bei Drittanbietern, z.B. in der Hotelbranche, eingelöst.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Text

// ergebnis des imports

'''

[#beschreibung]
==== Beschreibung

Möchtest du eine Beschreibung für deine Kampagne eingeben? Gib die Beschreibung in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine##intable-gutscheinkampagne-beschreibung, *Aufträge » Gutscheine* in der Kampagne im Bereich *Kampagne*>>.

'''

[#rabattwert]
==== Rabattwert

Gib den Rabattwert des Gutscheins innerhalb der Kampagne in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagnenübersicht und in der Kampagne im Bereich *Gutschein*>>.

'''

[#artikel]
==== Artikel

'''

[#kategorien]
==== Kategorien

'''

[#mandanten-shops]
==== Mandanten (Shops)

Welcher Mandant (Shop) soll die Gutscheine deiner Kampagne einlösen können? Gib die ID des Mandanten in deine CSV-Datei ein.

// wenn mehrere IDs, dann kommasepariert eingeben?

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagne im Bereich *Filter*>>.

'''

[#kundenklassen]
==== Kundenklassen

Welche Kundenklasse soll die Gutscheine deiner Kampagne einlösen können? Gib die ID der Kundenklasse in deine CSV-Datei ein.

// wenn mehrere IDs, dann kommasepariert eingeben?

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagne im Bereich *Filter*>>.

'''

[#datensatz-loeschen]
==== Datensatz löschen

Möchtest du die Kampagne löschen?

*_Standardwert:_* `0`

[[table-mapping-campaign-delete-data-record]]
[cols="1,1"]
|===

|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Datensatz wird  _nicht_ gelöscht

|`1`
|Datensatz wird gelöscht.

|===
