= Eigenschaften: Auswahlwerte
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Eigenschaft, Eigenschaften, Auswahl, Mehrfachauswahl, Auswahlwert, Auswahlwerte, Auswahl-Eigenschaft, Auswahl-Eigenschaften, Auswahleigenschaft, Auswahleigenschaften
:position: 45
:url: daten/daten-importieren/sync-typen/elasticSync-eigenschaften-auswahlwerte
:id: M1OB20C
:author: team-item

////
zuletzt bearbeitet 25.05.2021
////

Hast du Eigenschaften vom Typ *Auswahl* oder *Mehrfachauswahl*?
Das Besondere an diesen beiden Eigenschafts-Typen ist, dass sie einzelne _Werte_ haben, die zur _Auswahl_ stehen.
Solche Auswahlwerte können manuell erstellt oder importiert werden.
Darum geht es auf dieser Handbuchseite.

////
Funktioniert auch für Multi-Select.

Es war bisher nicht möglich, irgendwelche Auswahlwerte für die Eigenschaft selbst zu importieren und das haben wir damit erschlagen.
Man muss die Eigenschaften vorab anlegen und dann im Anschluss die Auswahlwerte mit diesem Import

Bisher war es nur begrenzt möglich, Eigenschaftswerte sowie Übersetzungen zu importieren.
Es wäre schwierig gewesen, das im bestehenden Typ "Eigenschaft" zu integrieren. Deswegen wurde es in einem eigenen Typ "Eigenschaft: Auswahlwerte" ausgelagert.

Es gibt verschiedene Abgleichfelder.
Auswahl-ID oder Auswahlname mit der entsprechende Sprache.
Zusätzlich kann man Eigenschaft-ID oder Name mit in den Abgleich rein nehmen.
Eine Einschränkung: der Auswahlname ist nur als Abgleich möglich, wenn auch ein Eigenschaft-Identifier mit angegeben wird.
Da es möglich ist, dass der selbe Auswahlname für verschiedene Eigenschaften hinterlegt ist.
So können wir keine eindeutige Erkennung vornehmen.

In die Zuordnungsoptionen gibt es verschiedene Felder.
Zum Beispiel die Position oder die Name und Beschreibung in verschiedene Sprachen.
#Frage - Position: kommt das in die neue UI? Denn zur Zeit kann man ja keine Position im Backend hinterlegen#

#Frage - Löschen#: fallen die Optionen im Import-Typ "Eigenschaft" weg?

#Frage#: Wozu sollte man die Eigenschafts-ID importieren? Es geht als Zuordnungsfeld
////

//optional - add extra sentences between the brackets in einleitung-weitere-info if you want to have further info in your introduction
:einleitung-daten: pass:quotes[Auswahlwerten]
:einleitung-weitere-info: pass:quotes[]
:abgleich-tabelle: <<table-matching-fields-property-selection-values>>
:abgleich-daten: pass:quotes[Auswahlwerten]
:zuordnung-daten: pass:quotes[Auswahlwerten]
:zuordnung-standardwert: pass:quotes[dein Auswahlwert]

include::./_textblocks/einleitung.adoc[]

[IMPORTANT]
.Voraussetzungen
====
##Text schön formulieren##

Man muss die Eigenschaften vorab anlegen und dann im Anschluss die Auswahlwerte mit diesem Import
====

[#100]
== Abgleichfelder

include::./_textblocks/abgleich.adoc[]

[[table-matching-fields-property-selection-values]]
.Abgleichfelder für Auswahlwerte
[cols="1,3"]
|====
|Abgleichfeld |Erläuterung

| *Auswahl-ID*
|In welcher Spalte der CSV-Datei werden Auswahlwert-IDs aufgelistet?
Wähle diese Spalte hier.
Diese Option ist sinnvoll, wenn du _bestehende Auswahlwerte aktualisieren_ möchtest.

*_Hintergrund-Info_*: Jeder neu angelegte Auswahlwert erhält automatisch eine ID, die nicht geändert werden kann.
Die ID dient zur eindeutigen Kennzeichnung des Auswahlwerts.
Da die ID eindeutig ist, lässt sich damit gut prüfen, ob der importierte Datensatz bereits in plentymarkets vorhanden ist.

| *Auswahlname*
|In welcher Spalte der CSV-Datei ist der Name des Auswahlwerts aufgeführt?
Wähle diese Spalte hier.
Diese Option ist sinnvoll, wenn du _neue Auswahlwerte erstellen_ möchtest.

*_Zusätzliche Einstellung_*:
#Text schön formulieren#

Auswahlname funktioniert nur in Kombination mit entweder Eigenschafts ID oder Eigenschaftsname.

Aus der zweiten Dropdown-Liste die Sprache wählen.

| *Eigenschaft-ID*
|
#anders formulieren - nach das, was unter Auswahlname steht#

In welcher Spalte der CSV-Datei werden Eigenschaft-IDs aufgelistet?
Wähle diese Spalte hier.
Diese Option ist sinnvoll, wenn du _bestehende Eigenschaften aktualisieren_ möchtest.

*_Hintergrund-Info_*: Jede neu angelegte Eigenschaft erhält automatisch eine ID, die nicht geändert werden kann.
Die ID dient zur eindeutigen Kennzeichnung der Eigenschaft.
Da die ID eindeutig ist, lässt sich damit gut prüfen, ob der importierte Datensatz bereits in plentymarkets vorhanden ist.

| *Eigenschaftsname*
|
#anders formulieren - nach das, was unter Auswahlname steht#

In welcher Spalte der CSV-Datei ist der Name der Eigenschaft aufgeführt?
Wähle diese Spalte hier.
Diese Option ist sinnvoll, wenn du _neue Eigenschaften erstellen_ möchtest.

Aus der zweiten Dropdown-Liste die Sprache wählen.

|====

[#200]
== Zuordnungsfelder

include::./_textblocks/zuordnung.adoc[]

[#300]
=== Auswahlwerte

[#300]
==== Eigenschaft-ID

#wozu wird das verwendet?#

'''
[#300]
==== Position

#haben Auswahlwerte tatsächlich eine Position? Ist noch nicht in die UI#

Welcher Auswahlwert soll als erste, zweite, dritte, usw. angezeigt werden?
Gib eine Positionsnummer in die CSV-Datei ein.
Hat der Auswahl-Eigenschaft mehrere Werte, dann werden die Werte aufsteigend nach Positionsnummer dargestellt.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Numerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/eigenschaften#1250, Einrichtung » Einstellungen » Eigenschaften » Gruppen » Eingabefeld: Position>>

'''
[#300]
==== Name

icon:warning[role="red"] [red]#Pflichtwert# für neue Auswahlwerte

Gib den Namen des Auswahlwerts in die CSV-Datei ein.

Hinterlegt dann den Namen in der Systemsprache.
Wenn du weitere Sprachen hinzufügen willst, dann verwende *Name von Auswahlwerten / Name*.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

[TIP]
Stelle mithilfe der Dropdown-Liste auch die Sprache ein.

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/eigenschaften#700, Einrichtung » Einstellungen » Eigenschaften » Konfiguration » Eingabefeld: Name>>

'''
[#300]
==== Wert löschen

Möchtest du den Auswahlwert löschen?

*_Standardwert_*: `0`

[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Auswahlwert wird _nicht_ gelöscht.

|`1`
|Auswahlwert wird gelöscht.
|====

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/eigenschaften#760, Einrichtung » Einstellungen » Eigenschaften » Konfiguration » Werte>>


Löschen erwartet immer eine 0/1.

'''
[#400]
=== Name von Auswahlwerten

Namen müssen natürlich einer Sprache zugeordnet werden

[#300]
==== ID

'''
[#300]
==== Name

icon:warning[role="red"] [red]#Pflichtwert# für neue Auswahlwerte

Gib den Namen des Auswahlwerts in die CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

[TIP]
Stelle mithilfe der Dropdown-Liste auch die Sprache ein.

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/eigenschaften#700, Einrichtung » Einstellungen » Eigenschaften » Konfiguration » Eingabefeld: Name>>

'''
[#300]
==== Beschreibung

Gib eine Beschreibung des Auswahlwerts in die CSV-Datei ein.
Wenn du die Beschreibung in mehreren Sprachen speichern willst, dann füge das Feld einmal pro Sprache hinzu.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

[TIP]
Stelle mithilfe der Dropdown-Liste auch die Sprache ein.

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/eigenschaften#700, Einrichtung » Einstellungen » Eigenschaften » Konfiguration » Eingabefeld: Beschreibung>>

'''
[#300]
==== Namen löschen

Möchtest du den Auswahlwert löschen?

*_Standardwert_*: `0`

[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Auswahlwert wird _nicht_ gelöscht.

|`1`
|Auswahlwert wird gelöscht.
|====

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/eigenschaften#760, Einrichtung » Einstellungen » Eigenschaften » Konfiguration » Werte>>


Zum Löschen eines Namens muss die ID mit angegeben werden.
