= Hersteller
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Hersteller importieren, Importieren Hersteller, Hersteller Import, Hersteller-Import, Import Hersteller
:position: 70
:url: daten/daten-importieren/sync-typen/elasticSync-hersteller
:id: 0WCHQHL
:author: team-item

//optional - add extra sentences between the brackets in einleitung-weitere-info if you want to have further info in your introduction
:einleitung-daten: pass:quotes[Herstellerdatensätzen]
:einleitung-weitere-info: pass:quotes[]
:abgleich-tabelle: <<table-matching-fields-manufacturers>>
:abgleich-daten: pass:quotes[Herstellerdaten]
:zuordnung-daten: pass:quotes[Herstellerdaten]
:zuordnung-standardwert: pass:quotes[dein Herstellerdatensatz]

include::./_textblocks/einleitung.adoc[]

////
[TIP]
.Praxisbeispiel: Neue Herstellerdatensätze importieren
====
Stell dir mal vor, du bist ganz neu bei plentymarkets und möchtest alle deine Herstellerdaten auf einmal importieren. Wie geht so etwas? Wirf einen Blick auf ##<<daten/daten-importieren/elasticsync-best-practices/best-practices-elasticsync-kategorien#, dieses praktische Beispiel>>##, welches dich Schritt für Schritt durch den Prozess führt.
====
////

[#10]
== Abgleichfelder

include::./_textblocks/abgleich.adoc[]

[[table-matching-fields-manufacturers]]
.Abgleichfelder für den Import von Herstellerdaten
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Hersteller-ID*
|In welcher Spalte der CSV-Datei werden Hersteller-IDs aufgelistet? Wähle diese Spalte hier.
Diese Option ist sinnvoll, wenn du _bestehende Herstellerdatensätze aktualisieren_ möchtest.

*_Hintergrund-Info_*: Jeder neu angelegte Hersteller erhält automatisch eine ID, die nicht geändert werden kann.
Die ID dient zur eindeutigen Kennzeichnung des Herstellers.
Da die ID eindeutig ist, lässt sich damit gut prüfen, ob der importierte Datensatz bereits in plentymarkets vorhanden ist.

| *Herstellername*
|In welcher Spalte der CSV-Datei wird der Name des Herstellers aufgeführt? Wähle diese Spalte hier.
Diese Option ist sinnvoll, wenn du _neue Herstellerdatensätze erstellen_ möchtest.

| *Externer Herstellername*
|In welcher Spalte der CSV-Datei wird der externe Herstellername aufgeführt? Wähle diese Spalte hier.
|====

[#20]
== Zuordnungsfelder

include::./_textblocks/zuordnung.adoc[]

[#30]
=== Hersteller

[#40]
==== Name

icon:warning[role="red"] [red]#Pflichtwert# für neue Herstellerdatensätze

Gib den internen Namen des Herstellers in die CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Name>>

'''
[#50]
==== Externer Name

Gib den externen Namen des Herstellers in die CSV-Datei ein.
Wenn du später deine Artikeldaten an Marktplätze überträgst, wird dieser externe Herstellername mitgeliefert.
Falls kein externer Herstellername existiert, wird stattdessen der interne Name verwendet.
Der externe Name wird auch zu <<webshop/webshop-einrichten/extras/findologic#, FINDOLOGIC>> übertragen und für die Suche indexiert.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Externer Name>>

'''
[#60]
==== Logo-URL

Gib die URL zum Logo des Herstellers in die CSV-Datei ein.
Die URL darf bis zu 2.000 Zeichen umfassen.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Logo-URL>>

'''
[#70]
==== Homepage

Gib die URL zur Homepage des Herstellers in die CSV-Datei ein.
Die URL darf bis zu 2.000 Zeichen umfassen.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Homepage>>

'''
[#80]
==== Straße

Gib die Adressdaten des Herstellers in die CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Straße>>

'''
[#90]
==== Haus-Nr.

Gib die Adressdaten des Herstellers in die CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Haus-Nr.>>

'''
[#100]
==== PLZ

Gib die Adressdaten des Herstellers in die CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: PLZ>>

'''
[#110]
==== Ort

Gib die Adressdaten des Herstellers in die CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Ort>>

'''
[#120]
==== Telefonnummer

Gib die Telefonnummer des Herstellers in die CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Telefonnummer>>

'''
[#130]
==== Faxnummer

Gib die Faxnummer des Herstellers in die CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Faxnummer>>

'''
[#140]
==== E-Mail

Gib die E-Mail-Adresse des Herstellers in die CSV-Datei ein.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: E-Mail>>

'''
[#150]
==== Land

Gib die passende <<daten/interne-IDs#20, interne Länder-ID>> in die CSV-Datei ein.
Das heißt, die plentymarkets ID für das Land.

*_Standardwert_*: `Unbekannt`

*_Zulässige Importwerte_*: Numerisch (interne Länder-IDs)

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Dropdown-Liste: Land>>

'''
[#160]
==== Pixmania-ID

Gib die Hersteller-ID des Marktplatzes in die CSV-Datei ein.
Die Hersteller-ID erhältst du beim Einrichten des Marktplatzes.

*_Standardwert_*: `0`

*_Zulässige Importwerte_*: Numerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: PIXmania-ID>>

'''
[#170]
==== Neckermann.at Enterprise-ID

Gib die Hersteller-ID des Marktplatzes in die CSV-Datei ein.
Die Hersteller-ID erhältst du beim Einrichten des Marktplatzes.

*_Standardwert_*: `0`

*_Zulässige Importwerte_*: Numerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Neckermann.at Enterprise-ID>>

'''
[#180]
==== La Redoute-ID

Gib die Hersteller-ID des Marktplatzes in die CSV-Datei ein.
Die Hersteller-ID erhältst du beim Einrichten des Marktplatzes.

*_Standardwert_*: `0`

*_Zulässige Importwerte_*: Numerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: La Redoute-ID>>

'''
[#190]
==== Position

Gib eine Positionsnummer für den Hersteller in die CSV-Datei ein.
Lässt du dieses Feld leer, dann wird automatisch die Positionsnummer 0 vergeben.

*_Standardwert_*: `0`

*_Zulässige Importwerte_*: Numerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Position>>

'''
[#200]
==== Kommentar

Gib einen optionalen Kommentar über den Hersteller in die CSV-Datei ein.
Dies ist ein interner Kommentar, d.h. er ist nur in deinem plentymarkets System sichtbar.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Kommentar>>

'''
[#210]
==== Hersteller löschen

Möchtest du den Herstellerdatensatz löschen?

*_Standardwert_*: `0`

[[table-mapping-attributes-delete-attribute]]
[cols="1,1"]
|====
|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|Hersteller wird _nicht_ gelöscht

|`1`
|Hersteller wird gelöscht
|====

'''
[#220]
=== Hersteller (extern)

[#230]
==== Wert

Gib die Hersteller-ID des Marktplatzes Netto Estores oder Cdiscount.com in die CSV-Datei ein.
Die Hersteller-ID erhältst du beim Einrichten des Marktplatzes.

*_Standardwert_*: Kein Standardwert

*_Zulässige Importwerte_*: Numerisch

[TIP]
Stelle mithilfe der Dropdown-Liste ein, ob sich die ID auf Netto Estores oder Cdiscount.com bezieht.

Das Ergebnis des Imports findest du im Backend im Menü: <<artikel/einstellungen/hersteller#100, Einrichtung » Artikel » Hersteller » Tab: Einstellungen » Eingabefeld: Netto Estores-ID oder Cdiscount.com-ID>>
