= Kampagnen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Kampagne, Gutschein-Kampagne
:position: 72
:url: daten/daten-importieren/sync-typen/elasticSync-kampagnen
:id: YQ1TVBF
:author: team-crm

Diese Seite erläutert die Abgleich- und Zuordnungsfelder, die dir beim Importieren von Gutscheinkampagnen zur Verfügung stehen. Diese Seite dient lediglich als Referenz und setzt voraus, dass du bereits Grundkenntnisse über das <<daten/daten-importieren/ElasticSync#, Import-Tool>> hast.

[#abgleichfelder]
== Abgleichfelder

Für den Abgleich von Gutscheinkampagnen steht dir das folgende Feld zur Verfügung. Anhand des gewählten Abgleichfelds wird geprüft, ob der importierte Datensatz in plentymarkets vorhanden ist.


[[tabelle-abgleichfeld-gutschein-codes]]
.Abgleichfeld für den Import von Gutschein-Codes und Kampagnendaten
[cols="1,3"]
|===
|Einstellung |Erläuterung

|Kampagnen-ID
|In welcher Spalte der CSV-Datei werden Kampagnen-IDs aufgelistet? Wähle diese Spalte hier. Diese Option ist sinnvoll, wenn du _bestehende Kampagnendaten aktualisieren_ möchtest. +
Wenn du z.B. neue Kampagnendaten importieren möchtest, lasse dieses Feld leer. Beim Import werden die IDs für die Kampagnen automatisch vergeben.

*_Hintergrund-Info:_* Jede neu angelegte Kampagne erhält automatisch eine ID, die nicht geändert werden kann. Die ID dient zur eindeutigen Kennzeichnung der Kampagne. Weil die ID eindeutig ist, lässt sich damit gut prüfen, ob der importierte Datensatz bereits in plentymarkets vorhanden ist.
|===

[#zuordnungsfelder]
== Zuordnungsfelder

In diesem Kapitel werden Felder erläutert, die für die Zuordnung von Kampagnendaten zur Verfügung stehen. Mithilfe dieser Felder legst du fest, welche _Spalte deiner Datei_ welchem _Datenfeld in deinem System_ entspricht.

[.instruction]
Grundlegende Vorgehensweise:

. *_In deiner CSV-Datei_*: Gib einen zulässigen Importwert in eine Spalte ein.
. *_In plentymarkets_*: Ordne diese Spalte dem passenden Zuordnungsfeld zu.
. *_Nach dem Import_*: Prüfe das Ergebnis im Backend.

[TIP]
.Kein Zuordnungsfeld? Standardwert greift!
====
Wenn du eine bestimmte Information nicht in deine CSV-Datei aufnimmst, d.h. wenn du ein bestimmtes Zuordnungsfeld _nicht verwendest_, dann erhält deine Kampagne den Standardwert.
====

[#kampagne]
=== Kampagne

[#kampagnen-id]
==== Kampagnen-ID

Wie lautet die ID der Kampagne? Gib die ID der Kampagne in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Numerisch (interne ID)

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#kampagne-erstellen, *Aufträge » Gutscheine* in der Kampagnenübersicht>>.

'''

[#externe-id]
==== Externe ID

[#name]
==== Name

Wie lautet der Name der Kampagne? Gib den Namen in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Alphanumerisch

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#kampagne-erstellen, *Aufträge » Gutscheine* in der Kampagnenübersicht>>.

'''

[#artikel-ueber-preisportale]
==== Artikel über Preisportale

Möchtest du, dass Gutscheine auch für Artikel über Preisportale gelten? Dies bedeutet, dass die Artikel gleichzeitig auf anderen Marktplätzen angeboten werden.

[TIP]
Preisportale sind alle Herkünfte > 1. Das heißt, neben Preisportalen sind auch Marktplätze und Plattformen inbegriffen. Die Herkünfte *Manuelle Anlage* (Herkunft 0) und *Webshop* (Herkunft 1) sind nicht betroffen.

*_Standardwert:_* `0`

[[tabelle-zuordnung-kontakte-typ]]
[cols="1,1"]
|===

|Zulässige Importwerte in CSV-Datei |Ergebnis im Backend

|`0`
|*Nicht erlauben* = Die Gutscheine innerhalb der Kampagne gelten _nicht_ für Preisportale.

|`1`
|*Erlauben* = Die Gutscheine innerhalb der Kampagne gelten für Preisportale.

|===
// prüfen, ob das stimmt und ob es funktioniert mit 0 und 1. oder aber mit ja und nein.

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagnenübersicht und in der Kampagne im Bereich *Filter*>>.

// Link anpassen?

'''


[#inkl-versandkosten]
==== Inkl. Versandkosten

Sollen die Versandkosten im Rabattwert eingeschlossen werden?

[#enddatum]
==== Enddatum

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagnenübersicht und in der Kampagne im Bereich *Gültigkeiten*>>.

// Link anpassen?

'''

[#startdatum]
==== Startdatum

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagnenübersicht und in der Kampagne im Bereich *Gültigkeiten*>>.

// Link anpassen?

'''

[#mindestbestellwert]
==== Mindestbestellwert

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagne im Bereich *Kampagne*>>.

// Link anpassen?

'''

[#code-gueltigkeit-in-wochen]
==== Code-Gültigkeit in Wochen

Wie lange sollen die Gutschein-Codes innerhalb der Kampagne gültig sein? Gib eine Zahl in Wochen in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagne im Tab *Einstellungen* im Bereich *Gültigkeiten*>>.

// Link prüfen

*_Beispiel:_* Gib 8 ein, wenn die Gutschein-Codes innerhalb der Kampagne 8 Wochen lang gültig sein sollen.

'''


[#code-zuweisung]
==== Code-Zuweisung

[#code-laenge]
==== Code-Länge

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagne im Bereich *Gutschein*>>.

// Link anpassen?

'''

[#nutzung]
==== Nutzung

[#konzept]
==== Konzept

[#einloesungen]
==== Einlösungen

[#rabattart]
==== Rabattart

Welche Rabattart hat dein Gutschein?

Wenn du als Gutscheinart einen Aktionsgutschein wählst, stehen dir die folgenden Rabattarten zur Verfügung:

// verlinken auf das Wort Gutscheinart auf dieser Seite

* Festbetrag
* Prozentwert
* Stück
* Versand

Wenn du als Gutscheinart einen Mehrzweckgutschein wählst, steht dir die Rabattart *Festbetrag* zur Verfügung.

// Standardwert?
// Zulässige Importwerte?

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagne im Bereich *Gutschein*>>.

// Link anpassen?

'''

[#gutscheinart]
==== Gutscheinart

[#gutscheintyp]
==== Gutscheintyp

[#beschreibung]
==== Beschreibung

[#rabattwert]
==== Rabattwert

Gib den Rabattwert des Gutscheins innerhalb der Kampagne in deine CSV-Datei ein.

*_Standardwert:_* kein Standardwert

*_Zulässige Importwerte:_* Numerisch

Das Ergebnis des Imports findest du im Backend im Menü <<auftraege/gutscheine#intable-gutscheinkampagne-rabattwert, *Aufträge » Gutscheine* in der Kampagnenübersicht und in der Kampagne im Bereich *Gutschein*>>.

'''

[#artikel]
==== Artikel

[#kategorien]
==== Kategorien

[#mandanten-shops]
==== Mandanten (Shops)

[#kundenklassen]
==== Kundenklassen

[#datensatz-loeschen]
==== Datensatz löschen
