= idealo einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: idealo, idealo Direktkauf, Direktkauf, Marktplatz, Preisvergleich
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz idealo Direktkauf in deinem plentymarkets System ein.
:position: 10
:url: maerkte/idealo/idealo-einrichten

Auf dieser Handbuchseite findest du Informationen zur Einrichtung des Preisvergleichportals und Marktplatzes idealo in plentymarkets. Du erfährst, wie du die Schnittstelle einrichtest, deine Artikel zu idealo exportierst und Verkaufspreise festlegst. +

[.subhead]
idealo Preisvergleich und idealo Direktkauf

Mit plentymarkets können sowohl der idealo Preisvergleich als auch idealo Direktkauf genutzt werden. Mit idealo Direktkauf können Kund*innen deine Produkte direkt bei idealo kaufen, ohne in deinen Webshop zu wechseln. +

Du benötigst das idealoDE-Plugin, um den idealo Preisvergleich und idealo Direktkauf nutzen zu können.

[#100]
== Bei idealo registrieren

Bevor du idealo in plentymarkets einrichtest, musst du dich bei link:https://partner.idealo.com/de/[idealo^] registrieren.

////
=== Authentifizierung bei idealo durchführen

Um plentymarkets Zugriff auf Ihr idealo-Konto zu erlauben, müssen Sie bei idealo eine Authentifizierung durchführen. Dadurch wird der Datenaustausch zwischen idealo und plentymarkets ermöglicht.

[.instruction]
Authentifizierung bei idealo durchführen:

. Melden Sie sich bei idealo mit Ihren idealo-Zugangsdaten an.
. Öffnen Sie das Menü *Mein idealo » Einstellungen*.
. Klicken Sie auf *API Clients*.
. Klicken Sie im Bereich *Partner Web Service 2.0* auf *Neuen API Client erstellen*. +
→ Die API-Credentials bestehend aus Client-ID und Client-Passwort werden erstellt und in einem neuen Fenster angezeigt.

Damit plentymarkets auf Ihr idealo-Konto zugreifen kann, geben Sie Client-ID und Client-Passwort in Ihrem plentymarkets System ein. Sie benötigen dafür das link:https://marketplace.plentymarkets.com/plugins/channels/preisportale/elasticexportidealode_4723[idealoDE-Plugin^], welches Sie im plentyMarketplace erhalten.

[.instruction]
API-Credentials in plentymarkets eingeben:

. Öffnen Sie das Menü *System » Systemeinstellungen » Märkte » idealo » Konfiguration » Prozesse*.
. Geben Sie *Client-ID* und *Client-Passwort* ein, wie von idealo erhalten.
. *Speichern* Sie die Einstellungen. +
→ Ein Token wird generiert, der plentymarkets Zugriff auf idealo erlaubt.
////

[#150]
== idealoDE-Plugin installieren

Daten werden über den Elastischen Export automatisch zu idealo übertragen. Damit du Artikeldaten automatisch an idealo übertragen kannst, installiere zunächst das Plugin link:https://marketplace.plentymarkets.com/plugins/markets/ElasticExport_4763[Elastischer Export^] und das link:https://marketplace.plentymarkets.com/plugins/markets/ElasticExportIdealoDE_4723[idealoDE-Plugin^] aus dem link:https://marketplace.plentymarkets.com/plugins/markets[plentyMarketplace^]. +

Die Installation des Plugins ist sowohl für den idealo Preisvergleich als auch für idealo Direktkauf erforderlich. +

//und Preise und Bestände automatisch mit idealo abgeglichen werden//

Die Installation des idealoDE-Plugins stellt folgende Prozesse bereit:

* automatische Datenübertragung zu idealo über den elastischen Export
//* automatischer Preis- und Bestandsabgleich//

[#200]
== idealo in plentymarkets einrichten

//Auftragsimport aktivieren//

[IMPORTANT]
.idealo Produkt-CSV prüfen
====
Zurzeit sind in plentymarkets nicht alle Spalten der idealo Produkt-CSV verfügbar. Prüfe vor der Einrichtung, ob du Produktspalten benötigst, die in plentymarkets noch nicht verfügbar sind. In diesem Fall ist die Einrichtung von idealo noch nicht möglich. +
Eine Übersicht der in plentymarkets verfügbaren Spalten erhältst du im link:https://marketplace.plentymarkets.com/plugins/channels/preisportale/elasticexportidealode_4723[idealo-Plugin User Guide^].
====

Nimm die folgenden Einstellungen in plentymarkets vor, um den automatischen stündlichen Auftragsimport von idealo zu aktivieren. Diese Einstellung ist sowohl für den idealo Preisvergleich als auch für idealo Direktkauf erforderlich.

[.instruction]
Auftragsimport aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Märkte » idealo*.
. Setze ein Häkchen bei *Automatischen Datenaustausch aktivieren*.
. Gib den API-Schlüssel ein, wie von idealo erhalten.
. *Speichere* die Einstellungen.

//Die Anbindung von idealo stellt folgende automatisierte Prozesse bereit:

//* stündlicher Auftragsabgleich//

[#250]
== idealo Preisvergleich: Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit dem idealo Preisvergleich verknüpfen kannst, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft *idealo* aktiviert werden. +

[.instruction]
Auftragsherkunft für idealo Preisvergleich aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setze bei *idealo* ein Häkchen.
. *Speichere* die Einstellungen.

Wenn du *idealo Direktkauf* nutzen möchtest, aktiviere zusätzlich die Auftragsherkunft *idealo Direktkauf* wie im Kapitel <<idealo Direktkauf einrichten, idealo Direktkauf einrichten>> beschrieben.

[#300]
== idealo Preisvergleich: Artikelverfügbarkeit einstellen

Artikel, die du auf idealo verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden. Stelle die Artikelverfügbarkeit für idealo ein wie im Folgenden beschrieben.

[.instruction]
Artikelverfügbarkeit für idealo Preisvergleich einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *idealo*.
. Aktiviere die Option *Web-API*.
. Klicke auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* die Einstellungen.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden. +

Wenn du *idealo Direktkauf* nutzen möchtest, aktiviere im Bereich *Märkte* zusätzlich die Option *idealo Direktkauf* wie im Kapitel <<idealo Direktkauf einrichten, idealo Direktkauf einrichten>> beschrieben.

[#400]
== idealo Preisvergleich und idealo Direktkauf: Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft idealo einen Verkaufspreis festzulegen. Dieser Preis wird auf idealo angezeigt und ist für den idealo Preisvergleich und idealo Direktkauf gültig.

[.instruction]
Verkaufspreis für idealo festlegen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
. Setze ein Häkchen bei der Herkunft *idealo*.
. *Speichere* die Einstellungen.

[#500]
== idealo Preisvergleich und idealo Direktkauf: SKU manuell festlegen

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *idealo*.
//. Wähle unter *Konto* das idealo-Konto. Dies ist erforderlich, wenn du die idealo-Plugin-Version 2.0 nutzt, damit deine SKUs dem Konto zugeordnet werden können. +
//→ Wähle *Keine Konto-Zuordnung*, wenn du die idealo-Plugin-Version 1.0 nutzt.
. Gib die SKU ein.
. Klicke auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

[#600]
== idealo Preisvergleich und idealo Direktkauf: Artikelexport einrichten

Artikel werden über den elastischen Export mit dem Datenformat IdealoDE zu idealo exportiert. Dafür müssen zuvor die Plugins *ElasticExport* und *ElasticExportIdealoDE* installiert worden sein. Lege zunächst das Datenformat IdealoDE an und übermittele im Anschluss die URL zu idealo. +

Die Einrichtung des Artikelexports ist sowohl für den idealo Preisvergleich als auch für idealo Direktkauf erforderlich.

[.instruction]
Artikelexport einrichten:

. Öffne das Menü *Daten » Elastischer Export*.
. Klicke auf *Neuer Export*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-artikelexport>>.
. Nimm die weiteren Einstellungen für Artikelfilter und Formateinstellungen vor. Beachte dazu die Erläuterungen in Tabelle 2 auf der Handbuchseite <<daten/daten-exportieren/elastischer-export#300, Elastischer Export>>.
. *Speichere* die Einstellungen. +
→ Eine ID für das Exportformat wird vergeben und das Exportformat erscheint in der Übersicht *Exporte*.

[[einstellungen-artikelexport]]
.Einstellungen für Artikelexport
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

|*Name*
|Name eingeben. Unter diesem Namen erscheint das Exportformat in der Übersicht im Tab *Exporte*.

|*Typ*
|Typ *Artikel* aus der Dropdown-Liste wählen.

|*Format*
|Format *IdealoDE* aus der Dropdown-Liste wählen.

|*Limit*
|Zahl eingeben. Wenn mehr als 10000 Datensätze an idealo übertragen werden sollen, wird die Ausgabedatei für 24 Stunden nicht noch einmal neu generiert, um Ressourcen zu sparen.

|*Bereitstellung*
|*URL* wählen.

|*Token*, +
*URL*
|Wenn unter *Bereitstellung* die Option *URL* gewählt wurde, auf *Token generieren* klicken. Der Token wird dann automatisch eingetragen. Die URL wird automatisch eingetragen, wenn unter *Token* der Token generiert wurde. Diese URL an idealo übergeben, damit die Artikel exportiert werden.
|====

[#625]
== idealo Direktkauf einrichten

Mit idealo Direktkauf können Kund*innen deine Produkte direkt bei idealo kaufen, ohne in deinen Webshop zu wechseln. In den folgenden Kapiteln wird erklärt, welche Einstellungen du vornehmen musst, um idealo Direktkauf in plentymarkets nutzen zu können. +

Aktiviere die Auftragsherkunft *idealo Direktkauf* und stelle die Artikelverfügbarkeit für *idealo Direktkauf* ein, um idealo Direktkauf nutzen zu können.

[.instruction]
Auftragsherkunft für idealo Direktkauf aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setze ein Häkchen bei *idealo Direktkauf*.
. *Speichere* die Einstellungen.

Wenn du die Auftragsherkunft *idealo Direktkauf* aktivierst, wird in der über den Elastischen Export generierten Datei die Spalte *checkout_approved* auf *true* gesetzt.

[.instruction]
Artikelverfügbarkeit für idealo Direktkauf einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *idealo Direktkauf*.
. Stelle sicher, dass die Option *Web-API* aktiviert ist.
. Klicke auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* die Einstellungen.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

[#650]
==  idealo Direktkauf: Zahlungsart *idealo Direktkauf* aktivieren

Damit Zahlungen für Aufträge von idealo Direktkauf durchgeführt und in deinem plentymarkets System angezeigt werden, aktiviere die Zahlungsart *idealo Direktkauf*.

[.instruction]
idealo-Zahlungsart aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *DE > idealo*.
. Wähle die idealo-Zahlungsart. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<einstellungen-zahlungsart>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* die Einstellungen.

[[einstellungen-zahlungsart]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Sprache*
| Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
| Name eintragen, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
| Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eintragen.

|*Infoseite (Extern)*
| Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eintragen.

|*Lieferländer*
| Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in deinem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
| Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standard-Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
| Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
| Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eintragen. *Wichtig*: Nicht in beide Felder einen Wert eintragen. +
Weitere Informationen findest du auf der Handbuchseite <<basics/statistik/statistiken-verwalten, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Grundeinstellungen>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » Systemeinstellungen » CRM » Kundenklassen* aktivieren oder deaktivieren Sie *erlaubte Zahlungsarten*. +
Weitere Informationen findest du im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[IMPORTANT]
.Zahlungsart PayPal
====
Wenn du PayPal als Zahlungsart anbietest, muss die Zahlungsart PayPal zwingend in deinem plentymarkets System hinterlegt und eingerichtet sein, damit die Zahlung korrekt importiert und dem Auftrag zugeordnet werden kann.
====

[#660]
== idealo Direktkauf: Merkmale erstellen

Mit <<artikel/artikel-verwalten#480, Merkmalen>> verknüpfst du bestimmte Eigenschaften, die du für die Einrichtung des Marktplatzes idealo Direktkauf benötigst, mit deinen Artikeln. Mit Merkmalen überträgst du Artikeleigenschaften, Versandarten und Gebühren an idealo Direktkauf.

[IMPORTANT]
.Merkmale können nur mit Plugin-Version 2.0 verwendet werden
====
Die Merkmale *DeliveryComment*, *DepositFee*, *DisposalPrice*, *EnergyClass*, *FreeReturnDays*, *Gender*, *Material* und *Replica* können verwendet werden, sobald die idealo-Plugin-Version 2.0 verfügbar und in deinem plentymarkets System installiert ist.
====

[#665]
=== Merkmal für Material und Zielgruppe/Geschlecht erstellen

Mit den Merkmalen *Material* und *Gender* überträgst du Informationen zu Material und Zielgruppe bzw. Geschlecht an idealo Direktkauf. +

Im Folgenden wird beschrieben, wie du das Merkmal *Material* erstellst. Erstelle das Merkmal *Gender* auf die gleiche Weise, wähle jedoch den Merkmaltyp *Text*.

[.instruction]
Merkmal für Material einrichten:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *Material*.
. *Speichere* die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[#675]
=== Merkmal für Versandarten erstellen

Wenn du idealo Direktkauf nutzt, findet der Verkauf direkt bei idealo statt und du musst Informationen zur Versandart an idealo Direktkauf übergeben. Versendest du deine Artikel mit einem Paketdienst, einer Spedition, oder per Download, wird diese Pflichtinformation mit einem Merkmal angegeben und an idealo Direktkauf übergeben. Bei der Versandart Spedition wird beim Verkauf des Artikels die Telefonnummer des Käufers zur Abstimmung eines Liefertermins mit dem beauftragten Speditionsunternehmen erfragt. +

Gehe wie im Folgenden beschrieben vor, um das Merkmal *FulfillmentType* anzulegen, mit dem du angibst, ob du die Versandart *Spedition*, *Paketdienst* oder *Download* verwendest.

[.instruction]
Merkmal für Versandart erstellen:

. Öffne das Menü <<artikel/artikel-verwalten#480, System » Systemeinstellungen » Artikel » Merkmale » Tab: Neues Merkmal>>.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *FulfillmentType*. +
→ Eine Dropdown-Liste erscheint.
. Wähle je nach Versandart einen Wert aus der Dropdown-Liste. Die Werte *Spedition*, *Paketdienst* und *Download* sind verfügbar.
. *Speichere* die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[.subhead]
Weitere Merkmale für Versandarten

Für Artikel mit der Versandart Spedition kann die zusätzliche Dienstleistung *Zwei-Mann-Lieferung bis zum Aufstellort* und *Altgeräteabholung* als Merkmal an idealo Direktkauf übergeben werden. Die Altgeräteabholung kann nur in Kombination mit der Zwei-Mann-Lieferung übergeben werden. Das heißt, du musst sowohl das Merkmal *Zwei-Mann-Lieferung* (*twoManHandlingPrice*) als auch das Merkmal *Altgeräteabholung* (*DisposalPrice*) anlegen und beide mit dem Artikel verknüpfen. Wähle in beiden Fällen als Merkmaltyp *Kommazahl*. Gib den Aufpreis am Artikel für die zusätzliche Dienstleistung mit zwei Dezimalstellen und mit Punkt als Dezimaltrenner (19.99) im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* ein.

[#676]
=== Merkmal für Kommentar zur Lieferung erstellen

Mit dem Merkmal *DeliveryComment* werden weitere Informationen zur Lieferung übermittelt. +

Gehe wie im Folgenden beschrieben vor, um das Merkmal *DeliveryComment* zu erstellen.

[.instruction]
Merkmal für Kommentar zur Lieferung erstellen:

. Öffne das Menü <<artikel/artikel-verwalten#480, System » Systemeinstellungen » Artikel » Merkmale » Tab: Neues Merkmal>>.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *Text* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *DeliveryComment*.
. *Speichere* die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[#680]
=== Merkmal für Energieeffizienzklasse erstellen

Mit dem Merkmal *EnergyClass* überträgst du Informationen zur Energieeffizienzklasse an idealo Direktkauf. +

Gehe wie im Folgenden beschrieben vor, um das Merkmal *EnergyClass* zu erstellen.

[.instruction]
Merkmal für Energieeffizienzklasse einrichten:

. Öffne das Menü <<artikel/artikel-verwalten#480, System » Systemeinstellungen » Artikel » Merkmale » Tab: Neues Merkmal>>.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *EnergyClass*. +
→ Eine Dropdown-Liste erscheint.
. Wähle je nach Energieeffizienzklasse einen Wert aus der Dropdown-Liste.
. *Speichere* die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[#685]
=== Merkmal für kostenlose Rückgabe erstellen

Mit dem Merkmal *FreeReturnDays* überträgst du Informationen zur kostenlosen Rückgabefrist, d.h. die Frist, innerhalb der ein Artikel kostenlos zurückgegeben werden kann, an idealo Direktkauf. +

Gehe wie im Folgenden beschrieben vor, um das Merkmal *FreeReturnDays* zu erstellen.

[.instruction]
Merkmal für kostenlose Rückgabefrist einrichten:

. Öffne das Menü <<artikel/artikel-verwalten#480, System » Systemeinstellungen » Artikel » Merkmale » Tab: Neues Merkmal>>.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *ganze Zahl* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *FreeReturnDays*.
. *Speichere* die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst anschließend das Merkmal mit dem Artikel.

[#690]
=== Merkmal für Pfand erstellen

Mit dem Merkmal *DepositFee* überträgst du Informationen zum Pfand an idealo Direktkauf. Dieses Merkmal wird benötigt, wenn für einen Artikel Pfand gezahlt werden muss. +

Gehe wie im Folgenden beschrieben vor, um das Merkmal *DepositFee* zu erstellen.

[.instruction]
Merkmal für Pfand einrichten:

. Öffne das Menü <<artikel/artikel-verwalten#480, System » Systemeinstellungen » Artikel » Merkmale » Tab: Neues Merkmal>>.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *Kommazahl* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *DepositFee*.
. *Speichere* die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[#695]
=== Merkmal für Replika erstellen

Mit dem Merkmal *Replica* gibst du an, ob es sich bei dem Artikel um eine Replika handelt. +

Gehe wie im Folgenden beschrieben vor, um das Merkmal *Replica* zu erstellen.

[.instruction]
Merkmal für Replika einrichten:

. Öffne das Menü <<artikel/artikel-verwalten#480, System » Systemeinstellungen » Artikel » Merkmale » Tab: Neues Merkmal>>.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *Replica*.
. *Speichere* die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[#700]
== idealo Direktkauf: Auftragsbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um nach Eingang eines Auftrags automatisch eine Auftragsbestätigung an idealo zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-auftragsbestätigung-idealo>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-auftragsbestätigung-idealo>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-auftragsbestätigung-idealo]]
.Ereignisaktion zum automatischen Senden von Auftragsbestätigungen an idealo
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsanlage: Neuer Auftrag*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Auftrag &gt; Auftragsbestätigung an idealo senden*
|
|====

[#800]
== idealo Direktkauf: Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um automatisch eine Versandbestätigung an idealo zu senden, nachdem ein Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-versandbestätigung-idealo>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-versandbestätigung-idealo>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-versandbestätigung-idealo]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an idealo
[cols="1,3,3"]
|====
|Einstellung |Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Versand &gt; Versandbestätigung an idealo senden*
|
|====

[#850]
== idealo Direktkauf: Retouren automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um idealo automatisch über Retouren zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-retouren-idealo>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-retouren-idealo>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-retouren-idealo]]
.Ereignisaktion zum automatischen Senden von Retouren an idealo
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Retoure &gt; Retoure an idealo senden*
|
|====

[#900]
== idealo Direktkauf: Stornierungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um idealo automatisch über Stornierungen zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<ereignisaktion-stornierungen-idealo>>.
. *Speichere* die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<ereignisaktion-stornierungen-idealo>> vor.
. Wähle einen *Grund* für die Stornierung.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[ereignisaktion-stornierungen-idealo]]
.Ereignisaktion zum automatischen Senden von Stornierungen an idealo
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Statuswechsel: [8] Storniert*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Auftrag &gt; Stornierung an idealo senden*
|
|====

[#1000]
== API-Log abrufen

Im Menü *Daten » API-Log* findest du eine Historie über Vorgänge, die über die idealo-Schnittstelle ausgeführt wurden. Das Format *idealoDirektkauf* steht dir für idealo zur Verfügung.

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle das Format *idealoDirektkauf* aus der Dropdown-Liste *Vorgang*.
. Wähle ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wähle die Anzahl der Ergebnisse pro Seite.
. Klicke auf *Suchen*, um die Ergebnisse anzuzeigen.
