= idealo einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: idealo, idealo Direktkauf, Direktkauf, Marktplatz, Preisvergleich
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz idealo Direktkauf in deinem plentymarkets System ein.
:position: 10
:url: maerkte/idealo/idealo-einrichten
:id: JFWN4QY

Auf dieser Handbuchseite findest du Informationen zur Einrichtung des Preisvergleichportals und Marktplatzes idealo in plentymarkets. Du erfährst, wie du die Schnittstelle einrichtest, deine Artikel zu idealo exportierst und Verkaufspreise festlegst. +

[.subhead]
Über idealo

Im Jahr 2000 mit der Mission gestartet, Nutzern zu helfen, richtige Kaufentscheidungen zu treffen, zählt idealo mit 50.000 Händlern und rund 18 Millionen Nutzern pro Monat zu den relevantesten deutschen E-Commerce-Websites.

Mit idealo Direktkauf bietet idealo einen starken Vertriebskanal. Der "Zum Kauf"-Button ermöglicht es Nutzern, das Produkt direkt über eine vollintegrierte Checkout-Funktion über idealo zu bestellen. Vertragspartner sind dabei stets die Händler selbst, die auch wie gewohnt das Fulfillment übernehmen.

[.subhead]
idealo Preisvergleich und idealo Direktkauf

Mit plentymarkets können sowohl der idealo Preisvergleich als auch idealo Direktkauf genutzt werden. Mit idealo Direktkauf können Kund*innen deine Produkte direkt bei idealo kaufen, ohne in deinen Webshop zu wechseln.


== Bei idealo registrieren

Um idealo in plentymarkets einrichten zu können, registriere dich zunächst bei idealo als Händler.

[IMPORTANT]
.Artikeldatenexport
====
Kläre vor der Einrichtung in plentymarkets mit idealo, wie Artikeldaten übertragen werden sollen (Erstellung, Aktualisierung und Löschen von Artikeln auf idealo). Artikeldaten können mit einer CSV-Datei oder per API (PWS 2.0-Schnittstelle) exportiert werden. +
Wenn du PWS 2.0 für den Artikelexport nutzt, werden Artikel einmal täglich auf idealo erstellt und gelöscht. Preise und Bestände werden alle 15 Minuten aktualisiert. +
Wenn du Artikel mit einer CSV-Datei über den elastischen Export zu idealo überträgst, können Artikel über eine URL von idealo abgerufen werden. +
Wie du die verschiedenen Arten der Datenübertragung in plentymarkets einrichtest, ist im Kapitel <<Artikelexport einrichten, Artikelexport einrichten>> beschrieben.
====

=== Plugin Elastischer Export installieren

Um das idealo-Plugin nutzen zu können, musst du zunächst das Plugin link:https://marketplace.plentymarkets.com/plugins/sales/marktplaetze/elasticexport_4763[Elastischer Export^] in deinem plentymarkets System installieren. Das Plugin erhältst du im link:https://marketplace.plentymarkets.com/[plentyMarketplace^].


== idealo-Assistent durchlaufen

Durchlaufe zunächst den Assistenten *idealo Grundeinstellungen* im Menü *Einrichtung » Assistenten » Omni-Channel*, um die Grundeinstellungen für idealo in plentymarkets vorzunehmen. Mit diesem Assistenten richtest du dein idealo-Konto in plentymarkets ein und nimmst Einstellungen für den Artikeldatenxport zu idealo und Auftragsimport von idealo Direktkauf vor. +

[IMPORTANT]
.Artikelexport per API
====
Wenn du deine Artikel über PWS 2.0 exportierst, ist es zwingend erforderlich, den *idealo Grundeinstellungen*-Assistenten zu durchlaufen, da der automatische Artikelexport nur im idealo-Assistenten eingestellt werden kann.
====


== idealo Preisvergleich und idealo Direktkauf nutzen

Je nachdem, ob du nur den idealo Preisvergleich nutzen möchtest oder deinen Kunden auch die Möglichkeit bieten möchtest, deine Artikel direkt bei idealo zu kaufen, ohne in deinen Webshop wechseln zu müssen, sind unterschiedliche Einstellungen nötig. Im Folgenden erhältst du eine Übersicht zu den nötigen Einstellungen für idealo Direktkauf.

→ *Einstellungen für idealo Direktkauf:*

- *Grundeinstellungen:* Durchlaufe im Menü *Einrichtung » Assistenten » Omni-Channel* den Assistenten *idealo Grundeinstellungen*.
- *Artikelexport:* Richte den <<Artikelexport per API, automatischen Artikelexport>> oder den <<Artikelexport mit elastischem Export, Artikelexport per CSV-Datei>> ein, je nachdem, wie du Artikel zu idealo übertragen möchtest.
- *Auftragsherkunft:* Aktiviere im Menü *Einrichtung » Aufträge » Auftragsherkunft* zusätzlich zur Auftragsherkunft *idealo* auch die <<Auftragsherkunft aktivieren, Auftragsherkunft>> *idealo Direktkauf*.
- *Artikelverfügbarkeit:* Aktiviere im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* im Bereich *Märkte* zusätzlich zur Option *idealo* auch die <<Artikelverfügbarkeit einstellen, Verfügbarkeit>> *idealo Direktkauf*.
- *Verkaufspreis:* Richte einen <<Verkaufspreis festlegen, Verkaufspreis>> ein.
- *SKU:* Füge marktplatzspezifische <<SKU manuell festlegen, SKUs>> hinzu, wenn gewünscht.
- *Zahlungsart:* Richte die <<Zahlungsart idealo Direktkauf aktivieren, Zahlungsart>> *idealo Direktkauf* ein.
- *Merkmale:* Erstelle <<Merkmale erstellen, Merkmale>> für idealo Direktkauf. Mit Merkmalen überträgst du Artikeleigenschaften, Versandarten und Gebühren an idealo Direktkauf.
- *Ereignisaktionen:* Richte <<Ereignisaktionen einrichten, Ereignisaktionen>> ein, um Änderungen am Auftragsstatus automatisch an idealo Direktkauf zu senden.


== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit dem idealo Preisvergleich verknüpfen kannst, muss im Menü *Einrichtung » Aufträge » Auftragsherkunft* die Auftragsherkunft *idealo* aktiviert werden.

[.instruction]
Auftragsherkunft für idealo Preisvergleich aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Setze ein Häkchen bei *idealo*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Wenn du idealo Direktkauf nutzen möchtest, aktiviere zusätzlich die Auftragsherkunft *idealo Direktkauf*. Wenn du die Auftragsherkunft *idealo Direktkauf* aktivierst, wird in der über den elastischen Export generierten CSV-Datei die Spalte *checkout_approved* auf *true* gesetzt.


== Artikelverfügbarkeit einstellen

Artikel, die du auf dem idealo-Preisvergleichsportal anbieten möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden. Stelle die Artikelverfügbarkeit für idealo ein wie im Folgenden beschrieben.

[.instruction]
Artikelverfügbarkeit für idealo Preisvergleich einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *idealo*.
. Aktiviere die Option *Web-API*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

Wenn du idealo Direktkauf nutzen möchtest, aktiviere im Bereich *Märkte* zusätzlich die Option *idealo Direktkauf*.


== Verkaufspreis festlegen

Gehe wie im Folgenden beschrieben vor, um für die Auftragsherkunft idealo einen Verkaufspreis festzulegen. Dieser Preis wird auf idealo angezeigt und ist für den idealo Preisvergleich und idealo Direktkauf gültig.

[.instruction]
Verkaufspreis für idealo festlegen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*. +
→ Wenn du noch keinen Verkaufspreis angelegt hast, klicke auf *Neu*, um einen Verkaufspreis zu erstellen.
. Setze ein Häkchen bei der Herkunft *idealo*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Mindestpreis
====
Wenn du für die idealo-Preisspanne einen Mindestpreis angeben möchtest, musst du mindestens zwei Verkaufspreise für idealo festlegen, einen Mindestpreis und einen normalen Verkaufspreis. Außerdem muss der Mindestpreis vom Typ *Aktionspreis* sein und mit der Herkunft *idealo Direktkauf* verknüpft werden. +
Welcher Preis als Mindestpreis für die idealo-Preisspanne an idealo übertragen werden soll, legst du im idealo-Assistenten im Schritt *Artikeldaten* mit der Einstellung *Welcher Preis soll als Mindestpreis an idealo übertragen werden?* fest.
====


== SKU manuell festlegen

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID im Tab Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *idealo*.
. Gib die SKU ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die SKU wird gespeichert und angezeigt.

Wenn du idealo Direktkauf nutzen möchtest, füge zusätzlich SKUs mit der Herkunft *idealo Direktkauf* hinzu.


== Artikelexport einrichten

Artikel werden entweder mit dem automatischen Artikelexport über eine API (PWS 2.0-Schnittstelle) oder mit einer CSV-Datei über den elastischen Export zu idealo übertragen. Je nachdem, welche Art der Datenübertragung du wählst, sind verschiedene Einstellungen notwendig. +

[IMPORTANT]
.Art der Datenübertragung
====
Kläre vor der Einrichtung in plentymarkets mit idealo, wie Artikeldaten übertragen werden sollen.
====

Informationen zu den verschiedenen Arten der Datenübertragung findest du in <<artikelexport-idealo>>.

[[artikelexport-idealo]]
.Datenübertragung bei idealo
[cols="1,3"]
|====
| Artikelexport per API (PWS 2.0) | Artikelexport mit elastischem Export

|Artikeldatenübertragung per Schnittstelle
|Artikeldatenübertragung per CSV-Datei

|tägliche Aktualisierung von Artikeln
|Abruf von Artikeldaten per URL, die bei idealo hinterlegt wird

|Aktualisierung von Preisen alle 15 Minuten
|Intervall, in dem Artikeldaten abgerufen werden, wird von idealo festgelegt

|Aktualisierung von Beständen alle 15 Minuten
|
|====

=== Artikelexport per API (PWS 2.0-Schnittstelle)

Wenn du deine Artikel per Schnittstelle automatisch zu idealo übertragen möchtest, durchlaufe den Assistenten *idealo Grundeinstellungen* im Menü *Einrichtung » Assistenten » Omni-Channel* und aktiviere den automatischen Artikeldatenexport. Für den automatischen Artikelexport sind außerhalb des idealo-Assistenten keine weiteren Einstellungen in plentymarkets nötig. +

Mit dieser Art der Datenübertragung werden Artikel einmal täglich auf idealo erstellt und gelöscht. Preise und Bestände werden alle 15 Minuten aktualisiert.

=== Artikelexport mit elastischem Export

Wenn du Artikel über den elastischen Export zu idealo überträgst, müssen im Menü *Daten » Elastischer Export* Einstellungen vorgenommen werden, um das Exportformat einzurichten. Als Voraussetzung muss das Plugin link:https://marketplace.plentymarkets.com/plugins/sales/marktplaetze/elasticexport_4763[Elastischer Export^] in deinem plentymarkets System installiert sein. Damit idealo deine Artikeldaten abrufen kann, lege zunächst das Datenformat IdealoDE an und hinterlege im Anschluss die URL bei idealo.

Wie du den Artikelexport über den elastischen Export in plentymarkets einrichtest, ist in den folgenden Kapiteln <<Das Format IdealoDE-Plugin in plentymarkets einrichten, Das Format IdealoDE-Plugin in plentymarkets einrichten>> und <<Verfügbare Spalten der Exportdatei, Verfügbare Spalten der Exportdatei>> beschrieben.

==== Das Format IdealoDE-Plugin in plentymarkets einrichten

[TIP]
.Einstellungen nur für elastischen Export relevant
====
Die in diesem Kapitel beschriebenen Einstellungen sind nur notwendig, wenn du Artikel über den elastischen Export zu idealo überträgst.
====

[TIP]
.idealo Produkt-CSV prüfen
====
Zurzeit sind in plentymarkets nicht alle Spalten der idealo Produkt-CSV verfügbar. Prüfe vor der Einrichtung, ob du Produktspalten benötigst, die in plentymarkets noch nicht verfügbar sind. In diesem Fall ist die Einrichtung von idealo zurzeit noch nicht möglich. +
Eine Übersicht der in plentymarkets verfügbaren Spalten erhältst du im Kapitel <<Verfügbare Spalten der Exportdatei, Verfügbare Spalten der Exportdatei>>.
====

Damit deine Artikel mit dem elastischen Export zu idealo übertragen werden können, musst du das Exportformat *IdealoDE* einrichten. Weitere Informationen zum elastischen Export findest du auf der Handbuchseite <<daten/daten-exportieren/elastischer-export#, Elastischer Export>>. Um das Format *IdealoDE* für den elastischen Export nutzen zu können, installiere zunächst das Plugin *Elastischer Export* aus dem plentyMarketplace, wenn noch nicht geschehen.

[.instruction]
Neues Exportformat erstellen:

. Öffne das Menü *Daten » Elastischer Export*.
. Klicke auf *Neuer Export*.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<formateinstellungen-idealo>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Eine ID für das Exportformat *IdealoDE-Plugin* wird vergeben und das Exportformat erscheint in der Übersicht *Exporte*.

In der folgenden Tabelle findest du Hinweise zu den einzelnen Formateinstellungen und empfohlenen Artikelfiltern für das Format *IdealoDE-Plugin*.

[[formateinstellungen-idealo]]
.Formateinstellungen für IdealoDE
[cols="1,3"]
|====
|*Einstellung*  |*Erläuterung*

2+|*Einstellungen*

|*Name*
|Name eingeben. Unter diesem Namen erscheint das Exportformat in der Übersicht im Tab *Exporte*.

|*Typ*
|Typ *Artikel* aus der Dropdown-Liste wählen.

|*Format*
|*IdealoDE-Plugin* wählen.

|*Limit*
|Zahl eingeben. Wenn mehr als 9999 Datensätze an die Preissuchmaschine übertragen werden sollen, wird die Ausgabedatei wird für 24 Stunden nicht noch einmal neu generiert, um Ressourcen zu sparen. Wenn mehr als 9999 Datensätze benötigt werden, muss die Option *Cache-Datei generieren* aktiv sein. +
*Oder:* Wenn du mehr als 9999 Datensätze an idealo übertragen möchtest, kannst du als Alternative auch Version 2.0 des idealo-Plugins installieren.

|*Cache-Datei generieren*
|Häkchen setzen, wenn mehr als 9999 Datensätze an die Preissuchmaschine übertragen werden sollen. Um eine optimale Performance des elastischen Exports zu gewährleisten, darf diese Option bei maximal 20 Exportformaten aktiv sein.

|*Bereitstellung*
|*URL* wählen.

|*Dateiname*
|Der Dateiname muss auf *.csv* oder *.txt* enden, damit idealo die Datei erfolgreich importieren kann.

|*Token, URL*
|Wenn unter *Bereitstellung* die Option *URL* gewählt wurde, auf *Token generieren* klicken. Der Token wird dann automatisch eingetragen. Die URL wird automatisch eingetragen, wenn unter *Token* der Token generiert wurde.

2+|*Artikelfilter*

|*Artikelfilter hinzufügen*
|Artikelfilter aus der Dropdown-Liste wählen und auf *Hinzufügen* klicken. Standardmäßig sind keine Filter voreingestellt. Es ist möglich, alle Artikelfilter aus der Dropdown-Liste nacheinander hinzuzufügen. +
*Varianten* = *Alle übertragen* oder *Nur Hauptvarianten übertragen* wählen. +
*Märkte* = *idealo* wählen. +
*Währung* = Währung wählen. +
*Kategorie* = Aktivieren, damit der Artikel mit Kategorieverknüpfung übertragen wird. Es werden nur Artikel, die dieser Kategorie zugehören, übertragen. +
*Bild* = Aktivieren, damit der Artikel mit Bild übertragen wird. Es werden nur Artikel mit Bildern übertragen. +
*Mandant* = Mandant wählen. +
*Bestand* = Wählen, welche Bestände exportiert werden sollen. +
*Markierung 1 - 2* = Markierung wählen. +
*Hersteller* = Einen, mehrere oder *ALLE* Hersteller wählen. +
*Aktiv* = Nur aktive Varianten werden übertragen.

2+|*Formateinstellugen*

|*Produkt-URL*
|Wählen, ob die URL des Artikels oder der Variante an das Preisportal übertragen wird. Varianten URLs können nur in Kombination mit dem Ceres Webshop übertragen werden.

|*Mandant*
|Mandant wählen. Diese Einstellung wird für den URL-Aufbau verwendet.

|*URL-Parameter*
|Suffix für die Produkt-URL eingeben, wenn dies für den Export erforderlich ist. Die Produkt-URL wird dann um die eingegebene Zeichenkette erweitert, wenn weiter oben die Option *übertragen* für die Produkt-URL aktiviert wurde.

|*Auftragsherkunft*
|Die Auftragsherkunft *Idealo* wählen.

|*Marktplatzkonto*
|Marktplatzkonto aus der Dropdown-Liste wählen. Die Produkt-URL wird um die gewählte Auftragsherkunft erweitert, damit die Verkäufe später analysiert werden können.

|*Sprache*
|Sprache aus der Dropdown-Liste wählen.

|*Artikelname*
|*Name 1*, *Name 2* oder *Name 3* wählen. Die Namen sind im Tab *Texte* eines Artikels gespeichert. Im Feld *Maximale Zeichenlänge (def. Text)* optional eine Zahl eingeben, wenn die Preissuchmaschine eine Begrenzung der Länge des Artikelnamen beim Export vorgibt.

|*Vorschautext*
|Wählen, ob und welcher Text als Vorschautext übertragen werden soll. +
Im Feld *Maximale Zeichenlänge (def. Text)* optional eine Zahl eingeben, wenn die Preissuchmaschine eine Begrenzung der Länge des Vorschautextes beim Export vorgibt. +
Option *HTML-Tags entfernen* aktivieren, damit die HTML-Tags beim Export entfernt werden. +
Im Feld *Erlaubte HTML-Tags, kommagetrennt (def. Text)* optional die HTML-Tags eingeben, die beim Export erlaubt sind. Wenn mehrere Tags eingegeben werden, mit Komma trennen.

|*Beschreibung*
|Wählen, welcher Text als Beschreibungstext übertragen werden soll. +
Im Feld *Maximale Zeichenlänge (def. Text)* optional eine Zahl eingeben, wenn die Preissuchmaschine eine Begrenzung der Länge der Beschreibung beim Export vorgibt. +
Option *HTML-Tags entfernen* aktivieren, damit die HTML-Tags beim Export entfernt werden. +
Im Feld *Erlaubte HTML-Tags, kommagetrennt (def. Text)* optional die HTML-Tags eingeben, die beim Export erlaubt sind. Wenn mehrere Tags eingegeben werden, mit Komma trennen.

|*Zielland*
|Zielland aus der Dropdown-Liste wählen.

|*Barcode*
|ASIN, ISBN oder eine EAN aus der Dropdown-Liste wählen. Der gewählte Barcode muss mit der oben gewählten Auftragsherkunft verknüpft sein. Andernfalls wird der Barcode nicht exportiert.

|*Bild*
|*Position 0* oder *Erstes Bild* wählen, um dieses Bild zu exportieren. +
*Position 0* = Ein Bild mit der Position 0 wird übertragen. +
*Erstes Bild* = Das erste Bild wird übertragen.

|*Bildposition des Energieetiketts*
|Position des Energieetikettes eintragen. Alle Bilder, die als Energieetikette übertragen werden sollen, müssen diese Position haben.

|*Bestandspuffer*
|Der Bestandspuffer für Varianten mit der Beschränkung auf den Netto-Warenbestand.

|*Bestand für Varianten ohne Bestandsbeschränkung*
|Der Bestand für Varianten ohne Bestandsbeschränkung.

|*Bestand für Varianten ohne Bestandsführung*
|Der Bestand für Varianten ohne Bestandsführung.

|*Währung live umrechnen*
|Aktivieren, damit der Preis je nach eingestelltem Lieferland in die Währung des Lieferlandes umgerechnet wird. Der Preis muss für die entsprechende Währung freigegeben sein.

|*Verkaufspreis*
|Brutto- oder Nettopreis aus der Dropdown-Liste wählen.

|*Angebotspreis*
|Diese Option ist für dieses Format nicht relevant.

|*UVP*
|Aktivieren, um den UVP zu übertragen.

|*Versandkosten*
|Im Gegensatz zu anderen Formaten spielt hier die Auswahl einer Zahlungsart keine Rolle. Es werden alle Zahlungsarten der gewählten Konfiguration exportiert. +
Wenn keine Konfiguration gewählt wurde, werden alle Konfigurationen und alle Zahlungsarten exportiert. +
Wenn *Pauschale Versandkosten übertragen* gewählt wurde, wird nur Vorkasse als Zahlungsart übermittelt.

|*MwSt.Hinweis*
|Diese Option ist für dieses Format nicht relevant.

|*Artikelverfügbarkeit*
|Option *überschreiben* aktivieren und in die Felder *1* bis *10*, die die ID der Verfügbarkeit darstellen, Artikelverfügbarkeiten eintragen. Somit werden die Artikelverfügbarkeiten, die im Menü *System » Artikel » Verfügbarkeit* eingestellt wurden, überschrieben.
|====

==== Verfügbare Spalten der Exportdatei

[[spalten-exportdatei]]
.Spalten der Exportdatei
[cols="1,3"]
|====
| Spaltenbezeichnung | Erläuterung

|*article_id*
|*Pflichtfeld* +
Die SKU des Artikels. Bei Artikeln, die für idealo Direktkauf freigegeben wurden, wird hier eine SKU für idealo Direktkauf ausgegeben.

|*deeplink*
|*Pflichtfeld* +
Der URL-Pfad des Artikels abhängig vom gewählten Mandanten in den Formateinstellungen.

|*name*
|*Pflichtfeld* +
Entsprechend der Formateinstellung Artikelname.

|*short_description*
|Entsprechend der Formateinstellung *Vorschautext*.

|*description*
|*Beschränkung*: max. 1000 Zeichen +
Entsprechend der Formateinstellung *Beschreibung*.

|*article_no*
|Die Variantennr. unter *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Einstellungen » Grundeinstellungen*.

|*producer*
|Der Name des Herstellers des Artikels. Der Externe Name unter *Einrichtung » Artikel » Hersteller* wird bevorzugt, wenn vorhanden.

|*model*
|Das Modell unter *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Einstellungen » Grundeinstellungen*.

|*availability*
|*Pflichtfeld* +
Der Name der Artikelverfügbarkeit unter *Einrichtung » Artikel » Verfügbarkeit* oder die Übersetzung gemäß der Formateinstellung *Artikelverfügbarkeit überschreiben*. +
Bei idealo muss die Lieferzeit in Tagen angegeben werden.

|*ean*
|Entsprechend der Formateinstellung *Barcode*.

|*isbn*
|Entsprechend der Formateinstellung *Barcode*.

|*fedas*
|Der Amazon-Produkttyp unter *Artikel » Artikel bearbeiten » Artikel öffnen » Multi-Channel » Amazon*.

|*warranty*
|Aktuell nicht gepflegt.

|*price*
|*Pflichtfeld* +
Der Verkaufspreis der Variante.

|*price_old*
|Der Verkaufspreis vom Typ UVP der Variante, wenn in den Formateinstellungen aktiviert.

|*weight*
|Gewicht brutto in Gramm unter *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Einstellungen » Maße*.

|*category1-6*
|Der Name der Kategorieebene des Kategoriepfads der Standard-Kategorie für den in den Formateinstellungen definierten Mandanten.

|*category_concat*
|Kategoriepfad der Standard-Kategorie für den in den Formateinstellungen definierten Mandanten.

|*image_url_preview*
|URL zu einer für die Vorschau skalierten Version des Bildes gemäß der Formateinstellung *Bild*.

|*image_url*
|*Pflichtfeld* +
URL zu dem Bild gemäß der Formateinstellung *Bild*.

|*base_price*
|Die Grundpreisinformation im Format "Preis / Einheit". (Beispiel: 10,00 EUR / Kilogramm)

|*free_text_field*
|Der Wert eines Merkmals vom Typ Text oder Auswahl mit der Verknüpfung zu idealo.

|*checkoutApproved*
|Wird true gesetzt, wenn entweder die Auftragsherkunft idealo Direktkauf unter *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Verfügbarkeit » Märkte* aktiviert wurde oder ein Merkmal vom Typ *Kein* und der Verknüpfung zum idealo Direktkauf-Merkmal checkoutApproved gesetzt wurde.

|*itemsInStock*
|*Voraussetzung*: checkoutApproved ist true. +
Der Nettowarenbestand der Variante. Bei Artikeln, die nicht auf den Nettowarenbestand beschränkt sind, wird 999 übertragen.

|*fulfillmentType*
|*Voraussetzung*: checkoutApproved ist true. +
Merkmal vom Typ *Kein* und der Verknüpfung zum idealo Direktkauf-Merkmal *FulfillmentType > Spedition*, *FulfillmentType > Paketdienst*, *FulfillmentType > Brief* oder *FulfillmentType > Download*.

|*twoManHandlingPrice*
|*Voraussetzung*: checkoutApproved ist true und fulfillmentType ist Spedition. +
Merkmal vom Typ *Text*, *Auswahl* oder *Kommazahl* und der Verknüpfung zum idealo Direktkauf-Merkmal *twoManHandlingPrice*.

|*disposalPrice*
|*Voraussetzung*: *checkoutApproved* ist *true* und fulfillmentType ist *Spedition*. +
Merkmal vom Typ *Text*, *Auswahl* oder *Kommazahl* und der Verknüpfung zum idealo Direktkauf-Merkmal *disposalPrice*.

|*Zahlungsarten*
|*Pflichtfeld*: (Mindestens eine Zahlungsart) +
Es werden die Zahlungsarten gemäß der Formateinstellung *Versandkosten* in einer eigenen Spalte übermittelt.
|====


== Zahlungsart idealo Direktkauf aktivieren

Damit Zahlungen für Aufträge von idealo Direktkauf durchgeführt und in deinem plentymarkets System angezeigt werden, aktiviere die Zahlungsart *idealo Direktkauf*.

[TIP]
.Zahlungsart nur für idealo Direktkauf
====
Die Zahlungsart *idealo Direktkauf* muss nur aktiviert werden, wenn du idealo Direktkauf nutzt.
====

[.instruction]
idealo-Zahlungsart aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *DE > idealo*.
. Wähle die *idealo-Zahlungsart*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<zahlungsart-idealo>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[zahlungsart-idealo]]
.Einstellungen für idealo-Zahlungsart
[cols="1,3"]
|====
| *Einstellung* | *Erläuterung*

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
|Name eintragen, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eintragen.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eintragen.

|*Lieferländer*
|Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in deinem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standard-Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eintragen. *Wichtig:* Nicht in beide Felder einen Wert eintragen. +
Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklasse erlauben
====
Im Menü *Einrichtung » CRM » Kundenklassen* aktivierst oder deaktivierst du erlaubte Zahlungsarten. +
Weitere Informationen findest du im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[IMPORTANT]
.Zahlungsart PayPal
====
Wenn du PayPal als Zahlungsart anbietest, muss die Zahlungsart PayPal zwingend in deinem plentymarkets System hinterlegt und eingerichtet sein, damit die Zahlung korrekt importiert und dem Auftrag zugeordnet werden kann.
====


== Merkmale erstellen

Mit <<artikel/einstellungen/eigenschaften#100, Merkmalen>> verknüpfst du bestimmte Eigenschaften, die du für die Einrichtung des Marktplatzes idealo Direktkauf benötigst, mit deinen Artikeln. Mit Merkmalen überträgst du Artikeleigenschaften, Versandarten und Gebühren an idealo Direktkauf.

[NOTE]
.Bestimmte Merkmale können nur mit Plugin-Version 2.0 verwendet werden
====
Die Merkmale *DeliveryComment*, *DepositFee*, *DisposalPrice*, *EnergyClass*, *FreeReturnDays*, *Gender*, *Material* und *Replica* können nur verwendet werden, wenn die Plugin-Version 2.0 in deinem plentymarkets System installiert ist. Außerdem können diese Merkmale nur in Verbindung mit dem automatischen Artikelexport (Datenübertragung per Schnittstelle) zu idealo Direktkauf übertragen werden. Den automatischen Artikelexport aktivierst du im idealo-Assistenten im Schritt *Automatische Datenübertragung*. +
Wenn du den automatischen Artikelexport im idealo-Assistenten aktiviert hast, kannst du alle idealo-Merkmale übertragen. +
Wenn du deine Artikel per CSV-Datei mit dem elastischen Export überträgst, kannst du nur das Merkmal *FulfillmentType* verwenden.
====

=== Merkmal für Material und Zielgruppe/Geschlecht erstellen

Mit den Merkmalen Material und Gender überträgst du Informationen zu Material und Zielgruppe bzw. Geschlecht an idealo Direktkauf.

Im Folgenden wird beschrieben, wie du das Merkmal *Material* erstellst. Erstelle das Merkmal *Gender* auf die gleiche Weise, wähle jedoch den Merkmaltyp *Text*.

[.instruction]
Merkmal für Material einrichten:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *Material*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

=== Merkmal für Versandarten erstellen

Wenn du idealo Direktkauf nutzt, findet der Verkauf direkt bei idealo statt und du musst Informationen zur Versandart an idealo Direktkauf übergeben. Versendest du deine Artikel mit einem Paketdienst, einer Spedition, per Brief oder Download, wird diese Pflichtinformation mit einem Merkmal angegeben und an idealo Direktkauf übergeben. Bei der Versandart *Spedition* wird beim Verkauf des Artikels die Telefonnummer des Käufers zur Abstimmung eines Liefertermins mit dem beauftragten Speditionsunternehmen erfragt.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *FulfillmentType* anzulegen, mit dem du angibst, ob du die Versandart *Spedition*, *Paketdienst*, *Brief* oder *Download* verwendest.

[.instruction]
Merkmal für Versandart erstellen:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *FulfillmentType*. +
→ Eine Dropdown-Liste erscheint.
. Wähle je nach Versandart einen Wert aus der Dropdown-Liste. Die Werte *Spedition*, *Paketdienst*, *Brief* und *Download* sind verfügbar.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[.subhead]
Weitere Merkmale für Versandarten

Für Artikel mit der Versandart *Spedition* kann die zusätzliche Dienstleistung *Zwei-Mann-Lieferung bis zum Aufstellort* und *Altgeräteabholung* als Merkmal an idealo Direktkauf übergeben werden. Die Altgeräteabholung kann nur in Kombination mit der Zwei-Mann-Lieferung übergeben werden. Das heißt, du musst sowohl das Merkmal *Zwei-Mann-Lieferung (twoManHandlingPrice)* als auch das Merkmal *Altgeräteabholung (DisposalPrice)* anlegen und beide mit dem Artikel verknüpfen. Wähle in beiden Fällen als Merkmaltyp *Kommazahl*. Gib den Aufpreis am Artikel für die zusätzliche Dienstleistung mit zwei Dezimalstellen und mit Punkt als Dezimaltrenner (19.99) im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* ein.

=== Merkmal für Kommentar zur Lieferung erstellen

Mit dem Merkmal *DeliveryComment* werden weitere Informationen zur Lieferung übermittelt.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *DeliveryComment* zu erstellen.

[.instruction]
Merkmal für Kommentar zur Lieferung erstellen:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *Text* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *DeliveryComment*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

=== Merkmal für Energieeffizienzklasse erstellen

Mit dem Merkmal *EnergyClass* überträgst du Informationen zur Energieeffizienzklasse an idealo Direktkauf.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *EnergyClass* zu erstellen.

[.instruction]
Merkmal für Energieeffizienzklasse einrichten:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *EnergyClass*. +
→ Eine Dropdown-Liste erscheint.
. Wähle je nach Energieeffizienzklasse einen Wert aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

=== Merkmal für kostenlose Rückgabe erstellen

Mit dem Merkmal *FreeReturnDays* überträgst du Informationen zur kostenlosen Rückgabefrist, d.h. die Frist, innerhalb der ein Artikel kostenlos zurückgegeben werden kann, an idealo Direktkauf.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *FreeReturnDays* zu erstellen.

[.instruction]
Merkmal für kostenlose Rückgabefrist einrichten:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *ganze Zahl* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *FreeReturnDays*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst anschließend das Merkmal mit dem Artikel.

=== Merkmal für Pfand erstellen

Mit dem Merkmal *DepositFee* überträgst du Informationen zum Pfand an idealo Direktkauf. Dieses Merkmal wird benötigt, wenn für einen Artikel Pfand gezahlt werden muss.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *DepositFee* zu erstellen.

[.instruction]
Merkmal für Pfand einrichten:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *Kommazahl* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *DepositFee*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

=== Merkmal für Replika erstellen

Mit dem Merkmal *Replica* gibst du an, ob es sich bei dem Artikel um eine Replika handelt.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *Replica* zu erstellen.

[.instruction]
Merkmal für Replika einrichten:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *Replica*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.


== Ereignisaktionen einrichten

Richte Ereignisaktionen ein, um Änderungen am Auftragsstatus automatisch an idealo zu senden. Du kannst mit Ereignisaktionen Auftragsbestätigungen, Versandbestätigungen, Retouren und Stornierungen automatisch an idealo Direktkauf senden.

[TIP]
.Ereignisaktionen für idealo Direktkauf
====
Ereignisaktionen müssen nur eingerichtet werden, wenn du idealo Direktkauf nutzt.
====

=== Auftragsbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um nach Eingang eines Auftrags automatisch eine Auftragsbestätigung an idealo zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<auftragsbestaetigung-idealo>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<auftragsbestaetigung-idealo>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[auftragsbestaetigung-idealo]]
.Ereignisaktion zum automatischen Senden von Auftragsbestätigungen an idealo
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neuer Auftrag*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Auftrag &gt; Auftragsbestätigung an idealo senden*
|
|====

=== Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um automatisch eine Versandbestätigung an idealo zu senden, nachdem ein Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<versandbestaetigung-idealo>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<versandbestaetigung-idealo>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[versandbestaetigung-idealo]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an idealo
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Versand > Versandbestätigung an idealo senden*
|
|====

=== Retouren automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um idealo automatisch über Retouren zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<retouren-idealo>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<retouren-idealo>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[retouren-idealo]]
.Ereignisaktion zum automatischen Senden von Retouren an idealo
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Retoure > Retoure an idealo senden*
|
|====

=== Stornierungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um idealo automatisch über Stornierungen zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<stornierungen-idealo>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<stornierungen-idealo>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[stornierungen-idealo]]
.Ereignisaktion zum automatischen Senden von Stornierungen an idealo
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Statuswechsel: [8] Storniert*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Auftrag: Stornierung an idealo senden*
|
|====


== API-Log abrufen

Im Menü *Daten » API-Log* findest du eine Historie über Vorgänge, die über die idealo-Schnittstelle ausgeführt wurden. Das Format idealoDirektkauf steht dir für idealo zur Verfügung.

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle das Format *idealoDirektkauf* aus der Dropdown-Liste *Vorgang*.
. Wähle ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wähle die Anzahl der Ergebnisse pro Seite.
. Klicke auf *Suchen* (icon:search[role="blue"]), um die Ergebnisse anzuzeigen.
