= Data exchange
:lang: en
include::{includedir}/_header.adoc[]
:position: 90

This area deals with exchanging data in plentymarkets. Data can be exchanged automatically or manually. Use the **<<data-exchange/soap-api#, SOAP API  >>** or sub-menus in the **Data exchange** menu to exchange data between your plentymarkets system and external systems. The SOAP API and REST API can both be used for automatic data exchange. The **Data exchange** menu is used to manually transfer data. **<<basics/data-exchange/api-log#, Log entries  >>** in the API log help you keep track of any data you exchanged.

video::126357396[vimeo]
You can also use the data exchange to quickly and easily make changes and adapt settings within your plentymarkets system. Simply export the data of your items, customers, stocks or orders into a CSV file, make changes to the data and import the file back into the system.

[.row]
====
[.col-md-4]
.Manual data exchange
=====
* <<basics/data-exchange/data-formats#, **Data formats**  >>
* <<basics/data-exchange/exporting-data#, **Exporting data**  >>
* <<basics/data-exchange/importing-data#, **Importing data**  >>
=====

[.col-md-4]
.Interfaces
=====
* <<data-exchange/soap-api#, **SOAP API**  >>
* link:http://showcase.plentymarkets.com/[**REST API**, window="_blank"]
=====

[.col-md-4]
.Viewing protocols
=====
* <<basics/data-exchange/api-log#, **API log**  >>
=====
====
link::/[Back to the overview]

