= GDPR
:lang: en
include::{includedir}/_header.adoc[]
:description: Download an abriged version of the record of processing activities within the software plentymarkets according to GDPR.
:keywords: EU regulation, GDPR, gdpr, general data protection regulation, dsgvo, data protection, personal data, person-related data, record of processing activities, processing directory, processing activities, directory, May 25, processing documentation
:position: 100

This page of the manual includes a download link of an abriged version of the record of processing activities within plentymarkets in accordance with GDPR whose transition period ends on May 25, 2018.

== What is GDPR?

As of May 25, 2018, the link:http://data.consilium.europa.eu/doc/document/ST-5419-2016-INIT/en/pdf[General Data Protection Regulation^] goes into effect throughout Europe and thus replaces all national regulations.

The GDPR applies to all companies operating in the European Union and processing personal data such as names, bank data and address data. It requires companies to organise and document any processes where personal data is processed in line with the GDPR.

== Important notes

Please note that this record only contains the processing activities within the software plentymarkets. You will need to add the names and descriptions of any other processing activities that take place within your company (e.g. payroll accounting or processes within other software programs).

plentymarkets makes no claim to completeness regarding this record. It is intended to be a supplement when creating your own record of processing activities.

Please note that only *plentymarkets 7* systems are GDPR compliant. The plentymarkets 7 online store plugin *Ceres* will be GDPR compliant after the checkbox for consenting to the data transmission to shipping service providers has been added with the release of *version 2.9.0*.

== Download link

Download the document as a supplement to your own record of processing activities link:https://github.com/plentymarkets/template-processing-directory/releases[here^]. This document only describes the processing activities within the software plentymarkets.

== Contract for processing acc. to art. 28 §3 General Data Protection Regulation (GDPR)

On Thursday, 24th of May, 2018, plentymarkets 7 is updated in order to manage the conclusion of contracts for processing according to article 28 § 3 of the General Data Protection Regulation (GDPR) in a digital fashion.
Concluding the contract is done digitally in the *Contracts* (German: *Verträge*) menu. Users with administration rights can access the menu in the plentymarkets 7 Terra backend.
The new entry *Contracts* is located under the first menu item - the red plenty P.
In this area, click on the contract "Vertragsanlage zur Auftragsverarbeitung (DS-GVO) Mai 2018". The contract is only available in German.
You can download the contract document on the following page by clicking the icon in the *Dokument* column.
Enter your name and send the form. This concludes the contract.
This process forgoes the need for concluding the contract by mail, thereby saving time and money.

For further information, please refer to this link:https://forum.plentymarkets.com/t/vertragsanlage-zur-auftragsverarbeitung-i-s-d-art-28-abs-3-datenschutz-grundverordnung-dsgvo/483954[forum thread^].
