= Guestbook
:lang: en
include::{includedir}/_header.adoc[]
:position: 30

The guestbook is a way for your customers to show that they visited your store. Customers can use it to leave a message, give an opinion, make a request etc. Go to **Settings » Client (store) » Standard » Modules » Guestbook** to create and configure guestbooks.

toc::[]
== Creating and configuring a guestbook

You can save the language and layout options of the guestbook in the **Settings » Client (store) » Standard » Modules » Guestbook** menu. You have to create a language before you can configure the guestbook settings. The guestbook settings will be set up and become visible for a specific language and shop. Proceed as described below to set the language and further settings.

[.instruction]
Creating and configuring a guestbook:

. Go to **Settings » Client (store) » Standard » Modules » Guestbook**.
. Click on the **New language** tab.
. Select a language from the drop-down menu.
. **Save** the settings. +
&amp;rarr; The language will be displayed in the **Language** tab.
. Click on the language's **plus icon**.
. Pay attention to the explanations given in table 1 and configure the **Settings** tab as desired.
. **Save** the settings.

[cols="a,a"]
|====
|Setting |Explanation

|**Date format**
|Select the format for displaying the date from the drop-down menu.

|**Time format**
|Select the format for displaying the time from the drop-down menu.

|**Entries per page**
|Select how many entries per page should be displayed in the guestbook. Default setting is 15.

|**Allow BBCode**
|Select whether the simplified markup language BBCode should be permitted for formatting text within the guestbook entries.

|**Allow BBCode $img tag**
|Select whether the simplified markup language BBCode should be permitted for inserting images into the guestbook entries.
|====

__Table 1: guestbook settings__

== Editing or translating identifiers

You can save custom identifiers to replace the default identifiers in the **Identifier** tab. If you want to create a guestbook in a different language, then save your translations here.

== Inserting a guestbook into the design

The guestbook is displayed in the online store with the help of the **$Container_Guestbook** template variable. Insert the template variable where you want the guestbook to appear in a category of the type **Content**.

