= Syntax
:lang: en
// include::{includedir}/_header.adoc[]
:keywords: CMS, Web design, Syntax, Basics
:position: 20

*CMS » Web design*

== Content of this chapter

The following pages provide you with basic information about the structure, coding and syntax of content in your online store. You will learn how various elements are structured and how they can be customized. Most of the structures are already included and configured in the plentymarkets standard design, i.e. the default configuration when you first start your online store. The information on these pages helps you understand and edit these structures. You will need to have a basic understanding of web design to do so. If you are not already familiar with web design, then you should hire an agency to make changes for you.

Pay attention to the following explanations of pages within this chapter and refer to the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design, Editing the web design>> page, which includes additional information about designing your online store.

You need to have in-depth knowledge of HTML and CSS in order to edit the web design. You can also find a wealth of information about HTML and CSS online. For example, at link:http://html.net/[http://html.net/^].

== CMS syntax

There is a unique scripting language used for creating a web design in plentymarkets CMS.

== jQuery

jQuery is a fast and concise JavaScript Library that simplifies HTML document traversing, event handling, animating, and Ajax interactions for rapid web development. For further information, refer to the <<omni-channel/online-store/setting-up-clients/cms#web-design-basic-information-about-syntax-jquery, jQuery>> page of the manual.
