= Tools
:lang: en
// include::{includedir}/_header.adoc[]
:position: 25

*CMS » Web design*

== Content of this page

This chapter explains important tools that you need for working with the *CMS* and other menus in order to design your online strore.

== Editor

plentymarkets comes with an integrated WYSIWYG editor. You can use it to directly edit text and tables in content pages or to apply formatting such as headings, numbering or lists. You see the result immediately when working with this editor. You can also edit the content in the source code. For further information, refer to the <<omni-channel/online-store/setting-up-clients/cms#web-design-tools-editor, Editor>> page of the manual.

== Syntax editor

Apart from the familiar editor and the conventional *text field*, plentymarkets also provides the new *syntax editor* to edit html content such as item descriptions, templates and email templates. Broadly speaking, the syntax editor is a professional alternative to the *text field* because it not only includes syntax highlighting but also further functions that increase your level of comfort and efficiency when editing HTML. For further information, refer to the <<omni-channel/online-store/setting-up-clients/cms#web-design-tools-syntax-editor, Syntax editor>> page of the manual.
