= Locations
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Locations, Accounting, Headquarters
:position: 10

This page of the manual teaches you how to configure locations in the menu **Settings » Client (store) » Select store » Locations**. It is possible to save different accounting information and settings for every location.

== Saving accounting information for each location

In plentymarkets, it is possible to save different <<order-processing/orders/_accounting#, **accounting information**>> for each client and location. In other words, you can manage multiple clients that all have multiple branch offices in different countries. Every client must have at least one location by default. This standard location corresponds to the company's main headquarters. The standard location is the first menu item within the **Locations** menu. Every location is identified by a customisable name.

The location settings are divided into submenus, e.g. **Settings** and <<order-processing/orders/_accounting#, **Accounting**>>. Different accounting settings can be saved for each location.

== Creating a new location

Proceed as described below to create a new location.

[.instruction]
Creating a new location:

. Go to **Settings » Client (store) » Select store » Locations**.
. Move your cursor over the menu item **Locations**. +
→ An arrow will be displayed on the right.
. Click on the **arrow**. +
→ The option **New location** will appear.
. Click on **New location**. +
→ An editing window will open.
. Enter a name for the new location under **Name**.
. Select the new location's **Country** from the drop-down menu.
. Click on the **save icon** to save the settings.

== Settings

Every location has a **Settings** submenu, which you can use to change the location's name or to delete the location altogether. It is not possible to change a location's country once it has been created. This helps prevent errors. If you want to change the country, then you will need to create an entirely new location. It is also necessary to specify which location should be the standard or default location. Generally, this is where the company's main headquarters are located. Open the <<omni-channel/online-store/setting-up-clients#basic-settings, **Basic settings**>> menu and select the country from the **Default location** drop-down menu.

It is only possible to delete a location if there is at least one other location in this menu as well. It is not possible to delete the location that was set as the **Default location** in the menu <<omni-channel/online-store/setting-up-clients#basic-settings, **Basic settings**>>.

[.instruction]
Deleting a location:

. Go to **Settings » Client (store) » Select store » Locations**.
. Open the location that you want to delete and click on the **Settings** submenu.
. Click on the **delete icon**. +
→ Confirm the security question to delete the location.

