= Order process
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Online store, Client, Order process
:position: 60

**plentymarkets » Settings » Client (store) » Standard » Order process » Basic settings**

In this menu, you can configure important settings that relate to the order process in your online store. For example, you can decide which elements should be displayed to store visitors. Additionally, you can decide whether entering specific information should be compulsory or not. As such, e.g. the item condition can be displayed or hidden, even when it has been entered. You can select whether registration for the newsletter should generally apply or should only apply to specific customers or should not be displayed at all, and much more.

==  The order process - handle with care

The order process is a crucial part of any online transaction. As such, it is particularly important that you make sure all your settings in this area are correct and user-friendly. Otherwise, potential buyers might change their minds about ordering from your store at the last minute. Therefore, pay close attention to the information regarding the store order process options in table 1 and seek advice if necessary.

==  Configuring the order process

Configure the settings as described below.

[.instruction]
Configuring the store order process:

.  Go to **Settings » Client (store) » Standard » Order process » Basic settings**.
.  Pay attention to the explanations given in table 1 and carry out the settings as desired.
.  Click on the **save icon** to save the settings.

[cols="a,a"]
|====
| Setting | Explanation

|**Item bundle**
| Define how **<<item/managing-items#920, item bundles >>** should be displayed in the order process: not split up, replaced by basic items or with basic items added to them. +
**Important**: Always use the option **List the item bundle as well as the basic items** for Shopware clients.

|**Standard country of delivery**
| Select the country of delivery for each language. Here, you can choose between the countries of delivery that have been set up under **Settings » Orders » Shipping » Shipping options » Tab: Countries of delivery**. The countries of delivery are assigned based on the language here. In other words, the countries of delivery that were saved with the language **de** will be available for German. The countries that were saved with the language **en** will be available for English. +
The setting is left blank by default.

|**Default shipping method**
| Select the shipping method that should automatically be applied to new orders.

|**Default shipping profile**
| Select the shipping profile that should automatically be applied to new orders.

|**Default payment method**
| Select the payment method that should appear first in your online store.

|**Default customer class**
| Select which customer class should be applied to customers who are not logged into the online store. The settings of this customer class, e.g. whether gross / net prices and discounts are displayed, will apply for these customers. The setting only applies to the selected client (store). As such, it can be set for each client individually. If no customer class is selected, the customer class with the lowest position number is automatically set. For this function to work, at least one customer class must be set up in the <<crm/managing-customer-data#100, **Settings » Customers » Customer classes** >> menu.

|**Unit price**
| Select whether the unit price should be displayed in the order process or not. It is displayed for items that have an entry saved in the **Content** field within the variation tab (= content is larger than zero). +
The **<<item/managing-items#270, unit price >>** is the price based on a standard amount, e.g. per kg or 1000 g. It provides the user with a simple comparison of prices.

|**Payment information**
| Select whether the payment information should be queried in the order process or not.

|**Shipping method**
| Select whether the shipping information should be queried in the order process or not.

|**Motion picture rating information**
| Select whether the motion picture rating information should be displayed in the order process or not.

|**Newsletter registration during order process**
| Select whether **<<crm/sending-newsletters#, registration for the newsletter  >>** should be preselected, should take place depending on the customer's selection or should not be shown at all. +
**Note:** Marking newsletter registration as the default setting is a legal risk. In this case, customers have to remove the check mark if they do not want to be registered for the newsletter. Procure information on the current legal practice or consult a specialized solicitor. +
Newsletter registration in the store, which takes place when the visitor enters his or her own data and confirms the registration, is a legally unobjectionable alternative to the variation that takes place in the order process.

|**Newsletter main folder**
| Select which **e-mail folder** should automatically be linked to a customer's e-mail address when he or she subscribes to a newsletter in the online store.

|**Minimum order value**
| Enter the minimum order value. If the minimum value is not met, then the store visitor will receive a corresponding note. +
The minimum order value applies to the **gross value of items** in an order.

|**Ignore coupon amount when dealing with the minimum order value**
| Select whether coupon amounts should be included in the minimum order value. +
**YES** = Coupon amounts will not be included in the minimum order value. +
**NO** = Coupon amounts will be included in the minimum order value. This makes it easier for customers to reach the minimum value. +
The possibility of reaching the minimum order value easily may encourage customers to make a purchase.

|**Purchaser's IP address**
| Select whether the purchaser's IP address should be saved in the order or not.

|**Combine orders if possible**
| Select whether orders should be combined if possible. +
This function will only combine orders automatically if they have the same referrer and the order statuses are still below status 5, i.e. no incoming payment was booked yet. +
Use the **<<order-processing/orders/managing-sales-orders#changing-order-170, group function >>****Group orders** to manually combine orders after they have passed this status.

|**Permit changes to orders retroactively**
| Select whether the customer should still be allowed to make changes to the order after it has been sent (e.g. changing the item quantity, the payment and delivery method or the invoice and delivery address). +
Customers will only be allowed to go to the my account section and change their **address details** for existing orders if the payment method was activated for the country of the new address.

|**Delivery date information**
| Currently without actual function
////
If you mark an item availability as <strong>active</strong>, then your customers will be able to enter a delivery date for all items that have this availability. This information can be entered during the order process. You can also choose whether it should be mandatory for customers to specify a delivery date. The customer has to enter a delivery date before the item will added to the shopping cart if the entry is set as mandatory. If he or she does not enter a date for mandatory delivery dates an additional message will be displayed to remind him or her to enter a date. Otherwise the item will not be placed in the shopping cart.<br />
If only the option <strong>active</strong> was selected and the customer did not enter a delivery date when adding the item to the shopping cart, then he or she can still do so in the shopping cart by clicking on the <strong>Change delivery date</strong> link and entering a date. However, doing so is not mandatory.<br />
<strong>CMS</strong>: In order for the delivery date to be displayed in the order process, you need to insert the code <strong>&lt; input name=&quot;DeliveryDate&quot; type=&quot;text&quot; / &gt; </strong> into the template <strong>ItemViewSingleItem</strong> between <strong>FormOpen_Order</strong> and <strong>FormClose_Order</strong>.
////

|**External VAT number check**
| The VAT number will be checked if a company was entered as the form of address and a VAT number was saved. The function can be deactivated if you have problems with the external VAT number check.

|**Duplicate check**
| Select whether the e-mail address and street address or only the e-mail address should be checked for duplicates during the customer registration in the order process.
|====

__Table 1: store order process settings__
