= FormatDesigner
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Format, FormatDesigner, Format Designer, Formatdesigner, Export, data fields, data field, create a format, creating a format, editing a format, exporting data
:position: 30
:url: data/exporting-data/FormatDesigner
:id: J8CFXWD
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:nav-alias: Creating data formats with FormatDesigner

include::_textblocks/formatdesigner-export-intro.adoc[]

This page of the manual explains the first step. Here you'll learn how to <<data/exporting-data/FormatDesigner#50, set up the FormatDesigner plugin>>, how to <<data/exporting-data/FormatDesigner#100, create data formats>> and <<data/exporting-data/FormatDesigner#_creating_format_types, which types of data>> you can export.

The second step, i.e. the actual import, is done in the menu *Data » Elastic export*. You can find further information about the second step on the <<data/exporting-data/elastic-export#, elastic export>> page of the manual.

[#50]
== Setting up the plugin

Find the link:https://marketplace.plentymarkets.com/en/plugins/integration/formatdesigner_6483[FormatDesigner plugin on plentyMarketplace^] and add the plugin to your system. Refer to the <<plugins#, plugin chapter>> for basic information about adding plugins to your plentymarkets system.

[TIP]
.Is the plugin up to date?
====
Plugins are constantly being updated and improved. Before you start creating data formats, open the menu *Plugins » Plugin overview » Open plugin set* and make sure you're using the most current version of the plugin.
====

[IMPORTANT]
.FormatDesigner plugin has replaced the ElasticSync plugin
====
Do you still use the ElasticSync plugin to create export formats? This plugin will no longer be updated in the future. Therefore, we recommend that you switch to the FormatDesigner plugin and that you delete the ElasticSync plugin from your plugin set.
====

[#100]
== Creating a format

. Go to *Data » FormatDesigner*.
. Click on *Add format*.
. Enter a unique name.
. Select the desired format and field separator.
. Click on *Save*.

[#110]
== Editing the format

As soon as a format is created or opened, the editing window for the format opens. The available data fields are displayed on the right-hand side. By clicking on a field, this field is added to the left side of the screen. Once a data field has been created, it can be further edited. Once the data field was saved it is added to the export.

[[table-settings-data-fields]]
.Settings for the data fields
[cols="1,3"]
|====
|Setting |Explanation

|Name
|Enter a name for the data format. The name is displayed in the column header of the CSV file.

|Move
|Left of the data field name is a section marked with dots where you can move and position the data fields. Specify the order of the columns of the CSV file by moving the data fields.

|Mapping
|Data fields, e.g. VariationSalesPrice.price, require additional mapping because more than one price may exist for every variation. The mapping allows you to export a specific sales price. To export more than one sales price, you can add the data field to the export format several times and map these fields to different sales prices. For data fields that do not require any additional mapping, the button is deactivated.

|Change value
|Data fields with numeric values can be changed with procedures during the export. As many procedures can be added as desired. These procedures are carried out sequentially and manipulate the value based on the setting selected.

|Remove data field
|The data field is removed from the format.
|====
