= Catalogues
:lang: en
include::{includedir}/_header.adoc[]
:keywords:
:description:
:position: 0
:url: data/exporting-data/managing-catalogues
:id: FHQHFWO
:author: team-plenty-channel

Hi there! You clicked on a direct link to get to this pages. Welcome!

Information on catalogues are now split into two separate pages to make it easier for you to get to grips with this topic:

* *_You want to export plentymarkets data to a document?_*
  ** To do so, you need a catalogue with standard formats. Find out how to create catalogues with standard formats on the <<data/exporting-data/file-export#, Creating standard formats>>.
* *_You want to export item data to markets?_*
  ** To do so, you need a catalogue with marketplace formats. An introduction to marketplace formats lives on the manual page <<data/exporting-data/marketplace-export#, Catalogues: Marketplace export>>
  ** Check out the <<markets#, manual pages for a sales channel>> to find out how to create catalogues for individual markets.

TIP: The following chapters contain information about how to manage your existing catalogue. You can also find this information on the new pages for default formats and marketplace formats. On this current page, the information is only listed again to make sure that any old links from the forum continue to work. The content is the same on all three pages.

'''

[#manage-catalogues]
== Managing catalogues: how to delete, copy, etc.

include::_textblocks/catalogues/catalogues-manage.adoc[]
