= Managing catalogues
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Catalogue, Catalog, Catalogues, Catalogs, catalog templates, catalogue templates, templates, market, markets, sales channel, data sources, target data
:description: The *Data » Catalogues* menu allows you to configure the export of variation data to markets.
:position: 50
:url: data/exporting-data/managing-catalogues
:id: FHQHFWO
:author: team-elasticsync

Use catalogues to export variation data to markets and other sales channels. Currently, you can use catalogues to transfer data to the markets REWE, Etsy, Metro and OTTO Market.

Catalogues are used to prepare variation data for exporting them to a sales channel. On this manual page, you will find information on creating and managing catalogues.

[#10]
== What is a catalogue?

Each sales channel requires different product data. Often, different product information have to be sent to the same sales channel for different product categories (pet food, household items, food, etc.).

Catalogues allow you to customise information regarding your product portfolio to meet the requirements of each sales channel and target audience. You achieve this by mapping the individual data fields of a sales channel to a suitable plentymarkets data source. When your variation data is transferred to the sales channel, the sales channel’s data fields are then filled with the correct plentymarkets data.

Catalogues offer the following advantages:

* The sales channel provides the data structure. As such, you know exactly which variation data is necessary to sell your products on this sales channel.
* You select which variation data you want to publish on each sales channel and for each template. For example, you can use properties to transfer different variation names and descriptions to different sales channels.

[TIP]
.Exporting data? FormatDesigner
====
Catalogues are used to transmit data to sales channels. Catalogue data cannot be exported to a file or any other readable format. Use the <<data/exporting-data/FormatDesigner#, FormatDesigner>> to export data.
====

[#20]
== What is a catalogue template?

A catalogue template provides a framework of the data a sales channel can accept. As such, catalogue templates tell you what data can be transmitted to the sales channel.

A sales channel can offer more than one catalogue template, for example for different product categories (pet food, food, non-food, etc.) or for different languages. Check the documentation to find out which catalogue templates are available for the different sales channels.

[NOTE]
.Could not find a catalogue template?
====
The catalogue templates of some sales channels are loaded into the *Data » Catalogues* menu when you deploy the sales channel’s plugin.
====

[#30]
== Managing variation data using properties

<<item/managing-items#3000, Properties of the Item area>> allow you to save data for variations for which no default data fields are available in the plentymarkets back end. In the following, you will find some examples on how to use properties.

==== Example 1: Diameter information

*Use case:* +
A sales channel allows you to send the *diameter* and the *diameter unit* of your products. By default, you cannot save diameter data in the plentymarkets back end.

*Recommended:* +
<<table-diameter>> shows the recommended settings for sending diameter data to sales channels.

[[table-diameter]]
.Example 1: Diameter information
[cols="1,3"]
|====
|Data field sales channel |Properties in plentymarkets

2+| *Setup » Settings » Properties » Configuration*

|*Diameter unit*
a|* Create the property *Diameter unit*: +
Section: *Item* +
Property type: *Selection*
* Save values, e.g. *cm* and *mm*

|*Diameter*
a|* Create the property *Diameter*: +
Section: *Item* +
Property type: *Decimal number*

2+|*Item » Edit items » Open item » Open variation*

|*Diameter unit*
a|* Open the *Properties* tab.
* Add the property *Diameter unit*.
* Select the unit from the drop-down list.

|*Diameter*
a|* Open the *Properties* tab.
* Add the property *Diameter*.
* Enter the diameter in the unit you selected for *Diameter unit*.

2+|*Data » Catalogues » Open catalogue*

|*Diameter unit*
a|* From the drop-down list *Source*, select the option *Property » Diameter unit*.

|*Diameter*
a|* From the drop-down list *Source*, select the option *Property » Diameter*.
|====


==== Example 2: Brand names

*Use case:* +
The sales channel allows you to transfer the brand name of products. By default, you can save manufacturers but not brand names in the plentymarkets back end.

*Recommended:* +
If the manufacturer names saved in your system are not identical to the products’ brand names, you can manage brand names using properties. <<table-brands>> shows the recommended settings for managing brands to send to sales channels.

[[table-brands]]
.Example 2: Brand information
[cols="1,3"]
|====
|Data field sales channel |Properties in plentymarkets

2+| *Setup » Settings » Properties » Configuration*

|*Brand*
a|* Create the property *Brand*: +
Section: *Item* +
Property type: *Short text*

2+|*Item » Edit items » Open item » Open variation*

|*Brand*
a|* Open the *Texts* tab.
* Add the property *Brand*.
* Enter the brand name.

2+|*Data » Catalogues » Open catalogue*

a|* From the drop-down list *Brand*, select the brand.
a|* From the drop-down list *Source*, select the option *Property » Brand*.
* In the *Value* field, enter the brand name. +
*_Note:_* The brand name of the sales channel is published on the sales channel.
|====

[#40]
== Managing catalogues

To create, edit or delete catalogues, go to *Data » Catalogues*.

[NOTE]
.Could not find a catalogue template?
====
The catalogue templates of some sales channel are loaded into the *Data » Catalogues* menu when you deploy the sales channel’s plugin.
====

[#50]
=== Creating a catalogue

Proceed as described below to create a catalogue.

[.instruction]
Creating a catalogue:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. Click on *Create catalogue* (icon:plus-square[role="green"]).
. Enter a name for the catalogue.
. Select a catalogue template from the drop-down list.
. *Save* (icon:save[role="green"]) the settings. +
→ The catalogue is created. +
→ The catalogue is opened for editing.

The toggle button on the right in the catalogue overview allows you to activate or deactivate a catalogue. To edit the name of a catalogue, go to the settings (icon:cog[role="black"]).

[#60]
=== Mapping data sources

Once you created a catalogue, the catalogue opens. On the left, the sales channel’s data is shown. Fields with an asterisk are mandatory. Further on the right of each data field is a drop-down list. Use these drop-down lists to map one or more plentymarkets data sources to the data fields of the sales channel.

Depending on the product data you want to transfer, you either map a data field or a value. In the upper area, you can map data fields. For example, you select which data field in plentymarkets contains the weight of variations. In the lower section, you can map values. For example, you map the sales channel’s category “Pet food” to your plentymarkets category “Animal food”.

Proceed as described below to map the data fields of the sales channel to a plentymarkets data source.

[NOTE]
.No free text fields or characteristics
====
Free text fields and characteristics have been replaced with properties. Thus, you cannot transfer free text fields and characteristics to sales channels anymore. Use the properties instead.
====

[.instruction]
Mapping data sources:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. Click on the catalogue. +
→ The catalogue opens. +
→ On the left, the sales channel’s data fields are displayed. +
*_Tip:_* Fields with an asterisk are mandatory. +
→ In the middle, drop-down lists with plentymarkets data sources are displayed. +
. From the drop-down list, select a plentymarkets source for the data fields of the sales channel. +
*_Note:_* Check the information in the user guide of the sales channel’s plugin for details on the target data fields. <<table-catalogue-fields>> contains information regarding the plentymarkets data sources and how to map these data sources. +
. To map another plentymarkets source to a data field, click on *Add source* on the right. A source that has been added can be removed again by clicking on *Remove source*. +
→ A new line is added. +
*_Note:_* The selected data fields are checked in the order in which they were mapped. So if the first data field does not contain a value, the second data field is transferred, etc. In case you map more than one data source to a data field, only one value is transferred. However, there is the possibility of <<data/exporting-data/managing-catalogues#70, combining data sources>>.
. Map all data you want to send to the sales channel.
. *Save* (icon:save[role="green"]) the settings. +
→ The mappings are saved.

[[table-catalogue-fields]]
.Available plentymarkets data sources
[cols="1,1,2"]
|====
|Type |Available sources |Explanation

|Variation
a|* *Variation ID*
* *Is main variation* +
* *ID of main variation* +
* *Position* +
* *Active* +
* *Show unit price* +
* *Variation no.* +
* *Model* +
* *External variation ID* +
* *Net purchase price* +
* *Order picking* +
* *Stock limit* +
* *Online store: visible if net stock is positive* +
* *Online store: invisible if net stock is 0 or negative* +
* *Available if net stock is positive* +
* *Not available if net stock is 0 or negative* +
* *Max. order quantity* +
* *Min. order quantity* +
* *Interval order quantity* +
* *Available until* +
* *Release date* +
* *Variation name* +
* *Gross weight in g* +
* *Net weight in g* +
* *Width in mm* +
* *Length in mm* +
* *Height in mm* +
* *Extra shipping charge 1* +
* *Extra shipping charge 2* +
* *Number of packages* +
* *Net transportation costs* +
* *Net storage costs* +
* *Customs* +
* *Operating costs* +
* *Invisible: in item list* +
* *Default shipping costs* +
* *VAT rate* +
* *Availability* +
* *Content unit* +
* *Content amount*
|The value saved for the variation in the data field is transferred.

|Attribute
a|* The attribute values saved in the system
|

|Barcode
a|* The barcodes saved in the system
|The variation’s code saved for this barcode is transferred.

|Sales price
a|* The sales prices saved in the system
|The variation’s price saved for this sales price is transferred.

|Property
a|* The properties saved in the system
|Once you select a source, a drop-down list containing the available languages is shown.

|SKU
a|* *SKU* +
* *Parent SKU*
|The value saved for the variation in the data field is transferred.

|Item
a|* *Item ID* +
* *Manufacturer ID* +
* *Manufacturer name* +
* *External manufacturer name* +
* *Manufacturing country ID* +
* *Manufacturing country name*
|

|Stock
a|* *Virtual warehouse* +
* The warehouses saved in the system
|The stock information for the selected warehouse is transmitted to the sales channel.

|Item text
a|* *Name 1* +
* *Name 2* +
* *Name 3* +
* *Preview text* +
* *Meta description* +
* *Item text* +
* *Technical data* +
* *URL path*
|Once you select a source, a drop-down list containing the available languages is shown.

|Default category
a|* *Category ID* +
* *Category name* +
* *Category description* +
* *URL name* +
* *Meta title* +
* *Meta description* +
* *Meta keywords*
|

|Image
a|* *All available images*
|

|ASIN
a|* *All* +
* *Amazon Germany* +
* *Amazon Espania* +
* *Amazon France* +
* *Amazon United Kingdom* +
* *Amazon Italy* +
* *Amazon United States*
|

|Manufacturer
a|* The manufacturers saved in the system
|In drop-down lists for target and source, the manufacturers of the sales channel are mapped to the manufacturers saved in plentymarkets one by one. On the left, click on *Add manufacturer* (icon:plus-square[role="green"]) to map additional target manufacturers. +
*_Note:_* The manufacturer name of the sales channel is published on the sales channel.

|Category
a|* The categories saved in the system
|In drop-down lists for target and source, the categories of the sales channel are mapped to the categories saved in plentymarkets one by one. On the left, click on *Add categories* (icon:plus-square[role="green"]) to map additional target categories. +
*_Note:_* The category name of the sales channel is published on the sales channel.
|====

[NOTE]
.Also show non-obligatory fields
====
By default, only obligatory fields of a catalogue are displayed. They are highlighted with a *. In order to display non-obligatory fields, too, activate the toggle button at the top of the overview of a catalogue.
====

[#70]
=== Combining data sources

To export a data field, you can use the Own value to combine as many sources as you like. To do so, create *Additional sources* and select a separator for each combination.

[.instruction]
Combining data sources:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. Click on a catalogue. +
→ The catalogue opens.
. In the line of the data field you want to export, select a plentymarkets source from the drop-down list.
. Underneath the source that you want to combine, click on *Additional source* (icon:plus-square[role="green"]). +
→ Another source is added.
. From the left drop-down list, select *Own value*.
. In the field *Value*, enter the separator that you want to place between the sources.
. Underneath the Own value, click on *Additional source* (icon:plus-square[role="green"]). +
→ Another source is added.
. From the drop-down list, select a plentymarkets source that you want to combine with the first source.
. If required, select further additional sources and separators via the Own value. Between two sources, there always has to be a separator.
. Click on *Save*. +
→ The sources are combined and displayed with the respectively selected separator. +
*_Note_*: In case you create several combinations of sources for a data field, only the first combination is transferred. However, a prerequisite is that all of the selected values exist. If, for example, the first value is empty or does not exist, the combination is ignored and the next combination of data sources is used.

[#80]
=== Copying a catalogue

You can copy catalogues and thus use catalogues that you have already configured in order to quickly create a new catalogue.

[.instruction]
Coping a catalogue:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. Select one or multiple catalogues.
. Click on *Copy catalogue*. +
→ The catalogue is copied. *_Copy of_* is added to a copied catalogue.

[#90]
=== Deleting a catalogue

Proceed as described below to delete a catalogue.

[.instruction]
Deleting a catalogue:

. Go to *Data » Catalogues*. +
→ The catalogue overview opens.
. Click on the catalogue that you want to delete. +
→ The catalogue opens. +
. In the upper right corner, click on *Delete* (icon:minus-square[role="red"]). +
→ You are asked to confirm your decision.
. Confirm the deletion. +
→ The catalogue is deleted.

[#100]
== Transferring catalogue data to the sales channel

The catalogues created in the *Data » Catalogues* menu allow you to map the data fields of a sales channel to the correct plentymarkets data sources. Transferring the variation data to the sales channel is activated in the settings of the sales channel.
