= Managing catalogues
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Catalogue, Catalog, Catalogues, Catalogs, catalogue templates, market, markets, sales channel, templates, data sources, target data
:description: In the *Data » Catalogue* menu allows you to configure the export of variation data to markets.
:position: 50
:url: data/exporting-data/Managing-catalogs
:id: FHQHFWO

[IMPORTANT]
.Catalogues are a new feature!
====
Catalogues are a new feature for exporting variation data to markets and other sales channels. In the pilot phase, you can create catalogues for the German market REWE. Additional markets will follow soon.
====

Catalogues are used to prepare variation data for exporting them to a sales channel. On this page of the manual, you will find information on creating and managing catalogues.

[NOTE]
.Visibility of the menu *Data » Catalogs*
====
The *Data » Catalogue* becomes visible when you deploy a plugin that provides a catalogue template.
====

== What is a catalogue?

Each sales channel requires different product data. Often, different product information must be sent to the same sales channel for different product categories (pet food, household items, food, etc.).

Catalogues allow you to customise information regarding your product portfolio to meet the requirements of each sales channel and target audience. You achieve this by mapping the individual data fields of a sales channel to a suitable plentymarkets data source. When your variation data is transferred to the sales channel, the sales channel’s data fields are then filled with the correct plentymarkets data.

Catalogs offers the following advantages:

* The sales channel provides the data structure. As such, you know exactly which variation data is necessary to sell your products on this sales channel.
* You select which variation data you want to publish on each sales channel and for each template. For example, you can use properties to transfer different variation names and descriptions to different sales channels.

[TIP]
.Exporting data? FormatDesigner
====
Catalogues are used to transmit data to sales channels. Catalogue data cannot be exported to a file or any other readable format. Use the <<data/exporting-data/FormatDesigner#, FormatDesigner>> to export data.
====

== What is a catalogue template?

A catalogue template provides a framework of the data a sales channel can accept. As such, catalogue templates tell you what data can be transmitted to the sales channel.

A sales channel can offer more than one catalogue template, for example for different product categories (pet food, food, non-food, etc.) and/or for different languages. Catalogue templates are loaded into the plentymarkets back end by deploying the plugin for the sales channel. Check the plugin documentation to find out which catalogue templates are available for the different sales channels.

[NOTE]
.No catalogue template without a plugin
====
The catalogue templates of a sales channel are loaded into the *Data » Catalogue* menu when you deploy the sales channel’s plugin.
====

== Managing variation data using properties

<<item/managing-items#3000, Properties of the Item area>> allow you to save data for variations for which no default data fields are available in the plentymarkets back end.

==== Example 1: Diameter information

*Use case:* +
A sales channel allows you to send the *diameter* and the *diameter unit* of your products. By default, you cannot save diameter data in the plentymarkets back end.

*Recommended:* +
<<table-diameter>> shows the recommended settings for sending diameter data to sales channels.

[[table-diameter]]
.Example 1: Diameter information
[cols="1,3"]
|====
|Data field sales channel |Properties in plentymarkets

2+| *Setup » Settings » Properties » Configuration*

|*Diameter unit*
a|* Create a property *Diameter unit*: +
Section: *Item* +
Type: *Selection*
* Save values, e.g. *cm* and *mm*

|*Diameter*
a|* Create a property *Diameter*: +
Section: *Item* +
Type: *Decimal number*

2+|*Item » Edit item » Open item » Open variation*

|*Diameter unit*
a|* Open the *Properties* tab.
* Add the property *Diameter unit*.
* Select the unit from the drop-down list.

|*Diameter*
a|* Open the *Properties* tab.
* Add the property *Diameter*.
* Enter the diameter in the unit you selected for *Diameter unit*.

2+|*Data » Catalogues » Open catalogue*

|*Diameter unit*
a|* From the drop-down list *Source*, select the option *Property » Diameter unit*.

|*Diameter*
a|* From the drop-down list *Source*, select the option *Property » Diameter*.
|====


==== Example 2: Brand names

*Use case:* +
The sales channel allows you to transfer the brand name of products. By default, you can save manufacturers but not brand names in the plentymarkets back end.

*Recommended:* +
If the manufacturer names saved in your system are not identical to the products’ brand names, you can manage brand names using properties. <<table-brands>> shows the recommended settings for managing brands to send to sales channels.

[[table-brands]]
.Example 2: Brand information
[cols="1,3"]
|====
|Data field sales channel |Properties in plentymarkets

2+| *Setup » Settings » Properties » Configuration*

|*Brand*
a|* Create a property *Brand*: +
Section: *Item* +
Type: *Short text*

2+|*Item » Edit item » Open item » Open variation*

|*Brand*
a|* Open the *Texts* tab.
* Add the property *Brand*.
* Enter the brand name.

2+|*Data » Catalogues » Open catalogue*

a|* Select the brand from the drop-down list *Brand*.
a|* From the drop-down list *Source*, select the option *Property » Brand*.
* In the *Value* field, add the brand name. +
*_Note:_* The brand name of the sales channel is published on the sales channel.
|====


== Managing catalogues

The *Data » Catalogues* menu becomes visible in the plentymarkets back end once you deploy a plugin that makes catalogue templates available. Use this menu to search for, edit or delete catalogues.

=== Creating a catalogue

Proceed as described below to create a catalogue.

[.instruction]
Creating a catalogue:

. Go to *Data » Catalogs*. +
→ The catalogue overview is shown.
. Click on *Create catalogue*.
. Enter a name for the catalogue.
. Select a catalogue template from the drop-down list.
. *Save* the settings. +
→ The catalogue is created. +
→ The catalogue is opened for editing.

=== Mapping data sources

After you create a catalogue, the catalogue opens. To the left, the sales channel’s data is shown. Fields with an asterisk are mandatory. Further to the right of each data field is a drop-down list. Use these drop-down lists to map one or more plentymarkets data sources to the data fields of the sales channel.

Depending on the product data you want to transfer, you either map a data field or a value. In the upper area, you map data fields. For example, you select which data field in plentymarkets contains the weight of variations. In the lower section, you map values. For example, you map the sales channel’s category “Pet food” to your plentymarkets category “Animal food”.

Proceed as described below to map the data fields of the sales channel to a plentymarkets data source.

[.instruction]
Mapping data sources:

. Go to *Data » Catalogs*. +
→ The catalogue overview is shown.
. Click on the catalogue. +
→ The catalogue opens. +
→ To the left, the sales channel’s data fields are shown. +
*_Tipp:_* Fields with an asterisk are mandatory. +
→ In the middle, drop-down lists with plentymarkets data sources are shown. +
. From the drop-down list, select a plentymarkets source for the data fields of the sales channel. +
*_Note:_* Check the information in the user guide of the sales channel’s plugin for details on the target data fields. <<table-catalogue-fields>> contains information regarding den plentymarkets data sources and how to map these data sources. +
. To map another plentymarkets source to a data field, click on *Add source* on the right. +
→ A new line is added. +
*_Note:_* Even if you map more than one data source to a data field, only one value is transferred to the sales channel. The data is checked in the order in which they were mapped. So if the first data field does not contain a value, the second data field is transmitted, etc.
. Map all data you want to send to the sales channel.
. *Save* the settings. +
→ The mappings are saved.

[[table-catalogue-fields]]
.Available plentymarkets data sources
[cols="1,1,2"]
|====
|Type |Available sources |Explanation

|Texts
a|* *Name 1* +
* *Name 2* +
* *Name 3* +
* *Short description* +
* *Meta description* +
* *Description* +
* *Technical data* +
* *URL path*
|Once you select a source, a drop-down list containing the available languages is shown.

|Sales price
a|* The sales prices saved in the system
|The variation’s price saved for this sales price is transferred.

|Property
a|* The properties saved in the system
|Once you select a source, a drop-down list containing the available languages is shown.

|Image
|No additional selection of data
|

|Barcode
a|* The barcodes saved in the system
|The variation’s code saved for this barcode is transferred.

|SKU
|No additional selection of data
|

|Stock
a|* *Virtual warehouse* +
* The warehouses saved in the system
|The stock information for the selected warehouse is transmitted to the sales channel.

|Default category
a|* *ID* +
* *Name* +
* *Description* +
* *URL name* +
* *Meta title* +
* *Meta description* +
* *Meta keywords*
|

|Property
a|* The properties saved in the system
|

|Variation
a|* *Variation ID*
* *Is main variation* +
* *ID of main variation* +
* *Position* +
* *Active* +
* *Show unit price* +
* *Variation no.* +
* *Model* +
* *External variation ID* +
* *Net purchase price* +
* *Order picking* +
* *Stock limit* +
* *Store: visible if net stock is positive* +
* *Store: invisible if net stock is 0 or negative* +
* *Available if net stock is positive* +
* *Not available if net stock is 0 or negative* +
* *Max. order quantity* +
* *Min. order quantity* +
* *Interval order quantity* +
* *Available until* +
* *Release date* +
* *Variation name* +
* *Gross weight in g* +
* *Net weight in g* +
* *Width in mm* +
* *Length in mm* +
* *Height in mm* +
* *Extra charge 1* +
* *Extra charge 2* +
* *Units contained* +
* *Number of packages* +
* *Net transportation costs* +
* *Net storage costs* +
* *Customs* +
* *Operating costs* +
* *Invisible: in item list* +
* *Default shipping costs*
|The value saved for the variation in the data field is transferred.

|Manufacturers
a|* The manufacturers saved in the system
|In drop-down lists for target and source, the manufacturers of the sales channel are mapped to the manufacturers saved in plentymarkets one by one. To the left, click on *Add manufacturer* to map additional target manufacturers. +
*_Note:_* The manufacturer name of the sales channel is published on the sales channel.

|Attribute
a|* The attribute values saved in the system
|

|Category
a|* The categories saved in the system
|In drop-down lists for target and source, the categories of the sales channel are mapped to the categories saved in plentymarkets one by one. To the left, click on *Add categories* to map additional target categories. +
*_Note:_* The category name of the sales channel is published on the sales channel.
|====


=== Deleting a catalogue

Proceed as described below to delete a catalogue.

[.instruction]
Deleting a catalogue:

. Go to *Data » Catalogs*. +
→ The catalogue overview is shown.
. Click on the catalogue. +
→ The catalogue opens. +
. In the upper right corner, click on *Delete*. +
→ You are asked to confirm your decision.
. Confirm the delete. +
→ The catalogue is deleted.

== Transferring catalogue data to the sales channel

The catalogues created in the *Data » Catalogues* menu allow you to map the data fields of a sales channel to the correct plentymarkets data sources. Transferring the variation data to a sales channel is activated in the settings of the plugin of the sales channel.
