= Assignment taric code
:lang: en
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, import, taric, taric code, assignment, VAT
:position: 10
:url: data/importing-data/sync-types/elasticSync-assignment-taric-code
:id: 91N5TSK
:author: none

A sync of the type *Assignment taric code* allows you to import data for the taric code table in the menu *Setup » Client » Settings » Taric code*. In order to provide taric codes for variations via import, go to the <<data/importing-date/sync-types/elasticSync-item#2300, sync type Item>>.

[#10]
== Fields for matching taric assignment

The following fields are available for matching the taric assignment. During the import, plentymarkets checks if the imported data record already exists based on the matching field.

* Taric code
* Country

[#20]
== Fields for mapping taric assignment

<<table-mapping-fields-taric-assignment>> explains the fields that are available for mapping date for the taric assignment. During the import, plentymarkets checks if the imported data record already exists based on the matching field.

[[table-mapping-fields-taric-assignment]]
.Mapping fields for importing taric assignment
[cols="1,3"]
|====
|Matching field |Explanation

|*Assignment / VAT*
|The VAT rates which are assigned to the taric codes and the corresponding country.

|*Assignment / delete*
|The VAT rate for the listed taric code and the corresponding country is deleted.
|====
