= Notes
:lang: en
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, import, notes
:position: 90

A sync of the type *Note* allows you to import notes. Depending on the matching field you select, the notes are either saved for contacts, variations, orders or categories.

[#2110]
== Fields for matching

<<Table-matching-fields-notes>> explains the fields that are available for matching notes. During the import, plentymarkets checks if the imported data record already exists based on the matching field. The matching field you select determines the type of data record the note is assigned to during import. As such, you need to create separate syncs for each type of note.

[[table-matching-fields-notes]]
.Matching fields for importing notes
[cols="1,2"]
|====
|Setting |Explanation

|Contact ID
|The notes are saved for the contact with the ID specified in the matching field.

|Variation ID
|The notes are saved for the variation with the ID specified in the matching field.

|Order ID
|The notes are saved for the order with the ID specified in the matching field.

|Category ID
|The notes are saved for the category with the ID specified in the matching field.

|====

[#2120]
== Fields for mapping notes

<<Table-mapping-fields-notes>> explains the fields that are available for mapping notes. During the import, plentymarkets checks if the imported data record already exists based on the matching field.

[[table-mapping-fields-notes]]
.Mapping fields for importing notes
[cols="1,1,2"]
|====
|Mapping field |Permitted import values |Explanation

|User ID +
(mandatory)
|Numeric (internal ID)
|The ID of the person who creates the note.

|Text
|Alpha-numeric
|The text of the note

|Visible to customers
|0 = No +
1 = Yes
|Only applies to order note

|====
