= Categories
:lang: en
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Categories
:position: 80
:url: data/importing-data/sync-types/elasticSync-categories
:id: GV1MLXQ
:author: team-item

This page explains the matching and mapping fields that you can use while importing categories. This page serves purely as a reference and it assumes that you already have a basic understanding of the <<data/importing-data/ElasticSync#, import tool>>.

[TIP]
.Practical example: Importing new categories
====
Imagine you’re new to plentymarkets and you want to import all of your category data at once. How would that work? Take a look at <<data/importing-data/elasticsync-best-practices/best-practices-elasticsync-categories#, this practical example>>, which guides you through the process step-by-step.
====

[#10]
== Matching fields

<<table-matching-fields-categories>> explains the fields that are available for matching category data. During the import, plentymarkets checks if the imported data record already exists based on the matching field.

[[table-matching-fields-categories]]
.Matching fields for importing categories
[cols="1,3"]
|====
|Setting |Explanation

| *Category ID*
|Which column of your CSV file lists the category IDs? Choose this column here.
This option is useful if you want to _update existing categories_.

*_Background info_*: Every new category automatically receives an ID, which can not be changed.
The ID is used to uniquely identify the category.
Since the ID is unique, it’s a good way to check whether the imported data record already exists in plentymarkets.

| *Combined category name*
|Which column of your CSV file contains the complete category path? Choose this column from the first drop-down list and choose the separator from the second drop-down list.
This option is useful if you want to _update existing categories_.

| *Category name level 1 - 6*
|Which column of your CSV file contains the category name for this level? Choose this column here.
|====

[#20]
== Mapping fields

This chapter explains the fields that are available for mapping category data.
Use these fields to specify which _column of your file_ corresponds to which _data field in your system_.

[.instruction]
Basic procedure:

. *_In your CSV file_*: Enter a valid import value into a column.
. *_In plentymarkets_*\: Assign this column to the appropriate mapping field.
. *_After the import_*: Check the result in the back end.

[TIP]
.No mapping field? Default value applies!
====
If you don’t include a certain piece of information in your CSV file, i.e. if you _don’t use_ a certain mapping field, then your category will be given the default value.
====

[#30]
=== Category

[#40]
==== Parent category ID

Enter the higher-level category ID in your CSV file.
This tells plentymarkets how the categories relate to each other.
For example, whether a row of the CSV file should be interpreted as a subcategory and if so, which category is above it.

*_Default value_*: No default value

*_Permitted import values_*: Numeric (internal category ID)

'''
[#50]
==== Parent category name

Enter the higher-level category name in your CSV file.
This tells plentymarkets how the categories relate to each other.
For example, whether a row of the CSV file should be interpreted as a subcategory and if so, which category is above it.

*_Default value_*: No default value

*_Permitted import values_*: Alpha-numeric

'''
[#60]
==== Type

What do you want to use the category for? In plentymarkets, categories can be used to group products together or to create content pages for your store.

*_Default value_*: `item`

[[table-mapping-categories-type]]
[cols="1,1"]
|====
|Permitted import values in CSV file |Options in the drop-down list in the back end

|`item`
|Item

|`container`
|Container

|`content`
|Content

|`blog`
|Blog
|====

You can find the result of the import in the back end menu: <<item/settings/categories#intable-use-case, Item » Category » Tab: Settings » Drop-down list: Type>>

'''
[#70]
==== In link list

Decide whether the category should be displayed in the online store’s navigation.

*_Default value_*: `0`

[[table-mapping-categories-linklist]]
[cols="1,1"]
|====
|Permitted import values in CSV file |Options in the drop-down list in the back end

|`0`
|Do not display

|`1`
|Display
|====

You can find the result of the import in the back end menu: <<item/settings/categories#intable-in-link-list, Item » Category » Tab: Settings » Drop-down list: In link list>>

'''
[#80]
==== right

Decide whether the category should only be visible for users who have logged in.

*_Default value_*: `all`

[[table-mapping-categories-right]]
[cols="1,1"]
|====
|Permitted import values in CSV file |Options in the drop-down list in the back end

|`all`
|Public

|`customer`
|After login
|====

You can find the result of the import in the back end menu: <<item/settings/categories#intable-login, Item » Category » Tab: Settings » Drop-down list: Visible>>

'''
[#90]
==== Visible

Decide whether the category should be included in the sitemap.

*_Default value_*: `0`

[[table-mapping-categories-visible]]
[cols="1,1"]
|====
|Permitted import values in CSV file |Options in the drop-down list in the back end

|`0`
|Do not display

|`1`
|Display
|====

You can find the result of the import in the back end menu: <<item/settings/categories#intable-sitemap, Item » Category » Tab: Settings » Drop-down list: Sitemap>>

'''
[#100]
==== Delete category

Do you want to delete the category?

*_Default value_*: `0`

[[table-mapping-categories-delete-category]]
[cols="1,1"]
|====
|Permitted import values in CSV file |Result in the back end

|`0`
|Category will _not_ be deleted

|`1`
|Category will be deleted
|====

'''
[#110]
==== Create parent category if not found

Do you want to create the category directly above it, if this category doesn’t already exist?

*_Default value_*: `0`

[[table-mapping-categories-create-parent]]
[cols="1,1"]
|====
|Permitted import values in CSV file |Result in the back end

|`0`
|Parent category will _not_ be created

|`1`
|Parent category will be created
|====

'''
[#120]
=== Category settings

[#130]
==== Name

icon:warning[role="red"] [red]#Required field#

Enter the category name into the CSV file.

*_Default value_*: No default value

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-category-name, Item » Category » Tab: Settings » Entry field: Name>>

'''
[#140]
==== Description 1

Enter the category description into the CSV file.

*_Default value_*: No default value

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#800, Item » Category » Tab: Description 1>>

'''
[#150]
==== Description 2

Enter the category description into the CSV file.

*_Default value_*: No default value

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#800, Item » Category » Tab: Description 2>>

'''
[#160]
==== Short description

Enter the short description into the CSV file.

*_Default value_*: No default value

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-short-description, Item » Category » Tab: Settings » Entry field: Short description>>

'''
[#170]
==== Meta keywords

Enter keywords into the CSV file.

*_Default value_*: No default value

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-meta-keywords, Item » Category » Tab: Settings » Entry field: Meta keywords>>

'''
[#180]
==== Meta description

Enter a meta description into the CSV file.

*_Default value_*: No default value

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-meta-description, Item » Category » Tab: Settings » Entry field: Meta description>>

'''
[#190]
==== Meta title

Enter a meta title into the CSV file.

*_Default value_*: No default value

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-meta-data, Item » Category » Tab: Settings » Entry field: Meta title>>

'''
[#200]
==== URL name

Enter a URL name into the CSV file.
This name is used to form the category URL.

*_Default value_*: URL name = Category name

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-url, Item » Category » Tab: Settings » Entry field: URL name>>

*_Example_*: The URL name `new-category` will transform into the URL `www.your-domain.com/new-category`

'''
[#210]
==== Position

Enter a position number in the CSV file.

*_Default value_*: `0`

*_Permitted import values_*: Numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-position, Item » Category » Tab: Settings » Entry field: Position>>

'''
[#220]
==== Template list

icon:warning[role="red"] [red]#Only relevant for the old Callisto store#

Enter the name of the template into the CSV file.

*_Default value_*: ItemViewCategoriesList

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-template-list, Item » Category » Tab: Settings » Drop-down list: Template list>>

'''
[#230]
==== Template product

icon:warning[role="red"] [red]#Only relevant for the old Callisto store#

Enter the name of the template into the CSV file.

*_Default value_*: ItemViewSingleItem

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-template-product, Item » Category » Tab: Settings » Drop-down list: Template product>>

'''
[#240]
==== Template page

icon:warning[role="red"] [red]#Only relevant for the old Callisto store#

Enter the name of the template into the CSV file.

*_Default value_*: PageDesignContent

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-template-page, Item » Category » Tab: Settings » Drop-down list: Template page>>

'''
[#250]
==== Full text search

Decide whether the category should be added to the store’s category search index.

[TIP]
Also use the drop-down lists to select the language and the webstore.

*_Default value_*: `0`

[[table-mapping-categories-fulltext]]
[cols="1,1"]
|====
|Permitted import values in CSV file |Options in the drop-down list in the back end

|`0`
|No

|`1`
|Yes
|====

You can find the result of the import in the back end menu: <<item/settings/categories#intable-full-text-search, Item » Category » Tab: Settings » Drop-down list: Full text search>>

'''
[#260]
==== Robots

Decide how search engine crawlers should deal with the page and any links on the page.

[TIP]
Also use the drop-down lists to select the language and the webstore.

*_Default value_*: `all`

[[table-mapping-categories-robots]]
[cols="1,1"]
|====
|Permitted import values in CSV file |Options in the drop-down list in the back end

|`all`
|all

|`index`
|index

|`nofollow`
|nofollow

|`noindex`
|noindex

|`nofollow_noindex`
|nofollow, noindex
|====

You can find the result of the import in the back end menu: <<item/settings/categories#intable-robots, Item » Category » Tab: Settings » Drop-down list: Robots>>

'''
[#270]
==== Translate placeholder

Decide whether template variables and template functions should be translated.

[TIP]
Also use the drop-down lists to select the language and the webstore.

*_Default value_*: `Y`

[[table-mapping-categories-placeholder]]
[cols="1,1"]
|====
|Permitted import values in CSV file |Options in the drop-down list in the back end

|`Y`
|Yes

|`N`
|No

|`L`
|Template variables and template functions for links only
|====

You can find the result of the import in the back end menu: <<item/settings/categories#intable-variables-functions, Item » Category » Tab: Settings » Drop-down list: Translate template variables and template functions>>

'''
[#280]
==== Canonical

Is there another category with the same content? If so, then enter the URL for this category into your CSV file.
The URL is limited to a maximum of 256 characters.
This prevents so-called “duplicate content”.

*_Default value_*: No default value

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down lists to select the language and the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-canonical, Item » Category » Tab: Settings » Entry field: Canonical>>

'''
[#290]
=== Elmar

[#300]
==== Elmar-category

Enter the name of the Elmar category into your CSV file.

*_Default value_*: No default value

*_Permitted import values_*: Alpha-numeric

[TIP]
Also use the drop-down list to select the webstore.

You can find the result of the import in the back end menu: <<item/settings/categories#intable-elmar-category, Item » Category » Tab: Settings » Drop-down list: Elmar category>>

'''
[#310]
==== Delete existing

Do you want to delete the Elmar category link?

*_Default value_*: `0`

[[table-mapping-categories-delete-elmar-link]]
[cols="1,1"]
|====
|Permitted import values in CSV file |Result in the back end

|`0`
|Link will _not_ be deleted

|`1`
|Link will be deleted
|====

[TIP]
Also use the drop-down list to select the webstore.

'''
[#320]
=== Client (store)

[#330]
==== Active

Should the category be activated for a particular store?

[TIP]
Also use the drop-down list to select the webstore.

*_Default value_*: `0`

[[table-mapping-categories-client-active]]
[cols="1,1"]
|====
|Permitted import values in CSV file |Result in the back end

|`0`
|_Not activated_ for the specified client.

|`1`
|_Activated_ for the specified client.
|====

You can find the result of the import in the back end menu: <<item/settings/categories#intable-client, Item » Category » Tab: Settings » Check box: Client (store)>>
