= Warehouse
:lang: en
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, import, warehouse, Sync, sync type
:position: 100
:url: data/importing-data/sync-types/elasticSync-warehouse
:id: IS31LNZ
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

With syncs of the type *Warehouse*, you import new storage locations or update existing ones.

In order to create or update storage locations via ElasticSync, a warehouse must be created.

[#2231]
== Fields for storage location matching

<<table-matching-fields-storage-locations>> explains the fields that are available for matching storage locations. During the import, plentymarkets checks if the imported data record already exists based on the matching field.

For further information on the terms dimensions, levels and storage locations, refer to the link:https://knowledge.plentymarkets.com/en/stock-management/setting-up-a-warehouse[Setting up a warehouse^] page of the manual.

[[table-matching-fields-storage-locations]]
.Matching fields for importing storage locations
[cols="2,2"]
|====
|Matching field |Explanation

|Level name
|Name of the level, e.g. R01

|Level ID
|ID of the level

|WarehouseLocationId
|ID of the storage location

|WarehouseLocationName
|Name of the storage location without path
|====

[#2232]
== Fields for the storage location mapping

<<table-mapping-fields-storage-locations>> explains the fields that are available for mapping storage location data. During the import, plentymarkets checks if the imported data record already exists based on the matching field.

For further information on the terms dimensions, levels and storage locations, refer to the link:https://knowledge.plentymarkets.com/en/stock-management/setting-up-a-warehouse[Setting up a warehouse^] page of the manual.


[[table-mapping-fields-storage-locations]]
.Mapping fields for importing storage locations
[cols="2,2"]
|====
|Mapping field |Explanation

2+^|*Storage locations*

|Storage location ID +
(only for existing storage locations)
|ID of the storage location

|Level ID
|ID of the level

|Storage location name
|Name of the storage location without path

|Purpose
|Purpose of the storage location, e.g. removal from storage

|Status
|Status of the storage location, e.g. active, inactive

|Position
|Position of the storage location (distance)

|Notes
|Notes on the storage location

|Delete Storage Location
|Delete function for storage locations

2+^|*Levels of storage locations*

|Level Parent ID
|Parent ID of the level

|Dimension ID
|ID of the dimension, e.g. rack

|Level Position
|Position of the level

|Level name
|Name of the level, e.g. R01, R02 etc.

|====

[IMPORTANT]
.Use Level ID of the smallest dimension
====
When importing storage locations use the Level ID of the smallest dimension. In the following table this would be Level ID 309. +
In case you select the ID of a higher dimension, the storage locations are no longer visible and the existing structure disappears.
====

[[table-level-id]]
.Level IDs and level names
[cols="2,2,2,2,2"]
|====
| |Level 1 |Level 2 |Level 3 |Storage location

|*Name of the level*
|Rack 1
|Shelf 5
|Box 17
|102

|*Level ID*
|8
|22
|*309*
|
|====

[#2240]
== Adjusting storage locations

You can adjust storage locations via ElasticSync such as changing the name or the position of the storage location.

[.instruction]
Adjusting storage locations:

. Go to *Data » ElasticSync*.
. Click on the sync in the sync overview. +
→ The settings open.
. Switch to the *Matching* tab.
. Activate the field *Warehouse Location ID*.
. Select one of the *Import options*.
. *Save* (icon:save[role="green"]) the settings.
. Click on *Mapping*.
. Open the mapping from the overview.
. Expand the area *Warehouse location* on the right-hand side.
. Activate the fields *Storage location name* and *Position*.
. *Save* (icon:save[role="green"]) the settings.

[#2250]
== Creating storage locations

You can use ElasticSync to create new storage locations. Note that the structure of the warehouse has to be defined beforehand which means that at least one storage location already has to exist.

[.instruction]
Creating storage locations:

. Go to *Data » ElasticSync*.
. Click on the sync in the sync overview. +
→ The settings open.
. Switch to the *Matching* tab.
. Select the field *Level ID*.
. Select one of the *Import options*.
. *Save* (icon:save[role="green"]) the settings.
. Click on *Mapping*.
. Open the mapping from the overview.
. Activate the lines in which the values *Storage location name*, *Purpose*, *Position* and *Status* can be found and select the respective source.
. Expand the area *Warehouse location* on the right-hand side and map the fields *Storage location name*, *Purpose*, *Position* and *Status*. The *Storage location ID* is optional - if not selected, the next highest ID is automatically assigned.
. *Save* (icon:save[role="green"]) the settings.

[#2250]
== Deleting storage locations

You can delete storage locations with ElasticSync.

[.instruction]
Deleting storage locations:

. Go to *Data » ElasticSync*.
. Click on the sync in the sync overview. +
→ The settings open.
. Switch to the *Matching* tab.
. Select the field *Warehouse Location ID*.
. Select one of the *Import options*.
. *Save* (icon:save[role="green"]) the settings.
. Click on *Mapping*.
. Open the mapping from the overview.
. Expand the area *Warehouse location* on the right-hand side.
. Activate the field *Delete storage location*.
. You can either delete all storage locations or only specific ones. Carry out the respective settings. Pay attention to the explanations given in <<table-deleting-storage-locations>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-deleting-storage-locations]]
.Deleting all storage locations or only specific ones
[cols="1,3"]
|====
|Setting |Explanation

|Deleting all storage locations
|All storage location IDs that exist in the CSV file will be deleted. +
 For the Delete storage location value, select *Own value*. +
 Then select *Yes* or *No*.

|Deleting only specific storage locations
|Here, the CSV file contains two values: on the one hand there are the storage location IDs and on the other hand there are the values *Yes* and *No* by which you can determine whether the value should be deleted.
|====
