= Best Practice: ASIN und ePID ex- und importieren
:lang: de
:keywords: Import, Artikel, Anlage, BestPractice, automatisiert, ASIN, Verknüpfung, ePID
:position: 1

[#Export von ASIN und ePID]
== Export von ASIN und ePID

=== Erstellen des Formats im FormatDesigner

Die derzeit mit Varianten verknüpften ASINs und ePIDs können mit dem FormatDesigner exportiert werden. Dafür erstellt Ihr im Menü *Daten » FormatDesigner* ein neues Format vom Typ *Artikel*.

Anschließend wählt Ihr die Datenfelder:

* Für die Zuordnung beim späteren Import aus dem Bereich *Variation* die *ID* oder *Number* der Variante.

* Die eigentlichen Verknüpfungen fügt Ihr dann im Bereich *VariationMarketIdentNumber* hinzu.

Hier besteht die Möglichkeit, 3 Werte zu wählen:

- *countryID*: Gibt die ID des Landes aus.
- *type*: Gibt den Typ, also ASIN oder ePID, aus.
- *value*: Gibt den Wert aus, der für die ASIN oder ePID hinterlegt ist.

Für alle 3 Felder muss eine Zuordnung des Typs vorgenommen werden. Möchte man also alle ASINs und ePIDs exportieren, muss jedes Feld doppelt in das Format aufgenommen werden.

Nach dem Speichern des Formats kann der Export im Elastischen Export eingerichtet werden.

=== Einrichten des Exports im Elastischen Export

Den Export des angelegten Formats richtet man im Menü *Daten » Elastischer Export* ein.

Dafür klickt Ihr auf *Neuer Export* und hinterlegt einen Namen, den Typ *Artikel*, das angelegte Format, ein Limit und einen Dateinamen.

[TIP]
.Datei als CSV exportieren
====
Wenn die Datei direkt als CSV heruntergeladen werden soll, muss beim Dateinamen das Suffix *.csv* angegeben werden.
====

Nach dem Speichern des Formats ist die Einrichtung abgeschlossen.

=== Daten exportieren

Es gibt mehrere Möglichkeiten, die Daten zu exportieren:

* Im Export auf *Herunterladen* klicken.
* Die im Export angegebene URL im Browser öffnen.
* In der Übersicht der Exporte auf *Herunterladen* klicken.

[#Import von ASIN und ePID]
== Import von ASIN und ePID

=== Erstellen des Formats im Import-Tool

Für den Import und das Bearbeiten der ASINs und ePIDs könnt ihr unter *Daten » Import* einen eigenen Import vom Typ *Artikel* anlegen oder auch die Felder in einen bestehenden Import einbauen.

* Der Abgleich muss über ein variantenspezifisches Feld wie die *Variantennummer* erfolgen.

* Für die *Zuordnung* des Imports müssen für die Verknüpfung im Bereich *ASIN/ePID* die Felder *Land*, *Typ* und *Wert* hinterlegt und mit den Spalten aus der CSV verknüpft werden.

* Das Land muss dabei als ID hinterlegt werden und der Typ entweder als ASIN oder EPID.

Mehr benötigt Ihr für die Verknüpfung nicht. Der Import ist damit einsatzbereit und die Merkmale können verknüpft werden.
