= Best Practice: Merkmalverknüpfungen ex- und importieren
:lang: de
:keywords: Import, Artikel, Anlage, BestPractice, automatisiert, Merkmale, Verknüpfung, Merkmalverknüpfung
:position: 1

[#Export von Merkmalverknüpfungen]
== Export von Merkmalverknüpfungen

=== Erstellen des Formats im FormatDesigner

Die derzeit mit Varianten verknüpften Merkmale können mit dem FormatDesigner exportiert werden. Dafür erstellt Ihr im Menü *Daten » FormatDesigner* ein neues Format vom Typ *Item*.

Anschließend wählt Ihr die Datenfelder:

* Für die Zuordnung beim späteren Import im Bereich *Item* die *ID* des Artikels oder im Bereich *Variation* die *ID* oder die *Number* der Variante.

* Die eigentlichen Merkmalverknüpfungen werden dann im Bereich *VariationProperty* hinzugefügt:

Hier besteht die Möglichkeit, zwischen 3 Werten zu wählen:

- *value*: Gibt den Wert des im Format zugeordneten Merkmals aus.
- *all*: Gibt alle verknüpften Merkmale eines Artikels mit Wert aus.
- *allIds*: Gibt alle verknüpften Merkmal-IDs eines Artikels ohne Wert aus.

Nach dem Speichern des Formats kann der Export im Elastischen Export eingerichtet werden.

=== Einrichten des Exports im Elastischen Export

Den Export des angelegten Formats richtet man im Menü *Daten » Elastischer Export* ein.

Dafür klickt Ihr auf *Neuer Export* und hinterlegt einen Namen, den Typ *Artikel*, das angelegte Format, ein Limit und einen Dateinamen.

[TIP]
.Datei als CSV exportieren
====
Wenn die Datei direkt als CSV heruntergeladen werden soll, muss beim Dateinamen das Suffix *.csv* angegeben werden.
====

Nach dem Speichern des Formats ist die Einrichtung abgeschlossen.

=== Daten exportieren

Es gibt mehrere Möglichkeiten, die Daten zu exportieren:

* Im Export auf *Herunterladen* klicken.
* Die im Export angegebene URL im Browser öffnen.
* In der Übersicht der Exporte auf *Herunterladen* klicken.

[#Import von Merkmalverknüpfungen]
== Import von Merkmalverknüpfungen

=== Erstellen des Formats im Import-Tool

Für den Import der Merkmalverknüpfungen könnt Ihr unter *Daten » Import* einen eigenen Import von Typ *Artikel* anlegen oder auch die Felder in einen bestehenden Import einbauen.

Der Abgleich kann über ein variantenspezifisches Feld wie die *Variantennummer* erfolgen oder auch über die *Artikel ID*, wenn die Verknüpfungen in einem eigenen Import erstellt werden.

In der Zuordnung des Imports können verschiedene Felder gewählt werden, um die Verknüpfung zu erstellen bzw. zu bearbeiten. Zum Beispiel könnt Ihr die Felder *ID, Wert und Sprache* (es müssen alle 3 sein) hinzufügen oder auch nur das Feld *Merkmalkombination*. Letzteres muss in der Datei wie folgt aufgebaut sein:

*InternerName1:Wert1:Sprache;InternerName2:Wert2:Sprache*

Sollen Merkmalverknüpfungen gelöscht werden, geschieht das mit dem Feld *Löchen (Ja/Nein)*, das in der Datei mit einer *1* für löschen und *2* für nicht löschen gefüllt sein muss.

Mehr benötigt Ihr für die Verknüpfung nicht. Der Import ist damit einsatzbereit und die Merkmale können verknüpft werden.
