= DHL Wunschpaket
:lang: en
include::{includedir}/_header.adoc[]
:keywords: DHL Wunschpaket, DHL Wunschpaket plugin, Preferred day, preferred location, preferred neighbour, preferred neighbor, Wunschpaket services, Show Wunschpaket in checkout, Wunschpaket services in checkout
:description: Learn how to set up the “DHL Wunschpaket” plugin in plentymarkets.
:position: 200
:url: fulfilment/shipping-service-provider-plugins/plugin-dhl-wunschpaket
:id: DKSJ6HL
:author: team-fulfillment

[IMPORTANT]
.Download the DHL Wunschpaket plugin
====
You need a plugin to integrate the DHL Wunschpaket services in plentymarkets. Visit the link:https://marketplace.plentymarkets.com/en/plugins/integration/dhlwunschpaket_5435[plentyMarketplace^]{nbsp}icon:external-link[] to download the DHL Wunschpaket plugin.
====

[#general-information]
== General information

This plugin allows you to show the DHL Wunschpaket services in your Ceres online store. Setting up the DHL Wunschpaket services themselves has to be carried out via the *DHL Wunschpaket* assistant. This assistant will be available in the *Setup » Assistants » Plugins* menu in the relevant plugin set once you have successfully installed the plugin. Afterwards, you have to activate the services in the *DHL Shipping (Versenden): Settings combination* assistant.

[IMPORTANT]
.Tracking pixel for reporting purposes
====
Note that the DHL Wunschpaket plugin contains a tracking pixel. This is due to reporting purposes. The pixel returns the URL where the plugin is used as well as the total number of plugin calls. No person-related data or data that could be related to persons will be collected or processed.
====

[#requirements]
== Requirements

In order that you can offer your customers the DHL Wunschpaket services in your online store, the following requirements have to be met.

[#register-with-dhl]
=== Registering with DHL

In order to set up the interface for DHL Shipping (Versenden) in your plentymarkets system and use the function _Versenden_ (shipping) in the DHL business customer portal, you have to be registered with link:https://www.dhl.de/en/geschaeftskunden/paket/kunde-werden/angebot-dhl-geschaeftskunden-online.html[DHL^]{nbsp}icon:external-link[]. You receive the data from DHL that you need for the settings in plentymarkets.

Note that the DHL Wunschpaket services are only available for deliveries within Germany.

[#install-plugins]
=== Installing the plugins

The following plugins have to be installed:

* link:https://marketplace.plentymarkets.com/en/plugins/integration/DHLShipping_4871[DHL Shipping (Versenden)^]{nbsp}icon:external-link[]
* link:https://marketplace.plentymarkets.com/en/plugins/integration/DHLWunschpaket_5435[DHL Wunschpaket^]{nbsp}icon:external-link[]
* link:https://marketplace.plentymarkets.com/en/plugins/templates/Ceres_4697[Ceres^]{nbsp}icon:external-link[]
* link:https://marketplace.plentymarkets.com/en/plugins/templates/IO_4696[IO^]{nbsp}icon:external-link[]

[#priorities-dhl-plugins]
=== Observing the priorities of the DHL plugins

Pay attention to priorities of the two DHL plugins in the *Plugins » Plugin set overview* menu.

In order that this plugin works correctly, it has to be loaded with a certain priority compared to other plugins. If you install the plugin with the help of the Integration assistant, the correct priority is already set. If not, you have to adjust the priority yourself. To do so, open your plugin set and click on *Priority*. Make sure that the DHL Wunschpaket plugin has a higher priority than _DHL Shipping (Versenden)_ and a lower priority than _Ceres_ and _IO_.

[#dhl-shipping-as-shipping-service-provider]
=== Selecting DHL Shipping (Versenden) as shipping service provider

*DHL Shipping (Versenden)* has to be selected as shipping service provider in the *Setup » Orders » Shipping » Settings* menu in the *Shipping service provider* tab.

[#complete-assistant]
== Completing the assistant

Once you have <<plugins/installing-added-plugins#installing-plugins, installed the plugin in a plugin set>>, the *DHL Wunschpaket* assistant is visible in the *Setup » Assistants » Plugins* menu in the relevant plugin set.

Complete the assistant to save a surcharge for the *Preferred day* service, determine the cut-off times that belong to the *Preferred day* service and set the days where no parcels are transferred to DHL. The cut-off time determines up to which time transfer of parcels to DHL is possible at the same day.

DHL offers the services *Preferred neighbour* and *Preferred location* without any additional charge. If your customer selects the *Preferred day* service in the online store, the price you determined for this service is displayed in the order process and added to the order's total sum.

In order that your customers can use the finder in the Ceres online store to search for a <<#dhl-wunschpaket-packstation-postfiliale-finder, DHL Packstation or post office>> nearby, you have to enter your Google Maps API key and <<fulfilment/shipping-service-provider-plugins/plugin-dhl-shipping-versenden#dhl-assistant-settings-combination, activate>> the finder in the *DHL Shipping (Versenden): Settings combination* assistant. Furthermore, you can determine whether it is mandatory for your customers to enter the DHL post number for post offices in the finder in the Ceres online store.

[#visibility-online-store]
== Setting the visibility of the DHL Wunschpaket services in the online store

In order that your customers can select the DHL Wunschpaket services during the order process in your online store, you have to activate some options in the plugin’s *Container links* area.

[.instruction]
Setting the visibility of the DHL Wunschpaket services in the online store: 

. Go to *Plugins » Plugin overview*.
. Click on the table row of the plugin set that contains the DHL Wunschpaket plugin.
. Click on the table row *DHL Wunschpaket*.
. Go to *Container links*.
. Expand the area *Container links*.
. Select from the drop-down list *Data provider* the option *DHL Wunschpaket CSS*.
. Select from the drop-down list *Ceres* on the right the option *Checkout: Styles*.
. Select from the drop-down list *Data provider* the option *DHL Wunschpaket Scripts*.
. Select from the drop-down list *Ceres* on the right the option *Checkout: After scripts loaded*.
. Select from the drop-down list *Data provider* the option *DHL Wunschpaket Checkout View*.
. Select from the drop-down list *Ceres* on the right the option *Checkout: After shipping method*.
. *Save* (icon:save[role="green"]) the setting. +
→ Your customers can now select the services in the checkout.

[TIP]
.Showing the services in the order confirmation
====
Do you want the services that your customers selected in the checkout to be listed as shipping information in the order confirmation? Then select the following options in addition:

* from the drop-down list *Data provider* the option *DHL Wunschpaket Order Confirmation*
* from the drop-down list *Ceres* on the right the option *Order confirmation: Additional shipping confirmation*
====

[#dhl-wunschpaket-packstation-postfiliale-finder]
== DHL Packstation/Postfiliale finder

Your customers can use the DHL Packstation/Postfiliale finder during the order process in your Ceres online store to search for a packstation or post office nearby and select this address as delivery address. This way, your customers can pick up your parcels when it suits them best. To do so, they select an appropriate packstation or post office during the order process from the results list. This address is then saved as the delivery address.

*_Note:_* Your customers can enter the street, postcode or town. If the street is entered, it is required for the search to display results that in addition at least the postcode or the town is entered.

[IMPORTANT]
.Google Maps API key required
====
In order that the DHL Packstation/Postfiliale finder is available for your customers in the Ceres checkout, you need a Google Maps API key.
====

[discrete]
=== Setting the visibility of the DHL Packstation/Postfiliale finder in the online store

In order that your customers can use the DHL Packstation/Postfiliale finder during the order process in your online store, you have to activate some options in the plugin’s *Container links* area.

[.instruction]
Setting the visibility of the DHL Packstation/Postfiliale finder in the online store: 

. Go to *Plugins » Plugin overview*.
. Click on the table row of the plugin set that contains the DHL Wunschpaket plugin.
. Click on the table row *DHL Wunschpaket*.
. Go to *Container links*.
. Expand the area *Container links*.
. Select from the drop-down list *Data provider* the option *DHL Packstation/Postfiliale Checkout View*.
. Select from the drop-down list *Ceres* on the right the option *Checkout: After shipping method*.
. Select from the drop-down list *Data provider* the option *DHL Packstation/Postfiliale Scripts*.
. Select from the drop-down list *Ceres* on the right the option *Checkout: After scripts loaded*.
. Select from the drop-down list *Data provider* the option *DHL Packstation/Postfiliale Styles*.
. Select from the drop-down list *Ceres* on the right the option *Checkout: After shipping method*.
. *Save* (icon:save[role="green"]) the settings.

*_Note:_* In addition to these settings, you have to activate the button in the *DHL Shipping (Versenden): Settings combination* assistant with which you decide whether you offer the finder to your customers in the order process of your online store. In order that your customers can use the finder, the button has to be green (icon:toggle-off[role="green"]).

[#example-calculation]
== Examples of possible options of preferred days during the checkout

In the following, you find examples of the settings of preferred days and cut-off times and how these settings affect the options your customers can choose from during the checkout.

Note that the time of registering the shipment in the following examples does not refer to the exact time when the customer completes the order process. The possible preferred days that can be selected by the customer is updated when the customer opens the checkout or updates the address.

[discrete]
=== Example 1: Time of registering the shipment: Tuesday, 06 March 2018, 12:00 noon, without exclusion of transfer days

* Setting for *Cut-off times*: 1:00pm
* Setting for *Exclusion of transfer days*: none

Days the customer can select in the checkout:

 * Thursday (08 March 2018)
 * Friday (09 March 2018)
 * Saturday (10 March 2018)
 * Monday (12 March 2018)
 * Tuesday (13 March 2018)
 * Wednesday (14 March 2018)

[discrete]
=== Example 2: Time of registering the shipment: Tuesday, 06 March 2018, 2:00pm, without exclusion of transfer days

* Setting for *Cut-off times*: 1:00pm
* Setting for *Exclusion of transfer days*: none

Days the customer can select in the checkout:

 * Friday (09 March 2018)
 * Saturday (10 March 2018)
 * Monday (12 March 2018)
 * Tuesday (13 March 2018)
 * Wednesday (14 March 2018)
 * Thursday (15 March 2018)

[discrete]
=== Example 3: Time of registering the shipment: Tuesday, 06 March 2018, 2:00pm, with exclusion of transfer days

* Setting for *Cut-off times*: 1:00pm
* Setting for *Exclusion of transfer days*: Tuesday, Wednesday

Days the customer can select in the checkout:

 * Saturday (10 March 2018)
 * Monday (12 March 2018)
 * Tuesday (13 March 2018)
 * Wednesday (14 March 2018)
 * Thursday (15 March 2018)
 * Friday (16 March 2018)
