= postNL
:lang: en
include::{includedir}/_header.adoc[]
:keywords: postNL, postnl, post.nl, post-nl, Post Netherlands
:description: Learn how to set up the “postNL” plugin in plentymarkets.
:position: 600
:url: fulfilment/shipping-service-provider-plugins/plugin-post-nl
:id: 97CN7P2
:author: team-fulfillment

[IMPORTANT]
.Download the postNL plugin
====
You need a plugin to link plentymarkets to postNL. Visit the link:LINKEINFÜGEN[plentyMarketplace^]{nbsp}icon:external-link[] to download the postNL plugin.
====

// bei plentyMarketplace den Link zum Plugin einfügen - insgesamt 3 Mal auf dieser Seite

[#register-with-post-nl]
== Registering with postNL

The *postNL* plugin allows shippers from the Netherlands to create shipping labels quickly and easily and to use the shipment tracking in plentymarkets.

In order to set up the interface for postNL in your plentymarkets system and use the services, you have to register with link:https://www.postnl.be/en/log-in-business/[postNL^]{nbsp}icon:external-link[]. You receive the data from postNL that you need for the settings in plentymarkets. Contact your account manager at postNL, if needed.

[#set-up-post-nl]
== Setting up postNL in plentymarkets

[TIP]
.Simply setting up postNL with the help of an assistant
====
You need a plugin to link plentymarkets to postNL. Visit the link:LINKEINFÜGEN[plentyMarketplace^]{nbsp}icon:external-link[] to download the postNL plugin. +
The postNL assistant that allow an easy setup is then available in the *Setup » Assistants » Plugins* menu in the relevant plugin set.

Before completing the postNL assistant, you need to complete the *Shipping settings* assistant. This assistant is available in your plentymarkets system by default. You can find it in the *Setup » Assistants » Integration* menu. With this assistant, carry out the following settings:

* determine a name for the shipping setting (i.e. the shipping profile)
* activate existing regions or create a new region
* determine the shipping costs and select the calculation type
* *_Note:_* Afterwards, go to *Setup » Orders » Shipping » Settings* and click on the *Shipping profiles* tab to carry out further settings for the shipping profile. Further information on these settings are provided below on this manual page.

Afterwards, complete the postNL assistant.
====

[#preparatory-settings]
== Carrying out the preparatory settings

First, you have to carry out some preparatory settings in the plentymarkets back end:

* <<fulfilment/preparing-the-shipment#100, Set up countries of delivery>>

** You can set up the countries of delivery in the *Shipping settings* assistant or in the back end.

* <<fulfilment/preparing-the-shipment#400, Create regions>>
** You can create regions in the *Shipping settings* assistant or in the back end.

* <<fulfilment/preparing-the-shipment#800, Creating the shipping service provider>> *postNL*
** Currently, you can create shipping service providers only in the back end and _not_ in an assistant.

* Create a <<fulfilment/preparing-the-shipment#1000, shipping profile>> and the <<fulfilment/preparing-the-shipment#1500, table of shipping charges>> for *postNL +
** You can set up some of the shipping settings in the *Shipping settings* assistant. The remaining settings have to be carried out in the back end in the *Setup » Orders » Shipping » Settings* menu in the *Shipping profiles* tab. +
icon:exclamation-triangle[role="red"] *_Important:_* Not all functions and settings have been transferred from the shipping profile to the *Shipping settings* assistant yet. Note the explanations in the <<#assistant-shipping-settings, Completing the *Shipping settings* assistant>> chapter.

[#complete-assistant]
== Completing the assistants

Once you have <<plugins/installing-added-plugins#installing-plugins, installed the plugin in a plugin set>>, the assistant is visible in the *Setup » Assistants » Plugins* menu in the relevant plugin set and you can start with the setup. The *Shipping settings* assistant is available in your plentymarkets system by default. You can find it in the *Setup » Assistants » Integration* menu.

Now complete the assistants in the following order:

1. *Shipping settings*
2. *postNL*

[#assistant-shipping-settings]
=== Completing the *Shipping settings* assistant

You find the *Shipping settings* assistant in the *Setup » Assistants » Integration* menu. In this assistant, carry out the following settings:

* Enter a back end and a front end name for the shipping setting. These names can be selected per language. +
 ** Link this name later in the *postNL* assistant.

* Select the plugin of the shipping service provider for which you want to set up shipping costs. +
 ** You have to download the postNL plugin in the link:LINKEINFÜGEN[plentyMarketplace^]{nbsp}icon:external-link[] before you can see it here.

* Select a region, enter the shipping costs and select the calculation type for the selected countries. Furthermore, you can determine the value of items from which no shipping costs will be calculated.

[IMPORTANT]
.Carry out further settings for the shipping settings in the back end
====
If you have completed the *Shipping settings* assistant, the shipping profile also appears in the *Setup » Orders » Shipping » Settings* menu in the *Shipping profile* tab. +
The following settings are available once the assistant has been completed:

* the name of the shipping profile is saved
* the shipping service provider is saved
* the option *Activate for new items* is activated
* all clients (stores) are activated
* all order referrers are activated
* the shipping costs are saved
* the region is saved

If you want to carry out further settings such as blocking customer classes or payment methods or activating the option for the agreement upon data transmission to shipping service providers, you have to go to *Setup » Orders » Shipping » Settings* and carry out these settings in the *Shipping profiles* tab in the corresponding shipping profile.

icon:exclamation-triangle[role="red"] This workaround is still necessary because not all functions and settings have been transferred from the shipping profile to the assistant yet. We will implement the missing settings in the assistant step by step.
====

When you completed the *Shipping settings* assistant and open it again, the following information is displayed:

* In the tile view:

** Back end name
** Region
** Shipping service provider

* In the table overview:

** Back end name
** Region
** Shipping service provider
** Front end name
** ID of the shipping profile

[#complete-post-nl-assistant]
=== Completing the *postNL* assistant

You find the *postNL* assistant in the *Setup » Assistants » Plugins* menu in the relevant plugin set. This assistant has several steps to complete. These steps are explained in the following.

[discrete]
==== Global settings

In this step, determine whether you want to change the global settings.

If the option is activated (icon:toggle-on[role="green"]), you can make changes to the steps *Login details*, *Shipper data* and *Reference on label* at any time. If the option is deactivated (icon:toggle-off[role="red"]), only the step *Settings combination* is visible and can be changed.

[discrete]
==== Login details

In this step, enter your login details by using your API key. Enter a name of your choice in the field *Name of the API key* for every API key that you use. Click on icon:plus-square[role="green"] to add further login details.

[discrete]
==== Shipper data

In this step, enter your shipper address. Click on icon:plus-square[role="green"] to add further shipper addresses.

[discrete]
==== Reference on label

In this step, select which information should be shown on the shipping label. You can select the following values:

* No entry
* Order ID
* External order ID
* Order ID + external order ID

[discrete]
==== Settings combination

In this step, link the settings that you saved in the *Shipping settings* and in the single steps of the *postNL* assistant. Link the shipping setting with your login details, the products and services, the shipper address and the item description.

If you select a <<#available-shipping-methods-and-services, product>>, all <<#available-shipping-methods-and-services, corresponding services>> are listed below and you can select them. Note that you may need to contact your postNL account manager to obtain additional activation for certain products and services.

The item description refers to the values that you saved in the *Item » Edit item* » _Open item_ menu in the *Texts* tab in the fields *Name1*, *Name2*, *Name3* and *Preview text*. In this step, select one of the four fields.

Furthermore, select whether you want to activate the productive mode or the test mode.

If you ship internationally (icon:toggle-on[role="green"]), you have to enter also the declarations type and the default customs number.

[discrete]
==== Summary

In this step, a summary of all entries that you made in the single steps is listed. You can take a look at all the settings that you carried out, adjust setting within the steps, if needed and complete the assistant afterwards via the summary step.

When you completed the *postNL* assistant and open it again, the following information is displayed:

* In the tile view:

** Shipping setting
** Region
** Name of the API key

* In the table overview:

** Shipping setting
** Region
** Name of the API key

[#available-shipping-methods-and-services]
== Currently available products and services

<<#table-available-products-and-services>> lists all products and services that are currently available via the *postNL* plugin. Note that you may need to contact your postNL account manager to obtain additional activation for certain products and services.

[[table-available-products-and-services]]
.Currently available products and services
[cols="1,3"]
|====
|Product |Service

|Dutch domestic products (destination Netherlands)
a|
* Dutch domestic products +
** Standard shipment +
** Delivery to stated address only +
** Delivery to neighbour + Return when not at home +
** Delivery to stated address only + Return when not at home
* Pickup points +
* Standard pickup points  +
These are e.g. selected supermarkets and bookstores.
* Mailbox parcel +
* Smart returns +
Your customers can show a barcode on their smartphone and have the return label printed in a postNL branch.
* Evening delivery +
Parcels are delivered between 6:00pm and 10:00pm.
* Sunday delivery +
Parcels are delivered between 12:00 noon and 6:00pm.
* Sameday delivery +
Parcels are delivered between 6:00pm and 10:00pm if the order was placed before lunchtime. Contact your postNL account manager for the exact time.
* Guaranteed / Morning delivery +
** on working days before 9:00am +
** on working days before 10:00am +
** on working days before 12:00 noon +
** on working days before 5:00pm


|Destination EU
|Parcels EU +
Currently, shipment from the Netherlands to 27 countries is possible. Contact your postNL account manager for further information.


|Destination Rest of World
|GlobalPack products

|International Mail & Packets
|International Mail & Packets +
Possible options: +
 _Tracked_, _Untracked_ and _Registered_


|====

[#register-order]
== Registering an order

In the *Orders » Shipping centre* menu in the *Register* tab, you can register your orders with postNL and simultaneously transmit the order data to the postNL. To do so, proceed as follows.

[.instruction]
. Go to *Orders » Shipping centre*.
. Select the option *open* from the drop-down list *Shipping status*.
. Select the option *postNL* from the drop-down list *Shipping service provider*.
. Click on the magnifying glass (icon:search[role="blue"]). +
→ You see a list of open shipping orders for postNL.
. Click on the *Register* tab.
. Select the option *postNL* from the drop-down list *Shipping service provider*.
. Select the order status from the drop-down list *Change order status*. Select the status that you want the orders to receive after they are registered. +
*_Note:_* You can combine this function using an <<automation/event-procedures#, event procedure>> which, for example, automatically books outgoing items.
. Select the orders that you want to register with postNL.
. Click on *Register* (icon:cog[]) to transfer the order data to postNL.

For further information about registering orders, refer to the <<fulfilment/shipping-centre#, Using the shipping centre>> page of the manual.
