= mailbox.org migration
:lang: en
include::{includedir}/_header.adoc[]
:description: This page explains how you can migrate your mailboxes hosted by plentymarkets to mailbox.org.
:position: 9

[TIP]
.Existing plentymarkets customers only
====
The migration described here is only relevant to plentymarkets customers with systems created after June 23rd 2016 for whom plentymarkets hosted email accounts.
====

Since January 2017, plentymarkets no longer offers customers an email hosting service. We recommend the external email hosting provider link:https://mailbox.org/business/[mailbox.org^]. If you used email accounts hosted by plentymarkets, you need to migrate any mailboxes you still need to mailbox.org.

Go to **System » System settings » Settings » User » Accounts** to start migrating the email accounts of your system users. During this migration, all your email accounts hosted by plentymarkets are migrated to mailbox.org at once. For each plentymarkets email account, one mailbox is created at mailbox.org. For plentymarkets email accounts with more than one email address, you select a main email address before migration. For all other email addresses associated with this email account, aliases will be created for the mailbox.org mailbox. You select a fee for each mailbox. You are billed through your plentymarkets contract.

[WARNING]
.Provider change does not include migration of your emails
====
The email messages saved in your plentymarkets email accounts are not migrated to mailbox.org during this change of your provider. In addition, you can no longer access your old plentymarkets mailboxes. You can find information on how to migrate any locally saved emails in the <<basics/working-with-plentymarkets/_mailbox-migration#48, Migrating email messages to mailbox.org>> chapter.
====

[#10]
== Preparing for migration

We recommend the following steps to prepare for migration of your email accounts from plentymarkets to mailbox.org.

* plentymarkets bills the hosting of mailboxes at mailbox.org on a per-mailbox basis. As such, check if you still need all email accounts saved in plentymarkets before the migration. Delete any email accounts you no longer need before the migration.
* The number of email addresses (aliases) per mailbox influences the fee charged for this mailbox. As such, check if you still need all email addresses in your system before migrating to mailbox.org.

[#20]
== Migrating mailboxes to mailbox.org

Once you have checked your email accounts, you are ready to migrate your mailboxes to mailbox.org. Proceed as described below to start migration.

[.instruction]
Migrating mailboxes to mailbox.org:

. Log into your plentymarkets back end as an admin user.
. Go to **System » System settings » Settings » User » Accounts**.
. Click on **My account**.
. Open the **Email** tab. +
→ A list of all email accounts hosted by plentymarkets is shown.
. Click on **Change email provider**. +
→ The **Change email provider** will open.
. Click on **Continue**. +
→ For email accounts with more than one email address, a dropdown list becomes available in the **Main email address** column.
. Select a main email address for each email account, e.g. the email address at which the system user receives the most emails. +
→ All other email addresses associated with this email account will be created as an alias at mailbox.org.
. Click on **Save address selection and continue**. +
→ The mailboxes are listed. Mailboxes shown in red require additional settings.
. Click on the first mailbox shown in red. +
→ A configuration window will open.
. Check the fields **First name** and **Last name** and correct this information if necessary.
. Enter a **Password**.
. Confirm the password by entering it in the **Repeat password** field.
. Select a fee for this mailbox.
. **Save** the settings.
. Repeat these steps for all other mailboxes shown in red.
. Click on **Confirm costs and change provider**. +
→ The migration of your mailboxes is started. The mailboxes and aliases are created on the mailbox.org server.

[#30]
== Accessing your mailbox.org mailboxes

After migration, you can access your new mailboxes via the link:https://mailbox.org/en/[mailbox.org website^]. You can find information on how to set up the new mailbox.org mailbox in your local email program in the link:https://support-en.mailbox.org/knowledge-base/articles/e-mail-setup[mailbox.org knowledge base^].

[#40]
== Changing the email server's access data in plentymarkets

For plentymarkets to continue to send emails such as order confirmations on your behalf, you need to save the new <<crm/sending-emails#100, access data>> of the mailbox.org mailbox from which you want to send these emails in the **System » System settings » Client » Select client » Email » Access data**.

[#50]
== Select basic fee

By default, mailboxes are assigned to mailbox.org's monthly basic fee **Business Reseller** after migration. This basic fee applies to all mailboxes in your plentymarkets system including all clients. The basic fee is free. However, it does not include support by mailbox.org. You can <<basics/admin-tasks/manage-users#46a, change>> your basic fee model at any time.
//  h2>Nach der Migration auf alte plentymarkets Postfächer zugreifen<a id="460." name="460."></a></h2> <p>Nach der Migration sind Ihre alten plentymarkets Postfächer noch 14 Tage zugänglich. Zugriff haben Sie auf diese Postfächer per <strong><a href="{% Link(742) %}">Webmail</a></strong>. Auch lokale E-Mail-Programme, z.B. Mozilla Thunderbird, können weiterhin mit dem plentymarkets E-Mail-Server kommunizieren. Dies ist jedoch nicht mehr über den Server <strong>mail.Ihre-Domain.tld</strong> möglich, sondern nur noch über den Server <strong>mail.plentymarkets.com</strong>. Passen Sie daher die Server-Einstellungen in Ihrem lokalen E-Mail-Programm an. Das Vorgehen wird hier am Beispiel von Mozilla Thunderbird beschrieben.</p> <h5>Server-Einstellungen in Ihrem lokalen plentymarkets Postfachs ändern:</h5> <ol> <li>Öffnen Sie Mozilla Thunderbird.</li> <li>Klicken Sie links in der Übersicht auf das Postfach.<br /> → Die Einstellungen des Postfachs werden angezeigt. </li> <li>Klicken Sie auf <strong>Kontoeinstellungen bearbeiten</strong>.<br /> → Ein Fenster wird geöffnet. </li> <li>Klicken Sie in der Übersicht links auf <strong>Server-Einstellungen</strong>.<br /> → Die Server-Einstellungen des Postfachs werden eingeblendet. </li> <li>Prüfen Sie den Inhalt des Felds <strong>Server:</strong>.</li> <li>Ersetzen Sie <strong>mail.Ihre-Domain.tld</strong> durch <strong>mail.plentymarkets.com</strong>.<br /> → Wenn das Feld bereits den Server <strong>mail.plentymarkets.com</strong> enthält, sind keine Änderungen erforderlich. </li> <li>Klicken Sie auf <strong>OK</strong>, um die Einstellung zu speichern.</li> </ol

[#60]
== Migrating old email messages to mailbox.org

The emails previously saved in your plentymarkets email accounts are not migrated to your new mailbox.org mailboxes during this change of your email provider. You no longer have access to the plentymarkets mail server to access old email messages. You can only migrate old email messages to your new email provider if these are saved in a local email program.

* IMAP: Copy your emails via a local email program (e.g. Mozilla Thunderbird) to the mailbox.org server using the transmission protocol IMAP.
* POP3: You forward your emails from your local email program to the mailbox.org server.

These options are described below.

//  h3>Externen Dienstleister mit der Migration beauftragen (empfohlen)</h3> <p>Beauftragen Sie nach dem Wechsel zu mailbox.org einen professionellen Anbieter mit der Migration Ihrer E-Mails, z.B. <strong><a href="https://www.email-umzug.de/" target="_blank">audriga</a></strong>. Mit audriga können Sie sowohl E-Mails aus IMAP-Postfächern als auch aus den meisten POP3-Postfächern umziehen.</p> <p>Für eine Migration benötigt der Anbieter in der Regel folgende Informationen:</p> <ul> <li>Alten und neuen E-Mail-Provider</li> <li>plentymarkets E-Mail-Server <strong>mail.plentymarkets.com</strong></li> <li>Benutzernamen und Passwörter Ihrer alten Postfächer</li> <li>Benutzernamen und Passwörter Ihrer neuen Postfächer</li> </ul> <p>Informationen zum weiteren Vorgehen erhalten Sie vom Anbieter.</p
[#70]
=== Migrating your emails using a local email program and IMAP

If you do not want to charge an external provider with the migration, you can migrate your emails from your plentymarkets account to your new mailbox.org account using a local email program. We recommend that you proceed as described below. The description is based on the email program link:https://www.mozilla.org/de/thunderbird/[Mozilla Thunderbird^]. Note that this migration may take a long time depending on the number and size of your emails. As such, if your emails are organized in subfolders it is advisable to move these folders separately.

[.instruction]
Migrating emails in Thunderbird, IMAP:

. Open Mozilla Thunderbird.
. Change the <<basics/working-with-plentymarkets/_mailbox-migration#460, server settings>> in your local plentymarkets mailbox.
. In addition to your plentymarkets mailbox, set up your new mailbox.org mailbox in Mozilla Firefox as described link:https://support.mailbox.org/knowledge-base/article/einrichtung-mit-mozilla-thunderbird[here^].
. Select the transmission protocol **IMAP**.
. In the left side view, expand all subfolders of your plentymarkets mailbox.
. Click on the first subfolder and drag and drop it to the new mailbox. +
→ Mozilla Thunderbird synchronises your local data with the mailbox.org mailbox and uploads the emails to the mailbox.org IMAP server.
. Repeat the procedure until you have copied all folders of the mailbox.

[#80]
=== Migrating your emails using a local email program and POP3

If you select the outdated transmission protocol POP3 for communication of a local email program with the mailbox.org server, you can not synchronise your emails using a local email program. This is because POP3 only allows the retrieval of data from the server. However, if you want to use POP3, we recommend that you proceed as described below.

[.instruction]
Migrating emails in Thunderbird, POP3:

. Open Mozilla Thunderbird.
. Change the <<basics/working-with-plentymarkets/_mailbox-migration#460, server settings>> in your local plentymarkets mailbox.
. In addition to your plentymarkets mailbox, set up your new mailbox.org mailbox in Mozilla Firefox as described link:https://support.mailbox.org/knowledge-base/article/einrichtung-mit-mozilla-thunderbird[here^].
. Select the transmission protocol **POP3**.
. In the left side view, expand all subfolders of your plentymarkets mailbox.
. Click on the first subfolder and drag and drop it to the new mailbox. +
→ The emails are saved locally in your new mailbox. However, they are not synchronised with the mailbox.org server because the transmission protocol POP3 does not allow uploading emails to the server.
. Repeat the procedure until you have copied all folders of the mailbox.
. If you want to save the emails on the mailbox.org server, you need to forward them to the email address at mailbox.org. To maintain the sender and content of the message, you can use tools such as the free Thunderbird add-on link:http://mailredirect.sourceforge.net/index.html[mailredirect^].

Learn more about migrating your mailboxes to mailbox.org in the following video tutorial:

video::174637467[vimeo]
