= Managing boards
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Board, Boards
:description: Learn how to manage boards in plentymarkets.
:position: 40
:url: basics/working-with-plentymarkets/boards
:id: KWBLPJJ

When using boards you can visualise the workflow of a project or a working process within your company. Common boards consist of 3 columns: _To do_, _Doing_ and _Done_. You decide about the structure of the board and how many columns you add.

[#5]
== Setting the visibility for back end users

In order that the *Start » Boards* menu is visible and editable for users with *Back end* access, the menu visibility must be activated in the user account.

[.instruction]
Setting the visibility for back end users:

. Go to *System » System settings » Settings » User » Rights » User*. +
→ The overview opens.
. *_Optional_*: In the filter settings on the left-hand side, enter an ID or a name to limit the search results.
. Click on *Search*. +
→ The accounts that correspond to the search criteria entered are displayed. +
*_Tip:_* Accounts that are shown greyed out have admin rights.
. Click on the account for that you want to activate the visibility and the rights. +
→ The view *Rights* opens.
. In the *Menu visibility* area, expand the *Start* option.
. Activate the option *Boards*. +
→ *_Note:_* In the *Rights* area, the option for *Start > Boards* is automatically activated.
. *Save* the settings. +
→ The *Start » Boards* menu is visible and editable for the back end user.

[#10]
== Creating a board

Proceed as described below to create a board.

[.instruction]
Creating a board:

. Go to *Start » Boards*. +
→ *_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen.
. → The *Boards* tab opens in a new tab.
. Click on *Create new board*. +
→ The window *Create new board* opens.
. Enter the name of the board.
. *Save* the settings. +
→ The board is created and added to the list.


[#20]
== Adding a column

Proceed as described below to add columns to the board. You can add as many columns as you like.

[.instruction]
Adding a column:

. Go to *Start » Boards*. +
→ *_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen.
. → The *Boards* tab opens in a new tab.
. Click on the board that you want to edit.
. Click on *Add new column*. +
→ The column is added to the left side.
. Enter the name of the column.
. Add further columns in the same way until you have the desired number of columns for the board. +
→ *_Tip:_* You can change the position of the columns.

[#30]
== Adding a card


Proceed as described below to add cards to the board. You can add as many cards as you like.

[.instruction]
Adding a card:

. Go to *Start » Boards*. +
→ *_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen.
. → The *Boards* tab opens in a new tab.
. Click on the board that you want to edit.
. Click on *Add new card* in the column that you want to add a card to.
. Enter the name of the card.
. Click on *Save new card*.
. Add further cards in the same way until you have the desired number of cards for the board.

[#40]
== Editing a card

You can edit the cards on the board at any time. Link the cards to a contact, an order and a ticket, for example, or add an owner and tags. To do so, proceed as described below.

[.instruction]
Editing a card:

. Go to *Start » Boards*. +
→ *_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen.
. → The *Boards* tab opens in a new tab.
. Click on the board that you want to edit.
. Click on the card's arrow in the right to edit the card. +
→ The settings menu opens.
. Carry out the settings. Pay attention to the information given in <<table-boards-edit-card>>.

[[table-boards-edit-card]]
.Settings in the *Start » Boards* menu
[cols="1,3"]
|====
|Setting| Explanation

|*Edit card*
|Enter the text for the card. If required, you can format the text.

|*Delete card*
|Delete the card by clicking on *Delete card*.

|*Link contact*
|Enter the contact ID to link the card to the contact. +
*_Note:_* When the card is linked to the contact, a symbol is displayed on the card. Via this symbol, open the contact directly in the *CRM » Contacts* menu or delete the link to the contact.

|*Link ticket*
|Enter the ticket ID to link the card to the ticket. +
*_Note:_* When the card is linked to the ticket, a symbol is displayed on the card. Via this symbol, open the ticket directly in the *CRM » Ticket system* menu or delete the link to the ticket.

|*Link order*
|Enter the order ID to link the card to the order. +
*_Note:_* When the card is linked to the order, a symbol is displayed on the card. Via this symbol, open the order directly in the *Orders » Edit orders* menu or delete the link to the order.

|*Add user*
|Select the owner from the list in order to add this owner to the card. +
When the owner is added to the card, a symbol with the owner's initials or the first letter of the name is displayed on the card. +
*_Tip:_* In order to remove the owner from the card, move the cursor over the symbol and click on *Delete reference*.

|*Add tag*
|Select the tag from the list in order to add this tag to the card. +
*_Important:_* Only those tags that were created in the *System » System settings » Settings » Tags* menu are displayed in the list. For further information, refer to the <<basics/working-with-plentymarkets/tags#, Tags>> page of the manual.

|====

[#50]
== Editing a board

When opening the menu *Start » Boards*, you see the number of cards and columns, the name of the board as well as the time period of the last change on every card that you created. Click on *Rename board* to enter a new name for the board. Click on *Delete board* to delete the board.

In order to edit boards, click on the name of the board. You can add new columns and cards and edit the cards. Pay attention to the information given in <<table-boards-edit-card>>.

[#60]
== Setting up event procedures

Go to the *System » System settings » CRM » Ticket system » Events* menu to create event procedures that e.g. automatically move the cards on your boards to a column that you determined once a certain event takes place. It is also possible to move cards to another board. Furthermore, you can select a prefix for newly created cards or delete cards once a certain event takes place.

For further information about creating event procedures, refer to the chapter <<crm/using-the-ticket-system#2900, Automatically sending email template>> on the <<crm/using-the-ticket-system#, Using the ticket system>> page of the manual.
