= Customising the user account
:lang: en
include::{includedir}/_header.adoc[]
:description: Working with plentymarkets: Set up your preferred shortcuts and your personal signature and customise your own user account in the plentymarkets system.
:position: 20

On this page, you will find all the information about the settings in plentymarkets that you only have to set up once in order to customise your user account. Of course you can change these settings at any time.

[#10]
== Setting the complimentary close

Go to the **System » Settings » User » Accounts** menu and enter a text in the **My account** area. This text is automatically added as a complimentary close at the end of your messages and comments in the ticket system. Generally, this text consists only of a closing and your name. When sending emails from the ticket system, the complimentary close and the signature will automatically be added to the end of the email. You will find a description of how to set up your signature in the next chapter.

[.instruction]
Setting the complimentary close:

. Go to **System » Settings » User » Accounts**.
. Click on **My account**.
. Open the **Complimentary close** tab.
. Enter your complimentary close.
. **Save** the settings.

[#20]
== Setting the signature

Go to the **System » Settings » User » Accounts** menu and enter a text in the **My account** area. This text is automatically added as a signature at the end of your messages and comments in the ticket system. Generally, this text consists of your contact details as well as information about where your company is registered and its registration number. Depending on your company's legal form, the name of the company, the chief executive officer and, if applicable, the European VAT number are all mandatory entries. When sending emails from the ticket system, the complimentary close and the signature will automatically be added to the end of the email.

[TIP]
.Template variable for the signature
====
The template variables **$Signature** and **$SignatureHTML** contain the complimentary close.
====

[.instruction]
Setting the signature:

. Go to **System » Settings » User » Accounts**.
. Click on **My account**.
. Open the **Signature** tab.
. Enter your signature.
. **Save** the settings.

[WARNING]
.Mandatory entries in emails
====
Since the beginning of 2007, mandatory entries for email signatures in Germany correspond to those for company business letters. Non-compliance can result in a fine or in a costly warning being issued by a competitor. +
Read up on the legal regulations for signatures in your own country or contact a legal adviser for such information.
====

[#30]
== Changing personal settings in the My account area

Go to the **System » Settings » User » Accounts** menu and open the **My account » Personal settings** area to change the settings of the user currently logged into the system. Therefore, you can only see this tab in your own user account. The tab is divided into 3 tabs with settings that only apply to you personally. These tabs are **General**, **Shortcuts** and **Favourites**.

[#40]
=== Changing general settings

In the **General** tab you determine whether you want to receive a warning if tabs are open and you try to close the window. You can also reset all user-specific settings.

[cols="a,a"]
|====
|Button |Explanation

|**Reset messages**
|Users can deactivate certain messages, e.g. the message that is displayed when plentymarkets needs to be reloaded in order for updates to go into effect. This setting is saved for each individual user. Click on this button again to reset all of the relevant settings for the user. For example, all of the messages that were deactivated will be displayed again.

|**Reset all**
|Resets all of the user-specific settings, e.g. the messages described above, the content and column widths in tables, any favourites, etc.

|**Warn if tabs are open and the window is to be closed**
|**Activate** = A warning will be displayed if you try to close a window while tabs are still open. +
**Deactivate** = The window will be closed without warning.
|====

__Table 1: options in the **Personal settings » General** tab__

[#50]
=== Setting up shortcuts

Default shortcuts are saved in this tab. Shortcuts are used for many functions that are carried out on a regular basis. You can use shortcuts to open important menus in plentymarkets or to switch between tabs and tab levels. For example, the shortcut **Alt + I** opens the item overview. **Alt + W** is used to close the tab again.

Learn more about shortcuts in the following video tutorial:

video::99954261[vimeo]
[IMPORTANT]
.Shortcuts are user-specific and some combinations are not possible
====
This tab is only visible in your own user account. You are the only person who can edit your shortcuts.

Do not use any shortcut that is specific to an operating system. Shortcuts differ from one operating system to the next. Example: The **F** keys. +
The combination **cmd / Ctrl + W** is reserved for the browser and is therefore not possible.
====

[cols="a,a"]
|====
|Shortcut |Explanation

2+|Global shortcuts

|**Alt + W**
|Closes the current tab.

|**Shift + Alt + DOWN (arrow down)**
|Moves down one tab level.

|**Shift + Alt + UP (arrow up)**
|Moves up one tab level.

|**Shift + Alt + RIGHT (arrow right)**
|Moves one tab to the right.

|**Shift + Alt + LEFT (arrow left)**
|Moves one tab to the left.

|**Alt + R**
|Reloads the current tab.

|**Alt + ESC**
|Logs out the user and locks the backend.

2+|Open areas

|**Alt + I**
|Opens the **Item » Edit item** menu.

|**Alt + O**
|Opens the **Orders » Edit orders** menu.

|**Alt + Y**
|Opens the **Item » Categories** menu.

|**Alt + C**
|Opens the **CRM » Edit customer** menu.

|**Alt + T**
|Opens the *CRM » Ticket system* menu.

|**Alt + N**
|Opens the **CRM » Edit customer** menu and opens the **New customer** tab.

|**Alt + M**
|Opens the **Customer data**.

|**Alt + S**
|Opens the **online store**.

|**Alt + E**
|Opens the online store with the inline editing function.

|**Alt + P**
|Only available in plentymarkets Client. Opens the **Processes** menu.

2+|Edit order

|**Shift + Alt + N**
|Opens the customer notes in an order; available in all tabs of the order.

|**Shift + Alt + A**
|Opens the order notes in an order; available in all tabs of the order.
|====

__Table 2: **shortcuts**__

[NOTE]
.Shortcuts can be customised
====
The default shortcuts can be changed. Change the shortcuts as desired and click on **Save**.

Click on **Reset shortcuts** to reset the shortcuts to their default settings.
====

[#60]
=== Displaying favourites

All menu paths saved as favourites are displayed in this tab. Favourites can also be deleted in this menu. Use the **Up** and **Down** arrows for sorting your favourites. This tab is only visible in your own user account. For further information about adding and deleting favourites , refer to the <<basics/working-with-plentymarkets/general-functions#80, Setting up general functions>> page of the manual.

