= Carrying out data cleansing
:lang: en
include::{includedir}/_header.adoc[]
:keywords: cleansing, data cleansing, data clean-up, data cleanup, data purge, delete automatically, delete addresses, delete unused addresses
:description: Learn how to automatically delete data records in your plentymarkets system.
:position: 55


This page of the manual describes how to delete certain data records after a certain time period has expired. You determine this time period in the *System » Settings » Data » Cleansing* menu.

== Setting the visibility of the menu for variable users

In order that the *System » Settings » Data » Cleansing* menu is visible for users with the user class *Variable*, the menu must be activated in the user account.

In addition, rights in the *REST API* menu must be activated.

[.instruction]
Setting the visibility of the menu for variable users:

. Go to *System » Settings » User » Accounts*.
. Open the user with the user class *Variable* for whom you would like to activate the visibility of the menu.
. Open the *Right* tab.
. Click on the *Menu* tab.
. Expand the section *Settings » Basic settings » Data*.
. Activate the option *Cleansing*.
. Open the *REST API* tab.
. Expand the section *Data cleansing*.
. Activate the option *Show configuration* and *Save configuration*.
. *Save* the settings.

== Entering deletion values

In order that data records are deleted in your plentymarkets system after a certain time period has expired, you must enter values for this time period. To do so, proceed as follows.

[NOTE]
.Further functions will be added to this menu step by step
====
Currently, you can automatically delete unassigned addresses. Step by step, further areas will be added to this menu.
====

[.instruction]
Entering deletion values:

. Go to *System » Settings » Data » Cleansing*.
. Enter a value in the input field.
. Pay attention to the information given in <<table-settings-data-cleansing>>.
. *Save* the settings.


[[table-settings-data-cleansing]]
.Settings in the System » Settings » Data » Cleansing menu
[cols="1,3"]
|====
|Setting|Explanation

|Deletion of unused addresses (after days)
|Enter the number in days. Maximum possible value = 365 days. After this time period has expired, unused addresses are automatically deleted from your plentymarkets system. Unused addresses are those addresses that do not have any relation. +
*_Important:_* Addresses are only deleted if the toggle button was activated and the settings saved. +
If you do not want to delete addresses after the value entered, deactivate the toggle button and save this setting.
|Deletion of unused contacts (after days)
|Enter the number in days. After this time period has expired, unused contacts are automatically deleted from your plentymarkets system. Unused contacts are those contacts that do not have any relation. +
*_Important:_* Contacts are only deleted if the toggle button was activated and the settings saved. +
If you do not want to delete contacts after the value entered, deactivate the toggle button and save this setting.
|====

[NOTE]
.Number of data records to be deleted
====
Currently, the number of the addresses to be deleted is 5,000 data records per day. Further data records that will be added this menu and that can be deleted also via this menu, initially get a limit of 2,000 data records. plentymarkets will monitor this behaviour and adjust this to a higher value, if necessary.
====

== Automatically deleting tickets

Delete tickets automatically from your ticket system. This setting is not carried out in the *System » Settings » Data » Cleansing* menu, but via the procedure manager in the ticket system in the *System » CRM » Ticket system » Procedures* menu.

Further information about the ticket system as well as an example scenario can be found on the <<crm/using-the-ticket-system#3000, Using the ticket system>> page of the manual.

== Viewing the log

All changes that have been made in the *System » Settings » Data » Cleansing* menu are logged in the *Data » Log* menu for a period of 4 weeks: The date and time, the user as well as the old and new values are logged.

For further information about the log, refer to the <<basics/working-with-plentymarkets/datalog#, Data log>> page of the manual.
