= Managing tags
:lang: en
include::{includedir}/_header.adoc[]
:keywords: tag, tags, create tag
:description: Learn how to manage tags in plentymarkets.
:position: 110

Tags are keywords that can be used to mark texts and pages. In plentymarkets, tags are created and managed centrally in one menu. The tags can then be used in different areas, such as in *categories* and the *ticket system*. Tags can also contain spaces. When a tag consists of more than one word, it is possible to separate these words with spaces.

[#100]
== Creating a tag

The following section explains how to create tags. You determine whether the tags can be used in all available areas or only in certain areas of plentymarkets.

[.instruction]
Creating a tag:

. Go to *System » Settings » Tags*.
. Click on *Create a new tag*. +
→ A window opens on the right-hand side.
. Carry out the settings. Pay attention to the information given in <<table-tag-settings>>.
. *Save* the settings. +
→ The tag is created and added to the list.

[[table-tag-settings]]
.Tag settings
[cols="1,3"]
|====
|Setting |Explanation

|*Name*
|Displays the name of the tag. This name is *_not linked to any language_*.

|*Colour*
|Select a colour for the tag. This setting is optional.

|*Visibility*
|Select the visibility area such as *Category* or *Ticket*. Or select *all* to make the tag available in all areas.

|*Name of the language*
|Create a tag in another *language* or edit the tag for another language. For further information, refer to the <<basics/working-with-plentymarkets/tags#200, Adding further languages>> chapter.
|====

[#200]
== Adding further languages

You can add further languages to existing tags. To do so, proceed as follows:

[.instruction]
Adding further languages:

. Go to *System » Settings » Tags*.
. Click on *Search*. +
→ All tags that have been created are displayed.
. Select the tag from the list. +
→ A window opens on the right-hand side.
. Click in the line of the language and enter the translation.
. *Save* the settings.

[#300]
== Filtering by tags

There are three possibilities for filtering tags. You can filter the tags by *name*, *visibility* and *language*.

[.instruction]
Filtering by tags:

. Go to *System » Settings » Tags*.
. Select one or multiple filters. Pay attention to the information given in <<table-tag-filter>>.
. Click on *Search*. +
→ The tags that correspond to the search criteria entered are displayed.

[[table-tag-filter]]
.Tag filters
[cols="1,3"]
|====
|Setting |Explanation

|*Name*
| Enter the name of the tag. If all languages were selected, all languages are included here as well. However, only the value that was entered under *Name* is displayed.


|*Visibility*
|Select one visibility area or the setting *All*.

|*Language*
|Select a language or the setting *All*.

|====
