= Managing tasks and calendars
:lang: en
include::{includedir}/_header.adoc[]
:keywords: task, tasks, ticket task, ticket tasks, calendar, appointment, meeting, owner, right, access right, read, write, read & write, read and write, CalDAV, caldav, CALDAV, CalDAV interface, synchronise calendar, external calendar tool
:description: Learn how to manage tasks and calendars in plentymarkets.
:position: 50

Find out how to manage <<basics/working-with-plentymarkets/tasks-and-calendars#100, tasks>> and <<basics/working-with-plentymarkets/tasks-and-calendars#600,calendars>> here.

[#100]
== Managing tasks

Use the *Start » Tasks* menu to manage duties for all of the users in the system. For example, a task could be "Call customer xy". You can see how much progress has been made towards completing a task. This helps you plan your business processes and improve internal processes.

You can create tasks not only in the *Start » Tasks* menu, but also in a ticket in the <<crm/using-the-ticket-system#4000,ticket system>>. This allows you to directly create a task during a customer phone call, for example. If a task is created in the *CRM » Ticket system » Open ticket » Tab: Tasks*, then it is linked to the ticket. This link is also visible in the overview of tasks under *Start » Tasks*.

[#200]
=== Setting the visibility of tasks for variable users

In order that the *Start » Tasks* menu is visible for users with the user class *Variable*, the menu must be activated in the user account.

[.instruction]
Setting the visibility of tasks for variable users:

. Go to *System » Settings » User » Accounts*.
. Open the user with the user class *Variable* for whom you would like to activate the visibility of the menu.
. Click on the *Right* tab.
. Click on the *Menu* tab.
. Expand the *Start* area.
. Activate the option *Tasks*.
. *Save* the settings.

[#300]
=== Creating a task

Proceed as described below to create a task. A consecutive ID is automatically assigned by the system and cannot be changed.

[.instruction]
Creating a task:

. Go to *Start » Tasks*. +
→ *_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen.
. Click on *New task*. +
→ The tab *New task* will open.
. Carry out the settings. Pay attention to the information given in <<table-create-task>>.
. *Save* the settings.

[[tablel-create-task]]
.Creating a task
[cols="1,3"]
|====
| Setting | Explanation

|*Title*
| Enter the title for the task.

|*Priority*
| Select the priority. The priorities range from *0 = gray star* to *5 = two yellow stars*.

|*Progress*
| Select the percentage value. This will show the progress of the task. Users will have to manually change the progress as they complete the task.

|*Flag*
| Select a flag. The flag helps you find tasks again in the future.

|*Owner*
|Select the owner. This is a mandatory setting. The owner is the person responsible for the task.

|*Description*
| Enter the description of the task and format the text, if required.
|====

[#400]
=== Searching for tasks

When opening the menu *Start » Tasks* menu, all tasks with a progress below 100% of the currently active user are displayed as standard. If you have created a task via the <<crm/using-the-ticket-system#4000, ticket system>>, the ticket ID as well as the ticket title are displayed in the overview. By clicking on the ticket ID, the ticket will open directly.

Use the search filters to keep track of your tasks, even if there are a lot of them. The filters also help you find the exact tasks you are looking for.

[.instruction]
Searching for tasks:

. Go to *Start » Tasks*. +
→ All own uncompleted tasks will be displayed because the filter for the progress is set to *<100%* and the active user is pre-selected in the drop-down list *Owner* when opening the menu.
. Click on *Reset* to remove the filters.
. Select the filters. Pay attention to the information given in <<table-search-task>>.
. Click on *Search*. +
→ The tasks that correspond to the search criteria entered will be displayed.

[[table-search-task]]
.Searching for tasks
[cols="1,3"]
|====
| Filter | Explanation

|*Title/Description*
|Enter text to search for the text. This is a full text search. It searches in the task's *title* and *description*. Enter at least 4 characters for the search.

|*ID*
|Enter an ID to search for the task that has this ID. The system automatically assigns consecutive task IDs. This ID cannot be changed.

|*Ticket ID*
|Enter a ticket ID to search for the task(s) that belong(s) to this ticket.

|*Progress*
|Select an operator and the progress. For example, you could search for all of the tasks that have already been completed to 60% or more.

|*Priority*
|Select an operator and the priority. For example, you could search for all of the tasks that have priority 2 or higher.

|*Date of creation*
|Select an operator and the date. For example, you could search for all of the tasks that were created before a specific date.

|*Owner*
|Select an owner to search for the tasks of this owner.

|*Flag*
|Select a flag to search for the tasks that have this flag.
|====

[#500]
=== Editing a task

You can edit tasks at any time in order to adjust the progress bar or to add a description, for example.

[.instruction]
Editing a task:

. Go to *Start » Tasks*. +
→ All own uncompleted tasks will be displayed because the filter for the progress is set to *<100%* and the active user is pre-selected in the drop-down list *Owner* when opening the menu. +
. Click on *Reset* to remove the filters.
. Select the filters. Pay attention to the information given in <<table-search-tasks>> in the <<basics/working-with-plentymarkets/tasks-and-calendars#400, Searching for tasks>> chapter. +
→ The tasks that correspond to the search criteria entered will be displayed.
. Click in the line of the task. +
→ The task will open.
. Carry out the settings. Pay attention to the information given in <<table-create-task>> in the <<basics/working-with-plentymarkets/tasks-and-calendars#300, Creating a task>> chapter.
. *Save* the settings.

[#550]
=== Displaying tasks on the dashboard

You can have your uncompleted tasks displayed on the dashboard. This way you will see at a glance which tasks still need to be done when starting your working day.

Activate the checkbox next to the task when you have finished the task. This task will also be updated in the *Start » Tasks* menu and marked with *100%*.

[.instruction]
Displaying tasks on the dashboard:

. Open your plentymarkets system. +
→ The dashboard will be displayed.
. Select the element *My tasks* from the drop-down list. +
→ The *My tasks* area will be displayed on the dashboard from now on every time you open your plentymarkets system.

Click on *Enter ToDo* in the *My tasks* area to directly open the *Start » Tasks* menu and <<basics/working-with-plentymarkets/tasks-and-calendars#300,create a new task>>.

[#600]
== Managing calendars

The calendar in the *Start » Calendar* menu allows you to make appointments and plan deadlines. This helps you organise your own and your employees' time and improve internal processes.

The calendar displays your appointments. In addition, it shows the appointments of any users whose calenders have been made visible to you and which you have activated in the *filter*.

You can choose to display the day, week or month. Click on the button *Today* to change to the view of the current day.

The filter shows a list of all users for which you at least have read permissions. Place a check mark to display a user's appointments in your calendar. You can display the calendars of multiple users at the same time.

[#650]
=== Setting the visibility of calendars for variable users

In order that the *Start » Tasks* menu is visible for users with the user class *Variable*, the menu must be activated in the user account.

[.instruction]
Setting the visibility of calendars for variable users:

. Go to *System » Settings » User » Accounts*.
. Open the user with the user class *Variable* for whom you would like to activate the visibility of the menu.
. Click on the *Right* tab.
. Click on the *Menu* tab.
. Expand the *Start* area.
. Activate the *Calendar* option.
. *Save* the settings.

[#700]
=== Setting a variable user as owner

Except for the user classes *API* and *Variable*, all <<basics/admin-tasks/manage-users#10, user classes>> are automatically owner of a calendar. The calendar is not available for the user class *API*. For the *Variable* user class, rights need to be granted to use the calendar. To do so, proceed as described below.

The right assigned to a user can be deactivated in the *Owner* tab at any time.

[.instruction]
Setting a variable user as owner:

. Go to *System » Settings » User » Accounts*.
. Open the user with the user class *Variable* who you would like to set as calendar owner.
. Click on the *Owner* tab.
. Activate the *Calendar* option.
. *Save* the settings. +
→ The new tab *Calendar* is visible and can be configured as described in the next chapter.

[#800]
=== Carrying out basic calendar settings and setting access rights for users

Proceed as described below to carry out basic calendar settings such as saving the password and to set the access rights for users. You can select between the settings *No access*, *Read* and *Read & write*.

[.instruction]
Carrying out basic calendar settings and setting access rights for users:

. Go to *System » Settings » User » Accounts*.
. Open the user.
. Click on the *Calendar* tab.
. Carry out the settings. Pay attention to the information given in <<table-calendar-basic-settings>>.
. *Save* the settings.

[[table-calender-basic-settings]]
.Carrying out basic calendar settings
[cols="1,3"]
|====
|Setting |Explanation

|*Server address* +
*Server path* +
*Port*
|Automatically saved by the system. +
The server address and server path are required for configuring an external calendar tool such as Google Calendar.

|*New password*
|A password must be entered during setup of the calendar account. This password will be required for the external calendar tools. The password can be changed at any time. +
*_Important:_* After saving, the password is no longer displayed and cannot be retrieved. +
If you use an external calendar tool, you might need to re-enter the password when the password is changed.

|*Repeat password*
|Enter the password again to confirm it.

|*Description*
|The description is displayed within the information and settings for the calendar.

|*Right*
|Select which users can access this owner's calendar. Also select the type of access right assigned to these users. Users must to be assigned at least read permission in order to see the calendar. +
*No access* = The user has neither read nor write permissions for this owner's calendar. +
*Read* = The user can view the calendar. +
*Write* = The user can edit and delete appointments in the calendar.
|====

[#900]
=== Creating an appointment

Proceed as described below to create an appointment. Depending on your access rights that are set according to <<table-calendar-basic-settings>> , you can also create appointments for other users. You can only create appointments for users for which you have write permissions. You cannot select users for which you do not have write permissions.

[.instruction]
Creating an appointment:

. Go to *Start » Calendar*. +
→ *_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen.
. Select the point in time of the appointment by clicking the time in the calendar. +
→ *_Tip:_* Select the time period for the appointment by clicking the start time and move the cursor to the end time of the appointment.
. Carry out the settings in the *Appointment details* area. Pay attention to the information given in <<table-create-appointment>>.
. *Save* the settings.

[[table-create-appointment]]
.Creating an appointment
[cols="1,3"]
|====
|Setting |Explanation

|*Title*
|Will be displayed in the calendar overview.

|*All day*
|Specifies that the appointment will last the entire day. In the daily and weekly view of the calendar, all appointments will be displayed in the top row. This helps to ensure that the calendar will not become cluttered.

|*From / To*
|The date and time are preselected but can be edited.

|*Type*
|Select the type of appointment from the drop-down list.

|*Calendar*
|Select the owner you want to create the appointment for.

|*Description*
|Enter the description, e.g. further information about the appointment. This description is displayed in the appointment details and visible to all users with access rights to the calendar.
|====

[#1000]
=== Editing an appointment

Click on an appointment to open the appointment details and edit the details.

[.instruction]
Editing an appointment:

. Go to *Start » Calendar*.
. Click on the appointment that you would like to edit. +
→ The window *Appointment details* will be displayed.
. Carry out the changes. Pay attention to the information given in <<table-create-appointment>>.
. *Save* the settings.

[#1100]
=== Deleting an appointment

Delete appointments when they have been created by mistake or when they have become obselete.

[.instruction]
Deleting an appointment:

. Go to *Start » Calendar*.
. Click on the appointment that you would like to delete. +
→ The window *Appointment details* will be displayed.
. Click on *Delete*. +
→ The appointment will be deleted and removed from the calendar overview.

[#1200]
=== Synchronising the calendar with external calendar tools

You can use a link:https://en.wikipedia.org/wiki/CalDAV[CalDAV^] interface to synchronise your calendar with external calendar tools. For example, you can synchronise your calendar with tools such as Mac Calendar or iPad Calendar.

The option *Calendar* must be activated in the *Owner* tab of the user account as described in the <<basics/working-with-plentymarkets/tasks-and-calendars#700, Setting a variable user as owner>>. You need to know the settings for the user in order to carry out the configuration. The settings are saved in the user's *Calendar* tab.

Refer to the external tool's documentation to find out how to synchronise your plentymarkets calendar with the external calendar tool.
