= Managing tasks and calendars
:lang: en
include::{includedir}/_header.adoc[]
:keywords: task, tasks, ticket task, ticket tasks, calendar, calender, appointment, meeting, owner, right, access right, read right, write right, CalDAV, synchronise calendar, external calendar,
:description: Learn how to manage tasks and calendars in plentymarkets.
:position: 50
:url: basics/working-with-plentymarkets/tasks-and-calendars
:id: U0UVIS6

On this page of the manual, you learn how to manage <<basics/working-with-plentymarkets/tasks-and-calendars#100, tasks>> and <<basics/working-with-plentymarkets/tasks-and-calendars#600, calendars>>.

[#100]
== Managing tasks

Use the *Start » Tasks* menu to manage duties for all of the users in the system. For example, a task could be ""Call customer xy". You can see how much progress has been made towards completing a task. This helps you plan your business processes and improve internal processes.

You can create tasks in the *Start » Tasks* menu and in the <<crm/using-the-ticket-system#4000, ticket system>>. This allows you to directly create a task during a customer phone call, for example. If a task is created in the *CRM » Ticket system » Open ticket » Tab: Tasks*, it is linked to the ticket. This link is also visible in the overview of tasks under *Start » Tasks*.

[#200]
=== Setting the visibility of tasks for back end users

In order that the *Start » Tasks* menu is visible for users with *Back end* access, the menu must be activated in the user account.

[.instruction]
Setting the visibility for back end users:

. Go to *System » System settings » Settings » User » Rights » User*. +
→ The overview opens.
. *_Optional_*: In the filter settings on the left-hand side, enter an ID or a name to limit the search results.
. Click on *Search*. +
→ The accounts that correspond to the search criteria entered are shown. +
*_Tip:_* Accounts that are shown greyed out have admin rights.
. Click on the account for that you want to activate the visibility and the rights. +
→ The view *Rights* opens.
. In the *Menu visibility* area, expand the *Start* option.
. Activate the option *Tasks*. +
→ *_Note:_* In the *Rights* area, the option for *Start > Tasks* is automatically activated.
. *Save* the settings. +
→ The *Start » Tasks* menu is visible and editable for the back end user.

[#300]
=== Creating a task

Proceed as described below to create a task. A consecutive ID is automatically assigned by the system and cannot be changed.

[.instruction]
Creating a task:

. Go to *Start » Tasks*. +
→ *_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen.
. Click on *New task*. +
→ The tab *New task* opens.
. Carry out the settings. Pay attention to the information given in <<table-create-task>>.
. *Save* the settings.

[[table-create-task]]
.Creating a task
[cols="1,3"]
|====
| Setting | Explanation

|*Title*
| Enter the title for the task.

|*Priority*
| Select the priority. The priorities range from *0  = grey star* to *5  = 2 yellow stars*.

|*Progress*
| Select the percentage value. This shows the progress of the task. Users have to change the progress manually as they complete the task.

|*Flag*
| Select a flag. The flag helps you find tasks again in the future.

|*Owner*
|Select the owner. Selecting the owner is a mandatory setting. The owner is the person responsible for the task.

|*Description*
|Enter the description of the task and format the text, if required.
|====

[#400]
=== Searching for tasks

When opening the *Start » Tasks* menu, all tasks with a progress below 100% of the currently active user are shown as standard. If you have created a task via the <<crm/using-the-ticket-system#4000, ticket system>>, the ticket ID as well as the ticket title are shown in the overview. By clicking on the ticket ID, the ticket opens directly.

Use the search filters to keep track of your tasks, even if there are a lot of them. The filters also help you find the exact tasks you are looking for.

[.instruction]
Searching for tasks:

. Go to *Start » Tasks*. +
→ All own uncompleted tasks are shown because the filter for the progress is set to *<100%* and the active user is pre-selected in the drop-down list *Owner* when opening the menu.
. Click on *Reset* to remove the filters.
. Select one or several filters. Pay attention to the information given in <<table-search-task>>.
. Click on *Search*. +
→ The tasks that correspond to the search criteria entered are shown.

[[table-search-task]]
.Searching for a task
[cols="1,3"]
|====
| Filter | Explanation

|*Title/Description*
|Enter text to search for the text. This is a full text search. It searches in the task's *title* and *description*. Enter at least 4 characters for the search.

|*ID*
|Enter an ID to search for the task with this ID. The system automatically assigns consecutive task IDs. This ID cannot be changed.

|*Ticket ID*
|Enter a ticket ID to search for the task(s) that belong(s) to this ticket.

|*Progress*
|Select an operator and the progress. For example, you could search for all of the tasks that have already been completed to 60% or more.

|*Priority*
|Select an operator and the priority. For example, you could search for all of the tasks that have priority 2 or higher.

|*Date of creation*
|Select an operator and the date. For example, you could search for all of the tasks that were created before a specific date.

|*Owner*
|Select an owner to search for the tasks of this owner.

|*Flag*
|Select a flag to search for the tasks with this flag.
|====

[#500]
=== Editing a task

You can edit tasks at any time in order to adjust the progress bar or to add a description, for example.

[.instruction]
Editing a task:

. Go to *Start » Tasks*. +
→ All own uncompleted tasks are shown because the filter for the progress is set to *<100%* and the active user is pre-selected in the drop-down list *Owner* when opening the menu. +
. Click on *Reset* to remove the filters.
. Select one or several filters. Pay attention to the information given in <<table-search-task>> in the <<basics/working-with-plentymarkets/tasks-and-calendars#400, Searching for a task>> chapter. +
→ The tasks that correspond to the search criteria entered are shown.
. Click in the line of the task. +
→ The task opens.
. Carry out the settings. Pay attention to the information given in <<table-create-task>> in the <<basics/working-with-plentymarkets/tasks-and-calendars#300, Creating a task>> chapter.
. *Save* the settings.

[#550]
=== Showing tasks on the dashboard

You can have your uncompleted tasks shown on the dashboard. This way you can see at a glance which tasks still need to be done when starting your working day.

Activate the checkbox next to the task when you have finished the task. This task is also updated in the *Start » Tasks* menu and marked with *100%*.

[.instruction]
Showing tasks on the dashboard:

. Open your plentymarkets system. +
→ The dashboard is shown.
. Select the element *My tasks* from the drop-down list. +
→ The *My tasks* area is displayed on the dashboard from now on every time you open your plentymarkets system.

Click on *Enter ToDo* in the *My tasks* area to directly open the *Start » Tasks* menu and <<basics/working-with-plentymarkets/tasks-and-calendars#300, create a new task>>.

Refer to the <<basics/working-with-plentymarkets/customise-user-account#70, Personalising the dashboard>> chapter on the <<basics/working-with-plentymarkets/customise-user-account#, Customising the user account>> page of the manual to learn which elements can also be shown on the dashboard.

[#600]
== Managing calendars

The calendar in the *Start » Calendar* menu of your plentymarkets system allows you to make appointments and plan deadlines. This helps you organise your own and your employees' time and improve internal processes.

The calendar shows your appointments. In addition, it shows the appointments of any users whose calenders have been made visible to you and which you have activated in the *filter*.

You can choose to show the day, week or month. Click on the button *Today* to change to the view of the current day.

The filter shows a list of all users for which you at least have read permissions. Place a check mark to show a user's appointments in your calendar. You can show the calendars of multiple users at the same time.

[#650]
=== Setting the visibility of the calendar for back end users

In order that the *Start » Calendar* menu is visible for users with *Back end* access, the menu must be activated in the user account.

[.instruction]
Setting the visibility of the calendar for back end users:

. Go to *System » System settings » Settings » User » Rights » User*. +
→ The overview opens.
. *_Optional_*: In the filter settings on the left-hand side, enter an ID or a name to limit the search results.
. Click on *Search*. +
→ The accounts that correspond to the search criteria entered are shown. +
*_Tip:_* Accounts that are shown greyed out have admin rights.
. Click on the account for that you want to activate the visibility and the rights. +
→ The view *Rights* opens.
. In the *Menu visibility* area, expand the *Start* option.
. Activate the *Calendar* option. +
→ *_Note:_* In the *Rights* area, the option for *Start > Calendar* is automatically activated.
. *Save* the settings. +
→ The *Start » Calendar* menu is visible and editable for the back end user.

[#700]
=== Setting the back end user as owner

For persons with *Back end* access, the calendar must be activated as described in the following. It is not possible to activate the calendar for persons with *REST API* access.

The right assigned to a user can be deactivated in the *Owner* tab at any time.

[.instruction]
Setting the back end user as owner:

. Go to *System » System settings » Settings » User » Accounts*.
. Open the user account with the *Back end* access.
. Click on the *Owner* tab.
. Activate the *Calendar* option.
. *Save* the settings. +
→ The new tab *Calendar* is visible and can be set up as described in the next chapter.

[#800]
=== Carrying out basic calendar settings and setting access rights for users

Proceed as described below to carry out basic calendar settings such as saving the password and to set the access rights for users. You can select between the settings *No access*, *Read* and *Read & write*.

[.instruction]
Carrying out basic calendar settings and setting access rights for users:

. Go to *System » System settings » Settings » User » Accounts*.
. Open the user.
. Click on the *Calendar* tab.
. Carry out the settings. Pay attention to the information given in <<table-calendar-basic-settings>>.
. *Save* the settings.

[[table-calendar-basic-settings]]
.Carrying out basic calendar settings
[cols="1,3"]
|====
|Setting |Explanation

|*Server address*; +
*Server path*; +
*Port*
|Automatically saved by the system. +
The server address and server path are required for configuring an external calendar tool such as Google Calendar.

|*New password*
|A password must be entered during setup of the calendar account. This password is required for the external calendar tools. The password can be changed at any time. +
*_Important:_* After saving, the password is no longer shown and cannot be retrieved. +
If you use an external calendar tool, you might need to re-enter the password when the password is changed.

|*Repeat password*
|Enter the password again to confirm it.

|*Description*
|The description is shown within the information and settings for the calendar.

|*Right*
|Select which users can access this owner's calendar. Also select the type of access right assigned to these users. Users must to be assigned at least read permission in order to see the calendar. +
*No access* = The user has neither read nor write permissions for this owner's calendar. +
*Read* = The user can view the calendar. +
*Write* = The user can edit and delete appointments in the calendar.
|====

[#900]
=== Creating an appointment

Proceed as described below to create an appointment. Depending on your access rights that are set according to <<table-calendar-basic-settings>>, you can also create appointments for other users. You can only create appointments for users for which you have write permissions. You cannot select users for which you do not have write permissions.

[.instruction]
Creating an appointment:

. Go to *Start » Calendar*. +
→ *_Tip:_* To do so, point your cursor at the plentymarkets logo at the top left of the screen.
. Select the point in time of the appointment by clicking the time in the calendar. +
→ *_Tip:_* Select the time period for the appointment by clicking the start time and move the cursor to the end time of the appointment.
. Carry out the settings in the *Appointment details* area. Pay attention to the information given in <<table-create-appointment>>.
. *Save* the settings.

[[table-create-appointment]]
.Creating an appointment
[cols="1,3"]
|====
|Setting |Explanation

|*Title*
|Is shown in the calendar overview.

|*All day*
|Specifies that the appointment lasts the entire day. In the daily and weekly view of the calendar, all appointments are shown in the top row. This helps to ensure that the calendar does not become cluttered.

|*From / To*
|The date and time are pre-selected but can be edited.

|*Type*
|Select the type of appointment from the drop-down list.

|*Calendar*
|Select the owner you want to create the appointment for.

|*Description*
|Enter the description, e.g. further information about the appointment. This description is shown in the appointment details and visible to all users with access rights to the calendar.
|====

[#1000]
=== Editing an appointment

Click on an appointment to open the appointment details and edit the details.

[.instruction]
Editing an appointment:

. Go to *Start » Calendar*.
. Click on the appointment that you would like to edit. +
→ The window *Appointment details* is shown.
. Carry out the changes. Pay attention to the information given in <<table-create-appointment>>.
. *Save* the settings.

[#1100]
=== Deleting an appointment

Delete appointments when they have been created by mistake or when they have become obsolete.

[.instruction]
Deleting an appointment:

. Go to *Start » Calendar*.
. Click on the appointment that you would like to delete. +
→ The window *Appointment details* is shown.
. Click on *Delete*. +
→ The appointment is deleted and removed from the calendar overview.

[#1200]
=== Synchronising the calendar with external calendar tools

You can use a link:https://en.wikipedia.org/wiki/CalDAV[CalDAV^] interface to synchronise your calendar with external calendar tools. For example, you can synchronise your calendar with tools such as Mac Calendar or iPad Calendar.

The option *Calendar* must be activated in the *Owner* tab of the user account as described in the <<basics/working-with-plentymarkets/tasks-and-calendars#700, Setting the back end user as owner>>. You need to know the settings for the user in order to carry out the configuration. The settings are saved in the user's *Calendar* tab.

Refer to the external tool's documentation to find out how to synchronise your plentymarkets calendar with the external calendar tool.
