= Dashboard (Beta)
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Statistik, Kundenstatistik, Auftragsstatistik, Amazon Statistik, eBay Statistik, Dashboard, Besucherstatistik, Rohdaten, Kennzahlen, Unternehmenskennzahlen
:position: 10
:url: business-entscheidungen/plenty-bi/myview-dashboard
:id: QPO2ICG
:author: team-bi

In der schnelllebigen Welt des Onlinehandels ist es entscheidend, stets den Überblick über die Zahlen und Daten deines Online-Business zu behalten. Damit du als Onlinehändler:in immer auf die aktuellen Kennzahlen deines Unternehmens zugreifen kannst und somit direkt siehst, wo Handlungsbedarf besteht, bietet plentymarkets dir das neue Dashboard. Hier kannst du zahlreiche Kennzahlen, Statistiken, Diagrammtypen und Formatierungen miteinander kombinieren. So richtest du dir flexibel und individuell genau das Dashboard ein, das du brauchst.

Besonders bei der Einrichtung deines ersten Dashboards gibt es einige Punkte zu beachten. Achte besonders auf die vorbereitenden Einstellungen und befolge sorgfältig die Anleitungen in den folgenden Abschnitten:

** <<#200, Kennzahlen anlegen>>
** <<#300, Berechtigungen vergeben>>
** <<#400, Dashboard anlegen>>

[#100]
== Vorbereitende Einstellungen vornehmen

Bevor du dein individuelles Dashboard einrichten kannst, sind nur ein paar vorbereitende Schritte notwendig. Diese werden in den folgenden Kapiteln beschrieben.

[#200]
=== Kennzahlen anlegen

[IMPORTANT]
.Kennzahlen je nach plentyBI-Tarif verfügbar
====
Um Kennzahlen anzulegen, ist die Buchung eines entsprechenden plentyBI-Tarifs notwendig. Öffne dazu das Menü *plentymarkets Logo (Start) » Mein Konto » Verträge*. Im Bereich *plentyBI Tarif buchen* stehen dir plentyBI-Tarife mit verschiedenen Umfängen zur Auswahl. Zusätzlich wird auch im Menü *Einrichtung » plentyBI » Kennzahlen* pro Kennzahl angezeigt, in welchem plentyBI-Tarif sie enthalten ist.
====

Damit Daten im Dashboard angezeigt werden können, musst du zuerst entsprechende Kennzahlen erstellen.

Kennzahlen erlauben dir, verschiedene Datensätze zusammenzustellen. Kennzahlen liefern somit die Basis für die Werte und Daten, die du später auf dem Dashboard anzeigen und nachverfolgen kannst. Pro Kennzahl werden von deinem plentymarkets System sogenannte Dimensionen bereitgestellt. Dimensionen bestimmen, nach welchen Kriterien die Daten der Kennzahl gruppiert werden.
So kannst du pro Kennzahl genau eingrenzen, wie die Daten pro Kennzahl berechnet werden sollen.

//TODO: Beispiel!

Du legst Kennzahlen entweder im eigens dafür vorhandenen Menü oder direkt aus dem Dashboard heraus an. Im Folgenden werden beide Vorgehensweisen erklärt.

[TIP]
.Benutzerrechte beachten 
====
Falls Benutzer:innen ohne Admin-Zugang zu deinem plentymarkets System Kennzahlen anlegen sollen, vergib zuerst die <<#300, notwendigen Benutzerrechte>>.
====

[#210]
==== Kenzahlen im Einrichtungsmenü erstellen

Diese Vorgehensweise bietet sich an, wenn du viele verschiedene Kennzahlen auf einmal anlegen möchtest. <<tabelle-kennzahlen-anlegen>> enthält eine Auflistung der verfügbaren <<#option-keyfigure, Kennzahlen>>. Klicke auf den jeweiligen Link, um detaillierte Informationen zur Einrichtung der Kennzahl und den verfügbaren Einstellungen zu erhalten. 

[.instruction]
Kennzahlen im Einrichtungsmenü erstellen:

. Öffne das Menü *Einrichtung » plentyBI » Kennzahlen*.
. Nimm die Einstellungen gemäß <<tabelle-kennzahlen-anlegen>> vor.
. Speichere icon:save[set=plenty] die Einstellungen.

[[tabelle-kennzahlen-anlegen]]
.Kennzahlen anlegen
[cols="1,3"]
|====

|Einstellung |Erläuterung

| *Name*
| Gib einen Namen für die Kennzahl an.

| [#option-keyfigure]*Kennzahl*
a| Wähle die Kennzahl aus, die angelegt werden soll. Die folgenden Kennzahlen sind verfügbar:

* <<business-entscheidungen/plenty-bi/kennzahlen/umsatz#, Umsatz>>
* <<business-entscheidungen/plenty-bi/kennzahlen/absatz#, Absatz>>
* <<business-entscheidungen/plenty-bi/kennzahlen/versandumsatz#, Versandumsatz>>
* <<business-entscheidungen/plenty-bi/kennzahlen/rohertrag#, Rohertrag>>
* <<business-entscheidungen/plenty-bi/kennzahlen/durchschnittlicher-bestellwert#, Durchschnittlicher Bestellwert>>
* <<business-entscheidungen/plenty-bi/kennzahlen/durchschnittliche-anzahl-auftragspositionen#, Durchschnittliche Anzahl an Auftragspositionen>>
* <<business-entscheidungen/plenty-bi/kennzahlen/retourenquote#, Retourenquote>>
* <<business-entscheidungen/plenty-bi/kennzahlen/auftraege#, Aufträge>>
* <<business-entscheidungen/plenty-bi/kennzahlen/live-auftraege#, Aufträge (Live)>>
* <<business-entscheidungen/plenty-bi/kennzahlen/umsatzsteuer-gesamt#, Umsatzsteuer gesamt>>
* <<business-entscheidungen/plenty-bi/kennzahlen/nachrichten#, Nachrichten>>
* <<business-entscheidungen/plenty-bi/kennzahlen/marktplatz-bestandsinformationen#, Marktplatz-Bestandsinformationen>>
* <<business-entscheidungen/plenty-bi/kennzahlen/marktplatz-variantenvalidierung#, Marktplatz-Variantenvalidierung>>

| *Kommentar*
| Gib hier bei Bedarf einen Kommentar zur Kennzahl ein. Der Kommentar wird an der Kennzahl gespeichert und gibt dir und deinen Mitarbeiter:innen schnell Einblick in eventuelle Besonderheiten oder Vermerke für die Kennzahl.

2+| Bereich *Zielwerte*

| [#option-targetvalue]*für Tage und Wochen*, *für Monate*, *für Quartale*, *für Jahre*
| Trage Zielwerte ein, die von der Kennzahl erreicht werden sollen. Je nach gewünschtem Zeitraum kannst du hier flexibel die Zielwerte eintragen, die du für die Kennzahl planst.

|====

[#220]
==== Kennzahlen über das Dashboard anlegen

Möchtest du auf einem neuen oder bereits eingerichteten Dashboard Kennzahlen hinzufügen? Dann kannst du dies bequem aus dem Dashboard selbst heraus tun.

[IMPORTANT]
.Einstellungsmöglichkeiten für Kennzahlen im Dashboard 
====
Beim Anlegen neuer Kennzahlen über das Dashboard ist es nicht möglich, <<#option-targetvalue, Zielwerte>> für diese Kennzahlen einzugeben. Diese Einstellungen kannst du jedoch im Nachhinein im Menü *Einrichtung » plentyBI » Kennzahlen* für die entsprechende Kennzahl ergänzen.
====

[.instruction]
Kennzahlen über das Dashboard anlegen:

. Öffne das Menü *plentymarkets Logo (Start) » Dashboard (Beta)*.
. Klicke auf *Ansicht bearbeiten* icon:design_inline_edit[set=plenty]. +
→ Das Einstellungsmenü öffnet sich.
. Platziere per Drag-and-drop ein Element aus dem Einstellungsmenü auf dem Dashboard.
. Bewege den Mauszeiger über das Element und klicke auf icon:design_inline_edit[set=plenty]. +
→ Das Einstellungsmenü für das Element öffnet sich.
. Platziere per Drag-and-drop ein Element innerhalb der blau umrandeten Fläche.
. Bewege den Mauszeiger über das Element und klicke auf icon:design_inline_edit[set=plenty].
. Klicke im Einstellungsmenü auf *Kennzahl* und wähle die Option *Neue Kennzahl erstellen*. +
→ Ein Fenster zur Einrichtung der neuen Kennzahl öffnet sich.
. Gib einen *Namen* für die Kennzahl ein.
. Nimm die Einstellungen wie in <<tabelle-kennzahlen-anlegen>> beschrieben vor.
. Klicke auf *Speichern* icon:save[set=plenty].

[#300]
=== Benutzerrechte vergeben

Bei der Arbeit mit Kennzahlen solltest du entscheiden, welche Mitarbeiter:innen welche Kennzahlen einsehen dürfen. Benutzer:innen mit Admin-Zugang zu deinem plentymarkets System können alle Kennzahlen einsehen sowie neue Kennzahlen anlegen.
Benutzer:innen mit einem Zugang vom Typ *Backend* muss diese Berechtigung durch eine:n Benutzer:in mit Admin-Zugang erteilt werden.

Gehe wie unten beschrieben vor, um festzulegen, welche Kennzahlen für welche Benutzer:innen sichtbar sein sollen.

[.instruction]
Berechtigungen zur Einsicht von Kennzahlen erteilen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Übersicht wird geöffnet. +
*_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen* icon:search[role="blue"]. +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das gewünschte Konto.
. Klicke auf *Ressourcen*.
. Klicke auf *Kennzahlen*.
. Aktiviere alle Kennzahlen, die für das Benutzerkonto sichtbar sein sollen. +
*_Optional:_* Klicke auf *Alle Kennzahlen*, wenn sämtliche Kennzahlen für das Benutzerkonto sichtbar sein sollen.
. *Speichere* icon:save[set=plenty] die Einstellungen.

Du möchtest Mitarbeiter:innen ohne Admin-Zugang zum System erlauben, Kennzahlen anzulegen? Dann nimm zusätzlich noch die folgenden Einstellungen vor.

[.instruction]
Berechtigung zum Anlegen von Kennzahlen erteilen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Übersicht wird geöffnet. +
*_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen* icon:search[role="blue"]. +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das gewünschte Konto.
. Aktiviere im Bereich *plentyBI* die Option *Kennzahlen*.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[#400]
== Dashboard einrichten

Sobald du die <<#100, vorbereitenden Einstellungen>> vorgenommen hast, kannst du mit der Einrichtung des Dashboards beginnen. 

Grundsätzlich legst du auf einem neuen Dashboard zuerst verschiedene Bereiche an. Diese Darstellungsbereiche befüllst du im zweiten Schritt mit Daten, die in Form verschiedener Elemente angezeigt werden. Pro Bereich kannst du mehrere Elemente hinzufügen und individuell anordnen.

[#405]
=== Verfügbare Funktionen im Bearbeitungsmodus

Das Dashboard erlaubt dir viel Flexibilität beim Anordnen von Inhalten und Daten. Grundsätzlich platzierst du Darstellungsbereiche und Elemente intuitiv per Drag-and-Drop auf dem Dashboard. Jeder Bereich und jedes Element kann per Klick auf icon:design_inline_edit[set=plenty] weiter bearbeitet werden. Die folgende Tabelle enthält einen Überblick über die Funktionen, die im Bearbeitungsmodus des Dashboards oben rechts im Menü *plentymarkets Logo (Start) » Dashboard (Beta)* zur Verfügung stehen.

[[tabelle-bearbeitungsmodus-dashboard]]
[width="100%"]
[cols="1,3"]
|====
|Bedienelement |Erläuterung

| *Ansicht bearbeiten* icon:design_inline_edit[set=plenty]
| Öffnet das Dashboard zur Bearbeitung.

| *Rückgängig* icon:reply[role=darkGrey]
| Macht die letzte Änderung rückgängig, soweit die betreffende Änderung noch nicht gespeichert wurde.

| *Wiederherstellen* icon:share[role=darkGrey]
| Stellt eine rückgängig gemachte Änderung wieder her.

| *Standardansicht*
| Dieser Bereich zeigt an, welche Dashboard-Ansicht aktuell geöffnet ist. Klicke auf icon:sort-down[role=darkGrey], um zu einer anderen Ansicht zu wechseln oder eine <<#407, neue Ansicht>> zu erstellen.

| *Letzten Speicherpunkt wiederherstellen* icon:reset[set=plenty]
| Setzt das Dashboard auf den Stand zurück, der beim letzten Speichern vorhanden war.

| *Speichern* icon:save[set=plenty]
| Speichert die am Dashboard vorgenommenen Änderungen.

| *Schließen* icon:close[set=plenty]
| Beendet den Bearbeitungsmodus. Falls nicht gespeicherte Änderungen vorhanden sind, erscheint eine Sicherheitsabfrage.

|====

[#407]
=== Neue Dashboard-Ansicht erstellen

Zusätzlich zur Standardansicht im Menü *plentymarkets Logo (Start) » Dashboard (Beta)* kannst du weitere individuelle Ansichten erstellen und speichern. Je nachdem, wie detailliert du Kennzahlen auf dem Dashboard auswerten möchtest, kannst du zum Beispiel separate Ansichten für verschiedene Themenbereiche und Daten erstellen. 

[.instruction]
Neue Dashboard-Ansicht erstellen:

. Öffne das Menü *plentymarkets Logo (Start) » Dashboard (Beta)*.
. Klicke oben rechts auf *Standardansicht*.
. Klicke auf *Neue Ansicht erstellen*.
. Vergib einen *Namen* für die Ansicht.
. Klicke auf *Ansicht erstellen*.
→ Die neue Ansicht wird geöffnet. Eine neue Ansicht ist standardmäßig immer eine Kopie der zuvor angelegten Ansicht. Nutze den <<#405, Bearbeitungsmodus>>, um nicht benötigte Elemente zu entfernen und weitere Elemente zur neu erstellten Ansicht hinzuzufügen.
. *Speichere* icon:save[set=plenty] die Einstellungen. +
→ Die neue Ansicht wird gespeichert.

Zusätzlich kannst du die Sichtbarkeit der erstellten Ansichten so festlegen, dass nur bestimmte Benutzer:innen oder Benutzerrollen darauf zugreifen können. Weitere Informationen dazu findest du im folgenden Kapitel.

[#408]
=== Rechte für Dashboard-Ansichten vergeben

Überlege dir, welche Benutzer:innen die Standardansicht sehen dürfen. Auch die Sichtbarkeit weiterer Ansichten kannst du auf Ebene von Benutzer:innen und Rollen eingrenzen.

Aktiviere bei einer bereits angelegten <<#407, Dashboard-Ansicht>> den Bearbeitungsmodus (icon:design_inline_edit[set=plenty]), um über die Schaltfläche *Rechteverwaltung* zu den Einstellungen für Benutzer:innen und Rollen zu gelangen.

Weitere Informationen und eine Anleitung für die Zuweisung pro Benutzer:in oder Rolle findest du auf der Handbuchseite <<business-entscheidungen/benutzerkonten-zugaenge#112, Benutzer:innen-Konten und Zugänge>>.

[#410]
=== Elemente zum Dashboard hinzufügen

Im Dashboard stehen dir verschiedene Möglichkeiten zur Verfügung, um Kennzahlen darzustellen. Die folgenden Typen von Elementen lassen sich verwenden:

* <<#500, Kacheln>>
* <<#600, Tabellen>>
* <<#700, Diagramme>>
* <<#800, Zeilen>>
* <<#900, Benachrichtigungen>>

Unabhängig vom Elementtyp ist die Vorgehensweise beim Platzieren der Inhalte auf dem Dashboard immer gleich. Die folgende Anleitung verdeutlicht den allgemeinen Ablauf.

[.instruction]
Element auf dem Dashboard platzieren:

. Öffne das Menü *plentymarkets Logo (Start) » Dashboard (Beta)*.
. Klicke auf *Ansicht bearbeiten* icon:design_inline_edit[set=plenty].
. Wähle ein Element aus dem Einstellungsmenü und platziere es per Drag-and-drop auf dem Dashboard.
. Klicke an der oberen rechten Ecke des so platzierten Bereichs auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü öffnet sich. +
→ Die für den Bereich verfügbaren Elemente werden angezeigt.
. Wähle ein Element aus dem Einstellungsmenü und platziere es per Drag-and-drop im soeben erstellten Bereich auf dem Dashboard.
. *Speichere* icon:save[set=plenty] die Einstellungen.

Die folgenden Kapitel beschreiben, wie du die verschiedenen Elemente nutzt und welche Einstellungen jeweils möglich sind.

[#500]
==== Kacheln verwenden

Kacheln sind quadratische Darstellungsbereiche. Sie stellen Daten ausschließlich in Text- und Zahlenform dar. Du kannst zwischen verschiedenen Farben wählen sowie Angaben zu Zeiträumen und Zielwerten darstellen.

Füge zunächst <<#420, wie oben beschrieben>> eine Kachel hinzu. Gehe dann wie folgt vor, um individuelle Einstellungen für die Kachel vorzunehmen.

[.instruction]
Kacheln verwenden:

. Klicke an der oberen rechten Ecke der Kachel auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü öffnet sich.
. Nimm die Einstellungen für die Kachel vor.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[.collapseBox]
.*Einstellungen für Kacheln vornehmen*
--

[[tabelle-kacheln-einstellungen]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Vorlagen für Kacheln*
| Klicke auf diese Schaltfläche, um eine vom System bereitgestellte Vorlage für die Kachel zu wählen. So zeigt die Kachel die ausgewählten Daten an, ohne dass du die Daten in weiteren Schritten manuell auswählen musst.

| *Kennzahl*
| Wähle aus der Dropdown-Liste eine Kennzahl aus, die in der Kachel dargestellt werden soll. Klicke alternativ auf *Neue Kennzahl erstellen* icon:plus[role="green"], um eine neue Kennzahl anzulegen.

| *Titel*
| Gib einen aussagekräftigen Titel ein. Der Titel wird als Name auf der Kachel angezeigt. Klicke auf icon:preview[role="skyBlue"], wenn der Titel nicht auf der Kachel angezeigt werden soll.

| *Zeitraum*
| Wähle den Zeitraum, aus dem die Werte der gewählten Kennzahl berücksichtigt werden soll.

| *Zeitintervall*
| Diese Einstellung schränkt die Werte aus dem gewählten *Zeitraum* weiter ein. Das Zeitintervall muss also immer kleiner gewählt werden als der *Zeitraum*. +
*_Beispiel:_* Wenn du den aktuellen Monat als *Zeitraum* gewählt hast und für das *Zeitintervall* die Option *Woche*, wird nur der Wert für die aktuelle Woche auf der Kachel angezeigt.

| *Hauptwert*
| Der Hauptwert wird auf der Kachel etwas größer als der *Sekundärwert* dargestellt. Hier kannst du das reine *Ergebnis der Kennzahl* oder die *Differenz* zum in der Kennzahl <<#option-targetvalue, festgelegten Zielwert>> anzeigen lassen. Die Differenz kannst du als absoluten Wert oder *in %* anzeigen lassen. Über icon:settings[set=plenty] kannst du bestimmen, wie viele Nachkommastellen für den Wert angezeigt werden sollen.

| *Sekundärwert*
| Dieser Wert wird auf der Kachel etwas kleiner und oberhalb des Hauptwerts angezeigt. Für den Sekundärwert stehen dir dieselben Einstellungsmöglichkeiten wie für den *Hauptwert* zur Verfügung. Wähle die Option *Keine*, wenn du keinen Sekundärwert auf der Kachel anzeigen möchtest.

| *Ziel*
| Soll der in der Kennzahl <<#option-targetvalue, festgelegte Zielwert>> auf der Kachel angezeigt werden? Wähle zwischen den Optionen *Anzeigen* und *Nicht anzeigen*.

| *Einheit*
| Wähle, ob die Einheit der Kennzahl auf der Kachel angezeigt werden soll.

| *Einfärbung*
| Möchtest du die Kachel in einer bestimmten Farbe anzeigen? Wähle dazu die Option *Anzeigen* und klicke auf icon:settings[set=plenty]. Es öffnet sich ein weiteres Einstellungsfenster. Wähle links die Farbe für die Kachel aus. Soll die Farbe der Kachel sich je nach Wert der Kennzahl ändern, wähle zusätzlich einen *Operator* und einen *Vergleichswert* aus, bevor du auf *Speichern* klickst. +
*_Tipp:_* Klicke auf icon:plus[role="green"], um weitere Bedingungen für die Einfärbung zu speichern.

|====

--

[#600]
==== Tabellen verwenden

Kennzahlen lassen sich auf dem Dashboard auch in Tabellenform übersichtlich darstellen. Grundsätzlich stehen für Tabellen dieselben Einstellungsmöglichkeiten wie im Abschnitt <<#500, Kacheln>> beschrieben zur Verfügung. 
Weitere speziell für Tabellen verfügbare Einstellungen werden weiter unten in diesem Kapitel beschrieben.

Füge zunächst <<#420, wie oben beschrieben>> eine Tabelle hinzu. Gehe danach wie folgt vor, um individuelle Einstellungen für die Tabelle vorzunehmen.

[.instruction]
Tabellen verwenden:

. Klicke an der oberen rechten Ecke der Tabelle auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü öffnet sich.
. Nimm die Einstellungen für die Tabelle vor.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[.collapseBox]
.*Einstellungen für Tabellen vornehmen*
--

[[tabelle-tabellen-einstellungen]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Vorlagen für Tabelle*
| Klicke auf diese Schaltfläche, um eine vom System bereitgestellte Vorlage für die Tabelle zu wählen. So zeigt die Tabelle die ausgewählten Daten an, ohne dass du die Daten in weiteren Schritten manuell auswählen musst.

| *Ergebnissortierreihenfolge*
| Über diese Option lassen sich die Werte in der Spalte *Ergebnis* der Tabelle sortieren. Wähle eine der Optionen *Aufsteigend* oder *Absteigend*.

| *Skalenbasis Sortierreihenfolge*
| Wenn mehrere Ergebnisse denselben Wert haben, lassen sich über diese Option die Werte in der Spalte *Dimension* der Tabelle sortieren. Wähle eine der Optionen *Aufsteigend* oder *Absteigend*.

| *Aggregierung*
| Wähle aus, wie die Daten gesammelt werden sollen. Die möglichen Optionen sind Summe (Σ), Durchschnitt (∅), Maximum und Minimum.

| *Einträge pro Seite*
| Je nach Anzahl der Einträge kann die Tabelle aus mehreren Seiten bestehen. Wähle aus, ob *10*, *25*, *50*, *75* oder *100* Einträge pro Seite angezeigt werden sollen.

| *Gruppe nach Dimension*
| Wenn aktiviert, werden mehrere Einträge derselben Dimension zusammengefasst.

| *Zugeordnete Spalte*
| Für jede zugeordnete Spalte wird eine weitere Spalte in der Tabelle hinzugefügt. Wähle für jede Spalte eine der Optionen *Berechnungsdatum*, *Dimension*, *Primäres Ergebnis*, *Ergebniseinheit*, *Skalenbasis* oder *Ziel*.

|====

--

[#700]
==== Diagramme verwenden

Mithilfe von Diagrammen kannst du deine Daten auf dem Dashboard anschaulich aufbereiten. Die folgenden Diagrammtypen stehen dir zur Verfügung:

* <<#710, Tortendiagramm>>
* <<#720, Balkendiagramm>>
* <<#720, Liniendiagramm>>
* <<#730, Heatmap>>
* <<#740, Fortschrittsdiagramm>>

Die folgenden Abschnitte erläutern, wie du die verschiedenen Diagrammtypen auf dem Dashboard platzierst und welche Einstellungen jeweils verfügbar sind.

[#710]
===== Tortendiagramm

Füge zunächst <<#420, wie oben beschrieben>> ein *Diagramm* hinzu. Gehe danach wie folgt vor, um individuelle Einstellungen für das Tortendiagramm vorzunehmen.

[.instruction]
Tortendiagramme verwenden:

. Klicke an der oberen rechten Ecke des Tortendiagramms auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü öffnet sich.
. Nimm die Einstellungen für das Tortendiagramm vor.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[.collapseBox]
.*Einstellungen für Tortendiagramme vornehmen*
--

[[tabelle-tortendiagramm-einstellungen]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Kennzahl*
| Wähle aus der Dropdown-Liste eine Kennzahl aus, die im Diagramm dargestellt werden soll. Klicke alternativ auf *Neue Kennzahl erstellen* icon:plus[role="green"], um <<#220, direkt im Einstellungsmenü>> eine neue Kennzahl anzulegen.

| *Titel*
| Gib einen aussagekräftigen Titel ein. Der Titel wird als Name auf dem Tortendiagramm angezeigt. Klicke auf icon:preview[role="skyBlue"], wenn der Titel nicht auf dem Tortendiagramm angezeigt werden soll.

| *Zeitraum*
| Wähle den Zeitraum, aus dem die Werte der gewählten Kennzahl berücksichtigt werden soll.

| *Zeitintervall*
| Diese Einstellung schränkt die Werte aus dem gewählten *Zeitraum* weiter ein. Das Zeitintervall muss also immer kleiner gewählt werden als der *Zeitraum*. +
*_Beispiel:_* Wenn du den aktuellen Monat als *Zeitraum* gewählt hast und für das *Zeitintervall* die Option *Woche*, wird nur der Wert für die aktuelle Woche durch das Tortendiagramm abgebildet.

|====

--

[#720]
==== Balken- und Liniendiagramm

Balken- und Liniendiagramme sind ebenfalls häufig verwendete Diagrammtypen. Sie geben besonders deutlich Aufschluss über zeitliche Entwicklungen von Werten. Deshalb kannst du für diese Diagramme auch mehrere Kennzahlen kombiniert pro Element darstellen.

Für beide Diagrammtypen sind identische Einstellungen verfügbar. Deshalb werden sie in diesem Kapitel kombiniert beschrieben.

Füge zunächst <<#420, wie oben beschrieben>> ein *Balkendiagramm* oder ein *Liniendiagramm* hinzu. Gehe danach wie folgt vor, um individuelle Einstellungen für die Diagramme vorzunehmen.

[.instruction]
Balken- und Liniendiagramme verwenden:

. Klicke an der oberen rechten Ecke des Balken- oder Liniendiagramms auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü öffnet sich.
. Nimm die Einstellungen für das Balken- oder Liniendiagramm vor.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[.collapseBox]
.*Einstellungen für Balken- und Liniendiagramme vornehmen*
--

[[tabelle-balken-liniendiagramm-einstellungen]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Vorlagen für Balkendiagramm* 
| Klicke auf diese Schaltfläche, um eine vom System bereitgestellte Vorlage für das Balkendiagramm zu wählen. So zeigt das Balkendiagramm die ausgewählten Daten an, ohne dass du die Daten in weiteren Schritten manuell auswählen musst.

| *Kennzahlen und Zeitraum*
| Wähle aus der Dropdown-Liste Kennzahlen und Zeiträume zur Darstellung aus. Klicke alternativ auf *Neue Kennzahl erstellen* icon:plus[role="green"], um eine neue Kennzahl anzulegen.

| *Zeitintervall*
| Diese Einstellung schränkt die Werte aus dem gewählten *Zeitraum* weiter ein. Das Zeitintervall muss also immer kleiner gewählt werden als der *Zeitraum*. +
*_Beispiel:_* Wenn du den aktuellen Monat als *Zeitraum* gewählt hast und für das *Zeitintervall* die Option *Woche*, wird pro abgelaufener Woche des aktuellen Monats der jeweilige Wert als separate Linie oder Balken abgebildet.

| *X-Achse*
| Wähle, welche Grundlage für die X-Achse verwendet werden soll. Die Optionen *Skalenbasis*, *Dimension* und *Berechnungsdatum* stehen zur Verfügung.

| *Y-Achse*
| Wähle, welche Grundlage für die Y-Achse verwendet werden soll. Du kannst entweder das *Primäre Ergebnis* oder das *Ziel* verwenden.

| *Drehung der X-Achsenbeschriftung*
| Mit dieser Einstellung legst du fest, wie die Beschriftungen an der X-Achse dargestellt werden. Wähle *0* für die reguläre Darstellung und *45* oder *90*, um die Beschriftungen um die jeweilige Gradzahl zu drehen.

| *Anzahl der Spalten*
| Wähle, wie viele Einheiten des gewählten Zeitintervalls in dem Diagramm abgebildet werden sollen. Der Startpunkt basiert auf dem gewählten Zeitraum.

| *Zoom aktivieren*
| Aktiviere diese Option, um die Ansicht des Dashboard-Elements per Zoom-Funktion regulieren zu können. Lege zusätzlich einen *Anfangswert* fest, auf den der Zoom standardmäßig bei jedem Öffnen des Dashboards eingestellt werden soll.

|====

[TIP]
.Kennzahlen schnell ein- und ausblenden
====
Du kannst einzelne Kennzahlen schnell ein- und ausblenden, indem du unterhalb des Diagramms auf den Namen der Kennzahl klickst.
====

--

[#730]
===== Heatmap

Die Heatmap ist eine vereinfachte Darstellung, die im Hintergrund auf einer Diagrammstruktur basiert. Sie zeigt dir durch die Farbgebung, die auf dem aktuellen Wertes der Kennzahl basiert, einen dynamischen Status an. So kannst du sehen, ob bei der gewählten Kennzahl Handlungsbedarf besteht. 

Füge zunächst <<#420, wie oben beschrieben>> eine *Heatmap* hinzu. Gehe danach wie folgt vor, um individuelle Einstellungen für die Heatmap vorzunehmen.

[.instruction]
Heatmap verwenden:

. Klicke an der oberen rechten Ecke der Heatmap auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü öffnet sich.
. Nimm die Einstellungen für die Heatmap vor.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[.collapseBox]
.*Einstellungen für Heatmaps vornehmen*
--

[[tabelle-heatmap-einstellungen]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Kennzahlen und Zeitraum*
| Wähle aus der Dropdown-Liste eine oder mehrere Kennzahlen und Zeiträume aus, die in der Heatmap dargestellt werden sollen. Klicke alternativ auf *Neue Kennzahl erstellen* icon:plus[role="green"], um eine neue Kennzahl anzulegen.

| *Zeitintervall*
| Diese Einstellung schränkt die Werte aus dem gewählten *Zeitraum* weiter ein. Das Zeitintervall muss also immer kleiner gewählt werden als der *Zeitraum*. +
*_Beispiel:_* Wenn du den aktuellen Monat als *Zeitraum* gewählt hast und für das *Zeitintervall* die Option *Woche*, wird die Farbgebung der Heatmap durch den Wert der aktuellen Woche bestimmt.

| *X-Achse*
| Wähle, welche Grundlage für die X-Achse verwendet werden soll. Die Optionen *Skalenbasis*, *Dimension* und *Berechnungsdatum* stehen zur Verfügung.

| *Y-Achse*
| Wähle, welche Grundlage für die Y-Achse verwendet werden soll. Du kannst entweder das *Primäre Ergebnis* oder das *Ziel* verwenden.

| *Drehung der X-Achsenbeschriftung*
| Mit dieser Einstellung legst du fest, wie die Beschriftungen an der X-Achse dargestellt werden. Wähle *0* für die reguläre Darstellung und *45* oder *90*, um die Beschriftungen um die jeweilige Gradzahl zu drehen.

| *Anzahl der Spalten*
| 

|==== 

--

[#740]
===== Fortschrittsdiagramm

Für die Darstellung von Daten als Fortschrittsdiagramm sind dieselben Einstellungen wie für <<#710, Tortendiagramme>> verfügbar. Einzig die Darstellungsform unterscheidet sich. Im Gegensatz zum Tortendiagramm zeigt das Fortschritsdiagramm die Daten pro Kennzahl als Anteile eines Balkens dar.

Füge zunächst <<#420, wie oben beschrieben>> ein Fortschrittsdiagramm hinzu. Gehe danach wie folgt vor, um individuelle Einstellungen für das Fortschrittsdiagramm vorzunehmen.

[.instruction]
Fortschrittsdiagramm verwenden:

. Klicke an der oberen rechten Ecke des Fortschrittsdiagramms auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü öffnet sich.
. Nimm die Einstellungen für das Fortschrittsdiagramm vor. Das Kapitel <<#710, Tortendiagramm>> enthält weitere Informationen zu den verfügbaren Optionen.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[#800]
==== Zeilen verwenden

Für die Darstellung von Daten in einfacher Zeilenform sind dieselben Einstellungen wie für <<#500, Kacheln>> verfügbar.

Füge zunächst <<#420, wie oben beschrieben>> eine Zeile hinzu. Gehe danach wie folgt vor, um individuelle Einstellungen für die Zeile vorzunehmen.

[.instruction]
Zeilen verwenden:

. Klicke an der oberen rechten Ecke der Zeile auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü öffnet sich.
. Nimm die Einstellungen für die Zeile vor. Das Kapitel <<#500, Kacheln>> enthält weitere Informationen zu den verfügbaren Optionen.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[#810]
==== Weitere Informationen in Bereichen darstellen

Zusätzlich zur Darstellung von Daten in Form von Kacheln, Tabellen, Diagrammen und Zeilen lassen sich weitere Informationen innerhalb der Bereiche auf dem Dashboard darstellen. So kannst du Textfelder mit wichtigen Zusatzinformationen für deine Mitarbeiter:innen oder selbst konfigurierte Schaltflächen zu deinem Dashboard hinzufügen und genau nach deinen Anforderungen gestalten.

[#820]
===== Formartierten Text darstellen

Formartierter Text bietet dir die Möglichkeit, Informationen in Textform im Dashboard darzustellen. Der Text wird dann neben oder unter Elementen wie beispielsweise Kacheln angezeigt.

Gehe wie folgt vor, um formartierten Text zum Dashboard hinzuzufügen.

[.instruction]
Formartierten Text darstellen:

. Klicke an dem Bereich, in dem Text dargestellt werden soll, auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü öffnet sich.
. Wähle im Einstellungsmenü das Element *Formartierter Text* und platziere es per Drag-and-drop an der gewünschten Position.
. Klicke auf das Element *Formatierter Text* und gib im Einstellungsmenü den gewünschten Text ein. +
*_Optional_*: Formatiere den Text mithilfe der Optionen für Fettschrift, kursiv, unterstrichen und Stichpunkte.
. *Speichere* icon:save[set=plenty] die Einstellungen. +
→ Der Text wird permanent im Bereich dargestellt.

[#830]
===== Individuelle Schaltflächen hinzufügen

Ähnlich zum oben beschriebenen formatierten Text kannst du auch individuell nach deinen Wünschen Schaltflächen im Dashboard platzieren. Die Farbe, den Text und die Funktion der Schaltflächen kannst du dabei frei konfigurieren. Die Schaltfläche wird dann neben oder unter Elementen wie beispielsweise Kacheln angezeigt.

Gehe wie folgt vor, um individuelle Schaltflächen zum Dashboard hinzuzufügen.

[.instruction]
Individuelle Schaltflächen hinzufügen:

. Klicke an dem Bereich, in dem Text dargestellt werden soll, auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü öffnet sich.
. Wähle im Einstellungsmenü das Element *Schaltfläche* und platziere es per Drag-and-drop an der gewünschten Position.
. Klicke auf das Element *Schaltfläche* und nimm die Einstellungen vor. Beachte dabei die Informationen in <<tabelle-button-einstellungen>>.
. *Speichere* icon:save[set=plenty] die Einstellungen. +
→ Die Schaltfläche wird permanent im Bereich dargestellt.

[[tabelle-button-einstellungen]]
.Verfügbare Einstellungen für individuelle Schaltflächen
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Titel*
|Gib einen Titel ein. Der Titel wird als Text auf der Schaltfläche dargestellt.

| *Shortcut Typ*
|Gib an, welche Aktion beim Klick auf die Schaltfläche ausgeführt werden soll. Aktuell steht nur die Option *Link öffnen* zur Verfügung.

| *Link*
|Gib einen Link ein, der beim Klick auf die Schaltfläche geöffnet werden soll. Hierbei gibt es 2 Möglichkeiten: +
Interner Link: Ein interner Link öffnet ein Menü innerhalb des plentymarkets Backends. Gib dabei die URL des zu öffnenden Menüs beginnend mit einem */* ein. Der Link muss alles beinhalten, was nach dem Bestandteil *terra* in der URL des zu öffnenden Menüs angegeben ist. *_Beispiel_*: Soll durch Klick auf den Button die Auftragsübersicht geöffnet werden, gib den Link */order/order-search ein*. 
+ 
Externer Link: Gib den vollständigen Link zur externen Seite ein, beginnend mit *http://* oder *https://*.

| *Farben*
| Wähle, in welchen Farben die Schaltfläche angezeigt werden soll. Das linke Auswahlfeld bestimmt die Hintergrundfarbe der Schaltfläche. Das rechte Auswahlfeld bestimmt die Schriftfarbe des Titels.

|====

[#840]
==== Zusatzliche Aktionen ausführen

//TODO: Optionen im Dreipunktmenü beschreiben (Bild- und Datendownload, Rohdaten, Filter ändern)
//TODO: Kacheln - Dreipunktmenü bzw. Shortcuts
//TODO: Zeilen - Dreipunktmenü
//TODO: Detaillierte Dashboard-Ansicht


[#900]
=== Benachrichtigungen auf dem Dashboard anzeigen

<<willkommen/login-rundgang#notification-center, Benachrichtigungen>> beinhalten wichtige Informationen über dein plentymarkets System. Dazu findest du am oberen Rand des plentymarkets Backend ein Glockensymbol. Klickst du auf dieses, werden dir aktuelle Benachrichtigungen angezeigt. Zusätzlich werden Benachrichtigungen beim erstmaligen Öffnen des Dashboards und beim Anlegen jeder neuen Dashboard-Ansicht bereits standardmäßig in einem eigenen Bereich angezeigt. Gehe wie unten beschrieben vor, falls du diesen Bereich entfernt hast und ihn wieder anzeigen möchtest.

[.instruction]
Benachrichtigungen auf dem Dashboard anzeigen:

. Öffne das Menü *plentymarkets Logo (Start) » Dashboard (beta)*.
. Klicke auf *Ansicht bearbeiten* icon:design_inline_edit[set=plenty].
. Platziere das Element *Benachrichtigungen* per Drag-and-drop auf dem Dashboard.
. *Speichere* icon:save[set=plenty] die Einstellungen.
