= Prozesse
:lang: de
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: Prozesse, Einstellungen, plentyBase
:position: 40
:url: automatisierung/prozesse
:id: BOVCLZL

== Warum du Prozesse nutzen solltest

Ähnlich wie die <<automatisierung/ereignisaktionen#, Ereignisaktionen>> helfen dir Prozesse dabei, komplexe Abläufe in deinem plentymarkets System zu automatisieren. Die Prozesse erlauben es dir aber auch, Auftragsdokumente oder Versandlabels automatisiert ausdrucken zu lassen. Um Prozesse verwenden zu können, muss das Tool link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentymarkets Marketplace^]{nbsp}icon:external-link[] auf deinem Rechner installiert und gestartet sein.

== Wie werden Prozesse eingerichtet?

Neue Prozesse legst du unter dem Menüpunkt *Einrichtung » Prozesse » Neuer Prozess* an. Weitere Informationen dazu findest du auf der Handbuchseite <<automatisierung/prozesse/prozesse-einrichten#, Prozesse einrichten>>.

Bereits angelegte Prozesse kannst du jederzeit ansehen und starten, wenn du in der oberen Menüleiste im plentymarkets Backend auf den Punkt *Prozesse* klickst. Was genau beim Ausführen von Prozessen beachten zu ist, erfährst du auf der Handbuchseite <<automatisierung/prozesse/prozesse-ausfuehren#, Prozesse ausführen>>.

Du schaust dir die Einrichtung lieber Schritt für Schritt in anschaulichen Videos an? Kein Problem! In unseren <<automatisierung/prozesse/best-practices#, Praxisbeispielen>> haben wir einige nützliche Videotutorials für dich gesammelt. 
//todo: Deep Dive Video verlinken https://www.youtube.com/watch?v=p5NF6rLr7ho mit Timestamp 03:52:00 


== Welche Funktionen stehen dir zur Verfügung?

Für Prozesse stehen dir vielfältige Einrichtungmsöglichkeiten zur Verfügung. Diese werden über 3 verschiedene Einstellungstypen abgebildet, die du innerhalb der Prozesse verwenden kannst:

* <<automatisierung/prozesse/arbeitsschritte#, Arbeitsschritte>>
* <<automatisierung/prozesse/aktionen#, Aktionen/Steuerelemente>>
* <<automatisierung/prozesse/subaktionen#, Subaktionen>>


