= Report
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Report, Reports, Rohdaten
:position: 30

== Was ist ein Report?

Ein Report besteht aus Rohdaten. Die Rohdaten werden auf einem Cloud-Speicher gespeichert und können von dort über die REST-API und ein externes BI-Tool abgerufen werden. Das Erzeugen der Daten wird einmal in der Nacht über einen Cron-Job angestoßen.

Ein Report in plentymarkets erfüllt im Wesentlichen 2 Aufgaben:

* Bereitstellung von Daten per API für die Erhebung von Kennzahlen (KPI), um diese für externe BI-Lösungen bereitstellen zu können
* Bereitstellung einer Benutzeroberfläche, über die man eigenen KPIs erstellen kann, sofern man kein externes BI-Tool verwendet


[TIP]
.Aktueller Stand
====
Das neue Report-Modul befindet sich aktuell in der Entwicklung und wird in diesem Jahr (2019) veröffentlicht. Die Benutzeroberfläche wird zukünftig im Menü *Daten » Report* zur Verfügung stehen. Über die Benutzeroberfläche können Sie dann eigene KPIs erstellen.
====

== Aktuell verfügbare Datentypen

Aktuell sind die folgenden Datentypen im Report abrufbar:

[[tabelle-report-datentypen]]
.Verfügbare Datentypen
[cols="1,2"]
|====
|Datentyp |Erläuterung

|item
|Artikel

|item variation
|Variante

|producer
|Hersteller

|item variation supplier
|Lieferant

|account
|Firma

|account contact
|

|account contact type
|Kontakttyp. Die folgenden Werte sind verfügbar: +
1 = Customer +
2 = Interested party +
3 = Sales reprensentative +
4 = Supplier +
5 = Producer/Manufacturer +
6 = Partner

|account contact class
|Kundenklasse

|order
|Auftrag

|order property
|Auftragseigenschaft

|order item
|Auftragsposition

|order item property
|Eigenschaft der Auftragsposition

|order item amount
|Anzahl der Auftragspositionen

|user
|Benutzer

|referrer
|Herkunft

|online store
|Web-Shop

|====

Weitere Datentypen werden sukzessive ergänzt und in dieser Tabelle hinzugefügt.
