= Report
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Report, Reports, Rohdaten
:position: 30

== Was ist ein Report?

Ein Report besteht aus Rohdaten. Die Rohdaten werden auf einem Cloud-Speicher gespeichert und können von dort über die REST-API und ein externes BI-Tool abgerufen werden. Das Erzeugen der Daten wird einmal in der Nacht über einen Cron-Job angestoßen.

BI steht für "Business Intelligence" und beschreibt das Sammeln, Aufbereiten und Darstellen von geschäftsrelevanten Informationen und erlaubt eine  Gegenüberstellung der Vergangenheit und des gegenwärtigen Status. Daraus lassen sich dann Prognosen für die Zukunft ableiten.

Ein Report in plentymarkets erfüllt im Wesentlichen 2 Aufgaben:

* Bereitstellung von Daten per API für die Erhebung von Kennzahlen (KPI), um diese für externe BI-Lösungen bereitstellen zu können
* Bereitstellung einer Benutzeroberfläche, über die man eigenen KPIs erstellen kann, sofern man kein externes BI-Tool verwendet

[TIP]
.Aktueller Stand
====
Das neue Report-Modul befindet sich aktuell in der Entwicklung und wird im Laufe des Jahres 2019 veröffentlicht. Die Benutzeroberfläche wird zukünftig im Menü *Daten » Report* zur Verfügung stehen. Über die Benutzeroberfläche können Sie dann eigene KPIs erstellen.
====

== Verfügbare Datentypen

Aktuell können die folgenden Datentypen im Report abgerufen werden.

[[tabelle-report-datentypen]]
.Verfügbare Datentypen
[cols="1,2"]
|====
|Datentyp |Erläuterung

|item
|Artikel

|item variation
|Variante

|producer
|Hersteller

|item variation supplier
|Lieferant

|account
|Firma

|account contact
|

|account contact type
|Kontakttyp. Die folgenden Werte sind verfügbar: +
1 = Customer +
2 = Interested party +
3 = Sales reprensentative +
4 = Supplier +
5 = Producer/Manufacturer +
6 = Partner

|account contact class
|Kundenklasse

|order
|Auftrag

|order property
|Auftragseigenschaft

|order item
|Auftragsposition

|order item property
|Eigenschaft der Auftragsposition

|order item amount
|Anzahl der Auftragspositionen

|user
|Benutzer

|referrer
|Herkunft

|online store
|Web-Shop

|====

Weitere Datentypen werden sukzessive ergänzt und in dieser Tabelle hinzugefügt.

== Verfügbare Datenformate

Die Datenformate werden von einem sogenannten Creator generiert. Der Creator liefert ein bestimmtes Datenformat und legt es zum Abruf oder zur weiteren Verarbeitung an.

Welche Datenfelder verwendet werden können, wird auf den Unterseiten der einzelnen Datentypen beschrieben. Über die folgenden Links gelangen Sie direkt auf die Unterseite der Datentypen:

* <<daten/report/datentypen#, account>>
* <<daten/report/datentypen#, accountContact>>
* <<daten/report/datentypen#, accountContactClass>>
* <<daten/report/datentypen#, accountContactType>>
* <<daten/report/datentypen#, item>>
* <<daten/report/datentypen#, itemVariation>>
* <<daten/report/datentypen#, itemVariationSupplier>>
* <<daten/report/datentypen#, onlineStore>>
* <<daten/report/datentypen#, order>>
* <<daten/report/datentypen#, orderItem>>
* <<daten/report/datentypen#, orderItemAmount>>
* <<daten/report/datentypen#, orderItemProperty>>
* <<daten/report/datentypen#, orderProperty>>
* <<daten/report/datentypen#, producer>>
* <<daten/report/datentypen#, referrer>>
* <<daten/report/datentypen#, user>>
