= Report
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Report, Reports, Rohdaten, KPI, Kennzahl, Datenanalyse, Statistik, BI, Business Intelligence
:position: 30

== Was ist ein Report?

Ein Report ist eine Datenanalyse, welche als Ergebnis eine einzelne Kennzahl (KPI) oder eine Ergebnisliste ermittelt. Als Datenbasis für diese Analyse werden regelmäßig Rohdaten aus plentymarkets exportiert und auf einem sicheren Cloud-Speicher abgelegt.

[TIP]
.Aktueller Stand
====
Zum aktuellen Zeitpunkt kann die Analyse lediglich über externe Business-Intelligence-Tools (BI-Tools) erfolgen. Für das laufende Jahr ist auch ein internes Modul zur Datenanalyse geplant.
====

=== Rohdaten

Rohdaten werden im Hintergrund und im Regelfall nachts ermittelt. Welche Rohdaten abgelegt werden, legen Sie im Menü *Daten » Rohdaten* fest. Die generierten Dateien können Sie per REST-API abrufen und extern verarbeiten.

=== Für Endanwender

Wir beobachten, dass Geschäftsentscheidungen oft nicht auf Basis von Kennzahlen, sondern eher aus dem Bauch heraus getroffen werden. Um dies zu verändern, empfehlen wir den Einsatz eines Business-Intelligence-Tools. Bestenfalls werden darin unterschiedliche Daten aus mehreren Quellen analysiert, um daraus konkrete Handlungsempfehlungen ableiten zu können.

Die Daten aus plentymarkets können einfach in eine bestehende BI-Lösung integriert werden. Sofern noch kein Standard-Connector existiert, leiten Sie bitte die URL zu dieser Seite an den Lösungsanbieter weiter.

=== Für Entwickler

Alle plentymarkets Systeme verfügen über eine einheitliche REST-API. Die Dokumentation finden Sie auf der folgenden Seite: link:https://developers.plentymarkets.com/[developers.plentymarkets.com^].

[...] Da folgt noch was


== Creator Datenformat

Mit Creator bezeichnen wir einen bestimmten Prozess, welcher ein Datenformat bereitstellt. Jeder Creator legt erst dann Daten ab, wenn dieser zuvor im Menü *Daten » Rohdaten* aktiviert wurde.

Die einzelnen Datenformate haben englische Bezeichnungen. Die Bedeutung ist in der folgenden Tabelle aufgelistet.

[[tabelle-report-datenformate]]
.Verfügbare Datenformate
[cols="1,2"]
|====
|Datentyp |Erläuterung

|item
|Artikel

|itemVariations
|Variante

|itemProducer
|Hersteller

|itemVariationsSupplier
|Lieferant

|account
|Firma

|accountContacts
|

|accountContactType
|Kontakttyp. Die folgenden Werte sind verfügbar: +
1 = Customer +
2 = Interested party +
3 = Sales reprensentative +
4 = Supplier +
5 = Producer/Manufacturer +
6 = Partner

|accountContactClass
|Kundenklasse

|orders
|Auftrag

|orderProperties
|Auftragseigenschaften

|orderItems
|Auftragsposition

|orderItemProperties
|Eigenschaft der Auftragsposition

|orderItemAmounts
|Anzahl der Auftragspositionen

|user
|Benutzer

|referrer
|Herkunft

|online store
|Web-Shop

|====

Weitere Datentypen werden sukzessive ergänzt und in dieser Tabelle hinzugefügt.

== Verfügbare Datenformate

Die Datenformate werden von einem sogenannten Creator generiert. Der Creator liefert ein bestimmtes Datenformat und legt es zum Abruf oder zur weiteren Verarbeitung an.

Welche Datenfelder verwendet werden können, wird auf den Unterseiten der einzelnen Datenformate beschrieben. Über die folgenden Links gelangen Sie direkt auf die Unterseite der Datenformate:

* <<daten/report/datenformate/account#, account>>
* <<daten/report/datenformate/accountcontact#, accountContacts>>
* <<daten/report/datenformate/accountcontactclass#, accountContactClass>>
* <<daten/report/datenformate/accountcontacttype#, accountContactType>>
* <<daten/report/datenformate/item#, item>>
* <<daten/report/datenformate/itemvariation#, itemVariation>>
* <<daten/report/datenformate/itemvariationsupplier#, itemVariationSupplier>>
* <<daten/report/datenformate/onlinestore#, onlineStore>>
* <<daten/report/datenformate/order#, order>>
* <<daten/report/datenformate/orderitem#, orderItem>>
* <<daten/report/datenformate/orderitemamount#, orderItemAmount>>
* <<daten/report/datenformate/orderitemproperty#, orderItemProperty>>
* <<daten/report/datenformate/orderproperty#, orderProperty>>
* <<daten/report/datenformate/producer#, producer>>
* <<daten/report/datenformate/referrer#, referrer>>
* <<daten/report/datenformate/user#, user>>
