= Report
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Report, Reports, Rohdaten, KPI, Kennzahl, Datenanalyse, Statistik, BI, Business Intelligence
:position: 30

== Was ist ein Report?

Ein Report ist eine Datenanalyse, welche als Ergebnis eine einzelne Kennzahl (KPI) oder eine Ergebnisliste ermittelt. Als Datenbasis für diese Analyse werden regelmäßig Rohdaten aus plentymarkets exportiert und auf einem sicheren Cloud-Speicher abgelegt.

[TIP]
.Aktueller Stand
====
Zum aktuellen Zeitpunkt kann die Analyse lediglich über externe Business-Intelligence-Tools (BI-Tools) erfolgen. Für das laufende Jahr ist auch ein internes Modul zur Datenanalyse geplant.
====

=== Rohdaten

Rohdaten werden im Hintergrund und im Regelfall nachts ermittelt. Welche Rohdaten abgelegt werden, legen Sie im Menü *Daten » Rohdaten* fest. Die generierten Dateien können Sie per REST-API abrufen und extern verarbeiten.

=== Für Endanwender

Wir beobachten, dass Geschäftsentscheidungen oft nicht auf Basis von Kennzahlen, sondern eher aus dem Bauch heraus getroffen werden. Um dies zu verändern, empfehlen wir den Einsatz eines Business-Intelligence-Tools. Bestenfalls werden darin unterschiedliche Daten aus mehreren Quellen analysiert, um daraus konkrete Handlungsempfehlungen ableiten zu können.

Die Daten aus plentymarkets können einfach in eine bestehende BI-Lösung integriert werden. Sofern noch kein Standard-Connector existiert, leiten Sie bitte die URL zu dieser Seite an den Lösungsanbieter weiter.

=== Für Entwickler

Alle plentymarkets Systeme verfügen über eine einheitliche REST-API. Die Dokumentation finden Sie auf der folgenden Seite: link:https://developers.plentymarkets.com/[developers.plentymarkets.com^].

[...] Da folgt noch was


== Datenformat-Creator

Mit Creator bezeichnen wir einen bestimmten Prozess, welcher ein Datenformat bereitstellt. Jeder Creator legt erst dann Daten ab, wenn dieser zuvor im Menü *Daten » Rohdaten* aktiviert wurde.

Die einzelnen Datenformate haben englische Bezeichnungen. Die Bedeutung sowie weiterführende Links sind in <<tabelle-report-datenformate>> aufgelistet.

[[tabelle-report-datenformate]]
.Verfügbare Datenformate
[cols="1,2"]
|====
|Datenformat |Erläuterung

|accounts
|Firma +
Weitere Informationen finden Sie auf der Unterseite <<daten/report/datenformate/accounts#, accounts>>.

|accountContacts
|Kontakt +
Weitere Informationen finden Sie auf der Unterseite <<daten/report/datenformate/accountcontacts#, accountContacts>>.

|itemProducer
|Hersteller +
Weitere Informationen finden Sie auf der Unterseite <<daten/report/datenformate/itemproducer#, ItemProducer>>.

|itemVariations
|Variante +
Weitere Informationen finden Sie auf der Unterseite <<daten/report/datenformate/itemvariations#, itemVariations>>.

|orderItemAmounts
|Anzahl der Auftragspositionen +
Weitere Informationen finden Sie auf der Unterseite <<daten/report/datenformate/orderitemamounts#, orderItemAmounts>>.

|orderItemProperties
|Eigenschaft der Auftragsposition +
Weitere Informationen finden Sie auf der Unterseite <<daten/report/datenformate/orderitemproperties#, orderItemProperties>>.

|orderItems
|Auftragsposition +
Weitere Informationen finden Sie auf der Unterseite <<daten/report/datenformate/orderitems#, orderItems>>.

|orderProperties
|Auftragseigenschaft +
Weitere Informationen finden Sie auf der Unterseite <<daten/report/datenformate/orderproperties#, orderProperties>>.

|orders
|Auftrag +
Weitere Informationen finden Sie auf der Unterseite <<daten/report/datenformate/orders#, orders>>.

|====

Weitere Datenformate werden sukzessive ergänzt und in dieser Tabelle hinzugefügt.
