= Zahlungen abwicklen
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

In deinem Ceres Webshop kannst du deinen Kunden verschiedene Zahlungsarten anbieten. Alle Zahlungsarten werden über die Plugin-Struktur von plentymarkets integriert. Je nach deinen Wünschen kannst du eine Vielzahl von Zahlungsarten in deinem Webshop anbieten. Auf dieser Seite stellen wir dir die Zahlungsarten PayPal und Vorkasse vor und erklären dir, wie du diese in deinem Webshop anbietest. Zudem findest du hier Informationen zu den notwendigen Pflichteinstellungen, damit Zahlungen jeder Art korrekt in deinem plentymarkets System verarbeitet werden.

== PayPal einrichten

Das PayPal-Plugin ist standardmäßig in deinem plentymarkets System installiert und aktiviert. Dies erkennst du im Menü *Plugins » Plugin-Übersicht* an der blau gefärbten Weltkugel.
Du musst über ein PayPal-Geschäftskonto verfügen, um das PayPal-Plugin zu nutzen. Nimm nach der Erstellung des PayPal-Geschäftskontos die folgenden Schritte zur Einrichtung des Plugins vor.

PayPal-Plugin einrichten:

[.instruction]
. Öffne das Menü *System » Aufträge » Zahlung » Plugins » Kontoeinstellungen*.
. Klicke auf das grüne Plus, um ein neues PayPal-Konto hinzuzufügen.
. Gib die E-Mail-Adresse an, die du zur Erstellung deines PayPal-Geschäftskontos genutzt hast.
. Wähle die Option *Live-Umgebung*, die das eingegebene Konto für Zahlungen deiner Kunden im Webshop zur Verfügung. Alternativ: Stelle zuerst die nicht sichtbare *Testumgebung* ein und wechsle am Ende der Einrichtung auf die *Live-Umgebung*.
. Aktiviere die Option *PayPal PLUS*, falls du dein PayPal-Geschäftskonto für PayPal PLUS freigeschaltet hast.
. Klicke auf *Hinzufügen*. +
→ Du wirst automatisch zu PayPal weitergeleitet.
. Nimm bei PayPal die angezeigten Einstellungen vor.
. Klicke auf *Zurück zu plentymarkets*. +
→ Du wirst zu deinem plentymarkets Backend zurückgeleitet. Dort öffnet sich nun der PayPal-Schnellkonfigurator.
. Nimm die gewünschten Einstellungen im PayPal-Schnellkonfigurator vor. Durch Klick auf die Info-Icons rechts kannst du dir weitere Informationen zu den einzelnen Einstellungen anzeigen lassen.
. Klicke auf *Speichern*.
→ Dein PayPal-Konto wird mit deinen gewählten Einstellungen eingerichtet.

Sollte es zu einem späteren Zeitpunkt notwendig sein, einzelne Einstellungen im PayPal-Plugin zu ändern, beachte die detaillierte Anleitung in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/payment/PayPal_4690[hier^] im plentyMarketplace.

== PayPal deaktivieren

Möchtest du deinen Kunden PayPal vorerst nicht als Zahlungsart anbieten, kannst du das PayPal-Plugin unkompliziert deaktivieren und zu einem späteren jederzeit Zeitpunkt wieder aktivieren.

PayPal-Plugin deaktivieren:

[.instruction]
. Öffne das Menü *Plugins » Plugin-Übersicht*.
→ Die Plugin-Übersicht öffnet sich.
. Klicke auf die blaue Weltkugel in der Spalte *Aktiv*.
. Klicke auf *Speichern*, um die Änderung zu übernehmen. +
→ Das Plugin ist nun deaktiviert.

== Vorkasse einrichten

Die Zahlungsart Vorkasse ist vor allem interessant, wenn du deinen Kunden vorerst keinen Rechnungskauf anbieten oder dich generell vor Zahlungsausfällen schützen möchtest. +
Das passende Vorkasse-Plugin ist in deinem plentymarkets System bereits vorhanden, jedoch noch nicht installiert. Gehe wie folgt vor, um das Vorkasse-Plugin zu installieren.

Vorkasse-Plugin installieren:

[.instruction]
. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Aktiviere die Checkbox *Nicht installiert* und klicke auf *Suchen*. +
→ Nicht installierte Plugins werden als Suchergebnisse angezeigt.
. Wähle die Aktion *Plugin installieren* in der Zeile des Plugins *Vorkasse*.
→ Ein Fenster mit zusätzlichen Informationen zum Plugin öffnet sich. +
. Klicke auf *Installieren*.
→ Das Plugin wird installiert.

Nach der Installation des Plugins musst du noch weitere Einstellungen vornehmen, um die Einrichtung abzuschließen. Gehe dazu vor wie im Folgenden beschrieben.

Vorkasse-Plugin einrichten:

[.instruction]
. Öffne das Menü *System » Aufträge » Zahlung » Plugins » Vorkasse*.
. Wähle den Mandanten, für den das Vorkasse-Plugin aktiviert werden soll.
. Nimm die Einstellungen vor. Beachte dabei die detaillierte Anleitung in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/payment/PrePayment_4758[hier^] im plentyMarketplace.

== Weitere Zahlungsarten einrichten

Oben wurde die Einrichtung der Zahlungsarten PayPal und Vorkasse beschrieben. Je nach deinen Wünschen und den Anforderungen deiner Kunden im Webshop kann es später Sinn machen, weitere Zahlungsarten anzubieten. Hierzu steht dir eine große Auswahl an weiteren Plugins zum Download im Bereich link:https://marketplace.plentymarkets.com/plugins/payment[Payment^] des plentyMarketplace zur Verfügung.
