= Artikelkatalog aufbauen
:lang: de
include::{includedir}/_header.adoc[]
:position: 80
:url: schnelleinstieg/schnelleinstieg-artikelkatalog
:id: IKOMOQN

IMPORTANT: Hast du schon Lieferländer eingerichtet und in Regionen eingeteilt, das Versandprofil eingerichtet und die Versandkosten festgelegt? Noch nicht? Dann geht's hier zurück zum Thema <<schnelleinstieg/schnelleinstieg-versandoptionen#, Versandoptionen einstellen>>.

Nun pflegst du deine Produkte in plentymarkets ein.

[#5]
== Vorbereitungen treffen

In plentymarkets werden einige Artikelinformationen zentral verwaltet und mit Varianten verknüpft. Deshalb musst du diese Daten im System speichern, bevor du Varianten erstellen kannst. Die folgenden Artikelinformationen müssen im System vorhanden sein, damit du Artikel und Varianten erstellen kannst:

* Kategorien
* Attribute
* Verkaufspreise

Nun erfährst du, wie du diese Informationen in plentymarkets speicherst.

[#10]
=== Kategorien erstellen

Mit Kategorien des Typs *Artikel* strukturierst du dein Produktsortiment und gestaltest deinen Webshop übersichtlich. Jeder Artikel muss mindestens einer Kategorie zugeordnet sein.

Im Webshop Ceres kannst du dich für eine Kategorietiefe von 2 oder von bis zu 4 Ebenen entscheiden:

* 1 Hauptkategorie + 1 Unterkategorie
  ** In der Standard-Navigationsleiste wird unterhalb der Hauptkategorien maximal eine weitere Kategorieebene dargestellt.
* 1 Hauptkategorie + bis zu 3 Unterkategorien
  ** Über das Megamenü sind bis zu drei weitere Ebenen unterhalb der Hauptkategorien darstellbar.

[TIP]
.Kategoriestruktur planen
====
Überlege dir, welche Kategorien und Unterkategorien für deine Produkte sinnvoll sind. Mit welcher Sortierung findet man sich am besten in deinem Shop zurecht? Trage diese Informationen am besten zusammen, bevor du loslegst. Eine Baumstruktur zu skizzieren kann dir helfen, deine Produkte sinnvoll zu gruppieren.
====

Gehe wie unten beschrieben vor, um eine Hauptkategorie zu erstellen.

[.instruction]
Hauptkategorie erstellen:

. Öffne das Menü *Artikel » Kategorien*.
. Wähle aus der Dropdown-Liste den Mandanten, für den du die Kategorie erstellen möchtest. +
*_Tipp:_* Der Standard-Mandant ist bereits vorausgewählt.
. Klicke links unten auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Gib einen Namen ein. +
*_Tipp:_* Die Option *Hauptkategorie* ist standardmäßig ausgewählt.
. Klicke auf *Erstellen*. +
→ Die Kategorie wird erstellt. +
→ Das Tab *Einstellungen* der Kategorie wird geöffnet. +
. Gib eine *Position* ein. Über die Position legst du die Reihenfolge fest, in der die Kategorien im Webshop angezeigt werden. Standardmäßig hat jede neue Kategorie, die du anlegst, die Position 0. +
*_Tipp:_* Positionsnummern in Zehnerschritten vergeben, damit neue Kategorien dazwischen eingefügt werden können.
. Aktiviere die *Mandanten (Shops)*, in denen die Kategorie verfügbar sein sollen.
. Gib einen *Meta-Titel* ein. +
*_Tipp:_* Der Meta-Titel wird im Tab des Browsers angezeigt.
. *Speichere* die Einstellungen. +
→ Die Kategorie wird erstellt. +
*_Hinweis:_* Die Kategorie wird erst im Webshop angezeigt, wenn mindestens ein für den Mandanten sichtbarer Artikel mit der Kategorie verknüpft ist.

Nun erstellst du eine Unterkategorie zu der Hauptkategorie, die du eben erstellt hast.

[.instruction]
Unterkategorie erstellen:

. Öffne das Menü *Artikel » Kategorien*.
. Klicke links unten auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Gib einen Namen ein. +
. Wähle die Option *Unterkategorie*.
. Klicke auf die Hauptkategorie, für die du die Unterkategorie erstellen möchtest. +
*_Tipp:_* Um eine Unterkategorie der dritten oder vierten Ebene zu erstellen, klicke in der Liste auf das Symbol der Hauptkategorie, um den Ordner zu öffnen. Öffne dann die Ordner der Unterkategorien auf die gleiche Weise, bis du die Kategorie erreichst, zu der du eine Unterkategorie erstellen möchtest.
. Klicke auf *Erstellen*. +
→ Die Kategorie wird erstellt. +
→ Das Tab *Einstellungen* der Kategorie wird geöffnet.
. Gib eine *Position* ein. Über die Position legst du die Reihenfolge fest, in der die Kategorien im Webshop angezeigt werden. Standardmäßig hat jede neue Kategorie, die du anlegst, die Position 0. +
*_Tipp:_* Positionsnummern in Zehnerschritten vergeben, damit neue Kategorien dazwischen eingefügt werden können.
. Aktiviere die *Mandanten (Shops)*, in denen die Kategorie verfügbar sein sollen.
. Gib einen *Meta-Titel* ein. +
*_Tipp:_* Der Meta-Titel wird im Tab des Browsers angezeigt.
. *Speichere* die Einstellungen. +
→ Die Kategorie wird erstellt. +
*_Hinweis:_* Die Kategorie wird erst im Webshop angezeigt, wenn mindestens ein für den Mandanten sichtbarer Artikel mit der Kategorie verknüpft ist.


[TIP]
.Die neuen Kategorien werden nicht im Webshop angezeigt?
====
Wenn deine Kategorien nicht im Webshop angezeigt werden, hilft dir unsere <<artikel/best-practices#kategorien, Checkliste für die Kategoriesichtbarkeit im Webshop>> weiter.
====

[#20]
=== Attribute erstellen

Attribute dienen dazu, Varianten zu erstellen. Varianten sind verschiedene Ausführungen eines Artikels, die sich sehr ähnlich sind, sich aber in einer oder mehreren Eigenschaften unterscheiden. Typische solche Attribute sind zum Beispiel Farben und Größen. Damit du nicht für jedes Produkt einen eigenen Artikel erstellen musst, werden diese Eigenschaften in plentymarkets als Attribute erstellt und einem Artikel zugeordnet. Unten wird beispielhaft beschrieben, wie du das Attribut *Farbe* erstellst.

[TIP]
.Beispiel
====
Ein Artikel soll in 3 Farben verkauft werden. Diese 3 Farbvarianten sollen bei der Bestellung wählbar sein. Statt 3 Artikel zu erstellen, wird ein Artikel mit drei Varianten erstellt. Die Varianten werden über Attributwerte gebildet.
====

[.instruction]
Attribut "Farbe" erstellen:

. Öffne das Menü *Einrichtung » Artikel » Attribute*.
. Klicke auf *Neues Attribut*. +
→ Das Fenster *Neues Attribut* wird geöffnet.
. Gib einen *Namen (intern)* ein, z.B. *Farbe*. +
*_Tipp:_* Dieser interne Name ist im Webshop nicht sichtbar.
. *Speichere* die Einstellungen. +
→ Das Attribut wird erstellt. +
→ Das Tab *Grundeinstellungen* des Attributs wird geöffnet.
. Wechsele in das Tab *Name*.
. Gib Namen für das Attribut in den Sprachen ein, die du in deinem Webshop verwendest. +
→ Dieser Name wird im Webshop angezeigt.
. *Speichere* die Einstellungen.

Nun erstellst du Attributwerte für das Attribut. Hier wird beispielhaft beschrieben, wie du den Wert "Grün" erstellst.

[.instruction]
Wert "Grün" für das Attribut "Farbe" erstellen:

. Wechsele in das Tab *Werte*.
. Klicke auf *Neuer Wert*. +
→ Das Fenster *Neuer Wert* wird geöffnet.
. Gib einen *Namen (intern)* ein, z.B. *Grün*. +
*_Tipp:_* Dieser interne Name ist im Webshop nicht sichtbar.
. *Speichere* die Einstellungen. +
→ Der Wert wird erstellt. +
→ Der Wert wird in der Liste angezeigt.
. Gib in der Spalte *Name* einen Namen für den Wert ein. +
*_Tipp:_* Standardmäßig wird der interne Name eingefügt. +
→ Dieser Name wird im Webshop angezeigt.
. *_Optional:_* Wenn du deine Produkte in mehreren Sprachen anbietest, wähle im Dropdown-Menü *Sprache anzeigen* die weiteren Sprachen.
. *_Optional:_* Gib in der Spalte *Name* einen Namen für den Wert in dieser Sprache ein. +
→ Dieser Name wird später im Webshop angezeigt.
. *Speichere* die Einstellungen.

// Als Beispiel oder allgemein formulieren? Also "Farbe" oder "Attribut"?


[#30]
=== Verkaufspreis anpassen

Definiere Bedingungen für Artikelpreise und Sonderpreise. Möchtest du beispielsweise deine Artikel in deinem Webshop günstiger anbieten als auf Amazon? Kein Problem! In diesem Schritt bestimmst du die Konditionen für einzelne Marktplätze, Kundenklassen, Lieferländer usw.

Öffne das Menü *Einrichtung* und suche nach dem Assistenten *Verkaufspreise*. Nach Abschluss des Assistenten kannst du die erstellten Verkaufspreise <<schnelleinstieg/schnelleinstieg-artikelkatalog#220, mit allen relevanten Varianten verknüpfen>> und den eigentlichen Preisen eintragen.

[#40]
== Artikelstruktur verstehen

Du hast nun die folgenden Artikelinformationen hinterlegt, die du benötigst, um deine Produkte in plentymarkets abzubilden:

* Kategorien
* Attribute
* Verkaufspreis

Bevor du deine ersten Artikeldaten ins System einpflegst, solltest du dich kurz mit der Artikelübersicht und der Artikelstruktur vertraut machen. Wir erklären, wie die Artikelübersicht funktioniert und stellen dir die Beispielartikel vor, die in neuen Systemen gespeichert sind.

[#50]
=== Artikelübersicht verstehen

Im Menü *Artikel » Artikel bearbeiten* werden alle Artikel und Varianten aufgelistet. In dieser Artikelübersicht kannst du Artikel und Varianten suchen, bearbeiten und neue Artikel erstellen.

In der Spalte links findest du Filter, um die Artikelsuche einzugrenzen. Zum Einstieg ist vor allem der Filter *Aktiv* wichtig. Mit diesem Filter legst du fest, ob in der Liste der Artikel nur Artikel und Varianten angezeigt werden, die für einen Webshop aktiviert sind. Standardmäßig ist dieser Filter auf *Ja* eingestellt. Das wird dir später, wenn du viele Artikel und Varianten hast, helfen, deine Artikel schneller zu bearbeiten. Am Anfang kann es aber verwirrend sein, denn Artikel, die nicht aktiv sind, werden nicht gefunden, wenn du auf *Suchen* klickst, ohne vorher den Filter auf *Nein* oder *Alle* zu setzen.


[#60]
=== Beispielartikel verstehen

Dein plentymarkets System enthält einige Beispielartikel und Beispielvarianten. Diese Beispieldaten helfen dir, dich mit der Struktur von Artikeln und Varianten vertraut zu machen, bevor du eigene Daten einpflegst.

Anhand dieser Beispielartikel werden wir dir kurz die Artikelstruktur erklären.

[#65]
==== Beispielartikel anzeigen

[.instruction]
Beispielartikel anzeigen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke in der Spalte links oben auf *Suchen*. +
→ Die Beispielartikel werden in der Artikelübersicht angezeigt.
. Öffne die folgenden Artikel:
  * Den Einzelartikel "Sessel Floating Water", Artikel-ID 123
  * Den Variantenartikel "Zweisitzer Paradise Now", Artikel-ID 132
. Klicke dich durch die Tabs des Artikels und der Varianten und mache dich mit den Einstellungsmöglichkeiten vertraut. +
→ <<tabelle-beispielartikel>> stellt die beiden Artikel gegenüber.
. Teste die Funktionsweise der Vererbung:
  .. Verknüpfe für die Variante 1065 des Artikels 132 im Tab *Kategorien* eine weitere Kategorie. +
  → Die bisher vererbte Kategorie wird direkt an der Variante gespeichert. +
  → Die Vererbung wird deaktiviert.
  .. Klicke auf *Vererbung aktivieren*. +
  → Die Kategorie, die du verknüpft hast, wird entfernt. +
  → Die Kategorie der Hauptvariante wird übernommen.

[[tabelle-beispielartikel]]
.Einzel- und Variantenartikel
[cols="1,3,3"]
|====
| |Einzelartikel |Variantenartikel

|Artikel-ID
|123
|132

|Name 1
|Sessel Floating Water
|Zweisitzer Paradise Now

|ID der Hauptvariante
|1021
|1030

|Hauptvariante kaufbar
|Ja +
*_Tipp:_* Bei Einzelartikeln sollte das Produkt der Hauptvariante entsprechen.
|Nein +
*_Tipp:_* Bei Variantenartikeln sollte die Hauptvariante kein verkaufbares Produkt sein. Die Hauptvariante sollte nur dazu dienen, die anderen Varianten des Artikels per Vererbung mit Daten zu versorgen.

|ID der Varianten
|--
|1065 - rot +
1066 - weiß

|Hersteller
|A & C Design
|Exclusive Leather

|Verkaufspreis
|Preis +
UVP
|Preis +
UVP +
*_Tipp:_* Die Preise werden nicht von der Hauptvariante an die Varianten vererbt.

|Kategorie
|Wohnzimmer » Sessel & Hocker
a|Wohnzimmer » Sofas +
*_Tipp:_* Die Kategorie wird von der Hauptvariante an die Varianten vererbt.

|Attributauswahlkombination +
(Attribut:Attributwert)
|---
|1065 - Couch color:rot +
1066 - Couch color:white +
*_Tipp:_* Mit der Hauptvariante ist kein Attribut verknüpft.

|Mandant (Shop)
|Standard Shop
|Standard Shop +
*_Tipp:_* Der Mandant wird von der Hauptvariante an die Varianten vererbt.
|====


[#90]
=== Beispielartikel löschen

Nachdem du dir die Beispielartikel angesehen hast, haben sie ihre Schuldigkeit getan und du kannst sie löschen. Damit stellst du sicher, dass du von Anfang an ein sauberes System ohne unnötige Daten hast. Am schnellsten löschst du die Beispielartikel mit der Gruppenfunktion.

[.instruction]
Beispielartikel per Gruppenfunktion löschen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Stelle den Filter *Aktiv* auf *ALLE*.
. Klicke auf *Suchen*. +
→ Alle im System gespeicherten Artikel werden angezeigt.
. Klicke in der Spaltenüberschrift der Liste ganz oben links auf das Kontrollkästchen, um alle angezeigten Artikel zu markieren.
. Klicke auf *Artikel-Gruppenfunktion*. +
→ Das Fenster *Artikel-Gruppenfunktion* wird geöffnet.
. Aktiviere die Option *Artikel löschen*.
. Klicke auf *Ausführen*. +
→ Alle Artikel werden aus dem System gelöscht.


[#220]
== Artikel und Varianten erstellen

Nun ist es so weit: Du pflegst deine eigenen Artikel in plentymarkets ein. Je nachdem, mit wie vielen Artikeln du starten möchtest und wie du Artikeldaten bisher verwaltest hast, hast du zwei Möglichkeiten, Artikeldaten ins System zu bringen:

* <<#100, Artikel manuell erstellen>> +
*_Tipp:_* Nachdem du den ersten Artikel erstellt hast, kannst du diesen Artikel kopieren und diese Kopie anpassen, um schneller zu arbeiten.
* <<#120, In einer CSV-Datei gespeicherte Artikeldaten importieren>> +
*_Tipp:_* Auch wenn du die Artikel importierst, solltest du vorher mindestens einen Beispielartikel manuell erstellen, um die Artikelstruktur kennenzulernen. Denke daran, diesen Beispielartikel vor dem Importieren zu löschen.

Beide Möglichkeiten werden nachfolgend beschrieben.

[TIP]
.Änderungen nicht sofort sichtbar
====
Neue Varianten und Änderungen an Variantendaten sind nicht sofort im Webshop und den Exporten verfügbar. Wie du prüfst, ob die Variantendaten aktuell sind, erfährst du auf der Handbuchseite <<artikel/artikeldaten-status-pruefen#, Aktualität von Artikeldaten prüfen>>.
====

[#100]
=== Artikel manuell erstellen

Nun erstellst du deinen ersten verkaufsbereiten Artikel. Damit du möglichst schnell loslegen kannst, beschreiben wir nur die nötigsten Einstellungen, die du vornehmen musst, damit der Artikel im Webshop verkauft werden kann.

[.instruction]
Artikel manuell erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet. +
*_Tipp:_* Der Artikeltyp *Standard* ist vorausgewählt.
. Gib einen Namen ein.
. Gib den Inhalt als Zahl ein.
. Wähle für diesen Inhalt eine Einheit aus der Dropdown-Liste.
. Klicke auf die Kategorie. +
→ Diese Kategorie wird als Standardkategorie mit der Hauptvariante des Artikels verknüpft.
. Gib einen *Preis* ein. +
. *Speichere* die Einstellungen. +
→ Der Artikel wird erstellt. +
→ Eine Hauptvariante wird erstellt. +
→ Das Tab *Global* des Artikels wird geöffnet.
. Nimm bei Bedarf weitere Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-artikel-bearbeiten>>. +
*_Tipp:_* Die in <<einstellungen-artikel-bearbeiten>> beschriebenen Einstellungen beziehen sich auf verschiedene Tabs im Bearbeitungsfenster des Artikels. Das Tab wird in einer eigenen Zeile als Zwischenüberschrift angezeigt.
. *Speichere* die Einstellungen. +
*_Hinweis:_* Neue Artikel und Änderungen an Artikeldaten sind nicht sofort im Webshop und den Exporten verfügbar. +
*_Tipp:_* Zeige eine Vorschau des Artikels an:
 .. Klicke in der Speicherzeile des Artikels auf das Augensymbol. +
 → Das Fenster *Mandant (Shop)* wird angezeigt. +
 .. Wähle in der Dropdown-Liste das *Plugin Set*, in dem du die Vorschau anzeigen möchtest.
 .. Wähle in der Dropdown-Liste den *Mandant (Shop)*, in dem du die Vorschau anzeigen möchtest. +
 *_Tipp:_* Die Einstellungen bleiben erhalten, wenn du die Vorschau das nächste Mal öffnest.
 .. Klicke auf *Ausführen*. +
 → Eine Vorschau des Artikels wird angezeigt.

[[einstellungen-artikel-bearbeiten]]
.Artikeleinstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|plentymarkets kann automatisch eine fortlaufende Nummer vergeben (empfohlen). +
Alternativ kannst du beim Erstellen eines Artikels eine eigene Artikel-ID eingeben. Die ID darf nur aus Zahlen bestehen. Jede ID darf nur einmal im System vorkommen.

2+|Tab: Global

|*Versandprofile*
|Das Versandprofil *DHL* aktivieren. Standardmäßig ist kein Versandprofil aktiviert. +
*_Hinweis:_* Pro Artikel muss mindestens ein Versandprofil aktiviert werden, da sonst ungewollte Effekte bei der Versandkostenberechnung auftreten.

2+|Tab: Varianten-ID » Einstellungen

|*Aktiv*
|Artikel aktivieren. Artikel werden erst im Webshop angezeigt, wenn sie aktiv sind.

|*Verfügbarkeit*
|Verfügbarkeitsstufe wählen. +
*_Tipp:_* Du bist gesetzlich verpflichtet, Verbraucherinnen und Verbraucher über die Lieferfristen deiner Produkte zu informieren. Im Menü *Einrichtung » Artikel » Verfügbarkeit* sind Standardtexte für 5 Verfügbarkeitsstufen gespeichert. Passe diese Texte bei Bedarf an.

|*Anzeige im Webshop:* +
*Automatisch verfügbar wenn Netto-WB positiv*;
*Automatisch nicht verfügbar wenn kein Netto-WB*
|Beide Optionen aktivieren. Die Variante ist dann bei positivem Nettowarenbestand verfügbar und käuflich und nicht käuflich, wenn kein Nettowarenbestand vorhanden ist.

|*Verkaufspreis*
|Verkaufspreis *Preis* hinzufügen und einen Preis eingeben.

|*Barcode*
|Barcode hinzufügen und Code eingeben.

|*ASIN/ePID*
|ASIN/ePID hinzufügen und ASIN bzw. ePID eingeben.

|*Gewicht brutto*; +
*Gewicht netto*
|Angabe in Gramm oder Kilogramm. +
*_Hinweis:_* Diese Angaben sind unbedingt erforderlich, wenn die Versandkosten auf Basis des Gewichts berechnet werden.

|*Umsatzsteuer*
|Umsatzsteuersatz des Produkts wählen. +
*_Tipp:_* Die Umsatzsteuersätze werden im Menü *Einrichtung » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung* gepflegt.

2+|Tab: Varianten-ID » Verfügbarkeit

|*Mandant (Shop): Verfügbar*
|Den oder die Mandanten (Shops) aktivieren, in denen die Variante verfügbar sein soll.

2+|Tab: Texte

|*Name 1*
|Einen Namen für den Artikel eingeben. +
*_Tipp:_* Dieser Name wird im Webshop angezeigt. Der Name gilt für alle Varianten des Artikels.

|*Artikeltext*
|Artikeltext eingeben. Der Artikeltext ist eine detaillierte Produktbeschreibung, die im Webshop angezeigt wird.
|====

[#110]
=== Varianten manuell erstellen

Super! Du hast nun deinen ersten Artikel erstellt. Dir ist sicher aufgefallen, dass beim Erstellen eines neuen Artikels immer eine Hauptvariante erstellt wird. Wenn du nur Einzelartikel verkaufen möchtest, entspricht die Hauptvariante deinem Produkt. Wenn du deine Produkte als Varianten eines Artikels gruppieren möchtest, erstellst du nun weitere Varianten.

[TIP]
.Vererbung
====
Wenn du Varianten erstellst, erben diese Varianten standardmäßig die vererbbaren Einstellungen der Hauptvariante:

* Verfügbarkeitseinstellungen
* Verkaufspreis und Preis
* Kategorie
* Lieferant
* Lager
* Mandantenverfügbarkeit

Deshalb empfehlen wir, Artikel mit mehreren Varianten so zu erstellen, dass die Hauptvariante virtuell ist, also nur dazu dient, Daten an die Varianten zu vererben. Wenn ein oder mehrere Einstellungen nicht vererbt werden sollen, kannst du die Vererbung an der Variante selbst deaktivieren und für die Variante eigene Daten speichern.
====

[.instruction]
Eine oder mehrere Varianten erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Varianten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neue Variante erstellen* wird geöffnet.
. Gib den Inhalt als Zahl ein.
. Wähle für diesen Inhalt eine Einheit aus der Dropdown-Liste.
. Wähle ein oder mehrere Attribute. +
→ Unter *Kombinationen* wird angezeigt, wie viele Varianten erstellt werden.
. Klicke auf *Varianten erstellen*. +
→ Die Varianten werden erstellt. +
→ Die Varianten werden in der Variantenübersicht angezeigt. +
*_Tipp:_* Die vererbbaren Einstellungen werden von der Hauptvariante an die Varianten vererbt.  +
*_Hinweis:_* Neue Varianten und Änderungen an Variantendaten sind nicht sofort im Webshop und den Exporten verfügbar. +
*_Tipp:_* Zeige eine Vorschau der Variante an:
  .. Klicke in der Speicherzeile der Variante auf das Augensymbol. +
  → Das Fenster *Mandant (Shop)* wird angezeigt. +
  .. Wähle in der Dropdown-Liste *Plugin Set*, in welchem Plugin-Set du die Vorschau anzeigen möchtest.
  .. Wähle in der Dropdown-Liste *Mandant (Shop)*, in welchem Mandanten du die Vorschau anzeigen möchtest.
  .. Klicke auf *Ausführen*. +
  → Eine Vorschau der Variante wird angezeigt.

[TIP]
.Artikel kopieren
====
Wenn sich mehrere deiner Artikel ähnlich sind, kannst du bei der Artikelerstellung Zeit sparen, indem du Artikel kopierst und anpasst. Klicke dazu in der oberen Zeile des Artikels auf das Symbol *Kopieren*.
====

[#120]
=== Artikel und Varianten importieren

Wenn du sofort eine größere Menge Artikeldaten importieren möchtest, ist das natürlich auch kein Problem. Um Daten von Artikeln und Varianten zu importieren, benötigst du diese Daten in einer CSV-Datei, die auf deinem Rechner gespeichert ist.

[TIP]
.Vor dem Import manuell einen Beispielartikel erstellen
====
Auch wenn du die Artikel importierst, solltest du vorher mindestens einen Beispielartikel manuell erstellen, um die Artikelstruktur kennenzulernen. Denke daran, diesen Beispielartikel vor dem Importieren zu löschen.
====

[#230]
==== Das Konzept verstehen

Damit dir der Import leichter von der Hand geht, haben wir eine link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/musterdatei_initialer_artikelimport_190226.csv[Muster-CSV-Datei] vorbereitet, die die Datenfelder enthält, die du benötigst, um verkaufbare Artikel zu importieren.

Die CSV-Datei enthält einen Einzelartikel und einen Variantenartikel mit einer virtuellen Hauptvariante und 3 weiteren Varianten.

Lade dir die Muster-CSV-Datei herunter und mache dich damit vertraut, wie die Datei aufgebaut ist.

[TIP]
.Spaltenüberschriften
====
Wir haben die Spaltenüberschriften genauso benannt wie die Felder, die du in <<daten/daten-importieren/ElasticSync#, ElasticSync>> bei der Zuordnung als Ziel angibst.
====

[#130]
==== Deine eigene Importdatei erstellen

Bereite nun deine eigene CSV-Datei mit deinen Artikeldaten vor. Öffne das Menü *Einrichtung* und suche nach dem Assistenten *Artikelimport*. Damit erstellst du eine auf deine Bedürfnisse zugeschnittene Importvorlage für Artikeldaten. Nach Abschluss des Assistenten lädst du die Importvorlage herunter und befüllst sie mit deinen Artikeldaten.

[TIP]
.Alle nötige Vorbereitungen getroffen?
====
Prüfe vor dem Import, dass du wirklich alle Daten im System gespeichert hast, die du mit Artikeln und Varianten verknüpfen möchtest. Um Produkte in plentymarkets abbilden zu können, benötigst du mindestens:

* Kategorien
* Attribute
* Verkaufspreise
====

[#140]
==== Deine Datei hochladen

Bist du bereit, deine Artikeldaten in plentymarkets hochzuladen? Öffne das Menü *Einrichtung* und suche nach dem Assistenten *Daten hochladen*.

[TIP]
.Suchst du umfangreichere Importoptionen?
====
Hast du einen spezifischen Anwendungsfall, den du nicht mit Assistenten abdecken kannst? Oder suchst du noch umfangreichere Importoptionen als in den Assistenten enthalten? <<daten/daten-importieren/ElasticSync#, ElasticSync>> ist das passende Tool für komplexe und umfangreiche Datenimporte!
====

[#170]
== Artikelbilder speichern

Beim Import der Artikel hattest du die Möglichkeit, für online erreichbare Bilder eine URL anzugeben. Wenn deine Artikelbilder nicht online verfügbar sind, kannst du die Bilder wie hier beschrieben manuell speichern.

NOTE: Wenn du deine Artikelbilder schon beim Artikelimport importiert hast, kannst du gleich zur <<#200, Checkliste>> springen.

[#180]
=== Artikelbilder hochladen

Im Tab *Bilder* im Bearbeitungsfenster des Artikels speicherst du Bilder und verknüpfst diese Bilder mit den Varianten des Artikels. Pro Artikel sind bis zu 25 Bilder in den Formaten JPG/JPEG oder PNG möglich.

[TIP]
.FTP-Upload nutzen
====
Größere Bildmengen überträgst du am besten per FTP-Upload auf den Server. Beachte aber die Hinweise zur Benennung der Bilddateien, damit die Bilder beim Hochladen den richtigen Artikeln und Varianten zugeordnet werden.
====

[.instruction]
Bilder für einen Artikel speichern:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Bilder* des Artikels.
. Ziehe neue Bilder per Drag & Drop-Funktion in den Bereich *Neues Bild einfügen*. +
icon:map-signs[] *_Oder:_* Klicke auf *Dateien auswählen*.
. Wähle aus der Dropdown-Liste *Verfügbarkeit* die Mandanten und/oder Herkünfte, für die das Bild bereitgestellt werden soll.
. *Speichere* die Einstellungen.

[#190]
=== Artikelbilder mit Varianten verknüpfen

Verknüpfe nun die am Artikel gespeicherten Bilder mit einer oder mehreren Varianten. Gehe dazu wie unten beschrieben vor.

[.instruction]
Artikelbilder mit Varianten verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Bilder* des Artikels. +
→ Eine Vorschau der am Artikel gespeicherten Bilder wird angezeigt.
. Setze ganz links ein Häkchen bei den Bildern, die du mit einer oder mehreren der Varianten verknüpfen möchtest.
. Klicke am unteren Ende der Seite auf *Variantenverknüpfung*. +
→ Das Fenster *Varianten verknüpfen* wird angezeigt.
. Wähle die Varianten, die du mit den gewählten Bildern verknüpfen möchtes.
. Klicke auf *Verknüpfen*. +
→ Die Bilder werden mit den gewählten Varianten verknüpft.


[#200]
== Checkliste Artikelkatalog

Arbeite die Checkliste durch, um deine Einstellungen zum Thema Artikelkatalog zu prüfen.

[%interactive]
* [ ] Hast du sinnvolle Kategorien für die Artikel erstellt?
* [ ] Hast du alle Artikel mit allen Beschreibungstexten erstellt?
* [ ] Hast du die Artikelverfügbarkeitsstufen korrekt eingestellt?
* [ ] Hast du die Verfügbarkeit aller Artikel aktiviert, die du im Webshop anbieten möchtest?
* [ ] Hast du geprüft, dass die richtigen Preise im Webshop angezeigt werden?

[#210]
== Mehr zum Thema Artikelkatalog aufbauen

=== Vorbereitungen treffen

* <<artikel/kategorien-verwalten#, Kategorien verwalten>>
* <<artikel/artikel-verwalten#390, Attribute verwalten>>
* <<artikel/artikel-verwalten#870, Verkaufspreise verwalten>>

=== Artikel verwalten

* <<artikel/artikelstruktur-kennenlernen#, Artikelstruktur verstehen>>
* <<artikel/artikel-verwalten#350, Filtermöglichkeiten für Artikel und Varianten in der Artikelansicht>>
* <<artikel/artikel-verwalten#, Artikel verwalten>>
* <<artikel/artikel-verwalten#155, Mehrere Artikel gleichzeitig bearbeiten>>
* <<artikel/artikel-verwalten#330, Mehrere Varianten gleichzeitig bearbeiten>>
* <<artikel/multipacks-pakete-sets-verwalten#, Sets, Multipacks und Pakete erstellen>>


[TIP]
.Cross-Selling nutzen
====
Du möchtest direkt im Artikel auf weitere interessante Produkte aufmerksam machen? Dann richte <<artikel/artikel-verwalten#950, Cross-Selling-Verknüpfungen ein>>.
====

=== Artikelbilder verwalten

* <<artikel/artikel-verwalten#660, Artikelbilder per FTP-Server hochladen>>

=== Daten importieren

* <<daten/daten-importieren/ElasticSync#, Sync für weitere Importe erstellen>>

TIP: Weiter zum Thema <<schnelleinstieg/schnelleinstieg-warenbestand#, Warenbestand buchen>>
