= Versandoptionen einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Lieferland, Lieferländer, Region, Regionen, Versanddienstleister, Versandprofil, Versandkosten, Versandprofil, Portotabelle
:description: Erfahre in diesem Teil des Schnelleinstiegs, wie du die Versandoptionen einrichtest.
:position: 0

Auf dieser Seite erfährst du, wie du dein System fit für den Versand machst: Du legst fest, in welche Länder du deine Artikel versenden möchtest und teilst diese Länder dann wiederum in Regionen ein. Die Einteilung in Regionen ist notwendig für das Speichern der Versandkosten, da die Versandkosten nicht für einzelne Lieferländer, sondern nur für Regionen angegeben werden. Außerdem richtest du den Versanddienstleister und das Versandprofil inklusive der Versandkosten ein.

[#100]
== Bereits vorbereitete Einstellungen

In deinem System sind bereits einige Einstellungen für dich vorbereitet, damit du noch schneller mit dem Verkauf deiner Artikel starten kannst:

* die Lieferländer Deutschland und United Kingdom sind aktiv
* die Region *Germany* mit dem Lieferland Deutschland ist erstellt
* das Versandprofil für DHL ist erstellt +
→  hier musst du noch weitere Einstellungen vornehmen

Wie du die hier genannten voreingestellten Optionen anpasst und weitere Einstellungen vornimmst, ist in in den folgenden Kapiteln beschrieben.

[#200]
== Lieferländer einrichten

Standardmäßig sind in deinem System bereits die Lieferländer _Deutschland_ und _United Kingdom_ aktiviert. Gehe wie im Folgenden beschrieben vor, um weitere Lieferländer einzurichten.

[.instruction]
Lieferländer einrichten:

. Öffne das Menü *System » Aufträge » Versand » Optionen*. +
→ Das Tab *Lieferländer* wird geöffnet.
. Wähle für die gewünschten Lieferländer in der Spalte *Aktiv* die Option *Aktiv* aus der Dropdown-Liste.
. Wähle in der Spalte *Lager* das Lager, das bei Bestellungen aus diesen Ländern als Standardlager gewählt werden soll.
. *Speichere* die Einstellungen.

////
TODO
Lager wird hier schon erwähnt, kommt aber in der Reihenfolge des Schnelleinstiegs erst an späterer Stelle
////

[#300]
== Lieferländer in Regionen einteilen

Aktivierte Lieferländer müssen in Regionen eingeteilt werden. Das Erstellen von Regionen ist notwendig, da du Versandkosten nur für Regionen und nicht für Länder angeben kannst. Ordne alle Lieferländer, für die du die gleichen Versandkosten berechnen lassen möchtest, einer Region zu.

Es ist es wichtig, dass du dir im Vorfeld genau überlegst, wie du die Lieferländer gruppieren möchtest, denn einmal gewählt, ist das Lieferland nicht mehr für andere Regionen verfügbar. Ein sinnvolles Beispiel aus europäischer Sicht ist z.B. die Einteilung in die Regionen _Inland_, _Europa_, _Welt_.

Standardmäßig ist in deinem System bereits die Region *Germany* mit dem Lieferland Deutschland eingerichtet.

Gehe wie im Folgenden beschrieben vor, um weitere Regionen zu erstellen.

[.instruction]
Lieferländer in Regionen einteilen:

. Öffne das Menü *System » Aufträge » Versand » Optionen*.
. Wechsele in das Tab *Regionen » Neue Region*.
. Gib einen Namen für die Region ein, z.B. _Europa_.
. Wähle unter *Verfügbare Länder* die eben aktivierten Länder für diese Region. +
→ Die Länder werden unter *Ausgewählte Länder* verschoben.
. *Speichere* die Einstellungen. +
→ Die neue Region ist im Tab *Übersicht* verfügbar.

//Lege weitere Regionen analog an, bis alle zuvor aktivierten Lieferländer einer Region zugeordnet sind und der Bereich *Verfügbare Länder* vollständig leer ist.

[#400]
== Versanddienstleister einrichten

Jetzt erfährst du, wie du den Versanddienstleister, mit dem du deine Artikel an deine Kunden verschicken möchtest, einrichtest. Voraussetzung ist, dass du dich bei dem Versanddienstleister vorab registriert hast.

////
TODO
DHL Plugin beschreiben und auf das Erstellen neuer VDs verlinken
////

[.instruction]
Versanddienstleister einrichten:

. Öffne das Menü *System » Aufträge » Versand » Optionen*.
. Wechsele in das Tab *Versanddienstleister*. +
→ Der Versanddienstleister *DHL* ist bereits vorhanden.
. Passe ggf. den Namen des Versanddienstleisters in den Feldern *Name (de)* und *Name (Backend)* ein. +
→ Der *Name (de)* ist für deine Kunden im Webshop sowie auf Rechnungen sichtbar. Der *Name (Backend)* ist für die Kunden nicht sichtbar und dient der internen Unterscheidung für dich und deine Mitarbeiter.
. Wähle den Versanddienstleister *DHL Shipping (Versenden)* aus der Dropdown-Liste *Versanddienstleister*.
//. Gib die *Tracking-URL* des Versanddienstleisters ein. Beachte die Informationen in der grünen Box.
. Gib die Adresse des Versanddienstleisters ein. +
→ Dies ist notwendig, um DSGVO-konform arbeiten zu können. Weitere Informationen dazu erhältst du auf der Handbuchseite <<auftragsabwicklung/fulfillment/versand-vorbereiten#800, Versand vorbereiten>>.
. *Speichere* die Einstellungen.

[TIP]
.Tracking-URL
====
Die Tracking-URL dient der Sendungsverfolgung der Pakete. Wenn du die URL in deinem plentymarkets System eingibst, kannst du diese dem Kunden in der Versandbestätigung mitteilen, sodass er verfolgen kann, wann die Lieferung bei ihm eintrifft. Die Tracking-URL erhältst du direkt bei dem Versanddienstleister.

Damit der Kunde genau für seine Sendung die Tracking-URL erhält, muss die URL die Paketnummer und oftmals auch die PLZ des Empfängers enthalten. Damit du diese Angaben nicht bei jeder Sendung einzeln angeben musst, fügst du einfach die Template-Variablen *[PaketNr]* und *[PLZ]* in die Tracking-URL ein.

Beispiel für eine DHL-Tracking-URL mit eingefügten Template-Variablen: +
+http://nolp.dhl.de/nextt-online-public/set_identcodes.do?lang=de&zip=[PLZ]&idc=[PaketNr]+
====

[#500]
== Versandprofil einrichten

Im Versandprofil legst du die Versandkosten fest und bestimmst, wie die Versandkosten ermittelt werden: auf Basis der Artikelgewichte, der Volumina oder der Artikelpreise. Du kannst für jeden Versanddienstleister mehrere Versandprofile erstellen. Wenn mehrere Versandprofile möglich sind, kann dein Kunde später im Webshop ein Profil wählen.

Damit plentymarkets weiß, wie ein Artikel verschickt werden soll und dem Kunden nur diese Versandprofile im Webshop zur Auswahl stellt, musst du deine Artikel mit dem Versandprofil verknüpfen.

[TIP]
.Versandprofile einfach halten
====
Gestalte die Versandprofile so einfach wie möglich. Je komplexer die Einstellungen sind, desto eher kann es zu Fehlern kommen. Außerdem könntest du deine Kunden durch zu komplizierte Versandkostenmodelle verwirren und damit letztlich vom Kauf abhalten.
====

[.instruction]
Versandprofil einrichten:

. Öffne das Menü *System » Aufträge » Versand » Optionen*.
. Wechsele in das Tab *Versandprofile*.
. Klicke auf *Neu*, um ein neues Versandprofil einzurichten oder in die Zeile eines bestehenden Versandprofils, um es zu bearbeiten.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-versandprofil-einrichten>>.
. *Speichere* die Einstellungen.

[[tabelle-versandprofil-einrichten]]
.Versandprofil einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|Jedes Versandprofil erhält nach dem Speichern automatisch eine ID. Diese ID ist nicht änderbar.

|*Versanddienstleister*
|Versanddienstleister für dieses Versandprofil wählen.

|*Name*
|Name eingeben, der dem Kunden im Webshop angezeigt wird.

|*Name (Backend)*
|Name eingeben, der im plentymarkets Backend verwendet wird und dem Kunden nicht angezeigt wird.

|*Markierung*
|Markierung wählen. Die Markierung wird z.B. in der Auftragsübersicht angezeigt.

|*Priorität*
|Priorität wählen, um die Reihenfolge der Versandprofile in der Kaufabwicklung im Webshop festzulegen. Die höchste Priorität ist standardmäßig eingestellt.

|*Kategorie*
|Kategorie wählen, mit der festgelegt wird, wann ein Versandprofil in der Kaufabwicklung angezeigt wird. Kategorie *1* ist standardmäßig eingestellt. +
// Es wird immer das Versandprofil mit der niedrigsten Kategorie angezeigt. +
// Bei mehreren Artikeln wird das gemeinsame Versandprofil mit der niedrigsten Kategorie angezeigt.

|*Bei neuen Artikeln aktivieren*
|Aktivieren, um das Versandprofil automatisch für jeden neuen Artikel einzustellen. +
Wähle bei mindestens einem Versandprofil die Option *Bei neuen Artikeln aktivieren*, damit neuen Artikeln immer automatisch mindestens dieses Profil zugeordnet wird. Ist ein Artikel nicht mit mindestens einem Versandprofil verknüpft, kann dieser auch nicht versendet werden.

//|*Mandanten (Shops)*
//|<<omni-channel/online-shop/mandanten-verwalten#, Mandanten>> wählen, für die das Versandprofil gelten soll (Mehrfachauswahl möglich).

|*Auftragsherkunft*
|Auftragsherkunft wählen, wenn das Versandprofil ausschließlich für bestimmte Aufträge gelten soll. Mindestens ein Versandprofil sollte die Auftragsherkunft *ALLE* beinhalten, damit tatsächlich für alle Aufträge mindestens ein Versandprofil zur Verfügung steht.

|*Gesperrte Zahlungsarten*, *Gesperrte Kundenklassen*
|link:https://marketplace.plentymarkets.com/plugins/payment[Zahlungsarten^] und Kundenklassen wählen, für die das Versandprofil *nicht* gelten soll.

//|*eBay-Konto (nur bei Herkunft eBay)*
//|Konten wählen, die genutzt werden sollen, wenn mehrere <<omni-channel/multi-channel/ebay#30, Konten bei eBay>> bestehen (Mehrfachauswahl möglich).

//|*Listing-Typ (nur für eBay)*
//|<<omni-channel/multi-channel/ebay#350, Listing-Typen>> wählen, für die das Profil gelten soll (Mehrfachauswahl möglich).
|====

[#600]
== Portotabelle erstellen

Nachdem du dein Versandprofil erstellt hast, kannst du dich nun um die Versandkosten kümmern. Dazu erstellst du für jede erstellte Region eine eigene Portotabelle.

Bevor du Werte eingibst, musst du dich pro Region für einen Berechnungstyp entscheiden. Standardmäßig ist der Berechnungstyp *Pauschal* eingestellt.

[.instruction]
Portotabelle erstellen:

. Öffne das Menü *System » Aufträge » Versand » Optionen*.
. Wechsele in das Tab *Versandprofile*.
. Öffne das DHL-Versandprofil. +
→ Das Tab *Base* wird geöffnet.
. Wechsele in das Tab *Portotabelle*.
. Klappe die Region auf.
. Der Berechnungstyp *Pauschal* ist standardmäßig ist in deinem System gewählt.
. Ändere ggf. den Betrag im Feld *Pauschales Porto*. Standardmäßig sind 5,99 Euro eingestellt.
. Ändere ggf. im Feld *Versandkostenfrei ab Warenwert* den Betrag für den Warenwert, ab dem die Versandkosten entfallen. Standardmäßig sind 250,00 Euro eingestellt.
. Ändere ggf. auch die anderen Felder, in denen bereits etwas voreingestellt ist (*Ab Warenwert...* und *...pauschale Versandkosten von*).
. *Speichere* die Einstellungen.

////
TODO

Wenn du die Versandkosten nach Gewicht, Volumen, Menge oder Preis einrichten möchtest,

Beachte dazu die Erläuterungen in <<tabelle-portotabelle-berechnungstypen>>.

[[tabelle-portotabelle-berechnungstypen]]
.Portotabelle; Berechnungstypen
[cols="1,3"]
|====
|Berechnungstyp |Erläuterung

|*Pauschal*
|Pauschalbetrag, z.B. 6,00 EUR, eingeben und Warenwert bestimmen, ab dem die Versandkosten entfallen (optional).

|*Gewichtsabhängig*
|Staffelung eingeben. Je schwerer das Paket, desto höher in der Regel die Versandkosten. Achte darauf, später für jeden Artikel das Gewicht einzugeben. Das größte angegebene Maximum legt also das höchste Gewicht fest, das der Kunde bestellen kann.

|*Volumenabhängig*
|Staffelung in Abhängigkeit der Maßeinheit Kubikmeter eingeben. Achte darauf, später für jeden Artikel die Maße einzugeben.

|*Mengenabhängig*
|Staffelung eingeben. Je mehr Einzelartikel bestellt werden, desto höher sind in der Regel die Versandkosten.

|*Preisabhängig*
|Staffelung eingeben und bestimmen, bis zu welchem Warenwert welche Versandkosten gelten.

|*Artikelporto*
|Bei dieser von eBay bekannten Variante zahlt der Kunde für den ersten Artikel einen bestimmten Betrag und für jeden weiteren Artikel nochmals einen (meist geringeren) Zusatzbetrag. Ab einem gewissen Warenwert kann zusätzlich eine Pauschale eingegeben und schließlich noch ein Warenwert bestimmt werden, ab dem die Versandkosten komplett entfallen.
|====
////

// Durch die Eingabe eines *Mindestwerts* und *Maximalwerts* legst du eine Ober- und Untergrenze fest. Prüfe auch, ob du Versandprofile benötigst, die unter- und oberhalb der definierten Grenzen gültig sind. Wenn du z.B. ein Versandprofil auf den Maximalwert von 200 EUR begrenzt, benötigst du ein weiteres Versandprofil, damit eine Bestellung im Wert von mehr als 200 EUR für deine Kunden möglich ist.

[#700]
== Checkliste

Arbeite die Checkliste durch, um die zuvor beschriebenen Einstellungen zum Thema Versandoptionen zu prüfen.

[%interactive]

* [ ] Lieferländer: Hast du alle Länder, in die du deine Artikel liefern möchtest, aktiviert und einem Lager zugewiesen?
* [ ] Lieferländer: Hast du alle Lieferländer mit gleichen Versandkosten in eine Region eingeteilt?
* [ ] Versanddienstleister: Hast du alle nötigen Versanddienstleister inklusive Tracking-URL erstellt?
//* [ ] Versandprofil: Hast du für alle folgenden Optionen ein gültiges Versandprofil eingerichtet?
//** [ ] Für alle Regionen
// ** [ ] Für alle Marktplätze (Webshop, eBay, Amazon etc.)
//** [ ] Für alle Warenwerte
//** [ ] Für alle Artikel
* [ ] Versandprofil: Hast du für mindestens ein Versandprofil die Option *Bei neuen Artikeln aktivieren* gewählt?
* [ ] Portotabelle: Hast du Portotabellen für alle Regionen erstellt?
* [ ] DHL-Plugin: Hast du alle Einstellungen im Menü *System » Aufträge » Versand » DHL Shipping* vorgenommen?


[#800]
== Mehr zum Thema

* <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>
* link:https://marketplace.plentymarkets.com/plugins/payment[Zahlungsarten^]
* <<auftragsabwicklung/fulfillment/versand-vorbereiten#100, Lieferländer einrichten>>
* <<auftragsabwicklung/fulfillment/versand-vorbereiten#400, Region erstellen>>
* <<auftragsabwicklung/fulfillment/versand-vorbereiten#800, Versanddienstleister erstellen>>
* <<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, Versandprofil erstellen>>
* <<auftragsabwicklung/fulfillment/versand-vorbereiten#1500, Portotabelle erstellen>>
* <<auftragsabwicklung/auftraege/auftragsherkunft#, Auftragsherkunft aktivieren>>
