= Plugins dem System hinzufügen
:lang: de
include::{includedir}/_header.adoc[]
:position: 120
:url: schnelleinstieg/schnelleinstieg-plugins

IMPORTANT: Hast du schon Vorlagen für Rechnung und Stornobelege erstellt? Noch nicht? Dann geht's hier zurück zum Thema <<schnelleinstieg/schnelleinstieg-auftragsabwicklung#, Auftragsabwicklung vorbereiten>>.

Wie du bereits gesehen hast, kannst du die Funktionalität deines Shops durch Plugins erweitern. Einige Plugins können über den Integrations-Assistenten installiert werden, es gibt aber noch viele weitere Möglichkeiten, plentymarkets zu erweitern. Zu diesem Zweck werden wir beispielhaft dem System ein neues Plugin hinzufügen, dieses installieren und einrichten.

Mit unserem neuen Plugin wollen wir Kunden die Möglichkeit geben, die Artikel in unserem Shop zu bewerten und diese Bewertungen anderen potenziellen Käufern anzeigen. Dazu werden wir das Plugin Kunden-Feedback nutzen. Dieses Plugin ist gratis über plentyMarketplace erhältlich.

[.instruction]
Plugins dem System hinzufügen:

. Öffne das Menü *Plugins » Plugins-Übersicht*.
. Klicke auf *plentyMarketplace*. +
→ Der Marktplatz wird in einem neuen Tab geöffnet.
. Nutze die Suchfunktion, um nach dem Plugin Kunden-Feedback zu suchen. +
→ Die Suchergebnisse werden angezeigt.
. Klicke auf das Plugin Kunden-Feedback. +
→ Die Artikelansicht wird geöffnet.
. Klicke auf *Zur Kasse*. +
→ Die Kaufansicht wird geöffnet.
. Akzeptiere die AGB, indem du die Option aktivierst.
. Klicke auf *Kaufen*. +
→ Es wird eine Nachricht angezeigt, die bestätigt, dass du das Plugin erfolgreich erworben hast. Nach einigen Minuten wird es in deinem System als nicht installiertes Plugin erscheinen.

[TIP]
.Einstellungsmöglichkeiten
====
In der Artikelansicht jedes Plugins wird auch beschrieben, welche Einstellungsmöglichkeiten für das jeweilige Plugin zu Verfügung stehen. Im Rahmen des Schnelleinstiegs werden die notwendigen Schritte aber auch im Folgenden genauer beschrieben.
====

Als nächstes werden wir das neu gekaufte Plugin installieren. Gehe dazu wie bei der Installation des Plugins Vorkasse im letzten Kapitel vor.

[.instruction]
Kunden-Feedback im Set installieren:

. Wenn du dich nicht immer noch in dieser Ansicht befindest, öffne das Menü *Plugins » Plugins-Übersicht*.
. Deaktiviere die Option *Installiert* und aktiviere die Option *Nicht installiert*. Klicke dann auf *Suchen*. +
→ Alle nicht installierten Plugins werden angezeigt.
. Klicke in der Zeile *Kunden-Feedback* in der Spalte *Aktion* auf *Plugin installieren*. +
→ Ein Fenster zur Auswahl der zu installierenden Version öffnet sich. Klicke auf *Installieren*. +
→ Das Plugin wird installiert und ist in der Plugin-Übersicht des Plugin-Sets verfügbar. Eine Ansicht mit allen installierten Plugins wird angezeigt.

Sobald das Plugin installiert ist, kann es eingerichtet werden. Damit die Funktionalität später aber auch tatsächlich nutzbar wird, muss es auch noch aktiviert werden.

[.instruction]
Kunden-Feedback im Set aktivieren:

. Klicke in der Zeile Kunden-Feedback in der Spalte *Aktiv* auf *Inaktiv*. +
→ Das Plugin wird aktiviert.

Jetzt beginnen wir mit der Einrichtung. Bei manchen Plugins, wie *Vorkasse*, werden diese Einstellungen in den Systemeinstellungen vorgenommen. Bei anderen, wie *Kunden-Feedback*, geschieht dies direkt in der Plugin-Übersicht.

[.instruction]
Kunden-Feedback einrichten:

. Klicke auf das Plugin Kunden-Feedback. +
→ Die Detailansicht des Plugins wird geöffnet. Das Tab *Einstellung* ist bereits ausgewählt.
. Aktiviere die Option *Bewertungen automatisch veröffentlichen*, *Datum an der Bewertung anzeigen* und *Bewertungen nur erlauben, wenn der Artikel gekauft wurde*.
. *Speichere* die Einstellungen.

Mit diesen Einstellungen können Kunden nach dem Kauf eines Artikels eine Bewertung für diesen Artikel schreiben. Die Bewertung wird automatisch angezeigt und ist für andere Kunden sichtbar, die den entsprechenden Artikel aufrufen.

Abschließend müssen wir noch dafür sorgen, dass das Feedback auch wirklich in unserem Shop angezeigt wird. Dazu müssen wir einige Container-Verknüpfungen erstellen.

[.instruction]
Container-Verknüpfungen einrichten:

. Öffne das Menü *CMS » Container-Verknüpfungen*.
. Öffne das Dropdown-Menü *Feedback Javascript (Feedback*).
. Aktiviere die Option *Script loader: Register/load JS*.
. Öffne das Dropdown-Menü *Feedback CSS (Ceres) (Feedback)*.
. Aktiviere die Option *Template: Style*.
. Öffne das Dropdown-Menü *Feedback ratings (Feedback)*.
. Aktiviere die Option *Single item: Container for customer feedback*.
. Öffne das Dropdown-Menü *Feedback category ratings (Feedback)*.
. Aktiviere die Option *Category item list: Before prices container*.
. *Speichere* die Verknüpfungen.

Damit sind alle Einstellungen abgeschlossen und Kunden werden die Möglichkeit haben, Artikel nach dem Kauf auch zu bewerten. Im nächsten Kapitel kehren wir zu einem der standardmäßig installierten Plugins zurück: Ceres. Mit diesem Plugin kann das Aussehen des Shops beeinflusst werden.

== Mehr zum Thema Plugins

* <<plugins, Plugins verwalten>>
* link:https://marketplace.plentymarkets.com/[plentyMarketplace^]

TIP: Weiter zum Thema <<schnelleinstieg/schnelleinstieg-ebay#, eBay>>
