= Zahlungsabwicklung einrichten
:lang: de
include::{includedir}/_header.adoc[]
:position: 60
:url: schnelleinstieg/schnelleinstieg-zahlungsabwicklung
:id: LKPTJCQ

IMPORTANT: Hast du schon das Plugin-Set *standard-shop* deaktiviert? Noch nicht? Dann geht's hier zurück zum Thema <<schnelleinstieg/schnelleinstieg-webshop-einleitung#, Webshop einrichten: Einleitung>>.

In deinem Ceres Webshop kannst du deinen Kunden verschiedene Zahlungsarten anbieten. Alle Zahlungsarten werden über die Plugin-Struktur von plentymarkets integriert. Je nach deinen Wünschen kannst du eine Vielzahl von Zahlungsarten in deinem Webshop anbieten. +

Auf dieser Seite erklären wir dir, wie du die Zahlungsarten PayPal und Vorkasse in deinem Webshop anbietest. Zudem findest du hier Informationen zu den notwendigen Grundeinstellungen, damit Zahlungen jeder Art korrekt in deinem plentymarkets System verarbeitet werden.

[#10]
== Zahlungsarten einrichten

Im Folgenden stellen wir dir die Zahlungsarten PayPal und Vorkasse vor und erklären dir, wie du diese in deinem Webshop anbietest.

[#20]
=== PayPal einrichten

Das PayPal-Plugin ist standardmäßig in deinem plentymarkets System installiert und aktiviert. Dies erkennst du im Menü *Plugins » Plugin-Übersicht* an der blau gefärbten Weltkugel.
Du musst über ein PayPal-Geschäftskonto verfügen, um das PayPal-Plugin zu nutzen. Nimm nach der Erstellung des PayPal-Geschäftskontos die folgenden Schritte zur Einrichtung des Plugins vor.

[.instruction]
PayPal-Plugin einrichten:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Plugins » PayPal » Kontoeinstellungen*.
. Klicke auf das grüne Plus, um ein neues PayPal-Konto hinzuzufügen.
. Gib die E-Mail-Adresse an, die du zur Erstellung deines PayPal-Geschäftskontos genutzt hast.
. Wähle die Option *Live-Umgebung*, die das eingegebene Konto für Zahlungen deiner Kunden im Webshop zur Verfügung stellt. +
*_Alternativ:_* Stelle zuerst die nicht sichtbare *Testumgebung* ein und wechsle am Ende der Einrichtung auf die *Live-Umgebung*.
. Aktiviere die Option *PayPal PLUS*, falls du dein PayPal-Geschäftskonto für PayPal PLUS freigeschaltet hast.
. Klicke auf *Hinzufügen*. +
→ Du wirst automatisch zu PayPal weitergeleitet.
. Nimm bei PayPal die angezeigten Einstellungen vor.
. Klicke auf *Zurück zu plentymarkets*. +
→ Du wirst zu deinem plentymarkets Backend zurückgeleitet. Dort öffnet sich nun der PayPal-Schnellkonfigurator.
. Nimm die gewünschten Einstellungen im PayPal-Schnellkonfigurator vor. Durch Klick auf die Info-Icons rechts kannst du dir weitere Informationen zu den einzelnen Einstellungen anzeigen lassen.
. Klicke auf *Speichern*. +
→ Dein PayPal-Konto wird mit deinen gewählten Einstellungen eingerichtet.

Sollte es zu einem späteren Zeitpunkt notwendig sein, einzelne Einstellungen im PayPal-Plugin zu ändern, beachte die detaillierte Anleitung in der Beschreibung des Plugins link:https://marketplace.plentymarkets.com/plugins/payment/PayPal_4690[hier^] im plentyMarketplace.

[#40]
=== Vorkasse einrichten

Bei der Zahlungsart Vorkasse werden deine Kunden während des Bestellvorgangs aufgefordert, den Rechnungsbetrag per Banküberweisung zu begleichen. Du versendest die Waren erst, wenn die Zahlung bei dir eingegangen ist. Als Händler bist du gesetzlich verpflichtet, deinen Kunden im Webshop eine gebührenfreie und unkompliziert nutzbare Zahlungsmöglichkeit zur Verfügung zu stellen. Auch für dich als Händler fallen beim Vorkasse-Plugin keine zusätzlichen Kosten an. Deshalb empfehlen wir die Einrichtung und Verwendung dieser Zahlungsart in jedem Fall.

[NOTE]
.Standard-Zahlungsart
====
Die Zahlungsart *Vorkasse* ist in deinem plentymarkets System als Standard-Zahlungsart für den Webshop eingestellt. Du kannst die Standard-Zahlungsart zu einem späteren Zeitpunkt im Menü *System » Systemeinstellungen » Mandant » Standard Shop (Standard) » Aufträge* ändern. Wir empfehlen jedoch, diese Einstellung vorerst beizubehalten.
====

[#50]
==== Grundeinstellungen vornehmen

Nach der Installation des Plugins musst du noch weitere Einstellungen vornehmen, um die Einrichtung abzuschließen. Gehe dazu wie folgt vor.

[.instruction]
Vorkasse-Plugin einrichten:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Plugins » Vorkasse*.
. Wähle den Mandanten *Standard Shop*.
. Nimm die Einstellungen anhand der Informationen in <<tabelle-plugin-vorkasse-einrichtung>> vor.
. *Speichere* die Einstellungen.

[[tabelle-plugin-vorkasse-einrichtung]]
.Zahlungsart *Vorkasse* einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Einstellungen*

|*Sprache*
|Wähle die Sprache aus, für die das Plugin eingerichtet werden soll. Alle nachfolgenden Einstellungen werden in dieser Sprache vorgenommen. Wir empfehlen die Wahl der Option *Deutsch*, wenn du deinen Webshop in deutscher Sprache anbietest. Weitere Sprachen kannst du an einem späteren Zeitpunkt einrichten (siehe Link am Ende des Kapitels).

|*Name*
|Gib den Namen der Zahlungsart ein, so wie er den Kunden in der Kaufabwicklung im Webshop angezeigt werden soll. Standardmäßig ist hier bereits die Benennung *Vorkasse* eingetragen.

|*Infoseite*
|Optional: In der Zahlungsabwicklung kann neben dem Name der Zahlungsart ein Link namens "Details" angezeigt werden. Mit dieser Option legst du fest, ob sich für Kunden nach Klick auf diesen Link eine externe oder eine interne Seite mit Informationen zur Zahlungsart öffnet.

|*Infoseite Intern/Infoseite Extern*
|Optional: Wähle den gleichen Wert wie bei der vorherigen Einstellung *Infoseite*. Hast du dich für die Anzeige einer internen Infoseite entschieden, wählst du hier auch die entsprechende Option. Wähle zusätzlich die ID der Kategorie im Webshop aus, in der die Infoseite angezeigt werden soll.

|*Logo*
|Wir empfehlen, hier die Option *Standard-Logo* auszuwählen. Somit wird dann automatisch das im Plugin hinterlegte Logo für die Zahlungsart Vorkasse in der Kaufabwicklung angezeigt. Um ein selbst gewähltes Logo anzuzeigen, wähle die Option *Logo-URL* und beachte zwingend die nachfolgende Option *Logo-URL*.

|*Logo-URL*
|Wenn du ein selbst gewähltes Logo hinterlegen möchtest, hinterlege hier manuell die URL, die zum Speicherort des Logos führt.

|*Beschreibung*
|Gib hier einen Beschreibungstext (maximal 150 Zeichen) ein, der für die Zahlungsart in der Kaufabwicklung für die Zahlungsart angezeigt wird.

|*Lieferländer*
|Wähle aus, für welche Lieferländer die Zahlungsart verfügbar sein soll. Lieferst du in deinem Webshop eingegangene Bestellungen zunächst erst nach Deutschland, aktiviere nur die Option *Germany*.

2+|*Anzeigedaten*

|*Verwendungszweck*
|Gib den Namen ein, der Kunden auf der Bestellbestätigungsseite als Bezeichnung für das Feld Verwendungszweck angezeigt wird. Standardmäßig ist hier bereits die Benennung *Verwendungszweck* eingetragen. Wir empfehlen, in diesem Feld die Eingabe *Order ID %s* vorzunehmen. Das Prozentzeichen dient als Platzhalter für die Anzeige der Auftrags-ID im Verwendungszweck. So kann die Zahlung in deinem plentymarkets System korrekt zugeordnet werden.

|*Verwendungszweck anzeigen*
|Aktiviere diese Option, um Kunden den Verwendungszweck der Zahlung auf der Bestellbestätigungsseite anzuzeigen.

|*Bankdaten anzeigen*
|Aktiviere diese Option, um Kunden die Bankdaten für die Überweisung des Rechnungsbetrags auf der Bestellbestätigungsseite anzuzeigen. Somit werden dann die Bankdaten angezeigt, die du im Menü *System » Systemeinstellungen » Einstellungen » Bank* hinterlegt hat.
|====

[#60]
==== Anzeigeoptionen festlegen

Die in <<tabelle-plugin-vorkasse-einrichtung>> beschriebenen Einstellungen zu den *Anzeigedaten* erfordern nun noch einige Anpassungen in deinem plentymarkets Backend. Im Folgenden erklären wir dir die nötigen Einstellungen zur Darstellung der Bankdaten auf der Bestellbestätigungsseite sowie die Darstellung des Vorkasse-Logos auf der Startseite deines Webshops.

[NOTE]
.Container-Verknüpfungen
====
In den nachfolgenden Beschreibungen musst du zur korrekten Anzeige von Inhalten in deinem Webshop sogenannte Container verknüpfen. Container stellen Behälter dar, mit denen bestimmte Inhalte verknüpft werden können. Welche Container für ein Plugin verwendet werden können, definierst du im Plugin selbst. Diese Auswahl ist nicht durch den Endnutzer bzw. deine Kunden veränderbar.
====

[.instruction]
Bankdaten auf Bestellbestätigungsseite anzeigen:

. Öffne das Menü *CMS » Container-Verknüpfungen*.
. Wähle aus der Liste den Bereich *Cash in advance bank details (PrePayment)*.
. Aktiviere den Container *Order confirmation: Additional payment information*.
. *Speichere* die Einstellungen. +
→ Die Bankdaten werden auf der Bestellbestätigungsseite deines Webshops angezeigt.

[.instruction]
Vorkasse-Logo auf Startseite anzeigen:

. Öffne das Menü *CMS » Container-Verknüpfungen*.
. Wähle den Bereich *Cash in advance icon (PrePayment)*.
. Aktiviere den Container *Homepage: Payment method container*.
. *Speichere* die Einstellungen. +
→ Das Logo der Zahlungsart Vorkasse wird auf der Startseite deines Webshops angezeigt.

[#70]
=== Weitere Zahlungsarten einrichten

Oben wurde die Einrichtung der Zahlungsarten PayPal und Vorkasse beschrieben. Je nach deinen Wünschen und den Anforderungen deiner Kunden im Webshop kann es später Sinn machen, weitere Zahlungsarten anzubieten. Hierzu steht dir eine große Auswahl an weiteren Plugins zum Download im Bereich link:https://marketplace.plentymarkets.com/plugins/payment[Payment^] des plentyMarketplace zur Verfügung.

[#80]
== Grundeinstellungen für Zahlungen vornehmen

Zusätzlich zur Einrichtung der Plugins für die Zahlungsarten musst du noch einige Einstellungen in deinem plentymarkets Backend vornehmen, damit die Zahlungen im Allgemeinen korrekt verarbeitet werden. Zudem ist die Angabe deiner Umsatzsteuer-ID verpflichtend.

[#90]
=== Regeln für Zahlungseingänge festlegen

Damit Zahlungseingänge wie gewünscht erfasst werden, nimm zuerst die Einstellungen zur Zahlungskulanz und zum Import von Kundenbankdaten vor.

[.instruction]
Regeln für Zahlungseingänge festlegen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Eingänge*.
. Nimm die Einstellungen anhand der Informationen in <<tabelle-grundeinstellungen-zahlungseingang>> vor.
. Klicke auf *Speichern*.

[[tabelle-grundeinstellungen-zahlungseingang]]
.Grundeinstellungen für Zahlungseingänge vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Übereinstimmung für automatische Zuordnung*
|Wähle einen Wert zwischen *0.7* (nicht so genaue Übereinstimmung zur Zuordnung nötig) und *1.0* (genaue Übereinstimmung nötig). Ist dieser Wert höher eingestellt, kann das Problem auftreten, dass eingehende Zahlungen nicht automatisch vom System zugeordnet werden können. Daher ist hier ein Wert von *0,7* voreingestellt.

|*Zahlungskulanz*
|Damit die intern in plentymarkets berechneten Nachkommabeträge (ab der dritten Nachkommastelle) nicht zu falschen Buchungen führen, solltest du hier einen Mindestbetrag von *0,01* eintragen. Das bedeutet, dass Zahlungen mit einer Abweichung von 0,01 € als vollständige Zahlung verbucht werden. Stellst du z.B. *0,05* ein, werden Fehlbeträge bis zu 5 Cent trotzdem als vollständige Zahlung behandelt und verbucht.

|*Kundenbankdaten importieren*
|Wähle aus, ob die *Bankdaten* des Kunden beim Zahlungseingang *importiert* und in den jeweiligen Datensatz des Kontakts hinterlegt werden sollen oder nicht. +
*_Wichtig:_* Da Bankdaten nur mit Zustimmung des Kunden importiert und gespeichert werden dürfen, ist hier standardmäßig *Nein* voreingestellt. Beachte vor dem Aktivieren der Option *Ja* die aktuelle Rechtslage und die DSGVO-Regelung zu diesem Thema.

|*PayPal-Zahlung nur entsprechendem eBay Listing zuordnen, sofern an der Zahlung hinterlegt*
|Wir empfehlen, diese Option in jedem Fall auf *Ja* zu stellen, falls du eBay Listings in Kombination mit der Zahlungsart PayPal verwendest. Sollte an einer PayPal Zahlung eine eBay Listing-ID hinterlegt sein, so wird bei aktivierter Option diese Zahlung genau dem Auftrag zugeordnet, der über eine übereinstimmende eBay Listing-ID verfügt.
|====

[#100]
=== Umsatzsteuer-ID hinterlegen

Für den Standort Deutschland sind die gesetzlich vorgeschriebenen Umsatzsteuersätze von 19% und 7% bereits voreingestellt. Steuerrechtlich verpflichtend ist zusätzlich die Angabe deiner Umsatzsteuer-ID. Gehe wie folgt vor, um eine Umsatzsteuer-ID für Deutschland anzugeben.

[.instruction]
Umsatzsteuer-ID hinterlegen:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung*.
. Öffne das Tab *Umsatzsteuersätze*.
. Gib im Feld *Umsatzsteuer-ID* deine Umsatzsteuer ein.
. Klicke auf *Speichern*.

[IMPORTANT]
.Standorte und steuerliche Einstellungen
====
Die Einstellungen zu Steuersätzen sowie die weiteren Optionen im Tab *Buchhaltung* sind standortabhängig. Das bedeutet, dass du für jedes weitere Lieferland außer Deutschland die korrekten Steuersätze hinterlegen musst. Wir empfehlen bei Unsicherheit grundsätzlich, Änderungen mit einem Steuerberater zu besprechen. Beachte für weitere mögliche Einstellungen zum Thema Buchhaltung auch die Links am Ende dieser Seite.
====

[#110]
== Checkliste

Arbeite die Checkliste durch, um deine Einstellungen zum Thema Zahlungsabwicklung zu prüfen.

[%interactive]

* [ ] Hast du das PayPal-Plugin <<#20, eingerichtet>>?
* [ ] Hast du das PayPal-Plugin <<#30, deaktiviert>>, falls du die Zahlungsart nicht anbieten möchtest?
* [ ] Hast du das Vorkasse-Plugin <<#50, eingerichtet>>?
* [ ] Hast du die <<#60, passenden Container ausgewählt>>, so dass alle Daten für das Vorkasse-Plugin im Webshop angezeigt werden?
* [ ] Hast du die Regeln für <<#90, Zahlungseingänge>> festgelegt?
* [ ] Hast du deine <<#100, Umsatzsteuer-ID>> hinterlegt?
* [ ] Hast du etwaige Rückfragen zu <<#100, steuerlichen Einstellungen>> mit deinem Steuerberater besprochen?

[#120]
== Mehr zum Thema Zahlungsabwicklung

* <<auftraege/buchhaltung#, Buchhaltung>>
* <<payment/zahlungen-verwalten#, Zahlungen verwalten>>
* <<payment/bankdaten-verwalten#63, Bankdaten von Kunden speichern>>
* <<payment/best_practices_paypal#, Best Practices: PayPal-Plugin>>
* link:https://marketplace.plentymarkets.com/plugins/payment/paypal_4690[Weitere Informationen zum PayPal-Plugin im plentyMarketplace^]
* link:https://marketplace.plentymarkets.com/plugins/payment/PrePayment_4758[Weitere Informationen zum Vorkasse-Plugin im plentyMarketplace^]

TIP: Weiter zum Thema <<schnelleinstieg/schnelleinstieg-versandoptionen#, Versandoptionen einstellen>>
