= Ceres-Webshop einrichten
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

Auf dieser Seite erfährst du, wie du dir einen Ceres Webshop aufbaust. Nachdem du deinen Artikelkatalog aufgebaut und die Kategorien eingerichtet hast, erfährst du nun, wie du die benötigten Webshop-Plugins einrichtest.

[#510]
== Vorbereitung

Nachfolgend findest du Informationen zu wichtigen Vorarbeiten für das Einrichten des Ceres Webshops sowie zu den Daten, die du für den Schnelleinstieg und die grundlegenden Einstellungen deines Webshops benötigst.

[#520]
=== Rechtliche Angaben speichern

Für rechtliche Angaben stehen dir in Ceres passende Seiten zur Verfügung, auf denen du Rechtstexte anzeigen kannst. Im Menüpunkt *Rechtliches* speicherst du deine *AGB*, die *Widerrufsbelehrung*, das *Widerrufsformular*, die *Datenschutzerklärung* und das *Impressum* für deinen Webshop.

[#310.instruction]
AGB als Klartext eingeben:

. Öffne das Menü *System » Mandant » Mandant wählen » Webshop » Rechtliches*.
. Klappe die *Sprache* auf.
. Wechsel in das Tab *AGB*.
. Öffne das Tab *Text*.
. Gib den Text für deine AGB ein.
. *Speichere* die Einstellungen.

Gib die Texte für die *Widerrufsbelehrung*, das *Widerrufsformular*, die *Datenschutzerklärung* und das *Impressum* analog in den gewünschten Sprachen ein. Die Texte werden im *Ceres*-Webshop auf den zugehörigen Seiten angezeigt. Bei der Erstellung deiner Rechtstexte kannst du auf Mustertexte zurückgreifen. Lass die Texte am besten im Vorfeld von einem kundigen Fachanwalt prüfen. +

[#520]
=== Standardlieferland, -versandart, -versandprofil und -zahlungsart einstellen

Stelle ein Standardlieferland, eine Standardversandart, ein Standardversandprofil und eine Standardzahlungsart ein. Diese sind für nicht-registrierte Besucher Ihres Webshops vorausgewählt. Für Ceres Webshops kannst du ausschließlich *Plugin-Zahlungsarten* verwenden, die du im link::https://marketplace.plentymarkets.com/plugins/payment[plentyMarketplace^] findest.

[#250.instruction]
Standardlieferland einstellen:

. Öffne das Menü *System » Mandant » Mandant wählen » Aufträge*.
. Wähle unter *Standardlieferland* ein Lieferland pro Sprache.
. Wähle eine *Standardversandart*.
. Wähle ein *Standardversandprofil*.
. Wähle eine *Standardzahlungsart*. +
→ Für die Nutzung im Webshop *Ceres* muss eine *Plugin-Zahlungsart* gewählt werden.
. *Speichere* die Einstellungen. +

[#560]
== Plugin-Set bereitstellen

In deinem plentymarkets System gibt es bereits ein Plugin-Set, in dem alle für einen erfolgreichen Start nötigen Plugins enthalten sind. Das Plugin *IO* stellt die Logik-Grundlage des Webshops zur Verfügung und muss von dir zunächst nicht angepasst werden. Das Plugin Ceres stellt das Standard-Design des Webshops dar und kann von dir nach Belieben angepasst werden. Die beiden Plugin-Zahlungsarten *Vorkasse* und *Paypal* sind bereits installiert, damit deine Kunden so schnell wie möglich in deinem Webshop einkaufen können. +

Die installierten Plugins sind im Menü *Plugins » Plugin-Übersicht* verfügbar. Für den Anfang bietet es sich an, die Plugins über den *Plugin-Set Vorschau*-Button im Vorschaumodus zu testen. Der Vorschaumodus ist nur von Benutzern deines Systems zu erreichen. Einstellungen, die du am Webshop vornimmst, können anschließend über den *Plugin-Set aktivieren*-Button in den Live-Modus übernommen werden.

[.instruction]
Plugin-Set im Vorschaumodus öffnen:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Klicke auf das gewünschte Plugin-Set. +
→ Das Fenster *Plugin-Set Details* wird geöffnet.
. Aktiviere die Plugins *IO* , *Ceres* und *Vorkasse* in der Spalte *Aktiv* durch Klick auf die Weltkugel.
→ Aktivierte Plugins werden in der Spalte *Aktiv* blau hervorgehoben.
. Klicke auf *Speichern & Plugins bereitstellen*. +
→ Der Bereitstellungsprozess wird angestoßen. Dies kann etwas Zeit in Anspruch nehmen.
. Klicke auf *Plugin-Set Vorschau*. +
→ Der Webshop wird mit dem Plugin-Set in einem neuen Browser-Tab geöffnet.

[#570]
== Plugins einrichten

Nachdem du dir den Webshop mit Standardeinstellungen im Vorschaumodus angesehen haben, richtest du nun die Plugins nach deinen Wünschen ein.

[#590]
=== Plugin Ceres einrichten

Dein Webshop wird mit einem voll funktionsfähigen Testdesign angezeigt. Dieses Testdesign kannst du jederzeit nach deinen eigenen Vorstellungen ändern und ergänzen.

[#600]
==== Globale Einstellungen vornehmen

Globale Einstellungen, die sich auf den gesamten Webshop auswirken, nimmst du im Tab *Global* der Konfiguration des Plugins *Ceres* vor. Wähle zunächst das Firmenlogo und die angezeigten Kontaktdaten für deine Kontaktseite aus und speichere <<#680, Informationen über Versandkosten>>.

[.instruction]
Globale Einstellungen vornehmen:

. Öffne das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicke auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*. +
→ Das Tab *Global* ist bereits vorausgewählt.
. Lade unter *Firmenlogo* die Bilddatei deines Firmenlogos hoch. +
. Gib die *E-Mail-Adresse des Kontaktforumlars* ein.
. Aktiviere unter *Kontaktdaten anzeigen* die Felder, die du auf der Kontaktseite anzeigen möchtest.
. *Speichere* die Einstellungen.

Weitere Informationen zum Einrichten der Kontaktseite findest du unter <<omni-channel/online-shop/ceres-einrichten#400, Google reCAPTCHA einrichten>> und unter <<omni-channel/online-shop/ceres-einrichten#405, Karte von Google Maps einrichten>>. +

Um deine Kunden über Versandkosten in deinem Shop zu informieren, verknüpfst du nun im Tab *Global* eine *Kategorie zur Anzeige von Versandkosteninformationen*. +
Erstelle hierfür zunächst eine Kategorie vom Typ *Content*.

[#30.instruction]
Kategorie vom Typ Content erstellen:

. Öffne das Menü *Artikel » Kategorien*.
. Klicke auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Gib einen Namen für die Kategorie ein.
. Wähle die Kategorieart *Hauptkategorie*.
. Klicke auf *Erstellen*. +
→ Die neue Kategorie wird erstellt und im Kategoriebaum angezeigt.
. Öffne die neue Kategorie links im Kategoriebaum.
. Wähle für die Option *Typ* die Einstellung *Content* aus der Dropdown-Liste.
. Aktiviere den *Mandant (Shop)*.
. Wechsel in das Tab *Template*.
. Gib den Inhalt ein, der im Webshop angezeigt werden soll. Dies kann sowohl Freitext als auch HTML sein.
. *Speichere* Sie die Einstellungen.

[IMPORTANT]
====
Du gibst Inhalte für Content-Kategorien im Tab *Template* ein, nicht in den Tabs *Beschreibung 1* oder *Beschreibung 2*.
====

Nach dem Speichern der erstellten Content-Kategorie wird das Plugin *CategoryTemplates* im Menü *Plugin » Plugin-Übersicht* verfügbar. Dieses Plugin stellt Inhalte von Content-Kategorien für Ceres zur Verfügung. Das Plugin muss im Plugin-Set über den Button *Speichern & Plugin-Set bereitstellen* bereitgestellt werden. Anschließend verknüpfst du die Kategorie in den globalen Einstellungen von *Ceres*:

[#40.instruction]
Kategorie verknüpfen:

. Öffne das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicke auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*. +
→ Das Tab *Global* ist bereits vorausgewählt.
. Klicke auf *Kategorie zur Anzeige von Versandkosteninformationen*. +
→ Die Kategorieauswahl wird geöffnet.
. Wähle die zuvor erstellte Kategorie, um die Kategorie für die Anzeige der Versandkosten zu verknüpfen.
. Klicke auf *Auswählen*.
. *Speichere* die Einstellungen. +
→ Die Kategorie wird verknüpft.

Nach dem Verknüpfen der Kategorie muss das Plugin *CategoryTemplates* im Plugin-Set *aktiv* geschaltet und über den Button *Speichern & Plugin-Set bereitstellen* erneut bereitgestellt werden.

[#610]
==== Startseite aktivieren

Kunden gelangen im Regelfall über die Startseite in den Webshop und erhalten hier einen ersten Eindruck. Erstelle diese Seite daher mit Sorgfalt. *Ceres* wird mit einer Standard-Startseite ausgeliefert. Passe diese Startseite über das Drag&Drop-Baukastensystem *ShopBuilder* an, um eigene Inhalte auf der Startseite anzuzeigen.

[.instruction]
Startseite aktivieren:

. Öffne das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicke auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*.
. Wechsel in das Tab *Startseite*.
. Aktiviere die Option *ShopBuilder Startseite anzeigen*.
. Deaktiviere die Option *Standardstartseite anzeigen*.
. *Speichere* die Einstellungen. +
→ Die Standard-Startseite wird deaktiviert und deine Inhalte, die du mit dem ShopBuilder erstellst, werden angezeigt.

[#615]
==== Ceres-Startseite mit dem ShopBuilder erstellen

Du erreichst den ShopBuilder im Menü *CMS » ShopBuilder*. Im Editorbereich kannst du der Startseite Elemente per Drag&Drop hinzufügen, um die Seite deinen individuellen Bedürfnissen anzupassen.

[.instruction]
Elemente zum Vorschaubereich hinzufügen:

. Öffne das Menü *CMS » ShopBuilder*. +
→ Der ShopBuilder wird geöffnet.
. Klicke links in der Navigation auf *Startseite (Ceres)*.
. Erstelle unter *Inhalte für Startseite (Ceres)* eine neue Startseite.
→ Das Fenster *Neue Seite erstellen* öffnet sich.
. Gib einen Namen für deine Startseite ein und wähle die *Standard-Startseite* als Vorlage.
. Klicke auf die erstellte Startseite. +
→ Der ShopBuilder-Editor wird geöffnet.
. Ziehe per Drag&Drop Elemente von der linken Seite in den Vorschaubereich. Beachte dazu die Erläuterungen in <<tabelle-elemente-shop-builder>>.
. *Speichere* die Einstellungen.

Im Shopbuilder stehen dir Strukturelemente und Widgets zur Verfügung. *Strukturelemente* sind Gruppen von Spalten, die mit *Widgets* befüllt werden können, und die dem Design der Seite dienen. *Widgets* sind inhaltliche Elemente, die jeweils einen spezifischen Zweck erfüllen, beispielsweise die Darstellung einer Artikelliste. Es gibt *Widgets*, die nur im Header oder Footer des Webshops platziert werden können. Für die Basiseinrichtung empfehlen wir dir aber, zunächst die mitgelieferten Standardversionen des Headers und Footers zu verwenden.

[[tabelle-elemente-shop-builder]]
.Elemente des ShopBuilders
[cols="1,3"]
|====
|Element |Erläuterung

2+|*Struktur-Elemente*

|*2 Spalten*
|Stellt ein Strukturelement mit 2 Spalten zur Verfügung, die mit den unten aufgeführten Widgets befüllt werden können. Klicke auf *Bearbeiten*, um das Layout des Elements zu ändern. Wähle aus der Dropdown-Liste *Layout* das gewünschte Größenverhältnis der Spalten.

|*3 Spalten*
|Stellt ein Strukturelement mit 3 Spalten zur Verfügung, die mit den unten aufgeführten Widgets befüllt werden können. Klicke auf *Bearbeiten*, um das Layout des Elements zu ändern. Wähle aus der Dropdown-Liste *Layout* das gewünschte Größenverhältnis der Spalten. Bei *gestapelten* Verhältnissen werden 2 Spalten übereinander angezeigt.

|*4 Spalten*
|Stellt ein Strukturelement mit 4 Spalten zur Verfügung, die mit den unten aufgeführten Widgets befüllt werden können. Das Größenverhältnis der Spalten ist nicht anpassbar.
2+|*Widgets*

|*Titelleiste*
|Stellt eine Textbox zur Verfügung. Klicke auf *Bearbeiten*, um Text einzugeben und die <<#616, Farbe>> der Titelleiste zu ändern. Es kann nur Reintext verwendet werden.

|*Bilderkarussell*
|Stellt das Ceres-Bilderkarussell zur Verfügung. Klicke auf *Bearbeiten*, um Bilder hinzuzufügen oder zu entfernen. Bilder können über die Kategorieauswahl, die Eingabe der Varianten-ID oder die Dateiauswahl gewählt werden. Wenn das Bild über die Kategorieauswahl bestimmt wird, wird das erste im Tab Dokumente abgelegte Bild der Kategorie verwendet. Über die Dropdown-Liste *Erscheinungsbild* bestimmst du die <<#616, Farbe>> des Bilderkarussells. Die optimalen Bildergrößen werden in <<omni-channel/online-shop/ceres-einrichten#90, diesem Kapitel>> beschrieben.

|*Bilderbox*
|Stellt einen Container für Bilder zur Verfügung. Klicke auf *Bearbeiten*, um Bilder hinzuzufügen oder zu entfernen. Bilder können über die Kategorieauswahl, die Eingabe der Varianten-ID oder die Dateiauswahl gewählt werden. Wenn das Bild über die Kategorieauswahl bestimmt wird, wird das erste im Tab Dokumente abgelegte Bild der Kategorie verwendet. Über die Dropdown-Liste *Erscheinungsbild* bestimmst du die <<#616, Farbe>> der Bilderbox. Über die Dropdown-Listen *Stil der Box* und *Größe des Bilds* passt du das Widget hinsichtlich Text- und Bildgröße an. Die optimalen Bildergrößen werden in <<omni-channel/online-shop/ceres-einrichten#90, diesem Kapitel>> beschrieben.

|*Artikelliste*
|Stellt die <<#630, Ceres Artikelliste>> zur Verfügung. Klicke auf *Bearbeiten*, um Bilder hinzuzufügen oder zu entfernen. Für die Startseite können Artikellisten mit Kategorieartikeln, mit zuletzt angesehenen Artikeln oder über Tags definierte Artikellisten konfiguriert werden. Bestimme die Art der Sortierung über die *Artikelsortierung* Dropdown-Liste und leg die *Maximale Anzahl der angezeigten Artikel* fest.

|*Text*
|Stellt eine Textbox zur Verfügung. Klicke auf *Bearbeiten*, um Text einzugeben und die <<#616, Farbe>> der Textbox zu ändern. Im Texteditor kann Reintext und, nach Klick auf *</>*, auch HTML eingegeben werden. Es ist nicht möglich, CSS in diesem Widget einzubinden.

|*Liste*
|Stellt eine Liste zur Verfügung, die als Platzhalter dient. Klicke auf *Bearbeiten*, um Listeneinträge oder Icons hinzuzufügen.

|*Linkliste*
|Stellt eine Linkliste zur Verfügung, die als Platzhalter dient. Klicke auf *Bearbeiten*, um einen Listentitel, Listeneinträge oder Icons hinzuzufügen.

|*Trennlinie*
|Stellt eine Trennlinie zur Verfügung, die als Platzhalter dient.

|====

Du kannst Elemente, die du der Startseite hinzufgefügt hast, ebenso leicht wieder entfernen.

[.instruction]
Elemente aus dem Vorschaubereich entfernen:

. Öffne das Menü *CMS » ShopBuilder*. +
→ Der Vorschaubereich wird geöffnet.
. Zeige mit der Maus auf das Element im Vorschaubereich, das du entfernen willst. +
	→ Das Kontextmenü wird eingeblendet.
. Klicke in der rechten oberen Ecke auf *Löschen*, um das Element zu entfernen. +
	→ Das Element wird entfernt und die umliegenden Elemente ordnen sich neu an.
. *Speichere* die Einstellungen. +
→ Die Startseite deines Webshops ist den Einstellungen entsprechend umgestaltet.

Wenn du mit der Einrichtung der Startseite fertig bist, musst du sie im ShopBuilder aktivieren, damit sie in deinem Shop angezeigt wird.

[.instruction]
Startseite aktivieren

. Öffne das Menü *CMS » ShopBuilder*. +
→ Der ShopBuilder wird geöffnet.
. Klicke in der Navigation auf der linken Seite auf *Startseite (Ceres)*.
. Zeige mit der Maus auf die von dir erstellte Startseite.
. Klicke auf die Punkte in der rechten Ecke des Seiten-Icons, um die *Optionen* enzublenden.
. Klicke auf *Aktivieren*
→ Die Startseite wird aktiviert und das Icon wird blau hinterlegt.

Weitere Informationen zur Einrichtung des ShopBuilders findest du auf der <<omni-channel/online-store/shop-builder#, ShopBuilder>> Handbuchseite.

[#620]
==== Navigationsleiste einrichten

In Ceres steht dir entweder eine übersichtliche Navigationsleiste mit zwei Kategorieebenen oder ein umfangreiches Megamenü mit bis zu vier Kategorieebenen zur Auswahl. Je nach Artikelsortiment hast du deine Kategorien bereits erstellt. Richte nun die passende Navigation für deinen Webshop ein.

[.instruction]
Navigationsleiste einrichten:

. Öffne das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicke auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*.
. Wechsel in das Tab *Header*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-navigation>>.
. *Speichere* die Einstellungen.

[[tabelle-navigation]]
.Navigationsleiste einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Position der Navigationsleiste*
|Position wählen, an der die Navigationsleiste im Webshop angezeigt wird. Die Navigationsleiste kann *oben*, *links* oder *oben und links* angezeigt werden. Diese Einstellung bezieht sich nur auf Kategorieseiten.

|*Kategorietypen, die in der Navigationsleiste angezeigt werden*
|Kategorietypen wählen, die in der Navigationsleiste angezeigt werden. Es können *Content-Kategorien*, *Artikel-Kategorien* und *Blog-Kategorien* angezeigt werden. +

|====

Im Shopbuilder kannst du die Kategorienavigation im Header mit dem Widget *Kategorienavigation* individuell anpassen. Hierfür musst du in der ShopBuilder-Übersicht zunächst ein neues Header-Element anlegen.

[.instruction]
Header im ShopBuilder bearbeiten:

. Öffne das Menü *CMS » ShopBuilder*. +
→ Der ShopBuilder wird geöffnet.
. Klicke links in der Navigation auf *Startseite (Ceres)*.
. Erstelle unter *Header-Elemente* einen neuen Header.
→ Das Fenster *Neue Seite erstellen* öffnet sich.
. Gib einen Namen für deinen Header ein und wähle den *Standard-Header* als Vorlage.
. Klicke auf den erstellte Header. +
→ Der ShopBuilder-Editor wird geöffnet.
. Ziehe per Drag&Drop Elemente von der linken Seite in den Vorschaubereich. Beachte dazu die Erläuterungen in <<tabelle-navigation-sb>>.
. *Speichere* die Einstellungen.

[[tabelle-navigation-sb]]
.Kategorienavigation im ShopBuilder einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Kategorie-Navigation* (Header)
|Stellt eine Kategorie-Navigation zur Verfügung. Klicke auf *Bearbeiten*, um die Einstellungen vorzunehmen und den Stil der Kategorie-Navigation, die Kategorieebenen sowie die Anzahl der Kategorien festzulegen. Des Weiteren kann ein Firmenlogo hinzugefügt werden. +

*Beim Scrollen der Seite fixieren* = Aktivieren, um die Kategorie-Navigation immer anzuzeigen. +
*Stil der Kategorie-Navigation* = Wählen, ob die Kategorie-Navigation im normalen Stil oder als Megamenü angezeigt wird. +
*Kategorieebenen des Mega-Menüs* = Wählen, ob das Mega-Menü 2, 3 oder 4 Kategorieebenen anzeigt. Diese Einstellung ist nur wirksam, wenn *Mega-Menü* als *Stil der Kategorie-Navigation* gewählt wurde. +
*Anzahl der Kategorien* = Anzahl der Kategorien eingeben, die in der jeweiligen Ebene des Mega-Menüs angezeigt werden. Diese Einstellung ist nur wirksam, wenn *Mega-Menü* als *Stil der Kategorie-Navigation* gewählt wurde. +
*Firmenlogo* = Bilddatei auswählen, welche als Firmenlogo links oben im Shop angezeigt werden soll. Die gängigen Bildformate (PNG, JPG, etc.) sind zulässig.

|====

[#630]
==== Artikellisten einrichten

Mit Artikellisten lassen sich Artikel gruppieren und im Webshop auf der Startseite und der Einzelansicht eines Artikels hervorheben. Folgende Artikellisten können in Ceres eingerichtet werden:

* Cross-Selling: Cross-Selling-Artikel werden über *Beziehungen* im Webshop angezeigt. Weitere Informationen findest du im Handbuch unter <<artikel/artikel-verwalten#950, Cross-Selling einrichten>>.
* Shop-Aktionen: Listen mit Neuheiten, Sonderangeboten, etc. werden in Ceres mithilfe von Tags abgebildet. Weitere Informationen findest du im Handbuch unter <<artikel/artikel-verwalten#150, Artikel mit Tags versehen>>.
* Zuletzt angesehene Artikel: Eine Liste der vom Kunden zuletzt gesehenen Artikel wird angezeigt.

Artikellisten verknüpfst du bequem über Template-Container an der gewünschten Stelle im Webshop. Richte zunächst die Artikelliste für zuletzt angesehene Artikel ein.

[.instruction]
Zuletzt angesehen-Liste einrichten:

. Öffne das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicke auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*.
. Wechsel in das Tab *Artikellisten*.
. Wähle unter *Erste Artikelliste* die Option *Zuletzt angesehen* aus der Dropdown-Liste.
. *Speichere* Sie die Einstellungen.

Verknüpfe anschließend die Artikelliste in der Einzelansicht eines Artikels im Webshop.

[.instruction]
Artikelliste verknüpfen:

. Öffne das Menü *CMS » Container-Verknüpfungen*.
. Wähle den Bereich *First item list*.
. Wähle den Container *Single item: Container for item lists*
. *Speichere* Sie die Einstellungen. +
→ Die Artikelliste wird in der Einzelansicht eines Artikels im Webshop angezeigt.

Mit dem ShopBuilder kannst du Artikellisten über das Widget *Artikelliste* auf der Startseite anzeigen.

[#640]
==== Kaufabwicklung anpassen

Im Tab *Kaufabwicklung und Mein Konto* nimmst du Änderungen an den Anzeigeoptionen der Kaufabwicklung vor. Wähle die Felder aus, die im Adressformular angezeigt und validiert werden.

[.instruction]
Kaufabwicklung anpassen:

. Öffne das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicke auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*.
. Wechsel in das Tab *Kaufabwicklung und Mein Konto*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-kaufabwicklung-anpassen>>.
. *Speichere* die Einstellungen.

[[tabelle-kaufabwicklung-anpassen]]
.Kaufabwicklung anpassen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Rechnungsadressfelder im Adressformular anzeigen  (DE)*
|Ein, mehrere oder *ALLE* Adressfelder wählen, um diese Felder im Adressformular für das Lieferland *Deutschland* in der Kaufabwicklung anzuzeigen.

|*Rechnungsadressfelder validieren (DE)*
|Ein, mehrere oder *ALLE* Adressfelder aktivieren, um diese Felder bei der Adresseingabe zu validieren.

|*Lieferadressfelder im Adressformular anzeigen (DE)*
|Ein, mehrere oder *ALLE* Adressfelder aktivieren, um diese Felder im Adressformular für das Lieferland *Deutschland* in der Kaufabwicklung anzuzeigen.

|*Lieferadressfelder validieren (DE)*
|Ein, mehrere oder *ALLE* Adressfelder aktivieren, um diese Felder bei der Adresseingabe zu validieren.

|====

Aktiviere, falls nötig, die Formularfelder und die zugehörige Validierung der Felder analog für das Lieferland *Vereinigtes Königreich* (UK).

[#650]
==== Kundenbereich einrichten

Im Tab *Kaufabwicklung und Mein Konto* passt du den *Mein Konto*-Bereich für deine Kunden an.

[.instruction]
Mein Konto-Bereich anpassen:

. Öffne das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicke auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*.
. Wechsel in das Tab *Kaufabwicklung und Mein Konto*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-mein-konto>>.
. *Speichere* die Einstellungen.

[[tabelle-mein-konto]]
.Mein Konto anpassen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Anzahl der Aufträge pro Seite in der Auftragshistorie*
|Anzahl von Aufträgen eingeben, die in der Auftragshistorie pro Seite dargestellt werden.

|*Änderung der Zahlungsart durch den Kunden zulassen*
|Aktivieren, um eine nachträgliche Änderung der Zahlungsart durch den Kunden zuzulassen. Ist diese Einstellung deaktiviert, ist eine Änderung nicht mehr möglich. +
*_Hinweis:_* Diese Einstellung ist standardmäßig aktiviert.

|*Weiterleitung zur Login-Seite durch den Link in der Bestellbestätigung*
|Aktivieren, um registrierte Kunden nach Klick auf den Link in der Bestellbestätigung zur Login-Seite weiterzuleiten. Nach erfolgreichem Login wird die Bestellbestätigung angezeigt. +
*_Hinweis:_* Kunden, die als Gast bestellen, sind von dieser Einstellung nicht betroffen und werden direkt zur Bestellbestätigung weitergeleitet.

|====

[#660]
==== SEO-Metadaten eingeben

Im Tab *SEO* findest du Einstellungen für die Suchmaschinenoptimierung deines Webshops. Hier steuerst du den Zugriff auf die Seiten des Webshops durch Robots.

[.instruction]
Einstellungen für Suchmaschinenoptimierung vornehmen:

. Öffne das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicke auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicke im Verzeichnisbaum auf *Konfiguration*.
. Wechsen in das Tab *SEO*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-seo-einstellungen>>.
. *Speichere* die Einstellungen.

[[tabelle-seo-einstellungen]]
.Einstellungen für Suchmaschinenoptimierung vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Robots-Einstellungen für die Startseite*
|*Alle*, *In Index aufnehmen*, *Links nicht folgen*, *Nicht in den Index aufnehmen* oder *Nicht in den Index aufnehmen und Links nicht folgen* wählen, um den Zugriff durch Robots auf die Startseite deines Webshops zu steuern. Die Werte des Meta-Elements Robots werden von Suchmaschinen-Crawlern ausgewertet. Dem Crawler wird mithilfe dieser Werte mitgeteilt, wie er mit der Seite und den Links auf dieser Seite verfahren soll. +

*Alle* = Startseite des Webshops in den Suchmaschinenindex aufnehmen und Links auf der Seite folgen. +
*In Index aufnehmen* = In Suchmaschinenindex aufnehmen. +
*Links nicht folgen* = Links auf der Seite nicht folgen. +
*Nicht in den Index aufnehmen* = Nicht in den Suchmaschinenindex aufnehmen. +
*Nicht in den Index aufnehmen und Links nicht folgen* = Links nicht folgen und Startseite des Webshops nicht in den Suchmaschinenindex aufnehmen.

|====

Im Menü *CMS » Mehrsprachigkeit* kannst du SEO-relevante Meta-Beschreibungen für die statischen Seiten deines Webshops bearbeiten.
Nimm die SEO-Einstellungen für die *Kontaktseite* sowie die Seiten für *Widerrufsbelehrung*, *Widerrufsformular*, *Impressum*, *Datenschutzerklärung* und *AGB* analog vor.

[#.instruction]
Meta-Beschreibung der Kontaktseite bearbeiten:

. Öffne das Menü *CMS » Mehrsprachigkeit*.
. Wähle im Bereich *Zielsprache* die Sprache, für den du die Meta-Beschreibung bearbeiten willst.
. Klicke unter *Ceres* auf *Kontaktseite*. +
→ Der Kontaktseite-Bereich wird ausgeklappt.
. Gib unter *contactMetaDescription* den gewünschten Inhalt ein.
. *Speichere* Sie die Einstellungen.

[#665]
==== Namen des Webshops und Öffnungszeiten bearbeiten

Im Menü *CMS » Mehrsprachigkeit* gibst du einen Namen für deinen Webshop ein, der im Header des Shops angezeigt wird.

[#.instruction]
Namen des Webshops bearbeiten:

. Öffne das Menü *CMS » Mehrsprachigkeit*.
. Wähle im Bereich *Zielsprache* die Sprache, für den du den Namen des Webshops bearbeiten willst.
. Klicke unter *Ceres* auf *Header*. +
→ Der Header-Bereich wird ausgeklappt.
. Gib unter *Name des Webshops* den gewünschten Namen ein.
. *Speichere* Sie die Einstellungen.

Für das Bearbeiten der Öffnungszeiten deines Shops, gehst du analog vor. Der Eintrag für *Öffnungszeiten* findet sich im Bereich *Kontaktseite*.


[#700]
=== Plugin Vorkasse einrichten

Mit diesem Plugin bindest du die Zahlungsart **Vorkasse** in deinem Webshop ein. Bevor die Zahlungsart im Webshop verfügbar ist, musst du Einstellungen in deinem plentymarkets Backend vornehmen. Prüfe zudem die Einstellungen für **Erlaubte Zahlungsarten** in den <<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Kundenklassen>> und für **Gesperrte Zahlungsarten** in den <<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#710]
==== Lieferländer aktivieren

Aktiviere die gewünschten Lieferländer für die Zahlungsart *Vorkasse*.

[.instruction]
Lieferländer aktivieren:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Aktiviere das Plugin *Vorkasse* durch Klick auf die Weltkugel in der Spalte *Aktiv*.
. Klicke auf *Speichern & Plugins bereitstellen*.
. Öffne das Menü *System » Aufträge » Zahlung » Plugins » Vorkasse*.
. Aktiviere die Lieferländer, die du in deinem Webshop anbietest.
. *Speichere* die Einstellungen. +
→ Die Zahlungsart *Vorkasse* ist in der Kaufabwicklung Ihres Webshops verfügbar.

[#730]
==== Bankdaten in der Bestellbestätigung anzeigen

Die Bankdaten, die in den Einstellungen zentral gespeichert werden, sind im gesamten System verfügbar. Die Bankdaten können auch im Webshop angezeigt werden.

[.instruction]
Bankdaten speichern:

. Öffne das Menü *System » Einstellungen » Bank*.
. Gib deine Bankdaten ein.
. *Speichere* die Einstellungen.

Geh wie im Folgenden beschrieben vor, um die im System hinterlegten Bankdaten und einen Verwendungszweck auf der Bestellbestätigungsseite anzuzeigen.

[.instruction]
Bankdaten anzeigen:

. Öffne das Menü *Plugins » Plugin-Übersicht*.
. Aktiviere das Plugin *Vorkasse* durch Klick auf die Weltkugel in der Spalte *Aktiv*.
. Klicke auf *Speichern & Plugins bereitstellen*.
. Öffne das Menü *System » Aufträge » Zahlung » Plugins » Vorkasse*.
. Gib im Bereich *Anzeigedaten* einen *Verwendungszweck* ein.
. Aktiviere die Option *Verwendungszweck anzeigen*.
. Aktiviere die Option *Bankdaten anzeigen*.
. *Speichere* die Einstellungen.

Nachdem du die Einstellungen vorgenommen hast, verknüpfst du die Bankdaten mit einem Template-Container.

[.instruction]
Bankdaten mit Template-Container verknüpfen:

. Öffne das Menü *CMS » Container-Verknüpfungen*.
. Wähle den Bereich *Cash in advance bank details*.
. Aktiviere den Container *Order confirmation: Additional payment information*.
. *Speichere* die Einstellungen. +
→ Die Bankdaten werden auf der Bestellbestätigungsseite angezeigt.

[#740]
=== Automatischen E-Mail-Versand einrichten

Im Menü *System » Mandant » Mandant wählen » E-Mail » Automatischer Versand* stehen dir verschiedene Ereignisse zur Verfügung, die mit einer E-Mail-Vorlage verknüpft werden können. Wähle aus der Dropdown-Liste die E-Mail-Vorlage, die du zuvor im Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen* <<crm/e-mails-versenden#1200, erstellt>> hast. Dadurch wird bei Eintritt des Ereignisses die E-Mail-Vorlage automatisch an den Kunden versendet.

[.instruction]
Automatischen E-Mail-Versand einrichten:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Automatischer Versand*.
. Wähle in der Zeile des Ereignisses die gewünschte E-Mail-Vorlage aus der Dropdown-Liste. Beachte dazu die Erläuterungen in <<tabelle-ereignisse-automatischer-e-mail-versand>>.
. *Speichern* Sie die Einstellungen.

Mit einem Klick auf *E-Mail-Vorlage bearbeiten* wird die E-Mail-Vorlage im Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen* geöffnet und kann dort <<crm/e-mails-versenden#1700, bearbeitet>> werden.

[[tabelle-ereignisse-automatischer-e-mail-versand]]
.Erläuterungen zu einigen Ereignissen im Menü *System » Mandant » Mandant wählen » E-Mail » Automatischer Versand*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Neue Bestellung über den Webshop*
|Sendet Kunden eine E-Mail mit der Auftragsbestätigung, nachdem der Kaufvorgang im Webshop abgeschlossen wurde.

|*Sende Kunde E-Mail zur Passwortänderung*
|Sendet Kunden eine E-Mail mit einem Link zum neuen Passwort, der aktiv bestätigt werden muss. Die Template-Funktion *{% Link_ChangePassword() %}* muss in der E-Mail-Vorlage enthalten sein.

|*Kundenregistrierung*
|Sendet eine E-Mail als Bestätigung, sobald der Kunde sich als Benutzer im Webshop registriert.

|====


=== Final Check

[%interactive]
* [ ] Hast du die Plugins Ceres, IO, CategoryTemplates und Vorkasse in einem Plugin-Set gespeichert und bereitgestellt?
* [ ] Hast du ein Standardlieferland, eine Standardversandart und ein Standartversandprofil eingestellt?
* [ ] Hast du Vorkasse als Standardzahlungsart hinterlegt?
* [ ] Hast du deine Rechtstexte hinterlegt?
* [ ] Sind die Inhalte deiner Content-Kategorien (bspw. für die Anzeige von Versandkosteninformationen) im Tab *Template* der Kategorie hinterlegt?
* [ ] Hast du die Ceres Standardstartseite deaktiviert und die ShopBuilder Startseite aktiviert?
* [ ] Hast du dir eine Startseite mit dem ShopBuilder gebaut?
* [ ] Hast du die Einstellungen für die einzelnen Tabs der Ceres Konfiguration durchgeführt?
* [ ] Hast du nach deinen Änderungen an den Einstellungen der Ceres Konfiguration das Plugin-Set erneut gespeichert und bereitgestellt?


[#800]
== Mehr zum Thema *Webshop*

* <<omni-channel/online-shop/ceres-einrichten#, Ceres einrichten>>
* <<omni-channel/online-shop/io-einrichten#, IO einrichten>>
* <<omni-channel/online-shop/shop-builder#, ShopBuilder einrichten>>
* <<omni-channel/online-shop/best-practices#, Ceres Best Practices>>


// Dabei wählen Sie aus verschiedenen Themes, die im https://marketplace.plentymarkets.com/plugins/themes[plentyMarketplace^] zur Verfügung stehen. Wenn Sie Wert auf noch mehr Individualität legen, stehen Ihnen unsere link:https://www.plentymarkets.eu/partner/zertifizierte-agenturen/[zertifizierten Dienstleister^] mit Rat und Tat zur Seite.
