= Ceres-Webshop einrichten
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

////

Diese Seite enthält das Kapitel "Webshop einrichten"

To Do:
- Einleitungstext verfassen
- Kapitelstruktur prüfen
- Kürzen - alles unnötige raus!
- Checkliste für Webshop?
////


Sie haben den Artikelkatalog aufgebaut und die Kategorien eingerichtet. In diesem Kapitel erfahren Sie nun, wie Sie die benötigten Webshop-Plugins kaufen und installieren sowie Ihren Webshop einrichten.

[#510]
== Vorbereitung

Nachfolgend finden Sie Informationen zu wichtigen Vorarbeiten für das Einrichten des Webshops sowie zu den Daten, die Sie für den Schnelleinstieg und die grundlegenden Einstellungen Ihres Webshops benötigen.

[#520]
=== AGB zusammenstellen

Stellen Sie Ihre Allgemeinen Geschäftsbedingungen (AGB) in einem Dokument zusammen. Bei der Erstellung Ihrer AGB können Sie auf Mustertexte zurückgreifen. Lassen Sie den Text am besten von einem kundigen Fachanwalt prüfen.

[#530]
=== Gesetzliches Muster für Widerrufsbelehrung besorgen

Eine ordnungsgemäße Widerrufsbelehrung muss bestimmten formalen und inhaltlichen Anforderungen genügen. Besorgen Sie sich deshalb ein aktuelles gesetzliches Muster.

Partner, die Ihnen bei der Erstellung rechtssicherer Texte behilflich sind, finden Sie unter <<omni-channel/online-shop/webshop-einrichten/extras#, Extras>>.

// link zu extras ist nicht mehr aktuell!!! auf partnerseite verlinken???


////
auflisten, welche plugins standardmäßig im system installiert sind und wofür sie gut sind?
////


[#560]
== Plugins bereitstellen

// hinweis: nach dem bereitstellen kommt nur "hier entsteht ihr neuer webshop."
// => sollte man die plugins jetzt schon bereitstellen oder erst, nachdem man den shop eingerichtet hat?

Die installierten Plugins sind nun im Menü *Plugins » Plugin-Übersicht* verfügbar. Für den Anfang bietet es sich an, die Plugins über den *Plugin-Set Vorschau*-Button im Vorschaumodus zu testen. Der Vorschaumodus ist nur von Benutzern Ihres Systems aus zu erreichen. Einstellungen, die Sie am Webshop vornehmen, können anschließend über den *Plugin-Set aktivieren*-Button in den Produktivmodus übernommen werden. Bevor Sie die Plugins bereitstellen, legen Sie die Reihenfolge fest, in der die Plugins geladen werden.

[TIP]
.Positionsnummern der Plugins
====
Die installierten Plugins müssen in einer bestimmten Reihenfolge geladen werden, damit sämtliche Routen des Webshops korrekt aufgerufen werden. Das Plugin *IO* stellt die Logik für die Webshop-Routen zur Verfügung. Das Plugin erhält daher die höchste Positionsnummer und wird somit zuletzt geladen. Das Webshop-Plugin *Ceres* erhält eine niedrigere Position, als das Plugin *IO*. Das Plugin *Vorkasse* hat bereits die Positionsnummer *0* und damit die niedrigste Position.
====

[.instruction]
Positionsnummer speichern:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie in der Zeile des Plugins *IO* auf *Position festlegen*. +
→ Das Fenster *Plugin-Position* wird geöffnet.
. Geben Sie eine neue Positionsnummer ein, z.B. *999*.
. *Speichern* Sie die Einstellungen. +
→ Das Plugin *IO* wird in der Liste der Plugins neu angeordnet.

Wiederholen Sie Schritte 2 bis 4 für das Plugin *Ceres* und speichern Sie für *Ceres* z.B. die Positionsnummer *998*.

[.instruction]
Plugins als Vorschau öffnen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Klicken Sie auf das gewünschte Plugin-Set. +
→ Das Fenster *Plugin-Set Details* wird geöffnet.
. Aktivieren Sie die Plugins *IO* , *Ceres* und *Vorkasse* in der Spalte *Aktiv* durch Klick auf die Weltkugel.
. Klicken Sie auf *Speichern & Plugin-Set bereitstellen*. +
→ Der Bereitstellungsprozess wird angestoßen. Dies kann etwas Zeit in Anspruch nehmen.
. Klicken Sie auf *Plugin-Set Vorschau*.
. Wählen Sie den Webshop, den Sie in der Vorschau öffnen wollen. +
→ Der gewählte Webshop wird mit dem gewählten Plugin-Set in einem neuen Browser-Tab geöffnet.

[#570]
== Plugins einrichten

Nachdem Sie sich den Webshop mit Standardeinstellungen im Vorschaumodus angesehen haben, richten Sie nun die Plugins nach Ihren Wünschen ein.

[#580]
=== Plugin IO einrichten

Beginnen Sie mit der Einrichtung des Plugins **IO**. Hier legen Sie beispielsweise die Nachkommastellen für Maße und Gewichte fest. In der Grundeinstellung sind übliche Standardwerte eingegeben.

// Hinweis in englischen Schnelleinstieg einfügen: locale - dezimalzeichen sind deutsch formatiert und müssen für UK angepasst werden.

[.instruction]
Plugin IO einrichten:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicken Sie auf *IO*. +
→ Das Plugin wird geöffnet.
. Klicken Sie im Verzeichnisbaum auf *Konfiguration*. +
→ Das Tab *Template* ist bereits vorausgewählt.
. Wechseln Sie in das Tab *Zahlenformate*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnelleinstieg-zahlenformate>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnelleinstieg-zahlenformate]]
.Zahlenformate anpassen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Anzahl der Nachkommastellen*
|Anzahl der Nachkommastellen eingeben. Standardmäßig sind zwei Nachkommastellen eingestellt.

|*Dezimaltrennzeichen*
|Dezimaltrennzeichen eingeben. Standardmäßig ist das Komma als Dezimaltrennzeichen eingestellt.

|*Tausendertrennzeichen*
|Tausendertrennzeichen eingeben. Standardmäßig ist der Punkt als Tausendertrennzeichen eingestellt.

|*Kundenspezifisches Preisformat verwenden*
|Wählen, ob Preise im jeweiligen Preisformat Ihrer Webshop-Besucher angezeigt werden.

|====

[#590]
=== Plugin Ceres einrichten

Ihr Webshop wird mit einem voll funktionsfähigen Testdesign angezeigt. Dieses Testdesign können Sie jederzeit nach Ihren eigenen Vorstellungen ändern und ergänzen. Dabei wählen Sie aus verschiedenen Themes, die im https://marketplace.plentymarkets.com/plugins/themes[plentyMarketplace^] zur Verfügung stehen. Wenn Sie Wert auf noch mehr Individualität legen, stehen Ihnen unsere link:https://www.plentymarkets.eu/partner/zertifizierte-agenturen/[zertifizierten Dienstleister^] mit Rat und Tat zur Seite.

[#600]
==== Globale Einstellungen vornehmen

Globale Einstellungen, die sich auf den gesamten Webshop auswirken, nehmen Sie im Tab *Global* der Konfiguration des Plugins *Ceres* vor. Speichern Sie zunächst den Namen des Webshops und ändern Sie das Firmenlogo. Später richten Sie im Tab *Global* die <<#690, Kontaktseite>> ein und speichern <<#680, Informationen über Versandkosten>>.

[.instruction]
Globale Einstellungen vornehmen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicken Sie auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicken Sie im Verzeichnisbaum auf *Konfiguration*. +
→ Das Tab *Global* ist bereits vorausgewählt.
. Wählen Sie unter *Firmenlogo* die Bilddatei Ihres Firmenlogos aus. +
→ Das Firmenlogo kann z.B. im Menü *CMS » Webspace* im Ordner *layout* hochgeladen werden.
. *Speichern* Sie die Einstellungen.

[#610]
==== Startseite einrichten

Kunden gelangen im Regelfall über diese Seite in den Webshop und erhalten hier einen ersten Eindruck. Erstellen Sie diese Seite daher mit Sorgfalt. *Ceres* wird mit einer Standard-Startseite ausgeliefert. Passen Sie diese Startseite über den *ShopBuilder* an, um eigene Inhalte auf der Startseite anzuzeigen. Produkt- und Kategorievorschauen sowie Artikellisten werden erst nach Einrichtung angezeigt.

[.instruction]
Startseite einrichten:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicken Sie auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicken Sie im Verzeichnisbaum auf *Konfiguration*.
. Wechseln Sie in das Tab *Startseite*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-startseite-einrichten>>.
. *Speichern* Sie die Einstellungen. +
→ Die Standard-Startseite wird deaktiviert und Ihre Inhalte werden angezeigt.

[[tabelle-startseite-einrichten]]
.Startseite einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ShopBuilder Startseite anzeigen*
|Aktivieren, um die mit dem ShopBuilder erstellte Startseite anzuzeigen. Diese Option muss *aktiviert* sein, um Ihre individuelle Startseite im Webshop anzuzeigen.

|*Standardstartseite anzeigen*
|Aktivieren, um die Ceres Standard-Startseite anzuzeigen. Diese Einstellung muss *deaktiviert* sein, damit Änderungen an der Startseite angezeigt werden.

|====

[#615]
==== Ceres-Startseite mit dem ShopBuilder erstellen

Mit dem ShopBuilder können Sie die Startseite Ihres Ceres Webshops mit wenigen Handgriffen in Ihrem Backend per Drag&Drop erstellen und bearbeiten.

[WARNING]
.Versionsvoraussetzungen für den ShopBuilder
====
Der ShopBuilder ist erst ab Version 2.8.1 von Ceres und IO verfügbar. Sollten Sie eine ältere Version benutzen, können Sie die aktuelle Version der Plugins im Menü *Plugins » Plugin Übersicht* installieren.
====

==== Ceres-Startseite mit dem ShopBuilder bearbeiten

Sie erreichen den ShopBuilder im Menü *CMS » ShopBuilder*. Im Vorschaubereich können Sie der Startseite Elemente hinzufügen, um die Seite Ihren individuellen Bedürfnissen anzupassen.

[NOTE]
.Anzeigen der mit dem ShopBuilder erstellten Startseite
====
Beachten Sie, dass die im ShopBuilder erstellte Startseite erst aktiviert werden muss. Hierzu wählen Sie unter *CMS » ShopBuilder » Übersicht » Einstellungen » Startseite* die Option *ShopBuilder Startseite anzeigen* und deaktivieren die Option *Standardstartseite anzeigen*.
====

[.instruction]
Elemente zum Vorschaubereich hinzufügen:

. Gehen Sie zu *CMS » ShopBuilder*. +
→ Der ShopBuilder wird geöffnet.
. Wählen Sie das gewünschte Plugin-Set aus der *Plugin-Set wählen* Dropdown-Liste.
. Klicken Sie auf *Startseite*. +
	→ Der Vorschaubereich der Startseite wird geöffnet.
. Ziehen Sie per Drag&Drop Elemente von der linken Seite in den Vorschaubereich. Beachten Sie dazu die Erläuterungen in <<tabelle-elemente-shop-builder>>. +
	→ Neue Elemente werden unterhalb der vorhandenen Elemente eingefügt.
. *Speichern* Sie die Einstellungen.

[[tabelle-elemente-shop-builder]]
.Elemente des ShopBuilders
[cols="1,3"]
|====
|Element |Erläuterung

2+|*Struktur-Elemente*

|*2 Felder*
|Stellt ein Strukturelement mit 2 Feldern zur Verfügung, die mit den unten aufgeführten Widgets befüllt werden können. Klicken Sie auf *Bearbeiten*, um das Layout des Elements zu ändern. Wählen Sie aus der Dropdown-Liste *Layout* das gewünschte Größenverhältnis der Felder.

|*3 Felder*
|Stellt ein Strukturelement mit 3 Feldern zur Verfügung, die mit den unten aufgeführten Widgets befüllt werden können. Klicken Sie auf *Bearbeiten*, um das Layout des Elements zu ändern. Wählen Sie aus der Dropdown-Liste *Layout* das gewünschte Größenverhältnis der Felder. Bei *gestapelten* Verhältnissen werden 2 Felder übereinander angezeigt.

|*4 Felder*
|Stellt ein Strukturelement mit 4 Feldern zur Verfügung, die mit den unten aufgeführten Widgets befüllt werden können. Das Größenverhältnis der Felder ist nicht anpassbar.

2+|*Widgets*

|*Titelleiste*
|Dieses Widget stellt eine Textbox zur Verfügung. Klicken Sie auf *Bearbeiten*, um Text einzugeben und die <<#616, Farbe>> der Titelleiste zu ändern.

|*Bilderkarussell*
|Stellt das Ceres-Bilderkarussell zur Verfügung. Klicken Sie auf *Bearbeiten*, um Bilder hinzuzufügen oder zu entfernen. Bilder können über die Kategorieauswahl, die Eingabe der Varianten-ID oder die Dateiauswahl gewählt werden. Bestimmen Sie über die Dropdown-Liste *Erscheinungsbild* die <<#616, Farbe>> des Bilderkarussells.

|*Bilderbox*
|Stellt einen Container für Bilder zur Verfügung. Klicken Sie auf *Bearbeiten*, um Bilder hinzuzufügen oder zu entfernen. Bilder können über die Kategorieauswahl, die Eingabe der Varianten-ID oder die Dateiauswahl gewählt werden. Bestimmen Sie über die Dropdown-Liste *Erscheinungsbild* die <<#616, Farbe>> der Bilderbox. Über die Dropdown-Listen *Stil der Box* und *Größe des Bilds* passen Sie das Widget hinsichtlich Text- und Bildgröße an.

|*Artikelliste*
|Stellt die <<omni-channel/online-shop/ceres-einrichten#110, Ceres Artikelliste>> zur Verfügung. Klicken Sie auf *Bearbeiten*, um Bilder hinzuzufügen oder zu entfernen. Für die Startseite können Artikellisten mit Kategorieartikeln, zuletzt angesehenen Artikeln oder über Tags definierte Artikellisten konfiguriert werden. Bestimmen Sie die Art der Sortierung über die *Artikelsortierung* Dropdown-Liste und legen Sie die *Maximale Anzahl der angezeigten Artikel* fest.
|====

==== Elemente der Ceres-Startseite mit dem ShopBuilder bearbeiten

Im Vorschaubereich können Sie Elemente bearbeiten, um die Seite Ihren individuellen Bedürfnissen anzupassen.

[.instruction]
Elemente im Vorschaubereich bearbeiten

. Gehen Sie zu *CMS » ShopBuilder*. +
→ Der ShopBuilder wird geöffnet.
. Zeigen Sie mit der Maus auf das Element, das Sie bearbeiten wollen. +
→ Das Kontextmenü wird eingeblendet.
. Klicken Sie in der rechten oberen Ecke auf *Bearbeiten*. +
→ Die *Einstellungen*-Leiste wird eingeblendet.
. Nehmen Sie Einstellungen an den Elementen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-elemente-shop-builder>>.
. *Speichern* Sie die Einstellungen. +
→ Die Startseite Ihres Webshops ist den Einstellungen entsprechend umgestaltet.

Ebenso können Sie Elemente auch wieder entfernen.

[.instruction]
Elemente aus dem Vorschaubereich entfernen

. Gehen Sie zu *CMS » ShopBuilder*. +
→ Der Vorschaubereich wird geöffnet.
. Zeigen Sie mit der Maus auf das Element im Vorschaubereich, das Sie entfernen wollen. +
	→ Das Kontextmenü wird eingeblendet.
. Klicken Sie in der rechten oberen Ecke auf *Löschen*, um das Element zu entfernen. +
	→ Das Element wird entfernt und die umliegenden Elemente ordnen sich neu an.
. *Speichern* Sie die Einstellungen. +
→ Die Startseite Ihres Webshops ist den Einstellungen entsprechend umgestaltet.

[#616]
==== Farbeinstellungen im ShopBuilder bearbeiten

Im ShopBuilder können Sie die Hauptfarben für alle Seiten Ihres Shops global verwalten.

[.instruction]
Farben im ShopBuilder bearbeiten:

. Gehen Sie zu *CMS » ShopBuilder*. +
→ Der ShopBuilder wird geöffnet.
. Klicken Sie auf *Startseite*. +
	→ Der Vorschaubereich der Startseite wird geöffnet.
. Klicken Sie auf *Design*. +
	→ Das Menü *Design* wird geöffnet.
. Nehmen Sie die Einstellungen im Breich *Farben* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-farben-shop-builder>>.
. *Speichern* Sie die Einstellungen.


[[tabelle-farben-shop-builder]]
.Globale Farbeinstellungen im ShopBuilder
[cols="1,3"]
|====
|Element |Erläuterung

|*Primary colour*
|Dieses Attribut verändert die Primärfarbe des Shops. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. +
*_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.

|*Secondary colour*
|Dieses Attribut verändert die Sekundärfarbe des Shops. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. +
*_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.

|*Success colour*
|Dieses Attribut verändert die Farbe der Erfolgsmeldungen im Shop. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. *_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.

|*Information colour*
|Dieses Attribut verändert die Farbe der Hinweise im Shop. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. +
*_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.

|*Warning colour*
|Dieses Attribut verändert die Farbe der Warnmeldungen im Shop. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. +
*_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.

|*Danger colour*
|Dieses Attribut verändert die Farbe der Fehlermeldungen im Shop. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. +
*_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.
|====

==== Schriftarten bearbeiten

Sie können die im Webshop verwendeten Schriftarten im Unterpunkt *Design* verwalten.

[.instruction]
Schriftarten im ShopBuilder verwalten:

. Gehen Sie zu *CMS » ShopBuilder*. +
→ Der ShopBuilder wird geöffnet.
. Klicken Sie auf *Startseite*. +
	→ Der Vorschaubereich der Startseite wird geöffnet.
. Klicken Sie auf *Design*. +
	→ Das Menü *Design* wird geöffnet.
. Nehmen Sie die Einstellungen im Breich *Schriften* vor.
. *Speichern* Sie die Einstellungen.


[[tabelle-schriftart-shop-builder]]
.Schriftart im ShopBuilder bearbeiten
[cols="1,3"]
|====
|Option |Erläuterung

|*Schrift-URL einfügen*
|Wählen Sie eine URL und fügen Sie diese in die entsprechende Zeile (regulär, *bold*, _italic_ oder *_bold-italic_*) ein.

|*Schrift hochladen*
|Hierzu müssen Sie eine Schriftart auf Ihrem Rechner gespeichert haben. Wählen Sie in der entsprechenden Zeile (regulär, *bold*, _italic_ oder *_bold-italic_*) die gewünschte Datei aus.
|====


[TIP]
.Auswahl des Plugin-Sets im ShopBuilder

In der Dropdown-Liste kann ein Plugin-Set ausgewählt werden. Die Seitenvorschau zeigt dann die für das Plugin-Set vorgenommenen Einstellungen an (z.B. welche Artikel sichtbar sind).


==== Seite im ShopBuilder erstellen

In der Übersicht des ShopBuilders gibt es die Möglichkeit, Seiten zu erstellen und diese zu benennen.

[.instruction]
Seite erstellen:

. Öffnen Sie das Menü *CMS » ShopBuilder*. +
→ Die Übersicht des ShopBuilders wird geöffnet.
. Klicken Sie auf *Seite hinzufügen*. +
→ Das Fenster *Seitenname* öffnet sich.
. Geben Sie einen Namen ein.
. *Speichern* Sie die Einstellungen. +
→ Die neu erstellte Seite wird in der Übersicht angezeigt.

===== Seite im ShopBuilder bearbeiten

Zurzeit lässt sich in der Übersicht des ShopBuilders lediglich der Name einer Seite bearbeiten. Zukünftig werden jedoch noch weitere Einstellungen hinzukommen.

[.instruction]
Seitenname bearbeiten:

. Öffnen Sie das Menü *CMS » ShopBuilder*. +
→ Die Übersicht des ShopBuilders wird geöffnet.
. Klicken Sie auf *Bearbeiten*, um den Seitennamen zu bearbeiten.
. Wählen Sie einen beliebigen Namen für die Seite.
. *Speichern* Sie die Einstellungen.

==== Seite im ShopBuilder löschen

Im ShopBuilder erstellte Seiten lassen sich auch wieder entfernen.

[.instruction]
Seite löschen:

. Öffnen Sie das Menü *CMS » ShopBuilder*. +
→ Die Übersicht des ShopBuilders wird geöffnet.
. Klicken Sie auf *Löschen*, um eine Seite zu löschen. +
→ Die Seite wird gelöscht.


==== Verknüpfung von im ShopBuilder erstellten Seiten zur Startseite lösen

Jede im ShopBuilder erstellte Seite ist automatisch mit der Startseite verknüpft. Diese Verknüpfung kann jedoch auch gelöst werden.

[.instruction]
Verknüpfung lösen:

. Öffnen Sie das Menü *CMS » ShopBuilder*. +
→ Die Übersicht des ShopBuilders wird geöffnet.
. Wählen Sie die Seite, deren Verknüpfung zur Startseite gelöst werden soll.
. Klicken Sie auf *Verknüpfung erstellen/lösen.* +
→ Die Verknüpfung zur Startseite wird gelöst.

==== Im ShopBuilder erstellte Seiten mit der Startseite verknüpfen

Eine gelöste Verknüpfung zwischen einer im ShopBuilder erstellten Seite und der Startseite kann wiederhergestellt werden.

[.instruction]
Verknüpfung erstellen:

. Öffnen Sie das Menü *CMS » ShopBuilder*. +
→ Die Übersicht des ShopBuilders wird geöffnet.
. Wählen Sie die Seite, die mit der Startseite verknüpft werden soll.
. Klicken Sie auf *Verknüpfung erstellen/lösen*. +
→ Die ausgewählte Seite wird mit der Startseite verknüpft.

Die blaue Markierung zeigt an, dass eine Verknüpfung vorhanden ist.


[#620]
==== Navigationsleiste einrichten

In Ceres stehen Ihnen entweder eine übersichtliche Navigationsleiste mit zwei Kategorieebenen oder ein umfangreiches Megamenü mit bis zu vier Kategorieebenen zur Auswahl. Je nach Artikelsortiment haben Sie Ihre Kategorien bereits erstellt. Richten Sie nun die passende Navigation für Ihren Webshop ein.

[.instruction]
Navigationsleiste einrichten:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicken Sie auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicken Sie im Verzeichnisbaum auf *Konfiguration*.
. Wechseln Sie in das Tab *Header*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-navigation>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-navigation]]
.Navigationsleiste einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Position der Navigationsleiste*
|Position wählen, an der die Navigationsleiste im Webshop angezeigt wird. Die Navigationsleiste kann *oben*, *links* oder *oben und links* angezeigt werden. Diese Einstellung bezieht sich nur auf Kategorieseiten.

|*Navigationsleiste oben fixieren*
|Aktivieren, um die Navigationsleiste im Webshop oben zu fixieren.

|*Kategorietypen, die in der Navigationsleiste angezeigt werden*
|Kategorietypen wählen, die in der Navigationsleiste angezeigt werden. Es können entweder nur *Content-Kategorien*, nur *Artikel-Kategorien* oder eine Kombination aus beidem angezeigt werden. +

|*Warenkorbinformationen anzeigen*
|Informationen wählen, die in der Warenkorbanzeige im Header angezeigt werden. +

|*Kategorieebenen des Megamenüs*
|Anzahl der Kategorieebenen für das Megamenü wählen. Das Megamenü ist ein Navigationselement, welches als Dropdown-Menü mehrere Ebenen gleichzeitig anzeigen kann. +

*Inaktiv* = Das Megamenü ist inaktiv und wird nicht angezeigt. +
*2* = Kategorien der ersten und zweiten Ebene werden im Megamenü angezeigt. +
*3* = Kategorien bis zur dritten Ebene werden im Megamenü angezeigt. +
*4* = Kategorien bis zur vierten Ebene werden im Megamenü angezeigt.

|*Anzahl der Kategorien in der zweiten Ebene*
|Anzahl der Kategorien eingeben, die in der zweiten Kategorieebene des Megamenüs angezeigt werden. Standardmäßig werden 30 Kategorien der zweiten Ebene angezeigt. Kategorien werden nach Position geordnet angezeigt.

|*Anzahl der Kategorien in der dritten Ebene*
|Anzahl der Kategorien eingeben, die in der dritten Kategorieebene des Megamenüs angezeigt werden. Standardmäßig werden 3 Kategorien der dritten Ebene angezeigt. Kategorien werden nach Position geordnet angezeigt.

|*Anzahl der Kategorien in der vierten Ebene*
|Anzahl der Kategorien eingeben, die in der vierten Kategorieebene des Megamenüs angezeigt werden. Standardmäßig werden 2 Kategorien der vierten Ebene angezeigt. Kategorien werden nach Position geordnet angezeigt.

|====

[#630]
==== Artikellisten einrichten

Mit Artikellisten lassen sich Artikel gruppieren und im Webshop auf der Startseite und der Einzelansicht eines Artikels hervorheben. Folgende Artikellisten können in Ceres eingerichtet werden:

* Cross-Selling: Cross-Selling-Artikel werden über *Beziehungen* im Webshop angezeigt. Weitere Informationen finden Sie im Handbuch unter <<artikel/artikel-verwalten#950, Cross-Selling einrichten>>.
* Shop-Aktionen: Listen mit Neuheiten, Sonderangeboten, etc. werden in Ceres mithilfe von Tags abgebildet. Weitere Informationen finden Sie im Handbuch unter <<artikel/artikel-verwalten#150, Artikel mit Tags versehen>>.
* Zuletzt gesehene Artikel: Eine Liste der vom Kunden zuletzt gesehenen Artikel wird angezeigt.

Artikellisten verknüpfen Sie bequem über Template-Container an der gewünschten Stelle in Ihrem Webshop. Richten Sie zunächst die Artikelliste für Ihre Cross-Selling-Artikel ein.

[.instruction]
Cross-Selling-Liste einrichten:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicken Sie auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicken Sie im Verzeichnisbaum auf *Konfiguration*.
. Wechseln Sie in das Tab *Artikellisten*.
. Wählen Sie unter *Cross-Selling: Cross-Selling-Beziehung* die Beziehung für Cross-Selling-Artikel.
. Wählen Sie unter *Erste Artikelliste* die Option *Cross-Selling* aus der Dropdown-Liste. +
→ Eine Liste von Cross-Selling-Artikeln mit der gewählten Beziehung wird im Webshop angezeigt.
. *Speichern* Sie die Einstellungen.

Verknüpfen Sie anschließend die Artikelliste für Cross-Selling-Artikel in der Einzelansicht eines Artikels im Webshop.

[.instruction]
Artikelliste verknüpfen:

. Öffnen Sie das Menü *CMS » Container-Verknüpfungen*.
. Wählen Sie den Bereich *First item list*.
. Wählen Sie den Container *Single item: Container for item lists*
. *Speichern* Sie die Einstellungen. +
→ Die Artikelliste wird in der Einzelansicht eines Artikels im Webshop angezeigt.

[#640]
==== Kaufabwicklung anpassen

Im Tab *Kaufabwicklung und Mein Konto* nehmen Sie Änderungen an den Anzeigeoptionen der Kaufabwicklung vor. Wählen Sie, welche Felder im Adressformular angezeigt und validiert werden.

[.instruction]
Kaufabwicklung anpassen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicken Sie auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicken Sie im Verzeichnisbaum auf *Konfiguration*.
. Wechseln Sie in das Tab *Kaufabwicklung und Mein Konto*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-kaufabwicklung-anpassen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-kaufabwicklung-anpassen]]
.Kaufabwicklung anpassen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Rechnungsadressfelder im Adressformular anzeigen  (DE)*
|Ein, mehrere oder *ALLE* Adressfelder wählen, um diese Felder im Adressformular für das Lieferland *Deutschland* in der Kaufabwicklung anzuzeigen.

|*Rechnungsadressfelder validieren (DE)*
|Ein, mehrere oder *ALLE* Adressfelder aktivieren, um diese Felder bei der Adresseingabe zu validieren.

|*Lieferadressfelder im Adressformular anzeigen (DE)*
|Ein, mehrere oder *ALLE* Adressfelder aktivieren, um diese Felder im Adressformular für das Lieferland *Deutschland* in der Kaufabwicklung anzuzeigen.

|*Lieferadressfelder validieren (DE)*
|Ein, mehrere oder *ALLE* Adressfelder aktivieren, um diese Felder bei der Adresseingabe zu validieren.

|====

Aktivieren Sie die Formularfelder und die zugehörige Validierung der Felder analog für das Lieferland *Vereinigtes Königreich* (UK).

[#650]
==== Kundenbereich einrichten

Passen Sie zudem den *Mein Konto*-Bereich für Ihre Kunden im Tab *Kaufabwicklung und Mein Konto* an. Zusätzlich richten Sie hier auch <<omni-channel/online-shop/ceres-einrichten#430, Retouren>> für Ihren Webshop ein.

[.instruction]
Mein Konto anpassen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicken Sie auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicken Sie im Verzeichnisbaum auf *Konfiguration*.
. Wechseln Sie in das Tab *Kaufabwicklung und Mein Konto*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-mein-konto>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-mein-konto]]
.Mein Konto anpassen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Anzahl der Aufträge pro Seite in der Auftragshistorie*
|Anzahl von Aufträgen eingeben, die in der Auftragshistorie pro Seite dargestellt werden.

|*Änderung der Zahlungsart durch den Kunden zulassen*
|Aktivieren, um eine nachträgliche Änderung der Zahlungsart durch den Kunden zuzulassen. Ist diese Einstellung deaktiviert, ist eine Änderung nicht mehr möglich. +
*_Hinweis:_* Diese Einstellung ist standardmäßig aktiviert.

|*Weiterleitung zur Login-Seite durch den Link in der Bestellbestätigung*
|Aktivieren, um registrierte Kunden nach Klick auf den Link in der Bestellbestätigung zur Login-Seite weiterzuleiten. Nach erfolgreichem Login wird die Bestellbestätigung angezeigt. +
*_Hinweis:_* Kunden, die als Gast bestellen, sind von dieser Einstellung nicht betroffen und werden direkt zur Bestellbestätigung weitergeleitet.

|====

[#660]
==== SEO-Metadaten eingeben

Im Tab *SEO* finden Sie Einstellungen für die Suchmaschinenoptimierung Ihres Webshops. Hier steuern Sie den Zugriff auf die Seiten des Webshops durch Robots.

[.instruction]
Einstellungen für Suchmaschinenoptimierung vornehmen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicken Sie auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicken Sie im Verzeichnisbaum auf *Konfiguration*.
. Wechseln Sie in das Tab *SEO*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-seo-einstellungen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-seo-einstellungen]]
.Einstellungen für Suchmaschinenoptimierung vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Robots-Einstellungen für die Startseite*
|*Alle*, *In Index aufnehmen*, *Links nicht folgen*, *Nicht in den Index aufnehmen* oder *Nicht in den Index aufnehmen und Links nicht folgen* wählen, um den Zugriff durch Robots auf die Startseite Ihres Webshops zu steuern. Werte des Meta-Elements Robots werden von Suchmaschinen-Crawlern ausgewertet. Dem Crawler wird mithilfe dieser Werte mitgeteilt, wie er mit der Seite und den Links auf dieser Seite verfahren soll. +

*Alle* = Startseite des Webshops in den Suchmaschinenindex aufnehmen und Links auf der Seite folgen. +
*In Index aufnehmen* = In Suchmaschinenindex aufnehmen. +
*Links nicht folgen* = Links auf der Seite nicht folgen. +
*Nicht in den Index aufnehmen* = Nicht in den Suchmaschinenindex aufnehmen. +
*Nicht in den Index aufnehmen und Links nicht folgen* = Links nicht folgen und Startseite des Webshops nicht in den Suchmaschinenindex aufnehmen.

|====

Im Menü *CMS » Mehrsprachigkeit* können Sie Meta-Beschreibungen für die statischen Seiten Ihres Webshops bearbeiten.
Nehmen Sie die SEO-Einstellungen für die *Kontaktseite* sowie die Seiten für *Widerrufsbelehrung*, *Widerrufsformular*, *Impressum*, *Datenschutzerklärung* und *AGB* analog vor.

[#665]
==== Namen des Webshops und Öffnungszeiten bearbeiten

Im Menü *CMS » Mehrsprachigkeit* geben Sie einen Namen für Ihren Webshop ein, der im Header des Shops angezeigt wird.

[#.instruction]
Namen des Webshops bearbeiten:

. Öffnen Sie das Menü *CMS » Mehrsprachigkeit*.
. Wählen Sie im Bereich *Zielsprache* die Sprache, für den Sie den Namen des Webshops bearbeiten wollen.
. Klicken Sie unter *Ceres* auf *Header*. +
→ Der Header-Bereich wird ausgeklappt.
. Geben Sie unter *Name des Webshops* den gewünschten Namen ein.
. *Speichern* Sie die Einstellungen.

Falls Sie den Namen des Webshops für andere Sprachen bearbeiten wollen, wiederholen Sie die Schritte für die jeweilige Zielsprache.

Für das Bearbeiten der Öffnungszeiten Ihres Shops, gehen Sie analog vor. Der Eintrag für *Öffnungszeiten* findet sich im Bereich *Kontaktseite*.

[#670]
==== Rechtliche Angaben speichern

Für rechtliche Angaben stehen Ihnen in Ceres passende Templates zur Verfügung, in denen Sie Rechtstexte in den verschiedenen Sprachen anzeigen können. Unter *Rechtliche Angaben* speichern Sie Ihre *AGB*, die *Widerrufsbelehrung*, die *Datenschutzerklärung* und das *Impressum* für Ihren Webshop.

[#.instruction]
AGB als Klartext eingeben:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Webshop » Rechtliches*.
. Klappen Sie die *Sprache* auf.
. Wechseln Sie in das Tab *AGB*.
. Öffnen Sie das Tab *Text*.
. Geben Sie den Text für Ihre AGB ein.
. *Speichern* Sie die Einstellungen.

Alternativ speichern Sie Ihre Rechtstexte im HTML-Format. Nutzen Sie hierfür die Funktionen des HTML-Editors oder geben Sie das HTML als *Quellcode* ein.

[#.instruction]
AGB im HTML-Format eingeben:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Webshop » Rechtliches*.
. Klappen Sie die *Sprache* auf.
. Wechseln Sie in das Tab *AGB*.
. Öffnen Sie das Tab *HTML*.
. Wenn Sie den Text als HTML-Code eingeben möchten, klicken Sie auf *Quellcode*.
. Geben Sie den formatierten Text für Ihre AGB ein.
. *Speichern* Sie die Einstellungen.

Geben Sie die Texte für die *Widerrufsbelehrung*, die *Datenschutzerklärung* und das *Impressum* analog in den gewünschten Sprachen ein. Die Texte werden in *Ceres* auf den zugehörigen Seiten angezeigt.

[#680]
==== Informationen über Versandkosten speichern

Im Tab *Global* verknüpfen Sie eine Kategorie, um im Webshop Informationen zu Ihren Versandkosten anzuzeigen. Erstellen Sie dafür zunächst eine Kategorie vom Typ *Content*.

[.instruction]
Kategorie erstellen:

. Öffnen Sie das Menü *Artikel » Kategorien*.
. Klicken Sie auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Geben Sie einen Namen für die Kategorie ein.
. Wählen Sie die Kategorieart *Hauptkategorie*.
. Klicken Sie auf *Erstellen*. +
→ Die neue Kategorie wird erstellt und im Kategoriebaum angezeigt.
. Öffnen Sie die neue Kategorie links im Kategoriebaum.
. Wählen Sie für die Option *Typ* die Einstellung *Content* aus der Dropdown-Liste.
. Aktivieren Sie den *Mandant (Shop)*.
. Wechseln Sie in das Tab *Template*.
. Geben Sie den Inhalt ein, der im Webshop angezeigt werden soll.
. *Speichern* Sie die Einstellungen.

Nach dem Speichern der Kategorie wird das Plugin *CategoryTemplates* im Menü *Plugin » Plugin-Übersicht* verfügbar. Das Plugin muss über den *Speichern & Plugins bereitstellen*-Button bereitgestellt werden. Anschließend verknüpfen Sie die Kategorie in den Einstellungen von *Ceres*.

[.instruction]
Kategorie verknüpfen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicken Sie auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicken Sie im Verzeichnisbaum auf *Konfiguration*. +
→ Das Tab *Global* ist bereits vorausgewählt.
. Klicken Sie unter *Kategorie zur Anzeige von Versandkosteninformationen* auf *Suchen*. +
→ Das Fenster *Kategorien* wird geöffnet.
. Wählen Sie eine Kategorie, um diese für die Anzeige der Informationen zu Versandkosten zu verknüpfen.
. Klicken Sie auf *Auswählen*.
. *Speichern* Sie die Einstellungen. +
→ Die Kategorie wird verknüpft.
. Stellen Sie das Plugin *Kategorie zur Anzeige von Versandkosteninformationen* erneut bereit.

[#690]
==== Kontaktformular anzeigen

Auf der Kontaktseite zeigen Sie die Kontaktinformationen Ihres Webshops an. Hier richten Sie zudem das Kontaktformular für Kundenanfragen ein. Um die Kontaktseite mit dem Kontaktformular anzuzeigen, geben Sie in der Konfiguration von Ceres eine E-Mail-Adresse an, an die Kundenanfragen gesendet werden.

[.instruction]
Kontaktformular anzeigen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*. +
→ Die Plugin-Übersicht wird geöffnet.
. Klicken Sie auf *Ceres*. +
→ Das Plugin wird geöffnet.
. Klicken Sie im Verzeichnisbaum auf *Konfiguration*.
. Wechseln Sie in das Tab *Global*.
. Geben Sie unter *E-Mail-Adresse des Kontaktformulars* eine E-Mail-Adresse ein.
. *Speichern* Sie die Einstellungen.

Weitere Informationen zum Einrichten der Kontaktseite finden Sie unter <<omni-channel/online-shop/ceres-einrichten#400, Google reCAPTCHA einrichten>> und unter <<omni-channel/online-shop/ceres-einrichten#405, Karte von Google Maps einrichten>>.


[#700]
==== Plugin Vorkasse einrichten

Mit diesem Plugin binden Sie die Zahlungsart **Vorkasse** in Ihren Webshop ein. Bevor die Zahlungsart in Ihrem Webshop verfügbar ist, müssen Sie Einstellungen in Ihrem plentymarkets Backend vornehmen. Prüfen Sie zudem die Einstellungen für **Erlaubte Zahlungsarten** in den <<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Kundenklassen>> und für **Gesperrte Zahlungsarten** in den <<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#710]
===== Lieferländer aktivieren

Aktivieren Sie die gewünschten Lieferländer für die Zahlungsart *Vorkasse*.

[.instruction]
Lieferländer aktivieren:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Aktivieren Sie das Plugin *Vorkasse* durch Klick auf die Weltkugel in der Spalte *Aktiv*.
. Klicken Sie auf *Speichern & Plugins bereitstellen*.
. Öffnen Sie das Menü *System » Aufträge » Zahlung » Plugins » Vorkasse*.
. Wählen Sie einen Mandanten.
. Aktivieren Sie die Lieferländer, die Sie in Ihrem Webshop anbieten.
. **Speichern** Sie die Einstellungen. +
→ Die Zahlungsart *Vorkasse* ist in der Kaufabwicklung Ihres Webshops verfügbar.

[#720]
===== Logo der Zahlungsart auf der Startseite anzeigen

Das Template-Plugin **Ceres** bietet Ihnen auf der Startseite einen Template-Container, in dem Sie die Logos Ihrer Zahlungsart anzeigen können. Gehen Sie wie im Folgenden beschrieben vor, um das Logo der Zahlungsart zu verknüpfen.

[.instruction]
Logo mit Template-Container verknüpfen:

. Öffnen Sie das Menü *CMS » Container-Verknüpfungen*.
. Wählen Sie den Bereich *Cash in advance icon*.
. Aktivieren Sie den Container *Homepage: Payment method container*.
. *Speichern* Sie die Einstellungen. +
→ Das Logo der Zahlungsart wird auf der Startseite des Webshops angezeigt.

[#730]
===== Bankdaten in der Bestellbestätigung anzeigen

Die Bankdaten, die in den Einstellungen zentral gespeichert werden, sind im gesamten System verfügbar. Die Bankdaten können auch im Webshop angezeigt werden.

[.instruction]
Bankdaten speichern:

. Öffnen Sie das Menü *System » Einstellungen » Bank*.
. Geben Sie Ihre Bankdaten ein.
. *Speichern* Sie die Einstellungen.

Gehen Sie wie im Folgenden beschrieben vor, um die im System hinterlegten Bankdaten und einen Verwendungszweck auf der Bestellbestätigungsseite anzuzeigen.

[.instruction]
Bankdaten anzeigen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Aktivieren Sie das Plugin *Vorkasse* durch Klick auf die Weltkugel in der Spalte *Aktiv*.
. Klicken Sie auf *Speichern & Plugins bereitstellen*.
. Öffnen Sie das Menü *System » Aufträge » Zahlung » Plugins » Vorkasse*.
. Wählen Sie einen Mandanten.
. Geben Sie im Bereich *Anzeigedaten* einen *Verwendungszweck* ein.
. Aktivieren Sie die Option *Verwendungszweck anzeigen*.
. Aktivieren Sie die Option *Bankdaten anzeigen*.
. *Speichern* Sie die Einstellungen.

Nachdem Sie die Einstellungen vorgenommen haben, verknüpfen Sie die Bankdaten mit einem Template-Container.

[.instruction]
Bankdaten mit Template-Container verknüpfen:

. Öffnen Sie das Menü *CMS » Container-Verknüpfungen*.
. Wählen Sie den Bereich *Cash in advance bank details*.
. Aktivieren Sie den Container *Order confirmation: Additional payment information*.
. *Speichern* Sie die Einstellungen. +
→ Die Bankdaten werden auf der Bestellbestätigungsseite angezeigt.
