= Die letzten Schritte
:lang: de
include::{includedir}/_header.adoc[]
:position: 0


== Eine letzte Kontrolle
[%interactive]
* [ ] check 1
* [ ] check 2

== Shop live schalten

Jetzt hast du es fast geschafft. Zu Beginn des Schnelleinstiegs haben wir den Webshop gesperrt und alle E-Mails zu Testzwecken an die eigene Adresse gesendet. Diese Einstellungen müssen zum Verkaufsstart wieder zurückgesetzt werden.

[.instruction]
Testmodus deaktivieren:

. Öffne das Menü System » Mandant » Standard Shop (Standard) » E-Mail » Zugangsdaten.
. Wähle aus dem Dropdown-Menü Testmodus die Option Inaktiv aus.
. Speichern Sie die Einstellungen.

[.instruction]
Webshop entsperren:

. Öffne das Menü System » Mandant » Standard Shop (Standard) » Webshop » Einstellungen.
. Klicke auf die Schaltfläche Webshop jetzt entsperren.

*Herzlichen Glückwunsch! Dein Shop ist jetzt online!*

== Bleib auf dem Laufenden

plentymarkets wird ständig verbessert. Damit du über alle Änderungen immer gut informiert bist, empfehlen wird die, im Forum die Kategorie Changelog zu abonnieren. Dafür benötigst du zunächst ein Konto für unser Forum.

[.instruction]
Konto erstellen:
. Im Backend, öffne das Menü System » Einstellungen » Benutzer » Konten » Name deines Benutzerkontos.
. Klicke auf die Schaltfläche Konto erstellen.

[.instruction]
Den Changelog abonnieren:

. Öffne das Menü *Support* und klicke auf *Forum*. +
→ Das Forum öffnet sich in einer neuen Registerkarte.
. Logge dich mit deinen Zugangsdaten im Forum ein.
. Öffne deine Kontoeinstellungen, indem du in der oberen rechten Ecke auf dein Profilbild und anschließend auf die Schaltfläche Einstellungen klickst.
. Öffne das Menü *Kategorien*.
. Gib in das Textfeld *Beobachtet* „Version 7“ ein und bestätige den Eintrag mit der Eingabetaste.
. Speichere die Einstellungen.

Nun erhältst du automatisch eine E-Mail-Benachrichtigung, wenn ein Changelog veröffentlicht wird.

== Mehr zum Handbuch

Wenn du deinen Shop erweiterst und tiefer in das plentymarkets-System einsteigst, wirst du dich wahrscheinlich öfter auch auf dieses Handbuch beziehen. Dabei hast du zwei Möglichkeiten zur Navigation: Den Navigationsbaum und die Suchfunktion. Verwende den Navigationsbaum, um das Handbuch explorativ zu erkunden oder wenn du dir einen Überblick über ein komplettes Thema verschaffen möchtest. Mit der Suchfunktion kannst du direkt nach Schlagwörtern suchen.

[NOTE]
.Versionen

====
Das Handbuch beschreibt die Funktionalität von plentymarkets gemäß der Beta-Version. Neue Systeme werden jedoch in der Version Stable ausgeliefert. Dies hat zur Folge, dass einige Angaben im Handbuch möglicherweise bis zu zwei Wochen lang von deiner Systemumgebung abweichen.

Wenn du dein System auf eine andere Version umstellen möchtest, findest du Information dazu in deinem Backend im Menü *System » Mandant » Standard-Shop (Standard) » Version*.
====

== Mehr von plentymarkets
