= Auftragsabwicklung
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

Die Aufträge, die über deinen Webshop eingehen, verwaltest du als Händler im Backend deines plentymarkets Systems. Auf dieser Seite findest du die nötigen Einstellungen, die im Vorfeld für die Auftragsabwicklung vorgenommen werden müssen.

[#100]
== Grundeinstellungen vornehmen

Zuerst nimmst du die grundlegenden Einstellungen für den Bereich *Aufträge* vor. Einige davon sind in deinem plentymarkets System bereits voreingestellt. Wir empfehlen, diese Voreinstellungen vorerst nicht zu ändern. Andere Einstellungen solltest du jedoch zwingend anpassen. Diese werden in <<tabelle-auftraege-schnelleinstieg-grundeinstellungen>> erläütert. Gehe wie im Folgenden beschrieben vor:

[.instruction]
Grundeinstellungen vornehmen:

. Öffne das Menü *System » Aufträge » Einstellungen*.
. Nimm die Einstellungen anhand <<tabelle-auftraege-schnelleinstieg-grundeinstellungen>> vor.
. *Speichere* die Einstellungen.

[[tabelle-auftraege-schnelleinstieg-grundeinstellungen]]
.Grundeinstellungen vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Automatische Lagerauswahl*
|Die automatische Lagerauswahl wählt beim Auftragseingang automatisch das entsprechende Lager der enthaltenen Auftragspositionen aus. Wir empfehlen die Wahl einer der beiden folgenden Optionen: +
*b) in Abhängigkeit des Hauptlagers des Artikels*: Entscheidend bei der Auswahl des Lagers ist hier das Hauptlager des Artikels, das du zuvor in den Variantendaten eines gespeichert haben musst. Diese Einstellung ist sinnvoll, wenn du bestimmte Artikel immer aus einem festen Lager versenden willst. +
*c) in Abhängigkeit des höchsten Warenbestandes*: Bei dieser Option wird das Lager anhand des höchsten Warenbestandes des Artikels ausgewählt. Diese Option macht Sinn, wenn ein Artikel aus mehreren Lagern versendet wird. Wir empfehlen die Option weiterhin auch dann, wenn du voerst nur ein einziges Lager betreibst. Solltest du zu einem späteren Zeitpunkt aus mehreren Lagern versenden, ist bei dieser Einstellung keine Änderung mehr nötig.

|*Statuswechsel auf 4 statt 5, wenn Warenbestand fehlt*
|Wir empfehlen, hier die Option *JA* zu wählen. Somit wird anhand einer Warenbestandsautomatik verhindert, dass Aufträge, die Artikel enthalten zu denen kein Warenbestand in deinem Lager vorhanden ist, fälschlicherweise in den Status *[5] Freigabe Versand* wechseln. Stattdessen verbleiben Sie automatisch im *Status [4] in Versandvorbereitung*.
|====

[#200]
== Auftragsdokumente einrichten
////
Vorlagen für Auftragsdokumente einrichten! Beispiel anhand einem standort, einer sprache und einem dokument erklären. zb standard-rechnung oder auch lieferschein erstellen. Input Support: Stornobelege nicht vergessen und Hinweis, dass Aufträge für bearbeitung gesperrt werden sobald eine Rechnung erzeugt wurde. Stornobeleg storniert dann das Dokument (zB. Rechnung, NICHT den Auftrag an sich.)
////

[#300]
== Stornobelege einrichten
////
Vorlagen für Stornobelege einrichten. Sinn und zweck von stornobelegen kurz beschreiben. Auftrag gesperrt wenn rechnung da. Stornobeleg hilft. buchhalterisch relevant.
////

[#400]
== Auftragsübersicht nutzen
////
Was geht da, was beinhaltet sie, wo finde ich die, filter- und suchmöglichkeiten
3. Allgemeiner Beschreibungstext für Auftragsabwicklung - soll ans Ende (Links entfernen und auch kürzen)
////

[#500]
== Aufträge verwalten
////
3. Allgemeiner Beschreibungstext für Auftragsabwicklung - soll ans Ende (Links entfernen und auch kürzen)
4. Wichtige Bearbeitungsmöglichkeiten in der Auftragsübersicht
- Filter- und Suchmöglichkeiten auf der linken seite
- Aufträge nicht löschen
- manuell auftrag stornieren
- Immer auch auf Automatisierungsmöglichkeiten durch Ereignisaktionen hinweisen
- Wo werden manuell Warenausgang und Zahlung gebucht, wo werden Auftragsdokumente generiert falls das mal sein muss oder nicht automatisiert wird?
////

////
TODO

3. Allgemeiner Beschreibungstext für Auftragsabwicklung - soll ans Ende (Links entfernen und auch kürzen)

Im Menü *Aufträge » Aufträge verwalten” hast du jederzeit Zugriff auf alle Aufträge, egal ob sie über deinen Ceres Webshop[link] oder über Marktplätze wie Amazon[link] oder eBay[link] in deinem System eingehen oder manuell angelegt wurden. Zudem erkennst du in der Auftragsübersicht direkt, ob es sich um eine Gutschrift, eine Retoure oder einen anderen Auftragstypen handelt. Mehr Informationen zu den verschiedenen Auftragstypen und zur manuellen Auftragsanlage findest du auf der Handbuchseite <<auftragsabwicklung/auftraege/auftraege-verwalten#, Aufträge verwalten>>.

Den aktuellen Stand der Auftragsabwicklung verfolgst du anhand der Statusanzeige, die an jedem Auftrag in der Auftragsübersicht farblich markiert ist. In deinem plentymarkets System sind einige Status standardmäßig voreingestellt und dürfen nicht verändert werden. Du kannst jedoch im Menü *System » Aufträge » Status* beliebig viele Auftragsstatus hinzufügen, um die Schritte deiner Auftragsabwicklung optimal abzubilden. Beachte hierzu die Anleitungen und Tipps zum Umgang mit Auftragsstatus im Kapitel <<auftragsabwicklung/auftraege/auftraege-verwalten#1200, Auftragsstatus nutzen>>.

Durch einen Klick auf die Auftrags-ID in der Auftragsübersicht öffnest du einen bestimmten Auftrag. Die Tabs innerhalb eines Auftrags geben dir vielfältige Bearbeitungsmöglichkeiten. So kannst du im Tab *Kunde* auf die Kontaktdaten des Kunden zugreifen oder im Tab *Belege* manuell Auftragsdokumente wie Rechnungen oder Lieferscheine erstellen.
////

== Checkliste

Arbeite die Checkliste durch, um die zuvor beschriebenen Einstellungen zum Schnelleinstieg zu prüfen. Diese Kontrolle hilft dir, die korrekte Funktionsweise deines Systems sicherzustellen.

[%interactive]

* [ ] Hast du die <<#100, Grundeinstellungen>> für die Auftragsabwicklung vorgenommen?
* [ ] Hast du die <<#200, Dokumentenvorlagen>> für die Auftragsdokumente eingerichtet?
* [ ] Hast du die <<#300, Stornobelege eingerichtet?>>
* [ ]

== Mehr zum Thema *Auftragsabwicklung*

<<auftragsabwicklung/auftraege/grundeinstellungen#, Grundeinstellungen für Aufträge>>
<<auftragsabwicklung/auftraege/auftraege-verwalten#, Auftragstypen>>
<<auftragsabwicklung/auftrage/auftraege-verwalten#200, Manuelle Auftragsanlage>>
<<auftragsabwicklung/auftraege/auftraege-verwalten#1200, Auftragsstatus>>
<<auftragsabwicklung/auftraege/auftragsdokumente#, Auftragsdokumente>>
