= Automatismen
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

////
Früher Kapitel "Automatismen"

TO DO:

- Kapitel "Aufträge verwalten" neu schreiben und irgendwie sinnvoll machen --> wird auf Seite zu Auftragsabwicklung platziert.
- Ereignisaktionen aus dem Dokument "sytemeinrichtungsfragebogen" übernehmen und beschreiben
- Aktionsmanager aus dem Dokument "sytemeinrichtungsfragebogen" übernehmen und beschreiben
- Beispiele für Ereignisaktionen irgendwo anders platzieren
- auf Aktionsmanager nur verlinken (wenn du irgendwas zeitgesteuert machen möchtest, nutze den AM)
- Checkliste prüfen: Gehören alle Punkte zu diesem Thema?

////


In diesem Kapitel finden Sie Erläuterungen zu den Einstellungen, die Sie in plentymarkets zum Einrichten von Automatismen vornehmen sollten, bevor Sie mit dem System produktiv arbeiten. Das System erledigt einige Aufgaben dann automatisch im Hintergrund.

Ihnen stehen vier Möglichkeiten der Automatisierung von Arbeitsschritten in plentymarkets zur Verfügung:

* das Einrichten von E-Mail-Vorlagen, auf deren Basis plentymarkets später automatisch E-Mails an Ihre Kunden versendet.
* das Einrichten von Ereignisaktionen, bei denen bestimmte Ereignisse im Webshop automatisch bestimmte Aktionen auslösen.
* das Einrichten des Aktionsmanagers, über den Sie Ereignisse, die wiederholt und regelmäßig stattfinden sollen, automatisch zu bestimmten Uhrzeiten ausführen lassen.
* das Einrichten von Prozessen. Dieses Menü können Sie nur nutzen, wenn Sie das Tool plentyBase installiert haben, und richtet sich an fortgeschrittene plentymarkets Nutzer. Daher werden Prozesse im Schnelleinstieg nicht näher beschrieben.

[#770]
=== E-Mails automatisch versenden

Im Kapitel <<#10, Basiseinstellungen>> wurde beschrieben, wie Sie E-Mail-Vorlagen erstellen und vorhandene Vorlagen anpassen. Nun bleibt die Frage, wie plentymarkets diese E-Mail-Vorlagen automatisch verschickt.

Im Menü <<crm/e-mails-versenden#2300, System » Mandant » Mandant wählen » E-Mail » Automatischer Versand>> können Sie wählen, in welchen Fällen eine bestimmte E-Mail-Vorlage verschickt werden soll. Damit die bereits bekannte E-Mail-Vorlage *Eingangsbestätigung Webshop-Bestellung* automatisch versendet wird, wenn eine Bestellung über Ihren Webshop eingegangen ist, wählen Sie diese Vorlage in der Zeile *Auftragsbestätigung nach der Kaufabwicklung*. Sie können in diesem Menü weitere spezifische Auftragsbestätigungen für Bestellungen, die z.B. über eBay, Amazon und andere Marktplätze generiert wurden, aktivieren. Außerdem können Sie hier eine E-Mail-Vorlage wählen, die dem Kunden auf Anfrage ein neues Passwort sendet und eine Bestätigung nach der Anmeldung zum Newsletter versendet. Mit *Erinnerung bei Kaufabbruch* und *Kundenregistrierung* stehen weitere Standardereignisse zur Auswahl, die Sie auf Wunsch mit einer E-Mail bedienen können.

Natürlich sollten Sie hier nur solche E-Mail-Vorlagen wählen, die Sie bearbeitet und mit Ihren eigenen Daten ergänzt haben, ansonsten belassen Sie die Voreinstellung *kein Versand*.

[#780]
=== Automatismen mittels Ereignisaktionen einrichten

Das Tagesgeschäft eines Webshops ist von vielen Routineaufgaben geprägt. Die Bearbeitung der eingegangenen Aufträge ist ein komplexer Vorgang, der ein systematisches Vorgehen erfordert. Darüber hinaus möchten Ihre Kunden nach der Auftragsbestätigung noch weitere Informationen über den Status ihrer Bestellung per E-Mail erhalten.

plentymarkets bietet Ihnen im Menü <<basics/automatisierung/ereignisaktionen#, System » Aufträge » Ereignisse>> hierfür eine wirkungsvolle Möglichkeit, da Sie viele dieser Routineaufgaben automatisch ausführen lassen und Ihren Webshop damit äußerst effizient führen können.

Die Aktivierung einer Ereignisaktion gliedert sich in zwei Schritte: Zuerst konfigurieren Sie über verschiedene Filteroptionen ein Ereignis. Danach legen Sie fest, welche Aktionen vom System in diesem Fall auszuführen sind. Immer wenn dieses Ereignis in Zukunft eintritt, werden die gespeicherten Aktionen automatisch ausgeführt.

Im Folgenden finden Sie beispielhaft für die vielfältigen Möglichkeiten in plentymarkets vier Ereignisaktionen, die sich in der Praxis vieler Webshops bewährt haben.


////
die ereignisaktionen aus dem dokument "sytemeinrichtungsfragebogen" übernehmen und beschreiben.
////



////

diese Beispiele auf Best-Practice-Seite für Ereignisaktionen verschieben


[#790]
==== Beispiel 1: Rechnung automatisch versenden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, damit der Kunde seine Rechnung im PDF-Format per E-Mail erhält, sobald diese im System erzeugt wurde.

[IMPORTANT]
.Haben Sie die Dokumentvorlage erstellt?
====
Achten Sie darauf, dass Sie für Ihr Rechnungsdokument eine Dokumentvorlage erstellt haben, die u.a. Ihre Bankverbindung enthält.
====

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das *Ereignis* gemäß <<ereignisaktion-rechnung-automatisch-versenden>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<ereignisaktion-rechnung-automatisch-versenden>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-rechnung-automatisch-versenden]]
.Ereignisaktion zum automatischen E-Mail-Versand der Rechnung
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Dokumente: Rechnung generiert*
|

|*Filter*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Aktion*
|*Kunde &gt; E-Mail versenden*
|E-Mail-Vorlage; Empfänger
|====

[TIP]
.E-Mail-Vorlage und Empfänger wählen
====
Wählen Sie im oberen Auswahlfeld die E-Mail-Vorlage und im unteren Auswahlfeld den Empfänger der E-Mail. Wählen Sie danach ggf. weitere E-Mail-Vorlagen und Empfänger. Wird *Kunde* als Empfänger eingestellt, erhalten alle Kunden, die den Filterkriterien entsprechen, die E-Mail. Wird *Lager* eingestellt, erhält die Kontaktperson für das Lager die E-Mail. Wird ein bestimmter Benutzer eingestellt, erhält der eingestellte Benutzer Ihres plentymarkets Systems die E-Mail.
====

[#800]
==== Beispiel 2: Bestätigung des Eingangs einer Teilzahlung automatisch versenden

Wer bereits erste Erfahrungen im E-Business gesammelt hat, kennt das folgende Problem: Statt den korrekten Betrag zu überweisen, hat der Kunde versehentlich einen zu geringen Betrag gezahlt. Man muss den Kunden dann darauf hinweisen, den Sachverhalt erklären und den zu zahlenden Restbetrag nachfordern. In plentymarkets haben Sie die Möglichkeit, solche Fälle mit einer <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ohne aufwändige Zusatzarbeit automatisiert zu bearbeiten.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das *Ereignis* gemäß <<ereignisaktion-bestaetigung-teilzahlung-automatisch-versenden>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<ereignisaktion-bestaetigung-teilzahlung-automatisch-versenden>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-bestaetigung-teilzahlung-automatisch-versenden]]
.Ereignisaktion zum automatischen E-Mail-Versand der Vorlage Teilzahlung erhalten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Zahlung: Teilzahlung*
|

|*Filter*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Aktion*
|*Kunde &gt; E-Mail versenden*
|E-Mail-Vorlage; Empfänger
|====

[TIP]
.E-Mail-Vorlage und Empfänger wählen
====
Wählen Sie im oberen Auswahlfeld die E-Mail-Vorlage und im unteren Auswahlfeld den Empfänger der E-Mail. Wählen Sie danach ggf. weitere E-Mail-Vorlagen und Empfänger. Wird *Kunde* als Empfänger eingestellt, erhalten alle Kunden, die den Filterkriterien entsprechen, die E-Mail. Wird *Lager* eingestellt, erhält die Kontaktperson für das Lager die E-Mail. Wird ein bestimmter Benutzer eingestellt, erhält der eingestellte Benutzer Ihres plentymarkets Systems die E-Mail.
====

[TIP]
.Abgleich erfolgt automatisch
====
Wenn Zahlungseingänge verbucht werden, vergleicht Ihr plentymarkets System den gezahlten mit dem geforderten Betrag und erkennt das Ereignis *Teilzahlung* automatisch.
====

[#810]
==== Beispiel 3: Bestätigung des vollständigen Zahlungseingangs für Vorkassezahlung automatisch versenden

Mit der *Zahlung per Vorkasse* gibt Ihnen ein neuer Kunde immer einen Vertrauensvorschuss und geht zumindest theoretisch ein gewisses Risiko ein. Daher ist es verständlich, dass Kunden bei dieser Zahlungsart umso ungeduldiger auf ein Feedback von Ihnen warten. Automatisieren Sie diesen Kundenservice am besten mit einer weiteren <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das *Ereignis* gemäß <<ereignisaktion-bestaetigung-zahlungseingang-automatisch-versenden>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<ereignisaktion-bestaetigung-zahlungseingang-automatisch-versenden>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-bestaetigung-zahlungseingang-automatisch-versenden]]
.Ereignisaktion zum automatischen E-Mail-Versand der Vorlage Zahlungseingang vollständig
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Zahlung: Vollständig*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*Zahlung per Vorkasse*

|*Aktion*
|*Kunde &gt; E-Mail versenden*
|E-Mail-Vorlage; Empfänger
|====

[TIP]
.E-Mail-Vorlage und Empfänger wählen
====
Wählen Sie im oberen Auswahlfeld die E-Mail-Vorlage und im unteren Auswahlfeld den Empfänger der E-Mail. Wählen Sie danach ggf. weitere E-Mail-Vorlagen und Empfänger. Wird *Kunde* als Empfänger eingestellt, erhalten alle Kunden, die den Filterkriterien entsprechen, die E-Mail. Wird *Lager* eingestellt, erhält die Kontaktperson für das Lager die E-Mail. Wird ein bestimmter Benutzer eingestellt, erhält der eingestellte Benutzer Ihres plentymarkets Systems die E-Mail.
====

[#820]
==== Beispiel 4: Versand nach Import der Paketnummer automatisch bestätigen

Die tägliche Auftragsbearbeitung in einem Webshop wird im Regelfall durch den Versand der Pakete abgeschlossen. Die dabei erzeugten Paketnummern sollten nun unbedingt wieder an plentymarkets zurückgemeldet werden – nicht zuletzt, da Sie damit per Ereignisaktion weitere notwendige Schritte zum Abschluss der Auftragsbearbeitung erledigen können.

[TIP]
.Tipp: Paketnummernimport automatisieren
====
Für den Import der Paketnummern in plentymarkets stehen Ihnen verschiedene Möglichkeiten zur Verfügung: Die manuelle Eingabe in ein Formular können Sie durch den Einsatz eines USB-Scanners erheblich beschleunigen. Bei größeren Versandmengen empfiehlt es sich, den Rückimport dieser Angaben aus der Versandsoftware in das System zu automatisieren.
====

Die folgende <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> wird beim Import der Paketnummer dem Kunden eine Versandbestätigung senden, den Status der Bestellung auf 7 setzen und zusätzlich den Warenausgang im Lager buchen, damit die physischen Lagerbestände aktualisiert werden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das *Ereignis* gemäß <<ereignisaktion-versandbestaetigung-automatisch-versenden>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<ereignisaktion-versandbestaetigung-automatisch-versenden>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-versandbestaetigung-automatisch-versenden]]
.Ereignisaktion zum automatischen E-Mail-Versand der Vorlage Versandbestätigung zur Bestellung
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Paketnummer*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*Zahlung per Vorkasse*

|*Aktion 1*
|*Auftrag &gt; Status ändern*
|*[7] Warenausgang gebucht*

|*Aktion 2*
|*Kunde &gt; E-Mail versenden*
|E-Mail-Vorlage; Empfänger

|*Aktion 3*
|*Auftrag &gt; Warenausgang buchen*
|
|====

[TIP]
.E-Mail-Vorlage und Empfänger wählen
====
Wählen Sie im oberen Auswahlfeld die E-Mail-Vorlage und im unteren Auswahlfeld den Empfänger der E-Mail. Wählen Sie danach ggf. weitere E-Mail-Vorlagen und Empfänger. Wird *Kunde* als Empfänger eingestellt, erhalten alle Kunden, die den Filterkriterien entsprechen, die E-Mail. Wird *Lager* eingestellt, erhält die Kontaktperson für das Lager die E-Mail. Wird ein bestimmter Benutzer eingestellt, erhält der eingestellte Benutzer Ihres plentymarkets Systems die E-Mail.
====

Fast alle Versanddienstleister bieten ihren Kunden mittlerweile die Sendungsverfolgung per Internet an. Sie haben bei der Einrichtung Ihrer Versanddienstleister bereits eine Tracking-URL gespeichert. Mit der Eingabe der Paketnummer verfügt Ihr plentymarkets System nun über alle nötigen Informationen, um Ihrem Kunden eine Tracking-URL zur Verfolgung seines Paketes zu senden. Nutzen Sie diese Option und überzeugen Sie sich davon, dass die E-Mail-Vorlage Ihrer Versandbestätigung die Variable *$TrackingURL* enthält. Testen Sie dann bei den ersten Aufträgen, ob die Tracking-URLs korrekt verarbeitet werden und dem Kunden die entsprechenden Informationen anzeigen.

[TIP]
.Tipp: Markierungen verwenden
====
Zur besseren Übersicht im Auftragsordner empfehlen wir Ihnen, Markierungen zu verwenden. Die Bedeutung der Markierungen müssen Sie selbst bestimmen und dann durchgängig verwenden. Sie könnten beispielsweise teilbezahlte Aufträge über die aktuelle Ereignisaktion mit der *Markierung 5* auszeichnen und würden dann später in der Auftragsübersicht diesen Status sofort wieder anhand der Markierung erkennen. Markierungen können manuell oder über eine Aktion des Aktionstyps *Markierung ändern* per Ereignisaktion gesetzt und verändert werden. Markierte Aufträge sind in den Ereignisaktionen und im übrigen System anhand dieser Markierungen auch selektierbar (Filteroptionen).
====
////


[#830]
=== Automatismen mittels Aktionsmanager einrichten

Mit dem Aktionsmanager kann plentymarkets automatisch bestimmte Aktionen für Sie ausführen. Wir möchten Ihnen die Funktionsweise des Aktionsmanagers anhand zweier Praxisbeispiele erläutern. Dazu beschreiben wir im ersten Beispiel, wie Sie das automatische Abgeben von eBay-Bewertungen für ein verknüpftes eBay-Konto einrichten und im zweiten Beispiel, wie Sie das automatische Mahnwesen konfigurieren.


////
Aktionsmangager empfehlungen aus dem dokument systemeinrichtungsfragebogen übernehmen
////

////

auf best-practice-seite umziehen

[#840]
==== Beispiel 1: eBay-Bewertung automatisch abgeben

Das Abgeben von Bewertungen bei eBay ist eine zeitaufwändige Routineaufgabe. Genau das soll unsere erste Aktion jetzt automatisieren: Immer, wenn Ihre Kunden eine positive Bewertung für Sie abgegeben haben, soll via <<basics/automatisierung/aktionsmanager#, Aktionsmanager>> eine ebenfalls positive Bewertung des eBay-Kunden erfolgen.

[.instruction]
Automatische eBay-Bewertung per Aktionsmanager abgeben:

. Öffnen Sie das Menü *System » Aufträge » Aktionen*.
. Wechseln Sie in das Tab *Neue Aktion*.
. Setzen Sie ein Häkchen bei *Aktiv*, um die Aktion zu aktivieren.
. Wählen Sie bei der Einstellung *Täglich ausführen um* eine Uhrzeit.
. Geben Sie einen *Namen* für die Aktion ein.
. Wechseln Sie in das Tab *Filter*.
. Wählen Sie bei bei der Einstellung *eBay* die Option *positive Bewertung erhalten*. +
→ Alle anderen Einstellungsmöglichkeiten werden ausgegraut.
. Wechseln Sie in das Tab *Aktion*.
. Wählen Sie bei der Einstellung *eBay* die Option *positive Bewertung abgeben*.
. *Speichern* Sie die Einstellungen.

Das Einrichten der Aktion ist damit eigentlich abgeschlossen. Im vorliegenden Fall ist aber noch ein weiterer Schritt erforderlich, da das Abgeben von Bewertungen auch einen Bewertungstext erfordert. Die Texte geben Sie im Menü <<omni-channel/multi-channel/ebay-einrichten#65, System » Märkte » eBay » Einstellungen » Tab: Kontoeinstellungen>> ein. plentymarkets wählt nach dem Zufallsprinzip für jede Bewertung einen Text, um Ihre Bewertungen abwechslungsreicher zu gestalten.

[.instruction]
Bewertungstexte für eBay eingeben:

. Öffnen Sie das Menü *System » Märkte » eBay » Einstellungen*.
. Wechseln Sie in das Tab *Kontoeinstellungen*.
. Geben Sie im Bereich *Automatische Bewertungen* bis zu vier Bewertungstexte ein.
. *Speichern* Sie die Einstellungen.
////


[#850]
==== Zahlungserinnerung automatisch versenden

Leider kommt es in der Praxis immer wieder vor, dass Kunden Waren z.B. auf Rechnung bestellen, dann aber nicht bezahlen. In diesem Fall sollten Sie den Kunden per E-Mail eine Erinnerung senden. Diese Aufgabe kann der <<basics/automatisierung/aktionsmanager#, Aktionsmanager>> automatisch für Sie übernehmen.

[.instruction]
Automatischen E-Mail-Versand der Vorlage Zahlungserinnerung einstellen:

. Öffnen Sie das Menü *System » Aufträge » Aktionen*.
. Wechseln Sie in das Tab *Neue Aktion*. +
→ Eine neue Aktion wird erstellt. *_Hinweis:_* Die Aktion ist noch nicht aktiv.
. Wählen Sie im Tab *Filter* unter *Mahnstufe* eine Option, z.B. *Stufe 0*.
. Wählen Sie im Tab *Aktion* die E-Mail-Vorlage *Zahlungserinnerung*.
. Nehmen Sie ggf. weitere Einstellungen vor. //// welche?
. Setzen Sie im Tab *Einstellungen* ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen. +
→ Die Aktion ist aktiv.

////
[[aktionsmanager-zahlungserinnerung-automatisch-versenden]]
.Aktionsmanager; Einstellungen für automatischen E-Mail-Versand der Vorlage Zahlungserinnerung
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Einstellungen

|*Aktiv*
|Häkchen setzen, um die Aktion zu aktivieren.

|*Täglich ausführen um*
|Uhrzeit wählen, zu der die Aktion ausgeführt werden soll.

|*Name*
|Name für die Aktion eingeben. +
Standardeintrag: Datum und Uhrzeit der Erstellung, wird dem Kunden nicht angezeigt.

2+|Filter

|*Status*
|*[3] Warten auf Zahlung* wählen.

|*Letzter Statuswechsel*
|*Tage eingeben* wählen und z.B. 8 eingeben, d.h. letzter Statuswechsel vor 8 Tagen. +
Diese Angabe ist besonders für Erinnerungen oder Mahnung wichtig, um sicherzustellen, dass nur Aufträge in die Aktion eingeschlossen sind, bei denen der Zeitraum vergangen ist. +
*Wichtig*: Dieser Filter greift nur für Vorgänge, bei denen ein Status eingegeben ist, d.h. somit nicht bei manueller Buchung eines Zahlungseingangs, bei dem kein Status eingegeben ist.

|*Zahlungseingang*
|*OFFEN* wählen. Berücksichtigt nur Aufträge, die noch nicht bezahlt oder bei denen noch keine Zahlungen im System verbucht sind.

2+|Aktion

|*Versende E-Mail-Vorlage*
|*Zahlungserinnerung* wählen.

|*Ändere Mahnstufe*
|Mit der ersten E-Mail den Kunden an die vergessene Zahlung erinnern. Die Mahnstufe sollte dennoch auf *Stufe 1* erhöht werden, um später unbezahlte, aber bereits gemahnte Aufträge zusätzlich über diese Mahnstufe erkennen zu können.
|====
////

Sollte Ihr Kunde trotz der Zahlungserinnerung nicht bezahlen, erstellen Sie eine neue, schärfer formulierte E-Mail-Vorlage, z.B. eine Zahlungsaufforderung. Erstellen Sie eine neue Aktion für die zweite Mahnstufe und versenden Sie die Vorlage. Filtern Sie wieder alle unbezahlten Rechnungen über *Status 3*. Wählen Sie unter *Letzter Statuswechsel* aber einen längeren Zeitraum, z.B. 20 Tage.

Zuletzt bleibt Ihnen bei offenen Rechnungen nur noch die Übergabe des Auftrages an einen <<auftragsabwicklung/payment#, Inkassodienstleister>>. Auch diese Aufgabe können Sie mit plentymarkets einfach und bequem automatisieren.

[#860]
=== Checkliste

Die nachfolgende Checkliste dient zur Prüfung der Einstellungen. Arbeiten Sie die Checkliste durch, nachdem Sie die zuvor beschriebenen Einstellungen zum Schnelleinstieg vorgenommen haben. Diese Kontrolle gewährleistet die korrekte Funktionsweise Ihres plentymarkets Systems.

[%interactive]
* [ ] Konnten Sie die grundlegende Statuslogik bei der <<#760, Auftragsbearbeitung>> nachvollziehen?
* [ ] Haben Sie Ihre <<#770, E-Mail-Vorlagen>> bearbeitet, die Widerrufsbelehrung eingefügt sowie Ihre Bankverbindung und Kontaktdaten korrekt eingegeben?
* [ ] Wurde in der *Versandbestätigung zur Bestellung* die Tracking-URL korrekt eingegeben?
* [ ] Haben Sie wichtige Ereignisse mithilfe von <<#780, Ereignisaktionen>> oder des <<#830, Aktionsmanagers>> automatisiert?
