= Basiseinstellungen vornehmen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Stammdaten, Bankdaten, E-Mail, E-Mails, Emails, Zugangsdaten, E-Mail-Vorlagen, Vorlage, Vorlagen, Template-Variable
:description: Erfahre in diesem Teil des Schnelleinstiegs, welche Basiseinstellungen du vornehmen musst.
:position: 30

IMPORTANT: Hast du schon Popups erlaubt, ein Lesezeichen für dein Backend-Login gesetzt und die Systemvoraussetzungen geprüft? Noch nicht? Dann geht's hier zurück zum Thema <<schnelleinstieg/schnelleinstieg-schnell-durchstarten#, Schnell durchstarten>>.

In diesem Teil des Schnelleinstiegs findest du Erläuterungen zu allgemeinen Einstellungen wie dem Speichern von Stammdaten und Bankdaten sowie zum Einrichten der E-Mail-Einstellungen und E-Mail-Vorlagen. Außerdem erfährst du auf dieser Seite, wie du eine Domain und ein SSL-Zertifikat für deinen Webshop bestellst.

[#100]

== Stammdaten speichern

Im Menü *System » Einstellungen » Stammdaten* speicherst du zentral die Stammdaten deines Unternehmens wie z.B. die Kontaktdaten, Adresse und Umsatzsteuer-ID.

[.instruction]
Stammdaten speichern:

. Öffne das Menü *System » Einstellungen » Stammdaten*.
. Gib deine Daten ein.
. *Speichere* die Einstellungen. +
→ Die Stammdaten werden gespeichert.

[IMPORTANT]
.Vertragsdaten ändern
====
Eine Änderung der Stammdaten in diesem Menü ändert nicht die Kundenstammdaten deines plentymarkets Vertrages z.B. für die Rechnungsstellung. Vertragsdaten passt du im Menü *Start » Service-Center* an.
====

[#200]
== Bankdaten speichern

Ebenso wie die Stammdaten speicherst du auch deine Bankdaten an einer zentralen Stelle in deinem plentymarkets System. Änderungen dieser Daten wirken sich auf das gesamte System aus.

Deine Bankdaten können über sogenannte Template-Variablen in E-Mail-Vorlagen ausgegeben werden. Das bedeutet, dass plentymarkets in den E-Mails selbst  die Variablen durch den jeweiligen Inhalt ersetzt. Die Variable *$BankOwner* wird so z.B. durch den Namen des Kontoinhabers ersetzt und *$BankAccount* setzt die Kontonummer ein.

[.instruction]
Bankdaten speichern:

. Öffne das Menü *System » Einstellungen » Bank*.
. Gib deine Bankdaten ein. Beachte dazu die Erläuterungen in <<tabelle-bankdaten-speichern>>.
. *Speichere* die Einstellungen.

[[tabelle-bankdaten-speichern]]
.Bankdaten speichern
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Kontoinhaber*
|Vorname und Name des Kontoinhabers eingeben. +
Template-Variable: *$BankOwner*

|*Konto-Nr.*
|Kontonummer eingeben. +
Template-Variable: *$BankAccount*

|*BLZ*
|Bankleitzahl eingeben. +
Template-Variable: *$BankCode*

|*Bank*
|Name der Bank eingeben. +
Template-Variable *$BankName*

|*IBAN*
|Internationale Bankleitzahl eingeben. +
Template-Variable *$BankIban*
|====

Welche Template-Variablen dir für die E-Mail-Vorlagen zur Verfügung stehen, erfährst du weiter unten auf dieser Seite im Kapitel <<schnelleinstieg/basiseinstellungen#500, E-Mail-Vorlagen einrichten>>.

[#300]
== E-Mail-Signatur speichern

Speichere nun die Signatur deines Webshops, die dann in den E-Mail-Vorlagen automatisch ausgegeben wird, wenn du anschließend am Ende der E-Mail-Vorlagen die Template-Variable *$SignatureText* einfügst. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
E-Mail-Signatur speichern:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Signatur*.
. Gib den Text deiner Signatur ein. +
→ *_Wichtig:_* Beachte die gesetzlichen Vorgaben zum Inhalt einer E-Mail-Signatur. Lass dich im Zweifelsfall von einem kundigen Fachanwalt beraten.
. *Speichere* die Einstellungen.

[#400]
== E-Mail-Zugangsdaten eingeben

Im Folgenden erfährst du, welche Einstellungen du vornehmen musst, damit dein plentymarkets System später bei Eintritt eines definierten Ereignisses automatisch E-Mails wie Auftrags- und Versandbestätigungen erzeugt und an deine Kunden versendet.

Beachte, dass es unter Umständen möglich sein kann, dass du dir eine Freigabe bei deinem E-Mail-Provider einholen musst, damit plentymarkets die E-Mails versenden darf.

[TIP]
.Testmodus sendet E-Mails nur an deine E-Mail-Adresse
====
Es gibt einen Testmodus, der standardmäßig aktiviert ist. Im Testmodus werden alle E-Mails nur an die von dir eingegebene E-Mail-Adresse gesendet. So kannst du alle Einstellungen und Inhalte testen, bevor du live mit dem E-Mail-Versand arbeitest.
====

Damit plentymarkets über dein E-Mail-Konto E-Mails für dich versenden kann, musst du die Zugangsdaten deines E-Mail-Programms in plentymarkets eingeben.

[.instruction]
E-Mail-Zugangsdaten eingeben:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Zugangsdaten*.
. Nimm die Einstellungen gemäß <<tabelle-e-mail-zugangsdaten-eingeben>> vor.
. *Speichere* die Einstellungen.

[[tabelle-e-mail-zugangsdaten-eingeben]]
.E-Mail-Zugangsdaten eingeben
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Testmodus*
|*aktiv* (Standardeinstellung) = Während der Testphase einstellen, damit alle E-Mails nur an deine Adresse gesendet werden. +
*inaktiv* = Nach Ende der Testphase einstellen, damit deine Kunden die E-Mails erhalten.

|*Name des Absenders*
|Deinen Namen und/oder den Namen deines Webshops eingeben, wie er beim Empfänger angezeigt werden soll.

|*E-Mail-Adresse*
|E-Mail-Adresse eingeben, wie sie auch in deinem E-Mail-Programm steht, z.B. info@myshop.de.

|*Postausgangsserver / SMTP-Server*
|Den Postausgangsserver erfährst du von deinem Provider (meist smtp.domain.de oder mail.domain.de).

|*Benutzername*
|Benutzername zu der E-Mail-Adresse eingeben.

|*Passwort*
|Passwort zu dem Benutzernamen und der E-Mail-Adresse eingeben.

|*Port (Standard-Port: 25)*
|Der Wert *25* ist für fast alle Provider mit der Verschlüsselung *TLS* korrekt. Andernfalls musst du den korrekten Port bei deinem Provider erfragen. +
*_mailbox.org:_* Für Postfächer bei mailbox.org den Port *465* eingeben und unter *Verschlüsselung* die Einstellung *SSL* wählen.

|*Verschlüsselung*
|*SSL*, *TLS* oder *keine Verschlüsselung* (Standardeinstellung) wählen. +
*_mailbox.org:_* Für Postfächer bei mailbox.org den Port *465* eingeben und unter *Verschlüsselung* die Einstellung *SSL* wählen.
|====

[TIP]
.E-Mail-Infodienst einrichten
====
Sobald du den Testmodus deaktiviert hast, ist es gerade in der Anfangsphase sinnvoll, auf die durch das System versendeten E-Mails stärker ein Auge zu haben. Nutze dafür den Infodienst. Mit dieser Funktion sendest du eine Blindkopie (BCC) aller ausgehenden E-Mails an eine Adresse deiner Wahl.

[.instruction]
Infodienst einrichten:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Infodienst*.
. Wähle *JA* aus der ersten Dropdown-Liste, um den Infodienst für die in der nächsten Zeile eingegebene E-Mail-Adresse zu aktivieren.
. Gib die E-Mail-Adresse ein, an die eine Blindkopie gesendet werden soll.
. *Speichere* die Einstellungen.

Um den Infodienst wieder zu beenden, wähle *NEIN* aus den beiden Dropdown-Listen und speichere die Einstellungen.
====

[#500]
== E-Mail-Vorlagen einrichten

plentymarkets erzeugt alle E-Mails auf Basis von Vorlagen. <<tabelle-e-mail-vorlagen>> listet die E-Mail-Vorlagen auf, deren Einrichtung wir dir für den Anfang empfehlen.

Du kannst alle E-Mail-Vorlagen an deine Erfordernisse anpassen. Wie du dazu vorgehst, haben wir für dich am Beispiel der E-Mail-Vorlage *Webshop: Eingangsbestätigung Bestellung* weiter unten auf dieser Seite im Kapitel <<schnelleinstieg/basiseinstellungen#600, Beispiel: E-Mail-Vorlage anpassen>> beschrieben.

[[tabelle-e-mail-vorlagen]]
.Bereits vorkonfigurierte E-Mail-Vorlagen
[cols="1,3"]
|====
|E-Mail-Vorlage |Erläuterung

|*Auftrag: Rechnung PDF-Anhang*
|Sendet die Rechnung als Dateianhang an den Kunden. +
*_Wichtig:_* Eine Rechnungsvorlage für den Standort *Deutschland* ist bereits vorkonfiguriert. Du kannst die Vorlage nach Bedarf im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* anpassen. Wenn eine Rechnung für den Auftrag existiert und du eine Ereignisaktion eingerichtet hast, wird die Rechnung automatisch an den Kunden versendet, da in der Vorlage *Auftrag: Rechnung PDF-Anhang* der PDF-Anhang *Rechnung* bereits standardmäßig gewählt ist. +
 Weitere Informationen dazu findest du auf der Schnelleinstiegsseite <<schnelleinstieg/automatisierung#, Automatisierung>>.

|*Auftrag: Versandbestätigung*
|Wird bei Versand der Ware verschickt.

|*Webshop: Eingangsbestätigung Bestellung*
|Benachrichtigung an den Kunden, dass seine Bestellung eingegangen ist. +
*_Wichtig:_* In dieser E-Mail-Vorlage solltest du aus rechtlichen Gründen eine Widerrufsbelehrung sowie die AGB einfügen. Von großer Bedeutung in dieser E-Mail-Vorlage sind alle Formulierungen, die das vertragliche Verhältnis mit dem Kunden betreffen. Deine Texte solltest du daher von einem kundigen Fachanwalt prüfen lassen. +
Den Text für die Widerrufsbelehrung und die AGB speicherst du im Menü *System » Mandant » Mandant wählen » Webshop » Rechtliches*. Über die Template-Variablen *$CancellationRightsText* und *$GeneralTermsConditionsText* werden das Widerrufsrecht und die AGB dann automatisch in der E-Mail ausgegeben.
|====

[TIP]
====
Es gibt zahlreiche weitere E-Mail-Vorlagen, die bereits in deinem plentymarkets System vorhanden sind. Diese musst du ggf. anpassen und mit einem Ereignis im Menü *System » Mandant » Mandant wählen » E-Mail » Automatischer Versand* verknüpfen oder eine Ereignisaktion einrichten. Weitere Informationen findest du auf der Schnelleinstiegsseite <<schnelleinstieg/automatisierung#, Automatisierung>>.
====

////
[WARNING]
.Bankverbindung und Kontaktdaten nicht vergessen
====
Achte unbedingt darauf, dass in allen E-Mail-Vorlagen deine Bankverbindung eingegeben ist und dass am Ende der E-Mail statt des Mustertextes deine Kontaktdaten korrekt und vollständig eingegeben sind. Du kannst dafür <<schnelleinstieg/basiseinstellungen#700, Template-Variablen>> verwenden.
====
////

[#600]
=== Beispiel: E-Mail-Vorlage anpassen

Anhand des Beispiels der E-Mail-Vorlage *Webshop: Eingangsbestätigung Bestellung* beschreiben wir im Folgenden, wie du eine E-Mail-Vorlage an deine Erfordernisse anpasst.

[.instruction]
E-Mail-Vorlage anpassen:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Klicke bei *Allgemeine E-Mail-Vorlagen* auf *Webshop: Eingangsbestätigung Bestellung*. +
→ Das Tab *Einstellungen* öffnet sich.
. Ändere ggf. die Einstellungen. Beachte dazu die Erläuterungen in <<tabelle-e-mail-vorlagen-einrichten>>.
. Wechsele ins Tab *E-Mail-Nachricht » Tab: Inhalt » Tab: Reiner Text*. +
→ Der Standardtext öffnet sich.
. Ändere ggf. den Text.
. Füge die Texte für das Widerrufsrecht und die AGB im Menü *System » Mandant » Mandant wählen » Webshop » Rechtliches* ein, damit die im Standardtext bereits enthaltenen Template-Variablen *$CancellationRightsText* und *$GeneralTermsConditionText* in der versendeten E-Mail-Vorlage mit deinen Texten für die AGB und das Widerrufsrecht korrekt ausgegeben werden.
. Ersetze die Musterkontaktdaten am Ende der Vorlage durch deine Kontaktdaten. +
→ Du kannst dafür die Template-Variable *$SignatureText* verwenden und die Daten wie in Kapitel <<schnelleinstieg/schnelleinstieg-basiseinstellungen#300, E-Mail-Signatur speichern>> beschrieben einsetzen.
. *Speichere* die Einstellungen.

[[tabelle-e-mail-vorlagen-einrichten]]
.E-Mail-Vorlagen einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Kopfzeile

|*Speichern*
|Speichert die E-Mail-Vorlage.

|*Template-Variablen -und Funktionen*
|Öffnet alle in plentymarkets verfügbaren Template-Variablen und Template-Funktionen, die du in deinen E-Mail-Vorlagen verwenden kannst.

2+|Tab: Einstellungen

|*Eigner*
|Standardmäßig ist die Einstellung *Alle* gewählt. Das bedeutet, dass alle Benutzer Zugriff auf diese Vorlage haben.

|*Name*
|Name der E-Mail-Vorlage, die zur internen Unterscheidung verwendet wird. Dieser Name wird dem Empfänger nicht angezeigt. Du kannst diesen Namen anpassen.

|*Inhalt*
|*Nur reiner Text* (Standardeinstellung) oder *Nur HTML-formatierter Text* wählen.

|*Template-Typ*
|*Alle* (Grundeinstellung) wählen, wenn die E-Mail-Vorlage für alle Bereiche verwendet werden soll, oder den Bereich in plentymarkets aus der Dropdown-Liste wählen, für den diese E-Mail-Vorlage ausschließlich zur Verfügung stehen soll.

|*PDF-Anhang*
|Standardmäßig ist die Einstellung *Kein PDF-Anhang* gewählt. +
*_Hinweis:_* Wenn du später an eine deiner E-Mails z.B. die Rechnung als PDF-Datei anhängen willst, musst du die Rechnungsvorlage vorab konfigurieren. Außerdem muss eine Rechnung für den Auftrag existieren und am besten hast du eine Ereignisaktion für diese Ereignis eingerichtet.
|*Dokumentenanhang*
|Standardmäßig ist die Einstellung *Kein Dokumentenanhang* gewählt. +
*_Hinweis:_* Wenn du einen Anhang wie z.B. einen Artikelprospekt versenden möchtest, musst du diesen im Menü *CMS » Dokumente* hochladen. In der Dropdown-Liste *Dokumentenanhang* werden nur Dateien angezeigt, die im Menü *CMS » Dokumente* hochgeladen wurden.

|*Antwort an*
|E-Mail-Adresse eingeben, an die die Antworten auf diese E-Mail-Vorlage gesendet werden sollen. +
*_Hinweis:_* Wenn keine E-Mail-Adresse eingegeben wird, werden Antworten auf diese E-Mail-Vorlage an die E-Mail-Adresse, die im Menü *System » Mandant » Mandant wählen » E-Mail » Zugangsdaten* gespeichert ist, versendet.

|*Mandant (Shop)*
|Standardmäßig sind alle Mandanten aktiviert.

2+|Tab: E-Mail-Nachricht

|*Sprache wählen*
|Standardmäßig ist die Sprache *de* gewählt.

|*Betreff*
|Ggf. den Standardtext des Betreffs anpassen. Den Betreff sorgfältig wählen, damit die E-Mail im Postfach des Kunden erkannt und nicht als Spam gefiltert wird. +
*_Hinweis:_* Du kannst in der Betreffzeile auch Template-Variablen einfügen.
|====

Wenn du die E-Mail-Vorlage *Webshop: Eingangsbestätigung Bestellung* nach deinen Erfordernissen angepasst und gespeichert hast, wird diese auch automatisch an deine Kunden versendet, sobald sie in deinem Webshop bestellen, da diese Vorlage im Menü *System » Mandant » Mandant wählen » E-Mail » Automatischer Versand* bereits mit dem Ereignis *Neue Bestellung über den Webshop* verknüpft ist.

[#700]
=== Template-Variablen und Template-Funktionen einfügen

E-Mail-Vorlagen in plentymarkets bestehen immer aus Text sowie Template-Funktionen und Template-Variablen. In den E-Mails selbst ersetzt plentymarkets die Variablen durch den jeweiligen Inhalt. Die Variable *$CustomerFullName* wird so z.B. durch den Kundennamen ersetzt, *$CustomerEmail* setzt die E-Mail-Adresse des Kunden ein, die Variable *$OrderID* setzt die Auftrags-ID ein.

[IMPORTANT]
.Schreibweise der Template-Variablen beachten
====
Da Template-Variablen und Template-Funktionen vorkonfigurierte Systembefehle auslösen, musst du die Schreibweise der Namen genau einhalten. Um Fehlfunktionen durch Schreibfehler zu vermeiden, kopierst du die Variablen und fügst sie an gewünschter Stelle in die E-Mail-Vorlage ein.
====

[.instruction]
Template-Variablen und -Funktionen einfügen:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Öffne die E-Mail-Vorlage, in die du Template-Variablen einfügen möchtest.
. Klicke auf *Template-Variablen und -Funktionen*. +
→ Das Fenster *Template-Variablen und -Funktionen* wird geöffnet.
. Kopiere die Variable, die du in die E-Mail-Vorlage einfügen möchtest.
. Füge die Variable in das Textfeld im Tab *E-Mail-Nachricht » Tab: Inhalt » Tab: Reiner Text* an der gewünschten Stelle ein.
. *Speichere* die Einstellungen.

[TIP]
.Template-Funktion *{%Link_Checkout()%}* einfügen
====
Alle E-Mails an deine Kunden sollten unbedingt die Template-Funktion *{%Link_Checkout()%}* enthalten. Diese Funktion gibt den Link zum Bereich *Mein Konto* deines Webshops aus. Mit einem Klick auf diesen Link können deine Kunden jederzeit ihre Daten aktualisieren, die Auftragshistorie einsehen, weitere Artikel zur Bestellung hinzufügen und den Status der Bestellung verfolgen.
====

[#800]
=== Dateien an E-Mail-Vorlagen anhängen

Du kannst zwei Arten von Dateien an deine E-Mail-Vorlagen anhängen:

* einen PDF-Anhang +
* einen Dokumentenanhang

Was der Unterschied dieser beiden Anhänge ist, wird im Folgenden beschrieben.

Die möglichen Anhänge eines PDF-Anhangs, z.B. Rechnung, sind in deinem plentymarkets System vorgegeben. Diese Dokumente richtest du im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente* ein.

Ein Dokumentenanhang kann z.B. ein Artikelprospekt, eine Anleitung oder eine Fotodatei sein. Du lädst diese Dateien im Menü *CMS » Dokumente* hoch.

[#900]
==== PDF-Anhang erstellen und anhängen

Die Dokumente, die du als PDF-Anhang versenden kannst, werden automatisch von deinem plentymarkets System erzeugt. Ein Beispiel für ein solches Dokument ist die Rechnung.

Das Einrichten erfolgt in drei Schritten:

1. Dokumentenvorlage, z.B. eine Geschäftsbriefvorlage inklusive Logo, erstellen und auf deinem Rechner speichern
2. Dokumenteinstellungen anpassen (im Folgenden detaillierter beschrieben)
3. Dokument mit der E-Mail-Vorlage verknüpfen (im Folgenden detaillierter beschrieben)

[.instruction]
Dokumenteinstellung anpassen:

. Öffne das Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente*.
. Wähle das Dokument, das du bearbeiten möchtest, z.B. *Rechnung*. +
→ Das Dokument *Rechnung* ist bereits voreingestellt. Passe die Rechnungsvorlage ggf. an.
. Wechsele in das Tab *PDF-Vorlage*.
. Klicke auf *Vorlage hinzufügen*.
. Wähle ggf. eine *Zahlungsart*. +
→ Standardmäßig ist die Einstellung *Standard* gewählt.
. Klicke auf *Vorlage auswählen*.
. Öffne die zuvor erstellte PDF-Dokumentvorlage.
. *Speichere* die Einstellungen.
. Klicke auf *Vorschau*, um eine Vorschau des Dokuments anzeigen zu lassen.

[.instruction]
Dokument mit der E-Mail-Vorlage verknüpfen:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Öffne die E-Mail-Vorlage.
. Wähle in der Dropdown-Liste *PDF-Anhang* die Datei, die du als Anhang versenden möchtest.
. *Speichere* die Einstellungen. +
→ Das Dokument wird als Anhang mit versendet.

[#1000]
==== Dokumentenanhang erstellen und anhängen

Alle Dokumente, die du über eine E-Mail-Vorlage als Dokumentenanhang versenden möchtest, müssen vorher im System hochgeladen werden. Ein Beispiel für ein solches Dokument sind die AGB, da dieses Dokument häufig als Anhang der Eingangsbestätigung einer Bestellung versendet wird – vorausgesetzt du hast die AGB nicht über die Template-Variable *$GeneralTermsConditionsText* direkt in der Vorlage eingefügt.

Das Einrichten erfolgt in zwei Schritten. Zunächst lädst du das Dokument im Menü *CMS » Dokumente* hoch. Dann verknüpfst du das Dokument mit einer E-Mail-Vorlage. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Dokument hochladen:

. Öffne das Menü *CMS » Dokumente*.
. Klicke im Tab *Upload* auf *Datei auswählen*.
. Wähle die Datei, die du hochladen möchtest, und klicke auf *Öffnen*.
. Wähle eine der Optionen unter *Berechtigung*. +
→ Mit der Berechtigung legst du fest, ob das Dokument nur für *Mitarbeiter*, nur für *Kunden* oder *öffentlich*, also für alle Besucher des Webshops, verfügbar sein soll.
. Gib ggf. einen *Ordnernamen* ein.
. *Speichere* die Einstellungen.

[.instruction]
Dokument mit einer E-Mail-Vorlage verknüpfen:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Öffne die E-Mail-Vorlage.
. Wähle in der Dropdown-Liste *Dokumentenanhang* die Datei, die du als Anhang versenden möchtest.
. *Speichere* die Einstellungen. +
→ Die Datei wird als Anhang mit versendet.

[#1100]
== Domain bestellen

Der Begriff "Domain" bezeichnet eine Internetadresse in Form eines Namens sowie einer Erweiterung, der Top-Level-Domain, z.B. *.de*. Du kannst den Namen frei wählen. Eine Domain ist einmalig und darf weltweit nicht doppelt vorkommen. Bei der Registrierung der Domain, zum Beispiel bei einem Hosting-Dienstleister, wird daher geprüft, ob eine gewünschte Domain noch nicht vergeben ist.

Gehe wie im Folgenden beschrieben vor, um eine Domain zu bestellen und die Kontaktdaten des Domain-Inhabers zu speichern, das sogenannte Domain Handle. Du erhältst anschließend Informationen über die monatlichen Kosten der Nutzung. Nachdem du die Kontaktdaten eingegeben hast und das plentymarkets System zugeordnet wurde, bestellst du die Domain mit einem Klick auf *Zahlungspflichtig bestellen*.

[.instruction]
Domain bestellen:

. Öffne das Menü *Start » Service-Center*. +
→ Das Service-Center wird in einem neuen Browser-Tab geöffnet.
. Klicke auf das blaue Plus des Systems. +
→ Die verfügbaren Tabs werden eingeblendet.
. Wechsele in das Tab *Domain*.
. Klicke auf *Neue Domain bestellen*.
. Gib den gewünschten Domain-Namen ein.
. Wähle die Top-Level-Domain aus der Dropdown-Liste.
. Klicke auf *Prüfen*. +
→ Das System prüft, ob die Domain verfügbar ist.
. Klappe die Domain-ID auf.
. Klicke auf *Domain-Handle*.
. Gib die Kontaktdaten des Domain-Inhabers ein.
. *Speichere* die Einstellungen.

Wenn du bereits eine Domain bei einem anderen Provider hast und den Provider wechseln möchtest, gehe wie im Kapitel <<basics/arbeiten-mit-plentymarkets/plentymarkets-konto#250, Domain-Umzug durchführen>> auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/plentymarkets-konto#, plentymarkets Konto>> beschrieben vor.

[#1200]
== SSL-Zertifikat bestellen

Ein SSL-Zertifikat dient dazu, deine Website zu verschlüsseln und gewährleistet eine sichere Verbindung zu deinem Webshop. Wenn du ein SSL-Zertifikat verwendest, ist deine Website über _https_ erreichbar.

Wichtig ist, dass die Domain, für die du das SSL-Zertifikat bestellen möchtest, eine im Service-Center aktivierte Hauptdomain ist.

Gehe wie im Folgenden beschrieben vor, um ein kostenpflichtiges SSL-Zertifikat zu bestellen.

[.instruction]
SSL-Zertifikat bestellen:

. Öffne das Menü *System » Mandant » Mandant wählen » SSL*. +
→ Das Zertifikat der Domain wird angezeigt.
. Klicke in der Zeile *Neues SSL bestellen für Domain:[Domain-Name]* rechts auf den Pfeil nach unten. +
→ Die für die Domain buchbaren SSL-Zertifikate werden angezeigt.
. Klicke in der Zeile des SSL-Zertifikats, das du buchen möchtest, auf *SSL bestellen*. +
→ Das SSL-Zertifikat wird bestellt. +
*_Hinweis:_* Es kann bis zu 2 Stunden dauern, bis das SSL-Zertifikat aktiviert ist.

[#1300]
== Checkliste

* [ ] Stammdaten und Bankdaten: Hast du die Stammdaten und Bankdaten gespeichert?
* [ ] E-Mail-Kontodaten: Hast du deine E-Mail-Kontodaten im System eingegeben?
* [ ] E-Mail-Vorlagen: Enthalten alle E-Mail-Vorlagen die Template-Funktion *Link_Checkout()*?
* [ ] E-Mail-Vorlagen: Hast du in allen E-Mail-Vorlagen die Musterdaten durch deinen eigenen Kontaktdaten ergänzt?
* [ ] Signatur: Hast du deine E-Mail-Signatur gespeichert und die Template-Variable *$SignatureText* am Ende deiner E-Mail-Vorlagen hinzugefügt?
* [ ] SSL-Zertifikat: Hast du ein SSL-Zertifikat gebucht?
* [ ] Testmodus: Hast du nach dem Testen den Testmodus deaktiviert, damit E-Mails ab sofort an deine Kunden und nicht mehr an dich selbst versendet werden?

[#1400]
== Mehr zum Thema *Basiseinstellungen*

* <<crm/e-mails-versenden#100, E-Mail-Server-Zugangsdaten speichern>>
* <<crm/e-mails-versenden#1200, E-Mail-Vorlage erstellen>>
* <<omni-channel/online-shop/ceres-einrichten#300, Rechtliche Angaben im Ceres-Webshop speichern>>
// * verlinken auf Automatisierungsseite von Denise <<schnelleinstieg/automatisierung#, Automatischer E-Mail-Versand>>
* <<crm/newsletter-versenden#, Newsletter versenden>>
* <<crm/ticketsystem-nutzen#, Ticketsystem nutzen>>
* <<basics/arbeiten-mit-plentymarkets/plentymarkets-konto#50, Domain-Daten verwalten>>
* <<basics/arbeiten-mit-plentymarkets/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat verwalten>>
* <<basics/arbeiten-mit-plentymarkets/plentymarkets-konto#20, Vertragsdaten ändern>>

TIP: Weiter zum Thema <<schnelleinstieg/schnelleinstieg-warenwirtschaft#, Warenwirtschaft einrichten>>
