= Lager und Lieferant einrichten
:lang: de
include::{includedir}/_header.adoc[]
:position: 40
:url: schnelleinstieg/schnelleinstieg-warenwirtschaft

IMPORTANT: Hast du schon deine Kontaktdaten gespeichert, dein E-Mail-Konto und die E-Mail-Vorlagen eingerichtet und eine Domain und das SSL-Zertifikat bestellt? Noch nicht? Dann geht's hier zurück zum Thema <<schnelleinstieg/schnelleinstieg-basiseinstellungen#, Basiseinstellungen vornehmen>>.

Für eine funktionierende Warenwirtschaft müssen mindestens Lager, Lieferant und Warenbestand eingerichtet werden. Die beiden ersteren werden auf dieser Seite behandelt.

Wenn du die Warenbestände nicht in plentymarkets führen möchtest, wähle im Menü *Artikel » Artikel bearbeiten* im Tab *Varianten-ID » Einstellungen* bei der Einstellung *Beschränkung* die Option *Keinen Warenbestand für diese Variante führen*. Fahre dann fort mit <<artikel/artikel-verwalten#660, Artikelbilder verwalten>>.

[#100]
== Lager einrichten

Im Folgenden ist beschrieben, wie du ein Lager einrichtest. Hier werden allerdings lediglich die Basiseinstellungen für ein Lager erläutert. Informationen zu detaillierteren Einstellungen sind auf den unten aufgeführten Handbuchseiten zu finden. +
Es wird empfohlen, von vornherein ein Vertriebslager und ein Reparaturlager einzurichten.

[.instruction]
Lager einrichten:

. Öffne das Menü *System » Systemeinstellungen » Waren » Lager*.
. Wähle eines der bestehenden Lager *KS Repair* oder *KS Sales*.
. Klicke im Untermenü auf *Einstellungen*. +
→ Die Übersicht des Lagers wird geöffnet.
. Benenne das Lager im Feld *Lagername* um.
. Wähle einen Lagertyp und einen Logistiktyp.
. *Speichere* die Einstellungen. +
→ Das Lager wird eingerichtet und links im Verzeichnisbaum angezeigt.
. Öffne das Lager, um die Untermenüs zu sehen.

[#200]
== Lieferanten einrichten

Im Folgenden ist beschrieben, wie du einen Lieferanten einrichtest. Ein Lieferant ist hier nur Typ eines Kontakts.

[.instruction]
Lieferanten einrichten:

. Öffne das Menü *CRM » Kontakte*.
. Klicke auf *Neuen Kontakt erstellen*.
. Gib den Namen des Lieferanten ein.
. Wähle den Typ *Lieferant*.
. Wähle im Feld *Neue Adresse* einen Adresstyp (Rechnungs- oder Lieferadresse).
. Gib die Adressdaten ein.
. *Speichere* die Einstellungen.

[#300]
== Mehr zum Thema Lager und Lieferanten

* <<warenwirtschaft/lager-einrichten#, Lager einrichten>>
* <<crm/kontakte-verwalten#100, Kontakte verwalten>>.

TIP: Weiter zum Thema <<schnelleinstieg/schnelleinstieg-webshop-einleitung#, Webshop einrichten: Einleitung>>
