= Artikelkatalog aufbauen
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

Im Menü <<artikel/artikel-verwalten#, Artikel » Artikel bearbeiten>> werden alle Artikel und Varianten aufgelistet. In dieser Artikelübersicht kannst du Artikel und Varianten suchen, bearbeiten und neue Artikel erstellen.

Jedes neue plentymarkets System enthält einige Testartikel und Testvarianten. Diese Testdaten helfen dir, dich mit der Struktur von Artikeln und Varianten vertraut zu machen, bevor du deine eigenen Produkte importierst oder manuell ins System einpflegst.

In der Spalte links findest du Filter, um die Artikelsuche einzugrenzen. Zum Einstieg ist vor allem der Filter *Aktiv* wichtig. Mit diesem Filter legst du fest, ob in der Liste der Artikel nur Artikel und Varianten angezeigt werden, die für einen Webshop aktiviert sind. Standardmäßig ist dieser Filter auf *Ja* eingestellt. Das wird dir später, wenn du viele Artikel und Varianten hast, helfen, deine Artikel schneller zu bearbeiten. Am Anfang kann es aber verwirrend sein, denn natürlich werden Artikel, die nicht aktiv sind, erst einmal nicht gefunden, wenn du auf *Suchen* klickst, ohne vorher den Filter auf *Nein* oder *Alle* zu setzen.

Informationen zu den anderen Filtermöglichkeiten für Artikel und Varianten findest du unter <<artikel/artikel-verwalten#350, Artikel und Varianten suchen>>.

????Bevor du nun die ersten Artikel im System erstellst, sind einige vorbereitende Arbeiten nötig, darunter das Löschen der Musterartikel sowie das Erstellen von Kategorien und Attributen.????

////
[#260]
== Testartikel verstehen

Jedes neue plentymarkets System enthält einige Testartikel und Testvarianten. Diese Testdaten helfen dir, dich mit der Struktur von Artikeln und Varianten vertraut zu machen, bevor du deine eigenen Produkte importierst oder manuell ins System einpflegst.

Anhand dieser Testartikel werden wir dir kurz die Artikelstruktur erklären.

[.instruction]
Testartikel anzeigen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke in der Spalte links oben auf *Suchen*. +
→ Die Testartikel werden in der Übersicht angezeigt.



=== Testartikel 132: Zweisitzer Paradise Now

Der Artikel mit der Artikel-ID 132 hat drei Varianten:

1030 - Hauptvariante, virtuell
1065 - Zweisitzer, Farbe Rot
1066 - Zweisitzer, Farbe Weiß
////




[#290]
== Kategorien erstellen

Mit Kategorien des Typs *Artikel* strukturierst du dein Produktsortiment und gestaltest deinen Webshop übersichtlich. Jeder Artikel muss einer Standardkategorie zugeordnet sein. Die Standardkategorie entscheidet darüber, in welcher Kategorie ein Artikel bei der Suche im Webshop gefunden und angezeigt wird.

Überlege dir zuerst, welche Kategorien und Unterkategorien für deine Produkte sinnvoll sind. Welche Sortierung macht es deinen Kundinnen und Kunden leicht, sich in deinem Shop zurechtzufinden? Trage diese Informationen am besten in einem Dokument zusammen, bevor du loslegst. Eine Baumstruktur zu skizzieren kann dir helfen, deine Produkte sinnvoll zu gruppieren. Du kannst dich für eine Kategorietiefe von entweder 2 oder 4 Ebenen entscheiden: Im Webshop *Ceres* wird in der Standard-Navigationsleiste unterhalb der Hauptkategorien maximal eine weitere Kategorieebene dargestellt. Alternativ bietet dir das Megamenü die Möglichkeit, bis zu drei weitere Ebenen unterhalb der Hauptkategorien darzustellen.

[.instruction]
Hauptkategorie erstellen:

. Öffne das Menü *Artikel » Kategorien*.
. Klicke links unten auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Gib einen Namen ein. +
*_Tipp:_* Die Option *Hauptkategorie* ist standardmäßig ausgewählt.
. Klicke auf *Erstellen*. +
→ Die Kategorie wird erstellt. +
→ Das Tab *Einstellungen* der Kategorie wird geöffnet. +
. Gib eine *Position* ein. Über die Position legst du die Reihenfolge fest, in der die Kategorien im Webshop angezeigt werden. Standardmäßig hat jede neue Kategorie, die du anlegst, die Position 0. +
*_Tipp:_* Positionsnummern in Zehnerschritten vergeben, damit neue Kategorien dazwischen eingefügt werden können.
. Aktiviere die *Mandanten (Shops)*, in denen die Kategorie verfügbar sein sollen.
. Gib einen *Mega-Titel* ein. Dieser Meta-Titel wird im Tab des Browsers angezeigt.
. *Speichere* die Einstellungen.


[.instruction]
Unterkategorie erstellen:

. Öffne das Menü *Artikel » Kategorien*.
. Klicke links unten auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Gib einen Namen ein. +
. Wähle die Option *Unterkategorie*.
. Klicke auf die Hauptkategorie, für die du die Unterkategorie erstellen möchtest. +
*_Tipp:_* Um eine Unterkategorie der dritten oder vierten Ebene zu erstellen, klicke in der Liste auf das Symbol der Hauptkategorie, um den Ordner zu öffnen. Öffne dann die Ordner der Unterkategorien auf die gleiche Weise, bis du die Kategorie erreichst, zu der du eine Unterkategorie erstellen möchtest.
. Klicke auf *Erstellen*. +
→ Die Kategorie wird erstellt. +
→ Das Tab *Einstellungen* der Kategorie wird geöffnet.
. Gib eine *Position* ein. Über die Position legst du die Reihenfolge fest, in der die Kategorien im Webshop angezeigt werden. Standardmäßig hat jede neue Kategorie, die du anlegst, die Position 0. +
*_Tipp:_* Positionsnummern in Zehnerschritten vergeben, damit neue Kategorien dazwischen eingefügt werden können.
. Aktiviere die *Mandanten (Shops)*, in denen die Kategorie verfügbar sein sollen.
. Gib einen *Mega-Titel* ein. Dieser Meta-Titel wird im Tab des Browsers angezeigt.
. *Speichere* die Einstellungen.

[TIP]
.Die neuen Kategorien werden nicht im Webshop angezeigt?
====
Wenn deine Kategorien nicht im Webshop angezeigt werden, hilft dir unsere <<artikel/best-practices#kategorien, Checkliste für die Kategoriesichtbarkeit im Webshop>> weiter.
====

== Attribute erstellen

Attribute dienen dazu, in plentymarkets Varianten zu erstellen. Varianten sind verschiedene Ausführungen eines Artikels, die sich bei sonst gleichen Eigenschaften in einer oder mehreren Eigenschaften unterscheiden. Zum Beispiel soll ein Artikel in drei Farben verkauft werden. Diese drei Farbvarianten sollen für Kundinnen und Kunden bei der Bestellung wählbar sein. Damit du nicht für jedes Produkt einen eigenen Artikel erstellen musst, werden diese Eigenschaften in plentymarkets als <<artikel/artikel-verwalten#390, Attribute>> eingestellt und dann einem Artikel zugeordnet. Unten wird beispielhaft beschrieben, wie du das Attribut *Farbe* erstellst.

[.instruction]
Attribut "Farbe" erstellen:

. Öffne das Menü *System » Artikel » Attribute*.
. Klicke auf *Neues Attribut*. +
→ Das Fenster *Neues Attribut* wird geöffnet.
. Gib einen *Namen (intern)* ein, z.B. *Farbe*. +
*_Tipp:_* Dieser interne Name ist im Webshop nicht sichtbar.
. *Speichere* die Einstellungen. +
→ Das Attribut wird erstellt. +
→ Das Tab *Grundeinstellungen* des Attributs wird geöffnet.
. Wechsele in das Tab *Name*.
. Gib Namen für das Attribut in den Sprachen ein, die du in deinem Webshop verwendest. +
→ Dieser Name wird im Webshop angezeigt.
. *Speichere* die Einstellungen.
. Erstelle wie unten beschrieben Werte für das Attribut.


[.instruction]
Wert "Grün" für das Attribut "Farbe" erstellen:

. Wechsele in das Tab *Werte*.
. Klicke auf *Neuer Wert*. +
→ Das Fenster *Neuer Wert* wird geöffnet.
. Gib einen *Namen (intern)* ein, z.B. *Grün*. +
*_Tipp:_* Dieser interne Name ist im Webshop nicht sichtbar.
. *Speichere* die Einstellungen. +
→ Der Wert wird erstellt. +
→ Der Wert wird in der Liste angezeigt.
. Gib in der Spalte *Name* einen Namen für den Wert ein. +
*_Tipp:_* Standardmäßig wird der interne Name eingefügt. +
→ Dieser Name wird im Webshop angezeigt.
. *_Optional:_* Wenn du deine Produkte in mehreren Sprachen anbietest, wähle im Dropdown-Menü *Sprache anzeigen* die weiteren Sprachen.
. *_Optional:_* Gib in der Spalte *Name* einen Namen für den Wert in dieser Sprache ein. +
→ Dieser Name wird später im Webshop angezeigt.
. *Speichere* die Einstellungen.

// Soll das als Beispiel oder allgemein formuliert sein? Also "Farbe" oder "Attribut"?



[#350]
== Artikel erstellen

Die Basis Ihres Geschäfts bilden die Artikel und Artikelvarianten, die Sie verkaufen. Auch für Varianten müssen Sie zunächst einen Artikel erstellen. Wie Sie zu einem Artikel Varianten erstellen, folgt in einem späteren Kapitel. Erstellen Sie nun zunächst den Hauptartikel im Menü <<artikel/artikel-verwalten#, Artikel » Artikel bearbeiten>>.

[TIP]
.Artikelverfügbarkeit und Lieferfristen
====

====

[NOTE]
.Import möglich?
====
Wenn du schon eine eigene Datenbank aufgebaut hast oder Artikeldaten aus einem anderen System exportieren kannst, prüfe vor der manuellen Eingabe deiner Artikeldaten die <<basics/datenaustausch/ElasticSync/ElasticSync-beta#, Importmöglichkeiten>>. Mit etwas Vorarbeit können Daten per CSV-Datei in plentymarkets importiert werden. Dein plentymarkets System bietet auch zahlreiche komfortable Schnittstellen zu gängigen Softwarelösungen.
====


// Hauptvariante virtuell, wenn mehr als eine Variante!
// am besten artikel nicht mit attributen verknüpfen, damit man flexibel bleibt

[.instruction]
Artikel erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Artikeltyp *Standard*.
. Gib einen Namen ein.
. Gib eine Zahl für den Inhalt ein.
. Wähle für diesen Inhalt eine Einheit aus der Dropdown-Liste.
. Klicke auf die Kategorie. +
→ Diese Kategorie wird als Standardkategorie mit der Hauptvariante des Artikels verknüpft.
. Gib einen *Preis* ein. +
*_Tipp:_* Der Verkaufspreis *Preis* ist standardmäßig vorhanden. Bei Bedarf kannst du diesen Verkaufspreis <<artikel/artikel-verwalten#870, anpassen>> oder einen Verkaufspreis erstellen.
. *Speichere* die Einstellungen. +
→ Der Artikel wird erstellt. +
→ Das Tab *Global* des Artikels wird geöffnet.
. Nimm bei Bedarf weitere Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-artikel-bearbeiten>>.
. *Speichere* die Einstellungen.

Die in <<einstellungen-artikel-bearbeiten>> erläuterten Einstellungen beziehen sich auf verschiedene Tabs im Bearbeitungsfenster eines Artikels des Typs *Standard*. Das Tab wird in einer eigenen Zeile als Zwischenüberschrift angezeigt. Um dir zu helfen, deine Artikel möglichst bald verkaufsfähig zu machen, haben wir nur die wichtigsten Einstellungen zusammengestellt.

[[einstellungen-artikel-bearbeiten]]
.Einstellungen im Bearbeitungsfenster eines Artikels
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|plentymarkets kann automatisch eine fortlaufende Nummer vergeben (empfohlen). +
Alternativ kann beim Erstellen eines Artikels eine eigene Artikel-ID vergeben werden. Außerdem kann die Artikel-ID nachträglich geändert werden. Es sind nur Zahlen ohne Dubletten möglich.

2+|Tab: Global

|*Versandprofile*
|Ein, mehrere oder *ALLE* <<auftragsabwicklung/fulfillment/versand-vorbereiten#1800, Versandprofile>> aktivieren. Standardmäßig ist kein Versandprofil aktiviert. +
*_Hinweis:_* Pro Artikel muss mindestens ein Versandprofil aktiviert werden, da sonst ungewollte Effekte bei der Versandkostenberechnung auftreten können.

2+|Tab: Varianten-ID » Einstellungen

|*Aktiv*
|Artikel aktivieren, um ihn im Webshop und auf Marktplätzen anzubieten. Artikel werden erst im Webshop angezeigt, wenn sie aktiv sind. +
*_Hinweis:_* Bei der Artikelsuche im Menü *Artikel bearbeiten* werden inaktive Artikel nicht mit den Standardeinstellungen der Suche angezeigt. Im Filter *Aktiv* die Option *Nein* wählen, um nach inaktiven Artikeln zu suchen.

|*Verfügbarkeit*
|Verfügbarkeitsstufe wählen. +
*_Tipp:_* Du bist gesetzlich verpflichtet, Verbraucherinnen und Verbraucher über die Lieferfristen deiner Produkte zu informieren. Im Menü *System » Artikel » Verfügbarkeit* sind Standardtexte für 5 Verfügbarkeitsstufen gespeichert. Passe <<artikel/artikel-verwalten#180, diese Texte bei Bedarf an>>.

|*Verkaufspreise*
|Verkaufspreis hinzufügen und Preis eingeben.

|*Barcode*
|Barcode hinzufügen und Code eingeben.

|*ASIN/ePID*
|ASIN/ePID hinzufügen und ASIN bzw. ePID eingeben.

|*Gewicht brutto*; +
*Gewicht netto*
|Angabe in Gramm oder Kilogramm. +
*_Hinweis:_* Diese Angaben sind unbedingt erforderlich, wenn die Versandkosten auf Basis des Gewichts berechnet werden.

|*Umsatzsteuer*
|Umsatzsteuersatz des Produkts wählen.

2+|Tab: Varianten-ID » Verfügbarkeit

|*Mandant (Shop): Verfügbar*
|Den oder die Mandanten (Shops) aktivieren, in denen die Variante verfügbar sein soll.

2+|Tab: Texte

|*Name 1*
|Name des Artikels eingeben.

|*Artikeltext*
|Artikeltext eingeben. Der Artikeltext ist eine detaillierte Produktbeschreibung, die in der Artikelansicht im Webshop angezeigt wird.
|====


[#370]
== Varianten erstellen

Beim Erstellen eines neuen Artikels wird immer eine Hauptvariante erstellt. Die Hauptvariante ist fest mit dem Artikel verbunden. Die Hauptvariante kann nicht gelöscht werden. Standardmäßig werden die Informationen der Hauptvariante, zum Beispiel die Verkaufspreise und die Verfügbarkeit, von den weiteren Varianten des Artikels geerbt. Du kannst aber auch die Vererbung deaktivieren und für jede Variante andere Daten speichern. Erfahre zunächst, wie du Varianten erstellst.

[.instruction]
Eine oder mehrere Varianten erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Varianten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neue Variante erstellen* wird geöffnet.
. Gib den Inhalt ein.
. Wähle für diesen Inhalt eine Einheit aus der Dropdown-Liste.
. Wähle ein oder mehrere Attribute. +
→ Unter *Kombinationen* wird angezeigt, wie viele Varianten erstellt werden.
. Klicke auf *Varianten erstellen*. +
→ Die Varianten werden erstellt. +
→ Die Varianten werden in der Variantenübersicht angezeigt. +
*_Tipp:_* Die Varianten haben dieselben Einstellungen wie die Hauptvariante des Artikels.

// welche Daten werden vererbt?
// Tipp: Artikel kopieren und anpassen

[#400]
== Verfügbarkeitsanzeige im Webshop automatisieren

Die Verfügbarkeit von Artikeln ändert sich ständig. Die Verfügbarkeitsangaben manuell zu pflegen ist sehr aufwendig. Natürlich kannst du anfangs den Verfügbarkeitsstatus deiner Artikel manuell aktualisieren. Dennoch solltest du die Pflege der Verfügbarkeitsanzeige im Webshop so bald wie möglich automatisieren, wenn du den Warenbestand mit plentymarkets verwaltest. Im Webshop werden dann die Symbole *lieferbar* und *nicht lieferbar* automatisch nach dem aktuellen Warenbestand angezeigt. Alternativ kannst du Artikel ohne Warenbestand auch ganz ausblenden und wieder einblenden, sobald neuer Bestand im Lager gebucht wird.

[.instruction]
Verfügbarkeitsanzeige automatisieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel. +
→ Das Tab *Einstellungen* der Hauptvariante wird geöffnet.
. Wählen im Bereich *Verfügbarkeit* bei *Beschränkung* die Option *Auf Netto-WB*.
. Aktiviere im Bereich *Verfügbarkeit* die folgenden Optionen: +
*Anzeige im Webshop: Automatisch verfügbar wenn Netto-WB positiv* +
*Anzeige im Webshop: Automatisch nicht verfügbar wenn kein Netto-WB* +
*Mandant: Automatisch sichtbar wenn Netto-WB positiv* +
*Mandant: Automatisch unsichtbar wenn kein Netto-WB*.
. *Speichere* die Einstellungen.
// Oder per Gruppenfunktion?


[#410]
== Artikelbilder hochladen

// Auch importieren?

Im Tab <<artikel/artikel-verwalten#90, Bilder>> im Bearbeitungsfenster des Artikels speicherst du Bilder und verknüpfst diese Bilder mit den Varianten des Artikels. Pro Artikel sind bis zu 25 Bilder in den Formaten JPG/JPEG oder PNG möglich. Für die Verwendung auf der Plattform eBay solltest du das erste Bild, also das Hauptbild, im Format *JPG* speichern.

[TIP]
.FTP-Upload nutzen
====
Größere Bildmengen überträgst du am besten per <<artikel/artikel-verwalten#680, FTP-Upload>> auf den Server. Lies aber vorher die Hinweise zur Benennung der Bilddateien, damit die Bilder beim Hochladen den richtigen Artikeln und Varianten zugeordnet werden.
====

[.instruction]
Bilder für einen Artikel speichern:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Bilder* des Artikels.
. Ziehe neue Bilder per Drag & Drop-Funktion in den Bereich *Neues Bild einfügen*. +
*_Oder:_* Klicke auf *Dateien auswählen*.
. Wähle aus der Dropdown-Liste *Verfügbarkeit* die Mandanten und/oder Herkünfte, für die das Bild bereitgestellt werden soll.
. *Speichere* die Einstellungen.

[#420]
== Bilder mit Varianten verknüpfen

// auch beim import erklären?

Verknüpfe nun die am Artikel gespeicherten Bilder mit einer oder mehreren Varianten. Gehe dazu wie unten beschrieben vor.

[.instruction]
Artikelbilder mit Varianten verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Bilder* des Artikels. +
→ Eine Vorschau der am Artikel gespeicherten Bilder wird angezeigt.
. Setze ganz links ein Häkchen bei den Bildern, die du mit einer oder mehreren der Varianten verknüpfen möchtest.
. Klicke am unteren Ende der Seite auf *Variantenverknüpfung*. +
→ Das Fenster *Varianten verknüpfen* wird angezeigt.
. Wähle die Varianten, die du mit den gewählten Bildern verknüpfen möchtes.
. Klicke auf *Verknüpfen*. +
→ Die Bilder werden mit den gewählten Varianten verknüpft.


== Für Fortgeschrittene

[TIP]
.Cross-Selling nutzen
====
Du möchtest deine Kundinnen und Kunden auf weitere interessante Produkte aufmerksam machen? Dann richte <<artikel/artikel-verwalten#950, Cross-Selling-Verknüpfungen ein>>.
====




[#270]
== Testdaten löschen

Nun solltest du die Testartikel aus deinem System löschen.

////
Wir empfehlen Ihnen, die in neuen Systemen gespeicherten Testartikel zu löschen, da sie nicht Ihrem tatsächlichen Portfolio entsprechen und nur dazu dienen, plentymarkets schnell zu verstehen. Wenn Sie in Ihrem Testsystem weitere Artikel und Kategorien erstellt haben, die Sie für die endgültige Einrichtung nicht mehr benötigen, empfehlen wir Ihnen, diese Testdaten ebenfalls zu löschen, bevor Sie Ihren endgültigen Katalog aufbauen.
////

[.instruction]
Testartikel per Gruppenfunktion löschen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Stelle den Filter *Aktiv* auf *ALLE*.
. Klicke auf *Suchen*. +
→ Alle im System gespeicherten Artikel werden angezeigt.
. Wähle alle Artikel, indem du die Artikel-ID anklickst.
. Klicke auf *Artikel-Gruppenfunktion*. +
→ Das Fenster *Artikel-Gruppenfunktion* wird geöffnet.
. Aktiviere die Option *Artikel löschen*.
. Klicke auf *Ausführen*. +
→ Alle Artikel werden aus dem System gelöscht.


[#440]
== Checkliste Artikelkatalog

Die Checkliste soll dir helfen, dient zur Prüfung der Artikeleinstellungen. Arbeiten Sie die Checkliste durch, nachdem Sie die zuvor beschriebenen Einstellungen zum Schnelleinstieg vorgenommen haben.

[%interactive]
[ ] Hast du den <<#350, Artikelkatalog>> mit allen Beschreibungstexten aufgebaut?
[ ] Hast du die <<#370, Artikelverfügbarkeit>> korrekt eingestellt?
// [ ] Hast du alle <<#350, Preise und Mehrwertsteuersätze>> nochmals geprüft?
// wir haben keine MwSt. erstellt //
