= Basiseinstellungen vornehmen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Stammdaten, Bankdaten, E-Mail, E-Mails, Emails, Zugangsdaten, E-Mail-Vorlagen, Vorlage, Vorlagen, Template-Variable
:description: Erfahre in diesem Teil des Schnelleinstiegs, welche Basiseinstellungen du vornehmen musst.
:position: 0

In diesem Teil des Schnelleinstiegs findest du Erläuterungen zu allgemeinen Einstellungen wie dem Speichern von Stammdaten sowie zum Einrichten der E-Mail-Einstellungen und E-Mail-Vorlagen. Außerdem erfährst du auf dieser Seite, wie du eine Domain und ein SSL-Zertifikat für deinen Online-Shop bestellst.

[#100]
== Stammdaten speichern

Im Menü *System » Einstellungen » Stammdaten* speicherst du zentral die Stammdaten deines Unternehmens wie z.B. die Kontaktdaten, Adresse und Umsatzsteuer-ID.

//Änderungen dieser Daten wirken sich auf das ganze System aus.

[.instruction]
Stammdaten speichern:

. Öffne das Menü *System » Einstellungen » Stammdaten*.
. Gib deine Daten ein.
. *Speichere* die Einstellungen. +
→ Die Stammdaten werden gespeichert.

////
TODO
[IMPORTANT]
.Vertragsdaten ändern
====
Eine Änderung der Stammdaten in diesem Menü ändert nicht die Kundenstammdaten deines plentymarkets Vertrages z.B. für die Rechnungsstellung. Vertragsdaten passt du im Menü *Support » Service-Center* an. Weitere Informationen dazu findest du weiter unten auf dieser Seite im Kapitel << Vertragsdaten ändern >>.
====
////

[#200]
== Bankdaten speichern

Ebenso wie die Stammdaten speicherst du auch deine Bankdaten an einer zentralen Stelle in deinem plentymarkets System. Eine Korrektur der Bankdaten ist ausschließlich im Menü *System » Einstellungen » Bank* möglich. Änderungen dieser Daten wirken sich auf das gesamte System aus.

Deine Bankdaten können über sogenannte Template-Variablen in E-Mail-Vorlagen ausgegeben werden. Das bedeutet, dass plentymarkets in den E-Mails selbst  die Variablen durch den jeweiligen Inhalt ersetzt. Die Variable *$BankOwner* wird so z.B. durch den Namen des Kontoinhabers ersetzt und *$BankAccount* setzt die Kontonummer ein.

[.instruction]
Bankdaten speichern:

. Öffne das Menü *System » Einstellungen » Bank*.
. Gib deine Bankdaten ein. Beachte dazu die Erläuterungen in <<tabelle-bankdaten-speichern>>.
. *Speichere* die Einstellungen.

[[tabelle-bankdaten-speichern]]
.Bankdaten speichern
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Kontoinhaber*
|Vorname und Name des Kontoinhabers eingeben. +
Template-Variable: *$BankOwner*

|*Konto-Nr.*
|Kontonummer eingeben. +
Template-Variable: *$BankAccount*

|*BLZ*
|Bankleitzahl eingeben. +
Template-Variable: *$BankCode*

|*Bank*
|Name der Bank eingeben. +
Template-Variable *$BankName*

|*IBAN*
|Internationale Bankleitzahl eingeben. +
Template-Variable *$BankIban*
|====

Welche Template-Variablen dir für die E-Mail-Vorlagen zur Verfügung stehen, erfährst du weiter unten auf dieser Seite im Kapitel <<schnelleinstieg/basiseinstellungen#500, E-Mail-Vorlagen einrichten>>.

[#300]
== E-Mail-Signatur speichern

Speichere nun die Signatur deines Online-Shops, die dann in den E-Mail-Vorlagen automatisch ausgegeben wird, wenn du am Ende der E-Mail-Vorlagen die Template-Variable *$SignatureText* speicherst. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
E-Mail-Signatur speichern:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Signatur*.
. Gib den Text diner Signatur ein. +
→ Beachte die gesetzlichen Vorgaben zum Inhalt einer E-Mail-Signatur. Lass dich im Zweifelsfall von einem kundigen Fachanwalt beraten.
. *Speichere* die Einstellungen.

////
TODO
Signatur eingeben und dann $SignatureText am Ende der E-Mail-Vorlage einfügen
////

[#400]
== E-Mail-Zugangsdaten eingeben

Im Folgenden erfährst du, welche Einstellungen du vornehmen musst, damit dein plentymarkets System später bei Eintritt eines definierten Ereignisses automatisch E-Mails wie Auftrags- und Versandbestätigungen erzeugt und an deine Kunden versendet.

[TIP]
.Testmodus sendet E-Mails nur an deine E-Mail-Adresse
====
Don't worry! Es gibt einen Testmodus, der standardmäßig aktiviert ist. Im   Testmodus werden alle E-Mails nur an deine eigene E-Mail-Adresse gesendet. So kannst du alle Einstellungen testen, bevor du live damit arbeitest.
====

Damit plentymarkets über dein E-Mail-Konto E-Mails für dich versenden kann, musst du die Zugangsdaten deines E-Mail-Programms in plentymarkets eingeben.

[.instruction]
E-Mail-Zugangsdaten eingeben:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Zugangsdaten*.
. Nimm die Einstellungen gemäß <<tabelle-e-mail-zugangsdaten-eingeben>> vor.
. *Speichere* die Einstellungen.

[[tabelle-e-mail-zugangsdaten-eingeben]]
.E-Mail-Zugangsdaten eingeben
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Testmodus*
|*aktiv* (Standardeinstellung) = Während der Testphase einstellen, damit alle E-Mails nur an deine Adresse gesendet werden. +
*inaktiv* = Nach Ende der Testphase einstellen, damit deine Kunden die E-Mails erhalten.

|*Name des Absenders*
|Deinen Namen und/oder den Namen deines Webshops eingeben, wie er beim Empfänger angezeigt werden soll.

|*E-Mail-Adresse*
|E-Mail-Adresse eingeben, wie sie auch in deinem E-Mail-Programm steht, z.B. info@myshop.de.

|*Postausgangsserver / SMTP-Server*
|Den Postausgangsserver erfährst du von deinem Provider (meist smtp.domain.de oder mail.domain.de).

|*Benutzername*
|Benutzername zu der E-Mail-Adresse eingeben.

|*Passwort*
|Passwort zu dem Benutzernamen und der E-Mail-Adresse eingeben.

|*Port (Standard-Port: 25)*
|Der Wert *25* ist für fast alle Provider korrekt. Andernfalls musst du den korrekten Port bei deinem Provider erfragen. +
*_mailbox.org:_* Für Postfächer bei mailbox.org den Port *465* eingeben und unter *Verschlüsselung* die Einstellung *SSL* wählen.

|*Verschlüsselung*
|*SSL*, *TLS* oder *keine Verschlüsselung* (Standardeinstellung) wählen. +
Verwende für unsere E-Mail-Konten entweder die Einstellung *TLS* (mit Port 25) oder die Einstellung *keine Verschlüsselung*. +
*_mailbox.org:_* Für Postfächer bei mailbox.org den Port *465* eingeben und unter *Verschlüsselung* die Einstellung *SSL* wählen.

|====

[TIP]
.E-Mail-Infodienst einrichten
====
Sobald du den Testmodus deaktiviert hast, ist es gerade in der Anfangsphase sinnvoll, auf die durch das System versendeten E-Mails stärker ein Auge zu haben. Nutze dafür den Infodienst. Mit dieser Funktion sendest du eine Blindkopie (BCC) aller ausgehenden E-Mails an eine Adresse deiner Wahl.

[.instruction]
Infodienst einrichten:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Infodienst*.
. Wähle *JA* aus der ersten Dropdown-Liste, um den Infodienst für die in der nächsten Zeile eingegebene E-Mail-Adresse zu aktivieren.
. Gib die E-Mail-Adresse ein, an die eine Blindkopie gesendet werden soll.
. *Speichere* die Einstellungen.

Außerdem kannst du einstellen, ob du bei Eingang einer neuen Bestellung in deinem Webshop eine Info-E-Mail erhalten möchtest. Wähle dazu *JA* aus der zweiten Dropdown-Liste *Sende Hinweis bei Eingang einer neuen Bestellung an E-Mail (nächste Zeile)* und gib in der nächsten Zeile die E-Mail-Adresse ein, an die eine E-Mail gesendet werden soll.

Um den Infodienst wieder zu beenden, wähle *NEIN* aus den beiden Dropdown-Listen und speichere die Einstellungen.
====

[#500]
== E-Mail-Vorlagen einrichten

plentymarkets erzeugt alle E-Mails auf Basis von Vorlagen. <<tabelle-e-mail-vorlagen>> listet alle E-Mail-Vorlagen auf, die bereits standardmäßig in deinem System vorhanden sind, und erklärt, für welche Ereignisse du diese E-Mail-Vorlagen verwenden kannst.

Du kannst alle E-Mail-Vorlagen an deine Erfordernisse anpassen. Wie du dazu vorgehst, haben wir für dich am Beispiel der E-Mail-Vorlage *Webshop: Eingangsbestätigung Bestellung* weiter unten auf dieser Seite im Kapitel <<schnelleinstieg/basiseinstellungen#600, Beispiel: E-Mail-Vorlage anpassen>> beschrieben.

[[tabelle-e-mail-vorlagen]]
.Bereits vorkonfigurierte E-Mail-Vorlagen
[cols="1,3"]
|====
|E-Mail-Vorlage |Erläuterung

|*Auftrag: Änderung*
|Sendet die Änderung der Bestellung an den Kunden.

|*Auftrag: Rechnung PDF-Anhang*
|Sendet die Rechnung als Dateianhang an den Kunden. +
*_Wichtig:_* Eine Rechnungsvorlage für den Standort *Deutschland* ist bereits vorkonfiguriert. Du kannst die Vorlage nach Bedarf im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* anpassen. Wenn eine Rechnung für den Auftrag existiert, wird die Rechnung automatisch an den Kunden versendet, da in der Vorlage *Auftrag: Rechnung PDF-Anhang* der PDF-Anhang *Rechnung* bereits standardmäßig gewählt ist.

|*Auftrag: Teilzahlung erhalten*
|Sendet eine Benachrichtigung an den Kunden über den Eingang einer Teilzahlung.

|*Auftrag: Versandbestätigung*
|Wird bei Versand der Ware verschickt.

|*Auftrag: Zahlungseingang vollständig*
|Sendet eine Benachrichtigung an den Kunden über den Eingang der vollständigen Zahlung.

|*Auftrag: Zahlungserinnerung*
|Sendet eine Erinnerung an den Kunden bei Zahlungsrückstand.

|*Webshop: Eingangsbestätigung Bestellung*
|Benachrichtigung an den Kunden, dass seine Bestellung eingegangen ist. +
*_Wichtig:_* In dieser E-Mail-Vorlage solltest du aus rechtlichen Gründen eine Widerrufsbelehrung sowie die AGB einfügen. Von großer Bedeutung in dieser E-Mail-Vorlage sind alle Formulierungen, die das vertragliche Verhältnis mit dem Kunden betreffen. Deine Texte solltest du daher von einem kundigen Fachanwalt prüfen lassen. +
Den Text für die Widerrufsbelehrung und die AGB speicherst du im Menü *System » Mandant » Mandant wählen » Webshop » Rechtliches*. Über die Template-Variablen *$CancellationRightsText* und *$GeneralTermsConditionsText* werden das Widerrufsrecht und die AGB dann automatisch in der E-Mail ausgegeben.

|*Webshop: Neues Passwort*
|Bei Verlust der Zugangsdaten erzeugt das System auf Wunsch des Kunden einen Link zum Zurücksetzen des Passworts.

|*Webshop: Newsletter Anmeldung*
|Sendet Newsletter an deine Kunden. +
*_Wichtig:_* Lasse dich zum Thema Newsletter-Versand am besten von einem kundigen Fachanwalt beraten.
|====

//Beachte, dass du ggf. Dokumente für die E-Mails erstellen und diese im PDF-Format hochladen musst, damit du die Dokumente als Dokumentenanhang versenden kannst.

[WARNING]
.Bankverbindung und Kontaktdaten nicht vergessen
====
Achte unbedingt darauf, dass in allen E-Mail-Vorlagen deine Bankverbindung eingegeben ist und dass am Ende der E-Mail statt des Mustertextes deine Kontaktdaten korrekt und vollständig eingegeben sind. Du kannst dafür Template-Variablen verwenden. <<schnelleinstieg/basiseinstellungen#700, Template-Variablen und Template-Funktionen einfügen>>
====

[#600]
=== Beispiel: E-Mail-Vorlage anpassen

Anhand des Beispiels der E-Mail-Vorlage *Webshop: Eingangsbestätigung Bestellung* beschreiben wir im Folgenden, wie du eine E-Mail-Vorlage an deine Erfordernisse anpasst.

[.instruction]
E-Mail-Vorlage anpassen:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Klicke bei *Allgemeine E-Mail-Vorlagen* auf *Webshop: Eingangsbestätigung Bestellung*. +
→ Das Tab *Einstellungen* öffnet sich.
. Ändere ggf. die Einstellungen. Beachte dazu die Erläuterungen in <<tabelle-e-mail-vorlagen-einrichten>>.
. Wechsele ins Tab *E-Mail-Nachricht » Tab: Inhalt » Tab: Reiner Text*. +
→ Der Standardtext öffnet sich.
. Ändere ggf. den Text.
. Füge die Texte für das Widerrufsrecht und die AGB im Menü *System » Mandant » Mandant wählen » Webshop » Rechtliches* ein, damit die Template-Variablen *$CancellationRightsText* und *$GeneralTermsConditionText* in der versendeten E-Mail-Vorlage mit deinen AGB und dem Widerrufsrecht korrekt ausgegeben werden.
. Ersetze die Standardkontaktdaten am Ende der Vorlage durch deine Kontaktdaten.
. *Speichere* die Einstellungen.

[[tabelle-e-mail-vorlagen-einrichten]]
.E-Mail-Vorlagen einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Erste Zeile

|*Speichern*
|Speichert die E-Mail-Vorlage.

|*Template-Variablen -und Funktionen*
|Öffnet alle in plentymarkets verfügbaren Template-Variablen und Template-Funktionen, die du in deinen E-Mail-Vorlagen verwenden kannst.

2+|Tab: Einstellungen

|*Eigner*
|Standardmäßig ist die Einstellung *Alle* gewählt. Das bedeutet, dass alle Benutzer Zugriff auf diese Vorlage haben.

|*Name*
|Name der E-Mail-Vorlage, die zur internen Unterscheidung verwendet wird. Dieser Name wird dem Empfänger nicht angezeigt. Du kannst diesen Namen anpassen.

|*Inhalt*
|*Nur reiner Text* (Standardeinstellung) oder *Nur HTML-formatierter Text* wählen.

|*Template-Typ*
|*Alle* (Grundeinstellung) wählen, wenn die E-Mail-Vorlage für alle Bereiche verwendet werden soll, oder den Bereich in plentymarkets aus der Dropdown-Liste wählen, für den diese E-Mail-Vorlage ausschließlich zur Verfügung stehen soll.

|*PDF-Anhang*
|Standardmäßig ist die Einstellung *Kein PDF-Anhang* gewählt. +
*_Hinweis:_* Wenn du später für deine Auftragsbestätigungen die Rechnung an die E-Mail-Vorlage anhängen willst, musst du die Rechnungsvorlage vorab konfigurieren. Außerdem muss eine Rechnung für den Auftrag existieren.

|*Dokumentenanhang*
|Standardmäßig ist die Einstellung *Kein Dokumentenanhang* gewählt. +
*_Hinweis:_* Wenn du einen Anhang wie z.B. einen Artikelprospekt versenden möchtest, musst du diesen im Menü *CMS » Dokumente* hochladen. In der Dropdown-Liste *Dokumentenanhang* werden nur Dateien angezeigt, die im Menü *CMS » Dokumente* hochgeladen wurden.

|*Antwort an*
|E-Mail-Adresse eingeben, an die die Antworten auf diese E-Mail-Vorlage gesendet werden sollen. +
*_Hinweis:_* Wenn keine E-Mail-Adresse eingegeben wird, werden Antworten auf diese E-Mail-Vorlage an die E-Mail-Adresse, die im Menü *System » Mandant » Mandant wählen » E-Mail » Zugangsdaten* gespeichert ist, versendet.

|*Mandant (Shop)*
|Standardmäßig sind alle Mandanten aktiviert.

2+|Tab: E-Mail-Nachricht

|*Sprache wählen*
|Standardmäßig ist die Sprache *de* gewählt.

|*Betreff*
|Ggf. den Standardtext des Betreffs anpassen. Den Betreff sorgfältig wählen, damit die E-Mail im Postfach des Kunden erkannt und nicht als Spam gefiltert wird.
|====

[#700]
=== Template-Variablen und Template-Funktionen einfügen

E-Mail-Vorlagen in plentymarkets bestehen immer aus Text sowie Template-Funktionen und Template-Variablen. In den E-Mails selbst ersetzt plentymarkets die Variablen durch den jeweiligen Inhalt. Die Variable *$CustomerFullName* wird so z.B. durch den Kundennamen ersetzt, *$CustomerEmail* setzt die E-Mail-Adresse des Kunden ein, die Variable *$OrderID* setzt die Auftrags-ID ein.

[IMPORTANT]
.Schreibweise der Template-Variablen beachten
====
Da Template-Variablen und Template-Funktionen vorkonfigurierte Systembefehle auslösen, musst du die Schreibweise der Namen genau einhalten. Um Fehlfunktionen durch Schreibfehler zu vermeiden, kopierst du die Variablen und fügst sie an gewünschter Stelle in die E-Mail-Vorlage ein.
====

[.instruction]
Template-Variablen und -Funktionen einfügen:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Öffne die Vorlage, in die du Template-Variablen einfügen möchtest.
. Klicke in der *E-Mail-Vorlage* auf *Template-Variablen und -Funktionen*. +
→ Das Fenster *Template-Variablen und -Funktionen* wird geöffnet.
. Kopiere die Variable, die du in die E-Mail-Vorlage einfügen möchtest.
. Füge die Variable in das Textfeld im Tab *E-Mail-Nachricht » Tab: Inhalt » Tab: Reiner Text* an der gewünschten Stelle ein.
. *Speichere* die Einstellungen.

[TIP]
.Template-Variable *{%Link_Checkout()%}* einfügen
====
Alle E-Mails an deine Kunden sollten unbedingt die Variable *{%Link_Checkout()%}* enthalten, damit Kunden jederzeit mit einem Klick auf diese URL in den Bereich *Mein Konto* deines Webshops gelangen können. In diesem Bereich kann ein Kunde u.a. seine Daten aktualisieren, seine Auftragshistorie einsehen, weitere Artikel zur Bestellung hinzufügen und den Status seiner Bestellung verfolgen.
====

////
=== Dateien an E-Mail-Vorlagen anhängen

Du kannst zwei Arten von Dateien an deine E-Mail-Vorlagen anhängen: einen PDF-Anhang und einen Dokumentenanhang. Was der Unterschied dieser beiden Anhänge ist, wird im Folgenden beschrieben.

Die möglichen Anhänge eines PDF-Anhangs, z.B. Rechnung, sind in deinem plentymarkets System vorgegeben. Diese Dokumente richtest du im Menü *System » Mandant » Mandant wählen » Standorte » Deutschland (Standard) » Dokumente* ein.

Ein Dokumentenanhang kann z.B. ein Artikelprospekt, eine Anleitung oder eine Fotodatei sein. Du lädst diese Dateien im Menü *CMS » Dokumente* hoch.

==== PDF-Anhang erstellen und anhängen

Die Dokumente, die du als PDF-Anhang versendest, werden automatisch vom System erzeugt. Ein Beispiel für ein solches Dokument ist die Rechnung.

Die Einrichtung erfolgt in drei Schritten. Erstens erstellst du eine Dokumentvorlage auf deinem Rechner, z.B. eine Geschäftsbriefvorlage inklusive Logo, und speicherst diese als PDF-Datei. Zweitens passt du die Einstellungen des Dokuments im Menü *System » Aufträge » Dokumente* an. Drittens wählst du den PDF-Anhang für die E-Mail-Vorlage.

[.instruction]
Dokument bearbeiten:

. Öffne das Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente*.
. Wähle das Dokument, das du bearbeiten möchtest, z.B. *Rechnung*.
. Wähle eine *Sprache* aus der Dropdown-Liste, z.B. *de* für Deutsch.
. Nimm im Tab *Vorlage* die Einstellungen vor.
. Wechsele in das Tab *PDF-Vorlage » Vorlage hinzufügen*.
. Wähle ggf. eine *Zahlungsart*.
. Klicke auf *Vorlage auswählen*.
. Öffne die zuvor erstellte PDF-Dokumentvorlage.
. *Speichere* die Einstellungen.
. Klicke auf *Vorschau*, um eine Vorschau des Dokuments anzeigen zu lassen.

[.instruction]
PDF-Dokument mit einer E-Mail-Vorlage verknüpfen:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Öffne die E-Mail-Vorlage.
. Wähle in der Dropdown-Liste *PDF-Anhang* die Datei, die du als Anhang verwenden möchtest.
. *Speichere* die Einstellungen. +
→ Die Datei wird als Anhang gesichert.

==== Dokumentenanhang erstellen und anhängen

Alle Dokumente, die du über eine E-Mail-Vorlage als Dokumentenanhang versenden möchtest, müssen vorher im System hochgeladen werden. Ein Beispiel für ein solches Dokument sind die AGB, da dieses Dokument häufig als Anhang der Eingangsbestätigung einer Bestellung versendet wird – vorausgesetzt du hast die AGB nicht über die Template-Variable *$GeneralTermsConditionsText* direkt in der Vorlage eingefügt.

Das Einrichten erfolgt in zwei Schritten. Zunächst lädst du das Dokument im Menü *CMS » Dokumente* hoch. Dann verknüpfst du das Dokument mit einer E-Mail-Vorlage. Gehe dazu wie im Folgenden beschrieben vor.


[.instruction]
Dokument hochladen:

. Öffne das Menü *CMS » Dokumente*.
. Klicke im Tab *Upload* auf *Datei auswählen*.
. Wähle die *Datei*, die du hochladen möchtest, und klicke auf *Öffnen*.
. Wähle eine der Optionen unter *Berechtigung*. +
→ Mit der Berechtigung legst du fest, ob das Dokument nur für *Mitarbeiter*, nur für *Kunden* oder *öffentlich*, also für alle Besucher des Webshops, verfügbar sein soll.
. Gib ggf. einen *Ordnernamen* ein.
. *Speichere* die Einstellungen.

[.instruction]
Dokument mit einer E-Mail-Vorlage verknüpfen:

. Öffne das Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Wähle bei der E-Mail-Vorlage in der Dropdown-Liste *Dokumentenanhang* die Datei, die du als Anhang versenden möchtest.
. *Speichere* die Einstellungen. +

////

== Vertragsdaten ändern

Im Menü *Start » Service-Center » Tab: Vertrag* kannst du Informationen zu deinem laufenden plentymarkets Vertrag einsehen. Öffne dieses Menü, um Änderungen an deinem Vertrag vorzunehmen.

[.instruction]
Vertragsdaten ändern:

. Öffne das Menü *Start » Service-Center*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links in deinem Backend.
. Klicke auf *Service-Center*. +
→ Das Service-Center wird in einem neuen Browser-Tab geöffnet.
. Melde dich mit deinen Zugangsdaten im Mein Konto-Bereich an. +
→ Die verfügbaren Tabs werden eingeblendet.
. Wechsele in das Tab *Vertrag*.
. Nimm die Änderungen vor.
. *Speichere* die Einstellungen.

== Domain bestellen

Der Begriff "Domain" bezeichnet eine Internetadresse in Form eines Namens sowie einer Erweiterung, der Top-Level-Domain, z.B. *.de*. Du kannst den Namen frei wählen. Eine Domain ist einmalig und darf weltweit nicht doppelt vorkommen. Bei der Registrierung der Domain, zum Beispiel bei einem Hosting-Dienstleister, wird daher geprüft, ob eine gewünschte Domain noch nicht vergeben ist.

Gehe wie im Folgenden beschrieben vor, um eine Domain zu bestellen und die Kontaktdaten des Domain-Inhabers zu speichern, das sogenannte Domain Handle. Du erhältst anschließend Informationen über die monatlichen Kosten der Nutzung. Nachdem du die Kontaktdaten eingegeben hast und das plentymarkets System zugeordnet wurde, bestellst du die Domain mit einem Klick auf *Zahlungspflichtig bestellen*.

[.instruction]
Domain bestellen:

. Öffne das Menü *Start » Service-Center*. +
→ Das Service-Center wird in einem neuen Browser-Tab geöffnet.
. Klicke auf das blaue Plus des Systems. +
→ Die verfügbaren Tabs werden eingeblendet.
. Wechsele in das Tab *Domain*.
. Klicke auf *Neue Domain bestellen*.
. Gib den gewünschten Domain-Namen ein.
. Wähle die Top-Level-Domain aus der Dropdown-Liste.
. Klicke auf *Prüfen*. +
→ Das System prüft, ob die Domain verfügbar ist.
. Klappe die Domain-ID auf.
. Klicke auf *Domain-Handle*.
. Gib die Kontaktdaten des Domain-Inhabers ein.
. *Speichere* die Einstellungen.

== SSL-Zertifikat bestellen

Ein SSL-Zertifikat dient dazu, deine Website zu verschlüsseln und gewährleistet eine sichere Verbindung zu deinem Online-Shop. Wenn du ein SSL-Zertifikat verwendest, ist deine Website über _https_ erreichbar.

Wichtig ist, dass die Domain, für die du das SSL-Zertifikat bestellen möchtest, eine im Service-Center aktivierte Hauptdomain ist.

Gehe wie im Folgenden beschrieben vor, um ein kostenpflichtiges SSL-Zertifikat zu bestellen.

[.instruction]
SSL-Zertifikat bestellen:

. Öffne das Menü *System » Mandant » Mandant wählen » SSL*. +
→ Das Zertifikat der Domain wird angezeigt.
. Klicke in der Zeile *Neues SSL bestellen für Domain:[Domain-Name]* rechts auf den Pfeil nach unten. +
→ Die für die Domain buchbaren SSL-Zertifikate werden angezeigt.
. Klicke in der Zeile des SSL-Zertifikats, das du buchen möchtest, auf *SSL bestellen*. +
→ Das SSL-Zertifikat wird bestellt. +
*_Hinweis:_* Es kann bis zu 2 Stunden dauern, bis das SSL-Zertifikat aktiviert ist.

== Checkliste

* [ ] E-Mail-Kontodaten: Hast du die E-Mail-Kontodaten im System eingegeben?
* [ ] Testmodus: Hast du den Testmodus aktiviert, damit alle E-Mails an den Administrator gesendet werden?
* [ ] E-Mail-Infodienst: Hast du den E-Mail-Infodienst aktiviert?
* [ ] E-Mail-Vorlagen: Enthalten alle E-Mail-Vorlagen die Variable *Link_Checkout()*?
* [ ] E-Mail-Vorlagen: Hast du in allen E-Mail-Vorlagen die Musterdaten mit deinen eigenen Kontaktdaten ergänzt?
* [ ] SSL-Zertifikat: Hast du ein SSL-Zertifikat gebucht?

== Mehr zum Thema

* <<crm/e-mails-versenden#100, E-Mail-Server-Zugangsdaten speichern>>
* <<crm/e-mails-versenden#1200, E-Mail-Vorlage erstellen>>
// * verlinken auf Automatisierungsseite von Denise <<schnelleinstieg/automatisierung#, Automatischer E-Mail-Versand>>
* <<crm/e-mails-versenden#, E-Mails versenden>>
* <<crm/newsletter-versenden#, Newsletter versenden>>
* <<crm/ticketsystem-nutzen#, Ticketsystem nutzen>>
* <<omni-channel/online-shop/ceres-einrichten#300, Rechtliche Angaben im Ceres-Webshop speichern>>
* <<basics/arbeiten-mit-plentymarkets/plentymarkets-konto#20, Vertragsdaten ändern>>
* <<basics/arbeiten-mit-plentymarkets/plentymarkets-konto#50, Domain-Daten verwalten>>
* <<basics/arbeiten-mit-plentymarkets/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat verwalten>>
