= Artikelkatalog aufbauen
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

Nun pflegst du deine Produkte ins System ein.

[#5]
== Vorbereitungen treffen

In plentymarkets werden einige Artikelinformationen zentral verwaltet und mit Varianten verknüpft. Deshalb musst du diese Daten im System speichern, bevor du Varianten erstellen kannst. Die folgenden Artikelinformationen müssen im System vorhanden sein, damit du Artikel und Varianten erstellen kannst:

* Kategorien
* Attribute
* Verkaufspreise

Hier erfährst du, wie du diese Informationen in plentymarkets speicherst.

[#10]
=== Kategorien erstellen

Mit Kategorien des Typs *Artikel* strukturierst du dein Produktsortiment und gestaltest deinen Webshop übersichtlich. Jeder Artikel muss mindestens einer Standardkategorie zugeordnet sein. Die Standardkategorie entscheidet darüber, in welcher Kategorie ein Artikel bei der Suche im Webshop gefunden und angezeigt wird.

Im Webshop Ceres kannst du dich für eine Kategorietiefe von 2 oder von bis zu 4 Ebenen entscheiden:

* 1 Hauptkategorie + 1 Unterkategorie
  ** In der Standard-Navigationsleiste wird unterhalb der Hauptkategorien maximal eine weitere Kategorieebene dargestellt.
* 1 Hauptkategorie + bis zu 3 Unterkategorien
  ** Über das Megamenü sind bis zu drei weitere Ebenen unterhalb der Hauptkategorien darstellbar.

[TIP]
.Kategoriestruktur planen
====
Überlege dir, welche Kategorien und Unterkategorien für deine Produkte sinnvoll sind. Welche Sortierung macht es deinen Kundinnen und Kunden leicht, sich in deinem Shop zurechtzufinden? Trage diese Informationen am besten zusammen, bevor du loslegst. Eine Baumstruktur zu skizzieren kann dir helfen, deine Produkte sinnvoll zu gruppieren.
====

Gehe wie unten beschrieben vor, um eine Hauptkategorie zu erstellen.

[.instruction]
Hauptkategorie erstellen:

. Öffne das Menü *Artikel » Kategorien*.
. Klicke links unten auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Gib einen Namen ein. +
*_Tipp:_* Die Option *Hauptkategorie* ist standardmäßig ausgewählt.
. Klicke auf *Erstellen*. +
→ Die Kategorie wird erstellt. +
→ Das Tab *Einstellungen* der Kategorie wird geöffnet. +
. Gib eine *Position* ein. Über die Position legst du die Reihenfolge fest, in der die Kategorien im Webshop angezeigt werden. Standardmäßig hat jede neue Kategorie, die du anlegst, die Position 0. +
*_Tipp:_* Positionsnummern in Zehnerschritten vergeben, damit neue Kategorien dazwischen eingefügt werden können.
. Aktiviere die *Mandanten (Shops)*, in denen die Kategorie verfügbar sein sollen.
. Gib einen *Mega-Titel* ein. +
*_Tipp:_* Der Meta-Titel wird im Tab des Browsers angezeigt.
. *Speichere* die Einstellungen. +
→ Die Kategorie wird erstellt. +
*_Hinweis:_* Die Kategorie wird erst im Webshop angezeigt, wenn mindestens ein für den Mandanten sichtbarer Artikel mit der Kategorie verknüpft ist.

Nun erstellst du eine Unterkategorie zu der Hauptkategorie, die du eben erstellt hast.

[.instruction]
Unterkategorie erstellen:

. Öffne das Menü *Artikel » Kategorien*.
. Klicke links unten auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Gib einen Namen ein. +
. Wähle die Option *Unterkategorie*.
. Klicke auf die Hauptkategorie, für die du die Unterkategorie erstellen möchtest. +
*_Tipp:_* Um eine Unterkategorie der dritten oder vierten Ebene zu erstellen, klicke in der Liste auf das Symbol der Hauptkategorie, um den Ordner zu öffnen. Öffne dann die Ordner der Unterkategorien auf die gleiche Weise, bis du die Kategorie erreichst, zu der du eine Unterkategorie erstellen möchtest.
. Klicke auf *Erstellen*. +
→ Die Kategorie wird erstellt. +
→ Das Tab *Einstellungen* der Kategorie wird geöffnet.
. Gib eine *Position* ein. Über die Position legst du die Reihenfolge fest, in der die Kategorien im Webshop angezeigt werden. Standardmäßig hat jede neue Kategorie, die du anlegst, die Position 0. +
*_Tipp:_* Positionsnummern in Zehnerschritten vergeben, damit neue Kategorien dazwischen eingefügt werden können.
. Aktiviere die *Mandanten (Shops)*, in denen die Kategorie verfügbar sein sollen.
. Gib einen *Mega-Titel* ein. Dieser Meta-Titel wird im Tab des Browsers angezeigt.
. *Speichere* die Einstellungen. +
→ Die Kategorie wird erstellt. +
*_Hinweis:_* Die Kategorie wird erst im Webshop angezeigt, wenn mindestens ein für den Mandanten sichtbarer Artikel mit der Kategorie verknüpft ist.


[TIP]
.Die neuen Kategorien werden nicht im Webshop angezeigt?
====
Wenn deine Kategorien nicht im Webshop angezeigt werden, hilft dir unsere <<artikel/best-practices#kategorien, Checkliste für die Kategoriesichtbarkeit im Webshop>> weiter.
====

[#20]
=== Attribute erstellen

Attribute dienen dazu, Varianten zu erstellen. Varianten sind verschiedene Ausführungen eines Artikels, die sich sehr ähnlich sind, sich aber in einer oder mehreren Eigenschaften unterscheiden. Typische solche Attribute sind zum Beispiel Farben und Größen. Damit du nicht für jedes Produkt einen eigenen Artikel erstellen musst, werden diese Eigenschaften in plentymarkets als <<artikel/artikel-verwalten#390, Attribute>> erstellt und einem Artikel zugeordnet. Unten wird beispielhaft beschrieben, wie du das Attribut *Farbe* erstellst.

[TIP]
.Beispiel
====
Ein Artikel soll in 3 Farben verkauft werden. Diese 3 Farbvarianten sollen für Kundinnen und Kunden bei der Bestellung wählbar sein. Statt 3 Artikel zu erstellen, wird ein Artikel mit drei Varianten erstellt. Die Varianten werden über Attributwerte gebildet.
====

[.instruction]
Attribut "Farbe" erstellen:

. Öffne das Menü *System » Artikel » Attribute*.
. Klicke auf *Neues Attribut*. +
→ Das Fenster *Neues Attribut* wird geöffnet.
. Gib einen *Namen (intern)* ein, z.B. *Farbe*. +
*_Tipp:_* Dieser interne Name ist im Webshop nicht sichtbar.
. *Speichere* die Einstellungen. +
→ Das Attribut wird erstellt. +
→ Das Tab *Grundeinstellungen* des Attributs wird geöffnet.
. Wechsele in das Tab *Name*.
. Gib Namen für das Attribut in den Sprachen ein, die du in deinem Webshop verwendest. +
→ Dieser Name wird im Webshop angezeigt.
. *Speichere* die Einstellungen.
. Erstelle wie unten beschrieben Werte für das Attribut.

Nun erstellst du Attributwerte für das Attribut. Hier wird beispielhaft beschrieben, wie du den Wert "Grün" erstellst.

[.instruction]
Wert "Grün" für das Attribut "Farbe" erstellen:

. Wechsele in das Tab *Werte*.
. Klicke auf *Neuer Wert*. +
→ Das Fenster *Neuer Wert* wird geöffnet.
. Gib einen *Namen (intern)* ein, z.B. *Grün*. +
*_Tipp:_* Dieser interne Name ist im Webshop nicht sichtbar.
. *Speichere* die Einstellungen. +
→ Der Wert wird erstellt. +
→ Der Wert wird in der Liste angezeigt.
. Gib in der Spalte *Name* einen Namen für den Wert ein. +
*_Tipp:_* Standardmäßig wird der interne Name eingefügt. +
→ Dieser Name wird im Webshop angezeigt.
. *_Optional:_* Wenn du deine Produkte in mehreren Sprachen anbietest, wähle im Dropdown-Menü *Sprache anzeigen* die weiteren Sprachen.
. *_Optional:_* Gib in der Spalte *Name* einen Namen für den Wert in dieser Sprache ein. +
→ Dieser Name wird später im Webshop angezeigt.
. *Speichere* die Einstellungen.

// Als Beispiel oder allgemein formulieren? Also "Farbe" oder "Attribut"?


[#30]
=== Verkaufspreis anpassen

Du kannst beliebig viele Verkaufspreise erstellen und sie mit Varianten verknüpfen. In deinem System ist bereits der Verkaufspreis *Preis* vorhanden, damit du möglichst schnell Artikel verkaufen kannst. Prüfe die Einstellungen des Verkaufspreises *Preis*, bevor du Varianten damit verknüpfst. Passe die Einstellungen des Verkaufspreises bei Bedarf an. Gehe dazu wie unten beschrieben vor.

[.instruction]
Verkaufspreis "Preis" anpassen:

. Öffne das Menü *System » Artikel » Verkaufspreise*. +
→ Eine Liste der Verkaufspreise wird angezeigt.
. Klicken Sie auf den Verkaufspreis *Preis*. +
→ Der Verkaufspreis wird geöffnet.
. Prüfe die Einstellungen des Verkaufspreises. Beachte dazu die Erläuterungen in <<tabelle-verkaufspreis-erstellen>>.
. *Speichere* die Einstellungen.

[[tabelle-verkaufspreis-preis-anpassen]]
.Verkaufspreis *Preis* anpassen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Interner Name*; +
*Externer Name*
|Standardmäßig heißt der Verkaufspreis auf Deutsch *Preis* und auf Englisch *Price*. Im Tab *Sprache* passt du die Namen bei Bedarf an. Dort kannst du auch Übersetzungen des Namens in weiteren Sprachen eingeben. +
_Tipp:_* Der externe Name wird im Webshop angezeigt.

|*Währung*
|Standardmäßig sind alle Währungen aktiviert. Schränke den Verkaufspreis bei Bedarf auf bestimmte Währungen ein.

|*Mandant*
|Standardmäßig sind alle Mandanten aktiviert. Schränke den Verkaufspreis bei Bedarf auf bestimmte Mandanten ein.

|*Land*
|Standardmäßig sind alle Länder aktiviert. Schränke den Verkaufspreis bei Bedarf auf bestimmte Länder ein.

|*Herkunft*
|Standardmäßig sind mehrere Herkünfte aktiviert, die du benötigst, um Artikel im Webshop zu verkaufen.
|====

[#40]
== Artikelkatalog aufbauen

Du hast nun die folgenden Artikelinformationen hinterlegt, die du benötigst, um deine Produkte in plentymarkets abzubilden:

* Kategorien
* Attribute
* Verkaufspreis

Nun pflegst du deine eigenen Artikel in plentymarkets ein. Je nachdem, mit wie vielen Artikeln du starten möchtest und wie du Artikeldaten bisher verwaltest hast, hast du zwei Möglichkeiten, Artikeldaten ins System zu bringen:

* Artikel manuell erstellen +
*_Tipp:_* Nachdem du den ersten Artikel erstellt hast, kannst du diesen Artikel kopieren und diese Kopie anpassen, um schneller zu arbeiten.
* In einer CSV-Datei gespeicherte Artikeldaten importieren +
*_Tipp:_* Auch wenn du die Artikel importierst, solltest du vorher mindestens einen Beispielartikel manuell erstellen, um die Artikelstruktur kennenzulernen. Denke daran, diesen Beispielartikel vor dem Importieren zu löschen.

In beiden Fällen solltest du dich zunächst mit der Artikelübersicht und der Artikelstruktur vertraut machen.

[#50]
=== Artikelübersicht verstehen

Im Menü *Artikel » Artikel bearbeiten* werden alle Artikel und Varianten aufgelistet. In dieser Artikelübersicht kannst du Artikel und Varianten suchen, bearbeiten und neue Artikel erstellen.

In der Spalte links findest du Filter, um die Artikelsuche einzugrenzen. Zum Einstieg ist vor allem der Filter *Aktiv* wichtig. Mit diesem Filter legst du fest, ob in der Liste der Artikel nur Artikel und Varianten angezeigt werden, die für einen Webshop aktiviert sind. Standardmäßig ist dieser Filter auf *Ja* eingestellt. Das wird dir später, wenn du viele Artikel und Varianten hast, helfen, deine Artikel schneller zu bearbeiten. Am Anfang kann es aber verwirrend sein, denn Artikel, die nicht aktiv sind, werden nicht gefunden, wenn du auf *Suchen* klickst, ohne vorher den Filter auf *Nein* oder *Alle* zu setzen.


[#60]
=== Beispielartikel verstehen

Dein plentymarkets System enthält einige Beispielartikel und Beispielvarianten. Diese Beispieldaten helfen dir, dich mit der Struktur von Artikeln und Varianten vertraut zu machen, bevor du eigene Daten einpflegst.

Anhand dieser Beispielartikel werden wir dir kurz die Artikelstruktur erklären.

[#65]
==== Beispielartikel anzeigen

[.instruction]
Beispielartikel anzeigen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke in der Spalte links oben auf *Suchen*. +
→ Die Beispielartikel werden in der Artikelübersicht angezeigt.
. Öffne einen beliebigen Artikel. +
→ Das Tab *Einstellungen* der Hauptvariante des Artikels wird geöffnet.
. Klicke dich durch alle Tabs und mache dich mit den Einstellungen vertraut.
. Öffne nun die folgenden Artikel:
  * Den Einzelartikel "Sessel Floating Water", Artikel-ID 123
  * Den Variantenartikel "Zweisitzer Paradise Now", Artikel-ID 132
. Klicke dich auch hier durch die Tabs des Artikels und der Varianten. +
→ <<tabelle-beispielartikel>> stellt die beiden Artikel gegenüber.



[[tabelle-beispielartikel]]
.Einzel- und Variantenartikel
[cols="1,3,3"]
|====
| |Einzelartikel |Variantenartikel

|Artikel-ID
|123
|132

|Name 1
|Sessel Floating Water
|Zweisitzer Paradise Now

|ID der Hauptvariante
|1021
|1030

|Hauptvariante kaufbar
|Ja +
*_Tipp:_* Bei Einzelartikeln sollte das Produkt der Hauptvariante entsprechen.
|Nein +
*_Tipp:_* Bei Variantenartikeln sollte die Hauptvariante kein verkaufbares Produkt sein. Die Hauptvariante sollte nur dazu dienen, die anderen Varianten des Artikels per Vererbung mit Daten zu versorgen.

|ID der Varianten
|--
|1065 - rot +
1066 - weiß

|Hersteller
|A & C Design
|Exclusive Leather

|Verkaufspreis
|Preis +
UVP
|Preis +
UVP +
*_Tipp:_* Die Preise werden nicht von der Hauptvariante an die Varianten vererbt.

|Kategorie
|Wohnzimmer » Sessel & Hocker
a|Wohnzimmer » Sofas +
*_Tipp:_* Die Kategorie wird von der Hauptvariante an die Varianten vererbt.

. Verknüpfe für die Variante 1065 eine weitere Kategorie. +
→ Die bisher vererbte Kategorie wird direkt an der Variante gespeichert. +
→ Die Vererbung wird deaktiviert.
. Klicke auf *Vererbung aktivieren*. +
→ Die Kategorie, die du verknüpft hast, wird entfernt. +
→ Die Kategorie der Hauptvariante wird übernommen.

|Attributauswahlkombination +
(Attribut:Attributwert)
|-- +
*_Tipp:_* Mit dem Einzelartikel ist kein Attribut verknüpft.
|1030 - keine
1065 - Couch color:rot +
1066 - Couch color:white +
*_Tipp:_*  Mit der Hauptvariante ist kein Attribut verknüpft.

|Mandant (Shop)
|Standard Shop
|Standard Shop +
*_Tipp:_* Der Mandant wird von der Hauptvariante an die Varianten vererbt.
|====


[#90]
=== Beispielartikel löschen

Nachdem du dir die Beispielartikel angesehen hast, haben sie ihre Schuldigkeit getan und du kannst sie löschen. Damit stellst du sicher, dass du von Anfang an ein sauberes System ohne unnötige Daten hast. Am schnellsten löschst du die Beispielartikel mit der Gruppenfunktion.

[.instruction]
Beispielartikel per Gruppenfunktion löschen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Stelle den Filter *Aktiv* auf *ALLE*.
. Klicke auf *Suchen*. +
→ Alle im System gespeicherten Artikel werden angezeigt.
. Klicke in der Spaltenüberschrift der Liste ganz oben links auf das Kontrollkästchen, um alle angezeigten Artikel zu markieren.
. Klicke auf *Artikel-Gruppenfunktion*. +
→ Das Fenster *Artikel-Gruppenfunktion* wird geöffnet.
. Aktiviere die Option *Artikel löschen*.
. Klicke auf *Ausführen*. +
→ Alle Artikel werden aus dem System gelöscht.


[#100]
=== Artikel manuell erstellen

Nun ist es so weit: Du erstellst deinen ersten verkaufsbereiten Artikel. Damit du möglichst schnell loslegen kannst, beschreiben wir nur die Einstellungen, die du vornehmen musst, damit der Artikel im Webhshop verkauft werden kann.

[.instruction]
Artikel manuell erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet.
. Wähle den Artikeltyp *Standard*.
. Gib einen Namen ein.
. Gib den Inhalt als Zahl ein.
. Wähle für diesen Inhalt eine Einheit aus der Dropdown-Liste.
. Klicke auf die Kategorie. +
→ Diese Kategorie wird als Standardkategorie mit der Hauptvariante des Artikels verknüpft.
. Gib einen *Preis* ein. +
. *Speichere* die Einstellungen. +
→ Der Artikel wird erstellt. +
→ Eine Hauptvariante wird erstellt. +
→ Das Tab *Global* des Artikels wird geöffnet.
. Nimm bei Bedarf weitere Einstellungen vor. Beachte dazu die Erläuterungen in <<einstellungen-artikel-bearbeiten>>. +
*_Tipp:_* Die in <<einstellungen-artikel-bearbeiten>> beschriebenen Einstellungen beziehen sich auf verschiedene Tabs im Bearbeitungsfenster des Artikels. Das Tab wird in einer eigenen Zeile als Zwischenüberschrift angezeigt.
. *Speichere* die Einstellungen.

[[einstellungen-artikel-bearbeiten]]
.Artikeleinstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|plentymarkets kann automatisch eine fortlaufende Nummer vergeben (empfohlen). +
Alternativ kannst du beim Erstellen eines Artikels eine eigene Artikel-ID vergeben. Die ID darf nur aus Zahlen bestehen. Jede ID darf nur einmal vergeben werden.

2+|Tab: Global

|*Versandprofile*
|Das Versandprofil *DHL* aktivieren. Standardmäßig ist kein Versandprofil aktiviert. +
*_Hinweis:_* Pro Artikel muss mindestens ein Versandprofil aktiviert werden, da sonst ungewollte Effekte bei der Versandkostenberechnung auftreten können.

2+|Tab: Varianten-ID » Einstellungen

|*Aktiv*
|Artikel aktivieren. Artikel werden erst im Webshop angezeigt, wenn sie aktiv sind. +
*_Hinweis:_* Bei der Artikelsuche im Menü *Artikel bearbeiten* werden inaktive Artikel mit den Standardeinstellungen der Suche nicht angezeigt. Im Filter *Aktiv* die Option *Nein* wählen, um nach inaktiven Artikeln zu suchen.

|*Verfügbarkeit*
|Verfügbarkeitsstufe wählen. +
*_Tipp:_* Du bist gesetzlich verpflichtet, Verbraucherinnen und Verbraucher über die Lieferfristen deiner Produkte zu informieren. Im Menü *System » Artikel » Verfügbarkeit* sind Standardtexte für 5 Verfügbarkeitsstufen gespeichert. Passe diese Texte bei Bedarf an.

|*Verkaufspreis*
|Verkaufspreis *Preis* hinzufügen und einen Preis eingeben.

|*Barcode*
|Barcode hinzufügen und Code eingeben.

|*ASIN/ePID*
|ASIN/ePID hinzufügen und ASIN bzw. ePID eingeben.

|*Gewicht brutto*; +
*Gewicht netto*
|Angabe in Gramm oder Kilogramm. +
*_Hinweis:_* Diese Angaben sind unbedingt erforderlich, wenn die Versandkosten auf Basis des Gewichts berechnet werden.

|*Umsatzsteuer*
|Umsatzsteuersatz des Produkts wählen. +
*_Tipp:_* Die Umsatzsteuersätze werden im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung* gepflegt.

2+|Tab: Varianten-ID » Verfügbarkeit

|*Mandant (Shop): Verfügbar*
|Den oder die Mandanten (Shops) aktivieren, in denen die Variante verfügbar sein soll.

2+|Tab: Texte

|*Name 1*
|Einen Namen für den Artikel eingeben. +
*_Tipp:_* Dieser Name wird im Webshop angezeigt.

|*Artikeltext*
|Artikeltext eingeben. Der Artikeltext ist eine detaillierte Produktbeschreibung, die in der Artikelansicht im Webshop angezeigt wird.
|====

[#110]
==== Varianten manuell erstellen

Du hast nun deinen ersten Artikel erstellt. Beim Erstellen eines neuen Artikels wird immer eine Hauptvariante erstellt. Eine Hauptvariante kann nicht gelöscht werden. Nun erfährst du, wie du eine oder mehrere Varianten erstellst.

[TIP]
.Vererbung
====
Wenn du Varianten erstellst, erben diese Varianten standardmäßig die vererbbaren Einstellungen der Hauptvariante:

* Verfügbarkeitseinstellungen
* Verkaufspreis und Preis
* Kategorie
* Lieferant
* Lager
* Mandantenverfügbarkeit

Du kannst die Vererbung aber auch an der Variante selbst deaktivieren und für jede Variante eigene Daten speichern.
====

[.instruction]
Eine oder mehrere Varianten erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Varianten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neue Variante erstellen* wird geöffnet.
. Gib den Inhalt als Zahl ein.
. Wähle für diesen Inhalt eine Einheit aus der Dropdown-Liste.
. Wähle ein oder mehrere Attribute. +
→ Unter *Kombinationen* wird angezeigt, wie viele Varianten erstellt werden.
. Klicke auf *Varianten erstellen*. +
→ Die Varianten werden erstellt. +
→ Die Varianten werden in der Variantenübersicht angezeigt. +
*_Tipp:_* Die vererbbaren Einstellungen werden von der Hauptvariante an die Varianten vererbt.


[TIP]
.Artikel kopieren
====
Wenn sich deine Artikel ähnlich sind, kannst du bei der Artikelerstellung Zeit sparen, indem du Artikel kopierst und anpasst. Klicke dazu in der obersten Zeile des Artikels auf das Symbol *Kopieren*.
====


[#120]
=== Artikel und Varianten importieren

Wenn du sofort eine größere Menge Artikeldaten importieren möchtest, ist das natürlich auch kein Problem. Dazu benötigst du eine CSV-Datei mit den Artikeldaten, die auf deinem Rechner gespeichert ist.

[TIP]
.Vor dem Import manuell einen Beispielartikel erstellen
====
Auch wenn du die Artikel importierst, solltest du vorher mindestens einen Beispielartikel manuell erstellen, um die Artikelstruktur kennenzulernen. Denke daran, diesen Beispielartikel vor dem Importieren zu löschen.
====


[#130]
==== Importdaten prüfen

Prüfe vor dem Import, ob im System die folgenden Daten gespeichert sind:

* Kategorien
* Attribute
* Verkaufspreise

[#140]
==== Sync für Artikelimport erstellen

////
* Beispieldatei: (link)
* Erklären, welche Spalte welche Daten enthalten muss.
////

[.instruction]
Sync für Artikelimport erstellen:

. Öffne das Menü *Daten » ElasticSync Beta*.
. Klicke auf *Sync hinzufügen*. +
→ Der Bearbeitungsbereich *Neuer Sync* wird angezeigt.
. Gib in das Feld *Namen* die Bezeichnung *Initialer Artikelimport* ein.
. Wähle den Typ *Artikel* aus der Dropdown-Liste.
. Wähle aus der Dropdown-Liste *Quelle* die Option *HTTP*.
. Wähle aus der Dropdown-Liste *HTTP-Optionen* die Option *Datei-Upload*.
. Klicke im Feld *URL* auf das Dreipunktmenü. +
. Klicke im angezeigten Fenster auf *Datei hochladen*.
. Wähle in der Ordnernavigation die Importdatei.
. Kicke auf *Öffnen*. +
→ Die Datei wird hochgeladen.
. Klicke mit der Maus auf die Datei in der Liste, um sie zu markieren.
. Klicke auf *Wählen*. +
→ Die Datei wird für den Import vorgemerkt.
. *Speichere* die Einstellungen. +
→ Der Sync wird erstellt. +
→ Die Abgleicheinstellungen des Syncs werden geöffnet.

[[tabelle-sync-erstellen]]
.Sync für Artikelimport erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Zeichensatz*
|Den Zeichensatz der Datei oder die Option *Automatisch erkennen* wählen.
// Umlaute? oder ist *Automatisch* immer OK?

2+|*Trennzeichen*

|*Trennzeichen*
|Das Trennzeichen wählen, das in der Importdatei verwendet wird, um die Datenfelder (Spalten) eines Datensatzes voneinander zu trennen. +
Mögliche Trennzeichen sind *Semikolon*, *Komma*, *Tabulator* oder *Pipe*.

|*Feldbegrenzungszeichen*
|Die Begrenzungszeichen innerhalb von Feldern wählen, die mehrere Werte enthalten. +
*"* = Die einzelnen Werte innerhalb eines Felds sind durch doppelte Anführungszeichen voneinander getrennt. +
*'* = Die einzelnen Werte innerhalb eines Felds sind durch einfache Anführungszeichen voneinander getrennt.
|====


[#150]
==== Sync-Einstellungen vornehmen

Nachdem du den Sync erstellt hast, speicherst du nun Informationen darüber, wie die Daten in deiner Importdatei aufgebaut sind. Außerdem ordnest du die Daten in der Importdatei den Datenfeldern in plentymarkets zu. Mit Zuordnen meinen wir, dass du plentymarkets sagst, die Daten welcher Spalten der Datei in welche Datenfelder in plentymarkets importiert werden sollen.

[.instruction]
Sync-Einstellungen vornehmen:

. Öffne das Menü *Daten » ElasticSync*.
. Klicke in der Sync-Übersicht auf den Sync.
. Klicke auf *Abgleich*. +
*_Tipp:_* Da du komplett neue Artikeldaten importierst, sind im Bereich *Abgleich* keine Einstellungen nötig.
. Nimm die Einstellungen im Bereich *Importoptionen* vor. Beachte dazu die Erläuterungen in <<tabelle-Sync-Importoptionen>>.
. *Speichere* die Einstellungen.
. Klicke links in der Liste auf *Zuordnung*.
. Gib den Namen *Initialer Artikelimport* ein.
. *Speichere* die Einstellungen. +
→ Pro Spalte der Importdatei wird ein Feld *Quelle* angezeigt. +
*_Tipp:_* In der Spalte *Importdaten* werden die Daten aller Felder der Importdatei mit einer Vorschau der Daten angezeigt.
. Prüfe die Daten in der Spalte *Vorschau*. +
→ Wurden die Daten korrekt erkannt oder müssen die Importeinstellungen noch einmal angepasst werden?
. Wähle nun in der Spalte *plentymarkets Datenfelder* in jeder Zeile ein Datenfeld in plentymarkets als Ziel aus der Dropdown-Liste. Beachte dazu die Erläuterungen in <<tabelle-Sync-Importoptionen>>.
. Aktiviere nun in der Spalte ganz links die Zuordnungen, die beim Import berücksichtigt werden sollen. +
*_Tipp:_* In der Spalte *Importdaten* ganz oben kannst du auch alle Zuordnungen gleichzeitig aktivieren.
. *Speichere* die Einstellungen.
. Klicke in der Symbolleiste auf *Sync ausführen*. +
→ Die Artikeldaten werden importiert.
. Wechsele in das Menü *Artikel » Artikel bearbeiten*.


*_Tipps:_*

* Du kannst den Inhalt jeder Spalte auch in mehrere Datenfelder von plentymarkets importieren.
// Beispiel

* Du kannst auch als Quelle für die Importdaten die Option *Eigener Wert* wählen und einen Text/eine Zahl in das Feld *Quelle* eingeben. Dieser Text/diese Zahl wird dann für alle Artikel in das Feld in plentymarkets importiert, das du als Ziel wählst.
// Beispiel

[[tabelle-Sync-Importoptionen]]
.Importoptionen für den initialen Artikelimport
[cols="1,2"]
|====
|Option |Erläuterung

2+|Abgleich

|Abgleicheinstellungen
a|Wir beschreiben hier, wie du Artikeldaten in ein neu gebuchtes System importierst. Deshalb musst du im Bereich *Abgleich* keine Einstellungen vornehmen. Allerdings kannst du diesen Sync nur einmal verwenden. Erstelle daher nach dem initialen Artikelimport einen neuen Sync, in dem du festlegst, welche Abgleichfelder bei weiteren Importen verwendet werden sollen.

2+|Importoptionen

|*Wenn keine Daten gefunden wurden*
a|Option *Neue Daten importieren, vorhandene aktualisieren* wählen.

|*Dezimalzahl*
a|Wählen, wie Dezimaltrennzeichen in der Importdatei verwendet werden. +
*Deutsche Schreibweise* = Dezimalzahlen werden kommasepariert angegeben. Ein Punkt dient als Tausendertrennzeichen. +
*Englische Schreibweise* = Dezimalzahlen werden punktsepariert angegeben. Ein Komma dient als Tausendertrennzeichen.

|*Datumsformat*
|Datumsformat eingeben, das in der Importdatei verwendet wird. Wenn die Datumsangaben in der Datei dem Standardformat Y-m-d H:i:s entsprechen, kann das Feld leer bleiben. Andere Formate müssen eingetragen werden. Zulässig sind alle link:http://php.net/manual/de/function.date.php[php-konformen Datumsformate^].

2+|Zuordnung

|Zuordnungsfelder
|*Varianten / Nummer der Hauptvariante* = Wenn in diesem Feld die Nummer einer Hauptvariante steht, wird statt eines Einzelartikels eine Variante erstellt. +
*Varianten / Variantennr.* = Die Nummer der Variante +
*Artikelbeschreibung / Name* = Der Name der Variante, der im Webshop angezeigt wird. +
→ In der Dropdown-Liste rechts die Sprache wählen, in der der Name in der Datei gespeichert ist. +
*Barcodes / Code* = Der Barcode der Variante (GTIN etc.). +
→ In der Dropdown-Liste rechts den Barcode-Typ wählen, den die Spalte enthält. +
*Artikelbeschreibung / Artikeltext* = Der Beschreibungstext der Variante. +
→ In der Dropdown-Liste rechts die Sprache wählen, in der der Beschreibungstext in der Datei gespeichert ist. +
*Artikel Bilder / URL* = Ein Link zu einem online verfügbaren Bild des Produkts +
*_Tipp:_* Um von Anfang an mehr als ein Bild pro Variante hochzuladen, stattdessen das Ziel *Multi-Url (kommasepariert)* wählen. +
*Variantenpreise / Preis* = Der Preis der Variante. +
→ In der Dropdown-Liste rechts den Verkaufspreis *Preis* wählen. +
*Bestand / Menge* = Die Stückzahl der Variante, die als Bestand importiert werden soll. +
*Attribute / Attributauswahlkombination* = Die Attributwerte, die mit der Variante verknüpft werden sollen. +
→ In der Dropdown-Liste rechts das Format wählen. +
*Standardkategorien / ID der Kategorie* = Die Standardkategorie, die mit der Variante verknüpft werden soll. +
→ In der Dropdown-Liste rechts den Mandanten *Standard Shop* wählen.
|====


[#160]
=== Verfügbarkeitsanzeige automatisieren

Der Bestand und damit die Verfügbarkeit von Artikeln ändert sich ständig. Die Verfügbarkeitsangaben manuell zu pflegen ist daher sehr aufwendig. Natürlich kannst du anfangs den Verfügbarkeitsstatus deiner Artikel manuell aktualisieren. Dennoch solltest du die Pflege der Verfügbarkeitsanzeige im Webshop so bald wie möglich automatisieren, wenn du den Warenbestand mit plentymarkets verwaltest. Im Webshop werden dann die Symbole *lieferbar* und *nicht lieferbar* automatisch nach dem aktuellen Warenbestand angezeigt. Alternativ kannst du Artikel ohne Warenbestand auch ganz ausblenden und wieder einblenden, sobald neuer Bestand im Lager gebucht wird.

[.instruction]
Verfügbarkeitsanzeige automatisieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel. +
→ Das Tab *Einstellungen* der Hauptvariante wird geöffnet.
. Wähle im Bereich *Verfügbarkeit* bei *Beschränkung* die Option *Auf Netto-WB*.
. Aktiviere im Bereich *Verfügbarkeit* die folgenden Optionen, damit die Lieferbarkeit automatisch anhand des Bestands angepasst wird: +
*Anzeige im Webshop: Automatisch verfügbar wenn Netto-WB positiv* +
*Anzeige im Webshop: Automatisch nicht verfügbar wenn kein Netto-WB*
. Aktiviere im Bereich *Verfügbarkeit* die folgenden Optionen, damit der Artikel nur im Webhshop angezeigt wird, wenn der Artikel Bestand hat: +
*Mandant: Automatisch sichtbar wenn Netto-WB positiv* +
*Mandant: Automatisch unsichtbar wenn kein Netto-WB*.
. *Speichere* die Einstellungen.
// Oder per Gruppenfunktion?

[#170]
== Artikelbilder speichern

Beim Import der Artikel hattest du die Möglichkeit, für online erreichbare Bilder eine URL anzugeben. Wenn deine Artikelbilder nicht online verfügbar sind, kannst du die Bilder wie hier beschrieben manuell speichern.

[#180]
=== Artikelbilder hochladen

// Auch importieren?

Im Tab <<artikel/artikel-verwalten#90, Bilder>> im Bearbeitungsfenster des Artikels speicherst du Bilder und verknüpfst diese Bilder mit den Varianten des Artikels. Pro Artikel sind bis zu 25 Bilder in den Formaten JPG/JPEG oder PNG möglich.

[TIP]
.FTP-Upload nutzen
====
Größere Bildmengen überträgst du am besten per <<artikel/artikel-verwalten#680, FTP-Upload>> auf den Server. Lies aber vorher die Hinweise zur Benennung der Bilddateien, damit die Bilder beim Hochladen den richtigen Artikeln und Varianten zugeordnet werden.
====

[.instruction]
Bilder für einen Artikel speichern:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Bilder* des Artikels.
. Ziehe neue Bilder per Drag & Drop-Funktion in den Bereich *Neues Bild einfügen*. +
*_Oder:_* Klicke auf *Dateien auswählen*.
. Wähle aus der Dropdown-Liste *Verfügbarkeit* die Mandanten und/oder Herkünfte, für die das Bild bereitgestellt werden soll.
. *Speichere* die Einstellungen.

[#190]
=== Bilder mit Varianten verknüpfen

// auch beim import erklären?

Verknüpfe nun die am Artikel gespeicherten Bilder mit einer oder mehreren Varianten. Gehe dazu wie unten beschrieben vor.

[.instruction]
Artikelbilder mit Varianten verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Bilder* des Artikels. +
→ Eine Vorschau der am Artikel gespeicherten Bilder wird angezeigt.
. Setze ganz links ein Häkchen bei den Bildern, die du mit einer oder mehreren der Varianten verknüpfen möchtest.
. Klicke am unteren Ende der Seite auf *Variantenverknüpfung*. +
→ Das Fenster *Varianten verknüpfen* wird angezeigt.
. Wähle die Varianten, die du mit den gewählten Bildern verknüpfen möchtes.
. Klicke auf *Verknüpfen*. +
→ Die Bilder werden mit den gewählten Varianten verknüpft.


[#200]
== Checkliste Artikelkatalog

Die Checkliste soll dir helfen, dient zur Prüfung der Artikeleinstellungen. Arbeiten Sie die Checkliste durch, nachdem Sie die zuvor beschriebenen Einstellungen zum Schnelleinstieg vorgenommen haben.

[%interactive]
[ ] Hast du den <<#350, Artikelkatalog>> mit allen Beschreibungstexten aufgebaut?
[ ] Hast du die <<#370, Artikelverfügbarkeit>> korrekt eingestellt?
// [ ] Hast du alle <<#350, Preise und Mehrwertsteuersätze>> nochmals geprüft?
// wir haben keine MwSt. erstellt //







// == Artikel aktivieren

// über Gruppenfunktion oder Stapelverarbeitung
// beschreiben

[#210]
== Mehr zum Thema Artikelkatalog aufbauen



* <<artikel/artikel-verwalten#680, Artikelbilder per FTP-Server hochladen>>
* <<basics/datenaustausch/ElasticSync/ElasticSync-beta#, Sync für weitere Importe erstellen>>
* <<artikel/artikelstruktur-kennenlernen#, Artikelstruktur verstehen>>
* <<artikel/kategorien-verwalten#, Kategorien erstellen>>
* <<artikel/artikel-verwalten#, Artikel verwalten>>
* <<artikel/multipacks-pakete-sets-verwalten, Sets, Multipacks und Pakete erstellen>>
* <<artikel/artikel-verwalten#350, Filtermöglichkeiten für Artikel und Varianten in der Artikelansicht>>
* <<artikel/artikel-verwalten#155, Mehrere Artikel per Stapelverarbeitung bearbeiten>>
* <<artikel/artikel-verwalten#155, Mehrere Artikel per Gruppenfunktion bearbeiten>>
* <<artikel/artikel-verwalten#330, Mehrere Varianten per Stapelverarbeitung bearbeiten>>
* <<artikel/artikel-verwalten#330, Mehrere Varianten per Gruppenfunktion bearbeiten>>

[TIP]
.Cross-Selling nutzen
====
Du möchtest deine Kundinnen und Kunden auf weitere interessante Produkte aufmerksam machen? Dann richte <<artikel/artikel-verwalten#950, Cross-Selling-Verknüpfungen ein>>.
====
