= Automatisierung
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

////
Früher Kapitel "Automatismen"

TO DO:

- Kapitel "Aufträge verwalten" neu schreiben und irgendwie sinnvoll machen --> wird auf Seite zu Auftragsabwicklung platziert.
- Ereignisaktionen aus dem Dokument "sytemeinrichtungsfragebogen" übernehmen und beschreiben
- Aktionsmanager aus dem Dokument "sytemeinrichtungsfragebogen" übernehmen und beschreiben
- Beispiele für Ereignisaktionen irgendwo anders platzieren
- auf Aktionsmanager nur verlinken (wenn du irgendwas zeitgesteuert machen möchtest, nutze den AM)
- Checkliste prüfen: Gehören alle Punkte zu diesem Thema?

////


In diesem Kapitel findest du Erläuterungen zu den Einstellungen, die du in plentymarkets zum Einrichten von Automatismen vornehmen solltest, bevor du mit dem System produktiv arbeitest. Dein plentymarkets System erledigt einige Aufgaben dann automatisch im Hintergrund.

plentymarkets bietet dir verschiedene Möglichkeiten zur Automatisierung deiner Arbeitsabläufe an:

* den automatischen E-Mail-Versand
* Ereignisaktionen, bei denen bestimmte Ereignisse im Webshop automatisch bestimmte Aktionen auslösen
* den Aktionsmanager über den du Ereignisse automatisch zu bestimmten Uhrzeiten ausführen lässt
////
Hinweis auf Prozesse ans Ende der Seite stellen
////
* die Prozesse. Dieses Funktion kannst du nur nutzen, wenn du das Tool plentyBase installiert hast und richtet sich an fortgeschrittene plentymarkets Nutzer. Daher werden Prozesse im Schnelleinstieg nicht näher beschrieben.

[#100]
== Automatischer E-Mail-Versand

Im Schritt <<schnelleinstieg-basiseinstellungen, Basiseinstellungen>> wurde beschrieben, wie du die E-Mail-Vorlagen für den automatischen Versand gestaltest. +
Im Menü *System » Mandant » Mandant wählen » E-Mail » Automatischer Versand* wählst du, in welchen Fällen eine bestimmte E-Mail-Vorlage verschickt werden soll. Damit die bereits bekannte E-Mail-Vorlage *Eingangsbestätigung Webshop-Bestellung* automatisch versendet wird, wenn eine Bestellung über Ihren Webshop eingegangen ist, wähle diese Vorlage in der Zeile *Auftragsbestätigung nach der Kaufabwicklung*. Du kannst in diesem Menü weitere spezifische Auftragsbestätigungen für Bestellungen, die z.B. über eBay, Amazon und andere Marktplätze generiert wurden, aktivieren. Außerdem kannst du hier eine E-Mail-Vorlage wählen, die dem Kunden auf Anfrage ein neues Passwort sendet und eine Bestätigung nach der Anmeldung zum Newsletter versendet. Mit *Erinnerung bei Kaufabbruch* und *Kundenregistrierung* stehen weitere Standardereignisse zur Auswahl, die du auf Wunsch mit einer E-Mail bedienen kannst. +
Du solltest hier nur solche E-Mail-Vorlagen wählen, die du bearbeitet und mit deinen eigenen Daten ergänzt hast. Belasse die Auswahl bei *kein Versand*, wenn keine E-Mail-Vorlage verschickt werden soll.

[IMPORTANT]
.Automatischer E-Mail-Versand vs. Ereignisaktionen
====

====


[#200]
== Ereignisaktionen einrichten

Das Tagesgeschäft eines Webshops ist von vielen Routineaufgaben geprägt. Die Bearbeitung der eingegangenen Aufträge ist ein komplexer Vorgang, der ein systematisches Vorgehen erfordert. Darüber hinaus möchten Ihre Kunden nach der Auftragsbestätigung noch weitere Informationen über den Status ihrer Bestellung per E-Mail erhalten.

plentymarkets bietet Ihnen im Menü <<basics/automatisierung/ereignisaktionen#, System » Aufträge » Ereignisse>> hierfür eine wirkungsvolle Möglichkeit, da Sie viele dieser Routineaufgaben automatisch ausführen lassen und Ihren Webshop damit äußerst effizient führen können.

Die Aktivierung einer Ereignisaktion gliedert sich in zwei Schritte: Zuerst konfigurieren Sie über verschiedene Filteroptionen ein Ereignis. Danach legen Sie fest, welche Aktionen vom System in diesem Fall auszuführen sind. Immer wenn dieses Ereignis in Zukunft eintritt, werden die gespeicherten Aktionen automatisch ausgeführt.

Im Folgenden finden Sie beispielhaft für die vielfältigen Möglichkeiten in plentymarkets vier Ereignisaktionen, die sich in der Praxis vieler Webshops bewährt haben.


////
die ereignisaktionen aus dem dokument "sytemeinrichtungsfragebogen" übernehmen und beschreiben.
Beispiel für EA automatischer Paketnummernimport/Versandbestätigung auf Best Practice Seite übernehmen. Für diese Seite ein besseres Beispiel beschreiben, z.B. zahlungsaufforderung bei Vorkasse.


Die folgende <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> wird beim Import der Paketnummer dem Kunden eine Versandbestätigung senden, den Status der Bestellung auf 7 setzen und zusätzlich den Warenausgang im Lager buchen, damit die physischen Lagerbestände aktualisiert werden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das *Ereignis* gemäß <<ereignisaktion-versandbestaetigung-automatisch-versenden>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<ereignisaktion-versandbestaetigung-automatisch-versenden>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[ereignisaktion-versandbestaetigung-automatisch-versenden]]
.Ereignisaktion zum automatischen E-Mail-Versand der Vorlage Versandbestätigung zur Bestellung
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Paketnummer*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*Zahlung per Vorkasse*

|*Aktion 1*
|*Auftrag &gt; Status ändern*
|*[7] Warenausgang gebucht*

|*Aktion 2*
|*Kunde &gt; E-Mail versenden*
|E-Mail-Vorlage; Empfänger

|*Aktion 3*
|*Auftrag &gt; Warenausgang buchen*
|
|====

[TIP]
.E-Mail-Vorlage und Empfänger wählen
====
Wählen Sie im oberen Auswahlfeld die E-Mail-Vorlage und im unteren Auswahlfeld den Empfänger der E-Mail. Wählen Sie danach ggf. weitere E-Mail-Vorlagen und Empfänger. Wird *Kunde* als Empfänger eingestellt, erhalten alle Kunden, die den Filterkriterien entsprechen, die E-Mail. Wird *Lager* eingestellt, erhält die Kontaktperson für das Lager die E-Mail. Wird ein bestimmter Benutzer eingestellt, erhält der eingestellte Benutzer Ihres plentymarkets Systems die E-Mail.
====

Fast alle Versanddienstleister bieten ihren Kunden mittlerweile die Sendungsverfolgung per Internet an. Sie haben bei der Einrichtung Ihrer Versanddienstleister bereits eine Tracking-URL gespeichert. Mit der Eingabe der Paketnummer verfügt Ihr plentymarkets System nun über alle nötigen Informationen, um Ihrem Kunden eine Tracking-URL zur Verfolgung seines Paketes zu senden. Nutzen Sie diese Option und überzeugen Sie sich davon, dass die E-Mail-Vorlage Ihrer Versandbestätigung die Variable *$TrackingURL* enthält. Testen Sie dann bei den ersten Aufträgen, ob die Tracking-URLs korrekt verarbeitet werden und dem Kunden die entsprechenden Informationen anzeigen.

[TIP]
.Tipp: Markierungen verwenden
====
Zur besseren Übersicht im Auftragsordner empfehlen wir Ihnen, Markierungen zu verwenden. Die Bedeutung der Markierungen müssen Sie selbst bestimmen und dann durchgängig verwenden. Sie könnten beispielsweise teilbezahlte Aufträge über die aktuelle Ereignisaktion mit der *Markierung 5* auszeichnen und würden dann später in der Auftragsübersicht diesen Status sofort wieder anhand der Markierung erkennen. Markierungen können manuell oder über eine Aktion des Aktionstyps *Markierung ändern* per Ereignisaktion gesetzt und verändert werden. Markierte Aufträge sind in den Ereignisaktionen und im übrigen System anhand dieser Markierungen auch selektierbar (Filteroptionen).
====
////


[#300]
== Aktionsmanager nutzen

Mit dem Aktionsmanager kann plentymarkets automatisch bestimmte Aktionen für Sie ausführen. Wir möchten Ihnen die Funktionsweise des Aktionsmanagers anhand zweier Praxisbeispiele erläutern. Dazu beschreiben wir im ersten Beispiel, wie Sie das automatische Abgeben von eBay-Bewertungen für ein verknüpftes eBay-Konto einrichten und im zweiten Beispiel, wie Sie das automatische Mahnwesen konfigurieren.


////
Aktionsmangager empfehlungen aus dem dokument systemeinrichtungsfragebogen übernehmen
////

////
Bewertungstexte für ebay auf BP-Seite ergänzen
[.instruction]
Bewertungstexte für eBay eingeben:

. Öffnen Sie das Menü *System » Märkte » eBay » Einstellungen*.
. Wechseln Sie in das Tab *Kontoeinstellungen*.
. Geben Sie im Bereich *Automatische Bewertungen* bis zu vier Bewertungstexte ein.
. *Speichern* Sie die Einstellungen.
////

[#400]
Verweis auf Prozesse

[#500]
== Checkliste

Die nachfolgende Checkliste dient zur Prüfung der Einstellungen. Arbeiten Sie die Checkliste durch, nachdem Sie die zuvor beschriebenen Einstellungen zum Schnelleinstieg vorgenommen haben. Diese Kontrolle gewährleistet die korrekte Funktionsweise Ihres plentymarkets Systems.

[%interactive]
* [ ] Konnten Sie die grundlegende Statuslogik bei der <<#760, Auftragsbearbeitung>> nachvollziehen?
* [ ] Haben Sie Ihre <<#770, E-Mail-Vorlagen>> bearbeitet, die Widerrufsbelehrung eingefügt sowie Ihre Bankverbindung und Kontaktdaten korrekt eingegeben?
* [ ] Wurde in der *Versandbestätigung zur Bestellung* die Tracking-URL korrekt eingegeben?
* [ ] Haben Sie wichtige Ereignisse mithilfe von <<#780, Ereignisaktionen>> oder des <<#830, Aktionsmanagers>> automatisiert?

[#600]
== Mehr zum Thema *Automatisierung*

////
ToDo: links einfügen
////
