= Webshop einrichten: Einleitung
:lang: de
include::{includedir}/_header.adoc[]
:position: 100
:url: schnelleinstieg/schnelleinstieg-webshop-einleitung

IMPORTANT: Hast du schon die Schnittstelle zu eBay eingerichtet? Noch nicht? Dann geht's hier zurück zum Schnelleinstieg zum Thema <<schnelleinstieg/schnelleinstieg-ebay#, eBay>>.

Nachdem du in den vorherigen Kapiteln deine Artikel angelegt und gegebenenfalls eine Schnittstelle zu eBay eingerichtet hast, schauen wir uns im Folgenden an, wie du deinen Kunden verschiedene Zahlungsmöglichkeiten anbieten und deinen Shop ansprechend gestalten kannst. Diese und andere Funktionalitäten werden in plentymarkets mit Hilfe von Plugins bereitgestellt.

Zu Beginn sind in deinem System noch keine Plugins installiert. Durchlaufe den Integrations-Assistenten, um einige grundlegende Erweiterungen zu installieren. Du findest ihn im Menü *System » Assistenten*.

Im Kontext des Schnelleinstiegs werden wir mit plentyShop Ceres, den Zahlungsarten PayPal und Vorkasse sowie DHL als Versanddienstleister arbeiten. Wenn deine Bedürfnisse davon abweichen, überspringe die entsprechenden nachfolgenden Kapitel.

Nach dem Abschließen des Integrations-Assistenten, öffne das Menü *Plugins » Plugin-Übersicht*.

[NOTE]
.Installationszeit
====
Das Installieren der Plugins kann einige Minuten dauern. Dass der Installationsprozess abgeschlossen ist, kannst du an dem Zeitstempel in der Plugin-Übersicht erkennen.
====

Auf der linken Seite siehst du deine Plugin-Sets. Sets sind Zusammenstellungen von Plugins, die gesammelt das Aussehen und die Funktionen deines Shops beeinflussen. Wenn ein Set einem Mandanten zugewiesen ist, ist es für diesen Shop aktiv. Später kannst du auch neue Sets erstellen ohne diese einem Mandanten zuzuweisen, um beispielsweise Änderungen an deinem Shop zu testen, ohne diese direkt live zu schalten. Im Rahmen dieses Schnelleinstiegs werden wir aber mit dem standardmäßig vorhandenen Set standard-shop arbeiten. Hebe hierfür zunächst die Verknüpfung des Sets mit dem Mandanten auf.

[.instruction]
Verknüpfung aufheben:

. Klicke auf die Schaltfläche *Plugin-Sets verknüpfen*. +
→ Das Fenster *Plugin-Sets verknüpfen* öffnet sich.
. Wähle aus dem Dropdown-Menü die leere Zeile aus.
. *Speichere* die Einstellungen, um das Plugin-Set zu deaktivieren.

Direkt neben den Plugin-Sets findest du die Filtereinstellungen. Du kannst diese nutzen, um verschiedene Auswahlen an Plugins anzeigen zu lassen. Wenn du ein Plugin-Set öffnest, werden standardmäßig immer alle installierten Plugins angezeigt.

Mit den plentyShop-Plugins Ceres und IO werden wir uns später auseinandersetzen. Zunächst wollen wir unseren Kunden die Möglichkeit geben, für ihre Einkäufe auch zu bezahlen.

TIP: Weiter zum Thema <<schnelleinstieg/schnelleinstieg-zahlungsabwicklung#, Zahlungsabwicklung einrichten>>
