= Warenwirtschaft einrichten
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

Für eine funktionierende Warenwirtschaft müssen mindestens Lager, Lieferant und Warenbestand eingerichtet werden.

Wenn Sie die Warenbestände nicht in plentymarkets führen möchten, wählen Sie im Menü *Artikel » Artikel bearbeiten* im Tab *Varianten-ID » Einstellungen* bei der Einstellung *Beschränkung* die Option *Keinen Warenbestand für diese Variante führen*. Fahren Sie dann fort mit <<#410, Artikelbilder verwalten>>.

[.instruction]
Neues Lager einrichten:

. Öffnen Sie das Menü *System » Waren » Lager*.
. Klicken Sie auf *Neues Lager*. +
→ Das Fenster *Neues Lager* wird geöffnet.
. Geben Sie Name, Lagertyp und Logistiktyp ein.
. *Speichern* Sie die Einstellungen. +
→ Das Lager wird eingerichtet und links im Verzeichnisbaum angezeigt.
. Öffnen Sie das Lager, um die Untermenüs zu sehen.

Weitere Informationen und Einstellungen finden Sie auf der Handbuchseite <<warenwirtschaft/lager-einrichten#, Lager einrichten>>.

[.instruction]
Neuen Lieferanten einrichten:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Klicken Sie auf *Neuen Kontakt erstellen*.
. Geben Sie den Namen des Lieferanten ein.
. Wählen Sie den Typ *Lieferant*.
. *Speichern* Sie die Einstellungen. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie auf *Neue Adresse*.
. Geben Sie die Adressdaten ein.
. *Speichern* Sie die Einstellungen.

Beachten Sie weitere Informationen und Einstellungen zum Erstellen eines neues Kontakts auf der Handbuchseite <<crm/kontakte-verwalten#100, Kontakte verwalten>>.
