= Warenwirtschaft einrichten
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

Für eine funktionierende Warenwirtschaft müssen mindestens Lager, Lieferant und Warenbestand eingerichtet werden. Ein Lieferant ist hier nur Typ eines Kontakts.

Wenn du die Warenbestände nicht in plentymarkets führen möchtest, wähle im Menü *Artikel » Artikel bearbeiten* im Tab *Varianten-ID » Einstellungen* bei der Einstellung *Beschränkung* die Option *Keinen Warenbestand für diese Variante führen*. Fahre dann fort mit <<#410, Artikelbilder verwalten>>.

[.instruction]
Neues Lager einrichten:

. Öffne das Menü *System » Waren » Lager*.
. Klicke auf *Neues Lager*. +
→ Das Fenster *Neues Lager* wird geöffnet.
. Gib Name, Lagertyp und Logistiktyp ein.
. *Speichere* die Einstellungen. +
→ Das Lager wird eingerichtet und links im Verzeichnisbaum angezeigt.
. Öffne das Lager, um die Untermenüs zu sehen.

[.instruction]
Neuen Lieferanten einrichten:

. Öffne das Menü *CRM » Kontakte*.
. Klicke auf *Neuen Kontakt erstellen*.
. Gib den Namen des Lieferanten ein.
. Wähle den Typ *Lieferant*.
. *Speichere* die Einstellungen. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke auf *Neue Adresse*.
. Gib die Adressdaten ein.
. *Speichere* die Einstellungen.

=== Mehr zum Thema:
* <<warenwirtschaft/lager-einrichten#, Lager einrichten>>
* <<crm/kontakte-verwalten#100, Kontakte verwalten>>.
