= Schnell durchstarten
:lang: de
include::{includedir}/_header.adoc[]
:position: 10
:url: schnelleinstieg/schnelleinstieg-schnell-durchstarten
:id: 1WSFUVF


Herzlich Willkommen bei plentymarkets! Wir freuen uns, dass du dich für uns entschieden hast. In diesem Schnelleinstieg werden wir gemeinsam mit dir dein System einrichten. Ziel dabei ist, dich schnell und einfach verkaufsfähig zu machen.

Folgendes haben wir mit dir vor:

* Lagerhaltung und Versand vorbereiten
* Artikelkatalog aufbauen
// * Amazon
* eBay anbinden
* Webshop einrichten
* E-Mail-Versand vorbereiten
* Auftragsabwicklung organisieren
* Vorgänge automatisieren

[TIP]
.Professionelle Systemeinrichtung gewünscht?
====
Wenn du möchtest, dass dir unsere Einrichter mit Rat und Tat zur Seite stehen, kannst du link:https://www.plentymarkets.eu/service/systemeinrichtung-consulting/[hier^] einen Termin vereinbaren. Alternativ kannst du dich auch mit einem unserer link:https://marketplace.plentymarkets.com/services/support[Partner^] in Verbindung setzen.
====

Wie du wahrscheinlich schon weißt, handelt es sich bei plentymarkets um ein komplexes System, wenn man alle Möglichkeiten ausschöpfen möchte. Daher solltest du insbesondere für dieses erste Einrichten ausreichend Zeit einplanen. Das hilft dir später auch, dich leichter zurechtzufinden.

Natürlich wollen wir dich aber nicht davon abhalten, bei Themen, die dich besonders interessieren, tiefer in die Materie einzutauchen. Deshalb findest du sowohl am Ende jedes Kapitels als auch am Ende des Schnelleinstiegs Sammlungen mit thematisch relevanten weiterführenden Links.

Wenn du es nicht bereits getan hast, stelle sicher, dass dein Rechner alle <<schnelleinstieg/systemvoraussetzungen#100, Systemvoraussetzungen>> erfüllt.

Bereit? Dann können wir ja loslegen! ...Oder zumindest könnten wir das, vorher aber noch zwei Tipps:

[.instruction]
Tipps:

. Wenn du den Link aus deiner Willkommens-E-Mail öffnest, wirst du feststellen, dass die URL bereits deine plenty-ID enthält. Füge diese Seite zu deinen Lesezeichen hinzu, damit deine ID beim Aufrufen der Seite immer schon automatisch in der Anmeldemaske eingetragen wird.
. Im Administrationsbereich von plentymarkets, dem sogenannten Backend, werden Pop-ups verwendet. Wenn du ein effizientes Arbeiten gewährleisten möchtest, solltest du also die URLs +https://[*.]plentymarkets-cloud-de.com+ und +https://[*.]plentymarkets-cloud-ie.com+ in den Einstellungen deines Browsers als Ausnahmen hinzufügen.

Jetzt bist du aber wirklich startklar.

[.instruction]
Mit dem Einrichten beginnen:

. Melde dich mit deinem Benutzernamen und deinem Passwort in deinem System an.
. Öffne das Menü *System » Systemeinstellungen » Mandant » Standard Shop (Standard) » Webshop » Shop sperren*.
. Klicke auf *Webshop jetzt sperren*. +
→ Dein Webshop ist für Kunden nicht mehr sichtbar. Du kannst also in Ruhe alle notwendigen Einstellungen vornehmen.

TIP: Weiter zum Thema <<schnelleinstieg/schnelleinstieg-basiseinstellungen#, Basiseinstellungen vornehmen>>
