= Hurra
:lang: de
include::{includedir}/_header.adoc[]
:position: 0


////
TODO
Herzlichen Glückwunsch, du hast es geschafft
Final Checklist
Changelog im Forum abonnieren
weiterführende Links

Finale Checkliste, neu machen, runterladbar/druckbar machen? (evtl. im einem nächsten Schritt umsetzen)

////


== Final Check
Nehmen Sie sich auf jeden Fall vor der Live-Schaltung ausreichend Zeit für den Abschlusstest. Prüfen Sie anhand der Vorgaben, ob Ihr plentymarkets System vollständig eingerichtet und komplett funktionsfähig ist. Im Folgenden finden Sie einige Hinweise und Anregungen zum finalen Testen Ihres Webshops.

[TIP]
.Tipp zum Testen des Webshops
====
Verlassen Sie sich beim Testen nicht ausschließlich auf sich selbst. Je mehr Tester Sie für Ihren Webshop gewinnen können, umso sicherer und genauer ist das Feedback.
====

[%interactive]
* [ ] Ist Ihre Startseite ansprechend und informativ zugleich?
* [ ] Wird Ihre Website in gängigen Browsern korrekt angezeigt?
* [ ] Haben Sie alle Pflichtseiten erstellt? Widerrufsrecht und Versandkosten, Impressum und Datenschutz, Bankverbindung und AGB? Weitere Informationen finden Sie in diesem link:https://www.plentymarkets.eu/knowledge/video-archiv/arbeiten-mit-plentymarkets/schnelleinstieg/[Videotutorial].
* [ ] Sind Ihre Artikel in einem sinnvollen und nachvollziehbaren Kategoriebaum gegliedert?
* [ ] Testen Sie die Suche, die Listenansichten und die Einzeldarstellungen der Artikel.
* [ ] Legen Sie Artikel in den Warenkorb und testen Sie Ihre Versandeinstellungen. Berücksichtigen Sie dabei unterschiedliche Regionen und Zahlungsarten.
* [ ] Werden alle Versandkosten korrekt berechnet?
* [ ] Stimmen die berechneten Versandkosten mit Ihren Angaben in der Kategorie überein?
* [ ] Wird das individuelle Artikelporto korrekt berechnet (falls Artikelporto eingestellt wurde)?
* [ ] Sind alle angebotenen Zahlungsarten eingerichtet und freigeschaltet?
* [ ] Wird nach der Bestellung eine vollständige Bestätigung an den Kunden gesendet?
* [ ] Haben Sie alle E-Mail-Vorlagen mit Ihren Daten ergänzt?
* [ ] Haben Sie den Webshop entsperrt?
* [ ] Haben Sie den Testmodus für E-Mail-Benachrichtigungen wieder deaktiviert?



[#1010]
== Testmodus deaktivieren

Damit Ihre Kunden auch die richtigen E-Mails erhalten, müssen Sie den Testmodus wieder deaktivieren.

[.instruction]
Testmodus deaktivieren:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » E-Mail » Zugangsdaten*.
. Stellen Sie den Testmodus auf *inaktiv*.

[#1020]
== Webshop produktiv schalten

Abschließend müssen Sie nur noch Ihren Webshop produktiv schalten, damit Ihre Kunden auf Ihren Webshop gelangen können.

[.instruction]
Plugins bereitstellen:

. Öffnen Sie das Menü *Plugins » Plugin-Übersicht*.
. Wählen Sie das gewünschte *Plugin-Set* aus.
. Aktivieren Sie das Plugin *Vorkasse* in der Spalte *Aktiv*.
. Aktivieren Sie das Plugin *Ceres* in der Spalte *Aktiv*.
. Aktivieren Sie das Plugin *IO* in der Spalte *Aktiv*.
. Klicken Sie in der Menüleiste auf *Speichern & Plugins bereitstellen*. +
→ Die aktivierten Plugins werden geprüft und die Bereitstellung wird gestartet.
. Klicken Sie auf *Plugin-Set aktivieren* und aktivieren Sie das Plugin-Set für den gewünschten Mandanten.

Wenn alle Punkte erfolgreich bearbeitet wurden, haben Sie diesen Schnelleinstieg erfolgreich abgeschlossen und Ihr plentymarkets System für den ersten Start vollständig eingerichtet.

*Herzlichen Glückwunsch und viel Erfolg!*
