= Auftragsabwicklung
:lang: de
include::{includedir}/_header.adoc[]
:position: 0


////
TODO

1.
ZUERST: Vorlagen für Auftragsdokumente einrichten! Beispiel anhand einem standort, einer sprache und einem dokument erklären. zb standard-rechnung oder auch lieferschein erstellen. Input Support: Stornobelege nicht vergessen und Hinweis, dass Aufträge für bearbeitung gesperrt werden sobald eine Rechnung erzeugt wurde. Stornobeleg storniert dann das Dokument (zB. Rechnung, NICHT den Auftrag an sich.)

2.
DANN: nötige Grundeinstellungen im Menü System > Aufträge> Einstellungen

3.
Allgemeiner Beschreibungstext für Auftragsabwicklung - soll ans Ende (Links entfernen und auch kürzen)

Im Menü *Aufträge » Aufträge verwalten” hast du jederzeit Zugriff auf alle Aufträge, egal ob sie über deinen Ceres Webshop[link] oder über Marktplätze wie Amazon[link] oder eBay[link] in deinem System eingehen oder manuell angelegt wurden. Zudem erkennst du in der Auftragsübersicht direkt, ob es sich um eine Gutschrift, eine Retoure oder einen anderen Auftragstypen handelt. Mehr Informationen zu den verschiedenen Auftragstypen und zur manuellen Auftragsanlage findest du auf der Handbuchseite <<auftragsabwicklung/auftraege/auftraege-verwalten#, Aufträge verwalten>>.

Den aktuellen Stand der Auftragsabwicklung verfolgst du anhand der Statusanzeige, die an jedem Auftrag in der Auftragsübersicht farblich markiert ist. In deinem plentymarkets System sind einige Status standardmäßig voreingestellt und dürfen nicht verändert werden. Du kannst jedoch im Menü *System » Aufträge » Status* beliebig viele Auftragsstatus hinzufügen, um die Schritte deiner Auftragsabwicklung optimal abzubilden. Beachte hierzu die Anleitungen und Tipps zum Umgang mit Auftragsstatus im Kapitel <<auftragsabwicklung/auftraege/auftraege-verwalten#1200, Auftragsstatus nutzen>>.

Durch einen Klick auf die Auftrags-ID in der Auftragsübersicht öffnest du einen bestimmten Auftrag. Die Tabs innerhalb eines Auftrags geben dir vielfältige Bearbeitungsmöglichkeiten. So kannst du im Tab *Kunde* auf die Kontaktdaten des Kunden zugreifen oder im Tab *Belege* manuell Auftragsdokumente wie Rechnungen oder Lieferscheine erstellen.

4. Wichtige Bearbeitungsmöglichkeiten in der Auftragsübersicht
- Filter- und Suchmöglichkeiten
- Aufträge nicht löschen
- Wie storniert man manuell einen Auftrag
- Immer auch auf Automatisierungsmöglichkeiten durch Ereignisaktionen hinweisen
- Wo werden Warenausgang und Zahlung gebucht, wo werden Auftragsdokumente generiert (alles manuell als Beispiel
- Support nochmal um Input bitten

5. Weiterführende Links

Auftragstypen
Auftragsstatus
Auftragsdokumente
Handbuchseite Aufträge verwalten

////
