= Systemvoraussetzungen
:lang: de
include::{includedir}/_header.adoc[]
:position: 10

////
Handbuchseite "Systemvoraussetzungen"

TO DO:
Inhaltlich und optisch in Schnelleinstieg integrieren
Info, dass plenty für Google Chrome optimiert ist
////


Auf dieser Seite erfährst du, welche Voraussetzungen deine Hardware und deine Internetverbindung erfüllen muss, damit du plentymarkets nutzen kannst.

[#100]
== Vorausgesetzte Hardware, Betriebssysteme und Browser

Die Angaben in <<tabelle-generelle-voraussetzungen>> geben Mindeststandards wieder, um mit plentymarkets optimal arbeiten zu können. Wenn du die angegebenen Werte unterschreitest, musst du mit einer eingeschränkten Performance bis hin zu technischen Problemen, aufgrund mangelnder Kompatibilität, rechnen. Wenn du außerdem sehr alte Hardware oder einen schlecht gewarteten PC nutzt, sind dauerhafte Leistungsprobleme möglich. Die Angaben beziehen sich auf plentymarkets Systeme ab plentymarkets 6. +

[TIP]
plentymarkets ist für den Browser Google Chrome optimiert. Sie können jedoch auch über Mozilla Firefox oder Safari (Mac OS) darauf zugreifen. Diese Einschränkung gilt nur für den Administrationsbereich. Ihr Webshop ist natürlich von allen gängigen Browsern aus erreichbar.

[[tabelle-generelle-voraussetzungen]]
.Nutzungsvoraussetzungen
[cols="1,3"]
|====
| |Voraussetzung

|**Prozessor**
|2 x 2 GHz +
Bei Rechnern mit Windows-Betriebssystem mindestens Intel Core 2

|**Arbeitsspeicher**
|6 GB

|**Monitorauflösung**
|1280 x 720

|**Internetverbindung**
|Permanente Verbindung +
*_Hinweis:_* Die Bandbreite sollte immer im Verhältnis zur Anzahl der Nutzer stehen.

|*Betriebssystem*
a| * 64-Bit
* Windows 7 und höher
* Mac OS X 10.10 und höher
* Linux

Wenn du andere Betriebssysteme, Server-Betriebssysteme oder virtuelle Maschinen nutzt, sind Einschränkungen möglich.

|*Browser*
a|
* link:http://www.google.com/chrome/[Google Chrome^] Version 46 oder höher
* link:http://www.mozilla.com/[Mozilla Firefox^] Version 43 oder höher

*_Hinweis:_* Die Browser-Voraussetzungen gelten nicht für Deine Kunden. Deine Kunden können jederzeit mit einem W3C-konformen Browser in Deinem Shop einkaufen.
|====

[#200]
== plentymarkets App nutzen

Die plentymarkets App bietet umfassende Funktionen für das Abrufen von Kennzahlen sowie für die Kunden-, Artikel- und Auftragssuche. Für diese Funktionen benötigst du ein mobiles Android- oder iOS-Gerät. Die plentymarkets App stellt außerdem Funktionen für die mobile Warenwirtschaft sowie das Kassensystem plentymarkets POS bereit. Hier erfährst du, welche Hardware du benötigst, um diese Funktionen zu nutzen.

[#300]
=== Geschäftsdaten mit der plentymarkets App verwalten

Wenn du die plentymarkets App nur nutzen möchtest, um Geschäftsdaten zu verwalten, also keine Kasse betreiben oder Warenbestand verwalten möchtest, benötigst du lediglich ein mobiles Android- oder iOS-Gerät. <<tabelle-voraussetzungen-plenty-app>> erläutert die Hardware-Voraussetzungen für die plentymarkets App zum Abrufen von Kennzahlen und Geschäftsdaten.

[[tabelle-voraussetzungen-plenty-app]]
.Geschäftsdaten mit der plentymarkets App verwalten
[cols=""]
|====
|Voraussetzungen |App-Download

|Android-Geräte mit OS-Version 4.2.2 oder höher
|link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=de[plentymarkets App bei Google Play^]

|iOS-Geräte mit Version 8 oder höher
|link:https://itunes.apple.com/de/app/plentymarkets/id957702618[plentymarkets App bei iTunes^]
|====

[#400]
=== Warenbestand mit der plentymarkets App verwalten

Wenn du die plentymarkets App für die Warenwirtschaft im Lager nutzen möchtest, empfehlen wir die in <<tabelle-warenwirtschaft-app>> aufgeführte Hardware.

[[tabelle-warenwirtschaft-app]]
.Warenwirtschaft mit der plentymarkets App
[cols="1,3"]
|====
|Hardware |Bezugsquelle

|HM3 SM10 Mobile Computer +
(Android 5.1)
|link:https://www.sundsits.de/M3SM10[www.sundsits.de/M3SM10^] +

SundS ITS +
Beselerstr. 2-6 +
50354 Hürth +
info@sundsits.de +
Tel.: +49(0)2233-7064010 +
Fax: +49(0)2233-7064011 +
link:https://www.sundsits.de[www.sundsits.de^]

|Honeywell Dolphin 75e +
(Android 4.4.4)
|link:http://www.globos.de/produkte/honeywell-dolphin-75e-mobilecomputer[www.globos.de/produkte/honeywell-dolphin-75e-mobilecomputer^]

GLOBOS Logistik- und Informationssysteme GmbH +
Ahrensburger Straße 1 +
30659 Hannover +
vertrieb@globos.de +
Tel.: +49 (511) 76920-0 +
Fax: +49 (511) 76920-250 +
link:http://www.globos.de[www.globos.de^]
|====

[#500]
== Kassensystem plentymarkets POS nutzen

Das Kassensystem plentymarkets POS wird über die plentymarkets App bereitgestellt. Beachte jedoch, dass für den Einsatz von plentymarkets POS zusätzliche Hardware-Voraussetzungen bestehen. plentymarkets POS unterstützt die in <<tabelle-systemvoraussetzungen-kasse>> aufgeführte Hardware. Die Tabelle führt außerdem die Geräte auf, auf denen plentymarkets neue Releases vor der Veröffentlichung testet.

[[tabelle-systemvoraussetzungen-kasse]]
.Unterstützte Hardware für plentymarkets POS
[cols="1,2,2"]
|====
|Gerätetyp |Allgemeine Anforderungen |Getestete Geräte

|**Betriebssysteme**
a|
* Android-Geräte mit OS-Version ab 4.2.2, ARM Prozessor und den link:https://cdn.discourse.org/plentymarkets/uploads/default/original/3X/5/b/5b3b12c7adea2b46e1fb4ae4d1b42bc4e8e37fd8.png[Geräteklassen^]
Small, Normal, Large und X-Large. Die DPI-Zahl eines mobilen Geräts kann z.B. link:http://dpi.lv/[hier^] ermittelt werden.
* iOS-Geräte (iPad, iPhone, iPod) mit OS-Version ab 8 +
→ Bei iOS-Geräten gibt es Einschränkungen beim Scannen mit Bluetooth-Scannern. +
→ Kassen mit Standort Österreich können nur auf Android-Geräten betrieben werden.

a|Bei jedem regulären Release

* Elo Touch Solutions I-Series 15I1 - E021201
* Advantech UPOS-211 sundsits Edition
* Honeywell Dolphin 75e (Android 4.4.4)
* M3 SM10 (Android 5.1)
* Samsung Galaxy Tab A 6 - SM-T580
* Apple iPad Air 2

Regelmäßig

* Samsung Galaxy Tab A - SM-T555
* Samsung Galaxy Tab 4 - SM-T530
* Apple iPad Mini Retina

Punktuell

* Samsung Galaxy S4
* Apple iPhone 6
* Apple iPad Mini
* Apple iPhone 6

|**Bondrucker**
a|
* ePos-Print API
* Drucker muss über LAN oder WLAN verfügen
a|
* EPSON TM-M30
* EPSON TM-T88V-i (QR-Code-Druck)

|**Scanner**
a|
* Scanner muss über USB oder Bluetooth verfügen
a|
* Inateck BCST-10 (Bluetooth)
* Albasca USB Handscanner MK-1000 (ungetestet aber bei mehreren Kunden erfolgreich im Einsatz)

|**Kundendisplays**
a|
* Nur mit Belegdrucker EPSON TM-M30 einsetzbar
a|
* EPSON DM-D30

|**Karten-Terminals**
a|
* Nur in Verbindung mit Payment-Provider-Vertrag
a|
* Ingenico iPP480 mit Drucker (Betriebsart **ZVT**, Verbindungsart **TCP/IP**) - Anbindung über link:https://marketplace.plentymarkets.com/plugins/payment/ingenicozvt_5140[Ingenico ZVT-Plugin^]
* Verifone H5000 mit Drucker (Betriebsart **ZVT**, Verbindungsart **TCP/IP**) - Anbindung über link:https://marketplace.plentymarkets.com/plugins/payment/VerifoneZVT_5504[Verifone ZVT-Plugin^]
* CCV VX 680 mit Drucker (Betriebsart **ZVT**, Verbindungsart **TCP/IP**) - Anbindung über link:https://marketplace.plentymarkets.com/plugins/payment/VerifoneZVT_5504[Verifone ZVT-Plugin^]
* SumUp Air - Anbindung über link:https://marketplace.plentymarkets.com/plugins/payment/sumup_5141[SumUp-Plugin^] +
**__Hinweis:__** Für SumUp-Anbindung Ortung (Positionsbestimmung) auf dem mobilen Gerät aktivieren, auf dem die plentymarkets App installiert ist.
|====

[#600]
== Probleme beheben

Wenn du Probleme bei der Nutzung von plentymarkets hast, können folgende Punkte Ursache dafür sein:

* Dein Browser ist nicht aktuell. Prüfe die Version Deines Browsers und ob es eine neuere Version gibt.
* Deine CPU ist ausgelastet. Wenn deine CPU durch den Regelbetrieb bereits voll ausgelastet ist, schließe nicht benötigte Programme.
* Dein Arbeitsspeicher ist zu klein. Prüfe die Größe deines Arbeitsspeichers. Wir empfehlen eine Mindestgröße von 4 GB.
* Deine Java-Version ist nicht aktuell. Prüfe die installierte Java-Version und ob es eine neuere Version gibt. Installiere die aktuelle Version.
* Deine Festplatte ist zu mehr als 70% mit Daten belegt und wurde seit Jahren nicht mehr ausgetauscht. Je nach Betriebssystem und Qualität der Hardware sind ab einer Laufzeit von mehr als zwei Jahren deutliche Leistungseinbußen feststellbar. Lösche unnötige Dateien oder setze das System direkt neu auf. Eine aktuelle und leistungsfähige Festplatte/SSD wäre ebenfalls eine kostengünstige Option.

Fragen stellen oder Probleme melden kannst du jederzeit im link:https://forum.plentymarkets.com/[Forum^].
