= EASYMARKETING
:lang: de
include::{includedir}/_header.adoc[]
:keywords: easymarketing, Mandant, Webshop
:position: 50

*Einrichtung » Mandant » Mandant wählen » Dienste » Easymarketing*

== Allgemeines über EASYMARKETING

EASYMARKETING organisiert Online-Werbung vollautomatisiert. Das System analysiert deinen Webshop und ermittelt die relevanten Keywords. Es setzt anschließend die Kampagnen auf, setzt CPCs und erstellt Anzeigen. Diese werden stetig optimiert, um so die Ergebnisse zu verbessern. (Quelle: vgl. link:https://easymarketing.de/[easymarketing.de^])

Mithilfe der Schnittstelle zu EASYMARKETING werden Bestellungen in deinem Webshop getrackt und es wird eine google site verification ausgeführt.

== EASYMARKETING einrichten

Registriere dich zunächst bei link:https://easymarketing.de/users/new?website_url=&expected_conversion_rate=&advertising_strategy=aggressive&webshop_or_other=other&daily_budget=13[EASYMARKETING^]. Du erhältst einen Token, den du in plentymarkets einträgst.

[.instruction]
EASYMARKETING-Einstellungen konfigurieren:

. Öffne das Menü *Easymarketing* (Pfad siehe oben).
. Trage deinen *Access Token* ein, den du von EASYMARKETING erhalten hast.
. Setze ein Häkchen bei *Aktiv*.
. Klicke auf *Speichern*, um deine Einstellungen zu sichern.
