= Trusted Shops
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Truted Shops, Zertifizierung, Prüfungsprotokoll
:position: 100

*System » Systemeinstellungen » Mandant » Mandant wählen » Dienste » Trusted Shops*

== Allgemeines über Trusted Shops

Trusted Shops ist ein Internet-Gütesiegel für Online-Shops mit Käuferschutz für Online-Kunden. In diesem Kapitel wird beschrieben wie die Zertifizierung durch Trusted Shops erfolgt und welche Einstellungen Sie in plentymarkets für eine Zertifizierung beachten müssen.  +
plentymarkets hat bereits bei der Entwicklung Software mit Trusted Shops zusammengearbeitet und so ist ein Großteil der Zertifizierungsanforderungen bereits jetzt erfüllt. Der Vorteil für Sie: Sie können sich ohne großen Aufwand und zu ermäßigten Konditionen zertifizieren lassen.

[TIP]
.Tipp
====
Weitere Informationen und Erfahrungen von zertifizierten Online-Shops finden Sie auf der Trusted Shops-Website unter link:http://www.trustedshops.de/shopbetreiber[www.trustedshops.de/shopbetreiber^].
====

== Trusted Shops-Zertifizierung

Für die Zertifizierung durch Trusted Shops wird Ihr Webshop von Trusted Shops geprüft und Sie erhalten ein *Prüfungsprotokoll*. In diesem Protokoll sind Änderungen vermerkt, die Sie an Ihr plentymarkets-System anpassen müssen, damit die Zertifizierung vorgenommen werden kann.

Grundsätzlich ist der Bestellvorgang und der Aufbau des Webshops optimiert für die Zertifizierung durch Trusted Shops.
Jedoch gibt es einige Bereiche, in denen Sie u.a. individuelle Anpassungen vornehmen müssen. Diese Anpassungen betreffen häufig falsche Formulierungen in E-Mail-Vorlagen, in den Datenschutzbestimmungen des Webshops oder im Widerrufsrecht.  +
Hier finden Sie eine Übersicht der Menüs, in denen Anpassungen nötig sein können.

* <<crm/e-mails-versenden#1200, E-Mail-Vorlagen>>
* <<omni-channel/online-shop/mandanten-einrichten/_webshop/rechtliche-angaben#, Rechtliche Angaben>> wie AGB, Datenschutz oder Widerrufsrecht.
* Texte im <<omni-channel/online-shop/webshop-einrichten/_cms/webdesign/webdesign-bearbeiten/bestellvorgang#, Bestellvorgang>>
* Texte der <<omni-channel/online-shop/sprachpakete#, Sprachpakete>> +
Einige Standardtexte, die ebenfalls im Bestellvorgang angezeigt werden, sind in den Sprachpaketen enthalten.  +
Wenn Sie Ihren Shop mehrsprachig betreiben, hinterlegen Sie auch Übersetzungen der Texte.
* <<crm/e-mails-versenden#600, E-Mail-Signatur>> +
Hinterlegen Sie Ihre Signatur mit vollständiger Anbieterkennzeichnung.
* Automatische Erinnerung bei <<crm/e-mails-versenden#1800, Kaufabbruch>> +
Wenn Sie vorher nicht ausdrücklich die Einwilligung des Kunden eingeholt haben, wird empfohlen diese E-Mail nicht zu versenden.
* <<omni-channel/online-shop/webshop-einrichten/bestellvorgang#, Grundeinstellungen>> des Bestellvorgangs  +
Führen Sie keine Aufträge zusammen und erlauben Sie keine nachträglichen Änderungen.
* Markieren Sie Pflichtangaben in <<omni-channel/online-shop/webshop-einrichten/cms#einstellungen-formulare, Formularen>> und geben Sie einen Hinweis auf die Bedeutung der Markierung.
* <<omni-channel/online-shop/sprachpakete#, Hinweistext>> zum E-Mail-Feld bei der Registrierung im Webshop  +
Sie haben die Möglichkeit, in den *Allgemeinen Texten* der Sprachpakete einen Hinweistext für das E-Mail-Feld zu hinterlegen. Die *interne Bezeichnung* des Sprachpaketes ist *Registrierung E-Mail Hinweis*. Hier ein Vorschlag: +
"Wir senden Ihnen regelmäßig sorgfältig ausgesuchte Angebote zu ähnlichen Produkten aus unserem Sortiment per E-Mail zu. Ihre E-Mail-Adresse wird nicht an andere Unternehmen weitergegeben. Sie können der Nutzung Ihrer E-Mail-Adresse für Werbezwecke jederzeit durch eine formlose E-Mail widersprechen."

[TIP]
.Weiterführende Informationen zur Zertifizierung
====
link:http://www.trustedshops.de/info/qualitaetskriterien/[Trusted Shops Qualitäts-Kriterien^] +
link:http://www.trustedshops.de/info/kategorie/haeufige_fragen_zu_trusted_shops/geld-zurueck-garantie/[Fragen zum Käuferschutz^] +
link:http://www.trustedshops.de/shopbetreiber[Informationen für Shopbetreiber^]
====

Nachdem Sie durch Trusted Shops zertifiziert wurden, richten Sie die Kundenbewertungen ein.
