= Trusted Shops
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Truted Shops, Zertifizierung, Prüfungsprotokoll
:position: 100

*Einrichtung » Mandant » Mandant wählen » Dienste » Trusted Shops*

== Allgemeines über Trusted Shops

Trusted Shops ist ein Internet-Gütesiegel für Online-Shops mit Käuferschutz für Online-Kunden. In diesem Kapitel wird beschrieben wie die Zertifizierung durch Trusted Shops erfolgt und welche Einstellungen du in plentymarkets für eine Zertifizierung beachten musst.  +
plentymarkets hat bereits bei der Entwicklung Software mit Trusted Shops zusammengearbeitet und so ist ein Großteil der Zertifizierungsanforderungen bereits jetzt erfüllt. Der Vorteil für dich: Du kannst dich ohne großen Aufwand und zu ermäßigten Konditionen zertifizieren lassen.

[TIP]
.Tipp
====
Weitere Informationen und Erfahrungen von zertifizierten Online-Shops findest du auf der Trusted Shops-Website unter link:http://www.trustedshops.de/shopbetreiber[www.trustedshops.de/shopbetreiber^].
====

== Trusted Shops-Zertifizierung

Für die Zertifizierung durch Trusted Shops wird dein Webshop von Trusted Shops geprüft und du erhältst ein *Prüfungsprotokoll*. In diesem Protokoll sind Änderungen vermerkt, die du an dein plentymarkets-System anpassen musst, damit die Zertifizierung vorgenommen werden kann.

Grundsätzlich ist der Bestellvorgang und der Aufbau des Webshops optimiert für die Zertifizierung durch Trusted Shops.
Jedoch gibt es einige Bereiche, in denen du u.a. individuelle Anpassungen vornehmen musst. Diese Anpassungen betreffen häufig falsche Formulierungen in E-Mail-Vorlagen, in den Datenschutzbestimmungen des Webshops oder im Widerrufsrecht.  +
Hier findest du eine Übersicht der Menüs, in denen Anpassungen nötig sein können.

* <<crm/e-mails-versenden#1200, E-Mail-Vorlagen>>
* <<omni-channel/online-shop/mandanten-einrichten/_webshop/rechtliche-angaben#, Rechtliche Angaben>> wie AGB, Datenschutz oder Widerrufsrecht.
* Texte im <<omni-channel/online-shop/webshop-einrichten/_cms/webdesign/webdesign-bearbeiten/bestellvorgang#, Bestellvorgang>>
* Texte der <<omni-channel/online-shop/sprachpakete#, Sprachpakete>> +
Einige Standardtexte, die ebenfalls im Bestellvorgang angezeigt werden, sind in den Sprachpaketen enthalten.  +
Wenn du deinen Shop mehrsprachig betreibst, hinterlegst du auch Übersetzungen der Texte.
* <<crm/e-mails-versenden#600, E-Mail-Signatur>> +
Hinterlege Signatur mit vollständiger Anbieterkennzeichnung.
* Automatische Erinnerung bei <<crm/e-mails-versenden#1800, Kaufabbruch>> +
Wenn du vorher nicht ausdrücklich die Einwilligung des Kunden eingeholt hast, wird empfohlen diese E-Mail nicht zu versenden.
* <<omni-channel/online-shop/webshop-einrichten/bestellvorgang#, Grundeinstellungen>> des Bestellvorgangs  +
Führe keine Aufträge zusammen und erlaube keine nachträglichen Änderungen.
* Markiere Pflichtangaben in <<omni-channel/online-shop/webshop-einrichten/cms#einstellungen-formulare, Formularen>> und gib einen Hinweis auf die Bedeutung der Markierung.
* <<omni-channel/online-shop/sprachpakete#, Hinweistext>> zum E-Mail-Feld bei der Registrierung im Webshop  +
Du hast die Möglichkeit, in den *Allgemeinen Texten* der Sprachpakete einen Hinweistext für das E-Mail-Feld zu hinterlegen. Die *interne Bezeichnung* des Sprachpaketes ist *Registrierung E-Mail Hinweis*. Hier ein Vorschlag: +
"Wir senden dir regelmäßig sorgfältig ausgesuchte Angebote zu ähnlichen Produkten aus unserem Sortiment per E-Mail zu. Deine E-Mail-Adresse wird nicht an andere Unternehmen weitergegeben. Du kannst der Nutzung deiner E-Mail-Adresse für Werbezwecke jederzeit durch eine formlose E-Mail widersprechen."

[TIP]
.Weiterführende Informationen zur Zertifizierung
====
link:http://www.trustedshops.de/info/qualitaetskriterien/[Trusted Shops Qualitäts-Kriterien^] +
link:http://www.trustedshops.de/info/kategorie/haeufige_fragen_zu_trusted_shops/geld-zurueck-garantie/[Fragen zum Käuferschutz^] +
link:http://www.trustedshops.de/shopbetreiber[Informationen für Shopbetreiber^]
====

Nachdem du durch Trusted Shops zertifiziert wurdest, richtest du die Kundenbewertungen ein.
