= Händlerbund
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Rechtliche Angaben, Händlerbund, REST, API, SOAP, AGBs, AGB, Rechtstext
:description: plentymarkets Integration: Richten Sie die Schnittstelle zu Händlerbund und das Bewertungstool in plentymarkets ein.
:position: 150

[NOTE]
.Alt: CMS & Webshop
====
Diese Handbuchseite widmet sich Funktionen des alten plentymarkets Webshops *Callisto*. Informationen zum Webshop-Template *Ceres* finden Sie <<omni-channel/online-shop/ceres-einrichten#0, hier>>.
====

Der Händlerbund e.V. mit Sitz in Leipzig ist der größte Onlinehandelsverband Europas und einer der führenden Anbieter von <<omni-channel/online-shop/webshop-einrichten#rechtliche-angaben, Rechtstexten>> im Internet. Mit der AGB-Schnittstelle des Händlerbundes können Sie anwaltlich erstellte Rechtstexte auch per Mausklick in Ihr plentymarkets System einbinden. Eine Aktualisierung der Rechtstexte, die z.B. durch eine Gesetzesänderung erforderlich wird, kann somit ohne großen Aufwand vorgenommen werden.

== Beim Händlerbund registrieren

Damit Sie die Leistungen des Händlerbunds für Ihr plentymarkets-System nutzen können, müssen Sie sich zuerst link:http://www.haendlerbund.de/mitgliedschaft/details[registrieren^].

== Benutzer für Händlerbund einrichten

Ihr plentymarkets-System wird via REST-API mit dem Händlerbund verbunden. Für den Zugriff wird zunächst ein eigenes <<basics/admin-aufgaben/benutzer-verwalten#10, Benutzerkonto>> mit Zugriffsrechten auf die API in ihrem System eingerichtet.

[.instruction]
Benutzerkonto einrichten:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Klicken Sie auf *Neu*. +
→ Das Fenster *Neuen Benutzer anlegen* wird geöffnet.
. Geben Sie den *Benutzernamen*, den *realen Namen* und das *Passwort* ein.
. Wiederholen Sie das Passwort.
. Geben Sie die E-Mail-Adresse des Benutzers ein, damit der Benutzer Benachrichtigungen des Systems empfängt.
. Wählen Sie die Benutzerklasse *Variabel*.
. *Speichern* Sie die Einstellungen.

Anschließend aktivieren Sie im Benutzerprofil im Tab *Berechtigung » Tab: REST-API* die Checkboxen für *frontend*, *legalinformation* und *save*. Diese Calls werden für den Händlerbund benötigt. *Speichern* Sie die Änderungen.

[.instruction]
Händlerbund-Rechtstexte importieren:

. Loggen Sie sich auf der Händlerbund-Website in Ihren Mitglieds-Account ein.
. Wählen Sie Punkt 2 *Rechtstexte herunterladen* für den entsprechenden Shop aus.
. Klicken Sie auf den Button *Schnittstelle - Rechtstexte per Schnittstelle in den Shop integrieren*. +
→ Ein Fenster wird geöffnet.
. Geben Sie die Daten des neu angelegten Benutzers ein und klicken Sie auf *Weiter*. +
→ Die Daten werden von der Schnittstelle gespeichert.
. Wählen Sie den entsprechenden Mandanten und klicken Sie auf *Legitimieren*.
. Wählen Sie die Option *Klassenformatierungen* bei den Feldern, die mit Rechtstexten des Händlerbunds befüllt werden sollen.
. Klicken Sie auf *Rechtstexte importieren*.


Die entsprechenden Texte werden nun in Ihrem Webshop eingefügt.

Weitere Informationen hierzu finden Sie im link:https://wiki.haendlerbund.de/index.php/PlentyMarkets[Händlerbund-Wiki^].

== Bewertungstool einrichten

Der Händlerbund bietet für Mitglieder das Bewertungstool *Käufersiegel Kundenbewertung* an. Voraussetzung für die Nutzung ist die Mitgliedschaft beim Händlerbund. Für die link:https://www.kaeufersiegel.de/bewertung/register.php[Registrierung^] der Kundenbewertung benötigen Sie eine Händlerbund-Mitgliedsnummer. Für die Konfiguration im Käufersiegel-Backend benötigen Sie die Zugangsdaten des zuvor erstellten Benutzerkontos, also den *Benutzernamen* und das *Passwort*, sowie die *URL* des plentymarkets Systems, mit dem Sie das Bewertungstool nutzen möchten.

Weitere Informationen über die Einstellungen im Backend von Händlerbund und die Hinterlegung der Zugangsdaten finden Sie in der link:http://wiki.kaeufersiegel.de/index.php/Plentymarkets[Anleitung Käufersiegel^].

[IMPORTANT]
.Server-URL
====
Die *Server-URL*, die im Käufersiegel-Backend hinterlegt wird, ist die *URL des plentymarkets Systems*.
====
