= Händlerbund
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Rechtliche Angaben, Händlerbund, REST, API, SOAP, AGBs, AGB, Rechtstext
:description: plentymarkets Integration: Richte die Schnittstelle zu Händlerbund und das Bewertungstool in plentymarkets ein.
:position: 150
:url: webshop/webshop-einrichten/extras/haendlerbund

[NOTE]
.Alt: CMS & Webshop
====
Diese Handbuchseite widmet sich Funktionen des alten plentymarkets Webshops *Callisto*. Informationen zum Webshop-Template *Ceres* findest du <<omni-channel/online-shop/ceres-einrichten#0, hier>>.
====

Der Händlerbund e.V. mit Sitz in Leipzig ist der größte Onlinehandelsverband Europas und einer der führenden Anbieter von <<omni-channel/online-shop/webshop-einrichten#rechtliche-angaben, Rechtstexten>> im Internet. Mit der AGB-Schnittstelle des Händlerbundes kannst du anwaltlich erstellte Rechtstexte auch per Mausklick in dein plentymarkets System einbinden. Eine Aktualisierung der Rechtstexte, die z.B. durch eine Gesetzesänderung erforderlich wird, kann somit ohne großen Aufwand vorgenommen werden.

== Beim Händlerbund registrieren

Damit du die Leistungen des Händlerbunds für dein plentymarkets-System nutzen kannst, musst du dich zuerst link:http://www.haendlerbund.de/mitgliedschaft/details[registrieren^].

== Benutzer für Händlerbund einrichten

Dein plentymarkets-System wird via REST-API mit dem Händlerbund verbunden. Für den Zugriff wird zunächst ein eigenes <<basics/admin-aufgaben/benutzer-verwalten#10, Benutzerkonto>> mit Zugriffsrechten auf die API in ihrem System eingerichtet.

[.instruction]
Benutzerkonto einrichten:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Klicke auf *Neu*. +
→ Das Fenster *Neuen Benutzer anlegen* wird geöffnet.
. Gib den *Benutzernamen*, den *realen Namen* und das *Passwort* ein.
. Wiederhole das Passwort.
. Gib die E-Mail-Adresse des Benutzers ein, damit der Benutzer Benachrichtigungen des Systems empfängt.
. Wähle die Benutzerklasse *Variabel*.
. *Speichere* die Einstellungen.

Anschließend aktivierst du im Benutzerprofil im Tab *Berechtigung » Tab: REST-API* die Checkboxen für *frontend*, *legalinformation* und *save*. Diese Calls werden für den Händlerbund benötigt. *Speichere* die Änderungen.

[.instruction]
Händlerbund-Rechtstexte importieren:

. Logge dich auf der Händlerbund-Website in deinen Mitglieds-Account ein.
. Wähle Punkt 2 *Rechtstexte herunterladen* für den entsprechenden Shop aus.
. Klicke auf die Schaltfläche *Schnittstelle - Rechtstexte per Schnittstelle in den Shop integrieren*. +
→ Ein Fenster wird geöffnet.
. Gib die Daten des neu angelegten Benutzers ein und klicke auf *Weiter*. +
→ Die Daten werden von der Schnittstelle gespeichert.
. Wähle den entsprechenden Mandanten und klicke auf *Legitimieren*.
. Wähle die Option *Klassenformatierungen* bei den Feldern, die mit Rechtstexten des Händlerbunds befüllt werden sollen.
. Klicke auf *Rechtstexte importieren*.


Die entsprechenden Texte werden nun in deinem Webshop eingefügt.

Weitere Informationen hierzu findest du im link:https://wiki.haendlerbund.de/index.php/PlentyMarkets[Händlerbund-Wiki^].

== Bewertungstool einrichten

Der Händlerbund bietet für Mitglieder das Bewertungstool *Käufersiegel Kundenbewertung* an. Voraussetzung für die Nutzung ist die Mitgliedschaft beim Händlerbund. Für die link:https://www.kaeufersiegel.de/bewertung/register.php[Registrierung^] der Kundenbewertung benötigst du eine Händlerbund-Mitgliedsnummer. Für die Konfiguration im Käufersiegel-Backend benötigst du die Zugangsdaten des zuvor erstellten Benutzerkontos, also den *Benutzernamen* und das *Passwort*, sowie die *URL* des plentymarkets Systems, mit dem du das Bewertungstool nutzen möchtest.

Weitere Informationen über die Einstellungen im Backend von Händlerbund und die Hinterlegung der Zugangsdaten findest du in der link:http://wiki.kaeufersiegel.de/index.php/Plentymarkets[Anleitung Käufersiegel^].

[IMPORTANT]
.Server-URL
====
Die *Server-URL*, die im Käufersiegel-Backend hinterlegt wird, ist die *URL des plentymarkets Systems*.
====
