= Live-Shopping
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, Live-Shopping
:position: 200

[NOTE]
.Alt: CMS & Webshop
====
Diese Handbuchseite widmet sich Funktionen des alten plentymarkets Webshops *Callisto*. Informationen zum Webshop-Template *Ceres* finden Sie <<omni-channel/online-shop/ceres-einrichten#0, hier>>.
====

//  plentymarkets 7
Beim Live-Shopping wird täglich ein Artikel aus dem Sortiment für einen bestimmten Zeitraum (z.B. von 9:00 bis 18:00 Uhr) zu einem vergünstigten Preis angeboten. Live-Shopping-Angebote konfigurieren Sie im Menü *System » Systemeinstellungen » Mandant » Global » Live-Shopping*.

== Live-Shopping-Angebot erstellen

Gehen Sie wie unten beschrieben vor, um ein neues Live-Shopping-Angebot zu erstellen.

[NOTE]
.Verkaufspreis für Live-Shopping-Angebote
====
Legen Sie einen Verkaufspreis des Preistyps *Aktionspreis* an und hinterlegen Sie diesen Verkaufspreis am Artikel. Der Verkaufspreis für Ihre Live-Shopping-Angebote wird automatisch basierend auf Verkaufspreis-Einstellungen gewählt.
====

[.instruction]
Live-Shopping-Angebot erstellen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Global » Live-Shopping*.
. Klicken Sie auf ein Live-Shopping-Tab.
. Klicken Sie auf das *grüne Plus*. +
→ Das Fenster *Neues Live-Shopping* wird angezeigt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dabei <<tabelle-einstellungen-live-shopping>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-einstellungen-live-shopping]]
.Live-Shopping; Einstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Start*
|Datum und Uhrzeit für Beginn des Live-Shopping-Angebots wählen.

|*Ende*
|Datum und Uhrzeit für Ende des Live-Shopping-Angebots wählen.

|*Artikel-ID*
|ID des Artikels eingeben. +
*_Hinweis:_* Derselbe Artikel kann nicht zur gleichen Zeit in mehreren Live-Shopping-Angeboten angeboten werden.

|*Menge verkauft*
|Eingabe ändert die Prozentanzeige der bereits verkauften Menge im Live-Shopping.

|*Gesamt*
|Menge eingeben, die maximal zum Angebotspreis verkauft werden soll. Unabhängig von dieser Angabe muss bei Artikeln, die an Warenbestand gebunden sind, ausreichend Bestand vorhanden sein. +
Wenn ein Kunde im Warenkorb versucht, eine höhere Menge zu erwerben, wird die Menge automatisch verringert. Sobald diese Menge verkauft ist, gilt wieder der normale Preis.

|*Verknüpfung aktiv*
|Dieselbe Zeitspanne kann für mehrere Live-Shopping-Angebote konfiguriert werden. Option aktivieren, um dieses Angebot anzuzeigen, sobald ein Live-Shopping-Angebot, das in der Live-Shopping-Ansicht weiter oben steht und zum gleichen Zeitpunkt verkauft wird, ausverkauft ist.
|====


[WARNING]
.Preis bei Überschreiten der Restmenge
====
Wenn ein Käufer mehr Artikel in den Warenkorb legt, als für das Live-Shopping-Angebot verfügbar sind, wird die gesamte Bestellmenge des Artikels zum regulären Preis berechnet. Beträgt z.B. die Restmenge eines Live-Shopping-Artikels 7 Stück und ein Kunde legt den Artikel 8-mal in den Warenkorb, wird für alle 8 Artikel der normale Verkaufspreis berechnet.

Weisen Sie Ihre Kunden darauf hin und stellen Sie sicher, dass bei Live-Shopping-Angeboten jederzeit ersichtlich ist, wie viele Artikel noch zum vergünstigten Preis verfügbar sind.
====

== Live-Shopping-Angebot konfigurieren

Gehen Sie wie unten beschrieben vor, um ein neu angelegtes Live-Shopping-Angebot zu konfigurieren.

[.instruction]
Live-Shopping-Angebot konfigurieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Global » Live-Shopping*.
. Klicken Sie auf ein Live-Shopping-Tab.
. Wechseln Sie in das Tab *Einstellungen*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dabei <<tabelle-einstellungen-live-shopping-angebote>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-einstellungen-live-shopping-angebote]]
.Einstellungen für Live-Shopping-Angebote
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Live-Shopping anzeigen*
|*Ausblenden, wenn kein Angebot aktiv* = Template-Variable <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewliveshopping, Container_ItemViewLiveShopping()>> wird nur befüllt, wenn ein Artikel gerade zum günstigen Preis gekauft werden kann. +
*Zeige nächstes Angebot, wenn kein Angebot aktiv* = Template-Variable wird immer befüllt. Wenn kein Angebot aktiv ist, wird eine Vorschau des nächsten Angebots angezeigt. Der vergünstigte Preis gilt jedoch erst ab dem eingestellten Angebotsbeginn. Daher für Angebote, die einander automatisch folgen sollen, die gleiche Startzeit festlegen. Siehe auch <<tabelle-einstellungen-live-shopping>> , Option *Verknüpfung aktiv*.
|====

== Live-Shopping in Ihren Webshop einbinden

Binden Sie nun die Live-Shopping-Funktion in Ihren Webshop ein. Fügen Sie dazu die folgenden Template-Funktion und -Variable in das Design Ihres Webshops ein:

* *{% Container_ItemViewLiveShopping() %}*
* *{% $LiveShoppingID = 1 %}* +
→ Die ID bestimmt, welches Live-Shopping-Angebot eingefügt wird. Mit *ID 1* wird z.B. Angebot *Live Shopping 1* eingefügt.

=== ItemViewSingleItem-Ansicht anpassen

Um in der Artikeldetailansicht nochmals deutlich zu machen, dass es sich bei dem Live-Shopping-Angebot um ein Sonderangebot handelt, stehen die folgenden Template-Variablen zur Verfügung, die in das Template *ItemViewSingleItem* eingefügt werden:

* *$LiveShoppingQuantityRemaining*
* *$LiveShoppingPrice*

Beispielcode für Ihr ItemViewSingleItem-Template:

[source,plenty]
----
include::assets/EX-DE-Live-Shopping-SoAngebot.html[]

----

=== Aktionsansicht mit Template-Variablen anpassen

Im Template *CMS » Webdesign » Layout » ItemView » ItemViewLiveShopping* gestalten Sie die Live-Shopping-Angebote. Die folgenden Template-Variablen stehen dazu zur Verfügung:

* *$LiveShoppingContainerId*
* *$LiveShoppingQuantityRemaining*
* *$LiveShoppingPrice*
* *$LiveShoppingPriceOriginal*
* *$LiveShoppingPercentRemaining*
* *$LiveShoppingPercentSold*
* *$LiveShoppingQuantitySold*
* *$LiveShoppingStartTime*
* *$LiveShoppingEndTime*

Der folgende Code ist ein Beispiel für die Gestaltung von Live-Shopping-Angeboten im Template *ItemViewLiveShopping*:

[source,plenty]
----
include::assets/EX-DE-liveshopping.html[]

----

== Live-Shopping-Angebot veröffentlichen

Live-Shopping-Angebote können auch auf externen Plattformen eingestellt werden, z.B. auf link:http://www.liveshopping-aktuell.de[liveshopping-aktuell.de^]. Registrieren Sie sich dazu bei dem Anbieter und hinterlegen Sie die URL der Angebote nach folgendem Muster:

* Angebot 1: Ihre_Domain/plenty/api/liveshopping_xml_1.php
* Angebot 2: Ihre_Domain/plenty/api/liveshopping_xml_2.php

Bei diesen Beispielen werden die Artikel des ersten und zweiten Live-Shopping-Angebots exportiert.

Per ID bestimmen Sie, welches Live-Shopping-Angebot exportiert werden soll. Mit dem Parameter *SHIPPING* legen Sie feste Versandkosten fest.

[TIP]
.Beispiel: Parameter ID und SHIPPING
====
Mit ID für Live-Shopping-Angebot 1: "Ihre_Domain/plenty/api/liveshopping_xml_1.php?ID=1" +
Mit ID für Live-Shopping-Angebot 3 und mit Code für 3,90 Versandkosten: "Ihre_Domain/plenty/api/liveshopping_xml_2.php?ID=3&amp;SHIPPING=3.90"
====

Als Beschreibung des Artikels wird nur der Vorschautext (short_description) exportiert.

[IMPORTANT]
.Exportbedingung
====
Live-Shopping-Angebote werden nur exportiert, wenn der Artikel einer Kategorie zugeordnet ist.
====

[#100]
== Automatisch über Live-Shopping-Angebote berichten

Nutzen Sie den Aktionsmanager, um täglich auf Twitter und Facebook über Ihre Live-Shopping-Angebote zu berichten. Richten Sie dafür Aktionen ein. Weitere Informationen zur Einrichtung Ihres Twitter-Kontos in plentymarkets finden Sie auf der Handbuchseite <<omni-channel/online-shop/extras/twitter#, Twitter>>.

[.instruction]
Aktion einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Artikel » Aktionen*.
. Wechseln Sie in das Tab *Neue Aktion*.
. Wählen Sie die Aktion *Live-Shopping twittern*.
. Geben Sie einen Namen ein.
. Wählen Sie eine Uhrzeit, zu der die Aktion ausgeführt werden soll.
. Setzen Sie ein Häkchen bei *Aktiv*.
. Wechseln Sie in das Tab *Filter*.
. Wählen Sie den Mandanten (Shop).
. Wählen Sie die Kategorieseite, in die das Live-Shopping-Angebot als Template-Variable eingefügt wurde.
. Wählen Sie das Twitter-Konto, das für die Aktion genutzt werden soll.
. Wechseln Sie in das Tab *Aktion*.
. Geben Sie eine Nachricht für die Aktion ein.
. *Speichern* Sie die Einstellungen. +
→ Die Aktion wird eingerichtet und im Tab *Aktionen* angezeigt.

Um Live-Shopping-Angebote auf Facebook zu posten, richten Sie eine zweite Aktion *Live-Shopping auf Facebook posten* analog ein und verknüpfen diese Aktion mit Ihrem Facebook-Konto.

[WARNING]
.Facebook-Berechtigungen
====
Damit die Verknüpfung mit Ihrem Facebook-Konto einwandfrei funktioniert, müssen Sie die beiden Berechtigungen link:https://developers.facebook.com/docs/facebook-login/permissions/v2.4#reference-manage_pages[manage_pages^] und link:https://developers.facebook.com/docs/facebook-login/permissions/v2.4#reference-publish_pages[publish_pages^] aktivieren.
====

== FAQ

=== Aktives Live-Shopping

[.instruction]
Wann ist Live-Shopping für einen Artikel aktiv?

[.indented]
Das Live-Shopping für einen Artikel ist aktiv, wenn die aktuelle Uhrzeit sich im konfigurierten Bereich befindet und bei warenbestandsabhängigen Artikeln noch ausreichend Bestand für das Live-Shopping vorhanden ist.=== Attributartikel verkaufen

[.instruction]
Ich verkaufe Attributartikel. Kann die Attributauswahl in das Live-Shopping-Angebot eingebaut werden?

[.indented]
Ja, die Attributauswahl kann in das Live-Shopping-Angebot eingebaut werden. Verwenden Sie dazu dieselben Template-Variablen wie in der Ansicht eines Einzelartikels verfügbar, darunter auch *$AttributeSelect* und *$AttributeSelectWithoutAttributeName*. Bauen Sie einfach einen der beiden Template-Variablen in das Template *ItemViewLiveShopping* ein.=== Link zum Live-Shopping-Angebot einfügen

[.instruction]
Ich möchte von der Startseite einen Link zur Seite mit dem Live-Shopping-Angebot setzen. Wie blende ich diesen Link nur ein, wenn ein LiveShopping Angebot aktiv ist?

[.indented]
Verwenden Sie dazu die Template-Funktion *{% if Container_ItemViewLiveShopping() %} LINK {% endif %}*.
