= Live-Shopping
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, Live-Shopping
:position: 200
:url: webshop/webshop-einrichten/extras/live-shopping

[NOTE]
.Alt: CMS & Webshop
====
Diese Handbuchseite widmet sich Funktionen des alten plentymarkets Webshops *Callisto*. Informationen zum Webshop-Template *Ceres* findest du <<omni-channel/online-shop/ceres-einrichten#0, hier>>.
====

//  plentymarkets 7
Beim Live-Shopping wird täglich ein Artikel aus dem Sortiment für einen bestimmten Zeitraum (z.B. von 9:00 bis 18:00 Uhr) zu einem vergünstigten Preis angeboten. Live-Shopping-Angebote konfigurierst du im Menü *System » Systemeinstellungen » Mandant » Global » Live-Shopping*.

== Live-Shopping-Angebot erstellen

Gehe wie unten beschrieben vor, um ein neues Live-Shopping-Angebot zu erstellen.

[NOTE]
.Verkaufspreis für Live-Shopping-Angebote
====
Lege einen Verkaufspreis des Preistyps *Aktionspreis* an und hinterlege diesen Verkaufspreis am Artikel. Der Verkaufspreis für deine Live-Shopping-Angebote wird automatisch basierend auf Verkaufspreis-Einstellungen gewählt.
====

[.instruction]
Live-Shopping-Angebot erstellen:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Global » Live-Shopping*.
. Klicke auf ein Live-Shopping-Tab.
. Klicke auf das *grüne Plus*. +
→ Das Fenster *Neues Live-Shopping* wird angezeigt.
. Nimm die Einstellungen vor. Beachte dabei <<tabelle-einstellungen-live-shopping>>.
. *Speichere* die Einstellungen.

[[tabelle-einstellungen-live-shopping]]
.Live-Shopping; Einstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Start*
|Datum und Uhrzeit für Beginn des Live-Shopping-Angebots wählen.

|*Ende*
|Datum und Uhrzeit für Ende des Live-Shopping-Angebots wählen.

|*Artikel-ID*
|ID des Artikels eingeben. +
*_Hinweis:_* Derselbe Artikel kann nicht zur gleichen Zeit in mehreren Live-Shopping-Angeboten angeboten werden.

|*Menge verkauft*
|Eingabe ändert die Prozentanzeige der bereits verkauften Menge im Live-Shopping.

|*Gesamt*
|Menge eingeben, die maximal zum Angebotspreis verkauft werden soll. Unabhängig von dieser Angabe muss bei Artikeln, die an Warenbestand gebunden sind, ausreichend Bestand vorhanden sein. +
Wenn ein Kunde im Warenkorb versucht, eine höhere Menge zu erwerben, wird die Menge automatisch verringert. Sobald diese Menge verkauft ist, gilt wieder der normale Preis.

|*Verknüpfung aktiv*
|Dieselbe Zeitspanne kann für mehrere Live-Shopping-Angebote konfiguriert werden. Option aktivieren, um dieses Angebot anzuzeigen, sobald ein Live-Shopping-Angebot, das in der Live-Shopping-Ansicht weiter oben steht und zum gleichen Zeitpunkt verkauft wird, ausverkauft ist.
|====


[WARNING]
.Preis bei Überschreiten der Restmenge
====
Wenn ein Käufer mehr Artikel in den Warenkorb legt, als für das Live-Shopping-Angebot verfügbar sind, wird die gesamte Bestellmenge des Artikels zum regulären Preis berechnet. Beträgt z.B. die Restmenge eines Live-Shopping-Artikels 7 Stück und ein Kunde legt den Artikel 8-mal in den Warenkorb, wird für alle 8 Artikel der normale Verkaufspreis berechnet.

Weise deine Kunden darauf hin und stelle sicher, dass bei Live-Shopping-Angeboten jederzeit ersichtlich ist, wie viele Artikel noch zum vergünstigten Preis verfügbar sind.
====

== Live-Shopping-Angebot konfigurieren

Gehe wie unten beschrieben vor, um ein neu angelegtes Live-Shopping-Angebot zu konfigurieren.

[.instruction]
Live-Shopping-Angebot konfigurieren:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Global » Live-Shopping*.
. Klicke auf ein Live-Shopping-Tab.
. Wechsle in das Tab *Einstellungen*.
. Nimm die Einstellungen vor. Beachte dabei <<tabelle-einstellungen-live-shopping-angebote>>.
. *Speichere* die Einstellungen.

[[tabelle-einstellungen-live-shopping-angebote]]
.Einstellungen für Live-Shopping-Angebote
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Live-Shopping anzeigen*
|*Ausblenden, wenn kein Angebot aktiv* = Template-Variable <<omni-channel/online-shop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewliveshopping, Container_ItemViewLiveShopping()>> wird nur befüllt, wenn ein Artikel gerade zum günstigen Preis gekauft werden kann. +
*Zeige nächstes Angebot, wenn kein Angebot aktiv* = Template-Variable wird immer befüllt. Wenn kein Angebot aktiv ist, wird eine Vorschau des nächsten Angebots angezeigt. Der vergünstigte Preis gilt jedoch erst ab dem eingestellten Angebotsbeginn. Daher für Angebote, die einander automatisch folgen sollen, die gleiche Startzeit festlegen. Siehe auch <<tabelle-einstellungen-live-shopping>> , Option *Verknüpfung aktiv*.
|====

== Live-Shopping in deinen Webshop einbinden

Binde nun die Live-Shopping-Funktion in deinem Webshop ein. Füge dazu die folgenden Template-Funktion und -Variable in das Design deines Webshops ein:

* *{% Container_ItemViewLiveShopping() %}*
* *{% $LiveShoppingID = 1 %}* +
→ Die ID bestimmt, welches Live-Shopping-Angebot eingefügt wird. Mit *ID 1* wird z.B. Angebot *Live Shopping 1* eingefügt.

=== ItemViewSingleItem-Ansicht anpassen

Um in der Artikeldetailansicht nochmals deutlich zu machen, dass es sich bei dem Live-Shopping-Angebot um ein Sonderangebot handelt, stehen die folgenden Template-Variablen zur Verfügung, die in das Template *ItemViewSingleItem* eingefügt werden:

* *$LiveShoppingQuantityRemaining*
* *$LiveShoppingPrice*

Beispielcode für dein ItemViewSingleItem-Template:

[source,plenty]
----
include::assets/EX-DE-Live-Shopping-SoAngebot.html[]

----

=== Aktionsansicht mit Template-Variablen anpassen

Im Template *CMS » Webdesign » Layout » ItemView » ItemViewLiveShopping* gestaltest du die Live-Shopping-Angebote. Die folgenden Template-Variablen stehen dazu zur Verfügung:

* *$LiveShoppingContainerId*
* *$LiveShoppingQuantityRemaining*
* *$LiveShoppingPrice*
* *$LiveShoppingPriceOriginal*
* *$LiveShoppingPercentRemaining*
* *$LiveShoppingPercentSold*
* *$LiveShoppingQuantitySold*
* *$LiveShoppingStartTime*
* *$LiveShoppingEndTime*

Der folgende Code ist ein Beispiel für die Gestaltung von Live-Shopping-Angeboten im Template *ItemViewLiveShopping*:

[source,plenty]
----
include::assets/EX-DE-liveshopping.html[]

----

== Live-Shopping-Angebot veröffentlichen

Live-Shopping-Angebote können auch auf externen Plattformen eingestellt werden, z.B. auf link:http://www.liveshopping-aktuell.de[liveshopping-aktuell.de^]. Registriere dich dazu bei dem Anbieter und hinterlege die URL der Angebote nach folgendem Muster:

* Angebot 1: deine_Domain/plenty/api/liveshopping_xml_1.php
* Angebot 2: deine_Domain/plenty/api/liveshopping_xml_2.php

Bei diesen Beispielen werden die Artikel des ersten und zweiten Live-Shopping-Angebots exportiert.

Per ID bestimmst du, welches Live-Shopping-Angebot exportiert werden soll. Mit dem Parameter *SHIPPING* legst du feste Versandkosten fest.

[TIP]
.Beispiel: Parameter ID und SHIPPING
====
Mit ID für Live-Shopping-Angebot 1: "deine_Domain/plenty/api/liveshopping_xml_1.php?ID=1" +
Mit ID für Live-Shopping-Angebot 3 und mit Code für 3,90 Versandkosten: "deine_Domain/plenty/api/liveshopping_xml_2.php?ID=3&amp;SHIPPING=3.90"
====

Als Beschreibung des Artikels wird nur der Vorschautext (short_description) exportiert.

[IMPORTANT]
.Exportbedingung
====
Live-Shopping-Angebote werden nur exportiert, wenn der Artikel einer Kategorie zugeordnet ist.
====

[#100]
== Automatisch über Live-Shopping-Angebote berichten

Nutze den Aktionsmanager, um täglich auf Twitter und Facebook über deine Live-Shopping-Angebote zu berichten. Richte dafür Aktionen ein. Weitere Informationen zur Einrichtung deines Twitter-Kontos in plentymarkets findest du auf der Handbuchseite <<omni-channel/online-shop/extras/twitter#, Twitter>>.

[.instruction]
Aktion einrichten:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Aktionen*.
. Wechsle in das Tab *Neue Aktion*.
. Wähle die Aktion *Live-Shopping twittern*.
. Gib einen Namen ein.
. Wähle eine Uhrzeit, zu der die Aktion ausgeführt werden soll.
. Setze ein Häkchen bei *Aktiv*.
. Wechsle in das Tab *Filter*.
. Wähle den Mandanten (Shop).
. Wähle die Kategorieseite, in die das Live-Shopping-Angebot als Template-Variable eingefügt wurde.
. Wähle das Twitter-Konto, das für die Aktion genutzt werden soll.
. Wechsle in das Tab *Aktion*.
. Gib eine Nachricht für die Aktion ein.
. *Speichere* die Einstellungen. +
→ Die Aktion wird eingerichtet und im Tab *Aktionen* angezeigt.

Um Live-Shopping-Angebote auf Facebook zu posten, richtest du eine zweite Aktion *Live-Shopping auf Facebook posten* analog ein und verknüpfen diese Aktion mit deinem Facebook-Konto.

[WARNING]
.Facebook-Berechtigungen
====
Damit die Verknüpfung mit deinem Facebook-Konto einwandfrei funktioniert, musst du die beiden Berechtigungen link:https://developers.facebook.com/docs/facebook-login/permissions/v2.4#reference-manage_pages[manage_pages^] und link:https://developers.facebook.com/docs/facebook-login/permissions/v2.4#reference-publish_pages[publish_pages^] aktivieren.
====

== FAQ

=== Aktives Live-Shopping

[.instruction]
Wann ist Live-Shopping für einen Artikel aktiv?

[.indented]
Das Live-Shopping für einen Artikel ist aktiv, wenn die aktuelle Uhrzeit sich im konfigurierten Bereich befindet und bei warenbestandsabhängigen Artikeln noch ausreichend Bestand für das Live-Shopping vorhanden ist.=== Attributartikel verkaufen

[.instruction]
Ich verkaufe Attributartikel. Kann die Attributauswahl in das Live-Shopping-Angebot eingebaut werden?

[.indented]
Ja, die Attributauswahl kann in das Live-Shopping-Angebot eingebaut werden. Verwende dazu dieselben Template-Variablen wie in der Ansicht eines Einzelartikels verfügbar, darunter auch *$AttributeSelect* und *$AttributeSelectWithoutAttributeName*. Baue einfach einen der beiden Template-Variablen in das Template *ItemViewLiveShopping* ein.

=== Link zum Live-Shopping-Angebot einfügen

[.instruction]
Ich möchte von der Startseite einen Link zur Seite mit dem Live-Shopping-Angebot setzen. Wie blende ich diesen Link nur ein, wenn ein LiveShopping Angebot aktiv ist?

[.indented]
Verwende dazu die Template-Funktion *{% if Container_ItemViewLiveShopping() %} LINK {% endif %}*.
