= Protected Shops
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Protected Shops, Webshop, Mandant (Shop)
:description: Lassen Sie Rechtstexte jederzeit und ohne Aufwand in Ihren Onlineshop übertragen. Die Rechtstexte bleiben stets aktuell und auf dem neuesten Stand.
:position: 220
:url: webshop/webshop-einrichten/extras/protected-shops

*System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Rechtliches*

[NOTE]
.Alt: CMS & Webshop
====
Diese Handbuchseite widmet sich Funktionen des alten plentymarkets Webshops *Callisto*. Informationen zum Webshop-Template *Ceres* finden Sie <<omni-channel/online-shop/ceres-einrichten#0, hier>>.
====

== Allgemeines zu Protected Shops

Die *Protected Shops GmbH* ist einer der führenden *Anbieter für Rechtstextentwicklung* für den Online-Handel.
Von Protected Shops erhalten Online-Händler <<omni-channel/online-shop/webshop-einrichten#rechtliche-angaben, Rechtstexte>>,
die individuell angepasst und auf den Bedarf des Händlers zugeschnitten sind. Die Schutzpakete von Protected Shops beinhalten alle notwendigen
Rechtstexte mit Haftungsübernahmegarantie. Bei Änderung der Gesetzeslage werden die Texte von Protected Shops automatisch angepasst
und der Kunde per Protect Mail darüber informiert.

Als plentymarkets-Kunde können Sie von der AGB Connect-Schnittstelle profitieren, die Protected Shops eigens für das System anbietet. Diese Schnittstelle ermöglicht es, dass alle Rechtstexte jederzeit und ohne Aufwand in Ihren plentymarkets-Onlineshop übertragen werden können. Die Rechtstexte bleiben somit stets aktuell und auf dem neuesten Stand.

== Einstellungen in plentymarkets

Die Anbindung erfolgt über unsere SOAP API-Schnittstelle. Folgende Einstellungen sind darüber hinaus vorzunehmen:

* Konfiguration der *Shopdaten* in Ihrem Protected Shops-Account.
* Konfiguration eines <<basics/admin-aufgaben/benutzer-verwalten#, Benutzers>> mit Aktivierung der nötigen *SOAP-Berechtigungen*.
* Prüfen der <<basics/datenaustausch/api-daten#, SOAP-WSDL>> und der *Bezeichnungen* und *IDs* der <<artikel/kategorien-verwalten#, Kategorieseiten>>.
* Ggf. weitere Content-Seiten anlegen, z.B. *Batterieverordnung* und *Rückgaberecht*.
