= Universal Analytics
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Universal Analytics, Tracking
:position: 300

*CMS » Webdesign*

[NOTE]
.Alt: CMS & Webshop
====
Diese Handbuchseite widmet sich Funktionen des alten plentymarkets Webshops *Callisto*. Informationen zum Webshop-Template *Ceres* finden Sie <<omni-channel/online-shop/ceres-einrichten#0, hier>>.
====

== Allgemeines zu Universal Analytics

Universal Analytics ist der aktuelle Betriebsstandard für Google Analytics. link:http://www.google.com/intl/de_ALL/analytics/[Universal Analytics^] ist ein kostenfreies Tool zur Analyse von Websites und Apps hinsichtlich Besucherstatistik und Nutzungsverhalten. Mit dem Dienst link:https://support.google.com/analytics/answer/1037249?hl=de&topic=1037061&ctx=topic[E-Commerce^] von Google Analytics tracken Sie außerdem E-Commerce-Aktivitäten.

Auf dieser Seite wird beschrieben, wie Sie Universal Analytics einrichten, um Daten für Besucherstatistiken und Nutzungsverhalten zu sammeln (Kapitel 2).

Außerdem erfahren Sie in Kapitel 3, wie Sie auch Daten zu Ihren Verkäufen sammeln. Um das Conversion-Tracking mit Universal Analytics zu nutzen,
müssen Sie zunächst den <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-individueller-bestellvorgang, individuellen Bestellvorgang>> einrichten.

[WARNING]
.Wichtige Hinweise zum Datenschutz
====
Unter folgendem Link finden Sie drei Punkte, die Sie beachten sollten, wenn Sie Classic Google Analytics und Universal Analytics einsetzen: +
link:http://www.lhr-law.de/lbr-blog/nrw-datenschutzbeauftragter-uberpruft-google-analytics-einsatz[http://www.lhr-law.de/lbr-blog/nrw-datenschutzbeauftragter-uberpruft-google-analytics-einsatz^]

Die Richtlinien zum Datenschutz werden immer wieder angepasst. Halten Sie sich diesbezüglich auf dem Laufenden und holen Sie ggf. rechtlichen Rat ein, um Abmahnungen zu vermeiden.
====

== Universal Analytics einrichten

Nachfolgend wird beschrieben, wie Sie Universal Analytics (analytics.js) einrichten bzw. von Classic Google Analytics (ga.js) auf Universal Analytics migrieren. Die Einrichtung unterteilt sich in Einstellungen in Ihrem Konto bei Google Analytics und Einstellungen in plentymarkets.

=== Einstellungen bei Google Analytics

Um Universal Analytics für Ihre Website zu verwenden, erstellen Sie ein Konto bei link:http://www.google.com/intl/de_ALL/analytics/[Google Analytics^] oder melden sich mit Ihrem bestehenden Konto an. Informationen zum Einrichtung eines Profils Ihrer Website finden Sie auf den link:https://support.google.com/analytics/?hl=de#topic=3544906[Google Analytics-Hilfeseiten^].

Wenn Sie bereits Classic Google Analytics (ga.js) nutzen, finden Sie Informationen zur Migration auf Universal Analytics (analytics.js) im link:https://developers.google.com/analytics/devguides/collection/upgrade/[Universal Analytics-Migrationscenter^].

[TIP]
.Einstellung für verschlüsselte Website
====
Wenn Sie für Ihre Website ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>> verwenden, wählen Sie in Google Analytics das Schema *https*.
====

=== Tracking-Code-Snippet (analytics.js) abrufen

Nachdem Sie ein Profil Ihrer Website bei Google Analytics erstellt haben, benötigen Sie den Tracking-Code (analytics.js). Informationen zum Generieren des Tracking-Codes finden Sie auf der link:https://support.google.com/analytics/answer/1008080[Hilfeseite von Google Analytics^].

Zusammen mit Ihrem Tracking-Code (analytics.js) wird ein Tracking-Code-Snippet angezeigt, das Ihren Tracking-Code enthält. Das Tracking-Code-Snippet befindet sich in einem Feld mit einigen JavaScript-Zeilen. Es beginnt mit *&lt;script&gt;* und endet mit *&lt;/script&gt;*. Kopieren Sie den generierten Tracking-Code-Snippet in die Zwischenablage (*Strg+C* bzw. *cmd+C*). Fügen Sie das Tracking-Code-Snippet dann wie unten beschrieben in plentymarkets ein.

=== Einstellungen in plentymarkets

Fügen Sie das Tracking-Code-Snippet wie unten beschrieben in plentymarkets ein.

[.instruction]
Tracking-Code-Snippet (analytics.js) in plentymarkets einfügen:

. Öffnen Sie das Menü *CMS » Webdesign*.
. Wählen Sie links unter *Layout* das Template *PageDesign » PageDesignContent*.
. Öffnen Sie das Tab *PageDesignContentHtmlStructure*.
. Fügen Sie am Ende des Textfelds das Tracking-Code-Snippet (analytics.js) von Universal Analytics ein.
. *Speichern* Sie die Einstellungen. +
→ Der Code ist aktiv und Google Analytics beginnt, Daten zur Nutzung Ihrer Website zu sammeln.

== Conversion-Tracking im individuellen Bestellvorgang

Zusätzlich zu Daten wie der Anzahl der Besucher, welche Seiten angeklickt wurden etc. können mit Universal Analytics auch Daten zur Conversion getrackt werden.

[WARNING]
.Conversion-Tracking mit Universal Analytics nur mit individuellem Bestellvorgang nutzbar
====
Conversion-Tracking mit Universal Analytics ist in plentymarkets nur in Kombination mit dem <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-individueller-bestellvorgang, individuellen Bestellvorgang>> nutzbar. Der Tracking-Code von Universal Analytics für E-Commerce-Tracking funktioniert nicht mit dem Warenkorb bzw. Bestellvorgang im Menü *CMS » Webdesign » Bestellvorgang*. Richten Sie daher den individuellen Warenkorb ein, bevor Sie von Classic Google Analytics auf Universal Analytics migrieren.
====

Wenn Sie das Conversion-Tracking in plentymarkets aktivieren, werden alle Verkäufe erfasst. Universal Analytics erfasst dabei folgende auftrags- und artikelbezogenen Daten:

Auftragsdaten:

* Auftrags-ID
* Mehrwertsteuer des Auftrags
* Lieferkosten für den Auftrag

Artikeldaten:

* Artikel-ID
* Auftrags-ID
* Artikelnamen
* Artikelkategorie
* Artikelpreis
* Artikelmenge

Gehen Sie wie unten beschrieben vor, um das Conversion-Tracking zu aktivieren.

=== Einstellungen bei Google Analytics

Um Bestellvorgänge in Ihrem Webshop zu tracken, benötigen Sie den Dienst link:https://support.google.com/analytics/answer/1037249?hl=de&topic=1037061&ctx=topic[E-Commerce^] von Google Analytics. Aktivieren Sie diesen Dienst in Ihrem Profil bei Google Analytics, bevor Sie die unten beschriebenen Einstellungen vornehmen.

=== Einstellungen in plentymarkets

Conversion-Tracking mit Universal Analytics ist nur im <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-individueller-bestellvorgang, Individuellen Bestellvorgang>>
möglich. Um Daten aus dem individuellen Bestellvorgang zu erfassen, steht in plentymarkets die Template-Funktion *{% CheckoutGoogleUniversalTracking() %}* zur Verfügung.
Diese Template-Funktion wird zusammen mit dem Tracking-Code-Snippet (analytics.js) von Universal Analytics im Menü
*CMS » Webdesign » Layout* in das Template *Checkout » CheckoutOrderConfirmation* eingefügt. Gehen Sie wie unten beschrieben vor,
 um das Conversion-Tracking in plentymarkets zu aktivieren.

[.instruction]
Tracking-Code-Snippet (analytics.js) und Template-Funktion in individuellen Bestellvorgang einfügen:

. Öffnen Sie das Menü *CMS » Webdesign*.
. Wählen Sie links unter *Layout* das Template *Checkout » CheckoutOrderConfirmation*.
. Öffnen Sie das Tab *CheckoutOrderConfirmationHeader*.
. Fügen Sie am Ende des Textfelds das Tracking-Code-Snippet von Universal Analytics (analytics.js) ein.
. Fügen Sie im Tracking-Code-Snippet die Template-Funktion *{% CheckoutGoogleUniversalTracking() %}* zwischen den Zeilen +
*ga('create', 'UA-XXXX-Y', 'auto');* und *ga('send', 'pageview');* ein. Dabei steht UA-XXXX-Y für Ihre Tracking-ID. +
Der letzte Teil des Code-Snippets entspricht dann diesem Beispiel: +

* *ga('create', 'UA-1234-5', 'auto'); +*
* *{% CheckoutGoogleUniversalTracking() %} +*
* *ga('send', 'pageview');*

. *Speichern* Sie die Einstellungen. +
→ Der Code ist aktiv und Google Analytics beginnt, Daten aus dem Bestellvorgang zu sammeln.
