= Universal Analytics
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Universal Analytics, Tracking
:position: 300
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:url: webshop/webshop-einrichten/extras/universal-analytics
:id: 7XAXUII

*CMS » Webdesign*

[NOTE]
.Alt: CMS & Webshop
====
Diese Handbuchseite widmet sich Funktionen des alten plentymarkets Webshops *Callisto*. Informationen zum Webshop-Template *Ceres* findest du <<omni-channel/online-shop/ceres-einrichten#0, hier>>.
====

== Allgemeines zu Universal Analytics

Universal Analytics ist der aktuelle Betriebsstandard für Google Analytics. link:http://www.google.com/intl/de_ALL/analytics/[Universal Analytics^] ist ein kostenfreies Tool zur Analyse von Websites und Apps hinsichtlich Besucherstatistik und Nutzungsverhalten. Mit dem Dienst link:https://support.google.com/analytics/answer/1037249?hl=de&topic=1037061&ctx=topic[E-Commerce^] von Google Analytics trackst du außerdem E-Commerce-Aktivitäten.

Auf dieser Seite wird beschrieben, wie du Universal Analytics einrichtest, um Daten für Besucherstatistiken und Nutzungsverhalten zu sammeln (Kapitel 2).

Außerdem erfährst du in Kapitel 3, wie du auch Daten zu deinen Verkäufen sammelst. Um das Conversion-Tracking mit Universal Analytics zu nutzen,
musst du zunächst den <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-individueller-bestellvorgang, individuellen Bestellvorgang>> einrichten.

[WARNING]
.Wichtige Hinweise zum Datenschutz
====
Unter folgendem Link findest du drei Punkte, die du beachten solltest, wenn du Classic Google Analytics und Universal Analytics einsetzt: +
link:http://www.lhr-law.de/lbr-blog/nrw-datenschutzbeauftragter-uberpruft-google-analytics-einsatz[http://www.lhr-law.de/lbr-blog/nrw-datenschutzbeauftragter-uberpruft-google-analytics-einsatz^]

Die Richtlinien zum Datenschutz werden immer wieder angepasst. Halte dich diesbezüglich auf dem Laufenden und hole ggf. rechtlichen Rat ein, um Abmahnungen zu vermeiden.
====

== Universal Analytics einrichten

Nachfolgend wird beschrieben, wie du Universal Analytics (analytics.js) einrichtest bzw. von Classic Google Analytics (ga.js) auf Universal Analytics migrierst. Die Einrichtung unterteilt sich in Einstellungen in deinem Konto bei Google Analytics und Einstellungen in plentymarkets.

=== Einstellungen bei Google Analytics

Um Universal Analytics für deine Website zu verwenden, erstellst du ein Konto bei link:http://www.google.com/intl/de_ALL/analytics/[Google Analytics^] oder meldest dich mit deinem bestehenden Konto an. Informationen zum Einrichtung eines Profils deiner Website findest du auf den link:https://support.google.com/analytics/?hl=de#topic=3544906[Google Analytics-Hilfeseiten^].

Wenn du bereits Classic Google Analytics (ga.js) nutzt, findest du Informationen zur Migration auf Universal Analytics (analytics.js) im link:https://developers.google.com/analytics/devguides/collection/upgrade/[Universal Analytics-Migrationscenter^].

[TIP]
.Einstellung für verschlüsselte Website
====
Wenn du für deine Website ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>> verwendest, wähle in Google Analytics das Schema *https*.
====

=== Tracking-Code-Snippet (analytics.js) abrufen

Nachdem du ein Profil deiner Website bei Google Analytics erstellt hast, benötigst du den Tracking-Code (analytics.js). Informationen zum Generieren des Tracking-Codes findest du auf der link:https://support.google.com/analytics/answer/1008080[Hilfeseite von Google Analytics^].

Zusammen mit deinem Tracking-Code (analytics.js) wird ein Tracking-Code-Snippet angezeigt, das deinen Tracking-Code enthält. Das Tracking-Code-Snippet befindet sich in einem Feld mit einigen JavaScript-Zeilen. Es beginnt mit *&lt;script&gt;* und endet mit *&lt;/script&gt;*. Kopiere den generierten Tracking-Code-Snippet in die Zwischenablage (*Strg+C* bzw. *cmd+C*). Füge das Tracking-Code-Snippet dann wie unten beschrieben in plentymarkets ein.

=== Einstellungen in plentymarkets

Füge das Tracking-Code-Snippet wie unten beschrieben in plentymarkets ein.

[.instruction]
Tracking-Code-Snippet (analytics.js) in plentymarkets einfügen:

. Öffne das Menü *CMS » Webdesign*.
. Wähle links unter *Layout* das Template *PageDesign » PageDesignContent*.
. Öffne das Tab *PageDesignContentHtmlStructure*.
. Füge am Ende des Textfelds das Tracking-Code-Snippet (analytics.js) von Universal Analytics ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Code ist aktiv und Google Analytics beginnt, Daten zur Nutzung deiner Website zu sammeln.

== Conversion-Tracking im individuellen Bestellvorgang

Zusätzlich zu Daten wie der Anzahl der Besucher, welche Seiten angeklickt wurden etc. können mit Universal Analytics auch Daten zur Conversion getrackt werden.

[WARNING]
.Conversion-Tracking mit Universal Analytics nur mit individuellem Bestellvorgang nutzbar
====
Conversion-Tracking mit Universal Analytics ist in plentymarkets nur in Kombination mit dem <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-individueller-bestellvorgang, individuellen Bestellvorgang>> nutzbar. Der Tracking-Code von Universal Analytics für E-Commerce-Tracking funktioniert nicht mit dem Warenkorb bzw. Bestellvorgang im Menü *CMS » Webdesign » Bestellvorgang*. Richte daher den individuellen Warenkorb ein, bevor du von Classic Google Analytics auf Universal Analytics migrierst.
====

Wenn du das Conversion-Tracking in plentymarkets aktivieren, werden alle Verkäufe erfasst. Universal Analytics erfasst dabei folgende auftrags- und artikelbezogenen Daten:

Auftragsdaten:

* Auftrags-ID
* Mehrwertsteuer des Auftrags
* Lieferkosten für den Auftrag

Artikeldaten:

* Artikel-ID
* Auftrags-ID
* Artikelnamen
* Artikelkategorie
* Artikelpreis
* Artikelmenge

Gehe wie unten beschrieben vor, um das Conversion-Tracking zu aktivieren.

=== Einstellungen bei Google Analytics

Um Bestellvorgänge in deinem Webshop zu tracken, benötigst du den Dienst link:https://support.google.com/analytics/answer/1037249?hl=de&topic=1037061&ctx=topic[E-Commerce^] von Google Analytics. Aktiviere diesen Dienst in deinem Profil bei Google Analytics, bevor u die unten beschriebenen Einstellungen vornimmst.

=== Einstellungen in plentymarkets

Conversion-Tracking mit Universal Analytics ist nur im <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-individueller-bestellvorgang, Individuellen Bestellvorgang>>
möglich. Um Daten aus dem individuellen Bestellvorgang zu erfassen, steht in plentymarkets die Template-Funktion *{% CheckoutGoogleUniversalTracking() %}* zur Verfügung.
Diese Template-Funktion wird zusammen mit dem Tracking-Code-Snippet (analytics.js) von Universal Analytics im Menü
*CMS » Webdesign » Layout* in das Template *Checkout » CheckoutOrderConfirmation* eingefügt. Gehe wie unten beschrieben vor,
 um das Conversion-Tracking in plentymarkets zu aktivieren.

[.instruction]
Tracking-Code-Snippet (analytics.js) und Template-Funktion in individuellen Bestellvorgang einfügen:

. Öffne das Menü *CMS » Webdesign*.
. Wähle links unter *Layout* das Template *Checkout » CheckoutOrderConfirmation*.
. Öffne das Tab *CheckoutOrderConfirmationHeader*.
. Füge am Ende des Textfelds das Tracking-Code-Snippet von Universal Analytics (analytics.js) ein.
. Füge im Tracking-Code-Snippet die Template-Funktion *{% CheckoutGoogleUniversalTracking() %}* zwischen den Zeilen +
*ga('create', 'UA-XXXX-Y', 'auto');* und *ga('send', 'pageview');* ein. Dabei steht UA-XXXX-Y für deine Tracking-ID. +
Der letzte Teil des Code-Snippets entspricht dann diesem Beispiel: +

* *ga('create', 'UA-1234-5', 'auto'); +*
* *{% CheckoutGoogleUniversalTracking() %} +*
* *ga('send', 'pageview');*

. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Code ist aktiv und Google Analytics beginnt, Daten aus dem Bestellvorgang zu sammeln.
