= First login and tour
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Login, Logging in, Log in, Backend, Back end, New, New customer, Neu customers, System, Tour, Menu structure, Backend URL, Backend URLs, URL, URLs
:description: This page is gearted toward new plentymarkets users. Learn how to log into the system und navigate through the menu structure.
:position: 10
:url: welcome/login-tour
:id: BBRBTD5
:author: team-cloud, team-terra

//add this url weiterleitung /en/basics/working-with-plentymarkets/general-functions/;/en/welcome/login-tour/;301;L

Welcome to plentymarkets. Let me show you around and take you on a tour of your new system!

.Get to know plentymarkets in a playful introductory video
video::257090153[vimeo]

[#10]
== Logging in for the first time

All you need to get started is the welcome email that you received from plentymarkets.
It contains the information that you’ll need to log in.
The connection is encrypted, which makes every login secure.

[.instruction]
Logging into plentymarkets:

. Click on the link in the email to access the plentymarkets login screen.
. Enter the plentymarkets ID, user name and password as they were specified in your email.
. Click on *Login*.

[TIP]
.How do I log back out?
====
Move your mouse cursor over the user symbol (icon:user-circle[]) and then click on *Logout*.
====

[#20]
== Finding your way around the backend

The main navigation bar is up top. You'll notice that drop-downs appear when you move your mouse over the various menus.

* *Setup* +
This menu is where you configure the tools and functions in your plentymarkets system. Take a look at our <<welcome/assistants#, assistants>> and at the <<welcome/quick-start#, quick start>>. These resources are designed help new users set up their systems.
* *Your contract with plentymarkets* +
Open the menu *plentymarkets Logo (Start) » My account* to see information about your plentymarkets system. For example, here you can <<business-decisions/your-contract#, view and edit your contract with plentymarkets>>.
* *User account* +
Click on the user button (icon:user-circle[]) to access your user account. Here you can e.g. <<business-decisions/user-accounts-access#30, change the user name and password>> that were sent to you in the welcome email.
* *Online store* +
Click on your plenty ID in the top right of the plentymarkets back end to open the start page of your online store.
* *Full screen mode* +
Click on icon:ellipsis-v[] in the top right of the plentymarkets back end to activate or deactivate the full screen mode.
* *Favourites* +
Click on icon:ellipsis-v[] in the top right of the plentymarkets back end to display <<welcome/customise-system#90, your favourites>>, to open all favourites or to delete them.
* *Services and partner services* +
Click on icon:question-circle[] in the top right of the plentymarkets back end to access various support offers and partner services.

[#40]
== Customising your system

Are you new to plentymarkets? Then you'll probably want to customise your user account.
Take a look at a few other pages of the manual and learn how to:

* <<business-decisions/user-accounts-access#30, change the user name and password>> that you were initially given.
* <<welcome/customise-system#30, add a user image>> instead of the empty user button (icon:user-circle[]).
* <<welcome/customise-system#150, customise the columns and sort sequence>> in several menus.
* save frequently used menus as <<welcome/customise-system#90, favourites>>.
* add a <<welcome/customise-system#40, signature and complimentary close>> to the end of your emails.
* use plugins to add <<welcome/customise-system#140, additional functions and menus>>.

[#50]
== Directly accessing back end areas with URLs

You can access specific areas of the back end directly by using UI actions. This saves you time and clicks. This section lists the variables and parameters that lead to the respective back end areas.

[IMPORTANT]
.Note
====
You must be logged in to open a back end area with a URL. Also pay attention to lower-case and upper-case letters in parameter keys.
====

[#60]
=== Accessing a back end area with a URL

. The path starts with `https://plentymarkets-cloud-de.com` or `https://plentymarkets-cloud-ie.com`. Which information you should enter depends on whether your system is hosted in Germany or in Ireland.
. Add `/` and your plenty ID.
. Continue with the query string. It begins with a `?`.
. Add `uiAction=`.
. Add the key for the UI actions and the parameter with the corresponding ID. Note the information provided in <<table-keys-ui-actions-parameters>>.
. Once you have entered all relevant information, open the URL to access the desired back end area.

[TIP]
.Example
====
To open the variation detail view, the path has to consist of the following parameters: +
`plentymarkets-cloud-de.com/1234?uiAction=ITEM_VARIATION_DETAIL&itemId=102&variationId=1111`
====

[[table-keys-ui-actions-parameters]]
.Keys for UI actions and parameters
[cols="1,2"]
|====
|Keys |Explanation

| *ITEM_DETAIL* +
 *itemId*
|Opens the item detail view for the specified item ID (itemId is a required parameter).

| *ITEM_VARIATION_DETAIL* +
 *itemId* +
 *variationId*
|Opens the variation detail view for the specified item ID and variation ID (itemId and variationId are required parameters).

| *ORDER_DETAIL* +
 *orderId*
|Opens the order detail view for the specified order ID (orderId is a required parameter).

| *REORDER_DETAIL* +
 *reorderId* +
 *itemId* +
 *reorderItemId*
|Opens the reorder detail view for the specified reorder ID, the item ID or the item ID of a reorder (only one of the three parameters can be specified here).

| *TICKET_DETAIL_VIEW* +
 *ticketId*
|Opens the ticket detail view for the specified ticket ID (ticketId is a required parameter).

| *CUSTOMER_DETAIL* +
 *customerID*
|Opens the customer detail view for the specified customer ID (customerId is a required parameter).
|====

[#70]
=== Safe mode

Using safe mode, you can access the back end with all plugins deactivated. This may be necessary if you receive an error when logging in after installing or updating a plugin. In safe mode, you can change the status of the plugin to *inactive*.

If you want to log in using safe mode, use the URL `https://plentymarkets-cloud-de.com/?safemode=1` or `https://plentymarkets-cloud-ie.com/?safemode=1`. Which URL you should use depends on whether your system is hosted in Germany or in Ireland.
