= Fahrzeugverwendungsliste erstellen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, eBay, erstellen, Fahrzeugverwendungsliste, Fitment
:position: 40

Mit dem Sync-Typ *Fahrzeugverwendungsliste* erstellst, aktualisierst, oder löscht du im Menü *Daten » ElasticSync* vollständige Fahrzeugverwendungslisten oder einzelne Datemsätze aus den Fahrzeugverwendungslisten. +

In diesem Best Practice erfährst du, worauf du achten musst, wenn du mit dem Sync-Typ *Fahrzeugverwendungsliste* mit ElasticSync eine Fahrzeugverwendungliste erstellen oder aktualisieren möchtest.

[#100]
== Fahrzeugverwendungsliste erstellen

Beachte folgende Hinweise, wenn du eine neue Fahrzeugverwendungsliste erstellen möchtest:

* *Pflichtfelder* für die Erstellung einer Fahrzeugverwendungsliste:
  - Name
  - Markt-ID
  - Kategorie-ID
* Damit alle Datensätze/Listeneinträge in einer Fahrzeugverwendungsliste angelegt werden, müssen Name, Markt-ID und Kategorie-ID bei jedem Datensatz/Listeneintrag identisch sein.
* Wenn die Datensätze/Listeneinträge für Name, Markt-ID und Kategorie-ID bereits in dieser Kombination existieren, wird keine neue Fahrzeugverwendungsliste erstellt und auch nicht aktualisiert.
* Wenn eine Fahrzeugverwendungsliste erstellt werden soll und keine Fahrzeug-ID angegeben ist, wird nicht geprüft, ob das Fahrzeug bereits existiert. Das Fahrzeug wird stattdessen neu erstellt. Beachte deshalb, dass es hierbei zu Doppelungen kommen kann.
* Wenn keine Fahrzeug-ID angegeben ist, wird ein neues Fahrzeug erstellt.

[#200]
== Fahrzeugverwendungsliste aktualisieren

Beachte folgende Hinweise, wenn du eine bereits existierende Fahrzeugverwendungsliste aktualisieren möchtest:

* *Pflichtfeld*, um eine bereits existierende Fahrzeugverwendungsliste zu aktualisieren:
  - Fahrzeugverwendungsliste-ID
* Alle anderen Werte können wie gewünscht angegeben werden.
* Immer wenn eine Listen-ID angegeben ist, wird die Fahrzeugverwendungsliste aktualisiert.
* Wenn nur Listen-ID und Fahrzeugeigenschaften angegeben sind, dann werden die Fahrzeugeigenschaften als ein neues Fahrzeug zu dieser Liste hinzugefügt.
* Wenn Fahrzeugeigenschaften aktualisiert werden sollen, dann werden zunächst alle Fahrzeugeigenschaften gelöscht und nur die Fahrzeugeigenschaften aus der CSV-Datei übernommen.
