= Best Practices: Paketnummern und Fulfillment
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Aufträge, Best Practice, automatisiert, Paketnummern, Fulfillment, Dienstleister
:position: 90

[#import_paketnummern]
== Paketnummern von Fulfillment-Dienstleistern importieren

In diesem Beitrag wird beschrieben, wie Ihr mit *ElasticSync* Paketnummern von Aufträgen, die Ihr von einem Fulfillment-Dienstleister abwickeln lasst, in Euer plentymarkets System zu importieren.

Als Datenquelle bietet sich beispielsweise eine CSV-Datei an, in der die Auftrags-ID und die jeweilige Paketnummer enthalten sind. Typischerweise erhaltet Ihr eine solche Datei von Eurem Fulfillment-Dienstleister.

=== Erstellen des Syncs in ElasticSync

Für den Import von Paketnummern legt Ihr unter *Daten » ElasticSync* einen eigenen Sync vom Typ *Auftrag* an.

[TIP]
.Neuen Sync anlegen
====
Für die reibungslose Zusammenarbeit mit Eurem Fulfillment-Dienstleister empfehlen wir, einen separaten Sync für den Import von Paketnummern anzulegen und ihn ausschließlich für diesen Zweck zu nutzen. Wenn Ihr die unten beschriebenen Felder einem bestehenden Sync hinzufügt, kann es leicht zu falschen Zuordnungen und damit zu Fehlfunktionen kommen.
====

* Der Abgleich muss zwingend über die *Auftrags-ID* erfolgen. Weitere Abgleichfelder müssen nicht eingestellt werden.

* Für die Paketnummer fügt Ihr dann eine neue *Zuordnung* hinzu. Als Zuordnungsfeld muss das Feld *Paketnummer* sowie die Option *Standardpaket* ausgewählt werden.

* Über die Funktion *Bearbeiten* innerhalb der Zuordnung *Standardpaket* den Namen der Spalte auswählen, deren Werte aus der Quelldatei importiert werden sollen.

* Einstellungen *speichern*.

Nachdem Ihr die Einstellungen vorgenommen und gespeichert habt, solltet Ihr über das Menü *Sync » Abgleich* zuerst den Sync testen. Nach erfolgreichem Import der *Paketnummer* wird diese im Reiter *Einstellungen* des jeweiligen Auftrags angezeigt.
