= Best Practices: ASIN und ePID
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ElasticSync, Import, Artikel, Artikelanlage, Best Practice, automatisiert, ASIN, ePID
:position: 10

== ASIN und ePID exportieren und importieren

In diesem Beitrag wird beschrieben, wie du ASIN- und ePID-Daten exportierst und importierst.

NOTE: Für dieses Best Practice solltest du mit der generellen Funktionsweise von Elastic Sync vertraut sein. Allgemeine Infos dazu findest du auf der Handbuchseite <<daten/daten-importieren/ElasticSync#, Daten mit ElasticSync importieren>>.

[#export_ASIN_ePID]
=== Export von ASIN und ePID

==== Erstellen des Formats im FormatDesigner

Die derzeit mit Varianten verknüpften ASINs und ePIDs können mit dem FormatDesigner exportiert werden. Dafür erstellt Ihr im Menü *Daten » FormatDesigner* ein neues Format vom Typ *Artikel*.

Anschließend wählt Ihr die Datenfelder:

* Für die Zuordnung beim späteren Import aus dem Bereich *Variation* die *ID* oder *Number* der Variante.

* Die eigentlichen Verknüpfungen fügt Ihr dann im Bereich *VariationMarketIdentNumber* hinzu.

Hier besteht die Möglichkeit, 3 Werte zu wählen:

- *countryID*: Gibt die ID des Landes aus.
- *type*: Gibt den Typ, also ASIN oder ePID, aus.
- *value*: Gibt den Wert aus, der für die ASIN oder ePID hinterlegt ist.

Für alle 3 Felder muss eine Zuordnung des Typs vorgenommen werden. Möchte man also alle ASINs und ePIDs exportieren, muss jedes Feld doppelt in das Format aufgenommen werden.

Nach dem Speichern des Formats kann der Export im Elastischen Export eingerichtet werden.

==== Einrichten des Exports im Elastischen Export

Den Export des angelegten Formats richtet man im Menü *Daten » Elastischer Export* ein.

Dafür klickt Ihr auf den Button *Neuer Export* und hinterlegt einen Namen, den Typ *Artikel*, das angelegte Format, ein Limit und einen Dateinamen.

[TIP]
.Datei als CSV exportieren
====
Wenn die Datei direkt als CSV heruntergeladen werden soll, muss beim Dateinamen das Suffix *.csv* angegeben werden.
====

Nach dem Speichern des Formats ist die Einrichtung abgeschlossen.

==== Daten exportieren

Es gibt mehrere Möglichkeiten, die Daten zu exportieren:

* Im Export auf *Herunterladen* klicken.
* Die im Export angegebene URL im Browser öffnen.
* In der Übersicht der Exporte auf *Herunterladen* klicken.

[#import_ASIN_ePID]
=== Import von ASIN und ePID

==== Erstellen des Syncs in ElasticSync

Für den Import und das Bearbeiten der ASINs und ePIDs könnt Ihr unter *Daten » ElasticSync* einen eigenen Sync vom Typ *Artikel* anlegen oder auch die Felder in einen bestehenden Sync einbauen.

* Der Abgleich muss über ein variantenspezifisches Feld wie die *Variantennummer* erfolgen.

* Für die *Zuordnung* des Syncs müssen für die Verknüpfung im Bereich *ASIN/ePID* die Felder *Land*, *Typ* und *Wert* hinterlegt und mit den Spalten aus der CSV verknüpft werden.

* Das Land muss dabei als ID hinterlegt werden und der Typ entweder als ASIN oder EPID.

Mehr benötigt Ihr für die Verknüpfung nicht. Der Sync ist damit einsatzbereit und die Merkmale können verknüpft werden.
