= Syntax
:lang: de
// include::{includedir}/_header.adoc[]
:keywords: CMS, Webdesign, Syntax, Grundlagen
:position: 20

*CMS » Webdesign*

== Inhalt dieses Kapitels

Auf den folgenden Handbuchseiten erhalten Sie erste grundlegende Informationen zu Struktur, Codierung und Syntax der Inhalte Ihres Webshops. Sie erfahren, wie die verschiedenen Elemente aufgebaut sind und wie Sie die Elemente verändern können. Die meisten Strukturen sind im Standard-Design (d.h. der Grundkonfiguration bei Start Ihres Webshops) in plentymarkets bereits vorhanden und konfiguriert. Die Erläuterungen dieser Seiten sollen Ihnen helfen, diese Strukturen zu verstehen und anzupassen. Dazu sind gewisse Grundkenntnisse im Bereich Webdesign nötig. Alternativ sollten Sie gewünschte Anpassungen von einer Agentur vornehmen lassen.

Beachten Sie die folgenden Erläuterungen zu den Handbuchseiten dieses Bereichs sowie die Seite <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten, Webdesign bearbeiten>>, die weitere Hinweise zur Gestaltung Ihres Onlineshops enthält.

Für die Bearbeitung eines Webdesigns sind erweiterte Kenntnisse in den Bereichen HTML und CSS nötig. Auf der folgenden Seite finden Sie Informationen über HTML und CSS zum Selbststudium: link:http://de.selfhtml.org/[selfhtml^].

== CMS-Syntax

Für die Realisierung eines Webdesigns im plentymarkets CMS ist eine eigene Skriptsprache verfügbar. Im Kapitel <<omni-channel/online-shop/webshop-einrichten/cms-syntax#, CMS-Syntax>> erhalten Sie eine Übersicht aller Möglichkeiten der Gestaltung. Sie finden dort außerdem Erläuterungen zu den *Template-Variablen* und -*Funktionen* sowie zu *Operatoren* und *Kontrollstrukturen*.

== jQuery

jQuery ist eine umfangreiche JavaScript-Klassenbibliothek, die komfortable Funktionen zur Manipulation und Navigation Ihrer Website anbietet. Informationen dazu finden Sie auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/_cms/webdesign/syntax/jquery#, jQuery>>.
