= Werkzeuge
:lang: de
// include::{includedir}/_header.adoc[]
:position: 25

*CMS » Webdesign*

== Editor

plentymarkets enthält einen integrierten WYSIWYG-Editor. Sie können damit Texte und z.B. Tabellen in Content-Seiten direkt bearbeiten oder Formatierungen, wie z.B. Überschriften, Nummerierungen oder Listen, anwenden. Sie sehen bei diesem Editor direkt das Ergebnis. Sie können die Inhalte auch im Quellcode bearbeiten. Erfahren Sie mehr dazu auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-werkzeuge-editor, Editor>>.

== Syntax-Editor

Zur Bearbeitung von HTML-Inhalten, wie Artikelbeschreibungen, Templates und E-Mail-Vorlagen steht Ihnen neben dem bekannten Editor und dem herkömmlichen *Textfeld* der neue *Syntax-Editor* zur Verfügung. Vereinfacht gesagt ist dieser die professionelle Alternative zum *Textfeld*, da der Syntax-Editor neben Syntax-Highlighting weitere Funktionen mit sich bringt, die den Komfort und die Produktivität für die Bearbeitung von HTML enorm erhöhen. Details dazu erfahren Sie auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-werkzeuge-syntax-editor, Syntax-Editor>>.
