= Gelangensbestätigungen erzeugen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Gelangensbestätigung, Gelangensbestätigungen erzeugen, Fulfillment, Auftragsdokumente, Auftragsabwicklung, Lieferung, Auslandslieferung
:position: 94

[#100]
== Allgemeines zu Gelangensbestätigungen

In plentymarkets können Sie Gelangensbestätigungen als PDF-Dateien generieren, um diese z.B. zu drucken oder Ihren Kunden als E-Mail Anhang zukommen zu lassen. +
Bei Lieferungen von Deutschland in ein anderes EU-Land ist die Ausstellung von Gelangensbestätigungen vorgeschrieben. Empfänger bestätigen beispielsweise mittels Unterschrift auf der Gelangensbestätigung und die anschließende Rückübermittlung den erfolgten Wareneingang im jeweiligen EU-Land. +
Somit ist die Gelangensbestätigung nicht nur ein Begleitdokument bei Auslandslieferungen, sondern auch ein steuerrechtlich relevanter Beleg für Ihre Buchhaltung.

[#200]
== Dokumentenvorlage für Gelangensbestätigungen einrichten

Bevor Sie Gelangensbestätigungen generieren können, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü **System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente**. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/auftragsdokumente#, Auftragsdokumente>>.

[#300]
== Gelangensbestätigungen erzeugen

Nachdem Sie eine Dokumentenvorlage für Gelangensbestätigungen eingerichtet haben, können Sie Gelangensbestätigungen als PDF-Dateien erzeugen. Dabei können Sie über einen Suchfilter festlegen, welche Aufträge berücksichtigt werden und ob beispielsweise eine Statusänderung erfolgen soll, nachdem die Gelangensbestätigungen erzeugt wurden.

[.instruction]
Gelangensbestätigungen erzeugen:

. Öffnen Sie das Menü **Aufträge » Fulfillment » Gelangensbestätigung erzeugen**.
. Nehmen Sie die Einstellungen anhand <<tabelle-einstellungen-fulfillment-gelangensbestaetigung>> vor.
. Klicken Sie auf das **Zahnrad**, um die Gelangensbestätigungen zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei**, welche die zugehörigen Gelangensbestätigungen aller von Ihnen durch die Suchfilter bestimmten Aufträge beinhaltet.

[[tabelle-einstellungen-fulfillment-gelangensbestätigungen]]
.Optionen im Menü *Gelangensbestätigung erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Auftragsstatus**
|Aus der Liste den Status der Aufträge wählen, die für die Erstellung der Gelangensbestätigungen berücksichtigt werden sollen.

|**Eigner**
|Wählen Sie einen Eigner aus, für dessen Aufträge die Gelangensbestätigungen erzeugt werden sollen oder die Option **ALLE**, wenn für alle Eigner die Gelangensbestätigungen erzeugt werden sollen.

|**Standort**
|Wählen Sie einen Standort aus, für den die Gelangensbestätigungen erzeugt werden sollen.

|**Lager**
|Wählen Sie ein Lager oder **ALLE** aus.

|**Zahlungsart**
|Wählen Sie eine der Zahlungsarten oder *ALLE* aus.

|**Sortierung**
|Legen Sie fest, wie die erzeugten Gelangensbestätigungen sortiert werden sollen. Die Optionen **Auftrags-ID**, **Kunden-ID** und **Artikel-ID** geben verschiedene Sortierungen aus.

|**Limit**
|Legen Sie fest, wie viele Gelangensbestätigungen maximal pro Durchgang erzeugt werden. Das Maximum liegt bei *200* Gelangensbestätigungen.

|**Ändere Auftragsstatus**
|Wählen Sie einen Status, in den die Aufträge nach Erzeugung der Gelangensbestätigunen wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

|**Kommentar**
|Sie können hier einen Text verfassen, der später auf allen erzeugten Gelangensbestätigungen unterhalb der Artikelpositionen erscheint. Die Eingabe ist optional.
|====
