= Gutschriften erzeugen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Gutschrift, Gutschriften erzeugen, Korrekturbeleg, Korrekturbelege erzeugen
:position: 35

[#100]
== Allgemeines zu Gutschriften

In plentymarkets können Sie Gutschriften als PDF-Dateien generieren, um diese z.B. zu drucken oder Ihren Kunden als E-Mail Anhang zukommen zu lassen. +
Gutschriften nutzen Sie beispielsweise, um bei bereits bezahlten Aufträgen nachträgliche Preisnachlässe zu gewähren oder wenn im Rahmen von Retouren Rückerstattungen veranlasst werden sollen.

[#200]
== Dokumentenvorlage für Gutschriften einrichten

Bevor Sie Gutschriften generieren können, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü **System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente**. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/auftragsdokumente#, Auftragsdokumente>>.

[#300]
== Gutschriften erzeugen

Nachdem Sie eine Dokumentenvorlage für Gutschriften eingerichtet haben, können Sie Gutschriften als PDF-Dateien erzeugen. Dabei können Sie über einen Suchfilter festlegen, welche Aufträge berücksichtigt werden und ob beispielsweise eine Statusänderung erfolgen soll, nachdem die Gutschriften erzeugt wurden.

[.instruction]
Gutschriften erzeugen:

. Öffnen Sie das Menü **Aufträge » Fulfillment » Gutschriften / Korrekturbelege erzeugen**.
. Nehmen Sie die Einstellungen anhand <<tabelle-einstellungen-fulfillment-gutschriften>> vor.
. Klicken Sie auf das **Zahnrad**, um die Gutschriften zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei**, welche die zugehörigen Gutschriften aller von Ihnen durch die Suchfilter bestimmten Aufträge beinhaltet.

[[tabelle-einstellungen-fulfillment-gutschriften]]
.Optionen im Menü *Gutschriften / Korrekturbelege erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Dokumenttyp**
|Wählen Sie, ob Dokumente vom Typ *Gutschrift* oder *Korrekturbeleg* erzeugt werden sollen.

|**Auftragsstatus**
|Aus der Liste den Status der Aufträge wählen, die für die Erstellung der Gutschriften berücksichtigt werden sollen.

|**Eigner**
|Wählen Sie einen Eigner aus, für dessen Aufträge die Gutschriften erzeugt werden sollen oder die Option **ALLE**, wenn für alle Eigner die Gutschriften erzeugt werden sollen.

|**Standort**
|Wählen Sie einen Standort aus, für den die Gutschriften erzeugt werden sollen.

|**Lager**
|Wählen Sie ein Lager oder **ALLE** aus.

|**Zahlungsart**
|Wählen Sie eine der Zahlungsarten oder *ALLE* aus.

|**Sortierung**
|Legen Sie fest, wie die erzeugten Gutschriften sortiert werden sollen. Die Optionen **Gutschriftnummer**, **Auftrags-ID**, **Kunden-ID** und **Artikel-ID** geben verschiedene Sortierungen aus.

|**Limit**
|Legen Sie fest, wie viele Gutschriften maximal pro Durchgang erzeugt werden. Das Maximum liegt bei *200* Gutschriften.

|**Ändere Auftragsstatus**
|Wählen Sie einen Status, in den die Aufträge nach Erzeugung der Gutschriften wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

|**Kommentar**
|Sie können hier einen Text verfassen, der später auf allen erzeugten Gutschriften unterhalb der Artikelpositionen erscheint. Die Eingabe ist optional.
|====
