= Rücksendescheine erzeugen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Rücksendeschein, Rücksendescheine erzeugen, Fulfillment, Auftragsabwicklung, Auftragsdokumente, Rücksendung, Retoure
:position: 96

[#100]
== Allgemeines zu Rücksendescheinen

In plentymarkets können Sie Rücksendescheine als PDF-Dateien generieren, um diese z.B. zu drucken oder Ihren Kunden als E-Mail Anhang zukommen zu lassen. +
Somit können Ihre Kunden Rücksendescheine beispielsweise beim Umtausch von Artikeln oder bei Retouren einfach der Warensendung beilegen.

[#200]
== Dokumentenvorlage für Rücksendescheine einrichten

Bevor Sie Rücksendescheine generieren können, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü **System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente**. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/auftragsdokumente#, Auftragsdokumente>>.

[#300]
== Rücksendescheine erzeugen

Nachdem Sie eine Dokumentenvorlage für Rücksendescheine eingerichtet haben, können Sie Rücksendescheine als PDF-Dateien erzeugen. Dabei können Sie über einen Suchfilter festlegen, welche Aufträge berücksichtigt werden und ob beispielsweise eine Statusänderung erfolgen soll, nachdem die Rücksendescheine erzeugt wurden.

[.instruction]
Rücksendescheine erzeugen:

. Öffnen Sie das Menü **Aufträge » Fulfillment » Rücksendeschein erzeugen**.
. Nehmen Sie die Einstellungen anhand <<tabelle-einstellungen-fulfillment-ruecksendeschein>> vor.
. Klicken Sie auf das **Zahnrad**, um die Rücksendescheine zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei**, welche die zugehörigen Rücksendescheine aller von Ihnen durch die Suchfilter bestimmten Aufträge beinhaltet.

[[tabelle-einstellungen-fulfillment-ruecksendeschein]]
.Optionen im Menü *Rücksendeschein erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Auftragsstatus**
|Aus der Liste den Status der Aufträge wählen, die für die Erstellung der Rücksendescheine berücksichtigt werden sollen.

|**Eigner**
|Wählen Sie einen Eigner aus, für dessen Aufträge die Rücksendescheine erzeugt werden sollen oder die Option **ALLE**, wenn für alle Eigner die Rücksendescheine erzeugt werden sollen.

|**Standort**
|Wählen Sie einen Standort aus, für den die Rücksendescheine erzeugt werden sollen.

|**Lager**
|Wählen Sie ein Lager oder **ALLE** aus.

|**Zahlungsart**
|Wählen Sie eine der Zahlungsarten oder *ALLE* aus.

|**Sortierung**
|Legen Sie fest, wie die erzeugten Rücksendescheine sortiert werden sollen. Die Optionen **Auftrags-ID**, **Kunden-ID** und **Artikel-ID** geben verschiedene Sortierungen aus.

|**Limit**
|Legen Sie fest, wie viele Rücksendescheine maximal pro Durchgang erzeugt werden. Das Maximum liegt bei *200* Rücksendescheinen.

|**Ändere Auftragsstatus**
|Wählen Sie einen Status, in den die Aufträge nach Erzeugung der Rücksendescheine wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

|**Kommentar**
|Sie können hier einen Text verfassen, der später auf allen erzeugten Rücksendescheinen unterhalb der Artikelpositionen erscheint. Die Eingabe ist optional.
|====
