= BillSAFE
:lang: en
include::{includedir}/_header.adoc[]
:keywords: BillSAFE. payment method
:description: Payment in plentymarkets: Set up the interface to BillSAFE in your plentymarkets system.
:position: 30

**link:http://www.billsafe.de/[BillSAFE^]** is a provider for payment on invoice in online trade. Meanwhile, payment on invoice of BillSAFE was integrated with PayPal. Payment on invoice is now part of the new PayPal product **<<order-processing/payment/paypal-plus#, PayPal PLUS>>**.

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets. After you selected a payment method, pre-validations will be carried out.

[#20]
=== Payment process with BillSAFE

The payment process varies depending on the respective BillSAFE payment method.

[.subhead]
Rechnungskauf - 1500 (payment on invoice)

An additional button for completing the sale will be displayed in the order overview. You can change the button as you wish under **CMS » Web design » Buttons » BillSAFE Rechnungskauf** (payment on invoice). After clicking on the button, the customer is forwarded to BillSAFE where the data for BillSAFE must be confirmed. After data confirmation, the order is completed and created. The customer will be forwarded to the order confirmation page.

[.subhead]
Rechnungskauf Telefon - 1502 (payment on invoice: telephone)

This payment method is only available to the seller and can therefore only be selected in the backend. After this payment method was selected, the seller has to complete the purchase for the customer in the checkout process. After clicking on the button, the seller will be forwarded to BillSAFE. The seller has to call BillSAFE, complete the process with BillSAFE and enter the name of the person he or she talked to.

[.subhead]
Rechnungskauf Onsite - 1504 (payment on invoice: onsite)

The button **Place order** will be displayed in the order overview. In contrast to Rechnungskauf - 1500 (payment on invoice), the customer will not be redirected to BillSAFE after having clicked on this button. This way, the customer will complete the order process within your online store.

[#30]
=== Invoice and bank details

When an order is received, BillSAFE transfers the bank details to your plentymarkets system. These bank details will then automatically be used on the invoice when it is generated.

[#40]
== Registering with BillSAFE

BillSAFE is only available for sellers who are already registered for the service. New customers cannot register with BillSAFE anymore. Meanwhile, payment on invoice of BillSAFE was integrated with PayPal. Payment on invoice is now part of the new PayPal product **<<order-processing/payment/paypal-plus#, PayPal PLUS>>**.

[#50]
== Setting up BillSAFE in plentymarkets

Proceed as follows to set up the interface to BillSAFE in plentymarkets.

[.instruction]
Setting up the interface to BillSAFE:

. Go to **System » Orders » Payment » Methods**.
. Place a check mark next to the setting **Also show inactive**.
. Open the folder **DE**.
.  Click on **BillSAFE**. +
→ The **Settings** tab will open.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in table 1.
. **Save** the settings.

.setting up the interface to BillSAFE
[cols="a,a"]
|====
|Setting |Explanation

|**Merchant-ID;** +
**Merchant License;** +
**Public Key**
|Enter the information as received from BillSAFE.

|**Company logo**
|Save an icon or logo of your online store to be displayed in the BillSAFE checkout process. +
Format: gif, jpg or png. +
Maximum size: 130 x 60 px. +
__**Important**__: The company logo is a mandatory entry. +
The number **0** with underscore in the file name is automatically assigned and used by the plentymarkets system.

|**Activate test mode**
|Activate the test mode and check the BillSAFE functions before working live with the system.

// tr> <td><strong>Automatische Weiterleitung deaktivieren</strong></td> <td>In der Grundeinstellung wird der Besteller direkt nach Klick auf den Button <strong>Zahlungspflichtig bestellen</strong> zu BillSAFE weitergeleitet. Wenn bei dieser Option nun ein Häkchen gesetzt wird, wird diese Automatik deaktiviert und es erscheint der Button <strong>Weiter zu BillSAFE</strong>, der zur Weiterleitung angeklickt werden muss.<br /> <i><b>Wichtig:</b></i> Ein korrekter Zahlungsprozess ist nur direkt aus dem Webshop-Bestellvorgang möglich über Klick auf den Button <strong>Zahlungspflichtig bestellen</strong>. Andernfalls kann es zu Fehlfunktionen bei der Datenübermittlung an den Zahlungsanbieter kommen.</td> </tr

// tr> <td><strong>BillSAFE-Logo</strong></td> <td>Die Logo-ID aus dem BillSAFE-Händlerportal speichern, um das Logo anzuzeigen.</td> </tr

|**Minimum order value**
|Enter the minimum order value that has to be reached.

|**Maximum order value**
|Enter the maximum order value that is permitted.

2+|**Arranged BillSAFE payment surcharges**

|**Payment surcharge 1**
|Enter a payment surcharge in the **Settings** tab. Use the option **Domestic (surcharge)**. The surcharge will be displayed here after saving the settings. +
__**Important**__: You have to agree on the payment surcharges with BillSAFE. Surcharges which are too high or which have not been arranged with BillSAFE will result in errors or will interrupt your customers' purchase process.
|====

[#55]
== Activating payment methods

For BillSAFE, multiple payment methods are available. Go to **<<order-processing/payment/managing-payment-methods#20, System » Orders » Payment » Payment methods>>** to activate the payment methods. In addition, check the settings for **Permitted payment methods** in the **<<order-processing/payment/managing-payment-methods#30, customer classes>>** and for **Blocked payment methods** in the **<<order-processing/fulfilment/preparing-the-shipment#1000, shipping profiles>>**.

[IMPORTANT]
.Payment on invoice plus customer validation via telephone
====
The seller uses BillSAFE to process payments over the phone.
====

[#60]
== Setting up shipping service providers

Set up **<<order-processing/fulfilment/preparing-the-shipment#700, shipping service providers>>** for BillSAFE. The BillSAFE interface requires a shipping service provider which has to be authorised by BillSAFE. These are: DP, DHL, DPD, UPS, GLS, Hermes, TNT, FEDEX.

[#70]
== Automatically sending shipping confirmations

Only create the event procedures for the **payment method BillSAFE**. Otherwise unintended messages could be triggered. If you select multiple payment methods in the **Filter** tab, then the message that was triggered for BillSAFE will also be sent to all of the other payment providers that were selected. Set up an <<basics/automation/event-procedures#, **event procedure**>> to automatically send shipping confirmations when the outgoing items are booked.

[.collapseBox]
.Setting up an event procedure
--
.  Go to **System » Orders » Events**.
.  Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
.  Enter a name.
.  Select the **event** listed in table 2.
. **Save** the settings.
.  Pay attention to the explanations given in table 2 and carry out the settings as desired.
.  Place a check mark next to the option **Active**.
. **Save** the settings.
--
.event procedure for sending automatic shipping confirmations to BillSAFE
[cols="a,a,a"]
|====
| Setting | Option | Selection

|**Event**
|**Order change: Outgoing items booked**
|

|**Filter**
|**Order &gt; Payment method**
|**Payment on invoice with BillSAFE**

|**Procedure**
|**Shipping &gt; Send shipping confirmation to BillSAFE**
|
|====

[#80]
== Automatically sending returns

There are three ways to report a **return** to BillSAFE. You could either report a return to BillSAFE when a return was created, when the return is set to a specific status or when a credit note is set to a specific status. However, only set up one event procedure to automatically report returns to BillSAFE. Set up an <<basics/automation/event-procedures#, **event procedure**>> to automatically send returns to BillSAFE. For further information about creating returns, refer to the **<<order-processing/orders/managing-sales-orders#return, Return>>** page of the manual.

[.collapseBox]
.Setting up an event procedure
--
. Go to **System » Orders » Events**.
. Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
. Enter a name.
. Select the **event** listed in table 3.
. **Save** the settings.
. Pay attention to the explanations given in table 3 and carry out the settings as desired.
. Place a check mark next to the option **Active**.
. **Save** the settings.
--
.event procedure for sending automatic returns to BillSAFE
[cols="a,a,a"]
|====
|Setting |Option |Selection

|**Event**
|**Order generation: New return**
|

|**Filter 1**
|**Order &gt; Order type**
|**Return**

|**Filter 2**
|**Order &gt; Payment method**
|**Payment on invoice with BillSAFE**

|**Procedure**
|**Return &gt; Send return to BillSAFE**
|
|====

[.subhead]
Reporting a return when the status changes

Instead of reporting a return to BillSAFE when creating a new return, it is possible to use the event **Status change** to report a return. Use this event in order to report checked returns only to BillSAFE or when you want to report a return to BillSAFE when a credit note was created. To do so, create an **order status** for BillSAFE returns or for BillSAFE credit notes and select this status as an event in the event procedure. +
If you want to report a return when a credit note was created, you still have to create a return for the order. In this case, carry out the steps in the following order:

* Create a return for the order
* Create a credit note for the return
* Set the credit note's status that triggers the event procedure

Only set up one event procedure to report returns to BillSAFE.

[#90]
== Automatically sending cancellations

Set up an <<basics/automation/event-procedures#, **event procedure**>> to automatically send cancellations to BillSAFE.

[.collapseBox]
.Setting up an event procedure
--
. Go to **System » Orders » Events**.
. Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
. Enter a name.
. Select the **event** listed in table 4.
. **Save** the settings.
. Pay attention to the explanations given in table 4 and carry out the settings as desired.
. Place a check mark next to the option **Active**.
. **Save** the settings.
--
.event procedure for sending automatic cancellations to BillSAFE
[cols="a,a,a"]
|====
|Setting |Option |Selection

|**Event**
|**Order change: Status change**
|Select the status for cancellations.

|**Filter 1**
|**Order &gt; Order type**
|**Order**

|**Filter 2**
|**Order &gt; Payment method**
|**Payment on invoice with BillSAFE**

|**Procedure**
|**Return &gt; Send return to BillSAFE**
|
|====

[#100]
== Customising the invoice template for BillSAFE orders

If you use BillSAFE and you generate invoices for the orders that are paid for with BillSAFE invoices, then make sure to display BillSAFE's bank details on the invoice rather than your own bank details. This is done automatically with a payment instruction. Proceed as described below to use your own **<<order-processing/orders/order-documents#170, PDF template>>**.

[IMPORTANT]
.Respect the payment instruction width
====
In order to display the bank details of BillSAFE correctly on your invoice, save a width of 120 millimetres for the payment instruction in the **System » Client » Select client » Locations » Select location » Documents » Invoice** menu.
====

[.instruction]
Using own PDF template:

. Go to **System » Client » Select client » Locations » Select location » Documents » Invoice**.
. Click on the **PDF template** tab.
. Click on the **New template** tab.
. Select **BillSAFE** from the drop-down menu to save the template for BillSAFE.
. Use the **File** area to select the PDF file on your computer.
. Click on **Open**.
. **Save** the settings. +
→ The PDF file will be uploaded and listed in the **Templates** tab.

Before sending invoices to customers, find out whether customers already receive invoices from BillSAFE. In other words, make sure the customer does not receive 2 invoices.

[#110]
== Reporting a direct payment

If the invoice amount was incorrectly sent to you instead of to BillSAFE, then you can directly report this to BillSAFE. If you want to use the system to report a **direct payment to BillSAFE**, then the BillSAFE interface data has to be saved for the **default store**. This is true even if the payment method was only activated for a client (store).

[.instruction]
Reporting a direct payment:

. Go to **Orders » Edit orders**.
. Open the BillSAFE order. +
→ The **Overview** tab will open.
. Open the **Payment** tab.
. Under **Inform BillSAFE about a direct payment that was received**, enter the invoice amount.
. Click on **Report direct payment**. +
→ The invoice amount will be reported.

[#120]
== Sending a credit note

Individual **credit note amounts** can be reported to BillSAFE.

[.instruction]
Sending a credit note:

. Go to **Orders » Edit orders**.
. Open the BillSAFE order. +
→ The **Overview** tab will open.
. Click on the **Settings** tab.
. Under **Send credit note to BillSAFE**, enter the amount.
. Click on **Send credit note**. +
→ The credit note amount will be sent.

[#130]
== Reporting payment prolongation

You can report to BillSAFE that the payment will be **prolonged** between **1** and **10** days. This is useful, e.g. if the purchaser has let you know that he or she will return an item, but you have not yet received the item in question. By using the payment prolongation, you can postpone or pause the dunning procedure.

[.instruction]
Reporting payment prolongation:

. Go to **Orders » Edit orders**.
. Open the BillSAFE order. +
→ The **Overview** tab will open.
. Click on the **Settings** tab.
. Under **BillSAFE payment prolongation**, enter a value between 1 and 10.
. Click on **Report payment prolongation**. +
→ The payment prolongation will be reported.

[#140]
== Retrieving status history

**Events**, **prolonged payments**, **newly created invoices** and reported **credit notes** are all logged in the order overview.

[.instruction]
Retrieving status history:

. Go to **Orders » Edit orders**.
. Open the BillSAFE order. +
→ The **Overview** tab will open.
. Open the **Status history** tab. +
→ An overview of all logged events will be displayed.

[TIP]
.Payment rejected by BillSAFE - What now?
====
If BillSAFE **rejects** a payment, then the payment method will be switched to **cash in advance** (requirement by BillSAFE) - a message will also be displayed in the order history.
====
