= Configuring currencies
:lang: en
include::{includedir}/_header.adoc[]
:keywords: currency, standard currency, live conversion
:description: Payment in plentymarkets: Configure currencies in your plentymarkets system and change the display options of currencies in the online store.
:position: 4

You can work with different currencies in plentymarkets. This is useful if you sell your items in several different countries. This page describes the currency settings that relate to all of the stores in your plentymarkets system. In addition, further currency settings relate to individual stores. This page also teaches you how to insert template variables under <<omni-channel/online-store/setting-up-clients/cms#web-design, CMS » Web design>> so that your customers can switch from one currency to another.

[#10]
== Supported currencies

The following currencies are currently supported in plentymarkets:

.currencies in plentymarkets
[cols="a,a"]
|====
|ISO |Currency

|*AED*
|United Arab Emirates dirham

|*ARS*
|Argentine peso

|*AUD*
|Australia, Australian dollar

|*BGN*
|Bulgaria, Bulgarian lev

|*BHD*
|Bahraini dinar

|*BRL*
|Brazil, Brazilian real, plural: Reais

|*CAD*
|Canada, Canadian dollar

|*CHF*
|Switzerland, Swiss franc

|*CNY*
|People's Republic of China, Renminbi

|*CZK*
|Czech Republic, Czech koruna

|*DKK*
|Denmark, Danish krone

|*EUR*
|Euro

|*GBP*
|Great Britain, pound sterling

|*HKD*
|Hong Kong dollar

|*HRK*
|Croatian kuna

|*HUF*
|Hungary, forint

|*IDR*
|Indonesian rupiah

|*INR*
|India, Indian rupee

|*JPY*
|Japan, Japanese yen

|*MXN*
|Mexico, Mexican peso

|*MYR*
|Malaysian ringgit

|*NOK*
|Norway, Norwegian krone

|*NZD*
|New Zealand dollar

|*PHP*
|Philippine peso

|*PLN*
|Poland, zloty

|*QAR*
|Qatari riyal

|*RON*
|Romania, Romanian leu

|*RUB*
|Russian Federation, ruble

|*SEK*
|Sweden, Swedish krona

|*SGD*
|Singapore dollar

|*THB*
|Thai baht

|*TRY*
|Turkey, Turkish lira

|*TWD*
|New Taiwan dollar

|*UAH*
|Ukrainian hryvnia

|*USD*
|USA, US dollar

|*VND*
|Vietnamese dong

|*XCD*
|Eastern Caribbean dollar

|*ZAR*
|South African rand
|====

[#20]
== Currency conversion

In the <<item/managing-items#870, Sales prices>> menu, you activate the *Currency: Live conversion* option to convert the store currency into foreign currencies. Additionally, go to *System » Orders » Payment » Currencies* and configure the currency settings. To do so, proceed as described below.

[.instruction]
Currency conversion:

. Go to *System » Orders » Payment » Currencies*.
. Carry out the settings as desired. Pay attention to the information given in <<table-currency-settings>>.
. *Save* the settings.

[[table-currency-settings]]
.Currency settings
[cols="a,a"]
|====
|Setting |Explanation

|*Standard currency*
|Select a <<order-processing/payment/currencies#30, system currency>> from the drop-down list.

|*Automatically update conversion factors daily*
|This option specifies whether or not the conversion factors should automatically be updated on a daily basis. +
*Yes* = The conversion factors will automatically be updated overnight. Furthermore, a new option will appear directly below this field. The option is called *Last automatic update* (see next option). +
*No* = A *reload icon* will be displayed for each currency. This icon can be used to manually update the conversion factors any time.

|*Last automatic update*
|Display the last update of the conversion factors. This field is only visible if the option *Automatically update conversion factors daily* was set to *Yes*.

|*Conversion factor for standard currency into EUR, USD, CHF...*
|When opening the menu, you will see that there are already exchange rates, but that they may need to be updated. Click on the *reload icon* to have the new exchange rate calculated. Alternatively, set the option *Automatically update conversion factors daily* to *Yes*.
|====

[#30]
== Specifying the system currency

If you work with different currencies, then you will have to define one currency as the standard currency for the system. This currency is the default currency if no other is selected. The system's standard currency is *EUR* (Euro).

In plentymarkets, orders are always created in the standard currency. Each order shows which currency was selected by the customer. If an order was not made in the standard currency, then the current exchange rate is also saved with the order. These values can be used to analyse the order data any time or they can be used e.g. for automatic notifications.

[.instruction]
Specifying the system currency:

. Go to *System » Orders » Payment » Currencies*.
. Select a currency under *Standard currency*.
. *Save* the settings.

This setting is not necessarily identical to the currency <<order-processing/payment/currencies#70, displayed in your online store>>. A different standard currency can be defined for each store and language. Go to *System » Client » Select client » Online store » Currency* to carry out this setting.

[#40]
== Displaying the currency symbol in the order process

Select whether currencies are to be displayed as ISO codes or as symbols in the online store. For example, euro would be displayed with the ISO code *EUR* or with the symbol *€*. This setting controls how the currency is displayed during the *order process* and in the *My account* area. <<order-processing/payment/currencies#70, Template variables and functions>> are used to display the currency in other areas of the online store.

[.instruction]
Displaying the currency symbol in the order process:

. Go to *System » Client » Select client » Online store » Currency*.
. Select the option *Symbol* from the *Symbol* drop-down list.
. *Save* the settings.

// h2>Live-Umrechnung aktivieren<a id="50." name="50."></a></h2> <p>Der Standardpreis wird per Live-Umrechnung in die Währung umgerechnet und im Webshop angezeigt. Die Preise der verwendeten Währungen werden vom System ermittelt. Der Vorteil der Live-Umrechnung liegt darin, dass die Preise der Währungen nicht bei den Artikeln hinterlegt werden müssen, was bei umfangreichem Sortiment mit großem Aufwand verbunden ist. Um die Live-Umrechnung zu aktivieren, gehen Sie wie im folgenden beschrieben vor.</p> <h5>Live-Umrechnung aktivieren:</h5> <ol><li>Öffnen Sie das Menü <strong>System » Mandant (Shop) » Standard » Webshop » Währung</strong>.</li> <li>Wählen Sie die Option <strong>Live-Umrechnung</strong> für die Einstellung <strong>Währungsumrechnung</strong>.</li> <li><strong>Speichern</strong> Sie die Einstellungen.</li> <li>Öffnen Sie das Menü <strong>System » Aufträge » Zahlung » Währungen</strong>.</li> <li>Wählen Sie eine Option für die Einstellung <strong>Umrechnungsfaktoren täglich automatisch aktualisieren</strong>.</li> <li><strong>Speichern</strong> Sie die Einstellungen.</li></ol
[#60]
== Specifying the standard currency for the online store

If you offer different languages for your online store, you can specify a standard currency for every language. If you work with several clients (stores), then you can carry out the settings for each store individually. If you want to carry out these settings for a different store, then replace the menu point *Standard* with the name of the store.

[.instruction]
Specifying the standard currency for the online store:

. Go to *System » Client » Select client » Online store » Currency*.
. Select a standard currency for each language of the online store under *Standard currency*.
. *Save* the settings.

[#70]
== Customising the currency displayed in the online store

You can allow your customers to switch from one currency to another. This is useful, e.g. if you run a German store and you sell your items in Germany with the currency EUR and in Switzerland with the currency CHF. The following template functions make it possible to switch from one currency to another:

*$Link_Currency(EUR)* +
*$Link_Currency(CHF)* +
*$Link_Currency(USD)*

These are inserted with the following codes:

*&lt;a href="$Link_Currency(EUR)"&gt;EUR&lt;/a&gt;* +
*&lt;a href="$Link_Currency(CHF)"&gt;CHF&lt;/a&gt;* +
*&lt;a href="$Link_Currency(USD)"&gt;USD&lt;/a&gt;*

[.instruction]
Inserting template functions:

. Go to *CMS » Web design*.
. Open the folder *Layout » PageDesign*.
. Open a template, e.g. *PageDesignContent*.
. Copy the desired code above and insert it into the desired location within the template.
. *Save* the settings.

[TIP]
.Replace currency symbols
====
If you previously worked with currency symbols, then replace them with the template variable *$Currency*. This template variable represents the currency currently selected in the online store.
====
