= ExperCash
:lang: en
include::{includedir}/_header.adoc[]
:keywords: ExperCash, payment method
:description: Payment in plentymarkets: Set up the interface to ExperCash in your plentymarkets system.
:position: 40

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *ExperCash* in Callisto online stores. The following instructions are not valid for Ceres stores!
====

In April 2016, ExperCash GmbH merged into MasterCard Payment Gateway Services Client Finance Ltd. ExperCash is a payment provider for complete financial supply chain management. ExperCash payment solutions assist online shops in handling all processes relating to their payment transactions.

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets.

[#20]
=== Payment process

The payment method is selected in the online store. Afterwards, the customer is forwarded directly to ExperCash. The additional content is made available in an iframe. The customer enters their data here. In other words, the data is not entered in the online store, but rather in ExperCash. Once the customer has entered and confirmed the data, they will be forwarded to the order confirmation page. The ExperCash iframe currently supports the following languages: German, English, French, Italian and Spanish. The language that the customer selected in the checkout will automatically be used for payment processing with ExperCash.

[#30]
=== SSL certificate

You need to have an <<basics/working-with-plentymarkets/plentymarkets-account#ssl-certificate, SSL certificate>> in order to correctly use the payment method.

[WARNING]
.Ask your bank
====
Ask your bank whether it can process payments with iframe before you integrate this payment method.
====

[#40]
=== Available ExperCash payment methods

Below you will find an overview of the ExperCash payment methods that are available for plentymarkets. They are displayed along with the corresponding System ID in parentheses.

* Giropay (820)
* Credit card (850)
* Credit card authorisation/reservation (840)
* Debit (810)
* Sofortbanking (830)
* Payment method selection by the end customer (800)

[#50]
=== Currencies

All amounts will be converted into the online store's standard currency before payment takes place. All end customers pay in this currency. A separate contract has to be made with ExperCash for credit card payments in each individual currency. This is why plentymarkets always converts into the standard currency of the online store.

[#60]
== Registering with ExperCash

Register with ExperCash in order to activate it in plentymarkets. To do so, contact MasterCard Payment Gateway Services Client Finance Ltd. via email to link:mailto:service_mpgs_dach@mastercard.com[service_mpgs_dach@mastercard.com].

[#70]
== Setting up ExperCash in plentymarkets

Proceed as described below to set up the interface to ExperCash.

[.instruction]
Setting up the interface to ExperCash:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *DE*.
.  Click on *ExperCash*. +
→ The *Interface* tab will open.
.  Expand the client.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-expercash-interface>>.
. *Save* the settings.

[[table-setup-expercash-interface]]
.setting up the interface to ExperCash
[cols="1,3"]
|====
|Setting |Explanation

|*Pop-up ID*
|Enter the access identification for the store, that you received from ExperCash.

|*Authorisation key*
|Enter the iframe authorisation key, that you received from ExperCash.

|*CSS URL (optional)*
|Customise the appearance of the ExperCash iframe with the help of a CSS file. If possible, try to use an https URL.

|*Profile ID*
|Enter the profile number. Enter *1* if you are not sure. This value is usually applicable since there must be at least one profile.

2+|Client (store) options

|*Activate access data for all clients (stores)*
|Only visible if clients (stores) were set up. Activate to apply the account settings saved for the main store by clicking on *Add account* for all clients (shops). This setting is dominant over the settings saved for each client. Deactivate to use separate access data for your clients (stores). Online stores that do not have account settings saved for them cannot be used with ExperCash. +
Go to <<omni-channel/online-store/setting-up-clients/online-store#, System » Client » Select client » Online store » Settings>> and make sure that you have selected the option *Enable login for every store* in the line *Login*. This makes it possible to support several clients.
|====

[#80]
== Activating the payment method

Set up and activate the ExperCash <<order-processing/payment/managing-payment-methods#20, payment methods>> in the *Settings* tab of the payment methods. In addition, check the settings for *Permitted payment methods* in the <<order-processing/payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<order-processing/fulfilment/preparing-the-shipment#1000, shipping profiles>>.
