= Klarna Checkout UK
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Klarna Checkout UK, payment method
:description: Payment in plentymarkets: Set up the interface to Klarna Checkout UK in plentymarkets.
:position: 20

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *Klarna Checkout UK* in Callisto online stores. The following instructions are not valid for Ceres stores!
====

In plentymarkets, Klarna Checkout UK is the name for the checkout solution offered by Klarna in and for the United Kingdom. This checkout solution includes different countries of delivery and payment methods than the checkout solution provided for Germany. Klarna Checkout UK is responsive.

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets.

[IMPORTANT]
.Klarna Checkout and store design
====
Note that the following conditions must be met before integrating Klarna Checkout UK successfully in plentymarkets:

* Use of the standard design Callisto (Version 2 or higher)
* Use of the individual order process
* Safe handling of the plentymarkets CMS
* Experience with integrating payment providers
====

[#20]
=== Payment process with Klarna Checkout UK

The payment process can be described as follows: The customer enters their email address and the postcode of the invoice address in Klarna Checkout UK. For Klarna customers, the invoice address is filled in automatically. The same happens if the customer is logged in in your online store. The customer clicks on Purchase now. The customer can select a different payment method during the order confirmation. They can choose from the payment methods available in Klarna Checkout UK. The page for switching the payment method is hosted by Klarna. The customer receives the invoice directly from Klarna. For the customer, the order process is completed at this point. An order will be created in your plentymarkets system.

[#30]
=== SSL certificate

An iframe is used to integrate Klarna Checkout UK directly in plentymarkets. Thus, an <<basics/working-with-plentymarkets/plentymarkets-account#ssl-certificate, SSL certificate>> is required for using this payment method.

[#40]
=== Included payment methods

Klarna Checkout UK combines the following payment methods:

* American Express
* Maestro
* VISA
* VISA electron
* MasterCard
* Pay after delivery
* Further <<order-processing/payment/klarna-checkout-uk#80, external payment methods>>

== Registering with Klarna

[#50]
Before you set up Klarna Checkout UK in your plentymarkets system, you have to register with link:https://www.klarna.com/uk/business/sell-online-with-klarna[Klarna^].

== Setting up Klarna Checkout UK in plentymarkets

[#60]
Proceed as described below to set up the interface to Klarna Checkout UK.

[.instruction]
Setting up the interface to Klarna Checkout UK:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the option *Also show inactive*.
. Open the folder *International*.
.  Open the folder *Klarna*.
. Click on *Klarna Checkout UK*. +
→ The *settings* tab will be opened.
. Click on the *Interface* tab.
. Expand a Client (store).
. Carry out the settings as desired. Pay attention to the information given in <<table-setup-klarna-checkout-uk-interface>>.
. *Save* the settings.

[[table-setup-klarna-checkout-uk-interface]]
.setting up the interface to Klarna Checkout UK
[cols="1,3"]
|====
|Setting |Explanation

2+|General settings

|*Operating mode*
|*Live* = productive or active mode  +
*Test* = test mode. This mode allows you to test the data transfer between your system an Klarna. Any order made while the test mode is active will be ignored by Klarna. This means the invoice amount will not be requested from the test customer and you will not receive any payment. Furthermore, Klarna will not charge any fee for orders made while the test mode is active.

|*Country assignment*
|Select a country of delivery that will be used as standard country of delivery.

|*Show external payment providers*
|Activate to permit external payment providers. +
The following payment methods can be offered in combination with Klarna Checkout UK: +
PayPal, Amazon Pay, cash in advance, Giropay, cash payment, direct debit, cash on delivery +
Check the spelling of these payment methods with Klarna because they need to be set up in plentymarkets exactly as specified by Klarna. Only <<order-processing/payment/managing-payment-methods#20, active payment methods>> are taken into account.

2+|Klarna identification

|*Merchant ID*
|Enter the Merchant ID that you received from Klarna.

|*Security key (SharedSecret)*
|Enter the Security key that you received from Klarna.

2+|Mandatory entries

|*Date of birth*, +
*Delivery address*, +
*Form of address*
|Activate the options that should be mandatory for customers during the order process.

2+|Customising the checkout

|*Button colour*,  +
*Background colour of check boxes*,  +
*Button text colour*,  +
*Colour of check marks*, +
*Link colour*, +
*Header colour*
|Enter hexadecimal codes for the colours.  +
Make sure to choose different colours for the text and the button because the text cannot be read if the colours are the same. The same applies to the colour of the check box and the check mark.
|====

[#70]
== Activating the payment method

Set up and activate the <<order-processing/payment/managing-payment-methods#20, payment method>> Klarna Checkout UK in your plentymarkets system. In addition, check the settings for *Permitted payment methods* in the <<order-processing/payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<order-processing/fulfilment/preparing-the-shipment#1000, shipping profiles>>.

[#80]
== Permitting external payment methods in the Klarna Checkout UK

Besides the payment methods that are included, you can also offer your customers some external payment methods via Klarna Checkout UK. However, you need Klarna to agree to these external payment methods. Therefore, contact Klarna before setting up external payment methods.

You need to spell the external payment methods exactly as specified by Klarna. Otherwise, Klarna will not accept the payment method. Check the exact spelling with Klarna before setting them up. The logos for the external payment providers also must have the exact size specified by Klarna. Some examples are given below. The default logos saved in plentymarkets are too big for the Klarna Checkout. +
The available payment methods and image sizes are:

* PayPal (276 x 48px)
* Amazon Pay (276 x 48px)
* Cash in advance (69 x 24px)
* Giropay (69 x 24px)
* Cash payment (69 x 24px)
* Direct debit (69 x 24px)
* Cash on delivery (69 x 24px)

Klarna continuously adds new external payment methods to the Klarna Checkout UK. Therefore, this list may not be complete.

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Open the folder *Klarna*.
. Click on *Klarna Checkout UK*. +
→ The *settings* tab will be opened.
. Click on the *Interface* tab.
.  Expand the client.
. Activate the setting *External payment providers*.
. *Save* the setting.

Set up and activate the desired <<order-processing/payment/managing-payment-methods#20, payment methods>> in the *System » Orders » Payment » Methods* menu in your plentymarkets system.

[#90]
== Displaying Klarna Checkout UK in the online store

Use the following container to add the Klarna Checkout UK to your design: *{% Container_CheckoutKlarnaPayment() %}*. You can enter the function into a template or into a category of the type container. How to add the Klarna Checkout UK as an order step into your Callisto Light 3 design by replacing the order step Purchase is described below. Create a new category of the type *Container* and replace the standard order step Purchase by this new category.

[WARNING]
.No changes to the active design
====
Do not make changes to your active design. Before making changes to the design, make a backup copy so that you can restore the original state of the design.
====

[.instruction]
Creating a category of the type container:

. Go to *Item » Categories*.
. Click on *New category*. +
→ The *Create new category* window will open.
. Enter a name, e.g. Klarna Checkout UK.
. Click on *Create*. +
→ The category will be opened and the *Settings* tab will be displayed.
. Select the option *Container* as the *Type*.
. Click on the *Description 1* tab.
. Insert the container *{% Container_CheckoutKlarnaPayment() %}* into the text field.
. *Save* the settings.

Carry out additional settings, such as selecting the client, in the *Settings* tab. Afterwards, add the category as an order step to your order process.

[.instruction]
Adding a category as order step:

. Go to *CMS » Web design*.
. Click on *Settings*.  +
→ The *Design settings* window will open.
. Click on the *Clients* tab.
. Click on a client.
. Click on the *Order process* tab.
. Click on *Search* for the *3rd order process step*.
. Select the newly created *Klarna Checkout UK* category.
. Click on *Select*.
. *Save* the settings. +
→ The order step will be added.

[#100]
== Automatically sending shipping confirmations

Set up the following event procedures in order to inform Klarna UK when items are shipped, orders are cancelled and credit notes or refunds are paid. Set up an <<basics/automation/event-procedures#, event procedure>> to automatically send shipping confirmations to Klarna. Payment providers usually wait for the shipping confirmation from the merchant before they disburse and transfer the amount paid by the customer to the merchant’s account.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
. Enter a name.
. Select the *event* listed in table 2.
. *Save* the settings.
. Pay attention to the explanations given in table 2 and carry out the settings as desired.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for sending automatic shipping confirmations to Klarna Checkout UK
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order change: Outgoing items booked*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order* +
Delivery order - optional for partial delivery

|*Filter 2*
|*Order &gt; Payment method*
|*Klarna Checkout UK*

|*Procedure*
|*Shipping &gt; Send shipping confirmation to Klarna UK*
|
|====

== Automatically reporting refunds

[#110]
To refund customers the total purchase amount, create a *Return order*. Set up an <<basics/automation/event-procedures#, event procedure>> to automatically send refunds to Klarna UK. For further information about creating returns, refer to the <<order-processing/orders/managing-sales-orders#return, Return>> page of the manual.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
. Enter a name.
. Select the *event* listed in table 3.
. *Save* the settings.
. Pay attention to the explanations given in table 3 and carry out the settings as desired.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--

.event procedure for sending automatic refunds to Klarna Checkout UK
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order generation: New return*
|

|*Filter*
|*Order &gt; Payment method*
|*Klarna Checkout UK*

|*Procedure*
|*Payment methods &gt; Send refund to Klarna UK*
|
|====

[#120]
== Automatically sending cancellations

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically send cancellations to Klarna UK.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
. Enter a name.
. Select the *event* listed in table 4.
. *Save* the settings.
. Pay attention to the explanations given in table 4 and carry out the settings as desired.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for sending automatic cancellations to Klarna Checkout UK
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change*
| Select status for *cancelled orders*.

|*Filter*
|*Order &gt; Order type*
|*Order*

|*Filter*
|*Order &gt; Payment method*
|*Klarna Checkout UK*

|*Procedure*
|*Payment methods &gt; Send cancellation to Klarna UK*
|
|====

[#130]
== Reporting credit notes

Credit notes are usually used if only a partial amount of the total order amount should be refunded. To refund partial amounts, use the order type *credit note* and enter the amount that you would like to refund. Use your own discretion to decide how much is refunded. Partial amounts need to be entered manually since it is possible to enter a different amount for every order. Hence, it is not possible to automate this process.

[.instruction]
Creating a credit note to refund a partial amount:

. Go to *Orders » Edit orders*.
. Open the Klarna Checkout UK order. +
→ The *Overview* tab will open.
. Select the option *create* from the *Credit note...* drop-down list. +
→ The credit note will be created.
. Open the newly created credit note.
. Click on the *Settings* tab.
. Click on *Klarna Checkout UK Refund* under *Refund*.
. Enter the amount that you want to refund.
. Click on *Transfer refund*. +
→ The sum will automatically be reported to Klarna Checkout UK.

[#140]
== Checking the payment status

You can check the payment status in the *Payment* tab of an order. The meanings of the payment statuses and when a payment is added to the list will be explained next. The payment entries refer to the *Payment* tab of the main order.

[#150]
=== Status progression for complete shipping

[.subhead]
confirmed &gt; received

If Klarna accepted the customer to pay via Klarna, a payment will be created. The payment receives the status *confirmed*. Now you need to send the items to the customer and the shipping confirmation to Klarna. After Klarna received the shipping confirmation, they will transfer the amount to your account. The payment receives the status *received*.

[#160]
=== Status progression for partial shipping

[.subhead]
confirmed &gt; partially received &gt; received

If Klarna accepted the customer to pay via Klarna, a payment will be created. The payment receives the status *confirmed*. You only send part of the order to the customer because you do not have all items in stock. Let’s assume the customer ordered 5 items, but you only have 3 of them in stock. You create a delivery order for these 3 items and send them immediately. Then you book the outgoing items for the delivery order. A shipping confirmation for the *delivery order* will be sent to Klarna if the filter *Order &gt; Order type* in the event procedure for automatically sending shipping confirmations also includes delivery orders. Sending the shipping confirmation will cause a further payment to be added to the list in the main order. The payment will receive the status *received*. The status of the first payment will change from *confirmed* to *partially received*. Next create a second delivery order for the remaining items and book the outgoing items for the delivery order. A third payment will be created in the main order after you have sent the shipping confirmation for the remaining items. This payment receives the status *received*. The status of the first payment will change from *partially received* to *received*. +
In the scenario described above a payment will be created for each delivery order. Once the whole original order was sent, the payment status of the first payment will change to *received*. +
Do not include *delivery orders* in the filter of the event procedure if you do not wish to send shipping confirmations for delivery orders to Klarna.

[#170]
=== Status progression for cancellations, credit notes or refunds

The payment listed in the *Payment* tab of the main order will receive the status *cancelled* if a cancellation is reported. +
If a credit note is reported to Klarna, a further payment will be created in the *Payment* tab of the main order and this payment receives the status *partially refunded*. A payment will also be listed in the credit note itself. The payment in the credit note will have the status *confirmed*. +
If a refund is reported to Klarna, a further payment is added to the list of the main order in the *Payment* tab. This payment will receive the status *refunded*. The payment in the refund itself receives the status *confirmed*.
