= Old online store: PayPal PLUS
:lang: en
include::{includedir}/_header.adoc[]
:keywords: PayPal Plus, payment method
:description: Payment in plentymarkets: Set up the interface to PayPal PLUS in your plentymarkets system.
:position: 11

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *PayPal PLUS* in Callisto online stores. For further information on using *PayPal PLUS* in Ceres online stores, refer to the detailed information in the plugin description available in the link:https://marketplace.plentymarkets.com/en/plugins/payment/PayPal_4690[plentyMarketplace^].
====

PayPal PLUS includes the payment method PayPal and additional payment methods such as credit card or debit. However, the payment methods debit and purchase on invoice are only available if Germany is selected as the country of delivery.

[#10]
== Opening a business account for PayPal PLUS

You need to link:https://www.paypal.com/gb/webapps/mpp/merchant[open a business account with PayPal^] before you can set up the payment method in plentymarkets. You will then receive information and access data, which you will need for setting up the function for your Callisto online store in plentymarkets.

[IMPORTANT]
.PayPal PLUS and store design
====
Note that the following conditions must be met before integrating PayPal PLUS successfully in plentymarkets:

* Use of the standard design Callisto (Version 2 or higher)
* Use of the individual order process
* Safe handling of the plentymarkets CMS
* Experience with integrating payment providers
====

[#20]
== Setting up PayPal PLUS for Callisto

This section explains how and where to select stores and countries of delivery for PayPal PLUS. It also explains how to enter data for the interface. You can only choose the countries of delivery that were set up under <<order-processing/fulfilment/preparing-the-shipment#100, System » Orders » Shipping » Shipping options » Tab: Countries of delivery>>.

[.instruction]
Setting up the PayPal PLUS interface:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Click on *PayPal PLUS*. +
→ The *Settings* tab will open.
. Click on the *Interface* tab.
. Expand a Client (store).
. Activate the *Test mode* if you want to make a few test purchases first.
. *Save* the settings.
. Click on *Add account*. +
→ You will be forwarded to PayPal.
. Log in.
. Confirm that plentymarkets should be allowed to access your PayPal account.  +
→ You will be redirected back to your plentymarkets system.
. Repeat steps 1 to 6.
. Enter your store name.
. Enter the URL to your logo. This makes it possible for PayPal to display your logo within PayPal's shopping cart.
. Select *Yes* if you want the access data to apply for all clients (stores).
. *Save* the settings.

[TIP]
.Test mode or live mode
====
Activate the Test mode if you want to make a few test purchases using the PayPal sandbox first. Note that you will be forwarded to a different address (sandbox) within PayPal when activating the test mode. Therefore, save the settings for the interface after activating the test mode before you add the account.
====

[#30]
== Activating payment methods

In addition to the payment method PayPal PLUS which you activate in the <<order-processing/payment/managing-payment-methods#20, System » Orders » Payment » Payment methods>> menu, additional payment methods such as credit card or debit are available. However, the payment methods debit and purchase on invoice can only be used if Germany is selected as the country of delivery. Set up and activate the desired <<order-processing/payment/managing-payment-methods#10, payment methods>> in your plentymarkets system. To display the logos of additional payment methods, upload the logos directly in the settings of the payment method with a maximum size of 100 x 25 px. In addition, check the settings for *Permitted payment methods* in the <<order-processing/payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<order-processing/fulfilment/preparing-the-shipment#1000, shipping profiles>>.

[IMPORTANT]
.Limitations for purchase on invoice
====
Purchase on invoice via PayPal PLUS is not available if the purchase value is less than 1.50 EUR or greater than 1,500.00 EUR. Furthermore, digital media cannot be purchased on invoice due to the impossibility of return.
====

[#40]
== Displaying PayPal PLUS in the Callisto online store

This section explains how to add PayPal PLUS to the individual order process in plentymarkets. This is done in several steps. First, PayPal PLUS is inserted in a category of the type *Container*.

[WARNING]
.No changes to the active design
====
Do not make changes to your active design. Before making changes to the design, make a backup copy so that you can restore the original state of the design.
====

[IMPORTANT]
.Calculating the order total
====
PayPal and plentymarkets use a different number of decimal places when calculating prices. As such, there may be slight rounding differences in the order total calculated by plentymarkets and PayPal. These differences are automatically settled in the background ensuring that the totals match in plentymarkets and PayPal. This is either done with a credit note or with an item to balance out the difference.
====

[#50]
=== Adding a category for the additional step in the order process

Shipping and payment need to take place in two different steps. Your customer should first select a shipping method and then this shipping price should be transferred to PayPal. Therefore, create a new category for selecting the payment method. Afterwards, edit the *Payment &amp; shipping* category which is included in Callisto Light by default.

[.instruction]
Creating a category of the type container:

. Go to *Item » Categories*.
. Click on *New category*. +
→ The *Create new category* window will open.
. Enter name, e.g. Select payment method.
. Click on *Create*. +
→ The category will be opened and the *Settings* tab will be displayed.
. Select the option *Container* as the *Type*.
. Click on the *Description 1* tab.
. Insert the code example. +
→ The code examples below are for versions 2 and 3 of Callisto Light.
. *Save* the settings.

[.subhead]
Code example for version 3 of Callisto Light:

[source,plenty]
----
include::assets/EX-EN-Order-Step-Payment-Methods-PayPalPlus.html[]

----

[.subhead]
Code example for version 2 of Callisto Light:

[source,plenty]
----
include::assets/EX-EN-Order-Step-Payment-Methods-PayPalPlus-Callisto2.html[]

----
[#60]
=== Editing the Payment &amp; shipping category

Next, you need to edit the Payment &amp; shipping category, which is included in Callisto Light 3 by default.

[.instruction]
Editing the Payment &amp; shipping category:

. Go to *Item » Categories*.
. Open the design's folder, e.g. the folder for Callisto Light 3.
. Open the category *Payment &amp; shipping*.
. Change the name in the *Settings* tab, e.g. to Shipping.
. Click on the *Description 1* tab.
. Delete the div container for displaying payment methods.
. *Save* the settings.

[#70]
=== Changing the order steps

Both the newly created category and the edited category need to be added to the order steps of the individual order process.

[.instruction]
Changing the order steps:

. Go to *CMS » Web design*.
. Click on *Settings*.  +
→ The *Design settings* window will open.
. Click on the *Clients* tab.
. Click on a client.
. Click on the *Order process* tab.
. Click on *Search* for the *6th order process step*.
. Select the *Shipping* category.
. Click on *Select*.
. Click on *Search* for the *7th order process step*.
. Select the newly created *Select payment method* category.
. Click on *Select*.
. Click on *Search* for the *8th order process step*.
. Select the *Order overview &amp; transaction* category.
. Click on *Select*.
. Click on *Search* for the *9th order process step*.
. Select the *Order process* category.
. Click on *Select*.
. *Save* the settings. +
→ The order steps will be updated.

[#80]
=== Customising the Purchase category

The Purchase category also needs to be customised to ensure that the order steps are carried out in the correct sequence.

. Go to *Item » Categories*.
. Open the design's folder, e.g. the folder for Callisto Light 3.
. Open the category *Purchase*.
. Click on the *Description 1* tab.
. Delete the list element for payment &amp; shipping.
. After the list element *Address*, insert list elements for the new order steps Shipping and Select payment method. +
→ Example code is displayed further below.
. Scroll farther down in the code and replace *Step 3* and *Step 4* with the 2nd code example underneath this description.
. *Save* the settings.

[source,plenty]
----
include::assets/EX-EN-Order-Steps-Purchase-PayPalPlus.html[]

----

[source,plenty]
----
include::assets/EX-EN-Order-Steps2-Purchase-PayPalPlus.html[]

----
[#90]
=== Customising the Order overview &amp; transaction category

You also need to edit the "Order overview &amp; transaction" category so that customers who want to change their entries are forwarded to the correct order step from the order overview.

. Go to *Item » Categories*.
. Open the design's folder, e.g. the folder for Callisto Light 3.
. Open the *Order overview &amp; transaction* category.
. Click on the *Description 1* tab.
. Search for the code *data-plenty="click:Redirect.toCheckoutTab('#shipping-payment')"*.
. Delete *shipping-* so that the code reads *data-plenty="click:Redirect.toCheckoutTab('#payment')"*.
. *Save* the settings.

[#100]
=== Editing PageDesignPrepareMainColumn

Edit the template *PageDesignPrepareMainColumn* to ensure that PayPal PLUS is correctly used and displayed.

[.instruction]
Editing PageDesignPrepareMainColumn:

. Go to *CMS » Web design*.
. Open the folder *Layout » PageDesign*.
. Open the template *PageDesignPrepareMainColumn*.
. Search for the code *gototab=shipping-payment*.
. Replace *shipping-payment* with *payment*.
. *Save* the settings.

[#105]
=== Editing PageDesignCheckout

To open the order overview after completing an order, edit the template *PageDesignCheckout*.

[.instruction]
Editing PageDesignCheckout:

. Go to *CMS » Web design*.
. Open the folder *Layout » PageDesign*.
. Open the template *PageDesignCheckout*.
. Search for the code *PlentyFramework.setGlobal( 'checkoutConfirmCatID', {% CheckoutStepPageID(7) %});*.
. Replace *CheckoutStepPageID(7)* with *CheckoutStepPageID(8)*.
. *Save* the settings.

[#108]
=== Displaying a description for additional payment methods

If you use additional payment methods in the order process together with the payment methods of PayPal PLUS, a description can be displayed next to the name of the payment method in the list of payment methods. Learn how to add the description using the payment method *Cash in advance* as an example. Carry out the settings for <<order-processing/payment/managing-payment-methods#40, other payment methods>> in the same way.

[.instruction]
Creating a category with the description text:

. Go to *Item » Categories*.
. Click on *New category*. +
→ The *Create new category* window will open.
. Enter a name.
. Select the category type.
. If you activate *Subcategory*, then select the category that should include the new subcategory.
. Click on *Create*. +
→ The new category will be created and the *Settings* tab will open.
. Select the type *Content*.
. Activate the *client (store)*.
. *Save* the settings.
. Click on the *Description 2* tab.
. Select the option *Text field* from the drop-down list on the right.
. Insert the description into the text field.
. *Save* the settings.

You now link the previously created category with the payment method in order to display the description in the payment method overview in the order process with PayPal PLUS.

[.instruction]
Linking the category with the payment method:

.  Go to *System » Orders » Payment » Methods*.
.  Place a check mark next to the setting *Also show inactive*.
.  Open the folder *International*.
.  Click on *Cash in advance*. +
→ The *Settings* tab will open.
.  Select *Info page (internal)* from the *Info page* drop-down list.
.  Click on *Edit* next to the option *Info page (internal)*. +
→ The window *Select item template* will open.
. Select the newly created category.
. Click on *Select*. +
→ The category is linked to the payment method.
. *Save* the settings.

[#110]
== Customising the invoice template for PayPal PLUS orders

If you use PayPal PLUS and you generate invoices for the orders that are paid for with PayPal PLUS invoices, then make sure to display PayPal's bank details on the invoice rather than your own bank details. This is done automatically with a payment instruction. Proceed as described below to use your own <<order-processing/orders/order-documents#170, PDF template>>.

[IMPORTANT]
.Respect the payment instruction width
====
In order to display the bank details of PayPal PLUS correctly on your invoice, save a width of 120 millimetres for the payment instruction in the *System » Client » Select client » Locations » Select location » Documents » Invoice* menu.
====

[.instruction]
Using own PDF template:

. Go to *System » Client » Select client » Locations » Select location » Documents » Invoice*.
. Click on the *PDF template* tab.
. Click on the *New template* tab.
. Select *PayPal PLUS* from the drop-down list to save the template for PayPal PLUS.
. Use the *File* area to select the PDF file on your computer.
. Click on *Open*.
. *Save* the settings. +
→ The PDF file will be uploaded and listed in the *Templates* tab.

Before sending invoices to customers, find out whether customers already receive invoices from PayPal. In other words, make sure the customer does not receive 2 invoices.

[#120]
== Not applying the delivery address from PayPal PLUS

When ordering with PayPal PLUS, the delivery address is applied from PayPal by default and not the data entered by the customer. If you do not want to apply the delivery address from PayPal, proceed as follows.

[.instruction]
Not applying the delivery address:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the option *Also show inactive*.
. Open the folder *International*.
.  Click on PayPal PLUS. +
→ The *Settings* tab will open.
. Click on the *Interface* tab.
. Expand a Client (store).
. Activate the setting *Do not apply delivery address*.
. *Save* the settings.

[#130]
== Refunding a partial amount

It is possible to refund customers part of the purchase amount by creating a *credit note* and specifying how much of the total amount should be refunded. Use your own discretion to decide how much is refunded. Partial amounts need to be entered manually since it is possible to enter a different amount for every order. Hence, it is not possible to automate this process.

[.instruction]
Creating a credit note to refund a partial amount:

. Go to *Orders » Edit orders*.
. Open the desired PayPal PLUS order.
. In the *Overview* tab, click on the *Credit note ...* drop-down list and then select *create*. +
→ The credit note will be created.
. Open the newly created credit note and click on the *Settings* tab.
. Click on *PayPal PLUS Refund* under *Refund*.
. Enter the amount that you want to refund.
. Click on *Transfer refund*. +
→ The amount will be sent to PayPal.

[#140]
== Refunding the total amount and automatically sending it to PayPal

It is possible to refund customers the total purchase amount by creating an order of the type *Credit note*. Credit notes will automatically be assigned to the payment.

[.instruction]
Creating a credit note to refund the total amount:

. Go to *Orders » Edit orders*.
. Open the desired PayPal PLUS order.
. In the *Overview* tab, click on the *Credit note ...* drop-down list and then select *create*. +
→ The credit note will be created.

Then create an <<basics/automation/event-procedures#, event procedure>> to automatically send the refunds to PayPal PLUS.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » Orders » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
. Enter a name.
. Select the *Event* listed in table 1.
. *Save* the settings.
. Pay attention to the explanations given in table 1 and carry out the settings as desired.
. Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for automatically sending refunds to PayPal PLUS
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order generation: New credit note*
|

|*Filter*
|*Order &gt; Payment method*
|*PayPal PLUS*

|*Procedure*
|*Payment methods &gt; Send refund to PayPal PLUS*
|
|====

[#150]
==  Automatically reporting rejected payments

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically inform your customers of rejected payments. In order to inform your customers by email of rejected PayPal PLUS payments and change the status of these payments, create an *order status* for *rejected payments* by PayPal PLUS or use an existing order status.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 2.
. *Save* the settings.
.  Pay attention to the explanations given in table 2 and carry out the settings as desired.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.Event procedure for automatically reporting rejected payments by PayPal PLUS
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Payment: Rejected*
|

|*Filter*
|*Order &gt; Payment method*
|*PayPal PLUS*

|*Procedure 1*
|*Customer &gt; Send email*
| Select email template; +
Select *Customer*

|*Procedure 2*
|*Order &gt; Change status*
| Select the order status, e.g. *[3.2] In waiting position*
|====
