= Old online store: Wirecard
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Wirecard, payment method
:description: Payment in plentymarkets: Set up the interface to Wirecard in your plentymarkets system.
:position: 61

[IMPORTANT]
.Integration only for Callisto online stores
====
This page only contains instructions for integrating *Wirecard* in Callisto online stores. The following instructions are not valid for Ceres online stores!
====

Credit card payments can be handled in plentymarkets with *Wirecard*. The transaction is handled by QENTA, Austria's leading payment service provider (PSP), which is responsible for businesses' payment transactions on the internet. QENTA is part of the Wirecard group, the global company for payment and risk management.

[#10]
== Important notes

This chapter provides you with important information about integrating the payment provider in plentymarkets.

[#20]
=== Payment process

The customer is forwarded to Wirecard for the payment process and an iframe prompts the customer to enter their necessary data. The payment method is selected in the online store. Afterwards, the customer is forwarded directly to Wirecard and the additional content is made available in an iframe. The customer enters their data here. In other words, the data is not entered in the online store, but rather in Wirecard. Once the customer has entered and confirmed the data, they will be forwarded to the order confirmation page.

[#30]
=== SSL certificate

You need to have an <<basics/working-with-plentymarkets/plentymarkets-account#ssl-certificate, SSL certificate>> in order to correctly use the payment method.

[WARNING]
.Ask your bank
====
Ask your bank whether it can process payments with iframe before you integrate this payment method.
====

[#40]
=== Available Wirecard payment methods

Below you will find an overview of the Wirecard payment methods that are available for plentymarkets. They are displayed along with the corresponding System ID in parentheses.

* *eps online bank transfer* (950)
* *Giropay* (990)
* *iDEAL* (980)
* *Credit card* (910)
* *Debit* (960)
* *MAESTRO* (800)
* *paybox* (930)
* *paysafecard* (940)
* *QUICK* (970)
* *Payment method selection on the Wirecard payment site* (900)

[#50]
== Registering with Wirecard

You need to register with Wirecard before setting up link:https://www.wirecard.at/en/[Wirecard^] in plentymarkets. Once you have registered, you will receive the access data that you need to save in plentymarkets.

[#60]
== Setting up Wirecard for Callisto

Proceed as described below to set up the interface to Wirecard for your Callisto online store in plentymarkets.

[.instruction]
Setting up the Wirecard interface:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *International*.
.  Click on *Wirecard*. +
→ The *Interface* tab will open.
.  Carry out the settings as desired. Pay attention to the information given in <<table-setup-wirecard-interface>>.
. *Save* the settings.

[[table-setup-wirecard-interface]]
.setting up the Wirecard interface
[cols="1,3"]
|====
|Setting |Explanation

|*Customer number*
|Enter the customer number that you received from Wirecard. The customer number is required for identification purposes.

|*Secret Key*
|Enter the unique secret key that you received from Wirecard.

|*Shop ID*
|The Shop ID is the code of your plentymarkets online store if several licenses are active for your customer number. +
*Important*: Enter your shop ID only if Wirecard explicitly asks for it.

|*Iframe width*; +
*Iframe height*
|Enter values in pixels for the width and height of the iframe. The default values of the iframe are 450 x 450 pixels.
|====

[#70]
== Activating payment methods

Set up and activate the Wirecard <<order-processing/payment/managing-payment-methods#20, payment methods>> in the *Settings* tab of the payment methods. In addition, check the settings for *Permitted payment methods* in the <<order-processing/payment/managing-payment-methods#30, customer classes>> and for *Blocked payment methods* in the <<order-processing/fulfilment/preparing-the-shipment#1000, shipping profiles>>.

[#80]
== Carrying out settings in the Wirecard account

In addition to the settings described above, further configurations can be carried out directly in your Wirecard account, such as integrating further languages or designing templates.

[.subhead]
Languages

German and English are available as default settings. However, you can also integrate other languages in Wirecard upon request. Wirecard currently supports 26 languages.

[.subhead]
Currencies

Note that only one currency is activated in Wirecard as the default setting.

[.subhead]
ImageURL

The image URL is the link to your logo that will be integrated into the pages of Wirecard. The image that is automatically used here is the one that you saved in the *Settings* tab for Wirecard payment methods under *System » Orders » Payment » Methods*. A size of 95 x 65 pixels for the logo is recommended.

[.subhead]
Wirecard premium templates

You can order premium templates directly from Wirecard or download them from the website link:http://www2.wirecard.at/en/landingpage/checkoutpage-layoutanpassung/[http://www.wirecard.at^]. You can then customise them to match your ideas. You have to transmit your templates to Wirecard to have them activated. There the templates will be integrated into your Wirecard configuration. The integration of your customised templates is subject to extra costs.
