= CampaignCoupon
:lang: de
include::{includedir}/_header.adoc[]
:description: CampaignCoupon
:position: 30
:url: daten/export-import/datenformate/campaigncoupon
:id: KNP2JHY

Mit dem Datenformat *CampaignCoupon* exportieren, bearbeiten und importieren Sie die im Menü <<auftraege/gutscheine#, Aufträge » Gutscheine>> gespeicherten Gutschein-Codes der dort erstellten Gutscheinkampagnen. Sie können dann per Importfunktion zeitsparend weitere eigene (nicht von plentymarkets erzeugte) Gutschein-Codes einer Kampagne hinterlegen, die Sie andernfalls einzeln im Menü anlegen müssten. Sie erstellen und exportieren das Datenformat im Menü *Daten » Dynamischer Export*. Importieren Sie das Datenformat wieder im Menü *Daten » Dynamischer Import*. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<daten/export-import/daten-exportieren#, Daten exportieren>> und <<daten/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats *CampaignCoupon* in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab *Filter* des Datenformats vornehmen.

.Datenfelder des Datenformats *CampaignCoupon*
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|*CampaignID*
|ID der Kampagnen
|Filter aktivieren und die Kampagne, deren Gutschein-Codes bearbeitet werden sollen, aus der Dropdown-Liste wählen. +
*_Wichtig_*: Wird hier kein Filter gewählt, werden die Daten der ersten Kampagne exportiert.

|*CouponCode*
|Gutschein-Code +
Um weitere <<auftraege/gutscheine#5, Gutschein-Codes>> zu hinterlegen, diese in diese Spalte eingeben und dazu die ID der Kampagne in der Spalte *CampaignID* eingeben.
|

|*Export für Kundenklasse*
|*_Hinweis_*: reine Filtereinstellung
|Filter aktivieren und Kundenklasse aus der Dropdown-Liste wählen. Um Daten für alle Kundenklassen zu exportieren, Filter nicht aktivieren. Kundenklassen werden im Menü <<crm/kontakte-verwalten#15, Einrichtung » CRM » Kundenklassen>> erstellt.
|====

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat *CampaignCoupon* vorhanden sein und ein gültiger Wert muss eingegeben sein:

* *CampaignID*
* *CouponCode*
