= CustomerPropertyLink
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenformat CustomerPropertyLink, Kundeneigenschaften und Werte
:description: Mit dem Datenformat CustomerPropertyLink exportieren Sie Kundeneigenschaften und die für die Kunden eingegebenen Werte.
:position: 110
:url: daten/export-import/datenformate/customerpropertylink

Mit dem Datenformat *CustomerPropertyLink* exportieren Sie die im Tab *Eigenschaften* Ihrer Kundendaten verfügbaren <<crm/kontakte-verwalten#4000, Kundeneigenschaften>> und die für die Kunden eingegebenen Werte. Mit Hilfe dieses Datenformats verknüpfen Sie zeitsparend Kundeneigenschaften mit bestimmten Kunden. Sie erstellen und exportieren das Datenformat im Menü *Daten » Dynamischer Export*. Wie Sie das Datenformat exportieren, ist auf der Handbuchseite <<daten/export-import/daten-exportieren#, Daten exportieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

Erfahren Sie mehr zu den Kundeneigenschaften im folgenden Videotutorial:

video::106482586[vimeo]
== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats *CustomerPropertyLink* in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab *Filter* des Datenformats vornehmen.

.Datenfelder des Datenformats *CustomerPropertyLink*
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|*CustomerID*
|ID des Kunden
|

|*CustomerPropertyID*
|ID der Kundeneigenschaft
|Filer aktivieren, Operator wählen und Wert eingeben.

|*CustomerPropertyValue*
|Bei der Kundeneigenschaft für den Kunden eingegebener Wert
|Wert eingeben, um eine Eigenschaft mit einem Kunden zu verknüpfen. +
*__Hinweis__*: Wenn das Feld *CustomerPropertyValue* leer oder nicht gesetzt ist, wird die Eigenschaft für den Kunden deaktiviert. +
Eigenschaften werden im Menü *System » Systemeinstellungen » CRM » Eigenschaften* erstellt.

|*Export der Kundenklasse*
|*__Hinweis__*: reine Filtereinstellung
|Filter aktivieren und Kundenklasse aus der Dropdown-Liste wählen. Um Daten für alle Kundenklassen zu exportieren, Filter nicht aktivieren. Kundenklassen werden im Menü <<crm/kontakte-verwalten#15, System » Systemeinstellungen » CRM » Kundenklassen>> erstellt.
|====

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat *CustomerPropertyLink* vorhanden sein und ein gültiger Wert muss eingegeben sein:

* *CustomerPropertyID*
* *CustomerID*
