= CustomerNewsletter
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenformat CustomerNewsletter, Newsletterbezug
:description: Mit dem Datenformat CustomerNewsletter exportieren Sie Daten von Kunden, die den Newsletter beziehen.
:position: 80
:url: daten/export-import/datenformate/customernewsletter
:id: 0EUDZWC

Mit dem Datenformat *CustomerNewsletter* exportieren Sie Daten von Kunden, die für den Bezug von Newslettern eingetragen sind. Sie erstellen und exportieren das Datenformat im Menü *Daten » Dynamischer Export*. Wie Sie das Datenformat exportieren, ist auf der Handbuchseite <<daten/export-import/daten-exportieren#, Daten exportieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats *CustomerNewsletter* in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab *Filter* des Datenformats vornehmen.

.Datenfelder des Datenformats *CustomerNewsletter*
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|*Birthday*
|Geburtsdatum des Kunden
|

|*ConfirmedTimestamp*
|Datum der Opt-In-Bestätigung
|

|*CustomerID*
|ID des Kunden
|

|*CustomerNewsletterID*
|ID des Datensatzes im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails*
|

|*Directory*
|E-Mail-Ordner, der die E-Mail-Adresse des Kunden enthält; im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails*
|Filter aktivieren und E-Mail-Ordner aus der Dropdown-Liste wählen.

|*Email*
|E-Mail-Adresse des Kunden
|

|*FirstName*
|Vorname des Kunden
|

|*Gender*
|Geschlecht des Kunden
|

|*LastName*
|Nachname des Kunden
|

|*Export für Kundenklasse*
|*__Hinweis__*: reine Filtereinstellung
|Filter aktivieren und Kundenklasse aus der Dropdown-Liste wählen. Um Daten für alle Kundenklassen zu exportieren, Filter nicht aktivieren. Kundenklassen werden im Menü <<crm/kontakte-verwalten#15, Einrichtung » CRM » Kundenklassen>> erstellt.
|====

[TIP]
.Export von Daten
====
Daten werden nicht aus allen E-Mail-Ordnern exportiert. Wenn kein Filter in dem Datenformat aktiviert wurde, werden die Daten aus dem ersten gefundenen Ordner im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails* exportiert.
====

== Übersicht der Pflichtfelder

Das folgende Pflichtfeld muss für das Datenformat *CustomerNewsletter* vorhanden sein und ein gültiger Wert muss eingegeben sein:

* *CustomerID*
