= EbayTitleMatch
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenformat
:description: Datenformat EbayTitleMatch
:position: 140

Mit dem Datenformat **EbayTitleMatch** haben Sie die Möglichkeit, Listing-Titel an bestimmte Artikel zu knüpfen. Durch diese Verknüpfung ist es möglich, Listings, die Sie mit anderen Tools einstellen, in plentymarkets zu importieren und diese automatisch dem richtigen Artikel zuordnen zu lassen. Die Einstellung nehmen Sie direkt im Bearbeitungsfenster des Artikels im Tab **Multi-Channel » eBay-Titel** vor. Sie erstellen und exportieren das Datenformat im Menü **Daten » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<basics/datenaustausch/export-import/daten-exportieren#, Daten exportieren>> und <<basics/datenaustausch/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

Tabelle 1 erläutert die Datenfelder des Datenformats **EbayTitleMatch** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**ItemID**
|Artikel-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**ItemNo**
|Artikelnummer
|

|**Title**
|Titel des Listings, das mit diesem Artikel verknüpft werden soll
|
|====

__Tab. 1: Datenfelder des Datenformats **EbayTitleMatch**__

