= FacetReference
:lang: de
include::{includedir}/_header.adoc[]
:position: 160
:url: daten/export-import/datenformate/facetreference

Das Datenformat **FacetReference** wird für die Bearbeitung der Verknüpfungen der Facettensuche verwendet. Sie erstellen und exportieren das Datenformat im Menü **Daten » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<daten/export-import/daten-exportieren#, Daten exportieren>> und <<daten/export-import/daten-importieren#, Daten importieren>> beschrieben. Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

[IMPORTANT]
.Modul aktiv?
====
Das Datenformat ist nur sichtbar, wenn das Modul Facettensuche gebucht wurde und aktiv ist.
====

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **FacetReference** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|FacetValueID
|ID eines Facettenwertes
|Filter aktivieren, Operator wählen und Wert eingeben.

// td><strong>AttributeValueSurcharge</strong></td>
//          <td>Aufpreis des Attributwertes; Wert des gewählten Aufpreises</td>
//          <td>&nbsp;</td>
//       </tr>
// <tr
|ReferenceValueID
|Je nach Referenz-Typ die AttributeID, MerkmalID, ProducerID oder AvailabilityID
|

|ReferenceType
|Referenz-Typen: attribute, character, producer, availability
|

|Delete
|Verknüpfung bzw. Referenz löschen
|

|
|Filter: Export für Kundenklasse
|Filter aktivieren und Kundenklasse wählen.
|====

__Tab. 1: Datenfelder des Datenformats **FacetReference**__

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<daten/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Bei Pflichtabgleichfeldern (P) muss für die **Importaktion** die Option **Abgleich** gewählt werden.

[cols="1,3,3"]
|====
|Feldname |Erläuterung |Abgleichfeld

|**FacetValueID**
|ID eines Facettenwertes
|P

|**ReferenceValueID**
|Je nach Referenz-Typ (siehe oben)
|
|====

__Tab. 2: Datenfelder mit Einstellung auf die Option **Abgleich**__

