= ItemPrice
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenformat
:description: Datenformat ItemPrice
:position: 280
:url: daten/export-import/datenformate/itemprice

[NOTE]
.Datenformat ist veraltet
====
Das Datenformat **ItemPrice** ist in plentymarkets 7 nicht mehr verfügbar. Sie benötigen das Datenformat jedoch, um die Migration Ihres Systems von plentymarkets 6 auf plentymarkets 7 vorzubereiten.
====

Das Datenformat **ItemPrice** wird verwendet, um Preissets von Artikeln anzulegen, zu bearbeiten oder zu löschen. Sie erstellen und exportieren das Datenformat im Menü **Daten » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<daten/export-import/daten-exportieren#, Daten exportieren>> und <<daten/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **ItemPrice** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** vornehmen.

.Datenfelder des Datenformats **ItemPrice**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**DeleteItemPrice**
|Preis löschen
|

|**Height**
|Höhe des Artikels
|

|**ItemID**
|Artikel-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**IsNet**
|**Yes** = Nettopreise +
**No** = Bruttopreise
|Filter aktivieren und Wert aus der Dropdown-Liste wählen.

|**ItemName**
|Name des Artikels
|

|**Length**
|Länge des Artikels
|

|**Lot**
|Inhalt; Zahlenwert; Inhalt definiert die Verpackungseinheiten von **unit**, die pro Einheit enthalten sind.
|

|**PackagePalletType**
|Lademittel
|

|**PackageQuantity**
|Anzahl der Packstücke
|

|**PackageType**
|Packstückart
|

|**PackingUnit**
|Verpackungseinheit (Zahlenwert)
|

|**Position**
|Positionsnummer zur Sortierung von Preissets, für den Fall, dass bei einem Artikel mehrere Preissets verwendet werden.
|

|**Price**
|Preis des Artikels
|

|**Price1 ... Price12**
|Preis 1 bis Preis 12
|

|**PriceCarryingCosts**
|Transportkosten des Artikels
|

|**PriceID**
|ID des Preis-Sets
|

|**PriceInventoryCost**
|Lagerkosten des Artikels
|

|**PriceOperatingCostsPercental**
|Prozentualer Anteil der Gesamtbetriebskosten, der auf diesen Artikel entfällt.
|

|**PriceTollPercental**
|Steuersatz Einfuhrzoll für den Artikel
|

|**Unit**
|Standardeinheit +
Weitere Informationen zu Einheiten, siehe Handbuchseite <<daten/export-import/datenformate/item#, Datenformat Item>>.
|

|**Unit0**
|Einheit 1; frei definierbarer Inhalt möglich; max. 48 Zeichen
|

|**Unit1**
|Einheit 2; frei definierbarer Inhalt möglich; max. 32 Zeichen
|

|**Weight**
|Gewicht des Artikels
|

|**WeightNet**
|Nettogewicht des Artikels
|

|**Width**
|Breite des Artikels
|
|====

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat **ItemPrice** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* **ItemID** zum Anlegen eines Preissets
* **PriceID** zum Bearbeiten eines Preissets
* **PriceID** und **DeleteItemPrice** zum Löschen eines Preissets

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<daten/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Bei Pflichtabgleichfeldern (P) muss für die **Importaktion** die Option **Abgleich** gewählt werden. Wählen Sie mindestens eines der Datenfelder aus der Tabelle zum Abgleich. Sie können aber auch beide wählen. Wird nur das Datenfeld **ItemID** verwendet, wird nur **Preisset 1** abgeglichen.

.Datenfelder mit Einstellung auf die Option **Abgleich**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Abgleich

|**ItemID**
|Artikel-ID
|P

|**PriceID**
|ID des Preis-Sets
|P
|====
