= ItemListingMarketText
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenformat ItemListingMarketText
:position: 270
:url: daten/export-import/datenformate/itemlistingmarkettext

Mit dem Datenformat *ItemListingMarketText* exportierst du die Beschreibung, den Titel und den Untertitel des Listings in mehreren Sprachen. Du erstellst und exportierst das Datenformat im Menü *Daten » Dynamischer Export*. Importiere das Datenformat wieder im Menü *Daten » Dynamischer Import*. Wie du das Datenformat exportierst und importierst, ist auf den Handbuchseiten <<daten/export-import/daten-exportieren#, Daten exportieren>> und <<daten/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achte auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats *ItemListingMarketText* in alphabetischer Reihenfolge sowie die Filteroptionen, die du im Tab *Filter* des Datenformats vornimmst.

.Datenfelder mit Einstellung auf die Option *Abgleich*
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|*Description*
|Beschreibungstext
|Filter aktivieren, Operator wählen und Wert eingeben.

|*Lang*
|Sprache
|Filter aktivieren, Operator wählen und Wert eingeben.

|*ListingMarketID*
|Market-ID
|Filter aktivieren und Sprache wählen.

|*Subtitle*
|Untertitel des Listings
|Filter aktivieren, Operator wählen und Wert eingeben.

|*Title*
|Titel des Listings
|Filter aktivieren, Operator wählen und Wert eingeben.
|====

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<daten/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Bei Pflichtabgleichfeldern (P) muss für die *Importaktion* die Option *Abgleich* gewählt werden.

.Datenfelder des Datenformats *ItemListingMarketText*
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Abgleich

|*Lang*
|Sprache
|P

|*ItemListingMarketID*
|Market-ID
|P
|====
