= ItemImageName
:lang: de
include::{includedir}/_header.adoc[]
:position: 200
:url: daten/export-import/datenformate/itemimagename
:id: KEDRWGO

Mit dem Datenformat **ItemImageName** bearbeitest oder löschst du Artikelbildnamen und Alternativnamen von im Tab **Bilder** eines Artikels verknüpften Artikelbildern. Mit wenig Aufwand passt du so große Mengen an verknüpften Bildern bzw. deren Parameter an. Du erstellst und exportierst das Datenformat im Menü **Daten » Dynamischer Export**. Importiere das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie du das Datenformat exportierst und importierst, ist auf den Handbuchseiten <<daten/export-import/daten-exportieren#, Daten exportieren>> und <<daten/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achte auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

<<tabelle-datenformat-itemimagename-datenfelder>> erläutert die Datenfelder des Datenformats **ItemImageName** in alphabetischer Reihenfolge sowie die Filteroptionen, die du im Tab **Filter** des Datenformats vornimmst.

[[tabelle-datenformat-itemimagename-datenfelder]]
.Datenfelder des Datenformats **ItemImageName**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**ItemImageID**
|Artikelbild-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**ItemImageItemID**
|Artikel-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**ItemImageLanguage**
|Sprache des Artikelbildnamens
|Filter aktivieren und Sprache wählen.

|**ItemImageName**
|Name des Artikelbildes
|

|**ItemImageNameAlternate**
|Alternativname; verbessert die Indizierung durch Suchmaschinen für die Artikel.
|

|**ItemImageNameDelete**
|**1** = Bildnamen löschen +
Löscht Artikelbildnamen unwiederbringlich, wenn der Wert 1 eingegeben wird. Weitere Informationen zu Filtern, siehe Handbuchseite <<daten/export-import/daten-exportieren#20, Daten exportieren>>.
|

|**ItemImageURL**
|Artikelbild-URL
|
|====

== Übersicht der Abgleichfelder

Die in <<tabelle-datenformat-itemimagename-abgleich>> aufgelisteten Datenfelder stehen zum <<daten/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Bei Pflichtabgleichfeldern (P) muss für die **Importaktion** die Option **Abgleich** gewählt werden.

[[tabelle-datenformat-itemimagename-abgleich]]
.Datenfelder mit Einstellung auf die Option **Abgleich**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Abgleich

|**ItemImageID**
|Artikelbild-ID
|P

|**ItemImageLanguage**
|Sprache des Artikelbildnamens
|P
|====
