= ItemListingMarketText
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenformat ItemListingMarketText
:position: 270

Mit dem Datenformat **ItemListingMarketText** exportieren Sie die Beschreibung, den Titel und den Untertitel des Listings in mehreren Sprachen. Sie erstellen und exportieren das Datenformat im Menü **Daten » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<basics/datenaustausch/export-import/daten-exportieren#, Daten exportieren>> und <<basics/datenaustausch/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **ItemListingMarketText** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

.Datenfelder mit Einstellung auf die Option **Abgleich**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**Description**
|Beschreibungstext
|Filter aktivieren, Operator wählen und Wert eingeben.

|**Lang**
|Sprache
|Filter aktivieren, Operator wählen und Wert eingeben.

|**ListingMarketID**
|Market-ID
|Filter aktivieren und Sprache wählen.

|**Subtitle**
|Untertitel des Listings
|Filter aktivieren, Operator wählen und Wert eingeben.

|**Title**
|Titel des Listings
|Filter aktivieren, Operator wählen und Wert eingeben.
|====

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<basics/datenaustausch/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Bei Pflichtabgleichfeldern (P) muss für die **Importaktion** die Option **Abgleich** gewählt werden.

.Datenfelder des Datenformats **ItemListingMarketText**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Abgleich

|**Lang**
|Sprache
|P

|**ItemListingMarketID**
|Market-ID
|P
|====
