= VariationAdditionalSKU
:lang: de
include::{includedir}/_header.adoc[]
:position: 380

Das Datenformat **VariationAdditionalSKU** wird verwendet, um SKUs von Varianten zu exportieren, zu bearbeiten und zu importieren.

Sie erstellen und exportieren das Datenformat im Menü **Daten » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<daten/export-import/daten-exportieren#, Daten exportieren>> und <<daten/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **VariationAdditionalSKU** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

.Datenfelder des Datenformats **VariationAdditionalSKU**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**Delete**
|**1** = SKU löschen +
Löscht die SKU, wenn der Wert 1 eingegeben wird. Standardmäßig wird der Wert 0 übertragen. +
|

|**ItemMarking1**
|Markierung 1 des Artikels; 0 = keine Markierung
|Filter aktivieren, Operator und Markierung wählen.

|**ItemMarking2**
|Markierung 2 des Artikels; 0 = keine Markierung
|Filter aktivieren, Operator und Markierung wählen.

|**MarketAccountID**
|ID des Marktplatz-Accounts
|

|**MarketID**
|Markt-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**ProducerName**
|Name des Herstellers
|Filter aktivieren und Namen wählen.

|**SKU**
|Lagerhaltungsnummer
|

|**VariationID**
|ID der Variante
|

|**PrimaryVariationID**
|ID der Hauptvariante
|
|====

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat **VariationAdditonalSKU** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* **VariationID**
* **MarketID**
* **MarketAccountID**
* **SKU**

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<daten/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Es handelt sich um Pflichtabgleichfelder. Bei Pflichtabgleichfeldern muss für die **Importaktion** die Option **Abgleich** gewählt werden.

.Datenfelder mit Einstellung auf die Option **Abgleich**
[cols="1,3"]
|====
|Feldname |Erläuterung

|**VariationID**
|ID der Variante

|**MarketID**
|Markt-ID

|**MarketAccountID**
|ID des Marktplatz-Accounts
  
|**SKU**
|Lagerhaltungsnummer
|====
