= VariationBarcode
:lang: de
include::{includedir}/_header.adoc[]
:description: VariationBarcode
:position: 390
:url: daten/export-import/datenformate/variationbarcode
:id: PL8WIX7

Das Datenformat **VariationBarcode** wird verwendet, um die im Menü **Einrichtung » Artikel » Barcode** erstellten Barcodes zu exportieren, zu bearbeiten und zu importieren. Du erstellst und exportierst das Datenformat im Menü **Daten » Dynamischer Export**. Importiere das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie du das Datenformat exportierst und importierst, ist auf den Handbuchseiten <<daten/export-import/daten-exportieren#, Daten exportieren>> und <<daten/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achte auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

Tabelle 1 erläutert die Datenfelder des Datenformats **VariationBarcode** in alphabetischer Reihenfolge sowie die Filteroptionen, die du im Tab **Filter** des Datenformats vornimmst.

.Datenfelder des Datenformats **VariationBarcode**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**BarcodeID**
|ID des Barcodes
|Filter aktivieren und Wert aus der Dropdown-Liste wählen.

|**BarcodeName**
|Barcode-Name
|

|**BarcodeType**
|Barcode-Typ
|Filter aktivieren und Wert aus der Dropdown-Liste wählen.

|**Code**
|Code
|

|**VariationNumber**
|(früher VariationCustomNumber) Variantennummer
|

|**VariationID**
|ID der Variante
|Filter aktivieren, Operator wählen und Wert eingeben.
|====

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<daten/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Es handelt sich um Pflichtabgleichfelder. Bei Pflichtabgleichfeldern muss für die **Importaktion** die Option **Abgleich** gewählt werden. Wähle mindestens eines der Datenfelder aus der Tabelle zum Abgleich.

.Datenfelder mit Einstellung auf die Option **Abgleich**
[cols="1,3"]
|====
|Feldname |Erläuterung

|**VariationCustomNumber**
|Variantennummer
|====
