= VariationSalesPrice
:lang: de
include::{includedir}/_header.adoc[]
:position: 430

Das Datenformat **VariationSalesPrice** wird verwendet, um Verkaufspreise von Artikeln anzulegen, zu bearbeiten oder zu löschen. Sie erstellen und exportieren das Datenformat im Menü **Daten » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<basics/datenaustausch/export-import/daten-exportieren#, Daten exportieren>> und <<basics/datenaustausch/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **VariationSalesPrice** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** vornehmen.

.Datenfelder des Datenformats **VariationSalesPrice**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**DeleteSalesPrice**
|Preis löschen
|

|**IsNet**
|**1** = Nettopreise +
**0** = Bruttopreise
|Filter aktivieren und Wert aus der Dropdown-Liste wählen.

|**ItemMarking1**
|Markierung 1 des Artikels; 0 = keine Markierung
|

|**ItemMarking2**
|Markierung 2 des Artikels; 0 = keine Markierung
|

|**SalesPriceExternalName**
|Externer Name des Verkaufspreises
|

|**SalesPriceID**
|ID des Verkaufspreises
|Filter aktivieren und Preis aus der Dropdown-Liste wählen.

|**SalesPriceInternalName**
|Interner Name des Verkaufspreises
|

|**SalesPriceLiveConversion**
|Live-Umrechnung des Verkaufspreises, wie im Menü **System » Artikel » Verkaufspreise** aktiviert
|

|**SalesPriceLang**
|Sprache des Verkaufspreises, wie im Menü **System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Sprache** eingegeben
|Filter aktivieren und Sprache aus der Dropdown-Liste wählen.

|**SalesPriceMinimumOrderQuantity**
|Mindestbestellmenge des Verkaufspreises
|

|**SalesPricePosition**
|Position des Verkaufspreises; Verkaufspreise werden im Bereich **Verkaufspreise** von Artikelvarianten aufsteigend sortiert
|

|**SalesPriceType**
|Typ des Verkaufspreises
|

|**VariationAttributes**
|Attributname und Attributwertname der Variante im Format **Name:Wert**
|

|**VariationNumber**
|(früher VariationCustomNumber) Variantennummer
|

|**VariationID**
|Varianten-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**VariationName**
|Name der Variante
|

|**VariationPrice**
|Preis der Variante
|
|====

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat **VariationSalesPrice** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* **Variation ID** und **SalesPriceID** zum Bearbeiten eines Verkaufspreises
* **VariationID**, **SalesPriceID** und **DeleteItemPrice** zum Löschen eines Verkaufspreises

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<basics/datenaustausch/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Es handelt sich um Pflichtabgleichfelder. Bei Pflichtabgleichfeldern muss für die **Importaktion** die Option **Abgleich** gewählt werden. Wählen Sie mindestens eines der Datenfelder aus der Tabelle zum Abgleich. Sie können aber auch beide wählen.

.Datenfelder mit Einstellung auf die Option **Abgleich**
[cols="1,3"]
|====
|Feldname |Erläuterung

|**VariationCustomNumber**
|Variantennummer

|**VariationID**
|Varianten-ID

|**SalesPriceID**
|ID des Verkaufspreises
|====
