= VariationCategories
:lang: de
include::{includedir}/_header.adoc[]
:description: Datenformat VariationCategories
:position: 410

Das Datenformat **VariationCategories** wird verwendet, um Kategorieverknüpfungen von Varianten zu exportieren, zu bearbeiten und zu importieren. Sie können auch mit dem Datenformat <<daten/export-import/datenformate/variation#, Variation>> Kategorieverknüpfungen per Datenaustausch bearbeiten. Das Datenformat **VariationCategories** ist jedoch besonders geeignet, um Mehrfachverknüpfungen pro Variante vorzunehmen oder zu bearbeiten. +
Verwenden Sie das Format **VariationCategories** z.B. um neu importierte Varianten einfach und schnell mit Kategorieverknüpfungen zu versehen. Nachdem Sie die neuen Varianten importiert haben, exportieren Sie die Kategorieverknüpfungen Ihrer Varianten. Fügen Sie dann in der CSV-Datei bei den neuen Varianten die Werte für die Kategorieverknüpfungen für den Import hinzu.

Sie erstellen und exportieren das Datenformat im Menü **Daten » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<daten/export-import/daten-exportieren#, Daten exportieren>> und <<daten/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Wichtige Hinweise

Beim Import ist es möglich, über das Feld **DeleteOld** mit dem Wert **1** alte Kategorieverknüpfungen zu löschen. Geben Sie bei mehrzeiliger Eingabe der Verknüpfungen pro Variante nur in der ersten Zeile den Wert **1** ein (siehe Tabelle 1).

[IMPORTANT]
.Für neue Kategorien Datenformat Category verwenden
====
Das Erstellen von neuen Kategorien ist mit dem Datenformat **VariationCategories** nicht möglich. Sie können mit dem Datenformat **VariationCategories** lediglich neue Kategorieverknüpfungen an der Variante erstellen. Verwenden Sie daher das Datenformat <<daten/export-import/datenformate/category#, Category>>, um neue Kategorien zu erstellen.
====

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **VariationCategories** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

.Datenfelder des Datenformats **VariationCategories**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**Categories**
|Kategorien +
Kategorie-IDs werden kommagetrennt, IDs der Kategoriepfade mit Bindestrich eingegeben.
|

|**CategoryBranches**
|IDs der Kategoriezweige +
Diese IDs werden kommagetrennt eingegeben. Alternativ zeilenweise pro Kategoriezweig.
|Filter aktivieren, Operator wählen und Wert eingeben.

|**CategoryNameLang**
|Sprache der Kategorienamen
|Filter aktivieren und Sprache aus der Dropdown-Liste wählen.

|**CategoryNames**
|Kategorienamen +
Namen verschiedener Kategorien werden kommagetrennt. Pfadnamen werden mit einem Größer-als-Zeichen eingegeben.
|

|**DeleteOld**
|Alte Kategorieverknüpfungen löschen +
**0** = Nein +
**1** = Ja +
**__Wichtig__**: Wenn Kategorieverknüpfungen einer Variante zeilenweise eingegeben werden, darf nur die erste Zeile den Wert 1 enthalten.
|

|**Position**
|Position der Kategorie
|

|**VariationID**
|Varianten-ID
|Filter aktivieren, Operator wählen und Wert eingeben.
|====
