= VariationBundle
:lang: de
include::{includedir}/_header.adoc[]
:description: Datenformat VariationBundle
:position: 400
:url: daten/export-import/datenformate/variationbundle

Das Datenformat **VariationBundle** wird verwendet, um Variantenpakete zu exportieren, zu bearbeiten und zu importieren. Du erstellst und exportierst das Datenformat im Menü **Daten » Dynamischer Export**. Importiere das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie du das Datenformat exportierst und importierst, ist auf den Handbuchseiten <<daten/export-import/daten-exportieren#, Daten exportieren>> und <<daten/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achte auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **VariationBundle** in alphabetischer Reihenfolge sowie die Filteroptionen, die du im Tab **Filter** des Datenformats vornimmst.

.Datenfelder des Datenformats **VariationBundle**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**Quantity**
|Menge
|

|**VariationID**
|Varianten-ID eines Paketbestandteils
|Filter aktivieren, Operator wählen und Wert eingeben.

|**VariationSourceID**
|Varianten-ID des Paketartikels
|Filter aktivieren, Operator wählen und Wert eingeben.
|====

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat **VariationBundle** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* **Quantity**
* **VariationID**
* **VariationSourceID**

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<daten/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Es handelt sich um Pflichtabgleichfelder. Bei Pflichtabgleichfeldern muss für die **Importaktion** die Option **Abgleich** gewählt werden.

.Datenfelder mit Einstellung auf die Option **Abgleich**
[cols="1,3"]
|====
|Feldname |Erläuterung

|**VariationID**
|Varianten-ID eines Paketbestandteils

|**VariationSourceID**
|Varianten-ID des Paketartikels
|====
