= VariationMarketLink
:lang: de
include::{includedir}/_header.adoc[]
:description: Datenformat VariationMarketLink
:position: 420
:url: daten/export-import/datenformate/variationmarketlink

Mit dem Datenformat **VariationMarketLink** verknüpfen Sie Varianten mit Marktplätzen, damit diese für den Marktplatz verfügbar sind. Sie erstellen und exportieren das Datenformat im Menü **Daten » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<daten/export-import/daten-exportieren#, Daten exportieren>> und <<daten/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **VariationMarketLink** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**VariationID**
|Varianten-ID
|Filter aktivieren, Operator wählen und Wert eingeben.

|**VariationCustomNumber**
|Variantennummer
|

|**Mandant (Shop)**
|Sichtbarkeit des Mandanten (Shop). +
**VISIBLE** = Variante ist auf dem Marktplatz verfügbar. +
**INVISIBLE** = Variante ist nicht auf dem Marktplatz verfügbar.
|Filter aktivieren und Wert aus der Dropdown-Liste wählen.
|====

__Tab. 1: Datenfelder des Datenformats **VariationMarketLink**__

== Übersicht der Pflichtfelder

Die folgenden Pflichtfelder müssen für das Datenformat **VariationMarketLink** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* **VariationID** = ID der Variante
* Marktplatz, der importiert werden soll

== Übersicht der Abgleichfelder

Die in Tabelle 2 aufgelisteten Datenfelder stehen zum <<daten/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Es handelt sich um Pflichtabgleichfelder. Bei Pflichtabgleichfeldern muss für die **Importaktion** die Option **Abgleich** gewählt werden.

[cols="1,3"]
|====
|Feldname |Erläuterung

|**VariationID**
|ID der Variante

|Marktplatz
|Marktplatz wählen, der importiert werden soll
|====

__Tab. 2: Datenfelder mit Einstellung auf die Option **Abgleich**__

