= Warehouse
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Datenformat
:description: Datenformat Warehouse
:position: 470

Das Datenformat **Warehouse** dient zum Export der Daten, die für die Lagerkonfiguration benötigt werden. Sie erstellen und exportieren das Datenformat im Menü **Daten » Dynamischer Export**. Importieren Sie das Datenformat wieder im Menü **Daten » Dynamischer Import**. Wie Sie das Datenformat exportieren und importieren, ist auf den Handbuchseiten <<daten/export-import/daten-exportieren#, Daten exportieren>> und <<daten/export-import/daten-importieren#, Daten importieren>> beschrieben.

Achten Sie auf die exakte Schreibweise der Datenfelder, da die Daten sonst nicht verarbeitet werden können.

== Übersicht der Datenfelder

Tabelle 1 erläutert die Datenfelder des Datenformats **Warehouse** in alphabetischer Reihenfolge sowie die Filteroptionen, die Sie im Tab **Filter** des Datenformats vornehmen.

.Datenfelder des Datenformats **Warehouse**
[cols="1,3,3"]
|====
|Feldname |Erläuterung |Filter

|**LocationID**
|ID des Lagerorts
|

|**LocationMatchingPosition**
|Alter Stellplatz (**Stellplatz** ab Version 4.305 abgelöst durch **Lagerort**) +
Feld wird für die Überführung des alten Stellplatzes zum neuen Lagerort verwendet.
|

|**LocationName**
|Name des Lagerorts
|

|**LocationPosition**
|Position des Lagerorts
|

|**LocationType**
|Lagerorttyp
|

|**RackID**
|ID des Regals
|Filter aktivieren, Operator wählen und Wert eingeben.

|**RackName**
|Name des Regals
|

|**RackPosition**
|Positionsnummer des Regals
|

|**RackWarehouseID**
|ID des Regals im Lager
|Filter aktivieren und Lager, in dem sich das Regal befindet, aus der Dropdown-Liste wählen.

|**RackZone**
|Zone, in der sich das Regal befindet
|

|**ShelfID**
|ID des Regalbodens
|

|**ShelfLevel**
|Ebene des Regalbodens
|

|**ShelfName**
|Name des Regalbodens
|

|**Export für Kundenklasse**
|**__Hinweis__**: reine Filtereinstellung
|Filter aktivieren und Kundenklasse wählen. Um Daten für alle Kundenklassen zu exportieren, Filter nicht aktivieren. Kundenklassen werden im Menü <<crm/kontakte-verwalten#15, System » Systemeinstellungen » CRM » Kundenklassen>> angelegt.
|====

Weitere Details zur Konfiguration des Lagers finden Sie auf der Handbuchseite <<warenwirtschaft/lager-einrichten#, Lager einrichten>>.

== Übersicht der Pflichtfelder

Das folgende Pflichtfeld muss für das Datenformat **Warehouse** vorhanden sein und ein gültiger Wert muss eingegeben sein:

* **RackWarehouseID**

Die Option **Importaktion** muss bei diesem Datenfeld auf **Import** gestellt sein.

== Übersicht der Abgleichfelder

Das folgende Datenfeld steht zum <<daten/export-import/daten-importieren#25, Datenabgleich>> zur Verfügung. Es handelt sich um ein Pflichtabgleichfeld. Bei Pflichtabgleichfeldern muss für die **Importaktion** die Option **Abgleich** gewählt werden.

* **LocationID** = ID des Lagerorts

