= MyDashboard
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Statistik, Kundenstatistik,Auftragsstatistik, Amazon Statistik, eBay Statistik,Dashboard, Besucherstatistik, Rohdaten, Kennzahlen, Unternehmenskennzahlen, MeinDashboard
:position: 30
:url: business-entscheidungen/business-intelligence/myview-dashboard
:id: QPO2ICG
:author: denise-breidenbach

In der schnellebigen Welt des Onlinehandels ist es entscheidend, stets den Überblick über die Kennzahlen deines Online-Business zu behalten. Damit du als Onlinehändler:in immer auf die aktuellen Kennzahlen deines Unternehmens zugreifen kannst und somit direkt siehst, wo Handlungsbedarf besteht, bietet plentymarkets dir **MyDashboard**. Hier kannst du zahlreichen Kennzahlen, Statistiken, Diagrammtypen und Formatierungen miteinander kombinieren. So richtest du dir flexibel und individuell genau das Dashboard ein, das du dir wünscht und das dich zuverlässig durch den Händleralltag begleitet.

== Vorbereitende Einstellungen vornehmen

Bevor du dir dein individuelles Dashboard einrichten kannst, sind nur ein paar vorbereitende Schritte notwendig. Diese werden in den folgenden Kapiteln beschrieben.

=== Assistent durchlaufen

Für einen besonders schnellen und unkomplizierten Start empfehlen wir dir, unseren Assistenten im Menü *Einrichtung » Assistenten » Grundeinrichtung* zu durchlaufen. Der Assistent beinhaltet bereits vorgefertigte Kennzahlen zur Auswahl, beispielsweise zu eingehenden Aufträgen oder Neukunden für verschiedene Zeiträume. Nachdem du die Kennzahlen ausgewählt hast, die auf dem Dashboard angezeigt werden sollen, werden diese automatisch auf dem *MyDashboard* angelegt.

//TODO: Pfad ggf. noch anpassen, Name des Assistenten 

=== Kennzahlen anlegen

=== Benutzerrechte vergeben

== MyDashboard einrichten
