= MyDashboard
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Statistik, Kundenstatistik,Auftragsstatistik, Amazon Statistik, eBay Statistik,Dashboard, Besucherstatistik, Rohdaten, Kennzahlen, Unternehmenskennzahlen, MeinDashboard
:position: 30
:url: business-entscheidungen/business-intelligence/myview-dashboard
:id: QPO2ICG
:author: denise-breidenbach

In der schnellebigen Welt des Onlinehandels ist es entscheidend, stets den Überblick über Zahlen und Daten deines Online-Business zu behalten. Damit du als Onlinehändler:in immer auf die aktuellen Kennzahlen deines Unternehmens zugreifen kannst und somit direkt siehst, wo Handlungsbedarf besteht, bietet plentymarkets dir **MyDashboard**. Hier kannst du zahlreiche Kennzahlen, Statistiken, Diagrammtypen und Formatierungen miteinander kombinieren. So richtest du dir flexibel und individuell genau das Dashboard ein, das du dir wünscht und das dich zuverlässig durch den Händleralltag begleitet.

== Vorbereitende Einstellungen vornehmen

Bevor du dir dein individuelles Dashboard einrichten kannst, sind nur ein paar vorbereitende Schritte notwendig. Diese werden in den folgenden Kapiteln beschrieben.

=== Assistent durchlaufen

Für einen besonders schnellen und unkomplizierten Start empfehlen wir dir, unseren Assistenten im Menü *Einrichtung » Assistenten » Grundeinrichtung* zu durchlaufen. Der Assistent beinhaltet bereits vorgefertigte Kennzahlen zur Auswahl, beispielsweise zu eingehenden Aufträgen oder Neukunden für verschiedene Zeiträume. Nachdem du die Kennzahlen ausgewählt hast, die auf dem Dashboard angezeigt werden sollen, werden diese automatisch auf dem *MyDashboard* angelegt.

//TODO: Pfad ggf. noch anpassen, Name des Assistenten, weitere kurze Anleitung über gesamtes Vorgehen dazu

=== Kennzahlen anlegen

// TODO: hierzu braucht es ggf. kein separates Kapitel, da man direkt aus den Settings Kennzahlen anlegen kann. Klären, ob und wofür genau noch auf das Menü unter Report > Kennzahlen verweisen muss. Wahrscheinlich reicht für die meisten Use Cases eine Infobox dazu im Kapitel *MyDashboard einrichten*.

=== Benutzerrechte vergeben

//TODO: Benutzerrechte sind noch in Arbeit; Benennung der Menüpunkte noch in Erfahrung bringen

== MyDashboard einrichten

//TODO: Kacheln, Diagrammarten und co. beschreiben

Darstellungstypen:

* Portlet für Kacheln
* Portlet für Tabellen
* Portlet für Diagramme
* Portlet für Zeilen
* Portlet für Benachrichtigungen

//TODO: Einstellungen zentral auf Seite dokumentieren (z.B. in einer Tabelle), sodass sie verlinkbar sind und derselbe Content sich nicht x-mal wiederholt

Verfügbare Einstellungen für Kacheln:

* (Kennzahl)
* Titel
* Zeitraum
* Zeitintervall
* Hauptwert
* Sekundärwert
* Ziel (*Anzeigen* oder *Nicht anzeigen*)
* Einheit (*Anzeigen* oder *Nicht anzeigen*)
* Einfärbung (*Anzeigen* oder *Nicht anzeigen*, weitere Einstellungen wie Farbwahl über Button rechts möglich)

Verfügbare Einstellungen für Tabellen:

siehe Kacheln, plus:

* Ergebnissortierreihenfolge
* Skalenbasis Sortierreihenfolge
* Aggregierung
* Einträge pro Seite
* Gruppe nach Datengruppe
* Zugeordnete Spalte

Verfügbare Einstellungen für Diagramma:

* Diagrammtypen: Kuchendiagramm, Balkendiagramm, Heatmap, Liniendiagramm

Je nach Diagrammtyp verschiedene Einstellungsmöglichkeiten:

* Kuchendiagramm:
** (Kennzahl)
** Titel
** Zeitraum
** Zeitintervall

* Balkendiagramm:
** 

