= MyDashboard
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Statistik, Kundenstatistik,Auftragsstatistik, Amazon Statistik, eBay Statistik,Dashboard, Besucherstatistik, Rohdaten, Kennzahlen, Unternehmenskennzahlen, MeinDashboard
:position: 30
:url: business-entscheidungen/business-intelligence/myview-dashboard
:id: QPO2ICG
:author: denise-breidenbach

In der schnellebigen Welt des Onlinehandels ist es entscheidend, stets den Überblick über die Zahlen und Daten deines Online-Business zu behalten. Damit du als Onlinehändler:in immer auf die aktuellen Kennzahlen deines Unternehmens zugreifen kannst und somit direkt siehst, wo Handlungsbedarf besteht, bietet plentymarkets dir **MyDashboard**. Hier kannst du zahlreiche Kennzahlen, Statistiken, Diagrammtypen und Formatierungen miteinander kombinieren. So richtest du dir flexibel und individuell genau das Dashboard ein, das du brauchst.

== Vorbereitende Einstellungen vornehmen

Bevor du dir dein individuelles Dashboard einrichten kannst, sind nur ein paar vorbereitende Schritte notwendig. Diese werden in den folgenden Kapiteln beschrieben.

[IMPORTANT]
.Benutzerrechte beachten 
====
Falls Benutzer:innen ohne Admin-Zugang zu deinem plentymarkets System Kennzahlen anlegen sollen, vergib zuerst die (Link zum Kapitel) notwendigen Benutzerrechte.
====

=== Kennzahlen anlegen

Damit Daten im *MyDashboard* angezeigt werden können, musst du vorbereitend die entsprechenden Kennzahlen erstellen. Dies kannst du entweder im eigens dafür vorhandenen Menü oder direkt aus dem Dashboard heraus tun. In den folgenden Abschnitten werden beide Vorgehensweisen erklärt.

==== Kenzahlen im Einrichtungsmenü erstellen

Diese Vorgehensweise bietet sich an, wenn du viele Kennzahlen auf einmal anlegen möchtest. 

[.instruction]
Kennzahlen im Einrichtungsmenü erstellen:

. Öffne das Menü *Einrichtung » plentyBI » Kennzahlen*.
. Nimm die Einstellungen gemäß <<tabelle-kennzahlen-anlegen>> vor.
. Speichere icon:save[set=plenty] die Einstellungen.

[[tabelle-kennzahlen-anlegen]]
.Kennzahlen anlegen
[cols="1,3"]
|====

|Einstellung |Erläuterung

| *Name*
| Gib einen Namen für die Kennzahl an.

| *Kennzahl*
| Wähle die Kennzahl aus, die angelegt werden soll. Die folgenden Kennzahlen sind verfügbar: +
* Umsatz
* Absatz
* Versandumsatz
* Rohertrag
* Durchschnittlicher Bestellwert
* Durchschnittliche Anzahl der Auftragspositionen
* Retourenquote
* Nachrichten

| *Kommentar*
| Gib hier bei Bedarf einen Kommentar zur Kennzahl ein. Der Kommentar wird an der Kennzahl gespeichert und gibt dir und deinen Mitarbeiter:innen schnell Einblick in eventuelle Besonderheiten oder Vermerke für die Kennzahl.

2+| Bereich *Zielwerte*

| *für Tage und Wochen*, *für Monate*, *für Quartale*, *für Jahre*
| Trage Zielwerte ein, die von der Kennzahl erreicht werden sollen. Je nach gewünschtem Zeitraum kannst du hier flexibel die Zielwerte eintragen, die du für die Kennzahl planst.

|====

Im zweiten Schritt nimmst du die Filtereinstellungen für die Kennzahl vor. Filter ermöglichen es dir, die von der Kennzahl genutzten Daten genauer einzugrenzen. Du kannst  Gehe wie unten beschrieben vor, um Filter einzurichten.

[.instruction]
Filter einrichten:
. Navigiere im Menü **Einrichtung » plentyBI » Kennzahlen** zum Bereich *Filter*.
. Klicke auf icon:listing_create[set=plenty].
. Nimm die gewünschten Filtereinstellungen vor. Beachte dazu die Informationen in <<tabelle-kennzahlen-filtereinstellungen>>.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[[tabelle-kennzahlen-filtereinstellungen]]
.Filter einrichten
[cols="1,3"]
|====

|Einstellung |Erläuterung
|icon:listing_create[set=plenty]
|Fügt einen neuen Filter hinzu. Die folgenden Filter sind verfügbar: +
* Mandant
* Auftragsherkunft
* Auftragstyp
* Auftragsstatus 
* Auftrag Eigenschaftstyp
* Auftrag Eigenschaftswert
* Artikel-ID
* Artikeltyp
* Ertragskonto
* Rechnungsland
* Lieferland
* Abgeschlossen
* Zahlungsstatus
* Lager
* Amazon-Konto
* eBay-Konto
* Versandprofil
* Erstellt am
* Bezahlt am

Nachdem du einen der oben aufgelisteten Filter ausgewählt hast, erscheinen in der Ansicht rechts die weiteren Optionen zur Auswahl. Möchtest du beispielsweise nach Auftragstypen filtern, wähle erst den Filter *Auftragstyp* und dann aus der Liste auf der rechten Seite die konkreten Auftragstypen, nach denen gefiltert werden soll. +
Du kannst maximal 10 Filter anlegen. So kannst du innerhalb derselben Kennzahl gleichzeitig nach Auftragstyp, Auftragsherkunft, Mandant und weiteren Kriterien filtern.

|*Vergleichsoperator*
|Wähle aus, auf welche Art die Kennzahl gefiltert werden soll. Je nach ausgewähltem Filter stehen hier verschiedene Optionen zur Verfügung.

|icon:folder_openable[set=plenty]
|Fügt einem bestehenden Filter einen weiteren Filter hinzu. Auf diese Weise kannst du Verschachtelungen für einen Filter anlegen. Pro Filter kannst du maximal 2 dieser untergeordneten Filter hinzufügen.

|icon:trash[set=plenty]
|Löscht einen angelegten Filter.

|====

==== Kennzahlen über das Dashboard anlegen

Möchtest du auf einem neuen oder bereits eingerichteten Dashboard Kennzahlen hinzufügen? Dann kannst du dies bequem aus dem Dashboard selbst heraus tun.

[IMPORTANT]
.Einstellungsmöglichkeiten für Kennzahlen im Dashboard 
====
Beim Anlegen neuer Kennzahlen über das Dashboard ist es nicht möglich, Zielwerte für die Kennzahlen einzugeben. Diese Einstellungen kannst du jedoch im Nachhinein im Menü **Einrichtung » plentyBI » Kennzahlen** für die entsprechende Kennzahl ergänzen.
====

[.instruction]
Kennzahlen über das Dashboard anlegen:

. Öffne das Menü **plentymarkets Logo (Start) » MyDashboard**.
. Klicke auf *Ansicht bearbeiten* icon:design_inline_edit[set=plenty]. +
→ Der Bearbeitungsmodus wird aktiviert und das Einstellungsmenü öffnet sich.
. Platziere per Drag&Drop ein *Portlet* auf dem Dashboard.
. Platziere beispielsweise eine *Kachel* per Drag & Drop im Portlet.
. Bewege den Mauszeiger über die Kachel und klicke auf icon:design_inline_edit[set=plenty]. +
→ Das Einstellungsmenü für die Kachel öffnet sich.
. Klicke im Einstellungsmenü auf *Kennzahl* und wähle die Option *Neue Kennzahl erstellen*. +
→ Ein Fenster zum Anlegen der neuen Kennzahl öffnet sich.
. Gib einen *Namen* für die Kennzahl ein.
. Nimm die Einstellungen wie in <<tabelle-kennzahlen-anlegen>> beschrieben vor.
. Klicke auf *Speichern*.

=== Benutzerrechte vergeben

Bei der Arbeit mit Kennzahlen solltest du entscheiden, welche Mitarbeiter:innen welche Kennzahlen einsehen dürfen. Benutzer:innen mit Admin-Zugang zu deinem plentymarkets System können standardmäßig immer alle Kennzahlen einsehen sowie neue Kennzahlen anlegen.
Benutzer:innen mit einem Zugang vom Typ *Backend* muss diese Berechtigung durch eine:n Benutzer:in mit Admin-Zugang erteilt werden.

Gehe wie unten beschrieben vor, um festzulegen, welche Kennzahlen für welche Benutzer:innen sichtbar sein sollen.

[.instruction]
Berechtigungen zur Einsicht von Kennzahlen erteilen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
→ Die Übersicht wird geöffnet. +
*_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt.
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das gewünschte Konto.
. Klicke auf *Ressourcen*.
. Klicke auf *Kennzahlen*.
. Aktiviere alle Kennzahlen, die für das Benutzerkonto sichtbar sein sollen.
*_Optional:_* Klicke auf *Alle Kennzahlen*, wenn sämtliche Kennzahlen für das Benutzerkonto sichtbar sein sollen.
. *Speichere* icon:save[set=plenty] die Einstellungen.

Du möchtest Mitarbeiter:innen ohne Admin-Zugang zum System erlauben, Kennzahlen anzulegen? Dann nimm  zusätzlich noch die folgenden Einstellungen vor.

[.instruction]
Berechtigung zum Anlagen von Kennzahlen erteilen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
→ Die Übersicht wird geöffnet. +
*_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt.
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das gewünschte Konto.
. Aktiviere im Bereich *plentyBI* die Option *Kennzahlen*.
. *Speichere* icon:save[set=plenty] die Einstellungen.

//TODO: Es soll zusätzlich zu den o.g. Berechtigungen pro Dashboard-Ansicht Freigaben geben (gilt dann für alle MyView UIs). Im BI Dashboards soll dies über die Ansichts-Auswahl oben rechts möglich sein. Die Funktionalität soll zum Kongress mit released werden und muss noch dokumentiert werden. Hier fehlen aber noch Infos.

== MyDashboard einrichten

Sobald du alle (Link zum Kapitel)vorbereitenden Einstellungen vorgenommen hast, kannst du mit der Einrichtung des Dashboards beginnen. 

Grundsätzlich legst du auf einem neuen Dashboard zuerst ein Portlet an. Portlets sind Darstellungsbereiche, die im zweiten Schritt mit Daten befüllt werden. Per Drag&Drop kannst du sowohl die Portlets als auch die darin enthaltenen Informationen flexibel anordnen.

=== Portlets platzieren

Portlets werden mit verschiedenen Darstellungstypen für die in deinem System vorhandenen Daten befüllt. Deshalb stehen dir mehrere Arten von Portlets zur Verfügung:

* Portlet für Kacheln(Link zum Kapitel)
* Portlet für Tabellen(Link zum Kapitel)
* Portlet für Diagramme(Link zum Kapitel)
* Portlet für Zeilen(Link zum Kapitel)
* Portlet für Benachrichtigungen(Link zum Kapitel)

Gehe wie unten beschrieben vor, um ein Portlet auf dem Dashboard zu platzieren.

[.instruction]
Portlet platzieren:

. Öffne das Menü *plentymarkets Logo (Start) » MyDashboard*.
. Klicke auf *Ansicht bearbeiten* icon:design_inline_edit[set=plenty]. +
→ Der Bearbeitungsmodus wird aktiviert und das Einstellungsmenü öffnet sich.
. Wähle das gewünschte Portlet aus dem Einstellungsmenü und ziehe es per Drag&Drop auf das Dashboard.
. Klicke auf *Ansicht speichern* icon:save[set=plenty], um den aktuellen Stand zu speichern. Du kannst jederzeit wieder auf die Ansicht zugreifen und Änderungen vornehmen.

//TODO: Anleitung nochmal prüfen, ob wirklich alle möglichen Einstellungen für Portlets drin sind.

Du kannst beliebig viele Portlets auf dem Dashboard platzieren. Wiederhole dazu jeweils die oben beschriebenen Schritte. 

=== Portlets mit Informationen befüllen

Nachdem du Portlets zu deinem Dashboard hinzugefügt hast, kannst du diese individuell mit Informationen befüllen. Die folgenden Abschnitte beschreiben den Umgang mit und die Darstellungsmöglichkeiten innerhab der verschiedenen Portlets.

==== Kacheln erstellen

Mithilfe einer Kachel kannst du verschiedene Werte einer Kennzahl in Zahlenform kompakt sichtbar machen. Du kannst mehrere Kacheln in einem Portlet des entsprechenden Typs platzieren.
Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Kachel platzieren:

. öffne xy
. kennzahl wählen
. titel festlegen
. weitere Detaileinstellungen anhand <<table-dashboard-tile-settings>> vornehmen
. speichern

[.collapseBox]
.*Weitere Informationen über die einzelnen Optionen*
--

[[table-dashboard-tile-settings]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Zeitraum*
|

| *Zeitintervall*
|

| *Hauptwert*
|

| *Sekundärwert*
|

| *Ziel*
|

| *Einheit*
|

| *Einfärbung*
| 
|====

--

==== Tabelle erstellen

Verfügbare Einstellungen für Tabellen:

siehe Kacheln, plus:

* Ergebnissortierreihenfolge
* Skalenbasis Sortierreihenfolge
* Aggregierung
* Einträge pro Seite
* Gruppe nach Datengruppe
* Zugeordnete Spalte

==== Diagramm erstellen

Verfügbare Einstellungen für Diagramme:

* Diagrammtypen: Kuchendiagramm, Balkendiagramm, Heatmap, Liniendiagramm

Je nach Diagrammtyp verschiedene Einstellungsmöglichkeiten:

* Kuchendiagramm:
** (Kennzahl)
** (Titel)
** Zeitraum
** (Zeitintervall)

* Balkendiagramm:
** (Kennzahlen und Zeitraum)
** (Titel)
** (Zeitintervall)
** (X-Achse)
** (Y-Achse)
** Drehung der X-Achsenbeschriftung
** Anzahl der Spalten

* Heatmap:
** (Kennzahl)
** (Titel)
** Zeitraum
** (Zeitintervall)
** Aggregierung
** Grenze der Y-Achse
** (X-Achse)
** (Y-Achse)
** Wert

* Liniendiagramm:
** (Kennzahlen und Zeitraum)
** (Titel)
** (Zeitintervall)
** Aggregierung
** (X-Achse)
** (Y-Achse)
** Drehung der X-Achsenbeschriftung
** Anzahl der Spalten

==== Zeile erstellen

Verfügbare Einstellungen für Zeilen:

* (Kennzahl)
* (Titel)
* Zeitraum
* Zeitintervall
* Hauptwert
* Sekundärwert
* Ziel
* Einheit
* Einfärbung

=== Benachrichtigungen anzeigen




Icon für Bearbeitungsmodus: (icon:design_inline_edit[set=plenty])

Icon für Filter hinzufügen:
(icon:listing_create[set=plenty])

Icon für Bedingung hinzufügen:
(icon:folder_openable[set=plenty])

Icon für Stiftsymbol:
(icon:edit[set=plenty])

Icon für Löschen:
(icon:trash[set=plenty])

Icon für Speichern:
(icon:save[set=plenty])

Icon für Schließen (X):
(icon:close[set=plenty])

Icon für Rückgängig:
(icon:reset[set=plenty])

Icon für Warnzeichen an Kacheln:
(icon:problem[set=plenty, role=orange])