= MyDashboard
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Statistik, Kundenstatistik,Auftragsstatistik, Amazon Statistik, eBay Statistik,Dashboard, Besucherstatistik, Rohdaten, Kennzahlen, Unternehmenskennzahlen, MeinDashboard
:position: 30
:url: business-entscheidungen/business-intelligence/myview-dashboard
:id: QPO2ICG
:author: denise-breidenbach

In der schnellebigen Welt des Onlinehandels ist es entscheidend, stets den Überblick über die Zahlen und Daten deines Online-Business zu behalten. Damit du als Onlinehändler:in immer auf die aktuellen Kennzahlen deines Unternehmens zugreifen kannst und somit direkt siehst, wo Handlungsbedarf besteht, bietet plentymarkets dir **MyDashboard**. Hier kannst du zahlreiche Kennzahlen, Statistiken, Diagrammtypen und Formatierungen miteinander kombinieren. So richtest du dir flexibel und individuell genau das Dashboard ein, das du brauchst.

[#100]
== Vorbereitende Einstellungen vornehmen

Bevor du dir dein individuelles Dashboard einrichten kannst, sind nur ein paar vorbereitende Schritte notwendig. Diese werden in den folgenden Kapiteln beschrieben.

[IMPORTANT]
.Benutzerrechte beachten 
====
Falls Benutzer:innen ohne Admin-Zugang zu deinem plentymarkets System Kennzahlen anlegen sollen, vergib zuerst die <<business-entscheidungen/business-intelligence#300, notwendigen Benutzerrechte>>.
====

[#200]
=== Kennzahlen anlegen

Damit Daten im *MyDashboard* angezeigt werden können, musst du vorbereitend die entsprechenden Kennzahlen erstellen. Dies kannst du entweder im eigens dafür vorhandenen Menü oder direkt aus dem Dashboard heraus tun. In den folgenden Abschnitten werden beide Vorgehensweisen erklärt.

[#210]
==== Kenzahlen im Einrichtungsmenü erstellen

Diese Vorgehensweise bietet sich an, wenn du viele Kennzahlen auf einmal anlegen möchtest. 

[.instruction]
Kennzahlen im Einrichtungsmenü erstellen:

. Öffne das Menü *Einrichtung » plentyBI » Kennzahlen*.
. Nimm die Einstellungen gemäß <<tabelle-kennzahlen-anlegen>> vor.
. Speichere icon:save[set=plenty] die Einstellungen.

[[tabelle-kennzahlen-anlegen]]
.Kennzahlen anlegen
[cols="1,3"]
|====

|Einstellung |Erläuterung

| *Name*
| Gib einen Namen für die Kennzahl an.

| *Kennzahl*
| Wähle die Kennzahl aus, die angelegt werden soll. Die folgenden Kennzahlen sind verfügbar: +
* Umsatz
* Absatz
* Versandumsatz
* Rohertrag
* Durchschnittlicher Bestellwert
* Durchschnittliche Anzahl der Auftragspositionen
* Retourenquote
* Nachrichten

| *Kommentar*
| Gib hier bei Bedarf einen Kommentar zur Kennzahl ein. Der Kommentar wird an der Kennzahl gespeichert und gibt dir und deinen Mitarbeiter:innen schnell Einblick in eventuelle Besonderheiten oder Vermerke für die Kennzahl.

2+| Bereich *Zielwerte*

| [#option-zielwert]*für Tage und Wochen*, *für Monate*, *für Quartale*, *für Jahre*
| Trage Zielwerte ein, die von der Kennzahl erreicht werden sollen. Je nach gewünschtem Zeitraum kannst du hier flexibel die Zielwerte eintragen, die du für die Kennzahl planst.

|====

Im zweiten Schritt nimmst du die Filtereinstellungen für die Kennzahl vor. Filter ermöglichen es dir, die von der Kennzahl genutzten Daten genauer einzugrenzen. Du kannst  Gehe wie unten beschrieben vor, um Filter einzurichten.

[.instruction]
Filter einrichten:
. Navigiere im Menü **Einrichtung » plentyBI » Kennzahlen** zum Bereich *Filter*.
. Klicke auf icon:listing_create[set=plenty].
. Nimm die gewünschten Filtereinstellungen vor. Beachte dazu die Informationen in <<tabelle-kennzahlen-filtereinstellungen>>.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[[tabelle-kennzahlen-filtereinstellungen]]
.Filter einrichten
[cols="1,3"]
|====

|Einstellung |Erläuterung
|icon:listing_create[set=plenty]
|Fügt einen neuen Filter hinzu. Die folgenden Filter sind verfügbar: +
* Mandant
* Auftragsherkunft
* Auftragstyp
* Auftragsstatus 
* Auftrag Eigenschaftstyp
* Auftrag Eigenschaftswert
* Artikel-ID
* Artikeltyp
* Ertragskonto
* Rechnungsland
* Lieferland
* Abgeschlossen
* Zahlungsstatus
* Lager
* Amazon-Konto
* eBay-Konto
* Versandprofil
* Erstellt am
* Bezahlt am

Nachdem du einen der oben aufgelisteten Filter ausgewählt hast, erscheinen in der Ansicht rechts die weiteren Optionen zur Auswahl. Möchtest du beispielsweise nach Auftragstypen filtern, wähle erst den Filter *Auftragstyp* und dann aus der Liste auf der rechten Seite die konkreten Auftragstypen, nach denen gefiltert werden soll. +
Du kannst maximal 10 Filter anlegen. So kannst du innerhalb derselben Kennzahl gleichzeitig nach Auftragstyp, Auftragsherkunft, Mandant und weiteren Kriterien filtern.

|*Vergleichsoperator*
|Wähle aus, auf welche Art die Kennzahl gefiltert werden soll. Je nach ausgewähltem Filter stehen hier verschiedene Optionen zur Verfügung.

|icon:folder_openable[set=plenty]
|Fügt einem bestehenden Filter einen weiteren Filter hinzu. Auf diese Weise kannst du Verschachtelungen für einen Filter anlegen. Pro Filter kannst du maximal 2 dieser untergeordneten Filter hinzufügen.

|icon:trash[set=plenty]
|Löscht einen angelegten Filter.

|====

[#220]
==== Kennzahlen über das Dashboard anlegen

Möchtest du auf einem neuen oder bereits eingerichteten Dashboard Kennzahlen hinzufügen? Dann kannst du dies bequem aus dem Dashboard selbst heraus tun.

[IMPORTANT]
.Einstellungsmöglichkeiten für Kennzahlen im Dashboard 
====
Beim Anlegen neuer Kennzahlen über das Dashboard ist es nicht möglich, Zielwerte für die Kennzahlen einzugeben. Diese Einstellungen kannst du jedoch im Nachhinein im Menü **Einrichtung » plentyBI » Kennzahlen** für die entsprechende Kennzahl ergänzen.
====

[.instruction]
Kennzahlen über das Dashboard anlegen:

. Öffne das Menü **plentymarkets Logo (Start) » MyDashboard**.
. Klicke auf *Ansicht bearbeiten* icon:design_inline_edit[set=plenty]. +
→ Der Bearbeitungsmodus wird aktiviert und das Einstellungsmenü öffnet sich.
. Platziere per Drag&Drop ein *Portlet* auf dem Dashboard.
. Platziere beispielsweise eine *Kachel* per Drag & Drop im Portlet.
. Bewege den Mauszeiger über die Kachel und klicke auf icon:design_inline_edit[set=plenty]. +
→ Das Einstellungsmenü für die Kachel öffnet sich.
. Klicke im Einstellungsmenü auf *Kennzahl* und wähle die Option *Neue Kennzahl erstellen*. +
→ Ein Fenster zum Anlegen der neuen Kennzahl öffnet sich.
. Gib einen *Namen* für die Kennzahl ein.
. Nimm die Einstellungen wie in <<tabelle-kennzahlen-anlegen>> beschrieben vor.
. Klicke auf *Speichern*.

[#300]
=== Benutzerrechte vergeben

Bei der Arbeit mit Kennzahlen solltest du entscheiden, welche Mitarbeiter:innen welche Kennzahlen einsehen dürfen. Benutzer:innen mit Admin-Zugang zu deinem plentymarkets System können standardmäßig immer alle Kennzahlen einsehen sowie neue Kennzahlen anlegen.
Benutzer:innen mit einem Zugang vom Typ *Backend* muss diese Berechtigung durch eine:n Benutzer:in mit Admin-Zugang erteilt werden.

Gehe wie unten beschrieben vor, um festzulegen, welche Kennzahlen für welche Benutzer:innen sichtbar sein sollen.

[.instruction]
Berechtigungen zur Einsicht von Kennzahlen erteilen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
→ Die Übersicht wird geöffnet. +
*_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt.
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das gewünschte Konto.
. Klicke auf *Ressourcen*.
. Klicke auf *Kennzahlen*.
. Aktiviere alle Kennzahlen, die für das Benutzerkonto sichtbar sein sollen.
*_Optional:_* Klicke auf *Alle Kennzahlen*, wenn sämtliche Kennzahlen für das Benutzerkonto sichtbar sein sollen.
. *Speichere* icon:save[set=plenty] die Einstellungen.

Du möchtest Mitarbeiter:innen ohne Admin-Zugang zum System erlauben, Kennzahlen anzulegen? Dann nimm  zusätzlich noch die folgenden Einstellungen vor.

[.instruction]
Berechtigung zum Anlagen von Kennzahlen erteilen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
→ Die Übersicht wird geöffnet. +
*_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicke auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt.
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das gewünschte Konto.
. Aktiviere im Bereich *plentyBI* die Option *Kennzahlen*.
. *Speichere* icon:save[set=plenty] die Einstellungen.

//TODO: Es soll zusätzlich zu den o.g. Berechtigungen pro Dashboard-Ansicht Freigaben geben (gilt dann für alle MyView UIs). Im BI Dashboards soll dies über die Ansichts-Auswahl oben rechts möglich sein. Die Funktionalität soll zum Kongress mit released werden und muss noch dokumentiert werden. Hier fehlen aber noch Infos.

[#400]
== MyDashboard einrichten

Sobald du die <<business-entscheidungen/business-intelligence#100, vorbereitenden Einstellungen>> vorgenommen hast, kannst du mit der Einrichtung des Dashboards beginnen. 

Grundsätzlich legst du auf einem neuen Dashboard zuerst ein Portlet an. Portlets sind Darstellungsbereiche, die im zweiten Schritt mit Daten befüllt werden. Per Drag&Drop kannst du sowohl die Portlets als auch die darin enthaltenen Informationen flexibel anordnen.

[#410]
=== Portlets hinzufügen

Portlets werden mit verschiedenen Darstellungstypen für die in deinem System vorhandenen Daten befüllt. Deshalb stehen dir mehrere Arten von Portlets zur Verfügung:

* Portlet für <<business-entscheidungen/business-intelligence#500, Kacheln>>
* Portlet für <<business-entscheidungen/business-intelligence#600, Tabellen>>
* Portlet für <<business-entscheidungen/business-intelligence#700, Diagramme>>
* Portlet für <<business-entscheidungen/business-intelligence#800, Zeilen>>
* Portlet für <<business-entscheidungen/business-intelligence#900, Benachrichtigungen>>

Unabhängig von der Art ist die Vorgehensweise beim Platzieren von Portlets immer gleich.

[.instruction]
Portlet platzieren:

. Öffne das Menü *plentymarkets Logo (Start) » MyDashboard*.
. Klicke auf *Ansicht bearbeiten* icon:design_inline_edit[set=plenty].
. Wähle das gewünschte Portlet aus dem Einstellungsmenü und ziehe es per Drag&Drop auf das Dashboard.
. Klicke an der oberen rechten Ecke des Portlets auf *Bearbeiten* icon:edit[set=plenty]. +
→ Der Bearbeitungsmodus wird aktiviert und das Einstellungsmenü für das Portlet öffnet sich.
. Trage im Feld *Titel* einen Namen ein, der für das Portlet angezeigt werden soll.
. Klicke auf *Ansicht speichern* icon:save[set=plenty], um den aktuellen Stand zu speichern. Du kannst jederzeit wieder auf die Ansicht zugreifen und Änderungen vornehmen.

[TIP]
.Mehrere Portlets möglich
====
Du kannst beliebig viele Portlets auf dem Dashboard platzieren. Wiederhole dazu jeweils die oben beschriebenen Schritte. Je nach Bildschirmauflösung und Anzahl der verwendeten Portlets kann es jedoch zu Übersichtsproblemen kommen, da die Portlets immer untereinander platziert werden.
====

[#420]
=== Portlets mit Elementen befüllen

Nachdem du Portlets zu deinem Dashboard hinzugefügt hast, kannst du diese individuell mit Informationen befüllen.

Unabhängig vom Typ des Elements ist die Vorgehensweise zum Platzieren eines Elements innerhalb eines Portlets immer gleich.

[.instruction]
Element in einem Portlet platzieren:

. Öffne das Menü *plentymarkets Logo (Start) » MyDashboard*.
. Klicke auf *Ansicht bearbeiten* icon:design_inline_edit[set=plenty]. +
. Klicke an der oberen rechten Ecke des bereits platzierten Portlets auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü für das Portlet öffnet sich.
. Platziere das gewünschte Element per Drag&Drop im Portlet auf dem Dashboard.
. *Speichere* icon:save[set=plenty] die Einstellungen.

Je nach Typ des Portlets stehen dir nun verschiedene Elemente zur Verfügung. Mit diesen kannst du die Portlets mit Informationen anreichern. Die Darstellung der Kennzahlen innerhalb der Elemente ist individualisierbar. Die folgenden Abschnitten beschreiben die genaueren Einstellungen, die pro Element zur Verfügung stehen.

[#500]
==== Einstellungen für Kacheln

Kacheln sind quadratische Darstellungsbereiche, die du in einem *Portlet für Kacheln* platzieren kannst. Sie stellen Daten ausschließlich in Text- und Zahlenform dar. Zusätzlich kannst du zwischen verschiedenen Farben für die Kachel sowie Angaben zu Zeiträumen und Zielwerten wählen.

Füge zunächst <<business-entscheidungen/business-intelligence#420, wie oben beschrieben>> eine Kachel hinzu. Gehe dann wie folgt vor, um individuelle Einstellungen für die Kachel vorzunehmen.

[.instruction]

. Klicke an der oberen rechten Ecke der Kachel auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü für das Element öffnet sich.
. Nimm die Einstellungen für das Element vor. <<table-dashboard-tile-settings>> enthält weitere Informationen zu den verfügbaren Optionen.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[.collapseBox]
.*Weitere Informationen über die einzelnen Optionen*
--

[[table-dashboard-tile-settings]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Kennzahl*
| Wähle aus der Dropdown-Liste eine Kennzahl aus, die in der Kachel dargestellt werden soll. Klicke alternativ auf *Neue Kennzahl erstellen* icon:plus[role="green"], um <<business-entscheidungen/business-intelligence#220, direkt im Einstellungsmenü>> eine neue Kennzahl anzulegen.

| *Titel*
| Gib einen aussagekräftigen Titel ein. Der Titel wird als Name auf der Kachel angezeigt.

| *Zeitraum*
| Wähle den Zeitraum, aus dem die Werte der gewählten Kennzahl auf der Kachel dargestellt werden sollen.

| *Zeitintervall*
| //TODO: Klären, was hier nochmal genau gemeint war

| *Hauptwert*
| Der Hauptwert wird auf der Kachel etwas größer als der *Sekundärwert* dargestellt. Hier kannst das reine *Ergebnis der Kennzahl* oder die *Differenz* zum in der Kennzahl <<business-entscheidungen/business-intelligence#option-zielwert, festgelegten Zielwert>> anzeigen lassen. Die Differenz kann absolut oder *in %* anzeigt werden. Über (icon:settings[set=plenty]) kannst du bestimmen, wie viele Nachkommastellen für den Wert angezeigt werden sollen.

| *Sekundärwert*
| Dieser Wert wird auf der Kachel etwas kleiner und oberhalb des Hauptwerts angezeigt. Für den Sekundärwert stehen dir die selben Einstellungsmöglichkeiten wie für den *Hauptwert* zur Verfügung. Wähle die Option *Keine*, wenn du keinen Sekundärwert auf der Kachel anzeigen möchtest.

| *Ziel*
| Soll der in der Kennzahl <<business-entscheidungen/business-intelligence#option-zielwert, festgelegte Zielwert>> auf der Kachel angezeigt werden? Wähle zwischen den Optionen *Anzeigen* und *Nicht anzeigen*.

| *Einheit*
| Wähle, ob die Einheit der Kennzahl auf der Kachel angezeigt werden soll.

| *Einfärbung*
| Möchtest du die Kachel in einer bestimmten Farbe anzeigen? Wähle dazu die Option *Anzeigen* und klicke auf (icon:settings[set=plenty]). Es öffnet sich ein weiteres Einstellungsfenster. Wähle links die Farbe für die Kachel aus. Soll die Farbe der Kachel sich je nach Wert der Kennzahl ändern, wähle zusätzlich einen *Operator* und einen *Vergleichswert* aus, bevor du auf *Speichern* klickst. +
*_Tipp:_* Klicke auf icon:plus[role="green"], um weitere Bedingungen für Einfärbungen zu speichern.

|====

--

// TODO: Optionen für Tabellen klären
[#600]
==== Einstellungen für Tabellen

Kennzahlen lassen sich auf dem Dashboard auch in Tabellenform übersichtlich darstellen. Grundsätzlich stehen für Tabellen dieselben Einstellungsmöglichkeiten wie für Kacheln (siehe <<table-dashboard-tile-settings) zur Verfügung. 
Weitere speziell für Tabellen verfügbare Einstellungen werden in <<table-dashboard-table-settings>> beschrieben.

Füge zunächst <<business-entscheidungen/business-intelligence#420, wie oben beschrieben>> eine Tabelle hinzu. Gehe danach wie folgt vor, um individuelle Einstellungen für die Tabelle vorzunehmen.

[.instruction]

. Klicke an der oberen rechten Ecke der Tabelle auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü für das Element öffnet sich.
. Nimm die Einstellungen für das Element vor. <<table-dashboard-table-settings>> enthält weitere Informationen zu den verfügbaren Optionen.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[.collapseBox]
.*Weitere Informationen über die einzelnen Optionen*
--

[[table-dashboard-table-settings]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Ergebnissortierreihenfolge*
| Über diese Option lassen sich die Werte in der Spalte *Ergebnis* der Tabelle sortieren. Wähle eine der Optionen *Aufsteigend* oder *Absteigend*.

| *Skalenbasis Sortierreihenfolge*
| 

| *Aggregierung*
| 

| *Einträge pro Seite*
| Je nach Anzahl der Einträge kann die Tabelle aus mehreren Seiten bestehen. Wähle aus, ob *10*, *25*, *50*, *75* oder *100* Einträge pro Seite angezeigt werden sollen.

| *Gruppe nach Dimension*
| 

| *Zugeordnete Spalte*
|

|====

--


//TODO: Diagramme noch komplett beschreiben

[#700]
==== Einstellungen für Diagramme

Verfügbare Einstellungen für Diagramme:

* Diagrammtypen: Kuchendiagramm, Balkendiagramm, Heatmap, Liniendiagramm

Je nach Diagrammtyp verschiedene Einstellungsmöglichkeiten:

* Kuchendiagramm:
** (Kennzahl)
** (Titel)
** Zeitraum
** (Zeitintervall)

* Balkendiagramm:
** (Kennzahlen und Zeitraum)
** (Titel)
** (Zeitintervall)
** (X-Achse)
** (Y-Achse)
** Drehung der X-Achsenbeschriftung
** Anzahl der Spalten

* Heatmap:
** (Kennzahl)
** (Titel)
** Zeitraum
** (Zeitintervall)
** Aggregierung
** Grenze der Y-Achse
** (X-Achse)
** (Y-Achse)
** Wert

* Liniendiagramm:
** (Kennzahlen und Zeitraum)
** (Titel)
** (Zeitintervall)
** Aggregierung
** (X-Achse)
** (Y-Achse)
** Drehung der X-Achsenbeschriftung
** Anzahl der Spalten

[#800]
==== Einstellungen für Zeilen

Für die Darstellung von Daten in einfacher Zeilenform sind dieselben Einstellungen wie für <<business-entscheidungen/business-intelligence#500, Kacheln>> verfügbar.
In einem Portlet vom Typ Zeilen kannst du mehrere Zeilen platzieren, die dann untereinander angeordnet werden. Füge zunächst <<business-entscheidungen/business-intelligence#420, wie oben beschrieben>> eine Zeile hinzu. Gehe danach wie folgt vor, um individuelle Einstellungen für die Zeile vorzunehmen.

[.instruction]

. Klicke an der oberen rechten Ecke der Zeile auf *Bearbeiten* icon:edit[set=plenty]. +
→ Das Einstellungsmenü für das Element öffnet sich.
. Nimm die Einstellungen für das Element vor. <<table-dashboard-tile-settings>> enthält weitere Informationen zu den verfügbaren Optionen.
. *Speichere* icon:save[set=plenty] die Einstellungen.

[#900]
=== Benachrichtigungen auf dem Dashboard anzeigen

<<willkommen/login-rundgang#notification-center, Benachrichtigungen>> beinhalten wichtige Informationen über dein plentymarkets System. Dazu findest du am oberen Rand des plentymarkets Backend ein Glockensymbol. Klickst du auf dieses, werden dir aktuelle Benachrichtigungen angezeigt.
Gehe wie unten beschrieben vor, um Benachrichtigungen in einem eigenen Bereich auf dem Dashboard anzuzeigen.

[.instruction]
Benachrichtigungen auf dem Dashboard anzeigen:

. Öffne das Menü *plentymarkets Logo (Start) » MyDashboard*.
. Klicke auf *Ansicht bearbeiten* icon:design_inline_edit[set=plenty].
. Platziere das Element *Portlet für Benachrichtigungen* per Drag&Drop auf dem Dashboard.
. *Speichere* icon:save[set=plenty] die Einstellungen.







Icon für Bearbeitungsmodus: (icon:design_inline_edit[set=plenty])

Icon für Filter hinzufügen:
(icon:listing_create[set=plenty])

Icon für Bedingung hinzufügen:
(icon:folder_openable[set=plenty])

Icon für Stiftsymbol:
(icon:edit[set=plenty])

Icon für Löschen:
(icon:trash[set=plenty])

Icon für Speichern:
(icon:save[set=plenty])

Icon für Schließen (X):
(icon:close[set=plenty])

Icon für Rückgängig:
(icon:reset[set=plenty])

Icon für Zahnrad
(icon:settings[set=plenty])

