= MyDashboard
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Statistik, Kundenstatistik,Auftragsstatistik, Amazon Statistik, eBay Statistik,Dashboard, Besucherstatistik, Rohdaten, Kennzahlen, Unternehmenskennzahlen, MeinDashboard
:position: 30
:url: business-entscheidungen/business-intelligence/myview-dashboard
:id: QPO2ICG
:author: denise-breidenbach

In der schnellebigen Welt des Onlinehandels ist es entscheidend, stets den Überblick über die Zahlen und Daten deines Online-Business zu behalten. Damit du als Onlinehändler:in immer auf die aktuellen Kennzahlen deines Unternehmens zugreifen kannst und somit direkt siehst, wo Handlungsbedarf besteht, bietet plentymarkets dir **MyDashboard**. Hier kannst du zahlreiche Kennzahlen, Statistiken, Diagrammtypen und Formatierungen miteinander kombinieren. So richtest du dir flexibel und individuell genau das Dashboard ein, das du brauchst.

== Vorbereitende Einstellungen vornehmen

Bevor du dir dein individuelles Dashboard einrichten kannst, sind nur ein paar vorbereitende Schritte notwendig. Diese werden in den folgenden Kapiteln beschrieben.

=== Kennzahlen anlegen

Damit Daten im *MyDashboard* angezeigt werden können, musst du vorbereitend die entsprechenden Kennzahlen erstellen. Dies kannst du entweder im eigens dafür vorhandenen Menü oder direkt aus dem Dashboard heraus tun. In den folgenden Abschnitten werden beide Vorgehensweisen erklärt.

==== Kenzahlen im Einrichtungsmenü erstellen

Diese Vorgehensweise bietet sich an, wenn du viele Kennzahlen auf einmal anlegen möchtest. 

[.instruction]
Kennzahlen im Einrichtungsmenü erstellen:

. Öffne das Menü *Einrichtung » plentyBI » Kennzahlen*.
. Nimm die Einstellungen gemäß <<tabelle-kennzahlen-anlegen>> vor.
. Speichere icon:save[set=plenty] die Einstellungen.

[[tabelle-kennzahlen-anlegen]]
.Kennzahlen anlegen
[cols="1,3"]
|====

|Einstellung |Erläuterung

| *Name*
| Gib einen Namen für die Kennzahl an.

| *Kennzahl*
| Wähle die Kennzahl aus, die angelegt werden soll. Die folgenden Kennzahlen sind verfügbar: +
* Umsatz
* Absatz
* Versandumsatz
* Rohertrag
* Durchschnittlicher Bestellwert
* Durchschnittliche Anzahl der Auftragspositionen
* Retourenquote
* Nachrichten

| *Kommentar*
| Gib hier bei Bedarf einen Kommentar zur Kennzahl ein. Der Kommentar wird an der Kennzahl gespeichert und gibt dir und deinen Mitarbeiter:innen schnell Einblick in eventuelle Besonderheiten oder Vermerke für die Kennzahl.

2+| Bereich *Zielwerte*

| *für Tage und Wochen*
| 

| *für Monate*
|

| *für Quartale*
|

| *für Jahre*
|

|====

Im zweiten Schritt nimmst du die Filtereinstellungen für die Kennzahl vor. Filter ermöglichen es dir, die von der Kennzahl genutzten Daten genauer einzugrenzen. 

// TODO: hierzu braucht es ggf. kein separates Kapitel, da man direkt aus den Settings Kennzahlen anlegen kann. Klären, ob und wofür genau noch auf das Menü unter Report > Kennzahlen verweisen muss. --> beide Wege beschreiben, v.a. wenn User viele Kennzahlen auf einmal anlegen möchten

=== Benutzerrechte vergeben

//TODO: Es wird pro Ansicht Freigaben geben (gilt dann für alle MyView UIs). Menüpunkt wird dann im regulären Menü für die Rechte unter Ressourcen und Kennzahlen ergänzt. wird vor kongress fertig, Screenshots kommen

== MyDashboard einrichten

Icon für Bearbeitungsmodus: (icon:design_inline_edit[set=plenty])

Icon für Stiftsymbol:
(icon:edit[set=plenty])

Icon für Löschen:
(icon:trash[set=plenty])

Icon für Speichern:
(icon:save[set=plenty])

Icon für Schließen (X):
(icon:close[set=plenty])

Icon für Rückgängig:
(icon:reset[set=plenty])

Icon für Warnzeichen an Kacheln:
(icon:problem[set=plenty, role=orange])


=== Portlets platzieren

Auf deinem Dashboard kannst du verschiedene Bereiche, hier *Portlets* genannt, platzieren.
Portlets werden mit verschiedenen Darstellungstypen für die Daten deines Systems befüllt. Deshalb gibt es auch mehrere Arten von Portlets, die du verwenden kannst:

* Portlet für Kacheln
* Portlet für Tabellen
* Portlet für Diagramme
* Portlet für Zeilen

Gehe wie unten beschrieben vor, um ein Portlet auf dem Dashboard zu platzieren.

[.instruction]
Portlet platzieren:

. Öffne das Menü *plentymarkets Logo (Start) » MyDashboard*.
. Klicke auf *Ansicht bearbeiten* (icon:design_inline_edit[set=plenty]). +
→ Der Bearbeitungsmodus wird aktiviert und das Einstellungsmenü öffnet sich.
. Wähle das gewünschte Portlet aus dem Einstellungsmenü und ziehe es per Drag&Drop auf das Dashboard.
. Klicke auf *Ansicht speichern* (icon:save[set=plenty]), um den aktuellen Stand zu speichern. Du kannst jederzeit wieder auf die Ansicht zugreifen und Änderungen vornehmen.

Du kannst beliebig viele Portlets auf dem Dashboard platzieren. Wiederhole dazu jeweils die oben beschriebenen Schritte. 

=== Portlets mit Informationen befüllen

Nachdem du Portlets zu deinem Dashboard hinzugefügt hast, kannst du diese individuell mit Informationen befüllen. Die folgenden Abschnitte beschreiben den Umgang mit und die Darstellungsmöglichkeiten innerhab der verschiedenen Portlets.

==== Kacheln erstellen

Mithilfe einer Kachel kannst du verschiedene Werte einer Kennzahl in Zahlenform kompakt sichtbar machen. Du kannst mehrere Kacheln in einem Portlet des entsprechenden Typs platzieren.
Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Kachel platzieren:


Für Kacheln sind die in Tabelle (LINK) beschriebenen Einstellungen verfügbar.

Verfügbare Einstellungen für Kacheln:

* (Kennzahl)
* Titel
* Zeitraum
* Zeitintervall
* Hauptwert
* Sekundärwert
* Ziel (*Anzeigen* oder *Nicht anzeigen*)
* Einheit (*Anzeigen* oder *Nicht anzeigen*)
* Einfärbung (*Anzeigen* oder *Nicht anzeigen*, weitere Einstellungen wie Farbwahl über Button rechts möglich)

=== Tabelle erstellen

Verfügbare Einstellungen für Tabellen:

siehe Kacheln, plus:

* Ergebnissortierreihenfolge
* Skalenbasis Sortierreihenfolge
* Aggregierung
* Einträge pro Seite
* Gruppe nach Datengruppe
* Zugeordnete Spalte

=== Diagramm erstellen

Verfügbare Einstellungen für Diagramme:

* Diagrammtypen: Kuchendiagramm, Balkendiagramm, Heatmap, Liniendiagramm

Je nach Diagrammtyp verschiedene Einstellungsmöglichkeiten:

* Kuchendiagramm:
** (Kennzahl)
** (Titel)
** Zeitraum
** (Zeitintervall)

* Balkendiagramm:
** (Kennzahlen und Zeitraum)
** (Titel)
** (Zeitintervall)
** (X-Achse)
** (Y-Achse)
** Drehung der X-Achsenbeschriftung
** Anzahl der Spalten

* Heatmap:
** (Kennzahl)
** (Titel)
** Zeitraum
** (Zeitintervall)
** Aggregierung
** Grenze der Y-Achse
** (X-Achse)
** (Y-Achse)
** Wert

* Liniendiagramm:
** (Kennzahlen und Zeitraum)
** (Titel)
** (Zeitintervall)
** Aggregierung
** (X-Achse)
** (Y-Achse)
** Drehung der X-Achsenbeschriftung
** Anzahl der Spalten

=== Zeile erstellen

Verfügbare Einstellungen für Zeilen:

* (Kennzahl)
* (Titel)
* Zeitraum
* Zeitintervall
* Hauptwert
* Sekundärwert
* Ziel
* Einheit
* Einfärbung

