= Hosting
:lang: de
include::{includedir}/_header.adoc[]
:position: 80

Das Datenvolumen und der zulässige Traffic sind je nach Vertrag limitiert. Überschreitungen werden separat in Rechnung gestellt. plentymarkets bietet Ihnen daher die Möglichkeit, Ihren Verbrauch jederzeit nachzuvollziehen. Auf dieser Seite erfahren Sie, wie Sie diese Verbrauchsdaten anzeigen. Außerdem erhalten Sie Informationen dazu, wie Traffic entsteht.

== Verbrauchsdaten anzeigen

Die Verbrauchsdaten werden im Menü **Start » plentymarkets Konto » Hosting » Tab: Verbrauch** angezeigt. Die folgende Tabelle gibt Ihnen einen Überblick der in diesem Menü angezeigten Daten zu Ihrem Verbrauch.

[cols="a,a"]
|====
|Daten |Erläuterung

|**Monat**
|Verbrauchsmonat

|**Webspace gesamt**
|Speicherplatz, der in diesem Monat maximal im Webspace belegt war, in GB.

|**Webspace Dokumente**
|Speicherplatz, der in diesem Monat maximal durch Dokumente im Webspace belegt war, in GB.

|**Traffic**
|Traffic in GB

|**DB**
|Datenbank-Volumen, das in diesem Monat maximal belegt war, in GB.

|**Facettensuchen**
|Anzahl der im Webshop durchgeführten Facettensuchen

|**Artikel in Facettensuche**
|Anzahl der Artikel in der Facettensuche
|====

__Tab. 1: Angezeigte Verbrauchsdaten__

== Wissenswertes zum Thema Traffic

Traffic entsteht, wenn ein Kunde Ihren Webshop besucht und dort z.B. Artikel anklickt, Bilder vergrößert oder Dateien herunterlädt.

Zusätzlicher Traffic entsteht außerdem in den folgenden Fällen:

* Beim Austausch von Daten mit Marktplätzen.
* Bei link::/[**SOAP-Abfragen**], da bei diesen Abfragen Verbindungen zum Server aufgebaut werden. Je nach Art der Abfrage ist das Datenvolumen beträchtlich. Optimieren Sie daher Ihre Calls, indem Sie z.B. nicht ständig alle Bestände abfragen, sondern die Abfrage auf Änderungen beschränken.
* Beim Scannen Ihrer Website durch **link:http://de.wikipedia.org/wiki/Webcrawler[Bots, window="_blank"]**. Diese Bots speichern Ihre Seiten, wodurch Traffic entsteht. Wenn z.B. der Google-Bot Ihre Seite erfasst hat, werden bei einer Google-Suche Artikel aus Ihrem Shop mit deren Beschreibung etc. angezeigt. Wann solche Bots Ihre Seite besuchen, ist nicht vorhersehbar, da sie nach proprietären Algorithmen gesteuert werden.
* Bei Erweiterungen Ihres Sortiments und damit einer Vergrößerung des Bild- und Datenaufkommens. Dadurch werden mehr Bots auf Ihre Seite aufmerksam.

[IMPORTANT]
.Bots per robots.txt sperren lassen
====
Um das oben beschriebene Verhalten von Bots zumindest teilweise zu steuern, können Sie z.B. die Sperrung von Bots per **robots.txt-Datei** veranlassen. Weitere Informationen finden Sie in unserem **<<cms-syntax/fallbeispiele/seo-guide#, SEO-Guide  >>**.
====

