= Umzug
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Cloud-Umzug
:description: Cloud-Umzug
:position: 90

Im Menü **Start » plentymarkets-Konto » Umzug** beauftragen Sie einen kostenlosen Umzug Ihres Systems in eine andere Cloud. Im Menü **Umzug** werden außerdem der Status eines bereits geplanten Umzugs und Informationen zum zuletzt durchgeführten Umzug aufgeführt. Weitere Informationen zu den link:http://www.plentymarkets.eu/produkt/cloud-hosting/[**Cloud-Lösungen von plentymarkets**] finden Sie auf unserer Website.

toc::[]
== Voraussetzungen für einen Systemumzug

Stellen Sie sicher, dass die folgenden Voraussetzungen erfüllt sind, bevor Sie einen Umzug Ihres Systems in eine andere Cloud planen:

* Ihre Domain wird durch plentymarkets verwaltet. Ist dies nicht der Fall, ziehen Sie Ihre <<start/plentymarkets-konto/service-center/domain#, **Hauptdomain**  >> um.
* Sie verfügen über einen aktuellen plentymarkets Cloud Vertrag. Ist dies nicht der Fall, passen Sie Ihren link:http://www.plentymarkets.eu/preise/plentymarkets-classic-buchen/[**Vertrag**] an.
* Der Termin für den Start des Systemumzugs liegt mindestens 2 Tage in der Zukunft.

[WARNING]
.Dateien auf FTP-Server werden nicht migriert
====
Beim Umzug in eine andere Cloud ändert sich auch die FTP-Host-Adresse des plentymarkets Systems. Die Daten auf dem alten FTP-Host werden beim Umzug nicht zur neuen FTP-Hostadresse kopiert. Sie müssen die FTP-Dateien selbst umziehen.
====

== Umzug planen

Gehen Sie wie unten beschrieben vor, um einen Umzug Ihres Systems in eine andere Cloud zu planen. Beachten Sie, dass pro Cloud nicht mehr als ein Systemumzug zeitgleich stattfindet. Der tatsächliche Zeitpunkt, zu dem Ihr Umzug gestartet wird, kann sich daher ggf. verzögern.

[.instruction]
Umzug planen:

. Öffnen Sie das Menü **Start » plentymarkets-Konto » Umzug**.
. Öffnen Sie das Tab **Umzug planen**.
. Wählen Sie die Ziel-Cloud, d.h. die Cloud, in die Sie Ihr System umziehen möchten. +
→ Die Kosten für die Ziel-Cloud werden angezeigt.
. Wählen Sie das Datum, an dem der Systemumzug starten soll.
. Wählen Sie die Uhrzeit, zu der der Systemumzug starten soll. +
→ Der Termin für den Start des Systemumzugs muss mindestens 2 Tage in der Zukunft liegen.
. Klicken Sie auf **Umzug starten**, um den Umzug in Auftrag zu geben. +
→ Der geplante Umzug wird im Tab **Geplanter Umzug** angezeigt und zu diesem Zeitpunkt gestartet.

[IMPORTANT]
.Shop-Verfügbarkeit
====
Bei mittelgroßen Systemen dauert ein Umzug erfahrungsgemäß ca. 20 Minuten. Die tatsächliche Dauer ist jedoch immer von der zu übertragenden Datenmenge des Systems abhängig. Während dieser Zeit ist ihr plentymarkets System verfügbar, Sie können jedoch keine Änderungen im System speichern. Auch der Bestellvorgang Ihres Onlineshops ist deaktiviert, während der Umzug durchgeführt wird. Wählen Sie daher eine Uhrzeit, zu der mit wenig Traffic zu rechnen ist. Wir empfehlen Ihnen, den Umzug für die Nachtstunden zu planen.
====

== Geplanten Umzug abbrechen

Sie können einen geplanten Umzug so lange abbrechen, bis alle Vorgänge, die im Menü **Start » plentymarkets-Konto » Umzug » Tab: Geplanter Umzug** angezeigt werden, vollständig abgeschlossen sind. Dabei wird der Umzug zum nächstmöglichen Zeitpunkt abgebrochen, also ggf. nicht sofort. Gehen Sie wie unten beschrieben vor, um einen geplanten Umzug abzubrechen.

[.instruction]
Umzug abbrechen:

. Öffnen Sie das Menü **Start » plentymarkets-Konto » Umzug**.
. Öffnen Sie das Tab **Geplanter Umzug**.
. Klicken Sie auf **Umzug abbrechen**. +
→ Der Umzug wird zum nächsten möglichen Zeitpunkt abgebrochen. Bereits abgeschlossene Vorgänge werden zurück in die bisherige Cloud gezogen.

Wenn alle Vorgänge bereits abgeschlossen, d.h. das System komplett umgezogen wurde, müssen Sie einen neuen Umzug beauftragen, um Ihr System zurück in die bisherige Cloud zu ziehen.

