= Dokumente
:lang: de
// include::{includedir}/_header.adoc[]
:position: 60
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Im Menü *CMS » Dokumente* lädst duDokumente hoch, um diese Dokumente z.B. als Anhang von E-Mail-Vorlagen automatisch an deine Kunden zu senden. Du kannst verschiedene Datenformate hochladen, z.B. Bilder oder PDF-Dateien.

== Dokumente hochladen

Gehe wie unten beschrieben vor, um Dokumente im Menü *CMS » Dokumente* hochzuladen.

[.instruction]
Ein Dokument hochladen:

. Öffne das Menü *CMS » Dokumente*.
. Klicke auf *Durchsuchen...*.
. Wähle die Datei, die du hochladen möchtest.
. Klicke auf *Öffnen*.
. Wähle eine der Optionen unter *Berechtigung*.
. Trage einen *Ordnernamen* ein (optional).
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Tipp
====
Mit der Berechtigung legst du fest, ob das Dokument nur für *Kunden*, nur für *Mitarbeiter* oder für alle Besucher des Webshops verfügbar sein sollen (*öffentlich*).
====

== Dokumente mit E-Mail-Vorlagen verknüpfen

Du kannst hochgeladene Dokumente automatisch an E-Mail-Vorlagen anhängen. Pro E-Mail-Vorlage ist ein Dokument verknüpfbar. Gehe dazu wie unten beschrieben vor.

[.instruction]
Dokument mit E-Mail-Vorlage verknüpfen:

. Öffne das Menü <<crm/e-mails-versenden#1200, System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen>>.
. Öffne die gewünschte E-Mail-Vorlage.
. Wähle in der Dropdown-Liste *Dokumentenanhang* die Datei, die als Anhang verwendet werden soll.
. Klicke auf *Speichern*, um die Einstellung zu sichern.
