= Dokumente
:lang: de
// include::{includedir}/_header.adoc[]
:position: 60

Im Menü *CMS » Dokumente* laden Sie Dokumente hoch, um diese Dokumente z.B. als Anhang von E-Mail-Vorlagen automatisch an Ihre Kunden zu senden. Sie können verschiedene Datenformate hochladen, z.B. Bilder oder PDF-Dateien.

== Dokumente hochladen

Gehen Sie wie unten beschrieben vor, um Dokumente im Menü *CMS » Dokumente* hochzuladen.

[.instruction]
Ein Dokument hochladen:

. Öffnen Sie das Menü *CMS » Dokumente*.
. Klicken Sie auf *Durchsuchen...*.
. Wählen Sie die Datei, die Sie hochladen möchten.
. Klicken Sie auf *Öffnen*.
. Wählen Sie eine der Optionen unter *Berechtigung*.
. Tragen Sie einen *Ordnernamen* ein (optional).
. *Speichern* Sie die Einstellungen.

[TIP]
.Tipp
====
Mit der Berechtigung legen Sie fest, ob das Dokument nur für *Kunden*, nur für *Mitarbeiter* oder für alle Besucher des Webshops verfügbar sein sollen (*öffentlich*).
====

== Dokumente mit E-Mail-Vorlagen verknüpfen

Sie können hochgeladene Dokumente automatisch an E-Mail-Vorlagen anhängen. Pro E-Mail-Vorlage ist ein Dokument verknüpfbar. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Dokument mit E-Mail-Vorlage verknüpfen:

. Öffnen Sie das Menü <<crm/e-mails-versenden#1200, System » Mandant » Mandant wählen » E-Mail » Vorlagen>>.
. Öffnen Sie die gewünschte E-Mail-Vorlage.
. Wählen Sie in der Dropdown-Liste *Dokumentenanhang* die Datei, die als Anhang verwendet werden soll.
. Klicken Sie auf *Speichern*, um die Einstellung zu sichern.
