= Konstanten
:lang: de
// include::{includedir}/_header.adoc[]
:position: 90

In die Textfelder des Menüs *CMS » Konstanten* trägst du wiederkehrende Inhalte ein, die in das Design deines Webshops eingebunden werden können. Es stehen 25 Konstanten zur Verfügung. Die Verknüpfung über eine Konstante ermöglicht es, Inhalte wiederzuverwenden und zentral in diesem Menü zu bearbeiten anstatt diese Inhalte einzeln im Design anzupassen. Die Inhalte können HTML-Code oder JavaScript-Code enthalten. Auch <<omni-channel/online-shop/webshop-einrichten/_cms/einstellungen/artikel-galerie#, Artikel-Galerien>> werden mit Konstanten verknüpft.

== Konstanten definieren

Zunächst hinterlegst du einen Wert für die Konstante. Gehe dazu wie unten beschrieben vor. Wenn du eine Konstante mit einer Artikel-Galerie verknüpfst, wird automatisch Code als *Wert* der Konstanten eingefügt. Trage deshalb für <<omni-channel/online-shop/webshop-einrichten/_cms/einstellungen/artikel-galerie#, Artikel-Galerien>> keinen Wert ein.

[.instruction]
Konstanten definieren:

. Öffne das Menü *CMS » Konstanten*.
. Trage die Inhalte in das Textfeld der gewünschten Konstante ein.
. *Speichere* die Einstellungen. +
→ Die Inhalte können nun über die Konstante in den Webshop eingebunden werden.

[TIP]
.PHP-Skripte einbinden
====
PHP-Skripte können nicht als Konstante gespeichert werden. Lege PHP-Skripte extern ab, z.B. auf einem FTP-Server. Hinterlege die Verlinkung zu diesem Skript als *Wert* der Konstanten, um das Skript so aufzurufen.
====

== Konstanten in Design einfügen

Binde nun die Konstante in deinem Webshop ein. Gehe dazu wie unten beschrieben vor.

[.instruction]
Konstante in Design einfügen:

. Öffne das Menü *CMS » Webdesign » Layout*.
. Öffne das gewünschte Template.
. Füge die Konstante an der Position in das Template ein, an der die Inhalte angezeigt werden sollen.
. *Speichere* die Einstellungen.

Analog können Konstanten auch in Kategorien eingebunden werden.
