= Kunden-Feedback
:lang: de
// include::{includedir}/_header.adoc[]
:position: 110

Im Menü *CMS » Kunden-Feedback* werden alle Bewertungen aus Ihrem Webshop gesammelt. In der Übersicht werden alle Bewertungen aus allen Bereichen zusammen angezeigt. Nutzen Sie die Suche, um sich z.B. nur Bewertungen eines Typs, eines Zeitraums oder eines bestimmten Kunden anzeigen zu lassen.

== Kunden-Feedback einrichten

Richten Sie das Modul zunächst im Menü <<omni-channel/mandant-shop/globale-einstellungen/kunden-feedback#, System » Systemeinstellungen » Mandant » Global » Feedback>> ein und aktivieren Sie Bewertungen für die gewünschten Bereiche.

== Kunden-Feedback bearbeiten

Bewertungen und Kommentare, die in Ihrem Webshop eingehen, werden im Menü *CMS » Kunden-Feedback* gelistet. Hier stellen Sie Bewertungen sichtbar oder unsichtbar und bearbeiten Kommentare, falls diese z.B. nicht Ihrer Netiquette entsprechen.

[.instruction]
Bewertung bearbeiten:

. Öffnen Sie das Menü *CMS » Kunden-Feedback*.
. Klicken Sie in die Zeile eines Feedbacks, um es zu bearbeiten.
. Nehmen Sie die gewünschten Änderungen vor.
. *Speichern* Sie die Einstellungen.

[NOTE]
.Sichtbarkeit einstellen
====
Klicken Sie in der Übersicht auf das *Auge*, um eine Bewertung im Webshop sichtbar oder unsichtbar zu stellen. Ist eine Bewertung unsichtbar, ist das Auge mit einem *roten X* durchgestrichen. In der Bearbeitungsansicht eines Feedbacks kann die Sichtbarkeit über die Dropdown-Liste *Sichtbarkeit* geändert werden.
====

== Beispielkonfiguration im CMS

Um das Feature in Ihrem Webshop anzuzeigen, finden Sie im Bereich *CMS » Webdesign » Ordner: Layout » Ordner: Form* die passenden Templates und Template-Variablen.

=== Google reCAPTCHA einrichten

Richten Sie Google reCAPTCHA für das Webshop-Formular für die Bewertung von Artikeln ein. Registrieren Sie Ihren Webshop zunächst für die Verwendung von link:https://www.google.com/recaptcha/admin#list[Google reCAPTCHA^]. Geben Sie anschließend den Websiteschlüssel und den Geheimen Schlüssel für Ihren Webshop ein.

[.instruction]
Google reCAPTCHA einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Einstellungen*.
. Geben Sie den *Google reCAPTCHA Websiteschlüssel* ein.
. Geben Sie den *Google reCAPTCHA Geheimer Schlüssel* ein.
. *Speichern* Sie die Einstellungen.

=== Bewertungsformular anzeigen

Das folgende Code-Beispiel zeigt ein Webshop-Formular für die Bewertung von Artikeln im Template *FormItemFeedback*. Dieses Template fügen Sie dann mit dem Container *{% Container_FormItemFeedback($ID) %}* zum Beispiel im Template *ItemViewSingleItem* ein, um das Bewertungsformular bei einzelnen Artikeln anzuzeigen.

Die CSS-Klassen im folgenden Code dienen einer beispielhaften Darstellung. Passen Sie den Code nach Ihren Wünschen an.

[source,plenty]
----
include::assets/EX-DE-CMS-feedback-form.html[]

----
=== Bewertungen als Liste anzeigen

Sie haben auch die Möglichkeit, vorhandene Bewertungen als Liste im Webshop auszugeben. Konfigurieren Sie diese Liste im Template *MiscFeedbackList* unter *CMS » Webdesign » Ordner: Layout » Ordner: Misc*.
Der Code kann wie im folgenden Beispiel aussehen. Fügen Sie den Container *{% Container_MiscFeedbacksList('item',$ID) %}* dann an der Stelle in das Template ein,
an der Sie die Liste anzeigen möchten, zum Beispiel im Template *ItemViewSingleItem*.

[source,plenty]
----
include::assets/EX-DE-CMS-feedback-list.html[]

----
