= Kunden-Feedback
:lang: de
// include::{includedir}/_header.adoc[]
:position: 110
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Im Menü *CMS » Kunden-Feedback* werden alle Bewertungen aus deinem Webshop gesammelt. In der Übersicht werden alle Bewertungen aus allen Bereichen zusammen angezeigt. Nutze die Suche, um dir z.B. nur Bewertungen eines Typs, eines Zeitraums oder eines bestimmten Kunden anzeigen zu lassen.

== Kunden-Feedback einrichten

Richte das Modul zunächst im Menü <<omni-channel/mandant-shop/globale-einstellungen/kunden-feedback#, System » Systemeinstellungen » Mandant » Global » Feedback>> ein und aktiviere Bewertungen für die gewünschten Bereiche.

== Kunden-Feedback bearbeiten

Bewertungen und Kommentare, die in deinem Webshop eingehen, werden im Menü *CMS » Kunden-Feedback* gelistet. Hier stellst du Bewertungen sichtbar oder unsichtbar und bearbeiten Kommentare, falls diese z.B. nicht deiner Netiquette entsprechen.

[.instruction]
Bewertung bearbeiten:

. Öffne das Menü *CMS » Kunden-Feedback*.
. Klicke in die Zeile eines Feedbacks, um es zu bearbeiten.
. Nimm die gewünschten Änderungen vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[NOTE]
.Sichtbarkeit einstellen
====
Klicke in der Übersicht auf das *Auge*, um eine Bewertung im Webshop sichtbar oder unsichtbar zu stellen. Ist eine Bewertung unsichtbar, ist das Auge mit einem *roten X* durchgestrichen. In der Bearbeitungsansicht eines Feedbacks kann die Sichtbarkeit über die Dropdown-Liste *Sichtbarkeit* geändert werden.
====

== Beispielkonfiguration im CMS

Um das Feature in deinem Webshop anzuzeigen, findest du im Bereich *CMS » Webdesign » Ordner: Layout » Ordner: Form* die passenden Templates und Template-Variablen.

=== Google reCAPTCHA einrichten

Richte Google reCAPTCHA für das Webshop-Formular für die Bewertung von Artikeln ein. Registriere deinen Webshop zunächst für die Verwendung von link:https://www.google.com/recaptcha/admin#list[Google reCAPTCHA^]. Gib anschließend den Websiteschlüssel und den Geheimen Schlüssel für deinen Webshop ein.

[.instruction]
Google reCAPTCHA einrichten:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Einstellungen*.
. Gib den *Google reCAPTCHA Websiteschlüssel* ein.
. Gib den *Google reCAPTCHA Geheimer Schlüssel* ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

=== Bewertungsformular anzeigen

Das folgende Code-Beispiel zeigt ein Webshop-Formular für die Bewertung von Artikeln im Template *FormItemFeedback*. Dieses Template fügst du dann mit dem Container *{% Container_FormItemFeedback($ID) %}* zum Beispiel im Template *ItemViewSingleItem* ein, um das Bewertungsformular bei einzelnen Artikeln anzuzeigen.

Die CSS-Klassen im folgenden Code dienen einer beispielhaften Darstellung. Passe  den Code nach deinen Wünschen an.

[source,plenty]
----
include::assets/EX-DE-CMS-feedback-form.html[]

----
=== Bewertungen als Liste anzeigen

Du hast auch die Möglichkeit, vorhandene Bewertungen als Liste im Webshop auszugeben. Konfiguriere diese Liste im Template *MiscFeedbackList* unter *CMS » Webdesign » Ordner: Layout » Ordner: Misc*.
Der Code kann wie im folgenden Beispiel aussehen. Füge den Container *{% Container_MiscFeedbacksList('item',$ID) %}* dann an der Stelle in das Template ein,
an der du die Liste anzeigen möchtest, zum Beispiel im Template *ItemViewSingleItem*.

[source,plenty]
----
include::assets/EX-DE-CMS-feedback-list.html[]

----
