= plentymarkets CMS library
:lang: de
// include::{includedir}/_header.adoc[]
:position: 120

Die link:https://github.com/plentymarkets/plenty-cms-library[plentymarkets CMS library^] ist ein von plentymarkets entwickeltes Open-Source-Projekt.
Das Projekt lagert die logischen JavaScript-Elemente des plentymarkets CMS aus und ermöglicht so eine bessere Trennung von Layout und Logik. Innerhalb des Projekts wurde
Wert auf Modularisierung, Testbarkeit, Internationalisierung und Unabhängigkeit von JavaScript-Frameworks gelegt. +
Das Projekt liegt auf link:https://github.com/plentymarkets/plenty-cms-library[GitHub.com^] und kann kostenlos heruntergeladen und weiterentwickelt werden. Hier erfährst du, wie du neue Versionen der plentymarkets CMS library in dein plentymarkets CMS einbindest.

== plentymarketsCMStools Version aktualisieren

Das Projekt plentymarkets CMS library führt die Projektdateien in der JavaScript-Datei plentymarketsCMStools-x.x.x.js zusammen, die du im GitHub-Projektordner */dist* findest. Dabei steht x.x.x für die Dateiversion. Welche Version du aktuell verwendest, prüfst du im Menü <<omni-channel/online-shop/webshop-einrichten/_cms/webspace#, CMS » Webspace>> und dort im Ordner *layout » Ihr Design » js » plenty*. Gehe wie unten beschrieben vor, um eine neue Version der Datei *plentymarketsCMStools-x.x.x.js* einzubinden. +

[WARNING]
.Kompatibilität
====
plentymarketsCMStools Versionen *0.9.x* sind nicht mit Versionen *1.x.x* kompatibel. Wenn du bereits ein Design verwendest, das die JavaScript-Datei *plentymarketsCMStools-x.x.x.js* einbindet,
ist es daher nicht möglich, von einer Version *0.9.x* auf Versionen *1.x.x* zu aktualisieren.
====

=== Neue Version herunterladen

Gehe wie unten beschrieben vor, um die neue Version der plentymarketsCMStools-x.x.x.js aus dem GitHub-Repository herunterzuladen.

[.instruction]
Neue Version herunterladen:

. Öffne das GitHub-Repository link:https://github.com/plentymarkets/plenty-cms-library[plentymarkets CMS library^].
. Öffne den Order *dist*.
. Klicke auf die Datei *plentymarketsCMStools-x.x.x.js*. +
→ Der Inhalt der Datei wird angezeigt.
. Rechtsklicke auf *Raw*.
. Wähle die Option *Ziel speichern unter...*
. Speichere die Datei auf deinem Rechner.

Lade die Datei * plentymarketsCMStools-x.x.x.min.js analog herunter.

=== Neue Version hochladen

Gehe wie unten beschrieben vor, um die neue Version der plentymarketsCMStools-x.x.x.js und der plentymarketsCMStools-x.x.x.min.js in den Webspace deines plentymarkets Systems hochzuladen.

[.instruction]
Neue Version hochladen:

. Öffne das Menü *CMS » Webspace*.
. Öffne den Ordner *layout » Ihr Design » js » plenty*. +
→ Ordner klappen auf, indem du links in der Übersicht auf das kleine Plus klickst.
. Klicke auf *Dateien hochladen*.
. Wähle die Datei *plentymarketsCMStools-x.x.x.js*, die du im vorherigen Schritt heruntergeladen hast. +
→ Die Datei wird hochgeladen und angezeigt.

Lade die Datei plentymarketsCMStools-x.x.x.min.js analog hoch.

=== Versionsnummer in der JSON-Datei anpassen

Die Abhängigkeiten des Callisto Light Designs sind in einer JSON-Datei hinterlegt, die sich im selben Ordner wie die Datei plentymarketsCMStools-x.x.x.js befindet. Um die neueste Version der plentymarkets CMS library nutzen zu können, musst du die in dieser Datei gespeicherte Versionnummer aktualisieren. Der Name dieser JSON-Datei lautet aktuell *scripts-3.5.json*, bei älteren plentymarkets Designs jedoch *scripts.json* oder *dependencies.json*. Der Inhalt der Dateien ist identisch. Gehe wie unten beschrieben vor, um die Versionsnummer zu aktualisieren.

Nach diesem Schritt ist es nicht mehr notwendig die Skripte, die in der *scripts-3.5.json* vorkommen, durch ein script-Tag separat einzubinden. Das Skript *ScriptLoader.js* erzeugt die notwendigen script-Tags automatisch.

[.instruction]
Versionsnummer in der JSON-Datei anpassen:

. Öffne das Menü *CMS » Webspace*.
. Öffne den Ordner *layout » Ihr Design » js » plenty*. +
→ Ordner klappen auf, indem du links in der Übersicht auf das kleine Plus klickst.
. Lade die Datei *scripts-3.5.json* herunter.
. Öffne die Datei in einem Texteditor.
. Ändere die Versionsnummer von plentymarketsCMStools-x.x.x.js auf die Version der Datei, die du in den Webspace hochgeladen hast.
. Speichere die geänderte Datei.
. Lade die aktualisierte Datei an derselben Stelle in deinem plentymarkets System wieder hoch. +
→ Aufgrund des Cachings dauert es bis zu eine Stunde, bis die neue Dateiversion im Webspace angezeigt wird.
