= Suchen und Ersetzen
:lang: de
// include::{includedir}/_header.adoc[]
:position: 100

Im Menü *CMS » Suchen &amp; Ersetzen* nimmst du global sprachliche Änderungen in Kategorien und/oder im Design vor. Bei Namens- oder terminologischen Änderungen sparst du Zeit, da du die Stellen, an denen der Begriff verwendet wird, nicht einzeln suchen musst. Durch Eingabe des bisher verwendeten und des neuen Begriffs wird eine automatische Ersetzung durch das System ausgeführt.

== Suchen und Ersetzen

Gehe wie im Folgenden beschrieben vor, um Suchbegriffe zu ersetzen.

[.instruction]
Suchen und Ersetzen:

. Öffne das Menü *CMS » Suchen &amp; Ersetzen*.
. Gib in das erste Feld der Spalte *Suchen* den zu ersetzenden Begriff ein.
. Gib den neuen Begriff in das Feld *Ersetzen* derselben Zeile ein.
. Wiederhole dieses Vorgehen mit allen gewünschten Begriffen.
. Wähle, ob die Begriffe nur in den Kategorien, nur im Design oder in den Kategorien und im Design ersetzt werden sollen.
. Entscheide, ob zusätzlich die Kategorien und das Standard-Design veröffentlicht werden sollen.
. Klicke auf das *Zahnrad*, um die Funktion auszuführen.
