= Suchen und Ersetzen
:lang: de
// include::{includedir}/_header.adoc[]
:position: 100

Im Menü *CMS » Suchen &amp; Ersetzen* nehmen Sie global sprachliche Änderungen in Kategorien und/oder im Design vor. Bei Namens- oder terminologischen Änderungen sparen Sie Zeit, da Sie die Stellen, an denen der Begriff verwendet wird, nicht einzeln suchen müssen. Durch Eingabe des bisher verwendeten und des neuen Begriffs wird eine automatische Ersetzung durch das System ausgeführt.

== Suchen und Ersetzen

Gehen Sie wie im Folgenden beschrieben vor, um Suchbegriffe zu ersetzen.

[.instruction]
Suchen und Ersetzen:

. Öffnen Sie das Menü *CMS » Suchen &amp; Ersetzen*.
. Geben Sie in das erste Feld der Spalte *Suchen* den zu ersetzenden Begriff ein.
. Geben Sie den neuen Begriff in das Feld *Ersetzen* derselben Zeile ein.
. Wiederholen Sie dieses Vorgehen mit allen gewünschten Begriffen.
. Wählen Sie, ob die Begriffe nur in den Kategorien, nur im Design oder in den Kategorien und im Design ersetzt werden sollen.
. Entscheiden Sie, ob zusätzlich die Kategorien und das Standard-Design veröffentlicht werden sollen.
. Klicken Sie auf das *Zahnrad*, um die Funktion auszuführen.
