= Termine
:lang: de
// include::{includedir}/_header.adoc[]
:position: 80

Im Menü *CMS » Termine* erstellet du Termine. Diese Termine können z.B. auf einer Kategorie unter der Rubrik *News* angezeigt werden.

== Neuen Termin erstellen

Gehe wie unten beschrieben vor, um einen neuen Termin zu erstellen.

[.instruction]
Einen neuen Termin erstellen:

. Öffne das Menü *CMS » Termine*.
. Klicke auf das grüne *Plus*, um einen neuen Termin zu erstellen. +
→ Das Fenster *Neuer Termin* wird geöffnet.
. Trage die Daten des Termins ein.
. *Speichere* die Einstellungen. +
→ Der Termin wird im Tab *Vorschau* angezeigt.

== Termine bearbeiten

Bestehende Termine können bearbeitet werden. Gehe dazu wie unten beschrieben vor.

[.instruction]
Einen Termin bearbeiten:

. Öffne das Menü *CMS » Termine*.
. Öffne das Tab *Vorschau*.
. Klicke in der Spalte *Aktionen* auf den *Stift*, um einen Termin zu bearbeiten. +
→ Das Bearbeitungsfenster des Termins wird geöffnet.
. Nimm die gewünschten Änderungen vor.
. *Speichere* die Einstellungen.

== Termine suchen

Wenn du eine große Anzahl von Terminen gespeichert hast, erleichtert es dir die Terminsuche, einzelne Termine zu finden. Gehe wie unten beschrieben vor, um einen Termin zu finden.

[.instruction]
Einen Termin suchen:

. Öffne das Menü *CMS » Termine*.
. Öffne das Tab *Suche*.
. Wähle den Suchzeitraum, indem du ein Datum unter *von* sowie ein Datum unter *bis* wählst.
. Klicke auf die *Lupe*. +
→ Die Termine dieses Zeitraums werden angezeigt.

== Termine löschen

Gehe wie unten beschrieben vor, um Termine zu löschen.

[.instruction]
Einen Termin löschen:

. Öffne das Menü *CMS » Termine*.
. Öffne das Tab *Vorschau*.
. Klicke in der Spalte *Aktionen* des Termins, den du löschen möchtest, auf *Löschen*. +
→ Der Termin wird gelöscht.

== Termine ins Webshop-Design einbinden

Die Termine werden über das Template *MiscDatesList* angezeigt. Dieses Template findest du im Menü *CMS » Webdesign » Layout » Misc*. Du kannst den Code im Layout anpassen und z.B. weitere Parameter anzeigen lassen, z.B. den *Ort* mit der Template-Variable *$City*.

[IMPORTANT]
.$Container_MiscDatesList
====
Die Template-Variable zum Aufruf des Templates ist *$Container_MiscDatesList*.
====
