= Webspace
:lang: de
// include::{includedir}/_header.adoc[]
:position: 30
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

Das Webspace-Tool im Menü *CMS » Webspace* ermöglicht es dir, Daten auf den plentymarkets Server hochzuladen, die du deinen Kunden zur Verfügung stellen möchtest. Dies können Bilder, PDF-Dokumente und andere Dateien sein, die online für alle Besucher verfügbar gemacht werden sollen. Verwende dieses Tool, wenn du Bilder für dein Design auf Datei-Ebene verwalten möchtest. Lege für jedes Design einen Unterordner des Ordners *layout/* an.

== Upload-Einschränkungen

Für Uploads gelten die folgenden Einschränkungen:

* PHP-Dateitypen können nicht hochgeladen werden.
* Ein Upload ist auf 10 MB pro Vorgang begrenzt.

== Neuen Ordner erstellen

Die vorhandene Ordnerstruktur kann durch Anlegen weiterer Ordner erweitert werden. Gehe dazu wie unten beschrieben vor.

[.instruction]
Neuen Ordner erstellen:

. Wähle den gewünschten Zielordner bzw. die unterste Ebene (= /).
. Klicke dann auf *Neuer Ordner*.
. Trage einen *Namen* für den neuen Ordner ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

== Dateien hochladen

Gehe wie unten beschrieben vor, um Dateien in einen Ordner hochzuladen.

[.instruction]
Datei(en) hochladen:

. Wähle den Zielordner.
. Klicke auf *Dateien hochladen*.
. Wähle die Datei(en), die du hochladen möchtest.
. Klicke auf *Öffnen*.

== Alternativen zum Webspace-Upload

Einzelne Bilder kannst du auch über das Menü <<omni-channel/online-shop/webshop-einrichten/cms#bilder-galerie, Bilder-Galerie>> verwalten. Als weitere Option kannst du Bilder und Dokumente auch direkt dort, wo diese verwendet werden sollen, an der Kategorie im Tab <<artikel/kategorien-verwalten#, Dokumente>>, hochladen.
