= FBA vs. MFN
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Amazon FBA, FBA, FBA orders, FBA order
:description: Multi-Channel in plentymarkets: Amazon FBA with plentymarkets.
:position: 10
:url: markets/amazon/amazon-fulfilment/fulfilment
:id: QYFYPFT
:author: team-multi-channel

You can organise the shipping of variations sold on Amazon in two different ways:

[#100]
== Amazon FBA: Amazon stores and ships

The abbreviation FBA stands for Fulfilment by Amazon. Instead of dealing with the orders yourself, packaging the items and sending them, you let Amazon take care of this task for you with the FBA programme. Of course, you then have to store at least some of your items with Amazon. Learn how to set up the FBA service by Amazon on the <<markets/amazon/amazon-fba#, Using the FBA service by Amazon>> page of the manual. In addition, the Multi-Channel function allows you to store your items with Amazon and have Amazon ship your items even though you sell these items on external markets.

Sequence of FBA orders:

* Your products are listed on Amazon. The name of your company is shown with your products.
* Customers place an order on Amazon.
* Customers make their payments to Amazon.
* Amazon sends the items.
* The plentymarkets system requests a report.
* Amazon creates the report.
* The next day, plentymarkets automatically checks whether any Amazon reports exist. If yes, then these reports are imported.
* From the information contained in these reports, orders and contacts are generated in plentymarkets.
* 1 month after the order is created, the contacts are anonymized:
  ** First name and last name of the contact is anonymized.
  ** The following data is deleted:
      *** Addresses and address relations
      *** Address options
      *** Order relations
      *** Contact options
      *** Any relation to a company
      *** Bank details

[#200]
== Amazon MFN: You store and ship

MFN is short for Merchant Fulfillment Network. That means: You process your Amazon orders and pack and ship the orders. Our best practice <<markets/amazon/best-practices-amazon-mfn-order-import#, MFN order import>> tells you more.

Sequence of MFN orders:

* Your products are listed on Amazon. The name of your company is shown with your products.
* Customers place an order on Amazon.
* Customers make their payments to Amazon.
* → The order is imported to plentymarkets.
* A contact is created for the order.
* You ship the items (drop shipping).
* The contact is anonymized 30 days after shipping is confirmed:
  ** First name and last name of the contact is anonymized.
  ** The following data is deleted:
      *** Addresses and address relations
      *** Address options
      *** Order relations
      *** Contact options
      *** Any relation to a company
      *** Bank details

[#300]
== Decisions, decisions: FBA or MFN?

Only you can decide whether the advantages tied to the FBA service outweigh the disadvantages for your personal situation as an online seller. Here we would only like to make reference to a few important points:

*  Amazon processes orders quickly and reliably. Peak times before Christmas run just as smoothly for store owners as the summer slump while most people are away on vacation.
*  Your listing on the market improves noticeably. You can expect higher sales figures.
*  The FBA service is subject to costs. Naturally, your gross margin will decrease. When doing a comprehensive comparison of the costs, keep in mind that the FBA service includes the expenses tied to storage, handling orders, customer service etc. and as such, relieves you from these expenditures.
*  Generally, items that are stored with Amazon can only be offered there as well. You need to have separate stock for other markets. Amazon's Multi-Channel fulfilment service, however, is a variation that provides you with additional possibilities in this matter.
*  You have much less stress with deliveries that cannot be sent or that are delayed. Packages with the Amazon logo are generally given priority.
