= Categories
:lang: en
include::{includedir}/_header.adoc[]
:position: 30

**plentymarkets » Item » Categories**

== What are categories in plentymarkets?

There are different types of categories in plentymarkets. On the one hand, categories are what other systems may refer to as product groups or item categories. On the other hand, categories are also content pages for your **CMS**. The different types of categories have many settings in common. For example, all types of categories are managed within a folder structure. This is done by creating **main categories** and **subcategories**. All types of categories also typically include texts such as a description, short description, meta description and graphic elements. This is why all types of categories are managed together in plentymarkets.

You can tell the categories apart in plentymarkets by their type. The types <<item/categories/item-categories#, **Item**>>, <<item/categories/editing-content-categories#, **Content**>> and <<item/categories/editing-container-categories#, **Container**>> are available. By managing all types of categories together, each type has access to a few additional settings that would otherwise only be applicable to one of them. In some cases, these settings are also useful for the other types. For example, you can use a template variable to insert a short description for the type **Content**. You can use tags for the type **Item**.

Use the type **Item** for your item categories, i.e. for the categories that are used to group your items together in the online store. Use the type **Content** for all of the information in your store, i.e. for your terms and conditions, payment information and shipping information. Categories of the type **Container** are used for designing the order steps of the <<omni-channel/online-store/cms#web-design-editing-the-web-design-order-process-individual-order-process, **individual order process**>>. Create the category structure with main categories that each contain up to 5 subcategories. You can edit the content with an integrated HTML editor.

For further information about creating a category, refer to the <<item/categories/editing-categories#, **Editing categories**>> page of the manual. For specific information about the different category types, refer to the corresponding pages of the manual.

== Video tutorials

Learn more about categories in the following video tutorial:

[.linkBox]
link:https://www.plentymarkets.co.uk/a-3409/[Categories, window="_blank"]

