= Checking status of item data
:lang: en
include::{includedir}/_header.adoc[]
:position: 50

When you edit a substantial amount of item data or create a lot of items in one go, it takes a while for such changes to become available in the following areas of plentymarkets:

* Item display in Ceres
* Item search in Ceres
* Item data in the elastic export

How long it takes for the data to become available depends on how many items were created and/or changed:

* If you manually create one or a few items in the plentymarkets back end, it takes about 15 minutes for the changes to be visible in the online store and can be exported using the Elastic Export.
* If you create or update many items, for example using batch processing or imports, it can take a long time for the changes to be visible in the online store and can be exported using the Elastic Export. How long it takes depends on the types of changes you have made and how many variations are affected by this change.

== Technical background of item data status

Item data is saved in database. However, because it would take too long to retrieve this data from the database, this data is cached in ElasticSearch. The item view and item search in Ceres and the Elastic Export do not get item data from the database, but from ElasticSearch instead. This means it is much quicker to browse for items and open individual item views in the online store. The speed of the Elastic Export is also increased by relying on ElasticSearch. However, depending on how many items are changed it can take a substantial amount of time before the data is updated in ElasticSearch.

== Checking status of item data

Proceed as described below to check the status of item data. The view shows the status of the following item data:

* Item data in the elastic export
* Item search in Ceres
* Item display in Ceres

[.instruction]
Checking status of item data:

. Go to *Data » Status*. +
→ The menu *Status* opens. +
→ In the *Variations* row, you can see what percentage of the item data is up to date. <<table-data-status>> shows the available statuses. +
. The progress bar is not updated in real time. Reload the tab to see any changes in progress. +
*_Note:_* The plentymarkets Support cannot speed up the time it takes to update item data.


[[table-data-status]]
.Possible statuses of item data
[cols="1,3"]
|====
|Status |Description

|*Up to date*
|The item data is up to date.

|*Changed*
|Existing items have been changed. +
→ The changes are not yet available in the Ceres online store or the Elastic Export.

|*New*
|New items have been created. +
→ The new items are not yet available in the Ceres online store or the Elastic Export.
|====
