= Checking status of item data
:lang: en
include::{includedir}/_header.adoc[]
:position: 50
:url: item/checking-data-status
:id: PSROCEP

When you edit a substantial amount of item data or create a lot of items in one go, it takes a while for such changes to become available in the following areas of plentymarkets:

* Item display in Ceres
* Item search in Ceres
* Item data in the elastic export

How long it takes for the data to become available depends on how many items were created and/or changed:

* If you manually create one or a few items in the plentymarkets back end, it takes about 15 minutes for the changes to be visible in the online store and can be exported using the Elastic Export.
* If you create or update many items, for example using batch processing or imports, it can take a long time for the changes to be visible in the online store and can be exported using the Elastic Export. How long it takes depends on the types of changes you have made and how many variations are affected by this change.

== Technical background of item data status

Item data is saved in a database. However, because it would take too long to retrieve this data from the database, this data is cached in ElasticSearch. The item view and item search in Ceres and the Elastic Export do not get item data from the database, but from ElasticSearch instead. This means it is much quicker to browse for items and open individual item views in the online store. The speed of the Elastic Export is also increased by relying on ElasticSearch. How long it takes for the changes to be updated in ElasticSearch depends on the number of items that were changed.

== Checking status of item data

Proceed as described below to check the status of item data. The view shows the status of the following item data:

* Item data in the elastic export
* Item search in Ceres
* Item display in Ceres

[.instruction]
Checking status of item data:

. Go to *Data » Status*. +
→ The menu *Status* opens. +
→ In the *Item data in ElasticSearch* row, you can see what percentage of the variation data is current. <<table-freshness-status>> shows the available statuses. +
. The progress bar is not updated in real time. Click on *Reload* to check progress. +
*_Note:_* The plentymarkets Support cannot speed up the time it takes to update item data.


[[table-data-status]]
.Possible statuses of item data
[cols="1,3"]
|====
|Status |Explanation

|*Up to date*
|The item data is up to date.

|*Changed*
|Existing items have been changed. +
→ The changes are not yet available in the Ceres online store or the Elastic Export.

|*New*
|New items have been created. +
→ The new items are not yet available in the Ceres online store or the Elastic Export.
|====

== Previewing an item or a variation

Use the preview button to view items or variations straight after you created or edited them.

[.instruction]
Previewing an item or a variation:

. Go to *Item » Edit item*.
. Open the item. +
→ The *Settings* tab of the main variation opens.
. To preview the item, click on the preview icon in the save bar of the item.
. To preview the variation, open the tab of the variation and click on the preview icon in the save bar of the variation. +
→ The *Client (store)* window is displayed. +
. From the drop-down list *Plugin set*, select the plugin set in which you want to preview the item or variation.
. From the drop-down list *Client (Store)*, select the client in which you want to preview the item or variation. +
*_Tip:_* These settings are preselected next time you click on the preview icon.
. Click on *Execute*. +
→ A preview of the item or the variation is shown.
