= Managing multipacks, item bundles and sets
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Grouping variations, combining variations, combining products, combination offers, combined offers
:description: Find out how to combine variations in plentymarkets to sell them in bundles.
:position: 40

plentymarkets offers a variety of ways of combining products to sell them as a single sales unit. This means that the customer can add more than one product to the shopping cart at the same time. <<table-combining-products>> shows the different options for combining products.

[TIP]
.Are you familiar with how to manage items?
====
The information presented on this page serves as reference for users who are familiar with managing items in plentymarkets. For basic information on creating and managing items and variations, refer to the <<item/managing-items#, Managing items>> page of the manual.
====

[[table-combining-products]]
.Selling multiple products at the same time
[cols="1,5,1"]
|====
|Type |Explanation |Item type

|<<#1000, Multipack>>
a|* Multipacks consist of the same variation in different quantities.
* The main variation corresponds to a quantity of 1 of the other variations of the item.
* Stock is managed for the main variation only.
* The variations of the item are different quantities of the main variation.
|Multipack

|<<#2000, Bundle>>
a|* Bundles consist of a specific variation of different items.
* Customers select a bundle but cannot select between different options for the bundle components.
|Standard

|<<#3000, Set>>
a|*_Note:_* Set items currently cannot be rendered in the online store.

* Sets consist of several items.
* For each item of the set, customers select the variation they want to buy.
* The main variation is virtual. This means that the main variation is not a sellable product.
|Set
|====


[#1000]
== Setting up a multipack

For *Multipack* items, the main variation is the smallest sales unit of the product. All other variations of the item are combinations of this smallest sales unit. Stock is managed for the main variation only. All variations of the item have the same attributes. That means that customers cannot select between different colours or other characteristics of the product. In the online store, customers select the variation with the number of products they want to buy.


[#1100]
=== Creating a Multipack item

Just like when you create *Default* items, a main variation is always created when a new multipack item is created. This main variation is linked permanently to the *Multipack* item and can only be created or deleted at the same time as the item itself. This main variation itself is the smallest sales unit of the product.

[.instruction]
Creating a Multipack item:

. Go to *Item » Edit item*.
. Click on *New*. +
→ The *New item* tab opens.
. Select the type *Multipack*.
. Carry out the additional settings. Pay attention to the information given in <<table-combining-products>>.
. *Save* the settings. +
→ The *Multipack* item is created. +
→ The main variation opens in a new tab.

[TIP]
.Displaying new *Multipack* items in the item overview
====
The new *Multipack* item is not active. To display recently created items in the item overview in the *Item » Edit item* menu, select the *ALL* option for the *Active* filter in the search area. Then click on *Search*. Learn how to activate items and variations for the online store in the <<item/managing-items#180, Setting the availability>> chapter.
====

[[table-create-set-items]]
.Creating a Multipack item
[cols="1,2"]
|====
|Setting |Explanation

2+|*Item data*

|*Type*
|Select the item type *Multipack*. +
*Default* = Creates a *Default* item with main variation. +
*Set* = Creates a *Set* item.
*Multipack* = Creates a *Multipack* item.

|*ID*
|The item ID is a unique, consecutive number that is used to identify each item in plentymarkets. If you leave this field empty, plentymarkets automatically assigns the next available ID.

|*Name*
|Enter a name for the multipack. The name is a mandatory entry. Learn how to change the name in the <<item/managing-items#50, Entering item texts>> chapter.

2+|*Variation » Category link*

|Category selection
|Select the category in which the multipack is to be published. Alternatively, click on *New category* to create a new category.
|====

[#1300]
=== Editing Multipack items

Now that you have created the *Multipack* item, you can refine the settings for the multipack. These settings are identical to the settings for <<item/managing-items#30, Default items>>.

[#1400]
=== Creating a multipack variation

A main variation is always created when a new *Multipack* item is created. The main variation is linked to an item. The main variation cannot be deleted. This main variation is the smallest sales unit of the product. All other variations of the item are this smallest sales unit multiplied by x. The stock of all variations is managed in the main variation only. The *Stock* tab of all other variations of the item only shows the theoretical stock. When the stock level of the main variation changes, the stock for all other variations of the item is recalculated.

[.instruction]
Creating a multipack variation:

. Go to *Item » Edit item*.
. Open the *Multipack* item.
. Open the *Variations* tab.
. Click on *New*. +
→ The *Create new variations* window opens.
. As the content, enter a quantity for the main variation.
*_Tip:_* The variation’s units and the attributes cannot be changed.
. Click on *Create variation*. +
→ The variation is created. +
→ The variation is displayed in the variation overview.

The settings of the variations are edited in the same way as <<item/managin-items#170, Default variations>>. However, note the following limitations for multipack variations:

* Deactivate the inheritance function for the sales price and save a price.
* The information shown in the *Stock* tab cannot be edited. Stock is managed for the main variation only.

[#2000]
== Setting up an item bundle

An item bundle consists of multiple products. The bundle price of an item bundle may be lower than the sum of the individual prices. Go to *Item » Edit item* and use the *Bundle* filter to search for bundles.

[#2100]
=== Creating an item bundle

In the *Bundle* tab of a *Default* item, you create an item bundle which consists of multiple components, the basic items. If you add further variations to the opened item, you create a bundle. The bundle's components are displayed in the *Bundle components* tab where they can be edited or deleted.

[.instruction]
Creating an item bundle:

. Go to *Item » Edit item*.
. Click on *New*. +
→ The *New item* tab opens.
. Select the type *Default*.
. Enter a name.
. Enter the content.
. Select a category.
. Carry out additional settings as desired. Pay attention to the information given in <<table-create-default-items>>.
. *Save* the settings. +
→ The item is created. +
→ The main variation opens in a new tab.
. Open the variation.
. Open the *Bundle » Add variation* tab.
. Place check marks next to the variations you want to add as bundle components.
. Click on *Add variation*. +
→ The components are added to the item bundle and displayed in the *Bundle components* tab.

Then link a sales price with the item bundle and enter a price. Learn how to link sales prices in the <<item/managing-items#240, Linking sales prices>> chapter. When processing the order, only the bundle price and the bundle components are shown. No individual prices are shown.

[NOTE]
.Using an existing item as the bundle item
====
Instead of creating a new bundle item, you can also use an existing item and add bundle components to this item. Note that the bundle item to which bundle components are added must not have stock.
====

[#2200]
=== Editing or deleting bundle components

In the *Bundle components* tab, you can change the quantity of the item bundle's variations, view the variations' net stock and delete bundle components that are no longer required.

[.instruction]
Deleting a bundle component:

. Go to *Item » Edit item*.
. Select *Yes* for the *Bundle* filter.
. Click on *Search*. +
→ All bundle items found are displayed in the overview.
. Open the bundle item.
. Open the variation.
. Open the *Bundle » Bundle components* tab.
. Place check marks next to the bundle components you want to delete.
. Click on *Delete bundle components*. +
→ The bundle components are deleted and no longer available in the item bundle.

[#2300]
=== Creating multiple bundles in one item

Item variations also can be bundles with multiple components. In this way, you can design very complex item bundles that meet your individual needs.

[.subhead]
Example of bundle variations: Let us assume that you want to sell a bundle consisting of a hand towel and a larger bath towel. You also want to offer this bundle in different colours. To do so, the following steps are necessary:

* <<item/managing-items#400, Create an attribute>> with the colours you want to offer, e.g. red and blue.
* <<item/managing-items#20, Create an item>> that will serve as the bundle item, e.g. towel bundle.
* <<item/managing-items#160, Create variations>> of the bundle item and link the attribute values.
* Create items for the bundle components, e.g. hand towel and bath towel.
* Create variations of the bundle components, e.g. red hand towel, blue hand towel etc.
* Add the <<item/managing-items#930, bundle components>> to the variations of the item bundle.

In doing so, you can sell the item *towel bundle* in your online store and offer the bundle colours *red* and *blue*.

[#2400]
=== Setting the stock of item bundles

The stock of a bundle depends on the bundle component with the lowest stock. The stock of this bundle component is displayed in the *Net stock* column of the item overview in the *Item » Edit item* menu. The bundle item itself must not have stock. In the *Stock* tab of a bundle component, you manage the stock, book incoming items, make stock corrections and view supplies as well as item movements. For further information, refer to the <<stock-management#, Stock management>> page of the manual.


[#3000]
== Setting up a set (not sellable)

[#3100]
=== Creating a Set item

[WARNING]
.Set items can not be rendered in the online store
====
You can create *Set* items. However, currently set items can not be rendered in the online store. As such, you cannot select the option *Active* for *Set* items.
====

An item set consists of several items. When you offer *Set* items, your customers can choose one of the variations of the items to make an individual set. In contrast to item bundles, when you offer sets, customers can select one of several variations for each product added to the Set item. Go to *Item » Edit item* and use the *Type* filter to search for sets.

[#3200]
=== Preparing the set components

First, create a <<item/managing-items#880, sales price>> of the type *Set price*. Link this sales price to the variations of those *Default* items that you want to add to a set. Save a price for this sales price.

[#3300]
=== Creating a Set item

Just like when you create *Default* items, a main variation is always created when a new Set item is created. This main variation is linked permanently to the *Set* item and can only be created or deleted together with the item. However, unlike the main variations of *Default* items, the main variation of *Set* items is completely virtual. As such, the main variation of a set is not equivalent to a physical product. The main variations of *Set* items only serves as a data container. This container allows you to add set components and manage the settings for the set that is created from the sum of the individual components.

[.instruction]
Creating a Set item:

. Go to *Item » Edit item*.
. Click on *New*. +
→ The *New item* tab opens.
. Select the type *Set*.
. Carry out the additional settings. Pay attention to the information given in <<table-create-set-items>>.
. *Save* the settings. +
→ The *Set* item is created. +
→ The main variation opens in a new tab.

[TIP]
.Displaying new *Set* items in the item overview
====
The new *Set* item is still inactive. In order to display recently created items in the item overview in the *Item » Edit item* menu, select the *ALL* option for the *Active* filter in the search area. Then click on *Search*. Learn how to activate items and variations for the online store in the <<item/managing-items#180, Setting the availability>> chapter.
====

[[table-create-set-items]]
.Creating a Set item
[cols="1,2"]
|====
|Setting |Explanation

2+|*Item data*

|*Type*
|Select the item type *Set*. +
*Default* = Creates a *Default* item with main variation. +
*Set* = Creates a *Set* item.

|*ID*
|The item ID is a unique, consecutive number that is used to identify each item in plentymarkets. If you leave this field empty, plentymarkets automatically assigns the next available ID.

|*Name*
|Enter a name for the set. The name is a mandatory entry. Learn how to change the name in the <<item/managing-items#50, Entering item texts>> chapter.

2+|*Variation » Category link*

|Category selection
|Select the category in which the set is to be published. Alternatively, click on *New category* to create a new category.
|====

[#3400]
=== Editing Set items

Now that you have created the *Set* item, you can refine the settings for the set.

[.instruction]
Editing Set items:

. Go to *Item » Edit item*.
. Open the *Set* item.
. Carry out the settings. Pay attention to the information given in <<table-edit-set-items>>.
. *Save* the settings.

[[table-edit-set-items]]
.Editing Set items
[cols="1,2"]
|====
|Setting |Explanation

2+|*Tab: Global*

|*Tags*
|Add tags for the item. Learn how to use tags in the <<item/managing-items#150, Adding tags to items>> chapter.

|*Revenue account*
|Enter the revenue account. For further information about the revenue account, refer to the <<order-processing/orders/accounting#90, Accounting>> page of the manual.

|*Age rating*
|Select the age rating for the *Set* item. Select this age rating based on the variation of the set with the highest age rating. Items with an *18+* age rating must be linked to a <<order-processing/fulfilment/preparing-the-shipment#1000, shipping profile>> for which the *PostIdent* option was activated.

|*Coupon*
|Select whether coupons should be *permitted* or *not permitted* for the set, or if the set is *purchasable with coupons only*. For further information about coupons, refer to the <<order-processing/orders/coupons#, Coupons>> page of the manual.

|*Shipping package*
|Use a shipping package. Shipping packages have specific dimensions. If you enter the item's dimensions in the *Settings* tab of the *Set* item, the correct shipping package will be assigned automatically. For further information about setting up shipping packages, refer to the <<order-processing/fulfilment/preparing-the-shipment#1900, Shipping packages>> page of the manual.

|*Serial number*
|Use serial numbers to uniquely identify every single set sold. Serial numbers ensure traceability of items in case of errors or problems. Learn how to set up serial numbers in the <<item/managing-items#820, Using serial numbers>> chapter.

|*Shipping profiles*
|Activate one, multiple or *ALL* <<order-processing/fulfilment/preparing-the-shipment#1000, shipping profiles>>. No shipping profile is selected by default. Activate at least one shipping profile. Otherwise the shipping costs may not be calculated correctly. If an order contains items for which no shipping profile was activated, then the items will be given the default shipping profile of the default online store. If no default shipping profile was specified, then the shipping profile with the highest priority will be used.

|*Store special*
|Select a store special or select *none*. Sets can be displayed as store specials in the online store. Learn how to enable store specials in the <<item/managing-items#1010, Setting up store specials>> chapter of the manual. +
*Special offer* = To display a list of special offers. +
*New item* = To display a list of the latest items. +
*Top item* = To display a list of the best selling items.

|*Item feedback*
|Enter a number between *1* and *5* or *1* and *10* for the initial set feedback. When using the item feedback function, the entered number will be displayed as the initial feedback of a set. Every time new feedback is submitted, an average value will be calculated automatically from these numbers. Go to *System » Client » Settings » Feedback » Tab: Item* to change the *Maximum rating* for feedbacks.

|*Item image*
|Click on the image to open the *Images* tab.

2+|*Tab: Set*

|*Tab: Settings* +
*Tab: Add items*
|<<item/managing-items#900, Add>>, <<item/managing-items#910, edit>> and <<item/managing-items#940, delete>> items.

2+|*Tab: Variation ID*

|*Tab: Settings*
|Settings are equivalent to those for *Default* items, see <<item/managing-items#230, Setting a variation's availability>> and <<item/managing-items#250, Linking barcodes>>. Click on the image to open the *Images* tab.

|*Tab: Categories*
|Settings are equivalent to those for *Default* items, see <<item/managing-items#300, Linking additional categories>>.

|*Tab: Availability*
|In the *Available* column, place a check mark for those clients where you want to offer the set.

2+|*Tab: Texts*

|Texts
|Settings are equivalent to those for *Default* items, see <<item/managing-items#50, Entering item texts>>.

2+|*Tab: Images*

|Images
|Upload images of the set. In the online store, the images of the variations of the set are also displayed. Additional settings are equivalent to those for *Default* items, see <<item/managing-items#90, Uploading item images>>.

2+|*Tab: Media*

|Media
|Settings are equivalent to those for *Default* items, see <<item/managing-items#110, Making files available to be downloaded>>.
|====

[#3500]
=== Adding components to the set

Now add the *Default* items to the Set item that you want to offer as a set. If you add an item with more than one variation, customers can select one of these variations as a set component in the online store. For items with a main variation only, i.e. items without additional variations, customers can not make a selection. Instead, they simply add the main variation to the set.

[.instruction]
Adding components to the Set item:

. Go to *Item » Edit item*.
. Open the set item.
. Click on the *Set* tab.
. Click on the *Add item(s)* tab. +
→ The items are listed.
. Select the items you want to add to the set.
. *Save* the settings. +
→ The items are added to the Set item.

[#3600]
=== Changing the quantity for a set component

The components of a set item are listed in the *Set » Settings* tab. In the *Quantity* tab, you enter how many copies of the selected variation of an item are to be part of the set. The default quantity is *1*.

[.instruction]
Changing the quantity for a set component:

. Go to *Item » Edit item*.
. Open the set item.
. Click on the *Set* tab.
. Click on the *Settings* tab. +
→ The set components are listed.
. Enter the quantity in the *Quantity* column.
. *Save* the settings. +
→ The quantity is updated.

[#3700]
=== Setting discounts for set items

By default, the price of an item set is equivalent to the sum of the individual prices of all set components. However, you can offer a discount in % on the total price of the set.

[.instruction]
Setting discounts for set items:

. Go to *Item » Edit item*.
. Open the set item.
. Click on the *Set* tab.
. Click on the *Settings* tab. +
→ The set components are listed.
. In the *Discount* field, enter the discount in percent you want to offer on the total set price.
. *Save* the settings. +
→ The discount is applied.

[#3800]
=== Stock of Set items

The stock of a set depends on the set's variation with the lowest stock. The stock of this variation is displayed in the *Net stock* column of the item overview in the *Item » Edit item* menu. You can not manage any stock information for the *Set* item itself. Instead, stock is managed in the *Stock* tab of the set components. For further information, refer to the <<stock-management#, Stock management>> page of the manual.

[#3900]
=== Removing set components

Proceed as described below to remove components from the set item.

[.instruction]
Removing set components:

. Go to *Item » Edit item*.
. Open the set item.
. Click on the *Set* tab.
. Click on the *Settings* tab. +
→ The set components are listed.
. Place check marks next to the items you want to remove from the set item.
. Click on *Delete set components*. +
→ The items are removed from the set item.
