= Manually creating items
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Cross-selling, manufacturers, barcodes
:description: Learn how to create and manage items in plentymarkets.
:position: 25
:url: item/managing-items
:id: ZVYHQWL

Once you've configured all of the <<item/settings#, preparatory settings>> in plentymarkets, you'll be ready to start entering items into plentymarkets. This page shows you how to <<item/managing-items#20, manually create an item>>.

But it's also possible to import item and variation data with <<basics/assistants#, assistants>> or to send product data back and forth between your own plentymarkets system and other, external systems. For example, item data records can be:

* imported from existing <<markets/ebay/ebay-setup#11000, eBay listings>>.
* managed in CSV files and imported with <<data/importing-data/ElasticSync#, ElasticSync>>.
* imported from external systems with the <<basics/admin-tasks/rest-api#, REST-API>>.
* exported out of plentymarkets with the <<data/exporting-data/FormatDesigner#, FormatDesigner>>.

[#20]
== Creating Default items

The categories you created allow you to organise your products. When creating a new **Default** item, the first variation of this item is created automatically. This variation is the main variation. It is linked permanently to the **Default** item. The main variation can not be created or deleted without creating or deleting the default item. Now create a new default item.

[.instruction]
Creating Default items:

. Go to *Item » Edit item*.
. Click on *New*. +
→ The *New item* tab opens.
. Select the type *Default*.
. Enter a name.
. Enter the content.
. Select a category.
. *_Optional:_* Carry out the additional settings. Pay attention to the information given in <<table-create-default-items>>.
. *Save* the settings. +
→ The *Default* item and its main variation are created. +
→ The main variation of the item opens in a new tab.
*_Note:_* New items and changes to item data are not available in the online store and exports immediately. +
*_Tip:_* Open a preview of the item:
  .. Click on the preview icon in the save bar of the item. +
  → The *Client (store)* window is displayed. +
  .. From the drop-down list *Plugin set*, select the plugin set in which you want to preview the item or variation.
  .. From the drop-down list *Client (Store)*, select the client in which you want to preview the item or variation. +
  *_Tip:_* These settings are preselected next time you click on the preview icon.
  .. Click on *Execute*. +
  → A preview of the item is shown.

Alternatively, create a new *Default* item by clicking on the arrow next to a <<item/settings/categories#, category>> in the *Item » Categories* menu. In the context menu, click on *Create new item*.

[TIP]
.Displaying new **Default** items in the item overview
====
The new **Default** item is still inactive. In order to display recently created items in the item overview in the **Item » Edit item** menu, select the **ALL** option for the **Active** filter in the search area and click on **Search**. Learn how to activate your items and variations for the online store in the <<item/managing-items#180, Setting the availability>> chapter.
====

[[table-create-default-items]]
.Creating Default items
[cols="1,2"]
|====
|Setting |Explanation

2+|*Item data*

|*Type*
|Select the item type *Default*. +
*Default* = Creates an item with main variation. +
*Multipack* = Creates a <<item/combining-products#1000, Multipack>> item. +
*Set* = Creates a <<item/combining-products#3000, Set>> item. Set items can not currently be rendered in the online store. As such, creating set items is not recommended at this point in time.

|**ID**
|The item ID is a unique, consecutive number that is used to identify each item in plentymarkets. If you leave this field empty, plentymarkets automatically assigns the next available ID.

|**Manufacturer**
|Select the manufacturer. Learn how to create and link manufacturers in the <<item/settings/manufacturers#, Managing manufacturers>> chapter.

|**Name**
|Enter the item name. The item name is a mandatory entry. Learn how to change the item name in the <<item/managing-items#50, Entering item texts>> chapter.

|**Flag**
|Select a flag. Items can be filtered using flags. Learn how to edit and link flags in the chapters <<item/settings/flags#, Setting up flags>> and <<item/managing-items#810, Adding flags to items>>.

|**Stock type**
|Select **Stocked item** (default setting), **Production item**, **Colli** or **Special order item**. +
**Colli** = Select if the item is to be shipped in several packages. For additional packages, individual items with the stock type Colli must be created in plentymarkets, but these items should not be activated for the online store.

2+|*Variation data*

|**Variation name**
|Enter a name for the main variation.

|**Variation no.**
|The variation number is assigned automatically based on the pattern saved in the **Setup » Item » Settings** menu. Variation numbers can be changed subsequently in the **settings** tab of a variation.

|**External variation ID**
|Enter the external variation ID for the main variation of the item. The external variation number is optional. It facilitates importing items and variations from external systems to plentymarkets. External variation IDs can be changed subsequently in the **Settings** tab of a variation.

|**Content**
|By default, a quantity of *1* and the unit *Pieces* are preselected. Make changes to the settings as needed. The content is a mandatory entry. Learn how to create and edit units in the <<item/settings/units#, Managing units>> chapter.

|**Attributes**
|Select attributes for the main variation. If attributes are selected for the main variation, these selected attributes will be available for all additional variations of the item. If a **Default** item is created without selecting attributes for the main variation, then it will be possible to select all of the attributes that are available in the system when you <<item/managing-items#160, create variations>> later. Once you have created a variation with attributes, it will only be possible to create additional variations of the item with these attributes or without any attributes.

|**Sales prices**
|Link <<item/settings/prices#, sales prices>> and enter values for the linked prices.
|====

[#30]
== Editing Default items

A **default item** consists of global settings and data of the main variation. Additional variations can be created. Find out more about editing items and managing data that applies to all variations of the item in this chapter.

=== Personalising item details shown in item tabs

By default, the item ID is shown as the tab title of items. Instead of showing the item ID in the tab, you can display the name or the number of the item’s main variation. Proceed as described below to select different item data to be displayed in the tab title.

[.instruction]
Personalising item details shown in item tabs:

. Go to *Item » Edit item*.
. Open an item. +
→ The *Settings* tab of the main variation opens.
. Point your cursor over the item tab.
. Right-click your mouse. +
→ A drop-down list opens.
. Click on *Rename*. +
→ The *Select tab title* window opens.
. Select the item data to show as the tab title of the item. You can select to show the *Item ID*, the *Variation name of the main variation* or the *Variation number of the main variation*.
. Click on **Rename**. +
→ The selected item data is shown as tab titles for all items. +
→ If you select the setting *Variation name of the main variation* or *Variation number of the main variation* and this information is not saved for an item, the *Item ID* is shown instead. +
**__Tipp:__** The tab title of the item that currently is open only changes after you reload the item.

[#40]
=== Editing item data

In the **Global** tab, you edit the **Default** item's data and change the item's settings. Global settings apply to all variations of the **Default** item. Here, you select the **Default** item's condition and the <<item/settings/manufacturers#, manufacturer>>. Furthermore, you activate <<fulfilment/preparing-the-shipment#1000, shipping profiles>> and <<item/managing-items#1010, store specials>> for the **Default** item.

[TIP]
.Changes not visible immediately
====
New items and changes to item data are not available in the online store and exports immediately. Find out how to check the status of item data on the <<item/checking-data-status#, Checking status of item data>> page of the manual.
====

[.instruction]
Editing item data:

. Go to **Item » Edit item**.
. Click on **Edit item** in the line of an item. +
→ The item's **Global** tab opens.
. Carry out the settings as desired. Pay attention to the information given in <<table-global-item-settings>>.
. **Save** the settings. +
*_Note:_* New items and changes to item data are not available in the online store and exports immediately. +
*_Tip:_* Open a preview of the item:
 .. Click on the preview icon in the save bar of the item. +
 → The *Client (store)* window is displayed. +
 .. From the drop-down list *Plugin set*, select the plugin set in which you want to preview the item or variation.
 .. From the drop-down list *Client (Store)*, select the client in which you want to preview the item or variation. +
 *_Tip:_* These settings are preselected next time you click on the preview icon.
 .. Click on *Execute*. +
 → A preview of the item is shown.

[[table-global-item-settings]]
.Changing the global settings of an item
[cols="1,2"]
|====
|Setting |Explanation

2+|*Basic settings*

|*Condition*; +
*Condition for API*
|Select the item's condition. **New** is set by default. The *Condition for API* setting is used for the market <<markets/amazon#, Amazon>>.

|**Stock type**
|Select **Stocked item** (default setting), **Production item**, **Colli** or **Special order item**. +
**Colli** = Select if a **Default** item is to be shipped in several packages. For additional packages, individual **Default** items with the stock type Colli must be created in plentymarkets, but these items should not be activated for the online store.

|**Manufacturer**
|Select the manufacturer. Learn how to create and edit manufacturers in the <<item/settings/manufacturers#, Managing manufacturers>> chapter.

|**Manufacturing country**
|Select the country in which the **Default** item was manufactured.

|**Customs tariff number**
|Enter the customs tariff number. For further information, for example refer to the website link:http://auskunft.ezt-online.de/ezto/Welcome.do[EZT-Online^] (in German).

|**Revenue account**
|Enter the revenue account. For further information about revenue accounts, refer to the <<orders/accounting#90, Accounting>> page of the manual.

|*Max. order quantity*
|Enter a value to limit the total quantity of all variations of the item that customers can order in one order. +
0 = For each variation, the *Max. order quantity* that was saved in the variation’s *Settings* tab is applied. +
Value greater 0 = Customers can order no more that this quantity of all variations of the item in one order. Decimal values are possible to allow orders by weight or length. This value takes priority over the maximum order quantity of the individual variations of the item.

|**Age rating**
|Select the age rating for the **Default** item. Items with an **18+** age rating must be linked to a <<fulfilment/preparing-the-shipment#1000, shipping profile>> for which the **PostIdent** option was activated.

|*Promotional coupons/POS discount*
|*Permitted* = Customers can redeem promotional codes when they buy a variation of this item. POS users can apply discounts to the item in plentymarkets POS. Customer class discounts are applied automatically. +
*Not permitted* = Customers cannot redeem promotional codes when they buy a variation of this item. POS users cannot apply any discounts to the item in plentymarkets POS. Customer class discounts are not applied. +
*Purchasable with coupon only* = Customers can only buy the variations of this item if they enter the code of a promotional coupon. +
For further information about promotional coupons, refer to the <<orders/coupons#, Coupons>> page of the manual.

|**Subscription**
|Select whether a subscription is available for the **Default** item. Subscriptions are set up in the scheduler. The scheduler is an individual module in plentymarkets that allows an item to be shipped in regular intervals. The scheduler menu will be visible in plentymarkets after **link:https://www.plentymarkets.co.uk/prices/[booking the module]**. For further information about setting up subscriptions, refer to the <<orders/scheduler#scheduled-orders, Scheduled orders>> page of the manual.

|**Shipping package**
|Use a shipping package. Shipping packages have specific dimensions. If you enter the item's dimensions in the **Settings** tab of a variation, the correct shipping package will be assigned automatically. For further information about setting up shipping packages, refer to the <<fulfilment/preparing-the-shipment#1900, Shipping packages>> page of the manual.

|**Serial number**
|Use serial numbers to uniquely identify every single item sold. Serial numbers ensure traceability of items in case of errors or problems. Learn how to set up serial numbers in the <<item/managing-items#820, Using serial numbers>> chapter.

2+|*Shipping profiles*

|**Shipping profiles**
|Activate one, multiple or **ALL** <<fulfilment/preparing-the-shipment#1000, shipping profiles>>. No shipping profile is selected by default. Activate at least one shipping profile per item. Otherwise the shipping costs may not be calculated correctly. If an order contains items for which no shipping profile was activated, then the items will be given the default shipping profile of the default online store. If no default shipping profile was specified, then the shipping profile with the highest priority will be used.

2+|*Online store*

|*Store special*
|Select a store special or select *none*. Items can be displayed as store specials in the online store. Learn how to set up store specials in the <<item/managing-items#1010, Displaying items as top items>> chapter of the manual. +
*Special offer* = To display a list of special offers. +
*New item* = To display a list of the latest items. +
*Top item* = To display a list of the best selling items.

|**Item feedback**
|Enter a number between **1** and **5** or **1** and **10** for the initial item feedback. When using the item feedback function, the entered number will be displayed as the initial feedback of an item. Every time new feedback is submitted, an average value will be calculated automatically from these numbers. Go to **Setup » Client » Settings » Feedback » Tab: Item** to set the **Maximum rating** for feedbacks.

2+|*Item image*

|**Item image**
|Click on the image to open the **Images** tab.
|====


[#610]
=== Linking manufacturers

Link manufacturers either when <<item/managing-items#20, creating a Default item>> or in the existing **Default** item's **Global** tab.

[.instruction]
Linking manufacturers:

. Go to **Item » Edit item**.
. Click on **Edit item** in the line of a **Default** item. +
→ The **Default** item's **Global** tab opens.
. In the **Basic settings** area, select the **manufacturer** from the drop-down list.
. **Save** the settings. +
→ The manufacturer is linked with the **Default** item.

[#45]
=== Changing a Default item's settings for markets

In the **Multi-Channel** tab, change the settings for the markets <<markets/amazon/amazon-setup#, Amazon>>, <<markets/ebay/ebay-setup#, eBay>> and <<markets/neckermann/neckermann-at-setup#, Neckermann.at>>. Furthermore, link your categories to the categories of markets. The settings in this area are for the topic <<markets#, Multi-Channel>> and are described on the markets' pages.

[IMPORTANT]
.Markets: Default items only
====
You can only offer **Default** items on markets. **Set** items can not be transferred to markets.
====

[#50]
=== Entering item texts

Enter your item texts in the **Texts** tab. In addition to the preview text, you can also enter a description and additional text, for example technical data and keywords.

[.instruction]
Entering item texts:

. Go to **Item » Edit item**.
. Open the item.
. Click on the **Texts** tab.
. Select the language.
. Enter the item texts. Pay attention to the information given in <<table-enter-item-texts>>.
. **Save** the settings.

[[table-enter-item-texts]]
.Entering item texts
[cols="1,2"]
|====
|Setting |Explanation

|**Language**
|Select the language under **Open language** to enter the item texts in the selected language. The same language is automatically selected under **Save language**. In order to use the texts of one language in another language, select a different language under **Save language**.

|**Delete language texts**
|Delete the texts of the language selected under **Open language**. All text fields are emptied.

|**Name 1; +
Name 2; +
Name 3**
|Enter the item's name. +
**Name 1** = Default name of the item displayed in the online store and, in case of **Default** items, used for markets. +
**Name 2**; **3** = Alternative item name that can be used for example for markets. +
The maximum length of the item name is 240 characters. The item name is also used for structuring the item URL.  

|**Preview text**
|Enter the preview text. The preview text is a short text which can be displayed in item lists. The preview text can be entered in HTML format or as plain text.

|**Item text**
|Enter the item text. The item text is a detailed description displayed in the item layout in the online store.

|**Technical data**
|Enter the item's technical data.

|**URL path**
|The item's URL path in the online store. By default, the URL path consists of the categories and the item name. The path will be assigned automatically by plentymarkets when the item is created and will be displayed as part of the URL when the item is selected in the online store.

|**Meta description**
|Enter a description which is used when searching for the item with search engines (max. 350 characters).

|**Meta keywords**
|Enter keywords to improve search engine performance.

|**Item template**
|Select a template to alter the design of the detail view of an item. Learn how to create and link item templates in the <<item/managing-items#720, Managing item templates>> chapter.
|====

[#60]
=== Searching and replacing item texts

In the **Search &amp; replace** menu, you search for item texts in the database and replace the results with new texts.

[.instruction]
Searching and replacing item texts:

. Go to **Item » Search &amp; replace**.
. Select the database field.
. Enter the text into the search field. The field is case-sensitive.
. Enter the new text into **Replace by** field.
. Click on **Search**. +
→ The number of relevant items is displayed.
. Click on **Replace all**. +
→ All texts are replaced by the new texts.

[#70]
=== Activate free text fields

Add free text fields to the detailed view of a **Default** item. Customers can then enter values into the free text fields, such as an additional request or dimensions. First, define the free text fields.

[.instruction]
Defining free text fields:

. Go to **Setup » Item » Free text fields**.
. Enter a field name.
. Select the data type. Pay attention to the information given in <<table-define-free-text-fields>>.
. Enter the number of characters.
. **Save** the settings.

[[table-define-free-text-fields]]
.Defining free text fields
[cols="1,2"]
|====
|Setting |Explanation

|**Field name**
|Enter a name for free text field. The field name must not contain special characters. If the field name of a free text field is changed, its content will not be deleted automatically. The field's content must be changed manually or with the help of a CSV file.

|**Data type**
|Select the data type. +
**Small number** = For numerical values between 0 and ± 127. +
**Number** = For numerical values between 0 and ± 2147483647. +
**Character string** = For alphanumerical values with a maximum length of 142 characters. +
**Text** = For text entries with a maximum length of 65535 characters. +
**Checkbox** = GUI element for activating and deactivating functions.

|**Character length**
|Enter the maximum number of characters. The character length is especially important for character strings. With a greater character length, the search for values in this data field will be slower. You should not simply enter the maximum available character length, but rather a realistic length. This will help you save database resources.
|====

After defining free text fields, activate them in the **Fields** tab of a **Default** item.

[.instruction]
Activating free text fields:

. Go to **Item » Edit item**.
. Open the **Default** item.
. Click on the **Fields** tab.
. Enter the values into the required free text fields.
. **Save** the settings.

[#80]
=== Activating characteristics

<<item/settings/properties#100, Characteristics are features of an item>> that are activated in the **Characteristics** tab. Link any number of characteristics with a **Default** item. Customers can search for characteristics in the online store by using the linked characteristics.


[.instruction]
Linking a characteristic to a Default item:

. Go to **Item » Edit item**.
. Open the **Default** item.
. Click on the **Characteristics** tab.
. Activate properties in the **Activate further characteristics** area.
. **Save** the settings. +
→ The characteristics are displayed in the **Characteristics** area.
. *_Optional:_* Carry out the additional settings. Pay attention to the information given in <<table-link-properties>>.
. **Save** the settings.

[[table-link-properties]]
.Linking a characteristic to a Default item
[cols="1,2"]
|====
|Setting |Explanation

|**Name**
|The characteristic group and the name of the characteristic are displayed here. If a characteristic is not assigned to a characteristic group, then only the name of the characteristic will be displayed.

|**Type**
|Type of the characteristic.

|**Default language**
|Enter a value which is assigned to the characteristic. The characteristic value is either set by default or must be entered here. Characteristic values are displayed in the detailed view of an item in the online store.

|Language selection
|Select a language to enter a translation for the value. You can only enter details for characteristics of the type **Text**. The default language is displayed for editing by default.

|**Cross-selling**
|Activate to enable cross-selling between this **default** item and other **default** items with the same characteristic and characteristic value.

|**Surcharge**
|If a surcharge was entered for the characteristic or characteristic value, this surcharge is displayed here.
|====


[#90]
=== Uploading item images

Upload your item images in the item's **Images** tab. The file formats **PNG**, **JPG**, **GIF** and **SVG** are supported for images.

[NOTE]
.Valid characters for file names
====
The following characters are supported for image file names:

* Letters (a-z, A-Z) excluding umlauts
* Numbers (0-9)
* Underscores (_)
* Hyphens (-)

Spaces and special characters are not permitted. When you upload images, spaces and special characters are replaced by hyphens (-).
====

Drag and drop new images into the **Insert a new image** area or upload images as described below.

[.instruction]
Uploading an item image:

. Go to **Item » Edit item**.
. Open the item.
. Click on the **Images** tab.
. Click on **Select files**.
. Select the file that you would like to upload.
. Click on **Open**. +
→ The file is uploaded and displayed in the overview.
. Carry out the optional settings as desired. Pay attention to the information given in <<table-upload-item-image>>.
. **Save** the settings. +
→ The image is uploaded and can be linked with the item's variations.

[[table-upload-item-image]]
.Uploading an item image
[cols="1,2"]
|====
|Setting |Explanation

|**Position**
|Enter the image's position number. The position is used for sorting images in the online store.

|**Availability**
|Option can only be selected for **Default** items. Activate markets to enable the image export to and the visibility for <<markets#, markets>>.

|**Market attribute link**
|Select an attribute value to link the item image to the attribute value for markets. The image will only be transferred to markets for variations with this attribute value. +
__**Note:**__ Option is only shown if the image is linked with at least one variation.

|**Alternative text; +
Name**
|*_Optional:_* The entries for alternative text and name are optional. Entries in both fields help search engines index the item. Use appropriate keywords in the image names to make the images more relevant to search engines. This also increases traffic on the page, for example if the image is found with the Google image search.

|**Size**
|Displays the image size in pixels and kilo bytes.
|====

[IMPORTANT]
.Item image size
====
Every time an item image is uploaded, plentymarkets creates the following versions:

* High-resolution item image
* Medium-sized item image
* Item attribute image
* Two preview images

Since plentymarkets does not scale up images, the source image must have at least the size and quality specified in the <<item/managing-items#670, Sizes>> area. Larger images will be scaled down to the specified size.
====

Use an FTP server to upload several images at the same time. For further information, refer to <<item/settings/images#600, Uploading item images via FTP server>>.

[#100]
=== Activating cross-selling

In the **Cross-selling** tab, create relations between a **Default** item and any number of similar items of your product range. Learn how to set up cross-selling in the <<item/managing-items#950, Setting up cross-selling>> chapter.

[#110]
=== Making files available to be downloaded

NOTE: Files uploaded to the *Media* tab cannot be used in the Ceres online store.

In the *Media* tab, you can upload files for your items. Files, e.g. product information or data sheets, can be made available in the **My account** area or in the detailed view of an item in the online store. Files that are uploaded in the **Media** tab must meet the following requirements:

* Old online store Callisto
* *Permitted file formats:* PDF, EXCEL, X_EXCEL, DOC, DOCX, MSWORD, RTF, TEXT, RICHTEXT, ZIP, HTML, SWF
* *Maximum file size:* 10 MB per file
* *Maximum number of files:* 10 files per item (of which a maximum of 1 file in SWF format)

[#120]
==== Uploading files

Proceed as described below to upload files in the *Media* tab. Then decide where the files should be available.

[.instruction]
Uploading a file:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Media* tab.
. Click on *Select files*.
. Select the file that you would like to upload.
. Click on *Open*. +
icon:map-signs[] *_Or:_* Drag and drop new files into the *Insert a new document* area. +
→ The file is uploaded and displayed in the overview.
. Carry out the settings. Pay attention to the explanations given in <<table-upload-file>>.
. *Save* the settings.

[[table-upload-file]]
.Uploading a file
[cols="1,2"]
|====
|Setting |Explanation

|**Title**
|Edit the title, if needed.

|**Size**
|The file size is displayed here.

|**Email**
|This setting does not serve any function.

|**My account**
|Activate to make the file available for download in the **My Account** area.

|**CMS**
|Activate to make the file available in the old online store Callisto.
|====

[#130]
==== Inserting a download link into the online store

Use the template function **GetDocumentLinks()** of the Callisto design to add download links to the files saved in the **Media** tab to the old online store Callisto. These links give customers access to the files that were saved in the **Media** tab. This template function can be used in all templates in the **ItemView** folder. The function returns a list of links that customers can use to download the saved documents.

[.instruction]
Inserting the template function:

. Go to **CMS » Web design**.
. Open a template in the **Layout » ItemView** folder.
. Insert the code example into the template.
. **Save** the settings. +
→ A list of download links is displayed at the respective position in the online store.

[source,plenty]
----
include::assets/EX-EN-GetDocumentLinks.html[]

----
[TIP]
.Tip: Limit the list of download links to specific data types
====
Limit the list of download links to specific data types by specifying a file ending. The template function **GetDocumentLinks(".pdf")**, for example, displays only the download links to saved PDF files.
====

[#140]
=== Displaying item statistics

In the **Statistics** tab, you can create different statistics for the **Default** item. For example, statistics are available that let you analyse the **Default** item's revenue according to various criteria. For further information, refer to the <<basics/working-with-plentymarkets/statistics/managing-statistics#90, Managing statistics>> page of the manual.

[#810]
=== Adding flags to Default items

Add up to two flags to a **Default** item. Learn how to rename flags in the <<item/settings/flags#, Setting up flags>> chapter.

////
[TIP]
.Using tags
====
Flags can only be used for items. Instead of flags, use the more flexible <<item/managing-items#150, tags>> that can be linked to variations.
====
////

[.instruction]
Adding a flag to a Default item:

. Go to **Item » Edit item**.
. Open the **Default** item.
. Click on the greyed out button in the toolbar on the right. +
→ A drop-down list opens.
. Select a flag from the drop-down list.
. **Save** the settings.

[#155]
== Editing multiple items

Edit multiple items with the **Item group function** or the **Batch processing** function in the **Item** menu. The group function edits previously selected items. The batch processing function edits previously filtered items.

[TIP]
.Which method should you use?
====
It will be faster to use the group function or batch processing depending on the number and type of items you want to edit. Use **batch processing** with the **Manufacturer** filter if you only want to edit the items of a certain manufacturer. This way, you can edit all of the items for one manufacturer without having to select every single item. Use the **group function** if the items you wish to edit cannot be grouped with a certain **filter**.
====

[.instruction]
Carrying out the item group function:

. Go to **Item » Edit item**.
. Select the items that you want to edit.
. Click on **Item group function**. +
→ The **Item group function** window opens.
. Carry out the settings. Pay attention to the information given in <<table-edit-multiple-items>>.
. Click on **Execute** to carry out the item settings.

[[table-edit-multiple-items]]
.Editing items with the **Group function** or **Batch processing**
[cols="1,2"]
|====
| Setting | Explanation

2+| *Multi-Channel*

|**Multi-Channel**
|The settings in this area are for the topic <<markets#, Multi-Channel>> and are described on the markets' pages.

2+| *Characteristics*

|**Create link**
|Activate or deactivate the characteristic link. The characteristic link can also be activated for **Cross-selling**.

2+| *Procedures*

|**Delete item**
|Activate to delete items with all their variations.

|**Delete item images**
|Activate to delete all item images of the selected items.

|**Delete second item image**
|Activate to delete the second item image of the selected items.

|**Create listing**
|Activate to create listings for the selected items.

2+| *Shipping*

|**Delete old shipping profiles**
|Activate to delete old shipping profiles.

|**Customs tariff number**
|Activate and enter a number. This number will be saved in the selected items.

|**Manufacturing country**
|Activate and select the country in which the items were manufactured.

|**Shipping configuration**
|Activate one, multiple or **ALL** shipping profiles. Previously activated profiles can be deleted with the **Delete old shipping profiles** setting.

|**Condition**
|Activate and select the item's condition.

2+| *Global*

|**Serial number**
|Activate and select **Yes** to use serial numbers for uniquely identifying every item sold.

|**Item template**
|Activate and select the item template.

|**Manufacturer**
|Activate and select the manufacturer.

|**Flag 1; +
Flag 2**
|Activate and select the flag.

|**Revenue account**
|Activate and enter the revenue account.

2+| *Free text fields*

|**Free text field**
|Activate and enter a value. This value will be saved in the selected items.
|====

[.instruction]
Carrying out batch processing:

. Go to **Item » Batch processing**.
. Select the filters based on <<table-batch-processing-filters>>.
. Carry out the settings. Pay attention to the information given in <<table-edit-multiple-items>>.
. Click on **Apply** to apply the settings to the items.

[[table-batch-processing-filters]]
.Filter options for **batch processing**
[cols="1,2"]
|====
| Setting | Explanation

|**Item ID**
| Select the operator and enter one or more item IDs to search for items with this ID. Use commas to separate multiple item IDs.

|**Flag 1; +
Flag 2**
| Select a flag to only edit items that have this flag.

|**Manufacturers**
| Select a manufacturer or **ALL** to only edit items of the selected manufacturer.

|**Condition**
|Select the condition to only edit items that have this condition.

|**Without category**
|Activate to only edit items that are not linked with a category. In previous plentymarkets versions, it was possible to create items without linking a category.

|**Categories**
|Select the category to only edit items with this category.
|====

[#160]
== Creating variations

A main variation is always created when a new **Default** item is created. The main variation is linked permanently to the **Default** item. It cannot be deleted. Information saved for the main variation, such as sales prices and availability, is passed on to item variations. However, you can change the settings of every variation individually. First, learn how to create variations.

[.instruction]
Creating variations:

. Go to **Item » Edit item**.
. Open the **Default** item.
. Open the **Variations** tab.
. Click on **New**. +
→ The **Create new variations** window opens.
. Enter the content.
. Select one or multiple attributes. +
→ The number of **combinations** is displayed in the bottom right corner. This number of variations will be created.
. Click on **Create variations**. +
→ The variations is created and displayed in the variation overview. +
*_Note:_* New variations and changes to variation data are not available in the online store and exports immediately. +
*_Tip:_* Open a preview of the variation:
 .. Click on the preview icon in the save bar of the variation. +
 → The *Client (store)* window is displayed. +
 .. From the drop-down list *Plugin set*, select the plugin set in which you want to preview the item or variation.
 .. From the drop-down list *Client (Store)*, select the client in which you want to preview the item or variation. +
 *_Tip:_* These settings are preselected next time you click on the preview icon.
 .. Click on *Execute*. +
 → A preview of the variation is shown.

[TIP]
.Selecting attributes for variations
====
If you select attributes for the main variation, the selected attributes will be available for all additional variations of the item. If you create an item without selecting attributes for the main variation, then it will be possible to select all of the attributes that are available in the system when you create variations later. Once you have created a variation with attributes, it will only be possible to create additional variations of the item with these attributes or without any attributes.

If you delete all variations of an item where the main variation has no attributes, then it will be possible to select all of the attributes that are available in the system when creating new variations. Therefore, you only have to delete the variations of an item without deleting the item itself, in order to make new attributes available for this item. Once you have created variations for an item, attributes can no longer be deleted or added. To delete or add attributes, all variations with attributes must be deleted from the item.
====

[#170]
== Editing variations

Find out how to save and edit variation data.

=== Personalising variation details shown in variation tabs

By default, the variation ID is shown as the tab title of variations. Alternatively, you can display the variation name or the variation number. Proceed as described below to select different variation data to be displayed in the tab title.

[.instruction]
Personalising variation details shown in variation tabs:

. Go to **Item » Edit item**.
. Open an item. +
→ The **Settings** tab of the main variation opens.
. Point your cursor over the variation tab.
. Right-click your mouse. +
→ A drop-down list opens. +
**__Tip:__** If the drop-down list is not shown, switch to the tab of the main variation.
. Click on *Rename*. +
→ The *Select tab title* window opens.
. Select the variation data to show as the tab title of variations. You can select to show the *Variation ID*, the *Variation name* or the *Variation number*.
. Click on **Rename**. +
→ The selected variation data is shown as tab titles for all variations. +
→ If you select the setting *Variation name* or *Variation number* and this information is not saved for a variation, the *Variation ID* is shown instead. +
**__Tip:__** The tab title of the variation that currently is open only changes after you reload the item.

=== Carrying out basic settings for the main variation

Edit variation data in the main variation and pass the modified information on to every variation. By deactivating the inheritance, you can edit every variation individually.

[TIP]
.Changes not visible immediately
====
New variations and changes to variation data are not available in the online store and exports immediately. Find out how to check the status of variation data on the <<item/checking-data-status#, Checking status of item data>> page of the manual.
====

[.instruction]
Carrying out basic settings for the main variation:

. Go to *Item » Edit item*.
. Open the *Default* item. +
→ The *Settings* tab of the main variation opens.
. Carry out the settings in the *Basic settings* area. Pay attention to the information given in <<table-main-variation-basic-settings>>.
. *Save* the settings. +
*_Note:_* New variations and changes to variation data are not available in the online store and exports immediately. +
*_Tip:_* Open a preview of the variation:
  .. Click on the preview icon in the save bar of the variation. +
  → The *Client (store)* window is displayed. +
  .. From the drop-down list *Plugin set*, select the plugin set in which you want to preview the item or variation.
  .. From the drop-down list *Client (Store)*, select the client in which you want to preview the item or variation. +
  *_Tip:_* These settings are preselected next time you click on the preview icon.
  .. Click on *Execute*. +
  → A preview of the variation is shown.

[[table-main-variation-basic-settings]]
.Carrying out basic settings for the main variation
[cols="1,2"]
|====
|Setting |Explanation

|**Variation name**
|Enter a name for the main variation.

|**Variation number**
|The variation number is assigned automatically based on the pattern saved in the **Setup » Item » Settings** menu. Variation numbers can be changed subsequently in the **settings** tab of a variation.

|**External variation ID**
|Enter the external variation ID. The external variation number is optional. It facilitates importing items and variations from external systems to plentymarkets.

|**Model**
|Enter the model of the main variation. The model is passed on to every variation.

|**Position**
|Enter the position number for the variation. Variations are sorted in ascending order by position. +
**__Note:__** If **No** is selected for the setting **Automatically sort by monthly sales** in the **Setup » Client » Select client » Item layouts » Settings** menu, manually entered position numbers will be overwritten automatically.
|====

[#180]
=== Setting the availability

You are legally required to provide information in your online store about how long it takes to deliver all items that you offer. There are ten availability options in plentymarkets.

[#190]
==== Setting the availability options

Set the availability in the tab of a variation. Enter the texts for availability options in the plentymarkets back end. You can also replace the default availability icons with your own icons.

[.instruction]
Setting the availability options:

. Go to **Setup » Item » Availability**.
. Carry out the settings. Pay attention to the information given in <<table-set-availability>>.
. **Save** the settings.

[[table-set-availability]]
.Setting the availability options
[cols="1,2"]
|====
|Setting |Explanation

|**Back end icon**
|The default availability icons of the system are displayed here. These icons are set by default and can be replaced with individual icons.

|**Name**
|Enter a name or description for the delivery period.

|**Language**
|Select the language from the drop-down list. The system language that was set when the system was first created is selected by default.

|**Average delivery period**
|Enter the average delivery time in days. These values are analysed by search engines. Enter realistic values for the average delivery period. Customers will interpret this information as a guarantee. In addition, it can be relevant to competition law.

|**Upload store icon**
|Upload an individual availability icon. The icon is displayed in the online store instead of the back end icon. +
Available file formats: **PNG**, **JPG** and **GIF**. Ideal image size: **16 x 16 pixels**.

|**Delete store icon**
|Delete the individual availability icon. After deleting this icon, the back end icon is displayed in the online store.
|====

[#200]
==== Old online store: Displaying the availability in Callisto

By default, the availability in the design Callisto is displayed in the online store using the <<online-store/online-store/cms-syntax#web-design-itemview-container-itemviewsingleitem, ItemViewSingleItem>> template. Use the template variables **$AvailabilityString** and **$AvailabilityIcon** to display the availability text and icon in the online store. By default, these template variables are included in the template **ItemViewSingleItem** of the plentymarkets default design.

[IMPORTANT]
.Availability is not displayed correctly in the online store
====
If you use your own store icons for the availability, upload files for all availability options. Otherwise, an empty frame will be displayed in the design when the icon is missing. +
If the availability is not displayed correctly in the online store after changes were made, then delete the browser cache and reload the page.
====

[#220]
==== Deactivating availability options in the online store

By default, all availability options are activated and visible in the online store. Only products with an active availability option can be ordered in the online store. If you want to exclude products with a specific availability from your online store, deactivate this availability option. Products with a deactivated availability option are still available for markets. Proceed as described below to activate the availability options for your default online store. Activate the availability options for other clients (stores) in the same way.

[.instruction]
Activating availability options for the online store:

. Go to **Setup » Client » Select client » Item layouts » Availability**.
. Press and hold Ctrl or Cmd and select the availability options.
. **Save** the settings. +
→ The selected availability options are activated for the online store of this client (store).

If a variation's availability was not activated as described, then the variation can not be ordered in the online store. The visibility of the variation in the online store depends on the type of verification selected for the attribute availability in the <<online-store/setting-up-clients/item-layouts#, Setup » Client » Select client » Item layouts » Settings>>.

* If the option **Attribute availability** is set to **Server check**, the variation is visible and can be selected. The availability will not be checked until the last attribute has been selected in the order process.
* If you select the setting **Client check**, the variation either is not shown in the online store or it is greyed out.

[#230]
==== Setting a variation's availability

Set the availability and store visibility of a variation in the **Settings** tab of the variation.

[.instruction]
Setting the main variation's availability:

. Go to **Item » Edit item**.
. Open the item. +
→ The **Settings** tab of the main variation opens.
. Pay attention to the information given in <<table-main-variation-availability>> and carry out the settings in the **Availability** area.
. **Save** the settings.

[[table-main-variation-availability]]
.Setting the main variation's availability
[cols="1,2"]
|====
|Setting |Explanation

|**Active**
|Activate the variation to offer the variation in the online store or, in the case of **Default** items, on markets. Variations will only be displayed in the online store when the variations are active. When searching for items using the default settings, inactive variations will not be shown. Select **No** in the **Active** filter to search for inactive variations.

|**Availability**
|Select the availability. 10 availability levels are available. +
*_Note:_* The availability is a static setting. That means that the availability level selected does not change irrespective of actual stock levels. The setting is relevant only if stock availability is not set automatically.

|*Show in online store:* +
*Available if net stock is positive*; +
*Not available if net stock is 0 or negative*
|Activate to make the variation available if the net stock is positive and unavailable if the net stock is 0 or negative. Both functions complement each other and work in combination with the **To net stock** option under **Limitation**. plentymarkets automatically controls the item's availability in the online store. Variations do not have to be made invisible if no net stock is available.

|*Client:* +
*Automatically visible if net stock is positive*; +
*Automatically invisible if net stock is 0 or negative*
|Activate to automatically make the variation visible in the online store if the net stock is positive and invisible if the net stock is 0 or negative. Both functions complement each other and are only applied if the *Limitation* option is set to *To net stock*. When the options are activated and no net stock is available for the variation, the variation is not visible in the online store. Even the direct URL to the variation does not work.

|*Item list* +
(automation currently only works for Calisto, implementation in Ceres to follow)
|*Always invisible* (previously *Invisible: in item list*) = Activate to make the variations invisible in the item list of the online store. When the option is activated, the variation can only be opened using the direct URL to the variation. The variation is not shown in the categories, search results or item lists, i.e. store specials, cross-selling and last seen items. +
*Automatically visible if net stock is positive*; +
*Invisible automatically if net stock is 0 or negative* = Activate to automatically make the variation visible in the item list if the net stock is positive and invisible if the net stock is 0 or negative. Both functions complement each other and are only applied if the *Limitation* option is set to *To net stock*. When the options are activated and no net stock is available for the variation, the variation can only be opened using the direct URL to the variation. The variation is not shown in the categories, search results or item lists, i.e. store specials, cross-selling and last seen items. +
*_Note:_* The options *Client: Automatically visible if net stock is positive* and *Client: Invisible automatically if net stock is 0 or negative* takes priority. When those options are activated and no net stock is available for the variation, the variation is also not visible in the online store. Even the direct URL to the variation does not work. As such, we recommend that you do not combine these settings and manage the visibility using either the store visibility or the item list visibility.

|**In supply**
|Displays the estimated delivery date of ordered variations. For further information about reorders refer to <<stock-management/managing-reorders/working-with-reorders#, Managing reorders>>.

|**Limitation**
|Select **None**, **To net stock** or **Do not administer stock for this variation**. +
**None** = No limitation to the stock is set. The variation's availability is not checked automatically. +
**To net stock** = Stock is limited to the net stock. The variation's availability is checked automatically. +
**Do not administer stock for this variation** = If this setting is selected, then the tabs **Correction**, **Stock**, **Supply** and **Item movement** will be hidden in the **Stock** tab of a variation.

|**Max. order quantity**
|Enter the maximum order quantity that is permitted per order. Decimal values are possible to allow orders by weight or length. The value **0** is set by default. With the value **0**, the maximum order quantity is unlimited. You can use the maximum order quantity in combination with advance orders, for example to prevent other sellers from completely buying out the variation at a reduced price.

|**Min. order quantity**
|Enter the minimum order quantity. Decimal values are possible to allow orders by weight or length.

|**Interval order qty.**
|Enter which quantity intervals the variation can be ordered in. Decimal values are possible to allow orders by weight or length.

|**Release date**
|Date on which the variation becomes available. The variation can be visible in the online store before this date, e.g. for preorders. Respect the date format (DD.MM.YYYY) when entering the date manually. +
For further information about advance orders, refer to the <<orders/managing-orders#1100, Advance orders>> page of the manual.

|**Available until**
|Use the calendar to select the last date that the variation should be available. Respect the date format (DD.MM.YYYY) when entering the date manually.
|====

==== Setting the availability for clients

In the variation's **Availability** tab, you select the clients (stores) in which you want to offer the variation for sale.

[.instruction]
Making main variation available for a client:

. Go to **Item » Edit item**.
. Open the item. +

. Open the main variation.
. Click on the **Availability** tab.
. Select the clients in the **Client (store)** section.
. **Save** the settings. +
→ The variation is available in the selected clients.

[NOTE]
.Availability/visibility for variations without net stock
====
Whether or not a variation without positive net stock is visible/available for the selected clients depends on the settings for net stock dependency in the **Availability** section of the **Settings** tab. +
If the option **Not available if net stock is 0 or negative** or **Not visible if net stock is 0 or negative** is activated and no net stock is available for the variation, the client selection is greyed out. Click on the lock icon to activate the client selection even if net stock is negative. If you activate the selection and select a client, the settings for availability and/or visibility for negative net stock will be overwritten and the variation will be available in the selected clients. This settings remains valid until new stock is booked for the variation. Once net stock for the variation becomes positive, the availability and visibility settings if net stock is 0 or negative take effect again.
====

[#235]
==== Setting the availability for markets

In the **Availability** tab, you activate <<markets#, markets>> and make changes to the SKU settings.

[#240]
=== Linking sales prices

Link <<item/settings/prices#100, sales prices>> with the main variation of a **Default** item to save prices. You can enter prices or calculate them based on a <<item/settings/prices#500, price calculation>>. If inheritance is active, the combinations of sales price and price of the main variation are passed from the main variation to the variations of the item.

[.instruction]
Linking a sales price with the main variation:

. Go to **Item » Edit item**.
. Open the **Default** item. +
→ The **Settings** tab of the main variation opens.
. Select a sales price from the drop-down list.
. Select whether the price is net or gross.
. Click on **Add**. +
→ The sales price is added and displayed in the list.
. Enter a value into the **Price** field.
. **Save** the settings.

[.instruction]
Linking a sales price with price calculation with the main variation:

. Go to **Item » Edit item**.
. Open the **Default** item. +
→ The **Settings** tab of the main variation opens.
. Select a sales price from the drop-down list.
. Select whether the price is net or gross.
. Select a price calculation from the drop-down list.
. **Save** the variation. +
→ The sales price is linked and a price is calculated. +
**__Tip:__** Reload the tab of the variation to update the price shown.

If you want to maintain individual prices for your variations, deactivate the inheritance in the variation's tab and add a sales price. Click on **Delete** in the line of a sales price of the main variation or variation to delete the price.

[#250]
=== Linking barcodes

Barcodes such as GTIN, ISBN, UPC and QR are used to identify items in plentymarkets. Link <<item/settings/barcodes#, Barcodes>> with your item variations.

[.instruction]
Linking a barcode with the main variation:

. Go to *Item » Edit item*.
. Open the item. +
→ The *Settings* tab of the main variation opens.
. In the *Barcodes* area, select a barcode from the drop-down list.
. Click on *Add*. +
→ The barcode is added and displayed in the list.
. Enter the code into the *Code* field. +
icon:map-signs[] *_Or:_* Click on *Generate GTIN* to insert a code from the <<item/settings/barcodes#200, number range>>.
. *Save* the settings.

[#260]
=== Linking ASIN and ePID

ASIN (Amazon Standard Identification Number) is product identification that is provided by <<markets/amazon/amazon-setup#, Amazon>>. An ePID (eBay Product ID) is a product identification that is provided by <<markets/ebay/ebay-setup#, eBay>>. The ASIN contains 10 characters and/or numbers. For books, the ASIN matches the ISBN. The ASIN can be found on Amazon's product page. The ePID is provided by eBay. Link ASIN and ePID with your variations.

[.instruction]
Linking ASIN or ePID with the main variation:

. Go to **Item » Edit item**.
. Open the **Default** item. +
→ The **Settings** tab of the main variation opens.
. Click on **Add** in the **ASIN/ePID** area. +
→ A new entry is added and displayed in the list.
. Select the country platform from the drop-down list.
. Select **ASIN** or **ePID** from the drop-down list.
. Enter the ASIN or ePID into the field.
. **Save** the settings.

[#270]
=== Specifying item dimensions

In the **Dimensions** area, you specify the length, width and height of a **Default** item. You also define content and weight values.

[.instruction]
Specifying the dimensions of the main variation:

. Go to **Item » Edit item**.
. Open the **Default** item. +
→ The **Settings** tab of the main variation opens.
. Pay attention to the information given in <<table-main-variation-dimensions>> and carry out the settings in the **Dimensions** area.
. **Save** the settings.

[[table-main-variation-dimensions]]
.Specifying the dimensions of the main variation
[cols="1,2"]
|====
|Setting |Explanation

|**Content**
|Enter the content and select the <<item/settings/units#, unit>> from the drop-down list.

|**L x W x H**
|Enter the variation's dimensions in millimetres.

|**Gross weight**
|Enter the variation's gross weight in grams or kilograms. This weight includes the packaging for variations that are packaged separately. The value entered here is used for calculating shipping packages and weight-based shipping costs. +
The gross weight can automatically be calculated for item bundles <<item/combining-products#2500, based on the bundle components>>.

|**Net weight**
|Enter the variation's weight without packaging in grams or kilograms. +
The net weight can automatically be calculated for item bundles <<item/combining-products#2500, based on the bundle components>>.

|**Units contained**
|Units contained describes several sales units combined in one package. Default setting: **1**. +
**__Note:__** This value is currently not considered for calculations. +
Calculation of the unit prices, for example per kilogram, is carried out on the basis of the entry for weight in the section **content** as well as the selected option for **unit** in connection with the **price**. The value you enter for the **Units contained** option will have no impact on the calculation of the unit price.

|*Show unit price*
|Select if the variation's unit price is to be shown in the online store. +
Activated = The variation's unit price is shown in the online store if the necessary logic is implemented in the design. +
Not activated = The variation's unit price is not shown in the online store. +
*_Tipp:_* The unit price is the price based on a standard amount, for example per kg or litre. The unit price allows consumers to compare prices. In some countries, the unit price must be specified for products that are sold by weight, volume, length or surface area.
|====

[#280]
=== Specifying costs

In the **Costs** area, you specify the VAT rate and the variation's purchase price. You also enter additional costs such as costs for transportation and storage. These entries are used for <<item/settings/prices#500, calculating your sales prices>>.

[.instruction]
Specifying the costs of the main variation:

. Go to **Item » Edit item**.
. Open the **Default** item. +
→ The **Settings** tab of the main variation opens.
. Pay attention to the information given in <<table-main-variation-costs>> and carry out the settings in the **Costs** area.
. **Save** the settings.

[[table-main-variation-costs]]
.Specifying the costs of the main variation
[cols="1,2"]
|====
|Setting |Explanation

|**Acquisition price**
|Display the gross or net acquisition price. The acquisition price results from the procurement calculation. It is calculated based on the price requested by the supplier minus discounts and bonuses Plus procurement costs for transportation, insurance and packaging.

|**VAT**
|Select the <<orders/accounting#550, VAT rate>> for the main variation.

|**Net purchase price**
|The net purchase price. The purchase price is calculated or managed manually depending on the settings saved in the *Setup » Stock » Stock » Incoming items* menu. +
The net purchase price is used e.g. in *price calculations*. +
The net purchase price can automatically be calculated for item bundles <<item/combining-products#2500, based on the bundle components>>.

|**Mov. av. purchase price (net)**
|The *net moving average purchase price*. The net moving average purchase price is recalculated every time stock is booked in. The calculation takes into account the purchase prices of all stock of a variation currently in stock. +
**__Note:__** During calculation, only items incoming to those warehouses activated for the moving average purchase price are taken into account. Go to *Setup » Stock » Stock » Incoming items* to activate the warehouses. If no warehouse is active, then no moving average purchase price is calculated. +
The net moving average purchase price can automatically be calculated for item bundles <<item/combining-products#2500, based on the bundle components>>.

|**Net transport**
|Enter the net transportation costs for the variation. This value is used for **price calculations** and for calculating the acquisition price.

|**Net storage costs**
|Enter the net storage costs for the variation.

|**Customs**
|Enter a value in percent for customs.

|**Operating costs**
|Enter a value in percent for operating costs.
|====

[#290]
=== Specifying shipping data

In addition to global shipping information which you activate in the *Global* tab, you specify further data, such as warehouses and surcharges, in the **Shipping** area of the variation.

[.instruction]
Specifying the shipping data of the main variation:

. Go to **Item » Edit item**.
. Open the **Default** item. +
→ The **Settings** tab of the main variation opens.
. Pay attention to the information given in <<table-main-variation-shipping-data>> and carry out the settings in the **Shipping** area.
. **Save** the settings.

[[table-main-variation-shipping-data]]
.Entering the shipping data of the main variation
[cols="1,2"]
|====
|Setting |Explanation

|**Order picking**
|Select **Single order picking possible**, **Single order picking not possible** or **Exclude from pick list** to define the order picking type. If you do not want to define the order picking type, select the empty option.

|**Main warehouse**
|Select the variation's main warehouse.

|**Pallet type**
|Select the pallet type.

|**Packing units**
|Select the number of packing units and the type of packaging if the item consists of multiple packages. +
Select **0** if an item is always to be sent as one package. This setting also applies to various items. This setting also applies to various items. This means that all items of an order that have the value **0** will be packed into one package.

|**Extra charge 1; +
Extra charge 2**
|Enter a value for calculating an extra shipping charge for the 1. and 2. item. For further information, refer to <<fulfilment/preparing-the-shipment#1000, Creating a shipping profile>>.
|====

[#300]
=== Linking additional categories

In the **Categories** tab, you can link additional categories with your variations. The variations will be displayed in all selected categories in the online store. Furthermore, activate the default category of the variation in the area **Default categories**. With the default category, you set the category path in the breadcrumb bar in the online store. If a variation is displayed in multiple categories, the category path of the default category will always appear in the breadcrumb bar.

[.instruction]
Linking additional categories:

. Go to **Item » Edit item**.
. Open the item.
. Open the variation.
. Click on the **Categories** tab.
. Click on **Link category**. +
→ The **Link category** window opens.
. Select a category or subcategory.
. Click on **Link category**. +
→ The category link is created and displayed in the **Linked categories** area.

Category links of the main variation are passed on to variations. You can change the category links for each variation individually. Click on **Deactivate Inheritance** in the **Categories** tab of a variation and change the settings.

[.instruction]
Setting the default category:

. Go to **Item » Edit item**.
. Open the **Default** item.
. Open the variation.
. Click on the **Categories** tab.
. Use the drop-down list to select the appropriate **default category** for the client.
. **Save** the settings. +
→ The default category is set.

[#4800]
=== Linking properties and texts

<<item/settings/properties#500, Properties>> are centrally managed in the *Setup » Settings » Properties » Configuration* menu and can be linked to variations of *Default* items. Properties of the *Item* area are linked to variations in two different tabs of a variation:

* Variation properties of the types *Integer*, *Float*, *Selection*, *Date* and *File* are activated in the *Properties* tab of a variation.
* Variation properties of the types *Short text* and *Text* are linked in the *Texts* tab of the variation.

[NOTE]
.Inheritance of links and values
====
By default, inheritance of variation properties and variation texts is active. All combinations of properties and values that are saved for the main variation in the *Properties* and *Texts* tabs are inherited to those variations of the item for which inheritance is not deactivated. If you want to save individual properties for the variations of an item, deactivate the inheritance in the variation's tab and link properties.
====

[#4900]
==== Linking a variation property and saving a value

Proceed as described below to link a property of the types *Integer*, *Float*, *Selection*, *Date* or *File* to a main variation and save a value for that property.

[.instruction]
Linking a variation property with a main variation:

. Go to *Item » Edit item*.
. Open the *Default* item. +
→ The *Settings* tab of the main variation opens.
. Open the *Properties* tab. +
→ Any variation properties already linked to the variation are shown.
. Click on the *Properties* field. +
→ A drop-down list of available variation properties opens.
. Activate the variation property. +
*_Tip:_* You can link several or all variation properties to the variation at once.
. Click on *Add*. +
→ The variation properties are displayed in the *Properties* area.
. Enter a value for the property. Pay attention to the information given in <<table-link-properties>>.
. *Save* the settings.

[[table-link-properties]]
.Linking a property
[cols="1,2"]
|====
|Setting |Explanation

|*Name*
|Displays the property name.

|*Type*
|Displays the property type. +
*int* = *Integer* +
*float* = *Decimal number* +
*select* = *Selection* +
*date* = *Date* +
*file* = *File* +
*empty* = None

|*Value*
|Enter a value. How you specify a value depends on the property type. +
*int* = Enter an integer. +
*float* = Enter a decimal number. +
*select* = Select an option from the drop-down list. +
*date* = Enter or select a date. +
*file* = Upload a file. +
*empty* = No value can be specified for this type.
|====

[#5000]
==== Linking a text and saving a value

Proceed as described below to link a property of the types *Short text* or *Text* to a main variation and save a value for that property.

[.instruction]
Linking text with a main variation:

. Go to *Item » Edit item*.
. Open the *Default* item. +
→ The *Settings* tab of the main variation opens.
. Click on the *Texts* tab. +
→ Any texts already linked to the variation are shown.
. Click on the *Properties* field. +
→ A drop-down list of available variation properties opens.
. Activate the variation property. +
*_Tip:_* You can link several or all variation properties to the variation at once.
. Click on *Add*. +
→ The variation properties are displayed in the *Texts* area. +
→ The default language is displayed for editing by default.
. Enter a value. Pay attention to the information given in <<table-link-texts>>.
. *Save* the settings.
. Enter the text in additional languages (optional). +
*_Tip:_* Click on *Multilingualism* to open a bilingual editing window.
. *Save* the settings.

[[table-link-texts]]
.Linking texts
[cols="1,2"]
|====
|Setting |Explanation

|*Name*
|Displays the property name.

|*Type*
|Properties of the type *Short text* are shown in the upper part of the tab. Enter a value into the text field. +
Properties of the type *Text* are shown in the lower part of the tab in an editor that provides additional formatting options. +
→ The default language is displayed for editing by default.
|====

[#5010]
==== Deleting link and value

To delete a property link, go to the *Properties* or *Texts* tab of the variation and click on *Delete* in the row of the property. The following inheritance logic applies when you delete a property link:

* If you delete the property link of a main variation, the link and value are deleted for all variations of the item that inherit the properties of the main variation.
* If you delete the property link of a variation for which inheritance is active, inheritance is deactivated and the remaining properties are saved for this variation. +
*_Note:_* The properties and values of *Properties* tab and the *Texts* tab are inherited together. You can inherit either all or none of the values.

[#310]
=== Adding suppliers to a variation

In the **Supplier** tab of a variation, you select suppliers for the product and enter supplier information, i.e. delivery time and minimum purchase. For further information, refer to the <<stock-management#, Stock management>> page of the manual.

[.instruction]
Adding a supplier to the main variation:

. Go to **Item » Edit item**.
. Open the **Default** item. +
→ The **Settings** tab of the main variation opens.
. Open the **Supplier** tab of the variation.
. Select a supplier from the drop-down list.
. Click on **Add**. +
→ The supplier is added and displayed in the list.
. Enter the supplier information. Pay attention to the information given in <<table-main-variation-supplier>>.
. **Save** the settings.

[[table-main-variation-supplier]]
.Specifying the shipping data of the main variation
[cols="1,2"]
|====
|Setting |Explanation

|**Supplier item No.**
|Enter the supplier's item number in order to explicitly identify the variation.

|**Purchase price**
|Enter the price at which you purchased the item from your supplier.

|**Minimum purchase**
|Enter the minimum quantity of the variation that have to be ordered from the supplier. Value is also used as a quantity suggestion when creating a reorder.

|**Delivery time in days**
|Enter the delivery time in days.

|**Last price query**
|Enter the date that you made the last price query to your supplier. This helps to plan price negotiations.

|**Discount**
|Enter the discount in percent if the supplier offers a discount on the variation.

|**Discountable**
|Activate the entered supplier's discount.

|**Packaging unit**
|Enter the packaging unit of the supplier if it differs from the packaging unit settings in plentymarkets.
|====

[#312]
=== Adding warehouses for the variation

In the **Warehouse** tab of a variation, you select warehouses for the product and enter warehouse information, i.e. reorder level and maximum stock. For further information, refer to the <<stock-management#, Stock management>> page of the manual.

[#314]
=== Managing the variation's stock

In the **Stock** tab, you manage your stock, book incoming items, make stock corrections and view supplies as well as item movements. For further information, refer to the <<stock-management#, Stock management>> page of the manual.

[#320]
=== Using item bundles

Item bundles consist of several **Default** items. The bundle price may be lower than the sum of the individual prices. Learn how to set up item bundles in the <<item/combining-products#2000, Setting up item bundles>> chapter.

=== Linking item images with variations

Image settings are managed in the item's **Images** tab. You can assign the images displayed in this tab to its variations by linking them with the item's variations. You can link images with variations in two different ways:

* In the **Images** tab of the item, you link images with more than one variation of the item.
* In the **Images** tab of the variation, you link images with the variation you are currently viewing.

Both procedures are described below.

==== Linking images with more than one variation

In the **Images** tab of the item, you link images with one or more variations of the item. To do so, proceed as described below.

[.instruction]
Linking item images with more than one variation:

. Go to **Item » Edit item**.
. Open the item.
. Open the **Images** tab. +
→ A preview of all images saved for the item is displayed.
. Place a check mark on the left for those images that you want to link.
. Click on **Variation link**. +
→ The **Link variations** window is displayed.
. *_Optional:_* Filter the variations using the filter to the left.
. Select the variations that you want to link with the selected images.
. Click on **Link**. +
→ The images are linked with the selected variations.

Proceed as described below to unlink images from more than one variation.

[.instruction]
Unlinking images from more than one variation:

. Go to **Item » Edit item**.
. Open the item.
. Open the **Images** tab. +
→ A preview of all images saved for the item is displayed.
. Below the image for which you want to unlink variations, klick on the plus sign next to **Variation link**. +
→ A list of the variations linked with this image is displayed.
. Select the variations for which you want to remove the link to this image.
. Click on **Unlink**. +
→ The links to the variations are removed.

==== Linking item images with the variation you are currently viewing

In the **Images** tab of the variation, you link images saved for the item with the variation you are currently viewing. To do so, proceed as described below.

[.instruction]
Linking item images with the variation you are currently viewing:

. Go to **Item » Edit item**.
. Open the item.
. Open the variation.
. Open the **Images** tab. +
→ A preview of all images saved for the item is displayed. Images that are linked with the variation are shown with a green border. Images that are not linked with the variation are greyed out.
. Point your cursor over the image you want to link.
. Click on **Link**. +
→ The image is linked with this variation.

Proceed as described below to unlink images from the variation you are currently viewing.

[.instruction]
Unlinking images from the variation you are currently viewing:

. Go to **Item » Edit item**.
. Open the item.
. Open the variation.
. Open the **Images** tab. +
→ A preview of all images saved for the item is displayed. Images that are linked with the variation are shown with a green border. Images that are not linked with the variation are greyed out.
. Point your cursor over the image you want to unlink.
. Click on **Unlink**. +
→ The link with the variation is removed.

[#150]
=== Linking a tag to a variation

If you made your <<basics/working-with-plentymarkets/tags#, tags>> available for the *Item* menu, you can link an unlimited number of tags to variations. Tags that you link to the main variation are passed on to the variations of the item. To save other tags for a variation, deactivate inheritance and save different tags.

[NOTE]
.Inheriting tags
====
If you remove all tags from a variation, inheritance is not activated. This behaviour differs from other inheritance settings in the system. Instead, the variation is saved without any tags.
====


[.instruction]
Adding a tag:

. Go to *Item » Edit item*.
. Open the variation. +
→ The *Settings* tab of the variation opens.
. *_Optional:_* If inheritance is activated, click *Deactivate inheritance*.
. Click on the text field in the *tags* area to the right.
. Enter the tag name. +
*_Tip:_* Enter the first letter of the tag and then use the auto completion feature. +
icon:map-signs[] *_Or:_* Select the tag from the list.
. *Save* the variation. +
→ The tag is linked to the variation. +
→ The variation can be found in the item overview by applying the tag filter.

// Vererbung ist anders: Wenn man alle löscht, geht die vererbung nicht an!!!
// Was kann man mit Tags machen?

// Tags entfernen

[#2090]
=== Saving variation notes

In the **Notes** tab, you can save notes about a variation. Notes are only visible in your plentymarkets back end. As such, notes will not be displayed in the online store.

[.instruction]
Saving a note:

. Go to **Item » Edit item**.
. Search for the item or variation by using the <<item/introduction/search#100, filter settings>>.
. Open the variation.
. Click on the **Notes** tab.
. Enter a note. +
. *_Optional:_* Use the functions in the toolbar to format the note.
. **Save** the note. +
→ The variation note is saved. +
→ Variations with notes are shown with a notes icon in the **Procedures** column of the item overview. Variations without notes are shown with a notes icon with a green plus symbol.

[TIP]
.Notes in the item overview
====
The **Procedures** column of the item overview shows if a note has been saved for the variation. Variations without notes are shown with a notes icon with a green plus symbol. If you select the table type **Item** to filter the item overview, only notes saved for the main variation of the item will be shown. When you create a new note in the table view **Item**, this note is saved for the item's main variation.
====

If you no longer need the information that you saved in the note, delete the note by clicking on **Delete**.

[#330]
== Editing multiple variations

Edit multiple variations with the **Variation group function** or the **Batch processing** function in the **Item** menu. The group function edits those variations that were selected in the item overview. The batch processing function edits previously filtered variations.

[.instruction]
Carrying out the variation group function:

. Go to **Item » Edit item**.
. In the search, select **Variations** in the **Table type** drop-down list.
. Select the variations that you want to edit.
. Click on **Variation group function**. +
→ The **Variation group function** window opens.
. Activate the check box to the left of the option you want to modify. Pay attention to the information given in <<table-edit-multiple-variations>>.
. Select if the option is to be activated or deactivated for the selected variations. +
→ To activate the option for the variation, activate the check box to the right of the option. +
→ To deactivate the option for the variation, leave the check box to the right of the option empty. +
**__Note:__** You can only apply one inheritance setting at a time. As such, all other settings are disabled when you select an inheritance setting.
. Click on **Execute** to apply the settings to the variations. +
**__Tip:__** When you change inheritance settings, any main variations you selected in the item overview will be ignored when the group function is run.

[[table-edit-multiple-variations]]
.Editing variations with the **Group function** or **Batch processing**
[cols="1,2"]
|====
| Setting | Explanation

2+| *Market availability*

|**Activate markets**
|The settings in this area are for the topic <<markets#, Multi-Channel>> and are described on the markets' pages.

2+| *Procedures*

|*Delete variations*
|Activate to delete the selected variations. +
*_Note:_* Even if main variations are selected, main variations are never deleted.

2+| *Tags*

|*Add tags*
|Activate to link tags with the selected variations. Click into the field and select the tags to be added to the variation.

|*Remove tags*
|Activate to unlink tags from the selected variations. Click into the field and select the tags to be removed from the variation.

|*Remove all tags*
|Activate to unlink all tags from the selected variations.

2+| *Assign client (store)*

|**Create link**
|Activate and select one or multiple clients (stores) to make the selected variations available for these online stores.

2+| *Prices*

|**Price calculation**
|Activate and select price calculation.

|**Price change**
|Activate and select settings to change the price of the selected variations. To apply the operators to the price only, select the same sales price for both source and target price. +
**Absolute** = Select an operator and an absolute value. +
= The value entered is saved as the new price. +
+ The current price is increased by the amount entered. +
- The current price is decreased by the amount entered. +
/ The current price is divided by the value entered. +
* The current price is multiplied by the value entered. +
**In percent** = Select an operator and enter a percentage. +
+ The current price is increased by the percentage entered. +
- The current price is decreased by the percentage entered. +
**Source price** = Select a sales price from the drop-down list. The price saved for this sales price will be applied to the selected target price. +
**Target price** = Select a sales price from the drop-down list. The price saved for this sales price will be changed. +
→ If the sales price selected as target price is not linked to the variation, the target sales price is linked to the variation and the new price is saved. +
→ If any of the selected variations currently inherit prices from the main variation, inheritance of all prices is deactivated and the prices are saved on the variation level.

2+| *Shipping*

|**Extra charge 1; +
Extra charge 2**
|Activate and enter a value. This value will be saved in the selected variations.

2+| *Other*

|**Generate GTIN**
|Activate and select the GTIN type to generate GTINs of this type from the <<item/settings/barcodes#200, number range>> for the selected variations.

|**Gross weight, +
Net weight**
|Activate and enter a value. This weight value will be saved in the selected variations.

2+| *Availability*

|**Active**
|Activate the variations to offer them in the online store or on markets. Variations will only be displayed in the online store when the variations are active.

|Availability symbols
|Activate and select the availability for the selected variations.

|*Invisible: in item list*
|Activate to make the variations invisible in the item list of the online store. The variations will neither be displayed in a category nor will they be displayed with the search function. The variations can only be opened if the URL is known.

|*Item list: visible if net stock is positive*;
*Item list: invisible if net stock is 0 or negative*
|Activate to automatically make the variations visible in the item list if the net stock is positive and invisible if the net stock is 0 or negative. +
When the options are activated and no net stock is available for the variations, the variations can only be accessed using the direct URL. The variation is not shown in the categories, search results or item lists (store specials, cross-selling, last seen items).

2+| *Stock*

|**Limitation**
|Activate and select a stock limitation option.

|**Main warehouse**
|Activate and select the main warehouse for the variations.

|**Reorder level**
|Activate, select a warehouse and enter a value. If the stock reaches or falls below this value, a reorder is created for the variations.

|**Maximum stock**
|Activate, select a warehouse and enter a value to limit the stock of the selected variations.

|**Stock turnover (in days)**
|Activate, select a warehouse and enter a value in days. This represents the period in days that the stock of the selected variations will suffice.

|**Storage location type**
|Activate, select a warehouse and the storage location type according to the size of the selected variations.

|**Zone**
|Activate, select a warehouse and a zone for the selected variations if you have divided your warehouse into zones.

|*Available if net stock is positive*; +
*Not available if net stock is 0 or negative*
|Activate to make the selected variations available if the net stock is positive and unavailable if the net stock is 0 or negative. Both functions complement each other and work in combination with the **To net stock** option under **Limitation**.

|*Store: visible if net stock is positive*; +
*Store: invisible if net stock is 0 or negative*
|Activate to make the selected items visible in the online store if the net stock is positive and invisible if the net stock is 0 or negative. Both functions complement each other and work in combination with the To net stock option under Limitation.

2+| *Category*

|**Category**
|Activate and select the category. The selected variations will be linked with the category. Existing category links remain unchanged.

|**Delete old category link**
|Activate to delete existing category links of the selected variations.

2+| *Inheritance* (**Variation group function** only)

|**Prices**
|Activate to change the inheritance settings for those variations selected in the item overview. +
Check box to the right of **Prices** selected = Activates inheritance of the main variation's prices to those variations selected in the item overview. Prices saved for the variation are overwritten. +
Check box to the right of **Prices** not selected = Deactivates inheritance of the main variation's prices to those variations selected in the item overview. The main variation's prices are saved for the variation. +
**__Note:__** This group function controls inheritance of all prices saved for the main variation. In other words, a variation cannot inherit just one of the main variation's prices.

|**Availability**
|Activate to change the availability level settings for those variations selected in the item overview. +
Check box to the right of **Availability** selected = Activates inheritance of the main variation's availability levels to those variations selected in the item overview. The availability level settings saved for the variation are overwritten. +
Check box to the right of **Availability** not selected = Deactivates inheritance of the main variation's availability levels to those variations selected in the item overview. The main variation's availability level is saved for the variation.

|**Markets**
|Activate to change the market availability settings for those variations selected in the item overview. +
Check box to the right of **Markets** selected = Activates inheritance of the main variation's markets to those variations selected in the item overview. The market availability settings saved for the variation are overwritten. +
Check box to the right of **Markets** not selected = Deactivates inheritance of the main variation's markets to those variations selected in the item overview. The main variation's active markets are saved for the variation. +
**__Note:__** This group function controls inheritance of all market availability settings saved for the main variation. In other words, a variation cannot inherit only one of the main variation's prices.

|**Clients (stores)**
|Activate to change the client availability settings for those variations selected in the item overview. +
Check box to the right of **Clients (stores)** selected = Activates inheritance of the main variation's client (store) availability settings to those variations selected in the item overview. The client (store) availability settings saved for the variation are overwritten. +
Check box to the right of **Clients (stores)** not selected = Deactivates inheritance of the main variation's client (store) availability settings to those variations selected in the item overview. The main variation's active clients (stores) are saved for the variation. +
**__Note:__** This group function controls inheritance of all clients (stores) saved for the main variation. In other words, a variation cannot inherit only one of the main variation's clients (stores).

|**Suppliers**
|Activate to change the suppliers for those variations selected in the item overview. +
Check box to the right of **Suppliers** selected = Activates inheritance of the main variation's suppliers to those variations selected in the item overview. The supplier settings saved for the variation are overwritten. +
Check box to the right of **Suppliers** not selected = Deactivates inheritance of the main variation's suppliers to those variations selected in the item overview. The main variation's suppliers are saved for the variation. +
**__Note:__** This group function controls inheritance of all suppliers saved for the main variation. In other words, a variation cannot inherit just one of the main variation's suppliers.

|**Categories**
|Activate to change the categories linked to those variations selected in the item overview. +
Check box to the right of **Categories** selected = Activates inheritance of the main variation's categories to those variations selected in the item overview. The active categories saved for the variation are overwritten. +
Check box to the right of **Categories** not selected = Deactivates inheritance of the main variation's categories to those variations selected in the item overview. The main variation's active categories are saved for the variation. +
**__Note:__** This group function controls inheritance of all categories saved for the main variation. In other words, a variation cannot inherit just one of the main variation's categories.

|**Warehouses**
|Activate to change the warehouses for those variations selected in the item overview. +
Check box to the right of **Warehouses** selected = Activates inheritance of the main variation's warehouses to those variations selected in the item overview. The warehouse settings saved for the variation are overwritten. +
Check box to the right of **Warehouses** not selected = Deactivates inheritance of the main variation's warehouses to those variations selected in the item overview. The main variation's active warehouses are saved for the variation. +
**__Note:__** This group function controls inheritance of all warehouses saved for the main variation. In other words, a variation cannot inherit just one of the main variation's warehouses.

|**Properties**
|Activate to change the property inheritance settings for those variations selected in the item overview. +
Check box to the right of **Properties** selected = Activates inheritance of the main variation's properties to those variations selected in the item overview. The active properties saved for the variation are overwritten. +
Check box to the right of **Properties** not selected = Deactivates inheritance of the main variation's properties to those variations selected in the item overview. The main variation's active properties are saved for the variation. +
**__Note:__** This group function controls inheritance of all properties of the *Properties* and *Texts* of the main variation. In other words, a variation cannot inherit just one of the main variation's properties.

|*Tags*
|Activate to change the tag inheritance settings for those variations selected in the item overview. +
Check box to the right of *Tags* selected = Activates inheritance of the main variation's tags to those variations selected in the item overview. The tags linked to the variation are replaced. +
Check box to the right of *Tags* not selected = Deactivates inheritance of the main variation's tags to those variations selected in the item overview. The linked tags are removed. The variation is saved without any tags. +
*_Note:_* This group function controls inheritance of all categories saved for the main variation. In other words, a variation cannot inherit just one of the main variation's tags.
|====

[.instruction]
Carrying out batch processing:

. Go to **Item » Batch processing**.
. Open the **Variations** tab.
. Select the filters based on <<table-variation-filter-batch-processing>>.
. Carry out the settings. Pay attention to the information given in <<table-edit-multiple-variations>>.
. Click on **Apply** to apply the settings to the variations.

[[table-variation-filter-batch-processing]]
.Filter options for **batch processing** of variations
[cols="1,2"]
|====
| Setting | Explanation

|**Variation ID**
| Select the operator and enter one or more variation IDs to search for variations with this ID. Use commas to separate multiple variation IDs.

|**Item ID**
| Select the operator and enter one or more item IDs to search for items with this ID. Use commas to separate multiple item IDs. Allows you to edit all variations of an item.

|**Flag 1; +
Flag 2**
| Select a flag to only edit variations that have this flag.

|**Manufacturers**
| Select a manufacturer or **ALL** to edit variations of the selected manufacturer only.

|**Condition**
|Select the condition to edit variations that have this condition only.

|**Main variations**
|Activate to edit main variations only.

|**Without category**
|Activate to edit variations which are not linked with a category only.

|**Categories**
|Select the category to edit variations that have this category only.

|**Tags**
|Activate to edit variations which are linked with these tags. +
// xxx Reihenfolge prüfen!
|====



[#1090]
== Copying items and variations

In this chapter, you will learn how to copy items and variations. When copying an item, a copy of the item and all its variations is created. The following information is copied:

* Item data which is entered in the **Global** tab
* Item texts
* Free text fields
* Characteristics (old properties)
* Images
* Cross-selling settings
* Sales prices including saved values
* Barcodes including saved values
* Item bundles
* Properties

The following information is not copied:

* Listings
* Media files
* Availability of the main variation
* Dimensions
* Costs


New variation numbers for the main variation and all additional variations of the copied item will be assigned. Change the variation numbers in the <<item/managing-items#170, Settings>> tab of a variation. After copying, the copied <<item/managing-items#30, item>> can be edited. Proceed as follows to copy an item.

[.instruction]
Copying an item:

. Go to **Item » Edit item**.
. Open the item.
. Click on **Copy** in the item's toolbar. +
→ The **Copy** window opens.
. Click on **Copy**. +
→ The item is copied. +
→ The copy opens in a new tab.

Copy an item variation to offer this variation with different contents. All variation data will be copied. Main variations cannot be copied.

[.instruction]
Copying a variation:

. Go to **Item » Edit item**.
. Open the **Default** item.
. Open the variation.
. Click on **Copy** in the variation's toolbar. +
→ The **Copy** window opens.
. Enter the content.
. *_Optional:_* Select a unit.
. Click on **Copy**. +
→ A copy of the variation is created. +
→ The copy opens in a new tab.

[IMPORTANT]
.Check sales prices and barcodes
====
Check the <<item/settings/prices#, sales prices>> and <<item/settings/barcodes#, barcodes>> after copying and change these values if needed.
====


// NEXT: 4400
