= Preparatory settings
:lang: en
include::{includedir}/_header.adoc[]
:description: Get ready to start selling items with your plentymarkets system. Start out by saving information, will be linked to your items and variations later.
:url: item/settings
:icons: font
:position: 20
:docinfodir: /workspace/manual-adoc
:docinfo1:

//Text mit includes ersetzen, Textteile stammen aus der Seite "artikel/einleitung" und aus "artikel/einleitung/struktur"

Items are made up of lots of information, e.g. categories, prices, manufacturers, descriptive texts and images. But sometimes a little preliminary work is necessary.

Before you can sort an item into a specific category, the category first needs to exist in plentymarkets. Before you can select an item’s manufacturer, the manufacturer data needs to exist in plentymarkets.

Such preparatory system settings are first configured in the *Setup* menu and then they’re linked to items or variations.

Some of the most important system settings are:

* <<item/settings/categories#, Categories>>, which group your products.
* <<item/settings/units#, Units>>, which define the content of your variations.
* <<item/settings/attributes#, Attributes>>, which simultaneously characterise your products and build variations.
* <<item/settings/properties#, Characteristics and properties>>, which characterise your products _without_ building variations.
* <<fulfilment/preparing-the-shipment#1000, Shipping profiles>>, which define your shipping services and shipping costs.
* <<item/settings/manufacturers#, Manufacturers>>, which list the names, contact information, IDs and commissions saved for your manufacturers.
* <<item/settings/prices#, Sales prices>>, which define the conditions under which a variation is sold at a specific price.
