= Changes in the new Terra back end
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plentymarkets 7, changes, back end, admin area, terra
:description: Overview of changes in the new Terra back end of plentymarkets 7
:position: 0

This page provides you with a short overview of the most important changes in the new Terra back end of plentymarkets 7. The overview helps users get started with the new back end of plentymarkets 7. This description is geared towards plentymarkets users who already worked with the old back end. If you are unfamiliar with a certain function in plentymarkets, then take a look at the corresponding pages of the manual first.

== Accessing the new back end

Access the new back end via the login page of your plentymarkets administration area.

[.instruction]
Logging in to the new back end:

. Open the login page of your plentymarkets system.
. Select **Terra** from the **Version** drop-down list.
. Select the language.
. Enter the user name and password.
. Click on **Login**.

Alternatively, you can access the new back end using the following URL: **www.your-plentystore.co.uk/plenty/terra/login**.

== Login page

The login page has been visually redesigned. Existing functions and input fields were not changed. The **Version** drop-down list was added. Use this drop-down list to switch between the new and the old back end.

== Homepage

The homepage has been visually redesigned. In the old back end, the context menu is opened by right-clicking on the **Homepage** tab. In the new back end, open the context menu of the **Homepage** tab by mouse-over on the arrow on the right of the tab. Right-clicking the tab will only open the context menu of the browser. Further changes were made to the menu bar, the quick access buttons and the logout.

== Menu bar

The menu bar has been visually redesigned. The following changes were made to the structure of the menu bar.

* Icons were added to the individual menus
* Drop-down lists were changed into drop-down lists, i.e. sub-menus are greyed out and the options of the sub-menu are listed below
* The **Switch menu arrangement** button was removed
* The **Start** is opened by mouse-over on the plentymarkets icon on the left of the menu bar
* The red logout button was added on the right of the menu bar

== Quick access buttons

The quick access buttons were removed from the header and added to the blue **side bar** on the right of the browser window. Place the cursor on the side bar, to display the quick access buttons.

== Menus

The following menus were changed in the course of the back end redesign:

* The **Start » Plugins** menu was removed from the old back end and is only available in the new back end

