= Erster Login und Rundgang
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Login, Einloggen, Log in, Anmelden, Anmeldung, Backend, Back end, Neu, Neukunde, Neukunden, System, Rundgang, Tour, Menüstruktur, Backend-URL, Backend-URLs, URL, URLs
:description: Diese Seite richtet sich an neue plentymarkets Nutzer. Lerne, wie du dich im System einloggst und sich durch die Menüstruktur navigiert.
:position: 10
:url: willkommen/login-rundgang
:id: BBRBTD5
:author: team-cloud, team-terra

//add this url weiterleitung /basics/arbeiten-mit-plentymarkets/allgemeine-funktionen/;/willkommen/login-rundgang/;301;L

Willkommen bei plentymarkets. Komm mit auf einen Rundgang durch dein neues System!

.Lerne plentymarkets durch ein spielerisches Einführungsvideo kennen
video::257449279[vimeo]

[#10]
== Zum ersten Mal einloggen

Um loszulegen, brauchst du nur die Begrüßungs-E-Mail, die du von plentymarkets erhalten hast.
Dort findest du alle wichtigen Daten für deinen ersten Login.
Jeder Login ist verschlüsselt und daher absolut sicher.

[.instruction]
In plentymarkets einloggen:

. Klicke auf den Link in der E-Mail, um zum Anmeldefenster von plentymarkets zu gelangen.
. Gib die plentymarkets ID, den Benutzernamen und das Passwort so ein, wie sie in deiner E-Mail angegeben wurden.
. Klicke auf *Login*.

[TIP]
.Wie logge ich mich wieder aus?
====
Bewege den Mauszeiger über das Benutzersymbol (icon:user-circle[]) und klicke dann auf *Logout*.
====

[#20]
== Sich im Backend zurechtfinden

Oben befindet sich die Hauptnavigation. Hinter all den Punkten steckt natürlich auch noch viel mehr. Was genau zeigen dir die Dropdowns, die sich bei Mouseover öffnen und dich zu allen wichtigen Bereichen von plentymarkets führen.

* *Einrichtung* +
In diesem Menü konfigurierst du die Tools und Funktionen in deinem plentymarkets System. Wirf einen Blick auf unsere <<willkommen/assistenten#, Assistenten>> und auf den <<willkommen/schnelleinstieg#, Schnelleinstieg>>. Diese Hilfsmittel führen neue Benutzer durch die Ersteinrichtung des Systems.
* *Dein Vertrag mit plentymarkets* +
Im Menü *plentymarkets Logo (Start) » Mein Konto* findest du Informationen zu deinem plentymarkets System. Hier kannst du z.B. <<business-entscheidungen/dein-vertrag#, deinen Vertrag mit plentymarkets>> einsehen und bearbeiten.
* *Benutzerkonto* +
Klicke auf die Benutzer-Schaltfläche (icon:user-circle[]) um in dein Benutzerkonto zu gelangen. Hier kannst du z.B. den <<business-entscheidungen/benutzerkonten-zugaenge#30, Benutzernamen und das Passwort ändern>>, die dir in der Begrüßungs-E-Mail zugesandt wurden.
* *Webshop* +
Klicke auf deine plenty ID oben rechts im plentymarkets Backend, um die Startseite deines Webshops aufzurufen.
* *Vollbildmodus* +
Klicke auf icon:ellipsis-v[] oben rechts im plentymarkets Backend, um den Vollbildmodus zu aktivieren bzw. zu deaktivieren.
* *Favoriten* +
Klicke auf icon:ellipsis-v[] oben rechts im plentymarkets Backend, um <<willkommen/system-personalisieren#90, deine Favoriten>> anzuzeigen, alle zu öffnen oder diese zu löschen.
* *Services und Partnerangebote* +
Klicke auf icon:question-circle[] oben rechts im plentymarkets Backend, um verschiedene Supportangebote und Partnerservices aufzurufen.

[#40]
== Dein System personalisieren

Bist du neu bei plentymarkets? Dann empfiehlt es sich, zunächst mal dein Benutzerkonto individuell anzupassen.
Erfahre z.B. auf weiteren Handbuchseiten, wie du:

* deinen vorläufigen <<business-entscheidungen/benutzerkonten-zugaenge#30, Benutzernamen und Passwort ändern>> kannst.
* <<willkommen/system-personalisieren#30, ein Benutzerbild>> statt der leeren Benutzer-Schaltfläche (icon:user-circle[]) anzeigen kannst.
* die <<willkommen/system-personalisieren#150, Spalten- und Sortierreihenfolge>> einige Menüs anpassen kannst.
* häufig verwendete <<willkommen/system-personalisieren#90, Menüs als Favoriten speichern>> kannst.
* eine <<willkommen/system-personalisieren#40, Signatur und Grüßformel>> ans Ende deiner E-Mails anfügen kannst.
* <<willkommen/system-personalisieren#140, weitere Funktionalitäten und Menüeinträge>> mit Hilfe von Plugins hinzuzufügen kannst.

[#50]
== Backend-Bereiche mit URLs direkt aufrufen

Einige Bereiche des Backends können mithilfe von UI-Aktionen direkt aufgerufen werden. Das spart Zeit, da eine Vielzahl von Klicks im Backend mit einem einzigen Seitenaufruf ersetzt wird. In diesem Abschnitt sind die Variablen und Parameter aufgeführt, die hierfür verwendet werden können.

[IMPORTANT]
.Hinweis
====
Du musst eingeloggt sein, um einen Backend-Bereich mit einer URL aufrufen zu können. Beachte außerdem die Groß- und Kleinschreibung in der URL.
====

[#60]
=== Einen Backend-Bereich mit einer URL aufrufen

. Gib als ersten Teil des Pfads `https://plentymarkets-cloud-de.com` oder `https://plentymarkets-cloud-ie.com` ein. Welche Informationen du eingeben sollst, hängt davon ab, ob dein System in Deutschland oder in Irland gehostet wird.
. Trage nach einem `/` deine plenty-ID ein.
. Fahre mit der Abfragezeichenfolge fort. Diese beginnt mit einem `?`.
. Füge die UI-Aktion mit `uiAction=` hinzu.
. Trage den Schlüssel für die UI-Aktion und die Parameter mit den entsprechenden IDs ein. Beachte die Erläuterungen in <<tabelle-keys-ui-actions-parameter>>.
. Rufe die URL mit allen Informationen auf, um in den gewünschten Backend-Bereich zu gelangen.

[TIP]
.Beispiel
====
Um die Varianten-Detailansicht zu öffnen, muss sich der Pfad aus den folgenden Parametern zusammensetzen: +
`plentymarkets-cloud-de.com/1234?uiAction=ITEM_VARIATION_DETAIL&itemId=102&variationId=1111`
====

[[tabelle-keys-ui-actions-parameter]]
.Keys für UI-Actions und Parameter
[cols="1,2"]
|====
|Schlüssel |Erläuterung

|*ITEM_DETAIL* +
 *itemId*
|Öffnet die Artikeldetailansicht für die angegebene Artikel-ID (itemId ist Pflichtparameter).

|*ITEM_VARIATION_DETAIL* +
 *itemId* +
 *variationId*
|Öffnet die Variantendetailansicht für die angegebene Artikel-ID und Varianten-ID (itemId und variationId sind Pflichtparameter).

|*ORDER_DETAIL* +
 *orderId*
|Öffnet die Auftragsdetailansicht für die angegebene Auftrags-ID (orderId ist Pflichtparameter).

|*REORDER_DETAIL* +
 *reorderId* +
 *itemId* +
 *reorderItemId*
|Öffnet die Nachbestellungsdetailansicht für die angegebene Nachbestellungs-ID, die Artikel-ID oder die Artikel-ID einer Nachbestellung (Hier darf nur einer der drei Parameter angegeben werden).

|*TICKET_DETAIL_VIEW* +
 *ticketId*
|Öffnet die Ticketdetailansicht für die angegebene Ticket-ID (ticketId ist Pflichtparameter).

|*CUSTOMER_DETAIL* +
 *customerID*
|Öffnet die Kundendetailansicht für die angegebene Kontakt-ID (customerId ist Pflichtparameter).
|====

[#70]
=== Abgesicherter Modus

Im abgesicherten Modus kannst du das Backend mit deaktivierten Plugins aufrufen. Dies kann notwendig sein, wenn du nach der Installation oder dem Aktualisieren eines Plugins beim regulären Einloggen eine Fehlermeldung erhältst. Im abgesicherten Modus kannst du das Plugin auf *Inaktiv* setzen.

Wenn du dich im abgesicherten Modus einloggen möchtest, verwende die URL `https://plentymarkets-cloud-de.com/?safemode=1` oder `https://plentymarkets-cloud-ie.com/?safemode=1` ein. Welche URL du verwenden sollst, hängt davon ab, ob dein System in Deutschland oder in Irland gehostet wird.
