= Kauflux
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market Kauflux in your plentymarkets system.
:position: 130

**link:http://www.kauflux.de/[Kauflux.de, window="_blank"]** is an open marketplace with independent providers from various areas. Kauflux.de markets your items and services and provides you with direct contact to purchasers.

[#10]
==  Registering with Kauflux

You have to register with link:http://www.kauflux.de/konto[**Kauflux**, window="_blank"] before you can set up Kauflux in your plentymarkets system.

[#20]
==  Setting up Kauflux in plentymarkets

Carry out the following basic settings in order to transfer item data to Kauflux.

[.instruction]
Setting up Kauflux in plentymarkets:

. Go to **Settings » Markets » Kauflux » Basic settings**.
. Pay attention to the explanations given in table 1 and carry out the settings as desired.
. **Save** the settings.

[cols="a,a"]
|====
|Setting |Explanation

|**Exchange period**
|Enter the exchange period for the items. The exchange period is given in days. If you want to forbid items from being exchanged, then enter the value **0**.

|**Order referrer**
|Select the order referrer for Kauflux.

|**Type of stock management**
|Select whether you would like to transfer your stock and if so, whether you would like it to be **publicly** visible or not.

|**API URL for the order import**
|Kauflux uses this link to transfer orders to plentymarkets. This link is needed for importing orders from Kauflux and not for creating the item catalogue. The item catalogue is created with the price comparison portals. This is done in the **link::/[Settings » Markets » Price comparison portals » Exports]** menu. Further information in German can be found on **link:http://www.kauflux.de/shop-anmelden/automatischer-auftragsdatenexport[Kauflux, window="_blank"]**.
|====

__Table 1: basic settings for Kauflux__

[#30]
== Setting the item availability

Items have to be available for Kauflux. This is done in the **Availability** tab of an item within the link::/[**Item » Edit item » Tab: Variation ID**] menu.

[.instruction]
Setting the item availability for Kauflux:

. Open the **Item » Edit item » Open item » Tab: Variation ID » Tab: Settings** menu.
. Activate the main variation in the **Availability** section.
. Click on the **Availability** tab.
. Click in the **Markets** section in the selection field.  +
→ A list with all available markets will be displayed.
. Activate the option **Kauflux**.
. Click on **Add**. +
→ The Market will be added.
. **Save** the settings. +
→ The item is available on Kauflux.

The availability for variations can be individually edit in the **Item » Edit item » Open item » Tab: Variation ID » Open variation » Tab: Availability** menu.

[#40]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Kauflux. This price will be displayed on Kauflux.

[.instruction]
Defining a sales price for Kauflux:

. Open the menu **Settings » Item » Sales price » Open sales price » Tab: Settings**.
. Place a checkmark next to the referrer **Kauflux**.
. **Save** the settings.

[#50]
== Linking properties

In order to have the ability of using properties for the Kauflux market, these have to be linked with Kauflux in the corresponding property's settings.

[.instruction]
Linking properties:

. Go to **Settings » Item » Properties**.
. Expand a property.
. Activate the option **Kauflux**.
. **Save** the settings.

[#60]
== Linking categories

Go to **Settings » Markets » Kauflux » Category link** to link your online store categories with the categories on Kauflux. You need the Kauflux CSV file for setting up a category link. This file contains the **category IDs** for this market. You can download this link:http://support.expeedo.de/f/kl/kauflux-Kategorien.xls[**file**] from the sellers area on the Kauflux website. In the next steps, you will export a list of categories in your online store, link these categories and then import the category links.

[.instruction]
Exporting links:

. Go to **Settings » Markets » Kauflux » Category link**.
. Click on **Export link**. +
**→** This generates a CSV file with your online store categories.
. Open the online store CSV file.

[.instruction]
Entering category IDs

. Open the Kauflux CSV file.
. For each category in your online store, search for the corresponding **category IDs** in the Kauflux CSV file.
. Enter the category IDs from the Kauflux CSV file into the **KaufluxCat** column in the online store CSV file.
. Save the online store CSV file on your computer's hard drive.

[.instruction]
Importing links:

. Go to **Settings » Markets » Kauflux » Category link**.
. Click on **Browse...** in the line **File**.
. Select the online store CSV file that you saved on your computer's hard drive.
. Click on **Open**.
. **Save** the settings. +
→ The links will be imported and displayed in the **Links** area.

[#70]
== Exporting items

After you have configured Kauflux, you can export your items under **link::/[Settings » Markets » Price comparison portals » Exports]**.

For an automatic item export, you have to copy the complete URL and save it with Kauflux. The prerequisites for this are that you have carried out at least one item export manually and that you have assigned the individual fields in Kauflux. Additionally, the automatic item export from Kauflux has to be activated.

[#80]
== Exporting variations

During the export, variations will be exported as additional CSV fields. If you would like to import this CSV or ZIP file into Kauflux, then you will be asked to map the categories.

[IMPORTANT]
.Example
====
The variation fields **colour**, **size** and **length** are displayed in the mapping. For all variation fields, you have to select **GroupParam** as the mapping field so that these fields can be saved as variations on Kauflux.de. The field **GroupID** serves exclusively to identify the items that belong together in a group.
====

[#90]
== Importing orders

Your orders from Kauflux can be imported into your system automatically. You simply have to save the API URL on Kauflux. This URL is found under **Settings » Markets » Kauflux » Basic settings**. After completing this step, orders will automatically be imported into your system and displayed in the menu **Orders » Edit orders**.

[#100]
== Sending an email when orders are imported

It is possible to send automatic emails when orders are imported into plentymarkets. Go to **link::/[Settings » Client (store) » Standard » Email » Templates]** to create and activate an email template for Kauflux.

[.instruction]
Sending an email when orders are imported:

. Go to **Settings » Client (store) » Standard » Email » Automatic email**.
. Select the previously created email template for the option **New order from Kauflux**.
. **Save** the settings.

Click on **Edit email template** to access the menu **Settings » Client (store) » Standard » Email » Templates** and edit the email template.

