= Restposten.de
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market Restposten.de in your plentymarkets system.
:position: 210

link:http://www.restposten.de/[**Restposten.de**, window="_blank"] is a pure B2B portal, which means that both sellers and buyers have to be in possession of a valid traders license (source: Restposten.de). On this page, you will learn how to connect the Restposten.de market to your plentymarkets system.

toc::[]
[#10]
== Registering with Restposten.de

You have to register in the Restposten.de link:https://www.restposten.de/register.php[**seller portal**, window="_blank"] before you can set up Restposten.de in your plentymarkets system.

[#20]
== Creating an user account

Your plentymarkets system will be connected to Restposten.de via the SOAP API. In order for it to have access, the market requires its own user account with access rights to the API in your system. Go to **Settings » Basic settings » User » Accounts** and create a new user account for Restposten.de with the user class **API**. Furthermore, activate the call **GetCategoryMappingForMarket**. This call ensures that the market will later be able to retrieve your category links.

[.instruction]
Creating an user account for Restposten.de:

. Go to **Settings » Basic settings » User » Accounts**.
. Click on **New**. +
→ The **Create new user** window will open.
. Enter the data.
. Select the user class **API**.
. **Save** the settings. +
→ The user will be created.
. Select the user from the list. +
→ The editing window will open.
. Click on the tab **Right » API**.
. Expand the **Item** area.
. Activate the **GetCategoryMappingForMarket** call.
. **Save** the settings.

[#30]
== Procuring data

Restposten.de needs to have the following data from you in order to connect to your plentymarkets system:

* The URL for the SOAP API WSDL +
→ This URL can be found in the **<<working-with-plentymarkets/basic-settings/api-data#, Settings » Basic settings » API » Data  >>** menu under **SOAP WSDL**.
* The user name and password for the user account that you created for Restposten.de.
* Your login details for the Restposten.de. seller portal.

[#40]
== Setting the item availability

Items have to be available for Restposten.de. This is done in the **Availability** tab of an item within the <</#, **Item » Edit item » Tab: Variation ID** >> menu.

[.instruction]
Setting the item availability for Restposten.de:

. Open the **Item » Edit item » Open item » Tab: Variation ID » Tab: Settings** menu.
. Activate the main variation in the **Availability** section.
. Click on the **Availability** tab.
. Click in the **Markets** section in the selection field.  +
→ A list with all available markets will be displayed.
. Activate the option **Restposten**.
. Activate the option Web-API.
. Click on **Add**. +
→ The Market will be added.
. **Save** the settings.  +
→ The item is available on Restposten.de.

The availability for variations can be individually edit in the **Item » Edit item » Open item » Tab: Variation ID » Open variation » Tab: Availability** menu.

[#45]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Restposten.de. This price will be displayed on Restposten.de.

[.instruction]
Defining a sales price for Restposten.de:

. Open the menu **Settings » Item » Sales price » Open sales price » Tab: Settings**.
. Place a checkmark next to the referrer **Restposten.de**.
. **Save** the settings.

[#50]
== Creating properties

Use <</#, **properties** >> to link your items to particular characteristics that you need for the market Restposten.de. In order for Restposten.de to be able to retrieve the necessary parameters, the property has to be created with the **property type** set to the option **Selection**. Get in contact with Restposten.de to clarify which values will be needed for the property.

[.instruction]
Creating a property for Restposten.de:

. Go to **Settings » Item » Properties**.
. Click on the **New property** tab.
. Enter the name in the **Back end name** field.
. Select the **Selection** option as the **Property type**. +
→ An area will open where you enter the name and description.
. **Save** the settings. +
→ The property will be created.
. Click on the **Properties** tab.
. Expand the property.
. Enter another name in the next selection field of the **Selection** area.
. **Save** the setting.
. Repeat steps 8 and 9 until all required values are created.
. **Save** the settings.

[#60]
== Linking categories

Link your online store categories to the Restposten.de **<<item/categories#, categories  >>** in order to display your items in these categories. Further items from the linked category will be assigned automatically.

[.instruction]
Linking categories:

. Go to **Settings » Markets » Restposten**. +
→ The **Category link** tab will be displayed.
. Expand the category which you want to link to a Restposten category.
. Select a main category for Restposten from the drop-down menu. +
→ A window with subcategories will open.
. Select the appropriate Restposten category from the subcategories that appear. +
→ The category path will be displayed in the field **Category**.
. Click on **Accept**. +
→ The category window will close.
. **Save** the settings.

[IMPORTANT]
.Link to the lowest category level
====
Always select a path to the lowest level. Otherwise, the item will not be linked.
====

[.subhead]
Returns
For returns, you have to create an order with the type return, not credit note. It is also important to specify each individual item's value as a percentage. This can be done within the return's stock units tab.

