= Managing plugins
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plugins, extensions, functionality
:description: This is how you manage plugins in the plentymarkets back end.
:position: 40

Manage and deploy plugins that you purchased on the link:https://marketplace.plentymarkets.com/[plentyMarketplace^] or developed yourself in the **Plugins** menu. Install new plugins, change the state of existing plugins or delete plugins. Find out how to create your own plugins on link:http://developers.plentymarkets.com/[plentyDevelopers^].

[NOTE]
.Plugin functionalities are extended continuously
====
The plentymarkets plugin module and the possibilities for editing plugins are extended continuously. The number of available plugins will increase over time.
====

[#purchasing-marketplace-plugins]
== Purchasing marketplace plugins

The link:http://marketplace.plentymarkets.com/en/[plentyMarketplace^] is our platform for distributing software extensions for plentymarkets developed by plentymarkets or external developers. This platform makes plugins easily accessible and ensures that you can benefit from the advantages the new technology offers. To purchase a plugin, proceed as follows.

[.instruction]
Purchasing plugins:

. Open the link:http://marketplace.plentymarkets.com/en/[plentyMarketplace^].
. Click on the *Login* button.
. Enter your email address and plentyID. +
→ Use the same login data as for the service centre.
. Enter your password.
. Click on the **Login** button.
. Select a category and a plugin you want to purchase.
. In the detail view of the plugin, click on the **Go to checkout** button. +
→ The **Checkout** window opens.
. Accept the terms and conditions.
. Click on **Order now**. +
→ The purchased plugin is now available in the **Plugins » Plugin overview** menu.

[#adding-git-plugins]
== Adding your own plugins from git

If you cannot find the plugin you need on the plentyMarketplace, you can also add your own plugins to your plentymarkets system. To add a plugin to plentymarkets that is managed by Git versioning, proceed as follows.

[.instruction]
Adding a Git repository to plentymarkets:

. Go to *Plugins » Git*.
. Click on *Add new Repository*. +
→ The options for the repository settings are displayed.
. Enter the necessary information for the Git repository. Pay attention to the explanations given in <tabelle-git-plugins-hinzufuegen>.
. *Save* the settings. +
→ The connection to the Git repository is checked and established. The success message *Repository saved.* appears.

[[table-adding-git-plugins]]
.Adding git plugins
[cols="1,3"]
|====
|Setting |Explanation

|*Repository URL*
|HTTPS or HTTP URL of the Git repository

|*User name*
|The user name is part of the user data of the provider (e.g. GitHub) for the Git repository. +
For public repositories, enter any value into the field, e.g. *guest*.

|*Password or token*
|The password is part of the user data of the provider (e.g. GitHub) for the Git repository. +
For public repositories, enter any value into the field, e.g. *guest*. +
If two factor authentication has been activated, a token is needed.

|*Name of branch to be installed (must contain valid plugin.json file).*
|The Git repository has to include a valid Plugin.json file. This input is required for the initial installation.
|====


=== Deleting a Git repository

In the *Plugins » Git* menu, repositories can be deleted by clicking the *Delete* button.

[#managing-plugin-sets]
== Plugin overview - managing plugin sets

The following tables lists all UI elements of the *Plugin overview* menu and provides a short description for each of them. Furthermore, this section includes instructions for creating, editing and deleting your plugin sets.

[[table-plugin-overview]]
.Table view of the *Plugin » Plugin overview* menu
[cols="1,3"]
|====
|Element |Description

|*Create new set*
|Open a window for creating a new plugin set. +
*Save*: Saves the new plugin set. +
*New Set*: Name of the plugin set. +
*Copy Plugin Set*: Select an existing plugin set from the dropdown menu to copy all of its settings.

|*Publish plugin set*
|Publishes the selected plugin set.

|Name of the plugin set
|Loads the plugin overview for the selected plugin set.

|*Delete Plugin Set*
|Deletes the plugin set. Requires confirmation.

|Filter
|*Search*: Loads all plugins of the plugin set in the plugin overview that conform to the selected filter settings. +
*Reset*: Resets the filter settings to the default settings. +
*Name*: Filters for plugins whose name includes the entered string. +
*plentyMarketplace*: Filters for plugins which were added to the system via plentyMarketplace. +
*Git*: Filters for plugins which were added to the system via a git repository. +
*Local*: Filters for plugins which were added to the system via local storage. +
*Installed*: Filters for plugins which are installed for the selected plugin set. +
*Not installed*: Filters for plugins which are not installed for the selected plugin set. +
*Active*: Filters for plugins which are activated for the selected plugin set. +
*Not Active*: Filters for plugins which are not activated for the selected plugin set. +

|*Save & publish plugin set*
|Saves changes made to the plugin set and publishes plugins in the set for further use.

|*Plugin set preview*
|Opens a new tab displaying a preview of the front end with the current settings. Plugin sets must be published before changes are reflected in the preview.

|*plentyDrive: build automatically*
|When activated, whenever you add plugins to the plugin set via plentyDrive, the plugin set will be saved and published automatically.

|*Plugin set settings*
|Opens a window for editing the selected plugin set. +
*Save*: Saves the edited plugin set. +
*Name*: Changes the name of the plugin set. +
*Plugin set ID*: ID of the plugin set.

|*Log*
|Only visible when error messages exist. Displays the error messages.

|*Active*
|Shows whether the plugin is active or not.

|*Name*
|Name of the plugin. If the plugin is installed, click to view information and settings.

|*Installed version*
|The latest version of the plugin currently installed. A symbol indicates when a newer version of the plugin exists.

|*Active version*
|The activated version of the plugin. Will be loaded for the selected plugin set in both the front end and back end.

|*Source*
|The source of the plugin. Can be plentyMarkets, Git or a local storage.

|*Action*
|*Install plugin*: Installs the plugin. In a new window, you can select the version of the plugin you want to install and view the changelog. Only visible when the plugin is not installed. +
*Update*: Updates the plugin to a newer version. In a new window, you can select the version of the plugin you want to install and view the changelog. Only visible when there is a newer version of the plugin. +
*No update available*: The latest version of the plugin is installed. +
*Set position*: Determines the order in which plugins are loaded. Plugins set to a low position are loaded first. +
*Delete*: Removes the plugin from the plugin set. Requires confirmation.

|*plentyMarketplace*
|Opens plentyMarketplace in a new tab.
|====

A plugin set is a collection of multiple plugins. These sets can all be managed for one or multiple clients in the *Plugin overview*. They contain one or multiple plugins as well as settings for plugin configuration and layout containers. Plugin sets especially benefit sellers who use plentymarkets to manage multiple online stores at the same time. They can activate and configure different plugin sets for different clients.

The following sections describe how to create new plugin sets, edit plugin sets and delete plugin sets.

[#creating-plugin-sets]
== Creating plugin sets

[.instruction]
Creating plugin sets:

. Go to *Plugins » Plugin overview*.
. Click on *Add*. +
→ The *New plugin set* window opens.
. Enter a name for the plugin set.
. Select a plugin set from the *Copy plugin set* dropdown menu to copy that plugin set's settings.
. *Save* the settings.

[.instruction]
Installing plugins:

. Click on the plugin set you want to edit. +
→ This loads the plugin overview for the selected set.
. Use the filter by checking the *Not installed* checkbox and clicking on *Search*. If you want to install plugins you have added via a git repository or local storage, also check *Git* or *Local*.
→ The plugin overview will be updated according to the selected filters.
. To install a plugin, under *Action*, click on the *Install plugin* button associated with the plugin. +
→ A new window opens, allowing you select the version you want to install. Select the version you want to install from the *Version to install* dropdown menu. The newest version is selected by default. A text field below the dropdown menu shows the changelog of the currently selected version. Click on the *Install* button to install the selected version. +
→ The plugin will be installed and is then available in the plugin overview of the plugin set. The overview shows all currently installed plugins.

[.instruction]
Activating plugins:

. To activate a plugin, under *Active*, click on the *Not active* button associated with the plugin. +
→ Activated plugins will be loaded for the selected plugin set in both the front end and back end.

[.instruction]
Setting the position of plugins:

. To set the position of a plugin, under *Action*, click on the *Set position* button associated with the plugin. +
→ The *Plugin position* window will open. Enter the position you want to assign the plugin in the text field and click on *Save*.
→ The position of the plugin will be updated.

[TIP]
.Position of plugins
====
A plugin’s relative position determines the order in which plugins of the plugin set are loaded.  Plugins with a lower position will be loaded earlier. That is why you should set the IO plugin to the highest position and the Ceres plugin to the second highest.
====

[.instruction]
Previewing plugin sets:

. Click on *Plugin set preview*.
. Select the online store that you want to preview. Before previewing a plugin, it set has to be deployed by clicking the *Save & deploy plugin set* button. +
→ The selected online store and its selected plugin set open in a new browser tab.

[.instruction]
Linking plugin sets:

. Click on *Link plugin sets*. +
→ The *Link plugin sets* window opens.
. Select the plugin set you want to use for your online store.
. *Save* the settings.

[TIP]
.Linking plugin sets
====
Linking a plugin set to a client makes all plugins of that plugin set public. This happens immediately. You should test the plugin set thoroughly and utilize the preview function before linking it.
====

[#editing-plugin-sets]
== Editing plugin sets

[#changing-plugin-set-name]
=== Changing the name of a plugin set

[.instruction]
Changing the name of a plugin set:

. Go to *Plugins » Plugin overview*.
. Click on the plugin set you want to edit. +
→ This loads the plugin overview for the selected set.
. Click on the *Plugin Set Settings* button.
→ The *Settings* window will open.
. Under *Name*, enter the new name for your plugin set.
. *Save* the settings.
→ The name of the plugin set changes.

[TIP]
.Backup
====
Whenever you want to edit a plugin set, either by adding new plugins to the set, updating existing plugins or deleting plugins, it is recommended that you first create a backup of the plugin set and using this backup to implement your changes. This prevents any unforeseen consequences of the changes from affecting your actual store.
====

[#adding-plugins]
=== Adding plugins

[.instruction]
Copying a plugin set:

. Go to *Plugins » Plugin overview*.
. Click on *Add*. +
→ The *New plugin set* window opens.
. Enter a name for the plugin set.
. Select a plugin set from the *Copy plugin set* dropdown menu to copy that plugin set's settings.
. *Save* the settings.

[.instruction]
Installing plugins:

. Go to *Plugins » Plugin overview*.
. Click on the plugin set you want to edit. +
→ This loads the plugin overview for the selected set.
. Use the filter by checking the *Not installed* checkbox and clicking on *Search*. If you want to install plugins you have added via a git repository or local storage, also check *Git* or *Local*.
→ The plugin overview will be updated according to the selected filters.
. To install a plugin, under *Action*, click on the *Install plugin* button associated with the plugin. +
→ A new window opens, allowing you select the version you want to install. Select the version you want to install from the *Version to install* dropdown menu. The newest version is selected by default. A text field below the dropdown menu shows the changelog of the currently selected version. Click on the *Install* button to install the selected version. +
→ The plugin will be installed and is then available in the plugin overview of the plugin set. The overview shows all currently installed plugins.

[.instruction]
Activating plugins:

. To activate a plugin, under *Active*, click on the *Not active* button associated with the plugin. +
→ Activated plugins will be loaded for the selected plugin set in both the front end and back end.

[.instruction]
Setting the position of plugins:

. To set the position of a plugin, under *Action*, click on the *Set position* button associated with the plugin. +
→ The *Plugin position* window will open. Enter the position you want to assign the plugin in the text field and click on *Save*.
→ The position of the plugin will be updated.

[TIP]
.Position of plugins
====
A plugin’s relative position determines the order in which plugins of the plugin set are loaded.  Plugins with a lower position will be loaded earlier. That is why you should set the IO plugin to the highest position and the Ceres plugin to the second highest.
====

[.instruction]
Previewing plugin sets:

. Click on *Plugin set preview*.
. Select the online store that you want to preview. Before previewing a plugin, it set has to be deployed by clicking the *Save & deploy plugin set* button. +
→ The selected online store and its selected plugin set open in a new browser tab.

[.instruction]
Linking plugin sets:

. Click on *Link plugin sets*. +
→ The *Link plugin sets* window opens.
. Select the plugin set you want to use for your online store.
. *Save* the settings.

[TIP]
.Linking plugin sets
====
Linking a plugin set to a client makes all plugins of that plugin set public. This happens immediately. You should test the plugin set thoroughly and utilize the preview function before publishing it.
====

[#updating-plugins]
=== Updating plugins

[.instruction]
Copying a plugin set:

. Go to *Plugins » Plugin overview*.
. Click on *Add*. +
→ The *New plugin set* window opens.
. Enter a name for the plugin set.
. Select a plugin set from the *Copy plugin set* dropdown menu to copy that plugin set's settings.
. *Save* the settings.

[.instruction]
Updating plugins:

. If there is an update for a plugin, the *Update* button associated with the plugin under *Action* will be highlighted. Click this button to update the plugin. +
→ A new window opens, allowing you select the version you want to install. Select the version you want to install from the *Version to install* dropdown menu. The newest version is selected by default. A text field below the dropdown menu shows the changelog of the currently selected version. Click on the *Install* button to install the selected version. +
→ The plugin will be updated.

[.instruction]
Setting the position of plugins:

. To set the position of a plugin, under *Action*, click on the *Set position* button associated with the plugin. +
→ The *Plugin position* window will open. Enter the position you want to assign the plugin in the text field and click on *Save*.
→ The position of the plugin will be updated.

[TIP]
.Position of plugins
====
A plugin’s relative position determines the order in which plugins of the plugin set are loaded.  Plugins with a lower position will be loaded earlier. That is why you should set the IO plugin to the highest position and the Ceres plugin to the second highest.
====

[.instruction]
Previewing plugin sets:

. Click on *Plugin set preview*.
. Select the online store that you want to preview. Before previewing a plugin, it set has to be deployed by clicking the *Save & deploy plugin set* button. +
→ The selected online store and its selected plugin set open in a new browser tab.

[.instruction]
Linking plugin sets:

. Click on *Link plugin sets*. +
→ The *Link sets* window opens.
. Select the plugin set you want to use for your online store.
. *Save* the settings.

[TIP]
.Linking plugin sets
====
Linking a plugin set to a client makes all plugins of that plugin set public. This happens immediately. You should test the plugin set thoroughly and utilize the preview function before linking it.
====

[#removing-plugins]
=== Removing plugins

There are two ways to remove a plugin’s functionality from a plugin set. When you deactivate a plugin, it remains part of the set and you can activate it again at a later point without having to reinstall it. When you delete a plugin, it is removed from the set completely.

[#deactivating-plugins]
==== Deactivating plugins

[.instruction]
Copying a plugin set:

. Go to *Plugins » Plugin overview*.
. Click on *Add*. +
→ The *New plugin set* window opens.
. Enter a name for the plugin set.
. Select a plugin set from the *Copy plugin set* dropdown menu to copy that plugin set's settings.
. *Save* the settings.

[.instruction]
Deactivating plugins:

. To deactivate a plugin, under *Active*, click on the *Active* button associated with the plugin. +
→ Deactivated plugins will not be loaded for the selected plugin set in both the front end and back end.

[.instruction]
Previewing plugin sets:

. Click on *Plugin set preview*.
. Select the online store that you want to preview. Before previewing a plugin, it set has to be deployed by clicking the *Save & deploy plugin set* button. +
→ The selected online store and its selected plugin set open in a new browser tab.

[.instruction]
Linking plugin sets:

. Click on *Link plugin sets*. +
→ The *Link sets* window opens.
. Select the plugin set you want to use for your online store.
. *Save* the settings.

[TIP]
.Linking plugin sets
====
Linking a plugin set to a client makes all plugins of that plugin set public. This happens immediately. You should test the plugin set thoroughly and utilize the preview function before linking it.
====

[#deleting-plugins]
==== Deleting plugins

[.instruction]
Copying a plugin set:

. Go to *Plugins » Plugin overview*.
. Click on *Add*. +
→ The *New plugin set* window opens.
. Enter a name for the plugin set.
. Select a plugin set from the *Copy plugin set* dropdown menu to copy that plugin set's settings.
. *Save* the settings.

[.instruction]
Deleting plugins:

. To delete a plugin, under *Action*, click on the *Delete* button associated with the plugin. +
→ Deleted plugins will be removed from the plugin set.

[.instruction]
Previewing plugin sets:

. Click on *Plugin set preview*.
. Select the online store that you want to preview. Before previewing a plugin, it set has to be deployed by clicking the *Save & deploy plugin set* button. +
→ The selected online store and its selected plugin set open in a new browser tab.

[.instruction]
Linking plugin sets:

. Click on *Link plugin set*. +
→ The *Link sets* window opens.
. Select the plugin set you want to use for your online store.
. *Save* the settings.

[TIP]
.Linking plugin sets
====
Linking a plugin set to a client makes all plugins of that plugin set public. This happens immediately. You should test the plugin set thoroughly and utilize the preview function before linking it.
====

[#deleting-plugin-sets]
== Deleting plugin sets

[.instruction]
Deleting plugin sets:

. Go to *Plugins » Plugin overview*.
. Click on the *Delete plugin set* button associated with the plugin set you want to delete. +
→ The *Delete plugin set* window opens.
. Confirm the deletion. +
→ The plugin set will be deleted.

[#activating-back-end-plugin-set]
== Activating a back end plugin set

You can use active plugins in a plugin set not only to add additional features to your store, but also to add new menu items or user interfaces to your back end. Every user can select their own back end plugin set to load the plugins the set contains for their own back end. This is useful if some of your employees only need to be able to access certain functionality, but not all. If you want to change the plugin set for your back end view, proceed as follows.

[.instruction]
Selecting a back end plugin set:

. In the plentyMarkets back end, click on the account symbol in the upper right corner.
. Click on *Backend plugin set*. +
→ The *Backend plugin set* window opens.
. Click on a plugin set.
. *Save* the settings.
→ The selected plugin set is now active in your back end.

[#plugin-configuration]
== Plugin configuration

After installing a plugin, you might want to configure it. Depending on the plugin, you will have one of two options. Either, when clicking on the name of the plugin in the plugin set, a window with configuration options opens, or a new interface is added to the *System* menu when installing the plugin. Any options you change within a plugin set only applies to that specific set. Any options you change in the *System* menu apply globally and affect all plugin sets, even when installing the plugin in a set at a later time.

[NOTE]
.Exceptions
====
For plugins developed before the introduction of plugin sets, configuration may be different.
====

[#container-links]
== Container links

If a plugin adds new elements to your webshop, such as the logo of a payment method, certain services must be linked to so-called containers.

By default, you can configure container links in the *CMS* >> *Container links* menu, but plugin developers can also provide a set of default containers which you can then select in the plugin detail view all at once.

[.instruction]
Select default container links:

. Go to *Plugins* >> *Plugin Overview*.
. Open the plugin detail view of the plugin you want to link by clicking on that plugin’s name.
. Click on the Default container links button.
. Check the checkboxes of the containers you want to link.
. Save the settings.

You can check if it is possible to link containers this way in the plugin's item view on plentyMarketplace.

[WARNING]
.Does not overwrite existing links
====
Saving the default container links does not overwrite existing links. If you want to use only the default container links, you must first delete all links in the *CMS* >> *Container links* menu.
====