= Managing plugins
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plugins, extensions, features
:description: How to manage plugins in the plentymarkets back end.
:position: 40

Manage and deploy plugins that you purchased on the link:https://marketplace.plentymarkets.com/[plentyMarketplace^] or your own developed plugins in the **Plugins** menu. Install new plugins, change the state of existing plugins or delete plugins. Find out how to create your own plugins on link:http://developers.plentymarkets.com/[plentyDevelopers^].

[NOTE]
.Plugin functionalities are extended continuously
====
The plentymarkets plugin module and the possibilities for editing plugins are extended continuously. The number of available plugins will increase over time.
====

[#10]
== Purchasing marketplace plugins

The *plentyMarketplace* is our platform for distributing software extensions for plentymarkets developed by plentymarkets or external authors. This platform makes plugins easily accessible and ensures that you can benefit from the advantages the new technology offers. Proceed as described below to purchase a plugin.

[.instruction]
Purchasing a plugin:

. Go to the link:http://marketplace.plentymarkets.com/de/[plentyMarketplace^].
. Click on *Login*.
. Enter your email address or your plentyID. +
→ Use your access data that you also use for the service center.
. Enter your password.
. Click on *Login*.
. Select a plugin from a category.
. Click on *Buy plugin* in the detail view of the plugin. +
→ The checkout window will open. +
. Accept the terms and conditions.
. Click on *Order now*. +
→ The purchased plugin is now available in the *Plugins » Plugin overview* menu.

[TIP]
.Using filters
====
Use filters, for example to display only plugins in the plugin overview which are *Not installed*. To do so, select the filter *Not installed* from the drop-down list *Installed*. Click on *Search*.
For further information about filters, refer to the chapter <<en/basics/first-steps/plugins#80, Searching for specific plugins>>.
====

[#20]
== Plugin overview - Mananging Plugin Sets

[.instruction]
Managing Plugin Sets:

What is a Plugin Set? +
A Plugin Set is a named container for plugins. +
It can contain one or more plugins. +
It contains plugin configurations and layout containers. +
It can be activated for one or more webstores.

[#30]
=== Creating Plugin Sets

[.instruction]
Creating Plugin Sets:

. Go to *Plugins » Plugin overview*.
. Click on *Add*. +
→ The window *Create a plugin set* will open.
. Enter the name for the Plugin Set.
. You can copy an existing Plugin Set by clicking on *Copy Plugin Set*.
. *Save* the settings.

[#40]
=== Editing Plugin Sets

[.instruction]
Editing Plugin Sets:

. Go to *Plugins » Plugin overview*.
. Click on *Edit* on one of the Plugin Sets. +
→ The window *Edit Plugin Set* will open.
. Edit the name of the Plugin Set.
. *Save* the settings.

[#50]
=== Deleting Plugin Sets

[.instruction]
Deleting Plugin Sets:

. Go to *Plugins » Plugin overview*.
. Click on *Delete* on one of the Plugin Sets. +
→ The window *Delete Plugin Set* will open.
. *Confirm* the deletion. +
→ The Plugin Set is deleted.

[#60]
=== Previewing Plugin Sets

[.instruction]
Previewing Plugin Sets:

. Go to *Plugins » Plugin overview*.
. Click on one of the Plugin Sets. +
→ The window *Plugin set details* will open.
. Click on *Plugin set preview*.
. Select the online store you would like to preview. The selected plugin set must be deployed beforehand by clicking the button *Save & deploy plugin set*. +
→ The chosen online store and Plugin Set are displayed in a new browser tab.

[#70]
=== Activating Plugin Sets

Activating a Plugin Set for an online store will publish all plugins in the Plugin Set. This will take effect immediately. +
Make sure the chosen Plugin Set is thoroughly tested and previewed beforehand.

[.instruction]
Activating Plugin Sets:

. Go to *Plugins » Plugin overview*.
. Click on *Activate Plugin Set*. +
→ The window *Activate Plugin Set* will open.
. Select a Plugin Set for each webstore.
. *Save* the settings.

[#80]
=== Searching for specific plugins

To search for specific plugins, you can set a filter. It is possible to filter by name, source, installed or non-installed and active or inactive plugins.

[.instruction]
Searching for specific plugins:

. Go to *Plugins » Plugin overview*.
. Select a filter.
. Enter the name of the plugin or select one of the options given in the drop-down menu.
. Click on *Search*. +
→ The desired plugins are displayed.

[#90]
=== Managing Plugins

In the *Plugins » Plugin overview*, click on the Plugin Set you would like to manage. +
The plugins listed in the view contain the following information:


[[table-plugin-overview]]
.Table view of the menu **Plugins » Plugin overview**
[cols="1,3"]
|====
|Column |Explanation

|*Active*
|Shows whether the plugin is active or inactive.

|*Name*
|Name of the plugin

|*Version installed*
|The version of the plugin is installed, but not active.

|*Version active*
|The version of the plugin is active and will be loaded in the frontend and backend.

|*Source*
|The plugin source, e.g., *Git* or *plentyMarketplace*.

|*Action*
|*Update*: If an update is available, you can update the plugin to the latest version. +
 *Position*: Defines the load order of plugins. If a plugin doesn't work properly, it might help to change the position to a higher number. +
 *Delete*: Deletes the plugin from the Plugin Set. +
 *Install*: Installs the plugin.
|====

[#100]
== Plugin set back end switch

Plugins can add back end functionality like menu items and user interfaces. You can change the plugin set which is loaded for your back end. In order to do this, you need to pick a plugin set for your user.

[.instruction]
Picking a plugin set for your user:

. Click on the user icon on the top right of the plentymarkets back end.
. Click on *Back end plugin set*. +
→ The window *Plugin set* will open.
. Click on a plugin set.
. *Save* the settings.

[#110]
== Adding own Git plugins

Alternatively to plugins from plentyMarketplace you can add own plugins to the interface of your plentymarkets system. To add a plugin to plentymarkets that is managed by the <<basics/first-steps/plugins#90, Git versioning>>, proceed as follows.

[.instruction]
Adding a Git repository to the plentymarkets surface:

. Go to *Plugins » Git*.
. On the left, click on *Add new repository*. +
→ The options for the repository settings are displayed.
. Enter the necessary information for the Git repository. Pay attention to the information given in <<table-adding-git-plugins>>.
. *Save* the settings. +
→ The connection to the Git repository is checked and established. The success message *Repository saved* appears.

[[table-adding-git-plugins]]
.Adding Git plugins
[cols="1,3"]
|====
|Setting |Explanation

|*Repository URL*
|HTTPS or HTTP URL of the Git repository

|*User name*
|The user name is part of the user data of the provider (e.g. GitHub) for the Git repository. +
For public repositories, enter a value into the field, e.g. *guest*.

|*Password or token*
|The password is part of the user data of the provider (e.g. GitHub) for the Git repository. +
For public repositories, enter a value into the field, e.g. *guest*. +
If the two factor authentification has been activated, a token is needed.

|*Branch name*
|The Git repository has to include a valid Plugin.json. The input is needed for the initial installation.
|====


=== Deleting a Git repository

In the menu *Plugins » Git*, repositories can be deleted by clicking the *Delete* button. However, this is only possible if the plugin has been deactivated in all plugin sets.
