= System requirements
:lang: en
include::{includedir}/_header.adoc[]
:position: 10

On this page the requirements are listed that your PC and your internet connection need to fulfil, if you wish to use plentymarkets.

==  Required hardware, operating systems and browsers

The following requirements allow you to work efficiently with plentymarkets. The system's performance may be limited if you do not meet the specified values. You may have permanent performance problems if you are using old hardware or a PC that has been poorly maintained. These requirements are for plentymarkets version 6 and higher.

[cols="a,a"]
|====
| | Requirement

|**Processor**
| 2 x 2 GHz +
If you are working with a windows operating systems, you need at least an Intel Core 2 processor.

|**Memory**
| 4 GB

|**Resolution**
| 1280 x 720

|**Internet connection**
| we recommend using a permanent DSL Internet connection with a data transfer rate of at least 1000 kB +
**Note:** The transfer rate should needs to match the number of users.
|====

__Table 1: General requirements__

===  Using plentymarkets in a browser

The following table lists requirements that need to be fulfilled if you are working with plentymarkets in a browser. The performance may be limited if you do not meet the specified values. You also need to comply with the requirements given in table 1.

[cols=""]
|====
| | Requiretment

|**Operating system**
a| 64 bit
*  Windows 7 or a higher version
*  Mac OS X 10.10 or a higher versions
*  Linux

**Info:** The performance may be limited if you are using other operating systems, server operating systems or virual machines.

|**Browser**
a|
* link:http://www.google.com/chrome/[**Google Chrome**^] version 46 or higher
* link:http://www.mozilla.com/[**Mozilla Firefox**^] version 43 or higher

|====

__Table 2: requirements for working in a browser__

These browser requirements do not apply to your customers. Your customers can use a W3C compliant web browser of their choice in order to purchase items in your store.

===  Using the plentymarkets Client

You need to comply with the following requirements if you want to work with the plentymarkets Client. You also need to comply with the requirements listed in table 1.

[cols=""]
|====
| | Requirement

|**Operating system**
a| 64-Bit
*  Windows 7 or a higher version
*  Mac OS X 10.10 or a higher versions

**Info:** You can not use the plentymarkets Client if you are working with Linux. +
**Info:** The performance may be limited if you are using other operating systems, server operating systems or virual machines.
|====

__Table 3: requirements for using the plentymarkets Client__

===  Using the plentymarkets app

The hardware that supports the plentymarkets app is listed in table 4.

[cols=""]
|====
| | Requirement

|**Operating system**
a|
*  Android devices with version 4.2.2 or higher
*  iOS devices with version 8 or higher

|====

__Table 4: requirements for using the plentymarkets app__

==  Troubleshooting

The following points can cause problems if you are working with plentymarkets.

*  Your Browser ist not up-to-date. Check your browser's version and if a newer one is available, update your browser.
*  Your CPU is busy. If your CPU is already running at full capacity due to normal operating procedures, then you should close programmes that you do not need at the time.
*  Your memory is too small. Check the size of your memory. We recommend a minimum capacity of 4 GB.
*  Your Java version ist not up-to-date. Check the Java version installed on your computer and whether or not a newer one is available, update your browser. Install the current version
*  Your hard drive is more than 70% full and has not been switched out in years. Depending on the operating system and the quality of the hardware, you will be able to notice a significant decrease in performance after more than two years. Delete any unnecessary files or reinstall the system. Another cost-effective solution would be to purchase a newer and more powerful hard drive/SSD.
