= IT-Recht Kanzlei
:lang: en
include::{includedir}/_header.adoc[]
:position: 160

[NOTE]
.Old: CMS & online store
====
This manual page describes functions that pertain to the old plentymarkets online shop *Callisto*. For information regarding the online store template *Ceres*, please refer to the <<omni-channel/online-store/setting-up-ceres#, Setting up Ceres page>>.
====

Please note that the link:http://www.it-recht-kanzlei.de/schutzpakete.html[IT-Recht Kanzlei^] offers its services in German only. They provide an update service for your online store's <<omni-channel/online-store/setting-up-clients/online-store#legal-information, legal texts>> to ensure that these texts are always up to date.

== Setting up a user account

Your plentymarkets system will be connected to the IT-Recht Kanzlei via the SOAP interface, i.e. you require the SOAP module. In order for it to have access, this service requires its own user account with access rights to the API in your system.

[.instruction]
Creating a new user:

. Go to *System » Settings » User » Accounts*.
. Click on *New*. +
→ The editing window *Create new user* will appear.
. Enter the *user name*, the *real name* and the *password*.
. Repeat the password.
. Enter the user's email address. This will allow the user to receive messages from the system.
. Select the user class *API* or *Variable*.
. *Save* the settings.

The following calls must be activated for the user:

* GetServerTime
* GetPlentyMarketsVersion
* GetMultiShops
* GetTermsAndCancellation
* SetTermsAndCancellation
* GetLegalInformation
* SetLegalInformation

For further information, refer to the <<omni-channel/online-store/setting-up-clients/extras/it-recht-kanzlei#, Introduction to the SOAP API>> page of the manual.

== Automatically transferring legal texts

For IT-Recht Kanzlei to automatically transfer legal texts, set up a data interface in your IT-Recht Kanzlei account. The IT-Recht Kanzlei needs to have the following information from you in order to connect to your system:

* Login details, user name and password
* URL for the SOAP API WSDL +
This URL can be found in the *System » Settings » API » Data* menu under <<basics/data-exchange/api-data#, SOAP WSDL>>.
