= Gelangensbestätigungen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Gelangensbestätigung, Gelangensbestätigungen erzeugen, Fulfillment, Auftragsdokumente, Auftragsabwicklung, Lieferung, Auslandslieferung
:position: 80
:url: auftraege/auftragsdokumente/gelangensbestaetigung-erzeugen

In plentymarkets können Sie Gelangensbestätigungen als PDF-Dateien generieren, um diese z.B. zu drucken oder Ihren Kunden als E-Mail Anhang zukommen zu lassen. +
Bei Lieferungen von Deutschland in ein anderes EU-Land ist die Ausstellung von Gelangensbestätigungen vorgeschrieben. Empfänger bestätigen beispielsweise mittels Unterschrift auf der Gelangensbestätigung und die anschließende Rückübermittlung den erfolgten Wareneingang im jeweiligen EU-Land. +
Somit ist die Gelangensbestätigung nicht nur ein Begleitdokument bei Auslandslieferungen, sondern auch ein steuerrechtlich relevanter Beleg für Ihre Buchhaltung.

[#100]
== Dokumentenvorlage für Gelangensbestätigungen einrichten

Bevor Sie Gelangensbestätigungen generieren können, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü **System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente**. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage finden Sie auf der Handbuchseite <<auftraege/auftragsdokumente#, Auftragsdokumente>>.

[#200]
== Einzelne Gelangensbestätigung erzeugen

Eine einzelne Gelangensbestätigung können Sie in plentymarkets bei Bedarf manuell am Auftrag erzeugen.

[.instruction]
Einzelne Gelangensbestätigung erzeugen:

. Öffnen Sie das Menü **Aufträge » Aufträge bearbeiten**. +
→ Die Auftragsübersicht öffnet sich.
. Wählen Sie durch Klick auf die **Auftrag-ID** den Auftrag aus, für den eine Gelangensbestätigung erzeugt werden soll. +
. Wechseln Sie in das Tab **Belege**. +
. Wählen Sie im Drop-Down-Menü **Beleg erstellen** das Dokument **Gelangensbestätigung** aus. +
. Nehmen Sie die Einstellungen anhand <<tabelle-auftraege-belege-gelangensbestaetigung>> vor. +
. **Speichern** Sie die Einstellungen, um die Gelangensbestätigung zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei** mit der soeben erzeugten Gelangensbestätigung.

[[tabelle-auftraege-belege-gelangensbestaetigung]]
.Optionen im Menü *Beleg erstellen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Datum**
|Datum wählen, das auf der Gelangensbestätigung angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

|**Nummer**
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

|**Buche Warenausgang**
|Mit **JA** oder **NEIN** auswählen, ob mit dem Erzeugen der Gelangensbestätigung auch der Warenausgang gebucht werden soll.

|**Ändere Auftragsstatus auf Status**
|Einen Status wählen, in den der Auftrag nach dem Erzeugen der Gelangensbestätigung wechseln soll. Wenn kein Statuswechsel gewünscht ist, die Option **Keine Änderung** wählen.

|**Kommentar**
|Einen Text eingeben, der auf der Gelangensbestätigung unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====

[#300]
== Mehrere Gelangensbestätigungen erzeugen

Sollen mehrere Gelangensbestätigungen zugleich erzeugt werden, können Sie über einen Suchfilter im Menü **Aufträge » Fulfillment** festlegen, welche Aufträge berücksichtigt werden. Zudem können Sie in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Gelangensbestätigungen erzeugt wurden.

[.instruction]
Mehrere Gelangensbestätigungen erzeugen:

. Öffnen Sie das Menü **Aufträge » Fulfillment » Gelangensbestätigung erzeugen**.
. Nehmen Sie die Einstellungen anhand <<tabelle-einstellungen-fulfillment-gelangensbestaetigung>> vor.
. Klicken Sie auf das **Zahnrad**, um die Gelangensbestätigungen zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei**, in der die zugehörigen Gelangensbestätigungen aller von Ihnen durch die Suchfilter bestimmten Aufträge enthalten sind.

[[tabelle-einstellungen-fulfillment-gelangensbestaetigung]]
.Optionen im Menü *Gelangensbestätigung erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Auftragsstatus**
|Aus der Liste den Status der Aufträge wählen, die für die Erstellung der Gelangensbestätigungen berücksichtigt werden sollen.

|**Eigner**
|Wählen Sie einen Eigner aus, für dessen Aufträge die Gelangensbestätigungen erzeugt werden sollen oder die Option **ALLE**, wenn für alle Eigner die Gelangensbestätigungen erzeugt werden sollen.

|**Standort**
|Wählen Sie einen Standort aus, für den die Gelangensbestätigungen erzeugt werden sollen.

|**Lager**
|Wählen Sie ein Lager oder **ALLE** aus.

|**Zahlungsart**
|Wählen Sie eine der Zahlungsarten oder *ALLE* aus.

|**Sortierung**
|Legen Sie fest, wie die erzeugten Gelangensbestätigungen sortiert werden sollen. Die Optionen **Auftrags-ID**, **Kunden-ID** und **Artikel-ID** geben verschiedene Sortierungen aus.

|**Limit**
|Legen Sie fest, wie viele Gelangensbestätigungen maximal pro Durchgang erzeugt werden. Das Maximum liegt bei *200* Gelangensbestätigungen.

|**Ändere Auftragsstatus**
|Wählen Sie einen Status, in den die Aufträge nach Erzeugung der Gelangensbestätigunen wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

|**Kommentar**
|Sie können hier einen Text verfassen, der später auf allen erzeugten Gelangensbestätigungen unterhalb der Artikelpositionen erscheint. Die Eingabe ist optional.
|====
