= Gutschriften
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Gutschrift, Gutschriften erzeugen, Korrekturbeleg, Korrekturbelege erzeugen
:position: 20
:url: auftraege/auftragsdokumente/gutschriften-erzeugen

In plentymarkets kannst du Gutschriften als PDF-Dateien generieren, um diese z.B. zu drucken oder deine Kunden als E-Mail Anhang zukommen zu lassen. +
Gutschriften nutzt du beispielsweise, um bei bereits bezahlten Aufträgen nachträgliche Preisnachlässe zu gewähren oder wenn im Rahmen von Retouren Rückerstattungen veranlasst werden sollen.

[NOTE]
.Standardeinstellungen für Gutschriften
====
Nimm im Menü **System » Systemeinstellungen » Aufträge » Einstellungen** einmalig die gewünschten Standardeinstellungen zu Gutschriften vor und speichere diese ab. Nur so werden die Einstellungen zum Standard-Status von Gutschriften und zur Übernahme der Versandkosten in Gutschriften wirksam. Weitere Informationen zu den Grundeinstellungen für Aufträge findest du auf der Handbuchseite zum Thema <<auftraege/grundeinstellungen#, Grundeinstellungen>>.
====

[#200]
== Dokumentenvorlage für Gutschriften einrichten

Bevor du Gutschriften generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü **System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente**. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite <<auftraege/auftragsdokumente#, Auftragsdokumente>>.

[#300]
== Einzelne Gutschrift erzeugen

Einzelne Gutschriften kannst du bei Bedarf manuell am jeweiligen Gutschriftauftrag erzeugen. Weitere Informationen und Anleitungen zum Anlegen von Gutschriftaufträgen findest du im Kapitel <<auftraege/auftraege-verwalten#500, Gutschrift anlegen>>.

[.instruction]
Einzelne Gutschrift erzeugen:

. Öffne das Menü **Aufträge » Aufträge bearbeiten**. +
→ Die Auftragsübersicht öffnet sich.
. Wähle durch Klick auf die **Auftrag-ID** den Gutschriftauftrag, für den eine Gutschrift erzeugt werden soll.
. Wechsle in das Tab **Belege**. +
. Wähle im Drop-Down-Menü **Beleg erstellen** das Dokument **Gutschrift** aus. +
. Nimm die Einstellungen anhand <<tabelle-gutschriftauftrag-belege-gutschrift>> vor.
. **Speichere** die Einstellungen, um die Gutschrift zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei** mit der soeben erzeugten Gutschrift.

[[tabelle-gutschriftauftrag-belege-gutschrift]]
.Optionen im Menü *Beleg erstellen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Datum**
|Datum wählen, das auf der Gutschrift angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

|**Nummer**
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

|**Ändere Auftragsstatus auf Status**
|Einen Status wählen, in den der Auftrag nach dem Erzeugen der Gutshrift wechseln soll. Wenn kein Statuswechsel gewünscht ist, die Option **Keine Änderung** wählen.

|**Kommentar**
|Einen Text eingeben, der auf der Gutschrift unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====

[#400]
== Mehrere Gutschriften erzeugen

Sollen mehrere Gutschriften zugleich erzeugt werden, kannst du über einen Suchfilter im Menü **Aufträge » Fulfillment** festlegen, welche Aufträge berücksichtigt werden. Zudem kannst du in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Gutschriften erzeugt wurden.

[.instruction]
Mehrere Gutschriften erzeugen:

. Öffne das Menü **Aufträge » Fulfillment » Gutschriften / Korrekturbelege erzeugen**.
. Nimm die Einstellungen anhand <<tabelle-einstellungen-fulfillment-gutschriften>> vor.
. Klicke auf das **Zahnrad**, um die Gutschriften zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei**, in der die zugehörigen Gutschriften aller von dir durch die Suchfilter bestimmten Aufträge enthalten sind.

[[tabelle-einstellungen-fulfillment-gutschriften]]
.Optionen im Menü *Gutschriften / Korrekturbelege erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Dokumenttyp**
|Wähle, ob Dokumente vom Typ *Gutschrift* oder *Korrekturbeleg* erzeugt werden sollen.

|**Auftragsstatus**
|Aus der Liste den Status der Aufträge wählen, die für die Erstellung der Gutschriften berücksichtigt werden sollen.

|**Eigner**
|Wähle einen Eigner aus, für dessen Aufträge die Gutschriften erzeugt werden sollen oder die Option **ALLE**, wenn für alle Eigner die Gutschriften erzeugt werden sollen.

|**Standort**
|Wähle einen Standort aus, für den die Gutschriften erzeugt werden sollen.

|**Lager**
|Wähle ein Lager oder **ALLE** aus.

|**Zahlungsart**
|Wähle eine der Zahlungsarten oder *ALLE* aus.

|**Sortierung**
|Lege fest, wie die erzeugten Gutschriften sortiert werden sollen. Die Optionen **Gutschriftnummer**, **Auftrags-ID**, **Kunden-ID** und **Artikel-ID** geben verschiedene Sortierungen aus.

|**Limit**
|Lege fest, wie viele Gutschriften maximal pro Durchgang erzeugt werden. Das Maximum liegt bei *200* Gutschriften.

|**Ändere Auftragsstatus**
|Wähle einen Status, in den die Aufträge nach Erzeugung der Gutschriften wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

|**Kommentar**
|Du kannst hier einen Text verfassen, der später auf allen erzeugten Gutschriften unterhalb der Artikelpositionen erscheint. Die Eingabe ist optional.
|====
