= Korrekturbelege
:lang: de
include::{includedir}/_header.adoc[]
:position: 20
:url: auftraege/auftragsdokumente/korrekturbeleg-erzeugen
:id: U8ZHVGR
:keywords: Korrekturbeleg, Korrekturbeleg erzeugen, Auftragsdokumente, Auftragsabwicklung, Dokumentenvorlage, Vorlage, Mandant, Standort, Auftrag, Nummer, Dokumentennummer, Beleg, Dokumententyp, Dokument, PDF, PDF-Vorlage, PDF-Datei, korrigieren, Gutschrift, Gutschriftauftrag
:author: team-order-payment

Einen Korrekturbeleg nutzt du, wenn eine Korrektur für einen Auftrag notwendig ist. Stell dir zum Beispiel vor, du kannst dem Kunden nur zwei von seinen drei bestellten Artikelpositionen zusenden. Du teilst dies deinem Kunden mit und er möchte das Geld für den fehlenden Artikel erstattet bekommen. Was machst du? Du legst zu diesem Auftrag einen <<auftrage/auftraege-verwalten#500, Auftragstyp Gutschrift>> an, damit der Vorgang technisch im System abgebildet ist. Erst dann ist es möglich in diesem Auftragstyp Gutschrift einen Korrekturbeleg zu erstellen. Du kannst entweder einen einzelnen oder mehrere Korrekturbelege erzeugen. Erstelle PDF-Dateien, um diese z.B. zu drucken oder deinen Kunden als E-Mail-Anhang zukommen zu lassen.

[#100]
== Dokumentenvorlage für Korrekturbelege einrichten

Bevor du Korrekturbelege generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » _Mandant wählen_ » Standorte » _Standort wählen_ » Dokumente » Korrekturbeleg*. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite <<auftraege/auftragsdokumente#, Auftragsdokumente>>.

[#200]
== Einzelnen Korrekturbeleg erzeugen

Korrekturbelege können nur für den Auftragstypen *Gutschrift* erzeugt werden. Um einen einzelnen Korrekturbeleg manuell aus einem bestimmten Gutschriftaustrag zu erzeugen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Einzelnen Korrekturbeleg erzeugen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die Auftragsübersicht öffnet sich.
. Wähle durch Klick auf die *Auftrag-ID* den Gutschriftauftrag aus, für den ein Korrekturbeleg erzeugt werden soll. +
. Wechsle in das Tab *Belege*. +
. Wähle aus der  Dropdown-Liste *Beleg erstellen* das Dokument *Korrekturbeleg* aus. +
. Nimm die Einstellungen anhand <<tabelle-korrekturbeleg-erzeugen>> vor. +
. *Speichere* (icon:plus-square[role="green"]) die Einstellungen, um den Korrekturbeleg zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei* mit dem soeben erzeugten Korrekturbeleg.

[[tabelle-korrekturbeleg-erzeugen]]
.Optionen im Tab *Belege*
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Datum*
|Datum wählen, das auf dem Korrekturbeleg angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

| *Nummer*
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

| *Ändere Auftragsstatus auf Status*
|Einen Status wählen, in den der Gutschriftauftrag nach dem Erzeugen des Korrekturbelegs wechseln sollen. Wenn kein Statuswechsel gewünscht ist, die Option *Keine Änderung* wählen.

| *Kommentar*
|Einen Text eingeben, der auf dem Korrekturbeleg unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====

[#300]
== Mehrere Korrekturbelege erzeugen

Sollen mehrere Korrekturbelege zugleich erzeugt werden, legst du über Suchfilter im Menü *Aufträge » Fulfillment* fest, welche Gutschriftaufträge berücksichtigt werden. Zudem kannst du in diesem Menü bestimmen, ob der Status des Gutschriftauftrags geändert werden soll, nachdem die Korrekturbelege erzeugt wurden.

[.instruction]
Mehrere Korrekturbelege erzeugen:

. Öffne das Menü *Aufträge » Fulfillment » Gutschriften / Korrekturbelege erzeugen*.
. Nimm die Einstellungen anhand <<tabelle-einstellungen-fulfillment-korrekturbelege>> vor. +
_Beachte_, dass die Einstellungen sowohl *Suchfilter* als auch *Aktionen* umfassen.
. Klicke auf das *Zahnrad* (icon:cog[]), um den Korrekturbeleg zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei*, in der die zugehörigen Korrekturbelege aller von dir durch die Suchfilter bestimmten Gutschriftaufträge enthalten sind.

[[tabelle-einstellungen-fulfillment-korrekturbelege]]
.Optionen im Untermenü *Gutschriften / Korrekturbelege erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Dokumenttyp*
|Wähle aus der Dropdown-Liste *Korrekturbeleg* aus.

| *Auftragsstatus*
|Wähle aus der Dropdown-Liste den Status der Gutschriftaufträge aus, die für die Korrekturbelege berücksichtigt werden sollen.

| *Eigner*
|Wähle einen Eigner aus, für dessen Aufträge die Korrekturbelege erzeugt werden sollen oder die Option *ALLE*, wenn für alle Eigner die Korrekturbelege erzeugt werden sollen.

| *Standort*
|Wähle einen Standort aus, für den die Korrekturbelege erzeugt werden sollen.

| *Lager*
|Wähle ein Lager oder *ALLE* aus.

| *Zahlungsart*
|Wähle eine der Zahlungsarten oder die Option *ALLE*.

| *Sortierung*
|Lege fest, wie die erzeugten Korrekturbelege sortiert werden sollen. Die Optionen *Gutschriftennummer*, *Auftrags-ID*, *Kunden-ID* und *Artikel-ID* geben verschiedene Sortierungen aus.

| *Limit*
|Lege fest, wie viele Korrekturbelege maximal pro Durchgang erzeugt werden. Das Maximum liegt bei *200* Korrekturbelegen.

| *Ändere Auftragsstatus* (Aktion)
|Wähle einen Status, in den die Gutschriftaufträge nach Erzeugung der Korrekturbelege wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

| *Kommentar*
|Einen Text eingeben, der auf den Korrekturbelegen unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====
