= Reparaturscheine
:lang: de
include::{includedir}/_header.adoc[]
:position: 80
:url: auftraege/auftragsdokumente/reparaturschein-erzeugen
:id: 7K9NLOI
:keywords: Reparaturschein, Reparaturschein erzeugen, Auftragsdokumente, Auftragsabwicklung, Dokumentenvorlage, Vorlage, Mandant, Standort, Auftrag, Nummer, Dokumentennummer, Beleg, Dokumententyp, Dokument, PDF, PDF-Vorlage, PDF-Datei, Reparatur, Reparaturauftrag. reparaturbedürftig, retourniert, Retoure
:author: team-order-payment

Reparaturscheine nutzt du im Zusammenhang mit dem <<auftraege/auftraege-verwalten#700, Auftragstyp Reparatur>>. Reparaturen und Reparaturscheine sind also immer retournierter, reparaturbedürftiger Ware zugeordnet. Daher lassen sich Reparaturscheine auch nur aus einem Reperaturauftrag heraus erzeugen.

[#100]
== Dokumentenvorlage für Reparaturscheine einrichten

Bevor du Reparaturscheine generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dies geschieht im Menü *Einrichtung » Mandant » _Mandant wählen_ » Standorte » _Standort wählen_ » Dokumente » Reparaturschein*. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite <<auftraege/auftragsdokumente#, Auftragsdokumente>>.

[#200]
== Reparaturschein manuell erzeugen

Reparaturscheine können nur für den Auftragstypen *Reparatur* erzeugt werden. Um einen Reparaturschein manuell aus einem bestimmten Reparaturaustrag zu erzeugen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Reparaturschein manuell erzeugen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die Auftragsübersicht öffnet sich.
. Wähle durch Klick auf die *Auftrag-ID* den Reparaturauftrag aus, für den ein Reparaturschein erzeugt werden soll. +
. Wechsle in das Tab *Belege*. +
. Wähle aus der Dropdown-Liste *Beleg erstellen* das Dokument *Reparaturschein* aus. +
. Nimm die Einstellungen anhand <<tabelle-reparaturschein-erzeugen>> vor. +
. *Speichere* (icon:plus-square[role="green"]) die Einstellungen, um den Reparaturschein zu erzeugen. +
→ Es öffnet sich eine *PDF-Datei* mit dem soeben erzeugten Reparaturschein.

[[tabelle-reparaturschein-erzeugen]]
.Optionen im Tab *Belege*
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Datum*
|Datum wählen, das auf dem Korrekturbeleg angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

| *Nummer*
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

| *Buche Warenausgang*
|Mit *JA* oder *NEIN* auswählen, ob mit dem Erzeugen des Reparaturscheins auch der Warenausgang gebucht werden soll.

| *Ändere Auftragsstatus auf Status*
|Einen Status wählen, in den der Reparaturauftrag nach dem Erzeugen des Reparaturscheins wechseln sollen. Wenn kein Statuswechsel gewünscht ist, die Option *Keine Änderung* wählen.

| *Kommentar*
|Einen Text eingeben, der auf dem Korrekturbeleg unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====
