= Rücksendescheine
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Rücksendeschein, Rücksendescheine erzeugen, Fulfillment, Auftragsabwicklung, Auftragsdokumente, Rücksendung, Retoure
:position: 90

In plentymarkets können Sie Rücksendescheine als PDF-Dateien generieren, um diese z.B. zu drucken oder Ihren Kunden als E-Mail Anhang zukommen zu lassen. +
Somit können Ihre Kunden Rücksendescheine beispielsweise beim Umtausch von Artikeln oder bei Retouren einfach der Warensendung beilegen.

[#200]
== Dokumentenvorlage für Rücksendescheine einrichten

Bevor Sie Rücksendescheine generieren können, muss eine Dokumentenvorlage eingerichtet werden. Dokumentenvorlagen richten Sie im Menü **System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente** ein. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage finden Sie auf der Handbuchseite <<auftraege/auftragsdokumente#, Auftragsdokumente>>.

[#300]
== Einzelnen Rücksendeschein erzeugen

In manchen Fällen macht es Sinn, Rücksendescheine zu bestimmten Aufträgen manuell zu erzeugen. Dies geschieht sowohl für reguläre Aufträge als auch für Retourenaufträge in der Auftragsübersicht.

[#400]
=== Rücksendeschein am Hauptauftrag erzeugen

Einen einzelnen Rücksendeschein können Sie in plentymarkets bei Bedarf manuell direkt am Hauptauftrag erzeugen. Der so erzeugte Rücksendeschein beinhaltet dann alle im Auftrag enthaltenen Artikelpositionen. Nutzen Sie diese Methode, um jedem Paket, das Sie versenden, einen unausgefüllten Rücksendeschein beizulegen. Weitere Informationen hierzu finden Sie im Kapitel **<<auftraege/auftraege-verwalten#450, Rücksendeschein erstellen>>**.

[.instruction]
Rücksendeschein am Haupauftrag erzeugen:

. Öffnen Sie das Menü **Aufträge » Aufträge bearbeiten**. +
→ Die Auftragsübersicht öffnet sich.
. Wählen Sie durch Klick auf die **Auftrag-ID** den Auftrag aus, für den ein Rücksendeschein erzeugt werden soll. +
. Wechseln Sie in das Tab **Belege**. +
. Wählen Sie im Drop-Down-Menü **Beleg erstellen** das Dokument **Rücksendeschein** aus. +
. Nehmen Sie die Einstellungen anhand <<tabelle-auftraege-belege-ruecksendeschein>> vor. +
. **Speichern** Sie die Einstellungen, um den Rücksendeschein zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei** mit dem soeben erzeugten Rücksendeschein.

[[tabelle-auftraege-belege-ruecksendeschein]]
.Optionen im Menü *Beleg erstellen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Datum**
|Datum wählen, das auf dem Rücksendeschein angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

|**Nummer**
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

|**Ändere Auftragsstatus auf Status**
|Einen Status wählen, in den der Auftrag nach dem Erzeugen des Rücksendescheins wechseln soll. Wenn kein Statuswechsel gewünscht ist, die Option **Keine Änderung** wählen.

|**Kommentar**
|Einen Text eingeben, der auf dem Rücksendeschein unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====

[#500]
=== Rücksendeschein am Retourenauftrag erzeugen

Möchten Sie Ihren Kunden einen Rücksendeschein zur Verfügung stellen, z.B. wenn diese im Mein-Konto-Bereich des Webshops eine Retoure zu einem bestimmten Auftrag beantragen, erstellen Sie einen Rücksendeschein im dazugehörigen Retourenauftrag.

[.instruction]
Rücksendeschein am Retourenauftrag erzeugen:

. Öffnen Sie das Menü **Aufträge » Aufträge bearbeiten**. +
→ Die Auftragsübersicht öffnet sich.
. Wählen Sie durch Klick auf die **Auftrag-ID** den Retourenauftrag aus, für den ein Rücksendeschein erzeugt werden soll. +
. Wechseln Sie in das Tab **Belege**. +
. Wählen Sie im Drop-Down-Menü **Beleg erstellen** das Dokument **Rücksendeschein** aus. +
. Nehmen Sie die Einstellungen anhand <<tabelle-auftraege-belege-ruecksendeschein>> vor. +
. **Speichern** Sie die Einstellungen, um den Rücksendeschein zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei** mit dem soeben erzeugten Rücksendeschein.

[#600]
== Mehrere Rücksendescheine erzeugen

Sollen für mehrere Aufträge zugleich Rücksendescheine erzeugt werden, können Sie über einen Suchfilter im Menü **Aufträge » Fulfillment** festlegen, welche Aufträge berücksichtigt werden. Zudem können Sie in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Rücksendescheine erzeugt wurden.

[.instruction]
Mehrere Rücksendescheine erzeugen:

. Öffnen Sie das Menü **Aufträge » Fulfillment » Rücksendeschein erzeugen**.
. Nehmen Sie die Einstellungen anhand <<tabelle-einstellungen-fulfillment-ruecksendeschein>> vor.
. Klicken Sie auf das **Zahnrad**, um die Rücksendescheine zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei**, in der die zugehörigen Rücksendescheine aller von Ihnen durch die Suchfilter bestimmten Aufträge enthalten sind.

[[tabelle-einstellungen-fulfillment-ruecksendeschein]]
.Optionen im Menü *Rücksendeschein erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Auftragsstatus**
|Aus der Liste den Status der Aufträge wählen, die für das Erzeugen der Rücksendescheine berücksichtigt werden sollen.

|**Eigner**
|Wählen Sie einen Eigner aus, für dessen Aufträge die Rücksendescheine erzeugt werden sollen oder die Option **ALLE**, wenn für alle Eigner die Rücksendescheine erzeugt werden sollen.

|**Standort**
|Wählen Sie einen Standort aus, für den die Rücksendescheine erzeugt werden sollen.

|**Lager**
|Wählen Sie ein Lager oder **ALLE** aus.

|**Zahlungsart**
|Wählen Sie eine der Zahlungsarten oder *ALLE* aus.

|**Sortierung**
|Legen Sie fest, wie die erzeugten Rücksendescheine sortiert werden sollen. Die Optionen **Auftrags-ID**, **Kunden-ID** und **Artikel-ID** geben verschiedene Sortierungen aus.

|**Limit**
|Legen Sie fest, wie viele Rücksendescheine maximal pro Durchgang erzeugt werden. Das Maximum liegt bei *200* Rücksendescheinen.

|**Ändere Auftragsstatus**
|Wählen Sie einen Status, in den die Aufträge nach Erzeugung der Rücksendescheine wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

|**Kommentar**
|Einen Text eingeben, der auf allen Rücksendescheinen unterhalb der Artikelpositionen erscheint. Die Eingabe ist optional.
|====
