= Rücksendescheine
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Rücksendeschein, Rücksendescheine erzeugen, Fulfillment, Auftragsabwicklung, Auftragsdokumente, Rücksendung, Retoure
:position: 90
:url: auftraege/auftragsdokumente/ruecksendeschein-erzeugen

In plentymarkets generierst du Rücksendescheine als PDF-Dateien, um diese z.B. zu drucken oder deinen Kunden als E-Mail Anhang zukommen zu lassen. +
Somit können deine Kunden Rücksendescheine beispielsweise beim Umtausch von Artikeln oder bei Retouren einfach der Warensendung beilegen.

[#200]
== Dokumentenvorlage für Rücksendescheine einrichten

Bevor du Rücksendescheine generieren kannst, muss eine Dokumentenvorlage eingerichtet werden. Dokumentenvorlagen richtest du im Menü **System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente** ein. +
Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite <<auftraege/auftragsdokumente#, Auftragsdokumente>>.

[#300]
== Einzelnen Rücksendeschein erzeugen

In manchen Fällen macht es Sinn, Rücksendescheine zu bestimmten Aufträgen manuell zu erzeugen. Dies geschieht sowohl für reguläre Aufträge als auch für Retourenaufträge in der Auftragsübersicht.

[#400]
=== Rücksendeschein am Hauptauftrag erzeugen

Einen einzelnen Rücksendeschein kannst du in plentymarkets bei Bedarf manuell direkt am Hauptauftrag erzeugen. Der so erzeugte Rücksendeschein beinhaltet dann alle im Auftrag enthaltenen Artikelpositionen. Nutze diese Methode, um jedem Paket, das du versendest, einen unausgefüllten Rücksendeschein beizulegen. Weitere Informationen hierzu findest du im Kapitel **<<auftraege/auftraege-verwalten#450, Rücksendeschein erstellen>>**.

[.instruction]
Rücksendeschein am Haupauftrag erzeugen:

. Öffne das Menü **Aufträge » Aufträge bearbeiten**. +
→ Die Auftragsübersicht öffnet sich.
. Wähle durch Klick auf die **Auftrag-ID** den Auftrag aus, für den ein Rücksendeschein erzeugt werden soll. +
. Wechsle in das Tab **Belege**. +
. Wähle im Drop-Down-Menü **Beleg erstellen** das Dokument **Rücksendeschein** aus. +
. Nimm die Einstellungen anhand <<tabelle-auftraege-belege-ruecksendeschein>> vor. +
. **Speichere** die Einstellungen, um den Rücksendeschein zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei** mit dem soeben erzeugten Rücksendeschein.

[[tabelle-auftraege-belege-ruecksendeschein]]
.Optionen im Menü *Beleg erstellen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Datum**
|Datum wählen, das auf dem Rücksendeschein angezeigt wird. Standardmäßig ist das aktuelle Datum voreingestellt.

|**Nummer**
|Die Nummer des Dokuments wird automatisch vergeben. Hier muss keine Angabe gemacht werden.

|**Ändere Auftragsstatus auf Status**
|Einen Status wählen, in den der Auftrag nach dem Erzeugen des Rücksendescheins wechseln soll. Wenn kein Statuswechsel gewünscht ist, die Option **Keine Änderung** wählen.

|**Kommentar**
|Einen Text eingeben, der auf dem Rücksendeschein unterhalb der Artikelpositionen angezeigt wird. Die Eingabe ist optional.
|====

[#500]
=== Rücksendeschein am Retourenauftrag erzeugen

Möchtedz du deinen Kunden einen Rücksendeschein zur Verfügung stellen, z.B. wenn diese im Mein-Konto-Bereich des Webshops eine Retoure zu einem bestimmten Auftrag beantragen, erstelle einen Rücksendeschein im dazugehörigen Retourenauftrag.

[.instruction]
Rücksendeschein am Retourenauftrag erzeugen:

. Öffne das Menü **Aufträge » Aufträge bearbeiten**. +
→ Die Auftragsübersicht öffnet sich.
. Wähle durch Klick auf die **Auftrags-ID** den Retourenauftrag aus, für den ein Rücksendeschein erzeugt werden soll. +
. Wechsle in das Tab **Belege**. +
. Wähle im Drop-Down-Menü **Beleg erstellen** das Dokument **Rücksendeschein** aus. +
. Nimm die Einstellungen anhand <<tabelle-auftraege-belege-ruecksendeschein>> vor. +
. **Speichere** die Einstellungen, um den Rücksendeschein zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei** mit dem soeben erzeugten Rücksendeschein.

[#600]
== Mehrere Rücksendescheine erzeugen

Sollen für mehrere Aufträge zugleich Rücksendescheine erzeugt werden, kannst du über einen Suchfilter im Menü **Aufträge » Fulfillment** festlegen, welche Aufträge berücksichtigt werden. Zudem kannst du in diesem Menü festlegen, ob der Status des Auftrags geändert werden soll, nachdem die Rücksendescheine erzeugt wurden.

[.instruction]
Mehrere Rücksendescheine erzeugen:

. Öffne das Menü **Aufträge » Fulfillment » Rücksendeschein erzeugen**.
. Nimm die Einstellungen anhand <<tabelle-einstellungen-fulfillment-ruecksendeschein>> vor.
. Klicke auf das **Zahnrad**, um die Rücksendescheine zu erzeugen. +
→ Es öffnet sich eine **PDF-Datei**, in der die zugehörigen Rücksendescheine aller von dir durch die Suchfilter bestimmten Aufträge enthalten sind.

[[tabelle-einstellungen-fulfillment-ruecksendeschein]]
.Optionen im Menü *Rücksendeschein erzeugen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Auftragsstatus**
|Aus der Liste den Status der Aufträge wählen, die für das Erzeugen der Rücksendescheine berücksichtigt werden sollen.

|**Eigner**
|Wähle einen Eigner aus, für dessen Aufträge die Rücksendescheine erzeugt werden sollen oder die Option **ALLE**, wenn für alle Eigner die Rücksendescheine erzeugt werden sollen.

|**Standort**
|Wähle einen Standort aus, für den die Rücksendescheine erzeugt werden sollen.

|**Lager**
|Wähle ein Lager oder **ALLE** aus.

|**Zahlungsart**
|Wähle eine der Zahlungsarten oder *ALLE* aus.

|**Sortierung**
|Lege fest, wie die erzeugten Rücksendescheine sortiert werden sollen. Die Optionen **Auftrags-ID**, **Kunden-ID** und **Artikel-ID** geben verschiedene Sortierungen aus.

|**Limit**
|Lege fest, wie viele Rücksendescheine maximal pro Durchgang erzeugt werden. Das Maximum liegt bei *200* Rücksendescheinen.

|**Ändere Auftragsstatus**
|Wähle einen Status, in den die Aufträge nach Erzeugung der Rücksendescheine wechseln sollen. +
Der Statuswechsel ist wichtig, damit für bereits bearbeitete Aufträge ein Prozess nicht noch einmal durchgeführt wird.

|**Kommentar**
|Einen Text eingeben, der auf allen Rücksendescheinen unterhalb der Artikelpositionen erscheint. Die Eingabe ist optional.
|====
