= E-Mail bei verfügbarem Artikel
:lang: de
// include::{includedir}/_header.adoc[]
:description: plentymarkets informiert Interessenten, wenn Artikel wieder verfügbar sind
:position: 10

== E-Mail an Kunden senden, wenn Artikel wieder verfügbar ist

Artikel sind unter Umständen kurzfristig nicht lieferbar. Kunden sollen die Möglichkeit haben, eine E-Mail-Adresse direkt bei nicht lieferbaren Artikeln zu hinterlegen, um informiert zu werden, wenn der Artikel wieder auf Lager ist. Die E-mail soll einmalig versendet werden und nicht jedes Mal, wenn der Netto-Bestand des Artikels positiv wird. In diesem Fallbeispiel zeigen wir Ihnen, wie Sie vorgehen.

== E-Mail-Vorlage erstellen

Legen Sie zunächst eine <<crm/e-mails-versenden#1200, E-Mail-Vorlage>> an. Der Text dieser E-Mail wird an Kunden versendet, die eine E-Mail-Adresse hinterlegt haben, wenn ein Artikel wieder auf Lager ist. Unten finden Sie eine Liste möglicher Template-Variablen und -Funktionen für diese E-Mail-Vorlage. Wir stellen Ihnen außerdem einen Beispieltext zur Verfügung, den Sie an Ihre Anforderungen anpassen können.

Mögliche Template-Variablen und -Funktionen für eine E-Mail-Vorlage zur Artikelverfügbarkeit:

.Mögliche Template-Variablen/-Funktionen für eine E-Mail-Vorlage zur Artikelverfügbarkeit
[cols="1,3"]
|====
|Variable/Funktion |Erläuterung

|*$ItemASIN*
|Amazon Standard Ident Number (ASIN) des Artikels

|*$ItemEAN*
|Internationale Artikelnummer (EAN)

|*$ItemImageURL*
|URL zum Artikelbild

|*$ItemISBN*
|ISBN-Code des Artikels

|*$ItemModel*
|Modellbezeichnung des Artikels

|*$ItemName*
|Artikelname

|*$ItemNumber*
|Artikelnummer

|*$ItemPrice*
|Brutto-Artikelpreis

|*$ItemPriceNet*
|Netto-Artikelpreis

|*$ItemProducerName*
|Artikelhersteller

|*$VariantName*
|Artikelvariante

|*{% Link_Item($ItemID) %}*
|Link zum Artikel im Webshop
|====


Unten finden Sie einen Beispieltext für eine E-Mail-Vorlage, den Sie als Muster verwenden und an Ihre Anforderungen anpassen können. Diesen Text fügen Sie im Tab *Inhalt » HTML-formatierter Text* der E-Mail-Vorlage ein. Gehen Sie wie unten beschrieben vor, um diesen oder einen anderen Text in der E-Mail-Vorlage zu hinterlegen.

[.instruction]
Text für E-Mail-Vorlage hinterlegen:

. Legen Sie eine neue <<crm/e-mails-versenden#1200, E-Mail-Vorlage>> im HTML-Format an.
. Kopieren Sie den Beispieltext (_Nachricht_) in das Tab *E-Mail-Nachricht » Inhalt » HTML-formatierter Text* mit dem Syntax-Editor ein.
. Passen Sie den Text und die HTML-Formatierung des Beispieltexts an Ihre Anforderungen an.
. Fügen Sie im Tab *Artikelliste* das darauffolgende Beispiel mit dem Syntax-Editor ein.

[.instruction]
Nachricht

[source,plenty]
----
include::assets/E-Mail-Vorlage-Warenverfuegbarkeit.html[]

----
[.instruction]
Artikelliste

[source,plenty]
----
include::assets/E-Mail-Vorlage-Warenverfuegbarkeit-Artikelliste.html[]

----
== E-Mail-Vorlage für automatischen E-Mail-Versand verknüpfen

Nun verknüpfen Sie die E-Mail-Vorlage mit der Option *Benachrichtigung bei verfügbarem Artikel*. Die Vorlage greift, wenn ein Artikel, bei dem Interessenten eine E-Mail-Adresse hinterlegt haben, wieder lieferbar ist. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
E-Mail-Vorlage für automatischen E-Mail-Versand verknüpfen:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » E-Mail » Automatischer Versand*.
. Wählen Sie bei der Option *Benachrichtigung bei verfügbarem Artikel* die E-Mail-Vorlage aus der Dropdown-Liste.

== Beispiel-Code für Formular bearbeiten und einbinden

Nun binden Sie ein Formular in Ihr Design ein, das angezeigt wird, wenn ein Artikel nicht lieferbar ist. Als Minimalanforderung sollte dieses Formular aus einem Eingabefeld und einem Button bestehen. In das Feld geben Interessenten eine E-Mail-Adresse ein. Durch Klick auf den Button erklären Sie sich damit einverstanden, eine E-Mail zu erhalten, wenn der Artikel wieder verfügbar ist. Über den REST-Aufruf */rest/positive_stock_notification/* wird die E-Mail-Adresse gespeichert und alle hinterlegten E-Mail-Adressen benachrichtigt, sobald der Artikel einen positiven Netto-Bestand hat.

Weiter unten finden Sie einen Beispiel-Code, der für unser Responsive-Design *Callisto Light* optimiert ist. Verwenden Sie diesen Code als Basis, um das Formular in Ihr Design einzubinden. Passen Sie den Code an Ihre Anforderungen an, bevor Sie den Code in Ihrem Webshop verwenden. Gehen Sie wie unten beschrieben vor, um den Beispiel-Code in Ihr Design einzubinden.

[.instruction]
Beispiel-Code in Design einbinden:

. Passen Sie den Beispiel-Code unten an Ihre Anforderungen an.
. Kopieren Sie den Code in die Zwischenablage (*Strg + C* bzw. *Cmd + C*).
. Öffnen Sie das Menü *CMS » Webdesign* und dort dann *Layout » ItemView » ItemViewSingleItem*.
. Fügen Sie das Code-Beispiel an geeigneter Stelle in das Template ein.

[source,plenty]
----
include::assets/EX-DE-REST-positive-stock-notification.html[]

----

Wenn im Menü *System » Mandant » Mandant wählen » Artikelansichten » Einstellungen* für die Einstellung *Attribut-Verfügbarkeit* die *Client-Prüfung* aktiviert ist, wird durch das nachfolgende Code-Beispiel das zuvor erzeugte Formular je nach Verfügbarkeit der Variante dynamisch ein- und ausgeblendet.

[.instruction]
Beispiel-Code in Design einbinden:

. Passen Sie den Beispiel-Code unten an Ihre Anforderungen an.
. Kopieren Sie den Code in die Zwischenablage (*Strg + C* bzw. *Cmd + C*).
. Öffnen Sie das Menü *CMS » Webdesign* und dort dann *Layout » ItemView » ItemViewSingleItem*.
. Suchen Sie nach der Code-Zeile *$(window).on('variationChanged', function(event, variation) {*.
. Fügen Sie das Code-Beispiel unterhalb der Code-Zeile ein.

[source,plenty]
----
include::assets/EX-DE-REST-positive-stock-notification-dynamic.html[]

----
