= EbayTitleMatch
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Data format
:description: Data format EbayTitleMatch
:position: 90
:url: data/export-import/data-formats/ebaytitlematch

The data format **EbayTitleMatch** gives you the possibility of linking a listing's title to specific items. With this link, listings that were set up with other tools can be imported into plentymarkets and can be automatically assigned to the correct items. You can carry out this setting directly in the editing window of an item. It is found in the tab **Multi-Channel » eBay title**. Create and export the data format in the **Data » Dynamic export** menu. Import the data format in the **Data » Dynamic import** menu. The <<data/export-import/exporting-data#, Exporting data>> and <<data/export-import/importing-data#, Importing data>> pages of the manual describe how you export and import the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

Table 1 explains the data fields for the **EbayTitleMatch** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

[cols="1,3,3"]
|====
|Field name |Explanation |Filter

|**ItemID**
|Item ID
|Activate the filter, select the operator and enter the value.

|**ItemNo**
|Item number
|

|**Title**
|Title of the listing that should be linked with this item
|
|====

__Table 1: data fields of the data format **EbayTitleMatch**__

