= ItemImageName
:lang: en
include::{includedir}/_header.adoc[]
:position: 152
:url: data/export-import/data-formats/itemimagename
:id: KEDRWGO

**Data » Dynamic export** and **Data import » Dynamic import**

== General information about the data format ItemImageName

Use the data format **ItemImageName** to edit or delete the item image names and alternative names for item images that are linked in an item's **Images** tab. This allows you to easily edit large quantities of linked images at the same time.

== Important notes

[WARNING]
.Spell the field names correctly!
====
Pay close attention to the exact spelling of the data fields (upper/lower case letters). The data can not be processed if the data field is spelled incorrectly.
====

== Overview of the data fields

The following table explains the data fields for the data format **ItemImageName**. The data fields are listed in alphabetical order:

.Data fields of the data format **ItemImageName**
[cols="1,3,3"]
|====
|Field |Description |Filter options (tab: Filter)

|**ItemImageID**
|Item image ID
|Select the operator and enter the value.

|**ItemImageItemID**
|Item ID
|Select the operator and enter the value.

|**ItemImageLanguage**
|The item image name's language
|Select a language.

|**ItemImageName**
|Name of the item image
|

|**ItemImageNameAlternate**
|Alternative name; this helps search engines index the item.
|

|**ItemImageNameDelete**
|**1** = Deletes the image names +
Deletes the image names completely and irreversibly when the value 1 is entered. For further information, refer to the **Filter** page of the manual.
|

|**ItemImageURL**
|Item image URL
|
|====

== Synchronization fields

The data fields that are listed in the following table are available for **data synchronization**. The mandatory synchronization fields have to be selected in order for the synchronization to take place.

.Data fields that can be used for the **synchronization**
[cols="1,3,3"]
|====
|Field |Description |Mandatory synchronization fields (M) and alternatives

|**ItemImageID**
|Item image ID
|M

|**ItemImageLanguage**
|The item image name's language
|M
|====
