= ItemListingMarketText
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Data format ItemListingMarketText
:position: 160
:url: data/export-import/data-formats/itemlistingmarkettext

Use the data format *ItemListingMarketText* to  exportieren the Listing's description, subtitle and title in different languages. Create and export the data format in the *Data » Dynamic export* menu. Import the data format in the *Data » Dynamic import* menu. The <<data/export-import/exporting-data#, Exporting data>> and <<data/export-import/importing-data#, Importing data>> pages of the manual describe how you export and import the data format.

== Important notes

[WARNING]
.Spell the field names correctly!
====
Pay close attention to the exact spelling of the data fields (upper/lower case letters). The data can not be processed if the data field is spelled incorrectly.
====

== Overview of the data fields

The following table explains the data fields for the data format *ItemListingMarketText*. The data fields are listed in alphabetical order:

.Data fields of the data format *ItemListingMarketText*
[cols="1,3,3"]
|====
|Field |Description |Filter

|*Description*
|Description text
|Select the operator and enter the value.

|*Lang*
|Language
|Select the operator and enter the value.

|*ListingMarketID*
|Market-ID
|Select the operator and enter the value.

|*Subtitle*
|The subtitle of the Listing
|Select the operator and enter the value.

|*Title*
|The title of the Listing
|Filter aktivieren, Operator wählen und Wert eingeben.
|====

== Synchronization fields

The data fields that are listed in the following table are available for *data synchronization*. The mandatory synchronization fields have to be selected in order for the synchronization to take place.

.Data fields that can be used for the *Synchronization*
[cols="1,3,3"]
|====
|Field |Description |Mandatory synchronization fields (M) and alternatives

|*Lang*
|Language
|M

|*ItemListingMarketID*
|Market-ID
|M
|====
