= Erste Schritte
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:position: 10
:id: Y2C3HMM
:url: maerkte/conrad/erste-schritte
:keywords: {market}, Marktplatz, {market}.de, {market} einrichten, {market} Marktplatz, Multi-Channel, Multichannel, Multi-Channel {market}, Multichannel {market}, Multi Channel {market}
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz {market} in deinem plentymarkets System ein.
:marketplace-url: https://marketplace.plentymarkets.com/conradextension_6948
:assistant-name: ConradExtension
:market: Conrad

Auf dieser Seite erfährst du, wie du die Plugins *Mirakl* und *{market}* herunterlädst und installierst. Mirakl ist die Plattform, über die {market} angebunden ist.

[#registrieren]
== Bei {market} registrieren

Du benötigst die Conrad-Zugangsdaten bestehend aus Nutzername und Passwort. Diese Daten erhältst du von Conrad. Hierzu musst du zunächst bei link:https://www.conrad.de/de/service/bestellung-und-beschaffung/marketplace.html[Conrad^] ein Mitgliedskonto erstellen.

[#about]
== Über {market}

Über das Conrad-Plugin wird der B2B-Marktplatz Conrad mit deinem plentymarkets System verbunden. Durch das Plugin wird der automatische Austausch von Artikel- und Auftragsdaten zwischen plentymarkets und dem Marktplatz Conrad ermöglicht. Dadurch kannst du deine Artikel auf Conrad listen.

Um die Verbindung zu Conrad einzurichten, kannst du entweder der Anleitung auf dieser Seite folgen oder dir folgendes Webinar ansehen:

video::zI1_7iF8U0o[youtube]

[#plugins-herunterladen]
== Plugins Mirakl Connector und {market} herunterladen

Die Schnittstelle zu {market} wird über ein Plugin integriert. Um das {market}-Plugin nutzen zu können, lade das Plugin im link:{marketplace-url}[plentyMarketplace^]{nbsp}icon:external-link[] herunter.

Um das {market}-Plugin nutzen zu können, benötigst du außerdem das Plugin *Mirakl Connector*. Du findest Mirakl ebenfalls auf link:https://marketplace.plentymarkets.com/mirakl_6917[plentyMarketplace^]{nbsp}icon:external-link[].

:plugin: Mirakl Connector
[#mirakl-plugin-installieren]
== {plugin} installieren

Installiere das Plugin *{plugin}* wie im Folgenden beschrieben.

include::../../plugins/_textblocks/instructions/plugin-installieren.adoc[]

[#marktplatz-plugin-installieren]
== {market}-Plugin installieren

Gehe wie im Folgenden beschrieben vor, um das Plugin *{market}* zu installieren.

:plugin: {market}
:priority: 1

include::../../plugins/_textblocks/instructions/plugin-installieren.adoc[]
