= Automatischer Austausch von Produkt- und Angebotsdaten
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: {market}, Marktplatz, {market}.de, {market} einrichten, {market} Marktplatz, Multi-Channel, Multichannel, Multi-Channel {market}, Multichannel {market}, Multi Channel {market}
:description: Multi-Channel in plentymarkets: Produkt- und Angebotsdaten automatisch mit dem Marktplatz {market} austauschen.
:position: 30
:url: maerkte/conrad/automatischer-datenaustausch
:id: 853Y2O0
:market: Conrad
:marketplace-url: https://marketplace.plentymarkets.com/conradextension_6948
:assistant-name: ConradExtension
:category-example: VHS Kassetten

Auf dieser Seite lernst du, wie du mit Hilfe eines Assistenten einen Katalog für den Artikelexport erstellst und wie du die Datenfelder im Katalog zuordnest, um deine Produkt- und Angebotsdaten korrekt an den Marktplatz zu übertragen. Anschließend musst du nur noch die Variantenverfügbarkeit einstellen und den Katalogexport aktivieren.

[#allgemeine-informationen]
== Informationen zum automatischen Datenaustausch

Nachdem du das Plugin installiert und eingerichtet hast, stehen die in <<#datenaustausch-{market}>> automatisierten Prozesse bereit:

[#datenaustausch-{market}]
[cols="1,3a"]
.Häufigkeit des Datenaustauschs
|====
|Daten |Intervall

2+| Artikeldaten

| Artikelexport
| Täglich

| Bestandsabgleich
| Alle 15 Minuten

| Preisabgleich
| Alle 15 Minuten

2+| Auftragsdaten

| Auftragsimport
| Alle 15 Minuten

|====

[#artikelexport-katalog]
== Artikelexport einrichten

Artikeldaten werden über Marktplatz-Formate zu {market} übertragen. Kataloge erstellst du im Menü *Daten » Kataloge*. Du arbeitest zum ersten Mal mit den Katalogen? Dann solltest du dich zuerst <<daten/daten-exportieren/kataloge-verwalten#, mit dem Prinzip der Kataloge vertraut machen>>.

Für jede Produktkategorie von {market}, in der du Produkte verkaufen möchtest, erstellst du einen eigenen Katalog. Verknüpfe anschließend im Marktplatz-Format die von {market} vorgegebenen Felder mit den in plentymarkets gespeicherten Artikeldaten. Die Katalog-Vorlagen werden automatisch täglich zu {market} exportiert, wenn du den Katalog aktivierst.

[IMPORTANT]
.Fehler-Log
====
Wenn es beim Export Probleme gibt, findest du die zugehörigen Log-Einträge auf Mirakl und nicht im Log von plentymarkets.
====

[#katalog-im-assistenten]
=== Katalog im Assistenten erstellen

Gehe wie im Folgenden beschrieben vor, um einen Katalog im Assistenten zu erstellen.

:catalogue-assistant-name: {market}-Katalog
:number-of-boxes: Info-Box
:mapping-fields: die
:catalogue-path: pass:quotes[*Einrichtung » Assistenten » Plugins » [Plugin-Set wählen]*]
:catalogue-note: pass:quotes[Achte darauf, eine Kategorie der untersten Ebene zu wählen. Eine bessere Übersicht findest du auf Mirakl im Menü *Mein Konto » Meine Produktdaten-Einstellungen*.]

include::../_textblocks/instructions/catalogue-assistant-config.adoc[]

[#datenfelder-zuordnen]
=== Datenfelder im Katalog zuordnen

Nachdem du einen Katalog erstellt hast, ordnest du die Datenfelder des Marktplatzes den in plentymarkets gespeicherten Artikeldaten zu. Informationen dazu, welche Daten für welches Datenfeld des Marktplatzes übertragen werden müssen, findest du in der Dokumentation des Marktplatzes.

[TIP]
.Eigenschaften verwenden
====
Verwende <<artikel/artikel-verwalten#4800, Eigenschaften>>, um Werte für Marktplatz-Datenfelder zu übergeben, für die es keine Entsprechung in plentymarkets gibt.
====

include::../_textblocks/instructions/katalog-datenfelder-zuordnen.adoc[]

[IMPORTANT]
====
Beim Marktplatz {market} darf folgenden Marktplatz-Datenfeldern kein plentymarkets Datenfeld zugeordnet werden:

* Produktbild 1
* Produktbild 2
* Produktbild 3
* Produktbild 4
* Produktbild 5

Die Warnmeldung beim Speichern der Zuordnung kannst du dabei ignorieren.
====

:mirakl-conrad-inhalt-einheit:
:mirakl-attribut-hilfetool:
:mirakl-hersteller-teilenummer:

include::../_textblocks/instructions/katalog-mirakl-zuordnungen.adoc[]

////
Wird noch überarbeitet
[TIP]
.Datenfelder zur Grundpreisangabe pflegen
====
Die beiden Datenfelder *Brutto-Inhaltsmenge für Grundpreisangabe* und *Einheit der Grundpreisangabe* werden zwar nicht als Pflichtfelder markiert, müssen aber hinsichtlich der rechtlichen Situation zur Angabe der Grundpreise gepflegt und übertragen werden.
Für beide Datenfelder gibt es keine Liste von gültigen Werten. Wir empfehlen jedoch dem Attribut *Brutto-Inhaltsmenge für Grundpreisangabe* das plentymarkets Datenfeld *Inhalt Menge* zuzuordnen und für das Attribut *Einheit der Grundpreisangabe* eine Eigenschaft zu erstellen und die Werte an den Varianten zu speichern, zum Beispiel „g“ für *Gramm*.
====
////

[#weitere-eigenschaften]
=== Weitere Eigenschaften erstellen

Wenn du für eine oder alle deine Varianten mehrere <<artikel/einstellungen/attribute#, Attribute>> definiert hast, erstelle eine Eigenschaft, die diese Attribute vereint. Unterscheidest du bei einer Variante z.B. sowohl nach Farbe als auch nach Größe, legst du eine Eigenschaft mit der Benennung "Grau XL" an. <<artikel/einstellungen/eigenschaften#1400, Ordne diese Eigenschaften>> den entsprechenden Varianten zu.

Zusätzlich zu den <<maerkte/conrad/erste-schritte#eigenschaften-erstellen, zuvor beschriebenen Eigenschaften>> benötigst du Eigenschaften für alle Datenfelder des Marktplatzes, für die du Daten übergeben möchtest, die es standardmäßig in plentymarkets nicht gibt. Welche Eigenschaften du benötigst, siehst du anhand der Datenfelder im Katalog. Du arbeitest zum ersten Mal mit Eigenschaften? Weitere Informationen findest du auf der Artikel-Handbuchseite zum Thema <<artikel/einstellungen/eigenschaften#500, Eigenschaften>>.

////
Prüfen, wo Inhalt hingehört, wenn einkommentiert wird.

:valid-values-zip: https://drive.google.com/file/d/1VUBBNaTuOfiuWtpKl2TrAV54gm-bR2aW/view?usp=sharing

In der ZIP-Datei link:{valid-values-zip}[{market}: Gültige Werte^] findest du CSV-Dateien für jedes Marktplatzattribut. Innerhalb einer CSV-Datei sind die gültigen Werte für das Attribut abgebildet. Den zu übertragenden Wert findest du immer in der Spalte *Code*.
////

[#varianten-mit-katalog-kategorie-verknüpfen]
== Varianten mit {market} Katalog-Kategorie verknüpfen

Nachdem du mit dem Assistenten *{assistant-name} Catalog* oder manuell ein Marktplatz-Format für {market} erstellt hast, wird in deinem plentymarkets System die Eigenschaft *{market}* erstellt. Für jede Kategorie, die du im ersten Schritt *Einstellungen* des Assistenten wählst, wird die gewählte Kategorie als neuer Auswahlwert zur Eigenschaft *{market} Kategoriegruppe* hinzugefügt. Damit deine Varianten im gewünschten Katalog exportiert werden, müssen sie im *Tab: Eigenschaften* einer Variante mit der Eigenschaft *{market} Kategoriegruppe* verknüpft werden.

[.instruction]
Variante mit Kategorie verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen]*.
. Wechsele in das *Tab: Varianten*.
. Öffne die Variante, die du verknüpfen möchtest.
. Wechsele in das *Tab: Eigenschaften*.
. Wähle im Bereich *Varianteneigenschaften* aus der Dropdown-Liste *Eigenschaften* die Eigenschaft *{market} Kategoriegruppe* und klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird hinzugefügt.
. Wähle für die Eigenschaft *{market} Kategoriegruppe* aus der Dropdown-Liste *Wert* die gewünschte Kategorie. +
→ Die Variante wird im zugehörigen Katalog exportiert. +
*_Beispiel:_* Wählst du den Wert *{category-example}*, wird die Variante im Katalog für die Kategorie *{category-example}* exportiert.
. Wiederhole die Schritte 5 und 6 für alle Kategorien, in denen du die Variante verkaufen willst.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[discrete]
=== Weitere Möglichkeiten zum Verknüpfen

* per Import: Über *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* die Eigenschaft *{assistant-name} Kategoriemapping* aufrufen und auf Werte klicken. Dort sind die Auswahlwert-IDs, die für den Import notwendig sind, zu finden.
* per REST-API: Verwende dazu die REST-Routen aus den Bereichen link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/Property[Property^] und link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/Item[Item^], um den Katalog mit der Variante zu verknüpfen. +
*_Hinweis_*: Steht im Assistenten *{assistant-name} Catalog* keine Marktplatzkategorie zur Auswahl, dann ist im Assistenten *{assistant-name}* im Schritt *Authentifizierung* ggf. die falsche API-Umgebung ausgewählt.

[#eigenschaften-mit-varianten-verknuepfen]
==== Eigenschaften mit Varianten verknüpfen und Werte speichern

include::../_textblocks/instructions/properties-link.adoc[]

[#{market}]
== Katalogexport aktivieren

:interval: täglich
:market: {market}

include::../_textblocks/instructions/catalogue-activation.adoc[]

[#marktplatzspezifische-werte]
=== Markplatzspezifische Werte übertragen

Der Marktplatz verlangt für die Übertragung von Produktdaten bei den meisten Attributen spezifische Werte. Diese sind derzeit allerdings noch nicht in dieser Form an der Variante hinterlegt. +
*_Beispiel:_* Für das Attribut *Brand* ist beispielsweise *test* nicht erlaubt. Hier muss der entsprechende Code übergeben werden - in diesem Beispiel *BRAND_12345678*.

== Das Attribut-Hilfetool verwenden

Das sogenannte Attribut-Hilfetool ermöglicht es dir, nach den verschiedenen Attributen zu suchen und gibt die aktuell dafür gültigen Werte an. Um das Tool nutzen zu können, muss der Assistent *{assistant-name}* bereits eingerichtet sein.
Das Tool findest du unter der folgenden URL: `domain/marketplace_extension/attribute_values`.
Trage anstelle von `domain` deine plenty Domain ein. Würde deine plenty Domain beispielsweise `https://www.meine-plenty-domain.de` lauten, wäre die URL wie folgt aufgebaut: `https://www.meine-plenty-domain.de/marketplace_extension/attribute_values`.

Gib `SAP.TaxIndicator` in die Suche des Attribut-Hilfetools ein, um die gültigen Werte für *Umsatzsteuerklasse* und `SAP.BaseUnits`, um die gültigen Werte für *Verkaufsmengeneinheit* zu finden.

[IMPORTANT]
.Ausgabe der Attributwerte am Folgetag
====
Die Tabelle der gültigen Attributwerte wird jeweils über Nacht aktualisiert. Nach dem erstmaligen Installieren des Plugins werden die gültigen Werte erst am Folgetag ausgegeben. +
Wenn du im Assistenten die falsche API-Umgebung und/oder den falschen API-Schlüssel eingetragen hast, können die gültigen Werte nicht geladen werden.
====

Im Katalog findest du die Benennungen der Marktplatzattribute, wie zum Beispiel *Marke*. Um die für ein Attribut gültigen Werte herauszufinden, gehe vor wie folgt.

[.instruction]
Das Attribut-Hilfetool verwenden:

. Rufe die wie oben beschriebene URL auf.
. Gib den Namen des Attributes in die Suche ein oder nutze Strg+F bzw. Cmd+F, um die Ergebnisliste zu durchsuchen. +
→ In der Spalte *Attribute Label* ist das Attribut zu sehen. +
→ In der Spalte *Value Code* sind die gültigen Werte aufgeführt, die für die Attributwerte in der Spalte *Value Label* übertragen werden müssen.

=== Gültige Attributwerte zuordnen und übertragen

Hast du - je nach Variante, die übertragen werden soll - unterschiedliche Attributwerte, die gültig sein könnten, stellt sich zunächst die Frage, über welche Vorgehensweise du deine Artikeldaten aktuell hältst.
Verwaltest du deine Artikeldaten manuell, ist eine Eigenschaft vom Typ *Auswahl* empfehlenswert. Hier kannst du für die Auswahl eine Beschreibung hinterlegen. Diese wird dann in der Übersicht der Eigenschaften an der Variante angezeigt.
Wenn der Code der Eigenschaft zugeordnet wurde, kannst du den realen Namen der Variante im Feld *Beschreibung* verwenden. Das bedeutet, über den Katalog wird dann der Code übertragen und dahinter in Klammern der reale Name angezeigt. +

*_Tipp:_* Wenn du für ein Attribut immer nur einen einzigen Wert übertragen möchtest, z.B. als Marke immer *BRAND_12345678*, kannst du die Option *Eigener Wert* im Katalog verwenden.

[#produkt-und-angebotsdaten]
== Produkt- und Angebotsdaten übertragen

Bei {market} erfolgt der Listingprozess in zwei Schritten: Zuerst werden Produkte erstellt und nach Freigabe der Produktdaten vom Marktplatz können Angebote zu den erstellten Produkten aktiviert werden. Beide Exportprozesse, deren Voraussetzungen sowie Übertragungsoptionen werden in den folgenden Unterkapiteln beschrieben.

[#produktdaten-ubertragen]
=== Produktdaten übertragen

In diesem Kapitel erfährst du, wie du Produktdaten an den Marktplatz überträgst und welche Voraussetzungen erfüllt werden müssen. Diese Daten kommen aus dem von dir erstellten Katalog *{assistant-name} Catalog*.

=== Voraussetzungen für die Produktdatenübertragung

* Die Plugins link:{marketplace-url}[{market}^]{nbsp}icon:external-link[] sowie *Mirakl Connector* wurden im plentyMarketplace gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {market} und Mirakl aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {assistant-name}* wurde die Grundeinrichtung vorgenommen. Für die Produktübertragung muss die Option *Produkte exportieren* im Schritt Datenaustausch aktiv sein.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurden die Auftragsherkünfte *Mirakl* sowie *{assistant-name}* an einem bestehenden Preis aktiviert *_oder_* es wurde ein neuer Verkaufspreis erstellt, bei dem die Auftragsherkünfte *Mirakl* und *{assistant-name}*  aktiviert wurden.
* Du hast bereits einen <<daten/daten-exportieren/kataloge-verwalten#, Katalog>> für die Übertragung der Daten erstellt.

[IMPORTANT]
.Wie hängen die Angebotsfelder, das Produktexportfeld und die Marktplatz-SKU an der Variante zusammen?
====
Die Angebotsfelder *sku* und *product-id* werden grundsätzlich immer mit dem Wert gefüllt, der an der Variante im Feld *Marktplatz-SKU* für den Marktplatz definiert wurde.
Das Angebotsfeld *product-id-type* wird standardmäßig mit dem Wert *SHOP_SKU* übertragen.

// * Wenn *SKU* gewählt wird, muss die SKU vom Marktplatz als Marktplatz-SKU an der Variante definiert werden.
// * Wenn *EAN* gewählt wird, muss die EAN der Variante als Marktplatz-SKU an der Variante definiert werden. Bitte nicht verwenden, diese Funktion ist noch nicht im Marktplatz aktiv
// * Wenn *ISBN* gewählt wird, muss die ISBN der Variante als Marktplatz-SKU an der Variante definiert werden. Bitte nicht verwenden, diese Funktion ist noch nicht im Marktplatz aktiv

Das Produktexportfeld *Produkt-ID (Artikelnr. des Verkäufers)* wird je nach Einstellung im Katalog gefüllt.
Bei der ersten Übertragung, die über Nacht stattfindet, wird die Marktplatz-SKU an der Variante in plentymarkets automatisch aus der Varianten-ID gebildet. Die Marktplatz-SKU kann alternativ per Import oder manuell definiert werden.
====

////
//TODO: Prüfen, ob das sichtbar sein sollte.
=== Werte für die Übertragung an den Marktplatz definieren

Die Werte *product-id* und *sku* werden wie folgt übertragen:

* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, muss mit dem Wert der *product-id* in der Angebotsübertragung übereinstimmen.
* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, wird im Katalog definiert.
* Der Wert, der als Marktplatz-SKU an der Variante hinterlegt wird, wird für die Felder *sku* und *product-id* bei der Angebotsübertragung verwendet.
* Wenn du keinen Wert für die Marktplatz-SKU an einer Variante definiert hast, aber die Marktplatzverfügbarkeiten aktiviert wurden, wird die Variante in der Angebotsübertragung ohne *sku* und *product-id* übertragen.

Daraus ergeben sich die folgenden Zuordnungen für die Produktübertragung:

* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* nur die Varianten-ID zugeordnet. Bei der ersten Produktübertragung von dieser Variante wird automatisch (wenn sonst kein Wert vorher definiert wurde) die Varianten-ID als Marktplatz-SKU an der entsprechenden Variante gespeichert.
* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* die SKU zugeordnet und die Varianten-ID als Ausweich-Datenfeld definiert. Vor der ersten Produktübertragung der Variante wird die Marktplatz-SKU an der Variante definiert. Nimmst du diese Einstellung nicht vor,  wird die Varianten-ID nach der ersten Produktübertragung automatisch als Marktplatz-SKU an der Variante hinterlegt.
////

=== Produktdaten aktualisieren

Du kannst zu jeder Zeit eine Aktualisierung der Produktdaten vornehmen. Ausgeschlossen davon sind jedoch die folgenden Produktdaten:

* Verpackungseinheiten
* Hersteller-Teilenummer
* Artikelnummer des Verkäufers

Wenn du eines oder mehrere der o.g. Felder ändern möchtest, musst du das Produkt zuerst löschen und dann neu übertragen. Gehe dazu vor wie folgt:

[.instruction]
Produktdaten aktualisieren:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Erstelle eine Eigenschaft vom Typ *Kurztext*.
. Gib einen Namen ein, zum Beispiel *Marktplatz-Produkt löschen*.
. Öffne das Menü *Daten » Kataloge*.
. Öffne den entsprechenden Katalog.
. Ordne dem Datenfeld *Product Invalidierungs Markierung* bzw. *InvalidationFlag* die Eigenschaft zum Löschen des Produkts, die du gerade erstellt hast, zu.
. Öffne den Assistenten.
. Gehe in den Schritt *Zuordnung der Angebots- Eigenschaften*.
. Ordne der Eigenschaft *{market} Update-Delete* das Datenfeld *update-delete* zu.
. Wähle an der zu löschenden Variante den Auswahlwert *delete*. +
*_Hinweis:_* Eine Bestands- oder Preisänderung der Variante kann einige Zeit dauern. Alternativ kannst du diese Änderung manuell vornehmen.
. Warte bis zur nächsten Angebotsübertragung. +
→ Dies kann bis zu 15 Minuten dauern.
. Deaktivere die Marktplatzverfügbarkeit für den Marktplatz und Mirakl an der Variante.
. Entferne die Eigenschaft für die Katalogverknüpfung an der Variante.
. Lösche das Angebot zu dem Produkt manuell im Backend des Marktplatzes.
. Aktiviere an der entsprechenden Variante die Eigenschaft, die du für das Löschen des Produkts erstellt hast, und hinterlege den Wert *kill*.
. Aktiviere die Eigenschaft für die Katalogverknüpfung an der Variante.
. Warte bis zur nächsten Übertragung der Produkte. +
→  Diese findet über Nacht statt.
. Nachdem du das Produkt gelöscht hast, musst du 24 bis 48 Stunden warten, bis du die gleiche Produkt-ID wieder verwenden darfst.
. Entferne nach der Wartezeit die Eigenschaft, die du für das Löschen des Produkts erstellt hast, von der Variante.
. Aktiviere an der Variante die Marktplatzverfügbarkeit für den Marktplatz und Mirakl erneut.

[#angebotsdaten-uebertragen]
=== Angebotsdaten übertragen

In diesem Kapitel erfährst du, wie du Angebotsdaten an den Marktplatz überträgst und welche Voraussetzungen erfüllt werden müssen. Diese Daten kommen aus dem von dir erstellten Assistenten *{assistant-name}*.


=== Voraussetzungen für die Angebotsdatenübertragung

* Die Plugins link:{marketplace-url}[{market}^]{nbsp}icon:external-link[] sowie *Mirakl Connector* wurden im plentyMarketplace gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte *{market}* und *Mirakl* aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {assistant-name}* wurde die Grundeinrichtung vorgenommen.
** *Bestand synchronisieren* ist im Datenaustausch-Schritt aktiviert, damit die Angebote korrekt übertragen werden.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* sind an einem bestehenden Preis die Auftragsherkünfte *Mirakl* und *{market}* aktiviert *_oder_* ein neuer Verkaufspreis ist erstellt, in dem die Auftragsherkünfte *Mirakl* und *{market}* aktiviert wurden.

Die Angebotsübertragung findet alle 15 Minuten statt. Es werden nur Artikel übertragen, die die folgenden Voraussetzungen erfüllen:

* An der Variante sind die Auftragsherkünfte *Mirakl* und *{market}* aktiviert.
* An der Variante ist ein Preis aktiv, der für *{market}*, *Mirakl* und *WEB-API* aktiviert wurde.
* An dem Artikel (bzw. an der Variante) ist ein Versandprofil aktiv, das für *{market}*, *Mirakl* und *WEB-API* wurde.
* An der Variante ist ein Wert als Marktplatz-SKU für *{market}* hinterlegt.
* An der Variante hat in den letzten 15 Minuten eine Änderung an dem Bestand oder Preis stattgefunden
** Das Setzen eines neuen Zeitstempels über die Gruppenfunktion oder Stapelverarbeitung führt auch zu einer Übertragung der Variante. Somit muss an der Variante die Warenbestandsbeschränkung *Auf Netto-WB* oder *Keine* gewählt sein und die Variante muss positiven Bestand haben.

[IMPORTANT]
.Wie hängen die Angebotsfelder, das Produktexportfeld und die Marktplatz-SKU an der Variante zusammen?
====
Die Angebotsfelder *sku* und *product-id* werden grundsätzlich immer mit dem Wert gefüllt, der an der Variante im Feld *Marktplatz-SKU* für den Marktplatz definiert wurde.
Das Angebotsfeld *product-id-type* wird standardmäßig mit dem Wert *SHOP_SKU* übertragen.

// * Wenn *SKU* gewählt wird, muss die SKU vom Marktplatz als Marktplatz-SKU an der Variante definiert werden.
// * Wenn *EAN* gewählt wird, muss die EAN der Variante als Marktplatz-SKU an der Variante definiert werden. Bitte nicht verwenden, diese Funktion ist noch nicht im Marktplatz aktiv
// * Wenn *ISBN* gewählt wird, muss die ISBN der Variante als Marktplatz-SKU an der Variante definiert werden. Bitte nicht verwenden, diese Funktion ist noch nicht im Marktplatz aktiv

Das Produktexportfeld *Produkt-ID (Artikelnr. des Verkäufers)* wird je nach Einstellung im Katalog gefüllt.
Bei der ersten Übertragung, die über Nacht stattfindet, wird die Marktplatz-SKU an der Variante in plentymarkets automatisch aus der Varianten-ID gebildet. Die Marktplatz-SKU kann alternativ per Import oder manuell definiert werden.
====

[discrete]
=== Weitere Datenfelder, die bei der Angebotsübertragung übermittelt werden

* *sku* und *product-id*: Diese Felder werden automatisch mit dem Wert befüllt, der als Marktplatz-SKU an der Variante hinterlegt wurde.
* *product-id-type*: Dieses Feld wird standardmäßig mit dem Wert *SHOP_SKU* befüllt.
* *price*: Dieses Feld wird automatisch mit dem Wert befüllt, der an der Variante für den am Marktplatz aktivierten Preis definiert wurde. Wurden mehrere Verkaufspreise an der Variante definiert, die ebenfalls für den Marktplatz freigegeben sind, wird der Preis mit der niedrigsten ID exportiert.
* *quantity*: Dieses Feld wird automatisch mit dem Nettobestand oder den summierten Nettobeständen aus den Lagern befüllt, die im Assistent *{assistant-name}* im Schritt *Lagerauswahl* gewählt wurden.
* *min-quantity-alert*: Dieses Feld wird automatisch mit dem Wert *1* übertragen.
* *state*: Dieses Feld wird automatisch mit dem Wert *11* übertragen.
* *available-start-date*: Dieses Feld wird automatisch mit einem Zeitstempel übertragen.
* *price-ranges*: In diesem Feld werden ein oder mehrere <<artikel/einstellungen/preise#100, Verkaufspreise>> übertragen.
* *allow-quote-requests*: Dieses Feld wird automatisch mit dem Wert *false* übertragen.
* *logistic-class*: Dieses Feld ist standardmäßig nicht befüllt. Wenn kein Wert übertragen wird, wird die Variante mit dem kostenlosen Versandprofil *Kostenfreier Versand (free)* verknüpft. Im Assistentenschritt *Zuordnung der Angebots-Eigenschaften* kannst du eine Eigenschaft zuordnen, um pro Variante einen anderen Wert zu übertragen. Die gültigen Versandprofilcodes findest du im {market} Backend unter *Plattformeinstellungen > Versand*. Die Codes werden in Klammern dargestellt.
* *leadtime-to-ship*: Dieses Feld ist ein Pflichtfeld und ist standardmäßig nicht befüllt. Im Assistentenschritt *Zuordnung der Angebots-Eigenschaften* kannst du eine Eigenschaft zuordnen, um pro Variante einen Wert zu übertragen. Hier sind nur ganze Zahlen zwischen 1 und 45 gültig.
* *reversecharge*: Dieses Feld ist ein Pflichtfeld und ist standardmäßig nicht befüllt. Im Assistentenschritt *Zuordnung der Angebots-Eigenschaften* kannst du eine Eigenschaft zuordnen, um pro Variante entweder `true` oder `false` zu übertragen.

[#variantenverfuegbarkeit]
== Variantenverfügbarkeit einstellen

:market-availability: {market}
:option-availability: {market}
:conrad-variantenverfuegbarkeit-aktivieren:
:mirakl-herkunft:

include::../_textblocks/instructions/variantenverfuegbarkeit.adoc[]
