= Amazon einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Amazon, FBA, MFN, Prime, NextDay, SecondDay, Marktplatz, SKU, Multi-Channel, Amazon Business
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz Amazon in Ihrem plentymarkets System ein.
:position: 1

link:https://www.amazon.de/[*Amazon*^] hat sich vom größten Online-Buchhändler zum führenden Universalkaufhaus entwickelt. Unzählige Kunden schätzen die große Auswahl, vertrauen auf eine hohe Warenqualität und erwarten besten Service vom Marktführer wie z.B. eine sehr zeitnahe Warenlieferung. plentymarkets ermöglicht Ihnen die komplette und integrierte Anbindung an Amazon. Erfahren Sie, wie Sie Artikel verfügbar machen, den Datenaustausch über die Schnittstelle aktivieren, den FBA-Service von Amazon nutzen und vieles mehr. FBA ist das Kürzel für Fulfillment by Amazon, einem Service von Amazon, bei dem Amazon die Lagerhaltung sowie die gesamte Logistik übernimmt.

Das folgende Video-Tutorial veranschaulicht, wie schnell es gehen kann, Artikel auf Amazon hochzuladen:

video::193888643[vimeo]

[#100]
==  Bei Amazon registrieren

Bevor Sie Einstellungen in plentymarkets vornehmen, registrieren Sie sich bei Amazon als Verkäufer. Die zentrale Anlaufstelle für Verkäufer bei Amazon ist Amazon Seller Central. Händler, die mehr als 40 Artikel im Monat verkaufen, werden bei Amazon als sogenannte Power-Anbieter geführt und haben auch erst ab dieser Stufe die Möglichkeit zum Upload von Artikellisten. Wählen Sie als plentymarkets Nutzer die Option Power-Anbieter, da nur mit diesem Konto Lagerbestand und Angebote durch Automatismen und APIs verwaltet werden können. Bei dieser Option fällt eine monatliche Grundgebühr sowie weitere Gebühren beim Verkauf an. Weitere Informationen dazu erhalten Sie auf der *link:http://www.amazon.de/b/ref=nav_cs_sell/279-9008302-8223762?ie=UTF8&node=2383621031[Website von Amazon^]*.

Nachdem Sie sich registriert haben, richten Sie bei Amazon die link:https://developer.amazonservices.de/gp/mws/index.html[MWS-Schnittstelle^] ein. MWS steht für Marketplace Web Service. Dieser Service unterstützt API-Funktionen und muss daher für den Datenaustausch mit plentymarkets eingerichtet werden. Wählen Sie die MWS-Option, die den Zugriff einer Anwendung auf Ihr Amazon-Konto ermöglicht. Sie benötigen folgende Informationen für die Schnittstelle:

*  Name der Anwendung: plentymarkets
*  MWS-Kontonummer EU-Marktplätze: 6860-7675-7360
*  MWS-Kontonummer Marktplatz USA: 5751-6263-3716

Wenn Sie Amazon MWS eingerichtet haben, erhalten Sie die Verkäufer-ID, die Sie zum Einrichten der Schnittstelle in plentymarkets benötigen.

[#200]
==  Amazon in plentymarkets einrichten

Nehmen Sie die folgenden Einstellungen in plentymarkets vor, um die Schnittstelle zu Amazon einzurichten.

[#300]
===  Konto einrichten

Richten Sie zunächst ein neues Konto für Amazon in plentymarkets ein.

[.instruction]
Neues Konto anlegen:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Einstellungen*.
.  Klicken Sie auf *Neues Konto*. +
→ Das Fenster *Neues Amazon Seller Central-Konto erstellen* wird geöffnet.
.  Wählen Sie eine *Amazon-Plattform* aus.
.  Tragen Sie die *E-Mail-Adresse* ein, die Sie für die Plattform verwenden.
.  Klicken Sie auf *Neues Konto erstellen*. +
→ Das Konto wird angelegt.
.  Klicken Sie links auf das zuvor angelegte Konto in der Kontenübersicht.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dabei die Erläuterungen in den Tabellen 1 bis 4.
. *Speichern* Sie die Einstellungen.



[TIP]
.Europäisches Verkäuferkonto
====
"Amazon hat seine europäischen Marktplätze vereint. Dies ermöglicht Ihnen, Produktangebote für alle Amazon-Marktplätze in Deutschland, Frankreich, Großbritannien, Spanien und Italien zu erstellen und zu verwalten. Sie haben die Kontrolle darüber, was Sie wo verkaufen. Ihre Geschäfte wickeln Sie komfortabel über ein einziges Verkäuferkonto ab. Ihr Verkäuferkonto ermöglicht Ihnen automatisch, Ihre Angebote auch auf Amazon.co.uk, Amazon.fr, Amazon.es und Amazon.it zu verkaufen. Sie werden aufgefordert, einen Heimat-Marktplatz zu bestimmen, wobei jeder dieser 4 Marktplätze gewählt werden kann. Wir empfehlen Ihnen, als Heimat-Marktplatz das Land zu wählen, von dem aus Sie operieren und Ihre Bestellungen erfüllen." (Quelle: Amazon) +
Beachten Sie die weiteren link:http://services.amazon.de/programme/verkaufen-bei-amazon/ein-europisches-konto/[Informationen zum europäischen Verkäuferkonto^] sowie die link:http://services.amazon.de/faq-fuer-das-europaeische-verkaeuferkonto/[*FAQ*^] von Amazon.
====

[.subhead]
Amazon-Plattform

Wenn Sie mit einem europäischen Verkäuferkonto mehrere Amazon-Plattformen nutzen, richten Sie in plentymarkets für jede Plattform ein neues Konto mit plattformspezifischen Konfigurationen ein. Die Zugangsdaten sind für alle Plattformen gleich.

[#400]
===  Basiseinstellungen vornehmen

Alle Angaben im Bereich *Zugangsdaten* des Tabs *Einstellungen* sind Pflichtangaben. Tragen Sie die Angaben ein und beachten Sie die Erläuterungen in Tabelle 1.

.Einstellungen für *Zugangsdaten*
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Amazon-Plattform*
| Eine Plattform muss direkt beim Anlegen gewählt werden und kann hier geändert werden. Wenn Sie ein europäisches Verkäuferkonto haben, richten Sie für jede Plattform, auf der Sie verkaufen möchten, eine eigene Konfiguration ein.

|*Verkäufer-ID*
| Verkäufer-ID eintragen, wie von Amazon erhalten. Wenn Sie ein europäisches Verkäuferkonto haben, ist die Verkäufer-ID für jede Plattform die selbe.

|*Händler-Token*
| Händler-Token eintragen, wie im Seller Central zu finden.

|*E-Mail-Adresse*
| E-Mail-Adresse eintragen, die als Benutzername zum Seller Central-Konto verwendet wird.

|*Aktiv*
| Häkchen setzen, um die Schnittstelle zu aktivieren. +
Damit nicht schon im Vorfeld unerwünscht Daten übertragen werden, Schnittstelle erst aktivieren, wenn alle Einstellungen vorgenommen wurden.

|*B2B*
| Durch setzen des Häkchens wird dieses Konto für Amazon Business freigeschaltet.
|====

Im Bereich *Basiseinstellungen* nehmen Sie u.a. Einstellungen für den SKU-Aufbau vor. Die SKU (Stock Keeping Unit) ist eine eindeutige Referenznummer für alle Artikel und Artikelvarianten bei Amazon.

.Einstellungen im Tab *Basiseinstellungen*
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Mandant*
| Mandant wählen, für den Aufträge von Amazon zugeordnet werden.

|*SKU-Aufbau*
| Eine der folgenden Optionen wählen: +
*Variantenl-ID* +
*EAN wenn vorhanden, sonst Varianten-ID* +
*Variantennummer wenn vorhanden, sonst Varianten-ID* +
Die hier gewählte Einstellung greift nur für Artikel, die zum ersten mal zu Amazon exportiert werden. SKUs sind die Basis, auf der Amazon und Ihr Webshop künftig Daten austauschen. +
*Wichtig*: Diese Einstellung nicht mehr ändern, nachdem Artikel an Amazon übertragen wurden, da sonst die Kommunikation zwischen plentymarkets und Amazon (z.B. für Bestands-Updates) nicht mehr funktioniert. +
Anmerkung zu *Bereits bestehende SKU-Nummern zuordnen* unterhalb der Tabelle beachten.

|*Katalog wurde mit SSW gelistet*
|*Ja* = Artikel werden auf Amazon mit *link:https://ssw.starsellersworld.com/[starsellersworld^]* gelistet. Beim Auftragsimport wird dann die SKU des Artikels nach dem letzten "-" abgeschnitten, um eine Zuordnung des Artikels im System zu ermöglichen. +
*Nein* = Artikel werden auf Amazon nicht mit starsellersworld gelistet.

|*Rechnung erzeugen*
| Auswählen, ob die Rechnung von plentymarkets oder Amazon erzeugt werden soll. +
*plentymarkets* = Die Rechnung wird von plentymarkets erzeugt. +
*Amazon VCS* = Die Rechnung wird von Amazon erzeugt.
|====

[TIP]
.SKU-Einstellungen und Warenbestandsabgleich
====
Wenn Sie die Einstellungen für die SKU-Nummern bei allen Plattformen gleich wählen, können Sie mit einem Warenbestandsabgleich alle Plattformen des europäischen Verkäuferkontos abgleichen. Wenn die Einstellungen unterschiedlich sind, muss der Abgleich für jede Plattform separat durchgeführt werden.

Da der Warenbestand bei einem Europäischen Verkäuferkonto global verwaltet wird, genügt es, beim Heimat-Marktplatz den Bestand zu aktivieren. Voraussetzung dafür ist die Übereinstimmung der SKU-Einstellungen.
====

[IMPORTANT]
.Bereits bestehende SKU-Nummern zuordnen
====
Wenn Sie bereits auf Amazon verkaufen und nun anfangen möchten Ihre Artikel über plentymarkets auf Amazon zu verkaufen, ordnen Sie Ihre bestehenden SKU-Nummern Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen » Tab: Verfügbarkeit* zu.
====

[IMPORTANT]
.plentymarkets E-Mail-Adressen autorisieren
====
Alle plentymarkets E-Mail-Adressen, über die Sie Nachrichten an Amazon schicken, müssen zuvor bei Amazon im Seller Central-Bereich autorisiert werden.
====

Erfahren Sie mehr dazu im folgenden Video-Tutorial:

video::197494468[vimeo]

[#500]
===  Artikeleinstellungen vornehmen

Im Tab *Artikeleinstellungen* nehmen Sie Einstellungen zum Artikelexport vor. Sie legen u.a. Automatismen und Exportfilter fest.

.Einstellungen im Tab *Artikeleinstellungen*
[cols="1,3"]
|====
| Einstellung | Erläuterung

2+| Automatismen

|*Artikelexport; +
Preisänderungen; +
Bestandsabgleich; +
Bestandsänderungen*
| Keine Übertragung oder je ein Intervall für die Übertragung wählen.

2+| Exportfilter

|*Artikelverfügbarkeit; +
Export-Kategorien; +
BMVD-Export-Kategorien; +
Markierung 1; +
Markierung 2; +
Shop-Artikel*
| Nur Artikel mit den gewählten Filtern werden exportiert. +
*Artikelverfügbarkeit* = Wenn ein Parent (Hauptartikel) eine nicht freigegebene Verfügbarkeit hat, findet keine Übertragung statt. +
*Markierung 1* und *2* = Diese Filter greifen nur für den nächtlichen Export.

2+| Exporteinstellungen

|*Artikelname; +
Artikelbeschreibung*
| Die eingestellten Informationen werden exportiert.

|*HTML-Tags erlauben*
| Die folgenden Tags sind zugelassen: &lt; br &gt;, &lt; b &gt;, &lt; i &gt;, &lt; p &gt; ,&lt; ul &gt;, &lt; li &gt;, &lt; table &gt;, &lt; tr &gt;, &lt; td &gt;, &lt; th &gt;, &lt; tbody &gt; und &lt; strong &gt;.

|*Lagerauswahl*
|*Bestandsmenge des Vertriebslagers mit aktuell größtem Bestand übertragen*, *Hauptlager des Artikels verwenden*, *Summe der Bestandsmengen aller Vertriebslager übertragen* oder *Lager wählen* für den Export wählen. Bei der Option *Lager wählen* erscheint direkt darunter die Einstellung *Lager*, bei der ein oder mehrere Lager gewählt werden.

|*Lager*
| Ein oder mehrere Lager wählen. Diese Einstellung erschein nur, wenn unter Lagerauswahl die Option *Lager wählen* gewählt wurde. Die Bestände der gewählten Lagern wird summiert und zu Amazon übermittelt. Dabei werden auch Puffer und Maximalwerte berücksichtigt. Somit können auf bestimmten Amazon-Konten oder Amazon-Plattformen gezielt der Bestände gewisser Lager angeboten werden.

|*Bestandspuffer*
| Ist der Artikel auf Netto-Warenbestand beschränkt, wird der exportierte Bestand um den eingetragenen Wert verringert.

|*Maximaler Warenbestand*
| Bestimmt die obere Grenze des exportierten Bestands für alle Artikel. Diese Einstellung hat Priorität vor der unten beschriebenen Einstellung *Menge für Artikel ohne Bestandsbindung*.

|*Menge für Artikel ohne Bestandsbindung*
| Bei Artikeln mit der Einstellung *keine Beschränkung* wird der Maximalwert aus realem Bestand und der hier definierten Menge übermittelt. +
*Beispiel*: Einstellung 0, Nettowarenbestand 8. plentymarkets übermittelt 8. +
Artikel mit der Einstellung *Beschränkung auf Netto-Warenbestand* werden hier nicht berücksichtigt.

|*Durchschnittliche Lieferzeit*
|*Nicht übertragen*, *"Mittlere Lieferzeit in Tagen" übermitteln* oder *"Mittlere Lieferzeit in Tagen" übermitteln + Lieferverzugsaufschlag* wählen.

|*Bearbeitungszeit*
| Lieferverzugsaufschlag in Tagen eintragen. Wird nur angezeigt, wenn bei *Durchschnittliche Lieferzeit* die Option *"Mittlere Lieferzeit in Tagen" übermitteln + Bearbeitungszeit* gewählt wurde.

|*Artikelnummer des Herstellers*
| Wählen, ob SKU, Variantennummer, GTIN, Varianten-ID, Modellnummer oder kein Wert im Feld part_number der CSV-Datei übertragen werden soll.
|====

Erfahren Sie mehr zu den Artikeleinstellungen für Amazon im folgenden Video-Tutorial:

video::197490065[vimeo]

[#600]
===  Auftragseinstellungen vornehmen

Im Tab *Auftragseinstellungen* nehmen Sie Einstellungen zum Versand vor. Das Kürzel MFN steht für merchant-fulfilled network, d.h. die Abwicklung erfolgt durch den Händler.

.Einstellungen im Tab *Auftragseinstellungen*
[cols="1,3"]
|====
| Einstellung | Erläuterung

2+| Eigener Versand (MFN)

|*Auftragsimport*
| Keine Übertragung oder je ein Intervall für den Import wählen.

|*Versandbestätigung*
| Keine Übertragung oder je ein Intervall für den Export der Versandbestätigung an Amazon wählen.

|*Auftragsposition*
| Bestimmt die Darstellung des Artikelnamens in der Auftragsposition. Eine der folgenden Optionen wählen: +
*Artikelname aus Shop übernehmen* +
*Artikelname von Amazon übernehmen - mit SKU* +
*Artikelname von Amazon übernehmen - ohne SKU*

|*Zahlungseingang*
|*Zahlungseingang gebucht* wählen, wenn der Zahlungseingang bei Auftragsimport als gebucht angezeigt werden soll.

|*Status für übertragene Retouren*
|<<auftragsabwicklung/auftraege/auftraege-verwalten#, *Auftragstatus*>> für Retouren wählen, die erfolgreich an Amazon gemeldet wurden.

|*Status für nicht übertragene Retouren*
|<<auftragsabwicklung/auftraege/auftraege-verwalten#, *Auftragstatus*>> für Retouren wählen, die nicht erfolgreich an Amazon gemeldet wurden.

|*Austehende Aufträge*
| Wählen, ob ausstehende Aufträge von Amazon alle 15 Minuten importiert werden sollen, oder nie.

|*Gutschriftenimport*
| Wählen, ob Gutschriften in Ihr plentymarkets System importiert werden sollen. Nutzen Sie diese Option für Amazon FBA (= Versand durch Amazon). Weitere Informationen finden Sie im Kapitel <<Gutschriften automatisch importieren, Gutschriften automatisch importieren>>. +
Diese Funktion muss von plentymarkets freigeschaltet werden. Wenden Sie sich dazu an einen plentymarkets Supporter. +
*Ja* = Gutschriften werden einmal täglich in Ihr plentymarkets System importiert. +
*Nein* = Es findet kein Gutschriftenimport statt. +
Der Gutschriftenimport ist standardmäßig deaktiviert.

2+| Versand durch Amazon (FBA)

|*Herkunft*
| Wählen, ob nur Aufträge von Amazon mit FBA abgewickelt werden oder ob auch Aufträge von anderen <<omni-channel/auftragsherkunft#, *Herkünften*>> mit FBA abgewickelt werden können.

|*Auftragsimport*; +
*Retourenimport*; +
*Bestandsimport*
| Keine Übertragung oder je ein Intervall für den Import wählen.

|*Status*
|<<auftragsabwicklung/auftraege/auftraege-verwalten#, *Status*>> der Aufträge wählen, die von Amazon importiert wurden.

|*Lager*
| Wählen, welches <<omni-channel/multi-channel/amazon/amazon-einrichten#10, *Amazon FBA-Lager*>> für den Bestandabgleich des Kontos verwendet werden soll. Dieses Lager wird auch für die FBA-Auftragszuordnung des Kontos verwendet, falls kein FBA-Auftrag aufgrund eines nicht konfigurierten Lagers für das Auftragsland zugeordnet werden konnte.

|*Warenausgang*
| Wählen, ob der Warenausgang als gebucht markiert werden soll oder nicht. Die Option *Als gebucht markieren* erzeugt keine Warenbewegung. Um eine Warenbewegung zu erzeugen, muss die Option *Nicht als gebucht markieren* eingestellt sein und eine Ereignisaktion eingerichtet werden.

|*Status für übertragene Aufträge*
|<<auftragsabwicklung/auftraege/auftraege-verwalten#, *Auftragstatus*>> für Aufträge wählen, die erfolgreich an FBA übertragen wurden.

|*Gutschein bei Retouren berücksichtigen*
| Wählen, ob Gutscheine bei FBA-Retouren berücksichtigt werden sollen. Wurde der FBA-Auftrag komplett oder teilweise mit einem Gutschein beglichen, wird der Gutschein bei der Retoure hinzugefügt und verrechnet. Dabei wird kein Mindestbestellwert für den Gutschein berücksichtigt.

|*Versandkategorie*
|*Standard* = normaler Versand, *Expedited* = Schnellversand oder *Priority* = bevorzugt (schnellster Versand) wählen.
|====

Erfahren Sie mehr zu den Auftragseinstellungen für Amazon im folgenden Video-Tutorial:

video::197490845[vimeo]

[#650]
=== Bestellberichte abrufen

Im Tab *Prozessstatus* rufen Sie Informationen zu den Bestellberichten Ihrer MFN-Aufträge ab. Über den Button *Zeitplan abrufen* wird der Intervall, in dem die Bestellberichte von Amazon generiert werden und der Zeitpunkt des nächsten Abrufs von Ihrem plentymarkets Systems angezeigt.

[#660]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit Amazon-Plattformen verknüpfen können, muss im Menü *System » Aufträge » Auftragsherkunft* die Auftragsherkunft für die Amazon-Plattformen aktiviert werden.

[.instruction]
Auftragsherkunft für Amazon aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Auftragsherkunft*.
. Setzen Sie bei den gewünschten Amazon-Plattformen ein Häkchen.
. *Speichern* Sie die Einstellungen.


[#700]
==  Artikelverfügbarkeit einstellen

Artikel, die Sie auf Amazon verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID*>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Amazon-Länderplattform einstellen:

.  Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
.  Wechseln Sie in das Tab *Verfügbarkeit*.
.  Klicken Sie im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Wählen Sie *Web-API*.
. Klicken Sie auf *Hinzufügen*.
.  Aktivieren Sie in der gleichen Liste die Amazon-Länderplattform(en), für die der Artikel verfügbar sein soll.
.  Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen.
.  Wechseln Sie in das Tab *Multi-Channel*.
.  Nehmen Sie die Einstellungen im Bereich *Amazon* vor. Beachten Sie dazu die Erläuterungen in Tabelle 5.
. *Speichern* Sie die Einstellungen.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

.Artikelverfügbarkeit für Amazon einstellen
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Amazon-Produkttyp*
|<<basics/datenaustausch/export-import/datenformate/item#50, *Amazon-Produkttyp*>> wählen.

|*Amazon-Abwicklung (FBA)*
| Einen der Amazon-Marktplätze *AMAZON_EU* (Europa), *AMAZON_FE* (Ferner Osten), *AMAZON_NA* (Nordamerika) wählen, wenn der Artikel über FBA vermarktet werden soll.

|*Versand durch Amazon (FBA)*
| Aktivieren, wenn die FBA-Funktion genutzt werden soll und wenn FBA-Bestände und Multi-Channel-Bestände importiert werden sollen.
|====

[IMPORTANT]
.Artikelverfügbarkeit für MFN und FBA
====
Wenn Sie Ihre Artikel für MFN und FBA verfügbar stellen wollen, wählen Sie, am Beispiel für Deutschland, die Amazon Länderplattform *Amazon Germany* und die Länderplattform *Amazon FBA Germany.*
====

Erfahren Sie mehr im folgenden Video-Tutorial:

video::199993489[vimeo]

[#750]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID*>> im Tab *Verfügbarkeit* fügen Sie, wenn nötig, manuell marktplatzspezifische SKUs sowie Parent-SKUs hinzu. Wenn Sie z.B. bereits  auf Amazon verkaufen und nun anfangen möchten Ihre Artikel über plentymarkets auf Amazon zu verkaufen, ordnen Sie Ihre bestehenden SKU-Nummern in diesem Menü zu. Alternativ können SKUs über das Datenformat VariationSKU importiert werden.

[.instruction]
SKU hinzufügen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechseln Sie in das Tab *Verfügbarkeit*.
.  Klicken Sie im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
.  Wählen Sie die Herkunft *Amazon*, um die SKU hinzuzufügen.
.  Wählen Sie das dazugehörige Marktplatzkonto.
.  Geben Sie die SKU ein.
.  Geben Sie die Parent-SKU ein.
.  Klicken Sie auf *Hinzufügen*. +
→ Die SKUs werden gespeichert und angezeigt.

SKUs können nachträglich geändert werden. Beachten Sie allerdings, dass SKU-Änderungen dazu führen können, dass Amazon die Artikel nicht mehr erkennen bzw. zuordnen kann.

[IMPORTANT]
.Parent-SKU
====
Parent-SKUs können sowohl für den Artikel als auch für Varianten hinterlegt werden. Die manuelle SKU-Pflege erlaubt es, für Varianten eines Artikels die Parent-SKU komplett anderer Artikelvarianten zu vergeben. So kann z.B. für einen Artikel mit 5 Varianten, 5 mal die Parent-SKU einer Variante, die einem ganz anderen Artikel amgehört, vergeben werden. Diese Varianten werden auf Amazon als Varianten des Artikels, mit dessen Parent-SKU sie verknüpft sind, gelistet.  +
Wird bei einer Variente eine andere Parent-SKU vergeben als bei den restlichen Varienten eines Artikels, werden auf Amazon zwei verschidenen Artikel gelistet, aber in plentymarkets muss dafür nur ein Artikel gepfelgt werden.
====

[#760]
==  Amazon-Auftragsimport-SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID*>> im Tab *Verfügbarkeit* fügen Sie, wenn nötig, manuell SKUs hinzu, die nur beim Amazon-Auftragsimport berücksichtigt werden. Alternativ können Auftragsimport-SKUs über das Datenformat VariationAdditionalSKU importiert werden.

[.instruction]
SKU hinzufügen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechseln Sie in das Tab *Verfügbarkeit*.
.  Klicken Sie im Bereich *Amazon-Aufragsimport-SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue Auftragsimport-SKU* wird angezeigt.
.  Wählen Sie die Herkunft *Amazon*, um die SKU hinzuzufügen.
.  Wählen Sie das dazugehörige Marktplatzkonto.
.  Geben Sie die SKU ein.
.  Klicken Sie auf *Hinzufügen*. +
→ Die SKUs werden gespeichert und angezeigt.

SKUs können nachträglich geändert werden.

[#800]
==  Verkaufspreis festlegen

Gehen Sie wie im Folgenden beschrieben vor, um für Amazon-Länderplattformen einen Verkaufspreis festzulegen. Dieser Preis wird auf den Länderplattformen angezeigt.

[.instruction]
Verkaufspreis für Länderplattformen festlegen:

.  Öffnen Sie das Menü *System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
.  Setzen Sie ein Häkchen bei der gewünschten Amazon-Länderplattform.
.  Setzen Sie ein Häkchen bei dem gewünschten Amazon-Konto.
. *Speichern* Sie die Einstellungen.

[#850]
==  Aktionspreis festlegen

Um Aktionspreise an Amazon zu übermitteln, muss in den Verkaufspreisen ein Aktionspreis hinterlegt und mit dem Artikel verknüpft sein. Zudem müssen die Merkmale *SaleStartDate* und *SaleEndDate* angelegt und mit dem Artikel verknüpft sein. Gehen Sie wie im Folgenden beschrieben vor, um für Amazon-Artikel Aktionspreise festzulegen.

[.instruction]
Aktionsspreis für Amazon-Länderplattformen festlegen:

.  Öffnen Sie das Menü *System » Artikel » Verkaufspreise » Verkaufspreis öffnen » Tab: Einstellungen*.
.  Setzen Sie in der Zeile *Preistyp* ein Häkchen bei *Aktionspreis*.
.  Setzen Sie ein Häkchen bei der gewünschten Amazon-Länderplattform.
.  Setzen Sie ein Häkchen bei dem gewünschten Amazon-Konto.
. *Speichern* Sie die Einstellungen.

Verknüpfen Sie anschließend diesen Aktionspreis mit dem Artikel im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Einstellungen*.

Als nächstes legen Sie die Merkmale *SaleStartDate* und *SaleEndDate* an und verknüpfen diese mit dem Amazon-Produkttyp. Gehen Sie wie im Folgenden beschrieben vor, um das Merkmal *SaleStartDate* anzulgen und zu verknüpfen. Gehen Sie beim Merkmal *SaleEndDate* analog vor, wobei Sie als Namen *SaleEndDate* eingeben und  bei der Verknüpfung das Amazon-Feld *sale_end_date* wählen.

[.instruction]
Merkmal für Aktionspreis anlegen und mit Amazon-Produkttyp verknüpfen:

.  Öffnen Sie das Menü <<artikel/artikel-verwalten#480, *System » Artikel » Merkmale » Tab: Neues Merkmal*>>.
.  Geben Sie den Namen *SaleStartDate* in der Zeile *Namen (Intern)* ein. +
→ Für das Merkmal darf kein anderer Name benutzt werden, da sonst der Aktionspreis nicht an Amazon übermittlet wird.
. Wählen Sie als Merkmaltyp *Text* aus der Dropdown-Liste.
.  Wählen Sie bei *Amazon-Verknüpfung* den Produkttyp. +
→ Eine neue Dropdown-Liste erscheint.
.  Wählen Sie in der Dropdown-Liste das Amazon-Feld *sale_from_date*.
.  Klicken Sie auf *Hinzufügen*. +
→ Die Verknüpfung wird angelegt.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfen Sie anschließend die Merkmale mit dem Artikel und geben jeweils das Datum im Format *JJJJ-MM-TT*ein.

[#900]
==  Frei definierbare Felder im Amazon-Export Seller Central einrichten

Die frei definierbaren Felder dienen der Anpassung der Daten, die Sie zu Amazon exportieren. Diese Felder müssen mit *<<artikel/artikel-verwalten#70, Freitextfeldern>>* verknüpft werden. Die Freitextfelder ermöglichen Ihnen wiederum eine individuelle Anpassung der Artikeldaten und somit eine genaue Beschreibung der Artikel.

[#1000]
===  Freitextfelder anlegen

Legen Sie im ersten Schritt die <<artikel/artikel-verwalten#70, *Freitextfelder*>> an, die Sie mit den frei definierbaren Feldern bei Amazon verknüpfen möchten. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Freitextfelder anlegen:

.  Öffnen Sie das Menü *System » Artikel » Freitextfelder*.
.  Tragen Sie unter *Feldbezeichnung* den Namen ein.
.  Wählen Sie den *Datentyp* aus der Dropdown-Liste.
.  Tragen Sie die maximal mögliche *Zeichenlänge* für das Freitextfeld ein.
. *Speichern* Sie die Einstellungen. +
→ Die Freitextfelder stehen am nächsten Tag im Bearbeitungsfenster der Artikel im Tab *Felder* zur Verfügung. Dort tragen Sie den eigentlichen Text ein.

[#1100]
===  Freitextfelder verknüpfen

Nachdem Sie die Freitextfelder konfiguriert haben, verknüpfen Sie diese wie im Folgenden beschrieben mit den Exportfeldern bei Amazon Seller Central.

[.instruction]
Freitextfelder mit Amazon-Exportfeldern verknüpfen:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Frei definierbare Felder*.
.  Öffnen Sie das Untermenü *Frei definierbare Felder im Amazon-Export (Seller Central)*.
.  Klappen Sie die Kategorie auf.
.  Wählen Sie ein *Exportfeld* aus der Dropdown-Liste.
.  Wählen Sie das passende Feld aus der Dropdown-Liste *Freitextfeld*. +
→ Es stehen nur Felder zur Auswahl, die Sie angelegt haben.
. *Speichern* Sie die Einstellungen.

[#1200]
==  Frei definierbare Felder im Amazon-Export Marketplace einrichten

Frei definierbare Felder im Amazon-Export Marketplace verknüpfen Sie für die BMVD-Kategorien Bücher, Musik, Video und DVD.

[.instruction]
Freitextfelder verknüpfen:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Frei definierbare Felder*.
.  Öffnen Sie das Untermenü *Frei definierbare Felder im Amazon-Export (Marketplace)*.
.  Wählen Sie die Freitextfelder aus den Dropdown-Listen aus.
. *Speichern* Sie die Einstellungen.
.  Öffnen Sie das Menü *System » Artikel » Freitextfelder*.
.  Tragen Sie bei den eben gewählten Freitextfeldern unter *Feldbezeichnung* den Namen ein.
.  Wählen Sie aus der Dropdown-Liste in der Spalte *Datentyp* einen Typ aus.
.  Tragen Sie die maximal mögliche *Zeichenlänge* für das Freitextfeld ein.
. *Speichern* Sie die Einstellungen. +
→ Am nächsten Tag stehen diese Freitextfelder dann im Bearbeitungsfenster der Artikel im Tab *<<artikel/artikel-verwalten#70, Felder>>* zur Verfügung. Dort tragen Sie dann die *Ziffern* gemäß der Tabellen 6 und 7 ein.

[TIP]
.Freitextfelder mit Einschränkung
====
Für die Felder *item-condition* und *will-ship-internationally* sind nur vorgegebene Werte möglich. Das Feld *item-note* kann als Textfeld genutzt und für jeden Artikel neu formuliert werden.
====

[IMPORTANT]
.Amazon-Produkttyp und Artikeldaten eintragen
====
Damit der Export richtig funktioniert, muss im Menü *Artikel » Artikel bearbeiten* im Tab *Multi-Channel* der *Amazon-Produkttyp* ausgewählt sein: *Marketplace - Bücher*, *Marketplace - Musik*, *Marketplace - Video*, *Marketplace - DVD*. Des Weiteren muss in den Artikeldaten entweder eine *EAN*, *UPC* oder *ISBN* eingetragen sein.
====

Folgende Werte sind für das Feld *item-condition* möglich:

.Optionen für das Feld *item-condition*
[cols="1,3"]
|====
| Ziffer | Bedeutung

|*1*
| Used, Like New (Gebraucht, wie neu)

|*2*
| Used, Very Good (Gebraucht, sehr gut)

|*3*
| Used, Good (Gebraucht, gut)

|*4*
| Used, Acceptable (Gebraucht, annehmbar)

|*5*
| Collectible, Like New (Sammlerstück, wie neu)

|*6*
| Collectible, Very Good (Sammlerstück, sehr gut)

|*7*
| Collectible, Good (Sammlerstück, gut)

|*8*
| Collectible, Acceptable (Sammlerstück, annehmbar)

|*9*
| Not used (Nicht benutzt)

|*10*
| Refurbished (for computers, kitchen &amp; housewares, electronics, and camera &amp; photo only) (B-Ware)

|*11*
| New (Neu)
|====

Folgende Werte sind für das Feld *will-ship-internationally* möglich:

.Optionen für das Feld *will-ship-internationally*
[cols="1,3"]
|====
| Ziffer | Bedeutung

|*7*
| Versand innerhalb Deutschlands

|*8*
| Versand innerhalb Europas (auch Nicht-EU-Länder)

|*9*
| Versand innerhalb der EU, der Schweiz und Liechtenstein

|*10*
| Versand weltweit
|====

[#1300]
==  Kategorien verknüpfen

Damit Ihre Artikel beim Export zum Marktplatz Amazon automatisch in die dort vorhandenen Kategorien einsortiert werden, müssen Sie in plentymarkets bestimmte Informationen in Ihren Kategorien eintragen. Amazon stellt dazu Klassifikationslisten bereit, die sogenannten Browse Tree Guides (BTG). Diese Listen im Format MS Excel (.xls) enthalten eindeutige Klassifikationsnummern, die Browse Node IDs, die Sie Ihren Kategorien im Webshop zuweisen müssen. Die Listen sind über das Hilfe-Center im Seller Central abrufbar oder über diesen *link:https://sellercentral-europe.amazon.com/gp/help/help-folder.html/?ie=UTF8&itemID=1661[Link^]*.

Mit der Verwendung der offiziellen Amazon.de Browse Tree Guides stellen Sie sicher, dass Ihre Produkte schnell und einfach im Katalog von Amazon.de gefunden werden. Die genannten Klassifikationsnummern bilden die Grundlage für die Produktzuordnung sowohl in der Navigation als auch für die Produktsuche. Angesichts der Vielzahl der bei Amazon.de angebotenen Artikel entscheidet eine eindeutige Zuordnung Ihrer Artikel zu diesen Browse Node IDs darüber, ob Kunden Ihre Produkte in den entsprechenden Kategorien finden können oder nicht. Nehmen Sie sich also für den nächsten Schritt etwas Zeit und wählen Sie die Browse Node IDs sorgfältig aus.

Die Kategorieverknüpfung führen Sie im Menü *System » Märkte » Amazon » Kategorieverknüpfung* durch. In plentymarkets können Sie jeder Artikelkategorie bis zu zwei Amazon-Klassifikationsnummern aus den Browse Tree Guides zuweisen.

Die eingetragenen Werte müssen unbedingt pro Zeile separat verknüpft werden.

Die Kategorieverknüpfungen werden nur für Standard-Kategorien berücksichtigt, die im Menü <<artikel/artikel-verwalten#300, *Artikel » Artikel bearbeiten » Tab: Kategorien*>> des Artikels gewählt wurden.

[.instruction]
Amazon-Kategorien verknüpfen:

.  Rufen Sie über diesen *link:https://sellercentral-europe.amazon.com/gp/help/help-folder.html/?ie=UTF8&itemID=1661[Link^]* das Hilfe-Center im Seller Central auf.
.  Wählen Sie die Klassifikationsliste, z.B. Bekleidung.
.  Suchen Sie in der Spalte *Kategorie* nach der Produktbezeichnung, z.B. Bluse.
.  Öffnen Sie das Menü *System » Märkte » Amazon » Kategorieverknüpfung* in Ihrem plentymarkets Backend.
.  Tragen Sie die Browse Node ID aus der Liste in die Tabelle bei der entsprechenden Kategorie ein.
.  Klicken Sie auf das *Zahnrad* in der Zeile der Kategorie, um die Verknüpfungen herzustellen.

[IMPORTANT]
.Export der Browse Node ID
====
Die bei der Kategorieauswahl zugeordnete Browse Node ID wird beim Datenexport in das Feld *RecommendedBrowseNode1* übertragen. Das Feld *RecommendedBrowseNode2* wird nur für mehrfach verknüpfte Kategorien verwendet.
====

[#1350]
== Attribute und Attributwerte verknüpfen

Auch <<artikel/artikel-verwalten#390, *Attribute*>> müssen verknüpft werden, bevor Ihre Artikel zu Amazon übertragen werden können. Die Attributverknüpfung ist für Amazon auch mehrsprachig möglich.

[.instruction]
Attribute und Attributwerte verknüpfen:

. Öffnen Sie das Menü *System » Artikel » Attribute*. +
→ Die Übersicht aller in Ihrem Katalog verwendeten Attribute wird geöffnet.
. Klappen Sie ein Attribut auf.
. Wechseln Sie in das Tab *Attributverknüpfung*.
. Klicken Sie auf *Amazon*.  +
→ Der Bereich Amazon für die Attributverknüpfung wird geöffnet.
. Wählen Sie die passende Amazon-Kategorie aus dem Drop-Down-Menü.
. Geben Sie die zu Ihren Attributwerten passendenn Amazon-Attributwerte ein.
. *Speichern* Sie die Einstellungen.
. Wiederholen Sie den Vorgang für alle weiteren Attribute.

Als nächsten Schritt aktivieren Sie die Attribute in den Artikeleinstellungen.

[IMPORTANT]
.Hauptvariante ohne Attributverknüpfung deaktivieren
====
Wenn ein Artikel Varianten mit Attributverknüpfungen hat, aber die Hauptvariante keine Attributverknüpfung besitzt, muss die Hauptvariante auf inaktiv gestellt werden, damit diese nicht als Einzelartikel exportiert wird. Hat die Hauptvariante eine Attributverknüpfung, muss sie auf aktiv gestellt sein.
====

[#1400]
==  Merkmal mit Amazon-Produkttyp verknüpfen

Für den Fall, dass Sie für den Marktplatz Amazon die Definition von Parametern bzw. Eigenschaften für die Artikel benötigen, die Sie nicht direkt mit plentymarkets einrichten können, haben wir die hier beschriebene Lösung entwickelt: Die Integration der Parameter bzw. Werte wird über die Merkmale realisiert.

Die Verknüpfung des Merkmals eines Artikels mit dem Amazon-Produkttyp erfolgt im Menü <<artikel/artikel-verwalten#480, *System » Artikel » Merkmale*>>. In plentymarkets können maximal 8 Verknüpfungen pro Merkmal gespeichert werden.

[.instruction]
Merkmal mit Amazon Produkttyp verknüpfen:

.  Öffnen Sie das Menü *System » Artikel » Merkmale*.
.  Klappen Sie das Merkmal auf, das Sie für Amazon verwenden möchten. +
→ Der Bearbeitungsbereich des Merkmals wird geöffnet.
.  Wählen Sie bei *Amazon-Verknüpfung* den Produkttyp. +
→ Eine neue Dropdown-Liste erscheint.
.  Wählen Sie in der Dropdown-Liste das Amazon-Feld.
.  Klicken Sie auf *Hinzufügen*. +
→ Die Verknüpfung wird angelegt.

[TIP]
.Tipp: Merkmal multilingual übertragen
====
Generell können für die Amazon-Verknüpfung alle Merkmaltypen verwendet werden.  Mit Merkmalen des Typs *Auswahl* und *Text* ist es möglich, die Merkmale multilingual zu übertragen.
====

[.subhead]
Merkmal am Artikel aktivieren

Im letzten Schritt aktivieren Sie das <<artikel/artikel-verwalten#80, *Merkmal*>> in den Artikeleinstellungen und tragen einen Wert ein.

[.instruction]
Merkmal am Artikel aktivieren:

.  Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
.  Öffnen Sie den Artikel.
.  Wechseln Sie in das Tab *Merkmale*.
.  Setzen Sie bei dem Merkmal ein Häkchen, um das Merkmal zu aktivieren.
. *Speichern* Sie die Einstellungen. +
→ Das Feld für die Eingabe des Wertes wird angelegt.
.  Tragen Sie einen Wert ein.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.EU Compliance-Export
====
EU Compliance-Hinweise werden über Merkmal eingetragen und als eigene Flatfile zu Amazon übetragen. Wählen Sie dazu das Amazon-Feld *EU Compliance* beim jeweiligen Amazon-Produkttyp, verknüpfen Sie das Merkmal mit dem Artikel und wählen Sie in den Amazon Grundeinstellungen im Tab *Artikeleinstellungen* die passende Export-Kategorie.
====

Erfahren Sie mehr dazu im folgenden Video-Tutorial:

video::202024357[vimeo]

[#1500]
==  Datenaustausch aktivieren

In diesem Bereich werden die Einstellungen zum Datenaustausch zwischen Ihrem plentymarkets System und dem Marktplatz Amazon beschrieben. Sie erhalten Informationen zum Erzeugen eines Datenexports, der alle relevanten Informationen über Artikel und Warenbestände enthält. Außerdem importieren Sie Amazon-Aufträge automatisch über die XML-Schnittstelle oder manuell über eine CSV-Datei. Sie erfahren zudem, wie Sie Versandbestätigungen an Amazon senden, FBA-Bestände synchronisieren und Auftragsberichte von Amazon zurücksetzen.

[#1600]
===  Artikeldaten exportieren

Im Menü *System » Märkte » Amazon » Datenaustausch » Datenexport* können zwei Datenexporte erzeugt werden. Zum einen der Datenexport Seller Central, der alle relevanten Informationen über Artikel und Warenbestände enthält und anschließend direkt im Seller Central hochgeladen wird. Zum Anderen der Datenexport Marketplace, mit dem Sie Artikeldaten der BMVD-Kategorien für Amazon exportieren.

[#1700]
====  Datenexport Seller Central einrichten

Im Bereich *Seller Central* dieses Menüs erstellen Sie manuell einen Datenexport, der alle relevanten Informationen über Artikel und Warenbestände enthält und anschließend direkt im Amazon Seller Central hochgeladen wird. Gehen Sie dazu wie im Folgenden beschrieben vor.

[IMPORTANT]
.Artikel in mehreren Kategorien anbieten
====
Wenn Sie Artikel in mehreren Kategorien anbieten, müssen Sie nacheinander für die einzelnen Kataloge Exportdateien erzeugen.
====

[.instruction]
Datenexport Seller Central einrichten:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Datenaustausch » Datenexport*.
.  Nehmen Sie die Einstellungen im Bereich *Seller Central* vor. Beachten Sie dazu die Erläuterungen in Tabelle 8.
.  Klicken Sie auf *Datei laden*, um die Daten zu exportieren. +
→ Der Datenexport wird im CSV-Format ausgegeben.
.  Speichern Sie die CSV-Datei zur weiteren Verwendung auf Ihrem Rechner.

.Datenexport Seller Central
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Amazon-Konto*
| Amazon-Konto wählen.

|*Export des Artikelkatalogs*
| Artikelkatalog für den Export wählen. Beim Artikelkatalogexport zu Amazon werden nur noch Artikel berücksichtigt, die jeweils in den vergangenen 24 Stunden geändert wurden. Bestände und Preise werden weiterhin wie gewohnt automatisiert abgeglichen.

|*Nur Artikel mit Markierung*
| Wählen, ob *alle Artikel*, *alle Artikel mit Markierung*, *alle Artikel ohne Markierung* oder Artikel mit einer bestimmten Markierung exportiert werden sollen.

|*Artikel*
| Artikelmenge wählen.

|*Datum (ab)*
| Datum eingeben. +
*Neu:* = Nur ab diesem Datum neu eingestellte Artikel werden exportiert. +
*Geändert:* = Geänderte oder aktualisierte Artikel werden exportiert.

|*Hersteller*
|*ALLE* oder einen bestimmten Hersteller wählen.
|====

[#1800]
====  Datenexport Marketplace einrichten

Im Bereich *Marketplace* dieses Menüs exportieren Sie Artikeldaten der BMVD-Kategorien zum Austausch mit Amazon. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Datenexport Marketplace einrichten:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Datenaustausch » Datenexport*.
.  Nehmen Sie die Einstellungen im Bereich *Marketplace* gemäß Tabelle 9 vor.
.  Klicken Sie auf *Datei laden*, um die Daten zu exportieren. +
→ Der Datenexport wird im CSV-Format ausgegeben.
.  Speichern Sie die CSV-Datei zur weiteren Verwendung auf Ihrem Rechner.

.Datenexport Marketplace
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Amazon-Konto*
| Amazon-Konto wählen.

|*Genre*
| Eine der folgenden BMVD-Kategorien wählen: *Bücher*, *Musik*, *Video* oder *DVD*.

|*Nur Artikel mit Markierung*
| Wählen, ob *alle Artikel*, *alle Artikel mit Markierung*, *alle Artikel ohne Markierung* oder Artikel mit einer bestimmten Markierung exportiert werden sollen.

|*Aktion*
| Aktion für den Export wählen. +
*Artikel aktualisieren/hinzufügen* = Die in der CSV-Datei übermittelten Daten werden von Amazon hinzugefügt/aktualisiert. +
*Angebote entfernen* = Die in der CSV-Datei übermittelten Angebote werden von Amazon entfernt. +
*Daten vollständig aus dem System löschen* = Die in der CSV-Datei übermittelten Daten werden von Amazon vollständig gelöscht.

|*Lieferung*
| Versandart wählen.
|====

[NOTE]
.Lagerbestandsdatei im Seller Central hochladen
====
Beim Hochladen von BMVD-Produktdaten im Seller Central wählen Sie statt der Option *Textdateivorlagen für alle Kategorien außer BMVD* die Option *Lagerbestands-Assistent*.
====

[#1900]
===  Amazon-Aufträge importieren

Im Menü *System » Märkte » Amazon » Datenaustausch » Auftragsimport* richten Sie den Import von Amazon-Aufträgen ein. Aufträge können sowohl automatisch über die XML-Schnittstelle als auch manuell über eine CSV-Datei importiert werden. Beide Varianten werden folgend beschrieben.

[#2000]
====  Aufträge automatisch importieren

Gehen Sie wie im Folgenden beschrieben vor, um den automatischen Auftragsimport einzurichten.

[.instruction]
Automatischen Auftragsimport einrichten:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Datenaustausch » Auftragsimport*.
.  Wählen Sie aus der Dropdown-Liste *Verfahren für Auftragsimport* die Option *XML-Schnittstelle abrufen*. +
→ Eine zweite Dropdown-Liste erscheint.
.  Wählen Sie aus der Dropdown-Liste *Amazon-Account* das Konto.
.  Klicken Sie auf *Vorschau*, um eine Vorschau des Imports anzuzeigen.

[#2100]
====  Aufträge manuell importieren

Gehen Sie wie im Folgenden beschrieben vor, um den manuellen Import von Amazon-Aufträgen einzurichten.

[.instruction]
Manuellen Auftragsimport einrichten:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Datenaustausch » Auftragsimport*.
.  Wählen Sie aus der Dropdown-Liste *Verfahren für Auftragsimport* die Option *CSV-Datei importieren*. +
→ Der Bereich *Einstellungen* wird geöffnet.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 10.
.  Klicken Sie auf *Vorschau*, um eine Vorschau des Imports anzuzeigen.

Auftragsimport des Marktplatzes Amazon

Einstellung

Erläuterung *Buche Zahlungseingang* Beim Auftragsimport automatisch den Zahlungseingang buchen. *Altes Format verwenden* Wenn noch das alte Amazon-Importformat verwendet wird, diese Option aktivieren. *Mandant* Mandanten für den Auftragsimport wählen. *Amazon-Account* Amazon-Konto wählen. *CSV-Datei* CSV-Datei für den Auftragsimport einstellen. [.instruction]
CSV-Datei für den Auftragsimport einstellen:

.  Klicken Sie auf *Datei auswählen*.
.  Wählen Sie die CSV-Datei für den Import.
.  Klicken Sie auf *öffnen*.
.  Klicken Sie dann auf *Vorschau*. +
→ Die verfügbaren Aufträge werden angezeigt.
.  Setzen Sie bei den Aufträgen, die importiert werden sollen, ein Häkchen bei der Option *Importieren*.
.  Klicken Sie auf das *Zahnrad*, um den Import durchzuführen.

[TIP]
.Tipp: Importierte Aufträge
====
Sollten Aufträge von Amazon in Ihr System importiert werden, die Sie nicht mit plentymarkets eingestellt haben bzw. deren Artikel bisher nicht in plentymarkets angelegt sind, haben Sie die Möglichkeit, bei diesen Aufträgen manuell die Artikel zuzuordnen und den Status einzustellen. Alternativ können Sie aus dem Auftrag heraus den Artikel in Ihrem plentymarkets System anlegen.
====

[IMPORTANT]
.Fehlende Rechnungsanschrift
====
Wenn bei den von Amazon abgerufenen Aufträgen die Rechnungsanschrift fehlt, wenden Sie sich an den Amazon-Support. Die Einstellung muss von Amazon vorgenommen werden.
====

[TIP]
.Ursprüngliche Währung und Standardwährung sind unterschiedlich
====
Beim Auftragsimport wird zusätzlich die ursprüngliche Währung sowie der ursprüngliche Brutto- und Netto-Betrag an der Artikelposition gespeichert, wenn es sich bei der Währung nicht um die in plentymarkets eingestellte Standardwährung handelt.
====

[#2200]
===  Versandbestätigungen an Amazon senden

Sobald der Amazon-Auftrag in Ihrem plentymarkets System bearbeitet und die Ware verschickt wurde, müssen Sie Amazon über den neuen Status informieren, damit man dort die Umsätze Ihrem Konto gutschreiben kann. Auch diesen wichtigen Schritt erledigt Ihr plentymarkets System automatisch über die Schnittstelle.

Folgende Bedingungen müssen bei Aufträgen erfüllt sein, damit die Versandbestätigung automatisch an Amazon gemeldet wird:

*  Herkunft: Amazon oder eine Unterherkunft von Amazon
*  Statusbereich 7 (kleiner als 8)
*  Externe Auftragsnummer
*  Importierter Auftrag (nicht manuell angelegt)
*  Warenausgang gebucht (Uhrzeit darf nicht in der Zukunft liegen)

Sollte die automatische Übermittlung der Versandbestätigung, z.B. aufgrund von kurzfristig nicht erreichbaren Servern, nicht funktionieren oder sollten kurz vor einem Abrechnungsstichtag einzelne Aufträge manuell bestätigt werden, damit diese bei der nächsten Auszahlung berücksichtigt werden, können Sie die Versandbestätigung auch manuell an Amazon senden. Für Prime-Aufträge (Amazon_Prime, Amazon_Prime_SameDay, Amazon_Prime_NextDay und Amazon_Prime_SecondDay) wird keine Versandbestätigung an Amazon gesendet.
[.instruction]
Versandbestätigung manuell an Amazon senden:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Datenaustausch » Versandbestätigung*.
.  Wählen Sie ein Amazon-Konto aus der Dropdown-Liste.
.  Geben Sie ein Datum bei der Option *Datum Warenausgang* ein. +
→ Der gesamte Warenausgang des hier eingestellten Datums wird an Amazon übertragen.
.  Klicken Sie auf *Versandbestätigung senden*.

[#2300]
===  Amazon-Auftragsberichte bearbeiten

Im Menü *System » Märkte » Amazon » Datenaustausch » Berichte* können Amazon-Bestellberichte zeitlich eingestellt und nachträglich zurückgesetzt werden.

[#2350]
====  Intervall für Auftragsberichte setzen

Im Menü *System » Märkte » Amazon » Datenaustausch » Berichte » Tab: Geplante Berichte* bestimmen Sie, in welchem Zeitraum Bestellberichte von Amazon erstellt werden. Beim automatischen Auftragsimport werden Aufträge aus diesen Berichten importiert. Daher empfehlen wir sowohl für die Erstellung von Berichten als auch für den Auftragsimport einen möglichst niedrigen Intervall zu setzen. Bestellberichte erkennt man an ihrer Bezeichnung *GET ORDERS DATA*.

[.instruction]
Intervall festlegen:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Datenaustausch » Berichte » Tab: Geplante Berichte*.
.  Wählen Sie ein Amazon-Konto aus der Dropdown-Liste.
.  Wählen Sie einen Intervall, für die Erstellung von Auftragsberichten.
. *Speichern* Sie die Einstellungen.

[#2360]
====  Auftragsberichte zurücksetzen

Im Menü *System » Märkte » Amazon » Datenaustausch » Berichte » Tab: Auftragsberichte zurücksetzen* setzen Sie die Auftragsberichte von Amazon eines bestimmten Datums zurück.

Wenn Sie die Auftragsberichte bzw. die Bestellberichte eines Tages zurücksetzen, werden diese Berichte für den Import erneut zur Verfügung gestellt. Bei einem erneuten Import werden nur die fehlenden Aufträge eines Tages eingelesen. Hierzu erfolgt ein Abgleich der Transaktionsnummer von Amazon. Ist bereits eine Transaktionsnummer vorhanden, wird der Auftrag nicht erneut importiert. So wird eine Doppelung beim Einlesen verhindert.

[.instruction]
Auftragsbericht zurücksetzen:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Datenaustausch » Berichte » Auftragsberichte zurücksetzen*.
.  Wählen Sie ein Amazon-Konto aus der Dropdown-Liste.
.  Wählen Sie das Datum, für das Sie die Auftragsberichte zurücksetzen möchten.
. *Speichern* Sie die Einstellungen.

[#2400]
===  Bestand abgleichen

Im Menü *System » Märkte » Amazon » Datenaustausch » FBA-Warenbestand* haben Sie die Möglichkeit neben dem stündlichen automatischen Bestandsabgleich mit Amazon Ihren Bestand mit einer automatischen Aktion oder per CSV-Datei abzugleichen.

[IMPORTANT]
.Nur für Amazon Multi-Channel
====
Dieses Feature ist nur für <<omni-channel/multi-channel/amazon/amazon-einrichten#16-1, *Amazon Multi-Channel*>> vorgesehen.
====

In plentymarkets wird zwischen einem automatischen Bestandsabgleich und einem manuellen Bestandsabgleich unterschieden. Beide Verfahren werden folgend beschrieben.

[#2500]
====  Bestand automatisch abgleichen

Gehen Sie wie im Folgenden beschrieben vor, um einen automatischen Abgleich durchzuführen.

[.instruction]
Automatischen Bestandsabgleich durchführen:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Datenaustausch » FBA-Warenbestand*.
.  Wählen Sie im Tab *Automatisch* das Amazon-Konto.
.  Klicken Sie auf *FBA-Bestand synchronisieren*.

Für den Prozess ist eine Zeitspanne von 4 Minuten vorgesehen. Werden die Daten nicht innerhalb dieser Zeitspanne von Amazon zur Verfügung gestellt, erfolgt kein Abgleich. Bei der nächsten Anforderung werden dann die vorher nicht übertragenen Daten verwendet, was zu Fehlern führen kann. Daher ist ein manueller Abgleich per CSV-Datei zu empfehlen wie im folgenden Kapitel beschrieben.

Es werden nur Bestände von Artikeln übernommen, die in den letzten 30 Tagen eine Bestandsänderung auf Amazon erfahren haben. Für den Erstimport empfehlen wir Ihnen den manuellen Abgleich. Die Warenbestände werden gemäß der <<omni-channel/multi-channel/amazon/amazon-einrichten#2-4, *Grundeinstellungen*>> abgeglichen.

[#2600]
====  Bestand manuell abgleichen

Der manuelle Abgleich erfolgt per CSV-Datei.

[IMPORTANT]
.SKU-Zuordnung
====
Für den manuellen Abgleich muss die SKU-Zuordnung in den <<omni-channel/multi-channel/amazon/amazon-einrichten#2-3, *Grundeinstellungen*>> eingetragen werden.
====

Bevor Sie diesen Abgleich durchführen, ist es nötig, bei Amazon im Seller Central die entsprechende Berichtsdatei anzufordern, herunterzuladen und die CSV-Datei auf Ihrem Rechner zu speichern.

[.instruction]
Manuellen Bestandsabgleich durchführen:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Datenaustausch » FBA Warenbestand*.
.  Wechseln Sie in das Tab *Manuell*.
.  Wählen Sie das Amazon-Konto.
.  Klicken Sie auf *Datei auswählen*, um die soeben gespeicherte CSV-Datei zu wählen.
. *Speichern* Sie, um den Abgleich durchzuführen.

[#2700]
==  Amazon-Aufträge abrufen

Wenn Sie bereits mit einem anderen Shopsystem gearbeitet haben, wissen Sie bestimmt sehr genau, wie zeitaufwändig die tägliche Auftragsbearbeitung im Seller Central-Portal sein kann. Mit plentymarkets wird alles erheblich vereinfacht, denn hier werden alle Aufträge aus allen angeschlossenen Märkten in einem einzigen Auftragsordner für Sie gesammelt. Aus Amazon-Aufträgen werden automatisch plentymarkets Aufträge, die Sie nach dem gewohnten Fulfillment-Schema schnell und effektiv bearbeiten können. Nicht einmal um den Import der Aufträge müssen Sie sich noch kümmern, das macht die Schnittstelle für Sie im Hintergrund. Damit alles korrekt funktioniert, sind ein paar Voraussetzungen bzw. Einstellungen nötig, die hier zusammengefasst sind.

Der Abruf der Aufträge erfolgt im Viertelstundentakt. Dennoch kann es unter Umständen bis zu 90 Minuten dauern, bis ein in Amazon generierter Auftrag in Ihrem plentymarkets System angezeigt wird. Das ist keine Fehlfunktion, sondern aus technischen Gründen nicht anders möglich. Meist werden Sie zuvor durch eine E-Mail von Amazon über den Verkauf informiert und können den Auftrag im Seller Central bereits ansehen.

[#2800]
===  Einstellungen der Schnittstelle in plentymarkets vornehmen

Für den Import der Aufträge sind die Einstellungen *Zahlungseingang* sowie *Versandbestätigung* in den Grundeinstellungen relevant. Wir gehen davon aus, dass Sie Aufträge mit dem Status *[5] Freigabe Versand* übernehmen und die stündliche Versandbestätigung automatisch von Ihrem plentymarkets System erzeugen lassen. Kontrollieren Sie diese Einstellungen nochmals.

Für den manuellen und automatischen Auftragsimport beachten Sie das Kapitel *<<omni-channel/multi-channel/amazon/amazon-einrichten#12, FBA-Aufträge automatisch importieren>>*.

[IMPORTANT]
.Retouren von Amazon-Aufträgen bearbeiten
====
Natürlich müssen Sie auch bei Amazon gelegentlich mit einem Widerruf nach erfolgter Auslieferung rechnen. Die Artikel muss der Kunde direkt an Sie zurücksenden. Wie Sie in plentymarkets eine Retoure anlegen und den Warenausgang wieder zurücksetzen, lesen Sie auf der Handbuchseite <<warenwirtschaft/waren-ausbuchen#, Warenausgang>> nach.
====

[.subhead]
MFN: Rückbuchung manuell über Seller Central erledigen

Da Amazon für Sie die Zahlung des Kunden in Empfang genommen hat, muss die Rückbuchung ebenfalls über Amazon erfolgen. Das müssen Sie im Auftragsordner im Seller Central erledigen.

[IMPORTANT]
.Rückbuchung manuell oder per Ereignisaktion ausführen
====
Die Erstattung des Kaufpreises durch Amazon wird nicht automatisch über die Schnittstelle angestoßen, sondern muss manuell oder über eine Ereignisaktion automatisch ausgeführt werden. Wenn Sie dies vergessen, riskieren Sie eine Kundenbeschwerde bei Amazon und eine schlechte Bewertung.
====

MFN (=Versand durch den Händler) Retouren können Sie in Form von Gutschriften per Ereignisaktion an Amazon melden. Nur mit Hilfe eines Auftrags vom Typ Gutschrift kann die Rückzahlung der Artikelsumme und den Versandkosten garantiert werden. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.subhead]
Auftragsstatus anlegen

Legen Sie zunächst einen Auftragsstatus für Amazon-Retouren im Menü *<<auftragsabwicklung/auftraege/auftraege-verwalten#, System » Aufträge » Auftragsstatus>>* an, z.B. [9.6] Retoure an Amazon gesendet. Diesen Auftragsstatus benötigen Sie für die Amazon-Einstellungen.

[.subhead]
Auftragsstatus einstellen

Stellen Sie diesen Auftragsstatus nun in den Amazon-Einstellungen ein wie folgend beschrieben.

[.instruction]
Auftragsstatus für Retoure einstellen:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Einstellungen*.
.  Öffnen Sie das Amazon-Konto.
.  Wechseln Sie in das Tab *Auftragseinstellungen*.
.  Wählen Sie für die Option *Status für übertragene Retouren* den eben eingerichteten Auftragsstatus für Amazon-Retouren.
. *Speichern* Sie die Einstellungen.

Richten Sie eine *<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>* ein, um Retouren in Form von Gutschriften automatisch an Amazon zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Tragen Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß Tabelle 11.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 11 vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Retouren an Amazon
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Gutschrift*
|

|*Filter*
|*Auftrag &gt; Herkunft*
|*Amazon* oder die passende Amazon-Unterherkunft, z.B. Amazon France

|*Aktion*
|*Retoure &gt; Retoure bei Amazon anlegen*
|
|====

[#3100]
=== Ausstehende Amazon-Aufträge importieren

Ausstehende Amazon-Aufträge werden in Status [1] in Ihr plentymarkets System importiert und verbleiben in diesem Status bis Amazon den Auftrag frei gibt. Bis zur Freigabe werden weder die Rechnungs-/Lieferadresse noch Artikelpreise am Auftrag hinterlegt. Nach der Freigabe durch Amazon wird der Auftrag aktualisiert und die dazugehörigen Adressen und Preise werden hinterlegt. Die Warenbestandsautomatik entscheidet in welchen Status der Auftrag rutscht.

[#3110]
==== Warenbestand für ausstehende Aufträge reservieren

Es gibt zwei Möglichkeiten, den Warenbestand für ausstehende Aufträge in plentymarkets zu reservieren. Entweder mit Hilfe einer Ereignisaktion oder direkt in den Auftragsgrundeinstellungen.
Mit der Ereignisaktion wird der Auftrag von Status 1 in einen Status verschoben, bei dem Warenbestand reserviert wird.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß Tabelle 11.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 11 vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Aktualisieren von Auftragsstatus
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Neuer unvollständiger Auftrag*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*Amazon-Herkünfte*

|*Aktion*
|*Auftrag &gt; Status ändern*
|*Status wählen, in dem der Bestand reserviert wird.*
|====

In den Auftragsgrundeinstellungen wird über die Einstellung *Status Auftragsreservierung* definiert, in welchen Auftragsstatus Warenbestände reserviert werden.

[.instruction]
Auftragsstatus für Warenbestandsreservierung festlegen:

.  Öffnen Sie das Menü *System » Aufträge » Einstellungen*.
.  Wählen Sie bei der Einstellung *Status Auftragsreservierung* die Status, damit für Aufträge, die in diesen Status ankommen, Bestand reserviert wird.
. *Speichern* Sie die Einstellungen.

[#3200]
==  Amazon-Geschenkservice nutzen

Mit der Aktivierung des Amazon-Geschenkservices können Ihre Kunden optional während des Bestellprozesses auf Amazon einen Geschenkpapierservice nutzen und ggf. eine Grußbotschaft eingeben. Diese Optionen werden beim automatischen Auftragsabruf übernommen, ohne dass weitere Einstellungen erforderlich sind. Für jede Auftragsposition mit Geschenkoption wird eine zusätzliche Zeile mit Informationen direkt hinter dem bestellten Artikel angefügt. Dazu gehören die Verpackungsart sowie ggf. eine Grußbotschaft.

Aktivieren Sie die Geschenkoptionen im Amazon Seller Central, um den Geschenkservice zu nutzen.

[TIP]
.Tipp: Mehrere Verpackungsarten und Aufpreise
====
Sie können mehrere Verpackungsarten hinzufügen und Aufpreise definieren.
====

[#3300]
==  FBA-Service von Amazon nutzen

Das Kürzel FBA steht für Fulfillment by Amazon. Statt die Aufträge selbst zu bearbeiten, die Ware zu verpacken und zu versenden, überlassen Sie beim FBA-Programm Amazon diese Aufgabe. Natürlich müssen Sie zumindest einen Teil Ihrer Waren dann auch bei Amazon einlagern.

Erfahren Sie mehr FBA im folgenden Video-Tutorial:

video::198652256[vimeo]

[#3400]
===  Lager für Amazon FBA anlegen

Im Menü *System » Märkte » Amazon » Einstellungen* im Tab *Auftragseinstellungen* stellen Sie unter *Lager* u.a. ein, welches Lager für Amazon Fulfillment-Aufträge verwendet werden soll, damit die komplette Funktionalität der Warenwirtschaft auch beim FBA-Programm erhalten bleibt und Sie die Lagerbestände bei Amazon über Ihr plentymarkets System im Blick behalten.

[.instruction]
Lager anlegen:

.  Öffnen Sie das Menü *System » Waren » Lager*.
.  Klicken Sie auf das kleine Dreieck rechts in der Zeile *Lager*. +
→ Der Button *Neues Lager* wird eingeblendet.
.  Klicken Sie auf den Button *Neues Lager*. +
→ Das Fenster *Neues Lager* wird geöffnet.
.  Tragen Sie einen Namen ein.
.  Wählen Sie einen *Lagertyp*.
.  Wählen Sie als *Logistiktyp* die Option *Amazon*.
. *Speichern* Sie, um das Lager anzulegen. +
→ Das Lager wird alphabetisch sortiert unter Lager angezeigt.
.  Klappen Sie das Lager auf, um die Untermenüs anzuzeigen.
.  Nehmen Sie die weiteren Einstellungen gemäß der Erläuterungen auf der Handbuchseite <<warenwirtschaft/lager-einrichten#, *Einstellungen*>> vor.
. *Speichern* Sie die Einstellungen.

Ob die mit dem FBA-Service verbundenen Vorteile oder die Nachteile für Ihre persönliche Situation als Online-Händler überwiegen, können Sie nur selbst einschätzen. Wir möchten hier nur auf einige wichtige Punkte hinweisen:

*  Die Auftragsbearbeitung bei Amazon erfolgt schnell und zuverlässig. Spitzenzeiten vor Weihnachten sind für den Shopbetreiber genauso problemlos wie das Sommerloch während der Urlaubszeit.
*  Ihr Listing auf dem Marktplatz verbessert sich, d.h. Sie können mit höheren Verkaufszahlen rechnen.
*  Der FBA-Service ist mit Kosten verbunden, d.h. Ihre Brutto-Marge sinkt. Für einen umfassenden Vergleich der Kosten bedenken Sie jedoch, dass im FBA-Service der Aufwand für die Lagerhaltung, das Auftragshandling, den Kundenservice etc. enthalten ist und Sie so von diesem Aufwand entlastet werden.
*  Ware, die bei Amazon gelagert ist, kann in erster Linie auch nur dort angeboten werden. Für andere Marktplätze benötigen Sie gesonderte Warenbestände. Mit dem Service Multi-Channel-Fulfillment stellt Amazon jedoch auch eine Variante zur Verfügung, die Ihre Möglichkeiten diesbezüglich erweitert.
*  Sie haben deutlich weniger Ärger mit nicht zustellbaren Sendungen oder verzögerten Auslieferungen. Pakete mit Amazon-Logo werden in der Regel bevorzugt behandelt.

[#3500]
===  FBA-Auftragsimport

Gehen Sie wie im Folgenden beschrieben vor, um einzustellen, dass Ihre FBA-Aufträge täglich automatisch in Ihr plentymarkets System importiert werden.

[.instruction]
FBA-Aufträge automatisch importieren:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Einstellungen*.
.  Wählen Sie das Konto.
.  Wechseln Sie in das Tab *Auftragseinstellungen*.
. Setzen Sie im Bereich *Versand durch Amazon (FBA)* ein Häkchen bei Aktiv.
. *Speichern* Sie die Einstellungen.

Die Auftragsbearbeitung hat folgenden Ablauf:

*  Der Kunde kauft bei Amazon.
*  Amazon verschickt die Ware.
*  Das plentymarkets System fordert einen Bericht an.
*  Amazon erstellt den Bericht.
*  Am nächsten Tag prüft plentymarkets automatisch, ob Berichte bei Amazon vorliegen. Wenn ja, werden diese importiert.
*  Aus den Berichten werden in plentymarkets Aufträge erzeugt.

[IMPORTANT]
.Hinweis zum Auftragsimport
====
Amazon generiert die Berichte nur einmal täglich. Da der Versand nach bis zu 2 Tagen erfolgt, sind die FBA-Aufträge erst mit einer zeitlichen Verzögerung in Ihrem System verfügbar. Die von Amazon generierte Auftragsbestätigung ist in der Regel zwei Tage nach Versand der Ware, also insgesamt bis zu 4 Tage nach Bestellung der Ware durch den Käufer, in Ihrem System verfügbar. Die Lieferpünktlichkeit wird davon jedoch nicht berührt und erfolgt in der von Amazon gewohnten Schnelligkeit.
====

Amazon FBA-Aufträge werden mit den Parametern *Status* und *Herkunft* importiert. Für die Option *Status* legen Sie den für Ihren Prozess passenden Status fest, also zum Beispiel *[7] Warenausgang gebucht*. Die Herkunft wird automatisch auf Amazon FBA oder eine Amazon FBA-Unterherkunft, wie z.B. Amazon FBA USA, gesetzt. Der Warenausgang wird hier in plentymarkets direkt gebucht, so dass keine Reservierung des Bestands der enthaltenen Artikelpositionen stattfindet.

[TIP]
.Ereignisaktionen für Fulfillment
====
Konfigurieren Sie die für den Fulfillment-Prozess nötigen Ereignisaktionen, um eine Rechnung zu erzeugen und per E-Mail automatisch an den Käufer zu senden sowie den Auftrag dann in einen weiteren Status zu setzen. +
Beachten Sie dazu die Handbuchseiten *<<basics/automatisierung/ereignisaktionen#, Ereignisaktionen>>* sowie *<<auftragsabwicklung/fulfillment#, Standard-Fulfillment im Detail>>*.
====

[.subhead]
FBA-Teillieferungen

Amazon FBA-Teillieferungen werden von Amazon veranlasst, wenn sich die von Amazon im Kundenauftrag versendete Ware in unterschiedlichen Amazon-Lagern befindet.
Bei den Kunden kommen nach Bestellung demzufolge mehrere Pakete zu einem getätigten Auftrag an. +
In plentymarkets wird jede FBA-Teillieferung anhand des versendenden FBA-Lagers als separater Auftrag im System angelegt. Pro Teillieferung kann eine Sendungsnummer von Amazon importiert und der jeweiligen Teillieferung zugeordnet werden. Pro Teillieferung kann eine separate Rechnung erzeugt werden, was aufgrund der unterschiedlichen zu berechnenden Steuern erforderlich ist, wenn die Amazon-Lager in unterschiedlichen Ländern liegen.

[.subhead]
Europäisches Versandnetzwerk

Amazon erweitert kontinuierlich sein europäisches Versandnetzwerk für Händler, die Versand durch Amazon nutzen. Eine Voraussetzung ist, dass Sie in allen Ländern, in denen Sie FBA-Logistikzentren nutzen steuerrechtlich registriert sind. Damit für diese neuen Logistikzentren Ihre Rechnungen auch steuerlich korrekt erstellt werden, können Sie neben Ihrem Firmensitz jetzt auch im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung* den Lagerstandort als Basis für den Standard-Umsatzsteuersatz wählen und das individuell für jeden Ihrer Mandanten (Shops). Im gleichen Menü im Tab *Umsatzsteuersätze* erfassen Sie auch die notwendigen Steuersätze für die Länder.

[TIP]
.Beispiel: Logistikzentrum in Polen mit Versand nach Deutschland
====
Damit für Aufträge, die von einem Logistikzentrum in Polen nach Deutschland verschickt werden, nicht der polnische Steuersatz verwendet wird, muss für den Standort Polen zusätzlich das Land Deutschland mit dem deutschen Steuersatz eingetragen werden. Wählen Sie dafür im Menü *System » Mandant » Mandant wählen » Standorte » Polen » Buchhaltung » Tab: Umsatzsteuersätze* das Land *Deutschland* und tragen Sie den deutschen Steuersatz sowie die gültige USt-IdNr. ein.
====

[#3600]
===  FBA-Retouren automatisch importieren

Im Retourenfall sendet der Käufer die Ware zurück an Amazon. Die Retoure wird in Ihr plentymarkets System importiert und mit dem Retourenstatus, den Sie im Menü *<<auftragsabwicklung/auftraege/_grundeinstellungen#, System » Aufträge » Einstellungen>>* gewählt haben, im Auftragsmenü angelegt.

[IMPORTANT]
.Auftrag nicht ändern
====
Retouren werden nur importiert, wenn der Auftrag mit unveränderter externer Auftragsnummer in plentymarkets vorliegt.
====

Aktivieren Sie wie im Folgenden beschrieben die Importfunktion, um FBA-Retouren automatisch in Ihr plentymarkets System zu importieren.

[.instruction]
Importfunktion für FBA-Retouren aktivieren:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Einstellungen*.
.  Öffnen Sie das Amazon-Konto.
.  Wechseln Sie in das Tab *Auftragseinstellungen*.
.  Wählen Sie im Bereich *Versand durch Amazon (FBA)* für die Option *Retourenimport* die Einstellung *Täglich*.
. *Speichern* Sie die Einstellungen.

[#3650]
===  Gutschriften automatisch importieren

Nutzen Sie für Amazon FBA den Gutschriftenimport, um FBA-Gutschriften automatisch in Ihr plentymarkets System zu importieren. Die Gutschriften werden einmal täglich importiert.

[IMPORTANT]
.FBA-Retouren nicht als Gutschriften importieren
====
Importieren Sie FBA-Retouren nicht als Auftragstyp *Gutschrift* in Ihr plentymarkets System, wenn Sie den automatischen Gutschriftenimport nutzen.
====

[.instruction]
Automatischen Gutschriftenimport aktivieren:

. Öffnen Sie das Menü *System » Märkte » Amazon » Einstellungen*.
. Öffnen Sie das Amazon-Konto.
. Wechseln Sie in das Tab *Auftragseinstellungen*.
. Wählen Sie *Ja* für die Option *Gutschriftenimport*.
. *Speichern* Sie die Einstellungen.

[#3700]
==  Amazon Multi-Channel einrichten

Amazon Multi-Channel bedeutet, dass "Lieferungen im Auftrag des Verkäufers durch Amazon verschickt werden, für Bestellungen, die nicht bei Amazon.de aufgegeben wurden, sondern z.B. auf eBay oder auf der persönlichen Website eines Verkäufers." (Quelle: Amazon)

Die Multi-Channel-Funktion ermöglicht Ihnen also, Artikel bei Amazon zu lagern und von Amazon verschicken zu lassen, die Sie nicht bei Amazon, sondern auf anderen externen Marktplätzen verkaufen. Sie erfahren in diesem Kapitel, welche Einstellungen Sie in Ihrem plentymarkets System vornehmen müssen, damit diese Aufträge über Amazon abgewickelt werden können.

Die folgenden Schritte sind nötig, um Ihre Bestandsverwaltung und Artikeldaten für Amazon Multi-Channel zu konfigurieren.

[#3800]
===  Lager für Amazon Multi-Channel anlegen

Legen Sie ein Lager an, falls Sie dies noch nicht wie im Kapitel <<omni-channel/multi-channel/amazon/amazon-einrichten#10, *FBA-Service von Amazon nutzen*>> beschrieben getan haben. Wichtig beim Multi-Channel-Versand ist, dass Sie für jeden landesspezifischen Amazon-Markt ein eigenes Lager mit dem Logistiktyp *Amazon* und das Land als Standort in plentymarkets eingerichtet haben.

[IMPORTANT]
.Beispiel für die übereinstimmung von Amazon-Plattform und Lagerstandort
====
Beim Multi-Channel-Versand über amazon.co.uk muss ein eigenes Lager Amazon UK mit dem Logistiktyp *Amazon* und dem Standort Großbritannien angelegt werden. Die Ware muss also auch tatsächlich vor Ort bei Amazon z.B. in Großbritannien gelagert sein, da sonst keine Versandabwicklung über amazon.co.uk stattfinden kann.
====

[#3900]
===  Artikelverfügbarkeit für Amazon Multi-Channel einstellen

Nehmen Sie die im Folgenden beschriebenen Einstellungen an den Artikeln vor, die Sie für Amazon Multi-Channel verfügbar machen möchten.

[.instruction]
Artikelverfügbarkeit für Amazon Multi-Channel einstellen:

.  Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
.  Öffnen Sie den Artikel.
.  Wechseln Sie in das Tab *Multi-Channel*.
.  Nehmen Sie die Einstellungen im Bereich *Amazon* vor. Beachten Sie dazu die Erläuterungen in Tabelle 5 im Kapitel <<omni-channel/multi-channel/amazon/amazon-einrichten#700, *Artikelverfügbarkeit einstellen*>>.
. *Speichern* Sie die Einstellungen.

[#4000]
===  Einstellungen für Amazon Multi-Channel vornehmen

Nehmen Sie die folgend beschriebenen Einstellungen im Menü für Amazon vor.

[.instruction]
Amazon Multi-Channel konfigurieren:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Einstellungen*.
.  Wechseln Sie in das Tab *Auftragseinstellungen*.
.  Nehmen Sie die Einstellungen im Bereich *Versand durch Amazon (FBA)* vor. Beachten Sie dazu die Erläuterungen in Tabelle 12.
. *Speichern* Sie die Einstellungen.

.Amazon Multi-Channel konfigurieren
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Auftragsimport*
| Option *Täglich* wählen, damit die Aufträge täglich importiert werden.

|*Bestandsimport*
| Option *Stündlich* wählen, damit der Bestand importiert wird. +
Dabei werden nur Änderungen der Bestandsdaten berücksichtigt. Weitere Möglichkeiten zum Bestandsimport sind in Kapitel <<omni-channel/multi-channel/amazon/amazon-einrichten#9-5, *Bestand abgleichen*>> beschrieben.

|*Lager*
| Wählen, welches <<omni-channel/multi-channel/amazon/amazon-einrichten#10, *Lager*>> für den Versand durch Amazon verwendet werden soll.

|*Status für übertragene Aufträge*
| Bestimmt den Auftragsstatus für Multi-Channel FBA Aufträge, die erfolgreich an FBA übertragen wurden.

|*Versandkategorie*
| Versandkategorie wählen. +
*Standard* = Normaler Versand +
*Expedited* = Schnellversand +
*Priority* = Bevorzugt (schnellster Versand)
|====

[#4100]
===  FBA-Versandfreigabe automatisch erteilen

Richten Sie eine *<<basics/automatisierung/ereignisaktionen#, Ereignisaktion>>* ein, damit Amazon automatisch eine Meldung über den Auftrag erhält und den Auftrag bearbeiten sowie den Versand veranlassen kann.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Tragen Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß Tabelle 14.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 14 vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Erteilen von FBA-Versandfreigaben an Amazon
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel &gt; [5] Freigabe Versand*
|

|*Filter 1*
|*Auftrag &gt; Auftragslager*
|*Amazon Multi-Channel*

|*Filter 2*
|*Versand &gt; Versand ausschließlich durch FBA*
|

|*Aktion*
|*Versand &gt; FBA-Versandfreigabe erteilen*
|
|====

Bei Wechsel in Status 5 wird Amazon mit der Ereignisaktion darüber informiert, dass die Ware zum Versand freigegeben ist. Amazon verschickt die Ware und das plentymarkets System erhält intern eine Bestätigung von Amazon. Der Auftrag wechselt in Status 5.1, wie in den *<<omni-channel/multi-channel/amazon/amazon-einrichten#22, Auftragseinstellungen>>* festgelegt. Die Paketnummer wird in Ihr plentymarkets System importiert.

[TIP]
.Import von Paketnummern
====
Der Import der Paketnummern wird einmal täglich durchgeführt.
====

[#4200]
==  Amazon Prime-Aufträge bearbeiten

Mit Hilfe von Filtern in den Bereichen Auftragssuche und Ereignisaktionen werden Aufträge mit den Versandbedingungen von Amazon Prime gesondert in plentymarkets behandelt. Versandlabel für Amazon Prime-Aufträge werden über die Amazon Merchant Fulfillment API generiert.

[IMPORTANT]
.Pflichtfelder für die Anmeldung von Amazon Prime-Aufträgen
====
Damit Amazon Prime-Aufträge bearbeitet werden können, müssen bestimmte Informationen im Menü *System » Aufträge » Versand » Dienstleister » Einstellungen* hinterlegt sein. Amazon definiert folgende Pflichtfelder: *Firma*, *Straße*, *Hausnummer*, *PLZ*, *Ort*, *Land*, *Telefon* und *E-Mail*. Diese Pflichtfelder müssen gefüllt sein, damit die Anmeldung Ihrer Amazon Prime-Aufträge ausgeführt werden kann.
====

[#4300]
===  Amazon Prime-Aufträge filtern

Im Menü *<<auftragsabwicklung/auftraege/auftraege-verwalten#, Aufträge » Aufträge bearbeiten>>* werden alle Ihre Aufträge angezeigt. Diese Aufträge können Sie über *<<auftragsabwicklung/auftraege/auftraege-verwalten#suche, Filter>>* eingrenzen und sich z.B. nur Amazon Prime-Aufträge anzeigen lassen.

Innerhalb des Filters *Amazon* stehen Ihnen zehn Optionen zur Auswahl:

* *ALLE* filtert alle Amazon-Aufträge.
* *Prime* filtert alle Amazon Prime-Aufträge, außer Prime SameDay, Prime NextDay und Prime SecondDay.
* *Prime (alle)* filtert alle Amazon Prime-Aufträge, auch Prime SameDay, Prime NextDay und Prime SecondDay.
* *Nein* Amazon Prime-Aufträge werden nicht berücksichtigt.
* *Prime SameDay* nur Prime SameDay-Aufträge werden in der Auftragsübersicht gelistet.
* *Prime NextDay* nur Prime NextDay-Aufträge werden in der Auftragsübersicht gelistet.
* *Prime SecondDay* nur Prime SecondDay-Aufträge werden in der Auftragsübersicht gelistet.
* *SameDay* Amazon-Aufträge werden in der Auftragsübersicht gelistet, die nicht zu Amazon-Prime gehören, aber bei denen der Versand dennoch am gleichen Tag erfolgen muss.
* *NextDay* Amazon-Aufträge werden in der Auftragsübersicht gelistet, die nicht zu Amazon-Prime gehören, aber bei denen der Versand dennoch am nächsten Tag erfolgen muss.
* *SecondDay* Amazon-Aufträge werden in der Auftragsübersicht gelistet, die nicht zu Amazon-Prime gehören, aber bei denen der Versand dennoch am übernächsten Tag erfolgen muss.

[#4400]
===  Versandlabel für Amazon Prime-Aufträge generieren

Amazon schreibt vor, dass Sie Versandlabel für Amazon Prime-Aufträge über die Amazon Merchant Filfillment API generieren. Dafür stellt Amazon Versanddienstleister mit vergünstigten Konditionen zur Verfügung. Im Folgenden wird beschrieben, wie Sie zunächst die Versandprofile mit Amazon Prime verknüpfen.

[.instruction]
Versandprofile mit Amazon Prime verknüpfen:

.  Öffnen Sie das Menü *System » Aufträge » Versand » Optionen » Tab: Versandprofile*.
.  Wählen Sie das Versandprofil, das Sie mit Amazon Prime verknüpfen wollen.
.  Wählen Sie den Filter *Amazon Prime* im Bereich *Treueprogramm*.
.  Wechseln Sie in das Tab *Portotabelle*.
.  Wählen Sie bei der Option *Amazon Prime Service* im Bereich *Amazon Prime* die Versandart.
. *Speichern* Sie die Einstellungen.

[TIP]
.Tipp: Versandpaket beachten
====
Beachten Sie das beim Versandprofil hinterlegte Versandpaket, damit es nicht zur Generierung überteuerter Labels kommt.
====

Anschließend melden Sie im Menü *Aufträge » Versand-Center » Tab: Anmelden* Ihre Amazon Prime-Aufträge bei dem von Ihnen gewählten Amazon-Versanddienstleister an. Voraussetzung für die Anmeldung ist, dass Sie zuvor im Tab *Suche* Amazon Prime-Aufträge gesucht haben, die jetzt hier angezeigt werden.

[TIP]
.Tipp: Versanddienstleister beachten
====
Beachten Sie, dass der passende Versanddienstleister eingestellt ist, da sonst die korrekten Amazon Services in den Portotabellen nicht eingestellt werden können.
====

[.instruction]
Amazon Prime-Aufträge anmelden:

.  Öffnen Sie das Menü *Aufträge » Versand-Center » Tab: Suchen*.
.  Suchen Sie den Amazon Prime-Auftrag, den Sie anmelden wollen.
.  Wechseln Sie in das Tab *Anmelden*.
.  Wählen Sie aus der Dropdown-Liste *Versanddienstleister* die Option *Amazon Prime*.
.  Klicken Sie auf *Anmelden*.
.  Öffnen Sie den Auftrag. +
→ Nach erfolgreicher Anmeldung erscheint im Bereich *Übersicht* ein PDF-Symbol, über das Sie das Versandlabel herunterladen können.

Erfahren Sie mehr über Amazon Prime im folgenden Video-Tutorial:

video::158480475[vimeo]

[#4500]
==  Zahlungsart Amazon aktivieren

Die Zahlungsart *Amazon* ist für Aufträge, die über den Marktplatz Amazon in Ihr plentymarkets System kommen und nicht zu verwechseln mit der Zahlungsart *Amazon Pay*, die für Kunden ist, die über den Marktplatz Amazon in Ihrem Webshop einkaufen.

Aktivieren Sie die *<<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsart>>**Amazon*, wie im Folgenden beschrieben.

[.instruction]
Zahlungsart Amazon aktivieren:

.  Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
.  Klicken Sie auf den Ordner *International &gt; Amazon*. +
→ Die Einstellungen für die Amazon-Zahlungsart werden angezeigt.
.  Setzen Sie ein Häkchen bei der Option *Aktiv*.
.  Nehmen Sie ggf. weitere Einstellungen vor.
. *Speichern* Sie die Einstellungen.

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » CRM » Kundenklassen* aktivieren oder deaktivieren Sie *erlaubte Zahlungsarten*. +
Weitere Informationen finden Sie auf der Handbuchseite *<<auftragsabwicklung/payment/zahlungsarten-verwalten#40, Zahlungsarten und Kundenklassen>>*.
====

Weitere Informationen finden Sie auf der Handbuchseite *<<auftragsabwicklung/payment/zahlungsarten-verwalten#, Zahlungsarten>>*.

[#4550]
== Amazon Business einrichten

Mit Amazon Business verkaufen Sie Ihre Artikel an gewerbliche Kunden. Bevor Sie Einstellungen in plentymarkets vornehmen, link:https://services.amazon.de/programme/b2b-verkaufen/merkmale-und-vorteile.html[registrieren^] Sie sich bei Amazon für das Verkäuferprogramm. Damit Ihre Artikel als B2B-Artikel an Amazon Business übermittelt werden, muss Amazon Business für das Amazon-Konto freigeschaltet werden und Verkaufspreise und Mengenrabatte für Amazon Business müssen angelegt sowie mit dem Artikel verknüpft sein. Nehmen Sie die im Folgenden beschriebenen Einstellungen vor, um Artikel an Amazon Business zu übermitteln.

[IMPORTANT]
.Hinweis zu Amazon Business
====
Aktuell ist Amazon Business nur für die Länderplattformen Amazon.de und Amazon.co.uk verfügbar.
====

[#4555]
=== Amazon Business freischalten

Im Menü *System » Märkte » Amazon » Einstellungen* schalten Sie das Amazon-Konto für Amazon Business frei.

[.instruction]
Amazon-Konto für Amazon Business freischalten:

.  Öffnen Sie das Menü *System » Märkte » Amazon » Einstellungen » Konto öffnen » Tab: Einstellungen*.
.  Setzen Sie ein Häkchen bei der Option *B2B*.
. *Speichern* Sie die Einstellungen.

[#4560]
=== Verkaufspreis konfigurieren

Nachdem das Amazon-Konto für Amazon Business freigeschaltet wurde, müssen Sie Verkaufspreise für B2B-Artikel anlegen und verknüpfen. Sie können neben dem Standardpreis für Artikel ab Menge 1 bis zu 5 weitere Preise für Mengenrabatte anlegen. Dabei können Preise für Mengenrabatt als Festpreis oder prozentual angelegt werden.

[#4565]
==== Verkaufspreis anlegen

Legen Sie zunächst einen Standardpreis für B2B-Artikel an. Dabei müssen im Menü *System » Artikel » Verkaufspreise* die Option *Ab Menge*, die *Herkunft* und das *Amazon-Konto* eingestellt werden.

[.instruction]
Standardverkaufspreis für B2B-Artikel anlegen:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise*.
. Klicken Sie auf *Neu*. +
→ Das Tab *Neu* wird geöffnet.
. Tragen Sie bei der Option *Ab Menge* eine *1* ein.
. Wählen Sie die Herkunft *Amazon Germany B2B*.
. Wählen Sie das *Amazon-Konto*, das für Amazon B2B freigeschaltet ist.
. Nehmen Sie weitere Einstellungen gemäß Tabelle 10 auf der Seite *<<artikel/artikel-verwalten#880, Artikel verwalten>>* vor.
. *Speichern* Sie die Einstellungen.

[#4570]
==== Verkaufspreis für Mengenrabatt anlegen

Gehen Sie wie im folgenden beschrieben vor, um Amazon Business Kunden Mengenrabatt anzubieten.

[.instruction]
Verkaufspreis für Mengenrabatt anlegen:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise*.
. Klicken Sie auf *Neu*. +
→ Das Tab *Neu* wird geöffnet.
. Tragen Sie bei der Option *Ab Menge* die Mege ein, ab welcher der Verkaufspreis gelten soll. Die Menge muss größer als 1 sein.
. Wählen Sie die Herkunft *Amazon Germany B2B*.
. Wählen Sie das *Amazon-Konto*, das für Amazon B2B freigeschaltet ist.
. Nehmen Sie weitere Einstellungen gemäß Tabelle 10 auf der Seite *<<artikel/artikel-verwalten#880, Artikel verwalten>>* vor.
. *Speichern* Sie die Einstellungen.

Alternativ lassen sich bis zu 5 Verkaufspreise für den Mengenrabatt auch prozentual über Merkmalverknüpfungen darstellen. Dafür wird beim Anlegen des Merkmals vom Typ *Auswahl* oder *Text* die Amazon-Verküpfung *quantity_price_type* gewählt und bei der Artikelverknüpfung der Wert *percent* eingegeben. Zusätzlich müssen Merkmale mit den Amazon-Verknüpfungen *quantity_lower_bound1-5* für die Rabattmenge und *quantity_price1-5* für die Prozentzahl angelegt werden.

[.instruction]
Merkmal quantity_price_type anlegen:

.  Öffnen Sie das Menü *System » Artikel » Merkmale*.
.  Klappen Sie das Merkmal auf, das Sie für Amazon verwenden möchten. +
→ Der Bearbeitungsbereich des Merkmals wird geöffnet.
.  Wählen Sie bei *Amazon-Verknüpfung* den Produkttyp. +
→ Eine neue Dropdown-Liste erscheint.
.  Wählen Sie in der Dropdown-Liste das Amazon-Feld *quantity_price_type*.
.  Klicken Sie auf *Hinzufügen*. +
→ Die Verknüpfung wird angelegt.

Aktivieren Sie als nächstes das <<artikel/artikel-verwalten#80, *Merkmal*>> in den Artikeleinstellungen und hinterlegen Sie den Wert *percent*.

[.instruction]
Merkmal am Artikel aktivieren:

.  Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
.  Öffnen Sie den Artikel.
.  Wechseln Sie in das Tab *Merkmale*.
.  Setzen Sie bei dem Merkmal ein Häkchen, um das Merkmal zu aktivieren.
. *Speichern* Sie die Einstellungen. +
→ Das Feld für die Eingabe des Wertes wird angelegt.
.  Tragen Sie den Wert *percent* ein.
. *Speichern* Sie die Einstellungen.

Legen Sie die Merkmale mit den Amazon-Verknüpfungen *quantity_lower_bound1-5* und *quantity_price1-5* analog an. Wählen Sie dabei für *quantity_lower_bound1-5* Merkmale vom Typ *ganze Zahl* und für *quantity_price1-5* Merkmale vom Typ *ganze Zahl* oder *Kommazahl*.

[#5700]
==  Amazon Pay einrichten

*Bezahlen mit Amazon* ist eine umfassende Zahlungslösung für Online-Händler. Durch *Bezahlen mit Amazon* geben Sie Millionen von Amazon-Kunden die Möglichkeit, sicher auf Ihrer Website einzukaufen, ohne Versand- und Zahlungsinformationen erneut einzugeben. Kunden können Einkäufe rasch abschließen, ohne Ihre Website zu verlassen.

Die Besonderheit der Advanced-Option von Bezahlen mit Amazon liegt darin, dass sie eine reine Zahlungsabwicklung bietet. Sie übermitteln nur den zur Abwicklung der Transaktion notwendigen Zahlungsbetrag – ohne Details zum Warenkorb oder zu Artikeldaten (vgl. Amazon).

Auf der Handbuchseite *<<auftragsabwicklung/payment/amazon-pay#, Amazon Pay>>* erhalten Sie wichtige Hinweise zur Integration des Zahlungsanbieters in plentymarkets.

[#6600]
==  API-Log abrufen

Im Menü *<<basics/datenaustausch/api-log#, Datenaustausch » API-Log>>* finden Sie eine Historie über Vorgänge, die über die Amazon-Schnittstelle ausgeführt wurden. Folgende Formate stehen Ihnen für Amazon zur Auswahl:

* *AmazonArticleExportAutomatic*
* *Amazoncatalog*
* *AmazonControllerOrders*
* *AmazonFBAImportReturns*
* *AmazonFBAInventoryUpdate*
* *AmazonFBAOrders*
* *AmazonOrder*
* *AmazonOrderFulfillment*
* *AmazonPayments*
* *AmazonPaymentsAdvanced*
* *AmazonPaymentsFulfillment*
* *AmazonPriceUpdate*
* *AmazonRequestReport*
* *AmazonStock*
* *ArticleAmazonCSV*
* *Reader_ArticleAmazonCSV_Execution*

[.instruction]
API-Log abrufen:

.  Öffnen Sie das Menü *Daten » API-Log » Tab: API-Log*.
.  Wählen Sie ein Format aus der Dropdown-Liste *Vorgang*.
.  Wählen Sie ggf. ein *Datum*, um nur Einträge eines bestimmten Tages zu erhalten.
.  Klicken Sie auf *Suchen*, um die Suche auszuführen. +
→ Die Vorgänge werden angezeigt.

Erfahren Sie mehr dazu im folgenden Video-Tutorial:

video::204168903[vimeo]
