= Vertrag
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Vertrag, plentymarkets, Service-Center
:position: 35

Im Menü **Start » plentymarkets Konto » Service-Center » Tab: Vertrag** werden Ihnen Informationen zu Ihrem laufenden plentymarkets Vertrag angezeigt. Über dieses Menü nehmen Sie Änderungen an Ihrem Vertrag vor oder geben eine Kündigung Ihres Vertrags in Auftrag.

toc::[]
== Vertrag anpassen

plentymarkets wächst mit Ihren Bedürfnissen. Sie entscheiden selbst, wie viele Aufträge Sie pro Monat mit plentymarkets bewältigen möchten. Wir stellen Ihnen dafür die nötige Systemleistung zur Verfügung. Im Tab **Vertrag** können Sie eigenständig Ihren plentymarkets Vertrag im laufenden Betrieb anpassen. Dies ist z.B. sinnvoll, wenn Sie mehr Aufträge generieren, als im bestehenden Vertrag enthalten sind. Die Buchung einer höheren Anzahl an Aufträgen ist jederzeit möglich. Wenn Sie eine niedrigere Anzahl buchen, wird diese erst nach Ablauf der regulären Laufzeit Ihres aktuellen Vertrags wirksam.

[.instruction]
Vertrag ändern:

. Öffnen Sie das Menü **Start » plentymarkets Konto » Service-Center**.
. Öffnen Sie das Tab **Vertrag**.
. Klicken Sie auf **Zum Systemkonfigurator**.
. Passen Sie die Vertragsdetails wie gewünscht an.

== Vertrag kündigen

Sie haben im Tab **Vertrag** des Service-Centers auch die Möglichkeit, Ihren Vertrag mit plentymarkets zu kündigen. Klicken Sie auf **Vertrag kündigen**, um eine Kündigung Ihres Vertrags in Auftrag zu geben.

