extends: substitution
message: "Consider using '%s' instead of '%s'."
ignorecase: true
level: error
swap:
  Absender(?:in|innen) : Absender:innen
  Anbieter(?:in|innen) : Anbieter:innen
  Anfänger(?:in|innen) : Anfänger:innen
  Ansprechpartner(?:in|innen) : Ansprechpartner:innen
  Benutzer(?:in|innen) : Benutzer:innen
  Benutzer(?:schaltfläche|symbol) : Kontosymbol
  Benutzerkonto : Benutzer:innenkonto
  Benutzername : Benutzer:innenname
  Bieter(?:in|innen) : Bieter:innen
  Dienstleister(?:in|innen) : Dienstleister:innen
  Eigner(?:in|innen) : Eigner:innen
  Empfänger(?:in|innen) : Empfänger:innen
  Entwickler(?:in|innen) : Entwickler:innen
  Händler(?:in|innen) : Händler:innen
  Interessent(?:en|in|innen) : Interessent:innen
  Käufer(?:in|innen) : Käufer:innen
  Kolleg(?:e|en|in|innen) : Kolleg:innen
  Kund(?:e|en|in|innen) : Kund:innen
  Kund(?:en|innen)klasse : Kund:innenklasse
  Kund(?:en|innen)nummer : Kund:innennummer
  Kund(?:en|innen)typ : Kund:innentyp
  Kund(?:en|innen)stamm : Kundschaft
  Leser(?:in|innen) : Leser:innen
  Lieferant(?:en|in|innen) : Lieferant:innen
  Mitarbeiter(?:in|innen) : Mitarbeiter:innen
  Nutzer(?:in|innen) : Nutzer:innen
  Partner(?:in|innen) : Partner:innen
  Steuerberater(?:in|innen) : Steuerberater:innen
  Supporter(?:in|innen) : Supporter:innen
  Systembenutzer(?:in|innen) : Systembenutzer:innen
  Verkäufer(?:in|innen) : Verkäufer:innen
