= Cross-selling
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Online store, Items, Cross-selling
:position: 40
:url: item/online-store/cross-selling

In cross-selling, you subtly encourage customers to spend more money. This is done by offering additional products that relate to the purchased product. Just a few examples:

* The cashier at a fast food restaurant asks if you want fries with your cheeseburger.
* The salesman in an electronics store suggests a memory card that would work with the digital camera.
* In a shoe store, the sales clerk asks if you want to buy a shoe polish to properly care for your new shoes.

In e-commerce, you can't directly ask your customers if they want to buy additional products. However, you can display a list of related items on the product pages in your online store.

In just three easy steps, you can generate additional sales through cross-selling.
First, make sure that your items meet the <<item/online-store/cross-selling#100, requirements for cross-selling>>.
Then create <<item/online-store/cross-selling#200, cross-selling links>> in plentymarkets.
Finally, publish the <<item/online-store/cross-selling#700, list of related items in your online store>>.

[TIP]
.Other cross-selling service providers
====
The external service provider <<online-store/online-store/extras/yoochoose#, YOOCHOOSE>> offers an alternative to plentymarkets cross-selling.
====

[#100]
== Requirements

The following requirements have to be met in order for direct cross-selling items to be displayed in your online store:

* <<item/online-store/checklist-categories-visibility#, The cross-selling item’s category must be activated>>.
* <<item/online-store/checklist-items-visibility#, The item must be visible in the online store>>.

[TIP]
.Do you have a Callisto store?
====
If you use an older Callisto store, then you’ll also need to configure a few additional settings.
Go to *Setup » Client » Select client » Online store » Settings* and use the *Cross-selling* setting to specify <<online-store/online-store/item-sorting#_setting_up_cross_selling_templates, which type of cross-selling>> you want to use.

Then use the *Dynamic cross-selling* setting to specify whether you want to use so-called <<online-store/online-store/item-sorting#_setting_up_dynamic_cross_selling, dynamic cross-selling>>. In this case, items will automatically be linked to each other if customers have purchased them at the same time.
Please note that dynamic cross-selling is only possible with older Callisto stores.
It is not currently possible to set up dynamic cross-selling for newer Ceres stores.
====

[#200]
== Cross-selling links

[#300]
=== Creating new links

Which items should be linked together? You can link an item to any number of other products from your portfolio. For example, imagine you want to link a guitar to a pack of replacement strings, a song book and a guitar strap.

[.instruction]
Linking a main item to accessories:

. Go to *Item » Edit item*.
. <<item/introduction/search#100, Search for>> and open the main item, e.g. the guitar.
. Open the tab *Cross-selling » Add item(s)*.
. Search for items again in this tab.
. Select all the accessories (icon:check-square[role="blue"]) that should be linked to the main item, e.g. select the replacement strings, the song book and the guitar strap.
. Click on the appropriate relationship (icon:cubes[role="green"]). Note <<table-cross-selling-relationship>>. +
→ The links will be created and they <<item/online-store/cross-selling#600, can be changed any time>>.

[[table-cross-selling-relationship]]
.Cross-selling relationships
[cols="1,2"]
|====
|Setting |Explanation

|*Add to selection* (icon:check-square[role="blue"])
|Select this option if you want to <<item/online-store/cross-selling#500, link the other way around>>.

|*Similar* (icon:cubes[role="green"])
|The selected items are similar to the opened item.

|*Accessory* (icon:cubes[role="green"])
|The selected items are accessories of the opened item.

|*Replacement part* (icon:cubes[role="green"])
|The selected items are replacement parts for the opened item.

|*Item bundle* (icon:cubes[role="green"])
|The selected items are suitable to be sold as a bundle together with the opened item.

|*Copy* (icon:copy[role="yellow"])
|Click on this button if you want to <<item/online-store/cross-selling#400, copy the cross-selling links>> and apply them to other main items.
|====

[#400]
=== Copying links

<<item/online-store/cross-selling#300, The instructions above>> taught you how to link _one main item_ to several accessories or replacement parts.
For example, how to link a guitar to a pack of replacement strings, a song book and a guitar strap.

But what if you have 50 other guitars that should _also_ have these cross-selling items? It will take forever to manually link every single item.

Instead, copy the existing cross-selling links from the first main item and apply them to all 50 other main items simultaneously.

[.instruction]
Copying cross-selling links:

. Go to *Item » Edit item*.
. <<item/introduction/search#100, Search for>> and open the previously linked main item, e.g. the first guitar.
. Open the tab *Cross-selling » Add item(s)*.
. Search for items again in this tab.
. Select all of the main items (icon:check-square[role="blue"]) that should also have these links, e.g. the 50 other guitars.
. Click on the copy symbol (icon:copy[role="yellow"]). +
→ The links of the opened item are transferred to all of the selected items.

[#500]
=== Linking the other way around

<<item/online-store/cross-selling#300, The instructions above>> taught you how to link _one main item_ to several accessories or replacement parts.
For example, how to link a guitar to a pack of replacement strings, a song book and a guitar strap.

But it’s also possible to link _one replacement part_ to several main items. For example, to link a pack of replacement strings to several different guitars.
The procedure is nearly identical to the instructions above.

First, search for and open the replacement strings. Then click on the tab *Cross-selling » Add item(s)* and search for all of the guitars.
Finally, check the option *Add to selection* and then click on the appropriate relationship.

[#600]
=== Modifying the links at a later time

Once you’ve <<item/online-store/cross-selling#300, created a cross-selling link>>, you’ll see it in an overview within the item data record.
In other words, you’ll see which accessories or replacement parts were linked to a particular main item.
The links can be modified or deleted any time.

[.instruction]
Modifying or deleting cross-selling links:

. Go to *Item » Edit item*.
. <<item/introduction/search#100, Search for>> and open the main item.
. Open the tab *Cross-selling » Cross-selling items*. +
→ You will see a list of all the accessories or replacement parts that were linked to this item.
. *_Modify_*: Choose a different relationship from the drop-down list.
. *_Delete_*: Select all of the items that should be deleted (icon:check-square[role="blue"]) and click on *Delete link*.
. *Save* (icon:save[role="green"]) the settings.

[#700]
== Displaying the cross-selling list in the online store

In brick and mortar stores, salespeople can talk directly to customers and recommend additional products.
In contrast, online stores have to showcase accessories and replacement parts differently.

[#800]
=== Ceres online stores

Use so-called _item lists_ to display cross-selling items in your store.
Continue reading and learn how to <<online-store/setting-up-ceres#110, set up cross-selling item lists in your Ceres store>>.

[#900]
=== Callisto online stores

Use _templates_ to display cross-selling items in your store.
These templates are found in the menu *CMS » Web design » Folder: Layout » Folder: ItemView*.   The following templates can be used for cross-selling:

* <<online-store/online-store/cms-syntax#web-design-itemview-container-itemviewcrosssellingitemslist, ItemViewCrossSellingItemsList>>
* <<online-store/online-store/cms-syntax#web-design-itemview-container-itemviewcrosssellingitemslist2, ItemViewCrossSellingItemsList2>>
* <<online-store/online-store/cms-syntax#web-design-itemview-container-itemviewcrosssellingitemslist3, ItemViewCrossSellingItemsList3>>

Define the <<online-store/online-store/item-sorting#, sorting sequence>> in each template’s *Settings* tab.
Continue reading and learn more about <<online-store/online-store/item-sorting#_displaying_cross_selling_items_on_an_items_page, setting up cross-selling items in your Callisto store>>.
