= Store specials
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Online store, Items, Deals, Specials, New items, Top items, Store special, Store specials, Ceres
:position: 50
:url: item/online-store/store-specials

Do you want to highlight certain items in your online store? For example, do you want to display a list of new products, special offers or best sellers directly on the homepage? Then configure store specials in plentymarkets and feature select items in your store!

[TIP]
.Ceres vs. Callisto store
====
The procedure varies depending on whether you use a newer Ceres store or an older Callisto store. Both procedures are described on this page.
====

[#100]
== Store specials in Ceres

In Ceres, store specials are created with the help of _tags_. There are three steps to the process:

* <<basics/working-with-plentymarkets/tags#, Create the tags>> that you want to use for your items, e.g. "Best seller”. 
* <<item/managing-items#150, Link your variations to the tags>>. For example, give all of your best selling items the “Best seller” tag.
* <<online-store/setting-up-ceres#110, Create an item list>> to display the tagged items in your online store. Don’t forget to specify the ID for your “Best seller” tag.

[#200]
== Store specials in Callisto

Store specials are _less flexible_ in Callisto than they are in Ceres.

* Callisto only allows you to highlight entire items in the online store. Ceres allows you to feature individual variations.
* Callisto only allows you to call an item a “Special offer”, “New item” or “Top item”. Ceres allows you to think up your own names.

[#300]
=== Adding items to the store special

First, decide which items should be included in the store special.

[.instruction]
Adding items to the store special:

. Go to *Item » Edit item*.
. <<item/introduction/search#100, Search for>> and open the item that should be included in the store special.
. Click on the *Global* tab.
. Find the *Online store* area. Use the *Store special* drop-down list to specify whether you want to call this item a special offer, a new item or a top item.
. *Save* (icon:save[role="green"]) the settings.

[TIP]
.Other ways to add items
====
The instructions above explain how to manually add items to a store special. However, you could also use the group function if you want to <<item/managing-items#155, add several items at the same time>>. Or you could use the procedure manager if you want to <<item/online-store/store-specials#400, automatically add items to the store special>>, e.g. when the price drops.
====

[#400]
==== Automatically adding items to the store special

Use the procedure manager to automatically link items with store specials.

[.instruction]
Setting up the procedure manager:

. Go to *Setup » Item » Procedures*.
. Click on the *New procedure* tab.
. Select the procedure *Link items to an online store special*.
. Configure the settings for the procedure manager. Note <<table-link-store-actions>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-link-store-actions]]
.Automatically adding items with the procedure manager
[cols="1,3"]
|====
|Setting |Explanation

2+|*Tab: Settings*

|*Name*
|Enter a meaningful name.

|*Execute every day at*
|Choose a time when the procedure should be carried out each day.

|*Active*
|Place a check mark (icon:check-square[role="blue"]) once you’re ready for the procedure to take effect. In other words, leave this option deactivated until you’ve finished configuring the settings.

2+|*Tab: Filter*

|*Price filter*
|Items will automatically be added to the store special if their prices match the criteria specified here. For example, you can link all items that have a higher RRP than regular price.

|*Online store*
|Should items only be included in the store special if they are visible in the online store? Use the drop-down list to tell plentymarkets your choice.

|*Active items only*
|Select this option (icon:check-square[role="blue"]) if you only want <<item/managing-items#230, active items>> to be added to the store special. Inactive items will not be linked.

|*Availability*
|Choose an <<item/managing-items#230, availability level>> from the drop-down list if you only want items with this availability level to be included in the store special.

|*Flag 1; +
Flag 2*
|Choose one or two <<item/managing-items#810, flags>> if you only want items with these flags to be included in the store special.

2+|*Tab: Procedure*

|*Store special*
|Should the items be called special offers, new items or top items? All of the items that match the filter criteria will automatically be given this designation in the *Global* tab.

|*Category (Item)*
|Should the items automatically be sorted into a particular category? If so, choose this category from the drop-down list.

|*Delete category (Item)*
|Should the items automatically be removed from a particular category? If so, choose this category from the drop-down list.
|====

[#500]
=== Displaying specials in the online store

Specials are displayed in the online store with the help of templates. These templates are found in the menu *CMS » Web design » Folder: Layout » Folder: ItemView*.   The following templates can be used for store specials:

* Top items: <<online-store/online-store/cms-syntax#web-design-itemview-container-itemviewtopsellerslist, ItemViewTopSellersList>>
* Special offers: <<online-store/online-store/cms-syntax#web-design-itemview-container-itemviewspecialofferslist, ItemViewSpecialOffersList>>
* New items: <<online-store/online-store/cms-syntax#web-design-itemview-container-itemviewlastseenlist, ItemViewLatestItemsList>>

Define the <<online-store/online-store/item-sorting#, sorting sequence>> in each template’s *Settings* tab.

[#600]
== Callisto: Displaying items by their position number

You can use <<item/online-store/store-specials#, store specials>> to highlight specific items in your online store, e.g. best selling items or special offers. The _position number_ is another way to highlight items. In this case, the items with the highest position numbers are displayed in the online store.

You can either <<item/online-store/store-specials#700, manually enter position numbers for your items>>, i.e. decide which items should be featured in the online store, regardless of their actual sales figures. Or you can have plentymarkets <<item/online-store/store-specials#800, automatically calculate>> which items sell best. In this case, which items are displayed in the store depends on the actual sales figures.

[#700]
=== Manually entering position numbers

By manually entering position numbers, you decide yourself which items should be displayed in the online store. It doesn’t matter how well the item actually sells.

There are three steps to the process. First, you’ll tell plentymarkets that you plan to enter position numbers manually. Second, you’ll enter the position numbers into your item data records. Third, you’ll use a template to <<item/online-store/store-specials#900, display the items in your online store>>.

[.instruction]
Telling plentymarkets your choice:

. Go to *Setup » Client » Select client » Item layouts » Settings*.
. Make sure the option *Automatically sort by monthly sales* is set to *No*.
. *Save* (icon:save[role="green"]) the settings.

[.instruction]
Entering position numbers into your item data records:

. Go to *Item » Edit item*.
. <<item/introduction/search#100, Search for>> and open the items that should be displayed in your online store.
. Click on the variation’s *Settings* tab.
. Find the *Basic settings* area. Enter a number into the *Position* field. +
→ Items will be displayed in descending order by their position number. Therefore, assign the highest position numbers to whichever items should be displayed in your online store.
. *Save* (icon:save[role="green"]) the settings.

[#800]
=== Automatically calculating position numbers

Once a day, plentymarkets can automatically calculate how often item variations have been sold. These sales determine the position. The most frequently sold top item will be given the highest position number.

There are two steps to the process. First, you’ll tell plentymarkets that the position numbers should be calculated automatically. Second, you’ll use a template to <<item/online-store/store-specials#900, display the items in your online store>>.

[.instruction]
Telling plentymarkets your choice:

. Go to *Setup » Client » Select client » Item layouts » Settings*.
. Make sure the option *Automatically sort by monthly sales* is set to *Yes*.
. *Save* (icon:save[role="green"]) the settings.

Position numbers will automatically be entered into your variations’ *Settings* tab. Manually entered position numbers will be overwritten in the process. The automatic assignment is based on your monthly sales and thus will display your true top sellers.

[#900]
=== Displaying items in the online store

Items are displayed in the online store with the help of a template. The template is found in the menu *CMS » Web design » Folder: Layout » Folder: ItemView*.   Use the template <<online-store/online-store/cms-syntax#web-design-itemview-container-itemviewitemsbypositionlist, ItemViewItemsByPositionList>> to display your items in descending order by their position numbers.
