= Best practice: Rakuten
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Rakuten, Multi-Channel, item export, elastic export
:position: 20

== Setting up the item export

[.subhead]
Issue

In plentymarkets 7, the old exports which were set up in plentymarkets 6 do not function properly any more.
A new elastic export has to be created as a substitute.

[discrete]
=== Instructions

[discrete]
==== Step 1

Download the plugins *Elastic export* and *RakutenDE* from the link:https://marketplace.plentymarkets.com/en[plentyMarketplace] for 0.00 EUR. Log in with the same access data that you also use for the Service Center. If you do not know your access data, go to *Start » plentymarkets account » Service Center* to view your email address and your password.

[discrete]
==== Step 2

Install the plugins. Pay attention to the following guide.

link:https://forum.plentymarkets.com/t/faq-elastischer-export-wie-installiere-ich-ein-plugin-ein-update-fuer-ein-plugin/46271[Wie installiere ich ein Plugin?^] (Please note that this guide is currently only available in German.)

[discrete]
==== Step 3

Create an elastic export for each of your Rakuten.de accounts. To do so, go to *Data exchange » Elastic export*.
link:https://forum.plentymarkets.com/t/faq-elastischer-export-wie-installiere-ich-ein-plugin-ein-update-fuer-ein-plugin/46271[Wie installiere ich ein Plugin?^] (Please note that this guide is currently only available in German.)

The following settings should be carried out to replicate the old logic:

. Settings

* *Format:* RakutenDE-plugin
* *File name:* e.g. Rakuten.csv (The file name must have the ending “.csv.”!)
* *Token:* Click on *Generate token* to generate the token. The token is automatically added to the format’s URL. It is a token for authentication.

. Item filters

* *Filter “Active”:* Select *Active*.
* *Filter “Markets”:* Select *Rakuten.de*. *Important!* The name may differ. Go to *System » System settings » Orders » Order referrer* and check if the name was changed.
* *Filter “Client”* (optional): Select the client. It must be the same client that you selected in the *System » System settings » Markets » Rakuten.de* menu for the option *Client (store) assignment* for this account.

. Format settings

* *Setting “Client”:* Select the client. It must be the same client that you selected in the *System » System settings » Markets » Rakuten.de* menu under the option *Client (store) assignment* for this account.
* *Setting “Order referrer”* The same as the item filter *Markets*.
* *Setting “Account”:* If you have more than one account, select the appropriate account.
* *Setting “Overwrite item availability”:* Place a check mark next to the option *overwrite* and enter a permitted value for Rakuten in the item availability fields, for example 0, 3, 5 or 7.
* *Setting "Item filter":* Add the *prices* filter and select the option *with price*.

The selected settings ensure that the function is the same as in plentymarkets 6. Except for item availability, all settings can be changed, for example to exclude further items from export by using the item filters.

You can check the content of the file by downloading the file.

[discrete]
==== Step 4

Use the elastic export's URL to set up the import of the file in the Rakuten.de seller section. If you have little or no experience, contact the Rakuten support team to help you set up a schedule.

The setup is now completed.
