= Setting up Rakuten
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Rakuten, Market, Marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the market Rakuten in your plentymarkets system.
:position: 10

With plentymarkets you can sell items on the platform Rakuten.de.

[#100]
== Registering with Rakuten

You need to register with Rakuten before setting up Rakuten in plentymarkets. Use the registration forms of the platform link:http://leadgen.rakuten.de/form?leadsource=marketplace_header[rakuten.de^].

[#200]
==  Setting up Rakuten.de in plentymarkets

Carry out the following settings in plentymarkets in order to set up the interface to Rakuten.de.

[.instruction]
Setting up Rakuten.de:

. Go to *System » System settings » Markets » Rakuten.de*. +
→ The *New account* tab is displayed.
. Expand the *Rakuten settings*.  +
→ The platform *rakuten.de* is pre-selected.
. Enter the *Authentication key*. +
→ You can find the key in the back end of your Rakuten.de account.
. Carry out the settings. Pay attention to the explanations given in table 1.
. *Save* the settings.
. Reload the menu.  +
→ The account was created and the platform’s settings were loaded.

If you use multiple accounts for Rakuten.de, you need an authentication key for each account.

.Configuring Rakuten
[cols="1,3"]
|====
|Setting |Explanation

2+|Order import

|*Activate*
|*Deactivate* = Interface is inactive. +
*Activate* = Interface is active. New orders will automatically be retrieved once an hour. Sent orders will automatically be transferred to Rakuten every hour.

|*Payment*
|*Incoming payment pending* = Import orders as unpaid. +
*Incoming payment booked* = Import orders as paid. In this way, Rakuten can be tested. The order can be set to paid when the incoming payment from Rakuten is received. +
 Regardless of the chosen setting, items will immediately be cleared for shipping when they have sufficient stock.

|*Send order confirmation*
|*Deactivate* = Order confirmations are not transferred. +
*Activate* = Order confirmations are transferred to the customer. The email template saved under *System » System settings » Client » Select client » Email » Automatic* is sent to the customer.

|*View API log*
|Click on *View API log* to display the API log.
|====

Connecting to this market allows for the following automatic processes to take place:

* hourly order synchronisation

The following processes are carried out by the link:https://marketplace.plentymarkets.com/en/plugins/markets/ElasticExportRakutenDE_4721[ElasticExportRakutenDE plugin^].

* hourly stock synchronisation
* hourly price synchronisation

After you have installed the *ElasticExportRakutenDE plugin*, you can use the data format *RakutenDE plugin* for the elastic export. The plugin is available in the link:https://marketplace.plentymarkets.com/plugins/markets[plentyMarketplace^]. For further information about setting up the plugin in plentymarkets, refer to the plugin’s user guide.

[#250]
=== Activating an order referrer

In order to link items, properties etc. with Rakuten you have to activate the order referrer Rakuten in the menu *System » System settings » Orders » Order referrer*.

[.instruction]
Activating the order referrer for Rakuten:

. Go to *System » System settings » Orders » Order referrer*.
. Place a check mark next to *Rakuten.de*.
. *Save* the settings.

[#300]
=== Setting the item availability

Items that you want to sell on Rakuten.de have to be available for Rakuten. This is done in the *Availability* tab of an item within the <<item/managing-items#, Item » Edit item » Tab: Variation ID>> menu.

[.instruction]
Setting the item availability for Rakuten.de:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Activate the option *Rakuten.de*.
. Click on *Add*. +
→ The market is added.
. *Save* the settings. +
→ The item is available on Rakuten.de.

The availability for variations can be individually edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

[#350]
===  Defining SKU manually

Add SKUs manually for specific referrers in the menu <<en/item/managing-items#_changing_the_variation_data_shown_in_variation_tabs, Item » Edit item » Open item » Tab: Variation ID>>.

[.instruction]
Adding SKU

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
.  Click on the *Availability* tab.
.  Click on *Add* in the section *SKU*. +
→ The window *New SKU* is displayed.
.  Select the Referrer *Rakuten.de*.
.  Select the corresponding marketplace account.
.  Enter the SKU.
.  Click on *Add*. +
→ The SKU is saved and displayed.

[#400]
=== Linking categories

After you have made the item available, link it to the categories on Rakuten.

[.instruction]
Linking a category:

. Go to *Item » Edit item*.
. Open the item.
. Open the *Multi-Channel* tab.
. Select the main category for the item from the *Rakuten.de* drop-down list within the section *Category link*. +
→ A window for selecting further categories is opened.
. Select the subcategories until you have reached the lowest possible category level. +
→ A category number is displayed.
. Click on *Apply*. +
→ The category link is displayed by the category number and the Rakuten category.
. *Save* the settings.

[#500]
=== Linking shipping groups to items

Shipping profiles are set up directly on Rakuten. The shipping profiles that are saved for items will not be transferred to Rakuten. On Rakuten.de, the shipping profiles are called shipping groups (Versandgruppen). These shipping groups are linked to your items with a <<en/item/managing-items#70, free text field>>.

[.instruction]
Setting up a free text field for a shipping group:

. Go to *System » System settings » Item » Free text fields*.
. Enter a name for one of the free text fields, e.g. *Rakuten shipping group*.
. *Save* the settings. +
→ Note: Free text fields are activated at night and will be available the next morning.
. Go to *Item » Edit item*.
. Open each of the items that you want to transfer and enter the *shipping group number* in the item's *Fields* tab.
. *Save* the settings.
. Let Rakuten know which free text field is used.

[TIP]
.No free text field
====
If no free text field is transferred to Rakuten, then a link to shipping group 1 will automatically be created.
====

Set up further countries of delivery on Rakuten, too.

[#600]
=== Providing information on the energy efficiency

To comply with EU regulations on energy efficiency that came into force on 1 January 2015, you have to provide information on the energy efficiency of certain items. In addition, you have to make product data sheets available to potential buyers of these items. This information also has to be transferred to Rakuten. Create the following <<en/item/managing-items#480, properties>>:

* *Energy efficiency class* +
Property type: *No*
* *Energy efficiency class up to* +
Property type: *No* +

* *Device group - energy efficiency class* +
Property type: *No*

You have to create a separate property for each energy efficiency class from A+++ to G.

[.instruction]
Creating a property:

. Go to *System » System settings » Item » Properties*.
. Click on the *New property* tab.
. Enter a name for the property under *Name (internal)*.
. Select the option *No* from the *Property type* drop-down list.
. Select the Rakuten property from the *Rakuten.de property* drop-down list.
. *Save* the settings.

Link the properties in the <<en/item/managing-items#480, Properties>> tab of an item.


Make the product data sheet available for Rakuten in electronic form. This is done by inserting a link in the item description. The link to the product data sheet is saved in an item's <<item/managing-items#50, Texts>> tab. To do so, proceed as follows.

[.instruction]
Saving the product data sheet in the item description:

. Go to *Item » Edit item*.
. Upload the product data sheet in the item's *Images* tab.
. Copy the image URL.
. Insert the link to the product data sheet in the item's *Texts* tab.
. *Save* the settings.

[#700]
=== Setting up the item export

This chapter explains how to transfer your items to Rakuten.de. The item export for Rakuten is carried out by the elastic export. The data format RakutenDE is used for this. Therefore, the plugins *ElasticExport* and *ElasticExportRakutenDE* have to be installed. First, create the data format RakutenDE. Then transfer the URL to Rakuten.de

[IMPORTANT]
.Contact Rakuten for the setup
====
It is mandatory to contact Rakuten for setting up the export.
====

[.instruction]
Setting up the item export:

. Go to *Data » Elastic export*.
. Click on *New export*.
. Carry out the settings. Pay attention to the information given in table 2.
. Carry out further settings for item filters and format settings. Pay attention to the information given in table 5 in the <<en/basics/data-exchange/export-import/exporting-data#60, Exporting data page of the manual*>>
. *Save* the settings. +
→ The export format is given an ID and it appears in the overview within the *Exports* tab.

.Settings for the item export
[cols="1,3"]
|====
|Setting |Explanation

2+|Settings

|*Name*
|Enter a name. The export format is listed under this name in the overview within the *Exports* tab.

|*Type*
|Select the type *item* from the drop-down list.

|*Format*
|Select the format *RakutenDE* from the drop-down list.

|*Limit*
|Enter a number. If you want to transfer more than 10,000 data records to rakuten.de, then the output file will not be generated again for another 24 hours. This is to save resources.

|*Generate cache file*
|Place a check mark if you want to transfer more than 9,999 data records to the price search engine. We recommend that you do not activate this setting for more than 20 export formats. This is to ensure a high performance of the elastic export.

|*Provisioning*
|Select *URL*.

|*File name,*
|The file name must have the ending *.csv* for Rakuten.de to be able to import the file successfully.

|*Token*, +
*URL*
|If you have selected the option *URL* under *Provisioning*, then click on *Generate token*. The token is entered automatically. The URL is entered automatically if the token was generated under *Token*. Give this URL to Rakuten.de in order to export the items.

2+|Format settings

|*Product URL*
|Choose the URL that you wish to transfer to Rakuten.de. You can choose between the item’s URL and the variation’s URL. URLs of variations can only be transferred in combination with the Ceres store.

|*Client*
|Select a client. This setting is used for the URL structure.

|*URL parameter*
|Enter a suffix for the product URL if this is required for the export. This character string will be added to the product URL if you have activated the *transfer* option for the product URL further up.

|*Order referrer*
|Select *Rakuten.de*.

|*Marketplace account*
|If you export item data for the first time, the account selected here is considered when generating an SKU.

|*Language*
|Select the language from the drop-down list.

|*Item name*
|Select Name 1, Name 2 or Name 3. These names are saved in the *Texts* tab of the item. Enter a number into the *Maximum number of characters (def. Text)* field if desired. This specifies how many characters are exported for the item name.

|*Preview text*
|This option does not affect Rakuten.de.

|*Description*
|Select the text that you want to transfer as description. +
Enter a number into the *Maximum number of characters (def. Text)* field if desired. This specifies how many characters are exported for the description. +
 Activate the option *Remove HTML tags* if you want HTML tags to be removed during the export. +
If you only want to allow specific HTML tags to be exported, then enter these tags into the field  *Permitted HTML tags, separated by comma (def. Text)*. Use commas to separate multiple tags.

|*Target country*
|Select the target country from the drop-down list.

|*Barcode*
|Select the ISBN or an EAN from the drop-down list. The barcode has to be linked to the order referrer selected above. If the barcode is not linked to the order referrer it will not be exported.

|*Image*
|Select *Position 0* or *First image* to export this image. +
* Position 0* = An image with position 0 is transferred. +
* First image* = The first image is transferred.

|*Image position of the energy label*
|Enter the position of the energy label. Every image that should be transferred as an energy label must have this position.

|*Stock buffer*
|The stock buffer for variations with limitation to the net stock. Enter a number. The stock is reduced by the value of this number.

|*Stock for variation without stock limitation*
|The stock for variations without stock limitation.

|*Stock for variations with no stock administration*
|The stock for variations without stock administration.

|*Live currency conversion*
|Activate this option to convert the price into the currency of the selected country of delivery. The price has to be released for the corresponding currency.

|*Retail price*
|Select gross price or net price from the drop-down list.

|*Offer price*
|Activate to transfer the offer price.

|*RRP*
|Activate to transfer the RRP.

|*Shipping costs*
|Activate this option if you want to use the shipping costs that are saved in a configuration. If this option is activated, then you are able to select the configuration and the payment method from the drop-down lists. +
 Activate the option *Transfer flat rate shipping charge* if you want to use a fixed shipping charge. If this option is activated, a value has to be entered in the line underneath.

|*VAT note*
|Enter text. This amount includes the VAT but does not include shipping.

|*Item availability*
|Activate the *overwrite* option and enter item availabilities into the fields *1* to *10*. The fields represent the IDs of the availabilities. This overwrites the item availabilities that are saved in the menu *System » System settings » Item » Item availability*.
|====

[IMPORTANT]
.Export information
====
If you change one or more settings, then you have to transfer the new link to Rakuten.

A maximum of 4000 items will be exported at once. If you export more items, then a second export is automatically carried out. To display the second export process, set the parameter *&Page* = in the export link to *2*.

Technical data is transferred to Rakuten in the last column of the export file.
====

==== Overwriting delivery periods

Rakuten requires pre-defined values for the delivery period. For example, you cannot transfer the values 1 or 2 as delivery period. In this case, the export will be rejected with an error.
Therefore, you have to overwrite the delivery period in the elastic export for Rakuten. The following list contains an overview of Rakuten delivery periods with the corresponding item availabilities. If your item availability ID 1 means that the items are in stock and will be delivered within the next 1-3 business days, then use the elastic export to overwrite the item availability ID 1 with the delivery period 0.

* 0 = Available from stock (= delivery period 1 to 3 business days)
* 3= Ready for shipping within 3 business days (= delivery period approx. 3 to 6 business days)
* 5 = Ready for shipping within 5 business days (= delivery period approx. 6 to 8 business days)
* 7 = Ready for shipping within 7 business days (= delivery period approx. 8 to 10 business days)
* 10 = Ready for shipping within 10 business days (= delivery period approx. 10 to 15 business days)
* 15 = Ready for shipping within 15 business days (= delivery period approx. 15 to 20 business days)
* 20 = Ready for shipping within 20 business days (= delivery period approx. 20 to 30 business days)
* 30 = Ready for shipping within 30 business days (= delivery period approx. 30 to 40 business days)
* 40 = Ready for shipping within 40 business days (= delivery period approx. 40 to 50 business days)
* 50 = Ready for shipping within 50 business days (= delivery period approx. 50 to 60 business days)
* 60 = Ready for shipping within 60 business days (= delivery period more than 3 months)

The values for the delivery periods are also available in Rakuten’s link:http://doku.rakuten.de/doku.php/neuer_import/start[Interface documentation^]. Please note that this documentation is currently only available in German.

==== Adding prefixes and suffixes to a parent SKU

If you have installed thelink:https://marketplace.plentymarkets.com/plugins/markets/ElasticExportRakutenDE_4721[ElasticExportRakutenDE plugin^] in your plentymarkets system, then you can add prefixes and suffixes to parent SKUs. This way you avoid identical parent and child SKUs which will be treated as the same item on Rakuten.

Prefixes and suffixes are added within the *Plugins » Plugin overview » ElasticExportRakutenDE » Configuration » Parent SKU* menu.

[.instruction]
Adding prefixes and suffixes:

. Go to *Plugins » Plugin overview*.
. Click on the *ElasticExportRakutenDE* plugin.
. Go to *Configuration » Parent SKU*.
. Enter a prefix and suffix in the *Prefix* and *Suffix* fields as desired.
. *Save* the settings. +
→ The entered prefixes and suffixes are added to parent SKUs which you generate afterwards.

[TIP]
.Use alphanumeric characters
====
We recommend to use only letters and numbers for the prefixes and suffixes. You should avoid using umlauts. Using umlauts for the prefix and suffix might cause problems during the data exchange.
====

[IMPORTANT]
.Changes only apply to SKUs which you generate afterwards
====
Please note that the prefixes and suffixes are only added to those SKUs which you generate for Rakuten.de after you have saved this setting. Parent SKUs which already exist are not considered for this setting. Add prefixes and suffixes manually to those SKUs if desired.
====

[#800]
=== Setting up the price synchronisation

In this chapter, you will learn how to activate the price synchronisation for Rakuten. The price synchronisation for Rakuten is carried out by the elastic export. The data format RakutenDE is used for this. Therefore, the plugins *ElasticExport* and *ElasticExportRakutenDE* have to be installed. +
The price synchronisation is carried out once an hour.

[.instruction]
Activating the price synchronisation:

. Go to *Plugins » Plugin overview*.
. Click on the *ElasticExportRakutenDE* plugin.
. Go to *Configuration » Update settings*.
. Place a check mark next to the option *Price update*.
. *Save* the settings.

[#900]
=== Setting up the stock synchronisation:

In this chapter, you will learn how to activate the stock synchronisation for Rakuten. The stock synchronisation for Rakuten is carried out by the elastic export. The data format RakutenDE is used for this. Therefore, the plugins *ElasticExport* and *ElasticExportRakutenDE* have to be installed. +
The stock synchronisation is carried out once an hour.

[.instruction]
Activating the stock synchronisation:

. Go to *Plugins » Plugin overview*.
. Click on the *ElasticExportRakutenDE* plugin.
. Go to *Configuration » Update settings*.
. Place a check mark next to the option *Stock update*.
. *Save* the settings.

[#1400]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Rakuten.de. The price is displayed on Rakuten.de.

[.instruction]
Defining a sales price for Rakuten:

. Open the menu *System » System settings » Item » Sales price » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *Rakuten.de*.
. *Save* the settings.

[TIP]
.Original currency is not the default currency
====
Additional information is saved for orders that are imported with a different currency than the default currency saved in plentymarkets. In this case, both the original currency and the original gross and net amounts are saved for every item included in the order.
====

[#1500]
==  Activating payment methods

Activate the payment methods *Rakuten payment*, *Rakuten Rechnung* and *Klarna*. This allows payments to be made for orders on Rakuten and displayed in your plentymarkets system.

[.instruction]
Activating Rakuten payment methods:

.  Go to *System » System settings » Orders » Payment » Methods*.
.  Place a check mark next to the setting *Also show inactive*.
. Open the folder *DE* > *Rakuten*.
. Select the Rakuten payment method. +
→ The *Settings* tab opens.
.  Carry out the settings. Pay attention to the information given in table 3.
.  Place a check mark next to the option *Active*.
. *Save* the settings.

.Settings of the payment method
[cols="1,3"]
|====
| Setting | Explanation

|*Language*
| The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo* and *Upload logo*. This makes it possible to enter values for these options in various languages. The values for a language will be activated as soon as a buyer selects the language in the online store.

|*Name*
| Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
| Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
| If you have selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
| Do not select a country of delivery. +
 You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely set up.

|*Logo*
| Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

|*Logo view*
| If *Show upload logo* has been selected from the *Logo* drop-down list, then the logo that has been uploaded is displayed here.

|*Upload logo*
| If *Show upload logo* was selected from the *Logo* drop-down list, you can upload an external logo here. +
 Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|*Priority*
| Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
| If the payment method results in additional costs, enter the percentage value or the flat rate value. The choice depends on the conditions of your contract. *Important*: Do not enter a value into both fields. +
For further information, refer to the <<en/basics/statistics#, Statistics>> page of the manual. For an example of flat rate and percentage costs, refer to the <<payment/managing-payment-methods#20, Managing payment methods>> page of the manual.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *System » System settings » CRM » Classes* to activate or deactivate *Permitted payment methods*. +
For further information, refer to the <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter.
====

[TIP]
.Payment instruction on the invoice document for the payment method Rakuten Rechnung
====
Rakuten sends the invoice directly to the customer when Rakuten Rechnung is selected as the payment method. If you also issue an invoice, enter a *payment instruction* in the *Optional elements in the stock unit table* section. This payment instruction informs the customer that he or she has to pay Rakuten.

*Example text:* +
Payments are processed by Rakuten GmbH, Geisfelder Str. 16 in 96050 Bamberg. Because of this, the amount listed on this invoice is owed directly to Rakuten. It is not possible to make a payment to any other entity. Please pay the amount listed on this invoice within 10 days after receiving the goods. Transfer the amount to the Rakuten bank account listed below: +
Account holder Rakuten GmbH +
IBAN: DE86770200700021511501  +
BIC-/SWIFT-Code: HYVEDEMM411 (HypoVereinsbank) +
Designated use 1: Order number +
Designated use 2: First name & surname
====

For further information, refer to the <<payment/managing-payment-methods#, Payment methods>> page of the manual.

[#1600]
== Assigning delivery periods

Rakuten uses standard delivery periods. However, the market indicates deadlines rather than a time period spanning several days. These deadlines are always the last day in each timespan. Shipping and delivery periods for Rakuten are assigned automatically according to the *average period of delivery*. For example, if the *item availability* lists an average delivery time of 2 days, then there wouldn't be an exact equivalent for Rakuten. Therefore, the next longer shipping and delivery period is used for Rakuten.

.Rakuten delivery periods
[cols="1,3"]
|====
|Rakuten delivery period |Period

|*0*
|Available from stock (= delivery period 1 to 3 business days)

|*3*
|Ready for shipping within 3 business days (= delivery period approx. 3 to 6 business days)

|*5*
|Ready for shipping within 5 business days (= delivery period approx. 6 to 8 business days)

|*7*
|Ready for shipping within 7 business days (= delivery period approx. 8 to 10 business days)

|*10*
|Ready for shipping within 10 business days (= delivery period approx. 10 to 15 business days)

|*15*
|Ready for shipping within 15 business days (= delivery period approx. 15 to 20 business days)

|*20*
|Ready for shipping within 20 business days (= delivery period approx. 20 to 30 business days)

|*30*
|Ready for shipping within 30 business days (= delivery period approx. 30 to 40 business days)

|*40*
|Ready for shipping within 40 business days (= delivery period approx. 40 to 50 business days)

|*50*
|Ready for shipping within 50 business days (= delivery period approx. 50 to 60 business days)

|*60*
|Ready for shipping within 60 business days (= delivery period more than 3 months)
|====

[#170]
== Automatically sending preparation for shipping

Set up an *<<automation/event-procedures#, event procedure>>* to automatically flag orders as in preparation for shipping.  If you do so, customers and the Rakuten customer service cannot cancel orders for 48 hours. Use this time span to process the order and update the status to shipped afterwards.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-shipping-preparation-rakuten>>.
. *Save* the settings. +
→ The event is created.
.  Carry out further settings. Pay attention to the information given in <<event-procedure-shipping-preparation-rakuten>>.
.  Place a check mark next to the option *Active*.
. *Save* the settings. +
→ The event procedure is saved.
--

[[event-procedure-shipping-preparation-rakuten]]
.Event procedure for automatically sending preparation for shipping to Rakuten
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Status change: Preparing for Shipment*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*Rakuten*

|*Procedure*
|*Shipping &gt; Send preparation for shipping to Rakuten*
|
|====

[#170]
== Automatically sending shipping confirmations

Set up an <<automation/event-procedures#, event procedure>> to automatically send shipping confirmations to Rakuten when the outgoing items are booked.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-shipping-confirmation-rakuten>>.
. *Save* the settings. +
→ The event is created.
.  Carry out further settings. Pay attention to the explanations given in <<event-procedure-shipping-confirmation-rakuten>>.
.  Place a check mark next to the option *Active*.
. *Save* the settings. +
→ The event procedure is saved.
--

[[event-procedure-shipping-confirmation-rakuten]]
.Event procedure for sending automatic shipping confirmations to Rakuten
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order change: Outgoing items booked*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*Rakuten*

|*Procedure*
|*Shipping &gt; Send shipping confirmation to Rakuten*
|
|====

[#1800]
== Automatically sending returns

Set up an <<automation/event-procedures#, event procedure>> to automatically send returns to Rakuten.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-returns-rakuten>>.
. *Save* the settings. +
→ The event is created.
.  Carry out further settings. Pay attention to the explanations given in <<event-procedure-returns-rakuten>>.
.  Place a check mark next to the option *Active*.
. *Save* the settings. +
→ The event procedure is saved.
--

[[event-procedure-returns-rakuten]]
.Event procedure for sending automatic returns to Rakuten
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order generation: New return*
|

|*Filter 1*
|*Order &gt; Order type*
|*Return*

|*Filter 2*
|*Order &gt; Referrer*
|*Rakuten*

|*Procedure*
|*Return &gt; Send return to Rakuten*
|
|====

[#1900]
== Automatically sending cancellations

Set up an <<automation/event-procedures#, event procedure>> to automatically send cancellations to Rakuten.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » System settings » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-automatic-cancellation-rakuten>>.
. *Save* the settings. +
→ The event is created.
.  Carry out further settings. Pay attention to the information given in <<event-procedure-automatic-cancellation-rakuten>>.
.  Place a check mark next to the option *Active*.
. *Save* the settings. +
→ The event procedure is saved.
--

[[event-procedure-automatic-cancellation-rakuten]]
.Event procedure for sending automatic cancellations to Rakuten
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order change: Status change &gt; Cancelled*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*Rakuten*

|*Procedure*
|*Payment methods &gt; Send cancellation to Rakuten*
|
|====

[#2000]
== Viewing the log and the API log

The menus *Data » Log* and *Data » API log* contain a history of processes that run via the Rakuten interface. +
The *log* contains an overview of event procedures and the *API log* contains an overview of order imports.

=== Viewing the log

Open the menu *Data » Log* to retrieve an overview of event procedures that run via the Rakuten interface.

[.instruction]
Viewing log entries for Rakuten.de

. Go to *Data » Log*.
. Select the identifier *Rakuten.de* from the drop-down list *Identifier*.
. Select a filter from the drop-down list *Reference type* if you only want to see entries for a specific reference type. Pay attention to the information given in <<table-reference-types>>.
. Select a filter from the drop-down list *Reference value* if you only want to see entries for a specific reference value. Pay attention to the information given in <<table-reference-types>>.
. Select a date if you only want to see entries for a specific day.
. Select a time if you only want to see entries for a specific time of day.
. Click on *Search*.

Use the following reference types and reference values to filter the search results.

[[table-reference-types]]
.Reference types and reference values for Rakuten.de
[cols="1,3,3"]
|====
|Reference type |Explanation |Reference value

|*action*
|Filters the search results for event procedures.
|Select a reference value to search for event procedures of a specific type. +
*SendOrderStatusInLogistics* = Filters for event procedures of the type *Send preparation for shipping to Rakuten*. +
*SendOrderStatusShipped* = Filters for event procedures of the type *Send shipping confirmation to Rakuten*. +
*SendOrderTrackingData* = Filters for event procedures of the type *Send tracking information to Rakuten*. +
*SendOrderStatusCanceled* = Filters for event procedures of the type *Send cancellation to Rakuten*. +
*SendOrderStatusReturned* = Filters for event procedures of the type *Send return to Rakuten*.

|*externalOrderID*
|Filters the search results for entries of a specific external order ID.
|

|*orderID*
|Filters the search results for entries of a specific order ID.
|
|====

=== Viewing the API log

Open the menu *Data » API log » Tab: API log* to retrieve an overview of order imports that run via the Rakuten interface. The *Rakuten* format is available for Rakuten.

[.instruction]
Viewing the API log:

. Go to *Data » API log » Tab: API log*.
. Select the *Rakuten* format from the *Process* drop-down list.
. Select a date if you only want to see entries for a specific day.
. Select the number of results per page.
. Click on *Search* to display the results.

[#2100]
== FAQ

[.instruction]
How is the stock synchronised in plentymarkets with Rakuten.de?

[.indented]
If the automatic CSV import is set up for Rakuten.de, then the new stock will be synchronised by importing the CSV file again. Define how often synchronisation should take place in the Rakuten.de back end.
