= Plugins dem System hinzufügen
:lang: de
include::{includedir}/_header.adoc[]
:author: team-plugin-core
:position: 120
:url: willkommen/schnelleinstieg/schnelleinstieg-plugins
:id: KQTQONO

IMPORTANT: Hast du schon Vorlagen für Rechnung und Stornobelege erstellt? Noch nicht? Dann geht's hier zurück zum Thema <<willkommen/schnelleinstieg/schnelleinstieg-auftragsabwicklung#, Auftragsabwicklung vorbereiten>>.

Wie du bereits gesehen hast, kannst du die Funktionalität deines Shops durch Plugins erweitern. Einige Plugins können über den Integrations-Assistenten installiert werden, es gibt aber noch viele weitere Möglichkeiten, plentymarkets zu erweitern. Zu diesem Zweck werden wir beispielhaft dem System ein neues Plugin hinzufügen, dieses installieren und einrichten.

Mit unserem neuen Plugin wollen wir Kunden die Möglichkeit geben, die Artikel in unserem Shop zu bewerten und diese Bewertungen anderen potenziellen Käufern anzeigen. Dazu werden wir das Plugin Kunden-Feedback nutzen. Dieses Plugin ist gratis über plentyMarketplace erhältlich.

include::../../plugins/_textblocks/instructions/marketplace-plugin-kaufen.adoc[]

include::../../plugins/_textblocks/tables/marketplace-kaufoptionen.adoc[]

[TIP]
.Einstellungsmöglichkeiten
====
In der Artikelansicht jedes Plugins wird auch beschrieben, welche Einstellungsmöglichkeiten für das jeweilige Plugin zu Verfügung stehen. Im Rahmen des Schnelleinstiegs werden die notwendigen Schritte aber auch im Folgenden genauer beschrieben.
====

Als nächstes werden wir das neu gekaufte Plugin installieren. Gehe dazu wie bei der Installation des Plugins Vorkasse im letzten Kapitel vor.

:plugin: Kunden-Feedback

include::../../plugins/_chapters/plugin-in-set-installieren.adoc[]

Sobald das Plugin installiert ist, kann es eingerichtet werden. Bei manchen Plugins, wie *Vorkasse*, werden diese Einstellungen in den Systemeinstellungen vorgenommen. Bei anderen, wie *Kunden-Feedback*, geschieht dies direkt in den Plugin-Einstellungen.

[.instruction]
Kunden-Feedback einrichten:

. Öffne die Einstellungen (icon:cog[]) von Kunden-Feedback. +
→ Die Detailansicht des Plugins wird geöffnet. Das Tab *Einstellung* ist bereits ausgewählt.
. Aktiviere die Option *Bewertungen automatisch veröffentlichen*, *Datum an der Bewertung anzeigen* und *Bewertungen nur erlauben, wenn der Artikel gekauft wurde*.
. *Speichere* die Einstellungen.

Mit diesen Einstellungen können Kunden nach dem Kauf eines Artikels eine Bewertung für diesen Artikel schreiben. Die Bewertung wird automatisch angezeigt und ist für andere Kunden sichtbar, die den entsprechenden Artikel aufrufen.

Abschließend müssen wir noch dafür sorgen, dass das Feedback auch wirklich in unserem Shop angezeigt wird. Dazu müssen wir einige Container-Verknüpfungen erstellen.

[.instruction]
Container-Verknüpfungen einrichten:

include::../../plugins/_textblocks/instructions/plugin-container-verknuepfung.adoc[]
. Öffne das Dropdown-Menü *Feedback Javascript (Feedback*).
. Aktiviere die Option *Script loader: Register/load JS*.
. Öffne das Dropdown-Menü *Feedback CSS (Ceres) (Feedback)*.
. Aktiviere die Option *Template: Style*.
. Öffne das Dropdown-Menü *Feedback ratings (Feedback)*.
. Aktiviere die Option *Single item: Container for customer feedback*.
. Öffne das Dropdown-Menü *Feedback category ratings (Feedback)*.
. Aktiviere die Option *Category item list: Before prices container*.
. *Speichere* die Verknüpfungen.

Damit sind alle Einstellungen abgeschlossen und Kunden werden die Möglichkeit haben, Artikel nach dem Kauf auch zu bewerten. Im nächsten Kapitel kehren wir zu einem der standardmäßig installierten Plugins zurück: Ceres. Mit diesem Plugin kann das Aussehen des Shops beeinflusst werden.

== Mehr zum Thema Plugins

* <<plugins#, Plugins kennenlernen>>
* link:https://marketplace.plentymarkets.com/[plentyMarketplace^]{nbsp}icon:external-link[]

TIP: Weiter zum Thema <<willkommen/schnelleinstieg/schnelleinstieg-ebay#, eBay>>
