= Managing contacts
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kontakt, Kunde, Adressen
:description: Erfahren Sie, wie Sie in plentymarkets Kontakte erstellen und verwalten.
:position: 11

[IMPORTANT]
.Note about the "Managing contacts" page of the manual
====
This page of the manual describes all settings that are available in the *CRM » Contacts* menu in the new terra back end. The <<crm/managing-customer-data#, *Managing customer data*>> page of the manual that describes the settings in the *Customers » Edit customers* and *Settings » Customers* menus will be simultaneously available. Once the new *CRM » Contacts* menu has completely replaced the old *Customers » Edit customers* menu, the *Customers » Edit customers* menu as well as the *Managing customer data* page of the manual will be removed.
====

Go to *CRM » Contacts* to create data records about contacts and save all relevant information there. You can also edit and delete your contacts in this menu as well as display the addresses of your contacts, add new addresses and delete existing addresses. Furthermore, it is possible to take a look at the history of a contact. The history displays, for example, the registration date and if it is a regular account or a guest account.

[#100]
== Creating a contact

Proceed as described below to create a new contact. Add contact options such as email addresses, telephone numbers and, if required, the VAT number. You can also create a new contact, for example, while taking an order over the phone or while filling out a written order. It is also possible to save the contact details of interested parties here. When creating a contact, the system will automatically assign an ID. This ID cannot be changed.

[.instruction]
Creating a contact:

. Go to *CRM » Contacts*.
. Click on *Create new contact*.
. Carry out the settings as desired in the *New contact* section. Pay attention to the information given in table 1.
. In the *Contact options* section, select the type and sub-type from the drop-down values and enter the value. Pay attention to the information given in table 1. +
→ Click on *Add contact option* to add further contact options.
. *Save* the settings.

.Creating a contact
[cols="a,a"]
|====
|Setting |Explanation

2+|New contact

|*Form of address*
|Select the option from the drop-down menu. This selection is optional. +
*Ms.* = Female form of address +
*Mr.* = Male form of address

|*Title*
|Enter the title of the contact, if required.

|*First name*, *Last name*
|Enter the first and last name of the contact.

|*Client (store)*
|Select the client (store) from the drop-down menu in order to assign the contact to this client (store). +
Only those clients will be displayed that have a name entered for them in the store's *basic settings* under *Settings » Client (store)*.

|*Language*
|Select the language for the contact. For example, invoice documents will be sent in this language if you created a template in this language.

|*Type*
|Select the type. The types *Customer*, *Sales representative*, *Supplier*, *Partner*, *Manufacturer* and *Interested party* can be selected by default. Create further types in the <<crm/managing-customer-data#300, *Settings » Customers » Types*>> menu.

|*Class*
|Select the class. Classes serve as an internal distinction between customers and which discount will be granted this class, for example. Go to <<crm/managing-customer-data#100, *Settings » Customers » Customer classes*>> to create further classes. If you want to offer different prices to end customers and sellers in the online store, then this can be done with the *Display of the prices in the online store* option in the configuration of the classes. For end customers (B2C), the gross prices are displayed in the online store. For sellers (B2B), the net prices are displayed in the online store. +
Empty option = No assignment to a class +
*_Important_*: If there is no assignment to a class, the contact will be automatically assigned to the class with the lowest position. As the price display in the online store is configured for each class, check this option for the class with the position 1 so that the correct price is displayed during automatic assignments.

|*Sales representative*
|With this setting, a sales representative will be assigned to a type. Enter the sales representative's ID or enter the first three letters of the sales representative's name. Matching representatives will automatically be displayed in a list. Alternatively, press the down arrow key on your keyboard without entering a search term in order to display all sales representatives. By clicking on the entry of the sales representative, the ID and the name of the sales representative will be saved in this field. The sales representative is assigned to the type. +
If you use the statistic <<basics/statistics/general-statistics/revenue/revenue-sales-representative#, *Revenue by sales representative*>> to analyse how much revenue the sales representative generated, then you will need to use the event procedure <<basics/automation/event-procedures#configuration, *Assign sales representative to customer*>> to automatically save the sales representative in the contact data. +
*_Important_*: The sales representative selected in the contact data record will not be taken into account for the orders. As such, the order will not appear in the *Revenue by sales representative* statistic. In order for the sales representative to be taken into account for an order, he or she has to be assigned to the order by an event procedure. For further information, refer to the notes about the event procedure <<basics/automation/event-procedures#configuration, *Assign sales representative to order*>>.

|*Feedback*
|Give feedback about the contact for internal use. Select five red stars for the worst and five yellow stars for the best rating.

|*Customer number*
|Enter a customer number for the contact. It is a good idea to plan how you want your contacts to be numbered, e.g. consecutively. Customer numbers are not assigned automatically.

|*Owner*
|Select the owner for the contact. If you do not want to select an owner, select the empty option.

|*Date of birth*
|Enter the date of birth of the contact in the format yyyy-mm-dd or select it from the calendar.

|*Newsletter*
|Displays if the contact receives the newsletter. It is not possible to activate this option manually. In order to exclude the contact from receiving the newsletter, click on *Delete newsletter*.

|*Blocked*
|Select whether or not the contact should be blocked for the specific client (store). +
If the option is activated, the contact will be blocked and can no longer log into the online store. If the option is deactivated, the contact will be able to log into the online store.

2+|Contact options

|*Type*
|Select the type, e.g. email, telephone or website from the drop-down menu.

|*Sub-type*
|Select a sub-type, e.g. work, private or contact person from the drop-down menu.

|*Value*
|Enter the value.
|====

[#200]
== Searching for a contact

In the *Filter* view on the left side, you can search for contacts according to specific criteria. The contacts found will be listed in the *Overview* view. The overview currently displays the following information: ID, name, company, email address, telephone number, number of orders, postcode and country. You can also edit the contact data. For further information, refer to the <<crm/managing-contacts#300, *Editing a contact*>> chapter.

In order to search for specific contacts, enter a search term in the search fields or select the appropriate drop-down menu settings. You can enter multiple search terms into the search fields at one time. This makes your search run quicker and be more accurate.

[IMPORTANT]
.Searching contacts by means of the email address
====
Please note that it is currently possible to search contacts by means of the email address only. You can also search for parts of the email address. The other search options and filter that are listed in table 2 will be made available step by step.
====

[.instruction]
Searching for a contact:

. Go to *CRM » Contacts*.
. In the *Filter* view, enter the search term in the search field or set the filter options in the drop-down menus. Pay attention to the information given in table 2.
. Click on *Search*. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The contact will open.

.Filters for contacts
[cols="a,a"]
|====
|Setting |Explanation

|*Search*
|Click on *Search* without selecting any filter settings. This will display all contacts. Alternatively, limit the search results by using filters and click on *Search*. The contacts found will be listed in the overview.

|*Reset*
|Resets the filter criteria that was entered.

|*ID*
|Each contact automatically receives a consecutive and unique ID. It doesn't matter if the data record was saved manually or automatically. Two contacts never have the same ID. The ID is always a real number. "00521" or "ADF8354" e.g. are invalid.

|*Name*
|Enter the first name and/or surname to search for the contact with this name.

|*Email*
|Enter the email address to search for contacts with this email address.

|*Address*
|Enter the name of the street, the postcode or the town that is saved for the contact.

|*Country*
|Select a country to only display contacts from this country. The country is saved within the contact data.

|*Client (store)*
|Select a client (store) to only display contacts that correspond to this client. The client (store) is saved within the contact data. +
*_Important_*: Variable users can only select those clients that they have a right to access. Variable users are given rights within the <<basics/working-with-plentymarkets/manage-users#90, *Right*>> tab in the *Settings » Basic settings » User » Accounts* menu.
|====

[#300]
== Editing a contact

Search the contact by means of the <<crm/managing-contacts#200, *filter settings*>>. Open the contact by clicking in the line of the contact to edit the contact's data such as the language, class, date of birth, telephone number and email address, for example. You will find explanations of the settings and options in the sections *Contact* and *Contact options* in the <<crm/managing-contacts#100, *Creating a contact*>> chapter.

[.instruction]
Editing a contact:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, *Searching for a contact*>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The contact will open.
. Carry out the changes as desired. Pay attention to the information given in table 1 in the <<crm/managing-contacts#100, *Creating a contact*>> chapter.
. *Save* the settings.

[TIP]
.Display when one or multiple contacts are open
====
If you click on a contact in order to display or edit it, the contact name with ID opens as well as the details of the contacts with ID.

Via the left section, you can access further sub-menus of the contact such as *Addresses*, *New address*, *Orders* and *New order*. By clicking on *Addresses* for example, all addresses that are saved for the contact will be displayed. When more than one sub-menu of the contact is open, a triangle will appear in the field. Click on the triangle to quickly and easily switch between the open sub-menus of the contact.

You can get back to the overview of contacts found via the *Overview* view. From this view, you can open as many further contacts as you like.

When more than one contact is open, a triangle will appear in the *Details* view. Click on the triangle to quickly and easily access contacts that have been opened at least once.
====

[#400]
== Deleting a contact

You can delete individual contacts in the *CRM » Contacts* menu. All addresses that are assigned to the contact will be deleted if they are not linked to an order.

[.instruction]
Deleting a contact:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, *Searching for a contact*>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The contact will open in the detailed view.
. In the left section, click on *Delete contact* or click on *Delete* above the detailed view. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The contact will be deleted and removed from the overview.

[#500]
== Displaying the history

Each data record contains the history of a contact. The history includes e.g. how long the contact has been registered and when he or she has been logged into your online store for the last time and when the last order was generated. This data will be automatically updated and cannot be changed.

[.instruction]
Displaying the history:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, *Searching for a contact*>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The contact will open and the history will be displayed in the right section below the *contact options*.
. Pay attention to the information about the history given in table 4.

.History in the *CRM » Contacts » Open contact* menu
[cols="a,a"]
|====
|Setting |Explanation

|*Registered since*
|Date and time when the contact has first registered.

|*Updated*
|Date and time when the data record of the contact has been updated for the last time.

|*Last login*
|Date and time when the contact was logged into your online store for the last time.

|*Last order*
|Date and time when the last order was made. The order ID will also be displayed. Click on the ID to open the order. If no order has been placed, *No data* is displayed in this field.

|*Account type*
|Account via which the contact has registered. +
*Regular account* = The contact has newly registered in your online store or the data record has been manually created in the back end. +
*Guest account* = The contact has registered and ordered as a guest.
|====

[#600]
== Displaying addresses

From the opened contact, you can display the corresponding addresses in clearly structured info boxes. Besides the ID, company name, first and last name as well as address and country, you can see a tag in the info box that informs about the address type: invoice address or delivery address. +
If multiple addresses are opened, the address type as well as the address ID will also be dipslayed in the drop-down menu of the opened address data record.

[.instruction]
Displaying addresses:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, *Searching for a contact*>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The contact will open.
. In the left section, click on *Addresses*. +
→ All addresses that are saved for the contact will be displayed.
. Click on *Edit* in order to open the detail view of the address. +
→ In the detailed view below the entry fields, you can see next to the address type if the address is a primary address or not.

[#700]
== Adding an address
Add as many addresses as you like to the contact. The fields marked with *** area mandatory fields. Furthermore, you can add address options such as the VAT number or the telephone number of the contact.

[.instruction]
Adding an address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, *Searching for a contact*>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The contact will open.
. In the left section, click on *New address*.
. Carry out the settings in the *New address* section. Pay attention to the information given in table 3.
. In the *Address options* section, select the type from the drop-down menu and enter the value. Pay attention to the information given in table 3. +
→ By clicking on *Add address option*, you can add further address options.
. *Save* the settings. +
→ The address will be added to the overview in the *Addresses* section.

.Adding an address
[cols="a,a"]
|====
|Setting |Explanation

2+|New address

|*Company*
|Enter the company name. This is a mandatory field when there is no entry under *First name* and *Last name*.

|*First name*
|Enter the first name of the contact. This a mandatory field when there is no entry under *Company* and *Last name*.

|*Last name*
|Enter the last name of the contact. This a mandatory field when there is no entry under *Company* and *Last name*.

|*Additional address information*
|If needed, enter additional information, e.g. c/o Mr. John Doe.

|*Street* +
*House number* +
*Postcode* +
*Town*
|Enter the street, house number, postcode and town of the contact. This data will be used for the invoice address, for example. The order of the options *Postcode* and *Town* is reversed for certain countries, e.g. Germany. +
*Postcode* and *Town* are mandatory fields. +
*Street* is a mandatory field when there is no entry under *Additional address information*.

|*Additional address information*
|Enter additional address information if necessary, e.g. apartment 12a.

|*Free*
|This field can be freely used.

|*Country* +
*Region/County*
|Select the values from the drop-down menu.

|*Invoice address* / *Delivery address*
|Activate one or both options in order to determine the address type. +
The new address can either be the invoice address only, the delivery address only or both the invoice address and the delivery address. If both options are activated, two addresses will be created. With regard to the data saved, these two addresses do not differ from each other – except for the ID. +
If one ore both options are activated, you can select for one or both options if the address is the primary address.

|*Primary*
|Activate the option if the new address is the primary invoice address or the primary delivery address. +
It is possible to activate both options if the new address is the primary invoice address as well as the primary delivery address.

2+|Address options

|*Type*
|Select the type, for example the Postnummer or the VAT number from the drop-down menu.

|*Value*
|Enter the value.

|====


[#800]
== Editing the address

You can edit addreses as well as address options at any time. Pay attention to the information given in the <<crm/managing-contacts#600, *Adding an address*>> chapter.

[.instruction]
Editing the address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, *Searching for a contact*>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The contact will open.
. In the left section, click on *Addresses*. +
→ All addresses that are saved for the contact will be displayed.
. Click on *Edit* in the info box of the address that you want to edit. +
→ The detail view of the address will open.
. Carry out the changes as desired. Pay attention to the information given in table 3 in the <<crm/managing-contacts#700, *Adding an address*>> chapter.
. *Save* the settings.

[#900]
== Deleting an address

You can delete the addresses that are saved for the contact. This may be necessary, if the delivery address of the contact is outdated, for example.

[.instruction]
Deleting an address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, *Searching for a contact*>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The contact will open.
. In the left section, click on *Addresses*. +
→ All addresses that are saved for the contact will be displayed. +
. Click on *Delete* in the info box of the address that you want to delete. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The address will be deleted and removed from the overview.

[#1000]
== Displaying orders

Within the open contact, you can access all orders of the contact in the *Orders » Edit orders* menu. When switching to the order menu, it will be searched automatically for orders from contacts with this ID.

[.instruction]
Displaying orders:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, *Searching for a contact*>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The contact will open.
. Click on *Orders* in the left section. +
→ All orders that are saved for the contact will be displayed in the *Orders » Edit orders* menu. +
. Click in the line of the order to display further information about the order.

You can also edit the order. Orders can be edited as long as there has been no document generated for this order. Further information about orders can be found on the <<auftragsabwicklung/auftraege/auftraege-verwalten, *Managing orders*>> page of the manual.

[#1100]
== Creating an order

Within the open contact, you can create a new order for the contact with only one click. If the contact has ordered in your online store, the order will be automatically saved in your plentymarkets system. In case of orders via telephone, for example, you will create the order manually. Proceed as described below.

[.instruction]
Creating an order:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, *Searching for a contact*>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The contact will open.
. Click on *New order* in the left section. +
→ You will directly access the *New order* area in the *Orders » Edit orders* menu. +
. Carry out the settings. Pay attention to the information given on the <<order-processing/orders/managing-sales-orders#, *Managing orders*>> page of the manual.
