= Managing customer data
:lang: en
include::{includedir}/_header.adoc[]
:keywords: customer class, customer type, customer data record, edit customer, search for customer, delete customer, activity index, account receivables, discount system, VAT number
:description: Learn how to create and manage your customer data in plentymarkets.
:position: 50

Go to *CRM » Edit customer* to create <<crm/managing-customer-data#800, customer data records>>. Save your customers' information such as the address details, delivery addresses, bank details and documents, e.g. invoices and notes.

The *System » System settings » CRM* menu allows you, for example, to create <<crm/managing-contacts#15, customer classes>>, <<crm/managing-customer-data#300, customer types>> and <<crm/managing-customer-data#400, properties>>. You can also use this menu to <<crm/managing-customer-data#3100, generate new passwords>> for all your customers. Furthermore, learn how to use the <<crm/managing-customer-data#1600, discount system>> in plentymarkets. Go to *CRM » AR list* in order to retain control over <<crm/managing-customer-data#3600, orders that are still unpaid>>.

[NOTE]
.Exporting, importing and updating customer data
====
Export the data of your customers via the elastic export. Installing the plugins link:https://marketplace.plentymarkets.com/en/plugins/integration/ElasticSync_4750[ElasticSync^] and link:https://marketplace.plentymarkets.com/en/plugins/markets/ElasticExport_4763[Elastic Export^] as well as deploying them in a plugin set is required. Both plugins are available in the link:https://marketplace.plentymarkets.com/en/[plentyMarketplace^].

Create the format for the export in the *Data » FormatDesigner* menu. Create a new export in the *Data » Elastic export* menu. Select the format that you have just created via the FormatDesigner from the drop-down list. Afterwards, export the data to a CSV file. Various filter options are available for the export. You can export, for example, only customers that you have rated with 3 stars or only customers that are assigned to a certain owner.

Import the data of your contacts including address options, contact options and company data via the ElasticSync plugin. Install at least version 2.1 of the plugin. For further information, refer to the link:https://marketplace.plentymarkets.com/en/plugins/integration/ElasticSync_4750[user guide^] of the ElasticSync plugin.
====

[#100]
== Creating a customer class

Use customer classes to categorise your customer base according to specific criteria. For example, you can create a customer class for consumers (B2C) that displays gross prices for the items in your online store. For sellers (B2B), you create another customer class that displays net prices for the items in your online store. Further options are discounts based on the net value of your items, discounts based on the payment method or discount scales for a selected customer class.

Go to *System » System settings » CRM » Customer classes* to create new customer classes. The customer classes that you created in this menu are available in the customer data record. If no customer class is selected, the class with the lowest position number is automatically assigned in the customer data.

[TIP]
.Tip: Create types and classes
====
It is recommended to create a concept for organising your customer base into types and classes before saving customer data. By doing this, you will save time later on. For example, types and classes are automatically assigned when the initial configuration is missing. Decide which types and classes you need, create them accordingly and assign them to the customers.
====

You can set up and individually configure as many customer classes as you like. An ID is automatically assigned to customer classes. This ID is displayed to the left of the customer classes' name in the overview. However, customer classes are not ordered by ID. Instead, the order is set using the option *Position*.

When you create a new customer class, it is displayed in the *Customer classes* tab. Reload the menu after making changes to display the new settings in the overview.

[.instruction]
Creating a customer class:

. Go to *System » System settings » CRM » Customer classes*.
. Click on the *New customer class* tab.
. Carry out the settings. Pay attention to the information given in <<table-create-customer-class>>.
. *Save* the settings.

[[table-create-customer-class]]
.Settings in the *System » System settings » CRM » Customer classes* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Minimum order quantity*
|Enter the minimum order quantity if you want to require customers to order a specific quantity of items or if you want to require them to order a minimum quantity to get a discount.

|*Name*
|Enter a name for the new customer class, e.g. *wholesaler* or *premium customer*.

|*Position*
|If you do not enter a position, the next available position number is assigned automatically. The position is primarily used to sort the customer classes in the menu. It is relevant e.g. in combination with the visibility of item prices in the online store. This can be set under *Display of the prices in the online store*.

|*Payment due date*
|Enter a payment deadline in days for this customer class. If a payment due date is also saved for a customer in the *Customer data* tab, it has priority over the payment due date saved here. The payment due date can also be saved as an optional field on <<order-processing/orders/order-documents#, order documents>> such as <<order-processing/orders/order-documents/generating-invoices#, invoices>>. The invoice's payment due date would be used if no other payment due date was saved in the customer data record or the customer class. Pay attention to the box *Info: Example terms of payment* below <<table-create-customer-data-record>> in the <<crm/managing-customer-data#800, Creating a customer data record>> chapter.

|*Customer ID*
|Specify the customer who is to receive the multi-invoices that are created from <<order-processing/orders/multi-orders#, multi-orders>>. Simply enter the customer ID. Multi-orders are generated for this customer class and the invoice is sent to that customer.

|*Discount type*
|Select a discount type. The number of options that are visible depends on which discount type was selected. If you do no want to offer a discount, select the option *No discount*. Further information and explanations about the discount types in plentymarkets can be found in the <<crm/managing-customer-data#3900, Using the discount system>> chapter.

|*Volume discount*
|Select whether the value entered in the *System » System settings » Item » Sales prices* menu under *Minimum quantity* should be taken into account or not.

|*Permitted payment methods*
|Select which of the payment methods that are available in the online store should be permitted for this customer class. +
All of the available payment methods are selected by default. When you integrate new payment methods, you have to permit them here. This is because new payment methods are not automatically included in this list. +
*_Important_*: Pay attention to which <<fulfilment/preparing-the-shipment#1000, payment methods are blocked in the shipping profiles>> that you want to use for this customer class. Check those settings to make sure that they are compatible with the settings you make here. If you want to permit a payment method for a customer class, you should make sure it is not blocked in the shipping profiles. Make sure that the corresponding customer class is not blocked either.

|*Payment instruction*
|The payment instructions that are saved here are displayed on invoices. For example, you could enter payment information that relates to a specific customer class.

|*Display of the prices in the online store*
|Select whether *Gross* or *net* prices are displayed in the online store. +
*_Important_*: This option only sets how prices are displayed. It does not influence the way prices are calculated for the customer class. This option is particularly important for the customer class with position 1. This customer class is automatically assigned to customers if no customer class was selected in the customer data.
|====

You can link sales prices with customer classes. Go to *System » System settings » Items » Sales prices* and select one of the customer classes that you created under the setting *Class*. Further information can be found in the <<item/managing-items#870, Managing sales prices>> chapter on the <<item/managing-items#, Managing items>> page of the manual.

[#200]
== Searching for customers of a specific customer class

You can also use customer classes to search for specific customers. Use the search filter *Class* in the *CRM » Edit customer* menu to do so.

[.instruction]
Searching for customers of a specific customer class:

. Go to *CRM » Edit customer*.
. In the *Filter* tab, select the customer class in the drop-down list *Class* to display all customers of this customer class.
. Click on *Search*. +
→ All customer data records with the selected customer class are displayed in the *Customers* tab.

[#300]
== Creating a customer type

Customer types are used to classify and differentiate customers. Some customer types are available by default in your plentymarkets system and cannot be deleted. These types are *Customer*, *Sales representative*, *Supplier*, *Partners*, *Manufacturer* and *Interested party*. The customer types that you created are available in the *Filter* tab in the *Type* drop-down list in the *CRM » Edit customer* menu.

The customer type *Customer* is automatically set by default. Customers who were assigned to the customer type *Supplier* are available to select in certain drop-down lists, e.g. in a variation's *Supplier* tab. Create further customer types in the *System » System settings » CRM » Types* menu.

Proceed as described below to create customer types.

[.instruction]
Creating a customer type:

. Go to *System » System settings » CRM » Types*.
. Click on *Add type*.
. Enter a name.
. *Save* the settings.

[.subhead]
Deleting a customer type

Proceed as described below to irreversibly delete a customer type if it is no longer needed. Note that you cannot delete customer types that are already available in your plentymarkets system by default.

[.instruction]
Deleting a customer type:

. Go to *System » System settings » CRM » Types*.
. Click on *Delete*.
. Confirm your decision.

[#400]
== Creating a characteristic

Go to *System » System settings » CRM » Properties* to create properties that you will later use for characterising your customers. There are 2 possibilities for using the properties later: On the one hand, you can ask your customers to provide the necessary information during the order process or customer registration. On the other hand, you can use the characteristics to enter information about the customer yourself.

If you ask your customers to provide this information, specify whether the entry is mandatory or not, i.e. whether customers are required to provide this information. For example, you could ask customers how they heard about your online store during the registration process. Set up this characteristic by selecting the options *Single-line text* or *Multi-line text* as the *Type*. This creates a text field in which customers can enter the relevant information.





Proceed as described below to create a customer property.

[.instruction]
Creating a characteristic:

. Go to *System » System settings » CRM » Properties*.
. Click on the *New characteristic* tab.
. Carry out the settings. Pay attention to the information given in <<table-create-property>>.
. *Save* the settings.

[[table-create-property]]
.Settings in the *System » System settings » CRM » Properties » Tab: New property* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Name*
|Enter a name for the characteristic. This is displayed, e.g. during the order process.

|*Name / Language*
|Once a property has been saved in the default language of your plentymarkets system, you can save the texts in <<crm/managing-customer-data#600, other languages>> as well.

|*Type*
|The type specifies the kind of information your customers have to enter for the characteristic. Select one of the following options: *Number*, *Selection*, *Single-line text*, *Multi-line text*, *Date* or *Customer type*.

|*Selection*
|Only visible if the setting *Selection* was selected under *Type*. You may enter as many characteristic values as you like. +
A drop-down list with different options is created for the characteristic. This drop-down list is displayed in the order process, for example. +
*Name* = Enter a name for the characteristic. +
*Value* = Enter a number between 0 and 50. Use consecutive numbers to list the entries in ascending order. Select the order in which search results should be displayed. +
*Add value* = Add further fields.

|*Customer type*
|Only visible if the setting *Customer type* was selected under *Type*. Multiple selection is allowed here. You can assign multiple customer types to one characteristic. You can choose from the system's default customer types as well as the <<crm/managing-customer-data#300, customer types that you additionally created>>.

|*Position*
|Select the position for the property from the drop-down list. Assign consecutive position numbers to achieve the desired order of characteristics.

|*Mandatory field*
|Activate this option to make sure that the characteristic is a mandatory field. +
If the characteristic is defined as a mandatory field, it is displayed in bold font in the *Characteristics* tab of the customer data and during the order process. This means that the customer data clearly shows which characteristics are displayed as mandatory fields in the online store and that customers can see which characteristic fields are mandatory at a glance.

|*Customer search*
|Only visible if the setting *Selection* was selected under *Type*. Activate in order that the property is available in the customer search in the *CRM » Edit customer » Tab: Filter* menu.

|*Order process*
|Activate this option to make sure that the characteristic is displayed in the order process.

|*Customer registration*
|Activate this option to make sure that the characteristic is displayed in the customer registration.

|*Visibility*
|Select the customer types for which the characteristic should be visible.

|*Client (store)*
|Select one or more clients (stores) that the characteristic should be activated for.
|====

The properties created in this menu are displayed in the *CRM » Edit customer » Open customer » Tab: Properties* menu.

[#500]
=== Editing a characteristic

All characteristics saved within your plentymarkets system are displayed in the *Characteristics* tab. Here you can change the settings described in <<table-create-property>> or delete existing properties from the system if they are no longer needed.

[.instruction]
Editing a characteristic:

. Go to *System » System settings » CRM » Properties*.
. Click on *Search* to show all of the characteristics or select a *customer type* from the drop-down list to only show those characteristics that the customer type is included in.
. Expand the characteristic to edit the settings. Pay attention to the information given in <<table-create-property>>.
. *Save* the settings.

[#600]
=== Creating a characteristic in different languages

Once a characteristic has been saved in your system's default language, you can save the texts in other languages as well. To do so, proceed as follows.

[.instruction]
Creating a characteristic in different languages:

. Go to *System » System settings » CRM » Properties*.
. Expand the characteristic.
. Select the language from the drop-down list *Name*.
. Enter the name in the selected language.
. *Save* the settings.

If you select *Selection* as type, a further drop-down list and a further column are displayed for the values. Enter the values in the relevant language.

[#700]
=== Deleting a characteristic

Proceed as described below to irreversibly delete a characteristic if it is no longer needed.

[.instruction]
Deleting a characteristic:

. Go to *System » System settings » CRM » Properties*.
. Click on *Delete* in the line of the characteristic.
. Confirm your decision.

[#800]
== Creating a customer data record

Proceed as described below to create a new customer data record. You can also create a new customer data record, for example, while taking an order over the phone or while filling out a written order. It is also possible to save the contact details of interested parties here.

Learn more about creating customer data records in the following video tutorial:

video::145369998[vimeo]

[.instruction]
Creating a customer data record:

. Go to *CRM » Edit customer*.
. Click on *New*.
. Carry out the settings. Pay attention to the information given in <<table-create-customer-data-record>>.
. *Save* the settings.

[[table-create-customer-data-record]]
.Creating a customer data record
[cols="1,3"]
|====
|Setting |Explanation

|*ID*
|When creating a customer data record, the system automatically assigns a customer ID. This ID cannot be changed.

|*Company*
|Enter the company name. +
This is a mandatory field when there is no entry under *First name* and *Last name*.

|*Form of address*
|*Empty option* = Company +
*Ms.* = Female form of address +
*Mr.* = Male form of address

|*Title*
|Enter the customer's title.

|*First name*
|Enter the customer's first name. +
This a mandatory field when there is no entry under *Company* and *Last name*.

|*Last name*
|Enter the last name of the contact. +
This is a mandatory field when there is no entry under *Company* and *First name*.

|*Additional address information*
|If required, Enter the additional address information. It is e.g. used for the invoice address. +
This is a mandatory field when there is no entry under *Street*.

|*Street, +
Postcode*, +
*Town*
|Enter the street, house number, postcode and town of the customer. This data is used for the invoice address, for example. The order of the options *Town* and *Postcode* is reversed for certain countries, e.g. Germany. +
*Postcode* and *Town* are mandatory fields. *Street* is a mandatory field when there is no entry under *Additional address information*.

|*Region/County*
|Select the region from the drop-down list. +
Depending on the selected country, you are able to select e.g. states or counties. +
The drop-down list is deactivated if no further options are available for the country. +
This option is also displayed with the delivery address during the checkout process and in the My account area. The customer is required to make a selection in some cases, e.g. for PayPal in the USA.

|*Country*
|Select the country from the drop-down list. This country is e.g. used for the invoice address. The standard setting is based on which country you selected for the option *Default location* in the *System » System settings » Client » Select client » Settings* menu.

|*Contact*
|Enter your contact person, e.g. if your customer is a company.

|*Email*
|Enter the customer's email address. The email address is important for automatically sending email templates such as order confirmations, invoices and dunning letters. +
Check the <<crm/sending-emails#100, access data>> if the email was not sent correctly. Go to <<basics/data-exchange/api-log#, Data » API log>> to see the error messages.

|*Telephone*
|Enter the customer's telephone number.

|*Fax*
|Enter the customer's fax number.

|*Mobile*
|Enter the customer's mobile phone number.

|*Client*
|Select the client from the drop-down list in order to assign the contact to this client. +
Only those clients are displayed that have a name entered for them in the store's *basic settings* under *System » System settings » Client*.

|*Language*
|Select the language for the customer. For example, invoice documents are sent in this language if you created a template in this language.

|*Feedback*
|Give feedback about the customer for internal use. Select 5 red stars for the worst and 5 yellow stars for the best rating.

|*Owner*
|Select the owner for the customer. If you do not want to select an owner, select the empty option. +
Assigning an owner makes it possible for each user to search for the customers that he or she is owner of.

|*Type*
|Select a customer type. The types *Customer*, *Sales representative*, *Supplier*, *Partner*, *Manufacturer* and *Interested party* can be selected by default. Create further types in the <<crm/managing-customer-data#300, System » System settings » CRM » Types>> menu.

|*Postcode area sales rep*
|Only visible if the type *Sales representative* was selected. Enter the sales representative's postcode area. Use commas to separate multiple areas, e.g.: 33,34. The more numbers per postcode area, the more this area is limited. It is necessary to enter the sales representative's postcode area if you want to use the statistic <<basics/statistics#20, Revenue by sales representative>> to measure how much revenue the representative generated. For further information, refer to the *Sales rep* option.

|*Country of postcode area rep*
|Only visible if the type *Sales representative* was selected. The drop-down list is only activated if a postcode area was entered under *Postcode area sales rep*. +
Select a country that the postcode area refers to. The system country is selected by default. +
*_Tip_*: If a sales representative is working in multiple countries, create one customer data record per country.

|*Delivery time*
|Only visible if the type *Supplier* was selected. Enter the delivery time in days.

|*MOV*
|Only visible if the type *Supplier* was selected. MOV stands for minimum order value. Enter the minimum order value in the currency of the system.

|*Class*
|Select the customer class. Customer classes serve as an internal distinction between customers and you determine which discount is granted for this customer class, for example. Go to <<crm/managing-customer-data#100, System » System settings » CRM » Customer classes>> to create further classes. If you want to offer different prices to end customers and sellers in the online store, this can be done with the *Display of the prices in the online store* option in the customer classes configuration. For end customers (B2C), the gross prices are displayed in the online store. For sellers (B2B), the net prices are displayed in the online store. +
Empty option = No assignment to a customer class +
*_Important_*: If there is no assignment to a customer class, the customer is automatically assigned to the customer class with the lowest position. As the price display in the online store is configured for each customer class, check this option for the customer class with the position 1 so that the correct price is displayed during automatic assignments.

|*Sales rep*
|This option refers to sales representatives. With this setting, a sales representative is assigned to a customer type. Enter the sales representative's customer ID or enter the first 3 letters of the sales representative's name. Matching representatives are automatically displayed in a list. Alternatively, press the down arrow key on your keyboard without entering a search term in order to display all sales representatives. By clicking on the entry of the sales representative, the customer ID and the name of the sales representative are saved in this field. The sales representative is assigned to the type. +
If you use the statistic <<basics/statistics#20, Revenue by sales representative>> to analyse how much revenue the sales representative generated, you need to use the event procedure <<basics/automation/event-procedures#_procedure_type_customer, Assign sales representative to customer>> to automatically save the sales representative in the contact data. +
*_Important_*: The sales representative selected in the customer data record is not taken into account for the orders. As such, the order is not taken into account in the *Revenue by sales representative* statistic. In order for the sales representative to be taken into account for an order, he or she has to be assigned to the order by an event procedure. For further information, refer to the notes about the event procedure <<basics/automation/event-procedures#_procedure_type_orders, Assign sales representative to order>>.

|*Group forum*
|Select a user group for the forum. User groups are created in the <<omni-channel/online-store/setting-up-clients/modules#_creating_forums, System » System settings » Client » Select client » Modules » Forum>> menu.

|*Date of birth*
|Enter the customer's date of birth in the same format as the example provided or select it from the calendar.

|*Age rating*
|This setting is used to place an age restriction on items that need to be designated in this way. The customer is either allowed to buy an item or not depending on which age rating is set.

|*Newsletter*
|Select whether the customer should be taken into consideration when sending a newsletter. +
If the option is activated, the customer receives newsletters. If the option is deactivated, the customer does not receive any newsletters.

|*Blocked*
|Select whether or not the contact should be blocked for the specific client (store). +
If the option is activated, the contact is blocked and can no longer log into the online store. If the option is deactivated, the customer is able to log into the online store.

|*Credit rating*
|Only visible after the customer data record has been saved. Click on *Recheck* to check the customer's credit rating. The date of the last credit rating check is displayed here.

|*Customer No.*
|Enter a customer number for the customer. It is a good idea to plan how you want your customers to be numbered, e.g. consecutively. Customer numbers are not assigned automatically.

|*VAT number*
|Enter the customer's VAT number. The VAT number needs to be specified if you are sending goods to a commercial purchaser in another country within the EU (intra-community delivery) and you want net totals to be calculated for the order. After having entered the VAT number, go to <<order-processing/orders/accounting#, System » System settings » Client » Select client » Locations » Select location » Accounting>> and select *Net invoice* for the option *VAT number*. This causes invoices to be issued without VAT for customers who have a VAT number saved in the customer data. +
*_Important_*: The net setting does not go into effect if you saved tax rates for the customer's country of delivery or if the delivery threshold is exceeded.

|*Payment due date*
|Enter the number of days when the payment is due for the customer. This payment due date has priority over the payment due date saved for the <<crm/managing-customer-data#100, customer class>>. The payment due date can also be saved as an optional field on <<order-processing/orders/order-documents#130, order documents>> such as <<order-processing/orders/order-documents/generating-invoices#, invoices>>. The invoice's payment due date would be used if no other payment due date was saved in the customer data record or the customer class. Pay attention to the box *Info: example terms of payment* below the table. +
*_Important:_* The payment due date in the customer data record can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *System » System settings » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Value date*
|Enter the time period (starting when the invoice is created) when you wish for an additional time period before the *payment due* time period begins. Pay attention to the box *Info: example terms of payment* below the table. +
*_Important:_* The value date in the customer data record can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *System » System settings » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Early payment discount (days)*
|Enter the number of days (starting when the invoice is created) in which the customer can pay the pending amounts at a discounted price. Pay attention to the box *Info: example terms of payment* below the table. +
*_Important:_* The early payment discount in the customer data record can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *System » System settings » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Early payment discount (%)*
|Enter the value in percent that the customer may subtract if he or she makes the payment within the time period *Early payment discount (days)*. Pay attention to the box *Info: example terms of payment* below the table. +
*_Important:_* The early payment discount in the customer data record can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *System » System settings » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Deb. account*|Enter an additional, separate customer number. Generally, this number corresponds to the customer number or the debtor number in your financial accounting. It can be helpful to you or your tax accountant when further processing your receipts. This field can also be filled in automatically, if required. +
For further information about the debtor account, refer to the <<order-processing/orders/accounting#750, Accounting>> page of the manual.

|*Archive No.*
|Enter an archive number, e.g. if there is an archive of older customer data records.

|*Debit / Invoice*
|Permit a payment method for this customer, even if this method is not used globally. +
*Do not permit* = the customer cannot pay using this payment method. +
*Permit* = the customer can pay using this payment method, even if you do not offer this method globally. +
*_Example_*: If you want to allow one of your regular customers to buy items on invoice. +
Necessary settings: Go to *System » System settings » Orders » Payment » Payment methods* to activate the payment method. This makes it possible to select the payment method in an order. +
Make sure that no countries of delivery were saved in the settings of the payment method. Otherwise, the payment method would be available to all customers in the online store, which is not desired in this case. +
The second requirement is that the payment method *Invoice* or *Debit* has to be available in at least one shipping profile, i.e. the payment method may not be blocked. +
The third requirement is that this shipping profile is activated for items. +
Check the requirements that are listed here and activate the payment method. This allows the customer to use the payment method.

|*Personal identity number*
|Scandinavian end customers need the personal identity number for Scandinavian payment providers (e.g. Klarna). Customers can enter their personal identity number during the checkout process in the online store as well as in the my account area. Go to *CMS » Web design » Order process » Checkout* to configure how the personal identity number should be queried during the checkout process. Customise the settings in the areas <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-order-process-checkout, Customer registration>> and *Invoice address*. Go to *CMS » Web design » My account* and expand the <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design-my-account, Personal data>> area to configure how the personal identity number should be queried in the my account area. There you can specify whether the personal identity number should be a *Mandatory field*.

|*eBay name*
|Enter the customer's eBay name.

|*DHL-PostNr.*
|Enter the customer's DHL PostNumber. Customers receive their PostNumber from DHL if they are using specific services such as package notification.
|====

[TIP]
.Info: example terms of payment
====
You can use the options *Value date*, *Payment due*, *Early payment discount (days)* and *Early payment discount (%)* to set up the following payment conditions:

60 days *value date*, 30 days *net* (payment due), *10* days with a *2* % *early payment discount*

Explanation: The customer receives a 2% discount if he or she pays within 10 days. The payment is late after a total of 91 days. When incoming payments are imported and assigned, they are automatically checked internally to see whether the customer's early payment discount is valid. If the early payment discount time period has expired, the order receives the status *Partial payment received*. The terms of payment listed above are automatically applied to the order and e.g. to the <<order-processing/orders/order-documents/generating-invoices#, invoice>> and can be changed within the order as well. When the invoice is printed, these terms are combined into valid payment conditions for this order. The value date and payment due date are added together to create one date when the payment is due. Despite the value date and payment due date being added together, the following is displayed on an invoice:Payment conditions: +
Payment conditions Value date in 60 days, 2% early payment discount if paid within 10 days. Within 30 days due net. If a value for *Value date* is saved for a customer, this value is used for the document. Otherwise, the value saved under *Payment due* or the value from the customer class is used. The last possibility is to use the number of days entered for the *Payment due* option for the document. These are set up in the <<order-processing/orders/order-documents#130, Optional elements in the stock unit table>> section. Important: These options are only applied to the total gross value of an invoice.
====

[#1100]
== Searching for customers

In the *Filter* tab, you can search for customers according to specific criteria. The customer data that was found is displayed in the *Customers* tab. You can edit the customer data. You are provided with extensive settings for doing so as well as links to important menus such as <<crm/managing-customer-data#2000, Orders>>, <<crm/managing-customer-data#2200, Tickets>>, <<crm/managing-customer-data#2400, Statistics>> etc.

In order to search for specific customers, enter a search term in the search fields or select the appropriate drop-down list settings. You can enter multiple search terms into the search fields at one time. This makes your search run quicker and be more accurate. For example, you could enter the name of a company and a postcode if you are looking for all of the customers who are associated with a particular branch of a company.

You can use the filter settings to define exactly which customer or customer group should be displayed. For example, you could only list customers who are assigned to a specific customer class and have a specific owner. Or you could leave the default settings as they are and search for all customers. If several options are listed in a drop-down list, *ALL* is selected by default.

[.instruction]
Searching for customers:

. Go to *CRM » Edit customer*.
. In the *Filter* tab, enter the search term in the search field or set the filter options in the drop-down lists. Pay attention to the information given in <<table-filter-customer-search>>.
. Click on *Search*. +
→ The customers that correspond to the search criteria entered are listed.

[[table-filter-customer-search]]
.Filters for the customer search
[cols="1,3"]
|====
|Setting |Explanation

|*Search*
|Click on *Search* without selecting any filter settings. This displays all customer data records. Alternatively, limit the search results by using filters and click on *Search*. The customer data that was found is displayed in the *Customers* tab.

|*Reset*
|Resets the filter criteria that was entered.

|*ID*
|Each customer data record automatically receives a consecutive and unique customer ID. It doesn't matter if the data record was saved manually or automatically. 2 customers never have the same ID. The customer ID is always a real number. "00521" or "ADF8354" e.g. are invalid.

|*Customer data*
|The following parameters can be searched for in this field: *First name*, *Last name*, *Company*, *Contact person*, *eBay name*, *Additional name*, *Street*, *Postcode*, *Town*, *Email address*, *Customer number*, *External customer ID*, *Search tags*, *PostIdent*. It is also possible to only search for parts of the email address in this field.

|*Name*
|Enter the first name and/or last name to search for the customer with this name.

|*Email address*
|Enter the entire email address to search for customers with this email address. Parts of the email address can be searched for in the *Customer data* field.

|*Street*
|Enter the name of the street that is saved in the customer data record.

|*Postcode*
|Enter the postcode to find customers or groups of customers that are from a specific town.

|*Telephone*
|Enter a telephone number to search for customers with this number.

|*Note*
|Search for key words within a note in the customer data records.

|*Type*
|Select the <<crm/managing-customer-data#300, customer type>> that you want to search for. +
You have to select a type in order to search by <<crm/managing-customer-data#400, characteristics>>.

|*Class*
|Select the <<crm/managing-customer-data#100, customer class>> that you want to search for.

|*Owner*
|Select an owner to search for the customers that this user is responsible for. The owner must be saved within the customer data. +
*_Important_*: You can only select users from the drop-down list who are activated for the *Customer* option in the *Owner* tab of their user account.

|*Country*
|Select a country to only display customers from this country. The country is saved within the customer data.

|*Client (store)*
|Select a client (store) to only display customers that correspond to this client. The client is saved within the customer data record. +
*_Important_*: Variable users can only select those clients that they have a right to access. Variable users are given rights within the <<basics/admin-tasks/manage-users#90, Right>> tab in the *System » System settings » Settings » User » Accounts* menu.

|*Feedback*
|Select a feedback to only search for customers who have received this feedback.

|*Scheduled order*
|Select one of the following options: +
*Active and available* +
*Not available* +
*Ended* +
For further information about scheduled orders, refer to the <<order-processing/orders/scheduler#, Scheduled orders>> page of the manual.

|*IBAN*
|Select one of the following options: +
*Available* = Only searches for customers who have an IBAN saved in their bank details. +
*Not available* = Only searches for customers who have no IBAN saved in their bank details.

|*Direct debit mandate*
|Select *Yes* or *No*. +
*Yes* = Searches only for customers who have given you a SEPA direct debit mandate. +
*No* = Searches only for customers who have not given you a SEPA direct debit mandate. +
For further information, refer to the <<order-processing/payment/managing-bank-details#200, Setting up SEPA direct debit mandate>> chapter on the <<order-processing/payment/managing-bank-details#, Managing bank details>> page of the manual.
|====

[#900]
== Viewing the activity index

The *Activity index* area in the *CRM » Edit customer » Open customer* menu displays e.g. how long the person has been your customer and when he or she has been logged into your online store for the last time. This data is automatically updated and cannot be changed. <<table-activity-index-customer-data-record>> explains the activity index.

[[table-activity-index-customer-data-record]]
.Activity index in the *CRM » Edit customer » Open customer » Tab: Customer data* menu[cols="1,3"]
|====
|Setting |Explanation

|*Customer since*
|Date and time when the customer has first registered.

|*Account type*
|Account via which the customer has registered. Either *regular account* or *guest account*. Regular account means that the customer has newly registered in your online store. Guest account means that the customer has ordered as a guest without registering in your online store. +
*_Important:_* If you use Ceres, you can prevent that customer data records are created when guests place an order. To do so, go to *System » System settings » CRM » Settings* and select the option *Do not create contacts* from the drop-down list *Guest orders*. The option *Create contacts* is selected by default.

|*Updated*
|Date and time when the customer data record has been updated for the last time.

|*Last login*
|Date and time when the contact was logged into your online store for the last time.

|*Last order*
|Date and time when the last order was made. The order ID is also displayed. Click on the ID to open the order. If no order has been placed, *No data* is displayed in this field.
|====

[#1000]
== Carrying out the group function

You can use group functions to trigger specific procedures for several customers. For example, this can be sending an email template or printing address labels.

[.instruction]
Carrying out the group function:

. Go to *CRM » Edit customer*.
. In the *Filter* tab, enter the search term in the search field or set the filter options in the drop-down lists. Pay attention to the information given in <<table-filter-customer-search>> in the <<crm/managing-customer-data#1100, Searching for customers>>.
. Click on *Search*.
. Activate the customers which you want to use the group function for.
. Click on *Group function*.
. Select one or several group functions. Pay attention to the information given in <<table-group-function-customer-data-record>>.
. Click on *Apply* to apply the function(s) to the selected customers.

[[table-group-function-customer-data-record]]
.Group function in the *CRM » Edit customer* menu
[cols="1,3"]
|====
|Group function |Explanation

|*Print address labels*
|Prints the label that is selected from the drop-down list for all selected customers.

|*Send email template*
|Sends the template that is selected from the drop-down list to all selected customers.

|*Newsletter*
|The selected customer's email address is copied to the email folder that is chosen under *Category*. The email address is listed under *CRM » Newsletter* afterwards.

|*Payment due date*
|Saves the entered payment due date in the customer data record of all selected customers.
|====

[#1200]
== Accessing the customer data

In plentymarkets, you have the possibility to search for customers and e.g. directly create a new order for the customer. Go to *Customers » Customer data* or click on the quick access button *Customer data* in the header of the plentymarkets admin area. You can also create a new customer data record.





[.instruction]
Accessing the customer data:

. Go to *CRM » Customer data* or click on *Customer data* in the header of the plentymarkets admin area.
. Enter at least 3 letters or numbers of the search term such as the customer ID, name, company name, contact person or email address into the entry field. +
→ The customers are displayed in a list.
. By clicking on the customer, his or her customer data is opened in the *Overview* tab.

[.subhead]
Accessing the customer data of all customers

Furthermore, you can display all customers. To do so, proceed as follows.

[.instruction]
Accessing the customer data of all customers:

. Go to *CRM » Customer data* or click on *Customer data* in the header of the plentymarkets admin area.
. Click on the search field.
. Press the down arrow key on your keyboard without entering a search term. +
→ The customers are displayed in a list.

Click on *New customer* to create a new customer data record.

If you click on a customer in the list, the tabs for editing the customer data record opens. The button *New order* is also displayed in the title line next to *New customer*. Click on *New order* to create a new order for the customer. You can also use the function *New order* in the *CRM » Edit customer » Open customer » Tab: Customer data* menu.

The tabs also include all of the remaining settings for the <<crm/managing-customer-data#800, customer data record>>. You can edit these settings within the tabs.

[#1300]
== Editing a customer data record

With the <<crm/managing-customer-data#1100, customer search>>, you can quickly and easily find e.g. the address, telephone number, email address and further customer information. Use the <<crm/managing-customer-data#1100, filter settings>> to search for the customer(s). Click on the customer in the overview to open and edit the customer data record.

Learn more about editing customer data records in the following video tutorial:

video::145370111[vimeo]

[.instruction]
Editing a customer data record:

. Go to *CRM » Edit customer*.
. In the *Filter* tab, enter the search term in the search field or set the filter options in the drop-down lists. Pay attention to the information given in <<table-filter-customer-search>> in the <<crm/managing-customer-data#1100, Searching for customers>>.
. Click on *Search*.
. Click in the line of the contact. +
→ The *Customer data* tab opens.
. Click on the tab in which you want to carry out settings or make changes.
. Make the changes or carry out the settings as desired. +
→ Pay attention to the sections below.
. *Save* the settings.

Which settings you may carry out in the individual tabs of the customer data record is described in the following sub-chapters.

[#1400]
=== Displaying the customer data record

You can see a customer's basic data, such as address, telephone number and email address in the *Customer data* tab. Moreover, you can see all of the customer's activities. For example, you can see how long this person has been your customer.

<<table-toolbar-customer-data-record>> explains the toolbar in the *Customer data* tab. You find explanations of the settings and options in this tab in the <<crm/managing-customer-data#800, Creating a customer data record>> chapter.

[[table-toolbar-customer-data-record]]
.Toolbar in the *Customer data tab*
[cols="1,3"]
|====
|Setting |Explanation

|*Save*
|Saves the changes.

|*ID*
|ID of the customer The system automatically assigns the customer ID. This ID cannot be changed.

|*New order*
|Creates a new order for the customer.

|*Multi-order*
|Creates a new multi-order for the customer. The *Multi-order* function makes it possible for you to take all of the unpaid orders that belong to a customer and then compile them into one multi-order. For further information about multi-orders, refer to the <<order-processing/orders/multi-orders#, Multi-orders>> page of the manual.

|*New scheduler*
|Creates a new <<order-processing/orders/scheduler#, Scheduled order>> for the customer.

|*vCard*
|Exports the customer data as an electronic business card. The data is exported in CSV format.

|*New password*
|Sends the customer a new password.

|*Unblock login*
|Once an incorrect password is entered several times in succession, the login is blocked for the customer for a certain time. Use this button to unblock the login for the customer.
|====

[#1500]
=== Entering a property

The *Properties* tab lists the properties that were previously created under <<crm/managing-customer-data#400, System » System settings » Customers » Properties>>. Use these properties to save important information about the customer. Alternatively, use the properties as freely configurable text fields that are displayed in the customer registration or order process (depending on which setting was selected).

[.instruction]
Entering a property:

. Go to *CRM » Edit customer*.
. Search for the customer by using the <<crm/managing-customer-data#1100, filter settings>>.
. Open the customer.
. Open the *Properties* tab.
. Carry out the settings for the properties of the customer.
. *Save* the settings.

[#1600]
=== Saving a note

In the *Notes* tab, you can save notes about the customer. Notes are only visible in your plentymarkets back end. This means that customers cannot see the saved notes in your online store.

[.instruction]
Saving a note:

. Go to *CRM » Edit customer*.
. Search for the customer by using the <<crm/managing-customer-data#1100, filter settings>>.
. Open the customer.
. Click on the *Notes* tab.
. Enter a note. +
→ If needed, use the functions in the toolbar to format the note.
. *Save* the settings.

If you no longer need the information that you saved in the note, delete the note by clicking on *Delete*.

[#1700]
=== Uploading customer documents

Use the *CRM » Contacts* menu to upload documents. You can upload the data formats JPEG, PNG, GIF, TIFF, PDF, DOC, ODC, OTH, XLS, XML, HTML, HTM, CSS, ZIP and GZIP.

[.instruction]
Uploading customer documents:

. Go to *CRM » Contacts*.
. Search for the contact by using the <<crm/managing-customer-data#1100, filter settings>>.
. Open the contact.
. Open the *Documents* tab.
. Click on *Upload files*.
. Select the documents.
. Click on *Open* to upload the file or add the documents to the tab with the drag and drop function.

Use the checkboxes on top of the list of uploaded documents to select one or several documents. This way, you can download or delete several documents at once. +

[NOTE]
.Creating a folder
====
Create folders in the *Documents* view if you have already uploaded or plan to upload a lot of files about your contact. This allows to group the documents and have a better overview.
====

[#1800]
=== Displaying customer revenues

The *Account* tab lists the revenues of your customers. In the top line, you see the total of the client's invoices, the amount granted to your customer in form of credit notes and the difference between the 2 amounts. +
Orders and credit notes are listed as processes in the table. The *Paid* and *Outstanding* columns are especially helpful. If a payment for an order is listed in the *Outstanding* column, the customer still has to pay the amount. As soon as this is done, the amount is listed under *Paid*. If a payment for a credit note is listed in the *Outstanding* column, you still have to pay this amount to the customer. As soon as this is done, the amount is listed under *Paid*.

[.instruction]
Displaying customer revenues:

. Go to *CRM » Edit customer*.
. Search for the customer by using the <<crm/managing-customer-data#1100, filter settings>>.
. Open the customer.
. Click on the *Account* tab.
. Pay attention to the information given in <<table-show-customer-revenues>>.

[[table-show-customer-revenues]]
.Settings in the *CRM » Edit customer » Open customer » Tab: Account* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Balance*
|Shows the customer's account balance. +
*+* = total of the customer's outstanding payments +
* - = total of payments that still have to be paid to the customer if the customer has paid too much or if a credit note still has to be paid out. +
* 0.0* = No outstanding amounts

|*Invoices*
|Total invoice amounts of all orders and the number of invoices in parentheses

|*Credit notes*
|Total of all credit notes and the number of credit notes in parentheses

|*Delta*
|Difference in percent between the paid credit notes and the total invoice amount paid by the customer. 0 % means that no credit note has been paid out to the customer yet. 100 % means that every amount paid by the customer has been paid back in form of credit notes.

|*Date*
|Date when the order was created

|*Order ID*
|ID of the order. Click on the ID to open the detailed view of the order. Credit note IDs are indented and displayed under the order.

|*Event*
|Type of order, either order or credit note

|*Document*
|Document number, e.g. invoice number. Click on the number to open the document.

|*Value*
|Invoice total of the order

|*Paid*
|Amount already paid

|*Payment method*
|Payment method for the order

|*Outstanding*
|Remaining amount that is due before the order is completely paid for.

|*Status*
|Status of the order. Click on the status to open the editing window *Order status* and change the status, if required.
|====

[.subhead]
Filtering account data

Use filters to display the revenues of your customers.

[.instruction]
Filtering account data:

. Go to *CRM » Edit customer*.
. Search for the customer by using the <<crm/managing-customer-data#1100, filter settings>>.
. Open the customer.
. Click on the *Account* tab.
. Carry out the filter settings in the *Filter* tab. Pay attention to the information given in <<table-filter-account-data>>.
. Click on *Search*.

[[table-filter-account-data]]
.Filter settings in the *CRM » Edit customer » Open customer » Tab: Account* menu[cols="1,3"]
|====
|Setting |Explanation

|*Search*
|Perform a search. The account data found is listed in the *Account* tab.

|*Reset*
|Resets the filter criteria that was entered.

|*Period*
|Select one of the following settings from the drop-down list: *ALL*, *This year*, *Last year*, *This month*, *Last month* or *Last 3 months*.

|*Outstanding*
|Select *ALLE*, *Yes* or *No*. +
*Yes* = Only outstanding amounts are displayed. +
*No* = Only paid amounts are displayed. +
*ALL* = Outstanding and paid amount are displayed.

|*Relational operator / Status*
|Select the operator and an order status.

|*Invoice No.*
|Enter the invoice number.

|*Order ID*
|Enter the order ID.
|====

[#1900]
=== Entering delivery addresses

In the *Delivery addresses* tab, you enter the delivery addresses of your customer. You can save several different delivery addresses and then assign the delivery addresses individually to each order.

[.instruction]
Entering delivery addresses:

. Go to *CRM » Edit customer*.
. Search for the customer by using the <<crm/managing-customer-data#1100, filter settings>>.
. Open the customer.
. Click on the *Delivery addresses* tab.
. Click on *Create delivery address*.
. Expand the area *Create delivery address*.
. Carry out the settings. Pay attention to the information given in <<table-delivery-address>>.
. *Save* the settings.

[[table-delivery-address]]
.Settings in the *CRM » Edit customer » Open customer » Tab: Delivery addresses* menu[cols="1,3"]
|====
|Setting |Explanation

2+|Address

|*Company (name 1)*
|Enter the company name, if available.

|*Form of address*
|Select the form of address from the drop-down list, if required.

|*First name (name 2)*
|Enter the first name.

|*Last name (name 3)*
|Enter the last name.

|*Additional (name 4)*
|Enter additional information, e.g. c/o Mr. John Doe, if required.

|*Street (address 1)*
|Enter the street, Packstation or post office.

|*House number (address 2)*
|Enter the house number or the ID of the Packstation.

|*Additional (address 3)*
|Enter additional address information, e.g. apartment 12a, if required. +
Customers can also enter this information themselves during the order process or in the My account area. +
*_Note_*: Some shipping service providers do not process this field. This means that the additional information is not displayed on the label. This can also result in undeliverable shipment. Additional address information is not transmitted to the following shipping service providers at the moment: +
DHL Freight +
DHL Supply Chain +
Swiss Post +
Inform customers of this, e.g. by saving a note in the areas mentioned or by using JavaScript to hide or display the field in certain situations.

|*Free (address 4)*
|This field can be freely used.

|*Postcode*
|Enter the postcode.

|*Town*
|Enter the town.

|*Country*
|Select the country from the drop-down list.

|*Region/County*
|Select the region from the drop-down list. +
Depending on the selected country, you are able to select e.g. states or counties. +
The drop-down list is activated if no further options are available for the country. This option is also displayed with the delivery address during the checkout process and in the My account area. The customer is required to make a selection in some cases, e.g. for PayPal in the USA.

2+|Address options

|*VAT number*
|Enter the valued added tax identification number, if available.

|*External address ID*
|Enter the external address ID, if available.

|*Entry certificate (Gelangensbestätigung)*
|This option relates to German businesses. It is relevant when orders are placed by customers in EU countries other than Germany but are sent to German delivery addresses. If a check mark is placed, such orders are treated like deliveries to other foreign countries within the EU. This option determines how invoices are generated for orders that were placed from other countries within the EU and have a delivery address within Germany. If the option is activated, the invoices are generated according to the settings *VAT number* and *Export shipping* that are saved in the <<order-processing/orders/accounting#, System» Client » Select client » Locations » Select location » Accounting>> menu. If the option is deactivated, these orders receive gross invoices. +
If an entry certificate is required for an address, create a delivery address and activate the option. +
*_Important_*: Do not deactivate the option if an entry certificate is no longer desired for future orders. Rather, create an additional delivery address where the option is not activated. Otherwise earlier orders with this delivery address are calculated incorrectly.

|*Telephone*
|Enter the telephone number.

|*Email*
|Enter the email address.

|*PostNummer*
|Enter the customer's DHL PostNumber.

|*Personal identity number*
|Enter the personal identity number. Scandinavian end customers need the personal identity number for Scandinavian payment providers (e.g. Klarna).

|*Age rating*
|Select the age rating from the drop-down list.
|====

[#2000]
=== Displaying orders

In the *Orders* tab, you can list and edit all of the orders belonging to a customer or you can create new orders. The functions are the same as those in the *Order* menu. For further information about editing orders, refer to the <<order-processing/orders/managing-orders#changing-order, Changing an order>> page of the manual.

[#2100]
=== Displaying subscriptions

The customer's subscriptions are displayed in the *Scheduler* tab. Moreover, you can create new scheduled orders here. The menu is only visible in your plentymarkets system if you booked this module. Go to *Start » Service Centre » Tab: Contract* to book the module.

For further information, refer to the <<order-processing/orders/scheduler#, Scheduler>> page of the manual. The filter options are also described there. You can use the filter options both in the *CRM » Edit customer » Open customer » Tab: Scheduler* menu and in the *Orders » Scheduler » Scheduled orders* menu.

[#2200]
=== Displaying tickets

The customer's tickets are displayed in the *Tickets* tab. You can edit tickets in this tab and add new tickets, for example. For further information about the ticket system, refer to the <<crm/using-the-ticket-system#, Using the ticket system>> page of the manual.

[#2300]
=== Displaying events

In the *Events* tab, you can save various events that relate to the customer. For example, the event could be a call or an email. You can enter a duration, select information about the process and enter a comment about the event into the text field. This comment is displayed in the *Info* column of the overview afterwards. Activate the option *Bill* if this is an event that the customer needs to pay for.

[#2400]
=== Creating a statistic

Create customer-specific statistics in the *Statistics* tab. This allows you to analyse data related to the customer and display this data as a statistic. For example, you could create a statistic that shows the customer's total revenue development during a particular time period. You can also edit existing statistics in this tab. For further information, refer to the <<basics/statistics#100, Customer statistics>> page of the manual.

[.instruction]
Creating a statistic:

. Go to *CRM » Edit customer*.
. Search for the customer by using the <<crm/managing-customer-data#1100, filter settings>>.
. Open the customer.
. Open the *Statistics* tab.
. Click on *New sheet*.
. Enter a name.
. *Save* the settings. +
→ A tab with the name that you have just entered is displayed.
. Click on *Add*. +
→ The *New statistic* window opens.
. Select the type of statistic from the drop-down list.
. *Save* the settings. +
→ The data is loaded and displayed.

Depending on which type of statistic you selected, you find further information in the following chapters of the <<basics/statistics#, Statistics>> page of the manual:

* <<basics/statistics#20, Total revenue development>>* <<basics/statistics#100, Revenue by category>>* <<basics/statistcs#100, Revenue by order referrer>>

For further information about how to edit statistics, for example, refer to the <<basics/statistics#, Statistics>> page of the manual.

[#2500]
=== Displaying and editing settings

In the *Settings* tab, you save the customer's bank details, password, login URL, cost units and commissions. Which settings you may carry out in the individual tabs *Bank details*, *Password*, *Login URL*, *Cost units* and *Commissions* is described in the following sub-chapters.

[#2600]
==== Maintaining bank details

You can save the customer's bank details in the *Bank details* tab of a customer's data record. You can also delete the bank details if you no longer need them. Bank details are needed, e.g. for the payment method *Debit*. You also have the possibility of importing bank details into your plentymarkets system. To do so, use the data format <<basics/data-exchange/data-formats/customer#, Customer>>. Contact a legal adviser for information about the current laws in your own country as well as in other countries of delivery.

[IMPORTANT]
.Pay attention to subscription orders
====
Note that the bank details saved here are also used for subscription orders with the payment method *Debit*. If you delete bank details that are connected to such a subscription order, the payment method in the <<order-processing/orders/scheduler#, scheduler>> is changed to the <<omni-channel/online-store/setting-up-clients/order-process#, default payment method>> for the client (store). The subscription order is then no longer paid for as an automatic bank transfer. In such a case, only delete the bank details if absolutely necessary. If possible, save new bank details for the customer.
====

[#2700]
==== Sending a new password

In the *Password* tab, you can enter a new password for the customer. Decide whether you want to send the password to the customer by clicking on *Send email to customer* in the *Reset password* area.

Check the <<crm/sending-emails#100, access data>> if the email was not sent correctly. Go to <<basics/data-exchange/api-log#, Data » API log>> and use the *Email* process to see the error messages.

Go to *System » System settings » CRM » Passwords* to generate new password for all of your customers. Further information can be found in the <<crm/managing-customer-data#3100, Generating new passwords for all customers>> chapter.

[#2800]
==== Viewing the login URL

In the *Login URL* tab, you can see the URL for directly accessing the customer's account in the online store. If you use this URL, you are no longer required to enter login details (email address and password) in the online store. Enter the email address in the *CRM » Edit customer » Open customer » Tab: Customer data* menu in the *Email* field and enter the password in the *CRM » Edit customer » Open customer » Tab: Settings » Tab: Password* menu. The login URL is generated after the data is saved. Make sure to use a secure password. Otherwise an error message is displayed.

[#2900]
==== Creating a cost unit

In the *Cost units* tab, you create cost units. You also have the possibility of editing cost units here. A cost unit, also known as a cost centre, is part of an organisation that does not produce direct profit and adds to the cost of running a company.

[.instruction]
Creating a cost unit:

. Go to *CRM » Edit customer*.
. Search for the customer by using the <<crm/managing-customer-data#1100, filter settings>>.
. Open the customer.
. Click on the *Settings* tab.
. Click on the *Cost units* tab.
. Click on the *New cost unit* tab.
. Enter the name for the cost unit.
. Enter the budget for the cost unit.
. Enter the remaining budget for the cost unit.
. Select the *budget period* for the budget that was entered.
. *Save* the settings. +
→ The newly created cost unit is now listed in the *Cost units* tab.

[#3000]
==== Saving a commission

In the *Item commissions* tab, you can save item-specific commissions for the customer type *Sales representative*. Proceed as described below to enter values for commissions.

[.instruction]
Saving a commission:

. Go to *CRM » Edit customer*.
. Search for the customer by using the <<crm/managing-customer-data#1100, filter settings>>.
. Open the customer.
. Click on the *Settings* tab.
. Click on the *Commissions* tab.
. Click on the *Item commissions* tab.
. Expand the *New commission* area.
. Enter the *item ID* of the particular item that you wish to save one or more commission(s) for.
. Enter the commission(s) in percent. +
→ Enter up to 4 commissions per entry.
. *Save* the settings. +
→ The commission is saved. The name matching the item ID is displayed. This way you recognise the corresponding item right away.

[#3050]
== Deleting a customer

You can delete individual customers in the *CRM » Edit customer* menu in the *Customers* tab. Please note that you can only delete a customer when his or her customer data record is not linked to an order.

[.instruction]
Deleting a customer:

. Go to *CRM » Edit customer*.
. Search for the customer by using the <<crm/managing-customer-data#1100, filter settings>>. +
→ All customers that match the search criteria you selected are displayed.
. Click on *Delete* on the right side in the line of the customer. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The customer is deleted and removed from the overview.

[TIP]
.Show procedures to delete a customer
====
Note that the option *Procedures* must be activated in the customer overview. If this option is deactivated, you are not able to delete the customer. Activate the option *Procedures* via the function *Customise the layout* by clicking on the title bar. For further information, refer to the <<basics/working-with-plentymarkets/general-functions#50, Customising the layout>> chapter on the <<basics/working-with-plentymarkets/general-functions#, Using general functions>> page of the manual.
====

[#3100]
== Generating new passwords for all customers

Go to *System » System settings » CRM » Passwords* to generate new password for your customers. This can be necessary, e.g., if someone hacked into your plentymarkets system or if you are the victim of data theft.

[WARNING]
.Emails with newly generated passwords are not sent automatically
====
Note that your customers do not receive the newly generated passwords or any other information automatically. You have to e.g. actively send your customers an email informing them about the current situation and encouraging them to change their passwords in the My account area of your online store.
====

Proceed as follows to generate new passwords for all of your customers.

[.instruction]
Generating new passwords for all customers:

. Go to *System » System settings » CRM » Passwords*.
. Click on *Generate new passwords for all customers*. +
→ The new passwords are generated.

[#3200]
== Checking the VAT number

The value added tax identification number (VAT number) is an exclusive identification number and serves to designate VAT registered individuals. Within the EU, tax offices need this number for VAT accounting purposes. The VAT number is saved and checked in the *CRM » Edit customer* menu. It is located within the *Customer data* tab of each customer data record.

The VAT check allows you to verify German and international VAT numbers. These checks can be carried out daily from 5:00 a.m. to 11:00 p.m. CET. All VAT numbers from EU member states can be checked, with the exception of those from Slovakia and Latvia (is not possible or only possible to a limited extent). For German VAT numbers, only the number's validity is checked. The assignment to a person are not checked. For international VAT numbers, the number's validity is checked and the company and address details associated with the VAT number are retrieved and displayed.

[#3300]
=== Checking the VAT number in the customer data record

Proceed as follows to check the VAT number in the customer data record.

[.instruction]
Checking the VAT number in the customer data record:

. Go to *CRM » Edit customer*.
. Search for the customer by using the <<crm/managing-customer-data#1100, filter settings>>.
. Open the customer.
. In the *Customer data* tab, enter the VAT number without any spaces under *VAT number*.
. Click on *Check*. +
→ The check can take a few minutes.
. Once the check is completed, click on *Save* to save the VAT number.

The query provides the outcome of the VAT number check.

If the VAT number is valid, the status *Valid* is displayed. If the VAT number is not valid, the status *Invalid* is displayed. A message is displayed if a VAT number could not be checked. Data that does not match is designated with a red error message in the *Status* row.

You can check the VAT number from within the customer data section of an order. To do so, go to *Orders » Edit orders » Open order » Tab: Customer » Tab: Customer data*.

[#3400]
=== Checking the VAT number in the online store

The VAT number is automatically checked in the online store during the order process. If an invalid VAT number was entered, the purchaser is only able to complete his or her order once a valid VAT number has been entered or once the entry has been deleted.

[#3500]
=== Exporting check data

You can export a list of all the check data or the data for the current month. For further information about exporting the VAT number check data, refer to the <<basics/data-exchange/exporting-data#, Exporting data>> page of the manual in the <<basics/data-exchange#, Data exchange>> area.

[#3600]
== Displaying the accounts receivable list

The *CRM » AR list* menu provides you with an overview of all customers with unpaid orders. Here, AR stands for accounts receivable. The list includes the number of claims held for each customer as well as the total pending amount for these claims.

The accounts receivable list is automatically updated once per day. As such, claims may not be displayed in the list until the next day. However, it is also possible to <<crm/managing-customer-data#3800, update the list manually>>. Proceed as described below to display the entire accounts receivable list.

[.instruction]
Displaying the accounts receivable list:

. Go to *CRM » AR list*.
. Click on *Search*. +
→ All of the claims are displayed.

It is possible to open the customer data record from this list. Simply click on the ID in the *ID* column. It is also possible to open a list of all orders that were placed by the customer and that have not been paid yet. Simply click on *Show orders* in the *Orders* column.

[#3700]
=== Filtering the accounts receivable list

The list in the *CRM » AR list* can be filtered by *type*, *country*, *customer class* or *customer type*. The list can also be sorted from the highest to lowest number of *accounts receivable* or from the highest to lowest *pending amount*.

[.instruction]
Filtering the accounts receivable list:

. Go to *CRM » AR list*.
. Select the filters.
. Click on *Search* to display the results.

[#3800]
=== Manually updating the accounts receivable list

The accounts receivable list is automatically updated once per day. However, you can also update the list manually anytime.

[.instruction]
Manually updating the accounts receivable list:

. Go to *CRM » AR list*.
. Click on *Generate* in the *Generate AR list* area. +
→ The list is updated in the background.
. Click on *Search* to display the updated list.

[#3900]
== Using the discount system

In plentymarkets, you have various possibilities for offering discounts. You may give your customers a <<crm/managing-customer-data#4200, customer class discount>>, a discount based on the payment method or a <<crm/managing-customer-data#4100, discount scale based on the net value of items>>. Furthermore, you can <<crm/managing-customer-data#4300, save sales prices as discounts>> and <<crm/managing-customer-data#4400, manually enter discounts>>. Go to *System » System settings » CRM » Customer classes* to carry out the settings for the types of discounts. The following sub-chapters describe which settings you need to carry out in order to give discounts.

[#4000]
=== Setting up a customer class discount

In a customer class, you determine discounts that are only effective for this customer class. Furthermore, you have further configuration possibilities, such as activating the sales price's volume discount. Make sure that the discounts can be added for each configuration.

Proceed as described below to save a discount for customer classes.

[.instruction]
Setting up a customer class discount:

. Go to *System » System settings » CRM » Customer classes*.
. Expand the customer class that the discount should be applied to.
. Activate the option *Customer class discount* as *Discount type*. +
→ A further area to carry out settings opens.
. Under *Discount in %*, enter the percentage that you would like to have deducted.
. Select whether the *Volume discount* should be taken into consideration.
. Select which of the payment methods that are available in the online store should be permitted for this customer class.
. Enter payment instructions. +
→ These payment instructions are displayed on invoices.
. Select whether the prices in the online store should be displayed as *gross* (including VAT) or *net* (excluding VAT) prices.
. *Save* the settings.

You find information about how to create customer classes in the <<crm/managing-customer-data#100, Creating a customer class>> chapter.

[#4100]
=== Entering a discount scale based on the net value of items

If you would like to reward your customers with discounts when they make large purchases in your online store, you can determine amounts that should be discounted based on the net value of items in the order.

[.instruction]
Entering a discount scale based on the net value of items:

. Go to *System » System settings » CRM » Customer classes*.
. Expand the customer class that the discount scale should be applied to.
. Activate the option *Discount scale based on net value of items* as *Discount type*. +
→ A table with further settings opens.
. Enter monetary amounts under the words *Minimum net value of items* in an ascending order.
. Under *Discount in %*, enter the percentage that you would like to have deducted. +
→ If you enter 50, e.g. in the field *Minimum net value of items* and 2 in the field *Discount in %*, a 2% discount is offered for orders totalling £50 or more.
. Select whether the *Volume discount* should be taken into consideration.
. Select which of the payment methods that are available in the online store should be permitted for this customer class.
. Enter payment instructions. +
→ These payment instructions are displayed on invoices.
. Select whether the prices in the online store should be displayed as *gross* (including VAT) or *net* (excluding VAT) prices.
. *Save* the settings.

You find information about how to create customer classes in the <<crm/managing-customer-data#100, Creating a customer class>> chapter.

[.subhead]
What the customer sees when making a purchase

The discount is calculated and displayed once the customer has finished putting items into his or her shopping cart and has gone to the checkout. Initially, only the total discount is displayed in the shopping cart. When the customer completes the order and clicks on Go to cashier, the discount is calculated for the individual items in addition to the total discount and displayed accordingly.

[#4200]
=== Entering a discount based on the payment method

The discount type *Discount based on the payment method* is a sort of early payment discount in plentymarkets. You offer customers a discount if they use one or more payment methods.

[TIP]
.Directly saving a discount based on the payment method
====
Instead of configuring the settings in this menu, it is also possible to directly save a global discount for a payment method. An example is a discount in percent for the payment method *Cash in advance*. For further information, refer to the <<order-processing/payment/managing-payment-methods#20, Managing payment methods>> page of the manual. You are not able to completely customise the settings if you save a discount directly for a payment method. It is only possible to completely customise the settings when using the option *Discount based on payment method* in the *System » System settings » CRM » Customer classes* menu.
====

Proceed as described below to set up a discount based on one or more payment methods.

[.instruction]
Entering a discount based on the payment method:

. Go to *System » System settings » CRM » Customer classes*.
. Expand the customer class that the discount should be applied to.
. Enter a *Payment due* in days, which you would like to permit for this customer class.
. Activate the option *Discount based on payment method*. +
→ A table with further settings opens.
. Select one or several payment methods that the discount should be applied to.
. Under *Discount in %*, enter the percentage that you would like to have deducted.
. Select whether the *Volume discount* should be taken into consideration.
. Select which of the payment methods that are available in the online store should be permitted for this customer class.
. Enter payment instructions. +
→ These payment instructions are displayed on invoices.
. Select whether the prices in the online store should be displayed as *gross* (including VAT) or *net* (excluding VAT) prices.
. *Save* the settings.

You find information about how to create customer classes in the <<crm/managing-customer-data#100, Creating a customer class>> chapter.

[#4300]
=== Saving sales prices as discounts

A volume-related discount is created as own price in the *System » System settings » Item » Sales prices* menu. Using the option *Minimum quantity* in the *Settings* area, you specify for the sales price from which item quantity the discounted price should be valid. You can realise graduated prices by creating multiple sales prices accordingly and entering the desired minimum quantities. +
The discounted sales price is activated once you set the option *Volume discount* in the customer class to *include*. A customer receives the discount in case he or she belongs to the customer class and in case he or she orders at least the quantity saved for the sales price.

[.instruction]
Saving sales prices as discounts:

. Go to *System » System settings » Item » Sales prices*.
. Open the sales price.
. Enter a number in the *Settings* tab in the field *Minimum quantity*. This number determines from which item quantity the discounted price is valid.
. Activate the customer classes in the area *Class* for which the sales price should be valid.
. *Save* the settings.

Further information on sales prices can be found within the <<item/managing-items#, Items>> area in the <<item/managing-items#870, Managing sales prices>> chapter.

[#4400]
=== Manually entering a discount

Not only is it possible to automatically assign discounts, but it is also possible to manually assign a discount to some or all of the items contained in an order. There 2 two ways to manually enter discounts: in the list view of the <<order-processing/orders/managing-orders#, order search>> and in the editing window of an <<order-processing/orders/managing-orders#changing-order, order>>.

[#4500]
==== Entering a discount for individual items in the order search

If you would like to quickly assign discounts to individual stock units within an order, you can do that directly in the order search area. Proceed as described below to enter or edit a discount for individual items in the order search.

[.instruction]
Entering a discount for individual items in the order search:

. Go to *Orders » Edit orders*. +
→ The order search is displayed.
. Click on *Discount* on the right-hand side of an order (default value: *0%*). +
→ A window is displayed for entering the percentage.
. Enter the desired percentage of discount.
. *Save* the setting. +
→ The discount value is displayed and the discount is deducted from the stock unit.

[#4600]
==== Entering a discount for individual items in an order

The stock units are displayed at the very bottom of the order overview. You can also assign discount values to individual stock units here or you can edit discount values. Proceed as described below to enter or edit a discount for individual items in the order search.

[.instruction]
Entering a discount for individual items in an order:

. Go to *Orders » Edit orders*.
. Open the order that you want to discount. This is done by clicking on the order number.
. Click on *Edit* in the lower area of the order's *Overview*.
. Select the percentage of discount from the *Discount* drop-down list.
. *Save* the settings.

[#4700]
==== Entering a discount for all items of an order

Proceed as described below to enter or edit a discount for all stock units of an order.

[.instruction]
Entering a discount for all items of an order:

. Go to *Orders » Edit orders*.
. Open the order that you want to discount. This is done by clicking on the order number.
. Click on *Edit* in the lower area of the order's *Overview*.
. Click on the link *Give discount on all items* below the list of stock units.
. Select the percentage value from the displayed drop-down list.
. Click on *Save* to the right of the drop-down list.
. *Save* the settings.
