= Managing contacts
:lang: en
include::{includedir}/_header.adoc[]
:keywords: contact, customer, address, addresses, invoice address, delivery address, primary, company, companies, guest account, regular account, events, event, login details, change password, unblock login, bank details
:description: Learn how to manage contacts, addresses and companies in plentymarkets.
:position: 10
:icons: font
:docinfodir: /workspace/manual-adoc/de/_includes/_plugin/css/styles.css
:url: crm/managing-contacts

This page of the manual describes all settings that are available in the *CRM » Contacts* menu in the Terra back end using the centralised login as well as the settings that are carried out in the *Setup » CRM* menu.

Go to the *Setup » CRM* menu to carry out preparatory settings such as creating customer classes and types. Go to *CRM » Contacts* to create and edit data records for your contacts and manage all relevant information there such as addresses, orders, scheduled orders, tickets, notes, account balance, bank details and documents.

[#10]
== Carrying out the preparatory settings

Go to the *Setup » CRM* menu to carry out the preparatory settings such as creating <<crm/managing-contacts#15, customer classes>> and <<crm/managing-contacts#20, types>>. Furthermore, you set up <<crm/managing-contacts#25, discounts>> for your customers.

[#13]
=== Setting up the address layout for delivery notes

In the *Setup » CRM » Address layout* menu, you can individually set up address layout for your countries of delivery for the order document *Delivery note*. The address layouts for the countries of delivery German, France and the United Kingdom are already available in your plentymarkets system by default. You can edit these 3 address layouts if you have the corresponding rights to do this.

[.subhead]
Setting the visibility of the address layout for variable users

In order that the *Setup » CRM » Address layout* menu is visible for users with the user class *Variable*, the menu must be activated in the user account.

[.instruction]
Setting the visibility of the address layout for variable users:

. Go to *Setup » Settings » User » Account*.
. Open the user with the user class *Variable* for whom you would like to activate the visibility of the menu.
. Click on the *Right* tab.
. Click on the *Menu* tab.
. Expand the section *Settings » CRM*.
. Place a check mark next to the option *Address layout*.
. *Save* (icon:save[role="green"]) the settings. +
→ The *Setup » CRM » Address layout* menu is visible for the variable user.

[TIP]
.Variable users: REST API rights to create, delete and update address layouts
====
In order that variable users can create, update and delete address layouts in the *Setup » CRM » Address layout* menu, the right must be set in the user account in the *Rights » REST API* area.
====

[.instruction]
Setting up the address layout for delivery notes:

. Go to *Setup » CRM » Address layout*.
. Click on *New*.
. Carry out the settings. Pay attention to the information given in <<table-set-up-address-layout>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-set-up-address-layout]]
.Setting up the address layout
[cols="1,3"]
|====
|Setting |Explanation

2+|*Basic settings*

|*Layout name*
|Enter a name.

|*Use as standard address layout*
|Activate the toggle button if this layout is to be used as standard layout. In the overview on the left side, the standard address layout is marked with an asterisk.

|*Field list*
|If required, enter English and German names for the field names in order that this names can be displayed when designing the address layout.

|*Save*
|Save the settings. The list of the field names closes and the areas *Countries*, *Layout* and *Fields* are displayed.

|*Countries*
|Select one country or multiple countries from the list to which the address layout should apply.

|*Layout* / +
*Fields*
|Drag the address fields from the area *Fields* to the area *Layout*. By doing so, you individually design the address layout for each country. +
*_Tip:_* It is possible to add further rows (maximum number of rows: 6) and to remove single fields and complete rows. Blank rows can also be used. The number of fields per row is not limited.

|====

In order that the address layouts are automatically displayed on delivery notes, you have to carry out a setting in the delivery note. Your plentymarkets system automatically checks the country of delivery saved in the order and displays the delivery note in the layout listed in the *Setup » CRM » Address layout* menu. Proceed as described below.

. Go to *Setup » Client » Select client » Locations » Select location » Documents » Delivery note*.
. Activate the option *New address layout* in the area *Basic settings:{nbsp}Delivery note*. +
→ The option above *Structure of the invoice/delivery address* is hidden and the delivery notes are displayed in the address layouts listed in the *Setup » CRM » Address layout* menu.
. *Save* (icon:save[role="green"]) the settings.

How to create delivery notes is described on the <<orders/order-documents/generating-delivery-notes#, Generating delivery notes>> page of the manual.

Currently, this setting is only available for delivery notes. This setting will follow for further documents.

[#15]
=== Creating a customer class

Use customer classes to categorise your customer base according to specific criteria. For example, you can create a customer class for consumers (B2C) that displays gross prices for the items in your online store. For sellers (B2B), you create another customer class that displays net prices for the items in your online store. Further options are discounts based on the net value of your items, discounts based on the payment method or discount scales for a selected customer class.

Go to *Setup » CRM » Customer classes* to create new customer classes. The customer classes that you created in this menu are available in the contact data records in the *CRM » Contacts* menu.

[TIP]
.Tip: Create types and classes
====
It is recommended to create a concept for organising your customer base into types and classes before saving customer data. By doing this, you will save time later on. For example, types and classes are automatically assigned when the initial configuration is missing. Decide which types and classes you need, create them and assign them to the customers.
====

You can set up and individually configure as many customer classes as you like. An ID is automatically assigned to customer classes. This ID is displayed to the left of the customer classes' name in the overview. However, customer classes are not ordered by ID. Instead, the order is set using the option *Position*.

If a new customer class is created, the customer class is available in the detail view of the contact in the *CRM » Contacts » Open contact* menu.

[.instruction]
Creating a customer class:

. Go to *Setup » CRM » Customer classes*.
. Click on the *New customer class* tab.
. Carry out the settings. Pay attention to the information given in <<table-create-customer-class>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-create-customer-class]]
.Creating a customer class
[cols="1,3"]
|====
|Setting |Explanation

|*Minimum order quantity*
|Enter the minimum order quantity if you want to require customers to order a specific quantity of items or if you want to require them to order a minimum quantity to get a discount.

|*Name*
|Enter a name for the new customer class, e.g. *wholesaler* or *premium customer*.

|*Position*
|If you do not enter a position, the next available position number is assigned automatically. The position is primarily used to sort the customer classes in the menu. It is relevant e.g. in combination with the visibility of item prices in the online store. This can be set under *Display of the prices in the online store*.

|*Payment due date*
|Enter a payment due date in days for this customer class. If a payment due date is also saved for a contact in the contact data record, it has priority over the payment due date saved here. The payment due date can also be saved as an optional field on <<order-processing/orders/order-documents#, order documents>> such as <<orders/order-documents/generating-invoices#, invoices>>. The invoice's payment due date would be used if no other payment due date was saved in the customer data record or the customer class. Pay attention to the expandable box *Example:{nbsp}terms of payment* below <<table-create-contact>> in the <<crm/managing-contacts#100, Creating a contact>> menu.

|*Customer ID*
|Specify the customer who is to receive the multi-invoices that are created from <<orders/managing-orders#800#, multi-orders>>. Simply enter the customer ID. Multi-orders are generated for this customer class and the invoice is sent to that customer.

|*Discount type*
|Select a discount type. The number of options that are visible depends on which discount type was selected. If you do no want to offer a discount, select the option *No discount*. Further information and explanations about the discount types in plentymarkets can be found in the <<crm/managing-contacts#25, Using the discount system>> chapter.

|*Volume discount*
|Select whether the value entered in the *Setup » Item » Sales prices* menu under *Minimum quantity* should be taken into account or not.

|*Permitted payment methods*
|Select which of the payment methods that are available in the online store should be permitted for this customer class. +
All of the available payment methods are selected by default. When you integrate new payment methods, you have to permit them here. This is because new payment methods are not automatically included in this list. +
*_Important_*: Pay attention to which <<fulfilment/preparing-the-shipment#1000, payment methods are blocked in the shipping profiles>> that you want to use for this customer class. Check those settings to make sure that they are compatible with the settings you make here. If you want to permit a payment method for a customer class, you should make sure it is not blocked in the shipping profiles. Make sure that the corresponding customer class is not blocked either.

|*Payment instruction*
|The payment instructions that are saved here are displayed on invoices. For example, you could enter payment information that relates to a specific customer class.

|*Display of the prices in the online store*
|Select whether *Gross* or *net* prices are displayed in the online store. +
*_Important_*: This option only sets how prices are displayed. It does not influence the way prices are calculated for the customer class. This option is particularly important for the customer class with position 1. This customer class is automatically assigned to customers if no customer class was selected in the contact data record.
|====

You can link sales prices with customer classes. Go to *Setup » Items » Sales prices* and select one of the customer classes that you created under the setting *Class*. For further information, refer to the <<item/managing-items#870, Managing sales prices>> chapter on the <<item/managing-items#, Managing items>> page of the manual.

[#20]
=== Creating a type

Types are used to classify and differentiate contacts. Some customer types are available by default in your plentymarkets system and cannot be deleted. These types are *Customer*, *Sales representative*, *Supplier*, *Partners*, *Manufacturer* and *Interested party*. The types that you created are available in the *Filter* area in the *Type* drop-down list in the *CRM » Contacts* menu.

When creating a new contact data record, the customer type *Customer* is automatically set by default. Customers who were assigned to the customer type *Supplier* are available to select in certain drop-down lists, e.g. in a variation's *Supplier* tab.

Proceed as described below to create customer types.

[.instruction]
Creating a type:

. Go to *Setup » CRM » Types*.
. Click on *Add type*.
. Enter a name.
. *Save* (icon:save[role="green"]) the settings.

[.subhead]
Deleting a type

Proceed as described below to delete types if they are no longer needed. Note that you cannot delete types that are already available in your plentymarkets system by default.

[.instruction]
Deleting a type:

. Go to *Setup » CRM » Types*.
. Click on *Delete*.
. Confirm your decision.

[#25]
=== Using the discount system

In plentymarkets, you have various possibilities for offering discounts. You may give your customers a <<crm/managing-contacts#26, customer class discount>>, a <<crm/managing-contacts#28, discount based on the method of payment>> or a <<crm/managing-contacts#27, discount scale based on the net value of items>>. Furthermore, you can <<crm/managing-contacts#29, save sales prices as discounts>> and <<crm/managing-contacts#30, manually enter discounts>>. Go to *Setup » CRM » Customer classes* to carry out the settings for the types of discounts. The following sub-chapters describe which settings you need to carry out in order to give discounts.

[#26]
==== Setting up a customer class discount

In a customer class, you determine discounts that are only effective for this customer class. Furthermore, you have further configuration possibilities, such as activating the sales price's volume discount. Make sure that the discounts can be added for each configuration.

Proceed as described below to save a discount for customer classes.

[.instruction]
Setting up a customer class discount:

. Go to *Setup » CRM » Customer classes*.
. Expand the customer class that the discount should be applied to.
. Activate the option *Customer class discount* as *Discount type*. +
→ A further area to carry out settings opens.
. Under *Discount in %*, enter the percentage that you would like to have deducted.
. Select whether the *Volume discount* should be taken into consideration.
. Select which of the payment methods that are available in the online store should be permitted for this customer class.
. Enter payment instructions. +
→ These payment instructions are displayed on invoices.
. Select whether the prices in the online store should be displayed as *gross* (including VAT) or *net* (excluding VAT) prices.
. *Save* (icon:save[role="green"]) the settings.

You find information about how to create customer classes in the <<crm/managing-contacts#15, Creating a customer class>> chapter.

[#27]
==== Entering a discount scale based on the net value of items

If you would like to reward your customers with discounts when they make large purchases in your online store, you can determine amounts that should be discounted based on the net value of items in the order.

[.instruction]
Entering a discount scale based on the net value of items:

. Go to *Setup » CRM » Customer classes*.
. Expand the customer class that the discount scale should be applied to.
. Activate the option *Discount scale based on net value of items* as *Discount type*. +
→ A table with further settings opens.
. Enter monetary amounts under the words *Minimum net value of items* in an ascending order.
. Under *Discount in %*, enter the percentage that you would like to have deducted. +
→ If you enter 50, e.g. in the field *Minimum net value of items* and 2 in the field *Discount in %*, a 2% discount is offered for orders totalling £50 or more.
. Select whether the *Volume discount* should be taken into consideration.
. Select which of the payment methods that are available in the online store should be permitted for this customer class.
. Enter payment instructions. +
→ These payment instructions are displayed on invoices.
. Select whether the prices in the online store should be displayed as *gross* (including VAT) or *net* (excluding VAT) prices.
. *Save* (icon:save[role="green"]) the settings.

You find information about how to create customer classes in the <<crm/managing-contacts#15, Creating a customer class>> chapter.

[.subhead]
What the customer sees when making a purchase

The discount is calculated and displayed once the customer has finished putting items into their shopping cart and has gone to the checkout. Initially, only the total discount is displayed in the shopping cart. When the customer completes the order and clicks on Go to cashier, the discount is calculated for the individual items in addition to the total discount and displayed accordingly.

[#28]
==== Entering a discount based on the method of payment

The discount type *Discount based on the method of payment* is a sort of early payment discount in plentymarkets. You offer customers a discount if they use one or more payment methods.

[TIP]
.Directly saving a discount based on the method of payment
====
Instead of configuring the settings in this menu, it is also possible to directly save a global discount for a payment method. An example is a discount in percent for the payment method *Cash in advance*. For further information, refer to the <<payment/managing-payment-methods#, Managing payment methods>> page of the manual. You are not able to completely customise the settings if you save a discount directly for a payment method. It is only possible to completely customise the settings when using the option *Discount based on the method of payment* in the *Setup » CRM » Customer classes* menu.
====

Proceed as described below to set up a discount based on one or more payment methods.

[.instruction]
Entering a discount based on the method of payment:

. Go to *Setup » CRM » Customer classes*.
. Expand the customer class that the discount should be applied to.
. Enter a *Payment due date* in days, which you would like to permit for this customer class.
. Activate the option *Discount based on method of payment*. +
→ A table with further settings opens.
. Select one or several payment methods that the discount should be applied to.
. Under *Discount in %*, enter the percentage that you would like to have deducted.
. Select whether the *Volume discount* should be taken into consideration.
. Select which of the payment methods that are available in the online store should be permitted for this customer class.
. Enter payment instructions. +
→ These payment instructions are displayed on invoices.
. Select whether the prices in the online store should be displayed as *gross* (including VAT) or *net* (excluding VAT) prices.
. *Save* (icon:save[role="green"]) the settings.

You find information about how to create customer classes in the <<crm/managing-contacts#15, Creating a customer class>> chapter.

[#29]
==== Saving sales prices as discounts

A volume-related discount is created as own price in the *Setup » Item » Sales prices* menu. Using the option *Minimum quantity* in the *Settings* area, you specify for the sales price from which item quantity the discounted price should be valid. You can realise graduated prices by creating multiple sales prices accordingly and entering the desired minimum quantities. +
The discounted sales price is activated once you set the option *Volume discount* in the customer class to *include*. A customer receives the discount in case they belong to the customer class and in case they order at least the quantity saved for the sales price.

[.instruction]
Saving sales prices as discounts:

. Go to *Setup » Item » Sales prices*.
. Open the sales price.
. Enter a number in the *Settings* tab in the field *Minimum quantity*. This number determines from which item quantity the discounted price is valid.
. Activate the customer classes in the area *Class* for which the sales price should be valid.
. *Save* (icon:save[role="green"]) the settings.

Further information on sales prices can be found within the <<item/managing-items#, Items>> area in the <<item/managing-items#870, Managing sales prices>> chapter.

[#30]
==== Manually entering a discount

Not only is it possible to automatically assign discounts, but it is also possible to manually assign a discount to some or all of the items contained in an order. There are 2 ways to manually enter discounts: in the list view of the <<orders/managing-orders#1300, order search>> and in the editing window of an <<orders/managing-orders#1530, order>>.

[#31]
===== Entering a discount for individual items in the order search

If you would like to quickly assign discounts to individual stock units within an order, you can do that directly in the order search area. Proceed as described below to enter or edit a discount for individual items in the order search.

[.instruction]
Entering a discount for individual items in the order search:

. Go to *Orders » Edit orders*. +
→ The order search is displayed.
. Click on *Discount* on the right-hand side of an order (default value: *0%*). +
→ A window is displayed for entering the percentage.
. Enter the desired percentage of discount.
. *Save* (icon:save[role="green"]) the settings. +
→ The discount value is displayed and the discount is deducted from the stock unit.

[#32]
===== Entering a discount for individual items in an order

The stock units are displayed at the very bottom of the order overview. You can also assign discount values to individual stock units here or you can edit discount values. Proceed as described below to enter or edit a discount for individual items in the order search.

[.instruction]
Entering a discount for individual items in an order:

. Go to *Orders » Edit orders*.
. Open the order that you want to discount. This is done by clicking on the order number.
. Click on *Edit* in the lower area of the order's *Overview*.
. Select the percentage of discount from the *Discount* drop-down list.
. *Save* (icon:save[role="green"]) the settings.

[#33]
===== Entering a discount for all items of an order

Proceed as described below to enter or edit a discount for all stock units of an order.

[.instruction]
Entering a discount for all items of an order:

. Go to *Orders » Edit orders*.
. Open the order that you want to discount. This is done by clicking on the order number.
. Click on *Edit* in the lower area of the order's *Overview*.
. Click on the link *Give discount on all items* below the list of stock units.
. Select the percentage value from the displayed drop-down list.
. Click on *Save* to the right of the drop-down list.
. *Save* (icon:save[role="green"]) the settings.

[#50]
== Setting the visibility of the contact menu for variable users

In order that the *CRM » Contacts* menu is visible for users with the user class *Variable*, the menu must be activated in the user account.

Since the new user interface of the *CRM » Contacts* menu is retrieved via REST, additional rights have to be activated in the *REST API* menu. The following describes which rights must be at least activated in order that the menu is visible. Activate further rights accordingly. If you want that the variable user to create company data records, for example, go to the *Accounts* section and activate the *Create account* option.

[.instruction]
Setting the visibility of the contact menu for variable users:

. Go to *Setup » Settings » User » Accounts*.
. Open the user with the user class *Variable* for whom you would like to activate the visibility of the menu.
. Click on the *Right* tab.
. Click on the *Menu* tab.
. Expand the *CRM* section.
. Activate the *Contacts* options.
. Click on the *REST API* tab.
. Expand the *Accounts* section.
. Expand the *Address* section.
. Activate the *Show address* option.
. Expand the *Address option* section.
. Expand the *Type of address option* section.
. Activate the *Show type of address option* option.
. Expand the *Contact* section.
. Expand the *Contact address* section.
. Activate the *Show contact address* option.
. Expand the *Address type* section.
. Activate the *Show address type* option.
. Expand the *Contact option* section.
. Expand the *Type of contact option* section.
. Activate the *Show type of contact option* option.
. Expand the section *property*.
. Activate the *show* option.
. Expand the section *propertyOption*.
. Activate the *show* option.
. Expand the *Tag* section.
. Activate the *show* option.
. Expand the *tagRelationship* section.
. Activate the *show* option.
. *Save* (icon:save[role="green"]) the settings.

[#90]
== Managing contacts and companies

In the following sub-chapters, you learn, for example, how to create new contacts and companies, link contacts to a company, search for existing contacts using the filter settings as well as edit and delete existing contacts.

[.collapseBox]
.*Notes about detail view, context menu, card view and table view*
--
If you click on a contact in the overview of the *CRM » Contacts* menu in order to display or edit the contact, the detail view of the contact opens. Via the context menu in the left section of the contact, you can access views such as *Addresses* or *New address*.

As an alternative, you can access the menus *New multi-order*, *New order*, *Orders*, *New ticket* and *New note* as well as the function *Delete contact* easily with a right click.

If you click on *Addresses* in the detail view of the contact for example, all addresses that are saved for the contact are initially displayed as cards. By clicking on *Switch to table view*, the addresses are displayed in a table. From this view, you can switch back by clicking on *Switch to card view*. Your plentymarkets system recognises which of the two views you selected. When opening the action menu *Addresses* the next time, the view that was selected last is displayed.

When more than one view of the contact is open, an arrow is displayed in the view above. Click on the arrow to quickly and easily switch between the open views. Click on the cross to close the contact and remove it from the list.

You can get back to the overview of contacts found via the *Overview* view. From this view, you can open as many further contacts as you like. When more than one contact is open, an arrow is displayed in the view of the contact that is currently open. Click on the arrow to quickly and easily access contacts that have been opened at least once. Click on the cross to close the contact and remove it from the list.

--

[#100]
=== Creating a contact

Proceed as described below to create a new contact. Link the contact to an existing company or create a new company. Add contact options such as the email address and telephone numbers. You can create a new contact also while taking an order over the phone or while filling out a written order. It is also possible to save the contact details of interested parties here. When creating a contact, the system automatically assigns an ID. This ID cannot be changed.

For further information about linking a contact to a company and creating a new company, refer to the <<crm/managing-contacts#210, Linking a contact to a company>> and <<crm/managing-contacts#220, Creating a company>> chapters.

[.instruction]
Creating a contact:

. Go to *CRM » Contacts*.
. Click on *Create new contact*.
. Carry out the settings as desired in the *New contact* section. Pay attention to the information given in <<table-create-contact>>.
. Assign one or multiple tags in the area *Assigned tags*. Pay attention to the information given in the <<crm/managing-contacts#150, Creating tags>> chapter.
. Create a new company in the *Accounts* section or assign an existing company to a contact. Pay attention to the information given in <<table-create-contact>>. +
→ Further information can be found in the <<crm/managing-contacts#220, Creating a company>> and <<crm/managing-contacts#210, Linking the contact to a company>> chapters.
. In the *Contact options* section, select the type and sub-type from the drop-down list and enter the value. Pay attention to the information given in <<table-create-contact>>. +
→ Click on *Add contact option* to add further contact options.
. Add the address of the contact. +
→ *_Note:_* If you would like to create the address at a later point in time, deactivate the toggle button *Create address?*.
. Carry out the settings. Pay attention to the information given in <<table-create-contact>> in the *Address* section.
. *Save* (icon:save[role="green"]) the settings. +
→ The contact is created.

[IMPORTANT]
.Contact option: sub-type *Private* for the types *Email* and *Telephone*
====
Make sure to select the sub-type *Private* for the types *Email* and *Telephone* when creating the contact options in order that this data is automatically saved in the order.
====

[[table-create-contact]]
.Creating a contact
[cols="1,3"]
|====
|Setting |Explanation

2+|*New contact*

|*Form of address*
|Select the option from the drop-down list. This selection is optional. +
*Ms.* = Female form of address +
*Mr.* = Male form of address

|*Title*
|Enter the title of the contact, if required.

|*First name*, *Last name*
|Enter the first and last name of the contact. These are mandatory fields, if no company is selected.

|*Client*
|Select the client from the drop-down list in order to assign the contact to this client. +
Only those clients are displayed that have a name entered for them in the *Setup » Client » Select client » Settings* menu.

|*Language*
|Select the language for the contact. If you have created a template in the *Setup » Client » Select client » Email » Templates* menu in the same language that you have selected here, email templates are sent to the contact in this language.

|*Type*
|Select the type. The *Customer*, *Sales representative*, *Supplier*, *Partners*, *Manufacturers* and *Interested party* types can be selected by default. Create further types in the <<crm/managing-contacts#20, Setup » CRM » Types>> menu. +
*_Note:_* Depending on which setting is selected, different fields are visible in the area *Company*. Further information can be found in this table in the area *Company*.

|*Class*
|Select the class. This is a mandatory field. Classes serve as an internal distinction between customers and determine which discount is granted this class, for example. Go to <<crm/managing-contacts#15, Setup » CRM » Customer classes>> to create further classes. If you want to offer different prices to end customers and sellers in the online store, this can be done with the *Display of the prices in the online store* option in the settings of the customer class. It is very common that gross prices are displayed for end customers (B2C) in the online store and net prices for sellers (B2B).

|*Rating*
|Save a rating about the contact for internal use. Select 5 red stars for the worst and 5 yellow stars for the best rating.

|*Customer number*
|Enter a customer number for the contact, if required. Customer numbers can be assigned for internal purposes. They are not saved automatically. You decide whether and how you would like to use customer numbers.

|*Owner*
|Select the owner for the contact. If you do not want to select an owner, select the empty option. Only owners for whom the *Customer* option has been activated can be selected from the drop-down list. Go to *Setup » Settings » User » Account » Open user » Tab: Owner* to activate owners.

|*Debtor account*
|Enter an additional, separate customer number. Generally, this number corresponds to the customer number or the debtor number in your financial accounting. It can be helpful to you or your tax accountant when further processing your receipts. This field can also be filled in automatically, if required. +
For further information about the debtor account, refer to the <<orders/accounting#750, Accounting>> page of the manual.

|*Sales representative*
|With this setting, a sales representative is assigned to a contact. Enter the first 3 letters of the name or enter the ID. Matching representatives are automatically displayed in a list. By clicking on the name or the ID of the sales representative, the sales representative is assigned to the contact.

|*Allow invoice* / +
*Allow debit*
|Allow a payment method for the contact, even if this method is not used globally. +
*Do not allow* = The contact cannot pay using this payment method. +
*Allow* = The contact can pay using this payment method, even if you do not offer this payment method globally. +
*_Example:_* A contact who has bought in your online store multiple times, should be allowed to buy items on invoice. +
Necessary settings: +
Setting 1: Go to *Setup » Orders » Payment » Payment methods* to activate the payment method. This makes it possible to select the payment method in an order. +
*_Important:_* Make sure that no countries of delivery were saved in the settings of the payment method. Otherwise, the payment method would be available to all customers in the online store, which is not desired in this case. +
Setting 2: The second requirement is that the payment method *Invoice* or *Debit* has to be available in at least one shipping profile, i.e. the payment method may not be blocked. +
Setting 3: Activate the shipping profile for the items. +
Check the requirements that are listed here and activate the payment method. This allows the contact to use the payment method.

|*Date of birth*
|Enter the date of birth of the contact in the format yyyy-mm-dd or select it from the calendar.

|*Newsletter*
|Displays if the contact receives the newsletter. It is not possible to activate this option manually. In order to exclude the contact from receiving the newsletter, click on *Delete newsletter*.

|*Contact blocked*
|Select whether or not the contact should be blocked for the specific client. +
If the option is activated, the contact is blocked and can no longer log into the online store. If the option is deactivated, the contact is able to log into the online store.

2+|*Assigned tags*
2+|Click into the field in order to show all tags that are available for the area *Contacts* and that you have created beforehand in the *Setup » Settings » Tags* menu. +
icon:map-signs[] *_Or:_* Click into the field and enter the first 3 letters of the tag name. For further information about tags, refer to the <<crm/managing-contacts#150, Creating tags>> chapter.

2+|*Company*

|*Name*
|Enter the name of already <<crm/managing-contacts#220, created>> company in the suggestion list in order to assign this company to the contact. Or click into the field and enter the first 3 letters of the company name. +
*_Important:_* This is a mandatory field when there is no entry for first name and last name. +
Once an already existing company has been selected from the suggestion list, the data fields that belong to the company are displayed. These data fields are described in the following. +
How to create a new company is described in the <<crm/managing-contacts#220, Creating a company>> chapter. How you edit an existing company is described in the <<crm/managing-contacts#230, Creating a company>> chapter.

|*VAT number*
|Enter the value added tax identification number of the contact, if required. The VAT number needs to be specified if you are sending items to a commercial purchaser in another country within the EU (intra-community delivery) and you want net totals to be calculated for the order. +
After having entered the VAT number, go to <<orders/accounting#400, Setup » Client » Select client » Locations » Select location » Accounting>> and select *Net invoice* for the option *VAT number*. This causes invoices to be issued without VAT for contacts who have a VAT number saved in their data record. +
*_Important:_* The net setting does not go into effect if you saved tax rates for the customer's country of delivery.

|*Value date*
|Enter the time period (starting when the invoice is created) when you wish for an additional time period before the *payment due date* time period begins. Pay attention to the expandable box *Example:{nbsp}terms of payment* below the table. +
*_Important:_* The value date in the contact details can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *Setup » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Payment due date*
|Enter the number of days when the payment is due for the contact. This payment due date has priority over the payment due date saved for the customer class. The payment due date can also be saved as an optional field on documents such as <<orders/order-documents/generating-invoices#, invoices>>. The invoice's payment due date would be used if no other payment due date was saved in the contact details or the customer class. Pay attention to the expandable box *Example:{nbsp}terms of payment* below the table. +
*_Important:_* The payment due date in the contact details can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *Setup » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Days for early payment discount*
|Enter the number of days (starting when the invoice is created) in which the contact can pay the pending amounts at a discounted price. Pay attention to the expandable box *Example:{nbsp}terms of payment* below the table. +
*_Important:_* The early payment discount in the contact details can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *Setup » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Percentage for early payment discount*
|Enter the value in percent that the contact may subtract if he or she makes the payment within the time period *Days for early payment discount*. Pay attention to the expandable box *Example:{nbsp}terms of payment* below the table. +
*_Important:_* The early payment discount in the contact details can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *Setup » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Delivery period*
|Only visible if the type *Supplier* was selected. Enter the delivery time in days.

|*MOV*
|Only visible if the type *Supplier* was selected. MOV stands for minimum order value. Enter the minimum order value in the currency of the system.

|*Owner*
|Select the owner from the drop-down list.

2+|*Sales representative*

|*Country of postcode area sales rep*
|Only visible if the type *Sales representative* was selected. Select a country from the drop-down list that the postcode area of the sales representative refers to. +
*_Tip:_* If a sales representative is working in multiple countries, create one contact data record per country.

|*Postcode area sales rep*
|Only visible if the type *Sales representative* was selected. Enter the sales representative's postcode area. Use commas to separate multiple areas, e.g *33, 34*. The more numbers per postcode area, the more this area is limited.

2+|*Contact options*

|*Type*
|Select the type from the drop-down list. +
All available types are listed in <<table-types-sub-types-contact-options>>.

|*Sub-type*
|Select the sub-type from the drop-down list. +
All available sub-types are listed in <<table-types-sub-types-contact-options>>.

|*Value*
|Enter the value.

2+|*New address*2+|Deactivate the toggle button if you would like to create the address at a later point in time. The explanations about the settings of a new address are described in the <<crm/managing-contacts#600, Adding an address>> chapter.

|====


[.collapseBox]
.*Example:{nbsp}terms of payment with valuta, payment due date, days for early payment discount and percentage for early payment discount*
--
You can use the options *Valuta*, *Payment due date*, *Days for early payment discount* and *Percentage for early payment discount* to set up the following payment conditions:

60 days value date, 30 days net (payment due date), 10 days with a 2 % early payment discount

Explanation: The contact receives a 2% discount if they pay within 10 days. The payment is late after a total of 91 days. When incoming payments are imported and assigned, they are automatically checked internally to see whether the contact's early payment discount is valid. If the early payment discount time period has expired, the order receives the status *Partial payment received*. The terms of payment listed above are automatically applied to the order and e.g. to the <<orders/order-documents/generating-invoices#, invoice>> and can be changed within the order as well. When the invoice is printed, these terms are combined into valid payment conditions for this order. The value date and payment due date are added together to create one date when the payment is due. Despite the value date and payment due date being added together, the following is displayed on an invoice:

Payment conditions: Value date in 60 days, 2% early payment discount if paid within 10 days. Within 30 days due net. If a value for *Value date* is saved for a contact, this value is used for the document. Otherwise, the value saved under *Payment due date* or the value from the customer class is used. The last possibility is to use the number of days entered for the *Payment due date* option for the document. These are set up in the <<orders/order-documents#1300, Optional elements in the stock unit table>> section. Important: These options are only applied to the total gross value of an invoice.

--

[#110.subhead]
Available types and sub-types for the contact options

<<table-types-sub-types-contact-options>> lists all available types and sub-types for the contact options.

[[table-types-sub-types-contact-options]]
.Available types and sub-types for the contact options
[cols="1,3"]
|====
|Type |Sub-type

|Telephone
|Work +
Mobile private +
Mobile work +
Private +
*_Important:_* In order that the telephone number is automatically transferred in the order, the sub-type *Private* must be selected for the type *Telephone*.

|Email
|Work +
Private +
PayPal +
*_Important:_* In order that the email address is automatically transferred in the order, the sub-type *Private* must be selected for the type *Email*.

|Fax
|Work +
Private

|Web page
|Work +
Private

|Marketplace
|eBay +
Amazon

|Identification number
|Klarna +
DHL

|Payment
|PayPal +
Klarna +
Standard

|User name
|Work +
Private +
Forum

|Group
|Forum

|Access
|Guest +
Marketplace partner

|Additional
|Contact person

|Salutation
|Work +
Private

|====

[#150]
=== Creating tags

You can create tags for your contacts, assign them to contacts and filter by tags in the contact overview. Tags are keywords that you can assign to your contacts.

First of all, you have to create the tags in the *Setup » Settings » Tags* menu and activate the option *Contacts* in the *Availability* section. How to create tags is described on the <<basics/working-with-plentymarkets/tags#, Tags>> page of the manual.

[#151]
==== Assigning tags

After you have created the tags in the *Setup » Settings » Tags* menu and activated the option *Contacts* in the Availability section, proceed as described in the following to assign one or multiple tags to a contact.

[.instruction]
Assigning tags:

. Go to *CRM » Contacts*.
. In the *Filter* view, enter the search term in the search field or set the filter options in the drop-down lists. Pay attention to the information given in <<table-filter-contacts>>.
. Click on *Search*. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. In the section *Assigned tags*, enter the tag name.
. Click on the tag name in the list.
. *Save* (icon:save[role="green"]) the settings. +
→ The tag is assigned to the contact and displayed in the section *Assigned tags*.

[TIP]
.Tags for contacts
====
Only those tags can be selected in the contact data record that were created in the *Setup » Settings » Tags* menu for the area *Contacts*.
====

Delete the tag from the contact by clicking the x within the tag.

[#152]
==== Filtering by tags

Filter by tags in order to display all contacts with this tag. You can select one or multiple tags.

[.instruction]
Filtering by tags:

. Go to *CRM » Contacts*.
. Select one or more tags from the *Tags* drop-down list in the *Filter* section.
. Click on *Search*. +
→ The contacts that correspond to the search criteria entered are displayed.

[#200]
=== Searching for a contact

In the *Filter* view, you can search for contacts according to specific criteria. The contacts found are listed in the *Overview* view. The overview currently displays the following information: ID, guest, company, first name, last name, email address, telephone number, number of orders, postcode and country. How you edit contact data is described in the <<crm/managing-contacts#300, Editing a contact>> chapter.

You can also use the quick search to display all data that is saved for a contact including addresses, orders, notes and tickets. Carry out the settings as described in the chapter <<crm/managing-contacts#1705, Using the quick search>>.

[TIP]
.Sending emails directly from the overview
====
Send an email to your contact directly from the contact overview. Click on the email address to automatically open your email programme.
====

In order to search for specific contacts, enter a search term in the search fields or select the drop-down list settings. You can enter multiple search terms into the search fields at one time. This makes your search run quicker and be more accurate.

[.instruction]
Searching for a contact:

. Go to *CRM » Contacts*.
. In the *Filter* view, enter the search term in the search field or set the filter options in the drop-down lists. Pay attention to the information given in <<table-filter-contacts>>.
. Click on *Search*. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens. +
icon:map-signs[] *_Or:_* Open certain areas of the context menu such as *New order* or *New note* with a right click.


[[table-filter-contacts]]
.Filters for contacts
[cols="1,3"]
|====
|Setting |Explanation

|*Search*
|Click on *Search* without selecting any filter settings to display all contacts. +
icon:map-signs[] *_Or:_* Limit the search results by using filters and click on *Search*. +
→ The contacts found are listed in the overview

|*Reset*
|Resets the selected filter criteria.

|*ID*
|Each contact automatically receives a consecutive and unique ID. It doesn't matter if the data record was saved manually or automatically. 2 contacts never have the same ID. The ID is always a real number. "00521" or "ADF8354" e.g. are invalid. 

|*Name*
|Enter the first name and/or last name or the name of the company to search for the contact with this name or company name. The search is also carried out for names and company names that are saved in the address data records of the contact. It is also possible to search only for parts of the name or company name.

|*Contact data*
|In this field, you can search for the name, address, company, customer number and eBay name. +
*_Note:_* In order to search for the eBay name, first enter the parameter *ebay:* of the eBay name that you search for.

|*Address*
|Enter the name of the street and/or the postcode that is saved for the contact. It is also possible to search only for parts of the street and parts of the house number.

|*Postcode*
|Enter the postcode that is saved for the contact. The search is also carried out for postcodes that are saved in the address data records of the contact. It is also possible to search only for parts of the postcode.

|*Town*
|Enter the town that is saved for the contact. The search is also carried out for towns that are saved in the address data records of the contact. It is also possible to search only for parts of the town.

|*Email*
|Enter the complete email address to search for the contact with this email address.

|*Telephone*
|Enter the telephone number to search for the contact with this number. You can also search for parts of the telephone number. Enter at least 3 numbers.

|*Country*
|Select a country to only display contacts from this country. The country is saved within the contact data.

|*Owner*
|Select the owner to only search for contacts that are linked to this owner. The owner must be saved in the contact data record. +
*_Important:_* Only owners for whom the *Customer* option has been activated in the *Owner* tab can be selected from the drop-down list.

|*Type*
|Select the type to only search for contacts with this type.

|*Customer class*
|Select the customer class to only search for contacts with this class.

|*Rating*
|Select the rating to only search for contacts with this rating. 5 yellow stars are the best rating, 5 red stars are the worst rating:

|*Tags*
|Select the tag to only search for contacts with this tag.

|*Client*
|Select a client to only display contacts that correspond to this client. The client is saved within the contact data. +
*_Important:_* Variable users can only select those clients that they have a right to access. Variable users are given rights within the <<basics/admin-tasks/manage-users#90, Right>> tab in the *Setup » Settings » User » Accounts* menu.

|*Referrer*
|Select the referrer to only search for contacts with this referrer.
|====

[#210]
=== Linking the contact to a company

If you have created the contact without linking them to a company, you can link the company afterwards as well. In order to avoid confusion with companies having the same name, the town, street and country of the company are also displayed next to the company name.

Enter at least 3 characters of the company name, town, street or country. Your plentymarkets system suggests company data records that have already been saved.

[.instruction]
Linking the contact to a company:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Enter the name of the company, town, street or country in the entry field of the *Company* section. +
→ Once you have entered 3 characters, company data records that have already been saved are suggested.
. Select the company data record from the drop-down list.
. *Save* (icon:save[role="green"]) the settings. +
→ All company-related data is displayed in the detail view of the contact.

[#220]
=== Creating a company

Create the company and save data such as the VAT number, payment due date and early payment discount as a percentage value.

[.instruction]
Creating a company:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. In the *Company* section, click on *Add new company*. +
→ icon:map-signs[] *_Or:_* Enter the name of the company in the suggestion list and click on *Save*.
. Carry out the settings. Pay attention to the information given in <<table-create-contact>> in the *Company* section.
. *Save* (icon:save[role="green"]) the settings. +
→ The company is created and the detail view of the contact opens.
. *Save* (icon:save[role="green"]) the settings.

[TIP]
.Loading already existing company data records
====
Company data records that have been already saved are only loaded when clicking in the suggestion field once you have entered at least 3 letters of the company name.
====

[#230]
=== Editing the company

If you have edit company data that is already saved, the data of the existing company data record is overwritten.

[.instruction]
Editing the company:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Edit* in the *Company* section.
. Carry out the changes as desired. Pay attention to the information given in <<table-create-contact>> in the *Company* section.
. *Save* (icon:save[role="green"]) the settings. +
→ The data of the edited company is overwritten and the data of the newly created company displayed in the detail view of the contact.

[#240]
=== Deleting the link between company and contact

You can delete the link between the company and the contact in the detail view of the contact. Note that you only delete the link and not the company data itself. The company data is still displayed as a suggestion after you have entered at least 3 characters of the company name, the town, the street or the country.

[.instruction]
Deleting the link between company and contact:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click in the entry field in the *Company* section.
. Select the empty option.
. *Save* (icon:save[role="green"]) the settings. +
→ The link between the company and the contact is deleted.

[#300]
=== Editing a contact

Search the contact by means of the <<crm/managing-contacts#200, filter settings>>. Open the contact by clicking in the line of the contact to edit the contact's data such as the date of birth, telephone number and email address, for example. You find explanations of the settings and options in <<table-create-contact>> in the <<crm/managing-contacts#100, Creating a contact>> chapter. Click on *Delete contact option* to delete the contact options.

[.instruction]
Editing a contact:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens. +
icon:map-signs[] *_Or:_* Open certain areas of the context menu such as *New order* or *New note* with a right click.
. Carry out the changes as desired. Pay attention to the information given in <<table-create-contact>> in the <<crm/managing-contacts#100, Creating a contact>> chapter.
. *Save* (icon:save[role="green"]) the settings.

[#350]
=== Old online store: Converting a guest account into a regular account

If the contact ordered as a guest in your old online store (Callisto online store) and not in the Ceres online store, this account type is saved as contact option in the detail view of the contact. Guest accounts have the value 1. Delete the contact option with the value 1 in order to convert the guest account into a regular account.

Send your customer an email and inform them that the guest account was changed to a regular account. They can then create a password to be able to log into your online store.

[.instruction]
Converting a guest account into a regular account:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. In the *Contact options* section, click in the line of the account type (Type: *Account*, sub-type: *Guest*, value: *1*) on *Delete contact option*.
. *Save* (icon:save[role="green"]) the settings. +
→ The account type is changed from *Guest account* to *Regular account* in the history of the contact.

[NOTE]
.Guest accounts via the Ceres online store can only be found in the quick search
====
In order to be able to work GDPR-compliant, no contact data record is created in case of guest orders via the Ceres online store. Orders that were placed as a guest via a Ceres online store can therefore not be found via the *CRM » Contacts* menu. The data of the guest can only be found via the address data in the *CRM » Quick search* menu. +

Further information about converting Ceres guest orders into regular contact data records can be found in the <<crm/managing-contacts#1705b, Converting a guest account into a contact data record>> chapter.

====

[#400]
=== Deleting a contact

You can delete individual contacts. All addresses that are assigned to the contact are deleted if they are not linked to an order.

[.instruction]
Deleting the contact in the overview:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Open the context menu with a right click in the line of the contact.
. Click on *Delete contact* in the list. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The contact is deleted and removed from the overview.

You can delete the contact also in the detail view. Proceed as described below.

[.instruction]
Deleting the contact in the detail view:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Statistics* on the left side in the context menu. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The contact is deleted and removed from the overview.

[TIP]
.Delete addresses without orders, contacts, POS and warehouses (guest accounts)
====
Go to *Setup » Settings » Data » Cleansing* and determine the time period after which unused addresses are automatically deleted from your plentymarkets system. Unused addresses are those addresses that do not have any relation to a contact, an order, a POS and a warehouse.

For further information about data cleansing, refer to the the <<basics/working-with-plentymarkets/data-cleansing#, Carrying out data cleansing>> page of the manual.
====

[#420]
=== Duplicate check for contact data records with identical email address

When creating new and updating existing contact data records, the email address is checked in order to avoid duplicate entries in the system.

The logic works in the following way:

* When creating a new contact, the system searches for an existing regular contact with identical private email address. If a contact is found, this contact is updated with the new data. If no contact is found, a new regular contact is created.

* When updating the private email address of an existing regular contact, the system searches if another regular contact with the same private email address exists. If this is the case, the private email address of the current contact is not updated. All other data, however, is updated.


[#450]
=== Exporting the vCard

You can export the data of a contact as business card in VCF format.

[.instruction]
Exporting the vCard:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Download contact as vCard*. +
→ A window opens. Select the storage location on your computer.
. The vCard is available at the selected storage location.

[#455]
=== Reloading the contact data record

You can reload the data of the contact data record with one klick.

[.instruction]
Reloading the contact data record:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Reload data*. +
→ The contact data record is reloaded.

[#500]
== Displaying the history

When creating the contact data record, the history of a contact is saved. The history includes e.g. how long the contact has been registered and when they have been logged into your online store for the last time and when the last order was generated. This data is automatically updated and cannot be changed.

[.instruction]
Displaying the history:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens and the history is displayed in the right section below the *contact options*.
. Pay attention to the information about the history given in <<table-history-contact>>.

[[table-history-contact]]
.History in the *CRM » Contacts » Open contact menu*
[cols="1,3"]
|====
|Setting |Explanation

|*Registered since*
|Date and time when the contact has first registered.

|*Updated*
|Date and time when the data record of the contact has been updated for the last time.

|*Account type*
|Account via which the contact has registered. +
*Regular account* = The contact has newly registered in your online store or the data record has been manually created in the back end. +
*Guest account* = The contact has registered and ordered as a guest. +
*_Important:_* If you use Ceres, you can prevent that customer data records are created when guests place an order. To do so, go to *Setup » CRM » Settings* and select the option *Do not create contacts* from the drop-down list *Guest orders*. The option *Create contacts* is selected by default.

|*Last order*
|Date and time when the last order was made. If no order has been placed, *No data* is displayed in this field.

|*Last login*
|Date and time when the contact was logged in for the last time. If the contact was not logged in, *No data* is displayed in this field.
|====

[#510]
== Carrying out the group function

Use the group function to send an email template, print address label or add a contact to a newsletter folder. This can be done simultaneously for one or multiple contacts.

[.instruction]
Carrying out the group function:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click on *Group function*.
. Activate one or multiple procedures and select the options from the drop-down lists. Pay attention to the information given in <<table-contact-group-function>>.
. Activate the contact(s) that you would like to carry out the procedure for.
. Click on *Group function* to carry out the selected procedures for the activated contacts.

[[table-contact-group-function]]
.Group function in the *CRM » Contacts* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Print address label*
|Prints the label selected from the drop-down list for all activated contacts. +
*_Important:_* The address label template must have been <<fulfilment/generating-documents#address-label-template, created>> in the *Setup » Orders » Documents » Address label* menu beforehand. Whether the primary invoice address or the primary delivery address of the contact is printed, depends on the setting in the address label template.


|*Send email template*
|Sends the template selected from the drop-down list to all activated contacts. +
*_Important:_* The email template must have been <<crm/sending-emails#1200, created>> in the *Setup » Client » Select client » Email » Templates* menu beforehand.

|*Add to newsletter folder*
|Copies the email addresses of the activated contacts to the email folder selected from the drop-down list. The email addresses are listed in the *Setup » CRM » Newsletter » plentymarkets » Email folder* menu.

|*Save payment due date*
|Saves the entered payment due date in the contact data record of all activated contacts. +
*_Note:_* If you activate this option and do not enter a value, the saved values are deleted for the activated contacts.

|====

[#590]
== Managing addresses

In the following sub-chapters, you learn how to add new addresses for your contact, display all addresses that are saved for the contact as well as edit and delete existing addresses.

[#600]
=== Adding an address

You can add as many addresses and as address options as you like. An address option is, for example, the telephone number of the contact.

This chapter explains how to add addresses to an already existing contact data record. How to add an address directly when creating a new contact data record is described in the <<crm/managing-contacts#100, Creating a contact>> chapter.

[.instruction]
Adding an address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *New address* on the left side in the context menu.
. Carry out the settings in the *New address* section. Pay attention to the information given in <<table-add-address>>.
. In the *Address options* section, select the type from the drop-down list and enter the value. Pay attention to the information given in <<table-add-address>>. +
→ By clicking on *Add address option*, you can add further address options.
. *Save* (icon:save[role="green"]) the settings. +
→ The address is added to the overview in the *Addresses* section.

[[table-add-address]]
.Adding an address
[cols="1,3"]
|====
|Setting |Explanation

2+|*New address*

|*Invoice address* / *Delivery address*
|Activate one or both options in order to determine the address type. +
The new address can either be the invoice address only, the delivery address only or both the invoice address and the delivery address. If both options are activated, an address with a new ID and 2 address types is created. +
If one ore both options are activated, you can select for one or both options if the address is the primary address.

|*Primary*
|Activate the option if the new address is the primary invoice address or the primary delivery address. +
It is possible to activate both options if the new address is the primary invoice address as well as the primary delivery address.

|*Form of address*
|Select the form of address from the drop-down list, if required.

|*Name 1 (Company)*
|Enter the company name. This is a mandatory field when there is no entry under *First name* and *Last name*.

|*Name 2 (First name)*
|Enter the first name of the contact. This a mandatory field when there is no entry under *Company* and *Last name*.

|*Name 3 (Last name)*
|Enter the last name of the contact. This is a mandatory field when there is no entry under *Company* and *First name*.

|*Name 4 (Additional information)*
|Enter additional information, e.g. c/o Mr. John Doe, if required.

|*Address 1 (Street)* +
*Address 2 (House number)*
| Enter the street and house number. +
*Street* is a mandatory field when there is no entry under *House number* and *Additional address information*. *House number* is a mandatory field when there is no entry under *Street* and *Additional address information*.

|*Address 3 (Additional address information)*
|Enter additional address information, e.g. apartment 12a, if required. This is a mandatory field when there is no entry under *Street* and *House number*.

|*Address 4 (Free)*
|This field can be freely used.

|*Postcode* +
*Town*
|Enter the postcode and town of the contact, if available. *Town* is a mandatory field. +
This data is used for the invoice address, for example. The order of the options *Postcode* and *Town* is reversed for certain countries, e.g. Germany.

|*Country* +
*Region/County*
|Select the values from the drop-down list. +
*_Important:_* The drop-down list *Region/County* is not available for all countries.

2+|*Address options (optional)*

|*Type*
|Select the type from the drop-down list and enter values for the pre-selected options *Email* and *Telephone*. +
*_Note:_* The types *Email* and *Telephone* are statically displayed. Further available types in the drop-down list: VAT number, External address ID, Entry certificate, Post number, Personal ID, BBFC, Birthday, Title, Contact person.

|*Value*
|Enter the value.
|====

[#700]
=== Displaying addresses

From the open contact, you can display all addresses that are saved for the contact. Besides the ID, company name, first and last name as well as address and country, you can see the address type – invoice address or delivery address – and whether the address is a primary address or not.

If multiple addresses are open, the IDs of the addresses are also displayed in the drop-down list of the open address data records.

Initially, the addresses of your contact are displayed in card view. By clicking on *Switch to table view*, the addresses are displayed in a table. Your plentymarkets system recognises which of the 2 views you selected. When opening the context menu *Addresses* the next time, the view that was selected last is displayed.

Up to 25 address data records saved for the contact are displayed per page. If more than 25 addresses are saved for the contact, you can use the toolbar to browse between the pages, select a certain page and to change the number of address data records per page to 50, 75 or 100. Your plentymarkets system recognises the number of address data records you selected per page. When opening the view *Addresses* the next time, the setting that was selected last is displayed.

[.instruction]
Displaying addresses:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Addresses* on the left side in the context menu. +
→ All addresses that are saved for the contact are displayed.
. Click on *Edit* in order to open the detail view of the address. +
→ If you selected the table view, click in the line of the address in order to open the detail view.

[#800]
=== Editing the address

You can edit addresses as well as address options at any time. Pay attention to the information given in the <<crm/managing-contacts#600, Adding an address>> chapter. Click on *Delete address option* to delete the address options.

[.instruction]
Editing the address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Addresses* on the left side in the context menu. +
→ All addresses that are saved for the contact are initially displayed as cards.
. Click on *Edit* in the address card that you want to edit. +
→ The detail view of the address opens.
. Carry out the changes as desired. Pay attention to the information given in <<table-add-address>> in the <<crm/managing-contacts#700, Adding an address>> chapter as well as to the information about the toolbar given in <<table-edit-address>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-edit-address]]
.Editing the address
[cols="1,3"]
|====
|Setting |Explanation

|*Save*
|Saves the settings.

2+|*Invoice address*

|*Derive new invoice address*
|Creates a new invoice address based on the currently selected address. In order to create a new address with a new ID, changes must be made to the data of the new invoice address.

|*Add invoice address type*
|Adds the *Invoice address* type to the address. The ID does not change. +
If the type *Invoice address* has already been added for the address, this option is not visible.

|*Delete invoice address type*
|Deletes the *Invoice address* type from the address. +
If the type *Invoice address* has not been added for the address, this option is not visible.

|*Define as primary invoice address*
|The currently selected invoice address is defined as primary invoice address. The ID does not change. +
If the *Invoice address* type is not selected, this option is deactivated. +
If the invoice address has been defined as primary, this can be undone by clicking on *Reset primary invoice address*.

|*Convert to invoice address* / +
*Convert to delivery address*
|Converts the currently selected address to an invoice address or a delivery address. The ID does not change. +
If both address types are selected, this option is deactivated.

2+|*Delivery address*

|*Derive new delivery address*
|Creates a new delivery address based on the currently selected address. In order to create a new address with a new ID, changes must be made to the data of the new delivery address.

|*Add delivery address type*
|Adds the *Delivery address* type to the address. The ID does not change. +
If the type *Delivery address* has already been added for the address, this option is not visible.

|*Delete delivery address type*
|Deletes the *Delivery address* type from the address. +
If the type *Delivery address* has not been added for the address, this option is not visible.

|*Define as primary delivery address*
|The currently selected delivery address is defined as primary delivery address. The ID does not change. +
If the *Delivery address* type is not selected, this option is deactivated. +
If the delivery address has been defined as primary, this setting can be undone by clicking on *Reset primary delivery address*.

|*Delete address data record*
|Completely deletes the address data record.
|====

[#900]
=== Deleting an address

If the address is not an invoice address that is linked to an order, you may delete the address. This may be necessary, if the delivery address of the contact is outdated, for example.

[NOTE]
.Deleting invoice addresses that are linked to an order is not possible
====
If the address is of the type *Invoice address* and if it is linked to an order, you cannot delete the address. An error message is displayed.
====

[.instruction]
Deleting an address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Addresses* on the left side in the context menu. +
→ All addresses that are saved for the contact are initially displayed as cards. +
. Click on *Delete* in the address card that you want to delete. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The address is deleted and removed from the overview.

[#990]
== Managing orders

In the following sub-chapters, you learn how to display all orders that are available for the contact as well as create new orders for your contact.

[#1000]
=== Displaying orders

Within the open contact, you can access an overview of all orders of the contact.

[.instruction]
Displaying orders:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Orders* on the left side in the context menu. +
→ All orders that are saved for the contact are displayed. Determine via the pagination whether 25, 50, 100 or 250 orders are displayed.
. Click in the line of the order to open the order in the *Orders » Edit orders* menu and display further information about the order.

You can also edit the order. Orders can be edited as long as no document has been generated for this order. Further information about orders can be found on the <<orders/managing-orders#, Managing orders>> page of the manual.

[#1100]
=== Creating an order

Within the open contact, you can create a new order for the contact with only one click. If the contact has ordered in your online store, the order is automatically saved in your plentymarkets system. In case of orders via telephone, for example, you create the order manually. Proceed as described below.

[.instruction]
Creating an order:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *New order* on the left side in the context menu. +
→ You directly access the *New order* section in the *Orders » Edit orders* menu. +
. Carry out the settings. Pay attention to the information given on the <<orders/managing-orders#, Managing orders>> page of the manual.
. *Save* (icon:save[role="green"]) the settings.

[#1110]
=== Creating a multi-order

The Multi-order function makes it possible for you to take all of the unpaid orders that belong to a contact and then compile them into one multi-order. This might be useful if you have agreed upon with your contact that they do not pay each invoice individually, but pay all invoices per month or per quarter, for example.

As usual, the orders are processed and the items are sent, but left unpaid. Creating a multi-order is only possible for orders that have not been paid yet.

Click on *New multi-order* to summarise all orders of the contact into one multi-order. Beforehand, you determine which conditions such as the order type and the order status must be fulfilled to allow for a multi-order to be created. Carry out this setting in the *Setup » Orders » Order types » Multi-order* menu.

[.instruction]
Creating a multi-order:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *New Multi-order* on the left side in the context menu. +
→ The multi-order is created.

After you have successfully created the multi-order, the multi-order opens automatically in the *Orders* menu. Open the *Receipts* tab in the multi-order to create a multi-invoice.

For further information, refer to the <<orders/managing-orders#800, multi-orders>> page of the manual.

[#1150]
== Displaying the scheduler

In the *Scheduler* view, subscription orders of the contact are displayed. Moreover, you can create new scheduled orders here. The scheduler allows your customers to subscribe to certain items in your online store. The menu is only visible in your plentymarkets system if you booked it. Go to *Start » Service centre » Tab: Systems » Tab: Contract* to book the scheduler. Go to *Setup » Orders » Scheduler* to carry out the settings for your online store.

[.instruction]
Displaying the scheduler:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Scheduler* on the left side in the context menu. +
→ All scheduler orders that are saved for the contact are displayed.
. Pay attention to the explanations on the <<orders/scheduler#, Scheduler>> page of the manual.

For further information, refer to the <<orders/scheduler#, Scheduler>> page of the manual. The filter options are also described there. You can use the filter options both in the *CRM » Contact » Open contact » Tab: Scheduler* menu and in the *Orders » Scheduler » Scheduled orders* menu.


[#1190]
== Managing tickets

In the following sub-chapters, you learn how to create tickets and display all tickets that are available for your contact. Depending on which plentymarkets tariff you use, you may have to book the ticket system before you are able to use it.

[#1200]
=== Creating a ticket

Use the <<crm/using-the-ticket-system#, ticket system>> in plentymarkets to manage your customer communication. The following chapter explains how you can create a new ticket directly from the open contact.

[.instruction]
Creating a ticket:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *New ticket* on the left side in the context menu. +
→ You directly access the *New ticket* section in the *CRM » Ticket system* menu. The contact ID is already pre-filled. +
. Carry out the settings. Pay attention to the information given on the <<crm/using-the-ticket-system#1600, Using the ticket system>> page of the manual.
. *Save* (icon:save[role="green"]) the settings.

[#1300]
=== Displaying tickets

From the open contact, you can display all tickets that are saved for the contact.

[.instruction]
Displaying tickets:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Tickets* on the left side in the context menu. +
→ All tickets that are saved for the contact are displayed. Determine via the pagination whether 10, 25, 50 or 100 tickets are displayed.
. Click in the line of the ticket to open the ticket in the *CRM » Ticket system* menu and display further information about the ticket.

You have the possibility to edit and delete tickets. For further information, refer to the <<crm/using-the-ticket-system#, Using the ticket system>> page of the manual.

[#1390]
== Managing notes

In the following sub-chapters, you learn how to create new notes for your contact, display all notes that are available for your contact as well as edit and delete existing notes. Notes are only visible in your plentymarkets back end and cannot be accessed by your contacts.

[#1400]
=== Creating a note

You can save as many notes for your contacts as you like. Notes are only visible in your plentymarkets back end. This means that contacts cannot see the saved notes in your online store. Each note automatically receives a consecutive and unique ID. New texts can be entered by typing them in or by inserting them using the clipboard. Use the functions in the toolbar to format the text, insert links and upload image files.

[.instruction]
Creating a note:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Open the context menu with a right click in the line of the contact.
. Click on *New note*. +
. icon:map-signs[] *_Or:_* Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *New note* on the left side in the context menu. +
→ The *New note* window opens.
. Enter the text, insert text via the clipboard and format the text using the functions in the toolbar.
. *Save* (icon:save[role="green"]) the settings. +
→ The *Notes* section opens and the note is added to the overview.

[#1500]
=== Displaying notes

From the open contact, you can display all notes that are saved for the contact in form of cards. The cards show the creation date with timestamp, the name of the user that created the note as well as the ID.

[.instruction]
Displaying notes:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Notes* on the left side in the context menu. +
→ All notes that are saved for the contact are displayed.

[.subhead]
Opening an individual note

You can open individual notes by clicking on *Open preview*. When more than one note of the contact is open, an arrow is displayed in the view. Click on the arrow to quickly and easily switch between the open notes. Click on the cross to close the note and remove it from the list.

[#1600]
=== Editing a note

Edit notes to update contents. You can format the text, insert links and upload image files.

[.instruction]
Editing a note:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Notes* on the left side in the context menu. +
→ All notes that are saved for the contact are displayed.
. Click on *Edit* in the card of the note that you want to edit.
. Carry out the changes as desired.
. *Save* (icon:save[role="green"]) the settings.

[#1700]
=== Deleting a note

The notes for your contacts can be deleted if the information saved in the notes is outdated or if you do not need it any longer.

[.instruction]
Deleting a note:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Notes* on the left side in the context menu. +
→ All notes that are saved for the contact are displayed.
. Click on *Delete* in the card of the note that you want to delete. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The note is deleted and removed from the overview.

You can also delete the note when the preview is open. Click on *Delete* in the open note. In this case, a window opens and you need to confirm your decision by clicking on *Delete*.

[#1710]
== Managing documents

In the following sub-chapters, you learn how to upload, display, download and delete documents. The documents that you have uploaded in this menu are only visible in your plentymarkets back end and cannot be accessed by your contacts.

[#1720]
=== Uploading customer documents

In the *Documents* view, you can upload documents that relate to your contact. For example, this document could be an age check that you have performed before sending items to the contact for the first time. Either you upload the files by clicking on *Upload file* or via the drag & drop function. You can also create folders to group documents in a clearly structured way.

You can upload the data formats JPEG, PNG, GIF, TIFF, PDF, DOC, ODC, OTH, XLS, XML, HTML, HTM, CSS, ZIP and GZIP.

[.instruction]
Uploading customer documents:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Documents* on the left side in the context menu.
. Click on *Upload files*.
. Select the documents.
. Click on *Open* to upload the file or add the documents to the tab with the drag and drop function.

[NOTE]
.Creating a folder
====
Create folders in the *Folder* area if you have already uploaded or plan to upload a lot of files about your contact. This allows to group the documents and have a better overview.
====

[#1730]
=== Displaying documents

In the *Documents* view, you see all documents related to the contact that you have uploaded. In the overview, you can see the file name, the size of the file as well as the date and the time of the last change.

[.instruction]
Displaying documents:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Documents* on the left side in the context menu. +
→ All documents that are saved for the contact are displayed.

[#1740]
=== Downloading a document

You can download all files that you have uploaded for the contact.

[.instruction]
Downloading a document:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Documents* on the left side in the context menu. +
→ All documents that are saved for the contact are displayed.
. Click on *Download* in the line of the document that you want to download. +
→ *_Note:_* Some browsers save the file automatically in the download folder that you have determined before. For other browsers, you download the file with a click. In this case, follow the instructions on your computer. Pay attention that these instructions may vary depending on the browser and programme used.

[#1750]
=== Deleting a document

If you do not need a document any longer, you can delete the document. How to delete multiple documents at the same time is described in the box at the end of this chapter.

[.instruction]
Deleting a document:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Documents* on the left side in the context menu.
. Click on *Delete* in the line of the document that you want to delete. +
→ A window opens and you need to confirm your decision. +
. Click on *Delete*. +
→ The document is deleted and removed from the overview.

[TIP]
.Deleting multiple documents or all documents
====
In the *Documents* view, activate the documents that you want to delete or activate the option next to *File name* to activate all documents and save them afterwards. After you have confirmed your decision by clicking on *Delete*, the activated documents are deleted and removed from the overview.
====

[#1800]
== Displaying the account balance

The *Account* view lists the revenues of your contacts. In the top line, you see the total of the contact's invoices, the amount granted to your customer in form of credit notes and the difference between the 2 amounts. Orders and credit notes are listed as processes in the table. The *Paid* and *Outstanding* columns are especially helpful. If a payment for an order is listed in the *Outstanding* column, the contact still has to pay the amount. As soon as the contact has paid, the amount is listed under *Paid*. If a payment for a credit note is listed in the *Outstanding* column, you still have to pay this amount to the contact. As soon as you have paid, the amount is listed under *Paid*.

[.instruction]
Displaying the account balance:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Account* on the left side in the context menu. +
→ All data that is available for the account of the contact is displayed.
. Pay attention to the information given in <<table-account-balance-contact>>.

[[table-account-balance-contact]]
.Settings in the *CRM » Contacts » Open contact » View: Account*
[cols="1,3"]
|====
|Setting |Explanation

|*Balance*
|Shows the customer's account balance. +
*+* = total of the contact's outstanding payments +
*-* = total of payments that still have to be paid to the contact if the contact has paid too much or if a credit note still has to be paid out. +
*0.0* = No outstanding amounts

|*Invoices*
|Total invoice amounts of all orders and the number of invoices in parentheses

|*Credit notes*
|Total of all credit notes and the number of credit notes in parentheses

|*Delta*
|Difference in percent between the paid credit notes and the total invoice amount paid by the customer. 0 % means that no credit note has been paid out to the customer yet. 100 % means that every amount paid by the customer has been paid back in form of credit notes.

|*Date*
|Date when the order was created

|*Order ID*
|ID of the order. Click on the ID to open the detailed view of the order. Credit note IDs are indented and displayed under the order.

|*Event*
|Type of order, either order or credit note

|*Document*
|Document number, e.g. invoice number. Click on the number to open the document.

|*Value*
|Invoice total of the order

|*Paid*
|Amount already paid

|*Payment method*
|Payment method for the order

|*Outstanding*
|Remaining amount that is due before the order is completely paid for.

|*Status*
|Status of the order. Click on the status to open the editing window *Order status* and change the status, if required.

|====

[.subhead]
Filtering account data

Use filters to display the account data of your contact.

[.instruction]
Filtering account data:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Account* on the left side in the context menu. +
→ All data that is available for the account of the contact is displayed.
. Carry out the settings in the *Filter* sections. Pay attention to the information given in <<table-filter-account-data>>.
. Click on *Search*.

[[table-filter-account-data]]
.Filter settings in the *CRM » Contacts » Open contact » View: Account*
[cols="1,3"]
|====
|Setting |Explanation

|*Search*
|Perform a search. The account data that corresponds to the search criteria entered is displayed.

|*Reset*
|Resets the selected filter criteria.

|*Period*
|Select one of the following settings from the drop-down list: *ALL*, *This year*, *Last year*, *This month*, *Last month* or *Last 3 months*.

|*Outstanding*
|Select *ALL*, *Yes* or *No*. +
*Yes* = Only outstanding amounts are displayed. +
*No* = Only paid amounts are displayed. +
*ALL* = Outstanding and paid amounts are displayed.

|*Relational operator / Status*
|Select the relational operator and order status from the drop-down lists.

|*Invoice No.*
|Enter the invoice number.

|*Order ID*
|Enter the order ID.

|====

[#1890]
== Managing bank details

In the following sub-chapters, you learn how to add new bank details for your contact as well as edit and delete existing bank details.

[#1900]
=== Adding bank details

In the *Bank details* view, you can add the bank details of your contact. Add as many bank data records as you like.

After saving, the bank details are displayed as cards. Beside the name of the holder and the IBAN, a tag is displayed that shows whether the SEPA direct debit mandate is activated for the contact. If the BIC is saved in the bank details, this is also shown on the card.

[.instruction]
Adding bank details:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Bank details* on the left side in the context menu.
. Click on *Add*. +
→ The *New bank details* view are displayed.
. Carry out the settings. Pay attention to the information given in <<table-bank-data-contact>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-bank-data-contact]]
.Settings in the *CRM » Contacts » Open contact » View: Bank details*
[cols="1,3"]
|====
|Setting |Explanation

|*IBAN*, *BIC*, *Holder*, *Account number*, *Bank code*
|Enter the bank details of the contact. *IBAN* and *Holder* are mandatory fields.

|*Name, street, postcode and town of the bank*
|Enter the name and address of the bank.

|*Country of the bank*
|Select the country from the drop-down list.

|*SEPA direct debit mandate*
|Activate this option once the contact has signed the SEPA direct debit mandate. +
*_Important:_* This option needs to be activated before pain.008 formats can be retrieved for <<payment/managing-bank-details#200, SEPA payments>>.

|*SEPA direct debit mandate granted on*
|Only visible when the option *SEPA direct debit mandate* has been activated. +
The date when the contact agreed upon the SEPA direct debit mandate is displayed. Or select the date from the calendar.

|*Type of mandate*
|Only visible when the option *SEPA direct debit mandate* has been activated. +
Select an option from the drop-down list: +
*SEPA core direct debit* = Allows a biller to collect funds from a payer's account, provided that a signed mandate has been granted by the payer to the biller. +
*SEPA business to business direct debit* = Enables business customers in the role of payers to make payments by direct debit.

|*Payment frequency*
|Only visible when the option *SEPA direct debit mandate* has been activated. +
Select an option from the drop-down list: +
*One-time payment* = Is typically used for standard orders. +
*Recurring payment* = Is typically used for regularly occurring orders such as subscription orders, etc.
|====

[#2000]
=== Editing bank details

You can update the bank details of your contact at any time.

[.instruction]
Editing bank details:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Bank details* on the left side in the context menu.
. Click on *Edit* in the card of the bank details that you want to edit. +
→ The data record opens.
. Carry out the settings. Pay attention to the information given in <<table-bank-data-contact>>.
. *Save* (icon:save[role="green"]) the settings.

[#2100]
=== Deleting bank details

Delete the bank details of your contact if the data is outdated.

[.instruction]
Deleting bank details:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Bank details* on the left side in the context menu.
. Click on *Delete* in the card of the data record that you want to delete. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The bank details are deleted and removed from the overview.

[#2200]
== Managing events

In the following sub-chapters, you learn how to add, display and delete contact events. If you want your contact to pay for a certain event, it is also possible to bill those events.

[#2300]
=== Adding an event

Add as many events as you like. For example, the event can be a call or an email. You can enter a duration, select information about the process and enter a comment about the event into the text field. If you would like to bill the event, click on *Add and bill* when adding the event.

[.instruction]
Adding an event:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Events* on the left side in the context menu.
. Select the type from the drop-down list.
. Enter the duration of the event in minutes.
. Select the info from the drop-down list.
. Enter the info text.
. Click on *Add event*. +
→ Select *Add and bill* or *Add*. The event is added to the list.

[#2400]
=== Displaying events

You can display the events that you have saved for your contacts at any time.

It is also possible to update the duration of the event directly in the overview. How to update the duration is described in the box at the end of this chapter.

[.instruction]
Displaying events:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Events* on the left side in the context menu. +
→ A list of the events is displayed.

[TIP]
.Updating the duration of an event
====
You can update the duration of existing events. To do so, click on *Update duration* in the *Events* area of the contact data record. The window *Update event duration* opens. Enter the new number in minutes and click on *Update*.
====

[#2500]
=== Deleting an event

Delete events that you no longer need.

[.instruction]
Deleting an event:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Events* on the left side in the context menu. +
→ A list of the events is displayed.
. Click on *Delete* in the line of the event that you want to delete. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The event is deleted and removed from the overview.

[#2600]
== Editing login details

In the *Login details* view, you can manually change the password for your contact, send a link to your contact to change the password, unblock the login and open the My account area of the contact using the login URL.

[#2700]
=== Changing the password

Manually change the password for your contact in the *Change password* section.

[.instruction]
Changing the password:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Login details* on the left side in the context menu.
. Enter the password in the *Change password* section.
. Click on *Save password*.


[#2750]
=== Generating new passwords for all customers

Go to *Setup » CRM » Passwords* to generate new password for your customers. This can be necessary, e.g., if someone hacked into your plentymarkets system or if you are the victim of data theft.

[TIP]
.Emails with newly generated passwords are not sent automatically
====
Note that your contacts do not receive the newly generated passwords or any other information automatically. You have to e.g. actively send your contacts an email informing them about the current situation and encouraging them to change their passwords in the My account area of your online store.
====

Proceed as follows to generate new passwords for all of your customers.

[.instruction]
Generating new passwords for all customers:

. Go to *Setup » CRM » Passwords*.
. Click on *Generate new passwords for all customers*. +
→ The new passwords are generated.

[#2800]
=== Sending a link to change password

Send your contact an email template containing a link in order that he or she can change the password in your online store. It is required that you have linked an email template containing the template function *{% Link_ChangePassword() %}* to change the password with the event *Send customer email to change password*. Carry out this setting in the *Setup » Client » Select client » Email » Automatic* menu.

For further information about sending emails automatically, refer to the <<crm/sending-emails#2300, Sending emails>> page of the manual.

[.instruction]
Sending a link to change password:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Login details* on the left side in the context menu.
. Click on *Send link to change password*. +
→ The contact receives an email containing the link to change the password in your online store.

[#2900]
=== Unblocking the login

Once your contact has entered the incorrect password in your online store several times in succession, the login is blocked for the contact for a certain time. By clicking on *Unblock login*, you unblock the login and your contact is able to log into the your online store again.

[.instruction]
Unblocking the login:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Login details* on the left side in the context menu.
. Click on *Unblock login*. +
→ The contact is now able to log into your online store.

[#3000]
=== Opening the My account area of the contact

In the *Login URL* area, you can see the URL for directly accessing the contact's My account area in the online store. If you use this URL, you are no longer required to enter login details (email address and password) in the online store.

In order that the login URL is automatically created, both the email address in the *Contact options* area of the *CRM » Contacts » Open contact* menu and the password in the *CRM » Contacts » Open contact » View: Login details* must be saved. The login URL is generated after the data has been saved. Make sure to use a secure password. Otherwise an error message is displayed.

[.instruction]
Opening the My account area of the contact:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Login details* on the left side in the context menu.
. Click on *Open link* in the *Login URL* section or copy the login URL to the clipboard by clicking on *Copy to clipboard* and insert the link into the browser. +
→ The My account area of the contact in the online store opens.

[#3100]
== Managing commissions

In the *Item commissions* tab, you can save item-specific commissions for the customer type *Sales representative*. Proceed as described below to enter values for commissions.

[.instruction]
Saving a commission:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Commission & Cost units* on the left side in the context menu.
. Open the *Commissions* tab.
. Open the *Commissions* tab.
. Expand the *New commission* area.
. Enter the *item ID* of the item that you wish to save one or more commission(s) for.
. Enter the commission(s) in percent. +
→ Enter up to 4 commissions per entry.
. *Save* (icon:save[role="green"]) the settings. +
→ The commission is saved. The name matching the item ID is displayed. This way you recognise the corresponding item right away. The name is displayed after you have reloaded by clicking on the *Settings* tab.

[#3200]
== Managing cost units

Create cost units in the *Cost units* area. You also have the possibility of editing cost units here. A cost unit, also known as a cost centre, is part of an organisation that does not produce direct profit and adds to the cost of running a company.

[.instruction]
Creating a cost unit:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Commission & Cost units* on the left side in the context menu.
. Click on the *New cost unit* tab.
. Enter the name, the budget and the remaining budget.
. Select the year or the month as budget period.
. *Save* (icon:save[role="green"]) the settings. +
→ The cost unit is added to the overview.

[#3300]
== Creating a statistic

Create customer-specific statistics in the *Statistics* area. This allows you to analyse data related to the contact and display this data as a statistic. For example, you could create a statistic that shows the contact's total revenue development during a particular time period. You can also edit existing statistics in this area. For further information, refer to the <<basics/statistics/managing-statistics#100, Customer statistics>> chapter.

[.instruction]
Creating a statistic:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.
. Click on *Statistics* on the left side in the context menu.
. Click on *New sheet*.
. Enter a name.
. *Save* (icon:save[role="green"]) the settings. +
→ A tab with the name that you have just entered is displayed.
. Click on *Add*. +
→ The *New statistic* window opens.
. Select the type of statistic from the drop-down list.
. *Save* (icon:save[role="green"]) the settings. +
→ The data is loaded and displayed.

Depending on which type of statistic you selected, you find further information in the following chapters of the <<basics/statistics/managing-statistics#, Managing statistics>> page of the manual:

* <<basics/statistics/managing-statistics#20, Total revenue development>>
* <<basics/statistics/managing-statistics#100, Revenue by category>>
* <<basics/statistics/managing-statistics#100, revenue by order referrer>>

For further information about how to edit statistics, for example, refer to the <<basics/statistics/managing-statistics#, Managing statistics>> page of the manual.


[#4000]
== Managing properties

Properties are frequently occurring information that you can use in different areas of plentymarkets. Properties are centrally managed in the *Setup » Settings » Properties » Configuration* menu.





[WARNING]
.Important notes about the contact properties
====
Note that contact properties in the *CRM » Contacts » Open contact » View: Properties* menu are only available in a short while. The properties can then be added and displayed in the plentymarkets back end only. That means that it is not possible for the contact to save data in your online store, e.g. during the order process or when they register in your online store. This functionality is currently being developed.

You can, however, already create properties in the *Setup » Settings » Properties » Configuration* menu and also add values for the properties.

*_Important:_* A migration is planned for the properties that you created in the past in the *Setup » CRM » Properties (deprecated)* menu. That means that you do not have to transfer these properties to the new *Setup » Settings » Properties » Configuration* menu. Please keep an eye on the link:https://forum.plentymarkets.com/c/changelog[Changelog^] category of the plentymarkets forum where we will inform you about the time when the migration takes place.

====

[#4100]
=== Creating a property

Go to *Setup » Settings » Properties » Configuration* to create properties that you will later use for characterising your contacts.

//There are 2 possibilities for using the properties later:



Proceed as described below to create a property.

[.instruction]
Creating a property:

. Go to *Setup » Settings » Properties » Configuration*. +
→ The overview of the properties opens.
. Click on *Add property*.
. In the drop-down list *Section*, select the option *Items*.
. Carry out the additional settings. Pay attention to the information given in <<table-create-property>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The property is created and opened for editing.

[[table-create-property]]
.Creating properties
[cols="1,3"]
|====
|Setting |Explanation

|*Section*
|Select a section from the drop-down list where the property should be used. +
*Items* = Property is used for items. +
*Contact* = Property is used for contacts. +
*Storage location* = Property is used for storage locations. +

|*Property type*
|Select the property type from the drop-down list. +
*None* = No property type +
*Whole number* = Allows to enter a whole number. +
*Decimal number* = Allows to enter a number with decimal places. +
*Selection* = Allows to select multiple options. +
*Short text* = Enter short text. +
  +
*Text* = Enter text. +
  +
*Date* = Allows to enter a date. +


|*Name*
|Enter the name for the property. +
  +
*_Note:_* The name of the system language is displayed by default. After the property has been created, you can save the name in English. Further languages are planned.

|*Description*
|Enter the description of the property. +
*_Note:_* The description of the system language is displayed by default. After the property has been created, you can save the description in English. Further languages are planned.

|*Group*
|Select a property group from the drop-down list to assign the property to this group. This is optional. +
*_Tip:_* Click on *Add property group* to create a group.

|*Position*
|Enter the position number for the property. Properties are sorted by the position number in ascending order. +
*_Tip:_* Count by tens when creating position numbers. This allows you to easily add new properties in between.
|====

[#4200]
=== Editing a property

Properties are centrally managed in the *Setup » Settings » Properties » Configuration* menu. Change the settings that are described in <<table-create-property>> in this menu.

[.instruction]
Editing a property:

. Go to *Setup » Settings » Properties » Configuration*.
. Click on *Search* to display all properties or select filters to limit the search results.
. Click on the property. +
→ The *General* tab opens.
. Edit the settings. Pay attention to the information given in <<table-edit-property>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-edit-property]]
.Editing a property
[cols="1,3"]
|====
|Setting |Explanation

2+|*General*

|*Position*
|Enter the new position to change the order of the properties.

|*Mandatory field* (currently without function)
|Activate this option to make sure that the property is a mandatory entry. Mandatory fields are displayed in bold in the detail view of the contact in the *Properties* section and in the order process. +
*_Note:_* This setting is currently without function.

|*Order process* (currently without function)
|Activate this option to make sure that the property is displayed in the order process. +
*_Note:_* This setting is currently without function.

|*Customer registration* (currently without function)
|Activate this option to make sure that the property is displayed in the customer registration. +
*_Note:_* This setting is currently without function.

|*Name*; +
*Description*
|For multilingualism, enter name and description for other languages. +
*_Note:_* Currently, names and descriptions can only be saved in German and English. Further languages are planned.

2+|*Visibility*

|*Client*
|Select one ore multiple clients that the property should be activated for.

|*Visibility*
|Select one or more types that the property should be visible for.

2+|*Values*

|Only visible for property type *Selection*
|Enter the values that should be displayed in the drop-down list. +
Click on *Add value* to create a value. +
*Name* = Enter a name for the property value.
|====

[#4300]
=== Searching for a property

Properties are centrally managed in the *Setup » Settings » Properties » Configuration* menu. After opening the menu, start the search to display the properties. In order to search for specific properties, enter a search term in the search fields. The drop-down lists help you search for properties that share specific criteria. You can combine as many search filters as you like.

[.instruction]
Searching for a property:

. Go to *Setup » Settings » Properties » Configuration*.
. In the *Filter* view, enter the search term in the search field or set the filter options in the drop-down lists. Pay attention to the information given in <<table-filter-properties>>.
. Click on *Search*. +
→ The properties that correspond to the search criteria entered are displayed.
. Click in the line of the property. +
→ The detail view of the property opens.

[[table-filter-properties]]
.Filters for the properties
[cols="1,3"]
|====
|Setting |Explanation

|*Search*
|Click on *Search* without selecting any filter settings to display all properties. +
icon:map-signs[] *_Or:_* Limit the search results by using filters and click on *Search*. +
→ The properties found are listed in the overview.

|*Reset*
|Resets the selected filter criteria.

|*ID*
|Each property automatically receives a consecutive and unique ID.

|*Name*
|Enter the name to search for the property with this name. It is also possible to search only for parts of the name.

|*Language*
|Select a language to only display properties for which a name has been saved in this language.

|*Group*
|Select the group to only display properties that are assigned to this group. +
Select *Not grouped* to only display properties that are not assigned to a group. +
Select *Grouped* to only display properties that are assigned to a group.

|*Section*
|Select a section to only display properties that are used in this section.

|*Property type*
|Select a property type to only display properties of this type.
|====

[#4400]
=== Deleting a property

You can delete one or more properties at the same time.

[#4500]
==== Deleting a property

Proceed as described below to irreversibly delete a property if it is no longer needed.

[.instruction]
Deleting a property:

. Go to *Setup » Settings » Properties » Configuration*.
. Start the search. +
→ If required, select filters to limit the search results.
. Click on the property. +
→ The detail view of the property opens.
. Click on *Delete property*. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The property is deleted and removed from the overview.

[#4600]
==== Deleting multiple properties

Proceed as described below to irreversibly delete multiple properties if they are no longer needed.

[.instruction]
Deleting multiple properties:

. Go to *Setup » Settings » Properties » Configuration*.
. Start the search. +
→ If required, select filters to limit the search results.
. Activate the properties that you want to delete.
. Click on *Delete*. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The selected properties are deleted and removed from the overview.

[#4700]
=== Grouping properties

Create property groups to summarise multiple properties. Proceed as described below to create a property group.

[.instruction]
Creating a property group:

. Go to *Setup » Settings » Properties » Groups*.
. Click on *Add property group*.
. Carry out the settings. Pay attention to the information given in <<table-create-property-group>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The property group is created.

[[table-create-property-group]]
.Creating a new property group
[cols="1,3"]
|====
|Setting |Explanation

|*Name*
|Enter the name for the property group. +
*_Note:_* The name of the system language is displayed by default. After the property group has been created, you can save the name in English. Further languages are planned.

|*Description*
|Enter the description for the property group. +
*_Note:_* The description of the system language is displayed by default. After the property group has been created, you can save the description in English. Further languages are planned.

|*Position*
|Enter the position number for the property group. Properties are sorted by the position number in ascending order. +
*_Tip:_* Count by tens when creating position numbers. This allows you to easily add new property groups in between.

|*Group type*
|Select the group type from the drop-down list. This option determines how properties of the type *Empty* are displayed in the order process. +
*None* = Properties are not grouped by default. +
*Select* = One of the grouped properties can be selected from the drop-down list. +
*Multiselect* = Multiple properties can be selected. +
*_Note:_* This option only applies for properties of the type *None* for which the *Order process* option has been activated.

|*Surcharge type*
|Select the type of surcharge from the drop-down list. +
*Flat* = The surcharge is entered as flat amount. +
*Percent* = The surcharge is entered as percentage.
|====

[#4800]
==== Assigning properties to a group

Proceed as described below to assign one or more properties to a property group.

[.instruction]
Assigning properties to a group:

. Go to *Setup » Settings » Properties » Configuration*.
. Start the search. +
→ If required, select filters to limit the search results.
. Activate the properties that you want to assign to the group.
. Click on *Assign property group*. +
→ A drop-down list of property groups opens.
. Select the property group from the drop-down list.
. Click on *Group function*. +
→ The selected properties are assigned to the property group.

[#4900]
==== Deleting property groups

You can delete one or more property groups at the same time. Properties that are assigned to groups remain unaffected when deleting property groups.

===== Deleting a property group

Proceed as described below to irreversibly delete a property group if it is no longer needed.

[.instruction]
Deleting a property group:

. Go to *Setup » Settings » Properties » Groups*.
. Start the search. +
→ If required, select filters to limit the search results.
. Click on the property group. +
→ The detail view of the property group opens.
. Click on *Delete group*. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The property group is deleted and removed from the overview. +
*_Note:_* When you delete a property group, the properties that are assigned to the group are not deleted.

[#5000]
===== Deleting multiple property groups

Proceed as described below to irreversibly delete multiple property groups if they are no longer needed.

[.instruction]
Deleting multiple property groups:

. Go to *Setup » Settings » Properties » Groups*.
. Start the search. +
→ If required, select filters to limit the search results.
. Activate the property groups that you want to delete.
. Click on *Delete*. +
→ A window opens and you need to confirm your decision.
. Click on *Delete*. +
→ The selected property groups are deleted and removed from the overview. +
*_Note:_* When you delete a property group, the properties that are assigned to the group are not deleted.

[#1704]
== Setting the visibility of the quick search for variable users

In order that the *CRM » Contacts* menu is visible for users with the user class *Variable*, the menu must be activated in the user account.

Since the new user interface of the *CRM » Quick search* menu is retrieved via REST, additional rights have to be activated in the *REST API* menu. The following describes which rights must be at least activated in order that the menu is visible. Activate further rights accordingly. If you want that the variable user to create notes in the quick search, for example, go to the *Comments* section and activate the *Create comment* option.

[.instruction]
Setting the visibility of the quick search for variable users:

. Go to *Setup » Settings » User » Accounts*.
. Open the user with the user class *Variable* for whom you would like to activate the visibility of the menu.
. Click on the *Right* tab.
. Click on the *Menu* tab.
. Expand the *CRM* section.
. Activate the option *Quick search*.
. Click on the *REST API* tab.
. Expand the *Accounts* section.
. Activate the *Show account* option.
. Expand the *Address* section.
. Activate the *Show address* option.
. Expand the *Address option* section.
. Expand the *Type of address option* section.
. Activate the *Show type of address option* option.
. Expand the *Contact* section.
. Expand the *Contact address* section.
. Activate the *Show contact address* option.
. Expand the *Address type* section.
. Activate the *Show address type* option.
. Expand the *Contact option* section.
. Expand the *Type of contact option* section.
. Activate the *Show type of contact option* option.
. Activate the *Show contact* option.
. Expand the *Comments* section.
. Activate the *Show comment* option.
. Expand the *Orders* section.
. Activate the *Show orders* option.
. Expand the *Order status* section.
. Activate the *Show order status* option.
. *Save* (icon:save[role="green"]) the settings.

[#1705]
== Finding data records via the quick search

Use the quick search to get an overview of all information that is saved for a contact or a guest account. Besides the invoice address, the master data and general information such as the customer type, pending amounts and the data of the last order, also orders, further addresses, events, notes and tickets are displayed.

[.instruction]
Finding data records via the quick search:

. Go to *CRM » Quick search*.
. Select at least one filter. Pay attention to the information given in <<table-filter-quick-search>>.
. Click on *Search*. +
→ The data records that correspond to the search criteria entered are displayed.
. Click in the line of the data record. +
→ The overview of the contact with the sections *Assigned tags*, *Invoice address*, *Master data* and *Info* is displayed.
. Click in the line *Orders* to display the orders. +
→ Click in the line of the order to directly access the order in the *Orders » Edit orders* menu.
. Click in the line *Addresses* to display further addresses. +
→ Click in the line of the address to directly access the address and edit it.
. Click in the line *Events* to display the events. +
→ The stop watch in the top right corner starts automatically once the data record is opened. Click on *Add event* to save this time. +
*_Note:_* Events are only available for contact data records, not for guest accounts.
. Click in the line *Tickets* to display the tickets. +
→ Click in the line of the ticket to directly access the ticket in the *CRM » Ticket system* menu.
. Click in the line *Notes* to display the notes.

[[table-filter-quick-search]]
.Quick search filters
[cols="1,3"]
|====
|Setting |Explanation

|*Search*
|Displays the data records that correspond to the search criteria. At least one filter must be selected.

|*Reset*
|Resets the selected filter criteria.

|*ID*
|Each contact automatically receives a consecutive and unique ID. It doesn't matter if the data record was saved manually or automatically. 2 contacts never have the same ID. The ID is always a real number. "00521" or "ADF8354" e.g. are invalid.

|*Name*
|Enter the first name and/or last name or the name of the company to search for the contact with this name or company name.

|*Contact data*
|In this field, you can search for the name, address, company, customer number and eBay name. +
*_Note:_* In order to search for the eBay name, first enter the parameter *ebay:* of the eBay name that you search for.

|*Address*
|Enter the name of the street and/or the postcode that is saved for the contact. It is also possible to search only for parts of the street and parts of the house number.

|*Postcode*
|Enter the postcode that is saved for the contact. The search is also carried out for postcodes that are saved in the address data records of the contact. It is also possible to search only for parts of the postcode.

|*Town*
|Enter the town that is saved for the contact. The search is also carried out for towns that are saved in the address data records of the contact. It is also possible to search only for parts of the town.

|*Email*
|Enter the complete email address to search for the contact with this email address.

|*Telephone*
|Enter the telephone number to search for the contact with this number. You can also search for parts of the telephone number. Enter at least 3 numbers.

|*Country*
|Select a country to only display contacts from this country. The country is saved within the contact data.

|*Owner*
|Select the owner to only search for contacts that are linked to this owner. The owner must be saved in the contact data record. +
*_Important:_* Only owners for whom the *Customer* option has been activated in the *Owner* tab can be selected from the drop-down list.

|*Type*
|Select the type to only search for contacts with this type.

|*Customer class*
|Select the customer class to only search for contacts with this class.

|*Rating*
|Select the rating to only search for contacts with this rating. 5 yellow stars are the best rating, 5 red stars are the worst rating:

|*Tags*
|Select one or more tags to only search for contacts with these tags.

|*Client*
|Select a client to only display contacts that correspond to this client. The client is saved within the contact data record. +
*_Important:_* Variable users can only select those clients that they have a right to access. Variable users are given rights within the <<basics/admin-tasks/manage-users#90, Right>> tab in the *Setup » Settings » User » Accounts* menu.

|*Referrer*
|Select the referrer to only search for contacts with this referrer.

|====

[#1705a]
=== Further options in the quick search

When you open a data record in the quick search, you see further possible settings in the first line of the data record. These settings are explained in <<table-settings-quick-search>>.

[[table-settings-quick-search]].Settings in the quick search
[cols="1,3"]
|====
|Setting |Explanation

|*Contact ID*|Click on the contact ID to open the contact data record in the *CRM » Contacts* menu. +
*_Note:_* If the data record is a guest account, this field is not available.

|*Orders*|Click on the *Orders* to open the *Orders » Edit orders* menu. The ID of the contact is automatically selected as filter. +
Click on *New order* to create a new order in the *Orders » Edit orders* menu. +
*_Note:_* If the data record is a guest account, these fields are greyed out.

|*Tickets*|Click on *Tickets* to open the *CRM » Ticket system* menu. The ID of the contact is automatically selected as filter. +
Click on *New ticket* to create a new ticket in the *CRM » Ticket system* menu. +
*_Note:_* If the data record is a guest account, these fields are greyed out.

|*Notes*|Click on *Notes* to open the *Notes* area in the *CRM » Contacts* menu. The ID of the contact is automatically selected as filter. +
Click on *New note* to create a new note. +
*_Note:_* If the data record is a guest account, these fields are greyed out.

|*Download all data of the contact*|Click on this field to download all data that is saved for this data record. Further information can be found in the chapter <<crm/managing-contacts#1706, Downloading all data of a contact>>.

|*Send newsletter opt-in email*|Click on this field to manually register the customer for the newsletter. +
*_Note:_* If the customer is not registered for the newsletter yet, they will receive the automatic email for newsletter opt-in. If the customer is already registered for the newsletter, but has not confirmed yet, they will receive the confirmation for the newsletter opt-in.

|*Anonymise data record*|Click on this field to anonymise the data record. Anonymising data is only possible when the data record is a "real" contact and not a guest account. For further information, refer to the <<crm/managing-contacts#1707, Anonymising a data record>> chapter.

|*Convert guest into contact*
|Click on this field to convert the guest account into a regular contact data record. In the *History* area of the newly created contact data record, the entry *Converted by* as well as the user name are added. +
Further information can be found in the <<crm/managing-contacts#1705b, Converting a guest account into a contact data record>> chapter.

|*Update data*|Click on this field to update the data for this data record.

|====

[#1705b]
=== Converting a guest account into a contact data record


Go to *CRM » Quick search* to convert a data record from a guest account into a regular contact data record.

In case of guest orders via the Ceres online store, the guest account consists only of the address and the corresponding order. If a company name is additionally contained in the address, the company data record is also created when converting the data record.

[.instruction]
Converting a guest account into a contact data record:

. Go to *CRM » Quick search*.
. Select at least one filter. Pay attention to the information given in <<table-filter-quick-search>>.
. Click on *Search*. +
→ The data records that correspond to the search criteria entered are displayed.
. Click in the line of the data record. +
→ The data record opens.
. Click on *Convert guest to contact* in the header. +
→ A window opens and you need to confirm your decision. +
. If you have worked in compliance with GDPR, click on *Convert*. +
→ The data record is converted into a contact data record and automatically obtains the next free contact ID. In the *History* area of the contact data record, the entry *Converted by* as well as the user name are added.

[TIP]
.Callisto guest orders vs. Ceres guest orders
====
The <<crm/managing-contacts#350, Old online store: Converting a guest account into a regular account>> chapter describes how to convert Callisto guest orders into regular accounts. It is not possible via the contact data record to convert Ceres guest orders into regular accounts.

Besides Ceres guest orders, you can, however, use the quick search to convert also Callisto guest orders into regular contact data records.
====



[#1705c]
=== Using the stop watch

As soon as you open a data record in the *CRM » Quick search* menu, the stop watch in the top right corner starts counting. Click on the start/stop symbol to stop the stop watch from counting. Click on the start/stop symbol again to continue counting the time.

Click on *Reset* to set the time to 0. The times of the stop watch are automatically transferred to the *Events* area of the contact data record. In this area, you can carry out further settings and select the type as well as enter an info text.

The data saved in the quick search is also available in the *Events* area of a contact data record in the *CRM » Contacts* menu.

[#1706]
== Downloading all data of a contact or guest account

In the *CRM » Quick search* menu, you can download all data that is saved for a contact or an address (guest account) as a ZIP file.

[.instruction]
Downloading all data of a contact or guest account:

. Go to *CRM » Quick search*.
. Select at least one filter.
. Click on *Search*. +
→ The data records that correspond to the search criteria entered are displayed.
. Click in the line of the data record. +
→ The overview of the contact with the sections *Assigned tags*, *Invoice address*, *Master data* and *Info* is displayed.
. Click on *Download all data of the contact* in the upper line. +
→ A dialogue window appears. Determine a location on your computer where the ZIP file is saved.

Further information about the download file can be found in this link:https://forum.plentymarkets.com/t/dsgvo-button-fuer-den-datenexport-zu-einem-kunden-integriert/486915[Changelog^] thread in the plentymarkets forum.

[#1707]
== Anonymising a data record

You can delete data of a contact respectively make this data illegible in such way that no reference to this person is given any longer.

Anonymising data is only possible when the data record is a "real" contact and not a guest account.

[.instruction]
Anonymising a data record:

. Go to *CRM » Quick search*.
. Select at least one filter.
. Click on *Search*. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The overview of the contact opens.
. Click on *Anonymise data record* in the upper line. +
→ A window opens and you need to confirm your decision.
. Enter the ID of the contact that you would like to anonymise.
. Click on *Anonymise*. +
→ The data record is anonymised.

[TIP]
.Which data is anonymised and deleted?
====
By clicking on *Anonymise data record*, the following data in the data record of the contact is anonymised and deleted:

* The data is anonymised: First name, last name
* This data is deleted: Contact options, address options, addresses, address relations, order relations, company (account) relations, bank details
====

[#5100]
== Displaying the change history for contact data

Via the change history you can track which user has changed data of a contact data record in your system. Furthermore, it is displayed if the contact have made changes in the My account area of your online store.

[.instruction]
Displaying the change history for contact data:

. Go to *Data » Change history*.
. Select an option from the drop-down list *Reference type*.
. Enter the reference ID, e.g. the ID of the contact.
. Click on *Search*. +
→ A list of the changes with the old and new value is displayed.

[TIP]
.Currently available reference types
====
The following reference types are currently available to display changes in the contact data record:

Contact, address, company, configuration of data cleansing.
====

[#5200]
== Displaying the accounts receivable list

The *CRM » AR list* menu provides you with an overview of all customers with unpaid orders. Here, AR stands for accounts receivable. The list includes the number of claims held for each customer as well as the total pending amount for these claims.

The accounts receivable list is automatically updated once per day. As such, claims may not be displayed in the list until the next day. However, it is also possible to <<crm/managing-contacts#5400, Manually updating the accounts receivable list>>. Proceed as described below to display the entire accounts receivable list.

[.instruction]
Displaying the accounts receivable list:

. Go to *CRM » AR list*.
. Click on *Search*. +
→ All of the claims are displayed.

It is possible to open the customer data record from this list. Simply click on the ID in the *ID* column. Or open a list of all orders that were placed by the customer and that have not been paid yet. Simply click on *Show orders* in the *Orders* column.

[#5300]
=== Filtering the accounts receivable list

The list in the *CRM » AR list* can be filtered by *type*, *country*, *customer class* or *customer type*. The list can also be sorted from the highest to lowest number of *accounts receivable* or from the highest to lowest *pending amount*.

[.instruction]
Filtering the accounts receivable list:

. Go to *CRM » AR list*.
. Select the filters.
. Click on *Search* to display the results.

[#5400]
=== Manually updating the accounts receivable list

The accounts receivable list is automatically updated once per day. However, you can also update the list manually anytime.

[.instruction]
Manually updating the accounts receivable list:

. Go to *CRM » AR list*.
. Click on *Generate* in the *Generate AR list* area. +
→ The list is updated in the background.
. Click on *Search* to display the updated list.


[#5500]
== Checking the VAT number

The value added tax identification number (VAT number) is an exclusive identification number and serves to designate VAT registered individuals. Within the EU, tax offices need this number for VAT accounting purposes.

////
The VAT number is saved and checked in the *CRM » Edit customer* menu. It is located within the *Customer data* tab of each customer data record.
////

The VAT check allows you to verify German and international VAT numbers. These checks can be carried out daily from 5:00 a.m. to 11:00 p.m. CET. All VAT numbers from EU member states can be checked, with the exception of those from Slovakia and Latvia (is not possible or only possible to a limited extent). For German VAT numbers, only the number's validity is checked. The assignment to a person are not checked. For international VAT numbers, the number's validity is checked and the company and address details associated with the VAT number are retrieved and displayed.

////
[#5600]
=== Checking the VAT number in the customer data record

Proceed as follows to check the VAT number in the customer data record.

[.instruction]
Checking the VAT number in the customer data record:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered are displayed.
. Click in the line of the contact. +
→ The detail view of the contact opens.

. In the *Customer data* tab, enter the VAT number without any spaces under *VAT number*.
. Click on *Check*. +
→ The check can take a few minutes.
. Once the check is completed, click on *Save* to save the VAT number.

The query provides the outcome of the VAT number check.

If the VAT number is valid, the status *Valid* is displayed. If the VAT number is not valid, the status *Invalid* is displayed. A message is displayed if a VAT number could not be checked. Data that does not match is designated with an error message in the *Status* row.

You can check the VAT number from within the customer data section of an order. To do so, go to *Orders » Edit orders » Open order » Tab: Customer » Tab: Customer data*.
////

[#5700]
=== Checking the VAT number in the online store

The VAT number is automatically checked in the online store during the order process. If an invalid VAT number was entered, the purchaser is only able to complete their order once a valid VAT number has been entered or once the entry has been deleted.

[#5800]
=== Exporting check data

You can export a list of all the check data or the data for the current month. For further information about exporting the VAT number check data, refer to the <<data#, Data exchange>> area.

[#5900]
== Exporting, importing and updating contact data

Export the data of your contacts via the elastic export. Installing the plugins link:https://marketplace.plentymarkets.com/en/plugins/integration/ElasticSync_4750[ElasticSync^] and link:https://marketplace.plentymarkets.com/en/plugins/markets/ElasticExport_4763[Elastic Export^] as well as deploying them in Productive is required. Both plugins are available in the link:https://marketplace.plentymarkets.com/en/[plentyMarketplace^]. ElasticSync is not needed for the export, but for the import and update of data, but it contains the function FormatDesigner.

Create the format for the export in the *Data » FormatDesigner* menu. Create a new export in the *Data » Elastic export* menu. Select the format that you have just created via the FormatDesigner from the drop-down list. Afterwards, export the data to a CSV file.

Various filter options are available for the export. You can export, for example, only contacts that you have rated with 3 stars or only contacts that are assigned to a certain owner.

Import or update the data of your contacts including address options, contact options and company data via ElasticSync. For further information, refer to the <<data/importing-data/ElasticSync#, Importing data with ElasticSync>> page of the manual.
