= Managing contacts
:lang: en
include::{includedir}/_header.adoc[]
:keywords: contact, customer, address, addresses, invoice address, delivery address, primary,
:description: Learn how to manage contacts in plentymarkets.
:position: 15

[IMPORTANT]
.Note about the "Managing contacts" page of the manual
====
This page of the manual describes all settings that are available in the *CRM » Feedback ratings* menu in the Terra back end using the centralised login. The<<crm/managing-customer-data#, Managing customer data>> page of the manual that describes the settings in the *Customers » Edit customers* and *System »Customers* menus will be simultaneously available. Once the new *CRM » Contacts* menu has completely replaced the old *Customers » Edit customers* menu, the *Customers » Edit customers* menu as well as the *Managing customer data* page of the manual will be removed.
====

Go to *CRM » Contacts* to create data records about contacts and save all relevant information there. You can edit and delete your contacts in this menu as well as display the addresses, orders, tickets, notes and account of your contacts, add new addresses, orders, tickets and notes and delete existing addresses, tickets and notes.

[TIP]
.Notes about detail view, context menu, card view and table view
====
If you click on a contact in order to display or edit it, the detail view of the contact will open. Via the context menu in the left section of the contact, you can access views such as *Addresses* or *New address*.

By clicking on *Addresses* for example, all addresses that are saved for the contact will be initially displayed as cards. By clicking on *Switch to table view*, the addresses will be displayed in a table. From this view, you can switch back by clicking on *Switch to card view*. Your plentymarkets system will recognise which of the two views you selected. When opening the context menu *Addresses* the next time, the view that was selected last will be displayed.

When more than one view of the contact is open, a triangle will appear in the view above. Click on the triangle to quickly and easily switch between the open views. Click on the cross to close the contact and remove it from the list.

You can get back to the overview of contacts found via the *Overview* view. From this view, you can open as many further contacts as you like. When more than one contact is open, a triangle will appear in the view of the contact that is currently open. Click on the triangle to quickly and easily access contacts that have been opened at least once. Click on the cross to close the contact and remove it from the list.
====

[#50]
== Setting up the visibility for variable user

In order that the *CRM » Contacts* menu is visible for users with the user class *Variable*, the menu must be activated in the user account. For users with the user class *Admin*, the *CRM » Contacts* menu is activated by default.

[.instruction]
Setting up the visibility for variable user:

. Open the menu *System » Settings » User » Accounts*.
. Open the user with the user class *Variable* for whom you would like to make activate the visibility of the menu.
. Click on the *Right* tab.
. Click on the *Menu* tab.
. Expand the *Customer* area.
. Activate the *Contacts* option.
. *Save* the setting.


[#100]
== Creating a contact

Proceed as described below to create a new contact. Add contact options such as email addresses, telephone numbers and, if required, the VAT number. You can also create a new contact, for example, while taking an order over the phone or while filling out a written order. It is also possible to save the contact details of interested parties here. When creating a contact, the system will automatically assign an ID. This ID cannot be changed.

[.instruction]
Creating a contact:

. Go to *CRM » Contacts*.
. Click on *Create new contact*.
. Carry out the settings as desired in the *New contact* section. Pay attention to the information given in table 1.
. In the *Contact options* section, select the type and sub-type from the drop-down menu and enter the value. Pay attention to the information given in table 1. +
→ Click on *Add contact option* to add further contact options.
. *Save* the settings. +
→ The contact will be added.

.Creating a contact
[cols="a,a"]
|====
|Setting |Explanation

2+|*New contact*

|*Form of address*
|Select the option from the drop-down menu. This selection is optional. +
*Ms.* = Female form of address +
*Mr.* = Male form of address

|*Title*
|Enter the title of the contact, if required.

|*First name*, *Last name*
|Enter the first and last name of the contact.

|*Client (store)*
|Select the client (store) from the drop-down menu in order to assign the contact to this client (store). +
Only those clients will be displayed that have a name entered for them in the *System » Client » Select online store » Settings* menu.

|*Language*
|Select the language for the contact. For example, invoice documents will be sent in this language if you created a template in this language.

|*Type*
|Select the type. The types *Customer*, *Sales representative*, *Supplier*, *Partner*, *Manufacturer* and *Interested party* can be selected by default. Create further types in the <<crm/managing-customer-data#300, System » Customers » Types>> menu.

|*Class*
|Select the class. Classes serve as an internal distinction between customers and which discount will be granted this class, for example. Go to <<crm/managing-customer-data#100, System » Customers » Customer classes>> to create further classes. If you want to offer different prices to end customers and sellers in the online store, then this can be done with the *Display of the prices in the online store* option in the configuration of the classes. For end customers (B2C), the gross prices are displayed in the online store. For sellers (B2B), the net prices are displayed in the online store. +
Empty option = No assignment to a class +
*_Important:_* If there is no assignment to a class, the contact will be automatically assigned to the class with the lowest position. As the price display in the online store is configured for each class, check this option for the class with the position 1 so that the correct price is displayed during automatic assignments.

|*Feedback*
|Give feedback about the contact for internal use. Select five red stars for the worst and five yellow stars for the best rating.

|*Customer number*
|Enter a customer number for the contact. It is a good idea to plan how you want your contacts to be numbered, e.g. consecutively. Customer numbers are not assigned automatically.

|*Owner*
|Select the owner for the contact. If you do not want to select an owner, select the empty option.

|*Date of birth*
|Enter the date of birth of the contact in the format yyyy-mm-dd or select it from the calendar.

|*Newsletter*
|Displays if the contact receives the newsletter. It is not possible to activate this option manually. In order to exclude the contact from receiving the newsletter, click on *Delete newsletter*.

|*Blocked*
|Select whether or not the contact should be blocked for the specific client (store). +
If the option is activated, the contact will be blocked and can no longer log into the online store. If the option is deactivated, the contact will be able to log into the online store.

2+|*Contact options*

|*Type*
|Select the type, e.g. email, telephone or website from the drop-down menu.

|*Sub-type*
|Select a sub-type, e.g. work, private or contact person from the drop-down menu.

|*Value*
|Enter the value.
|====

[#200]
== Searching for a contact

In the *Filter* view, you can search for contacts according to specific criteria. The contacts found will be listed in the *Overview* view. The overview currently displays the following information: ID, company, first name, last name, email address, telephone number, number of orders, postcode and country. How you edit contact data is described in the <<crm/managing-contacts#300, Editing a contact>> chapter.

[TIP]
.Sending emails directly from the overview
====
Send an email to your contact directly from the contact overview. Click on the email address to automatically open your email programme.
====

In order to search for specific contacts, enter a search term in the search fields or select the appropriate drop-down menu settings. You can enter multiple search terms into the search fields at one time. This makes your search run quicker and be more accurate.

[.instruction]
Searching for a contact:

. Go to *CRM » Contacts*.
. In the *Filter* view, enter the search term in the search field or set the filter options in the drop-down menus. Pay attention to the information given in table 2.
. Click on *Search*. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open. As an alternative, open the context menu by clicking right in order to access the views of the contact.

.Filters for contacts
[cols="a,a"]
|====
|Setting |Explanation

|*Search*
|Click on *Search* without selecting any filter settings. This will display all contacts. Alternatively, limit the search results by using filters and click on *Search*. The contacts found will be listed in the overview.

|*Reset*
|Resets the filter criteria that was entered.

|*ID*
|Each contact automatically receives a consecutive and unique ID. It doesn't matter if the data record was saved manually or automatically. Two contacts never have the same ID. The ID is always a real number. "00521" or "ADF8354" e.g. are invalid. 

|*Name*
|Enter the first name and/or last name or the name of the company to search for the contact with this name or company name. The search is also carried out for names and company names that are saved in the address data records of the contact. It is also possible to search only for parts of the name or company name.

|*Address*
|Enter the name of the street and/or the postcode that is saved for the contact. It is also possible to search only for parts of the street and parts of the house number.

|*Postcode*
|Enter the postcode that is saved for the contact. The search is also carried out for postcodes that are saved in the address data records of the contact. It is also possible to search only for parts of the postcode.

|*Town*
|Enter the town that is saved for the contact. The search is also carried out for towns that are saved in the address data records of the contact. It is also possible to search only for parts of the town.

|*Email*
|Enter the email address to search for the contact with this email address. It is also possible to search only for parts of the email address.

|*Country*
|Select a country to only display contacts from this country. The country is saved within the contact data.

|*Owner*
|Select the owner to only search for contacts with this owner. The owner must be saved in the contact data record. +
*_Important:_* You can only select users from the drop-down menu who are activated for the *Customer* option in the *Owner* tab of their user account.

|*Type*
|Select the type to only search for contacts with this type.

|*Client (store)*
|Select a client (store) to only display contacts that correspond to this client. The client (store) is saved within the contact data. +
*_Important:_* Variable users can only select those clients (stores) that they have a right to access. Variable users are given rights within the <<basics/working-with-plentymarkets/manage-users#90, Right>> tab in the *System » Settings » User » Accounts* menu.

|*Referrer*
|Select the referrer to only search for contacts with this referrer.
|====

[#300]
== Editing a contact

Search the contact by means of the <<crm/managing-contacts#200, filter settings>>. Open the contact by clicking in the line of the contact to edit the contact's data such as the language, class, date of birth, telephone number and email address, for example. You will find explanations of the settings and options in the sections *Contact* and *Contact options* in the <<crm/managing-contacts#100, Creating a contact>> chapter. Click on *Delete contact option* to delete the contact options.

[.instruction]
Editing a contact:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Carry out the changes as desired. Pay attention to the information given in table 1 in the <<crm/managing-contacts#100, Creating a contact>> chapter.
. *Save* the settings.

[#400]
== Deleting a contact

You can delete individual contacts. All addresses that are assigned to the contact will be deleted if they are not linked to an order.

[.instruction]
Deleting a contact:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Delete contact* in the context menu or click on *Delete* above the detail view. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The contact will be deleted and removed from the overview.

[#500]
== Displaying the history

Each data record contains the history of a contact. The history includes e.g. how long the contact has been registered and when he or she has been logged into your online store for the last time and when the last order was generated. This data will be automatically updated and cannot be changed.

[.instruction]
Displaying the history:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open and the history will be displayed in the right section below the *contact options*.
. Pay attention to the information about the history given in table 3.

.History in the *CRM » Contacts » Open contact* menu
[cols="a,a"]
|====
|Setting |Explanation

|*Registered since*
|Date and time when the contact has first registered.

|*Updated*
|Date and time when the data record of the contact has been updated for the last time.

|*Account type*
|Account via which the contact has registered. +
*Regular account* = The contact has newly registered in your online store or the data record has been manually created in the back end. +
*Guest account* = The contact has registered and ordered as a guest.

|*Last order*
|Date and time when the last order was made. If no order has been placed, *No data* is displayed in this field.

|*Last login*
|Date and time when the contact was logged in for the last time. If the contact was not logged in, *No data* is displayed in this field.
|====

[#600]
== Adding an address

You can add as many addresses and as address options as you like. Address options are for example, the VAT number or the telephone number of the contact.

[.instruction]
Adding an address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *New address* in the context menu.
. Carry out the settings in the *New address* section. Pay attention to the information given in table 4.
. In the *Address options* section, select the type from the drop-down menu and enter the value. Pay attention to the information given in table 4. +
→ By clicking on *Add address option*, you can add further address options.
. *Save* the settings. +
→ The address will be added to the overview in the *Addresses* section.

.Adding an address
[cols="a,a"]
|====
|Setting |Explanation

2+|*New address*

|*Form of address*
|Select the form of address from the drop-down menu, if needed.

|*Name 1 (Company)*
|Enter the company name. This is a mandatory field when there is no entry under *First name* and *Last name*.

|*Name 2 (First name)*
|Enter the first name of the contact. This a mandatory field when there is no entry under *Company* and *Last name*.

|*Name 3 (Last name)*
|Enter the last name of the contact. This is a mandatory field when there is no entry under *Company* and *First name*.

|*Name 4 (Additional information)*
|If needed, enter additional information, e.g. c/o Mr. John Doe.

|*Address 1 (Street)* +
*Address 2 (House number)*
| Enter the street and house number. +
*Street* is a mandatory field when there is no entry under *House number* and *Additional address information*. *House number* is a mandatory field when there is no entry under *Street* and *Additional address information*.

|*Address 3 (Additional address information)*
|Enter additional address information if necessary, e.g. apartment 12a. This is a mandatory field when there is no entry under *Street* and *House number*.

|*Address 4 (Free)*
|This field can be freely used.

|*Postcode* +
*Town*
|Enter the postcode and town of the contact. This data will be used for the invoice address, for example. The order of the options *Postcode* and *Town* is reversed for certain countries, e.g. Germany. +
*Postcode* and *Town* are mandatory fields.

|*Country* +
*Region/County*
|Select the values from the drop-down menu. +
*_Important:_* The drop-down menu *Region/County* is not available for all countries.

|*Invoice address* / *Delivery address*
|Activate one or both options in order to determine the address type. +
The new address can either be the invoice address only, the delivery address only or both the invoice address and the delivery address. If both options are activated, an address with a new ID and two address types will be created. +
If one ore both options are activated, you can select for one or both options if the address is the primary address.

|*Primary*
|Activate the option if the new address is the primary invoice address or the primary delivery address. +
It is possible to activate both options if the new address is the primary invoice address as well as the primary delivery address.

2+|*Address options*

|*Type*
|Select the type, for example the Postnummer or the VAT number from the drop-down menu.

|*Value*
|Enter the value.
|====

[#700]
== Displaying addresses

From the open contact, you can display all addresses that are saved for the contact. Besides the ID, company name, first and last name as well as address and country, you can see the address type – invoice address or delivery address – and whether the address is a primary address or not.

If multiple addresses are open, the IDs of the addresses will also be dipslayed in the drop-down menu of the open address data records.

Initially, the addresses of your contact are displayed in card view. By clicking on *Switch to table view*, the addresses will be displayed in a table. Your plentymarkets system will recognise which of the two views you selected. When opening the context menu *Addresses* the next time, the view that was selected last will be displayed.

Up to 25 address data records saved for the contact are displayed per page. If more than 25 addresses are saved for the contact, you can use the toolbar to browse between the pages, select a certain page and to change the number of address data records per page to 50, 75 or 100. Your plentymarkets system will recognise the number of address data records you selected per page. When opening the view *Addresses* the next time, the setting that was selected last will be displayed.

[.instruction]
Displaying addresses:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Addresses* in the context menu. +
→ All addresses that are saved for the contact will be displayed.
. Click on *Edit* in order to open the detail view of the address. +
→ If you selected the table view, click in the line of the address in order to open the detail view.

[#800]
== Editing the address

You can edit addresses as well as address options at any time. Pay attention to the information given in the <<crm/managing-contacts#600, Adding an address>> chapter. Click on *Delete address option* to delete the address options.

[.instruction]
Editing the address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Addresses* in the context menu. +
→ All addresses that are saved for the contact will initially be displayed as cards.
. Click on *Edit* in the address card that you want to edit. +
→ The detail view of the address will open.
. Carry out the changes as desired. Pay attention to the information given in table 4 in the <<crm/kontakte-verwalten#700, Adding an address>> chapter as well as to the information about the toolbar given in table 5.
. *Save* the settings.

.Editing the address
[cols="a,a"]
|====
|Setting |Explanation

|*Save*
|Saves the settings.

2+|*Invoice address*

|*Derive new invoice address*
|Creates a new invoice address based on the currently selected address. In order to create a new address with a new ID, changes must be made to the data of the new invoice address.

|*Add invoice address type*
|Adds the *Invoice address* type to the address. The ID does not change. +
If the type *Invoice address* has already been added for the address, this option will not be visible.

|*Delete invoice address type*
|Deletes the *Invoice address* type from the address. +
If the type *Invoice address* has not been added for the address, this option will not be visible.

|*Define as primary invoice address*
|The currently selected invoice address will be defined as primary invoice address. The ID does not change. +
If the *Invoice address* type is not selected, this option will be deactivated. +
If the invoice address has been defined as primary, this can be undone by clicking on *Reset primary invoice address*.

|*Convert to invoice address* / +
*Convert to delivery address*
|Converts the currently selected address to an invoice address or a delivery address. The ID does not change. +
If both address types are selected, this option will be deactivated.

2+|*Delivery addres*

|*Derive new delivery address*
|Creates a new delivery address based on the currently selected address. In order to create a new address with a new ID, changes must be made to the data of the new delivery address.

|*Add delivery address type*
|Adds the *Delivery address* type to the address. The ID does not change. +
If the type *Delivery address* has already been added for the address, this option will not be visible.

|*Delete delivery address type*
|Deletes the *Delivery address* type from the address. +
If the type *Delivery address* has not been added for the address, this option will not be visible.

|*Define as primary delivery address*
|The currently selected delivery address will be defined as primary delivery address. The ID does not change. +
If the *Delivery address* type is not selected, this option will be deactivated. +
If the delivery address has been defined as primary, this can be undone by clicking on *Reset primary delivery address*.

|*Delete address data record*
|Completely deletes the address data record.
|====

[#900]
== Deleting an address

If the address is not an invoice address that is linked to an order, you may delete the address. This may be necessary, if the delivery address of the contact is outdated, for example.

[NOTE]
.Deleting invoice addresses that are linked to an order is not possible
====
If the address is of the type *Invoice address* and if it is linked to an order, you cannot delete the address. An error message will be displayed.
====

[.instruction]
Deleting an address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Addresses* in the context menu. +
→ All addresses that are saved for the contact will initially be displayed as cards. +
. Click on *Delete* in the address card that you want to delete. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The address will be deleted and removed from the overview.

[#1000]
== Displaying orders

Within the open contact, you can access all orders of the contact in the *Orders » Edit orders* menu. When switching to the order menu, it will be searched automatically for orders from contacts with this ID.

[.instruction]
Displaying orders:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Orders* in the context menu. +
→ All orders that are saved for the contact will be displayed in the *Orders » Edit orders* menu. +
. Click in the line of the order to display further information about the order.

You can also edit the order. Orders can be edited as long as no document has been generated for this order. Further information about orders can be found on the <<order-processing/orders/managing-orders, Managing orders>> page of the manual.

[#1100]
== Creating an order

Within the open contact, you can create a new order for the contact with only one click. If the contact has ordered in your online store, the order will be automatically saved in your plentymarkets system. In case of orders via telephone, for example, you will create the order manually. Proceed as described below.

[.instruction]
Creating an order:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *New order* in the context menu. +
→ You will directly access the *New order* area in the *Orders » Edit orders* menu. +
. Carry out the settings. Pay attention to the information given on the <<order-processing/orders/managing-orders#, Managing orders>> page of the manual.
. *Save* the settings.

[#1150]
== Displaying the scheduler

In the *Scheduler* view, subscription orders of the contact will be displayed. Moreover, you can create new scheduled orders here. The scheduler allows your customers to subscribe to certain items in your online store. The menu is only visible in your plentymarkets system if you booked it. Go to *Start » Service centre » Tab: Systems » Tab: Contract* to book the scheduler. Go to *System » Orders » Scheduler* to carry out the settings for your online store.

[.instruction]
Displaying the scheduler:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Scheduler* in the context menu. +
→ All scheduler orders that are saved for the contact will be displayed.
. Pay attention to the explanations on the <<order-processing/orders/scheduler#, Scheduler>> page of the manual.

For further information, refer to the <<order-processing/orders/scheduler#, Scheduler>> page of the manual. The filter options are also described there. You can use the filter options both in the *CRM » Contact » Open contact » Tab: Scheduler* menu and in the *Orders » Scheduler » Scheduled orders* menu.


[#1200]
== Creating a ticket

Use the <<crm/using-the-ticket-system#, ticket system>> in plentymarkets to manage your customer communication. The following chapter explains how you can create a new ticket directly from the open contact.

[.instruction]
Creating a ticket:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *New ticket* in the context menu. +
→ You will directly access the *New ticket* area in the *CRM » Ticket system* menu. The contact ID is already pre-filled. +
. Carry out the settings. Pay attention to the information given on the <<crm/using-the-ticket-system#1600, Using the ticket system>> page of the manual.
. *Save* the settings.


[#1300]
== Displaying tickets

From the open contact, you can display all tickets that are saved for the contact in the *CRM » Ticket system* menu. When switching to the ticket menu, it will be searched automatically for tickets from contacts with this ID.

[.instruction]
Displaying tickets:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Tickets* in the context menu. +
→ All tickets that are saved for the contact will be displayed.

You have the possibility to edit and delete tickets. For further information, refer to the <<crm/using-the-ticket-system#, Using the ticket system>> page of the manual.

[#1400]
== Creating a note

You can save as many notes for your contacts as you like. Notes are only visible in your plentymarkets back end. This means that contacts cannot see the saved notes in your online store. Each note automatically receives a consecutive and unique ID. New texts can be entered by typing them in or by inserting them using the clipboard. Use the functions in the toolbar to format the text, insert links and upload image files.

[.instruction]
Creating a note:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *New note* in the context menu. +
→ The *New note* window will open.
. Enter the text, insert text via the clipboard and format the text using the functions in the toolbar.
. *Save* the settings. +
→ The *Notes* section will open and the note will be added to the overview.


[#1500]
== Displaying notes

From the open contact, you can display all notes that are saved for the contact in form of cards. The cards show the creation date with timestamp, the name of the user that created the note as well as the ID.

[.instruction]
Displaying notes:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Notes* in the context menu. +
→ All notes that are saved for the contact will be displayed.

[.subhead]
Opening an individual note

You can open individual notes by clicking on *Open preview*. If more than one note of the contact is open, a triangle will appear in the view. Click on the triangle to quickly and easily switch between the open notes. Click on the cross to close the note and remove it from the list.



[#1600]
== Editing a note

Edit notes to update contents. You can format the text, insert links and upload image files.

[.instruction]
Editing a note:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Notes* in the context menu. +
→ All notes that are saved for the contact will be displayed.
. Click on *Edit* in the card of the note that you want to edit.
. Carry out the changes as desired.
. *Save* the settings.


[#1700]
== Deleting a note

The notes for your contacts can be deleted if the information saved in the notes is outdated or if you do not need it any longer.

[.instruction]
Deleting a note:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Notes* in the context menu. +
→ All notes that are saved for the contact will be displayed.
. Click on *Delete* in the card of the note that you want to delete. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The note will be deleted and removed from the overview.

You can also delete the note when the preview is open. Click on *Delete* in the open note. In this case, a window will open and you need to confirm your decision by clicking on *Delete*.


[#1800]
== Displaying the account balance

The *Account* view lists the revenues of your contacts. In the top line, you see the total of the contact's invoices, the amount granted to your customer in form of credit notes and the difference between the two amounts.  Orders and credit notes are listed as processes in the table. The *Paid* and *Outstanding* columns are especially helpful. If a payment for an order is listed in the *Outstanding* column, then the contact still has to pay the amount. As soon as this is done, the amount will be listed under *Paid*. If a payment for a credit note is listed in the *Outstanding* column, then you still have to pay this amount to the contact. As soon as this is done, the amount will be listed under *Paid*.

[.instruction]
Displaying the account balance:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Account* in the context menu. +
→ All data that is available for the account of the contact will be displayed.
. Pay attention to the information given in table 6. 


.Settings in the *CRM » Contacts » Open contact » View: Account*
[cols="a,a"]
|====
|Setting |Explanation

|*Balance*
|Shows the customer's account balance. +
*+* = total of the contact's outstanding payments +
*-* = total of payments that still have to be paid to the contact if the contact has paid too much or if a credit note still has to be paid out. +
*0.0* = No outstanding amounts

|*Invoices*
|Total invoice amounts of all orders and the number of invoices in parentheses

|*Credit notes*
|Total of all credit notes and the number of credit notes in parentheses

|*Delta*
|Difference in percent between the paid credit notes and the total invoice amount paid by the customer. 0 % means that no credit note has been paid out to the customer yet. 100 % means that every amount paid by the customer has been paid back in form of credit notes.

|*Date*
|Date when the order was created

|*Order ID*
|ID of the order. Click on the ID to open the detailed view of the order. Credit note IDs are indented and displayed under the order.

|*Process*
|Type of order, either order or credit note

|*Document*
|Document number, e.g. invoice number. Click on the number to open the document.

|*Value*
|Invoice total of the order

|*Paid*
|Amount already paid

|*Payment method*
|Payment method for the order

|*Outstanding*
|Remaining amount that is due before the order is completely paid for.

|*Status*
|Status of the order. Click on the status to open the editing window *Order status* and change the status, if required.

|====

[.subhead]
Filtering account data

Use filters to display the account data of your contact.

[.instruction]
Filtering account data:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Notes* in the context menu. +
→ All data that is available for the account of the contact will be displayed.
. Carry out the settings in the *Filter* area. Pay attention to the information given in table 7.
. Click on *Search*. 

.Filter settings in the *CRM » Contacts » Open contact » View: Account*
[cols="a,a"]
|====
|Setting |Explanation

|*Search*
|Perform a search. The account data that correspond to the search criteria entered will be displayed.

|*Reset*
|Resets the filter criteria that was entered.

|*Period*
|Select one of the following settings from the drop-down menu: *ALL*, *This year*, *Last year*, *This month*, *Last month* or *Last 3 months*.

|*Outstanding*
|Select *ALL*, *Yes* or *No*. +
*Yes* = Only outstanding amounts will be displayed. +
*No* = Only paid amounts will be displayed. +
*ALL* = Outstanding and paid amounts will be displayed.

|*Relational operator / Status*
|Select the relational operator and order status from the drop-down menu.

|*Invoice No.*
|Enter the invoice number.

|*Order ID*
|Enter the order ID.

|====

[#1900]
== Adding bank data

In the *Bank data* view, you can add the bank data of your contact. You can add as many data records as you like.

After saving, the bank data will be displayed as cards. Beside the name of the holder and the IBAN, a tag will be displayed that shows whether the SEPA direct debit mandate is activated for the contact. If the BIC is saved in the bank data, this will also be shown on the card.

[.instruction]
Adding bank data:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Bank data* in the context menu.
. Click on *Add*. +
→ The *New bank data* view will be displayed.
. Carry out the settings. Pay attention to the information given in table 8.
. *Save* the settings.

.Settings in the *CRM » Contacts » Open contact » View: Bank data*
|===
|Setting |Explanation

|*IBAN*, *BIC*, *Holder*, *Account number*, *Sort code*
|Enter the bank data of the contact. *IBAN* and *Holder* are mandatory fields.

|*Name, street, postcode and town of the bank*
|Enter the name and address of the bank.

|*Country of the bank*
|Select a country from the drop-down menu.

|*SEPA direct debit mandate*
|Activate this option once the contact has signed the SEPA direct debit mandate. +
*_Important:_* This option needs to be activated before pain.008 formats can be retrieved for <<order-processing/payment/managing-bank-details#200, SEPA payments>>.

|*Type of mandate*
|Only visible when the SEPA direct debit mandate has been activated. +
Select the option from the drop-down menu. +
*SEPA core direct debit* = Allows a biller to collect funds from a payer's account, provided that a signed mandate has been granted by the payer to the biller. +
*SEPA business to business direct debit* = Enables business customers in the role of payers to make payments by direct debit.

|*Payment frequency*
|Only visible when the SEPA direct debit mandate has been activated. +
Select the option from the drop-down menu. +
*One-time payment* = Is typically used for standard orders. +
*Recurring payment* = Is typically used for regularly occurring orders such as subscription orders, etc.

|===

[#2000]
== Editing bank data

You can update the bank data of your contact at any time.

[.instruction]
Editing bank data:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Bank data* in the context menu.
. Click on *Edit* in the card of the bank data that you want to edit. +
→ The data record will open.
. Carry out the settings. Pay attention to the information given in table 8.
. *Save* the settings.

[#2100]
== Deleting bank data

Delete the bank data of your contact if they are outdated.

[.instruction]
Deleting bank data:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Bank data* in the context menu.
. Click on *Delete* in the card of the data record that you want to delete. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The bank data will be deleted and removed from the overview.
