= Managing contacts
:lang: en
include::{includedir}/_header.adoc[]
:keywords: contact, customer, address, addresses, invoice address, delivery address, primary, company, companies, guest account, regular account, properties, access data, change password, unblock login
:description: Learn how to manage contacts in plentymarkets.
:position: 15


[IMPORTANT]
.Note about the "Managing contacts" page of the manual
====
This page of the manual describes all settings that are available in the *CRM » Contacts* menu in the Terra back end using the centralised login. The <<crm/managing-customer-data#, Managing customer data>> page of the manual that describes the settings in the *CRM » Edit customers* and *System » CRM* menus will be simultaneously available. Once the new *CRM » Contacts* menu has completely replaced the old *CRM » Edit customers* menu, the *CRM » Edit customers* menu as well as the *Managing customer data* page of the manual will be removed.
====

Go to *CRM » Contacts* to create and edit data records for your contacts and manage all relevant information there such as addresses, orders, scheduled orders, tickets, notes, account balance, bank data and documents.

[TIP]
.Notes about detail view, context menu, card view and table view
====
If you click on a contact in order to display or edit it, the detail view of the contact will open. Via the context menu in the left section of the contact, you can access views such as *Addresses* or *New address*.

By clicking on *Addresses* for example, all addresses that are saved for the contact will be initially displayed as cards. By clicking on *Switch to table view*, the addresses will be displayed in a table. From this view, you can switch back by clicking on *Switch to card view*. Your plentymarkets system will recognise which of the two views you selected. When opening the context menu *Addresses* the next time, the view that was selected last will be displayed.

When more than one view of the contact is open, a triangle will appear in the view above. Click on the triangle to quickly and easily switch between the open views. Click on the cross to close the contact and remove it from the list.

You can get back to the overview of contacts found via the *Overview* view. From this view, you can open as many further contacts as you like. When more than one contact is open, a triangle will appear in the view of the contact that is currently open. Click on the triangle to quickly and easily access contacts that have been opened at least once. Click on the cross to close the contact and remove it from the list.
====

[#50]
== Setting up the visibility for variable user

In order that the *CRM » Contacts* menu is visible for users with the user class *Variable*, the menu must be activated in the user account. For users with the user class *Admin*, the *CRM » Contacts* menu is activated by default. Since the new user interface of the *CRM » Contacts* menu is retrieved via REST, additional rights have to be activated in the *REST API* menu. The following describes which rights must be at least activated. You can of course activate further rights for variable users.

[.instruction]
Setting up the visibility for variable user:

. Go to *System » Settings » User » Accounts*.
. Open the user with the user class *Variable* for whom you would like to make activate the visibility of the menu.
. Click on the *Right* tab.
. Click on the *Menu* tab.
. Expand the *CRM* area.
. Activate the *Contacts* options.
. Click on the *REST API* tab.
. Expand the *Accounts* area.
. Expand the *Address* area.
. Activate the *Show address* option.
. Expand the *Type of address option* area.
. Activate the *Show type of address option* option.
. Expand the *Contact* area.
. Expand the *Contact address* area.
. Activate the *Show contact address* option.
. Expand the *Address type* area.
. Activate the *Show address type* option.
. *Save* the setting.

[#90]
== Managing contacts and companies

In the following sub-chapters, you will learn, among others, how to create new contacts and companies, link a contact to a company, search for existing contacts using the filter settings as well as edit and delete existing contacts.

[NOTE]
.Exporting, importing and updating contact data
====
Export the data of your contacts via the elastic export. Installing the plugins link:https://marketplace.plentymarkets.com/en/plugins/integration/ElasticSync_4750[ElasticSync^] and link:https://marketplace.plentymarkets.com/en/plugins/markets/ElasticExport_4763[Elastic Export^] as well as deploying them in Productive is required. Both plugins are available in the link:https://marketplace.plentymarkets.com/en/[plentyMarketplace^].

Create the format in the *Data » FormatDesigner* menu. Create a new export in the *Data » Elastic export* menu and select the format that you have just created via the FormatDesigner from the drop-down menu. Afterwards, export the data to a CSV file. Various filter options are available for the export. You can export, for example, only contacts that you have rated with three stars or only contacts that are assigned to a certain owner.

Import the data of your contacts including address options, contact options and company data via the ElasticSync plugin. Install at least plugin version 2.1. For further information, refer to the link:https://marketplace.plentymarkets.com/en/plugins/integration/ElasticSync_4750[user guide^] of the ElasticSync plugin.
====

[#100]
=== Creating a contact

Proceed as described below to create a new contact. Link the contact to an existing company or create a new company. Add contact options such as email addresses and telephone numbers. You can also create a new contact, for example, while taking an order over the phone or while filling out a written order. It is also possible to save the contact details of interested parties here. When creating a contact, the system will automatically assign an ID. This ID cannot be changed.

For further information about linking a contact to a company and creating a new company, refer to the <<crm/managing-contacts#210, Linking a contact to a company>> and <<crm/kontakte-verwalten#220, Creating a company>> chapters.

[.instruction]
Creating a contact:

. Go to *CRM » Contacts*.
. Click on *Create new contact*.
. Carry out the settings in the *Details* area. Pay attention to the information given in <<table-create-contact>>.
. Create a new company in the *Accounts* area or assign an existing company to a contact. Pay attention to the information given in <<table-create-contact>>. +
→ Further information can be found in the <<crm/managing-contacts#220, Creating a company>> and<<crm/managing-contacts#210, Linking the contact to a company>> chapters.
. In the *Contact options* section, select the type and sub-type from the drop-down menu and enter the value. Pay attention to the information given in <<table-create-contact>>. +
→ Click on *Add contact option* to add further contact options.
. *Save* the settings. +
→ The contact will be added.

[[table-create-contact]]
.Creating a contact
[cols="a,a"]
|====
|Setting |Explanation

2+|*Details*

|*Form of address*
|Select the option from the drop-down menu. This selection is optional. +
*Ms.* = Female form of address +
*Mr.* = Male form of address

|*Title*
|Enter the title of the contact, if required.

|*First name*, *Last name*
|Enter the first and last name of the contact.

|*Client*
|Select the client from the drop-down menu in order to assign the contact to this client. +
Only those clients will be displayed that have a name entered for them in the *System » Client » Select client » Settings* menu.

|*Language*
|Select the language for the contact. If you have created a template in the *System » Client » Select client » Email » Templates* menu in the same language that you have selected here, email templates will be sent to the contact in this language.

|*Type*
|Select the type. The types *Customer*, *Sales representative*, *Supplier*, *Partner*, *Manufacturer* and *Interested party* can be selected by default. Create further types in the <<crm/managing-customer-data#300, System » CRM » Types>> menu.

|*Class*
|Select the class. Classes serve as an internal distinction between customers and which discount will be granted this class, for example. Go to <<crm/managing-customer-data#100, System » CRM » Customer classes>> to create further classes. If you want to offer different prices to end customers and sellers in the online store, then this can be done with the *Display of the prices in the online store* option in the configuration of the classes. It is very common that gross prices are displayed for end customers (B2C) in the online store and net prices for sellers (B2B). +
Empty option = No assignment to a class +
*_Important:_* If there is no assignment to a class, the contact will be automatically assigned to the class with the lowest position. As the price display in the online store is configured for each class, check this option for the class with the position 1 so that the correct price is displayed during automatic assignments.

|*Feedback*
|Give feedback about the contact for internal use. Select five red stars for the worst and five yellow stars for the best rating.

|*Customer number*
|Enter a customer number for the contact, if required. Customer numbers can be assigned for internal purposes. They will not be saved automatically. You decide whether and how you would like to use customer numbers.

|*Owner*
|Select the owner for the contact. If you do not want to select an owner, select the empty option. Only owners for whom the *Customer* option has been activated can be selected from the drop-down menu. Go to *System » Settings » User » Account » Open user » Tab: Owner* to activate owners.

|*Date of birth*
|Enter the date of birth of the contact in the format yyyy-mm-dd or select it from the calendar.

|*Newsletter*
|Displays if the contact receives the newsletter. It is not possible to activate this option manually. In order to exclude the contact from receiving the newsletter, click on *Delete newsletter*.

|*Blocked*
|Select whether or not the contact should be blocked for the specific client. +
If the option is activated, the contact will be blocked and can no longer log into the online store. If the option is deactivated, the contact will be able to log into the online store.

2+|*Company*

|*Name*
|Enter the name of the company. This is a mandatory field.

|*VAT number*
|Enter the value added tax identification number of the contact, if required. The VAT number needs to be specified if you are sending items to a commercial purchaser in another country within the EU (intra-community delivery) and you want net totals to be calculated for the order. +
After having entered the VAT number, go to <<order-processing/orders/accounting#400, System » Client » Select client » Locations » Select location » Accounting>> and select *Net invoice* for the option *VAT number*. This causes invoices to be issued without VAT for contacts who have a VAT number saved in their data record. +
*_Important:_* The net setting does not go into effect if you saved tax rates for the customer's country of delivery.

|*Value date*
|Enter the time period (starting when the invoice is created) when you wish for an additional time period before the *payment due date* time period begins. Pay attention to the box *Info: Example terms of payment* below the table. +
*_Important:_* The value date in the contact details can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *System » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Payment due date*
|Enter the number of days when the payment will be due for the contact. This payment due date has priority over the payment due date saved for the <<crm/managing-customer-data#100, customer class. The payment due date can also be saved as an optional field on documents such as <<order-processing/orders/order-documents/generating-invoices, invoices>>. The invoice's payment due date would be used if no other payment due date was saved in the contact details or the customer class. Pay attention to the box *Info: Example terms of payment* below the table. +
*_Important:_* The value date in the contact details can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *System » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Days for early payment discount*
|Enter the number of days (starting when the invoice is created) in which the contact can pay the pending amounts at a discounted price. Pay attention to the box *Info: Example terms of payment* below the table. +
*_Important:_* The early payment discount in the contact details can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *System » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Percentage for early payment discount*
|Enter the value in percent that the contact may subtract if he or she makes the payment within the time period *Days for early payment discount*. Pay attention to the box *Info: Example terms of payment* below the table. +
*_Important:_* The early payment discount in the contact details can only be selected for companies, but not for private persons. It is, however, possible to save a value for the payment due date in the invoice. To do so, go to *System » Client » Select client » Locations » Select location » Documents » Invoice*.

|*Owner*
|Select the owner from the drop-down menu.

2+|*Contact options*

|*Type*
|Select the type, e.g. email, telephone or website from the drop-down menu.

|*Sub-type*
|Select the sub-type from the drop-down menu, e.g. business or private.

|*Value*
|Enter the value, e.g. the business email address.
|====

[TIP]
.Info: example terms of payment
====
You can use the options Value date, Payment due date, Days for early payment discount and Percentage for early payment discount to set up the following payment conditions:

60 days value date, 30 days net (payment due date), 10 days with a 2 % early payment discount

Explanation: The contact receives a 2% discount if he or she pays within 10 days. The payment is late after a total of 91 days. When incoming payments are imported and assigned, they will automatically be checked internally to see whether the contact's early payment discount is valid. If the early payment discount time period has expired, then the order will receive the status *Partial payment received*. The terms of payment listed above will automatically be applied to the order and e.g. to the <<order-processing/orders/order-documents/generating-invoices#, invoice>> and can be changed within the order as well. When the invoice is printed, these terms will be combined into valid payment conditions for this order. The value date and payment due date are added together to create one date when the payment is due. Despite the value date and payment due date being added together, the following is displayed on an invoice:
Payment conditions: Value date in 60 days, 2% early payment discount if paid within 10 days. Within 30 days due net. If a value for *Value date* is saved for a contact, then this value is used for the document. Otherwise, the value saved under Payment due or the value from the customer class is used. The last possibility is to use the number of days entered for the *Payment due date* option for the document. These are set up in the <<order-processing/orders/order-documents/#130, Optional elements in the stock unit table>> section. Important: These options are only applied to the total gross value of an invoice.
====

[#200]
=== Searching for a contact

In the *Filter* view, you can search for contacts according to specific criteria. The contacts found will be listed in the *Overview* view. The overview currently displays the following information: ID, company, first name, last name, email address, telephone number, number of orders, postcode and country. How you edit contact data is described in the <<crm/managing-contacts#300, Editing a contact>> chapter.

[TIP]
.Sending emails directly from the overview
====
Send an email to your contact directly from the contact overview. Click on the email address to automatically open your email programme.
====

In order to search for specific contacts, enter a search term in the search fields or select the appropriate drop-down menu settings. You can enter multiple search terms into the search fields at one time. This makes your search run quicker and be more accurate.

[.instruction]
Searching for a contact:

. Go to *CRM » Contacts*.
. In the *Filter* view, enter the search term in the search field or set the filter options in the drop-down menus. Pay attention to the information given in <<table-filter-contacts>>.
. Click on *Search*. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open. As an alternative, open the context menu by clicking right in order to access the views of the contact such as *New order* or *New note*.

[[table-filter-contacts]]
.Filters for contacts
[cols="a,a"]
|====
|Setting |Explanation

|*Search*
|Click on *Search* without selecting any filter settings. This will display all contacts. Alternatively, limit the search results by using filters and click on *Search*. The contacts found will be listed in the overview.

|*Reset*
|Resets the filter criteria that was entered.

|*ID*
|Each contact automatically receives a consecutive and unique ID. It doesn't matter if the data record was saved manually or automatically. Two contacts never have the same ID. The ID is always a real number. "00521" or "ADF8354" e.g. are invalid. 

|*Name*
|Enter the first name and/or last name or the name of the company to search for the contact with this name or company name. The search is also carried out for names and company names that are saved in the address data records of the contact. It is also possible to search only for parts of the name or company name.

|*Address*
|Enter the name of the street and/or the postcode that is saved for the contact. It is also possible to search only for parts of the street and parts of the house number.

|*Postcode*
|Enter the postcode that is saved for the contact. The search is also carried out for postcodes that are saved in the address data records of the contact. It is also possible to search only for parts of the postcode.

|*Town*
|Enter the town that is saved for the contact. The search is also carried out for towns that are saved in the address data records of the contact. It is also possible to search only for parts of the town.

|*Email*
|Enter the email address to search for the contact with this email address. It is also possible to search only for parts of the email address.

|*Country*
|Select a country to only display contacts from this country. The country is saved within the contact data.

|*Owner*
|Select the owner to only search for contacts with this owner. The owner must be saved in the contact data record. +
*_Important:_* You can only select users from the drop-down menu who are activated for the *Customer* option in the *Owner* tab of their user account.

|*Type*
|Select the type to only search for contacts with this type.

|*Client*
|Select a client to only display contacts that correspond to this client. The client is saved within the contact data. +
*_Important:_* Variable users can only select those clients that they have a right to access. Variable users are given rights within the <<basics/working-with-plentymarkets/manage-users#90, Right>> tab in the *System » Settings » User » Accounts* menu.

|*Referrer*
|Select the referrer to only search for contacts with this referrer.
|====

[#210]
=== Linking the contact to a company

If you have created the contact without linking it to a company, you can link them afterwards as well. In order to avoid confusion with companies having the same name, the town, street and country of the company will also be displayed next to the company name.

Enter at least three characters of the company name, town, street or country. Your plentymarkets system will suggest company data records that have already been saved.

[.instruction]
Linking the contact to a company:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Enter the name of the company, town, street or country in the entry field of the *Company* section. +
→ Once you have entered three characters, company data records that have already been saved will be suggested.
. Select the company data record from the drop-down menu.
. *Save* the settings. +
→ All company-related data will be displayed in the detail view of the contact.

[#220]
=== Creating a company

Create the company and save data such as the VAT number, payment due date and early payment discount as a percentage value.

[.instruction]
Creating a company:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. In the *Company* section, click on *Add new company*.
. Carry out the settings. Pay attention to the information given in <<table-create-contact>> in the *New company* section.
. *Save* the settings. +
→ The detail view of the contact will open.
. *Save* the settings.

[#230]
=== Editing the company

You can edit company data that has already been saved at any time. Note that the data of the already existing company data record will be overwritten.

[.instruction]
Editing the company:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Edit* in the *Company* section.
. Carry out the changes as desired. Pay attention to the information given in <<table-create-contact>> in the *New company* section.
. *Save* the settings. +
→ The data of the edited company will be overwritten and the data of the newly created company will be displayed in the detail view of the contact.

[#240]
=== Deleting the link between company and contact

You can delete the link between the company and the contact in the detail view of the contact. Note that you only delete the link and not the company data itself. The company data will still be displayed as a suggestion after you have entered at least three characters of the company name, the town, the street or the country.

[.instruction]
Deleting the company:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click in the entry field in the *Company* section.
. Select the empty option.
. *Save* the settings. +
→ The link between the company and the contact will be deleted.


[#300]
=== Editing a contact

Search the contact by means of the <<crm/managing-contacts#200, filter settings>>. Open the contact by clicking in the line of the contact to edit the contact's data such as the date of birth, telephone number and email address, for example. You will find explanations of the settings and options in <<table-create-contact>> in the <<crm/managing-contacts#200, Creating a contact>> chapter. Click on *Delete contact option* to delete the contact options.

[.instruction]
Editing a contact:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Carry out the changes as desired. Pay attention to the information given in <<table-create-contact>> in the <<crm/managing-contacts#100, Creating a contact>> chapter.
. *Save* the settings.

[#350]
=== Converting a guest account into a regular account

If the contact has placed an order in your online store as a guest, this account type will be saved as contact option in the detail view of the contact. Guest accounts have the value 1. Delete the contact option with the value 1 in order to convert the guest account into a regular account.

[.instruction]
Converting a guest account into a regular account:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. In the *Contact options* area, click in the line of the account type (type: *Account*, subtype: *Guest*, value: *1*) on *Delete contact option*.
. *Save* the settings. +
→ The account type will be changed from *Guest account* to *Regular account* in the history of the contact.

[TIP]
.Inform the contact
====
Send your customer an email and inform him or her about the change. He or she can then create a password to be able to log into your online store.
====

[#400]
=== Deleting a contact

You can delete individual contacts. All addresses that are assigned to the contact will be deleted if they are not linked to an order.

[.instruction]
Deleting a contact:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Delete contact* in the context menu or click on *Delete* above the detail view. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The contact will be deleted and removed from the overview.

[#500]
== Displaying the history

Each data record contains the history of a contact. The history includes e.g. how long the contact has been registered and when he or she has been logged into your online store for the last time and when the last order was generated. This data will be automatically updated and cannot be changed.

[.instruction]
Displaying the history:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open and the history will be displayed in the right section below the *contact options*.
. Pay attention to the information about the history given in <<table-contact-history>>.

[[table-contact-history]]
.History in the *CRM » Contacts » Open contact* menu
[cols="a,a"]
|====
|Setting |Explanation

|*Registered since*
|Date and time when the contact has first registered.

|*Updated*
|Date and time when the data record of the contact has been updated for the last time.

|*Account type*
|Account via which the contact has registered. +
*Regular account* = The contact has newly registered in your online store or the data record has been manually created in the back end. +
*Guest account* = The contact has registered and ordered as a guest.

|*Last order*
|Date and time when the last order was made. If no order has been placed, *No data* is displayed in this field.

|*Last login*
|Date and time when the contact was logged in for the last time. If the contact was not logged in, *No data* is displayed in this field.
|====

[#510]
== Carrying out the group function

Use the group function to send an email template, print address label or add a contact to a newsletter folder. This can be done simultaneously for one or multiple contacts.

[.instruction]
Carrying out the group function:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click on *Group function*.
. Activate one or multiple procedures and select the options from the drop-down menus. Pay attention to the information given in <<table-contact-group-function>>.
. Activate the contact(s) that you would like to carry out the procedure for.
. Click on *Group function* to carry out the selected procedures for the activated contacts.

[[table-contact-group-function]]
.Group function in the *CRM » Contacts* menu
|===
|Procedure |Explanation

|*Print address label*
|Prints the label selected from the drop-down menu for all activated contacts. +
*_Important:_* The address label template must have been <<order-processing/fulfilment/generating-documents#400, created>> in the *System » Orders » Documents » Address label* menu beforehand. Whether the primary invoice address or the primary delivery address of the contact will be printed, depends on the setting in the address label template.


|*Send email template*
|Sends the template selected from the drop-down menu to all activated contacts. +
*_Important:_* The email template must have been <<crm/sending-emails#1200, created>> in the *System » Client » Select client » Email » Templates* menu beforehand.

|*Add to newsletter folder*
|Copies the email addresses of the activated contacts to the email folder selected from the drop-down menu. The email addresses will be listed in the *System » CRM » Newsletter » plentymarkets » Email folder* menu.

|===

[#590]
== Managing addresses

In the following sub-chapters, you will learn how to add new addresses for your contact, display all addresses that are saved for the contact as well as edit and delete existing addresses.

[#600]
=== Adding an address

You can add as many addresses and as address options as you like. Address options are for example, the VAT number or the telephone number of the contact.

[.instruction]
Adding an address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *New address* in the context menu.
. Carry out the settings in the *New address* section. Pay attention to the information given in <<table-add-address>>.
. In the *Address options* section, select the type from the drop-down menu and enter the value. Pay attention to the information given in <<table-add-address>>. +
→ By clicking on *Add address option*, you can add further address options.
. *Save* the settings. +
→ The address will be added to the overview in the *Addresses* section.

[[table-add-address]]
.Adding an address
[cols="a,a"]
|====
|Setting |Explanation

2+|*New address*

|*Form of address*
|Select the form of address from the drop-down menu, if needed.

|*Name 1 (Company)*
|Enter the company name. This is a mandatory field when there is no entry under *First name* and *Last name*.

|*Name 2 (First name)*
|Enter the first name of the contact. This a mandatory field when there is no entry under *Company* and *Last name*.

|*Name 3 (Last name)*
|Enter the last name of the contact. This is a mandatory field when there is no entry under *Company* and *First name*.

|*Name 4 (Additional information)*
|If needed, enter additional information, e.g. c/o Mr. John Doe.

|*Address 1 (Street)* +
*Address 2 (House number)*
| Enter the street and house number. +
*Street* is a mandatory field when there is no entry under *House number* and *Additional address information*. *House number* is a mandatory field when there is no entry under *Street* and *Additional address information*.

|*Address 3 (Additional address information)*
|Enter additional address information if necessary, e.g. apartment 12a. This is a mandatory field when there is no entry under *Street* and *House number*.

|*Address 4 (Free)*
|This field can be freely used.

|*Postcode* +
*Town*
|Enter the postcode and town of the contact. This data will be used for the invoice address, for example. The order of the options *Postcode* and *Town* is reversed for certain countries, e.g. Germany. +
*Postcode* and *Town* are mandatory fields.

|*Country* +
*Region/County*
|Select the values from the drop-down menu. +
*_Important:_* The drop-down menu *Region/County* is not available for all countries.

|*Invoice address* / *Delivery address*
|Activate one or both options in order to determine the address type. +
The new address can either be the invoice address only, the delivery address only or both the invoice address and the delivery address. If both options are activated, an address with a new ID and two address types will be created. +
If one ore both options are activated, you can select for one or both options if the address is the primary address.

|*Primary*
|Activate the option if the new address is the primary invoice address or the primary delivery address. +
It is possible to activate both options if the new address is the primary invoice address as well as the primary delivery address.

2+|*Address options*

|*Type*
|Select the type, for example the Postnummer or the VAT number from the drop-down menu.

|*Value*
|Enter the value.
|====

[#700]
=== Displaying addresses

From the open contact, you can display all addresses that are saved for the contact. Besides the ID, company name, first and last name as well as address and country, you can see the address type – invoice address or delivery address – and whether the address is a primary address or not.

If multiple addresses are open, the IDs of the addresses will also be displayed in the drop-down menu of the open address data records.

Initially, the addresses of your contact are displayed in card view. By clicking on *Switch to table view*, the addresses will be displayed in a table. Your plentymarkets system will recognise which of the two views you selected. When opening the context menu *Addresses* the next time, the view that was selected last will be displayed.

Up to 25 address data records saved for the contact are displayed per page. If more than 25 addresses are saved for the contact, you can use the toolbar to browse between the pages, select a certain page and to change the number of address data records per page to 50, 75 or 100. Your plentymarkets system will recognise the number of address data records you selected per page. When opening the view *Addresses* the next time, the setting that was selected last will be displayed.

[.instruction]
Displaying addresses:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Addresses* in the context menu. +
→ All addresses that are saved for the contact will be displayed.
. Click on *Edit* in order to open the detail view of the address. +
→ If you selected the table view, click in the line of the address in order to open the detail view.

[#800]
=== Editing the address

You can edit addresses as well as address options at any time. Pay attention to the information given in the <<crm/managing-contacts#600, Adding an address>> chapter. Click on *Delete address option* to delete the address options.

[.instruction]
Editing the address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Addresses* in the context menu. +
→ All addresses that are saved for the contact will initially be displayed as cards.
. Click on *Edit* in the address card that you want to edit. +
→ The detail view of the address will open.
. Carry out the changes as desired. Pay attention to the information given in <<table-add-address>> in the <<crm/managing-contacts#700, Adding an address>> chapter as well as to the information about the toolbar given in <<table-edit-address>>.
. *Save* the settings.

[[table-edit-address]]
.Editing the address
[cols="a,a"]
|====
|Setting |Explanation

|*Save*
|Saves the settings.

2+|*Invoice address*

|*Derive new invoice address*
|Creates a new invoice address based on the currently selected address. In order to create a new address with a new ID, changes must be made to the data of the new invoice address.

|*Add invoice address type*
|Adds the *Invoice address* type to the address. The ID does not change. +
If the type *Invoice address* has already been added for the address, this option will not be visible.

|*Delete invoice address type*
|Deletes the *Invoice address* type from the address. +
If the type *Invoice address* has not been added for the address, this option will not be visible.

|*Define as primary invoice address*
|The currently selected invoice address will be defined as primary invoice address. The ID does not change. +
If the *Invoice address* type is not selected, this option will be deactivated. +
If the invoice address has been defined as primary, this can be undone by clicking on *Reset primary invoice address*.

|*Convert to invoice address* / +
*Convert to delivery address*
|Converts the currently selected address to an invoice address or a delivery address. The ID does not change. +
If both address types are selected, this option will be deactivated.

2+|*Delivery address*

|*Derive new delivery address*
|Creates a new delivery address based on the currently selected address. In order to create a new address with a new ID, changes must be made to the data of the new delivery address.

|*Add delivery address type*
|Adds the *Delivery address* type to the address. The ID does not change. +
If the type *Delivery address* has already been added for the address, this option will not be visible.

|*Delete delivery address type*
|Deletes the *Delivery address* type from the address. +
If the type *Delivery address* has not been added for the address, this option will not be visible.

|*Define as primary delivery address*
|The currently selected delivery address will be defined as primary delivery address. The ID does not change. +
If the *Delivery address* type is not selected, this option will be deactivated. +
If the delivery address has been defined as primary, this can be undone by clicking on *Reset primary delivery address*.

|*Delete address data record*
|Completely deletes the address data record.
|====

[#900]
=== Deleting an address

If the address is not an invoice address that is linked to an order, you may delete the address. This may be necessary, if the delivery address of the contact is outdated, for example.

[NOTE]
.Deleting invoice addresses that are linked to an order is not possible
====
If the address is of the type *Invoice address* and if it is linked to an order, you cannot delete the address. An error message will be displayed.
====

[.instruction]
Deleting an address:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Addresses* in the context menu. +
→ All addresses that are saved for the contact will initially be displayed as cards. +
. Click on *Delete* in the address card that you want to delete. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The address will be deleted and removed from the overview.

[#990]
== Managing orders

In the following sub-chapters, you will learn how to display all orders that are available for the contact as well as create new orders for your contact.

[#1000]
=== Displaying orders

Within the open contact, you can access all orders of the contact in the *Orders » Edit orders* menu. When switching to the order menu, it will be searched automatically for orders from contacts with this ID.

[.instruction]
Displaying orders:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Orders* in the context menu. +
→ All orders that are saved for the contact will be displayed in the *Orders » Edit orders* menu. +
. Click in the line of the order to display further information about the order.

You can also edit the order. Orders can be edited as long as no document has been generated for this order. Further information about orders can be found on the <<order-processing/orders/managing-orders, Managing orders>> page of the manual.

[#1100]
=== Creating an order

Within the open contact, you can create a new order for the contact with only one click. If the contact has ordered in your online store, the order will be automatically saved in your plentymarkets system. In case of orders via telephone, for example, you will create the order manually. Proceed as described below.

[.instruction]
Creating an order:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *New order* in the context menu. +
→ You will directly access the *New order* area in the *Orders » Edit orders* menu. +
. Carry out the settings. Pay attention to the information given on the <<order-processing/orders/managing-orders#. Managing orders>> page of the manual.
. *Save* the settings.

[#1110]
=== Creating a multi-order

The Multi-order function makes it possible for you to take all of the unpaid orders that belong to a contact and then compile them into one multi-order. This might be useful if you have agreed upon with your contact that he or she does not pay each invoice individually, but pays all invoices per month or per quarter, for example.

As usual, the orders will be processed and the items will be sent, but left unpaid. Creating a multi-order is only possible for orders that have not been paid yet.

Click on *New multi-order* to summarise all orders of the contact into one multi-order. Beforehand, you determine which conditions such as the order type and the order status must be fulfilled to allow for a multi-order to be created. Carry out this setting in the *System » Orders » Order types » Multi-order* menu.

[.instruction]
Creating a multi-order:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *New multi-order* in the context menu. +
→ The multi-order will be created.

After you have successfully created the multi-order, it will open automatically in the *Orders* menu. Open the *Receipts* tab in the multi-order to create a multi-invoice.

For further information, refer to the <<order-processing/orders/multi-orders#, Multi-order>> page of the manual.

[#1150]
== Displaying the scheduler

In the *Scheduler* view, subscription orders of the contact will be displayed. Moreover, you can create new scheduled orders here. The scheduler allows your customers to subscribe to certain items in your online store. The menu is only visible in your plentymarkets system if you booked it. Go to *Start » Service centre » Tab: Systems » Tab: Contract* to book the scheduler. Go to *System » Orders » Scheduler* to carry out the settings for your online store.

[.instruction]
Displaying the scheduler:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Scheduler* in the context menu. +
→ All scheduler orders that are saved for the contact will be displayed.
. Pay attention to the explanations on the <<order-processing/orders/scheduler#, Scheduler>> page of the manual.

For further information, refer to the <<order-processing/orders/scheduler#, Scheduler>> page of the manual. The filter options are also described there. You can use the filter options both in the *CRM » Contact » Open contact » Tab: Scheduler* menu and in the *Orders » Scheduler » Scheduled orders* menu.


[#1190]
== Managing tickets

In the following sub-chapters, you will learn how to create tickets and display all tickets that are available for your contact. Depending on which plentymarkets tariff you use, you may have to book the ticket system before you are able to use it.

[#1200]
=== Creating a ticket

Use the <<crm/using-the-ticket-system#, ticket system>> in plentymarkets to manage your customer communication. The following chapter explains how you can create a new ticket directly from the open contact.

[.instruction]
Creating a ticket:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *New ticket* in the context menu. +
→ You will directly access the *New ticket* area in the *CRM » Ticket system* menu. The contact ID is already pre-filled. +
. Carry out the settings. Pay attention to the information given on the <<crm/using-the-ticket-system#1600, Using the ticket system>> page of the manual.
. *Save* the settings.

[#1300]
=== Displaying tickets

From the open contact, you can display all tickets that are saved for the contact in the *CRM » Ticket system* menu. When switching to the ticket menu, it will be searched automatically for tickets from contacts with this ID.

[.instruction]
Displaying tickets:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Tickets* in the context menu. +
→ All tickets that are saved for the contact will be displayed.

You have the possibility to edit and delete tickets. For further information, refer to the <<crm/using-the-ticket-system#, Using the ticket system>> page of the manual.

[#1390]
== Managing notes

In the following sub-chapters, you will learn how to create new notes for your contact, display all notes that are available for your contact as well as edit and delete existing notes. Notes are only visible in your plentymarkets back end and cannot be accessed by your contacts.

[#1400]
=== Creating a note

You can save as many notes for your contacts as you like. Notes are only visible in your plentymarkets back end. This means that contacts cannot see the saved notes in your online store. Each note automatically receives a consecutive and unique ID. New texts can be entered by typing them in or by inserting them using the clipboard. Use the functions in the toolbar to format the text, insert links and upload image files.

[.instruction]
Creating a note:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *New note* in the context menu. +
→ The *New note* window will open.
. Enter the text, insert text via the clipboard and format the text using the functions in the toolbar.
. *Save* the settings. +
→ The *Notes* section will open and the note will be added to the overview.

[#1500]
=== Displaying notes

From the open contact, you can display all notes that are saved for the contact in form of cards. The cards show the creation date with timestamp, the name of the user that created the note as well as the ID.

[.instruction]
Displaying notes:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Notes* in the context menu. +
→ All notes that are saved for the contact will be displayed.

[.subhead]
Opening an individual note

You can open individual notes by clicking on *Open preview*. If more than one note of the contact is open, a triangle will appear in the view. Click on the triangle to quickly and easily switch between the open notes. Click on the cross to close the note and remove it from the list.

[#1600]
=== Editing a note

Edit notes to update contents. You can format the text, insert links and upload image files.

[.instruction]
Editing a note:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Notes* in the context menu. +
→ All notes that are saved for the contact will be displayed.
. Click on *Edit* in the card of the note that you want to edit.
. Carry out the changes as desired.
. *Save* the settings.

[#1700]
=== Deleting a note

The notes for your contacts can be deleted if the information saved in the notes is outdated or if you do not need it any longer.

[.instruction]
Deleting a note:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Notes* in the context menu. +
→ All notes that are saved for the contact will be displayed.
. Click on *Delete* in the card of the note that you want to delete. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The note will be deleted and removed from the overview.

You can also delete the note when the preview is open. Click on *Delete* in the open note. In this case, a window will open and you need to confirm your decision by clicking on *Delete*.

[#1710]
== Managing documents

In the following sub-chapters, you will learn how to upload, display, download and delete documents. The documents that you have uploaded in this menu are only visible in your plentymarkets back end and cannot be accessed by your contacts.

[#1720]
=== Uploading a document

In the *Documents* view, you can upload documents that relate to your contact. For example, this document could be an age check that you have performed before sending items to the contact for the first time. Either you upload the files by clicking on *Upload file* or via the drag & drop function. You can also create folders to group documents in a clearly structured way.

You can upload the data formats JPEG, PNG, GIF, TIFF, PDF, DOC, ODC, OTH, XLS, XML, HTML, HTM, CSS, ZIP and GZIP.

[.instruction]
Uploading a document:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Documents* in the context menu.
. Upload the file to the folder by clicking on *Upload file* or by using the drag & drop function. +
→ The file is uploaded and displayed in the overview.

[NOTE]
.Creating a folder
====
Create folders in the *Documents* view if you have already uploaded or plan to upload a lot of files about your contact. This allows to group the documents and have a better overview.
====

[#1730]
=== Displaying documents

In the *Documents* view, you will see all documents related to the contact that you have uploaded. In the overview, you can see the file name, the size of the file as well as the date and the time of the last change.

[.instruction]
Displaying documents:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Documents* in the context menu. +
→ All documents that are saved for the contact will be displayed.

[#1740]
=== Downloading a document

You can download all files that you have uploaded for the contact.

[.instruction]
Downloading a document:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Documents* in the context menu. +
→ All documents that are saved for the contact will be displayed.
. Click on *Download* in the line of the document that you want to download. +
→ The window to determine the storage location will open.
. Select the storage location on your computer and save the document.

[#1750]
=== Deleting a document

If you do not need a document any longer, you can delete it. How to delete multiple documents at the same time is described in the box at the end of this chapter.

[.instruction]
Deleting a document:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Documents* in the context menu.
. Click on *Delete* in the line of the document that you want to delete. +
→ A window will open and you need to confirm your decision. +
. Click on *Delete*. +
→ The document will be deleted and removed from the overview.

[TIP]
.Deleting multiple documents or all documents
====
In the *Documents* view, activate the documents that you want to delete or activate the option next to *File name* to activate all documents and save them afterwards. After you have confirmed your decision by clicking on *Delete*, the activated documents will be deleted and removed from the overview.
====

[#1800]
== Displaying the account balance

The *Account* view lists the revenues of your contacts. In the top line, you see the total of the contact's invoices, the amount granted to your customer in form of credit notes and the difference between the two amounts. Orders and credit notes are listed as processes in the table. The *Paid* and *Outstanding* columns are especially helpful. If a payment for an order is listed in the *Outstanding* column, then the contact still has to pay the amount. As soon as this is done, the amount will be listed under *Paid*. If a payment for a credit note is listed in the *Outstanding* column, then you still have to pay this amount to the contact. As soon as this is done, the amount will be listed under *Paid*.

[.instruction]
Displaying the account balance:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Account* in the context menu. +
→ All data that is available for the account of the contact will be displayed.
. Pay attention to the information given in <<table-display-account-balance>>.

[[table-display-account-balance]]
.Settings in the *CRM » Contacts » Open contact » View: Account*
[cols="a,a"]
|====
|Setting |Explanation

|*Balance*
|Shows the customer's account balance. +
*+* = total of the contact's outstanding payments +
*-* = total of payments that still have to be paid to the contact if the contact has paid too much or if a credit note still has to be paid out. +
*0.0* = No outstanding amounts

|*Invoices*
|Total invoice amounts of all orders and the number of invoices in parentheses

|*Credit notes*
|Total of all credit notes and the number of credit notes in parentheses

|*Delta*
|Difference in percent between the paid credit notes and the total invoice amount paid by the customer. 0 % means that no credit note has been paid out to the customer yet. 100 % means that every amount paid by the customer has been paid back in form of credit notes.

|*Date*
|Date when the order was created

|*Order ID*
|ID of the order. Click on the ID to open the detailed view of the order. Credit note IDs are indented and displayed under the order.

|*Process*
|Type of order, either order or credit note

|*Document*
|Document number, e.g. invoice number. Click on the number to open the document.

|*Value*
|Invoice total of the order

|*Paid*
|Amount already paid

|*Payment method*
|Payment method for the order

|*Outstanding*
|Remaining amount that is due before the order is completely paid for.

|*Status*
|Status of the order. Click on the status to open the editing window *Order status* and change the status, if required.

|====

[.subhead]
Filtering account data

Use filters to display the account data of your contact.

[.instruction]
Filtering account data:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Account* in the context menu. +
→ All data that is available for the account of the contact will be displayed.
. Carry out the settings in the *Filter* area. Pay attention to the information given in <<table-filter-account-data>>.
. Click on *Search*.

[[table-filter-account-data]]
.Filter settings in the *CRM » Contacts » Open contact » View: Account*
[cols="a,a"]
|====
|Setting |Explanation

|*Search*
|Perform a search. The account data that correspond to the search criteria entered will be displayed.

|*Reset*
|Resets the filter criteria that was entered.

|*Period*
|Select one of the following settings from the drop-down menu: *ALL*, *This year*, *Last year*, *This month*, *Last month* or *Last 3 months*.

|*Outstanding*
|Select *ALL*, *Yes* or *No*. +
*Yes* = Only outstanding amounts will be displayed. +
*No* = Only paid amounts will be displayed. +
*ALL* = Outstanding and paid amounts will be displayed.

|*Relational operator / Status*
|Select the relational operator and order status from the drop-down menu.

|*Invoice No.*
|Enter the invoice number.

|*Order ID*
|Enter the order ID.

|====

[#1890]
== Managing bank data

In the following sub-chapters, you will learn how to add new bank data for your contact as well as edit and delete existing bank data.

[#1900]
=== Adding bank data

In the *Bank data* view, you can add the bank data of your contact. You can add as many data records as you like.

After saving, the bank data will be displayed as cards. Beside the name of the holder and the IBAN, a tag will be displayed that shows whether the SEPA direct debit mandate is activated for the contact. If the BIC is saved in the bank data, this will also be shown on the card.

[.instruction]
Adding bank data:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Bank data* in the context menu.
. Click on *Add*. +
→ The *New bank data* view will be displayed.
. Carry out the settings. Pay attention to the information given in <<table-bank-data-contact>>.
. *Save* the settings.

[[table-bank-data-contact]]
.Settings in the *CRM » Contacts » Open contact » View: Bank data*
|===
|Setting |Explanation

|*IBAN*, *BIC*, *Holder*, *Account number*, *Sort code*
|Enter the bank data of the contact. *IBAN* and *Holder* are mandatory fields.

|*Name, street, postcode and town of the bank*
|Enter the name and address of the bank.

|*Country of the bank*
|Select a country from the drop-down menu.

|*SEPA direct debit mandate*
|Activate this option once the contact has signed the SEPA direct debit mandate. +
*_Important:_* This option needs to be activated before pain.008 formats can be retrieved for <<order-processing/payment/managing-bank-details#200, SEPA payments>>.

|*Type of mandate*
|Only visible when the SEPA direct debit mandate has been activated. +
Select the option from the drop-down menu. +
*SEPA core direct debit* = Allows a biller to collect funds from a payer's account, provided that a signed mandate has been granted by the payer to the biller. +
*SEPA business to business direct debit* = Enables business customers in the role of payers to make payments by direct debit.

|*Payment frequency*
|Only visible when the SEPA direct debit mandate has been activated. +
Select the option from the drop-down menu. +
*One-time payment* = Is typically used for standard orders. +
*Recurring payment* = Is typically used for regularly occurring orders such as subscription orders, etc.

|===

[#2000]
=== Editing bank data

You can update the bank data of your contact at any time.

[.instruction]
Editing bank data:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Bank data* in the context menu.
. Click on *Edit* in the card of the bank data that you want to edit. +
→ The data record will open.
. Carry out the settings. Pay attention to the information given in <<table-bank-data-contact>>.
. *Save* the settings.

[#2100]
=== Deleting bank data

Delete the bank data of your contact if they are outdated.

[.instruction]
Deleting bank data:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Bank data* in the context menu.
. Click on *Delete* in the card of the data record that you want to delete. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The bank data will be deleted and removed from the overview.

[#2200]
== Managing events

In the following sub-chapters, you will learn how to add, display and delete contact events. If you want your contact to pay for a certain event, it is also possible to bill those events.

[#2300]
=== Adding an event

Add as many contact events as you like. For example, the event can be a call or an email. You can enter a duration, select information about the process and enter a comment about the event into the text field. If you would like to bill the event, click on *Add and bill* when adding the event.

[.instruction]
Adding an event:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Events* in the context menu.
. Select the type from the drop-down menu.
. Enter the duration of the event in minutes.
. Select the info from the drop-down menu.
. Enter the info text.
. Click on *Add event*. +
→ Select *Add and bill* or *Add*. The event will be added to the list.

[#2400]
=== Displaying events

You can display the events that you have saved for your contacts at any time.

It is also possible to update the duration of the event directly in the overview. How to update the duration is described in the box at the end of this chapter.

[.instruction]
Displaying events:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Events* in the context menu. +
→ A list of the events will be displayed.

[TIP]
.Updating the duration of an event
====
You can update the duration of existing events. To do so, click on *Update duration* in the event overview. The window *Update event duration* will open. Enter the new number in minutes and click on *Update*.
====

[#2500]
=== Deleting an event

Delete events that you no longer need.

[.instruction]
Deleting an event:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Events* in the context menu. +
→ A list of the events will be displayed.
. Click on *Delete* in the line of the event that you want to delete. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The event will be deleted and removed from the overview.

[#2600]
== Editing access data

In the *Access data* view, you can manually change the password for your contact, send a link to your contact to change the password, unblock the login and open the My account area of the contact using the login URL.

[#2700]
=== Changing the password

Manually change the password for your contact in the *Change password* area.

[.instruction]
Changing the password:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Access data* in the context menu.
. Enter the password twice in the *Change password* area.
. Click on *Save password*.

[#2800]
=== Sending a link to change password

Send your contact an email template containing a link in order that he or she can change the password in your online store. It is required that you have linked an email template containing the template function *{% Link_ChangePassword() %}* to change the password with the event *Send customer email to change password*. Carry out this setting in the *System » Client » Select client » Email » Automatic* menu.

For further information about sending emails automatically, refer to the <<crm/sending-emails#2300, Sending emails>> page of the manual.

[.instruction]
Sending a link to change password:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Access data* in the context menu.
. Click on *Send link to change password*. +
→ The contact will receive an email containing the link to change the password in your online store.

[#2900]
=== Unblocking the login

Once your contact has entered the incorrect password in your online store several times in succession, the login will be blocked for the contact for a certain time. By clicking on *Unblock login*, you unblock the login and your contact is able to log into the your online store again.

[.instruction]
Unblocking the login:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Access data* in the context menu.
. Click on *Unblock login*. +
→ The contact is now able to log into your online store.

[#3000]
=== Opening the My account area of the contact

In the *Login URL* area, you can see the URL for directly accessing the contact's My account area in the online store. If you use this URL, then you are no longer required to enter login details (email address and password) in the online store.

In order that the login URL will be created, both the email address in the *Contact options* area of the *CRM » Contacts » Open contact* menu and the password in the *CRM » Contacts » Open contact » View: Access data* must be saved. The login URL will be generated after the data is saved. Make sure to use a secure password. Otherwise an error message will be displayed.

[.instruction]
Opening the My account area of the contact:

. Go to *CRM » Contacts*.
. Search the contact by means of the filter settings as described in the <<crm/managing-contacts#200, Searching for a contact>> chapter. +
→ The contacts that correspond to the search criteria entered will be displayed.
. Click in the line of the contact. +
→ The detail view of the contact will open.
. Click on *Access data* in the context menu.
. Click on *Open link* in the *Login URL* area or copy the login URL to the clipboard by clicking on *Copy to clipboard* and insert the link into the browser. +
→ The My account area of the contact in the online store will open.

[#4000]
== Managing properties

Properties are frequently occurring information that you can use in different areas of plentymarkets. Properties are centrally managed in the *System » Settings » Properties* menu.





[WARNING]
.Important notes about the contact properties
====
Note that contact properties in the *CRM » Contacts » Open contact » View: Properties* will only be available in a short while. The properties can then be added and displayed in the plentymarkets back end only. That means that it will not be possible for the contact to save data in your online store, e.g. during the order process or when he or she registers in your online store. This functionality is currently being developed.

You can, however, already create properties in the *System » Settings » Properties* menu and also add values for the properties.

*_Important:_* A migration is planned for the properties that you created in the past in the *System » CRM » Properties* menu. That means that you do not have to transfer these properties to the new *System » Settings » Properties* menu. We will inform you about the point in time in the link:https://forum.plentymarkets.com/c/changelog[Changelog^] category of the plentymarkets forum.

====

[#4100]
=== Creating a property

Go to *System » Settings » Properties* to create properties that you will later use for characterising your contacts.





Proceed as described below to create a property.

[.instruction]
Creating a property:

. Go to *System » Settings » Properties*. +
→ The overview of the properties will open.
. Click on *Add property*.
. Select the *Contact* option from the *Section* drop-down menu.
. Carry out the additional settings. Pay attention to the information given in <<table-create-property>>.
. *Save* the settings. +
→ The property is created and opened for editing.

[[table-create-property]]
.Creating properties
[cols="1,3"]
|====
|Setting |Explanation

|*Section*
|Select a section from the drop-down menu where the property should be used. +
  +
  +
*Contact* = Property will be used for contacts. +

|*Property type*
|Select the property type from the drop-down menu. +
*None* = No property type +
*Whole number* = Allows to enter a whole number. +
*Decimal number* = Allows to enter a number with decimal places. +
*Selection* = Allows to select multiple options. +
*Short text* = Enter short text. +
  +
*Text* = Enter text. +
  +
*Text* = Allows to enter a date. +


|*Name*
|Enter the name for the property. +
  +
*_Note:_* The name of the system language is displayed by default. After the property has been created, you can save the name in English. Further languages are planned.

|*Description*
|Enter the description of the property. +
*_Note:_* The description of the system language is displayed by default. After the property has been created, you can save the description in English. Further languages are planned.

|*Group*
|Select a property group from the drop-down menu to assign the property to this group. This is optional. +
*_Tip:_* Click on *Add property group* to create a group.

|*Position*
|Enter the position number for the property. Properties are sorted by the position number in ascending order. +
*_Tip:_* Count by tens when creating position numbers. This will allow you to easily add new properties in between.
|====

[#4200]
=== Editing a property

Properties are centrally managed in the *System » Settings » Properties* menu. Change the settings that are described in <<table-create-property>>.

[.instruction]
Editing a property:

. Go to *System » Settings » Properties*.
. Click on *Search* to display all properties or select filters to limit the search results.
. Click on the property. +
→ The *General* tab will open.
. Edit the settings. Pay attention to the information given in <<table-edit-property>>.
. *Save* the settings.

[[table-edit-property]]
.Editing a property
[cols="1,3"]
|====
|Setting |Explanation

2+|*General*

|*Position*
|Enter the new position to change the order of the properties.

|*Mandatory field* (currently without function)
|Activate this option to make sure that the property will be a mandatory entry. Mandatory fields are displayed in bold in the detail view of the contact in the *Properties* area and in the order process. +
*_Note:_* This setting is currently without function.

|*Order process* (currently without function)
|Activate this option to make sure that the property will be displayed in the order process. +
*_Note:_* This setting is currently without function.

|*Customer registration* (currently without function)
|Activate this option to make sure that the property will be displayed in the customer registration. +
*_Note:_* This setting is currently without function.

|*Name*; +
*Description*
|For multilingualism, enter name and description for other languages. +
*_Note:_* Currently, names and descriptions can only be saved in German and English. Further languages are planned.

2+|*Visibility*

|*Client*
|Select one or more clients that the property should be activated for.

|*Visibility*
|Select one or more types that the property should be visible for.

2+|*Values*

|Only visible for property type *Selection*
|Enter the values that should be displayed in the drop-down menu. +
Click on *Add value* to create a value. +
*Name* = Enter a name for the property value.
|====

[#4300]
=== Searching for a property

Properties are centrally managed in the *System » Settings » Properties* menu. After opening the menu, start the search to display the properties. In order to search for specific properties, enter a search term in the search fields. The drop-down menus will help you to search for properties that share specific criteria. You can combine as many search filters as you like.

[.instruction]
Searching for a property:

. Go to *System » Settings » Properties*.
. In the *Filter* view, enter the search term in the search field or set the filter options in the drop-down menus. Pay attention to the information given in <<table-filter-properties>>.
. Click on *Search*. +
→ The properties that correspond to the search criteria entered will be displayed.
. Click in the line of the property. +
→ The detail view of the property will open.

[[table-filter-properties]]
.Filters for the properties
[cols="a,a"]
|====
|Setting |Explanation

|*Search*
|Click on *Search* without selecting any filter settings. This will display all properties. Alternatively, limit the search results by using filters and click on *Search*. The properties found will be listed in the overview.

|*Reset*
|Resets the filter criteria that was entered.

|*ID*
|Each property automatically receives a consecutive and unique ID.

|*Name*
|Enter the name to search for the property with this name. It is also possible to search only for parts of the name.

|*Language*
|Select a language to only display properties for which a name has been saved in this language.

|*Group*
|Select the group to only display properties that are assigned to this group. +
Select *Not grouped* to only display properties that are not assigned to a group. +
Select *Grouped* to only display properties that are assigned to a group.

|*Section*
|Select a section to only display properties that are used in this section.

|*Property type*
|Select a property type to only display properties of this type.
|====

[#4400]
=== Deleting a property

You can delete one or more properties at the same time.

[#4500]
==== Deleting a property

Proceed as described below to irreversibly delete a property if it is no longer needed.

[.instruction]
Deleting a property:

. Go to *System » Settings » Properties*.
. Start the search and, if required, select filters to restrict the search results.
. Click on the property. +
→ The detail view of the property will open.
. Click on *Delete property*. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The property will be deleted and removed from the overview.

[#4600]
==== Deleting multiple properties

Proceed as described below to irreversibly delete multiple properties if they are no longer needed.

[.instruction]
Deleting multiple properties:

. Go to *System » Settings » Properties*.
. Start the search and, if required, select filters to restrict the search results.
. Activate the properties that you want to delete.
. Click on *Delete*. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The selected properties will be deleted and removed from the overview.

[#4700]
=== Grouping properties

Create property groups to summarise multiple properties. Proceed as described below to create a property group.

[.instruction]
Creating a property group:

. Go to *System » Settings » Properties » Property groups*.
. Click on *Add property group*.
. Carry out the settings. Pay attention to the information given in <<table-create-property-group>>.
. *Save* the settings. +
→ The property group will be created.

[[table-create-property-group]]
.Creating a new property group
[cols="1,3"]
|====
|Setting |Explanation

|*Name*
|Enter the name for the property group. +
*_Note:_* The name of the system language is displayed by default. After the property group has been created, you can save the name in English. Further languages are planned.

|*Description*
|Enter the description for the property group. +
*_Note:_* The description of the system language is displayed by default. After the property group has been created, you can save the description in English. Further languages are planned.

|*Position*
|Enter the position number for the property group. Properties are sorted by the position number in ascending order. +
*_Tip:_* Count by tens when creating position numbers. This will allow you to easily add new property groups in between.

|*Group type*
|Select the group type from the drop-down menu. This option determines how properties of the type *Empty* are displayed in the order process. +
*None* = Properties will not be grouped by default. +
*Single selection* = One of the grouped properties can be selected from the drop-down menu. +
*Multiselect* = Multiple properties can be selected. +
*_Note:_* This option only applies for properties of the type *None* for which the *Order process* option has been activated.

|*Surcharge type*
|Select the surcharge type from the drop-down menu. +
*Flat* = The surcharge will be entered as flat amount. +
*Flat* = The surcharge will be entered as percentage.
|====

[#4800]
==== Assigning properties to a group

Proceed as described below to assign one or more properties to a property group.

[.instruction]
Assigning properties to a group:

. Go to *System » Settings » Properties*.
. Start the search and, if required, select filters to restrict the search results.
. Activate the properties that you want to assign to the group.
. Click on *Assign property group*. +
→ A drop-down menu of the property groups will be displayed.
. Select the property group from the drop-down menu.
. Click on *Group function*. +
→ The selected properties will be assigned to the property group.

[#4900]
==== Deleting property groups

You can delete one or more property groups at the same time. Properties that are assigned to groups will remain unaffected when deleting property groups.

===== Deleting a property group

Proceed as described below to irreversibly delete a property group if it is no longer needed.

[.instruction]
Deleting a property group:

. Go to *System » Settings » Properties » Property groups*.
. Start the search and, if required, select filters to restrict the search results.
. Click on the property group. +
→ The detail view of the property group will open.
. Click on *Delete group*. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The property group will be deleted and removed from the overview. +
*_Note:_* When you delete a property group, the properties that are assigned to the group will not be deleted.

[#5000]
===== Deleting multiple property groups

Proceed as described below to irreversibly delete multiple property groups if they are no longer needed.

[.instruction]
Deleting multiple property groups:

. Go to *System » Settings » Properties » Property groups*.
. Start the search and, if required, select filters to restrict the search results.
. Activate the property groups that you want to delete.
. Click on *Delete*. +
→ A window will open and you need to confirm your decision.
. Click on *Delete*. +
→ The selected property groups will be deleted and removed from the overview. +
*_Note:_* When you delete a property group, the properties that are assigned to the group will not be deleted.
