= Sending emails
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Access data, HTML design, info service, email template, e-mail template, email, e-mail, template variable, template variables, template functions, automatic email, event procedure, aborted purchase email
:description: Learn how to set up email templates and automatically send emails to your customers.
:position: 20

All emails that are sent with plentymarkets are based on email templates. Go to *System » Client » Select client » Email » Templates* to create and set up email templates. Create as many email templates as desired. In case of certain events, e.g. if a new order is placed in your online store or when a customer subscribes to a newsletter, your plentymarkets system automatically creates emails from these templates and sends them to your customers. You configure which emails are sent when.

[#100]
== Saving the email server's access data

In the *System » Client » Select client » Email » Access data* menu, you save the access data of a mailbox so that plentymarkets emails such as order or shipping confirmations can be sent from this email address.

[.instruction]
Saving the email server's access data:

. Go to *System » Client » Select client » Email » Access data*.
. Carry out the settings. Pay attention to the information given in <<table-email-server-access-data>>.
. *Save* the settings.

[[table-email-server-access-data]]
.Saving the email server's access data
[cols="1,3"]
|====
|Setting |Explanation

|*Test mode*
|Select *Active* or *Inactive*. +
*Active* = The test mode is activated. All emails are only sent to the saved email address. This allows you to test the settings before switching to the live mode. +
*Inactive* = The live mode is activated. +
*_Important:_* The test mode is only applied to this online store. The settings for additional clients (stores) are carried out in the client's menu.

|*Name of sender*
|Enter your name or the name of your company/online store, as you would like it to be displayed to the recipient. Avoid using special characters in order to allow for correct display.

|*Email address*
|Enter the email address as it is listed in the email program.

|*Outgoing mail server/SMTP server*
|Enter the outgoing mail server as specified by the provider (usually smtp.domain.co.uk or mail.domain.co.uk). +
*_mailbox.org_*: For mailbox.org mailboxes, enter the outgoing mail server *smtp.mailbox.org* and select the encryption method *SSL*.

|*User name*
|Enter the user name that matches the email address. +
*_mailbox.org_*: The mailbox.org user name is the complete email address of the mailbox.org mailbox.

|*Password*
|Enter the password that matches the user name and email address.

|*Port (standard: 25)*
|Enter the value *25*. This value is correct for nearly all providers. Otherwise, ask your provider about the correct port. +
*_mailbox.org_*: For mailbox.org mailboxes, enter the port *465* and select the encryption method *SSL*.

|*Encryption*
|Select *SSL*, *TLS* or *No encryption*. For further information, refer to the <<crm/sending-emails#200, Selecting the encryption for email communication>> chapter. +
*_mailbox.org_*: For mailbox.org mailboxes, enter port *465* and select the encryption method *SSL*.
|====

[TIP]
.Entering newsletter access data
====
Go to *System » Client » Select client » Email » Newsletter*. Enter the access data to use the newsletter service that is integrated in plentymarkets. For further information, refer to the <<crm/sending-newsletters#200, Entering newsletter access data>> chapter of the <<crm/sending-newsletters#, Sending newsletters>> page of the manual.
====

[#200]
== Selecting the encryption for email communication

The encryption methods *SSL*, *TLS* and the setting *no encryption* are available in plentymarkets. Select one of these encryption methods for the communication with the email server. Which settings you have to carry out is described in the following sub-chapters.

[#300]
=== Security via SSL encryption

Set up SSL encryption for protected data transfer between your email programs and your mailbox. <<table-ssl-encryption>> explains the settings for SSL encryption in the *System » Client » Select client » Email » Access data* menu.

[[table-ssl-encryption]]
.Settings for SSL encryption
[cols="1,3,3,3"]
|====
|Server type |Server |Connection security |Port

|*IMAP*
|mail.YOUR-DOMAIN.co.uk
|SSL/TLS
|993

|*POP3*
|mail.YOUR-DOMAIN.co.uk
|SSL/TLS
|995

|*SMTP*
|mail.YOUR-DOMAIN.co.uk
|SSL/TLS
|587
|====

[#400]
=== Security via STARTTLS

plentymarkets also provides STARTTLS in order to ensure compatibility with older email programs. <<table-starttls-encryption>> explains the settings for STARTTLS encryption in the *System » Client » Select client » Email » Access data* menu.

[[table-starttls-encryption]]
.Settings for STARTTLS encryption
[cols="1,3,3,3"]
|====
|Server type |Server |Connection security |Port

|*IMAP*
|mail.YOUR-DOMAIN.co.uk
|STARTTLS
|143

|*POP3*
|mail.YOUR-DOMAIN.co.uk
|STARTTLS
|110

|*SMTP*
|mail.YOUR-DOMAIN.co.uk
|STARTTLS
|25
|====

[#500]
=== Unencrypted connection

[WARNING]
.Security not guaranteed
====
Unencrypted communication can be read by third parties. Unencrypted transmission does not meet current security standards.
====

<<table-unencrypted-connection>> explains the settings for unencrypted communication in the *System » Client » Select client » Email » Access data* menu.

[[table-unencrypted-connection]]
.Settings for unencrypted connections
[cols="1,3,3,3"]
|====
|Server type |Server |Connection security |Port

|*IMAP*
|mail.YOUR-DOMAIN.co.uk
|none
|143

|*POP3*
|mail.YOUR-DOMAIN.co.uk
|none
|110

|*SMTP*
|mail.YOUR-DOMAIN.co.uk
|none
|25
|====

[#600]
== Saving the email signature

Go to *System » Client » Select client » Email » Signature* to save the signature. The signature is then automatically inserted into an email template.

[IMPORTANT]
.Pay attention to the legal requirements
====
Please note the legal requirements that are in effect for your online store as to the content of an email signature, e.g. specifying the VAT number. Email signatures are required to include the same information as company business letters. Non-compliance can result in a fine or in a costly warning being issued by a competitor. If in doubt, ask a specialised solicitor.
====

[.instruction]
Saving the email signature:

. Go to *System » Client » Select client » Email » Signature*.
. Enter the text of your signature. Pay attention to the explanations given in the green box.
. *Save* the settings.

[TIP]
.Formatting the signature by means of the HTML editor
====
Select whether you save the text of your signature as *plain text signature* or *HTML signature*. If you want to format the text, it is recommended to enter the text in the *HTML signature* area. An integrated HTML editor is provided to assist you with editing and formatting.

Go to *System » Settings » Editors* and determine which editors should be available for certain areas in your plentymarkets system. Choose between *Editor*, *Syntax editor* and *Text field*.
====

[#700]
== Setting up the email information service

In the *System » Client » Select client » Email » Info service* menu, you have the possibility of sending a "blind copy" (BCC) of all emails sent by your plentymarkets system to an email address of your choice. This can be particularly helpful in the early stages of your online store, as it allows you to maintain an overview of all sent emails and recognise where processes can still be improved. You can, for example, also configure your settings so that you automatically receive an informational email for each order.

[.instruction]
Setting up the email information service:

. Go to *System » Client » Select client » Email » Info service*.
. Carry out the settings. Pay attention to the information given in <<table-email-info-service>>.
. *Save* the settings.

[[table-email-info-service]]
.Setting up the email information service
[cols="1,3"]
|====
|Setting |Explanation

|*All outgoing emails are sent as blind copies (BCC) to the email address entered in the next line*
|Select whether all outgoing emails are sent as BCC to one or multiple email addresses. The email addresses are entered in the next line. +
*YES* = The option is activated. +
*NO* = The option is deactivated (default setting).

|*Email address for blind copy*
|Enter the email address(es). If you enter multiple email addresses, separate them with commas and do not use spaces.

|*Deactivate blind copies (BCC) for the newsletter*
|Select whether blind copies (BCC) should be sent for newsletters. +
Activate option = No blind copies are sent for newsletters. +
Deactivate option = Blind copies are sent for newsletters (default setting).

|*Send notification to email address when a new order was received (next line)*
|Select whether an email should be sent when an order is received. The email addresses are entered in the next line. +
*YES* = An email is sent when an order is received. +
*NO* = No email is sent (default setting). +
 *_Important:_* This function is not available for new orders on eBay. It is recommended instead to set up an <<automation/event-procedures#, event procedure>>.

|*Email address*
|Enter the email address(es). If you enter multiple email addresses, separate them with commas and do not use spaces.
|====

[#800]
== Using the HTML design

Use the *System » Client » Select client » Email » HTML design* menu to set an HTML design for each client (store). The HTML design can then be linked to email templates. You can activate or deactivate the design separately for every email template.

Use this function to ensure that for example the letterhead including the logo of your company automatically appears in all selected email templates. By doing so, it is no longer needed to insert the letterhead and the logo for each email template individually. If you make changes in this menu, you change the design for all linked email templates.

If you wish to create your email templates without a centrally saved HTML design, proceed with the <<crm/sending-emails#1200, Creating an email template>> chapter.

[#900]
=== Uploading the company logo to the image gallery

You can adapt your email templates to the design of your online store, e.g. by inserting your company logo in the HTML design. First, you have to upload the logo to the image gallery. After you created the email template, you insert the <<crm/sending-emails#1750#, logo in the HTML design>> and <<crm/sending-emails#1100, link>> the design with this email template.

[.instruction]
Uploading the company logo to the image gallery:

. Go to *CMS » Image gallery*.
. Click on the folder that you want to upload the logo to. +
→ Alternatively, create a new folder.
. Upload the logo to the folder by clicking on *Upload files* or by using the drag & drop function. +
→ The logo is uploaded.
. Click on the image. +
→ The window with the name of the image opens.
. Copy the URL from the field *Absolute URL*.
. Close the window.

For further information about the image gallery, refer to the <<omni-channel/online-store/setting-up-clients/cms#image-gallery, CMS>> page of the manual.

[#1000]
=== Inserting template variables in the HTML design

First, insert the template variables *$EmailContentHTML* and *$SignatureHTML* in the HTML design. After you created the email template, <<crm/sending-emails#1100, link>> the HTML design with the email template.

[IMPORTANT]
$EmailContentHTML must be present
====
The template variable *$EmailContentHTML* must be inserted in the HTML design. Otherwise, the HTML design cannot be used.
====

[.instruction]
Inserting template variables in the HTML design:

. Go to *System » Client » Select client » Email » HTML design*.
. First, insert the template variables *$EmailContentHTML* and *$SignatureHTML* in the HTML design. +
→ *$EmailContentHTML* contains the content of the email. *$SignatureHTML* contains the signature.
. Format the HTML design as desired.
. *Save* the settings.

Now create the email template as described in the following chapters. Afterwards, you insert the <<crm/sending-emails#1750, logo in the HTML design>> and <<crm/sending-emails#1100, link>> the design with the email template.

[#1200]
== Creating an email template

Go to *System » Client » Select client » Email » Templates* to create new email templates. The folder *General email templates* already contains preconfigured email templates. You can of course make changes to these templates.

You can define up to 2 attachments for each email template. Use email templates to automatically send your customers a PDF document that was generated in the *Orders » Fulfilment* menu, such as an invoice, as well as a document uploaded in the *CMS » Documents* menu, such as a brochure or instructions. For example, it would be useful to attach PDF documents of your cancellation rights and terms and conditions to the email template *Confirmation of online store order*.

[TIP]
.Sending reversal document and invoice in one email template
====
The option *Reversal document and new invoice* was added to the *PDF attachment* drop-down list of an email template. If the order changes after the invoice has been created, you can send your customers both documents in one email.
====

[.instruction]
Creating an email template:

. Go to *System » Client » Select client » Email » Templates*.
. Click on *New email template*. +
→ The *New email template* window opens.
. Enter the name for the template.
. Select an owner or the setting *All* from the drop-down list *Owner*.
. *Save* the settings. +
→ The email template is created and saved in one of the 3 folders, depending on the selected setting in the *Owner* drop-down list.
. Carry out the remaining settings. Pay attention to the information given in <<table-email-template>>.
. *Save* the settings.

[[table-email-template]]
.Settings in the *System » Client » Select client » Email » Templates* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Save*|Saves the settings in the email template.

|*Template variables and functions*|Opens the *Template variables and functions* area from which the template variables and template functions are copied for the email template.

2+|Tab: Settings

|*Owner*
|If the name of the owner has already been selected from the drop-down list upon creation of the email template, the name of the owner is displayed here. Otherwise, select the owner from the drop-down list. This setting can be changed at any time. +
*All* = The template is saved under *General email templates*. +
Own user name = The template is saved under *My email templates*. +
Different user name = The template is saved under *Email templates from other users*. +
*_Note_*: You have to be logged into the system as a user in order to create your own email templates under *My email templates*.

|*Name*
|If the name has already been entered upon creation of the email template, the name of the email template is displayed here. Otherwise, enter the name for the template.
The name can be changed at any time. The name is not displayed to the recipient.

|*Content*
|Select whether the content of the email template should be saved as *Plain text only* or *Only in HTML format*. +
*_Tip_*: Use text in HTML format. The link for order processing (template function *Link_Checkout()*) can be very long. Pure text emails can lead to line breaks that can damage the link. +
*_Important:_* If you want to add further languages in HTML format, pay attention that the setting *Only in HTML format* is selected in the drop-down list *Content* in the *Settings* tab. The selection *Plain text only* is the standard setting for all languages.

|*Template type*
|Select for which area the email template should be available. Possible options: *All* (default setting), *Order*, *Customers*, *Online store*, *Ticket* or *Scheduler*. +
*All* / *Online store* = The email template is available for all areas. +
*Order* = The email template is only available for the selected area. It is not visible in the other areas. If the ticket is linked to an order, email templates with the template type *Order* can also be selected in the ticket. +
*Customer* = The email template is only available for the selected area. It is not visible in the other areas. +
*Ticket* = The email template is only available for the selected area. It is not visible in the other areas. +
*Scheduler* = The email template is available for all areas where the template type *Order* is visible.

|*PDF attachment*
|Select the attachment from the drop-down list. The documents that can be selected from this drop-down list are for example generated in the *Orders » Fulfilment* menu or through shipment-related processes.

|*Document attachment*
|Documents that were uploaded under *CMS » Documents* are displayed here. You can attach one of these documents to an email template. +
All email templates can be sent to customers with up to 2 attachments in a standardised way. Use email templates to send your customers PDF documents relating to fulfilment (e.g. invoices) or other files (e.g. brochures or instructions). For example, it would be useful to attach PDF documents of your cancellation rights and terms and conditions to the email template *Confirmation of online store order*.

|*Reply to*
|Enter an email address. If someone replies to the email template, their message is sent to this address. If no email address was entered, replies to the template are sent to the email address that is saved under <<crm/sending-emails#100, System » Client » Select client » Email » Access data>>. For example, it is useful to enter the accounting department's email address for the *PDF invoice* email template. Questions about the invoice would then directly be sent to your accounting department and wouldn't have to be forwarded to them in an extra step.

|*Use design*
|Activate if the content of the email should be sent with the design that was saved under *System » Client » Select client » Email » HTML design*. If the option is not activated, only the content of the email is used.

|*Client (store)*
|Activate one, multiple or *ALL* clients (stores). The email template is only valid for the selected clients (stores).

2+|Tab: Email message

|*Select a language*
|Select another language from the drop-down list, if required. +
*_Note:_* The language that is set in the contact data record determines which language is sent in the email template.


|*Subject*
|Enter the subject text. Choose the subject carefully so that the emails are recognised by the email account and displayed in the customer's inbox instead of his or her spam folder.

|*Content / Item list*
|Insert the text or list of items in these tabs. Use *plain text* or text in *HTML format*. Template variables and template functions can be used to display the content. +
*_Note_*: Check which type of content was selected in the *Settings* tab under *Content*. Enter the text of the email into this corresponding tab. For example, if *Plain text only* is selected but you entered content into the *Text in HTML format* tab, this content is not sent in the email.
|====

[TIP]
.Tip: Use text in HTML format
====
plentymarkets recommends that you use text which was formatted with HTML since the link for processing orders can be very long. Pure text emails can lead to line breaks that might damage the link. Furthermore, if you use HTML-formatted text, you have the possibility to format the text by means of the integrated HTML editor.

Go to *System » Settings » Editors* and determine which editors should be available for certain areas in your plentymarkets system. Select the *editor*, *syntax editor* or *text field*.
====

[#1300]
=== Using template variables and template functions

Template variables and template functions can be used in email templates. In place of the variable or the function, your plentymarkets system automatically displays the content that this variable or function represents. In this way, only the content is displayed in the email. If you use the <<crm/using-the-ticket-system#4800, ticket system>>, some template variables can also be used as assignment parameters.

Open an email template in the *System » Client » Select client » Email » Templates* menu to display a list of all template variables and template functions that are available for your email templates.

For an overview of the template variables and template functions for email templates, refer to the <<omni-channel/online-store/setting-up-clients/cms-syntax#email-email, Email>> chapter on the <<omni-channel/online-store/setting-up-clients/cms-syntax#, CMS syntax>> page of the manual. For general information about template variables and template functions, refer to the <<omni-channel/online-store/setting-up-clients/cms-syntax#basics, Basics>> section.

[TIP]
.Inserting the link to the checkout in the email template
====
If possible, every email that is sent to a customer should include a link to the checkout. The customer can use this link to look at the current status of his or her order any time. Insert the template function *Link_Checkout()* in the email template.
====

[#1400]
=== Configuring the display of stock units

You can individually configure the way that the stock unit lines are structured for each email template and language. <<crm/sending-emails#1500, If queries>> can also be used for the configuration of stock units. If you do not configure how the stock units should be displayed, plentymarkets displays a standard list of the stock units.

[.instruction]
Configuring the display of stock units:

. Go to *System » Client » Select client » Email » Templates*.
. Open the template.
. Click on the *Email message* tab. +
→ The *Content* tab is displayed.
. Insert the template variable *$ItemListHTML* in the tab *Text in HTML format* or the template variable *$ItemListPlain* in the tab *Plain text* in the email's *Content* tab. Position the template variable where you would like the stock units to be displayed.
. Copy the template variables that you need for the stock units and insert them into the *Item list* tab. The template variables can be copied from the overview. +
​→ To help with the formatting, for example, you can insert tabs that you copied from a text program between the template variables.
. *Save* the settings.

[.subhead]
Example: Displaying stock units

Insert the template variables to display the item ID (*$ItemID*), the item name (*$ItemName*) and the item price (*$ItemPrice*) of the stock units. The display begins with a hyphen. This is used at the start of each new line, even if multiple stock units are shown. In order for the display to "work" on multiple lines, insert a line break at the end of the line by pressing Enter.

How you open the preview in order to check the email template is described in the <<crm/sending-emails#1600, Checking the email template using the preview function>> chapter.

[#1500]
=== Using if queries in email templates

Use if queries in email templates to display specific information on a case-by-case basis. For example, you can save a code that causes bank details to only be displayed in the email to the customer if cash in advance (ID = 0) was selected as the payment method. This if query can be found in the following example.

[source,plenty]
----
include::assets/Email-Templates-MethodOfPayment.html[]

----

For further information, refer to the <<omni-channel/online-store/setting-up-clients/cms-syntax#basics-if, if queries>> page of the manual.

[#1600]
=== Checking the email template using the preview function

Use the email preview function to check whether your email template meets your requirements. In particular, you should check to make sure that the link for order processing works correctly. Proceed as follows to open the preview of the email template.

[.instruction]
Checking the email template using the preview function:

. Go to *Orders » Edit orders*.
. Open the order.
. Click on the *Email* tab.
. Select the language from the *Select a language* drop-down list in the *Email templates* tab.
. Click on the tab where your email template is saved: *General email templates*, *My email templates* or *Email templates from other users*.
. Activate the email template.
. Click on *Preview*. +
→ The *Email preview* window opens.

[#1700]
=== Editing the email template

You can edit general email templates, your own email templates and email templates of other users. Go to *System » Client » Select client » Email » Templates* to edit email templates.

[.instruction]
Editing the email template:

. Go to *System » Client » Select client » Email » Templates*.
. Click on the folder where the email template that you want to edit is saved.
. Click on the email template. +
→ The *Settings* tab of the email template opens.
. Carry out the settings. Pay attention to the information given in <<table-email-template>> in the <<crm/sending-emails#1200, Creating an email template>> chapter.
. *Save* the settings.

[TIP]
.Check email template after every change
====
You should use an order's email service to check every change that is made to a template. In particular, you should check to make sure that the link for order processing works correctly. To do so, proceed as described in the <<crm/sending-emails#1600, Checking the email template using the preview function>> chapter.
====

[#1750]
== Inserting the company logo in the HTML design

In the next step, you insert the logo via an image link in the HTML design of an already created email template. Proceed as described below.

[.instruction]
Inserting the company logo in the HTML design:

. Go to *System » Client » Select client » Email » Templates*.
. Open the email template which you want to insert the logo in.
. Click on the *Email message* tab.
. Click on the *Text in HTML format* tab within the *Content* tab.
. Select the *Editor* from the top right drop-down list. +
→ 2 toolbars to format the text are displayed.
. Click on *Image* in the toolbar. +
→ The *Image properties* window opens.
. Paste the absolute URL that you have just copied from the image gallery in the field *URL*.
. Click on *OK*. +
→ The logo is displayed.
. *Save* the settings.

[#1100]
== Linking the HTML design with an email template

Go to *System » Client » Select client » Email » Templates*. Carry out the following settings to link the HTML design with an email template. Make sure that the content of the email template is saved in the *Text in HTML format* tab. Save the content there if it was not saved already. This content is displayed with the template variable *$EmailContentHTML*.

[.instruction]
Linking the HTML design with the email template:

. Go to *System » Client » Select client » Email » Templates*.
. Select the email template from the folder.
. Select the option *Only text in HTML format* from the *Content* drop-down list.
. Activate the option *Use design*.
. Enter a subject in the *Email message* tab.
. *Save* the settings.

[#1800]
== Sending emails

In order to send emails, user data has to be saved in the <<basics-working-with-plentymarkets/manage-users#10, System » Settings » User » Accounts>> menu. This data can be received from your provider and corresponds to the data that is saved in your email program.

[#1900]
=== Sending ticket messages and comments as emails

An email account must be saved in the <<crm/using-the-ticket-system#2100, System » CRM » Ticket system » Email accounts>> menu in order for messages and comments to be sent as emails. You also have to set up an email template that displays the last ticket message or comment. This email template has to be linked to an <<crm/using-the-ticket-system#2900, event procedure>> in order for messages and comments to be sent via email. For further information, refer to the <<crm/using-the-ticket-system#2100, Using the ticket system>> page of the manual.

[#2000]
=== Sending coupons via email

You can send coupons and coupon codes via email. Simply attach them to emails as PDF files. For further information, refer to the chapters <<orders/coupons#100, Inserting coupon codes directly into emails>> and <<orders/coupons#140, Configuring coupon templates>> on the <<orders/coupons#, Coupons>> page of the manual.

[#2300]
== Setting up automatic emails

The *System » Client » Select client » Email » Automatic* menu contains various events that can be linked with an email template. Select the email template that you have previously <<crm/sending-emails#1200, created>> in the *System » Client » Select client » Email » Templates* menu from the drop-down list. This ensures that the email template is sent to your customer once the event occurs.

[IMPORTANT]
.Removing the link before deleting the email template
====
Deleting an email template that is linked with an event in the *Automatic email* section may lead to undesired effects. Therefore, first go to *System » Client » Select client » Email » Automatic* and remove the link by selecting the option *Do not send* from the drop-down list in the line of the event. Afterwards, you delete the email template in the *System » Client » Select client » Email » Templates* menu.
====

[.instruction]
Setting up automatic emails:

. Go to *System » Client » Select client » Email » Automatic*.
. Select an email template from the drop-down list in the line of the event. Pay attention to the information given in <<table-events-automatic-emails>>.
. *Save* the settings.

Click on *Edit email template*. This opens the email template in the *System » Client » Select client » Email » Templates* menu. The email template can be <<crm/sending-emails#1700, edited>> there.

<<table-events-automatic-emails>> lists explanations of some of the events.

[[table-events-automatic-emails]]
.Explanations for some events in the *System » Client » Select client » Email » Automatic* menu
[cols="1,3"]
|====
|Setting |Explanation

|*New order from online store*
|The customers receive an email including the order confirmation after the purchase has been completed in the online store.

|*Send customer email to change password*
|The customers receive an email with a link to the new password. The link must be actively confirmed. The template function *{% Link_ChangePassword() %}* must be included in the email template.

|*Newsletter opt-in*
|The customers receive an email when they have registered for the newsletter. The email template should include the confirmation link that the customers have to click in order to complete the newsletter registration process.

|*Newsletter opt-in confirmation*
|The customers receive a confirmation email once they have activated the confirmation link that was sent with the email template for the *Newsletter opt-in* event.

|*Reminder in case of aborted purchase*
|The customers receive a reminder email that one or multiple items are in the shopping cart, but the purchase has not been completed yet. It also makes sense for the email template to include a link to the shopping cart. Customers can then click on this link to complete their purchase. Simply insert your online store's URL with the suffix */basket/* (example: *https://myshop.co.uk/basket/*). +
The only requirement is that potential buyers were registered and logged into your online store. Otherwise the email address is not available and the email template cannot be sent automatically. +
*_Important_*: Due to missing previous consent of the recipient, this kind of emailing can be considered to be unsolicited message (spam). Therefore, it is recommended to ask a specialised solicitor.

|*Tell-A-Friend*
|This event sends an email with the link to an item from the online store as a recommendation to an email address that the customers have entered in the Tell-A-Friend form in the online store. +
*_Important_*: Due to missing previous consent of the recipient, this kind of emailing can be considered to be unsolicited message (spam). Therefore, it is recommended to ask a specialised solicitor.

|*Registration for sweepstakes*
|The customers that have registered for the sweepstake receive a confirmation email.

|*Email when item becomes available*
|The customers receive an email containing the information that a certain item is available again. Beforehand, the customers have entered their email address directly next to the item that could not be delivered at that time.
|====

[#2350.subhead]
Setting up an automatic email taking a new order on eBay as an example

An order is automatically created in plentymarkets after a customer has purchased an item on eBay. If you <<crm/sending-emails#1200, created>> the email template "Order confirmation eBay" for example and selected this template from the drop-down list for the event *New order from eBay* in the *System » Client » Select client » Email » Automatic* menu, an email is automatically sent to the customer. The following green box contains an example text for the email template.

[TIP]
.Example email template that should be sent after a purchase is made on eBay
====
Dear $CustomerFullName,

Congratulations on winning the auction!

In order to keep the checkout process as simple as possible, please click on the following link or copy and paste it into the address line of your browser.

In the checkout area, you are able to view and make changes to your personal data as well as view our bank information. When making a bank transfer, always specify the designated use that is saved in this area.

Link_Checkout()
====

Along with the automatic email, the customer can also be sent a message via the eBay messaging system. Go to *System » Markets » eBay » Settings » Tab: Account settings » Tab: Message after purchase* and save the text. For further information, refer to the <<omni-channel/multi-channel/ebay#1500, Sending messages after purchase>> chapter on the <<omni-channel/multi-channel/ebay#, eBay>> page of the manual.

[#2310.subhead]
Setting up an event procedure

It is also possible to set up event procedures in the *System » Orders » Events* menu. Define an event, activate one or more filters and decide which procedures your plentymarkets system should carry out automatically when the event occurs. For example, you can use filters to trigger a procedure once a customer has placed a certain number of orders. The procedure could be sending an email that includes a gift card. For further information, refer to the <<automation/event-procedures#, event procedures>> page of the manual.

[#2500]
== Displaying sent email templates for each customer

Go to *Orders » Edit orders » Tab: Email » Tab: Emails sent*. There you can display all email templates that you have ever sent to the customer. Please note that only those email templates that are linked to a unique customer ID are displayed in this tab.

[.instruction]
Displaying sent email templates for each customer:

. Go to *Orders » Edit orders*.
. Open the order.
. Click on the *Email* tab.
. Click on the *Emails sent* tab. +
→ The date, time, email address of the recipient, ID and name of the template as well as the order ID are displayed.

Expand the area *Other emails sent to this customer...* to display all emails that have been sent to the customer. Here you can also see those emails that were sent to the customer from another order. Click on the order ID on the right-hand side. The order overview of the order opens in a separate tab.

[#2600]
== Displaying all sent email templates

Go to *Start » Statistics* to create a new statistic. Select the statistic type *Sent email templates* in the *Orders* section. This statistic shows information about the emails sent with your plentymarkets system according to the ID and the name of the email template. This statistical feedback is made for each date within the selected time span. The standard setting of the time span is the last 30 days. You can also adapt the time span or select a starting date and an ending date.

In this statistic, you can see for example which email template was used during the selected time period. This helps you to easily recognise which processes were carried out on a regular basis. For further information, refer to the <<basics/statistics#40, Statistics>> page of the manual.
