= Sending newsletters
:lang: en
include::{includedir}/_header.adoc[]
:keywords: double-opt-in function, double opt, double-opt, email template, e-mail template, email folder, e-mail folder, newsletter access data, cleverreach, CleverReach
:description: Learn how to send newsletters to your customers with plentymarkets.
:position: 40

This page of the manual describes which settings you need to carry out to send newsletters with plentymarkets. Send your newsletters e.g. with the <<crm/sending-newsletters#100, integrated newsletter service>>, via the integrated interface <<crm/sending-newsletters#1700, CleverReach>> or any other email marketing and newsletter plugins available in the link:https://marketplace.plentymarkets.com/en/plugins/integration[plentyMarketplace^].

[#100]
== Setting up the newsletter service integrated in plentymarkets

The following sub-chapters describe how to set up the newsletter service that is integrated in plentymarkets.

[TIP]
.Double opt-in method
====
The double opt-in method is used in plentymarkets. This means that an email is sent to the recipient after they have asked to receive the newsletter. This email contains a link that is used to confirm the newsletter subscription. Only after the recipient has clicked on the link is the customer registered for the newsletter. This method is integrated in plentymarkets and cannot be changed.
====

[#200]
=== Entering newsletter access data

Go to *System » System settings » Client » Select client » Email » Newsletter*. Enter the access data to use the newsletter service that is integrated in plentymarkets.

[.instruction]
Entering newsletter access data:

. Go to *System » System settings » Client » Select client » Email » Newsletter*.
. Carry out the settings. Pay attention to the information given in <<table-newsletter-access-data>>.
. *Save* the settings.

[[table-newsletter-access-data]]
.Settings in the *System » System settings » Client » Select client » Email » Newsletter* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Name of sender*
|Enter your name or the name of the online store. This name is displayed to the recipient.

|*Email address*
|Enter the email address as it is listed in the email program. The newsletter is sent via this email address.

|*Outgoing mail server/SMTP server*
|Enter the outgoing mail server as specified by the provider (usually smtp.domain.co.uk or mail.domain.co.uk). +
*_mailbox.org:_* For mailbox.org mailboxes, enter the outgoing mail server *smtp.mailbox.org* and select *SSL* as the *encryption method*.

|*User name*
|Enter the user name that matches the email address. +
*_mailbox.org:_* The mailbox.org user name is the complete email address of the mailbox.org mailbox.

|*Password*
|Enter the password that matches the user name and email address.

|*Port (standard: 25)*
|Enter the value *25*. This value is correct for nearly all providers. Otherwise, ask your provider about the correct port. +
*_mailbox.org:_* For mailbox.org mailboxes, enter the port *465* and select *SSL* as *encryption method*.

|*Encryption*
|Select *SSL*, *TLS* or *No encryption*. +
*_mailbox.org:_* For mailbox.org mailboxes, select the encryption method *SSL*. +
Further information can be found in the <<crm/sending-emails#200, Selecting the encryption for email communication>> chapter on the <<crm/sending-emails#, Sending emails>> page of the manual.
|====

[#300]
=== Creating an email folder

Go to *System » System settings » CRM » Newsletter » plentymarkets » Email folder* to create folders for sending newsletters. Afterwards, you save the email addresses of your customers in these folders. This allows you to send different newsletters to different target groups. Proceed as described below to create a new email folder.

[.instruction]
Creating an email folder:

. Go to *System » System settings » CRM » Newsletter » plentymarkets » Email folder*.
. Enter a name for the folder under *Create new email folder*.
. Change the folder ID if needed.
. Carry out the settings. Pay attention to the information given in <<table-create-email-folder>>.
. *Save* the settings. +
→ The email folder is created and displayed in the overview.

[[table-create-email-folder]]
.Settings in the *System » System settings » CRM » Newsletter » plentymarkets » Email folder* menu
[cols="1,3"]
|====
|Setting |Explanation

|*ID*
|The folder ID that was assigned when the folder was created. Consecutive IDs are automatically assigned by default. However, a different ID can be assigned as needed while creating the folder. The ID *0* cannot be used. +
*_Note:_* Do not use the same ID for multiple folders. If you enter an already existing ID, the original folder is overwritten.

|*Name*
|The name of the email folder. If you activate the option *Can be selected by customers*, this name is also visible for customers in the online store.

|*Can be selected by customers*
|Activate if you want the folder to be selected by customers in your online store. If this option is activated, the folder is displayed in the *My account* area of the online store. Customers are then able to subscribe to the newsletters that are included in this folder.

|*Position*
|Enter a position number to specify which order the folders should be displayed in.

|*Visibility*
|Decide whether the newsletter folder should be visible for the default online store only or whether it should be visible for all online stores. The folder is completely invisible if you select *None*.

|*Delete*
|Activate and click on *Save* to delete the folder.
|====

[#400]
=== Editing an email folder

Existing email folders can also be edited in the menu *System » System settings » CRM » Newsletter » plentymarkets » Email folder*. Proceed as follows to edit the settings of an email folder.

[.instruction]
Editing an email folder:

. Go to *System » System settings » CRM » Newsletter » plentymarkets » Email folder*.
. Carry out the changes as desired. Pay attention to the information given in <<table-create-email-folder>>.
. *Save* the settings.

[#500]
=== Assigning email addresses to the newsletter main folder

Go to <<omni-channel/online-store/setting-up-clients/order-process#, System » System settings » Client » Select client » Order process » Settings>> and use the *Newsletter main folder* drop-down list to select which email folder should automatically be linked to a customer's email address when he or she subscribes to a newsletter during the order process in the online store. All of the visible email folders are listed in the drop-down list (see the *Visibility* option in <<table-create-email-folder>>).

[#600]
=== Allowing customers to select newsletters

Let your customers choose which newsletters they want to receive. This is advantageous, for example, if you regularly send newsletters about different topics. Your customers can select any of the email folders that you have activated for the option *Can be selected by customers* in <<table-create-email-folder>>. Your customers can select these folders in the *My account* area of the online store. The customer's email address is saved in this email folder in your plentymarkets system.

[#700]
=== Creating an email template

Use an email template to send your confirmation email. Use template variables in your template to make sure that the correct name of the customer as well as the confirmation link is automatically included in the template. Proceed as follows to create the email template that contains the confirmation link.

[IMPORTANT]
.Using template variables and template functions
====
There is a wide range of template variables and template functions for your email templates available in plentymarkets. Open the email template and click on *Template variables and template functions*. Copy the template variable or template function from this area and insert it to the desired position in the email template in the *Email message* tab. You can copy them to plain text or to text in HTML format.

For further information, refer to the <<crm/sending-emails#, Sending emails>>, <<omni-channel/online-store/setting-up-clients/cms-syntax#basics-template-variables, Template variables>> and <<omni-channel/online-store/setting-up-clients/cms-syntax#basics-template-functions, Template functions>> pages of the manual.
====

[.instruction]
Creating an email template:

. Go to *System » System settings » Client » Select client » Email » Templates*.
. Click on *New email template*. +
→ The *New email template* window opens.
. Enter the name for the email template.
. Select the owner from the drop-down list.
. *Save* the settings. +
→ The email template is created and saved in one of the 3 folders, depending on the selected setting in the *Owner* drop-down list. Pay attention to the information given about *Owner* in <<table-create-email-template>>.
. Carry out the settings. Pay attention to the information given in <<table-create-email-template>>.
. Insert the template variable *$CustomerFullName* into the text of the email. +
→ This template variable makes the first name and last name available.
. Insert the template variable *$NewsletterConfirmURL* into the text of the email. +
→ This template variable makes the confirmation link available.
. *Save* the settings.

If the recipient of the email clicks on the link that was inserted with the template variable *$NewsletterConfirmURL*, the recipient confirms the newsletter registration and will receive from now on the newsletter to the saved email address.

If you would like to use the <<crm/sending-newsletters#800, double opt-in method>>, a further step is required. You must create two templates and select them for the events *Newsletter opt-in* and *Newsletter opt-in confirmation* in the *System » System settings » Client » Select client » Email » Automatic* menu.


[[table-create-email-template]]
.Creating a new email template in the *System » System settings » Client » Select client » Email » Templates* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Save*
|Saves the settings in the email template.

|*Template variables and template functions*
|Opens the *Template variables and functions* area from which the template variables and template functions are copied for the email template.

2+|Tab: Settings

|*Owner*
|If the name of the owner has already been selected from the drop-down list upon creation of the email template, the name of the owner is displayed here. Otherwise, select the owner from the drop-down list. This setting can be changed at any time. +
*All* = The template is saved under *General email templates*. +
Own user name = The template is saved under *My email templates*. +
Different user name = The template is saved under *Email templates from other users*. +
*_Note:_* You have to be logged into the system as a user in order to create your own email templates under *My email templates*.

|*Name*
|If the name of the email template has already been entered upon creation of the template, the name of the email template is displayed here. Otherwise, enter the name for the template. +
The name can be changed at any time. The name is not displayed to the recipient.

|*Content*
|Select whether the message should be saved as *plain text* or in *HTML format*.

|*Template type*
|Select for which area the email template should be available. Possible options: *All* (default setting), *Order*, *Customers*, *Online store*, *Ticket* or *Scheduler*. +
*All* / *Online store* = The email template is available for all areas. +
*Order* = The email template is only available for the selected area. It is not visible in the other areas. If the ticket is linked to an order, email templates with the template type *Order* can also be selected in the ticket. +
*Customer* = The email template is only available for the selected area. It is not visible in the other areas. +
*Ticket* = The email template is only available for the selected area. It is not visible in the other areas. +
*Scheduler* = The email template is available for all areas where the template type *Order* is visible.

|*PDF attachment*
|Select the attachment from the drop-down list. The documents that can be selected from this drop-down list are for example generated in the *Orders » Fulfilment* menu or through shipment-related processes.

|*Document attachment*
|Documents that were uploaded under *CMS » Documents* are displayed here. You can attach one of these documents to an email template. +
 All email templates can be sent to customers with up to 2 attachments in a standardised way. Use email templates to send your customers PDF documents relating to fulfilment (e.g. invoices) or other files (e.g. brochures or instructions). For example, it would be useful to attach PDF documents of your cancellation rights and terms and conditions to the email template *Confirmation of online store order*.

|*Reply to*
|Enter an email address. If someone replies to the email template, their message is sent to this address. If no email address was entered, replies to the template are sent to the email address that is saved under <<crm/sending-emails#100, System » System settings » Client » Select client » Email » Access data>>. For example, it is useful to enter the accounting department's email address for the *PDF invoice* email template. Questions about the invoice would directly be sent to your accounting department and wouldn't have to be forwarded to them in an extra step.

|*Use design*
|Activate if the content of the email should be sent with the design that was saved under <<crm/sending-emails#800, System » System settings » Client » Select client » Email » HTML design>>. If the option is not activated, only the content of the email is used.

|*Client (store)*
|Activate one, multiple or *ALL* clients (stores). The email template is only valid for the selected clients (stores).

2+|Tab: Email message

|*Select language*
|The selected language is displayed here and can be changed.

|*Subject*
|Enter the subject text. Select the subject name very carefully so that your customers can easily recognise the emails in their inbox and so that the emails are not filtered out as spam.

|*Content / Item list*
|Insert the text or list of items in these tabs. Use *plain text* or text in *HTML format*. Template variables and template functions can be used to display the content. +
*_Note:_* Check which type of content was selected in the *Settings* tab under *Content*. Enter the text of the email into this corresponding tab. For example, if *Plain text only* is selected but you entered content into the *Text in HTML format* tab, this content is not sent in the email.
|====

[#800]
=== Linking the email template to the double opt-in function

In the next step, link the email template that you have just created to the double opt-in function and select another template for the option *Newsletter opt-in confirmation*. If you use the double opt-in method, the customer has to confirm the newsletter registration in a second step after they have registered for the newsletter.

[TIP]
.Notes about the double opt-in method
====
You must <<crm/sending-newsletters#700, create>> 2 templates and select these for the events Newsletter opt-in and *Newsletter opt-in confirmation* in the *System » System settings » Client » Select client » Email » Automatic* menu. The selected template under *Newsletter opt-in* is sent when the customer has registered for the newsletter. This template should contain the confirmation link that the customer has to click in order to complete the newsletter registration. Use the template variable *$NewsletterConfirmURL* to display the confirmation link. This template variable contains the URL to confirm the newsletter registration. The selected template under *Newsletter opt-in confirmation* is sent when the customer has activated the confirmation link.

In the contact data record in the *CRM » Contacts » Search contact » Open contact* menu, the *Newsletter* option is activated automatically when the customer has registered for the newsletter during the order process and has confirmed the newsletter registration via the confirmation link.
====

[.instruction]
Linking the email template to the double opt-in function:

. Go to *System » System settings » Client » Select client » Email » Automatic*.
. Select the email template that was previously created from the *Newsletter opt-in* drop-down list.
. Select the email template that was previously created from the *Newsletter opt-in confirmation* drop-down list.
. *Save* the settings.

You can see the confirmation status by going to *System » System settings » CRM » Newsletter » plentymarkets » Emails*. Customers who confirmed that they want to receive the newsletter are designated with the status *confirmed*. Customers who did not go through the double opt-in process are designated with the status *not confirmed*.

The *IP address* and the *confirmation URL* used for a confirmation are saved in the database. This data can be retrieved afterwards via a link:https://developers.plentymarkets.com/rest-doc/newsletter/details#list-a-recipient[REST call^]. This is not displayed in the back end.

[#900]
=== Saving an email address

The email addresses that newsletters should be sent to are saved in various folders. Go to *System » System settings » CRM » Newsletter » plentymarkets » Emails* to manage the email addresses that are saved in these folders. If you have not yet created a <<crm/sending-newsletters#300, folder structure>> for your newsletters, we recommend doing so before you continue.

Proceed as described below to save an email address in an email folder.

[.instruction]
Saving an email address:

. Go to *System » System settings » CRM » Newsletter » plentymarkets » Emails*.
. Expand the folder.
. Expand the *New email address* area.
. Carry out the settings. Pay attention to the information given in <<table-save-email-address>>.
. *Save* the settings.

[[table-save-email-address]]
.Settings for saving a new email address
[cols="1,3"]
|====
|Setting |Explanation

|*First name*
|Enter the customer's first name.

|*Last name*
|Enter the last name of the contact.

|*Email*
|Enter the customer's email address.

|*Folder*
|Select the <<crm/sending-newsletters#300, email folder>> in which the customer data should be saved.
|====

[#1000]
=== Creating a newsletter

Proceed as described below to create new newsletters. You can also edit existing newsletter.

[.instruction]
Creating a newsletter:

. Go to *CRM » Newsletter*.
. Expand the *New newsletter* area. +
→ The editing window for the new newsletter opens.
. Carry out the settings. Pay attention to the information given in <<table-create-newsletter>>.
. *Save* the settings.

[[table-create-newsletter]]
.Settings for creating a newsletter
[cols="1,3"]
|====
|Setting |Explanation

|*Placeholder(s)*
|Lists the placeholders that are recognised by the system and replaced in the message.

|*Image gallery*
|Opens the <<omni-channel/online-store/cms#image-gallery, CMS » Image gallery>> menu. Save an image here to attach it to the newsletter.

|*Input layout template*
|Clicking on *Input layout template* inserts the form of address *[Guten Tag]* along with the placeholder *[NAME]]* in the area *HTML newsletter*. The customer's name is automatically replaced the template variable.

|*Subject*
|Enter a subject for the newsletter.

|*Editor*
|The *CKEditor* is pre-selected. If required, select another editor from the drop-down list.

|*HTML newsletter*
|Enter the content of the newsletter as HTML code. +
*_Note:_* Texts can only be saved in one field. Therefore, you can either enter text into the *HTML newsletter* or the *Text newsletter* field.

|*Text newsletter*
|Enter the newsletter's content as plain text only. +
*_Note:_* Texts can only be saved in one field. Therefore, you can either enter text into the *HTML newsletter* or the *Text newsletter* field.

|====

[#1100]
=== Searching for customers by their email address or last name

Proceed as described below to save an email address in an email folder. You can either search for customers by their email address or by their last name.

[.instruction]
Searching for customers by their email address or last name:

. Go to *System » System settings » CRM » Newsletter » plentymarkets » Emails*.
. Expand the email folder.
. Select the option *Email address* or *Last name* from the drop-down list. Customers are searched for by this criterion.
. Enter the customer's email address or last name in the search field.  +
→ It is sufficient to only enter part of the name or email address. Leave the field blank if you want to display all email addresses or last names.
. Click on *Search*. +
→ The search result(s) are displayed.

The confirmation status is also displayed in the search results. The <<crm/sending-newsletters#800, double opt-in method>> is used in plentymarkets. This means that the recipient is sent an email after having asked to receive the newsletter. This email contains a link that is used to confirm the newsletter subscription. Customers who confirmed that they want to receive the newsletter are designated with the status *confirmed*. Otherwise, you see the words *not confirmed*.

[#1200]
=== Editing an email address

Once you have found an email address with the search function, you can edit the data that is saved for this customer. For example, this is useful if you need to update a customer's email address or if you want to move the customer data record into a different email folder. To do so, proceed as follows.

[.instruction]
Editing an email address:

. Go to *System » System settings » CRM » Newsletter » plentymarkets » Emails*.
. Search for the customer as described in the chapter <<crm/sending-newsletters#1100, Searching for customers by their email address or last name>>.
. Expand the customer.
. Carry out the changes as desired. Pay attention to the information given in <<table-save-email-address>> in the <<crm/sending-newsletters#900, Saving an email address>> chapter.
. *Save* the settings.

[#1300]
=== Exporting and importing email addresses

The previous chapters describe how to manage individual email addresses. If you want to edit several email addresses at once, it is recommended that you work with the <<basics/data-exchange#, data exchange>>.

You can import or export email addresses. You can export all of the email addresses by going to <<data/export-import/exporting-data#, Data » Dynamic export>> and using the <<data/export-import/data-formats/customernewsletter#, CustomerNewsletter>> data format. You can import new email addresses by going to <<data/export-import/importing-data#, Data » Dynamic import>>.

[#1400]
=== Copying customer data into an email folder

Go to *System » System settings » CRM » Newsletter » plentymarkets » Email filter* to filter customer data and copy this data into specific email folders. For example, you can search for all customers who purchased a certain item during a specific time period. You can use the folders when sending newsletters to these customer groups in the <<crm/sending-newsletters#1000, CRM » Newsletter>> menu.

Proceed as described below in order to copy customer data into an email folder.

[.instruction]
Copying customer data into an email folder:

. Go to *System » System settings » CRM » Newsletter » plentymarkets » Email filter*.
. Carry out the settings in the *Copy all customer data into email folder(s)* area. Pay attention to the information given in <<table-copy-customer-data>>.
. Click on *Transfer emails into folder*.

[[table-copy-customer-data]]
.Copying customer data into an email folder
[cols="1,3"]
|====
|Setting |Explanation

|*Newsletter registration*
|Select one of the following options: +
*ALL* = The customer data of all customers who subscribed to the newsletter are copied into the email folder. This includes customers who confirmed their newsletter subscription with the <<crm/sending-newsletters#800, double opt-in method>> and customers who have not yet confirmed. +
*Only customers who have consented to the receipt of newsletters* = The customer data are copied into the email folder for those customers who have confirmed their newsletter subscription.

|*Country*
|Select the country to only filter customers from this country. For example, this makes it possible to send one version of a newsletter to customers who live in the United Kingdom and another version to customers who live in Ireland.

|*Email folder*
|Select the email folder. The customer data is saved in this email folder.
|====

[#1500]
=== Filtering customer data

The customer filter helps you find more specific customer data. Proceed as described below in order to filter customer data and to copy this data into an email folder.

[.instruction]
Filtering customer data:

. Go to *System » System settings » CRM » Newsletter » plentymarkets » Email filter*.
. Carry out the settings in the *Customer filter* area. Pay attention to the information given in <<table-filter-customer-data>>.
. Click on *Preview* to see the customer data. +
→ The *Preview* area that contains the customer data opens. Check the result.
. Click on *Transfer emails into folder*.

[[table-filter-customer-data]]
.Settings for the customer filter
[cols="1,3"]
|====
|Setting |Explanation

|*Minimum order value*
|Enter a minimum order value to filter customers whose orders reached or exceeded this value.

|*Category 1-3*
|Select up to 3 category levels to filter customers who bought an item in this category or sub-category.

|*Item ID*
|Enter one or more item IDs to filter customers who bought these items.

|*Exact order time*
|Enter a time period to filter customers who placed an order during this time period. If you do not want to filter by the date, activate the option *No exact order time*.

|*Country*
|Select the country to only filter customers from this country. For example, this makes it possible to send one version of a newsletter to customers who live in the United Kingdom and another version to customers who live in Ireland.

|*Client (store)*
|Select a client (store) to filter customers who bought an item from this client (store).

|*Customer class*
|Select a <<crm/managing-contacts#15, customer class>> to filter customers who belong to this class.

|*Order referrer*
|Select an order referrer to filter customers who placed orders with this order referrer.

|*Newsletter registration*
|Choose between the options *ALL* and *Only customers who have consented to the receipt of newsletters*. +
*ALL* = The customer data of all customers who have subscribed to the newsletter are copied into the email folder. This includes customers who confirmed their newsletter subscription with the <<crm/sending-newsletters#800, double opt-in method>> and customers who have not yet confirmed. +
*Only customers who have consented to the receipt of newsletters* = The customer data are copied into the email folder for those customers who have confirmed their newsletter subscription.

|*Email folder*
|Select the email folder. The customer data is saved in this email folder.
|====

[#1600]
=== Sending newsletters

After you <<crm/sending-newsletters#700, created>> and <<crm/sending-newsletters#800, linked>> the email template and have <<crm/sending-newsletters#1000, created the newsletter>>, you set which email addresses that are saved in the email folders the newsletter should be sent to. To do so, go to *CRM » Newsletter*. Using the *Filter* option, you can decide whether to send a newsletter to all email addresses or only to confirmed email addresses. Carry out this setting in the *Send newsletter* tab of the newsletter.

[TIP]
.Only a limited number of newsletters is sent during the day
====
Please note that only a limited number of newsletters is sent to your customers during the day. At night, a larger number of emails is allowed to be sent to your customers.

* During the day between 8:00am and 12:00 midnight: 60 emails every 15 minutes
* At night between 12:00 midnight and 8:00am: 500 emails every 15 minutes
====

[.instruction]
Sending newsletters:

. Go to *CRM » Newsletter*.
. Expand the newsletter that you want to send.
. Click on the *Send newsletter* tab.
. Select a group under *Send newsletter to group* from the drop-down list.
. Select the option *ALL* or *To confirmed email addresses only* from the *Filter* drop-down list.
. Click on *Send*. +
→ The newsletter are sent according to the settings that you selected above.

[#1700]
== Sending newsletters with CleverReach

Proceed as described below to send newsletters to your customers with link:https://www.cleverreach.com/en/[CleverReach^].

[#1800]
=== Registering with CleverReach

Register for free in order to use CleverReach in plentymarkets. To do so, go to the link:https://www.cleverreach.com/en/[CleverReach website^]. For further information about the settings, refer to the link:http://support.cleverreach.de/hc/de[CleverReach help center^].

[#1900]
=== Setting up CleverReach in plentymarkets

Proceed as described below to set up the CleverReach interface in plentymarkets.

[.instruction]
Setting up CleverReach in plentymarkets:

. Go to *System » System settings » CRM » Newsletter » CleverReach*.
. Carry out the settings. Pay attention to the information given in <<table-set-up-cleverreach>>.
. Enter your *API key*.
. Enter the *List ID* of the group that you created in CleverReach.
. *Save* the settings.
. Click on *Generate group attributes*. +
→ Data fields are set up in CleverReach. This way the data that you transfer can be saved and processed.
. Open the CleverReach back end and open the group whose list ID you entered into plentymarkets.
. Delete the data fields that you do not want to use in CleverReach. +
→ The following data fields are currently transferred from plentymarkets to CleverReach: *Birthday*, *First name*, *Gender (form of address)*, *Lang (language)* and *Last name*.
. Go back to *System » System settings » CRM » Newsletter » CleverReach* in your plentymarkets back end.
. Activate the option *Automatic transfer (daily)* so that customer data is transmitted.
. *Save* the settings.

[[table-set-up-cleverreach]]
.Settings in the *System » System settings » CRM » Newsletter » CleverReach* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Generate group attributes*
|Generates the data fields (group attributes) for CleverReach.

|*Carry out data transfer*
|Transfers data fields (group attributes) to CleverReach. The following data fields are currently transferred from plentymarkets to CleverReach: *Birthday*, *First name*, *Gender (form of address)*, *Lang (language)* and *Last name*. Select the area from the drop-down list. +
*_Note:_* This is to be carried out before you transfer the actual customer data. Refer to the following instructions.

|*API key*
|Enter the API key that you received from CleverReach.

|*List ID*
|Enter the list ID that you received from CleverReach.

|*Order referrers*
|Select the order referrers that should be available for CleverReach. Referrers that do not allow data to be transferred are not selected by default. +
*_Note:_* Check the selected order referrers before you begin working with CleverReach. This helps you avoid potential warnings or reprimands.

|*Export starting with order status*
|Select a status. Data is exported starting from this status.

|*Automatic transfer (daily)*
|Activate if data should automatically be transferred every day.
|====

[IMPORTANT]
.First transfer
====
During the first automatic transfer, customer data is transferred from the past 3 days. After that, only new customers' data is transferred.
====

You can use filters in CleverReach if you do not want to write to all customers. For further information, refer to the link:https://support.cleverreach.de/hc/en-us[CleverReach^] support page.

[#2000]
=== Manually transmitting customer data

Use the *Carry out data transfer* option to only transfer customer data for a specific customer type. This allows you to sort the plentymarkets customer types into different CleverReach groups.

[IMPORTANT]
.Should I use the automatic transfer?
====
If you use the option *Carry out data transfer* in order to transfer customer data filtered by customer type, you may have to deactivate the automatic transfer. The automatic transfer transfers all new customer data without considering the different customer types.
====

[.instruction]
Manually transmitting customer data:

. Go to *System » System settings » CRM » Newsletter » CleverReach*.
. Enter your *API key*.
. Enter the *List ID* of the group that you created in CleverReach.
. *Save* the settings.
. Click on *Generate group attributes*. +
→ Data fields is set up in CleverReach. This way the data that you transfer can be saved and processed.
. Open the CleverReach back end and open the group whose list ID you entered into plentymarkets.
. Delete the data fields that you do not want to use in CleverReach. +
→ The following data fields are currently transferred from plentymarkets to CleverReach: *Birthday*, *First name*, *Gender (form of address)*, *Lang (language)* and *Last name*.
. Go back to *System » System settings » CRM » Newsletter » CleverReach* in your plentymarkets back end.
. Select the customer type from the drop-down list *Carry out data transfer*.
. *Save* the settings.
. Click on *Export*. +
→ The customer data is transmitted.
