= Using the ticket system
:lang: en
include::{includedir}/_header.adoc[]
:keywords: ticket system, ticket, role, type, status, signature, complimentary close, message, comment, template, child ticket, event procedure, procedure manager
:description: Learn how to use the ticket system in plentymarkets for your customer communication.
:position: 30
:url: crm/using-the-ticket-system

The ticket system in plentymarkets provides numerous functions for <<crm/using-the-ticket-system#1600, creating>>, <<crm/using-the-ticket-system#3400, searching>> and <<crm/using-the-ticket-system#3500, editing>> your tickets. Furthermore, project management functions are also included. On this page of the manual, you find information about the settings that you need to carry out in the user account first as well as the ticket system settings in the *System » System settings » CRM » Ticket system* menu. Depending on which plentymarkets tariff you choose, you may have to <<crm/using-the-ticket-system#100, book>> the ticket system before you can use it in the *CRM » Ticket system* menu.

[#100]
== Booking the ticket system

Depending on which plentymarkets tariff you use, you may have to book the ticket system before you are able to use it. You find an overview on the plentymarkets tariffs on this link:https://www.plentymarkets.co.uk/prices/[page^].

[#200]
== Carrying out settings in the user account

In order to efficiently use the ticket system, you should save your signature and a complimentary close. Furthermore, you have to activate the *Ticket* option in the user account. By doing so, these users can be selected as owners in the ticket system. Moreover, users of the *Variable* user class must be assigned a right to be able to work with the ticket system. The settings for users who should use the ticket system are important for correctly configuring your ticket system. These settings are described in the following sub-chapters.

[#300]
=== Adding the signature and complimentary close

Save data for every user account who is owner of the ticket system in the *Signature* and *Complimentary close* tabs. The complimentary close and signature are added to the end of emails (in that order). The complimentary close is also automatically added to the end of the text in messages and comments in the ticket system. For further information, refer to the <<basics/working-with-plentymarkets/customise-user-account#, Customising the user account>> page of the manual.

[IMPORTANT]
.Note the priority of the signature
====
The signature that was saved for a user in his or her user account takes priority over the signature that is saved under <<crm/sending-emails#600, System » System settings » Client » Select client » Email » Signature>>. +
If you inserted the template variable *$SignatureHTML* in the email template, the signature that is saved in the user account is used. If no signature is saved in the user account, the signature that is saved in the *System » System settings » Client » Select client » Email » Signature* menu is used. +
If you inserted the template variable *$SignatureText* in the email template, the signature that is saved in the *System » System settings » Client » Select client » Email » Signature* menu is always used.
====

[#400]
=== Activating owners

Go to *System » System settings » Settings » User » Account » Open user » Tab: Owner* to activate owners. Activate the *Ticket* option for each user who should be available as an owner in the ticket system. For further information, refer to the <<basics/admin-tasks/manage-users#40, Managing user accounts>> page of the manual.

[#500]
=== Assigning rights

You need to assign a right to users of the *Variable* user class. By doing so, they are able to use the ticket system. Go to *System » System settings » Settings » User » Account » Open user » Tab: Right » Tab: Menu* to enable him or her to use the ticket system. Activate the *Ticket system* option in the *Customers* area. For further information, refer to the <<basics/admin-tasks/manage-users#90, Managing user accounts>> page of the manual.

[#600]
== Carrying out the basic settings

Before you can use the ticket system, you have to activate the email retrieval in the *System » System settings » CRM » Ticket system » Email accounts* menu. This automatically converts your emails into tickets. Furthermore, you have to create roles, types, statuses, status groups and topics. To do so, go to *System » System settings » CRM » Ticket system » Settings*. These settings are described in the following sub-chapters.

[#2100]
=== Setting up the email account

You need to be able to retrieve emails before tickets can automatically be created from emails. Go to *System » System settings » CRM » Ticket system » Email accounts* and enter the email addresses from which emails should be retrieved. plentymarkets regularly retrieves new emails from your account and converts them into tickets. The original emails can either be deleted automatically or moved to a different email folder.

You can save up to twenty email accounts that you want to use for transferring your customers' emails directly into the ticket system. plentymarkets recommends that you create individual email addresses that you use specifically for tickets. Give these addresses a name that is easily recognisable.

[.instruction]
Setting up the email account:

. Go to *System » System settings » CRM » Ticket system » Email accounts*.
. Click on *New configuration*.
. Expand the *Email* area.
. Carry out the settings. Pay attention to the information given in <<table-set-up-email-account>>. +
→ The settings in the areas *Account*, *Retrieval* and *Shipping* are mandatory settings.
. *Save* (icon:save[role="green"]) the settings.

[IMPORTANT]
.Observe test mode
====
After you have carried out all tests, you have deactivate the test mode in the *System » System settings » Client » Select client » Email » Login details* menu. If you do not deactivate the test mode, tickets are only sent to the email address that is saved in the *System » System settings » CRM » Ticket system » Email accounts* menu.
====

[[table-set-up-email-account]]
.Settings in the *System » System settings » CRM » Ticket system » Email accounts* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Test retrieving emails*
|Tests the email retrieval function. You receive a message that lets you know if the test was successful. Afterwards, you receive an email with the date and time of the test.

|*Test sending of emails*
|Tests the email retrieval function. You receive a message that lets you know if the test was successful. +
*_Important_*: Unsuccessful tests are usually caused by incorrect login details or an incorrect password. Check these parameters if an error has occurred.

2+|Account

|*Email*
|Enter the email address that should be used for the ticket system. This is a mandatory field.

2+|Retrieval (*_Note_*: All settings in this area are mandatory.)

|*Active*
|If you want the account and thus the retrieval to be active, activate the option. +
If you do not want the account to be active, deactivate the option and save the settings. The account is still available and can be activated again at any time.

|*User*
|Enter the user name that matches the email address.

|*Password*
|Enter the password that matches the user name and email address.

|*Process*
|Select a process. Recommended process: IMAP: +
*IMAP* = emails are managed on the provider's server and are available on several different devices such as computer, tablet or smartphone. Emails are synchronised; this means that all devices receive the same emails at the same time. +
*POP* = email connection protocol that manages the retrieval of emails from a server. A permanent connection to the server is not necessary. Errors can occur, especially if you work with several different devices. When using the POP process, all messages are completely downloaded from the server or saved as a copy on the device. The messages can be read, answered or deleted locally. Changes are not saved neither on the devices used nor on the server. Synchronisation does not take place.

|*Port*
|Default value: 25. This value is correct for nearly all providers. Otherwise, ask your provider about the correct port. Pay attention to the information about *Coding*.

|*Encryption*
|Select *SSL*, *TLS* (default setting) or *No encryption*. +
*_Important_*: For plentymarkets email accounts with the type IMAP, select the setting *TLS* with port 143 or the setting *No coding* with port 143. +
TLS coding = If you are hosting on your own domain (e.g. mail.domain.tld), you may not select *TLS* as coding for port 143. You need to select *No coding*. If you are hosting with plentymarkets (e.g. mail.plentymarkets.com), you can select *TLS* for port 143.

|*Host*
|Enter the URL of the host computer which the email account is managed on.

|*Type / status of the new ticket*
|Select the type and status for new tickets from the drop-down lists. The email is sent automatically when a new ticket is created with these parameters.

2+|Shipping *_Note_*: All settings in this area are mandatory.)

|*Name of sender*
|Enter your name or the name of your company/online store as you would like it to be displayed to the recipient.

|*Reply to*
|Enter the email address that the answer should be sent to.

|*User*
|Enter the user name that matches the email address.

|*Password*
|Enter the password that matches the user name and email address.

|*Port*
|Default value: 25. This value is correct for nearly all providers. Otherwise, ask your provider about the correct port.

|*Encryption*
|Select *SSL*, *TLS* or *No coding*.

|*Host*
|Enter the URL of the host computer which the email account is managed on.

2+|Procedures

|*Procedure*
|The procedure *Move* is used to sort the emails into a specific folder after the ticket was created. This allows you to archive the emails. +
Select *Delete* if you do not want to save the emails. The emails are deleted after they were received and assigned to the ticket.

|*Move to*
|This option is only visible if the procedure *Move* was selected. Select which folder the emails should be moved to. +
*_Important_*: You are required to select a folder. If you do not select a folder, the emails are not moved.
|====

[#700]
=== Adding a role

A role provides information about the members of your staff involved in handling a ticket. These roles can be individually assigned for each ticket. For example, if an employee provides assistance to customers in a ticket, it would make sense to assign this employee to the previously created role *Support*. The active user is automatically assigned as owner of a new ticket. The active user is automatically assigned as owner of a new ticket.

Go to *System » System settings » CRM » Ticket system » Settings » Tab: Roles* and enter a name in different languages for each role. You can save names for the *default language* (the language that you are currently logged into your plentymarkets system with) as well as for other languages. These language versions are used when accessing the system in a different language. In other words, if you log into your plentymarkets system in *German*, you see the names that were saved under *de* in the default language column. Use the *position* number to specify which order the roles should be displayed in.

If you make someone owner of a ticket, you also need to specify the role that he or she plays in processing the ticket. In this menu, create as many different roles as desired.

[TIP]
.Example for using the ticket system as a project management tool
====
Add the roles *Project leader* and *Employee*, for example. Add the roles Project leader and Employee, for example. It is possible to set up an event procedure which causes the project leader to receive an email notification when the ticket's status changes or a comment was made.
====

[.instruction]
Adding a role:

. Go to *System » System settings » CRM » Ticket system » Settings » Tab: Roles*.
. Click on *Add*. +
→ An empty line is displayed.
. Enter a name and position number.
. *Save* (icon:save[role="green"]) the settings.

Edit a role by clicking on the previously saved text. Click on *Delete* to delete the line. You are asked to confirm your decision.

[#800]
=== Adding a type

You can create as many different types of tickets as you want, e.g. *customer inquiries* or *complaints*. Carry out the settings for the *default language*, *additional languages* and the *position* number. The procedure for doing so is the same as for the <<crm/using-the-ticket-system#700, roles>>.

[.instruction]
Adding a type:

. Go to *System » System settings » CRM » Ticket system » Settings » Tab: Types & Status*.
. Click on *New type*. +
→ The *New type* window opens.
. Enter the name.
. *Save* (icon:save[role="green"]) the settings. +
→ The type is added and opened.
. Enter the *position*.
. *Save* (icon:save[role="green"]) the settings.

Edit a type by clicking on the previously saved text. Click on *Delete* to delete the line. You are asked to confirm your decision.

[#900]
=== Adding a status

You can specify individual statuses for each ticket type. You can reuse the same statuses for each type of ticket or you can create individual statues for each type.

[IMPORTANT]
.Setting the visibility
====
The following rule applies to the <<basics/admin-tasks/manage-users#100, visibilities>> that you set for ticket statuses in the *System » System settings » Settings » User » Accounts* and the *System » System settings » Settings » User » Roles* menus: Any limitation of visibility is dominant. If a user is assigned several roles, the areas that are set to *Visible* in the *Visibility* tab must also be set to *Visible* in all other roles of this user. If one area is set to *Invisible* in one role, this setting is also applied to all other roles of this user.
====

[.instruction]
Adding a status:

. Go to *System » System settings » CRM » Ticket system » Settings » Tab: Types & Status*.
. Open the <<crm/using-the-ticket-system#800, type>> that you have just added.
. Click on *Add a new status* to add a status to the type.
. Enter the *name*.
. Enter the amount of *progress* that this status represents. Save the progress as a percentage between 0% and 100%. +
→ A progress bar is displayed in the ticket overview once the status has been reached.
. Select a *group* from the drop-down list.
. *Save* (icon:save[role="green"]) the settings.

Edit a status by clicking on the previously saved text. Click on *Delete* to delete the line. You are asked to confirm your decision.

[#1000]
=== Creating a status group

Go to *System » System settings » CRM » Ticket system » Settings » Tab: Status groups* to create different status groups. Status groups help you keep track of your tickets within the ticket system. For example, if you created 10 statuses to help you follow a task from start to finish and these statuses are only relevant to one department within your company, you may find it helpful to combine these statuses into one status group.

[IMPORTANT]
.Assigning the statuses
====
Every status can only be added to one group.
====

[.instruction]
Creating a status group:

. Go to *System » System settings » CRM » Ticket system » Settings » Tab: Status groups*.
. Click on *Add new status group*. +
→ The window *New status group* opens.
. Enter the *name*.
. Enter the *position*.
. Click on *Add*. +
→ The status group is added and opened.
. Select a *colour* for the status group.
. Activate the statuses that should be included in the group.
. *Save* (icon:save[role="green"]) the settings.

[TIP]
.Adding the language of the status group
====
The status group is created for the default system language. Select a different language in the editing window if you want to enter translations for the name. The selected statuses apply to every language.
====

If you activated the option *Status group* via <<basics/working-with-plentymarkets/general-functions#50, Customising the layout>> in the *CRM » Ticket system » Tab: Tickets* menu, you can see in the ticket overview the status of the ticket directly after having created the ticket. The status group is also displayed in the ticket next to *Show / Hide tags*.

[#1100]
=== Adding a topic

In the *System » System settings » CRM » Ticket system » Settings » Tab: Topics* menu, you can create topics that are later used as headings for new messages and comments. This makes working with tickets easier and more understandable. Assign topics for your communication, e.g. *item details*, *service* or *exchange*. You can scan the topics of longer communication threads at a glance. How you assign topics is described in the <<crm/using-the-ticket-system#2600, Assigning a topic>> chapter.

[.instruction]
Adding a topic:

. Go to *System » System settings » CRM » Ticket system » Settings » Tab: Topics*.
. Click on *Add*.
. Enter a name for the *default language* and the selected language.
. Enter the *position*.
. *Save* (icon:save[role="green"]) the settings.

Edit a topic by clicking on the previously saved text. Click on *Delete* to delete the line. You are asked to confirm your decision.

[#1600]
== Creating a ticket

A ticket has many characteristics such as the progress, the origin, the ticket type and the status. It is possible to manage different ticket types with individual status values. Furthermore, multiple users can be owners of a ticket and edit it. This requires you to define different roles for the ticket system. You can individually assign these roles to an owner.

You can either create tickets manually or automatically. Which settings you have to carry out is described in the following chapters.

[#1700]
=== Manually creating a ticket

There are two ways to manually create tickets:

* without a template
* from a template

When creating tickets without a template, you have to carry out each setting individually. When creating tickets from a <<crm/using-the-ticket-system#3100, template>>, the settings saved in the template are applied.

[#1800]
==== Creating a ticket without a template

Proceed as described below to create a ticket manually and without a template.

[.instruction]
Creating a ticket without a template:

. Go to *CRM » Ticket system*.
. Click on *New ticket*.
. Carry out the settings. Pay attention to the information given in <<table-create-ticket-without-template>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The ticket is created.

[[table-create-ticket-without-template]]
.Settings in the *CRM » Ticket system » Tab: New ticket* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Role*
|Select the role of the owner from the drop-down list. You can select the <<crm/using-the-ticket-system#700, roles>> that you set up in the *System » System settings » CRM » Ticket system » Settings » Tab: Roles* menu. +
This is a mandatory field. If no role is selected, the ticket cannot be created.

|*Owner*
|The active user is automatically assigned as owner of a new ticket. Select another owner's name from the drop-down list, if required. +
This is a mandatory field. If no owner has been selected, the ticket cannot be created.

|*Customer*
|Press the down arrow key on your keyboard. A list of the customers is displayed. The customers are displayed in order by their ID. The customer with the lowest ID is displayed at the top. By clicking on the customer, the name and the ID of the customer are transferred into this field.

|*Title*
|Enter the ticket title. +
This is a mandatory field. If no title has been entered, the ticket cannot be created.

|*Tags*
|Click to add tags. You can select the tags that you set up in the *System » System settings » Settings » Tags* menu. For further information, refer to the <<basics/working-with-plentymarkets/tags#, Tags>> page of the manual.

|*Folder*
|Select the folder from the drop-down list. You can select the <<crm/using-the-ticket-system#4500, folders>> that you created in the *CRM » Ticket system* menu.

|*Priority*
|Select the priority from the drop-down list.

|*Type*
|Select the type from the drop-down list. You can select the types that you created in the *System » System settings » CRM » Ticket system » Settings » Tab: Types & Status* menu. +
This is a mandatory field. If no type has been selected, the ticket cannot be created.

|*Status*
|Select the status from the drop-down list. Only when a type has been selected before is the drop-down list activated. You can select the statuses that you created in the *System » System settings » CRM » Ticket system » Settings » Tab: Types & Status* menu. +
This is a mandatory field. If no status has been selected, the ticket cannot be created.

|*Deadline*
|Enter the deadline in the format M/DD/YY or select the date from the calendar.

|*Define ticket as confidential (not visible to customer)*
|Click to define the ticket as confidential. If the ticket is confidential, it is not possible to send messages. Confidential tickets are not visible to the customer.

|*Client (store)*
|Select the client (store) from the drop-down list.
|====

Once you saved the settings, the ticket ID is displayed in the ticket tab. Furthermore, a toolbar is displayed. Pay attention to the information about the toolbar given in <<table-toolbar-ticket>>.

[[table-toolbar-ticket]]
.Toolbar in the *CRM » Ticket system » Open ticket* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Add message*
|Messages are public, i.e. visible to customers. Messages are marked in blue. If a ticket is *confidential*, it is not possible to write a message. For further information, refer to the <<crm/using-the-ticket-system#2400, Adding a message>> chapter.

|*Add comment*
|Comments are only visible internally, i.e. they are not visible to customers. Comments are marked in red. Comments are used for internal communication. For further information, refer to the <<crm/using-the-ticket-system#2500, Adding a comment>> chapter.

|*Send email template*
|Click to send an email template. The *Send email* window opens. Select the template from the drop-down list and click on *Send email template*. +
If the ticket is not linked to a customer, it is not possible to send the email template. To do so, click in the *Customer* field and press the down arrow key on your keyboard. A list of the customers is displayed. The customers are displayed in order by their ID. The customer with the lowest ID is displayed at the top. By clicking on the customer, the name and the ID of the customer are transferred into this field.

|*Print*
|Prints the ticket. A ticket is printed as a <<crm/using-the-ticket-system#5300, ticket card>>.

|*Open parent ticket*
|Opens the parent ticket in a new tab, if available.

|*Hide / Show status history*
|Displays or hides the status history. If *Show status history* is activated, the window *Status history* is displayed on the right side of the ticket. The status history displays the statuses that the ticket had up to this point.

|*Hide / Show events*
|Displays or hides events. If *Show events* is activated, the window *Events* is displayed on the right side of the ticket. All events relating to the ticket are displayed.

|*Show / Hide list of owners*
|Shows or hides the list of owners. If *Show list of owners* is activated, the area *Owner* is displayed on the right side of the ticket. All owners of the tickets as well as their roles are displayed.

|*Hide / Show tags*
|Displays or hides tags. If *Show list of tags* is activated, the area *Tags* is displayed on the right side of the ticket. Further <<basics/working-with-plentymarkets/tags#, tags>> that were created before in the *System » System settings » Settings » Tags* menu can be added here. You can save as many tags for the ticket as needed.
|====

[#1900]
==== Creating a ticket from a template

If you created templates in the *System » System settings » CRM » Ticket system » Templates* menu, you can create tickets or child tickets that are based on one of these general or personal templates. Before you start carrying out the settings in the following menu, pay attention to the chapters <<crm/using-the-ticket-system#3100, Creating a general ticket template>> and <<crm/using-the-ticket-system#3200, Creating a personal ticket template>>. Proceed as described below to create a ticket from a template.

[.instruction]
Creating a ticket from a template:

. Go to *CRM » Ticket system*.
. Click on *New ticket from template*. +
→ The *Create new ticket from template* window opens.
. Select the <<crm/using-the-ticket-system#3100, template>> that you have previously created in the *System » System settings » CRM » Ticket system » Templates* menu from the drop-down list.
. Click on *New ticket* to apply the template settings to the ticket. +
→ A new ticket opens. The settings saved in the template are already entered.
. Make changes to the template, if necessary.
. *Save* (icon:save[role="green"]) the settings. +
→ The ticket is created.

[#2000]
=== Automatically creating tickets

You can automatically create tickets from emails, eBay messages and forms.

[#2200]
==== Creating tickets from eBay messages

plentymarkets gives you the possibility to retrieve eBay messages directly. Afterwards, they can immediately be imported into your ticket system. The messages are retrieved every hour. Go to <<omni-channel/multi-channel/ebay#600, System » System settings » Markets » eBay » Settings » Tab: Account settings>> and make sure that the *Automatically retrieve messages* option is activated. Select a message type and message status there as well. These parameters are automatically assigned to the eBay messages. If necessary, set up a specific type and status that you want to use for your eBay messages.

You can also use the ticket system to answer afterwards. Your customer receives the message via the eBay messaging system. An eBay message may not exceed the maximum of 950 characters. If you use more characters, the message is not transmitted.

The first time that eBay messages are imported, only the ones from the last seven days are retrieved. If an import has been carried out before, messages are imported until the date of the last import. However, this last import may not date back more than seven days. Otherwise, only messages from the last seven days are imported again. You can access information about the imports by going to <<basics/data-exchange/api-log#, Data » API log>> and looking at the *EbayMemberMessages* API log.

[#2300]
==== Creating tickets from forms

Forms are often used to help customers contact the online store. Once a customer has filled out the contact form in your online store, this information is saved as a ticket. You can answer the customer directly from the ticket. However, this is only possible if a valid email account was set up under *System » System settings » CRM » Ticket system » Email accounts*.

You receive an email notification whenever a new message is received. This notification is separate from the ticket and any procedures that are carried out in the ticket system. The notification is sent to the address that was saved under *System » System settings » Client » Select client » Email » Login details*. You receive this email notification even if you did not <<crm/using-the-ticket-system#100, book>> the ticket system.

[TIP]
.Example for using the contact form
====
A customer sends you a question with the contact form in your online store. The contact form is used to create a ticket in the ticket system. The ticket contains the customer's message. You answer the customer by writing a message in the ticket system. The customer receives an email with the help of an event procedure. The customer now replies to your message from his or her own email program. If parameters such as the ticket ID etc. were inserted into the email as template variable, the email automatically assigned to the ticket. +
If the customer deleted the ticket ID or other parameters from the subject line and from the email, it is not possible to assign the email to a ticket. A new ticket is created. +
A new ticket is also created if the customer decides to use the contact form again instead of answering the email directly. In this case, no assignment parameters would be included in the message and your plentymarkets system would not be able to recognise that the message belongs to a previous thread.
====

Proceed as described in the following to make sure that contact forms filled out by customers in your online store are automatically created as tickets.

[.instruction]
Creating tickets from forms:

. Go to *System » System settings » CMS » Forms*.
. Enter the *Form name*.
. Select the *Ticket type*.
. Select the *Ticket status*.
. Enter the field name for the email address.
. Select the *Text field email address* type from the drop-down list. +
→ Pay attention to the note in the following box.
. Enter other field names as needed.
. Select a *Type* for each field name from the drop-down list.
. *Save* (icon:save[role="green"]) the settings. +
→ This type of ticket is created every time the form is filled out and submitted.

All of the other form settings are optional. For further information, refer to the <<omni-channel/online-store/cms#settings-forms, Forms>> page of the manual.

[IMPORTANT]
.Assignment based solely on email addresses
====
Contact forms are only assigned by the customer's email address. Select the type *Text field email address* for the email address field in contact forms. Otherwise your plentymarkets system does not recognise the information as an email address. If an email address is entered into a different field, e.g. into the message field, it is not taken into consideration for the assignment and answers are not sent to this email address.
====

If the email address can be assigned to an existing customer, this customer is displayed in the ticket. If the email address cannot be assigned to an existing customer, you do not see the sender's email address in the ticket system. Messages that are now composed in the ticket system are still sent to the sender's address.

Use messages to reply to your customers from within the ticket system. Note that messages are only sent as emails if an event procedure was set up for this purpose.

[IMPORTANT]
.First email account is used for answers to form tickets
====
If you set up multiple <<crm/using-the-ticket-system#2100, email accounts>> under *System » System settings » CRM » Ticket system » Email accounts*, the email account that was set up first is used for sending answers to form tickets.
====

[#2400]
== Adding a message

Messages are used for external communication, i.e. for communicating with your customers. Click on *Add message* to create a new message. Enter your message text into the text field of the *Message* window. Use the toolbar to format the text. If you saved a <<basics/working-with-plentymarkets/customise-user-account#10, complimentary close>> in the user account, it is automatically added onto the end of this user's messages.

A timer starts in the *Events* section when the message is created. This makes it possible to measure the time to the exact second. If the process needs to be billed, you can enter the time into the *Min.* field to the left of the timer. The lower portion of the event area lists the events that were previously carried out. The events are listed in chronological order. For example, you can see if a different employee has already edited this ticket.

[IMPORTANT]
.New event with filters service type, bill and duration added
====
In the *System » System settings » CRM » Ticket system » Events* menu, it is possible to add the event *New event* and the filters *Service type*, *Bill* and *Duration*. This allows you to differentiate in more detail and thus to also send different email templates.

Sending automatic email templates for service units in the *System » System settings » Client » Select client » Email » Automatic* menu still applies for events that were created in the contact data record.

*_Important:_* This function was deactivated for the ticket system. This is why you have to set up a new event procedure in the *System » System settings » CRM » Ticket system » Events* menu.
====

[.instruction]
Billing a process:

. Go to *CRM » Ticket system*.
. Open the ticket.
. Click on *Add message*. +
→ The *Message* window opens and the timer starts.
. Activate the option *Bill* if the process should be billed.
. Select the type of process from the drop-down list.  +
→ The following options can be selected: *Call*, *Ticket*, *Email*, *Meeting*, *Webinar*, *Development* and *Design*.
. Enter the time in minutes in the *Min.* field.
. *Save* (icon:save[role="green"]) the settings.

[TIP]
.Information about the timer
====
If you are not able to begin working as soon as you opened the message window, click on *Reset* when you are ready to begin. The timer is reset to zero. If you would like to interrupt the editing of the message, click on *Pause* and afterwards on *Play*.
====

[IMPORTANT]
.Sending messages via email
====
Messages are only sent as emails if an <<crm/using-the-ticket-system#2900, event procedure>> was set up for this purpose. +
To do so, the event *New message* must be set up. The procedure *Send email* is recommended. The email template that is selected here must contain the template variable *$TicketLastMessage*. Furthermore, *Customer* must be selected as the recipient. The email subject should also include the ticket ID. Use the template variable *$TicketID* for this.
====

[#2500]
== Adding a comment

Comments are added the same way as <<crm/using-the-ticket-system#2400, messages>>. Note that comments are only visible internally. They are not visible to the customer. This is intentional since the comment function is meant for sending messages within your company. You can use the comment function to pass on the current state of the ticket or information about the topic or the customer to a different employee or user of the ticket system. If you saved a <<basics/working-with-plentymarkets/customise-user-account#10, complimentary close>> in the user account, it is automatically added onto the end of this user's comments.

A timer starts in the *Events* section when the comment is created. This makes it possible to measure the time to the exact second. If the process needs to be billed, you can enter the time into the *Min.* field to the left of the timer. The lower portion of the event area lists the events that were previously carried out. The events are listed in chronological order. For example, you can see if a different employee has already edited this ticket.

[#2600]
== Assigning a topic

A topic can be saved with every message or comment. Although this is not mandatory, topics can help you understand the general content of a message or comment at a glance. This is particularly useful for longer texts. The topic thus functions as a headline.

Select the topic from the drop-down list above the text field of the message or comment window. Once you saved, the topic is displayed as a headline for this part of the communication. You need to create topics before they can be selected in the ticket system. To do so, go to *System » System settings » CRM » Ticket system » Settings » Tab: Topics*. How you add topics is described in the <<crm/using-the-ticket-system#1100, Adding a topic>> chapter.

[.instruction]
Assigning a topic:

. Go to *CRM » Ticket system*.
. Open the ticket.
. Click on *Add message* or *Add comment*.
. Select a topic from the drop-down list.
. *Save* (icon:save[role="green"]) the settings.

[#2700]
== Entering answers to FAQs

You can insert previously written text blocks into messages. Go to *CRM » FAQs* to create these text blocks. This saves you a lot of time and effort, particularly if you often answer the same questions or deal with the same problems. You can also enter long texts here and save a lot of time when working with your tickets.

Go to *CRM » FAQs* and create a useful structure of folders, sub-folders and questions. Make sure to select the setting *visible* for the ticket system in the *CRM » FAQs » Tab: Folder » Expand folder » Tab: Settings* menu. For further information, refer to the <<omni-channel/online-store/cms#faqs, FAQs>> page of the manual.

[#2800]
== Manually sending an email template

You are not limited to only communicating in the ticket system with messages and comments. You can also send <<crm/sending-emails#1200, email templates>>. Go to *System » System settings » Client » Select client » Email » Templates* to set up email templates. An email template includes a standard text that is applicable to all recipients. You can supplement this text with dynamic content that is automatically inserted with the help of template variables.

First create an email template. For example, use the template variables for the subject line and the text as listed in <<table-template-variables-ticket-system>>. You can see a list of all the template variables that are available for an email template by clicking on *Template variables and template functions* on the top left within the template. From there, you can insert the template variables into the template simply by clicking on it. <<table-template-variables-ticket-system>> shows a list of useful template variables for the ticket system.

For the email template, select e.g. the template variables *$TicketID* and *$TicketTitle* if you want to have the ticket ID and the ticket title displayed in the subject line. If the text should contain the status, the priority and a link to the ticket, select the template variables *$TicketStatus*, *$TicketPriority* and *$TicketBackendURL* and enter these in the text field of the template.

[.instruction]
Creating an email template:

. Go to *System » System settings » Client » Select client » Email » Templates*.
. Click on *New email template*.
. Carry out the settings. For further information, refer to the explanations on the <<crm/sending-emails#, Sending emails>> page of the manual in the <<crm/sending-emails#1200, Creating an email template>> chapter.
. Select the setting *Only text in HTML format* under *Content*.
. *Save* (icon:save[role="green"]) the settings.

[IMPORTANT]
.Only text in HTML format
====
Open the email templates and look at the *Settings* tab. Make sure that the *Content* drop-down list was set to *Only text in HTML format*. Otherwise the template variables are not translated.
====

[[table-template-variables-ticket-system]]
.Template variables for email templates in the ticket system
[cols="1,3"]
|====
|Setting |Explanation

|*$TicketBackendURL*
|Links to the ticket in the *CRM » Ticket system* menu.

|*$TicketHistory*
|Displays the text that was last saved in the ticket, i.e. the text of a comment or a message.

|*$TicketID*
|Displays the ticket ID that the email was sent from.

|*$TicketLastComment*
|Displays the text of the last comment.

|*$TicketLastMessage*
|Displays the text of the last message.

|*$TicketPriority*
|Displays the priority of the ticket. The star values are displayed in ascending order with the numbers 0 to 5.

|*$TicketStatus*
|Displays the status of the ticket.

|*$TicketTitle*
|Displays the title of the ticket.

|*$TicketURL*
|Links to the ticket in the *My account* area. The customer can read the message in the My account area, write an answer and send it. +
For further information, refer to the <<crm/using-the-ticket-system#5500, Creating tickets in the My account area>> chapter.

|*$SignatureText*
|The following only applies if email templates are manually sent: Displays the signature that was saved in the system's email settings.

|*$SignatureHTML*
|The following only applies if <<crm/using-the-ticket-system#2900, email templates are sent using an event procedure>>: Displays the complimentary close and the signature that were saved in the settings of the user account. +
This template variable displays the user's signature if it was saved in the settings for that user. This signature takes priority over the signature that was saved in the system's email settings.
|====

Proceed as described below to manually send an email template.

[.instruction]
Manually sending an email template:

. Go to *CRM » Ticket system*.
. Open the ticket.
. Click on *Send email template*.  +
→ The *Send email* window opens.
. Select an email template from the drop-down list.
. Click on *Send email template*.

If the ticket is not linked to a customer, the email template cannot be sent. If you manually send email templates, the signature displayed in these emails is the signature that was saved in the system's email settings.

[#2900]
== Automatically sending email template

In the *System » System settings » CRM » Ticket system » Events* menu, you use filters to select tickets and then assign the tickets to automatic procedures which are carried out by an <<<automation/event-procedures#, event procedure>>. For example, every time that a ticket is received, you could automatically send an email template that informs the customer that his or her ticket was received and explains what happens next.

As already described in <<table-template-variables-ticket-system>> , the complimentary close and the signature that are saved in the settings of the user account are displayed when you use the template variable *$SignatureHTML*. This signature takes priority over the signature that was saved in the system's email settings.

Note that an event procedure also has to be set up for sending messages and comments via email. If you answer your customers with messages in the ticket system, you need to set up an event procedure that sends the last ticket message as an email. Otherwise the customer does not receive your answer. For further information about customer communication in the ticket system, refer to the chapters <<crm/using-the-ticket-system#2400, Adding a message>>, <<crm/using-the-ticket-system#2500, Adding a comment>>, <<crm/using-the-ticket-system#2600, Assigning a topic>>, <<crm/using-the-ticket-system#2700, Entering answers to FAQs>> and <<crm/using-the-ticket-system#2800, Manually sending an email template>>.

For further information, refer to the <<basics/automation/event procedures#, Event procedures>> page of the manual.

[IMPORTANT]
.Avoid contradictory filter options
====
Avoid using contradictory filter options if you set up multiple filters for one procedure. For example, an error occurs if you use several status options for the same ticket type.

Example: First filter: Type *eBay*, status *completed*. Second filter: Type *eBay*, status *in progress*.
====

Set up an <<automation/event-procedures#, event procedure>> to receive an email every time that a new ticket message is received in your ticket system, for example.

[.collapseBox]
.Setting up an event procedure
--
. Go to *System » System settings » CRM » Ticket system » Events*.
. Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<table-event-procedure-new-message-ticket-system>>.
. *Save* (icon:save[role="green"]) the settings.
. Pay attention to the information given in <<table-event-procedure-new-message-ticket-system>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings.
--
[[table-event-procedure-new-message-ticket-system]]
.Event procedure for automatically being informed when new messages are received in the ticket system
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*New message from customer*
|

|*Filter*
|*Owner*
|Select the owner.

|*Procedure*
|*Send email*
|Select the email template and recipient.
|====

[#3000]
== Automatically deleting tickets

Go to *System » System settings » CRM » Ticket system » Procedures* and set up procedures that are carried out automatically by your plentymarkets system at a certain time. For example, you could set up a procedure to automatically delete tickets if they were not edited within a certain amount of time and if they have a specific status.

Proceed as described below to set up the example described above.

[.instruction]
Automatically deleting tickets:

. Go to *System » System settings » CRM » Ticket system » Procedures*.
. Click on *Add procedure*. +
→ The *Create a new procedure* window opens.
. Enter the name.
. Select the time from the drop-down list when the procedure is to be carried out every day.
. *Save* (icon:save[role="green"]) the settings. +
→ The procedure is created.
. Click on *Add filter*. +
→ The *Add filter* window opens.
. Select the filter *Last status change*.
. Click on *Add*.
. Select an option from the drop-down list.
. Click on *Add filter* to add another filter. +
→ The *Add filter* window opens.
. Select the filter *Type/status*.
. Click on *Add*.
. Activate the previously created <<crm/using-the-ticket-system#900, status>>. +
→ Pay also attention to the previously created <<crm/using-the-ticket-system#800, type>>.
. Click on *Add procedure*. +
→ The *Add procedure* window opens.
. Select the procedure *Delete*.
. Click on *Add*.
. Place a check mark.
. Place another check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings.

Use this menu to create as many procedures as you like and select filters and a time for theses procedures. For further information about setting up the procedure manager, refer to the <<automation/procedure-manager#, Procedure manager>> page of the manual.

[#3100]
== Creating a general ticket template

Go to *System » System settings » CRM » Ticket system » Templates* to create templates for your tickets. Templates help you work with the ticket system more efficiently. Furthermore, you can decide which user roles the ticket templates should be available for. They can be used for specific roles or for all roles. This helps you keep track of even a large number of templates.

[.instruction]
Creating a general ticket template:

. Go to *System » System settings » CRM » Ticket system » Templates*.
. Click on *New template*. +
→ The *New template* window opens.
. Enter the *name*.
. Enter the *position*.
. Click on *Add*. +
→ The template is created and opened.
. Carry out the settings. Pay attention to the information given in <<table-settings-ticket-template>>.
. *Save* (icon:save[role="green"]) the settings.

[[table-settings-ticket-template]]
.Settings in the ticket template
[cols="1,3"]
|====
|Setting |Explanation

|*Name*
|The name of the template is displayed. The name can be changed here.

|*Position*
|The position number specifies which order the templates should be displayed in. By default, they are sorted in ascending order by their position number. The position number can be changed here. +
*_Tip_*: Count by tens when creating position numbers. This allows you to easily add new templates in between later on.

|*Title*
|Enter a title. Tickets that use this template receive this title. The title can be changed when the ticket is created.

|*Customer*
|Select a customer to create a template for this customer.

|*Confidentiality*
|Activate to create a template for confidential tickets. If a ticket is confidential, messages are only sent to people who are owner of the ticket. Customers do not receive any messages for a confidential ticket even if you have set up event procedures.

|*Client (store)*
|Select a client (store) the template should be used for.

|*Type*
|Select a ticket type to create a template for this type. Ticket types are created in the <<crm/using-the-ticket-system#800, System » System settings » CRM » Ticket system » Settings » Tab: Types & Status>> menu.

|*Status*
|Select a ticket status to create a template for this status. Ticket statuses are created in the <<crm/using-the-ticket-system#900, System » System settings » CRM » Ticket system » Settings » Tab: Types & Status>> menu.

|*Priority*
|Select a priority to create a template for this priority.

|*Owner*
|Select an owner to create a template for this owner. Whether or not someone can be selected as owner in the ticket system depends on the settings that were saved in the <<basics/admin-tasks/manage-users#40, user account>>.

|*Visibility*
|Select one of the following options: *Public*, *Private* or *User roles*. +
*Public* = The template is visible to all users. +
*Private* = The template is only visible to the user who created it. Further information can be found in the <<crm/using-the-ticket-system#3200, Creating a personal ticket template>> chapter. +
*User roles* = An additional setting is displayed if you select this option. Select which user roles the template should be visible for.

|*User roles*
|Only visible if the setting *User roles* was selected under *Visibility*. Select which user roles the template should be visible for.

|*Tags*
|Select tags to create a template with these tags. Go to <<basics/working-with-plentymarkets/tags#, System » System settings » Settings » Tags>> to create tags.

|*Deadline*
|Enter the number of days. Tickets that are created with this template have a deadline that is this many days after the ticket is created.

|*Resubmission*
|Enter the number of days and select the time. Tickets that are created with this template are resubmitted after this many days at the selected time.

|*Message*
|Activate *FAQ* or *Own message*. +
*FAQ* = Click on *Edit*. The *Select FAQ* window opens. Select an <<omni-channel/online-store/cms#faqs, FAQ>> that should be entered when using the template. Click on *Apply*. +
*Own message* = Enter a message that should be entered when using the template.

|*Comment*
|Activate *FAQ* or *Own comment*. +
*FAQ* = Click on *Edit*. The *Select FAQ* window opens. Select an <<omni-channel/online-store/cms#faqs, FAQ>> that should be entered when using the template. Click on *Apply*. +
*Own comment* = Enter a comment that should be entered when using the template.

|*Enter complimentary close*
|Activate to automatically insert the complimentary close at the end of a message or comment.
|====

Edit a template by clicking on the previously saved text. Click on *Delete* to delete the line. You are asked to confirm your decision.

[#3200]
== Creating a personal ticket template

In the ticket overview in the *CRM » Ticket system* menu, you can create user-defined templates. These personal templates are listed there and in the *System » System settings » CRM » Ticket system » Templates* menu. They are only visible for the user who created them. The personal templates are created and edited in a separate window. This window opens when clicking on *Personal templates*.

Set up personal ticket templates the same way you create general ticket templates. Pay attention to the <<crm/using-the-ticket-system#3100, Creating a general ticket template>> chapter. The personal templates are included in the list of general templates. They are only visible for the user who created them. However, general templates are not included in the list of personal templates. Go to *System » System settings » CRM » Ticket system » Templates* and use the *Visibility* option to control which templates are displayed. Select the setting *Private* for personal templates.

[#3300]
== Displaying the ticket overview

Go to *CRM » Ticket system*. Tickets are displayed within the *Tickets* tab. There you can see important information about your tickets, e.g. their age, title, customer name and progress. Use the <<basics/working-with-plentymarkets/general-functions#50, Customising the layout>> function and select which parameters should be displayed in the ticket overview.

By clicking on the ticket, it opens in its own tab. You have the possibility to <<crm/using-the-ticket-system#3500, edit>> the ticket here.

Default folders are displayed in the *Folder* tab. Your tickets are sorted into these folders based on specific criteria, e.g. outstanding tickets. For example, click on the folder to display all outstanding tickets in the *Tickets* tab. It is neither possible to rename nor to delete these default folders. You can, however, create <<crm/using-the-ticket-system#4500, custom folders>>. These folders are added to the list in the *Folder* tab.

Above the ticket overview in the *CRM » Ticket system » Tab: Tickets* menu, you can create a new ticket manually or from a template. You can also select personal templates or use the group function. <<table-ticket-overview>> explains the settings that you can carry out in the *Tickets* tab.

[[table-ticket-overview]]
.Settings in the *CRM » Ticket system » Tab: Tickets* menu
[cols="1,3"]
|====
|Setting |Explanation

|*New ticket*
|Click to create a new ticket manually.

|*New ticket from template*
|Click to create a ticket and give it the settings and entries from a template, e.g. example texts.

|*Personal templates*
|Create or edit personal templates. Personal templates are included in the list of <<crm/using-the-ticket-system#3100, general templates>>. However, general templates are not included in the list of personal templates.

|*Group function*
|Click to edit all of the activated tickets simultaneously.

|*Search options*
|You can use the drop-down lists to create individual search options and only display those tickets that you want to see or edit, e.g. only those tickets that relate to a specific owner and has a specific priority. +
Click on *Search* to display the tickets with the selected properties. +
For further information about the search options, refer to the chapter <<crm/using-the-ticket-system#3400, Searching for tickets>>.

|*Age in days*
|Different colours indicate how old the tickets are. The colours have the following meaning: +
Green = The ticket is 0 to 3 days old. +
Yellow = The ticket is 4 to 5 days old. +
Orange = The ticket is 6 to 7 days old. +
Red = The ticket is at least 8 days old.
|====

[TIP]
.Changing the order of sorting in the columns
====
Changing the order of sorting in the columns Simply click on the triangle in the title bar. You can also change the order of sorting for the following columns: *Age in days*, *ID*, *Priority*, *Created on*, *Last change*, *Progress* and *Resubmission*. The only requirement is that you activate the parameters via the <<basics/working-with-plentymarkets/general-functions#50, Customising the layout>> function.
====

[#3400]
== Searching for tickets

Various entry fields and filters are available in the ticket search in the *Tickets* tab. They help you narrow down the list of tickets to find the exact ones that you are looking for. Expand the *Search* area to select further filters and entry fields. This allows to search for your tickets even more detailed.

[.instruction]
Searching for tickets:

. Go to *CRM » Ticket system*.
. In the *Tickets* tab in the *Search* area, select filters and enter data in the entry fields. Pay attention to the information given in <<table-search-ticket>>.
. Click on *Search*.  +
→ The tickets that match the selected settings are displayed.

[[table-search-ticket]]
.Search options in the *CRM » Ticket system » Tab: Tickets* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Search*
|Perform a search.

|*Ticket data*
|Enter text to search for this content.

|*Priority*
|Select a priority to only see tickets with this priority.

|*Type/status*
|Search using a combination of ticket type and ticket status. Select one, multiple or all options from the drop-down list. +
Go to *System » System settings » CRM » Ticket system  » Settings* to edit existing <<crm/using-the-ticket-system#800, types>> and <<crm/using-the-ticket-system#900, statuses>> or to create new ones.

|*Status group*
|Select one, multiple or all options from the drop-down list. +
Go to *System » System settings » CRM » Ticket system » Settings* to edit existing <<crm/using-the-ticket-system#1000, status groups>> and to create new ones.

|*Owner*
|Limit the ticket search to an owner. The drop-down list lists all of the users who are activated for the *Ticket* option in their user account under *Owner* tab.

|*Customer class*
|Select a customer class to only search for tickets that belong to customers with this customer class. Go to <<crm/managing-contacts#15, System » System settings » CRM » Classes>> to create further classes.

|*Client (store)*
|Select the client (store) from the drop-down list.

|*Customer ID*
|Enter the customer ID to only search for tickets with this customer ID.

|*Deadline*
|Select one of the following options from the drop-down list to only search for tickets that have this deadline: *yesterday*, *today*, *tomorrow*, *exceeded* or *in the future*.

|*Role*
|Select one or multiple roles or all options from the drop-down list. Go to <<crm/using-the-ticket-system#700, System » System settings » CRM » Ticket system » Settings>> to create roles.

|*Relational progress operator*
|Use the operator to specify whether a ticket's progress should be greater than, less than or equal to the progress that was entered.

|*Progress*
|Select a percentage from the drop-down list to only search for tickets that correspond to the specified relational operator and progress.

|*Resubmission*
|Select a resubmission date from the drop-down list to only search for tickets that have this resubmission date. +
The procedure manager in the *System » System settings » CRM » Ticket system » Procedures* can be used to remind you of the ticket. An example how to set up a procedure and select filters and the time can be found in this <<crm/using-the-ticket-system#3000, chapter>>.

|*Tags*
|Click into the field. Select one or more tags to only search for tickets that contain these tags. First tags must be created in the *System » System settings » Settings » Tags* menu.
|====

[#3500]
== Editing tickets

A ticket is made up of several messages and comments. The comments can only be read internally. In addition, you can add files and tasks to a ticket. Tickets can also be added up to build a chain: One ticket can have several children and these children can have children themselves.

Which settings you may carry out in a ticket's tabs is described in the following sub-chapters.

[#3600]
=== Displaying and editing ticket settings

You can see all the settings of your ticket at a glance in the *CRM » Ticket system » Open ticket » Tab: Ticket* menu. You can also change some of the settings here. <<table-edit-ticket>> explains the setting options for your tickets.

[[table-edit-ticket]]
.Settings in the *CRM » Ticket system » Open ticket » Tab: Ticket* menu
[cols="1,3"]
|====
|Setting |Explanation

|*Ticket source*
|The symbol shows the source of the ticket. +
plentymarkets logo = *ticket source: Back end* +
Globe = *Ticket source: Front end* +
eBay logo = *Ticket source: eBay* +
Letter symbol = *Ticket source: Email*

|*Save*
|Saves the settings.

|*Deadline*
|Shows the number of days until the deadline as well as the progress in percent. +
If no deadline has been selected yet, select a date from the calendar. The progress bar is only displayed after you have selected and saved the date. The deadline can be changed by clicking on it.

|*Priority*
|Displays the priority of the ticket. There are 6 priority levels. +
Grey star = lowest priority (default priority) +
Two yellow stars = highest priority

|*Type*
|Displays the type. Ticket types are created in the <<crm/using-the-ticket-system#800, System » System settings » CRM » Ticket system » Settings » Tab: Types & Status>> menu.

|*Status*
|Displays the current status. Ticket statuses are created in the <<crm/using-the-ticket-system#900, System » System settings » CRM » Ticket system » Settings » Tab: Types & Status>> menu.

|*Folder*
|Displays the folder. Folders are created in the <<crm/using-the-ticket-system#4500, System » System settings » CRM » Ticket system » Tab: Folder>> menu.

|*Day of resubmission*
|Displays the day of resubmission.

|*Resubmission before hour/ +
Resubmission before minute*
|Select the time from the drop-down list.

|*ID*
|Displays the ticket ID. The ID is automatically assigned by the system and cannot be changed.

|*Age*
|The age of the tickets in days is displayed here. Depending on the age, the ticket is displayed in a different colour. +
Green = The ticket is 0 to 3 days old. +
Yellow = The ticket is 4 to 5 days old. +
Orange = The ticket is 6 to 7 days old. +
Red = The ticket is at least 8 days old.

|*Progress*
|Displays the progress in percent by means of a bar. The percentage is displayed in the bar.

|*Customer*
|Displays the ID and the name of the customer. Customers are <<crm/using-the-ticket-system#2100, automatically assigned>> in some cases, e.g. when tickets are automatically created from emails.

|*Define ticket as confidential (not visible to customer)*
|Click to define the ticket as confidential. If the ticket is confidential, it is not possible to send messages. Confidential tickets are not visible to the customer.

|*Order ID*
|Displays the order ID if the ticket is linked to an order.

|*Client (store)*
|Displays the client (store) that the ticket is linked to.
|====

[#3700]
=== Displaying the customer data record

The menu *CRM » Ticket system » Open ticket » Tab: Customer* contains the customer data as it is also found in the <<crm/crm/managing-contacts#300, CRM » Contacts » Open contact>> menu. You can also edit the customer data record here. This tab is only visible if the ticket is linked to a customer.

[#3800]
=== Displaying orders

Go to *CRM » Ticket system » Open ticket » Tab: Search orders* to see the customer's orders. You can search for orders and edit them in this menu. This tab is only visible if the ticket is linked to a customer.

[#3900]
=== Showing the attachment

Go to *CRM » Ticket system » Open ticket » Tab: Attachment* to see all file attachments that were uploaded to this tab. Both your customers and staff members can attach documents to tickets and have permanent access to them. The number of attachments is displayed in parentheses in the tab's title. Once the first file has been successfully uploaded, a table is displayed. The table lists the file name, the name of the employee or customer who uploaded the file as well as the visibility and the date.

The image files immediately open after the click. If this is not supported by the browser, the file can be downloaded. With the setting *Visibility*, you decide whether the file is also visible for your customers or only for you and your employees.

If you activated the option *Attachment* via the <<basics/working-with-plentymarkets/general-functions#50, Customising the layout>> in the *CRM » Ticket system » Tab: Tickets* menu, you can directly see in the ticket overview the tickets that have an attachment.

[IMPORTANT]
.File types permitted for upload
====
The following file types are permitted and can be uploaded: *COMMA*, *CSS*, *CSV*, *DOC*, *DOCX*, *EXCEL*, *GIF*, *GZIP*, *HTML*, *JPEG*, *MSWORD*, *ODC*, *ODF*, *ODG*, *ODM*, *ODS*, *ODT*, *OTG*, *OTH*, *OTS*, *OTT*, *OXT*, *PNG*, *PDF*, *RICHTEXT*, *RTF*, *SWF*, *SDA*, *SDC*, *SDW*, *SXW*, *STW*, *TEXT*, *X_EXCEL*, *X_LATEX*, *X_TAR*, *XLS*, *X_XLS*, *XML*, *TIFF*, *ZIP*.
====

[#4000]
=== Creating a task

Tasks help you plan concrete duties and assign them to different employees. If a task is created in the *CRM » Ticket system » Open ticket » Tab: Tasks*, it is linked to the ticket. This link is also visible in the overview of tasks under *Start » Tasks*. The number of tasks is displayed in parentheses in the tab's title. This chapter explains how to search for tasks.

[.instruction]
Creating a task:

. Go to *CRM » Ticket system » Open ticket » Tab: Tasks*.. Click on *New task*.
. Carry out the settings. Pay attention to the explanations in the <<basics/working-with-plentymarkets/tasks-and-calendars#300, Creating a task>> chapter on the <<basics/working-with-plentymarkets/tasks-and-calendars#, Managing tasks and calendars>> page of the manual.
. *Save* (icon:save[role="green"]) the settings. +
→ The newly created task is displayed in the *Tasks* tab.

[#4100.subhead]
Searching for tasks

Proceed as follows to search for tasks that have already been created.

[.instruction]
Searching for tasks:

. Go to *CRM » Ticket system » Open ticket » Tab: Tasks*.
. Click on the arrow in the top left corner to open the *Filter* tab.
. Carry out the settings. Pay attention to the explanations in the <<basics/working-with-plentymarkets/tasks-and-calendars#400, Searching for tasks>> chapter on the <<basics/working-with-plentymarkets/tasks-and-calendars#, Managing tasks and calendars>> page of the manual.
. Click on *Search*.

[#4200]
=== Linking tickets

In the *CRM » Ticket system » Open ticket » Tab: Children* menu, you can link tickets with each other. This means that you can assign further tickets (so called children) to a ticket or create a child ticket in the *Children* tab. One ticket can have several children (parent-child concept) and these children can have children themselves. This characteristic is especially helpful if you have bigger projects and you want to divide tasks and assign them to different members of your staff (owners) or to different teams. Open the original parent ticket in order to see the processing status of the child ticket. The number of child tickets is displayed in parentheses in the *Children* tab.

[#4300]
==== Assigning a ticket as child ticket

You can assign existing tickets as child tickets. This is done in the *Ticket search* tab.

[.instruction]
Assigning a ticket as child ticket:

. Go to *CRM » Ticket system » Open ticket » Tab: Children*.
. Click on the *Ticket search* tab.
. Click on the arrow in the top left corner to open the *Folder* tab.
. Select a folder in the *Folder* tab.
. Select the filters in the *Search* area of the *Tickets* tab.
. Expand the *Search* area to select further filters.
. Click on *Search*. +
→ The tickets are displayed.
. Activate the tickets that you want to assign as child tickets to the main ticket.
. Click on *Add*.

[IMPORTANT]
.Creating child tickets in the *Children* tab
====
Create a child ticket in the *Children* tab of the *CRM » Ticket system » Open ticket » Tab: Children* menu. Click on *New ticket*. Carry out the settings as desired. This new ticket is automatically assigned to the main ticket and can be found in it's *Children* tab.
====

[#4400]
==== Editing a child ticket

As soon as you have assigned tickets as children in the *Ticket search* tab, they are moved to the *Children* tab. The *Children* tab only includes the child tickets of the main ticket. The assignment can be removed in the *Children* tab. Activate the child ticket and click on *Delete*. The child ticket then becomes a normal ticket again and can be found in the *Ticket search* tab.

[#4500]
== Creating a folder

You can create custom folders. You can create your folder structure as needed. Folders are especially useful in grouping together those tickets that were not already grouped together because of their filter parameters, but that you would like to have together for other reasons. You can always rename your customised folders and delete them, if you no longer need them. Only you can see your own custom folders.

[.instruction]
Creating a folder:

. Go to *CRM » Ticket system*.
. Click on *Create a new folder* in the *Folder* tab. +
→ The *Create new folder* window opens.
. Enter the name or the path. Pay attention to the explanations given in the following box.
. *Save* (icon:save[role="green"]) the settings. +
→ The folder that you have just created is listed in the *Folder* tab.

[NOTE]
.Creating main folders and sub-folders
====
If you create a new folder in your ticket system, enter a name for the new folder if you want this folder to be a main folder. Click on an existing folder if you want to create a sub-folder within this existing folder. When creating a sub-folder, enter a slash and the new name behind the name of the main folder. As an alternative, enter the path into the text field, e.g. the name of the main folder and the name of the new folder. +
Example: Frequent buyers/B2B. The sub-folder B2B is created within the main folder Frequent buyers.
====

[#4600]
== Manually moving tickets into folders

You have to manually move tickets into folders. The ticket is available both in the ticket overview and in the selected folder.

[.instruction]
Manually moving tickets into folders:

. Go to *CRM » Ticket system*.
. Open the ticket.
. Select the folder from the *Folder* drop-down list.
. *Save* (icon:save[role="green"]) the settings. +
→ The ticket is also displayed in the folder that you have just created.

[#4700]
== Creating a custom filter

You can create custom filters. Only you can see your own custom filters.

[.instruction]
Creating a custom filter:

. Go to *CRM » Ticket system*.
. Click on *Create a new filter* in the *Folder* tab. +
→ The *Create custom filter* window opens.
. Enter the name for the filter in the *Settings* area.
. Select a symbol from the drop-down list in the *Settings* area.
. Carry out the settings. Pay attention to the information about *filters* given in <<table-search-ticket>> in the <<crm/using-the-ticket-system#3400, Searching for tickets>> chapter.
. *Save* (icon:save[role="green"]) the settings.

[#4800]
== Assigning emails in the ticket system

Emails in the ticket system are assigned to tickets with the help of keywords or text parameters that are automatically recognised by your plentymarkets system. If an email contains a ticket ID, the email is automatically saved as a message within the corresponding ticket. As already explained in the <<crm/using-the-ticket-system#2100, Setting up the email account>> chapter, you should set up a separate email account and email address that are only used for the ticket system.

Note the keywords and alternative spellings that are used for assigning emails to tickets as listed in <<table-assignment-ticket-system>>. Both upper and lower case letters can be used. Check the <<crm/sending-emails#1200, email templates>> that you use in the ticket system. If needed, correct or add the template variables.

[[table-assignment-ticket-system]]
.Assignment parameters and permitted spellings
[cols="1,3"]
|====
|Parameter |Alternative spellings

|*Email address*
|example@mail.de

|*Ticket ID*
|Ticket / ID / Nr / No / nummer / number + digits +
Examples: +
Ticket ID: 123 +
Ticket id 123 +
TicketID #123 +
ID: #123 +
ID 123 +
Permitted symbols: +
Space, Period, Colon, Minus, Equals sign, hash key, round brackets, square brackets

|*Customer data*
|Customer ID or Customer No.: Kunden / Customer + ID / Nr / No / nummer / number + digits +
Customer name: Kunden / Customer + Name + digits +
Examples: +
Customer ID: 123 +
Customer ID 123 +
Customer id 123 +
CustomerID123 +
Customer number 123 +
Permitted symbols: +
Space, Period, Colon, Minus, Equals sign, hash key

|*Order ID*
|Auftrag(s) / Order + ID / Nr / No + digits +
Examples: +
Order ID: 123 +
Order ID 123 +
OrderID123 +
Order id 123 +
Permitted symbols: +
Space, Period, Colon, Minus, Equals sign, hash key

|*Invoice No.*
|Rechnung(s) / invoice + ID / Nr / No / nummer / number + digits +
Examples: +
Invoice ID: 123 +
invoice ID 123 +
Invoice No 123 +
Permitted symbols: +
Space, Period, Colon, Minus, Equals sign, hash key
|====

If you have set up a special email account for the ticket system, your emails are automatically transferred into the ticket system. This is done with the help of the parameters listed in <<table-assignment-ticket-system>>. Tickets are created as follows:

* If an email contains a ticket ID, the email is automatically saved as a message within the ticket.
* If an email contains a customer ID, customer number or customer name, a ticket is automatically created. The customer data is saved in the ticket's *Customer* tab.
* If an email contains an order ID or invoice ID, a ticket is automatically created. The order is saved in the ticket's *Search orders* tab.

[IMPORTANT]
.Only unread messages are synchronised
====
Emails are assigned to tickets whenever the ticket system is synchronised. The email may not have previously been opened or read in the email program. This is because only unread messages are synchronised.
Pay attention to the information about the *Process* setting in table 1 in the <<crm/using-the-ticket-system#2100, Setting up the email account>> chapter.
====

The examples below illustrate different ways that emails are assigned to tickets.

[#4900.subhead]
Assigning by ticket ID

An email contains the keyword *Ticket ID 1* as its subject. The ticket system recognises this keyword. The ticket system would also recognise the keyword if it was located e.g. within the text of the email. +
During the synchronisation process, the email that contains the keyword *Ticket ID 1* is automatically attached as a message to the ticket that has the ID 1.

[#5000.subhead]
Assigning by customer ID

If a customer ID is included in the email, the customer is automatically linked to the ticket when the message is imported. You can tell that this information was linked because an entry was made in the *Customer* field and the *Customer* tab contains data about the customer. Therefore, emails that relate to customers should always include the customer ID or customer number so that this data is available in the ticket immediately.

[#5100.subhead]
Assigning by order ID

If an order ID is the only parameter saved in the email, a new ticket is created and the order that has this ID is loaded in the *Search orders* tab.

[#5200.subhead]
Assigning by invoice number

If an invoice number is specified, the order is searched for and displayed in the ticket's *Search orders* tab.

[IMPORTANT]
.Sender's email address takes priority over the email address saved in the customer data record
====
If an email doesn't contain any of the parameters necessary for assigning it to a ticket, the sender's email address is used when replies are sent.

If an email contains customer parameters (i.e. the ticket was linked to a specific customer) and this customer data includes an email address, the sender's email address is still used when replies are sent. The sender's email address always takes priority.
====

[#5300]
== Creating a ticket card

Go to *System » System settings » CRM » Ticket system » Ticket cards* to create a print template that is used to generate your tickets as PDF files which you can file or print. Setting up ticket cards can basically be compared to the procedure of setting up <<fulfilment/generating-documents#address-label-template, label templates>>.

The number of cards per page changes depending on the size of the page, the number of lines and columns and the size of the cards. Also consider the spacing between the cards when you set up the page.

The parameters, e.g. the ticket ID, are displayed as soon as the values have been entered into the fields *X*, *Y* and *mm*. Optionally, you can enter a field name that is displayed before the value.

In the lines *Message* and *Comment*, you can select whether the oldest or the latest message and the oldest or the latest comment should be displayed on the ticket card.

The priorities start with *0* (= grey star, lowest priority) and go up to *5* (= two yellow stars, highest priority).

[TIP]
.Allow line break for longer lines
====
If several people are owners of the ticket and you want them all displayed on the ticket card, you need to activate the option *Allow line break*. It is also possible to allow line breaks for the setting *Ticket title*.
====

[.instruction]
Creating a ticket card:

. Go to *System » System settings » CRM » Ticket system » Ticket cards*.
. Expand the *New template* area.
. Enter the *name*.
. Enter the width and height of the *Page* and the *Card*.
. Enter the parameters for those elements that are to be displayed on the ticket card.
. *Save* (icon:save[role="green"]) the settings.

[NOTE]
.Generating a preview of the ticket card
====
You can see a preview once you have created the new template. Expand the template. Enter the *Ticket ID* and click on *Preview*.
====

[#5400]
== Exporting tickets in a PDF file

After you saved the <<crm/using-the-ticket-system#5300, ticket card template>> in the *System » System settings » CRM » Ticket system » Ticket cards*, it is available in the *CRM » Ticket system » Tab: Tickets* menu in the drop-down list *Print ticket* of the *Group function*. Proceed as follows to export your tickets in a PDF file.

[.instruction]
Exporting tickets in a PDF file:

. Go to *CRM » Ticket system*.
. In the ticket overview, activate those tickets that you want to export.
. Click on *Group function*. +
→ The *Group function* window opens.
. Activate the setting *Print ticket*.
. Select a template from the drop-down list.
. Enter a *message* or a *comment* as needed. +
​→ This entry is saved for all printed tickets (not displayed on the printed ticket card, but in the ticket in the system).
. Click on *Apply*. +
​→ The PDF file is created.

[#5500]
== Creating tickets in the My account area

Your customers can create tickets in the *My account* area of your online store. They can send messages there and see answers to the ticket. If an event procedure is used to send the customer an email and this email contains the template variable *$TicketURL*, the customer is able to click on this link to directly open up the ticket in *My account* area. He or she is able to answer the message there.

[#5600]
== Creating ticket statistics

Go to *Start » Statistics* to create statistics regarding the tickets in your ticket system. You can choose between the statistic types *Tickets by current status*, *Tickets by system state* or *Tickets by status*.

For further information, refer to the <<basics/statistics#80, Statistics>> page of the manual. How to create statistics is described on the <<basics/statistics#, Statistics>> page of the manual.
