= Feedbacks verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kundenrezension, Kunden-Feedback, Rezension, Feedback
:position: 40

[IMPORTANT]
.Hinweis zur Handbuchseite Feedbacks verwalten
====
Auf dieser Handbuchseite werden alle Einstellungen, die im Menü *CMS » Feedback-Bewertungen* im Terra-Backend über den zentralen Login-Bereich zur Verfügung stehen, beschrieben. Die Handbuchseite <<omni-channel/online-shop/webshop-einrichten/extras/kunden-feedback#, Kunden-Feedback>> und das Kapitel <<omni-channel/online-shop/webshop-einrichten/cms#kunden-feedback, Kunden-Feedback>>, welche die Einstellungen in den Menüs *CMS » Kunden-Feedback* und *System » Mandant » Global » Feedback* beschreiben, stehen parallel zur Verfügung. Wenn das neue Menü *CMS » Feedback-Bewertungen* das alte Menü *CMS » Kunden-Feedback* vollständig ersetzt, wird das Menü *CMS » Kunden-Feedback* abgeschaltet und somit auch die Handbuchseite *Kunden-Feedback* entfernt.
====

link:https://marketplace.plentymarkets.com/plugins/widgets/Feedback_5115[Kunden-Feedback^] ist ein Plugin für den Webshop link:https://marketplace.plentymarkets.com/plugins/templates/Ceres_4697[Ceres^]. Installieren Sie das Plugin *Kunden-Feedback*, um Kundenrezensionen im Webshop anzuzeigen und zu beantworten. Im Menü *CMS » Feedback-Bewertungen* schalten Sie Kundenrezensionen für die Besucher Ihres Webshops frei. Hier beantworten oder bearbeiten Sie Kundenrezensionen. Auch das Migrieren von bestehenden Rezensionen und das Löschen von Kundenrezensionen ist in diesem Menü möglich.

[#100]
== Kundenrezensionen migrieren

Wenn Sie von Ihrem Callisto-Webshop auf den Ceres-Webshop umsteigen, stehen Ihnen die Kundenrezensionen nach einer Migration auch im neuen Webshop zur Verfügung. Gehen Sie wie im Folgenden beschrieben vor, um bestehende Kundenrezensionen zu migrieren.

[#200.instruction]
Bestehende Kundenrezensionen migrieren:

. Öffnen Sie das Menü *CMS » Feedback-Bewertungen*.
. Klicken Sie auf *Bestehende Feedbacks migrieren*. +
→ Die bestehenden Feedbacks werden migriert.

[NOTE]
.Migration bestehender Kundenrezensionen
====
Bei der Migration werden bestehende Kundenrezensionen in die neue Datenbankstruktur überführt. In der neuen Struktur verfügen Rezensionen über maximal 5 Bewertungspunkte. Kundenrezensionen, die bisher eine Bewertungsskala von 10 Punkten hatten, werden bei der Migration auf maximal 5 Punkte umgerechnet:

* 1 bis 2 Sterne werden zu 1 Stern
* 3 bis 4 Sterne werden zu 2 Sternen
* 5 bis 6 Sterne werden zu 3 Sternen
* 7 bis 8 Sterne werden zu 4 Sternen
* 9 bis 10 Sterne werden zu 5 Sternen

====

[#300]
== Kundenrezensionen suchen

In der Ansicht *Filter* haben Sie die Möglichkeit, Kundenrezensionen nach bestimmten Kriterien zu suchen. Die Suchergebnisse werden dann in der Ansicht *Übersicht* angezeigt. In der Übersicht werden aktuell die folgenden Informationen angezeigt: ID, Typ, Referenz-ID, Titel, Autor, Datum, Kommentar, Bewertung, Antworten und Sichtbarkeit. Wie Sie Rezensionen bearbeiten, erfahren Sie unter <<#700, Kundenrezensionen bearbeiten>>.

Um bestimmte Kundenrezensionen zu suchen, geben Sie die Ihnen bekannten IDs in das Suchfeld ein oder wählen Sie die Einstellungen der Dropdown-Listen.

[#400.instruction]
Kundenrezension suchen:

. Öffnen Sie das Menü *CMS » Feedback-Bewertungen*.
. Geben Sie in der Ansicht *Filter* gesuchte IDs in das Suchfeld ein bzw. stellen Sie Filteroptionen in den Dropdown-Listen ein. Beachten Sie dazu die Erläuterungen in <<tabelle-filter-rezensionen>>.
. Klicken Sie auf *Suchen*. +
→ Die Kundenrezensionen, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile der Kundenrezension. +
→ Die Detailansicht der Kundenrezension wird geöffnet.

[[tabelle-filter-rezensionen]]
.Filter für die Rezensionen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Ohne gewählte Filtereinstellungen auf *Suchen* klicken, um alle Kundenrezensionen anzuzeigen. Alternativ die Suchergebnisse durch Filtereinstellungen eingrenzen und auf *Suchen* klicken. Die gefundenen Kundenrezensionen werden in der Übersicht angezeigt.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*Feedback-ID*
|Jede Kundenrezension erhält automatisch eine fortlaufende und einzigartige ID. Die ID entspricht immer einer echten Zahl. Ungültig sind z.B. *00521* oder *ADF8354*.

|*Sichtbarkeit*
|*Alle*, *Ja* oder *Nein* wählen. +
*Alle* = Alle Kundenrezensionen werden in der Übersicht angezeigt. +
*Ja* = Nur Kundenrezensionen, die im Webshop sichtbar sind, werden in der Übersicht angezeigt. +
*Nein* = Nur Kundenrezensionen, die nicht im Webshop sichtbar sind, werden in der Übersicht angezeigt.

|*Von Bewertung; +
Bis Bewertung*
|Bewertungspunkte wählen, um Kundenrezensionen mit dieser Bewertung zu suchen.

|*Von; +
Bis*
|Datum eingeben oder Datum im Kalender wählen, um Kundenrezensionen zu suchen, die in dieser Zeitspanne abgegeben wurden.

|====

[#500]
== Kundenrezensionen freischalten

Wenn Sie die automatische Freischaltung von Kundenrezensionen im Plugin deaktivieren, schalten Sie Kundenrezensionen manuell frei.

[#600.instruction]
Kundenrezensionen manuell freischalten:

. Öffnen Sie das Menü *CMS » Feedback-Bewertungen*.
. Aktivieren Sie eine oder mehrere Kundenrezensionen.
. Klicken Sie auf *Sichtbar*, um die Rezensionen sichtbar zu schalten. +
→ Kundenrezensionen werden in der Einzelansicht eines Artikels angezeigt.

[#700]
== Kundenrezensionen bearbeiten

Sobald Kundenrezensionen in Ihrem Webshop eingehen, werden die Rezensionen im Menü *CMS » Feedback-Bewertungen* gelistet. Hier stellen Sie Kundenrezensionen sichtbar oder unsichtbar und bearbeiten Texte, die beispielsweise nicht Ihrer Netiquette entsprechen. Wenn Sie einen Rezensionstext bearbeiten möchten, gehen Sie wie folgt vor.

[#800.instruction]
Kundenrezensionen bearbeiten:

. Öffnen Sie das Menü *CMS » Feedback-Bewertungen*.
. Klicken Sie auf die gewünschte Kundenrezension. +
→ Die Kundenrezension wird geöffnet.
. Ändern Sie den Titel.
. Ändern Sie den Rezensionstext.
. *Speichern* Sie die Einstellungen. +
→ Die Kundenrezension wird im Webshop aktualisiert.

[#900]
== Kundenrezensionen löschen

Löschen Sie Kundenrezensionen, um diese aus dem Webshop zu entfernen. Alternativ schalten Sie Kundenrezensionen unsichtbar.

[#1000.instruction]
Kundenrezensionen löschen:

. Öffnen Sie das Menü *CMS » Feedback-Bewertungen*.
. Aktivieren Sie eine oder mehrere Kundenrezensionen.
. Klicken Sie auf *Löschen*. +
→ Das Fenster *Feedbacks löschen* wird geöffnet.
. Klicken Sie auf *Ok*, um die Rezensionen zu löschen. +
→ Die Kundenrezensionen werden gelöscht.

[#1100]
== Kundenrezensionen beantworten

Wenn Sie auf eine Kundenrezension antworten möchten, gehen Sie wie folgt vor.

[#1200.instruction]
Kundenrezensionen beantworten:

. Öffnen Sie das Menü *CMS » Feedback-Bewertungen*.
. Klicken Sie auf die gewünschte Kundenrezension. +
→ Die Kundenrezension wird geöffnet.
. Klicken Sie auf *Antworten*. +
→ Das Antwortfeld wird geöffnet.
. Geben Sie eine Antwort ein.
. *Speichern* Sie die Einstellungen. +
→ Die Antwort wird hinzugefügt und im Webshop angezeigt.

[#1300]
=== Antworten anzeigen

Antworten zu Kundenrezensionen zeigen Sie auch in der Detailansicht einer Rezension an.

[#1400.instruction]
Antworten anzeigen:

. Öffnen Sie das Menü *CMS » Feedback-Bewertungen*.
. Klicken Sie auf die gewünschte Kundenrezension. +
→ Die Kundenrezension wird geöffnet.
. Klicken Sie auf *Feedback-Antworten*. +
→ Die Liste mit Antworten wird geöffnet.
. Klicken Sie auf eine Antwort. +
→ Die Antwort wird angezeigt.

[#1500]
=== Antworten bearbeiten

Bearbeiten Sie Antworten auf Kundenrezensionen folgendermaßen.

[#1600.instruction]
Antworten bearbeiten:

. Öffnen Sie das Menü *CMS » Feedback-Bewertungen*.
. Klicken Sie auf die gewünschte Kundenrezension. +
→ Die Kundenrezension wird geöffnet.
. Klicken Sie auf *Feedback-Antworten*. +
→ Die Liste mit Antworten wird geöffnet.
. Klicken Sie auf eine Antwort.
. Bearbeiten Sie den Antworttext.
. *Speichern* Sie die Einstellungen. +
→ Die Antwort wird aktualisiert.

[#1700]
=== Antworten löschen

Schließlich ist es ebenfalls möglich Antworten auf Kundenrezensionen zu löschen.

[#1800.instruction]
Antworten löschen:

. Öffnen Sie das Menü *CMS » Feedback-Bewertungen*.
. Klicken Sie auf die gewünschte Kundenrezension. +
→ Die Kundenrezension wird geöffnet.
. Klicken Sie auf *Antworten anzeigen*. +
→ Die Liste mit Antworten wird geöffnet.
. Klicken Sie auf eine Antwort.
. Klicken Sie auf *Löschen*. +
→ Das Fenster *Antwort löschen* wird geöffnet.
. Klicken Sie auf *Ok*. +
→ Die Antwort wird gelöscht.
