= IO einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, Standard, Ceres, Plugin, IO, io, Routen, Template, Konfiguration
:position: 20
:url: webshop/io-einrichten

Der plentymarkets 7 Webshop ist auf zwei unterschiedliche Plugins aufgeteilt: link:https://marketplace.plentymarkets.com/plugins/templates/Ceres_4697[Ceres^] stellt das Webshop-Design zur Verfügung und kann nach Ihren Bedürfnissen angepasst werden.
Das Plugin link:https://marketplace.plentymarkets.com/plugins/templates/IO_4696[IO^] beinhaltet die PHP-Grundfunktionen des Webshops und stellt die Logik-Grundlage für sämtliche Design-Plugins dar.
Auf dieser Handbuchseite erfahren Sie, wie Sie das Plugin IO einrichten.

[#10]
== IO in plentymarkets einrichten

Um einen Ceres Webshop einzurichten, müssen die Plugins Ceres und IO in einem <<basics/erste-schritte/plugins#20, Plugin-Set>> gespeichert und bereitgestellt werden.
Außerdem muss IO im Menü *Plugins » Plugin Übersicht* über die Funktion *Position festlegen* die höchste Positionsnummer im Plugin-Set zugewiesen werden.

[WARNING]
.Alter Webshop Callisto nicht mehr erreichbar
====
Wenn Sie die Template-Plugins *Ceres* und *IO* in einem Plugin-Set <<basics/erste-schritte/plugins#70, aktivieren>>, ist der alte plentymarkets Webshop Callisto nicht mehr erreichbar, da *Ceres* und *IO* die URL des Webshops übernehmen.
====

Wenn die oben genannten Vorarbeiten geleistet sind, klicken Sie im Menü *Plugins » Plugin Übersicht* auf das Plugin *IO*.

[#20]
== IO-Konfiguration bearbeiten

Die *IO*-Konfiguration ist in die 3 Tabs *Template*, *Zahlenformate* und *Routing* untergliedert.


[[tabelle-IO-Konfiguration]]
.IO-Konfiguration anpassen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Template*

|*Name des verwendeten Template-Plugins*
|Namen des verwendeten Template-Plugins eingeben. In nahezu allen Fällen ist dieser Name *Ceres*. Anwender, die Ceres durch ein komplett eigenes Template-Plugin ersetzen möchten, müssen hier den Namen dieses Templates eingeben, damit IO korrekt mit diesem in Interaktion tritt. Diese Einstellung ist nur für sehr fortgeschrittene Anwedender gedacht. Sollte hier ein anderer Name eingegeben werden, obwohl das *Ceres* Template-Plugin verwendet wird, wird es zu Fehlern im Webshop kommen.

2+|*Zahlenformate*

|*Anzahl der Nachkommastellen*
|Anzahl der Nachkommastellen eingeben. Standardmäßig sind zwei Nachkommastellen eingestellt.

|*Dezimaltrennzeichen*
|Dezimaltrennzeichen eingeben. Standardmäßig ist das Komma als Dezimaltrennzeichen eingestellt.

|*Tausendertrennzeichen*
|Tausendertrennzeichen eingeben. Standardmäßig ist der Punkt als Tausendertrennzeichen eingestellt.

|*Kundenspezifisches Preisformat verwenden*
|Wählen, ob Preise im jeweiligen Preisformat Ihrer Webshop-Besucher angezeigt werden.

2+|*Routing*

|*Routen aktivieren*
|Aktivieren Sie die von Ceres verwendeten Routen. Für die Verwendung von *Ceres* müssen alle Routen aktiviert sein. Für die Verwendung des *Ceres-Checkouts* in Callisto müssen einige Routen deaktiviert werden. Nähere Informationen hierzu finden Sie in unserem <<webshop/best-practices#checkout, Best Practice>>.

|====
