= Automatischer Austausch von Produkt- und Angebotsdaten
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:position: 30
:id: M5YQMBY
:url: maerkte/mediamarkt/automatischer-datenaustausch
:keywords: {market}, Marktplatz, {market}.de, {market} einrichten, {market} Marktplatz, Multi-Channel, Multichannel, Multi-Channel {market}, Multichannel {market}, Multi Channel {market}
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz {market} in deinem plentymarkets System ein.
:marketplace-url: https://marketplace.plentymarkets.com/mediamarkt_6918
:assistant-name: Mediamarkt
:market: Mediamarkt
:category-example: VIDEO CASSETTES

[.previous-next-navigation]
<<maerkte/mediamarkt/mediamarkt-einrichten#, icon:long-arrow-left[] Mediamarkt einrichten>>
<<maerkte/mediamarkt/automatisierte-auftragsabwicklung#, Automatisierte Auftragsabwicklung einrichten icon:long-arrow-right[]>>

'''

Auf dieser Seite lernst du, wie du mit Hilfe eines Assistenten einen Katalog für den Artikelexport erstellst und wie du die Datenfelder im Katalog zuordnest, um deine Produkt- und Angebotsdaten korrekt an den Marktplatz zu übertragen. Anschließend musst du nur noch die Variantenverfügbarkeit einstellen und den Katalogexport aktivieren.

[#allgemeine-informationen]
== Informationen zum automatischen Datenaustausch

Nachdem du das Plugin installiert und eingerichtet hast, stehen die in <<#datenaustausch-{market}>> automatisierten Prozesse bereit:

[#datenaustausch-{market}]
[cols="1,3a"]
.Häufigkeit des Datenaustauschs
|====
|Daten |Intervall

2+| Artikeldaten

| Artikelexport
| Täglich

| Bestandsabgleich
| Alle 15 Minuten

| Preisabgleich
| Alle 15 Minuten

2+| Auftragsdaten

| Auftragsimport
| Alle 15 Minuten

|====

[#artikelexport-katalog]
== Artikelexport einrichten

Artikeldaten werden über Marktplatz-Formate zu {market} übertragen. Kataloge erstellst du im Menü *Daten » Kataloge*. Du arbeitest zum ersten Mal mit den Katalogen? Dann solltest du dich zuerst <<daten/daten-exportieren/kataloge-verwalten#, mit dem Prinzip der Kataloge vertraut machen>>.

Für jede Produktkategorie von {market}, in der du Produkte verkaufen möchtest, erstellst du einen eigenen Katalog. Verknüpfe anschließend im Marktplatz-Format die von {market} vorgegebenen Felder mit den in plentymarkets gespeicherten Artikeldaten. Die Katalog-Vorlagen werden automatisch täglich zu {market} exportiert, wenn du den Katalog aktivierst.

[IMPORTANT]
.Fehler-Log
====
Wenn es beim Export Probleme gibt, findest du die zugehörigen Log-Einträge auf Mirakl und nicht im Log von plentymarkets.
====

[#katalog-im-assistenten]
=== Katalog im Assistenten erstellen

Gehe wie im Folgenden beschrieben vor, um einen Katalog im Assistenten zu erstellen.

:catalogue-assistant-name: {market}-Katalog
:number-of-boxes: Info-Box
:mapping-fields: die
:catalogue-path: pass:quotes[*Einrichtung » Assistenten » Plugins » [Plugin-Set wählen]*]
:catalogue-note: pass:quotes[Achte darauf, eine Kategorie der untersten Ebene zu wählen. Eine bessere Übersicht findest du auf Mirakl im Menü *Mein Konto » Meine Produktdaten-Einstellungen*.]

include::../_textblocks/instructions/catalogue-assistant-config.adoc[]

[#datenfelder-zuordnen]
=== Datenfelder im Katalog zuordnen

Nachdem du einen Katalog erstellt hast, ordnest du die Datenfelder des Marktplatzes den in plentymarkets gespeicherten Artikeldaten zu. Informationen dazu, welche Daten für welches Datenfeld des Marktplatzes übertragen werden müssen, findest du in der Dokumentation des Marktplatzes.

[TIP]
.Eigenschaften verwenden
====
Verwende <<artikel/artikel-verwalten#4800, Eigenschaften>>, um Werte für Marktplatz-Datenfelder zu übergeben, für die es keine Entsprechung in plentymarkets gibt.
====

include::../_textblocks/instructions/katalog-datenfelder-zuordnen.adoc[]

[IMPORTANT]
====
Beim Marktplatz {market} darf folgenden Marktplatz-Datenfeldern kein plentymarkets Datenfeld zugeordnet werden:

* Main Product Image
* Additional Product Image 1
* Additional Product Image 2

Die Warnmeldung beim Speichern der Zuordnung kannst du dabei ignorieren.
====


[[katalog-mirakl-zuordnungen]]
.{market}-Zuordnungen
[cols="1,2a"]
|====
|Marktplatz-Datenfeld |plentymarkets Datenfeld

| *Brand*
a| Erstelle für dieses Marktplatz-Datenfeld eine Eigenschaft vom Typ *Kurztext*. Erstelle einen Eigenschaftswert für alle Einheiten, die du für deine Produkte verwendest. Achte darauf, den Code einzugeben und nicht das Label. +

*_Tipp:_* Alle möglichen Werte findest du in der entsprechenden CSV-Datei. +

*_Hinweis:_* Beachte, dass du für dieses Marktplatz-Datenfeld _keine_ Eigenschaften vom Typ *Mehrfachauswahl* verwenden kannst. Beim Versuch eine Eigenschaft vom Typ *Mehrfachauswahl* im Katalog zuzuordnen, wird dies zu einer Fehlübertragung führen.

| *Title*
a| Ordne für dieses Marktplatz-Datenfeld eines oder mehrere der folgenden plentymarkets Datenfelder zu. Verwende mindestens 20 und maximal 100 Zeichen.

* Name 1

_oder_

* Name 2

_oder_

* Name 3

_oder_

* Eigenschaft

| *SHOP_SKU*
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* SKU

Ordne das folgende plentymarkets Datenfeld als Ausweich-Datenfeld zu:

* Varianten-ID

| *EAN*
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* GTIN 13

| *Seller Product ID*
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* SKU

Ordne das folgende plentymarkets Datenfeld als Ausweich-Datenfeld zu:

* Varianten-ID

| *Weight (according to the manufacturer)**
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* Gewicht Brutto g

_oder_

* Gewicht netto g

| *Width**
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* Breite mm

| *Height**
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* Höhe mm

| *Depth**
a| Ordne für dieses Marktplatz-Datenfeld das folgende plentymarkets Datenfeld zu:

* Länge mm
|====


[#weitere-eigenschaften]
=== Weitere Eigenschaften erstellen

Wenn du für eine oder alle deine Varianten mehrere <<artikel/einstellungen/attribute#, Attribute>> definiert hast, erstelle eine Eigenschaft, die diese Attribute vereint. Unterscheidest du bei einer Variante z.B. sowohl nach Farbe als auch nach Größe, legst du eine Eigenschaft mit der Benennung "Grau XL" an. <<artikel/einstellungen/eigenschaften#1400, Ordne diese Eigenschaften>> den entsprechenden Varianten zu.

Zusätzlich zu den <<maerkte/conrad/erste-schritte#eigenschaften-erstellen, zuvor beschriebenen Eigenschaften>> benötigst du Eigenschaften für alle Datenfelder des Marktplatzes, für die du Daten übergeben möchtest, die es standardmäßig in plentymarkets nicht gibt. Welche Eigenschaften du benötigst, siehst du anhand der Datenfelder im Katalog. Du arbeitest zum ersten Mal mit Eigenschaften? Weitere Informationen findest du auf der Artikel-Handbuchseite zum Thema <<artikel/einstellungen/eigenschaften#500, Eigenschaften>>.

[#varianten-mit-katalog-kategorie-verknüpfen]
== Varianten mit {market} Katalog-Kategorie verknüpfen

Nachdem du mit dem Assistenten *{assistant-name} Catalog* oder manuell ein Marktplatz-Format für {market} erstellt hast, wird in deinem plentymarkets System die Eigenschaft *{market}* erstellt. Für jede Kategorie, die du im ersten Schritt *Einstellungen* des Assistenten wählst, wird die gewählte Kategorie als neuer Auswahlwert zur Eigenschaft *{market} Kategoriegruppe* hinzugefügt. Damit deine Varianten im gewünschten Katalog exportiert werden, müssen sie im *Tab: Eigenschaften* einer Variante mit der Eigenschaft *{market} Kategoriegruppe* verknüpft werden.

[.instruction]
Variante mit Kategorie verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen]*.
. Wechsele in das *Tab: Varianten*.
. Öffne die Variante, die du verknüpfen möchtest.
. Wechsele in das *Tab: Eigenschaften*.
. Wähle im Bereich *Varianteneigenschaften* aus der Dropdown-Liste *Eigenschaften* die Eigenschaft *{market} Kategoriegruppe* und klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird hinzugefügt.
. Wähle für die Eigenschaft *{market} Kategoriegruppe* aus der Dropdown-Liste *Wert* die gewünschte Kategorie. +
→ Die Variante wird im zugehörigen Katalog exportiert. +
*_Beispiel:_* Wählst du den Wert *{category-example}*, wird die Variante im Katalog für die Kategorie *{category-example}* exportiert.
. Wiederhole die Schritte 5 und 6 für alle Kategorien, in denen du die Variante verkaufen willst.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[discrete]
=== Weitere Möglichkeiten zum Verknüpfen

* per Import: Über *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* die Eigenschaft *{assistant-name} Kategoriemapping* aufrufen und auf Werte klicken. Dort sind die Auswahlwert-IDs, die für den Import notwendig sind, zu finden.
* per REST-API: Verwende dazu die REST-Routen aus den Bereichen link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/Property[Property^] und link:https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/Item[Item^], um den Katalog mit der Variante zu verknüpfen. +
*_Hinweis_*: Steht im Assistenten *{assistant-name} Catalog* keine Marktplatzkategorie zur Auswahl, dann ist im Assistenten *{assistant-name}* im Schritt *Authentifizierung* ggf. die falsche API-Umgebung ausgewählt.

[#eigenschaften-mit-varianten-verknuepfen]
==== Eigenschaften mit Varianten verknüpfen und Werte speichern

include::../_textblocks/instructions/properties-link.adoc[]

[#{market}]
== Katalogexport aktivieren

:interval: täglich
:market: {market}

include::../_textblocks/instructions/catalogue-activation.adoc[]

[#marktplatzspezifische-werte]
=== Markplatzspezifische Werte übertragen

Der Marktplatz verlangt für die Übertragung von Produktdaten bei den meisten Attributen spezifische Werte. Diese sind derzeit allerdings noch nicht in dieser Form an der Variante hinterlegt. +
*_Beispiel:_* Für das Attribut *Brand* ist beispielsweise *test* nicht erlaubt. Hier muss der entsprechende Code übergeben werden - in diesem Beispiel *BRAND_12345678*.

Kontaktiere dein:e Ansprechpartner:in bei Mediarmarkt für Informationen zu den gültigen Attributwerten.

=== Gültige Attributwerte zuordnen und übertragen

Hast du - je nach Variante, die übertragen werden soll - unterschiedliche Attributwerte, die gültig sein könnten, stellt sich zunächst die Frage, über welche Vorgehensweise du deine Artikeldaten aktuell hältst.
Verwaltest du deine Artikeldaten manuell, ist eine Eigenschaft vom Typ *Auswahl* empfehlenswert. Hier kannst du für die Auswahl eine Beschreibung hinterlegen. Diese wird dann in der Übersicht der Eigenschaften an der Variante angezeigt.
Wenn der Code der Eigenschaft zugeordnet wurde, kannst du den realen Namen der Variante im Feld *Beschreibung* verwenden. Das bedeutet, über den Katalog wird dann der Code übertragen und dahinter in Klammern der reale Name angezeigt. +

*_Tipp:_* Wenn du für ein Attribut immer nur einen einzigen Wert übertragen möchtest, z.B. als Marke immer *BRAND_12345678*, kannst du die Option *Eigener Wert* im Katalog verwenden.

[discrete]
=== Vorhandene Angebote auf Mediamarkt nicht überschreiben

Wenn du bereits Artikel bei Mediamarkt verkaufst, musst du die Varianten in plentymarkets mit ProductIDs versehen. Dies stellt sicher, dass die vorhandenen Produktdaten nicht überschrieben und nur neue Angebote zu den Produkten erstellt werden. Beim Übertragen von Produktdaten wird also eine ProductID an Mediamarkt übermittelt. Die ProductID ist wichtig, um bei der Übertragung von Angebotsdaten eine Verbindung zwischen Angebot und Produkt herzustellen.

Standardmäßig wird bei der Übertragung eines Produktes, für das noch keine Marktplatz-SKU hinterlegt wurde, automatisch die Varianten-ID als Marktplatz-SKU gespeichert. Später bei der Angebotsübertragung wird der Wert, der als Marktplatz-SKU hinterlegt ist, für *sku* und *product-id* verwendet.

Gib im Katalog eine gültige EAN an und übertrage diese an Mediamarkt.

[#produkt-und-angebotsdaten]
== Produkt- und Angebotsdaten übertragen

Bei {market} erfolgt der Listingprozess in zwei Schritten: Zuerst werden Produkte erstellt und nach Freigabe der Produktdaten vom Marktplatz können Angebote zu den erstellten Produkten aktiviert werden. Beide Exportprozesse, deren Voraussetzungen sowie Übertragungsoptionen werden in den folgenden Unterkapiteln beschrieben.

[#produktdaten-ubertragen]
=== Produktdaten übertragen

In diesem Kapitel erfährst du, wie du Produktdaten an den Marktplatz überträgst und welche Voraussetzungen erfüllt werden müssen. Diese Daten kommen aus dem von dir erstellten Katalog *{assistant-name} Catalog*.

=== Voraussetzungen für die Produktdatenübertragung

* Die Plugins link:{marketplace-url}[{market}^]{nbsp}icon:external-link[] sowie *Mirakl Connector* wurden im Marktplatz gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte {market} und Mirakl aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {assistant-name}* wurde die Grundeinrichtung vorgenommen. Für die Produktübertragung muss die Option *Produkte exportieren* im Schritt Datenaustausch aktiv sein.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* wurden die Auftragsherkünfte *Mirakl* sowie *{assistant-name}* an einem bestehenden Preis aktiviert *_oder_* es wurde ein neuer Verkaufspreis erstellt, bei dem die Auftragsherkünfte *Mirakl* und *{assistant-name}* aktiviert wurden.
* Du hast bereits einen <<daten/daten-exportieren/kataloge-verwalten#, Katalog>> für die Übertragung der Daten erstellt.

=== Werte für die Übertragung an den Marktplatz definieren

Die Werte *product-id* und *sku* werden wie folgt übertragen:

* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, muss mit dem Wert der *product-id* in der Angebotsübertragung übereinstimmen.
* Der Wert, der als Produkt-ID bei der Produktübertragung übertragen wird, wird im Katalog definiert.
* Der Wert, der als Marktplatz-SKU an der Variante hinterlegt wird, wird für die Felder *sku* und *product-id* bei der Angebotsübertragung verwendet.
* Wenn du keinen Wert für die Marktplatz-SKU an einer Variante definiert hast, aber die Marktplatzverfügbarkeiten aktiviert wurden, wird die Variante in der Angebotsübertragung ohne *sku* und *product-id* übertragen.

Daraus ergeben sich die folgenden Zuordnungen für die Produktübertragung:

* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* nur die Varianten-ID zugeordnet. Bei der ersten Produktübertragung von dieser Variante wird automatisch (wenn sonst kein Wert vorher definiert wurde) die Varianten-ID als Marktplatz-SKU an der entsprechenden Variante gespeichert.
* Im Katalog wird den Datenfeldern *Produkt-ID (Artikelnr. des Verkäufers)*, *Seller Product ID* bzw. *Die eindeutige Nummer (ID) des Artikels im System des Sellers* die SKU zugeordnet und die Varianten-ID als Ausweich-Datenfeld definiert. Vor der ersten Produktübertragung der Variante wird die Marktplatz-SKU an der Variante definiert. Nimmst du diese Einstellung nicht vor,  wird die Varianten-ID nach der ersten Produktübertragung automatisch als Marktplatz-SKU an der Variante hinterlegt.


[#angebotsdaten-uebertragen]
=== Angebotsdaten übertragen

In diesem Kapitel erfährst du, wie du Angebotsdaten an den Marktplatz überträgst und welche Voraussetzungen erfüllt werden müssen. Diese Daten kommen aus dem von dir erstellten Assistenten *{assistant-name}*.

=== Voraussetzungen für die Angebotsdatenübertragung

* Die Plugins link:{marketplace-url}[{market}^]{nbsp}icon:external-link[] sowie *Mirakl Connector* wurden im plentyMarketplace gekauft, heruntergeladen und in einem Plugin-Set installiert und bereitgestellt.
* Im Menü *Einrichtung » Aufträge » Auftragsherkunft* wurden die Auftragsherkünfte *{market}* und *Mirakl* aktiviert.
* Im Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen] » {market}* wurde die Grundeinrichtung vorgenommen
** *Bestand synchronisieren* ist im Datenaustausch-Schritt aktiviert, damit die Angebote korrekt übertragen werden.
* Im Menü *Einrichtung » Artikel » Verkaufspreise* sind an einem bestehenden Preis die Auftragsherkünfte *Mirakl* und *{market}* aktiviert *_oder_* ein neuer Verkaufspreis ist erstellt, in dem die Auftragsherkünfte *Mirakl* und *{market}* aktiviert wurden.

Die Angebotsübertragung findet alle 15 Minuten statt. Es werden nur Artikel übertragen, die die folgenden Voraussetzungen erfüllen:

* An der Variante sind die Auftragsherkünfte *Mirakl* und *{market}* aktiviert.
* An der Variante ist ein Preis aktiv, der für *{market}*, *Mirakl* und *WEB-API* aktiviert wurde.
* An dem Artikel (bzw. an der Variante) ist ein Versandprofil aktiv, das für *{market}*, *Mirakl* und *WEB-API* wurde.
* An der Variante ist ein Wert als Marktplatz-SKU für *{market}* hinterlegt.
* An der Variante hat in den letzten 15 Minuten eine Änderung an dem Bestand oder Preis stattgefunden
** Das Setzen eines neuen Zeitstempels über die Gruppenfunktion oder Stapelverarbeitung führt auch zu einer Übertragung der Variante. Somit muss an der Variante die Warenbestandsbeschränkung *Auf Netto-WB* oder *Keine* gewählt sein und die Variante muss positiven Bestand haben.

[discrete]
=== Weitere Datenfelder, die bei der Angebotsübertragung übermittelt werden

* *sku* und *product-id*: Diese Felder werden automatisch mit dem Wert befüllt, der als Marktplatz-SKU an der Variante hinterlegt wurde.
* *price*: Dieses Feld wird automatisch mit dem Wert befüllt, der an der Variante für den am Marktplatz aktivierten Preis definiert wurde. Wurden mehrere Verkaufspreise an der Variante definiert, die ebenfalls für den Marktplatz freigegeben sind, wird der Preis mit der niedrigsten ID exportiert.
* *quantity*: Dieses Feld wird automatisch mit dem Nettobestand oder den summierten Nettobeständen aus den Lagern befüllt, die im Assistent *{assistant-name}* im Schritt *Lagerauswahl* gewählt wurden.
* *min-quantity-alert*: Dieses Feld wird automatisch mit dem Wert *1* übertragen.
* *state*: Dieses Feld wird automatisch mit dem Wert *11* übertragen.
* *available-start-date*: Dieses Feld wird automatisch mit einem Zeitstempel übertragen.
* *price-ranges*: In diesem Feld werden ein oder mehrere <<artikel/einstellungen/preise#100, Verkaufspreise>> übertragen.
* *allow-quote-requests*: Dieses Feld wird automatisch mit dem Wert *false* übertragen.
* *logistic-class*: Dieses Feld wird standardmäßig nicht befüllt. Wenn kein Wert übertragen wird, wird die Variante mit dem kostenlosen Versandprofil *Free Shipping (FS)* verknüpft. Im Assistentenschritt *Zuordnung der Angebots-Eigenschaften* kannst du eine Eigenschaft zuordnen, um pro Variante einen anderen Wert zu übertragen. Die gültigen Versandprofilcodes findest du im Mediamarkt-Backend unter *Platform Settings » Shipping*. Diese Codes werden in Klammern dargestellt.
* *leadtime-to-ship*: Dieses Feld ist ein Pflichtfeld und wird standardmäßig nicht befüllt. Im Assistentenschritt *Zuordnung der Angebots-Eigenschaften* kannst du eine Eigenschaft zuordnen, um pro Variante einen anderen Wert zu übertragen. Hier sind nur ganze Zahlen zwischen 1 und 45 gültig.


[#variantenverfuegbarkeit]
== Variantenverfügbarkeit einstellen

:market-availability: {market}
:option-availability: {market}
:mirakl-variantenverfuegbarkeit-aktivieren:
:mirakl-herkunft:

include::../_textblocks/instructions/variantenverfuegbarkeit.adoc[]

'''

[.previous-next-navigation]
<<maerkte/mediamarkt/mediamarkt-einrichten#, icon:long-arrow-left[] Mediamarkt einrichten>>
<<maerkte/mediamarkt/automatisierte-auftragsabwicklung#, Automatisierte Auftragsabwicklung einrichten icon:long-arrow-right[]>>
