= Erste Schritte
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:position: 10
:id: 3G907O5
:url: maerkte/mediamarkt/erste-schritte
:market: Mediamarkt
:keywords: {market}, Marktplatz, {market}.de, {market} einrichten, {market} Marktplatz, Multi-Channel, Multichannel, Multi-Channel {market}, Multichannel {market}, Multi Channel {market}
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz {market} in deinem plentymarkets System ein.
:marketplace-url: https://marketplace.plentymarkets.com/mediamarkt_6918
:assistant-name: Mediamarkt

[.next-navigation]
<<maerkte/mediamarkt/mediamarkt-einrichten#, Mediamarkt einrichten icon:long-arrow-right[]>>

'''

Auf dieser Seite erfährst du, wie du die Plugins *Mirakl* und *{market}* herunterlädst und installierst. Mirakl ist die Plattform, über die {market} angebunden ist.

[#registrieren]
== Bei {market} registrieren

Du benötigst die Mediamarkt-Zugangsdaten bestehend aus Nutzername und Passwort. Diese Daten erhältst du von Mediamarkt. Hierzu musst du zunächst bei link:https://www.mediamarkt.de/de/about-us/marketplace[Mediamarkt^] ein Mitgliedskonto erstellen.

[#about]
== Über {market}

Über das Mediamarkt-Plugin wird der Marktplatz Mediamarkt mit deinem plentymarkets System verbunden. Durch das Plugin wird der automatische Austausch von Artikel- und Auftragsdaten zwischen plentymarkets und dem Marktplatz Mediamarkt ermöglicht. Dadurch kannst du deine Artikel auf Mediamarkt listen.

Um die Verbindung zu {market} einzurichten, folge der Anleitung auf dieser und den folgenden Seiten.

[#plugins-herunterladen]
== Plugins Mirakl Connector und {market} herunterladen

Die Schnittstelle zu {market} wird über ein Plugin integriert. Um das {market}-Plugin nutzen zu können, lade das Plugin im link:{marketplace-url}[plentyMarketplace^]{nbsp}icon:external-link[] herunter.

Um das {market}-Plugin nutzen zu können, benötigst du außerdem das Plugin *Mirakl Connector*. Du findest Mirakl ebenfalls auf link:https://marketplace.plentymarkets.com/mirakl_6917[plentyMarketplace^]{nbsp}icon:external-link[].

:plugin: Mirakl Connector
[#mirakl-plugin-installieren]
== {plugin} installieren

Installiere das Plugin *{plugin}* wie im Folgenden beschrieben.

include::../../plugins/_textblocks/instructions/plugin-installieren.adoc[]

[#marktplatz-plugin-installieren]
== {market}-Plugin installieren

Gehe wie im Folgenden beschrieben vor, um das Plugin *{market}* zu installieren.

:plugin: {market}
:priority: 1

include::../../plugins/_textblocks/instructions/plugin-installieren.adoc[]

'''

[.next-navigation]
<<maerkte/mediamarkt/mediamarkt-einrichten#, Mediamarkt einrichten icon:long-arrow-right[]>>
