= Manually creating reports for FBA orders and FBA returns
:lang: en
:keywords: Amazon, Items, Export
:position: 50

Sometimes Amazon FBA returns and FBA orders have not been imported or are missing. There are several causes for this issue.

== Instructions on what to do if FBA returns are missing:

1. Log into the link:https://sellercentral.amazon.de/[*Amazon Seller Central for Europe*^] and go to *Reports » Fulfilment by Amazon*.

2. Go to *Customer concessions » Returns*.

3. An FBA returns report can be created here.

[IMPORTANT]
.Note 1:
====
When selecting a time period for the report, always make sure that the date of creation of the FBA return is included.
====

[IMPORTANT]
.Note 2:
====
Make sure to select the shortest possible time period for the creation of this report. If the time period is too long, issues may occur during import (depending on the amount of orders), and in the worst case, the process will crash. In this case, reports cannot be retrieved for another 10 hours.
====

[IMPORTANT]
.Note 3:
====
Make sure that you do not continuously create reports, as only a limited number of reports can be retrieved. Normally, one report should be enough.
====

=== Import in plentymarkets
The order report created here is automatically read once an hour. An option for manual import is not provided here.

== Instructions on what to do if FBA orders are missing:

1. Log into the link:https://sellercentral.amazon.de/[*Amazon Seller Central for Europe*^] and go to *Reports » Fulfilment by Amazon*.

2. Go to *Sales » Amazon Fulfilled Shipments*.

3. An FBA order report can be created here.

[IMPORTANT]
.Note 1:
====
When selecting a time period for the report, always make sure that the date of creation of the FBA order is included.
====

[IMPORTANT]
.Note 2:
====
Make sure to select the shortest possible time period for the creation of this report. If the time period is too long, issues may occur during import (depending on the amount of orders), and in the worst case, the process will crash.
====

[IMPORTANT]
.Note 3:
====
Make sure that you do not continuously create reports, as only a limited number of reports can be retrieved. Normally, one report should be enough.
====

[IMPORTANT]
.Note 4:
====
If the report serves for internal purposes only and should not be retrieved, the report must be flagged as “read”. This is done by the Amazon support, by us, or by your own developer access (external program). You can find information on how to get external access in our forum.
====

=== Import in plentymarkets
The order report created here is automatically read every four hours. An option for manual import is not provided here.
