= External discount websites
:lang: en
include::{includedir}/_header.adoc[]
:description: Take advantage of the possibility to offer coupons for your items on external discount websites, such as Groupon.
:position: 70

Coupons are a popular marketing tool for online stores. Take advantage of the possibility to offer coupons for your items on external discount websites, such as Groupon (www.groupon.com). This page walks you through the steps that are needed to offer coupons on external discount websites.

== Creating a new category

The first step is to create a category for the coupon campaign. To do so, proceed as follows.

[.instruction]
Creating a new category:

. Go to **<<item/managing-categories#, Item » Categories>>**.
. Create a new category of the type **<<item/managing-categories#, Content>>**.
. Click on the **Description 1** tab.
. Select the **Syntax editor** option from the drop-down list to the right.
. The code below is an example for a form. Insert this code into the text field.
. Pay attention to the explanations given in table 1 and customise the example code.
. **Save** the settings.

Below you will find an example code for a form. Customise the example code as described in table 1 before using it productively.

[source,plenty]
----
include::assets/EX-EN-form.html[]

----

To customise the form, edit those sections of the code described in table 1.

[cols="1,3"]
|====
|Code |Explanations

|&lt;input name="BuyParamId" value="xxx" type="hidden"&gt;
|Replace "xxx" with the price ID from the Price tab of the item for which you want to offer coupons on external discount pages.

|&lt;input name="BuyParam$ReferrerId" value="1" type="hidden"&gt;
|Enter your store's referrer ID. The referrer ID is typically 1. This value is entered by default. If your online store has a different referrer ID, replace "1" with that referrer ID.

|&lt;input name="BuyParam$ContentPage" value="xxx" type="hidden"&gt;
|Replace "xxx" with the ID of the category that you insert the example form into.

|&lt;input name="BuyParam$ArticleId" value="xxx" type="hidden"&gt;
|Replace "xxx" with the ID of the item for which you want to offer coupons on external discount pages. +
**Note:** This function does not work for item bundles. Therefore, do not enter any IDs of item bundles.
|====

__Table 1: sections to be replaced in the code example__

== Creating a coupon campaign

Since every coupon belongs to a campaign, you need to create such a campaign now. How to create campaigns is described below.

[.instruction]
Creating a new coupon campaign:

. Go to **<<order-processing/orders/coupons#, Orders » Coupons>>**.
. Create a new **<<order-processing/orders/coupons#, campaign>>**.
. Use the settings described in table 2 when creating this campaign.
. **Save** the settings. +
&amp;rarr; The campaign is created and displayed in the **Campaigns** tab.

[cols="1,3"]
|====
|Option |Necessary settings

|**Concept**
|Drop-down list 1: **Several codes** +
Drop-down list 2: **One redemption per customer**

|**Discount type**
|**Fixed amount**

|**Discount value**
|Enter the discount amount. +
**Tip:** To offer free shipping, select the option **incl. shipping costs** and add the item's shipping costs to the discount value. +
If there are several types of shipping available for the item that you are working with, then add the price of the shipping method that has the highest priority. Customers may incur some additional costs if they select a different shipping method. Alternatively, change the item's shipping settings so that only one shipping method is offered.

|**Items**
|Enter the IDs of the items you want to offer the coupon for.
|====

__Table 2: settings for a campaign on external discount websites__

== Generating coupon codes

Now generate the necessary coupon codes. Coupon codes can be <<order-processing/orders/coupons#10, **generated manually or entered manually**>>.

== Configuring the coupon payment method

You have to configure the payment method for **Coupons** before customers will be able to redeem coupons in your store.

[.instruction]
Configuring the coupon payment method:

. Go to **<<order-processing/payment#, System » Orders » Payment » Payment methods>>**.
. Open the payment method **Coupon**.
. Place a **check mark** next to the option **payment method is active**.
. Select the countries of delivery according to the external discount website that you will offer the coupons on.
. **Save** the settings.

== Sending coupon codes to external discount websites

Now send the coupon codes to the external discount website. Proceed as described below to generate a file that contains the campaign's coupon codes. Give this file to your contact person at the external discount website.

[.instruction]
Sending coupon codes:

. Go to **<<order-processing/orders/coupons#, Orders » Coupons>>**.
. Open the coupon campaign.
. Click on the **Settings** tab.
. Click on the **green arrow** directly below the tab. +
&amp;rarr; A file will be generated which contains all of the codes belonging to this campaign.
. Give this file to your contact person at the external discount website.

== Making category link available

Now make the link to the category available to the external discount website. To do so, proceed as follows.

[.instruction]
Making category link available:

. Go to **Item » Categories**.
. Open the category.
. Click on the **settings** tab.
. Copy the link from the **URL** field.
. Save this link on the external discount website or give this link to your contact person at the discount website. Information regarding the exact procedure for doing so can usually be found on the external discount website.
