= Eigene Cloud Infrastruktur
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Cloud, Own Cloud, Infrastruktur, Cloud Infrastruktur, Version, Versionen, Versionierung, Versionierungsprozess, Versionierung-Prozess, Manueller Versionierungsprozess, Beta, Early, Stable, Hosting
:position: 67
:url: business-entscheidungen/systemadministration/eigene-cloud-infrastruktur
:id: 8NSQ6X6
:author: team-cloud
//zuletzt aktualisiert am 9.12.20

Bei der Bestellung von plentymarkets wählen Händler zwischen verschiedenen Hosting-Optionen:

* Cloud-Hosting mit Server-Standort in Frankfurt oder Irland.
* Hosting mit eigener Cloud-Infrastruktur.

Diese Handbuchseite beschreibt die zweite Option: die eigene Cloud-Infrastruktur.
Diese Option steht lediglich Händlern mit einem <<PLUS-Tarif>> zur Verfügung.
In diesem Szenario haben Händler ihre eigene Cloud mit eigenem DB-Server und Webserver.

[discrete]
[#100]
== Versionierung: Praxisbeispiel

Du kannst beliebig viele plentymarkets Systeme innerhalb deiner eigenen Cloud-Infrastruktur betreiben.
Stell dir zum Beispiel vor, du hast ein Testsystem und ein Produktivsystem:

* Du benutzt das Testsystem, um neue Software-Funktionen frühzeitig auszuprobieren.
Sobald es eine neue Funktion gibt, soll die Änderung in deinem Testsystem erscheinen, damit du sie ausprobieren kannst.
* Du benutzt das Produktivsystem für dein Tagesgeschäft.
Neue Funktionen sollen nicht direkt im Produktivsystem erscheinen, da sie vom Arbeitsalltag ablenken könnten.
Neue Funktionen sollen erst in deinem Produktivsystem erscheinen, nachdem du sie im Testsystem ausprobiert und für gut befunden hast.

Du entscheidest, wann neue Funktionen in jedem deiner System erscheinen.
Sollen neue Veröffentlichungen automatisch integriert werden?
Oder sollen sie erst dann erscheinen, wenn du die Updates manuell einspielst?
Du bist völlig flexibel bei der Konfiguration der Einstellungen.

[discrete]
[#200]
=== Einrichtung

. Öffne das Menü *Einrichtung » Einstellungen » Hosting » Manueller Versionierungsprozess*. +
→ Alle Systeme in deiner eigenen Cloud-Infrastruktur werden angezeigt.
. Klicke in der Zeile *Plenty ID: [Eigene ID und URL]* rechts auf den Pfeil nach unten (icon:chevron-down[role="darkGrey"]). +
→ Die Versionierungs-Einstellungen dieses Systems werden angezeigt.
. Prüfe die Einstellungen und ändere sie bei Bedarf. Beachte <<table-manual-versioning-process>>.

[[table-manual-versioning-process]]
.Versionierungsprozess
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *plentymarkets Version*
|Oben links findest du Informationen zu diesem System.
Du siehst den Namen des Entwicklungsstandes (Beta, Early, Stable) sowie das Datum und die Uhrzeit der aktuell verwendeten Version.

| *Versionen automatisch einspielen*
a|Sollen Updates automatisch oder manuell in dieses System eingespielt werden?
Klicke auf die Umschalttaste unten links, um automatische Updates ein- und auszuschalten.

[cols="1,5a"]
!======

!icon:toggle-on[role="green"]
!Updates werden automatisch ins System eingespielt.
Du musst keine weiteren Einstellungen für dieses System konfigurieren.

*_Praxisbeispiel_*: wähle diese Einstellung z.B. für das Testsystem, in dem du neue Softwarefunktionen ausprobierst.

!icon:toggle-off[role="red"]
!Updates werden manuell ins System eingespielt.
Bevor du den Update-Prozess startest, legst du mit den weiteren Einstellungen fest, _welche Updates_ eingespielt werden sollen.

*_Praxisbeispiel_*: wähle diese Einstellung z.B. für das Produktivsystem, mit dem du dein Tagesgeschäft abwickelst.

!======

| *Version von weiterem System einspielen*
a|Dieser Bereich wird nur angezeigt, wenn du dich für manuelle Updates entschieden hast (icon:toggle-off[role="red"]).

. Wirf einen Blick auf _den mittleren Bereich_.
. Wähle eines deiner Systeme aus der Dropdown-Liste aus.
. Klicke auf *Updateprozess starten*. +
→ Es wird exakt die Version des ausgewählten Systems übernommen.

| *Neuste Version einspielen*
a|Dieser Bereich wird nur angezeigt, wenn du dich für manuelle Updates entschieden hast (icon:toggle-off[role="red"]).

. Wirf einen Blick auf _den Bereich rechts_.
. Klicke auf *Updateprozess starten*. +
→ Es wird die aktuellste Version übernommen.
|====

////
//dieses Kapitel ist noch eine Rohversion. Die Texte müssen alle noch überarbeitet werden, damit das flüssig klingt.
[discrete]
=== Fragen und Antworten

[.collapseBox]
.*Was sind die Vor- und Nachteile von automatischen Updates?*
--

* *_Faktor Zeit_*:
Automatische Updates sparen Zeit.
Manuelle Updates nehmen mehr Zeit in Anspruch, da du sie selbst regelmäßig einspielen musst.

* *_Faktor Veränderung_*:
Hast du die Sorge, dass automatische Updates dein System negativ beeinflussen könnten?
Vielleicht befürchtest du, dass neue Funktionen von deinem Tagesgeschäft ablenken könnten.
Wähle in diesem Fall manuelle Updates und entscheide selbst, wann sich das System ändert.

--

[.collapseBox]
.*Ich bin mit einem Update nicht zufrieden. Was kann ich tun?*
--

Melde das Problem im Forum.
Aktualisiere dein System nicht, bis das Problem behoben wurde.

--

[.collapseBox]
.*Kann ich wieder auf eine ältere Version zurückwechseln?*
--

Man kann nur hoch wechseln. Also man kann nicht runter auf einem älteren System rückgängig wechseln, sondern nur höher auf eine neure Version.
Deswegen die ursprüngliche Idee, dass man ein Testsystem hat. Da probiert man erstmal die Sachen aus und sieht, ob es einem gefällt oder nicht.
Sollte der Nutzer ein Problem mit einem neuen Version feststellen (im Testystem), dann kann er im Forum schreiben und das Problem schildern.
Erst nachdem das Problem behoben wurde und alles läuft wie gewünscht, dann kann man sein produktives System auf die Version setzen.


--

[.collapseBox]
.*Wie lange kann ich neue Updates aufschieben?*
--

Es wird irgendwann ein Fallback geben. Also wenn die Version z.B. inzwischen schon 4 Wochen alt ist. Wir werden nicht jede Version bis in aller Ewigkeit mit uns rum schleppen.
Sondern irgendwann wenn die Version wirklich älter ist, werden wir updaten müssen.
Plan ist, dass der Kunde dann eine Notification kriegt.
Das ist noch nicht eingebaut, aber wird noch umgesetzt.


--

[.collapseBox]
.*Können mein Test- und Produktivsystem unterschiedliche Entwicklungsstände haben (Beta, Early, Stable)?*
--

Ja. Aber wenn dein System z.B. auf stable7 läuft, dann kannst du nicht manuell Updates von beta7 einspielen. Add link to page

*Was sind das für Versionen, die zur Auswahl stehen?*
Gemeint ist eben nicht beta, early, stable. Stattdessen wählt man innerhalb z.B. von stable, eine Version aus.
Das ist sozusagen, eine Unter-Version von stable.
Das ist, wenn man in dem #deploy Chat geht. Wenn da steht, "beta7 baking", "early baking". Das ist jeweils eine eigene Release.
Das ist was gemeint ist.

--

[.collapseBox]
.*Mein System umfasst mehrere Mandanten. Kann ich die Versionierung für jeden Mandanten separat einstellen?*
--

Nein. Add link to page
Man sieht nicht nur das System indem man gerade ist, sondern alle System, die auf der Own-cloud sind. Was man da sieht sind keine Mandanten, das sind Hauptsysteme. Mandante werde hier nicht aufgeführt. Mandanten sind Unter-Dinger von den jeweiligen System hier. Weil du kannst für einen Mandant auch keine eigene Version nehmen. Sondern das nimmt immer die Version vom Hauptshop.

--
