= Aufträge bearbeiten
:lang: de
include::{includedir}/_header.adoc[]
:position: 30

**plentymarkets » Aufträge » Aufträge bearbeiten**

== Inhalt dieses Kapitels

In diesem Kapitel erfahren Sie, wie Sie Ihre Aufträge in plentymarkets verwalten. Dazu gehört das Anlegen eines <<auftragsabwicklung/auftraege/auftraege-bearbeiten/neuer-auftrag#, **Neuen Auftrags**  >>, die <<auftragsabwicklung/auftraege/auftraege-bearbeiten/suche#, **Auftragssuche**  >>, das <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#, **Ändern bestehender Aufträge**  >> und das Anlegen verschiedener Auftragstypen, wie <<auftragsabwicklung/auftraege/auftraege-bearbeiten/gutschrift#, **Gutschriften**  >>.
Im Menü **Aufträge bearbeiten** erwarten Sie in der Übersicht alle Aufträge, die Sie von verschiedensten Marktplätzen und Ihrem Online-Shop generieren. Sie werden hier zentral und in einem einheitlichen Format gesammelt. Daher verläuft für Sie die Bearbeitung der Aufträge verschiedener **Herkünfte** generell gleich. Mit den vielen <<auftragsabwicklung/auftraege/auftraege-bearbeiten/suche#2, **Filtermöglichkeiten** >> können Sie bestimmte Aufträge nach verschiedenen Kriterien suchen und schnell finden. Bereits in der Auftragsübersicht erhalten Sie die wichtigsten Informationen auf einen Blick und können über Icons direkt Aktionen ausführen, z.B. eine Auftragsbestätigung erstellen.

== Auftragsbearbeitung in plentymarkets

Die Bearbeitungsmaske jedes Auftrags umfasst die folgenden Tabs:

* Im Tab <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#3, **Übersicht** >> erhalten Sie alle Informationen im Überblick.
* Im Tab <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#4, **Einstellungen** >> hinterlegen Sie die grundlegenden Einstellungen des Auftrags.
* Im Tab <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#5, **Mail** >> finden Sie die E-Mail-Vorlagen, die Sie für Aufträge sichtbar geschaltet haben.
* Im Tab <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#6, **Zahlung** >> buchen Sie Zahlungen und sehen die Zahlungshistorie zum Auftrag ein.
* Im Tab <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#7, **Belege** >> erzeugen Sie zum Beispiel eine Rechnung zum Auftrag.
* Im Tab <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#8, **Kunde** >> finden Sie Informationen zum Kunden.
* Im Tab <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#9, **Tickets** >> werden Tickets des Kunden angezeigt und können direkt bearbeitet werden.
* Im Tab <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#10, **Aufträge** >> finden Sie andere Aufträge des Kunden.
* Im Tab <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#11, **Waren** >> werden Warenbestandsdaten der Artikel im Auftrag angezeigt.
* Im Tab <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#12, **Nachbestellung** >> können Sie direkt eine Nachbestellung zum Auftrag erzeugen.
* Im Tab <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#13, **Lief** >> erstellen Sie Lieferaufträge.

== Videotutorials

Hier finden Sie Videos zu Themen, die in diesem Handbuchkapitel beschrieben werden.

Eine Einführung zum Menü **Aufträge bearbeiten** erhalten Sie in den folgenden Videotutorials:

[.linkBox]
link:https://www.plentymarkets.eu/a-2516/[Die neue Auftragssuche, window="_blank"]

[.linkBox]
link:https://www.plentymarkets.eu/a-2842/[Auftragsherkünfte, window="_blank"]

[.linkBox]
link:https://www.plentymarkets.eu/a-2947/[Lieferaufträge anlegen, window="_blank"]

== Wichtige Seiten zum Thema direkt aufrufen

* <<auftragsabwicklung/auftraege/auftraege-bearbeiten/suche#, **Auftragssuche**  >>
* <<auftragsabwicklung/auftraege/auftraege-bearbeiten/neuer-auftrag#, **Neuer Auftrag**  >>
* <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#, **Auftrag ändern**  >>
* <<auftragsabwicklung/auftraege/auftraege-bearbeiten/retoure#, **Retoure**  >>
* <<auftragsabwicklung/auftraege/auftraege-bearbeiten/lieferauftrag#, **Lieferauftrag**  >>

