= Aufträge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:position: 20
:keywords: Auftragsabwicklung, Auftrag, Aufträge, Auftragsstatus, Auftragstypen, Lieferauftrag, Lieferaufträge, Auftrag manuell anlegen, Kontaktübersicht, Kundenübersicht, Retoure, Retouren, Gutschrift, Gutschriften, Gewährleistung, Gewährleistungen, Reparatur, Reparaturen, Sammelauftrag, Sammelaufträge, Scheduler, Vorbestellung, Aufträge filtern, Auftrag suchen, Aufträge suchen, Auftragsübersicht, Auftrag bearbeiten, Aufträge bearbeiten,

Aufträge bilden Ihre Verkäufe sowie damit einhergehende und übliche Geschäftsvorfälle ab. Mithilfe von Auftragstypen werden die unterschiedlichen Geschäftsvorfälle kenntlich gemacht. Fortschritte bei der Bearbeitung eines Auftrags werden durch <<auftragsabwicklung/auftraege/auftraege-verwalten#1200, Auftragsstatus>> angezeigt. Welche Möglichkeiten Ihnen Auftragstypen und Auftragsstatus bieten und wie Sie Aufträge sinnvoll abwickeln, erfahren Sie in den folgenden Beschreibungen. Alle Aufträge werden zentral und in einem einheitlichen Format erfasst. Bereits in der <<auftragsabwicklung/auftraege/auftraege-verwalten#1400, Auftragsübersicht>> sehen Sie wichtige Informationen auf einen Blick und können einige Arbeiten direkt ausführen.

[#100]
== Allgemeines zur Auftragsanlage in plentymarkets

In plentymarkets wird ein Auftrag automatisch angelegt, wenn Kunden Bestellungen in Ihrem Webshop tätigen. Unterschiedliche Geschäftsvorfälle wie <<auftragsabwicklung/auftraege/auftraege-verwalten#300, Lieferaufträge>>, <<auftragsabwicklung/auftraege/auftraege-verwalten#400, Retouren>>, <<auftragsabwicklung/auftraege/auftraege-verwalten#500, Gutschriften>>, <<auftragasabwicklung/auftraege/auftraege-verwalten#600, Gewährleistungen>> und <<auftragsabwicklung/auftraege/auftraege-verwalten#700, Reparaturen>> werden mithilfe eigene Aufträge verschiedener Typen abgebildet, die immer mit dem Hauptauftrag verbunden sind. Über die <<auftragsabwicklung/auftraege/auftraege-verwalten#1400, Auftragsübersicht>> lassen sich Aufträge ungeachtet der <<auftragsabwicklung/auftraege/auftragsherkunft#, Auftragsherkunft>> öffnen und bearbeiten. Für viele Auftragstypen, wie zum Beispiel <<auftragsabwicklung/auftraege/auftraege-verwalten#300, Lieferaufträge>>, macht das Einrichten von <<basics/automatisierung/ereignisaktionen#, Ereignisaktionen>> Sinn, um Vorgänge zu automatisieren. Einige Beispiele für die Nutzung von Ereignisaktionen für die Auftragsabwicklung werden in den folgenden Kapiteln erläutert. +
Aufträge, die außerhalb des Webshops bei Ihnen eingehen, legen Sie <<auftragsabwicklung/auftraege/auftraege-verwalten#200, manuell>> im System an. Das ist beispielsweise bei telefonischen oder E-Mail-Bestellungen sowie bei Barverkäufen der Fall.

[NOTE]
.Grundeinstellungen speichern
====
Passen Sie die Einstellungen im Menü *<<auftragsabwicklung/auftraege/grundeinstellungen#, System » Aufträge » Einstellungen>>* an, bevor Sie die ersten Aufträge in Ihrem plentymarkets System abwickeln. *Speichern* Sie die Grundeinstellungen auch dann einmalig ab, auch wenn Sie die voreingestellten Werte nicht verändert haben.
====

[#200]
== Aufträge manuell anlegen

Folgende Möglichkeiten sind verfügbar, um einen Auftrag manuell anzulegen:

* In der *Kontaktübersicht*
* In den *Kundendaten* des Kunden
* In einem bestehenden *Auftrag*
* Über einen *Barverkauf*

Diese verschiedenen Vorgehensweisen werden nachfolgend beschrieben.

[IMPORTANT]
.E-Mail-Versand
====
Bei manuell angelegten Aufträgen wird keine automatische E-Mail, z. B. Auftragsbestätigung, an den Kunden versendet. Grund dafür ist, dass das System nicht wissen kann, wann alle Einstellungen zu diesem Auftrag vorgenommen wurden. Stoßen Sie daher den Versand einer E-Mail-Vorlage manuell im Auftrag und dort im Tab *<<auftragsabwicklung/auftraege/auftraege-verwalten#1550, Mail>>* an.
====

[#210]
=== Auftrag in der Kontaktübersicht anlegen

Im Menü *CRM » Kontakte* steht pro Kontakt die Option *Neuer Auftrag* zur Verfügung. Gehen Sie wie unten beschrieben vor, um einen neuen Auftrag über die Kontaktinformationen anzulegen.

[.instruction]
Neuen Auftrag über die Kontaktübersicht anlegen:

. Öffnen Sie das Menü *CRM » Kontakte*. +
→ Die *Kontaktübersicht* wird angezeigt.
. Klicken Sie auf den Kontakt, für den Sie einen neuen Auftrag anlegen möchten. +
→ Der Datensatz des Kontakts wird geöffnet.
. Wählen Sie aus der Menüleiste links die Option *Neuer Auftrag*, um einen neuen Auftrag für diesen Kontakt anzulegen. +
→ Das Tab *Neuer Auftrag* wird geöffnet.
. Klicken Sie auf *Suchen*, um sich eine Liste aller verfügbaren Artikel anzeigen zu lassen, oder suchen Sie mithilfe der Suchfelder nach der *Artikel-ID* oder weiteren *Artikeldaten*.
. Wählen Sie die Artikel und die entsprechenden Mengen, die Sie zum Auftrag hinzufügen möchten.
. *Speichern* Sie die Einstellungen. +
→ Der Auftrag wird angelegt und in einem neuen Tab geöffnet.

[#220]
=== Auftrag in der Kundenübersicht anlegen

Im Menü *CRM » Kontakte* legen Sie einen neuen Auftrag wie unten beschrieben über die Kundendaten an.

[.instruction]
Neuen Auftrag über die Kundenübersicht anlegen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Neuer Auftrag*. +
→ Das Tab *Neuer Auftrag* wird geöffnet.
. Klicken Sie auf *Suchen*, um sich eine Liste aller verfügbaren Artikel anzeigen zu lassen, oder suchen Sie mithilfe der Suchfelder nach der *Artikel-ID* oder weiteren *Artikeldaten*.
. Wählen Sie die Artikel und die entsprechenden Mengen, die Sie zum Auftrag hinzufügen möchten.
. *Speichern* Sie die Einstellungen. +
→ Der Auftrag wird angelegt und in einem neuen Tab geöffnet.

[#230]
=== Auftrag über einen bestehenden Auftrag anlegen

In einem Auftrag finden Sie das Icon *Neuer Auftrag* im Tab *Übersicht*. Gehen Sie wie unten beschrieben vor, um einen neuen Auftrag über das Tab *Übersicht* eines bestehenden Auftrags anzulegen.

[.instruction]
Neuen Auftrag über bestehenden Auftrag anlegen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die *Auftragsübersicht* wird angezeigt.
. Klicken Sie auf einen Auftrag des Kunden, für den Sie einen neuen Auftrag anlegen möchten. +
→ Der Auftrag wird geöffnet.
. Öffnen Sie das Tab *Übersicht*.
. Öffnen Sie das Tab *Kundendaten* und klicken Sie dort auf *Neuer Auftrag*, um einen Auftrag für diesen Kunden anzulegen. +
→ Das Tab *Neuer Auftrag* wird geöffnet.
. Klicken Sie auf *Suchen*, um sich eine Liste aller verfügbaren Artikel anzeigen zu lassen, oder suchen Sie mithilfe der Suchfelder nach der *Artikel-ID* oder weiteren *Artikeldaten*.
. Wählen Sie die Artikel und die entsprechenden Mengen, die Sie zum Auftrag hinzufügen möchten.
. *Speichern* Sie die Einstellungen. +
→ Der Auftrag wird angelegt und in einem neuen Tab geöffnet.

[#240]
=== Auftrag über Barverkauf anlegen

Im Menü *CRM » Kontakte* haben Sie die Möglichkeit, Barverkäufe ohne Kundenzuordnung direkt über das Kundenprofil *Barverkauf* abzuwickeln. Das Kundenprofil *Barverkauf* ist in Ihrem System standardmäßig eingerichtet.

[WARNING]
.Zahlungsart und Auftragsdokumente bei Barverkäufen
====
Achten Sie darauf, bei der Auftragsanlage über Barverkauf in den *Auftragsdaten* die passende *Zahlungsart* auszuwählen. Zudem findet bei dieser Art der Auftragsanlage keine Zuordnung zu einem in Ihrem System gespeicherten Kunden statt. Generieren Sie deshalb die benötigten *<<auftragsabwicklung/auftraege/auftragsdokumente#, Auftragsdokumente>>* wie die Rechnung direkt während der Abwicklung des Barverkaufs manuell im Tab *Belege* des Auftrags.
====

[.instruction]
Neuen Auftrag für Barverkäufe anlegen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Geben Sie im Suchfeld *ID* die Zahl 100 ein. +
→ Eine Liste der Suchergebnisse wird eingeblendet.
. Wählen Sie *Barverkauf* aus der *Ergebnisliste*. +
→ Das Kundenprofil für Barverkäufe mit der ID *100* wird geöffnet.
. Klicken Sie auf *Neuer Auftrag*, um einen neuen Auftrag für einen Barverkauf anzulegen. +
→ Das Tab *Neuer Auftrag* wird geöffnet.
. Klicken Sie auf *Suchen*, um sich eine Liste aller verfügbaren Artikel anzeigen zu lassen, oder suchen Sie mithilfe der Suchfelder nach der *Artikel-ID* oder weiteren *Artikeldaten*.
. Wählen Sie die Artikel und die entsprechenden Mengen, die Sie zum Auftrag hinzufügen möchten.
. *Speichern* Sie die Einstellungen. +
→ Der Auftrag wird angelegt und in einem neuen Tab geöffnet.

[#300]
== Auftragstyp Lieferauftrag nutzen

Mithilfe des Auftragstyps *Lieferauftrag* werden aus einem Hauptauftrag jeweils Lieferaufträge für die enthaltenen Auftragspositionen generiert, so dass Sie diese einzeln oder in Teilen verschicken können. Sie können somit beispielsweise Artikel, die Sie auf Lager haben, sofort losschicken und Artikel, die Sie erst noch geliefert bekommen, später nachsenden. Führen Sie dies mit unterschiedlichen oder auch nur mit einem Versanddienstleister durch. +

Lieferaufträge können *manuell*, *automatisch* oder per *Ereignisaktion* erstellt werden. +

[IMPORTANT]
.Gemeinsamer Status
====
Der Hauptauftrag folgt immer dem Status des Lieferauftrags mit dem niedrigsten Status.
Wenn z. B. ein Auftrag (in Status *5.0*) zwei Lieferaufträge hat (je in Status *5.0*) und der eine Lieferauftrag wechselt in den Status *6.5* (am Beispiel bedeutet 6.5 "*Beim Logistiker im Versand*"), ändert sich am Status des Hauptauftrages zunächst nichts. Erst wenn der zweite Lieferauftrag in den Status *6.5* wechselt, wird automatisch auch der Status des Hauptauftrages zu *6.5* geändert.
====

[#310]
=== Eigenschaften von Lieferauträgen

Im Allgemeinen besitzen Lieferaufträge folgende Eigenschaften:

* Eine Anpassung der in einem Lieferauftrag enthaltenen Auftragspositionen ist nach Erzeugung *nicht* mehr möglich.
* Der *Preis* und das *Gewicht* eines Artikels werden aus dem Hauptauftrag übernommen.
* *Adressetikett*, *Lieferschein*, *Proformarechung* und *Gelangensbestätigung* können im Tab *Belege* des jeweiligen Lieferauftrags generiert werden.
* Die *Rechnung* und alle weiteren Dokumente werden zentral im Hauptauftrag generiert.
* Die Bestandsreservierung für die in einem Lieferauftrag enthaltene Menge wird beim Anlegen eines Lieferauftrags vom Hauptauftrag auf den Lieferauftrag übertragen.

[#320]
=== Grundeinstellungen für Lieferaufträge vornehmen

[WARNING]
.Lager pro Auftragsposition zuordnen
====
Im Menü *System » Aufträge » Einstellungen* muss zwingend für die *Zuordnung des Lagers* die Option *b) pro Artikelposition kann ein Lager zugeordnet werden* ausgewählt werden.
====

Im Menü *System » Aufträge » Auftragstypen » Lieferauftrag* legen Sie vorab fest, nach welchem Kriterium Aufträge in Lieferaufträge gesplittet werden sollen.

[instruction]
Optionen für das Splitten von Aufträgen in Lieferaufträge wählen:

. Öffnen Sie das Menü *System » Aufträge » Auftragstypen » Lieferauftrag*.
. Nehmen Sie die Einstellungen anhand von <<tabelle-auftragstypen-lieferauftrag-optionen>> vor.
. *Speichern* Sie die Einstellungen.

[[tabelle-auftragstypen-lieferauftrag-optionen]]
.Optionen für das *Splitten von Aufträgen in Lieferaufträge*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Aufträge in Lieferaufträge splitten nach*

|*Aus*
|Es erfolgt *keine Aufsplittung*. +
*_Achtung_*: Wenn Sie diese Option aktivieren, können Lieferaufträge nur noch manuell angelegt werden. Das automatische Generieren sowie die Erstellung von Lieferaufträgen per Ereignisaktion sind bei dieser Auswahl nicht mehr möglich.

|*Lager*
|Die Lieferaufträge werden anhand der verschiedenen *Lager* der Auftragspositionen erstellt.

|*Versandprofil*
|Die Lieferaufträge werden anhand der verschiedenen *Versandprofile* der Auftragspositionen erstellt.

|*Lager und Versandprofil*
|Die Lieferaufträge werden anhand der verschiedenen *Lager und der Versandprofile* der Auftragspositionen erstellt.

|*Lager und Netto-Warenbestand*
|Die Lieferaufträge werden anhand der verschiedenen *Lager und des Netto-Warenbestands* der Auftragspositionen erstellt.
|====

[#330]
=== Lieferaufträge manuell anlegen

Bei Bedarf können Sie Lieferaufträge manuell über den Hauptauftrag anlegen. Bei dieser Methode wählen Sie für jeden Lieferauftrag einzeln die Auftragspositionen und -mengen aus, die im jeweiligen Lieferauftrag beinhaltet sein sollen.

[NOTE]
.Lieferaufträge immer für alle Auftragspositionen anlegen
====
Wir empfehlen, grundsätzlich für *alle* Auftragspositionen Lieferaufträge anzulegen. Verbleiben eine oder mehrere Auftragspositionen ohne Zuordnung zu einem Lieferauftrag im Hauptauftrag, kann es zu Fehlfunktionen kommen.

Zudem darf die Menge, die Sie unter *LiefAufMenge* eintragen nicht größer sein, als die unter *NZMenge* (nicht zugeordnete Menge) angezeigte Menge.
====

[.instruction]
Lieferaufträge manuell anlegen

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag, für den Lieferaufträge angelegt werden sollen.
. Wechseln Sie in das Tab *Lief*.
. Tragen Sie in das Feld *LiefAufMenge* (Menge für den Lieferauftrag), die *Menge* ein, die in den Lieferauftrag überführt werden soll.
. Klicken Sie anschließend auf das *Zahnrad*. +
→ Der Lieferauftrag wird angelegt.
. Wiederholen Sie den Prozess, um weitere Lieferaufträge anzulegen.

[#340]
=== Lieferaufträge automatisch anlegen

[IMPORTANT]
.Bedingung für das automatische Anlegen von Lieferaufträgen
====
Lieferaufträge können nur automatisch erzeugt werden, wenn noch kein Lieferauftrag zu dem Auftrag besteht.
====

Wenn Sie Lieferaufträge automatisch anlegen, greifen die zuvor in <<tabelle-auftragstypen-lieferauftrag-optionen>> beschriebenen Kriterien zum Aufsplitten in Lieferaufträge. Somit müssen die Auftragspostionen und -mengen nicht einzeln ausgewählt werden. Stattdessen überführt das System je nach gewähltem Kriterium alle Auftragspositionen automatisch in Lieferaufträge.

[.instruction]
Lieferaufträge automatisch anlegen

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag, für den Lieferaufträge angelegt werden sollen.
. Wechseln Sie in das Tab *Lief*.
. Klicken Sie auf *Lieferauftrag automatisch anlegen*. +
→ Die Lieferaufträge werden angelegt.

[#350]
=== Lieferaufträge per Ereignisaktion anlegen

Lieferaufträge werden idealerweise über eine Ereignisaktion generiert. Sie als Händler können somit bestimmen, wann und wie die Lieferaufträge zu einem Auftrag generiert werden. Im Folgenden werden drei Beispiele zur Generierung von Lieferaufträgen per Ereignisaktion beschrieben.

Erzeugen Sie folgende neue *Ereignisaktionen* bzw. die von Ihnen benötigten und nehmen Sie darin die nachfolgend beschriebenen Einstellungen vor.

==== Beispiel A: Ereignisaktion "Lieferauftrag generieren bei Auftragseingang"

Wenn Sie möchten, dass schon beim Eingang eines Auftrags die zugehörigen Lieferaufträge generiert werden, nutzen Sie die in <<tabelle-ereignisaktion-lieferauftrag-bei-auftragseingang>> beschriebene Ereignisaktion.

Da diese Ereignisaktion direkt beim Auftragseingang greift, wird der Status des Hauptauftrags nicht beachtet. Somit werden auch Lieferaufträge von Aufträgen in Status *3.0* (oder *1.0* wenn Sie mit Auktionsplattformen wie eBay arbeiten) generiert. Diese nehmen bei der Generierung den Status des Hauptauftrages an.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen eindeutigen Namen für die Ereignisaktion ein.
. Wählen Sie das *Ereignis* gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-auftragseingang>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-auftragseingang>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[tabelle-ereignisaktion-lieferauftrag-bei-auftragseingang]]
.Ereignisaktion "Lieferauftrag generieren bei Auftragseingang" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Neuer Auftrag*
|

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag > Auftragslager*
|*Mehrere Lager pro Auftrag*

|*Aktion*
|*Auftrag > Lieferaufträge generieren*
|

|====

==== Beispiel B: Ereignisaktion "Lieferauftrag generieren bei Wechsel zu Status 5" einrichten

Wenn Sie möchten, dass zu einem Auftrag, der in den Status 5.0 gelangt, die zugehörigen Lieferaufträge generiert werden, nutzen Sie die in <<tabelle-ereignisaktion-lieferauftrag-bei-status-5>> beschriebene Ereignisaktion.

Nach dem Generieren der Lieferaufträge dürfen Sie den Hauptauftrag nicht mehr verändern, damit die Summe der Artikel der Lieferaufträge der des Hauptauftrags entspricht.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen eindeutigen Namen für die Ereignisaktion ein.
. Wählen Sie das *Ereignis* gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-status-5>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-status-5>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[tabelle-ereignisaktion-lieferauftrag-bei-status-5]]
.Ereignisaktion "Lieferauftrag generieren bei Wechsel zu Status 5" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung > Statuswechsel*
|*Freigabe Versand*

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag > Auftragslager*
|*Mehrere Lager pro Auftrag*

|*Aktion*
|*Auftrag > Lieferaufträge generieren*
|

|====

==== Beispiel C: Ereignisaktion "Lieferauftrag generieren bei Rechnungserzeugung"

Wenn Sie möchten, dass zu einem Auftrag bei Erzeugung der Rechnung die Lieferaufträge angelegt werden, nutzen Sie die in <<tabelle-ereignisaktion-lieferauftrag-bei-rechnungserzeugung>> beschriebene Ereignisaktion. +
Somit können Sie am Hauptauftrag solange Änderungen vornehmen, bis Sie ihn durch den Rechnungsdruck zum Versand freigeben. Folgende Einstellungen sind nötig:

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen eindeutigen Namen für die Ereignisaktion ein.
. Wählen Sie das *Ereignis* gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-rechnungserzeugung>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-rechnungserzeugung>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[tabelle-ereignisaktion-lieferauftrag-bei-rechnungserzeugung]]
.Ereignisaktion "Lieferauftrag generieren bei Rechnungserzeugung" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Dokumente > Rechnung generiert*
|

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag > Auftragslager*
|*Mehrere Lager pro Auftrag*

|*Aktion*
|*Auftrag > Lieferaufträge generieren*
|

|====

[#360]
=== Haupt- und Lieferaufträge bearbeiten

[NOTE]
.Berechtigungen zum Öffnen von Hauptaufträgen
====
Um den Hauptauftrag öffnen zu dürfen, müssen variable Benutzer über die *<<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90, Berechtigung>>* für alle Lager der Lieferaufträge eines Hauptauftrags verfügen. Prüfen Sie dazu die Einstellungen im Menü *System » Einstellungen » Benutzer » Konten » Tab: Sichtbarkeiten*.
====

Wenn Sie einen Hauptauftrag löschen möchten, müssen zuerst die Lieferaufträge gelöscht werden. Lieferaufträge können einzeln oder über die Gruppenfunktion in der Auftragssuche gelöscht werden. Erst danach kann der Hauptauftrag gelöscht werden.

Es können weitere Auftragspositionen zum Hauptauftrag hinzugefügt oder daraus gelöscht werden. Allerdings können nur Auftragspositionen, die nicht in Lieferaufträgen enthalten sind, aus dem Hauptauftrag gelöscht werden. Die Menge der Artikel im Hauptauftrag lässt sich erhöhen oder verringern. Löschen sollten Sie jedoch nur *nicht zu Lieferaufträgen zugeordnete Mengen*.

[WARNING]
.Löschen von Positionen in einem Lieferauftrag
====
Technisch möglich ist zwar auch das Löschen von Positionen, die bereits in einem Lieferauftrag enthalten sind. Dies sollten Sie jedoch vermeiden, um Fehlfunktionen zu verhindern.
====

[#400]
== Auftragstyp Retoure nutzen

Der Auftragstyp Retoure bildet den Geschäftsvorfall einer Retoure ab. Sie und Ihre Mitarbeiter können Retouren manuell erfassen. Zusätzlich können Sie auch Ihren Webshop-Kunden erlauben, Retouren über den *Mein Konto* Bereich anzumelden. Das Erfassen einer Retoure bucht die retournierten Artikel noch nicht zurück in den Warenbestand. Sie erfassen also die retournierten Artikel zunächst und entscheiden anschließend, ob die Artikel wieder zum Bestand gebucht werden oder ob weitere Schritte, wie z.B. eine Reparatur, notwendig sind. Die Retoure ist ein untergeordneter Auftragstyp, da Retouren entweder einem Auftrag oder einer Gewährleistung zugeordnet sind.
Bevor Sie Retouren erfassen können, legen Sie Retourengründe und Artikelstatus für retournierte Artikel an.

[NOTE]
.Standardstatus für Retouren ändern
====
Der Standardstatus für Retouren ist Status 9. Jede Retoure, die erfasst wird, erhält automatisch diesen Status. Sie können jedoch jederzeit im Menü *<<auftragsabwicklung/auftraege/grundeinstellungen#, System » Aufträge » Einstellungen>>* einen anderen Status als *Standard-Status Retoure* festlegen.
====

[#410]
=== Retourengründe eintragen

Sie können bis zu 20 Retourengründe eintragen. Beim Erfassen einer Retoure wählen Sie dann für jede Auftragsposition einen Grund.  Anhand von Retourengründen ist später nachvollziehbar, ob ein Artikel besonders häufig wegen des selben Grundes retourniert wurde.

[.instruction]
Retourengründe anlegen:

. Öffnen Sie das Menü *System » Aufträge » Auftragstypen » Retoure*.
. Tragen Sie *Gründe* für Retouren ein.
. *Speichern* Sie die Einstellungen.

Wenn Sie erlauben, dass Kunden im Mein-Konto-Bereich des Webshops *<<omni-channel/online-shop/webshop-einrichten/mein-konto#grundeinstellungen, Retouren selbst anlegen>>* können, stehen die angelegten Retourengründe den Kunden dort zur Wahl. Wenn der Kunde keinen Grund wählt, wird der erste Retourengrund verwendet, da dieser voreingestellt ist.

[#420]
=== Status für retournierte Artikel eintragen

Sie können bis zu 12 Artikelstatus anlegen. Die Status können Sie z.B. nutzen, um einerseits den Zustand der retournierten Artikel anzugeben, aber auch den Fortschritt beim Bearbeiten der retournierten Artikel. Die Status stehen in einer Retoure im Tab *Übersicht* bei den Auftragspositionen zur Wahl. Um je nach Fortschritt der Bearbeitung verschiedene Status zuzuweisen, legen Sie entsprechend Ihrer Anforderungen die benötigten Status an.

[.instruction]
Status für retournierte Artikel eintragen:

. Öffnen Sie das Menü *System » Aufträge » Auftragstypen » Retoure*.
. Tragen Sie die gewünschten *Status* für die Zuordnung zurückgesendeter Artikel ein.
. *Speichern* Sie die Einstellungen.

[#440]
=== Retoure erfassen und bearbeiten

Eine Retoure erfassen Sie manuell, wenn ein Paket bei Ihnen eingegangen ist oder Sie erlauben Ihren registrierten Webshop-Kunden direkt im Kundenkonto des Shops Retouren anzumelden. Nachdem eine Retoure erfasst wurde, werden weitere Bearbeitungsmöglichkeiten sichtbar. So können Sie z.B. den Artikelstatus der retournierten Artikel erst nach dem Erfassen angeben.

==== Retoure erfassen

[.instruction]
Retoure erfassen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag oder die Gewährleistung, für den eine Retoure angelegt werden soll.
. Klicken Sie im Tab *Übersicht* unter *Retoure* auf *anlegen*. +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nehmen Sie die Einstellungen anhand <<tabelle-einstellungen-retoure>> vor.
. *Speichern* Sie die Einstellungen. +
→ Die Retoure wird angelegt und in einem eigenen Tab geöffnet.

[[tabelle-einstellungen-retoure]]
.Optionen beim Erfassen einer Retoure
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Einstellungen*

|*Status*
|Einen Status für die Retoure wählen. Voreingestellt ist der Standardstatus, der im Menü *System » Aufträge » Einstellungen* gespeichert wurde.

|*Eigner*
|Einen Eigner auswählen, der dem Retourenauftrag zugewiesen wird.

|*Paketcode der Retoure*
|Paketcode der Retoure eintragen.

2+|*Artikel*

|*Retourengrund auf alle Artikel übertragen*
|Einen Grund für die Retoure wählen, der für alle Artikel der Retoure gilt. +
Wenn hier ein Grund gewählt wird, hat der gewählte Grund Priorität gegenüber den einzeln wählbaren Gründen auf Artikelpositionsebene.

|*Übernehmen*
|Artikel wählen, die in die Retoure übernommen werden sollen.

|*Menge*
|Artikelmenge eintragen, die in die Retoure übernommen werden soll.

|*Grund der Retoure*
|Individuellen Grund für die Retoure eines Artikels wählen.

|*Artikel*
|Der Artikelname kann hier angepasst werden.
|====

Nachdem eine Retoure erfasst wurde, können Sie den Artikelstatus für retournierte Artikel wählen. Außerdem werden weitere Bearbeitungsmöglichkeiten sichtbar.

[#450]
=== Rücksendeschein erstellen

Einen Rücksendeschein können Sie Ihren Kunden bei Zustellung der Ware im Paket beilegen. In diesem Fall sollte der Rücksendeschein Blankofelder für die Retourengründe enthalten. Sie können Ihren Kunden aber auch erlauben den Rücksendeschein im *Mein Konto* Bereich auszufüllen, auszudrucken und der Retoure beizulegen.
Bevor Rücksendescheine erzeugt werden können, muss die Dokumentenvorlage *Rücksendeschein* im Menü *<<auftragsabwicklung/auftraege/auftragsdokumente#, System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rücksendeschein>>* eingerichtet werden.

[TIP]
.Retourengründe auf der Vorlage einstellen
====
Sie können einen unausgefüllten Rücksendeschein in jedem Paket beilegen, dass Sie versenden. Hierfür generieren Sie den Rücksendeschein direkt im Auftrag, ohne dass es überhaupt eine Retoure geben muss. Die zweite Möglichkeit ist, dass Sie Ihren Webshop-Kunden erlauben Retouren im Mein-Konto-Bereich des Shops anzumelden und hier die Retourengründe anzugeben. Anschließend kann der Kunde den Rücksendeschein ausdrucken und dieser ist bereits befüllt. Egal wie Sie den Rücksendeschein Ihren Kunden zukommen lassen, damit Retourengründe eingetragen werden können, müssen Sie die Spalte Retourengründe unterhalb der Artikelpositionen platzieren.
====

Prüfen Sie die Artikelpositionen der Retoure und ändern Sie bei Bedarf die Optionen, z.B. die Menge eines Artikels, bevor Sie im Tab *Belege* der Retoure einen Rücksendeschein erzeugen.

[.instruction]
Rücksendeschein manuell erstellen:

. Öffnen Sie die Retoure und klicken Sie auf das Tab *Belege*.
. Wählen Sie die Option *Rücksendeschein* aus der Dropdown-Liste *Beleg erstellen*. +
→ Ein Fenster wird geöffnet.
. Nehmen Sie die Einstellungen für den Rücksendeschein vor.
. *Speichern* Sie die Einstellungen, um den Rücksendeschein zu generieren.

[TIP]
.Rücksendeschein automatisch generieren
====
Richten Sie eine Ereignisaktion ein, die den Rücksendeschein automatisch generiert. Wenn Sie hier als Ereignis *Neue Retoure (durch Kunden)* einstellen und nach der Herkunft Webshop filtern, können Sie ausgefüllte Rücksendescheine generieren und müssen diese dann lediglich noch zum Download für den Kunden bereitstellen.
====

[#460]
=== Warenbestand zurückbuchen

Wenn Sie einen Artikel über eine Retoure zurückerhalten, können Sie den Warenbestand ganz oder teilweise zurückbuchen oder auch den gesamten Warenausgang zurücksetzen.

[.instruction]
Warenbestand zurückbuchen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Wählen Sie in den Filtereinstellungen unter *Typ* die Option *Retoure*.
. Klicken Sie auf *Suchen*. +
→ Die Retourenaufträge werden aufgelistet.
. Öffnen Sie die Retoure, für die der Bestand zurückgebucht werden soll.
. Öffnen Sie das Tab *Einstellungen*.
. Klicken Sie bei der Option *Warenbestand* auf *Warenbestand einbuchen*. +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nehmen Sie die Einstellungen anhand <<tabelle-warenbestand-rueckbuchen-retoure>> vor.
. *Speichern* Sie die Einstellungen.

[NOTE]
.Warenbestand zurückbuchen für Retouren von Aufträgen mit Lieferaufträgen
====
Die Vorgehensweise zum Zurückbuchen des Warenbestands ist auch für Retouren zu Aufträgen mit Lieferaufträgen gleich. Dass Lieferaufträge vorhanden sind, wird Ihnen im Bearbeitungsfenster für das Rückbuchen angezeigt.
====

[[tabelle-warenbestand-rueckbuchen-retoure]]
.Optionen für das Rückbuchen des Warenbestands
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Warenausgang komplett zurücksetzen*
|Setzt den Warenausgang vollständig zurück. Auch das Datum des Warenausgangs wird gelöscht.

2+|*Warenbestand zurückbuchen*

|*Komplette Menge wählen*
|Trägt die komplette Menge des Artikels im Auftrag in die Spalte *Rückbuchen* ein.

|*Komplette Menge abwählen*
|Setzt die Artikelmengen in der Spalte *Rückbuchen* auf 0.

|*Rückbuchen*
|Wenn Teilmengen zurückgebucht werden sollen, dann hier die Artikelmengen manuell eintragen.

|*Lager*
|Das Lager wählen, in das die Artikel zurückgebucht werden sollen.

|*Lagerort*
|Den Lagerort wählen, in den die Artikel zurückgebucht werden sollen.

|*Menge im Auftrag*
|Zeigt die Menge der Artikel an, die im Auftrag enthalten sind.

|*Zurückgebucht*
|Zeigt bereits zurückgebuchte Artikelmengen an.

|*Charge*
|Zeigt die Chargennumer des Artikels an.

|*MHD*
|Zeigt das Mindeshaltbarkeitsdaum des Artikels an.

|*ID*
|ID des Artikels.

|*Artikel*
|Name des Artikels.
|====

[NOTE]
.Retouren-Artikel im Zulauf
====
Im Menü *<<warenwirtschaft/nachbestellungen-verwalten/rueckstandsliste-verwalten#400, Waren » Retouren » Zulauf>>* finden Sie eine Übersicht aller durch Retouren im Zulauf befindlichen Artikel.
====

[#500]
== Auftragstyp Gutschrift nutzen

Bei einer Gutschrift bekommen Ihre Endkunden einen Betrag zurückerstattet. Dies kann beispielsweise nach einer <<auftragstyp-retoure-nuten, Retoure>> der Fall sein. Bei der Gutschrift in plentymarkets handelt es sich also nicht um eine Art umgekehrte Rechnung, sondern um eine Rückzahlung. Gutschriftaufträge erzeugen Sie unter *Aufträge » Aufträge bearbeiten* aus einem Auftrag. Eine Gutschrift ist also immer einem Auftrag zugeordnet. Die in einem Gutschriftauftrag erzeugten Gutschriftbelege werden auch in Buchhaltungsexporten, wie dem *DATEV*-Export, berücksichtigt.

[#510]
=== Standardstatus für Gutschriften speichern

Bevor Sie eine Gutschrift anlegen, prüfen Sie den Standard-Status für Gutschriften im Menü *<<auftragsabwicklung/auftraege/grundeinstellungen#, System » Aufträge » Einstellungen>>*. Passen Sie den Standardstatus bei Bedarf an und speichern Sie die Einstellungen.

[#520]
=== Gutschrift anlegen

Eine Gutschrift ist immer mit einem bestehenden Auftrag in Ihrem plentymarkets System verknüpft. Deshalb müssen Sie den gewünschten Auftrag zunächst in der Auftragsübersicht öffnen, bevor eine Gutschrift angelegt werden kann.

[TIP]
.Gutschriften im Hauptauftrag oder im Retourenauftrag anlegen
====
Hat ein Kunde den Auftrag bereits gezahlt, beispielsweise per Vorkasse, und entscheidet sich vor dem Warenausgang gegen den Kauf, empfehlen wir den Auftrag zu stornieren direkt im Hauptauftrag eine Gutschrift über alle Auftragspositionen anzulegen.

Kommt es nach erfolgter Zahlung, Warenausgang und Zustellung der Ware beim Kunden für eine oder alle Auftragspositionen zu einer <<auftragstyp-retoure-nutzen, Retoure>> oder im Folgenden zu einem <<auftragstyp-reparatur-nutzen, Reparaturauftrag>>, legen Sie die Gutschrift direkt im entsprechenden Retouren- oder Reparaturauftrag an.
====

[.instruction]
Auftrag öffnen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag, zu dem eine Gutschrift angelegt werden soll. +
→ Der Auftrag wird in einem eigenen Tab geöffnet.

Durch Wahl der Option *Gutschrift / anlegen* im Tab *Übersicht* des Auftrags wird ein neuer Gutschriftauftrag in plentymarkets erzeugt.

[.instruction]
Gutschriftauftrag anlegen:

. Klicken Sie auf das Tab *Übersicht* des Auftrags, zu dem Sie eine Gutschrift anlegen möchten.
. Klicken Sie auf die Dropdown-Liste *Gutschrift* und dort auf die Einstellung *anlegen*. +
→ Der Gutschriftauftrag wird angelegt und in einem eigenen Tab geöffnet.

Sie können die Optionen der Auftragspositionen, die für den Gutschriftauftrag berücksichtigt werden sollen, im Tab *Bearbeiten* ändern oder nicht benötigte Auftragspositionen *Löschen*. Dabei ist es auch möglich, die *Menge* einer Auftragsposition zu ändern, die in den Gutschriftauftrag übernommen wird. Sie erkennen änderbare Optionen an den Textfeldern, Dropdown-Listen oder Textlinks. Weiterhin finden Sie rechts Icons zu den Bereichen *Warenbestand* und *Nachbestellung anlegen*. Durch Klick auf *Löschen* entfernen Sie die Auftragsposition aus dem Gutschriftauftrag.

Wenn bereits ein Gutschriftauftrag zu einem Auftrag angelegt wurde, erscheint im Tab *Übersicht* des Haupfauftrags rechts der Hinweis *Gutschrift verfügbar*. Zusätzlich können Sie bereits angelegte Gutschriftaufträge im Tab *Übersicht* des Hauptauftrags über die Dropdown-Liste *Gutschrift / suchen* aufrufen.

[#530]
=== Gutschriftbeleg erstellen

[NOTE]
.Dokumentenvorlage erstellen
====
Bevor Gutschriftbelege erzeugt werden können, muss die Dokumentenvorlage *<<auftragsabwicklung/auftraege/auftragsdokumente/gutschriften-erzeugen#, Gutschrift>>* im Menü *<<auftragsabwicklung/auftraege/auftragsdokumente#, Aufträge » Fulfillment>>* eingerichtet werden.
====

Nach dem Anlegen des Gutschriftauftrags muss ein Gutschriftbeleg direkt im Gutschriftauftrag erstellt werden. Bevor Sie den Gutschriftbeleg im Tab *Belege* des Gutschriftauftrags erzeugen, sollten Sie die im Gutschriftauftrag enthaltenen Auftragspositionen prüfen und bei Bedarf ändern.

[.instruction]
Gutschriftbeleg erstellen:

. Öffnen Sie den Gutschriftauftrag, für den ein Gutschriftbeleg erzeugt werden soll.
. Wählen Sie die Option *Gutschrift* aus der Dropdown-Liste unter *Beleg / erstellen*.
. Klicken Sie auf *Beleg erstellen*.
→ Der Gutschriftbeleg wird erzeugt und in einem eigenen Tab geöffnet.

[#540]
=== Gutschriftbeleg korrigieren und stornieren

Nachdem Sie zu einem Gutschriftauftrag den entsprechenden Gutschriftbeleg erzeugt haben, ist der Gutschriftauftrag selbst für die Bearbeitung gesperrt, damit steuerrelevante Daten nicht verändert werden können. Wenn Sie feststellen, dass Korrekturen am Gutschriftauftrag nötig sind, erzeugen Sie einen *Stornobeleg Gutschrift*.

==== Vorlage Stornobeleg Gutschrift einrichten

Richten Sie sich zunächst die Vorlage für das Dokument *Stornobeleg Gutschrift* ein. Der schnellste Weg ist in diesem Fall das Übernehmen der Einstellungen aus der Standard-Dokumentvorlage.  +
Im Folgenden wird daher kurz das Übernehmen der Standard-Dokumentvorlage beschrieben.

[.instruction]
Vorlage einrichten:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Stornobeleg Gutschrift*.
. Wechseln Sie in das Tab *Transfer*.
. Klicken Sie unter *Einstellungen aus Standard-Dokumentenvorlage übernehmen* auf *Übernehmen*.

Da die Einstellungen der Vorlage für Stornobelege mit den Einstellungen der Vorlage für eine Rechnung übereinstimmen, finden Sie nährere Erläuterungen zu den einzelnen Einstellungen auf der Seite *<<auftragsabwicklung/auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnungen erzeugen>>*.

==== Gutschriftauftrag korrigieren

Einen Gutschriftauftrag und den dazugehörigen Gutschriftbeleg korrigieren Sie, indem Sie sie zunächst einen *Stornobeleg Gutschrift* erzeugen. Anschließend kann der Gutschriftauftrag wieder bearbeitet werden, also die Daten korrigert werden, und ein neuer Gutschriftbeleg erzeugt werden.

[NOTE]
.Stornieren eines Gutschriftsbelegs
====
Das Stornieren eines Gutschriftbelegs dient der nachvollziehbaren Korrektur von steuerrelevanten Daten und *nicht* der Stornierung eines Gutschriftenauftrags selbst.
====

[.instruction]
Gutschriftauftrag korrigieren:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag, in dem Sie den Gutschriftbeleg stornieren möchten.
. Wechseln Sie in das Tab *Belege*.
. Wählen Sie aus der Dropdown-Liste *Beleg erstellen* den *Stornobeleg Gutschrift*.  +
→ Ein Fenster mit optionalen Einstellungen wird geöffnet.
. *Speichern* Sie die Einstellungen.  +
→ Der Stornobeleg wird erzeugt und die Auftragseinstellungen des Gutschriftauftrags entsperrt.
. Bearbeiten Sie die Daten, die Sie korrigieren möchten.
. Wechseln Sie wieder in das Tab *Belege*.
. Wählen Sie aus der Dropdown-Liste *Beleg erstellen* das Dokument *Gutschrift*.  +
→ Ein Fenster mit optionalen Einstellungen wird geöffnet.
. *Speichern* Sie die Einstellungen.  +
→ Die Gutschrift wird erzeugt und die Auftragseinstellungen des Gutschriftauftrags erneut gesperrt.

[#550]
=== Rückzahlungen buchen

Nachdem Sie einen Gutschriftbeleg erstellt haben, muss die Rückzahlung des gutgeschriebenen Betrags in Ihrem plentymarkets System gebucht werden. Rückzahlungen über bestimmte Zahlungsarten, die Sie in Ihrem System eingerichtet haben, buchen Sie direkt im Tab *Einstellungen* des Gutschriftauftrags. Die Option *Rückzahlung an Kunden* wird nur bei den Zahlungsarten *PayPal*, *ClickandBuy* und *heidelpay* angezeigt.

[IMPORTANT]
.Bedingung bei PayPal
====
Bei *PayPal* ist es nicht möglich, höhere Beträge einzusetzen als mit der ursprünglichen Paypal-Transaktion bezahlt wurden.
====

[.instruction]
Rückzahlung im Tab *Einstellungen* buchen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Gutschriftauftrag, für den Sie eine Rückzahlung buchen möchten.
. Öffnen Sie das Tab *Einstellungen*.
. Klicken Sie bei der Option *Rückzahlung* auf das *Zahlungs-Icon*.
. Prüfen Sie den *Betrag* der Rückzahlung und passen Sie diesen falls nötig an.
. Klicken Sie auf das *Zahnrad*, um die Rückzahlung zu buchen. +
→ Die Rückzahlung wird gebucht.

Alternativ ist es auch möglich, die Rückzahlung im Tab *Zahlung* des Gutschriftauftrags zu buchen. Im Tab *Zahlung* sehen Sie alle Zahlungen und Teilzahlungen, die zum Auftrag gehören. Das Rückbuchen der Zahlung in diesem Tab ist vor allem notwendig, wenn die Zahlung für den Hauptauftrag nicht über eine in plentymarkets integrierte Zahlungsart getätigt wurde.

[.instruction]
Rückzahlung im Tab *Zahlung* buchen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Gutschriftauftrag, für den Sie eine Rückzahlung buchen möchten.
. Öffnen Sie das Tab *Zahlung*.
. Klicken Sie auf das Icon *Zahlung buchen*.
. Geben Sie den *Betrag* (Soll) sowie falls nötig eine *Währung* und einen *Verwendungszweck* ein.
. Klicken Sie auf *Zahlung buchen*. +
→ Die Rückzahlung wird gebucht und wird im Tab *Zahlung* angezeigt.

[#560]
=== Warenbestand zurückbuchen

Wenn der Warenausgang bereits gebucht wurde und die Waren beispielsweise im Rahmen einer <<auftragsabwicklung/auftraege/auftraege-verwalten#400, Retoure>> wieder in das Lager zurückgebucht werden sollen, wird dies im Tab *Einstellungen* des Gutschriftauftrags vorgenommen.

[.instruction]
Warenbestand zurückbuchen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Gutschriftauftrag, für den der Warenbestand zurückgebucht werden soll.
. Wechseln Sie in das Tab *Einstellungen*.
. Klicken Sie bei der Option *Warenausgang* auf den Link *Warenbestand einbuchen*.
. Wählen Sie im angezeigten Fenster die gewünschte Option gemäß den Erläuterungen in <<tabelle-warenbestand-rueckbuchung>>.
. Klicken Sie auf *Speichern*, um den Vorgang auszuführen.

[[tabelle-warenbestand-rueckbuchung]]
.Optionen zur Rückbuchung des Warenbestandes
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Warenausgang komplett zurücksetzen*
|Setzt den Warenausgang vollständig zurück. Auch das Datum des Warenausgangs im Hauptauftrag wird gelöscht.

|*Warenbestand zurückbuchen*
|Bucht die Artikel vollständig oder teilweise zurück. Bei dieser Option wird der Warenausgang nicht zurückgesetzt.

|*Komplette Menge wählen*
|Trägt die komplette Menge des Artikels im Auftrag in das Feld *Rückbuchen* ein.

|*Komplette Menge abwählen*
|Setzt die Artikelmengen unter *Rückbuchen* auf Null.

|*Rückbuchen*
|Die Artikelmenge(n) eintragen, die zurückgebucht werden soll(en), wenn Teilmengen zurückgebucht werden sollen.

|*Lager*
|Das Lager wählen, in das die Artikel zurückgebucht werden sollen.

|*Lagerort*
|Den Lagerort wählen, in den die Artikel zurückgebucht werden sollen.

|*Menge im Auftrag*
|Zeigt die Menge der Artikel an, die im Auftrag enthalten sind.

|*Zurückgebucht*
|Zeigt bereits zurückgebuchte Artikelmengen an.

|*Charge*
|Zeigt die Chargennummer der Artikel an, die im Auftrag enthalten sind.

|*MHD*
|Zeigt das Mindesthaltbarkeitsdatum der Artikel an, die im Auftrag enthalten sind.

|*ID*
|ID des Artikels

|*Artikel*
|Name des Artikels
|====

[#600]
== Auftragstyp Gewährleistung nutzen

Gewährleistungen sind <<auftragsabwicklung/auftraege/auftraege-verwalten#400, Retouren>> relativ ähnlich, denn in beiden Fällen bekommen Sie Waren eines Auftrags im *Status 7* wieder zurückgesendet. Im Gegensatz zur Retoure erwarten Kunden bei einer Gewährleistung aber entweder eine neue Lieferung oder eine Rückerstattung des Rechnungsbetrags mittels einer <<auftragsabwicklung/auftraege/auftraege-verwalten#500, Gutschrift>>.

[NOTE]
.Garantie vs. Gewährleistung
====
Im Gegensatz zur freiwillig erklärten Garantie handelt es sich bei der Gewährleistung um die *gesetzliche Pflicht* der Händler, Mängel am Artikel, die bereits bei Lieferung bestanden haben, für Käufer kostenlos zu beseitigen. Käufer können die Gewährleistung gerichtlich bis zu 2 Jahre bei beweglichen Artikeln oder 3 Jahre bei unbeweglichen Artikeln geltend machen. Ab 6 Monaten nach Erhalt der Ware muss der Käufer jedoch beweisen, dass die Mängel bereits bei Erhalt der Ware vorhanden war.
====

Wenn ein Gewährleistungsfall vorliegt, entscheiden Sie als Händler, ob Sie dem Käufer die Kosten erstatten, den Artikel reparieren oder den Artikel austauschen. Legen Sie *<<auftragsabwicklung/auftraege/auftraege-verwalten#, Gutschrift>>* im Tab *Übersicht* der Gewährleistung an, wenn Sie dem Käufer die Kosten erstatten wollen. Soll ein Umtausch durchgeführt werden, legen Sie eine *Gewährleistung* an. Ob Sie die *Versandkosten* in einer Gewährleistung übernehmen oder nicht, wählen Sie im Menü *<<auftragsabwicklung/auftraege/grundeinstellungen#, System » Aufträge » Einstellungen>>*.

[TIP]
.Einstellungen einer Gewährleistung
====
Wenn Sie aus einem Auftrag heraus eine Gewährleistung erzeugen, wird automatisch das *Versandprofil* des Auftrags übernommen. Die Einstellungen sind jedoch in der Gewährleistung änderbar. Bei *Lieferaufträgen* wird ebenfalls automatisch das korrekte Lager eingestellt. Die *Zahlungsart* bei Gewährleistungen ist änderbar.
====

[#610]
=== Eine Gewährleistung anlegen

Normalerweise legen Sie eine Gewährleistung in einem bestehenden Retourenauftrag an. Es ist jedoch auch möglich, diese direkt aus dem zugrunde liegenden Hauptauftrag heraus anzulegen.

[TIP]
.Gewährleistung im Haupt- oder Retourenauftrag anlegen
====
Beanstandet ein Käufer die Ware nach Lieferung und Sie entscheiden sich beispielsweise aus Kostengründen gegen die Rücksendung der Ware, legen Sie die Gewährleistung direkt im Hauptauftrag an.

Möchten Sie dagegen erst den Eingang der Retoure abwarten und die Ware prüfen, legen Sie zunächst einen Retourenauftrag an und erstellen Sie im Rahmen der Abwicklung dort eine Gewährleistung.
====

[.instruction]
Eine Gewährleistung anlegen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den gewünschten Haupt- oder Retourenauftrag.
. Klicken Sie im Bereich *Gewährleistung* auf *anlegen*. +
→ Das Bearbeitungsfenster *Gewährleistung zum Auftrag* wird geöffnet.
. Setzten Sie bei den betreffenden Artikeln ein *Häkchen*.
. *Speichern* Sie die Einstellungen. +
→ Die Gewährleistung wird angelegt und in einem eigenen Tab geöffnet.

[#620]
=== Eine Gewährleistung bearbeiten

Gewährleistungsaufträge werden in der Auftragsübersicht angezeigt. Öffnen Sie eine Gewährleistung, um beispielsweise einen zusätzlichen *Preis* einzugeben, wenn Sie dem Käufer einen höherpreisigen Artikel als Ersatz liefern wollen. Falls nötig, können hier auch die Mengen der in der Gewährleistung enthaltenen Auftragspositionen verändert werden. Um eine Gewährleistung zu bearbeiten, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung bearbeiten:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Wählen Sie im Tab *Filter* für den Filter *Typ* die Option *Gewährleistung*.
. Klicken Sie auf *Suchen*. +
→ Es werden nur Gewährleistungen aufgelistet.
. Klicken Sie in die Zeile der Gewährleistung, die Sie bearbeiten möchten. +
→ Die Gewährleistung wird geöffnet und kann über das Tab *Bearbeiten* bearbeitet werden.


[#630]
=== Eine Gewährleistung abschließen

Zum Abschließen einer Gewährleistung müssen Sie, wenn für die Ersatzware ein Aufpreis berechnet wird, zunächst eine Rechnung in der Gewährleistung erzeugen. Falls Sie keine Ersatzware versenden, sondern sich mit dem Käufer auf einen nachträglichen Preisnachlass auf die beanstandete Ware einigen, legen Sie eine Gutschrift im Hauptauftrag an.

Um die Bearbeitung einer Gewährleistung durch einen Umtausch abzuschließen, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung durch Umtausch abschließen:

. Öffnen Sie in der Gewährleistung das Tab *Belege*.
. Wählen Sie *Rechnung* aus der Dropdown-Liste *Beleg erstellen*. +
→ Ein neues Bearbeitungsfenster öffnet sich. +
. Klicken Sie auf *Speichern*.
→ Die Rechnung wird erzeugt und in einem eigenen Tab geöffnet.
. Wechseln Sie in das Tab *Einstellungen*.
. Klicken Sie in der Zeile *Warenausgang* auf das Symbol *Warenausgang buchen*. +
→ Der Warenausgang wird gebucht und der *Status* wechselt automatisch zu *[7] Warenausgang gebucht*.
. Wechseln Sie in das Menü *Aufträge » Aufträge bearbeiten*.
. Setzen Sie den Status der Gewährleistung manuell auf Status *[10] Gewährleistung*.
. *Speichern* Sie die Einstellungen.

[NOTE]
.Zahlungseingang bei Gewährleistungen buchen
====
Grundsätzlich müssen Zahlungen zu Gewährleistungen nur dann gebucht werden, wenn mit dem Käufer ein Aufpreis vereinbart wurde. In diesem Fall buchen Sie den Zahlungseingang nach erfolgter Zahlung des Käufers im Tab *Zahlung* der Gewährleistung.
====

Um die Bearbeitung einer Gewährleistung durch eine Gutschrift an den Käufer abzuschließen, gehen Sie wie im Folgenden beschrieben vor:

[.instruction]
Gewährleistung durch Gutschrift abschließen:

. Öffnen Sie den Haupt- oder Retourenauftrag zur Gewährleistung, für die Sie eine Gutschrift anlegen möchten.
. Öffnen Sie das Tab *Übersicht*
. Klicken Sie auf die Dropdown-Liste *Gutschrift* und dort auf die Einstellung *anlegen*. +
→ Der Gutschriftauftrag wird angelegt und in einem eigenen Tab geöffnet.

Der weitere Bearbeitungsprozess läuft identisch mit dem regulären Anlegen einer Gutschrift und dem Erzeugen eines Gutschriftbelegs ab und wird im Kapitel <<auftragsabwicklung/auftraege/auftraege-verwalten#500, Auftragstyp Gutschrift nutzen>> detailliert beschrieben.

[#700]
== Auftragstyp Reparatur nutzen

Reparaturen werden in plentymarkets durch einen eigenen Auftragstyp abgebildet. Reparaturen bestehen aus retournierter, reparaturbedürftiger Ware. Reparaturaufträge können daher nur aus <<auftragsabwicklung/auftraege/auftraege-verwalten#400, Retourenaufträgen>> angelegt werden.

[#710]
=== Status für Reparaturen anlegen

Hinterlegen Sie vor dem Anlegen von Reparaturen verschiedene *Status* für die einzelnen Stationen des Reparaturvorgangs, um den Reparaturverlauf in Ihrem plentymarkets System genau nachvollziehen zu können.

[.instruction]
Status für Reparaturen hinterlegen:

. Öffnen Sie das Menü *System » Aufträge » Auftragstypen » Reparatur*. +
. Tragen Sie die von Ihnen benötigten *Status* für Reparaturen ein. +
. *Speichern* Sie die Einstellungen.

[#720]
=== Zustände für Reparaturen anlegen

Mit einem *Zustand* können Sie den Artikel genau beschreiben, z.B. ob dieser überhaupt eine Reparatur benötigt oder auch, dass es nicht möglich ist, diesen zu reparieren.

[.instruction]
Zustände für Reparaturen anlegen:

. Öffnen Sie das Menü *System » Aufträge » Auftragstypen » Reparatur*.
. Tragen Sie die von Ihnen benötigten *Zustände* für die Zuordnung der Artikelpositionen ein. +
. *Speichern* Sie die Einstellungen.

[#730]
=== Reparatur anlegen

Um eine Reparatur anzulegen, gehen Sie wie nachfolgend beschrieben vor.

[.instruction]
Reparatur anlegen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie die Retoure, zu der Sie eine Reparatur anlegen möchten.
. Öffnen Sie das Tab *Übersicht*
. Klicken Sie auf die Dropdown-Liste *Reparatur* und dort auf die Einstellung *anlegen*. +
→ Ein Bearbeitungsfenster öffnet sich. Geben Sie den gewünschten *Status* und den *Zustand* der Reparatur an. Wählen Sie die zu reparierenden *Artikel* aus. Geben Sie optional einen *Hinweis* ein.
. *Speichern* Sie die Einstellungen. +
→ Die Reparatur wird angelegt und in einem eigenen Tab geöffnet.

[#740]
=== Reparatur bearbeiten

Je nach Grund der Rücksendung oder Zustand der zu reparierenden Artikel müssen bei der Bearbeitung verschiedene Schritte durchgeführt werden. +
Da es sich bei einer Reparatur um einen eigenen Auftragstyp handelt, können Sie direkt im Tab *Übersicht* der Reparatur nach den bereits beschriebenen Vorgehensweisen entweder eine Gutschrift, eine Gewährleistung oder eine Retoure anlegen. Die jeweils nötigen Schritte wie die Dokumentenerzeugung, Buchungen des Warenausgangs oder -eingangs oder der eventuellen Buchung von Zahlungen laufen jeweils identisch mit den Auftragstypen <<auftragsabwicklung/auftraege/auftraege-verwalten#500, Gutschrift>>, <<auftragsabwicklung/auftraege/auftraege-verwalten#600, Gewährleistung>> und <<auftragsabwicklung/auftraege/auftraege-verwalten#400, Retoure>> ab,

[#800]
== Auftragstyp Sammelauftrag nutzen

Unbezahlte Aufträge können in einem Sammelauftrag zusammengefasst werden. Sie können in Menü *Aufträge » Aufträge bearbeiten* oder im Tab *Aufträge* eines Kontakts mit dem Suchfilter *Auftragsstatus*, z.B. anhand eines Status im Bereich *[3] Warten auf Zahlung*, nach solchen Aufträgen suchen. Somit haben Sie zwei Möglichkeiten, Sammelaufträge zu erzeugen, die nachfolgend beschrieben werden.
Für beide Möglichkeiten übernehmen Sie im Menü *Aufträge » Sammelaufträge* noch nicht bezahlte Aufträge in einen Sammelauftrag. Im Tab *Belege* des Sammelauftrags ist dann die Erzeugung von Sammelrechnungen möglich.

[#810]
=== Grundeinstellungen für Sammelaufträge vornehmen

Im Menü *System » Aufträge » Auftragstypen » Multi-Order* nehmen Sie die Grundeinstellungen für Sammelaufträge vor. Hier legen Sie beispielsweise fest, für welche Auftragstypen und Auftragsstatus Sammelaufträge angelegt werden können.

[.instruction]
Grundeinstellungen für Sammelaufträge vornehmen:

. Öffnen Sie das Menü *System » Aufträge » Auftragstypen » Multi-Order*.
. Nehmen Sie die Einstellungen gemäß <<tabelle-sammelauftrag-optionen>> vor.
. *Speichern* Sie die Einstellungen.

[[tabelle-sammelauftrag-optionen]]
.Grundeinstellungen für Sammelaufträge
[cols="1,3"]
|====
|Einstellung
|Erläuterung

|*Auftragstypen*
|Die Auftragstypen wählen, die für Sammelaufträge verwendbar sein sollen. Eine Mehrfachauswahl ist möglich. Nur die aufgeführten Auftragstypen *Auftrag*, *Gewährleistung* und *Reparatur* sind als Sammelaufträge umsetzbar.

|*Artikeltext*
|Die Optionen für die Spalte *Artikeltext* der Artikelpositionen eines Sammelauftrags wählen. Eine Mehrfachauswahl ist möglich. Die gewählten Optionen werden für jeden Einzelauftrag separat im Sammelauftrag aufgelistet und ermöglichen eine Zuordnung zum Kunden und zum Einzelauftrag.

|*Auftragssortierung*
|Wählen, wie die einzelnen Aufträge im Sammelauftrag sortiert sein sollen. Nur eine Auswahl ist möglich. Die Aufträge sind anhand der der Auftrags-ID (*Order ID aufsteigend* oder *Order ID absteigend*) oder dem Zeitpunkt des Warenausgangs (*Warenausgang aufsteigend* oder *Warenausgang absteigend*) sortierbar.

|*Auftragsstatus Aufträge*
|Wählen, in welchem Status sich Aufträge befinden müssen, um für Sammelaufträge berücksichtigt zu werden. Eine Mehrfachauswahl ist möglich. Um gezielt nur Aufträge zu erfassen, die für Sammelaufträge vorgesehen sind, empfehlen wir, je nach Anwendungsfall einen eigenen Auftragsstatus anzulegen.

|*Auftragsstatus Gutschriften*
|Wählen, in welchem Status sich <<auftragsabwicklung/auftraege/auftraege-verwalten#500, Gutschriftaufträge>> befinden müssen, um für Sammelgutschriften berücksichtigt zu werden. Eine Mehrfachauswahl ist möglich.
|====

Weiterhin legen Sie im Menü *<<auftragsabwicklung/auftraege/grundeinstellungen#, System » Aufträge » Einstellungen>>* mit der Option *Standard-Status Sammelauftrag* fest, welchen Auftragsstatus ein Sammelauftrag beim Anlegen erhalten soll. Standardmäßig steht dafür der Status *[13] Sammelauftrag* zur Verfügung. Wählen Sie zudem mit der Option *Standard-Status Sammelgutschrift* einen Status für Sammelgutschriften aus. Standardmäßig steht dafür der Status *[14] Sammelgutschrift* zur Verfügung.

[#820]
=== Sammelauftrag pro Kundenklasse anlegen

Ein Unternehmen möchte für die Mitarbeiter monatlich die anfallenden Rechnungen in Ihrem Webshop bezahlen. Richten Sie dafür eine eigene Kundenklasse ein. Mit der Kunden-ID in der vorgesehenen Kundenklasse wird der Rechnungsempfänger bestimmt. Dieser Rechnungsempfänger erhält dann die Sammelrechnung, die direkt aus dem Sammelauftrag heraus erzeugt wird. +

Einen Sammelauftrag für eine bestimmte Kundenklasse sowie einen Zeitraum legen Sie im Menü *Aufträge » Sammelaufträge* an. Alle unbezahlten Aufträge der Kundenklasse werden somit gesammelt in einem Sammelauftrag abgelegt. Hinterlegen Sie in den Einstellungen der Kundenklassen anhand der Option *Kunden-ID*, welcher Kunde für die Kundenklasse als Eigner des Sammelauftrags sowie als Empfänger der Sammelrechnung aufgeführt werden soll. Je nach Anforderung empfiehlt es sich, eigene <<crm/kontakte-verwalten#15, Kundenklassen>> für Sammelaufträge anzulegen.

[.instruction]
Sammelauftrag für eine Kundenklasse anlegen:

. Öffnen Sie das Menü *Aufträge » Sammelaufträge*.
. Öffnen Sie das Untermenü *Sammelaufträge generieren*.
. Wählen Sie die *Kundenklasse* und optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Auftragseingangs.
. Klicken Sie auf das *Zahnrad*. +
→ Der Sammelauftrag wird angelegt.

[#830]
=== Sammelauftrag pro Kontakt anlegen

Ein Kunde möchte nicht jede Rechnung einzeln bezahlen, sondern pro Monat oder pro Quartal bezahlen. +
In diesem Fall legen Sie einen Sammelauftrag für einen bestimmten Kontakt direkt im Kontaktdatensatz im Menü *CRM » Kontakte* an. Öffnen Sie dazu einen Kontakt und wählen Sie links im Menü die Option *Neuer Sammelauftrag*. Anschließend wird automatisch ein Sammelauftrag generiert, der alle unbezahlten Aufträge des Kontakts enthält.

[TIP]
.Aufträge prüfen
====
Um sicher zu gehen, dass geeignete Aufträge für die Erzeugung eines Sammelauftrags vorhanden sind, suchen Sie im Tab *Aufträge* des Kunden nach unbezahlten Aufträgen.
====

[#840]
=== Sammelrechnung generieren

In diesem Kapitel erfahren Sie, wie Sie Sammelrechnungen erstellen. Die Erstellung von Sammelrechnungen ist nur in den dazugehörigen Sammelaufträgen möglich. +
Richten Sie zuerst eine Dokumentenvorlage für Sammelrechnungen im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Sammelrechnung* ein. In diesem Menü können Sie das Dokument detailliert einstellen sowie eine <<auftragsabwicklung/auftraege/auftragsdokumente#, Dokumentenvorlage>> in Form einer PDF-Datei hinterlegen. In der Grundeinstellung der Vorlage sind bereits Standardwerte hinterlegt, die Sie bei Bedarf durch Kopie aus einer anderen Vorlage, z.B. der Dokumentenvorlage *Rechnung*, mit geringem Aufwand weiter vervollständigen können. Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/auftragsdokumente#, Auftragsdokumente>>. +
Anschließend können Sie im Tab *Belege* des Sammelauftrags eine Sammelrechnung generieren.

[IMPORTANT]
.Zahlungseingänge bei Sammelaufträgen
====
Wird eine Sammelrechnung von einem Kunden bezahlt und der Sammelauftrag als bezahlt markiert, werden die Zahlungseingänge *nicht* automatisch an den einzelnen im Sammelauftrag zusammengefassten Aufträgen gebucht. Zahlungseingänge müssen Sie also an den einzelnen Aufträgen manuell buchen.
====

Mithilfe der in plentymarkets verfügbaren Ereignisaktionen können Sie die Sammelrechnung automatisiert generieren, sobald ein Sammelauftrag angelegt wird. Gehen Sie dazu wie nachfolgend beschrieben vor:

[.instruction]
Ereignisaktion für Sammelrechnungen erstellen:

. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie links unten auf das *grüne Plus*, um eine neue Ereignisaktion zu erstellen.
. Tragen Sie im Bearbeitungsfenster einen Namen ein, z.B. *Sammelrechnungen erstellen*.
. Wählen Sie unter *Ereignis* die Option *Auftragsanlage &gt; Neuer Sammelauftrag*.
. Klicken Sie auf *Speichern*. +
→ Die Ereignisaktion wird angelegt.
. Fügen Sie mit dem grünen Plus eine Aktion des Aktionstyps *Dokumente &gt; Sammelrechnung erzeugen* hinzu. In der Aktion haben Sie die Möglichkeit, ein Zahlungsziel und eine Skonto-Option einzustellen.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen eindeutigen Namen für die Ereignisaktion ein.
. Wählen Sie das *Ereignis* gemäß <<tabelle-ereignisaktion-sammelrechnung-automatisch>>.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß <<tabelle-ereignisaktion-sammelrechnung-automatisch>> vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[tabelle-ereignisaktion-sammelrechnung-automatisch]]
.Ereignisaktion "Sammelrechnung automatisch generieren"
[cols="1,3"]
|====
|Einstellung |Auswahl

|*Ereignis*

|*Auftragsanlage > Neuer Sammelauftrag*

|*Aktion*

|*Dokumente > Sammelrechnung erzeugen* +

*_Hinweis_*: Innerhalb der Aktion haben Sie die Möglichkeit, ein *Zahlungsziel* und ein *Skonto* einzustellen.
|====

[#845]
=== Mahnung für Sammelauftrag generieren

Mahnungen für Sammelaufträge generieren Sie genau wie Rechnungen im Tab *Belege* des Sammelauftrags. Gehen Sie wie folgt vor:

[.instruction]
Mahnung für Sammelauftrag generieren:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Sammelauftrag, für den eine Mahnung erzeugt werden soll.
. Öffnen Sie das Tab *Belege*.
. Wählen Sie die Option *Mahnung* aus der Dropdown-Liste unter *Beleg erstellen*.
. Klicken Sie auf *Beleg erstellen*. +
→ Die Mahnung wird erzeugt und in einem eigenen Tab geöffnet.

[#850]
=== Sammelgutschrift generieren

Eine Sammelgutschrift erzeugen Sie im Menü *Aufträge » Sammelaufträge*. +
Alle Gutschriften der Kundenklasse werden gesammelt in einer Sammelgutschrift abgelegt. Je nach Anwendungsfall empfehlen wir, eigene <<crm/kontakte-verwalten#15, Kundenklassen>> für Sammelgutschriften anzulegen.

[.instruction]
Sammelgutschrift für eine Kundenklasse generieren:

. Öffnen Sie das Menü *Aufträge » Sammelaufträge*.
. Öffnen Sie das Untermenü *Sammelgutschriften generieren*.
. Wählen Sie die *Kundenklasse* und optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Gutschrifteingangs.
. Klicken Sie auf das *Zahnrad*. +
→ Die Sammelgutschrift wird angelegt.

[#900]
== Auftragstyp Scheduler nutzen

Der Scheduler ist ein Abonnement-Modul (Abo-Aufträge), das Ihren Kunden erlaubt, bestimmte Artikel in Ihrem Webshop im Abonnement zu kaufen. Das Modul ist eine <<basics/arbeiten-mit-plentymarkets/plentymarkets-konto#vertrag, zusätzliche Erweiterung>> und nur in Ihrem plentymarkets System sichtbar, wenn Sie es gebucht haben. Die Buchung erfolgt im Menü *Start » Service-Center » Tab: Vertrag*.

Im Menü *System » Aufträge » Scheduler* konfigurieren Sie das Abo-Modul für Ihren Webshop. Nachdem Sie das Modul konfiguriert haben, finden Sie eine Übersicht Ihrer Abonnements im Menü <<auftragsabwicklung/auftraege/scheduler#scheduler-auftraege, Aufträge » Scheduler-Aufträge>>.

[IMPORTANT]
.Nicht für Artikel mit Bestellmerkmalen
====
Das Abo-Modul funktioniert nicht bei Artikeln mit <<artikel/artikel-verwalten#480, Bestellmerkmalen>>.
====

[#910]
=== Grundlegende Einstellungen vornehmen

Legen Sie im Menü *System » Aufträge » Scheduler* fest, welche grundlegenden Einstellungen für das Modul gelten sollen:

[.instruction]
Grundlegende Einstellungen vornehmen:

. Öffnen Sie das Menü *System » Aufträge » Scheduler*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-grundlegende-einstellungen-abo-modul>>.
. *Speichern* Sie die Einstellung.

[[tabelle-grundlegende-einstellungen-abo-modul]]
.Erläuterungen zu den Einstellungen des Abo-Moduls
[cols="1,3"]
|====
|Einstellung
|Erläuterung

|*Intervalle*
| Intervalle für die Abo-Funktion wählen. Mit Strg+C bzw. cmd+C ist Mehrfachauswahl möglich. Die hier gewählten Intervalle stehen Kunden beim Artikel im Webshop zur Auswahl zur Verfügung. So kann der Kunde bei der Bestellung wählen, in welchen Zeitabständen er den Artikel erhalten möchte. Damit die Optionen im Webshop angezeigt werden, muss eine Template-Variable eingefügt werden. Weitere Informationen dazu finden Sie im Kapitel *<<auftragsabwicklung/auftrage/scheduler#, Template-Variablen in das Webshop-Layout einfügen>>*.

|*Anzahl der Aufträge*
|Gibt an, wie oft das Abonnement abgewickelt werden soll. Die Optionen wählen, die Kunden zur Auswahl zur Verfügung stehen sollen. Mit Strg+C bzw. cmd+C ist Mehrfachauswahl möglich. Die hier gewählten Werte stehen Kunden beim Artikel im Webshop zur Auswahl zur Verfügung. So kann der Kunde bei der Bestellung wählen, wie oft er den abonnierten Artikel erhalten möchte. Damit die Optionen im Webshop angezeigt werden, muss eine enstprechende Template-Variable eingefügt werden. Weitere Informationen dazu finden Sie im Kapitel *<<auftragsabwicklung/auftraege/scheduler#500, Template-Variablen in das Webshop-Layout einfügen>>*.

|*Erlaubte Zahlungsarten*
| Zahlungsarten wählen, die für die Abo-Funktion zur Verfügung stehen sollen. Mit Strg+C bzw. cmd+C ist Mehrfachauswahl möglich.

|*Änderungen an Artikeln*
|Wählen, ob Änderungen der Bestelloptionen, z.B. die Menge, im Bestellvorgang erlaubt sein sollen.

|*Artikelfaktor pro Intervall*
|Wählen, in welcher Anzahl ein Artikel für das Intervall geliefert werden soll. Diese Angabe ist optional und kann verwendet werden, um Mindermengen auszugleichen. Wenn eine Artikelmenge z.B. nur für eine Woche ausreicht und der Kunde ein Intervall von zwei Wochen wählt, kann für diesen Fall der Artikelfaktor 2 eingetragen werden. Vorausgesetzt natürlich, dass der Kunde damit einverstanden ist, die korrigierte Menge zu erhalten.

|*Mindestlaufzeit*
|Mindestlaufzeit für die Abo-Funktion wählen. Unter dieser Laufzeit ist ein Abonnement nicht möglich. Die Mindestlaufzeit ist optional.

|*Maximale Laufzeit*
|Maximale Laufzeit für ein Abonnement wählen. Die maximale Laufzeit ist optional.

|*Auftragsherkunft für generierte Aufträge*
| Auftragsherkunft für Abonnements festlegen.
|====

[#920]
=== Einstellungen für Abo-Artikel vornehmen

Nehmen Sie nun Einstellungen für Ihre Abo-Artikel vor. Zunächst ordnen Sie die Abo-Artikel in Ihren Artikelbestand ein. Dann aktivieren Sie die Abo-Funktion. Gehen Sie dazu wie in den folgenden Unterkapiteln beschrieben vor.

[IMPORTANT]
.Einstellung *Abo-Intervall* am Verkaufspreis ohne Funktion
====
Der Scheduler berücksichtigt die Option *Abo-Intervall* des Verkaufspreises  nicht. Es ist zwar technisch möglich, Verkaufspreise für verschiedene Abo-Intervalle zu erstellen. Die Einstellung wird jedoch vom Scheduler ignoriert.
====

[#930]
=== Abo-Artikel kategorisieren

Sie haben verschiedene Möglichkeiten, Abo-Artikel in Ihren Artikelbestand einzuordnen. Empfehlenswert ist es, eine eigene *<<artikel/kategorien/kategorien-bearbeiten#, Kategorie>>* für Abo-Artikel anzulegen und die Artikel mit dieser Kategorie zu verknüpfen.

[#940]
=== Abo-Funktion aktivieren

Die Abo-Funktion aktivieren Sie zuerst global und dann für jeden Artikel separat. Die globale Aktivierung erlaubt es Kunden, grundsätzlich Bestellungen im Abonnement aufzugeben. Die Aktivierung für einzelne Artikel bestimmt, welche Artikel Kunden im Abonnement bestellen dürfen. Gehen Sie wie nachfolgendend beschrieben vor, um die Abo-Funktion global zu aktivieren.

[.instruction]
Abo-Funktion global aktivieren:

. Öffnen Sie das Menü <<omni-channel/online-shop/webshop-einrichten/mein-konto#, System » Mandant » Mandant wählen » Mein Konto » Einstellungen>>.
. Wählen Sie für die Option *Abonnements* die Einstellung *aktiviert*.
. *Speichern* Sie die Einstellungen.

Aktivieren Sie nun die Abo-Funktion für jeden Artikel, den Ihre Kunden im Abonnement bestellen dürfen sollen.

[.instruction]
Abo-Funktion des Abo-Artikels aktivieren:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab <<artikel/artikel-verwalten#40, Global>>.
. Wählen Sie im Bereich *Grundeinstellungen* für die Option *Abonnement* die Einstellung *Ja*.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Abo-Funktion deaktivieren
====
Wenn Sie die Abo-Funktion nicht mehr nutzen möchten, stellen Sie die globale Funktion auf *deaktiviert* und die Funktion beim Artikel auf *Nein*. Entfernen Sie den Code aus dem Layout Ihres Webshops. Weitere Informationen dazu finden Sie im Kapitel <<auftragsabwicklung/auftraege/scheduler#500, Template-Variablen in das Webshop-Layout einfügen>>.
====

[#950]
=== Template-Variablen in das Webshop-Layout einfügen

Damit Kunden in Ihrem Webshop die Abo-Funktionen wählen können, müssen Sie zunächst Template-Variablen und Code in das Layout Ihres Webshops einfügen.

[.instruction]
Template-Variablen in das Webshop-Layout einfügen:

. Öffnen Sie das Menü *CMS » Webdesign » Layout » ItemView » ItemViewSingleItem*.
. Fügen Sie die Template-Variablen und Code zwischen *$FormOpenOrder* und *$FormCloseOrder* ein. Beachten Sie die Erläuterungen in <<tabelle-template-variablen-abo-modul>>. +
→ Ein Code-Beispiel finden Sie unterhalb von <<tabelle-template-variablen-abo-modul>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-template-variablen-abo-modul]]
.Erläuterungen zu den Template-Variablen des Abo-Moduls
[cols="1,3"]
|====
|Template-Variable
|Funktion

|*$IsSubscriptionItem*
|Gibt einen Boolschen Wert zurück (TRUE oder FALSE, je nach Einstellung am Artikel). Diese Template-Variable für eine IF-Abfrage im Layout verwenden, um festzustellen, ob ein Artikel ein Abo-Artikel ist oder nicht. Ansonsten wird die Abo-Funktion bei allen Artikeln angezeigt und nicht nur bei den tatsächlichen Abo-Artikeln. Ein Beispiel mit IF-Abfrage befindet sich unter der Tabelle.

|*$SchedulerDateSelector*
|Fügt eine Kalender-Auswahlbox ein, damit Kunden das Datum der ersten Lieferung wählen können.

|*$SchedulerInterval*
|Fügt eine Dropdown-Liste zur Auswahl des Intervalls für das Abonnement ein. Es stehen die Intervalle zur Verfügung, die in den Einstellungen gespeichert wurden. Weitere Informationen finden Sie im Kapitel <<auftragsabwicklung/auftraege/scheduler#100, Grundlegende Einstellungen vornehmen>>.

|*$SchedulerRepeating*
|Fügt eine Dropdown-Liste zur Auswahl der Anzahl der Lieferungen ein. Es stehen die Optionen zur Anzahl der Aufträge zur Verfügung, die in den Einstellungen gespeichert wurden. Weitere Informationen finden Sie im Kapitel <<auftragsabwicklung/auftraege/scheduler#100, Grundlegende Einstellungen vornehmen>>.
|====

Der folgende Code ist ein Beispiel für die Anordnung und Bezeichnung der Template-Variablen:

[source,xml]
----
{% if $IsSubscriptionItem %}
<!--  Box Filter -->
<div class="ff01_pagenav" style="margin-top:5px;"<h2Abonnement</h2></div>
Erste Lieferung: $SchedulerDateSelector<br />
Intervall: $SchedulerInterval<br />
Lieferungen: $SchedulerRepeating<br />
<!--  End Box Filter -->
{% endif %}

----

[#960]
=== Ansicht der Abo-Funktion im Webshop

Nachdem Sie die auf dieser Seite beschriebenen Einstellungen konfiguriert haben, werden Abo-Artikel in Ihrem Webshop angezeigt. Käufer können den Zeitpunkt für die erste Lieferung, das Intervall sowie die Anzahl der Lieferungen festlegen, bevor sie den Artikel in den Warenkorb legen (Bild 1). Im Bestellvorgang können diese Einstellungen dann noch geändert werden, bevor die Bestellung abgeschickt wird. Das Code-Beispiel in Kapitel <<auftragsabwicklung/auftraege/scheduler#500, Template-Variablen in das Webshop-Layout einfügen>> wird im Webshop folgendermaßen dargestellt:

[#970]
=== Scheduler-Aufträge

Im Menü *Aufträge » Scheduler-Aufträge* werden Ihre Abonnements mit Informationen zu den Kunden und Aufträgen in einer Übersicht angezeigt. In dieser Ansicht suchen, bearbeiten und löschen Sie Scheduler-Aufträge.

Außerdem generieren Sie einen Auftrag aus dem Abonnement heraus durch Klick auf das *Zahnrad*, zu sehen in Bild 2 ganz rechts in der Zeile des Abonnements. Das Generieren eines Auftrags aus dem Abonnement ist notwendig, damit Sie den Auftrag in der Auftragsübersicht finden. Dies wird manuell ausgeführt.

[#980]
=== Scheduler-Aufträge suchen

Suchen Sie Scheduler-Aufträge anhand von bestimmten Filterkriterien. Die gefundenen Scheduler-Daten werden dann im Tab *Scheduler* aufgelistet.

[.instruction]
Scheduler-Aufträge suchen:

. Öffnen Sie das Menü *Aufträge » Scheduler-Aufträge*.
. Geben Sie die Suchbegriffe in die Suchfelder ein bzw. stellen Sie die Filteroptionen in den Dropdown-Listen ein. Beachten Sie dazu die Erläuterungen in <<tabelle-scheduler-auftraege-suchen>>.
. Klicken Sie auf *Suchen*. +
→ Die Scheduler-Aufträge, die den eingegebenen Suchkriterien entsprechen, werden aufgelistet.

[[tabelle-scheduler-auftraege-suchen]]
.Scheduler-Aufträge suchen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Die Suche durch einen Klick ausführen. Die gefundenen Scheduler-Aufträge werden im Tab *Scheduler* aufgelistet.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*Scheduler-ID*
|Jeder Scheduler-Datensatz erhält automatisch eine fortlaufende und exklusive ID. Die ID entspricht immer einer echten Zahl (z.B. "00521" oder "ADF8354" sind ungültig).

|*Kunden-ID*
|Suche nach der Kunden-ID.

|*Artikel-ID*
|Suche nach der Artikel-ID des Artikels, den der Scheduler-Auftrag enthält.

|*Kundenname*
|Suche nach dem Namen des Kunden. Es kann nach Vor- und Nachname gesucht werden.

|*Start*
|Den Zeitraum des Starttermins wählen, nach dem gesucht werden soll. Wählbar sind: +
*Alle* = Keine Filterung +
*Ohne Startdatum* = Suche nach Scheduler-Aufträgen ohne Startdatum. +
*Startdatum in Zukunft* = Suche nach Scheduler-Aufträgen mit einem Startdatum, das in der Zukunft liegt. +
*Startdatum in Vergangenheit* = Suche nach Scheduler-Aufträgen mit einem Startdatum, das in der Vergangenheit liegt. +
*In den letzten 7/14/30/80/90 Tagen* = Suche nach Scheduler-Aufträgen mit einem Startdatum, das eine bestimmte Anzahl von Tagen zurückliegt.

|*Ende*
|Den Zeitraum des Endtermins wählen, nach dem gesucht werden soll. Wählbar sind: +
*Alle* = Keine Filterung +
*Ohne Enddatum*= Suche nach Scheduler-Aufträgen ohne Enddatum. +
*Enddatum in Zukunft* = Suche nach Scheduler-Aufträgen mit einem Enddatum, das in der Zukunft liegt. +
*Zukünftig oder ohne Enddatum* = Suche nach Scheduler-Aufträgen ohne Enddatum oder mit einem Enddatum, das in der Zukunft liegt. +
*Enddatum in Vergangenheit* = Suche nach Scheduler-Aufträgen mit einem Enddatum, das in der Vergangenheit liegt. +
*In den letzten 7/14/30/80/90 Tagen* = Suche nach Scheduler-Aufträgen mit einem Enddatum, das eine bestimmte Anzahl von Tagen zurückliegt.

|*Durchlauf*
|Für den Durchlauf unter folgenden Filteroptionen wählen: +
*Noch nie* = Suche nach Scheduler-Aufträgen, für die noch kein Durchlauf stattgefunden hat. +
*In diesem Monat* = Suche nach Scheduler-Aufträgen, für die in diesem Monat ein Durchlauf stattgefunden hat. +
*Im letzten Monat* = Suche nach Scheduler-Aufträgen, für die im letzten Monat ein Durchlauf stattgefunden hat.

|*Aktiv*
|Zwischen den Optionen *Ja* und *Nein* oder der Einstellung *ALLE* wählen, wenn alle Scheduler-Aufträge gesucht werden sollen.

|*Eigner*
| Eigner wählen, um dessen Scheduler-Aufträge zu suchen. Der Eigner muss in den Kundendaten gespeichert sein.

|*Herkunft*
| Herkunft des Scheduler-Auftrags wählen.

|*Intervall*
|Wählbar sind die Option *Alle* sowie die Intervalle, die im Menü *System » Aufträge » Scheduler* gewählt wurden.

|*IBAN*
|Mit der Einstellung *Vorhanden* werden nur Scheduler-Aufträge für Kunden gesucht, bei denen die IBAN in den <<crm/kontakte-verwalten#1890, Bankdaten>> hinterlegt ist.

|*Lastschriftmandat*
|Suche nach Kunden, für die <<crm/kontakte-verwalten#200, SEPA-Lastschriftmandat>> vorliegt oder nicht vorliegt.

|*Mandant (Shop)*
| Mandanten wählen, um nur Scheduler-Aufträge des ausgewählten Mandanten anzuzeigen. +
*_Wichtig:_* Variable Benutzern stehen nur Mandanten zur Auswahl, für die sie eine Berechtigung haben. Berechtigungen werden unter <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90, System » Einstellungen » Benutzer » Konten » Tab: Berechtigung>> eingestellt.
|====

[#990]
=== Scheduler-Auftrag manuell anlegen

Gehen Sie wie im Folgenden beschrieben vor, um einen Scheduler-Auftrag manuell anzulegen.

[.instruction]
Scheduler-Auftrag manuell anlegen:

. Klicken Sie rechts in der Zeile eines Scheduler-Auftrags auf das *Zahnrad*. +
→ Das Fenster *Neuen Scheduler-Auftrag anlegen* wird geöffnet.
. Klicken Sie auf *Auftrag anlegen*. +
→ Bei erfolgreichem Anlegen erhalten Sie eine Erfolgsmeldung.

Nachdem ein Scheduler-Auftrag manuell gestartet wurde, wird in der Spalte *Letzter Durchlauf* das Datum des letzten Durchlaufs angezeigt (Bild 3).

Im Menü *Aufträge* wird ein Auftrag angelegt.

[TIP]
.Tipp: Aktion nicht erfolgreich: Einstellungen prüfen
====
Prüfen Sie die Einstellungen des Abonnements. Ein Fehler kann z.B. sein, dass das Startdatum in der Zukunft liegt. In diesem Fall passen Sie das Startdatum an. Oder die Zahlungsart wurde nicht in den Einstellungen des Schedulers berücksichtigt. Prüfen Sie die Scheduler-Einstellungen. Sie erhalten auch eine Fehlermeldung, wenn bereits ein Auftrag für diesen Scheduler-Auftrag generiert wurde.
====

=== Abonnement bearbeiten

Sie können bestehende Abonnements jederzeit bearbeiten. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Abonnement bearbeiten:

. Öffnen Sie das Menü *Aufträge » Scheduler-Aufträge*.
. Klicken Sie rechts in der Zeile des Scheduler-Auftrags, den Sie bearbeiten möchten, auf *Bearbeiten*. +
→ Der Scheduler-Auftrag wird zur Bearbeitung geöffnet.

Das Bearbeitungsfenster eines Scheduler-Auftrags gliedert sich in drei Tabs. Die Einstellungen im Tab *Base* werden in <<tabelle-einstellungen-tab-base>> erläutert. Die Einstellungen im Tab *Artikel* betreffen die abonnierten Artikel. Das Tab *Kunde* enthält die Informationen zum Kunden aus dem Menü *Kunden*.

==== Tab: Base

Folgende Parameter eines Abonnements werden im Tab *Base* angezeigt:

[[tabelle-einstellungen-tab-base]]
.Einstellungen im Tab *Base* des Scheduler-Auftrags
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Rechnungsanschrift*
|Die Anschrift, an die die Rechnung geschickt wird.

|*Kunde ändern*
|Klicken, um den Kunden zu ändern. Entweder die Kunden-ID oder den Namen des Kunden eintragen. Nach Eingabe von mindestens 3 Zeichen werden passende Treffer angezeigt.

|*Lieferanschrift*
|Enthält die Lieferanschrift, wenn diese in den Kundendaten hinterlegt ist.

|*Lieferanschrift ändern*
|Wenn für den Kunden Lieferanschriften hinterlegt sind, können diese gewählt werden. Es kann jedoch keine neue Lieferanschrift angelegt werden.

|*Scheduler-ID*
|Die ID des Abonnements wird automatisch vom System vergeben und ist nicht änderbar.

|*Aktiv*
|Bei gesetztem Häkchen ist der Scheduler-Auftrag aktiv. +
Das Häkchen entfernen und auf *Speichern* klicken, um den Scheduler-Auftrag zu deaktivieren.

|*Anzahl der Aufträge*
|Die im Menü *Einstellungen* hinterlegten Werte werden angezeigt; die Anzahl der Sendungen kann geändert werden. +
Vor dem Schrägstrich wird die Anzahl der bereits versendeten Aufträge angezeigt.

|*Start*; +
*Ende*
|Datum für Start und Ende des Scheduler-Auftrags wählen, um die Laufzeit zu bestimmen. +
Zur Konfiguration wird ein Kalender geöffnet, in dem auch ein bestehendes Datum geändert werden kann.

|*Start Artikel*; +
*Ende Artikel*
|Sucht Scheduler mit Artikeln mit einem Start- bzw. Enddatum gemäß der gewählten Option, z.B. Startdatum in den letzten sieben Tagen.

|*Letzter Durchlauf*
|Zeigt das Datum des zuletzt gesendeten Auftrags an, also wann der jüngste Auftrag versendet wurde. +
Anhand des angegebenen Datums kann der Zeitpunkt für den nächsten Scheduler-Auftrag ermittelt werden, wenn dieser manuell ausgeführt werden soll.

|*Intervall*
|Bei Bedarf das Intervall für diesen Scheduler-Auftrag ändern. Verfügbar sind die Werte, die im Menü *Einstellungen* festgelegt wurden.

|*Gutschein*
|Es wird angezeigt, ob ein Gutschein für den Scheduler-Auftrag verwendet wurde.

|*Währung*
|Die Währung des Scheduler-Auftrags. Bei Bedarf eine andere Währung aus der Dropdown-Liste wählen.

|*Versandkosten*
|Die Kosten für den Versand. Bei Bedarf einen anderen Betrag eingeben.

|*Versandart*
|Die Versandart des Scheduler-Auftrags. Bei Bedarf eine andere Versandart aus der Dropdown-Liste wählen.

|*Zahlungsart*
|Die Zahlungsart des Scheduler-Auftrags. Bei Bedarf eine andere Zahlungsart aus der Dropdown-Liste wählen.

|*Mandant (Shop)*
|Der Mandant (Shop) des Scheduler-Auftrags. Bei Bedarf einen anderen Mandanten (Shop) aus der Dropdown-Liste wählen. +
Der gewählte Mandant bestimmt die im Tab *Artikel* verfügbaren *<<auftragsabwicklung/auftraege/buchhaltung#, Mehrwertsteuersätze>>* (siehe unten).

|*Eigner*
|Die Eigner des Scheduler-Auftrags. Bei Bedarf einen anderen Eigner aus der Dropdown-Liste wählen.

|*Herkunft*
|Die Herkunft des Scheduler-Auftrags. Bei Bedarf eine andere Herkunft aus der Dropdown-Liste wählen.
|====

==== Tab: Artikel

Das Tab *Artikel* gliedert sich in zwei Untermenüs. Im Tab *Scheduler-Artikel* sehen Sie die Artikel, die sich aktuell im Scheduler-Auftrag befinden. Sie können hier u.a. die *Menge* und den *Preis* bearbeiten. Die hier verfügbaren *Mehrwertsteuersätze* ergeben sich aus dem im Tab *Base* gewählten Mandanten. Es stehen die Mehrwertsteuersätze zur Auswahl, die bei dem Mandanten unter <<auftragsabwicklung/auftraege/buchhaltung#, System » Mandant » Mandant wählen » Buchhaltung>> als Umsatzsteuersätze hinterlegt sind.

Wenn Sie die Artikelbeschreibung im Feld *Artikelbeschreibung* ändern, wird diese Änderung nicht am Artikel selbst übernommen.

Im Tab *Artikel hinzufügen* wird die *Artikelübersicht* angezeigt, so dass Sie aus Ihrem gesamten Artikel-Portfolio wählen können.

Die Optionen *Start* und *Ende* entsprechen denen für den Scheduler-Auftrag (siehe <<tabelle-einstellungen-tab-base>>) mit dem Unterschied, dass damit die Laufzeit für jeden Artikel separat bestimmt werden kann. Damit ist es z.B. möglich, verschiedene Artikel zu bestimmten Zeiten oder auch nacheinander für ein Abo anzubieten.

==== Tab: Kunde

Beim Klick auf das Tab *Kunde* öffnet sich der Kontaktdatensatz im Menü <<crm/kontakte-verwalten#, CRM » Kontakte>>.

[#1000]
=== Neues Abonnement anlegen

Gehen Sie wie im Folgenden beschrieben vor, um ein neues Abonnement anzulegen.

[.instruction]
Neues Abonnement anlegen:

. Öffnen Sie das Menü *Aufträge » Scheduler-Aufträge*.
. Klicken Sie auf *Neu*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-einstellungen-tab-base>>.
. *Speichern* Sie die Einstellungen. +
→ Das neue Abonnement wird angelegt.

[#1010]
=== Durchlauf der Abo-Aufträge starten

Im Menü *Aufträge » Durchlauf* werden anstehende Abo-Aufträge angezeigt. Sie können hier Abo-Aufträge gesammelt starten, was besonders komfortabel ist, wenn Sie viele Abonnements bearbeiten und überwachen müssen.

Sie sehen nach dem Klicken auf eines der Icons *Durchlauf starten* (siehe Bild 5, grüne Pfeile), für welche Abonnement-IDs Aufträge anstehen.

[.instruction]
Abo-Aufträge wählen und starten

. Wählen Sie die Filteroptionen oder lassen Sie die Einstellungen auf *ALLE*, wenn Sie alle aktuell anstehenden Abo-Aufträge anlegen möchten.
. Starten Sie den *Durchlauf* dann durch Klick auf eines der Icons. Dadurch werden die Abo-Aufträge angelegt und dann im Durchlauf nicht mehr angezeigt.


[#1100]
== Auftragstyp Vorbestellung nutzen

Vorbestellungen sind im Online-Handel ein wichtiges Instrument im Marketing-Mix. Meist können Artikel noch vor der tatsächlichen Verfügbarkeit zum günstigen Einführungspreis bestellt werden. Für eine Warenwirtschaft stellt diese Situation einen Sonderfall dar, da noch nicht verfügbare Artikel natürlich auch noch keinen Lagerbestand haben können.

Vorbestellungen sind in plentymarkets sehr einfach zu erstellen. Es gibt dafür den Auftragstyp *Vorbestellung*, den Sie bei manuell erfassten Aufträgen verwenden können.

Um Vorbestellungen über den Webshop entgegennehmen zu können, ist das Erscheinungsdatum und die Artikelverfügbarkeit notwendig. Nehmen Sie dazu die auf dieser Seite beschriebenen Einstellungen am Artikel vor.

[IMPORTANT]
.Manuelle Auftragseingabe
====
Der Auftragstyp *Vorbestellung* kann nur bei manueller Auftragseingabe gewählt werden. Eine automatische Zuweisung des Auftragstyps *Vorbestellung* bei Bestellungen über den Webshop erfolgt in der aktuellen Version von plentymarkets noch nicht.
====

[#1110]
=== Erscheinungsdatum

Die Option *Erscheinungsdatum* finden Sie in der Artikelbearbeitung im Tab *Verfügbar*. Hier können Sie über einen Kalender das Datum hinterlegen, zu dem der Artikel verfügbar sein wird (Eingabe auch per dynamischem Import möglich). Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Erscheinungsdatum eintragen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie einen Artikel, den Sie vorbestellbar machen möchten.
. Wechseln Sie in das Tab *Verfügbar*.
. Tragen Sie bei *Erscheinungsdatum* das Datum ein, ab dem der Artikel verfügbar sein soll.
. *Speichern* Sie die Einstellungen.

Im nächsten Schritt sorgen Sie dafür, dass das Erscheinungsdatum Ihren Kunden angezeigt wird. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Erscheinungsdatum im Webshop sichtbar machen:

. Öffnen Sie das Menü *CMS » Webdesign » Ordner: Layout » Ordner: ItemView*.
. Öffnen Sie das Template *ItemViewSingleItem*.
. Fügen Sie die Template-Variable *$ReleaseDate* ein.
. *Speichern* Sie die Einstellungen.

[#1120]
=== Artikelverfügbarkeit

Eine weitere Voraussetzung ist die korrekte Einstellung der *Artikelverfügbarkeit*. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Artikelverfügbarkeit für Vorbestellungen einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie einen Artikel, den Sie vorbestellbar machen möchten.
. Wechseln Sie in das Tab *Einstellungen*.
. Wählen Sie für die Option *Beschränkung* die Einstellung *Keine Beschränkung*. +
→ Der Artikel kann nun ohne tatsächlichen Bestand vorbestellt, also verkauft werden.

[TIP]
.Maximale Bestellmenge
====
Damit andere Online-Händler Ihre Vorbestellungen nicht dazu missbrauchen können, Ihre Bestände zum günstigen Preis komplett aufzukaufen, tragen Sie im *Tab Verfügbar* bei der Option *Maximale Bestellmenge* einen Wert ein. Tragen Sie dort den Wert *1* ein, kann der Artikel pro Bestellung nur ein einziges Mal gekauft werden. Setzen Sie die maximale Abgabemenge auf den Wert *0*, wird ohne Beschränkung verkauft.
====

[#1130]
=== Zahlungsaufforderung für Vorbestellungen einrichten

Die Option *Versanddatum* bleibt bei normalen Bestellungen in der Regel ungenutzt, kann jedoch für Vorbestellungen sinnvoll verwendet werden. Liegt das Erscheinungsdatum eines Artikels aber in der Zukunft, so wird das Erscheinungsdatum bei der Bestellung als Versanddatum hinterlegt, da ja erst mit dem Erscheinen des Artikels geliefert werden kann. Das Versanddatum können Sie in der Auftragssuche als Filteroption verwenden und über den Aktionsmanager nutzen.

Meist werden Vorbestellungen einige Zeit vor dem Erscheinen eines Artikels generiert, von den Kunden zum Zeitpunkt der Bestellung aber noch nicht bezahlt. Daher ist es sinnvoll, Kunden einige Tage vor dem Erscheinungs- bzw. Versanddatum über den bevorstehenden Versand zu informieren und sie zur Zahlung aufzufordern. Dies kann der *Aktionsmanager* automatisch für Sie erledigen. Kunden wird dann wenige Tage vor dem geplanten Versand eine Erinnerungs-E-Mail mit Ihren Bankdaten und dem Link zur Kaufabwicklung gesendet. Gehen Sie wie unten beschrieben vor, um die automatische Zahlungsaufforderung für Vorbestellungen einzurichten.

[.instruction]
Zahlungsaufforderung per E-Mail einrichten:

. Erstellen Sie eine geeignete *<<crm/e-mails-versenden#1200, E-Mail-Vorlage>>*.
. Öffnen Sie das Menü *System » Aufträge » Aktionen*.
. Wechseln Sie in das Tab *Neue Aktion*.
. Tragen Sie dort im Tab *Einstellungen* einen *Namen* ein.
. Wählen Sie bei der Option *Täglich ausführen um* eine Uhrzeit aus der Dropdown-Liste.
. Setzen Sie ein Häkchen bei *Aktiv*, um die Aktion zu aktivieren.
. Wechseln Sie in das Tab *Filter*.
. Wählen Sie für den *Status* die Einstellung *[3] Warten auf Zahlung*.
. Wählen Sie unter *Versanddatum* z.B. die Einstellung *in 4 Tagen*.
. Wechseln Sie in das Tab *Aktion*.
. Wählen Sie bei der Option *Versende E-Mail-Vorlage* die zuvor erstellte E-Mail-Vorlage. Diese Vorlage wird dann mit dieser Aktion automatisch an den Kunden gesendet.
. Klicken Sie auf *Speichern*, um die Aktion zu sichern.

[#1200]
== Auftragsstatus nutzen

Mit Auftragsstatus wird der Fortschritt bei der Abwicklung von Aufträgen abgebildet. 18 Status mit je 4 Nachkommastellen, d.h. eine Anzahl von 189999, stehen Ihnen im System zur Verfügung. 28 sind bereits vorangelegt. Diese vorangelegten Status stellen einen Grundstock für übliche Abwicklungsschritte dar. Einige der 28 voreingetragenen Status sind mit Systemautomatismen verknüpft und sollten von Ihnen auch nur für die systemseitig vorgesehenen Zwecke verwendet werden. Der Auftragsstatus eines Auftrags ändert sich durch diese Systemautomatismen, durch von Ihnen eingerichtete Automatismen oder kann auch manuell geändert werden. Auftragsstatus dienen auch zur besseren Auftragssuche.

Spielen Sie Ihre Auftragsabwicklung einmal grob durch und überlegen Sie sich, wann Sie Aufträgen einen neuen Status zuordnen möchten, um den Fortschritt bei der Abwicklung kenntlich zu machen. Richten Sie anschließend die Status ein, indem Sie Namen für die Status eingeben. Beachten Sie jedoch die zweckgebundenen Status, die in [[tabelle-vorhandene-status]] erwähnt sind.

[TIP]
.Benutzerrechte beachten
====
Beachten Sie, dass Ihnen in Dropdown-Listen etc. nur die *Shops* und **Auftragsstatus** angezeigt werden, die für Ihren Benutzer freigegeben wurden. Wenn Sie einen Status nicht sehen, fehlt Ihnen wahrscheinlich die Berechtigung für den Status. Berechtigungen können durch Admin-Benutzer vergeben werden.
====

[#1210]
=== Voreingestellte Status verstehen

Die folgenden 28 Statuseinträge sind bereits zu Beginn in Ihrem plentymarkets System vorhanden und sind teilweise mit Systemautomatismen verknüpft. Die mit Systemautomatismen verknüpften Status sind nicht löschbar.

[[tabelle-vorhandene-status]]
.Standardstatus und Systemautomatismen
[cols="1,3"]
|====
|Status |Erläuterung

|**[1]** Unvollständige Daten
|Wird automatisch zugeordnet, wenn Daten eines Auftrages unvollständig sind, z.B. Addressdaten noch fehlen. Unvollständige Daten sind teilweise bei Importen von Märkten der Fall. Aufträge in diesem Status dürfen noch nicht weiter bearbeitet werden. Die Daten werden durch nachfolgende Importe noch vervollständigt. Die unvollständigen Daten dienen z.B. der frühzeitigen Bestandsreservierung.

|**[1.1]** Warten auf Zahlung &amp; Freischaltung
.3+|Werden nicht automatisch vergeben. Ein Anwendungsfall ist der vorbefüllte Warenkorb. Ein Auftrag wird angelegt und ein Link zum Warenkorb des Auftrags wird zur Bestätigung an den Kunden geschickt.

|**[1.2]** Freigeschaltet, warten auf Zahlung

|**[2]** Warten auf Freischaltung

|**[3]** Warten auf Zahlung
|Wird jedem unbezahlten Auftrag vom Typ Auftrag automatisch zugeordnet

|**[3.2]** In Warteposition
|Wird automatisch in 2 Fällen gesetzt: +
* Wenn für einen Auftrag eine Teilzahlung gebucht wird, aber kein Warenbestand vorhanden ist. +
* Wenn für einen Auftrag eine Überbezahlung gebucht wird.

|**[3.3]** Versandfertig; warten auf Zahlung
|Wird automatisch einem Auftrag des Typs Auftrag zugeordnet, wenn dem Auftrag eine Teilzahlung zugeordnet wird und Bestand für den Auftrag vorhanden ist.

|**[3.4]** Mahnung versendet
|Empfohlen, um zu erkennen, dass ein Mahnung versendet wurde. Mithilfe einer Ereignisaktion oder Prozessen lässt sich hier eine Automatisierung erreichen. Der Status wird jedoch nicht durch einen Systemautomatismus gesetzt.

|**[4]** In Versandvorbereitung
|Steht in Verbindung mit Bestandsbeschränkung. Wenn Sie keinen Bestand führen und keine Beschränkung nutzen, dann steht der Status zur freien Verfügung. +
Wenn die Bestandsbeschränkung genutzt wird, wird der Status automatisch zugeordnet, wenn ein Auftrag vom Typ Auftrag bezahlt ist, aber der Bestand der Artikel für den Auftrag nicht ausreicht. Die Beschränkung von Artikeln muss auf Nettowarenbestand eingestellt sein. +
Wenn Sie die Bestandsbeschränkung und diesen Status bei fehlendem Bestand nutzen, können Sie z.B. erreichen, dass nur Lieferscheine und Rechnungen für Aufträge erzeugt werden, die auch weiter abgewickelt werden können.

|**[5]** Freigabe Versand
|Wird automatisch zugeordnet, wenn ein Auftrag vom Typ Auftrag bezahlt oder die Zahlungsart z.B. Rechnung oder Vorkasse ist und der Bestand der Artikel für den Auftrag ausreicht oder der Bestand unbeschränkt ist.

|**[5.1]** Abwicklung extern
|Empfohlen, um zu kennzeichen, dass die Ware durch einen Fulfillment-Anbieter zusammengestellt und verschickt wird. Der Status wird jedoch nicht durch einen Systemautomatismus gesetzt.

|**[6]** Gerade im Versand
|Empfohlen, um zu kennzeichnen, dass Aufträge zum Picken und Packen an das Lager übertragen wurden. Mithilfe von Ereignisaktionen oder Prozessen lässt sich hier eine Automatisierung erreichen.

|**[7]** Warenausgang gebucht
|Wird automatisch zugeordnet, wenn der Warenausgang in einem Auftrag gebucht wurde. Das manuelle Setzen des Status sorgt wiederum nicht dafür, dass der Warenausgang tatsächlich gebucht wird und der Bestand reduziert wird. Deshalb sollte dieser Status nicht manuell, per Ereignisaktion oder Prozess gesetzt werden.

|**[7.1]** Auftrag exportiert
|Steht zur freien Verfügung. Möglicher Anwendungsfall ist das Setzen des Status, nachdem Aufträge zur Auswertung exportiert wurden.

|**[8]** Storniert
|Empfohlen, um zu kennzeichnen, dass ein Auftrag vom Typ Auftrag storniert wurde. Status 8 ist als Standard für stornierte Aufträge festgelegt. Sie können die Standardfestlegung für stornierte Aufträge jedoch im Menü *System » Aufträge » Einstellungen* ändern. Die Einstellung hierfür heißt *Status stornierter Aufträge*. Wenn Sie einen anderen Status für Stornierungen festgelegt haben, können Sie Status 8 frei nutzen.

|**[8.1]** Storniert durch Kunden
|Empfohlen, um zu kennzeichnen, dass ein Auftrag durch den Kunden storniert wurde

|**[9]** Retoure
|Ist beim Anlegen eines Auftrags vom Typ Retoure automatisch vorausgewählt. Sie können auch einen anderen Status als Standard festlegen. Die Einstellung erfolgt im Menü *System » Aufträge » Einstellungen*.

|**[9.1]** Ware wird geprüft
|Empfohlen, um in einer Retoure anzuzeigen, dass die retournierte Ware geprüft wird

|**[9.2]** Warten auf Retoure von Großhändler
|Steht zur freien Verfügung.

|**[9.3]** Gewährleistung eingeleitet
|Empfohlen, um zu kennzeichnen, dass eine Gewährleistung zur Retoure eingeleitet wurde.

|**[9.4]** Umtausch eingeleitet
|Empfohlen, um in einer Retoure anzuzeigen, dass ein Umtausch der retournierten Ware eingeleitet wurde.

|**[9.5]** Gutschrift angelegt
|empfohlen, um in einer Retoure anzuzeigen, dass eine Gutschrift zur Retoure angelegt wurde.

|**[10]** Gewährleistung
|Steht zur freien Verfügung. Kann genutzt werden, um eine Gewährleistung als abgeschlossen zu kennzeichen. Beim Anlegen einer Gewährleistung erhält der Gewährleistungsauftrag je nach Bestandsführung Status 4 oder 5.

|**[11]** Gutschrift
|Wird einem Auftrag vom Typ Gutschrift automatisch zugeordnet, wenn eine Gutschrift angelegt wird. Sie können auch einen anderen Status als Standard festlegen. Die Einstellung erfolgt im Menü *System » Aufträge » Einstellungen*.

|**[11.1]** Gutschrift ausgezahlt
|Empfohlen, um zu kennzeichen, dass die Gutschrift ausgezahlt wurde und abgeschlossen ist.

|**[12]** Reparatur
|Ist beim Anlegen eines Auftrags vom Typ Retoure automatisch vorausgewählt. Sie können auch einen anderen Status als Standard festlegen. Die Einstellung erfolgt im Menü *System » Aufträge » Einstellungen*.

|**[13]** Sammelauftrag
|Wird einem Auftrag vom Typ Sammelauftrag automatisch zugeordnet, wenn er angelegt wird. Sie können auch einen anderen Status als Standard festlegen. Die Einstellung erfolgt im Menü *System » Aufträge » Einstellungen*.

|**[14]** Sammelgutschrift
|Wird einem Auftrag vom Typ Sammelgutschrift automatisch zugeordnet, wenn er angelegt wird. Sie können auch einen anderen Status als Standard festlegen. Die Einstellung erfolgt im Menü *System » Aufträge » Einstellungen*.
|====

[#1220]
=== Status hinzufügen und bearbeiten

Sie können neben den in <<tabelle-vorhandene-status>> aufgeführten Status eigene hinzufügen. Die bereits vorhandenen können Sie bearbeiten und z.B. umbenennen. Pflegen Sie Status in verschiedenen Sprachen, um Ihre Kunden per E-Mail oder im Kundenkonto des Webshops über den Fortschritt zu informieren. Bis auf Status, die mit Systemautomatismen verbunden sind, können Sie alle Status auch wieder löschen. Status, die mit Systemautomatismen verbunden sind, können Sie umbenennen. Sie sollten die mit Systemautomatismen verbundenen Status jedoch nicht zweckentfremden.

[TIP]
.Name ist kein Pflichtfeld
====
Der Name ist kein Pflichtfeld. Wenn Sie keinen Namen pflegen, sehen Sie in Filtern jedoch nur eine Liste vermeintlich leerer Status und in der Auftragsübersicht ein leeres Statusfeld. Tragen Sie deshalb z.B. wenigstens die Statusnummer auch als Namen für Ihre hauptsächlich genutzte Sprache, Deutsch oder Englisch, ein. Übersetzungen in andere Sprachen dienen nur der Anzeige im Kundenkonto Ihres Shops sowie zur Kundenbenachrichtigung per E-Mail.
====

[#1230]
==== Status hinzufügen

Fügen Sie eigene Status hinzu.

[.instruction]
Status hinzufügen:

. Öffnen Sie das Menü *System » Aufträge » Status*.
. Klicken Sie auf *Neuen Status erstellen*.
. Tragen Sie eine Statusnummer ein. +
→ Die höchstmögliche Nummer ist 18.9999.
. Tragen Sie optional einen Namen ein. +
→ Die Sprache, in der Sie eingeloggt sind, wird als Eingabefeld angezeigt.
. *Speichern* Sie die Einstellungen. +
→ Eingabefelder für weitere Einstellungen werden sichtbar. +
. Fügen Sie bei Bedarf weitere Sprachen für den Auftragsstatus hinzu.
. Unter *Farbe* können Sie eine individuelle Farbe für den Auftragsstatus wählen. +
. *Speichern* Sie die Einstellungen. +

[NOTE]
.Nachkommastellen
====
Achten Sie bei der Vergabe der Statusnummern darauf, dass diese nicht auf 0 enden. Besteht die letzte Nachkommastelle aus einer 0, wird diese automatisch vom System gekürzt. In plentymarkets wird somit nicht zwischen einem Status mit der Nummer 1.1 und einem Status mit der Nummer 1.10 unterschieden.
====

[#1240]
==== Status bearbeiten

Gehen Sie wie folgt vor, um einen einzelnen bestehenden Status zu bearbeiten.

[.instruction]
Einzelnen Status bearbeiten:

. Öffnen Sie das Menü *System » Aufträge » Status*.
. Klicken Sie auf *Suchen*. +
→ Eine Liste aller vorhandenen Status wird geöffnet.
. Wählen Sie den gewünschten Status aus der Ergebnisliste. +
→ Die Detailansicht des Status wird geöffnet.
. Ändern Sie den Namen des Status.
. Ändern Sie die *Farbe* des Status.
. Klicken Sie auf das *Zahnrad*. +
→ Die Änderungen werden gespeichert.

Nutzen Sie die Gruppenfunktion im Menü *System » Aufträge » Status*, um mehrere Aufträge zugleich zu bearbeiten.

[.instruction]
Mehrere Status bearbeiten:

. Öffnen Sie das Menü *System » Aufträge » Status*.
. Klicken Sie auf *Suchen*. +
→ Eine Liste aller vorhandenen Status wird geöffnet.
. Setzen Sie in der Statusliste ein Häkchen für alle Status, die bearbeitet werden sollen.
. Klicken Sie auf *Gruppenfunktion*. +
→ Ein neuer Bearbeitungsbereich wird angezeigt.
. Aktivieren Sie im Bearbeitungsbereich die Option *Neue Farbe*, um eine neue Statusfarbe auszuwählen.
. Aktivieren Sie die Option *Shop-Sichtbarkeit* und wählen Sie die gewünschte Einstellung aus dem Dropdown-Menü.
. Klicken Sie auf das *Zahnrad*, um die Einstellungen auf die ausgewählten Status zu übertragen. +
→ Die Änderungen werden gespeichert.

[#1300]
== Aufträge suchen

Mit der Auftragssuche können Sie sowohl alle Aufträge auflisten als auch bestimmte Aufträge gezielt finden. Beim Öffnen des Menüs wird standardmäßig keine Suche ausgeführt, jedoch ist der Filter Datum standardmäßig auf *Auftragseingang* in den letzten 2 Monaten eingestellt. Alle anderen Filteroptionen stehen zunächst auf **ALLE**. Ändern Sie die Filtereinstellungen, um die Suche einzuschränken und führen Sie dann eine Suche aus.

[.instruction]
Aufträge suchen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*
. Nehmen Sie Filtereinstellungen vor.
. Prüfen Sie, ob die Standardeinstellung für die Option *Datum* und den Zeitraum unter *von bis* Ihren Kriterien entspricht.
. Klicken Sie auf *Suchen*, um die Aufträge anzuzeigen.

Wenn Sie z.B. nach Aufträgen, die in einem Status kleiner als (<) Status 7 sind, bei denen der Warenausgang nicht gebucht ist und Sie keine Datum berücksichtigen, dann erhalten Sie alle Aufträge, die noch nicht abgeschlossen sind.

[NOTE]
.Suche zurücksetzen
====
Klicken Sie auf *Reset*, um Ihre Filtereinstellungen auf die Standardwerte zurückzusetzen. Klicken Sie dann erneut auf *Suchen*, um auch das Suchergebnis zurückzusetzen.
====

[#1310]
=== Nach IDs und Nummern filtern

Um nach IDs oder Nummern zu filtern, geben Sie in die Eintragsfelder eine ID oder Nummer ein. Durch Eingabe einer *Kunden-ID* erhalten Sie z.B. nur die Aufträge des Kunden mit dieser ID.

Wenn Sie eine 3 in das Feld *Auftrags-ID* eingeben und suchen, wird auch nur der Auftrag mit der ID 3 in der Übersicht angezeigt. Es handelt sich also um eine genaue Suche und keine unscharfe Suche. Jedoch können Sie bei den Auftrags-IDs mehrere IDs kommagetrennt eintragen und auf diese Weise auch nach mehreren Aufträgen suchen.

[NOTE]
.Status-Suchfilter prüfen
====
Wenn Sie nach Nummern oder IDs suchen, ist es sinnvoll den Status nicht einzuschränken und *Alle* einzustellen. Es werden nur Aufträge angezeigt, die alle eingestellten Kriterien erfüllen. Wenn Sie einen Auftrag trotz eindeutiger ID nicht finden, haben Sie vielleicht den Suchfilter *Status* nicht auf den Wert *ALLE* umgestellt.
====

[#1320]
=== Nach Kunden- bzw. Artikeldaten und Rechnungsnummern filtern

Für gezielte Suchen anhand von kunden- oder artikelbezogenen Angaben nutzen Sie am besten die Suchfelder *Kundendaten* und *Artikeldaten*. Hier ist die Eingabe von Suchbegriffen und Zahlen gleichermaßen zulässig. Bei den *Kundendaten* sind neben Namen auch Postleitzahlangaben möglich, jedoch keine Telefonnummern. Bei den *Artikeldaten* werden Artikel-ID, Artikel-Nummer und Name abgefragt, jedoch nicht die Felder mit den Beschreibungstexten (short_description, description). Bei der Suche nach *Rechnungsnummern* ist auch die Suche nach externen Rechnungsnummern möglich.

[NOTE]
.Suchbegriffe und Zahlen nur am Ende kürzen
====
Bei der Suche nach Kunden bzw. Artikeldaten reicht es häufig aus, nur den Wortstamm einzugeben. Achten Sie aber darauf, dass Sie Suchwörter hinten fast beliebig kürzen können, am Wortanfang allerdings nicht. Suchen Sie z.B. nach Artikeln mit dem Stichwort Startersets, können Sie Starterset oder Starter oder Start eingeben. Eine Suche nach arterset hingegen führt zu keinem Ergebnis. Gleichermaßen verhält es sich mit Zahlenwerten wie z. B. Kundennummern oder PLZ.
====

[#1330]
=== Nach Auftragstypen filtern

Nutzen Sie den Filter *Typ*, um nach folgenden *Auftragstypen* zu suchen:

* *Auftrag*
* *Gutschrift*
* *Sammelgutschrift*
* *Retoure*
* *Gewährleistung*
* *Angebot*
* *Vorbestellung*
* *Lieferauftrag*
* *Reparatur*
* *Sammelauftrag*
* *Aufträge, Gewährleistungen, Lieferaufträge und Reparaturen*
* *Aufträge und Lieferaufträge*
* *Aboauftrag*

Nur die gewählten Auftragstypen bzw. die Kombinationen werden gesucht. In der Standardeinstellung steht der Filter auf *ALLE*, d.h. alle Auftragstypen werden gesucht.

[#1340]
=== Nach Datum filtern

Nutzen Sie den Filter *Datum*, um Aufträge zu suchen, die im eingestellten Zeitraum einen bestimmten Schritt durchlaufen haben. Zur Wahl als Ereignis unter *Datum* stehen der *Auftragseingang*, der *Zahlungseingang* oder der *Warenausgang*. Wählen Sie dann unter *von* das Startdatum und unter *bis* das Enddatum des Zeitraums. Alle Aufträge, die innerhalb des gewählten Zeitraums den gewählten Schritt durchlaufen haben, werden angezeigt. Für die Suche ist standardmäßig *Auftragseingang* und ein Zeitraum von 2 Monaten rückwirkend zum aktuellen Datum eingestellt.

Wenn Sie Aufträge nicht mit der Standardeinstellung von 2 Monaten rückwirkend suchen möchten, wählen Sie den gewünschten Zeitraum, wie nachfolgend erläutert.

[.instruction]
Aufträge nach Datum filtern:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Wählen Sie aus der Dropdown-Liste unter *Datum* eine der Filteroptionen, z. B. *Auftragseingang*.
. Wählen Sie unter *von* und *bis* das Start- und das Enddatum.
. Wählen Sie ggf. weitere Filteroptionen.
. Klicken Sie auf *Suchen*, um Aufträge des gewählten Zeitraums anzuzeigen.

[#1350]
=== Nach Markierungen filtern

Sie können Aufträgen unabhängig vom Auftragsstatus Markierungen zuweisen. Auch nach diesen Markierungen können Sie Aufträge filtern. So können Sie z.B. festlegen, dass problematische Aufträge mit einem bestimmten Symbol gekennzeichnet werden und vor der Auslieferung von einem Verantwortlichen freigegeben werden müssen. Dieser kann die Aufträge einmal täglich über den Filter *Markierung* suchen, eine Information hinterlegen und die Markierung dann wieder zurücksetzen.

[#1360]
=== Nach Dokumenten filtern

Nutzen Sie den Filter *Dokument*, um Aufträge zu suchen, für die bereits ein *<<auftragsabwicklung/auftraege/auftragsdokumente#, Dokument>>* eines bestimmten Typs angelegt wurde. Die folgenden zwei Möglichkeiten stehen zur Verfügung:

Um alle Aufträge anzuzeigen, für die ein Dokument eines Typs angelegt wurde, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Alle Aufträge mit einem Dokument suchen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Wählen Sie im Tab *Filter* einen Dokumententyp aus der Dropdown-Liste *Dokument*, z.B. Rechnung.
. Beachten Sie den Filter *Datum*, da standardmäßig nur Aufträge der letzten 2 Monate angezeigt werden. Passen Sie den Filter gegebenenfalls an.
. Klicken Sie auf *Suchen*. +
→ Alle Aufträge, für die bereits eine Rechnung generiert wurde, werden im Suchergebnis angezeigt.

Auch die Suche nach einem Auftrag, der ein Dokument mit einer bestimmten Nummer enthält, ist möglich. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Auftrag mit einer Dokumentnummer suchen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Wählen Sie im Tab *Filter* einen Dokumententyp aus der Dropdown-Liste *Dokument*, z.B. Lieferschein.
. Tragen Sie im Feld *Nummer* rechts daneben die Nummer des gesuchten Lieferscheins ein.
. Beachten Sie den Filter *Datum*, da standardmäßig nur Aufträge der letzten 2 Monate angezeigt werden. Passen Sie den Filter gegebenenfalls an.
. Klicken Sie auf *Suchen*. +
→ Nur der Auftrag, zu dem der Lieferschein mit der eingegeben Nummer gehört, wird im Suchergebnis angezeigt.

[TIP]
.Auswahl eines Dokumententyps bei Suche mit Nummer nicht zwingend erforderlich
====
Die Suche nach einer Dokumentennummer funktioniert auch, wenn Sie die Standardeinstellung *Dokument* stehen lassen, also keinen Typen wählen. Wenn jedoch die Nummern verschiedener Dokumententypen identisch sind, werden Ihnen alle Aufträge, die ein Dokument mit dieser Nummer haben, angezeigt. Dies kann zum Beispiel der Fall sein, wenn Sie alle Dokumente ohne Nummernkreis durchnummerieren.
====

[#1370]
=== Nach Gutscheincodes filtern

Nach Aufträgen mit *<<auftragsabwicklung/auftraege/gutscheine#, Gutscheinen>>* suchen Sie, indem Sie den Gutscheincodes in das Suchfeld *Gutschein-Code* eintragen. Zusätzlich stehen die Optionen *Alle*, *Eingelöst* und *Verkauft* zur Verfügung. *Alle* ist standardmäßig voreingestellt. Mit *Eingelöst* suchen Sie nur Aufträge, in denen der Gutscheincode eingelöst wurde. Mit *Verkauft* suchen Sie nur Aufträge, in denen ein Gutschein mit dem eingetragenen Gutscheincode verkauft wurde. *Alle* sucht sowohl Aufträge, in denen der Code eingelöst als auch verkauft wurde. Der Suchfilter, auch mit der Option *Alle*, greift nur, wenn ein Gutscheincode eingetragen ist. Sie können den Suchfilter also nicht nutzen, um alle Aufträge mit Gutscheinen zu suchen.

[#1400]
== Auftragsübersicht einrichten

Damit Sie die Suchergebnisse gut überblicken und bearbeiten können, passen Sie die Auftragsübersicht an. +
Sie können einstellen, wie viele Aufträge pro Seite in der Auftragsübersicht angezeigt werden. Die höchste Anzahl an Aufträgen pro Seite ist 400, die niedrigste 50. +
Nutzen Sie die Pfeile, um zur nächsten Seite oder zurück zu wechseln. Sie können die gewünschte Seitenziffer auch direkt eintragen und die Eingabetaste betätigen.

[#1410]
=== Auftragspositionen ein- oder ausblenden

In der Auftragsübersicht werden standardmäßig die Auftragspositionen mit angezeigt. So stehen Ihnen auf einen Blick die im Auftrag enthaltenen Artikel mit wichtigen Parametern, z.B. *Titel*, *Größe*, *Preis* zur Verfügung. Sie können die Auftragspositionen jedoch auch ausblenden. Sie können die Positionen entweder nur bei einzelnen Aufträgen oder bei allen ausblenden. Um die Positionen eines einzelnen Auftrages auszublenden, nutzen Sie das Pfeilsymbol *Artikelliste schließen". Um die Positionen für alle Aufträge auszublenden, folgen Sie den aufgeführten Schritten.

[.instruction]
Auftragspositionen für alle Aufträge ausblenden:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Wählen Sie im Tab *Filter* für den Filter *Artikelposition* die Einstellung *Nicht anzeigen*.
. Klicken Sie auf *Suchen*. +
→ Die Artikellisten der angezeigten Aufträge werden geschlossen.

[#1420]
=== Informationen und Symbole in der Auftragsübersicht verstehen

In der Auftragsübersicht werden je nach Zustand eines Auftrags verschiedene Symbole angezeigt, die im Folgenden kurz erläutert werden. Wenn Sie den Mauszeiger auf ein Symbol bewegen, wird Ihnen eine kurze Erläuterung, ein Tooltip, eingeblendet.

In der Titelzeile eines Auftrags sehen Sie mindestens wie Sie den Kunden bewertet haben, den *<<auftragsabwicklung/auftraege/auftraege-verwalten#, Status>>* des Auftrages, das Logo des *<<auftragsabwicklung/fulfillment/versand-vorbereiten#, Versanddienstleisters>>* und die *<<auftragsabwicklung/payment#, Zahlungsart>>*. Je nach Fortschritt des Auftrages erscheinen dort weitere Symbole. Wenn z.B. der Warenausgang gebucht, verschwindet das Symbol *Warenausgang buchen* und das Symbol für *Warenausgang gebucht* wird angezeigt. Beim Buchen des Warenausgangs wechselt auch der Status in Status 7. Anhand der Farbe der Statusanzeige erkennen Sie Aufträge mit gleichem Status auf einen Blick.

Die folgende Tabelle enthält eine Übersicht der möglichen Informationen. Einige Symbole erlauben Ihnen auch direkt Aktionen auszuführen. Beachten Sie, dass nie alle Symbole angezeigt werden, sondern nur die zum Bearbeitungsstand passenden.

.Mögliche Symbole in der Auftragsübersicht
[cols="1,3a"]
|====
|Tooltip des Symbols |Erläuterung

|*Auftragsstatus*
|Zeigt den aktuellen Auftragsstatus und erlaubt auch den Status zu ändern. Zum ändern, einfach auf den Status klickenund einen neuen wählen. +
**Wichtig**: Ein Auftragsstatus &gt;= 7 kann nicht verringert werden, ohne dass vorher die Buchung des Warenausgangs zurückgesetzt wird.

|*Versanddienstleister*
|Individuelles Symbol des zugeordneten Dienstleisters. Ein Symbol wird jedoch nur angezeigt, wenn im *<<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, Versandprofil>>* eine Markierung eingestellt wurde.

|*DHL-Packstation*
|Das Symbol wird nur angezeigt, wenn die Packstationsdaten korrekt im Auftrag hinterlegt sind. Es kann bei Aufträgen von Marktplätzen vorkommen, dass Packstationsdaten nicht korrekt sind, wenn der Marktplatz z.B. keine Validierung bereitstellt. In einem solchen Fall wird das Symbol nicht angezeigt, da aufgrund der falschen Daten nicht an eine Packstation geliefert werden kann.

|*Versandart* oder +
 *Versanddienstleisterservice*
|*Schnellversand* ist ein Service, der zusätzlich durch ein Symbol angezeigt wird

|*Zahlungsart*
|Individuelles Symbol der Zahlungsart

|*Warenausgang gebucht*
|Wird nur angezeigt, wenn der Warenausgang gebucht wurde. Falls nur der Status in Status 7 geändert wurde, wird das Symbol nicht angezeigt.

|*Mahnstufe*
|*<<auftragsabwicklung/payment/mediafinanz#30, Mahnstufen>>* können per Aktionsmanager zugeordnet werden

|*Markierung*
|Individuelle Auftragsmarkierung

|*Lieferland*
|ISO-Code für das Lieferland nach ISO-3166 Alpha 2

|*Währung*
|ISO-Code der Auftragswährung nach ISO 4217

|*Zahlungsstatus*
|Wird passend zur Zahlung als farbiger Balken und zusätzlich in einem Tooltip als Prozentwert angezeigt.

|*Auftragsbestätigung erstellen*
|Auftragsbestätigung direkt erstellen

|*Rechnung erstellen*
|Rechnung direkt erstellen

|*Zahlungseingang direkt buchen*
|Zahlung direkt zum Auftrag buchen. Der Betrag ist frei einstellbar. Der offene Rechnungsbetrag ist voreingetragen.

|*Lieferschein erstellen*
|Lieferschein direkt erstellen

|*Warenausgang buchen*
|Erlaubt den Warenausgang direkt zu buchen, wodurch der Bestand der Varianten reduziert wird, wenn Sie Bestand führen. Der Status der Auftrags ändert sich automatisch in Status 7.

|*Tracking-URL anzeigen*
|Die Tracking-URL dient zur Sendungsverfolgung eines Paketes. Die *<<auftragsabwicklung/fulfillment/versand-vorbereiten#840, Tracking-URL>>* müssen Sie beim Einrichten von Versanddienstleistern eintragen und speichern.

|*Notiz zum Auftrag erstellen*
|Erlaubt eine Notiz zum Auftrag zu verfassen sowie eine bereits vorhandene Notiz zu lesen. An einem Symbol ohne Plus ist erkennbar, dass bereits eine Notiz existiert.

|*Notizen zum Kunden*
|Erlaubt eine Notiz zum Kunden zu verfassen sowie eine bereits vorhandene Notiz zu lesen

|*E-Mail-Adresse des Kunden*
|Erlaubt über Ihr E-Mail-Programm direkt eine E-Mail an den Kunden des Auftrags zu senden

|*E-Mail-Service*
|Öffnet das Tab E-Mail-Vorlagen und erlaubt so direkt eine E-Mail-Vorlage an den Kunden zu senden oder bereits gesendete Vorlagen einzusehen.

|*Vorhandene Vorgänge anzeigen*
|Zeigt u.a. eine Liste von Retouren und Gutschriften mit Datum und Wert.

|*Warenbestand ermitteln*
|Lädt eine Warenbestandsübersicht für die im Auftrag enthaltenen Varianten. +
Über den Warenkorb sind Nachbestellungen möglich.

|*Artikelliste öffnen* oder *schließen*
|Erlaubt die Auftragspositionen eines Auftrags ein- oder auszublenden

|*Nachbestellung anzeigen*
|Öffnet die auftragsbezogene Nachbestellung im Menü *Nachbestellungen*

|*Rechnungsnummer*
|Öffnet die Rechnung wird

|*Artikel-ID* oder *Varianten-ID*
|Öffnet den Artikel oder die Variante im Menü *Artikel » Artikel bearbeiten*
|====

[#1500]
== Aufträge bearbeiten

Im Menü *Aufträge » Aufträge bearbeiten* werden Ihre Aufträge in einer Übersicht angezeigt. Klicken Sie auf die Auftrags-ID, um einen Auftrag zu öffnen und die Auftragseinstellungen zu ändern. Aufträge können so lange geändert werden, wie noch kein Dokument für einen Auftrag existiert. Die Einstellungen verteilen sich auf mehrere Tabs, die auf dieser Handbuchseite erläutert werden.

[#1510]
=== Infos und Aktionen in der Auftragsübersicht

Im Menü *Aufträge » Aufträge bearbeiten* werden alle Aufträge mit den wichtigsten Informationen zu jedem Auftrag angezeigt. Neben Informationen zum Kunden, dem Auftragsstatus, dem Zahlungsstatus sowie den Artikeln des Auftrags erkennen Sie z.B. auf einen Blick, ob der Warenausgang gebucht und ob eine Rechnung erzeugt wurde. So haben Sie die wichtigsten Vorgänge im Blick, ohne den Auftrag zu öffnen. Zeigen Sie mit dem Mauszeiger auf die Symbole und Angaben, um Tooltips mit weiteren Informationen anzuzeigen.

Durch Klick auf ein *Icon* öffnen Sie außerdem bestimmte Bereiche des Auftrags. Klicken Sie z.B. auf *Warenbestand*, um den aktuellen Warenbestand der Artikel abzufragen und ggf. Nachbestellungen auszulösen.

In der Auftragsübersicht passen Sie außerdem bei Bedarf den *Status*, das *Porto*, die *Artikeldaten* oder den *Rabatt* an. Unten wird beispielhaft das Vorgehen bei einer Statusänderung beschrieben.

[.instruction]
Auftragsstatus in der Auftragsübersicht anpassen:

. Klicken Sie auf den Button *Status*. +
→ Eine Liste mit den verfügbaren Status wird angezeigt.
. Wählen Sie den gewünschten Status. +
. Klicken Sie auf *Speichern*, um die Änderung zu sichern. +
→ Der Status wird aktualisiert.

[#1520]
=== Auftrag öffnen und bearbeiten

Das Bearbeitungsmenü des Auftrags öffnen Sie, indem Sie auf die Titelzeile in der Auftragsliste klicken. Der Auftrag wird dann in einem eigenen Tab geöffnet. Die verschiedenen Bereiche sind in weitere Tabs unterteilt, die auf dieser Handbuchseite beschrieben werden. Ein geöffneter Auftrag ist an der *ID* im Titel des Tabs erkennbar.

[NOTE]
.Einstellungen bzw. Änderungen speichern
====
Die meisten Tabs eines Auftrags enthalten kein Speichern-Symbol. In diesen Tabs werden die geänderten Einstellungen automatisch gespeichert, z.B. beim Ändern der Markierung oder Mahnstufe im Tab *Übersicht*. Sie können das Tab wechseln oder den Auftrag gänzlich schließen und erneut öffnen, ohne dass die vorgenommenen Einstellungen verloren gehen. Einige Tabs enthalten jedoch ein Speichern-Symbol, z.B. das Tab *Einstellungen*. Hier können Sie das Tab wechseln, ohne Ihre Änderungen zu verlieren. Sie müssen jedoch Ihre Änderungen speichern, bevor sie den Auftrag schließen.
====

[IMPORTANT]
.Grundeinstellungen zur Auftragsbearbeitung durch variable Benutzer
====
Damit variable Benutzer Aufträge öffnen können, müssen im Menü *<<auftragsabwicklung/auftraege/grundeinstellungen#, **System » Aufträge » Einstellungen>>* die Standard-Status für *Retouren* und *Gutschriften* gespeichert werden. In der Grundeinstellung ist dort kein Status voreingestellt. Außerdem müssen variable Benutzer im Benutzerprofil unter *<<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#110, Berechtigung » Tab: Menü » Bereich: Aufträge>>* für die Bearbeitung von Aufträgen berechtigt sein.
====

[TIP]
.Aufträge über POS (Kasse) sind nur eingeschränkt bearbeitbar
====
Aufträge, die über <<omni-channel/pos/pos-kassenbenutzer#7, POS (Kasse)>> in das System gelangen, sind aus Gründen der Rechtssicherheit zur Bearbeitung gesperrt. Nur wenige Einstellungen lassen sich bearbeiten.
====

[#1530]
=== Tab: Übersicht

Im Tab *Übersicht* eines Auftrags finden Sie die wichtigsten Parameter zu einem Auftrag. Sie erhalten auf einen Blick Informationen zu Preis, Versandkosten, Mehrwertsteuer, Status etc.

[TIP]
.Tipp: Werte ändern
====
Änderbare Werte erkennen Sie an einer Dropdown-Liste oder an einem *Stift*. Klicken Sie auf einen Stift, um den betreffenden Parameter zu ändern (z.B. Bild 16, links oben unter *Gewicht*).
====

.Optionen im Tab *Übersicht* eines Auftrags
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Auftrag-ID*
|ID des Auftrags. Diese wird automatisch vergeben und ist nicht änderbar.

|*Kunden-ID*
|ID des Kunden.

|*Kaufabwicklung*
|Öffnet den Auftrag im Bereich *Mein Konto* des Webshops.

|*Eingabe*
|Datum des Auftragseingangs, d.h. wann der Auftrag angelegt wurde bzw. im System eingegangen ist. Das Eingabedatum kann manuell geändert werden, jedoch nur so lange keine Dokumente für den Auftrag existieren.

|*IP-Adresse*
|Zeigt optional die IP-Adresse des Kunden an. +
Die Option *IP-Adresse des Käufers* wird im Menü *<<omni-channel/online-shop/webshop-einrichten/bestellvorgang#, System » Mandant » Mandant wählen » Bestellvorgang » Einstellungen>>* aktiviert bzw. deaktiviert.

|*Markierung*
|Auf Wunsch dem Auftrag eine Markierung zuweisen. Mit Markierungen können Aufträge kategorisiert und so z.B. mit dem Suchfilter gesucht oder für automatische Funktionen, z.B. Ereignisaktionen, verwendet werden.

|*Mahnstufe*
|Wenn ein Kunde den Auftrag nicht bezahlt, werden hier verschiedene Mahnstufen eingestellt. Diese Mahnstufen werden für automatische Prozesse im Mahnvorgang verwendet. +
Ein Beispiel für das Verwenden von Mahnstufen finden Sie auf der Handbuchseite *<<auftragsabwicklung/payment/mediafinanz#, mediafinanz>>*.

|*Voraussichtlicher Versand*
|Das Datum des voraussichtlichen Versands wird aus dem Datum ermittelt, das bei einer *<<warenwirtschaft/nachbestellungen-verwalten#, Nachbestellung>>* als Liefertermin hinterlegt wurde. Damit der voraussichtliche Versand angezeigt wird, müssen die Nachbestellung sowie der Liefertermin des Artikels bestätigt sein und der Auftrag muss sich in *Status 4* befinden. +
*__Wichtig:__* Die weitere Option *Versanddatum* im Tab *Einstellungen* hat eine andere Funktion, siehe Tabelle 2.

|*Kopieren*
|Kopiert den Auftrag und legt in einem separaten Auftrags-Tab einen neuen Auftrag mit eigener ID an.

|*Löschen*
|Löscht den Auftrag. Es erfolgt eine Sicherheitsabfrage. +
Das Löschen-Icon wird in folgenden Fällen nicht angezeigt: +
- Wenn der Benutzer nicht *<<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90, berechtigt>>* ist, Aufträge zu löschen +
- Nach dem Buchen des Warenausgangs +
- Wenn ein Lieferauftrag angelegt wurde +
Generell sollten Aufträge nicht gelöscht werden. Durch die Verknüpfung mit Artikeln, Versandeinstellungen und weiteren Funktionen, wie Stornierungen und Retouren, kann es nach dem Löschen zu Fehlern an den Verknüpfungspunkten kommen. Neu angelegte Aufträge können jedoch problemlos gelöscht werden.

|*Teilen*
|Teilt den Auftrag. Es erfolgt eine Abfrage, welche Artikel in den Teilauftrag übernommen werden sollen.

|*Retoure; Gutschrift; Gewährleistung*
|Auf die Dropdown-Liste klicken, um das Auftragsdokument anzulegen oder zu suchen.

|*Neuer Auftrag*
|Legt einen *<<auftragsabwicklung/auftraege/auftraege-verwalten#neuer-auftrag, neuen Auftrag>>* für den Kunden an. Darin werden automatisch Standardeinstellungen vorgenommen, die ggf. angepasst werden müssen.

|*Rechnungsanschrift*
|Auf das *kleine Plus* klicken, um die Rechnungsanschrift einzublenden. Auch Telefonnummer, E-Mail-Adresse und ggf. eBay-Kontoname des Kunden werden angezeigt.

|*Lieferanschrift*
|Auf das *kleine Plus* klicken, um die Lieferanschrift einzublenden. Ist die Lieferanschrift mit der Rechnungsanschrift identisch, wird *Lieferanschrift* durchgestrichen angezeigt. +
Bei Bedarf auf *Neue Lieferanschrift* klicken, um eine neue Lieferanschrift anzulegen, oder auf *Alle Lieferanschriften auflisten*, um eine Lieferanschrift zu wählen. +
*Lieferanschrift exportieren* = Exportiert die Lieferanschrift im für den gewünschten Versanddienstleister ausgewählten Export-Format.

|*Bankdaten*
|Auf das *kleine Plus* klicken, um die *<<auftragsabwicklung/payment/bankdaten-verwalten#, Bankdaten>>* des Kunden einzublenden und bei Bedarf zu bearbeiten.

|*Kundennotizen*
|Zeigt die zum Kunden gespeicherten Kundennotizen an. Auf *Neue Notiz* klicken, um eine Kundennotiz anzulegen. Im Bearbeitungsfenster werden unten die bisherigen Notizen in Gelb angezeigt. Neue Notizen werden mit den üblichen Editor-Funktionen formatiert. Hier gespeicherte Notizen werden sowohl in weiteren Aufträgen des Kunden als auch im Tab *Notizen* der Kundendaten angezeigt.

|*Auftragsnotiz*
|Zeigt die zum Kunden gespeicherten Auftragsnotizen an. Auf *Neue Notiz* klicken, um eine Auftragsnotiz anzulegen. Neue Notizen werden mit den üblichen Editor-Funktionen formatiert.

|*Statushistorie*
|Zeigt eine Liste aller Statusänderungen des Auftrags an.

|*Zahlungshistorie*
|Zeigt Details zu Zahlungen wie Zahlungsart, Währung, Zahlungs-ID oder Datum.

|*Artikelpositionen*
|Zeigt Informationen zu den Artikelpositionen des Auftrags an.

|*Bearbeiten*
|Bei Bedarf die Artikeldaten bearbeiten, d.h. Artikelmenge, Artikeldetails, Preise, Rabatte und Mehrwertsteuer-Sätze.

|*Hinzufügen*
|Über die integrierte Artikelsuche bei Bedarf weitere Artikel zum Auftrag hinzufügen.

|*Lagerort zuordnen*
|Ordnet der Auftragsposition einen Lagerort zu. Ist für einen Artikel mehr als ein Lagerort hinterlegt, werden die Lagerorte anhand der Position priorisiert. Wurde kein Lagerort hinterlegt, wird der *Standard-Lagerort* zugeordnet. +
Die Zuordnung des Lagerorts ist für Pick-/Packlisten relevant. +
*__Tipp__*: Lagerorte können Artikeln auch per *<<basics/automatisierung/ereignisaktionen#konfiguration, Ereignisaktion>>* zugeordnet werden.

|*Zuordnung lösen*
|Hebt die aktuelle Zuordnung des Lagerorts auf. Durch erneutes Klicken auf *Lagerort zuordnen* (siehe oben) kann eine neue Zuordnung vorgenommen und diese so an aktuelle Lagergegebenheiten angepasst werden.
|====

Aufträge teilen

Aufträge teilen Sie im Menü *<<auftragsabwicklung/auftraege/auftraege-verwalten#30, Aufträge » Aufträge bearbeiten » Auftrag öffnen » Tab: Übersicht>>*. Ein Auftrag darf nur unter folgenden Bedingungen geteilt werden:

* Es ist noch kein Zahlungseingang erfolgt.
* Es wurde kein Warenausgang gebucht.
* Es wurde keine Rechnung erzeugt.

[#1540]
=== Tab: Einstellungen

Im Tab *Einstellungen* sind die grundlegenden Parameter eines Auftrags hinterlegt, wie *Status*, *Herkunft* oder *Zahlungsart*.

.Optionen im Tab **Einstellungen** eines Auftrags
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Status; +
Auftragstyp; +
Eigner; +
Herkunft; +
Mandant (Shop)**
| +
+
Diese Optionen werden je nach Zustand bzw. Gegebenheiten angezeigt, können jedoch geändert werden.

|*Lager*
|Lager des Artikels des Auftrags bzw. das Hauptlager. Bei Bedarf auf *Lagerkorrektur* klicken, um das Lager zu ändern.

|*Status*
|Der Auftragsstatus *[7] Warenausgang gebucht* kann nicht in einen niedrigeren Status geändert werden. Grund ist, dass die Ware bereits verschickt wurde. Sollte dies trotzdem gewünscht sein, muss die Buchung des Warenausgangs vorher zurückgesetzt werden. Danach ist die Änderung in einen niedrigeren Auftragsstatus möglich.

|*Warenausgang*
|Zeigt an, ob der Warenausgang gebucht wurde und ggf. das Buchungsdatum. +
Bei Bedarf auf *Warenausgang* klicken, um den Warenausgang manuell zu buchen.

|*Versanddatum*
|Das Versanddatum wird vom Artikel aus der Option **Erscheinungsdatum** übernommen und ist damit eine Funktion für *<<auftragsabwicklung/auftraege/auftraege-verwalten#vorbestellungen, Vorbestellungen>>*. Sind mehrere vorbestellte Artikel im Auftrag vorhanden, wird das am weitesten in der Zukunft liegende Datum hier übernommen. Das Datum ist manuell änderbar.

|*Rückgabedatum*
|Das Datum einer Retoure hinterlegen, wenn Artikel des Auftrags zurückgegeben wurden. Dient als Information zu einer Retoure, damit diese nicht extra geöffnet werden muss.

|*Währung*
|Die Währung des Auftrags.

|*Zahlungsart; +
Versanddienstleister; +
Versandprofil &amp; Porto*
|Diese Optionen werden je nach Zustand bzw. Gegebenheiten angezeigt, können jedoch geändert werden. +
Um Änderungen vorzunehmen, eine *Zahlungsart* aus der Dropdown-Liste wählen bzw. auf den *Stift* klicken, um die Versandoptionen zu ändern.

|*Zahlungsziel*
|Die Werte für *Valuta (Tage)*, *Skonto (Tage)* bzw. *Skonto (%)* werden einzeln oder kombiniert hinterlegt und damit die Zahlungsbedingungen gestaltet. Wenn die Werte in den <<crm/kontakte-verwalten#100, Kundendaten>> hinterlegt sind, werden sie vom System automatisch übernommen und hier eingesetzt, können jedoch geändert werden.

|*Versanddienstleister*
|Der Versanddienstleister, über den die Artikel des Auftrags versendet werden.

|*Versandprofil &amp; Porto*
|Das Versandprofil und die Portokosten des Auftrags.

|*Ext. Auftragsnummer*
|Bei Aufträgen, die z.B. aus einem externen System stammen, die externe Auftragsnummer eintragen.

|*Zeichen Kunde*
|Zeigt ein Zeichen bzw. einen Text an, den der Kunde bei der Bestellung hinterlegen kann, wenn das Feld **Ihr Zeichen** für den Bestellvorgang sichtbar ist.
|*Pakete*
|Anzahl der zum Auftrag gehörenden Pakete. +
__**Wichtig**__: Dieser Eintrag ist unabhängig von der im Versand-Center eingestellten Paketanzahl. Wenn Sie die Anzahl der Pakete verändern möchten, passen Sie dies im Versand-Center an.

|*Paketnummer*
|Paketnummer des Versandpakets +
Wenn eine Paketnummer hinterlegt wurde, kann das Paket über *Vorschau* verfolgt werden. Allerdings nur, wenn unter *<<auftragsabwicklung/fulfillment/versand-vorbereiten#800,System » Aufträge » Versand » Optionen » Tab: Versanddienstleister>>* ein entsprechender Tracking-Code hinterlegt wurde. Sonst wird das Vorschau-Symbol nicht angezeigt.
|====

[#1550]
=== Tab: Mail

Im Tab *Mail* sind alle E-Mail-Vorlagen verfügbar, die Sie unter *<<crm/e-mails-versenden#1200, System » Mandant » Mandant wählen » E-Mail » Vorlagen>>* konfiguriert haben und die gemäß des Template-Typs für Aufträge sichtbar sind. Sie können diese Vorlagen per manueller Aktion an den Kunden schicken, wenn z.B. eine außerplanmäßige E-Mail nötig ist bzw. eine, die nicht durch eine automatische Aktion erfolgt. Gehen Sie wie unten beschrieben vor, um eine E-Mail-Vorlage zu verschicken.

[.instruction]
E-Mail-Vorlage verschicken:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag.
. Klicken Sie auf das Tab *Mail*.
. Wählen Sie ggf. die *Sprache*.
. Wählen Sie im Tab *E-Mail-Vorlagen* das Tab, das die gewünschte E-Mail-Vorlage enthält.
. Markieren Sie die Vorlage.
. Klicken Sie auf *Direkter E-Mail-Versand*. +
→ Die E-Mail wird versendet.
. Warten Sie, bis der Versand durch eine Meldung bestätigt wird.

Bei nicht erfolgreichem E-Mail-Versand prüfen Sie die *<<crm/e-mails-versenden#, Zugangsdaten>>*. Im Menü *<<basics/datenaustausch/api-log#, Daten » API-Log>>* werden die Fehlermeldungen zum Vorgang *E-Mail* gespeichert.

[IMPORTANT]
.Kunden ein neues Passwort senden
====
Die E-Mail-Vorlage *Sende Kunde neues Passwort* ist für den Versand aus einem Auftrag nicht verwendbar. Diese E-Mail-Vorlage versenden Sie im Datensatz des Kunden. Dort ist im Tab *Einstellungen* das Tab *Passwort* verfügbar, wenn sich ein Kunde im Webshop registriert hat. Hier ist der Versand dieser E-Mail-Vorlage vorgesehen.
====

Das Tab *Gesendete E-Mails* bietet eine Übersicht der gesendeten E-Mail-Vorlagen. Dort werden *Datum*, *Empfänger*, die Bezeichnung der *Vorlage* sowie die *Auftrags-ID* aufgeführt. Es werden alle an den Kunden gesendeten E-Mails aufgelistet, auch die von anderen Aufträgen.

[#1560]
=== Tab: Zahlung

Im Tab *Zahlung* sehen Sie alle Zahlungen und Teilzahlungen, die zum Auftrag gehören. Über Filter suchen Sie außerdem nach einzelnen Zahlungen des Auftrags. Im Tab *Zahlungsverkehr* werden in der obersten Leiste der Rechnungsbetrag, der bereits bezahlte Rechnungsbetrag sowie der noch offene Rechnungsbetrag angezeigt. So haben Sie anhand dieser Zahlen direkt einen Überblick. Außerdem buchen Sie in diesem Tab Zahlungen manuell über den Button *Zahlung buchen*.

[TIP]
.Fehlende Zahlungseingänge
====
Wenn nicht alle Zahlungen des Auftrags angezeigt werden, ändern Sie den Filter *Eingangsdatum von*, um den Zeitraum, ab dem gesucht wird, anzupassen.
====

Details zur manuellen Buchung von Zahlungen finden Sie auf der Handbuchseite *<<auftragsabwicklung/payment/zahlungen-verwalten#, Zahlungen verwalten>>*.

[#1570]
=== Tab: Belege

Im Tab *Belege* erzeugen Sie Belege, d.h. z.B. eine Auftragsbestätigung, einen Lieferschein oder eine Rechnung.
Nachdem Sie Dokumente zu einem Auftrag erzeugt haben, kann das Eingabedatum des Auftrags nicht mehr geändert werden.
Die Dokumente werden anhand von Dokumentenvorlagen erstellt, die im Menü *<<auftragsabwicklung/auftraege/auftragsdokumente#, Einstellungen » Aufträge » Dokumente>>* hinterlegt wurden. Prüfen Sie daher vor der Erstellung der Belege bzw. auch bei einer Fehlermeldung, ob Sie die Dokumentenvorlagen erstellt haben.

[TIP]
.Tipp: Dokumentenvorlagen kopieren
====
Wenn Sie bei der Einrichtung der *<<auftragsabwicklung/auftraege/auftragsdokumente#20, Dokumentenvorlagen>>* Zeit sparen möchten, kopieren Sie sie von einer bereits konfigurierten Dokumentenvorlage und passen sie nach Bedarf an.
====

Die Belege werden jeweils vor der Erstellung konfiguriert. Sie können je nach Beleg verschiedene Parameter anpassen, z.B. bei einer Rechnung das Datum, das *Zahlungsziel*, ob Skonto angerechnet werden soll und ob der Warenausgang gebucht werden soll. Außerdem kann ein Statuswechsel bei Erzeugung des Belegs veranlasst werden.

[#1580]
=== Tab: Kunde

Im Tab *Kunde* wird der <<crm/kontakte-verwalten#, Kontaktdatensatz>> angezeigt. Sie können diese Informationen bearbeiten.

[#1590]
=== Tab: Tickets

Im Tab *Tickets* werden *<<crm/ticketsystem-nutzen#, Tickets>>* des Kunden angezeigt. Sie können diese Tickets direkt bearbeiten, ohne ins Ticketsystem zu wechseln.

[#1600]
=== Tab: Aufträge

Im Tab *Aufträge* finden Sie die weiteren Aufträge des Kunden des betreffenden Auftrags. Sie können die Aufträge des Kunden dort auch bearbeiten.

[#1610]
=== Tab: Waren

Im Tab *Waren* werden die *<<warenwirtschaft/warenbestaende-verwalten#, Warenbestandsdaten>>* der Artikel angezeigt, die in dem Auftrag enthalten sind. Das Tab bietet die volle Funktionalität des Menüs *Warenbestand* mit Ausnahme der Filterfunktionen. Sie können Warenbestände einsehen und bei Bedarf konfigurieren.

[#1620]
=== Tab: Nachbestellung

Im Tab *Nachbestellung* wählen Sie Auftragspositionen für eine Nachbestellung. Dabei wählen Sie, ob eine Nachbestellung nur für den Auftrag erzeugt werden soll oder ob eine Nachbestellung erzeugt werden soll, der auch nachbestellte Auftragspositionen aus anderen Aufträgen hinzugefügt werden. +
Eine Bedingung in beiden Fällen ist, dass der Lieferant (Kunde) und das Lager bei allen Positionen gleich sind. Ist das nicht der Fall, wird für jede Lieferanten-/Lager-Konstellation eine separate Nachbestellung erzeugt.

[NOTE]
.Lieferanten hinterlegen!
====
Damit eine Bestellung möglich ist, muss für jeden Artikel ein Lieferant hinterlegt sein.
====

[#1630]
==== Auftragspositionen wählen

Gehen Sie wie unten beschrieben vor, um einzelne Positionen bzw. alle Positionen eines Auftrags für die Nachbestellung zu wählen.

[.instruction]
Einzelne Positionen für die Nachbestellung wählen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den gewünschten Auftrag.
. Klicken Sie auf das Tab *Nachbestellung*.
. Wählen Sie die *Varianten*, die Sie nachbestellen möchten.
. Klicken Sie auf *Markierte Positionen nachbestellen*. +
→ Eine allgemeine, offene Nachbestellung wird erzeugt, in die neben den markierten Positionen auch Auftragspositionen aus anderen Aufträgen überführt werden, wenn diese über diesen Button gewählt wurden. Die Teilmengen werden unter *Menge* angezeigt.

Wenn Sie bestimmte Artikelpositionen für die Nachbestellung gewählt haben, wird *Alle Positionen nachbestellen* deaktiviert und ist nicht mehr wählbar.

[.instruction]
Alle Positionen für eine Nachbestellung wählen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den gewünschten Auftrag.
. Klicken Sie auf das Tab *Nachbestellung.*
. Klicken Sie auf *Alle Positionen nachbestellen*. +
→ Es wird nur für diesen Auftrag eine Nachbestellung erzeugt, die alle Positionen des Auftrags enthält. Die Teilmengen werden unter *Menge* angezeigt.

[#1640]
==== Nachbestellung ausführen

[TIP]
.Bedeutung der Angaben unter Menge
====
In der Spalte *Menge* sehen Sie auf einen Blick die gelieferte Menge (grüne Zahl), die offene Menge (rote Zahl) und die bestellte Menge. +
Unter *geliefert* werden Teilmengen angezeigt, wenn diese als Teillieferung in der Nachbestellung unter *Status* gebucht werden. +
====

Nachdem Sie die Auftragspositionen gewählt haben, führen Sie nun die eigentliche Nachbestellung aus. Gehen Sie dazu wie folgt vor:

[.instruction]
Nachbestellung ausführen:

. Klicken Sie im Tab *Nachbestellung* des Auftrags auf einen *Warenkorb*. +
→ Das Menü *Nachbestellung* wird geöffnet. Im Tab *Base* der Nachbestellung werden die bestellten Artikel im Bereich *Artikeldaten* angezeigt.
. Klicken Sie im Bereich *Grunddaten* bei der Option *Bestellen* auf das *Zahnrad*. +
→ Die Bestellung wird ausgeführt. Die Bestelldaten werden auch im Auftrag im Tab *Nachbestellung* angezeigt.

[TIP]
.EK und Menge anpassen
====
Sie können im Bereich *Artikeldaten* des Tabs *Base* die Optionen *EK* und *Menge* anpassen, bevor die Nachbestellung ausgeführt wird.
====

Weitere Details zur Bearbeitung der Nachbestellung und wie Sie z.B. Teilmengen buchen finden Sie auf der Handbuchseite *<<warenwirtschaft/nachbestellungen-verwalten#, Nachbestellungen>>*.

[#1650]
==== Variantenmengen einer Nachbestellung erhöhen

Bei noch offenen Nachbestellungen können Sie die Mengen für Varianten erhöhen. Dies ist für Werte möglich, für die bei der *<<artikel/artikel-verwalten#410, Mengenverteilung>>* prozentuale Anteile hinterlegt wurden. Gehen Sie wie folgt vor, um die Menge für Varianten zu erhöhen.

[.instruction]
Menge für Variante erhöhen:

. Klicken Sie auf *Mengen für Varianten erhöhen*.
. Wählen Sie die *ID der Nachbestellung* und den *Artikel* aus den Dropdown-Listen.
. Wählen Sie das *Attribut* und den *Wert*.
. Tragen Sie die *Menge* ein.
. Klicken Sie auf *Menge erhöhen*.
. Wiederholen Sie diese Schritte für jede gewünschte weitere Variante, um die Mengen zu erhöhen.

[#1660]
=== Tab: Lief

Im Tab *Lief* werden *<<auftragsabwicklung/auftraege/auftraege-verwalten#lieferauftrag, Lieferaufträge>>* erstellt. Sie sehen dort die Artikelpositionen des Auftrags, die noch nicht in Lieferaufträge überführt wurden.

[.instruction]
Lieferaufträge manuell anlegen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den gewünschten Auftrag.
. Klicken Sie auf das Tab *Lief*.
. Tragen Sie in das Feld *LiefAufMenge* (Menge für den Lieferauftrag) die Menge ein, die in den Lieferauftrag überführt werden soll. +
→ Die eingetragene Menge darf nicht größer sein als die unter *NZMenge* (nicht zugeordnete Menge) angezeigte Menge.
. Klicken Sie auf das *Zahnrad*, um den Lieferauftrag anzulegen.

[NOTE]
.Lieferaufträge automatisch anlegen
====
Klicken Sie auf *Lieferauftrag automatisch anlegen*, um die Aufträge entsprechend der unter *<<auftragsabwicklung/auftraege/auftraege-verwalten#lieferauftrag, System » Aufträge » Auftragstypen » Lieferauftrag>>* im Feld *Aufträge in Lieferaufträge splitten nach* gewählten Einstellung anzulegen. Es werden alle Auftragspositionen in Lieferaufträge geteilt. Diese Funktion können Sie nur nutzen, wenn noch kein Lieferauftrag zu dem Auftrag besteht.
====

Für die in einem Lieferauftrag enthaltene Menge wird die Bestandsreservierung beim Anlegen eines Lieferauftrags vom Hauptauftrag auf den Lieferauftrag übertragen. Werden Lieferaufträge einzeln angelegt und im Hauptauftrag sind noch Artikel vorhanden, werden diese Artikel ebenfalls reserviert.

[TIP]
.Tipp: Auftragspositionen im Hauptauftrag bearbeiten
====
Auftragspositionen können zum Hauptauftrag hinzugefügt oder daraus gelöscht werden. Allerdings können nur Auftragspositionen, die nicht in Lieferaufträgen enthalten sind, aus dem Hauptauftrag gelöscht werden. Die Menge der Artikel im Hauptauftrag lässt sich erhöhen oder verringern. Sie sollten jedoch nur nicht zugeordnete Mengen löschen. Technisch möglich ist auch das Löschen von Positionen, die bereits in einem Lieferauftrag enthalten sind. Dies sollten Sie jedoch vermeiden.
====

[#1670]
=== Rechnung korrigieren und stornieren

Wenn Sie oder Ihr Kunde nachträglich feststellen, dass eine Angabe auf der Rechnung fehlerhaft ist und sie diese korrigieren möchten, erstellen Sie einen Stornobleg und erzeugen Sie eine neue Rechnung.
Durch Stornieren der Rechnung können Änderungen schnell nachvollzogen werden, da sowohl die alte Rechnung, der Stornobeleg und die neue Rechnung vorhanden sind. Wenn Sie den gesamten Auftrag stornieren möchten, nutzen Sie den Auftragsstatus *storniert*. Wenn Sie den Auftrag bearbeiten möchten und einige Angaben korrigieren, nutzen Sie den Stornobeleg.

[#1680]
==== Vorlage Stornobeleg einrichten

Richten Sie sich zunächst die Vorlage für das Dokument Stornobeleg ein. Der schnellste Weg ist in diesem Fall das Übernehmen der Einstellungen aus der Standard-Dokumentvorlage oder das Kopieren der Einstellungen einer Rechnungsvorlage.  +
Im Folgenden wird kurz das Übernehmen der Standard-Dokumentvorlage beschrieben.

[.instruction]
Vorlage einrichten:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Stornobeleg*.
. Wechseln Sie in das Tab *Transfer*.
. Klicken Sie unter *Einstellungen aus Standard-Dokumentenvorlage übernehmen* auf *Übernehmen*.

Da die Einstellungen der Vorlage für Stornobelege mit den Einstellungen der Vorlage für Rechnungen übereinstimmen, finden Sie nährere Erläuterungen zu den einzelnen Einstellungen auf der Seite *<<auftragsabwicklung/auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnungen erzeugen>>*.

[#1690]
==== Rechnung korrigieren

Eine Rechnung korrigieren Sie, indem Sie sie zunächst stornieren. Das Stornieren einer Rechnung dient der nachvollziehbaren Korrektur von rechnungsrelevanten Daten und nicht der Stornierung eines Auftrages. Anschließend kann der Auftrag wieder bearbeitet werden und eine neue Rechnung erzeugt werden.

[.instruction]
Rechnung korrigieren:

.  Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
.  Öffnen Sie den Auftrag, dessen Rechnun Sie stornieren möchten.
.  Wechseln Sie in das Tab *Belege*.
.  Wählen Sie aus der Dropdown-Liste *Beleg erstellen* den *Stornobeleg*.  +
→ Ein Fenster mit optionalen Einstellungen wird geöffnet.
. *Speichern* Sie die Einstellungen.  +
→ Der Stornobeleg wird erzeugt und die Auftragseinstellungen entsperrt.
.  Bearbeiten Sie jetzt die Daten, die Sie korrigieren möchten.  +
→ Tragen Sie z.B. eine Umsatzsteueridentifiaktionsnummer in der Rechnungsanschrift nach.
.  Wechseln Sie wieder in das Tab *Belege*.
.  Wählen Sie aus der Dropdown-Liste *Beleg erstellen* die *Rechnung*.  +
→ Ein Fenster mit optionalen Einstellungen wird geöffnet.
. *Speichern* Sie die Einstellungen.  +
→ Die Rechnung wird erzeugt und die Auftragseinstellungen gesperrt.

[#1700]
==== Gruppenfunktionen nutzen und mehrere Aufträge bearbeiten

plentymarkets hält viele Hilfsmittel für bestmögliche Produktivität in der Auftragsbearbeitung bereit. Die beschriebene Gruppenfunktion gehört dazu. Sie können damit eine oder mehrere Aktionen an mehreren Aufträgen gleichzeitig ausführen und so viele manuelle Eingaben und damit verbundene mögliche Eingabefehler vermeiden.

Ein Praxisbeispiel verdeutlicht die Anwendungsmöglichkeiten der Gruppenfunktion: Ein begehrter Artikel in Ihrem Shop ist vorübergehend nicht lieferbar, es liegen aber bereits eine ganze Reihe von Bestellungen dafür vor. Gegen solche Lieferverzögerungen sind Händler in aller Regel machtlos, müssen aber die betroffenen Kunden schnellstmöglich über einen solchen Umstand informieren. Von Kunden, die bereits per Vorkasse bezahlt haben, ist verständlicherweise wenig Geduld zu erwarten.

Mit der Gruppenfunktion ist diese Aufgabe schnell erledigt: Suchen Sie mithilfe der **Artikel-ID** oder der *Artikelbezeichnung* alle Aufträge im Status *ALLE &lt; 7*, denn Ihre Aktion ist nur für die Aufträge relevant, bei denen der Warenausgang noch nicht erfolgt ist. Hat Ihr System alle Aufträge gefunden, wählen Sie unter *Gruppenfunktion* die Option *E-Mail-Service* aus, um Ihre Kunden per E-Mail zu erreichen. Sobald eine Gruppenfunktion ausgewählt wird, erscheint ein neues Fenster mit spezifischen Einstellungen.

Im Beispiel ist der Kunde der E-Mail-Empfänger. Eine *<<crm/e-mails-versenden#1200, E-Mail-Vorlage>>* müssen Sie vorher selbst erstellt haben. Eine **Markierung** zu setzen ist nicht notwendig, aber durchaus sinnvoll. Bevor Sie die Aktion über *Anwenden* ausführen, überzeugen Sie sich nochmals davon, dass alle gewünschten Aufträge mit einem Häkchen ausgewählt wurden.

[TIP]
.Status &gt;= 7
====
Beachten Sie, dass ein *Auftragsstatus &gt;= 7* nicht verringert werden kann, ohne dass vorher die Buchung des Warenausgangs zurückgesetzt wird. Für Aufträge mit Auftragsstatus ab Status 7 müssen Sie vorher den *Warenausgang* per Gruppenfunktion rückbuchen.
====

Mit der *Gruppenfunktion* ist es möglich, Prozesse für eine größere Menge an Aufträgen gleichzeitig auszuführen. Damit werden Vorgänge, z.B. eine Statusänderung oder ein E-Mail-Service, auf alle markierten Aufträge angewendet. Sie können auch bestimmte Aufträge per Gruppenfunktion löschen. Die Gruppenfunktion ist besonders zu empfehlen, wenn viele Aufträge bearbeitet werden müssen und die individuelle Bearbeitung sehr zeitaufwändig wäre.

Nachfolgend finden Sie ein Beispiel für die Verwendung der Gruppenfunktion.

[.instruction]
Beispiel Warenausgang per Gruppenfunktion buchen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Markieren Sie die *Aufträge*, für die Warenausgang per Gruppenfunktion gebucht werden soll.
. Klicken Sie auf *Gruppenfunktion*.
. Markieren Sie die Option *Warenausgang buchen*.
. Wählen Sie das *Datum* und die *Uhrzeit*. +
→ Für das Datum wird automatisch das aktuelle Datum gewählt, dies ist jedoch änderbar. Die Wahl des Datums ist bei dieser Gruppenfunktion Pflicht.
. Klicken Sie auf *Anwenden*, um die Aktion auszuführen.

[IMPORTANT]
.Grundeinstellungen zur Auftragsbearbeitung durch variable Benutzer
====
Damit variable Benutzer Aufträge öffnen können, müssen im Menü *<<auftragsabwicklung/auftraege/grundeinstellungen#, System » Aufträge » Einstellungen>>* die Standard-Status für *Retouren* und *Gutschriften* gespeichert worden sein. In der Grundeinstellung ist dort kein Status voreingestellt.
Außerdem müssen diese Benutzer für die Erstellung und Bearbeitung von Aufträgen im Benutzerprofil unter *<<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#110, Berechtigung » Tab: Menü » Bereich: Aufträge>>* berechtigt werden.
Damit variable Benutzer Aufträge der Typen *Retoure*, *Gewährleistung* und *Reparatur* anlegen können, müssen sie für die im Menü *<<auftragsabwicklung/auftraege/grundeinstellungen#, System » Aufträge » Einstellungen>>* hinterlegten Standard-Status dieser drei Auftragstypen berechtigt sein. Die Berechtigung erfolgt im *Benutzerprofil* des variablen Benutzers unter *<<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#100, Berechtigung » Tab: Sichtbarkeiten>>*.
====
