= Buchhaltung
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Buchhaltung, Preise runden
:position: 10

Erfahren Sie welche Einstellungen, die die Buchhaltung beeinflussen, es in plentymarkets gibt und in welchem Menü diese sich befinden.
Hierzu zählen in plentymarkets Umsatzsteuersätze, Währungen, Umrechnungskurse, die Berechnung von Auftragspreisen , Buchhungsschlüssel, Erlöskonten, Debitorenkonen, aber auch Dokumente. +
Die genaue Einrichtung von Dokumenten wird auf einer anderen Seite ausführlich beschrieben.

== Grundlagen der Preisberechnung in plentymarkets

Die Preisberechnung in Aufträgen beruht auf dem Bruttopreis der Varianten.
Ausgehend von diesem Bruttopreis wird der Nettopreis der Varianten für den Auftrag errechnet.
Die Auftragspositionsummen errechnen sich durch Multiplikation der Einzelpreise mit der gekauften Anzahl.
Die Bruttosumme einer Auftragsposition errechnet sich also aus dem Bruttoeinzelpreis multipliziert der Anzahl.
Die Nettosumme einer Auftragsposition errechnet sich aus dem errechneten und auf 4 oder 2 Nachkommastellen gerundeten Nettoeinzelpreis multipliziert mit der gekauften Anzahl.
Die Nachkommastellen des Einzelpreises werden durch die Einstellungen in der Buchhaltung bestimmt.
Der Umsatzsteuerbetrag für eine Auftragsposition ist die Differenz aus Bruttosumme minus Nettosumme. +
Ab irgendeinem Moment in der Preisberechnung wird der Preis auf 2 Nachkommastellen gerundet und anschließend mit diesem gerundeten Werten weiter gerechnet. Durch Ihre Einstellungen bestimmen Sie wie lange mit 4 Nachkommastellen gerechnet wird und ab wann mit 2 Nachkommastellen gerechnet wird.
Mithilfe der Einstellungen lassen sich folgende Ergebnisse erreichen:

*  Gerundete Einzelpreise
*  Gerundete Auftragspositionssummen
*  Gerundete Gesamtbeträge

== Speichern und Runden einstellen

Das Menü, in dem die 2 Einstellungen, sich befinden sowie eine Erläuterung der Einstellungen. Berücksichtigt für die Berechnung der Auftragspreise werden die Einstellungen, die beim Anlegen eines Auftrags eingestellt waren.

[.instruction]
Speichern und Runden einstellen:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Shop wählen » Standorte » Standort wählen » Buchhaltung**.  +
Das Tab **Grundeinstellungen** wird geöffnet.
. Nehmen Sie die Einstellung vor. Beachten Sie die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen.

.Speicher- und Rundungseinstellungen
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Anzahl Nachkommstellen bei Preisen**
|2 oder 4 Nachkommastellen wählen  +
**2** = Preise im Auftrag werden mit nur 2 Nachkommastellen gespeichert. Dadurch wird indirekt auch erreicht, dass der Einzelpreis gerundet wird. Die weitere Berechnung der Summen und des Rechnungsbetrages erfolgt dann basierend auf den gerundeten Einzelpreisen.  +
**4** = Preise werden im Auftrag mit 4 Nachkommastellen gespeichert. Wenn 4 Nachkommstellen gewählt werden, werden standardmäßig die Summen von Auftragsposition gerundet. Im Hintergrund werden die Summen jedoch ungerundet mit 4 Nachkommastellen gespeichert, so dass es möglich bleibt, später auch nur die Gesamtbeträge zu runden. Durch ein Häkchen bei **Nur Gesamtpreise runden** wird das standardmäßige Rundungsverhalten bei 4 Nachkommastellen aufgehoben und erst zu einem späteren Zeitpunkt gerundet.

|**Nur Gesamtpreise runden**
|Häkchen setzen, um das standardmäßge Runden bei 4 Nachkommastellen außer Kraft zu setzen und stattdessen erst die Gesamtbeträge zu runden. Gesamtbeträge bezieht sich auf den Warenwert eines Auftrages. Bezogen auf die Dokumenteinstellungen einer Rechnung sind das die Werte, die unter der Überschrift Summen aufgeführt werden.  +
Bei 4 Nachkommastellen werden ohne das Häkchen die Summen der Auftragspositionen gerundet.  +
Bei 2 Nachkommastellen hat das Häkchen keine Auswirkungen, da bereits der Einzelpreis gerundet wird.
|====

=== Beispielberechnungen

Im folgenden wird ein Vergleich der unterschiedlichen Berechnungvarianten und der resultierenden Beträge anhand eines Beispiels dargestellt. +
Verkauft wurden Stoffe. Es wurde mehrere Bahnen des gleichen Stoffs in einer Breite von 50 Zentimeter und von 30 Zentimeter gekauft. Die 50-Zentimeterbahn wurde 8 mal gekauft und die 30-Zentimeterbahn 7 mal. 30 Zentimeter kosten 2,187 € und 50 Zentimeter kosten 3,645 €. Die Preise basieren auf einem Meterpreis von 7,29 €. Welche Einstellungen für welche Variante gewählt werden müssen, steht ebenfalls in der Tabelle.

.Berechnungsvarianten im Vergleich
[cols="a,a,a,a,a,a,a,a,a,a,a,a,a"]
|====
|Berechnungsvariante |Einstellungen |Anzahl Bahnen |Variante |Einzelpreis brutto |Einzelpreis netto |Mwst. Einzelposition |Gesamtpreis brutto |Gesamtpreis netto |Mehrwertsteuer Auftragsposition |Nettowarenwert |Mehrwertsteuer gesamt |Rechnungsbetrag

.2+|Gerundete Gesamtbeträge
.2+|Um gerundete Gesamtbeträge zu erhalten, müssen 4 Nachkommastellen gewählt werden und die Einstellung, dass erst die Gesamtpreise gerundet werden. Das ist die Standardeinstellungen.
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,6025
|2,187
|0,4155
|18,2175
|15,309
|2,9085
.2+|gerundet 44,47
.2+|gerundet 8,45
.2+|52,92

|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|4,3376
|3,645
|0,6926
|34,700
|29,16
|5,5404

.2+|Gerundete Auftragspositionen
.2+|Um zu erreichen, dass die Auftragspositionssummen auf 2 Nachkommastellen zu runden, müssen 4 Nachkommastellen gewählt werden. Die Preise werden jedoch trotz des Rundens auf 2 Nachkommastellen mit 4 Nachkommastellen gespeichert.
|7
|Sommerwiese, Baumwolle, Grasgrün
|2,6025
|2,187
|0,4155
|gerundet 18,22
|gerundet 15,31
|2,91
.2+|44,47
.2+|8,45
.2+|52,92

|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|4,3376
|3,645
|0,6926
|gerundet 34,70
|gerundet 29,16
|5,54

.2+|Gerundete Einzelbeträge
.2+|Für gerundete Einzelpreise müssen 2 Nachkommstellen gewählt werden. Die Preise werden auch nur mit 2 Nachkommastellen gespeichert.
|7
|Sommerwiese, Baumwolle, Grasgrün
|gerundet 2,60
|gerundet 2,18
|0,42
|18,20
|15,26
|2,94
.2+|44,46
.2+|8,46
.2+|52,92

|8
|Sommerwiese, Baumwolle, Sonnenuntergangsrot
|gerundet 4,34
|gerundet 3,65
|0,69
|34,72
|29,20
|5,52
|====
