= Dokumentenarchiv
:lang: de
include::{includedir}/_header.adoc[]
:position: 80

== Gespeicherte Dokumente im Dokumentenarchiv

Im Dokumentenarchiv können Sie sich bereits generierte PDF-Dokumente einzeln anzeigen lassen oder Sammeldokumente im ZIP-Format generieren. In diesem Archiv werden PDF-Dokumente abgelegt, die in Ihrem plentymarkets-System im Rahmen der Auftragsabwicklung, beim Kassenverkauf mit POS oder im Bereich Warenwirtschaft erzeugt wurden.

Folgende Dokumente finden Sie im Dokumentenarchiv im PDF-Format:

[.row]
====
[.col-md-4]
.In plentymarkets erzeugte Auftragsdokumente
=====
* *Angebot*
* <<auftragsabwicklung/auftraege/auftraege-verwalten#1420, Auftragsbestätigung>>
* <<auftragsabwicklung/auftraege/auftragsdokumente/gelangensbestaetigung-erzeugen#, Gelangensbestätigung>>
* <<auftragsabwicklung/auftraege/auftragsdokumente/gutschriften-erzeugen#, Gutschrift>>
* <<auftragsabwicklung/auftraege/auftragsdokumente/gutschriften-erzeugen#, Korrekturbeleg>>
* <<auftragsabwicklung/auftraege/auftragsdokumente/lieferscheine-erzeugen#, Lieferschein>>
* <<auftragsabwicklung/auftraege/auftragsdokumente/mahnungen-erzeugen#, Mahnung>>
* *Proformarechnung*
* <<auftragsabwicklung/auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnung>>
* *Reparaturschein*
* <<auftragsabwicklung/auftraege/auftragsdokumente/ruecksendeschein-erzeugen#, Rücksendeschein>>
* <<auftragsabwicklung/auftraege/auftraege-verwalten#540, Sammelgutschrift>>
* <<auftragsabwicklung/auftraege/auftraege-verwalten#850, Sammelrechnung>>
* <<auftragsabwicklung/auftraege/auftraege-verwalten#530, Stornobeleg Gutschrift>>
* <<auftragsabwicklung/auftraege/auftraege-verwalten#1670, Stornobeleg Rechnung>>
=====

[.col-md-4]
.POS-Dokumente
=====
* <<omni-channel/pos/pos-einrichten#1020, Kassenbeleg>>
* <<omni-channel/pos/pos-kassenbenutzer#210, Kassengutscheinbeleg>>
* <<omni-channel/pos/pos-kassenbenutzer#210, Kassenrechnung>>
* <<omni-channel/pos/pos-kassenbenutzer#210, Kassenstornierung>>
* <<omni-channel/pos/pos-kassenbenutzer#210, Kassenstornorechnung>>
* <<omni-channel/pos-kassenbenutzer#_kassensturzbericht_erstellen#, Kassensturz>>
* <<omni-channel/pos-kassenbenutzer#210, Z-Report>>
=====

[.col-md-4]
.Sonstige Dokumente
=====
* *Abhollieferung*
* <<auftragsabwicklung/payment/paypal#80, Abrechnungsbericht>>
* <<auftragsabwicklung/payment/bankdaten-verwalten#70, EBICS-INI-Brief>>
* <<omni-channel/pos/pos-einrichten#400, Kassenjournal>>
* <<warenwirtschaft/nachbestellungen-verwalten#, Nachbestellung>>
* <<auftragsabwicklung/payment/bankdaten-verwalten#200, SEPA-Lastschriftmandat>>
* <<warenwirtschaft/wareneingaenge-verwalten#, Wareneingangsbeleg (Lagerschein)>>
=====
====

== Archivierte PDF-Dokumente suchen

Im Dokumentenarchiv können Sie PDF-Dokumente einer bestimmten Dokumentart in einem gewählten Zeitraum suchen. Die Dokumente werden chronologisch aufgelistet.

[.instruction]
PDF-Dokument suchen:

. Öffnen Sie das Menü *Aufträge » Dokumentenarchiv*.
. Wählen Sie die Einstellungen, die Sie suchen möchten. Beachten Sie dazu die Erläuterungen in <<tabelle-parameter-suche-dokumentenarchiv>>.
. Klicken Sie auf *Suche*.

[[tabelle-parameter-suche-dokumentenarchiv]]
.Parameter im Tab *Suche*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Nummer*
|Erlaubt eine scharfe Suche nach nur einem Dokument. Nummer eintragen, um nur ein bestimmtes Dokument zu suchen. *Dokument*, *Zeitraum* und *Mandant* müssen ebenfalls zum gesuchten Dokument passen.

|*Dokument*
|Dokumentyp wählen, um nur Dokumente dieses Typs zu suchen.

|*Datum*
|Zeitraum auswählen, um nur Dokumente zu suchen, die in einem bestimmten Zeitraum erzeugt wurden. Standardmäßig ist das aktuelle Datum als Start- und Enddatum eingestellt.

|*Mandant (Shop)*
|Einen *Mandant* oder *alle* wählen.

|*pro Seite*
|Wählen, wie viele Suchergebnisse pro Seite angezeigt werden.
|====

[TIP]
.Auftrag, Kunden und PDF-Dokumente öffnen
====
Klicken Sie auf die Auftrags-ID, um den Auftrag der jeweiligen Rechnung zu öffnen oder auf die Kunden-ID, um den Kundendatensatz zu öffnen. Öffnen Sie das PDF-Dokument durch Klick auf den Link in der Spalte *Datei*.
====

== Sammeldokumente im ZIP-Format exportieren

Sammeldokumente im ZIP-Format erlauben es Ihnen, größere Anzahlen von Dokumenten gleichzeitig abzurufen.

[.instruction]
Sammeldokument exportieren:

. Öffnen Sie das Menü *Aufträge » Dokumentenarchiv*.
. Wechseln Sie in das Tab *Export*.
. Nehmen Sie die Einstellungen gemäß <<tabelle-parameter-export-dokumentenarchiv>> vor.
. Klicken Sie auf das Zahnrad. +
→ Die ZIP-Datei wird exportiert.

[[tabelle-parameter-export-dokumentenarchiv]]
.Parameter im Tab *Export*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Dokument*
|Dokumenttyp wählen, um nur Dokumente dieses Typs zu suchen.

|*Mandant*
|Einen *Mandant* oder *alle* wählen.

|*Zeitraum*
|Zeitraum auswählen, um nur Dokumente zu suchen, die in einem bestimmten Zeitraum erzeugt wurden. Standardmäßig ist das aktuelle Datum als Start- und Enddatum eingestellt.

|*Unterordner*
|Auswählen, ob beim Export Unterordner erstellt werden sollen. Bei Auswahl der Option *mit* werden in der ZIP-Datei Unterordner für jeden Monat erstellt. Bei der Option *ohne* werden keine Unterordner erstellt.

|====

[IMPORTANT]
.Export schlägt fehl
====
Es werden maximal 6.000 PDFs exportiert. Wenn Ihr Export fehlschlägt, überschreitet die Datei eventuell die maximale Anzahl, die exportiert wird. Schränken Sie den Zeitraum weiter ein, um die Anzahl der Dokumente zu verringern. Wenn Sie den Zeitraum auf den kleinstmöglichen Zeitraum, also 1 Tag, reduziert haben, werden unabhängig von Export-Maximum alle Dokumente exportiert.
====
