= Tags
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Tag, Tags, Tag erstellen
:description: Erfahre auf dieser Handbuchseite, wie du Tags in plentymarkets verwaltest.
:position: 20
:url: willkommen/allgemeine-funktionen/tags
:id: UZRABLS
:author: team-crm

Tags sind Schlagworte, mit denen du Datensätze in plentymarkets hervorheben kannst.
Tags sind vielseitig einsetzbar. Beispielsweise helfen dir Tags:

* den Überblick über große Datenmengen im Backend zu behalten.
Das heißt, du markierst spezifische Kunden, Aufträge, Tickets usw.
* Produkte im Frontend hervorzuheben.
Das heißt, du versiehst spezifische Varianten mit Schlagworten.

Im Wesentlichen besteht der Ablauf aus nur zwei Schritten.
Erstens, <<erstelle die Tags>>.
Zweitens, <<verknüpfe die Tags>> mit den passenden Datensätzen.

////
Tags werden zentral im Menü *Einrichtung » Einstellungen » Tags* erstellt und verwaltet. Diese Tags können mit Datensätzen in den folgenden Bereichen von plentymarkets verknüpft werden:

* Board
* Kategorie
* Ticket
* Kontakt
* Variante
* Auftrag
* Nachrichten
* Nachrichten (kostenpflichtig)
////

[#50]
== Voraussetzung: Nötige Benutzerrechte

Benutzer:innen vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs in plentymarkets. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit *Backend*-Zugang mit Tags arbeiten können, muss eine Person mit *Admin*-Zugang ihnen die nötigen Rechte vergeben.

[.instruction]
Benutzerrechte vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne das zu bearbeitende Konto.
. Aktiviere im Bereich *Berechtigungen* die Berechtigungen anhand von <<#tabelle-tags-erforderliche-rechte-backend-benutzer>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-tags-erforderliche-rechte-backend-benutzer]]
.Benutzerrechte vergeben
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Einrichtung > Tag > Aktualisieren*
|Das Recht, bestehende Tags zu bearbeiten.

| *Einrichtung > Tag > Anzeigen*
|Das Recht, Tags im plentymarkets System zu sehen.

| *Einrichtung > Tag > Erstellen*
|Das Recht, neue Tags zu erstellen.

| *Einrichtung > Tag > Löschen*
|Das Recht, Tags zu löschen.

| *Einrichtung > Tag > Tag-Verknüpfung > Aktualisieren*
|

| *Einrichtung > Tag > Tag-Verknüpfung > Anzeigen*
|

| *Einrichtung > Tag > Tag-Verknüpfung > Erstellen*
|

| *Einrichtung > Tag > Tag-Verknüpfung > Löschen*
|
|====

[#100]
== Tags erstellen und bearbeiten

[#200]
=== Neue Tags erstellen

Erstelle zunächst die Tags, die du für deine Produkte, Kunden, Aufträge, Tickets usw. verwenden möchtest.

[.instruction]
Neues Tag erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Tags*.
. Klicke auf *Neues Tag erstellen* (icon:plus[role="green"]). +
→ Rechts wird ein Fenster geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-tag-einstellungen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Tag wird erstellt und der Liste hinzugefügt.

[[tabelle-tag-einstellungen]]
.Tag erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *ID*
|Die Tag-ID wird automatisch vergeben und ist nicht änderbar.
Sie dient zur eindeutigen Kennzeichnung deiner Tags.

*_Anwendungsfall_*: <<Tag-Verknüpfungen>> können importiert werden.
Während du also z.B. Artikel- und Variantendaten importierst, kannst du die passenden Tags auch direkt verknüpfen.
Dies geschieht z.B. durch Angabe der Tag-ID.

| *Name DE* +
[red]#(Pflichtfeld)#
|Gib einen Namen für das Tag ein.
Der Name ist das Schlagwort, das den Datensatz hervorhebt.

*_Tipp_*: Der Name darf Leerzeichen enthalten, d.h. er kann aus mehreren Wörtern bestehen.

| *Farbe*
a|Welche Hintergrundfarbe soll der Tag-Text haben?
Es gibt drei Möglichkeiten, die Farbe zu wählen.

* Gib die Farbe als Hexadezimalwert ein.
* Gib die englische Bezeichnung einer der 16 Grundfarben ein (black, red, silver, white etc.) +
* Klicke auf das Quadrat rechts und wähle die Farbe.

| *Bereich*
a|Welche Art von Datensätzen willst du mit diesem Tag verknüpfen?
Wähle alle zutreffenden Bereiche (icon:check-square[role="blue"]).

//hinzfügen: die noch inhaltslose Bereiche (Tickets, Kontakt, usw) mit Inhalt ergänzen

[cols="1,3"]
!===
!Bereich !Anwendungsbeispiel

! *Board*
!Willst du bestimmte Aufgabenkarten auf Boards markieren?
//im Menü *plentymarkets Logo (Start) » Boards*.
Beispielsweise könntest du angeben, dass manche Aufgaben eine hohe oder niedrige Priorität haben.

! *Kategorie*
!Willst du bestimmte Kategorien im Backend markieren?
Beispielsweise könntest du angeben, dass eine Kategorie nur für saisonale Angebote verwendet werden soll.

*_Hinweis_*: Kategorie-Tags sind für Kunden im Webshop _nicht sichtbar_.

! *Ticket*
!Tag kann mit Tickets des Ticketsystems verknüpft werden.

! *Kontakt*
!Tag kann mit Kontakten verknüpft werden.

! *Variante*
!Tag kann mit Varianten verknüpft werden.

! *Auftrag*
!Tag kann mit Aufträgen verknüpft werden.
//hinzfügen: dass man zwar den Bereich auswählen kann, aber man kann noch nirgendwo am Auftrag den Tag verknüpfen

! *Nachrichten*
!Tag kann mit Nachrichten im Messenger verknüpft werden.

! *Nachrichten (kostenpflichtig)*
!Tag kann mit kostenpflichtigen Nachrichten im Messenger verknüpft werden.
!===

//hinzfügen: Inhalt hier mit den auskommentierten Teil ganz unten vergleichen, denn es sagt das gleiche aus
| *Name EN* +
*Name FR* +
*Name IT* +
usw.
|Tag-Namen in weiteren Sprachen eingeben. Weitere Informationen findest du im Kapitel <<willkommen/allgemeine-funktionen/tags#400, Weitere Sprachen zu Tags hinzufügen>>.
|====

[TIP]
.Tags können nur manuell erstellt werden
====
Es ist derzeit nur möglich, Tags manuell im Menü *Einrichtung » Einstellungen » Tags* zu erstellen und zu verwalten.
Es ist also nicht möglich, neue Tags mit Hilfe einer Importdatei zu erstellen.

<<Tag-Verknüpfungen>> können aber wiederum importiert werden.
Während du also z.B. Artikel- und Variantendaten importierst, kannst du die passenden Tags auch direkt verknüpfen.
====

[#300]
=== Bestehende Tags suchen und bearbeiten

Tags können nach *Name*, *Bereich* und *Sprache* gefiltert werden. Gehe wie unten beschrieben vor, um Tags anhand dieser Kriterien zu filtern.

[.instruction]
Tags filtern:

. Öffne das Menü *Einrichtung » Einstellungen » Tags*.
. Wähle einen oder mehrere Filter. Beachte dazu die Erläuterungen in <<#tabelle-tag-filter>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Tags, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
//hinzfügen: und öffnen für die weiterbearbeitung

[[tabelle-tag-filter]]
.Tag-Filter
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Name*
|Name des Tags eingeben. +
*_Tipp:_* Wenn alle Sprachen gewählt wurden, werden alle Sprachen berücksichtigt. Angezeigt wird jedoch der unter *Name DE* eingegebene Wert.

| *Bereich*
|Einen oder mehrere Bereiche wählen, um nur für diese Bereiche aktivierte Tags anzuzeigen.

| *Sprache*
|Einen oder mehrere Sprachen wählen, um nur Tags mit Namen in diesen Sprachen anzuzeigen.
|====

[#400]
== Tags verknüpfen

//hinzfügen: evtl Links zu den anderen Handbuchseiten, wo die Verknüpfung stattfindet, oder evtl includes, um die Beschreibung auch hier zu zeigen
//hinzfügen: wo es auch mittels Import klappt
//https://knowledge.plentymarkets.com/crm/kontakte-verwalten#150
//https://knowledge.plentymarkets.com/artikel/einstellungen/kategorien#700
//https://knowledge.plentymarkets.com/willkommen/allgemeine-funktionen/boards#40

////
[#400]
=== Tag-Namen in weiteren Sprachen hinzufügen

Gehe wie im Folgenden beschrieben vor, um zu einem bereits erstellten Tag Namen in weiteren Sprachen hinzuzufügen.

[.instruction]
Tag-Namen in weiteren Sprachen hinzufügen:

. Öffne das Menü *Einrichtung » Einstellungen » Tags*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Alle Tags werden angezeigt.
. Kicke auf das Tag. +
→ Rechts wird ein Fenster geöffnet.
. Gib in die Felder der gewünschten Sprachen die Übersetzung ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
