= Kontakte verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kontakt, Kunde, Adressen
:description: Erfahren Sie, wie Sie in plentymarkets Kontakte erstellen und verwalten.
:position: 11

[IMPORTANT]
.Hinweis zur Handbuchseite Kontakte verwalten
====
Auf dieser Handbuchseite werden alle Einstellungen, die im Menü *CRM » Kontakte* im neuen Terra-Backend zur Verfügung stehen, beschrieben. Die Handbuchseite <<crm/kundendaten-verwalten#, *Kundendaten verwalten*>>, die die Einstellungen in den Menüs *Kunden » Kunden bearbeiten* und *Einstellungen » Kunden* beschreibt, steht parallel zur Verfügung. Wenn das neue Menü *CRM » Kontakte* das alte Menü *Kunden » Kunden bearbeiten* vollständig ersetzt, wird das Menü *Kunden » Kunden bearbeiten* abgeschaltet und somit auch die Handbuchseite *Kundendaten verwalten* entfernt.
====

Im Menü *CRM » Kontakte* erstellen Sie Datensätze zu Kontakten und speichern dort alle Informationen. Sie können Ihre Kontakte in diesem Menü auch bearbeiten und löschen sowie die Adressen Ihrer Kontakte anzeigen, neue Adressen hinzufügen und bestehende Adressen löschen. Außerdem haben Sie die Möglichkeit, die Historie, die z.B. anzeigt, seit wann der Kontakt registriert ist oder ob es sich um einen regulären Zugang oder einen Gastzugang handelt, einzusehen.

[#100]
== Kontakt erstellen

Gehen Sie wie im Folgenden beschrieben vor, um einen neuen Kontakt zu erstellen. Fügen Sie Kontaktoptionen wie z.B. E-Mail-Adressen, Telefonnummern und ggf. die USt-IdNr. hinzu. Sie können einen neuen Kontakt beispielsweise auch während einer telefonischen oder schriftlichen Bestellung erstellen oder die Daten eines Interessenten speichern. Beim Erstellen eines Kontakts wird vom System automatisch eine ID vergeben. Diese ID kann nicht geändert werden.

[.instruction]
Kontakt erstellen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Klicken Sie auf *Neuen Kontakt erstellen*.
. Nehmen Sie die Einstellungen im Bereich *Neuer Kontakt* vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. Wählen Sie im Bereich *Kontaktoptionen* den Typ und Subtyp aus den Dropdown-Menüs und geben Sie den Wert ein. Beachten Sie dazu die Erläuterungen in Tabelle 1. +
→ Mit einem Klick auf *Kontaktoption hinzufügen* fügen Sie weitere Kontaktoptionen hinzu.
. *Speichern* Sie die Einstellungen.

.Kontakt erstellen
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|Neuer Kontakt

|*Anrede*
|Option aus dem Dropdown-Menü wählen. Die Auswahl ist optional. +
*Frau* = Weibliche Anrede +
*Herr* = Männliche Anrede

|*Titel*
|Ggf. Titel des Kontakts eingeben.

|*Vorname*, *Nachname*
|Vorname und Nachname des Kontakts eingeben.

|*Mandant (Shop)*
|Mandant (Shop) aus dem Dropdown-Menü wählen, um den Kontakt diesem Mandanten zuzuordnen. +
Es werden nur Mandanten angezeigt, für die im Menü *Einstellungen » Mandant (Shop)* in den *Grundeinstellungen* des Mandanten ein Name eingegeben ist.

|*Sprache*
|Sprache für den Kontakt wählen. Es werden z.B. Rechnungsdokumente in dieser Sprache erstellt, wenn Sie eine Vorlage für die Sprache angelegt haben.

|*Typ*
|Typ wählen. Standardmäßig können die Typen *Kunde*, *Handelsvertreter*, *Lieferant*, *Partner*, *Hersteller* und *Interessent* gewählt werden. Eigene Typen erstellen Sie im Menü <<crm/kundendaten-verwalten#300, *Einstellungen » Kunden » Typen*>>.

|*Klasse*
|Klasse wählen. Klassen dienen zur internen Unterscheidung und z.B. ob und welcher Rabatt dieser Klasse gewährt werden soll. Klassen werden im Menü <<crm/kundendaten-verwalten#100, *Einstellungen » Kunden » Kundenklassen*>> erstellt. Soll zum Beispiel zwischen Endkunden und Händlern bei der Preisanzeige im Webshop unterschieden werden, kann dies über die Option *Anzeige der Preise im Webshop* in der Konfiguration der Klassen vorgenommen werden. Bei Endkunden (B2C) werden die Bruttopreise im Webshop angezeigt. Bei Händlern (B2B) werden die Nettopreise im Webshop angezeigt. +
Leere Option = Keine Zuordnung zu einer Klasse +
*_Wichtig_*: Wenn keine Zuordnung zu einer Klasse erfolgt, wird ein Kontakt automatisch der Klasse mit der niedrigsten Position zugeordnet. Da pro Klasse auch die Preisdarstellung im Webshop konfiguriert wird, diese Option bei der Klasse mit der Position 1 prüfen, damit bei automatischen Zuweisungen auch die gewünschte Preisdarstellung erfolgt.

|*Handelsvertreter*
|Mit dieser Einstellung wird dem Typ ein Handelsvertreter zugeordnet. ID des Handelsvertreters eingeben oder die ersten drei Buchstaben des Namens eingeben, um die Vorschlagsliste aufzurufen. Alternativ auf der Tastatur die Pfeiltaste nach unten drücken, ohne einen Suchbegriff einzugeben, um alle Handelsvertreter anzuzeigen. Mit einem Klick auf den Eintrag des Handelsvertreters wird die ID und der Name des Handelsvertreters in dieses Feld eingetragen. Somit ist der Handelsvertreter dem Typ zugeordnet. +
Sollen die Umsätze Ihrer Handelsvertreter mit der Statistik <<basics/statistik/allgemeine-statistiken/umsatz/umsatz-handelsvertreter#, *Umsatz nach Handelsvertreter*>> ausgewertet werden, muss die Zuordnung per Ereignisaktion erfolgen, mit der Aktion <<basics/automatisierung/ereignisaktionen#konfiguration, *Handelsvertreter dem Kunden zuordnen*>>. +
*_Wichtig_*: Der im Kontakt eingestellte Handelsvertreter wird nicht für die Aufträge des Kontakts herangezogen. Somit wird der Auftrag nicht in der Statistik *Umsatz nach Handelsvertreter* berücksichtigt. Damit der Handelsvertreter für einen Auftrag berücksichtigt wird, muss auch diese Zuordnung per Ereignisaktion erfolgen. Beachten Sie dazu die Hinweise zur Ereignisaktion <<basics/automatisierung/ereignisaktionen#konfiguration, *Handelsvertreter dem Auftrag zuordnen*>>.

|*Bewertung*
|Kontakt für interne Zwecke bewerten. Fünf rote Sterne stehen für die schlechteste und fünf gelbe Sterne für die beste Bewertung.

|*Kundennummer*
|Kundennummer für den Kontakt eingeben. Die Kundennummern können fortlaufend nummeriert werden oder nicht. Kundennummern werden nicht automatisch vergeben.

|*Eigner*
|Eigner für den Kontakt wählen. Wenn kein Eigner gewählt werden soll, die leere Option wählen.

|*Geburtsdatum*
|Geburtsdatum des Kontakts nach dem Muster dd.mm.yyyy eingeben oder aus dem Kalender wählen.

|*Newsletter*
|Zeigt an, ob der Kontakt den Newsletter erhält. Es ist nicht möglich, die Option manuell zu aktivieren. Um den Newsletter-Bezug für den Kontakt zu deaktivieren, auf *Newsletter löschen* klicken.

|*Gesperrt*
|Wählen, ob der Kontakt für den eingestellten Mandanten (Shop) gesperrt wird oder nicht. +
Wenn die Option aktiviert ist, ist der Kontakt gesperrt und kann sich nicht mehr im Webshop einloggen. Wenn die Option deaktiviert ist, kann sich der Kontakt im Webshop einloggen.

2+|Kontaktoptionen

|*Typ*
|Typ, z.B. E-Mail, Telefon oder Webseite, aus dem Dropdown-Menü wählen.

|*Subtyp*
|Subtyp, z.B. Arbeit, Privat oder Ansprechpartner, aus dem Dropdown-Menü wählen.

|*Wert*
|Wert eingeben.
|====

[#200]
== Kontakt suchen

In der Ansicht *Filter* auf der linken Seite haben Sie die Möglichkeit, Kontakte nach bestimmten Kriterien zu suchen. Die gefundenen Kontakte werden dann in der Ansicht *Übersicht* angezeigt. Sie können die Kontaktdaten <<crm/_kontakte-verwalten#300, *bearbeiten*>>.

Um bestimmte Kontakte zu suchen, geben Sie die Ihnen bekannten Suchbegriffe in die Filter ein oder wählen Sie die Einstellungen der Dropdown-Menüs. Sie können dabei auch mehrere Suchbegriffe gleichzeitig in die Suchfelder eingeben. Dies ermöglicht Ihnen eine schnellere und genauere Suche.

[IMPORTANT]
.Suche über die E-Mail-Adresse
====
Bitte beachten Sie, dass aktuell nur die Suche über die E-Mail-Adresse möglich ist. Sie können auch nach Teilen der E-Mail-Adresse suchen. Die anderen Suchoptionen und Filter, die in Tabelle 2 aufgelistet sind, werden nach und nach zur Verfügung gestellt.
====

[.instruction]
Kontakt suchen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Geben Sie in der Ansicht *Filter* Suchbegriffe in die Suchfelder ein bzw. stellen Sie Filteroptionen in den Dropdown-Menüs ein. Beachten Sie dazu die Erläuterungen in Tabelle 2.
. Klicken Sie auf *Suchen*. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Der Kontakt wird geöffnet.

.Filter für die Kontakte
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Ohne gewählte Filtereinstellungen auf *Suchen* klicken, um alle Kontakte anzuzeigen. Alternativ die Suchergebnisse durch Filtereinstellungen eingrenzen und auf *Suchen* klicken. Die gefundenen Kontakte werden in der Übersicht angezeigt.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*ID*
|Jeder Kontakt erhält automatisch eine fortlaufende und einzigartige ID. Dies ist unabhängig davon, ob der Eintrag manuell oder automatisch angelegt wurde. Zwei Kontakte haben somit nie die gleiche ID. Die ID entspricht immer einer echten Zahl. Ungültig sind z.B. "00521" oder "ADF8354".

|*Name*
|Vorname und/oder Nachname eingeben, um den Kontakt mit diesem Namen zu suchen.

|*E-Mail*
|Vollständige E-Mail-Adresse eingeben, um den Kontakt mit dieser E-Mail-Adresse zu suchen.

|*Anschrift*
|Straßenname, PLZ oder Ort eingeben, der im Kontakt gespeichert ist.

|*Land*
|Land wählen, um nur Kontakte aus diesem Land anzuzeigen. Das Land ist in den Kontaktdaten gespeichert.

|*Mandant (Shop)*
|Mandant (Shop) wählen, um nur Kontakte dieses Mandanten anzuzeigen. Der Mandant ist in den Kontaktdaten gespeichert. +
*_Wichtig_*: Variablen Benutzern stehen nur Mandanten zur Auswahl, für die sie eine Berechtigung haben. Berechtigungen werden im Tab <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90, *Berechtigung*>> unter *Einstellungen » Grundeinstellungen » Benutzer » Konten* eingestellt.
|====

[#300]
== Kontakt bearbeiten

Suchen Sie den Kontakt mit Hilfe der <<crm/_kontakte-verwalten#200, *Filtereinstellungen*>>. Öffnen Sie den Kontakt durch einen Klick auf die Zeile des Kontakts, um dessen Daten, wie z.B. Sprache, Klasse, Geburtsdatum, Telefonnummer und E-Mail-Adresse, zu bearbeiten. Erläuterungen zu den Einstellungen und Optionen in den Bereichen *Kontakt* und *Kontaktoptionen* finden Sie im Kapitel <<crm/_kontakte-verwalten#100, *Kontakt erstellen*>>.

[.instruction]
Kontakt bearbeiten:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der <<crm/_kontakte-verwalten#200, *Filtereinstellungen*>>. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Der Kontakt wird geöffnet.
. Nehmen Sie die Änderungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1 im Kapitel <<crm/_kontakte-verwalten#100, *Kontakt erstellen*>>.
. *Speichern* Sie die Einstellungen.

[TIP]
.Anzeige bei einem oder mehreren geöffneten Kontakten
====
Klickt man auf einen Kontakt, um diesen anzuzeigen oder zu bearbeiten, öffnet sich der Kontakt mit ID sowie die Details des Kontakts mit ID. +

Über den linken Bereich können nun weitere Untermenüs des Kontakts wie *Adressen* und *Neue Adresse* aufgerufen werden. Klickt man z.B. auf *Adresse* werden alle zu dem Kontakt gespeicherten Adressen angezeigt. Sobald mehr als ein Untermenü des Kontakts geöffnet ist, erscheint im Feld ein Dreieck, über das man zwischen den geöffneten Untermenüs des Kontakts einfach und schnell hin- und herwechseln kann. +

Über die Ansicht *Übersicht* gelangt man zurück in die Übersicht der gefundenen Kontakte. Aus dieser Ansicht heraus lassen sich beliebig viele weitere Kontakte aufrufen. +

Sobald mehr als ein Kontakt geöffnet ist, erscheint in der Ansicht *Details* ein Dreieck, über das man die Kontakte, die bereits einmal geöffnet waren, einfach und schnell aufrufen kann.
====

[#400]
== Kontakt löschen

Sie haben die Möglichkeit, einzelne Kontakte im Menü *CRM » Kontakte* zu löschen. Ein Kontakt kann nur gelöscht werden, sofern dieser nicht mit einem Auftrag verknüpft ist.

[.instruction]
Kontakt löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der <<crm/_kontakte-verwalten#200, *Filtereinstellungen*>>. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Der Kontakt wird geöffnet.
. Klicken Sie im linken Bereich auf *Kontakt löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Der Kontakt wird gelöscht und aus der Übersicht entfernt.

[#500]
== Adressen anzeigen

Aus dem geöffneten Kontakt heraus lassen sich alle dem Kontakt zugehörigen Adressen in übersichtlichen Info-Boxen anzeigen. Neben Informationen wie ID, Firmenname, Vor- und Nachname, Adresse und Land sehen Sie anhand eines Tags auf einen Blick, bei welcher der gespeicherten Adressen es sich um die Rechnungsadresse und die Lieferadresse handelt.

[.instruction]
Adressen anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der <<crm/_kontakte-verwalten#200, *Filtereinstellungen*>>. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Der Kontakt wird geöffnet.
. Klicken Sie im linken Bereich auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherten Adressen werden angezeigt.

[#600]
== Adresse hinzufügen
Fügen Sie einem Kontakt beliebig viele Adressen hinzu. Bei den mit *** gekennzeichneten Feldern handelt es sich um Pflichtfelder. Fügen Sie außerdem Adressoptionen wie z.B. die Umsatzsteuer-Identifikationsnummer oder die Telefonnummer des Kontakts hinzu.

[.instruction]
Adresse hinzufügen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der <<crm/_kontakte-verwalten#200, *Filtereinstellungen*>>. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Der Kontakt wird geöffnet.
. Klicken Sie im linken Bereich auf *Neue Adresse*.
. Nehmen Sie die Einstellungen im Bereich *Neue Adresse* vor. Beachten Sie dazu die Erläuterungen in Tabelle 3.
. Wählen Sie im Bereich *Adressoptionen* den Typ aus dem Dropdown-Menü und geben Sie den Wert ein. Beachten Sie die dazu die Erläuterungen in Tabelle 3. +
→  Mit einem Klick auf *Adressoption hinzufügen* fügen Sie weitere Adressoptionen hinzu.
. *Speichern* Sie die Einstellungen. +
→ Die Adresse wird der Übersicht im Bereich *Adressen* hinzugefügt.

.Adresse hinzufügen
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|Neue Adresse

|*Firma*
|Firmenname eingeben. Dies ist ein Pflichtfeld, wenn unter *Vorname* und *Nachname* kein Eintrag gemacht wird.

|*Vorname*
|Vorname des Kontakts eingeben. Dies ist ein Pflichtfeld, wenn unter *Firma* und *Nachname* kein Eintrag gemacht wird.

|*Nachname*
|Nachname des Kunden eingeben. Dies ist ein Pflichtfeld, wenn unter *Firma* und *Nachname* kein Eintrag gemacht wird.

|*Zusatz*
|Ggf. Zusatzangaben zum Kontakt eingeben, z.B. z.Hd. Herrn Max Mustermann.

|*Straße* +
*Hausnummer* +
*Postleitzahl* +
*Ort*
|Straße, Hausnummer, Postleitzahl und Ort des Kontakts eingeben. Diese Angaben werden z.B. für die Rechnungsadresse verwendet. Bei bestimmten Ländern, z.B. Vereinigtes Königreich, wird die Reihenfolge der Optionen *Postleitzahl* und *Ort* getauscht. +
*Postleitzahl* und *Ort* sind Pflichtfelder. +
*Straße* ist ein Pflichtfeld, wenn unter *Zusatz* kein Eintrag gemacht wird.

|*Zusatz*
|Ggf. Adresszusatz eingeben, z.B. Apartment 12a.

|*Frei*
|Feld zur freien Verfügung.

|*Land* +
*Region/Bezirk*
|Werte aus den Dropdown-Menüs wählen.

2+|Adressoptionen

|*Typ*
|Typ, z.B. Postnummer oder Umsatzsteuer-Identifikationsnummer, aus dem Dropdown-Menü wählen.

|*Wert*
|Wert eingeben.

|====


[#700]
== Adresse bearbeiten

Sie können bestehende Adressen sowie Adressoptionen jederzeit bearbeiten. Beachten Sie dazu die Erläuterungen im Kapitel <<crm/_kontakte-verwalten#600, *Adresse hinzufügen*>>.

[.instruction]
Adressen bearbeiten:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der <<crm/_kontakte-verwalten#200, *Filtereinstellungen*>>. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Der Kontakt wird geöffnet.
. Klicken Sie im linken Bereich auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherten Adressen werden angezeigt.
. Klicken Sie in der Info-Box der Adresse, die Sie bearbeiten möchten, auf *Bearbeiten*.
. Nehmen Sie die Änderungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 3 im Kapitel <<crm/_kontakte-verwalten#700, *Adresse hinzufügen*>>.
. *Speichern* Sie die Einstellungen.

[#800]
== Adresse löschen

Sie haben die Möglichkeit, die zu dem Kontakt gespeicherten Adressen zu löschen. Dies ist z.B. nötig, wenn die Lieferadresse des Kontakts nicht mehr aktuell ist.

Adresse löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der <<crm/_kontakte-verwalten#200, *Filtereinstellungen*>>. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Der Kontakt wird geöffnet.
. Klicken Sie im linken Bereich auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherte Adressen werden angezeigt. +
. Klicken Sie in der Info-Box der Adresse, die Sie löschen möchten, auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Die Adresse wird gelöscht und aus der Übersicht entfernt.

[#900]
== Historie anzeigen

In jedem Datensatz können Sie die Historie eines Kontakts einsehen. Die Historie beinhaltet z.B. das Datum, seit dem der Kontakt bei Ihnen registriert ist, wann er das letzte Mal in Ihrem Webshop eingeloggt war und wann der letzte Auftrag generiert wurde. Die Daten werden automatisch angepasst und können nicht geändert werden.

[.instruction]
Historie anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der <<crm/_kontakte-verwalten#200, *Filtereinstellungen*>>. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→   Der Kontakt wird geöffnet und die Historie wird im rechten Bereich unterhalb der *Kontaktoptionen* angezeigt.
. Beachten Sie die Erläuterungen zur Historie in Tabelle 4.

.Historie im Menü *CRM » Kontakte » Kontakt öffnen*
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Registriert seit*
|Datum und Uhrzeit, seit wann der Kontakt registriert ist.

|*Aktualisiert*
|Datum und Uhrzeit, wann die Daten des Kontakts das letzte Mal aktualisiert wurden.

|*Letzter Login*
|Datum und Uhrzeit des letzten Login.

|*Letzter Auftrag*
|Datum und Uhrzeit, wann der letzte Auftrag eingegangen ist. Die Auftrags-ID wird ebenfalls angezeigt. Mit einem Klick auf die ID wird der Auftrag geöffnet. Wenn noch kein Auftrag eingegangen ist, steht in diesem Feld *Keine Daten*.

|*Zugangsart*
|Art, wie sich der Kontakt registriert hat. +
*Regulärer Zugang* = Der Kontakt hat sich neu registriert bzw. der Datensatz wurde manuell im Backend erstellt. +
*Gastzugang* = Der Kontakt hat sich als Gast angemeldet und bestellt.
|====
