= Kontakte verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kontakt, Kunde, Adressen
:description: Erfahren Sie, wie Sie Kontakte in plentymarkets erstellen und verwalten.
:position: 11

[IMPORTANT]
.Hinweis zur Handbuchseite Kontakte verwalten
====
Auf dieser Handbuchseite werden alle Einstellungen, die im Menü **CRM » Kontakte** im neuen Terra-Backend zur Verfügung stehen, beschrieben. Die Handbuchseite <<crm/kundendaten-verwalten#, **Kundendaten verwalten**>>, die die Einstellungen in den Menüs **CRM » Kunden bearbeiten** und **System » Kunden** beschreibt, steht parallel zur Verfügung. Wenn das neue Menü **CRM » Kontakte** das alte Menü **CRM » Kunden bearbeiten** vollständig ersetzt, wird das Menü **CRM » Kunden bearbeiten** abgeschaltet und somit auch die Handbuchseite **Kundendaten verwalten** entfernt.
====

Im Menü **CRM » Kontakte** erstellen Sie Datensätze zu Kontakten und speichern dort alle Informationen. Sie können Ihre Kontakte in diesem Menü auch bearbeiten und löschen sowie die Adressen Ihrer Kontakte anzeigen. Außerdem haben Sie die Möglichkeit, die Historie, die z.B. anzeigt, seit wann der Kontakt registriert ist oder ob es sich um einen regulären Zugang oder einen Gastzugang handelt, einzusehen.

[#100]
== Kontakt erstellen

Gehen Sie wie im Folgenden beschrieben vor, um einen neuen Kontakt zu erstellen. Fügen Sie Kontaktoptionen wie z.B. E-Mail-Adressen, Telefonnummern und ggf. die USt-IdNr. hinzu. Sie können einen neuen Kontakt beispielsweise auch während einer telefonischen oder schriftlichen Bestellung erstellen oder die Daten eines Interessenten speichern. Beim Erstellen eines Kontakts wird vom System automatisch eine ID vergeben. Diese ID kann nicht geändert werden.

[.instruction]
Kontakt erstellen:

. Öffnen Sie das Menü **CRM » Kontakte**.
. Klicken Sie auf **Neuen Kontakt erstellen**.
. Nehmen Sie die Einstellungen im Bereich **Neuer Kontakt** vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. Klicken Sie im Bereich **Kontaktoptionen** auf **Kontaktoption hinzufügen**.
. Wählen Sie den Typ und den Subtyp und geben Sie den Wert ein. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen.

.Kontakt erstellen
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|Neuer Kontakt

|**Anrede**
|Option aus dem Dropdown-Menü wählen. Die Auswahl ist optional. +
**Frau** = Weibliche Anrede +
**Herr** = Männliche Anrede

|**Titel**
|Ggf. Titel des Kontakts eingeben.

|**Vorname**
|Vorname des Kontakts eingeben.

|**Name**
|Nachname des Kontakts eingeben.

|**Mandant (Shop)**
|Mandant (Shop) aus dem Dropdown-Menü wählen, um den Kontakt diesem Mandanten zuzuordnen. +
Es werden nur Mandanten angezeigt, für die im Menü **System » Mandant** in den **Grundeinstellungen** des Mandanten ein Name eingegeben ist.

|**Sprache**
|Sprache für den Kontakt wählen. Es werden z.B. Rechnungsdokumente in dieser Sprache erstellt, wenn Sie eine Vorlage für die Sprache angelegt haben.

|**Typ**
|Typ wählen. Standardmäßig können die Typen **Kunde**, **Handelsvertreter**, **Lieferant**, **Partner**, **Hersteller** und **Interessent** gewählt werden. Eigene Typen erstellen Sie im Menü <<crm/kundendaten-verwalten#300, **System » Kunden » Typen**>>.

|**Klasse**
|Klasse wählen. Klassen dienen zur internen Unterscheidung und z.B. ob und welcher Rabatt dieser Klasse gewährt werden soll. Klassen werden im Menü <<crm/kundendaten-verwalten#100, **System » Kunden » Kundenklassen**>> erstellt. Soll zum Beispiel zwischen Endkunden und Händlern bei der Preisanzeige im Webshop unterschieden werden, kann dies über die Option **Anzeige der Preise im Webshop** in der Konfiguration der Klassen vorgenommen werden. Bei Endkunden (B2C) werden die Bruttopreise im Webshop angezeigt. Bei Händlern (B2B) werden die Nettopreise im Webshop angezeigt. +
Leere Option = Keine Zuordnung zu einer Klasse +
__**Wichtig**__: Wenn keine Zuordnung zu einer Klasse erfolgt, wird ein Kontakt automatisch der Klasse mit der niedrigsten Position zugeordnet. Da pro Klasse auch die Preisdarstellung im Webshop konfiguriert wird, diese Option bei der Klasse mit der Position 1 prüfen, damit bei automatischen Zuweisungen auch die gewünschte Preisdarstellung erfolgt.

|**Handelsvertreter**
|Mit dieser Einstellung wird dem Typ ein Handelsvertreter zugeordnet. ID des Handelsvertreters eingeben oder die ersten drei Buchstaben des Namens eingeben, um die Vorschlagsliste aufzurufen. Alternativ auf der Tastatur die Pfeiltaste nach unten drücken, ohne einen Suchbegriff einzugeben, um alle Handelsvertreter anzuzeigen. Mit einem Klick auf den Eintrag des Handelsvertreters wird die ID und der Name des Handelsvertreters in dieses Feld eingetragen. Somit ist der Handelsvertreter dem Typ zugeordnet. +
Sollen die Umsätze Ihrer Handelsvertreter mit der Statistik **<<basics/statistik/allgemeine-statistiken/umsatz/umsatz-handelsvertreter#, Umsatz nach Handelsvertreter>>** ausgewertet werden, muss die Zuordnung per Ereignisaktion erfolgen, mit der Aktion <<basics/automatisierung/ereignisaktionen#konfiguration, **Handelsvertreter dem Kunden zuordnen**>>. +
__**Wichtig**__: Der im Kontakt eingestellte Handelsvertreter wird nicht für die Aufträge des Kontakts herangezogen. Somit wird der Auftrag nicht in der Statistik **Umsatz nach Handelsvertreter** berücksichtigt. Damit der Handelsvertreter für einen Auftrag berücksichtigt wird, muss auch diese Zuordnung per Ereignisaktion erfolgen. Beachten Sie dazu die Hinweise zur Ereignisaktion <<basics/automatisierung/ereignisaktionen#konfiguration, **Handelsvertreter dem Auftrag zuordnen**>>.

|**Bewertung**
|Kontakt für interne Zwecke bewerten. Fünf rote Sterne stehen für die schlechteste und fünf gelbe Sterne für die beste Bewertung.

|**Kundennummer**
|Kundennummer für den Kontakt eingeben. Die Kundennummern können fortlaufend nummeriert werden oder nicht. Kundennummern werden nicht automatisch vergeben.

|**Eigner**
|Eigner für den Kontakt wählen. Wenn kein Eigner gewählt werden soll, die leere Option wählen.

|**Geburtsdatum**
|Geburtsdatum des Kontakts nach dem Muster dd.mm.yyyy eingeben oder aus dem Kalender wählen.

|**Newsletter**
|Zeigt an, ob der Kontakt den Newsletter erhält. Es ist nicht möglich, die Option manuell zu aktivieren. Um den Newsletter-Bezug für den Kontakt zu deaktivieren, Häkchen entfernen.

|**Gesperrt**
|Wählen, ob der Kontakt für den eingestellten Mandanten (Shop) gesperrt wird oder nicht. +
Wenn die Option aktiviert ist, ist der Kontakt gesperrt und kann sich nicht mehr im Webshop einloggen. Wenn die Option deaktiviert ist, kann sich der Kontakt im Webshop einloggen.

2+|Kontaktoptionen

|**Typ**
|Typ, z.B. E-Mail, Telefon oder Webseite, aus dem Dropdown-Menü wählen.

|**Subtyp**
|Subtyp, z.B. Arbeit, Privat oder Ansprechpartner, aus dem Dropdown-Menü wählen.

|**Wert**
|Wert eingeben.
|====

[#200]
== Kontakt suchen

Im Filterbereich auf der linken Seite haben Sie die Möglichkeit, Kontakte nach bestimmten Kriterien zu suchen. Die gefundenen Kontakte werden dann in der Übersicht im Bereich **Ergebnisse** angezeigt. Sie können die Kontaktdaten bearbeiten.

Um bestimmte Kontakte zu suchen, geben Sie die Ihnen bekannten Suchbegriffe in die Filter ein oder wählen Sie die Einstellungen der Dropdown-Menüs. Sie können dabei auch mehrere Suchbegriffe gleichzeitig in die Suchfelder eingeben. Dies ermöglicht Ihnen eine schnellere und genauere Suche.

[IMPORTANT]
.Suche über die E-Mail-Adresse
====
Bitte beachten Sie, dass aktuell nur die Suche über die E-Mail-Adresse möglich ist. Die anderen Suchoptionen werden nach und nach zur Verfügung gestellt.
====

[.instruction]
Kontakt suchen:

. Öffnen Sie das Menü **CRM » Kontakte**.
. Geben Sie im Filterbereich Suchbegriffe in die Suchfelder ein bzw. stellen Sie Filteroptionen in den Dropdown-Menüs ein. Beachten Sie dazu die Erläuterungen in Tabelle 2.
. Klicken Sie auf **Suchen**. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

.Filter für die Kontakte
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Suchen**
|Ohne gewählte Filtereinstellungen auf **Suchen** klicken, um alle Kontakte anzuzeigen. Alternativ die Suchergebnisse durch Filtereinstellungen eingrenzen und auf **Suchen** klicken. Die gefundenen Kontakte werden in der Übersicht angezeigt.

|**Reset**
|Eingestellte Filterkriterien zurücksetzen.

|**ID**
|Jeder Kontakt erhält automatisch eine fortlaufende und einzigartige ID. Dies ist unabhängig davon, ob der Eintrag manuell oder automatisch angelegt wurde. Zwei Kontakte haben somit nie die gleiche ID. Die ID entspricht immer einer echten Zahl. Ungültig sind z.B. "00521" oder "ADF8354".

|**Name**
|Vorname und/oder Nachname eingeben, um den Kontakt mit diesem Namen zu suchen.

|**E-Mail**
|Vollständige E-Mail-Adresse eingeben, um den Kontakt mit dieser E-Mail-Adresse zu suchen.

|**Anschrift**
|Straßenname, PLZ oder Ort eingeben, der im Kontakt gespeichert ist.

|**Land**
|Land wählen, um nur Kontakte aus diesem Land anzuzeigen. Das Land ist in den Kontaktdaten gespeichert.

|**Mandant (Shop)**
|Mandant (Shop) wählen, um nur Kontakte dieses Mandanten anzuzeigen. Der Mandant ist in den Kontaktdaten gespeichert. +
**__Wichtig__**: Variablen Benutzern stehen nur Mandanten zur Auswahl, für die sie eine Berechtigung haben. Berechtigungen werden im Tab <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90, **Berechtigung**>> unter **System » Einstellungen » Benutzer » Konten** eingestellt.
|====

[#300]
== Kontakt bearbeiten

Suchen Sie den Kontakt mit Hilfe der <<crm/_kontakte-verwalten#200, **Filtereinstellungen**>>. Öffnen Sie den Kontakt durch einen Klick auf die Zeile des Kontakts, um dessen Daten, wie z.B. Sprache, Klasse, Geburtsdatum, Telefonnummer und E-Mail-Adresse, zu bearbeiten. Erläuterungen zu den Einstellungen und Optionen in den Bereichen **Kontakt** und **Kontaktoptionen** finden Sie im Kapitel <<crm/_kontakte-verwalten#100, **Kontakt erstellen**>>.

[.instruction]
Kontakt bearbeiten:

. Öffnen Sie das Menü **CRM » Kontakte**.
. Geben Sie im Filterbereich Suchbegriffe in die Suchfelder ein bzw. stellen Sie Filteroptionen in den Dropdown-Menüs ein. Beachten Sie dazu die Erläuterungen in Tabelle 2 im Kapitel <<crm/_kontakte-verwalten#200, **Kontakt suchen**>>.
. Klicken Sie auf **Suchen**.
. Klicken Sie in die Zeile des Kontakts. +
→ Der Kontakt wird geöffnet.
. Nehmen Sie die Änderungen vor.
. **Speichern** Sie die Einstellungen.

////
h3>Kontakt anzeigen<a id="400." name="400."></a></h3>
<p>Im Bereich <strong>Kontakt</strong> finden Sie die grundlegenden Daten eines Kontakts wie z.B. Sprache, Klasse und Geburtsdatum. Im Bereich <strong>Kontaktoptionen</strong> speichern Sie Daten wie Telefonnummer, E-Mail-Adresse und Ansprechpartner. Erläuterungen zu den Einstellungen und Optionen in diesen Bereichen finden Sie im Kapitel <a href="#100."><strong>Kontakt erstellen</strong></a>.</p
////
[#500]
== Kontakt löschen

Sie haben die Möglichkeit, einzelne Kontakte im Menü **CRM » Kontakte** zu löschen. Alle dem Kontakt zugeordneten Adressen werden gelöscht, sofern diese nicht mit einem Auftrag verknüpft sind.

[.instruction]
Kontakt löschen:

. Öffnen Sie das Menü **CRM » Kontakte**.
. Suchen Sie den Kontakt anhand der <<crm/_kontakte-verwalten#200, **Filtereinstellungen**>>. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Öffnen Sie den Kontakt mit einem Klick in die Zeile des Kontakts.
. Klicken Sie im linken Bereich auf **Kontakt löschen**. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf **OK**. +
→ Der Kontakt wird gelöscht und aus der Übersicht entfernt.

[#600]
== Adressen anzeigen

Aus dem geöffneten Kontakt heraus lassen sich alle dem Kontakt zugehörigen Adressen in übersichtlichen Info-Boxen anzeigen. Anhand eines Tags innerhalb der Info-Box sehen Sie auf einen Blick, bei welcher der angegebenen Adressen es sich um die Rechnungsadresse und die Lieferadresse handelt.

[.instruction]
Adressen anzeigen:

. Öffnen Sie das Menü **CRM » Kontakte**.
. Suchen Sie den Kontakt anhand der <<crm/_kontakte-verwalten#200, **Filtereinstellungen**>>. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Öffnen Sie den Kontakt mit einem Klick in die Zeile des Kontakts.
. Klicken Sie im linken Bereich auf **Adressen**. +
→ Alle dem Kontakt zugehörigen Adressen werden angezeigt.

////
h3>Neue Adresse hinzufügen</h3>
<p>Dieser Menüpunkt ist aktuell noch nicht funktional.</p>

<h3>Aufträge anzeigen</h3>
<p>Dieser Menüpunkt ist aktuell noch nicht funktional.</p>

<h3>Neuen Auftrag hinzufügen</h3>
<p>Dieser Menüpunkt ist aktuell noch nicht funktional.</p
////

////
h3>Firma anzeigen</h3>
<p>TEXT</p>

<h3>Neue Firma hinzufügen</h3>
<p>TEXT</p
////

////
h3>Aufträge anzeigen</h3>
<p>Sie können im Tab <strong>Aufträge</strong> alle Aufträge des Kunden auflisten und bearbeiten oder neue Aufträge anlegen. Die Funktionen entsprechen denen im Menü <strong>Aufträge</strong>. Details zur Auftragsbearbeitung finden Sie daher auf der Handbuchseite <strong><a href="{% Link(2008) %}">Auftrag ändern</a></strong>.</p>

<h3>Neuen Auftrag hinzufügen</h3>
<p>TEXT</p
////

////
h3>Scheduler anzeigen</h3>
<p>Sie können im Tab <strong>Aufträge</strong> alle Aufträge des Kunden auflisten und bearbeiten oder neue Aufträge anlegen. Die Funktionen entsprechen denen im Menü <strong>Aufträge</strong>. Details zur Auftragsbearbeitung finden Sie daher auf der Handbuchseite <strong><a href="{% Link(2008) %}">Auftrag ändern</a></strong>.</p
////

////
h3>Eigenschaft eingeben<a id="1500." name="1500."></a></h3>
<p>Im Tab <strong>Eigenschaften</strong> stehen Ihnen die <a href="#400."><strong>zuvor erstellten Eigenschaften</strong></a> zur Verfügung, um wichtige Informationen zu Ihren Kunden zu speichern. Die Eigenschaften sind auch als frei konfigurierbare Textfelder verwendbar, die dann je nach Einstellung bei der Kundenregistrierung oder im Bestellvorgang eingesetzt werden.</p>

<h5>Eigenschaft eingeben:</h5>
<ol>
<li>Öffnen Sie das Menü <strong>CRM » Kunden bearbeiten</strong>.</li>
<li>Suchen Sie den Kunden anhand der <a href="#1100."><strong>Filtereinstellungen</strong></a>.</li>
<li>Öffnen Sie den Kunden.</li>
<li>Wechseln Sie in das Tab <strong>Eigenschaften</strong>.</li>
<li>Nehmen Sie die Einstellungen zu den Eigenschaften des Kunden vor.</li>
<li><strong>Speichern</strong> Sie die Einstellungen.</li>
</ol>

<h3>Notiz speichern</h3>
<p>Im Tab <strong>Notizen</strong> können Sie zu jedem Kunden Notizen speichern. Notizen sind nur in Ihrem plentymarkets Backend sichtbar, d.h. Kunden können die gespeicherten Notizen nicht im Webshop sehen.</p>

<h5>Notiz speichern:</h5>
<ol>
<li>Öffnen Sie das Menü <strong>CRM » Kunden bearbeiten</strong>.</li>
<li>Suchen Sie den Kunden anhand der <a href="#1100."><strong>Filtereinstellungen</strong></a>.</li>
<li>Öffnen Sie den Kunden.</li>
<li>Wechseln Sie in das Tab <strong>Notizen</strong>.</li>
<li>Geben Sie die Notiz ein.<br />→ Formatieren Sie ggf. die Notiz mit den Funktionen in der Symbolleiste.</li>
<li><strong>Speichern</strong> Sie die Einstellungen.</li>
</ol>

<p>Wenn Sie die Informationen, die Sie in der Notiz gespeichert haben, nicht mehr benötigen, entfernen Sie die Notiz mit einem Klick auf <strong>Löschen</strong>.</p>

<h3>Dokument hochladen</h3>
<p>Im Tab <strong>Dokumente</strong> laden Sie Dokumente zum Kunden hoch. Zulässig sind Datenformate wie JPEG, PNG, GIF, TIFF, PDF, DOC, ODC, OTH, XLS, XML, HTML, HTM, CSS, ZIP und GZIP.</p>

<h5>Dokument hochladen:</h5>
<ol>
<li>Öffnen Sie das Menü <strong>CRM » Kunden bearbeiten</strong>.</li>
<li>Suchen Sie den Kunden anhand der <a href="#1100."><strong>Filtereinstellungen</strong></a>.</li>
<li>Öffnen Sie den Kunden.</li>
<li>Wechseln Sie in das Tab <strong>Dokumente</strong>.</li>
<li>Klicken Sie auf <strong>Dateien hochladen</strong>.</li>
<li>Wählen Sie die Dokumente aus.</li>
<li>Klicken Sie auf <strong>Öffnen</strong>, um die Dateien hochzuladen oder ziehen Sie Dokumente per Drag-and-Drop-Funktion in das Tab.</li>
</ol>

<p>Wenn Sie die Option <strong>Alle auswählen</strong> aktivieren, stehen Ihnen die Buttons <strong>Vorschau</strong>, <strong>Herunterladen</strong> und <strong>Löschen</strong> in der Symbolleiste für alle hochgeladenen Dokumente zur Verfügung. Wenn kein Dokument gewählt ist, sind diese Buttons deaktiviert. Die Funktionen stehen Ihnen aber auch bei jedem Dokument einzeln zur Verfügung.<br />Wenn Sie nur einige der hochgeladenen Dokumente aktivieren möchten, klicken Sie in die obere linke Ecke des Dokuments. Deaktivieren Sie umgekehrt die obere linke Ecke des Dokuments, wenn Sie dieses wieder abwählen möchten.</p>

<h3>Kundenumsätze anzeigen</h3>
<p>Im Tab <strong>Konto</strong> sehen Sie die Umsätze Ihres Kunden. In der obersten Zeile sehen Sie die Summe der Rechnungen des Kunden, was Sie ihm in Form von Gutschriften gutgeschrieben haben und wie hoch die Differenz zwischen diesen beiden Beträgen ist.<br />In der Tabelle sind die Aufträge und Gutschriften zu diesem Kunden als Vorgänge aufgeführt. Dabei sind die Spalten <strong>Gezahlt</strong> und <strong>Ausstehend</strong> besonders hilfreich. Wenn bei einem Auftrag ein Betrag unter <strong>Ausstehend</strong> aufgeführt ist, muss der Kunde diesen Betrag noch an Sie zahlen. Sobald dies geschehen ist, wird der Betrag unter <strong>Gezahlt</strong> aufgeführt. Wenn bei einer Gutschrift noch ein Betrag unter <strong>Ausstehend</strong> aufgeführt ist, müssen Sie diesen Betrag noch an den Kunden zahlen. Sobald dies geschehen ist, wird der Betrag unter <strong>Gezahlt</strong> aufgeführt.</p>

<h5>Kundenumsätze anzeigen:</h5>
<ol>
<li>Öffnen Sie das Menü <strong>CRM » Kunden bearbeiten</strong>.</li>
<li>Suchen Sie den Kunden anhand der <a href="#1100."><strong>Filtereinstellungen</strong></a>.</li>
<li>Öffnen Sie den Kunden.</li>
<li>Wechseln Sie in das Tab <strong>Konto</strong>.</li>
<li>Beachten Sie die Erläuterungen in Tabelle 8.</li>
</ol>

<table>
<caption>Einstellungen im Menü <strong>CRM » Kunden bearbeiten » Kunde öffnen » Tab: Konto</strong></caption>
<tr>
<th>Einstellung</th>
<th>Erläuterung</th>
</tr>
<tr>
<td><strong>Saldo</strong></td>
<td>Zeigt den Kontostand des Kunden an.<br />	<strong>+</strong> = Summe der noch vom Kunden zu zahlenden Beträge<br />	<strong>-</strong> = Summe der noch an den Kunden zu zahlenden Beträge, wenn der Kunde zu viel gezahlt hat oder eine Gutschrift noch ausgezahlt werden muss.<br />	<strong>0,0</strong> = keine ausstehenden Beträge</td>
</tr>
<tr>
<td><strong>Rechnungen</strong></td>
<td>Summe der Rechnungsbeträge aller Aufträge und die Anzahl der Rechnungen in Klammern</td>
</tr>
<tr>
<td><strong>Gutschriften</strong></td>
<td>Summe aller Gutschriften und die Anzahl der Gutschriften in Klammern</td>
</tr>
<tr>
<td><strong>Delta</strong></td>
<td>Differenz in Prozent zwischen den gezahlten Gutschriften und dem insgesamt bezahlten Rechnungsbetrag des Kunden. Bei 0 % wurde dem Kunden noch keine Gutschrift ausgezahlt. Bei 100 % wurde dem Kunden jeder bezahlte Betrag wieder als Gutschrift zurückgezahlt.</td>
</tr>
<tr>
<td><strong>Datum</strong></td>
<td>Datum, an dem der Auftrag erstellt wurde</td>
</tr>
<tr>
<td><strong>Auftrags-ID</strong></td>
<td>ID des Auftrags. Ein Klick auf die ID öffnet die Detailansicht des Auftrags. IDs von Gutschriften sind eingerückt und unterhalb des Auftrags dargestellt.</td>
</tr>
<tr>
<td><strong>Vorgang</strong></td>
<td>Auftragsart, entweder Auftrag oder Gutschrift</td>
</tr>
<tr>
<td><strong>Dokument</strong></td>
<td>Dokumentnummer, z.B. Rechnungsnummer. Ein Klick auf die Nummer öffnet das Dokument.</td>
</tr>
<tr>
<td><strong>Wert</strong></td>
<td>Rechnungssumme des Auftrags</td>
</tr>
<tr>
<td><strong>Gezahlt</strong></td>
<td>Der bereits bezahlte Betrag</td>
</tr>
<tr>
<td><strong>Zahlungsart</strong></td>
<td>Zahlungsart des Auftrags</td>
</tr>
<tr>
<td><strong>Ausstehend</strong></td>
<td>Der zur vollständigen Bezahlung des Auftrags noch ausstehende Betrag.</td>
</tr>
<tr>
<td><strong>Status</strong></td>
<td>Status des Auftrags. Ein Klick auf den Status öffnet das Bearbeitungsfenster <strong>Auftragsstatus</strong>, in dem der Status geändert werden kann.</td>
</tr>
</table>

<strong class="subhead">Kontodaten filtern</strong>
<p>Verwenden Sie Filter, um die Umsätze Ihrer Kunden anzeigen zu lassen.</p>

<h5>Kontodaten filtern:</h5>
<ol>
<li>Öffnen Sie das Menü <strong>CRM » Kunden bearbeiten</strong>.</li>
<li>Suchen Sie den Kunden anhand der <a href="#1100."><strong>Filtereinstellungen</strong></a>.</li>
<li>Öffnen Sie den Kunden.</li>
<li>Wechseln Sie in das Tab <strong>Konto</strong>.</li>
<li>Nehmen Sie die Filtereinstellungen im Tab <strong>Filter</strong> vor. Beachten Sie dazu die Erläuterungen in Tabelle 9.</li>
<li>Klicken Sie auf <strong>Suchen</strong>.</li>
</ol>

<table>
<caption>Filtereinstellungen im Menü <strong>CRM » Kunden bearbeiten » Kunde öffnen » Tab: Konto</strong></caption>
<tr>
<th>Einstellung</th>
<th>Erläuterung</th>
</tr>
<tr>
<td><b>Suchen</b></td>
<td>Suche ausführen. Die gefundenen Kontodaten werden im Tab <strong>Konto</strong> aufgelistet.</td>
</tr>
<tr>
<td><b>Reset</b></td>
<td>Eingestellte Filterkriterien zurücksetzen.</td>
</tr>
<tr>
<td><b>Zeitraum</b></td>
<td>Eine der folgenden Einstellungen aus dem Dropdown-Menü wählen: <strong>ALLE</strong>, <strong>Dieses Jahr</strong>, <strong>Letztes Jahr</strong>, <strong>Diesen Monat</strong>, <strong>Letzten Monat</strong> oder <strong>Letzte 3 Monate</strong>.</td>
</tr>
<tr>
<td><b>Ausstehend</b></td>
<td><strong>ALLE</strong>, <strong>Ja</strong> oder <strong>Nein</strong> wählen.<br /><strong>Ja</strong> = Nur ausstehende Beträge werden angezeigt.<br /><strong>Nein</strong> = Nur gezahlte Beträge werden angezeigt.<br /><strong>ALLE</strong> = Ausstehende und gezahlte Beträge werden angezeigt.</td>
</tr>
<tr>
<td><b>Vergleichsoperator / Status</b></td>
<td>Vergleichsoperator und Auftragsstatus wählen.</td>
</tr>
<tr>
<td><b>Rechnungsnr.</b></td>
<td>Rechnungsnummer eingeben.</td>
</tr>
<tr>
<td><b>Auftrags-ID</b></td>
<td>Auftrags-ID eingeben.</td>
</tr>
</table>

<h3>Events anzeigen</h3>
<p>Im Tab <strong>Events</strong> speichern Sie die Events mit dem Kunden. Dies kann z.B. ein Anruf oder eine E-Mail sein. Sie können dort die Dauer eingeben, eine Information zum Vorgang wählen und einen Kommentar zum Event in das Textfeld eingeben. Dieser Kommentar wird dann in der Übersicht unter <strong>Info</strong> angezeigt. Für kostenpflichtige Events aktivieren Sie die Option <strong>Abrechnen</strong>.</p
////

////
h3>Lieferanschrift eingeben</h3>
<p>Im Tab <strong>Lieferanschriften</strong> geben Sie die Lieferanschriften des Kunden ein. Sie können mehrere Lieferanschriften eingeben und diese Lieferanschriften dann pro Auftrag individuell zuordnen.</p>

<h5>Lieferanschrift eingeben:</h5>
<ol>
<li>Öffnen Sie das Menü <strong>CRM » Kunden bearbeiten</strong>.</li>
<li>Suchen Sie den Kunden anhand der <a href="#1100."><strong>Filtereinstellungen</strong></a>.</li>
<li>Öffnen Sie den Kunden.</li>
<li>Wechseln Sie in das Tab <strong>Lieferanschriften</strong>.</li>
<li>Klicken Sie auf <strong>Neue Lieferadresse anlegen</strong>.</li>
<li>Klappen Sie den Bereich <strong>Neue Lieferadresse anlegen</strong> auf.</li>
<li>Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 10.</li>
<li><strong>Speichern</strong> Sie die Einstellungen.</li>
</ol>

<table>
<caption>Einstellungen im Menü <strong>CRM » Kunden bearbeiten » Kunde öffnen » Tab: Lieferanschriften</strong></caption>
<tr>
<th>Einstellung</th>
<th>Erläuterung</th>
</tr>
<tr>
<td colspan="2" class="th">Adresse</td>
</tr>
<tr>
<td><b>Firma (Name 1)</b></td>
<td>Firmenname eingeben, falls vorhanden.</td>
</tr>
<tr>
<td><b>Vorname (Name 2)</b></td>
<td>Vorname eingeben.</td>
</tr>
<tr>
<td><b>Nachname (Name 3)</b></td>
<td>Nachname eingeben.</td>
</tr>
<tr>
<td><b>Zusatz (Name 4)</b></td>
<td>Ggf. Zusatzangaben zum Empfänger eingeben, z.B. z.Hd. Herrn Max Mustermann.</td>
</tr>
<tr>
<td><b>Straße (Adresse 1)</b></td>
<td>Straße, Packstation oder Postfiliale eingeben.</td>
</tr>
<tr>
<td><b>Hausnummer (Adresse 2)</b></td>
<td>Hausnummer oder ID der Packstation eingeben.</td>
</tr>
<tr>
<td><b>Zusatz (Adresse 3)</b></td>
<td>Ggf. Adresszusatz eingeben, z.B. Apartment 12a.<br />Kunden können diese Angabe auch selbst im Bestellvorgang und im Mein Konto-Bereich eingeben.<br /><b><i>Hinweis</b></i>: Einige Versanddienstleister verarbeiten dieses Feld nicht. Das bedeutet, dass der Zusatz nicht auf dem Etikett erscheint. Dies kann dazu führen, dass eine Sendung nicht zugestellt werden kann. Zu folgenden Versanddienstleistern wird der Adresszusatz derzeit nicht übermittelt:<br /> DHL Freight<br /> DHL Supply Chain<br /> Swiss Post<br />			Um Kunden darüber zu informieren, in den genannten Bereichen z.B. einen Hinweis eingeben oder das Feld fallabhängig einblenden, z.B. per JavaScript-Skript.</td>
</tr>
<tr>
<td><b>Frei (Adresse 4)</b></td>
<td>Feld zur freien Verfügung.</td>
</tr>
<tr>
<td><b>Postleitzahl</b></td>
<td>Postleitzahl eingeben.</td>
</tr>
<tr>
<td><b>Ort</b></td>
<td>Ort eingeben.</td>
</tr>
<tr>
<td><b>Land</b></td>
<td>Land aus dem Dropdown-Menü wählen.</td>
</tr>
<tr>
<td><b>Region/Bezirk</b></td>
<td>Region aus dem Dropdown-Menü wählen.<br />Je nach Land können hier z.B. Bundesstaaten oder Bundesländer gewählt werden.<br/>Wenn zu einem Land keine Regionen oder Bezirke verfügbar sind, ist das Dropdown-Menü deaktiviert. In der Kaufabwicklung und im Mein Konto-Bereich wird diese Option auch bei der Lieferanschrift angezeigt. Die Angabe kann in bestimmten Fällen notwendig sein, z.B. für PayPal in den USA.</td>
</tr>
<tr>
<td colspan="2" class="th">Adressoptionen</td>
</tr>
<tr>
<td><b>Umsatzsteuer-Identifikationsnummer</b></td>
<td>Umsatzsteuer-Identifikationsnummer eingeben, falls vorhanden.</td>
</tr>
<tr>
<td><b>Externe Adress-ID</b></td>
<td>Externe Adress-ID eingeben, falls vorhanden.</td>
</tr>
<tr>
<td><b>Gelangensbestätigung</b></td>
<td>Option aktivieren, um Aufträge von Kunden im EU-Ausland, die an eine inländische Lieferanschrift versendet werden, wie EU-Auslandslieferungen zu behandeln. Bei aktivierter Option werden Rechnungen für Aufträge aus dem EU-Ausland mit Lieferanschrift innerhalb Deutschlands gemäß den Einstellungen <strong>Umsatzsteuer-ID</strong> und <strong>Ausfuhrlieferung</strong> im Menü <a href="{% Link(2010) %}"><strong>System » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung</strong></a> ausgestellt. Ist die Option nicht aktiviert, werden diese Aufträge brutto berechnet.<br />	Für Anschriften, für die eine Gelangensbestätigung erforderlich ist, eine eigene Lieferanschrift anlegen und die Option aktivieren.<br /><i><b>Wichtig</i></b>: Wenn bei zukünftigen Aufträgen keine Gelangensbestätigung mehr gewünscht ist, diese Option nicht deaktivieren, sondern eine weitere Lieferanschrift ohne Aktivierung der Option anlegen. Sonst kommt es zu Fehlberechnungen früherer Aufträge mit dieser Lieferanschrift.</td>
</tr>
<tr>
<td><b>Telefon</b></td>
<td>Telefonnummer eingeben.</td>
</tr>
<tr>
<td><b>E-Mail</b></td>
<td>E-Mail-Adresse eingeben.</td>
</tr>
<tr>
<td><b>Postnummer</b></td>
<td>DHL PostNummer eingeben.</td>
</tr>
<tr>
<td><b>Personennummer</b></td>
<td>Personennummer eingeben. Die Personennummer wird von skandinavischen Endkunden für skandinavische Zahlungsanbieter (z.B. Klarna) benötigt.</td>
</tr>
<tr>
<td><b>Altersfreigabe</b></td>
<td>Altersfreigabe aus dem Dropdown-Menü wählen.</td>
</tr>
</table
////

////
h3>Einstellungen anzeigen und bearbeiten</h3>
<p>Im Tab <strong>Einstellungen</strong> werden die Bankdaten, Passwort, Login-URL sowie Kostenstellen und Provisionen des Kunden gespeichert. Welche Einstellungen Sie in den Tabs <strong>Bankdaten</strong>, <strong>Passwort</strong>, <strong>Login-URL</strong>, <strong>Kostenstellen</strong> und <strong>Provisionen</strong> vornehmen können, wird in den folgenden Unterkapiteln beschrieben.</p>

<h4>Bankdaten pflegen</h4>
<p>Im Tab <strong>Bankdaten</strong> können Sie die Bankdaten des Kunden eingeben und diese bei Bedarf löschen. Die Bankdaten benötigen Sie z.B. für die Zahlungsart <strong>Lastschrift</strong>. Sie haben auch die Möglichkeit, die Bankdaten in plentymarkets zu importieren. Nutzen Sie dazu das Datenformat <a href="{% Link(880) %}"><strong>Customer</strong></a>. Beachten Sie dabei die aktuelle Rechtslage, auch in anderen Lieferländern.</p>

<div class="plentyInfoBox plentyIsImportant"><div class="plentyInfoBoxHeader">Abo-Aufträge beachten</div>
<div class="plentyInfoBoxContent"><p>Beachten Sie, dass die hier eingegebenen Bankdaten auch für Abo-Aufträge mit der Zahlungsart <strong>Lastschrift</strong> verwendet werden. Wenn Sie Bankdaten löschen, die mit einem solchen Abo-Auftrag verbunden sind, wird die Zahlungsart im <strong><a href="{% Link(674) %}">Scheduler</a></strong> auf die für den Mandanten (Shop) festgelegte <a href="{% Link(1639) %}"><strong>Standardzahlungsart</strong></a> zurückgesetzt. Der Abo-Auftrag wird dann nicht mehr per Bankeinzug beglichen. Löschen Sie die Bankdaten in einem solchen Fall daher nur, wenn dies wirklich erforderlich ist, und geben Sie wenn möglich neue Bankdaten für den Kunden ein.</p></div></div>

<h4>Neues Passwort vergeben</h4>
<p>Im Tab <strong>Passwort</strong> geben Sie im Bereich <strong>Passwort ändern</strong> ein neues Passwort für den Kunden ein. Ob Sie das Passwort an den Kunden senden oder nicht, können Sie mit einem Klick auf <strong>E-Mail an Kunden versenden</strong> im Bereich <strong>Passwort zurücksetzen</strong> entscheiden.</p>
<p>Bei nicht erfolgreichem E-Mail-Versand prüfen Sie die <a href="{% Link(3386) %}#100."><strong>Zugangsdaten</strong></a>. Im Menü <a href="{% Link(680) %}"><strong>Daten » API-Log</strong></a> werden die Fehlermeldungen zum Vorgang <strong>E-Mail</strong> gespeichert.</p>

<p>Ein neues Passwort für alle Ihre Kunden generieren Sie im Menü <strong>System » Kunden » Passwörter</strong>. Weitere Information finden Sie im Kapitel <a href="#3100."><strong>Passwörter für alle Kunden neu generieren</strong></a>.</p>

<h4>Login-URL einsehen</h4>
<p>Im Tab <strong>Login-URL</strong> wird die URL für einen direkten Zugang zum Konto des Kunden im Webshop angezeigt. Wenn diese URL verwendet wird, ist eine Eingabe der Login-Daten (E-Mail-Adresse und Passwort) im Webshop nicht mehr nötig. Damit die Login-URL erzeugt wird, muss die E-Mail-Adresse im Menü <strong>CRM » Kunden bearbeiten » Kunde öffnen » Tab: Kundendaten</strong> im Feld <strong>E-Mail</strong> und das Passwort im Menü <strong>CRM » Kunden bearbeiten » Kunde öffnen » Tab: Einstellungen » Tab: Passwort</strong> eingegeben werden. Nach dem Speichern wird die Login-URL erzeugt. Verwenden Sie ein sicheres Passwort, andernfalls wird eine Fehlermeldung ausgegeben.</p>

<h4>Kostenstelle anlegen</h4>
<p>Im Tab <strong>Kostenstellen</strong> legen Sie Kostenstellen. Sie haben auch die Möglichkeit, bereits angelegte Kostenstellen zu bearbeiten. Bei einer Kostenstelle handelt es sich um den Ort der Kostenentstehung und Kostenzurechnung, quasi ein betrieblicher Bereich, der selbstständig abgerechnet wird.</p>

<h5>Kostenstelle anlegen:</h5>
<ol>
<li>Öffnen Sie das Menü <strong>CRM » Kunden bearbeiten</strong>.</li>
<li>Suchen Sie den Kunden anhand der <a href="#1100."><strong>Filtereinstellungen</strong></a>.</li>
<li>Öffnen Sie den Kunden.</li>
<li>Wechseln Sie in das Tab <strong>Einstellungen</strong>.</li>
<li>Öffnen Sie das Tab <strong>Kostenstellen</strong>.</li>
<li>Öffnen Sie das Tab <strong>Neue Kostenstelle</strong>.</li>
<li>Geben Sie den Namen für die Kostenstelle ein.</li>
<li>Geben Sie das Budget für die Kostenstelle ein.</li>
<li>Geben Sie das Restbudget für die Kostenstelle ein.</li>
<li>Wählen Sie die <strong>Budgetperiode</strong> für das eingegebene Budget.</li>
<li><strong>Speichern</strong> Sie die Einstellungen.<br /> → Die angelegte Kostenstelle finden Sie dann im Tab <strong>Kostenstellen</strong>.</li>
</ol>

<h4>Provision eingeben</h4>
<p>Im Tab <strong>Artikelprovisionen</strong> geben Sie artikelbezogene Provisionen für den Kundentyp <strong>Handelsvertreter</strong> ein. Gehen Sie wie im Folgenden beschrieben vor, um Werte für Provisionen einzugeben.</p>

<h5>Provision eingeben:</h5>

<ol>
<li>Öffnen Sie das Menü <strong>CRM » Kunden bearbeiten</strong>.</li>
<li>Suchen Sie den Kunden anhand der <a href="#1100."><strong>Filtereinstellungen</strong></a>.</li>
<li>Öffnen Sie den Kunden.</li>
<li>Wechseln Sie in das Tab <strong>Einstellungen</strong>.</li>
<li>Öffnen Sie das Tab <strong>Provisionen</strong>.</li>
<li>Öffnen Sie das Tab <strong>Artikelprovisionen</strong>.</li>
<li>Klappen Sie den Bereich <strong>Neue Provision</strong> auf.</li>
<li>Geben Sie die <strong>Artikel-ID</strong> des Artikels ein, für den Sie eine oder mehrere Provision(en) eingeben möchten.</li>
<li>Geben Sie die Provision(en) in Prozent ein.<br />	→  Sie können bis zu vier Provisionen pro Eintrag eingeben.</li>
<li><strong>Speichern</strong> Sie die Einstellungen.<br /> → Die Provision wird gespeichert. Damit Sie auf einen Blick erkennen können, um welchen Artikel es sich handelt, wird nach erneutem Laden des Kundendatensatzes zusätzlich der Name des Artikels in der Übersicht angezeigt.</li>
</ol
////
[#700]
== Historie anzeigen

In jedem Datensatz können Sie die Historie eines Kontakts einsehen. Die Historie beinhaltet z.B. das Datum, seit dem der Kontakt bei Ihnen registriert ist, wann er das letzte Mal in Ihrem Webshop eingeloggt war und wann der letzte Auftrag generiert wurde. Die Daten werden automatisch angepasst und können nicht geändert werden.

[.instruction]
Historie anzeigen:

. Öffnen Sie das Menü **CRM » Kontakte**.
. Geben Sie im Filterbereich Suchbegriffe in die Suchfelder ein bzw. stellen Sie die Filteroptionen in den Dropdown-Menüs ein. Beachten Sie dazu die Erläuterungen in Tabelle 2 im Kapitel <<crm/_kontakte-verwalten#200, **Kontakt suchen**>>.
. Klicken Sie auf **Suchen**.
. Klicken Sie in die Zeile des Kontakts. +
→   Der Kontakt wird geöffnet und die Historie wird angezeigt.
. Beachten Sie die Erläuterungen zur Historie in Tabelle 3.

.Historie im Menü **CRM » Kontakte » Kontakt öffnen**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Registriert seit**
|Datum und Uhrzeit, seit wann der Kontakt registriert ist.

|**Aktualisiert**
|Datum und Uhrzeit, wann die Daten des Kontakts das letzte Mal aktualisiert wurden.

|**Letzter Login**
|Datum und Uhrzeit des letzten Login.

|**Letzter Auftrag**
|Datum und Uhrzeit, wann der letzte Auftrag eingegangen ist. Die Auftrags-ID wird ebenfalls angezeigt. Mit einem Klick auf die ID wird der Auftrag geöffnet. Wenn noch kein Auftrag eingegangen ist, steht in diesem Feld **Keine Daten**.

|**Zugangsart**
|Art, wie sich der Kontakt registriert hat. **Regulärer Zugang** bedeutet, dass sich der Kontakt neu registriert hat. **Gastzugang** bedeutet, dass sich der Kontakt als Gast angemeldet und bestellt hat.
|====
