= Kundendaten verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kundenklasse, Kundentyp, Kundendatensatz, Kunden bearbeiten, Kunden suchen, Kunde löschen, Bewegungsdaten, Offene Posten, Rabattsystem, USt-IdNr.
:description: Erfahren Sie, wie Sie Kundendaten in plentymarkets erstellen und verwalten.
:position: 50

Im Menü *CRM » Kunden bearbeiten* erstellen Sie <<crm/kundendaten-verwalten#800, Kundendatensätze>> und speichern dort alle Informationen Ihrer Kunden – von den Adressdaten über Lieferanschriften, Bankdaten bis hin zu Dokumenten wie Rechnungen und Notizen.

Im Menü *System » CRM* erstellen Sie z.B. <<crm/kontakte-verwalten#15, Kundenklassen>>, <<crm/kontakte-verwalten#20, Kundentypen>> und <<crm/kundendaten-verwalten#400, Eigenschaften>> und generieren neue <<crm/kundendaten-verwalten#3100, Passwörter>> für all Ihre Kunden. Erfahren Sie außerdem, wie Sie das <<crm/kontakte-verwalten#25, Rabattsystem>> in plentymarkets nutzen. Behalten Sie im Menü *CRM » OP-Liste* die Kontrolle über noch <<crm/kundendaten-verwalten#3600, nicht bezahlte Aufträge>>.

[NOTE]
.Kundendaten exportieren, importieren und aktualisieren
====
Exportieren Sie die Daten Ihrer Kontakte über den Elastischen Export. Voraussetzung dafür ist, dass Sie die Plugins link:https://marketplace.plentymarkets.com/plugins/integration/ElasticSync_4750[ElasticSync^] und link:https://marketplace.plentymarkets.com/plugins/markets/ElasticExport_4763[Elastischer Export^] installieren und bereitstellen. Beide Plugins sind im link:https://marketplace.plentymarkets.com/[plentyMarketplace^] verfügbar.

Das Format für den Export erstellen Sie im Menü *Daten » FormatDesigner*. Einen neuen Export erstellen Sie im Menü *Daten » Elastischer Export*. Dort wählen Sie das über den FormatDesigner erstellte Format aus der Dropdown-Liste und exportieren die Daten anschließend in eine CSV-Datei. Ihnen stehen zahlreiche Filteroptionen für den Export zur Verfügung. Exportieren Sie z.B. nur Daten von Kunden, die Sie mit 3 Sternen bewertet haben, oder nur Kunden, die einem bestimmten Eigner zugeordnet sind.

Importieren Sie die Daten Ihrer Kontakte im Menü *CRM » Kunden* inklusive Adressoptionen, Kontaktoptionen und Firmendaten über das ElasticSync-Plugin. Installieren Sie mindestens Version 2.1 des Plugins. Weitere Informationen stehen Ihnen im link:https://marketplace.plentymarkets.com/de/plugins/integration/ElasticSync_4750[User Guide^] des ElasticSync-Plugins zur Verfügung.
====

[#100]
== Kundenklasse erstellen

Mit Kundenklassen unterteilen Sie Ihren Kundenstamm nach unterschiedlichen Kriterien. So können Sie eine Kundenklasse festlegen, die an Endkunden (B2C) angepasst ist und mit deren Einstellungen die Artikel mit Bruttopreisen im Webshop angezeigt werden. Für Händler (B2B) erstellen Sie eine weitere Kundenklasse, mit deren Einstellungen die Artikel mit Nettopreisen im Webshop angezeigt werden. Weitere Optionen, die festgelegt werden können, sind z.B. Rabatte auf den Nettowarenwert, Rabatte auf die Zahlungsart oder Rabattstaffeln, die nur für eine bestimmte Kundenklasse gelten.

Erstellen Sie Kundenklassen im Menü *System » CRM » Kundenklassen*. Die dort erstellten Kundenklassen stehen dann zur Auswahl in den Kundendaten zur Verfügung. Wird keine Auswahl getroffen, wird in den Kundendaten die Kundenklasse mit der niedrigsten Position automatisch zugeordnet.

[TIP]
.Tipp: Typen und Klassen erstellen
====
Für die Einteilung Ihres Kundenstamms in Typen und Klassen ist es empfehlenswert, ein Konzept zu entwickeln, bevor Sie größere Mengen an Kundendaten erstellen. Damit vermeiden Sie späteren Änderungsaufwand, z.B. wenn Typen und Klassen bei fehlender Konfiguration automatisch zugewiesen werden. Überlegen Sie, welche Typen und Klassen Sie benötigen, erstellen Sie die Typen und Klassen und weisen sie Ihren Kunden zu.
====

Sie können beliebig viele Kundenklassen erstellen und individuell konfigurieren. Kundenklassen erhalten automatisch eine ID, die in der Übersicht vor dem Namen der Kundenklasse angezeigt wird. Die ID bestimmt jedoch keine Reihenfolge, diese wird durch die Option *Position* festgelegt.

Wird eine neue Kundenklasse erstellt, wird die Kundenklasse in der Übersicht im Tab *Kundenklassen* angezeigt. Nach Änderungen laden Sie das Menü neu, damit die neuen Einstellungen in der Übersicht sichtbar sind.

[.instruction]
Kundenklasse erstellen:

. Öffnen Sie das Menü *System » CRM » Kundenklassen*.
. Wechseln Sie in das Tab *Neue Kundenklasse*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-kundenklasse-erstellen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-kundenklasse-erstellen]]
.Einstellungen im Menü *System » CRM » Kundenklassen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Mindestbestellmenge*
|Mindestbestellmenge eingeben, wenn pro Artikel eine bestimmte Anzahl bestellt werden muss oder um eine Mindestbestellmenge für die Mengenrabatte zu gewährleisten.

|*Bezeichnung*
|Bezeichnung für die neue Kundenklasse eingeben, z.B. *Großhändler* oder *Premiumkunde*.

|*Position*
|Wenn keine Zahl eingegeben wird, wird eine Position automatisch anschließend an die höchste vorhandene Position vergeben. In erster Linie dient die Position der Sortierung der Kundenklassen im Menü. Dies ist z.B. in Kombination mit der Gestaltung der Sichtbarkeit der Artikelpreise im Webshop wichtig. Dies wird unter *Anzeige der Preise im Webshop* eingestellt.

|*Zahlungsziel*
|Zahlungsziel in Tagen eingeben, das für diese Kundenklasse gelten soll. Ein beim Kunden im Tab *Kundendaten* gespeichertes Zahlungsziel hat Priorität vor diesem Zahlungsziel. Ein Zahlungsziel kann weiterhin optional im <<auftragsabwicklung/auftraege/auftragsdokumente#, Auftragsdokumenten>> wie z.B. <<auftragsabwicklung/auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnungen>> gespeichert werden. Dieses Zahlungsziel wird dann in der Rechnung ausgegeben, wenn für einen Kunden und die Kundenklasse kein Zahlungsziel gespeichert wurden. Dazu die Box *Info: Gestaltung von Zahlungsbedingungen* unterhalb von <<tabelle-kundendatensatz-erstellen>> im Kapitel <<crm/kundendaten-verwalten#800, Kundendatensatz erstellen>> beachten.

|*Kunden-ID*
|Kunden-ID des Kunden eingeben, an den Sammelrechnungen bei <<auftragsabwicklung/auftraege/sammelauftraege#, Sammelaufträgen>> geschickt werden sollen. Die Sammelaufträge werden kundenklassenspezifisch angelegt und die Rechnung wird an den Kunden gesendet.

|*Rabattart*
|Rabattart wählen. Je nach Rabattart werden mehr oder weniger Optionen eingeblendet. Wenn Sie keinen Rabatt wünschen, wählen Sie die Option *Kein Rabatt*. Weitere Informationen sowie Erläuterungen zu den Rabattarten in plentymarkets finden Sie im Kapitel <<crm/kontakte-verwalten#25, Rabattsystem nutzen>>.

|*Mengenrabatt*
|Wählen, ob der im Menü *System » Artikel » Verkaufspreise* eingegebene Wert unter *Ab Menge* berücksichtigt werden soll oder nicht.

|*Erlaubte Zahlungsarten*
|Wählen, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen. +
In der Grundeinstellung sind alle verfügbaren Zahlungsarten erlaubt. Werden neue Zahlungsarten integriert, müssen diese Zahlungsarten hier erlaubt werden, da neue Zahlungsarten nicht automatisch mit in die Erlaubnisliste aufgenommen werden. +
*_Wichtig_*: Dabei die Einstellungen hinsichtlich der <<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, gesperrten Zahlungsarten in den Versandprofilen>> beachten, die für die Kundenklasse verwendet wird, bzw. diese Einstellung prüfen, damit es an dieser Stelle nicht zu ungewollten Überschneidungen kommt. Die Zahlungsart, die für eine Kundenklasse erlaubt sein soll, darf in den Versandprofilen nicht gesperrt sein und auch die Kundenklasse darf dort nicht gesperrt sein.

|*Zahlungshinweis*
|Ein hier eingegebener Zahlungshinweis wird auf Einzelrechnungen angezeigt. Das können z.B. besondere Angaben zur Zahlung für eine bestimmte Kundenklasse sein.

|*Anzeige der Preise im Webshop*
|Wählen, ob die Preise im Webshop *Brutto* oder *Netto* angezeigt werden sollen. +
*_Wichtig_*: Diese Option legt nur die Anzeige der Preise fest, nicht die Berechnung der Preise für die Kundenklasse. Einstellung besonders für die Kundenklasse der Position 1 beachten, da diese Kunden automatisch zugewiesen wird, wenn keine Kundenklasse in den Kundendaten gewählt wurde.
|====

Sie können Verkaufspreise mit Kundenklassen verknüpfen. Wählen Sie dazu im Menü *System » Artikel » Verkaufspreise* unter der Einstellung *Klasse* eine von Ihnen erstellte Kundenklasse. Weitere Informationen finden Sie auf der Handbuchseite <<artikel/artikel-verwalten#, Artikel verwalten>> im Kapitel <<artikel/artikel-verwalten#870, Verkaufspreise verwalten>>.

[#200]
== Kunden einer Kundenklasse suchen

Auch für die Suche nach bestimmten Kunden können Sie die Zuordnung der Kunden zu Kundenklassen nutzen und diese Kundenklassen im Menü *CRM » Kunden bearbeiten* mit dem Suchfilter *Klasse* gezielt suchen.

[.instruction]
Kunden einer Kundenklasse suchen:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Wählen Sie im Tab *Filter* aus der Dropdown-Liste *Klasse* die Kundenklasse, um alle Kunden dieser Kundenklasse anzuzeigen.
. Klicken Sie auf *Suchen*. +
→ Alle Kundendatensätze mit der gewählten Kundenklasse werden im Tab *Kunden* aufgelistet.

[#300]
== Kundentyp erstellen

Kundentypen dienen der Einordnung und Unterscheidung von Kunden. Einige Typen sind bereits standardmäßig in Ihrem plentymarkets System angelegt und können nicht gelöscht werden. Diese Typen sind *Kunde*, *Handelsvertreter*, *Lieferant*, *Partner*, *Hersteller* und *Interessent*. Die erstellten Kundentypen stehen im Menü *CRM » Kunden bearbeiten* im Tab *Filter* in der Dropdown-Liste *Typ* zur Verfügung.

In den Kundendaten ist automatisch der Kundentyp *Kunde* als Standard eingestellt. Kunden des Kundentyps *Lieferant* stehen als Lieferanten zur Verfügung, z.B. im Tab *Lieferant* einer Variante. Weitere, eigene Kundentypen erstellen Sie im Menü *System » CRM » Typen*.

Gehen Sie wie im Folgenden beschrieben vor, um Kundentypen zu erstellen.

[.instruction]
Kundentyp erstellen:

. Öffnen Sie das Menü *System » CRM » Typen*.
. Klicken Sie auf *Typ hinzufügen*.
. Geben Sie einen Namen ein.
. *Speichern* Sie die Einstellungen.

[.subhead]
Kundentyp löschen

Gehen Sie wie im Folgenden beschrieben vor, um erstellte Kundentypen, die Sie nicht mehr benötigen, zu löschen. Beachten Sie, dass die standardmäßig vorhandenen Kundentypen nicht gelöscht werden können.

[.instruction]
Kundentyp löschen:

. Öffnen Sie das Menü *System » CRM » Typen*.
. Klicken Sie auf *Löschen*.
. Bestätigen Sie die Sicherheitsabfrage.

[#400]
== Eigenschaft erstellen

Im Menü *System » CRM » Eigenschaften* erstellen Sie Eigenschaften, die Sie im Anschluss für die nähere Charakterisierung Ihrer Kunden nutzen. Für die spätere Verwendung der Eigenschaften haben Sie 2 Möglichkeiten: Sie können die Informationen entweder im Bestellvorgang oder in der Kundenregistrierung von Ihren Kunden abfragen oder Sie nutzen die Eigenschaften, um selbst Informationen zu den Kunden im Kundendatensatz zu speichern.

Im Fall der Abfrage vom Kunden bestimmen Sie, ob die Angabe ein Pflichtfeld ist und somit zwingend durch den Kunden eingegeben werden muss. Sie können beispielsweise bei der Registrierung abfragen, wie der Kunde auf Ihren Webshop aufmerksam geworden ist. Für die Eigenschaft wählen Sie dann als *Typ* die Option *Text einzeilig* oder die Option *Text mehrzeilig*, damit der Kunde die Information dort eingeben kann.

Gehen Sie wie im Folgenden beschrieben vor, um eine Kundeneigenschaft zu erstellen.

[.instruction]
Eigenschaft erstellen:

. Öffnen Sie das Menü *System » CRM » Eigenschaften*.
. Wechseln Sie in das Tab *Neue Eigenschaft*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-eigenschaft-erstellen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-eigenschaft-erstellen]]
.Einstellungen im Menü *System » CRM » Eigenschaften » Tab: Neue Eigenschaft*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
|Name der Eigenschaft, der z.B. im Bestellvorgang, angezeigt wird.

|*Name / Sprache*
|Nachdem eine Eigenschaft erstellt und gespeichert wurde, kann man diese Eigenschaft auch zu einer <<crm/kundendaten-verwalten#600, multilingualen Eigenschaft>> machen.

|*Typ*
|Die Einstellung des Typs legt fest, welche Art von Information für die Eigenschaft einzugeben ist. Eine der folgenden Optionen wählen: *Zahl*, *Auswahl*, *Text einzeilig*, *Text mehrzeilig*, *Datum* oder *Kundentyp*.

|*Auswahl*
|Nur sichtbar, wenn unter *Typ* die Einstellung *Auswahl* gewählt wurde. Dort können beliebig viele Eigenschaftswerte eingegeben werden. +
Eine Dropdown-Liste mit unterschiedlichen Auswahlmöglichkeiten wird für die Eigenschaft erstellt. Diese Dropdown-Liste wird dann z.B. im Bestellvorgang angezeigt. +
*Name* = Name für den Eigenschaftswert eingeben. +
*Wert* = Zahl zwischen 0 und 50 eingeben. Bei fortlaufenden Zahlenwerten wird eine aufsteigende Sortierung erreicht. Bestimmt die Reihenfolge, in der die Werte in der Dropdown-Liste angezeigt werden. +
*Wert hinzufügen* = Weitere Felder hinzufügen.

|*Kundentyp*
|Nur sichtbar, wenn unter *Typ* die Einstellung *Kundentyp* gewählt wurde. Hier ist eine Mehrfachauswahl möglich. Einer Eigenschaft können mehrere Kundentypen zugewiesen werden. Zur Verfügung stehen die im System standardmäßig verfügbaren Kundentypen sowie die <<crm/kontakte-verwalten#20, zusätzlich erstellten Kundentypen>>.

|*Position*
|Position für die Eigenschaft aus der Dropdown-Liste wählen. Fortlaufende Positionsnummern für die Eigenschaften vergeben, um eine bestimmte Reihenfolge zu erhalten.

|*Pflichtfeld*
|Aktivieren, damit die Eigenschaft zu einer Pflichteingabe wird. +
Ist die Eigenschaft als Pflichtfeld deklariert, wird die Eigenschaft in den Kundendaten im Tab *Eigenschaften* bzw. im Bestellvorgang fett markiert. Im ersten Fall ist in den Kundendaten ersichtlich, welche Eigenschaften Pflichtfelder im Webshop sind und im zweiten Fall sieht der Kunde, welche der Eigenschaften für ihn verpflichtend sind.

|*Kundensuche*
|Nur sichtbar, wenn unter *Typ* die Einstellung *Auswahl* gewählt wurde. Aktivieren, damit die Eigenschaft in der Kundensuche im Menü *CRM » Kunden bearbeiten* im Tab *Filter* zur Verfügung steht.

|*Bestellvorgang*
|Aktivieren, damit die Eigenschaft im Bestellvorgang angezeigt wird.

|*Kundenregistrierung*
|Aktivieren, damit die Eigenschaft in der Kundenregistrierung angezeigt wird.

|*Sichtbarkeit*
|Einen oder mehrere Kundentypen wählen, für die die Eigenschaft sichtbar sein soll.

|*Mandant (Shop)*
|Einen oder mehrere Mandanten (Shops) wählen, um die Eigenschaft für diese(n) Mandanten zu aktivieren.
|====

Die in diesem Menü erstellten Eigenschaften werden im Menü *CRM » Kunden bearbeiten » Kunde öffnen » Tab: Eigenschaften* angezeigt.

[#500]
=== Eigenschaft bearbeiten

Im Tab *Eigenschaften* finden Sie alle in Ihrem plentymarkets System erstellten Eigenschaften. Hier ändern Sie die in <<tabelle-eigenschaft-erstellen>> beschriebenen Einstellungen oder löschen bestehende Eigenschaften aus dem System, wenn Sie diese nicht mehr benötigen.

[.instruction]
Eigenschaft bearbeiten:

. Öffnen Sie das Menü *System » CRM » Eigenschaften*.
. Klicken Sie auf *Suchen*, um alle Eigenschaften anzuzeigen, oder wählen Sie einen *Kundentyp* aus der Dropdown-Liste, um nur die Eigenschaften, die für diesen Kundentyp gespeichert sind, anzuzeigen.
. Klappen Sie die Eigenschaft auf, um die Einstellungen zu bearbeiten. Beachten Sie dazu die Erläuterungen in <<tabelle-eigenschaft-erstellen>>.
. *Speichern* Sie die Einstellungen.

[#600]
=== Multilinguale Eigenschaft erstellen

Nachdem Sie eine Eigenschaft erstellt haben, können Sie diese Eigenschaft auch zu einer multilingualen Eigenschaft machen. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Multilinguale Eigenschaft erstellen:

. Öffnen Sie das Menü *System » CRM » Eigenschaften*.
. Klappen Sie die Eigenschaft auf.
. Wählen Sie die Sprache aus der Dropdown-Liste *Name*.
. Geben Sie den Namen in der Sprache ein.
. *Speichern* Sie die Einstellungen.

Wenn Sie als Typ *Auswahl* gewählt haben, wird für die Werte eine weitere Dropdown-Liste und eine weitere Spalte angezeigt, in die Sie die Namen der Eigenschaftswerte in der Sprache eingeben.

[#700]
=== Eigenschaft löschen

Gehen Sie wie im Folgenden beschrieben vor, um eine Eigenschaft unwiderruflich zu löschen, wenn Sie diese nicht mehr benötigen.

[.instruction]
Eigenschaft löschen:

. Öffnen Sie das Menü *System » CRM » Eigenschaften*.
. Klicken Sie in der Zeile der Eigenschaft auf *Löschen*.
. Bestätigen Sie die Sicherheitsabfrage.

[#800]
== Kundendatensatz erstellen

Gehen Sie wie im Folgenden beschrieben vor, um einen neuen Kundendatensatz zu erstellen. Sie können einen neuen Kundendatensatz beispielsweise auch während einer telefonischen oder schriftlichen Bestellung erstellen oder um die Kontaktdaten eines Interessenten zu speichern.

[.instruction]
Kundendatensatz erstellen:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Klicken Sie auf *Neu*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-kundendatensatz-erstellen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-kundendatensatz-erstellen]]
.Kundendatensatz erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|Beim Erstellen eines Kundendatensatzes wird vom System automatisch eine Kunden-ID vergeben. Diese ID kann nicht geändert werden.

|*Firma*
|Firmenname eingeben. +
Das ist ein Pflichtfeld, wenn unter *Vorname* und *Nachname* kein Eintrag gemacht wird.

|*Anrede*
|*Leere Option* = Firma +
*Frau* = Weibliche Anrede +
*Herr* = Männliche Anrede

|*Titel*
|Titel des Kunden eingeben.

|*Vorname*
|Vorname des Kunden eingeben. +
Das ist ein Pflichtfeld, wenn unter *Firma* und *Nachname* kein Eintrag gemacht wird.

|*Nachname*
|Nachname des Kunden eingeben. +
Das ist ein Pflichtfeld, wenn unter *Firma* und *Vorname* kein Eintrag gemacht wird.

|*Adresszusatz*
|Ggf. Adresszusatz eingeben. Dieser wird z.B. für die Rechnungsadresse verwendet. +
Das ist ein Pflichtfeld, wenn unter *Straße* kein Eintrag gemacht wird.

|*Straße, +
PLZ*, +
*Ort*
|Straße, Hausnummer, Postleitzahl und Ort des Kunden eingeben. Diese Angaben werden z.B. für die Rechnungsadresse verwendet. Bei bestimmten Ländern, z.B. Vereinigtes Königreich, wird die Reihenfolge der Optionen *PLZ* und *Ort* getauscht. +
*PLZ* und *Ort* sind Pflichtfelder. *Straße* ist ein Pflichtfeld, wenn unter *Adresszusatz* kein Eintrag gemacht wird.

|*Region/Bezirk*
|Region aus der Dropdown-Liste wählen. +
Je nach Land können hier z.B. Bundesstaaten oder Bundesländer gewählt werden. +
Wenn zu einem Land hier keine Optionen verfügbar sind, ist die Dropdown-Liste deaktiviert. +
In der Kaufabwicklung und im Mein Konto-Bereich wird diese Option auch bei der Lieferanschrift angezeigt. Die Angabe kann in bestimmten Fällen notwendig sein, z.B. für PayPal in den USA.

|*Land*
|Land aus der Dropdown-Liste wählen. Dieses Land wird z.B. für die Rechnungsadresse verwendet. Die Standardeinstellung richtet sich nach der Konfiguration der Option *Standard-Standort* im Menü *System » Mandant » Mandant wählen » Einstellungen*.

|*ASP*
|Steht für Ansprechpartner und ist z.B. für Firmenkunden.

|*E-Mail*
|E-Mail-Adresse des Kunden eingeben. Die E-Mail-Adresse ist wichtig für den automatischen Versand von E-Mail-Vorlagen wie Auftragsbestätigungen, Rechnungen und Mahnungen. +
Bei nicht erfolgreichem E-Mail-Versand prüfen Sie die <<crm/e-mails-versenden#100, Zugangsdaten>>. Im Menü <<basics/datenaustausch/api-log#, Daten » API-Log>> werden die Fehlermeldungen gespeichert.

|*Telefon*
|Telefonnummer des Kunden eingeben.

|*Telefax*
|Faxnummer des Kunden eingeben.

|*Mobil*
|Handynummer des Kunden eingeben.

|*Mandant*
|Mandant aus der Dropdown-Liste wählen, um den Kunden diesem Mandanten zuzuordnen. +
Nur Mandanten, für die unter *System » Mandant* in den *Grundeinstellungen* des Mandanten ein Name eingegeben ist, werden angezeigt.

|*Sprache*
|Sprache für den Kunden wählen. Rechnungsdokumente werden z.B. in dieser Sprache erstellt, wenn Sie eine Vorlage für die Sprache angelegt haben.

|*Bewertung*
|Kunde für interne Zwecke bewerten. 5 rote Sterne stehen für die schlechteste und 5 gelbe Sterne für die beste Bewertung.

|*Eigner*
|Eigner für den Kunden wählen. Wenn kein Eigner gewählt werden soll, die leere Option wählen. +
Mit der Zuordnung eines Eigners ist es in der Kundensuche z.B. möglich, nur die Kunden eines Eigners aufzulisten.

|*Typ*
|Kundentyp wählen. Standardmäßig können die Typen *Kunde*, *Handelsvertreter*, *Lieferant*, *Partner*, *Hersteller* und *Interessent* gewählt werden. Eigene Kundentypen erstellen Sie im Menü <<crm/kontakte-verwalten#20, System » CRM » Typen>>.

|*HV PLZ-Bereich*
|Nur sichtbar bei Wahl des Typs *Handelsvertreter*. PLZ-Bereich des Handelsvertreters eingeben. Mehrere Bereiche durch Kommata getrennt eingeben, z.B.: 33,34. Je mehr Ziffern pro PLZ-Bereich, desto mehr wird dieser eingegrenzt. Der PLZ-Bereich wird für Handelsvertreter benötigt, deren Umsätze mit der Statistik <<basics/statistik#20, Umsatz nach Handelsvertreter>> ausgewertet werden sollen. Weitere Details siehe Option *HV*.

|*HV PLZ-Bereich Land*
|Nur sichtbar bei Wahl des Typs *Handelsvertreter*. Die Dropdown-Liste ist nur aktiviert, wenn ein PLZ-Bereich unter *HV PLZ-Bereich* eingegeben wurde. +
Land wählen, für das der PLZ-Bereich des Handelsvertreters gelten soll. Standardeinstellung ist das Systemland. +
*_Tipp_*: Wenn ein Handelsvertreter in mehreren Ländern tätig ist, pro Land einen Kundendatensatz erstellen.

|*Lieferzeit*
|Nur sichtbar bei Wahl des Typs *Lieferant*. Lieferzeit in Tagen eingeben.

|*MBW*
|Nur sichtbar bei Wahl des Typs *Lieferant*. MBW steht für Mindestbestellwert. Mindestbestellwert in der Systemwährung eingeben.

|*Klasse*
|Kundenklasse wählen. Kundenklassen dienen zur internen Unterscheidung und z.B. ob und welcher Rabatt dieser Kundenklasse gewährt werden soll. Kundenklassen werden im Menü <<crm/kontakte-verwalten#15, System » CRM » Kundenklassen>> erstellt. Soll zum Beispiel zwischen Endkunden und Händlern bei der Preisanzeige im Webshop unterschieden werden, kann dies über die Option *Anzeige der Preise im Webshop* in der Konfiguration der Kundenklassen vorgenommen werden. Bei Endkunden (B2C) werden die Bruttopreise im Webshop angezeigt. Bei Händlern (B2B) werden die Nettopreise im Webshop angezeigt. +
Leere Option = Keine Zuordnung zu einer Kundenklasse +
*_Wichtig_*: Wenn keine Zuordnung zu einer Kundenklasse erfolgt, wird ein Kunde automatisch der Kundenklasse mit der niedrigsten Position zugeordnet. Da pro Kundenklasse auch die Preisdarstellung im Webshop konfiguriert wird, diese Option bei der Kundenklasse mit der Position 1 prüfen, damit bei automatischen Zuweisungen auch die gewünschte Preisdarstellung erfolgt.

|*HV*
|HV steht für Handelsvertreter. Mit dieser Einstellung wird dem Kundentyp ein Handelsvertreter zugeordnet. Kunden-ID des Handelsvertreters eingeben oder die ersten 3 Buchstaben des Namens eingeben, um die Vorschlagsliste aufzurufen. Alternativ auf der Tastatur die Pfeiltaste nach unten drücken, ohne einen Suchbegriff einzugeben, um alle Handelsvertreter anzuzeigen. Mit einem Klick auf den Eintrag des Handelsvertreters wird die Kunden-ID und der Name des Handelsvertreters in dieses Feld eingetragen. Somit ist der Handelsvertreter dem Kundentyp zugeordnet. +
Sollen die Umsätze Ihrer Handelsvertreter mit der Statistik <<basics/statistik#20, Umsatz nach Handelsvertreter>> ausgewertet werden, muss die Zuordnung per Ereignisaktion erfolgen, mit der Aktion <<basics/automatisierung/ereignisaktionen#_aktionsgruppe_kunde, Handelsvertreter dem Kunden zuordnen>>. +
*_Wichtig_*: Der im Kundendatensatz eingestellte Handelsvertreter wird nicht für die Aufträge des Kunden herangezogen. Somit wird der Auftrag nicht in der Statistik *Umsatz nach Handelsvertreter* berücksichtigt. Damit der Handelsvertreter für einen Auftrag berücksichtigt wird, muss auch diese Zuordnung per Ereignisaktion erfolgen. Beachten Sie dazu die Hinweise zur Ereignisaktion <<basics/automatisierung/ereignisaktionen#_aktionsgruppe_aufträge, Handelsvertreter dem Auftrag zuordnen>>.

|*Gruppe Forum*
|Benutzergruppe für das Forum wählen. Benutzergruppen werden im Menü <<omni-channel/online-shop/webshop-einrichten/module#forum, System » Mandant » Mandant wählen » Module » Forum>> eingerichtet.

|*Geburtsdatum*
|Geburtsdatum des Kunden nach dem vorgegebenen Muster eingeben oder aus dem Kalender wählen.

|*Altersfreigabe*
|Einstellung zur Altersbeschränkung für Artikel, die diesbezüglich gekennzeichnet sein müssen. Je nach Einstellung der Altersfreigabe kann der Kunde Artikel kaufen oder nicht.

|*Newsletter*
|Wählen, ob der Kunde beim Newsletterversand berücksichtigt wird oder nicht. +
Wenn die Option aktiviert ist, erhält der Kunde Newsletter. Wenn die Option deaktiviert ist, erhält der Kunde keine Newsletter.

|*Gesperrt*
|Wählen, ob der Kunde für den eingestellten Mandanten (Shop) gesperrt wird oder nicht. +
Wenn die Option aktiviert ist, ist der Kunde gesperrt und kann sich nicht mehr im Webshop einloggen. Wenn die Option deaktiviert ist, kann sich der Kunde im Webshop einloggen.

|*Bonität*
|Erst sichtbar, wenn der Kundendatensatz gespeichert wurde. *Erneut prüfen* klicken, um die Bonität des Kunden zu prüfen. Das Datum der letzten Bonitätsprüfung wird hier angezeigt.

|*Kundennr.*
|Kundennummer für den Kunden eingeben. Die Kundennummern können fortlaufend nummeriert werden oder nicht. Kundennummern werden nicht automatisch vergeben.

|*USt-IdNr.*
|Umsatzsteuer-ID des Kunden eingeben. Wenn beim Versand von Waren an einen gewerblichen Käufer in ein anderes EU-Land (innergemeinschaftliche Lieferung) der Auftrag netto berechnet werden soll, muss die Umsatzsteuer-ID eingegeben sein. Nachdem die USt-IdNr. hier eingegeben wurde, muss im Menü <<auftragsabwicklung/auftraege/buchhaltung#, System » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung>> für die Option *Umsatzsteuer-ID* die Einstellung *Nettorechnung* gewählt werden. Damit werden Rechnungen für Kunden, bei denen eine Umsatzsteuer-ID in den Kundendaten eingegeben ist, ohne Umsatzsteuer ausgestellt. +
*_Wichtig_*: Die Nettoeinstellung greift nicht, wenn für das Lieferland des Kunden Steuersätze gespeichert sind oder die Lieferschwelle überschritten wurde.

|*Zahlungsziel*
|Zahlungsziel für den Kunden in Tagen eingeben. Dieses Zahlungsziel hat Priorität vor dem Zahlungsziel, das in der <<crm/kontakte-verwalten#15, Kundenklasse>> festgelegt ist. Ein Zahlungsziel kann weiterhin optional in <<auftragsabwicklung/auftraege/auftragsdokumente#130, Auftragsdokumenten>> wie z.B. <<omni-channel/online-shop/mandanten-einrichten/dokumente/rechnung#, Rechnungen>> hinterlegt werden. Dieses Zahlungsziel wird dann in der Rechnung ausgegeben, wenn für einen Kunden und die Kundenklasse kein Zahlungsziel hinterlegt wurde. Dazu die Box *Info: Gestaltung von Zahlungsbedingungen* unterhalb der Tabelle beachten. +
*_Wichtig:_* Das Zahlungsziel kann im Kundendatensatz nur Firmenkunden, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Wert für das Zahlungsziel in der Rechnung im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* zu speichern.

|*Valuta*
|Zeitraum (ab Rechnungserstellung) eingeben, wenn eine zusätzliche Frist vor dem Zeitraum *Zahlungsziel* gewünscht ist. Dazu die Box *Info: Gestaltung von Zahlungsbedingungen* unterhalb der Tabelle beachten. +
*_Wichtig:_* Valuta kann im Kundendatensatz nur Firmenkunden, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Wert für Valuta in der Rechnung im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* zu speichern.

|*Skonto (Tage)*
|Anzahl der Tage (ab Rechnungserstellung) eingeben, in denen der Kunde skontiert offene Forderungen bezahlen kann. Dazu die Box *Info: Gestaltung von Zahlungsbedingungen* unterhalb der Tabelle beachten. +
*_Wichtig:_* Skonto kann im Kundendatensatz nur Firmenkunden, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Skonto-Wert in der Rechnung im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* zu speichern.

|*Skonto (%)*
|Wert in Prozent eingeben, den der Kunde bei Einhaltung der Frist *Skonto (Tage)* in Abzug bringen kann. Dazu die Box *Info: Gestaltung von Zahlungsbedingungen* unterhalb der Tabelle beachten. +
*_Wichtig:_* Skonto kann im Kundendatensatz nur Firmenkunden, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Skonto-Wert in der Rechnung im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* zu speichern.

|*Deb. Konto*
|Weitere separate Kundennummer eingeben. Diese Nummer entspricht in der Regel der Kundennummer bzw. Debitorennummer in Ihrer Finanzbuchhaltung und ist zur weiteren Bearbeitung Ihrer Belege hilfreich. Dieses Feld kann ggf. auch automatisch befüllt werden. +
Weitere Informationen zum Debitorenkonto finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/buchhaltung#750, Buchhaltung>>.

|*Archivnr.*
|Archivnummer eingeben, wenn z.B. noch ein Archiv mit älteren Kundendaten besteht.

|*Lastschrift / Rechnung*
|Zahlungsart für den Kunden zulassen, auch wenn diese ansonsten global nicht verwendet wird. +
*Nicht erlauben* = Der Kunde kann nicht mit dieser Zahlungsart zahlen. +
*Erlauben* = Der Kunde kann mit dieser Zahlungsart zahlen, selbst wenn diese global nicht angeboten wird. +
*_Beispiel_*: Ein Kunde, der bereits mehrfach bei Ihnen bestellt hat, soll auf Rechnung einkaufen können. +
Notwendige Einstellungen: Die Zahlungsart im Menü *System » Aufträge » Zahlung » Zahlungsarten* aktivieren. Damit wird die Zahlungsart zur Auswahl in einem Auftrag verfügbar. +
Allerdings keine Lieferländer wählen, da die Zahlungsart dann global im Webshop verfügbar ist und dies in diesem Fall nicht gewünscht ist. +
Eine zweite Bedingung ist, dass die Zahlungsart *Rechnung* bzw. *Lastschrift* in mindestens einem Versandprofil verfügbar sein muss, d.h. nicht gesperrt sein darf. +
Die dritte Bedingung ist, dass das Versandprofil bei Artikeln aktiviert ist. +
Die hier genannten Punkte prüfen und dann die Zahlungsart aktivieren, um dem Kunden die Nutzung zu ermöglichen.

|*Personennummer*
|Die Personennummer wird von skandinavischen Endkunden für skandinavische Zahlungsanbieter (z.B. Klarna) benötigt. Die Anzeige der Personennummer wird im Webshop sowohl in der Kaufabwicklung als auch im Mein Konto-Bereich abgefragt. Für die Kaufabwicklung wird die Abfrage im Menü *CMS » Webdesign » Bestellvorgang » Kaufabwicklung* im Bereich <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-kaufabwicklung, Kundenregistrierung>> sowie unter *Rechnungsanschrift* konfiguriert. Für den Mein Konto-Bereich wird die Abfrage unter *CMS » Webdesign » Mein Konto* im Bereich <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-mein-konto, Persönliche Daten>> eingerichtet. Dort kann auch die Option *Pflichtfeld* für die Personennummer gewählt werden.

|*eBay-Name*
|eBay-Name des Kunden eingeben.

|*DHL-PostNr.*
|DHL-PostNummer des Kunden eingeben. Eine DHL-PostNummer erhalten Kunden von DHL, wenn sie Empfängerservices wie Paketankündigung nutzen.
|====

[TIP]
.Info: Gestaltung von Zahlungsbedingungen
====
Mit den Optionen *Valuta*, *Zahlungsziel*, *Skonto (Tage)* und *Skonto (%)* ist z.B. folgende Zahlungsbedingung möglich:

60 Tage *Valuta*, 30 Tage *netto* (Zahlungsziel), *10* Tage mit *2* % *Skonto*

Erläuterung: Zahlt der Kunde innerhalb von 10 Tagen, erhält der Kunde einen Skonto von 2%. Nach insgesamt 91 Tagen befindet sich die Zahlung im Verzug. Beim Import von Zahlungseingängen und der automatischen Zuordnung wird vorab intern automatisch geprüft, ob der von Kunden durchgeführte Skontoabzug gültig ist. Ist der Skontozeitraum abgelaufen, erhält der Auftrag den Status *Teilzahlung erhalten*. Die oben aufgeführten Zahlungsbedingungen werden automatisch in den Auftrag sowie z.B. in die <<auftragsabwicklung/auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnung>> übernommen und können dort auch geändert werden. Bei Rechnungsdruck werden diese Bedingungen zu einer für diesen Auftrag gültigen Zahlungskondition zusammengefasst. Hierbei werden Valutatage auf die Zahlungszieltage aufgerechnet, um ein Zahlungsziel abzubilden. Auf einer Rechnung wird trotz der Addition von Valuta und Zahlungsziel Folgendes ausgegeben: +
Zahlungskonditionen: Valuta 60 Tage, innerhalb von 10 Tagen 2% Skonto, innerhalb von 30 Tagen ohne Abzug. Wenn ein Wert für *Valuta* am Kunden gespeichert ist, wird dieser für das Dokument verwendet, andernfalls der Wert unter *Zahlungsziel* bzw. der Wert aus der Kundenklasse, falls eingegeben. Als letzte Möglichkeit, wenn alles andere nicht gesetzt ist, wird die Anzahl der Tage aus der Option *Zahlungsziel* in den Einstellungen des Dokuments verwendet. Diese werden im Bereich <<auftragsabwicklung/auftraege/auftragsdokumente#130, Optionale Elemente unter Artikelpositionstabelle>> eingestellt. Wichtig: Diese Optionen finden nur Anwendung auf den Bruttogesamtwert einer Rechnung.
====

[#1100]
== Kunden suchen

Im Tab *Filter* haben Sie die Möglichkeit, Kunden nach bestimmten Kriterien zu suchen. Die gefundenen Kundendaten werden dann im Tab *Kunden* aufgelistet. Sie können die Kundendaten bearbeiten. Dazu stehen Ihnen umfangreiche Einstellungen und Verknüpfungen zu wichtigen Menüs, wie z.B. <<crm/kundendaten-verwalten#2000, Aufträge>>, <<crm/kundendaten-verwalten#2200, Tickets>>, <<crm/kundendaten-verwalten#2400, Statistik>> etc. zur Verfügung.

Um bestimmte Kunden zu suchen, geben Sie die Ihnen bekannten Suchbegriffe in die Filter ein oder wählen Sie die Einstellungen der Dropdown-Listen. Sie können auch mehrere Suchbegriffe gleichzeitig in die Suchfelder eingeben. Dies ermöglicht Ihnen eine schnellere und genauere Suche. Sie können z.B. eine Firma und eine Postleitzahl eingeben, um alle Kunden einer Firmenfiliale zu finden.

Sie können mit den Filtereinstellungen definieren, welcher Kunde oder welche Kundengruppe angezeigt werden soll. Listen Sie z.B. nur Kunden einer bestimmten Kundenklasse und eines bestimmten Eigners oder suchen Sie alle Kunden. Für Einstellungen, bei denen die Optionen in einer Dropdown-Liste zur Auswahl stehen, ist *ALLE* die Standardeinstellung.

[.instruction]
Kunden suchen:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Geben Sie im Tab *Filter* Suchbegriffe in die Suchfelder ein bzw. stellen Sie Filteroptionen in den Dropdown-Listen ein. Beachten Sie dazu die Erläuterungen in <<tabelle-filter-kundensuche>>.
. Klicken Sie auf *Suchen*. +
→ Die Kunden, die den Suchkriterien entsprechen, werden aufgelistet.

[[tabelle-filter-kundensuche]]
.Filter für die Kundensuche
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Ohne gewählte Filtereinstellungen auf *Suchen* klicken, um alle Kundendatensätze anzuzeigen. Alternativ die Suchergebnisse durch Filtereinstellungen eingrenzen und auf *Suchen* klicken. Die gefundenen Kundendaten werden im Tab *Kunden* angezeigt.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*ID*
|Jeder Kundendatensatz erhält automatisch eine fortlaufende und einzigartige Kunden-ID. Dies ist unabhängig davon, ob der Eintrag manuell oder automatisch angelegt wurde. 2 Kunden haben somit nie die gleiche ID. Die Kunden-ID entspricht immer einer echten Zahl. Ungültig sind z.B. "00521" oder "ADF8354".

|*Kundendaten*
|In diesem Feld können die folgenden Parameter gesucht werden: *Vorname*, *Nachname*, *Firma*, *Ansprechpartner*, *eBay-Name*, *Zusatzname*, *Straße*, *PLZ*, *Ort*, *E-Mail-Adresse*, *Kundennummer*, *Externe Kunden-ID*, *Such-Tags*, *PostIdent*. Es ist auch möglich, in diesem Feld nur Teile der E-Mail-Adresse einzugeben.

|*Name*
|Vorname und/oder Nachname eingeben, um den Kunden mit diesem Namen zu suchen.

|*E-Mail-Adresse*
|Komplette E-Mail-Adresse eingeben, um den Kunden mit dieser E-Mail-Adresse zu suchen. Teile der E-Mail-Adresse können im Feld *Kundendaten* gesucht werden.

|*Straße*
|Straßenname eingeben, der im Kundendatensatz gespeichert ist.

|*PLZ*
|Postleitzahl eingeben, um Kunden oder Kundengruppen aus einem bestimmten Ort zu ermitteln.

|*Telefon*
|Telefonnummer eingeben, um den Kunden mit dieser Nummer zu suchen.

|*Notiz*
|Nach Stichworten in der Notiz in den Kundendaten suchen.

|*Typ*
|<<crm/kontakte-verwalten#20, Kundentyp>> wählen, um nach diesem zu suchen. +
Der Typ muss gewählt sein, um nach <<crm/kundendaten-verwalten#400, Eigenschaften>> zu suchen.

|*Klasse*
|<<crm/kontakte-verwalten#15, Kundenklasse>> wählen, um nach dieser zu suchen.

|*Eigner*
|Eigner wählen, um dessen Kunden zu suchen. Der Eigner muss in den Kundendaten gespeichert sein. +
*_Wichtig_*: In der Dropdown-Liste werden nur Eigner angezeigt, bei denen im Benutzerkonto im Tab *Eigner* die Option *Kunde* aktiviert ist.

|*Land*
|Land wählen, um nur Kunden aus diesem Land anzuzeigen. Das Land ist in den Kundendaten gespeichert.

|*Mandant (Shop)*
|Mandant (Shop) wählen, um nur Kunden dieses Mandanten anzuzeigen. Der Mandant ist in den Kundendaten gespeichert. +
*_Wichtig_*: Variablen Benutzern stehen nur Mandanten zur Auswahl, für die sie eine Berechtigung haben. Berechtigungen werden im Tab <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90, Berechtigung>> unter *System » Einstellungen » Benutzer » Konten* eingestellt.

|*Bewertung*
|Bewertung wählen, um nur Kunden mit der Bewertung zu suchen.

|*Scheduler-Auftrag*
|Eine der folgenden Optionen wählen: +
*Vorhanden und aktiv* +
*Nicht vorhanden* +
*Beendet* +
Weitere Informationen zu Scheduler-Aufträgen finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/scheduler#, Scheduler-Aufträge>>.

|*IBAN*
|Eine der folgenden Optionen wählen: +
*Vorhanden* = Sucht nur nach Kunden, bei denen die IBAN in den Bankdaten gespeichert ist. +
*Nicht vorhanden* = Sucht nur nach Kunden, bei denen die IBAN nicht in den Bankdaten gespeichert ist.

|*Lastschriftmandat*
|*Liegt vor* oder *Liegt nicht vor* wählen. +
*Liegt vor* = Sucht nur nach Kunden, bei denen ein SEPA-Lastschriftmandat vorliegt. +
*Liegt nicht vor* = Sucht nur nach Kunden, bei denen kein SEPA-Lastschriftmandat vorliegt. +
Weitere Informationen dazu finden Sie auf der Handbuchseite <<auftragsabwicklung/payment/bankdaten-verwalten#, Bankdaten verwalten>> im Kapitel <<auftragsabwicklung/payment/bankdaten-verwalten#200, SEPA-Lastschriftmandat einrichten>>.
|====

[#900]
== Bewegungsdaten einsehen

Im Menü *CRM » Kunden bearbeiten » Kunde öffnen* im Bereich *Bewegungsdaten* wird z.B. angezeigt, seit wann der Kunde bei Ihnen Kunde ist und wann der Kunde das letzte Mal in Ihrem Webshop eingeloggt war. Die Daten werden automatisch angepasst und können nicht geändert werden. <<tabelle-bewegungsdaten-kundendatensatz>> erläutert die Bewegungsdaten.

[[tabelle-bewegungsdaten-kundendatensatz]]
.Bewegungsdaten im Menü *CRM » Kunden bearbeiten » Kunde öffnen » Tab: Kundendaten*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Kunde seit*
|Datum und Uhrzeit, seit wann der Kunde registriert ist.

|*Zugangsart*
|Art, wie sich der Kunde registriert hat. Entweder *regulärer Zugang* oder *Gastzugang*. Regulärer Zugang bedeutet, dass sich der Kunde neu registriert hat. Gastzugang bedeutet, dass sich der Kunde als Gast angemeldet und bestellt hat. +
*_Wichtig:_* Wenn Sie Ceres nutzen, haben Sie die Möglichkeit, das Erstellen von Kundendatensätzen bei Gastbestellungen zu unterbinden. Wählen Sie dazu im Menü *System » CRM » Einstellungen* die Option *Keine Kontakte erstellen* aus der Dropdown-Liste *Gastbestellungen*. Standardmäßig ist die Option *Kontakte erstellen* gewählt.

|*Aktualisiert*
|Datum und Uhrzeit, wann die Kundendaten das letzte Mal aktualisiert wurden.

|*Letztes Login*
|Datum und Uhrzeit des letzten Login.

|*Letzter Auftrag*
|Datum und Uhrzeit, wann der letzte Auftrag eingegangen ist. Die Auftrags-ID wird ebenfalls angezeigt. Mit einem Klick auf die ID wird der Auftrag geöffnet. Wenn noch kein Auftrag eingegangen ist, steht in diesem Feld *Keine Daten*.
|====

[#1000]
== Gruppenfunktion nutzen

Mit der Gruppenfunktion können Sie bestimmte Aktionen für mehrere Kunden auslösen, so z.B. den Versand einer E-Mail-Vorlage oder den Druck von Adressetiketten.

[.instruction]
Gruppenfunktion nutzen:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Geben Sie im Tab *Filter* Suchbegriffe in die Suchfelder ein bzw. stellen Sie Filteroptionen in den Dropdown-Listen ein. Beachten Sie dazu die Erläuterungen in <<tabelle-filter-kundensuche>> im Kapitel <<crm/kundendaten-verwalten#1100, Kunden suchen>>.
. Klicken Sie auf *Suchen*.
. Aktivieren Sie die Kunden, für die die Gruppenfunktion angewendet werden soll.
. Klicken Sie auf *Gruppenfunktion*.
. Wählen Sie eine oder mehrere Gruppenfunktionen. Beachten Sie dazu die Erläuterungen in <<tabelle-gruppenfunktion-kundendatensatz>>.
. Klicken Sie auf *Anwenden*, um die Funktion(en) auf die aktivierten Kunden anzuwenden.

[[tabelle-gruppenfunktion-kundendatensatz]]
.Gruppenfunktion im Menü *CRM » Kunden bearbeiten* nutzen
[cols="1,3"]
|====
|Gruppenfunktion |Erläuterung

|*Adressetiketten drucken*
|Druckt das aus der Dropdown-Liste gewählte Etikett für alle aktivierten Kunden.

|*E-Mail-Vorlage senden*
|Versendet die aus der Dropdown-Liste gewählte Vorlage für alle aktivierten Kunden.

|*Newsletter*
|Die E-Mail-Adresse der aktivierten Kunden wird in den unter *Kategorie* eingestellten E-Mail-Ordner im Menü *CRM » Newsletter* für den Newsletterversand kopiert.

|*Zahlungsziel*
|Speichert das eingegebene Zahlungsziel in den Kundendaten aller aktivierter Kunden.
|====

[#1200]
== Kunden über die Kundenkarte aufrufen

In Ihrem plentymarkets System haben Sie im Menü *CRM » Kundenkarte* oder über den Schnellzugriff *Kundenkarte* in der Kopfzeile des plentymarkets Administrationsbereichs die Möglichkeit nach Kunden zu suchen und dann z.B. direkt einen neuen Auftrag für den Kunden anzulegen. Sie können auch einen neuen Kundendatensatz erstellen.

[.instruction]
Kunden über die Kundenkarte aufrufen:

. Öffnen Sie das Menü *CRM » Kundenkarte* oder klicken Sie auf *Kundenkarte* in der Kopfzeile des plentymarkets Administrationsbereichs.
. Geben Sie mindestens 3 Buchstaben bzw. Ziffern des Suchbegriffs, z.B. Kunden-ID, Name, Firmenname, Ansprechpartner oder E-Mail-Adresse, in das Eingabefeld ein. +
→ Die Kunden werden in der Liste angezeigt.
. Mit einem Klick auf den Kunden wird dessen Kundenkarte im Tab *Übersicht* geöffnet.

[.subhead]
Alle Kunden über die Kundenkarte aufrufen

Sie haben außerdem die Möglichkeit, alle Kunden anzuzeigen. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Alle Kunden über die Kundenkarte aufrufen:

. Öffnen Sie das Menü *CRM » Kundenkarte* oder klicken Sie auf *Kundenkarte* in der Kopfzeile des plentymarkets Administrationsbereichs.
. Klicken Sie in das Suchfeld.
. Drücken Sie auf Ihrer Tastatur die Pfeiltaste nach unten, ohne einen Suchbegriff einzugeben. +
→ Alle Kunden werden in der Liste angezeigt.

Mit einem Klick auf *Neuer Kunde* erstellen Sie einen neuen Kundendatensatz.

Nach einem Klick auf den Kunden aus der Liste werden die Tabs zur Bearbeitung des Kundendatensatzes geöffnet. Gleichzeitig wird neben *Neuer Kunde* in der Titelzeile *Neuer Auftrag* angezeigt. Mit einem Klick auf *Neuer Auftrag* legen Sie für den Kunden einen neuen Auftrag an. Alternativ nutzen Sie dafür die Funktion *Neuer Auftrag* im Menü *CRM » Kunden bearbeiten » Kunde öffnen » Tab: Kundendaten*.

In den Tabs finden Sie alle weiteren Einstellungen des <<crm/kundendaten-verwalten#800, Kundendatensatzes>> und können diese hier bearbeiten.

[#1300]
== Kundendatensatz bearbeiten

Über die <<crm/kundendaten-verwalten#1100, Kundensuche>> finden Sie schnell und einfach die Kundendaten Ihrer Kunden wie z.B. Anschrift, Telefonnummer und E-Mail-Adresse. Suchen Sie den Kunden mit Hilfe der <<crm/kundendaten-verwalten#1100, Filtereinstellungen>>. Öffnen Sie den Kunden durch einen Klick auf die Zeile des Kunden, um dessen Kundendatensatz zu bearbeiten.

[.instruction]
Kundendatensatz bearbeiten:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Geben Sie im Tab *Filter* Suchbegriffe in die Suchfelder ein bzw. stellen Sie Filteroptionen in den Dropdown-Listen ein. Beachten Sie dazu die Erläuterungen in <<tabelle-filter-kundensuche>> im Kapitel <<crm/kundendaten-verwalten#1100, Kunden suchen>>.
. Klicken Sie auf *Suchen*.
. Klicken Sie in die Zeile des Kunden. +
→ Das Tab *Kundendaten* wird geöffnet.
. Wechseln Sie in das Tab, in dem Sie Einstellungen bzw. Änderungen vornehmen möchten.
. Nehmen Sie die Einstellungen bzw. Änderungen vor. +
→ Beachten Sie hierzu die folgenden Kapitel.
. *Speichern* Sie die Einstellungen.

Welche Einstellungen Sie in den einzelnen Tabs im Kundendatensatz vornehmen können, wird in den folgenden Unterkapiteln beschrieben.

[#1400]
=== Kundendaten anzeigen

Im Tab *Kundendaten* finden Sie die grundlegenden Daten eines Kunden wie z.B. Anschrift, Telefonnummer und E-Mail-Adresse. Außerdem sehen Sie die Bewegungsdaten des Kunden. Hierzu gehört z.B. seit wann der Kunde bei Ihnen Kunde ist.

<<tabelle-symbolleiste-kundendatensatz>> erläutert die Symbolleiste im Tab *Kundendaten*. Erläuterungen zu den Einstellungen und Optionen in diesem Tab finden Sie im Kapitel <<crm/kundendaten-verwalten#800, Kundendatensatz erstellen>>.

[[tabelle-symbolleiste-kundendatensatz]]
.Symbolleiste im Tab *Kundendaten*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Speichern*
|Speichert die Änderungen.

|*ID*
|ID des Kunden. Wird beim Erstellen des Kunden automatisch vom System vergeben. Die ID kann nicht geändert werden.

|*Neuer Auftrag*
|Legt einen neuen Auftrag für den Kunden an.

|*Sammelauftrag*
|Legt einen neuen Sammelauftrag für den Kunden an. Die Funktion *Sammelauftrag* bietet die Möglichkeit, nicht bezahlte Aufträge eines Kunden in einen Auftrag zu übernehmen. Weitere Details zu Sammelaufträgen finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/sammelauftraege#, Sammelaufträge>>.

|*Neuer Scheduler*
|Legt einen neuen <<auftragsabwicklung/auftraege/scheduler#, Scheduler-Auftrag>> für den Kunden an.

|*vCard*
|Exportiert die Kundendaten als Visitenkarte im CSV-Format.

|*Neues Passwort*
|Sendet dem Kunden ein neues Passwort.

|*Login entsperren*
|Wurde das Passwort beim Login mehrmals hintereinander falsch eingegeben, wird der Kunde für das Login eine gewisse Zeit gesperrt. Über diesen Button wird der Login frühzeitig entsperrt.
|====

[#1500]
=== Eigenschaft eingeben

Im Tab *Eigenschaften* stehen Ihnen die <<crm/kundendaten-verwalten#400, zuvor erstellten Eigenschaften>> zur Verfügung, um wichtige Informationen zu Ihren Kunden zu speichern. Die Eigenschaften sind auch als frei konfigurierbare Textfelder verwendbar, die dann je nach Einstellung bei der Kundenregistrierung oder im Bestellvorgang eingesetzt werden.

[.instruction]
Eigenschaft eingeben:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Suchen Sie den Kunden anhand der <<crm/kontakte-verwalten#200, Filtereinstellungen>>.
. Öffnen Sie den Kunden.
. Wechseln Sie in das Tab *Eigenschaften*.
. Nehmen Sie die Einstellungen zu den Eigenschaften des Kunden vor.
. *Speichern* Sie die Einstellungen.

[#1600]
=== Notiz speichern

Im Tab *Notizen* können Sie zu jedem Kunden Notizen speichern. Notizen sind nur in Ihrem plentymarkets Backend sichtbar, d.h. Kunden können die gespeicherten Notizen nicht im Webshop sehen.

[.instruction]
Notiz speichern:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Suchen Sie den Kunden anhand der <<crm/kundendaten-verwalten#1100, Filtereinstellungen>>.
. Öffnen Sie den Kunden.
. Wechseln Sie in das Tab *Notizen*.
. Geben Sie die Notiz ein. +
→ Formatieren Sie ggf. die Notiz mit den Funktionen in der Symbolleiste.
. *Speichern* Sie die Einstellungen.

Wenn Sie die Informationen, die Sie in der Notiz gespeichert haben, nicht mehr benötigen, entfernen Sie die Notiz mit einem Klick auf *Löschen*.

[#1700]
=== Kundendokumente hochladen

Im Menü *CRM » Kontakte* laden Sie Dokumente zum Kunden hoch. Zulässig sind Datenformate wie JPEG, PNG, GIF, TIFF, PDF, DOC, ODC, OTH, XLS, XML, HTML, HTM, CSS, ZIP und GZIP.

[.instruction]
Kundendokumente hochladen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der <<crm/kundendaten-verwalten#1100, Filtereinstellungen>>.
. Öffnen Sie den Kontakt.
. Öffnen Sie den Menüpunkt *Dokumente*.
. Klicken Sie auf *Dateien hochladen*.
. Wählen Sie die Dokumente aus.
. Klicken Sie auf *Öffnen*, um die Dateien hochzuladen oder ziehen Sie Dokumente per Drag-and-Drop-Funktion in das Tab.

Mit den Checkboxen oberhalb der Liste von Dokumenten können Sie ein einzelnes oder mehrere Dokumente zugleich wählen, um die Dokumente herunterzuladen oder zu löschen. +

[NOTE]
.Ordner erstellen
====
Klicken Sie auf *Ordner erstellen*, um die Kundendokumente zu sortieren und in bestimmten Ordnern abzulegen. Das Sortieren ist besonders hilfreich, wenn Sie eine große Zahl von Kundendokumenten hochladen oder dies planen.
====

[#1800]
=== Kundenumsätze anzeigen

Im Tab *Konto* sehen Sie die Umsätze Ihres Kunden. In der obersten Zeile sehen Sie die Summe der Rechnungen des Kunden, was Sie ihm in Form von Gutschriften gutgeschrieben haben und wie hoch die Differenz zwischen diesen beiden Beträgen ist. +
In der Tabelle sind die Aufträge und Gutschriften zu diesem Kunden als Vorgänge aufgeführt. Dabei sind die Spalten *Gezahlt* und *Ausstehend* besonders hilfreich. Wenn bei einem Auftrag ein Betrag unter *Ausstehend* aufgeführt ist, muss der Kunde diesen Betrag noch an Sie zahlen. Sobald dies geschehen ist, wird der Betrag unter *Gezahlt* aufgeführt. Wenn bei einer Gutschrift noch ein Betrag unter *Ausstehend* aufgeführt ist, müssen Sie diesen Betrag noch an den Kunden zahlen. Sobald dies geschehen ist, wird der Betrag unter *Gezahlt* aufgeführt.

[.instruction]
Kundenumsätze anzeigen:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Suchen Sie den Kunden anhand der <<crm/kundendaten-verwalten#1100, Filtereinstellungen>>.
. Öffnen Sie den Kunden.
. Wechseln Sie in das Tab *Konto*.
. Beachten Sie die Erläuterungen in <<tabelle-kundenumsaetze-anzeigen>>.

[[tabelle-kundenumsaetze-anzeigen]]
.Einstellungen im Menü *CRM » Kunden bearbeiten » Kunde öffnen » Tab: Konto*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Saldo*
|Zeigt den Kontostand des Kunden an. +
*+* = Summe der noch vom Kunden zu zahlenden Beträge +
*-* = Summe der noch an den Kunden zu zahlenden Beträge, wenn der Kunde zu viel gezahlt hat oder eine Gutschrift noch ausgezahlt werden muss. +
*0,0* = keine ausstehenden Beträge

|*Rechnungen*
|Summe der Rechnungsbeträge aller Aufträge und die Anzahl der Rechnungen in Klammern

|*Gutschriften*
|Summe aller Gutschriften und die Anzahl der Gutschriften in Klammern

|*Delta*
|Differenz in Prozent zwischen den gezahlten Gutschriften und dem insgesamt bezahlten Rechnungsbetrag des Kunden. Bei 0 % wurde dem Kunden noch keine Gutschrift ausgezahlt. Bei 100 % wurde dem Kunden jeder bezahlte Betrag wieder als Gutschrift zurückgezahlt.

|*Datum*
|Datum, an dem der Auftrag erstellt wurde

|*Auftrags-ID*
|ID des Auftrags. Ein Klick auf die ID öffnet die Detailansicht des Auftrags. IDs von Gutschriften sind eingerückt und unterhalb des Auftrags dargestellt.

|*Vorgang*
|Auftragsart, entweder Auftrag oder Gutschrift

|*Dokument*
|Dokumentnummer, z.B. Rechnungsnummer. Ein Klick auf die Nummer öffnet das Dokument.

|*Wert*
|Rechnungssumme des Auftrags

|*Gezahlt*
|Der bereits bezahlte Betrag

|*Zahlungsart*
|Zahlungsart des Auftrags

|*Ausstehend*
|Der zur vollständigen Bezahlung des Auftrags noch ausstehende Betrag.

|*Status*
|Status des Auftrags. Ein Klick auf den Status öffnet das Bearbeitungsfenster *Auftragsstatus*, in dem der Status geändert werden kann.
|====

[.subhead]
Kontodaten filtern

Verwenden Sie Filter, um die Umsätze Ihrer Kunden anzeigen zu lassen.

[.instruction]
Kontodaten filtern:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Suchen Sie den Kunden anhand der <<crm/kundendaten-verwalten#1100, Filtereinstellungen>>.
. Öffnen Sie den Kunden.
. Wechseln Sie in das Tab *Konto*.
. Nehmen Sie die Filtereinstellungen im Tab *Filter* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-kontodaten-filtern>>.
. Klicken Sie auf *Suchen*.

[[tabelle-kontodaten-filtern]]
.Filtereinstellungen im Menü *CRM » Kunden bearbeiten » Kunde öffnen » Tab: Konto*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Suche ausführen. Die gefundenen Kontodaten werden im Tab *Konto* aufgelistet.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*Zeitraum*
|Eine der folgenden Optionen aus der Dropdown-Liste wählen: *ALLE*, *Dieses Jahr*, *Letztes Jahr*, *Diesen Monat*, *Letzten Monat* oder *Letzte 3 Monate*.

|*Ausstehend*
|*ALLE*, *Ja* oder *Nein* wählen. +
*Ja* = Nur ausstehende Beträge werden angezeigt. +
*Nein* = Nur gezahlte Beträge werden angezeigt. +
*ALLE* = Ausstehende und gezahlte Beträge werden angezeigt.

|*Vergleichsoperator / Status*
|Vergleichsoperator und Auftragsstatus wählen.

|*Rechnungsnr.*
|Rechnungsnummer eingeben.

|*Auftrags-ID*
|Auftrags-ID eingeben.
|====

[#1900]
=== Lieferanschrift eingeben

Im Tab *Lieferanschriften* geben Sie die Lieferanschriften des Kunden ein. Sie können mehrere Lieferanschriften eingeben und diese Lieferanschriften dann pro Auftrag individuell zuordnen.

[.instruction]
Lieferanschrift eingeben:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Suchen Sie den Kunden anhand der <<crm/kundendaten-verwalten#1100, Filtereinstellungen>>.
. Öffnen Sie den Kunden.
. Wechseln Sie in das Tab *Lieferanschriften*.
. Klicken Sie auf *Neue Lieferadresse anlegen*.
. Klappen Sie den Bereich *Neue Lieferadresse anlegen* auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-lieferanschrift>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-lieferanschrift]]
.Einstellungen im Menü *CRM » Kunden bearbeiten » Kunde öffnen » Tab: Lieferanschriften*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Adresse

|*Firma (Name 1)*
|Firmenname eingeben, falls vorhanden.

|*Anrede*
|Ggf. Anrede aus der Dropdown-Liste wählen.

|*Vorname (Name 2)*
|Vorname eingeben.

|*Nachname (Name 3)*
|Nachname eingeben.

|*Zusatz (Name 4)*
|Ggf. Zusatzangaben zum Empfänger eingeben, z.B. z.Hd. Herrn Max Mustermann.

|*Straße (Adresse 1)*
|Straße, Packstation oder Postfiliale eingeben.

|*Hausnummer (Adresse 2)*
|Hausnummer oder ID der Packstation eingeben.

|*Zusatz (Adresse 3)*
|Ggf. Adresszusatz eingeben, z.B. Apartment 12a. +
Kunden können diese Angabe auch selbst im Bestellvorgang und im Mein Konto-Bereich eingeben. +
*_Hinweis_*: Einige Versanddienstleister verarbeiten dieses Feld nicht. Das bedeutet, dass der Zusatz nicht auf dem Etikett angezeigt wird. Dies kann dazu führen, dass eine Sendung nicht zugestellt werden kann. Zu folgenden Versanddienstleistern wird der Adresszusatz derzeit nicht übermittelt: +
DHL Freight +
DHL Supply Chain +
Swiss Post +
Um Kunden darüber zu informieren, in den genannten Bereichen z.B. einen Hinweis eingeben oder das Feld fallabhängig einblenden, z.B. per JavaScript-Skript.

|*Frei (Adresse 4)*
|Feld zur freien Verfügung.

|*Postleitzahl*
|Postleitzahl eingeben.

|*Ort*
|Ort eingeben.

|*Land*
|Land aus der Dropdown-Liste wählen.

|*Region/Bezirk*
|Region aus der Dropdown-Liste wählen. +
Je nach Land können hier z.B. Bundesstaaten oder Bundesländer gewählt werden. +
Wenn zu einem Land keine Regionen oder Bezirke verfügbar sind, ist die Dropdown-Liste deaktiviert. In der Kaufabwicklung und im Mein Konto-Bereich wird diese Option auch bei der Lieferanschrift angezeigt. Die Angabe kann in bestimmten Fällen notwendig sein, z.B. für PayPal in den USA.

2+|Adressoptionen

|*Umsatzsteuer-Identifikationsnummer*
|Umsatzsteuer-Identifikationsnummer eingeben, falls vorhanden.

|*Externe Adress-ID*
|Externe Adress-ID eingeben, falls vorhanden.

|*Gelangensbestätigung*
|Option aktivieren, um Aufträge von Kunden im EU-Ausland, die an eine inländische Lieferanschrift versendet werden, wie EU-Auslandslieferungen zu behandeln. Bei aktivierter Option werden Rechnungen für Aufträge aus dem EU-Ausland mit Lieferanschrift innerhalb Deutschlands gemäß den Einstellungen *Umsatzsteuer-ID* und *Ausfuhrlieferung* im Menü <<auftragsabwicklung/auftraege/buchhaltung#, System » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung>> ausgestellt. Ist die Option nicht aktiviert, werden diese Aufträge brutto berechnet. +
Für Anschriften, für die eine Gelangensbestätigung erforderlich ist, eine eigene Lieferanschrift anlegen und die Option aktivieren. +
*_Wichtig_*: Wenn bei zukünftigen Aufträgen keine Gelangensbestätigung mehr gewünscht ist, diese Option nicht deaktivieren, sondern eine weitere Lieferanschrift ohne Aktivierung der Option anlegen. Sonst kommt es zu Fehlberechnungen früherer Aufträge mit dieser Lieferanschrift.

|*Telefon*
|Telefonnummer eingeben.

|*E-Mail*
|E-Mail-Adresse eingeben.

|*Postnummer*
|DHL PostNummer eingeben.

|*Personennummer*
|Personennummer eingeben. Die Personennummer wird von skandinavischen Endkunden für skandinavische Zahlungsanbieter (z.B. Klarna) benötigt.

|*Altersfreigabe*
|Altersfreigabe aus der Dropdown-Liste wählen.
|====

[#2000]
=== Aufträge anzeigen

Sie können im Tab *Aufträge* alle Aufträge des Kunden auflisten und bearbeiten oder neue Aufträge anlegen. Die Funktionen entsprechen denen im Menü *Aufträge*. Details zur Auftragsbearbeitung finden Sie daher auf der Handbuchseite <<auftragsabwicklung/auftraege/auftraege-verwalten#auftrag-aendern, Auftrag ändern>>.

[#2100]
=== Abonnements anzeigen

Im Tab *Scheduler* werden Abonnements des Kunden angezeigt. Außerdem können neue Scheduler-Aufträge angelegt werden. Das Menü ist nur in Ihrem plentymarkets System sichtbar, wenn Sie es gebucht haben. Die Buchung erfolgt im Menü *Start » Service-Center » Tab: Vertrag*.

Weitere Informationen finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/scheduler#, Scheduler>>. Dort sind auch die Filteroptionen beschrieben, die Sie sowohl im Menü *CRM » Kunden bearbeiten » Kunde öffnen » Tab: Scheduler* als auch im Menü *Aufträge » Scheduler » Scheduler-Aufträge* wählen können.

[#2200]
=== Tickets anzeigen

Im Tab *Tickets* werden die Tickets des Kunden angezeigt. Sie können z.B. bestehende Tickets in diesem Tab bearbeiten und neue Tickets hinzufügen. Weitere Informationen zum Ticketsystem finden Sie auf der Handbuchseite <<crm/ticketsystem-nutzen#, Ticketsystem nutzen>>.

[#2300]
=== Events anzeigen

Im Tab *Events* speichern Sie die Events mit dem Kunden. Dies kann z.B. ein Anruf oder eine E-Mail sein. Sie können dort die Dauer eingeben, eine Information zum Vorgang wählen und einen Kommentar zum Event in das Textfeld eingeben. Dieser Kommentar wird dann in der Übersicht unter *Info* angezeigt. Für kostenpflichtige Events aktivieren Sie die Option *Abrechnen*.

[#2400]
=== Statistik erstellen

Im Tab *Statistik* erstellen Sie kundenspezifische Statistiken. Damit können Sie bestimmte Daten speziell für diesen Kunden auswerten und als Statistik anzeigen, z.B. den Gesamtumsatzverlauf des Kunden in einem bestimmten Zeitraum. Bestehende Statistiken können Sie auch in diesem Tab bearbeiten. Weitere Informationen finden Sie auf der Handbuchseite <<basics/statistik#100, Kundenstatistiken>>.

[.instruction]
Statistik erstellen:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Suchen Sie den Kunden anhand der <<crm/kundendaten-verwalten#1100, Filtereinstellungen>>.
. Öffnen Sie den Kunden.
. Wechseln Sie in das Tab *Statistik*.
. Klicken Sie auf *Neuer Bereich*.
. Geben Sie einen Namen ein.
. *Speichern* Sie die Einstellungen. +
→ Ein Tab mit dem soeben eingegebenen Namen wird geöffnet.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Neue Statistik* wird geöffnet.
. Wählen Sie den Statistiktyp aus dem Dropdown-Menu.
. *Speichern* Sie die Einstellungen. +
→ Die Daten werden geladen und angezeigt.

Je nachdem, welchen Statistiktyp Sie gewählt haben, finden Sie weitere Informationen in den folgenden Kapiteln der Handbuchseite <<basics/statistik#, Statistik>>:

* <<basics/statistik#20, Gesamtumsatzverlauf>>
* <<basics/statistik#100, Umsatz nach Kategorie>>
* <<basics/statistik#100, Umsatz Herkunft Auftrag>>

Allgemeine Informationen, wie Sie z.B. Statistiken bearbeiten, finden Sie auf der Handbuchseite <<basics/statistik#, Statistiken>>.

[#2500]
=== Einstellungen anzeigen und bearbeiten

Im Tab *Einstellungen* werden die Bankdaten, Passwort, Login-URL sowie Kostenstellen und Provisionen des Kunden gespeichert. Welche Einstellungen Sie in den Tabs *Bankdaten*, *Passwort*, *Login-URL*, *Kostenstellen* und *Provisionen* vornehmen können, wird in den folgenden Unterkapiteln beschrieben.

[#2600]
==== Bankdaten pflegen

Im Tab *Bankdaten* können Sie die Bankdaten des Kunden eingeben und diese bei Bedarf löschen. Die Bankdaten benötigen Sie z.B. für die Zahlungsart *Lastschrift*. Sie haben auch die Möglichkeit, die Bankdaten in plentymarkets zu importieren. Nutzen Sie dazu das Datenformat <<basics/datenaustausch/export-import/datenformate/customer#, Customer>>. Beachten Sie die aktuelle Rechtslage, auch in anderen Lieferländern.

[IMPORTANT]
.Abo-Aufträge beachten
====
Beachten Sie, dass die hier eingegebenen Bankdaten auch für Abo-Aufträge mit der Zahlungsart *Lastschrift* verwendet werden. Wenn Sie Bankdaten löschen, die mit einem solchen Abo-Auftrag verbunden sind, wird die Zahlungsart im <<auftragsabwicklung/auftraege/scheduler#, Scheduler>> auf die für den Mandanten (Shop) festgelegte <<omni-channel/online-shop/webshop-einrichten/bestellvorgang#, Standardzahlungsart>> zurückgesetzt. Der Abo-Auftrag wird dann nicht mehr per Bankeinzug beglichen. Löschen Sie die Bankdaten in einem solchen Fall daher nur, wenn es wirklich erforderlich ist, und geben Sie wenn möglich neue Bankdaten für den Kunden ein.
====

[#2700]
==== Neues Passwort vergeben

Im Tab *Passwort* geben Sie im Bereich *Passwort ändern* ein neues Passwort für den Kunden ein. Ob Sie das Passwort an den Kunden senden oder nicht, können Sie mit einem Klick auf *E-Mail an Kunden versenden* im Bereich *Passwort zurücksetzen* entscheiden.

Bei nicht erfolgreichem E-Mail-Versand prüfen Sie die <<crm/e-mails-versenden#100, Zugangsdaten>>. Im Menü <<basics/datenaustausch/api-log#, Daten » API-Log>> werden die Fehlermeldungen zum Vorgang *E-Mail* gespeichert.

Ein neues Passwort für alle Ihre Kunden generieren Sie im Menü *System » CRM » Passwörter*. Weitere Information finden Sie im Kapitel <<crm/kundendaten-verwalten#3100, Passwörter für alle Kunden neu generieren>>.


[#2800]
==== Login-URL einsehen

Im Tab *Login-URL* wird die URL für einen direkten Zugang zum Konto des Kunden im Webshop angezeigt. Wenn diese URL verwendet wird, ist eine Eingabe der Login-Daten (E-Mail-Adresse und Passwort) im Webshop nicht mehr nötig. Damit die Login-URL erzeugt wird, muss die E-Mail-Adresse im Menü *CRM » Kunden bearbeiten » Kunde öffnen » Tab: Kundendaten* im Feld *E-Mail* und das Passwort im Menü *CRM » Kunden bearbeiten » Kunde öffnen » Tab: Einstellungen » Tab: Passwort* eingegeben werden. Nach dem Speichern wird die Login-URL erzeugt. Verwenden Sie ein sicheres Passwort, andernfalls wird eine Fehlermeldung ausgegeben.

[#2900]
==== Kostenstelle anlegen

Im Tab *Kostenstellen* legen Sie Kostenstellen. Sie haben auch die Möglichkeit, bereits angelegte Kostenstellen zu bearbeiten. Bei einer Kostenstelle handelt es sich um den Ort der Kostenentstehung und Kostenzurechnung, quasi ein betrieblicher Bereich, der selbstständig abgerechnet wird.

[.instruction]
Kostenstelle anlegen:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Suchen Sie den Kunden anhand der <<crm/kundendaten-verwalten#1100, Filtereinstellungen>>.
. Öffnen Sie den Kunden.
. Wechseln Sie in das Tab *Einstellungen*.
. Öffnen Sie das Tab *Kostenstellen*.
. Öffnen Sie das Tab *Neue Kostenstelle*.
. Geben Sie den Namen für die Kostenstelle ein.
. Geben Sie das Budget für die Kostenstelle ein.
. Geben Sie das Restbudget für die Kostenstelle ein.
. Wählen Sie die *Budgetperiode* für das eingegebene Budget.
. *Speichern* Sie die Einstellungen. +
→ Die angelegte Kostenstelle finden Sie dann im Tab *Kostenstellen*.

[#3000]
==== Provision eingeben

Im Tab *Artikelprovisionen* geben Sie artikelbezogene Provisionen für den Kundentyp *Handelsvertreter* ein. Gehen Sie wie im Folgenden beschrieben vor, um Werte für Provisionen einzugeben.

[.instruction]
Provision eingeben:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Suchen Sie den Kunden anhand der <<crm/kundendaten-verwalten#1100, Filtereinstellungen>>.
. Öffnen Sie den Kunden.
. Wechseln Sie in das Tab *Einstellungen*.
. Öffnen Sie das Tab *Provisionen*.
. Öffnen Sie das Tab *Artikelprovisionen*.
. Klappen Sie den Bereich *Neue Provision* auf.
. Geben Sie die *Artikel-ID* des Artikels ein, für den Sie eine oder mehrere Provision(en) eingeben möchten.
. Geben Sie die Provision(en) in Prozent ein. +
→ Geben Sie bis zu 4 Provisionen pro Eintrag ein.
. *Speichern* Sie die Einstellungen. +
→ Die Provision wird gespeichert. Damit Sie auf einen Blick erkennen können, um welchen Artikel es sich handelt, wird nach erneutem Laden des Kundendatensatzes zusätzlich der Name des Artikels in der Übersicht angezeigt.

[#3050]
== Einzelnen Kunden löschen

Sie haben die Möglichkeit, einzelne Kunden im Menü *CRM » Kunden bearbeiten* im Tab *Kunden* zu löschen. Beachten Sie, dass Sie einen Kunden nur dann löschen können, wenn dieser nicht mit einem Auftrag verknüpft ist.

[.instruction]
Einzelnen Kunden löschen:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Suchen Sie den Kunden anhand der <<crm/kundendaten-verwalten#1100, Filtereinstellungen>>. +
→ Alle Kunden, die mit den Suchkriterien übereinstimmen, werden angezeigt.
. Klicken Sie in der Zeile des Kunden ganz rechts auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Der Kunde wird gelöscht und aus der Übersicht entfernt.

[TIP]
.Zum Löschen eines Kunden Aktionen einblenden
====
Beachten Sie, dass die Option *Aktionen* in der Kundenübersicht aktiviert sein muss. Wenn diese Option deaktiviert ist, können Sie den Kunden nicht löschen. Aktivieren Sie die Option *Aktionen* mit einem Klick auf die Titelleiste über die Funktion *Ansicht einrichten*. Weitere Informationen finden Sie im Kapitel <<basics/arbeiten-mit-plentymarkets/allgemeine-funktionen#50, Menüansicht einrichten>> auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/allgemeine-funktionen#, Allgemeine Funktionen nutzen>>.
====

[#3100]
== Passwörter für alle Kunden neu generieren

Im Menü *System » CRM » Passwörter* generieren Sie neue Passwörter für Ihre Kunden. Dies kann z.B. nötig sein, wenn sich jemand widerrechtlich Zutritt zu Ihrem plentymarkets System verschafft hat bzw. Sie von Datendiebstahl betroffen sind.

[WARNING]
.Kein automatischer Versand der neu generierten Passwörter
====
Beachten Sie, dass Ihre Kunden nicht automatisch die neu generierten Passwörter erhalten. Sie müssen Ihre Kunden aktiv, z.B. per E-Mail, über die Sachlage informieren und sie auffordern, ihr Passwort im Webshop bzw. Mein Konto-Bereich zu ändern.
====

Gehen Sie wie im Folgenden beschrieben vor, um neue Passwörter für alle Kunden zu generieren.

[.instruction]
Passwörter für alle Kunden neu generieren:

. Öffnen Sie das Menü *System » CRM » Passwörter*.
. Klicken Sie auf *Passwörter für alle Kunden neu generieren*. +
→ Die neuen Passwörter werden erzeugt.

[#3200]
== USt-IdNr. prüfen

Die Umsatzsteuer-Identifikationsnummer (USt-IdNr.) ist eine exklusive Identifikationsnummer und dient der Kennzeichnung von Umsatzsteuerpflichtigen. Innerhalb der EU wird sie für die Abrechnung der Umsatzsteuer durch die Finanzämter benötigt. Die USt-IdNr. wird im Menü *CRM » Kunden bearbeiten* im Tab *Kundendaten* des Kunden gespeichert und geprüft.

Die Prüfung der USt-IdNr. erlaubt die Verifizierung einer deutschen oder einer ausländischen USt-IdNr. und ist täglich von 5.00 bis 23.00 Uhr verfügbar. Geprüft werden können alle USt-IdNrn. aus Mitgliedsstaaten der EU mit Ausnahme der Slowakei und Lettland (nicht oder nur eingeschränkt möglich). Bei deutschen Ust-IdNrn. wird nur die Gültigkeit geprüft, die Zuordnung zu einer Person wird nicht geprüft. Bei ausländischen USt-IdNrn. wird die Gültigkeit geprüft und es werden die zugehörigen Firmennamen- und Adressdaten zur USt-IdNr. abgefragt und angezeigt.

[#3300]
=== USt-IdNr. in den Kundendaten prüfen

Gehen Sie wie im Folgenden beschrieben vor, um die USt-IdNr. in den Kundendaten zu prüfen.

[.instruction]
USt-IdNr. in den Kundendaten prüfen:

. Öffnen Sie das Menü *CRM » Kunden bearbeiten*.
. Suchen Sie den Kunden anhand der <<crm/kundendaten-verwalten#1100, Filtereinstellungen>>.
. Öffnen Sie den Kunden.
. Geben Sie im Tab *Kundendaten* die Umsatzsteuer-ID ohne Leerzeichen bei der Option *USt-IdNr.* ein.
. Klicken Sie auf *Prüfen*. +
→ Die Prüfung kann einige Minuten dauern.
. Wenn die Prüfung erfolgreich war, klicken Sie auf *Speichern*, um die USt-IdNr. zu sichern.

Als Resultat liefert die Anfrage das Ergebnis der Prüfung der USt-IdNr. sowie bei einer ausländischen USt-IdNr. zusätzlich den Firmennamen und die Adresse.

Wenn die USt-IdNr. gültig ist, wird der Status *Gültig* angezeigt. Bei ungültiger USt-IdNr. wird der Status *Ungültig* angezeigt. Wenn eine USt-IdNr. nicht geprüft werden kann, erhalten Sie den Hinweis, dass die USt-IdNr. nicht geprüft werden konnte. Nicht übereinstimmende Daten führen zu einer Fehlermeldung bei *Status*.

Die Prüfung der USt-IdNr. können Sie auch in den Kundendaten des Auftrags im Menü *Aufträge » Aufträge bearbeiten » Auftrag öffnen » Tab: Kunde » Tab: Kundendaten* vornehmen.

[#3400]
=== USt-IdNr. im Webshop prüfen

Im Webshop wird die USt-IdNr. automatisch im Bestellvorgang geprüft. Bei nicht gültiger USt-IdNr. kann der Käufer die Bestellung erst abschließen, wenn eine gültige USt-IdNr. eingegeben wird oder der Eintrag entfernt wird.

[#3500]
=== Prüfungsdaten exportieren

Sie können eine Liste aller Prüfungsdaten oder der Daten für den aktuellen Monat exportieren. Details zum Export der USt-ID-Prüfungsdaten finden Sie im Themenbereich <<basics/datenaustausch#, Datenaustausch>> auf der Handbuchseite <<basics/datenaustausch/export-import/daten-exportieren#, Daten exportieren>>.

[#3600]
== Offene Posten anzeigen

Im Menü *CRM » OP-Liste* erhalten Sie eine Übersicht über Kunden mit unbezahlten Aufträgen. OP steht für offene Posten. Die Liste enthält die Anzahl der offenen Posten eines Kunden sowie die Höhe der Forderung, die sich aus den offenen Posten ergibt.

Die Liste der offenen Posten wird einmal täglich automatisch aktualisiert. Forderungen werden daher teilweise erst am nächsten Tag in der Liste angezeigt. Sie haben aber auch die Möglichkeit, die <<crm/kundendaten-verwalten#3800, Liste manuell zu aktualisieren>>. Um alle offenen Posten anzuzeigen, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Offene Posten anzeigen:

. Öffnen Sie das Menü *CRM » OP-Liste*.
. Klicken Sie auf *Suchen*. +
→ Alle offenen Posten werden aufgeführt.

Aus der Liste heraus öffnen Sie den Kunden, indem Sie in der Spalte *ID* auf die ID klicken. Alternativ öffnen Sie eine Liste aller Aufträge des Kunden, in denen noch Posten offen sind, indem Sie in der Spalte *Aufträge* auf *Aufträge anzeigen* klicken.

[#3700]
=== Offene Posten filtern

Die Liste im Menü *CRM » OP-Liste* lässt sich nach *Typ*, *Land*, *Kundenklasse* und *Kundentyp* filtern. Offene Posten können Sie außerdem nach der Anzahl der *offenen Posten* oder der Höhe der *Forderung* sortieren.

[.instruction]
Offene Posten filtern:

. Öffnen Sie das Menü *CRM » OP-Liste*.
. Wählen Sie die Filtereinstellungen.
. Klicken Sie auf *Suchen*, um die gefilterten Ergebnisse anzuzeigen.

[#3800]
=== Offene Posten manuell aktualisieren

Die offenen Posten werden einmal täglich automatisch aktualisiert. Zwischendurch können Sie die Liste wie im Folgenden beschrieben manuell aktualisieren:

[.instruction]
Offene Posten manuell aktualisieren:

. Öffnen Sie das Menü *CRM » OP-Liste*.
. Klicken Sie im Bereich *OP-Liste generieren* auf *Generieren*. +
→ Die Liste wird im Hintergrund aktualisiert.
. Klicken Sie auf *Suchen*, um die aktualisierte Liste anzuzeigen.

[#3900]
== Rabattsystem nutzen

In plentymarkets haben Sie mehrere Möglichkeiten der Rabattierung. Sie können Ihren Kunden einen <<crm/kontakte-verwalten#26, Kundenklassenrabatt>>, einen <<crm/kontakte-verwalten#28, Rabatt auf die Zahlungsart>> sowie eine <<crm/kontakte-verwalten#27, Rabattstaffel auf den Nettowarenwert einer Bestellung>> gewähren. Außerdem können Sie <<crm/kontakte-verwalten#29, Verkaufspreise als Rabatte>> speichern und <<crm/kontakte-verwalten#30, manuelle Rabatte>> eingeben. Nehmen Sie die Einstellungen für die Rabattarten im Menü *System » CRM » Kundenklassen* vor. Wie Sie die Rabatte gewähren, wird in den folgenden Unterkapiteln beschrieben.

[#4000]
=== Kundenklassenrabatt einrichten

In einer Kundenklasse legen Sie Rabatte fest, die dann nur für die Kundenklasse wirksam werden. Darüber hinaus bestehen hier weitere Konfigurationsmöglichkeiten, z.B. die Aktivierung von Mengenrabatten der Verkaufspreise. Beachten Sie, dass sich je nach Konfiguration Rabatte addieren können.

Gehen Sie wie im Folgenden beschrieben vor, um einen Rabatt für Kundenklassen einzugeben.

[.instruction]
Kundenklassenrabatt einrichten:

. Öffnen Sie das Menü *System » CRM » Kundenklassen*.
. Klappen Sie die Kundenklasse, für die der Rabatt gelten soll, auf.
. Aktivieren Sie unter *Rabattart* die Option *Kundenklassenrabatt*. +
→ Eine weitere Einstellung wird geöffnet.
. Geben Sie unter *Rabatt in %* den Prozentwert für den Rabattabzug ein.
. Wählen Sie, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wählen Sie, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Geben Sie einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wählen Sie, ob die Preise im Webshop *brutto* (inkl. MwSt.) oder *netto* (ohne MwSt.) angezeigt werden sollen.
. *Speichern* Sie die Einstellungen.

Informationen, wie Sie Kundenklassen erstellen, finden Sie im Kapitel <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>.

[#4100]
=== Rabattstaffel auf Nettowarenwert einrichten

Möchten Sie Ihre Kunden mit Rabatten belohnen, wenn diese häufig und umsatzsteigernd in Ihrem Webshop einkaufen, können Sie hier Rabattwerte auf den Nettowarenwert des Auftrages festlegen.

[.instruction]
Rabattstaffel auf Nettowarenwert einrichten:

. Öffnen Sie das Menü *System » CRM » Kundenklassen*.
. Klappen Sie die Kundenklasse, für die die Rabattstaffel gelten soll, auf.
. Aktivieren Sie unter *Rabattart* die Option *Rabattstaffel auf Nettowarenwert*. +
→ Eine Tabelle mit weiteren Einstellungen wird geöffnet.
. Geben Sie unter *ab Nettowarenwert* die Betragsangaben aufsteigend ein.
. Geben Sie unter *Rabatt in %* die Prozentwerte für den Rabattabzug aufsteigend ein. +
→ Wenn Sie z.B. im Feld *ab Nettowarenwert* 50 eingeben und im Feld *Rabatt in %* 2 eingeben, werden ab 50 Euro 2% Rabatt gewährt.
. Wählen Sie, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wählen Sie, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Geben Sie einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wählen Sie, ob die Preise im Webshop *brutto* (inkl. MwSt.) oder *netto* (ohne MwSt.) angezeigt werden sollen.
. *Speichern* Sie die Einstellungen.

Informationen, wie Sie Kundenklassen erstellen, finden Sie im Kapitel <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>.

[.subhead]
Ansicht des Kunden beim Einkauf

Der Rabatt wird berechnet und angezeigt, wenn der Kunde seinen Einkauf beendet und zur Kasse geht. Im Warenkorb wird zunächst nur der gesamte Rabattbetrag ausgewiesen. Wenn der Kunde die Bestellung abschließt, wird zusätzlich zum Gesamtrabatt der Rabatt auf die einzelnen Artikelpositionen berechnet und angezeigt.

[#4200]
=== Rabatt auf Zahlungsart einrichten

Die Rabattart *Rabatt auf Zahlungsart* ist eine Art Skontoumsetzung in plentymarkets. Sie gewähren Kunden damit einen Rabatt auf die Verwendung einer oder mehrerer Zahlungsarten.

[TIP]
.Rabatt auf Zahlungsart direkt hinterlegen
====
Alternativ zur Konfiguration in diesem Menü ist es möglich, direkt bei einer Zahlungsart einen globalen Rabatt für diese Zahlungsart zu hinterlegen. Ein Beispiel ist ein prozentualer Rabatt bei der Zahlungsart *Vorkasse*. Beachten Sie dazu die Handbuchseite <<auftragsabwicklung/payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>. Die Konfiguration direkt bei der Zahlungsart erlaubt jedoch keine differenzierten Einstellungen wie bei der Option *Rabatt auf Zahlungsart* im Menü *System » CRM » Kundenklassen*.
====

Gehen Sie wie im Folgenden beschrieben vor, um einen Rabatt auf eine oder mehrere Zahlungsarten einzurichten.

[.instruction]
Rabatt auf Zahlungsart einrichten:

. Öffnen Sie das Menü *System » CRM » Kundenklassen*.
. Klappen Sie die Kundenklasse, für die der Rabatt gelten soll, auf.
. Geben Sie ein *Zahlungsziel* in Tagen ein, das Sie dieser Kundenklasse einräumen möchten.
. Aktivieren Sie unter *Rabattart* die Option *Rabatt auf Zahlungsart*. +
→ Eine Tabelle mit weiteren Einstellungen wird geöffnet.
. Wählen Sie eine oder mehrere Zahlungsarten, für die der Rabatt gelten soll.
. Geben Sie unter *Rabatt in %* den Prozentwert für den Rabattabzug ein.
. Wählen Sie, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wählen Sie, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Geben Sie einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wählen Sie, ob die Preise im Webshop *brutto* (inkl. MwSt.) oder *netto* (ohne MwSt.) angezeigt werden sollen.
. *Speichern* Sie die Einstellungen.

Informationen, wie Sie Kundenklassen erstellen, finden Sie im Kapitel <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>.

[#4300]
=== Verkaufspreis als Rabatt speichern

Ein mengenbezogener Rabatt wird im Menü *System » Artikel » Verkaufspreise* als eigener Preis angelegt. Dort legen Sie mit der Option *Ab Menge* im Bereich *Einstellungen* für den Verkaufspreis fest, ab welcher Artikelmenge der rabattierte Preis gelten soll. Eine Staffelung realisieren Sie durch das Anlegen entsprechender Verkaufspreise mit den gewünschten Mindestmengen. +
Der rabattierte Verkaufspreis wird aktiviert, wenn Sie in der Kundenklasse die Option *Mengenrabatt* auf *Berücksichtigen* setzen. Ein Kunde erhält den Rabatt, wenn der Kunde erstens zu der betreffenden Kundenklasse gehört und zweitens mindestens die beim Verkaufspreis gespeicherte Menge bestellt.

[.instruction]
Verkaufspreis als Rabatt speichern:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise*.
. Öffnen Sie den Verkaufspreis.
. Geben Sie im Tab *Einstellungen* im Feld *Ab Menge* eine Ziffer ein, ab welcher Artikelmenge der rabattierte Preis gelten soll.
. Aktivieren Sie im Bereich *Klasse* die Kundenklassen, für die der Verkaufspreis gelten soll.
. *Speichern* Sie die Einstellungen.

Weitere Informationen zu Verkaufspreisen finden Sie im Themenbereich <<artikel#, Artikel>> im Kapitel <<artikel/artikel-verwalten#870, Verkaufspreise verwalten>>.

[#4400]
=== Manuellen Rabatt eingeben

Zusätzlich zur Vergabe von automatischen Rabatten haben Sie auch die Möglichkeit, einzelnen oder allen Artikelpositionen eines Auftrags manuell einen Rabatt zuzuweisen. Sie können manuelle Rabatte in 2 verschiedenen Ansichten eingeben: in der Listenansicht der <<auftragsabwicklung/auftraege/auftraege-verwalten#suche, Auftragssuche>> und im Bearbeitungsfenster eines <<auftragsabwicklung/auftraege/auftraege-verwalten#auftrag-aendern, Auftrags>>.

[#4500]
==== Rabatt für einzelnen Artikel in der Auftragssuche eingeben

Wenn Sie schnell einzelnen Artikelpositionen eines Auftrags einen Rabatt zuweisen oder den Rabattwert ändern möchten, können Sie dies direkt in der Auftragssuche tun. Gehen Sie wie im Folgenden beschrieben vor, um einen Rabatt für einzelne Artikel in der Auftragssuche einzugeben oder zu ändern.

[.instruction]
Rabatt für einzelnen Artikel in der Auftragssuche eingeben:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die Auftragssuche wird angezeigt.
. Klicken Sie rechts in der Ansicht eines Auftrags auf *Rabatt* (Standard: *0%*). +
→ Ein Fenster zur Eingabe des Prozentsatzes wird geöffnet.
. Geben Sie den als Rabatt gewünschten Prozentsatz ein.
. *Speichern* Sie die Einstellung. +
→ Der Rabattwert wird angezeigt und der Rabatt wird von der Artikelposition abgezogen.

[#4600]
==== Rabatt für einzelnen Artikel im Auftrag eingeben

In der Auftragsübersicht werden ganz unten die Artikelpositionen angezeigt. Auch hier haben Sie die Möglichkeit, einzelnen Artikelpositionen einen Rabattwert zuzuweisen oder den Rabattwert zu ändern. Gehen Sie wie im Folgenden beschrieben vor, um einen Rabatt für einen Artikel im Auftrag einzugeben oder zu ändern.

[.instruction]
Rabatt für einzelnen Artikel im Auftrag eingeben:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag, auf den ein Rabatt gewährt werden soll, mit einem Klick auf die Auftragsnummer.
. Öffnen Sie im Tab *Übersicht* des Auftrags im unteren Bereich das Tab *Bearbeiten*.
. Wählen Sie aus der Dropdown-Liste *Rabatt* den Rabattsatz.
. *Speichern* Sie die Einstellungen.

[#4700]
==== Rabatt für alle Artikel eines Auftrags eingeben

Gehen Sie wie im Folgenden beschrieben vor, um einen Rabatt für alle Artikelpositionen eines Auftrags einzugeben bzw. zu ändern.

[.instruction]
Rabatt für alle Artikel eines Auftrags eingeben:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag, auf den ein Rabatt gewährt werden soll, mit einem Klick auf die Auftragsnummer.
. Öffnen Sie im Tab *Übersicht* des Auftrags im unteren Bereich das Tab *Bearbeiten*.
. Klicken Sie unterhalb der Liste der Artikelpositionen auf den Link *Rabatt für alle Artikel vergeben*.
. Wählen Sie aus der angezeigten Dropdown-Liste den Rabattsatz.
. Klicken Sie rechts neben der Dropdown-Liste auf *Speichern*.
. *Speichern* Sie die Einstellungen.
