= E-Mails versenden
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zugangsdaten, HTML-Design, Infodienst, E-Mail-Vorlage, Email-Vorlage, Email, E-Mail, Template-Variable, Template-Variablen, Template-Funktionen, automatische E-Mail, Ereignisaktion, Kaufabbruch-E-Mail
:description: Erfahre, wie du E-Mail-Vorlagen einrichtest und E-Mails automatisiert an deine Kunden versendest.
:position: 20
:url: crm/e-mails-versenden

Alle E-Mails, die über plentymarkets versendet werden, basieren auf E-Mail-Vorlagen. E-Mail-Vorlagen werden im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen* verwaltet. Erstelle beliebig viele E-Mail-Vorlagen in diesem Menü. Bei bestimmten Ereignissen, z.B. beim Eingehen neuer Bestellungen in deinem Webshop oder nachdem ein Kunde einen Newsletter abonniert hat, erstellt dein plentymarkets System automatisch E-Mails aus diesen Vorlagen und versendet diese an deine Kunden. Du legst fest, welche E-Mail wann automatisch versendet werden soll.

[#100]
== E-Mail-Server-Zugangsdaten speichern

Im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Zugangsdaten* speicherst du die Zugangsdaten des E-Mail-Postfachs, aus dem du E-Mails versenden möchtest, damit plentymarkets E-Mails wie Auftragsbestätigungen und Versandbestätigungen von dieser E-Mail-Adresse versenden kann.

[.instruction]
E-Mail-Server-Zugangsdaten speichern:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Zugangsdaten*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-e-mail-server-zugangsdaten>>.
. *Speichere* die Einstellungen.

[[tabelle-e-mail-server-zugangsdaten]]
.E-Mail-Server-Zugangsdaten speichern
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Testmodus*
|*Aktiv* oder *Inaktiv* wählen. +
*Aktiv* = Der Testmodus ist aktiviert. Alle E-Mails werden nur an die eingegebene E-Mail-Adresse gesendet. So kann vor dem Live-Betrieb die korrekte Funktionsweise geprüft werden. +
*Inaktiv* = Der Live-Modus ist aktiviert. +
*_Wichtig:_* Der Testmodus gilt nur für diesen Webshop. Die Einstellungen für weitere Mandanten werden im Menü des Mandanten (Shops) konfiguriert.

|*Name des Absenders*
|Eigenen Namen oder Namen des Webshops eingeben. Der Name wird dem Empfänger angezeigt. Für die korrekte Darstellung die Verwendung von Sonderzeichen vermeiden.

|*E-Mail-Adresse*
|E-Mail-Adresse eingeben, wie sie auch im E-Mail-Programm steht.

|*Postausgangsserver/SMTP-Server*
|Postausgangsserver wie vom Provider angegeben eingeben (meist smtp.domain.de oder mail.domain.de). +
*_mailbox.org:_* Für Postfächer bei mailbox.org den Postausgangsserver *smtp.mailbox.org* eingeben und Verschlüsselung *SSL* wählen.

|*Benutzername*
|Benutzername zu der E-Mail-Adresse eingeben. +
*_mailbox.org:_* Der mailbox.org-Benutzername ist die vollständige E-Mail-Adresse des mailbox.org-Postfachs.

|*Passwort*
|Passwort zu dem Benutzername und der E-Mail-Adresse eingeben.

|*Port (Standardport: 25)*
|Wert *25* eingeben. Dieser Wert ist für fast alle Provider korrekt. Ggf. den korrekten Port beim Provider erfragen. +
*_mailbox.org:_* Für Postfächer bei mailbox.org den Port *465* eingeben und unter *Verschlüsselung* die Einstellung *SSL* wählen.

|*Verschlüsselung*
|*SSL*, *TLS* oder *keine Verschlüsselung* wählen. Weitere Informationen findest du im Kapitel <<crm/e-mails-versenden#200, Verschlüsselung der E-Mail-Kommunikation wählen>>. +
*_mailbox.org:_* Für Postfächer bei mailbox.org den Port *465* eingeben und Verschlüsselung *SSL* wählen.
|====

[TIP]
.Newsletter-Zugangsdaten eingeben
====
Wenn du Newsletter an deine Kunden versenden möchtest, gibst du die Zugangsdaten im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Newsletter* ein. Weitere Informationen dazu findest du auf der Handbuchseite <<crm/newsletter-versenden#, Newsletter versenden>> im Kapitel <<crm/newsletter-versenden#200, Newsletter-Zugangsdaten eingeben>>.
====

[#200]
== Verschlüsselung der E-Mail-Kommunikation wählen

Die Verschlüsselungsmethoden *SSL*, *TLS* und die Einstellung *keine Verschlüsselung* stehen dir in plentymarkets zur Verfügung. Wähle für die Kommunikation mit dem E-Mail-Server eine dieser Verschlüsselungsmethoden. Welche Einstellungen du für die Methode vornehmen musst, wird in den folgenden Unterkapiteln beschrieben.

[#300]
=== Sicherheit durch SSL-Verschlüsselung

Richte für eine geschützte Datenübertragung zwischen deinen E-Mail-Programmen und deinem Postfach eine SSL-Verschlüsselung ein. <<tabelle-ssl-verschluesselung>> listet die Einstellungen für die SSL-Verschlüsselung im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Zugangsdaten* auf.

[[tabelle-ssl-verschluesselung]]
.Einstellungen für SSL-Verschlüsselung
[cols="1,3,3,3"]
|====
|Servertyp |Server |Verbindungssicherheit |Port

|*IMAP*
|mail.IHRE-DOMAIN.de
|SSL/TLS
|993

|*POP3*
|mail.IHRE-DOMAIN.de
|SSL/TLS
|995

|*SMTP*
|mail.IHRE-DOMAIN.de
|SSL/TLS
|587
|====

[#400]
=== Sicherheit durch STARTTLS

Um die Kompatibilität zu älteren E-Mail-Programmen zu gewährleisten, bietet plentymarkets auch STARTTLS an. <<tabelle-starttls-verschluesselung>> listet die Einstellungen für die STARTTLS-Verschlüsselung im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Zugangsdaten* auf.

[[tabelle-starttls-verschluesselung]]
.Einstellungen für STARTTLS-Verschlüsselung
[cols="1,3,3,3"]
|====
|Servertyp |Server |Verbindungssicherheit |Port

|*IMAP*
|mail.IHRE-DOMAIN.de
|STARTTLS
|143

|*POP3*
|mail.IHRE-DOMAIN.de
|STARTTLS
|110

|*SMTP*
|mail.IHRE-DOMAIN.de
|STARTTLS
|25
|====

[#500]
=== Unverschlüsselte Verbindung

[WARNING]
.Sicherheit nicht gewährleistet
====
In unverschlüsselter Form kann deine Kommunikation von Dritten eingesehen werden. Eine unverschlüsselte Übertragung entspricht nicht mehr den aktuellen Sicherheitsstandards.
====

<<tabelle-unverschluesselte-verbindung>> listet die Einstellungen für eine unverschlüsselte Verbindung im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Zugangsdaten* auf.

[[tabelle-unverschluesselte-verbindung]]
.Einstellungen für eine unverschlüsselte Verbindung
[cols="1,3,3,3"]
|====
|Servertyp |Server |Verbindungssicherheit |Port

|*IMAP*
|mail.IHRE-DOMAIN.de
|keine
|143

|*POP3*
|mail.IHRE-DOMAIN.de
|keine
|110

|*SMTP*
|mail.IHRE-DOMAIN.de
|keine
|25
|====

[#600]
== E-Mail-Signatur speichern

Im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Signatur* speicherst du deine Signatur, die dann in einer E-Mail-Vorlage automatisch eingefügt wird.

[IMPORTANT]
.Gesetzliche Vorgaben beachten
====
Beachte die für deinen Online-Shop geltenden gesetzlichen Vorgaben zum Inhalt einer E-Mail-Signatur, wie z.B. die Angabe der USt-IdNr. Die Pflichtangaben entsprechen denen der Geschäftsbriefe deines Unternehmens. Bei Nichtbeachten besteht die Gefahr eines Zwangsgeldes oder einer kostenpflichtigen Abmahnung durch einen Mitbewerber. Lasse dich im Zweifelsfall von einem kundigen Fachanwalt beraten.
====

[.instruction]
E-Mail-Signatur speichern:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Signatur*.
. Gib den Text deiner Signatur ein. Beachte dazu die Erläuterung in der grünen Box.
. *Speichere* die Einstellungen.

[TIP]
.Signatur mit Hilfe des HTML-Editors formatieren
====
Entscheide, ob du den Text deiner Signatur als *reine Textsignatur* oder als *HTML-Signatur* speicherst. Wenn du den Text formatieren möchtest, empfiehlt es sich, den Text im Bereich *HTML-Signatur* einzugeben. Dort steht dir der integrierte HTML-Editor zur Verfügung.

Im Menü *System » Systemeinstellungen » Einstellungen » Editoren* legst du fest, welche Editoren für bestimmte Bereiche in deinem plentymarkets System zur Verfügung stehen sollen. Wähle zwischen *Editor*, *Syntax-Editor* und *Textfeld*.
====


[#700]
== E-Mail-Infodienst einrichten

Du hast im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Email » Infodienst* die Möglichkeit, alle von deinem plentymarkets System ausgehenden E-Mails auf eine von dir gewählte E-Mail-Adresse als blinde Kopie (BCC) zu versenden. Besonders in der Anfangsphase deines Webshops erhältst du so eine gute Kontrolle über alle versendeten E-Mails und kannst erkennen, wo du Prozesse noch optimieren musst. Du kannst in diesem Menü auch einstellen, dass du bei Bestellungen automatisch eine Info-E-Mail erhältst.

[.instruction]
E-Mail-Infodienst einrichten:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Infodienst*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-e-mail-infodienst>>.
. *Speichere* die Einstellungen.

[[tabelle-e-mail-infodienst]]
.E-Mail-Infodienst einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Alle ausgehenden E-Mails werden als blinde Kopie (BCC) an die E-Mail-Adresse (nächste Zeile) gesendet*
|Einstellen, ob alle ausgehenden E-Mails als BCC an eine oder mehrere E-Mail-Adressen gesendet werden. Die E-Mail-Adressen werden in der nächsten Zeile eingegeben. +
*JA* = Option ist aktiviert. +
*NEIN* = Option ist deaktiviert (Standardeinstellung).

|*E-Mail-Adresse für blinde Kopie*
|E-Mail-Adresse(n) eingeben. Mehrere E-Mail-Adressen kommagetrennt und ohne Leerzeichen eingeben.

|*Blinde Kopien (BCC) für Newsletter deaktivieren*
|Wählen, ob blinde Kopien (BCC) bei Newslettern versendet werden. +
Option aktivieren = Es werden keine blinde Kopien bei Newslettern versendet. +
Option deaktivieren = Es werden blinde Kopien bei Newslettern versendet (Standardeinstellung).

|*Sende Hinweis bei Eingang einer neuen Bestellung an E-Mail (nächste Zeile)*
|Einstellen, ob bei einer neuen Bestellung eine E-Mail versendet wird. Die E-Mail-Adressen werden in der nächsten Zeile eingegeben. +
*JA* = Es wird eine E-Mail versendet, wenn eine Bestellung eingeht. +
*NEIN* = Es wird keine E-Mail versendet (Standardeinstellung). +
 *_Wichtig:_* Bei neuen Bestellungen über eBay ist diese Funktion nicht vorhanden. Es wird empfohlen stattdessen eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> einzurichten.

|*E-Mail-Adresse*
|E-Mail-Adresse(n) eingeben. Mehrere E-Mail-Adressen kommagetrennt und ohne Leerzeichen eingeben.
|====

[#800]
== HTML-Design verwenden

Im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » HTML-Design* hast du die Möglichkeit, pro Mandant (Shop) ein HTML-Design einzustellen, das dann für E-Mail-Vorlagen zur Verfügung steht. Du kannst das Design für jede E-Mail-Vorlage aktivieren und auch wieder deaktivieren.

Verwende diese Funktion, damit z.B. der Briefkopf inklusive Logo deines Unternehmens automatisch in den E-Mail-Vorlagen angezeigt wird und du diesen nicht bei jeder E-Mail-Vorlage separat einfügen musst. Wenn du in diesem Menü Änderungen vornimmst, änderst du das Design zentral für alle verknüpften E-Mail-Vorlagen.

Wenn du deine E-Mail-Vorlagen ohne zentrales HTML-Design erstellen möchtest, fahre mit dem Kapitel <<crm/e-mails-versenden#1200, E-Mail-Vorlage erstellen>> fort.

[#900]
=== Unternehmenslogo in der Bildergalerie hochladen

Du hast die Möglichkeit, deine E-Mail-Vorlagen an das Design deines Webshops anzupassen und z.B. dein Unternehmenslogo in das HTML-Design einzufügen. Lade zunächst das Logo in der Bildergalerie hoch. Nachdem du die E-Mail-Vorlage erstellt hast, füge  das <<crm/e-mails-versenden#1750, Logo in das HTML-Design>> ein und <<crm/e-mails-versenden#1100, verknüpfen>> dieses mit der E-Mail-Vorlage.

[.instruction]
Unternehmenslogo in der Bildergalerie hochladen:

. Öffne das Menü *CMS » Bilder-Galerie*.
. Klicke auf der linken Seite auf den Ordner, in den du das Logo hochladen möchtest. +
→ *_Oder:_* Erstelle einen neuen Ordner.
. Klicke auf *Dateien hochladen* oder ziehe die Datei per Drag&amp;Drop-Funktion in den Ordner. +
→ Das Bild wird hochgeladen.
. Klicke auf das Bild. +
→ Das Fenster mit dem Namen des Bildes wird geöffnet.
. Kopiere die URL aus dem Feld *Absolute URL*.
. Schließe das Fenster.

Weitere Informationen zur Bildergalerie findest du auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/cms#bilder-galerie, CMS>>.

[#1000]
=== Template-Variablen in das HTML-Design einfügen

Füge die Template-Variablen *$EmailContentHTML* und *$SignatureHTML* in das HTML-Design ein. Nachdem du die E-Mail-Vorlage erstellt hast, <<crm/e-mails-versenden#1100, verknüpfst>> du das HTML-Design mit der E-Mail-Vorlage.

[IMPORTANT]
.$EmailContentHTML muss vorhanden sein
====
Die Template-Variable *$EmailContentHTML* muss in das HTML-Design eingefügt werden. Andernfalls kann das HTML-Design nicht verwendet werden.
====

[.instruction]
Template-Variablen in das HTML-Design einfügen:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » HTML-Design*.
. Füge die Template-Variablen *$EmailContentHTML* und *$SignatureHTML* ein. +
→ *$EmailContentHTML* gibt den Inhalt der E-Mail aus. *$SignatureHTML* gibt die Signatur aus.
. Formatiere das HTML-Design nach deinen Wünschen.
. *Speichere* die Einstellungen.

Erstelle nun die E-Mail-Vorlage wie in den folgenden Kapiteln beschrieben und füge anschließend das <<crm/e-mails-versenden#1750, Logo in das HTML-Design>> ein und <<crm/e-mails-versenden#1100, verknüpfe>> dieses mit der E-Mail-Vorlage.

[#1200]
== E-Mail-Vorlage erstellen

Erstelle im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen* neue E-Mail-Vorlagen. Im Ordner *Allgemeine E-Mail-Vorlagen* sind bereits vorkonfigurierte E-Mail-Vorlagen enthalten, die du selbstverständlich anpassen kannst.

Für jede E-Mail-Vorlage kannst du bis zu 2 Anhänge definieren:
* ein PDF-Dokument aus dem Menü *Aufträge » Fulfillment*, z.B. eine Rechnung
* ein im Menü *CMS » Dokumente* hochgeladenes Dokument, z.B. ein Artikelprospekt oder eine Anleitung.

Diese Anhänge können standardisiert über E-Mail-Vorlagen an deine Kunden versendet werden. Für die E-Mail-Vorlage *Eingangsbestätigung Webshop Bestellung* wären z.B. die Widerrufsbelehrung und deine AGB im PDF-Format eine sinnvolle Ergänzung.

[TIP]
.Stornobeleg und Rechnung zusammen in einer E-Mail-Vorlage versenden
====
Es ist möglich, in der E-Mail-Vorlage in der Dropdown-Liste *PDF-Anhang*, die Option *Stornobeleg und neue Rechnung* zu wählen. Im Falle einer Änderung am Auftrag nach dem Erstellen der Rechnung kannst du so deinen Kunden beide Dokumente in nur einer E-Mail senden.
====

[.instruction]
E-Mail-Vorlage erstellen:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Klicke auf *Neue E-Mail-Vorlage*. +
→ Das Fenster *Neue E-Mail-Vorlage* wird geöffnet.
. Gib den Namen für die Vorlage ein.
. Wähle aus der Dropdown-Liste *Eigner* den Eigner oder die Option *Alle*.
. Klicke auf *Speichern*. +
→ Die E-Mail-Vorlage wird erstellt und abhängig von der gewählten Einstellung in der Dropdown-Liste *Eigner* in einem der 3 Ordner gespeichert.
. Nimm die restlichen Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-e-mail-vorlage>>.
. *Speichere* die Einstellungen.

[[tabelle-e-mail-vorlage]]
.Einstellungen im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Speichern*
|Speichert die Einstellungen in der E-Mail-Vorlage.

|*Template-Variablen -und Funktionen*
|Öffnet den Bereich *Template-Variablen -und Funktionen*, aus dem die Template-Variablen bzw. Template-Funktionen für die E-Mail-Vorlage kopiert werden.

2+|Tab: Einstellungen

|*Eigner*
|Wenn der Name des Eigners bereits beim Erstellen aus der Dropdown-Liste gewählt wurde, wird hier der Name des Eigners angezeigt. Andernfalls Eigner aus der Dropdown-Liste wählen. Diese Einstellung kann jederzeit geändert werden. +
*Alle* = Die Vorlage wird unter *Allgemeine E-Mail-Vorlagen* gespeichert. +
Eigener Benutzername = Die Vorlage wird unter *Meine E-Mail-Vorlagen* gespeichert. +
Anderer Benutzername = Die Vorlage wird unter *E-Mail-Vorlagen anderer Benutzer* gespeichert. +
*_Hinweis:_* Um eine eigene E-Mail-Vorlage unter *Meine E-Mail-Vorlagen* zu erstellen, muss man als Benutzer im System eingeloggt sein.

|*Name*
|Wenn der Name der E-Mail-Vorlage bereits beim Erstellen eingegeben wurde, wird hier der Name der E-Mail-Vorlage angezeigt. Andernfalls Namen eingeben, unter dem diese Vorlage gespeichert werden soll.
Der Name kann jederzeit geändert werden. Der Name wird dem Empfänger nicht angezeigt.

|*Inhalt*
|Wählen, ob der Inhalt der E-Mail-Vorlage als *Nur reiner Text* oder *Nur HTML-formatierter Text* gespeichert werden soll. +
*_Tipp:_* HTML-formatierten Text verwenden. Der Link zur Auftragsabwicklung (Template-Funktion *{%Link_Checkout()%}*) kann sehr lang sein. Bei reinen Text-E-Mails kann dies zu Zeilenumbrüchen führen, die den Link unter Umständen beschädigen. +
*_Wichtig:_* Wenn du weitere Sprachen im HTML-Format hinzufügst, achte darauf, dass im Tab *Einstellungen* in der Dropdown-Liste *Inhalt* wieder die Einstellung *Nur HTML-formatierter Text* gewählt ist. Die Auswahl *Nur reiner Text* ist die Standardeinstellung für alle Sprachen.

|*Template-Typ*
|Wählen, in welchem Bereich die E-Mail-Vorlage als Auswahl zur Verfügung steht. Mögliche Optionen: *Alle* (Standardeinstellung), *Auftrag*, *Kunden*, *Webshop*, *Ticket* oder *Scheduler*. +
*Alle* / *Webshop* = Die E-Mail-Vorlage steht in allen Bereichen als Auswahl zur Verfügung. +
*Auftrag* = Die E-Mail-Vorlage steht ausschließlich für den gewählten Bereich als Auswahl zur Verfügung. Die Vorlage ist in anderen Bereichen nicht sichtbar. Wenn das Ticket mit einem Auftrag verknüpft ist, sind E-Mail-Vorlagen mit dem Template-Typ *Auftrag* ebenfalls im Ticket wählbar. +
*Kunden* = Die E-Mail-Vorlage steht ausschließlich für den gewählten Bereich als Auswahl zur Verfügung. Die Vorlage ist in anderen Bereichen nicht sichtbar. +
*Ticket* = Die E-Mail-Vorlage steht ausschließlich für den gewählten Bereich als Auswahl zur Verfügung. Die Vorlage ist in anderen Bereichen nicht sichtbar. +
*Scheduler* = Die E-Mail-Vorlage steht in allen Bereichen, in denen auch der Template-Typ *Auftrag* sichtbar ist, als Auswahl zur Verfügung.

|*PDF-Anhang*
|Anhang aus der Dropdown-Liste wählen. Die Dokumente, die hier in der Dropdown-Liste zur Verfügung stehen, werden u.a. im Menü *Aufträge » Fulfillment* oder durch versandbezogene Prozesse erzeugt.

|*Dokumentenanhang*
|Auf Wunsch ein unter *CMS » Dokumente* hochgeladenes eigenes Dokumente wählen, das an die E-Mail-Vorlage anhängt werden soll. +
Alle E-Mail-Vorlagen können mit bis zu 2 Anhängen standardisiert an Kunden versendet werden: PDF-Dokumente aus dem Bereich Fulfillment (z.B. Rechnungen) oder andere Dateien (z.B. ein Artikelprospekt oder eine Anleitung). Für die Vorlage *Eingangsbestätigung Webshop Bestellung* wären z.B. die Widerrufsbelehrung und die AGB im PDF-Format eine sinnvolle Ergänzung.

|*Antwort an*
|E-Mail-Adresse eingeben, an die die Antworten auf diese E-Mail-Vorlage gesendet werden sollen. Wenn keine E-Mail-Adresse eingegeben ist, werden Antworten auf diese Vorlage standardmäßig an die unter <<crm/e-mails-versenden#100, System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Zugangsdaten>> gespeicherte E-Mail-Adresse versendet. Beispielsweise ist es sinnvoll, die E-Mail-Adresse der Buchhaltungsabteilung für die E-Mail-Vorlage *PDF-Rechnung* einzugeben. So gehen z.B. Rückfragen zur Rechnung direkt an die Buchhaltungsabteilung und müssen nicht erst weitergeleitet werden.

|*Design verwenden*
|Aktivieren, wenn der Inhalt der E-Mail mit dem im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » HTML-Design* gespeicherten Design versendet werden soll. Wird die Option nicht aktiviert, wird nur der Inhalt der E-Mail-Vorlage verwendet.

|*Mandant (Shop)*
|Einen, mehrere oder *ALLE* Mandanten (Shops) aktivieren. Die E-Mail-Vorlage ist nur für die gewählten Mandanten (Shops) gültig.

2+|Tab: E-Mail-Nachricht

|*Sprache wählen*
|Ggf. andere Sprache aus der Dropdown-Liste wählen. +
*_Hinweis:_* Die eingestellte Sprache im Kontaktdatensatz bestimmt, in welcher Sprache die E-Mail-Vorlage versendet wird.

|*Betreff*
|Betreff eingeben. Betreff sorgfältig wählen, damit die E-Mails im Postfach des Kunden leicht erkennbar sind und nicht als Spam-Nachricht eingestuft werden.

|*Inhalt / Artikelliste*
|In diese Tabs den Text bzw. die Artikelauflistung als *reinen Text* oder als *HTML-formatierten Text* eingeben. Für den Inhalt stehen verschiedene Template-Variablen und Template-Funktionen zur Verfügung. +
*_Hinweis:_* Nur der Inhalt des Tabs wird berücksichtigt, dessen Inhaltstyp im Tab *Einstellungen* unter *Inhalt* festgelegt wurde. Wenn dort also z.B. *Nur reiner Text* eingestellt wurde, jedoch nur das Tab *HTML-formatierter Text* Inhalt enthält, wird keine E-Mail versendet.
|====

[TIP]
.Tipp: HTML-formatierten Text verwenden
====
plentymarkets empfiehlt die Verwendung von HTML-formatiertem Text, da der Link zur Auftragsabwicklung sehr lang sein kann. Bei reinen Text-E-Mails kann dies zu Zeilenumbrüchen führen, die möglicherweise den Link beschädigen. Des Weiteren hast du bei der Verwendung von HTML-formatierten Text die Möglichkeit, den Text mit dem integrierten HTML-Editor zu formatieren.

Im Menü *System » Systemeinstellungen » Einstellungen » Editoren* legst du fest, welche Editoren für bestimmte Bereiche in deinem plentymarkets System zur Verfügung stehen sollen. Wähle den *Editor*, den *Syntax-Editor* oder das *Textfeld*.
====

[#1300]
=== Template-Variablen und Template-Funktionen verwenden

Für E-Mail-Vorlagen stehen Template-Variablen und Template-Funktionen zur Verfügung. Statt der Variablen oder Funktion wird dann von deinem plentymarkets System automatisch der definierte Inhalt abgebildet, d.h. in der E-Mail wird dann der Inhalt dargestellt. Außerdem erfüllen einige Template-Variablen die Funktion von Zuordnungsparametern, wenn du mit dem <<crm/ticketsystem-nutzen#4800, Ticketsystem>> arbeitest.

Öffne eine E-Mail-Vorlage im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen*, um eine Liste aller Template-Variablen und Template-Funktionen, die dir für deine E-Mail-Vorlagen zur Verfügung stehen, anzuzeigen.

Eine Übersicht der Template-Variablen und Template-Funktionen für E-Mail-Vorlagen findest du im Kapitel <<crm/e-mails-versenden#4000, Für E-Mail-Vorlagen verfügbare Template-Variablen und Template-Funktionen>>.

[TIP]
.Link zur Auftragsabwicklung in E-Mail-Vorlage einfügen
====
Möglichst in jeder E-Mail an den Kunden sollte der Link zur Auftragsabwicklung enthalten sein, da der Kunde darüber jederzeit den aktuellen Status seines Auftrags einsehen kann. Füge dazu die Template-Funktion *Link_Checkout()* in die E-Mail-Vorlage ein. Für die korrekte Ausgabe der URL musst die Template-Funktion folgendermaßen in die E-Mail-Vorlage einfügen: *{%Link_Checkout()%}*.
====

[#1400]
=== Anzeige der Artikelpositionen einrichten

Der Aufbau einer Artikelpositionenzeile kann pro E-Mail-Vorlage und Sprache einzeln eingerichtet werden. Beim Einrichten der Artikelpositionen kannst du <<crm/e-mails-versenden#1500, if-Abfragen>> verwenden. Wird die Anzeige der Artikelpositionen nicht eingerichtet, wird von plentymarkets eine Standardauflistung der Artikelpositionen ausgegeben.

[IMPORTANT]
.Template-Variable $OrderProperties in der Artikelliste hinzufügen
====
Die Template-Variable *$OrderProperties*, die die Bestellmerkmale ausgibt, ist nicht in der Standardauflistung der Artikelpositionen in E-Mail-Vorlagen vom Template-Typ *Auftrag* enthalten. Das bedeutet, dass Bestellmerkmale nicht in den Artikelpositionen ausgegeben werden. Wenn du möchtest, dass die Bestellmerkmale in der Artikelliste enthalten sind, musst du die Template-Variable *$OrderProperties* manuell hinzufügen.
====

[.instruction]
Anzeige der Artikelpositionen einrichten:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Öffne die Vorlage.
. Wechsele in das Tab *E-Mail-Nachricht*. +
→ Das Tab *Inhalt* wird angezeigt.
. Füge im Tab *HTML-formatierter Text* die Template-Variable *$ItemListHTML* oder im Tab *Reiner Text* die Template-Variable *$ItemListPlain* an der Stelle im Tab *Inhalt* der E-Mail ein, an der die Artikelpositionen angezeigt werden sollen.
. Kopiere die Template-Variablen aus der Übersicht, die du für die Artikelpositionen benötigst und füge die Template-Variablen im Tab *Artikelliste* ein. +
​→ Zur Formatierung füge z.B. Tabulatoren, die du aus einem Textprogramm kopiert hast, zwischen den Template-Variablen ein.
. *Speichere* die Einstellungen.

[.subhead]
Beispiel: Anzeige der Artikelpositionen

Füge die Template-Variablen zur Anzeige von Artikel-ID (*$ItemID*), Artikelname (*$ItemName*) und Preis (*$ItemPrice*) der Artikelpositionen ein. Die Anzeige beginnt mit einem Bindestrich. Dieser wird dann jeweils zu Beginn einer Zeile auch bei mehreren Artikelpositionen angezeigt. Damit die Anzeige mehrzeilig funktioniert, füge am Ende der Zeile durch Drücken der Enter-Taste einen Zeilenumbruch ein.

Wie du eine Vorschau öffnest, um deine E-Mail-Vorlage zu prüfen, ist im Kapitel <<crm/e-mails-versenden#1600, E-Mail-Vorlage anhand der Vorschau prüfen>> beschrieben.

[#1500]
=== if-Abfragen in E-Mail-Vorlagen verwenden

Setze in E-Mail-Vorlagen Fallunterscheidungen nach den Prinzipien der if-Abfragen ein. Füge z.B. einen Code ein, der bewirkt, dass die Bankdaten in der E-Mail an den Kunden nur angezeigt werden, wenn die Zahlungsart Vorkasse (ID = 0) gewählt wurde. Diese if-Abfrage ist im folgenden Beispiel zu sehen.

[source,plenty]
----
include::assets/E-Mail-Vorlagen-MethodOfPayment.html[]

----

Weitere Informationen findest auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/cms-syntax#grundlagen-if, if-Konstrukt>>.

[#1600]
=== E-Mail-Vorlage anhand der Vorschau prüfen

Du hast die Möglichkeit anhand der E-Mail-Vorschau zu prüfen, ob die E-Mail-Vorlage deinen Vorstellungen entspricht. Prüfe auch die korrekte Funktionsweise des Links zur Auftragsabwicklung. Gehe wie im Folgenden beschrieben vor, um die Vorschau der E-Mail-Vorlage aufzurufen.

[.instruction]
E-Mail-Vorlage anhand der Vorschau prüfen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag.
. Wechsele in das Tab *Mail*.
. Wähle im Tab *E-Mail-Vorlagen* die Sprache aus der Dropdown-Liste *Sprache wählen*.
. Wechsele in das Tab, in das du die E-Mail-Vorlage gespeichert hast: *Allgemeine E-Mail-Vorlagen*, *Meine E-Mail-Vorlagen* oder *E-Mail-Vorlagen anderer Benutzer*.
. Aktiviere die E-Mail-Vorlage.
. Klicke auf *Vorschau*. +
→ Das Fenster *E-Mail-Vorschau* wird geöffnet.

[#1700]
=== E-Mail-Vorlage bearbeiten

Du hast die Möglichkeit, allgemeine E-Mail-Vorlagen, deine eigenen E-Mail-Vorlagen und E-Mail-Vorlagen anderer Benutzer zu bearbeiten. Änderungen an den E-Mail-Vorlagen nimmst du im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen* vor.

[.instruction]
E-Mail-Vorlage bearbeiten:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Klicke auf den Ordner, in dem sich die E-Mail-Vorlage, die du bearbeiten möchtest, befindet.
. Klicke auf die E-Mail-Vorlage. +
→ Das Tab *Einstellungen* der E-Mail-Vorlage wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-e-mail-vorlage>> im Kapitel <<crm/e-mails-versenden#1200, E-Mail-Vorlage erstellen>>.
. *Speichere* die Einstellungen.

[TIP]
.E-Mail-Vorlage nach jeder Änderung prüfen
====
Jede Änderung an einer Vorlage sollte über den Mailservice eines Auftrags getestet werden. Besonders die korrekte Funktionsweise des Links zur Auftragsabwicklung sollte geprüft werden. Gehe dazu, wie im Kapitel <<crm/e-mails-versenden#1600, E-Mail-Vorlage anhand der Vorschau prüfen>> beschrieben, vor.
====

[#1750]
== Unternehmenslogo in das HTML-Design einfügen

Füge nun das Logo über einen Bild-Link in das HTML-Design der bereits erstellten E-Mail-Vorlage ein. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Unternehmenslogo in das HTML-Design einfügen:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Öffne die E-Mail-Vorlage, in der du das Logo einfügen möchtest.
. Wechsele in das Tab *E-Mail-Nachricht*.
. Wechsele im Tab *Inhalt* in das Tab *HTML-formatierter Text*.
. Wähle aus der Dropdown-Liste rechts oben die Option *Editor*. +
→ 2 Symbolleisten zum Formatieren des Textes werden eingeblendet.
. Klicke in der Symbolleiste auf *Bild*. +
→ Das Fenster *Bild-Eigenschaften* wird geöffnet.
. Füge im Feld *URL* die absolute URL ein, die du soeben in der Bilder-Galerie kopiert hast.
. Klicke auf *OK*. +
→ Das Logo wird angezeigt.
. *Speichere* die Einstellungen.


[#1100]
== HTML-Design mit der E-Mail-Vorlage verknüpfen

Um das HTML-Design mit einer E-Mail-Vorlage zu verknüpfen, nimmst du die folgenden Einstellungen im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen* vor. Der Inhalt der E-Mail-Vorlage muss im Tab *HTML-formatierter Text* vorhanden sein oder, wenn noch nicht, dort eingefügt werden. Dieser Inhalt wird dann über die Template-Variable *$EmailContentHTML* ausgegeben.

[.instruction]
HTML-Design mit der E-Mail-Vorlage verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Wähle die E-Mail-Vorlage aus dem Ordner.
. Wähle in der Zeile *Inhalt* die Option *Nur HTML-formatierter Text* aus der Dropdown-Liste.
. Aktiviere die Option *Design verwenden*.
. Gib im Tab *E-Mail-Nachricht* einen Betreff ein.
. *Speichere* die Einstellungen.

[#1800]
== E-Mails versenden

Für den Versand von E-Mails müssen im Menü <<basics/admin-aufgaben/benutzer-verwalten#10, System » Systemeinstellungen » Einstellungen » Benutzer » Konten>> Benutzerdaten gespeichert sein. Diese Daten sind von deinem Provider erhältlich und stimmen mit den Daten, die in deinem E-Mail-Programm gespeichert sind, überein.

[#1900]
=== Ticketnachrichten und Kommentare als E-Mails versenden

Du musst im Menü <<crm/ticketsystem-nutzen#2100, System » Systemeinstellungen » CRM » Ticketsystem » E-Mail-Konten>> ein E-Mail-Konto gespeichert haben, damit Nachrichten und Kommentare als E-Mails versendet werden. Außerdem musst du eine E-Mail-Vorlage, die die letzte Ticketnachricht oder den letzten Kommentar enthält, einrichten und diese in einer <<crm/ticketsystem-nutzen#2900, Ereignisaktion>> einstellen, damit der Versand per E-Mail durchgeführt wird. Weitere Informationen findest du auf der Handbuchseite <<crm/ticketsystem-nutzen#2100, Ticketsystem nutzen>>.

[#2000]
=== Gutscheine per E-Mail versenden

Versende Gutschein-Codes oder Gutscheine als PDF-Dateien per E-Mail. Details dazu findest du auf der Handbuchseite <<auftraege/gutscheine#, Gutscheine>> in den Kapiteln <<auftraege/gutscheine#100, Gutschein-Codes per E-Mail versenden>> und <<auftraege/gutscheine#140, Gutscheinvorlage einrichten>>.

[#2300]
== Automatischen E-Mail-Versand einrichten

Im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Automatischer Versand* stehen dir verschiedene Ereignisse zur Verfügung, die mit einer E-Mail-Vorlage verknüpft werden können. Wähle aus der Dropdown-Liste die E-Mail-Vorlage, die du zuvor im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen* <<crm/e-mails-versenden#1200, erstellt>> hast. Dadurch wird bei Eintritt des Ereignisses die E-Mail-Vorlage automatisch an den Kunden versendet.

[IMPORTANT]
.Verknüpfung vor Löschen der E-Mail-Vorlage entfernen
====
Das Löschen einer E-Mail-Vorlage, die mit einem Ereignis im Bereich *Automatischer Versand* verknüpft ist, kann zu unerwünschten Effekten führen. Entferne daher zunächst die Verknüpfung im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Automatischer Versand*, indem du in der Zeile des Ereignisses in der Dropdown-Liste die Option *Kein Versand* wählen. Anschließend löschst du die E-Mail-Vorlage im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen*.
====

[.instruction]
Automatischen E-Mail-Versand einrichten:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Automatischer Versand*.
. Wähle die in der Zeile des Ereignisses die E-Mail-Vorlage aus der Dropdown-Liste. Beachte dazu die Erläuterungen in <<tabelle-ereignisse-automatischer-e-mail-versand>>.
. *Speichere* die Einstellungen.

Mit einem Klick auf *E-Mail-Vorlage bearbeiten* wird die E-Mail-Vorlage im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen* geöffnet und kann dort <<crm/e-mails-versenden#1700, bearbeitet>> werden.

<<tabelle-ereignisse-automatischer-e-mail-versand>> listet Erläuterungen zu einigen der Ereignisse auf.

[[tabelle-ereignisse-automatischer-e-mail-versand]]
.Erläuterungen zu einigen Ereignissen im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Automatischer Versand*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Neue Bestellung über den Webshop*
|Sendet Kunden eine E-Mail mit der Auftragsbestätigung, nachdem der Kaufvorgang im Webshop abgeschlossen wurde.

|*Sende Kunde E-Mail zur Passwortänderung*
|Sendet Kunden eine E-Mail mit einem Link zum neuen Passwort, der aktiv bestätigt werden muss. Die Template-Funktion *{% Link_ChangePassword() %}* muss in der E-Mail-Vorlage enthalten sein.

|*Newsletter Opt-In*
|Sendet Kunden eine E-Mail, wenn die Kunden sich für den Newsletter angemeldet haben. Die E-Mail-Vorlage sollte den Bestätigungslink, den die Kunden anklicken müssen, um die Newsletter-Anmeldung abzuschließen, enthalten.

|*Bestätigung Newsletter Opt-In*
|Sendet Kunden eine E-Mail als Bestätigung, sobald die Kunden den Bestätigungslink, der mit der E-Mail-Vorlage für das Ereignis *Newsletter Opt-In* versendet wurde, aktiviert haben.

|*Erinnerung bei Kaufabbruch*
|Sendet Kunden eine E-Mail als Erinnerung, dass ein oder mehrere Artikel im Warenkorb liegen, der Kaufvorgang jedoch nicht abgeschlossen wurde. Die E-Mail-Vorlage sollte den Link zum Warenkorb enthalten, damit die Kunden diesen aufrufen und die Bestellung abschließen können. Dazu an die URL des Webshops den Suffix */basket/* anfügen (Beispiel: *https://www.meinshop.de/basket/*). +
Voraussetzung ist, dass die potenziellen Käufer beim Besuch im Webshop angemeldet und eingeloggt waren, da andernfalls die E-Mail-Adresse nicht vorliegt und der automatische Versand der E-Mail-Vorlage daher nicht funktionieren kann. +
*_Wichtig:_* Diese Art von E-Mail-Versand kann aufgrund der fehlenden vorherigen Einwilligung als unzulässiger Spam gelten. Lasse dich daher von einem kundigen Fachanwalt beraten.

|*Tell-A-Friend*
|Sendet eine E-Mail mit einem Link zu einem Artikel aus dem Webshop als Empfehlung an eine E-Mail-Adresse, die der Kunde im Webshop in das Tell-A-Friend-Formular eingetragen hat. +
*_Wichtig:_* Diese Art von E-Mail-Versand kann aufgrund der fehlenden vorherigen Einwilligung als unzulässiger Spam gelten. Lasse dich daher von einem kundigen Fachanwalt beraten.


|*Gewinnspielanmeldung*
|Sendet Kunden, die sich zum Gewinnspiel angemeldet haben, eine E-Mail als Bestätigung.

|*Benachrichtigung bei verfügbarem Artikel*
|Sendet Kunden eine E-Mail mit dem Hinweis, dass ein bestimmter Artikel wieder verfügbar ist. Der Kunde hat zuvor seine E-Mail-Adresse direkt bei dem nicht lieferbaren Artikel eingetragen.
|====

[#2350.subhead]
Automatischer E-Mail-Versand am Beispiel einer neuen Bestellung über eBay

Nachdem ein Kunde einen Artikel über eBay erworben hat, wird in plentymarkets automatisch ein Auftrag angelegt. Wenn du z.B. die E-Mail-Vorlage Auftragsbestätigung eBay <<crm/e-mails-versenden#1200, erstellt>> und diese im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Automatischer Versand* für das Ereignis *Neue Bestellung über eBay* aus der Dropdown-Liste definiert hast, wird automatisch eine E-Mail an den Kunden versendet. In der folgenden grünen Box findest du einen Beispieltext für die E-Mail-Vorlage.

[TIP]
.Beispieltext für eine E-Mail-Vorlage für den Versand nach einem Kauf über eBay
====
Sehr geehrte(r)$CustomerFullName,

herzlichen Glückwunsch zur gewonnenen Auktion.

Um die Kaufabwicklung so einfach wie möglich zu gestalten, klicken Sie bitte auf den folgenden Link oder kopieren Sie den Link in die Adresszeile Ihres Browsers.

Sie können über die Kaufabwicklung Ihre Daten einsehen und ändern sowie unsere Bankdaten einsehen. Verwenden Sie für Überweisungen immer den dort angegebenen Verwendungszweck.

*{%Link_Checkout()%}*
====

Parallel zum E-Mail-Versand kann dem Kunden auch eine Nachricht über das eBay-Nachrichtensystem gesendet werden. Dazu musst du im Menü *System » Systemeinstellungen » Märkte » eBay » Einstellungen » Tab: Kontoeinstellungen » Untermenü: Nachricht nach Kauf* den Text speichern. Weitere Informationen findest du auf der Handbuchseite <<maerkte/ebay/ebay-einrichten#, eBay einrichten>> im Kapitel <<maerkte/ebay/ebay-einrichten#1500, Nachrichten nach Kauf versenden>>.

[#2310.subhead]
Ereignisaktion einrichten

Du hast außerdem die Möglichkeit, Ereignisaktionen im Menü *System » Systemeinstellungen » Aufträge » Ereignisse* einzurichten. Definiere ein Ereignis, setze einen oder mehrere Filter und lege Aktionen fest, die von deinem plentymarkets System automatisch im Ereignisfall ausgeführt werden. Richte z.B. ein, dass der E-Mail-Versand eines Gutscheins ausgelöst wird, wenn der Kunde eine bestimmte Anzahl an Aufträgen generiert hat. Weitere Informationen findest du auf der Handbuchseite <<automatisierung/ereignisaktionen#, Ereignisaktionen>>.

[#2500]
== Gesendete E-Mail-Vorlagen pro Kunde anzeigen

Im Menü *Aufträge » Aufträge bearbeiten » Auftrag öffnen » Tab: Mail » Tab: Gesendete E-Mails* hast du die Möglichkeit, alle E-Mail-Vorlagen, die du an den Kunden versendet hast, anzuzeigen. Beachte, dass in diesem Tab nur die gesendeten E-Mail-Vorlagen angezeigt werden, die mit einer eindeutigen Kunden-ID verknüpft sind.

[.instruction]
Gesendete E-Mail-Vorlagen pro Kunde anzeigen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag.
. Wechsele in das Tab *Mail*.
. Wechsele in das Tab *Gesendete E-Mails*. +
→ Das Datum, die Uhrzeit, die E-Mail-Adresse des Empfängers, die ID und der Name der Vorlage sowie die Auftrags-ID werden angezeigt.

Klappe den Bereich *Weitere an den Kunden gesendete E-Mails...* auf, um alle E-Mails anzuzeigen, die an den Kunden gesendet wurden. Hier werden auch E-Mails angezeigt, die der Kunde aus einem anderen Auftrag heraus erhalten hat. Mit einem Klick auf die Auftrags-ID wird die Auftragsübersicht dieses Auftrags in einem separaten Tab geöffnet.

[#2600]
== Alle versendeten E-Mail-Vorlagen anzeigen

Im Menü *Start » Statistik* erstellst du eine neue Statistik und wählst im Bereich *Aufträge* den Statistiktyp *Versendete E-Mail-Vorlagen*. Du erhältst somit Informationen der über dein plentymarkets System versendeten E-Mails mit der ID und dem Namen der E-Mail-Vorlage sowie der datumsbezogenen Anzahl der E-Mails. Die Standardeinstellung der Zeitspanne beträgt die letzten 30 Tage. Du kannst die Zeitspanne jedoch auch anpassen oder ein Startdatum und ein Enddatum wählen.

Anhand dieser Statistik kannst du erkennen, welche E-Mail-Vorlage in welchem Zeitraum genutzt wurde und welche Vorgänge besonders häufig oder selten ausgeführt werden. Weitere Informationen dazu findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistik>>.


[#4000]
== Für E-Mail-Vorlagen verfügbare Template-Variablen und Template-Funktionen

[#4100]
=== Template-Funktionen

Für E-Mail-Vorlagen stehen dir die in <<tabelle-template-funktionen-e-mails>> aufgelisteten Link-Funktionen zur Verfügung.

[TIP]
.Korrekte Ausgabe von Template-Funktionen
====
Damit Template-Funktionen korrekt als URL ausgegeben werden, muss die Template-Funktion von *{%* und *%}* umschlossen sein.
====

[[tabelle-template-funktionen-e-mails]]
.Für E-Mail-Vorlagen verfügbare Template-Funktionen
[cols="1,3"]
|====
|Funktion |Erläuterung

|*Link_Checkout()*
|Diese Funktion gibt die URL zum Bereich *Mein Konto* des Webshops aus. +
*_Hinweis:_* Für die korrekte Ausgabe der URL *{%Link_Checkout()%}* in der E-Mail-Vorlage einfügen.

|*Link_TermsConditions()*
|Diese Funktion gibt die URL zu den AGB aus. +
*_Hinweis:_* Für die korrekte Ausgabe der URL *{%Link_TermsConditions()%}* in der E-Mail-Vorlage einfügen.

|*Link_Webstore()*
|Diese Funktion gibt die URL zum Webshop aus. +
*_Hinweis:_* Für die korrekte Ausgabe der URL *{%Link_Webstore()%}* in der E-Mail-Vorlage einfügen.

|*Link_NewPassword()*
|Diese Funktion gibt die URL zu einem Formular zum Erstellen eines neuen Passworts aus. Dort gibt der Kunde seine E-Mail-Adresse ein. +
*_Hinweis:_* Für die korrekte Ausgabe der URL *{%Link_NewPassword()%}* in der E-Mail-Vorlage einfügen.

|*Link_ChangePassword()*
|Diese Funktion gibt die URL zum Bereich *Passwort ändern* aus. Dort kann der Kunde ein neues Passwort eingeben. +
*_Hinweis:_* Für die korrekte Ausgabe der URL *{%Link_ChangePassword()%}* in der E-Mail-Vorlage einfügen.

|====

[#4200]
=== Template-Variablen

Template-Variablen sind vordefinierte Variablen, die in E-Mail-Vorlagen eingefügt werden können. Beim Versand der E-Mails wird die Variable automatisch mit dem entsprechenden Inhalt gefüllt. Template-Variablen beginnen mit einem Dollarzeichen ($), darauf folgt ein Großbuchstabe. <<tabelle-template-variablen-e-mails>> listet die für E-Mail-Vorlagen verfügbare Template-Variablen auf.


[TIP]
.Logik der Template-Variablen
====
Beachte, dass die Template-Variablen nur befüllt werden, wenn bestimmte Voraussetzungen erfüllt sind.

Beispiele:

* *$TicketLastMessage* wird nur befüllt, wenn eine Ereignisaktion eingerichet ist, die auf eine neue Ticketnachricht reagiert
* *$orderId* wird nur in Zusammenhang mit Aufträgen versendet. Das System würde z.B. bei der "Passwort vergessen"-Funktion gar nicht wissen, welche Auftrags-ID verwendet werden soll, da der Bezug fehlt.
====

[[tabelle-template-variablen-e-mails]]
.Für E-Mail-Vorlagen verfügbare Template-Variablen
[cols="1,3"]
|====
|Variable |Erläuterung

|$OrderID
|ID des Auftrags

|$OrderStatusLabel
|Statustext des Auftrags

|$OrderStatusID
|ID des Orderstatus

|$OrderEarliestDeliveryDate
|Frühestes Lieferdatum des Auftrags

|$OrderEstimatedShipmentDate
|Voraussichtliches Versanddatum des Auftrags

|$OrderReturnDate
|Datum des Retoureneingangs

|$CustomerID
|ID des Kontakts

|$CustomerEmail
|E-Mail-Adresse des Kontakts

|$CustomerFullName
|Vorname (Name2) und Nachname (Name 3) des Kontakts

|$CustomerState
|Region/Bezirk/Bundesland oder andere länderspezifische Einteilungen in der Kontaktadresse

|$CustomerAdditionalAddress
|Zusätzliche Adressinformationen in der Kontaktadresse

|$CustomerSign
|Kundenzeichen

|$EmailFrom
|Absender der E-Mail

// |$ItemURLTellAFriend
// |

|$EmailMessage
|Inhalt der E-Mail

|$EmailSubject
|Betreff der E-Mail

|$CustomerFirstName
|Vorname des Kontakts

|$CustomerLastName
|Nachname des Kontakts

|$CustomerSalutationKey
|Mögliche Werte: 0 = male und 1 = female. Richtet sich nach der im Kontaktdatensatz gespeicherten Anrede.

|$CustomerSalutationLabel
|Mögliche Werte: Herr und Frau. Richtet sich nach der im Kontaktdatensatz gespeicherten Anrede.

|$CustomerCompany
|Angegebene Firma des Kontakts

|$CustomerStreet
|Straße des Kontakts

|$CustomerCityWithZip
|Ort und Postleitzahl des Kontakts

|$CustomerCity
|Ort des Kontakts

|$CustomerZip
|Postleitzahl des Kontakts

|$CustomerCountry
|Land des Kontakts

|$CustomerCountryID
|Länder-ID des Kontakts

|$CustomerCountryIsoCode
|Länder-ISO-Code des Kontakts

|$CustomerPhone
|Telefonnummer des Kontakts

|$CustomerMobilePhone
|Mobilfunknummer des Kontakts

|$CustomerFax
|Faxnummer des Kontakts

|$CustomerEbayName
|eBay-Name des Kontakts

|$IsNewsletterActive
|Markierung, die angibt, ob der Kontakt dem Newsletter-Empfang zugestimmt hat.

|$NewsletterConfirmURL
|URL zur Bestätigung des Newsletter-Abonnements

|$CustomerLang
|Sprache des Kontakts

|$CustomerClass
|Kundenklasse

|$CustomerNumber
|Kundennnummer

|$CustomerTitle
|Titel des Kontakts

|$OrderCount
|Auftragsanzahl

|$ExternalOrderID
|Externe Auftrags-ID

|$Currency
|Währung

|$ReturnReasonID
|ID des Rücksendegrunds. +
Rücksendegründe werden im Menü *System » Systemeinstellungen » Aufträge » Auftragstypen » Retoure* gespeichert.

|$ReturnReasonLabel
|Text des Rücksendegrunds. +
Rücksendegründe werden im Menü *System » Systemeinstellungen » Aufträge » Auftragstypen » Retoure* gespeichert.

|$VoucherCodes
|Alle Codes aller Gutscheine für einen Auftrag durch Komma getrennt

|$CustomerIBAN
|IBAN des Kontakts

|$CustomerBIC
|BIC des Kontakts

|$CustomerAccountOwner
|Name des Kontoinhabers

|$CustomerBankName
|Name der Bank des Kontakts

|$GeneralTermsConditionsText
|AGB im reinen Textformat. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Rechtliches » Sprache aufklappen » Tab: AGB » Tab: Text* gespeichert.

|$GeneralTermsConditionsHTML
|AGB im HTML-Format. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Rechtliches » Sprache aufklappen » Tab: AGB » Tab: HTML* gespeichert.

|$CancellationRightsText
|Widerrufsrecht im reinen Textformat. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Rechtliches » Sprache aufklappen » Tab: Widerrufsrecht » Tab: Text* gespeichert.

|$CancellationRightsHTML
|Widerrufsrecht im HTML-Format. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Rechtliches » Sprache aufklappen » Tab: Widerrufsrecht » Tab: HTML* gespeichert.

|$PrivacyPolicyText
|Datenschutzerklärung im reinen Textformat. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Rechtliches » Sprache aufklappen » Tab: Datenschutzerklärung » Tab: Text* gespeichert.

|$PrivacyPolicyHTML
|Datenschutzerklärung im HTML-Format. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Rechtliches » Sprache aufklappen » Tab: Datenschutzerklärung » Tab: HTML* gespeichert.

|$LegalDisclosureText
|Impressum im reinen Textformat. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Rechtliches » Sprache aufklappen » Tab: Impressum » Tab: Text* gespeichert.

|$LegalDisclosureHTML
|Impressum im HTML-Format. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Rechtliches » Sprache aufklappen » Tab: Impressum » Tab: HTML* gespeichert.

|$WithdrawalFormText
|Widerrufsformular im reinen Textformat. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Rechtliches » Sprache aufklappen » Tab: Widerrufsformular » Tab: Text* gespeichert.

|$WithdrawalFormHTML
|Widerrufsformular im HTML-Format. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Rechtliches » Sprache aufklappen » Tab: Widerrufsformular » Tab: HTML* gespeichert.

|$DeliveryAddressFullName
|Vor- und Nachname in der Lieferadresse

|$DeliveryAddressAdditionalAddress
|Zusätzliche Adressinformationen in der Lieferadresse

|$DeliveryAddressFirstName
|Vorname in der Lieferadresse

|$DeliveryAddressLastName
|Nachname in der Lieferadresse

|$DeliveryAddressCompany
|Firma in der Lieferadresse

|$DeliveryAddressPhone
|Telefonnummer in der Lieferadresse

|$DeliveryAddressPostident
|Postident-Nummer in der Lieferadresse

|$DeliveryAddressStreet
|Straße in der Lieferadresse

|$DeliveryAddressCityWithZip
|Ort und Postleitzahl in der Lieferadresse

|$DeliveryAddressCity
|Ort in der Lieferadresse

|$DeliveryAddressZip
|Postleitzahl in der Lieferadresse

|$DeliveryAddressCountry
|Land in der Lieferadresse

|$DeliveryAddressCountryID
|Länder-ID in der Lieferadresse

|$DeliveryAddressCountryIsoCode
|Länder-ISO-Code in der Lieferadresse

|$DeliveryAddressState
|Region/Bezirk/Bundesland in der Lieferadresse

|$OrderEstimatedDeliveryDate
|Voraussichtliches Lieferdatum der Bestellung

|$OrderBillingAddressTaxId
|Umsatzsteuer-ID in der Rechnungsadresse des Auftrags

|$OrderDeliveryAddressTaxId
|Umsatzsteuer-ID in der Lieferadresse des Auftrags

|$ShippingCosts
|Versandkosten

|$ValueOfItems
|Wert der Artikel

|$CouponValue
|Wert des Gutscheins

|$InvoiceTotal
|Gesamtrechnungsbetrag in brutto und durch Komma getrennt

|$InvoiceTotalDecimalSeparatorDot
|Gesamtrechnungsbetrag in brutto und durch Punkt getrennt

|$InvoiceTotalNet
|Gesamtrechnungsbetrag in netto und durch Komma getrennt

|$TotalVAT
|Gesamtbetrag der Mehrwertsteuer am Auftrag

|$OrderTotalNet
|Gesamtbetrag des Auftrags in netto

|$OrderDate
|Auftragsdatum

|$PaymentDate
|Datum des Zahlungseingangs

|$TodaysDate
|Aktuelles Datum

|$PackageCount
|Paketnummern. Werden im Auftrag gespeichert.

|$TrackingURL
|Tracking-URL zur Sendungsverfolgung. +
Die URL wird im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister* gespeichert.

|$BankAccount
|Kontonummer. Wird im Menü *System » Systemeinstellungen » Einstellungen » Bank* gespeichert.

|$BankCode
|Bankleitzahl. Wird im Menü *System » Systemeinstellungen » Einstellungen » Bank* gespeichert.

|$BankOwner
|Vorname und Nachname des Kontoinhabers. Wird im Menü *System » Systemeinstellungen » Einstellungen » Bank* gespeichert.

|$BankName
|Name der Bank. Wird im Menü *System » Systemeinstellungen » Einstellungen » Bank* gespeichert.

|$BankIBAN
|Internationale Bankleitzahl. Wird im Menü *System » Systemeinstellungen » Einstellungen » Bank* gespeichert.

|$BankSwift
|Bank Identifier Code. Wird im Menü *System » Systemeinstellungen » Einstellungen » Bank* gespeichert.

|$ShippingServiceProviderName
|Name des Versanddienstleisters

|$ShippingServiceProviderID
|ID des Versanddienstleisters

|$MethodOfPaymentName
|Name der Zahlungsart wie im Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten* gespeichert.

|$MethodOfPaymentID
|ID der Zahlungsart. +
Die IDs sind vom System vergeben. Im Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten* sind die IDs aufgeführt.

|$ShippingProfileID
|ID des Versandprofils

|$ShippingProfileName
|Name des Versandprofils

|$ReferrerID
|ID der Herkunft

|$ReferrerName
|Name der Herkunft

|$PaidAmount
|Bezahlter Betrag

|$OpenAmount
|Ausstehender Betrag

|$OverpaidAmount
|Betrag der Überbezahlung

|$PartialPaymentAmount
|Teilzahlungsbetrag

|$PartialPaymentOpenAmount
|Ausstehender Teilzahlungsbetrag

|$WarehouseID
|ID des Lagers. +
Die ID wird vom System vergeben und kann nicht geändert werden. Die ID ist im Menü *System » Systemeinstellungen » Waren » Lager » Lager öffnen » Einstellungen* gespeichert.

|$WebstoreID
|ID des Mandanten. +
Die ID wird vom System vergeben und kann nicht geändert werden. Die ID ist im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Einstellungen* gespeichert.

|$EbaySellerAccount
|

|$EbayUniquePaymentID
|

|$SignatureText
|Signatur im reinen Textformat. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Signatur* gespeichert.

|$SignatureHTML
|Signatur im HTML-Format. +
Der Text wird im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Signatur* gespeichert.

|$RebateAmount
|Rabattbetrag

|$BarcodeOrderID
|Barcode der Auftrags-ID

|$ItemCategoryLevel1List
|ID der Kategorie, in der sich der Artikel befindet

|$CustomerSpecialWishes
|Kundenwunsch. Ein Kunde kann bei der Bestellung über den Webshop einen Wunsch angeben. Dieser Wunsch wird als Auftragsnotiz in den Auftragsdaten gespeichert.

|$CouponCode1
|Gutschein-Code 1

|$CouponCode2
|Gutschein-Code 2

|$CouponCode3
|Gutschein-Code 3

|$CouponCode4
|Gutschein-Code 4

|$CouponCode5
|Gutschein-Code 5

|$CouponCode6
|Gutschein-Code 6

|$CouponCode7
|Gutschein-Code 7

|$CouponCode8
|Gutschein-Code 8

|$CouponCode9
|Gutschein-Code 9

|$CouponCode10
|Gutschein-Code 10

|$OrderType
|Auftragstyp

|$OrderAccessKey
|Mit einem Klick auf *Kaufabwicklung* in der Auftragsübersicht wird der Auftrag im Mein Konto-Bereich des Webshops geöffnet.

|$TrustedShopsRating
|Bewertungsergebnis der bei Trusted Shops abgegebenen Bewertungen

|$TrustedShopsRatingShopButton
|

|$TrustedShopsRatingEmailButton
|

|$TrustedShopsSeal
|Trusted Shop-Gütesiegl

|$SchedulerID
|ID des Scheduler-Auftrags

|$SchedulerStartDate
|Startdatum des Scheduler-Auftrags

|$SchedulerEndDate
|Enddatum des Scheduler-Auftrags

|$SchedulerExecutionCount
|Anzahl der Aufträge, die der Scheduler-Auftrag umfasst

|$SchedulerInterval
|Scheduler-Intervall

|$SchedulerTotalAmount
|Gesamtbetrag der Scheduler-Aufträge

|$TicketHistory
|Der zuletzt gespeicherte Text im Ticket, d.h. der Text eines Kommentare oder einer Nachricht

|$TicketLastComment
|Der letzte Kommentar im Ticket

|$TicketLastMessage
|Die letzte Nachricht im Ticket

|$TicketURL
|Verlinkt zum Ticket im Bereich *Mein Konto* des Kontakts

|$TicketBackendURL
|Verlinkt zum Ticket im Menü *CRM » Ticketsystem*

|$TicketTitle
|Betreff des Tickets

|$TicketID
|Ticket-ID

|$TicketTags
|Zeigt die mit dem Ticket verknüpften Tags an. +
Die Tags müssen zuvor im Menü *System » Systemeinstellungen » Einstellungen » Tags* für den Bereich *Ticket* erstellt werden.

|$TicketStatus
|Status des Tickets

|$TicketPriority
|Priorität des Tickets

|$ReorderID
|ID der Nachbestellung

|$ReorderDeliveryDate
|Lieferdatum der Nachbestellung

|$EventType
|Typ des Events

|$EventInfo
|Informationen zum Event

|$EventDuration
|Dauer des Events

|$EventBilled
|Markierung für abgerechnetes Event

|$EventNotBilled
|Markierung für nicht abgerechnetes Event

//|$EventBilledRequiringPayment
//|

//|$EventNotBilledRequiringPayment
//|

|$EventBillable
|Markierung für Event, das abgerechnet werden kann

//|$EventStaffer
//|

|$ForumSubscription
|Anmeldung im Forum

2+|$ItemListPlain / $ItemListHTML

|$ItemID
|ID des Artikels

|$OrderProperties
|Bestellmerkmale

|$ReturnItemStatusID
|

|$ReturnItemStatusLabel
|

|$ItemNumber
|Artikelnummer

|$ItemName
|Artikelname

|$ItemQuantity
|Anzahl des Artikels

|$ItemPrice
|Artikelpreis

|$ItemPriceNet
|Nettopreis des Artikels

|$ItemReferrer
|Herkunft des Artikels

|$ExternalItemID
|Externe Artikel-ID

|$ExternalVariationID
|Externe Varianten-ID

|$TransactionID
|Transaktions-ID

|$UnitString
|Einheit des Artikels

|$VariationName
|Variantenname

|$VariationNumber
|Variantennummer

|$VariationId
|Varianten-ID

|$VariantName
|Variantenname

|$ItemModel
|Modellbezeichnung des Artikels

|$ItemEAN
|Internationale Artikelnummer (EAN)

|$ItemISBN
|ISBN-Code des Artikels

|$ItemASIN
|Amazon Standard Ident Number (ASIN) des Artikels

|$ItemAvailabilityLabel
|Text der Artikelverfügbarkeit

|$ItemAvailabilityID
|ID der Artikelverfügbarkeit

|$Free
|Freitextfeld für die Artikel. Die Texte werden im Menü *System » Systemeinstellungen » Artikel » Freitextfelder* gespeichert. Für die Ausgabe der Feldbezeichnungen die Feldnummer in eckigen Klammer dahinter schreiben. +
*_Beispiel:_* *$Free[3]* gibt den Text, der unter *Feld 3* gespeichert ist, aus.

|$DownloadLink
|Download-Link z.B. zu Produktinformationen, der im Mein Konto-Bereich des Webshops eingebunden werden kann. +
*_Hinweis:_* Die Dateien werden im Tab *Media* des Artikels hochgeladen. +
*_Wichtig_:* Im Tab *Media* hochgeladene Dateien können für den Ceres-Webshop nicht genutzt werden.

|$ItemImageURL
|URL zum Artikelbild

|$ItemProducerName
|Name des Herstellers

|$ItemVatRate
|Mehrwertsteuersatz für die einzelne Auftragsposition in Prozent (ohne Angabe des Prozentzeichens)

|$ItemWarehouseID
|Lager-ID des Artikels

|$SchedulerItemStartDate
|Startdatum

|$SchedulerItemEndDate
|

|$ReturnItemComment
|

|$ReturnItemValuePercentage
|

|$ReturnItemReasonID
|

|$ReturnItemReasonLabel
|

|$ItemVoucherCodes
|Codes eines Gutscheins pro Auftragsposition durch Komma getrennt

|====
