= EmailBuilder (Vorschau)
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:description: Erfahre, wie du den EmailBuilder in plentymarkets verwendest.
:position: 19
:url: crm/emailbuilder
:id: MYFLVYO
:author: team-crm

Der EmailBuilder ist ein Baukastenmodul, mit dem du deine E-Mail-Vorlagen schnell und einfach per Drag-and-drop erstellen und bearbeiten kannst. Dafür benötigst du keinerlei Programmierungskenntnisse. +
Der EmailBuilder besteht aus 2 Ansichten: dem Konfigurationsmanager und dem Editor. Im Konfigurationsmanager erstellst du Ordner, ggf. Unterordner, Textblöcke, Vorlagen sowie Vorlagen für deinen Footer und deinen Header. Im Editor befüllst du deine Vorlagen, Textblöcke, Header und Footer mit Inhalt. Du kannst zum Beispiel eine Vorlage für eine Rechnung erstellen und diese zukünftig für alle Rechnungen an deine Kund:innen verwenden. +
Die Header- und Footer-Vorlagen kannst du dann beliebig in deinen E-Mail-Vorlagen verwenden. Header und Footer sind global wirksam; Änderungen, die du am Header und Footer vornimmst, wirken sich demnach auch auf alle bestehenden Vorlagen sowie weitere Vorlagen, die du zukünftig erstellst, aus.


//Jenna fragen: Konfigurationsmanager? Oder Content-Manager? So wie im ShopBuilder?

// Screenshot einfügen
// überall: Icons einfügen

[#ordner-verwalten]
== Ordner verwalten

Du kannst beliebig viele Ordner und Unterordner erstellen. Nachdem der Ordner erstellt ist, kannst du über das Kontextmenü (icon:ellipsis-v[]) neue Unterordner, neue Textblöcke, neue Vorlagen und neue Vorlagen für Header und Footer erstellen.

Mit dem Header und dem Footer erstellst du sozusagen das Gerüst deiner E-Mail. Der Textblock bildet den eigentlichen Inhalt deiner E-Mail.

// (Screenshot einfügen).

// Vorlage = Gerüst mit Header und Footer
//Textblock = Inhalt der E-Mail

[#ordner-erstellen]
=== Ordner erstellen

Erstelle Ordner, um später eine bessere Übersicht für deine E-Mail-Vorlagen zu bekommen. Gehe wie im Folgenden beschrieben vor, um einen neuen Ordner zu erstellen.

[instruction]
Ordner erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke auf icon:plus[role="green"] *Neuer Hauptordner*. +
→ Ein Fenster wird geöffnet.
. Gib den Namen für den Ordner ein.
. *Speichere* die Einstellungen. +
→ Der neue Ordner wird der Ordnerliste hinzugefügt.

[#ordername-aktualisieren]
=== Ordnernamen aktualisieren

Du kannst den Namen des Ordners jederzeit anpassen. Gehe dazu wie im Folgenden beschrieben vor.

[instruction]
Ordnernamen aktualisieren:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke auf den Ordner, den du bearbeiten möchtest. +
→ Ein Fenster wird geöffnet.
. Gib einen anderen Namen für den Ordner ein.
. Klicke auf *Aktualisieren*. +
→ Der neue Name des Ordners wird aktualisiert und in der Liste angezeigt.

[#unterordner-erstellen]
=== Unterordner erstellen

Erstelle Unterordner in deinen Ordnern, um deine E-Mail-Vorlagen später noch differenzierter zu gruppieren. Du kannst beliebig viele Unterordner erstellen. Auch die Anzahl der Ebenen ist unbegrenzt.

[TIP]
.Entwurf für deine Ordner-Struktur im Vorfeld erstellen
====
Wir empfehlen dir, im Vorfeld einen Entwurf zu erstellen, um unübersichtliche Verschachtelungen in deiner Ordnerstruktur zu vermeiden, denn: Je mehr Ebenen du erstellst, desto unübersichtlicher wird die Struktur.
====

[instruction]
Unterordner erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners, für den du einen Unterordner erstellen möchtest, auf das Kontextmenü (icon:ellipsis-v[]). +
→ Ein Fenster wird geöffnet.
. Klicke auf icon:plus[] *Neuer Unterordner*. +
→ Ein Fenster wird geöffnet.
. Gib den Namen für den Unterordner ein.
. *Speichere* die Einstellungen. +
→ Der Unterordner wird erstellt.

Öffne den Unterordner, indem du den Hauptordner mit einem Klick auf icon:angle-right[] öffnest. Du siehst dort auf einen Blick alle erstellten Unterordner.

[#ordner-loeschen]
=== Ordner löschen

Du kannst Ordner und Unterordner jederzeit löschen. Beachte, dass dabei alle Inhalte in dem Ordner, den du löschen möchtest, entfernt werden.

[instruction]
Ordner löschen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners bzw. Unterordners, den du löschen möchtest, auf das Kontextmenü (icon:ellipsis-v[]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicke auf *Löschen*. +
→ Der Ordner wird gelöscht.

[#textbloecke-verwalten]
== Textblöcke verwalten

Der Textblock ist der eigentliche Inhalt deiner E-Mail. In einen Textblock kannst du beliebig viele Variablen per Drag-and-drop einfügen, die dann in der E-Mail an deine Kund:innen durch den korrekten Inhalt ersetzt werden.

Welche Variablen dir für deine E-Mail-Vorlagen zur Verfügung stehen, findest du in den Listen ganz unten auf dieser Seite im Kapitel <<#e-mail-variablen, Verfügbare Variablen für den EmailBuilder>>.

[#textblock-erstellen]
=== Textblock erstellen

// Einleitung

[.instruction]
Textblock erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners bzw. Unterordners, in dem du einen Textblock erstellen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf icon:plus[] *Neuer Textblock*.
. Gib einen Namen für den Textblock ein.
. Klicke auf *Speichern*.
. Klicke auf *Bearbeiten* (icon:pencil[]). +
→ Der Editor öffnet sich.

[#widgets-einfuegen]
=== Widgets in den Textblock einfügen

// hier dann beschreiben, wie man die Widgets einfügt per Drag-and-drop.


[#textblock-bearbeiten]
=== Textblock bearbeiten

Du kannst deine Textblöcke jederzeit bearbeiten. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Textblock bearbeiten:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners bzw. Unterordners, in dem sich der Textblock befindet, den du bearbeiten möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf den Textblock.
. Klicke auf *Bearbeiten* (icon:pencil[]).

// infos ergänzen


// Kapitel ergänzen: "Vorschau anzeigen"

[#textblock-loeschen]
=== Textblock löschen

// Einleitung

. Öffne das Menü *CRM » EmailBuilder*.
. Klappe den Ordner auf (icon:angle-right[]), der den Textblock enthält, den du löschen möchtest.
. Klicke in der Zeile des Textblocks, den du löschen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicke auf *Löschen*. +
→ Der Textblock wird gelöscht.

// 25.03.21: Ist in der UI aktuell noch falsch. Da steht bei der Sicherheitsabfrage "Möchtest du den Ordner mit allen dazugehörigen Unterordnern und Vorlagen wirklich löschen?"

[#vorlagen-verwalten]
== Vorlagen verwalten

In den folgenden Unterkapiteln erfährst du, wie du Vorlagen für <<#header-erstellen, Header>> und <<#footer-erstellen, Footer>> und anschließend <<#vorlage-erstellen, allgemeine Vorlagen>> erstellst.

[#vorlage-header-footer]
=== Vorlagen für Header und Footer erstellen

Erstelle Vorlagen für den Header und den Footer, die du dann in deinen alle E-Mail-Vorlagen wählen kannst. Header und Footer sind global wirksam. Das bedeutet: Änderungen, die du am Header und Footer vornimmst, wirken sich demnach auch auf alle bestehenden Vorlagen sowie weitere Vorlagen, die du zukünftig erstellst, aus.

Es gibt bereits vordefinierte Inhalte, die du nach deinen Wünschen anpassen kannst. Gehe wie im Folgenden beschrieben vor, um Vorlagen für den Header und den Footer zu erstellen.

// stimmt das? vordefiniert?


[#header-erstellen]
==== Vorlage für den Header erstellen

Gehe wie im Folgenden beschrieben vor, um eine Vorlage für den Header zu erstellen.

[instruction]
Vorlage für den Header erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners bzw. Unterordners, in dem du einen Header erstellen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf icon:plus[] *Neuer Header*. +
→ Eine weitere Ansicht öffnet sich.
. Gib einen Namen für den Header ein.
. *Speichere* die Einstellungen.
. Klicke auf *Vorschau*.

// Vorschau funktioniert noch nicht | Nachtrag 25.03.21: Den Button "Vorschau" kann man nun zwar klicken, aber danach geht es aktuell noch nicht weiter. Der Editor lädt nicht. Frage: Wo kann ich den Inhalt des Headers konfigurieren?

[#footer-erstellen]
==== Vorlage für den Footer erstellen

Gehe wie im Folgenden beschrieben vor, um eine Vorlage für den Footer zu erstellen.

[instruction]
Vorlage für den Footer erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners bzw. Unterordners, in dem du einen Footer erstellen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf icon:plus[] *Neuer Footer*. +
→ Eine weitere Ansicht öffnet sich.
. Gib einen Namen für den Footer ein.
. *Speichere* die Einstellungen.
. Klicke auf *Vorschau*.

// Vorschau funktioniert noch nicht | Nachtrag 25.03.21: Den Button "Vorschau" kann man nun zwar klicken, aber danach geht es aktuell noch nicht weiter. Der Editor lädt nicht. Frage: Wo kann ich den Inhalt des Footers konfigurieren?


[#vorlage-erstellen]
=== Vorlage erstellen

// Einleitung

[instruction]
Inhalt der Vorlage erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners, in dem du eine Vorlage erstellen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf icon:plus[] *Neue Vorlage*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-emailbuilder-create-template>>.

// Screenshot einfügen

[[table-emailbuilder-create-template]]
.Vorlage im EmailBuilder erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Speichern*
|Speichert die Einstellungen.

| *Vorschau*
|Zeigt eine Vorschau der Vorlage an. +
Du wählst, ob du die Vorschau im HTML-Format oder im reinen Textformat anzeigen lassen möchtest.
// Je nachdem, welchen Vorschautypen du wählst, öffnet sich ein Fenster mit dem Inhalt der E-Mail-Vorlage mit HTML-Formatierung oder in reinem Textformat.

| *Name*
|Gib einen Name für die Vorlage ein.

| *Header*
|Welchen Header möchtest du in dieser Vorlage anzeigen? Wähle einen Header aus der Dropdown-Liste. +
Die Liste enthält alle <<#header-erstellen, Header>>, die du bereits erstellt hast.

| *Footer*
|Welchen Footer möchtest du in dieser Vorlage anzeigen? Wähle einen Footer aus der Dropdown-Liste. +
Die Liste enthält alle <<#footer-erstellen, Footer>>, die du bereits erstellt hast.

| *Typ*
|In welchem Bereich soll die E-Mail-Vorlage als Auswahl zur Verfügung stehen? Wähle einen Typ aus der Dropdown-Liste.

| *Bearbeiten*
|Klicke auf icon:pencil[], um den Inhalt der Vorlage zu bearbeiten. +
Der Editor-Bereich öffnet sich und du kannst über die Widgets den Inhalt der Vorlage bearbeiten.

| *Betreff*
|Wie lautet der Betreff deiner E-Mail?

| *Von*
|

| *Antwort an*
|An wen soll die E-Mail gesendet werden?

| *CC*
|An wen soll die E-Mail in Kopie gesendet werden? Gib die E-Mail-Adresse(n) ein.

| *BCC*
|An wen soll die E-Mail als blinde Kopie gesendet werden? Gib die E-Mail-Adresse(n) ein.

| *Anhänge*
|Welche Anhänge möchtest du in deiner E-Mail senden? Wähle die Dateien von deinem Computer aus.

|====

[#vorlage-suchen]
=== Vorlage suchen

Die folgende Handlungsanweisung beschreibt, wie du im Allgemeinen nach Vorlagen suchst. Die Vorgehensweise ist demnach identisch für die Suche nach allen Vorlagen, so z.B. auch für die Suche nach deinen Vorlagen, die du für Header und Footer erstellt hast.

[instruction]
Vorlage suchen:

. Öffne das Menü *CRM » EmailBuilder*.
. Wähle die Sprache und/oder den Mandanten aus den Dropdown-Listen. +
→ Die Vorlagen, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke auf die Vorlage, um diese zu öffnen und zu bearbeiten.

[#vorlage-bearbeiten]
=== Vorlage bearbeiten

Die folgende Handlungsanleitung beschreibt, wie du allgemein Vorlagen bearbeitest. Die Vorgehensweise ist demnach identisch für das Bearbeiten aller Vorlagen, so z.B. auch für das Bearbeiten von deinen Vorlagen, die du für Header und Footer erstellt hast.

[instruction]
Vorlage bearbeiten:

. Öffne das Menü *CRM » EmailBuilder*.
. Klappe den Ordner auf (icon:angle-right[]), der die Vorlage enthält, die du bearbeiten möchtest.
. Klicke auf die Vorlage.
. Nimm die Änderungen vor. Beachte dazu auch die Erläuterungen in <<#table-emailbuilder-create-template>>.
. *Speichere* die Einstellungen.

[#vorlage-loeschen]
=== Vorlage löschen

Gehe wie im Folgenden beschrieben vor, um Vorlagen zu löschen.

// Info ergänzen, was genau gelöscht wird. Nur die zusammengesetzte Vorlage, aber Header und Footer nicht und auch nicht der Textblock, richtig?

[instruction]
Vorlage löschen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klappe den Ordner auf (icon:angle-right[]), der die Vorlage enthält, die du löschen möchtest.
. Klicke in der Zeile der Vorlage, die du löschen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicke auf *Löschen*. +
→ Die Vorlage wird gelöscht.


[#e-mail-variablen]
== Verfügbare Variablen für den EmailBuilder

Die verfügbaren Variablen für den EmailBuilder sind in verschiedene Kategorien bzw. Unterkategorien gruppiert:

* Auftrag
** Auftragsvariablen allgemein
** Lieferadresse
** Rechnungsadresse
** Auftragspositionen
** Versand

* Kontakt
** Kontaktvariablen allgemein
** Lieferadresse
** Rechnungsadresse
** Kontaktoptionen

* Globale Variablen

* Newsletter
// * Ticket

Möchtest du wissen, welche Variablen für die einzelnen Kategorien zur Verfügung stehen? Dann klappe die Bereiche mit einem Klick auf icon:angle-down[] einfach auf.







[.collapseBox]
.Kategorie *Auftrag*
--

* Auftrags-ID
* ID des Hauptauftrags
* ID des Elternauftrags
* Statusname
* Status-ID
* Markierung
* Kundenzeichen
* Kontaktperson Rechnungsadresse
// warum bei Order?
* Kontaktperson Lieferadresse
// warum bei Order?
* Anzahl der Aufträge
* Externe Auftrags-ID
* Währung
* Rechnungsadresse USt-IdNr.
* Lieferadresse USt-IdNr.
* Wert der Artikel
* Gesamtrechnungsbetrag
* Gesamtrechnungsbetrag, durch Punkt getrennt
* Gesamtrechnungsbetrag netto
* Gesamtbetrag der Mehrwertsteuer
* Gesamtbetrag des Auftrags netto
* Datum und Uhrzeit des Auftragseingangs
* Datum des Zahlungseingangs
* Zahlungsart
* Zahlungsart-ID
* Herkunft
* Herkunfts-ID
* Bezahlter Betrag
* Offener Betrag
* Überbezahlter Betrag
* Lager-ID
* Mandanten-ID
* Verkäuferkonto
* eBay-Zahlungs-ID
* Barcode-ID
* Kundenwunsch
* Auftragstyp
* Auftrag im Webshop aufrufen
* Nachbestellungs-ID
* Nachbestellung Lieferdatum
* Gutscheinwert
* Rechnungsnummer-ID
* Lieferschein-ID
////
* Abonnements-ID
* Abonnement Startdatum
* Abonnement Enddatum
* Anzahl der Aufträge im Abonnement
* Abonnements-Intervall
* Abonnement Gesamtbetrag
////
--


[.collapseBox]
.Unterkategorie *Auftrag / Lieferadresse*
--

* Lieferadresse Vorname + Nachname
* Lieferadresse Adresszusatz
* Lieferadresse Vorname
* Lieferadresse Nachname
* Lieferadresse Firmenname
* Lieferadresse Telefon
* Lieferadresse Straße
* Lieferadresse Ort + Postleitzahl
* Lieferadresse Ort
* Lieferadresse Postleitzahl
* Lieferadresse Land
* Lieferadresse Länder-ID
* Lieferadresse Länder-ISO-Code 2
* Lieferadresse Länder-ISO-Code 3
* Lieferadresse Region/Bundesland etc.

--





[.collapseBox]
.Unterkategorie *Auftrag / Rechnungsadresse*
--

* Rechnungsadresse Vorname + Nachname
* Rechnungsadresse Adresszusatz
* Rechnungsadresse Vorname
* Rechnungsadresse Nachname
* Rechnungsadresse Firmenname
* Rechnungsadresse Telefon
* Rechnungsadresse Straße
* Rechnungsadresse Ort + Postleitzahl
* Rechnungsadresse Ort
* Rechnungsadresse Postleitzahl
* Rechnungsadresse Land
* Rechnungsadresse Länder-ID
* Rechnungsadresse Länder-ISO-Code 2
* Rechnungsadresse Länder-ISO-Code 3
* Rechnungsadresse Region/Bundesland etc.

--




[.collapseBox]
.Unterkategorie *Auftrag / Auftragspositionen*
--

* Artikel-ID
* Artikeleigenschaften
* Status-ID des retournierten Artikels
* Name des retournierten Artikels
* Variantennummer
* Artikelname
* Artikelmenge
* Bruttopreis
* Nettopreis
* Mehrwertsteuersatz
* Herkunft
* Externe Artikel-ID
* Externe Varianten-ID
* Externe Token-ID
* Inhalt
* Einheit
* Variantenname
* Varianten-ID
* Attributwerte
* Modell
* GTIN
* ISBN
* ASIN
* Verfügbarkeitstext
* Verfügbarkeits-ID
* Verfügbarkeitstext physischer Warenbestand
* Verfügbarkeits-ID physischer Warenbestand
* Freitextfeld
* URL zum Variantenbild
* Herstellername
* Lager-ID
* Retourenkommentar
* Retourenwert in Prozent
* ID des Retourengrunds
* Name des Retourengrunds
* Codes eines Gutscheins
* Zolltarifnummer
* Erscheinungsdatum
* Gesamtpreis (Einzelpreis x Menge)
* Rabatt pro Auftragsposition
* URL zum Artikel

--






[.collapseBox]
.Unterkategorie *Auftrag / Versand*
--

* Mögliches Lieferdatum
* Voraussichtliches Versanddatum
* Datum des Retoureneingangs
* Voraussichtliches Lieferdatum
* Retourenpaketnummer
* Versandkosten gesamt
* Paketnummernliste
** Paketnummern bzw. Tracking-Nummern werden nach erfolgreicher Auftragsanmeldung beim Versanddienstleister im Auftrag im Tab *Einstellungen* gespeichert.
* Tracking-URL
** Dient zur Sendungsverfolgung.
Die URL wird im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versanddienstleister* gespeichert.
* Versanddienstleister
* Versanddienstleister-ID
** Wird automatisch vom System vergeben.
* Versandprofil-ID
** Wird automatisch vom System vergeben.
* Versandprofil
* DHL Retoure Online QR-Code
// erklärung ergänzen

--




[.collapseBox]
.Kategorie *Kontakt*
--

* Kontakt-ID
* Vorname
* Nachname
* Geschlecht
* Anrede
* Firmenname
* Sprache
* Klasse
** Klasse, der der Kontakt zugeordnet ist. Klassen erstellst du im Menü *Einrichtung » CRM » Kundenklassen*.
* Nummer
** Zusätzliche Nummer für den Kontakt
* Titel
* Vorname und Nachname des Systembenutzers
// Erklärung ergänzen
* Signatur des Systembenutzers
// Erklärung ergänzen
* Signatur des Systembenutzers im HTML-Format
// Erklärung ergänzen
* Kontoinhaber
* Bankname
* IBAN
* BIC

////
TODO Event-Variablen verfügbar? Prüfen!
* Event-Typ
* Event-Beschreibung
* Event-Dauer
* Event abgerechnet
* Event nicht abgerechnet
* Event abgerechnet und kostenpflichtig
* Event nicht abgerechnet und kostenpflichtig
* Event abrechenbar
////

* Anmeldung im Forum
// Erklärung ergänzen
* Newsletter-Empfang: Zustimmung durch Kontakt
// Erklärung ergänzen

--




[.collapseBox]
.Unterkategorie *Kontakt / Lieferadresse*
--

* Lieferadresse Vorname + Nachname
* Lieferadresse Adresszusatz
* Lieferadresse Vorname
* Lieferadresse Nachname
* Lieferadresse Firmenname
* Lieferadresse Telefon
* Lieferadresse Straße
* Lieferadresse Ort + Postleitzahl
* Lieferadresse Ort
* Lieferadresse Postleitzahl
* Lieferadresse Land
* Lieferadresse Länder-ID
* Lieferadresse Länder-ISO-Code 2, Lieferadresse Länder-ISO-Code 3
* Lieferadresse Region/Bundesland etc.

--



[.collapseBox]
.Unterkategorie *Kontakt / Rechnungsadresse*
--

* Rechnungsadresse Vorname + Nachname
* Rechnungsadresse Adresszusatz
* Rechnungsadresse Vorname
* Rechnungsadresse Nachname
* Rechnungsadresse Firmenname
* Rechnungsadresse Telefon
* Rechnungsadresse Straße
* Rechnungsadresse Ort + Postleitzahl
* Rechnungsadresse Ort
* Rechnungsadresse Postleitzahl
* Rechnungsadresse Land
* Rechnungsadresse Länder-ID
* Rechnungsadresse Länder-ISO-Code 2, Rechnungsadresse Länder-ISO-Code 3
* Rechnungsadresse Region/Bundesland etc.

--




[.collapseBox]
.Unterkategorie *Kontakt / Optionen*
--

* E-Mail privat
* Telefon privat
* Mobiltelefon privat
* Fax privat
* E-Mail geschäftlich
* Telefon geschäftlich
* Mobiltelefon geschäftlich
* Fax geschäftlich
* eBay-Name des Kontakts
* Anrede privat
* Anrede geschäftlich
* E-Mail PayPal
* Zusätzlicher Ansprechpartner

--




















[.collapseBox]
.Kategorie *Global*
--

* URL zum Checkout
** Gibt die URL zum Checkout-Bereich des Auftrags im Webshop aus

* URL zum Warenkorb
** Gibt die URL zum Warenkorb im Webshop aus

* URL zu den Geschäftsbedingungen
** Gibt die URL zu den AGB aus

* URL zum Webshop
** Gibt die URL zum Webshop aus

* URL zum neuen Passwort
** Gibt die URL zu einem Formular zum Erstellen eines neuen Passworts aus. Dort geben Kund:innen ihre E-Mail-Adresse ein.

* URL zum Ändern des Passworts
** Gibt die URL zum Bereich *Passwort ändern* im Webshop aus. Dort können Kund:innen ein neues Passwort eingeben.

* URL zum Bestätigen der E-Mail-Adresse
// Erklärung ergänzen

* Widerrufsrecht im HTML-Format
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsrecht* und dort im Tab *HTML* gespeichert.

* Widerrufsrecht im reinen Textformat
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsrecht* und dort im Tab *Text* gespeichert.

* Datenschutzerklärung im reinen Textformat
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Datenschutzerklärung* und dort im Tab *Text* gespeichert.

* Datenschutzerklärung im HTML-Format
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Datenschutzerklärung* und dort im Tab *HTML* gespeichert.

* Impressum im reinen Textformat
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Impressum* und dort im Tab *Text* gespeichert.

* Impressum im HTML-Format
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Impressum* und dort im Tab *HTML* gespeichert.

* Widerrufsformular im reinen Textformat
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsformular* und dort im Tab *Text* gespeichert.

* Widerrufsformular im HTML-Format
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsformular* und dort im Tab *HTML* gespeichert.

* Heutiges Datum
** Gibt das heutige Datum aus
// in welchem Format?

* Vorname und Nachname des Kontoinhabers
** Wird im *Basics*-Assistenten im Schritt *Bankdaten* gespeichert. Du findest den Assistenten im Menü *Einrichtung » Assistenten » Grundeinstellungen*.

* Bankname
** Wird im *Basics*-Assistenten im Schritt *Bankdaten* gespeichert. Du findest den Assistenten im Menü *Einrichtung » Assistenten » Grundeinstellungen*.

* IBAN
** Wird im *Basics*-Assistenten im Schritt *Bankdaten* gespeichert. Du findest den Assistenten im Menü *Einrichtung » Assistenten » Grundeinstellungen*.

* BIC
** Wird im *Basics*-Assistenten im Schritt *Bankdaten* gespeichert. Du findest den Assistenten im Menü *Einrichtung » Assistenten » Grundeinstellungen*.

* Signatur im reinen Textformat
** Die Signatur wird im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Signatur* im Bereich *Reine Textsignatur* gespeichert.

* Signatur im HTML-Format
** Die Signatur wird im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Signatur* im Bereich *HTML-Signatur* gespeichert.

* Gutschein-Code (1) bis (10)
** Gutschein-Codes werden in der Kampagne im Menü *Aufträge » Gutscheine* generiert. Ein Gutschein-Code kann immer nur jeweils einer Kampagne zugeordnet werden, um diesen Gutschein-Code aus der Kampagne in der E-Mail-Vorlage zu versenden.

* EORI-Nummer
** Eindeutige Identifizierungsnummer, die für Zollzwecke benötigt wird

--





[.collapseBox]
.Kategorie *Newsletter*
--

* URL zur Bestätigung des Newsletter-Abonnements
// Erklärung ergänzen

--





////

[.collapseBox]
.Kategorie *Ticket*
--

[[table-emailbuilder-variable-list-globals]]
.Verfügbare Variablen für die Kategorie *Ticket*
[cols="1,3"]
|====
|Variable |Erläuterung

|Historie
|Der zuletzt gespeicherte Text im Ticket, d.h. der Text eines Kommentars oder einer Nachricht. +
Damit diese Variable befüllt wird, müssen eine E-Mail-Vorlage und Ereignisaktionen eingerichtet sein. Die Ereignisaktionen müssen auf dem Ereignis *Neuer Kommentar*, *Neue Nachricht vom Mitarbeiter* oder *Neue Nachricht vom Kunden* beruhen. Die Variable wird dann je nach Ereignis befüllt. Bei allen anderen Ereignissen wird die Variable nicht befüllt.


|Letzter Kommentar
|Der zuletzt hinzugefügte Kommentar im Ticket. +
Damit diese Variable befüllt wird, müssen eine E-Mail-Vorlage und eine Ereignisaktion eingerichtet sein. Die Ereignisaktion muss auf dem Ereignis *Neuer Kommentar* beruhen. Bei allen anderen Ereignissen wird die Variable nicht befüllt.

|Letzte Nachricht
|Die zuletzt hinzugefügte Nachricht im Ticket. +
Damit diese Variable befüllt wird, müssen eine E-Mail-Vorlage und eine Ereignisaktion eingerichtet sein. Die Ereignisaktion muss auf einem der beiden Ereignisse *Neue Nachricht vom Mitarbeiter* oder *Neue Nachricht vom Kunden* beruhen. Am besten richtest du eine Ereignisaktion für beide Ereignisse ein und erhältst so eine E-Mail, egal ob deine Mitarbeiter:innen oder deine Kund:innen schreiben. Bei allen anderen Ereignissen wird die Variable nicht befüllt.


|URL
|Verlinkt zum Ticket im Bereich *Mein Konto* des Kontakts in deinem Webshop. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.


|Backend-URL
|Öffnet das Ticket im Backend im Menü *CRM » Ticketsystem*. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.


|Titel
|Betreff des Tickets. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.

|Ticket-ID
|ID des Tickets. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.


|Tags
|Zeigt die mit dem Ticket verknüpften Tags an. +
Die Tags müssen zuvor im Menü *Einrichtung » Einstellungen » Tags* für den Bereich *Ticket* erstellt werden.

|Status
|Status des Tickets. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.


|Priorität
|Priorität des Tickets. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.

|====

--
////
