= EmailBuilder
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:description: Erfahre, wie du den EmailBuilder in plentymarkets verwendest.
:position: 19
:url: crm/emailbuilder
:id:
:author: team-crm

Der EmailBuilder ist ein Baukastenmodul, mit dem du deine E-Mail-Vorlagen schnell und einfach per Drag&Drop erstellen und bearbeiten kannst. Dafür benötigst du keinerlei Programmierungskenntnisse.

Der EmailBuilder besteht aus 2 Ansichten: dem Konfigurationsmanager und dem Editor. Im Konfigurationsmanager erstellst du Ordner, ggf. Unterordner, Basisvorlagen, Vorlagen und Textblöcke. Im Editor befüllst du deine Basisvorlagen, Vorlagen und Textblöcke mit Inhalt. Du kannst zum Beispiel eine Vorlage für eine Rechnung erstellen und diese zukünftig für alle Rechnungen an deine Kund:innen verwenden.

//Konfigurationsmanager? Oder Content-Manager?

Über die sogenannte *Basisvorlage* erstellst du den Header und den Footer für die Vorlage, die dann für alle E-Mail-Vorlagen verwendet wird. Header und Footer sind global wirksam; Änderungen, die du am Header und Footer vornimmst, wirken sich demnach auch auf alle bestehenden Vorlagen sowie weitere Vorlagen, die du zukünftig erstellst, aus.

// Screenshot einfügen
// Icons einfügen

[#ordner-verwalten]
== Ordner verwalten

Du kannst beliebig viele Ordner und Unterordner erstellen. Nachdem der Ordner erstellt ist, kannst du über das Kontextmenü (Dreipunkt-Menü) eine neue Vorlage und einen neuen Textblock erstellen.

Mit der Vorlage erstellst du sozusagen das Gerüst deiner E-Mail, also den Header und den Footer. (Screenshot einfügen). Der Textblock ist der eigentliche Inhalt deiner E-Mail.

//Vorlage = Gerüst mit Header und Footer
//Textblock = Inhalt der E-Mail

[#ordner-erstellen]
=== Ordner erstellen

Erstelle Ordner, um später eine bessere Übersicht für deine E-Mail-Vorlagen zu bekommen. Gehe wie im Folgenden beschrieben vor, um einen neuen Ordner zu erstellen.

[instruction]
Ordner erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke auf *Neuer Basisordner* (Plus-Zeichen). +
→ Ein Fenster wird geöffnet.
. Gib den Namen für den Ordner ein.
. *Speichere* die Einstellungen. +
→ Der neue Ordner wird der Ordnerliste ganz unten hinzugefügt.

[#ordername-aktualisieren]
=== Ordnernamen aktualisieren

Du kannst den Namen des Ordners jederzeit anpassen. Gehe dazu wie im Folgenden beschrieben vor.

[instruction]
Ordnernamen aktualisieren:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke auf den Ordner, den du bearbeiten möchtest. +
→ Ein Fenster wird geöffnet.
. Gib einen anderen Namen für den Ordner ein.
. Klicke auf *Aktualisieren*. +
→ Der neue Name des Ordners wird aktualisiert und in der Liste angezeigt.

[#unterordner-erstellen]
=== Unterordner erstellen

Erstelle Unterordner in deinen Ordnern, um deine E-Mail-Vorlagen später noch differenzierter zu gruppieren. Du kannst beliebig viele Unterordner erstellen. Auch die Anzahl der Ebenen ist unbegrenzt.

[TIP]
.Entwurf für deine Ordner-Struktur im Vorfeld erstellen
====
Wir empfehlen dir, im Vorfeld einen Entwurf zu erstellen, um unübersichtliche Verschachtelungen in deiner Ordnerstruktur zu vermeiden, denn: Je mehr Ebenen du erstellst, desto unübersichtlicher wird die Struktur.
====

[instruction]
Unterordner erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners, für den du einen Unterordner erstellen möchtest, auf das Kontextmenü (Dreipunkte-Menü). +
→ Ein Fenster wird geöffnet.
. Klicke auf *+ Neuer Ordner*. +
→ Ein Fenster wird geöffnet.
. Gib den Namen für den Unterordner ein.
. *Speichere* die Einstellungen. +
→ Der Unterordner wird erstellt.

Öffne den Unterordner, indem du den Hauptordner mit einem Klick auf den Pfeil ( > ) ganz links öffnest. Du siehst dort auf einen Blick alle erstellten Unterordner.

[#ordner-loeschen]
=== Ordner löschen

Du kannst Ordner und Unterordner jederzeit löschen. Beachte, dass dabei alle Inhalte in dem Ordner, den du löschen möchtest, entfernt werden.

[instruction]
Ordner löschen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners bzw. Unterordners, den du löschen möchtest, auf das Kontextmenü (Dreipunkte-Menü). +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicke auf *Löschen*. +
→ Der Ordner wird gelöscht.

[#textblock-erstellen]
== Textblock erstellen

Text

[#vorlagen-verwalten]
== Vorlagen verwalten

Text

[#basisvorlage-erstellen]
=== Basisvorlage erstellen

Über die sogenannte Basisvorlage erstellst du den Header und den Footer für die Vorlage, die dann für alle E-Mail-Vorlagen verwendet wird. Header und Footer sind global wirksam; Änderungen, die du am Header und Footer vornimmst, wirken sich demnach auch auf alle bestehenden Vorlagen sowie weitere Vorlagen, die du zukünftig erstellst, aus.

Es gibt bereits vordefinierte Inhalte, die du nach deinen Wünschen anpassen kannst.

[instruction]
Basisvorlage erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners bzw. Unterordners, in dem du eine Basisvorlage erstellen möchtest, auf das Kontextmenü (Dreipunkt-Menü).
. Klicke auf *+ Neue Basis-Vorlage*.

[#vorlage-erstellen]
=== Vorlage erstellen

Text

[instruction]
Inhalt der Vorlage erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners, in dem du eine Vorlage erstellen möchtest, auf das Kontextmenü (Dreipunkt-Menü).
. Klicke auf *+ Neue Vorlage*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-emailbuilder-create-template>>.

// Screenshot einfügen

[[table-emailbuilder-create-template]]
.Vorlage im EmailBuilder erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Speichern*
|Speichert die Einstellungen.

| *Name*
|Name für die Vorlage eingeben.

| *Basisvorlage*
|Basisvorlage aus der Dropdown-Liste wählen. Die Liste enthält <<basisvorlage-erstellen#, alle Basisvorlagen, die du bereits erstellt hast>>.

| *Bearbeiten*
|

| *Betreff*
|Betreff deiner E-Mail eingeben.

| *Von*
|

| *Antwort an*
|

| *CC*
|

| *BCC*
|

| *Anhänge*
|

|====

[#vorlage-suchen]
=== Vorlage suchen

Die folgende Handlungsanweisung beschreibt, wie du allgemein Vorlagen suchst. Die Vorgehensweise ist demnach identisch für die Suche nach Vorlagen und Basisvorlagen.

[instruction]
Vorlage suchen:

. Öffne das Menü *CRM » EmailBuilder*.
. Wähle die Sprache und/oder den Mandanten aus den Dropdown-Listen. +
→ Die Vorlagen, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke auf die Vorlage, um diese zu öffnen und zu bearbeiten.

[#vorlage-bearbeiten]
=== Vorlage bearbeiten

Die folgende Handlungsanleitung beschreibt, wie du allgemein Vorlagen bearbeitest. Die Vorgehensweise ist demnach identisch für das Bearbeiten von Vorlagen und Basisvorlagen.

[instruction]
Vorlage bearbeiten:

. Öffne das Menü *CRM » EmailBuilder*.
. Klappe den Ordner auf (Pfeil-Icon), der die Vorlage enthält, die du bearbeiten möchtest.
. Klicke auf die Vorlage.
. Nimm die Änderungen vor. Beachte dazu auch die Erläuterungen in <<#table-emailbuilder-create-template>>.
. *Speichere* die Einstellungen.

[#vorlage-loeschen]
=== Vorlage löschen

Text

[instruction]
Vorlage löschen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klappe den Ordner auf (Pfeil-Icon), der die Vorlage enthält, die du löschen möchtest.
. Klicke in der Zeile der Vorlage, die du löschen möchtest, auf das Kontextmenü (Dreipunkte-Menü).
. Klicke auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicke auf *Löschen*. +
→ Die Vorlage wird gelöscht.

[#e-mail-variablen]
== Verfügbare Variablen für den EmailBuilder

Die verfügbaren Variablen für den EmailBuilder sind in verschiedene Kategorien gruppiert:

* Kontakt
* Adresse
* Auftrag
** Versand
** Kontakt
* Artikelliste
* Globale Variablen
* Ticket

Die folgenden Tabellen listen diese Variablen mit einer Erläuterung auf.


[[table-emailbuilder-variable-list-contact]]
.Vorlage im EmailBuilder erstellen
[cols="1,3,3"]
|====
|Objekt |Variable |Erläuterung

|contact.id
|Kontakt-ID
|

|contact.privateEmail
|E-Mail privat
|

|contact.privatePhone
|Telefon privat
|

|contact.privateMobile
|Mobiltelefon privat
|

|contact.privateFax
|Fax privat
|

|contact.businessEmail
|E-Mail geschäftlich
|

|contact.businessPhone
|Telefon geschäftlich
|

|contact.businessMobile
|Mobiltelefon geschäftlich
|

|contact.businessFax
|Fax geschäftlich
|

|contact.ebayName
|eBay-Name des Kontakts
|

|contact.newsletterAllowanceAt
|
|

|====
