= EmailBuilder (Vorschau)
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:description: Erfahre, wie du den EmailBuilder in plentymarkets verwendest.
:position: 19
:url: crm/emailbuilder
:id: MYFLVYO
:author: team-crm

[IMPORTANT]
.EmailBuilder wird kontinuierlich weiterentwickelt
====
Auf dieser Seite stellen wir dir die Funktionen des neuen EmailBuilder vor. Der EmailBuilder wird kontinuierlich weiterentwickelt und um weitere Funktionen und Features ergänzt. Natürlich werden in diesem Zuge auch die Beschreibungen auf dieser Handbuchseite nach und nach erweitert.
====

Der EmailBuilder ist ein Baukastenmodul, mit dem du deine E-Mail-Vorlagen schnell und einfach per Drag-and-drop erstellen und bearbeiten kannst. Dafür benötigst du keinerlei Programmierungskenntnisse.

Der EmailBuilder besteht aus 2 Ansichten: dem Konfigurationsmanager und dem Editor. Im Konfigurationsmanager erstellst du Ordner, ggf. Unterordner, Textblöcke, Vorlagen sowie Vorlagen für deinen Footer und deinen Header. Im Editor befüllst du deine Vorlagen, Textblöcke, Header und Footer mit Inhalt. Du kannst zum Beispiel eine Vorlage für eine Rechnung erstellen und diese zukünftig für alle Rechnungen an deine Kund:innen verwenden. +
Die Header- und Footer-Vorlagen kannst du dann beliebig in deinen E-Mail-Vorlagen verwenden. Header und Footer sind global wirksam; Änderungen, die du am Header und Footer vornimmst, wirken sich demnach auch auf alle bestehenden Vorlagen sowie weitere Vorlagen, die du zukünftig erstellst, aus.


// Screenshot einfügen

[#ordner-verwalten]
== Ordner verwalten

Du kannst beliebig viele Ordner und Unterordner erstellen. Nachdem der Ordner erstellt ist, kannst du über das Kontextmenü (icon:ellipsis-v[]) neue Unterordner, neue Textblöcke, neue Vorlagen und neue Vorlagen für Header und Footer erstellen.

Mit dem Header und dem Footer erstellst du sozusagen das Gerüst deiner E-Mail. Der Textblock bildet den eigentlichen Inhalt deiner E-Mail.

// (Screenshot einfügen)



[#ordner-erstellen]
=== Ordner erstellen

Erstelle Ordner, um später eine bessere Übersicht über deine E-Mail-Vorlagen zu bekommen. Gehe wie im Folgenden beschrieben vor, um einen neuen Ordner zu erstellen.

[.instruction]
Ordner erstellen:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klicke auf icon:plus[role="green"] *Neuer Hauptordner*. +
→ Das Fenster *Neuer Ordner erstellen* wird geöffnet.
. Gib den Namen für den Ordner ein.
. Klicke auf *Speichern*. +
→ Der neue Ordner wird der Ordnerliste hinzugefügt.

[TIP]
Wenn du alle Einstellungen wie im Folgenden beschrieben vorgenommen hast – also Unterordner, Textblöcke, Vorlagen, Header und Footer erstellt hast –, kannst du den Hauptordner mit einem Klick auf icon:angle-right[] öffnen. Dort siehst du dann auf einen Blick alle Unterordner, Textblöcke, Vorlagen, Header und Footer, die du direkt unter dem Hauptordner erstellt hast.

[#ordername-aktualisieren]
=== Ordnernamen aktualisieren

Du kannst den Namen des Ordners jederzeit anpassen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Ordnernamen aktualisieren:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klicke auf den Ordner, den du bearbeiten möchtest. +
→ Das Fenster *Ordner aktualisieren* wird geöffnet.
. Gib einen anderen Namen für den Ordner ein.
. Klicke auf *Aktualisieren*. +
→ Der neue Name des Ordners wird aktualisiert und in der Liste angezeigt.

// das wird angepasst. "Bearbeiten"-Button kommt zukünftig in das Kontextmenü.

[#unterordner-erstellen]
=== Unterordner erstellen

Erstelle Unterordner in deinen Ordnern, um deine E-Mail-Vorlagen später noch differenzierter zu gruppieren. Du kannst beliebig viele Unterordner erstellen. Auch die Anzahl der Ebenen ist unbegrenzt.

[TIP]
.Entwurf für deine Ordner-Struktur im Vorfeld erstellen
====
Wir empfehlen dir, im Vorfeld einen Entwurf zu erstellen, um unübersichtliche Verschachtelungen in deiner Ordnerstruktur zu vermeiden, denn: Je mehr Ebenen du erstellst, desto unübersichtlicher wird die Struktur.
====

[.instruction]
Unterordner erstellen:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klicke in der Zeile des Ordners, für den du einen Unterordner erstellen möchtest, auf das Kontextmenü (icon:ellipsis-v[]). +
// später alle "icon:ellipsis-v[]" ersetzen durch "icon:more-vert[set-material]"
→ Ein Fenster wird geöffnet.
. Klicke auf icon:plus[] *Neuer Unterordner*. +
→ Das Fenster *Neuen Ordner erstellen* wird geöffnet.
. Gib den Namen für den Unterordner ein.
. Klicke auf *Speichern*. +
→ Der Unterordner wird erstellt.

Öffne den Unterordner, indem du den Hauptordner mit einem Klick auf icon:angle-right[] öffnest. Du siehst dort auf einen Blick alle erstellten Unterordner.

[#ordner-loeschen]
=== Ordner löschen

Du kannst Ordner und Unterordner jederzeit löschen. Beachte, dass dabei alle Inhalte in dem Ordner, den du löschen möchtest, entfernt werden.

[.instruction]
Ordner löschen:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klicke in der Zeile des Ordners bzw. Unterordners, den du löschen möchtest, auf das Kontextmenü (icon:ellipsis-v[]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicke auf *Löschen*. +
→ Der Ordner wird gelöscht.

[#textbloecke-verwalten]
== Textblöcke verwalten

Der Textblock ist der eigentliche Inhalt deiner E-Mail. In einen Textblock kannst du über die verfügbaren Widgets beliebig viele Variablen per Drag-and-drop einfügen, die dann in der E-Mail an deine Kund:innen durch den korrekten Inhalt ersetzt werden.

Welche Variablen dir für deine E-Mail-Vorlagen zur Verfügung stehen, findest du in den Listen ganz unten auf dieser Seite im Kapitel <<#e-mail-variablen, Verfügbare Variablen für den EmailBuilder>>.

[#textblock-erstellen]
=== Textblock erstellen

Gehe wie im Folgenden beschrieben vor, um einen Textblock – also den eigentlichen Inhalt deiner E-Mail – zu erstellen.

[.instruction]
Textblock erstellen:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klicke in der Zeile des Ordners bzw. Unterordners, in dem du einen Textblock erstellen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf icon:plus[] *Neuer Textblock*.
. Gib einen Namen für den Textblock ein.
. Klicke auf *Speichern* (icon:save[]).
. Klicke auf *Bearbeiten* (icon:pencil[]). +
→ Der Editor öffnet sich.

Gestalte nun den Inhalt deiner E-Mail, indem du über die Widgets Variablen in den Textblock einfügst. Wie du dazu vorgehst, ist im folgenden Kapitel <<widget-einfuegen#, Widget in den Textblock einfügen>> beschrieben.

[#widget-einfuegen]
=== Widget in den Textblock einfügen

Im Editor findest du eine Auswahl an Widgets, deren Inhalte bereits für dich vorkonfiguriert sind. Du kannst die Inhalte jedoch jederzeit nach deinen Wünschen anpassen. Beispielsweise findest du im Widget *Auftragspositionen* eine vordefinierte Liste mit den wichtigsten Variablen rund um den bestellten Artikel.

<<#table-available-widgets-emailbuilder>> listet die im EmailBuilder verfügbaren Widgets auf.


[[table-available-widgets-emailbuilder]]
.Im EmailBuilder verfügbare Widgets
[cols="1,3"]
|====
|Widget |Erläuterung

| *Zweispaltiges Layout*
a|Ermöglicht die Darstellung von Text in einem zweispaltigen Layout. Mit einem Klick auf icon:cog[role="darkGrey"] öffnen sich die Einstellungen. Hier kannst du das Verhältnis, wie die beiden Spalten angezeigt werden, bestimmen. Zur Auswahl stehen die folgenden Werte:

* 50% / 50% (Standard)
* 30% / 70%
* 70% / 30%

Klicke auf *Einstellungen schließen* (icon:times[]), um die Einstellungen zu schließen. Klicke auf *Widget löschen* (icon:trash[set=plenty]), um das Widget zu entfernen.


| *Text*
|In diesem Widget kannst du Text eingeben und Variablen verwenden.

Mit einem Klick auf icon:pencil[] öffnet sich auf der linken Seite die Liste mit den Variablen. Nutze die Suchfunktion, um nach einzelnen Variablen zu suchen oder finde die passenden Variablen, indem du die einzelnen Bereiche aufklappst (icon:angle-right[]). Klicke auf die Variable, die du einfügen möchtest. Gib ggf. zusätzlich Text in das Widget ein.

Mit einem Klick auf icon:cog[role="darkGrey"] öffnen sich die Einstellungen. Hier kannst du das Widget mit einem Klick auf *Widget löschen* (icon:trash[set=plenty]) entfernen. Weitere Einstellungen können hier nicht vorgenommen werden. Klicke auf *Einstellungen schließen* (icon:times[]), um die Einstellungen zu schließen.



| *Code*
|In diesem Widget kannst du Text im HTML-Format eingeben.

Klicke auf icon:code[role="dark-grey"], um die Ansicht zu öffnen.

Mit einem Klick auf icon:cog[role="darkGrey"] öffnen sich die Einstellungen. Hier kannst du das Widget mit einem Klick auf *Widget löschen* (icon:trash[set=plenty]) entfernen. Weitere Einstellungen können hier nicht vorgenommen werden. Klicke auf *Einstellungen schließen* (icon:times[]), um die Einstellungen zu schließen.

| *Kontaktadresse*
|Dieses Widget enthält Musterdaten der Kontaktadresse.

// Wie im Menü CRM - Adress-Layout hinterlegt?
// wie passe ich die Musterdaten an? Muss ich sie überhaupt anpassen? Oder ist es so wie bei den Auftragspositionen, dass das dann richtig in der E-Mail angezeigt wird?


Mit einem Klick auf icon:cog[role="darkGrey"] öffnen sich die Einstellungen. Wähle aus der Dropdown-Liste den Adresstyp *Rechnungsadresse* oder *Lieferadresse*.



Klicke auf *Einstellungen schließen* (icon:times[]), um die Einstellungen zu schließen. Klicke auf *Widget löschen* (icon:trash[set=plenty]), um das Widget zu entfernen.

| *Auftragsadresse*
|Dieses Widget enthält Musterdaten der Auftragsadresse.

// Wie im Menü CRM - Adress-Layout hinterlegt?
// wie passe ich die Musterdaten an? Muss ich sie überhaupt anpassen? Oder ist es so wie bei den Auftragspositionen, dass das dann richtig in der E-Mail angezeigt wird?

Mit einem Klick auf icon:cog[role="darkGrey"] öffnen sich die Einstellungen. Wähle aus der Dropdown-Liste den Adresstyp *Rechnungsadresse* oder *Lieferadresse*.

Klicke auf *Einstellungen schließen* (icon:times[]), um die Einstellungen zu schließen. Klicke auf *Widget löschen* (icon:trash[set=plenty]), um das Widget zu entfernen.

| *Auftragspositionen*
|Dieses Widget enthält bereits ein vordefiniertes Layout für die Auftragspositionen mit Musterdaten. Die Musterdaten werden dann in der E-Mail durch die korrekten Werte ausgegeben.

Mit einem Klick auf icon:cog[role="darkGrey"] öffnen sich die Einstellungen. Hier kannst du aus den Dropdown-Listen wählen, welche Inhalte angezeigt werden sollen.

| *Artikelliste*
|In diesem Widget kannst du Text eingeben und Variablen verwenden.

Mit einem Klick auf icon:pencil[] öffnet sich auf der linken Seite die Liste mit den Variablen. Nutze die Suchfunktion, um nach einzelnen Variablen zu suchen oder finde die passenden Variablen, indem du die einzelnen Bereiche aufklappst (icon:angle-right[]). Klicke auf die Variable, die du einfügen möchtest. Gib ggf. zusätzlich Text in das Widget ein.

Mit einem Klick auf icon:cog[role="darkGrey"] öffnen sich die Einstellungen. Hier kannst du das Widget mit einem Klick auf *Widget löschen* (icon:trash[set=plenty]) entfernen. Weitere Einstellungen können hier nicht vorgenommen werden. Klicke auf *Einstellungen schließen* (icon:times[]), um die Einstellungen zu schließen.

// was ist von den Funktionen her der Unterschied zwischen den Widgets "Artikelliste" und "Text"?


|====



Gehe wie im Folgenden beschrieben vor, um ein Widget in den Textblock einzufügen.

[.instruction]
Widget in den Textblock einfügen:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klappe den Ordner auf (icon:angle-right[]), der den Textblock enthält, den du bearbeiten möchtest.
. Klicke auf den Textblock.
. Klicke auf *Bearbeiten* (icon:pencil[]). +
→ Der Editor öffnet sich und die Widgets werden geladen.
. Klicke auf das Widget auf der linken Seite, das du einbinden möchtest, und ziehe es via Drag-and-drop in den schraffierten Bereich.
. *Speichere* (icon:save[]) die Einstellungen.

[#textblock-vorschau-anzeigen]
=== Vorschau anzeigen

Prüfe die E-Mail-Vorlage, indem du die Vorschau öffnest.

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klappe den Ordner auf (icon:angle-right[]), der den Textblock enthält, von dem du eine Vorschau anzeigen möchtest.
. Klicke auf den Textblock.
. Klicke auf *Vorschau* .
// Icon einfügen für Vorschau: "(icon:preview[set=material])" / muss erst hinzugefügt werden
. Wähle *Vorschau HTML* oder *Vorschau reiner Text*. +
→ Die Vorschau wird in einem separaten Fenster geöffnet.
. Schließe das Fenster mit einem Klick auf *Schließen*.

Wenn du mit dem Ergebnis nicht zufrieden bist, <<#textblock-bearbeiten, bearbeite>> den Inhalt deiner Vorlage wie im folgenden Kapitel beschrieben.

[#textblock-bearbeiten]
=== Textblock und Widget bearbeiten

Du kannst deine Textblöcke und die Inhalte der Widgets jederzeit bearbeiten. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Textblock und Widget bearbeiten:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klappe den Ordner auf (icon:angle-right[]), der den Textblock enthält, den du bearbeiten möchtest.
. Klicke auf den Textblock.
. Klicke auf *Bearbeiten* (icon:pencil[]). +
→ Der Editor öffnet sich und die Widgets werden geladen.
. Klicke auf icon:cog[role="darkGrey"] *Einstellungen*. +
→ Die Widget-Einstellungen werden – sofern vorhanden – geöffnet.
. Klicke auf icon:pencil[] – sofern vorhanden. +
→ Auf der linken Seite öffnen sich die Variablen.
. Nutze die Suchfunktion, um nach einzelnen Variablen zu suchen oder finde die passenden Variablen, indem du die einzelnen Bereiche aufklappst (icon:angle-right[]).
. Klicke auf die Variable, die du in dem Widget anzeigen möchtest.
. *Speichere* die Einstellungen.



[#textblock-loeschen]
=== Textblock löschen

Gehe wie im Folgenden beschrieben vor, um einen Textblock zu löschen.

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klappe den Ordner auf (icon:angle-right[]), der den Textblock enthält, den du löschen möchtest.
. Klicke in der Zeile des Textblocks, den du löschen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicke auf *Löschen*. +
→ Der Textblock wird gelöscht.

[#vorlagen-verwalten]
== Vorlagen verwalten

In den folgenden Unterkapiteln erfährst du, wie du Vorlagen für <<#header-erstellen, Header>> und <<#footer-erstellen, Footer>> und anschließend <<#vorlage-erstellen, allgemeine Vorlagen>> erstellst.

[#vorlage-header-footer]
=== Vorlagen für Header und Footer erstellen

Erstelle Vorlagen für den Header und den Footer, die du dann in deinen alle E-Mail-Vorlagen wählen kannst. Header und Footer sind global wirksam. Das bedeutet: Änderungen, die du am Header und Footer vornimmst, wirken sich demnach auch auf alle bestehenden Vorlagen sowie weitere Vorlagen, die du zukünftig erstellst, aus.

Es gibt bereits vordefinierte Inhalte, die du nach deinen Wünschen anpassen kannst. Gehe wie im Folgenden beschrieben vor, um Vorlagen für den Header und den Footer zu erstellen.

// stimmt das? vordefiniert?


[#header-erstellen]
==== Vorlage für den Header erstellen

Gehe wie im Folgenden beschrieben vor, um eine Vorlage für den Header deiner E-Mail-Vorlage zu erstellen.

[.instruction]
Vorlage für den Header erstellen:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klicke in der Zeile des Ordners bzw. Unterordners, in dem du einen Header erstellen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf icon:plus[] *Neuer Header*.
. Gib einen Namen für den Header ein.
. *Speichere* (icon:save[]) die Einstellungen.
. Klicke auf *Bearbeiten* (icon:pencil[]).
. Bearbeite den Header nach deinen Wünschen.
. *Speichere* die Einstellungen.


[#footer-erstellen]
==== Vorlage für den Footer erstellen

Gehe wie im Folgenden beschrieben vor, um eine Vorlage für den Footer deiner E-Mail-Vorlage zu erstellen.

[.instruction]
Vorlage für den Footer erstellen:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klicke in der Zeile des Ordners bzw. Unterordners, in dem du einen Footer erstellen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf icon:plus[] *Neuer Footer*. +
→ Eine weitere Ansicht öffnet sich.
. Gib einen Namen für den Footer ein.
. *Speichere* (icon:save[]) die Einstellungen.
. Klicke auf *Bearbeiten* (icon:pencil[]).
. Bearbeite den Footer nach deinen Wünschen.
. *Speichere* die Einstellungen.




[#vorlage-erstellen]
=== Vorlage erstellen

Gehe wie im Folgenden beschrieben vor, um eine Vorlage zu erstellen.

[.instruction]
Inhalt der Vorlage erstellen:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klicke in der Zeile des Ordners, in dem du eine Vorlage erstellen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf icon:plus[] *Neue Vorlage*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-emailbuilder-create-template>>.

// Screenshot einfügen

[[table-emailbuilder-create-template]]
.Vorlage im EmailBuilder erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Speichern*
|Speichert die Einstellungen.

| *Vorschau*
|Zeigt eine Vorschau der Vorlage an. +
Wähle, ob du die Vorschau im HTML-Format oder im reinen Textformat anzeigen lassen möchtest.
Je nachdem, welchen Vorschautypen du wählst, öffnet sich ein Fenster mit dem Inhalt der E-Mail-Vorlage im HTML-Format oder in reinem Textformat.

| *Name*
|Wie lautet der Name der Vorlage? Gib einen aussagekräftigen Namen ein, damit du die Vorlage später leicht wiederfinden kannst.

| *Header*
|Welchen Header möchtest du in dieser Vorlage anzeigen? Wähle einen Header aus der Dropdown-Liste. +
Die Liste enthält alle <<#header-erstellen, Header>>, die du bereits erstellt hast.

| *Footer*
|Welchen Footer möchtest du in dieser Vorlage anzeigen? Wähle einen Footer aus der Dropdown-Liste. +
Die Liste enthält alle <<#footer-erstellen, Footer>>, die du bereits erstellt hast.

//| *Typ*
//|In welchem Bereich soll die E-Mail-Vorlage als Auswahl zur Verfügung stehen? Wähle einen Typ aus der Dropdown-Liste.

| *Bearbeiten*
|Klicke auf icon:pencil[], um den Inhalt der Vorlage zu bearbeiten. +
Der Editor-Bereich öffnet sich und du kannst über die Widgets den Inhalt der Vorlage bearbeiten.

| *Betreff*
|Wie lautet der Betreff deiner E-Mail?

//| *Von*
//|

| *Antwort an*
|An wen soll die E-Mail gesendet werden? Gib die E-Mail-Adresse(n) ein. +
*_Hinweis:_* Wenn du mehrere E-Mail-Adressen eingibst, trenne diese jeweils durch ein Komma.

| *CC*
|An wen soll die E-Mail in Kopie gesendet werden? Gib die E-Mail-Adresse(n) ein. +
*_Hinweis:_* Wenn du mehrere E-Mail-Adressen eingibst, trenne diese jeweils durch ein Komma.

| *BCC*
|An wen soll die E-Mail als blinde Kopie gesendet werden? Gib die E-Mail-Adresse(n) ein. +
*_Hinweis:_* Wenn du mehrere E-Mail-Adressen eingibst, trenne diese jeweils durch ein Komma.

//| *Anhänge*
//|Welche Anhänge möchtest du in deiner E-Mail senden? Wähle die Dateien von deinem Computer aus.

|====

[#vorlage-suchen]
=== Vorlage suchen

Die folgende Handlungsanweisung beschreibt, wie du im Allgemeinen nach Vorlagen suchst. Die Vorgehensweise ist demnach identisch für die Suche nach allen Vorlagen, so z.B. auch für die Suche nach deinen Vorlagen, die du für Header und Footer erstellt hast.

[.instruction]
Vorlage suchen:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Wähle die Sprache und/oder den Mandanten aus den Dropdown-Listen. +
→ Die Vorlagen, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke auf die Vorlage, um diese zu öffnen und zu bearbeiten.

[#vorlage-vorschau-anzeigen]
=== Vorschau anzeigen

Prüfe die Vorlage, indem du die Vorschau öffnest.

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klappe den Ordner auf (icon:angle-right[]), der die Vorlage enthält, von der du eine Vorschau anzeigen möchtest.
. Klicke auf die Vorlage.
. Klicke auf *Vorschau* .
// Icon einfügen für Vorschau: "(icon:preview[set=material])" / muss erst hinzugefügt werden
. Wähle *Vorschau HTML* oder *Vorschau reiner Text*. +
→ Die Vorschau wird in einem separaten Fenster geöffnet.
. Schließe das Fenster mit einem Klick auf *Schließen*.

Wenn du mit dem Ergebnis nicht zufrieden bist, <<#vorlage-bearbeiten, bearbeite>> deine Vorlage wie im folgenden Kapitel beschrieben.

[#vorlage-bearbeiten]
=== Vorlage bearbeiten

Die folgende Handlungsanleitung beschreibt, wie du allgemein Vorlagen bearbeitest. Die Vorgehensweise ist demnach identisch für das Bearbeiten aller Vorlagen, so z.B. auch für das Bearbeiten von deinen Vorlagen, die du für Header und Footer erstellt hast.

[.instruction]
Vorlage bearbeiten:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klappe den Ordner auf (icon:angle-right[]), der die Vorlage enthält, die du bearbeiten möchtest.
. Klicke auf die Vorlage.
. Nimm die Änderungen vor. Beachte dazu auch die Erläuterungen in <<#table-emailbuilder-create-template>>.
. *Speichere* (icon:save[]) die Einstellungen.

[#vorlage-loeschen]
=== Vorlage löschen

Gehe wie im Folgenden beschrieben vor, um Vorlagen zu löschen. Nur die zusammengesetzte Vorlage wird gelöscht, aber _nicht_ die darin enthaltenen Komponenten wie Header und Footer oder Textblock.

[.instruction]
Vorlage löschen:

. Öffne das Menü *CRM » EmailBuilder (Vorschau)*.
. Klappe den Ordner auf (icon:angle-right[]), der die Vorlage enthält, die du löschen möchtest.
. Klicke in der Zeile der Vorlage, die du löschen möchtest, auf das Kontextmenü (icon:ellipsis-v[]).
. Klicke auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicke auf *Löschen*. +
→ Die Vorlage wird gelöscht.


[#e-mail-variablen]
== Verfügbare Variablen für den EmailBuilder

Die verfügbaren Variablen für den EmailBuilder sind in verschiedene Kategorien bzw. Unterkategorien gruppiert:

* Auftrag

** Auftragsvariablen allgemein
** Lieferadresse
** Rechnungsadresse
** Auftragspositionen
** Versand

* Kontakt

** Kontaktvariablen allgemein
** Lieferadresse
** Rechnungsadresse
** Optionen

* Global

* Newsletter


Möchtest du wissen, welche Variablen für die einzelnen Kategorien zur Verfügung stehen? Dann klappe die Bereiche mit einem Klick auf icon:angle-down[] einfach auf.



[.collapseBox]
.Variablen in der Kategorie *Auftrag*
--

* Auftrags-ID

* ID des Hauptauftrags
** ID des obersten Vorgängerauftrags. Dies ist in der Regel ein normaler Auftrag. +
*_Beispiel:_* Bei einer Gutschrift G1 aus einer Retoure R1 aus einem Auftrag A1 gibt die Variable `ID des Elternauftrags` die ID von R1 und `ID des Hauptauftrags` die ID von A1 aus.

* ID des Elternauftrags
** ID des direkten Vorgängerauftrags +
*_Beispiel:_* Bei einer Gutschrift kann es die ID der Retoure oder des Auftrags sein, aus dem die Gutschrift erzeugt wurde.

* Status
** Name des Auftragsstatus wie im Menü *Einrichtung » Aufträge » Status* gespeichert.

* Status-ID
** ID des Auftragsstatus wie im Menü *Einrichtung » Aufträge » Status* gespeichert.

* Markierung
* Kundenzeichen
* Externe Auftrags-ID
* Währung
* Rechnungsadresse USt-IdNr.
* Lieferadresse USt-IdNr.
* Wert des Artikels
* Gesamtrechnungsbetrag
* Gesamtrechnungsbetrag, durch Punkt getrennt
* Gesamtrechnungsbetrag netto
* Gesamtbetrag der Mehrwertsteuer
* Gesamtbetrag des Auftrags netto
* Datum und Uhrzeit des Auftragseingangs
* Datum des Zahlungseingangs

* Zahlungsart
** Name der Zahlungsart wie im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* gespeichert.

* Zahlungsart-ID
** Die ID wird vom System vergeben. Die IDs sind im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* aufgeführt.

* Herkunft
** Name der Auftragsherkunft wie im Menü *Einrichtung » Aufträge » Auftragsherkunft* gespeichert.

* Herkunfts-ID
** ID der Auftragsherkunft wie im Menü *Einrichtung » Aufträge » Auftragsherkunft* gespeichert.

* Bezahlter Betrag
* Offener Betrag
* Überbezahlter Betrag
* Auftrag Lager-ID

* Mandanten-ID
** Die ID wird vom System vergeben und kann nicht geändert werden. Du findest die ID im Menü *Einrichtung » Mandant » [Mandant wählen] » Einstellungen*.

* Verkäuferkonto
* eBay-Zahlungs-ID
* Barcode-ID

* Kundenwunsch
** Kund:innen können bei der Bestellung über den Webshop einen Wunsch angeben. Dieser Wunsch wird als Auftragsnotiz in den Auftragsdaten gespeichert.

* Auftragstyp

* Auftrag im Webshop aufrufen
** Öffnet die URL des Auftrags in deinem Webshop

* Nachbestellungs-ID
* Gutscheinwert
* Rechnungsnummer-ID

* DHL Retoure Online QR-Code
** Sendet deinen Kund:innen einen QR-Code für DHL Retoure Online. Wenn deine Kund:innen einen Artikel zurücksenden möchten, müssen sie dem Personal in der Postfiliale vor Ort den QR-Code auf ihrem Smartphone vorzeigen und diese drucken dann das Retourenlabel und bringen es auf dem Paket an. Deine Kund:innen benötigen also keinen Drucker mehr und du musst das Retourenlabel nicht als PDF-Anhang in der E-Mail versenden. +
Der QR-Code wird in der E-Mail an deine Kund:innen als URL ausgegeben. Nach einem Klick auf die URL erscheint dann in einem separaten Fenster der QR-Code.

--


[.collapseBox]
.Variablen in der Unterkategorie *Auftrag / Lieferadresse*
--

* Lieferadresse Vorname + Nachname
* Lieferadresse Adresszusatz
* Lieferadresse Vorname
* Lieferadresse Nachname
* Lieferadresse Firmenname
* Lieferadresse Kontaktperson
* Lieferadresse Telefon
* Lieferadresse Straße
* Lieferadresse Ort + Postleitzahl
* Lieferadresse Ort
* Lieferadresse Postleitzahl
* Lieferadresse Land
* Lieferadresse Länder-ID
* Lieferadresse Länder-ISO-Code 2
* Lieferadresse Länder-ISO-Code 3
* Lieferadresse Region/Bundesland etc.

--





[.collapseBox]
.Variablen in der Unterkategorie *Auftrag / Rechnungsadresse*
--

* Rechnungsadresse Vorname + Nachname
* Rechnungsadresse Adresszusatz
* Rechnungsadresse Vorname
* Rechnungsadresse Nachname
* Rechnungsadresse Firmenname
* Rechnungsadresse Kontaktperson
* Rechnungsadresse Telefon
* Rechnungsadresse Straße
* Rechnungsadresse Ort + Postleitzahl
* Rechnungsadresse Ort
* Rechnungsadresse Postleitzahl
* Rechnungsadresse Land
* Rechnungsadresse Länder-ID
* Rechnungsadresse Länder-ISO-Code 2
* Rechnungsadresse Länder-ISO-Code 3
* Rechnungsadresse Region/Bundesland etc.

--




[.collapseBox]
.Variablen in der Unterkategorie *Auftrag / Auftragspositionen*
--

* Artikel-ID
* Artikeleigenschaften
* Status-ID des retournierten Artikels
* Name des retournierten Artikels
* Variantennummer
* Artikelname
* Artikelmenge
* Bruttopreis
* Nettopreis
* Mehrwertsteuersatz
* Herkunft
* Externe Artikel-ID
* Externe Varianten-ID
* Externe Token-ID
* Inhalt
* Einheit
* Variantenname
* Varianten-ID
* Attributwerte

* Modell
** Modellbezeichnung des Artikels

* GTIN
** Global Trade Item Number (GTIN) des Artikels

* ISBN
** ISBN-Code des Artikels

* ASIN
** Amazon Standard Ident Number (ASIN) des Artikels

* Verfügbarkeitstext
** Name der Artikelverfügbarkeit des Nettowarenbestands

* Verfügbarkeits-ID
** ID der Artikelverfügbarket des Netttowarenbestands

* Verfügbarkeitstext physischer Warenbestand
** Name der Artikelverfügbarkeit des physischen Warenbestands

* Verfügbarkeits-ID physischer Warenbestand
** ID der Artikelverfügbarkeit des physischen Warenbestands

* Freitextfelder 1 bis 20
** Freitextfelder für die Artikel wie im Menü *Einrichtung » Artikel » Freitextfelder* gespeichert. +
*_Beispiel:_* `Freitextfeld 3` gibt den Text aus, der unter *Feld 3* gespeichert ist.

* URL zum Variantenbild
** Gibt die URL zum Variantenbild aus.

* Herstellername

* Lager-ID

* Retourenkommentar

* Wert der Retoure in Prozent

* ID des Retourengrunds
** ID des Retourengrund wie im Menü *Einrichtung » Aufträge » Auftragstypen » Retoure* gespeichert.

* Retourengrund
** Name des Retourengrund wie im Menü *Einrichtung » Aufträge » Auftragstypen » Retoure* gespeichert.

* Codes eines Gutscheins

* Zolltarifnummer

* Erscheinungsdatum

* Gesamtpreis (Einzelpreis x Menge)

* Rabatt pro Auftragsposition

* URL zum Artikel
** Gibt die URL zum Artikel im Webshop aus.


--






[.collapseBox]
.Variablen in der Unterkategorie *Auftrag / Versand*
--

* Mögliches Lieferdatum
* Voraussichtliches Versanddatum
* Datum des Retoureneingangs
* Voraussichtliches Lieferdatum
* Retourenpaketnummer
* Versandkosten gesamt

* Paketnummernliste
** Paketnummern bzw. Tracking-Nummern werden nach erfolgreicher Auftragsanmeldung beim Versanddienstleister im Auftrag im Tab *Einstellungen* gespeichert.

* Tracking-URL
** Dient zur Sendungsverfolgung. Die URL wird im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versanddienstleister* gespeichert.

* Versanddienstleister
** Name des Versanddienstleisters wie im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versanddienstleister* gespeichert.

* Versanddienstleister-ID
** Wird automatisch vom System vergeben. Die ID des Versanddienstleisters findest du im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versanddienstleister*.

* Versandprofil
** Name des Versandprofils wie im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile* gespeichert.

* Versandprofil-ID
** Wird automatisch vom System vergeben. Die ID des Versandprofils findest du im Menü *Einrichtung » Aufträge » Versand » Optionen* im Tab *Versandprofile*.


* Lieferschein-ID
* Nachbestellung Lieferdatum


--




[.collapseBox]
.Variablen in der Kategorie *Kontakt*
--

* Kontakt-ID
* Vorname
* Nachname
* Vollständiger Name
* Geschlecht
* Anrede
* Anrede geschäftlich
* Anrede privat
* Firmenname
* Sprache

* Klasse
** Klasse, der der Kontakt zugeordnet ist. Klassen erstellst du im Menü *Einrichtung » CRM » Kundenklassen*.

* Nummer
** Zusätzliche Nummer für den Kontakt

* Titel
* Vorname und Nachname des Systembenutzers
** Vorname und Nachname des Systembenutzers, der als Eigner am Kontaktdatensatz gespeichert ist.
* Signatur des Systembenutzers
** Signatur des Systembenutzers, der als Eigner am Kontaktdatensatz gespeichert ist, im Textformat.
* Signatur des Systembenutzers im HTML-Format
** Signatur des Systembenutzers, der als Eigner im Kontaktdatensatz gespeichert ist, im HTML-Format.
* Kontoinhaber (Kontakt)
* Bankname des Kontakts
* IBAN des Kontakts
* BIC des Kontakts
* Anzahl der Aufträge
* Newsletter-Empfang: Zustimmung durch Kontakt
** Datum, wann der Kontakt dem Newsletter-Empfang zugestimmt hat. +
Datumsformat in der E-Mail: `mm-tt-jjjj`. +
Im Kontaktdatensatz wird zusätzlich zum Datum im Format `tt-mm-jjjj` der Zeitstempel im Format `00:00:00` gespeichert.



--




[.collapseBox]
.Variablen in der Unterkategorie *Kontakt / Lieferadresse*
--

* Lieferadresse Vorname + Nachname
* Lieferadresse Adresszusatz
* Lieferadresse Vorname
* Lieferadresse Nachname
* Lieferadresse Firmenname
* Lieferadresse Telefon
* Lieferadresse Straße
* Lieferadresse Ort + Postleitzahl
* Lieferadresse Ort
* Lieferadresse Postleitzahl
* Lieferadresse Land
* Lieferadresse Länder-ID
* Lieferadresse Länder-ISO-Code 2
* Lieferadresse Länder-ISO-Code 3
* Lieferadresse Region/Bundesland etc.

--



[.collapseBox]
.Variablen in der Unterkategorie *Kontakt / Rechnungsadresse*
--

* Rechnungsadresse Vorname + Nachname
* Rechnungsadresse Adresszusatz
* Rechnungsadresse Vorname
* Rechnungsadresse Nachname
* Rechnungsadresse Firmenname
* Rechnungsadresse Telefon
* Rechnungsadresse Straße
* Rechnungsadresse Ort + Postleitzahl
* Rechnungsadresse Ort
* Rechnungsadresse Postleitzahl
* Rechnungsadresse Land
* Rechnungsadresse Länder-ID
* Rechnungsadresse Länder-ISO-Code 2
* Rechnungsadresse Länder-ISO-Code 3
* Rechnungsadresse Region/Bundesland etc.

--




[.collapseBox]
.Variablen in der Unterkategorie *Kontakt / Optionen*
--

* E-Mail privat
* Telefon privat
* Mobiltelefon privat
* Fax privat
* E-Mail geschäftlich
* Telefon geschäftlich
* Mobiltelefon geschäftlich
* Fax geschäftlich
* eBay-Name
* E-Mail PayPal
* Zusätzlicher Ansprechpartner

--




















[.collapseBox]
.Variablen in der Kategorie *Global*
--

* URL zum Checkout
** Gibt die URL zum Checkout-Bereich des Auftrags im Webshop aus.

* URL zum Warenkorb
** Gibt die URL zum Warenkorb im Webshop aus.

* URL zu den Geschäftsbedingungen
** Gibt die URL zu den AGB aus.

* URL zum Webshop
** Gibt die URL zum Webshop aus.

* URL zum neuen Passwort
** Gibt die URL zu einem Formular zum Erstellen eines neuen Passworts aus. Dort geben Kund:innen ihre E-Mail-Adresse ein.

* URL zum Ändern des Passworts
** Gibt die URL zum Bereich *Passwort ändern* im Webshop aus. Dort können Kund:innen ein neues Passwort eingeben.

* URL zum Bestätigen der E-Mail-Adresse
** Gibt die URL zum Bestätigen der E-Mail-Adressänderung des Kontakts aus.

* Widerrufsrecht im HTML-Format
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsrecht* und dort im Tab *HTML* gespeichert.

* Widerrufsrecht im reinen Textformat
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsrecht* und dort im Tab *Text* gespeichert.

* Datenschutzerklärung im reinen Textformat
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Datenschutzerklärung* und dort im Tab *Text* gespeichert.

* Datenschutzerklärung im HTML-Format
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Datenschutzerklärung* und dort im Tab *HTML* gespeichert.

* Impressum im reinen Textformat
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Impressum* und dort im Tab *Text* gespeichert.

* Impressum im HTML-Format
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Impressum* und dort im Tab *HTML* gespeichert.

* Widerrufsformular im reinen Textformat
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsformular* und dort im Tab *Text* gespeichert.

* Widerrufsformular im HTML-Format
** Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsformular* und dort im Tab *HTML* gespeichert.

* Heutiges Datum
** Gibt das heutige Datum im Format tt-mm-jjjj aus.

* Bankname (Stammdaten)
** Bankname aus den Stammdaten deines plentymarkets Systems. Wird im *Basics*-Assistenten im Schritt *Bankdaten* gespeichert. Du findest den Assistenten im Menü *Einrichtung » Assistenten » Grundeinstellungen*. +
Alternativ findest du den gespeicherten Banknamen im Menü *Einrichtung » Einstellungen » Bank*.

* IBAN (Stammdaten)
** IBAN aus den Stammdaten deines plentymarkets Systems. Wird im *Basics*-Assistenten im Schritt *Bankdaten* gespeichert. Du findest den Assistenten im Menü *Einrichtung » Assistenten » Grundeinstellungen*. +
Alternativ findest du die gespeicherte IBAN im Menü *Einrichtung » Einstellungen » Bank*.

* BIC
** BIC aus den Stammdaten deines plentymarkets Systems. Wird im *Basics*-Assistenten im Schritt *Bankdaten* gespeichert. Du findest den Assistenten im Menü *Einrichtung » Assistenten » Grundeinstellungen*. +
Alternativ findest du die gespeicherte BIC im Menü *Einrichtung » Einstellungen » Bank*.

* Kontoinhaber
** Kontoinhaber:in aus den Stammdaten deines plentymarkets Systems. Wird im *Basics*-Assistenten im Schritt *Bankdaten* gespeichert. Du findest den Assistenten im Menü *Einrichtung » Assistenten » Grundeinstellungen*. +
Alternativ findest du den:die Kontoinhaber:in im Menü *Einrichtung » Einstellungen » Bank*.

* Signatur im reinen Textformat
** Die Signatur wird im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Signatur* im Bereich *Reine Textsignatur* gespeichert.

* Signatur im HTML-Format
** Die Signatur wird im Menü *Einrichtung » Mandant » [Mandant wählen] » E-Mail » Signatur* im Bereich *HTML-Signatur* gespeichert.

* Gutschein-Code (1) bis (10)
** Gutschein-Codes werden in der Kampagne im Menü *Aufträge » Gutscheine* generiert. Ein Gutschein-Code kann immer nur jeweils einer Kampagne zugeordnet werden, um diesen Gutschein-Code aus der Kampagne in der E-Mail-Vorlage zu versenden.

* EORI-Nummer
** Eindeutige Identifizierungsnummer, die für Zollzwecke benötigt wird

--





[.collapseBox]
.Variablen in der Kategorie *Newsletter*
--

* URL zur Bestätigung des Newsletter-Abonnements
** Gibt die URL zum Bestätigen des Newsletter-Abonnements aus.

--
