= EmailBuilder
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:description: Erfahre, wie du den EmailBuilder in plentymarkets verwendest.
:position: 19
:url: crm/emailbuilder
:id:
:author: team-crm

Der EmailBuilder ist ein Baukastenmodul, mit dem du deine E-Mail-Vorlagen schnell und einfach per Drag&Drop erstellen und bearbeiten kannst. Dafür benötigst du keinerlei Programmierungskenntnisse.

Der EmailBuilder besteht aus 2 Ansichten: dem Konfigurationsmanager und dem Editor. Im Konfigurationsmanager erstellst du Ordner, ggf. Unterordner, Basisvorlagen, Vorlagen und Textblöcke. Im Editor befüllst du deine Basisvorlagen, Vorlagen und Textblöcke mit Inhalt. Du kannst zum Beispiel eine Vorlage für eine Rechnung erstellen und diese zukünftig für alle Rechnungen an deine Kund:innen verwenden.

//Konfigurationsmanager? Oder Content-Manager?

Über die sogenannte *Basisvorlage* erstellst du den Header und den Footer für die Vorlage, die dann für alle E-Mail-Vorlagen verwendet wird. Header und Footer sind global wirksam; Änderungen, die du am Header und Footer vornimmst, wirken sich demnach auch auf alle bestehenden Vorlagen sowie weitere Vorlagen, die du zukünftig erstellst, aus.

// Screenshot einfügen
// Icons einfügen

[#ordner-verwalten]
== Ordner verwalten

Du kannst beliebig viele Ordner und Unterordner erstellen. Nachdem der Ordner erstellt ist, kannst du über das Kontextmenü (Dreipunkt-Menü) eine neue Vorlage und einen neuen Textblock erstellen.

Mit der Vorlage erstellst du sozusagen das Gerüst deiner E-Mail, also den Header und den Footer. (Screenshot einfügen). Der Textblock ist der eigentliche Inhalt deiner E-Mail.

//Vorlage = Gerüst mit Header und Footer
//Textblock = Inhalt der E-Mail

[#ordner-erstellen]
=== Ordner erstellen

Erstelle Ordner, um später eine bessere Übersicht für deine E-Mail-Vorlagen zu bekommen. Gehe wie im Folgenden beschrieben vor, um einen neuen Ordner zu erstellen.

[instruction]
Ordner erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke auf *Neuer Basisordner* (Plus-Zeichen). +
→ Ein Fenster wird geöffnet.
. Gib den Namen für den Ordner ein.
. *Speichere* die Einstellungen. +
→ Der neue Ordner wird der Ordnerliste ganz unten hinzugefügt.

[#ordername-aktualisieren]
=== Ordnernamen aktualisieren

Du kannst den Namen des Ordners jederzeit anpassen. Gehe dazu wie im Folgenden beschrieben vor.

[instruction]
Ordnernamen aktualisieren:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke auf den Ordner, den du bearbeiten möchtest. +
→ Ein Fenster wird geöffnet.
. Gib einen anderen Namen für den Ordner ein.
. Klicke auf *Aktualisieren*. +
→ Der neue Name des Ordners wird aktualisiert und in der Liste angezeigt.

[#unterordner-erstellen]
=== Unterordner erstellen

Erstelle Unterordner in deinen Ordnern, um deine E-Mail-Vorlagen später noch differenzierter zu gruppieren. Du kannst beliebig viele Unterordner erstellen. Auch die Anzahl der Ebenen ist unbegrenzt.

[TIP]
.Entwurf für deine Ordner-Struktur im Vorfeld erstellen
====
Wir empfehlen dir, im Vorfeld einen Entwurf zu erstellen, um unübersichtliche Verschachtelungen in deiner Ordnerstruktur zu vermeiden, denn: Je mehr Ebenen du erstellst, desto unübersichtlicher wird die Struktur.
====

[instruction]
Unterordner erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners, für den du einen Unterordner erstellen möchtest, auf das Kontextmenü (Dreipunkte-Menü). +
→ Ein Fenster wird geöffnet.
. Klicke auf *+ Neuer Ordner*. +
→ Ein Fenster wird geöffnet.
. Gib den Namen für den Unterordner ein.
. *Speichere* die Einstellungen. +
→ Der Unterordner wird erstellt.

Öffne den Unterordner, indem du den Hauptordner mit einem Klick auf den Pfeil ( > ) ganz links öffnest. Du siehst dort auf einen Blick alle erstellten Unterordner.

[#ordner-loeschen]
=== Ordner löschen

Du kannst Ordner und Unterordner jederzeit löschen. Beachte, dass dabei alle Inhalte in dem Ordner, den du löschen möchtest, entfernt werden.

[instruction]
Ordner löschen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners bzw. Unterordners, den du löschen möchtest, auf das Kontextmenü (Dreipunkte-Menü). +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicke auf *Löschen*. +
→ Der Ordner wird gelöscht.

[#textblock-erstellen]
== Textblock erstellen

Text

[#vorlagen-verwalten]
== Vorlagen verwalten

Text

[#basisvorlage-erstellen]
=== Basisvorlage erstellen

Über die sogenannte Basisvorlage erstellst du den Header und den Footer für die Vorlage, die dann für alle E-Mail-Vorlagen verwendet wird. Header und Footer sind global wirksam; Änderungen, die du am Header und Footer vornimmst, wirken sich demnach auch auf alle bestehenden Vorlagen sowie weitere Vorlagen, die du zukünftig erstellst, aus.

Es gibt bereits vordefinierte Inhalte, die du nach deinen Wünschen anpassen kannst.

[instruction]
Basisvorlage erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners bzw. Unterordners, in dem du eine Basisvorlage erstellen möchtest, auf das Kontextmenü (Dreipunkt-Menü).
. Klicke auf *+ Neue Basis-Vorlage*.

[#vorlage-erstellen]
=== Vorlage erstellen

Text

[instruction]
Inhalt der Vorlage erstellen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klicke in der Zeile des Ordners, in dem du eine Vorlage erstellen möchtest, auf das Kontextmenü (Dreipunkt-Menü).
. Klicke auf *+ Neue Vorlage*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#table-emailbuilder-create-template>>.

// Screenshot einfügen

[[table-emailbuilder-create-template]]
.Vorlage im EmailBuilder erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Speichern*
|Speichert die Einstellungen.

| *Name*
|Name für die Vorlage eingeben.

| *Basisvorlage*
|Basisvorlage aus der Dropdown-Liste wählen. Die Liste enthält <<basisvorlage-erstellen#, alle Basisvorlagen, die du bereits erstellt hast>>.

| *Bearbeiten*
|

| *Betreff*
|Betreff deiner E-Mail eingeben.

| *Von*
|

| *Antwort an*
|

| *CC*
|

| *BCC*
|

| *Anhänge*
|

|====

[#vorlage-suchen]
=== Vorlage suchen

Die folgende Handlungsanweisung beschreibt, wie du allgemein Vorlagen suchst. Die Vorgehensweise ist demnach identisch für die Suche nach Vorlagen und Basisvorlagen.

[instruction]
Vorlage suchen:

. Öffne das Menü *CRM » EmailBuilder*.
. Wähle die Sprache und/oder den Mandanten aus den Dropdown-Listen. +
→ Die Vorlagen, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke auf die Vorlage, um diese zu öffnen und zu bearbeiten.

[#vorlage-bearbeiten]
=== Vorlage bearbeiten

Die folgende Handlungsanleitung beschreibt, wie du allgemein Vorlagen bearbeitest. Die Vorgehensweise ist demnach identisch für das Bearbeiten von Vorlagen und Basisvorlagen.

[instruction]
Vorlage bearbeiten:

. Öffne das Menü *CRM » EmailBuilder*.
. Klappe den Ordner auf (Pfeil-Icon), der die Vorlage enthält, die du bearbeiten möchtest.
. Klicke auf die Vorlage.
. Nimm die Änderungen vor. Beachte dazu auch die Erläuterungen in <<#table-emailbuilder-create-template>>.
. *Speichere* die Einstellungen.

[#vorlage-loeschen]
=== Vorlage löschen

Text

[instruction]
Vorlage löschen:

. Öffne das Menü *CRM » EmailBuilder*.
. Klappe den Ordner auf (Pfeil-Icon), der die Vorlage enthält, die du löschen möchtest.
. Klicke in der Zeile der Vorlage, die du löschen möchtest, auf das Kontextmenü (Dreipunkte-Menü).
. Klicke auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicke auf *Löschen*. +
→ Die Vorlage wird gelöscht.

[#e-mail-variablen]
== Verfügbare Variablen für den EmailBuilder

Die verfügbaren Variablen für den EmailBuilder sind in verschiedene Kategorien bzw. Unterkategorien gruppiert:

* Kontakt
** Kontaktoptionen
** Rechnungsadresse
** Lieferadresse
* Auftrag
** Rechnungsadresse
** Lieferadresse
** Versand
* Auftragsposition
* Globale Variablen
* Ticket

In den folgenden aufklappbaren Bereichen findest du die einzelnen Variablen, die für die verschiedenen Kategorien zur Verfügung stehen. Bei Bedarf kannst du diese Bereiche einfach aufklappen (icon:plus-square-o[]).





[.collapseBox]
.Kategorie *Kontakt*
--

[[table-emailbuilder-variable-list-contact]]
.Verfügbare Variablen für die Kategorie *Kontakt*
[cols="1,3"]
|====
|Variable |Erläuterung

|Kontakt-ID
|



|
|

|====

--






[.collapseBox]
.Unterkategorie *Kontakt / Kontaktoptionen*
--

[[table-emailbuilder-variable-list-contact-options]]
.Verfügbare Variablen für die Unterkategorie *Kontakt / Kontaktoptionen*
[cols="1,3"]
|====
|Variable |Erläuterung

|E-Mail privat
|


|Telefon privat
|


|Mobiltelefon privat
|


|Fax privat
|


|E-Mail geschäftlich
|


|Telefon geschäftlich
|


|Mobiltelefon geschäftlich
|


|Fax geschäftlich
|


|eBay-Name des Kontakts
|

|====

--





[.collapseBox]
.Unterkategorie *Kontakt / Rechnungsadresse*
--

[[table-emailbuilder-variable-list-contact-invoice-address]]
.Verfügbare Variablen für die Unterkategorie *Kontakt / Rechnungsadresse*
[cols="1,3"]
|====
|Variable |Erläuterung

|
|



|====

--







[.collapseBox]
.Unterkategorie *Kontakt / Rechnungsadresse*
--

[[table-emailbuilder-variable-list-contact-delivery-address]]
.Verfügbare Variablen für die Unterkategorie *Kontakt / Lieferadresse*
[cols="1,3"]
|====
|Variable |Erläuterung

|
|



|====

--






[.collapseBox]
.Kategorie *Auftrag*
--

[[table-emailbuilder-variable-list-order]]
.Verfügbare Variablen für die Kategorie *Auftrag*
[cols="1,3"]
|====
|Variable |Erläuterung

|
|



|====

--





[.collapseBox]
.Unterkategorie *Auftrag / Rechnungsadresse*
--

[[table-emailbuilder-variable-list-order-invoice-address]]
.Verfügbare Variablen für die Unterkategorie *Auftrag / Rechnungsadresse*
[cols="1,3"]
|====
|Variable |Erläuterung

|
|



|====

--





[.collapseBox]
.Unterkategorie *Auftrag / Lieferadresse*
--

[[table-emailbuilder-variable-list-order-delivery-address]]
.Verfügbare Variablen für die Unterkategorie *Auftrag / Lieferadresse*
[cols="1,3"]
|====
|Variable |Erläuterung

|
|



|====

--







[.collapseBox]
.Unterkategorie *Auftrag / Versand*
--

[[table-emailbuilder-variable-list-order-shipping]]
.Verfügbare Variablen für die Unterkategorie *Auftrag / Versand*
[cols="1,3"]
|====
|Variable |Erläuterung

|Mögliches Lieferdatum
|

|Voraussichtliches Versanddatum
|

|Datum des Retoureneingangs
|

|Voraussichtliches Lieferdatum
|

|Retourenpaketnummer
|

|Versandkosten gesamt
|

|Paketnummernliste
|

|Tracking-URL
|

|Versanddienstleister
|

|Versanddienstleister-ID
|

|Versandprofil-ID
|

|Versandprofil
|

|Spätestes Lieferdatum
|
|====

--







[.collapseBox]
.Kategorie *Auftragsposition*
--

[[table-emailbuilder-variable-list-order-item]]
.Verfügbare Variablen für die Kategorie *Auftragsposition*
[cols="1,3"]
|====
|Variable |Erläuterung

|
|



|====

--



[.collapseBox]
.Kategorie *Globale Variablen*
--

[[table-emailbuilder-variable-list-globals]]
.Verfügbare Variablen für die Kategorie *Globale Variablen*
[cols="1,3"]
|====
|Variable |Erläuterung

|URL zum Checkout
|Gibt die URL zum Checkout-Bereich des Auftrags im Webshop aus.

|URL zum Warenkorb
|Gibt die URL zum Warenkorb im Webshop aus.

|URL zu den Geschäftsbedingungen
|Gibt die URL zu den AGB aus.

|URL zum Webshop
|Gibt die URL zum Webshop aus.

|URL zum neuen Passwort
|Gibt die URL zu einem Formular zum Erstellen eines neuen Passworts aus. Dort geben Kund:innen ihre E-Mail-Adresse ein.

|URL zum Ändern des Passworts
|Gibt die URL zum Bereich *Passwort ändern* im Webshop aus. Dort können Kund:innen ein neues Passwort eingeben.

|URL zum Bestätigen der E-Mail-Adresse
|

|Widerrufsrecht im HTML-Format
|Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsrecht* und dort im Tab *HTML* gespeichert.

|Widerrufsrecht im reinen Textformat
|Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsrecht* und dort im Tab *Text* gespeichert.

|Datenschutzerklärung im reinen Textformat
|Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Datenschutzerklärung* und dort im Tab *Text* gespeichert.

|Datenschutzerklärung im HTML-Format
|Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Datenschutzerklärung* und dort im Tab *HTML* gespeichert.

|Impressum im reinen Textformat
|Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Impressum* und dort im Tab *Text* gespeichert.

|Impressum im HTML-Format
|Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Impressum* und dort im Tab *HTML* gespeichert.

|Widerrufsformular im reinen Textformat
|Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsformular* und dort im Tab *Text* gespeichert.

|Widerrufsformular im HTML-Format
|Der Text wird im Menü *Einrichtung » Mandant » [Mandant wählen] » Webshop » Rechtliches » [Sprache aufklappen]* im Tab *Widerrufsformular* und dort im Tab *HTML* gespeichert.

|Heutiges Datum
|

|Vorname und Nachname des Kontoinhabers
|

|Bankname
|

|IBAN
|

|BIC
|

|Signatur im reinen Textformat
|

|Signatur im HTML-Format
|

|Gutschein-Code (1) bis (10)
|Ein Gutschein-Code kann immer nur jeweils einer Kampagne zugeordnet werden, um diesen Gutschein-Code aus der Kampagne in der E-Mail-Vorlage zu versenden.

|====

--




[.collapseBox]
.Kategorie *Ticket*
--

[[table-emailbuilder-variable-list-globals]]
.Verfügbare Variablen für die Kategorie *Ticket*
[cols="1,3"]
|====
|Variable |Erläuterung

|Historie
|Der zuletzt gespeicherte Text im Ticket, d.h. der Text eines Kommentars oder einer Nachricht. +
Damit diese Variable befüllt wird, müssen eine E-Mail-Vorlage und Ereignisaktionen eingerichtet sein. Die Ereignisaktionen müssen auf dem Ereignis *Neuer Kommentar*, *Neue Nachricht vom Mitarbeiter* oder *Neue Nachricht vom Kunden* beruhen. Die Variable wird dann je nach Ereignis befüllt. Bei allen anderen Ereignissen wird die Variable nicht befüllt.


|Letzter Kommentar
|Der zuletzt hinzugefügte Kommentar im Ticket. +
Damit diese Variable befüllt wird, müssen eine E-Mail-Vorlage und eine Ereignisaktion eingerichtet sein. Die Ereignisaktion muss auf dem Ereignis *Neuer Kommentar* beruhen. Bei allen anderen Ereignissen wird die Variable nicht befüllt.

|Letzte Nachricht
|Die zuletzt hinzugefügte Nachricht im Ticket. +
Damit diese Variable befüllt wird, müssen eine E-Mail-Vorlage und eine Ereignisaktion eingerichtet sein. Die Ereignisaktion muss auf einem der beiden Ereignisse *Neue Nachricht vom Mitarbeiter* oder *Neue Nachricht vom Kunden* beruhen. Am besten richtest du eine Ereignisaktion für beide Ereignisse ein und erhältst so eine E-Mail, egal ob deine Mitarbeiter:innen oder deine Kund:innen schreiben. Bei allen anderen Ereignissen wird die Variable nicht befüllt.


|URL
|Verlinkt zum Ticket im Bereich *Mein Konto* des Kontakts in deinem Webshop. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.


|Backend-URL
|Öffnet das Ticket im Backend im Menü *CRM » Ticketsystem*. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.


|Titel
|Betreff des Tickets. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.

|Ticket-ID
|ID des Tickets. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.


|Tags
|Zeigt die mit dem Ticket verknüpften Tags an. +
Die Tags müssen zuvor im Menü *Einrichtung » Einstellungen » Tags* für den Bereich *Ticket* erstellt werden.

|Status
|Status des Tickets. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.


|Priorität
|Priorität des Tickets. +
Damit diese Variable befüllt wird, muss eine E-Mail-Vorlage eingerichtet sein.

|====

--
