= Firmen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Firma, Firmen, Firmen verwalten, Firmen-UI
:description: Erfahre, wie du in plentymarkets Firmen verwaltest.
:position: 12
:url: crm/firmen
:id: SFYHVN4
:author: team-crm

Auf dieser Handbuchseite erfährst du alles über die Firmenverwaltung in plentymarkets. Firmen verwaltest du im Menü *CRM » Firmen*. Erstelle neue Firmendatensätze und verknüpfe diese mit bestehenden Kontaktdatensätzen.

== Firma erstellen

Die Bedienoberfläche zum Erstellen einer neuen Firma wird in einer Standardansicht, die du nachträglich ganz einfach bearbeiten kannst, geöffnet. Mit dieser individuell anpassbaren Bedienoberfläche hast du maximale Flexibilität und kannst genau die Felder auswählen, die für dich und deinen Arbeitsalltag am besten geeignet sind.

== Firma suchen

== Firma bearbeiten

== Firma mit Kontakt verknüpfen


* Eine Firma einem Kontakt zuweisen
* Eine Firma mehreren Kontakten zuweisen
* Einem Kontakt eine Firma zuweisen
* Mehreren Kontakten eine Firma zuweisen


== Firma löschen
