= Firmen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Firma, Firmen, Firmen verwalten, Firmen-UI
:description: Erfahre, wie du in plentymarkets Firmen verwaltest.
:position: 12
:url: crm/firmen
:id: SFYHVN4
:author: team-crm

Auf dieser Handbuchseite erfährst du alles über die Firmenverwaltung in plentymarkets. Firmen verwaltest du im Menü *CRM » Firmen*. Erstelle neue Firmendatensätze und verknüpfe diese mit bestehenden Kontaktdatensätzen.

[#firma-erstellen]
== Firma erstellen

Die Bedienoberfläche zum Erstellen einer neuen Firma wird in einer Standardansicht, die du nachträglich ganz einfach bearbeiten kannst, geöffnet. Mit dieser individuell anpassbaren Bedienoberfläche hast du maximale Flexibilität und kannst genau die Felder auswählen, die für dich und deinen Arbeitsalltag am besten geeignet sind.

[.instruction]
Firma erstellen:

. Öffne das Menü *CRM » Firmen*.
. Klicke auf *+ Neue Firma hinzufügen*.

[#firma-suchen]
== Firma suchen

Die Bedienoberfläche zum Suchen einer neuen Firma wird in einer Standardansicht, die du nachträglich ganz einfach bearbeiten kannst, geöffnet. Speichere mehrere Suchen und wähle die passende für dich aus. So sparst du Zeit, weil du nicht jedes Mal erneut die gewünschten Filter setzen musst.

[.instruction]
Firma suchen:

. Öffne das Menü *CRM » Firmen*.
.

[#firma-bearbeiten]
== Firma bearbeiten

TEXT

[.instruction]
Firma bearbeiten:

. Öffne das Menü *CRM » Firmen*.
. Suche die Firma, du die bearbeiten möchtest anhand der Filtereinstellungen wie im Kapitel <<#firma-bearbeiten, Firma bearbeiten>> beschrieben.
→ Die Firmen, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile der Firma.

[#firma-mit-kontakt-verknuepfen]
== Firma mit Kontakt verknüpfen

TEXT

* Eine Firma einem Kontakt zuweisen
* Eine Firma mehreren Kontakten zuweisen
* Einem Kontakt eine Firma zuweisen
* Mehreren Kontakten eine Firma zuweisen

[#firma-loeschen]
== Firma löschen

Wenn ein Firmendatensatz nicht mehr benötigt wird, kannst du diesen jederzeit löschen. Die Kontaktdatensätze, die mit der Firma verknüpft sind, werden selbstverständlich _nicht_ gelöscht. Lediglich die Zuordnung Firma/Kontakt wird beim Löschen der Firma entfernt.

[.instruction]
Firma löschen:

. Öffne das Menü *CRM » Firmen*.
. Suche die Firma, du die löschen möchtest anhand der Filtereinstellungen wie im Kapitel <<#firma-bearbeiten, Firma bearbeiten>> beschrieben.
→ Die Firmen, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile der Firma.
