= Firmen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Firma, Firmen, Firmen verwalten, Firmen-UI
:description: Erfahre, wie du in plentymarkets Firmen verwaltest.
:position: 12
:url: crm/firmen
:id: SFYHVN4
:author: team-crm

Auf dieser Handbuchseite erfährst du alles über die Firmenverwaltung in plentymarkets. Firmen verwaltest du im Menü *CRM » Firmen*. Erstelle neue Firmendatensätze und verknüpfe diese mit bestehenden Kontaktdatensätzen.

[#firma-erstellen]
== Firma erstellen

Die Bedienoberfläche zum Erstellen einer neuen Firma wird in einer Standardansicht, die du nachträglich ganz einfach bearbeiten kannst, geöffnet. Mit dieser individuell anpassbaren Bedienoberfläche hast du maximale Flexibilität und kannst genau die Felder auswählen, die für dich und deinen Arbeitsalltag am besten geeignet sind.

[.instruction]
Firma erstellen:

. Öffne das Menü *CRM » Firmen*.
. Klicke auf der linken Seite auf *+ Neue Firma hinzufügen*. +
→ Die Ansicht *Details* öffnet sich.
. Gib die Daten ein bzw. wähle die Optionen aus den Dropdown-Listen. Beachte dazu die Erläuterungen in <<#table-create-company>>.
. *Speichere* die Einstellungen.

[[table-create-company]]
.Firma erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+| *Details*

| *Name*
|Wie lautet der Name der Firma?

| *USt-IdNr.*
|Wie lautet die Umsatzsteueridentifikationsnummer der Firma? +
Wenn beim Versand von Waren an einen gewerblichen Käufer in ein anderes EU-Land (innergemeinschaftliche Lieferung) der Auftrag netto berechnet werden soll, muss die USt-IdNr. gespeichert sein.

| *Valuta*
|Gib einen Zeitraum (ab Rechnungserstellung) ein, wenn eine zusätzliche Frist vor dem Zeitraum *Zahlungsziel* gewünscht ist.
// ausklappbare Box Kontakte-Seite

| *Zahlungsziel*
|Gib das Zahlungsziel in Tagen ein.
// ausklappbare Box Kontakte-Seite

| *Skontofrist*
|Gib die Anzahl der Tage (ab Rechnungserstellung) ein, in denen die Firma skontiert offene Forderungen bezahlen kann.
// ausklappbare Box Kontakte-Seite

| *Skontosatz*
|Gib einen Wert in Prozent ein, den die Firma bei Einhaltung der *Skontofrist* in Abzug bringen kann.
// ausklappbare Box Kontakte-Seite

| *Eigner*
|Welcher Eigner soll der Firma zugeordnet werden? Wähle einen Namen aus der Dropdown-Liste.

2+| *Lieferantendetails* +
//wann ist dieser Bereich sichtbar?

| *Lieferzeit*
|Gib die Lieferzeit in Tagen ein.

| *MBW*
|MBW steht für Mindestbestellwert. Gib den Mindestbestellwert in der Systemwährung ein.

| *Währung*
|Wähle die Währung aus der Dropdown-Liste. Diese Währung wird vorrangig für die jeweiligen Artikel und Aufträge berücksichtigt.

|====

[#firma-suchen]
== Firma suchen

Die Bedienoberfläche zum Suchen einer neuen Firma wird in einer Standardansicht, die du nachträglich ganz einfach bearbeiten kannst, geöffnet. Speichere mehrere Suchen und wähle die passende für dich aus. So sparst du Zeit, weil du nicht jedes Mal erneut die gewünschten Filter setzen musst.

Um bestimmte Firmen zu suchen, gibst du die dir bekannten Suchbegriffe in die Filter ein oder wählst die Einstellungen der Dropdown-Listen. Es ist auch möglich, mehrere Suchbegriffe gleichzeitig in die Suchfelder einzugeben. Dies ermöglicht eine schnellere und genauere Suche.

[.instruction]
Firma suchen:

. Öffne das Menü *CRM » Firmen*.
. Klicke auf icon:filter[].
. Gib die ID der Firma, den Namen der Firma oder den zugeordneten Eigner oder eine Kombination aus allen oder mehreren Begriffen ein.
. Klicke auf *Suchen*. +
→ Die Firmen, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt.


[#firma-bearbeiten]
== Firma bearbeiten

TEXT

[.instruction]
Firma bearbeiten:

. Öffne das Menü *CRM » Firmen*.
. Suche die Firma, du die bearbeiten möchtest anhand der Filtereinstellungen wie im Kapitel <<#firma-suchen, Firma suchen>> beschrieben. +
→ Die Firmen, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile der Firma.
. Nimm die Änderungen vor. Beachte dazu die Erläuterungen im Kapitel <<#firma-erstellen, Firma erstellen>> in <<#table-create-company>>.
. *Speichere* die Einstellungen.

[#firma-mit-kontakt-verknuepfen]
== Firma mit Kontakt verknüpfen

TEXT

* Eine Firma einem Kontakt zuweisen
* Eine Firma mehreren Kontakten zuweisen
* Einem Kontakt eine Firma zuweisen
* Mehreren Kontakten eine Firma zuweisen

[#firma-loeschen]
== Firma löschen

Wenn ein Firmendatensatz nicht mehr benötigt wird, kannst du diesen jederzeit löschen. Die Kontaktdatensätze, die mit der Firma verknüpft sind, werden selbstverständlich _nicht_ gelöscht. Lediglich die Zuordnung Firma/Kontakt wird beim Löschen der Firma entfernt.
// und in der Kontakt-UI wird die Firma auch entfernt.

[.instruction]
Firma löschen:

. Öffne das Menü *CRM » Firmen*.
. Suche die Firma, du die löschen möchtest anhand der Filtereinstellungen wie im Kapitel <<#firma-bearbeiten, Firma bearbeiten>> beschrieben.
→ Die Firmen, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile der Firma.
