= Kontakte verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kontakt, Kunde, Adressen, Rechnungsadresse, Lieferadresse, primär,
:description: Erfahren Sie, wie Sie in plentymarkets Kontakte erstellen und verwalten.
:position: 15



[IMPORTANT]
.Hinweis zur Handbuchseite Kontakte verwalten
====
Auf dieser Handbuchseite werden alle Einstellungen, die im Menü *CRM » Kontakte* im Terra-Backend über den zentralen Login-Bereich zur Verfügung stehen, beschrieben. Die Handbuchseite <<crm/kundendaten-verwalten#, *Kundendaten verwalten*>>, die die Einstellungen in den Menüs *Kunden » Kunden bearbeiten* und *System » Kunden* beschreibt, steht parallel zur Verfügung. Wenn das neue Menü *CRM » Kontakte* das alte Menü *Kunden » Kunden bearbeiten* vollständig ersetzt, wird das Menü *Kunden » Kunden bearbeiten* abgeschaltet und somit auch die Handbuchseite *Kundendaten verwalten* entfernt.
====

Im Menü *CRM » Kontakte* erstellen Sie Datensätze zu Kontakten und speichern dort alle Informationen. Sie können Ihre Kontakte in diesem Menü bearbeiten und löschen sowie Adressen, Aufträge, Tickets, Notizen und Umsätze Ihrer Kontakte anzeigen, neue Adressen, Aufträge, Tickets und Notizen hinzufügen sowie bestehende Adressen, Tickets und Notizen löschen.

[TIP]
.Hinweise zu Detailansicht, Kontextmenü, Kartenansicht und Tabellenansicht
====
Klickt man auf einen Kontakt, um diesen anzuzeigen oder zu bearbeiten, öffnet sich die Detailansicht des Kontakts. Über das Kontextmenü im linken Bereich des Kontakts können Ansichten wie *Adressen* oder *Neue Adresse* aufgerufen werden.

Klickt man z.B. auf *Adressen* werden alle zu dem Kontakt gespeicherten Adressen initial als Karten angezeigt. Mit einem Klick auf *Zur Tabellenansicht wechseln* werden die Adressen in Tabellenform angezeigt. Aus dieser Ansicht wechselt man zurück mit einem Klick auf *Zur Kartenansicht wechseln*. Ihr plentymarkets System merkt sich, welche der beiden Ansichten Sie gewählt haben und zeigt beim nächsten Öffnen des Kontextmenüs *Adressen* die zuletzt gewählte Ansicht an.

Wenn mehr als eine Ansicht des Kontakts geöffnet ist, erscheint in der Ansicht oben ein Dreieck, über das man zwischen den geöffneten Kontakten einfach und schnell hin- und herwechseln kann. Mit einem Klick auf das Kreuz wird der Kontakt geschlossen und aus der Liste entfernt.

Über die Ansicht *Übersicht* gelangt man zurück in die Übersicht der gefundenen Kontakte. Aus dieser Ansicht heraus lassen sich beliebig viele weitere Kontakte aufrufen. Wenn mehr als ein Kontakt geöffnet ist, erscheint in der Ansicht des gerade geöffneten Kontakts ein Dreieck, über das man die Kontakte, die bereits einmal geöffnet waren, einfach und schnell aufrufen kann. Mit einem Klick auf das Kreuz wird der Kontakt geschlossen und aus der Liste entfernt.
====

[#50]
== Sichtbarkeit für variablen Benutzer einstellen

Damit für Benutzer mit der Benutzerklasse *Variabel* das Menü *CRM » Kontakte* sichtbar ist, muss das Menü im Benutzerkonto freigeschaltet werden. Für Benutzer mit der Benutzerklasse *Admin* ist die Sichtbarkeit des Menüs *CRM » Kontakte* standardmäßig aktiviert.

[.instruction]
Sichtbarkeit für variablen Benutzer einstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den Benutzer mit der Benutzerklasse *Variabel*, für den Sie die Sichtbarkeit des Menüs aktivieren möchten.
. Wechseln Sie in das Tab *Berechtigung*.
. Wechseln Sie in das Tab *Menü*.
. Klappen Sie den Bereich *Kunden* auf.
. Aktivieren Sie die Option *Contacts*.
. *Speichern* Sie die Einstellung.


[#100]
== Kontakt erstellen

Gehen Sie wie im Folgenden beschrieben vor, um einen neuen Kontakt zu erstellen. Fügen Sie Kontaktoptionen wie z.B. E-Mail-Adressen, Telefonnummern und ggf. die USt-IdNr. hinzu. Sie können einen neuen Kontakt beispielsweise auch während einer telefonischen oder schriftlichen Bestellung erstellen oder die Daten eines Interessenten speichern. Beim Erstellen eines Kontakts wird vom System automatisch eine ID vergeben. Diese ID kann nicht geändert werden.

[.instruction]
Kontakt erstellen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Klicken Sie auf *Neuen Kontakt erstellen*.
. Nehmen Sie die Einstellungen im Bereich *Neuer Kontakt* vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. Wählen Sie im Bereich *Kontaktoptionen* den Typ und Subtyp aus den Dropdown-Menüs und geben Sie den Wert ein. Beachten Sie dazu die Erläuterungen in Tabelle 1. +
→ Mit einem Klick auf *Kontaktoption hinzufügen* fügen Sie weitere Kontaktoptionen hinzu.
. *Speichern* Sie die Einstellungen. +
→ Die Kontakt wird hinzugefügt.

.Kontakt erstellen
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|*Neuer Kontakt*

|*Anrede*
|Option aus dem Dropdown-Menü wählen. Die Auswahl ist optional. +
*Frau* = Weibliche Anrede +
*Herr* = Männliche Anrede

|*Titel*
|Ggf. Titel des Kontakts eingeben.

|*Vorname*, *Nachname*
|Vorname und Nachname des Kontakts eingeben.

|*Mandant (Shop)*
|Mandant (Shop) aus dem Dropdown-Menü wählen, um den Kontakt diesem Mandanten zuzuordnen. +
Es werden nur Mandanten angezeigt, für die im Menü *System » Mandant (Shop)* in den *Grundeinstellungen* des Mandanten ein Name eingegeben ist.

|*Sprache*
|Sprache für den Kontakt wählen. Es werden z.B. Rechnungsdokumente in dieser Sprache erstellt, wenn Sie eine Vorlage für die Sprache angelegt haben.

|*Typ*
|Typ wählen. Standardmäßig können die Typen *Kunde*, *Handelsvertreter*, *Lieferant*, *Partner*, *Hersteller* und *Interessent* gewählt werden. Eigene Typen erstellen Sie im Menü <<crm/kundendaten-verwalten#300, *System » Kunden » Typen*>>.

|*Klasse*
|Klasse wählen. Klassen dienen zur internen Unterscheidung und z.B. ob und welcher Rabatt dieser Klasse gewährt werden soll. Klassen werden im Menü <<crm/kundendaten-verwalten#100, *System » Kunden » Kundenklassen*>> erstellt. Soll zum Beispiel zwischen Endkunden und Händlern bei der Preisanzeige im Online-Shop unterschieden werden, kann dies über die Option *Anzeige der Preise im Online-Shop* in der Konfiguration der Klassen vorgenommen werden. Bei Endkunden (B2C) werden die Bruttopreise im Online-Shop angezeigt. Bei Händlern (B2B) werden die Nettopreise im Online-Shop angezeigt. +
Leere Option = Keine Zuordnung zu einer Klasse +
*_Wichtig:_* Wenn keine Zuordnung zu einer Klasse erfolgt, wird ein Kontakt automatisch der Klasse mit der niedrigsten Position zugeordnet. Da pro Klasse auch die Preisdarstellung im Online-Shop konfiguriert wird, diese Option bei der Klasse mit der Position 1 prüfen, damit bei automatischen Zuweisungen auch die gewünschte Preisdarstellung erfolgt.

|*Bewertung*
|Kontakt für interne Zwecke bewerten. Fünf rote Sterne stehen für die schlechteste und fünf gelbe Sterne für die beste Bewertung.

|*Kundennummer*
|Kundennummer für den Kontakt eingeben. Die Kundennummern können fortlaufend nummeriert werden oder nicht. Kundennummern werden nicht automatisch vergeben.

|*Eigner*
|Eigner für den Kontakt wählen. Wenn kein Eigner gewählt werden soll, die leere Option wählen.

|*Geburtsdatum*
|Geburtsdatum des Kontakts nach dem Muster dd.mm.yyyy eingeben oder aus dem Kalender wählen.

|*Newsletter*
|Zeigt an, ob der Kontakt den Newsletter erhält. Es ist nicht möglich, die Option manuell zu aktivieren. Um den Newsletter-Bezug für den Kontakt zu deaktivieren, auf *Newsletter löschen* klicken.

|*Gesperrt*
|Wählen, ob der Kontakt für den eingestellten Mandanten (Shop) gesperrt wird oder nicht. +
Wenn die Option aktiviert ist, ist der Kontakt gesperrt und kann sich nicht mehr im Online-Shop einloggen. Wenn die Option deaktiviert ist, kann sich der Kontakt im Online-Shop einloggen.

2+|*Kontaktoptionen*

|*Typ*
|Typ, z.B. E-Mail, Telefon oder Webseite, aus dem Dropdown-Menü wählen.

|*Subtyp*
|Subtyp, z.B. Arbeit, Privat oder Ansprechpartner, aus dem Dropdown-Menü wählen.

|*Wert*
|Wert eingeben.
|====

[#200]
== Kontakt suchen

In der Ansicht *Filter* haben Sie die Möglichkeit, Kontakte nach bestimmten Kriterien zu suchen. Die gefundenen Kontakte werden dann in der Ansicht *Übersicht* angezeigt. In der Übersicht werden aktuell die folgenden Informationen angezeigt: ID, Firma, Vorname, Nachname, E-Mail-Adresse, Telefonnummer, Anzahl der Aufträge, Postleitzahl und Land. Wie Sie Kontaktdaten bearbeiten, ist im Kapitel <<crm/kontakte-verwalten#300, *Kontakt bearbeiten*>> beschrieben.

[TIP]
.E-Mails direkt aus der Übersicht heraus versenden
====
Senden Sie Ihrem Kontakt direkt aus der Kontaktübersicht heraus eine E-Mail. Mit einem Klick auf die E-Mail-Adresse öffnet sich Ihr E-Mail-Programm automatisch.
====

Um bestimmte Kontakte zu suchen, geben Sie die Ihnen bekannten Suchbegriffe in die Filter ein oder wählen Sie die Einstellungen der Dropdown-Menüs. Sie können dabei auch mehrere Suchbegriffe gleichzeitig in die Suchfelder eingeben. Dies ermöglicht Ihnen eine schnellere und genauere Suche.

[.instruction]
Kontakt suchen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Geben Sie in der Ansicht *Filter* Suchbegriffe in die Suchfelder ein bzw. stellen Sie Filteroptionen in den Dropdown-Menüs ein. Beachten Sie dazu die Erläuterungen in Tabelle 2.
. Klicken Sie auf *Suchen*. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet. Alternativ öffnen Sie das Kontextmenü mit einem Rechtsklick, um die Ansichten des Kontakts direkt aufzurufen.

.Filter für die Kontakte
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Ohne gewählte Filtereinstellungen auf *Suchen* klicken, um alle Kontakte anzuzeigen. Alternativ die Suchergebnisse durch Filtereinstellungen eingrenzen und auf *Suchen* klicken. Die gefundenen Kontakte werden in der Übersicht angezeigt.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*ID*
|Jeder Kontakt erhält automatisch eine fortlaufende und einzigartige ID. Dies ist unabhängig davon, ob der Eintrag manuell oder automatisch angelegt wurde. Zwei Kontakte haben somit nie die gleiche ID. Die ID entspricht immer einer echten Zahl. Ungültig sind z.B. "00521" oder "ADF8354".

|*Name*
|Vorname und/oder Nachname oder Firmenname eingeben, um den Kontakt mit diesem Namen bzw. Firmennamen zu suchen. Es wird auch nach Namen und Firmennamen, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen des Namens bzw. Firmennamens zu suchen.

|*Anschrift*
|Straßenname und/oder Hausnummer eingeben, der im Kontakt gespeichert ist. Es ist möglich, nur nach Teilen des Straßennamens und Teilen der Hausnummer zu suchen.

|*PLZ*
|Postleitzahl, die im Kontakt gespeichert sind, eingeben. Es wird auch nach Postleitzahlen, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen der Postleitzahl zu suchen.

|*Ort*
|Ort, der im Kontakt gespeichert ist, eingeben. Es wird auch nach Orten, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen des Ortsnamens zu suchen.

|*E-Mail*
|E-Mail-Adresse eingeben, um den Kontakt mit dieser E-Mail-Adresse zu suchen. Es ist möglich, nur nach Teilen der E-Mail-Adresse zu suchen.

|*Land*
|Land wählen, um nur Kontakte aus diesem Land anzuzeigen. Das Land ist in den Kontaktdaten gespeichert.

|*Eigner*
|Eigner wählen, um nur Kontakte von diesem Eigner anzuzeigen. Der Eigner muss in den Kontaktdaten gespeichert sein. +
*_Wichtig:_* Es werden im Dropdown-Menü nur Benutzer angezeigt, bei denen im Benutzerkonto im Tab *Eigner* die Option *Kunde* aktiviert ist.

|*Typ*
|Typ wählen, um nur Kontakte mit diesem Typ anzuzeigen.

|*Mandant (Shop)*
|Mandant (Shop) wählen, um nur Kontakte dieses Mandanten anzuzeigen. Der Mandant ist in den Kontaktdaten gespeichert. +
*_Wichtig:_* Variablen Benutzern stehen nur Mandanten zur Auswahl, für die sie eine Berechtigung haben. Berechtigungen werden im Tab <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90, *Berechtigung*>> unter *System » Einstellungen » Benutzer » Konten* eingestellt.

|*Herkunft*
|Herkunft wählen, um nur Kontakte mit dieser Herkunft anzuzeigen.
|====

[#300]
== Kontakt bearbeiten

Suchen Sie den Kontakt anhand der <<crm/kontakte-verwalten#200, *Filtereinstellungen*>>. Öffnen Sie den Kontakt durch einen Klick in die Zeile des Kontakts, um dessen Daten, wie z.B. Sprache, Klasse, Geburtsdatum, Telefonnummer und E-Mail-Adresse, zu bearbeiten. Erläuterungen zu den Einstellungen und Optionen in den Bereichen *Kontakt* und *Kontaktoptionen* finden Sie im Kapitel <<crm/kontakte-verwalten#100, *Kontakt erstellen*>>. Kontaktoptionen löschen Sie mit einem Klick auf *Kontaktoption löschen*.

[.instruction]
Kontakt bearbeiten:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Nehmen Sie die Änderungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1 im Kapitel <<crm/kontakte-verwalten#100, *Kontakt erstellen*>>.
. *Speichern* Sie die Einstellungen.

[#400]
== Kontakt löschen

Sie haben die Möglichkeit, einzelne Kontakte zu löschen. Ein Kontakt kann nur gelöscht werden, sofern dieser nicht mit einem Auftrag verknüpft ist.

[.instruction]
Kontakt löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Kontakt löschen* oder klicken Sie auf *Löschen* oberhalb der Detailansicht. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Der Kontakt wird gelöscht und aus der Übersicht entfernt.

[#500]
== Historie anzeigen

In jedem Datensatz können Sie die Historie eines Kontakts einsehen. Die Historie beinhaltet z.B. das Datum, seit dem der Kontakt bei Ihnen registriert ist, wann er das letzte Mal in Ihrem Online-Shop eingeloggt war und wann der letzte Auftrag generiert wurde. Die Daten werden automatisch angepasst und können nicht geändert werden.

[.instruction]
Historie anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet und die Historie wird im rechten Bereich unterhalb der *Kontaktoptionen* angezeigt.
. Beachten Sie die Erläuterungen zur Historie in Tabelle 3.

.Historie im Menü *CRM » Kontakte » Kontakt öffnen*
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Registriert seit*
|Datum und Uhrzeit, seit wann der Kontakt registriert ist.

|*Aktualisiert*
|Datum und Uhrzeit, wann die Daten des Kontakts das letzte Mal aktualisiert wurden.

|*Zugangsart*
|Art, wie sich der Kontakt registriert hat. +
*Regulärer Zugang* = Der Kontakt hat sich neu registriert bzw. der Datensatz wurde manuell im Backend erstellt. +
*Gastzugang* = Der Kontakt hat sich als Gast angemeldet und bestellt.

|*Letzter Auftrag*
|Datum und Uhrzeit, wann der letzte Auftrag eingegangen ist. Wenn kein Auftrag eingegangen ist, steht in diesem Feld *Keine Daten*.

|*Letzter Login*
|Datum und Uhrzeit des letzten Login. Wenn kein Login stattgefunden hat, steht in diesem Feld *Keine Daten*.
|====

[#600]
== Adresse hinzufügen

Fügen Sie einem Kontakt beliebig viele Adressen sowie Adressoptionen wie z.B. die Umsatzsteuer-Identifikationsnummer oder die Telefonnummer des Kontakts hinzu.

[.instruction]
Adresse hinzufügen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Neue Adresse*.
. Nehmen Sie die Einstellungen im Bereich *Neue Adresse* vor. Beachten Sie dazu die Erläuterungen in Tabelle 4.
. Wählen Sie im Bereich *Adressoptionen* den Typ aus dem Dropdown-Menü und geben Sie den Wert ein. Beachten Sie dazu die Erläuterungen in Tabelle 4. +
→ Mit einem Klick auf *Adressoption hinzufügen* fügen Sie weitere Adressoptionen hinzu.
. *Speichern* Sie die Einstellungen. +
→ Die Adresse wird der Übersicht im Bereich *Adressen* hinzugefügt.

.Adresse hinzufügen
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|*Neue Adresse*

|*Name 1 (Firma)*
|Firmenname eingeben. Dies ist ein Pflichtfeld, wenn unter *Vorname* und *Nachname* kein Eintrag gemacht wird.

|*Name 2 (Vorname)*
|Vorname des Kontakts eingeben. Dies ist ein Pflichtfeld, wenn unter *Firma* und *Nachname* kein Eintrag gemacht wird.

|*Name 3 (Nachname)*
|Nachname des Kunden eingeben. Dies ist ein Pflichtfeld, wenn unter *Firma* und *Vorname* kein Eintrag gemacht wird.

|*Name 4 (Zusatz)*
|Ggf. Zusatzangaben zum Kontakt eingeben, z.B. z.Hd. Herrn Max Mustermann.

|*Adresse 1 (Straße)* +
*Adresse 2 (Hausnummer)*
| Straße und Hausnummer eingeben. +
*Straße* ist ein Pflichtfeld, wenn unter *Hausnummer* und *Adresszusatz* kein Eintrag gemacht wird. *Hausnummer* ist ein Pflichtfeld, wenn unter *Straße* und *Adresszusatz* kein Eintrag gemacht wird.

|*Adresse 3 (Adresszusatz)*
|Ggf. Adresszusatz eingeben, z.B. Apartment 12a. Dies ist ein Pflichtfeld, wenn unter *Straße* und *Hausnummer* kein Eintrag gemacht wird.

|*Adresse 4 (Frei)*
|Feld zur freien Verfügung.

|*Postleitzahl* +
*Ort*
|Postleitzahl und Ort des Kontakts eingeben. Diese Angaben werden z.B. für die Rechnungsadresse verwendet. Bei bestimmten Ländern, z.B. Vereinigtes Königreich, wird die Reihenfolge der Optionen *Postleitzahl* und *Ort* getauscht. +
*Postleitzahl* und *Ort* sind Pflichtfelder.

|*Land* +
*Region/Bezirk*
|Werte aus den Dropdown-Menüs wählen. +
*_Wichtig:_* Das Dropdown-Menü *Region/Bezirk* ist nicht für alle Länder verfügbar.

|*Rechnungsadresse* / *Lieferadresse*
|Eine oder beide Optionen aktivieren, um den Adresstyp festzulegen. +
Die neue Adresse kann entweder nur Rechnungsadresse, nur Lieferadresse oder sowohl Rechnungsadresse als auch Lieferadresse sein. Wenn beide Optionen aktiviert sind, wird eine Adresse mit einer neuen ID und zwei Adresstypen erstellt. +
Sobald eine oder beide Optionen aktiviert sind, kann man für eine oder beide Optionen wählen, ob es sich um die primäre Adresse handelt.

|*Primär*
|Option aktivieren, wenn es sich bei der neuen Adresse um die primäre Rechnungsadresse bzw. primäre Lieferadresse handelt. +
Es ist möglich, beide Optionen zu aktivieren, wenn es sich bei der neuen Adresse sowohl um die primäre Rechnungsadresse als auch um die primäre Lieferadresse handelt.

2+|*Adressoptionen*

|*Typ*
|Typ, z.B. Postnummer oder Umsatzsteuer-Identifikationsnummer, aus dem Dropdown-Menü wählen.

|*Wert*
|Wert eingeben.
|====

[#700]
== Adressen anzeigen

Aus dem geöffneten Kontakt heraus lassen sich alle dem Kontakt zugehörigen Adressen anzeigen. Neben Informationen wie ID, Firmenname, Vor- und Nachname sowie Adresse und Land sehen Sie außerdem, um welchen Adresstyp es sich handelt – Rechnungsadresse oder Lieferadresse – und ob die Adresse eine primäre Adresse ist.

Wenn mehrere Adressen geöffnet sind, werden im Dropdown-Menü der geöffneten Adressen die IDs der Adressen angezeigt.

Initial werden die Adressen Ihres Kontakts in der Kartenansicht angezeigt. Mit einem Klick auf *Zur Tabellenansicht wechseln* werden die Adressen in Tabellenform angezeigt. Ihr plentymarkets System merkt sich, welche der beiden Ansichten Sie gewählt haben und zeigt beim nächsten Öffnen des Kontextmenüs *Adressen* die zuletzt gewählte Ansicht an.

Pro Seite werden bis zu 25 Adressdatensätze zu einem Kontakt angezeigt. Wenn mehr als 25 Adressen zu einem Kontakt gespeichert sind, haben Sie über die Toolbar die Möglichkeit, in den Seiten zu blättern, eine bestimmte Seite zu wählen und die Anzahl der Adressdatensätze pro Seite auf 50, 75 oder 100 zu ändern. Ihr plentymarkets System merkt sich, welche Anzahl der Adressdatensätze Sie gewählt haben und zeigt beim nächsten Öffnen der Adressen die zuletzt gewählte Einstellung an.

[.instruction]
Adressen anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherten Adressen werden angezeigt.
. Klicken Sie auf *Bearbeiten*, um die Detailansicht der Adresse zu öffnen. +
→ Wenn Sie die Tabellenansicht gewählt haben, klicken Sie in die Zeile der Adresse, um die Detailansicht zu öffnen.

[#800]
== Adresse bearbeiten

Sie können bestehende Adressen sowie Adressoptionen jederzeit bearbeiten. Beachten Sie dazu die Erläuterungen im Kapitel <<crm/kontakte-verwalten#600, *Adresse hinzufügen*>>. Adressoptionen löschen Sie mit einem Klick auf *Adressoption löschen*.

[.instruction]
Adressen bearbeiten:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherten Adressen werden inital als Karten angezeigt.
. Klicken Sie in der Adresskarte, die Sie bearbeiten möchten, auf *Bearbeiten*. +
→ Die Detailansicht der Adresse wird geöffnet.
. Nehmen Sie die Änderungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 4 im Kapitel <<crm/kontakte-verwalten#700, *Adresse hinzufügen*>> sowie die Erläuterungen zur Toolbar in Tabelle 5.
. *Speichern* Sie die Einstellungen.

.Adresse bearbeiten
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Speichern*
|Speichert die Einstellungen.

2+|*Rechnungsadresse*

|*Neue Rechnungsadresse ableiten*
|Erstellt eine neue Rechnungsadresse auf Basis der aktuell gewählten Adresse. Um eine neue Adresse mit einer neuen ID zu erstellen, müssen Änderungen an der neuen Rechnungsadresse vorgenommen werden.

|*Rechnungsadresstyp hinzufügen*
|Fügt den Typ *Rechnungsadresse* zu der Adresse hinzu. Die ID ändert sich nicht. +
Diese Einstellung ist nicht sichtbar, wenn für die Adresse bereits der Typ *Rechnungsadresse* hinzugefügt wurde.

|*Rechnungsadresstyp löschen*
|Löscht den Typ *Rechnungsadresse* in der Adresse. +
Diese Einstellung ist nicht sichtbar, wenn der Typ *Rechnungsadresse* nicht für die Adresse hinzugefügt wurde.

|*Als primäre Rechnungsadresse definieren*
|Setzt die aktuell gewählte Rechnungsadresse als primäre Rechnungsadresse. Die ID ändert sich nicht. +
Wenn der Typ *Rechnungsadresse* nicht vorhanden ist, ist diese Option deaktiviert. +
Wenn die Rechnungsadresse als primär definiert wurde, kann man dies mit einem Klick auf *Primäre Rechnungsadresse zurücksetzen* wieder rückgängig machen.

|*In Rechnungsadresse umwandeln* / +
*In Lieferadresse umwandeln*
|Wandelt die aktuell gewählte Adresse in die Rechnungsadresse bzw. Lieferadresse um. Die ID ändert sich nicht. +
Wenn beide Adresstypen bereits vorhanden sind, ist diese Option deaktiviert.

2+|*Lieferadresse*

|*Neue Lieferadresse ableiten*
|Erstellt eine neue Lieferadresse auf Basis der aktuell gewählten Adresse. Um eine neue Adresse mit einer neuen ID zu erstellen, müssen Änderungen an der neuen Lieferadresse vorgenommen werden.

|*Lieferadresstyp hinzufügen*
|Fügt den Typ *Lieferadresse* zu der Adresse hinzu. Die ID ändert sich nicht. +
Diese Einstellung ist nicht sichtbar, wenn für die Adresse bereits der Typ *Lieferadresse* hinzugefügt wurde.

|*Lieferadresstyp löschen*
|Löscht den Typ *Lieferadresse* in der Adresse. +
Diese Einstellung ist nicht sichtbar, wenn der Typ *Lieferadresse* nicht für die Adresse hinzugefügt wurde.

|*Als primäre Lieferadresse definieren*
|Setzt die aktuell gewählte Lieferadresse als primäre Lieferadresse. Die ID ändert sich nicht. +
Wenn der Typ *Lieferadresse* nicht vorhanden ist, ist diese Option deaktiviert. +
Wenn die Lieferadresse als primär definiert wurde, kann man dies mit einem Klick auf *Primäre Lieferadresse zurücksetzen* wieder rückgängig machen.

|*Adressdatensatz löschen*
|Löscht den Adressdatensatz vollständig.
|====

[#900]
== Adresse löschen

Sofern es sich bei der Adresse nicht um eine mit einem Auftrag verknüpfte Rechnungsadresse handelt, können Sie Adressen löschen. Dies ist z.B. nötig, wenn die Lieferadresse des Kontakts nicht mehr aktuell ist.

[NOTE]
.Löschen von Rechnungsadressen, die mit Aufträgen verknüpft sind, ist nicht möglich
====
Wenn die Adresse vom Typ *Rechnungsadresse* ist und mit einem Auftrag verknüpft ist, können Sie die Adresse nicht löschen. Eine Fehlermeldung erscheint.
====

[.instruction]
Adresse löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherte Adressen werden inital als Karten angezeigt. +
. Klicken Sie in der Adresskarte, die Sie löschen möchten, auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Die Adresse wird gelöscht und aus der Übersicht entfernt.

[#1000]
== Aufträge anzeigen

Aus dem geöffneten Kontakt heraus können Sie alle Aufträge des Kontakts im Menü *Aufträge » Aufträge bearbeiten* aufrufen. Beim Wechsel in das Menü wird in der Auftragssuche automatisch initial auch nur nach Aufträgen von Kontakten mit der ID gesucht.

[.instruction]
Aufträge anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Aufträge*. +
→ Alle zu dem Kontakt gespeicherten Aufträge werden im Menü *Aufträge » Aufträge bearbeiten* angezeigt. +
. Klicken Sie in die Zeile des Auftrags, um nähere Informationen einzusehen.

Sie können den Auftrag auch bearbeiten. Aufträge können solange bearbeitet werden, bis ein Dokument für diesen Auftrag existiert. Weitere Informationen zu Aufträgen finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/auftraege-verwalten, *Aufträge verwalten*>>.

[#1100]
== Auftrag anlegen

Mit einem Klick haben Sie die Möglichkeit aus dem geöffneten Kontakt heraus manuell einen neuen Auftrag für den Kontakt anzulegen. Wenn der Kontakt im Online-Shop bestellt, wird der Auftrag automatisch in Ihrem plentymarkets System gespeichert. Bei telefonischen Bestellungen beispielsweise legen Sie den Auftrag manuell an. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Auftrag anlegen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Neuer Auftrag*. +
→ Sie gelangen direkt in den Bereich *Neuer Auftrag* im Menü *Aufträge » Aufträge bearbeiten*. +
. Nehmen Sie die Einstellungen vor. Beachten Sie die Informationen auf der Handbuchseite <<auftragsabwicklung/auftraege/auftraege verwalten#, *Aufträge verwalten*>>.
. *Speichern* Sie die Einstellungen.

[#1150]
== Scheduler anzeigen

In der Ansicht *Scheduler* werden Abo-Aufräge des Kontakts angezeigt. Außerdem können neue Scheduler-Aufträge angelegt werden. Über den Scheduler haben Ihre Kunden die Möglichkeit, bestimmte Artikel in Ihrem Online-Shop im Abonnement zu kaufen. Das Menü ist nur in Ihrem plentymarkets System sichtbar, wenn Sie es gebucht haben. Die Buchung nehmen Sie im Menü *Start » plentymarkets Konto » Service-Center » Tab: Vertrag* vor. Im Menü *System » Aufträge » Scheduler* nehmen Sie die Einstellungen für Ihren Online-Shop vor.

[.instruction]
Scheduler anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Scheduler*. +
 → Alle zu dem Kontakt verfügbaren Abonnements werden angezeigt.
. Beachten Sie die Erläuterungen auf der Handbuchseite <<auftragsabwicklung/auftraege/scheduler#, *Scheduler* >>.

Weitere Informationen finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/scheduler#, *Scheduler* >>. Dort sind auch die Filteroptionen beschrieben, die Sie sowohl im Menü *CRM » Kontakte » Kontakt öffnen » Ansicht: Scheduler* als auch im Menü *Aufträge » Scheduler » Scheduler-Aufträge* wählen können.


[#1200]
== Ticket erstellen

Das <<crm/ticketsystem-nutzen#, *Ticketsystem*>> in plentymarkets nutzen Sie zur Verwaltung Ihrer Kundenkommunikation. Erfahren Sie im Folgenden, wie Sie ein neues Ticket direkt aus dem geöffneten Kontakt heraus erstellen.

[.instruction]
Ticket erstellen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Neues Ticket*. +
→ Sie gelangen direkt in den Bereich *Neues Ticket* im Menü *CRM » Ticketsystem*. Die Kontakt-ID ist bereits vorausgefüllt. +
. Nehmen Sie die Einstellungen vor. Beachten Sie die Informationen auf der Handbuchseite <<crm/ticketsystem-nutzen#1600, *Ticketsystem nutzen*>>.
. *Speichern* Sie die Einstellungen.


[#1300]
== Tickets anzeigen

Aus dem geöffneten Kontakt heraus können Sie alle zu dem Kontakt gespeicherten Tickets im Menü *CRM » Ticketsystem* aufrufen. Beim Wechsel in das Menü wird in der Ticketsuche automatisch initial auch nur nach Tickets von Kontakten mit der ID gesucht.

[.instruction]
Tickets anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Tickets*. +
→ Alle zu dem Kontakt gespeicherten Tickets werden angezeigt.

Sie haben die Möglichkeit Tickets zu bearbeiten und zu löschen. Beachten Sie dazu die Handbuchseite <<crm/ticketsystem-nutzen#, *Ticketsystem nutzen*>>.

[#1400]
== Notiz erstellen

Sie können zu jedem Ihrer Kontakte beliebig viele Notizen speichern. Notizen sind nur in Ihrem plentymarkets Backend sichtbar, d.h. Kontakte können die gespeicherten Notizen nicht im Online-Shop sehen. Jede Notiz erhält nach dem Speichern eine fortlaufende ID. Neue Texte geben Sie über die Tastatur ein oder fügen Sie über die Zwischenablage ein. Mit den Funktionen in der Symbolleiste können Sie den Text formatieren, Verlinkungen einfügen sowie Bilddateien hochladen.

[.instruction]
Notiz erstellen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Neue Notiz*. +
→ Das Fenster *Neue Notiz* wird geöffnet.
. Geben Sie den Text ein, fügen Sie Text über die Zwischenablage ein und formatieren Sie ggf. den Text mit den Funktionen in der Symbolleiste.
. *Speichern* Sie die Einstellungen. +
→ Der Bereich *Notizen* wird geöffnet und die Notiz wird der Übersicht hinzugefügt.


[#1500]
== Notizen anzeigen

Aus dem geöffneten Kontakt heraus lassen sich alle zu dem Kontakt gespeicherten Notizen in Form von Karten anzeigen. Die Karten zeigen das Erstellungsdatum mit Uhrzeit, den Benutzernamen, der die Notiz erstellt hat, und die ID an.

[.instruction]
Notizen anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Notizen*. +
→ Alle zu dem Kontakt gespeicherten Notizen werden angezeigt.

[.subhead]
Einzelne Notiz öffnen

Sie können einzelne Notizen mit einem Klick auf *Vorschau öffnen* anzeigen. Wenn mehr als eine Notiz des Kontakts geöffnet ist, erscheint in der Ansicht ein Dreieck, über das man zwischen den geöffneten Notizen einfach und schnell hin- und herwechseln kann. Mit einem Klick auf das Kreuz wird die Notiz geschlossen und aus der Liste entfernt.



[#1600]
== Notiz bearbeiten

Bearbeiten Sie Notizen, um Inhalte zu aktualisieren. Sie haben die Möglichkeit, den Text zu formatieren, Verlinkungen einzufügen und Bilddateien hochzuladen.

[.instruction]
Notiz bearbeiten:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Notizen*. +
→ Alle zu dem Kontakt gespeicherten Notizen werden angezeigt.
. Klicken Sie in der Notiz, die Sie bearbeiten möchten, auf *Bearbeiten*.
. Nehmen Sie die Änderungen vor.
. *Speichern* Sie die Einstellungen.


[#1700]
== Notiz löschen

Die Notizen Ihrer Kontakte können jederzeit gelöscht werden, wenn die darin gespeicherten Informationen veraltet sind oder Sie diese nicht mehr benötigen.

[.instruction]
Notiz löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Notizen*. +
→ Alle zu dem Kontakt gespeicherten Notizen werden angezeigt.
. Klicken Sie in der Notiz, die Sie löschen möchten, auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicken Sie auf *Löschen*. +
→ Die Notiz wird gelöscht und aus der Übersicht entfernt.

Sie können die Notiz auch löschen, wenn die Vorschau geöffnet ist. Dazu klicken Sie in der geöffneten Notiz auf *Löschen*. In diesem Fall erscheint ebenfalls eine Sicherheitsabfrage, die Sie mit *Löschen* bestätigen müssen.


[#1800]
== Kontostand anzeigen

In der Ansicht *Konto* sehen Sie die Umsätze Ihres Kontakts. In der obersten Zeile sehen Sie neben dem Kontostand des Kontakts die Summe der Rechnungen des Kontakts, was Sie ihm in Form von Gutschriften gutgeschrieben haben und wie hoch die Differenz zwischen diesen beiden Beträgen ist. 
In der Tabelle sind die Aufträge und Gutschriften zu diesem Kunden als Vorgänge aufgeführt. Dabei sind die Spalten *Gezahlt* und *Ausstehend* besonders hilfreich. Wenn bei einem Auftrag ein Betrag unter *Ausstehend* aufgeführt ist, muss der Kontakt diesen Betrag noch an Sie zahlen. Sobald dies geschehen ist, wird der Betrag unter *Gezahlt* aufgeführt. Wenn bei einer Gutschrift noch ein Betrag unter *Ausstehend* aufgeführt ist, müssen Sie diesen Betrag noch an den Kontakt zahlen. Sobald dies geschehen ist, wird der Betrag unter *Gezahlt* aufgeführt.

[.instruction]
Kontostand anzeigen: 

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kunden anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Konto*. +
→ Alle verfügbaren Daten zum Kontostand des Kontakts werden angezeigt.
. Beachten Sie die Erläuterungen in Tabelle 6. 

.Einstellungen im Menü CRM » Kontakte » Ansicht: Konto
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Saldo*
|Zeigt den Kontostand des Kontakts an. +
+ = Summe der noch vom Kontakt zu zahlenden Beträge +
- = Summe der noch an den Kontakt zu zahlenden Beträge, wenn der Kontakt zu viel gezahlt hat oder eine Gutschrift noch ausgezahlt werden muss. +
0,0 = keine ausstehenden Beträge

|*Rechnungen*
|Summe der Rechnungsbeträge aller Aufträge und die Anzahl der Rechnungen in Klammern

|*Gutschriften*
|Summe aller Gutschriften und die Anzahl der Gutschriften in Klammern

|*Delta*
|Differenz in Prozent zwischen den gezahlten Gutschriften und dem insgesamt bezahlten Rechnungsbetrag des Kontakts. Bei 0 % wurde dem Kontakt noch keine Gutschrift ausgezahlt. Bei 100 % wurde dem Kontakt jeder bezahlte Betrag wieder als Gutschrift zurückgezahlt.

|*Datum*
|Datum, an dem der Auftrag erstellt wurde

|*Auftrags-ID*
|ID des Auftrags. Ein Klick auf die ID öffnet die Detailansicht des Auftrags. IDs von Gutschriften sind eingerückt und unterhalb des Auftrags dargestellt.

|*Vorgang*
|Auftragsart, entweder Auftrag oder Gutschrift

|*Dokument*
|Dokumentennummer, z.B. Rechnungsnummer. Ein Klick auf die Nummer öffnet das Dokument.

|*Wert*
|Rechnungssumme des Auftrags

|*Gezahlt*
|Der bereits bezahlte Betrag

|*Zahlungsart*
|Zahlungsart des Auftrags

|*Ausstehend*
|Der zur vollständigen Bezahlung des Auftrags noch ausstehende Betrag.

|*Status*
|Status des Auftrags. Ein Klick auf den Status öffnet das Bearbeitungsfenster *Auftragsstatus*, in dem der Status geändert werden kann.

|====

[.subhead]
Kontodaten filtern 

Verwenden Sie Filter, um den Kontostand Ihres Kontakts anzuzeigen.

[.instruction]
Kontodaten filtern:

. Öffnen Sie das Menü *CRM » Konto*.
. Suchen Sie den Kunden anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, *Kontakt suchen*>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf *Konto*. +
→ Alle verfügbaren Daten zum Kontostand des Kontakts werden angezeigt.
. Nehmen Sie die Filtereinstellungen im Bereich *Filter* vor. Beachten Sie dazu die Erläuterungen in Tabelle 7.
. Klicken Sie auf *Suchen*. 

.Filtereinstellungen im Menü *CRM » Kontakte » Ansicht: Konto*
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Suche ausführen. Die gefundenen Kontodaten werden aufgelistet.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*Zeitraum*
|Eine der folgenden Einstellungen aus dem Dropdown-Menü wählen: *ALLE*, *Dieses Jahr*, *Letztes Jahr*, *Diesen Monat*, *Letzten Monat* oder *Letzte 3 Monate*.

|*Ausstehend*
|*ALLE*, *Ja* oder *Nein* wählen.
*Ja* = Nur ausstehende Beträge werden angezeigt. +
*Nein* = Nur gezahlte Beträge werden angezeigt. +
*ALLE* = Ausstehende und gezahlte Beträge werden angezeigt.

|*Vergleichsoperator / Status*
|Vergleichsoperator und Auftragsstatus aus den Dropdown-Menüs wählen.

|*Rechnungsnr.*
|Rechnungsnummer eingeben.

|*Auftrags-ID*
|Auftrags-ID eingeben.

|====
