= Kontakte (Testphase)
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:position: 0
:url: crm/kontakte
:id:
:nav-alias: Übersicht
:author: team-crm

// keywords auf den Seiten entsprechend verteilen:
// Kontakt, Kunde, Adresse, primäre Lieferadresse, primäre Rechnungsadresse, Firmen, Firma, Ustidnummer, Ust ID Nummer, Handelsvertreter, Gastzugang, Gastbestellung, eingeloggter Kunde, registrierter Kunde, regulärer Zugang, Passwort ändern, Passwortänderung, Kunde kann sich nicht einloggen, Login entsperren, Bankdaten, Kundenklasse, Kontaktklasse, Kundendaten löschen, Datensatz löschen, Kunde löschen, Kontakt löschen, Adresslayout, Kundentyp, Rabattsystem, Rabatte vergeben, Rabatte für Kundenklasse, Kontaktoption, Adressoption, Provision, Kostenstelle, Kontakte importieren, Kundendaten importieren, Kundendaten exportieren

Die neue Bedienoberfläche *Kontakte (Testphase)* wurde im xx 2021 in einer geschlossenen Betaphase veröffentlicht. Geschlossene Betaphase bedeutet, dass die neue Bedienoberfläche zum Erstellen und Verwalten von Kontakten zunächst von einer kleinen Personengruppe getestet wird. Sobald diese Bedienoberfläche weiter ausgereift ist und mögliche Fehler behoben wurden, wird die offene Betaphase beginnen.

In diesem Themenbereich findest du alle Informationen rund um die neue Bedienoberfläche *Kontakte (Testphase)* im Menü *CRM » Kontakte (Testphase)*. Im Menü *Einrichtung » CRM* nimmst du <<#crm/kontakte/vorbereitende-einstellungen, vorbereitende Einstellungen>> wie das Erstellen von Kundenklassen und Typen vor. Im Menü *CRM » Kontakte (Testphase)* erstellst und bearbeitest du die Datensätze deiner Kontakte und verwaltest dort alle Informationen wie z.B. Adressen, Aufträge, Tickets, Umsätze, Bankdaten und Dokumente.

// einige Wörter aus der Einleitung anschließend verlinken

Das Menü *CRM » Kontakte (Testphase)* ist wie folgt aufgebaut:

// farblich markierten Screenshot einfügen

* *Navigation*: Hier navigierst du durch die einzelnen Bereiche des Menüs. Der aktuell ausgewählte Bereich (blaue Schrift) wird im Hauptfenster rechts angezeigt. Falls du mehrere Kontakte gleichzeitig geöffnet hast, werden diese untereinander angezeigt. Klicke auf icon:bars[], um die Navigationsleiste ein- und auszublenden.
* *Toolbar*: Hier kannst du nach Kontakten <<#kontakt-suchen, suchen>>, die <<#spalten-anpassen, Spalten in der Übersicht anpassen>>, die Ergebnisse pro Seite, die du angezeigt haben möchtest, einstellen und durch die Seiten mit den Kontakten klicken.
* *Hauptfenster*: Hier wird der aktuell geöffnete Bereich angezeigt. 
** *Übersicht*: Wenn du eine Suche ausführst, siehst du die Ergebnisse in einer Übersicht. Die Übersicht liefert auf einen Blick Informationen zu den gefundenen Kontakten. Zum Beispiel siehst du die Namen der Kontakte, die Anzahl der Aufträge und die Kundenklasse. 
** *Detailansicht*: Wenn du einen Kontakt öffnest, werden die Details im Hauptfenster auf der rechten Seite angezeigt. Die Detailansicht eines Kontakts ist in die folgenden Bereiche unterteilt: Allgemein, Primäre Adresse, Dokumente, Eigenschaften, Tags, plentyShop-Login, Aufträge, Adressen, Historie, Bankdaten, Firma, Konto, Messenger, Optionen, Tickets.