= Kontakte verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kontakt, Kunde, Adresse, Adressen, Rechnungsadresse, Lieferadresse, primär, Firmen, Firma, Gastzugang, regulärer Zugang, Events, Eigenschaften, Zugangsdaten, Passwort ändern, Passwortänderung, Login entsperren, Bankdaten, Zugangsdaten
:description: Erfahren Sie, wie Sie in plentymarkets Kontakte, Adressen und Firmen verwalten.
:position: 10

Auf dieser Handbuchseite werden alle Einstellungen, die im Menü *CRM » Kontakte* im Terra-Backend über den zentralen Login-Bereich zur Verfügung stehen, sowie die Einstellungen, die Sie im Menü *System » CRM* vornehmen müssen, beschrieben.

Im Menü *System » CRM* nehmen Sie vorbereitende Einstellungen wie das Erstellen von Kundenklassen und Typen vor. Im Menü *CRM » Kontakte* erstellen und bearbeiten Sie Datensätze Ihrer Kontakte und verwalten dort alle Informationen wie z.B. Adressen, Aufträge, Scheduler-Aufträge, Tickets, Notizen, Umsätze, Bankdaten und Dokumente Ihrer Kontakte.

[#10]
== Vorbereitende Einstellungen vornehmen

Im Menü *System » CRM* nehmen Sie vorbereitende Einstellungen wie das Erstellen von <<crm/kontakte-verwalten#15, Kundenklassen>> und <<crm/kontakte-verwalten#20, Typen>> vor. Außerdem richten Sie in diesem Menü <<crm/kontakte-verwalten#25, Rabatte>> für Ihre Kunden ein.

[#12]
=== Callisto: Erstellen von Kontaktdatensätzen bei Gastbestellungen

Im Menü *System » CRM » Einstellungen* legen Sie über die Dropdown-Liste *Gastbestellungen* fest, ob bei Gastbestellungen, die über Ihren Callisto-Webshop in Ihr System kommen, Kontaktdatensätze erstellt werden oder nicht.

Diese Einstellung greift nicht für Gastbestellungen, die über den Ceres-Webshop in Ihr System kommen. Gastbestellungen, die über Ceres erstellt werden, bestehen lediglich aus der Adresse und dem Auftrag. Es wird kein vollständiger Kontaktdatensatz erstellt.

[#13]
=== Adress-Layout für Lieferschein einrichten

Im Menü *System » CRM » Adress-Layout* werden die statischen Adress-Layouts für Deutschland, Frankreich und das Vereinigte Königreich (UK) für das Auftragsdokument *Lieferschein* aufgelistet. Klicken Sie auf den Info-Button, um zu erfahren, für welche Adressfelder die einzelnen Parameter stehen.

Damit Lieferscheine für die Lieferländer Deutschland, Frankreich und UK automatisch in diesen drei Adress-Layouts ausgegeben werden, müssen Sie eine Einstellung im Lieferschein vornehmen. Ihr plentymarkets System prüft dann automatisch das Lieferland aus dem Auftrag und gibt den Lieferschein in den im Menü *System » CRM » Adress-Layout* aufgelisteten Layout aus. Gehen Sie dazu wie im Folgenden beschrieben vor.

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Lieferschein*.
. Aktivieren Sie im Bereich *Grundeinstellungen:{nbsp}Lieferschein* die Option *Neues Adresslayout*. +
→ Die Option darüber *Aufbau der Rechnungs-/ Lieferanschrift* wird ausgeblendet und die Lieferscheine für die Lieferländer Deutschland, Frankreich und UK werden in den Adresslayouts im Menü *System » CRM » Adress-Layout* ausgegeben.
. *Speichern* Sie die Einstellung.

Aktuell ist diese Einstellung vorerst nur für Lieferscheine verfügbar. Fü weitere Dokumente wird diese Einstellung folgen.

[#15]
=== Kundenklasse erstellen

Mit Kundenklassen unterteilen Sie Ihren Kundenstamm nach unterschiedlichen Kriterien. So können Sie eine Kundenklasse festlegen, die an Endkunden (B2C) angepasst ist und mit deren Einstellungen die Artikel mit Bruttopreisen im Webshop angezeigt werden. Für Händler (B2B) erstellen Sie eine weitere Kundenklasse, mit deren Einstellungen die Artikel mit Nettopreisen im Webshop angezeigt werden. Weitere Optionen, die festgelegt werden können, sind z.B. Rabatte auf den Nettowarenwert, Rabatte auf die Zahlungsart oder Rabattstaffeln, die nur für eine bestimmte Kundenklasse gelten.

Erstellen Sie Kundenklassen im Menü *System » CRM » Kundenklassen*. Die dort erstellten Kundenklassen stehen dann in den Kontaktdatensätzen im Menü *CRM » Kontakte* als Auswahl zur Verfügung.

[TIP]
.Tipp: Typen und Klassen erstellen
====
Für die Einteilung Ihres Kundenstamms in Typen und Klassen ist es empfehlenswert, ein Konzept zu entwickeln, bevor Sie größere Mengen an Kontaktdaten erstellen. Dadurch vermeiden Sie späteren Änderungsaufwand, z.B. wenn Typen bei fehlender Einstellung automatisch zugewiesen werden. Überlegen Sie, welche Typen und Klassen Sie benötigen, erstellen Sie die Typen und Klassen und weisen sie Ihren Kontakten zu.
====

Sie können beliebig viele Kundenklassen erstellen und individuell einrichten. Kundenklassen erhalten automatisch eine ID, die in der Übersicht vor dem Namen der Kundenklasse angezeigt wird. Die ID bestimmt jedoch keine Reihenfolge, diese wird durch die Option *Position* festgelegt.

Wird eine neue Kundenklasse erstellt, steht die Kundenklasse in der Detailansicht des Kontakts im Menü *CRM » Kontakte » Kontakt öffnen* als Auswahl zur Verfügung.

[.instruction]
Kundenklasse erstellen:

. Öffnen Sie das Menü *System » CRM » Kundenklassen*.
. Wechseln Sie in das Tab *Neue Kundenklasse*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-kundenklasse-erstellen>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-kundenklasse-erstellen]]
.Kundenklasse erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Mindestbestellmenge*
|Mindestbestellmenge eingeben, wenn pro Artikel eine bestimmte Anzahl bestellt werden muss oder um eine Mindestbestellmenge für die Mengenrabatte zu gewährleisten.

|*Bezeichnung*
|Name für die neue Kundenklasse eingeben, z.B. *Großhändler* oder *Premiumkunde*.

|*Position*
|Wenn keine Zahl eingegeben wird, wird eine Position automatisch anschließend an die höchste vorhandene Position vergeben. In erster Linie dient die Position der Sortierung der Kundenklassen im Menü. Dies ist z.B. in Kombination mit der Gestaltung der Sichtbarkeit der Artikelpreise im Webshop wichtig. Dies wird unter *Anzeige der Preise im Webshop* eingestellt.

|*Zahlungsziel*
|Zahlungsziel in Tagen eingeben, das für diese Kundenklasse gelten soll. Ein im Kontaktdatensatz gespeichertes Zahlungsziel hat Priorität vor diesem Zahlungsziel. Ein Zahlungsziel kann weiterhin optional im <<auftragsabwicklung/auftraege/auftragsdokumente#, Auftragsdokumenten>> wie z.B. <<auftragsabwicklung/auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnungen>> hinterlegt werden. Dieses Zahlungsziel wird dann in der Rechnung ausgegeben, wenn für einen Kunden und die Kundenklasse kein Zahlungsziel hinterlegt wurden. Dazu die Box *Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen* unterhalb von <<tabelle-kontakt-erstellen>> im Kapitel <<crm/kontakte-verwalten#100, Kontakt erstellen>> beachten.

|*Kunden-ID*
|Kunden-ID des Kunden eingeben, an den Sammelrechnungen bei <<auftragsabwicklung/auftraege/sammelauftraege#, Sammelaufträgen>> geschickt werden sollen. Die Sammelaufträge werden kundenklassenspezifisch angelegt und die Rechnung wird an den Kunden gesendet.

|*Rabattart*
|Rabattart wählen. Je nach Rabattart werden mehr oder weniger Optionen eingeblendet. Wenn Sie keinen Rabatt wünschen, wählen Sie die Option *Kein Rabatt*. Weitere Informationen sowie Erläuterungen zu den Rabattarten in plentymarkets finden Sie im Kapitel <<crm/kontakte-verwalten#25, Rabattsystem nutzen>>.

|*Mengenrabatt*
|Wählen, ob der im Menü *System » Artikel » Verkaufspreise* eingegebene Wert unter *Ab Menge* berücksichtigt werden soll oder nicht.

|*Erlaubte Zahlungsarten*
|Wählen, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen. +
In der Grundeinstellung sind alle verfügbaren Zahlungsarten erlaubt. Werden neue Zahlungsarten integriert, müssen diese Zahlungsarten hier erlaubt werden, da neue Zahlungsarten nicht automatisch mit in die Erlaubnisliste aufgenommen werden. +
*_Wichtig_*: Dabei die Einstellungen hinsichtlich der <<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, gesperrten Zahlungsarten in den Versandprofilen>> beachten, die für die Kundenklasse verwendet wird, bzw. diese Einstellung prüfen, damit es an dieser Stelle nicht zu ungewollten Überschneidungen kommt. Die Zahlungsart, die für eine Kundenklasse erlaubt sein soll, darf in den Versandprofilen nicht gesperrt sein und auch die Kundenklasse darf dort nicht gesperrt sein.

|*Zahlungshinweis*
|Ein hier eingegebener Zahlungshinweis wird auf Einzelrechnungen angezeigt. Das können z.B. besondere Angaben zur Zahlung für eine bestimmte Kundenklasse sein.

|*Anzeige der Preise im Webshop*
|Wählen, ob die Preise im Webshop *Brutto* oder *Netto* angezeigt werden sollen. +
*_Wichtig_*: Diese Option legt nur die Anzeige der Preise fest, nicht die Berechnung der Preise für die Kundenklasse. Einstellung besonders für die Kundenklasse der Position 1 beachten, da diese Kunden automatisch zugewiesen wird, wenn keine Kundenklasse im Kontaktdatensatz gewählt wurde.
|====

Sie können Verkaufspreise mit Kundenklassen verknüpfen. Wählen Sie dazu im Menü *System » Artikel » Verkaufspreise* unter der Einstellung *Klasse* eine von Ihnen erstellte Kundenklasse. Weitere Informationen finden Sie auf der Handbuchseite <<artikel/artikel-verwalten#, Artikel verwalten>> im Kapitel <<artikel/artikel-verwalten#870, Verkaufspreise verwalten>>.

[#20]
=== Typ erstellen

Typen dienen der Einordnung und Unterscheidung von Kontakten. Einige Typen sind bereits standardmäßig in Ihrem plentymarkets System angelegt und können nicht gelöscht werden. Diese Typen sind *Kunde*, *Handelsvertreter*, *Lieferant*, *Partner*, *Hersteller* und *Interessent*. Die erstellten Typen stehen im Menü *CRM » Kontakte* im Bereich *Filter* in der Dropdown-Liste *Typ* zur Verfügung.

Beim Erstellen eines neuen Kontakdatensatzes ist automatisch der Typ *Kunde* als Standard eingestellt. Kunden des Typs *Lieferant* stehen als Lieferanten zur Verfügung, z.B. im Tab *Lieferant* einer Variante.

Gehen Sie wie im Folgenden beschrieben vor, um eigene Typen zu erstellen.

[.instruction]
Typ erstellen:

. Öffnen Sie das Menü *System » CRM » Typen*.
. Klicken Sie auf *Typ hinzufügen*.
. Geben Sie einen Namen ein.
. *Speichern* Sie die Einstellungen.

[.subhead]
Typ löschen

Gehen Sie wie im Folgenden beschrieben vor, um erstellte Typen, die Sie nicht mehr benötigen, zu löschen. Beachten Sie, dass die standardmäßig vorhandenen Typen nicht gelöscht werden können.

[.instruction]
Typ löschen:

. Öffnen Sie das Menü *System » CRM » Typen*.
. Klicken Sie auf *Löschen*.
. Bestätigen Sie die Sicherheitsabfrage.

[#25]
=== Rabattsystem nutzen

In plentymarkets haben Sie mehrere Möglichkeiten der Rabattierung. Sie können Ihren Kontakten einen <<crm/kontakte-verwalten#26, Kundenklassenrabatt>>, einen <<crm/kontakte-verwalten#28, Rabatt auf die Zahlungsart>> sowie eine <<crm/kontakte-verwalten#27, Rabattstaffel auf den Nettowarenwert einer Bestellung>> gewähren. Außerdem können Sie <<crm/kontakte-verwalten#29, Verkaufspreise als Rabatte>> speichern und <<crm/kontakte-verwalten#30, manuelle Rabatte>> eingeben. Nehmen Sie die Einstellungen für die Rabattarten im Menü *System » CRM » Kundenklassen* vor. Wie Sie die Rabatte gewähren, wird in den folgenden Unterkapiteln beschrieben.

[#26]
==== Kundenklassenrabatt einrichten

In einer Kundenklasse legen Sie Rabatte fest, die dann nur für die Kundenklasse wirksam werden. Darüber hinaus bestehen hier weitere Einstellungsmöglichkeiten, z.B. die Aktivierung von Mengenrabatten der Verkaufspreise. Beachten Sie dabei, dass sich je nach Einstellung Rabatte addieren können.

Gehen Sie wie im Folgenden beschrieben vor, um einen Rabatt für Kundenklassen einzugeben.

[.instruction]
Kundenklassenrabatt einrichten:

. Öffnen Sie das Menü *System » CRM » Kundenklassen*.
. Klappen Sie die Kundenklasse, für die der Rabatt gelten soll, auf.
. Aktivieren Sie unter *Rabattart* die Option *Kundenklassenrabatt*. +
→ Eine weitere Einstellung wird geöffnet.
. Geben Sie unter *Rabatt in %* den Prozentwert für den Rabattabzug ein.
. Wählen Sie, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wählen Sie, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Geben Sie einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wählen Sie, ob die Preise im Webshop *brutto* (inkl. MwSt.) oder *netto* (ohne MwSt.) angezeigt werden sollen.
. *Speichern* Sie die Einstellungen.

Informationen, wie Sie Kundenklassen erstellen, finden Sie im Kapitel <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>.

[#27]
==== Rabattstaffel auf Nettowarenwert einrichten

Möchten Sie Ihre Kontakte mit Rabatten belohnen, wenn diese häufig und umsatzsteigernd in Ihrem Webshop einkaufen, können Sie hier Rabattwerte auf den Nettowarenwert des Auftrages festlegen.

[.instruction]
Rabattstaffel auf Nettowarenwert einrichten:

. Öffnen Sie das Menü *System » CRM » Kundenklassen*.
. Klappen Sie die Kundenklasse, für die die Rabattstaffel gelten soll, auf.
. Aktivieren Sie unter *Rabattart* die Option *Rabattstaffel auf Nettowarenwert*. +
→ Eine Tabelle mit weiteren Einstellungen wird geöffnet.
. Geben Sie unter *ab Nettowarenwert* die Betragsangaben aufsteigend ein.
. Geben Sie unter *Rabatt in %* die Prozentwerte für den Rabattabzug aufsteigend ein. +
→ Wenn Sie z.B. im Feld *ab Nettowarenwert* 50 eingeben und im Feld *Rabatt in %* 2 eingeben, werden ab 50 Euro 2% Rabatt gewährt.
. Wählen Sie, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wählen Sie, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Geben Sie einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wählen Sie, ob die Preise im Webshop *brutto* (inkl. MwSt.) oder *netto* (ohne MwSt.) angezeigt werden sollen.
. *Speichern* Sie die Einstellungen.

Informationen, wie Sie Kundenklassen erstellen, finden Sie im Kapitel <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>.

[.subhead]
Ansicht des Kontakts beim Einkauf

Der Rabatt wird berechnet und angezeigt, wenn der Kontakt seinen Einkauf beendet und zur Kasse geht. Im Warenkorb wird zunächst nur der gesamte Rabattbetrag ausgewiesen. Wenn der Kontakt die Bestellung abschließt, wird zusätzlich zum Gesamtrabatt der Rabatt auf die einzelnen Artikelpositionen berechnet und angezeigt.

[#28]
==== Rabatt auf Zahlungsart einrichten

Die Rabattart *Rabatt auf Zahlungsart* ist eine Art Skontoumsetzung in plentymarkets. Sie gewähren Ihren Kontakten damit einen Rabatt auf die Verwendung einer oder mehrerer Zahlungsarten.

[TIP]
.Rabatt auf Zahlungsart direkt hinterlegen
====
Alternativ zu der Einstellung, die Sie in diesem Menü vornehmen, ist es möglich, direkt bei einer Zahlungsart einen globalen Rabatt für diese Zahlungsart zu hinterlegen. Ein Beispiel ist ein prozentualer Rabatt bei der Zahlungsart *Vorkasse*. Beachten Sie dazu die Handbuchseite <<auftragsabwicklung/payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>. Die Einstellung direkt bei der Zahlungsart erlaubt jedoch keine differenzierten Einstellungen wie bei der Option *Rabatt auf Zahlungsart* im Menü *System » CRM » Kundenklassen*.
====

Gehen Sie wie im Folgenden beschrieben vor, um einen Rabatt auf eine oder mehrere Zahlungsarten einzurichten.

[.instruction]
Rabatt auf Zahlungsart einrichten:

. Öffnen Sie das Menü *System » CRM » Kundenklassen*.
. Klappen Sie die Kundenklasse, für die der Rabatt gelten soll, auf.
. Geben Sie ein *Zahlungsziel* in Tagen ein, das Sie dieser Kundenklasse einräumen möchten.
. Aktivieren Sie unter *Rabattart* die Option *Rabatt auf Zahlungsart*. +
→ Eine Tabelle mit weiteren Einstellungen wird geöffnet.
. Wählen Sie eine oder mehrere Zahlungsarten, für die der Rabatt gelten soll.
. Geben Sie unter *Rabatt in %* den Prozentwert für den Rabattabzug ein.
. Wählen Sie, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wählen Sie, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Geben Sie einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wählen Sie, ob die Preise im Webshop *brutto* (inkl. MwSt.) oder *netto* (ohne MwSt.) angezeigt werden sollen.
. *Speichern* Sie die Einstellungen.

Informationen, wie Sie Kundenklassen erstellen, finden Sie im Kapitel <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>.

[#29]
==== Verkaufspreis als Rabatt speichern

Ein mengenbezogener Rabatt wird im Menü *System » Artikel » Verkaufspreise* als eigener Preis angelegt. Dort legen Sie mit der Option *Ab Menge* im Bereich *Einstellungen* für den Verkaufspreis fest, ab welcher Artikelmenge der rabattierte Preis gelten soll. Eine Staffelung realisieren Sie durch das Erstellen entsprechender Verkaufspreise mit den gewünschten Mindestmengen. +
Der rabattierte Verkaufspreis wird aktiviert, wenn Sie in der Kundenklasse die Option *Mengenrabatt* auf *Berücksichtigen* setzen. Ein Kontakt erhält den Rabatt, wenn der Kontakt erstens zu der betreffenden Kundenklasse gehört und zweitens mindestens die beim Verkaufspreis gespeicherte Menge bestellt.

[.instruction]
Verkaufspreis als Rabatt speichern:

. Öffnen Sie das Menü *System » Artikel » Verkaufspreise*.
. Öffnen Sie den Verkaufspreis.
. Geben Sie im Tab *Einstellungen* im Feld *Ab Menge* eine Ziffer ein, ab welcher Artikelmenge der rabattierte Preis gelten soll.
. Aktivieren Sie im Bereich *Klasse* die Kundenklassen, für die der Verkaufspreis gelten soll.
. *Speichern* Sie die Einstellungen.

Weitere Informationen zu Verkaufspreisen finden Sie im Themenbereich <<artikel#, Artikel>> im Kapitel <<artikel/artikel-verwalten#870, Verkaufspreise verwalten>>.

[#30]
==== Manuellen Rabatt eingeben

Zusätzlich zur Vergabe von automatischen Rabatten haben Sie auch die Möglichkeit, einzelnen oder allen Artikelpositionen eines Auftrags manuell einen Rabatt zuzuweisen. Sie können manuelle Rabatte in 2 verschiedenen Ansichten eingeben: in der Listenansicht der <<auftragsabwicklung/auftraege/auftraege-verwalten#suche, Auftragssuche>> und im Bearbeitungsfenster eines <<auftragsabwicklung/auftraege/auftraege-verwalten#auftrag-aendern, Auftrags>>.

[#31]
===== Rabatt für einzelnen Artikel in der Auftragssuche eingeben

Wenn Sie schnell einzelnen Artikelpositionen eines Auftrags einen Rabatt zuweisen oder den Rabattwert ändern möchten, können Sie dies direkt in der Auftragssuche tun. Gehen Sie wie im Folgenden beschrieben vor, um einen Rabatt für einzelne Artikel in der Auftragssuche einzugeben oder zu ändern.

[.instruction]
Rabatt für einzelnen Artikel in der Auftragssuche eingeben:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die Auftragssuche wird angezeigt.
. Klicken Sie rechts in der Ansicht eines Auftrags auf *Rabatt* (Standard: *0%*). +
→ Ein Fenster zur Eingabe des Prozentsatzes wird geöffnet.
. Geben Sie den als Rabatt gewünschten Prozentsatz ein.
. *Speichern* Sie die Einstellung. +
→ Der Rabattwert wird angezeigt und der Rabatt wird von der Artikelposition abgezogen.

[#32]
===== Rabatt für einzelnen Artikel im Auftrag eingeben

In der Auftragsübersicht werden ganz unten die Artikelpositionen angezeigt. Auch hier haben Sie die Möglichkeit, einzelnen Artikelpositionen einen Rabattwert zuzuweisen oder den Rabattwert zu ändern. Gehen Sie wie im Folgenden beschrieben vor, um einen Rabatt für einen Artikel im Auftrag einzugeben oder zu ändern.

[.instruction]
Rabatt für einzelnen Artikel im Auftrag eingeben:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag, auf den ein Rabatt gewährt werden soll, mit einem Klick auf die Auftragsnummer.
. Öffnen Sie im Tab *Übersicht* des Auftrags im unteren Bereich das Tab *Bearbeiten*.
. Wählen Sie aus der Dropdown-Liste *Rabatt* den Rabattsatz.
. *Speichern* Sie die Einstellungen.

[#33]
===== Rabatt für alle Artikel eines Auftrags eingeben

Gehen Sie wie im Folgenden beschrieben vor, um einen Rabatt für alle Artikelpositionen eines Auftrags einzugeben bzw. zu ändern.

[.instruction]
Rabatt für alle Artikel eines Auftrags eingeben:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag, auf den ein Rabatt gewährt werden soll, mit einem Klick auf die Auftragsnummer.
. Öffnen Sie im Tab *Übersicht* des Auftrags im unteren Bereich das Tab *Bearbeiten*.
. Klicken Sie unterhalb der Liste der Artikelpositionen auf den Link *Rabatt für alle Artikel vergeben*.
. Wählen Sie aus der angezeigten Dropdown-Liste den Rabattsatz.
. Klicken Sie rechts neben der Dropdown-Liste auf *Speichern*.
. *Speichern* Sie die Einstellungen.

[#50]
== Sichtbarkeit des Kontakt-Menüs für variablen Benutzer einstellen

Damit für Benutzer mit der Benutzerklasse *Variabel* das Menü *CRM » Kontakte* sichtbar ist, muss dieses Menü im Benutzerkonto freigeschaltet werden.

Da die Benutzeroberfläche des Menüs *CRM » Kontakte* über REST abgerufen wird, müssen zusätzlich Berechtigungen im Bereich *REST-API* aktiviert werden. Im Folgenden werden die Berechtigungen, die mindestens aktiviert werden müssen, damit das Menü sichtbar ist, beschrieben. Aktivieren Sie weitere Berechtigungen analog. Wenn der variable Benutzer z.B. Firmendatensätze erstellen soll, aktivieren Sie im Bereich *Firma* die Option *Firma erstellen*.

[.instruction]
Sichtbarkeit des Kontakt-Menüs für variablen Benutzer einstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den Benutzer mit der Benutzerklasse *Variabel*, für den Sie die Sichtbarkeit des Menüs aktivieren möchten.
. Wechseln Sie in das Tab *Berechtigung*.
. Wechseln Sie in das Tab *Menü*.
. Klappen Sie den Bereich *CRM* auf.
. Aktivieren Sie die Option *Kontakte*.
. Wechseln Sie in das Tab *REST-API*.
. Klappen Sie den Bereich *Firma* auf.
. Klappen Sie den Bereich *Adresse* auf.
. Aktivieren Sie die Option *Adresse anzeigen*.
. Klappen Sie den Bereich *Adressoption* auf.
. Klappen Sie den Bereich *Typ der Adressoption* auf.
. Aktivieren Sie die Option *Typ der Adressoption anzeigen*.
. Klappen Sie den Bereich *Kontakt* auf.
. Klappen Sie den Bereich *Kontaktadresse* auf.
. Aktivieren Sie die Option *Kontaktadresse anzeigen*.
. Klappen Sie den Bereich *Adresstyp* auf.
. Aktivieren Sie die Option *Adresstyp anzeigen*.
. Klappen Sie den Bereich *Kontaktoption* auf.
. Klappen Sie den Bereich *Typ der Kontaktoption* auf.
. Aktivieren Sie die Option *Typ der Kontaktoption anzeigen*.
. Klappen Sie den Bereich *property* auf.
. Aktivieren Sie die Option *show*.
. Klappen Sie den Bereich *propertyOption* auf.
. Aktivieren Sie die Option *show*.
. Klappen Sie den Bereich *tag* auf.
. Aktivieren Sie die Option *show*.
. Klappen Sie den Bereich *tagRelationship* auf.
. Aktivieren Sie die Option *show*.
. *Speichern* Sie die Einstellungen.

[#90]
== Kontakte und Firmen verwalten

Erfahren Sie in den folgenden Unterkapiteln, wie Sie z.B. neue Kontakte und Firmen erstellen, Kontakte mit einer Firma verknüpfen, nach vorhandenen Kontakten mit Filtereinstellungen suchen sowie vorhandene Kontakte bearbeiten und löschen.

[TIP]
.Hinweise zu Detailansicht, Kontextmenü, Kartenansicht und Tabellenansicht
====
Klickt man in der Übersicht im Menü *CRM » Kontakte* auf einen Kontakt, um den Kontakt anzuzeigen oder zu bearbeiten, öffnet sich die Detailansicht des Kontakts. Über das Kontextmenü im linken Bereich des Kontakts können Ansichten wie *Adressen* oder *Neue Adresse* aufgerufen werden.

Alternativ können Sie in der Kontaktübersicht die Menüs *Neuer Sammelauftrag*, *Neuer Auftrag*, *Aufträge*, *Neues Ticket* und *Neue Notiz* sowie die Funktion *Kontakt löschen* bequem mit einem Rechtsklick aufrufen.

Klickt man in der Detailansicht des Kontakts z.B. auf *Adressen* werden alle zu dem Kontakt gespeicherten Adressen initial als Karten angezeigt. Mit einem Klick auf *Zur Tabellenansicht wechseln* werden die Adressen in Tabellenform angezeigt. Aus dieser Ansicht wechselt man zurück mit einem Klick auf *Zur Kartenansicht wechseln*. Ihr plentymarkets System merkt sich, welche der beiden Ansichten Sie gewählt haben und zeigt beim nächsten Öffnen des Kontextmenüs *Adressen* die zuletzt gewählte Ansicht an.

Wenn mehr als eine Ansicht des Kontakts geöffnet ist, wird in der Ansicht oben ein Pfeil angezeigt, über den man zwischen den geöffneten Kontakten einfach und schnell hin- und herwechseln kann. Mit einem Klick auf das Kreuz wird der Kontakt geschlossen und aus der Liste entfernt.

Über die Ansicht *Übersicht* gelangt man zurück in die Übersicht der gefundenen Kontakte. Aus dieser Ansicht heraus lassen sich beliebig viele weitere Kontakte aufrufen. Wenn mehr als ein Kontakt geöffnet ist, wird in der Ansicht des gerade geöffneten Kontakts ein Pfeil angezeigt, über den man die Kontakte, die bereits einmal geöffnet waren, einfach und schnell aufrufen kann. Mit einem Klick auf das Kreuz wird der Kontakt geschlossen und aus der Liste entfernt.
====

[#100]
=== Kontakt erstellen

Gehen Sie wie im Folgenden beschrieben vor, um einen neuen Kontakt zu erstellen. Verknüpfen Sie den Kontakt mit einer bestehenden Firma oder erstellen Sie eine neue Firma. Fügen Sie Kontaktoptionen wie z.B. E-Mail-Adressen und Telefonnummern hinzu. Erstellen Sie einen neuen Kontakt z.B. während einer telefonischen oder schriftlichen Bestellung oder speichern Sie die Daten eines Interessenten. Beim Erstellen eines Kontakts wird vom System automatisch eine ID vergeben. Diese ID kann nicht geändert werden.

Weitere Informationen zum Verknüpfen des Kontakts mit einer Firma und zum Erstellen einer neuen Firma finden Sie in den Kapiteln <<crm/kontakte-verwalten#210, Kontakt mit Firma verknüpfen>> und <<crm/kontakte-verwalten#220, Firma erstellen>>.

[.instruction]
Kontakt erstellen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Klicken Sie auf *Neuen Kontakt erstellen*.
. Nehmen Sie die Einstellungen im Bereich *Neuer Kontakt* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-kontakt-erstellen>>.
. Weisen Sie im Bereich *Zugeordnete Tags* dem Kontakt einen oder mehrere Tags zu. Beachten Sie dazu die Erläuterungen im Kapitel <<crm/kontakte-verwalten#150, Tags erstellen>>.
. Erstellen Sie im Bereich *Firma* eine neue Firma oder weisen Sie eine dem Kontakt eine bestehende Firma zu. Beachten Sie dazu die Erläuterungen in <<tabelle-kontakt-erstellen>>. +
→ Weitere Informationen finden Sie in den Kapiteln <<crm/kontakte-verwalten#220, Firma erstellen>> und <<crm/kontakte-verwalten#210, Kontakt mit Firma verknüpfen>>.
. Wählen Sie im Bereich *Kontaktoptionen* den Typ und Subtyp aus den Dropdown-Listen und geben Sie den Wert ein. Beachten Sie dazu die Erläuterungen in <<tabelle-kontakt-erstellen>>. +
→ Mit einem Klick auf *Kontaktoption hinzufügen* fügen Sie weitere Kontaktoptionen hinzu.
. Fügen Sie die Adresse des Kontakts hinzu. +
→ *_Hinweis:_* Wenn Sie die Adresse zu einem späteren Zeitpunkt erstellen möchten, deaktivieren Sie den Toggle-Button *Adresse erstellen?*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-kontakt-erstellen>> im Bereich *Adresse*.
. *Speichern* Sie die Einstellungen. +
→ Der Kontakt wird erstellt.

[IMPORTANT]
.Kontaktoption: Subtyp *Privat* bei Typen *E-Mail* und *Telefon*
====
Beachten Sie, dass Sie beim Erstellen der Kontaktoptionen für die Typen *E-Mail* und *Telefon* den Subtyp *Privat* wählen, damit diese Daten automatisch in den Auftrag übernommen werden.
====

[[tabelle-kontakt-erstellen]]
.Kontakt erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Neuer Kontakt*

|*Anrede*
|Option aus der Dropdown-Liste wählen. Die Auswahl ist optional. +
*Frau* = Weibliche Anrede +
*Herr* = Männliche Anrede

|*Titel*
|Ggf. Titel des Kontakts eingeben.

|*Vorname*, *Nachname*
|Vorname und Nachname des Kontakts eingeben. Das sind Pflichtfelder, wenn keine Firma gewählt wird.

|*Mandant*
|Mandant aus der Dropdown-Liste wählen, um den Kontakt diesem Mandanten zuzuordnen. +
Nur Mandanten, für die im Menü *System » Mandant » Mandant wählen » Einstellungen* der Name gespeichert wurde, werden angezeigt.

|*Sprache*
|Sprache für den Kontakt wählen. Wenn Sie im Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen* eine Vorlage in der hier gewählten Sprache erstellt haben, werden E-Mail-Vorlagen in dieser Sprache versendet.

|*Typ*
|Typ wählen. Standardmäßig stehen die Typen *Kunde*, *Handelsvertreter*, *Lieferant*, *Partner*, *Hersteller* und *Interessent* zur Auswahl. Eigene Typen erstellen Sie im Menü <<crm/kontakte-verwalten#20, System » CRM » Typen>>. +
*_Hinweis:_* Je nachdem, welche Einstellung gewählt ist, sind unterschiedliche Felder im Bereich *Firma* sichtbar. Die Erläuterungen dazu finden Sie in dieser Tabelle im Bereich *Firma*.

|*Klasse*
|Klasse wählen. Dies ist ein Pflichtfeld. Klassen dienen zur internen Unterscheidung und z.B. ob und welcher Rabatt dieser Klasse gewährt werden soll. Klassen werden im Menü <<crm/kontakte-verwalten#15, System » CRM » Kundenklassen>> erstellt. Soll zum Beispiel zwischen Endkunden und Händlern bei der Preisanzeige im Webshop unterschieden werden, kann dies über die Option *Anzeige der Preise im Webshop* in den Einstellungen der Kundenklasse vorgenommen werden. Eine gängige Einstellung wäre z.B., dass bei Endkunden (B2C) die Bruttopreise und bei Händlern (B2B) die Nettopreise im Webshop angezeigt werden.

|*Bewertung*
|Kontakt für interne Zwecke bewerten. 5 rote Sterne stehen für die schlechteste und 5 gelbe Sterne für die beste Bewertung.

|*Kundennummer*
|Ggf. Kundennummer für den Kontakt eingeben. Kundennummern können für eine eigene interne Zuordnung genutzt werden und werden nicht automatisch vergeben. Sie entscheiden, ob und in welcher Form Sie interne Kundennummern verwenden möchten.

|*Eigner*
|Eigner für den Kontakt wählen. Wenn kein Eigner gewählt werden soll, die leere Option wählen. In der Dropdown-Liste werden ausschließlich Eigner angezeigt, für die im Menü *System » Einstellungen » Benutzer » Konten » Benutzer öffnen » Tab: Eigner* die Option *Kunde* aktiviert wurde.

|*Debitorenkonto*
|Weitere separate Kundennummer eingeben. Diese Nummer entspricht in der Regel der Kundennummer bzw. Debitorennummer in Ihrer Finanzbuchhaltung und ist zur weiteren Bearbeitung Ihrer Belege hilfreich. Dieses Feld kann ggf. auch automatisch befüllt werden. +
Weitere Informationen zum Debitorenkonto finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/buchhaltung#750, Buchhaltung>>.

|*Handelsvertreter*
|Hier kann dem Kontakt ein Handelsvertreter zugeordnet werden. Die ersten 3 Buchstaben des Namens oder die ID eingeben, um die Vorschlagsliste aufzurufen. Mit einem Klick auf die ID bzw. den Namen ist der Handelsvertreter dem Kontakt zugeordnet.

|*Rechnung erlauben* / +
*Lastschrift erlauben*
|Zahlungsart für den Kontakt erlauben, auch wenn diese Zahlungsart ansonsten global nicht verwendet wird. +
*Nicht erlauben* = Der Kontakt kann nicht mit dieser Zahlungsart zahlen. +
*Erlauben* = Der Kontakt kann mit dieser Zahlungsart zahlen, selbst wenn diese Zahlungsart nicht global angeboten wird. +
*_Beispiel:_* Ein Kontakt, der bereits mehrfach bei Ihnen bestellt hat, soll auf Rechnung einkaufen können. +
Notwendige Einstellungen: +
Einstellung 1: Die Zahlungsart im Menü *System » Aufträge » Zahlung » Zahlungsarten* aktivieren. Mit dieser Einstellung wir die Zahlungsart zur Auswahl in einem Auftrag verfügbar. +
*_Wichtig:_* Keine Lieferländer wählen, da die Zahlungsart ansonsten global im Webshop verfügbar ist und dies in diesem Fall nicht gewünscht ist. +
Einstellung 2: Die Zahlungsart *Rechnung* bzw. *Lastschrift* muss in mindestens einem Versandprofil verfügbar sein, d.h. sie darf nicht gesperrt sein. +
Einstellung 3: Das Versandprofil bei den Artikeln aktivieren. +
Die hier genannten notwendigen Einstellungen prüfen und dann die Zahlungsart aktivieren, um dem Kontakt die Nutzung dieser Zahlungsart zu erlauben.

|*Geburtsdatum*
|Geburtsdatum des Kontakts nach dem Muster dd.mm.yyyy eingeben oder aus dem Kalender wählen.

|*Newsletter*
|Zeigt an, ob der Kontakt den Newsletter erhält. Es ist nicht möglich, die Option manuell zu aktivieren. Um den Newsletter-Bezug für den Kontakt zu deaktivieren, auf *Newsletter löschen* klicken.

|*Gesperrt*
|Wählen, ob der Kontakt für den eingestellten Mandanten gesperrt wird oder nicht. +
Wenn die Option aktiviert ist, ist der Kontakt gesperrt und kann sich nicht mehr im Webshop einloggen. Wenn die Option deaktiviert ist, kann sich der Kontakt im Webshop einloggen.

2+|*Zugeordnete Tags*
2+|In das Feld klicken, um alle für den Bereich *Kontakte* verfügbaren Tags, die Sie zuvor im Menü *System » Einstellungen » Tags* erstellt haben, anzuzeigen. +
*_Oder:_* In das Feld klicken und die ersten 3 Buchstaben des Tag-Namens eingeben. Weitere Informationen zu Tags finden Sie im Kapitel <<crm/kontakte-verwalten#150, Tags erstellen>>.

2+|*Firma*

|*Name*
|Name der bereits <<crm/kontakte-verwalten#220, erstellten>> Firma in das Vorschlagsfeld eingeben, um diese Firma dem Kontakt zuzuordnen. Oder in das Feld klicken und die ersten 3 Buchstaben des Firmennamens eingeben. +
*_Wichtig:_* Das ist ein Pflichtfeld, wenn Vorname und Nachname nicht eingegeben wurden. +
Sobald eine bereits bestehende Firma aus der Vorschlagsliste gewählt wird, werden die zur Firma gehörenden Datenfelder direkt darunter angezeigt. Diese Datenfelder werden im Folgenden beschrieben. +
Wie Sie eine neue Firma erstellen, ist im Kapitel <<crm/kontakte-verwalten#220, Firma erstellen>> beschrieben. Wie Sie eine bestehende Firma bearbeiten, ist im Kapitel <<crm/kontakte-verwalten#230, Firma bearbeiten>> beschrieben.

|*USt-IdNr.*
|Umsatzsteueridentifikationsnummer des Kontakts eingeben. Wenn beim Versand von Waren an einen gewerblichen Käufer in ein anderes EU-Land (innergemeinschaftliche Lieferung) der Auftrag netto berechnet werden soll, muss die USt-IdNr. gespeichert sein. +
Nachdem die USt-IdNr. hier eingegeben wurde, muss im Menü <<auftragsabwicklung/auftraege/buchhaltung#400, System » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung>> für die Option *Umsatzsteuer-ID* die Einstellung *Nettorechnung* gewählt werden. Mit dieser Einstellung werden Rechnungen für Kontakte, bei denen eine UStId-Nr. in den Daten eingegeben ist, ohne Umsatzsteuer ausgestellt. +
*_Wichtig:_* Die Nettoeinstellung greift nicht, wenn für das Lieferland des Kontakts Steuersätze gespeichert sind.

|*Valuta*
|Zeitraum (ab Rechnungserstellung) eingeben, wenn eine zusätzliche Frist vor dem Zeitraum *Zahlungsziel* gewünscht ist. Dazu die Box *Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen* unterhalb dieser Tabelle beachten. +
*_Wichtig:_* Valuta kann nur Firmenkontakten, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Wert für Valuta in der Rechnung im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* zu speichern.

|*Zahlungsziel*
|Zahlungsziel für den Kontakt in Tagen eingeben. Dieses Zahlungsziel hat Priorität vor dem Zahlungsziel, das in der Kundenklasse festgelegt ist. Ein Zahlungsziel kann weiterhin optional im Dokument <<auftragsabwicklung/auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnung>> gespeichert werden. Das Zahlungsziel wird dann in der Rechnung ausgegeben, wenn für einen Kontakt und die Kundenklasse kein Zahlungsziel gespeichert wurde. Dazu die Box *Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen* unterhalb dieser Tabelle beachten. +
*_Wichtig:_* Das Zahlungsziel kann nur Firmenkontakten, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Wert für das Zahlungsziel in der Rechnung im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* zu speichern.

|*Skontofrist*
|Anzahl der Tage (ab Rechnungserstellung) eingeben, in denen der Kontakt skontiert offene Forderungen bezahlen kann. Dazu die Box *Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen* unterhalb dieser Tabelle beachten. +
*_Wichtig:_* Skonto kann nur Firmenkontakten, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Skontowert in der Rechnung im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* zu speichern.

|*Skontosatz*
|Wert in Prozent eingeben, den der Kontakt bei Einhaltung der *Skontofrist* in Abzug bringen kann. Dazu die Box *Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen* unterhalb dieser Tabelle beachten. +
*_Wichtig:_* Skonto kann nur Firmenkontakten, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Skontowert in der Rechnung im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* zu speichern.

|*Lieferzeit*
|Nur sichtbar bei Wahl des Typs *Lieferant*. Lieferzeit in Tagen eingeben.

|*MBW*
|Nur sichtbar bei Wahl des Typs *Lieferant*. MBW steht für Mindestbestellwert. Mindestbestellwert in der Systemwährung eingeben.

|*Eigner*
|Eigner aus der Dropdown-Liste wählen.

2+|*Handelsvertreter*

|*HV PLZ-Bereich Land*
|Nur sichtbar bei Wahl des Typs *Handelsvertreter*. Land aus der Dropdown-Liste wählen, für das der PLZ-Bereich des Handelsvertreters gelten soll. +
*_Tipp:_* Wenn ein Handelsvertreter in mehreren Ländern tätig ist, pro Land einen Kontaktdatensatz erstellen.

|*HV PLZ-Bereich*
|Nur sichtbar bei Wahl des Typs *Handelsvertreter*. PLZ-Bereich des Handelsvertreters eingeben. Mehrere Bereiche durch Kommata getrennt eingeben, z.B. *33, 34*. Je mehr Ziffern pro PLZ-Bereich, desto mehr wird der Bereich eingegrenzt.

2+|*Kontaktoptionen*

|*Typ*
|Typ aus der Dropdown-Liste wählen. +
Alle verfügbaren Typen sind in <<tabelle-typen-subtypen-kontaktoptionen>> aufgelistet.

|*Subtyp*
|Subtyp aus der Dropdown-Liste wählen. +
Alle verfügbaren Subtypen sind in <<tabelle-typen-subtypen-kontaktoptionen>> aufgelistet.

|*Wert*
|Wert eingeben.

2+|*Neue Adresse*
2+|Toggle-Button deaktivieren, wenn Sie die Adresse zu einem späteren Zeitpunkt hinzufügen möchten. Die Erläuterungen zu den Einstellungen einer neuen Adresse sind im Kapitel <<crm/kontakte-verwalten#600, Adresse hinzufügen>> beschrieben.

|====


[.collapseBox]
.Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen mit den Optionen Valuta, Zahlungsziel, Skontofrist und Skontosatz
--
Mit den Optionen *Valuta*, *Zahlungsziel*, *Skontofrist* und *Skontosatz* ist z.B. folgende Zahlungsbedingung möglich:

60 Tage Valuta, 30 Tage netto (Zahlungsziel), 10 Tage mit 2 % Skonto

Erläuterung: Zahlt der Kontakt innerhalb von 10 Tagen, erhält der Kontakt einen Skonto von 2%. Nach insgesamt 91 Tagen befindet sich die Zahlung im Verzug. Beim Import von Zahlungseingängen und der automatischen Zuordnung wird vorab intern automatisch geprüft, ob der von Kontakten durchgeführte Skontoabzug gültig ist. Ist der Skontozeitraum abgelaufen, erhält der Auftrag den Status *Teilzahlung erhalten*. Die oben aufgeführten Zahlungsbedingungen werden automatisch in den Auftrag sowie z.B. in die <<auftragsabwicklung/auftraege/auftragsdokumente/rechnungen-erzeugen, Rechnung>> übernommen und können dort auch geändert werden. Bei Rechnungsdruck werden diese Bedingungen zu einer für diesen Auftrag gültigen Zahlungskondition zusammengefasst. Hierbei werden Valutatage auf die Zahlungszieltage aufgerechnet, um ein Zahlungsziel abzubilden. Auf einer Rechnung wird trotz der Addition von Valuta und Zahlungsziel Folgendes ausgegeben:

Zahlungskonditionen: Valuta 60 Tage, innerhalb von 10 Tagen 2% Skonto, innerhalb von 30 Tagen ohne Abzug. Wenn ein Wert für *Valuta* am Kontakt gespeichert ist, wird dieser für das Dokument verwendet, andernfalls der Wert unter *Zahlungsziel* bzw. der Wert aus der Kundenklasse, falls eingegeben. Als letzte Möglichkeit, wenn alles andere nicht gesetzt ist, wird die Anzahl der Tage aus der Option *Zahlungsziel* in den Einstellungen des Dokuments verwendet. Diese werden im Bereich <<auftragsabwicklung/auftraege/auftragsdokumente#130, Optionale Elemente unter Artikelpositionstabelle>> eingestellt. Wichtig: Diese Optionen finden nur Anwendung auf den Bruttogesamtwert einer Rechnung.

--

[#110.subhead]
Verfügbare Typen und Subtypen der Kontaktoptionen

<<tabelle-typen-subtypen-kontaktoptionen>> listet alle verfügbaren Typen sowie Subtypen in den Kontaktoptionen auf.

[[tabelle-typen-subtypen-kontaktoptionen]]
.Verfügbare Typen und Subtypen der Kontaktoptionen
[cols="1,3"]
|====
|Typ |Subtyp

|Telefon
|Geschäftlich +
Mobil Privat +
Mobil Arbeit +
Privat +
*_Wichtig:_* Damit die Telefonnummer automatisch in den Auftrag übernommen wird, muss für den Typ *Telefon* der Subtyp *Privat* gewählt werden.

|E-Mail
|Geschäftlich +
Privat +
PayPal +
*_Wichtig:_* Damit die E-Mail-Adresse automatisch in den Auftrag übernommen wird, muss für den Typ *E-Mail* der Subtyp *Privat* gewählt werden.

|Telefax
|Geschäftlich +
Privat

|Webseite
|Geschäftlich +
Privat

|Marktplatz
|eBay +
Amazon

|Identifikationsnummer
|Klarna +
DHL

|Payment
|PayPal +
Klarna +
Standard

|Benutzername
|Geschäftlich +
Privat +
Forum

|Gruppe
|Forum

|Zugang
|Gast +
Marketplace Partner

|Zusatz
|Ansprechpartner

|Briefanrede
|Geschäftlich +
Privat

|====

[#150]
=== Tags erstellen

Sie haben die Möglichkeit, Tags für Ihre Kontakte zu erstellen und nach diesen Tags auch in der Übersicht zu filtern. Tags sind Schlagworte, die Sie Ihren Kontakten zuordnen können.

Zunächst müssen Sie die Tags im Menü *System » Einstellungen » Tags* erstellen und den Bereich *Kontakte* aktivieren. Wie Sie Tags erstellen, ist auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/tags#, Tags>> beschrieben.

[#151]
==== Tags zuordnen

Nachdem Sie Tags im Menü *System » Einstellungen » Tags* erstellt und den Bereich *Kontakte* aktiviert haben, gehen Sie wie im Folgenden beschrieben vor, um den oder die Tags einem Kontakt zuzuordnen.

[.instruction]
Tags zuordnen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Geben Sie in der Ansicht *Filter* Suchbegriffe in die Suchfelder ein bzw. stellen Sie Filteroptionen in den Dropdown-Listen ein. Beachten Sie dazu die Erläuterungen in <<tabelle-filter-kontakte>>.
. Klicken Sie auf *Suchen*. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Geben Sie im Bereich *Zugeordnete Tags* den Namen des Tags ein.
. Klicken Sie auf den Namen des Tags in der Liste.
. *Speichern* Sie die Einstellungen. +
→ Der Tag wird dem Kontakt zugeordnet und im Bereich *Zugeordnete Tags* angezeigt.

[TIP]
.Tags für den Bereich Kontakte
====
Nur Tags, für die der Bereich *Kontakte* im Menü *System » Einstellungen » Tags* aktiviert wurde, stehen am Kontakt als Auswahl zur Verfügung.
====

Sie können den Tag auch jederzeit mit einem Klick auf das x im Tag wieder vom Kontakt entfernen.

[#152]
==== Nach Tags filtern

Filtern Sie nach Tags, um alle Kontakte, denen dieses Tag zugeordnet ist, anzuzeigen. Sie haben die Möglichkeit nach einem oder mehreren Tags gleichzeitig zu filtern.

[.instruction]
Nach Tags filtern:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Wählen Sie in der Ansicht *Filter* einen oder mehrere Tags aus der Dropdown-Liste *Tags*.
. Klicken Sie auf *Suchen*. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

[#200]
=== Kontakt suchen

In der Ansicht *Filter* haben Sie die Möglichkeit, Kontakte nach bestimmten Kriterien zu suchen. Die gefundenen Kontakte werden dann in der Ansicht *Übersicht* angezeigt. In der Übersicht werden aktuell die folgenden Informationen angezeigt: ID, Gast, Firma, Vorname, Nachname, E-Mail-Adresse, Telefonnummer, Anzahl der Aufträge, Postleitzahl und Land. Wie Sie Kontaktdaten bearbeiten, ist im Kapitel <<crm/kontakte-verwalten#300, Kontakt bearbeiten>> beschrieben.

Sie haben auch die Möglichkeit, alle gespeicherten Daten eines Kontakts inklusive Adressen, Aufträgen, Notizen und Tickets über die Schnellsuche anzuzeigen. Wie Sie dazu vorgehen, ist im Kapitel <<crm/kontakte-verwalten#1705, Schnellsuche verwenden>> beschrieben.

[TIP]
.E-Mails direkt aus der Übersicht heraus versenden
====
Senden Sie Ihrem Kontakt direkt aus der Kontaktübersicht heraus eine E-Mail. Mit einem Klick auf die E-Mail-Adresse öffnet sich Ihr E-Mail-Programm automatisch.
====

Um bestimmte Kontakte zu suchen, geben Sie die Ihnen bekannten Suchbegriffe in die Filter ein oder wählen Sie die Einstellungen der Dropdown-Listen. Es ist auch möglich, mehrere Suchbegriffe gleichzeitig in die Suchfelder einzugeben. Dies ermöglicht Ihnen eine schnellere und genauere Suche.

[.instruction]
Kontakt suchen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Geben Sie in der Ansicht *Filter* Suchbegriffe in die Suchfelder ein bzw. stellen Sie Filteroptionen in den Dropdown-Listen ein. Beachten Sie dazu die Erläuterungen in <<tabelle-filter-kontakte>>.
. Klicken Sie auf *Suchen*. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet. +
*_Oder:_* Öffnen Sie bestimmte Bereiche des Kontextmenüs wie *Neuer Auftrag* oder *Neue Notiz* mit einem Rechtsklick.


[[tabelle-filter-kontakte]]
.Filter für die Kontakte
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Ohne gewählte Filtereinstellungen auf *Suchen* klicken, um alle Kontakte anzuzeigen. +
*_Oder:_* Die Suchergebnisse durch Filtereinstellungen eingrenzen und auf *Suchen* klicken. +
→ Die gefundenen Kontakte werden in der Übersicht angezeigt.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*ID*
|Jeder Kontakt erhält automatisch eine fortlaufende und einzigartige ID. Dies ist unabhängig davon, ob der Kontakt manuell oder automatisch erstellt wurde. 2 Kontakte haben somit nie die gleiche ID. Die ID entspricht immer einer echten Zahl. Ungültig sind z.B. "00521" oder "ADF8354".

|*Name*
|Vorname und/oder Nachname oder Firmenname eingeben, um den Kontakt mit diesem Namen bzw. Firmennamen anzuzeigen. Es wird auch nach Namen und Firmennamen, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen des Namens bzw. Firmennamens zu suchen.

|*Kontaktdaten*
|In diesem Feld kann nach dem Namen, der Adresse, der Firma, der Kundennummer und dem eBay-Namen gesucht werden. +
*_Hinweis:_* Um nach dem eBay-Namen zu suchen, zuerst den Parameter *ebay:* gefolgt vom gesuchten eBay-Namen eingeben.

|*Anschrift*
|Straßenname und/oder Hausnummer eingeben, der im Kontakt gespeichert ist. Es ist möglich, nur nach Teilen des Straßennamens und Teilen der Hausnummer zu suchen.

|*PLZ*
|Postleitzahl, die im Kontakt gespeichert sind, eingeben. Es wird auch nach Postleitzahlen, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen der Postleitzahl zu suchen.

|*Ort*
|Ort, der im Kontakt gespeichert ist, eingeben. Es wird auch nach Orten, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen des Ortsnamens zu suchen.

|*E-Mail*
|Komplette E-Mail-Adresse eingeben, um den Kontakt mit dieser E-Mail-Adresse zu suchen.

|*Telefon*
|Telefonnummer eingeben, um nur den Kontakt mit dieser Telefonnummer anzuzeigen. Es kann auch nach Teilen der Telefonnummer gesucht werden. Mindestens 3 Ziffern eingeben.

|*Land*
|Land wählen, um nur Kontakte aus diesem Land anzuzeigen. Das Land ist in den Kontaktdaten gespeichert.

|*Eigner*
|Eigner wählen, um nur Kontakte anzuzeigen, die mit diesem Eigner verknüpft sind. Der Eigner muss in den Kontaktdaten gespeichert sein. +
*_Wichtig:_* In der Dropdown-Liste werden nur Benutzer angezeigt, bei denen im Benutzerkonto im Tab *Eigner* die Option *Kunde* aktiviert ist.

|*Typ*
|Typ wählen, um nur Kontakte mit diesem Typ anzuzeigen.

|*Kundenklasse*
|Kundenklasse wählen, um nur Kontakte mit dieser Kundenklasse anzuzeigen.

|*Tags*
|Tag wählen, um nur Kontakte mit diesem Tag anzuzeigen.

|*Mandant*
|Mandant wählen, um nur Kontakte dieses Mandanten anzuzeigen. Der Mandant ist in den Kontaktdaten gespeichert. +
*_Wichtig:_* Variablen Benutzern stehen nur Mandanten zur Auswahl, für die sie eine Berechtigung haben. Berechtigungen werden im Menü *System » Einstellungen » Benutzer » Konten* im Tab <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90, Berechtigung>> des Benutzerkontos eingestellt.

|*Herkunft*
|Herkunft wählen, um nur Kontakte mit dieser Herkunft anzuzeigen.
|====

[#210]
=== Kontakt mit Firma verknüpfen

Wenn Sie den Kontakt ohne eine Verknüpfung zu einer Firma erstellt haben, können Sie die Firma auch nachträglich verknüpfen. Um Verwechslungen auszuschließen, werden neben dem Firmennamen auch der Ort, die Straße und das Land der Firma angezeigt.

Geben Sie mindestens 3 Buchstaben des Firmennamens, des Orts, der Straße oder des Landes ein, damit Ihr plentymarkets System Ihnen bereits gespeicherte Firmendatensätze vorschlägt.

[.instruction]
Kontakt mit Firma verknüpfen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Geben Sie im Bereich *Firma* den Namen der Firma, den Ort, die Straße oder das Land in das Feld ein. +
→ Sobald Sie 3 Buchstaben eingeben, werden Ihnen bereits im System gespeicherte Firmendatensätze vorgeschlagen.
. Wählen Sie den Firmendatensatz aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen. +
→ Die zu der Firma gespeicherten Daten werden in der Detailansicht des Kontakts angezeigt.

[#220]
=== Firma erstellen

Erstellen Sie die Firma und speichern Sie Daten wie USt-IdNr., Zahlungsziel und Skontosatz.

[.instruction]
Firma erstellen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Bereich *Firma* auf *Neue Firma hinzufügen*. +
→ *_Oder:_* Geben Sie den Namen der Firma in das Vorschlagsfeld ein und klicken Sie auf *Speichern*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-kontakt-erstellen>> im Bereich *Firma*.
. *Speichern* Sie die Einstellungen. +
→ Die Firma wird erstellt und die Detailansicht des Kontakts wird geöffnet.
. *Speichern* Sie die Einstellungen.

[TIP]
.Laden bereits vorhandener Firmendatensätze
====
Bereits gespeicherte Firmendatensätze werden beim Klick in das Vorschlagsfeld erst geladen, wenn Sie mindestens 3 Buchstaben des Firmennamens eingegeben haben.
====

[#230]
=== Firma bearbeiten

Wenn Sie bereits gespeicherte Firmendaten bearbeiten, werden die Daten des bereits vorhandenen Firmendatensatzes überschrieben.

[.instruction]
Firma bearbeiten:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Bereich *Firma* auf *Bearbeiten*.
. Nehmen Sie die Änderungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-kontakt-erstellen>> im Bereich *Firma*.
. *Speichern* Sie die Einstellungen. +
→ Die Daten der bearbeiteten Firma werden überschrieben und die Daten der neu erstellten Firma werden in der Detailansicht des Kontakts angezeigt.

[#240]
=== Verknüpfung zwischen Firma und Kontakt löschen

Wenn Sie die Verknüpfung zwischen Firma und Kontakt in der Detailansicht des Kontakts wieder löschen möchten, wird nur die Verknüpfung gelöscht und nicht die gespeicherten Firmendaten selbst. Die Firmendaten werden weiterhin in der Dropdown-Liste als Vorschlag angezeigt, wenn Sie mindestens 3 Buchstaben des Firmennamens, des Orts, der Straße oder des Landes eingeben.

[.instruction]
Verknüpfung zwischen Firma und Kontakt löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Bereich *Firma* in das Eingabefeld.
. Wählen Sie die leere Option.
. *Speichern* Sie die Einstellungen. +
→ Die Verknüpfung zwischen Firma und Kontakt wird gelöscht.

[#300]
=== Kontakt bearbeiten

Suchen Sie den Kontakt anhand der <<crm/kontakte-verwalten#200, Filtereinstellungen>>. Öffnen Sie den Kontakt durch einen Klick in die Zeile des Kontakts, um dessen Daten, wie z.B. Geburtsdatum, Telefonnummer und E-Mail-Adresse, zu bearbeiten. Erläuterungen zu den Einstellungen und Optionen finden Sie in <<tabelle-kontakt-erstellen>> im Kapitel <<crm/kontakte-verwalten#100, Kontakt erstellen>>. Kontaktoptionen löschen Sie mit einem Klick auf *Kontaktoption löschen*.

[.instruction]
Kontakt bearbeiten:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet. +
*_Oder:_* Öffnen Sie bestimmte Bereiche des Kontextmenüs wie *Neuer Auftrag* oder *Neue Notiz* mit einem Rechtsklick.
. Nehmen Sie die Änderungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-kontakt-erstellen>> im Kapitel <<crm/kontakte-verwalten#100, Kontakt erstellen>>.
. *Speichern* Sie die Einstellungen.

[#350]
=== Callisto: Gastzugang in regulären Zugang umwandeln

Wenn der Kontakt als Gast in Ihrem Callisto-Webshop bestellt hat, wird diese Zugangsart als Kontaktoption in der Detailansicht des Kontakts gespeichert. Gastzugänge haben den Wert 1. Löschen Sie die Kontaktoption mit dem Wert 1, um den Gastzugang in einen regulären Zugang umzuwandeln.

Informieren Sie den Kontakt darüber, dass das Gastkonto in ein reguläres Konto umgewandelt wurde und senden Sie dem Kontakt eine E-Mail, damit der Kontakt ein Passwort für den Login in Ihrem Webshop vergeben kann.

[.instruction]
Gastzugang in regulären Zugang umwandeln:

. Öffnen Sie das Menu *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Bereich *Kontaktoptionen* in der Zeile der Zugangsart (Typ: *Zugang*, Subtyp: *Gast*, Wert: *1*) auf *Kontaktoption löschen*.
. *Speichern* Sie die Einstellungen. +
→ Die Zugangsart in der Historie des Kontakts wird von *Gastzugang* auf *Regulärer Zugang* geändert.

[NOTE]
.Gastzugänge über Ceres-Webshop nur in Schnellsuche
====
Um DSGVO-konform zu arbeiten, wird bei Gastbestellungen über den Ceres-Webshop kein Kontaktdatensatz erstellt. Bestellungen, die als Gast über einen Ceres-Webshop aufgegeben wurden, können daher nicht über das Menü *CRM » Kontakte* gefunden werden. Die Daten des Gastes können nur über die Adressdaten im Menü *CRM » Schnellsuche* gefunden werden.
====

[#400]
=== Kontakt löschen

Sie haben die Möglichkeit, einzelne Kontakte zu löschen. Ein Kontakt kann nur gelöscht werden, sofern dieser nicht mit einem Auftrag verknüpft ist.

[.instruction]
Kontakt in der Übersicht löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Öffnen Sie das Kontextmenü mit einem Rechtsklick auf die Zeile des Kontakts.
. Klicken Sie in der Liste auf *Kontakt löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Der Kontakt wird gelöscht und aus der Übersicht entfernt.

Sie können den Kontakt auch in der Detailansicht löschen. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Kontakt in der Detailansicht löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Kontakt löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Der Kontakt wird gelöscht und aus der Übersicht entfernt.

[#420]
=== Dublettenprüfung bei Kontaktdatensätzen mit identischer E-Mail-Adresse

Beim Erstellen neuer und beim Aktualisieren bestehender Kontaktdatensätze erfolgt eine Prüfung anhand der E-Mail-Adresse, um Dubletten im System zu vermeiden.

Die Logik funktioniert folgendermaßen:

* Beim Erstellen eines neuen Kontakts wird nach einem vorhandenen regulären Kontakt mit identischer privater E-Mail-Adresse gesucht. Wird ein Kontakt gefunden, wird dieser mit den neuen Daten aktualisiert. Wird kein Kontakt gefunden, wird ein neuer regulärer Kontakt erstellt.

* Wenn beim Aktualisieren eines bestehenden regulären Kontaktes die private E-Mail-Adresse geändert wird, wird zunächst gesucht, ob ein anderer regulärer Kontakt mit derselben privaten E-Mail-Adresse existiert. Ist dies der Fall, wird die private E-Mail-Adresse des aktuellen Kontaktes nicht aktualisiert, alle anderen Daten jedoch schon.


[#450]
=== vCard exportieren

Sie haben die Möglichkeit, die Daten des Kontakts als Visitenkarte im VCF-Format zu exportieren.

[.instruction]
vCard exportieren:

. Öffnen Sie das Menu *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie auf *Kontakt als vCard herunterladen*. +
→ Ein Fenster, in dem Sie den Speicherort auf Ihrem Computer wählen, wird geöffnet.
. Die vCard steht Ihnen am gewählten Speicherort zur Verfügung.

[#500]
== Historie anzeigen

Beim Erstellen des Kontakdatensatz wird die Historie eines Kontakts gespeichert. Die Historie beinhaltet z.B. das Datum, seit dem der Kontakt bei Ihnen registriert ist, wann der Kontakt das letzte Mal in Ihrem Webshop eingeloggt war und wann der letzte Auftrag generiert wurde. Die Daten werden automatisch angepasst und können nicht geändert werden.

[.instruction]
Historie anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet und die Historie wird im rechten Bereich unterhalb der *Kontaktoptionen* angezeigt.
. Beachten Sie die Erläuterungen zur Historie in <<tabelle-historie-kontakt>>.

[[tabelle-historie-kontakt]]
.Historie im Menü *CRM » Kontakte » Kontakt öffnen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Registriert seit*
|Datum und Uhrzeit, seit wann der Kontakt registriert ist.

|*Aktualisiert*
|Datum und Uhrzeit, wann die Daten des Kontakts das letzte Mal aktualisiert wurden.

|*Zugangsart*
|Art, wie sich der Kontakt registriert hat. +
*Regulärer Zugang* = Der Kontakt hat sich neu registriert bzw. der Datensatz wurde manuell im Backend erstellt. +
*Gastzugang* = Der Kontakt hat sich als Gast angemeldet und bestellt. +
*_Wichtig:_* Wenn Sie Ceres nutzen, haben Sie die Möglichkeit, das Erstellen von Kontaktdatensätzen bei Gastbestellungen zu unterbinden. Wählen Sie dazu im Menü *System » CRM » Einstellungen* aus der Dropdown-Liste *Gastbestellungen* die Option *Keine Kontakte erstellen*. Standardmäßig ist die Option *Kontake erstellen* gewählt.

|*Letzter Auftrag*
|Datum und Uhrzeit, wann der letzte Auftrag eingegangen ist. Wenn kein Auftrag eingegangen ist, steht in diesem Feld *Keine Daten*.

|*Letzter Login*
|Datum und Uhrzeit des letzten Login. Wenn kein Login stattgefunden hat, steht in diesem Feld *Keine Daten*.
|====

[#510]
== Gruppenfunktion nutzen

Mit der Gruppenfunktion wird der Versand einer E-Mail-Vorlage, der Druck von Adressetiketten oder das Hinzufügen des Kontakts zu einem Newsletter-Ordner für einen oder mehrere Kontakte gleichzeitig ausgelöst.

[.instruction]
Gruppenfunktion nutzen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt bzw. die Kontakte anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie auf *Gruppenfunktion*.
. Aktivieren Sie eine oder mehrere Aktionen und wählen Sie die Optionen aus den Dropdown-Listen. Beachten Sie dazu die Erläuterungen in <<tabelle-kontakt-gruppenfunktion>>.
. Aktivieren Sie den Kontakt bzw. die Kontakte, für die Sie die Aktionen ausführen möchten.
. Klicken Sie auf *Gruppenfunktion*, um die gewählten Aktionen für die aktivierten Kontakte auszulösen.

[[tabelle-kontakt-gruppenfunktion]]
.Gruppenfunktion im Menü *CRM » Kontakte* nutzen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Adressetikett drucken*
|Druckt das aus der Dropdown-Liste gewählte Etikett von allen aktivierten Kontakten. +
*_Wichtig:_* Die Adressetikettenvorlage muss zuvor im Menü *System » Aufträge » Dokumente » Adressetikett* <<auftragsabwicklung/fulfillment/dokumente-erzeugen#400, erstellt>> worden sein. Ob die primäre Rechnungsadresse oder die primäre Lieferadresse des Kontakts ausgegeben wird, hängt von der Einstellung in der Adressetikettenvorlage ab.


|*E-Mail-Vorlage senden*
|Versendet die aus der Dropdown-Liste gewählte Vorlage an alle aktivierten Kontakte. +
*_Wichtig:_* Die E-Mail-Vorlage muss zuvor im Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen* <<crm/e-mails-versenden#1200, erstellt>> worden sein.

|*Zu Newsletter-Ordner hinzufügen*
|Kopiert die E-Mail-Adressen der aktivierten Kontakte in den aus der Dropdown-Liste gewählten E-Mail-Ordner im Menü *System » CRM » Newsletter » plentymarkets » E-Mail-Ordner* für den Newsletterversand.

|*Zahlungsziel speichern*
|Speichert das eingegebene Zahlungsziel in Tagen in den Kontaktdatensätzen aller aktivierten Kontakte. +
*_Hinweis:_* Wenn Sie diese Aktion aktivieren und keinen Wert eingeben, wird für die aktivierten Kontakte der bisher gespeicherte Wert gelöscht.

|====

[#590]
== Adressen verwalten

Erfahren Sie in den folgenden Unterkapiteln, wie Sie neue Adressen zu Ihrem Kontakt hinzufügen, alle zu Ihrem Kontakt gespeicherten Adressen anzeigen sowie bestehende Adressen bearbeiten und löschen.

[#600]
=== Adresse hinzufügen

Fügen Sie einem Kontakt beliebig viele Adressen sowie Adressoptionen wie z.B. die Telefonnummer des Kontakts hinzu.

In diesem Kapitel wird beschrieben, wie Sie Adressen zu einem bereits bestehenden Kontaktdatensatz hinzufügen. Wie Sie Adressen direkt beim Erstellen eines neues Kontakts hinzufügen, ist im Kapitel <<crm/kontakte-verwalten#100, Kontakt erstellen>> beschrieben.

[.instruction]
Adresse hinzufügen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Neue Adresse*.
. Nehmen Sie die Einstellungen im Bereich *Neue Adresse* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-adresse-hinzufuegen>>.
. Wählen Sie im Bereich *Adressoptionen* den Typ aus der Dropdown-Liste und geben Sie den Wert ein. Beachten Sie dazu die Erläuterungen in <<tabelle-adresse-hinzufuegen>>. +
→ Mit einem Klick auf *Adressoption hinzufügen* fügen Sie weitere Adressoptionen hinzu.
. *Speichern* Sie die Einstellungen. +
→ Die Adresse wird der Übersicht im Bereich *Adressen* hinzugefügt.

[[tabelle-adresse-hinzufuegen]]
.Adresse hinzufügen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Neue Adresse*

|*Rechnungsadresse* / *Lieferadresse*
|Eine oder beide Optionen aktivieren, um den Adresstyp festzulegen. +
Die neue Adresse kann entweder nur Rechnungsadresse, nur Lieferadresse oder sowohl Rechnungsadresse als auch Lieferadresse sein. Wenn beide Optionen aktiviert sind, wird eine Adresse mit einer neuen ID und 2 Adresstypen erstellt. +
Sobald eine oder beide Optionen aktiviert sind, kann für eine oder beide Optionen gewählt werden, ob es sich um die primäre Adresse handelt.

|*Primär*
|Option aktivieren, wenn es sich bei der neuen Adresse um die primäre Rechnungsadresse bzw. primäre Lieferadresse handelt. +
Es ist möglich, beide Optionen zu aktivieren, wenn es sich bei der neuen Adresse sowohl um die primäre Rechnungsadresse als auch um die primäre Lieferadresse handelt.

|*Anrede*
|Optional Anrede aus der Dropdown-Liste wählen.

|*Name 1 (Firma)*
|Firmenname eingeben. Das ist ein Pflichtfeld, wenn unter *Vorname* und *Nachname* kein Eintrag gemacht wird.

|*Name 2 (Vorname)*
|Vorname des Kontakts eingeben. Das ist ein Pflichtfeld, wenn unter *Firma* und *Nachname* kein Eintrag gemacht wird.

|*Name 3 (Nachname)*
|Nachname des Kunden eingeben. Das ist ein Pflichtfeld, wenn unter *Firma* und *Vorname* kein Eintrag gemacht wird.

|*Name 4 (Zusatz)*
|Optional Zusatzangaben zum Kontakt eingeben, z.B. z.Hd. Herrn Max Mustermann.

|*Adresse 1 (Straße)* +
*Adresse 2 (Hausnummer)*
| Straße und Hausnummer eingeben. +
*Straße* ist ein Pflichtfeld, wenn unter *Hausnummer* und *Adresszusatz* kein Eintrag gemacht wird. *Hausnummer* ist ein Pflichtfeld, wenn unter *Straße* und *Adresszusatz* kein Eintrag gemacht wird.

|*Adresse 3 (Adresszusatz)*
|Optional Adresszusatz eingeben, z.B. Apartment 12a. Das ist ein Pflichtfeld, wenn unter *Straße* und *Hausnummer* kein Eintrag gemacht wird.

|*Adresse 4 (Frei)*
|Feld zur freien Verfügung.

|*Postleitzahl* +
*Ort*
|Falls vorhanden Postleitzahl und Ort des Kontakts eingeben. *Ort* ist ein Pflichtfeld. +
Diese Angaben werden z.B. für die Rechnungsadresse verwendet. Bei bestimmten Ländern, z.B. Vereinigtes Königreich, wird die Reihenfolge der Optionen *Postleitzahl* und *Ort* getauscht.

|*Land* +
*Region/Bezirk*
|Werte aus den Dropdown-Listen wählen. +
*_Wichtig:_* Die Dropdown-Liste *Region/Bezirk* ist nicht für alle Länder verfügbar.

2+|*Adressoptionen (optional)*

|*Typ*
|Typ aus der Dropdown-Liste wählen bzw. Werte für die vorausgewählten Optionen *E-Mail* und *Telefon* eingeben. +
*_Hinweis:_* Die Typen *E-Mail* und *Telefon* werden statisch angezeigt. Weitere verfügbare Typen in der Dropdown-Liste: Umsatzsteuernummer, Externe Adress-ID, Gelangensbestätigung, Postnummer, Personennummer, FSK, Geburtstag, Titel, Ansprechpartner.

|*Wert*
|Wert eingeben.
|====

[#700]
=== Adressen anzeigen

Aus dem geöffneten Kontakt heraus lassen sich alle dem Kontakt zugehörigen Adressen anzeigen. Neben Informationen wie ID, Firmenname, Vor- und Nachname sowie Adresse und Land sehen Sie außerdem, um welchen Adresstyp es sich handelt – Rechnungsadresse oder Lieferadresse – und ob die Adresse eine primäre Adresse ist.

Wenn mehrere Adressen geöffnet sind, werden in der Dropdown-Liste der geöffneten Adressen die IDs der Adressen angezeigt.

Initial werden die Adressen Ihres Kontakts in der Kartenansicht angezeigt. Mit einem Klick auf *Zur Tabellenansicht wechseln* werden die Adressen in Tabellenform angezeigt. Ihr plentymarkets System merkt sich, welche der beiden Ansichten Sie gewählt haben und zeigt beim nächsten Öffnen des Kontextmenüs *Adressen* die zuletzt gewählte Ansicht an.

Pro Seite werden bis zu 25 Adressdatensätze zu einem Kontakt angezeigt. Wenn mehr als 25 Adressen zu einem Kontakt gespeichert sind, haben Sie über die Toolbar die Möglichkeit, in den Seiten zu blättern, eine bestimmte Seite zu wählen und die Anzahl der Adressdatensätze pro Seite auf 50, 75 oder 100 zu ändern. Ihr plentymarkets System merkt sich, welche Anzahl der Adressdatensätze Sie gewählt haben und zeigt beim nächsten Öffnen der Ansicht *Adressen* die zuletzt gewählte Einstellung an.

[.instruction]
Adressen anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherten Adressen werden angezeigt.
. Klicken Sie auf *Bearbeiten*, um die Detailansicht der Adresse zu öffnen. +
→ Wenn Sie die Tabellenansicht gewählt haben, klicken Sie in die Zeile der Adresse, um die Detailansicht zu öffnen.

[#800]
=== Adresse bearbeiten

Sie können bestehende Adressen sowie Adressoptionen jederzeit bearbeiten. Beachten Sie dazu die Erläuterungen im Kapitel <<crm/kontakte-verwalten#600, Adresse hinzufügen>>. Adressoptionen löschen Sie mit einem Klick auf *Adressoption löschen*.

[.instruction]
Adressen bearbeiten:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherten Adressen werden inital als Karten angezeigt.
. Klicken Sie in der Adresskarte, die Sie bearbeiten möchten, auf *Bearbeiten*. +
→ Die Detailansicht der Adresse wird geöffnet.
. Nehmen Sie die Änderungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-adresse-hinzufuegen>> im Kapitel <<crm/kontakte-verwalten#700, Adresse hinzufügen>> sowie die Erläuterungen zur Toolbar in <<tabelle-adresse-bearbeiten>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-adresse-bearbeiten]]
.Adresse bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Speichern*
|Speichert die Einstellungen.

2+|*Rechnungsadresse*

|*Neue Rechnungsadresse ableiten*
|Erstellt eine neue Rechnungsadresse auf Basis der aktuell gewählten Adresse. Um eine neue Adresse mit einer neuen ID zu erstellen, müssen Änderungen an der neuen Rechnungsadresse vorgenommen werden.

|*Rechnungsadresstyp hinzufügen*
|Fügt den Typ *Rechnungsadresse* zu der Adresse hinzu. Die ID ändert sich nicht. +
Diese Einstellung ist nicht sichtbar, wenn für die Adresse bereits der Typ *Rechnungsadresse* hinzugefügt wurde.

|*Rechnungsadresstyp löschen*
|Löscht den Typ *Rechnungsadresse* in der Adresse. +
Diese Einstellung ist nicht sichtbar, wenn der Typ *Rechnungsadresse* nicht für die Adresse hinzugefügt wurde.

|*Als primäre Rechnungsadresse definieren*
|Setzt die aktuell gewählte Rechnungsadresse als primäre Rechnungsadresse. Die ID ändert sich nicht. +
Wenn der Typ *Rechnungsadresse* nicht vorhanden ist, ist diese Option deaktiviert. +
Wenn die Rechnungsadresse als primär definiert wurde, kann man diese Einstellung mit einem Klick auf *Primäre Rechnungsadresse zurücksetzen* wieder rückgängig machen.

|*In Rechnungsadresse umwandeln* / +
*In Lieferadresse umwandeln*
|Wandelt die aktuell gewählte Adresse in die Rechnungsadresse bzw. Lieferadresse um. Die ID ändert sich nicht. +
Wenn beide Adresstypen bereits vorhanden sind, ist diese Option deaktiviert.

2+|*Lieferadresse*

|*Neue Lieferadresse ableiten*
|Erstellt eine neue Lieferadresse auf Basis der aktuell gewählten Adresse. Um eine neue Adresse mit einer neuen ID zu erstellen, müssen Änderungen an der neuen Lieferadresse vorgenommen werden.

|*Lieferadresstyp hinzufügen*
|Fügt den Typ *Lieferadresse* zu der Adresse hinzu. Die ID ändert sich nicht. +
Diese Einstellung ist nicht sichtbar, wenn für die Adresse bereits der Typ *Lieferadresse* hinzugefügt wurde.

|*Lieferadresstyp löschen*
|Löscht den Typ *Lieferadresse* in der Adresse. +
Diese Einstellung ist nicht sichtbar, wenn der Typ *Lieferadresse* nicht für die Adresse hinzugefügt wurde.

|*Als primäre Lieferadresse definieren*
|Setzt die aktuell gewählte Lieferadresse als primäre Lieferadresse. Die ID ändert sich nicht. +
Wenn der Typ *Lieferadresse* nicht vorhanden ist, ist diese Option deaktiviert. +
Wenn die Lieferadresse als primär definiert wurde, kann man diese Einstellung mit einem Klick auf *Primäre Lieferadresse zurücksetzen* wieder rückgängig machen.

|*Adressdatensatz löschen*
|Löscht den Adressdatensatz vollständig.
|====

[#900]
=== Adresse löschen

Sofern es sich bei der Adresse nicht um eine mit einem Auftrag verknüpfte Rechnungsadresse handelt, können Sie Adressen löschen. Dies ist z.B. nötig, wenn die Lieferadresse des Kontakts nicht mehr aktuell ist.

[NOTE]
.Löschen von Rechnungsadressen, die mit Aufträgen verknüpft sind, ist nicht möglich
====
Wenn die Adresse vom Typ *Rechnungsadresse* ist und mit einem Auftrag verknüpft ist, können Sie die Adresse nicht löschen. Eine Fehlermeldung wird angezeigt.
====

[.instruction]
Adresse löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherte Adressen werden inital als Karten angezeigt. +
. Klicken Sie in der Adresskarte, die Sie löschen möchten, auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Die Adresse wird gelöscht und aus der Übersicht entfernt.

[#990]
== Aufträge verwalten

Erfahren Sie in den folgenden Unterkapiteln, wie Sie alle zu Ihrem Kontakt vorhandenen Aufträge anzeigen sowie neue Aufträge zu Ihrem Kontakt anlegen.

[#1000]
=== Aufträge anzeigen

Aus dem geöffneten Kontakt heraus können Sie eine Übersicht aller Aufträge des Kontakts aufrufen.

[.instruction]
Aufträge anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Aufträge*. +
→ Alle zu dem Kontakt gespeicherten Aufträge werden angezeigt. +
. Klicken Sie in die Zeile des Auftrags, um den Auftrag im Menü *Aufträge » Aufträge bearbeiten* zu öffnen und nähere Informationen einzusehen.

Sie können den Auftrag auch bearbeiten. Aufträge können solange bearbeitet werden, bis ein Dokument für diesen Auftrag existiert. Weitere Informationen zu Aufträgen finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/auftraege-verwalten#, Aufträge verwalten>>.

[#1100]
=== Auftrag anlegen

Mit einem Klick haben Sie die Möglichkeit aus dem geöffneten Kontakt heraus manuell einen neuen Auftrag für den Kontakt anzulegen. Wenn der Kontakt im Webshop bestellt, wird der Auftrag automatisch in Ihrem plentymarkets System gespeichert. Bei telefonischen Bestellungen beispielsweise legen Sie den Auftrag manuell an. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Auftrag anlegen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Neuer Auftrag*. +
→ Sie gelangen direkt in den Bereich *Neuer Auftrag* im Menü *Aufträge » Aufträge bearbeiten*. +
. Nehmen Sie die Einstellungen vor. Beachten Sie die Informationen auf der Handbuchseite <<auftragsabwicklung/auftraege/auftraege verwalten#, Aufträge verwalten>>.
. *Speichern* Sie die Einstellungen.

[#1110]
=== Sammelauftrag anlegen

Ein Sammelauftrag bietet die Möglichkeit, nicht bezahlte Aufträge eines Kontakts in einen Auftrag zu übernehmen. Das ist z.B. sinnvoll, wenn Sie mit Ihrem Kontakt vereinbart haben, dass der Kontakt nicht jede Rechnung einzeln, sondern pro Monat oder pro Quartal bezahlt.

Die Aufträge werden wie gewohnt bearbeitet und die Artikel versendet, bleiben jedoch unbezahlt. Das Anlegen eines Sammelauftrags ist nur möglich für Aufträge, die noch nicht bezahlt wurden.

Mit einem Klick auf *Neuer Sammelauftrag* werden alle Aufträge des Kontakts in einen Sammelauftrag zusammengefasst. Sie legen im Vorfeld im Menü *System » Aufträge » Auftragstypen » Multi-Order* fest, welche Bedingungen, wie z.B. Auftragstyp und Auftragsstatus, erfüllt sein müssen, damit ein Sammelauftrag angelegt werden kann.

[.instruction]
Sammelauftrag anlegen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Neuer Sammelauftrag*. +
→ Der Sammelauftrag wird angelegt.

Nachdem der Sammelauftrag erfolgreich angelegt wurde, öffnet sich der Sammelauftrag automatisch im Menü *Aufträge*. Im Sammelauftrag generieren Sie dann im Tab *Belege* eine Sammelrechnung.

Weitere Informationen finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/sammelauftraege#, Sammelaufträge>>.

[#1150]
== Scheduler anzeigen

In der Ansicht *Scheduler* werden Abo-Aufträge des Kontakts angezeigt. Außerdem können neue Scheduler-Aufträge angelegt werden. Über den Scheduler haben Ihre Kunden die Möglichkeit, bestimmte Artikel in Ihrem Webshop im Abonnement zu kaufen. Das Menü ist nur in Ihrem plentymarkets System sichtbar, wenn Sie es gebucht haben. Die Buchung nehmen Sie im Menü *Start » Service-Center » Tab: Vertrag* vor. Im Menü *System » Aufträge » Scheduler* nehmen Sie die Einstellungen für Ihren Webshop vor.

[.instruction]
Scheduler anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Scheduler*. +
→ Alle zu dem Kontakt verfügbaren Abonnements werden angezeigt.
. Beachten Sie die Erläuterungen auf der Handbuchseite <<auftragsabwicklung/auftraege/scheduler#, Scheduler >>.

Weitere Informationen finden Sie auf der Handbuchseite <<auftragsabwicklung/auftraege/scheduler#, Scheduler >>. Dort sind auch die Filteroptionen beschrieben, die Sie sowohl im Menü *CRM » Kontakte » Kontakt öffnen » Ansicht: Scheduler* als auch im Menü *Aufträge » Scheduler » Scheduler-Aufträge* wählen können.


[#1190]
== Tickets verwalten

Erfahren Sie in den folgenden Unterkapiteln, wie Sie Tickets erstellen und alle zu einem Kontakt vorhandenen Tickets aufrufen. Abhängig vom verwendeten plentymarkets Tarif müssen Sie das Ticketsystem ggf. buchen, bevor es Ihnen zur Verfügung steht.

[#1200]
=== Ticket erstellen

Das <<crm/ticketsystem-nutzen#, Ticketsystem>> in plentymarkets nutzen Sie zur Verwaltung Ihrer Kundenkommunikation. Erfahren Sie im Folgenden, wie Sie ein neues Ticket direkt aus dem geöffneten Kontakt heraus erstellen.

[.instruction]
Ticket erstellen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Neues Ticket*. +
→ Sie gelangen direkt in den Bereich *Neues Ticket* im Menü *CRM » Ticketsystem*. Die Kontakt-ID ist bereits vorausgefüllt. +
. Nehmen Sie die Einstellungen vor. Beachten Sie die Informationen auf der Handbuchseite <<crm/ticketsystem-nutzen#1600, Ticketsystem nutzen>>.
. *Speichern* Sie die Einstellungen.

[#1300]
=== Tickets anzeigen

Aus dem geöffneten Kontakt heraus können Sie alle zu dem Kontakt gespeicherten Tickets im Menü *CRM » Ticketsystem* aufrufen. Beim Wechsel in das Menü wird in der Ticketsuche automatisch initial auch nur nach Tickets von Kontakten mit der ID gesucht.

[.instruction]
Tickets anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Tickets*. +
→ Alle zu dem Kontakt gespeicherten Tickets werden angezeigt.

Sie haben die Möglichkeit Tickets zu bearbeiten und zu löschen. Beachten Sie dazu die Handbuchseite <<crm/ticketsystem-nutzen#, Ticketsystem nutzen>>.

[#1390]
== Notizen verwalten

Erfahren Sie in den folgenden Unterkapiteln, wie Sie neue Notizen zu Ihrem Kontakt erstellen, alle zu einem Kontakt vorhandenen Notizen aufrufen sowie vorhandene Notizen bearbeiten und löschen. Notizen sind nur in Ihrem plentymarkets Backend sichtbar und können nicht von Ihren Kontakten aufgerufen werden.

[#1400]
=== Notiz erstellen

Speichern Sie zu jedem Ihrer Kontakte beliebig viele Notizen. Notizen sind nur in Ihrem plentymarkets Backend sichtbar, d.h. Kontakte können die gespeicherten Notizen nicht im Webshop sehen. Jede Notiz erhält nach dem Speichern eine fortlaufende ID. Neue Texte geben Sie über die Tastatur ein oder fügen Sie über die Zwischenablage ein. Mit den Funktionen in der Symbolleiste formatieren Sie den Text, fügen Verlinkungen ein und laden Bilddateien hoch.

[.instruction]
Notiz erstellen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Öffnen Sie das Kontextmenü mit einem Rechtsklick in die Zeile des Kontakts.
. Klicken Sie auf *Neue Notiz*. +
. *_Oder:_*: Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Neue Notiz*. +
→ Das Fenster *Neue Notiz* wird geöffnet.
. Geben Sie den Text ein, fügen Sie Text über die Zwischenablage ein und formatieren Sie ggf. den Text mit den Funktionen in der Symbolleiste.
. *Speichern* Sie die Einstellungen. +
→ Der Bereich *Notizen* wird geöffnet und die Notiz wird der Übersicht hinzugefügt.

[#1500]
=== Notizen anzeigen

Aus dem geöffneten Kontakt heraus lassen sich alle zu dem Kontakt gespeicherten Notizen in Form von Karten anzeigen. Die Karten zeigen das Erstellungsdatum mit Uhrzeit, den Benutzernamen, der die Notiz erstellt hat, und die ID an.

[.instruction]
Notizen anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Notizen*. +
→ Alle zu dem Kontakt gespeicherten Notizen werden angezeigt.

[.subhead]
Einzelne Notiz öffnen

Sie können einzelne Notizen mit einem Klick auf *Vorschau öffnen* anzeigen. Wenn mehr als eine Notiz des Kontakts geöffnet ist, wird in der Ansicht ein Pfeil angezeigt, über den man zwischen den geöffneten Notizen einfach und schnell hin- und herwechseln kann. Mit einem Klick auf das Kreuz wird die Notiz geschlossen und aus der Liste entfernt.

[#1600]
=== Notiz bearbeiten

Bearbeiten Sie Notizen, um Inhalte zu aktualisieren. Sie haben die Möglichkeit, den Text zu formatieren, Verlinkungen einzufügen und Bilddateien hochzuladen.

[.instruction]
Notiz bearbeiten:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Notizen*. +
→ Alle zu dem Kontakt gespeicherten Notizen werden angezeigt.
. Klicken Sie in der Notiz, die Sie bearbeiten möchten, auf *Bearbeiten*.
. Nehmen Sie die Änderungen vor.
. *Speichern* Sie die Einstellungen.

[#1700]
=== Notiz löschen

Die Notizen Ihrer Kontakte können jederzeit gelöscht werden, wenn die darin gespeicherten Informationen veraltet sind oder Sie diese nicht mehr benötigen.

[.instruction]
Notiz löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Notizen*. +
→ Alle zu dem Kontakt gespeicherten Notizen werden angezeigt.
. Klicken Sie in der Notiz, die Sie löschen möchten, auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird geöffnet.
. Klicken Sie auf *Löschen*. +
→ Die Notiz wird gelöscht und aus der Übersicht entfernt.

Sie können die Notiz auch löschen, wenn die Vorschau geöffnet ist. Dazu klicken Sie in der geöffneten Notiz auf *Löschen*. In diesem Fall wird ebenfalls eine Sicherheitsabfrage, die Sie mit *Löschen* bestätigen müssen, angezeigt.

[#1710]
== Dokumente verwalten

Erfahren Sie in den folgenden Unterkapiteln, wie Sie Dokumente zu Ihren Kontakten hochladen, anzeigen, herunterladen und löschen. Die Dokumente, die Sie in diesem Menü hochladen, sind nur in Ihrem plentymarkets Backend sichtbar und können nicht von Ihren Kontakten aufgerufen werden.

[#1720]
=== Kundendokumente hochladen

In der Ansicht *Dokumente* laden Sie Dokumente wie z.B. eine bereits im Vorfeld selbst durchgeführte Altersprüfung zu Ihrem Kontakt hoch. Entweder laden Sie die Dateien über *Datei hochladen* oder per Drag&Drop in diesen Bereich hoch. Erstellen Sie Ordner, um die Dokumente übersichtlicher zu gruppieren.

Zulässig sind Datenformate wie JPEG, PNG, GIF, TIFF, PDF, DOC, ODC, OTH, XLS, XML, HTML, HTM, CSS, ZIP und GZIP.

[.instruction]
Kundendokumente hochladen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakte verwalten>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Dokumente*.
. Klicken Sie auf *Dateien hochladen*.
. Wählen Sie die Dokumente aus.
. Klicken Sie auf *Öffnen*, um die Dateien hochzuladen oder ziehen Sie Dokumente per Drag-and-Drop-Funktion in das Tab.

[NOTE]
.Ordner erstellen
====
Erstellen Sie in der Ansicht *Dokumente* Ordner, wenn Sie viele Dokumente zu Ihrem Kontakt hochgeladen haben. Dies ermöglicht eine Gruppierung der Dokumente und somit eine bessere Übersicht.
====

[#1730]
=== Dokumente anzeigen

In der Ansicht *Dokumente* sehen Sie alle zum Kontakt verfügbaren Dokumente, die Sie hochgeladen haben. In der Übersicht sind der Dateiname, die Dateigröße sowie das Datum und die Uhrzeit der letzten Änderung zu sehen.

[.instruction]
Dokumente anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Dokumente*. +
→ Alle zu dem Kontakt gespeicherten Dokumente werden angezeigt.

[#1740]
=== Dokument herunterladen

Sie haben die Möglichkeit, alle Dokumente, die Sie zu Ihrem Kontakt hochgeladen haben, herunterzuladen.

[.instruction]
Dokument herunterladen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Dokumente*. +
→ Alle zu dem Kontakt gespeicherten Dokumente werden angezeigt.
. Klicken Sie in der Zeile des Dokuments, das Sie herunterladen möchten, auf *Datei herunterladen*. +
→ Das Fenster zum Festlegen des Speicherorts wird geöffnet.
. Wählen Sie den Speicherort auf Ihrem Computer und speichern Sie das Dokument.

[#1750]
=== Dokument löschen

Löschen Sie ein Dokument, wenn Sie das Dokument nicht mehr benötigen. Wie Sie mehrere Dokumente gleichzeitig löschen, ist in der Box am Ende des Kapitels beschrieben.

[.instruction]
Dokument löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Dokumente*.
. Klicken Sie in der Zeile des Dokuments, das Sie löschen möchten, auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt. +
. Klicken Sie auf *Löschen*. +
→ Das Dokument wird gelöscht und aus der Übersicht entfernt.

[TIP]
.Mehrere oder alle Dokumente löschen
====
Markieren Sie in der Ansicht *Dokumente* die Dokumente, die Sie löschen möchten, oder aktivieren Sie die Option neben *Dateiname*, um alle gespeicherten Dokumente zu markieren und anschließend zu löschen. Nachdem Sie die Sicherheitsabfrage mit *Löschen* bestätigt haben, werden die markierten Dokumente gelöscht und aus der Übersicht entfernt.
====

[#1800]
== Kontostand anzeigen

In der Ansicht *Konto* sehen Sie die Umsätze Ihres Kontakts. In der obersten Zeile sehen Sie neben dem Kontostand des Kontakts die Summe der Rechnungen des Kontakts, was Sie ihm in Form von Gutschriften gutgeschrieben haben und wie hoch die Differenz zwischen diesen beiden Beträgen ist. In der Tabelle sind die Aufträge und Gutschriften zu diesem Kunden als Vorgänge aufgeführt. Dabei sind die Spalten *Gezahlt* und *Ausstehend* besonders hilfreich. Wenn bei einem Auftrag ein Betrag unter *Ausstehend* aufgeführt ist, muss der Kontakt diesen Betrag noch an Sie zahlen. Sobald der Kontakt bezahlt hat, wird der Betrag unter *Gezahlt* aufgeführt. Wenn bei einer Gutschrift noch ein Betrag unter *Ausstehend* aufgeführt ist, müssen Sie diesen Betrag noch an den Kontakt zahlen. Sobald Sie gezahlt haben, wird der Betrag unter *Gezahlt* aufgeführt.

[.instruction]
Kontostand anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Konto*. +
→ Alle verfügbaren Daten zum Kontostand des Kontakts werden angezeigt.
. Beachten Sie die Erläuterungen in <<tabelle-kontostand-kontakt>>.

[[tabelle-kontostand-kontakt]]
.Einstellungen im Menü *CRM » Kontakte » Kontakt öffnen » Ansicht: Konto*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Saldo*
|Zeigt den Kontostand des Kontakts an. +
*+* = Summe der noch vom Kontakt zu zahlenden Beträge +
*-* = Summe der noch an den Kontakt zu zahlenden Beträge, wenn der Kontakt zu viel gezahlt hat oder eine Gutschrift noch ausgezahlt werden muss. +
*0,0* = keine ausstehenden Beträge

|*Rechnungen*
|Summe der Rechnungsbeträge aller Aufträge und die Anzahl der Rechnungen in Klammern

|*Gutschriften*
|Summe aller Gutschriften und die Anzahl der Gutschriften in Klammern

|*Delta*
|Differenz in Prozent zwischen den gezahlten Gutschriften und dem insgesamt bezahlten Rechnungsbetrag des Kontakts. Bei 0 % wurde dem Kontakt noch keine Gutschrift ausgezahlt. Bei 100 % wurde dem Kontakt jeder bezahlte Betrag wieder als Gutschrift zurückgezahlt.

|*Datum*
|Datum, an dem der Auftrag erstellt wurde

|*Auftrags-ID*
|ID des Auftrags. Ein Klick auf die ID öffnet die Detailansicht des Auftrags. IDs von Gutschriften sind eingerückt und unterhalb des Auftrags dargestellt.

|*Vorgang*
|Auftragsart, entweder Auftrag oder Gutschrift

|*Dokument*
|Dokumentennummer, z.B. Rechnungsnummer. Ein Klick auf die Nummer öffnet das Dokument.

|*Wert*
|Rechnungssumme des Auftrags

|*Gezahlt*
|Der bereits bezahlte Betrag

|*Zahlungsart*
|Zahlungsart des Auftrags

|*Ausstehend*
|Der zur vollständigen Bezahlung des Auftrags noch ausstehende Betrag.

|*Status*
|Status des Auftrags. Ein Klick auf den Status öffnet das Bearbeitungsfenster *Auftragsstatus*, in dem der Status geändert werden kann.

|====

[.subhead]
Kontodaten filtern 

Verwenden Sie Filter, um den Kontostand Ihres Kontakts anzuzeigen.

[.instruction]
Kontodaten filtern:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Konto*. +
→ Alle verfügbaren Daten zum Kontostand des Kontakts werden angezeigt.
. Nehmen Sie die Filtereinstellungen im Bereich *Filter* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-filter-kontodaten>>.
. Klicken Sie auf *Suchen*.

[[tabelle-filter-kontodaten]]
.Filtereinstellungen im Menü *CRM » Kontakte » Kontakt öffnen » Ansicht: Konto*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Suche ausführen. Die gefundenen Kontodaten werden aufgelistet.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*Zeitraum*
|Eine der folgenden Einstellungen aus der Dropdown-Liste wählen: *ALLE*, *Dieses Jahr*, *Letztes Jahr*, *Diesen Monat*, *Letzten Monat* oder *Letzte 3 Monate*.

|*Ausstehend*
|*ALLE*, *Ja* oder *Nein* wählen. +
*Ja* = Nur ausstehende Beträge werden angezeigt. +
*Nein* = Nur gezahlte Beträge werden angezeigt. +
*ALLE* = Ausstehende und gezahlte Beträge werden angezeigt.

|*Vergleichsoperator / Status*
|Vergleichsoperator und Auftragsstatus aus den Dropdown-Listen wählen.

|*Rechnungsnr.*
|Rechnungsnummer eingeben.

|*Auftrags-ID*
|Auftrags-ID eingeben.

|====

[#1890]
== Bankdaten verwalten

Erfahren Sie in den folgenden Unterkapiteln, wie Sie neue Bankdaten zu Ihrem Kontakt hinzufügen sowie bestehende Bankdaten bearbeiten und löschen.

[#1900]
=== Bankdaten hinzufügen

In der Ansicht *Bankdaten* fügen Sie die Bankdaten Ihres Kontakts hinzu. Fügen Sie beliebig viele Bankdatensätze hinzu.

Die Bankdatensätze werden nach dem Speichern in Form von Karten dargestellt und zeigen neben dem Namen des Inhabers und der IBAN ein Tag, wenn das SEPA-Lastschriftmandat für den Kontakt aktiviert ist. Sofern im Bankdatensatz die BIC gespeichert ist, wird diese auch auf der Karte angezeigt.

[.instruction]
Bankdaten hinzufügen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Bankdaten*.
. Klicken Sie auf *Hinzufügen*. +
→ Die Ansicht *Neue Bankdaten* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-bankdaten-kontakt>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-bankdaten-kontakt]]
.Einstellungen im Menü *CRM » Kontakte » Kontakt öffnen » Ansicht: Bankdaten*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*IBAN*, *BIC*, *Inhaber*, *Kontonummer*, *Bankleitzahl*
|Bankdaten des Kontakts eingeben. *IBAN* und *Inhaber* sind Pflichtfelder.

|*Name, Straße, PLZ und Ort der Bank*
|Name und Adresse der Bank eingeben.

|*Land der Bank*
|Land aus der Dropdown-Liste wählen.

|*SEPA-Lastschriftmandat*
|Option aktivieren, wenn der Kontakt das SEPA-Lastschriftmandat unterschrieben hat. +
*_Wichtig:_* Erst nach dem Aktivieren dieser Option können die pain.008-Formate für den <<auftragsabwicklung/payment/bankdaten-verwalten#200, SEPA-Zahlungsverkehr>> abgerufen werden.

|*SEPA-Lastschriftmandat erteilt am*
|Nur sichtbar, wenn die Option *SEPA-Lastschriftmandat* aktiviert wurde. +
Das Datum, an dem der Kontakt dem SEPA-Lastschriftmandat zugestimmt hat, wird angezeigt. Oder das Datum aus dem Kalender wählen.

|*Art des Mandats*
|Nur sichtbar, wenn die Option *SEPA-Lastschriftmandat* aktiviert wurde. +
Option aus der Dropdown-Liste wählen: +
*SEPA-Basis-Lastschrift* = Mit der Einzugsermächtigung (Standardkunden) vergleichbares Mandat. +
*SEPA-Firmen-Lastschrift* = Mit dem Buchungsauftrag (Firmenkunden, B2B) vergleichbares Mandat.

|*Ausführungsmodalität*
|Nur sichtbar, wenn die Option *SEPA-Lastschriftmandat* aktiviert wurde. +
Option aus der Dropdown-Liste wählen: +
*Einmalige Zahlung* = Wird typischerweise für Standardaufträge verwendet. +
*Wiederkehrende Zahlung* = Wird typischerweise für regelmäßige Abbuchungen, Abo-Verträge etc. verwendet.
|====

[#2000]
=== Bankdaten bearbeiten

Sie haben die Möglichkeit, die Bankdaten Ihrer Kontakte jederzeit zu aktualisieren.

[.instruction]
Bankdaten bearbeiten:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Bankdaten*.
. Klicken Sie im Bankdatensatz, den Sie bearbeiten möchten, auf *Bearbeiten*. +
→ Der Bankdatensatz wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-bankdaten-kontakt>>.
. *Speichern* Sie die Einstellungen.

[#2100]
=== Bankdaten löschen

Löschen Sie Bankdatensätze Ihrer Kontakte, wenn die Daten nicht mehr aktuell sind.

[.instruction]
Bankdaten löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Bankdaten*.
. Klicken Sie im Bankdatensatz, den Sie löschen möchten, auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Der Bankdatensatz wird gelöscht und aus der Übersicht entfernt.

[#2200]
== Events verwalten

Erfahren Sie in den folgenden Unterkapiteln, wie Sie Events zu Ihren Kontakten hinzufügen, anzeigen und löschen. Kostenpflichtige Events können auch abgerechnet werden.

[#2300]
=== Event hinzufügen

Fügen Sie beliebig viele Events hinzu. Ein Event kann z.B. ein Anruf oder E-Mail sein. Sie können außerdem die Dauer eingeben, eine Information zum Vorgang wählen und einen Kommentar zum Event speichern. Wenn Sie das Event kostenpflichtig abrechnen möchten, klicken Sie beim Hinzufügen des Events auf *Hinzufügen und abrechnen*.

[.instruction]
Event hinzufügen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Events*.
. Wählen Sie den Typ aus der Dropdown-Liste.
. Geben Sie die Dauer des Events in Minuten ein.
. Wählen Sie die Info aus der Dropdown-Liste.
. Geben Sie den Infotext ein.
. Klicken Sie auf *Event hinzufügen*. +
→ Wählen Sie *Hinzufügen und abrechnen* oder *Hinzufügen*. Das Event wird der Liste hinzugefügt.

[#2400]
=== Events anzeigen

Sie können die Events, die Sie zu Ihren Kontakten gespeichert haben, jederzeit einsehen.

Außerdem ist es möglich, die Dauer des Events direkt aus der Übersicht heraus zu aktualisieren. Wie Sie dazu vorgehen, ist in der Box am Ende des Kapitels beschrieben.

[.instruction]
Events anzeigen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Events*. +
→ Die Liste der Events wird angezeigt.

[TIP]
.Dauer des Events aktualisieren
====
Sie haben die Möglichkeit, die Dauer von bestehenden Events zu aktualisieren. Klicken Sie dazu in der Übersicht der Events auf *Dauer aktualisieren*. Das Fenster *Event-Dauer aktualisieren* wird daraufhin geöffnet. Geben Sie dort die neue Zahl in Minuten ein und klicken Sie auf *Aktualisieren*.
====

[#2500]
=== Event löschen

Löschen Sie nicht mehr benötigte Events aus der Übersicht.

[.instruction]
Event löschen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Events*. +
→ Die Liste der Events wird angezeigt.
. Klicken Sie in der Zeile des Events, das Sie löschen möchten, auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Das Event wird gelöscht und aus der Übersicht entfernt.

[#2600]
== Zugangsdaten bearbeiten

In der Ansicht *Zugangsdaten* haben Sie die Möglichkeit, das Passwort für Ihren Kontakt manuell zu ändern, einen Link zum Ändern des Passworts zu versenden, den Login zu entsperren und den Mein Konto-Bereich des Kontakts über die Login-URL zu öffnen.

[#2700]
=== Passwort ändern

Ändern Sie im Bereich *Passwort ändern* das Passwort manuell für Ihren Kontakt.

[.instruction]
Passwort ändern:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Zugangsdaten*.
. Geben Sie im Bereich *Passwort ändern* das Passwort ein.
. Klicken Sie auf *Passwort speichern*.


[#2750]
=== Passwörter für alle Konakte neu generieren

Im Menü *System » CRM » Passwörter* generieren Sie neue Passwörter für Ihre Kontakte. Dies kann z.B. nötig sein, wenn sich jemand widerrechtlich Zutritt zu Ihrem plentymarkets System verschafft hat bzw. Sie von Datendiebstahl betroffen sind.

[TIP]
.Kein automatischer Versand der neu generierten Passwörter
====
Beachten Sie, dass Ihre Kontakte die neu generierten Passwörter nicht automatisch erhalten. Sie müssen Ihre Kontakte aktiv, z.B. per E-Mail, über die Sachlage informieren und sie auffordern, ihr Passwort im Webshop bzw. Mein Konto-Bereich zu ändern.
====

Gehen Sie wie im Folgenden beschriebenen vor, um neue Passwörter für alle Kontakte zu generieren.

[.instruction]
Passwörter für alle Kontakte neu generieren:

. Öffnen Sie das Menü *System » CRM » Passwörter*.
. Klicken Sie auf *Passwörter für alle Kunden neu generieren*. +
→ Die neuen Passwörter werden generiert.

[#2800]
=== Link zur Passwortänderung versenden

Senden Sie Ihrem Kontakt eine E-Mail-Vorlage mit einem Link zur Passwortänderung in Ihrem Webshop. Voraussetzung dafür ist, dass Sie im Menü *System » Mandant » Mandant wählen » E-Mail » Automatischer Versand* eine E-Mail-Vorlage, die die Template-Funktion *{% Link_ChangePassword() %}* enthält, mit dem Ereignis *Sende Kunde E-Mail zur Passwortänderung* verknüpft haben.

Weitere Informationen zum automatischen E-Mail-Versand finden Sie auf der Handbuchseite <<crm/e-mails-versenden#2300, E-Mails versenden>>.

[.instruction]
Link zur Passwortänderung versenden:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Zugangsdaten*.
. Klicken Sie auf *Link zur Passwortänderung*. +
→ Der Kontakt erhält eine E-Mail mit dem Link zur Passwortänderung in Ihrem Webshop.

[#2900]
=== Login entsperren

Wenn der Kontakt das Passwort beim Login in Ihrem Webshop mehrmals hintereinander falsch eingegeben hat, wird der Kontakt für das Login eine gewisse Zeit gesperrt. Mit einem Klick auf *Login entsperren* entsperren Sie frühzeitig das Login und der Kontakt kann sich wieder einloggen.

[.instruction]
Login entsperren:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Zugangsdaten*.
. Klicken Sie auf *Login entsperren*. +
→ Der Kontakt kann sich erneut in Ihrem Webshop anmelden.

[#3000]
=== Mein Konto-Bereich des Kontakts öffnen

Im Bereich *Login-URL* wird die URL für einen direkten Zugang zum Mein Konto-Bereich des Kontakts im Webshop angezeigt. Wenn diese URL verwendet wird, ist eine Eingabe der Login-Daten (E-Mail-Adresse und Passwort) im Webshop nicht mehr nötig.

Damit die Login-URL automatisch erzeugt wird, muss sowohl die E-Mail-Adresse im Menü *CRM » Kontakte » Kontakt öffnen* im Bereich *Kontaktoptionen* als auch das Passwort im Menü *CRM » Kontakte » Kontakt öffnen » Bereich: Zugangsdaten* gespeichert sein. Nach dem Speichern wird die Login-URL erzeugt. Verwenden Sie ein sicheres Passwort, andernfalls wird eine Fehlermeldung ausgegeben.

[.instruction]
Mein Konto-Bereich des Kontakts öffnen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Zugangsdaten*.
. Klicken Sie im Bereich *Login-URL* auf *Link öffnen* oder kopieren Sie die Login-URL mit einem Klick auf *In Zwischenablage kopieren* und fügen den Link in den Browser ein. +
→ Der Mein Konto-Bereich des Kontakts im Webshop wird geöffnet.

[#3100]
== Provisionen verwalten

Im Tab *Artikelprovisionen* geben Sie artikelbezogene Provisionen für den Typ *Handelsvertreter* ein. Gehen Sie wie im Folgenden beschrieben vor, um Werte für Provisionen einzugeben.

[.instruction]
Provision eingeben:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Provision & Kostenstellen*.
. Wechseln Sie in das Tab *Provisionen*.
. Wechseln Sie in das Tab *Artikelprovisionen*.
. Klappen Sie den Bereich *Neue Provision* auf.
. Geben Sie die *Artikel-ID* des Artikels ein, für den Sie eine oder mehrere Provision(en) eingeben möchten.
. Geben Sie die Provision(en) in Prozent ein. +
→ Geben Sie bis zu 4 Provisionen pro Eintrag ein.
. *Speichern* Sie die Einstellungen. +
→ Die Provision wird gespeichert. Damit Sie auf einen Blick erkennen können, um welchen Artikel es sich handelt, wird nach erneutem Laden durch Klick auf das Tab *Einstellungen* oder das Tab mit der Kontakt-ID zusätzlich der Name des Artikels in der Übersicht angezeigt.

[#3200]
== Kostenstellen verwalten

Im Bereich *Kostenstellen* erstellen Sie Kostenstellen. Sie haben auch die Möglichkeit, bereits angelegte Kostenstellen zu bearbeiten. Bei einer Kostenstelle handelt es sich um den Ort der Kostenentstehung und Kostenzurechnung, quasi ein betrieblicher Bereich, der selbstständig abgerechnet wird.

[.instruction]
Kostenstelle erstellen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Provision & Kostenstellen*.
. Wechseln Sie in das Tab *Neue Kostenstelle*.
. Geben Sie den *Kostenstellennamen*, das *Budget* und das *Restbudget* ein.
. Wählen Sie *Jahr* oder *Monat* als Budgetperiode.
. *Speichern* Sie die Einstellungen. +
→ Die Kostenstelle wird der Übersicht hinzugefügt.

[#3300]
== Statistik erstellen

Im Bereich *Statistik* erstellen Sie kundenspezifische Statistiken. Damit können Sie bestimmte Daten speziell für diesen Kontakt auswerten und als Statistik anzeigen, z.B. den Gesamtumsatzverlauf des Kontakts in einem bestimmten Zeitraum. Bestehende Statistiken können Sie in diesem Bereich auch bearbeiten. Weitere Informationen finden Sie im Kapitel <<basics/statistik/statistiken-verwalten#100, Kundenstatistiken>>.

[.instruction]
Statistik erstellen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicken Sie im Kontextmenü auf der linken Seite auf *Statistik*.
. Klicken Sie auf *Neuer Bereich*.
. Geben Sie einen Namen ein.
. *Speichern* Sie die Einstellungen. +
→ Ein Tab mit dem soeben eingegebenen Namen wird geöffnet.
. Klicken Sie auf *Hinzufügen*. +
→ Das Fenster *Neue Statistik* wird geöffnet.
. Wählen Sie den Statistiktyp aus dem Dropdown-Menu.
. *Speichern* Sie die Einstellungen. +
→ Die Daten werden geladen und angezeigt.

Je nachdem, welchen Statistiktyp Sie gewählt haben, finden Sie weitere Informationen in den folgenden Kapiteln der Handbuchseite <<basics/statistik/statistiken-verwalten#, Statistiken verwalten>>:

* <<basics/statistik/statistiken-verwalten#20, Gesamtumsatzverlauf>>
* <<basics/statistik/statistiken-verwalten#100, Umsatz nach Kategorie>>
* <<basics/statistik/statistiken-verwalten#100, Umsatz Herkunft Auftrag>>

Allgemeine Informationen, wie Sie z.B. Statistiken bearbeiten, finden Sie auf der Handbuchseite <<basics/statistik/statistiken-verwalten#, Statistiken verwalten>>.


[#4000]
== Eigenschaften verwalten

Eigenschaften sind wiederholt auftretende Informationen, die Sie in verschiedenen Bereichen von plentymarkets anwenden. Eigenschaften werden zentral im Menü *System » Einstellungen » Eigenschaften » Konfiguration* verwaltet.

// und können in den folgenden Bereichen von plentymarkets eingesetzt werden:

//* Kontakte

[WARNING]
.Wichtige Hinweise zu den Kontakteigenschaften
====
Beachten Sie, dass die Kontakteigenschaften im Menü *CRM » Kontakte » Kontakt öffnen » Ansicht: Eigenschaften* erst in Kürze zur Verfügung stehen. Die Eigenschaften können dann vorerst ausschließlich über das plentymarkets Backend hinzugefügt und angezeigt werden. Das heißt, es ist vorerst nicht möglich, dass der Kontakt Daten in Ihrem Webshop, z.B. während des Bestellvorgangs oder wenn der Kontakt sich in Ihrem Webshop registriert, eingeben kann. Diese Funktionalität befindet sich derzeit in Arbeit.

Sie können Eigenschaften jedoch schon im Menü *System » Einstellungen » Eigenschaften » Konfiguration* erstellen sowie Werte hinzufügen.

*_Wichtig:_* Für die Eigenschaften, die Sie in der Vergangenheit im Menü *System » CRM » Eigenschaften* erstellt haben, ist eine Migration geplant. Das heißt, Sie müssen die dort erstellten Eigenschaften nicht in das neue Menü *System » Einstellungen » Eigenschaften » Konfiguration* übertragen. Wir informieren Sie über den Zeitpunkt der Migration in der Forumskategorie link:https://forum.plentymarkets.com/c/changelog[Changelog^].

====

[#4100]
=== Eigenschaft erstellen

Im Menü *System » Einstellungen » Eigenschaften » Konfiguration* erstellen Sie Eigenschaften, die Sie im Anschluss für die nähere Charakterisierung Ihrer Kontakte nutzen.

//Für die spätere Verwendung der Eigenschaften haben Sie 2 Möglichkeiten: Sie können die Informationen entweder im Bestellvorgang oder in der Kundenregistrierung von Ihren Kontakten abfragen oder Sie nutzen die Eigenschaften, um selbst Informationen zu den Kontakten im Kontaktdatensatz zu speichern.

//Im Fall der Abfrage vom Kontakt bestimmen Sie, ob die Angabe ein Pflichtfeld ist und somit zwingend durch den Kontakt eingegeben werden muss. Sie können beispielsweise bei der Registrierung abfragen, wie der Kontakt auf Ihren Webshop aufmerksam geworden ist. Für die Eigenschaft wählen Sie dann als *Typ* die Option *Text einzeilig* oder die Option *Text mehrzeilig*, damit der Kontakt die Information dort eingeben kann.

Gehen Sie wie im Folgenden beschrieben vor, um eine Eigenschaft zu erstellen.

[.instruction]
Eigenschaft erstellen:

. Öffnen Sie das Menü *System » Einstellungen » Eigenschaften » Konfiguration*. +
→ Die Übersicht der Eigenschaften wird geöffnet.
. Klicken Sie auf *Eigenschaft hinzufügen*.
. Wählen Sie in der Dropdown-Liste *Bereich* die Option *Kontakt*.
. Nehmen Sie die weiteren Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-eigenschaft-erstellen>>.
. *Speichern* Sie die Einstellungen. +
→ Die Eigenschaft wird erstellt und zur weiteren Bearbeitung geöffnet.

[[tabelle-eigenschaft-erstellen]]
.Eigenschaften erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Bereich*
|Bereich aus der Dropdown-Liste wählen, in dem die Eigenschaft genutzt werden soll. +
*Artikel* = Eigenschaft wird für Artikel verwendet. +
//*Stock* = Eigenschaft wird für die Lagerverwaltung verwendet. +
*Kontakt* = Eigenschaft wird für Kontakte verwendet. +

|*Eigenschaftstyp*
|Typ der Eigenschaft aus der Dropdown-Liste wählen. +
*Kein* = Kein Eigenschaftstyp +
*Ganze Zahl* = Ermöglicht die Eingabe einer ganzen Zahl. +
*Kommazahl* = Ermöglicht die Eingabe einer Zahl mit Kommastellen. +
*Auswahl* = Ermöglicht es, aus mehreren Optionen zu wählen. +
*Kurztext* = Kurztext eingeben. +
//Ermöglicht die Eingabe eines Textes mit bis zu XXX Zeichen. +
*Text* = Text eingeben. +
//Ermöglicht die Eingabe eines Textes mit bis zu XXX Zeichen. +
*Datum* = Ermöglicht die Eingabe eines Datums. +
//*Datei* = Ermöglicht das Hochladen einer Datei.

|*Name*
|Name für die Eigenschaft eingeben. +
//Dieser Name wird z.B. im Bestellvorgang angezeigt. +
*_Hinweis:_* Standardmäßig wird der Name für die Systemsprache angezeigt. Nachdem die Eigenschaft erstellt wurde, können Sie den Namen in englischer Sprache speichern. Weitere Sprachen sind in Planung.

|*Beschreibung*
|Beschreibung der Eigenschaft eingeben. +
*_Hinweis:_* Standardmäßig wird die Beschreibung für die Systemsprache angezeigt. Nachdem die Eigenschaft erstellt wurde, können Sie die Beschreibung in englischer Sprache speichern. Weitere Sprachen sind in Planung.

|*Gruppe*
|Optional eine Eigenschaftsgruppe aus der Dropdown-Liste wählen, um die Eigenschaft dieser Gruppe zuzuordnen. +
*_Tipp:_* Auf *Eigenschaftsgruppe hinzufügen* klicken, um eine Gruppe zu erstellen.

|*Position*
|Positionsnummer für die Eigenschaft eingeben. Standardmäßig wird aufsteigend nach Positionsnummer sortiert. +
*_Tipp:_* Positionsnummern in 10er-Schritten vergeben, damit neue Eigenschaften dazwischen eingefügt werden können.
|====

[#4200]
=== Eigenschaft bearbeiten

Im Menü *System » Einstellungen » Eigenschaften » Konfiguration* finden Sie alle Eigenschaften. Hier ändern Sie die in <<tabelle-eigenschaft-erstellen>> beschriebenen Einstellungen.

[.instruction]
Eigenschaft bearbeiten:

. Öffnen Sie das Menü *System » Einstellungen » Eigenschaften » Konfiguration*.
. Klicken Sie auf *Suchen*, um alle Eigenschaften anzuzeigen oder wählen Sie Filter, um die Ergebnisse einzugrenzen.
. Klicken Sie auf die Eigenschaft. +
→ Das Tab *Allgemein* wird geöffnet.
. Bearbeiten Sie die Einstellungen. Beachten Sie die Erläuterungen in <<tabelle-eigenschaft-bearbeiten>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-eigenschaft-bearbeiten]]
.Eigenschaften bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Allgemein*

|*Position*
|Neue Position eingeben, um die Anzeigereihenfolge zu ändern.

|*Pflichtfeld* (aktuell ohne Funktion)
|Aktivieren, damit die Eigenschaft zu einer Pflichteingabe wird. Pflichtfelder werden in der Detailansicht des Kontakts im Bereich *Eigenschaften* und ggf. im Bestellvorgang fett markiert. +
*_Hinweis:_* Diese Einstellung ist aktuell noch ohne Funktion.

|*Bestellvorgang* (aktuell ohne Funktion)
|Aktivieren, damit die Eigenschaft im Bestellvorgang angezeigt wird. +
*_Hinweis:_* Diese Einstellung ist aktuell noch ohne Funktion.

|*Kundenregistrierung* (aktuell ohne Funktion)
|Aktivieren, damit die Eigenschaft in der Kundenregistrierung angezeigt wird. +
*_Hinweis:_* Diese Einstellung ist aktuell noch ohne Funktion.

|*Name*; +
*Beschreibung*
|Für Mehrsprachigkeit Name und Beschreibung für weitere Sprachen eingeben. +
*_Hinweis:_* Aktuell können Namen und Beschreibungen nur in deutscher und englischer Sprache gespeichert werden. Weitere Sprachen sind in Planung.

2+|*Sichtbarkeit*

|*Mandant*
|Einen oder mehrere Mandanten wählen, um die Eigenschaft für diese Mandanten zu aktivieren.

|*Sichtbarkeit*
|Einen oder mehrere Typen wählen, für die die Eigenschaft sichtbar sein soll.

2+|*Werte*

|Nur bei Eigenschaftstyp *Auswahl*
|Die Werte eingeben, die in der Dropdown-Liste dargestellt werden sollen. +
Auf *Wert hinzufügen* klicken, um einen Wert zu erstellen. +
*Name* = Name für den Eigenschaftswert eingeben.
|====

[#4300]
=== Eigenschaft suchen

Eigenschaften verwalten Sie zentral im Menü *System » Einstellungen » Eigenschaften » Konfiguration*. Führen Sie nach dem Öffnen des Menüs eine Suche aus, um Eigenschaften anzuzeigen. Um Eigenschaften nach bestimmten Kriterien zu suchen, geben Sie die Ihnen bekannten Suchbegriffe in die Filter ein. Die Dropdown-Listen helfen Ihnen, Eigenschaften zu suchen, die bestimmte Kriterien gemeinsam haben. Sie können beliebig viele Suchfilter miteinander kombinieren.

[.instruction]
Eigenschaft suchen:

. Öffnen Sie das Menü *System » Einstellungen » Eigenschaften » Konfiguration*.
. Geben Sie in der Ansicht *Filter* ggf. Suchbegriffe in die Suchfelder ein bzw. stellen Sie Filteroptionen in den Dropdown-Listen ein. Beachten Sie die Erläuterungen in <<tabelle-filter-eigenschaften>>.
. Klicken Sie auf *Suchen*. +
→ Die Eigenschaften, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile der Eigenschaft. +
→ Die Detailansicht der Eigenschaft wird geöffnet.

[[tabelle-filter-eigenschaften]]
.Filter für die Eigenschaften
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Ohne gewählte Filtereinstellungen auf *Suchen* klicken, um alle Eigenschaften anzuzeigen. +
*_Oder:_* Die Suchergebnisse durch Filtereinstellungen eingrenzen und auf *Suchen* klicken. +
→ Die gefundenen Eigenschaften werden in der Übersicht angezeigt.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*ID*
|Jede Eigenschaft erhält automatisch eine fortlaufende und einzigartige ID.

|*Name*
|Name eingeben, um die Eigenschaft mit diesem Namen zu suchen. Es ist möglich, nur nach Teilen des Namens zu suchen.

|*Sprache*
|Sprache wählen, um nur Eigenschaften anzuzeigen, für die ein Name in dieser Sprache gespeichert ist.

|*Gruppe*
|Gruppe wählen, um nur Eigenschaften anzuzeigen, die dieser Gruppe zugeordnet sind. +
*Nicht gruppiert* wählen, um nur Eigenschaften anzuzeigen, die keiner Gruppe zugeordnet sind. +
*Gruppiert* wählen, um nur Eigenschaften anzuzeigen, die einer Gruppe zugeordnet sind.

|*Bereich*
|Bereich wählen, um nur Eigenschaften dieses Bereichs anzuzeigen.

|*Eigenschaftstyp*
|Eigenschaftstyp wählen, um nur Eigenschaften dieses Typs anzuzeigen.
|====

[#4400]
=== Eigenschaft löschen

Sie können entweder eine Eigenschaft oder mehrere Eigenschaften gleichzeitig löschen.

[#4500]
==== Eine Eigenschaft löschen

Gehen Sie wie im Folgenden beschrieben vor, um eine Eigenschaft unwiderruflich zu löschen.

[.instruction]
Eine Eigenschaft löschen:

. Öffnen Sie das Menü *System » Einstellungen » Eigenschaften » Konfiguration*.
. Führen Sie die Suche aus. +
→ Wählen Sie ggf. Filter, um die Ergebnisse einzugrenzen.
. Klicken Sie auf die Eigenschaft. +
→ Die Eigenschaft wird geöffnet.
. Klicken Sie auf *Eigenschaft löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Die Eigenschaft wird gelöscht und aus der Übersicht entfernt.

[#4600]
==== Mehrere Eigenschaften löschen

Gehen Sie wie im Folgenden beschrieben vor, um mehrere Eigenschaft gleichzeitig unwiderruflich zu löschen.

[.instruction]
Mehrere Eigenschaften löschen:

. Öffnen Sie das Menü *System » Einstellungen » Eigenschaften » Konfiguration*.
. Führen Sie die Suche aus. +
→ Wählen Sie ggf. Filter, um die Ergebnisse einzugrenzen.
. Aktivieren Sie die Eigenschaften, die Sie löschen möchten.
. Klicken Sie auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Die gewählten Eigenschaften werden gelöscht und aus der Übersicht entfernt.

[#4700]
=== Eigenschaften gruppieren

Erstellen Sie Eigenschaftsgruppen, um mehrere Eigenschaften zusammenzufassen. Gehen Sie wie im Folgenden beschrieben vor, um eine Eigenschaftsgruppe zu erstellen.

[.instruction]
Eigenschaftsgruppe erstellen:

. Öffnen Sie das Menü *System » Einstellungen » Eigenschaften » Gruppen*.
. Klicken Sie auf *Eigenschaftsgruppe hinzufügen*.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-eigenschaftsgruppe-erstellen>>.
. *Speichern* Sie die Einstellungen. +
→ Die Eigenschaftsgruppe wird erstellt.

[[tabelle-eigenschaftsgruppe-erstellen]]
.Neue Eigenschaftsgruppe erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
|Name für die Eigenschaftsgruppe eingeben. +
*_Hinweis:_* Standardmäßig wird der Name für die Systemsprache angezeigt. Nachdem die Eigenschaftsgruppe erstellt wurde, kann der Name in englischer Sprache gespeichert werden. Weitere Sprachen sind in Planung.

|*Beschreibung*
|Beschreibung für die Eigenschaftsgruppe eingeben. +
*_Hinweis:_* Standardmäßig wird die Beschreibung für die Systemsprache angezeigt. Nachdem die Eigenschaftsgruppe erstellt wurde, kann die Beschreibung in englischer Sprache gespeichert werden. Weitere Sprachen sind in Planung.

|*Position*
|Positionsnummer für die Eigenschaftsgruppe eingeben. Standardmäßig wird aufsteigend nach Positionsnummer sortiert. +
*_Tipp:_* Positionsnummern in 10er-Schritten vergeben, damit neue Eigenschaftsgruppen dazwischen eingefügt werden können.

|*Gruppentyp*
|Gruppentyp aus der Dropdown-Liste wählen. Die Option steuert, wie Eigenschaften des Typs *Empty* im Bestellvorgang angezeigt werden. +
*Keine* = Eigenschaften werden standardmäßig nicht gruppiert. +
*Select* = Eine der gruppierten Eigenschaften ist per Dropdown-Liste wählbar. +
*Multiselect* = Mehrere Eigenschaften sind wählbar. +
*_Hinweis:_* Option greift nur für Eigenschaften des Typs *Kein*, für die die Option *Bestellvorgang* aktiviert ist.

|*Aufpreistyp*
|Aufpreistyp aus der Dropdown-Liste wählen. +
*Pauschal* = Aufpreis wird als pauschaler Betrag eingegeben. +
*Prozent* = Aufpreis wird als Prozentwert eingegeben.
|====

[#4800]
==== Eigenschaft einer Gruppe zuordnen

Gehen Sie wie im Folgenden beschrieben vor, um eine oder mehrere Eigenschaft einer Eigenschaftsgruppe zuzuordnen.

[.instruction]
Eigenschaft einer Gruppe zuordnen:

. Öffnen Sie das Menü *System » Einstellungen » Eigenschaften » Konfiguration*.
. Führen Sie die Suche aus. +
→ Wählen Sie ggf. Filter, um die Ergebnisse einzugrenzen.
. Aktivieren Sie die Eigenschaften, die Sie der Gruppe zuordnen möchten.
. Klicken Sie auf *Eigenschaftsgruppe zuordnen*. +
→ Eine Dropdown-Liste der Eigenschaftsgruppen wird angezeigt.
. Wählen Sie die Eigenschaftsgruppe aus der Dropdown-Liste.
. Klicken Sie auf *Gruppenfunktion*. +
→ Die gewählten Eigenschaften werden der Eigenschaftsgruppe zugeordnet.

[#4900]
==== Eigenschaftsgruppen löschen

Sie können entweder eine Eigenschaftsgruppe oder mehrere Eigenschaftsgruppen gleichzeitig löschen. Die Eigenschaften, die den Gruppen zugeordnet sind, bleiben beim Löschen von Eigenschaftsgruppen erhalten.

===== Eine Eigenschaftsgruppe löschen

Gehen Sie wie im Folgenden beschrieben vor, um eine Eigenschaftsgruppe unwiderruflich zu löschen.

[.instruction]
Eine Eigenschaftsgruppe löschen:

. Öffnen Sie das Menü *System » Einstellungen » Eigenschaften » Gruppen*.
. Führen Sie die Suche aus. +
→ Wählen Sie ggf. Filter, um die Ergebnisse einzugrenzen.
. Klicken Sie auf die Eigenschaftsgruppe. +
→ Die Eigenschaftsgruppe wird geöffnet.
. Klicken Sie auf *Gruppe löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Die Eigenschaftsgruppe wird gelöscht und aus der Übersicht entfernt. +
*_Hinweis:_* Wenn Sie eine Eigenschaftsgruppe löschen, werden die Eigenschaften, die der Gruppe zugeordnet sind, nicht gelöscht.

[#5000]
===== Mehrere Eigenschaftsgruppen löschen

Gehen Sie wie im Folgenden beschrieben vor, um mehrere Eigenschaftsgruppen gleichzeitig unwiderruflich zu löschen.

[.instruction]
Mehrere Eigenschaftsgruppen löschen:

. Öffnen Sie das Menü *System » Einstellungen » Eigenschaften » Gruppen*.
. Führen Sie die Suche aus. +
→ Wählen Sie ggf. Filter, um die Ergebnisse einzugrenzen.
. Aktivieren Sie die Eigenschaftsgruppen, die Sie löschen möchten.
. Klicken Sie auf *Löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf *Löschen*. +
→ Die gewählten Eigenschaftsgruppen werden gelöscht und aus der Übersicht entfernt. +
*_Hinweis:_* Wenn Sie eine Eigenschaftsgruppe löschen, werden die Eigenschaften, die der Gruppe zugeordnet sind, nicht gelöscht.

[#1704]
== Sichtbarkeit der Schnellsuche für variablen Benutzer einstellen

Damit für Benutzer mit der Benutzerklasse *Variabel* das Menü *CRM » Schnellsuche* sichtbar ist, muss das Menü im Benutzerkonto freigeschaltet werden.

Da die neue Benutzeroberfläche des Menüs *CRM » Schnellsuche* über REST abgerufen wird, müssen zusätzlich Berechtigungen im Bereich *REST-API* aktiviert werden. Im Folgenden werden die Berechtigungen, die mindestens aktiviert werden müssen, damit das Menü sichtbar ist, beschrieben. Aktivieren Sie weitere Berechtigungen analog. Wenn der variable Benutzer in der Schnellsuche z.B. Notizen erstellen soll, aktivieren Sie im Bereich *Kommentare* die Option *Kommentar erstellen*.

[.instruction]
Sichtbarkeit der Schnellsuche für variablen Benutzer einstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den Benutzer mit der Benutzerklasse *Variabel*, für den Sie die Sichtbarkeit des Menüs aktivieren möchten.
. Wechseln Sie in das Tab *Berechtigung*.
. Wechseln Sie in das Tab *Menü*.
. Klappen Sie den Bereich *CRM* auf.
. Aktivieren Sie die Option *Schnellsuche*.
. Wechseln Sie in das Tab *REST-API*.
. Klappen Sie den Bereich *Firma* auf.
. Aktivieren Sie die Option *Firma anzeigen*.
. Klappen Sie den Bereich *Adresse* auf.
. Aktivieren Sie die Option *Adresse anzeigen*.
. Klappen Sie den Bereich *Adressoption* auf.
. Klappen Sie den Bereich *Typ der Adressoption* auf.
. Aktivieren Sie die Option *Typ der Adressoption anzeigen*.
. Klappen Sie den Bereich *Kontakt* auf.
. Klappen Sie den Bereich *Kontaktadresse* auf.
. Aktivieren Sie die Option *Kontaktadresse anzeigen*.
. Klappen Sie den Bereich *Adresstyp* auf.
. Aktivieren Sie die Option *Adresstyp anzeigen*.
. Klappen Sie den Bereich *Kontaktoption* auf.
. Klappen Sie den Bereich *Typ der Kontaktoption* auf.
. Aktivieren Sie die Option *Typ der Kontaktoption anzeigen*.
. Aktivieren Sie die Option *Kontakt anzeigen*.
. Klappen Sie den Bereich *Kommentare* auf.
. Aktivieren Sie die Option *Kommentar anzeigen*.
. Klappen Sie den Bereich *Aufträge* auf.
. Aktivieren Sie die Option *Aufträge anzeigen*.
. Klappen Sie den Bereich *Auftragsstatus* auf.
. Aktivieren Sie die Option *Auftragsstatus anzeigen*.
. *Speichern* Sie die Einstellungen.

[#1705]
== Schnellsuche verwenden

Verwenden Sie die Schnellsuche, um alle Informationen eines Kontakts auf einen Blick zu erhalten. Dazu gehören neben der Rechnungsadresse, den Stammdaten und allgemeinen Informationen wie z.B. Typ, offene Forderungen und dem Datum des letzten Auftrags auch die Aufträge, weitere Adressen, Events, Notizen und Tickets.

[.instruction]
Schnellsuche verwenden:

. Öffnen Sie das Menü *CRM » Schnellsuche*.
. Wählen Sie mindestens einen Filter. Beachten Sie die Erläuterungen in <<tabelle-filter-schnellsuche>>.
. Klicken Sie auf *Suchen*. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Übersicht des Kontakts mit den Bereichen *Rechnungsadresse*, *Stammdaten* und *Info* wird geöffnet.
. Die Übersicht der *Aufträge* ist standardmäßig geöffnet. +
→ Mit einem Klick in die Zeile des Auftrags gelangen Sie direkt in die Übersicht des Auftrags im Menü *Aufträge » Aufträge bearbeiten*.
. Klicken Sie in der Zeile *Adressen* auf den Pfeil rechts, um weitere Adressen des Kontakts anzuzeigen. +
→ Mit einem Klick in die Zeile der Adresse gelangen Sie direkt in die Adressübersicht und können dort Änderungen vornehmen.
. Klicken Sie in der Zeile *Events* auf den Pfeil rechts, um die Events für diesen Kontakt anzuzeigen.
. Klicken Sie in der Zeile *Tickets* auf den Pfeil rechts, um die Tickets des Kontakts anzuzeigen. +
→ Mit einem Klick in die Zeile des Tickets gelangen Sie direkt in das Ticket im Menü *CRM » Ticketsystem*.
. Klicken Sie in der Zeile *Notizen* auf den Pfeil rechts, um die Notizen des Kontakts anzuzeigen. +
→ Mit einem Klick auf *Neue Notiz* erstellen Sie direkt aus dieser Übersicht heraus eine Notiz.

[[tabelle-filter-schnellsuche]]
.Filter in der Schnellsuche
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Zeigt die gefundenen Kontakte, die den Suchkriterien entsprechen, an. Mindestens ein Filter muss gewählt sein.

|*Reset*
|Eingestellte Filterkriterien zurücksetzen.

|*ID*
|Jeder Kontakt erhält automatisch eine fortlaufende und einzigarte ID. Dies ist unabhängig davon, ob der Kontakt manuell oder automatisch erstellt wurde. 2 Kontakte haben somit nie die gleiche ID. Die ID entspricht immer einer echten Zahl. Ungültig sind z.B. "00521" oder "ADF8354".

|*Name*
|Vorname und/oder Nachname oder Firmenname eingeben, um den oder die Kontakte mit diesem Namen anzuzeigen.

|*Kontaktdaten*
|In diesem Feld kann nach dem Namen, der Adresse, der Firma, der Kundennummer und dem eBay-Namen gesucht werden. +
*_Hinweis:_* Um nach dem eBay-Namen zu suchen, zuerst den Parameter *ebay:* gefolgt vom gesuchten eBay-Namen eingeben.

|*Anschrift*
|Straßenname und/oder Hausnummer eingeben, der im Kontakt gespeichert ist. Es ist möglich, nur nach Teilen des Straßennamens und Teilen der Hausnummer zu suchen.

|*PLZ*
|Postleitzahl, die im Kontakt gespeichert sind, eingeben. Es wird auch nach Postleitzahlen, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen der Postleitzahl zu suchen.

|*Ort*
|Ort, der im Kontakt gespeichert ist, eingeben. Es wird auch nach Orten, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen des Ortsnamens zu suchen.

|*E-Mail*
|Komplette E-Mail-Adresse eingeben, um den Kontakt mit dieser E-Mail-Adresse anzuzeigen.

|*Telefon*
|Telefonnummer eingeben, um nur den Kontakt mit dieser Telefonnummer anzuzeigen. Es kann auch nach Teilen der Telefonnummer gesucht werden. Mindestens 3 Ziffern eingeben.

|*Land*
|Land wählen, um nur Kontakte aus diesem Land anzuzeigen. Das Land ist in den Kontaktdaten gespeichert.

|*Eigner*
|Eigner wählen, um nur Kontakte anzuzeigen, die mit diesem Eigner verknüpft sind. Der Eigner muss in den Kontaktdaten gespeichert sein. +
*_Wichtig:_* In der Dropdown-Liste werden nur Benutzer angezeigt, bei denen im Benutzerkonto im Tab *Eigner* die Option *Kunde* aktiviert ist.

|*Typ*
|Typ wählen, um nur Kontakte mit diesem Typ anzuzeigen.

|*Kundenklasse*
|Kundenklasse wählen, um nur Kontakte mit dieser Kundenklasse anzuzeigen.

|*Tags*
|Einen oder mehrere Tags wählen, um nur Kontakte mit diesen Tags anzuzeigen.

|*Mandant*
|Mandant wählen, um nur Kontakte dieses Mandanten anzuzeigen. Der Mandant ist in den Kontaktdaten gespeichert. +
*_Wichtig:_* Variablen Benutzern stehen nur Mandanten zur Auswahl, für die sie eine Berechtigung haben. Berechtigungen werden im Menü *System » Einstellungen » Benutzer » Konten* im Tab <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#90, Berechtigung>> des Benutzerkontos eingestellt.

|*Herkunft*
|Herkunft wählen, um nur Kontakte mit dieser Herkunft anzuzeigen.

|====

[#5100]
== Änderungshistorie für Kontaktdaten anzeigen

Über die Änderungshistorie können Sie nachverfolgen, welcher Benutzer in Ihrem System zu welchem Zeitpunkt welche Änderung an einem Kontaktdatensatz vorgenommen hat. Außerdem wird angezeigt, wenn Ihr Kontakt selbst Änderungen in seinem Mein Konto-Bereich vorgenommen hat.  

[.instruction]
Änderungshistorie für Kontaktdaten anzeigen:

. Öffnen Sie das Menü *Daten » Historie*.
. Wählen Sie eine Option aus der Dropdown-Liste *Referenztyp*.
. Geben Sie die Referenz-ID, z.B. die ID des Kontakts, ein.
. Klicken Sie auf *Suchen*. +
→ Eine Liste der Änderungen mit alten und neuen Werten wird angezeigt.

[TIP]
.Aktuell verfügbare Referenztypen
====
Die folgenden Referenztypen sind aktuell für die Anzeige von Änderungen an Kontaktdaten verfügbar:

Kontakt, Adresse, Firma, Konfiguration der Datenbereinigung.
====

[#1706]
== Alle Daten zu einem Kontakt herunterladen

Im Menü *CRM » Schnellsuche* können Sie mit einem Klick alle zu einem Kontakt oder zu einer Adresse gehörigen Daten als ZIP-Datei herunterladen.

[.instruction]
Alle Daten zu einem Kontakt herunterladen:

. Öffnen Sie das Menü *CRM » Schnellsuche*.
. Wählen Sie mindestens einen Filter.
. Klicken Sie auf *Suchen*. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Übersicht des Kontakts mit den Bereichen *Rechnungsadresse*, *Stammdaten* und *Info* wird geöffnet.
. Klicken Sie in der oberen Zeile auf *Alle Daten dieses Kontakts herunterladen*. +
→ Ein Dialogfenster erscheint. Legen Sie den Speicherort für die ZIP-Datei auf Ihrem Computer fest.

Weitere Informationen zu der Download-Datei finden Sie in diesem link:https://forum.plentymarkets.com/t/dsgvo-button-fuer-den-datenexport-zu-einem-kunden-integriert/486915[Changelog^]-Beitrag im plentymarkets Forum.

[#1707]
== Datensatz anonymisieren

Daten zu einem Kontakt können mit einem Klick gelöscht oder so unkenntlich gemacht werden, dass kein Bezug mehr zu dieser Person hergestellt werden kann.

[.instruction]
Datensatz anonymisieren:

. Öffnen Sie das Menü *CRM » Schnellsuche*.
. Wählen Sie mindestens einen Filter.
. Klicken Sie auf *Suchen*. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Übersicht des Kontakts mit den Bereichen *Rechnungsadresse*, *Stammdaten* und *Info* wird geöffnet.
. Klicken Sie in der oberen Zeile auf *Datensatz anonymisieren*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Geben Sie die ID des Kontakts, den Sie anonymisieren möchten, ein.
. Klicken Sie auf *Anonymisieren*. +
→ Der Datensatz wird anonymisiert.

[TIP]
.Welche Daten werden anonymisiert und gelöscht?
====
Mit einem Klick auf *Datensatz anonymisieren* werden die folgenden Daten im Datensatz des Kontakts anonymisiert und gelöscht:

* Daten werden anonymisiert: Vorname, Nachname
* Daten werden gelöscht: Kontaktoptionen, Adressoptionen, Adressen, Adressverknüpfungen, Auftragsverknüpfungen, Verknüpfungen zu einer Firma, Bankdaten
====


[#5200]
== Offene Posten anzeigen

Im Menü *CRM » OP-Liste* erhalten Sie eine Übersicht über Kunden mit unbezahlten Aufträgen. OP steht für offene Posten. Die Liste enthält die Anzahl der offenen Posten eines Kunden sowie die Höhe der Forderung, die sich aus den offenen Posten ergibt.

Die Liste der offenen Posten wird einmal täglich automatisch aktualisiert. Forderungen werden daher teilweise erst am nächsten Tag in der Liste angezeigt. Sie haben aber auch die Möglichkeit, die <<crm/kontakte-verwalten#5400, Liste manuell zu aktualisieren>>. Um alle offenen Posten anzuzeigen, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Offene Posten anzeigen:

. Öffnen Sie das Menü *CRM » OP-Liste*.
. Klicken Sie auf *Suchen*. +
→ Alle offenen Posten werden aufgeführt.

Aus der Liste heraus öffnen Sie den Kunden, indem Sie in der Spalte *ID* auf die ID klicken. Oder Sie öffnen eine Liste aller Aufträge des Kunden, in denen noch Posten offen sind, indem Sie in der Spalte *Aufträge* auf *Aufträge anzeigen* klicken.

[#5300]
=== Offene Posten filtern

Die Liste im Menü *CRM » OP-Liste* lässt sich nach *Typ*, *Land*, *Kundenklasse* und *Kundentyp* filtern. Offene Posten können Sie außerdem nach der Anzahl der *offenen Posten* oder der Höhe der *Forderung* sortieren.

[.instruction]
Offene Posten filtern:

. Öffnen Sie das Menü *CRM » OP-Liste*.
. Wählen Sie die Filtereinstellungen.
. Klicken Sie auf *Suchen*, um die gefilterten Ergebnisse anzuzeigen.

[#5400]
=== Offene Posten manuell aktualisieren

Die offenen Posten werden einmal täglich automatisch aktualisiert. Zwischendurch können Sie die Liste wie im Folgenden beschrieben manuell aktualisieren:

[.instruction]
Offene Posten manuell aktualisieren:

. Öffnen Sie das Menü *CRM » OP-Liste*.
. Klicken Sie im Bereich *OP-Liste generieren* auf *Generieren*. +
→ Die Liste wird im Hintergrund aktualisiert.
. Klicken Sie auf *Suchen*, um die aktualisierte Liste anzuzeigen.


[#5500]
== USt-IdNr. prüfen

Die Umsatzsteuer-Identifikationsnummer (USt-IdNr.) ist eine exklusive Identifikationsnummer und dient der Kennzeichnung von Umsatzsteuerpflichtigen. Innerhalb der EU wird sie für die Abrechnung der Umsatzsteuer durch die Finanzämter benötigt.

////
Die USt-IdNr. wird im Menü *CRM » Kunden bearbeiten* im Tab *Kundendaten* des Kunden gespeichert und geprüft.
////

Die Prüfung der USt-IdNr. erlaubt die Verifizierung einer deutschen oder einer ausländischen USt-IdNr. und ist täglich von 5.00 bis 23.00 Uhr verfügbar. Geprüft werden können alle USt-IdNrn. aus Mitgliedsstaaten der EU mit Ausnahme der Slowakei und Lettland (nicht oder nur eingeschränkt möglich). Bei deutschen Ust-IdNrn. wird nur die Gültigkeit geprüft, die Zuordnung zu einer Person wird nicht geprüft. Bei ausländischen USt-IdNrn. wird die Gültigkeit geprüft und es werden die zugehörigen Firmennamen- und Adressdaten zur USt-IdNr. abgefragt und angezeigt.

////
[#5600]
=== USt-IdNr. in den Kundendaten prüfen

Gehen Sie wie im Folgenden beschrieben vor, um die USt-IdNr. in den Kundendaten zu prüfen.

[.instruction]
USt-IdNr. in den Kundendaten prüfen:

. Öffnen Sie das Menü *CRM » Kontakte*.
. Suchen Sie den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicken Sie in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.

. Geben Sie im Tab *Kundendaten* die Umsatzsteuer-ID ohne Leerzeichen bei der Option *USt-IdNr.* ein.
. Klicken Sie auf *Prüfen*. +
→ Die Prüfung kann einige Minuten dauern.
. Wenn die Prüfung erfolgreich war, klicken Sie auf *Speichern*, um die USt-IdNr. zu sichern.

Als Resultat liefert die Anfrage das Ergebnis der Prüfung der USt-IdNr. sowie bei einer ausländischen USt-IdNr. zusätzlich den Firmennamen und die Adresse.

Wenn die USt-IdNr. gültig ist, wird der Status *Gültig* angezeigt. Bei ungültiger USt-IdNr. wird der Status *Ungültig* angezeigt. Wenn eine USt-IdNr. nicht geprüft werden kann, erhalten Sie den Hinweis, dass die USt-IdNr. nicht geprüft werden konnte. Nicht übereinstimmende Daten führen zu einer Fehlermeldung bei *Status*.

Die Prüfung der USt-IdNr. können Sie auch in den Kundendaten des Auftrags im Menü *Aufträge » Aufträge bearbeiten » Auftrag öffnen » Tab: Kunde » Tab: Kundendaten* vornehmen.
////

[#5700]
=== USt-IdNr. im Webshop prüfen

Im Webshop wird die USt-IdNr. automatisch im Bestellvorgang geprüft. Bei nicht gültiger USt-IdNr. kann der Käufer die Bestellung erst abschließen, wenn eine gültige USt-IdNr. eingegeben wird oder der Eintrag entfernt wird.

[#5800]
=== Prüfungsdaten exportieren

Sie können eine Liste aller Prüfungsdaten oder der Daten für den aktuellen Monat exportieren. Details zum Export der USt-ID-Prüfungsdaten finden Sie im Themenbereich <<basics/datenaustausch#, Datenaustausch>> auf der Handbuchseite <<basics/datenaustausch/export-import/daten-exportieren#, Daten exportieren>>.

[#5800]
== Kontaktdaten exportieren, importieren und aktualisieren

Exportieren Sie die Daten Ihrer Kontakte über den Elastischen Export. Voraussetzung dafür ist, dass Sie die Plugins link:https://marketplace.plentymarkets.com/plugins/integration/ElasticSync_4750[ElasticSync^] und link:https://marketplace.plentymarkets.com/plugins/markets/ElasticExport_4763[Elastischer Export^] installieren und bereitstellen. Beide Plugins sind im link:https://marketplace.plentymarkets.com/[plentyMarketplace^] verfügbar. Das ElasticSync-Plugin ist zwar nicht für den Export zuständig, sondern für den Import bzw. die Aktualisierung der Daten, es enthält allerdings die Funktion FormatDesigner.

Das Format für den Export erstellen Sie im Menü *Daten » FormatDesigner*. Einen neuen Export erstellen Sie im Menü *Daten » Elastischer Export*. Dort wählen Sie das über den FormatDesigner erstellte Format aus der Dropdown-Liste und exportieren die Daten anschließend in eine CSV-Datei.

Ihnen stehen zahlreiche Filteroptionen für den Export zur Verfügung. Exportieren Sie z.B. nur Kontakte, die Sie mit 3 Sternen bewertet haben, oder nur Kontakte, die einem bestimmten Eigner zugeordnet sind.

Importieren oder aktualisieren Sie die Daten Ihrer Kontakte inklusive Adressoptionen, Kontaktoptionen und Firmendaten über das ElasticSync-Plugin. Installieren Sie mindestens Version 2.1 des Plugins. Weitere Informationen stehen Ihnen im link:https://marketplace.plentymarkets.com/de/plugins/integration/ElasticSync_4750[User Guide^] des ElasticSync-Plugins zur Verfügung.
