= Kontakte verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kontakt, Kunde, Adresse, Adressen, Rechnungsadresse, Lieferadresse, primär, Firmen, Firma, Gastzugang, regulärer Zugang, Events, Eigenschaften, Zugangsdaten, Passwort ändern, Passwortänderung, Login entsperren, Bankdaten, Zugangsdaten, Nachrichten, Messenger
:description: Erfahre, wie du in plentymarkets Kontakte, Adressen und Firmen verwaltest.
:position: 10
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:url: crm/kontakte-verwalten
:id: KO9RPU2

Auf dieser Handbuchseite sind alle Einstellungen, die im Menü *CRM » Kontakte* zur Verfügung stehen, sowie die Einstellungen, die du im Menü *Einrichtung » CRM* vornehmen musst, beschrieben.

Im Menü *Einrichtung » CRM* nimmst du vorbereitende Einstellungen wie das Erstellen von Kundenklassen und Typen vor. Im Menü *CRM » Kontakte* erstellst und bearbeitest du die Datensätze deiner Kontakte und verwaltest dort alle Informationen wie z.B. Adressen, Aufträge, Scheduler-Aufträge, Tickets, Nachrichten, Umsätze, Bankdaten und Dokumente deiner Kontakte.

[#10]
== Vorbereitende Einstellungen vornehmen

Im Menü *Einrichtung » CRM* nimmst du vorbereitende Einstellungen wie das Erstellen von <<crm/kontakte-verwalten#15, Kundenklassen>> und <<crm/kontakte-verwalten#20, Typen>> vor. Außerdem richtest du in diesem Menü <<crm/kontakte-verwalten#25, Rabatte>> für deine Kontakte ein.

[#13]
=== Adress-Layout für Lieferscheine einrichten

Im Menü *Einrichtung » CRM » Adress-Layout* kannst du individuell Adress-Layouts für deine Lieferländer für das Auftragsdokument *Lieferschein* einrichten. Die Adress-Layouts für die Lieferländer Deutschland, Frankreich und das Vereinigte Königreich sind bereits standardmäßig in deinem plentymarkets System enthalten. Du kannst diese 3 Adress-Layouts bearbeiten, wenn du über die Rechte verfügst.

[.subhead]
Benutzerrechte für Backend-Benutzer vergeben

Nutzer vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs im plentymarkets Backend. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter mit diesem Nutzertyp Adress-Layouts sehen und bearbeiten können, muss ein Nutzer vom Typ *Admin* zumindest die in <<tabelle-berechtigungen-adress-layout>> beschriebenen Rechte für diesen Benutzer vergeben.

[.instruction]
Benutzerrechte für Backend-Benutzer vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne den zu bearbeitenden Benutzer.
. Aktiviere im Bereich *Berechtigungen* die Berechtigungen anhand von <<tabelle-berechtigungen-adress-layout>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-berechtigungen-adress-layout]]
.Berechtigungen für das Adress-Layout vergeben
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*CRM > Adress-Layout > Adress-Layout anzeigen*
|Erlaubt dem Backend-Benutzer, Adress-Layouts zu sehen.

|*CRM > Adress-Layout > Adress-Layout erstellen*
|Erlaubt dem Backend-Benutzer, Adress-Layouts zu erstellen.

|====

[TIP]
.REST-Berechtigungen zum Erstellen, Löschen und Aktualisieren von Adress-Layouts
====
Damit Personen mit dem Zugang *Backend* das Adress-Layout im Menü *Einrichtung » CRM » Adress-Layout* auch erstellen, aktualisieren und löschen können, musst du diese Berechtigungen im Benutzerkonto analog aktivieren.
====

[.instruction]
Adress-Layout für Lieferscheine einrichten:

. Öffne das Menü *Einrichtung » CRM » Adress-Layout*.
. Klicke auf *Neues Layout* (icon:plus-square[role="green"]).
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-adress-layout-einrichten>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-adress-layout-einrichten]]
.Adress-Layout einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Grundeinstellungen*

|*Layout-Name*
|Name eingeben.

|*Als Standard-Adress-Layout verwenden*
|Umschaltfläche aktivieren, wenn dieses Layout als Standard-Layout verwendet werden soll. In der Übersicht auf der linken Seite ist das Standard-Adress-Layout mit einem Sternchen gekennzeichnet.

|*Feldliste*
|Wenn gewünscht, englische und deutsche Bezeichnungen für die Feldnamen eingeben, damit diese Bezeichnungen dann beim Gestalten des Adress-Layouts angezeigt werden.

|*Speichern*
|Einstellungen speichern. Die Liste der Feldnamen schließt sich und die Bereiche *Länder*, *Layout* und *Felder* werden angezeigt.

|*Länder*
|Ein Land oder mehrere Länder aus der Liste wählen, für die das Adress-Layout gelten soll.

|*Layout* / +
*Felder*
|Aus dem Bereich *Felder* die Adressfelder in den Bereich *Layout* ziehen und das Adress-Layout individuell für jedes Land gestalten. +
*_Tipp:_* Es ist möglich, weitere Reihen (maximale Anzahl der Reihen: 6) hinzuzufügen, einzelne Felder zu entfernen und komplette Reihen zu entfernen. Auch leere Reihen sind erlaubt. Eine Beschränkung der Felderanzahl pro Reihe ist nicht vorhanden.

|====

Damit die Lieferscheine für die Lieferländer automatisch in den erstellten Adress-Layouts ausgegeben werden, musst du eine Einstellung im Lieferschein vornehmen. Dein plentymarkets System prüft dann automatisch das Lieferland aus dem Auftrag und gibt den Lieferschein in den im Menü *Einrichtung » CRM » Adress-Layout* aufgelisteten Layout aus. Gehe dazu wie im Folgenden beschrieben vor.

. Öffne das Menü *Einrichtung » Mandant* » _Mandant wählen_ » *Standorte* » _Standort wählen_ » *Dokumente » Lieferschein*.
. Aktiviere im Bereich *Grundeinstellungen:{nbsp}Lieferschein* die Option *Neues Adresslayout*. +
→ Die Option darüber *Aufbau der Rechnungs-/ Lieferanschrift* wird ausgeblendet und die Lieferscheine werden in den Adresslayouts im Menü *Einrichtung » CRM » Adress-Layout* ausgegeben.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Wie du Lieferscheine einrichtest und erstellst, ist auf der Handbuchseite <<auftraege/auftragsdokumente/lieferscheine-erzeugen#, Lieferscheine erzeugen>> beschrieben.

Aktuell ist diese Einstellung vorerst nur für Lieferscheine verfügbar. Fü weitere Dokumente wird diese Einstellung folgen.

[#15]
=== Kundenklasse erstellen

Mit Kundenklassen unterteilst du deinen Kundenstamm nach unterschiedlichen Kriterien. So kannst du eine Kundenklasse festlegen, die an Endkunden (B2C) angepasst ist und mit deren Einstellungen die Artikel mit Bruttopreisen im Webshop angezeigt werden. Für Händler (B2B) erstellst du eine weitere Kundenklasse, mit deren Einstellungen die Artikel mit Nettopreisen im Webshop angezeigt werden. Weitere Optionen, die festgelegt werden können, sind z.B. Rabatte auf den Nettowarenwert, Rabatte auf die Zahlungsart oder Rabattstaffeln, die nur für eine bestimmte Kundenklasse gelten.

Erstelle Kundenklassen im Menü *Einrichtung » CRM » Kundenklassen*. Die dort erstellten Kundenklassen stehen dann in den Kontaktdatensätzen im Menü *CRM » Kontakte* als Auswahl zur Verfügung.

[TIP]
.Tipp: Typen und Klassen erstellen
====
Für die Einteilung deines Kundenstamms in Typen und Klassen ist es empfehlenswert, ein Konzept zu entwickeln, bevor du größere Mengen an Kontaktdaten erstellst. Dadurch vermeidest du späteren Änderungsaufwand, z.B. wenn Typen bei fehlender Einstellung automatisch zugewiesen werden. Überlege dir, welche Typen und Klassen du benötigst, erstelle die Typen und Klassen und weise sie deinen Kontakten zu.
====

Du kannst beliebig viele Kundenklassen erstellen und individuell einrichten. Kundenklassen erhalten automatisch eine ID, die in der Übersicht vor dem Namen der Kundenklasse angezeigt wird. Die ID bestimmt jedoch keine Reihenfolge, diese wird durch die Option *Position* festgelegt.

Wird eine neue Kundenklasse erstellt, steht die Kundenklasse in der Detailansicht des Kontakts im Menü *CRM » Kontakte* » _Kontakt öffnen_ als Auswahl zur Verfügung.

[.instruction]
Kundenklasse erstellen:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Wechsele in das Tab *Neue Kundenklasse*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-kundenklasse-erstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-kundenklasse-erstellen]]
.Kundenklasse erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Mindestbestellmenge*
|Mindestbestellmenge eingeben, wenn pro Artikel eine bestimmte Anzahl bestellt werden muss oder um eine Mindestbestellmenge für die Mengenrabatte zu gewährleisten.

|*Bezeichnung*
|Name für die neue Kundenklasse eingeben, z.B. *Großhändler* oder *Premiumkunde*.

|*Position*
|Wenn keine Zahl eingegeben wird, wird eine Position automatisch anschließend an die höchste vorhandene Position vergeben. In erster Linie dient die Position der Sortierung der Kundenklassen im Menü. Dies ist z.B. in Kombination mit der Gestaltung der Sichtbarkeit der Artikelpreise im Webshop wichtig. Dies wird unter *Anzeige der Preise im Webshop* eingestellt.

|*Zahlungsziel*
|Zahlungsziel in Tagen eingeben, das für diese Kundenklasse gelten soll. Ein im Kontaktdatensatz gespeichertes Zahlungsziel hat Priorität vor diesem Zahlungsziel. Ein Zahlungsziel kann weiterhin optional in <<auftraege/auftragsdokumente#, Auftragsdokumenten>> wie z.B. <<auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnungen>> hinterlegt werden. Dieses Zahlungsziel wird dann in der Rechnung ausgegeben, wenn für einen Kunden und die Kundenklasse kein Zahlungsziel hinterlegt wurden. Dazu die ausklappbare Box *Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen* unterhalb von <<tabelle-kontakt-erstellen>> im Kapitel <<crm/kontakte-verwalten#100, Kontakt erstellen>> beachten.

|*Kunden-ID*
|Kunden-ID des Kunden eingeben, an den Sammelrechnungen bei <<auftraege/auftraege-verwalten#800, Sammelaufträgen>> geschickt werden sollen. Die Sammelaufträge werden kundenklassenspezifisch angelegt und die Rechnung wird an den Kunden gesendet.

|*Rabattart*
|Rabattart wählen. Je nach Rabattart werden mehr oder weniger Optionen eingeblendet. Wenn du keinen Rabatt vergeben möchtest, wähle die Option *Kein Rabatt*. Weitere Informationen sowie Erläuterungen zu den Rabattarten in plentymarkets findest du im Kapitel <<crm/kontakte-verwalten#25, Rabattsystem nutzen>>.

|*Mengenrabatt*
|Wählen, ob der im Menü *Einrichtung » Artikel » Verkaufspreise* eingegebene Wert unter *Ab Menge* berücksichtigt werden soll oder nicht.

|*Erlaubte Zahlungsarten*
|Wählen, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen. +
In der Grundeinstellung sind alle verfügbaren Zahlungsarten erlaubt. Werden neue Zahlungsarten integriert, müssen diese Zahlungsarten hier erlaubt werden, da neue Zahlungsarten nicht automatisch mit in die Erlaubnisliste aufgenommen werden. +
*_Wichtig:_* Dabei die Einstellungen hinsichtlich der <<fulfillment/versand-vorbereiten#1000, gesperrten Zahlungsarten in den Versandprofilen>> beachten, die für die Kundenklasse verwendet wird, bzw. diese Einstellung prüfen, damit es an dieser Stelle nicht zu ungewollten Überschneidungen kommt. Die Zahlungsart, die für eine Kundenklasse erlaubt sein soll, darf in den Versandprofilen nicht gesperrt sein und auch die Kundenklasse darf dort nicht gesperrt sein.

|*Zahlungshinweis*
|Ein hier eingegebener Zahlungshinweis wird auf Einzelrechnungen angezeigt. Das können z.B. besondere Angaben zur Zahlung für eine bestimmte Kundenklasse sein.

|*Anzeige der Preise im Webshop*
|Wählen, ob die Preise im Webshop *Brutto* oder *Netto* angezeigt werden sollen. +
*_Wichtig:_* Diese Option legt nur die Anzeige der Preise fest, nicht die Berechnung der Preise für die Kundenklasse. Einstellung besonders für die Kundenklasse der Position 1 beachten, da diese Kunden automatisch zugewiesen wird, wenn keine Kundenklasse im Kontaktdatensatz gewählt wurde.
|====

Du kannst Verkaufspreise mit Kundenklassen verknüpfen. Wähle dazu im Menü *Einrichtung » Artikel » Verkaufspreise* unter der Einstellung *Klasse* eine von dir erstellte Kundenklasse. Weitere Informationen findest du auf der Handbuchseite <<artikel/artikel-verwalten#, Artikel verwalten>> im Kapitel <<artikel/artikel-verwalten#870, Verkaufspreise verwalten>>.

[#20]
=== Typ erstellen

Typen dienen der Einordnung und Unterscheidung von Kontakten. Einige Typen sind bereits standardmäßig in deinem plentymarkets System angelegt und können nicht gelöscht werden. Diese Typen sind *Kunde*, *Handelsvertreter*, *Lieferant*, *Partner*, *Hersteller* und *Interessent*. Die erstellten Typen stehen im Menü *CRM » Kontakte* im Bereich *Filter* in der Dropdown-Liste *Typ* zur Verfügung.

Beim Erstellen eines neuen Kontakdatensatzes ist automatisch der Typ *Kunde* als Standard eingestellt. Kunden des Typs *Lieferant* stehen als Lieferanten zur Verfügung, z.B. im Tab *Lieferant* einer Variante.

Gehe wie im Folgenden beschrieben vor, um eigene Typen zu erstellen.

[.instruction]
Typ erstellen:

. Öffne das Menü *Einrichtung » CRM » Typen*.
. Klicke auf *Typ hinzufügen*.
. Gib einen Namen ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[.subhead]
Typ löschen

Gehe wie im Folgenden beschrieben vor, um erstellte Typen, die du nicht mehr benötigst, zu löschen. Beachte, dass die standardmäßig vorhandenen Typen nicht gelöscht werden können.

[.instruction]
Typ löschen:

. Öffne das Menü *Einrichtung » CRM » Typen*.
. Klicke in der Zeile des selbst erstellten Typs auf *Löschen* (icon:minus-square[role="red"]).
. Bestätige die Sicherheitsabfrage.

[#25]
=== Rabattsystem nutzen

In plentymarkets hast du mehrere Möglichkeiten der Rabattierung. Du kannst deinen Kontakten einen <<crm/kontakte-verwalten#26, Kundenklassenrabatt>>, einen <<crm/kontakte-verwalten#28, Rabatt auf die Zahlungsart>> sowie eine <<crm/kontakte-verwalten#27, Rabattstaffel auf den Nettowarenwert einer Bestellung>> gewähren. Außerdem kannst du <<crm/kontakte-verwalten#29, Verkaufspreise als Rabatte>> speichern und <<crm/kontakte-verwalten#30, manuelle Rabatte>> eingeben. Nimm die Einstellungen für die Rabattarten im Menü *Einrichtung » CRM » Kundenklassen* vor. Wie du die Rabatte gewährst, ist in den folgenden Unterkapiteln beschrieben.

[#26]
==== Kundenklassenrabatt einrichten

In einer Kundenklasse legst du Rabatte fest, die dann nur für die Kundenklasse wirksam werden. Darüber hinaus bestehen hier weitere Einstellungsmöglichkeiten, z.B. das Aktivieren von Mengenrabatten der Verkaufspreise. Beachte dabei, dass sich je nach Einstellung Rabatte addieren können.

Gehe wie im Folgenden beschrieben vor, um einen Rabatt für Kundenklassen einzugeben.

[.instruction]
Kundenklassenrabatt einrichten:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Klappe die Kundenklasse, für die der Rabatt gelten soll, auf (icon:plus-square-o[]).
. Aktiviere unter *Rabattart* die Option *Kundenklassenrabatt*. +
→ Eine weitere Einstellung wird geöffnet.
. Gib unter *Rabatt in %* den Prozentwert für den Rabattabzug ein.
. Wähle, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wähle, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Gib einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wähle, ob die Preise im Webshop *brutto* (inkl. MwSt.) oder *netto* (ohne MwSt.) angezeigt werden sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Informationen, wie du Kundenklassen erstellst, findest du im Kapitel <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>.

[#27]
==== Rabattstaffel auf Nettowarenwert einrichten

Möchtest du deine Kontakte mit Rabatten belohnen, wenn diese häufig und umsatzsteigernd in deinem Webshop einkaufen, kannst du hier Rabattwerte auf den Nettowarenwert des Auftrages festlegen.

[.instruction]
Rabattstaffel auf Nettowarenwert einrichten:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Klappe die Kundenklasse, für die die Rabattstaffel gelten soll, auf (icon:plus-square-o[]).
. Aktiviere unter *Rabattart* die Option *Rabattstaffel auf Nettowarenwert*. +
→ Eine Tabelle mit weiteren Einstellungen wird geöffnet.
. Gib unter *ab Nettowarenwert* die Betragsangaben aufsteigend ein.
. Gib unter *Rabatt in %* die Prozentwerte für den Rabattabzug aufsteigend ein. +
→ Wenn du z.B. im Feld *ab Nettowarenwert* 50 eingibst und im Feld *Rabatt in %* 2 eingibst, werden ab 50 Euro 2% Rabatt gewährt.
. Wähle, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wähle, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Gib einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wähle, ob die Preise im Webshop *brutto* (inkl. MwSt.) oder *netto* (ohne MwSt.) angezeigt werden sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Informationen, wie du Kundenklassen erstellst, findest du im Kapitel <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>.

[.subhead]
Ansicht des Kontakts beim Einkauf

Der Rabatt wird berechnet und angezeigt, wenn der Kontakt seinen Einkauf beendet und zur Kasse geht. Im Warenkorb wird zunächst nur der gesamte Rabattbetrag ausgewiesen. Wenn der Kontakt die Bestellung abschließt, wird zusätzlich zum Gesamtrabatt der Rabatt auf die einzelnen Artikelpositionen berechnet und angezeigt.

[#28]
==== Rabatt auf Zahlungsart einrichten

Die Rabattart *Rabatt auf Zahlungsart* ist eine Art Skontoumsetzung in plentymarkets. Du gewährst deinen Kontakten damit einen Rabatt auf die Verwendung einer oder mehrerer Zahlungsarten.

[TIP]
.Rabatt auf Zahlungsart direkt hinterlegen
====
Alternativ zu der Einstellung, die du in diesem Menü vornimmst, ist es möglich, direkt bei einer Zahlungsart einen globalen Rabatt für diese Zahlungsart zu hinterlegen. Ein Beispiel ist ein prozentualer Rabatt bei der Zahlungsart *Vorkasse*. Beachte dazu die Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>. Die Einstellung direkt bei der Zahlungsart erlaubt jedoch keine detaillierteren Einstellungen als bei der Option *Rabatt auf Zahlungsart* im Menü *Einrichtung » CRM » Kundenklassen*.
====

Gehe wie im Folgenden beschrieben vor, um einen Rabatt auf eine oder mehrere Zahlungsarten einzurichten.

[.instruction]
Rabatt auf Zahlungsart einrichten:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Klappe die Kundenklasse, für die der Rabatt gelten soll, auf (icon:plus-square-o[]).
. Gib ein *Zahlungsziel* in Tagen ein, das du dieser Kundenklasse einräumen möchtest.
. Aktiviere unter *Rabattart* die Option *Rabatt auf Zahlungsart*. +
→ Eine Tabelle mit weiteren Einstellungen wird geöffnet.
. Wähle eine oder mehrere Zahlungsarten, für die der Rabatt gelten soll.
. Gib unter *Rabatt in %* den Prozentwert für den Rabattabzug ein.
. Wähle, ob der *Mengenrabatt* berücksichtigt werden soll.
. Wähle, welche der im Webshop verfügbaren Zahlungsarten für die Kundenklasse erlaubt sein sollen.
. Gib einen Zahlungshinweis ein. +
→ Dieser Zahlungshinweis wird auf Einzelrechnungen angezeigt.
. Wähle, ob die Preise im Webshop *brutto* (inkl. MwSt.) oder *netto* (ohne MwSt.) angezeigt werden sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Informationen, wie du Kundenklassen erstellst, findest du im Kapitel <<crm/kontakte-verwalten#15, Kundenklasse erstellen>>.

[#29]
==== Verkaufspreis als Rabatt speichern

Ein mengenbezogener Rabatt wird im Menü *Einrichtung » Artikel » Verkaufspreise* als eigener Preis angelegt. Dort legst du mit der Option *Ab Menge* im Bereich *Einstellungen* für den Verkaufspreis fest, ab welcher Artikelmenge der rabattierte Preis gelten soll. Eine Staffelung realisierst du durch das Erstellen entsprechender Verkaufspreise mit den gewünschten Mindestmengen.

Der rabattierte Verkaufspreis wird aktiviert, wenn du in der Kundenklasse die Option *Mengenrabatt* auf *Berücksichtigen* setzt. Ein Kontakt erhält den Rabatt, wenn der Kontakt erstens zu der betreffenden Kundenklasse gehört und zweitens mindestens die beim Verkaufspreis gespeicherte Menge bestellt.

[.instruction]
Verkaufspreis als Rabatt speichern:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise*.
. Öffne den Verkaufspreis.
. Gib im Tab *Einstellungen* im Feld *Ab Menge* eine Ziffer ein, ab welcher Artikelmenge der rabattierte Preis gelten soll.
. Aktiviere im Bereich *Klasse* die Kundenklassen, für die der Verkaufspreis gelten soll.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Weitere Informationen zu Verkaufspreisen findest du im Themenbereich <<artikel#, Artikel>> im Kapitel <<artikel/artikel-verwalten#870, Verkaufspreise verwalten>>.

[#30]
==== Manuellen Rabatt eingeben

Zusätzlich zur Vergabe von automatischen Rabatten hastd du die Möglichkeit, einzelnen oder allen Artikelpositionen eines Auftrags manuell einen Rabatt zuzuweisen. Du kannst manuelle Rabatte in 2 verschiedenen Ansichten eingeben: in der Listenansicht der <<auftraege/auftraege-verwalten#1300, Auftragssuche>> und im Bearbeitungsfenster eines <<auftraege/auftraege-verwalten#1530, Auftrags>>.

[#31]
===== Rabatt für einzelnen Artikel in der Auftragssuche eingeben

Wenn du schnell einzelnen Artikelpositionen eines Auftrags einen Rabatt zuweisen oder den Rabattwert ändern möchtest, kannst du dies direkt in der Auftragssuche tun. Gehe wie im Folgenden beschrieben vor, um einen Rabatt für einzelne Artikel in der Auftragssuche einzugeben oder zu ändern.

[.instruction]
Rabatt für einzelnen Artikel in der Auftragssuche eingeben:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die Auftragssuche wird angezeigt.
. Klicke rechts in der Ansicht eines Auftrags auf *Rabatt* (Standard: *0%*). +
→ Ein Fenster zur Eingabe des Prozentsatzes wird geöffnet.
. Gib den als Rabatt gewünschten Prozentsatz ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Rabattwert wird angezeigt und der Rabatt wird von der Artikelposition abgezogen.

[#32]
===== Rabatt für einzelnen Artikel im Auftrag eingeben

In der Auftragsübersicht werden ganz unten die Artikelpositionen angezeigt. Auch hier hast du die Möglichkeit, einzelnen Artikelpositionen einen Rabattwert zuzuweisen oder den Rabattwert zu ändern. Gehe wie im Folgenden beschrieben vor, um einen Rabatt für einen Artikel im Auftrag einzugeben oder zu ändern.

[.instruction]
Rabatt für einzelnen Artikel im Auftrag eingeben:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, auf den ein Rabatt gewährt werden soll, mit einem Klick auf die Auftragsnummer.
. Öffne im Tab *Übersicht* des Auftrags im unteren Bereich das Tab *Bearbeiten* (icon:pencil[]).
. Wähle aus der Dropdown-Liste *Rabatt* den Rabattsatz.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#33]
===== Rabatt für alle Artikel eines Auftrags eingeben

Gehe wie im Folgenden beschrieben vor, um einen Rabatt für alle Artikelpositionen eines Auftrags einzugeben bzw. zu ändern.

[.instruction]
Rabatt für alle Artikel eines Auftrags eingeben:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, auf den ein Rabatt gewährt werden soll, mit einem Klick auf die Auftragsnummer.
. Öffne im Tab *Übersicht* des Auftrags im unteren Bereich das Tab *Bearbeiten* (icon:pencil[]).
. Klicke unterhalb der Liste der Artikelpositionen auf den Link *Rabatt für alle Artikel vergeben*.
. Wähle aus der angezeigten Dropdown-Liste den Rabattsatz.
. Klicke rechts neben der Dropdown-Liste auf *Speichern*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#50]
== Benutzerrechte für das Kontakt-Menü für Backend-Benutzer vergeben

Nutzer vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs im plentymarkets Backend. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter mit diesem Nutzertyp das Menü *CRM » Kontakte* sehen können, muss ein Nutzer vom Typ *Admin* zumindest die in <<tabelle-berechtigungen-kontakte>> beschriebenen Rechte für diesen Benutzer vergeben.

[TIP]
.Berechtigungen vergeben
====
Im Folgenden werden die Berechtigungen, die mindestens aktiviert werden müssen, damit das Menü sichtbar ist, beschrieben. Aktiviere weitere Berechtigungen analog.

Wenn der Benutzer z.B. Firmendatensätze sehen und erstellen soll, aktiviere im Bereich *CRM > Firma* die Optionen *Firma anzeigen* und *Firma erstellen*.
====


[.instruction]
Benutzerrechte für Backend-Benutzer vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne den zu bearbeitenden Benutzer.
. Aktiviere im Bereich *Berechtigungen* die Berechtigungen anhand von <<tabelle-berechtigungen-kontakte>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-berechtigungen-kontakte]]
.Berechtigungen für das Menü *CRM » Kontakte* vergeben
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*CRM > Adresse > Adresse anzeigen*
|Erlaubt dem Backend-Benutzer, Adressen zu sehen.

|*CRM > Kontakt > Kontakt anzeigen*
|Erlaubt dem Backend-Benutzer, Kontakte zu sehen. +

|*Einrichtung > Eigenschaft > Eigenschaft anzeigen*
|Erlaubt dem Backend-Benutzer, Eigenschaften zu sehen.

|*Einrichtung > Tag > Tag anzeigen*
|Erlaubt dem Backend-Benutzer, Tags zu sehen.

|====

[#90]
== Kontakte und Firmen verwalten

Erfahre in den folgenden Unterkapiteln, wie du z.B. neue Kontakte und Firmen erstellst, Kontakte mit einer Firma verknüpfst, nach vorhandenen Kontakten mit Filtereinstellungen suchst sowie vorhandene Kontakte bearbeitest und löschst.

[#100]
=== Kontakt erstellen

Gehe wie im Folgenden beschrieben vor, um einen neuen Kontakt zu erstellen. Verknüpfe den Kontakt mit einer bestehenden Firma oder erstelle eine neue Firma. Füge Kontaktoptionen wie z.B. E-Mail-Adressen und Telefonnummern hinzu. Erstelle einen neuen Kontakt z.B. während einer telefonischen oder schriftlichen Bestellung oder speichere die Daten eines Interessenten. Beim Erstellen eines Kontakts wird vom System automatisch eine ID vergeben. Diese ID kann nicht geändert werden.

Weitere Informationen zum Verknüpfen des Kontakts mit einer Firma und zum Erstellen einer neuen Firma findest du in den Kapiteln <<crm/kontakte-verwalten#210, Kontakt mit Firma verknüpfen>> und <<crm/kontakte-verwalten#220, Firma erstellen>>.

[.instruction]
Kontakt erstellen:

. Öffne das Menü *CRM » Kontakte*.
. Klicke auf *Neuen Kontakt erstellen* (icon:plus-square[role="green"]).
. Nimm die Einstellungen im Bereich *Neuer Kontakt* vor. Beachte dazu die Erläuterungen in <<tabelle-kontakt-erstellen>>.
. Weise im Bereich *Zugeordnete Tags* dem Kontakt einen oder mehrere Tags zu. Beachte dazu die Erläuterungen im Kapitel <<crm/kontakte-verwalten#150, Tags erstellen>>.
. Erstelle im Bereich *Firma* eine neue Firma oder weise dem Kontakt eine bestehende Firma zu. Beachte dazu die Erläuterungen in <<tabelle-kontakt-erstellen>>. +
→ Weitere Informationen findest du in den Kapiteln <<crm/kontakte-verwalten#220, Firma erstellen>> und <<crm/kontakte-verwalten#210, Kontakt mit Firma verknüpfen>>.
. Wähle im Bereich *Kontaktoptionen* den Typ und Subtyp aus den Dropdown-Listen und gib den Wert ein. Beachte dazu die Erläuterungen in <<tabelle-kontakt-erstellen>>. +
→ Mit einem Klick auf *Kontaktoption hinzufügen* fügst du weitere Kontaktoptionen hinzu.
. Füge die Adresse des Kontakts hinzu. +
→ *_Hinweis:_* Wenn du die Adresse zu einem späteren Zeitpunkt erstellen möchtest, deaktiviere die Umschaltfläche *Adresse erstellen?* (icon:toggle-on[role="green"]). +
→ Der Bereich *Neue Adresse* wird ausgeblendet und du kannst die Adresse später hinzufügen.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-kontakt-erstellen>> im Bereich *Adresse*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Kontakt wird erstellt.

[IMPORTANT]
.Kontaktoption: Subtyp *Privat* bei Typen *E-Mail* und *Telefon*
====
Achte darauf, dass du beim Erstellen der Kontaktoptionen für die Typen *E-Mail* und *Telefon* den Subtyp *Privat* wählst, damit diese Daten automatisch in den Auftrag übernommen werden.
====

[[tabelle-kontakt-erstellen]]
.Kontakt erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Neuer Kontakt*

|*Anrede*
|Anrede aus der Dropdown-Liste wählen. Die Auswahl ist optional. +
*Frau* = Weibliche Anrede +
*Herr* = Männliche Anrede +
*Divers* = Anrede für die Geschlechtsoption "Divers"

|*Titel*
|Ggf. Titel des Kontakts eingeben.

|*Vorname*, *Nachname*
|Vorname und Nachname des Kontakts eingeben. Das sind Pflichtfelder, wenn keine Firma gewählt wird.

|*Mandant*
|Mandant aus der Dropdown-Liste wählen, um den Kontakt diesem Mandanten zuzuordnen. +
Nur Mandanten, für die im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *Einstellungen* der Name gespeichert wurde, werden angezeigt.

|*Sprache*
|Sprache für den Kontakt wählen. Wenn du im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Vorlagen* eine Vorlage in der hier gewählten Sprache erstellt hast, werden E-Mail-Vorlagen in dieser Sprache versendet.

|*Typ*
|Typ wählen. Standardmäßig stehen die Typen *Kunde*, *Handelsvertreter*, *Lieferant*, *Partner*, *Hersteller* und *Interessent* zur Auswahl. Eigene Typen erstellst du im Menü <<crm/kontakte-verwalten#20, Einrichtung » CRM » Typen>>. +
*_Hinweis:_* Je nachdem, welche Einstellung gewählt ist, sind unterschiedliche Felder im Bereich *Firma* sichtbar. Die Erläuterungen dazu findest du in dieser Tabelle im Bereich *Firma*.

|*Klasse*
|Klasse wählen. Dies ist ein Pflichtfeld. Klassen dienen zur internen Unterscheidung und z.B. ob und welcher Rabatt dieser Klasse gewährt werden soll. Klassen werden im Menü <<crm/kontakte-verwalten#15, Einrichtung » CRM » Kundenklassen>> erstellt. Soll zum Beispiel zwischen Endkunden und Händlern bei der Preisanzeige im Webshop unterschieden werden, kann dies über die Option *Anzeige der Preise im Webshop* in den Einstellungen der Kundenklasse vorgenommen werden. Eine gängige Einstellung wäre z.B., dass bei Endkunden (B2C) die Bruttopreise und bei Händlern (B2B) die Nettopreise im Webshop angezeigt werden.

|*Bewertung*
|Kontakt für interne Zwecke bewerten. 5 rote Sterne stehen für die schlechteste und 5 gelbe Sterne für die beste Bewertung.

|*Kundennummer*
|Ggf. Kundennummer für den Kontakt eingeben. Kundennummern können für eine eigene interne Zuordnung genutzt werden und werden nicht automatisch vergeben. Du entscheidest, ob und in welcher Form du interne Kundennummern verwenden möchtest.

|*Eigner*
|Eigner für den Kontakt wählen. Wenn kein Eigner gewählt werden soll, die leere Option wählen. In der Dropdown-Liste werden ausschließlich Eigner angezeigt, für die im Menü *Einrichtung » Einstellungen » Benutzer » Konten* » _Benutzer öffnen_ im Tab *Eigner* die Option *Kunde* aktiviert wurde.

|*Debitorenkonto*
|Weitere separate Kundennummer eingeben. Diese Nummer entspricht in der Regel der Kundennummer bzw. Debitorennummer in deiner Finanzbuchhaltung und ist zur weiteren Bearbeitung deiner Belege hilfreich. Dieses Feld kann ggf. auch automatisch befüllt werden. +
Weitere Informationen zum Debitorenkonto findest du auf der Handbuchseite <<auftraege/buchhaltung#750, Buchhaltung>>.

|*Handelsvertreter*
|Hier kann dem Kontakt ein Handelsvertreter zugeordnet werden. Die ersten 3 Buchstaben des Namens oder die ID eingeben, um die Vorschlagsliste aufzurufen. Mit einem Klick auf die ID bzw. den Namen ist der Handelsvertreter dem Kontakt zugeordnet.

|*Rechnung erlauben* / +
*Lastschrift erlauben*
|Zahlungsart für den Kontakt erlauben, auch wenn diese Zahlungsart ansonsten global nicht verwendet wird. +
*Nicht erlauben* = Der Kontakt kann nicht mit dieser Zahlungsart zahlen. +
*Erlauben* = Der Kontakt kann mit dieser Zahlungsart zahlen, selbst wenn diese Zahlungsart nicht global angeboten wird. +
*_Beispiel:_* Ein Kontakt, der bereits mehrfach bei Ihnen bestellt hat, soll auf Rechnung einkaufen können. +
Notwendige Einstellungen: +
Einstellung 1: Die Zahlungsart im Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten* aktivieren. Mit dieser Einstellung wir die Zahlungsart zur Auswahl in einem Auftrag verfügbar. +
*_Wichtig:_* Keine Lieferländer wählen, da die Zahlungsart ansonsten global im Webshop verfügbar ist und dies in diesem Fall nicht gewünscht ist. +
Einstellung 2: Die Zahlungsart *Rechnung* bzw. *Lastschrift* muss in mindestens einem Versandprofil verfügbar sein, d.h. sie darf nicht gesperrt sein. +
Einstellung 3: Das Versandprofil bei den Artikeln aktivieren. +
Die hier genannten notwendigen Einstellungen prüfen und dann die Zahlungsart aktivieren, um dem Kontakt die Nutzung dieser Zahlungsart zu erlauben.

|*Geburtsdatum*
|Geburtsdatum des Kontakts nach dem Muster dd.mm.yyyy eingeben oder aus dem Kalender (icon:calendar[]) wählen.

|*Newsletter*
|Zeigt an, ob der Kontakt den Newsletter erhält. Es ist nicht möglich, die Option manuell zu aktivieren. Um den Newsletter-Bezug für den Kontakt zu deaktivieren, auf *Newsletter löschen* (icon:minus-square[role="red"]) klicken.

|*Kontakt gesperrt*
|Wählen, ob der Kontakt für den eingestellten Mandanten gesperrt sein soll oder nicht. +
Wenn die Option aktiviert ist, ist der Kontakt gesperrt und kann sich nicht mehr im Webshop einloggen. Wenn die Option deaktiviert ist, kann sich der Kontakt im Webshop einloggen.

2+|*Zugeordnete Tags*
2+|In das Feld klicken, um alle für den Bereich *Kontakte* verfügbaren Tags, die du zuvor im Menü *Einrichtung » Einstellungen » Tags* erstellt hast, anzuzeigen. +
icon:map-signs[] *_Oder:_* In das Feld klicken und die ersten 3 Buchstaben des Tag-Namens eingeben. Weitere Informationen zu Tags findest du im Kapitel <<crm/kontakte-verwalten#150, Tags erstellen>>.

2+|*Firma*

|*Name*
|Name der bereits <<crm/kontakte-verwalten#220, erstellten>> Firma in das Vorschlagsfeld eingeben, um diese Firma dem Kontakt zuzuordnen. Oder in das Feld klicken und die ersten 3 Buchstaben des Firmennamens eingeben. +
*_Wichtig:_* Das ist ein Pflichtfeld, wenn Vorname und Nachname nicht eingegeben wurden. +
Sobald eine bereits bestehende Firma aus der Vorschlagsliste gewählt wird, werden die zur Firma gehörenden Datenfelder direkt darunter angezeigt. Diese Datenfelder werden im Folgenden beschrieben. +
Wie du eine neue Firma erstellst, ist im Kapitel <<crm/kontakte-verwalten#220, Firma erstellen>> beschrieben. Wie du eine bestehende Firma bearbeitest, ist im Kapitel <<crm/kontakte-verwalten#230, Firma bearbeiten>> beschrieben.

|*USt-IdNr.*
|Umsatzsteueridentifikationsnummer des Kontakts eingeben. Wenn beim Versand von Waren an einen gewerblichen Käufer in ein anderes EU-Land (innergemeinschaftliche Lieferung) der Auftrag netto berechnet werden soll, muss die USt-IdNr. gespeichert sein. +
Nachdem die USt-IdNr. hier eingegeben wurde, muss im Menü <<auftraege/buchhaltung#400, Einrichtung » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung>> für die Option *Umsatzsteuer-ID* die Einstellung *Nettorechnung* gewählt werden. Mit dieser Einstellung werden Rechnungen für Kontakte, bei denen eine USt-IdNr. in den Daten eingegeben ist, ohne Umsatzsteuer ausgestellt. +
*_Wichtig:_* Die Nettoeinstellung greift nicht, wenn für das Lieferland des Kontakts Steuersätze gespeichert sind.

|*Valuta*
|Zeitraum (ab Rechnungserstellung) eingeben, wenn eine zusätzliche Frist vor dem Zeitraum *Zahlungsziel* gewünscht ist. Dazu die ausklappbare Box *Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen* unterhalb dieser Tabelle beachten. +
*_Wichtig:_* Valuta kann nur Firmenkontakten, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Wert für Valuta in der Rechnung im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *Standorte* » _Standort wählen_ » *Dokumente » Rechnung* zu speichern.

|*Zahlungsziel*
|Zahlungsziel für den Kontakt in Tagen eingeben. Dieses Zahlungsziel hat Priorität vor dem Zahlungsziel, das in der Kundenklasse festgelegt ist. Ein Zahlungsziel kann weiterhin optional im Dokument <<auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnung>> gespeichert werden. Das Zahlungsziel wird dann in der Rechnung ausgegeben, wenn für einen Kontakt und die Kundenklasse kein Zahlungsziel gespeichert wurde. Dazu die ausklappbare Box *Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen* unterhalb dieser Tabelle beachten. +
*_Wichtig:_* Das Zahlungsziel kann nur Firmenkontakten, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Wert für das Zahlungsziel in der Rechnung im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *Standorte* » _Standort wählen_ » *Dokumente » Rechnung* zu speichern.

|*Skontofrist*
|Anzahl der Tage (ab Rechnungserstellung) eingeben, in denen der Kontakt skontiert offene Forderungen bezahlen kann. Dazu die ausklappbare Box *Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen* unterhalb dieser Tabelle beachten. +
*_Wichtig:_* Skonto kann nur Firmenkontakten, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Skontowert in der Rechnung im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *Standorte* » _Standort wählen_ » *Dokumente » Rechnung* zu speichern.

|*Skontosatz*
|Wert in Prozent eingeben, den der Kontakt bei Einhaltung der *Skontofrist* in Abzug bringen kann. Dazu die ausklappbare Box *Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen* unterhalb dieser Tabelle beachten. +
*_Wichtig:_* Skonto kann nur Firmenkontakten, nicht aber Privatpersonen gewährt werden. Es ist jedoch möglich, einen Skontowert in der Rechnung im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *Standorte* » _Standort wählen_ » *Dokumente » Rechnung* zu speichern.

|*Lieferzeit*
|Nur sichtbar bei Wahl des Typs *Lieferant*. Lieferzeit in Tagen eingeben.

|*MBW*
|Nur sichtbar bei Wahl des Typs *Lieferant*. MBW steht für Mindestbestellwert. Mindestbestellwert in der Systemwährung eingeben.

|*Währung*
|Nur sichtbar bei Wahl des Typs *Lieferant*. Währung aus der Dropdown-Liste wählen. Diese Währung wird vorrangig für die jeweiligen Artikel und Aufträge berücksichtigt.

|*Eigner*
|Eigner aus der Dropdown-Liste wählen.

2+|*Handelsvertreter*

|*HV PLZ-Bereich Land*
|Nur sichtbar bei Wahl des Typs *Handelsvertreter*. Land aus der Dropdown-Liste wählen, für das der PLZ-Bereich des Handelsvertreters gelten soll. +
*_Tipp:_* Wenn ein Handelsvertreter in mehreren Ländern tätig ist, pro Land einen Kontaktdatensatz erstellen.

|*HV PLZ-Bereich*
|Nur sichtbar bei Wahl des Typs *Handelsvertreter*. PLZ-Bereich des Handelsvertreters eingeben. Mehrere Bereiche durch Kommata getrennt eingeben, z.B. *33, 34*. Je mehr Ziffern pro PLZ-Bereich, desto mehr wird der Bereich eingegrenzt.

2+|*Kontaktoptionen*

|*Typ*
|Typ aus der Dropdown-Liste wählen. +
Alle verfügbaren Typen sind in <<tabelle-typen-subtypen-kontaktoptionen>> aufgelistet.

|*Subtyp*
|Subtyp aus der Dropdown-Liste wählen. +
Alle verfügbaren Subtypen sind in <<tabelle-typen-subtypen-kontaktoptionen>> aufgelistet.

|*Wert*
|Wert eingeben.

2+|*Neue Adresse*
2+|Umschaltfläche deaktivieren, wenn du die Adresse zu einem späteren Zeitpunkt hinzufügen möchtest. Die Erläuterungen zu den Einstellungen einer neuen Adresse sind im Kapitel <<crm/kontakte-verwalten#600, Adresse hinzufügen>> beschrieben.

|====


[.collapseBox]
.*Beispiel:{nbsp}Gestaltung von Zahlungsbedingungen mit Valuta, Zahlungsziel, Skontofrist und Skontosatz*
--
Mit den Optionen *Valuta*, *Zahlungsziel*, *Skontofrist* und *Skontosatz* ist z.B. folgende Zahlungsbedingung möglich:

60 Tage Valuta, 30 Tage netto (Zahlungsziel), 10 Tage mit 2 % Skonto

Erläuterung: Zahlt der Kontakt innerhalb von 10 Tagen, erhält der Kontakt einen Skonto von 2%. Nach insgesamt 91 Tagen befindet sich die Zahlung im Verzug. Beim Import von Zahlungseingängen und der automatischen Zuordnung wird vorab intern automatisch geprüft, ob der von Kontakten durchgeführte Skontoabzug gültig ist. Ist der Skontozeitraum abgelaufen, erhält der Auftrag den Status *Teilzahlung erhalten*. Die oben aufgeführten Zahlungsbedingungen werden automatisch in den Auftrag sowie z.B. in die <<auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnung>> übernommen und können dort auch geändert werden. Bei Rechnungsdruck werden diese Bedingungen zu einer für diesen Auftrag gültigen Zahlungskondition zusammengefasst. Hierbei werden Valutatage auf die Zahlungszieltage aufgerechnet, um ein Zahlungsziel abzubilden. Auf einer Rechnung wird trotz der Addition von Valuta und Zahlungsziel Folgendes ausgegeben:

Zahlungskonditionen: Valuta 60 Tage, innerhalb von 10 Tagen 2% Skonto, innerhalb von 30 Tagen ohne Abzug. Wenn ein Wert für *Valuta* am Kontakt gespeichert ist, wird dieser für das Dokument verwendet, andernfalls der Wert unter *Zahlungsziel* bzw. der Wert aus der Kundenklasse, falls eingegeben. Als letzte Möglichkeit, wenn alles andere nicht gesetzt ist, wird die Anzahl der Tage aus der Option *Zahlungsziel* in den Einstellungen des Dokuments verwendet. Diese werden im Bereich <<auftraege/auftragsdokumente#1300, Optionale Elemente unter Artikelpositionstabelle>> eingestellt. Wichtig: Diese Optionen finden nur Anwendung auf den Bruttogesamtwert einer Rechnung.

--

[#110.subhead]
Verfügbare Typen und Subtypen der Kontaktoptionen

<<tabelle-typen-subtypen-kontaktoptionen>> listet alle verfügbaren Typen sowie Subtypen in den Kontaktoptionen auf.

[[tabelle-typen-subtypen-kontaktoptionen]]
.Verfügbare Typen und Subtypen der Kontaktoptionen
[cols="1,3"]
|====
|Typ |Subtyp

|Telefon
|Geschäftlich +
Mobil Privat +
Mobil Arbeit +
Privat +
*_Wichtig:_* Damit die Telefonnummer automatisch in den Auftrag übernommen wird, muss für den Typ *Telefon* der Subtyp *Privat* gewählt werden.

|E-Mail
|Geschäftlich +
Privat +
PayPal +
*_Wichtig:_* Damit die E-Mail-Adresse automatisch in den Auftrag übernommen wird, muss für den Typ *E-Mail* der Subtyp *Privat* gewählt werden.

|Telefax
|Geschäftlich +
Privat

|Webseite
|Geschäftlich +
Privat

|Marktplatz
|eBay +
Amazon

|Identifikationsnummer
|Klarna +
DHL

|Payment
|PayPal +
Klarna +
Standard

|Benutzername
|Geschäftlich +
Privat +
Forum

|Gruppe
|Forum

|Zugang
|Gast +
Marketplace Partner

|Zusatz
|Ansprechpartner

|Briefanrede
|Geschäftlich +
Privat

|====

[#150]
=== Tags erstellen

Du hast die Möglichkeit, Tags für deine Kontakte zu erstellen und nach diesen Tags auch in der Übersicht zu filtern. Tags sind Schlagworte, die du deinen Kontakten zuordnen kannst.

Zunächst musst du die Tags im Menü *Einrichtung » Einstellungen » Tags* erstellen und den Bereich *Kontakte* aktivieren. Wie du Tags erstellst, ist auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/tags#, Tags>> beschrieben.

[#151]
==== Tags zuordnen

Nachdem du Tags im Menü *Einrichtung » Einstellungen » Tags* erstellt und den Bereich *Kontakte* aktiviert hast, gehe wie im Folgenden beschrieben vor, um den oder die Tags einem Kontakt zuzuordnen.

[.instruction]
Tags zuordnen:

. Öffne das Menü *CRM » Kontakte*.
. Gib im Bereich *Filter* Suchbegriffe in die Suchfelder ein bzw. stelle Filteroptionen in den Dropdown-Listen ein. Beachte dazu die Erläuterungen in <<tabelle-filter-kontakte>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Gib im Bereich *Zugeordnete Tags* den Namen des Tags ein.
. Klicke auf den Namen des Tags in der Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Tag wird dem Kontakt zugeordnet und im Bereich *Zugeordnete Tags* angezeigt.

[TIP]
.Tags für den Bereich Kontakte
====
Nur Tags, für die der Bereich *Kontakte* im Menü *Einrichtung » Einstellungen » Tags* aktiviert wurde, stehen am Kontakt als Auswahl zur Verfügung.
====

Du kannst den Tag auch jederzeit mit einem Klick auf icon:times[] im Tag wieder vom Kontakt entfernen.

[#152]
==== Nach Tags filtern

Filtere nach Tags, um alle Kontakte, denen dieses Tag zugeordnet ist, anzuzeigen. Du hast die Möglichkeit nach einem oder mehreren Tags gleichzeitig zu filtern.

[.instruction]
Nach Tags filtern:

. Öffne das Menü *CRM » Kontakte*.
. Wähle im Bereich *Filter* einen oder mehrere Tags aus der Dropdown-Liste *Tags*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

[#200]
=== Kontakt suchen

Im Bereich *Filter* hast du die Möglichkeit, Kontakte nach bestimmten Kriterien zu suchen. Die gefundenen Kontakte werden dann im Bereich *Übersicht* angezeigt. In der Übersicht werden aktuell die folgenden Informationen angezeigt: ID, Gast, Aktionen (icon:bars[]), Firma, Vorname, Nachname, E-Mail-Adresse, Telefonnummer, Anzahl der Aufträge, Postleitzahl und Land. Wie du Kontaktdaten bearbeitest, ist im Kapitel <<crm/kontakte-verwalten#300, Kontakt bearbeiten>> beschrieben.

Du hast auch die Möglichkeit, alle gespeicherten Daten eines Kontakts inklusive Nachrichten, Aufträgen, Nachrichten und Tickets über die Schnellsuche anzuzeigen. Wie du dazu vorgehst, ist im Kapitel <<crm/kontakte-verwalten#1705, Datensätze über die Schnellsuche finden>> beschrieben.

[TIP]
.E-Mails direkt aus der Übersicht heraus versenden
====
Sende deinem Kontakt direkt aus der Kontaktübersicht heraus eine E-Mail. Mit einem Klick auf die E-Mail-Adresse öffnet sich dein E-Mail-Programm automatisch.
====

Um bestimmte Kontakte zu suchen, gibst du die dir bekannten Suchbegriffe in die Filter ein oder wählst die Einstellungen der Dropdown-Listen. Es ist auch möglich, mehrere Suchbegriffe gleichzeitig in die Suchfelder einzugeben. Dies ermöglicht eine schnellere und genauere Suche.

[.instruction]
Kontakt suchen:

. Öffne das Menü *CRM » Kontakte*.
. Gib im Bereich *Filter* Suchbegriffe in die Suchfelder ein bzw. stelle Filteroptionen in den Dropdown-Listen ein. Beachte dazu die Erläuterungen in <<tabelle-filter-kontakte>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet. +
icon:map-signs[] *_Oder:_* Öffne bestimmte Bereiche des Kontextmenüs wie *Neuer Auftrag* oder *Messenger* mit einem Rechtsklick.

[[tabelle-filter-kontakte]]
.Filter für die Kontakte
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Ohne gewählte Filtereinstellungen auf *Suchen* (icon:search[role="blue"]) klicken, um alle Kontakte anzuzeigen. +
icon:map-signs[] *_Oder:_* Die Suchergebnisse durch Filtereinstellungen eingrenzen und auf *Suchen* (icon:search[role="blue"]) klicken. +
→ Die gefundenen Kontakte werden in der Übersicht angezeigt.

|*Zurücksetzen*
|Mit einem Klick auf *Zurücksetzen* (icon:undo[role="orange"]) werden die  eingestellten Filterkriterien zurückgesetzt.

|*ID*
|Jeder Kontakt erhält automatisch eine fortlaufende und einzigartige ID. Dies ist unabhängig davon, ob der Kontakt manuell oder automatisch erstellt wurde. 2 Kontakte haben somit nie die gleiche ID. Die ID entspricht immer einer echten Zahl. Ungültig sind z.B. "00521" oder "ADF8354". +
*_Hinweis:_* Mit einem Klick auf den Pfeil neben der ID in der Übersicht kannst du die gefundenen Kontaktdatensätze aufsteigend oder absteigend nach ihrer ID anzeigen.

|*Name*
|Vorname und/oder Nachname oder Firmenname eingeben, um den oder die Kontakt mit diesem Namen bzw. Firmennamen anzuzeigen. Es wird auch nach Namen und Firmennamen, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen des Namens bzw. Firmennamens zu suchen. +
*_Hinweis:_* Mit einem Klick auf den Pfeil in den Spalten *Vorname* und *Nachname* in der Übersicht kannst du die gefundenen Kontaktdatensätze alphabetisch sortiert anzeigen.

|*Kontaktdaten*
|In diesem Feld kann nach dem Namen, der Adresse, der Firma, der Kundennummer und dem eBay-Namen gesucht werden. +
*_Hinweis:_* Um nach dem eBay-Namen zu suchen, zuerst den Parameter *ebay:* gefolgt vom gesuchten eBay-Namen eingeben.

|*Anschrift*
|Straßenname und/oder Hausnummer eingeben, der im Kontakt gespeichert ist. Es ist möglich, nur nach Teilen des Straßennamens und Teilen der Hausnummer zu suchen.

|*PLZ*
|Postleitzahl, die im Kontakt gespeichert sind, eingeben. Es wird auch nach Postleitzahlen, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen der Postleitzahl zu suchen.

|*Ort*
|Ort, der im Kontakt gespeichert ist, eingeben. Es wird auch nach Orten, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen des Ortsnamens zu suchen.

|*E-Mail*
|Komplette E-Mail-Adresse eingeben, um den Kontakt mit dieser E-Mail-Adresse anzuzeigen.

|*Telefon*
|Telefonnummer eingeben, um nur den Kontakt mit dieser Telefonnummer anzuzeigen. Es kann auch nach Teilen der Telefonnummer gesucht werden. Mindestens 3 Ziffern eingeben.

|*Land*
|Land wählen, um nur Kontakte aus diesem Land anzuzeigen. Das Land ist in den Kontaktdaten gespeichert.

|*Eigner*
|Eigner wählen, um nur Kontakte anzuzeigen, die mit diesem Eigner verknüpft sind. Der Eigner muss in den Kontaktdaten gespeichert sein. +
*_Wichtig:_* In der Dropdown-Liste werden nur Benutzer angezeigt, bei denen im Benutzerkonto im Tab *Eigner* die Option *Kunde* aktiviert ist.

|*Typ*
|Typ wählen, um nur Kontakte mit diesem Typ anzuzeigen.

|*Kundenklasse*
|Kundenklasse wählen, um nur Kontakte mit dieser Kundenklasse anzuzeigen.

|*Bewertung*
|Bewertung wählen, um nur Kontakte mit dieser Bewertung anzuzeigen. 5 gelbe Sterne stehen für die beste und 5 rote Sterne für die schlechteste Bewertung.

|*Tags*
|Tag wählen, um nur Kontakte mit diesem Tag anzuzeigen.

|*Mandant*
|Mandant wählen, um nur Kontakte dieses Mandanten anzuzeigen. Der Mandant ist in den Kontaktdaten gespeichert. +
*_Wichtig:_* Backend-Benutzern stehen nur Mandanten zur Auswahl, für die sie eine Berechtigung haben. Berechtigungen werden im Menü *Einrichtung » Einstellungen » Benutzer » Konten* im Tab <<basics/admin-aufgaben/benutzer-verwalten#90, Berechtigungen>> des Benutzerkontos eingestellt.

|====

[#210]
=== Kontakt mit Firma verknüpfen

Wenn du den Kontakt ohne eine Verknüpfung zu einer Firma erstellt hast, kannst du die Firma auch nachträglich verknüpfen. Um Verwechslungen auszuschließen, werden neben dem Firmennamen auch der Ort, die Straße und das Land der Firma angezeigt.

Gib mindestens 3 Buchstaben des Firmennamens, des Orts, der Straße oder des Landes ein, damit dein plentymarkets System dir bereits gespeicherte Firmendatensätze vorschlägt.

[.instruction]
Kontakt mit Firma verknüpfen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Gib im Bereich *Firma* den Namen der Firma, den Ort, die Straße oder das Land in das Feld ein. +
→ Sobald du 3 Buchstaben eingibst, werden dir bereits im System gespeicherte Firmendatensätze vorgeschlagen.
. Wähle den Firmendatensatz aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die zu der Firma gespeicherten Daten werden in der Detailansicht des Kontakts angezeigt.

[#220]
=== Firma erstellen

Erstelle die Firma und speichere Daten wie USt-IdNr., Zahlungsziel und Skontosatz.

[.instruction]
Firma erstellen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Bereich *Firma* auf *Neue Firma hinzufügen*. +
icon:map-signs[] *_Oder:_* Gib den Namen der Firma in das Vorschlagsfeld ein und klicke auf *Speichern*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-kontakt-erstellen>> im Bereich *Firma*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Firma wird erstellt und die Detailansicht des Kontakts wird geöffnet.

[TIP]
.Laden bereits vorhandener Firmendatensätze
====
Bereits gespeicherte Firmendatensätze werden beim Klick in das Vorschlagsfeld erst geladen, wenn du mindestens 3 Buchstaben des Firmennamens eingegeben hast.
====

[#230]
=== Firma bearbeiten

Wenn du bereits gespeicherte Firmendaten bearbeitest, werden die Daten des bereits vorhandenen Firmendatensatzes überschrieben.

[.instruction]
Firma bearbeiten:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Bereich *Firma* auf *Bearbeiten* (icon:pencil[role="yellow-background"]).
. Nimm die Änderungen vor. Beachte dazu die Erläuterungen in <<tabelle-kontakt-erstellen>> im Bereich *Firma*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Daten der bearbeiteten Firma werden überschrieben und die Daten der neu erstellten Firma werden in der Detailansicht des Kontakts angezeigt.

[#240]
=== Verknüpfung zwischen Firma und Kontakt löschen

Wenn du die Verknüpfung zwischen Firma und Kontakt in der Detailansicht des Kontakts wieder löschen möchtest, wird nur die Verknüpfung gelöscht und nicht die gespeicherten Firmendaten selbst. Die Firmendaten werden weiterhin in der Dropdown-Liste als Vorschlag angezeigt, wenn du mindestens 3 Buchstaben des Firmennamens, des Orts, der Straße oder des Landes eingibst.

[.instruction]
Verknüpfung zwischen Firma und Kontakt löschen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Bereich *Firma* in das Eingabefeld.
. Wähle die leere Option.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Verknüpfung zwischen Firma und Kontakt wird gelöscht.

[#300]
=== Kontakt bearbeiten

Suche den Kontakt anhand der <<crm/kontakte-verwalten#200, Filtereinstellungen>>. Öffne den Kontakt durch einen Klick in die Zeile des Kontakts, um dessen Daten, wie z.B. Geburtsdatum, Telefonnummer und E-Mail-Adresse, zu bearbeiten. Erläuterungen zu den Einstellungen und Optionen findest du in <<tabelle-kontakt-erstellen>> im Kapitel <<crm/kontakte-verwalten#100, Kontakt erstellen>>. Kontaktoptionen löschst du mit einem Klick auf *Kontaktoption löschen* (icon:minus-square[role="red"]).

[.instruction]
Kontakt bearbeiten:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet. +
icon:map-signs[] *_Oder:_* Öffne bestimmte Bereiche des Kontextmenüs wie *Neuer Auftrag* oder *Messenger* mit einem Rechtsklick auf Aktionen (icon:bars[]).
. Nimm die Änderungen vor. Beachte dazu die Erläuterungen in <<tabelle-kontakt-erstellen>> im Kapitel <<crm/kontakte-verwalten#100, Kontakt erstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#350]
=== Alter Webshop: Gastzugang in regulären Zugang umwandeln

Wenn der Kontakt als Gast in deinem alten Webshop (Callisto-Webshop) und nicht im Ceres-Webshop bestellt hat, wird diese Zugangsart als Kontaktoption in der Detailansicht des Kontakts gespeichert. Gastzugänge haben den Wert 1. Lösche die Kontaktoption mit dem Wert 1, um den Gastzugang in einen regulären Zugang umzuwandeln.

Informiere den Kontakt darüber, dass das Gastkonto in ein reguläres Konto umgewandelt wurde und sende dem Kontakt eine E-Mail, damit der Kontakt ein Passwort für den Login in deinem Webshop vergeben kann.

[.instruction]
Gastzugang in regulären Zugang umwandeln:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Bereich *Kontaktoptionen* in der Zeile der Zugangsart (Typ: *Zugang*, Subtyp: *Gast*, Wert: *1*) auf *Kontaktoption löschen* (icon:minus-square[role="red"]).
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Zugangsart in der Historie des Kontakts wird von *Gastzugang* auf *Regulärer Zugang* geändert.

[NOTE]
.Gastzugänge über Ceres-Webshop können nur in der Schnellsuche gefunden werden
====
Um DSGVO-konform zu arbeiten, wird bei Gastbestellungen über den Ceres-Webshop kein Kontaktdatensatz erstellt. Bestellungen, die als Gast über einen Ceres-Webshop aufgegeben wurden, können daher nicht über das Menü *CRM » Kontakte* gefunden werden. Die Daten des Gastes können nur über die Adressdaten im Menü *CRM » Schnellsuche* gefunden werden. +

Weitere Informationen zum Umwandeln von Ceres-Gastbestellungen in reguläre Kontaktdatensätze findest du im Kapitel <<crm/kontakte-verwalten#1705b, Gastzugang in Kontaktdatensatz umwandeln>>.

====

[#400]
=== Kontakt löschen

Du hast die Möglichkeit, einzelne Kontakte zu löschen. Ein Kontakt kann nur gelöscht werden, sofern dieser nicht mit einem Auftrag verknüpft ist.

[.instruction]
Kontakt in der Übersicht löschen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Öffne das Kontextmenü mit einem Rechtsklick in die Zeile des Kontakts.
. Klicke in der Liste auf *Kontakt löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicke auf *Löschen* (icon:minus-square[role="red"]). +
→ Der Kontakt wird gelöscht und aus der Übersicht entfernt.

Du kannst den Kontakt auch in der Detailansicht löschen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Kontakt in der Detailansicht löschen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Kontakt löschen*. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicke auf *Löschen* (icon:minus-square[role="red"]). +
→ Der Kontakt wird gelöscht und aus der Übersicht entfernt.

[TIP]
.Adressen ohne Aufträge, Kontakte, POS und Lager löschen (Gastkonten)
====
Im Menü *Einrichtung » Einstellungen » Daten » Bereinigung* kannst du einstellen, nach welcher Zeit ungenutzte Adressen automatisch aus deinem plentymarkets System gelöscht werden. Ungenutzte Adressen sind Adressen, die keine Verknüpfung zu einem Kontakt, einem Auftrag, einem POS und einem Lager haben.

Weitere Informationen zur Datenbereinigung findest du auf der Handbuchseite <<daten/datenbereinigung#, Datenbereinigung durchführen>>.
====

[#420]
=== Dublettenprüfung bei Kontaktdatensätzen mit identischer E-Mail-Adresse

Beim Erstellen neuer und beim Aktualisieren bestehender Kontaktdatensätze erfolgt eine Prüfung anhand der E-Mail-Adresse, um Dubletten im System zu vermeiden.

Die Logik funktioniert folgendermaßen:

* Beim Erstellen eines neuen Kontakts wird nach einem vorhandenen regulären Kontakt mit identischer privater E-Mail-Adresse gesucht. Wird ein Kontakt gefunden, wird dieser mit den neuen Daten aktualisiert. Wird kein Kontakt gefunden, wird ein neuer regulärer Kontakt erstellt.

* Wenn beim Aktualisieren eines bestehenden regulären Kontaktes die private E-Mail-Adresse geändert wird, wird zunächst gesucht, ob ein anderer regulärer Kontakt mit derselben privaten E-Mail-Adresse existiert. Ist dies der Fall, wird die private E-Mail-Adresse des aktuellen Kontaktes nicht aktualisiert, alle anderen Daten jedoch schon.

[#450]
=== vCard exportieren

Du hast die Möglichkeit, die Daten des Kontakts als Visitenkarte im VCF-Format zu exportieren.

[.instruction]
vCard exportieren:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke auf *Kontakt als vCard herunterladen* (icon:address-card-o[role="purple"]). +
→ Ein Fenster, in dem du den Speicherort auf deinem Computer wählst, wird geöffnet.
. Die vCard steht dir am gewählten Speicherort zur Verfügung.

[#455]
=== Kontaktdatensatz neu laden

Du hast die Möglichkeit, die Daten des Kontaktdatensatzes per Knopfdruck neu zu laden.

[.instruction]
Kontaktdatensatz neu laden:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke auf *Daten neu laden* (icon:undo[]). +
→ Die Daten des Kontaktdatensatzes werden neu geladen.

[#500]
== Historie anzeigen

Beim Erstellen des Kontakdatensatz wird die Historie eines Kontakts gespeichert. Die Historie beinhaltet z.B. das Datum, seit dem der Kontakt bei dir registriert ist, wann der Kontakt das letzte Mal in deinem Webshop eingeloggt war und wann der letzte Auftrag generiert wurde. Die Daten werden automatisch angepasst und können nicht geändert werden.

[.instruction]
Historie anzeigen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet und die Historie wird im rechten Bereich unterhalb der *Kontaktoptionen* angezeigt.
. Beachte dazu die Erläuterungen zur Historie in <<tabelle-historie-kontakt>>.

[[tabelle-historie-kontakt]]
.Historie im Kontaktdatensatz
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Registriert seit*
|Datum und Uhrzeit, seit wann der Kontakt registriert ist.

|*Aktualisiert*
|Datum und Uhrzeit, wann die Daten des Kontakts das letzte Mal aktualisiert wurden.

|*Zugangsart*
|Art, wie sich der Kontakt registriert hat. +
*Regulärer Zugang* = Der Kontakt hat sich neu registriert bzw. der Datensatz wurde manuell im Backend erstellt. +
*Gastzugang* = Der Kontakt hat sich über deinen Callisto-Webshop als Gast angemeldet und bestellt.

|*Letzter Auftrag*
|Datum und Uhrzeit, wann der letzte Auftrag eingegangen ist. Wenn kein Auftrag eingegangen ist, steht in diesem Feld *Keine Daten*.

|*Letzter Login*
|Datum und Uhrzeit des letzten Login. Wenn kein Login stattgefunden hat, steht in diesem Feld *Keine Daten*.
|====

[#510]
== Gruppenfunktion nutzen

Mit der Gruppenfunktion wird der Versand einer E-Mail-Vorlage, der Druck von Adressetiketten oder das Hinzufügen des Kontakts zu einem Newsletter-Ordner für einen oder mehrere Kontakte gleichzeitig ausgelöst.

[.instruction]
Gruppenfunktion nutzen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt bzw. die Kontakte anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke auf *Gruppenfunktion*.
. Aktiviere eine oder mehrere Aktionen und wählen die Optionen aus den Dropdown-Listen. Beachte dazu die Erläuterungen in <<tabelle-kontakt-gruppenfunktion>>.
. Aktiviere den Kontakt bzw. die Kontakte, für die du die Aktionen ausführen möchtest.
. Klicke auf *Gruppenfunktion*, um die gewählten Aktionen für die aktivierten Kontakte auszulösen.

[[tabelle-kontakt-gruppenfunktion]]
.Gruppenfunktion im Menü *CRM » Kontakte* nutzen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Adressetikett drucken*
|Druckt das aus der Dropdown-Liste gewählte Etikett von allen aktivierten Kontakten. +
*_Wichtig:_* Die Adressetikettenvorlage muss zuvor im Menü *Einrichtung » Aufträge » Dokumente » Adressetikett* <<fulfillment/dokumente-erzeugen#adressetikettenvorlage, erstellt>> worden sein. Ob die primäre Rechnungsadresse oder die primäre Lieferadresse des Kontakts ausgegeben wird, hängt von der Einstellung in der Adressetikettenvorlage ab.


|*E-Mail-Vorlage senden*
|Versendet die aus der Dropdown-Liste gewählte Vorlage an alle aktivierten Kontakte. +
*_Wichtig:_* Die E-Mail-Vorlage muss zuvor im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Vorlagen* <<crm/e-mails-versenden#1200, erstellt>> worden sein.

|*Zu Newsletter-Ordner hinzufügen*
|Kopiert die E-Mail-Adressen der aktivierten Kontakte in den aus der Dropdown-Liste gewählten E-Mail-Ordner im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner* für den Newsletterversand.

|*Zahlungsziel speichern*
|Speichert das eingegebene Zahlungsziel in Tagen in den Kontaktdatensätzen aller aktivierten Kontakte. +
*_Hinweis:_* Wenn du diese Aktion aktivierst und keinen Wert eingibst, wird für die aktivierten Kontakte der bisher gespeicherte Wert gelöscht.

|====

[#590]
== Adressen verwalten

Erfahre in den folgenden Unterkapiteln, wie du neue Adressen zu deinem Kontakt hinzufügst, alle zu deinem Kontakt gespeicherten Adressen anzeigst sowie bestehende Adressen bearbeitest und löschst.

[#600]
=== Adresse hinzufügen

Füge einem Kontakt beliebig viele Adressen sowie Adressoptionen wie z.B. die Telefonnummer des Kontakts hinzu.

In diesem Kapitel wird beschrieben, wie du Adressen zu einem bereits bestehenden Kontaktdatensatz hinzufügst. Wie du Adressen direkt beim Erstellen eines neues Kontakts hinzufügst, ist im Kapitel <<crm/kontakte-verwalten#100, Kontakt erstellen>> beschrieben.

[.instruction]
Adresse hinzufügen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Neue Adresse*.
. Nimm die Einstellungen im Bereich *Neue Adresse* vor. Beachte dazu die Erläuterungen in <<tabelle-adresse-hinzufuegen>>.
. Wähle im Bereich *Adressoptionen* den Typ aus der Dropdown-Liste und gib den Wert ein. Beachte dazu die Erläuterungen in <<tabelle-adresse-hinzufuegen>>. +
→ Mit einem Klick auf *Adressoption hinzufügen* fügst du weitere Adressoptionen hinzu.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Adresse wird der Übersicht im Bereich *Adressen* hinzugefügt.

[TIP]
.Anzeige der primären Rechnungs- und Lieferadresse
====
Nach dem Speichern der primären Rechnungsadresse und der primären Lieferadresse werden diese Adressen direkt beim Öffnen des Kontaktdatensatzes auf der rechten Seite im Bereich *Adressen* angezeigt. Mit einem Klick auf *Bearbeiten* (icon:pencil[role="yellow-background"]) öffnet sich die Adressansicht und die Adresse kann bearbeitet werden. +

Wenn weder eine Rechnungsadresse noch eine Lieferadresse als primär definiert wurde, werden die zuletzt hinzugefügte Rechnungsadresse und die zuletzt hinzugefügte Lieferadresse angezeigt.
====

[[tabelle-adresse-hinzufuegen]]
.Adresse hinzufügen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Neue Adresse*

|*Rechnungsadresse* / *Lieferadresse*
|Eine oder beide Optionen aktivieren, um den Adresstyp festzulegen. +
Die neue Adresse kann entweder nur Rechnungsadresse, nur Lieferadresse oder sowohl Rechnungsadresse als auch Lieferadresse sein. Wenn beide Optionen aktiviert sind, wird eine Adresse mit einer neuen ID und 2 Adresstypen erstellt. +
Sobald eine oder beide Optionen aktiviert sind, kann für eine oder beide Optionen gewählt werden, ob es sich um die primäre Adresse handelt.

|*Primär*
|Option aktivieren, wenn es sich bei der neuen Adresse um die primäre Rechnungsadresse bzw. primäre Lieferadresse handelt. +
Es ist möglich, beide Optionen zu aktivieren, wenn es sich bei der neuen Adresse sowohl um die primäre Rechnungsadresse als auch um die primäre Lieferadresse handelt. +
*_Hinweis:_* Wenn du mit einem Klick auf *Neuer Auftrag* einen neuen Auftrag anlegst, werden die primäre Rechnungsadresse und die primäre Lieferadresse automatisch im neuen Auftrag übernommen.

|*Anrede*
|Optional Anrede aus der Dropdown-Liste wählen.

|*Name 1 (Firma)*
|Firmenname eingeben. Das ist ein Pflichtfeld, wenn unter *Vorname* und *Nachname* kein Eintrag gemacht wird.

|*Name 2 (Vorname)*
|Vorname des Kontakts eingeben. Das ist ein Pflichtfeld, wenn unter *Firma* und *Nachname* kein Eintrag gemacht wird.

|*Name 3 (Nachname)*
|Nachname des Kunden eingeben. Das ist ein Pflichtfeld, wenn unter *Firma* und *Vorname* kein Eintrag gemacht wird.

|*Name 4 (Zusatz)*
|Optional Zusatzangaben zum Kontakt eingeben, z.B. z.Hd. Herrn Max Mustermann.

|*Adresse 1 (Straße)* +
*Adresse 2 (Hausnummer)*
| Straße und Hausnummer eingeben. +
*Straße* ist ein Pflichtfeld, wenn unter *Hausnummer* und *Adresszusatz* kein Eintrag gemacht wird. *Hausnummer* ist ein Pflichtfeld, wenn unter *Straße* und *Adresszusatz* kein Eintrag gemacht wird.

|*Adresse 3 (Adresszusatz)*
|Optional Adresszusatz eingeben, z.B. Apartment 12a. Das ist ein Pflichtfeld, wenn unter *Straße* und *Hausnummer* kein Eintrag gemacht wird.

|*Adresse 4 (Frei)*
|Feld zur freien Verfügung.

|*Postleitzahl* +
*Ort*
|Falls vorhanden Postleitzahl und Ort des Kontakts eingeben. *Ort* ist ein Pflichtfeld. +
Diese Angaben werden z.B. für die Rechnungsadresse verwendet. Bei bestimmten Ländern, z.B. Vereinigtes Königreich, wird die Reihenfolge der Optionen *Postleitzahl* und *Ort* getauscht.

|*Land* +
*Region/Bezirk*
|Werte aus den Dropdown-Listen wählen. +
*_Wichtig:_* Die Dropdown-Liste *Region/Bezirk* ist nicht für alle Länder verfügbar.

2+|*Adressoptionen (optional)*

|*Typ*
|Typ aus der Dropdown-Liste wählen bzw. Werte für die vorausgewählten Optionen *E-Mail* und *Telefon* eingeben. +
*_Hinweis:_* Die Typen *E-Mail* und *Telefon* werden statisch angezeigt. Weitere verfügbare Typen in der Dropdown-Liste: Umsatzsteuernummer, Externe Adress-ID, Gelangensbestätigung, Postnummer, Personennummer, FSK, Geburtstag, Titel, Ansprechpartner.

|*Wert*
|Wert eingeben.
|====

[#700]
=== Adressen anzeigen

Aus dem geöffneten Kontakt heraus lassen sich alle dem Kontakt zugehörigen Adressen anzeigen. Neben Informationen wie ID, Firmenname, Vorname, Nachname sowie Adresse, Adresszusatz und Land siehst du außerdem, um welchen Adresstyp es sich handelt – Rechnungsadresse oder Lieferadresse – und ob die Adresse eine primäre Adresse ist.

Wenn mehrere Adressen geöffnet sind, werden in der Dropdown-Liste der geöffneten Adressen die IDs der Adressen angezeigt.

Initial werden die Adressen deines Kontakts in der Kartenansicht angezeigt. Mit einem Klick auf *Zur Tabellenansicht wechseln* werden die Adressen in Tabellenform angezeigt. Dein plentymarkets System merkt sich, welche der beiden Ansichten du gewählt hast und zeigt beim nächsten Öffnen des Kontextmenüs *Adressen* die zuletzt gewählte Ansicht an.

Pro Seite werden bis zu 25 Adressdatensätze zu einem Kontakt angezeigt. Wenn mehr als 25 Adressen zu einem Kontakt gespeichert sind, hast du über die Toolbar die Möglichkeit, in den Seiten zu blättern, eine bestimmte Seite zu wählen und die Anzahl der Adressdatensätze pro Seite auf 50, 75 oder 100 zu ändern. Dein plentymarkets System merkt sich, welche Anzahl der Adressdatensätze du gewählt haben und zeigt beim nächsten Öffnen der Ansicht *Adressen* die zuletzt gewählte Einstellung an.

[.instruction]
Adressen anzeigen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherten Adressen werden angezeigt.
. Klicke auf *Bearbeiten* (icon:pencil[role="yellow-background"]), um die Detailansicht der Adresse zu öffnen. +
→ Wenn du die Tabellenansicht gewählt hast, klicke in die Zeile der Adresse, um die Detailansicht zu öffnen.

[#800]
=== Adresse bearbeiten

Du kannst bestehende Adressen sowie Adressoptionen jederzeit bearbeiten. Beachte dazu die Erläuterungen im Kapitel <<crm/kontakte-verwalten#600, Adresse hinzufügen>>. Adressoptionen löschst du mit einem Klick auf *Adressoption löschen* (icon:minus-square[role="red"]).

[.instruction]
Adresse bearbeiten:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherten Adressen werden initial als Karten angezeigt.
. Klicke in der Adresskarte, die du bearbeiten möchtest, auf *Bearbeiten* (icon:pencil[role="yellow-background"]). +
→ Die Detailansicht der Adresse wird geöffnet.
. Nimm die Änderungen vor. Beachte dazu die Erläuterungen in <<tabelle-adresse-hinzufuegen>> im Kapitel <<crm/kontakte-verwalten#700, Adresse hinzufügen>> sowie die Erläuterungen zur Toolbar in <<tabelle-adresse-bearbeiten>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-adresse-bearbeiten]]
.Adresse bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Speichern*
|Speichert (icon:save[role="green"]) die Einstellungen.

2+|*Rechnungsadresse*

|*Neue Rechnungsadresse ableiten*
|Klicke auf *Rechnungsadresse*, um diese Option zu wählen. +
Mit einem Klick auf *Neue Rechnunsadresse ableiten* wird eine neue Rechnungsadresse auf Basis der aktuell gewählten Adresse erstellt. Um eine neue Adresse mit einer neuen ID zu erstellen, müssen Änderungen an der neuen Rechnungsadresse vorgenommen werden.

|*Rechnungsadresstyp hinzufügen*
|Klicke auf *Rechnungsadresse*, um diese Option zu wählen. +
Mit einem Klick auf *Rechnungsadresstyp hinzufügen* wird der Typ *Rechnungsadresse* zu der Adresse hinzugefügt. Die ID ändert sich nicht. +
*_Hinweis:_* Diese Einstellung ist nicht sichtbar, wenn für die Adresse bereits der Typ *Rechnungsadresse* hinzugefügt wurde.

|*Rechnungsadresstyp löschen*
|Klicke auf *Rechnungsadresse*, um diese Option zu wählen. +
Mit einem Klick auf *Rechnungsadresstyp löschen* wird der Typ *Rechnungsadresse* in der Adresse gelöscht. +
Diese Einstellung ist nicht sichtbar, wenn der Typ *Rechnungsadresse* nicht für die Adresse hinzugefügt wurde.

|*Als primäre Rechnungsadresse definieren*
|Klicke auf *Rechnungsadresse*, um diese Option zu wählen. +
Mit einem Klick auf *Als primäre Rechnungsadresse definieren* wird die aktuell gewählte Rechnungsadresse als primäre Rechnungsadresse gesetzt. Die ID ändert sich nicht. +
Wenn der Typ *Rechnungsadresse* nicht vorhanden ist, ist diese Option deaktiviert. +
*_Hinweis:_* Wenn die Rechnungsadresse bereits als primär definiert wurde, kann man diese Einstellung mit einem Klick auf *Primäre Rechnungsadresse zurücksetzen* wieder rückgängig machen.

|*In Rechnungsadresse umwandeln* / +
*In Lieferadresse umwandeln*
|Mit einem Klick auf icon:exchange[role="yellow-background"] wird die aktuell gewählte Adresse in die Rechnungsadresse bzw. Lieferadresse umgewandelt. Die ID ändert sich nicht. +
Wenn beide Adresstypen bereits vorhanden sind, ist diese Option deaktiviert.

2+|*Lieferadresse*

|*Neue Lieferadresse ableiten*
|Klicke auf *Lieferadresse*, um diese Option zu wählen. +
Mit einem Klick auf *Neue Lieferadresse ableiten* wird eine neue Lieferadresse auf Basis der aktuell gewählten Adresse erstellt. Um eine neue Adresse mit einer neuen ID zu erstellen, müssen Änderungen an der neuen Lieferadresse vorgenommen werden.

|*Lieferadresstyp hinzufügen*
|Klicke auf *Lieferadresse*, um diese Option zu wählen. +
Mit einem Klick auf *Lieferadresstyp hinzufügen* wird der Typ *Lieferadresse* zu der Adresse hinzugefügt. Die ID ändert sich nicht. +
*_Hinweis:_* Diese Einstellung ist nicht sichtbar, wenn für die Adresse bereits der Typ *Lieferadresse* hinzugefügt wurde.

|*Lieferadresstyp löschen*
|Klicke auf *Lieferadresse*, um diese Option zu wählen. +
Mit einem Klick auf *Lieferadresstyp löschen* wird der Typ *Lieferadresse* in der Adresse gelöscht. +
*_Hinweis:_* Diese Einstellung ist nicht sichtbar, wenn der Typ *Lieferadresse* nicht für die Adresse hinzugefügt wurde.

|*Als primäre Lieferadresse definieren*
|Klicke auf *Lieferadresse*, um diese Option zu wählen. +
Mit einem Klick auf *Als primäre Lieferadresse definieren* wird die aktuell gewählte Lieferadresse als primäre Lieferadresse gesetzt. Die ID ändert sich nicht. +
*_Hinweis:_* Wenn der Typ *Lieferadresse* nicht vorhanden ist, ist diese Option deaktiviert. +
Wenn die Lieferadresse als primär definiert wurde, kann man diese Einstellung mit einem Klick auf *Primäre Lieferadresse zurücksetzen* wieder rückgängig machen.

|*Adressdatensatz löschen*
|Mit einem Klick auf icon:minus-square[role="red"] wird der Adressdatensatz vollständig gelöscht.
|====

[#900]
=== Adresse löschen

Sofern es sich bei der Adresse nicht um eine mit einem Auftrag verknüpfte Rechnungsadresse handelt, kannst du Adressen löschen. Dies ist z.B. nötig, wenn die Lieferadresse des Kontakts nicht mehr aktuell ist.

[NOTE]
.Löschen von Rechnungsadressen, die mit Aufträgen verknüpft sind, ist nicht möglich
====
Wenn die Adresse vom Typ *Rechnungsadresse* ist und mit einem Auftrag verknüpft ist, kannst du die Adresse nicht löschen. Eine Fehlermeldung wird angezeigt.
====

[.instruction]
Adresse löschen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Adressen*. +
→ Alle zu dem Kontakt gespeicherten Adressen werden initial als Karten angezeigt. +
. Klicke in der Adresskarte, die du löschen möchtest, auf *Löschen* (icon:minus-square[role="red"]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicke auf *Löschen*. +
→ Die Adresse wird gelöscht und aus der Übersicht entfernt.

[#990]
== Aufträge verwalten

Erfahre in den folgenden Unterkapiteln, wie du alle zu deinem Kontakt vorhandenen Aufträge anzeigen sowie neue Aufträge zu deinem Kontakt anlegst.

[#1000]
=== Aufträge anzeigen

Aus dem geöffneten Kontakt heraus kannst du eine Übersicht aller Aufträge des Kontakts aufrufen.

[.instruction]
Aufträge anzeigen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Aufträge*. +
→ Alle zu dem Kontakt gespeicherten Aufträge werden angezeigt. Über die Seitennummerierung legst du fest, ob 25, 50, 100 oder 250 Aufträge angezeigt werden.
. Klicke in die Zeile des Auftrags, um den Auftrag im Menü *Aufträge » Aufträge bearbeiten* zu öffnen und nähere Informationen einzusehen.

Du kannst den Auftrag auch bearbeiten. Aufträge können solange bearbeitet werden, bis ein Dokument für diesen Auftrag existiert. Weitere Informationen zu Aufträgen findest du auf der Handbuchseite <<auftraege/auftraege-verwalten#, Aufträge verwalten>>.

[#1100]
=== Auftrag anlegen

Lege mit einem Klick aus dem geöffneten Kontakt heraus manuell einen neuen Auftrag für den Kontakt an. Wenn der Kontakt im Webshop bestellt, wird der Auftrag automatisch in deinem plentymarkets System gespeichert. Bei telefonischen Bestellungen beispielsweise legst du den Auftrag hingegen manuell an. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Auftrag anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Neuer Auftrag*. +
→ Du gelangst direkt in den Bereich *Neuer Auftrag* im Menü *Aufträge » Aufträge bearbeiten*. +
→ *_Hinweis:_* Wenn eine Rechnungsadresse und/oder Lieferadresse als <<crm/kontakte-verwalten#600, primär>> definiert wurde, werden diese Adressen automatisch im neuen Auftrag übernommen.
. Nimm die Einstellungen vor. Beachte die Informationen auf der Handbuchseite <<auftraege/auftraege verwalten#, Aufträge verwalten>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#1110]
=== Sammelauftrag anlegen

Ein Sammelauftrag bietet die Möglichkeit, nicht bezahlte Aufträge eines Kontakts in einen Auftrag zu übernehmen. Das ist z.B. sinnvoll, wenn du mit deinem Kontakt vereinbart hast, dass der Kontakt nicht jede Rechnung einzeln, sondern pro Monat oder pro Quartal bezahlt.

Die Aufträge werden wie gewohnt bearbeitet und die Artikel versendet, bleiben jedoch unbezahlt. Das Anlegen eines Sammelauftrags ist nur möglich für Aufträge, die noch nicht bezahlt wurden.

Mit einem Klick auf *Neuer Sammelauftrag* werden alle Aufträge des Kontakts in einen Sammelauftrag zusammengefasst. Du legst im Vorfeld im Menü *Einrichtung » Aufträge » Auftragstypen » Multi-Order* fest, welche Bedingungen, wie z.B. Auftragstyp und Auftragsstatus, erfüllt sein müssen, damit ein Sammelauftrag angelegt werden kann.

[.instruction]
Sammelauftrag anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Neuer Sammelauftrag*. +
→ Der Sammelauftrag wird angelegt.

Nachdem der Sammelauftrag erfolgreich angelegt wurde, öffnet sich der Sammelauftrag automatisch im Menü *Aufträge*. Im Sammelauftrag generierst du dann im Tab *Belege* eine Sammelrechnung.

Weitere Informationen findest du auf der Handbuchseite <<auftraege/auftraege-verwalten#, Aufträge verwalten>> im Kapitel <<auftraege/auftraege-verwalten#800, Auftragstyp Sammelauftrag nutzen>>.

[#1150]
== Scheduler anzeigen

Im Bereich *Scheduler* werden Abo-Aufträge des Kontakts angezeigt. Außerdem können neue Scheduler-Aufträge angelegt werden. Über den Scheduler haben deine Kunden die Möglichkeit, bestimmte Artikel in deinem Webshop im Abonnement zu kaufen. Das Menü ist nur in deinem plentymarkets System sichtbar, wenn du es gebucht hast. Die Buchung nimmst du im Menü *plentymarkets Logo (Start) » Service-Center* im Tab *Vertrag* vor. Im Menü *Einrichtung » Aufträge » Scheduler* nimmst du die Einstellungen für deinen Webshop vor.

[.instruction]
Scheduler anzeigen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Scheduler*. +
→ Alle zu dem Kontakt verfügbaren Abonnements werden angezeigt.

Weitere Informationen findest du auf der Handbuchseite <<auftraege/scheduler#, Scheduler >>. Dort sind auch die Filteroptionen beschrieben, die du sowohl im geöffneten Kontaktdatensatz im Bereich *Scheduler* als auch im Menü *Aufträge » Scheduler » Scheduler-Aufträge* wählen kannst.

[#1190]
== Tickets verwalten

Erfahre in den folgenden Unterkapiteln, wie du Tickets erstellst und alle zu einem Kontakt vorhandenen Tickets aufrufst. Abhängig vom verwendeten plentymarkets Tarif musst du das Ticketsystem ggf. buchen, bevor es dir zur Verfügung steht.

[#1200]
=== Ticket erstellen

Das <<crm/ticketsystem-nutzen#, Ticketsystem>> in plentymarkets nutzt du zur Verwaltung deiner Kundenkommunikation. Erfahre im Folgenden, wie du ein neues Ticket direkt aus dem geöffneten Kontakt heraus erstellst.

[.instruction]
Ticket erstellen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Neues Ticket*. +
→ Du gelangst direkt in den Bereich *Neues Ticket* im Menü *CRM » Ticketsystem*. Die Kontakt-ID ist bereits vorausgefüllt. +
. Nimm die Einstellungen vor. Beachte die Informationen auf der Handbuchseite <<crm/ticketsystem-nutzen#1600, Ticketsystem nutzen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#1300]
=== Tickets anzeigen

Aus dem geöffneten Kontakt heraus kannst du eine Übersicht aller zu dem Kontakt gespeicherten Tickets aufrufen.

[.instruction]
Tickets anzeigen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Tickets*. +
→ Alle zu dem Kontakt gespeicherten Tickets werden angezeigt. Über die Seitennummerierung legst du fest, ob 10, 25, 50 oder 100 Tickets angezeigt werden.
. Klicke in die Zeile des Tickets, um das Ticket im Menü *CRM » Ticketsystem* zu öffnen und nähere Informationen einzusehen.

Du hast die Möglichkeit Tickets zu bearbeiten und zu löschen. Beachte dazu die Handbuchseite <<crm/ticketsystem-nutzen#, Ticketsystem nutzen>>.

[#1390]
== Nachrichten mit dem Messenger verwalten

Erfahre in den folgenden Unterkapiteln, wie du neue Nachrichten zu deinem Kontakt erstellst, alle zu einem Kontakt vorhandenen Nachrichten aufrufst sowie vorhandene Nachrichten löschst. Nachrichten sind nur in deinem plentymarkets Backend sichtbar und können nicht von deinen Kontakten aufgerufen werden.

[#1395]
=== Benutzerrechte für Backend-Benutzer vergeben

Nutzer vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs im plentymarkets Backend. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter mit diesem Nutzertyp Nachrichten im Messenger sehen und erstellen, muss ein Nutzer vom Typ *Admin* die in <<tabelle-berechtigungen-messenger>> beschriebenen Rechte für diesen Benutzer vergeben.

[.instruction]
Benutzerrechte für Backend-Benutzer vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne den zu bearbeitenden Benutzer.
. Aktiviere im Bereich *Berechtigungen* die Berechtigungen gemäß <<tabelle-berechtigungen-messenger>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-berechtigungen-messenger]]
.Berechtigungen für den Messenger vergeben
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*CRM > Messenger > Nachricht anzeigen*
|Erlaubt dem Backend-Benutzer, Nachrichten zu sehen.

|*CRM > Messenger > Nachricht erstellen*
|Erlaubt dem Backend-Benutzer, Nachrichten zu erstellen.

|*Kommentare > Kommentare anzeigen*
|Erlaubt dem Backend-Benutzer, Kommentare zu sehen.

|*Kommentare > Kommentare erstellen*
|Erlaubt dem Backend-Benutzer, Kommentare zu erstellen.

|*Einrichtung > Eigenschaft > Eigenschaft anzeigen*
|Erlaubt dem Backend-Benutzer, Eigenschaften zu sehen.

|*Einrichtung > Eigenschaft > Eigenschaft erstellen*
|Erlaubt dem Backend-Benutzer, Eigenschaften zu erstellen.

|*Einrichtung > Tag > Tag anzeigen*
|Erlaubt dem Backend-Benutzer, Tags zu sehen.

|*Einrichtung > Tag > Tag erstellen*
|Erlaubt dem Backend-Benutzer, Tags zu erstellen.

|====

[#1396]
=== Tags für den Messenger erstellen

Wie du Tags erstellst, hast du im Kapitel <<crm/kontakte-verwalten#150, Tags erstellen>> erfahren.

Für das Erstellen von Tags, die für den Messenger zur Verfügung stehen, ist es wichtig, dass du als Bereich *Ticket* wählst.

Bevor der Messenger das Ticketsystem vollständig ersetzt, werden wir eine Migration schreiben, die die Tag-Typen *Ticket* in Tags vom Typen *Messenger* umwandelt.

[#1400]
=== Nachricht mit dem Messenger erstellen

Erstelle zu jedem deiner Kontakte beliebig viele Nachrichten. Nachrichten sind nur in deinem plentymarkets Backend sichtbar, d.h. Kontakte können die gespeicherten Nachrichten nicht im Webshop sehen. Neue Texte gibst du über die Tastatur ein oder fügst sie über die Zwischenablage ein. Mit den Funktionen in der Symbolleiste formatierst du den Text, fügst Verlinkungen ein und lädst Dateien hoch.

[.instruction]
Nachricht erstellen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Öffne das Kontextmenü mit einem Rechtsklick in die Zeile des Kontakts.
. Klicke auf *Messenger*. +
. icon:map-signs[] *_Oder:_* Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Messenger*. +
→ Der Bereich *Messenger* wird geöffnet.
. Klicke auf das Plus-Zeichen (icon:plus-square[role="green"]).
. Wähle den oder die Empfänger aus der Dropdown-Liste *Empfänger*.
. Wähle ggf. Tags aus der Dropdown-Liste *Tags*.
. Gib einen Titel ein.
. Gib eine Nachricht ein. +
→ *_Hinweis:_* Füge Text über die Zwischenablage ein, formatiere ggf. den Text mit den Funktionen in der Symbolleiste und lade Dateien hoch.
. Klicke auf *Nachricht senden*. +
→ Die Nachricht wird erstellt.

[TIP]
.Anhänge versenden: zulässige Dateitypen
====
Die folgenden Dateitypen sind als Anhang in der Nachricht zulässig: +
bmp, csv, gif, jpeg, json, pdf, png, tiff, txt, zip.
====

[#1500]
=== Nachrichten im Messenger anzeigen

Aus dem geöffneten Kontakt heraus lassen sich alle zu dem Kontakt gespeicherten Nachrichten im Messenger anzeigen. Die Karten zeigen das Erstellungsdatum mit Uhrzeit und den Benutzernamen, der die Nachricht erstellt hat, an.

[.instruction]
Nachrichten im Messenger anzeigen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Messenger*. +
→ Alle zu dem Kontakt gespeicherten Nachrichten werden angezeigt.

Du kannst einzelne Nachrichten mit einem Klick auf die Nachricht anzeigen. Über die Sortierung kannst du die Nachrichten aufsteigend oder absteigend nach Datum anzeigen.

////
[.subhead]
Einzelne Nachricht öffnen

Du kannst einzelne Nachrichten mit einem Klick auf die Vorschau anzeigen.

Wenn mehr als eine Notiz des Kontakts geöffnet ist, wird in der Ansicht ein Pfeil angezeigt, über den man zwischen den geöffneten Notizen einfach und schnell hin- und herwechseln kann. Mit einem Klick auf icon:times[] wird die Notiz geschlossen und aus der Liste entfernt.
////

////
[#1600]
=== Notiz bearbeiten

Bearbeite Notizen, um Inhalte zu aktualisieren. Du hast die Möglichkeit, den Text zu formatieren, Verlinkungen einzufügen und Bilddateien hochzuladen.

[.instruction]
Notiz bearbeiten:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Notizen*. +
→ Alle zu dem Kontakt gespeicherten Notizen werden angezeigt.
. Klicke in der Notiz, die du bearbeiten möchtest, auf *Bearbeiten*.
. Nimm die Änderungen vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
////

[#1700]
=== Nachricht im Messenger löschen

Die Nachrichten im Messenger können jederzeit gelöscht werden, wenn die darin gespeicherten Informationen veraltet sind oder du diese nicht mehr benötigst. Beachte, dass beim Löschen die Hauptnachricht sowie alle zugehörigen Nachrichten gelöscht werden.

[.instruction]
Nachricht im Messenger löschen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Messenger*. +
→ Alle zu dem Kontakt gespeicherten Nachrichten werden angezeigt.
. Öffne die Nachricht, die du löschen möchtest. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicke auf *Löschen* (icon:minus-square[role="red"]). +
→ Die Nachricht wird gelöscht und aus der Übersicht entfernt.

[#1710]
== Dokumente verwalten

Erfahre in den folgenden Unterkapiteln, wie du Dokumente zu deinen Kontakten hochlädst, anzeigst, herunterlädst und löschst. Die Dokumente, die du in diesem Menü hochlädst, sind nur in deinem plentymarkets Backend sichtbar und können nicht von deinen Kontakten aufgerufen werden.

[#1720]
=== Kundendokumente hochladen

Im Bereich *Dokumente* lädst du Dokumente wie z.B. eine bereits im Vorfeld selbst durchgeführte Altersprüfung zu deinem Kontakt hoch. Entweder lädst du die Dateien über *Datei hochladen* oder per Drag&Drop in diesen Bereich hoch. Erstelle Ordner, um die Dokumente übersichtlicher zu gruppieren.

Zulässig sind Datenformate wie JPEG, PNG, GIF, TIFF, PDF, DOC, ODC, OTH, XLS, XML, HTML, HTM, CSS, ZIP und GZIP.

[.instruction]
Kundendokumente hochladen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Dokumente*.
. Klicke auf *Datei hochladen* (icon:upload[role="purple"]).
. Wähle die Dokumente aus.
. Klicke auf *Öffnen*, um die Dateien hochzuladen. +
icon:map-signs[] *_Oder:_* Ziehe Dokumente per Drag-and-Drop-Funktion in das Tab.

[NOTE]
.Ordner erstellen
====
Im Bereich *Ordner* kannst du Ordner erstellen. Dies ist sinnvoll, wenn du viele Dokumente zu deinem Kontakt hochgeladen hast, um diese Dokumente zu gruppieren und somit eine bessere Übersicht zu haben.
====

[#1730]
=== Dokumente anzeigen

Im Bereich *Dokumente* siehst du alle zum Kontakt verfügbaren Dokumente, die du hochgeladen hast. In der Übersicht sind der Dateiname, die Dateigröße sowie das Datum und die Uhrzeit der letzten Änderung zu sehen.

[.instruction]
Dokumente anzeigen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Dokumente*. +
→ Alle zu dem Kontakt gespeicherten Dokumente werden angezeigt.

[#1740]
=== Dokument herunterladen

Du hast die Möglichkeit, alle Dokumente, die du zu deinem Kontakt hochgeladen hast, herunterzuladen.

[.instruction]
Dokument herunterladen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Dokumente*. +
→ Alle zu dem Kontakt gespeicherten Dokumente werden angezeigt.
. Klicke in der Zeile des Dokuments, das du herunterladen möchtest, auf *Datei herunterladen* (icon:download[role="purple"]). +
→ *_Hinweis:_* Manche Browser speichern die Datei automatisch in dem von dir festgelegten Download-Ordner. Bei anderen Browsern lädst du die Datei selbst mit einem Klick herunter. Folge in diesem Fall den Anweisungen auf deinem Computer. Beachte, dass diese Anweisungen je nach verwendetem Browser und Programm variieren können.

[#1750]
=== Dokument löschen

Lösche ein Dokument, wenn du das Dokument nicht mehr benötigst. Wie du mehrere Dokumente gleichzeitig löschst, ist in der Box am Ende des Kapitels beschrieben.

[.instruction]
Dokument löschen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Dokumente*.
. Klicke in der Zeile des Dokuments, das du löschen möchtest, auf *Löschen* (icon:minus-square[role="red"]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt. +
. Klicke auf *Löschen* (icon:minus-square[role="red"]). +
→ Das Dokument wird gelöscht und aus der Übersicht entfernt.

[TIP]
.Mehrere oder alle Dokumente löschen
====
Markiere im Bereich *Dokumente* die Dokumente, die du löschen möchtest, oder aktiviere die Option neben *Dateiname*, um alle gespeicherten Dokumente zu markieren und anschließend zu löschen. Nachdem du die Sicherheitsabfrage mit *Löschen* (icon:minus-square[role="red"]) bestätigt hast, werden die markierten Dokumente gelöscht und aus der Übersicht entfernt.
====

[#1800]
== Kontostand anzeigen

Im Bereich *Konto* siehst du die Umsätze deines Kontakts. In der obersten Zeile siehst du neben dem Kontostand des Kontakts die Summe der Rechnungen des Kontakts, was du ihm in Form von Gutschriften gutgeschrieben hast und wie hoch die Differenz zwischen diesen beiden Beträgen ist. In der Tabelle sind die Aufträge und Gutschriften zu diesem Kunden als Vorgänge aufgeführt. Dabei sind die Spalten *Gezahlt* und *Ausstehend* besonders hilfreich. Wenn bei einem Auftrag ein Betrag unter *Ausstehend* aufgeführt ist, muss der Kontakt diesen Betrag noch an dich zahlen. Sobald der Kontakt bezahlt hat, wird der Betrag unter *Gezahlt* aufgeführt. Wenn bei einer Gutschrift noch ein Betrag unter *Ausstehend* aufgeführt ist, musst du diesen Betrag noch an den Kontakt zahlen. Sobald du gezahlt hast, wird der Betrag unter *Gezahlt* aufgeführt.

[.instruction]
Kontostand anzeigen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Konto*. +
→ Alle verfügbaren Daten zum Kontostand des Kontakts werden angezeigt.
. Beachte dazu die Erläuterungen in <<tabelle-kontostand-kontakt>>.

[[tabelle-kontostand-kontakt]]
.Einstellungen im Bereich *Konto* des Kontaktdatensatzes im Menü *CRM » Kontakte*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Saldo*
|Zeigt den Kontostand des Kontakts an. +
*+* = Summe der noch vom Kontakt zu zahlenden Beträge +
*-* = Summe der noch an den Kontakt zu zahlenden Beträge, wenn der Kontakt zu viel gezahlt hat oder eine Gutschrift noch ausgezahlt werden muss. +
*0,0* = keine ausstehenden Beträge

|*Rechnungen*
|Summe der Rechnungsbeträge aller Aufträge und die Anzahl der Rechnungen in Klammern

|*Gutschriften*
|Summe aller Gutschriften und die Anzahl der Gutschriften in Klammern

|*Delta*
|Differenz in Prozent zwischen den gezahlten Gutschriften und dem insgesamt bezahlten Rechnungsbetrag des Kontakts. Bei 0 % wurde dem Kontakt noch keine Gutschrift ausgezahlt. Bei 100 % wurde dem Kontakt jeder bezahlte Betrag wieder als Gutschrift zurückgezahlt.

|*Datum*
|Datum, an dem der Auftrag erstellt wurde

|*Auftrags-ID*
|ID des Auftrags. Ein Klick auf die ID öffnet die Detailansicht des Auftrags. IDs von Gutschriften sind eingerückt und unterhalb des Auftrags dargestellt.

|*Vorgang*
|Auftragsart, entweder Auftrag oder Gutschrift

|*Dokument*
|Dokumentennummer, z.B. Rechnungsnummer. Ein Klick auf die Nummer öffnet das Dokument.

|*Wert*
|Rechnungssumme des Auftrags

|*Gezahlt*
|Der bereits bezahlte Betrag

|*Zahlungsart*
|Zahlungsart des Auftrags

|*Ausstehend*
|Der zur vollständigen Bezahlung des Auftrags noch ausstehende Betrag.

|*Status*
|Status des Auftrags. Ein Klick auf den Status öffnet das Bearbeitungsfenster *Auftragsstatus*, in dem der Status geändert werden kann.

|====

[.subhead]
Kontodaten filtern 

Verwende Filter, um den Kontostand deines Kontakts anzuzeigen.

[.instruction]
Kontodaten filtern:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Konto*. +
→ Alle verfügbaren Daten zum Kontostand des Kontakts werden angezeigt.
. Nimm die Filtereinstellungen im Bereich *Filter* vor. Beachte dazu die Erläuterungen in <<tabelle-filter-kontodaten>>.
. Klicke auf *Suchen* (icon:search[role="blue"]).

[[tabelle-filter-kontodaten]]
.Filtereinstellungen im Bereich *Konto* des Kontaktdatensatzes im Menü *CRM » Kontakte*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Mit einem Klick auf icon:search[role="blue"] werden die gefundenen Kontodaten aufgelistet.

|*Zurücksetzen*
|Mit einem Klick auf *Zurücksetzen* (icon:undo[role="orange"]) werden die  eingestellten Filterkriterien zurückgesetzt.

|*Zeitraum*
|Eine der folgenden Einstellungen aus der Dropdown-Liste wählen: *ALLE*, *Dieses Jahr*, *Letztes Jahr*, *Diesen Monat*, *Letzten Monat* oder *Letzte 3 Monate*.

|*Ausstehend*
|*ALLE*, *Ja* oder *Nein* wählen. +
*Ja* = Nur ausstehende Beträge werden angezeigt. +
*Nein* = Nur gezahlte Beträge werden angezeigt. +
*ALLE* = Ausstehende und gezahlte Beträge werden angezeigt.

|*Vergleichsoperator / Status*
|Vergleichsoperator und Auftragsstatus aus den Dropdown-Listen wählen.

|*Rechnungsnr.*
|Rechnungsnummer eingeben.

|*Auftrags-ID*
|Auftrags-ID eingeben.

|====

[#1890]
== Bankdaten verwalten

Erfahre in den folgenden Unterkapiteln, wie du neue Bankdaten zu deinem Kontakt hinzufügst sowie bestehende Bankdaten bearbeitest und löschst.

[#1900]
=== Bankdaten hinzufügen

Im Bereich *Bankdaten* fügst du die Bankdaten deines Kontakts hinzu. Füge beliebig viele Bankdatensätze hinzu.

Die Bankdatensätze werden nach dem Speichern in Form von Karten dargestellt und zeigen neben dem Namen des Inhabers und der IBAN ein Tag, wenn das SEPA-Lastschriftmandat für den Kontakt aktiviert ist. Sofern im Bankdatensatz die BIC gespeichert ist, wird diese auch auf der Karte angezeigt.

[.instruction]
Bankdaten hinzufügen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Bankdaten*.
. Klicke auf *Hinzufügen*. +
→ Der Bereich *Neue Bankdaten* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-bankdaten-kontakt>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-bankdaten-kontakt]]
.Einstellungen im Bereich *Bankdaten* des Kontaktdatensatzes im Menü *CRM » Kontakte*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*IBAN*, *BIC*, *Inhaber*, *Kontonummer*, *Bankleitzahl*
|Bankdaten des Kontakts eingeben. *IBAN* und *Inhaber* sind Pflichtfelder.

|*Name, Straße, PLZ und Ort der Bank*
|Name und Adresse der Bank eingeben.

|*Land der Bank*
|Land aus der Dropdown-Liste wählen.

|*SEPA-Lastschriftmandat*
|Option aktivieren, wenn der Kontakt das SEPA-Lastschriftmandat unterschrieben hat. +
*_Wichtig:_* Erst nach dem Aktivieren dieser Option können die pain.008-Formate für den <<payment/bankdaten-verwalten#200, SEPA-Zahlungsverkehr>> abgerufen werden.

|*SEPA-Lastschriftmandat erteilt am*
|Nur sichtbar, wenn die Option *SEPA-Lastschriftmandat* aktiviert wurde. +
Das Datum, an dem der Kontakt dem SEPA-Lastschriftmandat zugestimmt hat, wird angezeigt. Oder das Datum aus dem Kalender wählen.

|*Art des Mandats*
|Nur sichtbar, wenn die Option *SEPA-Lastschriftmandat* aktiviert wurde. +
Option aus der Dropdown-Liste wählen: +
*SEPA-Basis-Lastschrift* = Mit der Einzugsermächtigung (Standardkunden) vergleichbares Mandat. +
*SEPA-Firmen-Lastschrift* = Mit dem Buchungsauftrag (Firmenkunden, B2B) vergleichbares Mandat.

|*Ausführungsmodalität*
|Nur sichtbar, wenn die Option *SEPA-Lastschriftmandat* aktiviert wurde. +
Option aus der Dropdown-Liste wählen: +
*Einmalige Zahlung* = Wird typischerweise für Standardaufträge verwendet. +
*Wiederkehrende Zahlung* = Wird typischerweise für regelmäßige Abbuchungen, Abo-Verträge etc. verwendet.
|====

[#2000]
=== Bankdaten bearbeiten

Du hast die Möglichkeit, die Bankdaten deiner Kontakte jederzeit zu aktualisieren.

[.instruction]
Bankdaten bearbeiten:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Bankdaten*.
. Klicke im Bankdatensatz, den du bearbeiten möchtest, auf *Bearbeiten* (icon:pencil[role="yellow-background"]). +
→ Der Bankdatensatz wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-bankdaten-kontakt>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#2100]
=== Bankdaten löschen

Lösche Bankdatensätze deiner Kontakte, wenn die Daten nicht mehr aktuell sind.

[.instruction]
Bankdaten löschen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Bankdaten*.
. Klicke im Bankdatensatz, den du löschen möchtest, auf *Löschen* (icon:minus-square[role="red"]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicke auf *Löschen* (icon:minus-square[role="red"]). +
→ Der Bankdatensatz wird gelöscht und aus der Übersicht entfernt.

[#2200]
== Events verwalten

Erfahre in den folgenden Unterkapiteln, wie du Events zu deinen Kontakten hinzufügst, anzeigst und löschst. Kostenpflichtige Events können auch abgerechnet werden.

[#2300]
=== Event hinzufügen

Füge beliebig viele Events hinzu. Ein Event kann z.B. ein Anruf oder E-Mail sein. Du kannst außerdem die Dauer eingeben, eine Information zum Vorgang wählen und einen Kommentar zum Event speichern. Wenn du das Event kostenpflichtig abrechnen möchtest, klicke beim Hinzufügen des Events auf *Hinzufügen und abrechnen*.

[.instruction]
Event hinzufügen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Events*.
. Wähle den Typ aus der Dropdown-Liste.
. Gib die Dauer des Events in Minuten ein.
. Wähle die Info aus der Dropdown-Liste.
. Gib den Infotext ein.
. Klicke auf *Event hinzufügen*.
. Wähle *Hinzufügen und abrechnen* oder *Hinzufügen*. +
→ Das Event wird der Liste hinzugefügt.

[#2400]
=== Events anzeigen

Du kannst die Events, die du zu deinen Kontakten gespeichert hast, jederzeit einsehen.

Außerdem ist es möglich, die Dauer des Events direkt aus der Übersicht heraus zu aktualisieren. Wie du dazu vorgehst, ist in der Box am Ende des Kapitels beschrieben.

[.instruction]
Events anzeigen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Events*. +
→ Die Liste der Events wird angezeigt.

[TIP]
.Dauer des Events aktualisieren
====
Du hast die Möglichkeit, die Dauer von bestehenden Events zu aktualisieren. Klicke dazu im Kontaktdatensatz im Bereich *Events* in der Übersicht auf *Dauer aktualisieren*. Das Fenster *Event-Dauer aktualisieren* wird daraufhin geöffnet. Gib dort die neue Zahl in Minuten ein und klicke auf *Aktualisieren*.
====

[#2500]
=== Event löschen

Lösche nicht mehr benötigte Events aus der Übersicht.

[.instruction]
Event löschen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Events*. +
→ Die Liste der Events wird angezeigt.
. Klicke in der Zeile des Events, das du löschen möchtest, auf *Löschen* (icon:minus-square[role="red"]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicke auf *Löschen*. +
→ Das Event wird gelöscht und aus der Übersicht entfernt.

[#2600]
== Zugangsdaten bearbeiten

Im Bereich *Zugangsdaten* des Kontaktdatensatzes hast du die Möglichkeit, das Passwort für deinen Kontakt manuell zu ändern, einen Link zum Ändern des Passworts zu versenden, den Login zu entsperren und den Mein Konto-Bereich des Kontakts über die Login-URL zu öffnen.

[#2700]
=== Passwort ändern

Ändere im Bereich *Passwort ändern* das Passwort manuell für deinen Kontakt.

[.instruction]
Passwort ändern:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Zugangsdaten*.
. Gib im Bereich *Passwort ändern* das Passwort ein.
. Klicke auf *Passwort speichern* (icon:save[role="green"]).


[#2750]
=== Passwörter für alle Konakte neu generieren

Im Menü *Einrichtung » CRM » Passwörter* generierst du neue Passwörter für deine Kontakte. Dies kann z.B. nötig sein, wenn sich jemand widerrechtlich Zutritt zu deinem plentymarkets System verschafft hat bzw. du von Datendiebstahl betroffen bist.

[TIP]
.Kein automatischer Versand der neu generierten Passwörter
====
Beachte, dass deine Kontakte die neu generierten Passwörter nicht automatisch erhalten. Du musst deine Kontakte aktiv, z.B. per E-Mail, über die Sachlage informieren und sie auffordern, ihr Passwort im Webshop bzw. Mein Konto-Bereich zu ändern.
====

Gehe wie im Folgenden beschriebenen vor, um neue Passwörter für alle Kontakte zu generieren.

[.instruction]
Passwörter für alle Kontakte neu generieren:

. Öffne das Menü *Einrichtung » CRM » Passwörter*.
. Klicke auf *Passwörter für alle Kunden neu generieren*. +
→ Die neuen Passwörter werden generiert.

[#2800]
=== Link zur Passwortänderung versenden

Sende deinem Kontakt eine E-Mail-Vorlage mit einem Link zur Passwortänderung in deinem Webshop. Voraussetzung dafür ist, dass du im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Automatischer Versand* eine E-Mail-Vorlage, die die Template-Funktion *{% Link_ChangePassword() %}* enthält, mit dem Ereignis *Sende Kunde E-Mail zur Passwortänderung* verknüpft hast.

Weitere Informationen zum automatischen E-Mail-Versand findest du auf der Handbuchseite <<crm/e-mails-versenden#2300, E-Mails versenden>>.

[.instruction]
Link zur Passwortänderung versenden:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Zugangsdaten*.
. Klicke auf *Link zur Passwortänderung*. +
→ Der Kontakt erhält eine E-Mail mit dem Link zur Passwortänderung in deinem Webshop.

[#2900]
=== Login entsperren

Wenn der Kontakt das Passwort beim Login in deinem Webshop mehrmals hintereinander falsch eingegeben hat, wird der Kontakt für das Login eine gewisse Zeit gesperrt. Mit einem Klick auf *Login entsperren* entsperrst du frühzeitig das Login und der Kontakt kann sich wieder einloggen.

[.instruction]
Login entsperren:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Zugangsdaten*.
. Klicke auf *Login entsperren*. +
→ Der Kontakt kann sich erneut in deinem Webshop anmelden.

[#3000]
=== Mein Konto-Bereich des Kontakts öffnen

Im Bereich *Login-URL* wird die URL für einen direkten Zugang zum Mein Konto-Bereich des Kontakts im Webshop angezeigt. Wenn diese URL verwendet wird, ist eine Eingabe der Login-Daten (E-Mail-Adresse und Passwort) im Webshop nicht mehr nötig.

Damit die Login-URL automatisch erzeugt wird, muss sowohl die E-Mail-Adresse im Menü *CRM » Kontakte* » _Kontakt öffnen_ im Bereich *Kontaktoptionen* als auch das Passwort im Menü *CRM » Kontakte* » _Kontakt öffnen_ » *Bereich: Zugangsdaten* gespeichert sein. Nach dem Speichern wird die Login-URL erzeugt. Verwende ein sicheres Passwort, andernfalls wird eine Fehlermeldung ausgegeben.

[.instruction]
Mein Konto-Bereich des Kontakts öffnen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Zugangsdaten*.
. Klicke im Bereich *Login-URL* auf *Link öffnen* oder kopiere die Login-URL mit einem Klick auf *In Zwischenablage kopieren* (icon:clipboard[role="yellow-background"]) und füge den Link in den Browser ein. +
→ Der Mein Konto-Bereich des Kontakts im Webshop wird geöffnet.

[#3100]
== Provisionen verwalten

Im Tab *Artikelprovisionen* gibst du artikelbezogene Provisionen für den Typ *Handelsvertreter* ein. Gehe wie im Folgenden beschrieben vor, um Werte für Provisionen einzugeben.

[.instruction]
Provision eingeben:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Provision & Kostenstellen*.
. Wechsele in das Tab *Provisionen*.
. Wechsele in das Tab *Artikelprovisionen*.
. Klappe den Bereich *Neue Provision* (icon:plus-square-o[]) auf.
. Gib die *Artikel-ID* des Artikels ein, für den du eine oder mehrere Provision(en) eingeben möchtest.
. Gib die Provision(en) in Prozent ein. +
→ Gib bis zu 4 Provisionen pro Eintrag ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Provision wird gespeichert. Damit du auf einen Blick erkennen kannst, um welchen Artikel es sich handelt, wird nach erneutem Laden durch Klick auf das Tab *Einstellungen* oder das Tab mit der Kontakt-ID zusätzlich der Name des Artikels in der Übersicht angezeigt.

[#3200]
== Kostenstellen verwalten

Im Bereich *Kostenstellen* erstellst du Kostenstellen. Du hast auch die Möglichkeit, bereits angelegte Kostenstellen zu bearbeiten. Bei einer Kostenstelle handelt es sich um den Ort der Kostenentstehung und Kostenzurechnung, quasi ein betrieblicher Bereich, der selbstständig abgerechnet wird.

[.instruction]
Kostenstelle erstellen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Provision & Kostenstellen*.
. Wechsele in das Tab *Neue Kostenstelle*.
. Gib den *Kostenstellennamen*, das *Budget* und das *Restbudget* ein.
. Wähle *Jahr* oder *Monat* als Budgetperiode.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Kostenstelle wird der Übersicht hinzugefügt.

[#3300]
== Statistik erstellen

Im Bereich *Statistik* erstellst du kundenspezifische Statistiken. Damit kannst du bestimmte Daten speziell für diesen Kontakt auswerten und als Statistik anzeigen, z.B. den Gesamtumsatzverlauf des Kontakts in einem bestimmten Zeitraum. Bestehende Statistiken kannst du in diesem Bereich auch bearbeiten. Weitere Informationen findest du im Kapitel <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#70, Kundenstatistiken>>.

[.instruction]
Statistik erstellen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf der linken Seite auf *Statistik*.
. Klicke auf *Neuer Bereich*.
. Gib einen Namen ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Ein Tab mit dem soeben eingegebenen Namen wird geöffnet.
. Klicke auf *Hinzufügen*. +
→ Das Fenster *Neue Statistik* wird geöffnet.
. Wähle den Statistiktyp aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Daten werden geladen und angezeigt.

Je nachdem, welchen Statistiktyp du gewählt hast, findest du weitere Informationen in den folgenden Kapiteln der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistiken verwalten>>:

* <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#20, Gesamtumsatzverlauf>>
* <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#100, Umsatz nach Kategorie>>
* <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#20, Umsatz Herkunft Auftrag>>

Allgemeine Informationen, wie du z.B. Statistiken bearbeitest, findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistiken verwalten>>.


[#4000]
== Eigenschaften verwalten

Eigenschaften sind wiederholt auftretende Informationen, die du in verschiedenen Bereichen von plentymarkets anwendest. Eigenschaften werden zentral im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* verwaltet.

[WARNING]
.Wichtige Hinweise zu den Kontakteigenschaften
====
Die Eigenschaften können vorerst ausschließlich über das plentymarkets Backend hinzugefügt und angezeigt werden. Das heißt, es ist vorerst nicht möglich, dass der Kontakt Daten in deinem Webshop, z.B. während des Bestellvorgangs oder wenn der Kontakt sich in deinem Webshop registriert, eingeben kann. Diese Funktionalität befindet sich derzeit in Arbeit.

Du kannst Eigenschaften jedoch schon im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* erstellen sowie Werte hinzufügen.

*_Wichtig:_* Für die Eigenschaften, die du in der Vergangenheit im Menü *Einrichtung » CRM » Eigenschaften (deprecated)* erstellt hast, ist eine Migration geplant. Das heißt, du musst die dort erstellten Eigenschaften nicht in das neue Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* übertragen. Wir informieren dich über den Zeitpunkt der Migration in der Forumskategorie link:https://forum.plentymarkets.com/c/changelog[Changelog^].

====

[#4100]
=== Eigenschaft erstellen

Im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* erstellst du Eigenschaften, die du im Anschluss für die nähere Charakterisierung deiner Kontakte nutzt.

//Für die spätere Verwendung der Eigenschaften hast du 2 Möglichkeiten: Du kannst die Informationen entweder im Bestellvorgang oder in der Kundenregistrierung von deinen Kontakten abfragen oder du nutzt die Eigenschaften, um selbst Informationen zu den Kontakten im Kontaktdatensatz zu speichern.

//Im Fall der Abfrage vom Kontakt bestimmst du, ob die Angabe ein Pflichtfeld ist und somit zwingend durch den Kontakt eingegeben werden muss. Du kannst beispielsweise bei der Registrierung abfragen, wie der Kontakt auf deinen Webshop aufmerksam geworden ist. Für die Eigenschaft wählst du dann als *Typ* die Option *Text einzeilig* oder die Option *Text mehrzeilig*, damit der Kontakt die Information dort eingeben kann.

Gehe wie im Folgenden beschrieben vor, um eine Eigenschaft zu erstellen.

[.instruction]
Eigenschaft erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*. +
→ Die Übersicht der Eigenschaften wird geöffnet.
. Klicke auf *Eigenschaft hinzufügen*.
. Wähle in der Dropdown-Liste *Bereich* die Option *Kontakt*.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-eigenschaft-erstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Eigenschaft wird erstellt und zur weiteren Bearbeitung geöffnet.

[[tabelle-eigenschaft-erstellen]]
.Eigenschaften erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Bereich*
|Bereich aus der Dropdown-Liste wählen, in dem die Eigenschaft genutzt werden soll. +
*Artikel* = Eigenschaft wird für Artikel verwendet. +
//*Stock* = Eigenschaft wird für die Lagerverwaltung verwendet. +
*Kontakt* = Eigenschaft wird für Kontakte verwendet. +
*Lagerort* = Eigenschaft wird für Lagerorte verwendet. +

|*Eigenschaftstyp*
|Typ der Eigenschaft aus der Dropdown-Liste wählen. +
*Kein* = Kein Eigenschaftstyp +
*Ganze Zahl* = Ermöglicht die Eingabe einer ganzen Zahl. +
*Kommazahl* = Ermöglicht die Eingabe einer Zahl mit Kommastellen. +
*Auswahl* = Ermöglicht es, aus mehreren Optionen zu wählen. +
*Kurztext* = Kurztext eingeben. +
//Ermöglicht die Eingabe eines Textes mit bis zu XXX Zeichen. +
*Text* = Text eingeben. +
//Ermöglicht die Eingabe eines Textes mit bis zu XXX Zeichen. +
*Datum* = Ermöglicht die Eingabe eines Datums. +
//*Datei* = Ermöglicht das Hochladen einer Datei.

|*Name*
|Name für die Eigenschaft eingeben. +
//Dieser Name wird z.B. im Bestellvorgang angezeigt. +
*_Hinweis:_* Standardmäßig wird der Name für die Systemsprache angezeigt. Nachdem die Eigenschaft erstellt wurde, kannst du den Namen in englischer Sprache speichern. Weitere Sprachen sind in Planung.

|*Beschreibung*
|Beschreibung der Eigenschaft eingeben. +
*_Hinweis:_* Standardmäßig wird die Beschreibung für die Systemsprache angezeigt. Nachdem die Eigenschaft erstellt wurde, kannst du die Beschreibung in englischer Sprache speichern. Weitere Sprachen sind in Planung.

|*Gruppe*
|Optional eine Eigenschaftsgruppe aus der Dropdown-Liste wählen, um die Eigenschaft dieser Gruppe zuzuordnen. +
*_Tipp:_* Auf *Eigenschaftsgruppe hinzufügen* klicken, um eine Gruppe zu erstellen.

|*Position*
|Positionsnummer für die Eigenschaft eingeben. Standardmäßig wird aufsteigend nach Positionsnummer sortiert. +
*_Tipp:_* Positionsnummern in 10er-Schritten vergeben, damit neue Eigenschaften dazwischen eingefügt werden können.
|====

[#4200]
=== Eigenschaft bearbeiten

Im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* findest du alle Eigenschaften. Hier änderst du die in <<tabelle-eigenschaft-erstellen>> beschriebenen Einstellungen.

[.instruction]
Eigenschaft bearbeiten:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Klicke auf *Suchen* (icon:search[role="blue"]), um alle Eigenschaften anzuzeigen oder wähle Filter, um die Ergebnisse einzugrenzen.
. Klicke auf die Eigenschaft. +
→ Das Tab *Allgemein* wird geöffnet.
. Bearbeite die Einstellungen. Beachte dazu die Erläuterungen in <<tabelle-eigenschaft-bearbeiten>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-eigenschaft-bearbeiten]]
.Eigenschaften bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Allgemein*

|*Position*
|Neue Position eingeben, um die Anzeigereihenfolge zu ändern.

|*Pflichtfeld* (aktuell ohne Funktion)
|Aktivieren, damit die Eigenschaft zu einer Pflichteingabe wird. Pflichtfelder werden in der Detailansicht des Kontakts im Bereich *Eigenschaften* und ggf. im Bestellvorgang fett markiert. +
*_Hinweis:_* Diese Einstellung ist aktuell noch ohne Funktion.

|*Bestellvorgang* (aktuell ohne Funktion)
|Aktivieren, damit die Eigenschaft im Bestellvorgang angezeigt wird. +
*_Hinweis:_* Diese Einstellung ist aktuell noch ohne Funktion.

|*Kundenregistrierung* (aktuell ohne Funktion)
|Aktivieren, damit die Eigenschaft in der Kundenregistrierung angezeigt wird. +
*_Hinweis:_* Diese Einstellung ist aktuell noch ohne Funktion.

|*Name*; +
*Beschreibung*
|Für Mehrsprachigkeit Name und Beschreibung für weitere Sprachen eingeben. +
*_Hinweis:_* Aktuell können Namen und Beschreibungen nur in deutscher und englischer Sprache gespeichert werden. Weitere Sprachen sind in Planung.

2+|*Sichtbarkeit*

|*Mandant*
|Einen oder mehrere Mandanten wählen, um die Eigenschaft für diese Mandanten zu aktivieren.

|*Sichtbarkeit*
|Einen oder mehrere Typen wählen, für die die Eigenschaft sichtbar sein soll.

2+|*Werte*

|Nur bei Eigenschaftstyp *Auswahl*
|Die Werte eingeben, die in der Dropdown-Liste dargestellt werden sollen. +
Auf *Wert hinzufügen* klicken, um einen Wert zu erstellen. +
*Name* = Name für den Eigenschaftswert eingeben.
|====

[#4300]
=== Eigenschaft suchen

Eigenschaften verwaltest du zentral im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*. Führe nach dem Öffnen des Menüs eine Suche aus, um Eigenschaften anzuzeigen. Um Eigenschaften nach bestimmten Kriterien zu suchen, gib die dir bekannten Suchbegriffe in die Filter ein. Die Dropdown-Listen helfen dir, Eigenschaften zu suchen, die bestimmte Kriterien gemeinsam haben. Du kannst beliebig viele Suchfilter miteinander kombinieren.

[.instruction]
Eigenschaft suchen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Gib im Bereich *Filter* Suchbegriffe in die Suchfelder ein bzw. stelle Filteroptionen in den Dropdown-Listen ein. Beachte dazu die Erläuterungen in <<tabelle-filter-eigenschaften>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Eigenschaften, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile der Eigenschaft. +
→ Die Detailansicht der Eigenschaft wird geöffnet.

[[tabelle-filter-eigenschaften]]
.Filter für die Eigenschaften
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Ohne gewählte Filtereinstellungen auf *Suchen* (icon:search[role="blue"]) klicken, um alle Eigenschaften anzuzeigen. +
icon:map-signs[] *_Oder:_* Die Suchergebnisse durch Filtereinstellungen eingrenzen und auf *Suchen* (icon:search[role="blue"]) klicken. +
→ Die gefundenen Eigenschaften werden in der Übersicht angezeigt.

|*Zurücksetzen*
|Mit einem Klick auf *Zurücksetzen* (icon:undo[role="orange"]) werden die  eingestellten Filterkriterien zurückgesetzt.

|*ID*
|Jede Eigenschaft erhält automatisch eine fortlaufende und einzigartige ID.

|*Name*
|Name eingeben, um die Eigenschaft mit diesem Namen zu suchen. Es ist möglich, nur nach Teilen des Namens zu suchen.

|*Sprache*
|Sprache wählen, um nur Eigenschaften anzuzeigen, für die ein Name in dieser Sprache gespeichert ist.

|*Gruppe*
|Gruppe wählen, um nur Eigenschaften anzuzeigen, die dieser Gruppe zugeordnet sind. +
*Nicht gruppiert* wählen, um nur Eigenschaften anzuzeigen, die keiner Gruppe zugeordnet sind. +
*Gruppiert* wählen, um nur Eigenschaften anzuzeigen, die einer Gruppe zugeordnet sind.

|*Bereich*
|Bereich wählen, um nur Eigenschaften dieses Bereichs anzuzeigen.

|*Eigenschaftstyp*
|Eigenschaftstyp wählen, um nur Eigenschaften dieses Typs anzuzeigen.
|====

[#4400]
=== Eigenschaft löschen

Du kannst entweder eine Eigenschaft oder mehrere Eigenschaften gleichzeitig löschen.

[#4500]
==== Eine Eigenschaft löschen

Gehe wie im Folgenden beschrieben vor, um eine Eigenschaft unwiderruflich zu löschen.

[.instruction]
Eine Eigenschaft löschen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Führe die Suche aus. +
→ Wähle ggf. Filter, um die Ergebnisse einzugrenzen.
. Klicke auf die Eigenschaft. +
→ Die Eigenschaft wird geöffnet.
. Klicke auf *Eigenschaft löschen* (icon:minus-square[role="red"]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicke auf *Löschen*. +
→ Die Eigenschaft wird gelöscht und aus der Übersicht entfernt.

[#4600]
==== Mehrere Eigenschaften löschen

Gehe wie im Folgenden beschrieben vor, um mehrere Eigenschaft gleichzeitig unwiderruflich zu löschen.

[.instruction]
Mehrere Eigenschaften löschen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Führe die Suche aus. +
→ Wähle ggf. Filter, um die Ergebnisse einzugrenzen.
. Aktiviere die Eigenschaften, die du löschen möchtest.
. Klicke auf *Löschen* (icon:minus-square[role="red"]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicke auf *Löschen*. +
→ Die gewählten Eigenschaften werden gelöscht und aus der Übersicht entfernt.

[#4700]
=== Eigenschaften gruppieren

Erstelle Eigenschaftsgruppen, um mehrere Eigenschaften zusammenzufassen. Gehe wie im Folgenden beschrieben vor, um eine Eigenschaftsgruppe zu erstellen.

[.instruction]
Eigenschaftsgruppe erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen*.
. Klicke auf *Eigenschaftsgruppe hinzufügen*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-eigenschaftsgruppe-erstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Eigenschaftsgruppe wird erstellt.

[[tabelle-eigenschaftsgruppe-erstellen]]
.Neue Eigenschaftsgruppe erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
|Name für die Eigenschaftsgruppe eingeben. +
*_Hinweis:_* Standardmäßig wird der Name für die Systemsprache angezeigt. Nachdem die Eigenschaftsgruppe erstellt wurde, kann der Name in englischer Sprache gespeichert werden. Weitere Sprachen sind in Planung.

|*Beschreibung*
|Beschreibung für die Eigenschaftsgruppe eingeben. +
*_Hinweis:_* Standardmäßig wird die Beschreibung für die Systemsprache angezeigt. Nachdem die Eigenschaftsgruppe erstellt wurde, kann die Beschreibung in englischer Sprache gespeichert werden. Weitere Sprachen sind in Planung.

|*Position*
|Positionsnummer für die Eigenschaftsgruppe eingeben. Standardmäßig wird aufsteigend nach Positionsnummer sortiert. +
*_Tipp:_* Positionsnummern in 10er-Schritten vergeben, damit neue Eigenschaftsgruppen dazwischen eingefügt werden können.

|*Gruppentyp*
|Gruppentyp aus der Dropdown-Liste wählen. Die Option steuert, wie Eigenschaften des Typs *Empty* im Bestellvorgang angezeigt werden. +
*Keine* = Eigenschaften werden standardmäßig nicht gruppiert. +
*Select* = Eine der gruppierten Eigenschaften ist per Dropdown-Liste wählbar. +
*Multiselect* = Mehrere Eigenschaften sind wählbar. +
*_Hinweis:_* Option greift nur für Eigenschaften des Typs *Kein*, für die die Option *Bestellvorgang* aktiviert ist.

|*Aufpreistyp*
|Aufpreistyp aus der Dropdown-Liste wählen. +
*Pauschal* = Aufpreis wird als pauschaler Betrag eingegeben. +
*Prozent* = Aufpreis wird als Prozentwert eingegeben.
|====

[#4800]
==== Eigenschaft einer Gruppe zuordnen

Gehe wie im Folgenden beschrieben vor, um eine oder mehrere Eigenschaft einer Eigenschaftsgruppe zuzuordnen.

[.instruction]
Eigenschaft einer Gruppe zuordnen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Führe die Suche aus. +
→ Wähle ggf. Filter, um die Ergebnisse einzugrenzen.
. Aktiviere die Eigenschaften, die du der Gruppe zuordnen möchtest.
. Klicke auf *Eigenschaftsgruppe zuordnen*. +
→ Eine Dropdown-Liste der Eigenschaftsgruppen wird angezeigt.
. Wähle die Eigenschaftsgruppe aus der Dropdown-Liste.
. Klicke auf *Gruppenfunktion*. +
→ Die gewählten Eigenschaften werden der Eigenschaftsgruppe zugeordnet.

[#4850]
==== Mehrere Sprachen zu einer Eigenschaftsgruppe hinzufügen

Zu Eigenschaftsgruppen können mehrere Sprachen hinzugefügt werden.

[.instruction]
Mehrere Sprachen zu einer Eigenschaftsgruppe hinzufügen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen*. +
→ Die Übersicht wird geöffnet.
. Wähle eine Eigenschaftsgruppe. +
→ Die Übersicht wird geöffnet und alle zur Auswahl vorhandenen Sprachen werden angezeigt.
. Wähle eine Sprache.
. Gib den Namen der Sprache ein.
. Gib die Beschreibung für die Sprache ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Sprache wurde zu der Eigenschaftsgruppe hinzugefügt.

[#4900]
==== Eigenschaftsgruppen löschen

Du kannst entweder eine Eigenschaftsgruppe oder mehrere Eigenschaftsgruppen gleichzeitig löschen. Die Eigenschaften, die den Gruppen zugeordnet sind, bleiben beim Löschen von Eigenschaftsgruppen erhalten.

===== Eine Eigenschaftsgruppe löschen

Gehe wie im Folgenden beschrieben vor, um eine Eigenschaftsgruppe unwiderruflich zu löschen.

[.instruction]
Eine Eigenschaftsgruppe löschen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen*.
. Führe die Suche aus. +
→ Wähle ggf. Filter, um die Ergebnisse einzugrenzen.
. Klicke auf die Eigenschaftsgruppe. +
→ Die Eigenschaftsgruppe wird geöffnet.
. Klicke auf *Gruppe löschen* (icon:minus-square[role="red"]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicke auf *Löschen*. +
→ Die Eigenschaftsgruppe wird gelöscht und aus der Übersicht entfernt. +
*_Hinweis:_* Wenn du eine Eigenschaftsgruppe löschst, werden die Eigenschaften, die der Gruppe zugeordnet sind, nicht gelöscht.

[#5000]
===== Mehrere Eigenschaftsgruppen löschen

Gehe wie im Folgenden beschrieben vor, um mehrere Eigenschaftsgruppen gleichzeitig unwiderruflich zu löschen.

[.instruction]
Mehrere Eigenschaftsgruppen löschen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen*.
. Führe die Suche aus. +
→ Wähle ggf. Filter, um die Ergebnisse einzugrenzen.
. Aktiviere die Eigenschaftsgruppen, die du löschen möchtest.
. Klicke auf *Löschen* (icon:minus-square[role="red"]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicke auf *Löschen*. +
→ Die gewählten Eigenschaftsgruppen werden gelöscht und aus der Übersicht entfernt. +
*_Hinweis:_* Wenn du eine Eigenschaftsgruppe löschst, werden die Eigenschaften, die der Gruppe zugeordnet sind, nicht gelöscht.

[#1705]
== Datensätze über die Schnellsuche finden

Verwende die Schnellsuche, um alle Informationen eines Kontakts oder eines Gastkontos auf einen Blick zu erhalten. Dazu gehören neben der Rechnungsadresse, den Stammdaten und allgemeinen Informationen wie z.B. Typ, offene Forderungen und dem Datum des letzten Auftrags auch die Aufträge, weitere Adressen, Events, Tickets und Nachrichten.

[.instruction]
Datensätze über die Schnellsuche finden:

. Öffne das Menü *CRM » Schnellsuche*.
. Wähle mindestens einen Filter. Beachte dazu die Erläuterungen in <<tabelle-filter-schnellsuche>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Datensätze, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Datensatzes. +
→ Die Übersicht mit den Bereichen *Zugeordnete Tags*, *Rechnungsadresse*, *Stammdaten* und *Info* wird geöffnet.
. Klicke in die Zeile *Aufträge*, um die Aufträge anzuzeigen. +
→ Mit einem Klick in die Zeile des Auftrags gelangst du direkt in die Übersicht des Auftrags im Menü *Aufträge » Aufträge bearbeiten*.
. Klicke in die Zeile *Adressen*, um weitere Adressen anzuzeigen. +
→ Mit einem Klick in die Zeile der Adresse gelangst du direkt in die Adressübersicht und können dort Änderungen vornehmen.
. Klicke in die Zeile *Events*, um die Events anzuzeigen. +
→ Die Stoppuhr oben rechts startet automatisch, sobald der Datensatz geöffnet wird. Klicke auf *Event hinzufügen*, um diese Zeit zu speichern. +
*_Hinweis:_* Events sind nur für Kontaktdatensätze verfügbar, nicht für Gastzugänge.
. Klicke in die Zeile *Tickets*, um die Tickets anzuzeigen. +
→ Mit einem Klick in die Zeile des Tickets gelangst du direkt in das Ticket im Menü *CRM » Ticketsystem*.
. Klicke in die Zeile *Messenger*, um die Nachrichten anzuzeigen.

[[tabelle-filter-schnellsuche]]
.Filter in der Schnellsuche
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Zeigt die gefundenen Datensätze, die den Suchkriterien entsprechen, an. Mindestens ein Filter muss gewählt sein.

|*Zurücksetzen*
|Mit einem Klick auf *Zurücksetzen* (icon:undo[role="orange"]) werden die  eingestellten Filterkriterien zurückgesetzt.

|*ID*
|Jeder Kontakt erhält automatisch eine fortlaufende und einzigartige ID. Dies ist unabhängig davon, ob der Kontakt manuell oder automatisch erstellt wurde. 2 Kontakte haben somit nie die gleiche ID. Die ID entspricht immer einer echten Zahl. Ungültig sind z.B. "00521" oder "ADF8354". +
*_Hinweis:_* Mit einem Klick auf den Pfeil neben der ID in der Übersicht kannst du die gefundenen Datensätze aufsteigend oder absteigend nach ihrer ID anzeigen.

|*Name*
|Vorname und/oder Nachname oder Firmenname eingeben, um den oder die Kontakte mit diesem Namen anzuzeigen. +
*_Hinweis:_* Mit einem Klick auf den Pfeil in den Spalten *Vorname* und *Nachname* in der Übersicht kannst du die gefundenen Datensätze alphabetisch sortiert anzeigen.

|*Kontaktdaten*
|In diesem Feld kann nach dem Namen, der Adresse, der Firma, der Kundennummer und dem eBay-Namen gesucht werden. +
*_Hinweis:_* Um nach dem eBay-Namen zu suchen, zuerst den Parameter *ebay:* gefolgt vom gesuchten eBay-Namen eingeben.

|*Anschrift*
|Straßenname und/oder Hausnummer eingeben, der im Kontakt gespeichert ist. Es ist möglich, nur nach Teilen des Straßennamens und Teilen der Hausnummer zu suchen.

|*PLZ*
|Postleitzahl, die im Kontakt gespeichert sind, eingeben. Es wird auch nach Postleitzahlen, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen der Postleitzahl zu suchen.

|*Ort*
|Ort, der im Kontakt gespeichert ist, eingeben. Es wird auch nach Orten, die in den Adressdatensätzen des Kontakts gespeichert sind, gesucht. Es ist möglich, nur nach Teilen des Ortsnamens zu suchen.

|*E-Mail*
|Komplette E-Mail-Adresse eingeben, um den Kontakt mit dieser E-Mail-Adresse anzuzeigen.

|*Telefon*
|Telefonnummer eingeben, um nur den Kontakt mit dieser Telefonnummer anzuzeigen. Es kann auch nach Teilen der Telefonnummer gesucht werden. Mindestens 3 Ziffern eingeben.

|*Land*
|Land wählen, um nur Kontakte aus diesem Land anzuzeigen. Das Land ist in den Kontaktdaten gespeichert.

|*Eigner*
|Eigner wählen, um nur Kontakte anzuzeigen, die mit diesem Eigner verknüpft sind. Der Eigner muss in den Kontaktdaten gespeichert sein. +
*_Wichtig:_* In der Dropdown-Liste werden nur Benutzer angezeigt, bei denen im Benutzerkonto im Tab *Eigner* die Option *Kunde* aktiviert ist.

|*Typ*
|Typ wählen, um nur Kontakte mit diesem Typ anzuzeigen.

|*Kundenklasse*
|Kundenklasse wählen, um nur Kontakte mit dieser Kundenklasse anzuzeigen.

|*Bewertung*
|Bewertung wählen, um nur Kontakte mit dieser Bewertung anzuzeigen. 5 gelbe Sterne stehen für die beste und 5 rote Sterne für die schlechteste Bewertung.

|*Tags*
|Einen oder mehrere Tags wählen, um nur Kontakte mit diesen Tags anzuzeigen.

|*Mandant*
|Mandant wählen, um nur Kontakte dieses Mandanten anzuzeigen. Der Mandant ist in den Kontaktdaten gespeichert. +
*_Wichtig:_* Backend-Benutzern stehen nur Mandanten zur Auswahl, für die sie eine Berechtigung haben. Berechtigungen werden im Menü *Einrichtung » Einstellungen » Benutzer » Konten* im Tab <<basics/admin-aufgaben/benutzer-verwalten#90, Berechtigungen>> des Benutzerkontos eingestellt.

|====

[#1705a]
=== Weitere Einstellungsmöglichkeiten in der Schnellsuche

Wenn du einen Datensatz in der Schnellsuche öffnest, siehst du in der ersten Zeile des Datensatzes weitere Einstellungsmöglichkeiten, die in <<tabelle-einstellungen-schnellsuche>> erläutert werden.

[[tabelle-einstellungen-schnellsuche]]
.Einstellungen in der Schnellsuche
[cols="2,1,6"]
|====
|Einstellung |Icon |Erläuterung

|*Kontakt-ID*
|
|Öffnet den Kontaktdatensatz im Menü *CRM » Kontakte*. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um einen Gastzugang handelt, ist dieses Feld nicht vorhanden.

|*Aufträge*
|
|Öffnet das Menü *Aufträge » Aufträge bearbeiten*. Als Filter ist die ID des Kontakts automatisch gewählt. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um einen Gastzugang handelt, ist dieses Feld ausgegraut.

|*Neuer Auftrag*
|icon:plus-square[role="green"]
|Erstellt einen neuen Auftrag im Menü *Aufträge » Aufträge bearbeiten*. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um einen Gastzugang handelt, ist dieses Feld ausgegraut.

|*Tickets*
|
|Öffnet das Menü *CRM » Ticketsystem*. Als Filter ist die ID des Kontakts automatisch gewählt. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um einen Gastzugang handelt, ist dieses Feld ausgegraut.

|*Neues Ticket*
|icon:plus-square[role="green"]
|Erstellt ein neues Ticket im Menü *CRM » Ticketsystem*. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um einen Gastzugang handelt, ist dieses Feld ausgegraut.

|*Messenger*
|
|Öffnet den Bereich *Messenger*. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um einen Gastzugang handelt, ist dieses Feld ausgegraut.

|*Neue Nachricht*
|icon:plus-square[role="green"]
|Erstellt eine neue Nachricht. +
*_Hinweis:_* Wenn es sich bei dem Datensatz um einen Gastzugang handelt, ist dieses Feld ausgegraut.

|*Alle Daten dieses Kontakts herunterladen*
|icon:download[role="purple"]
|Lädt alle gespeicherten Daten zu diesem Datensatz herunter. +
Weitere Informationen findest du im Kapitel <<crm/kontakte-verwalten#1706, Alle Daten zu einem Kontakt herunterladen>>.

|*Newsletter Opt-In E-Mail senden*
|icon:envelope-o[role="purple"]
|Versendet die E-Mail zum Newsletter-Opt-In bzw. die Bestätigung zum Newsletter-Opt-In an den Kunden. +
*_Hinweis:_* Wenn der Kunde noch nicht für den Newsletter angemeldet ist, erhält er die automatische E-Mail für Newsletter-Opt-In. Wenn der Kunde bereits für den Newsletter angemeldet ist, aber noch nicht bestätigt hat, erhält er die Bestätigung zum Newsletter-Opt-In.

|*Datensatz anonymisieren*
|icon:user-secret[]
|Anonymisiert den Datensatz. Das Anonymisieren der Daten ist nur bei einem Kontaktdatensatz möglich, nicht bei einem Gastzugang. +
Weitere Informationen findest du im Kapitel <<crm/kontakte-verwalten#1707, Datensatz anonymisieren>>.

|*Gast in Kontakt umwandeln*
|icon:exchange[role="yellow-background"]
|Wandelt den Gastzugang in einen regulären Kontaktdatensatz um. Im neu erstellten Kontaktdatensatz wird dann im Bereich *Historie* der Eintrag *Umgewandelt von* sowie der Benutzername hinzugefügt. +
Weitere Informationen findest du im Kapitel <<crm/kontakte-verwalten#1705b, Gastzugang in Kontaktdatensatz umwandeln>>.

|*Daten aktualisieren*
|icon:undo[]
|Aktualisiert die Daten in diesem Datensatz.

|====

[#1705b]
=== Gastzugang in Kontaktdatensatz umwandeln

Im Menü *CRM » Schnellsuche* kannst du mit einem Klick einen Datensatz von einem Gastzugang in einen regulären Zugang umwandeln.

Bei Gastbestellung über den Ceres-Webshop besteht der Gastzugang lediglich aus der Adresse und dem zugehörigen Auftrag. Wenn in der Adresse zusätzlich ein Firmenname enthalten ist, wird beim Umwandeln des Datensatzes auch der Firmendatensatz erstellt.

[.instruction]
Gastzugang in Kontaktdatensatz umwandeln:

. Öffne das Menü *CRM » Schnellsuche*.
. Wähle mindestens einen Filter. Beachte dazu die Erläuterungen in <<tabelle-filter-schnellsuche>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Datensätze, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Datensatzes. +
→ Der Datensatz wird geöffnet.
. Klicke in der Kopfzeile auf *Gast in Kontakt umwandeln* (icon:exchange[role="yellow-background"]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt. +
. Wenn du DGSVO-konform gearbeitet hast, klicke auf *Umwandeln*. +
→ Der Datensatz wird in einen Kontaktdatensatz umgewandelt und erhält automatisch die nächste freie Kontakt-ID. Im Bereich *Historie* des Kontaktdatensatzes wird der Eintrag *Umgewandelt von* sowie der Benutzername hinzugefügt.

[TIP]
.Callisto-Gastbestellungen vs. Ceres-Gastbestellungen
====
Im Kapitel <<crm/kontakte-verwalten#350, Alter Webshop: Gastzugang in regulären Zugang umwandeln>> ist beschrieben, wie du Callisto-Gastbestellungen in reguläre Zugänge umwandelst. Das Umwandeln von Ceres-Gastbestellungen in reguläre Zugänge ist über den Kontaktdatensatz nicht möglich.

Jedoch kannst du über die Schnellsuche neben Ceres-Gastbestellungen auch Callisto-Gastbestellungen in reguläre Kontaktdatensätze umwandeln.
====

[#1705c]
=== Stoppuhr verwenden

Sobald du im Menü *CRM » Schnellsuche* einen Datensatz öffnest, startet die Stoppuhr in der oberen rechten Ecke. Mit einem Klick auf das Start-/Stop-Symbol hältst du die Uhr an. Mit einem weiteren Klick auf das Start-/Stop-Symbol läuft die Zeit weiter.

Klicke auf *Zurücksetzen* (icon:undo[role="orange"]), um die Zeit auf 0 zu setzen. Die Zeiten der Stoppuhr werden automatisch in den Kontaktdatensatz in den Bereich *Events* übertragen. In diesem Bereich kannst du weitere Einstellungen vornehmen und den Typ wählen sowie einen Infotext eingeben.

Die in der Schnellsuche gespeicherten Daten sind dann ebenfalls im Menü *CRM » Kontakte* im Bereich *Events* des Kontaktdatensatzes verfügbar.

[#1706]
== Alle Daten zu einem Kontakt oder Gastzugang herunterladen

Im Menü *CRM » Schnellsuche* kannst du mit einem Klick alle zu einem Kontakt oder zu einer Adresse gehörigen Daten (Gastzugang) als ZIP-Datei herunterladen.

[.instruction]
Alle Daten zu einem Kontakt oder Gastzugang herunterladen:

. Öffne das Menü *CRM » Schnellsuche*.
. Wähle mindestens einen Filter.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Datensätze, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Datensatzes. +
→ Die Übersicht mit den Bereichen *Zugeordnete Tags*, *Rechnungsadresse*, *Stammdaten* und *Info* wird geöffnet.
. Klicke in der oberen Zeile auf *Alle Daten dieses Kontakts herunterladen* (icon:download[role="purple"]). +
→ Ein Dialogfenster erscheint. Lege den Speicherort für die ZIP-Datei auf deinem Computer fest.

Weitere Informationen zu der Download-Datei findest du in diesem link:https://forum.plentymarkets.com/t/dsgvo-button-fuer-den-datenexport-zu-einem-kunden-integriert/486915[Changelog^]-Beitrag im plentymarkets Forum.

[#1707]
== Datensatz anonymisieren

Daten zu einem Kontakt können mit einem Klick gelöscht oder so unkenntlich gemacht werden, dass kein Bezug mehr zu dieser Person hergestellt werden kann.

Das Anonymisieren der Daten ist nur bei einem Kontaktdatensatz möglich, nicht bei einem Gastzugang.

[.instruction]
Datensatz anonymisieren:

. Öffne das Menü *CRM » Schnellsuche*.
. Wähle mindestens einen Filter.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Übersicht des Kontakts wird geöffnet.
. Klicke in der oberen Zeile auf *Datensatz anonymisieren* (icon:user-secret[]). +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Gib die ID des Kontakts, den du anonymisieren möchten, ein.
. Klicke auf *Anonymisieren*. +
→ Der Datensatz wird anonymisiert.

[TIP]
.Welche Daten werden anonymisiert und gelöscht?
====
Mit einem Klick auf *Anonymisieren* werden die folgenden Daten im Datensatz des Kontakts anonymisiert und gelöscht:

* Daten werden anonymisiert: Vorname, Nachname
* Daten werden gelöscht: Kontaktoptionen, Adressoptionen, Adressen, Adressverknüpfungen, Auftragsverknüpfungen, Verknüpfungen zu einer Firma, Bankdaten
====

[#5100]
== Änderungshistorie für Kontaktdaten anzeigen

Über die Änderungshistorie kannst du nachverfolgen, welcher Benutzer in deinem System zu welchem Zeitpunkt welche Änderung an einem Kontaktdatensatz vorgenommen hat. Außerdem wird angezeigt, wenn dein Kontakt selbst Änderungen in seinem Mein Konto-Bereich vorgenommen hat.  

[.instruction]
Änderungshistorie für Kontaktdaten anzeigen:

. Öffne das Menü *Daten » Historie*.
. Wähle eine Option aus der Dropdown-Liste *Referenztyp*.
. Gib die Referenz-ID, z.B. die ID des Kontakts, ein.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Eine Liste der Änderungen mit alten und neuen Werten, dem Änderungsdatum sowie der Name und die ID des Benutzers, der die Änderung vorgenommen hat, wird angezeigt.

Weitere Informationen findest du auf der Handbuchseite <<daten/aenderungshistorie#, Änderungshistorie>>.

[#5200]
== Offene Posten verwalten

Im Menü *CRM » OP-Liste* erhältst du eine Übersicht über Kunden mit unbezahlten Aufträgen. OP steht für offene Posten. Die Liste enthält die Anzahl der offenen Posten eines Kunden sowie die Höhe der Forderung, die sich aus den offenen Posten ergibt.

Die Liste der offenen Posten wird einmal täglich automatisch aktualisiert. Forderungen werden daher teilweise erst am nächsten Tag in der Liste angezeigt. Du hast aber auch die Möglichkeit, die <<crm/kontakte-verwalten#5400, Liste manuell zu aktualisieren>>. Um alle offenen Posten anzuzeigen, gehe wie im Folgenden beschrieben vor.

[TIP]
.Berechtigung für Benutzer mit *Backend*-Zugang vergeben
====
Damit für Benutzer mit dem Zugang *Backend* die OP-Liste sichtbar ist, musst du die Option aktivieren. Öffne dazu das Benutzerkonto im Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer* und wähle im Bereich *Menü-Sichtbarkeiten* die Option *CRM > OP-Liste*.
====

[#5210]
=== Offene Posten anzeigen

[.instruction]
Offene Posten anzeigen:

. Öffne das Menü *CRM » OP-Liste*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Alle offenen Posten werden aufgeführt.

Aus der Liste heraus öffnest du den Kunden, indem du in der Spalte *ID* auf die ID klickst. Oder du öffnest eine Liste aller Aufträge des Kunden, in denen noch Posten offen sind, indem du in der Spalte *Aufträge* auf *Aufträge anzeigen* klickst.

[#5300]
=== Offene Posten filtern

Die Liste im Menü *CRM » OP-Liste* lässt sich nach *Typ*, *Land*, *Kundenklasse* und *Kundentyp* filtern. Offene Posten kannst du außerdem nach der Anzahl der *offenen Posten* oder der Höhe der *Forderung* sortieren.

[.instruction]
Offene Posten filtern:

. Öffne das Menü *CRM » OP-Liste*.
. Wähle die Filtereinstellungen.
. Klicke auf *Suchen* (icon:search[role="blue"]), um die gefilterten Ergebnisse anzuzeigen.

[#5400]
=== Offene Posten manuell aktualisieren

Die Liste der offenen Posten wird einmal täglich automatisch aktualisiert. Zwischendurch kannst du die Liste wie im Folgenden beschrieben manuell aktualisieren:

[.instruction]
Offene Posten manuell aktualisieren:

. Öffne das Menü *CRM » OP-Liste*.
. Klicke im Bereich *OP-Liste generieren* auf *Generieren* (icon:cog[]). +
→ Die Liste wird im Hintergrund aktualisiert.
. Klicke auf *Suchen* (icon:search[role="blue"]), um die aktualisierte Liste anzuzeigen.

[#5500]
== USt-IdNr. prüfen

Die Umsatzsteuer-Identifikationsnummer (USt-IdNr.) ist eine exklusive Identifikationsnummer und dient der Kennzeichnung von Umsatzsteuerpflichtigen. Innerhalb der EU wird sie für die Abrechnung der Umsatzsteuer durch die Finanzämter benötigt.

Die Prüfung der USt-IdNr. erlaubt die Verifizierung einer deutschen oder einer ausländischen USt-IdNr. und ist täglich von 5:00 bis 23:00 Uhr verfügbar. Geprüft werden können alle USt-IdNrn. aus Mitgliedsstaaten der EU mit Ausnahme der Slowakei und Lettland (nicht oder nur eingeschränkt möglich). Bei deutschen Ust-IdNrn. wird nur die Gültigkeit geprüft, die Zuordnung zu einer Person wird nicht geprüft. Bei ausländischen USt-IdNrn. wird die Gültigkeit geprüft und es werden die zugehörigen Firmennamen- und Adressdaten zur USt-IdNr. abgefragt und angezeigt.

[#5700]
=== USt-IdNr. im Webshop prüfen

Im Webshop wird die USt-IdNr. automatisch im Bestellvorgang geprüft. Bei nicht gültiger USt-IdNr. kann der Käufer die Bestellung erst abschließen, wenn eine gültige USt-IdNr. eingegeben wird oder der Eintrag entfernt wird.

[#5800]
=== Prüfungsdaten exportieren

Du kannst eine Liste aller Prüfungsdaten oder der Daten für den aktuellen Monat exportieren. Details zum Export der USt-ID-Prüfungsdaten findest du im Themenbereich <<daten#, Daten>>.

[#5900]
== Kontaktdaten exportieren, importieren und aktualisieren

Exportiere die Daten deiner Kontakte über das Menü *Daten » Elastischer Export*. Voraussetzung dafür ist, dass du die Plugins link:https://marketplace.plentymarkets.com/plugins/integration/formatdesigner_6483[FormatDesigner] und link:https://marketplace.plentymarkets.com/plugins/markets/ElasticExport_4763[Elastischer Export^] installierst und bereitstellst. Beide Plugins sind im link:https://marketplace.plentymarkets.com/[plentyMarketplace^] verfügbar. +

Das Format für den Export erstellst du im Menü *Daten » FormatDesigner*. Einen neuen Export erstellst du im Menü *Daten » Elastischer Export*. Dort wählst du das über den FormatDesigner erstellte Format aus der Dropdown-Liste und exportierst die Daten anschließend in eine CSV-Datei.

Dir stehen zahlreiche Filteroptionen für den Export zur Verfügung. Exportiere z.B. nur Kontakte, die du mit 3 Sternen bewertet hast, oder nur Kontakte, die einem bestimmten Eigner zugeordnet sind.

Importiere oder aktualisiere die Daten deiner Kontakte inklusive Adressoptionen, Kontaktoptionen und Firmendaten über ElasticSync. Weitere Informationen findest du auf der Handbuchseite <<daten/daten-importieren/ElasticSync#, Daten mit ElasticSync importieren>>.
