= Leads und Opportunities
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:description: Erfahre, wie du Leads und Opportunities in plentymarkets verwaltest.
:position: 12
:url: crm/leads-und-opportunities
:id: PJ9TZBK
:author: team-crm


In Zeiten, in denen sich Online-Märkte festigen, werden Kundenbindung und Kundenbeziehung immer wichtigere Faktoren im Online-Handel. Unternehmen, die in diesem Markt wachsen möchten, müssen ihre Kund:innen begeistern – und das vom ersten Kontakt an.

Neben der Verwaltung von Kundendaten umfasst das CRM-Modul von plentymarkets auf Basis der MyView

* eine Benutzeroberfläche zum Erfassen und Verwalten von Interessenten und somit potentiellen Neukunden, den sogenannten _Leads_

* sowie eine Benutzeroberfläche zum Erfassen und Verwalten von Verkaufschancen, also zum Verkauf stehende Services oder Dienstleistungen, den sogenannten _Opportunities_.

Mithilfe dieser Benutzeroberflächen steuerst du sämtliche vertriebliche Kundenprozesse entlang der kompletten Wertschöpfungskette des Customer Lifecycle.

[#leads-verwalten]
== Leads verwalten

Im Menü *CRM » Leads* kannst du auf einen Blick alle potentiellen Kund:innen sowie deren Status und die aktuelle Performance einsehen. Selbstverständlich hast du die Möglichkeit, die Liste aller erfassten Leads nach bestimmten Kriterien zu filtern. Du kannst außerdem die Quelle sehen, über die du auf einen Lead gestoßen bist. Klassischerweise sind dies zum Beispiel die Unternehmens-Website, telefonische Anfragen, Besuche auf Messen und Veranstaltungen etc.

// aktuelle Performance? wie?

[#vorbereitende-einstellungen]
=== Vorbereitende Einstellungen vornehmen

Damit du Leads optimal nutzen kannst, sind einige vorbereitende Einstellungen nötig, die im Folgenden beschrieben werden.

[#rechte-vergeben]
==== Rechte für Backend-Benutzer:innen vergeben

* CRM > Kontakt > Leads > Anzeigen
** Backend-Benutzer:innen können das Menü *CRM » Leads* sehen

* CRM > Kontakt > Leads > Statushistorie > Erstellen
** Backend-Benutzer:innen können den Status anpassen, z.B. von _Qualifiziert_ in _Umgewandelt_

[#eigenschaften]
==== Eigenschaften für Leads erstellen bzw. vorhandene Eigenschaften für Leads freigeben

Im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* gibt es im Bereich *Optionen* einer vorhandenen Kontakt-Eigenschaft den Bereich *Leads*. Diesen Bereich musst du beim Erstellen von neuen Eigenschaften vom Typ *Kontakt* aktivieren oder nachträglich bei bereits vorhandenen Eigenschaften aktivieren.

// Verlinkung auf Handbuchseite "Eigenschaften"

[#lead-erstellen]
=== Lead erstellen

Der Erstkontakt mit einem Lead ist hergestellt und du möchtest die Daten des Leads in deinem plentymarkets System speichern? Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Lead erstellen:

. Öffne das Menü *CRM » Leads*.
. Klicke auf *+ Neu*.
. Gib die Daten des Leads ein. Beachte die Erläuterungen in <<#table-create-lead>>. +
→ Der Lead wird standardmäßig der im System eingeloggten Person zugewiesen.
*_Hinweis:_* Der Bereich *Verlauf* kann nicht manuell angepasst werden.
. *Speichere* die Einstellungen.


[[table-create-lead]]
.Lead erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+| *Statusleiste*
| *Nicht qualifiziert*
|

| *Qualifiziert*
|

| *In Arbeit*
|

| *Umgewandelt*
|Der Lead wurde in einen Kontakt umgewandelt. Die ID bleibt bestehen.

| *Verloren*
|Der Lead ist verloren. Dies kann z.B. fehlendes Interesse des Leads sein.


2+| *Allgemein*

| *Anrede*
|Wähle die Anrede des Leads aus der Dropdown-Liste.

| *Vorname* / *Nachname*
|Wie lautet der Name des Leads? +
*_Hinweis:_* Der Nachname ist ein Pflichtfeld.


| *Bewertung*
|Wähle eine Bewertung für den Lead. +
5 gelbe Sterne stehen für die beste und 5 rote Sterne für die schlechteste Bewertung.

| *Herkunft*
|Wähle die Herkunft des Leads aus der Dropdown-Liste.

| *Firma*
|Gib den Namen der Firma des Leads ein. +
*_Hinweis:_* Der Firmenname ist ein Pflichtfeld.

| *Status*
|Wähle einen Status aus der Dropdown-Liste. +
*_Hinweis:_* Standardmäßig ist hier der Status *Nicht qualifiziert* gewählt.

| *Titel*
|In welcher Position arbeitet der Lead? Ist er oder sie z.B. CEO oder Marketing Manager?

// ist hier die Job-Position gemeint?

| *Eigner*
|Wähle einen Eigner aus der Dropdown-Liste.

2+| *Eigenschaften*

|
|


2+| *Optionen* +
Standardmäßig werden hier die Optionen *Telefon privat* und *E-Mail privat* bereits angezeigt. Mit einem Klick auf *+ Kontaktoption hinzufügen* kannst du weitere Kontaktoptionen hinzufügen. Mit einem Klick auf *Kontaktoption löschen* (icon:trash[set=plenty]) löschst du die Kontaktoption wieder.

2+| *Adresse*

| *Adresse 1 (Straße)*
|

| *Adresse 2 (Hausnummer)*
|

| *Adresse 3 (Adresszusatz)*
|

| *Adresse 4 (Frei)*
|

| *Ort*
|

| *Postleitzahl*
|

| *Land*
|

| *Region/Bezirk*
|

|====

[#lead-suchen]
=== Lead suchen

Um bestimmte Leads zu suchen, gibst du die dir bekannten Suchbegriffe in die Filter ein oder wählst die Einstellungen der Dropdown-Listen. Es ist auch möglich, mehrere Suchbegriffe gleichzeitig in die Suchfelder einzugeben. Dies ermöglicht eine schnellere und genauere Suche.

[.instruction]
Lead suchen:

. Öffne das Menü *CRM » Leads*.
. Klicke auf icon:filter[role="darkgrey"].
. Wähle deine Filter. Beachte die Erläuterungen in <<#table-search-lead>>.
. Klicke auf *Suchen*. +
→ Die Leads, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

[[table-search-lead]]
.Lead suchen
[cols="1,3"]
|====
|Filter |Erläuterung

| *Kontakt-ID*
|

| *Name*
|

| *Kontaktdaten*
|

| *Status*
|

| *Adresse*
|

| *PLZ*
|

| *Ort*
|

| *E-Mail*
|

| *Telefon*
|

| *Tags*
|

| *Land*
|

| *Eigner*
|

| *Typ*
|

| *Kundenklasse*
|

| *Bewertung*
|



|====


[discrete]
=== Übersicht aller Leads

Du entscheidest, welche Spalten du in der Übersicht anzeigen lassen möchtest. Klicke dazu oben rechts auf *Spalten konfigurieren* (icon:cog[role="darkGrey"]), wähle die gewünschten Spalten und klicke auf *Bestätigen*. Die folgenden Spalten sind verfügbar:

* ID
** Diese ID bleibt bestehen, wenn der Lead später in einen Kontakt umgewandelt wird.
* Status
* Firma
* Vorname
* Nachname
* Titel
* E-Mail
* Telefon
* Tage in Status
* Eigner
* Erstellt am


[#lead-bearbeiten]
=== Lead bearbeiten

Je nachdem, über welche Berechtigungen du verfügst, kannst du den Lead bearbeiten.

Suche den Lead anhand der <<#lead-suchen, Filtereinstellungen>>. Öffne den Lead durch einen Klick in die Zeile des Leads, um dessen Daten anzupassen oder weitere Daten zu ergänzen.

[.instruction]
Lead bearbeiten:

. Öffne das Menü *CRM » Leads*.
. Suche den Lead anhand der Filtereinstellungen wie im Kapitel <<#lead-suchen, Lead suchen>> beschrieben. +
→ Die Leads, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Leads. +
→ Die Detailansicht des Leads wird geöffnet.
. Nimm die gewünschten Änderungen vor. Beachte dazu die Erläuterungen in <<#table-create-lead>>.
. *Speichere* die Einstellungen.


[#lead-umwandeln]
=== Lead in Kontakt umwandeln

TEXT

[#historie-einsehen]
=== Historie einsehen

Beim Erstellen eines Leads wird die Historie des Leads gespeichert. Die Historie beinhaltet die Namen der Personen, die den Lead erstellt und aktualisiert haben sowie die zugehörigen Datumsangaben. Außerdem wird angezeigt, wie viele Tage sich der Lead im aktuellen Status befindet. Die Daten werden automatisch angepasst und können _nicht_ geändert werden.

[.instruction]
Historie einsehen:

. Öffne das Menü *CRM » Leads*.
. Suche den Lead anhand der Filtereinstellungen wie im Kapitel <<#lead-suchen, Lead suchen>> beschrieben. +
→ Die Leads, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Leads. +
→ Die Detailansicht des Leads wird geöffnet und die Historie wird im unteren Bereich angezeigt.
. Beachte dazu die Erläuterungen in <<#table-lead-history>>.

[[table-lead-history]]
.Historie des Leads
[cols="1,3"]
|====
|Eintrag |Erläuterung

| *Erstellt von*
|Zeigt an, wer den Lead erstellt hat.

| *Erstellt am*
|Zeigt an, wann der Lead erstellt wurde.

| *Aktualisiert von*
|Zeigt an, wer den Lead aktualisiert hat.

| *Aktualisiert am*
|Zeigt an, wann der Lead zuletzt aktualisiert wurde.

| *Tage in Status*
|Zeigt die Anzahl der Tage an, die sich der Lead im aktuellen Status befindet. Der Status wird mit dem Datumswechsel um 0:00 Uhr jeweils um eins erhöht.

|====

[#leads-importieren]
=== Leads importieren

Du hast Daten von Leads zum Beispiel während einer Messe in einer CSV-Datei gesammelt und möchtest diese Daten in plentymarkets importieren? Kein Problem!

Nutze dazu einfach das plentymarkets Import-Tool und den Import-Typ <<daten/daten-importieren/sync-typen/elasticSync-kontakte#, Kontakte, Firmen und Adressen>>.

Wie du einen Import erstellst, ist auf der Handbuchseite <<daten/daten-importieren/ElasticSync#, Import-Tool nutzen>> beschrieben.

[#opportunities-verwalten]
== Opportunities verwalten

Der Kernbereich der Opportunity ist die Darstellung der potenziellen Umsatzgröße dieser Verkaufschance, die wichtig ist für die Priorisierung und Planung innerhalb deines Unternehmens.

Beachte, dass du komplexe Berechnungen für den Forecast über plentyBI vornimmst. Der Forecast im Menü *CRM » Opportunities* gibt lediglich eine grobe Übersicht über den möglichen Wert.

// Verlinkung zu plentyBI einfügen

[#vorbereitende-einstellungen]
=== Vorbereitende Einstellungen vornehmen

Damit du Opportunities optimal nutzen kannst, sind einige vorbereitende Einstellungen nötig, die im Folgenden beschrieben werden.

[#rechte-vergeben]
==== Rechte für Backend-Benutzer:innen vergeben

// welche Rechte benötigt man für die Opportunities?

[#eigenschaften]
==== Eigenschaften für Opportunities erstellen bzw. vorhandene Eigenschaften für Opportunities freigeben

TEXT


[#opportunity-erstellen]
=== Opportunity erstellen

[TIP]
Der Typ der Opportunity kann im Nachhinein nicht mehr geändert werden.

[.instruction]
Opportunity erstellen:

. Öffne das Menü *CRM » Opportunities*.
. Klicke auf *+ Opportunity hinzufügen*.
. Fülle die Felder aus oder wähle die Optionen. Beachte dazu die Erläuterungen in <<#table-create-opportunity>>.
. *Speichere* die Einstellungen.

[[table-create-opportunity]]
.Opportunity erstellen
[cols="1,3"]
|====
|Eintrag |Erläuterung

| *Typ*
|Welchen Typ hat deine Opportunity? Wähle eine Option aus der Dropdown-Liste. +
*_Wichtig:_* Beachte, dass der Typ im Nachhinein _nicht_ mehr angepasst werden kann.

| *Status*
a|Wähle einen Status aus der Dropdown-Liste. Jeder Status ist automatisch mit einer Prozentzahl verknüpft, die nicht geändert werden kann. Diese Zahl spiegelt die Auftragswahrscheinlichkeit wider.

* icon:circle[role="darkgrey"] Kalt 5%
* icon:circle[role="blue"] In Kontakt 10%
* icon:circle[role="blue"] Angebot gesendet 25%
* icon:circle[role="blue"] Verhandlung 50%
* icon:circle[role="blue"] Vertrag unterzeichnet 75%
* icon:circle[role="green"] Live 100%
* icon:circle[role="red"] Geschlossen 0%

*_Hinweis:_* Wenn eine Opportunity verloren geht, ändere den Status in *Geschlossen*. Wähle aus der Dropdown-Liste einen Grund, warum die Opportunity verloren gegangen ist.

| *Kontakt*
|Mit welchem Kontakt möchtest du die Opportunity verknüpfen?
Gib die ID des Kontakts ein.

2+| *Historie*

|
|

2+| *Eigenschaften*

|
|

2+| *Werte*

| *Gesamtgebühr*
a| Die Gesamtgebühr setzt sich aus den folgenden 4 Gebühren zusammen, die weiter unten näher erläutert werden:

* Servicegebühr
* Einrichtungsgebühr
* Lizenzgebühr x 12 Monate
* Transaktionsgebühr x 12 Monate

| *Servicegebühr*
|Die Servicegebühr wird einmalig berechnet und ist _keine_ wiederkehrende Gebühr.

| *Einrichtungsgebühr*
|Die Einrichtungsgebühr wird einmalig berechnet und ist _keine_ wiederkehrende Gebühr.

| *Lizenzgebühr (wiederkehrend)*
|Die Lizenzgebühr ist eine wiederkehrende Gebühr und wird daher mit 12 multipliziert. Das Ergebnis aus dieser Berechnung ist automatisch in der Gesamtgebühr enthalten.

| *Transaktionsgebühr (wiederkehrend)*
|Die Transaktionsgebühr ist eine wiederkehrende Gebühr und wird daher mit 12 multipliziert. Das Ergebnis aus dieser Berechnung ist automatisch in der Gesamtgebühr enthalten.

2+| *Events*

| *Datum Servicegebühr*
|

| *Datum Einrichtungsgebühr*
|

| *Datum Lizenzgebühr*
|

| *Datum Transaktionsgebühr*
|

2+| *Eigner*

| *Eigner*
|Einer Opportunity können mehrere Eigner zugeordnet sein, die jeweils einen Verantwortungsbereich haben. Der Verantwortungsbereich ist abhängig vom gewählten Typ.

| *Verantwortungsbereich*
|

|====


[#opportunity-suchen]
=== Opportunity suchen

Um bestimmte Opportunities zu suchen, gibst du die dir bekannten Suchbegriffe in die Filter ein oder wählst die Einstellungen der Dropdown-Listen. Es ist auch möglich, mehrere Suchbegriffe gleichzeitig in die Suchfelder einzugeben. Dies ermöglicht eine schnellere und genauere Suche.

Die folgenden Filter sind für Opportunities verfügbar:

* Kontakt
* Firma
* Status
* Beschreibung
* Eigner


Die folgenden Phasen sind für Opportunities vorhanden:

// Phase ist nicht das richtige Wort

* icon:circle[role="darkgrey"] Kalt 5%
* icon:circle[role="blue"] In Kontakt 10%
* icon:circle[role="blue"] Angebot gesendet 25%
* icon:circle[role="blue"] Verhandlung 50%
* icon:circle[role="blue"] Vertrag unterzeichnet 75%
* icon:circle[role="green"] Live 100%
* icon:circle[role="red"] Geschlossen 0%
