= Messenger (Testphase)
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:description: Erfahre, wie du den Messenger in plentymarkets für den E-Mail-Versand und E-Mail-Empfang nutzt.
:position: 480
:url: crm/messenger-testphase
:id: 7Z6FCLK
:author: team-crm

Im Menü *CRM » Messenger (Testphase)* verwaltest du sowohl die externe Kommunikation mit deinen Kund:innen in Form von E-Mails als auch die interne Kommunikation. Wenn du Nachrichten zum Beispiel flüsterst sind diese Nachrichten nur in deinem plentymarkets System sichtbar und können von deinen Kontakten _nicht_ eingesehen werden. 

// TODO: Einleitung ergänzen

Das Menü *CRM » Messenger (Testphase)* ist wie folgt aufgebaut:

// TODO: farblich markierten Screenshot einfügen.

* *Navigation*: Hier navigierst du durch die einzelnen Bereiche des Menüs. Der aktuell ausgewählte Bereich (blauer Hintergrund) wird im Hauptfenster rechts angezeigt. Klicke auf icon:bars[], um die Navigationsleiste ein- und auszublenden.
* *Toolbar*: Hier kannst du nach <<#nachricht-suchen, Nachrichten suchen>>, die <<#spalten-konfigurieren, Spalten in der Übersicht anpassen>>, die Ergebnisse, die du pro Seite angezeigt haben möchtest, einstellen, und durch die Seiten mit den Nachrichten klicken.
* *Hauptfenster*: Hier wird der aktuell geöffnete Bereich angezeigt. +
** *Übersicht*: Wenn du eine Suche ausführst, siehst du die Ergebnisse in einer Übersicht. Die Übersicht liefert auf einen Blick Informationen zu den gefundenen Nachrichten. Zum Beispiel siehst du die E-Mail-Adressen der Absender:innen, den Betreff, das Empfangsdatum der E-Mail, die zugeordneten Tags und anhand des Symbols icon:attach_file[set=material], ob die E-Mail einen Anhang hat. +
** *Detailansicht*: Wenn du eine Nachricht öffnest, werden die Details unterhalb des Hauptfensters sichtbar. Die Detailansicht einer Nachricht ist unterteilt in den Nachrichtenverlauf und den Editor, in dem du deine Antwort verfassen kannst.

[discrete]
== Neue Features

[.collapseBox]
.Neue Features im Vergleich zum "alten" Messenger
--
Du findest die folgenden Neuerungen im neuen Messenger, die es vorher im "alten" Messenger nicht gab:

* E-Mails von deinen Kund:innen empfangen
* E-Mails an deine Kund:innen senden
--

[#vorbereitende-einstellungen]
== Vorbereitende Einstellungen

Wenn Benutzer:innen vom Typ *Backend* mit dem Messenger arbeiten sollen, muss eine Person mit *Admin*-Zugang zunächst Rechte für diese Benutzer:innen vergeben. Außerdem musst du Tags erstellen, damit diese für den Messenger zur Verfügung stehen und auch für die Tags bestimmte Rechte vergeben.

[#benutzerrechte-backend-benutzer]
=== Rechte für Backend-Benutzer:innen vergeben

:rights-purpose: Nachrichten im Messenger sehen und erstellen
:right-one: pass:quotes[*CRM > Nachricht > Anzeigen*]
:right-two: pass:quotes[*CRM > Nachricht > Erstellen*]
:right-three: pass:quotes[*Kommentare > Anzeigen*]
:right-four: pass:quotes[*Kommentare > Erstellen*]
:right-five: pass:quotes[*Einrichtung > Eigenschaft > Anzeigen*]
:right-six: pass:quotes[*Einrichtung > Eigenschaft > Erstellen*]

include::../_includes/textblocks/instructions/rechte.adoc[]

[#tags-messenger]
=== Tags für den Messenger erstellen

Du hast die Möglichkeit, den Nachrichten im Messenger Tags zuzuordnen und nach diesen auch in der Übersicht zu filtern. Tags sind Schlagworte, die dir das Gruppieren von Nachrichten leichter machen.

Welche Benutzer:innenrechte notwendig sind und wie du Tags erstellst, ist nachfolgend beschrieben.

[#rechte-tags]
==== Rechte für Backend-Benutzer:innen vergeben

include::../_includes/textblocks/instructions/tags-rights.adoc[]

[#tags-erstellen]
==== Tags erstellen

include::../_includes/textblocks/instructions/tags-creation.adoc[]
[TIP]
Wenn du Nachrichten erstellen möchtest, die über den Messenger _kostenpflichtig_ abgerechnet werden sollen, erstelle nach dem selben Schema Tags für den Bereich *Nachrichten (kostenpflichtig)*. Diese Tags musst du dann der <<#nachricht-erstellen, Nachricht>> hinzufügen.

// TODO: Begriff "Nachricht" vs. "E-Mail" prüfen und ggf. anpassen

[#assistent-durchlaufen]
=== Assistent durchlaufen

Um mit dem Messenger E-Mails senden und empfangen zu können, musst du den Assistenten *Messenger* im Menü *Einrichtung » Assistenten » Grundeinrichtung* durchlaufen. Im Folgenden werden die einzelnen Schritte, die du in diesem Assistenten durchläufst, beschrieben.

[TIP]
Für jedes Postfach, das du erstellen möchtest, musst du den Assistenten jeweils einmal durchlaufen. +
Du kannst jedem Postfach andere Tags zuweisen, um später nach diesen Tags <<#nachricht-suchen, filtern>> zu können.

[#service-aktivierung]
[discrete]
==== Service-Aktivierung

In diesem Schritt aktivierst du den Messenger-Service. Wenn die Schaltfläche blau (icon:toggle_on[set=material, role=skyBlue]) ist, ist der Service aktiviert. Wenn die Schaltfläche grau (icon:toggle_off[set=material, role=darkGrey]) ist, ist der Service _nicht_ aktiviert.

[#e-mail-weiterleitung]
[discrete]
==== E-Mail-Weiterleitung

In diesem Schritt wird automatisch eine kryptische E-Mail-Adresse, die die weiterleitende E-Mail-Adresse darstellt, erstellt. Verwende diese E-Mail-Adresse, um deinen E-Mail-Client einzurichten, damit deine E-Mails automatisch weitergeleitet werden. Beachte, dass du diese kryptische E-Mail-Adresse _nicht_ ändern kannst.

Gib im unteren Bereich alle E-Mail-Adressen ein, die Nachrichten an die kryptische, weiterleitende E-Mail-Adresse oben senden dürfen.

Du kannst beliebig viele E-Mail-Adressen mit einem Klick auf *Hinzufügen* (icon:plus-square[role="green"]) hinzufügen.

[#verifizierung-e-mail-adressen]
[discrete]
==== Verifizierung der E-Mail-Adressen

In diesem Schritt siehst du den Fortschritt des Verifizierungsvorgangs. plentymarkets sendet eine E-Mail an alle E-Mail-Adressen, die du im vorherigen Schritt <<#e-mail-weiterleitung, E-Mail-Weiterleitung>> eingegeben hast. Das System prüft dann, ob die E-Mail-Adressen valide sind und die Weiterleitungen funktionieren.

[#einstellungen-e-mail-versand]
[discrete]
==== Einstellungen für den E-Mail-Versand

// ehemals: SMTP-Konfiguration

In diesem Schritt speicherst du die Zugangsdaten des E-Mail-Postfachs, aus dem du E-Mails versenden möchtest, damit dein plentymarkets System E-Mails wie Auftragsbestätigungen und Versandbestätigungen von dieser E-Mail-Adresse versenden kann. 

Wähle nach Eingabe der Zugangsdaten (Host-Name, Benutzername, Port, Passwort) die Verschlüsselung und gib die Absender-E-Mail-Adresse sowie den Absendernamen ein. Diese E-Mail-Adresse und dieser Name wird den Empfänger:innen deiner E-Mails aus diesem Postfach angezeigt.

*_Hinweis für Postfächer bei mailbox.org:_* Gib den Port *465* ein und wähle als Verschlüsselung die Einstellung *SSL*.

// noch weitere Informationen aus diesem Kapitel einfügen ? https://knowledge.plentymarkets.com/crm/e-mails-versenden#200

Außerdem wählst du in diesem Schritt eine E-Mail-Vorlage für den E-Mail-Versand, die du vorher bereits im <<crm/emailbuilder-testphase#, EmailBuilder>> erstellt hast. Beachte, dass die hier gewählte Vorlage Messenger-Variablen enthalten sollte. 

Im EmailBuilder stehen dir die folgenden Messenger-bezogenen Variablen zur Verfügung:

* ID der Nachricht
* ID der Konversation
* Inhalt der Nachricht
* Titel der Nachricht
* Vorschau der Nachricht
* Minuten der Nachricht
* Abrechenbare Minuten der Nachricht

// siehe hier für englische Übersetzung: https://github.com/plentymarkets/module-mail-templates/pull/134/files 

// Erklärung ergänzen bzgl. der Messenger-Variablen

[#einstellungen-e-mail-empfang]
[discrete]
==== Einstellungen für den E-Mail-Empfang

// ehemals: Inbox configuration

In diesem Schritt wählst du den oder die Tags, die die Nachrichten erhalten sollen, wenn diese von weitergeleiteten Adressen empfangen werden.

Im letzten Abschnitt wählst du die Abonnent:innen, die bei neuen Nachrichten informiert werden. Wähle entweder einzelne Benutzer:innen aus der Dropdown-Liste oder wähle Rollen, damit alle dieser Rolle zugewiesenen Benutzer:innen neue Nachrichten in diesem Postfach abonnieren.

[#nachricht-erstellen]
== Nachricht erstellen

Gehe wie im Folgenden beschrieben vor, um eine neue Nachricht zu erstellen.

[.instruction]
Nachricht erstellen:

. Öffne das Menü *CRM » Messenger (Testphase)*.
. Klicke oben links auf icon:add[set=material] *Neue Nachricht*.
. Wähle (icon:check-square[role="blue"]) die Empfänger:innen aus der Liste. 
. Gib den Betreff ein.
. Klicke oben rechts auf *Tags* (icon:local_offer[set=material]), um Tags zu der Nachricht hinzuzufügen.
. Gib im Textfeld die Nachricht ein.
. Füge mit einem Klick auf icon:attach_file[set=material] Anhänge hinzu.
. Wähle mit einem Klick auf icon:more_vert[set=material] ggf. weitere Optionen.
. Beachte die Erläuterungen in <<#table-create-new-message>>.
. Klicke auf icon:forward_to_inbox[set=material] *SENDEN*.

[[table-create-new-message]]
.Neue Nachricht im Messenger erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Empfänger:innen*
|

| *Betreff*
|

| *Tags* (icon:local_offer[set=material])
|Mit einem Klick auf icon:local_offer[set=material] kannst du der Nachricht Tags hinzufügen.
// noch erklären und verlinken auf obere Kapitel bzgl. Tags.

| *Textfeld*
|

| *Anhänge* (icon:attach_file[set=material])
|Klicke auf icon:attach_file[set=material], um deiner Nachricht Anhänge hinzuzufügen. Wähle beliebig viele Anhänge von deinem Computer aus. +
Die folgenden Dateitypen sind als Anhang in der Nachricht zulässig: +
bmp, csv, gif, jpeg, json, pdf, png, tiff, txt, xlsx, zip.

| *Abrechnen* (icon:more_vert[set=material)])
|Du kannst eine Nachricht abrechnen, wenn es nicht um eine geflüsterte Nachricht handelt. Klicke dazu zunächst auf icon:more_vert[set=material]. Wenn du dann die Schaltfläche *Abrechnen* aktivierst (icon:toggle_on[set=material, role=skyBlue]), wird diese Nachricht abgerechnet. Die Schaltfläche icon:forward_to_inbox[set=material] *SENDEN* wird geändert in icon:forward_to_inbox[set=material] *ABRECHNEN UND SENDEN*. +
*_Hinweis:_* Sobald die Schaltfläche *Abrechnen* aktiviert ist, kann für diese Nachricht nicht der Flüstermodus aktiviert werden.

// weitere Informationen ergänzen bzgl. der Abrechnung. Wo sieht der Kunde das? im Mein Konto-Bereich?
// heißt in der UI aktuell noch "Abrechnung" --> muss noch in der UI-Datei angepasst werden.

| *Timer* (icon:more_vert[set=material)])
|Du kannst für jede Nachricht einen Timer starten. Klicke dazu zunächst auf icon:more_vert[set=material]. Wenn du dann die Schaltfläche *Timer* aktivierst (icon:toggle_on[set=material, role=skyBlue]), startet automatisch der Timer neben der Schaltfläche *SENDEN*. +
Klicke auf icon:pause-circle-o[], um den Timer anzuhalten bzw. auf icon:play-circle[], damit die Zeit weiterläuft.

| *Flüstern* (icon:more_vert[set=material)])
|Du kannst Nachrichten flüstern, damit diese nur intern sichtbar sind. Klicke dazu zunächst auf icon:more_vert[set=material]. Wenn du dann die Schaltfläche *Flüstern* aktivierst (icon:toggle_on[set=material, role=skyBlue]), wird diese Nachricht geflüstert. Das bedeutet, dass diese nur für interne Zwecke genutzt wird und _nicht_ extern versendet wird. Du erkennst eine geflüsterte Nachricht in dieser Ansicht an der Schaltfläche *Flüstern* (icon:visibility_off[set=material]) neben der Schaltfläche *SENDEN*. +
In der Übersicht werden geflüsterte Nachrichten in _kursiver Schrift_ dargestellt. +
*_Hinweis:_* Sobald der Flüstermodus für diese Nachricht aktiviert ist, kann die Schaltfläche *Abrechnen* nicht mehr aktiviert werden.

| *Senden*
|Mit einem Klick auf icon:forward_to_inbox[set=material] *SENDEN* wird die Nachricht gesendet.

|====

[#nachricht-suchen]
== Nachricht im Messenger suchen

Über die Übersicht im Messenger kannst du alle Nachrichten in einer Liste öffnen oder du wählst Filter (icon:filter[]), um die Suchergebnisse einzugrenzen.

[.instruction]
Nachricht im Messenger suchen:

. Öffne das Menü *CRM » Messenger (Testphase)*. +
* *_Möglichkeit 1:_* Klicke auf icon:search[set=material], um eine Liste aller E-Mails zu sehen.
* *_Möglichkeit 2:_* Klicke auf icon:filter[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.
. Beachte die Erläuterungen zu den Filtern in <<#table-search-message>>.

// TODO: Volltextsuche (großes Feld ganz oben) noch erklären.
// TODO: klären, ob das Icon innerhalb des Volltextsuchefelds so bleibt oder ob es auch das Filter-Icon sein soll.

[[table-search-message]]
.Filteroptionen im Messenger
[cols="1,3"]
|====
|Filter |Erläuterung

| *Inhalt*
|

| *Abgekürzte ID*
|

| *Von* / *Bis*
|Gib ein Datum ein oder wähle die Datumsangaben aus den Kalendern (icon:today[set=material]), um nach Nachrichten in einem bestimmten Zeitraum zu suchen.


| *Herkunft*
|Wähle eine Herkunft, um nach Nachrichten mit dieser Herkunft zu suchen.

| *Status*
|Wähle einen Status, um nach Nachrichten mit diesem Status zu suchen. +
Verfügbare Werte: *Erledigt* und *Nicht erledigt*.

| *Tags*
|Wähle <<#tags-messenger, Tags>>, um nach Nachrichten mit diesen Tags zu suchen.

| *Zurücksetzen*
|Setzt die gewählten Filtereinstellungen zurück.

| *Suchen*
|Führt die Suche aus. Die gefundenen Nachrichten werden in der Übersicht angezeigt. +
*_Tipp:_* Setze keine Filter, wenn du alle Nachrichten in der Übersicht sehen möchtest.

|====

// hier kann man gar keine Filter speichern????

[#aktuellen-filter-speichern]
=== Aktuellen Filter speichern

Wenn du eine Suche ausführst, siehst du deine gewählten Filter oben als so genannte "Chips" dargestellt. Diese Filter kannst du speichern, um sie in Zukunft schneller und einfacher wieder verwenden zu können.

[.instruction]
Aktuellen Filter speichern:

. Führe eine Suche aus.
. Klicke auf *Gespeicherte Filter* (icon:bookmarks[set=material]).
. Klicke auf icon:bookmark_border[set=material] *Aktuellen Filter speichern*.
. Gib einen Namen für den Filter ein.
. Entscheide, ob
** dieser Filter als Standard festgelegt werden soll (icon:toggle-on[role="blue"])
** dieser Filter für alle Benutzer:innen erstellt werden soll (icon:toggle-on[role="blue"]).
. Klicke auf *SPEICHERN*. +
→ Der Filter erscheint nun unter *Gespeicherte Filter* (icon:bookmarks[set=material]).

[TIP]
Lege die Reihenfolge der Filter per Drag-and-drop mit einem Klick auf *Verschieben* (icon:drag_indicator[set=material]) fest. Klicke auf icon:delete[set=material], um einen Filter zu löschen.

[#gespeicherte-filter-anwenden]
=== Gespeicherte Filter anwenden

[.instruction]
Gespeicherte Filter anwenden:

. Klicke auf *Gespeicherte Filter* (icon:bookmarks[set=material]).
. Klicke auf einen bereits erstellten Filter. +
→ Die Suche wird ausgeführt und die verwendeten Filtereinstellungen werden oben als so genannte "Chips" dargestellt.

[#spalten-konfigurieren]
=== Spalten konfigurieren

In der Übersicht des Messenger kannst du dir die folgenden Spalten anzeigen lassen:

* Auswahl
* Status
* Herkunft
* Von
* Betreff
* Empfangen am
* E-Mail
* Tags
* Anhang
* Kontextmenü

Über die Schaltfläche *Spalten konfigurieren* (icon:settings[set=material]) ganz oben rechts in der Übersicht kannst du bereits angezeigte Spalten in der Übersicht wieder deaktivieren.

[#ansicht-wechseln]
=== Ansicht wechseln

Du hast die Möglichkeit, die Ansichten von einer vertikalen zu einer horizontalen Ansicht zu wechseln. Klicke dazu auf *Ansicht wechseln* (icon:list[set=material]) ganz oben rechts in der Übersicht. +
Standardmäßig ist die horizontale Ansicht gewählt. Das bedeutet die Konversationen werden unten links angezeigt und der Editor zum Beantworten der Nachricht unten rechts.

[#kontextmenue]
== Kontextmenü in der Übersicht

In der Messenger-Übersicht stehen dir über das Kontextmenü in der Zeile der Nachricht mit einem Klick auf icon:more_vert[set=material] die folgenden Funktionen zur Verfügung:

* <<#kontextmenue-als-gelesen-markieren, Als gelesen / ungelesen markieren>>
* <<#kontextmenue-tags, Tags>>
* <<#kontextmenue-als-erledigt-markieren, Als erledigt markieren>>
* <<#kontextmenue-nachricht-loeschen, Löschen>>

[#kontextmenue-als-gelesen-markieren]
=== Nachricht als gelesen / ungelesen markieren

==== Nachricht als gelesen markieren

[.instruction]
Nachricht als gelesen markieren:

. Öffne das Menü *CRM » Messenger (Testphase)*.
. Klicke in der Zeile der Nachricht, die du als gelesen markieren möchtest auf icon:more_vert[set=material].
. Klicke auf icon:mark_email_read[set=material] *Als gelesen markieren*. +
→ Die Zeile der Nachricht ist nicht mehr in Fettdruck dargestellt und der blaue Punkt icon:circle[role="blue"] am Zeilenanfang verschwindet.

==== Nachricht als ungelesen markieren

[.instruction]
Nachricht als ungelesen markieren:

. Öffne das Menü *CRM » Messenger (Testphase)*.
. Klicke in der Zeile der Nachricht, die du als ungelesen markieren möchtest auf icon:more_vert[set=material].
. Klicke auf icon:mark_email_unread[set=material] *Als ungelesen markieren*. +
→ Die Zeile der Nachricht ist wird in Fettdruck dargestellt und ein blauer Punkt icon:circle[role="blue"] erscheint am Zeilenanfang.


[#kontextmenue-tags]
=== Tags zuweisen

Klicke auf icon:local_offer[set=material] *Tags*, um eine Liste aller bereits für den Bereich *Messenger* <<#tags-messenger, erstellten>> Tags zu sehen. Wähle (icon:check-square[role="blue"]) die Tags, die du der E-Mail zuweisen möchtest, aus der Liste.

// TODO: text ergänzen

[#nach-tag-suchen]
==== Nach Tag suchen

// TODO: text ergänzen

[#tags-waehlen]
==== Tag(s) wählen

// TODO: text ergänzen

[#tag-hinzufuegen]
==== Tag hinzufügen

Klicke auf icon:local_offer[set=material] *Tags* > icon:add[set=material] *Tag hinzufügen*, um ein neues Tag zu erstellen.

// TODO:  wird man hier dann in die UI Einrichtung » Einstellungen » Tags weitergeleitet?

[#tag-bearbeiten]
==== Tag bearbeiten

Klicke auf icon:local_offer[set=material] *Tags* > icon:edit[set=material] *Tag bearbeiten*, um ein bestehendes Tag zu bearbeiten.

// TODO:  wird man hier dann in die UI Einrichtung » Einstellungen » Tags weitergeleitet?
// TODO:  welches Tag kann ich hier bearbeiten? muss ich vorher eins ausgewählt haben oder lande ich direkt in der UI und kann dann dort entscheiden, welches Tag ich bearbeiten möchte?

[#kontextmenue-als-erledigt-markieren]
=== Nachricht auf erledigt setzen

Mit einem Klick auf icon:done[set=material] *Auf erledigt setzen* 

// TODO:  text ergänzen

[#kontextmenue-nachricht-loeschen]
=== Nachricht löschen

Mit einem Klick auf icon:delete[set=material] *Löschen*

// TODO:  text ergänzen

[#nachricht-bearbeiten]
== Nachricht bearbeiten

// TODO:  text ergänzen

[#nachricht-abrechnen]
== Nachricht abrechnen

// TODO:  text ergänzen

[#konversation-abonnieren]
== Nachrichtenkonversationen abonnieren

// TODO: text ergänzen

[#nachricht-loeschen]
== Nachricht löschen

// TODO: text ergänzen

[#gruppenfunktion]
== Gruppenfunktion nutzen

Sobald du eine Nachricht markiert hast (icon:check-square[role="blue"]), werden die verschiedenen Schaltflächen sichtbar (siehe TODO:). In Tabelle TODO: sind die Bedienelemente aus der Gruppenfunktion sowie deren Erläuterungen aufgelistet.

// TODO:  Bild und Tabelle ergänzen und verlinken

// TODO: Gruppenfunktionsbeschreibungen in der Tabelle nochmal prüfen.

[[table-group-functions-messenger]]
.Gruppenfunktion im Messenger nutzen
[cols="2,1,6"]
|====
|Bedienelement |Symbol |Erläuterung

| *Bearbeiten*
|icon:edit[set=material]
|

| *Herunterladen*
|icon:download[set=material]
|

| *xxx*
|icon:more_vert[set=material]
|

|====