= Messenger (Testphase)
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:description: Erfahre, wie du den Messenger in plentymarkets nutzt, um E-Mails an deine Kund:innen zu senden und zu empfangen.
:position: 480
:url: crm/messenger-testphase
:id: 7Z6FCLK
:author: team-crm

// TODO: testen in PID 56901

Im Menü *CRM » Messenger (Testphase)* verwaltest du die externe und interne Kommunikation mit deinen Kund:innen. Du hast auch die Möglichkeit, Nachrichten zu flüstern; in diesem Fall sind die Nachrichten nur in deinem plentymarkets System sichtbar und können von deinen Kontakten _nicht_ aufgerufen werden.

// TODO: Einleitung ergänzen

Das Menü *CRM » Messenger (Testphase)* ist wie folgt aufgebaut:

// TODO: farblich markierten Screenshot und bullet points mit Erklärungen einfügen.

* *Navigation*: TODO: 
* *Toolbar*: Hier kannst du nach Nachrichten suchen, die <<#spalten-konfigurieren, Spalten in der Übersicht anpassen>>, die Ergebnisse, die du pro Seite angezeigt haben möchtest, einstellen, und durch die Seiten mit den Nachrichten klicken.
* *Hauptfenster*: Hier wird der aktuell geöffnete Bereich angezeigt. +
** *Übersicht*: Wenn du eine Suche ausführst, siehst du die Ergebnisse in einer Übersicht. Die Übersicht liefert auf einen Blick Informationen zu den gefundenen Nachrichten. Zum Beispiel siehst du die E-Mail-Adressen der Absender:innen, den Betreff, das Empfangsdatum der E-Mail, die zugeordneten Tags und anhand des Symbols icon:attach_file[set=material], ob die E-Mail einen Anhang hat. +
** *Detailansicht*: Wenn du eine Nachricht öffnest, werden die Details unterhalb des Hauptfensters sichtbar. Die Detailansicht einer Nachricht ist unterteilt in den Nachrichtenverlauf und den Editor, in dem du deine Antwort verfassen kannst.

[discrete]
== Neue Features

[.collapseBox]
.Neue Features im Vergleich zum "alten" Messenger
--
Du findest die folgenden Neuerungen im neuen Messenger, die es vorher im "alten" Messenger nicht gab:

* E-Mails von deinen Kund:innen empfangen
* E-Mails an deine Kund:innen senden
--

[#vorbereitende-einstellungen]
== Vorbereitende Einstellungen

Wenn Benutzer:innen vom Typ *Backend* mit dem Messenger arbeiten sollen, muss eine Person mit *Admin*-Zugang zunächst Rechte für diese Benutzer:innen vergeben. Außerdem musst du Tags erstellen, damit diese für den Messenger zur Verfügung stehen und auch für die Tags bestimmte Rechte vergeben.

[#benutzerrechte-backend-benutzer]
=== Rechte für Backend-Benutzer:innen vergeben

:rights-purpose: Nachrichten im Messenger sehen und erstellen
:right-one: pass:quotes[*CRM > Nachricht > Anzeigen*]
:right-two: pass:quotes[*CRM > Nachricht > Erstellen*]
:right-three: pass:quotes[*Kommentare > Anzeigen*]
:right-four: pass:quotes[*Kommentare > Erstellen*]
:right-five: pass:quotes[*Einrichtung > Eigenschaft > Anzeigen*]
:right-six: pass:quotes[*Einrichtung > Eigenschaft > Erstellen*]

include::../_includes/textblocks/instructions/rechte.adoc[]

[#tags-messenger]
=== Tags für den Messenger erstellen

Du hast die Möglichkeit, den Nachrichten im Messenger Tags zuzuordnen und nach diesen auch in der Übersicht zu filtern. Tags sind Schlagworte, die dir das Gruppieren von Nachrichten leichter machen.

Welche Benutzer:innenrechte notwendig sind und wie du Tags erstellst, ist nachfolgend beschrieben.

[#rechte-tags]
==== Rechte für Backend-Benutzer:innen vergeben

include::../_includes/textblocks/instructions/tags-rights.adoc[]

[#tags-erstellen]
==== Tags erstellen

include::../_includes/textblocks/instructions/tags-creation.adoc[]
[TIP]
Wenn du Nachrichten erstellen möchtest, die über den Messenger _kostenpflichtig_ abgerechnet werden sollen, erstelle nach dem selben Schema Tags für den Bereich *Nachrichten (kostenpflichtig)*. Diese Tags musst du dann der <<#nachricht-erstellen, Nachricht>> hinzufügen.

// TODO: Begriff "Nachricht" vs. "E-Mail" prüfen und ggf. anpassen

[#assistent-durchlaufen]
=== Assistenten durchlaufen

Um mit dem Messenger E-Mails senden und empfangen zu können, musst du den Assistenten *Messenger* im Menü *Einrichtung » Assistenten » Grundeinrichtung* durchlaufen. Im Folgenden werden die einzelnen Schritte, die du in diesem Assistenten durchläufst, beschrieben.

Für jeden Posteingang musst du den Assistenten jeweils einmal durchlaufen.

[#service-aktivierung]
[discrete]
==== Service-Aktivierung

In diesem Schritt aktivierst du den Messenger-Service. Wenn die Schaltfläche blau (icon:toggle_on[set=material, role=skyBlue]) ist, ist der Service aktiviert. Wenn die Schaltfläche grau (icon:toggle_off[set=material, role=darkGrey]) ist, ist der Service _nicht_ aktiviert.

[#e-mail-weiterleitung]
[discrete]
==== E-Mail-Weiterleitung

In diesem Schritt wird automatisch eine kryptische E-Mail-Adresse, die die weiterleitende E-Mail-Adresse darstellt, erstellt. Verwende diese E-Mail-Adresse, im deinen E-Mail-Client einzurichten, damit deine E-Mails automatisch weitergeleitet werden. Beachte, dass du diese E-Mail-Adresse _nicht_ ändern kannst.

Gib im unteren Bereich die E-Mail-Adressen ein, die Nachrichten an die kryptische, weiterleitende E-Mail-Adresse oben senden dürfen.

Du kannst beliebig viele E-Mail-Adressen mit einem Klick auf *Hinzufügen* (icon:plus-square[role="green"]) hinzufügen.

[#verifizierung-e-mail-adressen]
[discrete]
==== Verifizierung der E-Mail-Adressen

In diesem Schritt siehst du den Fortschritt des Verifizierungsvorgangs. plentymarkets sendet eine E-Mail an alle E-Mail-Adressen, die du im vorherigen Schritt <<#e-mail-weiterleitung, E-Mail-Weiterleitung>> eingegeben hast. Das System prüft dann, ob die E-Mail-Adressen valide sind und die Weiterleitungen funktionieren.

[#einstellungen-e-mail-versand]
[discrete]
==== Einstellungen für den E-Mail-Versand

// ehemals: SMTP-Konfiguration

In diesem Schritt speicherst du die Zugangsdaten des E-Mail-Postfachs, aus dem du E-Mails versenden möchtest, damit dein plentymarkets System E-Mails wie Auftragsbestätigungen und Versandbestätigungen von dieser E-Mail-Adresse versenden kann. 

Wähle nach Eingabe der Zugangsdaten (Host-Name, Benutzername, Passwort) die Verschlüsselung und gib die Absender-E-Mail-Adresse sowie den Absendernamen ein. Dieser Name wird den Empfänger:innen deiner E-Mail angezeigt.

// weiter unten dieses Kapitel einfügen ? https://knowledge.plentymarkets.com/crm/e-mails-versenden#200

[#einstellungen-e-mail-empfang]
[discrete]
==== Einstellungen für den E-Mail-Empfang

// ehemals: Inbox configuration

In diesem Schritt wählst du eine E-Mail-Vorlage aus, die du im <<crm/emailbuilder-testphase#, EmailBuilder>> erstellt hast. Beachte, dass die hier gewählte Vorlage Messenger-Variablen enthalten sollte.

// Erklärung ergänzen bzgl. der Messenger-Variablen

Außerdem wählst du den oder die Tags, die die Nachrichten erhalten sollen, wenn diese von weitergeleiteten Adressen empfangen werden.

Im letzten Abschnitt wählst du die Abonnent:innen, die bei neuen Nachrichten informiert werden.

[#e-mail-suchen]
== E-Mail im Messenger suchen

Über die Übersicht im Messenger kannst du alle E-Mails in einer Liste öffnen oder du wählst Filter (icon:filter[]), um die Suchergebnisse einzugrenzen.

[.instruction]
E-Mail im Messenger suchen:

. Öffne das Menü *CRM » Messenger (Testphase)*. +
* *_Möglichkeit 1:_* Klicke auf icon:search[set=material], um eine Liste aller E-Mails zu sehen.
* *_Möglichkeit 2:_* Klicke auf icon:filter[], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.
. Beachte die Erläuterungen zu den Filtern in <<#table-search-email-messenger>>.

// TODO: Volltextsuche (großes Feld ganz oben) noch erklären.

[[table-search-email-messenger]]
.Filteroptionen im Messenger
[cols="1,3"]
|====
|Filter |Erläuterung

| *Inhalt*
|

| *Von*
|

| *Bis*
|

| *Herkunft*
|Wähle (icon:check-square[role="blue"]) eine oder mehrere Herkünfte, um nach E-Mails mit dieser Herkunft zu suchen.

| *Status*
|?

| *Tags*
|Wähle <<#tags-messenger, Tags>>, um nach Nachrichten mit diesen Tags zu suchen.

| *Zurücksetzen*
|Setzt die gewählten Filtereinstellungen zurück.

| *Suchen*
|Führt die Suche aus. Die gefundenen E-Mails werden in der Übersicht angezeigt. +
*_Tipp:_* Setze keine Filter, wenn du alle E-Mails in der Übersicht sehen möchtest.

|====

[#aktuellen-filter-speichern]
=== Aktuellen Filter speichern

Wenn du eine Suche ausführst, siehst du deine gewählten Filter oben als so genannte "Chips" dargestellt. Diese Filter kannst du speichern, um sie in Zukunft schneller und einfacher wieder verwenden zu können.

[.instruction]
Aktuellen Filter speichern:

. Führe eine Suche aus.
. Klicke auf *Gespeicherte Filter* (icon:bookmark[role="darkGrey"]).
. Klicke auf icon:bookmark-o[role="darkGrey"] *Aktuellen Filter speichern*.
. Gib einen Namen ein und und entscheide, ob die Filtervoreinstellung in allen Benutzerkonten sichtbar sein soll (icon:toggle-on[role="blue"]).
. Klicke auf *SPEICHERN*. +
→ Die Filtereinstellungen erscheinen nun unter *Gespeicherte Filter* (icon:bookmark[role="darkGrey"]).

[TIP]
Lege die Reihenfolge der Filtervoreinstellungen per Drag-and-drop mit einem Klick auf *Verschieben* (icon:drag_indicator[set=material]) fest. Klicke auf icon:trash[role="darkGrey"], um eine Filtervoreinstellung zu löschen.

[#gespeicherte-filter-anwenden]
=== Gespeicherte Filter anwenden

[.instruction]
Gespeicherte Filter anwenden:

. Klicke auf *Gespeicherte Filter* (icon:bookmark[role="darkGrey"]).
. Klicke auf eine bereits erstellte Filtervoreinstellung. +
→ Die Suche wird ausgeführt und die verwendeten Sucheinstellungen werden oben als so genannte "Chips" dargestellt.

[#spalten-konfigurieren]
== Spalten konfigurieren

In der Übersicht des Messenger kannst du dir die folgenden Spalten anzeigen lassen:

* Auswahl
* Status
* Herkunft
* Von
* Betreff
* Empfangen am
* E-Mail
* Tags
* Anhang
* Kontextmenü

// TODO: nochmal prüfen und ggf Texte in der UI korrigieren

Über die Schaltfläche *Spalten konfigurieren* (icon:settings[set=material]) ganz oben rechts in der Übersicht kannst du bereits angezeigte Spalten in der Übersicht wieder deaktivieren.

[#kontextmenue]
== Kontextmenü in der Übersicht

In der Messenger-Übersicht stehen dir über das Kontextmenü in der Zeile der E-Mail mit einem Klick auf icon:more_vert[set=material] die folgenden Funktionen zur Verfügung:

* <<#kontextmenue-als-gelesen-markieren, Als gelesen markieren>>
* <<#kontextmenue-tags, Tags>>
* <<#kontextmenue-auf-erledigt-setzen, Erledigt setzen>>
// TODO: in der UI ändern zu --> Auf erledigt setzen
* <<#kontextmenue-e-mail-loeschen, Löschen>>

[#kontextmenue-als-gelesen-markieren]
=== E-Mail als gelesen markieren

Klicke auf icon:drafts[set=material], um die E-Mail als gelesen zu markieren.

// TODO: woran ist es zu erkennen, dass ich eine E-Mail als gelesen markiert habe?

// TODO: text ergänzen

[#kontextmenue-tags]
=== Tags zuweisen

Klicke auf icon:local_offer[set=material] *Tags*, um eine Liste aller bereits für den Bereich *Messenger* <<#tags-messenger, erstellten>> Tags zu sehen. Wähle (icon:check-square[role="blue"]) die Tags, die du der E-Mail zuweisen möchtest, aus der Liste.

// TODO: text ergänzen

[#nach-tag-suchen]
==== Nach Tag suchen

// TODO: text ergänzen

[#tags-waehlen]
==== Tag(s) wählen

// TODO: text ergänzen

[#tag-hinzufuegen]
==== Tag hinzufügen

Klicke auf icon:local_offer[set=material] *Tags* > icon:add[set=material] *Tag hinzufügen*, um ein neues Tag zu erstellen.

// TODO:  wird man hier dann in die UI Einrichtung » Einstellungen » Tags weitergeleitet?

[#tag-bearbeiten]
==== Tag bearbeiten

Klicke auf icon:local_offer[set=material] *Tags* > icon:edit[set=material] *Tag bearbeiten*, um ein bestehendes Tag zu bearbeiten.

// TODO:  wird man hier dann in die UI Einrichtung » Einstellungen » Tags weitergeleitet?
// TODO:  welches Tag kann ich hier bearbeiten? muss ich vorher eins ausgewählt haben oder lande ich direkt in der UI und kann dann dort entscheiden, welches Tag ich bearbeiten möchte?

[#kontextmenue-auf-erledigt-setzen]
=== E-Mail auf erledigt setzen

Mit einem Klick auf icon:done[set=material] *Auf erledigt setzen* 

// TODO:  text ergänzen

[#kontextmenue-e-mail-loeschen]
=== E-Mail löschen

Mit einem Klick auf icon:delete[set=material] *Löschen*

// TODO:  text ergänzen

[#gruppenfunktion]
== Gruppenfunktion nutzen

Sobald du eine Nachricht markiert hast (icon:check-square[role="blue"]), werden die verschiedenen Schaltflächen sichtbar (siehe TODO:). In Tabelle TODO: sind die Bedienelemente aus der Gruppenfunktion sowie deren Erläuterungen aufgelistet.

// TODO:  Bild und Tabelle ergänzen und verlinken

// TODO: Gruppenfunktionsbeschreibungen in der Tabelle nochmal prüfen.

[[table-group-functions-messenger]]
.Gruppenfunktion im Messenger nutzen
[cols="2,1,6"]
|====
|Bedienelement |Symbol |Erläuterung

| *Bearbeiten*
|icon:edit[set=material]
|

| *Herunterladen*
|icon:download[set=material]
|

| *xxx*
|icon:more_vert[set=material]
|

|====