= Newsletter versenden
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Double-Opt-In-Funktion, Double-opt, E-Mail-Vorlage, E-Mail-Ordner, Newsletter-Zugangsdaten, CleverReach, Newsletter2Go
:description: Erfahren Sie, wie Sie Newsletter mit Newsletter2Go, CleverReach oder mit dem in plentymarkets integrierten Newsletter an Ihre Kunden versenden.
:position: 40

Auf dieser Handbuchseite wird beschrieben, welche Einstellungen Sie vornehmen müssen, um Newsletter mit plentymarkets zu versenden. Nutzen Sie den in plentymarkets <<crm/newsletter-versenden#100, *integrierten Newsletter*>> oder versenden Sie Ihre Newsletter mit <<crm/newsletter-versenden#1700, *CleverReach*>> oder <<crm/newsletter-versenden#2100, *Newsletter2Go*>>.

In plentymarkets wird die Double-Opt-In-Methode verwendet, d.h. der Empfänger erhält nach Bestellung des Newsletters eine E-Mail mit einem Bestätigungslink. Erst nachdem der Kunde auf den Link geklickt hat, ist er für den Newsletter angemeldet. Diese Methode ist fest integriert und kann nicht geändert werden.

[#100]
== In plentymarkets integrierten Newsletter-Dienst einrichten

Gehen Sie wie im Folgenden beschrieben vor, um den in plentymarkets integrierten Newsletter-Dienst einzurichten. Sie müssen in mehreren Menüs Einstellungen vornehmen, damit Sie Ihre Newsletter über plentymarkets versenden können.

[#200]
=== Newsletter-Zugangsdaten eingeben

Im Menü *System » Mandant » Mandant öffnen » E-Mail » Newsletter* geben Sie die Zugangsdaten ein, um den in plentymarkets integrierten Newsletter-Dienst zu nutzen.

[.instruction]
Newsletter-Zugangsdaten eingeben:

. Öffnen Sie das Menü *System » Mandant » Mandant öffnen » E-Mail » Newsletter*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. *Speichern* Sie die Einstellungen.

.Einstellungen im Menü *System » Mandant » Mandant öffnen » E-Mail » Newsletter*
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Name des Absenders*
|Eigenen Namen oder Name des Webshops eingeben, wie er beim Empfänger angezeigt werden soll.

|*E-Mail-Adresse*
|E-Mail-Adresse eingeben, wie sie auch im E-Mail-Programm steht. Über diese E-Mail-Adresse wird der Newsletter versendet.

|*Postausgangsserver / SMTP-Server*
|Postausgangsserver wie vom Provider angegeben eingeben (meist smtp.domain.de oder mail.domain.de). +
*_mailbox.org:_* Für Postfächer bei mailbox.org den Postausgangsserver *smtp.mailbox.org* eingeben und unter *Verschlüsselung* die Einstellung *SSL* wählen.

|*Benutzername*
|Benutzername zu der E-Mail-Adresse eingeben. +
*_mailbox.org:_* Der mailbox.org-Benutzername ist die vollständige E-Mail-Adresse des mailbox.org-Postfachs.

|*Passwort*
|Passwort zu dem Benutzername und der E-Mail-Adresse eingeben.

|*Port (Standardport: 25)*
|Wert *25* eingeben. Dieser Wert ist für fast alle Provider korrekt. Ggf. den korrekten Port beim Provider erfragen. +
*_mailbox.org:_* Für Postfächer bei mailbox.org den Port *465* eingeben und unter *Verschlüsselung* die Einstellung *SSL* wählen.

|*Verschlüsselung*
|*SSL*, *TLS* oder *keine Verschlüsselung* wählen. +
*_mailbox.org:_* Für Postfächer bei mailbox.org die Einstellung *SSL* wählen. +
Weitere Informationen siehe Kapitel <<crm/e-mails-versenden#200, *Verschlüsselung der E-Mail-Kommunikation wählen*>> auf der Handbuchseite <<crm/e-mails-versenden#, *E-Mails versenden*>>.
|====

[#300]
=== E-Mail-Ordner erstellen

Im Menü *System » CMS » Newsletter » plentymarkets » E-Mail-Ordner* erstellen Sie Ordner für den Versand von Newslettern. In diesen Ordnern speichern Sie dann die E-Mail-Adressen Ihrer Kunden. So können Sie auf bestimmte Zielgruppen abgestimmte Newsletter versenden. Gehen Sie wie im Folgenden beschrieben vor, um einen neuen E-Mail-Ordner zu erstellen.

[.instruction]
E-Mail-Ordner erstellen:

. Öffnen Sie das Menü *System » CMS » Newsletter » plentymarkets » E-Mail-Ordner*.
. Geben Sie im Bereich *Neuen E-Mail-Ordner anlegen* einen Namen für den Ordner ein.
. Ändern Sie ggf. die ID des Ordners.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 2.
. *Speichern* Sie die Einstellungen. +
→ Der E-Mail-Ordner wird erstellt und in der Übersicht angezeigt.

.Einstellungen im Menü *System » CMS » Newsletter » plentymarkets » E-Mail-Ordner*
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*ID*
|Wird beim Erstellen eines neuen Ordners fortlaufend vergeben. Die Ordner-ID kann beim Erstellen eines neuen Ordners geändert werden. Die ID *0* kann nicht vergeben werden. +
*_Hinweis:_* Eindeutige ID vergeben. Wird eine bereits bestehende ID eingegeben, wird der ursprüngliche Ordner überschrieben.

|*Bezeichnung*
|Name des E-Mail-Ordners. Wird die Option *Auswählbar durch Kunden* aktiviert, ist der Name für Kunden im Webshop sichtbar.

|*Auswählbar durch Kunden*
|Aktivieren, wenn der Ordner von Kunden im Webshop gewählt werden soll. Der Ordner wird im Bereich *Mein Konto* des Webshops angezeigt. Kunden wählen dann Newsletter anhand der dort verfügbaren Ordner.

|*Position*
|Position eingeben, um festzulegen, in welcher Reihenfolge die Ordner angezeigt werden sollen.

|*Sichtbarkeit*
|Festlegen, ob der Newsletter-Ordner nur für den Standard-Webshop oder für alle Webshops sichtbar sein soll. Mit *Keiner* wird die Sichtbarkeit des Ordners deaktiviert.

|*Löschen*
|Aktivieren und auf *Speichern* klicken, um den Ordner zu löschen.
|====

[#400]
=== E-Mail-Ordner bearbeiten

Bestehende E-Mail-Ordner bearbeiten Sie ebenfalls im Menü *System » CMS » Newsletter » plentymarkets » E-Mail-Ordner*. Gehen Sie wie im Folgenden beschrieben vor, um die Einstellungen eines E-Mail-Ordners zu bearbeiten.

[.instruction]
E-Mail-Ordner bearbeiten:

. Öffnen Sie das Menü *System » CMS » Newsletter » plentymarkets » E-Mail-Ordner*.
. Nehmen Sie die Änderungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 2.
. *Speichern* Sie die Einstellungen.

[#500]
=== E-Mail-Adressen dem Newsletter-Hauptordner zuordnen

Im Menü <<omni-channel/online-shop/webshop-einrichten/bestellvorgang#, *System » Mandant » Mandant öffnen » Bestellvorgang » Einstellungen*>> wählen Sie über das Dropdown-Menü *Newsletter-Hauptordner* den E-Mail-Ordner für Newsletter, der automatisch mit der E-Mail-Adresse eines Kunden verknüpft wird, wenn der Kunde den Newsletter während des Bestellvorgangs im Webshop abonniert. Alle sichtbaren E-Mail-Ordner sind im Dropdown-Menü aufgelistet (siehe Option *Sichtbarkeit* in Tabelle 2).

[#600]
=== Newsletter-Wahl für Kunden erlauben

Sie können Ihren Kunden ermöglichen, selbst einen E-Mail-Ordner zu wählen. Das ist z.B. von Vorteil, wenn Sie regelmäßig Newsletter zu verschiedenen Themenbereichen versenden. So bestimmen Ihre Kunden selbst, welche Newsletter sie von Ihnen erhalten. Ihre Kunden können alle E-Mail-Ordner, die Sie unter der Option *Auswählbar durch Kunden* in Tabelle 2 aktiviert haben, im Bereich *Mein Konto* des Webshops wählen. Die E-Mail-Adresse des Kunden wird dann in diesem E-Mail-Ordner in Ihrem plentymarkets System gespeichert.

[#700]
=== E-Mail-Vorlage erstellen

Versenden Sie Ihre Bestätigungs-E-Mail per E-Mail-Vorlage. Nutzen Sie Template-Variablen, damit die Vorlage beim Versenden automatisch den richtigen Namen des Kunden sowie den Bestätigungslink enthält. Gehen Sie wie im Folgenden beschrieben vor, um die E-Mail-Vorlage zu erstellen.

[.instruction]
E-Mail-Vorlage erstellen:

. Öffnen Sie das Menü *System » Mandant » Mandant öffnen » E-Mail » Vorlagen*.
. Klicken Sie auf *Neue E-Mail-Vorlage*. +
→ Das Fenster *Neue E-Mail-Vorlage* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in Tabelle 3.
. Fügen Sie die Template-Variable *$CustomerFullName* in den Text der E-Mail ein. +
→ Diese Template-Variable gibt den Vornamen und den Nachnamen des Kunden aus.
. Fügen Sie die Template-Variable *$NewsletterConfirmURL* in den Text der E-Mail ein. +
→ Diese Template-Variable gibt den Bestätigungslink aus.
. *Speichern* Sie die Einstellungen.

Klickt der Empfänger der E-Mail auf den durch die Template-Variable *$NewsletterConfirmURL* eingefügten Link, bestätigt er die Anmeldung zum Newsletter und erhält ab sofort Newsletter an diese E-Mail-Adresse.

Wenn Sie die <<crm/newsletter-versenden#800, *Double-Opt-In-Methode*>> verwenden möchten, ist ein weiterer Schritt notwendig. Sie müssen jeweils eine Vorlage erstellt haben und diese im Menü *System » Mandant » Mandant öffnen » E-Mail » Automatischer Versand* für die Ereignisse *Newsletter Opt-In* und *Bestätigung Newsletter Opt-In* gewählt haben.

[IMPORTANT]
.Template-Variablen und Template-Funktionen beachten
====
In plentymarkets steht Ihnen eine umfangreiche Auswahl an Template-Variablen und Template-Funktionen für Ihre E-Mail-Vorlagen zur Verfügung. Diese können Sie im Menü *System » Mandant » Mandant öffnen » E-Mail » Vorlagen* in der E-Mail-Vorlage im Tab *E-Mail-Nachricht* in den reinen Text oder in den HTML-formatierten Text an die gewünschte Stelle kopieren.

Weitere Informationen finden Sie auf den Handbuchseiten <<crm/e-mails-versenden#, *E-Mails versenden*>>, <<omni-channel/online-shop/cms-syntax#grundlagen-template-variablen, *Template-Variablen*>> und <<omni-channel/online-shop/cms-syntax#grundlagen-template-funktionen, *Template-Funktionen*>>.
====

.Neue E-Mail-Vorlage im Menü *System » Mandant » Mandant öffnen » E-Mail » Vorlagen* erstellen
[cols="a,a"]
|====
|Einstellung |Erläuterung

2+|Tab: Einstellungen

|*Eigner*
|Eigner oder die Einstellung *Alle* wählen. +
*Alle* = Vorlage wird unter *Allgemeine E-Mail-Vorlagen* gespeichert. +
Eigener Benutzername = Vorlage wird unter *Meine E-Mail-Vorlagen* gespeichert. Um eine eigene E-Mail-Vorlage unter *Meine E-Mail-Vorlagen* zu erstellen, muss man als Benutzer im System eingeloggt sein. +
Anderer Benutzername = Vorlage wird unter *E-Mail-Vorlagen anderer Benutzer* gespeichert.

|*Name*
|Name eingeben, unter der diese Vorlage gespeichert werden soll. Diese Bezeichnung wird dem Empfänger nicht angezeigt.

|*Inhalt*
|Wählen, ob die Nachricht als *reiner Text* oder als *HTML-formatierte Nachricht* gespeichert werden soll.

|*Template-Typ*
|*Alle* (Standardeinstellung), *Auftrag*, *Kunden*, *Webshop* oder *Ticket* wählen. +
*Alle* = Die E-Mail-Vorlage wird für alle Bereiche verwendet. +
*Auftrag*/*Kunden*/*Webshop*/*Ticket* = Die E-Mail-Vorlage steht ausschließlich für den gewählten Bereich zur Verfügung. Sie kann für die anderen Bereiche nicht verwendet werden bzw. ist dort nicht sichtbar.

|*PDF-Anhang*
|Anhang aus dem Dropdown-Menü wählen. Die dort verfügbaren Dokumente werden vom System erzeugt.

|*Dokumentenanhang*
|Auf Wunsch unter *CMS » Dokumente* hochgeladene eigene Dokumente wählen, die an eine E-Mail-Vorlage anhängt werden sollen. +
Für alle E-Mail-Vorlagen können bis zu zwei Anhänge hinterlegt werden. PDF-Dokumente aus dem Bereich Fulfillment (z.B. Rechnungen) oder andere Dateien (z.B. ein Artikelprospekt oder eine Anleitung) können standardisiert über E-Mail-Vorlagen an Kunden verschickt werden. Für die Vorlage *Eingangsbestätigung Webshop Bestellung* wären z. B. die Widerrufsbelehrung und Ihre AGB im PDF-Format eine sinnvolle Ergänzung.

|*Antwort an*
|E-Mail-Adresse eingeben, an die die Antworten auf diese E-Mail-Vorlage gesendet werden sollen. Wenn keine E-Mail-Adresse eingegeben ist, werden Antworten auf diese Vorlage standardmäßig an die unter <<crm/e-mails-versenden#100, *System » Mandant » Mandant öffnen » E-Mail » Zugangsdaten*>> gespeicherte E-Mail-Adresse geschickt. Beispielsweise ist es sinnvoll, die E-Mail-Adresse der Buchhaltungsabteilung für die E-Mail-Vorlage *PDF-Rechnung* einzugeben. So gehen z.B. Rückfragen zur Rechnung direkt an die Buchhaltungsabteilung und müssen nicht weitergeleitet werden.

|*Design verwenden*
|Aktivieren, wenn der Inhalt der E-Mail mit dem im Menü <<crm/e-mails-versenden#800, *System » Mandant » Mandant öffnen » E-Mail » HTML-Design*>> gespeicherten Design versendet werden soll. Wird die Option nicht aktiviert, wird nur der Inhalt der E-Mail-Vorlage verwendet.

2+|Tab: E-Mail-Nachricht

|*Sprache wählen*
|Die Sprache wird hier angezeigt und kann geändert werden.

|*Betreff*
|Betreff eingeben. Dabei den Betreff mit großer Sorgfalt wählen, damit die E-Mails im Postfach des Kunden leicht erkennbar sind und nicht dem Spam-Filter zum Opfer fallen.

|*Inhalt / Artikelliste*
|In diese Tabs den Text bzw. die Artikelauflistung als *reinen Text* oder als *HTML-formatierten Text* eingeben. Für den Inhalt stehen verschiedene Template-Variablen und Template-Funktionen zur Verfügung. +
*_Hinweis:_* Es wird nur der Inhalt des Tabs berücksichtigt, dessen Inhaltstyp im Tab *Einstellungen* unter *Inhalt* festgelegt wurde. Wenn dort also z.B. *Nur reiner Text* eingestellt wurde, jedoch nur das Tab *HTML-formatierter Text* Inhalt enthält, wird keine E-Mail versendet.
|====

[#800]
=== E-Mail-Vorlagen mit der Double-Opt-In-Funktion verknüpfen

Im nächsten Schritt verknüpfen Sie die soeben erstellte E-Mail-Vorlage mit der Double-Opt-In-Funktion und wählen eine weitere Vorlage für das Ereignis *Bestätigung Newsletter Opt-In*. Bei der Double-Opt-In-Methode muss der Kunde, nachdem er sich für den Newsletter angemeldet hat, die Newsletter-Anmeldung in einem zweiten Schritt bestätigen.

[TIP]
.Hinweise zur Double-Opt-In-Methode
====
Wählen Sie im Menü *System » Mandant » Mandant öffnen » E-Mail » Automatischer Versand* zwei <<crm/newsletter-versenden#700, *zuvor erstellte*>> Vorlagen für die Ereignisse *Newsletter Opt-In* und *Bestätigung Newsletter Opt-In*. Die gewählte Vorlage unter *Newsletter Opt-In* wird versendet, wenn der Kunde sich für Ihren Newsletter anmeldet. Diese Vorlage sollte den Bestätigungslink enthalten, den der Kunde anklicken muss, um die Newsletter-Anmeldung abzuschließen. Den Bestätigungslink können Sie mit der Template-Variable *$NewsletterConfirmURL*, die die URL zur Bestätigung der Newsletter-Anmeldung beinhaltet, abbilden. Die gewählte Vorlage unter *Bestätigung Newsletter Opt-In* wird versendet, sobald der Kunde den Bestätigungslink aktiviert hat.

Im Kundendatensatz im Menü *Kunden » Kunden bearbeiten » Kunde suchen » Kunde öffnen* wird im Tab *Kundendaten* die Option *Newsletter* automatisch aktiviert, wenn der Kunde sich im Bestellvorgang für den Newsletter angemeldet und die Newsletter-Anmeldung über den Bestätigungslink bestätigt hat.
====

[.instruction]
E-Mail-Vorlagen mit der Double-Opt-In-Funktion verknüpfen:

. Öffnen Sie das Menü *System » Mandant » Mandant öffnen » E-Mail » Automatischer Versand*.
. Wählen Sie für die Option *Newsletter Opt-In* die soeben erstellte E-Mail-Vorlage aus dem Dropdown-Menü.
. Wählen Sie für die Option *Bestätigung Newsletter Opt-In* die E-Mail-Vorlage aus dem Dropdown-Menü.
. *Speichern* Sie die Einstellungen.

Den Status der Bestätigung können Sie im Menü *System » CMS » Newsletter » plentymarkets » E-Mails* einsehen. Bei Kunden, die den Newsletter-Bezug nach der vorstehend beschriebenen Vorgehensweise bestätigt haben, ist dies am Status *bestätigt* zu erkennen. Bei Kunden, die das Double-Opt-in nicht durchgeführt haben, steht dort *nicht bestätigt*.

[#900]
=== E-Mail-Adresse speichern

E-Mail-Adressen für den Versand von Newslettern werden in verschiedenen Ordnern gespeichert. Im Menü *System » CMS » Newsletter » plentymarkets » E-Mails* verwalten Sie die E-Mail-Adressen der verfügbaren Ordner. Falls Sie noch keine <<crm/newsletter-versenden#300, *Ordnerstruktur*>> für Ihre Newsletter angelegt haben, empfiehlt es sich, dies vorab zu tun.

Gehen Sie wie im Folgenden beschrieben vor, um eine E-Mail-Adresse in einem E-Mail-Ordner zu speichern.

[.instruction]
E-Mail-Adresse speichern:

. Öffnen Sie das Menü *System » CMS » Newsletter » plentymarkets » E-Mails*.
. Klappen Sie den Ordner auf.
. Klappen Sie den Bereich *Neue E-Mail-Adresse* auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 4.
. *Speichern* Sie die Einstellungen.

.Einstellungen zum Speichern einer neuen E-Mail-Adresse
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Vorname*
|Vorname des Kunden eingeben.

|*Nachname*
|Nachname des Kunden eingeben.

|*E-Mail*
|E-Mail-Adresse des Kunden eingeben.

|*Ordner*
|<<crm/newsletter-versenden#300, *E-Mail-Ordner*>> wählen, in dem die Kundendaten gespeichert werden sollen.
|====

[#1000]
=== Newsletter erstellen

Neue Newsletter erstellen Sie wie im Folgenden beschrieben. Sie können so auch bestehende Newsletter bearbeiten.

[.instruction]
Newsletter erstellen:

. Öffnen Sie das Menü *CMS » Newsletter*.
. Klappen Sie den Bereich *Neuer Newsletter* auf. +
→ Das Bearbeitungsfenster für den neuen Newsletter wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 5.
. *Speichern* Sie die Einstellungen.

.Einstellungen zum Erstellen eines Newsletters
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Betreff*
|Betreff für den Newsletter eingeben.

|*HTML Newsletter*
|Inhalt des Newsletters als HTML-Code eingeben. +
*_Hinweis:_* Texte werden nur in einem Bereich gespeichert. Daher entweder im Bereich *HTML Newsletter* oder im Bereich *Text Newsletter* Inhalte eingeben.

|*Text Newsletter*
|Inhalt des Newsletters in reiner Textform eingeben. +
*_Hinweis:_* Texte werden nur in einem Bereich gespeichert. Daher entweder im Bereich *HTML Newsletter* oder im Bereich *Text Newsletter* Inhalte eingeben.

|*Bildergalerie*
|Öffnet das Menü <<omni-channel/online-shop/cms#bilder-galerie, *CMS » Bilder-Galerie*>>. Hier ein Bild hochladen, um es mit dem Newsletter zu verknüpfen.

|*Layout-Vorlage einspielen*
|Bei Klick auf *Layout-Vorlage einspielen* wird die Anrede *Guten Tag* sowie der Platzhalter *[NAME]* eingesetzt. Für den Platzhalter wird beim Versenden automatisch der Name des Kunden eingefügt.
|====

[#1100]
=== Kunden anhand der E-Mail-Adresse oder des Nachnamen suchen

Gehen Sie wie im Folgenden beschrieben vor, um eine E-Mail-Adresse in einem E-Mail-Ordner zu suchen. Sie können Kunden entweder anhand der E-Mail-Adresse oder des Nachnamens suchen.

[.instruction]
Kunden anhand der E-Mail-Adresse oder des Nachnamen suchen:

. Öffnen Sie das Menü *System » CMS » Newsletter » plentymarkets » E-Mails*.
. Klappen Sie den E-Mail-Ordner auf.
. Wählen Sie im Dropdown-Menü die Einstellung *E-Mail-Adresse* oder *Nachname*, um anhand dieser Einstellung zu suchen.
. Geben Sie die E-Mail-Adresse bzw. den Nachnamen des Kunden in das Suchfeld ein.  +
→ Für die Suche ist es ausreichend, wenn Sie nur einen Teil des Namens oder der E-Mail-Adresse eingeben. Lassen Sie das Feld leer, um alle E-Mail-Adressen bzw. Nachnamen anzuzeigen.
. Klicken Sie auf *Suche*. +
→ Das Suchergebnis wird angezeigt.

Im Suchergebnis wird auch der Status der Bestätigung angezeigt. In plentymarkets wird die <<crm/newsletter-versenden#800, *Double-Opt-In-Methode*>> verwendet. Dabei erhalten Empfänger nach dem Bestellen des Newsletters eine E-Mail mit einem Link, über den sie die Newsletter-Bestellung bestätigen müssen. Kunden, die den Newsletter-Bezug so bestätigt haben, erkennen Sie an dem Status *bestätigt*. Andernfalls steht dort *nicht bestätigt*.

[#1200]
=== E-Mail-Adresse bearbeiten

Nachdem Sie eine E-Mail-Adresse über die Suchfunktion gefunden haben, können Sie die Daten für diesen Kunden bearbeiten. Sie können z.B. die E-Mail-Adresse eines Kunden ändern oder den Kundendatensatz in einen anderen E-Mail-Ordner verschieben. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
E-Mail-Adresse bearbeiten:

. Öffnen Sie das Menü *System » CMS » Newsletter » plentymarkets » E-Mails*.
. Suchen Sie den Kunden wie im Kapitel <<crm/newsletter-versenden#1100, *Kunden anhand der E-Mail-Adresse oder des Nachnamen suchen*>> beschrieben.
. Klappen Sie den Kunden auf.
. Nehmen Sie die Änderungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 4 im Kapitel <<crm/newsletter-versenden#900, *E-Mail-Adresse speichern*>>.
. *Speichern* Sie die Einstellungen.

[#1300]
=== E-Mail-Adressen exportieren und importieren

In den vorigen Kapiteln wird beschrieben, wie Sie eine einzelne E-Mail-Adresse verwalten. Wenn Sie viele E-Mail-Adressen auf einmal bearbeiten möchten, ist es sinnvoll, mit dem <<basics/datenaustausch#, *Datenaustausch*>> zu arbeiten. E-Mail-Adressen können Sie importieren oder exportieren. Im Menü <<basics/datenaustausch/daten-exportieren#, *Datenaustausch » Export » Dynamischer Export*>> können Sie über das Datenformat <<basics/datenaustausch/datenformate/customernewsletter#, *CustomerNewsletter*>> alle E-Mail-Adressen exportieren. Im Menü <<basics/datenaustausch/daten-importieren#, *Datenaustausch » Import » Dynamischer Import*>> können Sie neue E-Mail-Adressen importieren.

[#1400]
=== Kundendaten in einen E-Mail-Ordner kopieren

Im Menü *System » CMS » Newsletter » plentymarkets » E-Mail-Filter* filtern Sie nach Kundendaten und kopieren die E-Mail-Adressen dieser Kunden in bestimmte E-Mail-Ordner. Sie haben z.B. die Möglichkeit, nach Kunden zu suchen, die bestimmte Artikel in einem bestimmten Zeitraum erworben haben. Sie können die Ordner dann für den Newsletter-Versand im Menü <<crm/newsletter-versenden#1000, *CMS » Newsletter*>> verwenden, um Newsletter an diese Kundengruppen zu senden.

Gehen Sie wie im Folgenden beschrieben vor, um Kundendaten in einen E-Mail-Ordner zu kopieren.

[.instruction]
Kundendaten in einen E-Mail-Ordner kopieren:

. Öffnen Sie das Menü *System » CMS » Newsletter » plentymarkets » E-Mail-Filter*.
. Nehmen Sie die Einstellungen im Bereich *Alle Kundendaten in E-Mail-Ordner kopieren* vor. Beachten Sie dazu die Erläuterungen in Tabelle 6.
. Klicken Sie auf *E-Mails in Ordner übertragen*.

.Kundendaten in einen E-Mail-Ordner kopieren
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Newsletter-Anmeldung*
|Eine der folgenden Optionen wählen: +
*ALLE* = Die Kundendaten aller Kunden, die den Newsletter bestellt haben, werden in den E-Mail-Ordner kopiert. Umfasst sowohl Kunden, die den Newsletter-Empfang mit der <<crm/newsletter-versenden#800, *Double-Opt-In-Methode*>> bestätigt haben, als auch Kunden, die dies noch nicht getan haben. +
*Nur Kunden, welche dem Empfang von Newslettern zugestimmt haben* = Nur die Kundendaten von Kunden, die den Newsletter-Empfang bestätigt haben, werden in den E-Mail-Ordner kopiert.

|*Land*
|<<crm/kundendaten-verwalten#1300, *Land*>> wählen, um nur Kunden aus diesem Land zu filtern. Ermöglicht es, z.B. unterschiedliche Newsletter an Kunden in Deutschland und in Österreich zu versenden.

|*E-Mail-Ordner*
|E-Mail-Ordner wählen. Die Kundendaten werden in diesen E-Mail-Ordner kopiert.
|====

[#1500]
=== Kundendaten filtern

Mit dem Kundenfilter filtern Sie Kundendaten noch genauer. Gehen Sie wie im Folgenden beschrieben vor, um Kundendaten zu filtern und in einen E-Mail-Ordner zu kopieren.

[.instruction]
Kundendaten filtern:

. Öffnen Sie das Menü *System » CMS » Newsletter » plentymarkets » E-Mail-Filter*.
. Nehmen Sie die Einstellungen im Bereich *Kundenfilter* vor. Beachten Sie dazu die Erläuterungen in Tabelle 7.
. Klicken Sie auf *Vorschau*, um die Kundendaten anzuzeigen. +
→ Der Bereich *Vorschau* wird mit den Kundendaten eingeblendet. Prüfen Sie das Ergebnis.
. Klicken Sie auf *E-Mails in Ordner übertragen*.

.Einstellungen für den Kundenfilter
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Mindestbestellwert*
|Mindestbestellwert eingeben, um nach Kunden zu filtern, die ab diesem Bestellwert eingekauft haben.

|*Kategorie 1-3*
|Bis zu drei Kategorieebenen wählen, um nach Kunden zu filtern, die Artikel in dieser Kategorie oder Unterkategorie gekauft haben.

|*Artikel-ID*
|Eine oder mehrere Artikel-IDs eingeben, um nach Kunden zu filtern, die diese Artikel gekauft haben.

|*Bestellzeitpunkt*
|Zeitraum eingeben oder Datum aus dem Kalender wählen, um nach Kunden zu filtern, die innerhalb dieses Zeitraums bestellt haben. Wenn kein Datumsfilter angewendet werden soll, die Option *Kein Bestellzeitpunkt* aktivieren.

|*Land*
|<<crm/kundendaten-verwalten#1300, *Land*>> wählen, um nach Kunden aus diesem Land zu filtern. Ermöglicht es, z.B. unterschiedliche Newsletter an Kunden in Deutschland und in Österreich zu versenden.

|*Mandant (Shop)*
|Mandant (Shop) wählen, um nach Kunden zu filtern, die Artikel bei diesem Mandanten (Shop) gekauft haben.

|*Kundenklasse*
|<<crm/kundendaten-verwalten#100, *Kundenklasse*>> wählen, um nach Kunden zu filtern, die dieser Kundenklasse angehören.

|*Auftragsherkunft*
|Auftragsherkunft wählen, um nach Kunden zu filtern, die Bestellungen über diese Auftragsherkunft vorgenommen haben.

|*Newsletter-Anmeldung*
|Zwischen den Optionen *ALLE* und *Nur Kunden, welche dem Empfang von Newslettern zugestimmt haben* wählen. +
*ALLE* = Die Kundendaten aller Kunden, die den Newsletter bestellt haben, werden in den E-Mail-Ordner kopiert. Umfasst sowohl Kunden, die den Newsletter-Empfang mit der <<crm/newsletter-versenden#800, *Double-Opt-In-Methode*>> bestätigt haben, als auch Kunden, die dies noch nicht getan haben. +
*Nur Kunden, welche dem Empfang von Newslettern zugestimmt haben* = Nur die Kundendaten von Kunden, die den Newsletter-Empfang bestätigt haben, werden in den E-Mail-Ordner kopiert.

|*E-Mail-Ordner*
|E-Mail-Ordner wählen. Die Kundendaten werden in diesen E-Mail-Ordner kopiert.
|====

[#1600]
=== Newsletter versenden

Nachdem Sie die <<crm/newsletter-versenden#700, *E-Mail-Vorlage erstellt*>> und <<crm/newsletter-versenden#800, *verknüpft*>> und den <<crm/newsletter-versenden#1000, *Newsletter erstellt*>> haben, können Sie im Menü *CMS » Newsletter* einstellen, an welche der in den E-Mail-Ordnern gespeicherten E-Mail-Adressen der Newsletter gesendet werden soll. Außerdem legen Sie mit der Option *Filter* fest, ob der Newsletter an alle oder nur an bestätigte E-Mail-Adressen gesendet werden soll. Diese Einstellung nehmen Sie im Tab *Newsletter senden* des erstellten Newsletters vor.

[TIP]
.Eingeschränkter Newsletter-Versand am Tag
====
Beachten Sie, dass Ihr Newsletter tagsüber eingeschränkt an Ihre Kunden versendet wird. In der Nacht wird der Versand einer größeren Anzahl von E-Mails erlaubt.

* Am Tag zwischen 8:00 und 0:00 Uhr: 60 E-Mails je Viertelstunde
* Nachts zwischen 0:00 und 8:00 Uhr: 500 E-Mails je Viertelstunde
====

[.instruction]
Newsletter versenden:

. Öffnen Sie das Menü *CMS » Newsletter*.
. Klappen Sie den Newsletter, den Sie versenden wollen, auf.
. Wechseln Sie in das Tab *Newsletter versenden*.
. Wählen Sie unter *Sende Newsletter an Gruppe* eine Gruppe aus dem Dropdown-Menü.
. Wählen Sie unter *Filter* die Option *ALLE* oder die Option *Nur an bestätigte E-Mail-Adressen*.
. Klicken Sie auf *Senden*. +
→ Der Newsletter wird gemäß der oben gewählten Einstellungen versendet.

[#1700]
== Newsletter mit CleverReach versenden

Gehen Sie wie im Folgenden beschrieben vor, um Ihre Newsletter mit link:https://www.cleverreach.de/[*CleverReach*^] an Ihre Kunden zu versenden.

[#1800]
=== Bei CleverReach registrieren

Registrieren Sie sich kostenlos auf der link:https://www.cleverreach.de/[*Website von CleverReach*^], um CleverReach in plentymarkets zu nutzen. Weitere Informationen zu den Einstellungen in CleverReach finden Sie in der link:http://support.cleverreach.de/hc/de[*Hilfe*^] von CleverReach.

[#1900]
=== CleverReach in plentymarkets einrichten

Gehen Sie wie im Folgenden beschrieben vor, um die Schnittstelle zu CleverReach in plentymarkets einzurichten.

[.instruction]
CleverReach in plentymarkets einrichten:

. Öffnen Sie das Menü *System » CMS » Newsletter » CleverReach*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 8.
. Geben Sie Ihren *API-Key* ein.
. Geben Sie die *Listen-ID* der in CleverReach angelegten Gruppe ein.
. *Speichern* Sie die Einstellungen.
. Klicken Sie auf *Standardattribute generieren*. +
→ Datenfelder werden in CleverReach erzeugt, damit die Kundendaten, die Sie übertragen, gespeichert werden.
. Öffnen Sie im CleverReach-Backend die Gruppe, deren ID Sie in plentymarkets eingetragen haben.
. Löschen Sie die Datenfelder, deren Inhalt Sie nicht bei CleverReach verwenden möchten. +
→ Aktuell werden die Datenfelder *Birthday (Geburtstag)*, *Vorname*, *Gender (Anrede)*, *Lang (Sprache)* und *Nachname* von plentymarkets an CleverReach übertragen.
. Wechseln Sie zurück in das Menü *System » CMS » Newsletter » CleverReach* des plentymarkets Backend.
. Aktivieren Sie die Option *Automatische Übertragung (täglich)*, damit die Kundendaten übertragen werden.
. *Speichern* Sie die Einstellungen.

.Einstellungen im Menü *System » CMS » Newsletter » CleverReach*
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Gruppenattribute erzeugen*
|Erzeugt die Datenfelder (Gruppenattribute) für CleverReach.

|*Datenübertragung ausführen*
|Überträgt die Datenfelder (Gruppenattribute) an CleverReach. Aktuell werden die Datenfelder *Birthday (Geburtstag)*, *Vorname*, *Gender (Anrede)*, *Lang (Sprache)* und *Nachname* von plentymarkets an CleverReach übertragen. Bereich aus dem Dropdown-Menü wählen. +
*_Hinweis:_* Vor der Übertragung der eigentlichen Kundendaten ausführen. Dazu Anleitung unten beachten.

|*API-Key*
|API-Key eingeben, wie von CleverReach erhalten.

|*Listen-ID*
|Listen-ID aus CleverReach eingeben.

|*Auftragsherkünfte*
|Auftragsherkünfte wählen, die für CleverReach verfügbar sein sollen. Herkünfte, die keine Datenübertragung gestatten, sind standardmäßig nicht gewählt. +
*_Hinweis:_* Auswahl der Auftragsherkünfte vor der Arbeit mit CleverReach prüfen, um potenzielle Abmahnungen zu vermeiden.

|*Export ab Auftragsstatus*
|Status wählen, ab dem die Daten exportiert werden sollen.

|*Automatische Übertragung (täglich)*
|Aktivieren, wenn Daten täglich automatisch übertragen werden sollen.
|====

[IMPORTANT]
.Erste Übertragung
====
Bei der ersten automatischen Übertragung werden die Kundendaten der in den vorhergehenden 3 Tagen neu erstellten Kunden übertragen. Anschließend werden nur noch die Kundendaten der Kunden übertragen, die seit der letzten Übertragung hinzugekommen sind.
====

Wenn Sie nicht an alle Kunden schreiben möchten, deren Daten Sie zu CleverReach übertragen haben, haben Sie in CleverReach Filtermöglichkeiten. Nähere Informationen hierzu finden Sie auf der Support-Seite von *link:http://support.cleverreach.de/entries/21538892-wie-kann-ich-meine-empfanger-filtern[CleverReach^]*.

[#2000]
=== Kundendaten manuell übertragen

Mit der Option *Datenübertragung ausführen* werden nur die Kundendaten eines bestimmten Kundentyps übertragen. Dies bietet die Möglichkeit, die Kundentypen in separate Gruppen bei CleverReach einzuordnen.

[IMPORTANT]
.Automatische Übertragung sinnvoll?
====
Wenn Sie die Option *Datenübertragung ausführen* nutzen, um die Kundendaten gefiltert nach Kundentyp zu übertragen, sollten Sie überlegen, ob die automatische Übertragung noch sinnvoll für Sie ist, da bei dieser Option unabhängig vom Kundentyp übertragen wird.
====

[.instruction]
Kundendaten manuell übertragen:

. Öffnen Sie das Menü *System » CMS » Newsletter » CleverReach*.
. Geben Sie Ihren *API-Key* ein.
. Geben Sie die *Listen-ID* der in CleverReach angelegten Gruppe ein.
. *Speichern* Sie die Einstellungen.
. Klicken Sie auf *Standardattribute generieren*. +
→ Datenfelder werden in CleverReach erzeugt, damit die Kundendaten, die Sie übertragen, gespeichert werden.
. Öffnen Sie im CleverReach-Backend die Gruppe, deren ID Sie in plentymarkets eingegeben haben.
. Löschen Sie die Datenfelder, deren Inhalt Sie nicht bei CleverReach verwenden möchten. +
→ Aktuell werden die Datenfelder *Birthday (Geburtstag)*, *Vorname*, *Gender (Anrede)*, *Lang (Sprache)* und *Nachname* von plentymarkets an CleverReach übertragen.
. Wechseln Sie zurück in das Menü *System » CMS » Newsletter » CleverReach* des plentymarkets Backend.
. Wählen Sie aus dem Dropdown-Menü *Datenübertragung ausführen* den Kundentyp.
. *Speichern* Sie die Einstellungen.
. Klicken Sie auf *Exportieren*. +
→ Die Kundendaten werden übertragen.

[#2100]
== Newsletter mit Newsletter2Go versenden

Gehen Sie wie im Folgenden beschrieben vor, um Newsletter mit link:http://www.newsletter2go.de[*Newsletter2Go*^] an Ihre Kunden zu senden.

[TIP]
.SOAP-Modul notwendig für Nutzung von Newsletter2Go
====
Beachten Sie, dass Sie das SOAP-Modul benötigen, um den Dienst von Newsletter2Go zu nutzen. Das SOAP-Modul ermöglicht den korrekten Abruf der Daten.
====

[#2200]
=== Bei Newsletter2Go registrieren

Registrieren Sie sich zunächst kostenlos auf der link:https://www.newsletter2go.de/registrierung[*Website von Newsletter2Go*^], um Newsletter2Go in plentymarkets zu nutzen. Weitere Informationen zu den Einstellungen in Newsletter2Go finden Sie in der link:https://www.newsletter2go.de/hilfe/[*Hilfe*^] von Newsletter2Go.

[#2300]
=== Benutzer erstellen

Erstellen Sie im Menü <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#10, *System » Einstellungen » Benutzer » Konten*>> einen neuen Benutzer für Newsletter2Go. Diesen Benutzer benötigen Sie für die Nutzung der Schnittstelle zu Newsletter2Go. Mit dem Erstellen des Benutzers mit der Benutzerklasse *Newsletter2Go* sind automatisch alle notwendigen Berechtigungen für die SOAP-API gespeichert wie z.B. die Einstellung *Customer* für die Empfängersynchronisierung sowie die Einstellung *Item* für die Artikelübernahme.

[.instruction]
Benutzer erstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Klicken Sie auf *Neu*.
. Geben Sie einen *Benutzernamen* ein.
. Geben Sie einen *Realen Namen* ein.
. Wählen Sie für *Benutzerklasse* die Option *Newsletter2Go* aus dem Dropdown-Menü.
. Geben Sie ein *Passwort* (zweimal) ein.
. *Speichern* Sie die Einstellungen.

[#2400]
=== Benutzer einrichten

Im nächsten Schritt richten Sie den neuen Benutzer für Newsletter2Go ein.

[.instruction]
Benutzer einrichten:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Konten*.
. Öffnen Sie den soeben erstellten Newsletter2Go-Benutzer.
. Wechseln Sie in das Tab *Berechtigung*.
. Aktivieren Sie im Tab *Sichtbarkeiten* im Bereich *Mandanten (Shops)* den bzw. die Mandanten (Shops).
. *Speichern* Sie die Einstellungen.

[TIP]
.Newsletter über dedizierte IP-Adresse versenden
====
Newsletter2Go bietet Ihnen die Möglichkeit, Newsletter über eine link:https://www.newsletter2go.de/features/newsletter-versand-dedizierte-ips/[*dedizierte IP-Adresse*^] zu versenden. Um dieses Angebot zu nutzen, speichern Sie im Service-Center im Menü *Start » Service-Center* für die Subdomains den <<basics/arbeiten-mit-plentymarkets/plentymarkets-konto#domain-nameserver, *Nameserver*>> von Newsletter2Go. Die erforderlichen Informationen zu Subdomains und Nameserver erhalten Sie von Newsletter2Go.
====
