= Newsletter versenden
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Double-Opt-In-Funktion, Double-opt, double opt, double oppt, Email Vorlage, E-Mail Vorlage, Newsletter Vorlage, Sichtbarkeit Newsletter, E-Mail-Vorlage, E-Mail-Ordner, Newsletter-Zugangsdaten, CleverReach,
:description: Erfahre, wie du Newsletter über plentymarkets an deine Kunden versendest.
:position: 40
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:url: crm/newsletter-versenden
:id: JIHLVCR

Auf dieser Handbuchseite ist beschrieben, welche Einstellungen du vornehmen musst, um Newsletter mit plentymarkets zu versenden. Versende deine Newsletter z.B. mit dem in plentymarkets <<crm/newsletter-versenden#100, integrierten Newsletter-Dienst>>, über die integrierte Schnittstelle zu <<crm/newsletter-versenden#1700, CleverReach>> oder übere weitere im link:https://marketplace.plentymarkets.com/plugins/integration[plentyMarketplace^] verfügbare E-Mail-Marketing- und Newsletter-Plugins.

[#100]
== In plentymarkets integrierten Newsletter-Dienst einrichten

In den folgenden Unterkapiteln erfährst du, wie du den in plentymarkets integrierten Newsletter-Dienst einrichtest.

[TIP]
.Double-Opt-In-Methode
====
In plentymarkets wird die Double-Opt-In-Methode verwendet, d.h. der Empfänger erhält nach Bestellung des Newsletters eine E-Mail mit einem Bestätigungslink. Erst nachdem der Kunde auf den Link geklickt hat, ist der Kunde für den Newsletter angemeldet. Diese Methode ist fest integriert und kann nicht geändert werden.
====

[#200]
=== Newsletter-Zugangsdaten eingeben

Im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Newsletter* gibst du die Zugangsdaten ein, um den in plentymarkets integrierten Newsletter-Dienst zu nutzen.

[.instruction]
Newsletter-Zugangsdaten eingeben:

. Öffne das Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Newsletter*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-newsletter-zugangsdaten>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-newsletter-zugangsdaten]]
.Einstellungen im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Newsletter*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name des Absenders*
|Eigenen Namen oder Name des Webshops eingeben. Der Name wird dem Empfänger angezeigt.

|*E-Mail-Adresse*
|E-Mail-Adresse eingeben, wie sie auch im E-Mail-Programm steht. Über diese E-Mail-Adresse wird der Newsletter versendet.

|*Postausgangsserver / SMTP-Server*
|Postausgangsserver wie vom Provider angegeben eingeben (meist smtp.domain.de oder mail.domain.de). +
*_mailbox.org:_* Für Postfächer bei mailbox.org den Postausgangsserver *smtp.mailbox.org* eingeben und unter *Verschlüsselung* die Einstellung *SSL* wählen.

|*Benutzername*
|Benutzername zu der E-Mail-Adresse eingeben. +
*_mailbox.org:_* Der mailbox.org-Benutzername ist die vollständige E-Mail-Adresse des mailbox.org-Postfachs.

|*Passwort*
|Passwort zu dem Benutzername und der E-Mail-Adresse eingeben.

|*Port (Standardport: 25)*
|Wert *25* eingeben. Dieser Wert ist für fast alle Provider korrekt. Ggf. den korrekten Port beim Provider erfragen. +
*_mailbox.org:_* Für Postfächer bei mailbox.org den Port *465* eingeben und unter *Verschlüsselung* die Einstellung *SSL* wählen.

|*Verschlüsselung*
|*SSL*, *TLS* oder *keine Verschlüsselung* wählen. +
*_mailbox.org:_* Für Postfächer bei mailbox.org die Einstellung *SSL* wählen. +
Weitere Informationen siehe Kapitel <<crm/e-mails-versenden#200, Verschlüsselung der E-Mail-Kommunikation wählen>> auf der Handbuchseite <<crm/e-mails-versenden#, E-Mails versenden>>.
|====

[#300]
=== E-Mail-Ordner erstellen

Im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner* erstellst du Ordner für den Versand von Newslettern. In diesen Ordnern speicherst du dann die E-Mail-Adressen deiner Kunden. Dies ermöglicht den Versand von Newslettern auf bestimmte Zielgruppen. Gehe wie im Folgenden beschrieben vor, um einen neuen E-Mail-Ordner zu erstellen.

[.instruction]
E-Mail-Ordner erstellen:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner*.
. Gib im Bereich *Neuen E-Mail-Ordner anlegen* einen Namen für den Ordner ein.
. Ändere ggf. die ID des Ordners.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-e-mail-ordner-erstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der E-Mail-Ordner wird erstellt und in der Übersicht angezeigt.

[[tabelle-e-mail-ordner-erstellen]]
.Einstellungen im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|Wird beim Erstellen eines neuen Ordners fortlaufend vergeben. Die Ordner-ID kann beim Erstellen eines neuen Ordners geändert werden. Die ID *0* kann nicht vergeben werden. +
*_Hinweis:_* Eindeutige ID vergeben. Wird eine bereits bestehende ID eingegeben, wird der ursprüngliche Ordner überschrieben.

|*Bezeichnung*
|Name des E-Mail-Ordners. Wird die Option *Auswählbar durch Kunden* aktiviert, ist der Name für Kunden im Webshop sichtbar.

|*Auswählbar durch Kunden*
|Aktivieren, wenn der Ordner von Kunden im Webshop gewählt werden soll. Der Ordner wird im Bereich *Mein Konto* des Webshops angezeigt. Kunden wählen dann Newsletter anhand der dort verfügbaren Ordner.

|*Position*
|Position eingeben, um festzulegen, in welcher Reihenfolge die Ordner angezeigt werden sollen.

|*Sichtbarkeit*
|Festlegen, ob der Newsletter-Ordner nur für den Standard-Webshop oder für alle Webshops sichtbar sein soll. Mit *Keiner* wird die Sichtbarkeit des Ordners deaktiviert.

|*Löschen*
|Aktivieren und auf *Speichern* klicken, um den Ordner zu löschen.
|====

[#400]
=== E-Mail-Ordner bearbeiten

Bestehende E-Mail-Ordner bearbeitest du ebenfalls im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner*. Gehe wie im Folgenden beschrieben vor, um die Einstellungen eines E-Mail-Ordners zu bearbeiten.

[.instruction]
E-Mail-Ordner bearbeiten:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Ordner*.
. Nimm die Änderungen vor. Beachte dazu die Erläuterungen in <<tabelle-e-mail-ordner-erstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#500]
=== E-Mail-Adressen dem Newsletter-Hauptordner zuordnen

Im Menü <<webshop/webshop-einrichten/bestellvorgang#, Einrichtung » Mandant » Mandant wählen » Bestellvorgang » Einstellungen>> wählst du über die Dropdown-Liste *Newsletter-Hauptordner* den E-Mail-Ordner für Newsletter, der automatisch mit der E-Mail-Adresse eines Kunden verknüpft wird, wenn der Kunde den Newsletter während des Bestellvorgangs im Webshop abonniert. Alle sichtbaren E-Mail-Ordner sind in der Dropdown-Liste aufgelistet. Beachte dazu auch die Erläuterung zur Option *Sichtbarkeit* in <<tabelle-e-mail-ordner-erstellen>>.

[#600]
=== Newsletter-Wahl für Kunden erlauben

Lasse deine Kunden selbst bestimmen, welche Newsletter sie von dir erhalten. Das ist z.B. von Vorteil, wenn du regelmäßig Newsletter zu verschiedenen Themenbereichen versendest. Deine Kunden können alle E-Mail-Ordner, die du unter der Option *Auswählbar durch Kunden* in <<tabelle-e-mail-ordner-erstellen>> aktiviert hast, im Bereich *Mein Konto* des Webshops wählen. Die E-Mail-Adresse des Kunden wird dann in diesem E-Mail-Ordner in deinem plentymarkets System gespeichert.

[#700]
=== E-Mail-Vorlage erstellen

Versende deine Bestätigungs-E-Mail per E-Mail-Vorlage. Nutze Template-Variablen, damit die Vorlage beim Versenden automatisch den richtigen Namen des Kunden sowie den Bestätigungslink enthält. Gehe wie im Folgenden beschrieben vor, um die E-Mail-Vorlage zu erstellen.

[IMPORTANT]
.Template-Variablen und Template-Funktionen beachten
====
In plentymarkets steht dir eine umfangreiche Auswahl an Template-Variablen und Template-Funktionen für deine E-Mail-Vorlagen zur Verfügung. Öffne die E-Mail-Vorlage und klicke auf *Template-Variablen -und Funktionen* (icon:code[role="blue"]). Kopiere aus diesem Bereich die Template-Variable bzw. Template-Funktion und füge diese in der E-Mail-Vorlage im Tab *E-Mail-Nachricht* in den reinen Text oder in den HTML-formatierten Text an der gewünschten Stelle ein.

Weitere Informationen findest du auf der Handbuchseite <<crm/e-mails-versenden#, E-Mails versenden>>.
====

[.instruction]
E-Mail-Vorlage erstellen:

. Öffne das Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Vorlagen*.
. Klicke auf *Neue E-Mail-Vorlage* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue E-Mail-Vorlage* wird geöffnet.
. Gib den Namen für die E-Mail-Vorlage ein.
. Wähle einen Eigner aus der Dropdown-Liste.
. Klicke auf *Speichern* (icon:save[role="green"]). +
→ Die E-Mail-Vorlage wird erstellt und abhängig von der gewählten Einstellung in der Dropdown-Liste *Eigner* in einem der 3 Ordner gespeichert. Beachte dazu die Erläuterung zu *Eigner* in <<tabelle-e-mail-vorlage-erstellen>>.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-e-mail-vorlage-erstellen>>.
. Füge die Template-Variable *$CustomerFullName* in den Text der E-Mail ein. +
→ Diese Template-Variable gibt den Vornamen und den Nachnamen des Kunden aus.
. Füge die Template-Variable *$NewsletterConfirmURL* in den Text der E-Mail ein. +
→ Diese Template-Variable gibt den Bestätigungslink aus.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Klickt der Empfänger der E-Mail auf den durch die Template-Variable *$NewsletterConfirmURL* eingefügten Link, bestätigt der Empfänger die Anmeldung zum Newsletter und erhält ab sofort Newsletter an diese E-Mail-Adresse.

Wenn du die <<crm/newsletter-versenden#800, Double-Opt-In-Methode>> verwenden möchtest, ist ein weiterer Schritt notwendig. Du musst jeweils eine Vorlage erstellt haben und diese im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Automatischer Versand* für die Ereignisse *Newsletter Opt-In* und *Bestätigung Newsletter Opt-In* gewählt haben.


[[tabelle-e-mail-vorlage-erstellen]]
.Neue E-Mail-Vorlage im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Vorlagen* erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Speichern*
|Speichert (icon:save[role="green"]) die Einstellungen in der E-Mail-Vorlage.

|*Template-Variablen -und Funktionen*
|Mit einem Klick auf icon:code[role="blue"] wird der Bereich *Template-Variablen -und Funktionen* geöffnet, aus dem die Template-Variablen bzw. Template-Funktionen für die E-Mail-Vorlage kopiert werden.

2+|*Tab: Einstellungen*

|*Eigner*
|Wenn der Name des Eigners bereits beim Erstellen aus der Dropdown-Liste gewählt wurde, wird hier der Name des Eigners angezeigt. Andernfalls Eigner aus der Dropdown-Liste wählen. Diese Einstellung kann jederzeit geändert werden. +
*Alle* = Die Vorlage wird unter *Allgemeine E-Mail-Vorlagen* gespeichert. +
Eigener Benutzername = Die Vorlage wird unter *Meine E-Mail-Vorlagen* gespeichert. +
Anderer Benutzername = Die Vorlage wird unter *E-Mail-Vorlagen anderer Benutzer* gespeichert. +
*_Hinweis:_* Um eine eigene E-Mail-Vorlage unter *Meine E-Mail-Vorlagen* zu erstellen, muss man als Benutzer im System eingeloggt sein.

|*Name*
|Wenn der Name der E-Mail-Vorlage bereits beim Erstellen eingegeben wurde, wird hier der Name der E-Mail-Vorlage angzeigt. Andernfalls Namen eingeben, unter dem diese Vorlage gespeichert werden soll. +
Der Name kann jederzeit geändert werden. Der Name wird dem Empfänger nicht angezeigt.

|*Inhalt*
|Wählen, ob die Nachricht als *reiner Text* oder als *HTML-formatierte Nachricht* gespeichert werden soll.

|*Template-Typ*
|Wählen, in welchem Bereich die E-Mail-Vorlage als Auswahl zur Verfügung steht. Mögliche Optionen: *Alle* (Standardeinstellung), *Auftrag*, *Kunden*, *Webshop*, *Ticket* oder *Scheduler*. +
*Alle* / *Webshop* = Die E-Mail-Vorlage steht in allen Bereichen als Auswahl zur Verfügung. +
*Auftrag* = Die E-Mail-Vorlage steht ausschließlich für den gewählten Bereich als Auswahl zur Verfügung. Die Vorlage ist in anderen Bereichen nicht sichtbar. Wenn das Ticket mit einem Auftrag verknüpft ist, sind E-Mail-Vorlagen mit dem Template-Typ *Auftrag* ebenfalls im Ticket wählbar. +
*Kunden* = Die E-Mail-Vorlage steht ausschließlich für den gewählten Bereich als Auswahl zur Verfügung. Die Vorlage ist in anderen Bereichen nicht sichtbar. +
*Ticket* = Die E-Mail-Vorlage steht ausschließlich für den gewählten Bereich als Auswahl zur Verfügung. Die Vorlage ist in anderen Bereichen nicht sichtbar. +
*Scheduler* = Die E-Mail-Vorlage steht in allen Bereichen, in denen auch der Template-Typ *Auftrag* sichtbar ist, als Auswahl zur Verfügung.

|*PDF-Anhang*
|Anhang aus der Dropdwon-Liste wählen. Die Dokumente, die hier in der Dropdown-Liste zur Verfügung stehen, werden u.a. im Menü *Aufträge » Fulfillment* oder durch versandbezogene Prozesse erzeugt.

|*Dokumentenanhang*
|Auf Wunsch unter *CMS » Dokumente* hochgeladene eigene Dokumente wählen, die an eine E-Mail-Vorlage anhängt werden sollen. +
 Alle E-Mail-Vorlagen können mit bis zu 2 Anhängen standardisiert an Kunden versendet werden: PDF-Dokumente aus dem Bereich Fulfillment (z.B. Rechnungen) oder andere Dateien (z.B. ein Artikelprospekt oder eine Anleitung). Für die Vorlage *Eingangsbestätigung Webshop Bestellung* wären z.B. die Widerrufsbelehrung und die AGB im PDF-Format eine sinnvolle Ergänzung.

|*Antwort an*
|E-Mail-Adresse eingeben, an die die Antworten auf diese E-Mail-Vorlage gesendet werden sollen. Wenn keine E-Mail-Adresse eingegeben ist, werden Antworten auf diese Vorlage standardmäßig an die unter <<crm/e-mails-versenden#100, Einrichtung » Mandant » Mandant wählen » E-Mail » Zugangsdaten>> gespeicherte E-Mail-Adresse versendet. Beispielsweise ist es sinnvoll, die E-Mail-Adresse der Buchhaltungsabteilung für die E-Mail-Vorlage *PDF-Rechnung* einzugeben. So gehen z.B. Rückfragen zur Rechnung direkt an die Buchhaltungsabteilung und müssen nicht weitergeleitet werden.

|*Design verwenden*
|Aktivieren, wenn der Inhalt der E-Mail mit dem im Menü <<crm/e-mails-versenden#800, Einrichtung » Mandant » Mandant wählen » E-Mail » HTML-Design>> gespeicherten Design versendet werden soll. Wird die Option nicht aktiviert, wird nur der Inhalt der E-Mail-Vorlage verwendet.

|*Mandant (Shop)*
|Einen, mehrere oder *ALLE* Mandanten (Shops) aktivieren. Die E-Mail-Vorlage ist nur für die gewählten Mandanten (Shops) gültig.

2+|*Tab: E-Mail-Nachricht*

|*Sprache wählen*
|Die Sprache wird hier angezeigt und kann geändert werden.

|*Betreff*
|Betreff eingeben. Dabei den Betreff mit großer Sorgfalt wählen, damit die E-Mails im Postfach des Kunden leicht erkennbar sind und nicht dem Spam-Filter zum Opfer fallen.

|*Inhalt / Artikelliste*
|In diese Tabs den Text bzw. die Artikelauflistung als *reinen Text* oder als *HTML-formatierten Text* eingeben. Für den Inhalt stehen verschiedene Template-Variablen und Template-Funktionen zur Verfügung. +
*_Hinweis:_* Nur der Inhalt des Tabs, dessen Inhaltstyp im Tab *Einstellungen* unter *Inhalt* festgelegt wurde, wird berücksichtigt. Wenn dort also z.B. *Nur reiner Text* eingestellt wurde, jedoch nur das Tab *HTML-formatierter Text* Inhalt enthält, wird keine E-Mail versendet.
|====

[#800]
=== E-Mail-Vorlagen mit der Double-Opt-In-Funktion verknüpfen

Im nächsten Schritt verknüpfst du die soeben erstellte E-Mail-Vorlage mit der Double-Opt-In-Funktion und wählst eine weitere Vorlage für das Ereignis *Bestätigung Newsletter Opt-In*. Bei der Double-Opt-In-Methode muss der Kunde nach Anmeldung zum Newsletter die Newsletter-Anmeldung in einem zweiten Schritt bestätigen.

[TIP]
.Hinweise zur Double-Opt-In-Methode
====
Wähle im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Automatischer Versand* 2 <<crm/newsletter-versenden#700, zuvor erstellte>> Vorlagen für die Ereignisse *Newsletter Opt-In* und *Bestätigung Newsletter Opt-In*. Die gewählte Vorlage unter *Newsletter Opt-In* wird versendet, wenn der Kunde sich für deinen Newsletter anmeldet. Diese Vorlage sollte den Bestätigungslink enthalten, den der Kunde anklicken muss, um die Newsletter-Anmeldung abzuschließen. Den Bestätigungslink bildest du mit der Template-Variable *$NewsletterConfirmURL*, die die URL zur Bestätigung der Newsletter-Anmeldung beinhaltet, ab. Die gewählte Vorlage unter *Bestätigung Newsletter Opt-In* wird versendet, sobald der Kunde den Bestätigungslink aktiviert hat.

Im Kontaktdatensatz im Menü *CRM » Kontakte » Kontakt öffnen* wird die Option *Newsletter* automatisch aktiviert, wenn der Kunde sich im Bestellvorgang für den Newsletter angemeldet und die Newsletter-Anmeldung über den Bestätigungslink bestätigt hat.
====

[.instruction]
E-Mail-Vorlagen mit der Double-Opt-In-Funktion verknüpfen:

. Öffne das Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Automatischer Versand*.
. Wähle für die Option *Newsletter Opt-In* die soeben erstellte E-Mail-Vorlage aus der Dropdown-Liste.
. Wähle für die Option *Bestätigung Newsletter Opt-In* die E-Mail-Vorlage aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Den Status der Bestätigung siehst du im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails*. Bei Kunden, die den Newsletter-Bezug nach der vorstehend beschriebenen Vorgehensweise bestätigt haben, ist dies am Status *[green]#bestätigt#* zu erkennen. Bei Kunden, die das Double-Opt-in nicht durchgeführt haben, steht dort *[red]#nicht bestätigt#*.

Die *IP-Adresse* und die verwendete *Bestätigungs-URL* einer Bestätigung werden in der Datenbank gespeichert. Diese Daten lassen sich anschließend über einen link:https://developers.plentymarkets.com/rest-doc/newsletter/details#list-a-recipient[REST-Call^] holen. Im Backend erfolgt keine Anzeige.

[#900]
=== E-Mail-Adresse speichern

E-Mail-Adressen für den Versand von Newslettern werden in verschiedenen Ordnern gespeichert. Im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails* verwaltest du die E-Mail-Adressen der verfügbaren Ordner. Falls du noch keine <<crm/newsletter-versenden#300, Ordnerstruktur>> für deine Newsletter angelegt hast, empfiehlt es sich, dies vorab zu tun.

Gehe wie im Folgenden beschrieben vor, um eine E-Mail-Adresse in einem E-Mail-Ordner zu speichern.

[.instruction]
E-Mail-Adresse speichern:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails*.
. Klappe den Ordner auf (icon:plus-square-o[]).
. Klappe den Bereich *Neue E-Mail-Adresse* (icon:plus-square-o[]) auf.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-e-mail-adresse-speichern>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-e-mail-adresse-speichern]]
.Einstellungen zum Speichern einer neuen E-Mail-Adresse
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Vorname*
|Vorname des Kunden eingeben.

|*Nachname*
|Nachname des Kunden eingeben.

|*E-Mail*
|E-Mail-Adresse des Kunden eingeben.

|*Ordner*
|<<crm/newsletter-versenden#300, E-Mail-Ordner>> wählen, in dem die Kundendaten gespeichert werden sollen.
|====

[#1000]
=== Newsletter erstellen

Neue Newsletter erstellst du wie im Folgenden beschrieben. Du kannst so auch bestehende Newsletter bearbeiten.

[.instruction]
Newsletter erstellen:

. Öffne das Menü *CRM » Newsletter*.
. Klappe den Bereich *Neuer Newsletter* (icon:plus-square-o[]) auf. +
→ Das Bearbeitungsfenster für den neuen Newsletter wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-newsletter-erstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-newsletter-erstellen]]
.Einstellungen zum Erstellen eines Newsletters
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Platzhalter*
|Listet auf, welche Platzhalter vom System erkannt und in der Nachricht ersetzt werden. +
Aktuell mögliche Platzhalter: +
*+[NAME]+* = Vorname und Nachname des Empfängers +
*+[EMAIL]+* = E-Mail-Adresse des Empfängers +
*+[RECIPIENTID]+* = ID des Empfängers +
//*+[FOLDERID]+* = ID des Newsletter-Ordners

|*Bildergalerie*
|Öffnet das Menü <<webshop/webshop-einrichten/cms#bilder-galerie, CMS » Bilder-Galerie>>. Hier ein Bild hochladen, um es mit dem Newsletter zu verknüpfen.

|*Layout-Vorlage einspielen*
|Bei Klick auf *Layout-Vorlage einspielen* wird die Anrede *[Guten Tag]* sowie der Platzhalter *[NAME]* im Bereich *HTML Newsletter* eingesetzt. Für den Platzhalter wird beim Versenden automatisch der Name des Kunden eingefügt.

|*Betreff*
|Betreff für den Newsletter eingeben.

|*Editor*
|Der *CKEditor* ist vorausgewählt. Ggf. anderen Editor aus der Dropdown-Liste wählen.

|*HTML Newsletter*
|Inhalt des Newsletters als HTML-Code eingeben. +
*_Hinweis:_* Texte werden nur in einem Bereich gespeichert. Daher entweder im Bereich *HTML Newsletter* oder im Bereich *Text Newsletter* Inhalte eingeben.

|*Text Newsletter*
|Inhalt des Newsletters in reiner Textform eingeben. +
*_Hinweis:_* Texte werden nur in einem Bereich gespeichert. Daher entweder im Bereich *HTML Newsletter* oder im Bereich *Text Newsletter* Inhalte eingeben.

|====

[#1100]
=== Kunden anhand der E-Mail-Adresse oder des Nachnamen suchen

Gehe wie im Folgenden beschrieben vor, um eine E-Mail-Adresse in einem E-Mail-Ordner zu suchen. Suche Kunden entweder anhand der E-Mail-Adresse oder des Nachnamens.

[.instruction]
Kunden anhand der E-Mail-Adresse oder des Nachnamen suchen:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails*.
. Klappe den E-Mail-Ordner auf (icon:plus-square-o[]).
. Wähle aus der Dropdown-Liste die Einstellung *E-Mail-Adresse* oder *Nachname*, um anhand dieser Einstellung zu suchen.
. Gib die E-Mail-Adresse bzw. den Nachnamen des Kunden in das Suchfeld ein.  +
→ Für die Suche ist es ausreichend, wenn du nur einen Teil des Namens oder der E-Mail-Adresse eingibst. Lasse das Feld leer, um alle E-Mail-Adressen bzw. Nachnamen anzuzeigen.
. Klicke auf *Suche* (icon:search[role="blue"]). +
→ Das Suchergebnis wird angezeigt.

Im Suchergebnis wird auch der Status der Bestätigung angezeigt. In plentymarkets wird die <<crm/newsletter-versenden#800, Double-Opt-In-Methode>> verwendet. Dabei erhalten Empfänger nach dem Bestellen des Newsletters eine E-Mail mit einem Link, über den sie die Newsletter-Bestellung bestätigen müssen. Kunden, die den Newsletter-Bezug so bestätigt haben, erkennst du an dem Status *bestätigt*. Andernfalls steht dort *nicht bestätigt*.

[#1200]
=== E-Mail-Adresse bearbeiten

Nachdem du eine E-Mail-Adresse über die Suchfunktion gefunden hast, kannst du die Daten für diesen Kunden bearbeiten. Ändere z.B. die E-Mail-Adresse des Kunden oder verschiebe den Kontaktdatensatz in einen anderen E-Mail-Ordner. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
E-Mail-Adresse bearbeiten:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mails*.
. Suche den Kunden wie im Kapitel <<crm/newsletter-versenden#1100, Kunden anhand der E-Mail-Adresse oder des Nachnamen suchen>> beschrieben.
. Klappe den Kunden auf (icon:plus-square-o[]).
. Nimm die Änderungen vor. Beachte dazu die Erläuterungen in <<tabelle-e-mail-adresse-speichern>> im Kapitel <<crm/newsletter-versenden#900, E-Mail-Adresse speichern>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#1300]
=== E-Mail-Adressen exportieren und importieren

In den vorigen Kapiteln ist beschrieben, wie du eine einzelne E-Mail-Adresse verwaltest. Wenn du mehrere E-Mail-Adressen gleichzeitig bearbeiten möchtest, ist es sinnvoll, mit dem <<daten/daten-importieren/ElasticSync#, ElasticSync>> zu arbeiten. Importiere neue und bearbeite bestehende E-Mail-Adressen mit dem Sync-Typ <<daten/daten-importieren/sync-typen/elasticSync-newsletter-empfaenger#, Newsletter-Empfänger>>.

Du kannst die E-Mail-Adressen auch exportieren. Erstelle dazu im Menü <<daten/daten-exportieren/FormatDesigner#, Daten » FormatDesigner>> zunächst das Exportformat und exportiere die Daten anschließend über den <<daten/daten-exportieren/elastischer-export#, elastischen Export>>.

[#1400]
=== Kundendaten in einen E-Mail-Ordner kopieren

Im Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Filter* filterst du nach Kundendaten und kopierst die E-Mail-Adressen dieser Kunden in bestimmte E-Mail-Ordner. Du hast z.B. die Möglichkeit, nach Kunden zu suchen, die bestimmte Artikel in einem bestimmten Zeitraum erworben haben. Verwende die Ordner dann für den Newsletter-Versand im Menü <<crm/newsletter-versenden#1000, CRM » Newsletter>>, um Newsletter an diese Kundengruppen zu senden.

Gehe wie im Folgenden beschrieben vor, um Kundendaten in einen E-Mail-Ordner zu kopieren.

[.instruction]
Kundendaten in einen E-Mail-Ordner kopieren:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Filter*.
. Nimm die Einstellungen im Bereich *Alle Kundendaten in E-Mail-Ordner kopieren* vor. Beachte dazu die Erläuterungen in <<tabelle-kundendaten-kopieren>>.
. Klicke auf *E-Mails in Ordner übertragen* (icon:cog[]).

[[tabelle-kundendaten-kopieren]]
.Kundendaten in einen E-Mail-Ordner kopieren
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Newsletter-Anmeldung*
|Eine der folgenden Optionen wählen: +
*ALLE* = Die Kundendaten aller Kunden, die den Newsletter bestellt haben, werden in den E-Mail-Ordner kopiert. Umfasst sowohl Kunden, die den Newsletter-Empfang mit der <<crm/newsletter-versenden#800, Double-Opt-In-Methode>> bestätigt haben, als auch Kunden, die dies noch nicht getan haben. +
*Nur Kunden, welche dem Empfang von Newslettern zugestimmt haben* = Nur die Kundendaten von Kunden, die den Newsletter-Empfang bestätigt haben, werden in den E-Mail-Ordner kopiert.

|*Land*
|Land wählen, um nur Kunden aus diesem Land zu filtern. Ermöglicht es, z.B. unterschiedliche Newsletter an Kunden in Deutschland und in Österreich zu versenden.

|*E-Mail-Ordner*
|E-Mail-Ordner wählen. Die Kundendaten werden in diesen E-Mail-Ordner kopiert.
|====

[#1500]
=== Kundendaten filtern

Mit dem Kundenfilter filterst du Kundendaten noch genauer. Gehe wie im Folgenden beschrieben vor, um Kundendaten zu filtern und in einen E-Mail-Ordner zu kopieren.

[.instruction]
Kundendaten filtern:

. Öffne das Menü *Einrichtung » CRM » Newsletter » plentymarkets » E-Mail-Filter*.
. Nimm die Einstellungen im Bereich *Kundenfilter* vor. Beachte dazu die Erläuterungen in <<tabelle-kundendaten-filtern>>.
. Klicke auf *Vorschau* (icon:eye[role="blue"]), um die Kundendaten anzuzeigen. +
→ Der Bereich *Vorschau* wird mit den Kundendaten eingeblendet. Prüfe das Ergebnis.
. Klicke auf *E-Mails in Ordner übertragen* (icon:cog[]).

[[tabelle-kundendaten-filtern]]
.Einstellungen für den Kundenfilter
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Mindestbestellwert*
|Mindestbestellwert eingeben, um nach Kunden zu filtern, die ab diesem Bestellwert eingekauft haben.

|*Kategorie 1-3*
|Bis zu 3 Kategorieebenen wählen, um nach Kunden zu filtern, die Artikel in dieser Kategorie oder Unterkategorie gekauft haben.

|*Artikel-ID*
|Eine oder mehrere Artikel-IDs eingeben, um nach Kunden zu filtern, die diese Artikel gekauft haben.

|*Bestellzeitpunkt*
|Zeitraum eingeben oder Datum aus dem Kalender wählen, um nach Kunden zu filtern, die innerhalb dieses Zeitraums bestellt haben. Wenn kein Datumsfilter angewendet werden soll, die Option *Kein Bestellzeitpunkt* aktivieren.

|*Land*
|Land wählen, um nur Kunden aus diesem Land zu filtern. Ermöglicht es, z.B. unterschiedliche Newsletter an Kunden in Deutschland und in Österreich zu versenden.

|*Mandant (Shop)*
|Mandant (Shop) wählen, um nach Kunden zu filtern, die Artikel bei diesem Mandanten (Shop) gekauft haben.

|*Kundenklasse*
|<<crm/kontakte-verwalten#15, Kundenklasse>> wählen, um nach Kunden zu filtern, die dieser Kundenklasse angehören.

|*Auftragsherkunft*
|Auftragsherkunft wählen, um nach Kunden zu filtern, die Bestellungen über diese Auftragsherkunft vorgenommen haben.

|*Newsletter-Anmeldung*
|Zwischen den Optionen *ALLE* und *Nur Kunden, welche dem Empfang von Newslettern zugestimmt haben* wählen. +
*ALLE* = Die Kundendaten aller Kunden, die den Newsletter bestellt haben, werden in den E-Mail-Ordner kopiert. Umfasst sowohl Kunden, die den Newsletter-Empfang mit der <<crm/newsletter-versenden#800, Double-Opt-In-Methode>> bestätigt haben, als auch Kunden, die dies noch nicht getan haben. +
*Nur Kunden, welche dem Empfang von Newslettern zugestimmt haben* = Nur die Kundendaten von Kunden, die den Newsletter-Empfang bestätigt haben, werden in den E-Mail-Ordner kopiert.

|*E-Mail-Ordner*
|E-Mail-Ordner wählen. Die Kundendaten werden in diesen E-Mail-Ordner kopiert.
|====

[#1600]
=== Newsletter versenden

Nachdem du die <<crm/newsletter-versenden#700, E-Mail-Vorlage erstellt>> und <<crm/newsletter-versenden#800, verknüpft>> und den <<crm/newsletter-versenden#1000, Newsletter erstellt>> hast, stellst du im Menü *CRM » Newsletter* ein, an welche der in den E-Mail-Ordnern gespeicherten E-Mail-Adressen der Newsletter gesendet werden soll. Außerdem legst du mit der Option *Filter* fest, ob der Newsletter an alle oder nur an bestätigte E-Mail-Adressen gesendet werden soll. Diese Einstellung nimmst du im Tab *Newsletter senden* des erstellten Newsletters vor.

[TIP]
.Eingeschränkter Newsletter-Versand am Tag
====
Beachte, dass dein Newsletter tagsüber eingeschränkt an deine Kunden versendet wird. In der Nacht wird der Versand einer größeren Anzahl von E-Mails erlaubt.

* Am Tag zwischen 8:00 und 0:00 Uhr: 60 E-Mails je Viertelstunde
* Nachts zwischen 0:00 und 8:00 Uhr: 500 E-Mails je Viertelstunde
====

[.instruction]
Newsletter versenden:

. Öffne das Menü *CRM » Newsletter*.
. Klappe den Newsletter, den du versenden möchtest, auf (icon:plus-square-o[]).
. Wechsele in das Tab *Newsletter versenden*.
. Wähle unter *Sende Newsletter an Gruppe* eine Gruppe aus der Dropdown-Liste.
. Wähle unter *Filter* die Option *ALLE* oder die Option *Nur an bestätigte E-Mail-Adressen*.
. Klicke auf *Senden* (icon:envelope-o[role="purple"]). +
→ Der Newsletter wird gemäß der oben gewählten Einstellungen versendet.

[#1650]
=== Link zum Abbestellen des Newsletters einfügen

Du solltest deinen Newsletter-Empfängern jederzeit die Möglichkeit geben, deinen Newsletter wieder abzubestellen. Damit der Empfänger den Newsletter abbestellen kann, musst du den Link zum Abbestellen in die Newsletter-Vorlage im Menü *CRM » Newsletter* oder in jede andere beliebige E-Mail-Vorlage im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *E-Mail » Vorlagen* einfügen.

Es ist möglich einen Abmelde-Link hinzuzfügen, der Empfänger von allen Newsletter-Ordnern abmeldet (siehe Punkt 1) oder einen Link, der Empfänger von einem bestimmten Newsletter-Ordner abmeldet (siehe Punkt 2):

. *+http://[Domain-Name]/?OrderShow=CancelNewsletter+* +
Wenn Empfänger auf diesen Link klicken, werden sie aus allen Newsletter-Ordnern abgemeldet.

. *+http://[Domain-Name]/?OrderShow=CancelNewsletter&folderId=1+* +
Wenn Empfänger auf diesen Link klicken, werden sie aus einem bestimmten Newsletter-Ordner abgemeldet. In diesem Beispiel handelt es sich um den Ordner mit der ID 1.

Deine Domain findest du im Menü *Einrichtung » Mandant* » _Mandant wählen_ » *Einstellungen*.

[#1700]
== Newsletter mit CleverReach versenden

Gehe wie im Folgenden beschrieben vor, um deine Newsletter mit link:https://www.cleverreach.de/[CleverReach^] an deine Kunden zu versenden.

[#1800]
=== Bei CleverReach registrieren

Registrier dich kostenlos auf der link:https://www.cleverreach.de/[Website von CleverReach^], um CleverReach in plentymarkets zu nutzen. Weitere Informationen zu den Einstellungen in CleverReach findest du in der link:http://support.cleverreach.de/hc/de[Hilfe^] von CleverReach.

[#1900]
=== CleverReach in plentymarkets einrichten

Gehe wie im Folgenden beschrieben vor, um die Schnittstelle zu CleverReach in plentymarkets einzurichten.

[.instruction]
CleverReach in plentymarkets einrichten:

. Öffne das Menü *Einrichtung » CRM » Newsletter » CleverReach*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-cleverreach-einrichten>>.
. Gib deinen *API-Key* ein.
. Gib die *Listen-ID* der in CleverReach angelegten Gruppe ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Klicke auf *Standardattribute generieren* (icon:cog[]). +
→ Datenfelder werden in CleverReach erzeugt, damit die Kundendaten, die du übertragst, gespeichert werden.
. Öffne im CleverReach-Backend die Gruppe, deren ID du in plentymarkets eingegeben hast.
. Lösche die Datenfelder, deren Inhalt du nicht bei CleverReach verwenden möchtest. +
→ Aktuell werden die Datenfelder *Birthday (Geburtstag)*, *Vorname*, *Gender (Anrede)*, *Lang (Sprache)* und *Nachname* von plentymarkets an CleverReach übertragen.
. Wechsele zurück in das Menü *Einrichtung » CRM » Newsletter » CleverReach* des plentymarkets Backend.
. Aktiviere die Option *Automatische Übertragung (täglich)*, damit die Kundendaten übertragen werden.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-cleverreach-einrichten]]
.Einstellungen im Menü *Einrichtung » CRM » Newsletter » CleverReach*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Gruppenattribute erzeugen*
|Erzeugt die Datenfelder (Gruppenattribute) für CleverReach.

|*Datenübertragung ausführen*
|Überträgt die Datenfelder (Gruppenattribute) an CleverReach. Aktuell werden die Datenfelder *Birthday (Geburtstag)*, *Vorname*, *Gender (Anrede)*, *Lang (Sprache)* und *Nachname* von plentymarkets an CleverReach übertragen. Bereich aus der Dropdown-Liste wählen. +
*_Hinweis:_* Vor der Übertragung der eigentlichen Kundendaten ausführen. Dazu Anleitung unten beachten.

|*API-Key*
|API-Key eingeben, wie von CleverReach erhalten.

|*Listen-ID*
|Listen-ID aus CleverReach eingeben.

|*Auftragsherkünfte*
|Auftragsherkünfte wählen, die für CleverReach verfügbar sein sollen. Herkünfte, die keine Datenübertragung gestatten, sind standardmäßig nicht gewählt. +
*_Hinweis:_* Auswahl der Auftragsherkünfte vor der Arbeit mit CleverReach prüfen, um potenzielle Abmahnungen zu vermeiden.

|*Export ab Auftragsstatus*
|Status wählen, ab dem die Daten exportiert werden sollen.

|*Automatische Übertragung (täglich)*
|Aktivieren, wenn Daten täglich automatisch übertragen werden sollen.
|====

[IMPORTANT]
.Erste Übertragung
====
Bei der ersten automatischen Übertragung werden die Kundendaten der in den vorhergehenden 3 Tagen neu erstellten Kunden übertragen. Anschließend werden nur noch die Kundendaten der Kunden übertragen, die seit der letzten Übertragung hinzugekommen sind.
====

Wenn du nicht an alle Kunden schreiben möchtest, deren Daten du zu CleverReach übertragen hast, hast du in CleverReach Filtermöglichkeiten. Nähere Informationen hierzu findest du auf der Support-Seite von link:http://support.cleverreach.de/entries/21538892-wie-kann-ich-meine-empfanger-filtern[CleverReach^].

[#2000]
=== Kundendaten manuell übertragen

Mit der Option *Datenübertragung ausführen* werden nur die Kundendaten eines bestimmten Kundentyps übertragen. Dies bietet die Möglichkeit, die Kundentypen in separate Gruppen bei CleverReach einzuordnen.

[IMPORTANT]
.Automatische Übertragung sinnvoll?
====
Wenn du die Option *Datenübertragung ausführen* nutzt, um die Kundendaten gefiltert nach Kundentyp zu übertragen, solltest du überlegen, ob die automatische Übertragung noch sinnvoll für dich ist, da bei dieser Option unabhängig vom Kundentyp übertragen wird.
====

[.instruction]
Kundendaten manuell übertragen:

. Öffne das Menü *Einrichtung » CRM » Newsletter » CleverReach*.
. Gib deinen *API-Key* ein.
. Gib die *Listen-ID* der in CleverReach angelegten Gruppe ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Klicke auf *Standardattribute generieren* (icon:cog[]). +
→ Datenfelder werden in CleverReach erzeugt, damit die Kundendaten, die du übertragst, gespeichert werden.
. Öffne im CleverReach-Backend die Gruppe, deren ID du in plentymarkets eingegeben hast.
. Lösche die Datenfelder, deren Inhalt du nicht bei CleverReach verwenden möchtest. +
→ Aktuell werden die Datenfelder *Birthday (Geburtstag)*, *Vorname*, *Gender (Anrede)*, *Lang (Sprache)* und *Nachname* von plentymarkets an CleverReach übertragen.
. Wechsele zurück in das Menü *Einrichtung » CRM » Newsletter » CleverReach* des plentymarkets Backend.
. Wähle aus der Dropdown-Liste *Datenübertragung ausführen* den Kundentyp.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Klicke auf *Exportieren* (icon:cog[]). +
→ Die Kundendaten werden übertragen.
