= Ticketsystem nutzen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Ticketsystem, Ticket, Rolle, Typ, Status, Signatur, Grußformel, Nachricht, Kommentar, Vorlage, Kinderticket, Ereignisaktion, Aktionsmanager
:description: Erfahre, wie du das Ticketsystem in plentymarkets für deine Kundenkommunikation nutzt.
:position: 30
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:url: crm/ticketsystem-nutzen

Das Ticketsystem in plentymarkets bietet dir umfangreiche Funktionen zum <<crm/ticketsystem-nutzen#1600, Erstellen>>, <<crm/ticketsystem-nutzen#3400, Suchen>> und <<crm/ticketsystem-nutzen#3500, Bearbeiten>> deiner Tickets. Darüber hinaus sind Funktionen zur Projektverwaltung integriert. Auf dieser Handbuchseite findest du Informationen zu den Einstellungen, die du vorab im Benutzerkonto vornehmen musst, sowie zu den Einstellungen des Ticketsystems selbst im Menü *System » Systemeinstellungen » CRM » Ticketsystem*. Je nachdem, welchen plentymarkets Tarif du nutzt, musst du das Ticketsystem ggf. zunächst <<crm/ticketsystem-nutzen#100, buchen>>, bevor du dieses im Menü *CRM » Ticketsystem* nutzen kannst.

[#100]
== Ticketsystem buchen

Abhängig vom verwendeten plentymarkets Tarif musst du das Ticketsystem ggf. buchen, bevor es Ihnen zur Verfügung steht. Eine Übersicht über die plentymarkets Tarife findest du auf dieser link:https://www.plentymarkets.eu/preise/[Seite^].

[#200]
== Einstellungen im Benutzerkonto vornehmen

Um das Ticketsystem sinnvoll zu nutzen, solltest du deine Signatur und eine Grußformel speichern. Außerdem musst du im Benutzerkonto die Option *Ticket* aktivieren, damit diese Benutzer als Eigner im Ticketsystem verfügbar sind. Benutzer mit dem Zugang *Backend* benötigen zudem eine Berechtigung, um mit dem Ticketsystem arbeiten zu können. Die Einstellungen für Benutzer, die das Ticketsystem verwenden sollen, sind wichtig für die korrekte Grundeinrichtung deines Ticketsystems. Diese Einstellungen sind in den folgenden Unterkapiteln beschrieben.

[#300]
=== Signatur und Grußformel hinzufügen

Speichere für Eigner, die das Ticketsystem nutzen sollen, im Benutzerkonto in den Tabs *Signatur* und *Grußformel* Signaturdaten. Die Signatur wird mit vorangestellter Grußformel in E-Mails ausgegeben. Die Grußformel wird zusätzlich in Nachrichten und Kommentaren im Ticketsystem automatisch an den Text angehängt. Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#, Benutzerkonto personalisieren>>.

[IMPORTANT]
.Priorität der Signatur beachten
====
Die im Benutzerkonto eingegebene Signatur hat Priorität gegenüber der Signatur, die im Menü <<crm/e-mails-versenden#600, System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Signatur>> gespeichert ist. +
Wenn du die Template-Variable *$SignatureHTML* in die E-Mail-Vorlage eingefügt hast, wird die Signatur aus dem Benutzerkonto übernommen. Wenn keine Signatur im Benutzerkonto gespeichert ist, wird die Signatur, die im Menü *System » Systemeinstellungen » Mandant* » _Mandant wählen_ » *E-Mail » Signatur* gespeichert ist, übernommen. +
Wenn du die Template-Variable *$SignatureText* in die E-Mail-Vorlage eingefügt hast, wird immer die Signatur, die im Menü *System » Systemeinstellungen » Mandant* » _Mandant wählen_ » *E-Mail » Signatur* gespeichert ist, übernommen.
====

[#400]
=== Eigner aktivieren

Eigner aktivierst du im Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten* » _Benutzer öffnen_ im Tab *Eigner*. Aktiviere für jeden Benutzer, der als Eigner im Ticketsystem verfügbar sein soll, die Option *Ticket*. Beachte dazu auch die Handbuchseite <<basics/admin-aufgaben/benutzer-verwalten#40, Benutzer verwalten>>.

[#500]
=== Benutzerrechte für Backend-Benutzer vergeben

Nutzer vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs in plentymarkets. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter mit diesem Nutzertyp mit dem Ticketsystem arbeiten, muss ein Nutzer vom Typ *Admin* die in <<tabelle-berechtigungen-ticketsystem>> beschriebenen Rechte für diese Benutzer vergeben.

[.instruction]
Benutzerrechte für Backend-Benutzer vergeben:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*. +
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne den zu bearbeitenden Benutzer.
. Aktiviere im Bereich *Berechtigungen* die Berechtigungen anhand von <<tabelle-berechtigungen-ticketsystem>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-berechtigungen-ticketsystem]]
.Erforderliche Rechte für Backend-Benutzer
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*CRM > Ticket > Ticket aktualisieren*
|Erlaubt dem Backend-Benutzer, Tickets zu aktualisieren.

|*CRM > Ticket > Ticket anzeigen*
|Erlaubt dem Backend-Benutzer, Tickets zu sehen.

|*CRM > Ticket > Ticket bearbeiten*
|Erlaubt dem Backend-Benutzer, Tickets zu bearbeiten.

|*CRM > Ticket > Ticket erstellen*
|Erlaubt dem Backend-Benutzer, Tickets zu erstellen.

|*CRM > Ticket > Ticket löschen*
|Erlaubt dem Backend-Benutzer, Tickets zu löschen.

|====

Welche Berechtigungen ein *Admin*-Benutzer einem *Backend*-Benutzer vergeben muss, damit dieser mit Ticket-Rollen, Ticket-Status und Ticket-Typen arbeiten kann, ist im Kapitel <<crm/ticketsystem-nutzen#650, Benutzerrechte für Backend-Benutzer für Rollen, Status und Typen vergeben>> beschrieben.

[#600]
== Grundeinstellungen vornehmen

Bevor du das Ticketsystem nutzt, musst du im Menü *System » Systemeinstellungen » CRM » Ticketsystem » E-Mail-Konten* den E-Mail-Abruf einrichten, damit deine E-Mails automatisch in Tickets umgewandelt werden. Außerdem musst du im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* die für dein Ticketsystem vorgesehenen Rollen, Typen, Status, Statusgruppen und Themen erstellen. Diese Einstellungen sind in den folgenden Unterkapiteln beschrieben.

[#2100]
=== E-Mail-Konto einrichten

Damit E-Mails automatisch in Tickets umgewandelt werden, muss der E-Mail-Abruf eingerichtet werden. Die E-Mail-Adressen, von denen E-Mails abgerufen werden sollen, gibst du im Menü *System » Systemeinstellungen » CRM » Ticketsystem » E-Mail-Konten* ein. plentymarkets ruft dann regelmäßig neue E-Mails deiner Konten ab und wandelt diese in Tickets um. Die ursprünglichen E-Mails können entweder automatisch gelöscht oder in einen anderen E-Mail-Ordner verschoben werden.

Gehe wie im Folgenden beschrieben vor, um das E-Mail-Konto für dein Ticketsystem einzurichten.

Du kannst bis zu zwanzig E-Mail-Konten speichern, über die du E-Mails deiner Kunden direkt ins Ticketsystem überführst. plentymarkets empfiehlt für die E-Mail-Kommunikation im Ticketsystem eigene E-Mail-Adressen zu erstellen, die du ausschließlich für Tickets nutzt und die bereits anhand des Namens als solche zu erkennen sind.

[.instruction]
E-Mail-Konto einrichten:

. Öffne das Menü *System » Systemeinstellungen » CRM » Ticketsystem » E-Mail-Konten*.
. Klicke auf *Neue Konfiguration* (icon:plus-square[role="green"]).
. Klappe den Bereich *E-Mail* auf (icon:angle-down[]).
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-e-mail-konto-einrichten>>. +
→ *_Hinweis:_* Bei den Einstellungen in den Bereichen *Konto*, *Abruf* und *Versand* handelt es sich um Pflichteinstellungen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[IMPORTANT]
.Testmodus beachten
====
Nachdem du alle Tests durchgeführt hast, musst du den Testmodus im Menü *System » Systemeinstellungen » Mandant* » _Mandant wählen_ » *E-Mail » Zugangsdaten* deaktivieren. Ansonsten werden Tickets nur an die im Menü *System » Systemeinstellungen » CRM » Ticketsystem » E-Mail-Konten* gespeicherte E-Mail-Adresse versendet.
====

[[tabelle-e-mail-konto-einrichten]]
.Einstellungen im Menü *System » Systemeinstellungen » CRM » Ticketsystem » E-Mail-Konten*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*E-Mail-Abruf testen*
|Testet die Funktion des E-Mail-Abrufs. Eine Meldung erfolgt, ob der Test erfolgreich war. Danach geht eine E-Mail mit dem Datum und der Uhrzeit des Tests ein.

|*E-Mail-Versand testen*
|Testet die Funktion des E-Mail-Versands. Eine Meldung erfolgt, ob der Test erfolgreich war. +
*_Wichtig:_* Bei nicht erfolgreichem Test sind meist falsche Login-Daten oder ein falsches Kennwort die Ursache. Im Fehlerfall die Parameter prüfen.

2+|*Konto* (icon:exclamation-triangle[role="red"] *_Hinweis:_* Die Einstellung in diesem Bereich ist eine Pflichteinstellung.)

|*E-Mail*
|E-Mail-Adresse eingeben, die für das Ticketsystem verwendet werden soll. Das ist ein Pflichtfeld.

2+|*Abruf* (icon:exclamation-triangle[role="red"] *_Hinweis:_* Alle Einstellungen in diesem Bereich sind Pflichteinstellungen.)

|*Aktiv*
|Soll das Konto und damit der Abruf aktiv sein, Option aktivieren. +
Soll das Konto nicht aktiv sein, Option deaktivieren und speichern. Das Konto bleibt verfügbar und kann jederzeit wieder aktiviert werden.

|*Benutzer*
|Benutzername zu der E-Mail-Adresse eingeben.

|*Passwort*
|Passwort zu dem Benutzernamen und der E-Mail-Adresse eingeben.

|*Verfahren*
|Verfahren wählen. Empfohlenes Verfahren: IMAP. +
*IMAP* = Die E-Mails werden auf dem Server des Providers verwaltet und stehen mehreren Geräten wie z.B. Computer, Tablet oder Smartphone zur Verfügung. Die E-Mails werden auf den Geräten synchronisiert; der Stand ist überall identisch. +
*POP* = E-Mail-Verbindungsprotokoll, das die Abholung von E-Mails von einem Server regelt. Zwar ist keine ständige Verbindung zum Server nötig, dennoch kann es besonders bei der Arbeit mit mehreren Geräten zu Datenfehlern kommen. Bei Nutzung des POP-Verfahrens werden alle Nachrichten vom Server komplett oder als Kopie auf das Gerät heruntergeladen. Diese können dort lokal gelesen, beantwortet oder gelöscht werden. Änderungen werden weder auf den anderen verwendeten Geräte noch auf dem Server gespeichert. Eine Synchronisierung findet nicht statt.

|*Port*
|Standardwert: 25, dieser Wert ist für fast alle Provider korrekt. Andernfalls den korrekten Port beim Provider erfragen. Info zu *Verschlüsselung* beachten.

|*Verschlüsselung*
|*SSL*, *TLS* (Grundeinstellung) oder *keine Verschlüsselung* wählen. +
*_Wichtig:_* Für plentymarkets E-Mail-Konten mit dem Typ IMAP die Einstellung *TLS* mit Port 143 oder die Einstellung *keine Verschlüsselung* mit Port 143 verwenden. +
TLS-Verschlüsselung = Bei Host auf eigener Domain (z.B. mail.domain.tld) kann über Port 143 nicht *TLS* als Verschlüsselungsmethode verwendet werden, sondern die Einstellung *keine Verschlüsselung*. Bei Host auf plentymarkets (z.B. mail.plentymarkets.com) kann Port 143 in Verbindung mit *TLS* genutzt werden.

|*Host*
|URL des Host-Rechners eingeben, auf dem das E-Mail-Konto verwaltet wird.

|*Typ/Status neues Ticket*
|Typ und Status für neue Tickets aus den Dropdown-Listen wählen. Wird ein neues Ticket mit diesen Parametern erstellt, erfolgt der automatische E-Mail-Versand.

2+|*Versand* (icon:exclamation-triangle[role="red"] *_Hinweis:_* Alle Einstellungen in diesem Bereich sind Pflichteinstellungen.)

|*Name Sender*
|Eigenen Namen oder Namen der eigenen Firma/Shop eingeben. Der Name wird dem Empfänger angezeigt.

|*Antwort an*
|E-Mail-Adresse eingeben, an die die Antwort gesendet werden soll.

|*Benutzer*
|Benutzername zu der E-Mail-Adresse eingeben.

|*Passwort*
|Passwort zu dem Benutzernamen und der E-Mail-Adresse eingeben.

|*Port*
|Standardwert: 25, dieser Wert ist für fast alle Provider korrekt. Andernfalls den korrekten Port beim Provider erfragen.

|*Verschlüsselung*
|*SSL*, *TLS* oder *keine Verschlüsselung* wählen.

|*Host*
|URL des Host-Rechners eingeben, auf dem das E-Mail-Konto verwaltet wird.

2+|Aktionen

|*Aktion*
|Mit *Verschieben* werden die E-Mails in einen bestimmten Ordner eingeordnet, nachdem das Ticket erstellt wurde. Damit können die E-Mails archiviert werden. +
*Löschen* wählen, wenn die E-Mails nicht gespeichert werden sollen. Die E-Mails werden dann nach Eingang und Zuordnung im Ticketsystem gelöscht.

|*Verschieben nach*
|Diese Option ist nur sichtbar, wenn die Aktion *Verschieben* gewählt wurde. Ordner wählen, in den die E-Mails verschoben werden sollen. +
*_Wichtig:_* Die Wahl eines Ordners ist zwingend. Wenn kein Ordner gewählt wird, werden die E-Mails nicht verschoben.
|====

[#650]
=== Benutzerrechte für Backend-Benutzer für Rollen, Status und Typen vergeben

Nutzer vom Typ *Backend* sehen nur bestimmte Bereiche und Menüs in plentymarkets. Somit können sie nur eingeschränkt im System arbeiten. Sollen Mitarbeiter mit diesem Nutzertyp mit Rollen, Status und Typen im Ticketsystem arbeiten, muss ein Nutzer vom Typ *Admin* die in <<tabelle-berechtigungen-ticketsystem-rollen-status-typen>> beschriebenen Rechte für diese Benutzer vergeben.

[.instruction]
Benutzerrechte für Backend-Benutzer vergeben:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*. +
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne den zu bearbeitenden Benutzer.
. Aktiviere im Bereich *Berechtigungen* die Berechtigungen anhand von <<tabelle-berechtigungen-ticketsystem-rollen-status-typen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-berechtigungen-ticketsystem-rollen-status-typen]]
.Berechtigungen für Rollen, Status und Typen für Backend-Benutzer
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*CRM > Ticket > Ticket-Rolle > Ticket-Rolle aktualisieren*
|Erlaubt dem Backend-Benutzer, Ticket-Rollen zu aktualisieren.

|*CRM > Ticket > Ticket-Rolle > Ticket-Rolle anzeigen*
|Erlaubt dem Backend-Benutzer, Ticket-Rollen zu sehen.

|*CRM > Ticket > Ticket-Rolle > Ticket-Rolle erstellen*
|Erlaubt dem Backend-Benutzer, Ticket-Rollen zu erstellen.

|*CRM > Ticket > Ticket-Status > Ticket-Status aktualisieren*
|Erlaubt dem Backend-Benutzer, Ticket-Status zu aktualisieren.

|*CRM > Ticket > Ticket-Status > Ticket-Status anzeigen*
|Erlaubt dem Backend-Benutzer, Ticket-Status zu sehen.

|*CRM > Ticket > Ticket-Status > Ticket-Status erstellen*
|Erlaubt dem Backend-Benutzer, Ticket-Status zu erstellen.

|*CRM > Ticket > Ticket-Typ > Ticket-Typ aktualisieren*
|Erlaubt dem Backend-Benutzer, Ticket-Typen zu aktualisieren.

|*CRM > Ticket > Ticket-Typ > Ticket-Typ anzeigen*
|Erlaubt dem Backend-Benutzer, Ticket-Typen zu sehen.

|*CRM > Ticket > Ticket-Typ > Ticket-Typ erstellen*
|Erlaubt dem Backend-Benutzer, Ticket-Typen zu erstellen.

|====

[#700]
=== Rolle hinzufügen

Eine Rolle repräsentiert die Beziehung des Mitarbeiters zu einem Ticket und kann jedem Ticket individuell zugeordnet werden. Wenn ein Mitarbeiter zum Beispiel in einem Ticket eine unterstützende Funktion ausübt, füge die Rolle *Support* hinzu und ordne diese Rolle dem Mitarbeiter zu. In ein neues Ticket wird der aktive Benutzer automatisch als Eigner übernommen.

Im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* im Tab *Rollen* gibst du für jede Rolle einen Namen in verschiedenen Sprachen ein. Du speicherst den Namen für die *Standardsprache*, d.h. die Sprache, mit der du in deinem plentymarkets System eingeloggt bist sowie für weitere Sprachen. Diese Sprachvarianten werden dann für die Systemsprachen verwendet. Wenn du dich z.B. mit der Spracheinstellung *Englisch* in deinem plentymarkets System einloggst, werden die Namen verwendet, die du unter *en* eingegeben hast. Die *Position* legt fest, in welcher Reihenfolge die Rollen in den Auswahlmöglichkeiten angezeigt werden.

Wird ein Eigner in einem Ticket eingegeben, muss gleichzeitig dessen Rolle im Ticket festgelegt werden. In diesem Menü legst du beliebig viele Rollen an.

[TIP]
.Beispiel für die Nutzung des Ticketsystems als Projektverwaltung
====
Füge die Rollen *Projektleiter* und *Mitarbeiter* hinzu. In den Ereignisaktionen im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Ereignisse* kann dann z.B. eingestellt werden, dass der Projektleiter per E-Mail benachrichtigt wird, wenn sich der Status des Tickets ändert oder ein Kommentar hinterlassen wurde.
====

[.instruction]
Rolle hinzufügen:

. Öffne das Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen*.
. Wechsele in das *Rollen*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Eine leere Zeile wird angezeigt.
. Gib einen Namen und eine Positionsnummer ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Du bearbeitest eine Rolle, indem du in das Textfeld klickst. Ein Klick auf *Löschen* (icon:minus-square[role="red"]) löscht die Zeile nach Bestätigung.

[#800]
=== Typ hinzufügen

Du kannst beliebig viele Typen für Tickets erstellen, z.B. *Kundenanfrage* oder *Beschwerde*. Die Einstellungen zur *Standardsprache*, *weiteren Sprachen* und der *Position* nimmst du wie im Kapitel <<crm/ticketsystem-nutzen#700, Rolle hinzufügen>> beschrieben vor.

[.instruction]
Typ hinzufügen:

. Öffne das Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen*.
. Wechsele in das Tab *Typen &amp; Status*.
. Klicke auf *Neuer Typ* (icon:plus-square[role="green"]). +
→ Das Fenster *Neuer Typ* wird geöffnet.
. Gib den Namen ein.
. Klicke auf *Speichern* (icon:save[role="green"]). +
→ Der Typ wird hinzugefügt und geöffnet.
. Gib die *Position* ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Du bearbeitest einen Typ, indem du in das Textfeld klickst. Ein Klick auf *Löschen* (icon:minus-square[role="red"]) löscht die Zeile nach Bestätigung.

[#900]
=== Status hinzufügen

Lege zu jedem Tickettyp individuelle Status fest. Lege für jeden Typ dieselben oder unterschiedliche Status an.

[IMPORTANT]
.Sichtbarkeit festlegen
====
Für die <<basics/admin-aufgaben/benutzer-verwalten#100, Sichtbarkeiten>>, die du in den Menüs *System » Systemeinstellungen » Einstellungen » Benutzer » Konten* und *System » Systemeinstellungen » Einstellungen » Benutzer » Rollen* für die Ticketstatus festlegst, gilt: "Verbote" sind dominant. Das heißt, wenn einem Benutzer mehrere Rollen zugeordnet sind, müssen Bereiche, die im Tab *Sichtbarkeiten* auf *Sichtbar* gestellt sind, in allen Rollen dieses Benutzers auf *Sichtbar* gestellt sein. Ist ein Bereich in einer Rolle auf *Unsichtbar* gestellt, gilt diese Einstellung auch für alle anderen Rollen des Benutzers.
====

[.instruction]
Status hinzufügen:

. Öffne das Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen*.
. Wechsele in das Tab *Typen &amp; Status*.
. Öffne den soeben hinzugefügten <<crm/ticketsystem-nutzen#800, Typ>>.
. Klicke auf *Neuen Status hinzufügen* (icon:plus-square[role="green"]).
. Gib den *Namen* ein.
. Lege einen *Fortschritt* zwischen 0 und 100 % für diesen Status fest. +
→ Bei Erreichen des Status wird in der Ticketübersicht ein Fortschrittsbalken angezeigt.
. Wähle eine *Gruppe* aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Du bearbeitest einen Status, indem du in das Textfeld klickst. Ein Klick auf *Löschen* (icon:minus-square[role="red"]) löscht die Zeile nach Bestätigung.

[#1000]
=== Statusgruppe erstellen

Du hast im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* im Tab *Statusgruppen* die Möglichkeit, Statusgruppen zu erstellen. Diese Statusgruppen helfen dir später im Ticketsystem, die Übersicht zu behalten. Wenn du die Status stark untergliedert hast, also z.B. 10 Bearbeitungsstatus hast, die abteilungsintern benötigt werden, aber für andere Abteilungen nicht wichtig sind, sind Statusgruppen eine Möglichkeit, diese Status zusammenzufassen.

[IMPORTANT]
.Zuordnung der Status
====
Jeder Status kann nur zu einer Gruppe hinzugefügt werden.
====

[.instruction]
Statusgruppe erstellen:

. Öffne das Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen*.
. Wechsele in das Tab *Statusgruppen*.
. Klicke auf *Neue Statusgruppe hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Statusgruppe* wird geöffnet.
. Gib den *Namen* ein.
. Gib die *Position* ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Statusgruppe wird hinzugefügt und geöffnet.
. Wähle eine *Farbe* für die Statusgruppe.
. Aktiviere den oder die Status, die der Gruppe angehören sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Sprache der Statusgruppe hinzufügen
====
Die Statusgruppe wird für die Standardsystemsprache erstellt. Wähle im Bearbeitungsfenster eine andere Sprache, um eine Übersetzung für den Namen einzugeben. Die Auswahl der Status wird übernommen.
====

Wenn du im Menü *CRM » Ticketsystem* im Tab *Tickets* über <<basics/arbeiten-mit-plentymarkets/allgemeine-funktionen#50, Ansicht einrichten>> die Option *Statusgruppe* aktiviert hast, siehst du direkt nach dem Erstellen eines Tickets in der Ticketübersicht, in welchem Status sich das Ticket befindet. Die Statusgruppe wird ebenfalls im Ticket neben *Tags anzeigen/verbergen* angezeigt.

[#1100]
=== Thema hinzufügen

Du hast im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* im Tab *Themen* die Möglichkeit, Themen zu erstellen, die du später beim Bearbeiten deiner Tickets den Nachrichten und Kommentaren als Überschriften zuweist. Auf diese Weise wird die Bearbeitung deiner Tickets übersichtlicher und verständlicher. Vergib für deine Kommunikation z.B. Themen wie *Artikeldetails*, *Service* und *Umtausch*. So erkennst du beim Überfliegen einer längeren Kommunikation das Thema deiner Antwort auf einen Blick. Wie du Themen zuweist, ist im Kapitel <<crm/ticketsystem-nutzen#2600, Thema zuweisen>> beschrieben.

[.instruction]
Thema hinzufügen:

. Öffne das Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen*.
. Wechsele in das Tab *Themen*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]).
. Gib für die *Standardsprache* sowie für die aus der Dropdown-Liste gewählte Sprache einen Namen ein.
. Gib die *Position* ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Du bearbeitest ein Thema, indem du in das Textfeld klickst. Ein Klick auf *Löschen* (icon:minus-square[role="red"]) löscht die Zeile nach Bestätigung.

[#1600]
== Ticket erstellen

Ein Ticket kann viele Eigenschaften haben, die den Fortschritt, die Herkunft, den Typ und den damit verbundenen Status betreffen. Es ist somit möglich, unterschiedliche Tickettypen mit individuellen Statuswerten zu verwalten. Ein Ticket kann von mehreren Eignern bearbeitet werden. Dazu definierst du für das Ticketsystem Rollen, die dann einem Eigner zugeordnet werden können.

Du hast die Möglichkeit, Tickets manuell oder automatisch zu erstellen. Welche Einstellungen du dazu vornehmen musst, wird in den folgenden Kapiteln beschrieben.

[#1700]
=== Ticket manuell erstellen

Du hast 2 Möglichkeiten, Tickets manuell zu erstellen:

* ohne Vorlage
* aus einer Vorlage

Beim Erstellen ohne Vorlage muss jede Einstellung individuell vorgenommen werden. Beim Erstellen aus einer <<crm/ticketsystem-nutzen#3100, Vorlage>> werden die Einstellungen der Vorlage übernommen.

[#1800]
==== Ticket ohne Vorlage erstellen

Gehe wie im Folgenden beschrieben vor, um ein Ticket manuell und ohne Vorlage zu erstellen.

[.instruction]
Ticket ohne Vorlage erstellen:

. Öffne das Menü *CRM » Ticketsystem*.
. Klicke auf *Neues Ticket* (icon:plus-square[role="green"]).
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-ticket-ohne-vorlage-erstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ticket wird erstellt.

[[tabelle-ticket-ohne-vorlage-erstellen]]
.Einstellungen im Menü *CRM » Ticketsystem* im Tab *Neues Ticket*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Rolle*
|Rolle des Eigners aus der Dropdown-Liste wählen. Zur Auswahl stehen die im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* im Tab *Rollen* hinzugefügten <<crm/ticketsystem-nutzen#700, Rollen>>. +
Das ist ein Pflichtfeld. Wenn keine Rolle gewählt ist, kann das Ticket nicht erstellt werden.

|*Eigner*
|In ein neues Ticket wird automatisch der aktive Benutzer als Eigner übernommen. Bei Bedarf anderen Eigner aus der Dropdown-Liste wählen. +
Das ist ein Pflichtfeld. Wenn kein Eigner gewählt ist, kann das Ticket nicht erstellt werden.

|*Kunde*
|Auf der Tastatur die Pfeiltaste nach unten drücken. Eine Liste der Kunden wird angezeigt. Die Kunden werden anhand ihrer ID sortiert angezeigt. Der Kunde mit der niedrigsten ID wird an erster Stelle angezeigt. Mit einem Klick auf den Kunden wird der Name sowie die ID in das Feld übernommen.

|*Titel*
|Titel für das Ticket eingeben. +
Das ist ein Pflichtfeld. Wenn kein Titel eingegeben ist, kann das Ticket nicht erstellt werden.

|*Tags*
|Klicken, um Tags hinzuzufügen. Zur Auswahl stehen die im Menü *System » Systemeinstellungen » Einstellungen » Tags* hinzugefügten Tags. Weitere Informationen dazu findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/tags#, Tags>>.

|*Ordner*
|Ordner aus der Dropdown-Liste wählen. Zur Auswahl stehen die im Menü *CRM » Ticketsystem* erstellten <<crm/ticketsystem-nutzen#4500, Ordner>>.

|*Priorität*
|Priorität aus der Dropdown-Liste wählen.

|*Typ*
|Typ aus der Dropdown-Liste wählen. Zur Auswahl stehen die im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* im Tab *Typen &amp; Status* erstellten Typen. +
Das ist ein Pflichtfeld. Wenn kein Typ gewählt ist, kann das Ticket nicht erstellt werden.

|*Status*
|Status aus der Dropdown-Liste wählen. Die Dropdown-Liste ist erst aktiviert, wenn zuvor ein Typ gewählt wurde. Zur Auswahl stehen die im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* im Tab *Typen &amp; Status* erstellten Status. +
Das ist ein Pflichtfeld. Wenn kein Status gewählt ist, kann das Ticket nicht erstellt werden.

|*Termin*
|Termin im Format TT.MM.JJJJ eingeben oder ein Datum aus dem Kalender wählen.

|*Ticket als vertraulich definieren (unsichtbar für Kunden)*
|Klicken, um das Ticket als vertraulich zu definieren. Wenn das Ticket vertraulich ist, ist die Nachrichtenfunktion deaktiviert. Vertrauliche Tickets sind für Kunden unsichtbar.

|*Mandant (Shop)*
|Mandant (Shop) aus der Dropdown-Liste wählen.
|====

Nachdem du die Einstellungen gespeichert hast, wird die ID des Tickets im Tab angezeigt. Außerdem wird eine Symbolleiste angezeigt. Beachte die Erläuterungen zur Symbolleiste in <<tabelle-symbolleiste-ticket>>.

[[tabelle-symbolleiste-ticket]]
.Symbolleiste im Menü *CRM » Ticketsystem » Ticket öffnen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Nachricht hinzufügen*
|Nachrichten sind blau gekennzeichnet und für den Kunden sichtbar. Wenn ein Ticket *vertraulich* ist, können keine Nachrichten geschrieben werden. Weitere Informationen findest du im Kapitel <<crm/ticketsystem-nutzen#2400, Nachricht hinzufügen>>.

|*Kommentar hinzufügen*
|Kommentare sind rot gekennzeichnet und nicht für den Kunden sichtbar. Kommentare dienen der internen Kommunikation. Weitere Informationen findest du im Kapitel <<crm/ticketsystem-nutzen#2500, Kommentar hinzufügen>>.

|*E-Mail-Vorlage senden*
|Klicken, um eine E-Mail-Vorlage zu senden. Das Fenster *E-Mail-Vorlage senden* wird geöffnet. Vorlage aus der Dropdown-Liste wählen und auf *E-Mail-Vorlage senden* klicken. +
Das Ticket muss mit einem Kunden verknüpft sein, um die E-Mail-Vorlage zu senden. Dazu in das Feld *Kunde* klicken und auf der Tastatur die Pfeiltaste nach unten drücken. Eine Liste der Kunden wird angezeigt. Die Kunden werden anhand ihrer ID sortiert angezeigt. Der Kunde mit der niedrigsten ID wird an erster Stelle angezeigt. Mit einem Klick auf den Kunden wird der Name sowie die ID in das Feld übernommen.

|*Drucken*
|Druckt das Ticket. Ein Ticket wird als <<crm/ticketsystem-nutzen#5300, Ticketkarte>> gedruckt.

|*Elternticket aufrufen*
|Öffnet das Elternticket in einem neuen Tab, falls vorhanden.

|*Statushistorie anzeigen/verbergen*
|Statushistorie anzeigen oder verbergen. Wenn *Statushistorie anzeigen* aktiviert wird, wird der Bereich *Statushistorie* auf der rechten Seite im Ticket angezeigt. Die Statushistorie listet alle Status auf, die das Ticket bisher durchlaufen hat.

|*Events anzeigen/verbergen*
|Events anzeigen oder verbergen. Wenn *Events anzeigen* aktiviert wird, wird der Bereich *Events* auf der rechten Seite im Ticket angezeigt. Alle bisherigen Events des Tickets werden angezeigt.

|*Eignerliste anzeigen/verbergen*
|Eignerliste anzeigen oder verbergen. Wenn *Eignerliste anzeigen* aktiviert wird, wird der Bereich *Eigner* auf der rechten Seite im Ticket angezeigt. Alle Eigner des Tickets sowie deren Rolle werden angezeigt.

|*Tags anzeigen/verbergen*
|Tags anzeigen oder verbergen. Wenn *Tags anzeigen* aktiviert wird, wird der Bereich *Tags* auf der rechten Seite im Ticket angezeigt. Dort können weitere <<basics/arbeiten-mit-plentymarkets/tags#, Tags>> hinzugefügt werden, die zuvor im Menü *System » Systemeinstellungen » Einstellungen » Tags* erstellt wurden. Für ein Ticket können beliebig viele Tags gewählt werden.

|*Neue Karte erstellen*
|Erstellt aus dem Ticket heraus eine neue Karte auf dem aus der Dropdown-Liste gewählten Board. Der Karte kann außerdem ein Präfix hinzugefügt werden. <<basics/arbeiten-mit-plentymarkets/boards#, Boards>> erstellst du im Menü *Start » Boards*.

|====

[#1900]
==== Ticket aus Vorlage erstellen

Wenn du bereits allgemeine oder persönliche Vorlagen im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Vorlagen* erstellt hast, kannst du Tickets oder Kindertickets, die auf einer dieser allgemeinen oder persönlichen Vorlagen basieren, erstellen. Beachte die Kapitel <<crm/ticketsystem-nutzen#3100, Allgemeine Ticketvorlage erstellen>> und <<crm/ticketsystem-nutzen#3200, Persönliche Ticketvorlage erstellen>>, bevor du die Einstellungen im folgenden Menü vornimmst. Gehe dann wie im Folgenden beschrieben vor, um ein Ticket aus einer Vorlage zu erstellen.

[.instruction]
Ticket aus Vorlage erstellen:

. Öffne das Menü *CRM » Ticketsystem*.
. Klicke auf *Neues Ticket aus Vorlage* (icon:plus-square[role="green"]). +
→ Das Fenster *Neues Ticket aus Vorlage erstellen* wird geöffnet.
. Wähle die zuvor im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Vorlagen* erstellte <<crm/ticketsystem-nutzen#3100, Vorlage>> aus der Dropdown-Liste.
. Klicke auf *Neues Ticket* (icon:plus-square[role="green"]), um die Einstellungen der Vorlage für das Ticket zu übernehmen. +
→ Ein neues Ticket mit den Einstellungen aus der Vorlage wird geöffnet.
. Nimm ggf. Änderungen in der Vorlage vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ticket wird erstellt.

[#2000]
=== Ticket automatisch erstellen

Wie in Kapitel <<crm/ticketsystem-nutzen#2100, E-Mail-Konto einrichten>> beschrieben, werden E-Mails automatisch in Tickets umgewandelt, wenn du den E-Mail-Abruf eingerichtet hast. Darüberhinaus besteht die Möglichkeit, Tickets automatisch aus eBay-Nachrichten und aus Formularen zu erstellen. Gehe dazu wie in den folgenden Unterkapiteln beschrieben vor.

[IMPORTANT]
.Fehlerhafte Anzeige von E-Mails mit Bildern, die von Apple-Geräten gesendet wurden
====
Beim Einlesen von E-Mails für das Ticketsystem, die ein Bild oder einen anderen Anhang mitten im Text haben und die von Apple-Geräten gesendet wurden, kann es vorkommen, dass der Textinhalt nach dem Anhang nicht eingelesen wird. Dieses Verhalten kann aktuell nicht behoben werden. Allerdings wird in einem solchen Fall ein Hinweistext am Ende der Ticketnachricht eingeblendet, der darüber informiert, dass ggf. Textinhalt fehlt.
====

[#2200]
==== Tickets aus eBay-Nachrichten erstellen

Du hast die Möglichkeit, eBay-Nachrichten direkt abzurufen und in dein Ticketsystem zu importieren. Die Nachrichten werden stündlich abgerufen. Du musst dazu im Menü *System » Systemeinstellungen » Märkte » eBay » Einstellungen* im Tab <<maerkte/ebay/ebay-einrichten#600, Kontoeinstellungen>> die Option *Nachrichten automatisch abrufen* aktivieren. Dort wählst du auch einen Nachrichtentyp und einen Nachrichtenstatus. Diese Parameter werden den eBay-Nachrichten dann automatisch zugeordnet. Richte bei Bedarf einen eigenen Typ und Status für deine eBay-Nachrichten ein.

Anschließend kannst du auch über das Ticketsystem antworten. Die Nachricht erreicht deine Kunden dann über das Nachrichtensystem von eBay. Eine eBay-Nachricht darf eine Länge von maximal 950 Zeichen haben. Wird diese Zeichenanzahl überschritten, kann die Nachricht nicht übermittelt werden.

Beim ersten Import der eBay-Nachrichten werden nur die Nachrichten der vergangenen 7 Tage importiert. Wurde bereits ein Import durchgeführt, werden die Nachrichten seit dem letzten Import abgerufen. Dieser Import darf nicht länger als 7 Tage zurückliegen, sonst werden wiederum nur die letzten 7 Tage importiert. Informationen zu den Importen findest du im Menü <<basics/datenaustausch/api-log#, Daten » API-Log>> durch Aufruf des API-Logs *EbayMemberMessages*.

[#2300]
==== Tickets aus Formularen erstellen

Mit Formularen kannst du Kontaktformulare in den Webshop einbinden. Die Formulare werden von Besuchern deines Webshops ausgefüllt und dann als Ticket erstellt. Um anschließend aus dem Ticket antworten zu können, muss im Menü *System » Systemeinstellungen » CRM » Ticketsystem » E-Mail-Konten* ein gültiges E-Mail-Konto eingerichtet sein.

Unabhängig von diesem Ticket und dem weiteren Vorgehen im Ticketsystem erhältst du als Händler eine Infomail über den Eingang einer neuen Nachricht an die im Menü *System » Systemeinstellungen » Mandant* » _Mandant wählen_ » *E-Mail » Zugangsdaten* gespeicherte E-Mail-Adresse. Diese E-Mail erhältst du auch, wenn du kein Ticketsystem <<crm/ticketsystem-nutzen#100, gebucht>> hast.

[TIP]
.Beispiel für die Verwendung des Kontaktformulars
====
Ein Webshop-Besucher hat eine Frage zu deinen Artikeln und nutzt das Kontaktformular in deinem Webshop, um mit dir in Kontakt zu treten. Daraufhin wird im Ticketsystem ein Ticket mit der Nachricht aus dem Kontaktformular erstellt. Du oder einer deiner Kollegen antwortet im Ticketsystem per Nachricht auf das Ticket. Mit einer entsprechend eingerichteten Ereignisaktion erhält der Webshop-Besucher daraufhin eine E-Mail. Der Webshop-Besucher antwortet jetzt aus seinem E-Mail-Programm auf deine Nachricht. Wenn die richtigen Parameter wie Ticket-ID etc. in dieser E-Mail als Template-Variablen eingefügt sind, wird die E-Mail dem Ticket zugeordnet. +
*_Hinweis:_* Hat der Webshop-Besucher z.B. die Ticket-ID oder andere Zuordnungsparameter aus dem Betreff und der E-Mail gelöscht, kann keine Zuordnung stattfinden. Ein neues Ticket wird daher erstellt. +
Ein neues Ticket wird ebenfalls erstellt, wenn der Webshop-Besucher statt direkt auf die E-Mail zu antworten wieder das Kontaktformular nutzt, da in diesem Fall die Zuordnungsparameter in der Nachricht fehlen und dein plentymarkets System die Zugehörigkeit zu einer vorhergehenden Nachricht nicht erkennen kann.
====

Gehe wie im Folgenden beschrieben vor, damit Tickets aus Kontaktformularen, die von Interessenten und Kunden im Webshop ausgefüllt werden, automatisch erstellt werden.

[.instruction]
Tickets aus Formularen erstellen:

. Öffne das Menü *System » Systemeinstellungen » CMS » Formulare*.
. Gib den *Formularnamen* ein.
. Wähle den *Tickettyp*.
. Wähle den *Ticketstatus*.
. Gib den Feldnamen für die E-Mail-Adresse ein.
. Wähle den Typ *Textfeld E-Mail-Adresse* aus der Dropdown-Liste. +
→ Beachte den Hinweis in der folgenden Box.
. Gib ggf. weitere Feldnamen ein.
. Wähle für jeden Feldnamen einen *Typ* aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Jedes Mal, wenn das Formular ausgefüllt und abgeschickt wird, wird ein Ticket dieses Typs erstellt.

Alle weiteren Formulareinstellungen sind optional. Weitere Informationen findest du auf der Handbuchseite <<omni-channel/online-shop/webshop-einrichten/cms#einstellungen-formulare, Formulare>>.

[IMPORTANT]
.Zuordnung ausschließlich anhand von E-Mail-Adressen
====
Kontaktformulare werden ausschließlich anhand der E-Mail-Adresse des Kunden zugeordnet. Eine E-Mail-Adresse in Kontaktformularen muss vom Typ *Textfeld E-Mail-Adresse* sein, ansonsten erkennt dein plentymarkets System nicht, dass es sich bei der Information um die E-Mail-Adresse handelt. E-Mail-Adresse, die in anderen Feldern, z.B. Nachricht oder Sonstiges eingegeben werden, werden nicht für die Zuordnung berücksichtigt und werden auch nicht für eine Antwort verwendet.
====

Wenn die E-Mail-Adresse einem bestehenden Kunden zugeordnet werden kann, wird dieser Kunde im Ticket angezeigt. Wenn die E-Mail-Adresse keinem bestehenden Kunden zugeordnet werden kann, siehst du die E-Mail-Adresse des Absenders nicht im Ticketsystem. Wird nun eine Nachricht im Ticketsystem verfasst, wird diese trotzdem an die Absenderadresse versendet.

Antworte deinen Kunden im Ticketsystem per Nachricht. Beachte, dass eine Nachricht nur als E-Mail versendet wird, wenn dafür eine Ereignisaktion im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Ereignisse* eingerichtet wurde.

[IMPORTANT]
.Verwendung des ersten E-Mail-Kontos für Antwortnachrichten auf Formulartickets
====
Wenn du mehrere <<crm/ticketsystem-nutzen#2100, E-Mail-Konten>> im Menü *System » Systemeinstellungen » CRM » Ticketsystem » E-Mail-Konten* eingerichtet hast, wird für den Versand einer Antwortnachricht auf ein Formularticket das E-Mail-Konto verwendet, das du zuerst eingerichtet haben.
====

[#2400]
== Nachricht hinzufügen

Nachrichten sind für die externe Kommunikation gedacht, d.h. für die Kommunikation mit deinen Kunden. Klicke zum Erstellen einer neuen Nachricht auf *Nachricht hinzufügen* und gib anschließend im Fenster *Nachricht* den Nachrichtentext im Textfeld ein. In der Symbolleiste stehen dir Formatierungsmöglichkeiten zur Verfügung. Eine im Benutzerkonto gespeicherte <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#10, Grußformel>> wird automatisch in Nachrichten des Benutzers eingefügt.

Gleichzeitig startet mit dem Erstellen der Nachricht im Bereich *Events* ein Timer, der die Bearbeitungszeit sekundengenau protokolliert. Diese Zeit kannst du im Feld *Min.* eingeben, wenn der Vorgang abgerechnet werden soll. Im unteren Eventbereich siehst du die bisherigen Events chronologisch gelistet, also z.B. wenn ein anderer Mitarbeiter dieses Ticket bereits bearbeitet hat.

[IMPORTANT]
.Neues Event mit Filter Servicetyp, Abrechnen und Dauer hinzugefügt
====
Im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Ereignisse* ist es möglich, das Ereignis *Neues Event* zu wählen und die Filter *Servicetyp*, *Abrechnen* und *Dauer* hinzuzufügen. Dies ermöglicht dir, Events feiner zu unterscheiden und somit auch unterschiedliche E-Mail-Vorlagen zu versenden.

Der automatische Versand für Serviceeinheiten im Menü *System » Systemeinstellungen » Mandant* » _Mandant wählen_ » *E-Mail » Automatischer Versand* greift weiterhin für Events, die am Kontakt erstellt wurden.

*_Wichtig:_* Für das Ticketsystem wurde diese Funktion abgeschaltet. Richte daher eine neue Ereignisaktion im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Ereignisse* ein.
====

[.instruction]
Vorgang abrechnen:

. Öffne das Menü *CRM » Ticketsystem*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne das zu bearbeitende Ticket.
. Klicke auf *Nachricht hinzufügen*. +
→ Das Fenster *Nachricht* wird geöffnet und der Timer startet.
. Aktiviere die Option *Abrechnen*, wenn der Vorgang abgerechnet werden soll.
. Wähle die Art des Vorgangs aus der Dropdown-Liste.  +
→ Zur Auswahl stehen: *Anruf*, *Ticket*, *E-Mail*, *Meeting*, *Webinar*, *Entwicklung* und *Design*.
. Gib im Feld *Min.* die Zeit in Minuten ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Hinweise zum Timer
====
Wenn du z.B. nach Öffnen des Nachrichtenfensters nicht sofort mit der Bearbeitung beginnen können, klicke auf *Reset*. Der Timer wird wieder auf Null zurückgesetzt. Wenn du die Bearbeitung der Nachricht unterbrechen möchtest, klicke auf *Pause* und anschließend erneut auf *Play* um mit der Bearbeitung fortzufahren.
====

[IMPORTANT]
.Nachricht als E-Mail versenden
====
Eine Nachricht wird nur als E-Mail versendet, wenn dafür eine <<crm/ticketsystem-nutzen#2900, Ereignisaktion>> eingerichtet wurde. +
Als Ereignis muss hier *Neue Nachricht* eingestellt werden und als Aktion empfiehlt sich *E-Mail versenden*. Die E-Mail-Vorlage, die hier gewählt wird, muss wiederum die Template-Variable *$TicketLastMessage* enthalten und als Empfänger die Option *Kunde*. Der E-Mail-Betreff sollte außerdem die Ticket-ID enthalten. Nutze dafür die Template-Variable *$TicketID*.
====

[#2500]
== Kommentar hinzufügen

Das Hinzufügen von Kommentaren funktioniert nach dem gleichen Prinzip wie das Hinzufügen von <<crm/ticketsystem-nutzen#2400, Nachrichten>>. Beachte, dass Kommentare nur intern sichtbar sind und dem Kunden nicht angezeigt werden. Die Kommentarfunktion dient dem Übermitteln von Informationen innerhalb deines Unternehmens. So können z.B. der Stand eines Tickets oder besondere Hinweise bezüglich des Themas oder des Kunden an andere Nutzer des Ticketsystems weitergegeben werden. Eine im Benutzerkonto gespeicherte <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#10, Grußformel>> wird automatisch in Kommentaren des Benutzers eingefügt.

Gleichzeitig startet mit der Erstellung des Kommentars im Bereich *Events* ein Timer, der die Bearbeitungszeit sekundengenau protokolliert. Diese Zeit kannst du im Feld *Min.* eingeben, wenn der Vorgang abgerechnet werden soll. Im unteren Eventbereich siehst du die bisherigen Events chronologisch gelistet, also z.B. wenn ein anderer Mitarbeiter dieses Ticket bereits bearbeitet hat.

[#2600]
== Thema zuweisen

Du kannst jeder Nachricht und jedem Kommentar ein Thema zuweisen. Die Zuweisung eines Themas ist eine freiwillige Angabe, die bei langen Texten hilft, auf einen Blick zu erfassen, worum es in der Nachricht oder dem Kommentar geht. Das Thema hat somit die Funktion einer Überschrift.

Wähle im Eingabefenster für Nachrichten oder Kommentare das Thema aus der Dropdown-Liste oberhalb des Textfeldes aus. Nach dem Speichern wird das Thema als Überschrift für den Text im Kommunikationsverlauf angezeigt. Alle Themen, die zur Auswahl verfügbar sein sollen, müssen zuvor im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* im  Tab *Themen* erstellt werden. Wie du Themen hinzufügst, ist im Kapitel <<crm/ticketsystem-nutzen#1100, Thema hinzufügen>> beschrieben.

[.instruction]
Thema zuweisen:

. Öffne das Menü *CRM » Ticketsystem*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne das zu bearbeitende Ticket.
. Klicke auf *Nachricht hinzufügen* bzw. *Kommentar hinzufügen*.
. Wähle ein Thema aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#2700]
== FAQ-Antwort einfügen

Du kannst in Nachrichten fertige Textbausteine einfügen, die du zuvor im Menü *CRM » FAQ* erstellt hast. Dies ist eine enorme Arbeitserleichterung, besonders wenn du häufig mit Standardfragen oder -problemen konfrontiert wirst. Du kannst hier auch längere Texte speichern und so bei der Bearbeitung deiner Tickets viel Zeit sparen. Lege eine sinnvolle Struktur von Ordnern, Unterordnern und Fragen an und stelle diese für das Ticketsystem im Menü *CRM » FAQ » Tab: Ordner* » _Ordner aufklappen_ » *Tab: Einstellungen* auf *sichtbar*.

[#2710]
=== Ordner erstellen

Erstelle eine Ordnerstruktur mit den Themen, zu denen du FAQs anlegen möchten.

[.instruction]
Ornder erstellen:

. Öffne das Menü *CRM » FAQ*.
. Wechsele in das Tab *Neuer Ordner*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-faq-neuer-ordner>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Ordner ist nach dem Neuladen im Tab *Ordner* sichtbar.


[[tabelle-faq-neuer-ordner]]
.Template-Variablen für E-Mail-Vorlagen im Ticketsystem
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
|Namen für den Ordner eingeben. +
*_Tipp:_* Die Ordnernamen gemäß der Themen wählen, zu denen es FAQs gibt.

|*öffentlich*
|*Sichtbar* wählen, wenn der Ordner z.B. auf der Webseite sichtbar sein soll.

|*Ticketsystem*
|*Sichtbar* wählen, wenn die FAQ auch im Tab *FAQ* einer Ticketnachricht oder eines Ticketkommentars sichtbar sein soll.

|*Oberordner*
|Wenn der neue Ordner ein Unterordner eines bestehenden Ordners sein soll, den Ordner aus der Dropdown-Liste wählen.

|====

[#2720]
=== FAQ anlegen

Erstelle nun im Tab *Neue FAQ* die FAQs, also Fragen mit Antworten.

[.instruction]
FAQ anlegen:

. Öffne das Menü *CRM » FAQ*.
. Wechsele in das Tab *Neue FAQ*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-neue-faq>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die FAQ ist nach dem Neuladen im Tab *FAQ* des Ordners sichtbar.

[[tabelle-neue-faq]]
.Template-Variablen für E-Mail-Vorlagen im Ticketsystem
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Ordner*
|Ordner aus der Dropdown-Liste wählen, in dem die FAQ sichtbar sein soll.

|*Öffentlich*
|*Sichtbar* wählen, wenn die FAQ auf der Webseite sichtbar sein soll. +
*_Wichtig:_* Wenn die Option *sichtbar* gewählt ist, muss der Ornder und eventuell der Unterordner auch als sichtbar eingestellt sein.

|*Ticketsystem*
|*Sichtbar* wählen, wenn die FAQ auch im Tab *FAQ* einer Ticketnachricht oder eines Ticketkommentare sichtbar sein soll.

|*Frage*
|Frage eingeben, z.B. "Kann ich Waren unfrei zurücksenden?"

|*Antwort*
|Antwort auf die Frage eingeben.

|====

[#2800]
== E-Mail-Vorlage manuell versenden

Kommunikation im Ticketsystem muss nicht ausschließlich mittels Nachrichten und Kommentaren erfolgen. Du kannst  auch <<crm/e-mails-versenden#1200, E-Mail-Vorlagen>> versenden. E-Mail-Vorlagen richtest du im Menü *System » Systemeinstellungen » Mandant* » _Mandant wählen_ » *E-Mail » Vorlagen* ein. Eine E-Mail-Vorlage enthält einen Standardtext, der für alle Empfänger passend ist und kann mit dynamischen Inhalten, die über Template-Variablen automatisch eingefügt werden, ergänzt werden.

Erstelle zunächst eine E-Mail-Vorlage. Verwende für die Betreffzeile und den Text z.B. die Template-Variablen wie in <<tabelle-template-variablen-ticketsystem>> aufgelistet. Die für eine E-Mail-Vorlage verfügbaren Template-Variablen werden über einen Klick auf *Template-Variablen und -Funktionen* angezeigt und können von dort in die Vorlage übernommen werden. <<tabelle-template-variablen-ticketsystem>> zeigt eine Auflistung sinnvoller Template-Variablen für das Ticketsystem.

Wähle z.B. für die E-Mail-Vorlage die Template-Variablen *$TicketID* und *$TicketTitle*, wenn du im Betreff die Ticket-ID und den Titel des Tickets sehen möchtest. Wenn der Text den Status und die Priorität sowie einen Link zum Ticket enthalten soll, wähle die Template-Variablen *$TicketStatus*, *$TicketPriority* und *$TicketBackendURL* und füge diese in den Textteil der Vorlage ein.

[.instruction]
E-Mail-Vorlage erstellen:

. Öffne das Menü *System » Systemeinstellungen » Mandant* » _Mandant wählen_ » *E-Mail » Vorlagen*.
. Klicke auf *Neue E-Mail-Vorlage* (icon:plus-square[role="green"]).
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen auf der Handbuchseite <<crm/e-mails-versenden#, E-Mails versenden>> im Kapitel <<crm/e-mails-versenden#1200, E-Mail-Vorlage erstellen>>.
. Wähle für *Inhalt* die Einstellung *Nur HTML-formatierter Text*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[IMPORTANT]
.Nur HTML-formatierter Text
====
Wähle bei den E-Mail-Vorlagen im Tab *Einstellungen* für *Inhalt* die Einstellung *Nur HTML-formatierter Text*, da ansonsten die Template-Variablen nicht übersetzt werden.
====

[[tabelle-template-variablen-ticketsystem]]
.Template-Variablen für E-Mail-Vorlagen im Ticketsystem
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*$TicketBackendURL*
|Verlinkt zum Ticket im Menü *CRM » Ticketsystem*.

|*$TicketHistory*
|Zeigt den zuletzt gespeicherten Text im Ticket an, d.h. den Text eines Kommentars oder einer Nachricht.

|*$TicketID*
|Zeigt die ID des Tickets an, aus dem die E-Mail versendet wurde.

|*$TicketLastComment*
|Zeigt den Text des letzten Kommentars an.

|*$TicketLastMessage*
|Zeigt den Text der letzten Nachricht an.

|*$TicketPriority*
|Zeigt die Priorität des Tickets an. Die Werte der Sterne werden aufsteigend mit Zahlen von 0 bis 5 dargestellt.

|*$TicketStatus*
|Zeigt den Status des Tickets an.

|*$TicketTitle*
|Zeigt den Titel des Tickets an.

|*$TicketURL*
|Verlinkt zum Ticket im Bereich *Mein Konto* des Kunden. Der Kunde kann dann dort die Nachricht lesen und direkt eine Antwortnachricht eingeben und versenden. +
Beachte dazu das Kapitel <<crm/ticketsystem-nutzen#5500, Tickets im Mein Konto-Bereich erstellen>>.

|*$SignatureText*
|Folgende Aussage ist nur gültig, wenn E-Mail-Vorlagen manuell versendet werden: Zeigt die Signatur an, die in den E-Mail-Einstellungen des Systems gespeichert sind.

|*$SignatureHTML*
|Folgende Aussage ist nur gültig, wenn <<crm/ticketsystem-nutzen#2900, E-Mail-Vorlagen über eine Ereignisaktion>> versendet werden: Zeigt die Grußformel und die Signatur an, die in den Einstellungen des Benutzerkontos gespeichert sind. +
Bei dieser Template-Variable wird die Signatur des Benutzers angezeigt, wenn diese beim Benutzer gespeichert ist. Diese Signatur hat Priorität vor der in den E-Mail-Einstellungen eingegebenen Signatur des Systems.
|====

Gehe wie im Folgenden beschrieben vor, um E-Mail-Vorlagen manuell zu versenden.

[.instruction]
E-Mail-Vorlage manuell versenden:

. Öffne das Menü *CRM » Ticketsystem*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne das zu bearbeitende Ticket.
. Klicke auf *E-Mail-Vorlage senden* (icon:envelope-o[role="purple"]).  +
→ Das Fenster *E-Mail-Vorlage senden* wird geöffnet.
. Wähle eine E-Mail-Vorlage aus der Dropdown-Liste.
. Klicke auf *E-Mail-Vorlage senden* (icon:cog[]).

Wenn das Ticket nicht mit einem Kunden verknüpft ist, kann die E-Mail-Vorlage nicht versendet werden. Als Signatur der E-Mails, die über E-Mail-Vorlagen manuell versendet werden, wird die Signatur aus den E-Mail-Einstellungen des Systems verwendet.

[#2900]
== E-Mail-Vorlage automatisch versenden

Im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Ereignisse* wählst du anhand von Filtern Tickets und ordnest diesen automatische Aktionen zu, die durch eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ausgeführt werden sollen. Ein Beispiel wäre, dass bei Eingang eines Tickets automatisch der Versand einer E-Mail-Vorlage ausgelöst wird, die dem Kunden den Eingang des Tickets bestätigt und ihm die weitere Vorgehensweise erläutert.

Wie in <<tabelle-template-variablen-ticketsystem>> beschrieben, wird bei Verwendung der Template-Variable *$SignatureHTML* die Grußformel und die Signatur angezeigt, die in den Einstellungen des Benutzerkontos gespeichert sind. Diese Signatur hat Priorität vor der in den E-Mail-Einstellungen eingegebenen Signatur des Systems.

Beachte, dass auch für den Versand von Nachrichten und Kommentaren per E-Mail eine Ereignisaktion eingerichtet werden muss. Wenn du deinen Kunden im Ticketsystem per Nachricht antwortest, aber keine Ereignisaktion eingerichtet haben, die die letzte Ticketnachricht als E-Mail versendet, erhält der Kunde deine Antwort nicht. Weitere Informationen zur Kundenkommunikation im Ticketsystem findest du in den Kapiteln <<crm/ticketsystem-nutzen#2400, Nachricht hinzufügen>>, <<crm/ticketsystem-nutzen#2500, Kommentar hinzufügen>>, <<crm/ticketsystem-nutzen#2600, Thema zuweisen>>, <<crm/ticketsystem-nutzen#2700, FAQ-Antwort einfügen>> und <<crm/ticketsystem-nutzen#2800, E-Mail-Vorlage manuell versenden>>.

Weitere Informationen zum Einrichten von Ereignisaktionen findest du auf der Handbuchseite <<automatisierung/ereignisaktionen#, Ereignisaktionen>>.

[IMPORTANT]
.Widersprüchliche Filteroptionen vermeiden
====
Vermeide widersprüchliche Filteroptionen, wenn du für eine Aktion mehrere Filter einrichtest. So führen z.B. verschiedene Statusoptionen bei gleichem Tickettyp zu einem Fehler.

Beispiel: 1. Filter: Typ *eBay*, Status *Geschlossen*. 2. Filter: Typ *eBay*, Status *Bearbeitet*.
====

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um z.B. eine E-Mail zu erhalten, wenn in deinem Ticketsystem eine neue Ticketnachricht eingegangen ist.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » CRM » Ticketsystem » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-neue-nachricht-ticketsystem>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-neue-nachricht-ticketsystem>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
--
[[tabelle-ereignisaktion-neue-nachricht-ticketsystem]]
.Ereignisaktion zum automatischen Benachrichtigen bei neuen Nachrichten im Ticketsystem
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Neue Nachricht vom Kunden*
|

|*Filter*
|*Eigner*
|Eigner wählen.

|*Aktion*
|*E-Mail versenden*
|Vorlage und Empfänger wählen.
|====

[#3000]
== Tickets automatisch löschen

Im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Aktionen* richtest du Aktionen ein, die von deinem plentymarkets System zu einem bestimmten Zeitpunkt automatisch ausgeführt werden. Damit legst du z.B. fest, dass Tickets, die für eine bestimmte Zeit nicht bearbeitet wurden und sich in einem bestimmten Status befinden, automatisch gelöscht werden.

Gehe wie im Folgenden vor, um das oben beschriebene Beispiel einzurichten.

[.instruction]
Tickets automatisch löschen:

. Öffne das Menü *System » Systemeinstellungen » CRM » Ticketsystem » Aktionen*.
. Klicke auf *Aktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Aktion erstellen* wird geöffnet.
. Gib den Namen ein.
. Wähle die Zeit, zu der die Aktion täglich ausgeführt werden soll, aus der Dropdown-Liste.
. Klicke auf *Speichern* (icon:save[role="green"]). +
→ Die Aktion wird erstellt.
. Klicke auf *Filter hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Filter hinzufügen* wird geöffnet.
. Wähle den Filter *Letzter Statuswechsel*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]).
. Wähle eine Option aus der Dropdown-Liste.
. Klicke auf *Filter hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Filter hinzufügen* wird geöffnet.
. Wähle den Filter *Typ/Status*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]).
. Aktiviere den zuvor erstellten <<crm/ticketsystem-nutzen#900, Status>>. +
→ Beachte dazu auch den zuvor erstellten <<crm/ticketsystem-nutzen#800, Typ>>.
. Klicke auf *Aktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Aktion hinzufügen* wird geöffnet.
. Wähle die Aktion *Löschen*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]).
. Setze ein Häkchen.
. Setze ein weiteres Häkchen bei der Option *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

In diesem Menü kannst du beliebig viele Aktionen erstellen und für diese Aktionen Filter und Uhrzeiten wählen. Weitere Informationen zum Einrichten des Aktionsmanagers findest du auf der Handbuchseite <<automatisierung/aktionsmanager#, Aktionsmanager>>.

[#3100]
== Allgemeine Ticketvorlage erstellen

Im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Vorlagen* erstellst du Vorlagen für Tickets. Mit Vorlagen gestaltest du die Arbeit mit dem Ticketsystem effizienter. Weiterhin stellst du ein, für welche Benutzer die Ticketvorlage verfügbar sein soll, d.h. ob für bestimmte Rollen oder für alle. So bleibt selbst bei einer Vielzahl an Vorlagen die Auswahl übersichtlich.

[.instruction]
Allgemeine Ticketvorlage erstellen:

. Öffne das Menü *System » Systemeinstellungen » CRM » Ticketsystem » Vorlagen*.
. Klicke auf *Neue Vorlage* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Vorlage* wird geöffnet.
. Gib den *Namen* ein.
. Gib die *Position* ein.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Vorlage wird erstellt und geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-einstellungen-ticketvorlage>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-einstellungen-ticketvorlage]]
.Einstellungen in der Ticketvorlage
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
|Name der Vorlage wird angezeigt. Der Name kann hier geändert werden.

|*Position*
|Zahl eingeben. Die Zahl legt die Reihenfolge der Vorlagen fest. Die Sortierung erfolgt standardmäßig nach aufsteigender Position. Die Zahl kann hier geändert werden. +
*_Tipp:_* Positionsnummern in 10er-Schritten eingeben, damit später neue Vorlagen dazwischen eingefügt werden können.

|*Titel*
|Titel eingeben, damit Tickets, bei denen diese Vorlage angewendet wird, diesen Titel erhalten. Der Titel kann beim Erstellen des Tickets geändert werden.

|*Kunde*
|Kunde wählen, um eine Vorlage für diesen Kunden zu erstellen.

|*Vertraulichkeit*
|Aktivieren, um eine Vorlage für vertrauliche Tickets zu erstellen. Bei vertraulichen Tickets erhalten nur Ticketeigner Nachrichten. Kunden erhalten bei dieser Einstellung trotz Ereignisaktionen keine Nachrichten.

|*Mandant (Shop)*
|Mandant (Shop) wählen, für den die Vorlage gültig sein soll.

|*Typ*
|Tickettyp wählen, um eine Vorlage für diesen Typ zu erstellen. Tickettypen werden im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* im Tab <<crm/ticketsystem-nutzen#800, Typen &amp; Status>> erstellt.

|*Status*
|Ticketstatus wählen, um eine Vorlage für diesen Status zu erstellen. Ticketstatus werden im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen*  im Tab <<crm/ticketsystem-nutzen#900, Typen &amp; Status>> erstellt.

|*Priorität*
|Priorität wählen, um eine Vorlage für diese Priorität zu erstellen.

|*Eigner*
|Eigner wählen, um eine Vorlage für diesen Eigner zu erstellen. Ob ein Benutzer als Eigner im Ticketsystem gewählt werden kann, wird im <<basics/admin-aufgaben/benutzer-verwalten#40, Benutzerkonto>> festgelegt.

|*Sichtbarkeit*
|Eine der folgenden Optionen wählen: *Öffentlich*, *Persönlich* oder *Benutzerrollen*. +
*Öffentlich* = Die Vorlage steht jedem Benutzer zur Verfügung. +
*Persönlich* = Die Vorlage steht dem Benutzer zur Verfügung, der die Vorlage erstellt hat. Weitere Informationen findest du im Kapitel <<crm/ticketsystem-nutzen#3200, Persönliche Ticketvorlage erstellen>>. +
*Benutzerrollen* = Bei Auswahl dieser Option wird eine weitere Einstellung geöffnet. In dieser Einstellung die Benutzerrollen aktivieren, für die die Vorlage sichtbar sein soll.

|*Benutzerrollen*
|Nur sichtbar, wenn unter *Sichtbarkeit* die Option *Benutzerrollen* gewählt wurde. Benutzerrollen aktivieren, für die die Vorlage sichtbar sein soll.

|*Tags*
|Tags wählen, um eine Vorlage mit diesen Tags zu erstellen. Tags werden im Menü <<basics/arbeiten-mit-plentymarkets/tags#, System » Systemeinstellungen » Einstellungen » Tags>> erstellt.

|*Endtermin*
|Anzahl an Tagen eingeben. Die Vorlage enthält den Endtermin des Tickets, der nach dieser Anzahl von Tagen nach dem Erstellen des Tickets liegt.

|*Wiedervorlage*
|Anzahl an Tagen eingeben und Uhrzeit wählen. Die Vorlage enthält das Datum und die Uhrzeit, an dem das Ticket wieder vorgelegt wird.

|*Nachricht*
|*FAQ* oder *Eigene Nachricht* aktivieren. +
*FAQ* = Auf *Bearbeiten* klicken. Das Fenster *FAQ auswählen* wird geöffnet. <<omni-channel/online-shop/webshop-einrichten/cms#faq, FAQ>> wählen, die bei Verwendung der Vorlage eingegeben wird. Auf *Übernehmen* klicken. +
*Eigene Nachricht* = Nachricht eingeben, die bei Verwendung der Vorlage eingegeben wird.

|*Kommentar*
|*FAQ* oder *Eigener Kommentar* aktivieren. +
*FAQ* = Auf *Bearbeiten* klicken. Das Fenster *FAQ auswählen* wird geöffnet. <<omni-channel/online-shop/webshop-einrichten/cms#faq, FAQ>> wählen, die bei Verwendung der Vorlage eingegeben wird. Auf *Übernehmen* klicken. +
*Eigener Kommentar* = Kommentar eingeben, der bei Verwendung der Vorlage eingegeben wird.

|*Grußformel einfügen*
|Aktivieren, um die Grußformel am Ende einer Nachricht oder eines Kommentars automatisch einzufügen.
|====

Du bearbeitest eine Vorlage, indem du in das Textfeld klickst. Ein Klick auf *Löschen* (icon:minus-square[role="red"]) löscht die Zeile nach Bestätigung.

[#3200]
== Persönliche Ticketvorlage erstellen

Im Menü *CRM » Ticketsystem* in der Ticketübersicht hast du auch die Möglichkeit benutzerbezogene Vorlagen zu erstellen. Diese persönlichen Vorlagen sind dort und im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Vorlagen* nur für den Benutzer sichtbar, der die Vorlagen erstellt hat. Die persönlichen Vorlagen werden in einem separaten Fenster erstellt und bearbeitet. Dieses Fenster wird nach einem Klick auf *Persönliche Vorlagen* geöffnet.

Richte persönliche Ticketvorlagen nach dem selben Schema wie die allgemeinen Ticketvorlagen ein. Beachte dazu das Kapitel <<crm/ticketsystem-nutzen#3100, Allgemeine Ticketvorlage erstellen>>. Die persönlichen Vorlagen sind bei den allgemeinen Vorlagen für den Benutzer sichtbar, der sie erstellt hat. Allerdings werden die allgemeinen Vorlagen bei den persönlichen Vorlagen nicht angezeigt. Welche Vorlagen angezeigt werden, wird durch die Einstellung der Option *Sichtbarkeit* im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Vorlagen* gesteuert. Diese Einstellung steht bei persönlichen Vorlagen auf *Persönlich*.

[#3300]
== Ticketübersicht anzeigen

Öffne das Menü *CRM » Ticketsystem*. Erstellte Tickets werden in der Übersicht im Tab *Tickets* angezeigt. Du kannst in der Übersicht wesentliche Eigenschaften des Tickets auf einen Blick erkennen, z.B. Alter, Titel, Kundennamen und Fortschritt. Wähle mit der Funktion <<basics/arbeiten-mit-plentymarkets/allgemeine-funktionen#50, Ansicht einrichten>>, welche Parameter du in der Ticketübersicht anzeigen möchtest.

Mit einem Klick auf das Ticket wird dieses in einem eigenen Tab geöffnet. Du hast die Möglichkeit das Ticket dort zu <<crm/ticketsystem-nutzen#3500, bearbeiten>>.

Im Tab *Ordner* stehen bereits voreingestellte Ordner zur Verfügung, in die deine Tickets anhand von bestimmten Kriterien eingeordnet sind, z.B. unerledigte Tickets. Klicke auf den Ordner, um z.B. alle unerledigten Tickets im Tab *Tickets* anzuzeigen. Diese voreingestellten Ordner kannst du weder umbenennen noch löschen. Du kannst  jedoch <<crm/ticketsystem-nutzen#4500, eigene Ordner>> erstellen. Diese werden dann der Liste im Tab *Ordner* hinzugefügt.

Im Menü *CRM » Ticketsystem* im Tab *Tickets* kannst du oberhalb der Ticketübersicht ein neues Ticket manuell oder aus einer Vorlage erstellen. Du kannst dort auch persönliche Vorlagen wählen oder die Gruppenfunktion nutzen. <<tabelle-ticketuebersicht>> erläutert die Einstellungen, die du im Tab *Tickets* vornehmen kannst.

[[tabelle-ticketuebersicht]]
.Einstellungen im Menü *CRM » Ticketsystem* im Tab *Tickets*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Neues Ticket*
|Klicken, um ein neues Ticket manuell zu erstellen.

|*Neues Ticket aus Vorlage*
|Klicken, um ein Ticket zu erstellen, in dem Einstellungen und Einträge, z.B. Mustertexte aus einer Vorlage, übernommen werden.

|*Persönliche Vorlagen*
|Persönliche Vorlagen erstellen oder bearbeiten. Die persönlichen Vorlagen sind auch bei den <<crm/ticketsystem-nutzen#3100, allgemeinen Vorlagen>> sichtbar. Allerdings werden die allgemeinen Vorlagen bei den persönlichen Vorlagen nicht angezeigt.

|*Gruppenfunktion*
|Klicken, um mehrere zuvor aktivierte Tickets gleichzeitig zu bearbeiten.

|*Suchoptionen*
|Über die Dropdown-Listen Suchoptionen einstellen oder Daten eingeben und so die Tickets in der Übersicht anzeigen, die angezeigt oder bearbeitet werden sollen, z.B. nur die Tickets eines bestimmten Eigners mit einer bestimmten Priorität. +
Auf *Suchen* klicken, um die Tickets mit den gewählten Eigenschaften aufzulisten. +
Weitere Informationen zu den Suchoptionen findest du im Kapitel <<crm/ticketsystem-nutzen#3400, Ticket suchen>>.

|*Alter in Tagen*
|Das Alter des Tickets wird mit einer Farbe dargestellt: +
Grün = Das Ticket ist 0 bis 3 Tage alt. +
Gelb = Das Ticket ist 4 bis 5 Tage alt. +
Orange = Das Ticket ist 6 bis 7 Tage alt. +
Rot = Das Ticket ist mindestens 8 Tage alt.
|====

[TIP]
.Reihenfolge der Sortierung in den Spalten ändern
====
Du kannst in der Ticketübersicht die Reihenfolge der Sortierung in den Spalten ändern. Klicke dazu auf das Dreieck in der Titelleiste. Die Reihenfolge der Sortierung kannst du bei den folgenden Spalten ändern: *Alter in Tagen*, *ID*, *Prio*, *Erstellt am*, *Letzte Änderung*, *Fortschritt* und *Wiedervorlage*. Voraussetzung hierfür ist, dass du die Parameter über <<basics/arbeiten-mit-plentymarkets/allgemeine-funktionen#50, Ansicht einrichten>> aktiviert hast.
====

[#3400]
== Ticket suchen

Um die Suche nach deinen Tickets so genau wie möglich eingrenzen zu können, stehen dir in der Suchmaske im Tab *Tickets* mehrere Eingabefelder und Filter zur Verfügung. Klappe den Bereich *Suchen* auf, um weitere Filter und Eingabefelder zu nutzen und so die Suche noch weiter einzugrenzen.

[.instruction]
Ticket suchen:

. Öffne das Menü *CRM » Ticketsystem*.
. Wähle im Tab *Tickets* im oberen Bereich die Filter bzw. gib die Daten in die Eingabefelder ein. Beachte dazu die Erläuterungen in <<tabelle-ticket-suchen>>.
. Klicke auf *Suchen* (icon:search[role="blue"]).  +
→ Die Tickets, die mit den gewählten Filtern übereinstimmen, werden angezeigt.

[[tabelle-ticket-suchen]]
.Suchoptionen im Menü *CRM » Ticketsystem* im Tab *Tickets*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Suche ausführen.

|*Ticket-Daten*
|Text eingeben, um nach diesen Inhalten zu suchen.

|*Prio*
|Priorität wählen, um nur Tickets dieser Dringlichkeitsstufe anzuzeigen.

|*Typ/Status*
|Kombiniert nach Tickettyp und Ticketstatus suchen. Eine, mehrere oder alle Optionen aus der Dropdown-Liste wählen. +
Im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* können <<crm/ticketsystem-nutzen#800, Typen>> und <<crm/ticketsystem-nutzen#900, Status>> bearbeitet und neue hinzugefügt werden.

|*Statusgruppe*
|Eine, mehrere oder alle Optionen aus der Dropdown-Liste wählen. +
Im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* können <<crm/ticketsystem-nutzen#1000, Statusgruppen>> bearbeitet und neue erstellt werden.

|*Eigner*
|Ticketsuche auf einen Eigner eingrenzen. In der Dropdown-Liste stehen alle Benutzer zur Auswahl, für die im Tab *Eigner* des Benutzerkontos die Option *Ticket* aktiviert wurde.

|*Kundenklasse*
|Kundenklasse wählen, um nur Tickets von Kunden dieser Kundenklasse zu suchen. Kundenklassen werden im Menü <<crm/kontakte-verwalten#15, System » Systemeinstellungen » CRM » Kundenklassen>> erstellt.

|*Mandant (Shop)*
|Mandant (Shop) aus der Dropdown-Liste wählen.

|*Kunden-ID*
|Kunden-ID eingeben, um nur die Tickets des Kunden mit dieser ID zu suchen.

|*Endtermin*
|Eine der folgenden Optionen aus der Dropdown-Liste wählen, um nur Tickets zu suchen, deren Endtermin der Option entspricht: *gestern*, *heute*, *morgen*, *überschritten* oder *in der Zukunft*.

|*Rolle*
|Eine, mehrere Rollen oder alle Optionen aus der Dropdown-Liste wählen. Rollen werden im Menü <<crm/ticketsystem-nutzen#700, System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen>> erstellt.

|*Vergleichsoperator für den Fortschritt*
|Mit dem Vergleichsoperator eingrenzen, ob der Fortschritt eines Tickets größer, kleiner oder gleich dem gewählten Fortschritt sein soll.

|*Fortschritt*
|Prozentzahl aus der Dropdown-Liste wählen, um nur Tickets zu suchen, die der Kombination aus dem gewählten Vergleichsoperator und dem Fortschritt entsprechen.

|*Wiedervorlage*
|Wiedervorlage aus der Dropdown-Liste wählen, um nur Tickets zu suchen, in denen diese Wiedervorlage eingestellt ist. +
Per Aktionsmanager im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Aktionen* kann an das Ticket erinnert werden. Ein Beispiel, wie man eine Aktion einrichtet sowie Filter und Uhrzeit wählt, ist in diesem <<crm/ticketsystem-nutzen#3000, Kapitel>> beschrieben.

|*Tags*
|In das Feld klicken. Einen oder mehrere Tags wählen, um nur Tickets zu suchen, in denen diese Tags hinterlegt sind. Tags müssen zuvor im Menü *System » Systemeinstellungen » Einstellungen » Tags* erstellt werden.
|====

[#3500]
== Ticket bearbeiten

Ein Ticket besteht aus einer Abfolge von Nachrichten und Kommentaren. Dabei sind Kommentare nur intern sichtbar. Zusätzlich können Dateien und Aufgaben in einem Ticket gespeichert werden. Tickets können auch verkettet erstellt werden: Ein Ticket kann mehrere Kinder haben und diese wiederum eigene Kindertickets.

In den folgenden Unterkapiteln wird beschrieben, welche Einstellungen du in den Tabs eines Tickets vornehmen kannst.

[#3600]
=== Ticketeinstellungen anzeigen und ändern

Im Menü *CRM » Ticketsystem » Ticket öffnen* im Tab *Ticket* siehst du die Einstellungen deines Tickets auf einen Blick. Einige Einstellungen kannst du hier auch ändern. <<tabelle-ticket-bearbeiten>> erläutert die Einstellungsmöglichkeiten in deinen Tickets.

[[tabelle-ticket-bearbeiten]]
.Einstellungen im Menü *CRM » Ticketsystem* » _Ticket öffnen_ » *Tab: Ticket*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Quelle des Tickets*
|Das Symbol zeigt die Quelle des Tickets an. +
plentymarkets Logo = *Quelle des Tickets: Backend* +
Weltkugel = *Quelle des Tickets: Frontend* +
eBay-Logo = *Quelle des Tickets: eBay* +
Briefsymbol = *Quelle des Tickets: E-Mail*

|*Speichern*
|Speichert die Einstellungen.

|*Endtermin*
|Zeigt die Anzahl in Tagen bis zum Endtermin sowie den Fortschritt in Prozent an. +
Wenn noch kein Endtermin gewählt ist, Termin aus dem Kalender wählen. Der Balken wird erst angezeigt, nachdem das Datum gewählt und gespeichert ist. Der Endtermin kann mit einem Klick geändert werden.

|*Priorität*
|Zeigt die Priorität des Tickets an. Die Priorität ist in 6 Stufen gestaffelt. +
Grauer Stern = niedrigste Priorität (Standardeinstellung) +
2 gelbe Sterne = höchste Priorität

|*Typ*
|Zeigt den Typ an. Tickettypen werden im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* im Tab  <<crm/ticketsystem-nutzen#800, Typen &amp; Status>> erstellt.

|*Status*
|Zeigt den Status an. Ticketstatus werden im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen* im Tab <<crm/ticketsystem-nutzen#900, Typen &amp; Status>> erstellt.

|*Ordner*
|Zeigt den Ordner an. Ordner werden im Menü *System » Systemeinstellungen » CRM » Ticketsystem* im Tab <<crm/ticketsystem-nutzen#4500,Ordner>> erstellt.

|*Tag der Wiedervorlage*
|Zeigt den Tag der Wiedervorlage an.

|*Wiedervorlage bis Stunde/ +
Wiedervorlage bis Minute*
|Uhrzeit aus den Dropdown-Listen wählen.

|*ID*
|Zeigt die Ticket-ID an. Die ID wird automatisch vom System vergeben und kann nicht geändert werden.

|*Alter*
|Zeigt das Alter des Tickets in Tagen an. Je nach Alter wird das Ticket in einer anderen Farbe dargestellt: +
Grün = Das Ticket ist 0 bis 3 Tage alt. +
Gelb = Das Ticket ist 4 bis 5 Tage alt. +
Orange = Das Ticket ist 6 bis 7 Tage alt. +
Rot = Das Ticket ist mindestens 8 Tage alt.

|*Fortschritt*
|Zeigt den Fortschritt in Prozent anhand eines Balkens an. Die Prozentzahl wird in dem Balken angezeigt.

|*Kunde*
|Zeigt die ID und den Namen des Kunden an. Die Kunden werden teilweise <<crm/ticketsystem-nutzen#2100, automatisch zugeordnet>>, z.B. beim automatischen Erstellen von Tickets aus E-Mails.

|*Ticket als vertraulich definieren (unsichtbar für Kunden)*
|Klicken, um das Ticket als vertraulich zu definieren. Wenn das Ticket vertraulich ist, ist die Nachrichtenfunktion deaktiviert. Vertrauliche Tickets sind für Kunden nicht sichtbar.

|*Auftrags-ID*
|Zeigt die Auftrags-ID an, wenn das Ticket mit einem Auftrag verknüpft ist.

|*Mandant (Shop)*
|Zeigt den Mandant (Shop) an, mit dem das Ticket verknüpft ist.
|====

[#3700]
=== Kundendaten anzeigen

Im Tab *Kunde* des Tickets im Menü *CRM » Ticketsystem* sind die Kundendaten enthalten wie sie auch im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte » Kontakt öffnen>> angezeigt werden. Du kannst den Kundendatensatz hier auch bearbeiten. Dieses Tab ist nur sichtbar, wenn das Ticket mit einem Kunden verknüpft ist.

[#3800]
=== Aufträge anzeigen

Im Tab *Aufträge suchen* des Tickets im Menü *CRM » Ticketsystem* werden alle Aufträge des Kunden angezeigt. Du kannst die Aufträge hier auch bearbeiten oder suchen. Dieses Tab ist nur sichtbar, wenn das Ticket mit einem Kunden verknüpft ist.

[#3900]
=== Anhang anzeigen

Im Menü *CRM » Ticketsystem » Ticket öffnen* im Tab *Anhang* siehst du alle Dateianhänge, die in diesem Tab hochgeladen wurden. Sowohl der Kunde als auch die Mitarbeiter können Dateien an ein Ticket anhängen und dauerhaft einsehen. Im Tabtitel wird die Anzahl der Anhänge in Klammern angezeigt. Sobald die erste Datei erfolgreich hochgeladen wurde, wird eine Tabelle angezeigt. Die Tabelle listet den Dateinamen, den Namen des Mitarbeiters oder Kunden, der die Datei hochgeladen hat, sowie die Sichtbarkeit und das Datum auf.

Bilddateien werden nach einem Klick unmittelbar zur Ansicht geöffnet. Wenn diese Funktion vom Browser nicht unterstützt wird, wird die Datei per Download zur Verfügung gestellt. Über *Sichtbarkeit* entscheidest du, ob die Datei auch für deine Kunden sichtbar sein soll oder nur für dich und deine Mitarbeiter.

Wenn du im Menü *CRM » Ticketsystem* im Tab *Tickets* über <<basics/arbeiten-mit-plentymarkets/allgemeine-funktionen#50, Ansicht einrichten>> die Option *Anhang* aktiviert hast, siehst du direkt in der Ticketübersicht, welches Ticket einen Anhang hat.

[IMPORTANT]
.Zulässige Dateitypen für den Upload
====
Folgende Dateitypen sind zulässig und können hochgeladen werden: *COMMA*, *CSS*, *CSV*, *DOC*, *DOCX*, *EXCEL*, *GIF*, *GZIP*, *HTML*, *JPEG*, *MSWORD*, *ODC*, *ODF*, *ODG*, *ODM*, *ODS*, *ODT*, *OTG*, *OTH*, *OTS*, *OTT*, *OXT*, *PNG*, *PDF*, *RICHTEXT*, *RTF*, *SWF*, *SDA*, *SDC*, *SDW*, *SXW*, *STW*, *TEXT*, *X_EXCEL*, *X_LATEX*, *X_TAR*, *XLS*, *X_XLS*, *XML*, *TIFF*, *ZIP*.
====

[#4000]
=== Aufgabe erstellen

Aufgaben helfen Ihnen, Tätigkeiten zu planen und diese sich selbst oder Mitarbeitern zuzuweisen. Aufgaben, die du im Ticket im Tab *Aufgaben* erstellst, sind mit dem Ticket verknüpft. Diese Verknüpfung wird auch in der Aufgabenübersicht im Menü *Start » Aufgaben* angezeigt. Im Ticket wird im Tabtitel die Anzahl der Aufgaben in Klammern angezeigt. In diesem Kapitel wird auch beschrieben, wie du Aufgaben suchst.

[.instruction]
Aufgabe erstellen:

. Öffne das Menü *CRM » Ticketsystem*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne das zu bearbeitende Ticket.
. Wechsele in das Tab *Aufgaben*.
. Klicke auf *Neue Aufgabe* (icon:plus-square[role="green"]).
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen im Kapitel <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#300, Aufgabe erstellen>>auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#, Aufgaben und Kalender>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Aufgabe wird im Tab *Aufgaben* angezeigt.

[#4100.subhead]
Aufgabe suchen

Gehe wie im Folgenden beschrieben vor, um nach bereits erstellten Aufgaben zu suchen.

[.instruction]
Aufgabe suchen:

. Öffne das Menü *CRM » Ticketsystem*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne das zu bearbeitende Ticket.
. Wechsele in das Tab *Aufgaben*.
. Klicke oben links auf den Pfeil, um das Tab *Filter* zu öffnen (icon:angle-right[]).
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen im Kapitel <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#400, Aufgaben suchen>> auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#, Aufgaben und Kalender>>.
. Klicke auf *Suchen* (icon:search[role="blue"]).

[#4200]
=== Tickets verknüpfen

Im Menü *CRM » Ticketsystem* im Tab *Kinder* eines Tickets können Tickets miteinander verknüpft werden, d.h. du kannst einem Ticket ein weiteres Ticket als Kinderticket zuordnen oder ein solches zugeordnetes Unterticket im Tab *Kinder* neu erstellen. Ein Ticket kann mehrere Kindertickets beinhalten (Eltern-Kind-Prinzip) und diese wiederum können eigene Kindertickets bekommen. Diese Eigenschaft ist besonders für größere Projekte sehr wichtig, um Teilaufgaben in Form einzelner Tickets auf mehrere Eigner oder Teams verteilen zu können. Über das ursprüngliche Elternticket kann der Bearbeitungsstand der Kindertickets eingesehen werden. Die Anzahl der Kindertickets wird in Klammern im Tab *Kinder* angezeigt.

[#4300]
==== Ticket als Kinderticket zuordnen

Du kannst bestehende Tickets als Kindertickets zuordnen. Die Zuordnung erfolgt im Tab *Ticketsuche*.

[.instruction]
Ticket als Kinderticket zuordnen:

. Öffne das Menü *CRM » Ticketsystem*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne das zu bearbeitende Ticket.
. Wechsele in das Tab *Kinder*.
. Wechsele in das Tab *Ticketsuche*.
. Klicke oben links auf den Pfeil, um das Tab *Ordner* zu öffnen (icon:angle-right[]).
. Wähle einen Ordner im Tab *Ordner*.
. Wähle die Filtereinstellungen im Bereich *Suchen* des Tabs *Tickets*.
. Klappe den Bereich *Suchen* auf, um weitere Filtereinstellungen zu wählen.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Tickets werden aufgelistet.
. Aktiviere die Tickets, die dem Hauptticket als Kindertickets zugeordnet werden sollen.
. Klicke auf *Hinzufügen*.

[IMPORTANT]
.Kinderticket im Tab *Kinder* erstellen
====
Ein Kinderticket erstellst du direkt im Tab *Kinder* des Tickets im Menü *CRM » Ticketsystem*. Klicke auf *Neues Ticket* und nimm die Einstellungen vor. Das Ticket wird automatisch dem Hauptticket zugeordnet und dort im Tab *Kinder* angezeigt.
====

[#4400]
==== Kinderticket bearbeiten

Tickets, die im Tab *Ticketsuche* zugeordnet wurden, werden aus dem Tab *Ticketsuche* in das Tab *Kinder* verschoben und dort angezeigt. Im Tab *Kinder* werden nur Kindertickets des Haupttickets angezeigt. Du kannst die Zuordnung im Tab *Kinder* auch wieder rückgängig machen. Aktiviere das Kinderticket und klicke auf *Entfernen*. Das Kinderticket wird dann wieder in das Tab *Ticketsuche* verschoben bzw. es wird wieder zu einem allgemeinen Ticket ohne Zuordnung.

[#4500]
== Ordner erstellen

Du hast die Möglichkeit, eigene Ordner zu erstellen. Auch verzweigte Ordnerstrukturen sind möglich. Ordner eignen sich, um Tickets zusammenzufassen, die nicht aufgrund von Filtereinstellungen zusammengefasst werden können, aber die du trotzdem aufgrund anderer Gesichtspunkte auf einen Blick sehen möchtest. Deine eigenen Ordner kannst du umbenennen und löschen, wenn diese nicht mehr benötigt werden. Deine eigenen Ordner siehst nur du selbst.

[.instruction]
Ordner erstellen:

. Öffne das Menü *CRM » Ticketsystem*.
. Klicke im Tab *Ordner* auf *Neuen Ordner erstellen*. +
→ Das Fenster *Neuen Ordner erstellen* wird geöffnet.
. Gib den Namen oder den Pfad ein. Beachte dazu die Erläuterung in der folgenden Box.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der soeben erstellte Ordner wird der Liste im Tab *Ordner* hinzugefügt.

[NOTE]
.Hauptordner und Unterordner erstellen
====
Wenn du im Ticketsystem einen neuen Ordner erstellst, gib einen Namen für diesen Ordner ein, wenn der Ordner in der Hauptebene erstellt werden soll. Wähle per Klick einen bestehenden Ordner, wenn du unter dem Hauptordner einen Unterordner erstellen möchtest. Gib den neuen Namen mit Schrägstrich hinter dem Namen des Hauptordners ein. Alternativ gibst du den Pfad in das Textfeld ein, der z.B. aus dem Namen eines Hauptordners sowie aus dem Namen des neuen Ordners besteht. +
Beispiel: Großkunde/Großkunde Müller. Großkunde Müller wird dann als Unterordner des Hauptordners Großkunde erstellt.
====

[#4600]
== Ticket manuell in Ordner verschieben

Du musst Tickets manuell in Ordner verschieben. Das Ticket ist dann sowohl in der Ticketübersicht als auch in dem gewählten Ordner sichtbar.

[.instruction]
Ticket manuell in Ordner verschieben:

. Öffne das Menü *CRM » Ticketsystem*.
. Nutze die Suchfunktion (icon:search[role="blue"]) und öffne das zu bearbeitende Ticket.
. Wähle aus der Dropdown-Liste *Ordner* den Ordner.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ticket wird nun zusätzlich auch im soeben gewählten Ordner angezeigt.

[#4700]
== Benutzerdefinierten Filter erstellen

Du hast die Möglichkeit, benutzerdefinierte Filter zu erstellen. Deine eigenen Filter siehst nur du selbst.

[.instruction]
Benutzerdefinierten Filter erstellen:

. Öffne das Menü *CRM » Ticketsystem*.
. Klicke im Tab *Ordner* auf *Neuen Filter erstellen*. +
→ Das Fenster *Benutzerdefinierte Filter erstellen* wird geöffnet.
. Gib im Bereich *Einstellungen* den Namen für den Filter ein.
. Wähle im Bereich *Einstellungen* ein Icon aus der Dropdown-Liste.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen zu den *Filtern* in <<tabelle-ticket-suchen>> im Kapitel <<crm/ticketsystem-nutzen#3400, Ticket suchen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#4800]
== E-Mails im Ticketsystem zuordnen

E-Mails im Ticketsystem werden nach Stichworten bzw. textlichen Parametern, die von deinem plentymarkets System automatisch erkannt werden, zugeordnet. Eine E-Mail, die eine Ticket-ID enthält, wird z.B. automatisch als Nachricht in das Ticket mit der in der E-Mail hinterlegten Ticket-ID eingeordnet. Wie bereits im Kapitel <<crm/ticketsystem-nutzen#2100, E-Mail-Konto einrichten>> erwähnt, solltest du für das Ticketsystem ein separates E-Mail-Konto mit einer E-Mail-Adresse einrichten, die nur dafür genutzt wird.

Beachte die Stichworte, die zu einer Zuordnung führen, und die Schreibweisen in <<tabelle-zuordnung-ticketsystem>>. Groß- und Kleinbuchstaben spielen keine Rolle. Prüfe dazu auch die <<crm/e-mails-versenden#1200, E-Mail-Vorlagen>>, die du im Ticketsystem verwendest, und korrigiere bzw. ergänze je nach Bedarf Template-Variablen.

[[tabelle-zuordnung-ticketsystem]]
.Zuordnungsparameter und erlaubte Schreibweisen
[cols="1,3"]
|====
|Parameter |Mögliche Schreibweisen

|*E-Mail-Adresse*
|beispiel@mail.de

|*Ticket-ID*
|Ticket / ID / Nr / No / Nummer / number + Zahl +
Beispiele: +
Ticket-ID: 123 +
Ticket id 123 +
TicketID #123 +
ID: #123 +
ID: 123 +
Erlaubte Zeichen: +
Leerzeichen, Punkt, Doppelpunkt, Minuszeichen, Gleichheitszeichen, Raute, runde Klammern, eckige Klammern

|*Kundendaten*
|Kunden-ID bzw. Kunden-Nr.: Kunde / Customer + ID / Nr / No / Nummer / number + Zahl +
Kunden-Name: Kunden / Customer + Name + Zahl +
Beispiele: +
Kunden-ID: 123 +
Kunden ID 123 +
Kunden id 123 +
KundenID123 +
Kundennummer 123 +
Erlaubte Zeichen: +
Leerzeichen, Punkt, Doppelpunkt, Minuszeichen, Gleichheitszeichen, Raute

|*Auftrags-ID*
|Auftrag(s) / Order + ID / Nr / No + Zahl +
Beispiele: +
Auftrags-ID: 123 +
Auftrag ID 123 +
AuftragsID123 +
Order id 123 +
Erlaubte Zeichen: +
Leerzeichen, Punkt, Doppelpunkt, Minuszeichen, Gleichheitszeichen, Raute

|*Rechnungs-Nr.*
|Rechnung(s) / invoice + ID / Nr / No / Nummer / number + Zahl +
Beispiele: +
Rechnung-ID: 123 +
Rechnung ID 123 +
Invoice No 123 +
Erlaubte Zeichen: +
Leerzeichen, Punkt, Doppelpunkt, Minuszeichen, Gleichheitszeichen, Raute
|====

E-Mails werden bei eingerichtetem E-Mail-Konto in den Einstellungen des Ticketsystems automatisch ins Ticketsystem überführt. Dort werden die E-Mails anhand der in <<tabelle-zuordnung-ticketsystem>> genannten Parameter wie folgt erstellt:

* Eine E-Mail, die eine Ticket-ID enthält, wird automatisch als Nachricht in das Ticket eingeordnet.
* Wenn eine E-Mail eine Kunden-ID, Kundennummer oder Kundennamen enthält, wird dazu automatisch ein Ticket erstellt, das die Kundendaten im Tab *Kunde* des Tickets enthält.
* Wenn eine E-Mail eine Auftrags-ID oder eine Rechnungs-ID enthält, wird dazu automatisch ein Ticket erstellt, das den Auftrag im Tab *Aufträge suchen* des Tickets enthält.

[IMPORTANT]
.Nur ungelesene Nachrichten werden synchronisiert
====
Die Zuordnung erfolgt durch eine Synchronisation mit dem Ticketsystem. Die E-Mail darf im E-Mail-Programm bis dahin nicht geöffnet bzw. gelesen werden, da nur ungelesene Nachrichten synchronisiert werden.
Beachte dazu auch die Erläuterung zu der Einstellung *Verfahren* in <<tabelle-e-mail-konto-einrichten>> im Kapitel <<crm/ticketsystem-nutzen#2100, E-Mail-Konto einrichten>>.
====

Im Folgenden findest du einige Beispiele, die die Zuordnung veranschaulichen:

[#4900.subhead]
Zuordnung nach Ticket-ID

Eine E-Mail enthält als Betreff das Stichwort *Ticket-ID 1*. Dieses Stichwort wird vom Ticketsystem erkannt. Dies wäre auch der Fall, wenn das Stichwort z.B. im Text der E-Mail stehen würde. +
Die E-Mail mit dem Stichwort *Ticket-ID 1* wird bei der Synchronisation mit dem Ticketsystem automatisch dem Ticket mit der ID 1 als Nachricht zugeordnet.

[#5000.subhead]
Zuordnung nach Kunden-ID

Wenn in der E-Mail eine Kunden-ID enthalten ist, wird beim Import der Nachricht der Kunde automatisch mit dem neu erstellten Ticket verknüpft. Dies ist zu erkennen am Suchfeld *Kunde* neben dem Fortschrittsbalken und am Tab *Kunde*, das die Kundendaten enthält. Kundenbezogene E-Mails sollten daher immer die Kunden-ID oder Kundennummer enthalten, damit diese Daten im Ticket sofort verfügbar sind.

[#5100.subhead]
Zuordnung nach Auftrags-ID

Wenn eine Auftrags-ID in der E-Mail enthalten ist, wird - wenn die Auftrags-ID der einzige Parameter ist - ein neues Ticket erstellt und dort der Auftrag mit der ID in das Tab *Aufträge suchen* geladen.

[#5200.subhead]
Zuordnung nach Rechnungsnummer

Ist eine Rechnungsnummer angegeben, wird der Auftrag gesucht und im erstellten Ticket im Tab *Aufträge suchen* angezeigt.

[IMPORTANT]
.Absender-E-Mail-Adresse hat Priorität vor E-Mail-Adresse in den Kundendaten
====
Wenn ein Ticket über eine E-Mail erstellt wurde, die keine Parameter zur Zuordnung enthielt, wird bei Antworten über automatische Prozesse die Absender-E-Mail-Adresse verwendet.

Wenn durch Kundenparameter in der E-Mail die Zuordnung zu einem Kunden erfolgt ist und die Kundendaten eine E-Mail-Adresse enthalten, wird bei automatischen Prozessen trotzdem die Absender-E-Mail-Adresse verwendet, da diese immer Priorität hat.
====

[#5300]
== Ticketkarte erstellen

Im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Ticketkarten* erstellst du eine Druckvorlage, mit der deine Tickets als PDF-Daten ausgegeben werden, um diese dann zu archivieren oder zu drucken. Das Einrichten von Ticketkarten ist im Prinzip vergleichbar mit dem Einrichten von <<fulfillment/dokumente-erzeugen#adressetikettenvorlage, Adressetikettenvorlagen>>.

Je nach Größe der Seite, Anzahl der Zeilen und Spalten sowie Größe der Karte passen mehr oder weniger Ticketkarten auf eine Seite. Bedenke bei der Berechnung auch die Kartenabstände.

Die Parameter, z.B. die Ticket-ID, werden angezeigt, sobald Werte für *X*, *Y* und *mm* gespeichert sind. Optional kannst du einen Feldnamen eingeben, der dann vor dem Wert angezeigt wird.

In den Zeilen *Nachricht* und *Kommentar* kannst du wählen, ob die älteste oder die neueste Nachricht und der älteste oder der neueste Kommentar auf der Ticketkarte angezeigt werden sollen.

Die Priorität wird beginnend mit *0* (= grauer Stern, niedrigste Priorität) und aufsteigend bis Priorität *5* (= 2 gelbe Sterne, höchste Priorität) bezeichnet.

[TIP]
.Zeilenumbruch erlauben
====
Damit bei mehreren Eignern alle eingegebenen Eigner eines Tickets in der Ticketkarte angezeigt werden, aktiviere je nach Zeilenlänge die Option *Zeilenumbruch erlauben*. Auch bei der Einstellung *Ticket-Titel* besteht die Möglichkeit, einen Zeilenumbruch zu erlauben.
====

[.instruction]
Ticketkarte erstellen:

. Öffne das Menü *System » Systemeinstellungen » CRM » Ticketsystem » Ticketkarten*.
. Klappe den Bereich *Neue Vorlage* auf.
. Gib einen *Namen* ein.
. Gib die Maße für die *Seite* und die *Karte* ein.
. Gib die Parameter für die Elemente ein, die auf der Ticketkarte angezeigt werden sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[NOTE]
.Ticketkarte als Vorschau anzeigen
====
Nachdem du die neue Vorlage erstellt haben, kannst du die Vorschau anzeigen lassen. Klappe die Vorlage auf. Gib die *Ticket-ID* ein und klicke auf *Vorschau*.
====

[#5400]
== Tickets in PDF-Datei ausgeben

Nachdem die Vorlage der <<crm/ticketsystem-nutzen#5300, Ticketkarte>> im Menü *System » Systemeinstellungen » CRM » Ticketsystem » Ticketkarten* gespeichert wurde, steht diese im Menü *CRM » Ticketsystem* im Tab *Tickets* in der *Gruppenfunktion* in der Dropdown-Liste *Ticket drucken* zur Verfügung. Gehe wie im Folgenden beschrieben vor, um Tickets in einer PDF-Datei auszugeben.

[.instruction]
Tickets in PDF-Datei ausgeben:

. Öffne das Menü *CRM » Ticketsystem*.
. Aktiviere die Tickets, die du ausgeben möchtest, in der Ticketübersicht.
. Klicke auf *Gruppenfunktion*. +
→ Das Fenster *Gruppenfunktion* wird geöffnet.
. Aktiviere die Einstellung *Ticket drucken*.
. Wähle die Vorlage aus der Dropdown-Liste.
. Gib ggf. eine *Nachricht* oder einen *Kommentar* ein. +
​→ Der Eintrag wird bei allen gedruckten Tickets gespeichert (nicht im Ausdruck, sondern im Ticket).
. Klicke auf *Anwenden* (icon:cog[]). +
​→ Die PDF-Datei wird erzeugt.

[#5500]
== Tickets im Mein Konto-Bereich erstellen

Im Bereich *Mein Konto* des Webshops haben deine Kunden die Möglichkeit, Tickets zu erstellen. Du kannst dort Nachrichten versenden und Antwortnachrichten zu dem Ticket werden dort angezeigt. Wenn der Kunde per Ereignisaktion bei Nachrichten eine E-Mail erhält und dort ein Link mit der Template-Variable *$TicketURL* enthalten ist, kann der Kunde über diesen Link direkt das Ticket im Bereich *Mein Konto* aufrufen und dort z.B. die Nachricht beantworten.

[#5600]
== Statistiken zu Tickets erstellen

Du hast im Menü *Start » Statistik* die Möglichkeit, Statistiken zu deinen Tickets zu erstellen. Dort stehen dir die Statistiktypen *Tickets nach aktuellen Status*, *Tickets nach Status* oder *Tickets nach Zustand* zur Verfügung.

Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistik>>. Dort wird auch beschrieben, wie du Statistiken erstellst und auswertest.
