= POS für Kassenbenutzer
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, Kasse, POS, plentymarkets Kasse, Kassenbenutzer, POS-Benutzer, Katzenbenutzer
:position: 20

////
p>Noch beschreiben:</p>

<ul>
<li>Artikel oder Variante???</li>
<li>Wie setzt sich die Belegnummer zusammen?</li>
<li>Preis bearbeiten</li>
<li>Dummy-Artikel, wenn Artikel nicht gefunden wird</li>
<li>Favoriten in der App anlegen</li>
<li>Umbuchen</li>
<li>Warenbestand prüfen</li>
<li>(Kasse sperren)</li>
<li>(Artikel synchronisieren)</li>
<li>(Aufträge hochladen)</li>
</ul
////

[#5]
== plentymarkets App installieren

Installieren Sie zunächst die plentymarkets App auf Ihrem mobilen Endgerät.

* **link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=de[plentymarkets App bei Google Play^]**

* **link:https://itunes.apple.com/de/app/plentymarkets/id957702618[plentymarkets App bei iTunes^]**

[WARNING]
.Offline-Aufträge werden bei Deinstallation der App gelöscht
====
Bei fehlender Internetverbindung werden Aufträge offline gespeichert und erst später synchronisiert. Wenn Sie die App deinstallieren, bevor die Aufträge an plentymarkets übertragen wurden, werden die lokal gespeicherten Aufträge unwiederbringlich gelöscht und können auch vom plentymarkets Support nicht wiederhergestellt werden. Prüfen Sie daher vor jeder Deinstallation Ihrer App, dass keine Offline-Aufträge auf dem Gerät vorhanden sind.
====

[#10]
== Bei plentymarkets POS anmelden

Gehen Sie wie unten beschrieben vor, um sich bei plentymarkets POS anzumelden.

[.instruction]
Bei plentymarkets POS anmelden:

. Melden Sie sich auf dem Mobilgerät an.
. Tippen Sie auf dem Startbildschirm auf das plentymarkets App Symbol. +
→ Der Login-Bildschirm wird angezeigt.
. Geben Sie Ihre Login-Daten ein. Beachten Sie Tabelle 1.
. Tippen Sie auf **Login**. +
→ Der Startbildschirm der plentymarkets App wird angezeigt.
. Tippen Sie oben links auf das Menüsymbol. +
→ Die verfügbaren Menüpunkte werden angezeigt.
. Tippen Sie auf **POS**. +
→ plentymarkets POS wird geöffnet.

[TIP]
.Anmeldung wird gespeichert
====
Sie bleiben bei plentymarkets POS angemeldet, bis Sie im Menü der App auf **Ausloggen** tippen. Sie können also die App schließen und öffnen, ohne sich erneut anmelden zu müssen.
====

.Anmeldung
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Sprache
|Sprache wählen, in der plentymarkets POS dargestellt werden soll. Die Benutzeroberfläche von plentymarkets POS ist auf Deutsch und Englisch verfügbar.

|**System (Basis-URL)**
|Domain des plentymarkets Systems ohne führendes https:// oder http:// eingeben, z.B. **ihr-shop.de**.

|**Benutzer**; **Passwort**
|Benutzernamen und Passwort für das plentymarkets System eingeben.
|====

[#30]
== Kassieren

Nachdem Sie sich bei plentymarkets POS angemeldet haben, wird das POS-Menü angezeigt. Tippen Sie auf **Kassieren**, um den POS-Warenkorb zu öffnen und Artikel hinzuzufügen.

[#40]
=== Artikel zum POS-Warenkorb hinzufügen

Sie können Artikel über die Artikelsuche, die Favoritenliste oder per Etiketten-Scan zu plentymarkets POS zum aktuellen Auftrag hinzufügen.

[#50]
==== Artikel suchen

Über die Artikelsuche haben Sie Zugriff auf den gesamten Artikelbestand des Mandanten. Eine Suche ist anhand folgender Artikeldaten möglich:

* Artikel-ID
* Variantennummer
* Barcode
* Artikelname
* Varianten-ID
* Lieferanten-Artikel-Nr.

Gehen Sie wie unten beschrieben vor, um Artikel über die Suche zum POS-Warenkorb hinzufügen.

[.instruction]
Artikel über Suche hinzufügen:

. Tippen Sie im POS-Warenkorb auf die Lupe. +
→ Die Artikelsuche wird geöffnet.
. Geben Sie ein Suchkriterium ein.
. Tippen Sie auf **Suchen**. +
→ Die gefundenen Artikel werden aufgelistet.
. Tippen Sie auf das grün hinterlegte Häkchen, um einen Artikel in den Warenkorb zu legen. +
→ Das Fenster **Menge eingeben** wird angezeigt.
. Geben Sie die Menge des Artikels ein, die Sie in den Warenkorb legen möchten. +
→ Der Artikel wird in den Warenkorb gelegt und die zu zahlende Summe aktualisiert. +
→ **__Tipp:__** Artikel ohne Nettowarenbestand werden in roter Schrift dargestellt, können aber verkauft werden.

[#60]
==== Favoritenliste öffnen

Über die Favoritenliste greifen Sie schnell auf als Favoriten gekennzeichnete Artikel zu. plentymarkets Administratoren können eine Favoritenliste für die Kasse hinterlegen. Aber auch Sie selbst können häufig gekaufte Artikel als Favoriten kennzeichnen, um den Kassiervorgang zu beschleunigen. Gehen Sie wie unten beschrieben vor, um Artikel über die Favoritenliste zum POS-Warenkorb hinzufügen.

[.instruction]
Artikel über Favoritenliste hinzufügen:

. Tippen Sie im POS-Warenkorb auf den Stern. +
→ Die Liste der Favoriten wird geöffnet.
. Tippen Sie auf das grün hinterlegte Häkchen, um einen Artikel in den Warenkorb zu legen. +
→ Das Fenster **Menge eingeben** wird angezeigt. +
. Geben Sie die Menge des Artikels ein, die Sie in den Warenkorb legen möchten. +
→ Der Artikel wird in den Warenkorb gelegt und die zu zahlende Summe aktualisiert.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter.

[#70]
==== Etikett scannen

Wenn in Ihrem plentymarkets System Etiketten für Ihre Artikel hinterlegt sind, können Sie Artikel auch zum POS-Warenkorb hinzufügen, indem Sie diese Etiketten scannen. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Artikel über Etiketten-Scan hinzufügen:

. Tippen Sie im POS-Warenkorb auf das Etikettensymbol. +
→ Die Kamera Ihres Mobilgeräts wird aktiviert.
. Tippen Sie auf das Kamerasymbol, um das Etikett zu scannen. +
→ Das Fenster **Menge eingeben** wird angezeigt.
. Geben Sie die Menge des Artikels ein, die Sie in den Warenkorb legen möchten. +
→ Der Artikel wird in den Warenkorb gelegt und die zu zahlende Summe aktualisiert.

[#80]
=== Zahlung entgegennehmen

Nachdem Sie alle Artikel des Kunden in den POS-Warenkorb gelegt haben und ggf. Rabatte/Verkaufsgutscheine angewendet haben, buchen Sie die Zahlung. Zurzeit können die Zahlungsarten Barzahlung und Zahlung über EC-Terminal verwendet werden.

[NOTE]
.Auftrag stornieren
====
Sie können einen POS-Auftrag direkt stornieren, nachdem Sie die Zahlung gebucht haben. Tippen Sie dazu in der Ansicht **Auftrag erstellt** auf **Auftrag stornieren**. Abgeschlossene Aufträge, die seit dem letzten Tagesabschluss über die Kasse erstellt wurden, stornieren Sie über das Menü <<omni-channel/pos/pos-kassenbenutzer#173, **POS » Auftrag stornieren**>>.
====

[.instruction]
Barzahlung:

. Geben Sie über das Tastenfeld den Betrag ein, den Sie vom Kunden erhalten haben.
. Tippen Sie auf **Zahlung erhalten**. +
→ Die Ansicht **Auftrag erstellt** wird angezeigt. +
→ Der Auftrag wird erstellt. +
→ Ein Beleg wird gedruckt. Alternativ tippen Sie auf **Beleg drucken**, um den Beleg zu drucken. +
→ **__Tipp:__** Über den Button **Auftrag anzeigen** rufen Sie die Auftragsdaten auf.
. Tippen Sie auf **Neuer Auftrag**, um einen neuen POS-Auftrag anzulegen.

[.instruction]
Zahlung über externes EC-Terminal:

. Tippen Sie auf **EC-Terminal**. +
→ Die zu zahlende Auftragssumme wird angezeigt.
. Führen Sie die Zahlung am EC-Terminal durch.
. Tippen Sie auf **Betrag erhalten/Zahlung abschließen**, um den Auftrag abzuschließen. +
→ Die Ansicht **Auftrag erstellt** wird angezeigt. +
→ Der Auftrag wird erstellt. +
→ Ein Beleg wird gedruckt. Alternativ tippen Sie auf **Beleg drucken**, um den Beleg zu drucken. +
→ **__Tipp:__** Über den Button **Auftrag anzeigen** rufen Sie die Auftragsdaten auf.
. Tippen Sie auf **Neuer Auftrag**, um einen neuen POS-Auftrag anzulegen.


[.instruction]
Zahlung über angebundenes EC-Terminal:

. Tippen Sie auf **EC-Terminal**.
. Folgen Sie den angezeigten Hinweisen, um die Zahlung über das Terminal abzuschließen.
→ Die Ansicht **Auftrag erstellt** wird angezeigt. +
→ Der Auftrag wird erstellt. +
→ Die Belege werden gedruckt. Alternativ tippen Sie auf **Händlerbeleg drucken** bzw. **Kundenbeleg drucken**, um das Drucken manuell zu starten. +
→ **__Tipp:__** Über den Button **Auftrag anzeigen** rufen Sie die Auftragsdaten auf.
. Tippen Sie auf **Neuer Auftrag**, um einen neuen POS-Auftrag anzulegen.


[#250]
=== Verkaufsgutschein verkaufen

Jeder Verkaufsgutschein entspricht einem einzigartigen Gutschein-Code. Dieser Gutschein-Code wird nicht auf dem Beleg ausgegeben, wenn Sie Gutscheinartikel verkaufen. Daher stellt Ihnen Ihr Arbeitgeber die erforderlichen Gutschein-Codes separat zur Verfügung. Daher können hier nur allgemeine Hinweise zum Verkauf von Verkaufsgutscheinen gegeben werden. Abhängig von den Abläufen in Ihrem Ladengeschäft kann es z.B. sein, dass Sie eine Liste mit Gutschein-Codes erhalten und dort die Codes durchstreichen, die Sie verkaufen, und dann den Gutschein-Code händisch auf dem Beleg notieren.

[.instruction]
Verkaufsgutschein verkaufen:

. Legen Sie den Gutscheinartikel mit dem gewünschten Gutscheinwert in den POS-Warenkorb.
. Schließen Sie den Auftrag wie gewohnt ab.
. Händigen Sie dem Kunden den Gutschein-Code aus.
. Dokumentieren Sie, welchen Gutschein-Code Sie verkauft haben. +
**__Hinweis:__** Jeder Gutschein-Code darf nur einmal verkauft werden, da der Betrag nur einmal eingelöst werden kann.

[#90]
== Optionale Kassiervorgänge

[#135]
=== Bestandskunde wählen

Standardmäßig wird für Kassiervorgänge der Standardkunde verwendet, der für die Kasse gespeichert wurde. Während des Kassierens haben Sie jedoch auch die Möglichkeit, einen anderen in plentymarkets gespeicherten Kundendatensatz zu wählen. Nachdem Sie den Kassiervorgang abgeschlossen haben, wird für den nächsten POS-Auftrag automatisch wieder der Standardkunde voreingestellt.

Gehen Sie wie unten beschrieben vor, um einen Bestandskunden zu wählen. Eine Suche ist anhand der folgenden Kundeninformationen möglich:

* **Kontakt-ID** = Kontakt-ID des Kunden
* **Kundendaten** = Vorname, Nachname, Firma, Kontaktperson, eBay-Name, Zusatzname, Straße, PLZ, Ort, E-Mail-Adresse, Kundennummer, Externe Kunden-ID, Such-Tags, PostIdent
* **PLZ** = Postleitzahl des Kunden

[.instruction]
Bestandskunde wählen:

. Tippen Sie im POS-Warenkorb unten auf das Kundensymbol. +
→ Die Daten des Standardkunden werden angezeigt.
. Tippen Sie auf die **Lupe**. +
→ Die Ansicht **Kundensuche** wird geöffnet.
. Geben Sie die Kundendaten ein, die Ihnen bekannt sind, um den Kundendatensatz zu suchen.
. Tippen Sie auf **Suchen**. +
→ Die Suchergebnisse werden aufgelistet.
. Tippen Sie auf einen Kundendatensatz. +
→ Die für den Kunden gespeicherten Adressen werden aufgelistet.
. Tippen Sie auf eine Adresse. Wenn für den Kundendatensatz nur eine Adresse gespeichert ist, ist diese Adresse bereits gewählt.
. Tippen Sie auf **Adresse verwenden**. +
→ Der Kundendatensatz wird gewählt.
. Wenn sich Artikel im POS-Warenkorb befinden, erfolgt die Abfrage **Preise aktualisieren?**. Wenn Sie **Ja** wählen, werden Rabatte, die für die Kundenklasse des gewählten Kunden gelten, auf alle Artikel des Auftrags angewendet. +
→ Die Kundendaten werden übernommen. +
→ **__Tipp:__** Über das Symbol **Zurücksetzen** können Sie den Standardkunden wiederherstellen.
. Tippen Sie rechts oben auf das **X** oder neben das Fenster, um zurück in den POS-Warenkorb zu springen. +
→ Der gewählte Kunde wird im POS-Warenkorb angezeigt.
. Bearbeiten Sie den Auftrag wie gewohnt weiter. +
→ Nachdem Sie den POS-Auftrag abgeschlossen haben, wird wieder der Standardkunde eingestellt.

[TIP]
.Kassenbeleg per E-Mail an Kunden senden
====
Im plentymarkets Backend können Sie <<omni-channel/pos/pos-einrichten#70, **eine Ereignisaktion einrichten**>>, mit der eine E-Mail-Vorlage mit dem Kassenbeleg als Anhang an den Kunden gesendet wird, wenn ein Beleg generiert wird. Für POS-Aufträge, die Sie im Offline-Modus erstellen, wird die Ereignisaktion jedoch erst ausgeführt, wenn die POS-Aufträge hochgeladen werden.
====

[#100]
=== Notiz zum Auftrag hinzufügen

Um zusätzliche Informationen am Auftrag zu hinterlegen, speichern Sie eine Notiz, bevor Sie den Auftrag abschließen. Notizen werden mit dem Auftrag in plentymarkets importiert.

[.instruction]
Notiz zum Auftrag hinzufügen:

. Tippen Sie im POS-Warenkorb auf **Notiz**. +
→ Eine Liste der bereits am Auftrag gespeicherten Notizen wird angezeigt.
. Tippen Sie auf **Notiz hinzufügen**. +
→ Das Fenster **Notiz hinzufügen** wird angezeigt.
. Geben Sie den Notiztext ein.
. Tippen Sie auf das Häkchen, um die Notiz am Auftrag zu speichern. +
→ Die Notiz wird in der Liste der Notizen angezeigt und mit dem Auftrag in plentymarkets importiert.
. Tippen Sie auf das **X**, um die Ansicht zu schließen und zurück in die Warenkorbanzeige zu gelangen.

[#110]
=== Kassiervorgang unterbrechen

Wenn sich ein Kassiervorgang verzögert, Sie aber schon Artikel in den POS-Warenkorb gelegt haben, können Sie den aktuellen Stand des Warenkorbs speichern, indem Sie den Bon parken. Auch mehrere Bons können so zwischengespeichert werden.

[#120]
==== Bon parken

Gehen Sie wie unten beschrieben vor, um einen Bon zu parken.

[.instruction]
Bon parken:

. Tippen Sie im POS-Warenkorb oben rechts auf die vertikale Ellipse. +
→ Weitere Optionen werden eingeblendet.
. Tippen Sie auf **Bon parken**. +
→ Das Fenster **Bon parken** wird angezeigt.
. Tippen Sie auf **Ja**. +
→ Der Bon wird gespeichert und ein neuer POS-Warenkorb angezeigt.

[#130]
==== Geparkten Bon laden

Gehen Sie wie unten beschrieben vor, um einen geparkten Bon zu laden und den Kassiervorgang abzuschließen.

[.instruction]
Geparkten Bon laden:

. Tippen Sie im POS-Warenkorb oben rechts auf die vertikale Ellipse. +
→ Weitere Optionen werden eingeblendet.
. Tippen Sie auf **Bon laden**. +
→ Eine Liste der geparkten Bons wird angezeigt.
. Tippen Sie auf den Bon, den Sie laden möchten. +
→ Die geparkten Artikel dieses Bons werden im POS-Warenkorb angezeigt.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter.

[#140]
=== Auftragsposition bearbeiten

//  Diese Einstellungen müssen noch in Einzelkapitel unterteilt und einzeln beschrieben werden.
Sie können Artikel im POS-Warenkorb weiter bearbeiten. Änderungen, die Sie über diese Funktion vornehmen, wirken sich grundsätzlich nur auf diesen Auftrag aus, nicht auf den Datensatz des Artikels im System.

[.instruction]
Auftragspositionen bearbeiten:

. Tippen Sie auf die Auftragsposition im POS-Warenkorb. +
→ Weitere Optionen werden eingeblendet.
. Tippen Sie auf die gewünschte Einstellung. Beachten Sie Tabelle 2.

.Auftragspositionen bearbeiten
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Menge ändern**
|Öffnet das Fenster **Menge ändern**. Neue Menge eingeben und auf **OK** tippen, um die Menge des Artikels im Warenkorb anzupassen.

|**Artikelposition umbenennen**
|Neuen Namen eingeben und auf **OK** tippen, um den Namen der Auftragsposition zu ändern. Der Name wird nur in diesem Auftrag geändert. Der Name des Artikels im System bleibt unverändert.

|**Einzelpreis ändern**
|Neuen Preis eingeben und auf **OK** tippen, um bei Auftragspositionen mit einer Menge größer 1 den Preis nur einer dieser Positionen zu ändern. Der Preis wird nur in diesem Auftrag geändert. Der Preis des Artikels im System bleibt unverändert.

|**Gesamtpreis ändern**
|Neuen Preis eingeben und auf **OK** tippen, um den Gesamtpreis der gesamten Menge der Auftragsposition zu ändern. Der Preis wird nur in diesem Auftrag geändert. Der Preis des Artikels im System bleibt unverändert.

|**Artikelpreis zurücksetzen**
|Setzt über **Einzelpreis ändern** oder **Gesamtpreis ändern** geänderte Preise auf den ursprünglichen Preis zurück.

|**Rabatt hinzufügen**
|Rabatt in Prozent eingeben und auf **OK** tippen, um einen Rabatt auf die Auftragsposition zu gewähren. Der Preis wird nur in diesem Auftrag geändert. Der Preis des Artikels im System bleibt unverändert. +
**__Hinweis:__** Wenn Rabatte auf einzelne Auftragspositionen hinzugefügt wurden, kann kein Rabatt auf den gesamten POS-Warenkorb eingegeben werden.

|**Rabatt entfernen**
|Setzt über **Rabatt hinzufügen** rabattierte Preise auf den ursprünglichen Preis zurück.

|**Löschen**
|Löscht den Artikel aus dem POS-Warenkorb.
|====

[#150]
=== Warenkorb bearbeiten

Nachdem Sie alle Artikel des Kunden in den POS-Warenkorb gelegt haben, können Sie in der Kassenansicht Verkaufsgutscheine einlösen oder einen Rabatt auf den gesamten Auftragswert anwenden, bevor Sie den Auftrag abschließen.

[#160]
==== Verkaufsgutschein einlösen

[.instruction]
Verkaufsgutschein einlösen:

. Tippen Sie unten im POS-Warenkorb auf den grün hinterlegten Pfeil nach rechts. +
→ Eine Zusammenfassung des Auftrags und die verfügbaren Zahlungsmethoden werden angezeigt.
. Tippen Sie auf **Gutschein / Rabatt**.
. Geben Sie in das Feld **Gutscheincode/Rabatt** den Gutscheincode ein.
. Tippen Sie auf **Gutschein**. +
→ Die Gutscheinsumme wird von der Auftragssumme abgezogen und die Restsumme eingeblendet.
. Tippen Sie auf **Zurück**.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter.

[#170]
==== Rabatt auf gesamten Auftrag anwenden

Statt einzelne Auftragspositionen zu rabattieren, haben Sie auch die Möglichkeit, einen Rabatt auf den gesamten Inhalt des POS-Warenkorbs anzuwenden. Ein Rabatt auf den gesamten POS-Warenkorb ist allerdings nur möglich, wenn kein Rabatt auf einzelne Auftragspositionen angewendet wurde. Gehen Sie wie hier beschrieben vor, um einen Rabatt auf den gesamten POS-Warenkorb anzuwenden.

[.instruction]
Rabatt auf gesamten Warenkorb anwenden:

. Tippen Sie unten im POS-Warenkorb auf den grün hinterlegten Pfeil nach rechts. +
→ Eine Zusammenfassung des Auftrags und die verfügbaren Zahlungsmethoden werden angezeigt.
. Tippen Sie auf **Gutschein / Rabatt**.
. Geben Sie in das Feld **Gutscheincode/Rabatt** den Rabatt in Prozent ein.
. Tippen Sie auf **Rabatt**. +
→ Die Rabattsumme wird von der Auftragssumme abgezogen und die neue Auftragssumme eingeblendet.
. Tippen Sie auf **Zurück**.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter.

[#173]
== Auftrag stornieren

Über den POS-Menüpunkt **Auftrag stornieren** stornieren Sie abgeschlossene POS-Aufträge, die seit dem letzten Tagesabschluss über die Kasse erstellt wurden. Gehen Sie wie unten beschrieben vor, um einen POS-Auftrag zu stornieren.

[WARNING]
.Stornierung von POS-Aufträgen nur über die Kasse
====
Wenn Sie POS-Aufträge über das plentymarkets Backend stornieren, kommt es zu Fehlern bei den Kassendaten (Tagesabschlüsse, Barbestand etc.). Stornieren Sie POS-Aufträge daher nur über die Kasse und nicht im plentymarkets Backend.
====

[.instruction]
Auftrag stornieren:

. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**.
. Tippen Sie auf **Auftrag stornieren**. +
**__Tipp:__** Der Menüpunkt ist nur wählbar, wenn Sie berechtigt sind, Aufträge zu stornieren. +
→ Nicht stornierte Aufträge, die seit dem letzten Tagesabschluss über die Kasse erstellt wurden, werden aufgelistet.
. Tippen Sie auf das Icon **Stornieren**. +
→ Alternativ tippen Sie auf den Auftrag, um die Detailansicht zu öffnen, und dort auf das Icon **Stornieren**.
. Bestätigen Sie die Stornierung. +
. **__Je nach Kartenterminal:__** Wählen Sie, ob der stornierte Betrag bar oder über das Terminal zurückerstattet werden soll.
. Zahlen Sie den stornierten Betrag bar aus oder wickeln Sie die Rückzahlung über das Kassenterminal/den Payment-Provider ab. +
→ Der Auftrag wird storniert.

[#175]
== Retoure buchen

Über eine Kasse gebuchte Retouren werden im plentymarkets Backend als Retoure ohne Hauptauftrag erstellt. Gehen Sie wie unten beschrieben vor, um eine Retoure zu buchen.

[.instruction]
Retoure buchen:

. Tippen Sie im Menü **POS** auf **Retoure**. +
→ Die Retourenansicht wird geöffnet.
. Fügen Sie die Retourenartikel per Scan oder über die Artikelsuche hinzu. +
→ Wenn der gezahlte Preis vom aktuellen Preis des Artikels abweicht, <<omni-channel/pos/pos-kassenbenutzer#140, **passen Sie den Preis des Artikels an**>>.
. Fügen Sie optional eine Notiz zur Retoure hinzu:
  .. Tippen Sie auf die Pinnwandnadel. +
  → Eine Liste der bereits an der Retoure gespeicherten Notizen wird angezeigt.
  .. Tippen Sie auf **Notiz hinzufügen**. +
  → Das Fenster **Notiz hinzufügen** wird angezeigt.
  .. Geben Sie den Notiztext ein.
  .. Tippen Sie auf das Häkchen, um die Notiz an der Retoure zu speichern. +
  → Die Notiz wird gespeichert und mit der Retoure in plentymarkets importiert.
  .. Tippen Sie auf das Listensymbol, um zurück in die Retourenansicht zu wechseln.
. Wenn alle Retourenartikel erfasst wurden, tippen Sie auf das grün hinterlegte Häkchen. +
→ Die Gesamtsumme der Retoure wird angezeigt.
. Tippen Sie auf **Retoure abschließen**. +
→ Im plentymarkets Backend wird eine Retoure ohne Hauptauftrag erstellt.

[#180]
== Einlagen/Entnahmen buchen

Entnahmen aus und Einzahlungen in die Kasse, die nicht durch das Buchen von Aufträgen entstehen, müssen erfasst und dokumentiert werden.

[#190]
=== Einlage buchen

[.instruction]
Einlage buchen:

. Tippen Sie im POS-Warenkorb oben links auf **Zurück**. +
→ Das **POS-Menü** wird eingeblendet.
. Tippen Sie auf **Einlagen und Entnahmen**. +
→ Ein Tastenfeld wird angezeigt, über das Sie den Betrag eingeben können.
. Geben Sie in das Feld **Grund** Informationen zu der Einlage ein.
. Tippen Sie den Betrag ein, der in die Kasse eingezahlt wird.
. Tippen Sie auf **Einlage**, um die Einlage zu erfassen. +
→ Der Ist-Kassenbestand wird aktualisiert. +
→ Ein Beleg für die Einlage wird gedruckt. +
→ Der Beleg wird in plentymarkets importiert und im Menü **Aufträge » Dokumentenarchiv** gespeichert.

[#200]
=== Entnahme buchen

[.instruction]
Entnahme buchen:

. Tippen Sie im POS-Warenkorb oben links auf **Zurück**. +
→ Das **POS-Menü** wird eingeblendet.
. Tippen Sie auf **Einlagen und Entnahmen**. +
→ Ein Tastenfeld wird angezeigt, über das Sie den Betrag eingeben können.
. Geben Sie in das Feld **Grund** Informationen zu der Entnahme ein.
. Tippen Sie den Betrag ein, der aus der Kasse genommen wird.
. Tippen Sie auf **Entnahme**, um die Entnahme zu erfassen. +
→ Der Ist-Kassenbestand wird aktualisiert. +
→ Ein Beleg für die Entnahme wird gedruckt. +
→ Der Beleg wird in plentymarkets importiert und im Menü **Aufträge » Dokumentenarchiv** gespeichert.

[#210]
== Berichte erstellen

[#220]
=== Zwischenbericht erstellen

Mit Zwischenberichten informieren Sie sich im laufenden Betrieb über die Umsätze, die seit dem letzten Tagesabschluss über die Kasse generiert wurden. Sie können beliebig viele Zwischenberichte erstellen. Zwischenberichte werden nicht in plentymarkets importiert, ihre  Erstellung also nicht langfristig dokumentiert. Zwischenberichte werden auch als X-Berichte bezeichnet.

Zwischenberichte enthalten folgende Informationen:

* Barbestand: Anfangsbarbestand, Entnahmen, Einlagen, Soll-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retouren: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufsgutscheine: Anzahl und Summe verkaufter Gutscheine
* Benutzer: Umsatz pro Benutzer

[.instruction]
Zwischenbericht erstellen:

. Tippen Sie im POS-Warenkorb oben links auf **Zurück**. +
→ Das **POS-Menü** wird eingeblendet.
. Tippen Sie auf **Zwischenbericht**. +
→ Der Zwischenbericht wird gedruckt.

[#230]
=== Tagesabschluss erstellen

Ein Tagesabschlussbericht dokumentiert die seit dem letzten Tagesabschlussbericht getätigten Umsätze. Durch das Drucken eines Tagesabschlussberichts werden die Tagesumsätze außerdem auf 0 zurückgesetzt. Die Tagesabschlussberichte werden mit einer fortlaufenden Nummer versehen und in plentymarkets gespeichert. Tagesabschlussberichte dienen als Nachweis gegenüber dem Finanzamt. Tagesabschlussberichte werden auch als Z-Berichte bezeichnet.

Tagesabschlussberichte enthalten folgende Informationen:

* Barbestand: Entnahmen, Einlagen, Soll-Kassenbestand, Ist-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retouren: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufte Gutscheine: Anzahl und Summe
* Benutzer: Umsatz pro Benutzer

[.instruction]
Tagesabschluss erstellen:

. Tippen Sie im POS-Warenkorb oben links auf **Zurück**. +
→ Das **POS-Menü** wird eingeblendet.
. Tippen Sie auf **Tagesabschluss**. +
→ Der Soll-Kassenbestand wird eingeblendet.
. Prüfen Sie den tatsächlichen Kassenbestand und geben Sie diesen Ist-Bestand ein.
. Tippen Sie auf **Tagesabschluss erstellen**.
→ Der Tagesabschluss wird in plentymarkets importiert und im Menü **Aufträge » Dokumentenarchiv** gespeichert. +
→ Der Tagesabschluss wird gedruckt. +
→ Die Tagesumsätze werden auf 0 zurückgesetzt.

[TIP]
.Tagesabschluss für Kartenzahlungen
====
Wenn Sie ein Karten-Terminal an plentymarkets POS angebunden haben, ist es bei einigen Terminals möglich, gleichzeitig mit dem plentymarkets POS Tagesabschluss einen Tagesabschluss für die Umsätze des Karten-Terminals anzustoßen. Beantworten Sie die angezeigte Frage **Gleichzeitig Tagesabschluss für Terminal erstellen?** mit **Ja**, um die Kartenumsätze an den Netzbetreiber zu übermitteln und auf 0 zurückzusetzen.
====

=== Kassensturzbericht erstellen

Ein Kassensturz dient dazu, den Kassenbestand zu dokumentieren, d.h. den Bestand an Bargeld in Form von Geldscheinen und Münzen zu einem bestimmten Zeitpunkt. Dazu wird der Barbestand einer Kasse physisch gezählt und ein Zählprotokoll erstellt. Aktuell ist systemseitig nur die Eingabe einer Zählung von Euromünzen vorgesehen.

==== Kassensturzergebnis erfassen

Wenn Sie einen Kassensturz durchführen und das Ergebnis über plentymarkets POS erfassen, können Sie entweder die Anzahl der einzelnen Münzen und Geldscheine eingeben oder das Ergebnis der Zählung als Gesamtbetrag eingeben. Gehen Sie wie unten beschrieben vor, um das Ergebnis eines Kassensturzes zu dokumentieren.

[.instruction]
Kassensturzergebnis erfassen:

. Melden Sie sich bei der plentymarkets App an.
. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**. +
→ Das POS-Menü wird angezeigt.
. Tippen Sie auf **Kassensturz**. +
→ Das Menü **Kassensturz** wird angezeigt. Die Stückelung **1 Cent** ist automatisch ausgewählt.
. Geben Sie über das Tastenfeld die Menge der vorhandenen 1-Cent-Stücke ein.
. Tippen Sie auf den grünen Return-Pfeil, um zur nächsten Stückelung zu springen.
. Wiederholen Sie den Vorgang, bis Sie die Menge für alle vorhandenen Münzen und Geldscheine eingegeben haben. +
→ **__Alternative:__** Um statt Stückelung und Menge den Gesamtbetrag einzugeben, tippen Sie in das Feld **Überschreiben** und geben Sie den gezählten Betrag ein.
. Tippen Sie auf **Kassensturz speichern**. +
→ Ein Kassensturzbericht wird erstellt und im Menü **plentymarkets » Aufträge » Dokumentenarchiv** gespeichert.
. **__Optional:__** Tippen Sie auf **Kassensturzbericht drucken**, um den Bericht zu drucken.
. Wenn der Ist-Kassenbestand vom Soll-Kassenbestand abweicht, gehen Sie wie unten beschrieben vor, um die Differenz zu buchen.

==== Differenz buchen

Wenn nach der Zählung des Barbestands der Ist-Kassenbestand vom Soll-Kassenbestand abweicht, muss die Differenz entweder ausgeglichen oder gebucht werden. Wenn Sie die Differenz buchen, wird der Ist-Kassenbestand als neuer Soll-Kassenbestand übernommen. Gleichzeitig wird abhängig vom Vorzeichen des Differenzbetrags entweder eine Einlage oder eine Entnahme gebucht:

* Ist der Ist-Kassenbestand größer als der Soll-Kassenbestand, wird eine Einlage gebucht.
* Ist ein Minusbetrag in der Kasse, wird eine Entnahme gebucht.

Wenn Sie die Differenz eines Kassensturzes buchen, wird als Grund automatisch **Differenz aus Kassensturz** gespeichert.

[.instruction]
Differenz buchen:

. Tippen Sie nach dem Speichern des Kassensturzes auf **Differenz buchen**, um den Ist-Kassenbestand als neuen Soll-Kassenbestand zu speichern. +
→ Für den Differenzbetrag wird eine Einlage bzw. Entnahme mit dem Grund **Differenz aus Kassensturz** erstellt und im Menü **plentymarkets » Aufträge » Dokumentenarchiv » Kassenbeleg** gespeichert. +
→ Der Ist-Kassenbestand wird als neuer Soll-Kassenbestand gespeichert.

[#240]
== POS-Aufträge im plentymarkets Backend ändern

Für POS-Aufträge wird ein Auftrag im plentymarkets Backend erstellt. Die folgenden Auftragsdaten von POS-Aufträgen können nachträglich im plentymarkets Backend geändert werden:

* Sprache
* Status
* Bezahlter Betrag
* Zahlungsstatus
* Retourengründe
* Auftrag lässt sich Sammelauftrag zuordnen
* Lieferanschrift
* E-Mail-Versand
* Auftragsnotiz
* Versanddatum
* Rückgabedatum
