= Best Practices: POS
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, Kasse, POS, Gutscheine, Gutscheine verkaufen, Best Practice
:position: 90

[#10]
== Gutscheine an der Kasse

Da es bezogen auf den Umgang mit Verkaufsgutscheinen viele Möglichkeiten bei plentymarkets gibt, möchten wir dir hier eine praxisnahe und einfache Variante für den POS-Bereich vorstellen.

=== Ziel

Schneller Verkauf von Gutscheinkarten in variabler Höhe an der Kasse.

=== Vorbereitung

. Sofern noch nicht vorhanden, musst du eine <<omni-channel/pos/pos-einrichten#_gutscheinverkauf_vorbereiten, passende Kampagne>> in plentymarkets erstellen.
. Lege dir einen <<omni-channel/pos/pos-einrichten#_gutscheinartikel_mit_flexiblem_wert_erstellen, Gutscheinartikel mit flexiblem Wert>> für diese Art von Gutscheinen in plentymarkets an.
. Füge diesen Gutscheinartikel dem <<omni-channel/pos/pos-einrichten#70, Favoritenbereich>> deiner Kasse hinzu.
. Beschaffe dir link:http://lmgtfy.com/?q=Barcode-Karten+Druck[Barcode-Karten^] mit vorgefertigten Codes. Die meisten Anbieter erwarten eine CSV-Datei, die die einzelnen Codes enthält, die auf den Karten platziert werden sollen, sowie eine Layout-Vorlage im Photoshop- oder Adobe-Illustrator-Format für das Rahmendesign. +
*_Tipp:_* Wenn du deinen Gutscheincodes das Präfix *#* voranstellst, beschleunigst du später den Einlösungsvorgang, weil plentyPOS dadurch direkt beim Scannen erkennt, dass es sich um einen Gutschein handelt und nicht erst manuell der Button für den Gutscheindialog betätigt werden muss.

=== Videos des Ablaufs

==== Gutschein verkaufen

video::omni-channel/pos/assets/verkauf_best_practice.mp4[width=640]


==== Gutschein einlösen

video::omni-channel/pos/assets/einloesung_best_practice.mp4[width=640]
