= POS einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, POS, Kasse, Kassensystem, Kassen, IDEA-Export, IDEA, GoBD, Kassenjournal, Kassenbuch, GoBD konform
:position: 10

Mit plentymarkets POS integrieren Sie den stationären Handel mühelos in plentymarkets.

[IMPORTANT]
.POS-Einstellung nicht im laufenden Betrieb ändern
====
Ändern Sie die POS-Einstellungen nicht im laufenden Betrieb. Wenn Sie dennoch Änderungen an den POS-Einstellungen vornehmen, fordern Sie Kassenbenutzer auf, sich aus der App ausloggen und wieder einloggen, da es sonst vor allem bei einer Änderung der Rundungseinstellungen zu Unstimmigkeiten in den Gesamtbeträgen kommt.
====

[#10]
== Unterstützte Hardware

plentymarkets POS unterstützt die folgende Hardware.

.POS - unterstütze Hardware
[cols="1,2,2"]
|====
|Gerätetyp |Allgemeine Anforderungen |Getestete Geräte

|**Betriebssysteme**
a|
* Android-Geräte mit OS-Version ab 4.2.2, ARM Prozessor und den link:https://cdn.discourse.org/plentymarkets/uploads/default/original/3X/5/b/5b3b12c7adea2b46e1fb4ae4d1b42bc4e8e37fd8.png[Geräteklassen, window="_blank"]
Small, Normal, Large und X-Large. Die DPI-Zahl des mobilen Geräts kann link:http://dpi.lv/[hier, window="_blank"] ermittelt werden.
* iOS-Geräte (iPad, iPhone, iPod) mit OS-Version ab 8
a|Bei jedem regulären Release

* Elo Touch Solutions I-Series 15I1 - E021201
* Honeywell Dolphin 75e
* Samsung Galaxy Tab A 6 - SM-T580
* Apple iPad Air 2

Regelmäßig

* Samsung Galaxy Tab A - SM-T555
* Samsung Galaxy Tab 4 - SM-T530
* Apple iPad Mini Retina

Punktuell

* Samsung Galaxy S4
* Apple iPhone 6
* Apple iPad Mini
* Apple iPhone 6

|**Belegdrucker**
a|
* ePos-Print API
* Drucker muss über LAN oder WLAN verfügen
a|
* EPSON TM-M30
* EPSON TM-T88V-i (QR-Code-Druck)

|**Scanner**
a|
* Scanner muss über USB oder Bluetooth verfügen
a|
* Inateck BCST-10 (Bluetooth)
* Albasca USB Handscanner MK-1000 (ungetestet aber bei mehreren Kunden erfolgreich im Einsatz)

|**Kundendisplays**
a|
* Nur mit Belegdrucker EPSON TM-M30 einsetzbar
a|
* EPSON DM-D30

|**Karten-Terminals**
a|
* Nur in Verbindung mit Payment-Provider-Vertrag
a|
* Ingenico iPP480 mit Drucker (Betriebsart **ZVT**, Verbindungsart **TCP/IP**) - Anbindung über link:https://marketplace.plentymarkets.com/plugins/payment/ingenicozvt_5140[Ingenico ZVT-Plugin, window="_blank"]
* SumUp Air - Anbindung über link:https://marketplace.plentymarkets.com/plugins/payment/sumup_5141[SumUp-Plugin, window="_blank"] +
**__Hinweis:__** Für SumUp-Anbindung Ortung (Positionsbestimmung) auf dem mobilen Gerät aktivieren, auf dem die plentymarkets App installiert ist.
* Miura Payment-Terminal (nur in Verbindung mit plentyPOS Vertrag)
|====

[#20]
== plentymarkets POS Kasse buchen

Um plentymarkets POS verwenden zu können, müssen Sie zunächst im plentymarkets Konfigurator eine oder mehrere Kassen buchen. Informationen zu den Konditionen finden Sie im Konfigurator oder auf unserer plentymarkets POS Produktseite.

[#30]
== Kasse einrichten

Nachdem Sie Kassen gebucht haben, richten Sie sie im plentymarkets Backend ein. Dabei weisen Sie die Kassen einem Mandanten zu, indem Sie sie im Menü **Einstellungen » Mandant (Shop) » Standard » POS** erstellen und weitere Einstellungen vornehmen. Gehen Sie dazu wie unten beschrieben vor.

[#40]
=== Kasse erstellen

Erstellen Sie zunächst im plentymarkets Backend eine Kasse für den gewünschten Mandanten (Shop).

[.instruction]
Kasse für Mandanten erstellen:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » POS**.
. Klicken Sie auf **Neue Kasse**. +
→ Das Fenster **Neue Kasse** wird eingeblendet.
. Geben Sie einen Namen für die Kasse ein.
. **Speichern** Sie die Einstellungen. +
→ Der Kasse wird eine Herkunft zugeordnet. +
→ Die Kasse wird gespeichert und zur weiteren Bearbeitung geöffnet.

Tabelle 1 beschreibt die Menüleiste der Kasse.

.Menüleiste der Kasse
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**ID**
|Eindeutige Kennung der Kasse. Diese ID wird automatisch und mandantenübergreifend vergeben und ist nicht änderbar.

|**Kopieren**
|Erstellt eine neue Kasse mit den Einstellungen der geöffneten Kasse. Dabei werden Name und Herkunft neu vergeben. +
**__Hinweis:__** Das Kopieren einer Kasse ist nur möglich, wenn eine ausreichende Anzahl an Kassen gebucht wurde.

|**Gerät**
|Zeigt die eindeutige ID des Geräts an, wenn die Kasse bereits mit einem Gerät gekoppelt ist.

|**Löschen**
|Löscht die Kasse aus dem System.
|====

[#50]
=== Grundeinstellungen vornehmen

Nehmen Sie nun im Tab **Grundeinstellungen** der neu erstellten Kasse die weiteren Einstellungen vor und speichern Sie die Einstellungen. Beachten Sie Tabelle 3.

.Tab **Grundeinstellungen** der Kasse
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Name**
|Einen Namen für die Kasse eingeben.

|**Herkunft**
|Beim Buchen einer Kasse wird automatisch eine Herkunft für diese Kasse generiert, um Aufträge, die über diese Kasse ins System gelangen, eindeutig zu kennzeichnen. Der neuen Kasse wird automatisch eine verfügbare POS-Herkunft (103.01 bis 103.99) zugeordnet.

|**Standardkunde**
|Für POS-Aufträge <<omni-channel/pos/pos-einrichten#90, **erstellten Standardkunden**>> wählen, dem über diese Kasse generierte Aufträge zugeordnet werden sollen.

2+|Artikelfilter

|**Marktplatz-Verfügbarkeit berücksichtigen**
|Wählen, ob für die Kasse die Marktplatz-Verfügbarkeit berücksichtigt werden soll. Die Marktplatz-Verfügbarkeit wird im Tab **Verfügbarkeit**, Bereich **Märkte** der Variante aktiviert. +
Häkchen gesetzt = In der Kasse sind nur Varianten verfügbar, für die im Tab **Verfügbarkeit**, Bereich **Märkte** die Herkunft der Kasse aktiviert ist. +
Häkchen nicht gesetzt = Auch nicht für die Herkunft der Kasse aktivierte Varianten sind in der Kasse verfügbar und können aufgerufen und verkauft werden.

|**Nur aktive Varianten berücksichtigen**
|Wählen, ob für die Kasse nur aktive Varianten berücksichtigt werden sollen. Varianten werden im Tab **Einstellungen** der Variante aktiviert. +
Häkchen gesetzt = In der Kasse sind nur Varianten verfügbar, für die im Tab **Einstellungen** der Variante die Option <<artikel/artikel-verwalten#230, **Aktiv**>> aktiviert ist. +
Häkchen nicht gesetzt = Aktive und inaktive Varianten sind in der Kasse verfügbar und können aufgerufen und verkauft werden.

2+|Standort

|**Name 1-4**; +
**Adresse 1-4**; +
**Postleitzahl**; +
**Ort**; +
**Land**
|Firmennamen und Adresse des Ladengeschäfts eingeben, an dem die Kasse betrieben wird. +
**__Hinweis:__** In Deutschland ist die Adresse eine Pflichtangabe, um ein rechtssicheres Arbeiten mit der Kasse zu ermöglichen. Genaue Angaben mit einem Steuerberater klären.

2+|Vertriebslager

|**Vertriebslager**
|Wählen, für welches Vertriebslager die über diese Kasse genierten Aufträge gebucht werden sollen. +
**__Hinweis:__** Artikel ohne Netto-Warenbestand werden im POS-Warenkorb rot markiert, können aber dennoch verkauft werden. Daher kann es zu rechnerischen Überverkäufen kommen.

2+|Reparaturlager

|**Reparaturlager**
|Wählen, in welches Lager Retouren eingebucht werden sollen.

|**Regal**
|Wählen, in welches Regal des Lagers defekte Retouren eingebucht werden sollen.

|**Lagerort**
|Wählen, in welchen Lagerort des Lagers defekte Retouren eingebucht werden sollen. +
**__Tipp:__** Zweimal die Pfeiltaste drücken, um eine Liste der Lagerorte anzuzeigen.

2+|Warenbewegung

|**Warenbestand bei Stornierung zurückbuchen**
|Aktivieren, um den Warenbestand bei einer Stornierung automatisch zurückzubuchen.

2+|Bedienung

|**Preisabfrage wenn Artikelpreis 0** +
(ab 1.5.19)
|Aktivieren, um die manuelle Preiseingabe zu öffnen, wenn beim Kassieren ein 0-Euro-Artikel gewählt wird.

|**Favoriten mit Menge 1 hinzufügen** +
(ab 1.5.19)
|Aktivieren, um beim Kassieren Favoriten automatisch mit der Menge 1 in den POS-Warenkorb zu legen. Artikel mehrmals in den Warenkorb legen, um die Anzahl zu erhöhen. +
*_Tipp:_* Für Favoriten, die über die Artikelsuche hinzugefügt werden, wird die Menge weiterhin manuell eingegeben.
|====

[#60]
=== Favoriten verwalten

Sie haben die Möglichkeit, Varianten zur Favoritenliste hinzuzufügen. Dadurch können Kassenbenutzer häufig verkaufte Varianten schneller aufrufen und zum POS-Warenkorb hinzufügen.

[#70]
==== Varianten als Favoriten speichern

Gehen Sie wie unten beschrieben vor, um Varianten als Favoriten zu speichern.

[.instruction]
Varianten als Favoriten speichern:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » POS**.
. Öffnen Sie die Kasse.
. Öffnen Sie in das Tab **Favoriten**.
. Öffnen Sie das Tab **Variante hinzufügen**. +
→ Eine Liste der Varianten wird angezeigt. Nutzen Sie ggf. die Filter, um die Anzeige einzuschränken.
. Klicken Sie auf **Varianten hinzufügen**. +
→ Die Varianten werden zur Liste der Favoriten hinzugefügt und im Tab **Favoriten** angezeigt. +
→ Bei der nächsten Synchronisierung mit plentymarkets POS werden die Favoriten an die Kasse übertragen.

[TIP]
.Favoriten des Kassenbenutzers haben Priorität
====
Kassenbenutzer können eigene Favoriten in plentymarkets POS speichern. Die Favoriten des Kassenbenutzers haben dabei Priorität gegenüber den im plentymarkets Backend gespeicherten Favoriten.
====

[#80]
==== Reihenfolge der Favoriten ändern

Die Priorität der Favoriten legen Sie über die Pfeilsymbole des Tabs **Favoriten** fest. Die am häufigsten verkaufte Variante sollte ganz oben in der Liste stehen. Die erste Variante der Liste des Menü wird auch dem Kassenbenutzer als erste Variante der Favoritenliste vorgeschlagen. Gehen Sie dazu wie unten beschrieben vor, um die Reihenfolge der Favoriten festzulegen.

[.instruction]
Reihenfolge der Favoriten ändern:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » POS**.
. Öffnen Sie die Kasse.
. Öffnen Sie das Tab **Favoriten**. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicken Sie in der Spalte **Aktionen** auf den Pfeil der Variante, deren Position Sie ändern möchten. +
→ Mit dem Pfeil nach oben erhöhen Sie die Priorität der Variante. +
→ Mit dem Pfeil nach unten verringern Sie die Priorität der Variante.

[#90]
==== Favoritenliste auf andere Kassen übertragen

Die Favoritenliste einer Kasse kann auf andere Kassen des Mandanten übertragen werden. Dabei werden in der Zielkasse vorhandene Favoriten nicht gelöscht. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Favoriten auf andere Kassen übertragen:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » POS**.
. Öffnen Sie die Kasse.
. Öffnen Sie das Tab **Favoriten**. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicken Sie auf **Favoriten übertragen**. +
→ Das Fenster **Favoriten übertragen** wird angezeigt.
. Setzen Sie Häkchen bei den Kassen, zu denen Sie die Favoriten dieser Kasse kopieren möchten.
. Klicken Sie auf **Speichern**. +
→ Die Favoriten werden auf die gewählten Kassen übertragen.

[#110]
==== Varianten aus Liste der Favoriten löschen

Gehen Sie wie unten beschrieben vor, um Varianten aus der Liste der Favoriten zu löschen. Aus der Liste gelöschte Varianten werden bei der nächsten Synchronisierung mit der POS-App aus der Favoritenliste der Kasse entfernt.

[.instruction]
Varianten aus Liste der Favoriten löschen:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » POS**.
. Öffnen Sie die Kasse.
. Öffnen Sie das Tab **Favoriten**. +
→ Die Liste der Varianten auf der Favoritenliste wird angezeigt.
. Klicken Sie in der Spalte der Variante auf **Löschen**. +
→ Die Variante wird aus der Liste der Favoriten entfernt.

[#120]
=== Belegvorlage bearbeiten

Im Tab **Beleg** der Kasseneinstellungen bestimmen Sie die Daten, die auf Belegen ausgegeben werden sollen. Laden Sie optional ein Bild hoch und legen Sie Kopf- und Fußzeile für Belege fest. Standardmäßig ist die Kopfzeile mit den im Menü **Einstellungen » Grundeinstellungen » Stammdaten** gespeicherten Daten befüllt. Diese Daten können Sie pro Kasse anpassen. Die Fußzeile gestalten Sie individuell, um Kunden z.B. auf Aktionsangebote oder Ihren Onlineshop hinzuweisen.

[.instruction]
Belegvorlage bearbeiten:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » POS**.
. Öffnen Sie die Kasse.
. Wechseln Sie in das Tab **Beleg**.
. Setzen Sie Häkchen bei den Komponenten, die auf Belegen der Kasse angezeigt werden sollen.
. Nehmen Sie die Einstellungen vor. Beachten Sie Tabelle 4.
. **Speichern** Sie die Einstellungen. +
→ Die Belegvorlage wird erstellt.

.Belegvorlage bearbeiten
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Bild**
|Option aktivieren und PNG-Datei wählen, die auf Belegen der Kasse ausgeben werden soll. Datei muss vorher im Menü **CMS » Bilder-Galerie** hochgeladen werden.

|**Kopfzeile**
|Wenn die Komponente gewählt wurde, wird Inhalt des Felds als Kopfzeile aller Belege der Kasse ausgegeben. Standardmäßig ist die Kopfzeile mit den im Menü **Einstellungen » Grundeinstellungen » Stammdaten** gespeicherten Daten befüllt. Daten ggf. anpassen.

|**Fußzeile**
|Option aktivieren und zusätzlichen Text eingeben.

|**Identische Auftragspositionen**
|Wählen, wie mehrere identische Varianten auf dem Beleg dargestellt werden sollen. +
**Einzeln darstellen** = Unabhängig von der gekauften Stückzahl wird jede gekaufte Variante einzeln aufgeführt: +
---------------------------------------------------- +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
Katzenfutter CaTasty Deluxe           6,99 EUR A +
---------------------------------------------------- +
**Zusammenfassen** = Identische Varianten werden zusammengefasst: +
---------------------------------------------------- +
Katzenfutter CaTasty Deluxe          20,97 EUR A +
3 x 6,99 EUR A +
----------------------------------------------------
|====

[#130]
== Benutzerkonten für POS verwalten

Um Kassenbenutzern den Zugriff auf plentymarkets POS zu ermöglichen, sind die folgenden Vorbereitungen nötig:

* Benutzerkonto der Benutzerklasse **Variabel** erstellen
* Berechtigung für Sichtbarkeit von POS aktivieren
* Berechtigungen für POS-Funktionen aktivieren (optional)
* Berechtigungen für REST-API aktivieren
* Berechtigungen für Sichtbarkeit von Kennzahlen aktivieren (optional)

Die Einstellungen, die Sie benötigen, um ein Benutzerkonto für Kassenbenutzer zu erstellen, werden nachfolgend beschrieben. Allgemeine Informationen zu Benutzerkonten und -rechten finden Sie auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#, **Benutzer verwalten**>>.

[TIP]
.Tipp: Rolle für Kassenbenutzer erstellen
====
Um die Rechteverwaltung für Kassenbenutzer zu vereinfachen, erstellen Sie eine <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#70, **Rolle**>> mit den Berechtigungen, die Sie Kassenbenutzern zuweisen möchten, und verknüpfen Sie diese Rolle mit den Benutzerkonten von Kassenbenutzern.
====

[#140]
=== Benutzerkonto für Kassenbenutzer erstellen

Damit neue Kassenbenutzer Zugriff auf plentymarkets POS erhalten, legen Sie zunächst im plentymarkets Backend **<<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#, Benutzerkonten>>** der Benutzerklasse **Variabel** für diese Benutzer an. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Neuen Kassenbenutzer erstellen:

. Öffnen Sie das Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten**.
. Klicken Sie auf **Neu**. +
→ Das Fenster **Neuen Benutzer anlegen** wird geöffnet.
. Geben Sie den **Benutzernamen**, den **realen Namen** und das **Passwort** ein.
. Wiederholen Sie das Passwort.
. Geben Sie die E-Mail-Adresse des Benutzers ein, damit er Benachrichtigungen des Systems empfängt.
. Wählen Sie die Benutzerklasse **Variabel**.
. **Speichern** Sie die Einstellungen.

[#150]
=== REST-API-Berechtigungen für Kassenbenutzer aktivieren

Im Tab **REST-API** erteilen Sie Berechtigungen für die Kommunikation zwischen plentymarkets POS und dem plentymarkets Backend über die REST-API.

[.instruction]
REST-API-Berechtigungen aktivieren:

. Öffnen Sie das Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten**.
. Öffnen Sie einen Benutzer.
. Öffnen Sie das Tab **Berechtigung**.
. Öffnen Sie das Tab **REST-API**.
. Wählen Sie im Bereich **Mobile** die Option **POS**. +
→ Die untergeordneten Berechtigungen werden automatisch gewählt.
. Aktivieren Sie im Bereich **Firma** die Berechtigung **Auftragszusammenfassung » Auftragszusammenfassung anzeigen**.
. Wenn der Kassenbenutzer berechtigt sein soll, im POS-Warenkorb auf Kundendaten zuzugreifen, aktivieren Sie die folgenden Berechtigungen: +
**Firma » Kontakt » Kontaktadresse » Kontaktadresse anzeigen** +
**Firma » Kontakt » Kontaktadresse » Adresstyp » Adresstyp anzeigen** +
**Firma » Kontakt » Kontakt anzeigen**
. **Speichern** Sie die Einstellungen.

[#160]
=== POS-Sichtbarkeit für Kassenbenutzer aktivieren

Im Tab **Mobile** legen Sie fest, welche Bereiche und Kennzahlen für Benutzer in der plentymarkets App sichtbar sein sollen.

[.instruction]
App-Berechtigungen aktivieren:

. Öffnen Sie das Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten**.
. Öffnen Sie einen Benutzer.
. Öffnen Sie das Tab **Berechtigung**.
. Öffnen Sie das Tab **Mobile**.
. Aktivieren Sie im Bereich **Sichtbare Funktionen** die Option **POS (beta)**.
. Wenn der Benutzer auf weitere Bereiche der plentymarkets App zugreifen können soll, aktivieren Sie weitere Berechtigungen.
. **Speichern** Sie die Einstellungen. +
→ Der Benutzer hat Zugriff auf plentymarkets POS und kann POS-Aufträge erstellen.

[#170]
=== Berechtigungen für optionale POS-Funktionen aktivieren

Damit Kassenbenutzer in plentymarkets POS Preise bearbeiten, Artikelpositionen umbenennen und/oder Rabatte gewähren können, müssen Sie die Berechtigungen dazu zuweisen. Wie Sie Rollen einrichten und Benutzern zuweisen, erfahren Sie **<<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#, hier>>**. Dort schalten Sie auch weitere App-Funktionen für Benutzer frei.

Im plentymarkets Backend legen Sie über das Zuweisen von Rollen fest, welche POS-Funktionen Kassenbenutzer verwenden dürfen. Dort legen Sie außerdem fest, welche weiteren Bereiche und Kennzahlen in der plentymarkets App sichtbar sein sollen.

[.instruction]
Berechtigungen für POS-Funktionen aktivieren:

. Öffnen Sie das Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten**.
. Öffnen Sie einen Benutzer.
. Öffnen Sie das Tab **Berechtigung**.
. Öffnen Sie das Tab **Mobile**.
. Aktivieren Sie die POS-Funktionen, die dem Kassenbenutzer zur Verfügung stehen sollen. Beachten Sie Tabelle 5.
. **Speichern** Sie die Einstellungen.

.Mobile-Berechtigungen für Kassenbenutzer
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Sichtbare Funktionen

|**POS (beta)**
|Erteilt Benutzer Zugang zu plentymarkets POS.

2+|POS-Funktionen

|**Preis bearbeiten**
|Erlaubt Kassenbenutzer, Preise in Aufträgen zu bearbeiten.

|**Artikelposition umbenennen**
|Erlaubt Kassenbenutzer, Positionen des Auftrags umzubenennen.

|**Rabatt gewähren**
|Erlaubt Kassenbenutzer, Rabatte auf Auftragspositionen oder ganze Aufträge zu gewähren.

|**Kassieren**
|Erlaubt Kassenbenutzer zu kassieren.

|**Kasse sperren**
|Erlaubt Kassenbenutzer, die Kasse zu sperren.

|**Einlagen und Entnahmen**
|Erlaubt Kassenbenutzer, Einlagen und Entnahmen zu tätigen.

|**Kassensturz**
|Erlaubt Kassenbenutzer, Kassenstürze durchzuführen.

|**Tagesabschluss**
a|Erlaubt Kassenbenutzer, Tagesabschlüsse zu erzeugen. +
Tagesabschlussberichte enthalten folgende Informationen: +

* Barbestand: Anfangsbarbestand, Entnahmen, Einlagen, Soll-Kassenbestand, Ist-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retouren: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufte Gutscheine: Anzahl und Summe
* Benutzer: Umsatz pro Benutzer

|**Zwischenbericht**
a|Erlaubt Kassenbenutzer, Zwischenberichte zu erzeugen. +
Zwischenberichte enthalten folgende Informationen: +

* Barbestand: Entnahmen, Einlagen, Soll-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retouren: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufte Gutscheine: Anzahl und Summe
* Benutzer: Umsatz pro Benutzer

|**Artikel synchronisieren**
|Erlaubt Kassenbenutzer, Artikeldaten mit der Kasse zu synchronisieren.

|**Aufträge hochladen**
|Erlaubt Kassenbenutzer, POS-Aufträge in plentymarkets hochzuladen.

|**Retoure anlegen**
|Erlaubt Kassenbenutzer, Retouren zu buchen.

|**Kunde auswählen**
|Erlaubt Kassenbenutzer, während des Kassierens Kundendaten aufzurufen und einen plentymarkets Bestandskunden zu wählen. +
**__Hinweis:__** Damit dieses Recht greift, muss dem Benutzer im Tab **REST-API** auch die Berechtigung **Firma » Kontakt » Adresse » Adresse anzeigen** erteilt werden.

|**Stornierung**
|Erlaubt Kassenbenutzer, Aufträge zu stornieren.
|====

=== Gesperrte POS-Benutzer entsperren

Wenn Benutzer ihr Passwort beim Login mehrmals hintereinander falsch eingegeben, wird der Benutzer eine gewisse Zeit gesperrt. Als Benutzer mit Admin-Rechten können Sie diese Sperre im plentymarkets Admin-Bereich frühzeitig aufheben.

[.instruction]
Benutzer entsperren:

. Öffnen Sie das Menü **Einstellungen » Grundeinstellungen » Benutzer » Konten » Benutzer öffnen**.
. Klicken Sie auf **Login entsperren**. +
→ Der Benutzer kann sich wieder bei der plentymarkets App anmelden.

[#700]
== Zahlungsarten für POS-Aufträge aktivieren

=== plentymarkets Zahlungsarten aktivieren

Aktivieren Sie nun die Zahlungsarten, die Sie benötigen. Beachten Sie, dass Zahlungsarten in einem weiteren Schritt für Kundenklassen erlaubt werden müssen. Weitere Informationen finden Sie unter **<<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>**.

Aktiveren Sie die folgenden Zahlungsarten, damit POS-Aufträge korrekt dargestellt werden:

* **4 » Bar bei Übergabe** für Barzahlungen
* **11 » Barverkauf/EC-Karte** für Kartenzahlungen über externe EC-Kartenterminals
* **1700 » Coupon** für Gutscheinzahlungen

Gehen Sie wie unten beschrieben vor, um diese Zahlungsarten zu aktivieren.

[.instruction]
Zahlungsarten für POS-Aufträge einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Zahlung » Zahlungsarten**.
. Aktivieren Sie die Einstellung **Auch inaktive zeigen**.
. Öffnen Sie den Ordner **International**.
. Klicken Sie auf die Zahlungsart. +
→ Das Tab **Einstellungen** wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in Tabelle 6.
. Setzen Sie ein Häkchen bei der Option **Aktiv**.
. **Speichern** Sie die Einstellungen.

.Einstellungen der Zahlungsarten für POS-Aufträge
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Sprache**
|Sprache wählen. Folgende Optionen werden sprachabhängig gespeichert: Name, Infoseite, Infoseite (Intern), Logo und Logo hochladen.

|**Name**
|Externen Namen eingeben, der auf dem Kassenbeleg und ggf. im Webshop und auf Rechnungen angezeigt werden soll. Wenn kein Name gespeichert ist, wird der Backend-Name der Zahlungsart für den Kassenbeleg verwendet. +
__**Tipp:**__ Der externe Name wird in der Sprache auf dem Beleg ausgegeben, die der Kassenbenutzer bei der Kassenanmelden wählt.

|**Infoseite**
|Standardwert **---** nur ändern, wenn die Zahlungsart auch im Webshop verwendet wird.

|**Lieferländer**
|Lieferland wählen. +
**__Hinweis:__** Lieferländer nur wählen, wenn die Zahlungsart auch im Webshop verwendet wird.

|**Mandant (Shop)**
|Mandanten der POS-Kassen wählen.

|**Logo**
|Standardeinstellung **Standardlogo anzeigen** nur ändern, wenn die Zahlungsart auch im Webshop verwendet wird.

|**Kosten: Pauschal oder Prozentual**
|Für alle Kosten **0,00** eintragen, damit kein Aufpreis für die Zahlungsart berechnet wird.
|====

[TIP]
.Zahlungsart Barverkauf/EC-Karte
====
Stellen Sie für die Zahlungsart **11 » Barverkauf/EC-Karte** außerdem im Menü **Einstellungen » Mandant (Shop) » Standard » POS  » Kasse öffnen » Tab: Zahlungsart** die Option **Ohne Anbindung** im Bereich **EC-Terminal** ein.
====

=== Kartenterminals anbinden

Bestimmte Kartenterminals können über ein Plugin an plentymarkets POS angebunden werden. Aktuell unterstützt plentymarkets POS folgende Anbindungen:

* link:https://marketplace.plentymarkets.com/plugins/payment[Ingenico-Geräte über ZVT-Schnittstelle, window="_blank"]
* link:https://marketplace.plentymarkets.com/plugins/payment[SumUp Air, window="_blank"]

Informationen zur Anbindung finden Sie in der Beschreibung des Plugins.

[#180]
== Versandart Selbstabholung einrichten

Damit POS-Aufträge korrekt in plentymarkets verbucht werden, ermöglichen Sie die Versandart **Selbstabholung** für die Artikel, die Sie über plentymarkets POS abrechnen möchten. Dazu sind folgende Vorbereitungen notwendig:

* Versanddienstleister **Selbstabholung** erstellen
* Versandprofil **Selbstabholung** erstellen
* Versandprofil **Selbstabholung** am Artikel aktivieren

Diese Vorbereitungen werden nachfolgend beschrieben.

[#190]
=== Versanddienstleister Selbstabholung erstellen

Gehen Sie wie unten beschrieben vor, um einen Versanddienstleister **Selbstabholung** zu erstellen. Es werden nur die für diesen Versanddienstleister relevanten Einstellungen beschrieben. Allgemeine Informationen zu Versanddienstleistern finden Sie auf der Handbuchseite <<auftragsabwicklung/fulfillment/versand-vorbereiten#800, **Versand vorbereiten**>>.

[.instruction]
Versanddienstleister Selbstabholung erstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versanddienstleister**.
. Klicken Sie auf **Neu**. +
→ Ganz unten wird eine neue Zeile hinzugefügt.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 7.
. **Speichern** Sie die Einstellungen.

.Versanddienstleister **Selbstabholung** erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Name (de)**
|Namen eingeben, z.B. **Selbstabholung**.

|**Name (Backend)**
|Systeminternen Namen eingeben, z.B. **Selbstabholung**.

|**Versanddienstleister**
|Option **Selbstabholer** aus der Dropdown-Liste wählen.
|====

[#200]
=== Versandprofil Selbstabholung erstellen

Erstellen Sie nun ein Versandprofil für die Selbstabholung. Es werden nur die für dieses Versandprofil relevanten Einstellungen beschrieben. Allgemeine Informationen zu Versandprofilen finden Sie auf der Handbuchseite <<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, **Versand vorbereiten**>>.

[.instruction]
Versandprofil für Selbstabholer erstellen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Versand » Versandoptionen » Tab: Versandprofile**.
. Klicken Sie auf **Neu**.
. Wählen Sie den eben erstellten Versanddienstleister aus dem Dropdown-Menü.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 8.
. **Speichern** Sie die Einstellungen. +
→ Das Tab **Portotabelle** wird angezeigt.
. **Speichern** Sie die Einstellungen des Tabs **Portotabelle** ohne Änderungen.

.Versandprofil **Selbstabholung** erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Versanddienstleister**
|Versanddienstleister **Selbstabholung** aus der Dropdown-Liste wählen.

|**Mandanten (Shops)**
|Option wird nur angezeigt, wenn mindestens ein Mandant (Shop) eingerichtet ist. Mandanten oder die Option **ALLE** wählen, wenn das Versandprofil für alle Webshops gelten soll.

|**Auftragsherkunft**
|plentymarkets POS-Kasse(n) als Auftragsherkunft wählen.

|**Gesperrte Zahlungsarten**
|Die Zahlungsarten wählen, die für das Versandprofil **Selbstabholung** nicht angeboten werden sollen.
|====

[#210]
=== Versandprofil Selbstabholung aktivieren

Aktivieren Sie nun das Versandprofil **Selbstabholung** bei den Artikeln, die Sie über Ihre Kasse verkaufen möchten.

[.instruction]
Versandprofil Selbstabholung aktivieren:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab **Global**.
. Aktivieren Sie das Versandprofil **Selbstabholung**.
. **Speichern** Sie die Einstellungen.

Sie möchten das Versandprofil für eine größere Anzahl an Artikeln gleichzeitig aktivieren? Dann nutzen Sie die <<artikel/artikel-verwalten#155, **Artikel-Gruppenfunktion**>>.

[#100]
== Preise für POS-Aufträge verwalten

Um POS-Preise für Ihre Varianten zu hinterlegen, benötigen Sie mindestens einen <<artikel/artikel-verwalten#870, **Verkaufspreis**>>, bei dem die POS-Herkunft Ihrer Kasse aktiviert ist. Verkaufspreise erstellen und verwalten Sie zentral. Preise für Ihre Varianten hinterlegen Sie, indem Sie Varianten mit dem Verkaufspreis verknüpfen und einen Preis speichern.

[#750]
=== Verkaufspreis für POS-Aufträge erstellen

Wenn Sie bereits Verkaufspreise angelegt haben, die Ihren Anforderungen für POS-Aufträge entsprechen, aktivieren Sie bei diesen Verkaufspreisen die Herkunft Ihrer Kasse. Gehen Sie sonst wie unten beschrieben vor, um einen neuen Verkaufspreis für POS-Aufträge zu erstellen. Es werden nur die für POS-Herkünfte relevanten Einstellungen beschrieben.

[.instruction]
Verkaufspreis für POS-Aufträge erstellen:

. Öffnen Sie das Menü **Einstellungen » Artikel » Verkaufspreise**.
. Klicken Sie auf **Neu**. +
→ Das Tab **Neu** wird geöffnet.
. Nehmen Sie die Einstellungen gemäß Tabelle 9 vor.
. **Speichern** Sie die Einstellungen.

.Verkaufspreis für POS-Aufträge erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Position**
|Positionsnummer eingeben. Verkaufspreise werden im Bereich **Verkaufspreise** von Artikelvarianten aufsteigend sortiert.

|**Interner Name DE**
|Internen Namen eingeben. Der interne Name wird nur im plentymarkets Backend geführt und ist nicht für Kunden sichtbar.

|**Externer Name DE**
|Externen Namen eingeben. Der externe Name wird ggf. in Ihrem Webshop angezeigt und ist für Kunden sichtbar.

|**Ab Menge**
|Mengenwert eingeben. Über Verkaufspreise mit verschiedenen Mengenwerten bilden Sie mengenbezogene Preisstaffelungen in plentymarkets ab.

|**Währung**
|Die Währung aktivieren, in der POS-Aufträge kassiert werden.

|**Preistyp**
|Preistyp für den Verkaufspreis aktivieren. +
**UVP** = Aktivieren, wenn es sich bei dem Verkaufspreis um den unverbindlichen Verkaufspreis (UVP) handelt. Wird der UVP und ein weiterer Verkaufspreis an der Variante verknüpft, dann wird der UVP im Webshop in rot und durchgestrichen neben dem Verkaufspreis dargestellt. +
**Aktionspreis** = Aktivieren, um einen Verkaufspreis als Aktionspreis zu kennzeichnen.

|**Mandant**
|Die Mandanten (Shops) aktivieren, mit denen der Verkaufspreis verknüpft wird.

|**Land**
|Das Land aktivieren, in dem die Kasse eingesetzt wird.

|**Herkunft**
|Eine oder mehrere POS-Auftragsherkünfte aktivieren, mit denen der Verkaufspreis verknüpft wird.
|====

[#550]
=== Verkaufspreis mit Varianten verknüpfen

Verknüpfen Sie nun den POS-Verkaufspreis mit den Hauptvarianten der Artikel, die Sie über die Kasse verkaufen möchten. Verkaufspreise werden von der Hauptvariante an Varianten vererbt. Sie können Verkaufspreise auch individuell mit Varianten verknüpfen.

[.instruction]
Verkaufspreis mit Hauptvariante verknüpfen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den Artikel. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Wählen Sie im Bereich **Verkaufspreise** den Preis aus dem Dropdown-Menü.
. Wählen Sie, ob es sich um einen Brutto- oder Nettopreis handelt.
. Wählen Sie ggf. eine Preiskalkulation.
. Klicken Sie auf **Hinzufügen**. +
→ Der Verkaufspreis wird hinzugefügt und in der Liste angezeigt.
. Geben Sie einen Wert in das Feld **Preis** ein.
. **Speichern** Sie die Einstellungen. +
→ Die Preise werden an die Varianten des Artikels vererbt. Speichern Sie für Varianten mit abweichendem Preis einen eigenen Wert.

[#800]
=== Rundungsverhalten für Kassenaufträge festlegen

Beträge werden auf plentymarkets POS Kassenbelegen grundsätzlich mit 2 Nachkommastellen dargestellt. Über die Einstellungen im plentymarkets Backend steuern Sie, ob die Preise in den Aufträge auch im Hintergrund auf 2 Nachkommastellen gerundet oder ob mit 4 Nachkommastellen gerechnet werden soll. Das Rundungsverhalten für Aufträge, die über plentymarkets POS Kassen generiert werden, wird über die folgenden 3 Optionen gesteuert:

.Erforderliche Optionen für Rundungsverhalten bei Kassenaufträgen
[cols="10,1,1"]
|====
|Menü |Option |Mögliche Einstellungen

|Einstellungen » Mandant (Shop) » Mandant wählen » Standorte » Standort wählen » Buchhaltung
|Anzahl Nachkommstellen bei Preisen
a|
* 2
* 4

|Einstellungen » Mandant (Shop) » Mandant wählen » Standorte » Standort wählen » Buchhaltung
|Nur Gesamtpreise runden
a|
* Ja
* Nein

|Einstellungen » Mandant (Shop) » Mandant wählen » POS » Kasse wählen » Tab: Beleg
|Identische Auftragspositionen
a|
* Einzeln darstellen
* Zusammenfassen
|====

Aus diesen Einstellungen ergeben sich 6 Einstellungskombinationen:

* Auftragspositionen einzeln darstellen, Einzelpreise auf 2 Nachkommastellen runden
* Auftragspositionen einzeln darstellen, Einzelpreise auf 4 Nachkommastellen runden
* Auftragspositionen einzeln darstellen, Gesamtpreise auf 4 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Einzelpreise auf 2 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Einzelpreise auf 4 Nachkommastellen runden
* Auftragspositionen zusammenfassen, Gesamtpreise auf 4 Nachkommastellen runden

Abhängig von den gewählten Einstellungen kommt es zu unterschiedlichen Gesamtbeträgen. Beachten Sie, dass sich die Abweichungen potenzieren, je mehr Artikel mit Rundungsbedarf pro Auftrag/Beleg verkauft werden.

==== Beispielrechnung

Die folgende Tabelle zeigt eine Beispielrechnung, um die Rundungsabweichungen zu verdeutlichen, die sich aus den verschiedenen Einstellungskombinationen ergeben.

Die Beispielrechnung beruht auf den folgenden Daten:

. Berechnungsbasis: Artikel zum Preis von 4,545 Euro
. Rechnung 1: Verkauf von 10 Artikeln
. Rechnung 2: Verkauf von 10 Artikeln mit 5 % Positionsrabatt


.Beispielrechnung bei einem Artikelpreis mit 4 Nachkommastellen
[cols="2,1,1"]
|====
|Gewählte Einstellungen |Rechnung 1 (4,545 Euro x 10) Gesamtpreis auf Beleg|Rechnung 2 (4,545 Euro x 10 - 5%) Gesamtpreis auf Beleg

|Anzahl Nachkommastellen = 2  +
Auftragspositionen = Einzeln darstellen
|45,50 Euro
|43,20 Euro

|Anzahl Nachkommastellen = 4  +
Nur Gesamtpreise runden = Nein +
Auftragspositionen = Einzeln darstellen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Ja +
Auftragspositionen = Einzeln darstellen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 2 +
Auftragspositionen = Zusammenfassen
|43,50 Euro
|43,20 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Nein +
Auftragspositionen = Zusammenfassen
|45,45 Euro
|43,18 Euro

|Anzahl Nachkommastellen = 4 +
Nur Gesamtpreise runden = Ja +
Auftragspositionen = Zusammenfassen
|45,50 Euro
|43,18 Euro
|====

Detaillierte Informationen und weitere Rechnungsbeispiele zum Rundungsverhalten finden Sie auch auf der Handbuchseite <<auftragsabwicklung/auftraege/buchhaltung#, **Buchhaltung**>>.






[#95]
== Standardkunden für POS-Aufträge erstellen

Damit POS-Aufträge korrekt in plentymarkets gespeichert werden, muss jedem Auftrag ein Kunde zugeordnet sein. Daher erstellen Sie zunächst einen anonymen Standardkunden. Gehen Sie wie hier beschrieben vor, um einen Standardkunden für POS-Aufträge anzulegen. Dabei werden nur die für das Erstellen des Standardkunden relevanten Einstellungen beschrieben. Allgemeine Informationen zum Erstellen von Kunden finden Sie auf der Handbuchseite <<crm/kundendaten-verwalten#, **Kundendaten verwalten**>>.

[IMPORTANT]
.Einstellungen für Standardkunden für POS-Aufträge mit Steuerberater abstimmen
====
Klären Sie im Vorfeld mit Ihrem Steuerberater, welche Einstellungen für Standardkunden für POS-Aufträge sinnvoll sind.
====

[.instruction]
Standardkunden für POS-Aufträge erstellen:

. Öffnen Sie das Menü **Kunden » Kunden bearbeiten**.
. Klicken Sie auf **Neu**.
. Nehmen Sie die Einstellungen gemäß Tabelle 12 vor.
. **Speichern** Sie die Einstellungen.
. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » POS » Kasse öffnen » Grundeinstellungen**.
. Geben Sie die ID des Standardkunden in das Feld **Standardkunde** ein.
. **Speichern** Sie die Einstellungen.

.Standardkunden für POS-Aufträge erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Firma**
|Einen Firmennamen eingeben, z.B. plentymarkets Kasse.

|**Anrede**
|Option **Firma** aus der Dropdown-Liste wählen.

|**Straße; +
PLZ**; +
**Ort**
|Straße, Postleitzahl und Ort des Kunden eingeben.

|**Land**
|Land aus der Dropdown-Liste wählen, in dem die Kasse eingesetzt wird. Standardeinstellung richtet sich nach der Option **Firmensitz für FiBu** im Menü **<<basics/erste-schritte/stammdaten#, Einstellungen » Grundeinstellungen » Stammdaten>>**.

|**Mandant**
|Mandanten aus der Dropdown-Liste wählen, wenn die Kasse nicht dem Standardmandanten zugeordnet ist.

|**Typ**
|Option **Kunde** aus der Dropdown-Liste wählen.
|====

[#220]
== Dummy-Artikel erstellen

Im Tagesgeschäft kommt es vor, dass Artikel verkauft werden sollen, für die es keinen Datensatz im System gibt. Zum Beispiel wird häufig für Diversartikel kein Datensatz angelegt. Um diese Artikel trotzdem kassieren zu können, erstellen Sie Dummy-Artikel. Kassenbenutzer fügen dann den Dummy-Artikel zum POS-Warenkorb hinzu und passen den Preis und optional den Namen der Artikelposition an.

Die folgenden Vorbereitungen sind nötig, um mit Dummy-Artikeln zu arbeiten.

* Einen Dummy-Artikel für jeden Umsatzsteuersatz erstellen, der für die Produkte Ihres Portfolios relevant sind. Wenn Sie Artikel mit 19% und 7% verkaufen, benötigen Sie also zwei Dummy-Artikel.
* Option *Preisabfrage wenn Artikelpreis 0* aktivieren, damit Kassenbenutzer den Preis manuell eingeben können.
* Kassenbenutzern Rechte zum Bearbeiten von Preisen erteilen.
* Kassenbenutzern Rechte zum Umbenennen von Artikelpositionen erteilen (optional).

Die erforderlichen Einstellungen werden in Tabelle 13 kurz erläutert. Die  Zwischenüberschriften der Tabelle geben an, in welchem Menü Sie die Einstellung vornehmen.

.Empfohlene Einstellungen für Dummy-Artikel
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Artikel » Artikel bearbeiten » Neuen Artikel erstellen » Tab: Einstellungen*

|**Beschränkung**
|Option **Keinen WB für diese Variante führen** wählen.

|**Preis**
|Verkaufspreis für Kasse wählen und Preis *0,00* Euro eingeben.

|**Umsatzsteuer**
|Umsatzsteuersatz eingeben, der für den Dummy-Artikel gelten soll.

2+|*Einstellungen » Mandant (Shop) » Mandant öffnen » POS » Kasse öffnen*

|**Preisabfrage wenn Artikelpreis 0**
|Option aktivieren.

2+|*Einstellungen » Grundeinstellungen » Benutzer » Konten » Konto öffnen » Tab: Berechtigung » Tab: Mobile » POS-Funktionen*

|**Preis bearbeiten**
|Recht für Kassenbenutzer aktivieren, damit Kassenbenutzer den Preis anpassen können.

|**Artikelposition umbenennen**
|Recht für Kassenbenutzer aktivieren, wenn Kassenbenutzer den Namen von Dummy-Artikeln anpassen können sollen.
|====

== Gutscheinverkauf vorbereiten

Um Verkaufsgutscheine über plentymarkets POS zu verkaufen, sind die folgenden Vorbereitungen im plentymarkets Backend erforderlich:

* Gutscheinkampagne mit Gutscheinart **Verkaufsgutschein** erstellen.
* Freitextfeld für die Kampagne anlegen und im Menü *Einstellungen » Aufträge » Gutscheine* verknüpfen.
* Gutscheinartikel mit 0% MwSt. erstellen.
* Gutscheinartikel mit Kampagne verknüpfen.
* Gutschein-Codes erzeugen oder manuell speichern.
* Gutscheinvordrucke erstellen und Kassenbenutzern zur Verfügung stellen.
* Gutschein-Codes Kassenbenutzern zur Verfügung stellen.

Diese Schritte werden hier kurz erläutert. Eine detaillierte Anleitung zum Erstellen von Gutscheinen finden Sie auf der Handbuchseite **<<auftragsabwicklung/auftraege/gutscheine#, Gutscheine>>**.

[NOTE]
.Vorgehensweise bei mehreren Kassen
====
Sie haben mehr als eine Kasse? Dann teilen Sie die ausgedruckten Gutschein-Codes zwischen den Kassen auf oder erstellen Sie für jede Kasse eigene Gutscheinkampagnen und -artikel, damit jeder Gutschein-Code nur einmal verkauft wird.
====

=== Freitextfeld vorbereiten

Um Gutscheine zu verkaufen, muss am Artikel ein Freitextfeld hinterlegt werden. Dieses Freitextfeld definieren Sie zunächst und ordnen es dann Gutscheinkampagnen zu.

[#820]
==== Freitextfeld definieren

Definieren Sie nun das Freitextfeld, das für Kampagnen verwendet werden soll.

[.instruction]
Freitextfeld definieren:

. Öffnen Sie das Menü **Einstellungen » Artikel » Freitextfelder**.
. Geben Sie in das Feld *Feldbezeichnung* die Bezeichnung **Kampagne ID** ein. +
*_Hinweis:_* Achten Sie auf die Schreibweise. Der Name **Kampagne ID** ist nur in der Schreibweise mit Leerzeichen gültig.
. Wählen Sie den Datentyp **Zahl**.
. Geben Sie eine Zeichenlänge ein.
. **Speichern** Sie die Einstellungen. +
→ Das Freitextfeld wird über Nacht aktiviert und ist am nächsten Morgen verfügbar.

==== Freitextfeld wählen

Im Menü **Einstellungen » Aufträge » Gutscheine** wählen Sie nun dieses Freitextfeld und ordnen es so Gutscheinkampagnen zu.

[.instruction]
Freitextfeld wählen:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Gutscheine**.
. Wählen Sie das Kampagnenfeld **Kampagne ID** aus der Dropdown-Liste.
. **Speichern** Sie die Einstellungen. +
→ Das Feld **Kampagne ID** wird im Tab **<<artikel/artikel-verwalten#75, Felder>>** der Artikel angezeigt.

[#830]
=== Kampagne für POS-Verkaufsgutscheine erstellen

Erstellen Sie für den Verkauf von Gutscheinen über plentymarkets POS pro Gutscheinwert eine eigene Kampagne. Wenn Sie also z.B. Gutscheine im Wert von 10 Euro, 25 Euro und 50 Euro verkaufen möchten, benötigen Sie 3 Kampagnen mit den Rabattwerten 10, 25 und 50 Euro. Wenn Sie mehr als eine Kasse einsetzen, kann es außerdem sinnvoll sein, pro Kasse eigene Kampagnen anzulegen. So erstellen Sie eine Kampagne für Verkaufsgutscheine:

[.instruction]
Kampagne für POS-Verkaufsgutscheine erstellen:

. Öffnen Sie das Menü **Aufträge » Gutscheine**.
. Klicken Sie auf **Neue Kampagne**.
. Nehmen Sie die Einstellungen vor. Beachten Sie Tabelle 14.
. **Speichern** Sie die Einstellungen.  +
→ Die neue Kampagne wird angelegt und in der Übersicht angezeigt.

.Einstellungen für POS-Verkaufsgutscheinkampagnen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Kampagne

|**Name**
|Namen für die Kampagne eingeben.
*_Tipp_*: Der Name sollte den Namen der Kasse und den Gutscheinwert enthalten.

|**Beschreibung**
|Optional eine Beschreibung eingeben.

|**Konzept: Code**
|**Mehrere Codes** wählen, um Gutschein-Codes zu erzeugt, die nur einmal einlösbar sind.

|**Konzept: Einlösungen**
|**Einlösung bis Wert aufgebraucht ist** wählen.

|**Nutzung**
|**Einzelbestellungen** oder <<auftragsabwicklung/auftraege/scheduler#, **Abonnements**>> oder beides wählen.

|**Mindestbestellwert**
|Keinen Wert eingeben.

2+|Gültigkeiten

|**Startdatum**
|Das Datum, ab dem die Kampagne aktiv sein soll.

|**Enddatum**
|Das Datum, bis zu dem die Kampagne aktiv sein soll.

|**Code-Gültigkeit in Wochen**
|Keinen Wert eingeben.

2+|Gutschein

|**Gutscheintyp**
|**Gutschein** wählen.

|**Gutscheinart**
|**Verkaufsgutschein** wählen.

|**Code-Länge**
|Die Zeichenlänge des Gutschein-Codes wählen.

|**Rabattart**
|**Festbetrag** wählen.

|**Rabattwert**
|Den Gutscheinwert eingeben, z.B. 10,00 = 10 Euro. +
*_Hinweis:_* Den Rabattwert nicht mehr ändern, nachdem der erste Gutschein verkauft wurde.

|**Inkl. Versandkosten**
|Option nicht aktivieren.

2+|Filter

|**Artikel über Preisportale**
|**Nicht erlauben** wählen.

|**Kategorien**
|Die Kategorien wählen, in denen der Gutschein einlösbar sein soll. Die Auswahl gilt auch für alle Unterkategorien einer markierten Kategorie.

|**Artikel**
|Keinen Wert eingeben.

|**Mandanten (Shops)**
|Mandanten (Shop) der Kasse wählen.

|**Kundenklassen**
|Standardkundenklasse oder *ALLE* wählen.

|**Kundentypen**
|*Kunde* wählen.
|====

[#850]
=== Gutschein-Codes erzeugen

Verkaufsgutscheine können in plentymarkets POS nur eingelöst werden, wenn beim Kassieren ein Gutschein-Code eingegeben wird. Damit Restbeträge bei einer Teileinlösung korrekt berechnet werden, benötigt jeder verkaufte Gutschein einen eigenen Gutschein-Code. Gutschein-Codes können Sie auf verschiedene Arten erstellen:

* Gutschein-Codes in plentymarkets generieren und Kassenbenutzern zur Verfügung stellen
* Gutschein-Codes extern erstellen (z.B. bei Gutscheinausstellung) und dann in plentymarkets speichern/importieren

Beide Verfahren werden hier erläutert. Empfohlen wird, Gutschein-Codes in plentymarkets zu generieren und Kassenbenutzern diese Codes zur Verfügung zu stellen.

[NOTE]
.Erstellungsdatum beachten
====
Sie haben bereits Gutschein-Codes im Umlauf und möchten weitere Gutschein-Codes erstellen? Dann achten Sie auf das Erstellungsdatum. In plentymarkets werden Gutschein-Codes nicht als verkauft gekennzeichnet. Um Gutschein-Codes nicht doppelt zu verkaufen, bringen Sie nur die Codes in Umlauf, die Sie an einem bestimmten Datum erstellt haben. Am einfachsten geht das, indem Sie Gutscheine im Menü **Aufträge » Gutscheine** generieren und die Gutschein-Codes dann als CSV-Datei exportieren. Diese CSV-Datei filtern Sie nach dem Erstellungsdatum, also nach der Spalte *GeneriertAm*. So erhalten Sie nur die neuen Gutschein-Codes. +
**__Tipp:__** Wenn Sie Gutscheine über plentymarkets POS verkaufen, wird automatisch ein Gutschein-Code generiert. Aus technischen Gründen wird dieser Code jedoch nicht an der Kasse ausgegeben. Im Menü **Aufträge » Gutscheine** werden also auch Gutschein-Codes mit anderem Erstellungsdatum aufgeführt. Diese Codes können Sie entweder löschen oder verkaufen. Achten Sie aber auch hier darauf, jeden Code nur einmal in Umlauf zu bringen.
====

==== Gutschein-Codes manuell generieren

Mit dem Gutschein-Generator im Tab **Codes** einer Kampagne erzeugen Sie gleichzeitig mehrere Gutschein-Codes.

[.instruction]
Gutschein-Codes generieren:

. Öffnen Sie das Menü **Aufträge » Gutscheine**.
. Klicken Sie auf die Kampagne, für die Sie Gutschein-Codes erzeugen möchten.
. Öffnen Sie das Tab **Codes**.
. Geben Sie im Bereich **Gutschein-Codes manuell generieren** links die gewünschte Anzahl an Gutschein-Codes ein.
. **Speichern** Sie die Eingabe. +
→ Die Gutschein-Codes werden erzeugt und zur Liste der Gutschein-Codes hinzugefügt.
. Klicken Sie auf *Exportieren*, um die Gutschein-Codes zu exportieren. +
→ Ein CSV-Export aller Gutschein-Codes der Kampagne wird erstellt.
. Filtern Sie die Spalte *GeneriertAm* der CSV-Datei nach dem aktuellen Datum. So erhalten Sie eine Liste aller neu erstellten Gutschein-Codes. +
. Stellen Sie die Gutschein-Codes Kassenbenutzern zur Verfügung. +
*_Hinweis:_* Achten Sie darauf, dass Gutschein-Codes nicht doppelt in Umlauf geraten. Teilen Sie bei mehreren Kassen die Gutschein-Codes entweder auf oder erstellen Sie separate Kampagnen pro Kasse.

==== Eigene Gutschein-Codes speichern

Statt Gutschein-Codes in plentymarkets zu generieren, können Sie auch eigene Gutschein-Codes in plentymarkets speichern. Gültige Zeichen für Gutschein-Codes sind Klein- und Großbuchstaben, Ziffern, Unterstriche (_) und Bindestriche (-).

[.instruction]
Gutschein-Code manuell speichern:

. Öffnen Sie das Menü **Aufträge » Gutscheine**.
. Klicken Sie auf die Kampagne, für die Sie einen Gutschein-Code speichern möchten.
. Öffnen Sie das Tab **Codes**.
. Geben Sie im Bereich **Gutschein-Code manuell eintragen** rechts einen Code mit zwischen 6 und 24 Zeichen ein.
. **Speichern** Sie die Eingabe. +
→ Der Gutschein-Code wird gespeichert und zur Liste der Gutschein-Codes hinzugefügt. +
*_Hinweis:_* Kunden können Gutscheine nur einlösen, wenn ihr Gutschein-Code in plentymarkets gespeichert ist. Wenn Sie Gutschein-Codes außerhalb von plentymarkets generieren, sollten Sie diese Codes daher zeitnah in plentymarkets speichern. +
*_Tipp:_* Mit dem Datenformat **CampaignCoupon** importieren Sie mehrere Gutschein-Codes gleichzeitig.

[#840]
=== Gutscheinartikel erstellen

Legen Sie nun pro Gutscheinwert einen Artikel an. Da die Kampagnen-ID auf Artikelebene zugeordnet wird, können Sie bei Verkaufsgutscheinen nicht mit Varianten arbeiten. Detaillierte Informationen zum Erstellen von Artikeln finden Sie auf der Handbuchseite **<<artikel/artikel-verwalten, Artikel verwalten>>**. Tabelle 14 zeigt nur die wichtigsten Einstellungen für Gutscheinartikel.

[.instruction]
Gutscheinartikel erstellen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Klicken Sie auf **Neu**. +
→ Das Tab **Neuer Artikel** wird geöffnet.
. Wählen Sie den Typ **Standard**.
. Geben Sie einen Namen ein.
. Geben Sie als Inhalt **1 Stück** ein.
. Wählen Sie eine Kategorie.
. Wählen Sie einen Verkaufspreis aus der Dropdown-Liste.
. Geben Sie als Preis den Gutscheinwert ein.
. **Speichern** Sie die Einstellungen. +
→ Der Artikel wird erstellt und zur weiteren Bearbeitung geöffnet.
. Nehmen Sie die weiteren Einstellungen vor. Beachten Sie Tabelle 15.
. **Speichern** Sie die Einstellungen.

.Artikeleinstellungen für Verkaufsgutscheine
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Tab: Variantennummer » Tab: Einstellungen

|**Beschränkung**
|**Keine** wählen.

|**Umsatzsteuer**
|**0%** wählen.

2+|Tab: Variantennummer » Tab: Verfügbarkeit

|**Märkte**
|Kasse(n) aus der Dropdown-Liste wählen, über die die Gutscheinartikel verkauft werden sollen.

|**Mandant (Shop)**
|Mandant der Kasse wählen.

2+|Tab: Felder

|**Kampagne ID**
|ID der Gutscheinkampagne eingeben.
|====

=== Besonderheiten beim Verkauf von Verkaufsgutscheinen

* Der Gutschein-Code wird nicht auf dem Beleg ausgegeben. Daher benötigen Sie Gutscheinvordrucke, in die Kassenbenutzer den Gutschein-Code per Hand eintragen.
* Beim Verkauf des Verkaufsgutscheins erhöht sich der Umsatz nicht.
* Verkaufte Gutscheine werden auf dem Tagesbericht separat ausgewiesen. Der Barbestand wird erhöht, wenn der Gutschein bar bezahlt wurde.

=== Besonderheiten beim Einlösen von Verkaufsgutscheinen

* Der Wert des Verkaufsgutscheins wird vom Gesamtbetrag inkl. Steuern abgezogen.
* Der Umsatz erhöht sich um den eingelösten Gutscheinbetrag.
* Auf dem Tagesbericht wird der eingelöste Gutscheinwert mit der Zahlungsart *Gutschein* ausgewiesen.
* Der Barbestand der Kasse erhöht sich durch die Einlösung des Gutscheins nicht.

== Warenbestandsverwaltung automatisieren

Ihre <<warenwirtschaft/waren-ausbuchen#, **Warenbestandsverwaltung**>> automatisieren Sie über Ereignisaktionen.

=== Warenausgang buchen

Legen Sie die unten beschriebene Ereignisaktion an, um Waren automatisch auszubuchen, wenn ein POS-Auftrag erstellt wird:

[.collapseBox]
.Buchen des Warenausgangs beim Erstellen eines POS-Auftrags:
--
. Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
. Klicken Sie auf **Ereignisaktion hinzufügen**.  +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das **Ereignis** gemäß Tabelle 16.
. **Speichern** Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß Tabelle 16 vor.
. Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Buchen des Warenausgangs beim Erstellen eines POS-Auftrags
[cols="a,a,a"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Dokumente: Kassenbeleg generiert**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|Kassen wählen, für die Warenausgang gebucht werden soll.

|**Aktion**
|**Auftrag &gt; Warenausgang buchen**
|
|====

[#600]
== plentymarkets App installieren

Installieren Sie nun die plentymarkets App auf Ihrem mobilen Endgerät.

[WARNING]
.Offline-Aufträge werden bei Deinstallation der App gelöscht
====
Bei fehlender Internetverbindung werden Aufträge offline gespeichert und erst später synchronisiert. Wenn Sie die App deinstallieren, bevor die Aufträge an plentymarkets übertragen wurden, werden die lokal gespeicherten Aufträge unwiederbringlich gelöscht und können auch vom plentymarkets Support nicht wiederhergestellt werden. Prüfen Sie daher vor jeder Deinstallation Ihrer App, dass keine Offline-Aufträge auf dem Gerät vorhanden sind.
====

[#230]
== Kasse mit Mobilgerät verbinden

=== Kasse mit Mobilgerät koppeln

Gehen Sie wie unten beschrieben vor, um eine Kasse mit einem Gerät zu koppeln.

[.instruction]
Kasse mit Mobilgerät koppeln:

. Öffnen Sie die plentymarkets App auf dem Gerät, das Sie mit der Kasse koppeln möchten.
. Öffnen Sie das Menü **plentymarkets App  » Einstellungen » POS beta**.
. Nehmen Sie die Einstellungen vor. Beachten Sie Tabelle 17.
. **Speichern** Sie die Einstellungen. +
→ Das Gerät wird mit der Kasse gekoppelt.

.Kasse mit Mobilgerät koppeln
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Mandant (Shop)**
|Mandant wählen, für den die Kasse angelegt wurde.

|**POS**
|Kasse wählen.

|**Preis**
|Wählen, ob Aufträge brutto oder netto angelegt werden sollen.

|**Drucker**
|IP-Adresse des Belegdruckers eingeben. +
**__Tipp:__** Auf **Testbeleg drucken** tippen, um einen Testbeleg zu drucken.

|**Automatisches Drucken**
|**Aus** =  Das Drucken von Kassenbelegen muss manuell ausgelöst werden. +
**Ein** = Standardeinstellung. Kassenbelege werden automatisch gedruckt, wenn ein Bezahlvorgang abgeschlossen wurde.

|**Darstellung** +
(nur Tablets)
|**Smartphone** =  Für Smartphones optimierte Darstellung; Hoch- oder Querformat. +
**Tablet** = Für Tablets optimierte Darstellung; nur Querformat.
|====

[#240]
=== Kasse von Mobilgerät entkoppeln

Sie haben die Möglichkeit, die Koppelung einer Kasse mit dem Mobilgerät aufzuheben. Stattdessen können Sie entweder eine andere Kasse mit dem Gerät verbinden oder keine Kasse wählen.

[.instruction]
Kasse von Mobilgerät entkoppeln:

. Öffnen Sie die plentymarkets App.
. Öffnen Sie das Menü **plentymarkets App  » Einstellungen » POS beta**.
. Wählen Sie für die Einstellung **POS** eine andere Kasse oder wählen Sie den leeren Eintrag.
. **Speichern** Sie die Einstellungen. +
→ Das Gerät wird von der Kasse entkoppelt.

[IMPORTANT]
.Entkoppelung der Kasse nur auf dem Mobilgerät möglich
====
Sie können die Kasse nur über die Einstellungen auf dem Mobilgerät von der Kasse entkoppeln. Wenden Sie sich bei einem Verlust oder Defekt des Mobilgeräts an den plentymarkets Support, um die Koppelung aufzuheben.
====

[#250]
== Senden des Kassenbelegs an Kunden einrichten

plentymarkets ermöglicht es Ihnen, Kassenbelege per Ereignisaktion automatisch an die am Kundendatensatz gespeicherte E-Mail-Adresse zu senden. Dazu erstellen Sie zunächst eine E-Mail-Vorlage mit dem PDF-Anhang **Kassenbeleg**. Erstellen Sie dann eine Ereignisaktion. Für POS-Aufträge, die im Offline-Modus erstellt werden, wird die Ereignisaktion jedoch erst ausgeführt, wenn die POS-Aufträge in das plentymarkets Backend hochgeladen werden. Prüfen Sie vor der Einrichtung die aktuellen gesetzlichen Bestimmungen zum Versand von E-Mails an Kunden.

[#260]
=== E-Mail-Vorlage erstellen

Erstellen Sie zunächst eine <<crm/e-mails-versenden#1200, **E-Mail-Vorlage**>>, die versendet wird, wenn ein Kassenbeleg generiert wird.

[.instruction]
E-Mail-Vorlage erstellen:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » E-Mail » Vorlagen**.
. Klicken Sie auf **Neue E-Mail-Vorlage**. +
→ Das Fenster **Neue E-Mail-Vorlage** wird geöffnet.
. Geben Sie einen Namen für die Vorlage ein.
. Wählen Sie einen Eigner oder **Alle** aus der Dropdown-Liste **Eigner**.
. Klicken Sie auf **Speichern**. +
→ Die E-Mail-Vorlage wird erstellt und je nach gewähltem Eigner in einem der drei Ordner gespeichert.
. Wählen Sie den PDF-Anhang **Kassenbeleg**.
. Nehmen Sie die weiteren Einstellungen vor. Beachten Sie die Erläuterungen unter <<crm/e-mails-versenden#1200, **Neue E-Mail-Vorlage erstellen**>>.
. **Speichern** Sie die Einstellungen.

[#270]
=== Ereignisaktion erstellen

Erstellen Sie nun eine Ereignisaktion, über die die E-Mail-Vorlage versendet wird, wenn ein Kassenbeleg generiert wird.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
. Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das **Ereignis** gemäß Tabelle 18.
. **Speichern** Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß Tabelle 18 vor.
. Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden des Kassenbelegs
[cols="a,a,a"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Dokumente: Kassenbeleg generiert**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag** +
**Retoure**

|**Filter 2**
|**Auftrag &gt; Herkunft**
|Kasse wählen, für die Kassenbelege per E-Mail versendet werden sollen.

|**Aktion**
|**Kunde &gt; E-Mail versenden**
|**Vorlage**: Die E-Mail-Vorlage für Kassenbeleg wählen +
**Empfänger**: Option **Kunde** wählen
|====

[#400]
== Kassenvorgänge im Kassenjournal suchen

In plentymarkets werden alle Kassenvorgänge dokumentiert, um rechtssicheres Arbeiten in Deutschland zu ermöglichen. Im Menü **Aufträge » POS » Kassenjournal** können Sie Kassenvorgänge suchen, anzeigen und bei Bedarf exportieren. Mit den Filtern des Tabs **Filter** grenzen Sie die im Kassenjournal angezeigten Kassenvorgänge anhand bestimmter Kriterien ein. Die gefundenen Kassenvorgänge werden im Tab **Kassenjournal** aufgelistet. Die Ergebnisse sind standardmäßig nach dem Datum sortiert. Gehen Sie wie unten beschrieben vor, um Kassenvorgänge im Kassenjournal zu suchen.

[.instruction]
Kassenvorgänge im Kassenjournal suchen:

. Öffnen Sie das Menü **Aufträge » POS » Kassenjournal**.
. Wählen Sie die Filter. Beachten Sie die Erläuterungen in Tabelle 19.
. Klicken Sie auf **Suchen**. +
→ Die Kassenvorgänge, die den Suchkriterien entsprechen, werden im Tab **Kassenjournal** aufgelistet.

.Menü **Kassenjournal**
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|Tab: Filter

|**Suchen**
|Ohne Filtereinstellungen auf **Suchen** klicken, um alle Kassenvorgänge anzuzeigen. Alternativ die Suchergebnisse durch Filtereinstellungen eingrenzen und auf **Suchen** klicken. Die gefundenen Kassenvorgänge werden im Tab **Kassenjournal** aufgelistet.

|**Reset**
|Eingestellte Filterkriterien zurücksetzen.

|**Belegnummer: von**; +
**Belegnummer: bis**
|Die Belegnummer des ersten und des letzten Belegs eingeben, um Kassenvorgänge einer bestimmten Belegabfolge anzuzeigen. Um nur einen Beleg anzuzeigen, die gesuchte Belegnummer in die Felder **Belegnummer: von** und **Belegnummer: bis** eingeben.

|**Kasse**
|Eine Kasse aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieser Kasse einzugrenzen.

|**Mandant (Shop)**
|Einen Mandanten (Shop) aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieses Mandanten einzugrenzen.

|**Benutzer**
|Einen Benutzer aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieses Benutzers einzugrenzen.

|**Zahlungsart**
|Eine Zahlungsart aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge mit dieser Zahlungsart einzugrenzen. Die Dropdown-Liste enthält nur aktive Zahlungsarten.

|**Zeitraum**
|Eine Zeitspanne wählen, um die angezeigten Kassenvorgänge auf diesen Zeitraum zu beschränken. +
Um Belege eines benutzerdefinierten Zeitraums anzuzeigen, die Option **Datumsauswahl** wählen und im Feld **von** das Startdatum und im Feld **bis** das Enddatum eingeben oder aus dem angezeigten Kalender wählen.

|**Typ**
|Einen Typ aus der Dropdown-Liste wählen, um die Ergebnisse auf Kassenvorgänge dieses Typs einzugrenzen.

2+|Tab: Kassenjournal

|**Datum**
|Datum und Uhrzeit des Kassenvorgangs

|**Vorgang**
|Zeigt an, ob es sich um eine Einnahme (**E**) oder um eine Ausgabe (**A**) handelt.

|**Betrag**
|Der Wert des Kassenvorgangs

|**Belegnummer**
|Die fortlaufende Nummer des Belegs, der für den Kassenvorgang erstellt wurde. Auf die Belegnummer klicken, um den Beleg im PDF-Format zu öffnen.

|**Typ**
|Der Typ des Kassenvorgangs

|**Barbestand**
|Der Barbestand der Kassen nach Abschluss des Kassenvorgangs

|**Auftrags-ID**
|Die ID des in plentymarkets angelegten Auftrags

|**Steuersatz**
|Die Steuersätze, die für diesen Auftrag zum Tragen kommen.

|**USt.**
|Die im Auftragswert enthaltene Umsatzsteuer

|**Buchungstext**
|Der Buchungstext für den Kassenvorgang. Bei Einlagen und Entnahmen entspricht der Buchungstext dem Grund der Bargeldbewegung.
|====

[#300]
== Kassenvorgänge in Deutschland rechtssicher belegen

Für eine ordnungsgemäße Kassenführung in Deutschland müssen alle Kassenvorgänge elektronisch und unveränderbar aufgezeichnet und für die Dauer des Aufbewahrungszeitraums digital lesbar archiviert werden. Damit Sie diesen gesetzlichen Anforderungen nachkommen können, stellt plentymarkets verschiedene Exportfunktionen bereit. Besprechen Sie mit Ihrem Steuerberater, welche Daten Sie exportieren und archivieren sollten, um rechtssicher zu arbeiten.

=== Kassenvorgänge als PDF-/CSV-Datei exportieren

Die im Kassenjournal angezeigten Kassenvorgänge können Sie entweder als PDF-Datei oder als CSV-Datei exportieren. Exportiert werden die über die Suche gefilterten Kassenvorgänge. Gehen Sie wie unten beschrieben vor, um Kassenvorgänge zu exportieren. Nachdem Sie einen Exportvorgang gestartet haben, ist das Starten weiterer Kassenjournalexporte zwei Minuten lang nicht möglich.

[.instruction]
Kassenvorgänge als PDF-Datei exportieren:

. Öffnen Sie das Menü **Aufträge » POS » Kassenjournal**.
. Wählen Sie die Filter. Beachten Sie die Erläuterungen in Tabelle 19.
. Klicken Sie auf **Suchen**. +
→ Die Kassenvorgänge, die den Suchkriterien entsprechen, werden im Tab **Kassenjournal** aufgelistet.
. Klicken Sie auf **PDF-Export**. +
→ Eine PDF-Datei der gefilterten Kassenvorgänge wird generiert. Abhängig von der Anzahl der Datensätze kann dieser Vorgang mehrere Minuten dauern. +
→ Die PDF-Datei wird in einem separaten Browser-Fenster angezeigt.
. **Speichern** Sie die PDF-Datei.

[.instruction]
Kassenvorgänge als CSV-Datei exportieren:

. Öffnen Sie das Menü **Aufträge » POS » Kassenjournal**.
. Wählen Sie die Filter. Beachten Sie die Erläuterungen in Tabelle 19.
. Klicken Sie auf **Suchen**. +
→ Die Kassenvorgänge, die den Suchkriterien entsprechen, werden im Tab **Kassenjournal** aufgelistet.
. Klicken Sie auf **CSV-Export**.
. Wählen und bestätigen Sie einen Speicherort für die CSV-Datei. +
→ Eine CSV-Datei der gefilterten Kassenvorgänge wird generiert. Abhängig von der Anzahl der Datensätze kann dieser Vorgang mehrere Minuten dauern. +
→ Die CSV-Datei wird gespeichert.

[#500]
=== IDEA-Export erstellen

Laut den deutschen handels- und steuerrechtlichen Ordnungsvorschriften (GoBD) müssen Sie bei einer Außenprüfung auf Verlangen der Finanzverwaltung nicht nur aufzeichnungs- und aufbewahrungspflichtige Daten vorlegen, sondern auch alle zur Auswertung der Daten notwendigen Strukturinformationen in maschinell auswertbarer Form bereitstellen. Deshalb stellt plentymarkets einen GoBD-konformen Export Ihrer Kassenvorgänge bereit. Die Exportdateien ermöglichen es Betriebsprüfern, Ihre Kassendaten vollständig und effizient auszuwerten. Gehen Sie wie unten beschrieben vor, um einen IDEA-Export zu erstellen:

[.instruction]
IDEA-Dateien exportieren:

. Öffnen Sie das Menü **Aufträge » POS » IDEA-Export**.
. Wählen Sie das Kalenderjahr, für das Sie die Daten exportieren möchten.
. Klicken Sie auf das Zahnrad, um den Export zu generieren. +
→ Der Export wird über Nacht generiert. +
→ Der Export ist abgeschlossen, wenn der Status **Fertig** angezeigt wird.
. Klicken Sie auf das Download-Symbol in der Spalte **Aktionen**.
. Wählen Sie einen Speicherort und bestätigen Sie die Auswahl. +
→ Die IDEA-Dateien werden exportiert und als ZIP-Datei gespeichert.

//  Next: 860
