= POS für Kassenbenutzer
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentymarkets POS, Kasse, POS, plentymarkets Kasse, Kassenbenutzer, POS-Benutzer, Katzenbenutzer
:position: 20

Auf dieser Handbuchseite erfahren Sie, wie Sie die plentymarkets POS Kasse bedienen.

////
p>Noch beschreiben:</p>

<ul>
<li>Artikel oder Variante???</li>
<li>Wie setzt sich die Belegnummer zusammen?</li>
<li>Preis bearbeiten</li>
<li>Dummy-Artikel, wenn Artikel nicht gefunden wird</li>
<li>Favoriten in der App anlegen</li>
<li>Umbuchen</li>
<li>Warenbestand prüfen</li>
<li>(Kasse sperren)</li>
<li>(Artikel synchronisieren)</li>
<li>(Aufträge hochladen)</li>
</ul
////

[#5]
== plentymarkets App installieren

Installieren Sie zunächst die plentymarkets App auf Ihrem mobilen Endgerät.

* **link:https://play.google.com/store/apps/details?id=eu.plentymarkets.mobile&hl=de[plentymarkets App bei Google Play^]**

* **link:https://itunes.apple.com/de/app/plentymarkets/id957702618[plentymarkets App bei iTunes^]**

[WARNING]
.Offline-Aufträge werden bei Deinstallation der App gelöscht
====
Bei fehlender Internetverbindung werden Aufträge offline gespeichert und erst später synchronisiert. Wenn Sie die App deinstallieren, bevor die Aufträge an plentymarkets übertragen wurden, werden die lokal gespeicherten Aufträge unwiederbringlich gelöscht und können auch vom plentymarkets Support nicht wiederhergestellt werden. Prüfen Sie daher vor jeder Deinstallation Ihrer App, dass keine Offline-Aufträge auf dem Gerät vorhanden sind.
====

[#10]
== Bei plentymarkets POS anmelden

Gehen Sie wie unten beschrieben vor, um sich bei plentymarkets POS anzumelden.

[.instruction]
Bei plentymarkets POS anmelden:

. Melden Sie sich auf dem Mobilgerät an.
. Tippen Sie auf dem Startbildschirm auf das plentymarkets App Symbol. +
→ Der Login-Bildschirm wird angezeigt.
. Geben Sie Ihre Login-Daten ein. Beachten Sie <<tabelle-POS-kassenbenutzer-anmeldung>>.
. Tippen Sie auf **Login**. +
→ Der Startbildschirm der plentymarkets App wird angezeigt.
. Tippen Sie oben links auf das Menüsymbol. +
→ Die verfügbaren Menüpunkte werden angezeigt.
. Tippen Sie auf **POS**. +
→ plentymarkets POS wird geöffnet.

[TIP]
.Anmeldung wird gespeichert
====
Sie bleiben bei plentymarkets POS angemeldet, bis Sie im Menü der App auf **Ausloggen** tippen. Sie können also die App schließen und öffnen, ohne sich erneut anmelden zu müssen.
====

[[tabelle-POS-kassenbenutzer-anmeldung]]
.Anmeldung
[cols="1,2"]
|====
|Einstellung |Erläuterung

|Sprache
|Sprache wählen, in der plentymarkets POS dargestellt werden soll. Die Benutzeroberfläche von plentymarkets POS ist auf Deutsch und Englisch verfügbar.

|**System (Basis-URL)**
|Domain des plentymarkets Systems ohne führendes https:// oder http:// eingeben, z.B. **ihr-shop.de**.

|**Benutzer**; **Passwort**
|Benutzernamen und Passwort für das plentymarkets System eingeben.
|====

////
[#290]
== plentymarkets POS personalisieren

=== Darstellung anpassen

[.instruction]
Darstellung anpassen:

. Öffnen Sie das Menü **Einstellungen » Artikel » Attribute**.
. Klicken Sie auf das Attribut.
. Wechseln Sie in das Tab **Werte**.
. Klicken Sie auf **Neuer Wert**.
. Geben Sie den internen Namen ein.
. Klicken Sie auf **Speichern**. +
→ Der Attributwert erhält eine ID und wird im Tab **Werte** angezeigt.
. Nehmen Sie ggf. weitere Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 2.
. **Speichern** Sie die Einstellungen.

[[tabelle-POS-darstellung]]
.titel
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+|*Hintergrund wählen*

|*Hintergrund wählen*
|Auf das Bild tippen, das als Hintergrund in der Kasse angezeigt wird.

2+|*Vollbildmodus verwenden*

|*Vollbildmodus* +
(nur Android-Geräte)
|Aktivieren, um die Softkeys des Betriebssystems auszublenden.
|====
////

[#30]
== Kassieren

Nachdem Sie sich bei plentymarkets POS angemeldet haben, wird das POS-Menü angezeigt. Tippen Sie auf **Kassieren**, um den POS-Warenkorb zu öffnen und Artikel hinzuzufügen.

[#40]
=== Artikel zum POS-Warenkorb hinzufügen

Sie können Artikel über die Artikelsuche, die Favoritenliste oder per Etiketten-Scan zu plentymarkets POS zum aktuellen Auftrag hinzufügen.

[#50]
==== Artikel suchen

Über die Artikelsuche haben Sie Zugriff auf den gesamten Artikelbestand des Mandanten. Eine Suche ist anhand folgender Artikeldaten möglich:

* Artikel-ID
* Variantennummer
* Barcode
* Artikelname
* Varianten-ID
* Lieferanten-Artikel-Nr.

Gehen Sie wie unten beschrieben vor, um Artikel über die Suche zum POS-Warenkorb hinzufügen.

[.instruction]
Artikel über Suche hinzufügen:

. Tippen Sie im POS-Warenkorb auf die Lupe. +
→ Die Artikelsuche wird geöffnet.
. Geben Sie ein Suchkriterium ein.
. Tippen Sie auf **Suchen**. +
→ Die gefundenen Artikel werden aufgelistet.
. Tippen Sie auf das grün hinterlegte Häkchen, um einen Artikel in den Warenkorb zu legen. +
→ Das Fenster **Menge eingeben** wird angezeigt.
. Geben Sie die Menge des Artikels ein, die Sie in den Warenkorb legen möchten. +
→ Der Artikel wird in den Warenkorb gelegt und die zu zahlende Summe aktualisiert. +
**__Tipp:__** Artikel ohne Nettowarenbestand werden in roter Schrift dargestellt, können aber verkauft werden.

[#60]
==== Favoritenliste öffnen

Über die Favoritenliste greifen Sie schnell auf als Favoriten gekennzeichnete Artikel zu. plentymarkets Administratoren können eine Favoritenliste für die Kasse hinterlegen. Aber auch Sie selbst können häufig gekaufte Artikel als Favoriten kennzeichnen, um den Kassiervorgang zu beschleunigen. Gehen Sie wie unten beschrieben vor, um Artikel über die Favoritenliste zum POS-Warenkorb hinzufügen.

[.instruction]
Artikel über Favoritenliste hinzufügen:

. Tippen Sie im POS-Warenkorb auf den Stern. +
→ Die Liste der Favoriten wird geöffnet.
. Tippen Sie auf das grün hinterlegte Häkchen, um einen Artikel in den Warenkorb zu legen. +
→ Das Fenster **Menge eingeben** wird angezeigt. +
. Geben Sie die Menge des Artikels ein, die Sie in den Warenkorb legen möchten. +
→ Der Artikel wird in den Warenkorb gelegt und die zu zahlende Summe aktualisiert.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter.

[#70]
==== Artikeletikett scannen

Wenn Sie mit Artikeletiketten arbeiten, können Sie Artikel auch das Etikett eines Artikels scannen, um ihn zum POS-Warenkorb hinzufügen. Artikel können Sie über die Kamera des Mobilgeräts oder einen angeschlossenen Bluetooth-Scanner einlesen. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Artikeletikett mit integrierter Gerätekamera scannen:

. Tippen Sie im POS-Warenkorb auf das Etikettensymbol. +
→ Die Kamera Ihres Mobilgeräts wird aktiviert.
. Tippen Sie auf das Kamerasymbol, um das Etikett zu scannen. +
→ Der Artikel wird mit einer Menge von 1 in den POS-Warenkorb gelegt. +
→ Die zu zahlende Summe wird aktualisiert. +
*_Tipp:_* Wenn im Feld *Eingabe* kein Währungszeichen angezeigt wird, können Sie die Menge eingeben und dann den Artikel scannen. Der Artikel wird dann mit der eingegebenen Menge in den POS-Warenkorb gelegt. Diese Komfortfunktion muss ein Administrator für die Kasse aktivieren.

[.instruction]
Artikeletikett mit externem Bluetooth-Scanner scannen:

. Öffnen Sie den POS-Warenkorb. +
. Scannen Sie das Etikett des Artikels. +
→ Der Artikel wird mit einer Menge von 1 in den POS-Warenkorb gelegt. +
→ Die zu zahlende Summe wird aktualisiert. +
*_Tipp:_* Wenn im Feld *Eingabe* kein Währungszeichen angezeigt wird, können Sie die Menge eingeben und dann den Artikel scannen. Der Artikel wird dann mit der eingegebenen Menge in den POS-Warenkorb gelegt. Diese Komfortfunktion muss ein Administrator für die Kasse aktivieren.

[#80]
=== Zahlung entgegennehmen

Nachdem Sie alle Artikel des Kunden in den POS-Warenkorb gelegt haben und ggf. Rabatte/Verkaufsgutscheine angewendet haben, buchen Sie die Zahlung. Zurzeit können die Zahlungsarten Barzahlung und Zahlung über EC-Terminal verwendet werden.

[NOTE]
.Auftrag stornieren
====
Sie können einen POS-Auftrag direkt stornieren, nachdem Sie die Zahlung gebucht haben. Tippen Sie dazu in der Ansicht **Auftrag erstellt** auf **Auftrag stornieren**. Abgeschlossene Aufträge, die seit dem letzten Tagesabschluss über die Kasse erstellt wurden, stornieren Sie über das Menü <<omni-channel/pos/pos-kassenbenutzer#173, POS » Auftrag stornieren>>.
====

[.instruction]
Barzahlung:

. Geben Sie über das Tastenfeld den Betrag ein, den Sie vom Kunden erhalten haben.
. Tippen Sie auf **Zahlung erhalten**. +
→ Die Ansicht **Auftrag erstellt** wird angezeigt. +
→ Der Auftrag wird erstellt. +
→ Ein Beleg wird gedruckt. Alternativ tippen Sie auf **Beleg drucken**, um den Beleg zu drucken. +
**__Tipp:__** Über den Button **Auftrag anzeigen** rufen Sie die Auftragsdaten auf.
. Tippen Sie auf **Neuer Auftrag**, um einen neuen POS-Auftrag anzulegen.

[.instruction]
Zahlung über externes EC-Terminal:

. Tippen Sie auf **EC-Terminal**. +
→ Die zu zahlende Auftragssumme wird angezeigt.
. Führen Sie die Zahlung am EC-Terminal durch.
. Tippen Sie auf **Betrag erhalten/Zahlung abschließen**, um den Auftrag abzuschließen. +
→ Die Ansicht **Auftrag erstellt** wird angezeigt. +
→ Der Auftrag wird erstellt. +
→ Ein Beleg wird gedruckt. Alternativ tippen Sie auf **Beleg drucken**, um den Beleg zu drucken. +
**__Tipp:__** Über den Button **Auftrag anzeigen** rufen Sie die Auftragsdaten auf.
. Tippen Sie auf **Neuer Auftrag**, um einen neuen POS-Auftrag anzulegen.


[.instruction]
Zahlung über angebundenes EC-Terminal:

. Tippen Sie auf **EC-Terminal**.
. Folgen Sie den angezeigten Hinweisen, um die Zahlung über das Terminal abzuschließen. +
→ Die Ansicht **Auftrag erstellt** wird angezeigt. +
→ Der Auftrag wird erstellt. +
→ Die Belege werden gedruckt. Alternativ tippen Sie auf **Händlerbeleg drucken** bzw. **Kundenbeleg drucken**, um das Drucken manuell zu starten. +
**__Tipp:__** Über den Button **Auftrag anzeigen** rufen Sie die Auftragsdaten auf.
. Tippen Sie auf **Neuer Auftrag**, um einen neuen POS-Auftrag anzulegen.


[#250]
=== Verkaufsgutschein verkaufen

Jeder Verkaufsgutschein hat einen einzigartigen Gutschein-Code. Dieser Gutschein-Code wird auf dem Beleg ausgegeben, wenn Sie einen Gutscheinartikel verkaufen. Damit Ihre Kunden einen Gutschein-Code einlösen können, muss dieser Gutschein-Code zu dem Zeitpunkt, in dem die Kundin den Gutschein einlösen möchte, im plentymarkets System gespeichert sein. Je nach den Abläufen in Ihrem Ladengeschäft generieren Sie Gutschein-Codes entweder automatisch beim Verkauf des Gutscheins oder Sie arbeiten mit Gutschein-Code-Listen, die Ihnen Ihr Arbeitgeber zur Verfügung stellt. Die Codes auf dieser Liste sind entweder bereits im System gespeichert oder Sie speichern die Codes beim Verkauf. Erkundigen Sie sich bei Ihrem Arbeitgeber, wie Sie beim Verkauf von Gutscheinen vorgehen sollten.

[.instruction]
Verkaufsgutschein verkaufen und automatischen Gutschein-Code generieren:

. Legen Sie den Gutscheinartikel mit dem gewünschten Gutscheinwert in den POS-Warenkorb.
. Wählen Sie die Menge. +
→ Das Fenster **Gutschein wählen** wird angezeigt.
. Tippen Sie auf **Generieren**. +
**__Tipp:__** Wenn Sie mehr als einen Gutschein als Menge wählen, wird dieser Schritt übersprungen.
. Geben Sie ggf. den Wert des Gutscheins ein. +
→ Bei Gutscheinartikeln mit festem Preis wird der Gutscheinwert automatisch übernommen.
. Schließen Sie den Auftrag wie gewohnt ab. +
→ Der Gutschein-Code wird auf dem Kassenbeleg ausgegeben.
. Händigen Sie dem Kunden den Kassenbeleg aus.
. Wenn Sie auch Gutscheinbelege drucken, händigen Sie dem Kunden auch den Gutscheinbeleg aus. +
*_Hinweis:_* Der Gutschein-Code steht auf dem Gutscheinbeleg und dem Kassenbeleg. Daher sollten Kunden beide Belege mitnehmen, damit niemand sonst den Gutschein einlösen kann.

[.instruction]
Verkaufsgutschein verkaufen und vorhandenen Gutschein-Code eingeben:

. Legen Sie den Gutscheinartikel mit dem gewünschten Gutscheinwert in den POS-Warenkorb.
. Wählen Sie die Menge 1. +
**__Tipp:__** Wenn Sie mehr als einen Gutschein als Menge wählen, werden die Gutschein-Codes automatisch generiert. +
→ Das Fenster **Gutschein wählen** wird angezeigt.
. Geben Sie in das Feld **Gutschein-Code** den Code ein.
. Tippen Sie auf **Vorhandenen**. +
→ Der Gutscheinwert wird im System ermittelt und übernommen.
. Schließen Sie den Auftrag wie gewohnt ab. +
→ Der Gutschein-Code wird auf dem Kassenbeleg ausgegeben.
. Händigen Sie dem Kunden den Kassenbeleg aus.
. Wenn Sie auch Gutscheinbelege drucken, händigen Sie dem Kunden auch den Gutscheinbeleg aus. +
*_Hinweis:_* Der Gutschein-Code steht auf dem Gutscheinbeleg und dem Kassenbeleg. Daher sollten Kunden beide Belege mitnehmen, damit niemand sonst den Gutschein einlösen kann.
. Dokumentieren Sie, welchen Gutschein-Code Sie verkauft haben. +
**__Hinweis:__** Jeder Gutschein-Code darf nur einmal verkauft werden, da der Betrag nur einmal eingelöst werden kann.

[.instruction]
Verkaufsgutschein verkaufen und Gutschein-Code im System speichern:

. Legen Sie den Gutscheinartikel mit dem gewünschten Gutscheinwert in den POS-Warenkorb.
. Wählen Sie die Menge 1. +
**__Tipp:__** Wenn Sie mehr als einen Gutschein als Menge wählen, werden automatisch Gutschein-Codes generiert. +
→ Das Fenster **Gutschein wählen** wird angezeigt.
. Geben Sie in das Feld **Gutschein-Code** den Code ein.
. Tippen Sie auf **Generieren**. +
→ Das Fenster **Gutscheinwert eingeben** wird angezeigt.
. Geben Sie den Wert des Gutscheins ein.
. Schließen Sie den Auftrag wie gewohnt ab. +
→ Der Gutschein-Code wird auf dem Kassenbeleg ausgegeben.
. Händigen Sie dem Kunden den Kassenbeleg aus.
. Wenn Sie auch Gutscheinbelege drucken, händigen Sie dem Kunden auch den Gutscheinbeleg aus. +
*_Hinweis:_* Der Gutschein-Code steht auf dem Gutscheinbeleg und dem Kassenbeleg. Daher sollten Kunden beide Belege mitnehmen, damit niemand sonst den Gutschein einlösen kann.
. Dokumentieren Sie, welchen Gutschein-Code Sie verkauft haben. +
**__Hinweis:__** Jeder Gutschein-Code darf nur einmal verkauft werden, da der Betrag nur einmal eingelöst werden kann.

[#160]
=== Verkaufsgutschein einlösen

Jeder Verkaufsgutschein hat einen einzigartigen Gutschein-Code. Diesen Gutschein-Code geben Sie während des Kassiervorgangs ein, um den Gutschein auf den Einkauf des Kunden anzuwenden. Damit Ihre Kunden einen Gutschein-Code einlösen können, muss dieser Gutschein-Code zu dem Zeitpunkt, in dem eine Kundin den Gutschein einlösen möchte, im plentymarkets System gespeichert sein.

[.instruction]
Verkaufsgutschein einlösen:

. Legen Sie die Artikel, die der Kunde kaufen möchten, in den POS-Warenkorb.
. Tippen Sie unten im POS-Warenkorb auf den grün hinterlegten Pfeil nach rechts. +
→ Eine Zusammenfassung des Auftrags und die verfügbaren Zahlungsmethoden werden angezeigt.
. Tippen Sie auf **Gutschein / Rabatt**.
. Geben Sie in das Feld **Gutscheincode/Rabatt** den Gutscheincode ein.
. Tippen Sie auf **Gutschein**. +
→ Die Gutscheinsumme wird von der Auftragssumme abgezogen. +
→ Die Restsumme, die der Kunde noch bezahlen muss, wird eingeblendet.
. Tippen Sie auf **Zurück**.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter.
. Wenn Sie mit Gutscheinbelegen arbeiten und der Gutschein nicht vollständig eingelöst wird, wird ein Gutscheinbeleg erstellt. Händigen Sie dem Kunden dann auch den Gutscheinbeleg aus. +
*_Tipp:_* Ob der Gutscheinbeleg automatisch gedruckt wird, hängt von den Kasseneinstellungen ab.

[#90]
== Optionale Kassiervorgänge

[#135]
=== Bestandskunde wählen

Standardmäßig wird für Kassiervorgänge der Standardkunde verwendet, der für die Kasse gespeichert wurde. Während des Kassierens haben Sie jedoch auch die Möglichkeit, einen anderen in plentymarkets gespeicherten Kundendatensatz zu wählen. Nachdem Sie den Kassiervorgang abgeschlossen haben, wird für den nächsten POS-Auftrag automatisch wieder der Standardkunde voreingestellt.

Gehen Sie wie unten beschrieben vor, um einen Bestandskunden zu wählen. Eine Suche ist anhand der folgenden Kundeninformationen möglich:

* **Kontakt-ID** = Kontakt-ID des Kunden
* **Kundendaten** = Vorname, Nachname, Firma, Kontaktperson, eBay-Name, Zusatzname, Straße, PLZ, Ort, E-Mail-Adresse, Kundennummer, Externe Kunden-ID, Such-Tags, PostIdent
* **PLZ** = Postleitzahl des Kunden

[.instruction]
Bestandskunde wählen:

. Tippen Sie im POS-Warenkorb unten auf das Kundensymbol. +
→ Die Daten des Standardkunden werden angezeigt.
. Tippen Sie auf die **Lupe**. +
→ Die Ansicht **Kundensuche** wird geöffnet.
. Geben Sie die Kundendaten ein, die Ihnen bekannt sind, um den Kundendatensatz zu suchen.
. Tippen Sie auf **Suchen**. +
→ Die Suchergebnisse werden aufgelistet.
. Tippen Sie auf einen Kundendatensatz. +
→ Die für den Kunden gespeicherten Adressen werden aufgelistet.
. Tippen Sie auf eine Adresse. Wenn für den Kundendatensatz nur eine Adresse gespeichert ist, ist diese Adresse bereits gewählt.
. Tippen Sie auf **Adresse verwenden**. +
→ Der Kundendatensatz wird gewählt.
. Wenn sich Artikel im POS-Warenkorb befinden, erfolgt die Abfrage **Preise aktualisieren?**. Wenn Sie **Ja** wählen, werden Rabatte, die für die Kundenklasse des gewählten Kunden gelten, auf alle Artikel des Auftrags angewendet. +
→ Die Kundendaten werden übernommen. +
**__Tipp:__** Über das Symbol **Zurücksetzen** können Sie den Standardkunden wiederherstellen.
. Tippen Sie rechts oben auf das **X** oder neben das Fenster, um zurück in den POS-Warenkorb zu springen. +
→ Der gewählte Kunde wird im POS-Warenkorb angezeigt.
. Bearbeiten Sie den Auftrag wie gewohnt weiter. +
→ Nachdem Sie den POS-Auftrag abgeschlossen haben, wird wieder der Standardkunde eingestellt.

[TIP]
.Kassenbeleg per E-Mail an Kunden senden
====
Über eine <<omni-channel/pos/pos-einrichten#70, Ereignisaktion>> kann der Beleg  als Anhang per E-Mail an den Kunden gesendet werden, sobald ein Beleg generiert wird. Bei POS-Aufträgen, die Sie im Offline-Modus abschließen, wird der Beleg jedoch erst versendet, wenn die POS-Aufträge hochgeladen werden.
====

[#100]
=== Notiz zum Auftrag hinzufügen

Um zusätzliche Informationen am Auftrag zu hinterlegen, speichern Sie eine Notiz, bevor Sie den Auftrag abschließen. Notizen werden mit dem Auftrag in das plentymarkets Backend importiert.

[.instruction]
Notiz zum Auftrag hinzufügen:

. Tippen Sie im POS-Warenkorb auf **Notiz**. +
→ Eine Liste der bereits am Auftrag gespeicherten Notizen wird angezeigt.
. Tippen Sie auf **Notiz hinzufügen**. +
→ Das Fenster **Notiz hinzufügen** wird angezeigt.
. Geben Sie den Notiztext ein.
. Tippen Sie auf das Häkchen, um die Notiz am Auftrag zu speichern. +
→ Die Notiz wird in der Liste der Notizen angezeigt und mit dem Auftrag in plentymarkets importiert.
. Tippen Sie auf das **X**, um die Ansicht zu schließen und zurück in die Warenkorbanzeige zu gelangen.

[#110]
=== Kassiervorgang unterbrechen

Wenn sich ein Kassiervorgang verzögert, Sie aber schon Artikel in den POS-Warenkorb gelegt haben, können Sie den aktuellen Stand des Warenkorbs speichern, indem Sie den Bon parken. Auch mehrere Bons können so zwischengespeichert werden.

[#120]
==== Bon parken

Gehen Sie wie unten beschrieben vor, um einen Bon zu parken.

[.instruction]
Bon parken:

. Tippen Sie im POS-Warenkorb oben rechts auf die vertikale Ellipse. +
→ Weitere Optionen werden eingeblendet.
. Tippen Sie auf **Bon parken**. +
→ Das Fenster **Bon parken** wird angezeigt.
. Tippen Sie auf **Ja**. +
→ Der Bon wird gespeichert und ein neuer POS-Warenkorb angezeigt.

[#130]
==== Geparkten Bon laden

Gehen Sie wie unten beschrieben vor, um einen geparkten Bon zu laden und den Kassiervorgang abzuschließen.

[.instruction]
Geparkten Bon laden:

. Tippen Sie im POS-Warenkorb oben rechts auf die vertikale Ellipse. +
→ Weitere Optionen werden eingeblendet.
. Tippen Sie auf **Bon laden**. +
→ Eine Liste der geparkten Bons wird angezeigt.
. Tippen Sie auf den Bon, den Sie laden möchten. +
→ Die geparkten Artikel dieses Bons werden im POS-Warenkorb angezeigt.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter.

[#140]
=== Auftragsposition bearbeiten

//  Diese Einstellungen müssen noch in Einzelkapitel unterteilt und einzeln beschrieben werden.
Sie können Artikel im POS-Warenkorb weiter bearbeiten. Änderungen, die Sie über diese Funktion vornehmen, wirken sich grundsätzlich nur auf diesen Auftrag aus, nicht auf den Datensatz des Artikels im System.

[.instruction]
Auftragspositionen bearbeiten:

. Tippen Sie auf die Auftragsposition im POS-Warenkorb. +
→ Weitere Optionen werden eingeblendet.
. Tippen Sie auf die gewünschte Einstellung. Beachten Sie <<tabelle-POS-kassenbenutzer-auftragspositionen-bearbeiten>>.

[[tabelle-POS-kassenbenutzer-auftragspositionen-bearbeiten]]
.Auftragspositionen bearbeiten
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Menge ändern**
|Öffnet das Fenster **Menge ändern**. Neue Menge eingeben und auf **OK** tippen, um die Menge des Artikels im Warenkorb anzupassen.

|**Artikelposition umbenennen**
|Neuen Namen eingeben und auf **OK** tippen, um den Namen der Auftragsposition zu ändern. Der Name wird nur in diesem Auftrag geändert. Der Name des Artikels im System bleibt unverändert.

|**Einzelpreis ändern**
|Neuen Preis eingeben und auf **OK** tippen, um bei Auftragspositionen mit einer Menge größer 1 den Preis nur einer dieser Positionen zu ändern. Der Preis wird nur in diesem Auftrag geändert. Der Preis des Artikels im System bleibt unverändert.

|**Gesamtpreis ändern**
|Neuen Preis eingeben und auf **OK** tippen, um den Gesamtpreis der gesamten Menge der Auftragsposition zu ändern. Der Preis wird nur in diesem Auftrag geändert. Der Preis des Artikels im System bleibt unverändert.

|**Artikelpreis zurücksetzen**
|Setzt über **Einzelpreis ändern** oder **Gesamtpreis ändern** geänderte Preise auf den ursprünglichen Preis zurück.

|**Rabatt hinzufügen**
|Rabatt in Prozent eingeben und auf **OK** tippen, um einen Rabatt auf die Auftragsposition zu gewähren. Der Preis wird nur in diesem Auftrag geändert. Der Preis des Artikels im System bleibt unverändert. +
**__Hinweis:__** Wenn Rabatte auf einzelne Auftragspositionen hinzugefügt wurden, kann kein Rabatt auf den gesamten POS-Warenkorb eingegeben werden.

|**Rabatt entfernen**
|Setzt über **Rabatt hinzufügen** rabattierte Preise auf den ursprünglichen Preis zurück.

|**Löschen**
|Löscht den Artikel aus dem POS-Warenkorb.
|====


[#170]
=== Rabatt auf gesamten Auftrag anwenden

Statt einzelne Auftragspositionen zu rabattieren, haben Sie auch die Möglichkeit, einen Rabatt auf alle Artikel im POS-Warenkorb anzuwenden, nachdem Sie alle Artikel des Kunden in den POS-Warenkorb gelegt haben. Ein Rabatt auf den gesamten POS-Warenkorb ist allerdings nur möglich, wenn nicht schon ein Rabatt auf einen oder mehrere Artikel im POS-Warenkorb angewendet wurde. Gehen Sie wie hier beschrieben vor, um einen Rabatt auf den gesamten POS-Warenkorb anzuwenden.

[.instruction]
Rabatt auf gesamten Warenkorb anwenden:

. Tippen Sie unten im POS-Warenkorb auf den grün hinterlegten Pfeil nach rechts. +
→ Eine Zusammenfassung des Auftrags und die verfügbaren Zahlungsmethoden werden angezeigt.
. Tippen Sie auf **Gutschein / Rabatt**.
. Geben Sie in das Feld **Gutscheincode/Rabatt** den Rabatt in Prozent ein.
. Tippen Sie auf **Rabatt**. +
→ Die Rabattsumme wird von der Auftragssumme abgezogen und die neue Auftragssumme eingeblendet.
. Tippen Sie auf **Zurück**.
. Bearbeiten Sie den POS-Auftrag wie gewohnt weiter.

[#173]
== Auftrag stornieren

Über den POS-Menüpunkt **Auftrag stornieren** stornieren Sie abgeschlossene POS-Aufträge, die seit dem letzten Tagesabschluss über die Kasse erstellt wurden. Gehen Sie wie unten beschrieben vor, um einen POS-Auftrag zu stornieren.

[WARNING]
.Stornierung von POS-Aufträgen nur über die Kasse
====
Wenn Sie POS-Aufträge über das plentymarkets Backend stornieren, kommt es zu Fehlern bei den Kassendaten (Tagesabschlüsse, Barbestand etc.). Stornieren Sie POS-Aufträge daher nur über die Kasse und nicht im plentymarkets Backend.
====

[.instruction]
Auftrag stornieren:

. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**.
. Tippen Sie auf **Auftrag stornieren**. +
**__Tipp:__** Der Menüpunkt ist nur wählbar, wenn Sie berechtigt sind, Aufträge zu stornieren. +
→ Nicht stornierte Aufträge, die seit dem letzten Tagesabschluss über die Kasse erstellt wurden, werden aufgelistet.
. Tippen Sie auf das Icon **Stornieren**. +
→ Alternativ tippen Sie auf den Auftrag, um die Detailansicht zu öffnen, und dort auf das Icon **Stornieren**.
. Bestätigen Sie die Stornierung. +
. **__Je nach Kartenterminal:__** Wählen Sie, ob der stornierte Betrag bar oder über das Terminal zurückerstattet werden soll.
. Zahlen Sie den stornierten Betrag bar aus oder wickeln Sie die Rückzahlung über das Kassenterminal/den Payment-Provider ab. +
→ Der Auftrag wird storniert.

[#175]
== Retoure buchen

Über eine Kasse gebuchte Retouren werden im plentymarkets Backend als Retoure ohne Hauptauftrag erstellt. Gehen Sie wie unten beschrieben vor, um eine Retoure zu buchen.

[.instruction]
Retoure buchen:

. Tippen Sie im Menü **POS** auf **Retoure**. +
→ Die Retourenansicht wird geöffnet.
. Fügen Sie die Retourenartikel per Scan oder über die Artikelsuche hinzu. +
→ Wenn der gezahlte Preis vom aktuellen Preis des Artikels abweicht, <<omni-channel/pos/pos-kassenbenutzer#140, passen Sie den Preis des Artikels an>>.
. Fügen Sie optional eine Notiz zur Retoure hinzu:
  .. Tippen Sie auf die Pinnwandnadel. +
  → Eine Liste der bereits an der Retoure gespeicherten Notizen wird angezeigt.
  .. Tippen Sie auf **Notiz hinzufügen**. +
  → Das Fenster **Notiz hinzufügen** wird angezeigt.
  .. Geben Sie den Notiztext ein.
  .. Tippen Sie auf das Häkchen, um die Notiz an der Retoure zu speichern. +
  → Die Notiz wird gespeichert und mit der Retoure in plentymarkets importiert.
  .. Tippen Sie auf das Listensymbol, um zurück in die Retourenansicht zu wechseln.
. Wenn alle Retourenartikel erfasst wurden, tippen Sie auf das grün hinterlegte Häkchen. +
→ Die Gesamtsumme der Retoure wird angezeigt.
. Tippen Sie auf **Retoure abschließen**. +
→ Im plentymarkets Backend wird eine Retoure ohne Hauptauftrag erstellt.

[#180]
== Einlagen und Entnahmen buchen

Auch Bargeldbewegungen aus und in die Kasse, die nicht durch das Buchen von Aufträgen entstehen, müssen erfasst werden. Wird Bargeld in die Kasse gelegt, zum Beispiel um ausreichend Wechselgeld vorzuhalten, handelt es sich um eine Einlage. Wenn Bargeld aus der Kasse entnommen wird, spricht man von einer Entnahme. Bargeld wird zum Beispiel aus der Kasse genommen, um es auf der Bank einzuzahlen. Gehen Sie wie unten beschrieben vor, um Einlagen und Entnahmen zu buchen.

[#190]
=== Einlage buchen

Gehen Sie wie unten beschrieben vor, um eine Einlage zu buchen.

[.instruction]
Einlage buchen:

. Tippen Sie in der Menüleiste auf das *Menüsymbol*.
. Tippen Sie auf *POS*. +
→ Das *POS-Menü* wird eingeblendet.
. Tippen Sie auf *Einlagen und Entnahmen*. +
→ Das Menü *Einlage/Entnahme* wird eingeblendet.
. Wählen Sie im Bereich *Grund* die Art des Einlagevorfalls aus der Dropdown-Liste.
. *_Optional:_* Geben Sie in das Feld *Zusätzliche Angaben* weitere Informationen zu der Einlage ein.
. Tippen Sie den Betrag ein, der in die Kasse eingezahlt wird.
. Tippen Sie auf *Einlage*, um die Einlage zu speichern. +
→ Der Ist-Kassenbestand wird aktualisiert. +
→ Ein Beleg für die Einlage wird gedruckt. +
→ Der Beleg wird in plentymarkets importiert und im Menü *Aufträge » Dokumentenarchiv* gespeichert.

[#200]
=== Entnahme buchen

Gehen Sie wie unten beschrieben vor, um eine Entnahme zu buchen.

[.instruction]
Entnahme buchen:

. Tippen Sie in der Menüleiste auf das *Menüsymbol*.
. Tippen Sie auf *POS*. +
→ Das *POS-Menü* wird eingeblendet.
. Tippen Sie auf *Einlagen und Entnahmen*. +
→ Das Menü *Einlage/Entnahme* wird eingeblendet.
. Wählen Sie im Bereich *Grund* die Art des Entnahmevorfalls aus der Dropdown-Liste.
. *_Optional:_* Geben Sie in das Feld *Zusätzliche Angaben* weitere Informationen zu der Entnahme ein.
. Tippen Sie den Betrag ein, der aus der Kasse genommen wird.
. Tippen Sie auf *Entnahme*, um die Entnahme zu speichern. +
→ Der Ist-Kassenbestand wird aktualisiert. +
→ Ein Beleg für die Entnahme wird gedruckt. +
→ Der Beleg wird in plentymarkets importiert und im Menü *Aufträge » Dokumentenarchiv* gespeichert.

[#210]
== Berichte erstellen

In plentymarkets POS können Sie Zwischenberichte und Tagesberichte erstellen.

[#220]
=== Zwischenbericht erstellen

Mit Zwischenberichten informieren Sie sich im laufenden Betrieb über die Umsätze, die seit dem letzten Tagesabschluss über die Kasse generiert wurden. Sie können beliebig viele Zwischenberichte erstellen. Zwischenberichte werden nicht in plentymarkets importiert, die Erstellung also nicht langfristig dokumentiert. Zwischenberichte werden auch als X-Berichte bezeichnet.

Zwischenberichte enthalten folgende Informationen:

* Barbestand: Anfangsbarbestand, Entnahmen, Einlagen, Soll-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retournierte Artikel: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufsgutscheine: Anzahl und Summe verkaufter Gutscheine
* Benutzer: Umsatz, Stornierungen und Retouren pro Benutzer

[.instruction]
Zwischenbericht erstellen:

. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**. +
→ Das **POS-Menü** wird eingeblendet.
. Tippen Sie auf **Zwischenbericht**. +
**__Hinweis:__** Wenn der Menüpunkt ausgegraut ist, benötigen Sie zusätzliche <<omni-channel/pos/pos-einrichten#170, Berechtigungen>>, um Zwischenberichte zu erstellen. +
→ Der Zwischenbericht wird gedruckt.

[#230]
=== Tagesabschluss erstellen

Ein Tagesabschlussbericht dokumentiert die seit dem letzten Tagesabschlussbericht getätigten Umsätze. Durch das Drucken eines Tagesabschlussberichts werden die Tagesumsätze außerdem auf 0 zurückgesetzt. Die Tagesabschlussberichte werden mit einer fortlaufenden Nummer versehen und in plentymarkets gespeichert. Tagesabschlussberichte dienen als Nachweis gegenüber dem Finanzamt. Tagesabschlussberichte werden auch als Z-Berichte bezeichnet.

Tagesabschlussberichte enthalten folgende Informationen:

* Barbestand: Entnahmen, Einlagen, Soll-Kassenbestand, Ist-Kassenbestand
* Umsatz: seit letztem Tagesabschluss (Summe) und seit Inbetriebnahme der Kasse (Grand Total)
* Steuerbericht: Steuersatz, Steuersumme und Nettoumsatz
* Zahlungsarten: Aufschlüsselung des Umsatzes nach Zahlungsart
* Retournierte Artikel: Anzahl und Summe
* Stornierungen: Anzahl und Summe
* Rabattierte Artikel: Anzahl und Summe
* Verkaufte Gutscheine: Anzahl und Summe
* Benutzer: Umsatz, Stornierungen und Retouren pro Benutzer

[.instruction]
Tagesabschluss erstellen:

. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**. +
→ Das **POS-Menü** wird eingeblendet.
. Tippen Sie auf **Tagesabschluss**. +
→ Der Soll-Kassenbestand wird eingeblendet.
. Prüfen Sie den tatsächlichen Kassenbestand und geben Sie diesen Ist-Bestand ein.
. Tippen Sie auf **Tagesabschluss erstellen**. +
**__Hinweis:__** Wenn der Menüpunkt ausgegraut ist, benötigen Sie zusätzliche <<omni-channel/pos/pos-einrichten#170, Berechtigungen>>, um Tagesberichte zu erstellen. +
→ Der Tagesabschluss wird in plentymarkets importiert und im Menü **Aufträge » Dokumentenarchiv** gespeichert. +
→ Der Tagesabschluss wird gedruckt. +
→ Die Tagesumsätze werden auf 0 zurückgesetzt. +
→ Für Kassen mit Standort Österreich wird ein Nullbeleg erstellt und im Kassenjournal gespeichert.

[TIP]
.Tagesabschluss für Kartenzahlungen
====
Wenn Sie ein Karten-Terminal an plentymarkets POS angebunden haben, ist es bei einigen Terminals möglich, gleichzeitig mit dem plentymarkets POS Tagesabschluss einen Tagesabschluss für die Umsätze des Karten-Terminals anzustoßen. Beantworten Sie die angezeigte Frage **Gleichzeitig Tagesabschluss für Terminal erstellen?** mit **Ja**, um die Kartenumsätze an den Netzbetreiber zu übermitteln und auf 0 zurückzusetzen.
====

=== Kassensturzbericht erstellen

Ein Kassensturz dient dazu, den Kassenbestand zu dokumentieren, also den Bargeldbestand in Form von Geldscheinen und Münzen zu einem bestimmten Zeitpunkt. Dazu wird der Barbestand einer Kasse physisch gezählt. Aus dem Ergebnis der Zählung wird ein Zählprotokoll erstellt. Aktuell ist systemseitig die Eingabe einer Zählung von Münzen und Scheinen in den Währungen Euro, Schweizer Franken und Britische Pfund möglich.

==== Kassensturzergebnis erfassen

Wenn Sie einen Kassensturz durchführen und das Ergebnis über plentymarkets POS erfassen, können Sie entweder die Anzahl der einzelnen Münzen und Geldscheine eingeben oder das Ergebnis der Zählung als Gesamtbetrag eingeben. Gehen Sie wie unten beschrieben vor, um das Ergebnis eines Kassensturzes zu dokumentieren.

[.instruction]
Kassensturzergebnis erfassen:

. Melden Sie sich bei der plentymarkets App an.
. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**. +
→ Das POS-Menü wird angezeigt.
. Tippen Sie auf **Kassensturz**. +
→ Das Menü **Kassensturz** wird angezeigt. Die Stückelung **1 Cent** ist automatisch ausgewählt.
. Geben Sie über das Tastenfeld die Menge der vorhandenen 1-Cent-Stücke ein.
. Tippen Sie auf den grünen Return-Pfeil, um zur nächsten Stückelung zu springen.
. Wiederholen Sie den Vorgang, bis Sie die Menge für alle vorhandenen Münzen und Geldscheine eingegeben haben. +
**__Alternative:__** Um statt Stückelung und Menge den Gesamtbetrag einzugeben, tippen Sie in das Feld **Überschreiben** und geben Sie den gezählten Betrag ein.
. Tippen Sie auf **Kassensturz speichern**. +
→ Ein Kassensturzbericht wird erstellt und im Menü **Aufträge » Dokumentenarchiv** gespeichert.
. **__Optional:__** Tippen Sie auf **Kassensturzbericht drucken**, um den Bericht zu drucken.
. Wenn der Ist-Kassenbestand vom Soll-Kassenbestand abweicht, gehen Sie wie unten beschrieben vor, um die Differenz zu buchen.

==== Differenz aus Kassensturz buchen

Wenn nach der Zählung des Barbestands der Ist-Kassenbestand vom Soll-Kassenbestand abweicht, muss die Differenz entweder ausgeglichen oder gebucht werden. Wenn Sie die Differenz buchen, wird der Ist-Kassenbestand als neuer Soll-Kassenbestand übernommen. Gleichzeitig wird abhängig vom Vorzeichen des Differenzbetrags entweder eine Einlage oder eine Entnahme gebucht:

* Ist der Ist-Kassenbestand größer als der Soll-Kassenbestand, wird eine Einlage gebucht.
* Ist ein Minusbetrag in der Kasse, wird eine Entnahme gebucht.

Wenn Sie die Differenz eines Kassensturzes buchen, wird als Grund automatisch **Differenz aus Kassensturz** gespeichert.

[.instruction]
Differenz buchen:

. Tippen Sie nach dem Speichern des Kassensturzes auf **Differenz buchen**, um den Ist-Kassenbestand als neuen Soll-Kassenbestand zu speichern. +
→ Für den Differenzbetrag wird eine Einlage bzw. Entnahme mit dem Grund **Differenz aus Kassensturz** erstellt und im Menü **Aufträge » Dokumentenarchiv » Kassenbeleg** gespeichert. +
→ Der Ist-Kassenbestand wird als neuer Soll-Kassenbestand gespeichert.

[#280]
== Besonderheiten in Österreich

Österreichische Kassen sind mit einer Signatureinheit ausgestattet. Daraus ergeben sich einige Besonderheiten, die im Folgenden näher beschrieben werden.

[#260]
=== Monatsbeleg erstellen (Österreich)

Monatsbelege sind signierte Kontrollbelege mit einem Betrag von Null (0,00) Euro. Laut RKSV muss am Ende jedes Monats ein Monatsbeleg erstellt werden. Der Monatsbeleg für den Monat Dezember dient gleichzeitig als Jahresbeleg.

[.instruction]
Monatsbeleg erstellen (Österreich):

. Melden Sie sich bei der plentymarkets App an.
. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**. +
→ Das POS-Menü wird angezeigt.
. Tippen Sie auf **Monatsbeleg (AT)**. +
→ Der Monatsbeleg wird gedruckt. +
→ Der Monatsbeleg wird in plentymarkets importiert und im Menü **Aufträge » Dokumentenarchiv** gespeichert.

=== Bei Ausfall der Signatureinheit kassieren (Österreich)

Der Gesetzgeber gibt vor, wie Sie vorgehen sollen, falls die Signatureinheit der Registrierkasse ausfällt.

* Notieren Sie sich den Zeitpunkt des Ausfalls.
* Weichen Sie wenn möglich auf eine Registrierkasse mit funktionierender Signatureinheit aus.
* Wenn keine andere Kasse verfügbar ist, können Sie trotz ausgefallener Signatureinheit weiter kassieren. Alle Belege werden dann mit dem Hinweis *Sicherheitseinrichtung ausgefallen* versehen.
* Sobald die Signatureinheit wieder funktioniert, wird in plentymarkets POS automatisch ein Sammelbeleg erstellt und gedruckt.

Hierbei handelt es sich lediglich um Empfehlungen zur Einhaltung der RKSV. Erkundigen Sie sich außerdem bei Ihrer Vorgesetzten, wie Sie bei einem Ausfall genau vorgehen sollen.

[#270]
=== Kontrollbeleg auf Verlangen der Finanzpolizei erstellen (Österreich)

Bei einer Kassenrückschau durch die Finanzpolizei muss auf Verlangen ein Kontrollbeleg mit dem Betrag Null erstellt werden. Dieser Kontrollbeleg ermöglicht es dem Prüfer, die Gültigkeit der Signatur mit einer Prüf-App direkt vor Ort in Ihrem Laden zu überprüfen. Sie benötigen keine zusätzlichen Benutzerrechte, um den Kontrollbeleg zu erstellen.

[.instruction]
Kontrollbeleg auf Verlangen erstellen:

. Melden Sie sich bei der plentymarkets App an.
. Tippen Sie in der Menüleiste auf das **Menüsymbol**.
. Tippen Sie auf **POS**. +
→ Das POS-Menü wird angezeigt.
. Tippen Sie auf **Kontrollbeleg**. +
→ Der Kontrollbeleg wird gedruckt. +
→ Der Kontrollbeleg wird in plentymarkets importiert und im Menü **Aufträge » Dokumentenarchiv** gespeichert. +
**__Hinweis:__** Der Prüfer darf den Kontrollbeleg als Beweismittel einbehalten.

// Next: [#300]
// [#150] ist im Moment frei
