= Affiliate
:lang: de
include::{includedir}/_header.adoc[]
:position: 50

**Einstellungen » Mandant (Shop) » Standard » Affiliate**

toc::[]
== Affiliate-Marketing

Affiliate-Marketing ist eine Form der provisionsbasierten Verkaufsvermittlung. Für diese Marketingkanäle gibt es spezialisierte Unternehmen, die sowohl die Verlinkung Ihrer Artikel auf Partner-Webseiten, als auch die Provisionsabwicklung organisieren. Sie finden in diesem Bereich die Informationen über entsprechende Schnittstellen. Diese Affiliate-Marketing-Systeme unterstützen damit die Vermarktung Ihrer Produkte bei überschaubaren Kosten: Sie zahlen nur bei messbaren Resultaten bzw. bei tatsächlich generierten Verkäufen.

Die gängigsten Modelle der Partnervergütung sind:

* Pay-per-Click, d.h. Zahlung pro Klick
* Pay-per-Lead, d.h. Zahlung pro Interessent/Download/Abonnent, etc.
* Pay-per-Sale, d.h. Zahlung pro Verkauf

Affiliate-Partner schaffen somit die Basis für eine Form des kooperativen Marketings bzw. Vertriebs im Internet. Anstatt einzelne Banner auf Werbeplattformen zu platzieren, können Sie mit Hilfe eines Affiliate-Anbieters virtuelle Netzwerke aufbauen und Ihre Produkte auf anderen Websites mit anbieten und verkaufen.

== Wichtige Begriffe

Um das Konzept von Affiliates zu verdeutlichen, haben wir einige Begriffsdefinitionen für Sie zusammengetragen:

* **Advertiser/Merchant**: Webshopbetreiber, der sich bei Affiliate-Netzwerk anmeldet
* **Publisher**: Werbeträger, der Bannerwerbung bzw. Verlinkung vornimmt
* **Tracking**: Aufzeichnung der URL eines Besuchers, der das Angebot des Advertisers anklickt bzw. kauft

== Affiliates in plentymarkets

Die folgenden Affiliate-Partner können Sie in plentymarkets einrichten und nutzen.

* <<marketing/affiliate/affilinet#, **affilinet**  >>
* <<marketing/affiliate/belboon#, **belboon**  >>
* <<marketing/affiliate/criteo#, **Criteo**  >>
* <<marketing/affiliate/redpeppix#, **redpeppix.**  >>
* <<marketing/affiliate/trade-doubler#, **Trade Doubler**  >>
* <<marketing/affiliate/zanox#, **zanox**  >>

