= Lock store
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Store, Client, Lock store
:position: 30

The **Lock store now** setting allows you to set your client (store) invisible during initial set-up. Visitors will see a service note when they try to access a locked online store. You can also lock the store in order to carry out substantial changes to your store at a later point and redirect your visitors to a page with a service note in the meantime. Don't forget to unlock your store after you have finished making changes. Otherwise, you will not be able to receive orders.

[TIP]
.Tip
====
If you need to make substantial changes, create a copy of your design and edit the copy. This allows you to return to the original design at any time if needed. Open the online store using the standard URL in another browser after each maintenance. Use this chance to check whether all your changes have been carried out correctly.
====

toc::[]
== Locking an online store

Proceed as described below to lock the online store.

[.instruction]
Locking an online store:

. Go to **Settings » Client (store) » Standard » Online store » Lock store**.
. Click on **Lock store now**. +
→ The online store is locked and can be accessed via direct product links or the URL suffix **/index.php** only. +
**__Tip:__** When you lock the default client (store), all other clients of the store also will be locked.

[IMPORTANT]
.Locked online stores cannot be accessed via REST API
====
When you lock an online store, you can no longer communicate with the plentymarkets system via REST API.
====

== Unlocking an online store

Proceed as described below to unlock the online store.

[.instruction]
Unlocking an online store:

. Go to **Settings » Client (store) » Standard » Online store » Lock store**.
. Click on **Unlock store now**. +
→ The online store is unlocked and can be accessed by customers.

