= Credit notes
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Credit note, Generating credit notes, Adjustment form, Generating adjustment forms
:position: 20

In plentymarkets, you can generate credit notes as PDF files, for example if you want to print them or send them to your customers as an email attachment. +
Use credit notes to grant customers additional discounts for orders that have already been paid or if refunds have to be arranged due to returned items.

[NOTE]
.Default settings for credit notes
====
Carry out the desired default settings once in the menu **System » Aufträge » Einstellungen** and save them before generating credit notes. This is required for the correct application of your desired default settings for the **Standard status for credit notes** and the inclusion of shipping costs in credit notes. For more information on carrying out standard settings for orders, refer to the <<orders/basic-settings#, Basic settings>> page of the manual.
====

[#200]
== Setting up a document template for credit notes

Before generating credit notes, you have to set up a document template. This is done in the menu **System » Client » Select client » Locations » Select location » Documents**. +
For further information and instructions on setting up the document template, refer to the <<orders/order-documents#, Order documents>> page of the manual.

[#300]
== Generating a single credit note

You can manually generate a single credit note in the corresponding credit note order, if necessary. For further information and instructions on generating credit note orders, refer to the <<orders/managing-orders#530, Generating a credit note>> chapter of the manual.

[.instruction]
Generating a single credit note:

. Go to **Orders » Edit orders**. +
→ The order overview opens.
. Select the credit note order for which a credit note should be created by clicking on the **Order ID**.
. Open the **Receipts** tab. +
. In the **Create receipt** drop-down menu, select the document **Credit note**. +
. Carry out the settings according to <<table-credit-note-order-receipts-credit-note>>.
. **Save** the settings to generate the credit note. +
→ A **PDF file** containing the generated credit note opens.

[[table-credit-note-order-receipts-credit-note]]
.Options in the *Create receipt* menu
[cols="1,3"]
|====
|Setting |Explanation

|**Date**
|Select the date that is displayed on the credit note. The present date is set by default.

|**Number**
|The document number is assigned automatically. No entry is required in this field.

|**Change order status to status**
|Select a status that should be applied to the order after generating the credit note. Choose the option **No change** if a status change is not desired.

|**Comment**
|Enter a text that is displayed below the item list on the credit note. This step is optional.
|====

[#400]
== Generating multiple credit notes

If you wish to generate multiple credit notes at a time, use the search filter in the **Orders » Fulfilment** menu to determine the orders for which credit notes should be generated. In addition, a status change can take place after the credit notes have been generated.

[.instruction]
Generating multiple credit notes:

. Go to **Orders » Fulfilment » Create credit notes / adjustment forms**.
. Carry out the settings according to <<table-settings-fulfilment-credit-notes>>.
. Click on the **gear-wheel icon** to generate the credit notes. +
→ A **PDF file** containing the credit notes for the previously selected orders opens.

[[table-settings-fulfilment-credit-notes]]
.Options in the *Create credit notes / adjustment forms* menu
[cols="1,3"]
|====
|Setting |Explanation

|**Document type**
|Select whether the document type *Credit note* or *Adjustment form* should be generated.

|**Order status**
|From the list, select the status of the orders for which credit notes should be generated.

|**Owner**
|Select the owner responsible for the orders for which the credit notes should be generated. Select **ALL** if credit notes should be generated for all owners.

|**Location**
|Select a location for which the dunning letters should be generated.

|**Warehouse**
|Select one of the warehouses or **ALL**.

|**Payment method**
|Select a payment method or *ALL*.

|**Sorting**
|Determine how the generated credit notes should be sorted. The options **Credit note number**, **Order ID**, **Customer ID** and **Item ID** are available for different sorting methods.

|**Limit**
|Determine the maximum number of credit notes generated at a time. There is a maximum of *200* credit notes.

|**Change order status**
|Select a status that should be applied to the orders after generating the credit notes. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been handled.

|**Comment**
|Enter a text that is later displayed below the item list on all credit notes. This step is optional.
|====
