= Return slips
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Return slip, Generating return slips, Fulfilment, Order processing, Order documents, Return, Return delivery
:position: 90
:url: orders/order-documents/generating-return-slips
:id: S938BDY

In plentymarkets, you can generate return slips as PDF files, for example if you want to print them or send them to your customers as an email attachment. +
This way, customers can enclose the return slips to their shipments when returning or exchanging items.

[#200]
== Setting up a document template for return slips

Before generating return slips, you have to set up a document template. This is done in the menu **Setup » Client » Select client » Locations » Select location » Documents**. +
For further information and instructions on setting up the document template, refer to the <<orders/order-documents#, Order documents>> page of the manual.

[#300]
== Generating a single return slip

In some cases, it makes sense to manually generate return slip for particular orders. This is done in the order overview for original main orders and return orders alike.

[#400]
=== Generating a return slip in the original main order

In plentymarkets, you can manually generate a single return slip in the original main order, if necessary. The generated return slip then lists all items contained in the order. Use this method to add a blank return slip to every order shipped to your customers. For further information about this method, refer to the **<<orders/managing-orders#450, Creating a return slip>>** chapter of the manual.

[.instruction]
Generating a return slip in the original main order:

. Go to **Orders » Edit orders**. +
→ The order overview opens.
. Select the order for which a return slip should be created by clicking on the **Order ID**. +
. Open the **Receipts** tab. +
. In the **Create receipt** drop-down menu, select the document **Return slip**. +
. Carry out the settings according to <<table-orders-receipts-return-slip>>. +
. **Save** the settings to generate the return slip. +
→ A **PDF file** containing the generated return slip opens.

[[table-orders-receipts-return-slip]]
.Options in the *Create receipt* menu
[cols="1,3"]
|====
|Setting |Explanation

|**Date**
|Select the date of the return slip. The present date is set by default.

|**Number**
|The document number is assigned automatically. No entry is required in this field.

|**Change order status to status**
|Select a status that should be applied to the order after generating the return slip. Choose the option **No change** if a status change is not desired.

|**Comment**
|Enter a text that is displayed below the item list on the return slip. This step is optional.
|====

[#500]
=== Generating a return slip in the return order

If you want to provide your customers with access to a return slip for a specific order, e.g. in the My Account area of the online store, generate a return slip in the corresponding return order.

[.instruction]
Generating a return slip in the return order:

. Go to **Orders » Edit orders**. +
→ The order overview opens.
. Select the return order for which a return slip should be created by clicking on the **Order ID**. +
. Open the **Receipts** tab. +
. In the **Create receipt** drop-down menu, select the document **Return slip**. +
. Carry out the settings according to <<table-orders-receipts-return-slip>>. +
. **Save** the settings to generate the return slip. +
→ A **PDF file** containing the generated return slip opens.

[#600]
== Generating multiple return slips

If you wish to generate return slips for multiple orders at a time, use the search filter in the **Orders » Fulfilment** menu to determine the orders for which return slips should be generated. In addition, a status change can take place for the order after the return slips have been generated.

[.instruction]
Generating multiple return slips:

. Go to **Orders » Fulfilment » Generate return slips**.
. Carry out the settings according to <<table-settings-fulfilment-return-slip>>.
. Click on the **gear-wheel icon** to generate the return slips. +
→ A **PDF file** containing the return slips for the previously selected orders opens.

[[table-settings-fulfilment-return-slip]]
.Options in the *Generate return slips* menu
[cols="1,3"]
|====
|Setting |Explanation

|**Order status**
|From the list, select the status of the orders for which return slips should be generated.

|**Owner**
|Select the owner responsible for the orders for which the return slips should be generated. Select **ALL** if return slips should be generated for all owners.

|**Location**
|Select a location for which the return slips should be generated.

|**Warehouse**
|Select one of the warehouses or the option **ALL**.

|**Payment method**
|Select a payment method or *ALL*.

|**Sorting**
|Determine how the generated return slips should be sorted. The options **Order ID**, **Customer ID** and **Item ID** are available for different sorting methods.

|**Limit**
|Determine the maximum number of return slips generated at a time. There is a maximum of *200* return slips.

|**Change order status**
|Select a status that should be applied to the orders after generating the return slips. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been handled.

|**Comment**
|Enter a text that is displayed below the item list on all return slips. This step is optional.
|====
