= Neckermann.at einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Neckermann.at, Marktplatz
:description: Multi-Channel in plentymarkets: Richten Sie die Schnittstelle zum Marktplatz Neckermann Österreich in Ihrem plentymarkets System ein.
:position: 10

Neckermann Österreich bietet Ihnen die Möglichkeit, Ihre Produkte auf dem Marktplatz *neckermann.at* zu präsentieren. Sie erhalten auf dieser Handbuchseite detaillierte Informationen zur Vorgehensweise, um den Marktplatz Neckermann Österreich für Ihr plentymarkets System einzurichten. Beachten Sie diese Informationen, um eine möglichst reibungslose Anbindung zu gewährleisten.

[#100]
== Bei Neckermann.at registrieren

Wenn Sie Partner bei link:http://www.neckermann.at/[Neckermann Österreich^] werden möchten, wenden Sie sich bitte zunächst direkt an Neckermann.at.

.Ansprechpartner
[cols="1,3"]
|====
|Ansprechpartner |E-Mail-Adresse

|*René Riebenbauer* - Leitung Vertriebsplattform und Contentmanagement
|link:mailto:rene.riebenbauer@neckermann.at[rene.riebenbauer@neckermann.at^]
|====

[#200]
== Neckermann.at in plentymarkets einrichten

Nachdem Sie Neckermann-Partner geworden sind, verwenden Sie Ihre Zugangsdaten, um den Marktplatz in plentymarkets einzurichten. Sie können die Plattform Neckermann.at Enterprise
// als auch Neckermann.at Cross-Docking
an plentymarkets anbinden. Um Neckermann.at Enterprise in plentymarkets einzurichten, gehen Sie wie im Folgenden beschrieben vor.
// Richten Sie Neckermann.at Cross-Docking auf die gleiche Weise ein.

[.instruction]
Neckermann.at in plentymarkets einrichten:

.  Öffnen Sie das Menü *System » Märkte » Neckermann Österreich Enterprise*.
. Klappen Sie den Bereich *Grundeinstellungen* auf.
.  Nehmen Sie die Einstellungen gemäß <<grundeinstellungen-neckermann>> vor.
. *Speichern* Sie die Einstellungen.

[[grundeinstellungen-neckermann]]
.Grundeinstellungen des Marktplatzes Neckermann.at
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Schnittstellenmodus*
|Schnittstellenmodus wählen. +
*Testmodus EIN* = Wählen, wenn Einstellungen und Vorbereitungen an Schnittstelle und Artikeln getroffen werden. +
*Aktivmodus EIN* = Wählen, nachdem Sie sicher sind, dass alle Einstellungen korrekt vorgenommen wurden.

2+|Vertriebspartner-Information

|*Partner-ID*
|ID eingeben, wie von Neckermann erhalten.

|*Firmenname*
|Firmen- oder Webshop-Name eingeben.

|*Name, Vorname (Kontaktperson);  +
Telefonnummer (Kontaktperson); +
E-Mail-Adresse (Kontaktperson)*
|Name, Telefonnummer und E-Mail-Adresse der Kontaktperson eingeben.

2+|Artikeleinstellungen

|*Regelsteuersatz*
|*10 %* oder *20 %* wählen.

|*Ermäßigter Steuersatz*
|*7 %* oder *19 %* wählen.

|*Artikelname*
|Textfeld wählen, das als Artikelname an Neckermann übertragen wird.

|*Artikelname (maximale Länge)*
|*35 Zeichen* oder *65 Zeichen* wählen.

|*Artikelvorschautext*
|Textfeld wählen, das als Artikelvorschautext an Neckermann übertragen wird.

|*Artikelvorschautext (maximale Länge)*
|*30 Zeichen* oder *50 Zeichen* wählen.

|*Artikelkurztext*
|Textfeld wählen, das als Artikelkurztext an Neckermann übertragen wird.

|*Artikelbeschreibung*
|Textfeld wählen, das als Artikelbeschreibung an Neckermann übertragen wird.

|*Artikel ohne Markenzuordnung übertragen*
|*Nein* = Artikel werden standardmäßig mit Markenzuordnung übertragen. +
*Ja* = Artikel werden ohne Markenzuordnung übertragen.

|*Bildposition für das Energieetikett*
|Ziffer der Bildposition des Artikelbildes eingeben, wenn das Energieetikett als Artikelbild und nicht als Merkmal gespeichert wurde. Weitere Informationen zum Energieetikett finden Sie im Kapitel <<Energieeffizienz angeben, Energieeffizienz angeben>>.

|*Cross-Selling übertragen*
|*Nein* = Cross-Selling-Einstellungen werden standardmäßig nicht übertragen. +
*Ja* = Cross-Selling-Einstellungen werden übertragen.

|*UVP übertragen*
|*Nein* = Die UVP wird standardmäßig nicht übertragen. +
*Ja* = Die UVP wird übertragen.

|*Am Artikel hinterlegte Artikelmaße*
|Artikelmaße wählen.

|*Mandanten (Shop) ID übertragen?*
|*Nein* = Die ID wird standardmäßig nicht übertragen. +
*Ja* = Die ID wird übertragen.

|*Standardprovisionsmodell*
|Provisionsmodell wählen, wie von Neckermann erhalten.

|*Bestandspuffer*
|Der übertragene Bestand von Artikeln wird um den eingegebenen Wert reduziert, damit der Arikel auf diesem Marktplatz nicht vollständig abverkauft wird. +
*Beispiel*: Für einen Artikel mit einem Bestand von 50 und einem Bestandspuffer von 10 wird der Bestandswert 40 übertragen. Weitere Informationen finden Sie auf der Handbuchseite <<warenwirtschaft/warenbestaende-verwalten#, Warenbestände verwalten>>.

|*Lieferzeiten*
|*Standardlieferzeiten* = Lieferzeit in Tagen eingeben. Diese Lieferzeit ist die Standardlieferzeit, die Sie für die meisten Ihrer Sendungen benötigen. +
*Artikel-Lieferzeit 1 - 5* = Lieferzeit in Tagen bei jeder Option eingeben. Die Optionen für Artikelverfügbarkeit werden im Menü <<artikel/artikel-verwalten#190, System » Artikel » Verfügbarkeit>> eingerichtet.

|*Feature-Liste*
|Textfeld oder *Nicht übertragen* wählen.

|*Artikelnummer übertragen*
|*Nein* = Artikelnummer wird nicht übertragen. +
*Ja* = Artikelnummer wird beim Artikelexport übertragen. Maximal 20 Zeichen werden übertragen.

|*Verfügbarkeit für Artikel ohne Bestandsbeschränkung, falls der Bestand 0 ist, überschreiben?*
|*Ja, mit Artikelverfügbarkeit 1 bis 5* = Verfügbarkeit durch Artikelverfügbarkeit 1 bis 5 (siehe Lieferzeiten) überschreiben.  +
*Nein* = Verfügbarkeit nicht überschreiben.

|*Bestandsmenge für Artikel ohne Bestandsbeschränkung, falls der Bestand 0 ist*
|Eingeben, welche Bestandsmenge bei fehlendem Bestand angezeigt werden soll.

2+|Bestelleinstellungen

|*Aufträge als nicht bezahlt buchen*
|*Ja* = In der Grundeinstellung kommen die Aufträge als *nicht bezahlt* im System an, da die Zahlung zu einem späteren Zeitpunkt abgewickelt wird. +
*Nein* = Aufträge werden als *bezahlt* gebucht.

|*Paketnummer speichern*
|*Ja* = Die Paketnummer wird standardmäßig übertragen. +
*Nein* = Die Paketnummer wird nicht übertragen.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierten Funktionen bereit:

* Täglicher Artikelexport
* Stündlicher Bestandsabgleich
* Stündlicher Auftragsimport
* Stündliche Meldung von Versandbestätigungen
* Stündliche Meldung von Retouren
* Stündliche Meldung von Stornierungen

[WARNING]
.Paketnummern übertragen
====
Jeder einzelne Neckermann-Auftrag darf nicht mehr als eine Paketnummer besitzen. Wird diese Bedingung nicht erfüllt, werden die entsprechenden Aufträge nicht an Neckermann gemeldet!
====

[#250]
== Auftragsherkunft aktivieren

Damit Sie Artikel, Merkmale etc. mit Neckermann.at verknüpfen können, muss im Menü *System » Aufträge » Auftragsherkunft* die Auftragsherkunft *Neckermann.at Enterprise* aktiviert werden.

[.instruction]
Auftragsherkunft für Neckermann.at aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Auftragsherkunft*.
. Setzen Sie bei *Neckermann.at Enterprise* ein Häkchen.
. *Speichern* Sie die Einstellungen.

[#300]
== Auftragsstatus einstellen

In diesem Bereich stellen Sie Ihre Auftragsstatus für Stornierungen ein und legen fest, wann Retouren an Neckermann gemeldet werden.

[.instruction]
Auftragsstatus einstellen:

.  Öffnen Sie das Menü *System » Märkte » Neckermann Österreich Enterprise*.
. Klappen Sie den Bereich *Auftragsstatus* auf.
.  Nehmen Sie die Einstellungen gemäß <<auftragsstatus-neckermann>> vor.
. *Speichern* Sie die Einstellungen.

[[auftragsstatus-neckermann]]
.Auftragsstatus einstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Auftragsstatus für Komplettstornierung "Bestandsstorno"*
|Status wählen, z.B. *[8] Storniert*, *[9] Retoure* oder *[10] Gewährleistung*.

|*Auftragsstatus für Komplettstornierung "Kundenstorno"*
|Status wählen, z.B. *[8] Storniert*, *[9] Retoure* oder *[10] Gewährleistung*.

|*Retouren melden wenn in Status*
|Status wählen, z.B. *[9] Retoure*.
|====

[#400]
== FTP-Serverzugang einrichten

In diesem Bereich richten Sie den Zugang zum FTP-Server ein. Der Zugang wird für den Auftrags- und Rechnungsimport von Neckermann benötigt.

[.instruction]
FTP-Serverzugang einrichten:

.  Öffnen Sie das Menü *System » Märkte » Neckermann Österreich Enterprise*.
. Klappen Sie den Bereich *FTP-Server* auf.
.  Geben Sie die Zugangsdaten ein, die Sie von Neckermann erhalten haben.
. *Speichern* Sie die Einstellungen.

[#500]
== Komponenten importieren

Komponenten beim Marktplatz Neckermann entsprechen den Merkmalen in plentymarkets. Merkmale in plentymarkets müssen mit Komponenten von Neckermann verknüpft werden. plentymarkets Merkmale werden durch Hochladen einer CSV-Datei, welche die Neckermann-Komponenten enthält, mit Neckermann-Komponenten verknüpft. Die notwendige Datei erhalten Sie von Neckermann bei Vertragsabschluss.

[.instruction]
Neckermann-Komponenten importieren:

. Öffnen Sie die Datei von Neckermann.
. Markieren und kopieren Sie die Spalten *COMPONENT_ID* und *COMPONENT_NAME*.
. Fügen Sie die Spalten in eine neue Datei einer Tabellenkalkulationssoftware ein.
. Speichern Sie die Datei im CSV-Format auf Ihrem Rechner.
. Öffnen Sie das Menü *System » Märkte » Neckermann Österreich Enterprise*.
. Klappen Sie den Bereich *Komponenten-Import* auf.
. Wählen Sie das Feldtrennzeichen.
. Klicken Sie auf *Datei auswählen*.
. Öffnen Sie die CSV-Datei.
. *Speichern* Sie die Einstellungen. +
→ Die Neckermann-Komponenten können nun in den Dropdown-Listen der Merkmale gewählt werden.

[#600]
== Merkmale verknüpfen

Als nächstes verknüpfen Sie Ihre <<artikel/artikel-verwalten#480, Merkmale>> mit den Neckermann-Komponenten.

[.instruction]
Merkmale verknüpfen:

. Öffnen Sie in das Menü *System » Artikel » Merkmale*.
. Klappen Sie ein Merkmal auf.
. Wählen Sie aus der Dropdown-Liste im Feld *Neckermann.at EP Komponente* die Neckermann-Komponente.
. *Speichern* Sie die Einstellungen.

[#700]
== Logos importieren

Neckermann stellt verschiedene Logos, z. B. für Eigenschaften oder Qualitätsmerkmale zur Verfügung. Logos werden durch Hochladen einer CSV-Datei importiert, die Daten von Neckermann enthält. Logos verknüpfen Sie auf die gleiche Weise wie Neckermann-Komponenten.

[.instruction]
Neckermann-Logos importieren:

. Öffnen Sie die Datei von Neckermann.
. Markieren und kopieren Sie die Spalten *LOGO_ID*, *LOGO_DESCRIPTION* und *Kurzbeschreibung*.
. Fügen Sie die Spalten in eine neue Datei einer Tabellenkalkulationssoftware ein, die den Spaltennamen *LOGO_ID;LOGO_NAME;SHORT_NAME* hat.
. Speichern Sie die Datei im CSV-Format auf Ihrem Rechner.
. Öffnen Sie das Menü *System » Märkte » Neckermann Österreich Enterprise*.
. Klappen Sie den Bereich *Infologo-Import* auf.
. Wählen Sie das Feldtrennzeichen.
. Klicken Sie auf *Durchsuchen...*.
. Öffnen Sie die CSV-Datei.
. *Speichern* Sie die Einstellungen. +
→ Die Neckermann-Logos können nun in den Dropdown-Listen der Merkmale gewählt werden.

[#800]
== Kategorien verknüpfen

Sie erhalten von Neckermann eine Datei mit Kategorien, in die Sie Ihre Webshop-Kategorien einordnen müssen. Die Kategorien werden dann verknüpft und weitere Artikel der verknüpften Kategorien werden automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffnen Sie das Menü *System » Märkte » Neckermann Österreich Enterprise*.
. Öffnen Sie das Tab *Kategorien importieren*.
. Geben Sie die Kategorien in die Spalte *Neckermann-Kategorie-ID* ein.
. *Speichern* Sie die Einstellungen.

[#900]
== Primär-Kategorien aktivieren

Wenn Sie einen Artikel mit mehreren Kategorien verknüpft haben, z.B. wenn Sie verschiedene Kategorieverknüpfungen für verschiedene Marktplätze verwenden, können Sie im Tab *Kategorien* eines Artikels die Primärkategorie aktivieren. Wenn Sie keine Primär-Kategorie aktivieren, wird automatisch die erste Kategorie als Primär-Kategorie verwendet.

[.instruction]
Primär-Kategorie aktivieren:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie einen Artikel.
. Wechseln Sie in das Tab *Kategorien*. +
→ Primär-Kategorien sind nur unter *Kategorieverknüpfungen* verfügbar, wenn der Marktplatz *Neckermann* aktiviert ist.
. Aktivieren Sie eine Primär-Kategorie.
. *Speichern* Sie die Einstellungen.

[#1000]
== Attribute verknüpfen

Wenn Sie <<artikel/artikel-verwalten#390, Attribute>> im plentymarkets System erstellt haben, müssen diese Attribute mit Neckermann verknüpft werden. Dazu müssen Sie zunächst die <<Komponenten importieren, Neckermann-Komponenten>> importieren. Nachfolgend wird beschrieben, wie Sie das Attribut Farbe mit Neckermann verknüpfen. Verknüpfen Sie andere Attribute auf die gleiche Weise.

[.instruction]
Attribute verknüpfen:

. Öffnen Sie das Menü *System » Artikel » Attribute*. +
→ Eine Übersicht aller erstellten Attribute wird geöffnet.
. Klappen Sie das Attribut *Farbe* auf.
. Wechseln Sie in das Tab *Marktplatzvariation*.
. Wählen Sie in der Dropdown-Liste *Marktplatz* die Option *Neckermann.at Enterprise*. +
→ Eine zusätzliche Dropdown-Liste *Neckermann.at Enterprise* wird angezeigt.
. Wählen Sie in der Dropdown-Liste *Neckermann.at Enterprise* das Attribut *Farbe*.
. Geben Sie unter *Marktplatzvariation* Werte in der Spalte *Neckermann.at Enterprise* ein.
. *Speichern* Sie die Einstellungen.

[#1100]
== Hersteller verknüpfen

Brand-IDs für Neckermann.at werden über den dynamischen Datenaustausch importiert.

[.instruction]
Brand-IDs von Neckermann.at importieren:

. Öffnen Sie das Menü *Daten » Dynamischer Export » Tab: Neues Datenformat*.
. Wählen Sie unter *Datenformat-Typ* die Einstellung *Producer*.
. Geben Sie einen Namen ein.
. Aktivieren Sie die Felder *ProducerID*, *ProducerName* und *ProducerNeckermannID_AT_EP* bzw. *ProducerNeckermannID_AT_CD*.
. *Speichern* Sie die Einstellungen. +
→ Das Tab *Datenformat bearbeiten* wird geöffnet.
. Klappen Sie das Datenformat auf.
. Klicken Sie auf *Daten exportieren*.
. Speichern Sie die CSV-Datei auf Ihrem Rechner.
. Geben Sie in die CSV-Datei unter *ProducerNeckermannID* die passenden Hersteller-IDs ein. +
→ Die IDs finden Sie in der Datei von Neckermann.
. Öffnen Sie das Menü *Daten » Dynamischer Import*.
. Wählen Sie das Feldtrennzeichen.
. Wählen Sie unter *Format* Ihr Datenformat.
. Klicken Sie auf *Durchsuchen...*.
. Öffnen Sie die CSV-Datei.
. Klicken Sie auf *Import*. +
→ Nach dem Import der Brand-IDs finden Sie die Neckermann-ID eines Herstellers im Menü *System » Artikel » Hersteller*.

[IMPORTANT]
.Format der CSV-Datei
====
Die CSV-Datei darf keine Kopfzeile enthalten. Die erste Spalte enthält die Hersteller-ID und die zweite Spalte die Brand-IDs von Neckermann. Die Hersteller-ID der ersten Spalte ist der entsprechenden Brand-ID der zweiten Spalte zugeordnet.
====

[#1200]
== Exportierte Artikel anzeigen

Im Menü *System » Märkte » Neckermann Österreich Enterprise » Tab: Übertragene Artikel* suchen Sie nach bereits an Neckermann übertragenen Artikeln. Geben Sie dazu die Artikel-ID, den Namen oder die Neckermann-Nummer ein, um nach bestimmten Artikeln zu suchen oder lassen Sie das Suchfeld leer, um alle Ergebnisse anzuzeigen.

[#1300]
== Fehlerberichte anzeigen

Sämtliche Vorgänge des Marktplatzes Neckermann werden in Ihrem plentymarkets System protokolliert. Sie können diese Meldungen aufrufen und erhalten eine Auflistung der Fehlermeldungen bzw. Hinweise mit den zugehörigen IDs. Im Menü *Fehlerberichte* werden Fehler aufgelistet, die mit Ihrem Warenbestand bei Neckermann zu tun haben. Die folgenden Fehlerarten werden unterschieden:

* *Hinweis*: Ein Hinweis wird angezeigt.
* *Warnung*: Bei Warnungen werden alle Artikel importiert.
* *Fehler*: Bei Fehlern werden keine fehlerhaften Artikel importiert.
* *Kritischer Fehler*: Bei kritischen Fehlern werden keine Artikel importiert.

[.instruction]
Fehlerberichte abrufen:

. Öffnen Sie das Menü *System » Märkte » Neckermann Österreich Enterprise*.
. Öffnen Sie das Tab *Fehlerberichte*.
. Klicken Sie auf *Fehlerberichte abrufen*. +
→ Die Fehlerberichte werden abgerufen und anschließend angezeigt.

In der Liste *Neueste Fehlerberichte* erhalten Sie Hinweise über Art und Anzahl der Fehler zu folgenden Datentypen:

* *Media (Bilder)*: Informationen zu Mediendateien.
* *Katalog*: Informationen zum Katalog und aller darin enthaltenen Artikel eines Händlers.
* *Bestandsabgleich*: Informationen zum stündlichen Warenbestandsabgleich sowie Preisabgleich.

Bei Fehlern, die beim Artikelexport aus plentymarkets aufgrund fehlerhafter Artikeldaten auftreten, finden Sie in der Fehlermeldung Informationen zum betreffenden Artikel sowie zur Fehlerart. Beheben Sie den Fehler und prüfen Sie nach dem nächsten automatischen Artikelexport, ob weitere Fehlermeldungen vorliegen.

[TIP]
.Fehlermeldungsbeschreibung
====
Nähere Angaben zu den Fehlermeldungen erhalten Sie direkt von Neckermann. Kontaktieren Sie ggf. Ihren dortigen Ansprechpartner.
====

[#1400]
== Artikelverfügbarkeit einstellen

Artikel, die Sie auf Neckermann.at verkaufen möchten, müssen im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Neckermann.at einstellen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktivieren Sie die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechseln Sie in das Tab *Verfügbarkeit*.
. Klicken Sie im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktivieren Sie Neckermann.at Enterprise.
. Aktivieren Sie die Option Web-API.
. Klicken Sie auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichern* Sie die Einstellungen.
. Wechseln Sie in das Tab *Multi-Channel*.
. Wählen Sie ein *Provisionsmodell*.
. Wählen Sie einen *Produkttyp*.
. *Speichern* Sie die Einstellungen.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* individuell angepasst werden.

[#1450]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügen Sie, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
.  Wechseln Sie in das Tab *Verfügbarkeit*.
.  Klicken Sie im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
.  Wählen Sie die Herkunft *Neckermann.at*.
.  Geben Sie die SKU ein.
.  Klicken Sie auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

Informationen zum Provisionsmodell und zur Produkttyp erhalten Sie von Neckermann.

[#1500]
== Energieeffizienz angeben

Für die Auszeichnung Ihrer Artikel für Neckermann gemäß der neuen Verordnung der EU zur Energieeffizienzrichtlinie sind ab 1.1.2015 Angaben zur Energieeffizienz sowie die Bereitstellung von Produktdatenblättern vorgeschrieben. Erstellen Sie dazu folgende <<artikel/artikel-verwalten#480, Merkmale>>:

* *Energieeffizienzklasse* +
Merkmal-Typ: *Kein*
* *Energieetikett* +
Merkmal-Typ: *Datei* +
Dateiformat: z.B. *JPG* oder *PNG* (Bildformat)
* *Produktdatenblatt* +
Merkmal-Typ: *Datei* +
Dateiformat: *PDF*

[.instruction]
Merkmal Energieeffizienzklasse erstellen:

. Öffnen Sie das Menü *System » Artikel » Merkmale*.
. Wechseln Sie in das Tab *Neues Merkmal*.
. Geben Sie den Namen unter *Name (intern)* ein.
. Wählen Sie den Merkmaltyp *Kein*.
. *Speichern* Sie die Einstellungen.

Für die Merkmale Energieetikett und Produktdatenblatt wählen Sie den Merkmaltyp *Datei* und das Neckermann-Merkmal *Energieetikett* bzw. *Produktdatenblatt*. Im Folgenden wird beispielhaft beschrieben, wie Sie das Energieetikett für Neckermann.at erstellen.

[.instruction]
Merkmal Energieetikett erstellen:

. Öffnen Sie das Menü *System » Artikel » Merkmale*.
. Wechseln Sie in das Tab *Neues Merkmal*.
. Geben Sie den Namen unter *Backendname* ein.
. Wählen Sie den Merkmaltyp *Datei*.
. Wählen Sie unter *Neckermann.at EP Merkmal* das Merkmal *Energieetikett*.
. *Speichern* Sie die Einstellungen.

Die Merkmale verknüpfen Sie im Tab *Merkmale* eines Artikels.

[.instruction]
Energieeffizienz-Merkmale verknüpfen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab *Merkmale*.
. Aktivieren Sie die soeben erstellten Merkmale *Energieeffizienzklasse*, *Energieetikett* und *Produktdatenblatt*.
. *Speichern* Sie die Einstellungen. +
→ Die Merkmale werden in der Liste angezeigt.
. Laden Sie beim Merkmal *Energieetikett* die Bilddatei des Energieetiketts hoch.
. Laden Sie beim Merkmal *Produktdatenblatt* die PDF-Datei des Produktdatenblatts hoch.
. *Speichern* Sie die Einstellungen.

*_Oder:_* Speichern Sie das Energieetikett im Tab *Bilder* des Artikels. Gehen Sie dazu wie im Folgenden beschrieben vor.

[.instruction]
Energieetikett als Bild hinterlegen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel.
. Wechseln Sie in das Tab *Bilder*.
. Fügen Sie die Bilddatei des Energieetiketts entweder über *Dateien auswählen* oder per Drag &amp; Drop-Funktion hinzu.
. *Speichern* Sie die Einstellungen.
. Öffnen Sie das Menü *System » Märkte » Neckermann Österreich Enterprise*.
. Geben Sie die Positionsnummer des Bildes im Bereich *Grundeinstellungen* bei der Option *Bildposition für das Energieetikett* ein.
. *Speichern* Sie die Einstellungen.

[#1600]
== Zahlungsart aktivieren

Aktivieren Sie die <<payment/zahlungsarten-verwalten#, Zahlungsart>> *Neckermann Payment*, wie im Folgenden beschrieben.

[.instruction]
Neckermann-Zahlungsarten aktivieren:

.  Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
.  Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
.  Öffnen Sie den Ordner *International*.
.  Klicken Sie auf *Neckermann Payment*. +
→ Das Tab *Einstellungen* wird geöffnet.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<zahlungsart-neckermann>>.
.  Setzen Sie ein Häkchen bei der Option *Aktiv*.
. *Speichern* Sie die Einstellungen.

[[zahlungsart-neckermann]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Sprache*
| Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit haben Sie die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
| Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
| Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
| Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
| Kein Lieferland wählen. +
Sie können die Zahlungsart nicht in Ihrem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
| Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
| Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
| Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben. +
Weitere Informationen finden Sie auf der Handbuchseite <<basics/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten finden Sie auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » CRM » Kundenklassen* aktivieren oder deaktivieren Sie *erlaubte Zahlungsarten*. +
Weitere Informationen finden Sie im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen finden Sie auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#1700]
== Retouren erstellen

Retouren für Neckermann erstellen Sie im Menü *Aufträge » Aufträge bearbeiten*. Dafür benötigen sie den *Paketcode*, der sich auf dem Rücksendeschein der Retoure befindet.

[.instruction]
Retoure erstellen:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Auftrag.
. Wählen Sie im Tab *Übersicht* aus der Dropdown-Liste *Retoure...* die Option *anlegen*. +
→ Das Fenster *Retoure zum Auftrag* wird geöffnet.
. Geben Sie den *Paketcode der Retoure* ein.
. Aktivieren Sie unter *Artikel* in der Spalte *Übernehmen* das Kontrollkästchen.
. *Speichern* Sie die Einstellungen. +
→ Die Retoure wird erstellt und geöffnet. Der Code ist im Tab *Einstellungen* der Retoure gespeichert.

[TIP]
.Tipp: Paketcode der Retoure
====
Der Paketcode lässt sich nicht nachträglich in der Retoure eingeben, sondern nur direkt wenn die Retoure erstellt wurde.
====

[#1800]
== Aufträge stornieren

Da für Stornierungen von z.B. einzelnen Artikeln eines Auftrages keine Möglichkeit des Löschens zur Verfügung steht, setzen Sie in einem solchen Fall die Menge des betreffenden Artikels auf 0. Zu jeder Stornierung muss ein Grund angegeben werden, entweder *Ware nicht auf Lager* oder *Kundenstornierung*.

[#1850]
== Neckermann-Rechnung erzeugen

Die Vorgehensweise zur Erzeugung von Neckermann-Rechnungen ist, verglichen mit den anderen Auftragsherkünften, ein Sonderfall. Deshalb gibt es in plentymarkets ein zusätzliches Menü für Neckermann-Rechnungen. Rechnungen für *Neckermann-Aufträge* werden nicht erst in Ihrem plentymarkets System erzeugt, wie bei Rechnungen anderer Auftragsherkünfte. Stattdessen erhält Ihr plentymarkets-System eine spezielle Datei (pcl-Format) mit den für Sie eingegangenen Aufträgen direkt vom Marktplatz Neckermann.

Einstellungen zum Layout aller Rechnungen können Sie im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* vornehmen. Im Menü *System » Aufträge » Ereignisse* definieren Sie, welche Aktion beim Rechnungsdruck durch eine Ereignisaktion zusätzlich ausgeführt werden soll. Vergessen Sie dabei nicht, einen Filter des Filtertyps *Herkunft* zu setzen und dort *Neckermann* auszuwählen, wenn die Aktion nur auf Aufträge von diesem Marktplatz beschränkt sein soll.

Nutzen Sie das Menü *Neckermann-Rechnungen erzeugen*, um aus den erhaltenen Neckermann-Aufträgen die von Ihnen gewünschten herauszufiltern und die zugehörigen Rechnungen in einer gesonderten Datei zu öffnen. Nutzen Sie den Suchfilter in diesem Bereich, um die Kriterien zu bestimmen, nach denen die Aufträge zum Rechnungsabruf ausgewählt werden.

[.instruction]
Neckermann-Rechnungen abrufen:

. Öffnen Sie das Menü *Aufträge » Fulfillment » Neckermann-Rechnungen erzeugen*.
. Stellen Sie die gewünschten Optionen für den *Suchfilter* ein.
. Wählen Sie unter *Aktion* einen neuen *Auftragsstatus*, der den gewählten Aufträgen nach erfolgreichem Rechnungsabruf zugewiesen werden soll.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu <<einstellungen-neckermann-rechnungen>>.
. Klicken Sie auf das *Zahnrad*. +
→ Eine *zip-Datei* wird erstellt, welche die zugehörigen Rechnungen aller von Ihnen durch die Filteroptionen bestimmten Aufträge enthält.
. Nach Entpacken dieser zip-Datei werden die Rechnungen gespeichert und ausgedruckt.

[[einstellungen-neckermann-rechnungen]]
.Einstellungen für Neckermann-Rechnungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Auftragsstatus*
|*Status* wählen, in dem sich die Aufträge befinden, für die Rechnungen erzeugt werdem sollen.

|*Warenausgangsdatum*
|Datum aus dem Kalender wählen. Das Warenausgangsdatum wird nur als Filter wirksam, wenn in der Dropdown-Liste *Auftragsstatus* der Status *[7] Warenausgang gebucht* gewählt ist.

|*Eigner*
|*Eigner* der zu suchenden Aufträge oder die Option *ALLE* wählen.

|*Mandant (Shop)*
|Einen *Shop* oder die Option *ALLE* wählen.

|*Lager*
|Suche auf ein *Lager* begrenzen oder die Suche für *ALLE* Lager ausführen.

|*Limit*
|Rechnungserstellung muss auf einen der Werte im Drop-down-Menü begrenzt werden. Maximum sind 200 Rechnungen.

|*Ändere Auftragsstatus*
|Einen neuen *Auftragsstatus* wählen, der den gewählten Aufträgen nach erfolgreichem Rechnungsabruf zugewiesen werden soll oder die Option *Keine Änderung* wählen.
|====

[#1900]
== API-Log abrufen

Im Menü *Daten » API-Log » Tab: API-Log* finden Sie eine Historie über Vorgänge, die über die Neckermann-Schnittstelle ausgeführt wurden. Die Formate *NeckermannATEP* und *NeckermannATCD* stehen Ihnen für Neckermann zur Verfügung.

[.instruction]
API-Log abrufen:

.  Öffnen Sie das Menü *Daten » API-Log*.
.  Wählen Sie das Format *NeckermannATEP* aus der Dropdown-Liste *Vorgang*.
.  Wählen Sie ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
.  Wählen Sie die Anzahl der Ergebnisse pro Seite.
.  Klicken Sie auf *Suchen*, um die Ergebnisse anzuzeigen.
