= Neckermann.at einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Neckermann.at, Marktplatz
:description: Multi-Channel in plentymarkets: Richte die Schnittstelle zum Marktplatz Neckermann Österreich in deinem plentymarkets System ein.
:position: 10
:url: maerkte/neckermann/neckermann-at-einrichten

Neckermann Österreich bietet dir die Möglichkeit, deine Produkte auf dem Marktplatz *neckermann.at* zu präsentieren. Du erhältst auf dieser Handbuchseite detaillierte Informationen zur Vorgehensweise, um den Marktplatz Neckermann Österreich für dein plentymarkets System einzurichten. Beachte diese Informationen, um eine möglichst reibungslose Anbindung zu gewährleisten.

[#100]
== Bei Neckermann.at registrieren

Wenn du Partner bei link:http://www.neckermann.at/[Neckermann Österreich^] werden möchtest, wende dich bitte zunächst direkt an Neckermann.at.

.Ansprechpartner
[cols="1,3"]
|====
|Ansprechpartner |E-Mail-Adresse

|*René Riebenbauer* - Leitung Vertriebsplattform und Contentmanagement
|link:mailto:rene.riebenbauer@neckermann.at[rene.riebenbauer@neckermann.at^]
|====

[#200]
== Neckermann.at in plentymarkets einrichten

Nachdem du Neckermann-Partner geworden bist, verwende deine Zugangsdaten, um den Marktplatz in plentymarkets einzurichten. Du kannst die Plattform Neckermann.at Enterprise an plentymarkets anbinden. Um Neckermann.at Enterprise in plentymarkets einzurichten, gehe wie im Folgenden beschrieben vor.
// Richten Sie Neckermann.at Cross-Docking auf die gleiche Weise ein.

[.instruction]
Neckermann.at in plentymarkets einrichten:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Neckermann Österreich Enterprise*.
. Klappe den Bereich *Grundeinstellungen* auf.
. Nimm die Einstellungen gemäß <<grundeinstellungen-neckermann>> vor.
. *Speichere* die Einstellungen.

[[grundeinstellungen-neckermann]]
.Grundeinstellungen des Marktplatzes Neckermann.at
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Schnittstellenmodus*
|Schnittstellenmodus wählen. +
*Testmodus EIN* = Wählen, wenn Einstellungen und Vorbereitungen an Schnittstelle und Artikeln getroffen werden. +
*Aktivmodus EIN* = Wählen, nachdem du sicher bist, dass alle Einstellungen korrekt vorgenommen wurden.

2+|Vertriebspartner-Information

|*Partner-ID*
|ID eingeben, wie von Neckermann erhalten.

|*Firmenname*
|Firmen- oder Webshop-Name eingeben.

|*Name*, *Vorname (Kontaktperson)*;  +
*Telefonnummer (Kontaktperson)*; +
*E-Mail-Adresse (Kontaktperson)*
|Name, Telefonnummer und E-Mail-Adresse der Kontaktperson eingeben.

2+|Artikeleinstellungen

|*Regelsteuersatz*
|*10 %* oder *20 %* wählen.

|*Ermäßigter Steuersatz*
|*7 %* oder *19 %* wählen.

|*Artikelname*
|Textfeld wählen, das als Artikelname an Neckermann übertragen wird.

|*Artikelname (maximale Länge)*
|*35 Zeichen* oder *65 Zeichen* wählen.

|*Artikelvorschautext*
|Textfeld wählen, das als Artikelvorschautext an Neckermann übertragen wird.

|*Artikelvorschautext (maximale Länge)*
|*30 Zeichen* oder *50 Zeichen* wählen.

|*Artikelkurztext*
|Textfeld wählen, das als Artikelkurztext an Neckermann übertragen wird.

|*Artikelbeschreibung*
|Textfeld wählen, das als Artikelbeschreibung an Neckermann übertragen wird.

|*Artikel ohne Markenzuordnung übertragen*
|*Nein* = Artikel werden standardmäßig mit Markenzuordnung übertragen. +
*Ja* = Artikel werden ohne Markenzuordnung übertragen.

|*Bildposition für das Energieetikett*
|Ziffer der Bildposition des Artikelbildes eingeben, wenn das Energieetikett als Artikelbild und nicht als Merkmal gespeichert wurde. Weitere Informationen zum Energieetikett findest du im Kapitel <<Energieeffizienz angeben, Energieeffizienz angeben>>.

|*Cross-Selling übertragen*
|*Nein* = Cross-Selling-Einstellungen werden standardmäßig nicht übertragen. +
*Ja* = Cross-Selling-Einstellungen werden übertragen.

|*UVP übertragen*
|*Nein* = Die UVP wird standardmäßig nicht übertragen. +
*Ja* = Die UVP wird übertragen.

|*Am Artikel hinterlegte Artikelmaße*
|Artikelmaße wählen.

|*Mandanten (Shop) ID übertragen?*
|*Nein* = Die ID wird standardmäßig nicht übertragen. +
*Ja* = Die ID wird übertragen.

|*Standardprovisionsmodell*
|Provisionsmodell wählen, wie von Neckermann erhalten.

|*Bestandspuffer*
|Der übertragene Bestand von Artikeln wird um den eingegebenen Wert reduziert, damit der Arikel auf diesem Marktplatz nicht vollständig abverkauft wird. +
*Beispiel*: Für einen Artikel mit einem Bestand von 50 und einem Bestandspuffer von 10 wird der Bestandswert 40 übertragen. Weitere Informationen findest du auf der Handbuchseite <<warenwirtschaft/warenbestaende-verwalten#, Warenbestände verwalten>>.

|*Lieferzeiten*
|*Standardlieferzeiten* = Lieferzeit in Tagen eingeben. Diese Lieferzeit ist die Standardlieferzeit, die Sie für die meisten Ihrer Sendungen benötigen. +
*Artikel-Lieferzeit 1 - 5* = Lieferzeit in Tagen bei jeder Option eingeben. Die Optionen für Artikelverfügbarkeit werden im Menü *System » Systemeinstellungen » Artikel » Verfügbarkeit* eingerichtet.

|*Feature-Liste*
|Textfeld oder *Nicht übertragen* wählen.

|*Artikelnummer übertragen*
|*Nein* = Artikelnummer wird nicht übertragen. +
*Ja* = Artikelnummer wird beim Artikelexport übertragen. Maximal 20 Zeichen werden übertragen.

|*Verfügbarkeit für Artikel ohne Bestandsbeschränkung, falls der Bestand 0 ist, überschreiben?*
|*Ja, mit Artikelverfügbarkeit 1 bis 5* = Verfügbarkeit durch Artikelverfügbarkeit 1 bis 5 (siehe Lieferzeiten) überschreiben.  +
*Nein* = Verfügbarkeit nicht überschreiben.

|*Bestandsmenge für Artikel ohne Bestandsbeschränkung, falls der Bestand 0 ist*
|Eingeben, welche Bestandsmenge bei fehlendem Bestand angezeigt werden soll.

2+|Bestelleinstellungen

|*Aufträge als nicht bezahlt buchen*
|*Ja* = In der Grundeinstellung kommen die Aufträge als *nicht bezahlt* im System an, da die Zahlung zu einem späteren Zeitpunkt abgewickelt wird. +
*Nein* = Aufträge werden als *bezahlt* gebucht.

|*Paketnummer speichern*
|*Ja* = Die Paketnummer wird standardmäßig übertragen. +
*Nein* = Die Paketnummer wird nicht übertragen.
|====

Die Anbindung des Marktplatzes stellt folgende automatisierten Funktionen bereit:

* Täglicher Artikelexport
* Stündlicher Bestandsabgleich
* Stündlicher Auftragsimport
* Stündliche Meldung von Versandbestätigungen
* Stündliche Meldung von Retouren
* Stündliche Meldung von Stornierungen

[WARNING]
.Paketnummern übertragen
====
Jeder einzelne Neckermann-Auftrag darf nicht mehr als eine Paketnummer besitzen. Wird diese Bedingung nicht erfüllt, werden die entsprechenden Aufträge nicht an Neckermann gemeldet!
====

[#250]
== Auftragsherkunft aktivieren

Damit du Artikel, Merkmale etc. mit Neckermann.at verknüpfen kannst, muss im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* die Auftragsherkunft *Neckermann.at Enterprise* aktiviert werden.

[.instruction]
Auftragsherkunft für Neckermann.at aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Setze bei *Neckermann.at Enterprise* ein Häkchen.
. *Speichere* die Einstellungen.

[#300]
== Auftragsstatus einstellen

In diesem Bereich stellst du deine Auftragsstatus für Stornierungen ein und legst fest, wann Retouren an Neckermann gemeldet werden.

[.instruction]
Auftragsstatus einstellen:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Neckermann Österreich Enterprise*.
. Klappe den Bereich *Auftragsstatus* auf.
. Nimm die Einstellungen gemäß <<auftragsstatus-neckermann>> vor.
. *Speichere* die Einstellungen.

[[auftragsstatus-neckermann]]
.Auftragsstatus einstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Auftragsstatus für Komplettstornierung "Bestandsstorno"*
|Status wählen, z.B. *[8] Storniert*, *[9] Retoure* oder *[10] Gewährleistung*.

|*Auftragsstatus für Komplettstornierung "Kundenstorno"*
|Status wählen, z.B. *[8] Storniert*, *[9] Retoure* oder *[10] Gewährleistung*.

|*Retouren melden wenn in Status*
|Status wählen, z.B. *[9] Retoure*.
|====

[#400]
== FTP-Serverzugang einrichten

In diesem Bereich richtest du den Zugang zum FTP-Server ein. Der Zugang wird für den Auftrags- und Rechnungsimport von Neckermann benötigt.

[.instruction]
FTP-Serverzugang einrichten:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Neckermann Österreich Enterprise*.
. Klappe den Bereich *FTP-Server* auf.
. Gib die Zugangsdaten ein, die du von Neckermann erhalten hast.
. *Speichere* die Einstellungen.

[#500]
== Komponenten importieren

Komponenten beim Marktplatz Neckermann entsprechen den Merkmalen in plentymarkets. Merkmale in plentymarkets müssen mit Komponenten von Neckermann verknüpft werden. plentymarkets Merkmale werden durch Hochladen einer CSV-Datei, welche die Neckermann-Komponenten enthält, mit Neckermann-Komponenten verknüpft. Die notwendige Datei erhältst du von Neckermann bei Vertragsabschluss.

[.instruction]
Neckermann-Komponenten importieren:

. Öffne die Datei von Neckermann.
. Markiere und kopiere die Spalten *COMPONENT_ID* und *COMPONENT_NAME*.
. Füge die Spalten in eine neue Datei einer Tabellenkalkulationssoftware ein.
. Speichere die Datei im CSV-Format auf deinem Rechner.
. Öffne das Menü *System » Systemeinstellungen » Märkte » Neckermann Österreich Enterprise*.
. Klappe den Bereich *Komponenten-Import* auf.
. Wähle das Feldtrennzeichen.
. Klicke auf *Datei auswählen*.
. Öffne die CSV-Datei.
. *Speichere* die Einstellungen. +
→ Die Neckermann-Komponenten können nun in den Dropdown-Listen der Merkmale gewählt werden.

[#600]
== Merkmale verknüpfen

Als nächstes verknüpfst du deine <<artikel/artikel-verwalten#480, Merkmale>> mit den Neckermann-Komponenten.

[.instruction]
Merkmale verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Klappe ein Merkmal auf.
. Wähle aus der Dropdown-Liste im Feld *Neckermann.at EP Komponente* die Neckermann-Komponente.
. *Speichere* die Einstellungen.

[#700]
== Logos importieren

Neckermann stellt verschiedene Logos, z. B. für Eigenschaften oder Qualitätsmerkmale zur Verfügung. Logos werden durch Hochladen einer CSV-Datei importiert, die Daten von Neckermann enthält. Logos verknüpfst du auf die gleiche Weise wie Neckermann-Komponenten.

[.instruction]
Neckermann-Logos importieren:

. Öffne die Datei von Neckermann.
. Markiere und kopiere die Spalten *LOGO_ID*, *LOGO_DESCRIPTION* und *Kurzbeschreibung*.
. Füge die Spalten in eine neue Datei einer Tabellenkalkulationssoftware ein, die den Spaltennamen *LOGO_ID;LOGO_NAME;SHORT_NAME* hat.
. Speichere die Datei im CSV-Format auf deinem Rechner.
. Öffne das Menü *System » Systemeinstellungen » Märkte » Neckermann Österreich Enterprise*.
. Klappe den Bereich *Infologo-Import* auf.
. Wähle das Feldtrennzeichen.
. Klicke auf *Durchsuchen...*.
. Öffne die CSV-Datei.
. *Speichere* die Einstellungen. +
→ Die Neckermann-Logos können nun in den Dropdown-Listen der Merkmale gewählt werden.

[#800]
== Kategorien verknüpfen

Du erhältst von Neckermann eine Datei mit Kategorien, in die du deine Webshop-Kategorien einordnen musst. Die Kategorien werden dann verknüpft und weitere Artikel der verknüpften Kategorien werden automatisch zugewiesen.

[.instruction]
Kategorien verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Neckermann Österreich Enterprise*.
. Öffne das Tab *Kategorien importieren*.
. Gib die Kategorien in die Spalte *Neckermann-Kategorie-ID* ein.
. *Speichere* die Einstellungen.

[#900]
== Primär-Kategorien aktivieren

Wenn du einen Artikel mit mehreren Kategorien verknüpft hast, z.B. wenn du verschiedene Kategorieverknüpfungen für verschiedene Marktplätze verwendest, kannst du im Tab *Kategorien* eines Artikels die Primärkategorie aktivieren. Wenn du keine Primär-Kategorie aktivierst, wird automatisch die erste Kategorie als Primär-Kategorie verwendet.

[.instruction]
Primär-Kategorie aktivieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne einen Artikel.
. Wechsele in das Tab *Kategorien*. +
→ Primär-Kategorien sind nur unter *Kategorieverknüpfungen* verfügbar, wenn der Marktplatz *Neckermann* aktiviert ist.
. Aktiviere eine Primär-Kategorie.
. *Speichere* die Einstellungen.

[#1000]
== Attribute verknüpfen

Wenn du <<artikel/artikel-verwalten#390, Attribute>> im plentymarkets System erstellt hast, müssen diese Attribute mit Neckermann verknüpft werden. Dazu musst du zunächst die <<Komponenten importieren, Neckermann-Komponenten>> importieren. Nachfolgend wird beschrieben, wie du das Attribut Farbe mit Neckermann verknüpfst. Verknüpfe andere Attribute auf die gleiche Weise.

[.instruction]
Attribute verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Attribute*. +
→ Eine Übersicht aller erstellten Attribute wird geöffnet.
. Klappe das Attribut *Farbe* auf.
. Wechsele in das Tab *Marktplatzvariation*.
. Wähle in der Dropdown-Liste *Marktplatz* die Option *Neckermann.at Enterprise*. +
→ Eine zusätzliche Dropdown-Liste *Neckermann.at Enterprise* wird angezeigt.
. Wähle in der Dropdown-Liste *Neckermann.at Enterprise* das Attribut *Farbe*.
. Gib unter *Marktplatzvariation* Werte in der Spalte *Neckermann.at Enterprise* ein.
. *Speichere* die Einstellungen.

[#1100]
== Hersteller verknüpfen

Brand-IDs für Neckermann.at werden über den dynamischen Datenaustausch importiert.

[.instruction]
Brand-IDs von Neckermann.at importieren:

. Öffne das Menü *Daten » Dynamischer Export » Tab: Neues Datenformat*.
. Wähle unter *Datenformat-Typ* die Einstellung *Producer*.
. Gib einen Namen ein.
. Aktiviere die Felder *ProducerID*, *ProducerName* und *ProducerNeckermannID_AT_EP* bzw. *ProducerNeckermannID_AT_CD*.
. *Speichere* die Einstellungen. +
→ Das Tab *Datenformat bearbeiten* wird geöffnet.
. Klappe das Datenformat auf.
. Klicke auf *Daten exportieren*.
. Speichere die CSV-Datei auf deinem Rechner.
. Gib in die CSV-Datei unter *ProducerNeckermannID* die passenden Hersteller-IDs ein. +
→ Die IDs findest du in der Datei von Neckermann.
. Öffne das Menü *Daten » Dynamischer Import*.
. Wähle das Feldtrennzeichen.
. Wähle unter *Format* dein Datenformat.
. Klicke auf *Durchsuchen...*.
. Öffne die CSV-Datei.
. Klicke auf *Import*. +
→ Nach dem Import der Brand-IDs findest du die Neckermann-ID eines Herstellers im Menü *System » Systemeinstellungen » Artikel » Hersteller*.

[IMPORTANT]
.Format der CSV-Datei
====
Die CSV-Datei darf keine Kopfzeile enthalten. Die erste Spalte enthält die Hersteller-ID und die zweite Spalte die Brand-IDs von Neckermann. Die Hersteller-ID der ersten Spalte ist der entsprechenden Brand-ID der zweiten Spalte zugeordnet.
====

[#1200]
== Exportierte Artikel anzeigen

Im Menü *System » Systemeinstellungen » Märkte » Neckermann Österreich Enterprise » Tab: Übertragene Artikel* suchst du nach bereits an Neckermann übertragenen Artikeln. Gib dazu die Artikel-ID, den Namen oder die Neckermann-Nummer ein, um nach bestimmten Artikeln zu suchen oder lasse das Suchfeld leer, um alle Ergebnisse anzuzeigen.

[#1300]
== Fehlerberichte anzeigen

Sämtliche Vorgänge des Marktplatzes Neckermann werden in deinem plentymarkets System protokolliert. Du kannst diese Meldungen aufrufen und erhältst eine Auflistung der Fehlermeldungen bzw. Hinweise mit den zugehörigen IDs. Im Menü *Fehlerberichte* werden Fehler aufgelistet, die mit deinem Warenbestand bei Neckermann zu tun haben. Die folgenden Fehlerarten werden unterschieden:

* *Hinweis*: Ein Hinweis wird angezeigt.
* *Warnung*: Bei Warnungen werden alle Artikel importiert.
* *Fehler*: Bei Fehlern werden keine fehlerhaften Artikel importiert.
* *Kritischer Fehler*: Bei kritischen Fehlern werden keine Artikel importiert.

[.instruction]
Fehlerberichte abrufen:

. Öffne das Menü *System » Systemeinstellungen » Märkte » Neckermann Österreich Enterprise*.
. Öffne das Tab *Fehlerberichte*.
. Klicke auf *Fehlerberichte abrufen*. +
→ Die Fehlerberichte werden abgerufen und anschließend angezeigt.

In der Liste *Neueste Fehlerberichte* erhältst du Hinweise über Art und Anzahl der Fehler zu folgenden Datentypen:

* *Media (Bilder)*: Informationen zu Mediendateien.
* *Katalog*: Informationen zum Katalog und aller darin enthaltenen Artikel eines Händlers.
* *Bestandsabgleich*: Informationen zum stündlichen Warenbestandsabgleich sowie Preisabgleich.

Bei Fehlern, die beim Artikelexport aus plentymarkets aufgrund fehlerhafter Artikeldaten auftreten, findest du in der Fehlermeldung Informationen zum betreffenden Artikel sowie zur Fehlerart. Behebe den Fehler und prüfe nach dem nächsten automatischen Artikelexport, ob weitere Fehlermeldungen vorliegen.

[TIP]
.Fehlermeldungsbeschreibung
====
Nähere Angaben zu den Fehlermeldungen erhältst du direkt von Neckermann. Kontaktiere ggf. deinen dortigen Ansprechpartner.
====

[#1400]
== Artikelverfügbarkeit einstellen

Artikel, die du auf Neckermann.at verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[.instruction]
Artikelverfügbarkeit für Neckermann.at einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Aktiviere die Hauptvariante im Bereich *Verfügbarkeit*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld.  +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere Neckermann.at Enterprise.
. Aktiviere die Option *Web-API*.
. Klicke auf *Hinzufügen*. +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* die Einstellungen.
. Wechsele in das Tab *Multi-Channel*.
. Wähle ein *Provisionsmodell*.
. Wähle einen *Produkttyp*.
. *Speichere* die Einstellungen.

Die Verfügbarkeit für Varianten kann im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten » Variante öffnen » Tab: Varianten-ID » Tab: Verfügbarkeit* angepasst werden.

[#1450]
==  SKU manuell festlegen

Im Menü <<artikel/artikel-verwalten#170, Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID>> im Tab *Verfügbarkeit* fügst du, wenn nötig, marktplatzspezifische SKUs hinzu.

[.instruction]
SKU hinzufügen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Tab: Varianten-ID » Tab: Einstellungen*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *SKU* auf *Hinzufügen*. +
→ Das Bearbeitungsfenster *Neue SKU* wird angezeigt.
. Wähle die Herkunft *Neckermann.at*.
. Gib die SKU ein.
. Klicke auf *Hinzufügen*. +
→ Die SKU wird gespeichert und angezeigt.

Informationen zum Provisionsmodell und zur Produkttyp erhältst du von Neckermann.

[#1500]
== Energieeffizienz angeben

Für die Auszeichnung deiner Artikel für Neckermann gemäß der neuen Verordnung der EU zur Energieeffizienzrichtlinie sind ab 1.1.2015 Angaben zur Energieeffizienz sowie die Bereitstellung von Produktdatenblättern vorgeschrieben. Erstelle dazu folgende <<artikel/artikel-verwalten#480, Merkmale>>:

* *Energieeffizienzklasse* +
Merkmal-Typ: *Kein*
* *Energieetikett* +
Merkmal-Typ: *Datei* +
Dateiformat: z.B. *JPG* oder *PNG* (Bildformat)
* *Produktdatenblatt* +
Merkmal-Typ: *Datei* +
Dateiformat: *PDF*

[.instruction]
Merkmal Energieeffizienzklasse erstellen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Wechsele in das Tab *Neues Merkmal*.
. Gib den Namen unter *Name (intern)* ein.
. Wähle den Merkmaltyp *Kein*.
. *Speichere* die Einstellungen.

Für die Merkmale Energieetikett und Produktdatenblatt wählst du den Merkmaltyp *Datei* und das Neckermann-Merkmal *Energieetikett* bzw. *Produktdatenblatt*. Im Folgenden wird beispielhaft beschrieben, wie du das Energieetikett für Neckermann.at erstellst.

[.instruction]
Merkmal Energieetikett erstellen:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Merkmale*.
. Wechsele in das Tab *Neues Merkmal*.
. Gib den Namen unter *Backendname* ein.
. Wähle den Merkmaltyp *Datei*.
. Wähle unter *Neckermann.at EP Merkmal* das Merkmal *Energieetikett*.
. *Speichere* die Einstellungen.

Die Merkmale verknüpfst du im Tab *Merkmale* eines Artikels.

[.instruction]
Energieeffizienz-Merkmale verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Merkmale*.
. Aktiviere die soeben erstellten Merkmale *Energieeffizienzklasse*, *Energieetikett* und *Produktdatenblatt*.
. *Speichere* die Einstellungen. +
→ Die Merkmale werden in der Liste angezeigt.
. Lade beim Merkmal *Energieetikett* die Bilddatei des Energieetiketts hoch.
. Lade beim Merkmal *Produktdatenblatt* die PDF-Datei des Produktdatenblatts hoch.
. *Speichere* die Einstellungen.

*_Oder:_* Speichere das Energieetikett im Tab *Bilder* des Artikels. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Energieetikett als Bild hinterlegen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Bilder*.
. Füge die Bilddatei des Energieetiketts entweder über *Dateien auswählen* oder per Drag &amp; Drop-Funktion hinzu.
. *Speichere* die Einstellungen.
. Öffne das Menü *System » Systemeinstellungen » Märkte » Neckermann Österreich Enterprise*.
. Gib die Positionsnummer des Bildes im Bereich *Grundeinstellungen* bei der Option *Bildposition für das Energieetikett* ein.
. *Speichere* die Einstellungen.

[#1600]
== Zahlungsart aktivieren

Aktiviere die <<payment/zahlungsarten-verwalten#, Zahlungsart>> *Neckermann Payment*, wie im Folgenden beschrieben.

[.instruction]
Neckermann-Zahlungsarten aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
. Klicke auf *Neckermann Payment*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<zahlungsart-neckermann>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* die Einstellungen.

[[zahlungsart-neckermann]]
.Einstellungen der Zahlungsart
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Sprache*
| Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn Käufer im Webshop die Sprache wählen.

|*Name*
| Name eingeben, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
| Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eingeben.

|*Infoseite (Extern)*
| Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eingeben.

|*Lieferländer*
| Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in deinem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
| Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standardlogo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
| Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
| Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
| Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eingeben. *Wichtig*: Nicht in beide Felder einen Wert eingeben. +
Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *System » Systemeinstellungen » CRM » Kundenklassen* aktivierst oder deaktivierst du *erlaubte Zahlungsarten*. +
Weitere Informationen findest du im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[#1700]
== Retouren erstellen

Retouren für Neckermann erstellst du im Menü *Aufträge » Aufträge bearbeiten*. Dafür benötigst du den *Paketcode*, der sich auf dem Rücksendeschein der Retoure befindet.

[.instruction]
Retoure erstellen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag.
. Wähle im Tab *Übersicht* aus der Dropdown-Liste *Retoure...* die Option *anlegen*. +
→ Das Fenster *Retoure zum Auftrag* wird geöffnet.
. Gib den *Paketcode der Retoure* ein.
. Aktiviere unter *Artikel* in der Spalte *Übernehmen* das Kontrollkästchen.
. *Speichere* die Einstellungen. +
→ Die Retoure wird erstellt und geöffnet. Der Code ist im Tab *Einstellungen* der Retoure gespeichert.

[TIP]
.Tipp: Paketcode der Retoure
====
Der Paketcode lässt sich nicht nachträglich in der Retoure eingeben, sondern nur direkt wenn die Retoure erstellt wurde.
====

[#1800]
== Aufträge stornieren

Da für Stornierungen von z.B. einzelnen Artikeln eines Auftrages keine Möglichkeit des Löschens zur Verfügung steht, setzt du in einem solchen Fall die Menge des betreffenden Artikels auf 0. Zu jeder Stornierung muss ein Grund angegeben werden, entweder *Ware nicht auf Lager* oder *Kundenstornierung*.

[#1850]
== Neckermann-Rechnung erzeugen

Die Vorgehensweise zur Erzeugung von Neckermann-Rechnungen ist, verglichen mit den anderen Auftragsherkünften, ein Sonderfall. Deshalb gibt es in plentymarkets ein zusätzliches Menü für Neckermann-Rechnungen. Rechnungen für *Neckermann-Aufträge* werden nicht erst in deinem plentymarkets System erzeugt, wie bei Rechnungen anderer Auftragsherkünfte. Stattdessen erhält dein plentymarkets System eine spezielle Datei (pcl-Format) mit den für dich eingegangenen Aufträgen direkt von Neckermann.

Einstellungen zum Layout aller Rechnungen kannst du im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* vornehmen. Im Menü *System » Systemeinstellungen » Aufträge » Ereignisse* definierst du, welche Aktion beim Rechnungsdruck durch eine Ereignisaktion zusätzlich ausgeführt werden soll. Vergiss dabei nicht, einen Filter des Filtertyps *Herkunft* zu setzen und dort *Neckermann* auszuwählen, wenn die Aktion nur auf Aufträge von diesem Marktplatz beschränkt sein soll.

Nutze das Menü *Neckermann-Rechnungen erzeugen*, um aus den erhaltenen Neckermann-Aufträgen die von dir gewünschten Aufträge herauszufiltern und die zugehörigen Rechnungen in einer gesonderten Datei zu öffnen. Nutze den Suchfilter in diesem Bereich, um die Kriterien zu bestimmen, nach denen die Aufträge zum Rechnungsabruf ausgewählt werden.

[.instruction]
Neckermann-Rechnungen abrufen:

. Öffne das Menü *Aufträge » Fulfillment » Neckermann-Rechnungen erzeugen*.
. Stelle die gewünschten Optionen für den *Suchfilter* ein.
. Wähle unter *Aktion* einen neuen *Auftragsstatus*, der den gewählten Aufträgen nach erfolgreichem Rechnungsabruf zugewiesen werden soll.
. Nimm die Einstellungen vor. Beachte dazu <<einstellungen-neckermann-rechnungen>>.
. Klicke auf das *Zahnrad*. +
→ Eine *zip-Datei* wird erstellt, welche die zugehörigen Rechnungen aller von dir durch die Filteroptionen bestimmten Aufträge enthält.
. Nach Entpacken dieser zip-Datei werden die Rechnungen gespeichert und ausgedruckt.

[[einstellungen-neckermann-rechnungen]]
.Einstellungen für Neckermann-Rechnungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Auftragsstatus*
|*Status* wählen, in dem sich die Aufträge befinden, für die Rechnungen erzeugt werdem sollen.

|*Warenausgangsdatum*
|Datum aus dem Kalender wählen. Das Warenausgangsdatum wird nur als Filter wirksam, wenn in der Dropdown-Liste *Auftragsstatus* der Status *[7] Warenausgang gebucht* gewählt ist.

|*Eigner*
|*Eigner* der zu suchenden Aufträge oder die Option *ALLE* wählen.

|*Mandant (Shop)*
|Einen *Shop* oder die Option *ALLE* wählen.

|*Lager*
|Suche auf ein *Lager* begrenzen oder die Suche für *ALLE* Lager ausführen.

|*Limit*
|Rechnungserstellung muss auf einen der Werte im Drop-down-Menü begrenzt werden. Maximum sind 200 Rechnungen.

|*Ändere Auftragsstatus*
|Einen neuen *Auftragsstatus* wählen, der den gewählten Aufträgen nach erfolgreichem Rechnungsabruf zugewiesen werden soll oder die Option *Keine Änderung* wählen.
|====

[#1900]
== API-Log abrufen

Im Menü *Daten » API-Log* findest du eine Historie über Vorgänge, die über die Neckermann-Schnittstelle ausgeführt wurden. Die Formate *NeckermannATEP* und *NeckermannATCD* stehen dir für Neckermann zur Verfügung.

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log*.
. Wähle das Format *NeckermannATEP* aus der Dropdown-Liste *Vorgang*.
. Wähle ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wähle die Anzahl der Ergebnisse pro Seite.
. Klicke auf *Suchen*, um die Ergebnisse anzuzeigen.
