= ItemParcelServicePreset
:lang: en
include::{includedir}/_header.adoc[]
:description: Special format ItemParcelServicePreset
:position: 165

The data format **ItemParcelServicePreset** is used to import shipping profiles which are activated in the item's **Global** tab. This data format is available as a special format in the **Data exchange » Import » Dynamic import** menu. The **<<data-exchange/importing-data#, Importing data  >>** page of the manual describes how you import the data format. Create an export format in the <<data-exchange/exporting-data#30., **Data exchange » Export » Elastic export** >> menu.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the data format **ItemParcelServicePreset**. The data fields are listed in alphabetical order.

[cols="a,a"]
|====
|Field name |Explanation

|**item_id**
|Item ID

|**parcel_service_preset_id - parcel_service_preset_id5**
|IDs of the shipping profiles that are activated in the item settings
|====

__Table 1: data fields of the **ItemParcelServicePreset** data format__

