= OTTO market
:lang: en
include::{includedir}/_header.adoc[]
:keywords: OTTO market, OTTO, marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to OTTO market in your plentymarkets system.
:position: 20
:url: markets/otto/otto-market
:id: SMKVRT7

This page provides information about OTTO market, OTTO's marketplace model.

== OTTO market

OTTO market is OTTO's marketplace. You are shown as the seller of your products. You also manage the customer communication yourself.

== Setting up OTTO market in plentymarkets

OTTO market is set up with assistants. Go to *Setup » Assistants* and work through these assistants to set up the market in your plentymarkets system:

* *OTTO market basic settings*: Set up your OTTO market account in plentymarkets with this assistant.
* *OTTO market creating catalogues*: Create catalogues and catalogue templates for OTTO market with this assistant. Catalogues are used to export items to OTTO market. For further information about catalogues, refer to the <<data/exporting-data/Managing-catalogs#, Managing catalogues>> page.

=== Further settings in plentymarkets

In order to use OTTO market in plentymarkets, you have to carry out a few more settings in addition to the assistants to ensure that your items are exported properly.

* Set up the item availability in a item's *Settings* tab.
* Activate an item's variation in an item's *Settings* tab.
* Variations have to be linked with the OTTO market category group variation property.

Connecting to this market allows for the following automatic functions to take place:

* Order import every 15 minutes
* Stock and price update every 15 minutes
* Item data is updated once a day
