= OTTO market
:lang: en
include::{includedir}/_header.adoc[]
:keywords: OTTO market, OTTO, marketplace, Otto assistant, Otto category group, Otto marketplace, Otto setup, setting up Otto
:description: Multi-Channel in plentymarkets: Set up the interface to OTTO market in your plentymarkets system.
:position: 20
:url: markets/otto/otto-market
:id: SMKVRT7
:author: team-multi-channel

This page provides information about OTTO market, OTTO's marketplace model.

[#100]
== OTTO market

OTTO market is OTTO's marketplace. You are shown as the seller of your products. You also manage the customer communication yourself. +

Connecting to this market with plentymarkets allows for the following automatic processes to take place:

* Order import every 15 minutes
* Stock and price update every 15 minutes
* Item data is updated once a day


[#200]
== Setting up an account

The basic settings for OTTO market are carried out in the *Setup » Assistants » Omni-Channel* menu with the *OTTO market basic settings* assistant. With this assistant, you set up your OTTO market account in plentymarkets. +

In order to open the assistant, go to *Setup » Assistants » Omni-Channel* and click on the *OTTO market Basic settings* assistant. The assistant opens and you can start setting up your account.


[#275]
== Activating the order referrer

In order to link items, properties etc. with OTTO market, you have to activate the order referrer OTTO market in the *Setup » Orders » Order referrer* menu.

[.instruction]
Activating the order referrer for OTTO market:

. Go to *Setup » Orders » Order referrer*.
. Place a check mark next to *OTTO market*.
. *Save* (icon:save[role="green"]) the settings.


[#300]
== Setting the variation availability

You need to activate all variations that you want to sell on OTTO market. This is done in the *Availability* tab of a variation within the *Item » Edit item » Open item » Tab: Variation ID* menu.

[TIP]
.Selling all variations of an item on OTTO market
====
If you want to sell all variations of an item on OTTO market, carry out the settings below for the item's main variation. All other variations of the item then inherit the settings of the main variation.
====

[.instruction]
Activating the variation availability for OTTO market:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Open the variation that you want to sell on OTTO market.
. In the *Availability* section, active the option *Active*.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list of all available markets is displayed.
. Activate the option *OTTO market*.
. Activate the option *Web API*.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The market is added.
. *Save* (icon:save[role="green"]) the settings.

[#350]
== Setting the availability for images

The availability *OTTO market* has to be saved for an image in the *Item » Edit item » Open item » Tab: Images* menu so that item images are displayed on OTTO market.

[.instruction]
Setting the availability for images:

. Go to *Item » Edit item » Open item » Tab: Images*.
. Activate the option *OTTO market* in the *Availability* drop-down list.
. *Save* (icon:save[role="green"]) the settings. +
→ The variation image is displayed on OTTO market.


[#400]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer OTTO market. The price is displayed on OTTO market.

[.instruction]
Defining a sales price for OTTO market:

. Go to *Setup » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *OTTO market*.
. *Save* (icon:save[role="green"]) the settings.


[#450]
== Setting up the item export

Item data is exported to OTTO market vie catalogue templates. Catalogues are cerated with the *OTTO market Creating catalogues* assistant in the *Setup » Assistants » Omni-Channel* menu. For further information about catalogues, refer to the <<data/exporting-data/managing-catalogues#, Managing catalogues>> page. +

In catalogues, you link your item data saved in plentymarkets to OTTO market data fields. The mandatory fields for each OTTO category group are already mapped in the assistant. Afterwards, open the catalogue that you created with the assistant to link further optional OTTO market data fields not marked with an asterisk with item data saved in plentymarkets. This way, you can describe your items in more detail. Your items are more likely to be sold with a detailed description. For further information about the plentymarkets data sources that can be linked, refer to the <<data/exporting-data/managing-catalogues#_mapping_data_sources, Mapping data sources>> chapter.

[.instruction]
Linking data fields in the catalogue:

. Go to *Data » Catalogues*.
. Click on the OTTO market catalogue. +
→ The catalogue opens. +
→ The market’s data fields are displayed on the left-hand side. +
*Tip:* Mandatory fields are marked with an asterisk. Mandatory fields were already mapped in the *OTTO market Creating catalogues* assistant.
. Select a plentymarkets data source for the market’s data fields from the drop-down list.
. Click on *Add source* to assign another plentymarkets data source to a data field. +
→ A new line is displayed. +
*Note:* Only one value is exported even if you assign more than one data source to a data field. The data is checked in the order in which you assigned it. This means that if the first data field does not provide a value, the second data field is exported etc.
. Link the desired data fields.
. Save (icon:save[role="green"]) the settings.

An example of how to link the data field *Stock* to data saved in plentymarkets is provided below. The data field *Stock* defines the warehouse from which stock should be exported to OTTO market.

[.instruction]
Linking the data field *Stock*::

. Go to *Data » Catalogues*.
. Click on the catalogue. +
→ The catalogue opens.
. Select a plentymarkets data source for the OTTO market data field from the *Source* drop-down list. To do so, expand the plentymarkets data source *Stock*. +
→ All warehouses saved in plentymarkets are displayed in the drop-down list.
. Select the warehouse which should be used to export stock to OTTO market and click on *Select* (icon:check-square[role="green"]). +
→ *Tip:* If you would like to transfer stock from multiple warehouses to OTTO market, click on *Add source* (icon:link[role="yellow"]) and add more warehouses.
. *Save* (icon:save[role="green"]) the settings. +
→ If you do not link the data field *Stock* to a warehouse, then the sum of the net stock of all distribution warehouses (data source *Virtual warehouse*) will be exported to OTTO market.

[IMPORTANT]
====
.Link all mandatory fields
The mandatory fields for the templates are marked with an asterisk. To make sure that all necessary item data is provided, link at least the mandatory fields. For OTTO market, mandatory fields are already linked in the *OTTO market Creating catalogues* assistant.
====


[#475]
== Linking variations with OTTO category groups

After you created a catalogue template for OTTO market with the *OTTO market Creating catalogues* assistant or manually, the property *OTTO category group* is created in your plentymarkets system. A new selection value is added to the *OTTO category group* property for each OTTO category group selected in the *Name and category group* step of the assistant. In order for your variations to be exported in the appropriate catalogue, they have to be linked to the *OTTO category group* property in the *Properties* tab of a variation.

[.instruction]
Linking a variation with an OTTO category group:

. Go to *Item » Edit item »* _Open item_.
. Open the *Variations* tab.
. Open the variation that should be linked.
. Open the *Properties* tab.
. In the *Variation properties* section, select the property *OTTO category group* from the *Properties* drop-down list and click on *Add* (icon:plus-square[role="green"]). +
→ The property is added.
. Select the desired category group from the *Value* drop-down list for the *OTTO category group* property. +
→ The variation will be exported in this catalogue. +
→ *Example:* If you select the value *Betten* (Beds), then the variation will be exported in the in the catalogue for the OTTO category group *Betten*.
. *Save* (icon:save[role="green"]) the settings.


[#500]
== Setting up event procedures

Set up <<automation/event-procedures#, event procedures>> to automatically inform OTTO market about order status changes. The following event procedures can be set up for OTTO market:

* Auftragsbestätigung an OTTO melden (Send order confirmation to OTTO)
* Versandinformation an OTTO melden (Send shipping confirmation to OTTO)
* Auftragsstornierung an OTTO melden (Send order cancellation to OTTO)
* Retoure an OTTO melden (Send return to OTTO)
* Ablehnung der Retoure an OTTO melden (Send rejection of return to OTTO)

How to set up the event procedures in plentymarkets is described in the following chapters.

[#550]
=== Generating a DHL return label

When OTTO market orders are imported into your plentymarkets system, then DHL return labels must be generated for those orders before the shipping confirmation is sent to OTTO market. The procedure *Generate DHL return label* automatically creates a tracking number for a return (retTrackingNumber) which is saved for the order. This is to ensure that a tracking number exists if customers wish to return an item. +

To ensure that the tracking number is sent to OTTO market along with the order confirmation, you have to create two event procedures which are triggered one after the other: 1. *Generate DHL Retoure Online label* and 2. *Auftragsbestätigung an OTTO melden* (Send order confirmation to OTTO).

*Note:* At the moment, the return label can only be generated with DHL. Further shipping service providers will be available soon.

[TIP]
.Install DHL Retoure Online plugin
====
In order to generate a DHL return label, the *DHL Retoure Online* plugin has to be installed, activated and set up in your plentymarkets system. The plugin is available in the link:https://marketplace.plentymarkets.com/en/plugins/integration/dhlretoureonline_6714[plentyMarketplace^].
====

How to set up the <<automation/event-procedures#, event procedure>> to create a DHL return label is described below.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<dhl-return-label-otto>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
. Carry out further settings as described in <<dhl-return-label-otto>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[dhl-return-label-otto]]
.Event procedure to create a DHL return label
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*New order*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Referrer*
|*OTTO market*

|*Procedure*
|*Plugins > Generate DHL Retoure Online label*
|
|====

[#600]
=== Sending an order confirmation to OTTO

The event procedure for sending an order confirmation to OTTO has to be triggered after a DHL return label was generated. How to set up the <<automation/event-procedures#, event procedure>> for sending an order confirmation to OTTO is described below.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<order-confirmation-otto>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
. Carry out further settings as described in <<order-confirmation-otto>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[order-confirmation-otto]]
.Event procedure to send an order confirmation to OTTO market
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Status change: select a status before shipping as needed*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Referrer*
|*OTTO market*

|*Procedure*
|*Plugins > Auftragsbestätigung an OTTO melden* (Send order confirmation to OTTO)
|
|====

[#700]
=== Sending a shipping confirmation to OTTO

Set up an <<automation/event-procedures#, event procedure>> to inform OTTO market that an item has been shipped.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<shipping-confirmation-otto>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
. Carry out further settings as described in <<shipping-confirmation-otto>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[shipping-confirmation-otto]]
.Event procedure to send a shipping confirmation to OTTO market
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Status change: e.g. status [7] Shipped*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Referrer*
|*OTTO market*

|*Procedure*
|*Plugins > Versandinformation an OTTO melden* (Send shipping confirmation to OTTO)
|
|====

[#800]
=== Sending an order cancellation to OTTO

Set up an <<automation/event-procedures#, event procedure>> to inform OTTO market about the cancellation of an order. It might be required to cancel orders because of different reasons. For example, if you as seller cancel an order, select *Status [8] Cancelled]*. If the customer cancels an order, select *Status [8.1] Cancelled by customer*.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<order-cancellation-otto>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
. Carry out further settings as described in <<order-cancellation-otto>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[order-cancellation-otto]]
.Event procedure to send an order cancellation to OTTO market
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order change: Status change*
|*[8] Cancelled* or *[8.1] Cancelled by customer*

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*OTTO market*

|*Procedure*
|*Plugins > Auftragsstornierung an OTTO melden* (Send order cancellation to OTTO)
|
|====

[#900]
=== Sending a return to OTTO

Set up an <<automation/event-procedures#, event procedure>> to inform OTTO market about returns.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<return-otto>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
. Carry out further settings as described in <<return-otto>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[return-otto]]
.Event procedure to send returns to OTTO market
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Order generation: New return*
|

|*Filter 1*
|*Order &gt; Order type*
|*Return*

|*Filter 2*
|*Order &gt; Referrer*
|*OTTO market*

|*Procedure*
|*Plugins > Retoure an OTTO melden* (Send return to OTTO)
|
|====

[#1000]
=== Sending rejection of return to OTTO

Set up an <<automation/event-procedures#, event procedure>> to inform OTTO market about the rejection of a return.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<rejection-return-otto>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
. Carry out further settings as described in <<rejection-return-otto>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[rejection-return-otto]]
.Event procedure to send the rejection of a return to OTTO market
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|Select an event, e.g. *Order change: Status change* +
*Note:* Select a status that suits your workflow. For example, you can create the status *[8.2] Reject OTTO return*.
|

|*Filter 1*
|*Order &gt; Order type*
|*Return*

|*Filter 2*
|*Order &gt; Referrer*
|*OTTO market*

|*Procedure*
|*Plugins > Ablehnung der Retoure an OTTO melden* (Send rejection of return to OTTO)
|
|====
