= Beschränkung von gleichzeitig eingeloggten Benutzern im Backend
:lang: de
include::{includedir}/_header.adoc[]
:keywords: gleichzeitig eingeloggt, Benutzer, User, Tarif, Tarifmodell, Tarifwechsel, mehrere Benutzer, zu viele Benutzer, zu viele User, zu viele Nutzer, Backend
:position: 10

Aufgrund der neuen Tarifmodelle gibt es für Kunden, die neue Verträge abschließen oder einen Tarifwechsel vornehmen, eine Änderung bezüglich der gleichzeitig eingeloggten Benutzer. Je nach Tarif besteht eine bestimmte Beschränkung der Anzahl dieser. *Kunden mit einem bestehenden Tarif sind davon nicht betroffen*.

=== Überschreitung der maximalen Anzahl von gleichzeitig eingeloggten Benutzern

Wird die Anzahl der gleichzeitig eingeloggten Benutzer erreicht bzw. überschritten, bekommt der Benutzer eine der beiden folgenden Fehlermeldungen:

*Für Variable Benutzer*:
Zu viele Benutzer. Nur x Benutzer können gleichzeitig im Backend eingeloggt sein. Versuchen Sie es erneut oder kontaktieren Sie den Administrator.

*Für Admins*:
Zu viele Benutzer. Nur x Benutzer können gleichzeitig im Backend eingeloggt sein. Führen Sie ein Upgrade für Ihren Vertrag durch oder öffnen Sie das Session-Verwaltung.

[[tabelle-beschraenkung-je-tarif]]
.Beschränkung je nach Tarif
[cols="1,3"]
|====
|Tarif|Maximale Anzahl von eingeloggten Benutzern

|*STARTER Zero*
|bis zu 3

|*STARTER Basic*
|bis zu 5

|*STARTER Advanced*
|bis zu 10

|*PRO Classic*
|bis zu 50

|*PRO Flex*
|bis zu 100

|*PLUS*
|keine Beschränkung
|====

=== Was ist zu tun, wenn die maximale Anzahl der gleichzeitig eingeloggten Benutzer erreicht ist?

Über den Link in der Fehlermeldung wird der Admin direkt zum Session-Verwaltung weitergeleitet. Dieses ermöglicht es dem Admin, die bereits laufenden Sessions zu beenden und so den Login eines anderes Benutzers zu ermöglichen. Der Login ist für 10 Minuten gültig. Danach wird der Admin automatisch wieder ausgeloggt. +
Zur Session-Verwaltung gelangt man im Backend über das Menü *System » Einstellungen » Benutzer* oder über das User-Icon oben rechts.
