= My account
:lang: en
// include::{includedir}/_header.adoc[]
:keywords: My account, Web design, CMS
:position: 90

*CMS » Web design » My account*

== Content of this chapter

This chapter provides you with detailed information about customizing the *My account* area of the online store.

The *my account* area is only accessible to registered store customers. Here, customers can view all of the purchases that they made and all of the information that they entered, e.g. their contact information.

Go to *CMS » Web design » My account* to design the frontend. Various submenus allow you to precisely configure each area.

== Basic settings

The <<omni-channel/online-store/setting-up-clients/my-account#, System » Client » Select client » My Account » Settings>> menu contains several basic settings that are relevant to the my account area of your online store. For example, you can activate or deactivate a few optional account areas.

== My account: Editing the design

This section has already been preconfigured. However, you have a wide range of possibilities for changing it.

[TIP]
.CSS modifications
====
You can modify the CSS. However, preconfigured CSS rules are already saved in plentymarkets. You can find them by going to *CMS » Web design*, opening the *Template* folder and then opening the *CSS* folder. The CSS rules for the My account area are saved under *CSSMyAccount*.
====

You can individually customize the following submenus within the *My account* tab:

* *Login*
* *My account*
* *Customer data*
* *Personal data*
* *Contact information*
* *Bank information*
* *Change password*

* *Newsletter*
* *Order history*
* *Order overview*
* *Change the delivery address*
* *Change shipping method*
* *Change payment method*
* *Change item*

* *Return*

* *Subscription history*
* *Subscription overview*
* *Change subscription*
* *Change item*

* *Watchlist*
* *Wish list*
* *Tickets*
* *Coupons*
* *Time account*
* *Documents*
* *Data export*

Some fields and settings appear in several of the menus and submenus listed above. These recurring fields and settings will be explained below. Individual functions are found in the explanations of the corresponding menu.

=== Recurring settings

Settings that appear in several of the my account submenus will be explained here. You may already be familiar with some of these settings, as they also appear in the *Order process* area.

.explanations of the recurring settings in the submenus
[cols="1,3"]
|====
|Setting |Explanation

|Title
|The menu heading as it should be displayed to customers in the online store.

|Text in front of &amp; text behind
|Enter notes or welcome texts that are appropriate for the menu. +
These two fields appear before and after all of the other menu items. In other words, *Text in front of* appears directly below the title and *Text behind* appears after all of the other menu items.

|Position (main menu item)
|Determine which order the main menus (first level menus) should be displayed in by selecting the position number from the drop-down list.

|Position (submenu)
|*Container 1*: Is displayed on the left in the order overview. +
*Container 2*: Is displayed on the right in the order overview. +
Use position numbers to specify the order. +
For example, if *Container 1* was selected for all elements and consecutive numbers were used, then the elements will appear one underneath the other on the left side. They will be displayed in the order specified by the position number. +
Use both containers to position the elements next to each other.

|Position (item submenu)
|Position the item submenu on the *bottom* or *top*. +
*Top* = Above the rest of the submenus in this area +
*Bottom* = Below these submenus

|Display
|*Directly show* = The entire content of a menu item will be displayed in the online store. The menu is already expanded. +
*Show after click* = Only the title of the menu will be displayed. All of the information will be displayed after the customer clicks on the title.

|Show details
|The text that you enter here is linked in the online store and directs the customers to a detailed layout.

|No item found
|The note that you enter here will be displayed to the customer, e.g. if there are no items on their watchlist or wish list.
|====


=== Individual settings of my account submenus

The settings in the submenus were given self-explanatory names. The text that you enter into the text fields will be displayed to your customers in the online store.

.explanations of the settings for the submenus
[cols="1,3"]
|====
|Menu item |Explanation

|CSS My account
|In this section, you can use CSS to design the layout of customer accounts. Standard CSS formatting can be used to set up general CSS rules for customer accounts. The entire CSS code for the *My account* area can also be entered here. Alternatively, only enter the portion of the code that is valid for all areas. Then you will have to enter information that is specific to individual areas in the *CSS* field for that area.

|Login
|Customers will see the information that you enter here when they access the online store and click on the *My account* tab. *CSS* formatting is entered by default. CSS can be used to change the way that information is arranged in this menu. +
*Password strength* +
6 characters are sufficient for the store password. The security level in the store is lower than in the admin area. This also means that a simple combination of letters and numbers is sufficient for the login password. For further information, refer to the <<basics/working-with-plentymarkets/manage-users#1, Creating a user>> page of the manual.

|My account
|The customer lands here after entering their login details and clicking on *Log in*. CSS formatting is entered by default. You can save a note above this button (*Text in front of*). Below that, the customer will see different submenus relating to their account. These are the first level submenus of the *my account area*, e.g. the *customer data* and *order history*. CSS can be used to change the way that information is arranged.

|Customer data
|CSS formatting is entered by default. The data that is entered here comes e.g. from the information that the customer entered during previous purchases. The customer data is grouped in several submenus. Under *personal data*, the customer sees the invoice address that they entered. Under *contact information*, the customer sees the email address that they used to log in. Customers can make changes to this data by clicking on *Change*. +
A new window opens up when a customer clicks on the *Change* button. This window is edited in the customer data submenus. The *Delivery address* window is edited in the corresponding order history submenu.

|Newsletter
|The title for the <<crm/sending-newsletters#, Newsletter>> area, the position and the way the newsletter area should be displayed.

|Order history
a| Customers can use the fields *Order ID* and *Select time period* to search for an order within their own account. The fields *Order date*, *Recipient*, *Show details*, *Status* and *Estimated shipping* will be individually displayed in the history of each order.
* *Order overview* +
The order overview is the detailed layout of a specific order with all of the data that belongs to it.
* *Delivery address* +
In this submenu, configure and name the entry fields that the customer will see. These entry fields will also be used for the customer data.
* *Shipping method* +
In this submenu, configure and name the entry fields that the customer will see regarding the *shipping method*.
* *Payment method* +
In this submenu, configure and name the entry fields that the customer will see regarding the *payment method*.
* *Item* +
In this submenu, configure and name the entry fields that the customer will see regarding the *items*.

* *Return* +
Once the customer has paid for an order, it has been shipped and is in *status 7*, then the button *send back item* will appear in the customer account. If the customer clicks on this button, then a menu will open up. This menu is configured here. The *reason for return* field is a drop-down list. Save the reasons that are available for the customer to select by going to <<order-processing/orders/managing-sales-orders#return, System » Orders » Order types » Return>>.

|Subscription history
|Customers can use the fields *Order number* and *Select time period* to search for a subscription within their own account. The fields *Recipient*, *First shipment* etc. will be displayed for every subscription. By clicking on *Show details*, the customer will see all of the information about a specific subscription. +
*Subscription overview* +
The subscription overview is the detailed layout of a specific subscription. The position and title of the individual submenus can be changed here, as well as the shipping method and items of this area. The actual entry fields are configured in the submenus of the order overview.

|Watchlist
|The <<omni-channel/online-store/setting-up-clients/my-account#, watchlist>> function is activated by going to *System » Client » Select client » My Account » Settings*. The *watchlist* function allows those customers who have an account to save a list of items in the store that they want to remember or buy at a later point in time. An item is only removed from the watchlist if it is deleted or moved to the shopping cart. +
*Watchlist button* +
If the watchlist function is not activated, then the *watchlist button* should also be removed from the store layout. Go to *CMS » Web design » Folder: Layout* and select *ItemViewSingleItem* from the *ItemView templates*. Delete the corresponding code.

|Wish list
|The <<omni-channel/online-store/setting-up-clients/my-account#, wish list>> function is activated by going to *System » Client » Select client » My Account » Settings*. The wish list function allows those customers who have an account to save a list of items in the store that they may want to buy at a later point in time, ask for as gifts or remember for another reason. A wish list is usually created in order to be shown to other people. An item is only removed from the wish list if it is deleted or moved to the shopping cart. +
*Wish list button* +
If the wish list function is not activated, then the *wish list button* should also be removed from the store layout. Go to *CMS » Web design » Folder: Layout* and select *ItemViewSingleItem* from the *ItemView templates*. Delete the corresponding code.

|Tickets
|This menu item is only displayed if the <<crm/using-the-ticket-system#, ticket system>> was booked as an add-on. The plentymarkets module "Ticket system STARTER" can be ordered free of charge. +
In the menu, configure and name the entry fields that are visible to your customers in the *Tickets* area.

|Coupons
|The *coupon* function is activated by going to *System » Client » Select client » My Account » Settings*.

|Documents
|If documents were uploaded under *CMS » Documents* and *customers* were given the *right* to view these documents, then customers will be able to see these documents here.

|Data export
|This function is used, e.g. in order to provide a list of items to corporate customers. Go to *Data » Dynamic export* and configure a new data format. Click on the data format's Filter tab and place a check mark in front of the words *Export for customer class*. This will activate the filter. Under *value*, select the customer class that the data format should be available for. If a customer belongs to the customer class that the data was made available for, then they will see the corresponding data in the *data export* menu of their customer account.
|====


[IMPORTANT]
.jQuery
====
jQuery functions are integrated in this area. For further information about working with or expanding these functions, refer to the <<omni-channel/online-store/setting-up-clients/cms#web-design-basic-information-about-syntax-jquery, jQuery>> page of the manual.
====
