= Setting up Neckermann.at
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Neckermann.at, marketplace, market
:description: Multi-Channel in plentymarkets: Set up the interface to the market Neckermann Austria in your plentymarkets system.
:position: 10

Neckermann Austria enables you to present your products on the market *neckermann.at*. On this page, you will find detailed information about the settings you need to carry out in order to set up the market Neckermann Austria in your plentymarkets system. Pay attention to this information in order to ensure the smoothest link-up possible with this market.

[#100]
== Registering with Neckermann.at

If you are interested in the partner programme of link:http://www.neckermann.at/[Neckermann Austria^], contact Neckermann.at directly. Please note that the neckermann.at website is currently only available in German.

.Contact person
[cols="1,3"]
|====
|Contact person |Email address

|*René Riebenbauer* - Head of Sales Platform and Content Management
|link:mailto:rene.riebenbauer@neckermann.at[rene.riebenbauer@neckermann.at]
|====

[#200]
== Setting up Neckermann.at in plentymarkets

After joining the Neckermann partner programme, use your access data to set up the market in plentymarkets. You can integrate the platform Neckermann.at Enterprise into plentymarkets.
// Neckermann.at Cross-Docking
To set up Neckermann.at Enterprise in plentymarkets, proceed as follows.
// Set up Neckermann.at Cross-Docking in the same way.

[.instruction]
Setting up Neckermann.at in plentymarkets:

.  Open the *System » System settings » Markets » Neckermann » Neckermann Austria Enterprise* menu.
. Expand the section *Basic settings*.
.  Carry out the settings. Pay attention to the explanations given in table 1.
. *Save* the settings.

.Basic settings for the market Neckermann.at
[cols="1,3"]
|====
|Setting |Explanation

|*Interface mode*
|Select the interface mode. +
*Test mode ON* = Select while you carry out settings and prepare the interface and items. +
*Live mode ON* = Select once you are sure that all settings have been carried out correctly.

2+|Sales partner information

|*Partner ID*
|Enter the ID that you have received from Neckermann.

|*Company name*
|Enter the name of the company or the online store.

|*Surname, first name (contact person);  +
Telephone number (contact person); +
Email address (contact person)*
|Enter the contact person's name, telephone number and email address.

2+|Item settings

|*Standard tax rate*
|Select *10%* or *20%*.

|*Reduced tax rate*
|Select *7%* or *19%*.

|*Item name*
|Select a text field that is transferred to Neckermann as the item name.

|*Item name (maximum length)*
|Select *35 characters* or *65 characters*.

|*Item preview text*
|Select a text field that is transferred to Neckermann as the item preview text.

|*Item preview text (maximum length)*
|Select *30 characters* or *50 characters*.

|*Short item text*
|Select a text field that is transferred to Neckermann as short item text.

|*Item description*
|Select a text field that is transferred to Neckermann as the item description.

|*Transfer item without assigning it to a brand*
|*No* = Items are transferred and assigned to a brand by default. +
*Yes* = Items are transferred without being assigned to a brand.

|*Image position for energy label*
|Enter the image position of the item image if the energy label is saved as an item image instead of as a property. For further information about the energy label, refer to the <<omni-channel/multi-channel/neckermann/neckermann-at-setup#1500, Providing information on the energy efficiency>> chapter.

|*Transfer cross-selling*
|*No* = Cross-selling settings are not transferred by default. +
*Yes* = Cross-selling settings are transferred.

|*Transfer RRP*
|*No* = RRP is not transferred by default. +
*Yes* = RRP is transferred.

|*Item dimensions saved in the item data*
|Select the item dimensions.

|*Transfer client (store) ID?*
|*No* = The ID is not transferred by default. +
*Yes* = The ID is transferred.

|*Standard commission model*
|Select the commission model that you received from Neckermann.

|*Stock buffer*
|The transferred stock is reduced by the entered value. This ensures that an item cannot be completely sold out on this market. +
*Example*: For an item with a stock of 50 and a stock buffer of 10, the value 40 is transferred as stock. For further information, refer to the <<en/stock-management/managing-stocks, Stock>> page of the manual.

|*Delivery periods*
|*Standard delivery time* = Enter the delivery time in days. The number of days you enter here is the standard delivery time that most of your shipments require. +
*Item delivery time 1 - 5* = Enter the delivery time in days for each option. Set up the options for item availability in the <<item/managing-items#190, System » System settings » Item » Availability>> menu.

|*Feature list*
|Select a text field or *Do not transfer*.

|*Transfer item number*
|*No* = The item number is not transferred. +
*Yes* = The item number is transferred during item export. A maximum of 20 characters will be transferred.

|*Overwrite the availability of items that are not limited to stock, if the stock is 0?*
|*Yes, with item availability 1 bis 5* = Overwrite the availability with the value of the item availability 1 to 5 (see delivery periods).  +
*No* = Do not overwrite the availability.

|*Stock quantity for items that are not limited to stock, if the stock is 0*
|Enter the stock quantity that should be displayed if the stock is missing.

2+|Order settings

|*Book orders as not paid for*
|*Yes* = In the default setting, orders are *unpaid* when they arrive in the system. This is because payment processing takes place at a later point in time. +
*No* = Orders are booked as *paid*.

|*Save package number*
|*Yes* = The package number is transferred by default. +
*No* = The package number is not transferred.
|====

Connecting to this market allows for the following automatic functions to take place:

* Daily item export
* Hourly stock synchronisation
* Hourly order import
* Hourly forwarding of shipping confirmations
* Hourly forwarding of returns
* Hourly forwarding of cancellations

[WARNING]
.Transfer of package numbers
====
Every single Neckermann order must not possess more than one package number. If this precondition is not fulfilled, the orders concerned are not forwarded to Neckermann!
====

[#250]
== Activating an order referrer

In order to link items, properties etc. with Neckermann.at, you have to activate the order referrer Neckermann.at in the menu *System » System settings » Orders » Order referrer*.

[.instruction]
Activating the order referrer for Neckermann.at:

. Go to *System » System settings » Orders » Order referrer*.
. Place a check mark next to *Neckermann.at*.
. *Save* the settings.

[#300]
== Setting the order status

Set the order statuses for cancellations and determine when returns are forwarded to Neckermann.

[.instruction]
Setting the order status:

.  Open the *System » System settings » Markets » Neckermann Austria Enterprise* menu.
. Expand the section *Order status*.
.  Carry out the settings. Pay attention to the explanations given in table 2.
. *Save* the settings.

.Setting the order status
[cols="1,3"]
|====
|Setting |Explanation

|*Order status for total cancellation "stock cancellation"*
|Select a status, e.g. *[8] Cancelled*, *[9] Return* or *[10] Warranty*.

|*Order status for total cancellation "customer cancellation"*
|Select a status, e.g. *[8] Cancelled*, *[9] Return* or *[10] Warranty*.

|*Report returns when they reach status*
|Select a status, e.g. *[9] Return*.
|====

[#400]
== Setting up FTP server access

Set up your FTP server access in this chapter. Neckermann requires FTP server access for importing orders and invoices.

[.instruction]
Setting up FTP server access:

.  Open the *System » System settings » Markets » Neckermann Austria Enterprise* menu.
. Expand the section *FTP server*.
.  Enter the access data that you have received from Neckermann.
. *Save* the settings.

[#500]
== Importing components

Components of the market Neckermann correspond to the properties in plentymarkets. Properties in plentymarkets must be linked to Neckermann components. This is done by uploading a CSV file which contains the Neckermann components. You will receive this file after having closed a contract with Neckermann.

[.instruction]
Importing Neckermann components:

. Open the file from Neckermann.
. Select and copy the columns *COMPONENT_ID* and *COMPONENT_NAME*.
. Insert the columns into a new file in a spreadsheet program.
. Save the file in CSV format on your computer.
. Open the *System » System settings » Markets » Neckermann Austria Enterprise* menu.
. Expand the section *Component import*.
. Select the field separator.
. Click on *Select file*.
. Open the CSV file.
. *Save* the settings. +
→ The Neckermann components are available in the drop-down lists of properties.

[#600]
== Linking properties

In the next step, link your <<en/item/managing-items#480, properties>> with the Neckermann components.

[.instruction]
Linking properties:

. Go to *System » System settings » Item » Properties*.
. Expand a property.
. Select the Neckermann component from the *Neckermann.at EP component* drop-down list.
. *Save* the settings.

[#700]
== Importing logos

Neckermann provides you with various logos, e.g. for features or characteristics that designate quality. The import is done by uploading a CSV file which contains the Neckermann data. Link logos in the same way as you link Neckermann components.

[.instruction]
Importing Neckermann logos:

. Open the file from Neckermann.
. Select and copy the columns *LOGO_ID*, *LOGO_DESCRIPTION* and *Short description*.
. Insert the columns into a new file in a spreadsheet program. The file name must be *LOGO_ID;LOGO_NAME;SHORT_NAME*.
. Save the file in CSV format on your computer.
. Open the *System » System settings » Markets » Neckermann Austria Enterprise* menu.
. Expand the section *Import info logo*.
. Select the field separator.
. Click on *Select file*.
. Open the CSV file.
. *Save* the settings. +
→ The Neckermann logos are now available in the drop-down lists of properties.

[#800]
== Linking categories

Neckermann provides you with a file which contains the categories that need to be assigned to the categories of your online store. The categories are then linked and further items from the linked category are assigned automatically.

[.instruction]
Linking categories:

. Open the *System » System settings » Markets » Neckermann Austria Enterprise* menu.
. Click on the *Link categories* tab.
. Enter the categories into the *Neckermann category ID* column.
. *Save* the settings.

[#900]
== Activating primary categories

If you have linked one item to several different categories, e.g. if you are using different category links for different markets, then you can activate the primary category in the *Categories* tab of an item. If you do not activate a primary category, the first category is automatically used as the primary category.

[.instruction]
Activating the primary category:

. Go to *Item » Edit item*.
. Open an item.
. Open the *Categories* tab. +
→ Primary categories are only available under *Category links* if the market *Neckermann* is activated.
. Activate a primary category.
. *Save* the settings.

[#1000]
== Linking attributes

If you have created <<en/item/managing-items#390, attributes>> in your plentymarkets system, you have to link these attributes with Neckermann. To do so, you have to import the <<en/omni-channel/multi-channel/neckermann-at#50, Neckermann components>> first. Proceed as described below to link the attribute Colour with Neckermann. Link further attributes in the same way.

[.instruction]
Linking attributes:

. Go to *System » System settings » Item » Attributes*. +
→ An overview of all existing attributes opens.
. Expand the attribute *Colour*.
. Open the *Market variation* tab.
. Select the option *Neckermann.at Enterprise* from the *Market* drop-down list. +
→ An additional drop-down list *Neckermann.at Enterprise* is displayed below.
. Select the attribute *Colour* from the *Neckermann.at Enterprise* drop-down list.
. Enter values into the column *Neckermann.at Enterprise* under *Market variation*.
. *Save* the settings.

[#1100]
== Linking manufacturers

Brand IDs for Neckermann.at are imported via the dynamic data exchange.

[.instruction]
Importing brand Ids from Neckermann.at:

. Go to *Data » Dynamic export » Tab: New data format*.
. Select the setting *Producer* under *Data format type*.
. Enter a name.
. Activate the fields *ProducerID*, *ProducerName* and *ProducerNeckermannID_AT_EP* or *ProducerNeckermannID_AT_CD*.
. *Save* the settings. +
→ The *Edit data format* tab opens.
. Expand the data format.
. Click on *Export data*.
. Save the CSV file on your computer.
. Enter the corresponding manufacturer IDs into the *ProducerNeckermannID* column of the CSV file. +
→ The IDs can be found in the file you received from Neckermann.
. Go to *Data » Dynamic import*.
. Select the field separator.
. Select you data format under *Format*.
. Click on *Select file*.
. Open the CSV file.
. Click on *Import*. +
→ After having imported the brand IDs, you can find the Neckermann ID of a manufacturer in the *System » System settings » Item » Manufacturers* menu.

[IMPORTANT]
.Format of the CSV file
====
The CSV file must not have a header. The first column contains the manufacturer ID and the second column contains the Neckermann brand IDs. Each manufacturer ID in the first column is assigned to the corresponding brand ID in the second column.
====

[#1200]
== Displaying exported items

Search for items that you have already transferred to Neckermann in the *System » System settings » Markets » Neckermann Austria Enterprise » Tab: Transferred items* menu. Enter the item ID, the name or the Neckermann number into the search field to search for specific items or leave the search field empty and click on Item search to display all results.

[#1300]
== Displaying error reports

All operations relating to the market Neckermann are recorded in your plentymarkets system. You can retrieve error reports containing a list of all error messages and notes with the corresponding IDs. In the *Error reports* menu, all errors related to your stock used for Neckermann are displayed. The following types of errors are distinguished:

* *Note*: A note is displayed.
* *Warning*: In case of warnings, all items are imported.
* *Error*: In case of errors, no faulty items are imported.
* *Critical error*: In case of critical errors, no items are imported.

[.instruction]
Retrieving error reports:

. Open the *System » System settings » Markets » Neckermann Austria Enterprise* menu.
. Open the *Error reports* tab.
. Click on *Retrieve error reports*. +
→ The error reports are retrieved and displayed.

The list *Latest error reports* provides information about type and number of errors for the following data types:

* *Media (images)*: Information about media files.
* *Catalogue*: Information about the catalogue and all included items of a seller.
* *Stock synchronisation*: Information about the hourly stock synchronisation and price synchronisation.

In case of errors due to incorrect item data occurring during the item export from plentymarkets, information about the affected item as well as the error type can be found in the error message. Fix the error and check whether there are additional error messages after you have carried out the next automatic item export.

[TIP]
.Description of error messages
====
For further information about error messages, contact Neckermann. Ask your Neckermann contact person, if needed.
====

[#1400]
== Setting the item availability

Items have to be available for Neckermann.at. This is done in the *Availability* tab of an item within the <<en/item/managing-items#170, Item » Edit item » Open item » Tab: Variation ID>> menu.

[.instruction]
Setting the item availability for Neckermann.at:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Activate Neckermann.at Enterprise.
. Activate the option Web API.
. Click on *Add*. +
→ The market is added.
. *Save* the settings.
. Open the *Multi-Channel* tab.
. Select a *commission model*.
. Select an *item type*.
. *Save* the settings.

The availability for variations can be individually edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

[#1450]
==  Defining SKU manually

Add SKUs manually for specific referrers in the menu <<en/item/managing-items#170, Item » Edit item » Open item » Tab: Variation ID » Tab: Availability>> if needed.

[.instruction]
Adding SKU

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
.  Click on the *Availability* tab.
.  Click on *Add* in the section *SKU*. +
→ The window *New SKU* is displayed.
.  Select the referrer *Neckermann.at*.
.  Enter the SKU.
.  Click on *Add*. +
→ The SKU is saved and displayed.

Information about the commission model and the item type is provided by Neckermann.

[#1500]
== Providing information on the energy efficiency

To comply with EU regulations on energy efficiency that came into force on 1 January 2015, you have to provide information on the energy efficiency of certain items to sell them on Neckermann. In addition, you have to make product data sheets available to potential buyers of these items. Create the following <<en/item/managing-items#480, properties>> to comply with these EU regulations:

* *Energy efficiency class* +
Property type: *No*
* *Energy label* +
Property type: *File* +
File format: e.g. *JPG* or *PNG* (image format)
* *Product data sheet* +
Property type: *File* +
File format: *PDF*

[.instruction]
Creating the property energy efficiency class:

. Go to *System » System settings » Item » Properties*.
. Open the *New Property* tab.
. Enter the name in the *Name (internal)* field.
. Select the property type *No*.
. *Save* the settings.

Select the property type *File* and the Neckermann property *Energy label* or *Product data sheet* for the properties Energy label and Product data sheet. The following example describes how to create the energy label for Neckermann.at.

[.instruction]
Creating the property energy label:

. Go to *System » System settings » Item » Properties*.
. Open the *New Property* tab.
. Enter the name in the *Name (internal)* field.
. Select the property type *File*.
. Select the property *Energy label* under *Neckermann.at EP property*.
. *Save* the settings.

Link the properties in the <<en/item/managing-items#80, Properties>> tab of an item.

[.instruction]
Linking energy efficiency properties:

. Go to *Item » Edit item*.
. Open the item.
. Open the *Properties* tab.
. Activate the properties *Energy efficiency class*, *Energy label* and *Product data sheet* that you have just created.
. *Save* the settings. +
→ The properties are displayed in the list.
. Upload the image file of the energy label to the *Energy label* property.
. Upload the PDF file of the product data sheet to the *Product data sheet* property.
. *Save* the settings.

Instead of linking the *Energy label* property, you can also upload the energy label file to the <<en/item/managing-items#90, Images>> tab of the item. To do so, proceed as follows.

[.instruction]
Uploading the energy label as an image:

. Go to *Item » Edit item*.
. Open the item.
. Open the *Images* tab.
. Add the image file of the energy label either via *Select files* or via the drag & drop function.
. *Save* the settings.
. Open the *System » System settings » Markets » Neckermann Austria Enterprise* menu.
. In the *Basic settings* section, enter the image's position number into *Image position for energy label* field.
. *Save* the settings.

[#1600]
== Activating the payment method

Activate the <<payment/managing-payment-methods, payment method>> *Neckermann Payment* as described below.

[.instruction]
Activating the Neckermann payment method:

.  Go to *System » System settings » Orders » Payment » Methods*.
.  Place a check mark next to the setting *Also show inactive*.
.  Open the folder *International*.
.  Click on *Neckermann Payment*. +
→ The *Settings* tab opens.
.  Carry out the settings. Pay attention to the information given in table 3.
.  Place a check mark next to the option *Active*.
. *Save* the settings.

.Settings for the payment method
[cols="1,3"]
|====
| Setting | Explanation

|*Language*
| The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo* and *Upload logo*. This makes it possible to enter values for these options in various languages. The values for a language are activated as soon as a buyer selects the language in the online store.

|*Name*
| Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
| Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
| If you have selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
| Do not select a country of delivery. +
 You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely set up.

|*Logo*
| Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method will be displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

|*Logo view*
| If *Show upload logo* has been selected from the *Logo* drop-down list, then the logo that has been uploaded is displayed here.

|*Upload logo*
| If *Show upload logo* was selected from the *Logo* drop-down list, you can upload an external logo here. +
 Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|*Priority*
| Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
| If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. *Important*: Do not enter a value into both fields. +
For further information, refer to the <<en/basics/statistics, Statistics>> page of the manual. For an example of flat rate and percentage costs, refer to the <<payment/managing-payment-methods#, Managing payment methods>> page of the manual.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *System » System settings » CRM » Classes* to activate or deactivate *Permitted payment methods*. +
For further information, refer to the <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter of the manual.
====

For further information, refer to the <<payment/managing-payment-methods#, Payment methods>> page of the manual.

[#1700]
== Creating returns

Create returns for Neckermann in the menu *Orders » Edit orders*. The *package code* which can be found on the return label is required.

[.instruction]
Creating returns:

. Go to *Orders » Edit orders*.
. Open the order.
. Select the option *create* from the *Return...* drop-down list in the *Overview* tab. +
→ The *Return for the order* window opens.
. Enter the *package code of the return*.
. Place a check mark in the *Accept* column under *Item*.
. *Save* the settings. +
→ The return is created and opened. The code is saved in the return's *Settings* tab.

[TIP]
.Tip: Package code of the return
====
The package code cannot be entered after the return was created. It can only be entered while creating the return.
====

[#1800]
== Cancelling orders

Because there is no possibility to delete cancellations e.g. of individual items in an order, set the quantity of items affected to 0 in this case. Provide a reason for each cancellation, either *Item not in stock* or *Customer cancellation*.

[#1850]
== Generating Neckermann invoices

The procedure for generating Neckermann invoices differs from the procedure for other order referrers. This is why there is an additional menu for generating Neckermann invoices in plentymarkets. Invoices for *Neckermann orders* are not generated in your plentymarkets system, as is the case for invoices that have other order referrers. Instead, your plentymarkets system receives a special file (pcl format) directly from the market Neckermann, which contains the orders that you received.

You can carry out settings related to the layout of the invoices by going to *System » System settings » Client (store) » Select a client » Locations » Select a location » Documents » Invoice*. Go to *System » System settings » Orders » Events* in order to define which additional procedure should be carried out should be carried out when the invoice is printed. If you would like the procedure to be limited to orders from the Neckermann market only, then make sure that you create a filter of the filter type *Referrer* and select *Neckermann* within the filter.

Use the *Generate Neckermann invoices* menu to filter out the orders of your choice from all of the Neckermann orders that you received and to open the corresponding invoices in a separate file. With the help of the search filter in this section, you can determine which criteria should be used to select orders for the retrieval of invoices.

[.instruction]
Retrieving Neckermann invoices:

. Go to *Orders » Fulfillment » Generate Neckermann invoices*.
. Set the desired *search filter* options.
. Under *Procedure*, select the *Order status* that you would like to have assigned to the selected orders after the invoices were successfully retrieved.
. Carry out the settings. Pay attention to the information given in table 4.
. Click on the *gear-wheel icon*. +
→ A *zip file* is created which contains the invoices corresponding to all of the orders that you selected with the filter options.
. After you have unzipped this file, you can save and print your invoices.

.Settings for Neckermann invoice
[cols="1,3"]
|====
|Setting |Explanation

|*Order status*
|Select the current *status* of the orders that you would like to generate invoices for.

|*Items shipped on*
|Select the date from the calendar. The date when items were shipped can only be used as a filter if you selected status *[7] Outgoing items booked* from the *Order status* drop-down list.

|*Owner*
|Select an *owner* for the orders that you are searching for. *_Or:_* Select the option *ALL*.

|*Client (store)*
|Select one of the *stores* or select the option *ALL*.

|*Warehouse*
|Limit the search to a particular *warehouse* or carry out the search for *ALL* warehouses.

|*Limit*
|You have to limit the number of invoices that can be generated to one of the values in the drop-down menu. The maximum is 200 invoices.

|*Change order status*
|Select a new *order status* that you would like to have assigned to the selected orders after the invoices were successfully retrieved. +
*_Or:_* Select the option *no change*.
|====

[#1900]
== Viewing the API log

The menu *Data » API log » Tab: API log* contains a history of processes that run via the Neckermann interface. The formats *NeckermannATEP* and *NeckermannATCD* are available for Neckermann.

[.instruction]
Viewing the API log:

.  Go to *Data » API log*.
.  Select the *NeckermannATEP* format from the *Process* drop-down list.
.  Select a date if you only want to see entries for a specific day.
.  Select the number of results per page.
.  Click on *Search* to display the results.
