= Abonnement
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Abonnement-Übersicht, Scheduler, Abo, Abonnement, Abo-Modul, Abomodul, Scheduler-Auftrag, Durchlauf, Durchläufe, automatischer Durchlauf, Durchlaufvorschau, Abo-Aufträge, Abo-Auftrag, Intervall, Abo-Intervall, Abo-Funktion, Abofunktion, Subscription, Abointervall, Aboauftrag, Gesperrte Abonnements, Abos, Aboübersicht
:description: Erfahre, wie du in plentymarkets Abonnements anlegst und verwaltest.
:position: 60
:url: auftraege/abonnement
:id: EFRPGV6
:author: team-order-payment

Das Modul Abonnement ermöglicht es dir, für Kund:innen intervallgesteuert automatisierte Aufträge anzulegen. So bekommen deine Kund:innen in regelmäßigen zeitlichen Abständen die ausgewählten Artikel zugeschickt, ohne dass du jeden Auftrag einzeln anlegen musst.
Erstelle ein individuelles Abonnement für eine Kund:in und konfiguriere es wie gewünscht. +
Die Erstellung und Bearbeitung der Abonnements findet gut überschaubar in einem eigenen Bereich im Backend deines plentymarkets Systems statt.
Durch Abonnements generierte Aufträge bearbeitest du dann wie andere Aufträge auch in der Auftragsübersicht. Im Folgenden erfährst du, wie du <<auftraege/abonnement#200, Abonnements anlegst>>, die <<auftraege/abonnement#300, Einstellungen vornimmst>> und welche Bearbeitungsmöglichkeiten dir zur Verfügung stehen.

[#100]
== Vorbereitende Einstellungen

Damit du so bequem wie möglich mit dem Abonnement arbeiten kannst, solltest du vorher einige vorbereitende Einstellungen beachten und vornehmen. Zum einen hast du die Möglichkeit, <<auftraege/abonnement#110, Standardeinstellungen>> für deine Abonnements zu wählen, so dass diese beim Anlegen neuer Abonnements vorausgewählt sind und nicht jedes Mal neu von dir eingestellt werden müssen. Auf diese Weise kannst du im voraus Einstellungen festlegen und beim Anlegen neuer Abonnements Zeit sparen. Zum anderen solltest du <<auftraege/abonnement#120, Benutzerrechte>> vergeben, wenn auch Benutzer:innen vom Typ Backend mit Abonnements arbeiten sollen. In den folgenden zwei Kapiteln werden sowohl die Standardeinstellungen als auch die Einstellungen für die Vergabe der notwendigen Benutzerrechte beschrieben.

Außerdem sind Tabellen individuell anpassbar. Das bedeutet, dass du selbst entscheiden kannst, welche Informationen dir in den Tabellenspalten angezeigt werden. Gehe dafür folgendermaßen vor:

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (icon:cog[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle aus, welche Spalten angezeigt werden sollen.
. Verschiebe (icon:drag_sort_handle[set=plenty]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

Wenn du eine Tabelle angepasst hast, wird diese Auswahl gespeichert. Die Tabellen sind jederzeit anpassbar.

[#110]
=== Standardeinstellungen festlegen

Im Menü *Einrichtung » Aufträge » Auftragstypen » Abonnement* kannst du einige grundlegende Einstellungen in Form von Standardeinstellungen für deine Abonnements festlegen.
So sind die hier vorgenommenen Einstellungen für deine neu angelegten Abonnements dann vorausgewählt.
Sie können deine Arbeit beschleunigen, wenn du regelmäßig die gleichen Einstellungen beim Anlegen von Abonnements wählst. Es ist aber dennoch weiterhin möglich, beim Anlegen eines Abonnements abweichende Einstellungen zu wählen.

[.instruction]
Gehe folgendermaßen vor, um die Standardeinstellungen vorzunehmen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragstypen » Abonnement*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-subscription-default-settings>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-subscription-default-settings]]
.Standardeinstellungen des Abonnements
[cols="1,3"]
|====
|Einstellung|Erläuterung

|[#intable-subscription-automatic-orders]*Für fällige Abonnements automatisch Aufträge erzeugen.*
|Stelle ein, ob für jedes Abonnement automatisch Aufträge mit zugeordneter Auftrags-ID erstellt werden sollen, wenn diese fällig sind.
Diese Aufträge werden dann automatisch in der Auftragsübersicht eingeordnet und sind dort bearbeitbar. +
_Beachte_, dass die Aufträge _nicht_ automatisch erzeugt werden und somit manuell angestoßen werden müssen, wenn du diese Option nicht aktivierst.

|[#intable-subscription-default-status]*Standard-Status*
|Wähle einen Standardstatus aus, der für Abonnements gelten soll. Dieser Status ist dann für neu angelegte Abonnements vorausgewählt, bleibt aber individuell anpassbar. Zur Verfügung stehen dir alle <<auftraege/auftraege-verwalten/#1220, Status>>, die du in deinem plentymarkets System festgelegt hast.

|[#intable-subscription-default-interval]*Standard-Intervall*
|Wähle optional einen Zeitabstand, in dem die Artikel eines Abonnements verschickt werden sollen, als Standard aus. Dieses Intervall ist dann für neu angelegte Abonnements vorausgewählt, bleibt aber individuell anpassbar.

|[#intable-subscription-default-owner]*Standard-Eigner*
|Wähle einen Standardeigner aus. Achte darauf, dass der zugewiesene Eigner die benötigten <<auftraege/abonnement#120, Benutzerrechte>> für das Abonnement hat.

|[#intable-subscription-default-referrer]*Standard-Herkunft*
|Wähle eine Standardherkunft aus, wenn diese beim Anlegen neuer Abonnements vorausgewählt sein soll.

|[#intable-subscription-default-client]*Standard-Mandant*
|Wähle einen Standardmandanten aus, wenn diese beim Anlegen neuer Abonnements vorausgewählt sein soll.

|*Anzeige von hinzugefügten Artikeln im Warenkorb*
|Wähle aus, wie die Artikel zum Warenkorb hinzugefügt werden sollen. Die Standardeinstellung ist *Als eine Auftragsposition, Mengen werden erhöht*. +
*Als separate Auftragspositionen.* = Auch gleiche Artikel werden einzeln hinzugefügt, d.h. jeder Artikel wird in einer eigene Zeile dargestellt. +
*Als eine Auftragsposition, Mengen werden erhöht.* = Gleiche Artikel werden in einer Auftragsposition zusammengefasst und die Menge wird entsprechend angepasst.

|====

[.discrete]
==== Durchlaufvorschau

Im gleichen Menübereich unter *Einrichtung » Aufträge » Auftragstypen » Abonnement* steht dir auch die *Durchlaufvorschau* zur Verfügung.
Klicke auf die Schaltfläche *Durchlaufvorschau* und eine Auflistung *Fälliger Abonnements* wird generiert. Diese sind aufsteigend nach der Auftrags-ID sortiert.
Zudem siehst du auf einen Blick die Laufzeit der Abonnements sowie den letzten und nächsten Durchlauf.

Die Fälligkeit der Abonnements wird systemseitig _einmal täglich_ abgefragt und angestoßen. Die *Durchlaufvorschau* bietet dir nicht nur die Möglichkeit zur Übersicht und Überprüfung anstehender Abonnements, du kannst fällige Abonnements
hier auch selbst sofort anstoßen. Beachte dabei, dass hier _alle auf einmal und sofort_ angestoßen werden, eine Auswahl einzelner ist in dieser Ansicht nicht möglich.
Wie du manuelle Durchläufe für einzelne Abonnements in der Detailansicht jedes Abonnements durchführst, wird weiter unten im Kapitel <<auftraege/abonnement#800, Abgeschlossene Aufträge: Durchläufe>> ausführlicher erläutert.

Werden dir also fällige Abonnements angezeigt, dann klicke für den sofortigen Anstoß rechts unten in der Tabelle auf *Durchlaufvorschau* und warte kurz.
Die Meldung *Durchlauf durchgeführt* nach Beendigung angezeigt. Die auf diese Weise generierten Aufträge findest du nun sowohl in der *Auftragsübersicht*, als auch im Bereich <<auftraege/abonnement#800, Abgeschlossene Aufträge>> in der Detailansicht des dazugehörigen Abonnements.

[IMPORTANT]
.Verwendung der Durchlaufvorschau
====
Der sofortige Anstoß aller fälligen Abonnements lässt sich nicht rückgängig machen. Du kannst aber in der Auftragsübersicht die generierten Aufträge stornieren.
====

[#120]
=== Benutzerrechte vergeben

:rights-purpose: Abonnements sehen und bearbeiten können
:right-one: pass:quotes[*Artikel > Artikel > Variante > Anzeigen*]
:right-two: pass:quotes[*Artikel > Artikel > Variante > Preis > Anzeigen*]
:right-three: pass:quotes[*Artikel > Verkaufspreis > Anzeigen*]
:right-four: pass:quotes[*Aufträge > Anzeigen*]
:right-five: pass:quotes[*CRM >  Nachricht > Anzeigen*]
:right-six: pass:quotes[*Einrichtung > Tag > Anzeigen*]

include::../_includes/textblocks/instructions/rechte.adoc[]

Sollen Mitarbeiter:innen mit dem Zugang *Backend* Abonnements auch anlegen können, benötigen diese Mitarbeiter:innen zusätzlich die folgenden Rechte:

* *CRM > Adresse > Anzeigen*
* *CRM > Kontakt > Anzeigen*
* *Einrichtung > Eigenschaft > Anzeigen*
* *Einrichtung > Tag > Tag-Verknüpfung > Löschen*
* *POS > Kasse anzeigen*

[#200]
== Neues Abonnement anlegen

Für das Anlegen eines neuen Abonnements gehst du über das Menü *CRM » Kontakte*.

[.instruction]
Neues Abonnement über die Kontaktübersicht anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Suche (icon:search[role="blue"]) den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts auf *Aktionen*. +
→ Eine Auswahl der verfügbaren Optionen wird geöffnet.
. Klicke in der Auswahl auf *Neues Abonnement*. +
→ Du wirst automatisch zu den Einstellungen für das neue Abonnement weitergeleitet.

[#300]
=== Einstellungen vornehmen

Die Berechnungen des *Nettowarenwertes* und des *Bruttowarenwertes* erfolgen nach Anlegen des Abonnements automatisch. Zudem wird dir auch der *Letzte Durchlauf* des Abonnements angezeigt. +
Aus dem Kundendatensatz des gewählten Kontaktes werden bereits Daten für das Abonnement übernommen. Dazu zählen zum Beispiel die Adressen oder die dem Kontakt zugeordnete Zahlungsart. Grundlegende Einstellungen des Abonnements werden in <<table-basic-settings-subscription>> erläutert.

[[table-basic-settings-subscription]]
.Erläuterungen zu den Einstellungen des Abonnements
[cols="1,3"]
|====
|Einstellung|Erläuterung

|[#intable-subscription-status]*Status*
|Wenn du einen <<auftraege/abonnement#intable-subscription-default-status, Standardstatus>> eingestellt hast, ist dieser hier vorausgewählt. Darüber hinaus stehen dir hier alle <<auftraege/auftraege-verwalten#1220, Status>> zur Verfügung, die du in deinem plentymarkets System angelegt hast. Wähle den passenden Status manuell aus der Dropdown-Liste aus.

|[#intable-subscription-tags]*Tags*
|Hier stehen dir <<willkommen/allgemeine-funktionen/tags#, Tags>> zur Verfügung, die du in deinem plentymarkets System angelegt hast. Wähle den gewünschten Tag aus der Dropdown-Liste aus.

|[#intable-subscription-invoice-address]*Rechnungsadresse*
|Wähle aus der Dropdown-Liste die gewünschte Rechnungsadresse des ausgewählten Kontaktes aus. Zur Auswahl stehen die Adressen, die auch im dazugehörigen Kontakdatensatz hinterlegt sind. Zur Unterscheidung von mehreren hinterlegten Adressen für einen Kontakt wird die Adress-ID ebenfalls angegeben. Wenn eine Adresse als primäre Rechnungsadresse festgelegt ist, wird diese durch einen Stern gekennzeichnet. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-invoice-address]*Lieferadresse*
|Wähle aus der Dropdown-Liste die gewünschte Lieferadresse des ausgewählten Kontaktes aus.  Zur Auswahl stehen die Adressen, die auch im dazugehörigen Kontakdatensatz hinterlegt sind. Zur Unterscheidung von mehreren hinterlegten Adressen für einen Kontakt wird die Adress-ID ebenfalls angegeben. Wenn eine Adresse als primäre Lieferadresse festgelegt ist, wird diese durch einen Stern gekennzeichnet. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-interval]*Abo-Intervall*
|Das hier gewählte Intervall legt fest, in welchen Zeitabständen Artikel an Kund:innen versendet werden. Wenn du einen <<auftraege/abonnement#intable-subscription-default-interval, Standard-Intervall>> eingestellt hast, ist dieser hier vorausgewählt. Das Intervall lässt sich durch die Auswahl in der Dropdown-Liste anpassen. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-currency]*Währung*
|Wähle die Währung für das Abonnement aus. Die von dir eingestellte <<payment/waehrungen#30, Systemwährung>> ist vorausgewählt.

|[#intable-subscription-start]*Beginn des Abonnements*
|Wähle das Startdatum (icon:calendar[]) für das Abonnement aus. Beachte, dass das Startdatum vor dem Enddatum liegen muss. Wenn das Startdatum in der Vergangenheit liegt, wird der erste automatische Durchlauf für das Abonnement am ausgewählten Startdatum plus dem ausgewählten Intervall ausgeführt. Vorher wird kein automatischer Durchlauf ausgeführt. Es ist aber jederzeit möglich einen <<auftraege/abonnement#800, manuellen Durchlauf>> anzustoßen. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-end]*Ende des Abonnements*
|Wähle das Enddatum (icon:calendar[]) für das Abonnement aus. Beachte, dass das Enddatum nach dem Startdatum liegen muss. Nach dem gewählten Enddatum finden keine Durchläufe mehr für das Abonnement statt. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-cancelled]*Gekündigt*
|Wähle ein Kündigungsdatum (icon:calendar[]) für das Abonnement aus, wenn es gekündigt wurde. Das Kündigungsdatum kann auch vor dem Startdatum des Abonnements liegen. Das Kündigungsdatum kann nicht nach dem Enddatum liegen. Nach dem gewählten Kündigungsdatum finden keine Durchläufe mehr für das Abonnement statt.

|[#intable-subscription-payment-method]*Zahlungsart*
|Zahlungsart wählen, die für das Abonnement gelten soll. Ist im Kontaktdatensatz eine Zahlungsart dem Kontakt zugeordnet, wird diese hier vorausgewählt, lässt sich aber anpassen. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-shipping-costs]*Versandkosten*
|Dieses Feld ist nach der Erstellung des Abonnements verfügbar. +
Wenn erforderlich, kannst du die Versandkosten nach Erstellung des Abonnements anpassen. Bei einer Änderung werden der Netto- und der Bruttowarenwert automatisch neu berechnet und angezeigt.

|[#intable-subscription-shipping-method]*Versandart*
|Dieses Feld ist nach der Erstellung des Abonnements verfügbar. +
Um die <<auftraege/abonnement#600, Versandart bearbeiten>> zu können, klicke nach Erstellung und Speichern des Abonnements auf *Versandprofilverknüpfungen neu berechnen* (icon:cog[]). Die Versandart ist nun bearbeitbar. Bei einer Änderung werden der Netto- und der Bruttowarenwert automatisch neu berechnet und angezeigt.

|[#intable-subscription-client]*Mandant*
|Wähle den Mandanten aus, für den das Abonnement gelten soll. Wenn du einen <<auftraege/abonnement#intable-subscription-default-client, Standard-Mandanten>> eingestellt hast, ist dieser hier vorausgewählt. +
_Dies ist ein Pflichtfeld._

|[#intable-subscription-owner]*Eigner*
|Wenn du einen <<auftraege/abonnement#intable-subscription-default-owner, Standard-Eigner>> eingestellt hast, ist dieser hier vorausgewählt. Der Eigner lässt sich durch die Auswahl in der Dropdown-Liste anpassen.

|[#intable-subscription-referrer]*Herkunft*
|Auftragsherkunft für Abonnements festlegen. Die Herkunft *Manuelle Eingabe* ist vorausgewählt. Es werden nur die <<auftraege/auftragsherkunft#, Herkünfte>> angezeigt, die im Backend aktiv geschaltet sind. +
_Dies ist ein Pflichtfeld._

|====

[#400]
=== Artikelliste erstellen

Zur vollständigen Anlage des Abonnements müssen Artikel hinzugefügt werden. Erst danach wird das Abonnement gespeichert und angelegt.

[.instruction]
Artikel zur Artikelliste hinzufügen:

. Klicke unter *Artikelliste* auf *hinzufügen* (icon:plus-square[role="green"]). +
→ Du wirst zu den *Auftragspositionen* weitergeleitet.
. Wähle den passenden Filter für die Suche und beachte dabei die Erläuterungen in <<table-filters-item-search-subscription>>.
. Füge den oder die Artikel in gewünschter Menge zum Warenkorb (icon:cart-plus[role="green"]) hinzu.
. *Speichere* (icon:save[role="green"]) den Warenkorb (icon:cart-plus[role="green"]). +
→ Das Abonnement wird angelegt und du wirst zu den Einstellungen des Abonnements zurückgeleitet.
. *Speichere* (icon:save[role="green"]) das Abonnement. +
→ Das Abonnement ist angelegt.

[[table-filters-item-search-subscription]]
.Verfügbare Filter in der Artikelsuche
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Variantennummer*
|Variantennummer eingeben, um nach der Variante mit dieser Nummer zu suchen.

|*Varianten-ID*
|ID eingeben, um nach der Variante mit dieser ID zu suchen.

|*Artikelname*
|Artikelnamen eingeben, um nach dem Artikel mit diesem Namen zu suchen.

|*Artikel-ID*
|ID eingeben, um nach dem Artikel mit dieser ID zu suchen.

|*Barcode*
|Barcode eingeben, um nach der Variante mit diesem Code zu suchen.

|====

[TIP]
.Preise in den Artikelpositionen
====
Beachte, dass dir in der Artikelübersicht je nach zuvor ausgewähltem Kontakt unterschiedliche Preise angezeigt werden können. Dies ist abhängig davon, wie du die Preiseinstellungen für dein plentymarkets System umgesetzt hast. Informationen dazu findest du auf den Handbuchseiten zum Thema <<auftraege/buchhaltung#, Buchhaltung>> sowie zum Thema <<artikel/einstellungen/preise#100, Verkaufspreise>>.
====

[.collapseBox]
.*Tabelle Auftragspositionen individualisieren*
--

Die Tabelle zum Hinzufügen von Auftragspositionen lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Standardmäßig werden dir beim Öffnen des Menüs folgende Tabellenspalten angezeigt:

* Artikelname
* Varianten-ID / Nr.
* Attribute
* Original VK
* Menge

Die folgenden Tabellenspalten können ausgewählt werden, werden aber standardmäßig nicht angezeigt:

* Artikel-ID
* Varianten-ID
* Variantennummer
* Variantenname
* Barcode

Passe die Tabelle deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Die Tabelle ist jederzeit anpassbar.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (icon:cog[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle aus, welche Spalten angezeigt werden sollen.
. Verschiebe (icon:drag_sort_handle[set=plenty]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

[#500]
=== Artikelliste bearbeiten

Auch nach Anlegen des Abonnements kannst du die Artikelliste bearbeiten und anpassen. Dies geht solange, bis ein Durchlauf einen ersten Auftrag generiert hat. Danach ist das Abonnement nur noch eingeschränkt bearbeitbar.

[.collapseBox]
.*Tabelle Artikelliste individualisieren*
--

Die Tabelle Artikelliste lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Standardmäßig werden dir beim Öffnen des Menüs folgende Tabellenspalten angezeigt:

* Artikelname
* Varianten-ID / Nr.
* Attribute
* Preis
* Menge

Die folgenden Tabellenspalten können ausgewählt werden, werden aber standardmäßig nicht angezeigt:

* Artikel-ID
* Varianten-ID
* Variantennummer
* Variantenname

Passe die Tabelle deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Die Tabelle ist jederzeit anpassbar.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (icon:cog[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle aus, welche Spalten angezeigt werden sollen.
. Verschiebe (icon:drag_sort_handle[set=plenty]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

Über *Hinzufügen* (icon:plus-square[role="green"]) wirst du direkt zur Artikelsuche weitergeleitet und kannst wie unter <<auftraege/abonnement#400, Artikelliste erstellen>> beschrieben Artikel hinzufügen. Auch die unten aufgeführten Bearbeitungsmöglichkeiten stehen dir hier offen.

Oder gehe über *Bearbeiten* (icon:pencil[role="yellow-background"]) und gelange direkt zum bestehenden Warenkorb (icon:cart-plus[role="green"]) für das ausgewählte Abonnement. Folgende Bearbeitungsmöglichkeiten stehen dir dort zur Verfügung:

[[table-editing-order-items-subscription]]
.Bearbeitungsmöglichkeiten der Artikelliste
[cols="1,3"]
|====
|Einstellung|Erläuterung

|[#intable-subscription-adding-items]*Artikel hinzufügen*
|Füge weitere Artikel zum Warenkorb des Abonnements hinzu (icon:plus-square[role="green"]). Gehe dabei wie unter <<auftraege/abonnement#400, Artikelliste erstellen>> beschrieben vor.

|[#intable-subscription-delete-items]*Artikel löschen*
|Entferne Artikel aus dem Warenkorb des Abonnements über *Artikel löschen* (icon:minus-square[role="red")]).

|[#intable-subscription-change-items]*Mengen anpassen*
|Ändere die Menge eines Artikels im Warenkorb des Abonnements durch Klicken in die Zeile des Artikels im Warenkorb.

|[#intable-subscription-change-prices]*Preise anpassen*
|Passe den Preis eines Artikels im Warenkorb des Abonnements an. Beachte, dass die Preisänderung nur für das ausgewählte Abonnement gilt.

|====

*Speichere* (icon:save[role="green"]) den Warenkorb, nachdem du die gewünschten Änderungen vorgenommen hast. Du wirst dann direkt zu den Einstellungen des Abonnements zurückgeleitet.
*Bruttowarenwert* und *Nettowarenwert* werden automatisch neu berechnet und dir angezeigt. +

[.collapseBox]
.*Tabelle Warenkorb individualisieren*
--

Die Tabelle Warenkorb lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Standardmäßig werden dir beim Öffnen des Menüs folgende Tabellenspalten angezeigt:

* Artikelname
* Varianten-ID / Nr.
* Attribute
* Verkaufsreis
* Menge

Die folgenden Tabellenspalten können ausgewählt werden, werden aber standardmäßig nicht angezeigt:

* Artikel-ID
* Varianten-ID
* Variantennummer
* Variantenname
* Barcode

Passe die Tabelle deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Die Tabelle ist jederzeit anpassbar.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (icon:cog[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle aus, welche Spalten angezeigt werden sollen.
. Verschiebe (icon:drag_sort_handle[set=plenty]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

In der Detailansicht des Abonnements kannst du zudem den *Artikelnamen* ändern. Auch diese Änderung gilt nur für das ausgewählte Abonnement.

[IMPORTANT]
.Änderungen an Artikeln
====
Änderungen an Artikeln in der Ansicht des Abonnements gelten nur für das ausgewählte Abonnement. Für dauerhafte Änderungen an Artikeln müssen die Anpassungen unter *Artikel » Artikel bearbeiten* oder *Einrichtung » Artikel* vorgenommen werden. Die Bearbeitung von Artikeln ist im Handbuch im Kapitel <<artikel#, Artikel>> beschrieben.
====

[#600]
=== Versandart und Versandkosten ändern

Sowohl der *Nettowarenwert* als auch der *Bruttowarenwert* wurden nach Anlegen der Artikelliste und Speichern des Abonnements automatisch berechnet. Nach dem Speichern des Abonnements kannst du die Versandart und die Versandkosten bearbeiten.

[.instruction]
Versandprofilverknüpfungen neu berechnen:

. Klicke auf *Versandprofilverknüpfungen neu berechnen* (icon:cog[]). +
→ Während der Neuberechnung sind die Bearbeitungsmöglichkeiten kurzzeitig gesperrt.
. Wähle unter *Versandart* die gewünschte aus. Es stehen dir die <<fulfillment/versand-vorbereiten#, Versandarten>> zur Verfügung, die du in deinem plentymarkets System hinterlegt hast. +
→ Die *Versandkosten* werden automatisch eingefügt.
. Passe die *Versandkosten* manuell an, wenn du sie ändern möchtest. +
. *Speichere* (icon:save[role="green"]) das Abonnement. +
→ Nettowarenwert und Bruttowarenwert werden automatisch neu berechnet.

[#700]
== Weitere Funktionen in der Detailansicht

In der Detailansicht eines ausgewählten Abonnements stehen dir neben den oben beschriebenen zudem die Funktionen *Abgeschlossene Aufträge*, *Messenger* und die *Auftragshistorie* zur Verfügung. Diese kannst du wahlweise über das Menü links oder im unteren Bereich der Detailansicht ansteuern.

[#800]
=== Abgeschlossene Aufträge: Durchläufe

In diesem Bereich werden dir die bereits abgeschlossene Aufträge des Abonnements angezeigt. Diese können durch automatische oder manuelle Durchläufe entstanden sein.
Ein *automatischer Durchlauf* erfolgt in den Zeitabständen, die du im Intervall für das Abonnement ausgewählt hast. Ist das Ende des Abonnements erreicht oder wird es gekündigt, finden keine automatischen Durchläufe mehr statt.

Zusätzlich zu den automatischen Durchläufen hast du die Möglichkeit, einen *manuellen Durchlauf* anzustoßen. _Beachte_, dass ein manueller Durchlauf immer _sofort_ ausgeführt wird. Gehe für das Anstoßen eines manuellen Durchlaufes wie folgt vor:

[.instruction]
Anstoß eines manuellen Durchlaufes:

. Gehe in der Detailansicht des ausgewählten Abonnements in den Bereich *Abgeschlossene Aufträge*.
. Klicke auf *Manueller Durchlauf*.
. Wähle in der Abfrage aus, ob du den nächsten automatischen Durchlauf des Abonnements überspringen möchtest oder nicht. +
→ Der nächste automatische Durchlauf hängt vom gewählten Intervall ab.
. Der manuelle Durchlauf wird durchgeführt. +
→ Der Auftrag erhält eine *Auftrags-ID* und ist sowohl im Bereich *Abgeschlossene Aufträge* als auch in der *Auftragsübersicht* zu sehen.

Im Bereich *Abgeschlossene Aufträge* wird dir nicht nur die ID angezeigt, du erhältst auch Informationen zum Auftrag, z.B. wann der Auftrag erstellt wurde oder welche Zahlungsart ausgewählt ist.
Zudem hast du die Möglichkeit, einzelne Aufträge eines Abonnements zu löschen (icon:minus-square[role="red"]). Durch das Löschen des Auftrages wird er gleichzeitig auch aus der Auftragsübersicht unter *Aufträge bearbeiten* entfernt. _Beachte_, dass Aufträge nicht gelöscht werden können, wenn bereits steuerrelevante Dokumente, wie z.B. eine Rechnung, erzeugt wurden.

[WARNING]
.Überspringen eines automatischen Durchlaufes
====
Wenn du bei Durchführung eines manuellen Durchlaufes *Nächsten automatischen Durchlauf überspringen* gewählt hast, wird der nächste automatische Durchlauf auch dann übersprungen, wenn du den Auftrag aus dem manuellen Durchlauf löschst.
====

[.collapseBox]
.*Tabelle Abgeschlossene Aufträge individualisieren*
--

Die Tabelle Abgeschlossene Aufträge lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Passe die Tabelle damit deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Die Tabelle ist jederzeit anpassbar.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (icon:cog[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle aus, welche Spalten angezeigt werden sollen.
. Verschiebe (icon:drag_sort_handle[set=plenty]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

[.discrete]
==== Sperrung und Entsperrung von Abonnements

Nach Generierung des ersten Auftrages wird das Abonnement gesperrt und die Bearbeitungsmöglichkeiten in der Detailansicht stehen nur noch sehr eingeschränkt zur Verfügung. End- und Kündigungsdatum des Abonnements bleiben bearbeitbar. Wird der Auftrag gelöscht, wird auch das Abonnement wieder freigeschaltet. *Beachte* aber, dass Aufträge nicht gelöscht werden können, sobald steuerrelevante Dokumente für diesen Auftrag existieren.

Zudem gibt es die Möglichkeit durch Klick auf *Entsperren* (icon:visibility_private[set=plenty]) das Abonnement zu entsperren, so dass alle Bearbeitungsmöglichkeiten wieder zur Verfügung stehen. Es wird in der <<auftraege/abonnement#1000, Auftragshistorie>> dokumentiert, welche Benutzer:in diese Aktion wann ausgeführt hat. Durch einen Klick auf *Sperren* (icon:unlock-alt[role="lightGrey"]) wird das Abonnement wieder gesperrt. Wird dieser Schritt nicht ausgeführt, wird das Abonnement automatisch nach dem nächsten Durchlauf wieder gesperrt. Es empfiehlt sich aber, das Abonnement nach der Bearbeitung wieder zu sperren, da auch diese Aktion einen Eintrag in der Auftragshistorie bekommt. So wird die Transparenz und Nachvollziehbarkeit der Bearbeitung eines Abonnements sichergestellt.

[#900]
=== Messenger nutzen

Nutze den Messenger, um im Backend Nachrichten zu erstellen, die deinen Kontakten zugeordnet werden. Diese Nachrichten funktionieren wie Notizen und sind nur in deinem plentymarkets Backend sichtbar und können nicht von deinen Kontakten aufgerufen werden.

[.instruction]
So erstellst du eine neue Nachricht:

. Klicke auf *Neue Nachricht* (icon:plus-square[role="green"]). +
→ Ein Textfeld öffnet sich.
. Wähle einen oder mehrere Empfänger:innen aus.
. Gib einen Titel ein.
. Gib den Text ins Textfeld ein. +
→ Über dem Textfeld stehen dir Formatierungsmöglichkeiten für deine Nachricht zur Verfügung.
. Füge optional mit *Dateien anhängen* eine Datei an.
. Klicke auf *Senden* (icon:envelope-o[role="purple"]).

Die Nachricht kannst du entweder in der Detailansicht des Abonnements unter *Messenger* öffnen oder in dem Kontakt, zu dem du die Nachricht bzw. Notiz erstellt hast. Gehe dazu in die Kontaktansicht. Eine ausführliche Anleitung zu Kundennotizen findest du im Kapitel <<crm/messenger#, Nachrichten mit dem Messenger verwalten>>.

Stelle noch die *Sortierung* im Messenger ein, indem du auswählst, ob dir die Nachrichten nach Datum auf- oder absteigend sortiert angezeigt werden sollen.

[#1000]
=== Auftragshistorie

Die Auftragshistorie bietet dir eine Übersicht über die ausgeführten Aktionen in einem angelegten Abonnement. Aufgeführt werden nach Datum sortiert z.B. Aktualisierungen von Aufträgen oder das Entsperren und Sperren von Abonnnements.
In der Tabelle siehst du, wann die Aktion durchgeführt wurde, von welchem Benutzer, um welche Aktion es sich handelt und in welchem Status des Abonnements die Aktion ausgeführt wurde.

[#1100]
== Übersicht der Abonnements

In die Übersicht der angelegten Abonnements gelangst du über *Aufträge » Abonnement*. Hier werden dir alle angelegten Abonnements aufsteigend nach ihrer Auftrags-ID aufgeführt.
Darüber hinaus werden dir für jedes Abonnement noch folgende Informationen angezeigt:

* Auftrags-ID
* Kontakt
* Abo-Intervall
* Zahlungsart
* Status
* Start des Abonnements
* Ende des Abonnements
* Gekündigt
* Letzter Durchlauf

Wenn du den Status eines Abonnements ändern möchtest, kannst du dies direkt in der Übersicht vornehmen. Klicke dafür in den Status und wähle aus der Dropdown-Liste den gewünschten Status aus.
Für weiterführende Änderungen an einem der in der Übersicht aufgelisteten Abonnements klicke in die Titelzeile. Die Detailansicht des Abonnements öffnet sich und du kannst Änderungen vornehmen.
Solange noch kein Auftrag generiert wurde, stehen dir alle Bearbeitungsmöglichkeiten zur Verfügung. Ist schon ein Auftrag vorhanden, sind die Bearbeitungsmöglichkeiten eingeschränkt.
Es bleibt jedoch weiterhin möglich z.B. das End- und das Kündigungsdatum des Abonnements anzupassen. Auch einen manuellen Durchlauf kannst du jederzeit starten.

[.collapseBox]
.*Übersichtsabelle individualisieren*
--

Die Übersichtstabelle lässt sich individuell anpassen. Du kannst wählen, welche Tabellenspalten dir in welcher Reihenfolge in der Tabelle angezeigt werden sollen. Passe die Tabelle damit deinen Bedürfnissen und deinem Arbeitsablauf an. Wenn du die Tabelle angepasst hast, wird diese Auswahl gespeichert. Die Tabelle ist jederzeit anpassbar.

[.instruction]
Tabelle individualisieren:

. Klicke auf *Spalten konfigurieren* (icon:cog[]). +
→ Das Fenster *Spalten konfigurieren* öffnet sich.
. Wähle aus, welche Spalten angezeigt werden sollen.
. Verschiebe (icon:drag_sort_handle[set=plenty]) die Spalten, so dass sie in der Reihenfolge angezeigt werden, in der du sie brauchst.
. Klicke auf *Bestätigen*, um deine Auswahl zu speichern.

--

[#1200]
=== Abonnements suchen

In der Abonnements-Übersicht kannst du Abonnements anhand von Filterkriterien suchen (icon:search[role="blue"]).

[.instruction]
Suche von Abonnements:

. Öffne das Menü *Aufträge » Abonnement*.
. Wähle die Filteroptionen aus. Beachte dazu die Erläuterungen in <<table-search-subscriptions>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Abonnements, die den eingegebenen Suchkriterien entsprechen, werden aufgelistet.

[[table-search-subscriptions]]
.Abonnements suchen
[cols="1,3"]
|====
|Einstellung|Erläuterung

|[#intable-subscription-search]*Suche*
|Die Suche (icon:search[role="blue"]) durch einen Klick ausführen. Die gefundenen Abonnements werden in der Übersicht aufgelistet.

|[#intable-subscription-search-reset]*Reset*
|Eingestellte Filterkriterien zurücksetzen (icon:undo[role="orange"]).

|[#intable-subscription-search-order-id]*Auftrags-ID*
|Jedem Abonnement wird automatisch eine fortlaufende und exklusive Auftrags-ID zugeordnet. Die ID entspricht immer einer echten Zahl.

|[#intable-subscription-search-interval]*Intervall*
|Wähle aus der Dropdown-Liste eines der Intervalle aus, damit dir alle Abonnements mit diesem Intervall angezeigt werden.

|[#intable-subscription-search-no-initial-run]*Noch kein initialer Durchlauf*
|Aktiviere diese Option, wenn du nach Abonnements suchen möchtest, für die noch kein Durchlauf, weder manuelle noch automatisch, stattgefunden hat. Wenn du diese Option auswählst, wird die Datumsauswahl darunter gesperrt, da für diesen Suchfilter keine zeitliche Eingrenzung notwendig und somit keine Kombinationsmöglichkeit gegeben ist.

|[#intable-subscription-search-date]*Datumstyp*
|Wähle in der Dropdown-Liste zwischen Startdatum, Enddatum, Kündigungsdatum oder Datum des letzten Durchlaufs aus. In Kombination mit *Auftragsdatum von* und *Auftragsdatum bis* werden dir die Abonnements angezeigt, deren Start-, End- oder Kündigungsdatum im ausgewählten Zeitraum liegt (icon:calendar[]).

|[#intable-subscription-search-date-from]*Auftragsdatum von*
|Definiere in Kombination mit *Auftragsdatum bis* einen Zeitraum und wähle einen Datumstyp, nach dem gesucht werden soll. Es werden dir Abonnements angezeigt, deren Start-, End- oder Kündigungsdatum in diesem Zeitraum liegt (icon:calendar[]).

|[#intable-subscription-search-date-to]*Auftragsdatum bis*
|Definiere in Kombination mit *Auftragsdatum von* einen Zeitraum und wähle einen Datumstyp, nach dem gesucht werden soll. Es werden dir Abonnements angezeigt, deren Start-, End- oder Kündigungsdatum in diesem Zeitraum liegt (icon:calendar[]).

|[#intable-subscription-search-client]*Mandant*
|Mandanten wählen, um nur Abonnements dieses Mandaten anzuzeigen.

|[#intable-subscription-search-contact]*Kontakt*
|Suche Abonnements eines Kunden über die Kontakt-ID.

|[#intable-subscription-search-owner]*Eigner*
|Wähle aus der Dropdown-Liste einen Eigner aus und suche so die Abonnements dieses Eigners.

|[#intable-subscription-search-status-from]*Status von*
|Wähle in Kombination mit *Status bis* aus der Dropdown-Liste einen Statusbereich aus. Es werden dir die Abonnements angezeigt, die in diesem Bereich liegen.

|[#intable-subscription-search-status-to]*Status bis*
|Wähle in Kombination mit *Status von* aus der Dropdown-Liste einen Statusbereich aus. Es werden dir die Abonnements angezeigt, die in diesem Bereich liegen.

|[#intable-subscription-search-payment-method]*Zahlungsart*
|Wähle eine Zahlungsart aus der Dropdown-Liste aus. Es werden dir alle Abonnements angezeigt, für die diese Zahlungsart ausgewählt ist.

|====

[#1300]
=== Gruppenfunktion: Manueller Durchlauf

In der Übersichtsansicht steht dir auch die Gruppenfunktion *Manueller Durchlauf* zur Verfügung. Mit dieser Funktion kannst du für bis zu 20 ausgewählte Abonnements auf einmal einen manuellen Durchlauf anstoßen. Wie auch beim Anstoßen eines einzelnen manuellen Durchlaufs in der Detailansicht eines Abonnements, wird der manuelle Durchlauf der Gruppenfunktion _sofort_ ausgeführt.

[.instruction]
Gehe wie folgt vor, um die Gruppenfunktion zu nutzen:

. Öffne das Menü *Aufträge » Abonnement*.
. Suche nach den Abonnements, für die du einen manuellen Durchlauf anstoßen möchtest.
. Wähle die entsprechenden Abonnements aus.
. Klicke auf *Manueller Durchlauf*. +
→ Ein manueller Durchlauf für die ausgewählten Abonnements wird ausgeführt. Konnte für eines oder mehrere Abonnements kein manueller Duchlauf ausgeführt werden, z.B., weil das Abonnement schon beendet ist, wird dir dies in einer Fehlermeldung angezeigt.

[#1400]
=== Abonnements in der Auftragsübersicht

In der Auftragsübersicht im Menü *Aufträge » Aufträge bearbeiten* werden die durch die Abonnements generierten Aufträge aufgelistet.
In der Titelzeile des Auftrags wird dir angezeigt, zu welchem Abonnement ein Auftrag gehört. Wenn du auf die ID des Abonnements klickst, wirst du zur Detailansicht des Abonnements geleitet.
Hier kannst du das ausgewählte Abonnement bearbeiten.

Die Aufträge eines Abonnements verwaltest du hier in der Auftragsübersicht, wie andere Aufträge auch.
Eine Beschreibung der Bearbeitungsmöglichkeiten findest du im Kapitel <<auftraege/auftraege-verwalten#1500, Aufträge bearbeiten>>.
