= Aufträge verwalten
:lang: de
include::{includedir}/_header.adoc[]
:position: 20
:url: auftraege/auftraege-verwalten
:keywords: Auftragsabwicklung, Auftrag, Aufträge, Auftragsstatus, Auftragstypen, Lieferauftrag, Lieferaufträge, Auftrag manuell anlegen, Kontaktübersicht, Kundenübersicht, Retoure, Retouren, Gutschrift, Gutschriften, Gewährleistung, Gewährleistungen, Reparatur, Reparaturen, Sammelauftrag, Sammelaufträge, Scheduler, Vorbestellung, Aufträge filtern, Auftrag suchen, Aufträge suchen, Auftragsübersicht, Auftrag bearbeiten, Aufträge bearbeiten,

Aufträge bilden deine Verkäufe sowie damit einhergehende und übliche Geschäftsvorfälle ab. Mithilfe von Auftragstypen werden die unterschiedlichen Geschäftsvorfälle kenntlich gemacht. Fortschritte bei der Bearbeitung eines Auftrags werden durch <<auftraege/auftraege-verwalten#1200, Auftragsstatus>> angezeigt. Welche Möglichkeiten dir Auftragstypen und Auftragsstatus bieten und wie du Aufträge sinnvoll abwickelst, erfährst du in den folgenden Beschreibungen. Alle Aufträge werden zentral und in einem einheitlichen Format erfasst. Bereits in der <<auftraege/auftraege-verwalten#1400, Auftragsübersicht>> siehst du wichtige Informationen auf einen Blick und kannst einige Arbeiten direkt ausführen.

[#100]
== Allgemeines zur Auftragsanlage in plentymarkets

In plentymarkets wird ein Auftrag automatisch angelegt, wenn Kunden Bestellungen in deinem Webshop tätigen. Unterschiedliche Geschäftsvorfälle wie <<auftraege/auftraege-verwalten#300, Lieferaufträge>>, <<auftraege/auftraege-verwalten#400, Retouren>>, <<auftraege/auftraege-verwalten#500, Gutschriften>>, <<auftraege/auftraege-verwalten#600, Gewährleistungen>> und <<auftraege/auftraege-verwalten#700, Reparaturen>> werden mithilfe eigener Aufträge verschiedener Typen abgebildet, die immer mit dem Hauptauftrag verbunden sind. Über die <<auftraege/auftraege-verwalten#1400, Auftragsübersicht>> lassen sich Aufträge ungeachtet der <<auftraege/auftragsherkunft#, Auftragsherkunft>> öffnen und bearbeiten. Für viele Auftragstypen, wie zum Beispiel <<auftraege/auftraege-verwalten#300, Lieferaufträge>>, macht das Einrichten von <<automatisierung/ereignisaktionen#, Ereignisaktionen>> Sinn, um Vorgänge zu automatisieren. Einige Beispiele für die Nutzung von Ereignisaktionen für die Auftragsabwicklung werden in den folgenden Kapiteln erläutert. +
Aufträge, die nicht über den Webshop bei dir eingehen, legst du <<auftraege/auftraege-verwalten#200, manuell>> im System an. Das ist beispielsweise bei telefonischen oder E-Mail-Bestellungen sowie bei Barverkäufen der Fall.

[NOTE]
.Grundeinstellungen speichern
====
Passe die Einstellungen im Menü *<<auftraege/grundeinstellungen#, System » Systemeinstellungen » Aufträge » Einstellungen>>* an, bevor du die ersten Aufträge in deinem plentymarkets System abwickelst. *Speichere* die Grundeinstellungen auch dann einmalig ab, auch wen du die voreingestellten Werte nicht verändert hast.
====

[#200]
== Aufträge manuell anlegen

Folgende Möglichkeiten sind verfügbar, um einen Auftrag manuell anzulegen:

* In der *Kontaktübersicht*
* In den *Kundendaten* des Kunden
* In einem bestehenden *Auftrag*
* Über einen *Barverkauf*

Diese verschiedenen Vorgehensweisen werden nachfolgend beschrieben.

[IMPORTANT]
.E-Mail-Versand
====
Bei manuell angelegten Aufträgen wird keine automatische E-Mail, z. B. Auftragsbestätigung, an den Kunden versendet. Grund dafür ist, dass das System nicht wissen kann, wann alle Einstellungen zu diesem Auftrag vorgenommen wurden. Stoße daher den Versand einer E-Mail-Vorlage manuell im Auftrag und dort im Tab *<<auftraege/auftraege-verwalten#1550, Mail>>* an.
====

[#220]
=== Auftrag in der Kontaktübersicht anlegen

Im Menü *CRM » Kontakte* legst du einen neuen Auftrag wie unten beschrieben über die Kontaktdaten an.

[.instruction]
Neuen Auftrag über die Kontaktübersicht anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Suche den Kontakt anhand der Filtereinstellungen wie im Kapitel <<crm/kontakte-verwalten#200, Kontakt suchen>> beschrieben. +
→ Die Kontakte, die den eingestellten Suchkriterien entsprechen, werden angezeigt.
. Klicke in die Zeile des Kontakts. +
→ Die Detailansicht des Kontakts wird geöffnet.
. Klicke im Kontextmenü auf *Neuer Auftrag*. +
→ Das Tab *Neuer Auftrag* wird geöffnet.
. Klicke auf *Suchen*, um eine Liste aller verfügbaren Artikel anzuzeigen, oder suche mithilfe der Suchfelder nach der *Artikel-ID* oder weiteren *Artikeldaten*.
. Wähle die Artikel und die entsprechenden Mengen, die du zum Auftrag hinzufügen möchtest.
. *Speichere* die Einstellungen. +
→ Der Auftrag wird angelegt und in einem neuen Tab geöffnet.

[#230]
=== Auftrag über einen bestehenden Auftrag anlegen

In einem Auftrag findest du das Icon *Neuer Auftrag* im Tab *Übersicht*. Gehe wie unten beschrieben vor, um einen neuen Auftrag über das Tab *Übersicht* eines bestehenden Auftrags anzulegen.

[.instruction]
Neuen Auftrag über bestehenden Auftrag anlegen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*. +
→ Die *Auftragsübersicht* wird angezeigt.
. Klicke auf einen Auftrag des Kunden, für den du einen neuen Auftrag anlegen möchtest. +
→ Der Auftrag wird geöffnet.
. Öffne das Tab *Übersicht*.
. Öffne das Tab *Kundendaten* und klicke dort auf *Neuer Auftrag*, um einen Auftrag für diesen Kunden anzulegen. +
→ Das Tab *Neuer Auftrag* wird geöffnet.
. Klicke auf *Suchen*, um dir eine Liste aller verfügbaren Artikel anzeigen zu lassen, oder suche mithilfe der Suchfelder nach der *Artikel-ID* oder weiteren *Artikeldaten*.
. Wähle die Artikel und die entsprechenden Mengen, die du zum Auftrag hinzufügen möchtest.
. *Speichere* die Einstellungen. +
→ Der Auftrag wird angelegt und in einem neuen Tab geöffnet.

[#240]
=== Auftrag über Barverkauf anlegen

Im Menü *CRM » Kontakte* hast du die Möglichkeit, Barverkäufe ohne Kundenzuordnung direkt über das Kundenprofil *Barverkauf* abzuwickeln. Das Kundenprofil *Barverkauf* ist in deinem System standardmäßig eingerichtet.

[WARNING]
.Zahlungsart und Auftragsdokumente bei Barverkäufen
====
Achte darauf, bei der Auftragsanlage über Barverkauf in den *Auftragsdaten* die passende *Zahlungsart* auszuwählen. Zudem findet bei dieser Art der Auftragsanlage keine Zuordnung zu einem in deinem System gespeicherten Kunden statt. Generiere deshalb die benötigten *<<auftraege/auftragsdokumente#, Auftragsdokumente>>* wie die Rechnung direkt während der Abwicklung des Barverkaufs manuell im Tab *Belege* des Auftrags.
====

[.instruction]
Neuen Auftrag für Barverkäufe anlegen:

. Öffne das Menü *CRM » Kontakte*.
. Gib im Suchfeld *ID* die Zahl 100 ein. +
→ Eine Liste der Suchergebnisse wird eingeblendet.
. Wähle *Barverkauf* aus der *Ergebnisliste*. +
→ Das Kundenprofil für Barverkäufe mit der ID *100* wird geöffnet.
. Klicke auf *Neuer Auftrag*, um einen neuen Auftrag für einen Barverkauf anzulegen. +
→ Das Tab *Neuer Auftrag* wird geöffnet.
. Klicke auf *Suchen*, um eine Liste aller verfügbaren Artikel anzuzeigen, oder suche mithilfe der Suchfelder nach der *Artikel-ID* oder weiteren *Artikeldaten*.
. Wähle die Artikel und die entsprechenden Mengen, die du zum Auftrag hinzufügen möchtest.
. *Speichere* die Einstellungen. +
→ Der Auftrag wird angelegt und in einem neuen Tab geöffnet.

[#300]
== Auftragstyp Lieferauftrag nutzen

Mithilfe des Auftragstyps *Lieferauftrag* werden aus einem Hauptauftrag jeweils Lieferaufträge für die enthaltenen Auftragspositionen generiert, so dass du diese einzeln oder in Teilen verschicken kannst. Du kannst somit beispielsweise Artikel, die du auf Lager hast, sofort losschicken und Artikel, die du erst noch geliefert bekommst, später nachsenden. Führe dies mit unterschiedlichen oder auch nur mit einem Versanddienstleister durch. +

Lieferaufträge können *manuell*, *automatisch* oder per *Ereignisaktion* erstellt werden. +

[IMPORTANT]
.Gemeinsamer Status
====
Der Hauptauftrag folgt immer dem Status des Lieferauftrags mit dem niedrigsten Status.
Wenn z. B. ein Auftrag (in Status *5.0*) zwei Lieferaufträge hat (je in Status *5.0*) und der eine Lieferauftrag wechselt in den Status *6.5* (am Beispiel bedeutet 6.5 "*Beim Logistiker im Versand*"), ändert sich am Status des Hauptauftrages zunächst nichts. Erst wenn der zweite Lieferauftrag in den Status *6.5* wechselt, wird automatisch auch der Status des Hauptauftrages zu *6.5* geändert.
====

[#310]
=== Eigenschaften von Lieferauträgen

Im Allgemeinen besitzen Lieferaufträge folgende Eigenschaften:

* Eine Anpassung der in einem Lieferauftrag enthaltenen Auftragspositionen ist nach Erzeugung *nicht* mehr möglich.
* Der *Preis* und das *Gewicht* eines Artikels werden aus dem Hauptauftrag übernommen.
* *Adressetikett*, *Lieferschein*, *Proformarechung* und *Gelangensbestätigung* können im Tab *Belege* des jeweiligen Lieferauftrags generiert werden.
* Die *Rechnung* und alle weiteren Dokumente werden zentral im Hauptauftrag generiert.
* Die Bestandsreservierung für die in einem Lieferauftrag enthaltene Menge wird beim Anlegen eines Lieferauftrags vom Hauptauftrag auf den Lieferauftrag übertragen.

[#320]
=== Grundeinstellungen für Lieferaufträge vornehmen

[WARNING]
.Lager pro Auftragsposition zuordnen
====
Im Menü *System » Systemeinstellungen » Aufträge » Einstellungen* muss zwingend für die *Zuordnung des Lagers* die Option *b) pro Artikelposition kann ein Lager zugeordnet werden* ausgewählt werden.
====

Im Menü *System » Systemeinstellungen » Aufträge » Auftragstypen » Lieferauftrag* legst du vorab fest, nach welchem Kriterium Aufträge in Lieferaufträge gesplittet werden sollen.

[instruction]
Optionen für das Splitten von Aufträgen in Lieferaufträge wählen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragstypen » Lieferauftrag*.
. Nimm die Einstellungen anhand von <<tabelle-auftragstypen-lieferauftrag-optionen>> vor.
. *Speichere* die Einstellungen.

[[tabelle-auftragstypen-lieferauftrag-optionen]]
.Optionen für das *Splitten von Aufträgen in Lieferaufträge*
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Aufträge in Lieferaufträge splitten nach*

|*Aus*
|Es erfolgt *keine Aufsplittung*. +
*_Achtung_*: Wenn du diese Option aktivierst, können Lieferaufträge nur noch manuell angelegt werden. Das automatische Generieren sowie die Erstellung von Lieferaufträgen per Ereignisaktion sind bei dieser Auswahl nicht mehr möglich.

|*Lager*
|Die Lieferaufträge werden anhand der verschiedenen *Lager* der Auftragspositionen erstellt.

|*Versandprofil*
|Die Lieferaufträge werden anhand der verschiedenen *Versandprofile* der Auftragspositionen erstellt.

|*Lager und Versandprofil*
|Die Lieferaufträge werden anhand der verschiedenen *Lager und der Versandprofile* der Auftragspositionen erstellt.

|*Lager und Netto-Warenbestand*
|Die Lieferaufträge werden anhand der verschiedenen *Lager und des Netto-Warenbestands* der Auftragspositionen erstellt.
|====

[#330]
=== Lieferaufträge manuell anlegen

Bei Bedarf kannst du Lieferaufträge manuell über den Hauptauftrag anlegen. Bei dieser Methode wählst du für jeden Lieferauftrag einzeln die Auftragspositionen und -mengen aus, die im jeweiligen Lieferauftrag beinhaltet sein sollen.

[NOTE]
.Lieferaufträge immer für alle Auftragspositionen anlegen
====
Wir empfehlen, grundsätzlich für *alle* Auftragspositionen Lieferaufträge anzulegen. Verbleiben eine oder mehrere Auftragspositionen ohne Zuordnung zu einem Lieferauftrag im Hauptauftrag, kann es zu Fehlfunktionen kommen.

Zudem darf die Menge, die du unter *LiefAufMenge* einträgst nicht größer sein, als die unter *NZMenge* (nicht zugeordnete Menge) angezeigte Menge.
====

[.instruction]
Lieferaufträge manuell anlegen

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, für den Lieferaufträge angelegt werden sollen.
. Wechsle in das Tab *Lief*.
. Trage in das Feld *LiefAufMenge* (Menge für den Lieferauftrag), die *Menge* ein, die in den Lieferauftrag überführt werden soll.
. Klicke anschließend auf das *Zahnrad*. +
→ Der Lieferauftrag wird angelegt.
. Wiederhole den Prozess, um weitere Lieferaufträge anzulegen.

[#340]
=== Lieferaufträge automatisch anlegen

[IMPORTANT]
.Bedingung für das automatische Anlegen von Lieferaufträgen
====
Lieferaufträge können nur automatisch erzeugt werden, wenn noch kein Lieferauftrag zu dem Auftrag besteht.
====

Wenn du Lieferaufträge automatisch anlegen lässt, greifen die zuvor in <<tabelle-auftragstypen-lieferauftrag-optionen>> beschriebenen Kriterien zum Aufsplitten in Lieferaufträge. Somit müssen die Auftragspostionen und -mengen nicht einzeln ausgewählt werden. Stattdessen überführt das System je nach gewähltem Kriterium alle Auftragspositionen automatisch in Lieferaufträge.

[.instruction]
Lieferaufträge automatisch anlegen

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, für den Lieferaufträge angelegt werden sollen.
. Wechsle in das Tab *Lief*.
. Klicke auf *Lieferauftrag automatisch anlegen*. +
→ Die Lieferaufträge werden angelegt.

[#350]
=== Lieferaufträge per Ereignisaktion anlegen

Lieferaufträge werden idealerweise über eine Ereignisaktion generiert. Du als Händler kannst somit bestimmen, wann und wie die Lieferaufträge zu einem Auftrag generiert werden. Im Folgenden werden drei Beispiele zur Generierung von Lieferaufträgen per Ereignisaktion beschrieben.

Lege folgende *Ereignisaktionen* bzw. die von dir benötigten an und nimm darin die nachfolgend beschriebenen Einstellungen vor.

==== Beispiel A: Ereignisaktion "Lieferauftrag generieren bei Auftragseingang"

Wenn du möchtest, dass schon beim Eingang eines Auftrags die zugehörigen Lieferaufträge generiert werden, nutze die in <<tabelle-ereignisaktion-lieferauftrag-bei-auftragseingang>> beschriebene Ereignisaktion.

Da diese Ereignisaktion direkt beim Auftragseingang greift, wird der Status des Hauptauftrags nicht beachtet. Somit werden auch Lieferaufträge von Aufträgen in Status *3.0* (oder *1.0* wenn du mit Auktionsplattformen wie eBay arbeitest) generiert. Diese nehmen bei der Generierung den Status des Hauptauftrages an.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen eindeutigen Namen für die Ereignisaktion ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-auftragseingang>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-auftragseingang>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[tabelle-ereignisaktion-lieferauftrag-bei-auftragseingang]]
.Ereignisaktion "Lieferauftrag generieren bei Auftragseingang" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Neuer Auftrag*
|

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag > Auftragslager*
|*Mehrere Lager pro Auftrag*

|*Aktion*
|*Auftrag > Lieferaufträge generieren*
|

|====

==== Beispiel B: Ereignisaktion "Lieferauftrag generieren bei Wechsel zu Status 5" einrichten

Wenn du möchtest, dass zu einem Auftrag, der in den Status 5.0 gelangt, die zugehörigen Lieferaufträge generiert werden, nutze die in <<tabelle-ereignisaktion-lieferauftrag-bei-status-5>> beschriebene Ereignisaktion.

Nach dem Generieren der Lieferaufträge darfst du den Hauptauftrag nicht mehr verändern, damit die Summe der Artikel der Lieferaufträge der des Hauptauftrags entspricht.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen eindeutigen Namen für die Ereignisaktion ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-status-5>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-status-5>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[tabelle-ereignisaktion-lieferauftrag-bei-status-5]]
.Ereignisaktion "Lieferauftrag generieren bei Wechsel zu Status 5" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung > Statuswechsel*
|*Freigabe Versand*

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag > Auftragslager*
|*Mehrere Lager pro Auftrag*

|*Aktion*
|*Auftrag > Lieferaufträge generieren*
|

|====

==== Beispiel C: Ereignisaktion "Lieferauftrag generieren bei Rechnungserzeugung"

Wenn du möchtest, dass zu einem Auftrag bei Erzeugung der Rechnung die Lieferaufträge angelegt werden, nutze die in <<tabelle-ereignisaktion-lieferauftrag-bei-rechnungserzeugung>> beschriebene Ereignisaktion. +
Somit kannst du am Hauptauftrag solange Änderungen vornehmen, bis du ihn durch den Rechnungsdruck zum Versand freigibst. Folgende Einstellungen sind nötig:

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen eindeutigen Namen für die Ereignisaktion ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-rechnungserzeugung>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-lieferauftrag-bei-rechnungserzeugung>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[tabelle-ereignisaktion-lieferauftrag-bei-rechnungserzeugung]]
.Ereignisaktion "Lieferauftrag generieren bei Rechnungserzeugung" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Dokumente > Rechnung generiert*
|

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag > Auftragslager*
|*Mehrere Lager pro Auftrag*

|*Aktion*
|*Auftrag > Lieferaufträge generieren*
|

|====

[#360]
=== Haupt- und Lieferaufträge bearbeiten

[NOTE]
.Berechtigungen zum Öffnen von Hauptaufträgen
====
Um den Hauptauftrag öffnen zu dürfen, müssen variable Benutzer über die *<<basics/admin-aufgaben/benutzer-verwalten#90, Berechtigung>>* für alle Lager der Lieferaufträge eines Hauptauftrags verfügen. Prüfe dazu die Einstellungen im Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten » Tab: Sichtbarkeiten*.
====

Wenn du einen Hauptauftrag löschen möchtest, müssen zuerst die Lieferaufträge gelöscht werden. Lieferaufträge können einzeln oder über die Gruppenfunktion in der Auftragssuche gelöscht werden. Erst danach kann der Hauptauftrag gelöscht werden.

Es können weitere Auftragspositionen zum Hauptauftrag hinzugefügt oder daraus gelöscht werden. Allerdings können nur Auftragspositionen, die nicht in Lieferaufträgen enthalten sind, aus dem Hauptauftrag gelöscht werden. Die Menge der Artikel im Hauptauftrag lässt sich erhöhen oder verringern. Löschen solltest du jedoch nur *nicht zu Lieferaufträgen zugeordnete Mengen*.

[WARNING]
.Löschen von Positionen in einem Lieferauftrag
====
Technisch möglich ist zwar auch das Löschen von Positionen, die bereits in einem Lieferauftrag enthalten sind. Dies solltest du jedoch vermeiden, um Fehlfunktionen zu verhindern.
====

[#400]
== Auftragstyp Retoure nutzen

Der Auftragstyp Retoure bildet den Geschäftsvorfall einer Retoure ab. Du und deine Mitarbeiter können Retouren manuell erfassen. Zusätzlich kannst du auch deinen Webshop-Kunden erlauben, Retouren über den *Mein Konto* Bereich anzumelden. Das Erfassen einer Retoure bucht die retournierten Artikel noch nicht zurück in den Warenbestand. Du erfasst also die retournierten Artikel zunächst und entscheidest anschließend, ob die Artikel wieder zum Bestand gebucht werden oder ob weitere Schritte, wie z.B. eine Reparatur, notwendig sind. Die Retoure ist ein untergeordneter Auftragstyp, da Retouren entweder einem Auftrag oder einer Gewährleistung zugeordnet sind.
Bevor du Retouren erfassen kannst, lege Retourengründe und Artikelstatus für retournierte Artikel an.

[NOTE]
.Standardstatus für Retouren ändern
====
Der Standardstatus für Retouren ist Status 9. Jede Retoure, die erfasst wird, erhält automatisch diesen Status. Du kannst jedoch jederzeit im Menü *<<auftraege/grundeinstellungen#, System » Systemeinstellungen » Aufträge » Einstellungen>>* einen anderen Status als *Standard-Status Retoure* festlegen.
====

[#410]
=== Alter Webshop: Retourengründe eintragen

Du kannst bis zu 20 Retourengründe eintragen. Beim Erfassen einer Retoure wählst du dann für jede Auftragsposition einen Grund.  Anhand von Retourengründen ist später nachvollziehbar, ob ein Artikel besonders häufig wegen des selben Grundes retourniert wurde.

[.instruction]
Retourengründe anlegen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragstypen » Retoure*.
. Trage *Gründe* für Retouren ein.
. *Speichere* die Einstellungen.

Wenn du erlaubst, dass Kunden im Mein-Konto-Bereich des Callisto Webshops *<<webshop/webshop-einrichten/mein-konto#grundeinstellungen, Retouren selbst anlegen>>* können, stehen die angelegten Retourengründe den Kunden dort zur Wahl. Wenn der Kunde keinen Grund wählt, wird der erste Retourengrund verwendet, da dieser voreingestellt ist.

[#420]
=== Status für retournierte Artikel eintragen

Du kannst bis zu 12 Artikelstatus anlegen. Die Status kannst du z.B. nutzen, um einerseits den Zustand der retournierten Artikel anzugeben, aber auch den Fortschritt beim Bearbeiten der retournierten Artikel. Die Status stehen in einer Retoure im Tab *Übersicht* bei den Auftragspositionen zur Wahl. Um je nach Fortschritt der Bearbeitung verschiedene Status zuzuweisen, lege entsprechend deiner Anforderungen die benötigten Status an.

[.instruction]
Status für retournierte Artikel eintragen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragstypen » Retoure*.
. Trage die gewünschten *Status* für die Zuordnung zurückgesendeter Artikel ein.
. *Speichere* die Einstellungen.

[#440]
=== Retoure erfassen und bearbeiten

Eine Retoure erfasst du manuell, wenn ein Paket bei dir eingegangen ist, oder du erlaubst deinen registrierten Webshop-Kunden, direkt im Kundenkonto des Shops Retouren anzumelden. Nachdem eine Retoure erfasst wurde, werden weitere Bearbeitungsmöglichkeiten sichtbar. So kannst du z.B. den Artikelstatus der retournierten Artikel erst nach dem Erfassen angeben.

==== Retoure erfassen

[.instruction]
Retoure erfassen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag oder die Gewährleistung, für den eine Retoure angelegt werden soll.
. Klicke im Tab *Übersicht* unter *Retoure* auf *anlegen*. +
→ Ein Bearbeitungsfenster wird geöffnet.
. Nimm die Einstellungen anhand <<tabelle-einstellungen-retoure>> vor.
. *Speichere* die Einstellungen. +
→ Die Retoure wird angelegt und in einem eigenen Tab geöffnet.

[[tabelle-einstellungen-retoure]]
.Optionen beim Erfassen einer Retoure
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Einstellungen*

|*Status*
|Einen Status für die Retoure wählen. Voreingestellt ist der Standardstatus, der im Menü *System » Systemeinstellungen » Aufträge » Einstellungen* gespeichert wurde.

|*Eigner*
|Einen Eigner auswählen, der dem Retourenauftrag zugewiesen wird.

|*Paketcode der Retoure*
|Paketcode der Retoure eintragen.

2+|*Artikel*

|*Retourengrund auf alle Artikel übertragen*
|Einen Grund für die Retoure wählen, der für alle Artikel der Retoure gilt. +
Wenn hier ein Grund gewählt wird, hat der gewählte Grund Priorität gegenüber den einzeln wählbaren Gründen auf Artikelpositionsebene.

|*Übernehmen*
|Artikel wählen, die in die Retoure übernommen werden sollen.

|*Menge*
|Artikelmenge eintragen, die in die Retoure übernommen werden soll.

|*Grund der Retoure*
|Individuellen Grund für die Retoure eines Artikels wählen.

|*Artikel*
|Der Artikelname kann hier angepasst werden.
|====

Nachdem eine Retoure erfasst wurde, kannst du den Artikelstatus für retournierte Artikel wählen. Außerdem werden weitere Bearbeitungsmöglichkeiten sichtbar.

[#450]
=== Rücksendeschein erstellen

Einen Rücksendeschein kannst du deinen Kunden bei Zustellung der Ware im Paket beilegen. In diesem Fall sollte der Rücksendeschein Blankofelder für die Retourengründe enthalten. Du kannst deinen Kunden aber auch erlauben den Rücksendeschein im *Mein Konto* Bereich auszufüllen, auszudrucken und der Retoure beizulegen.
Bevor Rücksendescheine erzeugt werden können, muss die Dokumentenvorlage *Rücksendeschein* im Menü *<<auftraege/auftragsdokumente#, System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rücksendeschein>>* eingerichtet werden.

[TIP]
.Retourengründe auf der Vorlage einstellen
====
Du kannst einen unausgefüllten Rücksendeschein in jedem Paket beilegen, dass du versendest. Hierfür generierst du den Rücksendeschein direkt im Auftrag, ohne dass es überhaupt eine Retoure geben muss. Die zweite Möglichkeit ist, dass du deinen Webshop-Kunden erlauben Retouren im Mein-Konto-Bereich des Shops anzumelden und hier die Retourengründe anzugeben. Anschließend kann der Kunde den Rücksendeschein ausdrucken und dieser ist bereits befüllt. Egal wie du den Rücksendeschein deinen Kunden zukommen lässt: Damit Retourengründe eingetragen werden können, musst du die Spalte Retourengründe unterhalb der Artikelpositionen platzieren.
====

Prüfe die Artikelpositionen der Retoure und ändere bei Bedarf die Optionen, z.B. die Menge eines Artikels, bevor du im Tab *Belege* der Retoure einen Rücksendeschein erzeugst.

[.instruction]
Rücksendeschein manuell erstellen:

. Öffne die Retoure und klicke auf das Tab *Belege*.
. Wähle die Option *Rücksendeschein* aus der Dropdown-Liste *Beleg erstellen*. +
→ Ein Fenster öffnet sich.
. Nimm die Einstellungen für den Rücksendeschein vor.
. *Speichere* die Einstellungen, um den Rücksendeschein zu generieren.

[TIP]
.Rücksendeschein automatisch generieren
====
Richte eine Ereignisaktion ein, die den Rücksendeschein automatisch generiert. Wenn du hier als Ereignis *Neue Retoure (durch Kunden)* einstellst und nach der Herkunft Webshop filterst, kannst du ausgefüllte Rücksendescheine generieren und musst diese dann lediglich noch zum Download für den Kunden bereitstellen.
====

[#460]
=== Warenbestand zurückbuchen

Wenn du einen Artikel über eine Retoure zurück erhältst, kannst du den Warenbestand ganz oder teilweise zurückbuchen oder auch den gesamten Warenausgang zurücksetzen.

[.instruction]
Warenbestand zurückbuchen:

. Öffn das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle in den Filtereinstellungen unter *Typ* die Option *Retoure*.
. Klicke auf *Suchen*. +
→ Die Retourenaufträge werden aufgelistet.
. Öffne die Retoure, für die der Bestand zurückgebucht werden soll.
. Öffne das Tab *Einstellungen*.
. Klicke bei der Option *Warenbestand* auf *Warenbestand einbuchen*. +
→ Ein Bearbeitungsfenster öffnet sich.
. Nimm die Einstellungen anhand <<tabelle-warenbestand-rueckbuchen-retoure>> vor.
. *Speichere* die Einstellungen.

[NOTE]
.Warenbestand zurückbuchen für Retouren von Aufträgen mit Lieferaufträgen
====
Die Vorgehensweise zum Zurückbuchen des Warenbestands ist auch für Retouren zu Aufträgen mit Lieferaufträgen gleich. Dass Lieferaufträge vorhanden sind, wird dir im Bearbeitungsfenster für das Rückbuchen angezeigt.
====

[[tabelle-warenbestand-rueckbuchen-retoure]]
.Optionen für das Rückbuchen des Warenbestands
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Warenausgang komplett zurücksetzen*
|Setzt den Warenausgang vollständig zurück. Auch das Datum des Warenausgangs wird gelöscht.

2+|*Warenbestand zurückbuchen*

|*Komplette Menge wählen*
|Trägt die komplette Menge des Artikels im Auftrag in die Spalte *Rückbuchen* ein.

|*Komplette Menge abwählen*
|Setzt die Artikelmengen in der Spalte *Rückbuchen* auf 0.

|*Rückbuchen*
|Wenn Teilmengen zurückgebucht werden sollen, dann hier die Artikelmengen manuell eintragen.

|*Lager*
|Das Lager wählen, in das die Artikel zurückgebucht werden sollen.

|*Lagerort*
|Den Lagerort wählen, in den die Artikel zurückgebucht werden sollen.

|*Menge im Auftrag*
|Zeigt die Menge der Artikel an, die im Auftrag enthalten sind.

|*Zurückgebucht*
|Zeigt bereits zurückgebuchte Artikelmengen an.

|*Charge*
|Zeigt die Chargennumer des Artikels an.

|*MHD*
|Zeigt das Mindeshaltbarkeitsdaum des Artikels an.

|*ID*
|ID des Artikels.

|*Artikel*
|Name des Artikels.
|====

[NOTE]
.Retouren-Artikel im Zulauf
====
Im Menü *<<warenwirtschaft/nachbestellungen-verwalten/rueckstandsliste-verwalten#400, Waren » Retouren » Zulauf>>* findest du eine Übersicht aller durch Retouren im Zulauf befindlichen Artikel.
====

[#500]
== Auftragstyp Gutschrift nutzen

Bei einer Gutschrift bekommen deine Endkunden einen Betrag zurückerstattet. Dies kann beispielsweise nach einer <<auftragstyp-retoure-nuten, Retoure>> der Fall sein. Bei der Gutschrift in plentymarkets handelt es sich also nicht um eine Art umgekehrte Rechnung, sondern um eine Rückzahlung. Gutschriftaufträge erzeugst du unter *Aufträge » Aufträge bearbeiten* aus einem Auftrag. Eine Gutschrift ist also immer einem Auftrag zugeordnet. Die in einem Gutschriftauftrag erzeugten Gutschriftbelege werden auch in Buchhaltungsexporten, wie dem *DATEV*-Export, berücksichtigt.

[#510]
=== Standardstatus für Gutschriften speichern

Bevor du eine Gutschrift anlegst, prüfe den Standard-Status für Gutschriften im Menü *<<auftraege/grundeinstellungen#, System » Systemeinstellungen » Aufträge » Einstellungen>>*. Passe den Standardstatus bei Bedarf an und speichere die Einstellungen.

[#520]
=== Gutschrift anlegen

Eine Gutschrift ist immer mit einem bestehenden Auftrag in deinem plentymarkets System verknüpft. Deshalb musst du den gewünschten Auftrag zunächst in der Auftragsübersicht öffnen, bevor eine Gutschrift angelegt werden kann.

[TIP]
.Gutschriften im Hauptauftrag oder im Retourenauftrag anlegen
====
Hat ein Kunde den Auftrag bereits gezahlt, beispielsweise per Vorkasse, und entscheidet sich vor dem Warenausgang gegen den Kauf, empfehlen wir den Auftrag zu stornieren direkt im Hauptauftrag eine Gutschrift über alle Auftragspositionen anzulegen.

Kommt es nach erfolgter Zahlung, Warenausgang und Zustellung der Ware beim Kunden für eine oder alle Auftragspositionen zu einer <<auftragstyp-retoure-nutzen, Retoure>> oder im Folgenden zu einem <<auftragstyp-reparatur-nutzen, Reparaturauftrag>>, lege die Gutschrift direkt im entsprechenden Retouren- oder Reparaturauftrag an.
====

[.instruction]
Auftrag öffnen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, zu dem eine Gutschrift angelegt werden soll. +
→ Der Auftrag wird in einem eigenen Tab geöffnet.

Durch Wahl der Option *Gutschrift / anlegen* im Tab *Übersicht* des Auftrags wird ein neuer Gutschriftauftrag in plentymarkets erzeugt.

[.instruction]
Gutschriftauftrag anlegen:

. Klicke auf das Tab *Übersicht* des Auftrags, zu dem du eine Gutschrift anlegen möchtest.
. Klicke auf die Dropdown-Liste *Gutschrift* und dort auf die Einstellung *anlegen*. +
→ Ein Fenster zum Auswählen der Auftragspositionen erscheint. Nutze die Checkboxen, um die gewünschten oder alle Artikel auszuwählen. Im Feld *Menge* kannst du die Menge der Artikel bearbeiten, die in den Gutschriftauftrag übernommen werden sollen.
→ Der Gutschriftauftrag wird angelegt und in einem eigenen Tab geöffnet.

Wenn bereits ein Gutschriftauftrag zu einem Auftrag angelegt wurde, erscheint im Tab *Übersicht* des Haupfauftrags rechts der Hinweis *Gutschrift verfügbar*. Zusätzlich kannst du bereits angelegte Gutschriftaufträge im Tab *Übersicht* des Hauptauftrags über die Dropdown-Liste *Gutschrift / suchen* aufrufen.

[#530]
=== Gutschriftbeleg erstellen

[NOTE]
.Dokumentenvorlage erstellen
====
Bevor Gutschriftbelege erzeugt werden können, muss die Dokumentenvorlage *<<auftraege/auftragsdokumente/gutschriften-erzeugen#, Gutschrift>>* im Menü *<<auftraege/auftragsdokumente#, Aufträge » Fulfillment>>* eingerichtet werden.
====

Nach dem Anlegen des Gutschriftauftrags muss ein Gutschriftbeleg direkt im Gutschriftauftrag erstellt werden. Bevor du den Gutschriftbeleg im Tab *Belege* des Gutschriftauftrags erzeugst, solltest du die im Gutschriftauftrag enthaltenen Auftragspositionen prüfen und bei Bedarf ändern.

[.instruction]
Gutschriftbeleg erstellen:

. Öffne den Gutschriftauftrag, für den ein Gutschriftbeleg erzeugt werden soll.
. Wähle die Option *Gutschrift* aus der Dropdown-Liste unter *Beleg / erstellen*.
. Klicke auf *Beleg erstellen*.
→ Der Gutschriftbeleg wird erzeugt und in einem eigenen Tab geöffnet.

[#540]
=== Gutschriftbeleg korrigieren und stornieren

Nachdem du zu einem Gutschriftauftrag den entsprechenden Gutschriftbeleg erzeugt hast, ist der Gutschriftauftrag selbst für die Bearbeitung gesperrt, damit steuerrelevante Daten nicht verändert werden können. Wenn du feststellst, dass Korrekturen am Gutschriftauftrag nötig sind, erzeuge einen *Stornobeleg Gutschrift*.

==== Vorlage Stornobeleg Gutschrift einrichten

Richte sich zunächst die Vorlage für das Dokument *Stornobeleg Gutschrift* ein. Der schnellste Weg ist in diesem Fall das Übernehmen der Einstellungen aus der Standard-Dokumentvorlage.  +
Im Folgenden wird daher kurz das Übernehmen der Standard-Dokumentvorlage beschrieben.

[.instruction]
Vorlage einrichten:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Stornobeleg Gutschrift*.
. Wechsle in das Tab *Transfer*.
. Klicke im Bereich *Einstellungen aus Standard-Dokumentenvorlage übernehmen* auf *Übernehmen*.

Da die Einstellungen der Vorlage für Stornobelege mit den Einstellungen der Vorlage für eine Rechnung übereinstimmen, findest du nähere Erläuterungen zu den einzelnen Einstellungen auf der Seite *<<auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnungen erzeugen>>*.

==== Gutschriftauftrag korrigieren

Einen Gutschriftauftrag und den dazugehörigen Gutschriftbeleg korrigierst du, indem du zunächst einen *Stornobeleg Gutschrift* erzeugst. Anschließend kann der Gutschriftauftrag wieder bearbeitet werden, also die Daten korrigert werden, und ein neuer Gutschriftbeleg erzeugt werden.

[NOTE]
.Stornieren eines Gutschriftsbelegs
====
Das Stornieren eines Gutschriftbelegs dient der nachvollziehbaren Korrektur von steuerrelevanten Daten und *nicht* der Stornierung eines Gutschriftenauftrags selbst.
====

[.instruction]
Gutschriftauftrag korrigieren:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag, in dem du den Gutschriftbeleg stornieren möchtest.
. Wechsle in das Tab *Belege*.
. Wähle aus der Dropdown-Liste *Beleg erstellen* den *Stornobeleg Gutschrift*. +
→ Ein Fenster mit optionalen Einstellungen öffnet sich.
. *Speichere* die Einstellungen.  +
→ Der Stornobeleg wird erzeugt und die Auftragseinstellungen des Gutschriftauftrags entsperrt.
. Bearbeite die Daten, die du korrigieren möchtest.
. Wechsle wieder in das Tab *Belege*.
. Wähle aus der Dropdown-Liste *Beleg erstellen* das Dokument *Gutschrift*.  +
→ Ein Fenster mit optionalen Einstellungen öffnet sich.
. *Speichere* die Einstellungen.  +
→ Die Gutschrift wird erzeugt und die Auftragseinstellungen des Gutschriftauftrags erneut gesperrt.

[#550]
=== Rückzahlungen buchen

Nachdem du einen Gutschriftbeleg erstellt hast, muss die Rückzahlung des gutgeschriebenen Betrags in deinem plentymarkets System gebucht werden. Rückzahlungen über bestimmte Zahlungsarten, die du in deinem System eingerichtet hast, buchst du direkt im Tab *Einstellungen* des Gutschriftauftrags. Die Option *Rückzahlung an Kunden* wird nur bei den Zahlungsarten *PayPal*, *ClickandBuy* und *heidelpay* angezeigt.

[IMPORTANT]
.Bedingung bei PayPal
====
Bei *PayPal* ist es nicht möglich, höhere Beträge einzusetzen als mit der ursprünglichen Paypal-Transaktion bezahlt wurden.
====

[.instruction]
Rückzahlung im Tab *Einstellungen* buchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Gutschriftauftrag, für den du eine Rückzahlung buchen möchtest.
. Öffne das Tab *Einstellungen*.
. Klicke bei der Option *Rückzahlung* auf das *Zahlungs-Icon*.
. Prüfe den *Betrag* der Rückzahlung und passe diesen falls nötig an.
. Klicke auf das *Zahnrad*, um die Rückzahlung zu buchen. +
→ Die Rückzahlung wird gebucht.

Alternativ ist es auch möglich, die Rückzahlung im Tab *Zahlung* des Gutschriftauftrags zu buchen. Im Tab *Zahlung* siehst du alle Zahlungen und Teilzahlungen, die zum Auftrag gehören. Das Rückbuchen der Zahlung in diesem Tab ist vor allem notwendig, wenn die Zahlung für den Hauptauftrag nicht über eine in plentymarkets integrierte Zahlungsart getätigt wurde.

[.instruction]
Rückzahlung im Tab *Zahlung* buchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Gutschriftauftrag, für den du eine Rückzahlung buchen möchtest.
. Öffne das Tab *Zahlung*.
. Klicke auf das Icon *Zahlung buchen*.
. Gib den *Betrag* (Soll) sowie falls nötig eine *Währung* und einen *Verwendungszweck* ein.
. Klicke auf *Zahlung buchen*. +
→ Die Rückzahlung wird gebucht und wird im Tab *Zahlung* angezeigt.

[#560]
=== Warenbestand zurückbuchen

Wenn der Warenausgang bereits gebucht wurde und die Waren beispielsweise im Rahmen einer <<auftraege/auftraege-verwalten#400, Retoure>> wieder in das Lager zurückgebucht werden sollen, wird dies im Tab *Einstellungen* des Gutschriftauftrags vorgenommen.

[.instruction]
Warenbestand zurückbuchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Gutschriftauftrag, für den der Warenbestand zurückgebucht werden soll.
. Wechsle in das Tab *Einstellungen*.
. Klicke bei der Option *Warenausgang* auf den Link *Warenbestand einbuchen*.
. Wähle im angezeigten Fenster die gewünschte Option gemäß den Erläuterungen in <<tabelle-warenbestand-rueckbuchung>>.
. Klicke auf *Speichern*, um den Vorgang auszuführen.

[[tabelle-warenbestand-rueckbuchung]]
.Optionen zur Rückbuchung des Warenbestandes
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Warenausgang komplett zurücksetzen*
|Setzt den Warenausgang vollständig zurück. Auch das Datum des Warenausgangs im Hauptauftrag wird gelöscht.

|*Warenbestand zurückbuchen*
|Bucht die Artikel vollständig oder teilweise zurück. Bei dieser Option wird der Warenausgang nicht zurückgesetzt.

|*Komplette Menge wählen*
|Trägt die komplette Menge des Artikels im Auftrag in das Feld *Rückbuchen* ein.

|*Komplette Menge abwählen*
|Setzt die Artikelmengen unter *Rückbuchen* auf Null.

|*Rückbuchen*
|Die Artikelmenge(n) eintragen, die zurückgebucht werden soll(en), wenn Teilmengen zurückgebucht werden sollen.

|*Lager*
|Das Lager wählen, in das die Artikel zurückgebucht werden sollen.

|*Lagerort*
|Den Lagerort wählen, in den die Artikel zurückgebucht werden sollen.

|*Menge im Auftrag*
|Zeigt die Menge der Artikel an, die im Auftrag enthalten sind.

|*Zurückgebucht*
|Zeigt bereits zurückgebuchte Artikelmengen an.

|*Charge*
|Zeigt die Chargennummer der Artikel an, die im Auftrag enthalten sind.

|*MHD*
|Zeigt das Mindesthaltbarkeitsdatum der Artikel an, die im Auftrag enthalten sind.

|*ID*
|ID des Artikels

|*Artikel*
|Name des Artikels
|====

[#600]
== Auftragstyp Gewährleistung nutzen

Gewährleistungen sind <<auftraege/auftraege-verwalten#400, Retouren>> relativ ähnlich, denn in beiden Fällen bekommst du Waren eines Auftrags im *Status 7* wieder zurückgesendet. Im Gegensatz zur Retoure erwarten Kunden bei einer Gewährleistung aber entweder eine neue Lieferung oder eine Rückerstattung des Rechnungsbetrags mittels einer <<auftraege/auftraege-verwalten#500, Gutschrift>>.

[NOTE]
.Garantie vs. Gewährleistung
====
Im Gegensatz zur freiwillig erklärten Garantie handelt es sich bei der Gewährleistung um die *gesetzliche Pflicht* der Händler, Mängel am Artikel, die bereits bei Lieferung bestanden haben, für Käufer kostenlos zu beseitigen. Käufer können die Gewährleistung gerichtlich bis zu 2 Jahre bei beweglichen Artikeln oder 3 Jahre bei unbeweglichen Artikeln geltend machen. Ab 6 Monaten nach Erhalt der Ware muss der Käufer jedoch beweisen, dass die Mängel bereits bei Erhalt der Ware vorhanden war.
====

Wenn ein Gewährleistungsfall vorliegt, entscheidest du als Händler, ob du dem Käufer die Kosten erstattest, den Artikel reparierst oder den Artikel austauschst. Lege die *<<auftraege/auftraege-verwalten#, Gutschrift>>* im Tab *Übersicht* der Gewährleistung an, wenn du dem Käufer die Kosten erstatten willst. Soll ein Umtausch durchgeführt werden, lege eine *Gewährleistung* an. Ob du die *Versandkosten* in einer Gewährleistung übernimmst oder nicht, wählst du im Menü *<<auftraege/grundeinstellungen#, System » Systemeinstellungen » Aufträge » Einstellungen>>*.

[TIP]
.Einstellungen einer Gewährleistung
====
Wenn du aus einem Auftrag heraus eine Gewährleistung erzeugst, wird automatisch das *Versandprofil* des Auftrags übernommen. Die Einstellungen sind jedoch in der Gewährleistung änderbar. Bei *Lieferaufträgen* wird ebenfalls automatisch das korrekte Lager eingestellt. Die *Zahlungsart* bei Gewährleistungen ist änderbar.
====

[#610]
=== Eine Gewährleistung anlegen

Normalerweise legst eine Gewährleistung in einem bestehenden Retourenauftrag an. Es ist jedoch auch möglich, diese direkt aus dem zugrunde liegenden Hauptauftrag heraus anzulegen.

[TIP]
.Gewährleistung im Haupt- oder Retourenauftrag anlegen
====
Beanstandet ein Käufer die Ware nach Lieferung und du entscheidest dich beispielsweise aus Kostengründen gegen die Rücksendung der Ware, lege die Gewährleistung direkt im Hauptauftrag an.

Möchtest du dagegen erst den Eingang der Retoure abwarten und die Ware prüfen, lege zunächst einen Retourenauftrag an und erstelle im Rahmen der Abwicklung dort eine Gewährleistung.
====

[.instruction]
Eine Gewährleistung anlegen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den gewünschten Haupt- oder Retourenauftrag.
. Klicke im Bereich *Gewährleistung* auf *anlegen*. +
→ Das Bearbeitungsfenster *Gewährleistung zum Auftrag* öffnet sich.
. Setzte bei den betreffenden Artikeln ein *Häkchen*.
. *Speichere* die Einstellungen. +
→ Die Gewährleistung wird angelegt und in einem eigenen Tab geöffnet.

[#620]
=== Eine Gewährleistung bearbeiten

Gewährleistungsaufträge werden in der Auftragsübersicht angezeigt. Öffne eine Gewährleistung, um beispielsweise einen zusätzlichen *Preis* einzugeben, wenn du dem Käufer einen höherpreisigen Artikel als Ersatz liefern willst. Falls nötig, können hier auch die Mengen der in der Gewährleistung enthaltenen Auftragspositionen verändert werden. Um eine Gewährleistung zu bearbeiten, gehe wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung bearbeiten:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle im Tab *Filter* für den Filter *Typ* die Option *Gewährleistung*.
. Klicke auf *Suchen*. +
→ Es werden nur Gewährleistungen aufgelistet.
. Klicke in die Zeile der Gewährleistung, die du bearbeiten möchtest. +
→ Die Gewährleistung wird geöffnet und kann über das Tab *Bearbeiten* bearbeitet werden.


[#630]
=== Eine Gewährleistung abschließen

Zum Abschließen einer Gewährleistung musst du, wenn für die Ersatzware ein Aufpreis berechnet wird, zunächst eine Rechnung in der Gewährleistung erzeugen. Falls du keine Ersatzware versendest, sondern dich mit dem Käufer auf einen nachträglichen Preisnachlass auf die beanstandete Ware einigst, legst du eine Gutschrift im Hauptauftrag an.

Um die Bearbeitung einer Gewährleistung durch einen Umtausch abzuschließen, gehe wie im Folgenden beschrieben vor.

[.instruction]
Gewährleistung durch Umtausch abschließen:

. Öffne in der Gewährleistung das Tab *Belege*.
. Wähle *Rechnung* aus der Dropdown-Liste *Beleg erstellen*. +
→ Ein neues Bearbeitungsfenster öffnet sich. +
. Klicke auf *Speichern*.
→ Die Rechnung wird erzeugt und in einem eigenen Tab geöffnet.
. Wechsle in das Tab *Einstellungen*.
. Klicke in der Zeile *Warenausgang* auf das Symbol *Warenausgang buchen*. +
→ Der Warenausgang wird gebucht und der *Status* wechselt automatisch zu *[7] Warenausgang gebucht*.
. Wechsle in das Menü *Aufträge » Aufträge bearbeiten*.
. Setze den Status der Gewährleistung manuell auf Status *[10] Gewährleistung*.
. *Speichere* die Einstellungen.

[NOTE]
.Zahlungseingang bei Gewährleistungen buchen
====
Grundsätzlich müssen Zahlungen zu Gewährleistungen nur dann gebucht werden, wenn mit dem Käufer ein Aufpreis vereinbart wurde. In diesem Fall buchst du den Zahlungseingang nach erfolgter Zahlung des Käufers im Tab *Zahlung* der Gewährleistung.
====

Um die Bearbeitung einer Gewährleistung durch eine Gutschrift an den Käufer abzuschließen, gehe wie im Folgenden beschrieben vor:

[.instruction]
Gewährleistung durch Gutschrift abschließen:

. Öffne  den Haupt- oder Retourenauftrag zur Gewährleistung, für die du eine Gutschrift anlegen möchtest.
. Öffne das Tab *Übersicht*
. Klicke auf die Dropdown-Liste *Gutschrift* und dort auf die Einstellung *anlegen*. +
→ Der Gutschriftauftrag wird angelegt und in einem eigenen Tab geöffnet.

Der weitere Bearbeitungsprozess läuft identisch mit dem regulären Anlegen einer Gutschrift und dem Erzeugen eines Gutschriftbelegs ab und wird im Kapitel <<auftraege/auftraege-verwalten#500, Auftragstyp Gutschrift nutzen>> detailliert beschrieben.

[#700]
== Auftragstyp Reparatur nutzen

Reparaturen werden in plentymarkets durch einen eigenen Auftragstyp abgebildet. Reparaturen bestehen aus retournierter, reparaturbedürftiger Ware. Reparaturaufträge können daher nur aus <<auftraege/auftraege-verwalten#400, Retourenaufträgen>> angelegt werden.

[#710]
=== Status für Reparaturen anlegen

Hinterlege vor dem Anlegen von Reparaturen verschiedene *Status* für die einzelnen Stationen des Reparaturvorgangs, um den Reparaturverlauf in deinem plentymarkets System genau nachvollziehen zu können.

[.instruction]
Status für Reparaturen hinterlegen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragstypen » Reparatur*. +
. Trage die von dir benötigten *Status* für Reparaturen ein. +
. *Speichere* die Einstellungen.

[#720]
=== Zustände für Reparaturen anlegen

Mit einem *Zustand* kannst du den Artikel genau beschreiben, z.B. ob dieser überhaupt eine Reparatur benötigt oder auch, dass es nicht möglich ist, diesen zu reparieren.

[.instruction]
Zustände für Reparaturen anlegen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragstypen » Reparatur*.
. Trage die von dir benötigten *Zustände* für die Zuordnung der Artikelpositionen ein. +
. *Speichere* die Einstellungen.

[#730]
=== Reparatur anlegen

Um eine Reparatur anzulegen, gehe wie nachfolgend beschrieben vor.

[.instruction]
Reparatur anlegen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne die Retoure, zu der du eine Reparatur anlegen möchtest.
. Öffne das Tab *Übersicht*
. Klicke auf die Dropdown-Liste *Reparatur* und dort auf die Einstellung *anlegen*. +
→ Ein Bearbeitungsfenster öffnet sich. Gib den gewünschten *Status* und den *Zustand* der Reparatur an. Wähle die zu reparierenden *Artikel* aus. Gib optional einen *Hinweis* ein.
. *Speichere* die Einstellungen. +
→ Die Reparatur wird angelegt und in einem eigenen Tab geöffnet.

[#740]
=== Reparatur bearbeiten

Je nach Grund der Rücksendung oder Zustand der zu reparierenden Artikel müssen bei der Bearbeitung verschiedene Schritte durchgeführt werden. +
Da es sich bei einer Reparatur um einen eigenen Auftragstyp handelt, kannst du direkt im Tab *Übersicht* der Reparatur nach den bereits beschriebenen Vorgehensweisen entweder eine Gutschrift, eine Gewährleistung oder eine Retoure anlegen. Die jeweils nötigen Schritte wie die Dokumentenerzeugung, Buchungen des Warenausgangs oder -eingangs oder der eventuellen Buchung von Zahlungen laufen jeweils identisch mit den Auftragstypen <<auftraege/auftraege-verwalten#500, Gutschrift>>, <<auftraege/auftraege-verwalten#600, Gewährleistung>> und <<auftraege/auftraege-verwalten#400, Retoure>> ab.

[#800]
== Auftragstyp Sammelauftrag nutzen

Unbezahlte Aufträge können in einem Sammelauftrag zusammengefasst werden. Du kannst im Menü *Aufträge » Aufträge bearbeiten* oder im Tab *Aufträge* eines Kontakts mit dem Suchfilter *Auftragsstatus*, z.B. anhand eines Status im Bereich *[3] Warten auf Zahlung*, nach solchen Aufträgen suchen. Somit hast du zwei Möglichkeiten, Sammelaufträge zu erzeugen, die nachfolgend beschrieben werden.
Für beide Möglichkeiten übernimmst du im Menü *Aufträge » Sammelaufträge* noch nicht bezahlte Aufträge in einen Sammelauftrag. Im Tab *Belege* des Sammelauftrags ist dann die Erzeugung von Sammelrechnungen möglich.

[#810]
=== Grundeinstellungen für Sammelaufträge vornehmen

Im Menü *System » Systemeinstellungen » Aufträge » Auftragstypen » Multi-Order* nimmst du die Grundeinstellungen für Sammelaufträge vor. Hier legst du beispielsweise fest, für welche Auftragstypen und Auftragsstatus Sammelaufträge angelegt werden können.

[.instruction]
Grundeinstellungen für Sammelaufträge vornehmen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Auftragstypen » Multi-Order*.
. Nimm die Einstellungen gemäß <<tabelle-sammelauftrag-optionen>> vor.
. *Speichere* die Einstellungen.

[[tabelle-sammelauftrag-optionen]]
.Grundeinstellungen für Sammelaufträge
[cols="1,3"]
|====
|Einstellung
|Erläuterung

|*Auftragstypen*
|Die Auftragstypen wählen, die für Sammelaufträge verwendbar sein sollen. Eine Mehrfachauswahl ist möglich. Nur die aufgeführten Auftragstypen *Auftrag*, *Gewährleistung* und *Reparatur* sind als Sammelaufträge umsetzbar.

|*Artikeltext*
|Die Optionen für die Spalte *Artikeltext* der Artikelpositionen eines Sammelauftrags wählen. Eine Mehrfachauswahl ist möglich. Die gewählten Optionen werden für jeden Einzelauftrag separat im Sammelauftrag aufgelistet und ermöglichen eine Zuordnung zum Kunden und zum Einzelauftrag.

|*Auftragssortierung*
|Wählen, wie die einzelnen Aufträge im Sammelauftrag sortiert sein sollen. Nur eine Auswahl ist möglich. Die Aufträge sind anhand der der Auftrags-ID (*Order ID aufsteigend* oder *Order ID absteigend*) oder dem Zeitpunkt des Warenausgangs (*Warenausgang aufsteigend* oder *Warenausgang absteigend*) sortierbar.

|*Auftragsstatus Aufträge*
|Wählen, in welchem Status sich Aufträge befinden müssen, um für Sammelaufträge berücksichtigt zu werden. Eine Mehrfachauswahl ist möglich. Um gezielt nur Aufträge zu erfassen, die für Sammelaufträge vorgesehen sind, empfehlen wir, je nach Anwendungsfall einen eigenen Auftragsstatus anzulegen.

|*Auftragsstatus Gutschriften*
|Wählen, in welchem Status sich <<auftraege/auftraege-verwalten#500, Gutschriftaufträge>> befinden müssen, um für Sammelgutschriften berücksichtigt zu werden. Eine Mehrfachauswahl ist möglich.
|====

Weiterhin legst du im Menü *<<auftraege/grundeinstellungen#, System » Systemeinstellungen » Aufträge » Einstellungen>>* mit der Option *Standard-Status Sammelauftrag* fest, welchen Auftragsstatus ein Sammelauftrag beim Anlegen erhalten soll. Standardmäßig steht dafür der Status *[13] Sammelauftrag* zur Verfügung. Wähle zudem mit der Option *Standard-Status Sammelgutschrift* einen Status für Sammelgutschriften aus. Standardmäßig steht dafür der Status *[14] Sammelgutschrift* zur Verfügung.

[#820]
=== Sammelauftrag pro Kundenklasse anlegen

Fallbeispiel: Ein Unternehmen möchte für die Mitarbeiter monatlich die anfallenden Rechnungen in deinem Webshop bezahlen. Richte dafür eine eigene Kundenklasse ein. Mit der Kunden-ID in der vorgesehenen Kundenklasse wird der Rechnungsempfänger bestimmt. Dieser Rechnungsempfänger erhält dann die Sammelrechnung, die direkt aus dem Sammelauftrag heraus erzeugt wird. +

Einen Sammelauftrag für eine bestimmte Kundenklasse sowie einen Zeitraum legst du im Menü *Aufträge » Sammelaufträge* an. Alle unbezahlten Aufträge der Kundenklasse werden somit gesammelt in einem Sammelauftrag abgelegt. Hinterlege in den Einstellungen der Kundenklassen anhand der Option *Kunden-ID*, welcher Kunde für die Kundenklasse als Eigner des Sammelauftrags sowie als Empfänger der Sammelrechnung aufgeführt werden soll. Je nach Anforderung empfiehlt es sich, eigene <<crm/kontakte-verwalten#15, Kundenklassen>> für Sammelaufträge anzulegen.

[.instruction]
Sammelauftrag für eine Kundenklasse anlegen:

. Öffne das Menü *Aufträge » Sammelaufträge*.
. Öffne das Untermenü *Sammelaufträge generieren*.
. Wähle die *Kundenklasse* und optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Auftragseingangs.
. Klicke auf das *Zahnrad*. +
→ Der Sammelauftrag wird angelegt.

[#830]
=== Sammelauftrag pro Kontakt anlegen

Ein Kunde möchte nicht jede Rechnung einzeln bezahlen, sondern pro Monat oder pro Quartal bezahlen. +
In diesem Fall legst du einen Sammelauftrag für einen bestimmten Kontakt direkt im Kontaktdatensatz im Menü *CRM » Kontakte* an. Öffne dazu einen Kontakt und wähle links im Menü die Option *Neuer Sammelauftrag*. Anschließend wird automatisch ein Sammelauftrag generiert, der alle unbezahlten Aufträge des Kontakts enthält.

[TIP]
.Aufträge prüfen
====
Um sicher zu gehen, dass geeignete Aufträge für die Erzeugung eines Sammelauftrags vorhanden sind, suche im Tab *Aufträge* des Kunden nach unbezahlten Aufträgen.
====

[#840]
=== Sammelrechnung generieren

In diesem Kapitel erfährst du, wie du Sammelrechnungen erstellst. Die Erstellung von Sammelrechnungen ist nur in den dazugehörigen Sammelaufträgen möglich. +
Richte zuerst eine Dokumentenvorlage für Sammelrechnungen im Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Sammelrechnung* ein. In diesem Menü kannst du das Dokument detailliert einstellen sowie eine <<auftraege/auftragsdokumente#, Dokumentenvorlage>> in Form einer PDF-Datei hinterlegen. In der Grundeinstellung der Vorlage sind bereits Standardwerte hinterlegt, die du bei Bedarf durch Kopie aus einer anderen Vorlage, z.B. der Dokumentenvorlage *Rechnung*, mit geringem Aufwand weiter vervollständigen kannst. Weitere Informationen und Anleitungen zur Einrichtung der Dokumentenvorlage findest du auf der Handbuchseite <<auftraege/auftragsdokumente#, Auftragsdokumente>>. +
Anschließend kannst du im Tab *Belege* des Sammelauftrags eine Sammelrechnung generieren.

[IMPORTANT]
.Zahlungseingänge bei Sammelaufträgen
====
Wird eine Sammelrechnung von einem Kunden bezahlt und der Sammelauftrag als bezahlt markiert, werden die Zahlungseingänge *nicht* automatisch an den einzelnen im Sammelauftrag zusammengefassten Aufträgen gebucht. Zahlungseingänge musst du also an den einzelnen Aufträgen manuell buchen.
====

Mithilfe der in plentymarkets verfügbaren Ereignisaktionen kannst du die Sammelrechnung automatisiert generieren, sobald ein Sammelauftrag angelegt wird. Gehe dazu wie nachfolgend beschrieben vor:

[.instruction]
Ereignisaktion für Sammelrechnungen erstellen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke links unten auf das *grüne Plus*, um eine neue Ereignisaktion zu erstellen.
. Trage im Bearbeitungsfenster einen Namen ein, z.B. *Sammelrechnungen erstellen*.
. Wähle unter *Ereignis* die Option *Auftragsanlage &gt; Neuer Sammelauftrag*.
. Klicke auf *Speichern*. +
→ Die Ereignisaktion wird angelegt.
. Füge mit dem grünen Plus eine Aktion des Aktionstyps *Dokumente &gt; Sammelrechnung erzeugen* hinzu. In der Aktion hast du die Möglichkeit, ein Zahlungsziel und eine Skonto-Option einzustellen.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen eindeutigen Namen für die Ereignisaktion ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-sammelrechnung-automatisch>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-sammelrechnung-automatisch>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[tabelle-ereignisaktion-sammelrechnung-automatisch]]
.Ereignisaktion "Sammelrechnung automatisch generieren"
[cols="1,3"]
|====
|Einstellung |Auswahl

|*Ereignis*

|*Auftragsanlage > Neuer Sammelauftrag*

|*Aktion*

|*Dokumente > Sammelrechnung erzeugen* +

*_Hinweis_*: Innerhalb der Aktion hast du die Möglichkeit, ein *Zahlungsziel* und ein *Skonto* einzustellen.
|====

[#845]
=== Mahnung für Sammelauftrag generieren

Mahnungen für Sammelaufträge generierst du genau wie Rechnungen im Tab *Belege* des Sammelauftrags. Gehe dazu wie folgt vor:

[.instruction]
Mahnung für Sammelauftrag generieren:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Sammelauftrag, für den eine Mahnung erzeugt werden soll.
. Öffne das Tab *Belege*.
. Wähle die Option *Mahnung* aus der Dropdown-Liste unter *Beleg erstellen*.
. Klicke auf *Beleg erstellen*. +
→ Die Mahnung wird erzeugt und in einem eigenen Tab geöffnet.

[#850]
=== Sammelgutschrift generieren

Eine Sammelgutschrift erzeugst du im Menü *Aufträge » Sammelaufträge*. +
Alle Gutschriften der Kundenklasse werden gesammelt in einer Sammelgutschrift abgelegt. Je nach Anwendungsfall empfehlen wir, eigene <<crm/kontakte-verwalten#15, Kundenklassen>> für Sammelgutschriften anzulegen.

[.instruction]
Sammelgutschrift für eine Kundenklasse generieren:

. Öffne das Menü *Aufträge » Sammelaufträge*.
. Öffne das Untermenü *Sammelgutschriften generieren*.
. Wähle die *Kundenklasse* und optional einen *Zeitraum*. Der Zeitraum bezieht sich auf das Datum des Gutschrifteingangs.
. Klicke auf das *Zahnrad*. +
→ Die Sammelgutschrift wird angelegt.

[#1100]
== Auftragstyp Vorbestellung nutzen

Vorbestellungen sind im Online-Handel ein wichtiges Instrument im Marketing-Mix. Meist können Artikel noch vor der tatsächlichen Verfügbarkeit zum günstigen Einführungspreis bestellt werden. Für eine Warenwirtschaft stellt diese Situation einen Sonderfall dar, da noch nicht verfügbare Artikel natürlich auch noch keinen Lagerbestand haben können.

Vorbestellungen sind in plentymarkets sehr einfach zu erstellen. Es gibt dafür den Auftragstyp *Vorbestellung*, den du bei manuell erfassten Aufträgen verwenden kannst.

Um Vorbestellungen über den Webshop entgegennehmen zu können, sind das Erscheinungsdatum und die Artikelverfügbarkeit notwendig. Nimm dazu die auf dieser Seite beschriebenen Einstellungen am Artikel vor.

[IMPORTANT]
.Manuelle Auftragseingabe
====
Der Auftragstyp *Vorbestellung* kann nur bei manueller Auftragseingabe gewählt werden.
====

[#1110]
=== Erscheinungsdatum

Die Option *Erscheinungsdatum* findest in der Artikelbearbeitung im Tab *Verfügbar*. Hier kannst du über einen Kalender das Datum hinterlegen, zu dem der Artikel verfügbar sein wird (Eingabe auch per dynamischem Import möglich). Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Erscheinungsdatum eintragen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne einen Artikel, den du vorbestellbar machen musst.
. Wechsle in das Tab *Verfügbar*.
. Trage bei *Erscheinungsdatum* das Datum ein, ab dem der Artikel verfügbar sein soll.
. *Speichere* die Einstellungen.

Im nächsten Schritt sorge dafür, dass das Erscheinungsdatum deinen Kunden angezeigt wird. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Erscheinungsdatum im Webshop sichtbar machen:

. Öffne das Menü *CMS » Webdesign » Ordner: Layout » Ordner: ItemView*.
. Öffne das Template *ItemViewSingleItem*.
. Füge die Template-Variable *$ReleaseDate* ein.
. *Speichere* die Einstellungen.

[#1120]
=== Artikelverfügbarkeit

Eine weitere Voraussetzung ist die korrekte Einstellung der *Artikelverfügbarkeit*. Gehen dazu wie im Folgenden beschrieben vor.

[.instruction]
Artikelverfügbarkeit für Vorbestellungen einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne einen Artikel, den du vorbestellbar machen möchtest.
. Wechsle in das Tab *Einstellungen*.
. Wähle für die Option *Beschränkung* die Einstellung *Keine Beschränkung*. +
→ Der Artikel kann nun ohne tatsächlichen Bestand vorbestellt, also verkauft werden.

[TIP]
.Maximale Bestellmenge
====
Damit andere Online-Händler deine Vorbestellungen nicht dazu missbrauchen können, deine Bestände zum günstigen Preis komplett aufzukaufen, trage im *Tab Verfügbar* bei der Option *Maximale Bestellmenge* einen Wert ein. Trage dort den Wert *1* ein, kann der Artikel pro Bestellung nur ein einziges Mal gekauft werden. Setze die maximale Abgabemenge auf den Wert *0*, wird ohne Beschränkung verkauft.
====

[#1130]
=== Zahlungsaufforderung für Vorbestellungen einrichten

Die Option *Versanddatum* bleibt bei normalen Bestellungen in der Regel ungenutzt, kann jedoch für Vorbestellungen sinnvoll verwendet werden. Liegt das Erscheinungsdatum eines Artikels aber in der Zukunft, so wird das Erscheinungsdatum bei der Bestellung als Versanddatum hinterlegt, da ja erst mit dem Erscheinen des Artikels geliefert werden kann. Das Versanddatum kannst du in der Auftragssuche als Filteroption verwenden und über den Aktionsmanager nutzen.

Meist werden Vorbestellungen einige Zeit vor dem Erscheinen eines Artikels generiert, von den Kunden zum Zeitpunkt der Bestellung aber noch nicht bezahlt. Daher ist es sinnvoll, Kunden einige Tage vor dem Erscheinungs- bzw. Versanddatum über den bevorstehenden Versand zu informieren und sie zur Zahlung aufzufordern. Dies kann der *Aktionsmanager* automatisch für dich erledigen. Kunden wird dann wenige Tage vor dem geplanten Versand eine Erinnerungs-E-Mail mit deinen Bankdaten und dem Link zur Kaufabwicklung gesendet. Gehe wie unten beschrieben vor, um die automatische Zahlungsaufforderung für Vorbestellungen einzurichten.

[.instruction]
Zahlungsaufforderung per E-Mail einrichten:

. Erstelle eine geeignete *<<crm/e-mails-versenden#1200, E-Mail-Vorlage>>*.
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Aktionen*.
. Wechsle in das Tab *Neue Aktion*.
. Trage dort im Tab *Einstellungen* einen *Namen* ein.
. Wähle bei der Option *Täglich ausführen um* eine Uhrzeit aus der Dropdown-Liste.
. Setze ein Häkchen bei *Aktiv*, um die Aktion zu aktivieren.
. Wechsle in das Tab *Filter*.
. Wähle für den *Status* die Einstellung *[3] Warten auf Zahlung*.
. Wähle unter *Versanddatum* z.B. die Einstellung *in 4 Tagen*.
. Wechsle in das Tab *Aktion*.
. Wähle bei der Option *Versende E-Mail-Vorlage* die zuvor erstellte E-Mail-Vorlage. Diese Vorlage wird dann mit dieser Aktion automatisch an den Kunden gesendet.
. Klicke auf *Speichern*, um die Aktion zu sichern.

[#1200]
== Auftragsstatus nutzen

Mit Auftragsstatus wird der Fortschritt bei der Abwicklung von Aufträgen abgebildet. 18 Status mit je 4 Nachkommastellen, d.h. eine Anzahl von 189999, stehen dir im System zur Verfügung. 28 sind bereits vorangelegt. Diese vorangelegten Status stellen einen Grundstock für übliche Abwicklungsschritte dar. Einige der 28 voreingetragenen Status sind mit Systemautomatismen verknüpft und sollten von dir auch nur für die systemseitig vorgesehenen Zwecke verwendet werden. Der Auftragsstatus eines Auftrags ändert sich durch diese Systemautomatismen, durch von dir eingerichtete Automatismen oder kann auch manuell geändert werden. Auftragsstatus dienen auch zur besseren Auftragssuche.

Spiele deine Auftragsabwicklung einmal grob durch und überlege dir, wann du Aufträgen einen neuen Status zuordnen möchtest, um den Fortschritt bei der Abwicklung kenntlich zu machen. Richte anschließend die Status ein, indem du Namen für die Status eingeben. Beachte jedoch die zweckgebundenen Status, die in [[tabelle-vorhandene-status]] erwähnt sind.

[TIP]
.Berechtigungen beachten
====
Beachte, dass dir in Dropdown-Listen etc. nur die *Shops* und **Auftragsstatus** angezeigt werden, die für deinen Benutzer freigegeben wurden. Wenn du einen Status nicht siehst, fehlt dir wahrscheinlich die Berechtigung für den Status. Berechtigungen können durch Admin-Benutzer vergeben werden.
====

[#1210]
=== Voreingestellte Status verstehen

Die folgenden 28 Statuseinträge sind bereits zu Beginn in deinem plentymarkets System vorhanden und sind teilweise mit Systemautomatismen verknüpft. Die mit Systemautomatismen verknüpften Status sind nicht löschbar.

[[tabelle-vorhandene-status]]
.Standardstatus und Systemautomatismen
[cols="1,3"]
|====
|Status |Erläuterung

|**[1]** Unvollständige Daten
|Wird automatisch zugeordnet, wenn Daten eines Auftrages unvollständig sind, z.B. Addressdaten noch fehlen. Unvollständige Daten sind teilweise bei Importen von Märkten der Fall. Aufträge in diesem Status dürfen noch nicht weiter bearbeitet werden. Die Daten werden durch nachfolgende Importe noch vervollständigt. Die unvollständigen Daten dienen z.B. der frühzeitigen Bestandsreservierung.

|**[1.1]** Warten auf Zahlung &amp; Freischaltung
.3+|Werden nicht automatisch vergeben. Ein Anwendungsfall ist der vorbefüllte Warenkorb. Ein Auftrag wird angelegt und ein Link zum Warenkorb des Auftrags wird zur Bestätigung an den Kunden geschickt.

|**[1.2]** Freigeschaltet, warten auf Zahlung

|**[2]** Warten auf Freischaltung

|**[3]** Warten auf Zahlung
|Wird jedem unbezahlten Auftrag vom Typ Auftrag automatisch zugeordnet

|**[3.2]** In Warteposition
|Wird automatisch in 2 Fällen gesetzt: +
* Wenn für einen Auftrag eine Teilzahlung gebucht wird, aber kein Warenbestand vorhanden ist. +
* Wenn für einen Auftrag eine Überbezahlung gebucht wird.

|**[3.3]** Versandfertig; warten auf Zahlung
|Wird automatisch einem Auftrag des Typs Auftrag zugeordnet, wenn dem Auftrag eine Teilzahlung zugeordnet wird und Bestand für den Auftrag vorhanden ist.

|**[3.4]** Mahnung versendet
|Empfohlen, um zu erkennen, dass eine Mahnung versendet wurde. Mithilfe einer Ereignisaktion oder Prozessen lässt sich hier eine Automatisierung erreichen. Der Status wird jedoch nicht durch einen Systemautomatismus gesetzt.

|**[4]** In Versandvorbereitung
|Steht in Verbindung mit Bestandsbeschränkung. Wenn du keinen Bestand führst und keine Beschränkung nutzen, dann steht der Status zur freien Verfügung. +
Wenn die Bestandsbeschränkung genutzt wird, wird der Status automatisch zugeordnet, wenn ein Auftrag vom Typ Auftrag bezahlt ist, aber der Bestand der Artikel für den Auftrag nicht ausreicht. Die Beschränkung von Artikeln muss auf Nettowarenbestand eingestellt sein. +
Wenn du die Bestandsbeschränkung und diesen Status bei fehlendem Bestand nutzt, kannst du z.B. erreichen, dass nur Lieferscheine und Rechnungen für Aufträge erzeugt werden, die auch weiter abgewickelt werden können.

|**[5]** Freigabe Versand
|Wird automatisch zugeordnet, wenn ein Auftrag vom Typ Auftrag bezahlt oder die Zahlungsart z.B. Rechnung oder Vorkasse ist und der Bestand der Artikel für den Auftrag ausreicht oder der Bestand unbeschränkt ist.

|**[5.1]** Abwicklung extern
|Empfohlen, um zu kennzeichen, dass die Ware durch einen Fulfillment-Anbieter zusammengestellt und verschickt wird. Der Status wird jedoch nicht durch einen Systemautomatismus gesetzt.

|**[6]** Gerade im Versand
|Empfohlen, um zu kennzeichnen, dass Aufträge zum Picken und Packen an das Lager übertragen wurden. Mithilfe von Ereignisaktionen oder Prozessen lässt sich hier eine Automatisierung erreichen.

|**[7]** Warenausgang gebucht
|Wird automatisch zugeordnet, wenn der Warenausgang in einem Auftrag gebucht wurde. Das manuelle Setzen des Status sorgt wiederum nicht dafür, dass der Warenausgang tatsächlich gebucht wird und der Bestand reduziert wird. Deshalb sollte dieser Status nicht manuell, per Ereignisaktion oder Prozess gesetzt werden.

|**[7.1]** Auftrag exportiert
|Steht zur freien Verfügung. Möglicher Anwendungsfall ist das Setzen des Status, nachdem Aufträge zur Auswertung exportiert wurden.

|**[8]** Storniert
|Empfohlen, um zu kennzeichnen, dass ein Auftrag vom Typ Auftrag storniert wurde. Status 8 ist als Standard für stornierte Aufträge festgelegt. Du kannst die Standardfestlegung für stornierte Aufträge jedoch im Menü *System » Systemeinstellungen » Aufträge » Einstellungen* ändern. Die Einstellung hierfür heißt *Status stornierter Aufträge*. Wenn du einen anderen Status für Stornierungen festgelegt hast, kannst du Status 8 frei nutzen.

|**[8.1]** Storniert durch Kunden
|Empfohlen, um zu kennzeichnen, dass ein Auftrag durch den Kunden storniert wurde

|**[9]** Retoure
|Ist beim Anlegen eines Auftrags vom Typ Retoure automatisch vorausgewählt. Du kannst auch einen anderen Status als Standard festlegen. Die Einstellung erfolgt im Menü *System » Systemeinstellungen » Aufträge » Einstellungen*.

|**[9.1]** Ware wird geprüft
|Empfohlen, um in einer Retoure anzuzeigen, dass die retournierte Ware geprüft wird

|**[9.2]** Warten auf Retoure von Großhändler
|Steht zur freien Verfügung.

|**[9.3]** Gewährleistung eingeleitet
|Empfohlen, um zu kennzeichnen, dass eine Gewährleistung zur Retoure eingeleitet wurde.

|**[9.4]** Umtausch eingeleitet
|Empfohlen, um in einer Retoure anzuzeigen, dass ein Umtausch der retournierten Ware eingeleitet wurde.

|**[9.5]** Gutschrift angelegt
|empfohlen, um in einer Retoure anzuzeigen, dass eine Gutschrift zur Retoure angelegt wurde.

|**[10]** Gewährleistung
|Steht zur freien Verfügung. Kann genutzt werden, um eine Gewährleistung als abgeschlossen zu kennzeichen. Beim Anlegen einer Gewährleistung erhält der Gewährleistungsauftrag je nach Bestandsführung Status 4 oder 5.

|**[11]** Gutschrift
|Wird einem Auftrag vom Typ Gutschrift automatisch zugeordnet, wenn eine Gutschrift angelegt wird. Du kannst auch einen anderen Status als Standard festlegen. Die Einstellung erfolgt im Menü *System » Systemeinstellungen » Aufträge » Einstellungen*.

|**[11.1]** Gutschrift ausgezahlt
|Empfohlen, um zu kennzeichen, dass die Gutschrift ausgezahlt wurde und abgeschlossen ist.

|**[12]** Reparatur
|Ist beim Anlegen eines Auftrags vom Typ Retoure automatisch vorausgewählt. Du kannst auch einen anderen Status als Standard festlegen. Die Einstellung erfolgt im Menü *System » Systemeinstellungen » Aufträge » Einstellungen*.

|**[13]** Sammelauftrag
|Wird einem Auftrag vom Typ Sammelauftrag automatisch zugeordnet, wenn er angelegt wird. Du kannst auch einen anderen Status als Standard festlegen. Die Einstellung erfolgt im Menü *System » Systemeinstellungen » Aufträge » Einstellungen*.

|**[14]** Sammelgutschrift
|Wird einem Auftrag vom Typ Sammelgutschrift automatisch zugeordnet, wenn er angelegt wird. Du kannst auch einen anderen Status als Standard festlegen. Die Einstellung erfolgt im Menü *System » Systemeinstellungen » Aufträge » Einstellungen*.
|====

[#1220]
=== Status hinzufügen und bearbeiten

Du kannst neben den in <<tabelle-vorhandene-status>> aufgeführten Status eigene hinzufügen. Die bereits vorhandenen kannst du bearbeiten und z.B. umbenennen. Pflege Status in verschiedenen Sprachen, um deine Kunden per E-Mail oder im Kundenkonto des Webshops über den Fortschritt zu informieren. Bis auf Status, die mit Systemautomatismen verbunden sind, kannst du alle Status auch wieder löschen. Status, die mit Systemautomatismen verbunden sind, kannst du umbenennen. Du solltest die mit Systemautomatismen verbundenen Status jedoch nicht zweckentfremden.

[TIP]
.Name ist kein Pflichtfeld
====
Der Name ist kein Pflichtfeld. Wenn du keinen Namen pflegst, siehst du in Filtern jedoch nur eine Liste vermeintlich leerer Status und in der Auftragsübersicht ein leeres Statusfeld. Trage deshalb z.B. wenigstens die Statusnummer auch als Namen für deine hauptsächlich genutzte Sprache, Deutsch oder Englisch, ein. Übersetzungen in andere Sprachen dienen nur der Anzeige im Kundenkonto deines Shops sowie zur Kundenbenachrichtigung per E-Mail.
====

[#1230]
==== Status hinzufügen

Füge eigene Status hinzu.

[.instruction]
Status hinzufügen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Status*.
. Klicke auf *Neuen Status erstellen*.
. Trage eine Statusnummer ein. +
→ Die höchstmögliche Nummer ist 18.9999.
. Trage optional einen Namen ein. +
→ Die Sprache, in der du eingeloggt bist, wird als Eingabefeld angezeigt.
. *Speichere* die Einstellungen. +
→ Eingabefelder für weitere Einstellungen werden sichtbar. +
. Füge bei Bedarf weitere Sprachen für den Auftragsstatus hinzu.
. Unter *Farbe* kannst du eine individuelle Farbe für den Auftragsstatus wählen. +
. *Speichere* die Einstellungen. +

[NOTE]
.Nachkommastellen
====
Achte bei der Vergabe der Statusnummern darauf, dass diese nicht auf 0 enden. Besteht die letzte Nachkommastelle aus einer 0, wird diese automatisch vom System gekürzt. In plentymarkets wird somit nicht zwischen einem Status mit der Nummer 1.1 und einem Status mit der Nummer 1.10 unterschieden.
====

[#1240]
==== Status bearbeiten

Gehe wie folgt vor, um einen einzelnen bestehenden Status zu bearbeiten.

[.instruction]
Einzelnen Status bearbeiten:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Status*.
. Klicke auf *Suchen*. +
→ Eine Liste aller vorhandenen Status wird geöffnet.
. Wähle den gewünschten Status aus der Ergebnisliste. +
→ Die Detailansicht des Status wird geöffnet.
. Ändere den Namen des Status.
. Ändere die *Farbe* des Status.
. Klicke auf das *Zahnrad*. +
→ Die Änderungen werden gespeichert.

Nutze die Gruppenfunktion im Menü *System » Systemeinstellungen » Aufträge » Status*, um mehrere Aufträge zugleich zu bearbeiten.

[.instruction]
Mehrere Status bearbeiten:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Status*.
. Klicke auf *Suchen*. +
→ Eine Liste aller vorhandenen Status wird geöffnet.
. Setze in der Statusliste ein Häkchen für alle Status, die bearbeitet werden sollen.
. Klicke auf *Gruppenfunktion*. +
→ Ein neuer Bearbeitungsbereich wird angezeigt.
. Aktiviere im Bearbeitungsbereich die Option *Neue Farbe*, um eine neue Statusfarbe auszuwählen.
. Aktiviere die Option *Shop-Sichtbarkeit* und wähle die gewünschte Einstellung aus dem Dropdown-Menü.
. Klicke auf das *Zahnrad*, um die Einstellungen auf die ausgewählten Status zu übertragen. +
→ Die Änderungen werden gespeichert.

[#1300]
== Aufträge suchen

Mit der Auftragssuche kannst du sowohl alle Aufträge auflisten als auch bestimmte Aufträge gezielt finden. Beim Öffnen des Menüs wird standardmäßig keine Suche ausgeführt, jedoch ist der Filter Datum standardmäßig auf *Auftragseingang* in den letzten 2 Monaten eingestellt. Alle anderen Filteroptionen stehen zunächst auf **ALLE**. Ändere die Filtereinstellungen, um die Suche einzuschränken und führe dann eine Suche aus.

[.instruction]
Aufträge suchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*
. Nimm Filtereinstellungen vor.
. Prüfe, ob die Standardeinstellung für die Option *Datum* und den Zeitraum unter *von bis* deinen Kriterien entspricht.
. Klicke auf *Suchen*, um die Aufträge anzuzeigen.

Wenn du z.B. nach Aufträgen suchst, die in einem Status kleiner als (<) Status 7 sind, bei denen der Warenausgang nicht gebucht ist und du keine Datum berücksichtigst, erhältst du alle Aufträge, die noch nicht abgeschlossen sind.

[NOTE]
.Suche zurücksetzen
====
Klicke auf *Reset*, um deine Filtereinstellungen auf die Standardwerte zurückzusetzen. Klicke dann erneut auf *Suchen*, um auch das Suchergebnis zurückzusetzen.
====

[#1310]
=== Nach IDs und Nummern filtern

Um nach IDs oder Nummern zu filtern, gib in die Eintragsfelder eine ID oder Nummer ein. Durch Eingabe einer *Kunden-ID* erhältst du z.B. nur die Aufträge des Kunden mit dieser ID.

Wenn du eine 3 in das Feld *Auftrags-ID* eingibst und suchst, wird auch nur der Auftrag mit der ID 3 in der Übersicht angezeigt. Es handelt sich also um eine genaue Suche und keine unscharfe Suche. Jedoch kannst du bei den Auftrags-IDs mehrere IDs kommagetrennt eintragen und auf diese Weise auch nach mehreren Aufträgen suchen.

[NOTE]
.Status-Suchfilter prüfen
====
Wenn du nach Nummern oder IDs suchst, ist es sinnvoll den Status nicht einzuschränken und *Alle* einzustellen. Es werden nur Aufträge angezeigt, die alle eingestellten Kriterien erfüllen. Wenn du einen Auftrag trotz eindeutiger ID nicht findest, hast du vielleicht den Suchfilter *Status* nicht auf den Wert *ALLE* umgestellt.
====

[#1320]
=== Nach Kunden- bzw. Artikeldaten und Rechnungsnummern filtern

Für gezielte Suchen anhand von kunden- oder artikelbezogenen Angaben nutzt du am besten die Suchfelder *Kundendaten* und *Artikeldaten*. Hier ist die Eingabe von Suchbegriffen und Zahlen gleichermaßen zulässig. Bei den *Kundendaten* sind neben Namen auch Postleitzahlangaben möglich, jedoch keine Telefonnummern. Bei den *Artikeldaten* werden Artikel-ID, Artikel-Nummer und Name abgefragt, jedoch nicht die Felder mit den Beschreibungstexten (short_description, description). Bei der Suche nach *Rechnungsnummern* ist auch die Suche nach externen Rechnungsnummern möglich.

[NOTE]
.Suchbegriffe und Zahlen nur am Ende kürzen
====
Bei der Suche nach Kunden bzw. Artikeldaten reicht es häufig aus, nur den Wortstamm einzugeben. Achte aber darauf, dass du Suchwörter hinten fast beliebig kürzen kannst, am Wortanfang allerdings nicht. Suche z.B. nach Artikeln mit dem Stichwort Startersets, kannst du Starterset oder Starter oder Start eingeben. Eine Suche nach arterset hingegen führt zu keinem Ergebnis. Gleichermaßen verhält es sich mit Zahlenwerten wie z. B. Kundennummern oder PLZ.
====

[#1330]
=== Nach Auftragstypen filtern

Nutze den Filter *Typ*, um nach folgenden *Auftragstypen* zu suchen:

* *Auftrag*
* *Gutschrift*
* *Sammelgutschrift*
* *Retoure*
* *Gewährleistung*
* *Angebot*
* *Vorbestellung*
* *Lieferauftrag*
* *Reparatur*
* *Sammelauftrag*
* *Aufträge, Gewährleistungen, Lieferaufträge und Reparaturen*
* *Aufträge und Lieferaufträge*
* *Aboauftrag*

Nur die gewählten Auftragstypen bzw. die Kombinationen werden gesucht. In der Standardeinstellung steht der Filter auf *ALLE*, d.h. alle Auftragstypen werden gesucht.

[#1340]
=== Nach Datum filtern

Nutze den Filter *Datum*, um Aufträge zu suchen, die im eingestellten Zeitraum einen bestimmten Schritt durchlaufen haben. Zur Wahl als Ereignis unter *Datum* stehen der *Auftragseingang*, der *Zahlungseingang* oder der *Warenausgang*. Wähle dann unter *von* das Startdatum und unter *bis* das Enddatum des Zeitraums. Alle Aufträge, die innerhalb des gewählten Zeitraums den gewählten Schritt durchlaufen haben, werden angezeigt. Für die Suche ist standardmäßig *Auftragseingang* und ein Zeitraum von 2 Monaten rückwirkend zum aktuellen Datum eingestellt.

Wenn du Aufträge nicht mit der Standardeinstellung von 2 Monaten rückwirkend suchen möchtest, wähle den gewünschten Zeitraum, wie nachfolgend erläutert.

[.instruction]
Aufträge nach Datum filtern:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle aus der Dropdown-Liste unter *Datum* eine der Filteroptionen, z. B. *Auftragseingang*.
. Wähle unter *von* und *bis* das Start- und das Enddatum.
. Wähle ggf. weitere Filteroptionen.
. Klicke auf *Suchen*, um Aufträge des gewählten Zeitraums anzuzeigen.

[#1350]
=== Nach Markierungen filtern

Du kannst Aufträgen unabhängig vom Auftragsstatus Markierungen zuweisen. Auch nach diesen Markierungen kannst du Aufträge filtern. So kannst du z.B. festlegen, dass problematische Aufträge mit einem bestimmten Symbol gekennzeichnet werden und vor der Auslieferung von einem Verantwortlichen freigegeben werden müssen. Dieser kann die Aufträge einmal täglich über den Filter *Markierung* suchen, eine Information hinterlegen und die Markierung dann wieder zurücksetzen.

[#1360]
=== Nach Dokumenten filtern

Nutze den Filter *Dokument*, um Aufträge zu suchen, für die bereits ein *<<auftraege/auftragsdokumente#, Dokument>>* eines bestimmten Typs angelegt wurde. Die folgenden zwei Möglichkeiten stehen zur Verfügung:

Um alle Aufträge anzuzeigen, für die ein Dokument eines Typs angelegt wurde, gehe wie im Folgenden beschrieben vor.

[.instruction]
Alle Aufträge mit einem Dokument suchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle im Tab *Filter* einen Dokumententyp aus der Dropdown-Liste *Dokument*, z.B. Rechnung.
. Beachte den Filter *Datum*, da standardmäßig nur Aufträge der letzten 2 Monate angezeigt werden. Passe den Filter gegebenenfalls an.
. Klicke auf *Suchen*. +
→ Alle Aufträge, für die bereits eine Rechnung generiert wurde, werden im Suchergebnis angezeigt.

Auch die Suche nach einem Auftrag, der ein Dokument mit einer bestimmten Nummer enthält, ist möglich. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Auftrag mit einer Dokumentnummer suchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle im Tab *Filter* einen Dokumententyp aus der Dropdown-Liste *Dokument*, z.B. Lieferschein.
. Trage im Feld *Nummer* rechts daneben die Nummer des gesuchten Lieferscheins ein.
. Beachte den Filter *Datum*, da standardmäßig nur Aufträge der letzten 2 Monate angezeigt werden. Passe den Filter gegebenenfalls an.
. Klicke auf *Suchen*. +
→ Nur der Auftrag, zu dem der Lieferschein mit der eingegeben Nummer gehört, wird im Suchergebnis angezeigt.

[TIP]
.Auswahl eines Dokumententyps bei Suche mit Nummer nicht zwingend erforderlich
====
Die Suche nach einer Dokumentennummer funktioniert auch, wenn du die Standardeinstellung *Dokument* stehen lässt, also keinen Typen wählen. Wenn jedoch die Nummern verschiedener Dokumententypen identisch sind, werden dir alle Aufträge, die ein Dokument mit dieser Nummer haben, angezeigt. Dies kann zum Beispiel der Fall sein, wenn du alle Dokumente ohne Nummernkreis durchnummerierst.
====

[#1370]
=== Nach Gutscheincodes filtern

Nach Aufträgen mit *<<auftraege/gutscheine#, Gutscheinen>>* suchest du, indem du den Gutscheincodes in das Suchfeld *Gutschein-Code* einträgst. Zusätzlich stehen die Optionen *Alle*, *Eingelöst* und *Verkauft* zur Verfügung. *Alle* ist standardmäßig voreingestellt. Mit *Eingelöst* suchst du nur Aufträge, in denen der Gutscheincode eingelöst wurde. Mit *Verkauft* suchst du nur Aufträge, in denen ein Gutschein mit dem eingetragenen Gutscheincode verkauft wurde. *Alle* sucht sowohl Aufträge, in denen der Code eingelöst als auch verkauft wurde. Der Suchfilter, auch mit der Option *Alle*, greift nur, wenn ein Gutscheincode eingetragen ist. Du kannst den Suchfilter also nicht nutzen, um alle Aufträge mit Gutscheinen zu suchen.

[#1400]
== Auftragsübersicht einrichten

Damit du die Suchergebnisse gut überblicken und bearbeiten kannst, passe die Auftragsübersicht an. +
Du kannst einstellen, wie viele Aufträge pro Seite in der Auftragsübersicht angezeigt werden. Die höchste Anzahl an Aufträgen pro Seite ist 400, die niedrigste 50. +
Nutze die Pfeile, um zur nächsten Seite oder zurück zu wechseln. Du kannst die gewünschte Seitenziffer auch direkt eintragen und die Eingabetaste betätigen.

[#1410]
=== Auftragspositionen ein- oder ausblenden

In der Auftragsübersicht werden standardmäßig die Auftragspositionen mit angezeigt. So stehen dir auf einen Blick die im Auftrag enthaltenen Artikel mit wichtigen Parametern, z.B. *Titel*, *Größe*, *Preis* zur Verfügung. Du kannst die Auftragspositionen jedoch auch ausblenden. Du kannst die Positionen entweder nur bei einzelnen Aufträgen oder bei allen ausblenden. Um die Positionen eines einzelnen Auftrages auszublenden, nutze das Pfeilsymbol *Artikelliste schließen*. Um die Positionen für alle Aufträge auszublenden, folge den aufgeführten Schritten.

[.instruction]
Auftragspositionen für alle Aufträge ausblenden:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle im Tab *Filter* für den Filter *Artikelposition* die Einstellung *Nicht anzeigen*.
. Klicke auf *Suchen*. +
→ Die Artikellisten der angezeigten Aufträge werden geschlossen.

[#1420]
=== Informationen und Symbole in der Auftragsübersicht verstehen

In der Auftragsübersicht werden je nach Zustand eines Auftrags verschiedene Symbole angezeigt, die im Folgenden kurz erläutert werden. Wenn du den Mauszeiger auf ein Symbol bewegst, wird dir eine kurze Erläuterung, ein Tooltip, eingeblendet.

In der Titelzeile eines Auftrags siehst du mindestens, wie du den Kunden bewertet hast, den *<<auftraege/auftraege-verwalten#1200, Status>>* des Auftrages, das Logo des *<<fulfillment/versand-vorbereiten#, Versanddienstleisters>>* und die *<<payment#, Zahlungsart>>*. Je nach Fortschritt des Auftrages erscheinen dort weitere Symbole. Wenn z.B. der Warenausgang gebucht, verschwindet das Symbol *Warenausgang buchen* und das Symbol für *Warenausgang gebucht* wird angezeigt. Beim Buchen des Warenausgangs wechselt auch der Status in Status 7. Anhand der Farbe der Statusanzeige erkennst du Aufträge mit gleichem Status auf einen Blick.

Die folgende Tabelle enthält eine Übersicht der möglichen Informationen. Einige Symbole erlauben dir auch direkt Aktionen auszuführen. Beachte, dass nie alle Symbole angezeigt werden, sondern nur die zum Bearbeitungsstand passenden.

.Mögliche Symbole in der Auftragsübersicht
[cols="1,3a"]
|====
|Tooltip des Symbols |Erläuterung

|*Auftragsstatus*
|Zeigt den aktuellen Auftragsstatus und erlaubt auch den Status zu ändern. Zum ändern, einfach auf den Status klickenund einen neuen wählen. +
**Wichtig**: Ein Auftragsstatus &gt;= 7 kann nicht verringert werden, ohne dass vorher die Buchung des Warenausgangs zurückgesetzt wird.

|*Versanddienstleister*
|Individuelles Symbol des zugeordneten Dienstleisters. Ein Symbol wird jedoch nur angezeigt, wenn im *<<fulfillment/versand-vorbereiten#1000, Versandprofil>>* eine Markierung eingestellt wurde.

|*DHL-Packstation*
|Das Symbol wird nur angezeigt, wenn die Packstationsdaten korrekt im Auftrag hinterlegt sind. Es kann bei Aufträgen von Marktplätzen vorkommen, dass Packstationsdaten nicht korrekt sind, wenn der Marktplatz z.B. keine Validierung bereitstellt. In einem solchen Fall wird das Symbol nicht angezeigt, da aufgrund der falschen Daten nicht an eine Packstation geliefert werden kann.

|*Versandart* oder +
 *Versanddienstleisterservice*
|*Schnellversand* ist ein Service, der zusätzlich durch ein Symbol angezeigt wird

|*Zahlungsart*
|Individuelles Symbol der Zahlungsart

|*Warenausgang gebucht*
|Wird nur angezeigt, wenn der Warenausgang gebucht wurde. Falls nur der Status in Status 7 geändert wurde, wird das Symbol nicht angezeigt.

|*Mahnstufe*
|*<<payment/zahlungsanbieter/mediafinanz#30, Mahnstufen>>* können per Aktionsmanager zugeordnet werden

|*Markierung*
|Individuelle Auftragsmarkierung

|*Lieferland*
|ISO-Code für das Lieferland nach ISO-3166 Alpha 2

|*Währung*
|ISO-Code der Auftragswährung nach ISO 4217

|*Zahlungsstatus*
|Wird passend zur Zahlung als farbiger Balken und zusätzlich in einem Tooltip als Prozentwert angezeigt.

|*Auftragsbestätigung erstellen*
|Auftragsbestätigung direkt erstellen

|*Rechnung erstellen*
|Rechnung direkt erstellen

|*Zahlungseingang direkt buchen*
|Zahlung direkt zum Auftrag buchen. Der Betrag ist frei einstellbar. Der offene Rechnungsbetrag ist voreingetragen.

|*Lieferschein erstellen*
|Lieferschein direkt erstellen

|*Warenausgang buchen*
|Erlaubt den Warenausgang direkt zu buchen, wodurch der Bestand der Varianten reduziert wird, wenn du Bestand führst. Der Status der Auftrags ändert sich automatisch in Status 7.

|*Tracking-URL anzeigen*
|Die Tracking-URL dient zur Sendungsverfolgung eines Paketes. Die *<<fulfillment/versand-vorbereiten#840, Tracking-URL>>* musst du beim Einrichten von Versanddienstleistern eintragen und speichern.

|*Notiz zum Auftrag erstellen*
|Erlaubt eine Notiz zum Auftrag zu verfassen sowie eine bereits vorhandene Notiz zu lesen. An einem Symbol ohne Plus ist erkennbar, dass bereits eine Notiz existiert.

|*Notizen zum Kunden*
|Erlaubt eine Notiz zum Kunden zu verfassen sowie eine bereits vorhandene Notiz zu lesen

|*E-Mail-Adresse des Kunden*
|Erlaubt über dein E-Mail-Programm direkt eine E-Mail an den Kunden des Auftrags zu senden

|*E-Mail-Service*
|Öffnet das Tab E-Mail-Vorlagen und erlaubt so direkt eine E-Mail-Vorlage an den Kunden zu senden oder bereits gesendete Vorlagen einzusehen.

|*Vorhandene Vorgänge anzeigen*
|Zeigt u.a. eine Liste von Retouren und Gutschriften mit Datum und Wert.

|*Warenbestand ermitteln*
|Lädt eine Warenbestandsübersicht für die im Auftrag enthaltenen Varianten. +
Über den Warenkorb sind Nachbestellungen möglich.

|*Artikelliste öffnen* oder *schließen*
|Erlaubt die Auftragspositionen eines Auftrags ein- oder auszublenden

|*Nachbestellung anzeigen*
|Öffnet die auftragsbezogene Nachbestellung im Menü *Nachbestellungen*

|*Rechnungsnummer*
|Öffnet die Rechnung wird

|*Artikel-ID* oder *Varianten-ID*
|Öffnet den Artikel oder die Variante im Menü *Artikel » Artikel bearbeiten*
|====

[#1500]
== Aufträge bearbeiten

Im Menü *Aufträge » Aufträge bearbeiten* werden deine Aufträge in einer Übersicht angezeigt. Klicke auf die Auftrags-ID, um einen Auftrag zu öffnen und die Auftragseinstellungen zu ändern. Aufträge können so lange geändert werden, wie noch kein Dokument für einen Auftrag existiert. Die Einstellungen verteilen sich auf mehrere Tabs, die auf dieser Handbuchseite erläutert werden.

[#1510]
=== Infos und Aktionen in der Auftragsübersicht

Im Menü *Aufträge » Aufträge bearbeiten* werden alle Aufträge mit den wichtigsten Informationen zu jedem Auftrag angezeigt. Neben Informationen zum Kunden, dem Auftragsstatus, dem Zahlungsstatus sowie den Artikeln des Auftrags erkennst du z.B. auf einen Blick, ob der Warenausgang gebucht und ob eine Rechnung erzeugt wurde. So hast du die wichtigsten Vorgänge im Blick, ohne den Auftrag zu öffnen. Zeige mit dem Mauszeiger auf die Symbole und Angaben, um Tooltips mit weiteren Informationen anzuzeigen.

Durch Klick auf ein *Icon* öffne außerdem bestimmte Bereiche des Auftrags. Klicke z.B. auf *Warenbestand*, um den aktuellen Warenbestand der Artikel abzufragen und ggf. Nachbestellungen auszulösen.

In der Auftragsübersicht passt du außerdem bei Bedarf den *Status*, das *Porto*, die *Artikeldaten* oder den *Rabatt* an. Unten wird beispielhaft das Vorgehen bei einer Statusänderung beschrieben.

[.instruction]
Auftragsstatus in der Auftragsübersicht anpassen:

. Klicke auf *Status*. +
→ Eine Liste mit den verfügbaren Status wird angezeigt.
. Wähle den gewünschten Status. +
. Klicke auf *Speichern*, um die Änderung zu sichern. +
→ Der Status wird aktualisiert.

[#1520]
=== Auftrag öffnen und bearbeiten

Das Bearbeitungsmenü des Auftrags öffnest du, indem du auf die Titelzeile in der Auftragsliste klickst. Der Auftrag wird dann in einem eigenen Tab geöffnet. Die verschiedenen Bereiche sind in weitere Tabs unterteilt, die auf dieser Handbuchseite beschrieben werden. Ein geöffneter Auftrag ist an der *ID* im Titel des Tabs erkennbar.

[NOTE]
.Einstellungen bzw. Änderungen speichern
====
Die meisten Tabs eines Auftrags enthalten kein Speichern-Symbol. In diesen Tabs werden die geänderten Einstellungen automatisch gespeichert, z.B. beim Ändern der Markierung oder Mahnstufe im Tab *Übersicht*. Du kannst das Tab wechseln oder den Auftrag gänzlich schließen und erneut öffnen, ohne dass die vorgenommenen Einstellungen verloren gehen. Einige Tabs enthalten jedoch ein Speichern-Symbol, z.B. das Tab *Einstellungen*. Hier kannst du das Tab wechseln, ohne deine Änderungen zu verlieren. Du musst jedoch deine Änderungen speichern, bevor du den Auftrag schließt.
====

[IMPORTANT]
.Grundeinstellungen zur Auftragsbearbeitung durch variable Benutzer
====
Damit variable Benutzer Aufträge öffnen können, müssen im Menü *<<auftraege/grundeinstellungen#, **System » Systemeinstellungen » Aufträge » Einstellungen>>* die Standard-Status für *Retouren* und *Gutschriften* gespeichert werden. In der Grundeinstellung ist dort kein Status voreingestellt. Außerdem müssen variable Benutzer im Benutzerprofil unter *<<basics/admin-aufgaben/benutzer-verwalten#110, Berechtigung » Tab: Menü » Bereich: Aufträge>>* für die Bearbeitung von Aufträgen berechtigt sein.
====

[TIP]
.Aufträge über POS (Kasse) sind nur eingeschränkt bearbeitbar
====
Aufträge, die über <<pos/pos-kassenbenutzer#7, POS (Kasse)>> in das System gelangen, sind aus Gründen der Rechtssicherheit zur Bearbeitung gesperrt. Nur wenige Einstellungen lassen sich bearbeiten.
====

[#1530]
=== Tab: Übersicht

Im Tab *Übersicht* eines Auftrags findest du die wichtigsten Parameter zu einem Auftrag. Du erhältst auf einen Blick Informationen zu Preis, Versandkosten, Mehrwertsteuer, Status etc.

[TIP]
.Tipp: Werte ändern
====
Änderbare Werte erkennst du an einer Dropdown-Liste oder an einem *Stift*. Klicke auf einen Stift, um den betreffenden Parameter zu ändern (z.B. Bild 16, links oben unter *Gewicht*).
====

.Optionen im Tab *Übersicht* eines Auftrags
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Auftrag-ID*
|ID des Auftrags. Diese wird automatisch vergeben und ist nicht änderbar.

|*Kunden-ID*
|ID des Kunden.

|*Kaufabwicklung*
|Öffnet den Auftrag im Bereich *Mein Konto* des Webshops.

|*Eingabe*
|Datum des Auftragseingangs, d.h. wann der Auftrag angelegt wurde bzw. im System eingegangen ist. Das Eingabedatum kann manuell geändert werden, jedoch nur so lange keine Dokumente für den Auftrag existieren.

|*IP-Adresse*
|Zeigt optional die IP-Adresse des Kunden an. +
Die Option *IP-Adresse des Käufers* wird im Menü *<<webshop/webshop-einrichten/bestellvorgang#, System » Systemeinstellungen » Mandant » Mandant wählen » Bestellvorgang » Einstellungen>>* aktiviert bzw. deaktiviert.

|*Markierung*
|Auf Wunsch dem Auftrag eine Markierung zuweisen. Mit Markierungen können Aufträge kategorisiert und so z.B. mit dem Suchfilter gesucht oder für automatische Funktionen, z.B. Ereignisaktionen, verwendet werden.

|*Mahnstufe*
|Wenn ein Kunde den Auftrag nicht bezahlt, werden hier verschiedene Mahnstufen eingestellt. Diese Mahnstufen werden für automatische Prozesse im Mahnvorgang verwendet. +
Ein Beispiel für das Verwenden von Mahnstufen findest du auf der Handbuchseite *<<payment/zahlungsanbieter/mediafinanz#, mediafinanz>>*.

|*Voraussichtlicher Versand*
|Das Datum des voraussichtlichen Versands wird aus dem Datum ermittelt, das bei einer *<<warenwirtschaft/nachbestellungen-verwalten#, Nachbestellung>>* als Liefertermin hinterlegt wurde. Damit der voraussichtliche Versand angezeigt wird, müssen die Nachbestellung sowie der Liefertermin des Artikels bestätigt sein und der Auftrag muss sich in *Status 4* befinden. +
*__Wichtig:__* Die weitere Option *Versanddatum* im Tab *Einstellungen* hat eine andere Funktion, siehe Tabelle 2.

|*Kopieren*
|Kopiert den Auftrag und legt in einem separaten Auftrags-Tab einen neuen Auftrag mit eigener ID an.

|*Löschen*
|Löscht den Auftrag. Es erfolgt eine Sicherheitsabfrage. +
Das Löschen-Icon wird in folgenden Fällen nicht angezeigt: +
- Wenn der Benutzer nicht *<<basics/admin-aufgaben/benutzer-verwalten#90, berechtigt>>* ist, Aufträge zu löschen +
- Nach dem Buchen des Warenausgangs +
- Wenn ein Lieferauftrag angelegt wurde +
Generell sollten Aufträge nicht gelöscht werden. Durch die Verknüpfung mit Artikeln, Versandeinstellungen und weiteren Funktionen, wie Stornierungen und Retouren, kann es nach dem Löschen zu Fehlern an den Verknüpfungspunkten kommen. Neu angelegte Aufträge können jedoch problemlos gelöscht werden.

|*Teilen*
|Teilt den Auftrag. Es erfolgt eine Abfrage, welche Artikel in den Teilauftrag übernommen werden sollen.

|*Retoure; Gutschrift; Gewährleistung*
|Auf die Dropdown-Liste klicken, um das Auftragsdokument anzulegen oder zu suchen.

|*Neuer Auftrag*
|Legt einen neuen Auftrag für den Kunden an. Darin werden automatisch Standardeinstellungen vorgenommen, die ggf. angepasst werden müssen.

|*Rechnungsanschrift*
|Auf das *kleine Plus* klicken, um die Rechnungsanschrift einzublenden. Auch Telefonnummer, E-Mail-Adresse und ggf. eBay-Kontoname des Kunden werden angezeigt.

|*Lieferanschrift*
|Auf das *kleine Plus* klicken, um die Lieferanschrift einzublenden. Ist die Lieferanschrift mit der Rechnungsanschrift identisch, wird *Lieferanschrift* durchgestrichen angezeigt. +
Bei Bedarf auf *Neue Lieferanschrift* klicken, um eine neue Lieferanschrift anzulegen, oder auf *Alle Lieferanschriften auflisten*, um eine Lieferanschrift zu wählen. +
*Lieferanschrift exportieren* = Exportiert die Lieferanschrift im für den gewünschten Versanddienstleister ausgewählten Export-Format.

|*Bankdaten*
|Auf das *kleine Plus* klicken, um die *<<payment/bankdaten-verwalten#, Bankdaten>>* des Kunden einzublenden und bei Bedarf zu bearbeiten.

|*Kundennotizen*
|Zeigt die zum Kunden gespeicherten Kundennotizen an. Auf *Neue Notiz* klicken, um eine Kundennotiz anzulegen. Im Bearbeitungsfenster werden unten die bisherigen Notizen in Gelb angezeigt. Neue Notizen werden mit den üblichen Editor-Funktionen formatiert. Hier gespeicherte Notizen werden sowohl in weiteren Aufträgen des Kunden als auch im Tab *Notizen* der Kundendaten angezeigt.

|*Auftragsnotiz*
|Zeigt die zum Kunden gespeicherten Auftragsnotizen an. Auf *Neue Notiz* klicken, um eine Auftragsnotiz anzulegen. Neue Notizen werden mit den üblichen Editor-Funktionen formatiert.

|*Statushistorie*
|Zeigt eine Liste aller Statusänderungen des Auftrags an.

|*Zahlungshistorie*
|Zeigt Details zu Zahlungen wie Zahlungsart, Währung, Zahlungs-ID oder Datum.

|*Artikelpositionen*
|Zeigt Informationen zu den Artikelpositionen des Auftrags an.

|*Bearbeiten*
|Bei Bedarf die Artikeldaten bearbeiten, d.h. Artikelmenge, Artikeldetails, Preise, Rabatte und Mehrwertsteuer-Sätze.

|*Hinzufügen*
|Über die integrierte Artikelsuche bei Bedarf weitere Artikel zum Auftrag hinzufügen.

|*Lagerort zuordnen*
|Ordnet der Auftragsposition einen Lagerort zu. Ist für einen Artikel mehr als ein Lagerort hinterlegt, werden die Lagerorte anhand der Position priorisiert. Wurde kein Lagerort hinterlegt, wird der *Standard-Lagerort* zugeordnet. +
Die Zuordnung des Lagerorts ist für Pick-/Packlisten relevant. +
*__Tipp__*: Lagerorte können Artikeln auch per *<<automatisierung/ereignisaktionen#, Ereignisaktion>>* zugeordnet werden.

|*Zuordnung lösen*
|Hebt die aktuelle Zuordnung des Lagerorts auf. Durch erneutes Klicken auf *Lagerort zuordnen* (siehe oben) kann eine neue Zuordnung vorgenommen und diese so an aktuelle Lagergegebenheiten angepasst werden.
|====

Aufträge teilen

Aufträge teilst du im Menü *<<auftraege/auftraege-verwalten#1530, Aufträge » Aufträge bearbeiten » Auftrag öffnen » Tab: Übersicht>>*. Ein Auftrag darf nur unter folgenden Bedingungen geteilt werden:

* Es ist noch kein Zahlungseingang erfolgt.
* Es wurde kein Warenausgang gebucht.
* Es wurde keine Rechnung erzeugt.

[#1540]
=== Tab: Einstellungen

Im Tab *Einstellungen* sind die grundlegenden Parameter eines Auftrags hinterlegt, wie *Status*, *Herkunft* oder *Zahlungsart*.

.Optionen im Tab **Einstellungen** eines Auftrags
[cols="1,2"]
|====
|Einstellung |Erläuterung

|**Status; +
Auftragstyp; +
Eigner; +
Herkunft; +
Mandant (Shop)**
| +
+
Diese Optionen werden je nach Zustand bzw. Gegebenheiten angezeigt, können jedoch geändert werden.

|*Lager*
|Lager des Artikels des Auftrags bzw. das Hauptlager. Bei Bedarf auf *Lagerkorrektur* klicken, um das Lager zu ändern. +
*_Wichtig_*: Die Option *Lagerkorrektur* gleicht die Anzeige im Tab *Einstellungen* des Auftrags mit dem Lager ab, das an den enthaltenen Auftragspositionen hinterlegt ist. Die Option erscheint nur, wenn du im Menü *<<auftraege/grundeinstellungen#, System » Systemeinstellungen » Aufträge » Einstellungen>>* die Option *b) pro Artikelposition kann ein Lager zugeordnet werden* gewählt hast. Änderst du im Tab *Übersicht* an einer Auftragsposition manuell das Lager und wird das neue Lager nicht automatisch in das Tab *Einstellungen* des Auftrags übernommen, klicke auf *Lagerkorrektur*, um die Anzeige des Lagers zu aktualisieren.

|*Status*
|Der Auftragsstatus *[7] Warenausgang gebucht* kann nicht in einen niedrigeren Status geändert werden. Grund ist, dass die Ware bereits verschickt wurde. Sollte dies trotzdem gewünscht sein, muss die Buchung des Warenausgangs vorher zurückgesetzt werden. Danach ist die Änderung in einen niedrigeren Auftragsstatus möglich.

|*Warenausgang*
|Zeigt an, ob der Warenausgang gebucht wurde und ggf. das Buchungsdatum. +
Bei Bedarf auf *Warenausgang* klicken, um den Warenausgang manuell zu buchen.

|*Versanddatum*
|Das Versanddatum wird vom Artikel aus der Option **Erscheinungsdatum** übernommen und ist damit eine Funktion für *<<auftraege/auftraege-verwalten#1100, Vorbestellungen>>*. Sind mehrere vorbestellte Artikel im Auftrag vorhanden, wird das am weitesten in der Zukunft liegende Datum hier übernommen. Das Datum ist manuell änderbar.

|*Rückgabedatum*
|Das Datum einer Retoure hinterlegen, wenn Artikel des Auftrags zurückgegeben wurden. Dient als Information zu einer Retoure, damit diese nicht extra geöffnet werden muss.

|*Währung*
|Die Währung des Auftrags.

|*Zahlungsart; +
Versanddienstleister; +
Versandprofil &amp; Porto*
|Diese Optionen werden je nach Zustand bzw. Gegebenheiten angezeigt, können jedoch geändert werden. +
Um Änderungen vorzunehmen, eine *Zahlungsart* aus der Dropdown-Liste wählen bzw. auf den *Stift* klicken, um die Versandoptionen zu ändern.

|*Zahlungsziel*
|Die Werte für *Valuta (Tage)*, *Skonto (Tage)* bzw. *Skonto (%)* werden einzeln oder kombiniert hinterlegt und damit die Zahlungsbedingungen gestaltet. Wenn die Werte in den <<crm/kontakte-verwalten#100, Kundendaten>> hinterlegt sind, werden sie vom System automatisch übernommen und hier eingesetzt, können jedoch geändert werden.

|*Versanddienstleister*
|Der Versanddienstleister, über den die Artikel des Auftrags versendet werden.

|*Versandprofil &amp; Porto*
|Das Versandprofil und die Portokosten des Auftrags.

|*Ext. Auftragsnummer*
|Bei Aufträgen, die z.B. aus einem externen System stammen, die externe Auftragsnummer eintragen.

|*Zeichen Kunde*
|Zeigt ein Zeichen bzw. einen Text an, den der Kunde bei der Bestellung hinterlegen kann, wenn das Feld **Ihr Zeichen** für den Bestellvorgang sichtbar ist.
|*Pakete*
|Anzahl der zum Auftrag gehörenden Pakete. +
__**Wichtig**__: Dieser Eintrag ist unabhängig von der im Versand-Center eingestellten Paketanzahl. Wenn du die Anzahl der Pakete verändern möchtest, passe dies im Versand-Center an.

|*Paketnummer*
|Paketnummer des Versandpakets +
Wenn eine Paketnummer hinterlegt wurde, kann das Paket über *Vorschau* verfolgt werden. Allerdings nur, wenn unter *<<fulfillment/versand-vorbereiten#800,System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister>>* ein entsprechender Tracking-Code hinterlegt wurde. Sonst wird das Vorschau-Symbol nicht angezeigt.
|====

[#1550]
=== Tab: Mail

Im Tab *Mail* sind alle E-Mail-Vorlagen verfügbar, die du unter *<<crm/e-mails-versenden#1200, System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen>>* konfiguriert hast und die gemäß des Template-Typs für Aufträge sichtbar sind. Du kannst diese Vorlagen per manueller Aktion an den Kunden schicken, wenn z.B. eine außerplanmäßige E-Mail nötig ist bzw. eine, die nicht durch eine automatische Aktion erfolgt. Gehe wie unten beschrieben vor, um eine E-Mail-Vorlage zu verschicken.

[.instruction]
E-Mail-Vorlage verschicken:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Auftrag.
. Klicke auf das Tab *Mail*.
. Wähle ggf. die *Sprache*.
. Wähle im Tab *E-Mail-Vorlagen* das Tab, das die gewünschte E-Mail-Vorlage enthält.
. Markiere die Vorlage.
. Klicke auf *Direkter E-Mail-Versand*. +
→ Die E-Mail wird versendet.
. Warte, bis der Versand durch eine Meldung bestätigt wird.

Bei nicht erfolgreichem E-Mail-Versand prüfe die *<<crm/e-mails-versenden#, Zugangsdaten>>*. Im Menü *<<daten/api-log#, Daten » API-Log>>* werden die Fehlermeldungen zum Vorgang *E-Mail* gespeichert.

[IMPORTANT]
.Kunden ein neues Passwort senden
====
Die E-Mail-Vorlage *Sende Kunde neues Passwort* ist für den Versand aus einem Auftrag nicht verwendbar. Diese E-Mail-Vorlage versendest du im Datensatz des Kunden. Dort ist im Tab *Einstellungen* das Tab *Passwort* verfügbar, wenn sich ein Kunde im Webshop registriert hat. Hier ist der Versand dieser E-Mail-Vorlage vorgesehen.
====

Das Tab *Gesendete E-Mails* bietet eine Übersicht der gesendeten E-Mail-Vorlagen. Dort werden *Datum*, *Empfänger*, die Bezeichnung der *Vorlage* sowie die *Auftrags-ID* aufgeführt. Es werden alle an den Kunden gesendeten E-Mails aufgelistet, auch die von anderen Aufträgen.

[#1560]
=== Tab: Zahlung

Im Tab *Zahlung* siehst du alle Zahlungen und Teilzahlungen, die zum Auftrag gehören. Über Filter suchst du außerdem nach einzelnen Zahlungen des Auftrags. Im Tab *Zahlungsverkehr* werden in der obersten Leiste der Rechnungsbetrag, der bereits bezahlte Rechnungsbetrag sowie der noch offene Rechnungsbetrag angezeigt. So hast du anhand dieser Zahlen direkt einen Überblick. Außerdem buchst du in diesem Tab Zahlungen manuell über die Schaltfläche *Zahlung buchen*.

[TIP]
.Fehlende Zahlungseingänge
====
Wenn nicht alle Zahlungen des Auftrags angezeigt werden, ändere den Filter *Eingangsdatum von*, um den Zeitraum, ab dem gesucht wird, anzupassen.
====

Details zur manuellen Buchung von Zahlungen findest du auf der Handbuchseite *<<payment/zahlungen-verwalten#, Zahlungen verwalten>>*.

[#1570]
=== Tab: Belege

Im Tab *Belege* erzeugst du Belege, d.h. z.B. eine Auftragsbestätigung, einen Lieferschein oder eine Rechnung.
Nachdem du Dokumente zu einem Auftrag erzeugt hast, kann das Eingabedatum des Auftrags nicht mehr geändert werden.
Die Dokumente werden anhand von Dokumentenvorlagen erstellt, die im Menü *<<auftraege/auftragsdokumente#, Einstellungen » Aufträge » Dokumente>>* hinterlegt wurden. Prüfe daher vor der Erstellung der Belege bzw. auch bei einer Fehlermeldung, ob du die Dokumentenvorlagen erstellt hast.

[TIP]
.Tipp: Dokumentenvorlagen kopieren
====
Wenn du bei der Einrichtung der *<<auftraege/auftragsdokumente#20, Dokumentenvorlagen>>* Zeit sparen möchtest, kopiere sie von einer bereits konfigurierten Dokumentenvorlage und passen sie nach Bedarf an.
====

Die Belege werden jeweils vor der Erstellung konfiguriert. Du kannst je je nach Beleg verschiedene Parameter anpassen, z.B. bei einer Rechnung das Datum, das *Zahlungsziel*, ob Skonto angerechnet werden soll und ob der Warenausgang gebucht werden soll. Außerdem kann ein Statuswechsel bei Erzeugung des Belegs veranlasst werden.

[#1580]
=== Tab: Kunde

Im Tab *Kunde* wird der <<crm/kontakte-verwalten#, Kontaktdatensatz>> angezeigt. Du kannst diese Informationen bearbeiten.

[#1590]
=== Tab: Tickets

Im Tab *Tickets* werden *<<crm/ticketsystem-nutzen#, Tickets>>* des Kunden angezeigt. Du kannst diese Tickets direkt bearbeiten, ohne ins Ticketsystem zu wechseln.

[#1600]
=== Tab: Aufträge

Im Tab *Aufträge* findest du die weiteren Aufträge des Kunden des betreffenden Auftrags. Du kannst die Aufträge des Kunden dort auch bearbeiten.

[#1610]
=== Tab: Waren

Im Tab *Waren* werden die *<<warenwirtschaft/warenbestaende-verwalten#, Warenbestandsdaten>>* der Artikel angezeigt, die in dem Auftrag enthalten sind. Das Tab bietet die volle Funktionalität des Menüs *Warenbestand* mit Ausnahme der Filterfunktionen. Du kannst Warenbestände einsehen und bei Bedarf konfigurieren.

[#1620]
=== Tab: Nachbestellung

Im Tab *Nachbestellung* wählst du Auftragspositionen für eine Nachbestellung. Dabei wählst du, ob eine Nachbestellung nur für den Auftrag erzeugt werden soll oder ob eine Nachbestellung erzeugt werden soll, der auch nachbestellte Auftragspositionen aus anderen Aufträgen hinzugefügt werden. +
Eine Bedingung in beiden Fällen ist, dass der Lieferant (Kunde) und das Lager bei allen Positionen gleich sind. Ist das nicht der Fall, wird für jede Lieferanten-/Lager-Konstellation eine separate Nachbestellung erzeugt.

[NOTE]
.Lieferanten hinterlegen!
====
Damit eine Bestellung möglich ist, muss für jeden Artikel ein Lieferant hinterlegt sein.
====

[#1630]
==== Auftragspositionen wählen

Gehe wie unten beschrieben vor, um einzelne Positionen bzw. alle Positionen eines Auftrags für die Nachbestellung zu wählen.

[.instruction]
Einzelne Positionen für die Nachbestellung wählen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den gewünschten Auftrag.
. Klicke auf das Tab *Nachbestellung*.
. Wähle die *Varianten*, die du nachbestellen möchtest.
. Klicke auf *Markierte Positionen nachbestellen*. +
→ Eine allgemeine, offene Nachbestellung wird erzeugt, in die neben den markierten Positionen auch Auftragspositionen aus anderen Aufträgen überführt werden, wenn diese über diese Schaltfläche gewählt wurden. Die Teilmengen werden unter *Menge* angezeigt.

Wenn du bestimmte Artikelpositionen für die Nachbestellung gewählt hast, wird *Alle Positionen nachbestellen* deaktiviert und ist nicht mehr wählbar.

[.instruction]
Alle Positionen für eine Nachbestellung wählen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den gewünschten Auftrag.
. Klicke auf das Tab *Nachbestellung.*
. Klicke auf *Alle Positionen nachbestellen*. +
→ Es wird nur für diesen Auftrag eine Nachbestellung erzeugt, die alle Positionen des Auftrags enthält. Die Teilmengen werden unter *Menge* angezeigt.

[#1640]
==== Nachbestellung ausführen

[TIP]
.Bedeutung der Angaben unter Menge
====
In der Spalte *Menge* siehst du auf einen Blick die gelieferte Menge (grüne Zahl), die offene Menge (rote Zahl) und die bestellte Menge. +
Unter *geliefert* werden Teilmengen angezeigt, wenn diese als Teillieferung in der Nachbestellung unter *Status* gebucht werden. +
====

Nachdem du die Auftragspositionen gewählt haben, führst du nun die eigentliche Nachbestellung aus. Gehe dazu wie folgt vor:

[.instruction]
Nachbestellung ausführen:

. Klicke im Tab *Nachbestellung* des Auftrags auf einen *Warenkorb*. +
→ Das Menü *Nachbestellung* wird geöffnet. Im Tab *Base* der Nachbestellung werden die bestellten Artikel im Bereich *Artikeldaten* angezeigt.
. Klicke im Bereich *Grunddaten* bei der Option *Bestellen* auf das *Zahnrad*. +
→ Die Bestellung wird ausgeführt. Die Bestelldaten werden auch im Auftrag im Tab *Nachbestellung* angezeigt.

[TIP]
.EK und Menge anpassen
====
Du kannst im Bereich *Artikeldaten* des Tabs *Base* die Optionen *EK* und *Menge* anpassen, bevor die Nachbestellung ausgeführt wird.
====

Weitere Details zur Bearbeitung der Nachbestellung und wie du z.B. Teilmengen buchen findest du auf der Handbuchseite *<<warenwirtschaft/nachbestellungen-verwalten#, Nachbestellungen>>*.

[#1650]
==== Variantenmengen einer Nachbestellung erhöhen

Bei noch offenen Nachbestellungen kannst du die Mengen für Varianten erhöhen. Dies ist für Werte möglich, für die bei der *<<artikel/artikel-verwalten#410, Mengenverteilung>>* prozentuale Anteile hinterlegt wurden. Gehe wie folgt vor, um die Menge für Varianten zu erhöhen.

[.instruction]
Menge für Variante erhöhen:

. Klicke auf *Mengen für Varianten erhöhen*.
. Wähle die *ID der Nachbestellung* und den *Artikel* aus den Dropdown-Listen.
. Wähle das *Attribut* und den *Wert*.
. Trage die *Menge* ein.
. Klicke auf *Menge erhöhen*.
. Wiederhole diese Schritte für jede gewünschte weitere Variante, um die Mengen zu erhöhen.

[#1660]
=== Tab: Lief

Im Tab *Lief* werden *<<auftraege/auftraege-verwalten#300, Lieferaufträge>>* erstellt. Du siehst dort die Artikelpositionen des Auftrags, die noch nicht in Lieferaufträge überführt wurden.

[.instruction]
Lieferaufträge manuell anlegen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den gewünschten Auftrag.
. Klicke auf das Tab *Lief*.
. Trage in das Feld *LiefAufMenge* (Menge für den Lieferauftrag) die Menge ein, die in den Lieferauftrag überführt werden soll. +
→ Die eingetragene Menge darf nicht größer sein als die unter *NZMenge* (nicht zugeordnete Menge) angezeigte Menge.
. Klicke auf das *Zahnrad*, um den Lieferauftrag anzulegen.

[NOTE]
.Lieferaufträge automatisch anlegen
====
Klicke auf *Lieferauftrag automatisch anlegen*, um die Aufträge entsprechend der unter *<<auftraege/auftraege-verwalten#300, System » Systemeinstellungen » Aufträge » Auftragstypen » Lieferauftrag>>* im Feld *Aufträge in Lieferaufträge splitten nach* gewählten Einstellung anzulegen. Es werden alle Auftragspositionen in Lieferaufträge geteilt. Diese Funktion kannst du nur nutzen, wenn noch kein Lieferauftrag zu dem Auftrag besteht.
====

Für die in einem Lieferauftrag enthaltene Menge wird die Bestandsreservierung beim Anlegen eines Lieferauftrags vom Hauptauftrag auf den Lieferauftrag übertragen. Werden Lieferaufträge einzeln angelegt und im Hauptauftrag sind noch Artikel vorhanden, werden diese Artikel ebenfalls reserviert.

[TIP]
.Tipp: Auftragspositionen im Hauptauftrag bearbeiten
====
Auftragspositionen können zum Hauptauftrag hinzugefügt oder daraus gelöscht werden. Allerdings können nur Auftragspositionen, die nicht in Lieferaufträgen enthalten sind, aus dem Hauptauftrag gelöscht werden. Die Menge der Artikel im Hauptauftrag lässt sich erhöhen oder verringern. Du solltest jedoch nur nicht zugeordnete Mengen löschen. Technisch möglich ist auch das Löschen von Positionen, die bereits in einem Lieferauftrag enthalten sind. Dies solltest du jedoch vermeiden.
====

[#1670]
=== Rechnung korrigieren und stornieren

Wenn du oder dein Kunde nachträglich feststellen, dass eine Angabe auf der Rechnung fehlerhaft ist und du diese korrigieren möchtest, erstelle einen Stornobeleg und erzeuge anschließend eine neue Rechnung.
Durch Stornieren der Rechnung können Änderungen schnell nachvollzogen werden, da sowohl die alte Rechnung, der Stornobeleg und die neue Rechnung vorhanden sind. Wenn du den gesamten Auftrag stornieren möchtest, nutze den Auftragsstatus *storniert*. Wenn du den Auftrag bearbeiten möchtest und einige Angaben korrigierst, nutze den Stornobeleg.

[#1680]
==== Vorlage Stornobeleg einrichten

Richte sich zunächst die Vorlage für das Dokument Stornobeleg ein. Der schnellste Weg ist in diesem Fall das Übernehmen der Einstellungen aus der Standard-Dokumentvorlage oder das Kopieren der Einstellungen einer Rechnungsvorlage.  +
Im Folgenden wird kurz das Übernehmen der Standard-Dokumentvorlage beschrieben.

[.instruction]
Vorlage einrichten:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Stornobeleg*.
. Wechsle in das Tab *Transfer*.
. Klicke unter *Einstellungen aus Standard-Dokumentenvorlage übernehmen* auf *Übernehmen*.

Da die Einstellungen der Vorlage für Stornobelege mit den Einstellungen der Vorlage für Rechnungen übereinstimmen, findest du nähere Erläuterungen zu den einzelnen Einstellungen auf der Seite *<<auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnungen erzeugen>>*.

[#1690]
==== Rechnung korrigieren

Eine Rechnung korrigierst du, indem du sie zunächst stornierst. Das Stornieren einer Rechnung dient der nachvollziehbaren Korrektur von rechnungsrelevanten Daten und nicht der Stornierung eines Auftrages. Anschließend kann der Auftrag wieder bearbeitet werden und eine neue Rechnung erzeugt werden.

[.instruction]
Rechnung korrigieren:

.  Öffne das Menü *Aufträge » Aufträge bearbeiten*.
.  Öffne den Auftrag, dessen Rechnun du stornieren möchtest.
.  Wechsle in das Tab *Belege*.
.  Wähle aus der Dropdown-Liste *Beleg erstellen* den *Stornobeleg*.  +
→ Ein Fenster mit optionalen Einstellungen wird geöffnet.
. *Speichere* die Einstellungen.  +
→ Der Stornobeleg wird erzeugt und die Auftragseinstellungen entsperrt.
.  Bearbeite jetzt die Daten, die du korrigieren möchtest.  +
→ Trage z.B. eine Umsatzsteueridentifiaktionsnummer in der Rechnungsanschrift nach.
.  Wechsle wieder in das Tab *Belege*.
.  Wähle aus der Dropdown-Liste *Beleg erstellen* die *Rechnung*.  +
→ Ein Fenster mit optionalen Einstellungen wird geöffnet.
. *Speichere* die Einstellungen.  +
→ Die Rechnung wird erzeugt und die Auftragseinstellungen gesperrt.

[#1700]
==== Gruppenfunktionen nutzen und mehrere Aufträge bearbeiten

plentymarkets hält viele Hilfsmittel für bestmögliche Produktivität in der Auftragsbearbeitung bereit. Die beschriebene Gruppenfunktion gehört dazu. Du kannst damit eine oder mehrere Aktionen an mehreren Aufträgen gleichzeitig ausführen und so viele manuelle Eingaben und damit verbundene mögliche Eingabefehler vermeiden.

Ein Praxisbeispiel verdeutlicht die Anwendungsmöglichkeiten der Gruppenfunktion: Ein begehrter Artikel in deinem Shop ist vorübergehend nicht lieferbar, es liegen aber bereits eine ganze Reihe von Bestellungen dafür vor. Gegen solche Lieferverzögerungen sind Händler in aller Regel machtlos, müssen aber die betroffenen Kunden schnellstmöglich über einen solchen Umstand informieren. Von Kunden, die bereits per Vorkasse bezahlt haben, ist verständlicherweise wenig Geduld zu erwarten.

Mit der Gruppenfunktion ist diese Aufgabe schnell erledigt: Suche mithilfe der **Artikel-ID** oder der *Artikelbezeichnung* alle Aufträge im Status *ALLE &lt; 7*, denn deine Aktion ist nur für die Aufträge relevant, bei denen der Warenausgang noch nicht erfolgt ist. Hat dein System alle Aufträge gefunden, wähle unter *Gruppenfunktion* die Option *E-Mail-Service* aus, um deine Kunden per E-Mail zu erreichen. Sobald eine Gruppenfunktion ausgewählt wird, erscheint ein neues Fenster mit spezifischen Einstellungen.

Im Beispiel ist der Kunde der E-Mail-Empfänger. Eine *<<crm/e-mails-versenden#1200, E-Mail-Vorlage>>* musst du vorher selbst erstellt haben. Eine **Markierung** zu setzen ist nicht notwendig, aber durchaus sinnvoll. Bevor du die Aktion über *Anwenden* ausführst, überzeuge dich nochmals davon, dass alle gewünschten Aufträge mit einem Häkchen ausgewählt wurden.

[TIP]
.Status &gt;= 7
====
Beachte, dass ein *Auftragsstatus &gt;= 7* nicht verringert werden kann, ohne dass vorher die Buchung des Warenausgangs zurückgesetzt wird. Für Aufträge mit Auftragsstatus ab Status 7 musst du vorher den *Warenausgang* per Gruppenfunktion rückbuchen.
====

Mit der *Gruppenfunktion* ist es möglich, Prozesse für eine größere Menge an Aufträgen gleichzeitig auszuführen. Damit werden Vorgänge, z.B. eine Statusänderung oder ein E-Mail-Service, auf alle markierten Aufträge angewendet. Du kannst auch bestimmte Aufträge per Gruppenfunktion löschen. Die Gruppenfunktion ist besonders zu empfehlen, wenn viele Aufträge bearbeitet werden müssen und die individuelle Bearbeitung sehr zeitaufwändig wäre.

Nachfolgend findest du ein Beispiel für die Verwendung der Gruppenfunktion.

[.instruction]
Beispiel Warenausgang per Gruppenfunktion buchen:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Markiere die *Aufträge*, für die Warenausgang per Gruppenfunktion gebucht werden soll.
. Klicke auf *Gruppenfunktion*.
. Markiere die Option *Warenausgang buchen*.
. Wähle das *Datum* und die *Uhrzeit*. +
→ Für das Datum wird automatisch das aktuelle Datum gewählt, dies ist jedoch änderbar. Die Wahl des Datums ist bei dieser Gruppenfunktion Pflicht.
. Klicke auf *Anwenden*, um die Aktion auszuführen.

[IMPORTANT]
.Grundeinstellungen zur Auftragsbearbeitung durch variable Benutzer
====
Damit variable Benutzer Aufträge öffnen können, müssen im Menü *<<auftraege/grundeinstellungen#, System » Systemeinstellungen » Aufträge » Einstellungen>>* die Standard-Status für *Retouren* und *Gutschriften* gespeichert worden sein. In der Grundeinstellung ist dort kein Status voreingestellt.
Außerdem müssen diese Benutzer für die Erstellung und Bearbeitung von Aufträgen im Benutzerprofil unter *<<basics/admin-aufgaben/benutzer-verwalten#110, Berechtigung » Tab: Menü » Bereich: Aufträge>>* berechtigt werden.
Damit variable Benutzer Aufträge der Typen *Retoure*, *Gewährleistung* und *Reparatur* anlegen können, müssen sie für die im Menü *<<auftraege/grundeinstellungen#, System » Systemeinstellungen » Aufträge » Einstellungen>>* hinterlegten Standard-Status dieser drei Auftragstypen berechtigt sein. Die Berechtigung erfolgt im *Benutzerprofil* des variablen Benutzers unter *<<basics/admin-aufgaben/benutzer-verwalten#100, Berechtigung » Tab: Sichtbarkeiten>>*.
====
