= Auftragsherkunft
:lang: de
include::{includedir}/_header.adoc[]
:position: 50
:url: auftraege/auftragsherkunft
:id: G39SVHL
:keywords: Auftragsherkunft, Auftragherkunft, Auftragsherkünfte, Herkunft, Herkünfte, Referrer, Kanal, Kanäle, Omni-Channel, Herkunft aktivieren, Auftragsherkunft aktivieren, Quelle, Quellen, Plugin-Herkunft, Unterherkunft, Unterherkünfte, Marktplatz, POS, ID, Herkunfts-ID, Auftrag, Länderplattform, manuelle Herkunft, manuelle Herkünfte, Auswahlspalte, Referrer-ID, Auftragsherkunft löschen, Herkunft löschen, löschen, Filter Herkunft, allgemeine Herkunft, allgemeine Herkünfte, Herkunftsangabe
:author: team-order-payment

Omni-Channel-Verkauf mit plentymarkets bedeutet, dass du deine Artikel über eine Vielzahl von Kanälen anbieten und so Aufträge aus den verschiedensten Quellen generieren kannst.
Einige Auftragsherkünfte sind im System vorab angelegt und können nicht geändert werden. Andere Herkünfte werden automatisch hinzugefügt, zum Beispiel durch das Einbinden eines Plugins oder <<pos#, plentyPOS>>.
Plugin-Herkünfte können nicht gelöscht werden. Du kannst Herkünfte aber auch manuell hinzufügen.

Jede Herkunft erhält eine eigene ID. Manche Herkünfte haben Unterherkünfte, bei denen die IDs dann Dezimalstellen haben. Die Marktplätze *Amazon* und *eBay* sowie plentyPOS haben je eine allgemeine Herkunft und Unterherkünfte.
Bei eBay oder Amazon hat jede Länderplattform eine eigene Unterherkunft, ebenso wie jede plentyPOS-Kasse.

Unabhängig von der Herkunft sind alle Aufträge im Menü *Aufträge » Aufträge bearbeiten* aufgelistet und bearbeitbar. Dort ist die Herkunft an jedem Auftrag hinterlegt. In der zum Auftrag gehörenden Zeile wird die ID der Herkunft angezeigt. Wenn du mit der Maus über die ID gehst, wird ein Tooltip mit dem Namen der Herkunft eingeblendet. Zudem ist die Herkunft im Tab *Einstellungen* eines Auftrags erkennbar.
Diese Herkunft kann geändert werden, allerdings nur bei manuell angelegten Herkünften und auch nur solange noch keine Rechnung erzeugt wurde.

[#10]
== Auftragsherkunft aktivieren

Bereits vorhandene oder automatisch durch Plugins hinzugefügte Herkünfte musst du nur noch aktivieren. Gehe dafür wie im Folgenden beschrieben vor.

[.instruction]
Auftragsherkunft aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Wähle eine Herkunft.
. Aktiviere die Herkunft durch Setzen eines Häkchens.  +
→ Beachte außerdem die Erläuterungen in <<tabelle-einstellungen-aktivierung-auftragsherkunft>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#20]
== Auftragsherkunft manuell erstellen

Wie in der Einleitung bereits erwähnt, kannst du dem System Auftragsherkünfte hinzufügen. Gehe wie im Folgenden beschrieben vor, um eine Auftragsherkunft manuell anzulegen.

[.instruction]
Auftragsherkunft erstellen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Klicke auf *Neu* (icon:plus-square[role="green"]).  +
→ Eine Zeile wird hinzugefügt und der Cursor ist direkt in der Namensspalte.
. Trage einen Namen für die *Auftragsherkunft* ein.
. Nimm die Einstellungen gemäß <<tabelle-einstellungen-aktivierung-auftragsherkunft>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-einstellungen-aktivierung-auftragsherkunft]]
.Einstellungen für Auftragsherkünfte
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *ID*
|Jede Auftragsherkunft erhält eine eigene ID. Diese wird automatisch vom System zugewiesen und ist nicht änderbar. Für manuelle Herkünfte stehen die IDs im Bereich 9-100 zur Verfügung. Die IDs 1-8 sowie die IDs ab 101 sind von fest im System hinterlegten Auftragsherkünften besetzt. Unterherkünfte sind an dezimalen IDs zu erkennen, zum Beispiel 2.08 für eBay Germany. +
_Hinweis_: Wenn alle freien IDs für manuell angelegte Auftragsherkünfte vergeben sind, ist die Schaltfläche *Neu* (icon:plus-square[role="green"]) nicht mehr sichtbar, da keine neuen Herkünfte hinzugefügt werden können.

| *Name*
|Der hier eingetragene Name für die Herkunft wird im System angezeigt, zum Beispiel bei der Auftragssuche. Der Name kann hier jederzeit geändert werden.

| *Interner Name*
|Der interne Name ist nicht änderbar und wird nicht im System angezeigt. Nur fest hinterlegte Auftragsherkünfte erhalten einen internen Namen, manuell angelegte Herkünfte nicht.

| *Eigner*
|Die Person wählen, die je nach Auftragsherkunft für einen Auftrag automatisch als Eigner eingetragen werden soll. Zur Auswahl stehen die unter <<business-entscheidungen/benutzerkonten-zugaenge#, Einrichtung » Einstellungen » Benutzer » Konten>> berechtigten Personen.

| *Auswahlspalte*
|Aktiviere die Herkunft durch das Setzen eines Häkchens. Die Herkunft wird dann in anderen Menüs angezeigt, zum Beispiel im Tab *Einstellungen* eines Auftrags. +
Deaktivierst du die Herkunft, wird sie in anderen Menüs nicht mehr angezeigt. +
Du kannst alle Herkünfte auf einmal aktivieren oder deaktivieren, indem du im Tabellenheader auf *Alles auswählen* klickst.

| *Webshop-URL kopieren*
|URL der Auftragsherkunft in den Zwischenspeicher kopieren. +
Die URL wird zum Beispiel für Affiliate-Dienste benötigt. Sie enthält die jeweilige ID als sogenannte Referrer-ID.

| *Im Webshop öffnen* (icon:eye[role="blue"])
|Ein Klick auf Vorschau (icon:eye[role="blue"]) öffnet den Webshop mit Referrer-ID der Herkunft. Alle Preise werden für die betreffende Auftragsherkunft angezeigt.  +
Die Vorschau funktioniert nur korrekt, wenn du Verkaufspreise angelegt und für die Herkunft aktiviert hast. Außerdem muss der Verkaufspreis an einer Variante hinzugefügt und ein Wert eingetragen werden.

| *Löschen*
|*Löschen* klicken, um eine Auftragsherkunft zu löschen. Es können nur Auftragsherkünfte gelöscht werden, die du selbst angelegt hast. Vom System automatisch angelegte Herkünfte sind nicht löschbar.
|====

[TIP]
.Herkunft wird für Affiliate-Dienstleister benötigt
====
Die Auftragsherkunft ist auch Voraussetzung für die Kooperation mit Affiliate-Partnern. Diese Partner vermitteln dir kaufinteressierte Besucher über definierte Tracking-URLs und erwarten bei einem durch sie vermittelten Verkauf eine Provision.
====

[#30]
== Aufträge nach Auftragsherkunft filtern und auswerten

Die Auftragssuche im Menü *Aufträge » Aufträge bearbeiten* bietet viele Filter, um deine Suche einzugrenzen. Der Filter *Herkunft* sucht Aufträge nach der Auftragsherkunft (zum Beispiel gefiltert nach Mandant (Shop), Amazon, eBay etc.). Für Amazon und eBay gibt es sowohl allgemeine Herkünfte als auch eine Unterherkunft für jede Länderplattform.

Bei monatlichen Auswertungen ist es sinnvoll, Suchfilter zu kombinieren und einen zusätzlichen Datumsfilter, zum Beispiel das Datum des Auftragseingangs, zu wählen und einen genauen Zeitraum festzulegen.

Die Herkunftsangabe ist für die Erfolgskontrolle in deinem Shop wichtig. Nur über diese Einstellung kannst du nachvollziehen, welche Plattformen für dein Warenangebot profitabel sind. Neben der Suchfunktion im Menü *Aufträge bearbeiten* stehen dir im Bereich <<business-entscheidungen/plenty-bi/statistiken#, Statistik>> weitere Auswertungsmöglichkeiten zur Verfügung. Dort kannst du über die Herkunftsangabe die Umsätze der Auftragsherkünfte sehen. So entscheidest du fundiert, wie du dein Werbebudget künftig immer gezielter und effizienter einsetzt.
