= Auftragsherkunft
:lang: de
include::{includedir}/_header.adoc[]
:position: 50
:url: auftraege/auftragsherkunft
:id: G39SVHL

Omni-Channel-Verkauf mit plentymarkets bedeutet, dass du deine Produkte über eine Vielzahl von Kanälen anbieten und so Aufträge aus den verschiedensten Quellen generieren kannst.
Einige Auftragsherkünfte sind im System vorab angelegt und können nicht geändert werden.
Andere Herkünfte werden automatisch hinzugefügt, z.B. durch das Einbinden eines Plugins oder plentymarkets POS.
Plugin-Herkünfte können nicht gelöscht werden. Auch manuell können Herkünfte angelegt werden.
Jede Herkunft hat eine ID und manche Herkünfte haben Unterherkünfte, bei denen die IDs dann Dezimalstellen haben.
Die Marktplätze *Amazon* und *eBay* so wie plentymarkets POS haben je eine allgemeine Herkunft und Unterherkünfte.
Bei eBay oder Amazon hat jede Länderplattform eine eigene Unterherkunft sowie jede plentymarkets POS-Kasse eine eigene Unterherkunft erhält.
Alle Aufträge, egal welcher Herkunft, werden in einem gemeinsamen Auftragsmenu gesammelt.
Im Tab *Einstellungen* eines Auftrags ist die Herkunft erkennbar.

== Auftragsherkunft aktivieren

Bereits vorhandene oder automatisch durch Plugins hinzugefügte Herkünfte musst du lediglich noch aktivieren.

[.instruction]
Auftragsherkunft aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Wähle eine Herkunft.
. Setze ein Häkchen in der Auswahlspalte der Herkunft.  +
→ Beachte außerdem die Erläuterungen in <<tabelle-einstellungen-aktivierung-auftragsherkunft>>.
. *Speichere* die Einstellungen.

== Auftragsherkunft manuell anlegen

Gehe wie unten beschrieben vor, um manuell eine Auftragsherkunft anzulegen.

[TIP]
.Herkunft wird für Affiliate-Dienstleister benötigt
====
Die Auftragsherkunft ist auch Voraussetzung für die Kooperation mit Affiliate-Partnern. Diese Partner vermitteln dir kaufinteressierte Besucher über definierte Tracking-URLs und erwarten bei einem durch sie vermittelten Verkauf eine Provision.
====

[.instruction]
Auftragsherkunft anlegen:

. Öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft*.
. Klicke auf *Neu*.  +
→ Eine Zeile wird hinzugefügt und der Maus-Cursor ist direkt in der Namensspalte.
. Trage einen Namen für die *Auftragsherkunft* ein.
. Nimm die Einstellungen gemäß <<tabelle-einstellungen-aktivierung-auftragsherkunft>> vor.
. *Speichere* die Einstellungen.

[[tabelle-einstellungen-aktivierung-auftragsherkunft]]
.Einstellungen für Auftragsherkünfte
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Neu*
|Klicken, um eine neue Auftragsherkunft anzulegen. +
*Hinweis*: Wenn die Schaltfläche nicht mehr sichtbar ist, sind alle Speicherplätze, freien IDs, für manuelle Auftragsherkünfte aufgebraucht (siehe *ID*).

|*ID*
|Jede Auftragsherkunft erhält eine ID. Diese wird automatisch vom System zugewiesen und ist nicht änderbar. Für manuelle Herkünfte stehen die IDs im Bereich 9 - 100 zur Verfügung. Die IDs bis 8 und ab 101 sind für fest im System hinterlegte Auftragsherkünfte reserviert. Unterherkünfte sind an dezimalen IDs zu erkennen, z.B. 2.08.

|*Name*
|Der eingetragene Name kann hier jederzeit geändert werden. Er wird im System, z.B. bei der Auftragssuche, angezeigt.

|*Interner Name*
|Der interne Name ist nicht änderbar und wird nicht im System angezeigt. Nur fest hinterlegte Auftragsherkünfte erhalten einen internen Namen, selbst angelegte Herkünfte nicht.

|*Eigner*
|Die Person wählen, die je nach Auftragsherkunft für einen Auftrag automatisch als Eigner eingetragen werden soll. Zur Auswahl stehen die unter *<<basics/admin-aufgaben/benutzer-verwalten#90, Einrichtung » Einstellungen » Benutzer » Konten>>* berechtigten Personen.

|*Auswahlspalte*
|Häkchen setzen = die Herkunft wird in anderen Menüs angezeigt, z.B. im Tab *Einstellungen* eines Auftrags +
Kein Häkchen = die Herkunft wird in anderen Menüs nicht angezeigt

|*Webshop-URL kopieren*
|URL der Auftragsherkunft in den Zwischenspeicher kopieren. +
Die URL wird z.B. für Affiliate-Dienste benötigt. Sie enthält die jeweilige ID als sogenannte Referrer-ID.

|*Im Webshop öffnen*
|Ein Klick auf Vorschau öffnet den Webshop mit Referrer-ID der Herkunft. Alle Preise werden für die betreffende Auftragsherkunft angezeigt.  +
Die Vorschau funktioniert nur korrekt, wenn du Verkaufspreise angelegt und für die Herkunft aktiviert hast. Außerdem muss der Verkaufspreis an einer Variante hinzugefügt und ein Wert eingetragen werden.

|*Löschen*
|Löschen klicken, um eine Auftragsherkunft zu löschen. Es können nur Auftragsherkünfte gelöscht werden, die du selbst angelegt hast. Vom System automatisch angelegte Herkünfte sind nicht löschbar.
|====

== Aufträge nach Auftragsherkunft suchen

Die Auftragssuche im Menü *Aufträge » Aufträge bearbeiten* bietet viele Filter, um deine Suche genauer einzugrenzen. Der Filter *Herkunft* sucht Aufträge nach der Auftragsherkunft (Mandant (Shop), Amazon, eBay etc.). Für Amazon und eBay gibt es sowohl allgemeine Herkünfte als auch eine Unterherkunft für jede Länderplattform.

Bei monatlichen Auswertungen ist es sinnvoll, einen zusätzlichen Datumsfilter, z.B. das Datum des Auftragseingangs, zu wählen und den genauen Zeitraum festzulegen. Im Bereich *Statistik* stehen dir weitere Auswertungsmöglichkeiten zur Verfügung.

== Auftragsherkunft am Auftrag erkennen

Die Herkunft eines Auftrags ist in der Auftragsübersicht ersichtlich. In der zum Auftrag gehörenden Zeile wird die ID der Herkunft angezeigt. Wenn du mit der Maus auf die ID zeigst, wird ein Tooltip mit dem Namen der Herkunft eingeblendet.

Im Tab *Einstellungen* eines Auftrags wird die *Herkunft* ebenfalls angezeigt. Diese Herkunft kann nur bei manuell angelegten Herkünften und auch nur so lange noch keine Rechnung erzeugt wurde, geändert werden.

== Verkäufe je Herkunft auswerten

Die Herkunftsangabe ist für die Erfolgskontrolle in deinem Shop wichtig. Nur über diese Einstellung kannst du nachvollziehen, welche Plattformen für dein Warenangebot profitabel sind. Im Auftragsmenü kannst du dir über den Herkunfts- und Datumsfilter die Auftragssumme je Auftragsherkunft für einen bestimmten Zeitraum anzeigen lassen. Im Menü *Statistik* kannst du über die Herkunftsangabe die Umsätze der Auftragsherkünfte sehen. So entscheidest du fundiert, wie du dein Werbebudget künftig immer gezielter und effizienter einsetzt.
