= Grundeinstellungen
:lang: de
include::{includedir}/_header.adoc[]
:position: 10
:url: auftraege/grundeinstellungen

Im Menü *System » Systemeinstellungen » Aufträge » Einstellungen* wählen Sie die Einstellungen, die für Aufträge automatisch eingestellt werden bzw. bei bestimmten Auftragsstatus oder Bedingungen gelten sollen. Zum Beispiel wählen Sie Standard-Einstellungen für die Auftragsherkunft und den Status von Aufträgen.

[#100]
== Wichtige Vorbedingungen beachten

Bei neuen Systemen sind Standard-Werte eingestellt, z.B. für Retouren der Status [9] und für Gutschriften der Status [11]. Diese Einstellungen sind änderbar. Wählen Sie dazu einen anderen Status. Alternativ legen Sie im Menü *<<auftraege/auftraege-verwalten#1200, System » Systemeinstellungen » Aufträge » Auftragsstatus>>* einen neuen Status an. Ein dort angelegter Status wird hier im Menü *Grundeinstellungen* angezeigt und ist auch als Standard-Status einstellbar.

[IMPORTANT]
.Grundeinstellungen speichern
====
Die Grundeinstellungen des Menüs *System » Systemeinstellungen » Aufträge » Einstellungen* müssen bei Inbetriebnahme des Systems gespeichert werden, damit die Einstellungen wirksam sind. Speichern Sie daher die Einstellungen auch, wenn Sie sie nicht verändert haben, also die Standardkonfiguration verwenden möchten.
====

[WARNING]
.Wichtig: Benutzer-Login
====
Wenn Sie in diesem Menü Änderungen vornehmen, werden andere Benutzer automatisch ausgeloggt und müssen sich neu einloggen, damit die Änderungen auch für diese Benutzerprofile greifen. Kündigen Sie Änderungen daher ggf. weiteren Benutzern an.
====

[#200]
== Grundeinstellungen vornehmen

Gehen Sie wie unten beschrieben vor, um die Grundeinstellungen vorzunehmen.

[.instruction]
Grundeinstellungen konfigurieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Einstellungen*.
. Nehmen Sie die Einstellungen gemäß <<tabelle-auftraege-grundeinstellungen>> vor.
. *Speichern* Sie die Einstellungen.

[[tabelle-auftraege-grundeinstellungen]]
.Optionen im Menü *System » Systemeinstellungen » Aufträge » Einstellungen*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Standard-Auftragsherkunft*
|Als Herkunft, die bei Aufträgen automatisch voreingestellt werden soll, einen Anbieter bzw. Marktplatz oder die Einstellung *Webshop* wählen. *Manuelle Eingabe* wählen, wenn keine Voreinstellung gewünscht ist, also die Auftragsherkunft individuell hinterlegt werden soll.

|*Standard-Status Retoure*
|Wählen, welcher Status bei *<<auftraege/auftraege-verwalten#400, Retouren>>* automatisch eingestellt sein soll. Der Status kann beim Anlegen der Retoure angepasst werden.

|*Standard-Status Gutschrift*
|Wählen, welcher Status bei *<<auftraege/auftraege-verwalten#500, Gutschriften>>* automatisch eingestellt sein soll.

|*Standard-Status Reparatur*
|Wählen, welcher Status bei *<<auftraege/auftraege-verwalten#700, Reparatur-Aufträgen>>* automatisch eingestellt sein soll.

|*Standard-Status Sammelauftrag*
|Wählen, welcher Status bei *<<auftraege/auftraege-verwalten#800, Sammelaufträgen>>* automatisch eingestellt sein soll.

|*Standard-Status Sammelgutschrift*
|Wählen, welcher Status bei *<<auftraege/auftraege-verwalten#850, Sammelgutschriften>>* automatisch eingestellt sein soll.

|*Standard-Status Rückbuchung*
|Wählen, welcher Status bei Rückbuchungen automatisch eingestellt sein soll. +
__**Beispiel**__: benutzerdefinierter Status *[6.4] Warenausgang storniert*. +
Wenn kein besonderer Status benötigt wird, *Letzter Status* wählen. Dann wird der vor dem Warenausgang durchlaufene Status wieder eingestellt.

|*Status stornierter Aufträge*
|Den Statusbereich für stornierte Aufträge wählen. +
__**Hintergrund**__: Sobald ein Auftrag in diesem Statusbereich ankommt, werden alle Bestandsreservierungen der darin enthaltenen Artikel aufgehoben. Das heißt, der Warenbestand steht wieder für Bestellungen zur Verfügung. Status können von dieser Automatik ausgenommen werden, wenn dies nötig ist bzw. wenn Artikel mit dem Status nicht rückgebucht werden sollen. +
__**Wichtig**__: Den Statusbereich aufsteigend hinterlegen, z.B. [8.0] bis [8.5].

|*Status Auftragsreservierung*
|Sobald ein Auftrag in dem hier gewählten Status ankommt, wird automatisch für die im Auftrag enthaltenen Artikel Bestand reserviert. Die Einstellung ist bis einschließlich Status [6.9] möglich. Zusätzlich ist wählbar, ob die Einstellung für alle Aufträge oder nur für bezahlte Aufträge gelten soll. Wenn z.B. für nicht bezahlte Aufträge kein Bestand reserviert werden soll, die Option *Nur bezahlte Aufträge* wählen.

|*Versandkosten in Gewährleistung übernehmen*
|*JA* = Die Versandkosten werden dem Käufer rückwirkend erstattet. +
*NEIN* = Der Kunde muss die Versandkosten auch im Falle einer Gewährleistung selbst tragen. Die Versandkosten werden nicht erstattet.

|*In Auftrag/Auftragsübersicht anzeigen*
|Wählen, ob im Auftrag bzw. in der Auftragsübersicht die *Rechnungsadresse* oder die *Lieferadresse* angezeigt werden soll.

|*Artikelpreis-Darstellung*
|Wählen, ob die Preise der Artikelliste im Auftrag *Brutto* oder *Netto* dargestellt werden sollen.

|*Zuordnung des Lagers*
|Die Lagerzuordnung wählen. +
*a) pro Auftrag kann ein Lager zugeordnet werden* = Wählen, wenn nur mit einem Lager bzw. Logistiker gearbeitet wird. +
*b) pro Artikelposition kann ein Lager zugeordnet werden* = Wählen, wenn mit mehreren Lagern bzw. Logistikern gearbeitet wird.

|*Automatische Lagerauswahl*
|Kriterien wählen, nach denen das Lager gewählt wird. +
*a) in Abhängigkeit des Lieferlandes* = Das Lager für das *Lieferland* ist im Menü *System » Systemeinstellungen » Aufträge » Versand » Einstellungen » Tab: Lieferländer* hinterlegt. +
*_Tipp:_* Bei Wahl dieser Option die Lagerzuordnung zu den Lieferländern prüfen. +
*b) in Abhängigkeit des Hauptlagers des Artikels* = Es wird das Lager bestimmt, das beim jeweiligen Artikel als Hauptlager hinterlegt ist. +
*_Wichtig:_* Wenn für einen Artikel kein Hauptlager hinterlegt wurde, wird das Lager anhand des Lieferlandes gewählt. +
*c) in Abhängigkeit des höchsten Warenbestandes* = Der Auftrag wird dem Lager mit dem höchsten Warenbestand der Artikelposition zugeordnet. +
*d) in Abhängigkeit der Lagerpriorität und des höchsten Warenbestandes* = Der Auftrag wird einem Lager nach folgenden Kriterien zugeordnet. Dabei wird nach folgender Reihenfolge geprüft: +
1) Nach der *Priorität* des Lagers (Option in den Lagereinstellungen). +
Bei ausreichendem bzw. gleichem Warenbestand in allen Lagern wird das Lager nach Priorität gewählt. Es kommt bei Kriterium 1 nicht auf die Menge an, sondern nur darauf, dass genügend Bestand vorhanden ist. Das heißt, dass kein Lager aufgrund der Menge bevorzugt wird, sondern dann mit Kriterium 2 anhand der Priorität. Umgekehrt ist mangelnder Bestand ein Ausschlusskriterium.
2) Es muss ausreichend Warenbestand vorhanden sein. +
*e) in Abhägigkeit des niedrigsten Warenbestandes* = Der Auftrag wird dem Lager mit dem niedrigsten Warenbestand der Artikelposition zugeordnet. +
*f) in Abhängigkeit der Lagerpriorität und des niedrigsten Warenbestandes* = Der Auftrag wird einem Lager nach folgenden Kriterien zugeordnet. Dabei wird nach folgender Reihenfolge geprüft: +
1) Nach der *Prioriät* des Lagers (Option in den Lagereinstellungen). +
Bei ausreichendem bzw. gleichem Warenbestand in allen Lagern wird das Lager nach Priorität gewählt. Es kommt bei Kriterium 1 nicht auf die Menge an, sondern nur darauf, dass genügend Bestand vorhanden ist. Das heißt, dass kein Lager aufgrund der Menge bevorzugt wird, sondern dann mit Kriterium 2 anhand der Priorität. Umgekehrt ist mangelnder Bestand ein Ausschlusskriterium.
2) Das Lager mit dem niedrigsten Warenbestand wird gewählt. +

|*Anzahlung auf Produktionsware*
|Die Höhe einer Anzahlung (in Prozent) oder *keine Anzahlung anbieten* wählen.

|*Statuswechsel auf [4] statt [5], wenn Warenbestand fehlt*
|Diese Option auf *Ja* setzen, wenn ein Auftrag erst für den Versand freigegeben werden soll, wenn genügend Ware auf Lager ist. Sobald genügend Ware eingebucht wurde, wird der *<<auftraege/auftraege-verwalten#1200, Auftragsstatus>>* von *[4]* auf *[5]* geändert. +
*Status [4]* = In Versandvorbereitung +
*Status [5]* = Freigabe Versand

|*Betroffener Statusbereich im Status [4.x]*
|Den Statusbereich eingrenzen, wenn eigene Statusvarianten im Bereich von Status [4] angelegt wurden. +
Standardeinstellung: von *[4] In Versandvorbereitung* bis *[4] In Versandvorbereitung*.

|*Zusätzlich ist Status [3.2] betroffen*
|*Status [3.2]* bezeichnet das Warten auf Ware bei Teilzahlungen. Wenn eine Teilzahlung erfolgt, wechselt der Auftrag automatisch statt in Status [4] in diesen Status. Ist Ware vorhanden, wechselt der Auftrag in Status [3.3]. +
*Status [3.2]* = In Warteposition
|====

[#300]
== Auftragsbearbeitung durch variable Benutzer

Damit variable Benutzer Aufträge öffnen können, müssen hier Standard-Status für *Retouren* und *Gutschriften* gespeichert sein. In der Grundeinstellung ist kein Status voreingestellt. +
Variable Benutzer müssen außerdem im Benutzerprofil unter *<<basics/admin-aufgaben/benutzer-verwalten#90, Berechtigung » Tab: Menü » Bereich: Aufträge>>* zur Bearbeitung von Aufträgen berechtigt werden.
Zudem müssen variable Benutzer Aufträge der Typen *Retoure*, *Gewährleistung* und *Reparatur* anlegen können. Dafür müssen sie für die im Menü *System » Systemeinstellungen » Aufträge » Einstellungen* hinterlegten Standard-Status dieser drei Auftragstypen berechtigt sein. Die Berechtigung erfolgt im Benutzerprofil des variablen Benutzers unter *<<basics/admin-aufgaben/benutzer-verwalten#100, Berechtigung » Tab: Sichtbarkeiten>>*.
