= Gutscheine
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Gutscheine, Gutschein, Kampagne, Gutschein-Code, Artikel als Gutschein verkaufen
:description: Erfahren Sie auf dieser Handbuchseite, wie Sie Gutscheine und Gutscheinkampagnen in plentymarkets verwalten.
:position: 80

Gutscheine sind ein beliebtes Mittel zur Neukundengewinnung, Kundenbindung und Absatzsteigerung. plentymarkets verfügt im Menü *Aufträge » Gutscheine* über ein umfangreiches Gutscheinmodul. In diesem Menü können Sie Kampagnen mit verschiedenen Rabattmöglichkeiten erstellen. Ein Gutschein ist ein bestimmter Code, der einer Kampagne angehört und entweder einmal oder mehrfach eingelöst werden kann. Die Einlösung erfolgt während des Bestellvorgangs. Dabei wird der entsprechende Rabattwert direkt angezeigt.

[#5]
== Freitextfeld wählen

Im Menü *System » Aufträge » Gutscheine* wählen Sie das Freitextfeld, das Sie für Gutscheinkampagnen verwenden möchten. Nachdem Sie die Einstellung gespeichert haben, wird das Feld *Kampagne ID* im Tab <<artikel/artikel-verwalten#75, Felder>> der Artikel angezeigt.

[.instruction]
Freitextfeld wählen:

. Öffnen Sie das Menü *System » Aufträge » Gutscheine*.
. Wählen Sie das Freitextfeld für die Kampagne aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen. +
→ Das Feld *Kampagne ID* wird im Tab <<artikel/artikel-verwalten#75, Felder>> der Artikel angezeigt.


[#10]
== Verwendungsmöglichkeiten von Gutscheinen

Ein Gutschein enthält einen Code, der einer Kampagne angehört und entweder nur einmal oder mehrfach eingelöst werden kann. Die Einlösung erfolgt während des Bestellvorgangs. Dabei wird der Rabattwert direkt angezeigt. Gutscheine können als Code in einer E-Mail verschickt werden oder als Artikel erstellt und verkauft werden. Der Käufer erhält den Gutschein dann als PDF-Dokument.

Die folgende Übersicht zeigt die Verwendungsmöglichkeiten von Gutscheinen:

[[tabelle-verwendungsmoeglichkeiten-gutscheine]]
.Verwendungsmöglichkeiten von Gutscheinen
[cols="1,3,3,3,3"]
|====
|Gutschein |Verwendung |per E-Mail |Webshop |PDF

|Code
|Einlösung
|ja
|ja
|nein

|Gutschein
|Verkauf und Einlösung
|ja
|ja
|ja

|Voucher
|Verkauf
|ja
|nein
|ja
|====

[TIP]
.Template-Variablen für die Ausgabe von Voucher-Codes in E-Mail-Vorlagen
====
Fügt man die Template-Variable *$ItemVoucherCodes* in der E-Mail-Vorlage ein, werden die Codes eines Vouchers kommasepariert pro Auftragsposition ausgegeben. Über die Template-Variable *$VoucherCodes* werden alle Codes aller Vouchers kommasepariert für einen Auftrag ausgegeben.
====

[#15]
== Artikel für Gutscheinzahlung vorbereiten

Bevor Sie mit Gutscheinen arbeiten, überlegen Sie zunächst, welche Artikel aus Ihrem Sortiment per Gutschein bezahlbar sein sollen.

[.instruction]
Artikel für Gutscheinzahlung vorbereiten:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Artikel, der per Gutschein bezahlbar sein soll.
. Öffnen Sie das Tab <<artikel/artikel-verwalten#40, Global>>.
. Stellen Sie die Option *Aktionsgutschein* auf *Möglich*.
. *Speichern* Sie die Einstellungen.  +
→ Beim Kauf des Artikels kann nun ein Gutschein eingelöst werden.

[IMPORTANT]
.Gutscheinzahlung nicht erlauben
====
Stellen Sie im Menü *Artikel » Artikel bearbeiten » Artikel öffnen* im Tab *Global* die Option *Aktionsgutschein* auf *Verboten*, wenn der Artikel nicht per Gutschein bezahlbar sein soll. Legt der Kunde einen solchen Artikel in den Warenkorb, wird der Rabattbetrag für diesen Artikel nicht abgezogen. Dies ist z.B. bei Sonderangeboten sinnvoll, die nicht weiter rabattiert werden sollen.

Soll ein Artikel nur per Gutschein bezahlbar sein, wählen Sie die Einstellung *Nur mit Gutschein kaufbar*.
====

[#20]
== Kampagne erstellen

Da jeder Gutschein einer Kampagne angehört, muss zuerst eine Kampagne erstellt werden. Kampagnen erstellen Sie im Menü *Aufträge » Gutscheine*. Bereits erstellte Kampagnen enthalten neben dem Tab *Einstellungen* zwei weitere Tabs: <<auftraege/gutscheine#60, Codes>> und <<auftraege/gutscheine#140, Vorlagen>>.

[.instruction]
Kampagne erstellen:

. Öffnen Sie das Menü *Aufträge » Gutscheine*.
. Klicken Sie auf *Neue Kampagne*.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Einstellungen in <<tabelle-einstellungen-gutscheinkampagne>>.
. *Speichern* Sie die Einstellungen.  +
→ Die Kampagne wird erstellt und in der Übersicht angezeigt.

[WARNING]
.Kampagnen nicht löschen
====
Jeder Gutschein gehört einer Kampagne an. Daher sollten Kampagnen nicht gelöscht werden, um Problemen mit bereits eingelösten Gutscheinen zu vermeiden.
====

[[tabelle-einstellungen-gutscheinkampagne]]
.Einstellungen für eine neue Gutschein-Kampagne
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Kampagne*

|*Name*
| Name der Kampagne eingeben.

|*Beschreibung*
|Beschreibung der Kampagne eingeben.

|*Konzept: Code*
|In der oberen Dropdown-Liste die Einstellung für die Codes wählen:  +
*Ein Code* = Pro Kampagne wird ein Gutschein-Code erzeugt, der mehrmals einlösbar ist.  +
*Mehrere Codes* = Es werden einzelne Gutschein-Codes erzeugt, die nur einmal einlösbar sind.

|*Konzept: Einlösungen*
|In der unteren Dropdown-Liste die Einstellung für die Einlösung(en) wählen:  +
*Mehrere Einlösungen pro Kunde* = Ein Kunde kann den Gutscheinbetrag mehrmals abrufen.  +
*_Wichtig:_* Wenn der Gutschein an mehrere Kunden verschickt wird, können diese den Gutschein unbegrenzt oft abrufen. In diesem Fall können hohe Gesamtbeträge erreicht werden!  +
*Eine Einlösung pro Kunde* = Ein Gutschein kann nur einmal pro Kunde vollständig oder in Teilbeträgen abgerufen werden. Bei mehreren Kunden können diese einen niedrigeren Betrag abrufen, doch sobald der erste Kunde den Gutscheinbetrag erreicht, ist keine weitere Einlösung mehr möglich.  +
*_Hinweis:_* Ist der Kunde kein registrierter Kunde und loggt sich über einen Gastzugang ein, wird er im System als neuer Kunde geführt. Wird die Gutscheinsumme nicht komplett verbraucht, kann der Gutschein immer wieder verwendet werden, da eine Einlösung PRO Kunde eingestellt ist - also neuer Kunde, neuer Gutschein.  +
*_Wichtig:_* Teilbeträge, die unter dem Gutscheinbetrag liegen, können von allen Kunden parallel abgerufen werden. Erst wenn der erste Kunde den vollen Betrag erreicht, endet die Einlöseoption. In diesem Fall können hohe Gesamtbeträge erreicht werden!  +
*Einlösung bis Wert aufgebraucht ist* = Der gesamte Betrag kann insgesamt nur einmal abgerufen werden. Ruft ein Kunde mehrere Teilbeträge ab, dürfen alle Teilbeträge zusammen nur so hoch sein wie der Gutscheinbetrag. Der Gutschein kann nicht durch mehrere Kunden eingelöst werden.  +
*Eine einzige Einlösung* = Nur ein Einlösungsvorgang ist möglich. Auch wenn dies nur ein geringer Teilbetrag ist, sind keine weiteren Einlösungen möglich.

|*Nutzung*
|*Einzelbestellungen* oder <<auftraege/scheduler#, Abonnement>> oder beides wählen.

|*Mindestbestellwert*
| Mindestbestellwert, der erreicht werden muss, damit der Gutschein eingelöst werden kann.

2+|*Gültigkeiten*

|*Startdatum*
|Das Datum, ab dem die Kampagne aktiv sein soll.

|*Enddatum*
|Das Datum, bis zu dem die Kampagne aktiv sein soll.

|*Code-Gültigkeit in Wochen*
|Anzahl der Wochen eingeben, die die Gutschein-Codes gültig sein sollen. 12 eingeben, wenn die Gutschein-Codes 12 Wochen lang gültig sein sollen. +
*_Wichtig:_* Die Gültigkeit darf dabei nicht mit den vorigen Optionen *Startdatum* und *Enddatum* verwechselt werden. Die Gültigkeit kann z.B. ein Jahr betragen (Eintrag: 52) und die Kampagne in diesem Zeitraum mehrfach gestartet und wieder beendet werden.

2+|*Gutschein*

|*Gutscheintyp*
|*Gutschein* oder *Voucher* wählen.  +
Anders als der Gutscheintyp *Gutschein* werden Gutscheine vom Typ *Voucher* nicht im Webshop, sondern bei Drittanbietern eingelöst. Voucher werden vor allem in der Hotellerie eingesetzt und dienen gleichzeitig auch als Reservierungsbestätigung.  +
*_Hinweis:_* Abhängig davon, welcher Gutscheintyp gewählt wurde, stehen unterschiedliche Einstellungen zur Verfügung.
|*Code-Zuweisung*
|Nur bei Gutscheintyp *Voucher* sichtbar.  +
Wählen, ob die Gutscheincodes neu erzeugt werden sollen oder vorhandene benutzt werden sollen.

|*Gutscheinart*
|*Aktionsgutschein* oder *Verkaufsgutschein* wählen. Bestimmt, wie die Gutscheine im Auftrag eingelöst und in den PDF-Dokumenten dargestellt werden.  +
Für Kampagnen mit Gutscheinen, die über den Webshop verkauft werden, *Verkaufsgutschein* wählen.  +
Diese Einstellung hat auch Einfluss darauf, wie der Gutschein im Webshop verrechnet wird. <<auftraege/gutscheine#25, Ein Beispiel erläutert die Berechnungsmethode>>.

|*Code-Länge*
|Die Zeichenlänge des Gutschein-Codes wählen. Gutschein-Codes können *6*, *16*, *24* oder *32* Zeichen lang sein.

|*Rabattart*
|Art des Rabatts wählen.  +
*Festbetrag* = Festen Rabattbetrag eingeben.  +
*Prozentwert* = Prozentwert vom Rechnungsbetrag eingeben. 10 eingeben, wenn 10 Prozent des Rechnungsbetrags abgezogen werden sollen.  +
*Stück* = Stückzahlen eingeben, z.B. 3 Artikel zum Preis von 2 Artikeln.  +
*Versand* = Der Rabatt besteht in kostenlosem Versand.

|*Rabattwert*
| Rabattwert des Gutscheins eingeben. +
Option *inkl. Versandkosten* aktivieren, wenn die Versandkosten im Rabattwert eingeschlossen sein sollen.

2+|*Filter*

|*Artikel über Preisportale*
|*Erlauben* = Gutscheine gelten auch für Artikel über <<maerkte#, Preisportale>>, d.h. für Artikel, die gleichzeitig auf anderen Marktplätzen angeboten werden.  +
*Nicht erlauben* = Gutscheine können nicht für Artikel über Preisportale verwendet werden (Standardeinstellung). +
*_Hinweis:_* Preisportale sind alle Herkünfte > 1, d.h. neben Preisportalen sind hier auch Marktplätze und Plattformen inbegriffen. Die manuelle Anlage (Herkunft 0) und Webshop (Herkunft 1) sind von dieser Einstellung nicht betroffen.

|*Kategorien*
|Kategorien hinzufügen, bei denen der Gutschein einlösbar sein soll. Die Auswahl gilt auch für alle Unterkategorien einer markierten Kategorie. Es ist auch möglich, nur Unterkategorien hinzuzufügen. +
Mit einem Klick auf *Löschen* neben der Kategorie-ID und dem Kategorienamen wird die Kategorie aus der Kampagne gelöscht. Lediglich die Verknüpfung wird gelöscht, nicht die Kategorie selbst.

|*Artikel*
|Bis zu 20 Artikel hinzufügen, für die die Gutscheine der Kampagne einlösbar sein sollen: Die Artikel-ID in das Textfeld eingeben und auf *Hinzufügen* klicken. Alle Artikel nach diesem Muster hinzufügen.  +
Mit einem Klick auf die Artikel-ID wird der Artikel im Menü *Artikel » Artikel bearbeiten* geöffnet. Mit einem Klick auf *Löschen* auf der rechten Seite wird der Artikel aus dieser Kampagne gelöscht und aus der Liste entfernt.

|*Mandanten (Shops)*
|<<omni-channel/online-shop#, Mandanten (Shops)>> wählen, für die der Gutschein einlösbar sein soll. Es muss mindestens ein Mandant gewählt werden.

|*Kundenklassen*
|<<crm/kontakte-verwalten#15, Kundenklassen>> wählen, für die der Gutschein einlösbar sein soll. Es muss mindestens eine Kundenklasse gewählt werden.

|*Kundentypen*
|<<crm/kontakte-verwalten#20, Kundentypen>> wählen, für die der Gutschein einlösbar sein soll. Es muss mindestens ein Kundentyp gewählt werden.

2+|*E-Mail-Vorlage*

|*Variable*
|Eine Variable für <<crm/e-mails-versenden#, E-Mail-Vorlagen>> wählen (siehe unten). Die Option *Keine Variable* ist voreingestellt. Eine gewählte Variable ist für weitere Kampagnen nicht mehr verfügbar.
|====

[#25.subhead]
Beispiel für die Berechnung von Aktions- und Verkaufsgutscheinen

Die Auswahl der *Gutscheinart* im Tab *Einstellungen* im Bereich *Gutschein* hat Einfluss darauf, wie der Gutschein im Webshop verrechnet wird. Aktionsgutscheine werden z.B. ähnlich wie Rabatte verrechnet.

[TIP]
.Beispiel für die Berechnung von Aktions- und Verkaufsgutscheinen
====
Ein Kunde hat einen Gutschein im Wert von 15 Euro. Der Kunde kauft für 25 Euro ohne MwSt. ein. Er kauft 2 Artikel. Einen Artikel für 17,95 Euro, der mit 19 % MwSt. versteuert werden muss, und einen Artikel für 7,05 Euro, auf den nur 7 % MwSt. angewendet werden. Handelt es sich bei dem Gutschein um einen *Verkaufsgutschein*, wird der Gutscheinwert vom Gesamtbetrag inkl. Steuern abgezogen. Handelt es sich um einen *Aktionsgutschein*, wird der Gutscheinwert zuerst abgezogen und dann der Restbetrag besteuert.
====

[[tabelle-vergleich-aktionsgutschein-verkaufsgutschein]]
.Vergleich von Aktionsgutschein und Verkaufsgutschein
[cols="3,3,3"]
|====
| |Verkaufsgutschein |Aktionsgutschein

|*Betrag vor Abzug des Gutscheinwertes*
|28,91 Euro inklusive MwSt.
|25 Euro exklusive MwSt.

|*Betrag nach Abzug des Gutscheinwertes*
|13,91 Euro inklusive MwSt.
|10 Euro exklusive MwSt.

11,56 Euro inklusive MwSt.

|*Durch den Kunden zu zahlender Endbetrag*
|13,91 Euro
|11,56 Euro
|====

[#55]
== Kampagne suchen

Um Kampagnen zu suchen, wählen Sie die Suchparameter im Menü *Aufträge » Gutscheine » Tab: Filter*. In der Standardeinstellung der Filter werden alle Kampagnen gesucht und angezeigt.
In der <<auftraege/auftraege-verwalten#1370, Auftragssuche>> steht ein Suchfilter für Gutschein-Codes zur Verfügung.

[.instruction]
Kampagne suchen:

. Öffnen Sie das Menü *Aufträge » Gutscheine*.
. Geben Sie im Bereich *Filter* die ID oder den Gutschein-Code ein bzw. stellen Sie Filteroptionen in den Dropdown-Listen ein. Beachten Sie dazu die Erläuterungen in <<tabelle-kampagne-suchen>>.
. Klicken Sie auf *Suchen*. +
→ Die Kampagnen, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

[[tabelle-kampagne-suchen]]
.Kampagne suchen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|ID der Kampagne eingeben.

|*Gutschein-Code*
|Gutschein-Code eingeben.

|*Mandant*
|Mandant aus der Dropdown-Liste wählen, um nur Kampagnen dieses Mandanten anzuzeigen.

|*Kundenklasse*
|Kundenklasse aus der Dropdown-Liste wählen, um nur Kampagnen für diese Kundenklasse anzuzeigen.

|*Datum von / bis*
|Start- und Enddatum der Kampagne wählen oder manuell eingeben.

|*Gutscheinart*
|*Aktionsgutschein* oder *Verkaufsgutschein* wählen, um nur Kampagnen mit dieser Gutscheinart anzuzeigen.

|*Gutscheintyp*
|*Gutschein* oder *Voucher* wählen, um nur Kampagnen mit diesem Gutscheintyp anzuzeigen.

|*Konzept*
|*Ein Code*, *Mehrere Codes* oder *Alle* wählen.

|*Rabattart*
|Rabattart wählen, um nur Kampagnen mit dieser Rabattart anzuzeigen. Mögliche Optionen: *Festbetrag*, *Prozentwert*, *Stück*, *Versand* oder *Alle*.

|====

[#50]
== Kampagne bearbeiten

Im Menü *Aufträge » Gutscheine » Tab: Kampagnen* werden die wichtigsten Informationen der erstellten Kampagnen in der Übersicht angezeigt. <<tabelle-werte-gutschein-uebersicht>> erläutert die Kampagnen-Übersicht.

[.instruction]
Kampagne bearbeiten:

. Öffnen Sie das Menü *Aufträge » Gutscheine*.
. Suchen Sie die Kampagne, die Sie bearbeiten möchten anhand der Filtereinstellungen in <<tabelle-kampagne-suchen>>.
. Klicken Sie in die Zeile der Kampagne. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-einstellungen-gutscheinkampagne>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-werte-gutschein-uebersicht]]
.Wichtige Informationen in der Gutscheinübersicht
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Start*
|Zeigt das Datum an, seit dem die Kampagne aktiv ist.

|*Ende*
|Zeigt das Datum an, bis zu dem die Kampagne aktiv ist. +
*_Wichtig:_* Nicht mit der Gültigkeit zu verwechseln. Dazu die Erläuterung zur Option *Code-Gültigkeit in Wochen* in <<tabelle-einstellungen-gutscheinkampagne>> beachten.

|*Gutscheintyp*
| Zeigt den Gutscheintyp an. Mögliche Werte: *Gutschein* oder *Voucher*.

|*Gutscheinart*
|Zu den Gutscheinarten *Aktionsgutschein* und *Verkaufsgutschein* die Erläuterungen in <<tabelle-einstellungen-gutscheinkampagne>> sowie das <<auftraege/gutscheine#25, Beispiel>> unter Tabelle 2 beachten.

|*Konzept*
|Das Konzept bestimmt z.B., ob ein Gutschein nur einmal oder mehrfach eingelöst werden kann. Erläuterungen dazu in <<tabelle-einstellungen-gutscheinkampagne>> beachten.

|*Rabatt*
| Zeigt die Rabattart sowie den dazugehörigen Wert an.

|*Mindestbestellwert*
| Mindestbestellwert, ab dem der Gutschein eingelöst werden kann.

|*Einlösungen*
|Die rote Ziffer steht für die Anzahl der eingelösten Gutscheine. Die grüne Ziffer steht für die Anzahl der noch nicht eingelösten Gutscheine.

|*Export*
|Auf *Export* am Zeilenende der Kampagne klicken, um die Kampagnedaten in eine CSV-Datei zu exportieren.

|*Löschen*
|Löscht die Kampagne.

|====



[#60]
== Gutschein-Codes erzeugen

Im Menü *Aufträge » Gutschein* im Tab *Codes* einer Kampagne finden Sie den Gutschein-Generator. Zur Erzeugung von Gutschein-Codes mit dem Gutschein-Generator stehen zwei Verfahren zur Verfügung, die im Folgenden erläutert werden.

[IMPORTANT]
.Gültige Zeichen für Gutschein-Codes
====
Ein Gutschein-Code kann aus Klein- oder Großbuchstaben, Ziffern, den Sonderzeichen _ und - oder aus einer Kombination aus diesen Zeichen bestehen.
====

[#70]
=== Gutschein-Codes manuell generieren

Generieren Sie gleichzeitig mehrere Gutschein-Codes. Diese Codes werden automatisch generiert und der Code-Liste hinzugefügt.

[.instruction]
Gutschein-Codes manuell generieren:

. Öffnen Sie das Menü *Aufträge » Gutscheine*.
. Klicken Sie auf die Kampagne, für die Sie Gutschein-Codes erzeugen möchten.
. Wechseln Sie in das Tab *Codes*.
. Geben Sie im Bereich *Gutschein-Codes manuell generieren* die *Anzahl* an Gutschein-Codes ein, die erzeugt werden soll.
. *Speichern* Sie die Einstellungen. +
→ Die Gutschein-Codes werden erzeugt und in der Liste der Gutschein-Codes hinzugefügt.

[IMPORTANT]
.Mehr Codes als Einlösungen
====
Die Anzahl der offenen Gutscheine kann die maximale Anzahl der Einlösungen überschreiten. Somit können noch offene Gutschein-Codes übrig bleiben, nachdem die maximale Anzahl an Einlösungen erreicht ist. Diese sind nicht mehr einlösbar.
====

[#80]
=== Externe oder eigene Gutschein-Codes manuell eingeben

Fügen Sie eigene oder externe Codes hinzu. Dabei kann es sich um Codes handeln, die Sie erhalten haben und die nicht in plentymarkets erzeugt wurden, oder um eigene Codes, die Sie individuell benennen und eingeben.

[.instruction]
Gutschein-Code manuell eingeben:

. Öffnen Sie das Menü *Aufträge » Gutscheine*.
. Klicken Sie auf die Kampagne, für die Sie einen Gutschein-Code eingeben möchten.
. Wechseln Sie in das Tab *Codes*.
. Geben Sie im Bereich *Gutschein-Code manuell eintragen* einen *Code* mit 6 bis 32 Zeichen ein.
. *Speichern* Sie die Einstellungen.  +
→ Der Gutschein-Code wird generiert und der Liste der Gutschein-Codes hinzugefügt.

[#90]
=== Gutschein-Codes per Datenaustausch bearbeiten

Verwenden Sie das Datenformat <<daten/export-import/datenformate/campaigncoupon#, CampaignCoupon>>, um Gutschein-Codes zeitsparend zu <<daten/export-import/daten-exportieren#, exportieren>>, zu bearbeiten und zu <<daten/export-import/daten-importieren#, importieren>>.
Auf diese Weise ist es z.B. möglich, größere Mengen an Gutscheincodes in einem Arbeitsgang zu importieren, statt sie einzeln manuell einzugeben.

[#100]
== Gutschein-Codes per E-Mail versenden

Gutschein-Codes können automatisch in E-Mails eingebunden werden. Beim Versenden einer E-Mail wird immer ein neuer Gutschein-Code erzeugt und versendet.
So kann auch per Newsletter jedem Kunden ein automatisch generierter Gutschein-Code zugeschickt werden.  +
Dazu muss der Kampagne zunächst eine <<omni-channel/online-shop/webshop-einrichten/cms-syntax#grundlagen-template-variablen, Template-Variable>> zugewiesen werden, z.B. *CouponCode1*.

Danach fügen Sie diese Template-Variable *$CouponCode1* in eine <<crm/e-mails-versenden#1200, E-Mail-Vorlage>> ein. Bei jedem Versand wird dann automatisch ein neuer Gutschein für die Kampagne erstellt.

[IMPORTANT]
.Eine Template-Variable pro Kampagne
====
Eine Template-Variable kann nur einer Kampagne zugeordnet werden.
====

[.instruction]
Template-Variable einer Kampagne zuordnen:

. Öffnen Sie das Menü *Aufträge » Gutscheine*.
. Klicken Sie auf die Kampagne, der Sie eine Variable zuordnen möchten. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wählen Sie im Bereich *E-Mail-Vorlage* eine *Variable* aus der Dropdown-Liste.
. *Speichern* Sie die Einstellungen.

[#110]
== Gutscheine verkaufen

Bevor Sie Gutscheine in Ihrem Webshop verkaufen können, müssen Sie eine <<auftraege/gutscheine#20, Gutscheinkampagne>> mit der Gutscheinart *Verkaufsgutschein* erstellen (siehe <<tabelle-einstellungen-gutscheinkampagne>>).
Um Gutscheine zu verkaufen, benötigen Sie außerdem ein Freitextfeld sowie eine Gutscheinvorlage für die Kampagne.
Gehen Sie wie in diesem Kapitel beschrieben vor, um Gutscheine in Ihrem Webshop zu verkaufen.

[#120]
=== Gutscheinartikel erstellen

Erstellen Sie nun einen <<artikel/artikel-verwalten#, Gutscheinartikel>> an, dem Sie z.B. die Bezeichnung *Gutschein1* geben. Geben Sie einen Preis und eine Kurzbeschreibung ein. Verknüpfen Sie den Gutscheinartikel mit einer Kategorie. Erstellen Sie ggf. eine eigene Kategorie für Gutscheine. +
Diese Parameter werden wie bei jedem Artikel im Webshop angezeigt.

[#130]
=== Gutscheinartikel mit Kampagne verknüpfen

Die Verknüpfung der Kampagne mit dem Gutscheinartikel erfolgt über ein <<artikel/artikel-verwalten#70, Freitextfeld>>.
Gehen Sie wie unten beschrieben vor, um den Gutscheinartikel mit dem Freitextfeld *Kampagne ID* zu verknüpfen.

Legen Sie zunächst ein Freitextfeld fest.

[.instruction]
Freitextfeld festlegen:

. Öffnen Sie das Menü *System » Artikel » Freitextfelder*.
. Geben Sie *Kampagne ID* als Feldbezeichnung ein.
. Wählen Sie den Datentyp *Zahl*.
. Geben Sie eine Zeichenlänge ein.
. *Speichern* Sie die Einstellungen.

[WARNING]
.Nur Kampagne ID als Feldbezeichnung zulässig
====
Achten Sie auf die Schreibweise des Freitextfeldes. Der Name *Kampagne ID* ist nur in der Schreibweise mit Leerzeichen gültig. Andere Namen und Schreibweisen sind nicht erlaubt.
====

Legen Sie anschließend das Freitextfeld als Kampagnenfeld fest.

[.instruction]
Kampagnenfeld festlegen:

. Öffnen Sie das Menü *System » Aufträge » Gutscheine*.
. Wählen Sie *Kampagne ID* als *Kampagnenfeld*.
. *Speichern* Sie die Einstellungen.

Verknüpfen Sie Ihre Kampagne mit einem Gutscheinartikel.

[.instruction]
Gutscheinartikel mit Kampagne verknüpfen:

. Öffnen Sie das Menü *Artikel » Artikel bearbeiten*.
. Öffnen Sie den Gutscheinartikel.
. Wechseln Sie in das Tab *Felder*.
. Geben Sie in das Freitextfeld, das Sie im Menü <<auftraege/gutscheine#, System » Aufträge » Gutscheine>> für Gutscheinkampagnen eingestellt haben, die ID der Kampagne ein, die Sie mit dem Gutscheinartikel verknüpfen möchten.
. *Speichern* Sie die Einstellungen.

[#140]
=== Gutscheinvorlage konfigurieren

Im Menü *Aufträge » Gutscheine » Tab: Vorlagen* im aufklappbaren Bereich *Gutschein-Vorlage* einer Kampagne speichern Sie eine Gutscheinvorlage für die Kampagne, d.h., Sie speichern für jede Kampagne eine eigene Vorlage. Die Vorlage ist der Hintergrund der Gutscheine, den Sie entwerfen und als PDF-Datei speichern. Im aufklappbaren Bereich *Gutschein-Layout* legen Sie die Elemente für den Gutschein sowie die Positio der Elemente fest. Gehen Sie dazu wie unten beschrieben vor.

[TIP]
.PDF-Version
====
plentymarkets unterstützt derzeit PDF-Dokumentenformate bis Version 1.4.
====

[.instruction]
Gutscheinvorlage speichern:

. Öffnen Sie das Menü *Aufträge » Gutscheine*.
. Klicken Sie in der Übersicht auf die Gutscheinkampagne, für die Sie die Vorlagen bearbeiten möchten.
. Wechseln Sie in das Tab *Vorlagen*.
. Klappen Sie den Bereich *Gutschein-Vorlage* auf.
. Klicken Sie bei *Dokumenten-Vorlage Upload* auf *Datei auswählen*.
. Markieren Sie das Dokument.
. *Speichern* Sie die Einstellungen.  +
*_Tipp:_* Nach erfolgreichen Upload wird eine Erfolgsmeldung angezeigt. Sollten Sie diese nicht erhalten und Ihnen nach dem Klicken auf *Vorlage anzeigen* eine Fehlermeldung angezeigt werden, wenden Sie sich bitte an den Support. Unter Umständen ist das Gutscheinverkaufsmodul für Ihr System nicht aktiviert.
. Klappen Sie den Bereich *Gutschein-Layout* auf .
. Geben Sie Werte für die *X-* und *Y-Koordinaten* ein.
. *Speichern* Sie die Einstellungen. +
*_Tipp:_* Nach erfolgreichem Speichern wird eine Erfolgsmeldung angezeigt. Klicken Sie auf *Vorschau anzeigen*, um einen Eindruck davon zu bekommen, wie der Gutschein aussehen wird und korrigieren Sie die Werte, bis Sie mit dem Ergebnis zufrieden sind.

[[tabelle-optionen-gutscheinvorlagen]]
.Optionen der Gutschein-Vorlagenkonfiguration
[cols="1,3"]
|====
|Einstellung
|Erläuterung

|*Zeichensatz*
|*ISO-8859-1* oder *Unicode* wählen.

|*Koordinaten und Schriftgrößen*
|Die Koordinaten eingeben und die Schriftgrößen der Gutscheintexte wählen.
|====

[TIP]
.Koordinaten
====
Mit der *X-Koordinate* stellen Sie den Abstand zum linken Rand der Seite ein. Die *Y-Koordinate* bestimmt den Abstand zum oberen Rand.
====

[#150]
=== Gutschein erzeugen

Der Prozess zum Kauf eines Gutscheins unterscheidet sich nicht vom Kaufprozess eines normalen Artikels. Sobald Ihr Kunde den Gutschein erworben hat, kann er die Gutscheintexte für die Gutscheinvorlage speichern.

[TIP]
.Tipp: Hinweistext
====
Um einen persönlichen Text zu speichern, muss der Kunde in seinem *Mein Konto*-Bereich des Webshops beim Artikel noch einmal auf *Ändern* klicken. Schreiben Sie am besten einen kurzen Hinweis in der Beschreibung des Gutschein-Artikels, um Kunden darüber zu informieren.
====

Nachdem der Kunde den Gutschein gekauft hat, kann er die Gutscheintexte wie folgt anpassen:

[.instruction]
Gutscheintexte im Mein Konto anpassen:

. Im Webshop einloggen.
. Den Bereich *Mein Konto* des Webshops im Bereich *Auftragshistorie* öffnen.
. Den Auftrag mit dem betreffenden Gutschein öffnen.
. Beim Artikel auf *Ändern* klicken.
. Dort kann nun ein *Empfänger*, ein *Absender* sowie ein *Text* gespeichert werden.  +
→ Diese Texte werden auf der Gutschein-Vorlage angezeigt.

Wenn der Kunde den Gutschein bezahlt hat, wird der Download der PDF-Vorlage bereitgestellt. Dies ist am PDF-Symbol erkennbar.

Nachdem das PDF-Dokument durch Klick auf *PDF erzeugen* erstellt wurde, kann der Kunde die Datei drucken oder speichern.

[#160]
=== Gutschein automatisch als PDF-Anhang verschicken

Gutscheine als PDF-Anhang zu verschicken ist z.B. sinnvoll, wenn Sie in Ihrem Webshop Geschenkgutscheine oder Reisegutscheine verkaufen.

Wenn Sie Gutscheine verkaufen und nicht im Mein-Konto-Bereich als PDF-Download zur Verfügung stellen, sondern per E-Mail versenden möchten, erzeugen und versenden Sie Gutscheine per Ereignisaktion. Für den E-Mail-Versand benötigen Sie eine <<crm/e-mails-versenden#1200, E-Mail-Vorlage>>, bei der Sie für die Option *PDF-Anhang* den Typ *Voucher* einstellen. Der Gutschein wird der E-Mail-Vorlage dann automatisch als PDF-Anhang hinzugefügt.

[TIP]
.Tipp: Voraussetzungen für Versand per Ereignisaktion
====
Damit Gutschein-Codes per Ereignisaktion versendet werden können, benötigen Sie eine Gutscheinkampagne. Diese müssen Sie am Artikel mittels Freitextfeld hinterlegt haben.
====

[.instruction]
E-Mail-Vorlage einrichten:

. Öffnen Sie das Menü <<crm/e-mails-versenden#, System » Mandant » Mandant wählen » E-Mail » Vorlagen>>.
. Klicken Sie auf *Neue E-Mail-Vorlage*.
. Gebeb Sie im Fenster *Neue E-Mail-Vorlage* einen Namen für die Vorlage ein, z.B. *Reisegutschein*.
. Wählen Sie einen *Eigner* oder *Alle* aus der Dropdown-Liste.  +
→ Die E-Mail-Vorlage wird erstellt, in die Liste eingeordnet und geöffnet.
. Wählen Sie *Voucher* als PDF-Anhang.
. Wechseln Sie in das Tab *E-Mail-Nachricht*.
. Geben Sie *Betreff* und *Inhalt* ein.
. Verwenden Sie Template-Variablen, um z.B. den Namen des Kunden einzufügen. Fügen Sie jedoch nicht die Template-Variable für Gutscheine *CouponCode* ein, da der Gutschein ja als Anhang versendet werden soll.
. *Speichern* Sie die Einstellungen.

[.instruction]
Gutscheinversand per Ereignisaktion einrichten:

. Öffnen Sie das Menü <<automatisierung/ereignisaktionen#, System » Aufträge » Ereignisaktionen>>.
. Klicken Sie links unten auf das *grüne Plus*, um eine neue Ereignisaktion zu erstellen.
. Geben Sie im Bearbeitungsfenster einen *Namen* ein, z.B. *Gutschein erzeugen &amp; versenden*.
. Wählen Sie unter *Ereignis* die Option *Zahlung &gt; Vollständig*
. Klicken Sie auf *Speichern*.  +
→ Die Ereignisaktion wird erstellt.
. Fügen Sie mit dem *grünen Plus* einen *Filter* des Filtertyps *Auftrag &gt; Auftragstyp* hinzu.  +
→ Der Filter wird erstellt.
. Markieren Sie im Filter die Option *Auftrag*.
. Fügen Sie mit dem *grünen Plus* einen *Filter* des Filtertyps *Artikel &gt; Artikel enthalten* hinzu.  +
→ Der Filter wird erstellt.
. Klicken Sie auf *Hinzufügen* und geben Sie in das Eingabefeld die ID des Artikels ein, bei dem die Ereignisaktion greifen soll.
. Fügen Sie mit dem *grünen Plus* eine *Aktion* des Aktionstyps *Dokumente &gt; Verkaufsgutschein erzeugen* hinzu.  +
→ Diese Aktion wird nur für bezahlte Aufträge ausgeführt.
. Fügen Sie mit dem *grünen Plus* eine *Aktion* des Aktionstyps *Auftrag &gt; Status ändern* hinzu.
. Wählen Sie in der Aktion den gewünschten *Status*.
. Fügen Sie mit dem *grünen Plus* eine *Aktion* des Aktionstyps *Kunde &gt; E-Mail versenden* hinzu.
. Wählen Sie in der Aktion die gewünschte *E-Mail-Vorlage* und als Empfänger *Kunde*.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.

[#170]
=== Gutscheinsumme auf Rechnungen anzeigen

Verkaufte Gutscheine werden auf Rechnungen als Artikelpositionen aufgeführt. Um die Summe von eingelösten Gutscheinen auf Rechnungen anzuzeigen, muss im Layout des Rechnungsdokuments ein Feldname bei <<auftraege/auftragsdokumente#90, Gutscheinsumme>> eingegeben sein.
