= Gutscheine
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Gutscheine, Gutschein, Kampagne, Gutschein-Code, Artikel als Gutschein verkaufen, Gutscheinartikel
:description: Erfahre auf dieser Handbuchseite, wie du Gutscheine und Gutscheinkampagnen in plentymarkets verwaltest.
:position: 80
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:url: auftraege/gutscheine

Gutscheine sind ein beliebtes Mittel zur Neukundengewinnung, Kundenbindung und Absatzsteigerung. plentymarkets verfügt im Menü *Aufträge » Gutscheine* über ein umfangreiches Gutscheinmodul. In diesem Menü kannst du Kampagnen mit verschiedenen Rabattmöglichkeiten erstellen. Ein Gutschein ist ein bestimmter Code, der einer Kampagne angehört und entweder einmal oder mehrfach eingelöst werden kann. Die Einlösung erfolgt während des Bestellvorgangs. Dabei wird der entsprechende Rabattwert direkt angezeigt.

[#10]
== Verwendungsmöglichkeiten von Gutscheinen

Ein Gutschein enthält einen Code, der einer Kampagne angehört und entweder nur einmal oder mehrfach eingelöst werden kann. Die Einlösung erfolgt während des Bestellvorgangs. Dabei wird der Rabattwert direkt angezeigt. Gutscheine können als Code in einer E-Mail verschickt werden oder als Artikel erstellt und verkauft werden. Der Käufer erhält den Gutschein dann als PDF-Dokument.

Die folgende Übersicht zeigt die Verwendungsmöglichkeiten von Gutscheinen:

[[tabelle-verwendungsmoeglichkeiten-gutscheine]]
.Verwendungsmöglichkeiten von Gutscheinen
[cols="1,3,3,3,3"]
|====
|Gutschein |Verwendung |per E-Mail |Webshop |PDF

|Code
|Einlösung
|ja
|ja
|nein

|Gutschein
|Verkauf und Einlösung
|ja
|ja
|ja

|Voucher
|Verkauf
|ja
|nein
|ja
|====

[TIP]
.Template-Variablen für die Ausgabe von Voucher-Codes in E-Mail-Vorlagen
====
Wenn du die Template-Variable *$ItemVoucherCodes* in der E-Mail-Vorlage einfügst, werden die Codes eines Vouchers kommasepariert pro Auftragsposition ausgegeben. Über die Template-Variable *$VoucherCodes* werden alle Codes aller Vouchers kommasepariert für einen Auftrag ausgegeben.
====

[#15]
== Artikel für Gutscheinzahlung vorbereiten

Bevor du mit Gutscheinen arbeitest, überlege dir zunächst, welche Artikel aus deinem Sortiment per Gutschein bezahlbar sein sollen.

[.instruction]
Artikel für Gutscheinzahlung vorbereiten:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel, der per Gutschein bezahlbar sein soll.
. Öffne das Tab <<artikel/artikel-verwalten#40, Global>>.
. Wähle aus der Dropdown-Liste *Aktionsgutschein/POS-Rabatt* die Einstellung *Möglich*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.  +
→ Beim Kauf des Artikels kann nun ein Gutschein eingelöst werden.

[IMPORTANT]
.Gutscheinzahlung nicht erlauben
====
Stelle im Menü *Artikel » Artikel bearbeiten » Artikel öffnen* im Tab *Global* die Option *Aktionsgutschein* auf *Verboten*, wenn der Artikel nicht per Gutschein bezahlbar sein soll. Legt der Kunde einen solchen Artikel in den Warenkorb, wird der Rabattbetrag für diesen Artikel nicht abgezogen. Dies ist z.B. bei Sonderangeboten sinnvoll, die nicht weiter rabattiert werden sollen.

Soll ein Artikel nur per Gutschein bezahlbar sein, wähle die Einstellung *Nur mit Gutschein kaufbar*.
====

[#20]
== Kampagne erstellen

Da jeder Gutschein einer Kampagne angehört, muss zuerst eine Kampagne erstellt werden. Kampagnen erstellst du im Menü *Aufträge » Gutscheine*. Bereits erstellte Kampagnen enthalten neben dem Tab *Einstellungen* 2 weitere Tabs: <<auftraege/gutscheine#60, Codes>> und <<auftraege/gutscheine#140, Vorlagen>>.

[.instruction]
Kampagne erstellen:

. Öffne das Menü *Aufträge » Gutscheine*.
. Klicke auf *Neue Kampagne* (icon:plus-square[role="green"]).
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-einstellungen-gutscheinkampagne>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.  +
→ Die Kampagne wird erstellt und in der Übersicht angezeigt.

[WARNING]
.Kampagnen nicht löschen
====
Jeder Gutschein gehört einer Kampagne an. Daher sollten Kampagnen nicht gelöscht werden, um Probleme mit bereits eingelösten Gutscheinen zu vermeiden.
====

[[tabelle-einstellungen-gutscheinkampagne]]
.Einstellungen für eine neue Gutschein-Kampagne
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Kampagne*

|*Name*
| Name der Kampagne eingeben.

|*Beschreibung*
|Beschreibung der Kampagne eingeben.

|*Konzept: Code*
|In der oberen Dropdown-Liste die Einstellung für die Codes wählen:  +
*Ein Code* = Pro Kampagne wird ein Gutschein-Code erzeugt, der mehrmals einlösbar ist.  +
*Mehrere Codes* = Es werden einzelne Gutschein-Codes erzeugt, die nur einmal einlösbar sind.

|*Konzept: Einlösungen*
|In der unteren Dropdown-Liste die Einstellung für die Einlösung(en) wählen:  +
*Mehrere Einlösungen pro Kunde* = Ein Kunde kann den Gutscheinbetrag mehrmals abrufen.  +
*_Wichtig:_* Wenn der Gutschein an mehrere Kunden verschickt wird, können diese den Gutschein unbegrenzt oft abrufen. In diesem Fall können hohe Gesamtbeträge erreicht werden. +
*Eine Einlösung pro Kunde* = Ein Gutschein kann nur einmal pro Kunde vollständig oder in Teilbeträgen abgerufen werden. Bei mehreren Kunden können diese einen niedrigeren Betrag abrufen, doch sobald der erste Kunde den Gutscheinbetrag erreicht, ist keine weitere Einlösung mehr möglich.  +
*_Hinweis:_* Ist der Kunde kein registrierter Kunde und loggt sich über einen Gastzugang ein, wird er im System als neuer Kunde geführt. Wird die Gutscheinsumme nicht komplett verbraucht, kann der Gutschein immer wieder verwendet werden, da eine Einlösung PRO Kunde eingestellt ist - also neuer Kunde, neuer Gutschein.  +
*_Wichtig:_* Teilbeträge, die unter dem Gutscheinbetrag liegen, können von allen Kunden parallel abgerufen werden. Erst wenn der erste Kunde den vollen Betrag erreicht, endet die Einlöseoption. In diesem Fall können hohe Gesamtbeträge erreicht werden. +
*Einlösung bis Wert aufgebraucht ist* = Der gesamte Betrag kann insgesamt nur einmal abgerufen werden. Ruft ein Kunde mehrere Teilbeträge ab, dürfen alle Teilbeträge zusammen nur so hoch sein wie der Gutscheinbetrag. Der Gutschein kann nicht durch mehrere Kunden eingelöst werden.  +
*Eine einzige Einlösung* = Nur ein Einlösungsvorgang ist möglich. Auch wenn dies nur ein geringer Teilbetrag ist, sind keine weiteren Einlösungen möglich.

|*Nutzung*
|*Einzelbestellungen* oder <<auftraege/scheduler#, Abonnement>> oder beides wählen.

|*Mindestbestellwert*
| Mindestbestellwert, der erreicht werden muss, damit der Gutschein eingelöst werden kann.

2+|*Gültigkeiten*

|*Startdatum*
|Das Datum, ab dem die Kampagne aktiv sein soll.

|*Enddatum*
|Das Datum, bis zu dem die Kampagne aktiv sein soll.

|*Code-Gültigkeit in Wochen*
|Anzahl der Wochen eingeben, die die Gutschein-Codes gültig sein sollen. 12 eingeben, wenn die Gutschein-Codes 12 Wochen lang gültig sein sollen. +
*_Wichtig:_* Die Gültigkeit darf dabei nicht mit den vorigen Optionen *Startdatum* und *Enddatum* verwechselt werden. Die Gültigkeit kann z.B. ein Jahr betragen (Eintrag: 52) und die Kampagne in diesem Zeitraum mehrfach gestartet und wieder beendet werden.

2+|*Gutschein*

|*Gutscheintyp*
|*Gutschein* oder *Voucher* wählen.  +
Anders als der Gutscheintyp *Gutschein* werden Gutscheine vom Typ *Voucher* nicht im Webshop, sondern bei Drittanbietern eingelöst. Voucher werden vor allem in der Hotellerie eingesetzt und dienen gleichzeitig auch als Reservierungsbestätigung.  +
*_Hinweis:_* Abhängig davon, welcher Gutscheintyp gewählt wurde, stehen unterschiedliche Einstellungen zur Verfügung.
|*Code-Zuweisung*
|Nur bei Gutscheintyp *Voucher* sichtbar.  +
Wählen, ob die Gutschein-Codes neu erzeugt werden sollen oder vorhandene benutzt werden sollen.

|*Gutscheinart*
|*Aktionsgutschein* oder *Verkaufsgutschein* wählen. Bestimmt, wie die Gutscheine im Auftrag eingelöst und in den PDF-Dokumenten dargestellt werden.  +
Für Kampagnen mit Gutscheinen, die über den Webshop verkauft werden, *Verkaufsgutschein* wählen.  +
Diese Einstellung hat auch Einfluss darauf, wie der Gutschein im Webshop verrechnet wird. <<auftraege/gutscheine#25, Ein Beispiel erläutert die Berechnungsmethode>>.

|*Code-Länge*
|Die Zeichenlänge des Gutschein-Codes wählen. Gutschein-Codes können *6*, *16*, *24* oder *32* Zeichen lang sein.

|*Rabattart*
|Art des Rabatts wählen.  +
*Festbetrag* = Festen Rabattbetrag eingeben.  +
*Prozentwert* = Prozentwert vom Rechnungsbetrag eingeben. 10 eingeben, wenn 10 Prozent des Rechnungsbetrags abgezogen werden sollen.  +
*Stück* = Stückzahlen eingeben, z.B. 3 Artikel zum Preis von 2 Artikeln.  +
*Versand* = Der Rabatt besteht in kostenlosem Versand.

|*Rabattwert*
| Rabattwert des Gutscheins eingeben. +
Option *inkl. Versandkosten* aktivieren, wenn die Versandkosten im Rabattwert eingeschlossen sein sollen.

2+|*Filter*

|*Artikel über Preisportale*
|*Erlauben* = Gutscheine gelten auch für Artikel über <<maerkte#, Preisportale>>, d.h. für Artikel, die gleichzeitig auf anderen Marktplätzen angeboten werden.  +
*Nicht erlauben* = Gutscheine können nicht für Artikel über Preisportale verwendet werden (Standardeinstellung). +
*_Hinweis:_* Preisportale sind alle Herkünfte > 1, d.h. neben Preisportalen sind hier auch Marktplätze und Plattformen inbegriffen. Die manuelle Anlage (Herkunft 0) und Webshop (Herkunft 1) sind von dieser Einstellung nicht betroffen.

|*Kategorien*
|Kategorien hinzufügen, bei denen der Gutschein einlösbar sein soll. Die Auswahl gilt auch für alle Unterkategorien einer markierten Kategorie. Es ist auch möglich, nur Unterkategorien hinzuzufügen. +
Mit einem Klick auf *Löschen* neben der Kategorie-ID und dem Kategorienamen wird die Kategorie aus der Kampagne gelöscht. Lediglich die Verknüpfung wird gelöscht, nicht aber die Kategorie selbst.

|*Artikel*
|Bis zu 20 Artikel hinzufügen, für die die Gutscheine der Kampagne einlösbar sein sollen: Die Artikel-ID in das Textfeld eingeben und auf *Hinzufügen* klicken. Alle Artikel nach diesem Muster hinzufügen.  +
Mit einem Klick auf die Artikel-ID wird der Artikel im Menü *Artikel » Artikel bearbeiten* geöffnet. Mit einem Klick auf *Löschen* auf der rechten Seite wird der Artikel aus dieser Kampagne gelöscht und aus der Liste entfernt.

|*Mandanten (Shops)*
|<<omni-channel/online-shop#, Mandanten (Shops)>> wählen, für die der Gutschein einlösbar sein soll. Mindestens ein Mandant muss gewählt werden.

|*Kundenklassen*
|<<crm/kontakte-verwalten#15, Kundenklassen>> wählen, für die der Gutschein einlösbar sein soll. Mindestens eine Kundenklasse muss gewählt werden.

|*Kundentypen*
|<<crm/kontakte-verwalten#20, Kundentypen>> wählen, für die der Gutschein einlösbar sein soll. Mindestens ein Kundentyp muss gewählt werden.

2+|*E-Mail-Vorlage*

|*Variable*
|Template-Variable für <<crm/e-mails-versenden#, E-Mail-Vorlagen>> wählen. Die Option *Keine Variable* ist voreingestellt. Eine gewählte Variable ist für weitere Kampagnen nicht mehr verfügbar.
|====

[#25.subhead]
Beispiel für die Berechnung von Aktions- und Verkaufsgutscheinen

In der Kampagne im Tab *Einstellungen* kannst du die Gutscheinart *Aktionsgutschein* oder *Verkaufsgutschein* wählen. Die Auswahl der Gutscheinart hat Einfluss darauf, wie der Gutschein im Webshop verrechnet wird. Aktionsgutscheine werden z.b. ähnlich wie Rabatte verrechnet.

[TIP]
.Beispiel für die Berechnung von Aktions- und Verkaufsgutscheinen
====
Ein Kunde hat einen Gutschein im Wert von 15 Euro. Der Kunde kauft für 25 Euro ohne MwSt. ein. Er kauft 2 Artikel. Einen Artikel für 17,95 Euro, der mit 19 % MwSt. versteuert werden muss, und einen Artikel für 7,05 Euro, auf den nur 7 % MwSt. angewendet werden. Handelt es sich bei dem Gutschein um einen *Verkaufsgutschein*, wird der Gutscheinwert vom Gesamtbetrag inkl. Steuern abgezogen. Handelt es sich um einen *Aktionsgutschein*, wird der Gutscheinwert zuerst abgezogen und dann der Restbetrag besteuert.
====

[[tabelle-vergleich-aktionsgutschein-verkaufsgutschein]]
.Vergleich von Aktionsgutschein und Verkaufsgutschein
[cols="3,3,3"]
|====
| |Verkaufsgutschein |Aktionsgutschein

|*Betrag vor Abzug des Gutscheinwertes*
|28,91 Euro inklusive MwSt.
|25 Euro exklusive MwSt.

|*Betrag nach Abzug des Gutscheinwertes*
|13,91 Euro inklusive MwSt.
|10 Euro exklusive MwSt.

11,56 Euro inklusive MwSt.

|*Durch den Kunden zu zahlender Endbetrag*
|13,91 Euro
|11,56 Euro
|====

[#55]
== Kampagne suchen

Um Kampagnen zu suchen, wähle die Suchparameter im Menü *Aufträge » Gutscheine*. In der Standardeinstellung der Filter werden alle Kampagnen gesucht und angezeigt. In der <<auftraege/auftraege-verwalten#1370, Auftragssuche>> steht ein Suchfilter für Gutschein-Codes zur Verfügung.

[.instruction]
Kampagne suchen:

. Öffne das Menü *Aufträge » Gutscheine*.
. Gib im Bereich *Filter* die ID oder den Gutschein-Code ein bzw. stelle Filteroptionen in den Dropdown-Listen ein. Beachte dazu die Erläuterungen in <<tabelle-kampagne-suchen>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Kampagnen, die den eingestellten Suchkriterien entsprechen, werden angezeigt.

[[tabelle-kampagne-suchen]]
.Kampagne suchen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|ID der Kampagne eingeben.

|*Gutschein-Code*
|Gutschein-Code eingeben.

|*Mandant*
|Mandant aus der Dropdown-Liste wählen, um nur Kampagnen dieses Mandanten anzuzeigen.

|*Kundenklasse*
|Kundenklasse aus der Dropdown-Liste wählen, um nur Kampagnen für diese Kundenklasse anzuzeigen.

|*Datum von / bis*
|Start- und Enddatum der Kampagne wählen oder manuell eingeben.

|*Gutscheinart*
|*Aktionsgutschein* oder *Verkaufsgutschein* wählen, um nur Kampagnen mit dieser Gutscheinart anzuzeigen.

|*Gutscheintyp*
|*Gutschein* oder *Voucher* wählen, um nur Kampagnen mit diesem Gutscheintyp anzuzeigen.

|*Konzept*
|*Ein Code*, *Mehrere Codes* oder *Alle* wählen.

|*Rabattart*
|Rabattart wählen, um nur Kampagnen mit dieser Rabattart anzuzeigen. Mögliche Optionen: *Festbetrag*, *Prozentwert*, *Stück*, *Versand* oder *Alle*.

|====

[#45]
== Kampagnenübersicht anzeigen

Im Menü *Aufträge » Gutscheine* im Tab *Kampagnen* werden die wichtigsten Informationen der erstellten Kampagnen in der Übersicht angezeigt. <<tabelle-kampagnenuebersicht>> erläutert die Kampagnenübersicht. Über die Funktion *Ansicht bearbeiten* entscheidest du, welche Informationen in der Übersicht angezeigt werden.

[[tabelle-kampagnenuebersicht]]
.Wichtige Informationen in der Kampagnenübersicht
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|ID der Kampagne. Wird automatisch vom System vergeben und kann nicht geändert werden.

|*Name*
|Name der Kampagne.

|*Start*
|Zeigt das Datum an, seit dem die Kampagne aktiv ist.

|*Ende*
|Zeigt das Datum an, bis zu dem die Kampagne aktiv ist. +
*_Wichtig:_* Nicht mit der Gültigkeit zu verwechseln. Dazu die Erläuterung zur Option *Code-Gültigkeit in Wochen* in <<tabelle-einstellungen-gutscheinkampagne>> beachten.

|*Gutscheintyp*
| Zeigt den Gutscheintyp an. Mögliche Werte: *Gutschein* oder *Voucher*.

|*Gutscheinart*
|Zu den Gutscheinarten *Aktionsgutschein* und *Verkaufsgutschein* die Erläuterungen in <<tabelle-einstellungen-gutscheinkampagne>> sowie das <<auftraege/gutscheine#25, Beispiel>> unter der Tabelle beachten.

|*Konzept*
|Das Konzept bestimmt z.B., ob ein Gutschein nur einmal oder mehrfach eingelöst werden kann. Erläuterungen dazu in <<tabelle-einstellungen-gutscheinkampagne>> beachten.

|*Rabatt*
| Zeigt die Rabattart sowie den dazugehörigen Wert an.

|*Mindestbestellwert*
| Mindestbestellwert, ab dem der Gutschein eingelöst werden kann.

|*Einlösungen*
|Die rote Ziffer steht für die Anzahl der eingelösten Gutscheine. Die grüne Ziffer steht für die Anzahl der noch nicht eingelösten Gutscheine.

|*Export*
|Auf *Export* (icon:download[role="purple"]) am Zeilenende der Kampagne klicken, um die Kampagnedaten in eine CSV-Datei zu exportieren.

|*Löschen*
|Auf *Löschen* (icon:minus-square[role="red"]) klicken, um die Kampagne zu löschen.

|====

[#50]
== Kampagne bearbeiten

Bereits erstellte Kampagnen kannst du jederzeit bearbeiten.

[.instruction]
Kampagne bearbeiten:

. Öffne das Menü *Aufträge » Gutscheine*.
. Suche die Kampagne, die du bearbeitest möchtest anhand der Filtereinstellungen in <<tabelle-kampagne-suchen>>.
. Klicke in die Zeile der Kampagne. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-einstellungen-gutscheinkampagne>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#60]
== Gutschein-Codes generieren

Im Menü *Aufträge » Gutschein* im Tab *Codes* einer Kampagne findest du den Gutschein-Generator. Zum Generieren von Gutschein-Codes mit dem Gutschein-Generator stehen 2 Verfahren zur Verfügung, die im Folgenden erläutert werden.

[IMPORTANT]
.Gültige Zeichen für Gutschein-Codes
====
Ein Gutschein-Code kann aus Klein- oder Großbuchstaben, Ziffern, den Sonderzeichen _ und - oder aus einer Kombination aus diesen Zeichen bestehen.
====

[#70]
=== Gutschein-Codes manuell generieren

Generiere gleichzeitig mehrere Gutschein-Codes. Diese Codes werden automatisch generiert und der Code-Liste hinzugefügt.

[.instruction]
Gutschein-Codes manuell generieren:

. Öffne das Menü *Aufträge » Gutscheine*.
. Klicke auf die Kampagne, für die du Gutschein-Codes erzeugen möchtest.
. Wechsele in das Tab *Codes*.
. Gib im Bereich *Gutschein-Codes manuell generieren* die *Anzahl* an Gutschein-Codes ein, die generiert werden soll.
. *Speichere* (icon:save[]) die Einstellungen. +
→ Die Gutschein-Codes werden generiert und in der Liste der Gutschein-Codes hinzugefügt.

[IMPORTANT]
.Mehr Codes als Einlösungen
====
Die Anzahl der offenen Gutscheine kann die maximale Anzahl der Einlösungen überschreiten. Somit können noch offene Gutschein-Codes übrig bleiben, nachdem die maximale Anzahl an Einlösungen erreicht ist. Diese sind nicht mehr einlösbar.
====

[#80]
=== Externe oder eigene Gutschein-Codes manuell eingeben

Füge eigene oder externe Codes hinzu. Dabei kann es sich um Codes handeln, die du erhalten hast und die nicht in deinem plentymarkets System generiert wurden, oder um eigene Codes, die du individuell benennst und eingibst.

[.instruction]
Gutschein-Code manuell eingeben:

. Öffne das Menü *Aufträge » Gutscheine*.
. Klicke auf die Kampagne, für die du einen Gutschein-Code eingeben möchtest.
. Wechsele in das Tab *Codes*.
. Gib im Bereich *Gutschein-Code manuell eintragen* einen *Code* mit 6 bis 32 Zeichen ein.
. *Speichere* (icon:save[]) die Einstellungen.  +
→ Der Gutschein-Code wird generiert und der Liste der Gutschein-Codes hinzugefügt.

[#90]
=== Gutscheinkampagnen und Gutschein-Codes importieren und exportieren

Verwende den ElasticSync im Menü *Daten » ElasticSync*, um <<daten/daten-importieren/sync-typen/elasticSync-gutschein-codes#, Gutschein-Codes>> zu importieren. Auf diese Weise ist es möglich, größere Mengen an Gutschein-Codes in einem Arbeitsgang zu importieren, statt sie einzeln manuell einzugeben. Erstelle dazu einen Sync des Typs *Gutschein-Code*.

Um Kampagnen zu importieren, verwende den Sync-Typ <<daten/daten-importieren/sync-typen/elasticSync-kampagnen#, Kampagnen>>.

Wenn du deine bestehenden Gutscheinkampagnen exportieren möchtest, verwende das Datenformat *Campaign* im Menü *Daten » Dynamischer Export*. Um Gutschein-Codes zu exportieren, verwende das Datenformat <<daten/export-import/datenformate/campaigncoupon#, CampaignCoupon>>.

[#100]
== Gutschein-Codes per E-Mail versenden

Gutschein-Codes können automatisch in E-Mails eingebunden werden. Beim Versenden einer E-Mail wird immer ein neuer Gutschein-Code erzeugt und versendet.

So kann auch per Newsletter jedem Kunden ein automatisch generierter Gutschein-Code zugeschickt werden. Dazu muss der Kampagne zunächst eine <<omni-channel/online-shop/webshop-einrichten/cms-syntax#grundlagen-template-variablen, Template-Variable>> zugewiesen werden, z.B. *CouponCode1*.

Danach fügst du diese Template-Variable *$CouponCode1* in eine <<crm/e-mails-versenden#1200, E-Mail-Vorlage>> ein. Bei jedem Versand wird dann automatisch ein neuer Gutschein für die Kampagne erstellt.

[IMPORTANT]
.Eine Template-Variable pro Kampagne
====
Eine Template-Variable kann nur einer Kampagne zugeordnet werden.
====

[.instruction]
Template-Variable einer Kampagne zuordnen:

. Öffne das Menü *Aufträge » Gutscheine*.
. Klicke auf die Kampagne, der du eine Variable zuordnen möchtest. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wähle im Bereich *E-Mail-Vorlage* eine *Variable* aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#110]
== Gutscheine im Webshop zum Verkauf anbieten

Bevor du Gutscheine in deinem Webshop zum Verkauf anbieten kannst, muss die <<auftraege/gutscheine#20, Gutscheinkampagne>> mit der Gutscheinart *Verkaufsgutschein* erstellt sein. Weitere Informationen findest du in <<tabelle-einstellungen-gutscheinkampagne>>.

Um Gutscheine zu verkaufen, benötigst du außerdem ein Freitextfeld sowie eine Gutscheinvorlage für die Kampagne.
Gehe wie im Folgenden beschrieben vor, um Gutscheine in deinem Webshop zu verkaufen.

[#120]
=== Gutscheinartikel erstellen

Erstelle nun einen <<artikel/artikel-verwalten#40, Gutscheinartikel>> an, den du z.B. *Gutschein1* nennst. Gib einen Preis und eine Kurzbeschreibung ein. Verknüpfe den Gutscheinartikel mit einer Kategorie. Erstelle ggf. eine eigene Kategorie für Gutscheine. Diese Parameter werden wie bei jedem Artikel im Webshop angezeigt.

[#130]
=== Gutscheinartikel mit Kampagne verknüpfen

Das Verknüpfen der Kampagne mit dem Gutscheinartikel erfolgt über ein <<artikel/artikel-verwalten#70, Freitextfeld>>.
Gehe wie im Folgenden beschrieben vor, um das Freitextfeld zu aktivieren, zu wählen und anschließend den Gutscheinartikel mit dem Freitextfeld *Kampagne ID* zu verknüpfen.

==== Freitextfeld aktivieren

Im Menü *System » Systemeinstellungen » Artikel » Freitextfelder* aktivierst du das Freitextfeld.

[.instruction]
Freitextfeld aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Artikel » Freitextfelder*.
. Gib *Kampagne ID* als Feldbezeichnung ein.
. Wähle den Datentyp *Zahl*.
. Gib die Zeichenlänge ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[WARNING]
.Nur Kampagne ID als Feldbezeichnung zulässig
====
Achte auf die Schreibweise des Freitextfeldes. Der Name *Kampagne ID* ist nur in der Schreibweise mit Leerzeichen gültig. Andere Namen und Schreibweisen sind nicht erlaubt.
====

==== Freitextfeld wählen

Wähle nun das Freitextfeld, das du für Gutscheinkampagnen verwenden möchtest. Nachdem du die Einstellung gespeichert hast, wird das Feld *Kampagne ID* im Tab *Felder* der Artikel angezeigt.

[.instruction]
Freitextfeld wählen:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Gutscheine*.
. Wähle *Kampagne ID* als *Kampagnenfeld*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

==== Kampagne mit Gutscheinartikel verknüpfen

Verknüpfe nun deine Kampagne mit einem Gutscheinartikel.

[.instruction]
Gutscheinartikel mit Kampagne verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Gutscheinartikel.
. Wechsele in das Tab *Felder*.
. Gib in das Freitextfeld, das du zuvor im Menü *System » Systemeinstellungen » Aufträge » Gutscheine* für Gutscheinkampagnen gewählt hast, die ID der Kampagne ein, die du mit dem Gutscheinartikel verknüpfen möchten.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#140]
=== Gutscheinvorlage einrichten

Im Menü *Aufträge » Gutscheine » Tab: Vorlagen* im aufklappbaren Bereich *Gutschein-Vorlage* einer Kampagne speicherst du eine Gutscheinvorlage für die Kampagne, d.h., du speicherst für jede Kampagne eine eigene Vorlage. Die Vorlage ist der Hintergrund der Gutscheine, den du entwirfst und als PDF-Datei speicherst. Im aufklappbaren Bereich *Gutschein-Layout* legst du die Elemente für den Gutschein sowie die Position der Elemente fest.

[TIP]
.PDF-Version
====
plentymarkets unterstützt derzeit PDF-Dokumentenformate bis Version 1.4.
====

[.instruction]
Gutscheinvorlage einrichten:

. Öffne das Menü *Aufträge » Gutscheine*.
. Klicke in der Übersicht auf die Gutscheinkampagne, für die du die Vorlagen bearbeiten möchtest.
. Wechsele in das Tab *Vorlagen*.
. Klappe den Bereich *Gutschein-Vorlage* auf (icon:plus-square-o[]).
. Klicke bei *Dokumenten-Vorlage Upload* auf *Datei auswählen*.
. Markiere das Dokument.
. *Speichere* (icon:save[role="green"]) die Einstellungen.  +
*_Tipp:_* Nach erfolgreichem Upload der Datei wird eine Erfolgsmeldung angezeigt. Wenn nach dem Klick auf *Vorschau anzeigen* (icon:eye[role="blue"]) eine Fehlermeldung und keine Erfolgsmeldung angezeigt wird, wende dich an den Support. Unter Umständen ist das Gutscheinverkaufsmodul für dein System nicht aktiviert.
. Klappe den Bereich *Gutschein-Layout* auf (icon:plus-square-o[]).
. Wähle den Zeichensatz aus der Dropdown-Liste.
. Gib Werte für die X- und Y-Koordinaten und für die Schriftgröße ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
*_Tipp:_* Nach erfolgreichem Speichern wird eine Erfolgsmeldung angezeigt. Klicke auf *Vorschau anzeigen* (icon:eye[role="blue"]), um einen Eindruck davon zu bekommen, wie der Gutschein aussehen wird und korrigiere die Werte, bis du mit dem Ergebnis zufrieden bist.


[TIP]
.Koordinaten
====
Mit der *X-Koordinate* stellst du den Abstand zum linken Rand der Seite ein. Die *Y-Koordinate* bestimmt den Abstand zum oberen Rand.
====

[#150]
=== Gutschein erzeugen

Der Prozess zum Kauf eines Gutscheins unterscheidet sich nicht vom Kaufprozess eines normalen Artikels. Sobald dein Kunde den Gutschein erworben hat, kann er die Gutscheintexte für die Gutscheinvorlage speichern.

[TIP]
.Hinweistext
====
Um einen persönlichen Text zu speichern, muss der Kunde in seinem *Mein Konto*-Bereich des Webshops beim Artikel noch einmal auf *Ändern* klicken. Schreibe am besten einen kurzen Hinweis in der Beschreibung des Gutscheinartikels, um Kunden darüber zu informieren.
====

Nachdem der Kunde den Gutschein gekauft hat, kann er die Gutscheintexte wie folgt anpassen:

[.instruction]
Gutscheintexte im Mein Konto anpassen:

. Im Webshop einloggen.
. Den Bereich *Mein Konto* des Webshops im Bereich *Auftragshistorie* öffnen.
. Den Auftrag mit dem Gutschein öffnen.
. Beim Artikel auf *Ändern* klicken.
. Dort kann nun ein *Empfänger*, ein *Absender* sowie ein *Text* gespeichert werden.  +
→ Diese Texte werden auf der Gutschein-Vorlage angezeigt.

Wenn der Kunde den Gutschein bezahlt hat, wird der Download der PDF-Vorlage bereitgestellt. Dies ist am PDF-Symbol erkennbar.

Nachdem das PDF-Dokument durch Klick auf *PDF erzeugen* erstellt wurde, kann der Kunde die Datei drucken oder speichern.

[#160]
=== Gutschein automatisch als PDF-Anhang verschicken

Gutscheine als PDF-Anhang zu verschicken ist z.B. sinnvoll, wenn du in deinem Webshop Geschenkgutscheine oder Reisegutscheine verkaufst.

Wenn du Gutscheine verkaufst und diese nicht im Mein-Konto-Bereich als PDF-Download zur Verfügung stellst, sondern per E-Mail versenden möchtest, erzeuge und versende Gutscheine per <<automatisierung/ereignisaktionen#, Ereignisaktion>>. Für den E-Mail-Versand benötigst du eine <<crm/e-mails-versenden#1200, E-Mail-Vorlage>>, bei der du für die Option *PDF-Anhang* den Typ *Voucher* einstellst. Der Gutschein wird der E-Mail-Vorlage dann automatisch als PDF-Anhang hinzugefügt.

[TIP]
.Tipp: Voraussetzungen für Versand per Ereignisaktion
====
Damit Gutschein-Codes per Ereignisaktion versendet werden können, benötigst du eine Gutscheinkampagne. Diese musst du am Artikel mittels Freitextfeld hinterlegt haben.
====

==== E-Mail-Vorlage einrichten

Richte wie im Folgenden beschrieben die E-Mail-Vorlage für den Gutschein ein.

[.instruction]
E-Mail-Vorlage einrichten:

. Öffne das Menü *System » Systemeinstellungen » Mandant* » _Mandant wählen_ » *E-Mail » Vorlagen*.
. Klicke auf *Neue E-Mail-Vorlage* (icon:plus-square[role="green"]).
. Gib im Fenster *Neue E-Mail-Vorlage* einen Namen für die Vorlage ein, z.B. *Reisegutschein*.
. Wähle einen *Eigner* oder *Alle* aus der Dropdown-Liste.
. Klicke auf *Speichern* (icon:save[role="green"]). +
→ Die E-Mail-Vorlage wird erstellt, in die Liste eingeordnet und geöffnet.
. Wähle aus der Dropdown-Liste *PDF-Anhang* die Einstellung *Voucher*.
. Wechsele in das Tab *E-Mail-Nachricht*.
. Gib *Betreff* und *Inhalt* ein.
. Verwende Template-Variablen, um z.B. den Namen des Kunden einzufügen. +
→ *_Wichtig:_* Füge nicht die Template-Variable für Gutscheine *$CouponCode* ein, da der Gutschein ja als Anhang versendet werden soll.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

==== Gutscheinversand per Ereignisaktion einrichten

Richte nun wie im Folgenden beschrieben die Ereignisaktion für den automatischen Versand von Gutscheinvorlagen ein.

[.instruction]
Gutscheinversand per Ereignisaktion einrichten:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke unten links auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das Ereignis gemäß <<tabelle-ereignisaktion-gutscheinvorlagen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<tabelle-ereignisaktion-gutscheinvorlagen>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-ereignisaktion-gutscheinvorlagen]]
.Ereignisaktion zum automatischen Senden von Gutscheinvorlagen
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|Zahlung > Vollständig
|

|*Filter 1*
|Auftrag > Auftragstyp
|Auftrag

|*Filter 2*
|Artikel > Artikel enthalten
|Artikel-ID eingeben.

|*Aktion 1*
|Dokumente > Verkaufsgutschein erzeugen
|*_Hinweis:_* Diese Aktion wird nur für bezahlte Aufträge ausgeführt.

|*Aktion 2*
|Auftrag > Status ändern
|Status wählen.

|*Aktion 3*
|Kunde > E-Mail versenden
|E-Mail-Vorlage wählen und *Kunde* als Empfänger wählen.

|====

[#170]
=== Gutscheinsumme auf Rechnungen anzeigen

Verkaufte Gutscheine werden auf Rechnungen als Artikelpositionen aufgeführt. Um die Summe von eingelösten Gutscheinen auf Rechnungen anzuzeigen, muss im Layout des <<auftraege/auftragsdokumente/rechnungen-erzeugen#, Rechnungsdokuments>> ein Name im Feld *Gutscheinsumme* eingegeben sein.
