= Paketinhaltsliste
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Paketinhaltsliste, Paketinhalt, Palette, Paket, ungepackte Artikel, verpackte Artikel
:description: Erfahren Sie auf dieser Handbuchseite, wie Sie die Paketinhaltsliste in plentymarkets verwenden.
:position: 300

Auf dieser Handbuchseite erfahren Sie, wie Sie die Paketinhaltsliste in plentymarkets verwenden. Die Paketinhaltsliste gibt Auskunft über den Inhalt des Pakets aus. Sie müssen eine solche Liste an Ihren Fulfillment-Dienstleister senden, damit dieser weiß, welche Artikel sich in den Paketen befinden, die er für Sie lagert und versendet.

[TIP]
.Hinweise zur Paketinhaltsliste
====
Die verfügbaren Funktionen im Menü *Aufträge » Paketinhaltsliste* richten sich in erster Linie an Mitarbeiter im Lager. Da Lagermitarbeiter nicht ständig unmittelbar vor dem Rechner sitzen, sondern sich beim Bedienen des Barcodescanenrs und beim Packen der Artikel frei bewegen, haben wir die Buttons und Kacheln in diesem Menü extra großzügig gestaltet.
====

[#100]
== Auftrags-ID eingeben

Aktuell müssen Sie die Auftrags-ID manuell eingeben. Später wird auch das Scannen der Auftrags-ID mit einem Barcodescanner möglich sein.

[#200]
== Artikel scannen

Der Artikel ist Bestandteil des Pakets. Das Paket ist Bestandteil der Palette.

Beim Scannen des Artikels wird automatisch eine Palette und ein Paket erstellt und der Artikel wird dem Paket hinzugefügt.

[#300]
== Palette bearbeiten

In den folgenden Unterkapiteln erfahren Sie, wie Sie Paletten bearbeiten können.

[#500]
=== Palette durch Scannen des Artikels erstellen

Sobald Sie einen Artikel gescannt haben, werden automatisch eine Palette und ein Paket erstellt.

Sie können die Palette jedoch auch manuell erstellen.

[#600]
=== Palette manuell hinzufügen

Mit einem Klick auf *Palette hinzufügen* wird die Palette erstellt.

[#700]
=== Palette schließen

Text

[#800]
=== Palette löschen

Text

[#900]
== Paket bearbeiten

In den folgenden Unterkapiteln erfahren Sie, wie Sie Pakete bearbeiten können.

[#1000]
=== Paket durch Scannen des Artikels erstellen

Sobald Sie einen Artikel gescannt haben, werden automatisch eine Palette und ein Paket erstellt.

Sie können das Paket jedoch auch manuell erstellen.

[#1100]
=== Paket manuell hinzufügen

Mit einem Klick auf *Paket hinzufügen* wird das Paket erstellt.

[#1200]
=== Paket schließen

Text

[#1300]
=== Paket löschen

Text

[#1400]
== Artikelliste anzeigen

<<tabelle-pil-artikelliste>> zeigt die Inhalte im Paket bzw. in der Palette, nachdem Sie die Artikel gescannt (und in das Paket gepackt haben).

[[tabelle-pil-artikelliste]]
.Artikelliste in der Paketinhaltsliste
[cols="1,3"]
|====
|Einstellung |Erläuterung

|Paletten-ID / Nr.
|

|Paket-ID / Nr.
|

|Tracking-Nr.
|

|Varianten-ID / Nr.
|

|Variantenname
|

|Barcode
|

|Menge
|

|====


[#1500]
=== Artikelmenge manuell anpassen

Text

[#1600]
=== Barcode hinzufügen

Text

[#1700]
== Ungepackte Artikel anzeigen

Text

////
== Paketinhaltsliste herunterladen und drucken

//Sie können für jedes einzelne Paket eine Paketinhaltsliste drucken, die genau Auskunft über den Inhalt des Pakets bzw. der Pakete gibt.
////
