= Paketinhaltsliste
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Paketinhaltsliste, Paketinhalt, Palette, Paket, ungepackte Artikel, verpackte Artikel, Purchase Order, Inbound, Einlieferungsliste
:description: Erfahre auf dieser Handbuchseite, wie du die Paketinhaltsliste in plentymarkets verwendest.
:position: 85
:url: auftraege/paketinhaltsliste

Auf dieser Handbuchseite erfährst du, wie du die Paketinhaltsliste in plentymarkets verwendest. Die Paketinhaltsliste gibt Auskunft über den Inhalt von Paletten, Paketen und Artikeln. Eine solche Liste ist für einen Fulfillment-Dienstleister relevant, damit dieser weiß, welche Artikel sich in den Paketen befinden, die er für dich lagert und versendet.

[TIP]
.Hinweise zur Paketinhaltsliste
====
Die verfügbaren Funktionen im Menü *Aufträge » Paketinhaltsliste* richten sich in erster Linie an die Mitarbeiter im Lager, die die Ware packen. Da Lagermitarbeiter nicht ständig unmittelbar vor dem Bildschirm sitzen, sondern sich beim Bedienen des Barcodescanners und beim Packen der Artikel frei bewegen, haben wir die Schaltflächen und Kacheln in diesem Menü extra großzügig gestaltet.
====

[#10]
== Sichtbarkeit für Backend-Benutzer einstellen

Damit für Benutzer mit dem Zugang *Backend* das Menü *Aufträge » Paketinhaltsliste* sichtbar ist, muss die Menü-Sichtbarkeit im Benutzerkonto freigeschaltet werden.

[.instruction]
Sichtbarkeit für Backend-Benutzer einstellen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Übersicht wird geöffnet.
. *_Optional:_* Gib in den Filtereinstellungen links eine ID oder einen Namen ein, um die Suche einzuschränken.
. Klicken Sie auf *Suchen*. +
→ Die gefundenen Konten werden angezeigt. +
*_Tipp:_* Ausgegraute Konten haben Admin-Rechte.
. Klicke auf das Konto, für das du die Sichtbarkeit des Menüs aktivieren möchtest.
→ Die Ansicht *Rechte* wird geöffnet.
. Klappe im Bereich *Menü-Sichtbarkeiten* den Bereich *Aufträge* auf.
. Aktiviere die Option *Paketinhaltsliste*.
. *Speichere* die Einstellungen.

[#100]
== Auftrags-ID eingeben

Aktuell musst du die Auftrags-ID manuell eingeben. Später wird auch das Scannen der Auftrags-ID mit einem Barcodescanner möglich sein.

[#200]
== Artikel scannen

Der Artikel ist Bestandteil des Pakets. Das Paket ist Bestandteil der Palette.

Beim Scannen des ersten Artikels wird automatisch eine Palette und ein Paket erstellt und der Artikel wird dem Paket hinzugefügt.

[#300]
== Palette bearbeiten

In den folgenden Unterkapiteln erfährst du, wie du Paletten bearbeiten kannst.

[#400]
=== Palette durch Scannen des Artikels erstellen

Sobald du den ersten Artikel gescannt hast, werden automatisch eine Palette und ein Paket erstellt.

Du kannst die Palette jedoch auch manuell erstellen.

[#500]
=== Palette manuell hinzufügen

Mit einem Klick auf *Palette hinzufügen* wird die Palette erstellt.

[#600]
=== Palette schließen

Wenn du die Palette schließt, sind die Palette, die Pakete und die darin enthaltenen Artikel für die weitere Bearbeitung geschlossen. Diese Aktion kann nicht rückgängig gemacht werden.

[#700]
=== Palette löschen

Wenn du die Palette löschst, werden die Palette, die Pakete sowie die darin enthaltenen Artikel gelöscht.

[#800]
== Paket bearbeiten

In den folgenden Unterkapiteln erfährst du, wie du Pakete bearbeiten kannst.

[#900]
=== Paket durch Scannen des Artikels erstellen

Sobald du den ersten Artikel gescannt hast, werden automatisch eine Palette und ein Paket erstellt.

Du kannst das Paket jedoch auch manuell erstellen.

[#1000]
=== Paket manuell hinzufügen

Mit einem Klick auf *Paket hinzufügen* wird ein neues Paket erstellt.

[#1100]
=== Paket schließen

Wenn du das Paket schließt, sind das Paket und die darin enthaltenen Artikel für die weitere Bearbeitung geschlossen. Diese Aktion kann nicht rückgängig gemacht werden.

[#1200]
=== Paket löschen

Wenn du das Paket löschst, werden das Paket sowie die darin enthaltenen Artikel gelöscht.

[#1300]
== Artikelmenge anzeigen

Im Menü *Aufträge » Paketinhaltsliste* siehst du oben rechts in der Ecke die Menge der Artikel in der folgenden Reihenfolge von links nach rechts:

* noch nicht verpackte Artikel
* verpackte Artikel
* Gesamtanzahl der Artikel

Die Anzeige aktualisiert sich automatisch, sobald du einen weiteren Artikel zum Paket hinzufügst.

[#1400]
== Artikelmenge manuell anpassen

Klicke in der Liste auf den Wert in die Zeile *Menge*, um die Menge manuell anzupassen. Die Anzahl der verpackten und noch nicht verpackten Artikel wird oben rechts in der Ecke automatisch angepasst.

[#1500]
== Barcode anzeigen

Wähle aus der Dropdown-Liste den Barcode. Die Liste enthält alle Barcode-Typen, die in deinem System verfügbar sind. Wenn für den Artikel ein Barcode vorhanden ist, wird dieser in der Übersicht angezeigt.

////
== Paketinhaltsliste herunterladen und drucken

Sie können eine komplette Gesamtübersicht der Paketinhaltsliste, die die Palettenebenen und Paketebenen auflistet, herunterladen und diese Liste dann anschließend drucken.

TODO
Später:
Sie können für jedes einzelne Paket eine Paketinhaltsliste drucken, die genau Auskunft über den Inhalt des Pakets bzw. der Pakete gibt.
////
