= eBay OAuth2 Account Management Plugin
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: eBay OAuth2 Account Management, eBay Plugin, eBay OAuth2
:description: Multi-Channel in plentymarkets: Schalte neue Konten für eBay in deinem plentymarkets System frei.
:position: 50
:url: maerkte/ebay/ebay-plugins/ebay-OAuth2
:id: BMY4DQO

Mit dem Plugin link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/ebayoauth2_4787[eBay OAuth2^]{nbsp}icon:external-link[] schaltest du neue Konten für eBay frei.

[IMPORTANT]
.Plugin eBay OAuth2 herunterladen
====
Lade das folgende Plugin herunter:

* link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/ebayoauth2_4787[eBay OAuth2^]{nbsp}icon:external-link[]

Dieses Plugin kannst du im link:https://marketplace.plentymarkets.com/[plentyMarketplace^]{nbsp}icon:external-link[] herunterladen.
====

:plugin: eBay OAuth2

[.collapseBox]
.Plugin *{plugin}* installieren
--
include::../../../plugins/_textblocks/instructions/plugin-installieren.adoc[]
--

== Konten freischalten und bearbeiten

Im Menü *Einrichtung » Märkte » eBay » OAuth2* schaltest du neue Konten für eBay frei. Dafür benötigst du die Zugangsdaten, bestehend aus Nutzername und Passwort. Wenn du deine eBay-Zugangsdaten änderst, musst du das Konto aktualisieren und synchronisieren. Du kannst mit plentymarkets mehrere eBay-Konten verwalten. Um ein oder mehrere Konten hinzuzufügen, gehst du folgendermaßen vor:

[.instruction]
Konto freischalten:

. Öffne das Menü *Einrichtung » Märkte » eBay » OAuth2*.
. Wähle *Sandbox-Koto hinzufügen*, um ein Konto für eine Testumgebung freizuschalten. +
*_oder:_* Wähle *Production-Konto hinzufügen*, wenn das neue Konto bereits produktiv ist. +
→ Du wirst zu eBay weitergeleitet und musst dort deine Daten authentifizieren. +
*_Wichtig:_* Beachte bei der Eingabe die Groß- und Kleinschreibung der Kontodaten. +
→ Das Konto wird freigeschaltet.
→ Das Konto wird im Menü *Einrichtung » Märkte » eBay » OAuth2* angezeigt.

Bei der Freischaltung oder Aktualisierung eines Kontos wird ein Token erzeugt, der 18 Monate gültig ist. Nach Ablauf der Gültigkeit erfolgt keine automatische Warnung. Der Schlüssel verliert außerdem seine Gültigkeit, wenn du deine Zugangsdaten bei eBay änderst.

Im Menü *Einrichtung » Märkte » eBay » OAuth2* hast du die Möglichkeit, Konten umzubenennen, zu aktualisieren oder zu löschen. Du musst z.B. das Konto in plentymarkets umbenennen, wenn du bei eBay deinen Mitgliedsnamen geändert hast.

== Berechtigungen erteilen

Damit Benutzer:innen mit dem Zugang *Backend* das *eBay OAuth2-Plugin* nutzen können, sind Menüberechtigungen und REST--Berechtigungen erforderlich.

Berechtigungen erteilst du im Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.

=== Menüberechtigungen erteilen

Die folgenden Menüberechtigungen sind für Benutzer:innen mit dem Zugang *Backend* erforderlich:

* Einrichtung » Märkte » eBay » OAuth2

Gehe wie unten beschrieben vor, um Benutzer:innen diese Berechtigungen zu erteilen.

[.instruction]
Menüberechtigungen zuweisen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Eine Liste der Benutzerkonten wird angezeigt.
. Klicke auf den *Benutzer*, dem du Berechtigungen zuweisen möchtest. +
*_Tipp:_* Verwende bei Bedarf die Suchfunktion (icon:search[role="blue"]). +
→ Die Ansicht *Rechte* wird geöffnet.
. Klappe in der Spalte *Menü-Sichtbarkeiten* das Menü *Einrichtung » Märkte » eBay* auf.
. Aktiviere die Option *OAuth2*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

=== REST-Berechtigungen erteilen

Die folgenden REST-Berechtigungen sind für Benutzer:innen mit dem Zugang *Backend* erforderlich:

* *Märkte » Zugangsdaten* und alle untergeordneten Berechtigungen, also:
  ** Aktualisieren
  ** Anzeigen
  ** Erstellen
  ** Löschen

* *Märkte » eBay » Marktplatz » Marktplatz anzeigen*

Gehe wie unten beschrieben vor, um Benutzer:innen diese REST-Berechtigungen zu erteilen.

[.instruction]
REST-Berechtigungen erteilen:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Eine Liste der Benutzerkonten wird angezeigt.
. Klicke auf den *Benutzer*, dem du Berechtigungen zuweisen möchtest. +
*_Tipp:_* Verwende bei Bedarf die Suchfunktion (icon:search[role="blue"]). +
→ Die Ansicht *Rechte* wird geöffnet.
. Klappe in der Spalte *Berechtigungen* den Menüpunkt *Märkte* auf.
. Aktiviere die Option *Zugangsdaten*. +
→ Alle untergeordneten Rechte werden aktiviert.
. Klappe im selben Menüpunkt *Märkte* den Punkt *eBay* auf.
. Aktiviere die Option *Marktplatz*. +
→ Das untergeordnete Recht *Anzeigen* wird aktiviert.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#1300]
== Lizenz

:license-link: https://github.com/plentymarkets/plugin-etsy/blob/master/LICENSE.md

include::../../_textblocks/explanations/plugin-lizenz.adoc[]
