= eBay OAuth2
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: eBay OAuth2 Account Management, eBay OAuth2
:description: Multi-Channel in plentymarkets: Schalte neue Konten für eBay in deinem plentymarkets System frei.
:position: 50
:url: maerkte/ebay/ebay-plugins/ebay-OAuth2
:id: BMY4DQO

Das Plugin link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/ebayoauth2_4787[eBay OAuth2^]{nbsp}icon:external-link[] wird für alle Calls benötigt, die über die neuen APIs von eBay laufen. Diese neuen APIs basieren auf der neuen Authentifizierungsmethode OAuth2 statt auf der der bisherigen Auth-n-Auth-Methode. Da die neue Authentifizierungsmethode für immer mehr essentielle Abläufe benötigt wird, solltest du das Plugin *eBay OAuth2* schon bei der Einrichtung installieren.

[IMPORTANT]
.Plugin eBay OAuth2 herunterladen
====
Lade das folgende Plugin herunter:

* link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/ebayoauth2_4787[eBay OAuth2^]{nbsp}icon:external-link[]

Dieses Plugin kannst du im link:https://marketplace.plentymarkets.com/[plentyMarketplace^]{nbsp}icon:external-link[] herunterladen.
====

:plugin: eBay OAuth2
include::../../_textblocks/instructions/plugin-installation.adoc[]


== Konten freischalten und bearbeiten

Nach der Installation des Plugins schaltest du im Menü *Einrichtung » Märkte » eBay » OAuth2* neue Konten für eBay frei. Dafür benötigst du deine eBay-Zugangsdaten, bestehend aus Nutzername und Passwort. Wenn du deine eBay-Zugangsdaten änderst, musst du das Konto aktualisieren und synchronisieren. Du kannst mit plentymarkets mehrere eBay-Konten verwalten. Um ein oder mehrere Konten hinzuzufügen, gehst du folgendermaßen vor:

[.instruction]
Konto freischalten:

. Öffne das Menü *Einrichtung » Märkte » eBay » OAuth2*.
. Wähle *Sandbox-Konto hinzufügen*, um ein Konto für eine Testumgebung freizuschalten. +
*_oder:_* Wenn das neue Konto bereits aktiv ist, wähle die Option *Production-Konto hinzufügen*. +
→ Du wirst zu eBay weitergeleitet und musst dort deine Daten authentifizieren. +
*_Wichtig:_* Beachte bei der Eingabe die Groß- und Kleinschreibung der Kontodaten. +
→ Das Konto wird freigeschaltet. +
→ Das Konto wird im Menü *Einrichtung » Märkte » eBay » OAuth2* angezeigt.

Beim Freischalten oder Aktualisieren eines Kontos wird ein Token erzeugt. Dieser Token ist 18 Monate gültig. Du erhältst keine Warnung, wenn der Token abläuft. Der Token verliert außerdem seine Gültigkeit, wenn du deine Zugangsdaten bei eBay änderst.

Im Menü *Einrichtung » Märkte » eBay » OAuth2* hast du die Möglichkeit, Konten umzubenennen, zu aktualisieren oder zu löschen. Du musst zum Beispiel das Konto in plentymarkets umbenennen, wenn du bei eBay deinen Mitgliedsnamen geändert hast.

== Berechtigungen vergeben

Damit Benutzer:innen mit dem Zugang *Backend* das *eBay OAuth2-Plugin* nutzen können, sind Menüberechtigungen und REST-Berechtigungen erforderlich.

Berechtigungen erteilst du im Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*.

=== Menüberechtigungen vergeben

Die folgenden Menüberechtigungen sind für Benutzer:innen mit dem Zugang *Backend* erforderlich:

* Einrichtung » Märkte » eBay » OAuth2

Gehe wie unten beschrieben vor, um Benutzer:innen diese Berechtigungen zu vergeben.

[.instruction]
Menüberechtigungen vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Eine Liste der Benutzerkonten wird angezeigt.
. Klicke auf den *Benutzer*, dem du Berechtigungen geben möchtest. +
*_Tipp:_* Verwende bei Bedarf die Suchfunktion (icon:search[role="blue"]). +
→ Die Ansicht *Rechte* wird geöffnet.
. Klappe in der Spalte *Menü-Sichtbarkeiten* das Menü *Einrichtung » Märkte » eBay* auf.
. Aktiviere die Option *OAuth2*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

=== REST-Berechtigungen vergeben

Die folgenden REST-Berechtigungen sind für Benutzer:innen mit dem Zugang *Backend* erforderlich:

* *Märkte » Zugangsdaten*
  ** Aktualisieren
  ** Anzeigen
  ** Erstellen
  ** Löschen

* *Märkte » eBay » Marktplatz*
  ** Anzeigen

Gehe wie unten beschrieben vor, um Benutzer:innen diese REST-Berechtigungen zu vergeben.

[.instruction]
REST-Berechtigungen vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Eine Liste der Benutzerkonten wird angezeigt.
. Klicke auf den *Benutzer*, dem du Berechtigungen geben möchtest. +
*_Tipp:_* Verwende bei Bedarf die Suchfunktion (icon:search[role="blue"]). +
→ Die Ansicht *Rechte* wird geöffnet.
. Klappe in der Spalte *Berechtigungen* den Menüpunkt *Märkte* auf.
. Aktiviere die Option *Zugangsdaten*. +
→ Alle untergeordneten Rechte werden aktiviert.
. Klappe im selben Menüpunkt *Märkte* den Punkt *eBay* auf.
. Aktiviere die Option *Marktplatz*. +
→ Das untergeordnete Recht *Anzeigen* wird aktiviert.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#1300]
== Lizenz

:license-link: https://github.com/plentymarkets/plugin-ebay-account-management/blob/master/LICENSE.md

include::../../_textblocks/explanations/plugin-lizenz.adoc[]
