= Amazon Payments Advanced
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Amazon Payments Advanced, Zahlungsart
:description: Payment in plentymarkets: Richten Sie die Schnittstelle zu Amazon Payments Advanced in Ihrem plentymarkets System ein.
:position: 12
:nav-break: Alle Zahlungsanbieter

**Bezahlen mit Amazon** ist eine umfassende Zahlungslösung für Online-Händler. Durch **Bezahlen mit Amazon** geben Sie Millionen von Amazon-Kunden die Möglichkeit, sicher auf Ihrer Website einzukaufen, ohne Versand- und Zahlungsinformationen erneut einzugeben. Kunden können Einkäufe rasch abschließen, ohne Ihre Website zu verlassen. Die Besonderheit der Advanced-Option von Bezahlen mit Amazon liegt darin, dass sie eine reine Zahlungsabwicklung bietet. Sie übermitteln nur den zur Abwicklung der Transaktion notwendigen Zahlungsbetrag – ohne Details zum Warenkorb oder zu Artikeldaten (vgl. Amazon).

[#10]
==  Wichtige Hinweise

In diesem Kapitel erhalten Sie wichtige Hinweise zur Integration des Zahlungsanbieters in plentymarkets.

[IMPORTANT]
.Amazon Payments Advanced und Webshop-Design
====
Beachten Sie, dass für die erfolgreiche Integration von Amazon Payments Advanced in plentymarkets folgende Bedingungen erfüllt sein müssen:

* Verwendung des Standard-Designs Callisto (ab Version 3.4)
* Nutzung des Individuellen Bestellvorgangs
* Sicherer Umgang mit dem plentymarkets CMS
* Erfahrung mit der Einrichtung von Zahlungsdienstleistern
====

[IMPORTANT]
.Lieferzeiten beachten
====
Aufträge mit dieser Zahlungsart sollten innerhalb 30 Tagen abgewickelt sein, da sie nach 30 Tagen sonst automatisch storniert werden. Wenn Sie generell Artikel mit längeren Lieferzeiten verkaufen, setzen Sie sich bitte mit dem Kundensupport von Amazon Payments in Verbindung. In Ausnahmefällen kann diese Frist verlängert werden.
====

[#20]
===  Bezahlvorgang mit Amazon Payments Advanced

Nachdem der Kunde einen Artikel in den Warenkorb gelegt hat (Template: **ItemViewItemToBasketConfirmationOverlay**), wird ein Button angezeigt (Template-Variable: **$AmazonPaymentsAdvancedButton**). über diesen Button wird der Kunde direkt zu Amazon Payments Advanced weitergeleitet. Der Kunde muss sich daraufhin bei Amazon Payments Advanced einloggen. Der Kunde wird dann im Webshop durch die Widgets zur Bestätigung der Versandadresse sowie der Zahlungsart geführt. Danach durchläuft er die weiteren Schritte im Bestellvorgang wie üblich. Erst nach Abschluss der Bestellung wird die Zahlung durch Amazon Payments Advanced veranlasst. +
Die Bezahlung mit Amazon Payments Advanced kann auch aus dem Warenkorb heraus ausgeführt werden, wenn dort der entsprechende Button angeklickt wird. Außerdem besteht die Möglichkeit, Amazon Payments Advanced erst im Checkout bei der Auswahl der Zahlungsart zu wählen. Hierbei wird der Kunde auf die Amazon Payments Advanced-Seite weitergeleitet. Der oben beschriebene Ablauf erfolgt.

[#30]
=== SSL-Zertifikat

Zum einen benötigt Ihr Webshop ein **<<basics/arbeiten-mit-plentymarkets/plentymarkets-konto/service-center/ssl-zertifikat#, SSL-Zertifikat  >>**, damit Sie die Zahlungsart Amazon Payments Advanced nutzen können. Außerdem ist es notwendig, nach der Konfiguration bzw. Änderungen das <<omni-channel/online-shop/cms/webdesign/webdesign-bearbeiten#, **Design zu veröffentlichen**  >>, da verschiedene Elemente der Zahlungsart im **CMS** eingebunden sind.

[#40]
==  Bei Amazon Payments Advanced registrieren

Sie benötigen für die Zahlungsart **Amazon Payments Advanced** ein separates Konto für Amazon. Sie können das im Menü **Einstellungen » Märkte » Amazon » Grundeinstellungen** angelegte Amazon Seller Central-Konto für diese Zahlungsart nicht nutzen. Der Prozess, um sich als Händler bei **Bezahlen mit Amazon** zu registrieren, wird im **link:https://www.plentymarkets.eu/documents/category/2077/Login-und-Bezahlen-Registrierungshandbuch-DE-v1-2.pdf[Amazon Payments-Registrierungshandbuch, window="_blank"]** beschrieben.

Typischerweise dauert der Vorgang der Eröffnung eines Händlerkontos inklusive Verifikation 1 bis 2 Wochen. Während dieser Zeit erhalten Sie E-Mails von Amazon Payments Advanced mit weiteren Anweisungen. Stellen Sie sicher, dass diese E-Mails dem richtigen Bearbeiter weitergeleitet werden und folgen Sie den darin enthaltenen Anweisungen, um unnötige Verzögerungen zu vermeiden.

[IMPORTANT]
.Händler-URL und Integrator-URL eingeben
====
Sie müssen bei Amazon Payments Advanced unter Händler-URL und Integrator-URL **ihr-plentyshop.de/plenty/api/payment_notification.php?payment=apa** eingeben. Ersetzen Sie **ihr-plentyshop.de** durch die Adresse Ihres Shops. Die Adresse Ihres Shops finden Sie z.B. im Menü **Einstellungen » Grundeinstellungen » API » Daten** unter **Host**. Das Protokoll **https://** muss eingegeben werden. Die Vorgehensweise wird auch im **link:https://www.plentymarkets.eu/documents/category/2077/Login-und-Bezahlen-Registrierungshandbuch-DE-v1-2.pdf[Amazon Payments-Registrierungshandbuch, window="_blank"]** beschrieben.
====

[#50]
==  Amazon Payments Advanced in plentymarkets einrichten

Um die Schnittstelle zu Amazon Payments Advanced in plentymarkets einzurichten, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Schnittstelle zu Amazon Payments Advanced einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Zahlung » Zahlungsarten**.
. Aktivieren Sie die Einstellung **Auch inaktive zeigen**.
. Öffnen Sie den Ordner **International**.
.  Klicken Sie auf **Amazon Payments Advanced**. +
→ Das Tab **Einstellungen** wird geöffnet.
. Wechseln Sie in das Tab **Schnittstelle**.
.  Klappen Sie den Mandanten auf.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen.

.Schnittstelle zu Amazon Payments Advanced einrichten
[cols="a,a"]
|====
| Einstellung | Erläuterung

|**Händler-ID**
| Händler-ID eingeben, wie von Amazon erhalten.

|**Marktplatz-ID**
| Land wählen.

|**MWS Access Key ID**
| MWS Access Key ID eingeben, wie von Amazon erhalten.

|**Secret Key**
| Secret Key eingeben, wie von Amazon erhalten.

|**Sandbox-Modus**
|**Ja** = Testmodus ist aktiv, um die Zahlungsart zu testen. +
**Nein** = Testmodus ist ausgeschaltet, d.h. die Schnittstelle ist aktiv.

|**AddressWidget Width**
| Anzahl von Pixeln eingeben, um die Breite des Amazon Adress-Widgets festzulegen. Das Adress-Widget von Amazon wird statt der Auswahl der Lieferanschrift des Webshops angezeigt.

|**AddressWidget Height**
| Anzahl von Pixeln eingeben, um die Höhe des Amazon Adress-Widgets festzulegen. Das Adress-Widget von Amazon wird statt der Auswahl der Lieferanschrift des Webshops angezeigt.

|**AddressWidget ReadOnly Width**
| Anzahl von Pixeln eingeben, um die Breite des Amazon Adress-Widgets in der Bestellübersicht festzulegen. Das Adress-Widget von Amazon in der Bestellübersicht ist nicht editierbar.

|**WalletWidget Width**
| Anzahl von Pixeln eingeben, um die Breite des Amazon Zahlungsarten-Widgets festzulegen. Dieses Widget wird im Checkout anstelle der Auswahl der Zahlungsarten angezeigt, sofern Amazon Payments Advanced gewählt wurde. Damit wird dem Kunden die gewählte Zahlungsart angezeigt.

|**WalletWidget Height**
| Anzahl von Pixeln eingeben, um die Höhe des Amazon Zahlungsarten-Widgets festzulegen.

|**WalletWidget ReadOnly Width**
| Anzahl von Pixeln eingeben, um die Breite des Amazon Zahlungsarten-Widgets in der Bestellübersicht festzulegen. Die gewählte Zahlungsart wird in der Bestellübersicht in diesem Widget angezeigt und ist nicht editierbar.

|**Verfügbarkeit**
| Verfügbarkeit wählen. +
**1** - **10** = Nur Artikel bis zu der eingestellten Verfügbarkeit können mit Amazon Payments Advanced bezahlt werden. +
**Nicht prüfen** = Die Verfügbarkeit der Artikel wird nicht geprüft. +
Die **<<artikel/artikel-verwalten#170, Verfügbarkeit >>** wird im Tab einer Variante eingestellt. +
**Wichtig:** Amazon Payments Advanced verlangt generell den Versand eines Artikels innerhalb von maximal 30 Tagen. Andernfalls wird die Zahlung storniert.
|====

[IMPORTANT]
.Ein Konto pro Mandant (Shop)
====
Sie benötigen für jeden Mandanten ein separates Konto bei Amazon Payments. Im Tab **Schnittstelle** finden Sie deshalb für jeden Mandanten ein eigenes Untermenü. Geben Sie dort die individuellen Zugangsdaten für jeden Shop ein.
====

[#70]
== Zahlungsart aktivieren

Richten Sie die **<<auftragsabwicklung/payment/zahlungsarten-verwalten#20, Zahlungsart >>** Amazon Payments Advanced im Tab **Einstellungen** der Zahlungsart ein. Prüfen Sie zudem die Einstellungen für **Erlaubte Zahlungsarten** in den **<<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Kundenklassen >>** und für **Gesperrte Zahlungsarten** in den **<<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, Versandprofilen >>**.

[#75"]
== Amazon Payments Advanced im Webshop anzeigen

Optional zur standardmäßigen Anzeige von Amazon Payments Advanced im Webshop, können Sie mit dem Template-Funktionen **Container_CheckoutAmazonPaymentsAdvancedAddressWidget()** und **Container_CheckoutAmazonPaymentsAdvancedPaymentWidget()** das Adress-Widget und das Payment-Widget für Amazon Payments Advanced individuell in Ihren Webshop anordnen. Außerdem finden Sie nachfolgend Beispiele für die Integration des **Bezahlen mit Amazon**-Buttons an den passenden Stellen im Design.

[WARNING]
.Keine Anpassungen am aktiven Design vornehmen
====
Nehmen Sie keine Änderungen an Ihrem aktiven Design vor. Bevor Sie Änderungen an Ihrem Design vornehmen, legen Sie eine Sicherungskopie an, damit Sie jederzeit wieder zum Ursprungszustand zurückgelangen.
====

[#110"]
=== Amazon Payments Advanced-Widgets anzeigen

Gehen Sie wie unten beschrieben vor, um das Adress-Widget und das Payment-Widget für Amazon Payments Advanced im Bestellvorgang anzuzeigen.

[.instruction]
Amazon Payments Advanced-Widgets im Bestellvorgang anzeigen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Öffnen Sie den Ordner des Designs, das Sie bearbeiten möchten, z.B. Callisto Light 3.
. Öffnen Sie die Kategorie **Zahlung &amp; Versand**.
. Wechseln Sie in das Tab **Beschreibung 1**.
. Fügen Sie das Code-Beispiel an der gewünschten Stelle ein.
. **Speichern** Sie die Einstellungen.

[.subhead]
Code-Beispiel für Amazon Payments Advanced-Widgets:

[source,plenty]
----
include::assets/EX-DE-Amazon-Payments-Advanced-Zahlung-Versand.html[]

----
[#120"]
=== ItemViewItemToBasketConfirmationOverlay anpassen

Gehen Sie wie unten beschrieben vor, um den **Bezahlen mit Amazon**-Button im Overlay für den Warenkorb an gewünschter Stelle einzubinden. Das Overlay wird angezeigt, nachdem der Kunde bei einem Artikel auf **In den Warenkorb** klickt.

[.instruction]
ItemViewItemToBasketConfirmationOverlay anpassen:

. Öffnen Sie das Menü **CMS » Webdesign**.
. Öffnen Sie den Ordner **Layout » ItemView**.
. Öffnen Sie das Template **ItemViewItemToBasketConfirmationOverlay**.
. Fügen Sie das Code-Beispiel an der gewünschten Stelle ein.
. **Speichern** Sie die Einstellungen.

[.subhead]
Code-Beispiel für die Integration des **Bezahlen mit Amazon**-Buttons im Overlay:

[source,plenty]
----
include::assets/EX-DE-Amazon-Payments-Advanced-Overlay.html[]

----
[#120"]
=== ItemViewBasketPreviewList anpassen

Gehen Sie wie unten beschrieben vor, um den **Bezahlen mit Amazon**-Button in der Warenkorbvorschau anzuzeigen.

[.instruction]
ItemViewBasketPreviewList anpassen:

. Öffnen Sie das Menü **CMS » Webdesign**.
. Öffnen Sie den Ordner **Layout » ItemView**.
. Öffnen Sie das Template **ItemViewBasketPreviewList**.
. Fügen Sie das Code-Beispiel an der gewünschten Stelle ein.
. **Speichern** Sie die Einstellungen.

[.subhead]
Code-Beispiel für die Integration des **Bezahlen mit Amazon**-Buttons in der Warenkorbvorschau:

[source,plenty]
----
include::assets/EX-DE-Amazon-Payments-Advanced-Warenkorbvorschau.html[]

----
[#130"]
=== Kategorie Warenkorb anpassen

Gehen Sie wie unten beschrieben vor, um den **Bezahlen mit Amazon**-Button im Warenkorb anzuzeigen.

[.instruction]
Kategorie Warenkorb anpassen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Öffnen Sie den Ordner des Designs, das Sie bearbeiten möchten, z.B. Callisto Light 3.
. Öffnen Sie die Kategorie **Warenkorb**.
. Wechseln Sie in das Tab **Beschreibung 1**.
. Fügen Sie das Code-Beispiel an der gewünschten Stelle ein.
. **Speichern** Sie die Einstellungen.

[.subhead]
Code-Beispiel für die Integration des **Bezahlen mit Amazon**-Buttons im Warenkorb:

[source,plenty]
----
include::assets/EX-DE-Amazon-Payments-Advanced-Warenkorb.html[]

----
[#140"]
=== Kategorie Anmeldung anpassen

Gehen Sie wie unten beschrieben vor, um den **Bezahlen mit Amazon**-Button auf der Anmeldeseite anzuzeigen.

[.instruction]
Kategorie Anmeldung anpassen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Öffnen Sie den Ordner des Designs, das Sie bearbeiten möchten, z.B. Callisto Light 3.
. Öffnen Sie die Kategorie **Anmeldung**.
. Wechseln Sie in das Tab **Beschreibung 1**.
. Fügen Sie das Code-Beispiel an der gewünschten Stelle ein.
. **Speichern** Sie die Einstellungen.

[.subhead]
Code-Beispiel für die Integration des **Bezahlen mit Amazon**-Buttons in der Anmeldung:

[source,plenty]
----
include::assets/EX-DE-Amazon-Payments-Advanced-Anmeldung.html[]

----
[#80]
==  Versandbestätigungen automatisch senden

Richten Sie eine <<auftragsabwicklung/auftraege/einstellungen/ereignisaktionen#, **Ereignisaktion**  >> ein, um Versandbestätigungen automatisch zu versenden, nachdem der Warenausgang gebucht wurde. Das Buchen des Warenausgangs und das Versenden der Versandbestätigung sollten nicht in einer Ereignisaktion erfolgen. Sonst kann es passieren, dass der Versand bestätigt wird, bevor der Warenausgang gebucht wurde. Richten Sie daher eine separate Ereignisaktion zur Buchung des Warenausgangs ein, die gleichzeitig den Status z.B. auf 7.1 ändert. Diesen Statuswechsel nutzen Sie wiederum bei der Ereignisaktion zur Versandbestätigung als Ereignis, damit nur für diese Aufträge eine Versandbestätigung gesendet wird. Den Status müssen Sie ggf. vorher im Menü **<<auftragsabwicklung/auftraege/einstellungen/auftragsstatus#, Einstellungen » Aufträge » Auftragsstatus  >>** erstellen.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 2.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 2 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Buchen des Warenausgangs
[cols="a,a,a"]
|====
| Einstellung | Option | Auswahl

|**Ereignis**
|**Auftragsänderung: Warenausgang gebucht**
|

|**Filter 1**
|**Auftrag &gt; Zahlungsart**
|**Amazon Payments Advanced**

|**Filter 2**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Aktion**
|**Auftrag &gt; Status ändern**
|
|====

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 3.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 3 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an Amazon Payments Advanced
[cols="a,a,a"]
|====
| Einstellung | Option | Auswahl

|**Ereignis**
|**Auftragsänderung: Statuswechsel**
|**Status aus vorheriger Ereignisaktion wählen.**

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Zahlungsart**
|**Amazon Payments Advanced**

|**Aktion**
|**Versand &gt; Versandbestätigung an Amazon Payments Advanced senden**
|
|====

[#90]
==  Stornierungen automatisch senden

Richten Sie eine <<auftragsabwicklung/auftraege/einstellungen/ereignisaktionen#, **Ereignisaktion**  >> ein, um Amazon automatisch über Stornierungen zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 4.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 4 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an Amazon Payments Advanced
[cols="a,a,a"]
|====
| Einstellung | Option | Auswahl

|**Ereignis**
|**Auftragsänderung: Statuswechsel**
| Status für **stornierte Aufträge** wählen.

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Zahlungsart**
|**Amazon Payments Advanced**

|**Aktion**
|**Zahlungsarten &gt; Stornierung an Amazon Payments Advanced senden**
|
|====

[#100]
==  Rückerstattungen automatisch senden

Damit die Rückerstattung korrekte Beträge aufweist, erstellen Sie einen **Auftragsstatus** für **Retouren** von Amazon Payments Advanced, der sicherstellt, dass die Retoure geprüft wurde und korrekt ist. Entsprechende Retouren müssen dann in diesen Auftragsstatus gesetzt werden. Dieser Auftragsstatus sollte eine treffende Bezeichnung erhalten, z.B. **Retoure geprüft**. Speichern Sie diesen Auftragsstatus bei den folgend beschriebenen Ereignisaktionen.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 5.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 5 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Rückerstattungen an Amazon Payments Advanced
[cols="a,a,a"]
|====
| Einstellung | Option | Auswahl

|**Ereignis**
|**Auftragsänderung: Statuswechsel**
| Status für **geprüfte Retouren** wählen.

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Retoure**

|**Filter 2**
|**Auftrag &gt; Zahlungsart**
|**Amazon Payments Advanced**

|**Aktion**
|**Zahlungsarten &gt; Rückerstattung an Amazon Payments Advanced senden**
|
|====

Alternativ kann die Rückerstattung auch über den Auftrag erfolgen. Erstellen Sie einen Auftragsstatus für Gutschriften von Amazon Payments Advanced, der sicherstellt, dass die Gutschrift geprüft wurde und korrekt ist. Entsprechende Gutschriften müssen dann in diesen Auftragsstatus gesetzt werden. Dieser Auftragsstatus sollte eine treffende Bezeichnung erhalten, z.B. Gutschrift geprüft. Speichern Sie diesen Auftragsstatus bei den folgend beschriebenen Ereignisaktionen.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 6.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 6 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Rückerstattungen an Amazon Payments Advanced
[cols="a,a,a"]
|====
| Einstellung | Option | Auswahl

|**Ereignis**
|**Auftragsänderung: Statuswechsel**
| Status für die **Gutschrift an Amazon Payments Advanced** wählen.

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Gutschrift**

|**Filter 2**
|**Auftrag &gt; Zahlungsart**
|**Amazon Payments Advanced**

|**Aktion**
|**Zahlungsarten &gt; Rückerstattung an Amazon Payments Advanced senden**
|
|====

[#150]
==  Abgelehnte Zahlungen automatisch melden

Richten Sie eine <<auftragsabwicklung/auftraege/einstellungen/ereignisaktionen#, **Ereignisaktion**  >> ein, um Ihre Kunden automatisch über abgelehnte Zahlungen zu informieren. Damit von Amazon abgelehnten Zahlungen automatisch per E-Mail an den Kunden und per Statuswechsel an Sie gemeldet werden, erstellen Sie einen **Auftragsstatus** für **abgelehnte Zahlungen** von Amazon Payments Advanced oder nutzen einen vorhandenen Auftragsstatus.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 7.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 7 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Melden von abgelehnten Zahlungen durch Amazon Payments Advanced
[cols="a,a,a"]
|====
| Einstellung | Option | Auswahl

|**Ereignis**
|**Zahlung: Abgelehnt**
|

|**Filter**
|**Auftrag &gt; Zahlungsart**
|**Amazon Payments Advanced**

|**Aktion 1**
|**Kunde &gt; E-Mail versenden**
| E-Mail-Vorlage wählen; +
**Kunde** wählen

|**Aktion 2**
|**Auftrag &gt; Status ändern**
| Auftragsstatus wählen, z.B. **[3.2] In Warteposition**
|====
