= BillSAFE
:lang: de
include::{includedir}/_header.adoc[]
:keywords: BillSAFE, Zahlungsart
:description: Payment in plentymarkets: Richten Sie die Schnittstelle zu BillSAFE in Ihrem plentymarkets System ein.
:position: 30

**link:http://www.billsafe.de/[BillSAFE, window="_blank"]** ist ein Anbieter für die rechnungsbasierte Zahlungslösung im Internethandel. Inzwischen wurde der Rechnungskauf mit BillSAFE in PayPal integriert. PayPal bietet den Rechnungskauf als Teil des neuen Produkts **<<auftragsabwicklung/payment/paypal-plus#, PayPal PLUS  >>** an.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhalten Sie wichtige Hinweise zur Integration des Zahlungsanbieters in plentymarkets. Nach der Auswahl der entsprechenden Zahlungsart werden Vorvalidierungen durchgeführt.

[#20]
=== Bezahlvorgang mit BillSAFE

Der Bezahlvorgang variiert für die unterschiedlichen Zahlungsarten bei BillSAFE.

[.subhead]
Rechnungskauf - 1500
In der Bestellübersicht wird ein weiterer Button für den Kaufabschluss angezeigt. Der Button lässt sich im Menü **CMS » Webdesign » Buttons » BillSAFE Rechnungskauf** bearbeiten und nach eigenen Wünschen verändern. Nach einem Klick auf den Button wird der Kunde zu BillSAFE weitergeleitet, um die Daten bei BillSAFE zu bestätigen. Nachdem die Bestätigung der Daten erfolgte, wird der Auftrag abgeschlossen und erstellt. Der Kunde wird auf die Bestellbestätigungsseite weitergeleitet.

[.subhead]
Rechnungskauf Telefon - 1502
Diese Zahlungsart ist nur für den Händler verfügbar und kann somit nur im Backend gewählt werden. Nach Auswahl der Zahlungsart muss der Händler in die Kaufabwicklung gehen und den Kauf für den Kunden abschließen. Beim Klick auf den Button erfolgt die Weiterleitung zu BillSAFE. Der Händler muss dann bei BillSAFE anrufen, die Abwicklung mit BillSAFE abschließen und anschließend den Namen des Gesprächspartners eingeben.

[.subhead]
Rechnungskauf Onsite - 1504
In der Bestellübersicht wird der Button **Zahlungspflichtig bestellen** für den Kaufabschluss angezeigt. Anders als beim Rechnungskauf, findet nach dem Klick auf den Button keine Weiterleitung des Kunden zu BillSAFE statt. Der Kunde beendet somit den Bestellprozess in Ihrem Webshop.

[#30]
=== Rechnung und Bankdaten

BillSAFE übermittelt die Bankdaten bei Eingang des Auftrags an Ihr plentymarkets System. Die Bankdaten werden dann bei Rechnungserzeugung automatisch in die Rechnung übernommen.

[#40]
== Bei BillSAFE registrieren

BillSAFE steht nur noch Händlern zur Verfügung, die diesen Service bereits nutzen. Als Neukunde können Sie sich nicht mehr bei BillSAFE registrieren. Inzwischen wurde der Rechnungskauf mit BillSAFE in PayPal integriert. PayPal bietet den Rechnungskauf als Teil des neuen Produkts **<<auftragsabwicklung/payment/paypal-plus#, PayPal PLUS  >>** an.

[#50]
== BillSAFE in plentymarkets einrichten

Um die Schnittstelle zu BillSAFE in plentymarkets einzurichten, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Schnittstelle zu BillSAFE einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Zahlung » Zahlungsarten**.
. Aktivieren Sie die Einstellung **Auch inaktive zeigen**.
. Öffnen Sie den Ordner **DE**.
.  Klicken Sie auf **BillSAFE**. +
→ Das Tab **Schnittstelle** wird geöffnet.
.  Klappen Sie den Mandanten auf.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen.

.Schnittstelle zu BillSAFE einrichten
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Merchant-ID;** +
**Merchant License;** +
**Public Key**
|Daten eingeben, wie von BillSAFE erhalten.

|**Firmenlogo**
|Logo Ihres Unternehmens oder Ihres Webshops für die Anzeige in der Kaufabwicklung bei BillSAFE speichern. +
Format: GIF, JPG oder PNG. +
Maximale Größe: 130 x 60 px. +
__**Wichtig:**__ Das Firmenlogo ist eine Pflichtangabe. +
Die Ziffer **0** mit Unterstrich im Dateinamen wird automatisch vom System eingefügt und dient systeminternen Zwecken.

|**Testbetrieb aktivieren**
|Testbetrieb aktivieren, um die BillSAFE-Funktionen zu testen, bevor mit dem System live gearbeitet wird.

////
tr>
<td><strong>Automatische Weiterleitung deaktivieren</strong></td>
<td>In der Grundeinstellung wird der Besteller direkt nach Klick auf den Button <strong>Zahlungspflichtig bestellen</strong> zu BillSAFE weitergeleitet. Wenn bei dieser Option nun ein Häkchen gesetzt wird, wird diese Automatik deaktiviert und es erscheint der Button <strong>Weiter zu BillSAFE</strong>, der zur Weiterleitung angeklickt werden muss.<br />			<i><b>Wichtig:</b></i> Ein korrekter Zahlungsprozess ist nur direkt aus dem Webshop-Bestellvorgang möglich über Klick auf den Button <strong>Zahlungspflichtig bestellen</strong>. Andernfalls kann es zu Fehlfunktionen bei der Datenübermittlung an den Zahlungsanbieter kommen.</td>
</tr
////

////
tr>
<td><strong>BillSAFE-Logo</strong></td>
<td>Die Logo-ID aus dem BillSAFE-Händlerportal speichern, um das Logo anzuzeigen.</td>
</tr
////

|**Minimaler Bestellwert**
|Eingeben, welcher Bestellwert mindestens erreicht werden soll.

|**Maximaler Bestellwert**
|Maximal zulässigen Bestellwert eingeben.

2+|**Vereinbarte Zahlungsaufschläge mit BillSAFE**

|**Zahlungsaufschlag 1**
|Einen Zahlungsaufschlag im Tab **Einstellungen** unter der Option **Kosten Inland** eingeben. Dieser wird nach dem Speichern hier angezeigt. +
__**Wichtig:**__ Die Zahlungsaufschläge müssen mit BillSAFE vereinbart werden. Nicht vereinbarte bzw. zu hohe Aufpreise führen zu Fehlern bzw. verhindern eine Kaufabwicklung.
|====

[#55]
== Zahlungsarten aktivieren

Für BillSAFE steht Ihnen mehrere Zahlungsarten zur Verfügung, die Sie im Menü **<<auftragsabwicklung/payment/zahlungsarten-verwalten#20, Einstellungen » Aufträge » Zahlung » Zahlungsarten >>** aktivieren. Prüfen Sie zudem die Einstellungen für **Erlaubte Zahlungsarten** in den **<<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Kundenklassen >>** und für **Gesperrte Zahlungsarten** in den **<<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, Versandprofilen >>**.

[IMPORTANT]
.Rechnungskauf Telefon
====
Die Zahlung wird telefonisch durch den Händler mit BillSAFE abgewickelt.
====

[#60]
== Versanddienstleister einrichten

Richten Sie die **<<auftragsabwicklung/fulfillment/versand-vorbereiten#2500, Versanddienstleister >>** für BillSAFE ein. Die Schnittstelle BillSAFE erfordert einen von BillSAFE freigegebenen Versanddienstleister. Diese sind: DP, DHL, DPD, UPS, GLS, Hermes, TNT, FEDEX.

[#70]
== Versandbestätigungen automatisch senden

Erstellen Sie die Ereignisaktionen nur für die **Zahlungsart BillSAFE**, da es sonst zu ungewollten Meldungen kommt. Denn wenn Sie im Tab **Filter** mehrere Zahlungsarten auswählen, wird die ausgelöste Meldung für BillSAFE auch an alle weiteren dort hinterlegten Payment-Provider geschickt. Richten Sie eine <<basics/automatisierung/ereignisaktionen#, **Ereignisaktion**  >> ein, um Versandbestätigungen automatisch zu versenden, nachdem der Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
.  Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das **Ereignis** gemäß Tabelle 2.
. **Speichern** Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 2 vor.
.  Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an BillSAFE
[cols="a,a,a"]
|====
| Einstellung | Option | Auswahl

|**Ereignis**
|**Auftragsänderung: Warenausgang gebucht**
|

|**Filter**
|**Auftrag &gt; Zahlungsart**
|**Rechnungskauf mit BillSAFE**

|**Aktion**
|**Versand &gt; Versandbestätigung an BillSAFE senden**
|
|====

[#80]
== Retouren automatisch senden

Sie haben 3 Möglichkeiten, um eine **Retoure** an BillSAFE zu senden. Sie können entweder eine Retoure an BillSAFE senden, wenn eine Retoure angelegt wurde, oder wenn die Retoure einen bestimmten Status erhält oder wenn eine Gutschrift einen bestimmten Status erhält. Legen Sie aber nur eine Ereignisaktion für eine der 3 Möglichkeiten zum Automatischen Senden der Retoure an BillSAFE an. Richten Sie eine <<basics/automatisierung/ereignisaktionen#, **Ereignisaktion**  >> ein, um Retouren automatisch an BillSAFE zu senden. Weitere Details zum Anlegen von Retouren finden Sie auf der Handbuchseite **<<auftragsabwicklung/auftraege/auftraege-verwalten#retoure, Retoure  >>**.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
. Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das **Ereignis** gemäß Tabelle 3.
. **Speichern** Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß Tabelle 3 vor.
. Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Retouren an BillSAFE
[cols="a,a,a"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Auftragsanlage: Neue Retoure**
|

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Retoure**

|**Filter 2**
|**Auftrag &gt; Zahlungsart**
|**Rechnungskauf mit BillSAFE**

|**Aktion**
|**Retoure &gt; Retoure an BillSAFE senden**
|
|====

[.subhead]
Retoure bei Statuswechsel melden
Statt bei Anlage einer neuen Retoure steht alternativ auch das Ereignis **Statuswechsel** zum Melden einer Retoure bei BillSAFE zur Verfügung. Nutzen Sie dieses Ereignis, um z.B. nur geprüfte Retouren an BillSAFE zu melden oder wenn Sie eine Retoure an BillSAFE melden möchten, wenn eine Gutschrift angelegt wurde. Legen Sie dazu einen **Auftragsstatus** für BillSAFE-Retouren oder für BillSAFE-Gutschriften an und wählen Sie diesen Status in der Ereignisaktion als Ereignis aus. +
Wenn Sie eine Retoure melden, wenn eine Gutschrift angelegt wurde, muss trotzdem zuvor eine Retoure für den Auftrag angelegt worden sein. Die Reihenfolge ist in dem Fall folgende:

* Retoure zum Auftrag anlegen
* Gutschrift zur Retoure anlegen
* Status der Gutschrift einstellen, der die Ereignisaktion auslöst

Legen Sie nur eine Ereignisaktion an, um Retouren an BillSAFE zu melden.

[#90]
== Stornierungen automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, **Ereignisaktion**  >> ein, um Stornierungen automatisch an BillSAFE zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü **Einstellungen » Aufträge » Ereignisaktionen**.
. Klicken Sie auf **Ereignisaktion hinzufügen**. +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das **Ereignis** gemäß Tabelle 4.
. **Speichern** Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß Tabelle 4 vor.
. Setzen Sie ein Häkchen bei **Aktiv**.
. **Speichern** Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an BillSAFE
[cols="a,a,a"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Auftragsänderung: Statuswechsel**
|Status für Stornierungen wählen.

|**Filter 1**
|**Auftrag &gt; Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Auftrag &gt; Zahlungsart**
|**Rechnungskauf mit BillSAFE**

|**Aktion**
|**Retoure &gt; Retoure an BillSAFE senden**
|
|====

[#100]
== Rechnungsvorlage für BillSAFE-Aufträge anpassen

Wenn Sie BilLSAFE nutzen und Rechnungen für Aufträge erzeugen, die mit der BillSAFE-Zahlungsart Rechnungskauf bezahlt werden, ist es notwendig, dass Sie die Bankdaten von BillSAFE auf der Rechnung anzeigen statt Ihrer Bankdaten. Dies geschieht automatisch über einen Zahlungshinweis. Wenn Sie Ihre eigene **<<auftragsabwicklung/auftraege/einstellungen/dokumente#170, PDF-Vorlage >>** verwenden möchten, gehen Sie wie nachfolgend beschrieben vor.

[IMPORTANT]
.Breite des Zahlungshinweises beachten
====
Um die Bankdaten von BillSAFE korrekt auf Ihrer Rechnung auszugeben, muss für den Zahlungshinweis im Menü **Einstellungen » Mandant (Shop) » Shop wählen » Standorte » Standort wählen » Dokumente » Rechnung** eine Breite von 120 Millimetern eigegeben werden.
====

[.instruction]
Eigene PDF-Vorlage verwenden:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Shop wählen » Standorte » Standort wählen » Dokumente » Rechnung**.
. Wechseln Sie in das Tab **PDF-Vorlage**.
. Wechseln Sie dort in das Untertab **Neue Vorlage**.
. Wählen Sie **BillSAFE** aus dem Dropdown-Menü, um die Vorlage für BillSAFE zu hinterlegen.
. Wählen Sie unter **Datei**, die auf Ihrem Rechner hinterlegte PDF-Datei.
. Klicken Sie auf **Öffnen**.
. **Speichern** Sie die Einstellungen. +
→ Die PDF-Datei wird hochgeladen und kann im Tab **Vorlagen** angezeigt werden.

Bevor Sie die Rechnung auch an Kunden schicken, informieren Sie sich, ob der Kunde nicht schon eine Rechnung von BillSAFE erhält, damit der Kunde nicht am Ende 2 Rechnungen erhält.

[#110]
== Direktzahlung melden

Wenn ein Rechnungsbetrag fälschlicherweise an Sie und nicht an BillSAFE überwiesen wurde, können Sie dies direkt an BillSAFE melden. Um die **Direktzahlung an BillSAFE** über das System zu melden, müssen die BillSAFE-Schnittstellendaten für den **Standard-Webshop** gespeichert sein, auch wenn die Zahlungsart nur für einen Mandanten (Shop) aktiv ist.

[.instruction]
Direktzahlung melden:

. Öffnen Sie das Menü **Aufträge » Auträge bearbeiten**.
. Öffnen Sie den Auftrag von BillSAFE. +
→ Das Tab **Übersicht** wird geöffnet.
. Wechseln Sie in das Tab **Zahlung**.
. Geben Sie unter **Erhaltene Direktzahlungen bei BillSAFE melden** den Rechnungsbetrag ein.
. Klicken Sie auf **Direktzahlung melden**. +
→ Der Rechnungsbetrag wird gemeldet.

[#120]
== Gutschrift senden

Es können individuelle **Gutschriftenbeträge** an BillSAFE gemeldet werden.

[.instruction]
Gutschrift senden:

. Öffnen Sie das Menü **Aufträge » Auträge bearbeiten**.
. Öffnen Sie den Auftrag von BillSAFE. +
→ Das Tab **Übersicht** wird geöffnet.
. Wechseln Sie in das Tab **Einstellungen**.
. Geben Sie unter **BillSAFE Gutschrift senden** den Betrag ein.
. Klicken Sie auf **Gutschrift senden**. +
→ Der Gutschriftenbetrag wird gesendet.

[#130]
== Stundung melden

Sie können eine **Stundung** zwischen **1** und **10** Tagen an BillSAFE melden. Dies ist z.B. dann sinnvoll, wenn der Käufer eine Retoure angemeldet hat, diese aber noch nicht bei Ihnen eingetroffen ist. Durch die Stundung wird der Start des Mahnverfahrens aufgeschoben bzw. pausiert.

[.instruction]
Stundung melden:

. Öffnen Sie das Menü **Aufträge » Auträge bearbeiten**.
. Öffnen Sie den Auftrag von BillSAFE. +
→ Das Tab **Übersicht** wird geöffnet.
. Wechseln Sie in das Tab **Einstellungen**.
. Geben Sie unter **BillSAFE Stundung** einen Wert von 1 bis 10 ein.
. Klicken Sie auf **Stundung melden**. +
→ Der Stundung wird gemeldet.

[#140]
== Statushistorie abrufen

In der Auftragsübersicht werden **Events**, **Stundungen**, **Rechnungserstellungen** und das Melden von **Gutschriften** geloggt.

[.instruction]
Statushistorie abrufen:

. Öffnen Sie das Menü **Aufträge » Auträge bearbeiten**.
. Öffnen Sie den Auftrag von BillSAFE. +
→ Das Tab **Übersicht** wird geöffnet.
. Wechseln Sie in das Tab **Statushistorie**. +
→ Eine Übersicht mit allen geloggten Ereignissen wird angezeigt.

[TIP]
.Zahlung von BillSAFE abgelehnt - was passiert dann?
====
Wenn eine Zahlung von BillSAFE **abgelehnt** wurde, dann wird die Zahlungsart auf **Vorkasse** umgestellt (Anforderung von BillSAFE) - es wird eine Meldung auch in der Statushistorie angezeigt.
====

