= CrefoPay
:lang: de
include::{includedir}/_header.adoc[]
:keywords: CrefoPay, Zahlungsart
:description: Payment in plentymarkets: Richten Sie die Schnittstelle zu CrefoPay in Ihrem plentymarkets System ein.
:position: 33

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *CrefoPay* in Callisto Shops. Die folgenden Anleitungen sind somit nicht für Ceres Shops gültig!
====

link:https://www.creditreform.de/crefopay.html[CrefoPay^] wird angeboten vom Verband der Vereine Creditreform e.V. und ist laut eigener Aussage eine Payment-Komplettlösung für den Online-Handel.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhalten Sie wichtige Hinweise zur Integration des Zahlungsanbieters *CrefoPay* in plentymarkets.

[IMPORTANT]
.CrefoPay und Webshop-Design
====
Beachten Sie, dass für die erfolgreiche Integration von CrefoPay in plentymarkets folgende Bedingungen erfüllt sein müssen:

* Verwendung des Standard-Designs Callisto (ab Version 2)
* Nutzung des Individuellen Bestellvorgangs
* Sicherer Umgang mit dem plentymarkets CMS
* Erfahrung mit der Einrichtung von Zahlungsdienstleistern
====

[.subhead]
Bezahlvorgang

Je nach gewählter Zahlungsart wird der Kunde nach dem Bestätigen der Bestellung auf eine Seite von CrefoPay weitergeleitet oder muss seine Daten direkt in einem eingeblendeten iframe eingeben. Wenn der Kunde weitergeleitet wurde, muss er dort die Daten für die gewählte Zahlungsart eingeben. Nachdem die Daten eingegeben wurden und die Zahlung durch den Kunden bestätigt wurde, wird der Kunde zurück zu Ihrem Webshop geleitet. Zahlungsarten, bei denen der Kunde weitergeleitet wird, sind Sofortüberweisung und PayPal (Stand 01.06.2016).

[#20]
== Bei CrefoPay registrieren

Registrieren Sie sich bei CrefoPay, bevor Sie die Einrichtung in plentymarkets vornehmen. Nehmen Sie link:http://www.creditreform.de/microsites/crefopay-kontakt.html[Kontakt^] zu CrefoPay auf.

[#30]
== CrefoPay in plentymarkets einrichten

Gehen Sie wie unten beschrieben vor, um die Schnittstelle zu CrefoPay einzurichten.

[.instruction]
Schnittstelle zu CrefoPay einrichten:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *DE*.
.  Klicken Sie auf *CrefoPay*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechseln Sie in das Tab *Schnittstelle*.
.  Klappen Sie den Mandanten auf.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-crefopay>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelleneinrichtung-crefopay]]
.Schnittstelle zu CrefoPay einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Testmodus*
|Testmodus aktivieren, um die Datenübertragung zwischen plentymarkets und CrefoPay zu testen, ohne dass tatsächlich Zahlungen ausgeführt werden.

|*Händler-ID*
|Händler-ID eingeben, wie von CrefoPay erhalten.

|*Private Key*
|Private Key eingeben, wie von CrefoPay erhalten.

|*Shop-ID*
|Shop-ID eingeben, wie von CrefoPay erhalten.
|====

[#40]
== Zahlungsart aktivieren

Richten Sie die <<auftragsabwicklung/payment/zahlungsarten-verwalten#20, Zahlungsart>> CrefoPay im Tab *Einstellungen* der Zahlungsart ein. Prüfen Sie zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, Versandprofilen>>. Die anzubietenden Zahlungsarten legen Sie direkt bei CrefoPay fest.

[#50]
== Einstellungen im CrefoPay-Konto vornehmen

In Ihrem CrefoPay-Konto geben Sie die URLs für die Integration ein und wählen die Zahlungsarten, die Sie mit CrefoPay anbieten möchten. Ob einem Kunden die Zahlungsarten tatsächlich angeboten werden, hängt von weiteren Faktoren, z.B. Fraud-Regeln, ab. In Ihrem CrefoPay-Konto gibt es einen Bereich für die Integration. In diesem Integrationsbereich geben Sie zwei URLs ein und wählen die Zahlungsarten, die Sie nutzen möchten. Die URLs müssen folgendem Schema entsprechen:

* Weiterleitungs-URL: https://MEIN-PLENTYSHOP.de/plenty/api/payment_notification.php?payment=crefopayredirectk
* Benachrichtigungs-URL: https://MEIN-PLENTYSHOP.de/plenty/api/payment_notification.php?payment=crefopay

[#60]
== CrefoPay im Webshop anzeigen

In diesem Kapitel wird beschrieben wie Sie CrefoPay im Webshop von plentymarkets anzeigen. Hierfür sind mehrere Schritte nötig. Zunächst wird die Kategorie *Bestellbestätigung* angepasst.

[WARNING]
.Keine Anpassungen am aktiven Design vornehmen
====
Nehmen Sie keine Änderungen an Ihrem aktiven Design vor. Bevor Sie Änderungen an Ihrem Design vornehmen, legen Sie eine Sicherungskopie an, damit Sie jederzeit wieder zum Ursprungszustand zurückgelangen.
====

[#61]
=== Kategorie Bestellbestätigung anpassen

Damit die von CrefoPay angebotenen Zahlungsarten Ihren Kunden im Webshop zur Verfügung stehen, müssen Sie Änderungen an der Kategorie *Bestellbestätigung* vornehmen.

[.instruction]
Zahlungsartenauswahl in der Bestellbestätigung hinzufügen:

. Öffnen Sie das Menü *Artikel » Kategorien*.
. Öffnen Sie den Ordner des Designs, das Sie bearbeiten möchten, z.B. Callisto Light 3.
. Öffnen Sie die Kategorie *Bestellbestätigung*.
. Wechseln Sie in das Tab *Beschreibung 1*.
. Suchen Sie *div class="panel-body"*.
. Ersetzen Sie den Inhalt dieses Div-Containers mit dem Code aus dem Code-Beispiel.
. *Speichern* Sie die Einstellungen.

[source,plenty]
----
include::assets/EX-DE-Crefopay-Bestellbestaetigung.html[]

----
[#63"]
=== CheckoutCustomerInvoiceAddress anpassen

Um bei der Adresseingabe nur für CrefoPay gültige Werte anzuzeigen, ist noch eine kleine Anpassung im Template *CheckoutCustomerInvoiceAddress* notwendig.

[.instruction]
CheckoutCustomerInvoiceAddress anpassen:

. Öffnen Sie das Menü *CMS » Webdesign*.
. Öffnen Sie den Ordner *Layout » Checkout*.
. Öffnen Sie das Template *CheckoutCustomerInvoiceAddress*.
. Suchen Sie im Code die Stelle *&lt;option value="3"{% if $FormOfAddressID == 3 %} selected{% endif %}&gt;Familie&lt;/option&gt;*.
. Löschen Sie die Code-Zeile aus dem Template.
. *Speichern* Sie die Einstellungen.

[#64"]
=== CheckoutCustomerShippingAddress anpassen

Die gleiche Änderung nehmen Sie im Template *CheckoutCustomerShippingAddress* analog vor.

[.instruction]
CheckoutCustomerShippingAddress anpassen:

. Öffnen Sie das Menü *CMS » Webdesign*.
. Öffnen Sie den Ordner *Layout » Checkout*.
. Öffnen Sie das Template *CheckoutCustomerShippingAddress*.
. Suchen Sie im Code die Stelle *&lt;option value="3"{% if $FormOfAddressID == 3 %} selected{% endif %}&gt;Familie&lt;/option&gt;*.
. Löschen Sie die Code-Zeile aus dem Template.
. *Speichern* Sie die Einstellungen.

[#65"]
=== Namensprüfung für B2B-Kunden einrichten

CrefoPay benötigt bei Bestellungen von B2B-Kunden den Vor- und Nachnamen des Kunden auf der Rechnungsadresse. Die Template-Variablen *ValidateInvoiceAddressFirstNameIfCompany* und *ValidateInvoiceAddressLastNameIfCompany* bieten die Möglichkeit Vor- und Nachnamen von B2B-Kunden für Rechnungsadressen zu prüfen, wenn das Textfeld *Firma* ebenfalls gefüllt ist.

[.instruction]
Namensprüfung für B2B-Kunden einrichten:

. Öffnen Sie das Menü *CMS » Webdesign*.
. Öffnen Sie den Ordner *Layout » PageDesign*.
. Klicken Sie auf *PageDesignPrepareMainColumn*.
. Suchen Sie die Template-Variablen *ValidateInvoiceAddressFirstNameIfCompany* und *ValidateInvoiceAddressLastNameIfCompany*.
. Ändern Sie die Werte der beiden Variablen von *false* auf *true*. Beachten Sie dazu auch die Erläuterungen in <<template-variablen-b2b>>.
. *Speichern* Sie die Einstellungen.

[[template-variablen-b2b]]
.Template-Variablen für B2B-Kunden
[cols="1,3"]
|====
| Element | Erläuterung

|*ValidateInvoiceAddressFirstNameIfCompany*
|*true* = Prüfen, ob der *Vorname* eingegeben wurde, wenn in der Rechnungsadresse das Textfeld *Firma* gefüllt ist. +
*false* = Textfeld *Vorname* nicht prüfen.

|*ValidateInvoiceAddressLastNameIfCompany*
|*true* = Prüfen, ob der *Nachname* eingegeben wurde, wenn in der Rechnungsadresse das Textfeld *Firma* gefüllt ist. +
*false* = Textfeld *Nachname* nicht prüfen.
|====

[#70]
==  Versandbestätigungen automatisch senden

Damit CrefoPay Beträge an Sie auszahlt, müssen Sie bestätigen, dass Sie dem Kunde die Ware gesendet haben. Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch zu versenden, nachdem der Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß Tabelle 3.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 3 vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an CrefoPay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag* +
Lieferauftrag - optional für Teillieferungen

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*CrefoPay*

|*Aktion*
|*Versand &gt; Versandbestätigung an CrefoPay senden*
|
|====

[#80]
==  Rückerstattungen automatisch senden

Wenn ein Käufer Artikel retourniert, legen Sie eine Retoure an und melden diese an CrefoPay, damit der Kunde das Geld von CrefoPay zurück erhält. Mithilfe einer Ereignisaktion wird die Retoure automatisch an CrefoPay gemeldet.

[.instruction]
Retoure anlegen:

[#90]

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den CrefoPay-Auftrag. +
→ Das Tab *Übersicht* wird geöffnet.
. Wählen Sie die Option *anlegen* aus der Dropdown-Liste *Retoure ...*.
. Wählen Sie die Artikel, die retourniert wurden. +
→ Die Retoure wird angelegt und geöffnet.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß Tabelle 4.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 4 vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Rückerstattungen an CrefoPay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*CrefoPay*

|*Aktion*
|*Zahlungsarten &gt; Rückerstattung an CrefoPay senden*
|
|====

[#100]
==  Stornierungen automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um CrefoPay automatisch über Stornierungen zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß Tabelle 5.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 5 vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an CrefoPay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für *stornierte Aufträge* wählen.

|*Filter*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*CrefoPay*

|*Aktion*
|*Zahlungsarten &gt; Stornierung an CrefoPay senden*
|
|====

[#110]
== Rückerstattung bei Teilstornierung an CrefoPay senden

Wenn Sie z.B. einen Artikel, den der Kunde bestellt hat, doch nicht mehr liefern können, melden Sie dies an CrefoPay, damit der Kunde sein Geld von CrefoPay zurück erhält. Diese Rückerstattung lösen Sie am Auftrag aus, indem Sie an CrefoPay melden, dass der Auftrag abgeschlossen wurde. Daraufhin erhält der Kunde den Differenzbetrag von CrefoPay, der übrig bleibt, wenn die versendeten Artikel vom Gesamtbetrag abgezogen werden.

[.instruction]
Rückerstattung melden:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den CrefoPay-Auftrag. +
→ Das Tab *Übersicht* wird geöffnet.
. Wechseln Sie in das Tab *Einstellungen*.
. Klicken Sie auf *CrefoPay-Zahlungsvorgang abschließen*.

Wenn ein Kunde mehr als den Auftragsbetrag gezahlt hat, können Sie den Zahlungsvorgang auch abschließen, um dem Kunden den zuviel gezahlten Betrag zu erstatten.
