= Alter Webshop: PAYONE
:lang: de
include::{includedir}/_header.adoc[]
:keywords: PAYONE, Zahlungsart
:description: Payment in plentymarkets: Richten Sie die Schnittstelle zu PAYONE in Ihrem plentymarkets System ein.
:position: 22

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *PAYONE* für Callisto Shops. Für die Verwendung von *PAYONE* in Ceres Shops erhalten Sie ausführliche Informationen in der Beschreibung des Plugins im link:https://marketplace.plentymarkets.com/plugins/payment/Payone_5434[plentyMarketplace^].
====

PAYONE ist ein Zahlungsanbieter mit einer breiten Palette an <<auftragsabwicklung/payment/payone#40, Zahlungsarten>>. Erfahren Sie auf dieser Seite, wie Sie Schnittstellen zu PAYONE einrichten und PAYONE im Webshop anzeigen.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhalten Sie wichtige Hinweise zur Integration des Zahlungsanbieters in plentymarkets.

[#20]
=== Bezahlvorgang mit PAYONE

Der Bezahlvorgang variiert für die unterschiedlichen Zahlungsarten bei PAYONE und wird bei den <<auftragsabwicklung/payment/payone#40, verfügbaren Zahlungsarten>> detailliert beschrieben.

[#30]
=== Zahlungseingänge

Der Zahlungseingang für Kreditkarten und Onlineüberweisungen wird nach erfolgreichem Abschluss sofort gebucht. Bei Vorkasse, Nachnahme und Rechnung wird der Zahlungseingang erst gebucht, wenn der entsprechende Status über die <<auftragsabwicklung/payment/payone#50, Transaktionsstatus-URL>> übermittelt wurde. Bei den Zahlungsarten Nachnahme und Rechnung wird der Zahlungseingang erst gebucht, wenn der Versand bestätigt wurde.

[#40]
=== Verfügbare PAYONE-Zahlungsarten

Nachfolgend finden Sie eine Übersicht der für plentymarkets verfügbaren PAYONE-Zahlungsarten mit der System-ID in Klammern.

[.subhead]
Kredit-/Debitkarten (3000)

Nach der Auswahl einer der nachfolgenden Zahlungsarten wird der Kunde dazu aufgefordert, seine Kreditkartendaten einzugeben. Die Kreditkarten werden zur Vorvalidierung direkt an PAYONE gesendet. Die Daten werden nicht beim Händler gespeichert. Sollte eine Karte am 3D-Secure teilnehmen, erhält der Kunde nach Abschluss der Bestellung einen entsprechenden Hinweis, dass er seine Karte noch durch Klick auf einen Link verifizieren muss. Beim Klick auf den Link wird der Kunde auf eine entsprechende Seite weitergeleitet. Bei Bestätigung oder Abbruch wird der Kunde zurück in den Webshop geleitet.

Folgende Zahlungsarten sind verfügbar:

* Visa (3010)
* MasterCard (3020)
* American Express (3030)
* Carte Bleue (3040)
* Diners Club (3050)
* Discover (3060)
* JCB (3070)
* Maestro (3080)

[.subhead]
Online-Überweisungen (3200)

Nach Auswahl einer der folgenden Zahlungsarten wird der Kunde aufgefordert, seine Überweisungsdaten einzugeben. Die Überweisungsdaten werden direkt an PAYONE zur Vorvalidierung gesendet. Die Daten werden nicht beim Händler gespeichert. Nach Abschluss der Bestellung wird der Kunde auf die entsprechende Seite des Zahlungsanbieters weitergeleitet. Dort muss der Kunde den beschriebenen Schritten folgen. Bei Bestätigung oder Abbruch wird der Kunde zurück in den Webshop geleitet.

Folgende Zahlungsarten sind verfügbar:

* Sofort Überweisung (3210)
* giropay (3220)
* eps (3230) - nur für Österreich
* PostFinance E-Finance (3240)
* PostFinance Card (3250)
* iDEAL (3260) - nur für Niederlande

[.subhead]
e-Wallet (3400)

Nach Abschluss der Bestellung wird der Kunde zum Zahlungsanbieter weitergeleitet, um sich einzuloggen und die Daten zu bestätigen. Nach der Bestätigung oder bei Abbruch wird der Kunde zurück in den Webshop geleitet.

Folgende Zahlungsarten sind verfügbar:

* PayPal (3410)

[.subhead]
Kontobasierte Zahlungsarten (3500)

Der Kunde wird nach Auswahl der Zahlungsart *Lastschrift* aufgefordert, seine Bankdaten in einem Eingabeformular zu hinterlegen. Die Daten werden direkt an PAYONE übermittelt. Eine Plausibilitätskontrolle wird durchgeführt. Die Daten werden nicht beim Händler gespeichert. Die Zahlung wird nach Abschluss der Bestellung veranlasst.

Folgende Zahlungsarten sind verfügbar:

* Lastschrift (3510)
* Offene Rechnung (3520)
* Vorkasse (3530)
* Nachnahme (3540)

[.subhead]
PAYONE: Kauf auf Rechnung (3600)

Nach Abschluss der Bestellung wird der Auftrag an den Zahlungsanbieter, z.B. <<auftragsabwicklung/payment/klarna#, Klarna>>, gesendet. Wenn eine positive Antwort erfolgt, wird der Auftrag angelegt. Der Kunde erhält eine Erfolgsmeldung. Kommt es zu einem Fehler oder wird die Zahlungsanfrage abgelehnt, wird der Auftrag nicht angelegt. Der Kunde erhält in der Bestellübersicht eine Fehlermeldung.

Folgende Zahlungsarten sind verfügbar:

* Klarna Rechnungskauf (3610)

[.subhead]
PAYONE: Finanzierung (3700)

Beim Auswählen der Zahlungsart, z.B. Klarna Ratenkauf, kann der Kunde direkt die Laufzeit wählen und die entsprechende Rate einsehen. Nach Abschluss der Bestellung wird der Auftrag gesendet. Sofern eine positive Antwort erfolgt, wird der Auftrag angelegt und der Kunde erhält eine Erfolgsmeldung. Kommt es zu einem Fehler oder wird die Zahlungsanfrage abgelehnt, wird der Auftrag nicht angelegt. Der Kunde erhält in der Bestellübersicht eine Fehlermeldung.

Folgende Zahlungsarten sind verfügbar:

* Klarna Ratenkauf (3710)

[#50]
== Bei PAYONE registrieren

Bevor Sie PAYONE in plentymarkets verwenden können, müssen Sie sich dort registrieren. Registrieren Sie sich bei PAYONE, indem Sie dort einen Account einrichten. Füllen Sie das link:https://www.payone.de/kontakt/angebot-anfordern/[Formular^] auf der PAYONE-Website aus. Sie erhalten dann die Zugangsdaten, die Sie für die Konfiguration in plentymarkets benötigen. Anschließend hinterlegen Sie die Transaktionsstatus-URL nach folgendem Muster im PAYONE-Backend:

*IHRE_DOMAIN/plenty/api/payone.php*

Diese URL passen Sie gemäß dem Domainnamen Ihres Shops an und hinterlegen sie in Ihrem Account im PAYONE-Backend.

[#60]
== PAYONE in Callisto einrichten

Um die Schnittstelle zu PAYONE für Ihren Callisto Shop in plentymarkets einzurichten, gehen Sie wie im Folgenden beschrieben vor.

[.instruction]
Schnittstelle zu PAYONE einrichten:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
.  Klicken Sie auf *PAYONE*. +
→ Das Tab *Schnittstelle* wird geöffnet.
.  Klappen Sie den Mandanten auf.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-payone>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelleneinrichtung-payone]]
.PAYONE-Schnittstelle einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Kundennummer*
|*Merchant-ID* eingeben, wie von PAYONE erhalten.

|*Zahlungsportal-ID*
|*Portal-ID* eingeben, wie von PAYONE erhalten.

|*Sub-Account-ID*
|ID des Sub-Accounts gemäß Bereich *ACCOUNTS* bei PAYONE eingeben.

|*Schlüssel*
|*Key* eingeben, wie von PAYONE erhalten.

|*Testmodus aktiv*
|*Ja* wählen, um den Testmodus zu aktivieren. *Nein* wählen, um den Testmodus zu deaktivieren. Die Schnittstelle ist dann im Live-Modus.

|*Shopware PAYONE-Autorisierung*
|Aktivieren, wenn PAYONE für link:https://docs.google.com/document/d/10mPeV3xqx4We71dYQdPmJK2qvb21Rpym6FG_tKwHKfc/edit#heading=h.h38ew7hip4tl[Shopware^] verwendet werden soll. Weitere Informationen finden Sie unter <<auftragsabwicklung/payment/payone#140, PAYONE für Shopware verwenden>>.
|====

[#70]
=== Adressprüfung einrichten

Bei Bedarf richten Sie außerdem eine Adressprüfung ein. Bei der Adressprüfung werden u.a. Fehler in der Adresseingabe erkannt und auf Wunsch automatisch korrigiert. Außerdem gewährleistet die Adressprüfung zusätzliche Sicherheit hinsichtlich der Identität des Kunden.

[.instruction]
Adressprüfung einrichten:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
.  Klicken Sie auf *PAYONE*. +
→ Das Tab *Schnittstelle* wird geöffnet.
.  Klappen Sie den Bereich *Adressprüfung* auf.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-einrichtung-adresspruefung-payolution>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-einrichtung-adresspruefung-payolution]]
.Adressprüfung einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Aktiv*
|*Ja* wählen, um die Adressprüfung zu aktivieren.

|*Testmodus aktiv*
|*Ja* wählen, um den Testmodus zu aktivieren. *Nein* wählen, um den Testmodus zu deaktivieren. Die Adressprüfung ist dann im Live-Modus.

|*Rechnungsadresse; +
Lieferadresse*
|Art der Adressprüfung wählen. +
*Basic* = Die Adresse wird geprüft. +
*Nicht prüfen* = Die Adresse wird nicht geprüft. +
*Person (nur für Deutschland möglich)* = Zusätzlich zur Adresse wird der Name geprüft.

|*Automatische Korrektur*
|Automatische Korrektur aktivieren. +
*JA* = Fehler werden bei der Adresseingabe automatisch korrigiert. +
*NEIN* = Fehler werden bei der Adresseingabe nicht automatisch korrigiert. +
*Benutzereingabe* = Der Benutzer kann entscheiden, ob eine vorgeschlagene Korrektur angenommen werden soll.

|*Fehlerverhalten*
|Wählen, ob der Prüfvorgang bei einem Fehler abgebrochen oder fortgesetzt werden soll.

|*Minimaler Warenwert*
|Minimalbetrag eingeben, ab dem eine Adressprüfung erfolgen soll. Die Eingabe ist optional.

|*Maximaler Warenwert*
|Maximalbetrag eingeben, bis zu dem eine Adressprüfung erfolgen soll. Die Eingabe ist optional.

|*Gültigkeit*
|Zahlenwert in Tagen eingeben, die eine Prüfung gültig sein soll. In diesem Zeitraum werden Kunden, die mehrfach bestellen, ab dem zweiten Vorgang nicht nochmals geprüft.

|*Personstatusmapping*
|Den Optionen die gewünschten Ampelwerte zuordnen. +
*GRÜN* = Einwandfreie Bonität, geringstes Risiko für Zahlungsausfälle. +
*GELB* = Toleranter, erhöht aber das Risiko. +
*ROT* = Höchstes Risiko. Bei diesem Wert sind die höchsten Zahlungsausfälle zu erwarten.
|====

[#80]
=== Bonitätsprüfung einrichten

Bei Bedarf richten Sie außerdem eine Bonitätsprüfung ein. Über die Bonitätsprüfung können Sie z.B. Kunden nur bestimmte Zahlungsarten zur Verfügung stellen. So können Sie bei einer negativen Bonitätsauskunft zum Beispiel die Zahlung per Rechnung unterbinden, eine Bestellung nicht zulassen oder einen maximalen Warenwert festlegen, der nicht überschritten werden darf.

[.instruction]
Bonitätsprüfung einrichten:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
.  Klicken Sie auf *PAYONE*. +
→ Das Tab *Schnittstelle* wird geöffnet.
.  Klappen Sie den Bereich *Bonitätsprüfung* auf.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-einrichtung-bonitaetspruefung-payone>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-einrichtung-bonitaetspruefung-payone]]
.Bonitätsprüfung einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Aktiv*
|*Ja* wählen, um die Bonitätsprüfung zu aktivieren.

|*Testmodus aktiv*
|*Ja* wählen, um den Testmodus zu aktivieren. *Nein* wählen, um den Testmodus zu deaktivieren. Die Bonitätsprüfung ist dann im Live-Modus.

|*Prüfungsart*
|Prüfungskriterien wählen. +
*Inforscore (harte Kriterien)* = Prüfung nur auf nachgewiesene Zahlungsprobleme, z.B. Zwangsvollstreckung des Kunden etc. +
*Infoscore (alle Merkmale)* = Prüfung auf alle Bonitätskriterien, z.B. auch unklare, wie Mahnbescheide. +
*Infoscore (alle Merkmale + Boniscore)* = Prüfung auf alle Bonitätskriterien, z.B. auch unklare, wie Mahnbescheide. Zusätzlich wird ein Scorewert zur Prüfung herangezogen. Der Scorewert (zwischen 100 und 990) wird anhand verschiedener Merkmale des Kunden ermittelt, z.B. Beruf und Wohnort.

|*Standardwert für Neukunden*
|Ampelwert für Bonitätsprüfung wählen, die als Standardwert für Neukunden verwendet wird. +
*GRÜN* = Einwandfreie Bonität, geringstes Risiko für Zahlungsausfälle. +
*GELB* = Toleranter, erhöht aber das Risiko. +
*ROT* = Höchstes Risiko. Bei diesem Wert sind die höchsten Zahlungsausfälle zu erwarten.

|*Gültigkeit*
|Zahlenwert in Tagen eingeben, die eine Prüfung gültig sein soll. Für diesen Zeitraum werden Kunden, die mehrfach bestellen, ab dem zweiten Vorgang nicht nochmals geprüft.

|*Minimaler Warenwert*
|Minimalbetrag eingeben, ab dem eine Bonitätsprüfung erfolgen soll. Die Eingabe ist optional.

|*Maximaler Warenwert*
|Maximalbetrag eingeben, bis zu dem eine Bonitätsprüfung erfolgen soll. Die Eingabe ist optional.

|*Fehlerverhalten*
|Wählen, ob der Prüfvorgang bei einem Fehler abgebrochen oder fortgesetzt werden soll.

|*A/B Test*
|Aktivieren und Wert eingeben, um stichprobenartig eine Bonitätsprüfung durchzuführen. Wenn z.B. nur jeder 3. Vorgang geprüft werden soll, eine 3 eingeben.
|====

[#90]
=== Schnittstellen für PAYONE-Zahlungsarten einrichten

Für die Schnittstellen der verschiedenen PAYONE-Zahlungsarten gibt es weitere Optionen. Die wichtigsten Optionen werden nachfolgend erläutert.

[.instruction]
Schnittstellen für PAYONE-Zahlungsarten einrichten:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
.  Öffnen Sie den Ordner *PAYONE*.
. Klicken Sie auf den Ordner der Zahlungsart. +
→ Das Tab *Schnittstelle* wird geöffnet.
.  Klappen Sie den Mandanten auf.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-optionen-schnittstelle-payone>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-optionen-schnittstelle-payone]]
.Weitere Optionen der Schnittstellen für PAYONE-Zahlungsarten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Nutze globale Einstellungen*
|Globale Einstellungen der Schnittstelle nutzen. +
*JA* = Einstellungen der Hauptschnittstelle (<<tabelle-schnittstelleneinrichtung-payone>>) übernehmen. Diese Optionen werden dann in der Schnittstelle ausgeblendet. +
*NEIN* = Separaten Account mit eigenen Zugangsdaten einzurichten.

|*Zugelassener Ampelwert*
|Für *Grün* gelten die strengsten Richtlinien und somit das geringste Risiko für Zahlungsausfälle. *Gelb* bedeutet ein erhöhtes Risiko für Zahlungsausfälle. *Rot* bedeutet das höchste Risiko, da bei diesem Wert die höchsten Zahlungsausfälle zu erwarten sind.

|*Klarna-Einstellungen*
|Werte eingeben, wie von Klarna erhalten, z.B. die länderbezogene *Klarna Shop-ID*, den *Klarna Kampagnen-Code* oder den *Klarna Kampagnen-Namen*.
|====

[#100]
=== SEPA für Lastschrift einrichten

Wenn Sie im Ordner *Kontobasierte Zahlungsart* die Zahlungsart *Lastschrift* über PAYONE anbieten möchten, ist es zusätzlich nötig, SEPA dafür einzurichten. Gehen Sie wie nachfolgend beschrieben vor.

[.instruction]
SEPA (Lastschrift) einrichten:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
.  Öffnen Sie den Ordner *PAYONE*.
. Klicken Sie auf den Ordner *Kontobasierte Zahlungsarten*. +
→ Das Tab *Schnittstelle* wird geöffnet.
.  Klappen Sie den Mandanten auf.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-einrichtung-sepa-payone>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-einrichtung-sepa-payone]]
.SEPA (Lastschrift) einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*zusätzliche Kontonummer/Bankleitzahl anzeigen*
|*JA* wählen, um zusätzlich zur Eingabe der SEPA-Daten, IBAN und BIC die Eingabe von Kontonummer und Bankleitzahl zu ermöglichen.

|*Mandatserteilung*
|*JA* wählen, um ein Mandat zu erstellen, das den Kunden angezeigt wird und das von den Kunden akzeptieren werden muss. +
Bei der Mandatserteilung handelt es sich um einen kostenpflichtigen Abruf. Eine Abfrage der POS-Sperrliste ist in diesem Zusammenhang nicht möglich.

|*Download Mandat als PDF*
|*JA* wählen, um dem Kunden ein PDF-Dokument des Mandats im *Mein Konto*-Bereich zum Download zur Verfügung zu stellen. +
Die Option *Download Mandat als PDF* kann nur gewählt werden, wenn bei PAYONE das Produkt *SEPA-Mandate als PDF* gebucht wurde.
|====

[#110]
== Zahlungsarten aktivieren

Für PAYONE steht Ihnen eine Vielzahl von Zahlungsarten zur Verfügung, die Sie im Menü <<auftragsabwicklung/payment/zahlungsarten-verwalten#20, System » Aufträge » Zahlung » Zahlungsarten>> aktivieren. Prüfen Sie zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<auftragsabwicklung/payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<auftragsabwicklung/fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#115]
== PAYONE im Callisto Webshop anzeigen

Im Menü *CMS* haben Sie die Möglichkeit, die Texte anzupassen, die einem Käufer im Bestellvorgang bei der Zahlungsart PAYONE angezeigt werden. Außerdem erfahren Sie, wo Sie das Design über das CSS anpassen können. Das Formular für Kreditkartendaten sowie das Formular für Online-Überweisungen passen Sie wie folgt an. Weitere Informationen finden Sie auch unter <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-kaufabwicklung, Kaufabwicklung>>.

[.instruction]
Online-Eingabeformular anpassen:

. Öffnen Sie das Menü *CMS » Webdesign*.
. Öffnen Sie den Ordner *Bestellvorgang » Kaufabwicklung*.
. Klappen Sie eine *PAYONE-Zahlungsart* auf.
. Geben Sie einen Text in das Feld *Text vor* bzw. *Text nach* ein.
. *Speichern* Sie die Einstellungen.

Das Formular für die Bestellbestätigung passen Sie wie folgt an. Weitere Informationen finden Sie auch unter <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten-bestellvorgang-bestellbestaetigung, Bestellbestätigung>>.

[.instruction]
Bestellbestätigung anpassen:

. Öffnen Sie das Menü *CMS » Webdesign*.
. Öffnen Sie den Ordner *Bestellvorgang » Bestellbestätigung*.
. Klappen Sie eine *PAYONE-Zahlungsart* auf.
. Geben Sie einen Text in das Feld *Text vor* bzw. *Text nach* ein.
. *Speichern* Sie die Einstellungen.

Das CSS für die verschiedenen PAYONE-Zahlungsarten finden Sie unter *CMS » Webdesign » Layout » CSS » CSSOrder*.

[#120]
==  Versandbestätigungen automatisch senden

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an PAYONE zu versenden, nachdem der Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß Tabelle 6.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 6 vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an PAYONE
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*PAYONE-Zahlungsart*

|*Aktion*
|*Versand &gt; Versandbestätigung an PAYONE senden*
|
|====

[#130]
== Rückerstattungen automatisch senden

Um Rückerstattungen automatisch zu senden, benötigen Sie einen <<auftragsabwicklung/auftraege/auftraege-verwalten#, Auftragsstatus>> für Gutschriften. Sie können einen Standardstatus verwenden oder einen eigenen Auftragsstatus erstellen. Nur fertig bearbeitete Gutschriften erhalten diesen Status. Diese Gutschriften dürfen nach dem Anlegen nicht geändert werden.

[IMPORTANT]
.Bedingung für Rückerstattungen
====
Rückerstattungen aus Gutschriften können nur an PAYONE gesendet werden, wenn vorher erfolgreich eine Versandbestätigung an PAYONE gesendet wurde.
====

Richten Sie eine <<basics/automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Rückerstattungen automatisch an PAYONE zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß Tabelle 7.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß Tabelle 7 vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Rückerstattungen an PAYONE
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für die *Rückerstattung an PAYONE* wählen.

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Gutschrift*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*PAYONE-Zahlungsart*

|*Aktion*
|*Zahlungsarten &gt; Gutschrift an PAYONE senden*
|
|====

[#140]
== PAYONE für Shopware verwenden

Für eine Nutzung mit Shopware hinterlegen Sie die <<auftragsabwicklung/payment/payone#50, Transaktionsstatus-URL>> im Shopware-Plugin. Im Backend von PAYONE hinterlegen Sie die URL zum Shopware-System.

[WARNING]
.PAYONE nicht parallel nutzbar
====
Wenn Sie PAYONE mit Shopware nutzen möchten, ist eine gleichzeitige Nutzung im plentymarkets Webshop nicht möglich.
====

Die Interaktion mit dem Shopsystem link:http://github.com/plentymarkets/plentymarkets-shopware-connector[Shopware^] hat folgenden Ablauf:

* Der Auftrag wird in Shopware angelegt.
* Über den Export von Shopware zu plentymarkets kommt der Auftrag in Ihr plentymarkets-System.
* Wenn der Auftrag bei Shopware als bezahlt markiert ist, wird die Zahlung importiert.
* Der Auftrag wird im Menü *Aufträge* in plentymarkets bearbeitet (Versandvorbereitung, Warenausgang etc.). +
→ Hierfür muss die Ereignisaktion für <<auftragsabwicklung/payment/payone#120, Versandbestätigungen>> eingerichtet sein.
* Bei Bedarf kann im plentymarkets System eine Gutschrift angelegt werden. +
→ Hierfür muss die Ereignisaktion für <<auftragsabwicklung/payment/payone#130, Rückerstattungen>> eingerichtet sein.
