= Währungen konfigurieren
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Währung, Standard-Währung, Live-Umrechnung
:description: Payment in plentymarkets: Konfigurieren Sie Währungen in Ihrem plentymarkets System und passen Sie die Anzeige der Währung im Webshop an.
:position: 4

In plentymarkets können Sie mit verschiedenen Währungen arbeiten, wenn Sie Ihre Artikel in verschiedenen Ländern anbieten möchten. Auf dieser Seite werden die Währungseinstellungen beschrieben, die sich global auf alle Mandanten (Shops) Ihres plentymarkets Systems auswirken. Zudem finden Sie weitere Währungseinstellungen, die sich nur auf einen einzelnen Webshop beziehen. Auf dieser Seite wird außerdem beschrieben, wie Sie im Bereich <<omni-channel/online-shop/webshop-einrichten/cms#webdesign, CMS » Webdesign>> Template-Variablen einfügen, damit Ihre Kunden selbstständig im Webshop die Währung ändern können.

[#10]
== Unterstützte Währungen

Aktuell werden in plentymarkets die folgenden Währungen unterstützt:

.Währungen in plentymarkets
[cols="a,a"]
|====
|ISO |Währung

|*AED*
|Dirham der Vereinigten Arabischen Emirate

|*ARS*
|Argentinischer Peso

|*AUD*
|Australien, Australischer Dollar

|*BGN*
|Bulgarien, Bulgarischer Lew

|*BHD*
|Bahrain-Dinar

|*BRL*
|Brasilien, Brasilianischer Real, Mehrzahl: Reais

|*CAD*
|Kanada, Kanadischer Dollar

|*CHF*
|Schweiz, Schweizer Franken

|*CNY*
|Volksrepublik China, Renminbi

|*CZK*
|Tschechische Republik, Tschechische Krone

|*DKK*
|Dänemark, Dänische Krone

|*EUR*
|Euro

|*GBP*
|Großbritannien, Pfund Sterling

|*HKD*
|Hongkong Dollar

|*HRK*
|Kroatische Kuna

|*HUF*
|Ungarn, Forint

|*IDR*
|Indonesische Rupiah

|*INR*
|Indien, Indische Rupie

|*JPY*
|Japan, Japanischer Yen

|*MXN*
|Mexiko, Mexikanischer Peso

|*MYR*
|Malaysischer Ringgit

|*NOK*
|Norwegen, Norwegische Krone

|*NZD*
|Neuseeland-Dollar

|*PHP*
|Philippinischer Peso

|*PLN*
|Polen, Zloty

|*QAR*
|Katar-Riyal

|*RON*
|Rumänien, Rumänischer Leu

|*RUB*
|Russische Föderation, Rubel

|*SEK*
|Schweden, Schwedische Krone

|*SGD*
|Singapur-Dollar

|*THB*
|Thai Baht

|*TRY*
|Türkei, Türkische Lira / Türkisches Pfund

|*TWD*
|Neuer Taiwan-Dollar

|*UAH*
|Ukrainische Hrywnja

|*USD*
|USA, US-Dollar

|*VND*
|Vietnamesischer Đồng

|*XCD*
|Ostkaribischer Dollar

|*ZAR*
|Südafrikanischer Rand
|====

[#20]
== Währung umrechnen

In <<artikel/artikel-verwalten#870, Verkaufspreisen>> aktivieren Sie unter *Währung: Live umrechnen*, ob die Shop-Währung in fremde Währungen umgerechnet wird. Zudem konfigurieren Sie die Währungseinstellungen im Menü *System » Aufträge » Zahlung » Währungen*. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Währung umrechnen:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Währungen*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dabei die Erläuterungen in <<tabelle-einstellungen-währung>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-einstellungen-währung]]
.Währungseinstellungen
[cols="a,a"]
|====
|Einstellung |Erläuterung

|*Standardwährung*
|<<auftragsabwicklung/payment/waehrungen#30, Systemwährung>> aus der Dropdown-Liste wählen.

|*Umrechnungsfaktoren täglich automatisch aktualisieren*
|Diese Option bestimmt, ob die Umrechnungsfaktoren täglich automatisch aktualisiert werden oder nicht. +
*Ja* = Die Umrechnungsfaktoren werden automatisch nachts aktualisiert. Außerdem wird in der Zeile darunter die Option *Letztes automatisches Update* eingeblendet (siehe nächste Option). +
*Nein* = Pro Währung wird ein *Reload-Symbol* angezeigt, mit dem die Wechselkurse jederzeit manuell ermittelt werden können.

|*Letztes automatisches Update*
|Letzte Aktualisierung der Umrechnungsfaktoren anzeigen. Dieses Feld ist nur sichtbar, wenn die Option *Umrechnungsfaktoren täglich automatisch aktualisieren* auf *Ja* gestellt wurde.

|*Umrechnungsfaktor Standard-Währung nach EUR, USD, CHF …*
|Die Wechselkurse sind beim Öffnen des Menüs bereits eingetragen, müssen aber ggf. aktualisiert werden. Durch Klick auf *Reload* wird der aktuelle Wechselkurs sofort manuell ermittelt. Alternativ die Option *Umrechnungsfaktoren täglich automatisch aktualisieren* auf *Ja* stellen.
|====

[#30]
== Systemwährung festlegen

Wenn Sie mit mehreren Währungen arbeiten, müssen Sie eine dieser Währungen als Standardwährung für das System festlegen. Diese Währung wird auch immer dann als voreingestellte Währung verwendet, wenn keine andere Währung gewählt wurde. In Ihrem System ist *EUR* (Euro) als Standardwährung voreingestellt.

Aufträge werden immer in der Standardwährung in plentymarkets erstellt. Für einen Auftrag wird die Währung verwendet, die der Kunde bei der Bestellung gewählt hat. Zusätzlich wird bei einer Bestellung in einer anderen Währung der aktuelle Wechselkurs gegenüber der Standardwährung mit beim Auftrag gespeichert. Diese Werte sind also jederzeit für die Auswertung der Bestelldaten oder z.B. für automatische Benachrichtigungen verfügbar.

[.instruction]
Systemwährung festlegen:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Währungen*.
. Wählen Sie eine Währung unter *Standardwährung*.
. *Speichern* Sie die Einstellungen.

Diese Einstellung ist nicht unbedingt identisch mit der <<auftragsabwicklung/payment/waehrungen#70, Anzeige der Währung im Webshop>>. Sie können für jeden Webshop und jede Sprache eine individuelle Standardwährung einstellen. Diese Einstellung nehmen Sie im Menü *System » Mandant » Mandant wählen » Webshop » Währung* vor.

[#40]
== Währung als Symbol im Bestellvorgang anzeigen

Die Währung kann als ISO-Code oder als Symbol im Webshop angezeigt werden. So würde z.B. für Euro der ISO-Code *EUR* oder das Symbol *€* angezeigt werden. Diese Einstellung bezieht sich auf die Darstellung im *Bestellvorgang* sowie im Bereich *Mein Konto*. Die Darstellung der Währung im Webshop wird ansonsten über <<auftragsabwicklung/payment/waehrungen#70, Template-Variablen und -Funktionen>> gesteuert.

[.instruction]
Währung als Symbol im Bestellvorgang anzeigen:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Webshop » Währung*.
. Wählen Sie unter *Symbol* die Option *Symbol*.
. *Speichern* Sie die Einstellungen.

////
h2>Live-Umrechnung aktivieren<a id="50." name="50."></a></h2>

<p>Der Standardpreis wird per Live-Umrechnung in die Währung umgerechnet und im Webshop angezeigt. Die Preise der verwendeten Währungen werden vom System ermittelt. Der Vorteil der Live-Umrechnung liegt darin, dass die Preise der Währungen nicht bei den Artikeln hinterlegt werden müssen, was bei umfangreichem Sortiment mit großem Aufwand verbunden ist. Um die Live-Umrechnung zu aktivieren, gehen Sie wie im folgenden beschrieben vor.</p>

<h5>Live-Umrechnung aktivieren:</h5>

<ol><li>Öffnen Sie das Menü <strong>System » Mandant » Mandant wählen » Webshop » Währung</strong>.</li>
<li>Wählen Sie die Option <strong>Live-Umrechnung</strong> für die Einstellung <strong>Währungsumrechnung</strong>.</li>
<li><strong>Speichern</strong> Sie die Einstellungen.</li>
<li>Öffnen Sie das Menü <strong>System » Aufträge » Zahlung » Währungen</strong>.</li>
<li>Wählen Sie eine Option für die Einstellung <strong>Umrechnungsfaktoren täglich automatisch aktualisieren</strong>.</li>
<li><strong>Speichern</strong> Sie die Einstellungen.</li></ol
////
[#60]
== Standardwährung für Webshop festlegen

Wenn Sie Ihren Webshop in verschiedenen Sprachen online stellen, können Sie für jede Sprache eine eigene Standardwährung festlegen. Wenn Sie mit mehreren Mandanten (Shops) arbeiten, können Sie die Einstellungen für jeden Webshop einzeln vornehmen. Wenn Sie diese Einstellungen für einen anderen Shop vornehmen möchten, finden Sie die Einstellungen analog zum Menüpunkt *Standard* im Ordner des Shops.

[.instruction]
Standardwährung für Webshop festlegen:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Webshop » Währung*.
. Wählen Sie unter *Standardwährung* eine Standardwährung für die jeweilige Sprache des Webshops.
. *Speichern* Sie die Einstellungen.

[#70]
== Anzeige der Währung im Webshop anpassen

Sie können es Ihren Kunden ermöglichen, selbst von einer Währung zu einer anderen Währung zu wechseln. Dies ist sinnvoll, wenn Sie z.B. einen deutschsprachigen Webshop betreiben und Ihre Artikel sowohl in Deutschland mit der Währung EUR als auch in der Schweiz mit der Währung CHF verkaufen möchten. Die Umschaltung von einer Währung zur anderen erfolgt mit den folgenden Template-Funktionen:

*$Link_Currency(EUR)* +
*$Link_Currency(CHF)* +
*$Link_Currency(USD)*

Diese werden mit folgenden Codes eingefügt:

*&lt;a href="$Link_Currency(EUR)"&gt;EUR&lt;/a&gt;* +
*&lt;a href="$Link_Currency(CHF)"&gt;CHF&lt;/a&gt;* +
*&lt;a href="$Link_Currency(USD)"&gt;USD&lt;/a&gt;*

[.instruction]
Template-Funktionen einfügen:

. Öffnen Sie das Menü *CMS » Webdesign*.
. Öffnen Sie den Ordner *Layout » PageDesign*.
. Öffnen Sie ein Template, z.B. *PageDesignContent*.
. Kopieren Sie den gewünschten Code oben und fügen Sie ihn an der gewünschten Stelle im Template ein.
. *Speichern* Sie die Einstellungen.

[TIP]
.Währungssymbole ersetzen
====
Falls Sie bisher mit Währungssymbolen gearbeitet haben, ersetzen Sie diese durch die Template-Variable *$Currency*. Diese Template-Variable enthält immer die aktuell im Webshop gewählte Währung.
====
