= Währungen verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Währung, Standard-Währung, Live-Umrechnung
:description: Payment in plentymarkets: Konfigurieren Sie Währungen in Ihrem plentymarkets System und passen Sie die Anzeige der Währung im Webshop an.
:position: 4

Wenn Sie Ihre Artikel in verschiedenen Ländern anbieten möchten, ist es unerlässlich, mit verschiedenen Währungen zu arbeiten. Diese Seite beschreibt die Einstellungen, die Sie dazu in Ihrem plentymarkets System vornehmen müssen.
In plentymarkets können Sie mit verschiedenen Währungen arbeiten, wenn Sie Ihre Artikel in verschiedenen Ländern anbieten möchten. Auf dieser Seite werden die Währungseinstellungen beschrieben, die sich global auf alle Mandanten (Shops) Ihres plentymarkets Systems auswirken. Zudem finden Sie weitere Währungseinstellungen, die sich nur auf einen einzelnen Webshop beziehen.

[#10]
== Unterstützte Währungen

Aktuell werden in Ihrem plentymarkets System die in <<tabelle-verfuegbare-waehrungen>> aufgelisteten Währungen unterstützt.

[[tabelle-verfuegbare-waehrungen]]
.Währungen in plentymarkets
[cols="1,3"]
|====
|ISO |Währung

|*AED*
|Dirham der Vereinigten Arabischen Emirate

|*ARS*
|Argentinischer Peso

|*AUD*
|Australien, Australischer Dollar

|*BGN*
|Bulgarien, Bulgarischer Lew

|*BHD*
|Bahrain-Dinar

|*BRL*
|Brasilien, Brasilianischer Real, Mehrzahl: Reais

|*CAD*
|Kanada, Kanadischer Dollar

|*CHF*
|Schweiz, Schweizer Franken

|*CNY*
|Volksrepublik China, Renminbi

|*CZK*
|Tschechische Republik, Tschechische Krone

|*DKK*
|Dänemark, Dänische Krone

|*EUR*
|Euro

|*GBP*
|Großbritannien, Pfund Sterling

|*HKD*
|Hongkong Dollar

|*HRK*
|Kroatische Kuna

|*HUF*
|Ungarn, Forint

|*IDR*
|Indonesische Rupiah

|*INR*
|Indien, Indische Rupie

|*JPY*
|Japan, Japanischer Yen

|*MXN*
|Mexiko, Mexikanischer Peso

|*MYR*
|Malaysischer Ringgit

|*NOK*
|Norwegen, Norwegische Krone

|*NZD*
|Neuseeland-Dollar

|*PHP*
|Philippinischer Peso

|*PLN*
|Polen, Zloty

|*QAR*
|Katar-Riyal

|*RON*
|Rumänien, Rumänischer Leu

|*RUB*
|Russische Föderation, Rubel

|*SEK*
|Schweden, Schwedische Krone

|*SGD*
|Singapur-Dollar

|*THB*
|Thai Baht

|*TRY*
|Türkei, Türkische Lira / Türkisches Pfund

|*TWD*
|Neuer Taiwan-Dollar

|*UAH*
|Ukrainische Hrywnja

|*USD*
|USA, US-Dollar

|*VND*
|Vietnamesischer Đồng

|*XCD*
|Ostkaribischer Dollar

|*ZAR*
|Südafrikanischer Rand
|====

[#20]
== Währung umrechnen

Im Menü <<artikel/artikel-verwalten#870, *System » Artikel » Verkaufspreise*>> aktivieren Sie über die Option *Währung: Live umrechnen*, ob die Währung im Webshop in fremde Währungen umgerechnet wird. +
Zudem nehmen Sie allgemeine Währungseinstellungen für alle eingehenden Aufträge im Menü *System » Aufträge » Zahlung » Währungen* vor. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Währung umrechnen:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Währungen*.
. Nehmen Sie die Einstellungen anhand von <<tabelle-einstellungen-waehrung>> vor.
. *Speichern* Sie die Einstellungen.

[[tabelle-einstellungen-waehrung]]
.Währungseinstellungen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Standard-Währung*
|<<auftragsabwicklung/payment/waehrungen#30, Systemwährung>> aus der Dropdown-Liste wählen.

|*Umrechnungsfaktoren täglich automatisch aktualisieren*
|Bestimmt, ob die Umrechnungsfaktoren täglich automatisch aktualisiert werden oder nicht. +
*Ja* = Die Umrechnungsfaktoren werden automatisch nachts aktualisiert. Außerdem wird in der Zeile darunter die Option *Letztes automatisches Update* eingeblendet (siehe nächste Option). +
*Nein* = Pro Währung wird ein *Reload-Symbol* angezeigt, mit dem Sie die Wechselkurse jederzeit manuell ermitteln können.

|*Letztes automatisches Update*
|Zeigt die letzte Aktualisierung der Umrechnungsfaktoren an. Dieses Feld ist nur sichtbar, wenn die Option *Umrechnungsfaktoren täglich automatisch aktualisieren* auf *Ja* gestellt wurde.

|*Umrechnungsfaktor Standard-Währung nach AED, ARS, AUD, …*
|Die Wechselkurse sind beim Öffnen des Menüs *System » Aufträge » Zahlung » Währungen* bereits eingetragen, müssen aber möglicherweise aktualisiert werden. Klicken Sie auf *Reload* neben der jeweiligen Währung, um den aktuellen Wechselkurs sofort manuell zu ermitteln. Setzen Sie alternativ die Option *Umrechnungsfaktoren täglich automatisch aktualisieren* auf *Ja*.
|====

[#30]
== Systemwährung festlegen

Wenn Sie mit mehreren Währungen arbeiten, müssen Sie eine dieser Währungen als Standardwährung für Ihr plentymarkets System festlegen. Diese Währung wird auch immer dann als voreingestellte Währung verwendet, wenn keine andere Währung gewählt wurde. In Ihrem System ist *EUR* (Euro) als Standardwährung voreingestellt. +
Aufträge werden immer in der Standardwährung in plentymarkets erstellt. Zusätzlich ist an jedem eingehenden Auftrag die Währung hinterlegt, die Ihre Kunden während des Bestellvorgangs gewählt haben. Zusätzlich wird bei einer Bestellung in einer anderen Währung der aktuelle Wechselkurs gegenüber der Standardwährung mit am Auftrag gespeichert. Diese Werte sind jederzeit für die Auswertung der Bestelldaten oder z.B. für automatische Benachrichtigungen verfügbar.

[.instruction]
Systemwährung festlegen:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Währungen*.
. Wählen Sie eine Währung unter *Standardwährung*.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Systemwährung vs. Währung im Webshop
====
Diese Einstellung ist nicht unbedingt identisch mit der <<auftragsabwicklung/payment/waehrungen#60, Anzeige der Währung im Webshop>>. Sie können für jeden Webshop und jede Sprache eine individuelle Standardwährung einstellen. Weitere Hinweise dazu finden Sie weiter unten auf dieser Handbuchseite.
====

[#40]
== Einstellungen im Webshop vornehmen

Nachdem Sie die Einstellungen zur <<auftragsabwicklung/payment/waehrungen#20, Währungsumrechnung>> und zur <<auftragsabwicklung/payment/waehrungen#30, Systemwährung>> vorgenommen haben, legen Sie eine Standardwährung für Ihren Webshop fest. Außerdem können Sie entscheiden, ob Kunden während des Bestellvorgangs die Währung ändern können. +
Die Einstellungen unterscheiden sich je nachdem, ob Sie Ihren Webshop unter <<auftragsabwicklung/payment/waehrungen#50, Ceres>> oder <<auftragsabwicklung/payment/waehrungen#60, Callisto>> verwenden.

[#50]
=== Ceres Webshops

Wenn Sie Ihren Webshop in plentymarkets 7 mit dem link:https://marketplace.plentymarkets.com/plugins/templates/Ceres_4697[Ceres Plugin] verwenden, finden Sie alle notwendigen Währungseinstellungen auf der Handbuchseite <<omni-channel/online-shop/ceres-einrichten#201, Ceres Webshop einrichten>>.

[#60]
=== Callisto Webshops

Die folgenden Kapitel erläutern die notwendigen Währungseinstellungen für Callisto Webshops.

[#70]
==== Callisto: Währung als Symbol im Bestellvorgang anzeigen

Die Währung kann als ISO-Code oder als Symbol im Webshop angezeigt werden. So würde z.B. für Euro der ISO-Code *EUR* oder das Symbol *€* angezeigt werden. Diese Einstellung bezieht sich auf die Darstellung im *Bestellvorgang* sowie im Bereich *Mein Konto*. Die Darstellung der Währung im Webshop wird ansonsten über <<auftragsabwicklung/payment/waehrungen#70, Template-Variablen und -Funktionen>> gesteuert.

[.instruction]
Währung als Symbol im Bestellvorgang anzeigen:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Webshop » Währung*.
. Wählen Sie unter *Symbol* die Option *Symbol*.
. *Speichern* Sie die Einstellungen.

[#80]
==== Callisto: Standardwährung für Webshop festlegen

Wenn Sie Ihren Webshop in verschiedenen Sprachen online stellen, können Sie für jede Sprache eine eigene Standardwährung festlegen. Wenn Sie mit mehreren Mandanten (Shops) arbeiten, können Sie die Einstellungen für jeden Webshop einzeln vornehmen. Wenn Sie diese Einstellungen für einen anderen Shop vornehmen möchten, finden Sie die Einstellungen analog zum Menüpunkt *Standard* im Ordner des Shops.

[.instruction]
Standardwährung für Webshop festlegen:

. Öffnen Sie das Menü *System » Mandant » Mandant wählen » Webshop » Währung*.
. Wählen Sie unter *Standardwährung* eine Standardwährung für die jeweilige Sprache des Webshops.
. *Speichern* Sie die Einstellungen.

[#90]
==== Callisto: Anzeige der Währung im Webshop anpassen

Sie können es Ihren Kunden ermöglichen, selbst von einer Währung zu einer anderen Währung zu wechseln. Dies ist sinnvoll, wenn Sie z.B. einen deutschsprachigen Webshop betreiben und Ihre Artikel sowohl in Deutschland mit der Währung EUR als auch in der Schweiz mit der Währung CHF verkaufen möchten. Die Umschaltung von einer Währung zur anderen erfolgt mit den folgenden Template-Funktionen:

*$Link_Currency(EUR)* +
*$Link_Currency(CHF)* +
*$Link_Currency(USD)*

Die Template-Funktionen werden mit folgenden Codes eingefügt:

*&lt;a href="$Link_Currency(EUR)"&gt;EUR&lt;/a&gt;* +
*&lt;a href="$Link_Currency(CHF)"&gt;CHF&lt;/a&gt;* +
*&lt;a href="$Link_Currency(USD)"&gt;USD&lt;/a&gt;*

[.instruction]
Template-Funktionen einfügen:

. Öffnen Sie das Menü *CMS » Webdesign*.
. Öffnen Sie den Ordner *Layout » PageDesign*.
. Öffnen Sie ein Template, z.B. *PageDesignContent*.
. Kopieren Sie den gewünschten Code oben und fügen Sie ihn an der gewünschten Stelle im Template ein.
. *Speichern* Sie die Einstellungen.

[TIP]
.Währungssymbole ersetzen
====
Falls Sie bisher mit Währungssymbolen gearbeitet haben, ersetzen Sie die Währungssymbole durch die Template-Variable *$Currency*. Die Template-Variable *$Currency* enthält immer die aktuell im Webshop gewählte Währung.
====
