= Artikel für den Verkauf auf Amazon vorbereiten
:lang: de
include::{includedir}/_header.adoc[]
:position: 10
:url: videos/amazon/artikel/verkauf

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Hast du dir Gedanken über deine Artikel, die du bei Amazon verkaufen möchtest, gemacht? In diesem Video erfährst du, wie du ihnen Namen, Beschreibung, Lagerbestand und Preise der Artikel an Amazon übergeben kannst.
|<<videos/amazon/artikel/verkauf-name-beschreibung#video, Name und Beschreibung wählen (0:48)>>

<<videos/amazon/artikel/verkauf-lagerbestand-lieferzeit#video, Lagerbestand und Lieferzeit (1:55)>>

<<videos/amazon/artikel/verkauf-kategorie-verknuepfen#video, Artikel mit Amazon-Kategorie verknüpfen (3:41)>>

<<videos/amazon/artikel/verkauf-verkaufspreis#video, Verkaufspreis für Amazon festlegen (4:32)>>

<<videos/amazon/artikel/verkauf-attribute#video, Attribute verknüpfen (5:27)>>

|===
//end::einleitung[]

video::199993489[vimeo]

// tag::transkript[]
[.collapseBox]
.Transkript
--
Hast Du dir schonmal Gedanken über die Artikel gemacht, die Du bei Amazon verkaufen möchtest? Über den Namen, die Beschreibung, den Lagerbestand, Preis und die Kategorie?

In diesem Video zeigen wir dir, wie du Namen und Beschreibungen hinterlegst. Du erfährst, wie der Lagerbestand und die Lieferzeit deiner Artikel berechnet werden. Außerdem erfährst du, wie du sicherstellen kannst, dass deine Artikel in die korrekte Amazon-Kategorie sortiert und mit den richtigen Verkaufspreisen und Attributen angezeigt werden. Schnüre deine Stiefel und begebe dich auf den Konfigurationspfad deiner Artikel.

Für das Video gehen wir davon aus, dass du deine Artikel und Kategorien bereits bei plentymarkets gepflegt hast. Sollte dies nicht der Fall sein, dann schaue dir die Videos zur Artikelstruktur an, bevor du fortfährst.

Soweit so gut, auf der ersten Etappe deiner Reise entscheidest Du, welchen Namen und welche Beschreibung für Amazon verwendet werden soll.

Öffne also zunächst einen Artikel deiner Wahl. Hier kannst du drei verschiedene Namen für deinen Artikel, sowie einen Vorschautext und eine Artikelbeschreibung eingeben.

Aber wie steuerst du, welcher dieser Texte auf Amazon angezeigt werden soll? Navigiere doch einfach zu deinen Amazon-Einstellungen und öffne die Artikeleinstellungen. Hier unten kannst du dann auswählen, welcher Name und welche Beschreibung zu Amazon übergeben werden sollen. Entscheide einfach, ob du den Namen 1, 2 oder 3 als Artikelname auf Amazon nutzen möchtest und ob die Vorschau oder die Artikelbeschreibung bei Amazon angezeigt werden soll.

Diese Einstellung solltest du auf nein Stellen, damit nicht unbeabsichtigt HTML-Tags aus deinen Artikeltexten zu Amazon übergeben werden. Bis auf wenige Ausnahmen verbietet Amazon nämlich diese HTML-Tags.

Mit diesen Einstellungen gibst du an, wie die Lagerbestände deiner Artikel bei Amazon berechnet werden und wie lange es für gewöhnlich dauert dauert, deine Artikel zu versenden.

Fangen wir damit an, plentymarkets zu sagen welchen Lagerbestand bzw. welche Lagerbestände zu Amazon übertragen werden sollen. Im Wesentlichen wird das von dir gewählte Lager als Bezugspunkt verwendet, um festzustellen, wie viele Exemplare des Artikels auf Lager sind. In einigen Fällen möchtest du das Lager möglicherweise selber wählen. Wenn du dann hier ein bestimmtes Lager auswählen möchtest, solltest du auf jeden Fall darauf achten, dass es sich dabei nicht um ein FBA-Lager handelt!

Zuerst schauen wir uns jetzt diese Einstellung an, weil sie ziemlich einfach ist. Hier definierst du ganz einfach einen maximalen Lagerbestand, den du an Amazon meldest. Gibst du also beispielsweise 60 ein, übergibt plentymarkets als Lagerbestand höchstens 60 Einheiten eines Artikels, auch wenn du mehr davon auf Lager hast.

Als nächstes schauen wir uns den Bestandspuffer an. Dieser Puffer gilt grundsätzlich nur für Artikel, deren Nettowarenbestand beschränkt ist. Gib hier einfach eine Zahl ein und Tadaaaa, so hast du immer einen kleinen Pufferwarenbestand in deinem Lager.

Die letzte Option ist dann nützlich, wenn einige deiner Artikel nicht auf den Nettobestand beschränkt sind.

Sag plentymarkets, wie viele Einheiten deiner Artikel an Amazon übertragen werden sollen. In diesem Beispiel wird die Information an Amazon übergeben, dass für alle Artikel, die nicht nettowarenbestandbeschränkt sind, 5 Einheiten verfügbar sind.

Schließlich entscheidest Du, ob die durchschnittliche Lieferzeit des Artikels zu Amazon übergeben werden soll oder sogar zusätzlich dazu eine Bearbeitungszeit, welche auf die durchschnittliche Lieferzeit aufaddiert wird. Beachte bitte, dass dieser Wert nicht exklusiv als Lieferzeit an Amazon übergeben wird. Vielmehr wird er zu dem Wert addiert, den Du am Versandprofil im Sellercentral hinterlegen kannst. Die restlichen Einstellungen in diesem Menü kannst du vorerst ignorieren und einfach auf speichern klicken.

Um unsere Route weiter zu gehen müssen nun deine Kategorien mit den Kategorien von Amazon abgestimmt werden!

Stellen wir uns jede Amazon-Kategorie mit einer ID vor, diese wird als Browse-Node bezeichnet. Jetzt musst du deine Kategorien mit den Browse-Nodes verknüpfen.

Also frisch ans Werk und das Menü Kategorieverknüpfung geöffnet. Wenn Du hier die Lupe klickst wirst du zum Amazon-Klassifikationsassistenten weitergeleitet.

Mit Hilfe des Assistenten kannst du die für dich korrekte Kategorie-ID herausfinden. Für jede deiner Kategorien kannst du hier Browse-Nodes hinterlegen und die Eingabe mit einem Klick auf das Zahnrad bestätigen. Auch wenn du hier zwei Browse-Nodes eintragen kannst, übergeben wir für Kategorien in denen nur eine Browse-Node von Amazon erlaubt ist, eine Browse-Node.

Wenn wir unsere Reise fortsetzen, kommen wir zu dem Thema, das für dich wortwörtlich Gold wert ist. Verkaufspreise! Mit plentymarkets können Verkäufer für jede Verkaufsplattform unterschiedliche Preise anlegen. Mit anderen Worten, dein Artikel kann zu einem Preis in deinem WebShop verkauft werden, bei Amazon verfügt der selbe Artikel aber über einen anderen Preis.

In plentymarkets erstellst du ganz einfach einen neuen Verkaufspreis oder erweiterst einen bestehenden Verkaufspreis um die Herkunft Amazon. Dazu setzt du hier einfach einen Haken bei der Amazon-Plattform und bei dem Amazon-Account, für den der Preis gültig sein soll. Kleine Anmerkung - Du solltest bei
dem Namen des Verkaufspreises darauf achten, dass du diesen in der Sprache der entsprechenden
Amazon-Plattform hinterlegst. Willst du also beispielsweise auf Amazon.co.uk verkaufen musst du den
Namen zwingend in Englisch hinterlegt haben!
Save Natürlich klickst du anschließend den Speichern-Button.
Grafik 05 - Shirt bei Amazon in
Safari-Gelb. Shirt hat einer
Drop-Down Menü, wo mehrere
Farben zur Auswahl stehen
Link einblenden - Artikel - Attribute
und Varianten

Es gibt wahrscheinlich auch einige Artikel, die Du in mehreren Größen oder Farben verkaufen
möchtest.

Grafik 05 - Kunde nutzt gelbe Filter
und sieht viele gelbe Produkte als
Ergebnis (inkl. Safari-gelbes Shirt)

Auf Amazon werden von den Kunden Suchfilter benutzt, die es auch erlauben, dass sie deine Artikel
finden.
Grafik 05 - Safari-gelbes Shirt wird
hervorgehoben

Dein safari-gelbes T-Shirt soll also bei der Betätigung des gelben Filters auf Amazon angezeigt
werden. Hier kommt die Attributverknüpfung ins Spiel.

Fade to "System > Item > Attributes" Mit anderen Worten, navigiere einfach zu den Attribut-Einstellungen in plentymarkets...
Open attribute Farbe ...und öffne das Attribut, das du mit einem Amazon verbinden möchtest.
Klicke Werte Grundsätzlich wird als Farbe der Wert übergegeben, den du hier im Feld Name hinterlegt hast.
Mouseover Safari-gelb Also in unserem Fall Safari-Gelb...
Grafik 05 - Shirt bei Amazon in
Safari-Gelb. Shirt hat einer
Drop-Down Menü, wo mehrere
Farben zur Auswahl stehen

... Diesen Wert findest du dann innerhalb des Artikels bei Amazon.

Grafik 05 - Kunde nutzt gelbe Filter
und sieht viele gelbe Produkte als
Ergebnis (inkl. Safari-gelbes Shirt)

Aber woher weiß Amazon, dass dein safari-gelb bei einem KLICK auf den Amazon-Filter Gelb
angezeigt werden soll?
Fade back to plenty "Werte" tab In plentymarkets...
Click on "Marktplatzverknüpfung" ...öffnest du dir ganz einfach diesen Tab...
Öffne Amazon ...und Amazon.

Wähle Kategorie Als nächstes wählst du aus diesem Dropdown die entsprechenden Amazon Kategorie...
Enter attribute names gelb
Link einblenden - Amazon Flat File -
Text: Take a look at the Amazon Flat
File to see which combinations are
permitted

...und gibst dann den Namen des entsprechenden Amazonfilters ein. Solltest du nicht wissen, welchen
Werte Amazon hier erlaubt empfiehlt sich ein Blick in das FlatFile der entsprechenden Kategorie.

Save Auch hier klickst du natürlich wieder den Speichern-Button.
Grafik 06 - Product hat ein Schild
wie ein Tramper, z.B. "Next stop
Amazon"

Deine Artikel sehen super aus! Du hast ihnen jede Menge Informationen mitgegeben. Jetzt kannst du
deine Artikel selber auf die Reise schicken...
--
//end::transkript[]
