= billiger.de Asia
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market billiger.de Asia in your plentymarkets system.
:position: 25

On this page, you will find information about the settings you need to carry out in order to set up **billiger.de Asia** in plentymarkets. You will learn how to set up the interface, how to export items to billiger.de and how to define sales prises.

[#100]
== Registering with billiger.de

You need to register with **link:http://info.fruugo.com/merchants/pages/start_selling.asp[billiger.de^]** before setting up billiger.de in plentymarkets.

[#200]
== Setting up billiger.de Asia in plentymarkets

Carry out the following settings in plentymarkets in order to set up the interface to billiger.de Asia.

[.instruction]
Setting up billiger.de Asia:

. Go to **System » Markets »  billiger.de Asia » Settings**.
. Activate the automatic data exchange.
. Enter the user name as received from billiger.de.
. Enter the password as received from billiger.de.
. **Save** the settings.

Connecting to billiger.de Asia allows for the following automatic processes to take place:

* hourly order synchronisation

[#300]
== Setting the item availability

Items have to be available for billuger.de Asia. This is done by linking the item to the property **Delivery to Asia** and in the **<<item/managing-items#, Available>>** tab of an item in the **Item » Edit item** menu. First create the property and link it with the item.

[.instruction]
Creating the property Delivery to Asia:

.  Go to <<omni-channel/multi-channel/billiger-de-asia#2, **System » Item » Properties » Tab: New property**>>.
.  Enter the name (internal).

**Next, you will have to link the special offer to the item in the **Item » Edit item » Open item » Tab: Variation ID » Tab: Properties** menu. Next, activate the item availability as described below.

[.instruction]
Activating the item availability for billiger.de:

. Open the **Item » Edit item » Open item » Tab: Variation ID » Tab: Settings** menu.
. Activate the main variation in the **Availability** section.
. Click on the **Availability** tab.
. Click in the **Markets** section in the selection field. +
→ A list with all available markets will be displayed.
. Activate the option **billiger.de**.
. Activate the option **Web API**.
. Click on **Add**. +
→ The Market will be added.
. **Save** the settings.

The availability for variations can be individually edit in the **Item » Edit item » Open item » Tab: Variation ID » Open variation » Tab: Availability** menu.

[#400]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer billiger.de. This price will be displayed on billiger.de.

[.instruction]
Defining a sales price for billiger.de:

. Open the menu **System » Item » Sales prices » Open sales price » Tab: Settings**.
. Place a checkmark next to the referrer **billiger.de**.
. **Save** the settings.

[#500]
==  Defining SKU manually

Add SKUs manually for specific referrers in the menu <<item/managing-items#170, **Item » Edit item » Open item » Tab: Variation ID » Tab: Settings » Tab: Availability**>> if needed.

[.instruction]
Addding SKU

. Open the **Item » Edit item » Open item » Tab: Variation ID » Tab: Settings** menu.
.  Click on the **Availability** tab.
.  Click in the **SKU** section on **Add**. +
→ The editing window **New SKU** will be displayed.
.  Select the referrer **billiger.de**.
.  Enter the SKU.
.  Click on **Add**. +
→ The SKU will be saved and displayed.

[#600]
== Setting up the item export

This section explains how to transfer your items to billiger.de Asia. Following this, the item export is carried out by the elastic export.

[.instruction]
Setting up the item export:

. Go to **Data » Elastic export**.
. Click on **New export**.
. Carry out the settings as desired. Pay attention to the information given in table 1.
. Carry out further settings for item filters and format settings. Pay attention to the information given in table 5 in the <<basics/data-exchange/exporting-data#60, **Exporting data**>> page of the manual.
. **Save** the settings. +
→ The export format will be given an ID and it will appear in the overview within the **Exports** tab.

.settings for the item export
[cols="1,3"]
|====
|Setting |Explanation

2+|Settings

|**Name**
|Enter a name. The export format will be listed under this name in the overview within the **Exports** tab.

|**Type**
|Select a type from the drop-down menu. Currently, **Item** is the only available option. Further options will be available soon.

|**Format**
|Select the format **BilligerDE** from the drop-down menu.

|**Limit**
|Enter a number. If you want to transfer more than 10,000 data records to billiger.de, then the output file will not be generated again for another 24 hours. This is to save resources.

|**Provisioning**
|Select **URL**.

|**Token, +
URL**
|If you selected the option **URL** under **Provisioning**, then click on **Generate token**. The token will be entered automatically. The URL will be entered automatically if the token was generated under **Token**. Give this URL to billiger.de. in order to export the items.
|====

[IMPORTANT]
.Export information
====
If you change one or more settings, then you will have to transfer the new link to billiger.de.

A maximum of 4000 items will be exported at once. If you export more items, then a second export will automatically be carried out. To display the second export process, set the parameter **&amp;Page** = in the export link to **2**.

Technical data is transferred to billiger.de in the last column of the export file.
====

[#700]
== Automatically sending order confirmations

Set up an **<<basics/automation/event-procedures#, event procedure>>** to automatically send an order confirmation to billiger.de.

[.collapseBox]
.Setting up an event procedure
--
.  Go to **System » Orders » Events**.
.  Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
.  Enter a name.
.  Select the **event** listed in table 2.
. **Save** the settings.
.  Pay attention to the explanations given in table 2 and carry out the settings as desired.
.  Place a check mark next to the option **Active**.
. **Save** the settings.
--
.event procedure for sending automatic order confirmations to billiger.de
[cols="1,3,3"]
|====
| Setting | Option | Selection

|**Event**
|**Order generation: New order**
|

|**Filter 1**
|**Order &gt; Order type**
|**Order**

|**Filter 2**
|**Order &gt; Referrer**
|**billiger.de**

|**Procedure**
|**Order &gt; Send order confirmation to billiger.de**
|
|====

[#800]
== Automatically sending shipping confirmations

Set up an **<<basics/automation/event-procedures#, event procedure>>** to automatically send a shipping confirmation to billiger.de when the outgoing items are booked.

[.collapseBox]
.Setting up an event procedure
--
.  Go to **System » Orders » Events**.
.  Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
.  Enter a name.
.  Select the **event** listed in table 3.
. **Save** the settings.
.  Pay attention to the explanations given in table 3 and carry out the settings as desired.
.  Place a check mark next to the option **Active**.
. **Save** the settings.
--
Setting.event procedure for sending automatic shipping confirmations to billiger.de
[cols="1,3"]
|====
| Option | Selection

|**Event**
|**Order change: Outgoing items booked**
|

|**Filter 1**
|**Order &gt; Order type**
|**Order**

|**Filter 2**
|**Order &gt; Referrer**
|**billiger.de**

|**Procedure**
|**Shipping &gt; Send shipping confirmation to billieger.de**
|
|====

[#1000]
== Viewing the API log

The menu **Data » API log » Tab: API log** contains a history of processes that run via the billiger.de interface. The **billiger.de Asia** format is available for billiger.de Asia.

[.instruction]
Viewing the API log:

.  Go to **Data » API log**.
.  Select the format **billiger.de Asia** from the drop-down menu **Process**.
.  Select a Date if you only want to see entries for a specific day.
.  Select the number of results per page.
.  Click on **Search** to display the results.**
