= Check24
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market Check24 in your plentymarkets system.
:position: 35

On this page, you will find information about the settings you need to carry out in order to set up the market Check24 in plentymarkets. You will learn how to set up the interface, how to export items to Allyouneed and how to define sales prises.

[#100]
== Registering with Check24

You need to register with *link:http://info.fruugo.com/merchants/pages/start_selling.asp[Check24^]* before setting up Check24 in plentymarkets.

[#200]
== Setting up Check24 in plentymarkets

Carry out the following settings in plentymarkets in order to set up the interface to Check24.

[.instruction]
Setting up Check24:

. Go to *System » Markets »  Check24*.
. Activte the automatic data exchange.
. Enter for the user name the FTP partner login.
. Enter the FTP access password.
. *Save* the settings.

Connecting to this market allows for the following automatic processes to take place:

* hourly order synchronisation

[#300]
=== Setting the item availability

Items have to be available for Check24. This is done in the *Availability* tab of an item within the *<<item/managing-items#, Item » Edit item » Tab: Variation ID>>* menu.

[.instruction]
Activating the item availability for Check24:

. Open the *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings* menu.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the *Markets* section in the selection field.  +
→ A list with all available markets will be displayed.
. Activate the option *Check24*.
. Activate the option *Web API*.
. Click on *Add*. +
→ The Market will be added.
. *Save* the settings.

The availability for variations can be individually edit in the *Item » Edit item » Open item » Tab: Variation ID » Open variation » Tab: Availability* menu.

[#400]
===  Defining SKUs

Add SKUs for referrers in the menu <<item/managing-items#170, *Item » Edit item » Open item » Tab: Variation ID*>>.

[.instruction]
Addding SKU

. Open the *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings* menu.
.  Click on the *Availability* tab.
.  Click in the *SKU* section on *Add*. +
→ The editing window *New SKU* will be displayed.
.  Select the referrer *Check24*.
.  Select the corresponding market account.
.  Enter the SKU.
.  Click on *Add*. +
→ The SKU will be saved and displayed.

[#500]
=== Setting up the item export

This section explains how to transfer your items to Check24. The item export for Check24 is carried out by the elastic export. Therefore, the plugins *ElasticExport* and *ElasticExportCheck24DE* have to be already installed. Create the data format Check24DE first and then transfer the URL to Check24.

[.instruction]
Setting up the item export:

. Go to *Data » Elastic export*.
. Click on *New export*.
. Carry out the settings as desired. Pay attention to the information given in table 1.
. Carry out further settings for item filters and format settings. Pay attention to the information given in table 5 in the <<basics/data-exchange/exporting-data#60, *Exporting data*>> page of the manual.
. *Save* the settings. +
→ The export format will be given an ID and it will appear in the overview within the *Exports* tab.

.settings for the item export
[cols="a,a"]
|====
|Setting |Explanation

2+|Settings

|*Name*
|Enter a name. The export format will be listed under this name in the overview within the *Exports* tab.

|*Type*
|Select a type from the drop-down menu. Currently, *Item* is the only available option. Further options will be available soon.

|*Format*
|Select the format *Check24DE* from the dropdown menu.

|*Limit*
|Enter a number. If you want to transfer more than 10,000 data records to Check24, then the output file will not be generated again for another 24 hours. This is to save resources.

|*Provisioning*
|Select *URL*.

|*Token, +
URL*
|If you selected the option *URL* under *Provisioning*, then click on *Generate token*. The token will be entered automatically. The URL will be entered automatically if the token was generated under *Token*. Give this URL to Check24.de in order to export the items.
|====

[IMPORTANT]
.Export information
====
If you change one or more settings, then you will have to transfer the new link to Check24.

A maximum of 4000 items will be exported at once. If you export more items, then a second export will automatically be carried out. To display the second export process, set the parameter *&amp;Page* = in the export link to *2*.

Technical data is transferred to Check24 in the last column of the export file.
====

[#600]
=== Defining a sales price

Proceed as described below to define a sales price for the order referrer Check24. This price will be shown on Check 24.

[.instruction]
Defining a sales price for Check24:

. Open the menu *System » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a checkmark next to the referrer *Check24*.
. *Save* the settings.

[#950]
== Order import

After the order import the order is set to status *[5]*cleared for shipping* . The invoice address is always Check24. The customer's address is the delivery address.

[#1000]
== Retrieving the API log

The menu *Data » API log » Tab: API log* contains a history of processes that run via the Check24 interface. The *Check24OrderImportAdapter* format is available for Check24.

[.instruction]
Viewing the API log:

.  Go to *Data » API log*.
.  Select the *Check24OrderImportAdapter* format from the *Process* drop-down menu.
.  Select a Date if you only want to see entries for a specific day.
.  Select the number of results per page.
.  Click on *Search* to display the results.
