= Flubit
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market Flubit in your plentymarkets system.
:position: 60

**link:https://www.flubit.com/About[Flubit^]** is an online market that is only available in the United Kingdom and that does not take a commission from sellers.

[#10]
== Registering with Flubit

First, register as a seller on **link:https://www.weflubit.com/start-selling[WeFlubit^]**, the central Flubit interface for sellers.

[#20]
== Setting up Flubit in plentymarkets

Set up Flubit in plentymarkets to offer items on Flubit. You need your access data. This includes your API key and security token. You will receive this data from Flubit.

[.instruction]
Setting up Flubit in plentymarkets:

. Go to **System » Markets » Flubit » Settings**.
. Carry out the settings as desired. Pay attention to the information given in table 1.
. **Save** the settings.

[cols="a,a"]
|====
|Setting |Explanation

|**Activate the automatic data exchange**
|If the data exchange is activated, then there will be a daily item export (at night), an hourly stock synchronisation and an hourly order import.

|**API key**
|Enter the API key (Key) that you received from Flubit.

|**Security token**
|Enter the Security token (Secret) that you received from Flubit.

|**Environment**
|Select **Live** or **Sandbox**. +
If **Live** is selected, the items will be listed live. The option **Sandbox** is a test mode.

|**Item name**
|Select **Name 1**, **Name 2** or **Name 3**. This item name will be transferred to Flubit.

|**Item description**
|Choose between **Standard description**, **Short description** or **Technical data**.  +
This item description will be transferred to Flubit. The item description has to be available in **<<omni-channel/online-store/setting-up-clients/multilingual-online-store#, English>>**. Otherwise the item will not be exported.

|**Warehouse selection**
|Select the stock quantity for the hourly synchronisation and the daily item export. Select one of the following options:  +
**Stock quantity of sales warehouse with largest stock** +
**Stock quantity of item's main warehouse** +
**Stock quantity of all warehouses**
|====

__Table 1: basic settings for the market Flubit__

Connecting to this market allows for the following automatic processes to take place:

* daily item export
* hourly stock synchronisation
* hourly order import
* Automatically create a new customer data record during the order import. This is assuming no customer data record was already saved in the database

[IMPORTANT]
.Language
====
Attributes have to be saved in English in order for items to be exported to Flubit.
====

[#30]
== Setting the item availability

Items have to be available for Flubit. This is done in the **Availability** tab of an item within the **<<item/managing-items#40, Item » Edit item » Tab: Variation ID>>** menu.

[.instruction]
Setting the item availability for Flubit:

. Open the **Item » Edit item » Open item » Tab: Variation ID » Tab: Settings** menu.
. Activate the main variation in the **Availability** section.
. Click on the **Availability** tab.
. Click in the **Markets** section in the selection field.  +
→ A list with all available markets will be displayed.
. Activate the option **Flubit**.
. Activate the option Web-API.
. Click on **Add**. +
→ The Market will be added.
. **Save** the settings.  +
→ The item is available on Flubit.

The availability for variations can be individually edit in the **Item » Edit item » Open item » Tab: Variation ID » Open variation » Tab: Availability** menu.

[IMPORTANT]
.Mandatory entries for the item export
====
Items must meet the following criteria before they can be exported to Flubit:

* The item price is greater than zero
* The item has positive stock
* The item description is available in **<<omni-channel/online-store/setting-up-clients/multilingual-online-store#, English>>**.
* The item is visible
* The item has an image
* The item number is transferred +
→ If the MPN is transferred as the item number, then the brand name or manufacturer needs to be specified as well.

Items will not be exported if these entries are missing.
====

[#35]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Flubit. This price will be displayed on Flubit.

[.instruction]
Defining a sales price for Flubit:

. Open the menu **System » Item » Sales prices » Open sales price » Tab: Settings**.
. Place a checkmark next to the referrer **Flubit**.
. **Save** the settings.

[#40]
== Automatically sending shipping confirmations

Set up an **<<basics/automation/event-procedures#, event procedure>>** to automatically send shipping confirmations to Flubit when the outgoing items are booked.

[.collapseBox]
.Setting up an event procedure
--
.  Go to **System » Orders » Events**.
.  Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
.  Enter name.
.  Select the **event** listed in table 2.
. **Save** the settings.
.  Pay attention to the explanations given in table 2 and carry out the settings as desired.
.  Place a check mark next to the option **Active**.
. **Save** the settings.
--
[cols="a,a,a"]
|====
|Setting |Option |Selection

|**Event**
|**Order change: Outgoing items booked**
|

|**Filter 1**
|**Order &gt; Order type**
|**Order**

|**Filter 2**
|**Order &gt; Referrer**
|**Flubit**

|**Procedure**
|**Order &gt; Send shipping confirmation to Flubit**
|
|====

__Table 2: event procedure for sending automatic shipping confirmations to Flubit__

[#50]
== Automatically sending cancellations

Set up an **<<basics/automation/event-procedures#, event procedure>>** to automatically inform Flubit of cancellations. Whenever you are dealing with cancellations, you need to send Flubit a reason for the cancellation. Go to **<<order-processing/orders/managing-sales-orders#order-status, System » Orders » Order status>>** and create additional order statuses as needed. The following cancellation reasons can be transferred to Flubit:

* Item not in stock
* Item discontinued
* Invalid delivery address
* Customer cancellation
* Legislation restriction
* Other

[.collapseBox]
.Setting up an event procedure
--
.  Go to **System » Orders » Events**.
.  Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
.  Enter name.
.  Select the **event** listed in table 3.
. **Save** the settings.
.  Pay attention to the explanations given in table 3 and carry out the settings as desired.
.  Place a check mark next to the option **Active**.
. **Save** the settings.
--
[cols="a,a,a"]
|====
|Setting |Option |Selection

|**Event**
|**Status change: [8.1] Cancelled by customer**
|

|**Filter 1**
|**Order &gt; Order type**
|**Order**

|**Filter 2**
|**Order &gt; Referrer**
|**Flubit**

|**Procedure**
|**Order &gt; Send cancellation to Flubit**
|**Customer cancellation**
|====

__Table 3: event procedure for sending automatic cancellations to Flubit__

[#60]
== Automatically sending returns

Set up an **<<basics/automation/event-procedures#, event procedure>>** to automatically inform Flubit about returns.

[.collapseBox]
.Setting up an event procedure
--
.  Go to **System » Orders » Events**.
.  Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
.  Enter name.
.  Select the **event** listed in table 4.
. **Save** the settings.
.  Pay attention to the explanations given in table 4 and carry out the settings as desired.
.  Place a check mark next to the option **Active**.
. **Save** the settings.
--
[cols="a,a,a"]
|====
|Setting |Option |Selection

|**Event**
|**Order generation: New return**
|

|**Filter 1**
|**Order &gt; Order type**
|**Return**

|**Filter 2**
|**Order &gt; Referrer**
|**Flubit**

|**Procedure**
|**Order &gt; Send return to Flubit**
|
|====

__Table 4: event procedure for sending automatic returns to Flubit__

[#70]
== Viewing the API log

The menu **<<basics/data-exchange/api-log#, Data exchange » API log>>**, tab **Flubit** contains a history of processes that run via the Flubit interface. The following formats are available for Flubit:

* **FlubitOrderImport** (order import)
* **FlubitOrderCancel** (cancellations)
* **FlubitOrderDispatch** (shipping confirmation, refund)
* **FlubitProductsFeed** (data export)

[.instruction]
Viewing the API log:

. Go to **Data exchange » API log**.
. Select a format from the drop-down menu **Process**.
. Select a **Date** if you only want to see entries for a specific day.
. Click on **Search** to carry out the search. +
→ The processes will be displayed.
. Click on the folder in the **Process** column.  +
→ The **Flubit** tab will open and error messages will be displayed for this process.
