= grosshandel.eu
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market grosshandel.eu in your plentymarkets system.
:position: 90

link:http://www.grosshandel.eu/[**grosshandel.eu**, window="_blank"] is a pure B2B portal, which means that both sellers and buyers have to be in possession of a valid traders license. You can use this market to buy and sell consumer goods and brand-name items (source: grosshandel.eu).

[#10]
== Registering with grosshandel.eu

You have to link:http://www.grosshandel.eu/registrierung-verkaeufer.php[**register**, window="_blank"] in the grosshandel.eu seller portal before you can set up grosshandel.eu in your plentymarkets system.

[#20]
== Creating an user account

Your plentymarkets system will be connected to grosshandel.eu via the SOAP API. In order for it to have access, the market requires its own user account with access rights to the API in your system. Go to **Settings » Basic settings » User » Accounts** and create a new user account for grosshandel.eu with the user class **API**. Additionally, activate the call **GetCategoryMappingForMarket**. This call ensures that the market will later be able to retrieve your category links.

[.instruction]
Creating an user account for grosshandel.eu:

. Go to **Settings » Basic settings » User » Accounts**.
. Click on **New**. +
→ The **Create new user** window will open.
. Enter the data.
. Select the user class **API**.
. **Save** the settings. +
→ The user will be created.
. Select the user from the list. +
→ The editing window will open.
. Click on the tab **Right » API**.
. Expand the **Item** area.
. Activate the **GetCategoryMappingForMarket** call.
. **Save** the settings.

[#30]
== Procuring data

grosshandel.eu needs to have the following data from you in order to connect to your plentymarkets system:

* The URL for the SOAP API WSDL. +
→ This URL can be found in the **<<basics/data-exchange/api-data#, Settings » Basic settings » API » Data  >>** menu under **SOAP WSDL**.
* The user name and password for the user account that you created for grosshandel.eu
* Your login details for the grosshandel.eu seller portal.

[#40]
== Setting the item availability

Items have to be available for grosshandel.eu. This is done in the **Availability** tab of an item within the link::/[**Item » Edit item » Tab: Variation ID**] menu.

[.instruction]
Setting the item availability for grosshandel.eu:

. Open the **Item » Edit item » Open item » Tab: Variation ID » Tab: Settings** menu.
. Activate the main variation in the **Availability** section.
. Click on the **Availability** tab.
. Click in the **Markets** section in the selection field.  +
→ A list with all available markets will be displayed.
. Activate the option **grosshandel.eu**.
. Activate the option Web-API.
. Click on **Add**. +
→ The Market will be added.
. **Save** the settings.  +
→ The item is available on grosshandel.eu.

The availability for variations can be individually edit in the **Item » Edit item » Open item » Tab: Variation ID » Open variation » Tab: Availability** menu.

[#50]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer grosshandel.eu. This price will be displayed on grosshandel.eu.

[.instruction]
Defining a sales price for grosshandel.eu:

. Open the menu **Settings » Item » Sales price » Open sales price » Tab: Settings**.
. Place a checkmark next to the referrer **grosshandel.eu**.
. **Save** the settings.

[#60]
== Linking categories

Link your store categories to the grosshandel.eu categories in order to display your items in these categories. Further items from the linked category will be assigned automatically.

[.instruction]
Linking categories:

. Go to **Settings » Markets » grosshandel.eu**.
. Expand the category which you want to link to a grosshandel.eu category.
. Select a main category for grosshandel.eu from the drop-down menu. +
→ A window with subcategories will open.
. Select the appropriate grosshandel.eu category from the subcategories that appear. +
→ Once the lowest category level has been reached, the category path will be displayed in the field **Category**.
. Click on **Accept**. +
→ The category window will close.
. **Save** the settings.

[IMPORTANT]
.Link to the lowest category level
====
Always select a path to the lowest level. Otherwise, the item will not be linked.
====

[#70]
== Linking multiple subcategories

Use the option **Apply the same selection to the sub-categories** to apply the same grosshandel.eu category path for all of the subcategories that are listed within a category. This is useful if you want to use the same link for the subcategories. If needed, you can use the drop-down menu to manually change individual subcategories.

[.instruction]
Linking multiple subcategories:

. Go to **Settings » Markets » grosshandel.eu**.
. Expand the category which you want to link.
. Select a main category for grosshandel.eu from the drop-down menu in the line **Apply the same selection to the sub-categories**. +
→ A window with subcategories will open.
. Select the appropriate category path from the subcategories that appear. +
→ Once the lowest category level has been reached, the category path will be displayed in the field **Category**.
. Click on **Accept**. +
→ The category window will close.
. Click on **Select all** in the line **Apply the same selection to the subcategories**.
. Click on **Reload**. +
→ The category path will be applied to all of the subcategories.
. **Save** the settings.

