= La Redoute
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market La Redoute in your plentymarkets system.
:position: 140

plentymarkets can be connected to La Redoute, the French market leader for mail order business. Learn how to set up the interface to La Redoute and which conditions online sellers need to fulfil in order to sell items on La Redoute.

[#10]
== Registering with La Redoute

La Redoute places conditions on online sellers who wants to offer their items on this market:

. They need to make their catalogue of items completely available in French.
. They need to be able to answer their customers' emails in French.
. They also need to be able to ship their items to France.

You need to register with La Redoute before setting up La Redoute in your plentymarkets system. This is done in two steps. First, get in contact with the La Redoute Business Development Team:

[cols="a,a"]
|====
|Contact person |Email address

|**Frédéric Maus** +
Head of Business development
|link:mailto:fmaus@redoute.fr[fmaus@redoute.fr]

|**Joseph Farhat** +
Manager Business development - Fashion &amp; accessories
|link:mailto:jfarhat@redoute.fr[jfarhat@redoute.fr]

|**Carlos Cantoni** +
Manager Business development - Home &amp; electronics
|link:mailto:ccantoni@redoute.fr[ccantoni@redoute.fr]
|====

__Table 1: contacts at La Redoute__

Second, you will receive an Excel file from La Redoute, which you fill out with information about your company and send back. Send the following documents along with the file:

* A copy of your information from the commercial register
* A notification from your bank that includes your account information (with your SWIFT and IBAN)

Alternatively, fill out the French link:http://www.laredoute.fr/espace-devenir-vendeur-marketplace.aspx[**contact form**, window="_blank"] on the La Redoute website. Once you have sent all of the necessary information to La Redoute, you will receive an email from La Redoute that contains the CallerID and the CatalogSupplierName. You can now enter these IDs into your plentymarkets system.

[#20]
== Setting up La Redoute in plentymarkets

Carry out the following basic settings to connect La Redoute to your plentymarkets system.

[.instruction]
Setting up La Redoute in plentymarkets:

. Go to **Settings » Markets » La Redoute » Basic settings**.
. Pay attention to the explanations given in table 2 and carry out the settings as desired.
. **Save** the settings.

[cols="a,a"]
|====
|Setting |Explanation

|**Interface mode**
|Select the interface mode.  +
**Test mode ON** = Select while you configure settings and prepare the interface and items.  +
**Live mode ON** = Select once La Redoute has confirmed that all of the tests have been completed.

2+|Sales partner information

|**HubID; +
ESystem**
|This ID is fixed and cannot be changed.

|**CallerID/SellerID; +
EUserID**
|Enter the ID that you received from La Redoute.

|**CatalogSupplierName**
|Enter the name that you received from La Redoute.

2+|Item settings

|**Item name**
|Select which field should be transferred to La Redoute as the item name. The name has to be in French. Otherwise the item will not be exported.

|**Item preview text**
|Select which field should be transferred to La Redoute as the item preview text. The item preview text has to be in French. Otherwise the item will not be exported.

|**Item description**
|Select which field should be transferred to La Redoute as the item description. The item description has to be in French. Otherwise the item will not be exported.

|**Technical data**
|Select if this data should be transferred or not. The technical data has to be in French. Otherwise the item will not be exported.

|**Item EAN**
|Select which EAN should be transferred as the item EAN.

|**Variation EAN**
|Select which EAN should be transferred as the variation EAN.

|**Preparation for shipping**
|Enter the number of days that you need to pack the order and hand it off to the shipping service provider.

|**Minimum additional delay in delivery**
|Enter duration in days. This number will be added to your items' normal minimum delivery time.

|**Maximum for additional delay in delivery**
|Enter duration in days. This will be added to your items' normal maximum delivery time.

|**Overwrite shipping costs**
|The shipping costs entered here will be transferred to La Redoute instead of the shipping costs that are saved for an item.

2+|Order settings

|**Temporary customer ID**
|Create a customer for La Redoute and enter the customer's ID here (see chapter 11).

|**Book incoming payment**
|Select whether orders from La Redoute should be marked as **paid** or **open** when they are imported. This decision has to be made since customers pay La Redoute and La Redoute pays you afterwards.
|====

__Table 2: basic settings for the market La Redoute__

Connecting to this market allows for the following automatic processes to take place:

* hourly order import
* daily item export
* stock synchronisation every two hours

[#30]
== Translating item information

Since La Redoute is a French market, the **link::/[items]** that you sell there need to be available in French as well. Another requirement for selling your items on La Redoute is that the item description has to be in French. Furthermore, all of the attributes and properties that are linked with La Redoute need to be in French. The item also needs to have an EAN and item images.

[.instruction]
Creating a French language version of an existing item:

. Go to **Item » Edit item**.
. Open the item.
. Click on the **Texts** tab.
. Select **fr** from the **Open language** drop-down menu.
. Enter a French name for this item in the field **Name 1**.
. Enter additional texts (description, technical data etc.). +
→ The description is mandatory for La Redoute.
. **Save** the settings.

[#40]
== Setting the item availability

Items have to be available for La Redoute. This is done in the **Availability** tab of an item within the link::/[**Item » Edit item » Tab: Variation ID**] menu.

[.instruction]
Setting the item availability for La Redoute:

. Open the **Item » Edit item » Open item » Tab: Variation ID » Tab: Settings** menu.
. Activate the main variation in the **Availability** section.
. Click on the **Availability** tab.
. Click in the **Markets** section in the selection field.  +
→ A list with all available markets will be displayed.
. Activate the option **La Redoute**.
. Activate the option **Web API**.
. Click on **Add**. +
→ The Market will be added.
. **Save** the settings. +
→ The item is available on La Redoute.

The availability for variations can be individually edit in the **Item » Edit item » Open item » Tab: Variation ID » Open variation » Tab: Availability** menu.

[#50]
== Defining a sales price

i Proceed as described below to define a sales price for the order referrer La Redoute. This price will be displayed on La Redoute.

[.instruction]
Defining a sales price for La Redoute:

. Open the menu **Settings » Item » Sales price » Open sales price » Tab: Settings**.
. Place a checkmark next to the referrer **La Redoute**.
. **Save** the settings.

[#60]
== Linking properties

Link your link::/[**properties**] with the La Redoute properties. Properties have to be created in French for this. You will receive an XLS file from La Redoute, which contains the properties. Use this file to create a CSV file for importing properties.

[IMPORTANT]
.Create the necessary links
====
You need to create different links in order for your items to be displayed on the market La Redoute. You are required to link **properties**, **categories**, **attributes and values** and **manufacturers**.
====

[.instruction]
Linking properties:

. Go to **Settings » Markets » La Redoute » Item property import**.
. Click on **Browse...**.
. Select the CSV file that contains the properties.
. Select the field separator.
. **Save** the settings. +
→ The file will be uploaded.
. Go to **Settings » Item » Properties**.
. Expand a property.
. Select **fr** for French from the **Language** drop-down menu.
. Enter the French name that you want to use for this property into the **Name** field.
. Select the La Redoute property from the drop-down menu in the **La Redoute property** field.
. **Save** the settings.

[#70]
== Linking categories

You have to create category links in order for your items to be displayed in the correct categories on La Redoute.

[.instruction]
Linking categories:

. Go to **Settings » Markets » La Redoute » Category link**.
. In the column **La Redoute category ID**, enter the category ID that best matches your online store category. +
→ The La Redoute category ID can be found in the category files that you received from La Redoute.
. **Save** the settings.

[#80]
== Linking attributes and attribute values

link::/[**Attributes**] also have to be linked before your items can be transferred to La Redoute. An item will only be displayed on La Redoute if all of its attributes were linked.

[.instruction]
Linking attributes and attribute values:

. Go to **Settings » Item » Attributes**. +
→ The overview of all attributes used in your catalogue will open.
. Expand an attribute.
. Click on the **Market variation** tab.
. Select **La Redoute** from the **Market** drop-down menu. +
→ A drop-down menu will open in the **Settings** area.
. Select the appropriate La Redoute attribute from the drop-down menu.
. Select the appropriate attribute values for La Redoute from the **Market variation** area.
. **Save** the settings.
. Repeat this process for all remaining attributes.

[#90]
== Linking manufacturers

As a final step, link your link::/[**manufacturers**]. You will receive a file from La Redoute, which contains the manufacturer IDs.

[.instruction]
Linking manufacturers:

. Go to **Settings » Item » Manufacturers**.
. Open a manufacturer.
. Enter the ID into the **La Redoute ID** field. +
→ You can find the La Redoute manufacturer ID in the file that you received from La Redoute.

[#100]
== Activating the payment method

The payment method **La Redoute Payment** is for orders that are imported into your plentymarkets system from **link:http://www.laredoute.com/[La Redoute, window="_blank"]**.

[.instruction]
Activating the payment method La Redoute Payment:

. Go to **Settings » Orders » Payment » Payment methods**.
. Place a check mark next to the setting **Also show inactive**.
. Open the folder **International**.
. Click on **La Redoute Payment**.  +
→ The **Settings** tab will open.
. Carry out the settings as desired. Pay attention to the information given in table 3.
. Place a check mark next to the option **Active**.
. **Save** the settings.

[cols="a,a"]
|====
|Setting |Explanation

|**Language**
|The following options are saved for the language selected: **Name**, **Info page**, **Info page (internal)**, **Logo** and **Upload logo**. This makes it possible to enter values for these options in various languages. The values for a language will be activated as soon as a buyer selects the language in the online store.

|**Name**
|Enter the name that should be displayed in the online store and on invoices etc.

|**Info page**
|Select a category page of the type **content** or enter the URL of a website to provide information about the payment method.

|**Info page (external)**
|If you selected the option **Info page (external)** under **Info page**, then enter the URL of the info page here.

|**Countries of delivery**
|Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely configured.

|**Logo**
|Select one of the following options for displaying the logo: +
**Show standard logo** = The logo that is saved in plentymarkets for this payment method will be displayed.  +
**Do not show a logo** = The logo that is saved in plentymarkets for this payment method will not be displayed. +
**Show upload logo** = The options **Logo view** and **Upload logo** will be displayed.

|**Logo view**
|If **Show upload logo** was selected from the **Logo** drop-down menu, then the logo that was uploaded will be displayed here.

|**Upload logo**
|If **Show upload logo** was selected from the **Logo** drop-down menu, then you will be able to upload an external logo here. +
Click on **Upload files** and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|**Priority**
|Select the priority for displaying the payment method in the online store.

|**Costs: Flat rate or percentage**
|If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. **Important:** Do not enter a value into both fields.  +
For further information, refer to the **<<basics/statistics#, Statistics  >>** and **<<basics/statistics/general-statistics/item/tops-flops#, Tops/Flops  >>** pages of the manual. For an example for flat rate and percentage costs, refer to the **<<omni-channel/multi-channel/laredoute#20, Basic settings >>** page of the manual.
|====

__Table 3: settings of the payment method__

[TIP]
.Permitting the payment method in customer classes
====
Go to **Settings » Customers » Customer classes** to activate or deactivate the **Permitted payment methods**.  +
For further information, refer to the **<<omni-channel/multi-channel/laredoute#40, Payment methods and customer classes >>** chapter of the manual.
====

For further information, refer to the **link::/[Payment methods]** page of the manual.

[#110]
== Creating a temporary customer

At first, orders will be imported into your system without any customer data. The actual customer data will be transmitted from La Redoute once your plentymarkets system has confirmed the order. Therefore, you have to create a customer in your system for La Redoute. Enter this customer's ID into the **Temporary customer ID** field.

[.instruction]
Creating a new customer:

. Go to link::/[**Customers » Edit customers**].
. Click on **New**.
. Enter at least a name for the temporary customer.
. **Save** the settings.
. Click on the **Search** tab.
. Search for the customer.
. Note the **Customer ID**.
. Go to **Settings » Markets » La Redoute » Basic settings**.
. Enter the La Redoute customer ID into the **Temporary customer ID** field.
. **Save** the settings.

[#120]
== Automatically sending shipping confirmations

Set up an **<<basics/automation/event-procedures#, event procedure  >>** to automatically send shipping confirmations to La Redoute. The shipping confirmation is automatically sent to La Redoute as soon as the order status changes to **[7] Outgoing items booked**. La Redoute automatically informs the purchaser of the shipment.

[.collapseBox]
.Setting up an event procedure
--
.  Go to **Settings » Orders » Event procedures**.
.  Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
.  Enter name.
.  Select the **event** listed in table 4.
. **Save** the settings.
.  Pay attention to the explanations given in table 4 and carry out the settings as desired.
.  Place a check mark next to the option **Active**.
. **Save** the settings.
--
[cols="a,a,a"]
|====
|Setting |Option |Selection

|**Event**
|**Order change &gt; Outgoing items booked**
|

|**Filter 1**
|**Order &gt; Order type**
|**Order**

|**Filter 2**
|**Order &gt; Referrer**
|**La Redoute**

|**Procedure**
|**Shipping &gt; Send shipping confirmation to La Redoute**
|
|====

__Table 4: event procedure for sending automatic shipping confirmations to La Redoute__

[#130]
== Automatically sending returns

Set up an **<<basics/automation/event-procedures#, event procedure  >>** to automatically send returns to La Redoute.

[.collapseBox]
.Setting up an event procedure
--
.  Go to **Settings » Orders » Event procedures**.
.  Click on **Add event procedure**. +
→ The **Create new event procedure** window will open.
.  Enter name.
.  Select the **event** listed in table 5.
. **Save** the settings.
.  Pay attention to the explanations given in table 5 and carry out the settings as desired.
.  Place a check mark next to the option **Active**.
. **Save** the settings.
--
[cols="a,a,a"]
|====
|Setting |Option |Selection

|**Event**
|**Order generation &gt; New return (by customer)**
|

|**Filter 1**
|**Order &gt; Order type**
|**Return**

|**Filter 2**
|**Order &gt; Referrer**
|**La Redoute**

|**Procedure**
|**Return &gt; Send return to La Redoute**
|
|====

__Table 5: event procedure for sending automatic returns to La Redoute__

[#140]
== Reporting cancellations

Cancellations cannot be transferred to La Redoute in the strict sense of the word. If you want to cancel an order, e.g. because you have removed the item from your portfolio, then you have to create a return.

plentymarkets automatically accepts new orders from La Redoute. This allows data to be imported into your plentymarkets system in general. One consequence of accepting orders is that they cannot be cancelled afterwards. Therefore, book the outgoing items first and then create a return directly afterwards.

[TIP]
.Tip: Email to customers
====
If you cancel an order, make sure to send an email to the customer and inform him or her about the item, e.g. explaining that the item is no longer part of your product range.
====

[#150]
== Deleting items

If you want to irreversibly delete an link::/[**item**] offered on La Redoute from your plentymarkets system, then you will first need to delete this item from the La Redoute catalogue.

[.instruction]
Deleting an item from the La Redoute catalogue:

. Go to **Item » Edit item**.
. Open the item that you want to delete.
. Click on the **Available** tab.
. Deactivate the option **La Redoute**.
. **Save** the settings. +
→ You have to wait 24 hours for the item to be removed from the La Redoute catalogue.

[WARNING]
.Wait before deleting items
====
Do not delete an item before the 24 hours are over. Also, do not delete an item in plentymarkets first as you will not be able to delete the item in La Redoute once it was deleted from plentymarkets.
====

[.instruction]
Deleting items:

. Go to **Item » Edit item**.
. Find the item that you want to delete and click on **Delete**. +
→ The item will be removed from your plentymarkets system.

[#160]
==  Viewing the API log

The menu **Data exchange » API log » Tab: API log** contains a history of processes that run via the La Redoute interface. The **LaRedoute** format is available for La Redoute.

[.instruction]
Viewing the API log:

.  Go to **Data exchange » API log**.
.  Select the **LaRedoute** format from the **Process** drop-down menu.
.  Select a date if you only want to see entries for a specific day.
.  Select the number of results per page.
.  Click on **Search** to display the results.

