= Plus.de and GartenXXL.de
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Plus.de, GartenXXL.de, Plus, GartenXXL, Market, Marketplace
:description: Multi-Channel in plentymarkets: Set up the interface to the markets Plus.de and GartenXXL.de in your plentymarkets system.
:position: 220

link:https://www.plus.de/[Plus.de^] offers an extensive portfolio of gardening and DIY supplies, living room and bedroom furniture, sports and wellness products, household items, wine, as well as multimedia and entertainment electronics. Since April 2014, the e-commerce activities of Plus Online GmbH are consolidated under the new corporate name Tengelmann E-Stores GmbH.

link:http://www.gartenxxl.de/[GartenXXL^] is a brand belonging to the Tengelmann E-Stores GmbH. The GartenXXL website offers brand-name equipment and outdoor furniture as well as tips and tricks for garden maintenance.

[#100]
== Registering with Plus.de

Before setting up Plus.de in your plentymarkets system, you have to register with link:https://www.plus.de/partnerprogramm[Plus.de^]. Contacts for the registration: +
Katrin.Beer@netto-online.de +
Christian.Mertens@netto-online.de

[#200]
== Setting up Plus.de in plentymarkets

You have to set up Plus.de in plentymarkets before you can sell items on the market. To do so, proceed as follows:

[.instruction]
Setting up Plus.de in plentymarkets:

. Go to *System » Markets » Plus.de*. +
→ The *Settings* tab opens.
. Carry out the settings. Pay attention to the explanations given in <<settings-plus>>.
. *Save* the settings.

[[settings-plus]]
.Settings for the market Plus.de
[cols="1,3"]
|====
|Setting |Explanation

|*Activate the automatic data exchange*
|Select *Yes* to activate the automatic data exchange or *No* to deactivate it. +
If you select *Yes,* the stock synchronisation, the item export, and the order import are activated.

|*Activate item export*
|Select *Yes* to activate the automatic item export or *No* to deactivate it.

|*Activate the stock update*
|Select *Yes* to activate the automatic stock update or *No* to deactivate it.

2+|Sales partner information

|*Supplier number*
|Enter the supplier number that you have received from Plus.de.

2+|Item settings

|*Item name*
|Select item name that is transferred to Plus.de.

|*Variation name*
|Select the variation name that is transferred to Plus.de. +
*Variation name* = The variation name is transferred. +
*Add attribute values of the variation* = The attribute values are added to the variation name, separated by space (example: “T-Shirt red XL”)

|*Short item description*
|Select the short item description that is transferred to Plus.de.

|*Item description*
|Select the item description that is transferred to Plus.de.

|*Image position for energy label*
|Enter the image's position number if the energy label was not uploaded to the energy label property but saved as an item image instead. Refer to the <<Creating the property energy efficiency, Creating the property energy efficiency>> chapter for details on energy labels.

|*Quantity for items that are not limited to the stock*
|For items that have the setting *no limitation*, the maximum amount of the real stock and the quantity defined here is transferred. +
Example: Setting 0, net stock 8. plentymarkets transfers 8. +
Items with the setting *Limited to net stock* are not taken into consideration.

|*Quantity for items not limited to stock, if stock is 0*
|Enter a number that you want to transfer as the stock quantity for items that are not limited to stock, if the stock is 0.

|*Standard delivery time*
|Enter the average delivery time in days.

|*Item delivery time 1 - 10*
|Enter the average delivery time in days for the item availabilities 1-10. +
*Important:* Note that you can only enter exact values (time periods, e.g. 2-3, are not possible).

|*Standard commission in percent*
|Enter the commission value that you agreed on with Plus.de.

2+|Additional texts

|*For property ...*
|Enter additional information about the properties here (optional). Properties are displayed after you have created them in the *System » Item » Properties* menu.

2+|Order settings

|*Minimum order quantity*
|Enter a number of items if you want to define a minimum order quantity.

|*Maximum order quantity*
|Enter a number of items if you want to define a maximum order quantity.

|*Item names in order items*
|Select whether the item name in the order items should be taken from Plus.de or from your online store.

2+|SFTP settings

|*User name*
|Enter the user name that you have received from Plus.de.
|====

Connecting to this market allows for the following automatic processes to take place:

- daily item export
- daily price synchronisation
- hourly stock synchronisation
- hourly order import

[#250]
== Activating an order referrer

In order to link items, properties etc. with Plus.de, you have to activate the order referrer Plus.de in the menu *System » Orders » Order referrer*.

[.instruction]
Activating the order referrer for Plus.de:

. Go to *System » Orders » Order referrer*.
. Place a check mark next to *Plus.de*.
. *Save* the settings.

[#300]
== Setting the item availability

Items have to be available for Plus.de. This is done in the *Availability* tab of an item within the <<item/managing-items#_changing_the_variation_data_shown_in_variation_tabs, Item » Edit item » Tab: Variation ID>> menu.

[.instruction]
Setting the item availability for Plus.de:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section.  +
→ A list with all available markets is displayed.
. Place a check mark next to the option *Plus.de*.
. Place a check mark next to the option *GartenXXL.de* if you also want to sell your items there.
. Place a check mark next to the option *Web API*.
. Click on *Add*. +
→ The market is added.
. *Save* the settings. +
→ The item is available on Plus.de.

The availability for variations can be individually edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

[#330]
==  Defining SKU manually

Add SKUs manually for specific referrers in the menu <<item/managing-items#_changing_the_variation_data_shown_in_variation_tabs, Item » Edit item » Open item » Tab: Variation ID » Tab: Availability>> if needed.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
.  Click on the *Availability* tab.
.  Click on *Add* in the section *SKU*. +
→ The window *New SKU* is displayed.
.  Select the referrer *Plus.de*.
.  Enter the SKU.
.  Click on *Add*. +
→ The SKU is saved and displayed.

[#350]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Plus.de or GartenXXL. This price is displayed on Plus.de or GartenXXL.

[.instruction]
Defining a sales price for Plus.de or GartenXXL:

. Open the menu *System » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *Plus.de* or *GartenXXL*.
. *Save* the settings.

[#400]
== Activating the payment method

Activate the <<order-processing/payment/managing-payment-methods#, payment method>> *Plus.de* as described below. Afterwards, carry out the settings in the same way for the payment method *GartenXXL.de*.

[.instruction]
Activating the Plus.de payment method:

. Go to *System » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Click on the folder *DE &gt; Plus.de*. +
→ The settings for the Plus.de payment method are displayed.
. Carry out the settings. Pay attention to the explanations given in <<settings-payment-method>>.
. Place a check mark next to the option *Active*.
. *Save* the settings.

[[settings-payment-method]]
.Settings for the payment method
[cols="1,3"]
|====
|Setting |Explanation

|*Language*
|The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo* and *Upload logo*. This makes it possible to enter values for these options in various languages. The values for a language are activated as soon as a buyer selects the language in the online store.

|*Name*
|Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
|Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
|If you have selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
|Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely configured.

|*Logo*
|Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

|*Logo view*
|If *Show upload logo* has been selected from the *Logo* drop-down list, then the logo that has been uploaded is displayed here.

|*Upload logo*
|If *Show upload logo* has been selected from the *Logo* drop-down list, upload an external logo here. +
 Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|*Priority*
|Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
|If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. Important: Do not enter a value into both fields.  +
For further information, refer to the <<basics/statistics#, Statistics>> page of the manual. For an example of flat rate and percentage costs, refer to the <<order-processing/payment/managing-payment-methods, Managing payment methods>> page of the manual.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *System » CRM » Classes* to activate or deactivate *Permitted payment methods*. +
For further information, refer to the <<order-processing/payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter of the manual.
====

For further information, refer to the <<order-processing/payment/managing-payment-methods#, Managing payment methods>> page of the manual.

[#500]
== Linking categories

You need to create category links in order for your items to be displayed on the markets Plus.de and GartenXXL.de. Plus.de will send you the necessary Plus.de and GartenXXL.de category IDs. Proceed as follows to create category links in order for your items to be displayed in the <<item/managing-categories#, categories>> on Plus.de and GartenXXL.de.

[.instruction]
Linking categories:

. Go to *System » Markets » Plus.de*.
. Click on the *Activate categories* tab.
. In the columns *Plus.de category links* and *GartenXXL.de category links*, enter the category ID that best matches your online store categories. +
→ The Plus.de and GartenXXL.de category IDs can be found in the category files that you received from Plus.de.
. Activate the categories.
. *Save* the settings.

[#600]
== Linking manufacturers

You need to link your <<item/managing-items#560, manufacturers>> in order for your items to be displayed for sale on the markets Plus.de and GartenXXL.de. You will receive a file from Plus.de which contains the manufacturer IDs.

[.instruction]
Linking manufacturers:

. Go to *System » Item » Manufacturers*.
. Open the manufacturer.
. Enter the ID into the *Plus.de ID* field. +
→ You can find the Plus.de manufacturer ID in the file that you received from Plus.de.
. *Save* the settings.

[#700]
== Creating properties

Use <<item/managing-items#480, properties>> to link your items to particular characteristics that you need for the market Plus.de. If needed, you can save commissions and category links that differ from the default settings saved for the items. Moreover, you transfer item information to Plus.de with the help of property filters and determine criteria for the item search on Plus.de.

As described in chapter <<Linking categories, Linking categories>>, go to *System » Markets » Plus.de* and save the standard category links in the *Activate categories* tab. If you want to link specific items to a different category, use the <<item/managing-items#480, property>> *Item category link for GartenXXL.de* or *Item category link for Plus.de*.

[.instruction]
Creating a property:

. Go to *System » Item » Properties*.
. Open the *New Property* tab.
. Enter the name in the *Name (internal)* field.
. Select the property type *Text*.
. Select the Plus.de property *Item category link for GartenXXL.de* or *Item category link for Plus.de* from the drop-down list.
. *Save* the settings.

[#800]
=== Setting commission rates saved for an item

Go to *System » Markets » Plus.de* to save a standard commission rate for the market Plus.de. You can save a different commission rate for each item because different commissions may apply to particular Plus.de item classes. To do so, use the <<item/managing-items#480, property>> *Commission in percent*. This setting has a higher priority than the standard provision. Make sure to coordinate this percentage value with Plus.de in advance.

[.instruction]
Creating a property:

. Go to *System » Item » Properties*.
. Open the *New Property* tab.
. Enter the name in the *Name (internal)* field.
. Select the property type *Text*.
. Select the Plus.de property *Commission in percent* from the drop-down list.
. *Save* the settings.

[TIP]
.Properties: Filter
====
Filters for Plus.de have two functions: First, they are used to transfer item information to Plus.de and second, items can be found with filters on Plus.de. After having selected a filter, another drop-down list is displayed. Select the filter property that you want to link to the item. +
Note: The property *Energy efficiency* is only available for the market Plus.de.
====

[#900]
=== Creating the property energy efficiency

To comply with EU regulations on energy efficiency that came into force on 1 January 2015, you have to provide information on the energy efficiency of certain items to sell them on Plus.de. In addition, you have to make product data sheets available to potential buyers of these items. Create the following three <<item/managing-items#480, properties>>: *Energy efficiency class*, *Energy label* and *Product data sheet*.

[.instruction]
Creating the property energy efficiency class:

. Go to *System » Item » Properties*.
. Open the *New Property* tab.
. Enter the name in the *Name (internal)* field.
. Select the property type *No*.
. Select the option *Energy efficiency* from the *Plus.de property* drop-down list. +
→ A drop-down list opens.
. Select the energy efficiency class.
. *Save* the settings.

Select the property type *File* for the properties Energy label and Product data sheet. Select the option *Energy label* or *Product data sheet* from the drop-down list *Plus.de property*. The following example describes how to create the property energy label. Afterwards, create the property product data sheet the same way.

[.instruction]
Creating the property energy label:

. Go to *System » Item » Properties*.
. Open the *New Property* tab.
. Enter the name in the *Name (internal)* field.
. Select the property type *File*.
. Select the option *Energy label* from the drop-down list *Plus.de property*.
. *Save* the settings.

You then link the properties in the <<item/managing-items#480, Properties>> tab of a Plus.de item. Proceed as described below to do so.

[.instruction]
Linking energy efficiency properties to a Plus.de item:

. Go to *Item » Edit item*.
. Open the item.
. Open the *Properties* tab.
. Activate the properties *Energy efficiency class*, *Energy label* and *Product data sheet* that you have just created.
. *Save* the settings. +
→ The properties are linked to the item and are visible in the *Properties* area.
. Upload the image file of the energy label to the *Energy label* property.
. Upload the PDF file of the product data sheet to the *Product data sheet* property.
. *Save* the settings.

Instead of linking the *Energy label* property, you can also upload the energy label file to the <<item/managing-items#660, Images>> tab of the item. To do so, proceed as follows.

[.instruction]
Saving the energy label in the "Images" tab:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Images* tab.
. Add the image file of the energy label either via *Select files* or via the drag & drop function.
. *Save* the settings.
. Go to *System » Markets » Plus.de*.
. In the *Settings* tab, enter the image's position number into *Image position for energy label* field (table 1).
. *Save* the settings.

[#1000]
== Automatically sending shipping confirmations

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically send shipping confirmations to Plus.de when the outgoing items have been booked. The shipping confirmation is automatically sent to Plus.de as soon as the order status changes to *[7] Outgoing items booked*. After that, the buyer is informed about the shipment of the item by Plus.de.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-shipping-confirmation>>.
. *Save* the settings.
.  Carry out the settings. Pay attention to the explanations given in <<event-procedure-shipping-confirmation>>.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[event-procedure-shipping-confirmation]]
.Event procedure for automatically sending shipping confirmations to Plus.de
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Outgoing items booked*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*Plus.de* and *GartenXXL.de*

|*Procedure*
|*Shipping &gt; Send shipping confirmation to Plus.de*
|
|====

[#1100]
== Automatically sending cancellations

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically send cancellations to Plus.de.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-cancellation>>.
. *Save* the settings.
.  Carry out the settings. Pay attention to the explanations given in <<event-procedure-cancellation>>.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[event-procedure-cancellation]]
.Event procedure for automatically sending cancellations to Plus.de
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change &gt; [8] Cancelled*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*Plus.de* and *GartenXXL.de*

|*Procedure*
|*Payment methods &gt; Send cancellation to Plus.de*
|
|====

[#1200]
== Automatically sending returns

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically send returns to Plus.de.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-returns>>.
. *Save* the settings.
.  Carry out the settings. Pay attention to the explanations given in <<event-procedure-returns>>.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[event-procedure-returns]]
.Event procedure for automatically sending returns to Plus.de
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order generation: New return*
|

|*Filter 1*
|*Order &gt; Order type*
|*Return*

|*Filter 2*
|*Order &gt; Referrer*
|*Plus.de* and *GartenXXL.de*

|*Procedure*
|*Return &gt; Send return to Plus.de*
|
|====

[#1250]
== Automatically cancelling unpaid orders after 30 days

Orders which have not been paid by the customer are automatically cancelled at Plus.de/GartenXXL after 30 days. Use the <<basics/automation/procedure-manager#, procedure manager>> to set up an procedure in order to automatically cancel unpaid Plus.de/GartenXXL orders in your plentymarkets system after 30 days. This way, reserved stock is released again.

[.instruction]
Setting up a procedure:

. Go to *System » Orders » Procedures » Tab: New procedure*.
. Click on the *Settings* tab.
. Place a check mark next to the option *Active*.
. Select a time at which the procedure is to be carried out from the drop-down list *Execute every day at*. We recommend to use *24:00 o clock* for this procedure.
. Enter a name.
. Click on the *Filter* tab.
. Select the filters according to <<unpaid-orders>>.
. Click on the *Procedure* tab.
. Select a status from the drop-down list *Change order status*, e.g. *[8.1] Cancelled by customer*. For further information about the selection of the status, refer to the info box below.
. *Save* the settings.
→ The procedure is created and displayed in the *Procedures* tab.

[TIP]
.Select a status
====
Select a status for the procedure *Change order status* that you have saved within *System » Orders » Settings* for the option *Status of cancelled orders (No reservation of stocks)* to cancel reservations. In addition, do not select a status that triggers an event action which reports cancellations to Plus.
====

[[unpaid-orders]]
.Filters for the procedure for automatically cancelling unpaid orders after 30 days
[cols="1,3"]
|====
| Filter | Selection

|*Status*
|*[3]Waiting for payment*

|*Order type*
|*Order*

|*Incoming orders*
|*30 days ago*

|*Order referrer*
|*Plus.de, GartenXXL.de*
|====

[#1350]
== Creating delivery notes and return labels

The following information only applies to delivery notes and return labels for Plus.de and GartenXXL.de. It does not apply to other markets.

[IMPORTANT]
.Invoices are sent by Plus.de
====
Plus.de sends the invoice to the customer. You will receive the customer's delivery address from Plus.de but not the customer's invoice address. The delivery address supplied by Plus.de is saved as the delivery and invoice address in plentymarkets. You send the items to this address.
====

Proceed as follows to create <<order-processing/orders/order-documents/generating-delivery-notes#, PDF templates>> for delivery notes and return labels for Plus.de and GartenXXL.de. The following example describes how to create a delivery note for Plus.de. Afterwards, create a return slip for Plus.de in the same way. Proceed the same way to create these two documents also for GartenXXL.de. The logo of Plus.de or GartenXXL.de must be included in the PDF templates. Request the logos directly from Plus.de.

Download the PDF templates for link:https://www.plentymarkets.eu/documents/category/3507/Template-Plus.pdf[Plus.de^] and link:https://www.plentymarkets.eu/documents/category/3507/Template-GartenXXL.pdf[GartenXXL]^ here.

[.instruction]
Creating delivery note for Plus.de (German example):

. Go to *System » Client » Select client » Locations » Germany (standard) » Documents » Delivery note*.
. Click on the tab *PDF template*.
. Click on *Add template*. +
→ An editing window opens.
. Select the option *Plus.de* from the drop-down list *Payment method*.
. Select a language from the *Language* drop-down list.
. In the line *Template*, click on *Choose template file*.  +
→ Upload the PDF template.
. *Save* the settings.

[IMPORTANT]
.Mandatory document entries for Plus.de and GartenXXL.de
====
The external order number and the external customer number are mandatory on documents that belong to orders with the referrer Plus.de or GartenXXL.de. You can normally hide these entries by selecting *NO* in the *Template* tab's *Optional elements in the stock unit table* area of the *System » Client » Select client » Locations » Germany (standard) » Documents » Delivery note* and/or *Return label* menu. +
For Plus.de and GartenXXL.de, the external order number and the external customer number are not hidden, even if you select the option *NO* here.
====

[IMPORTANT]
.Note is hidden
====
The text that you can save in the *Note* field in the *Template* tab's *Optional elements in the stock unit table* area of the *System » Client » Select client » Locations » Germany (standard) » Documents » Delivery note* and/or *Return label* menu is hidden on documents that belong to the referrers Plus.de and GartenXXL.de. This is required by Plus.de.
====
