= Yatego
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market Yatego in your plentymarkets system.
:position: 250

With plentymarkets you can offer your items on the **link:http://www.yatego.com/[Yatego.com^]** sales platform. Yatego offers sellers extensive services with powerful, complete solutions as well as comprehensive technical support.

[#10]
== Registering with Yatego

Register with **link:http://www.yatego.com/doc,yategoverkaufen[Yatego^]** to receive your access data. You will need this data for the settings in plentymarkets. Please note that the Yatego website is currently only available in German.

[#20]
== Setting up Yatego in plentymarkets

Once you have registered with Yatego, use the access data that is saved there to set up the market in plentymarkets. To do so, proceed as follows.

[.instruction]
Setting up Yatego in plentymarkets:

. Go to **System » Markets » Yatego » Settings**.
. Expand the **Settings** area.
. Carry out the settings as desired. Pay attention to the information given in table 1.
. **Save** the settings.

[cols="a,a"]
|====
|Setting |Explanation

|**User name**
|Enter the **user name** for logging in to Yatego.com.

|**Password**
|Enter the **password** for logging in to Yatego.com.

|**Item image size**
|Select **Item image (standard)**, **Medium-sized item image** or **Preview image**.

|**Item name**
|Select **Name 1**, **Name 2** or **Name 3**. The names are entered in the **Texts** tab of an item.

|**Yatego store name**
|Enter the name of the **Yatego store**.

|**Shipping costs**
|**Add up shipping charges for each item** = For every item, plentymarkets transfers the shipping costs (domestic) that are valid for the online store. If a customer purchases two items on Yatego, then the shipping charges of the individual items will be added up. In addition, the shipping costs that are saved in Yatego will be added to the shipping costs that were transferred by plentymarkets.  +
**Add up, but only once for multiple copies of the same item** = plentymarkets also transfers the shipping costs (domestic) that are valid for the online store. The shipping charges will be added when purchasing various items. When purchasing two or more of the same item, the shipping charge will only be calculated once. Finally, this will also be added to the extra shipping charges saved for Yatego. +
**Use Yatego table of shipping charges based on the item weight** = plentymarkets does not transfer any shipping costs to Yatego. Based on the weight, which is saved in plentymarkets and which is also transferred to Yatego, Yatego calculates the shipping costs itself.

|**Client for the item export**
|Select the **standard online store**, a **client (store)** or the option **ALL**, depending on which online store you want to use for the item export.

|**Client for the order import**
|Select the **standard online store** or a **client (store)** for the order import.

|**Sorting of variations**
|Select **Alphabetical**, **Surcharge** or **No sorting**.

|**Transfer RRP**
|**Yes** = Transfer value for RRP, if an **RRP** for Yatego items is entered. +
**No** = Do not transfer a value for RRP.

|**Automatic upload (daily)**
|Activate in order to automatically transfer item data to Yatego each day.

|**Sold out variations**
|**Visible** = Variations that are sold out are displayed on Yatego. +
**Invisible** = Variations that are sold out are not displayed on Yatego.

|**Yatego properties**
|**Do not export** = Properties are not exported to Yatego. +
**Place in the upper part of the description** = Place properties for Yatego items in the upper part of the description. +
**Place in the lower part of the description** = Place properties for Yatego items in the lower part of the description.

|**Free text fields 1 to 20**
|**Do not export** = Free text fields are not exported to Yatego. +
**Place in the upper part of the description** = Place the text for Yatego items in the upper part of the description. +
**Place in the lower part of the description** = Place the text for Yatego items in the lower part of the description. +
**Export in a separate column** = Export the property in a separate column of the CSV file during item export. +
**Note:** This function is only still supported for customers who already use the free text field functions in the Yatego settings. New customers are requested to use the following two options.

|**Yatego warehouse rights**
|Select **Exactly** or **Simply** if you manage stock with the values -1, 0, 1 or 2.

// tr> <td>&nbsp;</td> <td><strong>YATEGO Paket-Typ (bis plentymarkets Version 4.306)</strong>:<br /> In der Einstellung <strong>Standard</strong> werden keine Cross-Selling-Informationen in der Artikel-Exportdatei ausgegeben. Die Auswahl <strong>Standard</strong> bzw. <strong>Professional</strong> entfällt ab Version 4.400, da es keine gesonderten Tarife bei Yatego mehr gibt.</td> </tr

|**Item description**
|Select **Standard description**, **Technical data** or **Both**.

|**Short item description**
|Select whether the **preview text** or the **technical data** should be used as the short item description on Yatego.

|**Warehouse**
|Select own warehouse, **Main item warehouse** or **Transfer stock quantity of distribution warehouse that currently has the largest stock**.

|**Are you sure you want to delete all item images before importing from the Yatego shop?**
|**Yes** = All item images that are currently available on Yatego will be deleted when importing new images for these items. This prevents errors when importing images. If you do not delete the old images, Yatego would not replace the old image with the new one when they have the same file name. +
**No** = Do not delete item images before the import.

|**Status for all credit card orders**
|Select **status 3** (waiting for payment) or **status 5** (cleared for shipping).

|**Set all credit card orders in status 5 to booked**
|Select whether or not credit card orders in status 5 should be set to booked.

|**Status for all Sofortbanking orders**
|Select **status 3** (waiting for payment) or **status 5** (cleared for shipping).

|**Set all Sofortbanking orders in status 5 to booked**
|Select whether or not Sofortbanking orders in status 5 should be set to booked.

|**Status for all PayPal orders**
|Select **status 3** (waiting for payment) or **status 5** (cleared for shipping).

|**Set all PayPal orders in status 5 to booked**
|Select whether or not PayPal orders in status 5 should be set to booked.

|**Transfer item URL**
|Select whether or not the item URL should be transferred.

|**Use all of the images (max. 5) from the long description as the item images**
|Select whether all item images belonging to an item should be used or not. A maximum of 5 images can be used.

|**Transfer online store categories**
|Select **All**, **Only the default category** or **No**. +
The **Default category** is selected in the **Categories** tab of an item. If you select this option for Yatego, then check which default category was saved for the item in its **Categories** tab. If you did not select a category there, then the **default category** will automatically be selected. If you have multiple category links, then this means that the first category link will be treated as the default category.

|**Online store category levels**
|Select which **category levels** you wish to transfer. You can select any 3 consecutive levels. Note that all the levels must be set up and linked for all of the relevant Yatego items.
|====

__Table 1: basic settings for the market Yatego__

[#30]
== Setting the item availability

Items have to be available for Yatego. This is done in the **Availability** tab of an item within the **<<item/managing-items#40, Item » Edit item » Tab: Variation ID>>** menu.

[.instruction]
Setting the item availability for Yatego:

. Open the **Item » Edit item » Open item » Tab: Variation ID » Tab: Settings** menu.
. Activate the main variation in the **Availability** section.
. Click on the **Availability** tab.
. Click in the **Markets** section in the selection field.  +
→ A list with all available markets will be displayed.
. Activate the option **Yatego**.
. Activate the option **Web API**.
. Click on **Add**. +
→ The Market will be added.
. **Save** the settings.  +
→ The item is available on Yatego.

The availability for variations can be individually edit in the **Item » Edit item » Open item » Tab: Variation ID » Open variation » Tab: Availability** menu.

[#40]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Yatego. This price will be displayed on Yatego.

[.instruction]
Defining a sales price for Yatego:

. Open the menu **System » Item » Sales prices » Open sales price » Tab: Settings**.
. Place a checkmark next to the referrer **Yatego**.
. **Save** the settings.

[#50]
== Linking categories

First, import the official Yatego categories.

[.instruction]
Importing Yatego categories:

. Go to **System » Markets » Yatego » Category link**.
. Click on **Update Yatego categories**. +
→ The Yatego categories will appear in the **Category links** area.

Link your online store categories to the Yatego categories in order to display your items in these categories. Further items from the linked category will be assigned automatically.

[.instruction]
Linking categories:

. Go to **System » Markets » Yatego » Category link**.
. Click on the **gear-wheel icon** under **Yatego link**.
. Select a category in the **Official Yatego categories** area. +
→ As an alternative, you can enter the category ID under **Yatego category ID link**.
. **Save** the settings.

Then export your online store categories in Yatego format.

[.instruction]
Exporting online store categories in Yatego format:

. Go to **System » Markets » Yatego » Category link**.
. Click on **Export online store categories**. +
→ A new window will open.
. Click on **OK** to save the CSV file.
. Import the CSV file at Yatego. +
→ Die Online store categories are now available at Yatego.

[#60]
== Linking properties

Link your **<<item/managing-items#480, properties>>**  with the Yatego properties. To do so, proceed as follows.

[.instruction]
Linking properties:

.  Go to **System » Item » Properties**.
.  Expand a property.
.  Activate the option **Yatego**.
. **Save** the settings.

[#70]
== Automatically transmitting items

Go to **System » Markets » Yatego » Settings** to carry out the item exchange with Yatego. The functions in this menu are only available after having entered the access data, as described above. The preview function allows you to check the data before the transfer takes place. The Yatego import can take a long time. plentymarkets has no control over this.

[WARNING]
.**Full Yatego import**
====
With plentymarkets, you always need to transfer the entire data sets to Yatego. This means that all items already existing in Yatego have to be deleted before a new import is carried out. If you already have items in your Yatego account, make sure that you create the same items in plentymarkets first before you allow for the items to be exported to Yatego.
====

[.instruction]
Transmitting items to Yatego:

. Go to **System » Markets » Yatego » Settings**.
. Expand the submenu **Item exchange yatego.com (FTP)**.
. Click on the corresponding **preview icon** to check the data that will be made available as a CSV file.
. After checking the data, click on **Transmit data** to transfer the data to Yatego.

[#80]
== Importing orders

Orders will be transferred directly from Yatego if the plentymarkets system with an SSL certificate was booked. The transfer of orders from Yatego to plentymarkets takes place with an encoded connection only. An SSL certificate is necessary for this. If no SSL certificate was booked, then this will have to be done retrospectively.

[TIP]
.Tip: Book SSL certificate
====
To book an SSL certificate in the Service centre, go to **Start » Service centre** in your plentymarkets system. You can book the SSL certificate in the **Add-Ons** tab.
====

// p>Liegt ein SSL-Zertifikat vor, müssen im Yatego-Backoffice nur noch einige Einstellungen unter <strong>yatego.com &gt; Bestellungen &gt; Bestellanbindungen</strong> vorgenommen werden (siehe Bild 4) und zukünftig eintreffende Aufträge werden in plentymarkets übertragen. Achten Sie darauf, dass die richtige URL inkl. <b>https://</b> eingegeben wird (also: <b>https://www.mein-shop.de/</b>).</p> <div class="plentyInfoBox plentyIsWarning"><div class="plentyInfoBoxHeader"><strong>Artikelexport weiterer Webshops</strong></div> <div class="plentyInfoBoxContent">Wird der Artikelexport für einen weiteren Webshop (Mandanten) eingerichtet, sind für den Auftragsimport trotzdem die <strong>Zugangsdaten</strong> (<strong>URL</strong> mit <strong>SSL</strong>-Zertifikat und <strong>WebToken</strong> aus den plenty API Daten) des <strong>Hauptsystems</strong> zu hinterlegen. (WebToken = <u>nicht PlentyToken</u>)</div></div> <div class="plentyInfoBox plentyIsImportant"><div class="plentyInfoBoxHeader"></div> <div class="plentyInfoBoxContent">Den <strong>Web-Token</strong> finden Sie in plentymarkets im Menü <b>Einstellungen &gt; Grundeinstellungen &gt; API-Daten</b> und dort unter <strong>WebToken</strong>.</div></div> <div class="plentyInfoBox plentyIsWarning"><div class="plentyInfoBoxHeader"><strong>Versandbestätigung</strong></div> <div class="plentyInfoBoxContent">Es erfolgt keine automatische Versandbestätigung an Yatego. Der Auftrag muss manuell direkt bei Yatego bestätigt werden.</div></div
[#80]
== Activating the payment method

Activate the **<<order-processing/payment#, payment method>>** **Yatego invoice** as described below.

[.instruction]
Activating the payment method Yatego invoice:

. Go to **System » Orders » Payment » Methods**.
. Click on the folder **DE &gt; Yatego invoice**.  +
→ The settings for the payment method will be displayed.
. Carry out the settings as desired. Pay attention to the information given in table 2.
. Place a check mark next to the option **Active**.
. **Save** the settings.

[cols="a,a"]
|====
|Setting |Explanation

|**Language**
|The following options are saved for the language selected: **Name**, **Info page**, **Info page (internal)**, **Logo** and **Upload logo**. This makes it possible to enter values for these options in various languages. The values for a language will be activated as soon as a buyer selects the language in the online store.

|**Name**
|Enter the name that should be displayed in the online store and on invoices etc.

|**Info page**
|Select a category page of the type **content** or enter the URL of a website to provide information about the payment method.

|**Info page (external)**
|If you selected the option **Info page (external)** under **Info page**, then enter the URL of the info page here.

|**Countries of delivery**
|Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely configured.

|**Logo**
|Select one of the following options for displaying the logo: +
**Show standard logo** = The logo that is saved in plentymarkets for this payment method will be displayed.  +
**Do not show a logo** = The logo that is saved in plentymarkets for this payment method will not be displayed. +
**Show upload logo** = The options **Logo view** and **Upload logo** will be displayed.

|**Logo view**
|If **Show upload logo** was selected from the **Logo** drop-down menu, then the logo that was uploaded will be displayed here.

|**Upload logo**
|If **Show upload logo** was selected from the **Logo** drop-down menu, then you will be able to upload an external logo here. +
Click on **Upload files** and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|**Priority**
|Select the priority for displaying the payment method in the online store.

|**Costs: Flat rate or percentage**
|If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. **Important:** Do not enter a value into both fields.  +
For further information, refer to the **<<basics/statistics#, Statistics>>** and **<<basics/statistics/general-statistics/item/tops-flops#, Tops/Flops>>** pages of the manual. For an example for flat rate and percentage costs, refer to the **<<omni-channel/multi-channel/yatego#20, Basic settings>>** page of the manual.
|====

__Table 2: settings of the payment method__

[TIP]
.Permitting the payment method in customer classes
====
Go to **System » Customers » Classes** to activate or deactivate the **Permitted payment methods**.  +
For further information, refer to the **<<omni-channel/multi-channel/yatego#40, Payment methods and customer classes>>** chapter of the manual.
====

For further information, refer to the **<<order-processing/payment#, Payment methods>>**  page of the manual.

[#90]
== Viewing the API log

The menu **Data » API log » Tab: API log** contains a history of processes that run via the Yatego interface. The following formats are available for Yatego:

* **Yatego(new)** (item catalogue, variations, attributes)
* **OrdersYatego** (order import)
* **Writer_OrdersYatego_Execution** (export)

[.instruction]
Viewing the API log:

. Go to **Data » API log**.
. Select a format from the drop-down menu **Process**.
. Select a **Date** if you only want to see entries for a specific day.
. Click on **Search** to carry out the search. +
→ The processes will be displayed.
. Click on the folder in the **Process** column.  +
→ The **Yatego** tab will open and error messages will be displayed for this process.

[#100]
== FAQ

[.instruction]
How does plentymarkets transmit items that are not limited to stock to Yatego?

[.indented]
All items that are set to **No limitation** will be transferred to Yatego. This setting is found by opening an item and clicking on the **Tab: Stock » Tab: Settings**. The setting is found in the **Limitation** line. plentymarkets will send a value of -1 for these items, so that Yatego knows that these items can be bought without limitation.[.instruction]
Can I manually import orders from Yatego to plentymarkets?

[.indented]
Yes. If a Yatego order is manually transferred to plentymarkets from Yatego, then Yatego will not send an item ID or variation ID (attribute_value_set_id). This will make it impossible for the item to be assigned and the item will be imported with the item ID "-2" (unknown item). Unassigned items are flagged by a **green plus** icon in the order. The item then has to be assigned manually.[.instruction]
How do I know that the purchaser has already paid the order?

[.indented]
Yatego neither sends a transaction ID for payments nor other information that indicates whether the order was paid for or not. Therefore, the Yatego settings include an option that allows you to set orders to be booked for some payment methods: **Set all orders in status 5 to booked**. Select this option if the payment method ensures that payment was already made when the order is booked.[.instruction]
The link for the item in the order does not work. What can I do?

[.indented]
Yatego sends a link for the orders, which directly connects to the item on the Yatego platform. Usually, this link doesn't work, since Yatego adds "yatego.com" to the name of the online store. Simply delete "yatego.com" from the link and then it will work correctly. +
**Example**: http://www.yatego.com/STORENAME.yatego.com/p,4fcaaf8c8292c,461e2919becf22_4  +
**The correct format is**: http://www.yatego.com/SHOPNAME/p,4fcaaf8c8292c,461e2919becf22_4 [.instruction]
I set up Yatego in plentymarkets. Why does it not transfer my orders?

[.indented]
The first time that an online store activates the Yatego order process for plentymarkets, it is common that the first two to three orders will not be automatically transferred to plentymarkets. These orders have to be manually triggered again from within the Yatego system.[.instruction]
I would like to offer an item with attributes. Why does Yatego not display the stock correctly?

[.indented]
Yatego will not be able to process the warehouse data records that plentymarkets sends for items if there are more than 999 possible combinations of attributes. As such, all possible combinations of variations will be activated for the item and set to endless stock (meaning that stock doesn't exist for Yatego). If you need to use a large number of attributes, then get in contact with Yatego before exporting the corresponding items.[.instruction]
Why does Yatego not immediately edit the CSV files I transferred?

[.indented]
The CSV files that are transferred to Yatego each day are not imported and edited immediately, but rather have to wait in line to be processed. As such, the import and editing process can take several hours. You can go to Yatego and check where your file is in line.
