= Zalando
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market Zalando in your plentymarkets system.
:position: 260

Thanks to the Zalando partner programme, online sellers and manufacturers can use Zalando as an additional distribution channel for selling their high-quality products and take advantage of the well-known brand name Zalando.

[#10]
== Registering with Zalando

If you are interested in the link:https://www.zalando.co.uk/partner-programme/[**partner programme**^], then contact Zalando directly at partner-programme@zalando.co.uk.

[cols="a,a"]
|====
| |

|**Zalando partner program team**
|link:mailto:partner.programm@zalando.de[partner.programm@zalando.de]
|====

[#20]
== Setting up Zalando in plentymarkets

As soon as Zalando has accepted you into their partner programme, you will receive a manual from Zalando which helps you setting up the interface. In plentymarkets, carry out the following basic settings.

[.instruction]
Setting up Zalando in plentymarkets:

.  Go to **System » Markets » Zalando » Settings**. +
→ The **Settings** tab will open.
.  Pay attention to the explanations given in table 1 and carry out the settings as desired.
. **Save** the settings.

[cols="a,a"]
|====
|Setting |Explanation

2+|Basic configuration

|**User**
|Select the API user. The account for the API user will be created during the initial setup.

|**Price column**
|Select a price column that is used for Zalando items.

|**Item name**
|Select **Name 1**, **Name 2** or **Name 3**.

|**Assignment client (store)**
|Select a client (store).

|**Warehouse selection**
|Select a warehouse. +
**Transfer stock quantity of distribution warehouse that currently has the largest stock** = Select the distribution warehouse that currently has the largest stock of the item. +
**Use item's main warehouse** = Select the main warehouse of the item. +
**Transfer sum of stock quantities from all distribution warehouses** = Stock of all distribution warehouses is added and transferred as sum.

2+|Advanced options

|**EAN**
|Select **EAN**, **EAN 2**, **EAN 3** or **EAN 4**.

|**Stock buffer**
|Enter the stock buffer in units.

|**Quantity for items that are not limited to the stock**
|Enter the quantity for items that are not limited to stock.

|**Maximum for item upload**
|Enter a number to determine the limit value for the item upload in units per item.

|**Standard tax rate**
|Select **19%** or **7%**.

|**Reduced tax rate**
|Select **19%** or **7%**.
|====

__Table 1: basic settings for the market Zalando__

Connecting to this market allows for the following automatic functions to take place:

* Daily item export

[#30]
== Setting the item availability

Items have to be available for Zalando. This is done in the **Availability** tab of an item within the **<<item/managing-items#40, Item » Edit item » Tab: Variation ID>>** menu.

[.instruction]
Setting the item availability for Zalando:

. Open the **Item » Edit item » Open item » Tab: Variation ID » Tab: Settings** menu.
. Activate the main variation in the **Availability** section.
. Click on the **Availability** tab.
. Click in the **Markets** section in the selection field.  +
→ A list with all available markets will be displayed.
. Activate the option **Zalando**.
. Activate the option **Web API**.
. Click on **Add**. +
→ The Market will be added.
. **Save** the settings.  +
→ The item is available on Zalando.

The availability for variations can be individually edit in the **Item » Edit item » Open item » Tab: Variation ID » Open variation » Tab: Availability** menu.

[#35]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer Zalando. This price will be displayed on Zalando.

[.instruction]
Defining a sales price for Zalando:

. Open the menu **System » Item » Sales prices » Open sales price » Tab: Settings**.
. Place a checkmark next to the referrer **Zalando**.
. **Save** the settings.

[#40]
== Linking categories

Link your online store categories to the Zalando categories in order to display your items in these categories. Further items from the linked category will be assigned automatically.

[.instruction]
Linking categories:

. Go to **System » Markets » Zalando » Category link**.
. Select a category under **Zalando category**.
. **Save** the settings.

[#50]
== Converting silhouettes to properties

In the menu **System » Markets » Zalando » Settings » Tab: Silhouettes**, you convert Zalando silhouettes to item properties. Silhouettes are transferred during the initial setup of Zalando.

. Go to **System » Markets » Zalando » Settings**.
. Click on the **Silhouettes** tab.
. Select the **groups** for the properties that you want to convert.
. **Save** the settings. +
→ The properties will be created in your plentymarkets system.

[#60]
== Exporting Zalando item properties

You can export the silhouettes that you saved in the **Groups** area and use them for the dynamic data import.

[.instruction]
Exporting Zalando item properties:

. Go to **System » Markets » Zalando » Settings**.
. Click on the **Silhouettes** tab.
. Click on **Export Zalando item properties**. +
→ A file containing the property parameters will be exported.
. Open the file.
. Carry out the settings as desired. Pay attention to the information given in table 2.
. **Save** the settings.

[cols="a,a"]
|====
|Column |Explanation

|**Group name**
|Names of the property groups.

|**Silhouette**
|Values of all silhouettes.

|**Property ID**
|Enter the ID of the online store property. You find the property ID in the **System » Item » Properties** menu.

|**Property type**
|Enter the property type. The following entries are possible:  +
**empty** = Enter this value, if the property is not used. If the property is used, **empty** must be replaced with **1**. +
**text** = Enter a value in text form, e.g. "red" for colour. +
**int** = Enter a number, e.g. the heel height. +
**selection** = Enter the option's selection ID from the drop-down menu. You find the selection ID for properties of the type **Selection** in the **System » Item » Properties** menu under **Selection ID**.

|**Mandatory entry**
|If a cell contains the value **1**, the property must be transferred. Properties may also contain the value **1** because links to other selected properties exist. Observe the documentation provided by Zalando.

|**Language**
|Enter **de** in the lines that you use. Currently, only German is available.
|====

__Table 2: values for Zalando properties__

You can link the exported Zalando properties with the items in your plentymarkets system. This is done by means of the **<<basics/data-exchange/data-formats/itemproperties#, data format>>** via the **dynamic import**.

[#70]
== Linking attributes

If you created attributes in your plentymarkets system, link these attributes with Zalando. The following example describes how you link the attribute "colour" with Zalando. Link further attributes in the same way.

[.instruction]
Linking the attribute Colour:

. Go to **System » Item » Attributes**. +
→ An overview of all existing attributes will open.
. Expand the attribute **Colour**.
. Click on the **Market variation** tab.
. Select **Zalando** from the **Market** drop-down menu. +
→ The **Zalando** drop-down menu will be displayed.
. Select the attribute **Colour** from the **Zalando** drop-down menu.
. **Save** the settings.

[#80]
== Activating the payment method

Activate the **<<order-processing/payment#, payment method>>** **Zalando Payment** as described below.

[.instruction]
Activating the Zalando payment method:

. Go to **System » Orders » Payment » Methods**.
. Place a check mark next to the setting **Also show inactive**.
. Open the folder **International**.
. Click on **Zalando Payment**.  +
→ The **Settings** tab will open.
. Carry out the settings as desired. Pay attention to the information given in table 3.
. Place a check mark next to the option **Active**.
. **Save** the settings.

[cols="a,a"]
|====
|Setting |Explanation

|**Language**
|The following options are saved for the language selected: **Name**, **Info page**, **Info page (internal)**, **Logo** and **Upload logo**. This makes it possible to enter values for these options in various languages. The values for a language will be activated as soon as a buyer selects the language in the online store.

|**Name**
|Enter the name that should be displayed in the online store and on invoices etc.

|**Info page**
|Select a category page of the type **content** or enter the URL of a website to provide information about the payment method.

|**Info page (external)**
|If you selected the option **Info page (external)** under **Info page**, then enter the URL of the info page here.

|**Countries of delivery**
|Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely configured.

|**Logo**
|Select one of the following options for displaying the logo: +
**Show standard logo** = The logo that is saved in plentymarkets for this payment method will be displayed.  +
**Do not show a logo** = The logo that is saved in plentymarkets for this payment method will not be displayed. +
**Show upload logo** = The options **Logo view** and **Upload logo** will be displayed.

|**Logo view**
|If **Show upload logo** was selected from the **Logo** drop-down menu, then the logo that was uploaded will be displayed here.

|**Upload logo**
|If **Show upload logo** was selected from the **Logo** drop-down menu, then you will be able to upload an external logo here. +
Click on **Upload files** and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|**Priority**
|Select the priority for displaying the payment method in the online store.

|**Costs: Flat rate or percentage**
|If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. **Important:** Do not enter a value into both fields.  +
For further information, refer to the **<<basics/statistics#, Statistics>>** and **<<basics/statistics/general-statistics/item/tops-flops#, Tops/Flops>>** pages of the manual. For an example for flat rate and percentage costs, refer to the **<<omni-channel/multi-channel/zalando#20, Basic settings>>** page of the manual.
|====

__Table 3: settings of the payment method__

[TIP]
.Permitting the payment method in customer classes
====
Go to **System » CRM » Classes** to activate or deactivate the **Permitted payment methods**.  +
For further information, refer to the **<<omni-channel/multi-channel/zalando#40, Payment methods and customer classes>>** chapter of the manual.
====

For further information, refer to the **<<order-processing/payment#, Payment methods>>**  page of the manual.

[#90]
== Retrieving processing reports

In the **System » Markets » Zalando » Settings » Tab: Processing reports** menu, you can retrieve processing reports as well as the export log for Zalando.

[.instruction]
Retrieving processing reports:

. Go to **System » Markets » Zalando » Settings**.
. Click on the **Processing reports** tab.
. Click on **Download file** under **Procedures** in the line of a processing report. +
→ A CSV file will be downloaded.

Download the export log in the **Export log** area.

[#100]
== Viewing the API log

The menu **Data » API log » Tab: API log** contains a history of processes that run via the Zalando interface. The **ZalandoController** format is available for Zalando.

[.instruction]
Viewing the API log:

.  Go to **Data » API log**.
.  Select the **ZalandoController** format from the **Process** drop-down menu.
.  Select a date if you only want to see entries for a specific day.
.  Select the number of results per page.
.  Click on **Search** to display the results.
