= Verfahrensdokumentation
:lang: de
include::{includedir}/_header.adoc[]
:description: Lade über diese Seite die technische Systemdokumentation von plentymarkets herunter, die den Anwendern der plentymarkets Software jedoch lediglich als Grundlage zur Erstellung deiner Verfahrensdokumentation dient.
:keywords: GoBD, GOBD, gobd, steuerrechtlich, Steuerrecht, Systemdokumentation, Verfahrensdoku, Verfahrensdokumentation, Verfahrensweise, verwendete Software
:position: 10
:url: basics/rechtliches/verfahrensdokumentation
:id: JMGHYFQ

Auf dieser Handbuchseite stellen wir dir die technische Systemdokumentation von plentymarkets zur Verfügung. Diese Systemdokumentation dient als Grundlage zur Erstellung deiner eigenen Verfahrensdokumentation.

== Rechtssicher arbeiten mit plentymarkets

Nach GoBD müssen Händler unter anderem die Verfahrensweise der von ihnen verwendeten Software in Form einer Verfahrensdokumentation beschreiben und im Falle einer Steuerprüfung vorlegen. Wir unterstützen Nutzer von plentymarkets bei der Erstellung einer Verfahrensdokumentation durch die Bereitstellung einer technischen Systemdokumentation. In dieser Systemdokumentation werden die steuerrechtlich relevanten Arbeitsweisen von plentymarkets aufgeschlüsselt, die als Grundlage für eine Verfahrensdokumentation verwendet werden können.

== Link zum Download

Lade die technische Systemdokumentation von plentymarkets link:https://cdn02.plentymarkets.com/pmsbpnokwu6a/frontend/plentymarkets_Rechtliches/Verfahrensdokumentation_V6.2.pdf[hier herunter^] (link:https://github.com/plentymarkets/template-procedure-document/releases[ältere Versionen^]).

[IMPORTANT]
.Andere Softwarelösungen
====
plentymarkets ist in der Regel nur ein Teil der in der Verfahrensdokumentation zu beschreibenden (Software-)Lösungen. Kläre mit deinem Steuerbüro, welche für deinen individuellen Fall relevanten Informationen zusätzlich in der Verfahrensdokumentation beschrieben werden müssen.
====
