[cols="1,4a"]
|======
|Einstellung |Erläuterung

| *Bereich*
//Item, CRM, Stock
|Wofür möchtest du die Eigenschaft nutzen? Wähle den entsprechenden Bereich aus der Dropdown-Liste.

*_Hinweis_*: Diese Einstellung kann nach dem Speichern nicht mehr geändert werden.

[cols="1,4a"]
!======
!Bereich !Wofür ist der Bereich geeignet?

! *Artikel*
!Solche Eigenschaften werden zur näheren Charakterisierung von Produkten verwendet.
Beispielsweise kannst du die technischen Features eines Produkts im plentyShop hervorheben (z.B. Bluetooth, WLAN).

! *Kontakt*
!Solche Eigenschaften werden zur näheren Charakterisierung von Kontakten verwendet.
Beispielsweise kannst du in jedem Kontaktdatensatz speichern, auf welchem Weg der Kontakt kontaktiert werden soll und ob er die Zusendung deines neuen Produktkatalogs wünscht.

! *Lagerort*
!Solche Eigenschaften werden zur näheren Charakterisierung von Lagerorten verwendet.
Beispielsweise kannst du bestimmen, welche Lagerorte für Kühlware oder andere Produktgruppen geeignet sind.
!======

//Item, CRM, Stock*
| *Eigenschaftstyp*
|Welche Art von Eigenschaft möchtest du anlegen? Wähle den Eigenschaftstyp aus der Dropdown-Liste.

*_Hinweis_*: Diese Einstellung kann nach dem Speichern nicht mehr geändert werden.

[cols="1,4a"]
!======
!Typ !Wofür ist der Typ geeignet?

! *Kein*
!
ifdef::item[]
Der Name der Eigenschaft kann im plentyShop angezeigt werden.
Dies eignet sich, z.B. um:

* die technischen Besonderheiten einer Variante hervorzuheben (Bluetooth, WLAN).
* Filter zu erstellen (nur Bluetooh-fähige Produkte in die Suchergebnisse berücksichtigen)
//* <<artikel/einstellungen/eigenschaften#intable-bestellmerkmal, Als Bestellmerkmal>>: Eignet sich, z.B. um Kunden <<artikel/anwendungsfaelle/personalisierte-artikel#200, zusätzliche Optionen und Dienstleistungen>> während des Bestellvorgangs anzubieten.
endif::item[]
ifdef::crm,stock[]
Diese Option wählen, wenn Eigenschaften außerhalb der Bereiche *Artikel*, *Lagerort* und *Kontakt* verwendet werden sollen, wie z.B. für die Facettensuche. +
endif::crm,stock[]
ifdef::crm[]
*_Hinweis:_* Dieser Eigenschaftstyp kann _nicht_ auf deinen Dokumenten ausgegeben werden.
endif::crm[]

ifdef::item,crm[]
! *Datum*
!
endif::item,crm[]
ifdef::item[]
Ein Datum kann im plentyShop angezeigt werden.
endif::item[]
ifdef::crm[]
Wähle diese Option, um die Eingabe eines Datums oder die Wahl des Datums aus einem Kalender zu ermöglichen.
endif::crm[]

ifdef::item,crm[]
! *Datei*
!
endif::item,crm[]
ifdef::item[]
Eine Datei kann für die Variante verfügbar gemacht werden, z.B. eine Montageanleitung.

//<<artikel/einstellungen/eigenschaften#intable-bestellmerkmal, Als Bestellmerkmal>>: Ermöglicht es Kunden, z.B. <<artikel/anwendungsfaelle/personalisierte-artikel#100, ein eigenes Bild hochzuladen>>, das auf ein T-Shirt gedruckt werden soll.
endif::item[]
ifdef::crm[]
Wähle diese Option, um das Hochladen einer Datei zu ermöglichen.
endif::crm[]

ifdef::item,crm[]
! *Ganze Zahl*
!
endif::item,crm[]
ifdef::item[]
Eine ganze Zahl kann im plentyShop angezeigt werden.
Eignet sich, z.B. um ein Gewicht oder eine Länge anzugeben. Beispielsweise HDMI-Kabeln, die über 10 m lang sind.
endif::item[]
ifdef::crm[]
Gib eine ganze Zahl ein.
endif::crm[]

ifdef::item,crm[]
! *Kommazahl*
!
endif::item,crm[]
ifdef::item[]
Eine Zahl mit Kommastellen kann im plentyShop angezeigt werden.
Eigent sich, z.B. um Maßangaben im plentyShop anzuzeigen. Beispielsweise ein Krug, der 1,4 Liter fasst.
endif::item[]
ifdef::crm[]
Gib eine Zahl mit Kommastellen ein. Zulässig sind 8 Vor- und 4 Nachkommastellen.
endif::crm[]

ifdef::item,crm[]
! *Text*
!
endif::item,crm[]
ifdef::item[]
Ein Text mit Formatierung kann im plentyShop angezeigt werden.
Eignet sich z.B., um variantenspezifische Produktbeschreibungen zu erstellen.

//<<artikel/einstellungen/eigenschaften#intable-bestellmerkmal, Als Bestellmerkmal>>: Ermöglicht es Kunden, z.B. <<artikel/anwendungsfaelle/personalisierte-artikel#100, einen persönlichen Text einzugeben>>, der auf ein T-Shirt gedruckt werden soll.
endif::item[]
ifdef::crm[]
Gib einen Text ein. Dieser Text kann formatiert werden.
endif::crm[]

ifdef::item,crm[]
! *Kurztext*
!
endif::item,crm[]
ifdef::item[]
Ein Text ohne Formatierung kann im plentyShop angezeigt werden.
Eignet sich z.B., um variantenspezifische Produktbeschreibungen zu erstellen.
endif::item[]
ifdef::crm[]
Gib einen Kurztext ein. Dieser Text kann nicht formatiert werden.
endif::crm[]

! *Auswahl*
!
ifdef::item[]
Erstellt eine Dropdown-Liste mit möglichen Werten.
Während du die Eigenschaft mit einer Variante verknüpfst, gibst du an, welcher der Werte für die Variante zutrifft.
//Pro Option und Wert können bis zu 65.535 Zeichen eingegeben werden.

*_Anwendungsbeispiel_*:

. <<artikel/einstellungen/eigenschaften#760, Erstens>> erstellst du verschiedene Stufen der Wasserfestigkeit.
. <<artikel/einstellungen/eigenschaften#1400, Zweitens>> gibst du den Grad der Wasserfestigkeit für jede Variante an.
. <<artikel/frontend-artikelsuche-verwalten#, Drittens>> erstellst du Webshop-Filter, die es deinen Kunden ermöglichen, gezielt nach Varianten mit einer bestimmten Wasserfestigkeitsstufe zu suchen.
endif::item[]
ifdef::crm,stock[]
Diese Option ermöglicht es, Werte einzugeben und anschließend einen dieser Werte aus einer Dropdown-Liste zu wählen. +
endif::crm,stock[]
ifdef::crm[]
*_Hinweis:_* Dieser Eigenschaftstyp kann _nicht_ auf deinen Dokumenten ausgegeben werden.
endif::crm[]

ifdef::item,crm[]
! *Mehrfachauswahl*
!
endif::item,crm[]
ifdef::item[]
Erstellt eine Reihe von Checkboxen.
Während du die Eigenschaft mit einer Variante verknüpfst, kreuzt du alle passenden Werte an.

*_Anwendungsbeispiel_*:

. <<artikel/einstellungen/eigenschaften#760, Erstens>> erstellst du verschiedene Besonderheiten. Zum Beispiel, wenn du Bücher verkaufst: Erstausgabe, Autorensignatur, Rarität, Sammleredition.
. <<artikel/einstellungen/eigenschaften#1400, Zweitens>> kreuzt du die Besonderheiten an, die für die Variante gelten, z.B. eine Erstausgabe mit Autorensignatur.
. <<artikel/frontend-artikelsuche-verwalten#, Drittens>> erstellst du Webshop-Filter, die es deinen Kunden ermöglichen, gezielt nach Varianten mit solchen Besonderheiten zu suchen.
endif::item[]
ifdef::crm[]
Diese Option ermöglicht es, Werte einzugeben und anschließend eine oder mehrere Optionen zu wählen. +
*_Hinweis:_* Dieser Eigenschaftstyp kann _nicht_ auf deinen Dokumenten ausgegeben werden.
endif::crm[]
!======

| *Name*
//Item, CRM, Stock
|Gib einen Namen für die Eigenschaft in der Standardsprache deines plentymarkets Systems ein.
ifdef::item[]
Dieser Name kann <<für Kunden im plentyShop sichtbar>> gemacht werden.
Dies hängt davon ab, wie du das Layout mit ShopBuilder gestaltest.
endif::item[]

*_Hinweis_*: Nach dem Speichern, kannst du den <<artikel/einstellungen/eigenschaften#720, Namen in weiteren Sprachen angeben>>.

| *Beschreibung*
//Item, CRM, Stock
|
ifdef::item[]
Derzeit ohne Funktion.
Diese Option wird zukünftig zur Darstellung einer Beschreibung von Bestelleigenschaften im plentyShop verwendet werden.
Zurzeit ist es aber nur möglich, Bestellmerkmale zu verwenden.
endif::item[]

ifdef::crm,stock[]
Gib eine Beschreibung für die Eigenschaft in der Standardsprache deines plentymarkets Systems ein.

*_Hinweis_*: Nach dem Speichern, kannst du die <<artikel/einstellungen/eigenschaften#720, Beschreibung in weiteren Sprachen angeben>>.
endif::crm,stock[]

| *Gruppe*
//Item, CRM, Stock
|Soll diese Eigenschaft in eine bestimmte <<artikel/einstellungen/eigenschaften#1200, Gruppe>> eingeordnet werden? Falls ja, dann wähle die Gruppe hier aus.

*_Hinweis_*: Diese Dropdown-Liste enthält nur Eigenschaftsgruppen, die bereits angelegt wurden.
So erstellst du eine neue Gruppe:

. Klicke auf *Eigenschaftsgruppe hinzufügen* (icon:plus[role="green"]).
. Konfiguriere die <<artikel/einstellungen/eigenschaften#1200, Einstellungen für die Gruppe>>. +
→ Nachdem du die Gruppe gespeichert hast, wirst du automatisch zu diesem Menü zurückgeführt und die Gruppe wird hier vorausgewählt.

*_Hinweis_*: Es würde viel Zeit in Anspruch nehmen, manuell eine Gruppe für jede Eigenschaft auszuwählen.
Verwende stattdessen die Gruppenfunktion, um <<artikel/einstellungen/eigenschaften#1300, mehrere Eigenschaften gleichzeitig einer Gruppe zuzuweisen>>.

| *Position*
|Welche Eigenschaft soll als erste, zweite, dritte, usw. angezeigt werden? Gib eine Positionsnummer in dieses Feld ein.
ifdef::item[]
Wenn eine Variante mehrere Eigenschaften hat, werden die Eigenschaften aufsteigend nach Positionsnummern in deinem plentyShop dargestellt.
endif::item[]
ifdef::crm,stock[]
Standardmäßig wird aufsteigend nach Positionsnummer sortiert. +
*_Tipp:_* Speichere die Positionsnummern in 10er-Schritten, damit du mögliche neue Eigenschaften dazwischen einfügen kannst.
endif::crm,stock[]
|======

'''

[discrete]
===== Allgemein

[cols="1,3"]
|====
|Einstellung |Erläuterung

2+| *Details*

//Item, CRM, Stock
| *ID*
|Bei der Erstellung erhält jede Eigenschaft automatisch eine fortlaufende und einzigartige ID.
Die ID kann nicht geändert werden.

//Item, CRM, Stock
| *Bereich*
|Der Bereich, den du beim Erstellen der Eigenschaft gewählt hast.
Diese Einstellung kann nicht mehr geändert werden.

//Item, CRM, Stock
| *Eigenschaftstyp*
|Der Typ, den du beim Erstellen der Eigenschaft gewählt hast.
Diese Einstellung kann nicht mehr geändert werden.

//Item, CRM, Stock
| *Position*
|
ifdef::item[]
Welche Eigenschaft soll als erste, zweite, dritte, usw. angezeigt werden? Gib eine Positionsnummer in dieses Feld ein. Wenn eine Variante mehrere Eigenschaften hat, werden die Eigenschaften aufsteigend nach Positionsnummern in deinem plentyShop dargestellt.
endif::item[]
ifdef::crm,stock[]
Gib eine neue Position ein, um die Anzeigereihenfolge zu ändern.
endif::crm,stock[]

2+| *Optionen*

ifdef::item[]
| *Einheiten*
//Item
|Handelt es sich bei der Eigenschaft um etwas wie ein Gewicht oder eine Länge, z.B. HDMI-Kabeln, die über 10 m lang sind? Falls ja, dann wähle die passende <<artikel/einstellungen/einheiten#, Einheit>>.
endif::item[]

ifdef::item[]
| *Auftragseigenschaft* +
(Derzeit ohne Funktion)
//Item
a|Diese Option wird zukünftig zur Erstellung von _Bestelleigenschaften_ verwendet werden.
Zurzeit ist es aber nur möglich, _Bestellmerkmale_ zu verwenden.

Mit anderen Worten, zurzeit ist es nur möglich, ganze <<artikel/anwendungsfaelle/personalisierte-artikel#, Artikel personalisierbar zu machen>>, anstatt spezifische Varianten. Unser Entwicklungsteam arbeitet jedoch hart an einer Lösung: Bestelleigenschaften. Nach ihrer Veröffentlichung wird es möglich sein, einzelne Variante personalisierbar zu machen.
//Markiere dieses Feld (icon:check-square[role="blue"]), wenn Kunden die Möglichkeit haben sollen, <<artikel/anwendungsfaelle/personalisierte-artikel#, ihre Bestellung zu personalisieren>>. Zum Beispiel:

//* durch die Eingabe eines persönlichen Gravurtextes.
//* durch die Auswahl zusätzlicher Serviceleistungen gegen Aufpreis.

//Wie Kunden ihre Bestellungen genau personalisieren können, hängt davon ab, welchen <<Eigenschaftstyp>> du gewählt hast.
endif::item[]

ifdef::item[]
| *zusätzliche Kosten anzeigen* +
(Derzeit ohne Funktion)
//Item
|Diese Option wird zukünftig z.B. zur Darstellung von Pfandbeträgen verwendet werden.
Mit anderen Worten, diese Option legt fest, dass keine Mehrwertsteuer auf einen Aufpreis berechnet werden soll.

Zurzeit ist es nur möglich, solche Aufpreise mit <<artikel/einstellungen/eigenschaften#300, Merkmalen>> zu realisieren.

//|[#intable-preiskalk]*Preiskalkulationseigenschaft*
//|Eigenschaften vom Typ "Ganze Zahl" oder "Kommazahl" können in <<artikel/einstellungen/preise#1000, Preiskalkulationen>> verwendet werden.
//Wähle diese Option (icon:check-square[role="blue"]), wenn du eine Eigenschaft vom Typ "Ganze Zahl" oder "Kommazahl" erstellst und sie in Preiskalkulationen verfügbar sein soll.
endif::item[]

ifdef::crm[]
//CRM
| *Pflichtfeld*
|Aktiviere diese Option, damit die Eigenschaft zu einer Pflichtangabe wird.
Pflichtfelder werden in der Detailansicht des Kontakts im Bereich *Eigenschaften* und im Bestellvorgang im plentyShop fett markiert.
endif::crm[]

ifdef::crm[]
//CRM
| *Bestellvorgang*
|Aktiviere diese Option, damit die Eigenschaft im Bestellvorgang im plentyShop angezeigt wird.
endif::crm[]

ifdef::crm[]
//CRM
| *Kundenregistrierung*
|Aktiviere diese Option, damit die Eigenschaft in der Kundenregistrierung im plentyShop angezeigt wird.
endif::crm[]

ifdef::crm[]
//CRM
| *Kontaktsuche*
|Diese Option ist aktuell noch ohne Funktion. Es soll später möglich sein, nach Eigenschaften im Menü *CRM » Kontakte* filtern zu können.
endif::crm[]

2+| *Name*

//Item, CRM, Stock
| *Sprache*
|Ist dein plentyShop in mehreren Sprachen verfügbar? Dann wähle eine Sprachversion aus der Dropdown-Liste.

//Item, CRM, Stock
| *Name*
|Gib einen Namen für die Eigenschaft in der gewählten Sprache ein.
ifdef::item[]
Dieser Name kann <<für Kunden im plentyShop sichtbar>> gemacht werden.
Dies hängt davon ab, wie du das Layout mit ShopBuilder gestaltest.
endif::item[]

//Item, CRM, Stock
| *Beschreibung*
|
ifdef::item[]
Derzeit ohne Funktion.
Diese Option wird zukünftig zur Darstellung einer Beschreibung von Bestelleigenschaften im plentyShop verwendet werden.
Zurzeit ist es aber nur möglich, Bestellmerkmale zu verwenden.

//Gib eine Beschreibung für die Eigenschaft in der gewählten Sprache ein.
//sichtbar im Webshop je nachdem wie man ShopBuilder konfiguriert?
//Die Beschreibung wird angezeigt, wenn du mit dem Mauszeiger auf das Merkmal zeigst.
endif::item[]

ifdef::crm,stock[]
Gib eine Beschreibung für die Eigenschaft in der gewählten Sprache ein.
endif::crm,stock[]

2+| *Gruppe*

//Item, CRM, Stock
| *Gruppe*
|Soll diese Eigenschaft in eine bestimmte <<artikel/einstellungen/eigenschaften#1200, Gruppe>> eingeordnet werden? Falls ja, dann wähle die Gruppe hier aus.

*_Hinweis_*: Diese Dropdown-Liste enthält nur <<artikel/einstellungen/eigenschaften#1200, Eigenschaftsgruppen, die bereits angelegt wurden>>.

*_Hinweis_*: Es würde viel Zeit in Anspruch nehmen, manuell eine Gruppe für jede Eigenschaft auszuwählen.
Verwende stattdessen die Gruppenfunktion, um <<artikel/einstellungen/eigenschaften#1300, mehrere Eigenschaften gleichzeitig einer Gruppe zuzuweisen>>.
|====

[#740]
[discrete]
===== Sichtbarkeit

[cols="1,3"]
|====
|Einstellung |Erläuterung

ifdef::item[]
//Item
| *Herkunft*
|Auf welchen Verkaufskanälen soll die Eigenschaft sichtbar sein?
Wähle (icon:check-square[role="blue"]) eine, mehrere oder alle Herkünfte.

*_Hinweis_*: Die Dropdown-Liste enthält nur aktivierte Auftragsherkünfte.
Falls du also einen bestimmten Marktplatz in der Liste nicht finden kannst, öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft* und stelle sicher, dass der Markt aktiviert wurde (icon:check-square[role="blue"]).
endif::item[]

//Item, CRM
ifdef::item[]
| *Mandant*
endif::item[]
ifdef::crm[]
| *Mandant (Shop)*
endif::crm[]
ifdef::item,crm[]
|Soll die Eigenschaft nur für bestimmte Mandanten (Shops) gelten? Falls ja, dann wähle alle Shops (icon:check-square[role="blue"]), für die diese Eigenschaft gelten soll.

*_Hintergrund-Info_*: Mit plentymarkets kannst du mehrere Webshops, d.h. <<webshop/mandanten-verwalten#, mehrere Mandanten>>, mit nur einer Software verwalten. Somit ist es möglich, über ein plentymarkets System mehrere unterschiedliche Geschäftsbereiche zu realisieren. Das ist ein großer Vorteil. Aber es bedeutet auch, dass du plentymarkets immer mitteilen musst, für welchen Webshop die Eigenschaft gilt.
endif::item,crm[]

ifdef::item[]
//Item
| *Überall anzeigen*
|Wo soll die Eigenschaft angezeigt werden? Wähle die Bereiche (icon:check-square[role="blue"]), wo deine Kunden die Eigenschaft sehen sollen.
endif::item[]

ifdef::crm[]
//CRM
| *Sichtbarkeit*
|Wähle, für welche Kundentypen die Eigenschaft sichtbar sein soll.
endif::crm[]
|====
