= Forwarding
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Online store, Client, Forwarding
:position: 40

In the menu **plentymarkets » Settings » Client (store) » Standard » Online store » Forwarding**, you can configure the settings for forwarding mobile devices to your online store. Moreover you determine what should happen if the URL of a category page or an item is no longer up-to-date and a 404 error message is displayed. For further information, refer to our blog entry about link:https://www.plentymarkets.co.uk/blog/New-sitemap-avoid-404-errors-in-your-online-store/b-1283/[**avoiding 404 errors**].

== Setting up forwarding for mobile devices

If you wish to offer a mobile version of your website, you need to enter two target URLs in the menu **Settings » Client (store) » Standard » Online store » Forwarding**. The option **Target URL (category)** controls access to the categories. The option **Target URL (item page)** sets up forwarding to a specific item. The forwarding is initiated by a HTTP request when the online store is accessed with a mobile device. Proceed as described below to set up forwarding for mobile devices.

[.instruction]
Setting up forwarding for mobile devices:

. Go to **Settings » Client (store) » Standard » Online store » Forwarding**.
. Pay attention to the explanations given in table 1 and carry out the settings as desired.
. **Save** the settings.

[cols="a,a"]
|====
|Settings |Explanation

|**Forwarding**
|This function makes it possible to display your online store on mobile devices, e.g. with **<<omni-channel/multi-channel/shopgate#, Shopgate  >>** or a similar provider. Select **Active** to begin forwarding to the specified URLs.

|**Target URL (category)**
|Enter the URL for the mobile version of your online store, e.g. **http://mobile.yourplentystore.co.uk**. All customers that access your online store from a mobile device will be forwarded to this URL. +
**Tip:** In the URL, the template variable **$ReferrerID** defines where customers were forwarded from. The URL would then look like this: **http://mobile.yourplentystore.co.uk/?referrerId=$referrerId**

|**Target URL (item page)**
|Enter the URL that customers should be forwarded to e.g. when they use a mobile device to access an item in your online store from a price comparison portal. The item URL would then look like this: **http://mobile.yourplentystore.co.uk/?itemNumber=$itemId**. The template variable **$ItemID** in the URL provides access to every item. +
**Tip:** In the URL, the template variable **$ReferrerID** defines where customers were forwarded from. The URL would then look like this: **http://mobile.yourplentystore.co.uk/?itemNumber=$itemId&amp;referrerId=$referrerId** +
**Important:**: If you do not enter a URL here, then customers will not be forwarded to the items in your online store from price comparison portals etc.
|====

__Table 1: forwarding options for mobile devices__

== Determining what should happen in case of a 404 error

In the past, invalid URLs were not deleted from the sitemap immediately. This caused a 404 error when changes had been made to a category or item page. The page was no longer found. The sitemap function generates content for each client daily and deletes invalid entries. Only current and visible content will be included in the sitemaps. With the settings for 404 errors you determine which kind of search will be carried out as a result of such an error. The HTTP status message 301 (Moved permanently) will be sent simultaneously. Consequently, the outdated URL will be deleted from the search engines.

[TIP]
.When is an automatic search useful?
====
An automatic search is useful if the new URL contains the same or similar terms and is likely to be found easily. If this is not the case, then an automatic search can cause a soft 404 error to occur. You can use this forwarding if you usually offer similar content. We recommend that you discuss this matter with your SEO agency.
====

[.instruction]
Setting up forwarding for 404 errors:

. Go to **Settings » Client (store) » Standard » Online store » Forwarding**.
. Pay attention to the explanations given in table 2 and carry out the settings as desired.
. **Save** the settings.

[cols="a,a"]
|====
|Settings |Explanation

|**Redirect for categories**
|**Inactive** (default) = No forwarding +
**Carry out content search** = If the category URL is no longer valid, a corresponding category page will be searched for. +
**Carry out item search** = If the category URL is no longer valid, a corresponding item will be searched for. +
**Important**: If you activated this function, the **404 page** that you determined in the **Settings » Client (store) » Standard » Online store » Pages** menu will not be displayed.

|**Redirect for item pages**
|**Inactive** (default) = No forwarding +
**Carry out content search** = If the item URL is no longer valid, a corresponding category page will be searched for. +
**Carry out item search** = If the item URL is no longer valid, a corresponding item will be searched for. +
**Important**: If you activated this function, the **"Item not found" page** that you determined in the **Settings » Client (store) » Standard » Online store » Pages** menu will not be displayed.
|====

__Table 2: forwarding options for 404 errors (page not found)__

