= Entwurf-Sina2
:lang: de
include::{includedir}/_header.adoc[]
:description: Unser umfangreiches Handbuch ist ein ausführlicher Leitfaden für jeden Themenbereich Ihres plentymarkets Systems.
:position: 11

== Alles jederzeit zum Nachlesen

Unser plentymarkets Handbuch unterstützt Sie von den ersten Schritten bis zur Einrichtung komplexer Prozesse.
Die Funktionen Ihres plentymarkets System werden thematisch und menüübergreifend beschrieben.
So finden Sie z.B. alle Schritte zur Einrichtung eines Markets auf einer Seite, von A wir Artikel bis Z wie Zahlung ist jeder
Schritt erklärt und das Tempo der Einrichtung bestimmen Sie. Diese Struktur erlaubt es Ihnen eine Einrichtung jederzeit zu
unterbrechen und später fortzusetzen. Ergänzend finden Sie im Handbuch unsere Video-Tutorials, die Sie einleitend oder
zusätzlich zu den thematischen Inhalten des Handbuchs nutzen können. Die neue Themenstruktur orientiert sich an den
von plentymarkets angebotenen Modulen:

=== Den Grundstein legen

[.tileList]
* <<plentymarkets-7#,icon:seven[set=plenty]plentymarkets 7 >>
* <<arbeiten-mit-plentymarkets#,icon:plenty-p[set=plenty]Arbeiten mit plentymarkets >>
* <<datenaustausch#,icon:item[set=plenty]Artikel >>

[.row]
====
//  standard box - headline, accordion list

[.col-md-12]
=====
[.collapseBox]
=====
====

[.row]
Im Changelog erhalten Sie einen Überblick über alle Neuerungen, Änderungen und Optimierungen der aktuellen plentymarkets-Version.
Außerdem erfahren Sie, an welchen Stellen Sie die Konfiguration prüfen sollten, um die optimale Funktion zu gewährleisten.

<</#, Zum Changelog >>

