= Drucker
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Drucker, plentymarkets Client
:position: 15

Der plentymarkets Client ermöglicht die optimale Verknüpfung von plentymarkets mit lokal installierten Endgeräten. Im Menü **plentymarkets Client » Einstellungen » Grundeinstellungen » Drucker** richten Sie lokal bzw. in Ihrem Netzwerk installierte Drucker in plentymarkets ein. Den Download des plentymarkets Client finden Sie auf unserer **link:https://www.plentymarkets.eu/produkt/prozesse/plentymarkets-client/[Website]**.

[#10]
== Drucker hinzufügen

Gehen Sie wie unten beschrieben vor, um einen Drucker hinzuzufügen.

[.instruction]
Neuen Drucker hinzufügen:

. Öffnen Sie das Menü **plentymarkets Client » Einstellungen » Grundeinstellungen » Drucker**.
. Klicken Sie auf das Kontextmenü im Menübaum. +
→ Der Button **Neuer Drucker** wird eingeblendet.
. Klicken Sie auf **Neuer Drucker**. +
→ Das Konfigurationsmenü wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen. +
→ Der Drucker wird im Menübaum angezeigt.
. Drucken Sie vor dem Produktiveinsatz einige Testseiten/-etiketten und experimentieren Sie ggf. mit verschiedenen Drucker-Plugin.

.Drucker einrichten
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Testseite**
|Druckereinstellungen durch den Ausdruck einer Testseite prüfen.

|**Name**
|Name eingeben. Der Name ist frei wählbar. So lassen sich mehrere gleiche Drucker unterschiedlich benennen.

|**Drucker**
|Zeigt die Drucker, die lokal oder im Netzwerk verfügbar sind.

|**Drucker-Dialog**
|Wählen, ob der Drucker-Dialog vor dem Ausdrucken geöffnet oder nicht geöffnet werden soll. +
**öffnen**= Die Ausrichtung und weitere Angaben müssen vor jedem Druck gemacht werden. +
**nicht öffnen**= Die Ausrichtung und weitere Angaben werden in diesem Menü eingestellt und für den Druck verwendet.

|**Papierfach**
|Ein Papierfach wählen. Die verfügbare Auswahl ist abhängig vom gewählten Drucker.  +
Wenn Sie mit verschiedenen Papierformaten arbeiten, beachten Sie die Hinweise im nachfolgenden Unterkapitel.  +
**Hinweis**: Dieses Feature ist nur für Windows verfügbar.

|**Papierformat**
|Ein Papierformat wählen. Bei Wahl eines benutzerdefinierbaren Papierformats, z.B. des Papierformats **Custom**, werden Eingabefelder für die **Breite** und **Höhe** des Druckmediums eingeblendet. Die Papierformate werden vom Drucker bereitgestellt, daher können die Bezeichnungen abweichen.  +
Wenn mehrere Formate benötigt werden, richten Sie weitere Drucker ein, denen Sie die unterschiedlichen Formate zuordnen.

|**Doppelseitiger Druck**
|Wird derzeit vom Client nicht unterstützt.

|**Skalierung**
|Eine Skalierung wählen.  +
**Auf Seitengröße (Proportion nicht berücksichtigen)** = Der Ausdruck wird auf die Gesamtgröße des Druckbereichs skaliert. Diese Einstellung kann zu einer verzerrten Darstellung führen.  +
**Auf Seitengröße (Proportion berücksichtigen)** = Der Ausdruck wird innerhalb des Druckbereichs auf die größtmögliche Größe skaliert, bei der keine Verzerrung auftritt.  +
**Keine** = Der Ausdruck wird nicht skaliert.

|**Ausrichtung**
|Eine Ausrichtung wählen, um ausschließlich in einer Ausrichtung zu drucken. Die hier angezeigten Optionen stammen vom Drucker und unterscheiden sich abhängig vom Drucker.  +
**portrait** = Ausrichtung im Hochformat  +
**landscape** = Ausrichtung im Querformat  +
**Automatische Seitenausrichtung** = Diese Option befindet sich weiter unten im Menü. Sie bewirkt, dass die Ausrichtung automatisch erfolgt.

|**Oben, Unten, Links, Rechts**
|Optional Abstände in mm eingeben, um die Positionierung des Inhalts auf der Seite zu bestimmen.

|**Automatische Seitenausrichtung**
|Aktivieren, um den Seiteninhalt automatisch auf der Seite auszurichten.

|**Drucker-Plugin**
|Wählen, über welches Plugin der Drucker angesteuert werden soll. +
**__Tipp:__** Vor dem Produktiveinsatz Testseiten/-etiketten drucken, um die Druckqualität verschiedener Drucker-Plugins zu testen. +
**Standard** = Der Standard für das Betriebssystem wird verwendet. +
**Cups**, **PDFBox** = Wählen, wenn die Druckqualität mit der Option **Standard** nicht ausreicht. +
**ZPL** (Zebra Programming Language) = Plugin für Zebra-Etikettendrucker. +
**__Hinweis zum ZPL-Plugin:__** Das ZPL-Plugin ist für eine native Auflösung von 203 dpi optimiert. Bei anderen Auflösungen kann die Größe der Etiketten abweichen. Bei abweichender Etikettengröße 203 dpi wählen oder ein anderes Drucker-Plugin verwenden. +
**__Hinweis zum ZPL-Plugin:__** Für eine optimale Nutzung des ZPL-Plugins muss der Drucker unter Mac OSX über das CUPS-Webinterface im <<arbeiten-mit-plentymarkets/grundeinstellungen/drucker#65, **RAW-Modus** >> hinzugefügt werden.
|====

Erfahren Sie mehr zum Einrichten von Druckern im folgenden Videotutorial:

video::84490521[vimeo]

[#20]
== Drucker mit verschiedenen Papierfächern konfigurieren (nur Windows)

Wenn Sie über einen Drucker mit verschiedenen Papierfächern verfügen und mit verschiedenen Papierformaten arbeiten möchten, können Sie ein Druckerprofil pro Papierfach erstellen.

[TIP]
.Beispielkonfiguration für verschiedene Formate
====
Sie möchten Rechnungen im Format DIN A4 und Etiketten im Format DIN A6 drucken.

Richten Sie ein Druckerprofil mit dem Papierformat DIN A4 und ein weiteres Druckerprofil mit dem Papierformat DIN A6 ein. Wählen Sie dabei den gleichen Drucker und ordnen Sie das passende Papierfach zu.
====

[#30]
== Drucker freigeben

Druckerprofile werden benutzerabhängig auf dem Rechner gespeichert. Sie stehen also nicht für andere Benutzer eines Rechners zur Verfügung. Wenn ein Druckerprofil auch für andere Benutzer zur Verfügung stehen soll, muss das Profil freigegeben werden. Die Freigabe erfolgt auf Ihrem Rechner und nicht in plentymarkets. Wie Sie Drucker auf Ihrem Rechner freigeben, finden Sie in der Hilfe für Ihr Betriebssystem:

* Für Windows z.B. **link:http://windows.microsoft.com/de-de/windows/share-printer#1TC=windows-7[hier, window="_blank"]**
* Für Mac z.B. **link:https://support.apple.com/de-de/HT4670[hier, window="_blank"]**

[#40]
== Fehlerursachen und Fehler beheben

Die folgende Tabelle enthält Informationen zu Fehlercodes, die beim Einrichten des Druckers auftreten können.

.Fehlermeldungen im Menü **Drucker**
[cols="a,a,a,a"]
|====
|Code |Fehler |Ursache |Fehler beheben

|2000
|Unter Mac OS X: Kein CUPS Drucker gefunden.
|Kein angeschlossener Drucker verfügt über eine Netzwerkfreigabe. Diese Freigabe ist für die Druckerkommunikation über CUPS erforderlich.
|<<arbeiten-mit-plentymarkets/grundeinstellungen/drucker#30, **Drucker freigeben** >>

|2001
|Unter Mac OS X: Unbekannter CUPS Drucker.
|Unter dem angegebenen Namen konnte kein Drucker im Netzwerk gefunden werden.
|<<arbeiten-mit-plentymarkets/grundeinstellungen/drucker#30, **Drucker freigeben** >>

|2100
|Testseite konnte nicht gedruckt werden.
|Falsche Client-Version. Benötigt wird mindestens Version 121.
|link:https://www.plentymarkets.eu/produkt/prozesse/plentymarkets-client/[**Aktuellen Client herunterladen**]

|2101
|Fehler beim Drucken.
|Verschiedene Ursachen möglich.
|

|2102
|Drucker wurde nicht gefunden.
|Der Drucker ist im System nicht mehr vorhanden. Konfiguration ggf. nicht mehr korrekt.
|Neuen Drucker hinzufügen oder anderen Drucker verwenden.
|====

[#50]
== Etiketten drucken

Zum Drucken von Etiketten werden Etikettendrucker eingesetzt, die ein schnelles Ausdrucken großer Etikettenmengen ermöglichen. Dazu sind diese Drucker mit Etikettenrollen ausgestattet sowie, je nach Modell, mit einer Schneidevorrichtung. In den Einstellungen des Menüs **plentymarkets Client » Einstellungen » Grundeinstellungen » Drucker** legen Sie über die Option **Papierformat** die exakte Größe eines Etiketts fest. Sie wählen zwischen Standardformaten und einer frei konfigurierbaren Option, über die Sie benutzerdefinierte Größen hinterlegen (Tabelle 1).

Die Druckfunktionen sind mit üblichen Etikettendruckern kompatibel und wurden für Etikettendruckermodelle des Herstellers link:http://www.zebra.com[**Zebra**, window="_blank"] optimiert. Für den Einsatz als Desktop-Drucker empfehlen wir das Modell link:http://www.zebra.com/gb/en/products-services/printers/printer-type/desktop/g-series-gc.html[**Zebra GC420d**, window="_blank"].

[#60]
=== Zebra GC420d auf Ihrem Rechner installieren

Gehen Sie wie unten beschrieben vor, um das Druckermodell Zebra GC420d unter den Betriebssystemen Windows und Mac OSX zu installieren.

[.instruction]
Zebra GC420d installieren:

. Laden Sie die **link:http://www.zebra.com/gb/en/support-downloads/desktop/gx430t.html#mainpartabscontainer_999b=drivers[Zebra Setup Utilities, window="_blank"]**-Datei auf Ihren Rechner herunter.
. Installieren Sie diese Datei.
. Durchlaufen Sie den Installationsassistenten. +
→ Windows: Wählen Sie den Drucker ZDesigner GC420d. Hier ist der Druckertreiber ZPL eingestellt. +
→ Mac OSX: Stellen Sie den Druckertreiber ZPL ein. Testen Sie die Treibereinstellung für jede Etikettengröße. Um das Drucker-Plugin **ZPL** zu nutzen, konfigurieren Sie den Drucker für den <<arbeiten-mit-plentymarkets/grundeinstellungen/drucker#65, **RAW-Druck** >>.

[#65]
=== Zebra-Drucker mit ZPL-Plugin einrichten (nur Mac OSX)

Um das ZPL-Plugin unter Mac OSX optimal zu nutzen, muss der Zebra-Drucker so konfiguriert werden, dass er Druckaufträge im RAW-Format empfängt. Beim Drucken im RAW-Format werden Druckdaten in der nativen Sprache des Druckers gesendet. Dabei bleiben die Druckdaten unverändert, da der Druckertreiber des Betriebssystems umgangen wird.

Den RAW-Druck konfigurieren Sie über die CUPS-Webschnittstelle. Gehen Sie wie unten beschrieben vor, um die CUPS-Webschnittstelle zu aktivieren und die Konfiguration des Druckers vorzunehmen.

[.instruction]
ZPL-Plugin: CUPS-Webschnittstelle aktivieren (nur Mac OSX):

. Öffnen Sie mit der Tastenkombination "cmd" + "Leertaste" die Spotlight-Suche.
. Geben Sie den Begriff **Terminal** ein.
. Betätigen Sie die Eingabetaste. +
→ Das Terminal wird geöffnet.
. Geben Sie im Terminal den Befehl **sudo cupsctl WebInterface=yes** ein.
. Betätigen Sie die Eingabetaste. +
→ Sie werden aufgefordert, Ihr Passwort einzugeben.
. Geben Sie Ihr Passwort ein. +
→ Die CUPS-Webschnittstelle ist aktiviert.

[.instruction]
ZPL-Plugin: Raw-Modus für Zebra-Drucker einrichten (nur Mac OSX):

. Navigieren Sie in einem Webbrowser zu der Adresse **http://localhost:631**. +
→ Die CUPS-Webschnittstelle wird angezeigt.
. Wechseln Sie in das Tab **Administration**.
. Klicken Sie auf **Add Printer**. +
→ Sie werden aufgefordert, Ihre Benutzerdaten einzugeben.
. Geben Sie Benutzerdaten und Passwort ein. +
→ Die Seite **Add Printer** wird angezeigt.
. Wählen Sie den Zebra-Drucker aus der Liste.
. Klicken Sie auf **Continue**.
. Geben Sie einen Namen, eine Beschreibung und einen Standort für den Drucker ein.
. Markieren Sie **Share This Printer**, um den Drucker mit anderen Benutzern zu teilen.
. Klicken Sie auf **Continue**.
. Wählen Sie in der Liste **Make** die Option **Raw**.
. Klicken Sie auf **Continue**.
. Klicken Sie auf **Add Printer**.
. Lassen Sie die Einstellungen **Starting Banner** und **Ending Banner** auf **none**.
. Klicken Sie auf **Set Default Options**. +
→ Ihr Zebra-Drucker kann Druckaufträge im RAW-Format empfangen. +
**__Hinweis:__** Der Zebra-Drucker wird nicht in den Systemeinstellungen angezeigt, ist aber eingerichtet und für den Client sichtbar.
. Wählen Sie im Menü **plentymarkets Client » Einstellungen » Grundeinstellungen » Drucker** das Drucker-Plugin **ZPL**, um den Drucker hinzuzufügen.

[#70]
=== Etikettendruck konfigurieren

Die Größe und Breite Ihrer Etiketten konfigurieren Sie in plentymarkets. Fügen Sie hierfür den Etikettendrucker zur Druckerliste hinzu. Gehen Sie dazu wie unten beschrieben vor. Beispielhaft wird das Konfigurieren von Etiketten mit dem Format 104 x 150 beschrieben.

[.instruction]
Drucker mit Etikett 104 x 150 hinzufügen:

. Öffnen Sie das Menü **plentymarkets Client » Einstellungen » Grundeinstellungen » Drucker**.
. Klicken Sie auf das Kontextmenü im Menübaum. +
→ Der Button **Neuer Drucker** wird eingeblendet.
. Klicken Sie auf **Neuer Drucker**. +
→ Das Konfigurationsmenü wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie aus der Dropdown-Liste **Drucker** den Etikettendrucker.
. Wählen Sie **nicht öffnen** für den **Druckerdialog**.
. Wählen Sie **Ungültige Auswahl** für das **Papierfach**.
. Wählen Sie **Custom** für das **Papierformat**.
. Geben Sie **150** als **Papierhöhe** ein.
. Geben Sie **104** als **Papierbreite** ein.
. Lassen Sie die Option einseitig für doppelseitigen Druck.
. Wählen Sie **auf Seitengröße (Proportion nicht beachten)** für die **Skalierung**.
. Wählen Sie **Hochformat** für die **Ausrichtung**.
. **Speichern** Sie die Einstellungen.

[TIP]
.Tipp bei verschiedenen Etikettengrößen
====
Wenn Sie verschiedene Etikettengrößen verwenden, können Sie entweder die Papierhöhe und Papierbreite beim Wechsel der Etikettengröße anpassen oder pro Etikettengröße einen eigenen Drucker anlegen.
====

[#80]
=== Fehlerhaften Etikettendruck korrigieren

Wenn der Druck leicht versetzt, der Hauptteil auf dem Label jedoch erkennbar ist, empfehlen wir, die Ausrichtung über die Einstellungen **Oben**, **Links**, **Unten** und **Rechts** anzupassen.

Wenn nur ein kleiner Teil der Angaben auf dem Etikett gedruckt wird oder Ihr Etikett komplett leer bleibt, passen Sie den Druckertreiber an. Insbesondere auf Apple-Rechnern hängt der korrekte Druck häufig vom Treiber ab, aber auch bei Windows-Computern kann dies die Fehlerursache sein.  +
Für Windows empfehlen wir Ihnen, den Drucker ZDesigner GC420d mit dem Treiber ZPL zu installieren. In einigen Fällen kann aber der ZDesigner GC420d (EPL) mit dem Druckertreiber EPL bessere Druckergebnisse liefern.

Wenn das Etikett wieder korrekt gedruckt wird, legen Sie sich einen Drucker mit den korrekten Einstellungen für das Etikett an, so dass Sie die Einstellungen wiederverwenden können. Wir empfehlen dazu, den Drucker mehrfach mit verschiedenen Treibern auf Ihrem Rechner zu installieren, denn so können Sie, wenn ein Etikett nicht korrekt gedruckt wird, den Druck schnell mit einem anderen Treiber noch einmal versuchen.

Eine weitere Ursache für einen fehlerhaften Druck kann sein, dass der Prozess statt auf die Etiketteneinstellungen in plentymarkets auf die Etikettenparameter Ihres Druckers zugreift. Tragen Sie eventuell Etikettenparameter in Ihren Druckereinstellungen nach.

Ab plentymarkets 7 stehen außerdem verschiedene Drucker-Plugins zur Auswahl. Wenn Sie mit der Druckqualität nicht zufrieden sind, experimentieren Sie mit den verschiedenen Drucker-Plugins.

[#90]
== Druckverlauf anzeigen

Im Druckverlauf werden Ihre Druckaufträge der letzten Tage und Wochen angezeigt. Die Anzahl der angezeigten Druckaufträge beträgt maximal 10.000. Wenn diese Zahl überschritten wird, werden die ältesten 100 Einträge aus dem Verlauf entfernt. Die Druckaufträge werden zwischengespeichert, um sie an den Drucker weiterzuleiten. Sobald der Druckauftrag zwischengespeichert wurde, wird der Druck im Druckverlauf aufgeführt. Wenn z.B. Papier fehlt oder andere Probleme mit dem Drucker auftreten, kann es also sein, dass Druckaufträge im Verlauf stehen, die nicht gedruckt wurden.

[.instruction]
Druckverlauf anzeigen:

. Öffnen Sie das Menü **plentymarkets Client » Extras**.
. Klicken Sie auf **Druckverlauf öffnen** +
→ Der Druckverlauf wird geöffnet.

Im Druckverlauf haben Sie die Möglichkeit, Dokumente erneut zu drucken oder Druckaufträge aus dem Verlauf zu löschen. Beim Öffnen des Verlaufs werden standardmäßig 20 Einträge pro Seite angezeigt. Sie können aber auch 50 oder 100 Einträge pro Seite anzeigen. Um Aufträge zu löschen oder erneut zu drucken, markieren Sie diese Aufträge. Sie können alle Aufträge einer Seite oder einzelne Aufträge markieren.

[#100]
== Drucker löschen

Gehen Sie wie unten beschrieben vor, um einen Drucker zu löschen.

[.instruction]
Drucker löschen:

. Öffnen Sie das Menü **plentymarkets Client » Einstellungen » Grundeinstellungen » Drucker**.
. Klicken Sie auf den Drucker. +
→ Das Konfigurationsmenü wird geöffnet.
. Klicken Sie auf **Löschen**. +
→ Der Drucker wird gelöscht.

