= Content and containers
:lang: en
include::{includedir}/_header.adoc[]
:position: 20

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|Sometimes when you download a plugin, it comes with a bit of extra content. You'll need to tell plentymarkets which container it should display this content in.
|
|===
//end::einleitung[]

video::245342214[vimeo]

// tag::transkript[]
[.collapseBox]
.Transkript
--
Container. A box or jar for holding goods. Right, okay - what's that have to do with your website?

In one word - everything.

Imagine your online store is made up of a bunch of little containers. There are some at the top of the page, some at the bottom and some on the sides. And imagine that you have a bunch of different content like a PayPal icon or a slider for displaying recently viewed items.

Containers are a way to decide which content is displayed where. For example, you could put the icon in a container on the left and the slider in a container on the right. It's as easy as that!

Sometimes when you download a plugin it comes with a bit of extra content. For example, if you downloaded the PayPal plugin, then logically, it will come with a PayPal icon. All you need to do is use these checkboxes here to tell plentymarkets which container you want to display the icon in. Simply scroll through the checkboxes until you've found the right container for this piece of content.

Makes sense so far? Then let's try our hand at another example. When you install Ceres, you'll see three item lists that pop up in this menu. Now what's that all about? Well, this is an easy way to display lists of cross-selling items recently viewed items or any other items of your choice. Just like before, all you need to do is tell plentymarkets where it should display the item list.

Before saying goodbye, there's one last thing to note about item lists. Namely, you'll need to configure them in advance by opening up your Ceres plugin navigating to the configuration area and clicking on the "Item lists" tab. Here,tell plentymarkets what type of item list you'd like to make and then give your list a name.

Also, depending on which type of list you're creating, you'll either need to tell plentymarkets how many items it should display in the list which relationship the cross-selling items should have to one another or which tags you want to feature in your list.

Now that you've got the basics down, try it out for yourself and tell plentymarkets where each piece of content should be displayed.
--
//end::transkript[]