= Individualise system with plugins
:lang: en
include::{includedir}/_header.adoc[]
:position: 10
:id: 2GIX5MI

//tag::einleitung[]
[cols="2, 1" grid=none]
|===
|plentyMarketplace offers loads of different plugins such marketplace connectors, themes, templates, widgets, payment methods and more! plentymarkets as you want it!
|
|===
//end::einleitung[]

video::225255743[vimeo]

// tag::transkript[]
[.collapseBox]
.Transkript
--
plentyMarketplace - According to legend, mystical powers are imparted unto the finder of this treasure. Once you possess it, you have the power to set up and expand your system any way you like. But it almost sounds too good to be true!

And yet, this treasure is no legend and the road that takes you there is nice 'n smooth. Choose from marketplace connectors, themes, shop templates, widgets and much more! Everything to tailor your system to your specific needs! 

Each plugin comes with a user guide that gives you step-by-step instructions on how to integrate the plugin into your system. And in the event that changes were made to any of your plugins, simply check the changelog on a regular basis to stay up to speed on the current versions.

Whether its a new theme for your online store or a particular market that you want to reach - whatever plugin you choose, make sure you first check if the plugin you want requires another plugin to run successfully.

So for example, whatever marketplace export format you're working with, you will need to install the elastic export plugin. Simply click the checkout button as you would when making any online purchase and log into plentyMarketplace with the same details you use to access the service center or your contract info.

Lots of plugins are free and those that do require a fee can easily be paid via Paypal.

The "My account" area up here provides you with an overview of all the plugins you've already purchased and are ready to be installed in your system. When you open the plugin overview you'll find your plugins grouped together into so-called "sets", which are linked to your store.

Use the filter options here to find plugins that are ready to be installed. All you need to do now is click on the install button and then wait a few minutes for the process to finish. Then activate the plugin and click on the "save" icon to send your plugin out into the world. Again, this process can also take a few minutes to finish.

The overview provides you with lots of information about your plugins. For example, which version you're running and if an update is available for the plugin. And if there is, then you can easily install the update and then save this new version in your system.

Now let go and allow yourself to be enchanted by the riches! Time to explore the plentyMarketplace and create your very own El Dorado.
--
//end::transkript[]