= Entwurf_Kathrin_5
:lang: en
include::{includedir}/_header.adoc[]
:position: 0

**REST API** Class for <<_test-pages/kathrin/entwurf-kathrin-5#125, **REST calls**>> that can be assigned in the user account. REST calls are activated individually. REST API calls are not assigned to users by default. [#120]
== Activating REST API calls

In the **REST API** tab, decide which of the REST API calls the user should be allowed to edit. No API rights are assigned by default, not even for users who are assigned to the **REST API** class.

[.instruction]
Activating REST API areas:

. Go to **System » System settings » Settings » User » Accounts**.
. Open a user account.
. Click on the **Right** tab.
. Click on the **REST API** tab.
. Activate entire areas or expand areas to activate individual calls that the user should have access to.
. **Save** the settings.

== Creating an account for the plentymarkets forum

The plentymarkets is a knowledge base that keeps on growing. It already contains many solved support queries. Our developers and other plentymarkets customers will help you solve technical queries you might have. In addition, you will find tips for working with plentymarkets and can swap ideas with other plentymarkets customers. Proceed as described below to create an account for the plentymarkets forum. **Admin** class users can also create forum accounts for other users using this method.

[.instruction]
Creating an account for the plentymarkets forum:

. Go to **System » System settings » Settings » User » Accounts**.
. Click on **Open user**. +
→ The user will open in a new tab.
. In the **plentymarkets Forum** section, click on **Create account** +
→ The account will be created.

