= Neu: Nachbestellungen vornehmen
:lang: de
include::{includedir}/_header.adoc[]
:description: Erfahre, wie du mit der neuen Nachbestellung in plentymarkets arbeitest.
:keywords: Nachbestellung, Waren nachbestellen
:position: 10
:url: warenwirtschaft/nachbestellungen-verwalten/nachbestellungen-vornehmen

Im Menü *Waren » Bestellwesen* nimmst du nicht nur <<warenwirtschaft/umbuchungen-vornehmen#, Umbuchungen>> vor, sondern legst auch Nachbestellungen an. Über Nachbestellungen bildest du die Bestellung von Waren bei deinen Lieferanten ab.

Eine Nachbestellung gliedert sich in folgende Arbeitsschritte:

* <<#700, Varianten zur Nachbestellung identifizieren>>
* <<#800, Nachbestellung anlegen>>
* <<#900, Auftragspositionen hinzufügen>>
* <<#1000, Nachbestellung an den Lieferanten übermitteln>>
* <<#1100, Waren einbuchen>>
* <<#1200, Nachbestellung abschließen>>

Vor dem Anlegen der ersten Nachbestellungen solltest du einige vorbereitende Einstellungen vornehmen.

[#100]
== Vorbereitende Einstellungen
Die folgenden Kapitel beschreiben einige vorbereitende Einstellungen, die du vor dem Anlegen einer Nachbestellung vornehmen solltest. In der Regel sind diese Einstellungen nur einmalig notwendig. Richte den Meldebestand den Bestellmengenvorschlag ein, um festzulegen, wann Artikel nachbestellt werden sollen. Erstelle neue Auftragsstatus speziell für die Nachbestellungen und lege Tags an, um dir die Übersicht zu erleichtern. Verpflichtend ist zudem die Einrichtung einer Dokumentenvorlage für das Dokument *Nachbestellung*.

[#200]
=== Meldebestand und Bestellmengenvorschlag festlegen

Vor dem Anlegen der ersten Nachstellung solltest du die Einstellungen zum Meldebestand und zum Abverkaufszeitraum vornehmen. So legst du fest, ab welchem Restbestand Artikel nachbestellt werden

[.instruction]
Meldebestand und Bestellmengenvorschlag festlegen:

. Öffne das Menü *System » Systemeinstellungen » Waren » Bestellwesen » Nachbestellung » Einstellungen*.
. Nimm die Einstellungen anhand der Informationen in <<tabelle-meldebestand-bestellvorschlag-nachbestellung>> vor.
. *Speichere* die Einstellungen.

[[tabelle-meldebestand-bestellvorschlag-nachbestellung]]
.Vorbereitende Einstellungen für das Bestellwesen
[cols="1,3"]
|====

|Einstellung |Erläuterung

|*Standard-Status*
|Wähle einen Standard-Status, der beim Anlegen einer Nachbestellung vorausgewählt sein soll. Wie du spezielle Status für Nachbestellungen anlegst, erfährst du im Kapitel <<#300, Status für Nachbestellungen anlegen>>.

|*Standard-Eigner*
|Wähle eine der verfügbaren Optionen aus. +
*Aktiver Benutzer vorausgewählt*: Der Benutzer, der die Nachbestellung im plentymarkets Backend anlegt, wird im Feld *Eigner* vorausgewählt. +
*Kein Eigner vorausgewählt*: Bei dieser Auswahl bleibt das Feld *Eigner* beim Anlegen einer Nachbestellung leer.

|*Abverkaufszeitraum*
|Einen Zeitraum wählen. Der Zeitraum gibt vor, welcher Zeitraum für die Berechnung des durchschnittlichen Abverkaufs berücksichtigt wird. Dieser Durchschnittsverkauf fließt in die Berechnung des Nachbestellungsvorschlags von Varianten ein. Der Nachbestellungsvorschlag wird dir im Menü *Waren » Warenbestände* für die einzelnen Varianten angezeigt.

|*Voreingetragener Wert für Meldebestand/Bestellmenge*
a|Diese Einstellung bestimmt, wie die Bestellmenge im Nachbestellungsvorschlag berechnet wird. +
Du kannst wählen zwischen: +
*Meldebestand - Nettobestand - bestellte Menge* oder +
*(Meldebestand - Nettobestand - bestellte Menge) + (Durchschnittsverbrauch * (Wiederbeschaffungszeit + Lagerreichweite))* +
 +
Berechnungsparameter für den Bestellmengenvorschlag:

* *Meldebestand* = Bestandsmenge, bei der nachbestellt werden soll. Du kannst entweder einen <<warenwirtschaft/nachbestellungen-verwalten#500, statischen oder einen dynamischen Meldebestand>> einstellen.
* *Nettobestand* = Verkaufbare Menge des Lagerbestands.
* *Bestellte Menge* = Bereits nachbestellt, aber noch nicht geliefert.
* *Durchschnittsverbrauch* = Tagesdurchschnittsverkaufsmenge. Den Zeitraum, der zum Ermitteln des Tagesdurchschnitts verwendet wird, legst du mit dem Abverkaufszeitraum fest.
* *Wiederbeschaffungszeit* = Lieferzeit eines Lieferanten. In einer Variante im Tab *Lieferant* wird die Lieferzeit in Tagen eingetragen.
* *Lagerreichweite* = Eingetragene Lagerreichweite. Die Lagerreichweite wird pro Variante und Lager im Tab *Lager* einer Variante eingetragen und stellt einen Reichweitenwunsch dar, anhand dessen der Bestellmengenvorschlag ermittelt wird.

|====

[#300]
=== Status für Nachbestellungen anlegen
In deinem plentymarkets System sind bestimmte Auftragsstatus voreingestellt. Diese voreingestellten Status stehen dir auch für die Nachbestellungen zur Verfügung. Du kannst aber auch beliebig viele individuelle Status für verschiedene Verwendungszwecke anlegen. Das Anlegen neuer Status wird im dazugehörigen Kapitel auf der Handbuchseite <<auftraege/auftraege-verwalten#1200, Aufträge verwalten>> beschrieben.

[TIP]
.Eigene Status für Nachbestellungen anlegen
====
Wir empfehlen, separate Status anzulegen, die du ausschließlich für den Auftragstyp *Nachbestellung* nutzt. Stelle sicher, dass sich mittels unterschiedlicher Namensgebung die Status der Nachbestellungen von den Status der weiteren Auftragstypen unterscheiden.
====

[#400]
=== Tags für Nachbestellungen anlegen
Tags sind Kennzeichnungen, die du zentral in deinem plentymarkets System anlegst und anschließend für verschiedene Bereiche nutzen kannst. Möchtest du Nachbestellungen mit Tags versehen, musst du diese Tags zuvor im Menü *System » Systemeinstellungen » Einstellungen » Tags* anlegen. Folge der Anleitung auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/tags#, Tags verwalten>>.

[#500]
=== Dokument Nachbestellung einrichten
Für die Nachbestellung wird der speziell dafür vorgesehene Dokumententyp *Nachbestellung* genutzt. Dieses Dokument enthält alle nachzubestellenden Artikel und wird von dir als Händler an deinen Lieferanten übermittelt.

[WARNING]
.Dokumentenvorlage muss eingerichtet sein
====
Vor der erstmaligen Nutzung des Dokumens *Nachbestellung* muss zwingend die Dokumentenvorlage eingestellt werden. Solange keine Vorlage eingerichtet wurde, kann das Nachbestellungsdokument nicht erzeugt werden.
====

Im Folgenden wird beschrieben, wie du die einfache Standard-Vorlage übernimmst, die in deinem plentymarkets System bereits hinterlegt ist.

[.instruction]
Dokumentenvorlage für das Dokument *Nachbestellung* einrichten:

. Öffne das Menü *System » Systemeinstellungen » Waren » Bestellwesen » Nachbestellung » Dokumente » Nachbestellung*.
. Öffne das Tab *Transfer*.
. Wähle über dem Tab-Titel die Sprache.
. Klicke im Bereich *Einstellungen aus Standard-Dokumentenvorlage* auf *Übernehmen*. +
→ Die Standard-Einstellungen werden auf das Dokument angewendet.

Möchtest du das Dokument *Nachbestellung* individueller gestalten, das Logo deiner Firma oder zusätzliche Informationen darauf abbilden, gehe analog zu den Anleitungen auf der Handbuchseite zum Thema <<auftraege/auftragsdokumente#300, Auftragsdokumente>> vor.

[#600]
=== Versand der Nachbestellung vorbereiten
Nachdem du im vorherigen Schritt die Dokumentenvorlage für die Nachbestellung eingerichtet hast, solltest du im Folgenden noch Einstellungen zum Versand des Dokuments vornehmen, damit dein Lieferant die Nachbestellung auch erhält. Hierfür richtest du zunächst eine E-Mail-Vorlage ein, die den Bestellschein als PDF-Anhang enthält.

[.instruction]
E-Mail-Vorlage einrichten:

. Öffne das Menü *System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Vorlagen*.
. Klicke auf *Neue E-Mail-Vorlage*.
. Trage einen Namen ein, z.B. "Bestellschein an Lieferant".
. Wähle die oder den Eigner aus, für den oder die die E-Mail-Vorlage verfügbar sein soll.
. *Speichere* die Einstellungen.
. Wähle aus der Dropdown-Liste *PDF-Anhang* die Option *Nachbestellung (PDF)*.
. Wechsle in das Tab *E-Mail-Nachricht*.
. Trage einen Betreff ein.
. Trage den Text ein, den die E-Mail-Vorlage enthalten soll.
. *Speichere* die Einstellungen.

Im zweiten Schritt kannst du den Versand der Nachbestellung an den Lieferanten automatisieren. So wird direkt nach dem Erzeugen des Bestellscheins das Dokument automatisch per E-Mail an deinen Lieferanten gesendet.

Richte dir dazu die folgende Ereignisaktion ein.

[.collapseBox]
.Senden des Bestellscheins an Lieferanten automatisieren:
--
. Öffne das Menü **System » Systemeinstellungen » Waren » Bestellwesen » Ereignisse**.
. Klicke auf **Ereignisaktion hinzufügen**.  +
→ Das Fenster **Neue Ereignisaktion erstellen** wird geöffnet.
. Gib einen Namen ein.
. Wähle das **Ereignis** gemäß <<tabelle-ereignisaktion-bestellschein-an-lieferant>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-bestellschein-an-lieferant>> vor.
. Setze ein Häkchen bei **Aktiv**.
. *Speichere* die Einstellungen.
--
[[tabelle-ereignisaktion-bestellschein-an-lieferant]]
.Ereignisaktion zum automatischen Senden eines Bestellscheins an Lieferanten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Bestellwesen > Nachbestellungsdokument generiert*
|

|*Filter*
|*Auftragstyp > Bestellung, Typ Nachbestellung*

|*Aktion*
|*E-Mail versenden > Eigene Vorlage "Bestellschein an Lieferant"*
|
|====

[#700]
=== Meldebestand einer Variante festlegen
Möchtest du zuverlässig benachrichtigt werden, sobald es Zeit wird, einzelne Varianten nachzubestellen, solltest du in deinem plentymarkets System für jede Variante einen Meldebestand pflegen. Der Meldebestand zeigt an, bei welcher Menge einer Variante eine Nachbestellung veranlasst werden sollte.

[TIP]
.Lager hinzufügen, um Meldebestand einzutragen
====
Ein statischer Meldebestand lässt sich nur eingeben, wenn der Variante ein Lager zugeordnet ist. Wenn kein Lager zugeordnet ist, füge zunächst das Lager hinzu.
====

[.instruction]
Statischen Meldebestand eintragen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Lager*.
. Trage eine Menge unter *Meldebestand* ein.
. *Speichere* die Einstellung.

[TIP]
.Artikel, die den Meldebestand unterschreiten, direkt auf der Startseite anzeigen
====
Auf der Startseite deines Systems kanst du anzeigen, wie viele Varianten eines Lagers den Meldebestand unterschritten haben. Füge dafür das Element *Artikel unter Meldebestand* hinzu. Ein Klick auf die Anzahl der Varianten öffnet das Menü *Waren » Warenbestände* und filtert nach Varianten unter Meldebestand.
====

[#dynamischerMeldebestand.subhead]
Aktuelle Umsetzung des dynamischen Meldebestand

Pro Lager kannst du entscheiden, ob du den dynamischen Meldebestand nutzt oder nicht. Wenn du den dynamischen Meldebestand nutzen, berechnet dein System den dynamischen Meldebestand jede Nacht im Hintergrund. Dieser berechnete dynamische Meldebestand wird noch in keinem Feld dargestellt, d.h. Sie sehen den Wert nicht. Die Differenz zum Meldebestand, MeldΔ, basiert jedoch auf dem berechneten Meldebestand. Die Differenz wird Ihnen z.B. in der Bestandsübersicht angezeigt. So können Sie anhand der Differenz absehen wann eine Nachbestellung erfolgen sollte.

[IMPORTANT]
.Wenn dynamischer Meldebestand genutzt wird, keinen statischen Meldebestand pflegen
====
Wenn du den dynamischen Meldebestand nutzt, darfst du manuell keinen statischen Meldebestand eintragen. Belasse den Meldebestand für die Varianten in dem Lager auf 0. Wenn ein Meldebestand größer als 0 gespeichert ist, wird die Berechnung des dynamischen Meldebestands nicht ausgeführt.
====

Der dynamische Meldebestand wird jede Nacht anhand der folgenden Formel berechnet:

latexmath:[\mbox{Dynamischer Meldebestand} = {(\mbox{Ø Abverkauf} \cdot \mbox{Lagerreichweite}) + (\mbox{Ø Abverkauf} \cdot \mbox{kürzeste Lieferzeit})}]

Erläuterung der Formelparameter:

* Ø Abverkauf = durschnittlich verkaufte Menge
* kürzeste Lieferzeit = kürzeste Lieferzeit einer Variante egal von welchem Lieferanten

Die Differenz zum dynamischen Meldebestand (MeldΔ) wird im System dargestellt und berechnet sich folgendermaßen:

latexmath:[\mbox{MeldΔ} = {(\mbox{dynamischer Meldebestand} - (\mbox{Nettobestand} + (\mbox{nachbestellte Menge})}]

Die Einstellung für den dynamischen Meldebestand triffst du für jedes Lager in den <<warenwirtschaft/lager-einrichten#300, Lagereinstellungen>>.

[#800]
=== Mindestabnahme einer Variante festlegen

Die Mindestabnahme ist die Menge, die du deinem Lieferanten mindestens abnehmen musst, wenn du bei ihm bestellst. Wenn du eine Mindestabnahme für eine Variante einträgst, entspricht der Bestellmengenvorschlag für die Variante mindestens dieser Mindestabnahme. Ein Bestellmengenvorschlag wird wiederum nur angezeigt, wenn der Meldebestand erreicht wurde.

[TIP]
.Lieferant hinzufügen, um Mindestabnahme einzutragen
====
Eine Mindestabnahme lässt sich nur eingeben, wenn der Variante ein Lieferant zugeordnet ist. Wenn kein Lieferant zugeordnet ist, fügen Sie zunächst den Lieferanten hinzu.
====

[.instruction]
Mindestabnahme festlegen:

. Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Lieferant*.
. Trage eine Menge unter Mindestabnahme ein.
. *Speichere* die Einstellung.

Wenn weder eine Mindestabnahme noch ein Meldebestand für eine Variante eingetragen ist, beträgt der Vorschlag 0.

[#900]
== Varianten für die Nachbestellung identifizieren
Für eine gut funktionierende Warenwirtschaft ist es wichtig, nachzubestellende Varianten zeitnah zu ermitteln. So vermeidest du, dass dir Artikel ausgehen und verhinderst somit unnötig lange Lieferzeiten bei deinen Kunden.

Am einfachsten erkennst du nachzubestellende Varianten daran, dass sie den Meldebestand erreicht haben. Arbeitest du nicht mit dem Meldebestand, kannst du alternativ nach dem Netto-Warenbestand filtern.

[.instruction]
Varianten für die Nachbestellung identifizieren:

. Öffne das Menü *Waren » Warenbestände*.
. Wähle für den Filter *Beschränkung* die Option *Meldebestand erreicht/unterschritten*. +
*_Alternativ_*: Wähle die Option *Negativer Netto-Warenbestand oder Netto-Warenbestand gleich 0*, wenn du den Meldebestand nicht nutzt.
. Wähle optional ein Lager.
. Klicke auf *Suchen*. +
→ Eine Liste mit Artikeln, die nachbestellt werden sollten, erscheint.

[#1000]
== Nachbestellung anlegen
Im Folgenden wird beispielhaft beschrieben, wie du eine Nachbestellung für Artikel anlegst, die den Meldebestand unterschritten haben.


////
Kapitel 7 der alten HBS: Stimmt auch noch so.
Im Menü Waren > Warenbestände kann man durch den Button "Bestellung erstellen" eine komplett neue Nachbestellung erstellen. Oder wenn bereits eine OFFENE Nachbestellung zu dem Lieferanten existiert, werden die Mengen dort hinzugefügt.

Kapitel 8.2 kann genau so übernommen werden. Bestand der nachbestellt wird wird direkt dem Auftrag zugeordnet aus dem Heraus die Nachbestellung angelegt wurde. Das ist in der Nachbestellung in der Tabelle Auftragspositionen am Einkaufswagen vor der Variante sichtbar. Klick auf den Einkaufswagen zeigt im Tooltip die Auftrags ID an aus dem nachbestellt wurde. Bei Klick wird der Auftrag (Tab: Übersicht) geöffnet.

Kapitel 8.3 kann genauso übernommen werden. Allerdings fehlt hier noch eine Info dass die Nachbestellung auch abgeschickt werden muss - das passiert dann in unserer neuen UI (Nachbestellung öffnen und Bestelldatum setzen und an den Lieferanten schicken)

Kapitel 11: dafür haben wir in der UI neue Funktionen. Nach Anlegen der Warenbewegungen kann man über "Alle Warenbewegungen buchen" alle Artikel für die man davor die Warenbewegungen erstellt hat gleichzeitig einbuchen.

Kapitel 12: Stornieren in diesem Sinne ist nicht möglich. Aber wenn man eine Nachbestellung abschließt (Abschlussdatum setzen) werden die Artikel, die nicht eingebucht sind, aus dem Zulauf entfernt.

Kapitel 14: geht noch, aber in unserem neuen Menü

Button "Lieferdatum ermitteln": Wenn man im Tab Lieferant der Variante das Feld "Lieferzeit in Tagen" ausgefüllt hat, ermittelt diese Funktion ein ungefähres Lieferdatum für die Nachbestellung als Ganzes.
////
