= Nachbestellungen in Arbeitsschritte gliedern
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Nachbestellung, Bestellung, Lieferant, nachbestellen
:position: 10
:url: warenwirtschaft/nachbestellungen-verwalten/nachbestellungen-in-arbeitsschritte-gliedern

Verbinden Sie das Ticketsystem mit Ihren Nachbestellungen und bilden Sie Ihre Arbeitsschritte bei einer Nachbestellung in Ihrem System ab.
Hierfür erstellen Sie Ticketvorlagen, in denen Sie Arbeitsschritte anlegen.
Bis zu 30 Arbeitsschritte sind je Vorlage möglich.
Im Ticket können Sie die Kommunikation und den Fortschritt während eines Arbeitsschritts verfolgen und andere Benutzer einbinden.
Die Bestellung führen Sie erst dann aus, wenn alle Schritte bearbeitet bzw. geklärt sind.

[IMPORTANT]
.**Beispiel: Wann ist die Unterteilung in Arbeitsschritte sinnvoll?**
====
Für bei einem Hersteller bestellte Schuhe, die speziell gefertigt werden müssen, ist zunächst die Erstellung eines **Musters** nötig. Die Erstellung des Musters wird als erster **Arbeitsschritt** angelegt (siehe weiter unten für die Erläuterung der Arbeitsschritte). Anhand des Musters werden die **Materialkosten** berechnet. Dies stellt den zweiten Arbeitsschritt dar. Für die weiteren Arbeiten werden jeweils weitere Arbeitsschritte erstellt und Zeiträume festgelegt. Die Bestellung wird erst dann ausgeführt, wenn alle Schritte bearbeitet bzw. abgeschlossen sind.
====

[#100]
== Vorlage mit Arbeitschritten einrichten

Erfahren Sie mehr zur Funktionsweise von Vorlagen im Bestellwesen im folgenden Videotutorial:

video::89354998[vimeo]
[#200]
=== Vorlage erstellen

Gehen Sie wie nachfolgend beschrieben vor, um eine neue Vorlage einzurichten.

[.instruction]
Vorlage einrichten:

. Öffnen Sie das Menü **System » Systemeinstellungen » Waren » Bestellwesen » Vorlagen**.
. Klicken Sie auf **Neue Vorlage**. +
→ Ein neues **Fenster** öffnet sich.
. Tragen Sie einen **Namen** für die Vorlage ein.
. **Speichern** Sie die Einstellungen. +
→ Die Vorlage erhält eine ID und wird der Auswahl im Tab **Vorlagen** hinzugefügt.

[#300]
=== Arbeitsschritt der Vorlage hinzufügen

Sie können in diesem Menü pro Vorlage bis zu **30 Arbeitsschritte** erstellen.
Aus den Arbeitsschritten einer Vorlage können Sie dann Tickets für eine Nachbestellung erzeugen.
Dafür gibt es das Tab **Ticket** im Bearbeitungsmenü einer Nachbestellung.

Gehen Sie wie nachfolgend beschrieben vor, um einen Arbeitsschritt anzulegen.

[.instruction]
Arbeitsschritt erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Waren » Bestellwesen » Vorlagen**.
. Klicken Sie auf eine **Vorlage**, um diese zu öffnen.
. Klicken Sie auf die Schaltfläche **Neuer Schritt**. +
→ Ein neues **Fenster** öffnet sich.
. Nehmen Sie die **Einstellungen** vor. Beachten Sie dabei die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen.

.Einstellungen zu Vorlagen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Titel**
|Titel für einen Arbeitsschritt eintragen. +
Sie können den Titel erweitern, indem Sie ein **Suffix** anhängen oder ein **Präfix** voranstellen. Sie können auch beide Einstellungen nutzen. Mithilfe der Einstellungen können Sie auf einen Blick erkennen, zu welcher **Nachbestellung** oder welchem **Kunden** der Arbeitsschritt gehört.

|**Suffix**
|Zwischen den Optionen **Nachbestellungs-ID**, **Auftragsdatum** und **Kundenname** wählen, um Informationen an den Titel anzuhängen.

|**Präfix**
|Zwischen den Optionen **Nachbestellungs-ID**, **Auftragsdatum** und **Kundenname** wählen, um dem Titel Informationen voranzustellen.

|**Position**
|Eine Position pro Arbeitsschritt wählen, um die Reihenfolge der Arbeitsschritte in der Auflistung festzulegen.

|**Zieltermin**
|Zeitraum in Tagen eintragen. Daraus wird der Zieltermin für die Erledigung des Arbeitsschrittes errechnet.

|**Eigner**
|Hier stehen alle für das Ticketsystem berechtigte Benutzer als Eigner zur Verfügung. Einen Eigner für den Auftragsschritt wählen. Der Eigner wird automatisch und standardmäßig im Ticket hinzugefügt. Sie können im Ticket direkt aber auch weitere Eigner hinzufügen.

|**Rolle**
|Rolle des Eigners wählen. Rollen für das Ticketsystem richten Sie im Menü **System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen.** ein.

|**Typ**
|Typ wählen.  Tickettypen erstellen Sie im Menü **System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen**

|**Status**
|Status wählen. Ticketstatus sind tickettypabhängig und werden im Menü **System » Systemeinstellungen » CRM » Ticketsystem » Einstellungen** erstellt.

|**Vertraulich**
|**Ja** oder **Nein** wählen.  +
**Ja** = Der Arbeitsschritt ist vertraulich und nur Kommentare können geschrieben werden. Nachrichten sind nicht möglich.  +
**Nein** = Der Arbeitsschritt ist nicht vertraulich und sowohl Kommentare als auch Nachrichten können geschrieben werden.

|**Nachricht**
|Nachrichten dienen der internen und externen Kommunikation, d.h. der Kommunikation mit Kunden, Lieferanten etc. Sie können damit Informationen zu einem Arbeitsschritt oder einen Stand sowie Hinweise weitergeben. Eine Nachricht wird immer auch als E-Mail an die Ticketeigner geschickt.
Allerdings muss dafür im Benutzerkonto des Eigners eine <<basics/admin-aufgaben/benutzer-verwalten#30, E-Mail-Adresse>> gespeichert sein.

|**Kommentar**
|Kommentare dienen der internen Kommunikation und sind für Kunden und Lieferanten nicht sichtbar.
|====

[#400]
== Arbeitsschritte in der Nachbestellung nutzen

Alle Arbeitsschritte einer Vorlage werden als Tickets angelegt, sobald **Ticket aus Vorlage erzeugen** genutzt wird. Anschließend können Sie die erzeugten Tickets bearbeiten und Nachrichten oder Kommentare verfassen.

[TIP]
.Nur eine Arbeitsschrittvorlage pro Nachbestellung nutzbar
====
In einer Nachbestellung können nur einmal Arbeitsschritte aus einer Vorlage erzeugt werden. Wenn der Schritt einmal ausgeführt wurde, kann er nicht mit einer zweiten Vorlage wiederholt werden.
====

[#500]
=== Tickets für Arbeitsschritte erzeugen

Gehen Sie wie nachfolgend beschrieben vor, um Tickets für Arbeitsschritte zu erzeugen. Der Lieferant der Nachbestellung wird automatisch im Ticket verknüpft.

[.instruction]
Tickets für Arbeitsschritte erzeugen:

. Öffnen Sie das Menü **Waren » Bestellwesen » Nachbestellungen**.
. Öffnen Sie eine Nachbestellung oder legen Sie eine neue an.
. Wechseln Sie in das Tab **Tickets**.
. Wählen Sie eine **Ticketvorlage** aus der Dropdown-Liste.
. Klicken Sie auf **Ticket erzeugen**. +
→ Pro Schritt in der Vorlage wird ein Ticket erzeugt.

Die angelegten Tickets erhalten eine Ticket-ID und werden anhand dieser ID aufgelistet. Die ID wird anhand der Reihenfolge vergeben, in der die Schritte erstellt wurden. Im Ticket wird auch die Nachbestellungs-ID angezeigt, z.B. RO1234. RO steht hierbei für Reorder, also Nachbestellung. So erkennen Sie, wenn Sie ein Ticket über das Ticketsystem öffnen, ebenfalls, dass das Ticket zu einer Nachbestellung gehört.

[IMPORTANT]
.Schritte ergänzen
====
Wenn später neue Schritte in einer Vorlage hinzugefügt werden, werden in der Nachbestellung nachträglich keine neuen Tickets erzeugt.
====

[#600]
=== Tickets bearbeiten

In einem Ticket werden Kommentare und Nachrichten ausgetauscht. Im Tab **Anhang** können Dateien angehängt werden. Wird eine Nachricht gespeichert, wird diese als E-Mail direkt an den verknüpften Lieferanten geschickt. Antwortet der Lieferant auf die E-Mail, erscheint die Antwort ebenfalls als Nachricht im Ticket. Ein Kommentar ist hingegen eine interne Nachricht, die nicht an den Lieferanten geschickt wird.

Weiterhin wird die Bearbeitung der Tickets durch Status dokumentiert. Die Status sind dabei abhängig vom Typ des Tickets. Die Tickettypen und Status erlauben so, Tickets für Arbeitsschritte anders einzurichten als z.B. eine Kundensupportanfrage bei einer Webshop-Bestellung.

Den E-Mail-Abruf, Tickettypen und Status richten Sie im Menü <<crm/ticketsystem-nutzen#, System » Systemeinstellungen » CRM » Ticketsystem>> ein.

[#700]
== Vorlage suchen

Für die Suche nach Vorlagen stehen Ihnen Filter zur Vefügung. Gehen Sie wie nachfolgend beschrieben vor, um eine Vorlage zu suchen.

[.instruction]
Vorlage suchen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Waren » Bestellwesen » Vorlagen**.
. Geben Sie die **ID**, den **Namen** oder das **Erstellungsdatum** der Vorlage im Tab **Filter** ein.
. Klicken Sie auf **Suchen**. +
→ Die Ergebnisse werden im Tab **Vorlagen** angezeigt.
