= Rückstandsliste verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zulauf, Rückstandsliste, Retouren, Ausstehende Bestellungen
:position: 20
:url: warenwirtschaft/nachbestellungen-verwalten/rueckstandsliste-verwalten

In den Rückstandslisten finden Sie Artikel, die nachbestellt, aber noch nicht eingebucht wurden, also noch ausstehend sind. Außerdem erfahren Sie hier, wo Sie nachschauen können, welche Artikel aus Retouren gerade auf dem Rückweg an Sie sein sollten.

[#100]
== Ausstehende Artikel suchen

Sie haben die Möglichkeit, ganz allgemein nach ausstehenden Artikeln zu suchen oder nach Artikeln zu suchen, die direkt in einem Auftrag nachbestellt wurden und noch ausstehend sind. Hierfür gibt es zwei separate Menüs.

[#200]
=== Allgemein suchen

Im Menü **Waren » Bestellwesen » Rückstandsliste** werden Artikel aufgelistet, die **<<warenwirtschaft/nachbestellungen-verwalten#, nachbestellt>>** sind, für die aber noch kein Wareneingang gebucht wurde. Beim Öffnen des Menüs wird nicht automatisch eine Suche ausgeführt. Standardmäßig ist die Suche nicht eingeschränkt, d.h. wenn Sie eine Suche mit den Standardeinstellungen ausführen, werden alle ausstehenden Artikel gesucht, egal aus welchem Lager und egal wann die Nachbestellung angelegt wurde. Um die Suche einzuschränken, stellen Sie Filter ein.

[.instruction]
Ausstehende Artikel suchen:

. Öffnen Sie das Menü **Waren » Bestellwesen » Rückstandsliste**.
. Wählen Sie Filter für Ihre Suche. Beachten Sie dazu die Erläuterungen in Tabelle 1.
. Klicken Sie auf **Suchen**, um ausstehende Artikel zu suchen.

.Filter für die Suche nach ausstehenden Artikeln
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**ID-Auswahl**
|**ALLE IDs** oder eine der Einschränkungen **Nur Auftrags-ID**, **Nur Artikel-ID**, **Nur Zeichen** aus der Dropdown-Liste wählen. In das Eingabefeld rechts daneben eingetragene Werte beziehen sich auf diese Auswahl. Es werden entsprechend nur Suchergebnisse gezeigt, die zu dieser Kombination passen.

|**Artikeldaten**
|Eingabefeld zur Suche anhand von Daten, die im Artikel gespeichert sind.

|**Lager**
|**ALLE** oder eines der in Ihrem System angelegten Lager wählen.

|**Sortierung**
|Reihenfolge wählen, in der die Suchergebnisse angezeigt werden.

|**Limit**
|Anzahl der höchstens angezeigten Suchergebnisse.

|**Eigner**
|**ALLE** oder einen der in Ihrem System angelegten Eigner wählen.

|**Lieferant**
|**ALLE** oder einen der in Ihrem System angelegten Lieferanten wählen.

|**Datum**
|Bei Auswahl einer der drei Optionen **Liefertermin**, **Zahlungstermin** oder **Kalenderwoche** erscheinen Eingabefelder, mit denen der Zeitraum der Suche eingegrenzt wird.

|**Markierung**
|**ALLE**, **KEINE** oder eine der aufgelisteten Markierungen wählen.
|====

Nachdem Sie eine Suche durchgeführt haben, können Sie in der Liste der Suchergebnisse sowohl den ausstehenden Artikel öffnen als auch die Nachbestellungen, in denen der Artikel enthalten ist.

Durch einen Klick auf das kleine **Plus** in der Zeile eines Ergebnisses wird das Suchergebnis aufgeklappt und Sie sehen, in welchen Nachbestellungen der Artikel enthalten ist. Ein Klick auf die ID einer Nachbestellung genügt, um die Nachbestellung zu öffnen. Ein Klick auf die Artikel-ID öffnet den Artikel.

[#300]
=== Auftragsbezogen suchen

Auftragsbezogen heißt, dass die Nachbestellung, in der die Artikel bestellt wurden, direkt in einem Auftrag angelegt wurde. Beim Öffnen des Menüs wird standardmäßig eine Suche ausgeführt. Zum Einschränken der Suche sind Filter vorhanden.

[.instruction]
Auftragsbezogen suchen:

. Öffnen Sie das Menü **Waren » Bestellwesen » Auftragsbezogene Rückstandsliste**.
. Wählen Sie Filter für die Suche.
. Klicken Sie auf **Suchen**.

In der Ergebnisliste werden die ausstehenden Artikel aufsteigend nach Artikel-ID sortiert. Den Artikel, die Nachbestellung sowie den Kunden öffnen Sie durch einen Klick auf die ID in der Ergebnisliste. In der nachfolgenden Tabelle finden Sie einige Erläuterungen zu den Informationen im Suchergebnis.

[TIP]
.Aufträge werden automatisch auf Status 5 gesetzt, wenn in der auftragsbezogenen Nachbestellung die Artikel eingebucht werden
====
Wenn Sie die Nachbestellung öffnen, in der die ausstehenden Artikel bestellt wurden und den Wareneingang über die Nachbestellung buchen, wird der Auftrag automatisch auf Status 5 gesetzt.
====

.Spalten Ergebnisliste
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Menge**
|Zeigt in zwei Zeilen die nachbestellte Menge und die im Auftrag bestellte Menge. In beiden Zeilen werden jeweils die bereits gelieferte Menge, die noch ausstehende Menge und die insgesamt bestellte Menge angezeigt. Die gelieferte Menge in der unteren Zeile zeigt, wie viele Artikel bereits an den Kunden geliefert wurden.  +
obere Zeile = Nachbestellung
untere Zeile = Auftrag

|**DiffMenge**
|Differenz zwischen der Menge, die im Auftrag bestellt wurde, und der beim Lieferanten nachbestellten Menge.
|====

[#400]
== Zulauf aus Retouren auflisten

Für die Übersicht, welche Artikel demnächst durch Retouren wieder zurückkommen, gibt es ein separates Menü. Beim Öffnen des Menüs **Waren » Retouren » Zulauf** wird automatisch eine Suche ausgeführt. Die Ergebnisse werden absteigend anhand des Anlagedatums der Retoure sortiert. Artikel aus der jüngsten Retoure stehen oben.

