= ItemCategories
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Data format
:description: Data format ItemCategories
:position: 130

**Data » Dynamic export** and **Data import » Dynamic import**

== General information about the data format ItemCategories

The data format **ItemCategories** is used for exchanging data about your items' category links. It is used for both exporting and importing data. You can also use the data format **<<basics/data-exchange/data-formats/item#, Item>>** to edit category links via data exchange. However, the data format **ItemCategories** is especially well suited for creating or editing multiple links per item.

For example, use the format **ItemCategories** to assign category links to newly imported items. Once you have imported the new items, export the category links for your items. Open the CSV file and save values for the category links that you want to assign to newly imported items. Pay attention to the explanations given in table 1. The table lists the correct notation for the IDs.

== Important notes

By using the field **DeleteOld** with the value **1**, it is possible to delete old category links during the import (table 1). If you entered several category links per item and these category links are all in different lines, then only enter the value 1 into the first line (see table 1).

[WARNING]
.Spell the field names correctly!
====
Pay close attention to the exact spelling of the data fields (upper/lower case letters). The data can not be processed if the data field is spelled incorrectly.
====

== Overview of the data fields

The following table explains the data fields for the data format **ItemCategories**. The data fields are listed in alphabetical order:

[cols="a,a,a"]
|====
|Field |Explanation |Filter options (tab: Filter)

|**Categories**
|Categories +
Category IDs are separated with commas. Use hyphens to enter the IDs for category paths.
|

|**CategoryBranches**
|The IDs of the category branches +
Use commas to separate these IDs. +
If you have multiple category links per item, then it is also possible to save each category link in a different line.
|

|**CategoryName**
|Category names +
The names of different categories are separated by commas. Use a greater than symbol to enter path names.
|

|**CategoryNameLang**
|The language of the category names
|

|**DeleteOld**
|Delete old category links +
**0** = No +
**1** = Yes +
**__Important__**: If you entered several category links per item and these category links are all in different lines, then only enter the value 1 into the first line.
|

|**ItemID**
|Item ID
|Select the operator and enter the value for the item ID.
|====

__Table 1: data fields of the data format **ItemCategories**__

== Synchronization fields

None.
