= AttributeItemVariation
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Data format
:description: Data format AttributeItemVariation
:position: 20

The data format **AttributeItemVariation** is used to export, edit and import item variations. For further information, refer to the **<<basics/data-exchange/importing-data#60, Importing variations>>** chapter. Create and export the data format in the **Data exchange » Export » Dynamic export** menu. Import the data format in the **Data exchange » Import » Dynamic import** menu. The **<<basics/data-exchange/exporting-data#, Exporting data>>** and **<<basics/data-exchange/importing-data#, Importing data>>** pages of the manual describe how you export and import the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the **AttributeItemVariation** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

[cols="a,a,a"]
|====
|Field name |Explanation |Filter

|**ASIN**
|Amazon Standard Identification Number
|

|**AttributeValueSetID**
|ID of the item variation
|

|**Availability**
|The availability of the item variation
|

|**DeleteVariation**
|Deletes additional entries for a variation in the editing window of an item under **Tab: Attributes » Tab: Variations**, e.g. the EAN or variation number that was entered
|

|**EAN**
|EAN (international item number)
|Activate the filter, select the operator and enter the value for the EAN.

|**EAN2**
|EAN 2
|

|**EAN3**
|EAN 3
|

|**EAN4**
|EAN 4
|

|**ItemExternalID**
|External item ID
|

|**ItemFree1 - ItemFree20**
|The item variation's free text field 1 - free text field 20
|

|**ItemID**
|The item variation's item ID
|Activate the filter, select the operator and enter the value.

|**ItemMarking1ID**
|The item variation's flag
|Select the operator and the flag.

|**ItemMarking2ID**
|Additional item flag
|Select the operator and the flag.

|**ItemNo**
|The item variation's item number
|

|**ItemProducer**
|Item manufacturer
|

|**ItemProducerID**
|Item manufacturer ID
|

|**OverSale**
|Permits overselling of an item variation +
**0** = No +
**1** = Yes
|

|**PriceID**
|The item's price ID
|

|**PurchasePrice**
|The item variation's purchase price
|

|**RecommendedRetailPrice**
|RRP
|

|**VariationDetailsID**
|Internal system ID
|

|**VariationIDString**
|ID hash of the attributes and values. Example: "1:4;2:6". This is a list of attribute IDs and their corresponding values. These two numbers are separated by a colon. Multiple combinations of IDs and values (attributes and attribute values) are separated by a semicolon. +
Meaning of the values in the example above: +
**1** = **Attribute ID** for attribute A +
**4** = **Value ID** that corresponds to attribute A +
**2** =**Attribute ID** for attribute B +
**6** = **Value ID** that corresponds to attribute B +
Alternatively, use the data field **VariationString**.
|

|**VariationNo**
|Number of the item variation
|Activate the filter, select the operator and enter the value.

|**VariationString**
|System name hash of the attributes and values. Example: "Colour:Blue;Size:XXL" +
Pay attention to the explanation of the data field **VariationIDString**. This difference here is that the particular names are used instead of the IDs. +
Alternatively, use the data field **VariationIDString**.

|
|====

__Table 1: data fields of the data format **AttributeItemVariation**__

[IMPORTANT]
.Requirements
====
An EAN, variation number or availability needs to be saved at minimum for each variation in order to export this data format.

Furthermore, the following conditions have to be met:

* The item is created.
* The attributes are created.
* Both the attributes and values are linked with the item in order to build a variation from them.
====

== Overview of the mandatory fields

The following mandatory fields must be available for the data format **AttributeItemVariation** and need to have a valid value saved for them:

* **ItemID**
* **PriceID**
* **VariationIDString**
* plus additional fields, such as **EAN**, **VariationNo** etc.

== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<basics/data-exchange/importing-data#25, **data synchronisation**>>. These data fields are mandatory synchronisation fields. For mandatory synchronisation fields, select the option **Synchronisation** as **Import procedure**. At least one of the data fields from the following table must be selected for synchronisation.

[cols="a,a"]
|====
|Field name |Explanation

|**EAN**
|EAN (international item number)

|**EAN2 - EAN4**
|EAN 2 to EAN 4

|**VariationDetailsID**
|Internal system ID

|**VariationNo**
|Number of the item variation
|====

__Table 2: data fields with the import procedure set to **Synchronisation**__

