= ItemBundle
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Data format
:description: Data format ItemBundle
:position: 120

The data format **ItemBundle** is used to export, edit and import item bundle data. This data format is only available until plentymarkets 6. Use the data format variationBundle to manage bundles in plentymarkets 7. Create and export the data format in the **Data exchange » Export » Dynamic export** menu. Import the data format in the **Data exchange » Import » Dynamic import** menu. The **<<basics/data-exchange/exporting-data#, Exporting data  >>** and **<<basics/data-exchange/importing-data#, Importing data  >>** pages of the manual describe how you export and import the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

Table 1 explains the data fields for the **ItemBundle** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

[cols="a,a,a"]
|====
|Field name |Explanation |Filter

|**AttributeValueSetID**
|ID of the item variation
|

|**ItemID**
|The item bundle's item ID
|Activate the filter, select the operator and enter the value.

|**ItemSourceID**
|A basic item's ID
|Activate the filter, select the operator and enter the value.

|**PriceID**
|The item bundle's price ID
|

|**Quantity**
|Quantity
|
|====

__Table 1: data fields of the data format **ItemBundle**__

