= SerialKeys
:lang: en
include::{includedir}/_header.adoc[]
:position: 215

The data format **SerialKeys** is used to export, edit and import serial numbers. Use this data format to easily import a large amount of your item's serial numbers into plentymarkets. You can also export the serial numbers of your items, edit them in the file and re-import the file. Create and export the data format in the **Data exchange » Export » Dynamic export** menu. Import the data format in the **Data exchange » Import » Dynamic import** menu. The **<<basics/data-exchange/exporting-data#, Exporting data  >>** and **<<basics/data-exchange/importing-data#, Importing data  >>** pages of the manual describe how you export and import the data format.

Pay close attention to the exact spelling of the data fields. The data cannot be processed if the data fields are spelled incorrectly.

== Overview of the data fields

Table 1 explains the data fields for the **SerialKeys** data format in alphabetical order as well as filter options that you set in the **Filter** tab of the data format.

[cols="a,a,a"]
|====
|Field name |Explanation |Filter

|**ItemID**
|Item ID
|Activate the filter, select the operator and enter the value.

|**OrderID**
|Order ID
|

|**OrderRowID**
|The stock unit's order ID
|

|**SerialKey**
|Serial number
|

|**SerialKeyID**
|ID of the serial number
|
|====

__Table 1: data fields of the data format **SerialKeys**__

== Overview of the mandatory fields

The following mandatory field must be available for the data format **SerialKeys** and needs to have a valid value saved for it:

* ItemID

== Overview of the synchronisation fields

The data fields that are listed in table 2 are available for <<basics/data-exchange/importing-data#25, **data synchronisation** >>. This data field is a mandatory synchronisation field. For mandatory synchronisation fields, select the option **Synchronisation** as **Import procedure**.

[cols="a,a"]
|====
|Field name |Explanation

|**SerialKeyID**
|ID of the serial number
|====

__Table 2: data fields with the import procedure set to **Synchronisation**__

