= Best Practices: Ereignisaktionen und Aktionsmanager
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Vorgänge automatisieren, Automatisierung, Best Practice, Aufträge, Ereignisaktionen, Aktionsmanager
:position: 40

Ein nicht unerheblicher Teil deines Tagesgeschäfts als Händler entfällt auf einfache Routineaufgaben, die du weitgehend durch dein plentymarkets-System erledigen lassen kannst. Dazu beitet dir plentymarkets verschiedene effektive Werkzeuge, mit denen sich diese Routineaufgaben zeitsparend erledigen lassen. +
Auf dieser Handbuchseite findest du praktische Einrichtungsbeispiele zu den *Ereignisaktionen* und zum *Aktionsmanager*.

[IMPORTANT]
.Voraussetzung für Automatismen
====
Einige der auf dieser Seite genannten Einrichtungsbeispiele versenden E-Mail-Vorlagen oder erzeugen bestimmte Auftragsdokumente. Stelle daher sicher, dass die entsprechenden *E-Mail-Vorlagen* im Menü *System » Mandant » Mandant wählen » E-Mail » Vorlagen* erstellt sind. Ebenso müssen vor dem Einrichten und Verwenden der Automatismen, die Dokumente erzeugen, die entsprechenden Dokumentenvorlagen im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente* eingerichtet sein.
====

== Praxisbeispiele: Ereignisaktionen

Das Grundprinzip von Ereignisaktionen ist leicht verständlich: Bestimmte *Ereignisse* im Webshop lösen, gesteuert mit einer Ereignisaktion, durch eine Art Schalter-Funktion bestimmte *Aktionen* aus. Genaue Anleitungen zum Einrichten von Ereignisaktionen sowie zu den zur Verfügung stehenden Ereignisse, Filter und Aktionen findest du auf der Handbuchseite <<basics/automatisierung/ereignisaktionen#, Ereignisaktionen>>. +
Im Folgenden findest du eine Auflistung von Beispielen für automatische Aktionen, die mit Ereignisaktionen ausgelöst werden.

=== Bestellbestätigung versenden

Wenn du schon beim Auftragseingang über den Webshop eine Bestellbestätigung an deine Kunden versenden möchtest, empfehlen wir die in <<tabelle-ereignisaktion-bestellbestaetigung>> beschriebene Ereignisaktion.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen eindeutigen Namen für die Ereignisaktion ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-bestellbestaetigung>>.
. *Speichere* die Einstellungen.
. Nimm Einstellungen gemäß <<tabelle-ereignisaktion-bestellbestaetigung>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[tabelle-ereignisaktion-bestellbestaetigung]]
.Ereignisaktion "Bestellbestätigung an Kunden versenden" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage > Neuer Auftrag*
|

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Auftrag*

|*Aktion*
|*Kunde > E-Mail versenden*
|Über das Plus-Symbol die Vorlage *Webshop: Eingangsbestätigung Bestellung* wählen.
|====

=== Zahlungsbestätigung versenden

Möchtest du nach vollständiger Buchung des Zahlungseingangs eine entsprechende E-Mail an deine Kunden versenden, empfehlen wir die in <<tabelle-ereignisaktion-zahlungsbestätigung>> beschriebene Ereignisaktion.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen eindeutigen Namen für die Ereignisaktion ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-zahlungsbestaetigung>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-zahlungsbestaetigung>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[tabelle-ereignisaktion-zahlungsbestaetigung]]
.Ereignisaktion "Zahlungsbestätigung an Kunden versenden" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Zahlung > Teilzahlung*
|

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Auftrag*

|*Aktion*
|*Kunde > E-Mail versenden*
|Über das Plus-Symbol die Vorlage *Auftrag: Zahlungseingang vollständig* wählen.
|====

=== E-Mail-Vorlagen an Mitarbeiter versenden

Möchtest du deine Mitarbeiter per E-Mail über Zusatzwünsche zu einem Auftrag informieren, empfehlen wir die in <<tabelle-ereignisaktion-zusatzwunsch-ma>> beschriebene Ereignisaktion.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen eindeutigen Namen für die Ereignisaktion ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-zusatzwunsch-ma>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-zusatzwunsch-ma>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[tabelle-ereignisaktion-zusatzwunsch-ma]]
.Ereignisaktion "Zusatzwünsche an Mitarbeiter senden" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung > Auftragsnotiz vom Kunden*
|

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Auftrag*

|*Aktion*
|*Kunde > E-Mail versenden*
|Über das Plus-Symbol die für den Mitarbeiter die gewünschte E-Mail-Vorlage wählen. +
Die E-Mail wird an die Adresse des gewählten Mitarbeiters versendet. Damit eine E-Mail-Adresse hier wählbar ist, muss sie im Menü <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#42, System » Einstellungen » Benutzer » Konten>> beim Benutzer eingetragen sein. +
*_Tipp_*: Den Platzhalter *$CustomerSpecialWishes* in die E-Mail-Vorlage einfügen. Der Platzhalter gibt den vom Kunden eingetragenen Text aus.
|====

Möchtest du deine Mitarbeiter per E-Mail informieren, sobald ein Auftrag in den Status *[5] Freigabe Versand* wechselt, empfehlen wir die in <<tabelle-ereignisaktion-statuswechsel-ma>> beschriebene Ereignisaktion.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen eindeutigen Namen für die Ereignisaktion ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-statuswechsel-ma>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-statuswechsel-ma>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[tabelle-ereignisaktion-statuswechsel-ma]]
.Ereignisaktion "Mitarbeiter über Statuswechsel informieren" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung > Statuswechsel*
|Den Status *[5] Freigabe Versand* wählen.

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Auftrag*

|*Aktion*
|*Kunde > E-Mail versenden*
|Über das Plus-Symbol die für den Mitarbeiter die gewünschte E-Mail-Vorlage wählen, z.B die Vorlage *Auftrag > Versandbestätigung*. +
Die E-Mail wird an die Adresse des gewählten Mitarbeiters versendet. Damit eine E-Mail-Adresse hier wählbar ist, muss sie im Menü <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#42, System » Einstellungen » Benutzer » Konten>> beim Benutzer eingetragen sein. +
|====

=== Auftragsstatus ändern

Möchtest du eine Rechnung erzeugen, sobald ein Auftrag in den Status *[5] Freigabe Versand* wechselt und dabei diesen Auftrag in den Status *[6] Gerade im Versand* setzen, empfehlen wir die in <<tabelle-ereignisaktion-rechnung-statuswechsel>> beschriebene Ereignisaktion.

[WARNING]
.Dokument per Ereignisaktion erzeugen
====
Mit dieser Ereignisaktion findet lediglich die Erzeugung des Dokuments Rechnung statt. Richte dir eine zusätzliche Ereignisaktion ein, wenn deine Kunden die Rechnung als Anhang in einer E-Mail erhalten sollen. Werden Dokumente mit einer Aktion gleichzeitig erzeugt und versendet, erfolgt der E-Mail-Versand unter Umständen, bevor die Rechnung vollständig erzeugt wurde.
====

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen eindeutigen Namen für die Ereignisaktion ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-rechnung-statuswechsel>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-rechnung-statuswechsel>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[tabelle-ereignisaktion-rechnung-statuswechsel]]
.Ereignisaktion "Rechnung erzeugen und Statuswechsel veranlassen" einrichten
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung > Statuswechsel*
|Den Status *[5] Freigabe Versand* wählen.

|*Filter 1*
|*Auftrag > Auftragstyp*
|*Auftrag*

|*Aktion 1*
|*Auftrag > Status ändern*
|Den Status *[6] Gerade im Versand* wählen.

|*Aktion 2*
|*Dokumente > Rechnung erzeugen*
|Bei Bedarf die Optionen *Zahlungsziel* und *Skonto* aktivieren oder einen *Kommentar* eingeben, der auf der erzeugten Rechnung angezeigt wird. +
|====

=== Gratis-Artikel zu Aufträgen hinzufügen

Möchtest du zu Aufträgen ab einem bestimmten Warenwert oder zu Werbezwecken Gratis-Artikel hinzufügen, empfehlen wir die in <<tabelle-ereignisaktion-auftrag-gratiszugabe>> beschriebene Ereignisaktion. +
Weitere Information zu Gratis-Artikeln findest du auch auf der Handbuchseite <<artikel/artikel-verwalten#4300, Artikel verwalten>>.

[.collapseBox]
.Ereignisaktion erstellen
--
. Öffne das Menü *System » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<tabelle-ereignisaktion-auftrag-gratiszugabe>>.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ereignisaktion-auftrag-gratiszugabe>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

[[tabelle-ereignisaktion-auftrag-gratiszugabe]]
.Ereignisaktion "Gratis-Artikel hinzufügen" einrichten
[cols="1,2,2"]
|====
|Einstellung |Option |Auswahl

|**Ereignis**
|**Auftragsanlage > Neuer Auftrag**
|

|**Filter 1**
|**Auftrag > Auftragstyp**
|**Auftrag**

|**Filter 2**
|**Warenwert (brutto)**
|Operator wählen und Warenwert eingeben. +
*_Beispiel:_* Operator *>=*, Warenwert *50,00* = Variante wird ab 50 Euro Warenwert hinzugefügt

|*Aktion*
|*Variante > Variante hinzufügen*
|ID der Variante eingeben.
|====

=== Mahngebühren zum Auftrag hinzufügen

////
TODO: Ereignisaktion für Mahnungen/Mahnartikel
////


== Praxisbeispiele: Aktionsmanager

Mit dem Aktionsmanager richtest du automatische Prozesse ein, die Aktionen täglich zu bestimmten Zeitpunkten ausführen. Im Gegensatz zu den Ereignisaktionen werden die Aktionen im Aktionsmanager in der Regel nicht von bestimmten Ereignissen ausgelöst, sondern finden automatisch statt, sobald eine festgelegte Zeitspanne vergangen ist. Beispielsweise kannst du täglich eine automatische Zahlungserinnerung an alle Kunden schicken, die nicht innerhalb der letzten 7 Tage ihre Waren bezahlt haben. +
Genaue Anleitungen zum Einrichten des Aktionsmanagers sowie zu den zur Verfügung stehenden Filtern und Aktionen findest du auf der Handbuchseite <<basics/automatisierung/aktionsmanager#, Aktionsmanager>>.

=== Zahlungserinnerung versenden

Wenn du Käufer mit Aufträgen der Zahlungsart *Vorkasse* an eine ausstehende Zahlung erinnern möchtest, nutze die in <<tabelle-aktionsmanager-zahlungserinnerung>> beschriebene Aktion. Beachte bei den Einstellungen, dass Aufträge mit der Zahlungsart *Vorkasse* in Ihrem plentymarkets System direkt den Status *[3] Warten auf Zahlung* erhalten.

[[tabelle-aktionsmanager-zahlungserinnerung]]
.Aktion "Zahlungserinnerung versenden" einrichten
[cols="1,3"]
|====
|Tab |Einstellung

|*Einstellungen*
|Den *Zeitpunkt* der Aktion einstellen, zu dem die Aktion täglich ausgeführt werden soll. Einen *Namen* eintragen und die Option *Aktiv* aktivieren.

|*Filter*
|Unter *Status* die Option *Warten auf Zahlung* wählen. Unter *Letzter Statuswechsel* die Option *Tage eingeben* wählen. *7* in das Feld *Tage* eintragen. +
Somit werden alle Aufträge gefunden, die sich seit genau sieben Tagen im Status *[3] Warten auf Zahlung* befinden.

|*Aktion*
|Unter *Versende E-Mail-Vorlage* die für diesen Fall erstellte *E-Mail-Vorlage* wählen, beispielsweise die Vorlage *Auftrag: Zahlungserinnerung*.
|====

[TIP]
.Tipp: Aktionsvarianten
====
Es empfiehlt sich, diese Aktion in mehreren Varianten anzulegen. Eine zusätzliche E-Mail mit einer weiteren Zahlungsaufforderung kann so einige Tage später versendet werden. Noch einige Tage später kann direkt eine weitere Aktion ausgeführt werden, die den Status auf *8* setzt, um den Auftrag zu stornieren. Dieser Statuswechsel bewirkt auch, dass der für diesen Auftrag reservierte Warenbestand wieder freigegeben wird.
====

=== eBay-Disputprozess starten

Mithilfe des Aktionsmanagers kannst du auch eBay-Disputprozesse automatisch starten. Dabei erhält der Käufer über eBay eine Zahlungsaufforderung. Wir empfehlen, den Filter für diese Aktion ähnlich dem der Aktion *Zahlungserinnerung versenden* aus dem vorherigen Beispiel zu gestalten. Als Aktion wird dazu aber *eBay: Disputprozess starten* gewählt.

Der Disputprozess ist für Aufträge vorgesehen, bei denen du länger als mindestens 4 Tage auf die Zahlung wartest. Diese Aufträge werden in plentymarkets als *ausstehende Aufträge* bezeichnet und sind im Menü <<omni-channel/multi-channel/ebay-einrichten#7300, *System » Märkte » eBay » Datenaustausch*>> einsehbar und können hier importiert werden. Damit der Disputprozess per Aktionsmanager gestartet wird, musst du diese ausstehenden Aufträge zunächst importieren.

Nutze zum automatischen Starten des eBay-Disputprozesses die in <<tabelle-aktionsmanager-ebay-disputprozess>> beschriebene Aktion.

[[tabelle-aktionsmanager-ebay-disputprozess]]
.Aktion "eBay-Disputprozess starten" einrichten
[cols="1,3"]
|====
|Tab |Einstellung

|*Einstellungen*
|Den *Zeitpunkt* der Aktion einstellen, zu dem die Aktion täglich ausgeführt werden soll. Einen *Namen* eintragen und die Option *Aktiv* aktivieren.

|*Filter*
|Unter *Status* die Option *Unvollständige Daten* wählen. Unter *Letzter Statuswechsel* die Option *Tage eingeben* wählen. *10* in das Feld *Tage* eintragen. +
Somit werden alle Aufträge gefunden, die sich seit genau 10 Tagen im Status *[1] Unvollständige Daten* befinden.

|*Aktion*
|Unter *eBay* die Option *Disputprozess starten* wählen.
|====

=== eBay-Bewertungen abgeben

Der Aktionsmanager bietet dir die Möglichkeit, Käufer bei Erhalt einer positiven Bewertung automatisch ebenfalls positiv zu bewerten. Für diesen Prozess muss eine entsprechende Aktion im *Aktionsmanager* eingerichtet sowie *Bewertungstexte* hinterlegt werden. Diese Aktion ist die einzige im Aktionsmanager, die von einem Ereignis und nicht von einem bestimmten Zeitpunkt ausgelöst wird. Beachten dazu weiteren Informationen auf der Handbuchseite <<omni-channel/multi-channel/ebay-einrichten#1300, eBay>>.
