= Prozesse
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Prozesse, Einstellungen, Client
:position: 175

**plentymarkets » Einstellungen » Prozesse**

== Inhalt dieses Kapitels

Dieses Kapitel befasst sich mit Prozessen in plentymarkets, die Sie mit dem plentymarkets Client konfigurieren. +
Der plentymarkets Client ist ab plentymarkets Version 5.000 verfügbar.

Details dazu sowie den Download finden Sie auf unserer Webseite zum **link:https://www.plentymarkets.eu/produkt/prozesse/plentymarkets-client/[plentymarkets Client].**

== Videotutorials

Sehen Sie sich für einen ersten Einblick in die plentymarkets-Prozesse das folgende Einleitungsvideo an:

video::84490622[vimeo]

Weitere Videotutorials zur Einführung und Fallbeispiele zu den Prozessen finden Sie **link:http://www.plentymarkets.eu/knowledge/video-archiv/prozesse/[hier].**

== Anwendung und Konfiguration

Detaillierte Informationen zur Anwendung und Konfiguration der hier gelisteten Bestandteile eines Prozesses und weitere hilfreiche Videotutorials finden Sie auf der jeweiligen Handbuchseite:

* **<<basics/automatisierung/prozesse/arbeitsschritte#, Arbeitsschritte  >>**
* **<<basics/automatisierung/prozesse/aktionen#, Aktionen/Steuerelemente  >>**
* **<<basics/automatisierung/prozesse/subaktionen#, Subaktionen  >>**

