= FBA-Service von Amazon nutzen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Amazon FBA, FBA, Amazon Multi-Channel, Amazon FBA Multi-Channel, Amazon FBA einrichten, FBA einrichten, Versand durch Amazon, Amazon versendet, Fulfillment by Amazon, Fulfilment by Amazon, Amazon Fulfilment, Amazon Fulfillment
:description: Multi-Channel in plentymarkets: Amazon versendet deine Ware mit Amazon FBA.
:position: 30
:url: maerkte/amazon/amazon-fba-nutzen
:id: VKWEAOP
:author: team-multi-channel

Das Kürzel FBA steht für Fulfillment by Amazon. Statt die Aufträge selbst zu bearbeiten, die Ware zu verpacken und zu versenden, überlässt du beim FBA-Programm Amazon diese Aufgabe. Natürlich musst du zumindest einen Teil deiner Waren dann auch bei Amazon einlagern.

Weitere Informationen zu Amazon FBA und zur Einrichtung des Services in plentymarkets findest du in diesem Video-Tutorial:

.Amazon FBA
video::314732668[vimeo]

[#20]
== Informationen zur FBA-Auftragsabwicklung

Hier findest du Informationen zur Abwicklung von FBA-Aufträgen.

=== Ablauf des Auftragsimports

Die Auftragsbearbeitung hat folgenden Ablauf:

*  Kund:innen kaufen bei Amazon.
*  Amazon verschickt die Ware.
*  Das plentymarkets System fordert einen Bericht an.
*  Amazon erstellt den Bericht.
*  Am nächsten Tag prüft plentymarkets automatisch, ob Berichte bei Amazon vorliegen. Wenn ja, werden die Berichte importiert.
*  Aus den Berichten werden in plentymarkets Aufträge erzeugt.

=== Begriffsdefinitionen

* *Inbound* bedeutet, dass du Amazon mit Waren versorgst, die Amazon an deine Kundschaft liefert.
  ** Inbound-Sendungen sind also deine Sendungen an ein Amazon FBA-Logistikzentrum.
  ** Inbound-Aufträge sind die Aufträge, die in plentymarkets für deine Inbound-Sendungen erstellt werden.
* *Outbound* beschreibt den Prozess des Vertriebs und Versands, den Amazon für dich übernimmt: Amazon lagert die Artikel und verpackt und versendet die Artikel dann an deine Kund:innen.

[IMPORTANT]
.Hinweis zum Auftragsimport
====
Amazon generiert Berichte nur einmal täglich. Da Artikel nach bis zu 2 Tagen versendet werden, sind FBA-Aufträge erst mit einer zeitlichen Verzögerung in deinem System verfügbar. Die von Amazon generierte Auftragsbestätigung ist in der Regel zwei Tage nach Versand der Ware in deinem System verfügbar, also insgesamt bis zu 4 Tage nach Bestellung der Ware durch Käufer:innen. Die Lieferpünktlichkeit wird davon jedoch nicht berührt und erfolgt in der von Amazon gewohnten Schnelligkeit.
====

Amazon FBA-Aufträge werden mit den Parametern *Status* und *Herkunft* importiert. Für die Option *Status* legst du den für deinen Prozess passenden Status fest, also zum Beispiel *[7] Warenausgang gebucht*. Die Herkunft wird automatisch auf Amazon FBA oder eine Amazon FBA-Unterherkunft, wie z.B. Amazon FBA USA, gesetzt. Der Warenausgang wird hier in plentymarkets direkt gebucht, so dass keine Reservierung des Bestands der enthaltenen Artikelpositionen stattfindet.

[TIP]
.Ereignisaktionen für Fulfillment
====
Lege die für den Fulfillment-Prozess nötigen Ereignisaktionen an, um eine Rechnung zu erzeugen und per E-Mail automatisch an Käufer:innen zu senden sowie den Auftrag dann in einen weiteren Status zu setzen. +
Beachte dazu die Handbuchseiten <<automatisierung/ereignisaktionen#, Ereignisaktionen>> und <<fulfillment#, Standard-Fulfillment im Detail>>.
====

[#30]
=== FBA-Teillieferungen

Amazon FBA-Teillieferungen werden von Amazon veranlasst, wenn sich die von Amazon im Kundenauftrag versendete Ware in unterschiedlichen Amazon-Lagern befindet.
Bei den Kund:innen kommen nach Bestellung demzufolge mehrere Pakete zu einem getätigten Auftrag an. +
In plentymarkets wird jede FBA-Teillieferung anhand des versendenden FBA-Lagers als separater Auftrag im System erstellt. Pro Teillieferung kann eine Sendungsnummer von Amazon importiert und der jeweiligen Teillieferung zugeordnet werden. Pro Teillieferung kann eine separate Rechnung erzeugt werden, was aufgrund der unterschiedlichen zu berechnenden Steuern erforderlich ist, wenn die Amazon-Lager in unterschiedlichen Ländern liegen.

[#40]
=== Europäisches Versandnetzwerk

Amazon erweitert kontinuierlich das europäische Versandnetzwerk für Händler:innen, die Versand durch Amazon nutzen. Eine Voraussetzung ist, dass du in allen Ländern, in denen du FBA-Logistikzentren nutzt, steuerrechtlich registriert sind. Damit für diese neuen Logistikzentren deine Rechnungen auch steuerlich korrekt erstellt werden, kannst du neben deinem Firmensitz im Menü *Einrichtung » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung* den Lagerstandort als Basis für den Standard-Umsatzsteuersatz wählen und das individuell für jeden deiner Mandanten (Shops). Im gleichen Menü im Tab *Umsatzsteuersätze* erfasst du auch die notwendigen Steuersätze für die Länder.

[TIP]
.Beispiel: Logistikzentrum in Polen mit Versand nach Deutschland
====
Damit für Aufträge, die von einem Logistikzentrum in Polen nach Deutschland verschickt werden, nicht der polnische Steuersatz verwendet wird, muss für den Standort Polen zusätzlich das Land Deutschland mit dem deutschen Steuersatz eingetragen werden. Wähle dafür im Menü *Einrichtung » Mandant » Mandant wählen » Standorte » Polen » Buchhaltung » Tab: Umsatzsteuersätze* das Land *Deutschland* und trage den deutschen Steuersatz sowie die gültige USt-IdNr. ein.
====

[#50]
== Amazon FBA einrichten

Gehe wie unten beschrieben vor, um Amazon FBA in deinem plentymarkets System einzurichten.

[#60]
=== Lager für Amazon FBA erstellen

Im Menü *Einrichtung » Märkte » Amazon » Einstellungen* im Tab *Auftragseinstellungen* stellst du zunächst ein, welches Lager für Amazon Fulfillment-Aufträge verwendet werden soll. So bleibt die komplette Funktionalität der Warenwirtschaft auch beim FBA-Programm erhalten und du behältst die Lagerbestände bei Amazon über dein plentymarkets System im Blick.

[.instruction]
Lager erstellen:

. Öffne das Menü *Einrichtung » Waren » Lager*.
. Klicke auf *Neues Lager*.
. Gib einen Namen für das Lager ein.
. Wähle einen *Lagertyp*. +
*_Hinweis:_* Wenn du dieses Lager nur für FBA-Bestände verwenden möchtest, du den Bestand dieses Lagers also nicht in deinem Webshop oder auf anderen Marktplätzen anbieten möchtest, wähle den Lagertyp *Reparatur*.
. Wähle als *Logistiktyp* die Option *Amazon*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Lager wird alphabetisch sortiert unter Lager angezeigt und geöffnet.
. Nimm die weiteren Einstellungen gemäß der Erläuterungen auf der Handbuchseite <<warenwirtschaft/lager-einrichten#, Lager einrichten>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Lager wird erstellt.

[#70]
=== Einstellungen für Outbound-Aufträge vornehmen

Lege nun fest, wie Aufträge, die über Amazon eingehen, behandelt werden sollen.

[.instruction]
Einstellungen für Outbound-Aufträge vornehmen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Wähle das Amazon-Konto, für das du FBA aktivieren möchtest.
. Wechsele in das Tab *Auftragseinstellungen*.
. Nimm die Einstellungen vor. Beachte <<#fba-auftragseinstellungen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[fba-auftragseinstellungen]]
.Einstellungen im Tab *Auftragseinstellungen*
[cols="1,3"]
|====
| Einstellung | Erläuterung

2+| Versand durch Amazon (FBA)

| *Aktiv*
| Häkchen setzen, um den Versand durch Amazon zu aktivieren. Deine FBA-Aufträge werden täglich automatisch in dein plentymarkets System importiert.

| *Herkunft*
| Wählen, ob nur Aufträge von Amazon mit FBA abgewickelt werden oder ob auch Aufträge von anderen <<auftraege/auftragsherkunft#, Herkünften>> mit FBA abgewickelt werden können.

| *Status*
| <<auftraege/auftraege-verwalten#1200, Status>> wählen, der Aufträgen zugewiesen werden soll, die von Amazon importiert werden.

| *Lager*
| Wählen, welches <<Lager für Amazon FBA erstellen, Amazon FBA-Lager>> für den Bestandsabgleich des Kontos verwendet werden soll. Dieses Lager wird auch für die FBA-Auftragszuordnung des Kontos verwendet, falls kein FBA-Auftrag zugeordnet werden kann, weil für das Auftragsland kein Lager eingerichtet wurde.

| *Warenausgang*
| Wählen, ob der Warenausgang als gebucht markiert werden soll oder nicht. Die Option *Als gebucht markieren* erzeugt keine Warenbewegung. Um eine Warenbewegung zu erzeugen, muss die Option *Nicht als gebucht markieren* eingestellt sein und eine Ereignisaktion eingerichtet werden.

| *Retourenimport*
| Option *täglichen* wählen, damit FBA-Retouren automatisch einmal täglich in dein plentymarkets System importiert werden. +
*_Tipp:_* Im Retourenfall senden Käufer:innen die Ware zurück an Amazon. Die Retoure wird in dein plentymarkets System importiert und mit dem Retourenstatus im Auftragsmenü erstellt, den du im Menü *Einrichtung » Aufträge » Einstellungen* gewählt hast. +
*_Wichtig:_* Retouren werden nur importiert, wenn der Auftrag mit unveränderter externer Auftragsnummer in plentymarkets vorliegt.

| *Gutschein bei Retouren berücksichtigen*
| Wählen, ob Gutscheine bei Retouren berücksichtigt werden sollen oder nicht. Wurde der FBA-Auftrag komplett oder teilweise mit einem Gutschein beglichen, wird der Gutschein bei der Retoure hinzugefügt und verrechnet. Dabei wird kein Mindestbestellwert für den Gutschein berücksichtigt.

| *Bestandsimport*
| Wählen, ob der Bestandsimport *stündlich* oder nie ausgeführt werden soll.

|*Status für übertragene Aufträge*
| <<auftraege/auftraege-verwalten#1200, Auftragsstatus>> für Aufträge wählen, die erfolgreich an FBA übertragen wurden.

| *Artikelpakete Multichannel*
a| Wählen, welche Positionen an Amazon übertragen werden sollen.

* *Alle Auftragspositionen übertragen* = Alle Positionen, die sich im Auftrag befinden, an Amazon übertragen. Wenn diese Option gewählt wird, werden die Paketposition und die Paketbestandteile an Amazon übertragen.
* *Nur Paketposition übertragen* = Nur die Paketposition wird an Amazon übertragen.
* *Ohne Paketposition übertragen* = Nur die Paketbestandteile werden an Amazon übertragen.

| *Versandkategorie*
a| Versandpriorität wählen.

* *Standard* = normaler Versand +
* *Expedited* = Schnellversand +
* *Priority* = bevorzugt (schnellster Versand)
|====

[#80]
==== FBA-Gutschriften automatisch importieren

Nutze den Gutschriftenimport, um FBA-Gutschriften automatisch in dein plentymarkets System zu importieren. Die Gutschriften werden mit dem Status importiert, der unter *Einrichtung » Aufträge » Einstellungen* für die Einstellung *Standard-Status Gutschrift* gewählt wurde. Wenn der Gutschriftenimport aktiviert ist, werden FBA-Gutschriften alle 4 Stunden importiert.

[IMPORTANT]
.FBA-Retouren nicht per Ereignisaktion als Gutschriften erstellen
====
Wenn du den Gutschriftenimport aktivierst, werden FBA-Gutschriften automatisch alle 4 Stunden in dein plentymarkets System importiert. Verwende deshalb in diesem Fall keine Ereignisaktion, um FBA-Retouren als Auftragstyp *Gutschrift* anzulegen.
====

[.instruction]
Automatischen Gutschriftenimport aktivieren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Öffne das Amazon-Konto.
. Wechsele in das Tab *Auftragseinstellungen*.
. Wähle für die Einstellung *Gutschriftenimport* die Option *Ja*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#90]
=== Einstellungen für Sendungen an FBA-Logistikzentrum vornehmen

Damit Amazon deine Artikel versenden kann, musst du ausreichend Bestand in einem oder mehreren FBA-Logistikzentren vorrätig halten. Nimm dazu zunächst die unten beschriebenen Einstellungen für Sendungen an FBA-Logistikzentrum vor.

==== Allgemeine Einstellungen für FBA-Inbound-Sendungen vornehmen

[.instruction]
Allgemeine Einstellungen für FBA-Inbound-Sendungen vornehmen:

. Öffne das Menü *Einrichtung » Waren » Amazon FBA*. +
→ Die Ansicht *Allgemein* wird geöffnet.
. Nimm die Einstellungen vor. Beachte <<#fba-allgemein>>.
. Speichere (icon:save[set=plenty]) die Einstellungen. +
→ Die Einstellungen werden gespeichert.

[[fba-allgemein]]
.Allgemeine Einstellungen für FBA-Inbound-Sendungen
[cols="1,3"]
|====
|Filter |Erläuterung

2+|Versand

| *Etikettentyp*
|Etikettentyp wählen.

| *Sendungs-ID*
| Die ID der Sendung

| *Amazon-Konto*
|Amazon-Konto wählen.
|====

[#100]
==== Versandeinstellungen für FBA-Inbound-Sendungen vornehmen

Wähle, wie Sendungen an Amazon FBA-Logistikzentren versendet werden sollen.

[.instruction]
Versandeinstellungen für FBA-Inbound-Sendungen vornehmen:

. Öffne das Menü *Einrichtung » Waren » Amazon FBA*. +
→ Die Ansicht *Allgemein* wird geöffnet.
. Wechsele in die Ansicht *Versand*.
. Klicke auf das Plus, um neue Versandeinstellungen zu erstellen. +
→ Weitere Optionen werden eingeblendet.
. Nimm die Einstellungen vor. Beachte <<#fba-versand>>.
. Speichere (icon:save[set=plenty]) die Einstellungen. +
→ Die Versandeinstellungen werden gespeichert.

[[fba-versand]]
.Versandeinstellungen für FBA-Inbound-Sendungen
[cols="1,3"]
|====
|Filter |Erläuterung

| *Versandprofil*
| <<fulfillment/versand-vorbereiten#1000, Versandprofil>> wählen.

| *Versandart*
| Versandart wählen.

| *Amazon Transportpartner-Programm*
|Aktivieren, wenn du das Transportpartner-Programm von Amazon nutzt. +
// https://sellercentral.amazon.de/gp/help/external/G201119120?language=de_DE
// https://sellercentral.amazon.com/gp/help/external/G201119120

| *Sendungstyp*
|

|====

[#110]
==== Kontaktdaten für FBA-Inbound-Sendungen speichern

Gib die Kontaktdaten der Person in deinem Unternehmen ein, an die sich Amazon bei Rückfragen wenden kann.

[.instruction]
Kontaktdaten für FBA-Inbound-Sendungen speichern:

. Öffne das Menü *Einrichtung » Waren » Amazon FBA*. +
→ Die Ansicht *Allgemein* wird geöffnet.
. Wechsele in die Ansicht *Kontakt*.
. Nimm die Einstellungen vor. Beachte <<#fba-kontakt>>.
. Speichere (icon:save[set=plenty]) die Einstellungen. +
→ Die Kontaktdaten werden gespeichert.

[[fba-kontakt]]
.Kontaktdaten für FBA-Inbound-Sendungen
[cols="1,3"]
|====
|Filter |Erläuterung

| *Name*; +
*E-Mail-Adresse*; +
*Telefonnummer*; +
*Faxnummer*
|Kontaktdaten der Person eingeben, die Amazon bei Rückfragen kontaktieren soll.

|====

[#120]
== FBA-Inbound-Sendung an ein Amazon FBA-Logistikzentrum erstellen


[#130]
=== FBA-Sendung in Amazon Seller Central erstellen

Zunächst erstellst du eine FBA-Inbound-Sendung im Amazon Seller Central. Logge dich dafür im Amazon Seller Central ein und öffne den Bereich *Artikel an Amazon senden/ergänzen*. Nachdem du die Sendung im Amazon Seller Central erstellt hast, wird die Sendung mit der Sendungs-ID und dem Ziel-Logistikzentrum in plentymarkets importiert und kann im Menü *Waren » Amazon: Shipments* weiter bearbeitet werden.

// Amazon-Hilfe z.B. hier: https://images-eu.ssl-images-amazon.com/images/G/03/images/FBAQuickLaunchGuide_2015_DE.pdf?ld=NSGoogle_null

[#125]
=== FBA-Inbound-Sendungen in plentymarkets anzeigen

Das Menü *Waren » Amazon: Shipments* bietet eine Übersicht der FBA-Inbound-Sendungen, die du im Amazon Seller Central erstellt hast.

[.instruction]
FBA-Inbound-Sendungen in plentymarkets anzeigen:

. Öffne das Menü *Waren » Amazon: Shipments*.
. *_Optional:_* Wähle Filter in der Spalte links. Beachte <<#fba-inbound-sendungen>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefilterten Sendungen werden in der Übersicht rechts angezeigt. <<#fba-inbound-sendungen>> erläutert die angezeigten Informationen.


[[fba-inbound-sendungen]]
.FBA-Inbound-Sendungen in plentymarkets anzeigen
[cols="1,3"]
|====
|Spalte |Erläuterung

|Verfügbare Filter
a|
* *Sendungs-IDs* = Sendungs-ID eingeben, um nach der Sendung mit dieser ID zu suchen. +
* *Amazon-Konto* = Amazon-Konto aus der Dropdown-Liste wählen, um nach Sendungen für dieses Konto zu suchen. +
* *Letzte Änderung von* = Datum im Kalender wählen, um nach Sendungen zu suchen, die ab diesem Datum geändert wurden. +
* *Letzte Änderung bis* = Datum im Kalender wählen, um nach Sendungen zu suchen, die bis zu diesem Datum geändert wurden.

| *Sendungs-ID*
|Die ID, die Amazon der Sendung beim Erstellen im Amazon Seller Central gegeben hat.

| *Status*
|Der Status, den Amazon der Sendung gegeben hat. +
*_Hinweis:_* Hier werden nur Sendungen angezeigt, die den Status "Erstellt" haben und die im Amazon Seller Central erstellt wurden.

| *Name*
|Der Name, den Amazon der Sendung gegeben hat.

| *Ziel-Logistikzentrum*
|Das Amazon-FBA-Logistikzentrum, an das die Sendung gesendet wird.

| *Bestellung*
|Auf *Umbuchung anlegen* klicken, um für diese Sendung Varianten in ein FBA-Lager umzubuchen.
// umschreiben!!! ... um diese Sendung mit einer Umbuchung zu verknüpfen.
|====

[IMPORTANT]
.Umbuchung = Verknüpfung
====
Beachte, dass hier nicht wirklich eine Umbuchung stattfinden sollte, sondern lediglich eine Verknüpfung zur Umbuchung. +
Das Amazon FBA-Lager hat keine Stellplätze, sondern immer nur den Standardlagerort. Du solltest also vor der Anmeldung des Auftrags an Amazon _keine_ Umbuchung durchführen. Andernfalls gehen die in plentymarkets gespeicherten Stellplätze verloren und werden dann auf der Pickliste falsch angezeigt.
====

[#140]
=== FBA-Inbound-Auftrag für Sendung erstellen

Nachdem du im Amazon Seller Central eine FBA-Inbound-Sendung erstellt hast und diese Sendung in plentymarkets importiert wurde, buchst du die Varianten der Sendung in dein FBA-Lager um. Durch das Umbuchen der Ware in das FBA-Lager wird ein FBA-Inbound-Auftrag in plentymarkets erstellt. Dieser Auftrag kann dann im Lager weiter bearbeitet werden.
// umschreiben!!! ..., verknüpfst du deine Sendung mit der Umbuchung. Durch die Verknüpfung zur Umbuchung wird ein FBA-Inbound-Auftrag in plentymarkets erstellt. Dieser Auftrag kann dann im Lager weiter bearbeitet werden.

[.instruction]
FBA-Inbound-Auftrag für Sendung erstellen:

. Öffne das Menü *Waren » Amazon: Shipments*.
. *_Optional:_* Wähle Filter in der Spalte links, um nur bestimmte FBA-Inbound-Sendungen anzuzeigen. Beachte <<#fba-inbound-redistribution>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die Sendungen werden in der Übersicht rechts angezeigt.
. Klicke für die gewünschte Sendung in der Spalte *Bestellung* auf *Umbuchung anlegen* (icon:stock[set=plenty]). +
→ Das Menü *Umbuchung anlegen* wird angezeigt.
. Nimm die Umbuchung vor. Beachte die Erläuterungen in <<#fba-inbound-redistribution>>.
. *Speichere* (icon:save[set=plenty]) die Einstellungen. +
→ Die Varianten werden in das FBA-Lager umgebucht. +
// umschreiben!!! Die Varianten in der Sendung werden mit der Umbuchung verknüpft.
→ Für die Umbuchung wird ein FBA-Inbound-Auftrag im Menü *Waren » Amazon FBA Inbound* erstellt. +
→ Der FBA-Inbound-Auftrag kann weiter bearbeitet werden.

[[fba-inbound-redistribution]]
.FBA-Inbound-Auftrag für Sendung erstellen
[cols="1,3"]
|====
| Einstellung | Erläuterung

|Verfügbare Filter
| *Sendungs-IDs* = Sendungs-ID eingeben, um nach der Sendung mit dieser ID zu suchen. +
*Amazon-Konto* = Amazon-Konto aus der Dropdown-Liste wählen, um nach Sendungen für dieses Konto zu suchen. +
*Letzte Änderung von* = Datum im Kalender wählen, um nach Sendungen zu suchen, die ab diesem Datum geändert wurden. +
*Letzte Änderung bis* = Datum im Kalender wählen, um nach Sendungen zu suchen, die bis zu diesem Datum geändert wurden.

| *Quelllagerort*
|Lager wählen, aus dem die Varianten an das Amazon-FBA-Logistikzentrum gesendet werden sollen.

| *Status*
|Status aus der Dropdown-Liste wählen, der dem FBA-Inbound-Auftrag zugewiesen werden soll. +
//*_Tipp:_* Vorschlag für Status? Status in the range of 5.

| *ID der übergeordneten Bestellung* +
(optional)
| Wenn die Umbuchung als Kindauftrag eines existierenden Auftrags erstellt werden soll, die ID dieses Auftrags eingeben.


|====

[#150]
== FBA-Inbound-Aufträge anzeigen

Im Menü *Waren » Amazon FBA Inbound* werden die FBA-Inbound-Aufträge angezeigt. Beachte, dass erst ein FBA-Inbound-Auftrag erstellt wird, wenn du die Sendung mit einer Umbuchung verknüpft hast.

[.instruction]
FBA-Inbound-Aufträge anzeigen:

. Öffne das Menü *Waren » Amazon FBA Inbound*.
. *_Optional:_* Wähle Filter in der Spalte links. Beachte <<#fba-inbound-orders>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefilterten FBA-Inbound-Aufträge werden in der Übersicht rechts angezeigt. +
*_Tipp:_* Klicke auf den FBA-Inbound-Auftrag, um Optionen für die Auftragsbearbeitung anzuzeigen.

[[fba-inbound-orders]]
.FBA-Inbound-Aufträge anzeigen
[cols="1,3"]
|====
| Spalte | Erläuterung

|Verfügbare Filter
| *Eigner* = Eigner aus der Dropdown-Liste wählen, um nach FBA-Inbound-Aufträgen zu suchen, die diese Person erstellt hat. +
*Lager* = Lager aus der Dropdown-Liste wählen, um nach FBA-Inbound-Aufträgen zu suchen, die in dieses Lager umgebucht wurden. +
*Auftrags-ID* = ID des FBA-Inbound-Auftrags eingeben, um nach dem Auftrag mit dieser ID zu suchen.

| *Eigner*
|Die Person, die die Umbuchung erstellt hat

| *Ausgangslager*
|Das plentymarkets FBA-Lager

| *Empfangslager*
|Das Amazon-FBA-Logistikzentrum, an das der FBA-Inbound-Auftrag versendet wird

| *Auftrags-ID*
|plentymarkets ID des FBA-Inbound-Auftrags

| *Sendungs-ID*
|Die ID, die Amazon der Sendung beim Erstellen im Amazon Seller Central zugewiesen hat
|====

[#160]
== FBA-Inbound-Aufträge im Lager bearbeiten

Die weitere Bearbeitung der FBA-Inbound-Aufträge erfolgt im Lager, wo der Auftrag gepackt und bei Amazon angemeldet wird. Wie das Lagerpersonal dabei vorgeht, hängt natürlich von deinen individuellen Fulfillment-Abläufen ab. Hier wird beschrieben, wie du für den FBA-Inbound-Auftrag eine Pickliste druckst, die Paketinhaltsliste aufrufst und das Paket dann bei Amazon anmeldest.

[#200]
==== Pickliste drucken

Über das Menü *Waren » Amazon FBA Inbound* kannst du eine <<auftraege/auftragsdokumente/pickliste#, Pickliste>> für den FBA-Inbound-Auftrag drucken.

[.instruction]
Pickliste drucken:

. Öffne das Menü *Waren » Amazon FBA Inbound*.
. *_Optional:_* Wähle Filter in der Spalte links. Beachte <<#fba-inbound-orders>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefilterten FBA-Inbound-Aufträge werden in der Übersicht rechts angezeigt.
. Klicke auf den Auftrag. +
→ Die Optionen für die Auftragsbearbeitung werden angezeigt.
. Klicke auf *FBA-Inbound-Pickliste drucken*. +
→ Die Pickliste wird als PDF-Datei heruntergeladen und du kannst sie anschließend drucken.

[#170]
==== Paketinhaltsliste öffnen

Eine <<auftraege/paketinhaltsliste#, Paketinhaltsliste>> gibt Auskunft über den Inhalt von Paletten, Paketen und Artikeln. Die Paketinhaltsliste sorgt dafür, dass Amazon weiß, welche Artikel sich in den Paketen befinden, die Amazon für dich lagert und versendet.

[TIP]
.Menü *Aufträge » Paketinhaltsliste*
====
Du kannst die Paketinhaltsliste auch über das Menü *Aufträge » Paketinhaltsliste* öffnen und abarbeiten. Die Schaltfläche *Anmelden* wird aber nur angezeigt, wenn du die Paketinhaltsliste über das Menü *Waren » Amazon FBA Inbound* öffnest. Die Schaltfläche *Anmelden* benötigst du, wenn du die gepackten Pakete bei Amazon anmelden möchtest.
====

[.instruction]
Paketinhaltsliste öffnen:

. Öffne das Menü *Waren » Amazon FBA Inbound*.
. *_Optional:_* Wähle Filter in der Spalte links. Beachte <<#fba-inbound-orders>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefilterten FBA-Inbound-Aufträge werden in der Übersicht rechts angezeigt.
. Klicke auf den Auftrag. +
→ Die Optionen für die Auftragsbearbeitung werden angezeigt.
. Klicke auf *Paketinhaltsliste*. +
→ Der Auftrag wird im Menü *Aufträge » Paketinhaltsliste* angezeigt.
. Packe den Auftrag anhand der <<auftraege/paketinhaltsliste#, Paketinhaltsliste>>.

[#180]
==== FBA-Inbound-Auftrag bei Amazon anmelden

Nachdem der FBA-Inbound-Auftrag mithilfe der Paketinhaltsliste im Lager fertig gepackt ist, meldest du den Auftrag bei Amazon an. Bei der Anmeldung wird gleichzeitig die Paketinhaltsliste an Amazon gesendet. Wenn du einen eigenen Versanddienstleister nutzt, benötigst du die Paketnummer, um den FBA-Inbound-Auftrag bei Amazon anzumelden.

[IMPORTANT]
.Erst packen, dann anmelden
====
Sobald der Auftrag bei Amazon angemeldet wurde, darf der Inhalt der Pakete und Paletten nicht mehr geändert werden. Melde deshalb den Auftrag erst bei Amazon an, wenn alles fertig gepackt ist.
====

[.tabs]
====
Versand mit eigenem Versanddienstleister::
+
--
[.instruction]
FBA-Inbound-Auftrag bei Amazon anmelden (eigener Versanddienstleister):

. Öffne das Menü *Waren » Amazon FBA Inbound*.
. Klicke auf den Auftrag. +
→ Die Optionen für die Auftragsbearbeitung werden angezeigt.
. Klicke auf *Paketinhaltsliste*. +
→ Der Auftrag wird im Menü *Aufträge » Paketinhaltsliste* angezeigt.
. Klicke auf *Anmelden*. +
*_Hinweis:_* Der Button *Anmelden* wird nur angezeigt, wenn du die Paketinhaltsliste über das Menü *Waren » Amazon FBA Inbound* öffnest.
→ Das Fenster *Auftrag anmelden* wird geöffnet.
. Wähle die *Versandart für eigene Versanddienstleister* aus der Dropdown-Liste.
. Gib die Paketverfolgungsnummer für alle Pakete ein.
. Klicke auf *Ja*. +
→ Der Auftrag wird bei Amazon angemeldet.
. Bearbeite den Auftrag wie gewohnt weiter.

[TIP]
.Ausgegraute Felder beim Versand ohne Amazon-Transportpartner
======
Wenn du die Pakete selbst versendest und dies nicht von Amazon übernommen wird, sind die Schaltflächen *Versandkosten anfragen*, *Versandkosten akzeptieren*, *Anmeldung stornieren* und *Labels drucken* nicht verfügbar.
======

--

Versand mit Amazon-Transportpartner::
+
--
[.instruction]
FBA-Inbound-Auftrag bei Amazon anmelden (Amazon-Transportpartner):

. Öffne das Menü *Waren » Amazon FBA Inbound*.
. Klicke auf den Auftrag. +
→ Die Optionen für die Auftragsbearbeitung werden angezeigt.
. Klicke auf *Paketinhaltsliste*. +
→ Der Auftrag wird im Menü *Aufträge » Paketinhaltsliste* angezeigt.
. Klicke auf *Anmelden*. +
*_Hinweis:_* Die Schaltfläche *Anmelden* wird nur angezeigt, wenn du die Paketinhaltsliste über das Menü *Waren » Amazon FBA Inbound* öffnest.
→ Das Fenster *Auftrag anmelden* wird geöffnet.
. Wähle die *Versandart* aus der Dropdown-Liste. +
//*_Hinweis:_* Die Versandarten *Kleine Pakete* und *Teilladung* stehen zur Verfügung.
. Aktiviere die Option *Amazon-Transportpartner*.
. Klicke auf *Ja*. +
→ Eine neue Ansicht öffnet sich.
. Klicke auf *Versandkosten anfragen*, um eine Anfrage zu den geschätzten Versandkosten an Amazon zu senden. +
→  Die geschätzten Versandkosten werden in plentymarkets importiert.
. Um die Versandkosten zu akzeptieren, klicke auf *Versandkosten annehmen*. +
→ Der Auftrag wird bei Amazon angemeldet. +
→ Der Status ändert sich in _Bestätigt_.
→ Die Versandetiketten werden generiert.
. Klicke auf *Labels drucken*. +
→ Das Versandetikett wird heruntergeladen und du kannst es anschließend drucken.
. Bringe das Versandetikett an dem Paket an.
. Bearbeite das Paket wie gewohnt weiter.

[TIP]
.Versanddienstleister wird durch Amazon bestimmt
======
Wenn du die Sendung mit einem Amazon-Transportpartner versenden möchtest, entscheidet Amazon, mit welchem Versanddienstleister die Artikel versendet werden. Du hast keinen Einfluss auf die Wahl des Versanddienstleisters. +
Im Amazon Seller Central solltest du die Bedingungen zu allen Versanddienstleistern akzeptieren. Andernfalls kann dies zu Fehlermeldungen führen, wenn Amazon einen Versanddienstleister wählt, den du normalerweise nicht einsetzt.
======

--
====

[#180]
==== FBA-Inbound-Auftrags bei Amazon stornieren

Wenn du den FBA-Inbound-Auftrag fälschlicherweise angemeldet hast, kannst du die Anmeldung bei Amazon wieder rückgängig machen, indem du die Sendung stornierst.

Klicke dazu auf die Schaltfläche *Sendung stornieren*. Der Auftrag erhält nach der erfolgreichen Stornierung wieder den Status _In Arbeit_.

[IMPORTANT]
.Fristen für die Stornierung beachten
====
Beachte die Fristen, die für die Stornierung seitens Amazon vorgegeben sind:

* Für kleine Pakete beträgt die Frist, innerhalb der du den Auftrag stornieren kannst, 1 Tag.
* Für Teilladungen beträgt die Frist, innerhalb der du den Auftrag stornieren kannst, 1 Stunde.

Du kannst die Sendung allerdings jederzeit erneut anmelden, indem du die Versandkosten anforderst und diese akzeptierst.
====

[#3700]
== Amazon Multi-Channel einrichten

Amazon Multi-Channel bedeutet, dass "Lieferungen im Auftrag des Verkäufers durch Amazon verschickt werden, für Bestellungen, die nicht bei Amazon.de aufgegeben wurden, sondern z.B. auf eBay oder auf der persönlichen Website eines Verkäufers." (Quelle: Amazon)

Die Multi-Channel-Funktion ermöglicht dir also, Artikel bei Amazon zu lagern und von Amazon verschicken zu lassen, die du nicht bei Amazon, sondern auf anderen externen Marktplätzen verkaufst. Du erfährst in diesem Kapitel, welche Einstellungen du in deinem plentymarkets System vornehmen musst, damit diese Aufträge über Amazon abgewickelt werden können.

Die folgenden Schritte sind nötig, um deine Bestandsverwaltung und Artikeldaten für Amazon Multi-Channel einzurichten.

Weitere Informationen zu Amazon Multi-Channel und zur Einrichtung des Services in deinem plentymarkets System findest du in diesem Video-Tutorial:

.Amazon FBA
video::314735384[vimeo]

[#3800]
=== Lager für Amazon Multi-Channel erstellen

Lege ein Lager an, falls du noch kein Lager wie im Kapitel <<FBA-Service von Amazon nutzen, FBA-Service von Amazon nutzen>> beschrieben erstellt hast. Wichtig beim Multi-Channel-Versand ist, dass du für jeden landesspezifischen Amazon-Markt ein eigenes Lager mit dem Logistiktyp *Amazon* und das Land als Standort in plentymarkets eingerichtet hast.

[IMPORTANT]
.Beispiel für die Übereinstimmung von Amazon-Plattform und Lagerstandort
====
Beim Multi-Channel-Versand über amazon.co.uk muss ein eigenes Lager Amazon UK mit dem Logistiktyp *Amazon* und dem Standort Großbritannien erstellt werden. Die Ware muss also auch tatsächlich vor Ort bei Amazon z.B. in Großbritannien gelagert sein, da sonst keine Versandabwicklung über amazon.co.uk stattfinden kann.
====

[#3900]
=== Variantenverfügbarkeit für Amazon Multi-Channel einstellen

Nimm die im Folgenden beschriebenen Einstellungen an den Artikeln vor, die du für Amazon Multi-Channel verfügbar machen möchtest.

[.instruction]
Variantenverfügbarkeit für Amazon Multi-Channel einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Multi-Channel*.
. Nimm die Einstellungen im Bereich *Amazon* vor. Beachte dazu die Erläuterungen in <<artikelverfügbarkeit-amazon>> im Kapitel <<maerkte/amazon/amazon-einrichten#700, Variantenverfügbarkeit einstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#4000]
=== Einstellungen für Amazon Multi-Channel vornehmen

Nimm die im Folgenden beschriebenen Einstellungen im Menü für Amazon vor.

[.instruction]
Amazon Multi-Channel einrichten:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Wechsele in das Tab *Auftragseinstellungen*.
. Nimm die Einstellungen im Bereich *Versand durch Amazon (FBA)* vor. Beachte dazu die Erläuterungen in <<#amazon-multi-channel>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[amazon-multi-channel]]
.Amazon Multi-Channel einrichten
[cols="1,3"]
|====
| Einstellung | Erläuterung

| *Aktiv*
| Häkchen setzen, um den täglichen Auftragsimport zu aktivieren.

| *Herkunft*
| *Nur für Aufträge von Amazon verwenden* = Nur Aufträge von Amazon mit FBA abwickeln. +
*Für alle Aufträge verwendbar* = Alle Aufträge mit FBA abwickeln.

| *Status*
|<<auftraege/auftraege-verwalten#1200, Status>> der Aufträge wählen, die von Amazon importiert wurden.

| *Lager*
| Wählen, welches <<Lager für Amazon FBA erstellen, Lager>> für den Versand durch Amazon verwendet werden soll.

| *Warenausgang*
| Wählen, ob der Warenausgang als gebucht markiert werden soll oder nicht. Die Option *Als gebucht markieren* erzeugt keine Warenbewegung. Um eine Warenbewegung zu erzeugen, muss die Option *Nicht als gebucht markieren* eingestellt sein und eine Ereignisaktion eingerichtet werden.

| *Retourenimport*
|Wählen, ob Retouren *Nie* oder *Täglich* importiert werden sollen.

| *Gutschein bei Retouren berücksichtigen*
|Wählen, ob Gutscheine bei FBA-Retouren berücksichtigt werden sollen oder nicht. Wurde der FBA-Auftrag komplett oder teilweise mit einem Gutschein beglichen, wird der Gutschein bei der Retoure hinzugefügt und verrechnet. Dabei wird kein Mindestbestellwert für den Gutschein berücksichtigt.

| *Bestandsimport*
| Option *Stündlich* wählen, damit der Bestand importiert wird. +
Dabei werden nur Änderungen der Bestandsdaten berücksichtigt. Weitere Möglichkeiten zum Bestandsimport sind in Kapitel <<Bestand abgleichen, Bestand abgleichen>> beschrieben.

| *Status für übertragene Aufträge*
| Bestimmt den Auftragsstatus für Multi-Channel FBA Aufträge, die erfolgreich an FBA übertragen wurden.

| *Artikelpakete Multichannel*
a| Wählen, welche Positionen an Amazon übertragen werden sollen.

* *Alle Auftragspositionen übertragen* = Alle Positionen, die sich im Auftrag befinden, an Amazon übertragen. Wenn diese Option gewählt wird, werden die Paketposition und die Paketbestandteile an Amazon übertragen.
* *Nur Paketposition übertragen* = Nur die Paketposition wird an Amazon übertragen.
* *Ohne Paketposition übertragen* = Nur die Paketbestandteile werden an Amazon übertragen.

| *Versandkategorie*
a| Versandkategorie wählen.

* *Standard* = Normaler Versand
* *Expedited* = Schnellversand
* *Priority* = Bevorzugt (schnellster Versand)
|====

[#4100]
=== FBA-Versandfreigabe automatisch erteilen

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, damit Amazon automatisch eine Meldung über den Auftrag erhält und den Auftrag bearbeiten sowie den Versand veranlassen kann.

:table-event-procedure: <<#ereignisaktion-fba-versandfreigabe>>

include::../../../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-fba-versandfreigabe]]
.Ereignisaktion zum automatischen Erteilen von FBA-Versandfreigaben an Amazon
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

| *Ereignis*
| *Auftragsänderung: Statuswechsel &gt; [5] Freigabe Versand*
|

| *Filter 1*
| *Auftrag &gt; Auftragslager*
| *Amazon Multi-Channel*

| *Filter 2*
| *Versand &gt; Versand ausschließlich durch FBA*
|

| *Filter 3*
| *Auftrag &gt; Herkunft*
| *_Wichtig:_* Keine Amazon-Herkunft wählen, da es sonst zu Doppelungen bei FBA-Aufträgen kommen kann.

| *Aktion*
| *Versand &gt; FBA-Versandfreigabe erteilen*
|
|====

Bei Wechsel in Status 5 wird Amazon mit der Ereignisaktion darüber informiert, dass die Ware zum Versand freigegeben ist. Amazon verschickt die Ware und das plentymarkets System erhält intern eine Bestätigung von Amazon. Der Auftrag wechselt in Status 5.1, wie in den <<Auftragseinstellungen vornehmen, Auftragseinstellungen>> festgelegt. Die Paketnummer wird in dein plentymarkets System importiert.

[TIP]
.Import von Paketnummern
====
Paketnummern werden einmal täglich importiert.
====

[#2400]
=== Bestand für Amazon Multi-Channel abgleichen

Im Menü *Einrichtung » Märkte » Amazon » Datenaustausch » FBA-Warenbestand* hast du die Möglichkeit, neben dem stündlichen automatischen Bestandsabgleich mit Amazon deinen Bestand mit einer automatischen Aktion oder per CSV-Datei abzugleichen.

[IMPORTANT]
.Nur für Amazon Multi-Channel
====
Dieses Feature ist nur für <<Amazon Multi-Channel einrichten, Amazon Multi-Channel>> vorgesehen.
====

In plentymarkets wird zwischen einem automatischen Bestandsabgleich und einem manuellen Bestandsabgleich unterschieden. Beide Verfahren werden folgend beschrieben.


[.tabs]
====
Bestand automatisch abgleichen::
+
--
Gehe wie im Folgenden beschrieben vor, um einen automatischen Bestandsabgleich durchzuführen.

[.instruction]
Bestand automatisch abgleichen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Datenaustausch » FBA-Warenbestand*.
. Wähle im Tab *Automatisch* das Amazon-Konto.
. Klicke auf *Amazon FBA-Bestand synchronisieren*.

Für den Prozess ist eine Zeitspanne von 4 Minuten vorgesehen. Werden die Daten nicht innerhalb dieser Zeitspanne von Amazon zur Verfügung gestellt, dann werden die Bestände nicht abgeglichen. Bei der nächsten Anforderung werden dann die vorher nicht übertragenen Daten verwendet, was zu Fehlern führen kann. Daher ist ein manueller Abgleich per CSV-Datei zu empfehlen wie im folgenden Kapitel beschrieben.

Es werden nur Bestände von Artikeln übernommen, die in den letzten 30 Tagen eine Bestandsänderung auf Amazon erfahren haben. Für den Erstimport empfehlen wir dir den manuellen Abgleich. Die Warenbestände werden gemäß der <<Basiseinstellungen vornehmen, Grundeinstellungen>> abgeglichen.
--

Bestand manuell abgleichen::
+
--
Bestände werden manuell per CSV-Datei abgeglichen.

[IMPORTANT]
.SKU-Zuordnung
======
Für den manuellen Bestandsabgleich muss die SKU-Zuordnung in den <<maerkte/amazon/amazon-einrichten#400, Grundeinstellungen>> eingegeben werden.
======

Bevor du diesen Abgleich durchführst, musst du bei Amazon in der Seller Central die entsprechende Berichtsdatei anfordern, herunterladen und die CSV-Datei auf deinem Rechner speichern.

[.instruction]
Bestand manuell abgleichen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Datenaustausch » FBA Warenbestand*.
. Wechsele in das Tab *Manuell*.
. Wähle das Amazon-Konto.
. Klicke auf *Datei auswählen*, um die soeben gespeicherte CSV-Datei zu wählen.
. *Speichere* (icon:save[role="green"]) die Einstellungen, um den Abgleich durchzuführen.
--
====
