= Adding plugins to the system
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plugins, extensions, functionality
:description: This is how you manage plugins in the plentymarkets back end.
:position: 10

[#purchasing-marketplace-plugins]
== Purchasing marketplace plugins

The link:http://marketplace.plentymarkets.com/en/[plentyMarketplace^] is our platform for distributing software extensions for plentymarkets developed by plentymarkets or external developers. This platform makes plugins easily accessible and ensures that you can benefit from the advantages the new technology offers. To purchase a plugin, proceed as follows.

[.instruction]
Purchasing plugins:

. Go to **Plugins >> Plugin overview**.
. Click on **plentyMarketplace**.
→ The market place will open in a new tab.
→ _Or_: Log in directly on link:http://marketplace.plentymarkets.com/en/[plentyMarketplace^] using your service centre credentials.
. Select a category and a plugin you want to purchase. For an overview of all categories, see the <<table-marketplace-categories>> table.
. In the detail view of the plugin, click on the **Go to checkout** button. For an overview of all purchase options, see the <<table-purchase-types>> table. +
→ The **Checkout** window opens.
. Accept the terms and conditions.
. Click on **Order now**. +
→ The purchased plugin is now available as an uninstalled plugin in the **Plugins » Plugin overview** menu.

[[table-marketplace-categories]]
.Marketplace categories
[cols="1,3"]
|====
|Category |Explanation

|*Channels >> Marketplaces*
|Plugins that connect to other marketplaces like Rakuten or idealo. For more information on how to set up marketplaces developed by plentymarkets, see the manual category *Markets*.

|*Channels >> Online stores*
|Connect your plentymarkets system to other shop systems like Shopify. Also includes templates, which form the foundation of your online store. For more information on templates developed by plentymarkets, see the manual category *Online store*.

|*Channels >> Price comparisons*
|Add export formats to the Elastic Export. For an overview of all export formats, see link:https://knowledge.plentymarkets.com/en/basics/data-exchange/elastic-export[here^].

|*Storefront >> Themes*
|Use themes to change the design of your online store.

|*Storefront >> Widgets*
|Add new elements like social media buttons or contact information to your online store.

|*Payment*
|Use payment plugins, so that your customers can pay for your products in different ways. For more information on how to install and set up a plugins, see that plugin’s description.

|*Integration*
|Add functionality to your system using external tools.

|*Services >> Support* +
*Services >> Setup*
|External agencies offer various services tailored to your specific needs.

|*Services >> Hardware*
|Purchase cash registers and other hardware for plentyPOS. For more information, see *POS*.
|====

[[table-purchase-types]]
.Purchase types
[cols="1,3"]
|====
|Type |Explanation

|*Free trial*
|Test the full plugin for free for 30 days. You can no longer test a plugin after subscribing to it at least once. You can check when your trial period expires in the *My Account* area.

|*Purchase*
|Buy the plugin once for a set price and use it forever. Developers may distinguish between different versions of the plugin, which may only offer limited functionality. Check the description to see which features are included in which version.

|*Subscription*
|Subscribing to a plugin allows you to use all of its features for a limited period of time. Depending on the plugin, you may be able to choose between different billing periods. Payment is always due at the beginning of a billing period. Subscriptions do not expire automatically, you have to cancel the contract in the *My Account* area if you want to discontinue it.
|====

[#adding-git-plugins]
== Adding plugins via Git

If you cannot find the plugin you need on plentyMarketplace, you can also add plugins from Git repositories. External developers may provide their plugins this way. For more information on available plugins, contact these developers directly. You can find an overview of certified partners link:https://www.plentymarkets.eu/service/partneragenturen/search/plugin-30/?aoff=s[here^], post in the search/offer link:https://forum.plentymarkets.com/c/suche-biete/suche-biete-plugins[category^] on the forums or create a link:https://marketplace.plentymarkets.com/plentyprojects[new enquiry^] on plentyMarketplace.

For private repositories, you need a personal access token in addition to the repository URL. This page only describes how to generate a personal access token on GitHub. However, the process is similar on other sites like GitLab. Refer to the respective site’s documentation for details.

[.instruction]
Creating a personal access token for private repositories:

. Go to your link:https://github.com/settings/tokens[token settings^] on GitHub.
. Click on *Generate new token*.
→ GitHub will ask you to confirm your password.
. Enter a *Token description*.
. Under *Select scopes*, activate *repo:status*.
. Click on *Generate token*.
→ GitHub will generate a new token. You will need this token in the next step, so either stay on the page or save the token locally. If you save the token, remember to delete it again once you have added the plugin to your system.

Now you have everything you need to add the plugin to your plentymarkets system.

[.instruction]
Adding a Git plugin to plentymarkets

. Go to *Plugins » Git*.
. Click on *Add new Repository*. +
→ The repository settings are displayed.
. Enter the repository URL and user name, as well as the access token you generated earlier, into the respective fields.
. Enter the branch you want to check out during installation. By default, plentymarkets checks out the master branch, but you should check with the plugin developer which branch name to enter and update the field accordingly.
. *Save* the settings.
→ plentymarkets checks and establishes the connection to the Git repository.

[NOTE]
.Public repositories
====
When adding a public repository, you do not need to enter any real credentials as user name and token. However, the respective text fields must not be empty, so enter an arbitrary values, e.g. "guest".
====

[[table-adding-git-plugins]]
.Table view of the menu **Plugins >> Git**
[cols="1,3"]
|====
|Setting |Explanation

|*Add new repository
|Opens a view for setting up a new repository.

|Git repository name
|Opens a view for changing the settings of the selected repository.

|**Delete**
|Removes the repository from the system. You cannot delete repositories if they are installed in any plugin sets.

|*Repository URL*
|HTTPS or HTTP URL of the Git repository

|*Username*
|The user name is part of the user data of the provider (e.g. GitHub) for the Git repository. +
For public repositories, enter any value into the field, e.g. *guest*.

|*Token*
|The token is part of the user data of the provider (e.g. GitHub) for the Git repository. You can create new tokens in your provider's settings. +
For public repositories, enter any value into the field, e.g. *guest*. +

|*Name of branch to be installed (must contain valid plugin.json file).*
|The Git repository has to include a valid plugin.json file. This input is required for the initial installation.
|====

[table-git-plugin-detail-view]]
.Tabellenansicht des Menüs **Plugins >> Plugin-Übersicht >> Plugin-Detailansicht >> Git**
[cols="1,3"]
|====
|Setting |Explanation

|**Fetch**
|Downloads all commits on the selected branch. The list of commits is updated accordingly.

|**Pull**
|Downloads all commits on the selected branch and updates all files. The list of commits is updated accordingly.

|**Branch**
|Dropdown menu to switch between branches of the repository. Displays the currently selected branch.

|**Commit ID**
|Text field for selecting specific commits.

|**Checkout**
|Switches branch to the commit specified in the **Commit ID** text field. Throws an error if the commit ID does not exist.

|Name of the commit
|You can switch to a commit by clicking on it. Requires confirmation.

|**Copy commit ID to clipboard.**
|Copies the ID of the commit to the clipboard, so that you can paste it into the **Commit ID** field.

|**View on GitHub**
|Opens a new tab to display the changes made in the commit.
|====

[#adding-git-plugins]
=== Adding git plugins to the system

[.instruction]
Git-Repository hinzufügen:

. Go to **Plugins >> Git**.
. Click on the **Add new Repository** button. +
→ The **Repository settings** view opens.
. Enter the URL of the git repository you want to add into the **Repository URL** field.
. Enter the name of your git account into the **Username** field. When adding a public repository, you can enter any string.
. Enter the password or token associated with your account into the **Password or Token** field. When adding a public repository, you can enter any string.
. Enter the name of the branch you want to select by default into the **Branch name for installation (Must contain valid plugin.json)** field. The **master** branch is entered by default. You can switch between branches of your repository after installing the plugin. Note that the selected branch must contain a valid plugin.json file. For more information on the plugin.json file, see our link:https://developers.plentymarkets.com/marketplace/plugin-requirements#marketplace-pluginjson[developers page^].
. **Save** the settings.

[NOTE]
.plugin.json file
====
Trying to build a plugin set with plugins that do not contain a valid plugin.json file results in an error. That is why it is necessary to ensure that plugins added via git contain a valid plugin.json file.
====

[#git-branches]
=== Switching between branches of a git plugin

When working with git repositories, it is normal to use multiple branches. This way, you can change files without affecting your primary code base and check new code again before really implementing it. plentymarkets also supports working with different branches of a repository.

[.instruction]
Switching branches:

. Go to **Plugins >> Plugin Overview**.
. Click on the plugin set you want to edit. +
→ This loads the plugin overview for the selected set.
. Click on the git plugin you want to edit. +
→ This loads the plugin detail view for the selected plugin.
. Go to **Git**.
. From the dropdown menu **Branch*, select the branch you want to switch to. +
→ A message confirms that you have successfully switched to the selected branch. These settings are saved automatically.

Branches are local settings. In other words, you can use the same plugin in multiple sets, but work with different branches. This is useful if you want to, for example, use a stable branch in your active plugin set and test a new feature in an inactive plugin set at the same time.

[#git-commits]
=== Switching to commits

If you want to work with a different version of your repository, but did not create a branch for that version, you can also switch to individual commits.

[.instruction]
Switching to commits:

. Go to **Plugins >> Plugin Overview**.
. Click on the plugin set you want to edit. +
→ This loads the plugin overview for the selected set.
. Click on the git plugin you want to edit. +
→ This loads the plugin detail view for the selected plugin.
. Go to **Git**.
. Copy the commit ID of the commit you want to switch to. The last 50 commits of the selected branch are displayed in the detail view. You can copy a commit ID by clicking on the **Copy commit ID to clipboard.” button in the row of the commit. If you want to switch to an older commit, you can do the same in the commits overview of your git repository.
. Paste the copied ID into the **Commit ID** field.
. Click on the checkout **Checkout** button. +
→ **_Or_**: If you want to switch to one of the last 50 commits, you can also click on the name of the commit and confirm the switch by clicking on the **Ok** button. +
→ A message confirms that you have successfully switched to the provided commit and **Head@Commit_ID** is displayed as branch. These settings are saved automatically.

[#deleting-git-plugins]
=== Removing git plugins from the system

If you longer need a git plugin, you can completely remove it from the system. Note that you cannot remove plugins that are still installed in any plugin sets.

[.instruction]
Deleting a git repository:

. Go to **Plugins >> Git**.
. Click on the **Delete** button to remove the repository from your system.