= Adding plugins to the system
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plugins, extensions, functionality
:description: This is how you manage plugins in the plentymarkets back end.
:position: 10
:url: plugins/adding-plugins

[#purchasing-marketplace-plugins]
== Purchasing marketplace plugins

The link:http://marketplace.plentymarkets.com/en/[plentyMarketplace^] is our platform for distributing software extensions for plentymarkets developed by plentymarkets or external developers. This platform makes plugins easily accessible and ensures that you can benefit from the advantages the new technology offers. To purchase a plugin, proceed as follows.

include::./_textblocks/instructions/marketplace-plugin-kaufen-en_gb.adoc[]

[[table-marketplace-categories]]
include::./_textblocks/tables/marketplace-kategorien-en_gb.adoc[]

[[table-purchase-types]]
include::./_textblocks/tables/marketplace-kaufoptionen-en_gb.adoc[]

[#adding-git-plugins]
== Adding plugins via Git

If you cannot find the plugin you need on plentyMarketplace, you can also add plugins from Git repositories. External developers may provide their plugins this way. For more information on available plugins, contact these developers directly. You can find an overview of certified partners link:https://www.plentymarkets.eu/service/partneragenturen/search/plugin-30/?aoff=s[here^], post in the search/offer link:https://forum.plentymarkets.com/c/suche-biete/suche-biete-plugins[category^] on the forums or create a link:https://marketplace.plentymarkets.com/plentyprojects[new enquiry^] on plentyMarketplace.

include::./_textblocks/tables/git-repository-verwaltung-en_gb.adoc[]

include::./_textblocks/tables/git-plugin-detailansicht-en_gb.adoc[]

[#adding-git-plugins]
=== Adding Git repositories to the system

For private repositories, you need a personal access token in addition to the repository URL. This page only describes how to generate a personal access token on GitHub. However, the process is similar on other sites like GitLab. Refer to the respective site’s documentation for details.

[.collapseBox]
.GitHub access token
--
include::./_textblocks/instructions/git-zugriffstoken-github-en_gb.adoc[]
--

[.collapseBox]
.Bitbucket access token
--
include::./_textblocks/instructions/git-zugriffstoken-bitbucket-en_gb.adoc[]
--

Now you have all the necessary information to add the repository to your system.

include::./_textblocks/tips/git-oeffentliches-repository-en_gb.adoc[]

include::./_textblocks/instructions/git-repository-hinzufuegen-en_gb.adoc[]

include::./_textblocks/warnings/git-valide-plugin-json-en_gb.adoc[]

[#git-branches]
=== Switching between branches of a Git repository

When working with git repositories, it is normal to use multiple branches. This way, you can change files without affecting your primary code base and check new code again before really implementing it. plentymarkets also supports working with different branches of a repository.

include::./_textblocks/instructions/git-branch-wechseln-en_gb.adoc[]

Branches are local settings. In other words, you can use the same plugin in multiple sets, but work with different branches. This is useful if you want to, for example, use a stable branch in your active plugin set and test a new feature in an inactive plugin set at the same time.

[#git-commits]
=== Switching to commits

If you want to work with a different version of your repository, but did not create a branch for that version, you can also switch to individual commits.

include::./_textblocks/instructions/git-commit-wechseln-en_gb.adoc[]

[#deleting-git-plugins]
=== Removing Git repositories from the system

If you longer need a git plugin, you can completely remove it from the system. Note that you cannot remove plugins that are still installed in any plugin sets.

include::./_textblocks/instructions/git-repository-loeschen-en_gb.adoc[]