= Setting up plugins
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Plugins, Extensions, Functions
:description: This is how you manage plugins in the plentymarkets back end.
:position: 30
:url: plugins/plugins

[#plugin-configuration]
== Plugin configuration

After installing a plugin, you may need to configure it. Depending on the plugin, you will have one of two options. Either, when clicking on the name of the plugin in the plugin set, a window with configuration options opens, or a new interface is added to the *System settings* menu when installing the plugin. Any setting you change within a plugin set only applies to that specific set. Any setting you change in the *System settings* menu applies globally and affects all plugin sets, even when installing the plugin in a set at a later time.

include::./_textblocks/importants/plugin-konfigurationsausnahmen-en_gb.adoc[]

[#configuration-export-import]
=== Export and import

If you want to use the same plugin in more than one set, you cannot copy the configuration from an already set up set. You can, however, export the configuration and import it to the new one afterwards.

include::./_textblocks/instructions/plugin-konfiguration-exportieren-en_gb.adoc[]

include::./_textblocks/importants/export-systemeinstellungen-en_gb.adoc[]

include::./_textblocks/instructions/plugin-konfiguration-importieren-en_gb.adoc[]

include::./_textblocks/warnings/import-limitierung-en_gb.adoc[]

==== Plugin set configuration

If you do not only need the configuration of one plugin, but of all plugins of the same plugin set, you can export and import them all at once. For this, go to **Plugin set settings** and proceed as described above to export and import configurations.

[#container-links]
== Container links

If a plugin adds new elements to your online store, such as the logo of a payment method, certain services must be linked to so-called containers.

By default, you can configure container links in the *CMS* » *Container links* menu,  but plugin developers can also provide a set of default containers which you can then select in the plugin detail view all at once.

include::./_textblocks/instructions/standard-container-verknuepfung-en_gb.adoc[]

You can check if it is possible to link containers this way in the plugin's item view on plentyMarketplace.

include::./_textblocks/warnings/vorhandene-verknuepfungen-geschuetzt-en_gb.adoc[]