= Setting up plugins
:lang: en
include::{includedir}/_header.adoc[]
:keywords: plugins, extensions, functionality
:description: This is how you manage plugins in the plentymarkets back end.
:position: 30
:url: plugins/plugins

[#plugin-configuration]
== Plugin configuration

After installing a plugin, you might want to configure it. Depending on the plugin, you will have one of two options. Either, when clicking on the name of the plugin in the plugin set, a window with configuration options opens, or a new interface is added to the *System* menu when installing the plugin. Any options you change within a plugin set only applies to that specific set. Any options you change in the *System* menu apply globally and affect all plugin sets, even when installing the plugin in a set at a later time.

[NOTE]
.Exceptions
====
For plugins developed before the introduction of plugin sets, configuration may be different.
====

[#container-links]
== Container links

If a plugin adds new elements to your webshop, such as the logo of a payment method, certain services must be linked to so-called containers.

By default, you can configure container links in the *CMS* >> *Container links* menu, but plugin developers can also provide a set of default containers which you can then select in the plugin detail view all at once.

[.instruction]
Select default container links:

. Go to *Plugins* >> *Plugin Overview*.
. Open the plugin detail view of the plugin you want to link by clicking on that plugin’s name.
. Click on the Default container links button.
. Check the checkboxes of the containers you want to link.
. Save the settings.

You can check if it is possible to link containers this way in the plugin's item view on plentyMarketplace.

[WARNING]
.Does not overwrite existing links
====
Saving the default container links does not overwrite existing links. If you want to use only the default container links, you must first delete all links in the *CMS* >> *Container links* menu.
====