= Setting up plugins
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Plugins, Extensions, Functions
:description: This is how you manage plugins in the plentymarkets back end.
:position: 30
:url: plugins/plugins

[#plugin-configuration]
== Plugin configuration

After installing a plugin, you may need to configure it. Depending on the plugin, you will have one of two options. Either, when clicking on the name of the plugin in the plugin set, a window with configuration options opens, or a new interface is added to the *System settings* menu when installing the plugin. Any setting you change within a plugin set only applies to that specific set. Any setting you change in the *System settings* menu applies globally and affects all plugin sets, even when installing the plugin in a set at a later time.

[NOTE]
.Exceptions
====
For plugins developed before the introduction of plugin sets, configuration may be different.
====

[#configuration-export-import]
=== Export and import

If you want to use the same plugin in more than one set, you cannot copy the configuration from an already set up set. You can, however, export the configuration and import it to the new one afterwards.

[.instruction]
Exporting the plugin configuration:

. Go to *Plugins* » *Plugin overview*.
. Open the plugin detail view of the plugin whose configuration you want to export by clicking on that plugin’s name.
. Click on the *Configuration export/import* button.
. Click on *Export configuration*. +
→ A JSON file containing the configuration is downloaded.

[NOTE]
.System settings
====
During export, only settings from the plugin detail view are exported. Settings from the *System settings* menu are not.
====

[.instruction]
Importing the plugin configuration:

. Go to *Plugins* » *Plugin overview*.
. Open the plugin detail view of the plugin whose configuration you want to import by clicking on that plugin’s name.
. Click on the *Configuration export/import* button.
. Click on the *Select file* button and select the file you want to import.
. Click on *Import configuration*.
→ The configuration is imported.

[WARNING]
.Limitations
====
A valid JSON file is required for import.

If the plugin version changes between export and import and configuration options were removed or renamed between versions, some settings may not be imported.
====

==== Plugin set configuration

If you do not only need the configuration of one plugin, but of all plugins of the same plugin set, you can export and import them all at once. For this, go to **Plugin set settings** and proceed as described above to export and import configurations.

[#container-links]
== Container links

If a plugin adds new elements to your online store, such as the logo of a payment method, certain services must be linked to so-called containers.

By default, you can configure container links in the *CMS* >> *Container links* menu,  but plugin developers can also provide a set of default containers which you can then select in the plugin detail view all at once.

[.instruction]
Selecting default container links:

. Go to *Plugins* » *Plugin overview*.
. Open the plugin detail view of the plugin you want to link by clicking on that plugin’s name.
. Click on the *Default container links* button.
. Check the checkboxes of the containers you want to link.
. *Save* the settings.

You can check if it is possible to link containers this way in the plugin's item view on plentyMarketplace.

[WARNING]
.Does not overwrite existing links
====
Saving the default container links does not overwrite existing links. If you want to use only the default container links, you must first delete all links in the *CMS* >> *Container links* menu.
====