////
Nutzung:

:rights-purpose: Wofür werden die Rechte benötigt?
:right-one: *CRM > Kampagne > Code > Anzeigen*

include::PFAD_ZUR_DATEI/rechte.adoc[]

Die Attribute :right-one: bis :right-nine: enthalten die Pfade für die benötigten Rechte.
Wenn weniger als neun Rechte benötigt werden, gib das Attribut nicht an.
////

//tag::one[]

Benutzer:innen vom Typ *Backend* <<business-entscheidungen/benutzerkonten-zugaenge#105, sehen nur bestimmte Bereiche und Menüs>> in plentymarkets. Sie können also nur eingeschränkt im System arbeiten. Sollen Mitarbeiter:innen mit dem Zugang *Backend* {rights-purpose}, benötigen diese Mitarbeiter:innen mindestens die folgenden Rechte:

ifdef::right-one[]
* {right-one}
endif::[]
ifdef::right-two[]
* {right-two}
endif::[]
ifdef::right-three[]
* {right-three}
endif::[]
ifdef::right-four[]
* {right-four}
endif::[]
ifdef::right-five[]
* {right-five}
endif::[]
ifdef::right-six[]
* {right-six}
endif::[]
ifdef::right-seven[]
* {right-seven}
endif::[]
ifdef::right-eight[]
* {right-eight}
endif::[]
ifdef::right-nine[]
* {right-nine}
endif::[]

//end::one[]

[.collapseBox]
.Tipp: So vergibst du Rechte
--

//tag::two[]

Beachte, dass nur *Admin*-Benutzer:innen Rechte vergeben können.

[.instruction]
Rechte vergeben:

. Öffne das Menü *Einrichtung » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Übersicht wird geöffnet.
. Wähle eine:n Benutzer:in. +
→ Der Menüpunkt *Rechte* mit den Sichtbarkeiten wird geöffnet.
. Vergib die Rechte für den jeweiligen Bereich durch Anklicken der Checkboxen, die oben angegeben sind. +
*_Hinweis_*: Du kannst entweder Rechte für einen kompletten Bereich vergeben oder dem Konto nur eingeschränkt Rechte gewähren. Klappe für diese Option den Bereich auf.
. Speichere (icon:save[role="green"]) die Einstellungen.

[TIP]
======
Die Bereiche *Berechtigungen* und *Menü-Sichtbarkeiten* sind verknüpft. Wenn du also Rechte in einem der beiden Bereiche aktivierst, sind sie automatisch auch für den anderen Bereich aktiv.
======

//end::two[]

--

//tag::three[]

:!right-one:
:!right-two:
:!right-three:
:!right-four:
:!right-five:
:!right-six:
:!right-seven:
:!right-eight:
:!right-nine:

//end::three[]
