= Entwurf-Sina2
:lang: en
include::{includedir}/_header.adoc[]
:description: Our extensive manual provides detailed information about every area in your plentymarkets system.
:position: 11

== Understanding and exploring plentymarkets

The plentymarkets manual supports users every step of the way. Whether you are just beginning to set up your system or you are adding complex processes to help your business run more efficiently. The manual groups plentymarkets functions thematically and describes all of the menus where settings need to be carried out. For example, all of the steps necessary for setting up a market are described on one page. Our video tutorials also supplement the manual. They provide general introductions to new topics or additional descriptions and explanations of specific functions. The new topical structure mirrors the modules offered in plentymarkets:

* <<working-with-plentymarkets#,   >>
* <<multi-channel#,   >>
*

[.collapseBox]
.Manual structure and conventions
--
The manual is intended for users of the software, i.e. people who have access to the plentymarkets backend. plentymarkets is continuously being developed further and these improvements are released on a regular basis. Therefore, the descriptions in this manual may deviate slightly from your backend. This manual intentionally leaves out explanations for some settings. Self-explanatory settings such as where to enter a name, street address, etc. are not described here. Moreover, the manual does not provide any information about the scope of services provided by plentymarkets partners. It is only describes how to set up the interfaces to these partners. Ask the partner directly about the scope of services provided before you begin setting up the interface.

[.row]
=====
[.col-md-6]
.Formatting
======
*  Menu paths as well as terms and expressions that appear in the software are shown in **bold**.
*  Image and table captions are shown in __italics__.
*  Red boxes indicate danger such as possible data loss.
*  Yellow boxes indicate possible errors or faulty configurations.
*  Green boxes provide examples or alternate settings. Normally, these notes do not require you to take any action.
======

[.col-md-6]
.Screenshots
======
The manual occasionally uses screenshots of websites or input masks. These screenshots show the settings as they appear in the web browsers Mozilla Firefox or Google Chrome under the operating system Mac OS X. If you use a different operating system or web browser, then the settings may be displayed slightly differently on your own computer. The screenshots only show example configurations. The settings displayed in these images may deviate from the settings you want to carry out.
======
=====

[.row]
=====
[.col-md-6]
. Search
======
Type your search term into the entry field in the upper right corner of the manual.
======

[.col-md-6]
. Setting up an event procedure
======
Click on the title to expand these frequently recurring instructions and see the individual steps.
======
=====
--

[.row]
====
[.col-md-12]
.plentymarkets changelog
=====
The changelog provides you with an overview of all the new features, changes and improvements included in the current plentymarkets version. Furthermore, the changelog lets you know if you should check your settings and make sure that they are configured correctly for new features.

link::/[Open changelog]
=====
====
