= CMS-Syntax
:lang: de
include::{includedir}/_header.adoc[]
:position: 160

== Allgemeines

Bei der CMS-Syntax handelt es sich um eine Skriptsprache, die aktuell in den Bereichen **Webdesign**, **Kategorien** und **E-Mail-Vorlagen** in plentymarkets verwendet wird. Die CMS-Syntax wurde mit der plentymarkets-Version 5.1 eingeführt und wird seitdem schrittweise um weitere Sprachkonstruktionen und Funktionen erweitert.

'''

[.row]
====
[.col-md-4]
.Grundlagen
=====
<<omni-channel/online-shop/cms-syntax/grundlagen/compiler#, Compiler  >> +
<<omni-channel/online-shop/cms-syntax/grundlagen/code-block#, Block  >> +
<<omni-channel/online-shop/cms-syntax/grundlagen/kommentar#, Kommentar  >>
=====

[.col-md-4]
.Typen
=====
<<omni-channel/online-shop/cms-syntax/grundlagen/typen#, Primitive Typen  >>
=====

[.col-md-4]
.Variablen
=====
<<omni-channel/online-shop/cms-syntax/grundlagen/variablen#, Eigene Variablen  >> +
<<omni-channel/online-shop/cms-syntax/grundlagen/template-variablen#, Template-Variablen  >>
=====
====

[.row]
====
[.col-md-4]
.Operatoren
=====
<<omni-channel/online-shop/cms-syntax/grundlagen/operatoren#, Operatoren  >>
=====

[.col-md-4]
.Kontrollstrukturen
=====
<<omni-channel/online-shop/cms-syntax/grundlagen/if#, if/elseif/else  >> +
<<omni-channel/online-shop/cms-syntax/grundlagen/for#, for  >>
=====

[.col-md-4]
.Funktionen
=====
<<omni-channel/online-shop/cms-syntax/grundlagen/template-funktionen#, Template-Funktionen  >>
=====
====
== Templates

Alle Templates zur Gestaltung Ihres Online-Shops und Ihrer E-Mailvorlagen finden Sie auf den folgenden Seiten.

[.row]
====
[.col-md-4]
.Global
=====
In diesem Bereich finden Sie PHP-Funktionen, welche sowohl im Bereich Webdesign und E-Mail verwendet werden können.

<<omni-channel/online-shop/cms-syntax/global/phpfunctions#, PHP Funktionen öffnen  >>
=====

[.col-md-4]
.Webdesign
=====
Dieser Bereich ist in mehrere Unterbereiche gegliedert. Sie finden darüber alle Templates und Funktionen zur Gestaltung Ihres Online-Shops.

<<omni-channel/online-shop/cms-syntax/webdesign#, Webdesign öffnen  >>
=====

[.col-md-4]
.E-Mail
=====
Liste der Template-Variablen und –Funktionen für die Gestaltung von E-Mail-Vorlagen.

<<omni-channel/online-shop/cms-syntax/e-mail/email#, E-Mail öffnen  >>
=====
====
