= Globale Einstellungen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Mandant, Webshop, Globale Einstellungen
:position: 30

**plentymarkets » Einstellungen » Mandant (Shop) » Globale Einstellungen**

== Inhalt dieses Kapitels

In diesem Kapitel finden Sie Informationen zu den globalen Einstellungen, die sich auf die Bereiche Ihres Webshops sowie auf alle Mandanten auswirken bzw. die übergreifend gültig sind.

Sie erhalten Informationen zu **<<omni-channel/online-shop/globale-einstellungen/sprachpakete#, Sprachpaketen  >>**, mit denen Sie verschiedene vom System generierte Nachrichten und Meldungen bearbeiten können, und zur Konfiguration des **<<omni-channel/online-shop/globale-einstellungen/ftp-zugang#, FTP-Zugangs  >>** für Ihr System. Außerdem erhalten Sie eine Übersicht über die Grundkonfiguration von **<<omni-channel/online-shop/globale-einstellungen/externe-dienste#, externen Diensten  >>** wie **<<omni-channel/online-shop/globale-einstellungen/externe-dienste/facebook#, Facebook  >>** oder **<<omni-channel/online-shop/globale-einstellungen/externe-dienste/twitter#, Twitter  >>**. Darüber hinaus erhalten Sie Informationen zu Einstellungen, die zur Nutzung von **<<omni-channel/online-shop/globale-einstellungen/gewinnspiel#, Gewinnspielen  >>** oder zum **<<omni-channel/online-shop/globale-einstellungen/live-shopping#, Live-Shopping  >>** hinterlegt werden müssen.

== Verbindungen zu anderen Menüs

Um **<<artikel/artikel-verwalten#90, Artikelbilder >>**, **<<auftragsabwicklung/auftraege/einstellungen/dokumente#, PDF-Dokumente  >>** und andere Dateien online für alle Besucher verfügbar zu machen, müssen diese von Ihrem Rechner auf den plentymarkets-Server übertragen werden. Für das Hochladen beliebiger Dateien auf einen Webserver wird das File Transfer Protocol (FTP) verwendet. Hinterlegen Sie die Einstellungen entsprechend des **<<omni-channel/online-shop/globale-einstellungen/ftp-zugang#, FTP-Zugangs  >>**.

== Wichtige Seiten zum Thema direkt aufrufen

* <<omni-channel/online-shop/globale-einstellungen/sprachpakete#, **Sprachpakete**  >>
* <<omni-channel/online-shop/globale-einstellungen/ftp-zugang#, **FTP-Zugang**  >>
* <<omni-channel/online-shop/globale-einstellungen/externe-dienste#, **Dienste**  >>
* **<<omni-channel/online-shop/globale-einstellungen/externe-dienste/facebook#, Facebook  >>**
* **<<omni-channel/online-shop/globale-einstellungen/externe-dienste/twitter#, Twitter  >>**
* <<omni-channel/online-shop/globale-einstellungen/live-shopping#, **Live-Shopping**  >>
* **<<omni-channel/online-shop/globale-einstellungen/statistik#, Statistik  >>**

