= Mandanten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, Standard
:position: 20
:nav-alias: Mandanten einrichten


**plentymarkets » Einstellungen » Mandant (Shop) » Standard**

== Inhalt dieses Kapitels

In diesem Kapitel finden Sie die verschiedenen Grundeinstellungen zur Konfiguration Ihres **<<omni-channel/online-shop/mandanten-einrichten/webshop#, Webshops  >>**. Neben der Konfiguration des **<<crm/e-mails-versenden#700, E-Mail-Dienstes >>** können Sie hier verschiedene Einstellungen zu Ihrem Standard-Webshop hinterlegen. Von besonderer Bedeutung sind in diesem Kapitel die Einstellungen zur **<<omni-channel/online-shop/cms-syntax#fallbeispiele-seo-guide, Suchmaschinenoptimierung  >>**, mit denen Sie Ihren Webshop im Internet optimal auffindbar machen. Darüber hinaus werden in diesem Kapitel Grundeinstellungen zur Verwendung von **<<artikel/kategorien#, Kategorien  >>** sowie zum **<<omni-channel/online-shop/mandanten-einrichten/mein-konto#, Mein Konto  >>**-Bereich und zum **<<omni-channel/online-shop/mandanten-einrichten/bestellvorgang#, Bestellvorgang  >>** erläutert. Auch Informationen zu den Grundeinstellungen Ihrer <<omni-channel/online-shop/mandanten-einrichten/artikelansichten#, **Artikelansichten**  >> entnehmen Sie diesem Kapitel.

[TIP]
.Tipp
====
Jeder weitere Webshop bzw. Mandant (Shop) wird in einer eigenen Menüstruktur analog zu diesem Menü konfiguriert. Die Menübezeichnung wird entsprechend der Bezeichnung des Webshops automatisch vom System vorgenommen.
====



**plentymarkets » Einstellungen » Mandant (Shop) » Standard » Grundeinstellungen**

[#grundeinstellungen]
== Grundeinstellungen

In diesem Menü werden die IDs Ihres Webshops angezeigt sowie weitere Grunddaten, wie der Webstore-Typ und die Domain. Der hinterlegte Name des Webshops ist hier änderbar.

[WARNING]
.Benutzer werden ausgeloggt
====
Wenn Sie in diesem Menü Änderungen vornehmen, werden andere Benutzer automatisch ausgeloggt und müssen sich neu einloggen, damit die Änderungen auch für diese Benutzerprofile greifen. Kündigen Sie Änderungen daher ggf. weiteren Benutzern an.
====

== Konfiguration

Nehmen Sie die Konfiguration gemäß der nachfolgenden Tabelle vor.

[cols="a,a"]
|====
|Einstellung |Erklärung

|**Webstore-ID**
|Die Webstore-ID ist die ID des Webshop bzw. Mandant (Shop). Die Webstore-ID eines Mandant (Shop) wird in den Grundeinstellungen des betreffenden Shops angezeigt. +
Standard-Webshop = **0** +
Erster Mandant (Shop) = **1** +
Zweiter Mandant (Shop) = **2** +
usw. +
Ein externer Shop erhält ebenfalls eine Webstore-ID.

|**plenty-ID**
|Hier wird die ID des plentymarkets-Systems angezeigt.

|**Webstore-Typ**
|Anzeige des Webstore-Typ, **plentymarkets** oder **Shopware**.

|**Domain**
|Hier wird die URL der Domain des Webshops angezeigt. Über das **Auge** wird der Webshop aufgerufen.

|**Name**
|Name des Webshops.

|**Standard-Sprache**
|Die Standard-Sprache des Webshops wählen.

|**Standard-Standort**
|Den Standort wählen, der als Standard gelten soll. Dieser wird dann z.B. auch im Bestellvorgang im Webshop verwendet, was u.a. die Anzeige der MwSt. beeinflusst. Ein Standort, der hier als Standard hinterlegt wird, ist nicht löschbar.

|**eBay-Konto**
|Das oder die eBay-Konten wählen, die mit diesem Shop verknüpft werden sollen. Die Aufträge dieses eBay-Kontos werden automatisch diesem Shop zugeordnet. +
**Wichtig**: Wenn dasselbe eBay-Konto bei zwei verschiedenen Shops ausgewählt werden soll, werden die Aufträge dem Shop mit der niedrigeren ID zugeordnet.
|====

__Tab. 1: Grundeinstellungen eintragen__



== Verbindungen zu anderen Menüs

Für die Arbeit mit dem **<<crm/ticketsystem-nutzen#, Ticketsystem  >>** bzw. für das Versenden eines **<<crm/newsletter-versenden#, Newsletters  >>** müssen Sie Ihre Konfigurationen im Bereich **<<crm/e-mails-versenden#, E-Mail  >>** hinterlegt haben. Darüber hinaus legen Sie mit den Einstellungen im Bereich Artikelansichten den Grundstein für die Verwaltung Ihrer **<<artikel#, Artikel  >>**.

== Video-Tutorials

Erfahren Sie mehr über das Menü **E-Mail** im folgenden Videotutorial:

[.linkBox]
link:https://www.plentymarkets.eu//www.plentymarkets.eu/a-2842/[E-Mail-Konfiguration, window="_blank"]

Erfahren Sie mehr zum Menü **Buchhaltung** in plentymarkets im folgenden Video-Tutorial:

[.linkBox]
link:https://www.plentymarkets.eu/a-3345/[Buchhaltung, window="_blank"]

Wichtige Seiten zum Thema direkt aufrufen

// TODO: enable link after enabling '_multilingualismus.adoc'
// * **<<omni-channel/online-shop/mandanten-einrichten/mehrsprachiger-webshop#, Multilingualismus  >>**
* **<<omni-channel/online-shop/mandanten-einrichten/webshop#rechtliche-angaben#, Rechtliche Angaben  >>**
* <<crm/e-mails-versenden#100, **Zugangsdaten** >>
* **<<crm/e-mails-versenden#1200, E-Mail-Vorlagen >>**
* <<omni-channel/online-shop/mandanten-einrichten/artikelansichten#, **Artikelansichten**  >>
* **<<omni-channel/online-shop/cms-syntax#40, URL-Aufbau >>**
* **<<omni-channel/online-shop/cms-syntax#120120, sitemap-XML >>**
* <<artikel/kategorien#, **Kategorien**  >>
* <<omni-channel/online-shop/mandanten-einrichten/mein-konto#, **Mein Konto**  >>
* <<omni-channel/online-shop/mandanten-einrichten/bestellvorgang#, **Bestellvorgang**  >>
// TODO: rename link label?
* <<omni-channel/online-shop/extras#, **Externe Dienste**  >>
* **<<omni-channel/online-shop/extras/trusted-shops#, Trusted Shops  >>**
* **<<omni-channel/online-shop/mandanten-einrichten/module#, Module  >>**

