= Shop Builder einrichten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, Standard, Ceres, IO, Plugin, Konfiguration, Template, Startseite, Drag and Drop, Baukasten, Shop Builder, ShopBuilder, Artikellisten
:position: 56

[#10]
Der Shop Builder ist plentymarkets Baukastenmodul mit dem Sie Ihren link:https://marketplace.plentymarkets.com/plugins/templates/Ceres_4697[Ceres Webshops^] schnell und einfach per Drag&Drop erstellen und bearbeiten können. Dafür sind keinerlei Programmierungskenntnisse nötig.

[WARNING]
.Versionsvoraussetzungen für den Shop Builder
====
Der Shop Builder ist erst ab Version 2.8.1 von Ceres und IO verfügbar. Sollten Sie eine ältere Version benutzen, besuchen Sie den link:https://marketplace.plentymarkets.com[plentyMarketplace^], um die jeweils aktuelle Version zu installieren.
====

[NOTE]
.Funktionsumfang des Shop Builders
====
Zum gegenwärtigen Zeitpunkt kann ausschließlich die Startseite Ihres Ceres Webshops über den Shop Builder bearbeitet werden. Der Funktionsumfang des Shop Builders wird nach und nach erweitert und in Zukunft wird es möglich sein, des gesamten Ceres Shop darüber zu bearbeiten.
====

[NOTE]
.Anzeigen der mit dem Shop Builder erstellten Startseite
====
Beachten Sie, dass die im Shop Builder erstellte Startseite erst aktiviert werden muss. Hierzu wählen Sie unter *CMS » Shop Builder » Übersicht » Einstellungen » Startseite* die Option *Shop Builder Startseite anzeigen* und deaktivieren Sie die Option *Standardstartseite anzeigen*.
====


[#20]
== Ceres-Startseite mit dem Shop Builder bearbeiten

Im Vorschaubereich können Sie der Startseite Elemente hinzufügen, um die Seite Ihren individuellen Bedürfnissen anzupassen.

[.instruction]
Elemente zum Vorschaubereich hinzufügen:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Der Shop Builder wird geöffnet.
. Klicken Sie auf *Startseite*. +
	→ Der Vorschaubereich der Startseite wird geöffnet.
. Ziehen Sie per Drag&Drop Elemente von der linken Seite in den Vorschaubereich. Beachten Sie dazu die Erläuterungen in <<tabelle-elemente-shop-builder>>. +
→ Neue Elemente werden automatisch am unteren Ende hinzugefügt oder können in ein Strukturelement gezogen werden.
. *Speichern* Sie die Einstellungen. +
→ Die Startseite Ihres Webshops wird mit den gewählten Elementen dargestellt.

Der Shop Builder beinhaltet Strukturelemente, die das Layout der Seite gliedern und sogenannte Widgets, also verschiedenen Seitenelementen, mit denen die Strukturelemente befüllt werden können. Die folgende Tabelle erklärt diese Elemente im Detail:


[[tabelle-elemente-shop-builder]]
.Elemente des Shop Builders
[cols="1,3"]
|====
|Element |Erläuterung

2+|*Struktur-Elemente*

|*2 Felder*
|Stellt ein Strukturelement mit 2 Feldern zur Verfügung, die mit den unten aufgeführten Widgets befüllt werden können. Klicken Sie auf *Bearbeiten*, um das Layout des Elements zu ändern. Wählen Sie aus der Dropdown-Liste *Layout* das gewünschte Größenverhältnis der Felder.

|*3 Felder*
|Stellt ein Strukturelement mit 3 Feldern zur Verfügung, die mit den unten aufgeführten Widgets befüllt werden können. Klicken Sie auf *Bearbeiten*, um das Layout des Elements zu ändern. Wählen Sie aus der Dropdown-Liste *Layout* das gewünschte Größenverhältnis der Felder. Bei *gestapelten* Verhältnissen werden 2 Felder übereinander angezeigt.

|*4 Felder*
|Stellt ein Strukturelement mit 4 Feldern zur Verfügung, die mit den unten aufgeführten Widgets befüllt werden können. Das Größenverhältnis der Felder ist nicht anpassbar.
2+|*Widgets*

|*Titelleiste*
|Dieses Widget stellt eine Textbox zur Verfügung. Klicken Sie auf *Bearbeiten*, um Text einzugeben und die <<#616, Farbe>> der Titelleiste zu ändern. Es kann nur Reintext verwendet werden.

|*Bilderkarussell*
|Stellt das Ceres-Bilderkarussell zur Verfügung. Klicken Sie auf *Bearbeiten*, um Bilder hinzuzufügen oder zu entfernen. Bilder können über die Kategorieauswahl, die Eingabe der Varianten-ID oder die Dateiauswahl gewählt werden. Wenn das Bild über die Kategorieauswahl bestimmt wird, wird das erste im Tab Dokumente abgelegte Bild der Kategorie verwendet. Bestimmen Sie über die Dropdown-Liste *Erscheinungsbild* die <<#616, Farbe>> des Bilderkarussells.

|*Bilderbox*
|Stellt einen Container für Bilder zur Verfügung. Klicken Sie auf *Bearbeiten*, um Bilder hinzuzufügen oder zu entfernen. Bilder können über die Kategorieauswahl, die Eingabe der Varianten-ID oder die Dateiauswahl gewählt werden. Wenn das Bild über die Kategorieauswahl bestimmt wird, wird das erste im Tab Dokumente abgelegte Bild der Kategorie verwendet. Bestimmen Sie über die Dropdown-Liste *Erscheinungsbild* die <<#616, Farbe>> der Bilderbox. Über die Dropdown-Listen *Stil der Box* und *Größe des Bilds* passen Sie das Widget hinsichtlich Text- und Bildgröße an.

|*Artikelliste*
|Stellt die <<omni-channel/online-shop/ceres-einrichten#110, Ceres Artikelliste>> zur Verfügung. Klicken Sie auf *Bearbeiten*, um Bilder hinzuzufügen oder zu entfernen. Für die Startseite können Artikellisten mit Kategorieartikeln, zuletzt angesehenen Artikeln oder über Tags definierte Artikellisten konfiguriert werden. Bestimmen Sie die Art der Sortierung über die *Artikelsortierung* Dropdown-Liste und legen Sie die *Maximale Anzahl der angezeigten Artikel* fest.

|*Text*
|Stellt eine Textbox zur Verfügung. Klicken Sie auf *Bearbeiten*, um Text einzugeben und die <<#616, Farbe>> der Textbox zu ändern. Im Texteditor kann Reintext und, nach Klick auf *</>*, auch HTML eingegeben werden. Es ist nicht möglich, CSS in diesem Widget einzubinden.

|*Top Bar* (Header)
|Stellt eine Top Bar zur Verfügung. Klicken Sie auf *Bearbeiten*, um die Einstellungen vorzunehmen und die Anzeige der Elemente, der Suche oder der Warenkorbinformationen zu bestimmen.

|*Kategorie-Navigation* (Header)
|Stellt eine Kategorie-Navigation zur Verfügung. Klicken Sie auf *Bearbeiten*, um die Einstellungen vorzunehmen und den Stil der Kategorie-Navigation, die Kategorieebenen sowie die Anzahl der Kategorien festzulegen. Des Weiteren kann ein Firmenlogo hinzugefügt werden.

|*Breadcrumbs* (Header)
|Stellt eine Breadcrumb-Navigation zur Verfügung. Klicken Sie auf *Bearbeiten*, um die Einstellungen vorzunehmen.

|*Liste*
|Stellt eine Liste zur Verfügung, die als Platzhalter dient. Klicken Sie auf *Bearbeiten*, um Listeneinträge oder Icons hinzuzufügen.

|*Linkliste*
|Stellt eine Linkliste zur Verfügung, die als Platzhalter dient. Klicken Sie auf *Bearbeiten*, um einen Listentitel, Listeneinträge oder Icons hinzuzufügen.

|*Trennlinie*
|Stellt eine Trennlinie zur Verfügung, die als Platzhalter dient.

|*Rechtliche Informationen* (Footer)
|Stellt die Anzeige der rechtlichen Informationen zur Verfügung. Klicken Sie auf *Bearbeiten*, um festzulegen, welche Elemente im Footer sichtbar sein sollen. Des Weiteren kann ein Widerrufsformular hochgeladen werden.
|====


=== Elemente der Ceres-Startseite mit dem Shop Builder bearbeiten

Im Vorschaubereich können Sie Elemente bearbeiten, um die Seite Ihren individuellen Bedürfnissen anzupassen.

[.instruction]
Elemente im Vorschaubereich bearbeiten:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Der Shop Builder wird geöffnet.
. Zeigen Sie mit der Maus auf das Element, das Sie bearbeiten wollen. +
→ Das Kontextmenü wird eingeblendet.
. Klicken Sie auf *Bearbeiten*. +
→ Die *Einstellungen*-Leiste wird eingeblendet.
. Nehmen Sie Einstellungen an den Elementen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-elemente-shop-builder>>.
. *Speichern* Sie die Einstellungen. +
→ Die Startseite Ihres Webshops ist den Einstellungen entsprechend umgestaltet.


Ebenso können Sie Elemente auch wieder entfernen.

[.instruction]
Elemente aus dem Vorschaubereich entfernen:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Der Vorschaubereich wird geöffnet.
. Zeigen Sie mit der Maus auf das Element im Vorschaubereich, das Sie entfernen wollen. +
	→ Das Kontextmenü wird eingeblendet.
. Klicken Sie auf *Löschen*, um das Element zu entfernen. +
	→ Das Element wird entfernt. +
	→ Die umliegenden Elemente gruppieren sich neu und ersetzen das gelöschte Element.
. *Speichern* Sie die Einstellungen. +
→ Die Startseite Ihres Webshops ist den Einstellungen entsprechend umgestaltet.


== Farbeinstellungen im Shop Builder bearbeiten

Im Shop Builder können Sie die Hauptfarben für alle Seiten Ihres Shops global verwalten.

[.instruction]
Farben im Shop Builder bearbeiten:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Der Shop Builder wird geöffnet.
. Klicken Sie auf *Startseite*. +
	→ Der Vorschaubereich der Startseite wird geöffnet.
. Klicken Sie auf *Globale Farbeinstellungen*. +
	→ Das Menü *Globale Farbeinstellungen bearbeiten* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-farben-shop-builder>>.
. *Speichern* Sie die Einstellungen.


[[tabelle-farben-shop-builder]]
.Globale Farbeinstellungen im Shop Builder
[cols="1,3"]
|====
|Element |Erläuterung

|*Primary colour*
|Dieses Attribut verändert die Primärfarbe des Shops. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. +
*_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.

|*Secondary colour*
|Dieses Attribut verändert die Sekundärfarbe des Shops. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. +
*_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.

|*Success colour*
|Dieses Attribut verändert die Farbe der Erfolgsmeldungen im Shop. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. +
*_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.

|*Information colour*
|Dieses Attribut verändert die Farbe der Hinweise im Shop. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. +
*_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.

|*Warning colour*
|Dieses Attribut verändert die Farbe der Warnmeldungen im Shop. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. +
*_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.

|*Danger colour*
|Dieses Attribut verändert die Farbe der Fehlermeldungen im Shop. Wählen Sie eine Farbe über den Colour Picker oder geben Sie einen Hexadezimalwert ein. +
*_Hinweis:_* Dieser Wert kann von Theme-Plugins für andere Farbgebungen verwendet werden.
|====

== Schriftart im Shop Builder bearbeiten

Der Shop Builder bietet ebenfalls die Möglichkeit, eine beliebige Schriftart auszuwählen. Dazu kann entweder eine Schrift-URL eingefügt oder eine Schrift hochgeladen werden.

[.instruction]
Schriftart bearbeiten:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Der Shop Builder wird geöffnet.
. Klicken Sie auf *Startseite*. +
→ Der Vorschaubereich der Startseite wird geöffnet.
. Klicken Sie auf *Design*. +
→ Das Fenster *Design* wird geöffnet.
. Nehmen Sie die Einstellungen im Feld *Schriften* vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schriftart-shop-builder>>.
. *Speichern* Sie die Einstellungen.


[[tabelle-schriftart-shop-builder]]
.Schriftart im Shop Builder bearbeiten
[cols="1,3"]
|====
|Option |Erläuterung

|*Schrift-URL einfügen*
|Wählen Sie eine URL und fügen Sie die URL in die entsprechende Zeile (regulär, *bold*, _italic_ oder *_bold-italic_*) ein.

|*Schrift hochladen*
|Hierzu müssen Sie eine Schriftart auf Ihrem Rechner gespeichert haben. Wählen Sie in der entsprechenden Zeile (regulär, *bold*, _italic_ oder *_bold-italic_*) die gewünschte Datei aus.
|====


== Weitere Einstellungen vornehmen

Der Shop Builder bietet ebenfalls die Möglichkeit, alle in der Ceres-Konfiguration möglichen Einstellungen vorzunehmen. Gehen Sie dazu wie folgt vor.

. Gehen Sie zu *CMS » Shop Builder*. +
→ Der Shop Builder wird geöffnet.
. Klicken Sie auf *Einstellungen*. +
→ Das Menü *Plugin-Konfiguration* wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<omni-channel/online-shop/ceres-einrichten#20, Ceres einrichten>>.
. *Speichern* Sie die Einstellungen. +


[TIP]
.Auswahl des Plugin-Sets im Shop Builder

In der Dropdown-Liste kann ein Plugin-Set ausgewählt werden. Die Seitenvorschau zeigt dann die für das Plugin-Set vorgenommenen Einstellungen an (z.B. welche Artikel sichtbar sind).


== Weitere Seiten im Shop Builder erstellen

In der Übersicht des Shop Builders gibt es die Möglichkeit, zusätzliche Seiten für die Startseite zu erstellen und zu benennen.

[.instruction]
Seite erstellen:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Die Übersicht des Shop Builders wird geöffnet.
. Klicken Sie auf *Seite hinzufügen*. +
→ Das Fenster *Seitenname* öffnet sich.
. Geben Sie einen Namen ein.
. *Speichern* Sie die Einstellungen. +
→ Die neu erstellte Seite wird in der Übersicht angezeigt.

=== Seite im Shop Builder bearbeiten

Zurzeit lässt sich in der Übersicht des Shop Builders lediglich der Name einer Seite bearbeiten. Zukünftig werden jedoch noch weitere Einstellungen hinzukommen.

[.instruction]
Seitenname bearbeiten:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Die Übersicht des Shop Builders wird geöffnet.
. Klicken Sie auf *Bearbeiten*, um den Seitennamen zu bearbeiten.
. Wählen Sie einen beliebigen Namen für die Seite.
. *Speichern* Sie die Einstellungen.

=== Seite im Shop Builder löschen

Im Shop Builder erstellte Seiten lassen sich auch wieder entfernen.

[.instruction]
Seite löschen:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Die Übersicht des Shop Builders wird geöffnet.
. Klicken Sie auf *Löschen*, um eine Seite zu löschen. +
→ Die Seite wird gelöscht.

=== Verknüpfung von im Shop Builder erstellten Seiten zur Startseite lösen

Jede im Shop Builder erstellte Seite ist automatisch mit der Startseite verknüpft. Diese Verknüpfung kann jedoch auch gelöst werden.

[.instruction]
Verknüpfung lösen:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Die Übersicht des Shop Builders wird geöffnet.
. Wählen Sie die Seite, deren Verknüpfung zur Startseite gelöst werden soll.
. Klicken Sie auf *Verknüpfung erstellen/lösen.* +
→ Die Verknüpfung zur Startseite wird gelöst.

=== Im Shop Builder erstellte Seiten mit der Startseite verknüpfen

Eine gelöste Verknüpfung zwischen einer im Shop Builder erstellten Seite und der Startseite kann wiederhergestellt werden.

[.instruction]
Verknüpfung erstellen:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Die Übersicht des Shop Builders wird geöffnet.
. Wählen Sie die Seite, die mit der Startseite verknüpft werden soll.
. Klicken Sie auf *Verknüpfung erstellen/lösen*. +
→ Die ausgewählte Seite wird mit der Startseite verknüpft.

Die blaue Markierung zeigt an, dass eine Verknüpfung vorhanden ist.


== Sprache wählen
Startseiten können mit verschiedenen Sprachen unabhängig voneinander angelegt werden.

[.instruction]
Sprache wählen:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Die Übersicht des Shop Builders wird geöffnet.
. Wählen Sie in der Dropdown-Liste eine Sprache aus.
. Klicken Sie auf *Seite hinzufügen*.
. Geben Sie einen Namen für die Seite ein.
. *Speichern* Sie die Einstellungen. +
→ Die Spracheinstellung wird für die Seite automatisch gespeichert.


== Mandantenvorschau anzeigen

Auf der Bearbeitungsseite ist es möglich, die erstellte Seite für die verschiedenen Mandanten anzusehen (Vorschau).

[.instruction]
Mandantenvorscheu anzeigen:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Die Übersicht des Shop Builders wird geöffnet.
. Wählen Sie eine Seite. +
→ Die gewählte Seite wird geöffnet.
. Wählen Sie in der Dropdown-Liste *Mandant für Vorschau* den gewünschten Mandanten. +
→ Die erstellte Seite wird für den gewählten Mandanten angezeigt.

== Neue Kategorien im Shop Builder erstellen

In der Übersicht des Shop Builders werden links die Kategorien des Shops angezeigt. Dort können neue Kategorien als Ober- oder Unterkategorien angelegt werden. +
Die globalen Elemente werden in der Übersicht im oberen Abschnitt angezeigt und die Seiten der aktuell ausgewählten Kategorie sind im unteren Abschnitt aufgeführt.

[.instruction]
Neue Kategorien im Shop Builder erstellen:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Die Übersicht des Shop Builders wird geöffnet.
. Klicken Sie links im Kategoriebaum auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Geben Sie einen Namen ein und wählen Sie *Hauptseite* für eine Hauptkategorie oder *Unterseite* für eine Unterkategorie.
. Wenn Sie eine Unterseite erstellen möchten, klicken Sie im Bearbeitungsfenster auf die Kategorie, in der die Unterkategorie angelegt werden soll.
. Klicken Sie auf *Erstellen*. +
→ Die neue Kategorie wurde dem Kategoriebaum hinzugefügt.


== Einen Header oder Footer im Shop Builder erstellen

Im Shop Builder können ein Header und ein Footer erstellt werden. Header und Footer sind global für den gesamten Webshop wirksam.

[.instruction]
Einen Header oder Footer im Shop Builder erstellen:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Die Übersicht des Shop Builders wird geöffnet.
. Klicken Sie in der Spalte *Globale Elemente* auf *Neu*. +
→ Das Fenster *Neue Seite erstellen* wird geöffnet.
. Wählen Sie *Header anlegen* oder *Footer anlegen*.
. Geben Sie einen Namen ein.
. Wählen Sie entweder die Standard-Footer bzw. Standard-Header oder treffen Sie keine Auswahl.
. *Speichern* Sie die Einstellungen. +
→ Der Header oder der Footer wurde angelegt.
. Klicken Sie auf *Verlinkung aktivieren/deaktivieren*, um den Header oder den Footer zu verknüpfen.


== Den Header global bearbeiten

Die im Header vorgenommenen Einstellungen sind global wirksam. Für den Header stehen die Widgets *Top Bar*, *Kategorie-Navigation* und *Breadcrumbs* zur Auswahl.

[.instruction]
Den Header global bearbeiten:

. Öffnen Sie das Menü *CMS » Shop Builder*. +
→ Die Übersicht des Shop Builders wird geöffnet.
. Klicken Sie auf den Header. +
→ Die für den Header angelegte Seite wird geöffnet.
. Ziehen Sie das gewünschte Widget per Drag&Drop in die Mitte.
. Klicken Sie auf *Bearbeiten*. +
→ Das entsprechende Bearbeitungsfenster wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-elemente-shop-builder>>. +
→ Die Einstellungen werden automatisch gespeichert.


== Den Footer global bearbeiten

Die im Footer vorgenommenen Einstellungen sind global wirksam. Für den Footer steht zusätzlich das Widget *Rechtliche Informationen* zur Auswahl.

[.instruction]
Den Footer global bearbeiten:

. Öffnen sie das Menü *CMS » Shop Builder*. +
→ Die Übersicht des Shop Builders wird geöffnet.
. Klicken Sie auf den Footer. +
→ Die für den Footer angelegte Seite wird geöffnet.
. Ziehen Sie das gewünschte Widget per Drag&Drop in die Mitte.
. Klicken Sie auf *Bearbeiten*. +
→ Das entsprechende Bearbeitungsfenster wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-elemente-shop-builder>>. +
→ Die Einstellungen werden automatisch gespeichert.
