= Standard
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, Standard
:position: 40

**plentymarkets » Einstellungen » Mandant (Shop) » Standard**

== Inhalt dieses Kapitels

In diesem Kapitel finden Sie die verschiedenen Grundeinstellungen zur Konfiguration Ihres **<<omni-channel/online-shop/standard/webshop#, Webshops  >>**. Neben der Konfiguration des **<<crm/e-mails-versenden#700, E-Mail-Dienstes >>** können Sie hier verschiedene Einstellungen zu Ihrem Standard-Webshop hinterlegen. Von besonderer Bedeutung sind in diesem Kapitel die Einstellungen zur **<<omni-channel/online-shop/cms-syntax/fallbeispiele/seo-guide#, Suchmaschinenoptimierung  >>**, mit denen Sie Ihren Webshop im Internet optimal auffindbar machen. Darüber hinaus werden in diesem Kapitel Grundeinstellungen zur Verwendung von **<<artikel/kategorien#, Kategorien  >>** sowie zum **<<omni-channel/online-shop/standard/mein-konto#, Mein Konto  >>**-Bereich und zum **<<omni-channel/online-shop/standard/bestellvorgang#, Bestellvorgang  >>** erläutert. Auch Informationen zu den Grundeinstellungen Ihrer <<omni-channel/online-shop/standard/artikelansichten#, **Artikelansichten**  >> entnehmen Sie diesem Kapitel.

[TIP]
.Tipp
====
Jeder weitere Webshop bzw. Mandant (Shop) wird in einer eigenen Menüstruktur analog zu diesem Menü konfiguriert. Die Menübezeichnung wird entsprechend der Bezeichnung des Webshops automatisch vom System vorgenommen.
====

== Verbindungen zu anderen Menüs

Für die Arbeit mit dem **<<crm/ticketsystem-nutzen#, Ticketsystem  >>** bzw. für das Versenden eines **<<crm/newsletter-versenden#, Newsletters  >>** müssen Sie Ihre Konfigurationen im Bereich **<<crm/e-mails-versenden#, E-Mail  >>** hinterlegt haben. Darüber hinaus legen Sie mit den Einstellungen im Bereich Artikelansichten den Grundstein für die Verwaltung Ihrer **<<artikel#, Artikel  >>**.

== Video-Tutorials

Erfahren Sie mehr über das Menü **E-Mail** im folgenden Videotutorial:

[.linkBox]
link:https://www.plentymarkets.eu//www.plentymarkets.eu/a-2842/[E-Mail-Konfiguration, window="_blank"]

Erfahren Sie mehr zum Menü **Buchhaltung** in plentymarkets im folgenden Video-Tutorial:

[.linkBox]
link:https://www.plentymarkets.eu/a-3345/[Buchhaltung, window="_blank"]

Wichtige Seiten zum Thema direkt aufrufen

* <<omni-channel/online-shop/standard/grundeinstellungen#, **Grundeinstellungen**  >>
* **<<omni-channel/online-shop/standard/webshop/multilingualismus#, Multilingualismus  >>**
* **<<omni-channel/online-shop/standard/webshop/rechtliche-angaben#, Rechtliche Angaben  >>**
* <<crm/e-mails-versenden#100, **Zugangsdaten** >>
* **<<crm/e-mails-versenden#1200, E-Mail-Vorlagen >>**
* <<omni-channel/online-shop/standard/artikelansichten#, **Artikelansichten**  >>
* **<<omni-channel/online-shop/cms-syntax/fallbeispiele/seo-guide#40, URL-Aufbau >>**
* **<<omni-channel/online-shop/cms-syntax/fallbeispiele/seo-guide#120, sitemap-XML >>**
* <<artikel/kategorien#, **Kategorien**  >>
* <<omni-channel/online-shop/standard/mein-konto#, **Mein Konto**  >>
* <<omni-channel/online-shop/standard/bestellvorgang#, **Bestellvorgang**  >>
* <<omni-channel/online-shop/standard/externe-dienste#, **Externe Dienste**  >>
* **<<omni-channel/online-shop/standard/externe-dienste/trusted-shops#, Trusted Shops  >>**
* **<<omni-channel/online-shop/standard/module#, Module  >>**

