= Prozesse ausführen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Prozesse ausführen, Client
:position: 20

Über das Menü **plentymarkets Client » Prozesse** führen Sie die Prozesse aus, die im Menü <<basics/automatisierung/prozesse/prozesse-einrichten#, System » Prozesse>> erstellt wurden.

== Prozess ausführen

Gehen Sie wie unten beschrieben vor, um einen Prozess auszuführen. Beachten Sie, dass nur die Prozesse angezeigt werden, die Ihnen als Benutzer bzw. Ihrer Rolle <<basics/automatisierung/prozesse/prozesse-einrichten#10, zugeordnet>> wurden. Das Menü **Prozesse** ist für Benutzer der Klasse **Variabel** nur sichtbar, wenn ihnen im Menü <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#, System » Einstellungen » Benutzer » Konten » Benutzer öffnen » Tab: Berechtigung » Tab: Menü>> die Berechtigung **Prozesse** erteilt wurde.

[.instruction]
Prozess ausführen:

. Öffnen Sie den plentymarkets Client.
. Öffnen Sie das Menü **Prozesse**. +
→ Die verfügbaren Prozesse werden angezeigt.
. Klicken Sie auf einen Prozess. +
→ Der Prozess wird angezeigt und befindet sich im Status **Wartend**.
. Klicken Sie auf **Start**. +
→ Der Prozess wird gestartet. +
→ Die Balken im Tab **Arbeitsschritte** zeigen den Fortschritt der einzelnen Prozessschritte an. +
→ Abhängig vom gewählten Prozess ist während der Ausführung ein Eingreifen des Benutzers erforderlich.

[IMPORTANT]
.Direktes Anzeigen von PDFs unter Windows nicht möglich.
====
PDF-Dateien können unter Windows nicht direkt im Client angezeigt werden.
====
