= Prozesse ausführen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Prozesse ausführen, plentyBase
:position: 20

[WARNING]
.plentyBase installieren
====
Sie benötigen das Tool plentyBase, um Prozesse im plentymarkets Backend zu erstellen und auszuführen. Die Installationsdateien für plentyBase finden Sie im link:https://marketplace.plentymarkets.com/plugins/externe-tools/plentyBase_5053/[plentyMarketplace^].
====

Über das Menü **Prozesse** führen Sie die Prozesse aus, die im Menü <<basics/automatisierung/prozesse/prozesse-einrichten#, System » Prozesse>> erstellt wurden.

== Prozess ausführen

Gehen Sie wie unten beschrieben vor, um einen Prozess auszuführen. Beachten Sie, dass nur die Prozesse angezeigt werden, die Ihnen als Benutzer bzw. Ihrer Rolle <<basics/automatisierung/prozesse/prozesse-einrichten#10, zugeordnet>> wurden. Das Menü **Prozesse** ist für Benutzer der Klasse **Variabel** nur sichtbar, wenn ihnen im Menü <<basics/arbeiten-mit-plentymarkets/benutzer-verwalten#, System » Einstellungen » Benutzer » Konten » Benutzer öffnen » Tab: Berechtigung » Tab: Menü>> die Berechtigung **Prozesse** erteilt wurde.

[.instruction]
Prozess ausführen:

. Öffnen Sie das Menü **Prozesse**. +
→ Die verfügbaren Prozesse werden angezeigt.
. Klicken Sie auf einen Prozess. +
→ Der Prozess wird angezeigt und befindet sich im Status **Wartend**.
. Klicken Sie auf **Start**. +
→ Der Prozess wird gestartet. +
→ Die Balken im Tab **Arbeitsschritte** zeigen den Fortschritt der einzelnen Prozessschritte an. +
→ Abhängig vom gewählten Prozess ist während der Ausführung ein Eingreifen des Benutzers erforderlich.
