= Subaktionen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Subaktionen, Prozesse, Client, Prozess, Subaktion, Automatisierung
:description: Übersicht der Subaktionen, die Sie für den plentymarkets Client konfigurieren können.
:position: 40

Auf dieser Handbuchseite finden Sie Erläuterungen zu den Subaktionen, die Sie im Menü **Einstellungen » Prozesse** zu den Aktionen Ihrer Prozesse hinzufügen können.

Die Subaktionen sind in alphabetischer Reihenfolge aufgelistet. Der Aufbau der Informationen pro Subaktion folgt diesem Muster:

* Kurze Erläuterung der Subaktion
* Aktionen, für die die Subaktion verfügbar ist
* Einstellungen, die zusätzlich zu den <<basics/automatisierung/prozesse/subaktionen#100, **allgemeinen Einstellungen** >> für diese Subaktion verfügbar sind

Die Informationen auf dieser Seite dienen als Nachschlagewerk für Benutzer, die mit den Grundprinzipien von plentymarkets Prozessen vertraut sind. Grundlegende Informationen zu Prozessen finden Sie auf der Handbuchseite <<basics/automatisierung/prozesse/prozesse-einrichten#, **Prozesse einrichten**  >>.

[#110]
== Allgemeine Einstellungen

Bestimmte Einstellungen sind für alle Subaktionen verfügbar. Die folgende Tabelle erläutert diese Einstellungen.

.Allgemeine Einstellungen für Subaktionen
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Position**
|Zeigt die aktuelle Position der Subaktion innerhalb der Aktion an. Die Subaktion mit der niedrigsten Positionsnummer wird als erstes ausgeführt. Andere Position aus der Dropdown-Liste wählen, um die Abfolge der Subaktionen in der Aktion zu ändern.
|====

[#120]
== Artikel scannen

Die Subaktion **Artikel scannen** öffnet eine Eingabemaske zum Scannen von Artikeln mit einem Barcode-Scanner.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#160, **Artikelsuche** >>

[.subhead]
Einstellungen
Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

[#130]
== Auftragsnotizen hinzufügen

Mit der Subaktion **Auftragsnotizen hinzufügen** fügen Sie einem Auftrag eine Notiz hinzu.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#170, **Auftrag** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Auftragsnotizen hinzufügen**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Notiz
|Wählen, welche Art von Notizen zum Auftrag hinzugefügt werden soll. +
**Individuelle Eingabe** = Ermöglicht die Eingabe einer Nachricht durch den Benutzer im Prozessablauf. Die Notiz wird am Auftrag hinterlegt. +
**Vordefinierte Eingabe** = Öffnet ein Fenster, in dem im Bereich **Nachricht** eine Nachricht hinterlegt werden kann, die im Prozessablauf bei Aufträgen automatisch als Notiz hinterlegt wird. +
**Keine** = (Nur bei Aktion im Fehlerfall) Legt keine individuelle oder vorgefertigte Notiz am Auftrag an. Empfohlen, wenn nur die Fehlermeldung als Auftragsnotiz hinterlegt werden soll.

|Fehlermeldung als zusätzliche Notiz hinterlegen
|(Nur bei Aktion im Fehlerfall) Häkchen setzen, um die im Prozess ausgegebene Fehlermeldung als Notiz am Auftrag zu hinterlegen.
|====

[#140]
== Aus Prozess entfernen

Mit der Subaktion **Aus Prozess entfernen** entfernen Sie Aufträge aus dem Prozess. Der Auftrag wird auch aus Filtern oder angefangenen Boxkommissionierungen entfernt.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#170, **Auftrag** >>

[.subhead]
Einstellungen
Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

[#150]
== Bestellung scannen

Die Subaktion **Bestellung scannen** öffnet eine Maske, über die Bestellungen per Barcode-Scanner eingelesen werden.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#200, **Bestellsuche** >>

[.subhead]
Einstellungen
Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

[#160]
== Buchung durchführen

Mit der Subaktion **Buchung durchführen** wird automatisch der Wareneingang oder Warenausgang gebucht.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#440, **Warenausgang** >>
* <<basics/automatisierung/prozesse/aktionen#450, **Wareneingang (Bestellung)** >>

[.subhead]
Einstellungen
Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

[#170]
== Buchung zurücksetzen

Mit der Subaktion **Buchung zurücksetzen** wird der gebuchte Warenausgang für die gewählten Aufträge zurückgesetzt.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#440, **Warenausgang** >>

[.subhead]
Einstellungen
Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

[#180]
== Drucken

Für den Druck von Dokumenten, z.B. Lieferscheinen oder Rechnungen, wählen Sie beim Hinzufügen dieser Subaktion den gewünschten Drucker aus.

Erfahren Sie mehr über die Verwendung der Subaktion **Drucken** im folgenden Videotutorial:

video::85295366[vimeo]
Zur Verwendung der Subaktion **Drucken** müssen Drucker eingerichtet sein. Erfahren Sie mehr über die das Einrichten von Druckern im folgenden Videotutorial:

video::85295366[vimeo]
[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#110, **Abhol-/Lieferschein** >>
* <<basics/automatisierung/prozesse/aktionen#120, **Adressetikett** >>
* <<basics/automatisierung/prozesse/aktionen#130, **Angebot** >>
* <<basics/automatisierung/prozesse/aktionen#150, **Artikeletikett** >>
* <<basics/automatisierung/prozesse/aktionen#180, **Auftragsbestätigung** >>
* <<basics/automatisierung/prozesse/aktionen#210, **Dokumente** >>
* <<basics/automatisierung/prozesse/aktionen#240, **Gelangensbestätigung** >>
* <<basics/automatisierung/prozesse/aktionen#250, **Gutschrift** >>
* <<basics/automatisierung/prozesse/aktionen#270, **Korrekturbeleg** >>
* <<basics/automatisierung/prozesse/aktionen#280, **Lager-Pickliste** >>
* <<basics/automatisierung/prozesse/aktionen#290, **Lieferschein** >>
* <<basics/automatisierung/prozesse/aktionen#300, **Mahnung** >>
* <<basics/automatisierung/prozesse/aktionen#310, **Packliste** >>
* <<basics/automatisierung/prozesse/aktionen#320, **Pickliste** >>
* <<basics/automatisierung/prozesse/aktionen#350, **Rechnung** >>
* <<basics/automatisierung/prozesse/aktionen#360, **Reparaturschein** >>
* <<basics/automatisierung/prozesse/aktionen#380, **Retourenetikett** >>
* <<basics/automatisierung/prozesse/aktionen#390, **Rücksendeschein** >>
* <<basics/automatisierung/prozesse/aktionen#430, **Versand-Center** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Drucken**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Druckereinstellung
|Eines der im Menü **Einstellungen » Grundeinstellungen » Drucker** gespeicherten **<<basics/arbeiten-mit-plentymarkets/grundeinstellungen/drucker#, Druckerprofile  >>** wählen.

|Kopien
|Anzahl der Kopien pro Ausdruck eingeben.

|Als Sammeldokument
|Häkchen setzen, um alle Dokumente in einem einzigen Dokument zusammenzufassen und gleichzeitig zu drucken.
|====

[#190]
== Eigner ändern

Mit der Subaktion **Eigner ändern** führen Sie einen Eignerwechsel durch. Auswählbar sind die in Ihrem System hinterlegten Eigner.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#170, **Auftrag** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Eigner ändern**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Eigner
|Den Eigner aus der Dropdown-Liste wählen, der durch die Subaktion zugewiesen werden soll. Zur Auswahl stehen alle im System angelegten Eigner.
|====

[#200]
== Hinweis anzeigen

Die Subaktion **Hinweis** zeigt einen Hinweistext an, den Sie hinterlegen. Einstellbar ist auch die Zeit, nach der der Hinweis wieder ausgeblendet werden soll.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#260, **Hinweis** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Hinweis**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Titel**
|Aussagekräftigen Titel für den Hinweis eingeben, der angezeigt werden soll.

|**Automatisch schließen**
|Festlegen, ob der Hinweis automatisch geschlossen werden soll, nachdem er angezeigt wurde. +
**Nie** = Der Hinweis muss per Klick geschlossen werden. +
**Nach 1 - 5 Sekunden** = Der Hinweis wird danach automatisch geschlossen.

|**Nachricht**
|Text eingeben, der als Hinweis ausgegeben werden soll.
|====

[#210]
== Markierung ändern

Mit der Subaktion **Markierung ändern** führen Sie eine Änderung der Markierung aus. Auswählbar sind die in Ihrem System hinterlegten Markierungen.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#170, **Auftrag** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Markierung ändern**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Markierung
|Markierung aus der Dropdown-Liste wählen, die durch die Subaktion zugewiesen werden soll.
|====

[#230]
== Notizen zum Auftrag

Bei der Subaktion **Notizen zum Auftrag** werden während des Prozesses in Verbindung mit der Aktion <<basics/automatisierung/prozesse/aktionen#260, **Hinweis** >> die im Menü <<auftragsabwicklung/auftraege/auftraege-bearbeiten/auftrag-aendern#3, **Aufträge » Aufträge bearbeiten » Tab: Übersicht** >> hinterlegten Informationen angezeigt und können vom Bearbeiter berücksichtigt werden. +
Die Notizen können vom Kunden bei der Bestellung angegeben werden. Beispiel:

* Ihren kostenlosen Werbeartikel bitte nicht senden, habe dafür keine Verwendung!

Alternativ tragen Sie Notizen selbst ein. Beispiel:

* Kunde verzichtet generell auf Werbeartikel. Nicht beilegen!

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#260, **Hinweis** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Notizen zum Auftrag**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Sichtbarkeit
|Wählen, welche Notizen angezeigt werden sollen. +
**ALLE** = Alle Notizen werden angezeigt. +
**Nur Kundennotizen** = Nur Notizen werden angezeigt, die Kunden eingegeben haben. +
**Nur Mitarbeiternotizen** = Nur Notizen werden angezeigt, die Mitarbeiter eingegeben haben.
|====

[#240]
== Notizen zum Kunden

Bei der Subaktion **Notizen zum Kunden** werden während des Prozesses in Verbindung mit der Aktion <<basics/automatisierung/prozesse/aktionen#260, **Hinweis** >> die im Menü **Kunden » Kunden bearbeiten » Tab: Notizen** hinterlegten Informationen angezeigt und können vom Bearbeiter berücksichtigt werden. +
Beispiel:

* Kunde möchte keine Werbung erhalten.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#260, **Hinweis** >>

[.subhead]
Einstellungen
Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

[#245]
== Online speichern

Mit der Subaktion **Online speichern** speichern Sie eine Online-Pickliste, die in der plentymarkets App aufgerufen und abgearbeitet werden kann.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#320, **Pickliste** >>

[.subhead]
Einstellungen
Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

[#250]
== Paketnummer erfassen

Mit der Subaktion **Paketnummer erfassen** erfassen Sie eine Paketnummer.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#170, **Auftrag** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Paketnummer erfassen**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Paketnummern-Format
|Paketnummern-Format aus der Dropdown-Liste wählen.
|====

[#260]
== Seriennummern erfassen

Mit der Subaktion **Seriennummern erfassen** erfassen Sie im Prozessablauf <<artikel/artikel-verwalten#820, **Seriennummern** >> per Barcode-Scanner erfassen. Wählen Sie, ob Sie neue Seriennummern erlauben möchten und ob Seriennummern automatisch gespeichert werden sollen.

Erfahren Sie mehr über das Erfassen von Seriennummern in Prozessen im folgenden Videotutorial:

video::87624135[vimeo]
[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#420, **Seriennummern** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Seriennummern erfassen**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Neue Seriennummern
|**Erlauben** = Auch Seriennummern, die im Wareneingang noch nicht erfasst wurden, können im Warenausgang eingescannt werden. +
**Nicht erlauben** = Seriennummern müssen bereits beim Wareneingang und beim Warenausgang erneut gescannt werden.

|Automatisches Speichern
|**Ja** = Nach erfolgreicher Erfassung der Seriennummern aller Artikelpositionen eines Artikels wird gespeichert und der Prozess automatisch fortgesetzt. +
**Nein:** Nach erfolgreicher Erfassung der Seriennummern aller Artikelpositionen eines Artikels muss im Prozessablauf auf **Speichern** geklickt werden, bevor der Prozess fortgesetzt wird.
|====

[#270]
== Sounds

Mit der Subaktion **Sounds** geben Sie zur Bestätigung, dass eine Aktion ausgeführt wurde, ein akustisches Signal aus.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#110, **Abhol-/Lieferschein** >>
* <<basics/automatisierung/prozesse/aktionen#120, **Adressetikett** >>
* <<basics/automatisierung/prozesse/aktionen#130, **Angebot** >>
* <<basics/automatisierung/prozesse/aktionen#150, **Artikeletikett** >>
* <<basics/automatisierung/prozesse/aktionen#160, **Artikelsuche** >>
* <<basics/automatisierung/prozesse/aktionen#170, **Auftrag** >>
* <<basics/automatisierung/prozesse/aktionen#180, **Auftragsbestätigung** >>
* <<basics/automatisierung/prozesse/aktionen#210, **Dokumente** >>
* <<basics/automatisierung/prozesse/aktionen#220, **E-Mail** >>
* <<basics/automatisierung/prozesse/aktionen#240, **Gelangensbestätigung** >>
* <<basics/automatisierung/prozesse/aktionen#250, **Gutschrift** >>
* <<basics/automatisierung/prozesse/aktionen#260, **Hinweis** >>
* <<basics/automatisierung/prozesse/aktionen#270, **Korrekturbeleg** >>
* <<basics/automatisierung/prozesse/aktionen#280, **Lager-Pickliste** >>
* <<basics/automatisierung/prozesse/aktionen#290, **Lieferschein** >>
* <<basics/automatisierung/prozesse/aktionen#300, **Mahnung** >>
* <<basics/automatisierung/prozesse/aktionen#310, **Packliste** >>
* <<basics/automatisierung/prozesse/aktionen#320, **Pickliste** >>
* <<basics/automatisierung/prozesse/aktionen#340, **Polling** >>
* <<basics/automatisierung/prozesse/aktionen#350, **Rechnung** >>
* <<basics/automatisierung/prozesse/aktionen#360, **Reparaturschein** >>
* <<basics/automatisierung/prozesse/aktionen#380, **Retourenetikett** >>
* <<basics/automatisierung/prozesse/aktionen#390, **Rücksendeschein** >>
* <<basics/automatisierung/prozesse/aktionen#400, **SEPA Pain001** >>
* <<basics/automatisierung/prozesse/aktionen#410, **SEPA Pain008** >>
* <<basics/automatisierung/prozesse/aktionen#430, **Versand-Center** >>
* <<basics/automatisierung/prozesse/aktionen#440, **Warenausgang** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Sounds**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Sounds
|Akustisches Signal wählen, das ausgegeben werden soll, wenn eine Aktion ausgeführt wurde.
|====

[#280]
== Speichern

Die Dokumente werden in einem Ordner gespeichert, den Sie bei der Erstellung der Subaktion wählen. Wenn mehrere Benutzer den Prozess verwenden sollen, geben Sie einen für alle Benutzer verfügbaren Ordner an.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#110, **Abhol-/Lieferschein** >>
* <<basics/automatisierung/prozesse/aktionen#120, **Adressetikett** >>
* <<basics/automatisierung/prozesse/aktionen#130, **Angebot** >>
* <<basics/automatisierung/prozesse/aktionen#150, **Artikeletikett** >>
* <<basics/automatisierung/prozesse/aktionen#180, **Auftragsbestätigung** >>
* <<basics/automatisierung/prozesse/aktionen#210, **Dokumente** >>
* <<basics/automatisierung/prozesse/aktionen#220, **E-Mail** >>
* <<basics/automatisierung/prozesse/aktionen#230, **FiBu-Export** >>
* <<basics/automatisierung/prozesse/aktionen#240, **Gelangensbestätigung** >>
* <<basics/automatisierung/prozesse/aktionen#250, **Gutschrift** >>
* <<basics/automatisierung/prozesse/aktionen#270, **Korrekturbeleg** >>
* <<basics/automatisierung/prozesse/aktionen#280, **Lager-Pickliste** >>
* <<basics/automatisierung/prozesse/aktionen#290, **Lieferschein** >>
* <<basics/automatisierung/prozesse/aktionen#300, **Mahnung** >>
* <<basics/automatisierung/prozesse/aktionen#310, **Packliste** >>
* <<basics/automatisierung/prozesse/aktionen#320, **Pickliste** >>
* <<basics/automatisierung/prozesse/aktionen#340, **Polling** >>
* <<basics/automatisierung/prozesse/aktionen#350, **Rechnung** >>
* <<basics/automatisierung/prozesse/aktionen#360, **Reparaturschein** >>
* <<basics/automatisierung/prozesse/aktionen#380, **Retourenetikett** >>
* <<basics/automatisierung/prozesse/aktionen#390, **Rücksendeschein** >>
* <<basics/automatisierung/prozesse/aktionen#400, **SEPA Pain001** >>
* <<basics/automatisierung/prozesse/aktionen#410, **SEPA Pain008** >>
* <<basics/automatisierung/prozesse/aktionen#430, **Versand-Center** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Speichern**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Zielordner
|Auf den Stift klicken und den Pfad wählen, unter dem die Dokumente gespeichert werden sollen.

|Dateiname
|Wählen, unter welchem Namen die Dokumente gespeichert werden sollen. +
**Standard** = Dateien erhalten den Standardnamen. +
**Benutzerdefiniert** = Benutzerdefinierten Namen eingeben. Verfügbare Variable:$PlentyID. +
**Unterordner erstellen** = Die Dokumente werden in einem Unterordner angelegt. Dieser Unterordner wird nach dem Muster Zielordner/Typ_Datum_Uhrzeit/ erstellt.

|Als Sammeldokument
|Häkchen setzen, um alle Dokumente in einem Dokument zusammenzufassen und nur dieses Dokument zu speichern.
|====

[#290]
== Status ändern

Mit der Subaktion **Status ändern** führen Sie einen Statuswechsel durch. Auswählbar sind die in Ihrem System gespeicherten Status.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#170, **Auftrag** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Status ändern**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Status
|Status aus der Dropdown-Liste wählen, der durch die Subaktion zugewiesen werden soll.
|====

[#300]
== Versanddienstleister ändern

Mit der Subaktion **Versanddienstleister ändern** wechseln Sie den Versanddienstleister.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#170, **Auftrag** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Auftrag**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Versanddienstleister
|Einen Versanddienstleister aus dem Dropdown-Menü wählen, um diesen Versanddienstleister durch die Subaktion zuzuweisen. Zur Auswahl stehen alle im System angelegten Versanddienstleister.
|====

[#310]
== Versandpakete

Mit der Subaktion **Versandpakete** legen Sie Versandpakete an und bearbeiten diese Versandpakete.

Aktionen Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#170, **Auftrag** >>

[.subhead]
Einstellungen
Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

[#320]
== Versandprofil ändern

Mit der Subaktion **Versandprofil ändern** wechseln Sie ein Versandprofil.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#170, **Auftrag** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Versandprofil ändern**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|Versandprofil
|Ein Versandprofil aus der Dropdown-Liste wählen, um dieses Versandprofil durch die Subaktion zuzuweisen. Zur Auswahl stehen alle im System angelegten Versandprofile.

|Checkbox
|Häkchen setzen, um andere Versandkosten als die Versandkosten aus dem gewählten Versandprofil zu verwenden.

|Versandkosten
|Versandkosten eingeben. Wenn in der Checkbox ein Häkchen gesetzt ist, werden die eingetragenen Versandkosten verwendet.
|====

[#330]
== Versenden

Mit der Subaktion **Versenden** versenden Sie die E-Mail-Vorlage, die für die Aktion **<<basics/automatisierung/prozesse/aktionen#220, E-Mail >>** eingestellt wurde.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#220, **E-Mail** >>

[.subhead]
Einstellungen
Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

[#340]
== Zahlungsart ändern

Mit der Subaktion **Zahlungsart ändern** ändern Sie die Zahlungsart eines Auftrags.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#170, **Auftrag** >>

[.subhead]
Einstellungen
Die folgende Tabelle erläutert die zusätzlichen Einstellungen der Subaktion. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

.Subaktion **Drucken**
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Zahlungsart**
|Neue Zahlungsart aus der Dropdown-Liste wählen, die den Aufträgen zugewiesen werden soll.
|====

[#350]
== Zwischenspeichern

Wenn viele Dokumente gespeichert oder gedruckt werden sollen, kann der Prozess sehr lange dauern. Dadurch kommt es zu Wartezeiten im Prozessablauf. Um dies zu vermeiden, platzieren Sie die Subaktion **Zwischenspeichern** z.B. vor einer Aktion, die mehr Zeit beansprucht als der Speichervorgang. Das Zwischenspeichern läuft dann im Hintergrund ab, während die Aktion ausgeführt wird. Danach können Sie z.B. die Subaktion **Drucken** einbauen. Der Drucker greift dann auf die im Hintergrund geladenen und gespeicherten Dokumente zu und druckt diese Dokumente.

[.subhead]
Aktionen
Die Subaktion steht für folgende Aktionen zur Verfügung:

* <<basics/automatisierung/prozesse/aktionen#110, **Abhol-/Lieferschein** >>
* <<basics/automatisierung/prozesse/aktionen#120, **Adressetikett** >>
* <<basics/automatisierung/prozesse/aktionen#130, **Angebot** >>
* <<basics/automatisierung/prozesse/aktionen#150, **Artikeletikett** >>
* <<basics/automatisierung/prozesse/aktionen#180, **Auftragsbestätigung** >>
* <<basics/automatisierung/prozesse/aktionen#210, **Dokumente** >>
* <<basics/automatisierung/prozesse/aktionen#240, **Gelangensbestätigung** >>
* <<basics/automatisierung/prozesse/aktionen#250, **Gutschrift** >>
* <<basics/automatisierung/prozesse/aktionen#270, **Korrekturbeleg** >>
* <<basics/automatisierung/prozesse/aktionen#280, **Lager-Pickliste** >>
* <<basics/automatisierung/prozesse/aktionen#290, **Lieferschein** >>
* <<basics/automatisierung/prozesse/aktionen#300, **Mahnung** >>
* <<basics/automatisierung/prozesse/aktionen#310, **Packliste** >>
* <<basics/automatisierung/prozesse/aktionen#320, **Pickliste** >>
* <<basics/automatisierung/prozesse/aktionen#350, **Rechnung** >>
* <<basics/automatisierung/prozesse/aktionen#360, **Reparaturschein** >>
* <<basics/automatisierung/prozesse/aktionen#380, **Retourenetikett** >>
* <<basics/automatisierung/prozesse/aktionen#390, **Rücksendeschein** >>
* <<basics/automatisierung/prozesse/aktionen#430, **Versand-Center** >>

[.subhead]
Einstellungen
Für diese Subaktion sind keine zusätzlichen Einstellungen verfügbar. Informationen zu den allgemeinen Einstellungen für Subaktionen finden Sie in <<basics/automatisierung/prozesse/subaktionen#100, **Tabelle 1** >>.

