= Setting up Amazon in plentymarkets
:lang: en
include::{includedir}/_header.adoc[]
:description: Multi-Channel in plentymarkets: Set up the interface to the market Amazon in your plentymarkets system.
:position: 10

link:http://www.amazon.co.uk/[*Amazon*^] has gone from being the largest internet book store to one of the leading universal shopping centres. Various customers appreciate the large portfolio, rely on the high product quality and expect best service such as fast delivery. With plentymarkets, you have full access to Amazon. Learn how to make items available, activate the interface for data exchange, use the FBA service by Amazon and many more. The abbreviation FBA stands for Fulfilment by Amazon, a service from Amazon where Amazon takes care of the entire stock management and logistics.

[#100]
==  Registering with Amazon

Before carrying out the settings in plentymarkets, you will have to register as a seller on Amazon. Amazon Seller Central is the central Amazon interface for sellers. On the Amazon UK platform, sellers who sell more than 35 items per month are considered Pro sellers and only have the possibility to upload item lists from this amount on. plentymarkets users need to select the Pro option. It will only be possible to use automatic procedures and APIs to manage stock and offers with the Pro option. This option includes a monthly subscription fee as well as additional fees for each item sold. For further information, refer to the *link:https://services.amazon.co.uk/services/sell-online/pricing.html[Amazon website^]*.

Once you have registered, set up the *link:https://developer.amazonservices.co.uk/[MWS interface^]* on Amazon. MWS stands for Marketplace Web Service. This service supports API functions. As such, it needs to be set up in order to exchange data with plentymarkets. Select the MWS option that allows an application to access your Amazon account. You will need the following information for the interface:

*  Name of the application: plentymarkets
*  MWS account number for European markets: 6860-7675-7360
*  MWS account number for the US market: 5751-6263-3716

Once you have set up Amazon MWS, you will receive the merchant ID that you will need for setting up the interface in plentymarkets.

[#200]
==  Setting up Amazon in plentymarkets

Carry out the following settings in plentymarkets in order to set up the interface to Amazon.

[#300]
===  Setting up an account

Set up a new Amazon account in plentymarkets.

[.instruction]
Creating a new account:

.  Go to *System » Markets » Amazon » Settings*.
.  Click on *New account*.  +
→ The window *Create new Amazon Seller Central account* will open.
.  Select an *Amazon platform*.
.  Enter the *Email address* that you use for the platform.
.  Click on *Create new account*.  +
→ The account will be created.
.  Click on the previously created account in the overview on the left.
.  Carry out the settings as desired. Pay attention to the information given in tables 1 to 4.
. *Save* the settings.

[TIP]
.European Marketplaces Account
====
"Amazon has unified its European marketplaces, allowing you to create and manage product offers on any and all of our Amazon marketplaces in the UK, France, Germany, Spain and Italy. You control what you sell and where. You manage your business from a single seller account interface. When you sign up to sell on Amazon.co.uk, your seller account is automatically enabled to allow you to sell on Amazon.de, Amazon.fr, Amazon.es and Amazon.it. You will be asked to define your home marketplace which can be any of the 4 marketplaces. We recommend that you choose your home marketplace as the country from where you will be operating and fulfilling your orders." (Source: Amazon)  +
Refer to Amazon's link:http://services.amazon.co.uk/services/sell-online/international-selling.html[*information*^] and link:http://services.amazon.co.uk/faq-for-the-amazon-europe-marketplaces-account.html[*FAQ*^] about the European Marketplaces Account.
====

[.subhead]
Amazon platform

If you sell on multiple Amazon platforms with a European Marketplaces Account, then set up a new account for each platform in plentymarkets and configure each platform separately. The same access data is used for all platforms.

[#400]
===  Carrying out the initial settings

All entries in the *Access data* section of the *Settings* tab are mandatory entries. Enter the data and pay attention to the information given in table 1.

.settings for *Access data*
[cols="1,3"]
|====
| Setting | Explanation

|*Amazon platform*
| A platform has to be selected when the account is created. However, the platform can be changed here. If you have a European Marketplaces Account, then configure each platform separately.

|*Merchant ID*
| Enter the merchant ID that you received from Amazon. If you have a European Marketplaces Account, then the same merchant ID is used for every platform.

|*Merchant token*
| Enter the merchant token that you can find on Seller Central.

|*Email address*
| Enter the email address that is used as user name for the Seller Central account.

|*Active*
| Place a check mark to activate the interface.  +
Only place a check mark once all of the settings have been carried out. This prevents incorrect data from accidentally being transferred.

|*B2B*
| Place a check mark to activate this account for Amazon business.
|====

Carry out settings that relate to the SKU structure in the *Initial settings* section. The SKU (Stock Keeping Unit) is a unique reference number for all items and item variations on Amazon.

.settings in the *Initial settings* tab
[cols="1,3"]
|====
| Setting | Explanation

|*Client*
| Select which client should be used for orders from Amazon.

|*SKU structure*
| Select one of the following options:  +
*Variation ID* +
*EAN if available, otherwise variation ID* +
*Variation number if available, otherwise variation ID* +
The selected setting only goes into effect for items that are exported to Amazon for the first time. From now on, Amazon and your online store will exchange data based on these SKUs.  +
*Important*: Do not change this setting after items have been transferred to Amazon. If you do so, communication, e.g. stock updates, between plentymarkets and Amazon will no longer be possible.  +
Pay attention to the note below the table with the title *Assigning already existing SKU numbers*.

|*Catalogue was listed with SSW*
|*Yes* = Items will be listed on Amazon with *link:https://ssw.starsellersworld.com/[starsellersworld^]*. The item SKU will be cut off right behind the last "-" when importing the items. This makes it possible to match the item in the system.  +
*No* = Items will not be listed on Amazon with starsellersworld.

|*Generate invoice*
| Select whether the invoice should be generated by plentymarkets or by Amazon. +
*plentymarkets* = The invoice is generated by plentymarkets. +
*Amazon VCS* = The invoice is generated by Amazon.
|====

Learn more about setting up Amazon in the following video tutorial:

video::196421219[vimeo]

[TIP]
.SKU settings and stock synchronisation
====
If the same settings for SKU numbers are selected for all platforms, then you can synchronise all platforms for the European Marketplaces Account with the stock synchronisation. If the settings are not the same, then the synchronisation will have to be carried out separately for each platform.

Since the stock is managed globally for a European Marketplaces Account, it is sufficient to activate the stock for your home marketplace. Nevertheless, the SKU settings must match.
====

[IMPORTANT]
.Assigning already existing SKU numbers
====
If you are already selling your items on Amazon and now you want to start selling them with plentymarkets you will have to assign already existing SKUs in the menu *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings » Tab: Availability*.
====

[IMPORTANT]
.Authorising plentymarkets e-mail addresses
====
All plentymarkets e-mail addresses which are used to send messages to Amazon have to be authorised first within your Seller Central account on Amazon.
====

[#500]
===  Carrying out item settings

In the *Item settings* tab, you can carry out settings related to the item export. For example, you can configure automatic processes and export filters.

.settings in the *Item settings* tab
[cols="1,3"]
|====
| Setting | Explanation

2+| Automatic processes

|*Item export; +
Price changes; +
Stock synchronisation; +
Stock changes*
| Do not transfer the information or choose how often the information should be transferred.

2+| Export filter

|*Item availability; +
Export categories; +
BMVD export categories; +
Flag 1; +
Flag 2; +
Store items*
| Only items with the selected filters will be exported.  +
*Item availability* = If a parent (main item) has an availability that was not selected here, then it will not be transferred.  +
*Flag 1* and *Flag 2* = These filters only apply to the export that takes place at night.

2+| Export settings

|*Item name; +
Item description; +
Warehouse selection*
| The selected information will be exported.

|*Allowing HTML tags*
| The following tags are allowed: &lt; br &gt;, &lt; b &gt;, &lt; i &gt;, &lt; p &gt; ,&lt; ul &gt;, &lt; li &gt;, &lt; table &gt;, &lt; tr &gt;, &lt; td &gt;, &lt; th &gt;, &lt; tbody &gt; and &lt; strong &gt;.

|*Stock buffer*
| If an item is limited to net stock, the exported stock is reduced by the value entered.

|*Maximum stock*
| Defines the upper limit for exported stock for all items. This setting takes priority over the setting below *Quantity for items not limited to stock*.

|*Quantity for items not limited to stock*
| For items that have the setting *no limitation*, the maximum amount of the real stock and the quantity defined here will be transferred.  +
*Example:* setting 0, net stock 8. plentymarkets will transfer 8.  +
Items with the setting *Limited to net stock* will not be taken into consideration.

|*Average delivery period*
| Choose between the options *Do not transfer*, *Transmit "average delivery time in days"* and *Transmit "average delivery time in days" + additional delay in delivery*.

|*Handling time*
| Enter a number of days for the additional delay in delivery. This option is only displayed if the *Average delivery period* option is set to *Transmit "average delivery time in days" + handling time*.

|*Manufacturer part number*
| Select whether you want to transfer the SKU, variation number, GTIN, variation ID, model number or no value at all for the CSV file's field part_number.
|====

Learn more about the item settings in the following video tutorial:

video::196572384[vimeo]

[#600]
===  Carrying out order settings

In the *Order settings* tab, you can carry out settings related to shipping. The abbreviation MFN stands for merchant-fulfilled network. This means that the seller takes care of order processing.

.settings in the *Order settings* tab
[cols="1,3"]
|====
| Setting | Explanation

2+| Ship own orders (MFN)

|*Order import*
| Do not transfer the information or choose how often the information should be imported.

|*Shipping confirmation*
| Do not export the shipping confirmation to Amazon or choose how often the shipping confirmation should be exported.

|*Order item*
| Defines how item name is displayed in the order item. Select one of the following options:  +
*Copy item name from store* +
*Copy item name from Amazon - with SKU* +
*Copy item name from Amazon - without SKU*

|*Incoming payment*
| Select *Incoming payment booked* if the incoming payment should be displayed as booked when the order is imported.

|*Status for transmitted returns*
| Select the <<order-processing/orders/managing-sales-orders#order-status, *order status*>> for returns that were successfully reported to Amazon.

|*Status for untransmitted returns*
| Select the <<order-processing/orders/managing-sales-orders#order-status, *order status*>> for returns that were not reported to Amazon.

|*Outstanding orders*
| Decide whether pending orders should be imported every 15 minutes or never.

|*Credit note import*
|Select whether credit notes should be imported into your plentymarkets system. +
This function must be unlocked by plentymarkets. To do so, contact a plentymarkets supporter. +
*Yes* = Credit notes are imported into your plentymarkets system once a day. If you select *Yes*, the event procedure for automatically creating <<Editing returns of Amazon orders, credit notes>> which are sent to Amazon as returns has to be deactivated. +
*No* = Credit notes are not imported.
The credit note import is deactivated by default.

2+| Shipment by Amazon (FBA)

|*Referrer*
| Select whether only orders from Amazon should be processed with FBA or whether orders from other <<omni-channel/order-referrer#, *referrers*>> should be processed with FBA as well.

|*Order import*;  +
*Returns import*;  +
*Stock import*
| Do not transfer the information or choose how often the information should be imported.

|*Status*
| Select the <<order-processing/orders/managing-sales-orders#order-status, *order status*>> for orders that were imported from Amazon.

|*Warehouse*
| Select which <<omni-channel/multi-channel/amazon#10, *warehouse*>> should be used for Amazon shipments.

|*Outgoing items*
| Select whether outgoing items should be marked as booked or not. The option *Mark as booked* does not trigger an item movement. In order to trigger an item movement, select the option *Do not mark as booked* and set up an event procedure.

|*Status for transmitted orders*
| Select the <<order-processing/orders/managing-sales-orders#order-status, *order status*>> for orders that were successfully transferred to FBA.

|*Include coupons to returns*
| Select whether coupons used for the FBA order should be considered in the return.

|*Shipping category*
| Select *Standard* = Normal shipping *Expedited* = Express shipping or *Priority* = Fastest shipping service.
|====

Learn more about the order settings in the following video tutorial:

video::196572461[vimeo]

[#650]
=== Retrieve order reports

The tab *Process status* contains information about order reports for your MFN orders. Use the button *Call schedule* to display the time interval in which Amazon generates order reports and the exact time of the next call.

[#660]
== Activating the order referrer

In order to link items, properties etc. with Amazon platforms you will have to activate the order referrer for these Amazon platforms in the menu *System » Orders » Order referrer*.

[.instruction]
Activating the order referrer bol.com:

. Go to *System » Orders » Order referrer*.
. Place a check mark next for the desired Amazon platforms*.
. *Save* the settings.

[#700]
==  Setting the item availability

Items have to be available for Amazon. This is done in the *Availability* tab of an item within the <<item/managing-items#170, *Item » Edit item » Tab: Variation ID*>> menu.

[.instruction]
Setting the item availability for an amazon country platform:

.  Open the *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings* menu.
.  Activate the main variation in the *Availability* section.
.  Click on the *Availability* tab.
.  Click in the *Markets* section in the selection field.  +
→ A list with all available markets will be displayed.
. Select *Web API*.
. Click on *Add*.
.  Select in the same list the Amazon country platform(s) for which the item should be available for.
.  Click on *Add*.  +
→ The Market will be added.
. *Save* the settings.
.  Open the *Multi-Channel* tab.
.  Carry out the settings in the *Amazon* area. Pay attention to the information given in table 5.
. *Save* the settings.

The availability for variations can be individually edit in the *Item » Edit item » Open item » Tab: Variation ID » Open Variante »Tab: Availability* menu.

.Setting the item availability for Amazon
[cols="1,3"]
|====
| Setting | Explanation

|*Amazon product type*
| Select the <<basics/data-exchange/data-formats/item#50, *Amazon product type*>>.

|*Fulfilment by Amazon (FBA)*
| Select one of the Amazon marketplaces *AMAZON_EU* (Europe), *AMAZON_FE* (Far East), *AMAZON_NA* (North America).

|*Shipment by Amazon (FBA)*
| Activate if the FBA function should be used and FBA stock and Multi-Channel stock should be imported.
|====

[IMPORTANT]
.Item availability for Ship own orders (MFN) and FBA
====
In order to set up items for Ship own orders (MFN) as well as FBA select the Amazon country platform *Amazon country* and the platform *Amazon country FBA*.
====

Learn more about item settings for Amazon in the following video tutorial:

video::169838156[vimeo]

[#750]
==  Defining SKU manually

Add SKUs manually for specific referrers in the menu <<item/managing-items#170, *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings » Tab: Availability*>> if needed.

[.instruction]
Addding SKU

. Open the *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings* menu.
.  Click on the *Availability* tab.
.  Click in the *SKU* section on *Add*.  +
→ The editing window *New SKU* will be displayed.
.  Select the referrer *Amazon* to add the SKU.
.  Select the corresponding market account.
.  Enter the SKU.
.  Click on *Add*.  +
→ The SKU will be saved and displayed.

[#760]
==  Defining Amazon order import SKU manually

Add order import SKUs manually for Amazon in the menu <<item/managing-items#170, *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings » Tab: Availability*>>. The order import SKU is only used for the order import from Amazon.

[.instruction]
Addding SKU

. Open the *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings* menu.
.  Click on the *Availability* tab.
.  Click in the *Amazon order import SKU* section on *Add*.  +
→ The editing window *New order import SKU* will be displayed.
.  Select the referrer *Amazon* to add the SKU.
.  Select the corresponding market account.
.  Enter the SKU.
.  Click on *Add*.  +
→ The SKU will be saved and displayed.

SKUs can be changed afterwards.

[#800]
==  Defining a sales price

Proceed as described below to define a sales price for Amazon country platforms. This price will be displayed on the country platforms.

[.instruction]
Defining the sales price for country platforms:

.  Open the menu *System » Item » Sales prices » Open sales price » Tab: Settings*.
.  Place a checkmark next to the desired Amazon country platform.
.  Place a check mark next to the desired Amazon account.
. *Save* the settings.

[#850]
==  Defining special offers

In order to transfer special offers to Amazon they have to be saved as sales prices and linked to an item. In addition, the properties *SaleStartDay* and *SaleEndDate* have to be created and linked to the item. Proceed as described below to define special offers for Amazon items.

[.instruction]
Defining a special offer for an Amazon platform:

.  Open the menu *System » Item » Sales prices » Open sales price » Tab: Settings*.
.  Place a check mark next to the option *Special offer* in the line *Price type*.
.  Place a check mark next to the desired Amazon country platform.
.  Place a check mark next to the desired Amazon account.
. *Save* the settings.

Next, you will have to link the special offer to the item in the *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings* menu.

Next, create the properties *SaleStartDay* and *SaleEndDate* and link them with the Amazon product type. Proceed as described below to create and link the property *SaleStartDay*. Edit the property *SaleEndDate* the same way but enter the name *SaleEndDate* and link the Amazon field *sale_end_date* instead.

[.instruction]
Creating a property for special offers and linking it with the Amazon product type:

.  Go to <<omni-channel/multi-channel/amazon#2, *System » Item » Properties » Tab: New property*>>.
.  Enter *SaleStartDate* for *Name (internal)*.  +
→ Make sure to enter this exact name. Otherwise, the special offer won't be transfrred to Amazon.
. Select the option *Text* from the *Property type* drop-down menu.
.  Select the product type from the drop-down menu next to *Amazon link*.  +
→ A new drop-down menu will appear.
.  Select the Amazon option *sales_from_date* from the drop-down menu.
.  Click on *Add*.  +
→ The link will be created.

Now link the properties to the item in the *Item » Edit item » Open item » Tab: Variation ID » Tab: Properties* menu. Enter the date in the following format: *YYYY-MM-DD*.

Learn more about special offers for Amazon in the following video tutorial:

video::173464103[vimeo]

[#900]
==  Setting up freely definable fields in the Amazon export (Seller Central)

The freely definable fields are used to customise the data that you export to Amazon. These fields have to be linked to *<<item/managing-items#70, free text fields>>*. The free text fields allow you to individually customise the item data and therefore save an exact description of the item.

[#1000]
===  Creating free text fields

First, create the <<item/managing-items#70, *free text fields*>> that you want to link to freely definable fields on Amazon. To do so, proceed as follows.

[.instruction]
Creating free text fields:

.  Go to *System » Item » Free text fields*.
.  Enter a name under *Field name*.
.  Select the *Data type* from the drop-down menu.
.  Enter the maximum number of *Characters* for the free text field.
. *Save* the settings.  +
→ The free text fields will be available the next day in the editing window of the items in the *Fields* tab. Enter the actual text there.

[#1100]
===  Linking free text fields

Once you have configured the free text fields, you will need to link them with Amazon Seller Central export fields. To do so, proceed as follows.

[.instruction]
Linking free text fields with Amazon export fields:

.  Go to *System » Markets » Amazon » Freely definable fields*.
.  Open the submenu *Freely definable fields in the Amazon export (Seller Central)*.
.  Expand the category.
.  Select an *Export field* from the drop-down menu.
.  Select the appropriate field from the *Free text field* drop-down menu.  +
→ You can only select those fields that were previously created.
. *Save* the settings.

[#1200]
==  Setting up freely definable fields in the Amazon export (Marketplace)

Link freely definable fields in the Amazon export (Marketplace) for the BMVD categories Books, Music, Video and DVD.

[.instruction]
Linking free text fields:

.  Go to *System » Markets » Amazon » Freely definable fields*.
.  Open the submenu *Freely definable fields in the Amazon export (Marketplace)*.
.  Select the free text fields from the drop-down menus.
. *Save* the settings.
.  Go to *System » Item » Free text fields*.
.  Enter a name under *Field name* for the free text fields that you have just selected.
.  Select a type from the drop-down menu in the *Data type* column.
.  Enter the maximum number of *Characters* for the free text field.
. *Save* the settings.  +
→ The free text fields will be available the next day in the editing window of the items in the *<<item/managing-items#70, Fields>>* tab. Then, enter the *number*. Pay attention to tables 6 and 7.

[TIP]
.Limitations for free text fields
====
Only certain values can be used for the fields *item-condition* and *will-ship-internationally*. The field *item-note* can be used as a text field and formulated differently for every item.
====

[IMPORTANT]
.Entering the Amazon product type and item data
====
Open an item under *Item » Edit item* and click on its *Multi-Channel* tab. The *Amazon product type* must be selected in order for the export to work correctly: *Marketplace - Books*, *Marketplace - Music*, *Marketplace - Video*, *Marketplace - DVD*. Furthermore, the *EAN*, *UPC* or *ISBN* must be entered in the item data.
====

The following values are possible for the *item-condition* field:

.options in the *item-condition* field
[cols="1,3"]
|====
| Number | Meaning

|*1*
| Used, Like New

|*2*
| Used, Very Good

|*3*
| Used, Good

|*4*
| Used, Acceptable

|*5*
| Collectible, Like New

|*6*
| Collectible, Very Good

|*7*
| Collectible, Good

|*8*
| Collectible, Acceptable

|*9*
| Not used

|*10*
| Refurbished (for computers, kitchen &amp; housewares, electronics, and camera &amp; photo only)

|*11*
| New
|====

The following values are possible for the *will-ship-internationally* field:

.options in the *will-ship-internationally* field
[cols="1,3"]
|====
| Number | Meaning

|*7*
| Shipping within Germany

|*8*
| Shipping within Europe (including non EU countries)

|*9*
| Shipping within the EU, Switzerland and Lichtenstein

|*10*
| Shipping worldwide
|====

[#1300]
==  Linking categories

You will have to save some information in your plentymarkets categories in order for your items to automatically be assigned to the existing categories when exporting them to Amazon. The so called Browse Tree Guides (BTG) from Amazon provide you with classification information. This information is provided in table format (MS Excel) and contains unique classification numbers, the so called Browse Node IDs, which you will have to assign to your online store categories. The lists are available in the help centre of Seller Central or via this *link:https://sellercentral-europe.amazon.com/gp/help/help-folder.html/?ie=UTF8&itemID=1661[link^]*.

Using the official Browse Tree Guides for the Amazon platform that you want to sell your products on ensures that your items can be found quickly and easily in the Amazon catalogue. The Browse Node IDs form the basis for the item/product assignment in the navigation as well as in the product search. Due to the large amount of items offered on Amazon, an explicit assignment of your items into these Browse Node IDs determines whether a customer will find your product in the corresponding category or not. Therefore, we recommend that you take some time when carrying out this next step and that you select the Browse Node IDs carefully.

Go to *System » Markets » Amazon » Category link* to link categories. In plentymarkets, you can link each item category with up to two Amazon classification numbers from the Browse Tree Guides.

It is absolutely necessary that you link the entered values separately line by line.

The category links will only be taken into consideration for the default categories, which were selected for an item under <<item/managing-items#300, *Item » Edit item » Tab: Categories*>>.

[.instruction]
Linking Amazon categories:

.  Use this *link:https://sellercentral-europe.amazon.com/gp/help/help-folder.html/?ie=UTF8&itemID=1661[link^]* to access the help centre within Seller Central.
.  Select the desired classification list, e.g. apparel.
.  Look up the desired category name in the *node path* column (e.g. blouse).
.  Go to *System » Markets » Amazon » Category link* in your plentymarkets back end.
.  Enter the corresponding Browse Node ID from the list into the table.
.  Click on the *gear-wheel icon* that corresponds to the category that you want to link.

[IMPORTANT]
.Exporting the Browse Node ID
====
The Browse Node ID that was assigned when selecting the category will be inserted into the field *RecommendedBrowseNode1* during the data export. The field *RecommendedBrowseNode2* is only used for categories that are linked multiple times.
====

Learn more about linking categories for Amazon in the following video tutorial:

video::199997850[vimeo]

[#1350]
== Linking attributes and attribute values

<<item/managing-items#390, *Attributes*>> also have to be linked before your items can be transferred to Amazon.

[.instruction]
Linking attributes and attribute values:

. Go to *System » Item » Attributes*.  +
→ The overview of all attributes used in your catalogue will open.
. Expand an attribute.
. Click on the *Attribute link* tab.
. Click on *Amazon*.  +
→ The section Amazon for the attribute link will be displayed.
. Select the coressponding Amazon category from the dropdown menu.
. Enter the Amazon attribute values that most closely match your own attribute values. This is done in the Market variation area.
. *Save* the settings.
. Repeat this process for all remaining attributes.

Next, activate the attributes within the item settings.

[IMPORTANT]
.Deactivate main variation without an attribute link
====
If an item's variations have attribute links but the main variation has none then the main variation has to be set to inactive. Otherwise the main variation will be exported as a single item. The main variation must be activated if it has an attribute link.
====

[#1400]
==  Linking properties with the Amazon product type

In case you ever need to define the parameters or characteristics of items for the market Amazon, which cannot directly be set up with plentymarkets, we have developed the solution that is described here: Parameters or values are integrated by means of the properties.

The link between an item's property and the Amazon product type is made in the <<item/managing-items#480, *System » Item » Properties*>> menu.

[.instruction]
Linking properties with the Amazon product type:

.  Go to *System » Item » Properties*.
.  Open the property that you want to use for Amazon.  +
→ The property's editing area will open.
.  Select the product type from the drop-down menu next to *Amazon link*.  +
→ A new drop-down menu will appear.
.  Select the Amazon option from the drop-down menu.
.  Click on *Add*.  +
→ The link will be created.

[IMPORTANT]
.Number of links
====
In plentymarkets, you can save a maximum of 8 links for one property.
====

[TIP]
.Tip: Property type "selection"
====
All property types can be used for the Amazon link. Properties that are listed as being the type *Selection* and *Text* can be used to transfer multilingual properties.
====

[.subhead]
Activating a property for an item

In the last step, activate the <<item/managing-items#80, *property*>> in the item settings and save a value.

[.instruction]
Activating a property for an item:

.  Go to *Item » Edit item*.
.  Open the item.
.  Click on the *Properties* tab.
.  Activate the property by placing a check mark next to it.
. *Save* the settings.  +
→ The field will be created for entering the value.
.  Enter a value.
. *Save* the settings.

Learn more about linking properties in the following video tutorial:

video::202025898[vimeo]

[#1500]
==  Activating the data exchange

This chapter describes the settings that need to be configured in order to exchange data between your plentymarkets system and the market Amazon. First, you will learn how to export all of the relevant data about your items and stock. Second, you will learn how to automatically import Amazon orders via the XML interface and how to manually import them with a CSV file. Third, you will learn how to send shipping confirmations to Amazon, how to synchronise FBA stock and how to reset order reports from Amazon.

[#1600]
===  Exporting item data

In the *System » Markets » Amazon » Data exchange » Data export*, two data exports can be generated. On the one hand, the data export Seller Central which contains all relevant information about your items and stock and which can then be uploaded directly into Seller Central. On the other hand, the data export Marketplace which you can use to export item data for the BMVD categories on Amazon.

[#1700]
====  Setting up the data export Seller Central

Use the *Seller Central* area of this menu to manually generate a data export that contains all relevant information about items and stock and that can be uploaded directly to Amazon Seller Central. To do so, proceed as follows.

[IMPORTANT]
.Listing items in several categories
====
If you wish to offer items in several categories, you will have to generate the different catalogues as export files one after the other.
====

[.instruction]
Setting up the data export Seller Central:

.  Go to *System » Markets » Amazon » Data exchange » Data export*.
.  Carry out the settings in the *Seller Central* area. Pay attention to the information given in table 8.
.  Click on *Load file* to export the data.  +
→ The data export will be in CSV format.
.  Save the CSV file on your computer so that you can use it later.

.data export Seller Central
[cols="1,3"]
|====
| Setting | Explanation

|*Amazon account*
| Select the Amazon account.

|*Export the item catalogue*
| Select the item catalogue for the export. When exporting the item catalogue to Amazon, only those items will be taken into consideration that were edited during the last 24 hours. Stock and prices will continue to be synchronised automatically.

|*Items with flags only*
| Choose which items should be exported: *all items*, *all items with flags*, *all items without flags* or only those items with a specific flag.

|*Item*
| Select an item quantity.

|*Date (from)*
| Enter a date.  +
*New:* = Newly listed items will only be exported starting from this date.  +
*Changed:* = Changed or updated items will be exported.

|*Manufacturers*
| Select *ALL* or a certain manufacturer.
|====

[#1800]
====  Setting up the data export Marketplace

In the *Marketplace* area of this menu, you export item data of the BMVD categories to Amazon. To do so, proceed as follows.

[.instruction]
Setting up the data export Marketplace:

.  Go to *System » Markets » Amazon » Data exchange » Data export*.
.  Pay attention to the explanations given in table 9 and carry out the settings in the *Marketplace* area.
.  Click on *Load file* to export the data.  +
→ The data export will be in CSV format.
.  Save the CSV file on your computer so that you can use it later.

.data export Marketplace
[cols="1,3"]
|====
| Setting | Explanation

|*Amazon account*
| Select the Amazon account.

|*Genre*
| Select one of the following BMVD categories: *Books*, *Music*, *Video* or *DVD*.

|*Items with flags only*
| Choose which items should be exported: *all items*, *all items with flags*, *all items without flags* or only those items with a specific flag.

|*Procedure*
| Select the procedure for the export.  +
*Update/add item* = The data transmitted in the CSV file will be added/updated on Amazon.  +
*Remove offers* = The offers transmitted in the CSV file will be removed from Amazon.  +
*Delete data completely from the system* = The data transmitted in the CSV file will be completely deleted from Amazon.

|*Delivery*
| Select a shipping method.
|====

[NOTE]
.Uploading a stock file to Seller Central
====
When uploading BMVD product data to Seller Central, select the option *Inventory loader file* instead of the option *Inventory files for non-media categories*.
====

[#1900]
===  Importing Amazon orders

Go to *System » Markets » Amazon » Data exchange » Order import* to set up the import of Amazon orders. Orders can be imported automatically via the XML interface or they can be imported manually with a CSV file. Both possibilities are described below.

[#2000]
====  Automatically importing orders

Proceed as follows to set up the automatic order import.

[.instruction]
Setting up the automatic order import:

.  Go to *System » Markets » Amazon » Data exchange » Order import*.
.  Select the option *Retrieve XML interface* from the *Process for order import* drop-down menu.  +
→ A second drop-down menu will appear.
.  Select an account from the *Amazon account* drop-down menu.
.  Click on *Preview* to show a preview of the import.

[#2100]
====  Manually importing orders

Proceed as follows to set up the manual import of Amazon orders.

[.instruction]
Setting up the manual order import:

.  Go to *System » Markets » Amazon » Data exchange » Order import*.
. Select the option *Import CSV file* from the *Process for order import* drop-down menu.  +
→ The *Settings* area will open.
.  Carry out the settings as desired. Pay attention to the information given in table 10.
.  Click on *Preview* to show a preview of the import.

order import of the Amazon market

Setting
Explanation *Book incoming payment* The payment is automatically booked when importing the order. *Use old format* Activate if you still use the old Amazon import format. *Client* Select the client for the order import. *Amazon account* Select the Amazon account. *CSV file* Select the CSV file for the order import. [.instruction]
Selecting the CSV file for the order import:

.  Click on *Browse*.
.  Select the CSV file for the import.
.  Click on *Open*.
.  Click on *Preview*.  +
→ The available orders will be displayed.
.  Find the orders that you want to import and place check marks next to the *Import* option.
.  Click on the *gear-wheel icon* to carry out the import.

[TIP]
.Tip: Imported orders
====
If orders are imported from Amazon that you did not upload with plentymarkets and/or that contain items which have not yet been created in plentymarkets, then you can manually assign the items for these orders and set the corresponding status. Alternatively, you can create the item directly in your plentymarkets system.
====

[IMPORTANT]
.Missing invoice address
====
If the invoice address is missing from the orders that were retrieved from Amazon, then contact the Amazon support. Amazon has to carry out this setting.
====

[TIP]
.Original currency and standard currency are different
====
Additional information is saved for orders that are imported with a different currency than the standard currency saved in plentymarkets. In this case, both the original currency and the original gross and net amounts will be saved for every item included in the order.
====

[#2200]
===  Sending shipping confirmations to Amazon

As soon as the Amazon order has been dealt with in your plentymarkets system and the goods have been shipped, you have to inform Amazon of the new status so that the sales figures can be credited to your account. Your plentymarkets system automatically takes care of this important step via the interface as well.

Orders have to meet the following requirements in order for the shipping confirmation to be sent to Amazon:

*  Referrer: Amazon or an Amazon sub-referrer
*  Status range 7 (less than 8)
*  External order number
*  Imported order (not manually created)
*  Outgoing items booked (time must not be in the future)

If the shipping confirmation is not automatically transferred, e.g. because the servers are temporarily unavailable, or if you want orders to be manually confirmed shortly before an accounting deadline, so that they will still be taken into consideration during the next payment, then you can also transfer shipping confirmations manually to Amazon. No shipping confirmations will be sent to Amazon for Prime orders (Amazon_Prime, Amazon_Prime_SameDay, Amazon_Prime_NextDay and Amazon_Prime_SecondDay).

[.instruction]
Manually sending a shipping confirmation to Amazon:

.  Go to *System » Markets » Amazon » Data exchange » Shipping confirmation*.
.  Select an Amazon account from the drop-down menu.
.  Enter a date next to the option *Items shipped on*.  +
→ All of the outgoing items from this date will be transmitted to Amazon.
.  Click on *Send shipping confirmation*.

[#2300]
===  Resetting order reports

In the menu *System » Markets » Amazon » Data exchange » Reset order reports*, you can reset the Amazon order reports from a specific date.

If you reset order reports from a specific date, then these order reports will once again become available for import. When carrying out the import again, only the missing orders will be imported from the date. This is done by synchronising the Amazon transaction number. If a transaction number already exists, then the order will not be imported again. This ensures that orders will not be duplicated.

[.instruction]
Resetting an order report:

.  Go to *System » Markets » Amazon » Data exchange » Reset order reports*.
.  Select an Amazon account from the drop-down menu.
.  Select a date for which you want to reset the order reports.
. *Save* the settings.

[#2400]
===  Synchronising stock

Stock is synchronised with Amazon in the menu *System » Markets » Amazon » Data exchange » FBA stock*. There are a few different ways to do this. You can use the hourly automatic stock synchronisation, an automatic procedure or a CSV file.

[IMPORTANT]
.Only for Amazon Multi-Channel
====
This feature is for <<omni-channel/multi-channel/amazon#16-1, *Amazon Multi-Channel*>> only.
====

In plentymarkets, a distinction is made between automatic stock synchronisation and manual stock synchronisation. Both procedures are described below.

[#2500]
====  Automatically synchronising stock

Proceed as follows to automatically synchronise stock.

[.instruction]
Automatically synchronising stock:

.  Go to *System » Markets » Amazon » Data exchange » FBA stock*.
.  Select the Amazon account in the *Automatically* tab.
.  Click on *Synchronise FBA stock*.

4 minutes are allotted for this process. If Amazon does not provide the data within this time frame, then no synchronisation will take place. The next request will then use the previous data that was not transferred. This can lead to errors. Therefore, we recommend that you manually synchronise data with a CSV file as described in the next chapter.

Stock information will only be synchronised for those items that had their stock changed on Amazon in the last 30 days. We recommend that you use the manual synchronisation for the first import. The stock is synchronised according to the *basic settings* in plentymarkets.

[#2600]
====  Manually synchronising stock

The manual synchronisation is made with a CSV file.

[IMPORTANT]
.Assigning SKU numbers
====
If you want to manually synchronise data, then you also have to specify how SKU numbers should be assigned to the stock. This is specified in the <<omni-channel/multi-channel/amazon#2-3, *Basic settings*>>.
====

Before you carry out this synchronisation, you have to request the corresponding report file from Amazon in Seller Central. Download this CSV file and save it on your computer.

[.instruction]
Manually synchronising stock:

.  Go to *System » Markets » Amazon » Data exchange » FBA stock*.
.  Click on the *Manual* tab.
.  Select the Amazon account.
.  Click on *Browse* to select the CSV file that you have just saved.
. *Save* to carry out the synchronisation.

[#2700]
==  Retrieving Amazon orders

Anyone who has worked with another shop system in the past can certainly remember just how time-consuming daily order processing in the Seller Central portal can be. All that is made significantly easier with plentymarkets. Here, all orders from all connected markets are collected together into one order folder. Amazon orders will automatically become plentymarkets orders, which you can quickly and effectively work with according to the fulfilment procedure that you are accustomed to. You do not even have to worry about the order import. The interface takes care of that for you in the background. A few requirements have to be fulfilled so that everything works correctly. These are summarised in the following.

Orders are retrieved every 15 minutes. However, in some cases it can take up to 90 minutes until an order that was generated in Amazon will appear in your plentymarkets system. That is not a malfunction, but rather is the only possibility due to technical reasons. Usually, an email from Amazon will inform you about the sale beforehand and you can already see the order in Seller Central.

[#2800]
===  Carrying out settings for the interface in plentymarkets

The basic settings *Incoming payment* and *Shipping confirmation* are relevant for importing orders. We assume that you transfer orders with the status *[5] cleared for shipping* and that you let the daily shipping confirmation be generated automatically by your plentymarkets system. Check these settings once again.

For further information about manual and automatic order import, refer to the *<<omni-channel/multi-channel/amazon#12, Automatically importing FBA orders>>* chapter.

[#2900]
===  Checking the requirements in the Seller Central portal

In order for you to retrieve orders via the interface, a specific requirement has to be fulfilled in Seller Central that you should check in advance.

Log into the Seller Central portal. The order reports have to contain a text similar to the following: *You are currently receiving scheduled order reports via XML.* If this is not the case or if a different message is displayed there, then contact the Amazon support, since you cannot carry out the necessary settings yourself.

[WARNING]
.Do NOT request the report
====
You may NOT click on the yellow *Request report* button in the area *Request an order report*. Otherwise the scheduled order reports via XML will no longer function. If you have nevertheless done this by mistake, then contact the Amazon support in order to restore the configuration.
====

[#3000]
===  Editing returns of Amazon orders

Even with Amazon, you have to anticipate the occasional order cancellation after a shipment has taken place. The customer then has to send the items back to you directly. For further information about creating a return in plentymarkets and resetting the outgoing items again, refer to the *<<stock-management/outgoing-items#, Outgoing items>>* page of the manual.

[.subhead]
Manually reversing with Seller Central

Since Amazon received the customer's payment on your behalf, the reversal also has to take place via Amazon. You also have to take care of this in the order folder in Seller Central.

[IMPORTANT]
.Carrying out a reversal manually or with the help of an event procedure
====
The interface does not automatically trigger the refund of the purchase price with Amazon. Rather, this has to be carried out manually or automatically with the help of an event procedure. If you forget to do this, then you risk a customer complaint with Amazon and negative feedback.
====

Returns can be reported to Amazon in form of credit notes with the help of an event procedure. Returns for Amazon can only be created for orders of the type credit note. To do so, proceed as follows.

[.subhead]
Creating order statuses

First, go to *<<order-processing/orders/managing-sales-orders#order-status, System » Orders » Order status>>*. Create an order status for Amazon returns, e.g. [9.6] Return sent to Amazon. You will need this order status for the Amazon settings.

[.subhead]
Setting the order status

Set this order status in the Amazon settings as described below.

[.instruction]
Setting an order status for returns:

.  Go to *System » Markets » Amazon » Settings*.
.  Open the Amazon account.
.  Click on the *Order settings* tab.
.  For the option *Status for transmitted returns*, select the order status that you previously created for Amazon returns.
. *Save* the settings.

Set up an *<<basics/automation/event-procedures#, event procedure>>* to automatically send returns in form of credit notes to Amazon.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*.  +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *Event* listed in table 11.
. *Save* the settings.
.  Carry out the settings as desired. Pay attention to the information given in table 11.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure for sending automatic returns to Amazon
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order generation: New return*
|

|*Filter*
|*Order &gt; Referrer*
|*Amazon* or a suitable Amazon sub-referrer, e.g. Amazon France

|*Procedure*
|*Return &gt; Create a return at Amazon*
|
|====

[#3100]
=== Importing pending orders from Amazon

Pending orders will be imported in status 1 into your plentymarkets system and remain there until Amazon approves the orders. Until the approval, no addresses or prices will be saved for the order. After the approval, the order will be updated and dresses and prices will be saved. The automatic stock update decides in which status the order will be placed.

[#3110]
==== Reserving stock for pending orders

There are two ways to reserve stock for pending orders in plentymarkets. Use an event procedure or the basic settings of an the order. The event procedure is used to put the order from status 1 to an status where stock is reserved.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*.  +
→ The *Create new event procedure* window will open.
.  Enter the name.
.  Select the *Event* listed in table 11.
. *Save* the settings.
.  Carry out the settings as desired. Pay attention to the information given in table 11.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.Event procedure for automatically updating order statuses
[cols="1,3,3"]
|====
|Setting |Option |Selection

|*Event*
|*Ne incomplete order*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*Amazon referrers*

|*Procedure*
|*Order &gt; Change status*
|*Select the status in which stock is reserved.*
|====

In the basic settings of the order you can define with the setting *Status for order reservation* in which order statuses stock is reserved.

[.instruction]
Defining order status for stock reservation:

.  Go to *System » Orders » Settings*.
.  Select for the setting *Status for order reservation* the statuses for which stock should be reserved.
. *Save* the settings.

[#3200]
==  Using the Amazon gift service

By activating the Amazon gift service, your customers can choose to have their items gift wrapped and they can leave a gift message during the order process on Amazon. These options will be transferred to plentymarkets when orders are automatically retrieved. No additional settings need to be carried out. Each order item containing gift options will have an additional line of information added to it directly behind the actual ordered item. It will include the type of packaging as well as the greeting.

Activate the gift options in Amazon Seller Central in order to use the gift service.

[TIP]
.Tip: Multiple types of packaging and surcharges
====
You can add various types of packaging and define surcharges.
====

[#3300]
==  Using the FBA service by Amazon

The abbreviation FBA stands for Fulfilment by Amazon. Instead of dealing with the orders yourself, packaging the items and sending them, you let Amazon take care of this task for you with the FBA programme. Of course, you then have to store at least some of your items with Amazon.

[#3400]
===  Creating a warehouse for Amazon FBA

Go to *System » Markets » Amazon » Settings » Tab: Order settings* and use the *Warehouse* option to select which warehouse you would like to use for Amazon fulfilment orders. This way, you can be sure that the complete range of stock management functions remain intact with the FBA programme and that you can keep track of the stock at Amazon in your plentymarkets system.

[.instruction]
Creating a warehouse:

.  Go to *System » Stock » Warehouse*.
.  Click on the small triangle on the right-hand side of the line *Warehouse*.  +
→ The *New warehouse* button will appear.
.  Click on the *New warehouse* button.  +
→ The *New warehouse* window will open.
.  Enter a name.
.  Select a *Warehouse type*.
.  Select *Amazon* as *logistics type*.
. *Save* to create the warehouse.  +
→ The warehouse will be listed in the overview in alphabetical order.
.  Expand the warehouse to display the submenus.
.  Carry out further settings. Pay attention to the explanations given on the *Settings* page of the manual.
. *Save* the settings.

Only you can decide whether the advantages tied to the FBA service outweigh the disadvantages for your personal situation as an online seller. Here we would only like to make reference to a few important points:

*  Amazon order processing takes place quickly and reliably. Peak times before Christmas run just as smoothly for store owners as the summer slump while most people are away on vacation.
*  Your listing on the market improves noticeably. You can expect higher sales figures.
*  The FBA service is subject to costs. Naturally, your gross margin will decrease. When doing a comprehensive comparison of the costs, keep in mind that the FBA service includes the expenses tied to storage, handling orders, customer service etc. and as such, relieves you from these expenditures.
*  Generally, items that are stored with Amazon can only be offered there as well. You need to have separate stock for other markets. Amazon's Multi-Channel fulfilment service, however, is a variation that provides you with additional possibilities in this matter.
*  You have much less stress with deliveries that cannot be sent or that are delayed. Packages with the Amazon logo are generally given priority.

[#3500]
===  FBA order import

Proceed as follows to set that your FBA orders are automatically imported in your plentymarkets system once a day.

[.instruction]
Automatically importing FBA orders:

.  Go to *System » Markets » Amazon » Settings*.
.  Select the account.
.  Click on the *Order settings* tab.
. Place check marks next to the *Active* in the *Shipment by Amazon (FBA)*.
. *Save* the settings.

Order processing has the following steps:

*  The customer makes a purchase on Amazon.
*  Amazon sends the items.
*  The plentymarkets system requests a report.
*  Amazon creates the report.
*  The next day, plentymarkets automatically checks whether any Amazon reports exist. If they do, then these reports are imported.
*  Orders are generated in plentymarkets from the information contained in these reports.

[IMPORTANT]
.Note regarding the order import
====
Amazon only generates the list of orders once per day. Since it can take up to 2 days before an item is ready for shipping, FBA orders are available in your system with a time delay. Generally, the order confirmation that was generated by Amazon is available in your system two days after the item was shipped or a total of up to 4 days after it was ordered. The punctuality of the deliveries, however, is not affected. They will be carried out with the quickness that is customary for Amazon.
====

Amazon FBA orders are imported with the parameters *Status* and *Referrer*. Select the *Status* that is most appropriate for your process. For example, this could be status *[7] Outgoing items booked*. The referrer will automatically be set to Amazon FBA or an Amazon FBA sub-referrer, e.g. Amazon FBA USA. The date when items are shipped will be saved directly in plentymarkets. Therefore, stock will not be reserved for items that are included in the order.

[TIP]
.Event procedures for fulfilment
====
Configure the event procedures that are necessary for the fulfilment process. Such event procedures are having invoices generated and sent to your customers with the help of automatic emails, and having the order then switch to another status.  +
For further information, refer to the *<<basics/automation/event-procedures#, Event procedures>>* and *<<order-processing/fulfilment#, Standard fulfilment in detail>>* pages of the manual.
====

[.subhead]
European Fulfilment Network (EFN)

Amazon is continuously expanding its European Fulfilment Network for sellers that use shipment by Amazon. In order to use this network, it is required that you are fiscally registered in all countries in which you use FBA logistics centres. In order for your invoices to be generated correctly for these new logistics centres from the fiscal point of view, you can - in addition to your company location - select the warehouse location as basis for the default VAT rate. You can carry out these settings for each client (store) in the menu *System » Client » Select client » Locations » Select location » Accounting*. In the *VAT rates* tab, you save the necessary tax rates for the countries.

[TIP]
.Example: Logistics centre is located in Poland and items are shipped to Germany
====
To avoid that the Polish tax rate is used for orders that are shipped to Germany from a logistics centre in Poland, you also have to enter the country Germany with the German tax rate for the location Poland. To do so, go to *System » Client » Select client » Locations » Poland » Accounting » Tab: VAT rates*, select the country *Germany* and enter the German tax rate as well as the valid VAT number.
====

[#3600]
===  Automatically importing FBA returns

In case of a return, the purchaser will send the items back to Amazon. The return will be imported into your plentymarkets system and listed in the order menu. It will be given the return status that you selected in the *<<order-processing/orders/_basic-settings#, Settings » Orders » Basic settings>>* menu.

[IMPORTANT]
.Do not change the order
====
Returns will only be imported if the order exists in plentymarkets and its external order number was not changed.
====

Activate the import function as described below in order to automatically import FBA returns in your plentymarkets system.

[.instruction]
Activating the import function for FBA returns:

.  Go to *System » Markets » Amazon » Settings*.
.  Open the Amazon account.
.  Click on the *Order settings* tab.
.  Select the setting *Daily* from the *Returns import* drop-down menu in the *Shipment by Amazon (FBA)* area.
. *Save* the settings.

Learn more about FBA in the following video tutorial:

video::198346338[vimeo]

[#3700]
==  Setting up Amazon Multi-Channel

Amazon Multi-Channel Fulfillment is a service that enables you to fulfill orders from sales channels other than Amazon.com using the inventory that you have stored in the Amazon fulfillment center (source: Amazon).

In other words, the Multi-Channel function allows you to store your items with Amazon and have Amazon ship your items even though you sell these items on external markets. This chapter describes which settings you have to carry out in your plentymarkets system so that these orders will be processed by Amazon.

The following steps are necessary to configure your stock and item data for Amazon Multi-Channel.

[#3800]
===  Creating a warehouse for Amazon Multi-Channel

Create a warehouse, if you have not yet created one as described in the <<omni-channel/multi-channel/amazon#10, *Using the FBA service by Amazon*>> chapter. When using Multi-Channel fulfilment, it is important to set up a warehouse for each country-specific Amazon marketplace with the logistics type *Amazon* and the country as its location.

[IMPORTANT]
.Example of matching Amazon platform and warehouse location
====
Multi-Channel fulfilment takes place via amazon.co.uk. Create a new warehouse Amazon UK with the logistics type *Amazon* and the location Great Britain. The items must actually be stored with Amazon in that country e.g. in Great Britain. Otherwise they cannot be handled and shipped by amazon.co.uk.
====

[#3900]
===  Setting up the item availability for Amazon Multi-Channel

Carry out the following settings for the items that you want to make available for Amazon Multi-Channel.

[.instruction]
Setting up the item availability for Amazon Multi-Channel:

.  Go to *Item » Edit item*.
.  Open the item.
.  Open the *Multi-Channel* tab.
.  Carry out the settings in the *Amazon* area. Pay attention to the information given in table 5 in the <<en/omni-channel/multi-channel/amazon/amazon-setup#700, *Setting the item availability*>> chapter.
. *Save* the settings.

[#4000]
===  Carrying out settings for Amazon Multi-Channel

Carry out the settings in the Amazon menu as described below.

[.instruction]
Configuring Amazon Multi-Channel:

.  Go to *System » Markets » Amazon » Settings*.
.  Click on the *Order settings* tab.
.  Carry out the settings in the section *Shipment by Amazon (FBA)*. Pay attention to the information given in table 12.
. *Save* the settings.

.configuring Amazon Multi-Channel
[cols="1,3"]
|====
| Setting | Explanation

|*Order import*
| Select the option *Daily* to import the orders on a daily basis.

|*Stock import*
| Select the option *Hourly* to import the stock on an hourly basis.  +
Only changes in the stock data will be taken into consideration. For further information about stock import options, refer to the <<omni-channel/multi-channel/amazon#9-5, *Synchronising stock*>> chapter.

|*Warehouse*
| Select which <<omni-channel/multi-channel/amazon#10, *warehouse*>> should be used for Amazon shipments.

|*Status for transmitted orders*
| Determines which order status should be used for Multi-Channel FBA orders that were transferred to FBA.

|*Shipping category*
| Select a shipping category.  +
*Standard* = Normal shipping  +
*Expedited* = Express shipping  +
*Priority* = Fastest shipping service
|====

[#4100]
===  Automatically transferring the shipping permission to FBA

Set up an *<<basics/automation/event-procedures#, event procedure>>* to automatically inform Amazon about the order. After Amazon has received this information, the order will be processed and the item(s) will be made ready for shipping.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*.  +
→ The *Create new event procedure* window will open.
.  Enter a name.
.  Select the *event* listed in table 14.
. *Save* the settings.
.  Carry out the settings as desired. Pay attention to the information given in table 14.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--
.event procedure to automatically transfer the shipping permission to FBA
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order change: Status change &gt; [5] Cleared for shipping*
|

|*Filter 1*
|*Order &gt; Order warehouse*
|*Amazon Multi-Channel*

|*Filter 2*
|*Shipping &gt; Shipping by FBA only*
|

|*Procedure*
|*Shipping &gt; Transfer shipping permission to FBA*
|
|====

When switching to status 5, Amazon will be informed that the items are cleared for shipping. Amazon ships the items and your plentymarkets system will receive a confirmation from Amazon. The order switches to status 5.1, as determined in the *<<omni-channel/multi-channel/amazon#22, order settings>>*. The package number will be imported into your plentymarkets system.

[TIP]
.Import of package numbers
====
The package number import is carried out once a day.
====

[#4200]
==  Editing Amazon Prime orders

With the help of filters in the areas order search and event procedures, orders with shipping conditions for Amazon Prime will be separately treated in plentymarkets. Shipping labels for Amazon Prime orders are created via the Amazon Merchant Fulfilment API.

[IMPORTANT]
.Mandatory fields for registering Amazon Prime orders
====
In order to handle Amazon Prime orders, certain information has to be saved in the menu *System » Orders » Shipping » Shipping service provider » Settings*. Amazon requires the following mandatory fields: *Company*, *Street*House number*, *postcode*, *town*, *Country*, *Telephone* and *Email*. These mandatory field have to be filled in order to handle Amazon Prime orders.
====

[#4300]
===  Filtering Amazon Prime orders

All of your orders are displayed in the menu *<<order-processing/orders/managing-sales-orders#, Orders » Edit orders>>*. You can use *<<order-processing/orders/managing-sales-orders#order-search, filters>>* to narrow down which orders are displayed. For example, you can display Amazon Prime orders only.

The filter *Amazon* includes the following options:

* *ALL* filters all Amazon orders.
* *Prime* filters all Amazon Prime orders except Prime SameDay, Prime NextDay and Prime SecondDay.
* *Prime (all)* filters all Amazon Prime orders, including Prime SameDay, Prime NextDay and Prime SecondDay.
* *No* Amazon Prime orders will not be taken into consideration.
* *Prime SameDay* filters only Prime SameDay orders.
* *Prime NextDay* filters only Prime NextDay orders.
* *Prime SecondDay* filters only Prime SecondDay orders.
* *SameDay* filters Amazon orders that do not belong to Amazon Prime but need to be shipped the same day.
* *NextDay* filters Amazon orders that do not belong to Amazon Prime but need to be shipped the next day.
* *SecondDay* filters Amazon orders that do not belong to Amazon Prime but need to be shipped the day after tomorrow.

[#4400]
===  Creating a shipping label for Amazon Prime orders

Amazon requires you to create shipping labels for Amazon Prime orders via the Amazon Merchant Fulfilment API. In return, Amazon provides shipping service providers who offer a discounted price. The following describes how to link shipping profiles with Amazon Prime.

[.instruction]
Linking shipping profiles with Amazon Prime:

.  Go to *System » Orders » Shipping » Settings » Tab: Shipping profiles*.
.  Select the shipping profile that you want to link with Amazon Prime.
.  Select the filter *Amazon Prime* in the *Loyalty program* section.
.  Click on the *Table of shipping charges* tab.
.  Select the shipping method for the *Amazon Prime Service* option in the *Amazon Prime* area.
. *Save* the settings.

[TIP]
.Tip: Pay attention to the shipping package
====
Pay attantion to the shipping packages saved for the shipping profile to prevent overpriced labels.
====

Afterwards, register your Amazon Prime orders for the Amazon shipping provider that you have selected. To do so, go to *Orders » Shipping centre » Tab: Register*. You have to search for Amazon Prime orders in the *Search* tab before you can register them. The orders that were found will be displayed here.

[TIP]
.Tip: Pay attention to the shipping service provider
====
table of shipping chargesPay attention to the selected shipping service provider. Otherwise, you won't be able to set the correct Amazon services in the tables of shipping charges.
====

[.instruction]
Registering Amazon Prime orders:

.  Go to *Orders » Shipping centre » Tab: Search*.
.  Search for the Amazon Prime orders that you want to register.
.  Click on the *Register* tab.
.  Select the *Amazon Prime* option from the *Shipping service provider* drop-down menu.
.  Click on *Register*.
.  Open the order.  +
→ After successfully registering the order, a PDF icon appears in the *Overview* area. By clicking on this icon, you can download the shipping label.

Learn more about Amazon Prime in the following video tutorial:

video::189296596[vimeo]

[#4500]
==  Activating the Amazon payment method

The *Amazon* payment method is used for orders that were placed on Amazon and transferred to your plentymarkets system. Do not confuse this with *Amazon Pay*, which is a way for customers to use the Amazon checkout process when placing orders in your online store.

Activate the *<<order-processing/payment#, payment method>>* *Amazon* as described below.

[.instruction]
Activating the Amazon payment method:

.  Go to *System » Orders » Payment » Methods*.
.  Click on the folder *International &gt; Amazon*.  +
→ The settings for the Amazon payment method will be displayed.
.  Place a check mark next to the option *Active*.
.  Carry out additional settings as desired.
. *Save* the settings.

[TIP]
.Permitting the payment method in customer classes
====
Go to *System » CRM » Classes* to activate or deactivate the *Permitted payment methods*.  +
For further information, refer to the *<<omni-channel/multi-channel/amazon#4, Payment methods and customer classes>>* page of the manual.
====

For further information, refer to the *<<order-processing/payment#, Payment methods>>* page of the manual.

[#4550]
== Setting up Amazon Business

Use Amazon Business to sell your items to commercial customers. Before carrying out the settings in plentymarkets, you will have to link:https://services.amazon.de/programme/b2b-verkaufen/merkmale-und-vorteile.html[register^] on Amazon for the program. In order for B2B items to be transferred to Amazon, you have to activate an Amazon account for Amazon business as well as create and link sales prices and quantity based discounts. Proceed as described below in order to transfer your items to Amazon business.

[IMPORTANT]
.Information regarding Amazon Business
====
Currently Amazon Business is only available for the country platforms Amazon.de and Amazon.co.uk.
====

[#4555]
=== Activating Amazon business

Got to the menu *System » Markets » Amazon » Settings* to activate the Amazon account for Amazon Business.

[.instruction]
Activating an Amazon account for Amazon business:

.  Go to *System » Markets » Amazon » Settings » Open account » Tab: Settings*.
.  Place a check mark next to the option *B2B*.
. *Save* the settings.

[#4560]
=== Defining a sales price

After having activated the Amazon account for Amazon business, you have to create and link sales prices for B2B items. In addition to the standard price for items minimum quantity 1, you can create up to 5 more prices for quantity based discounts. It is possible to create prices for quantity based discounts as fixed prices or percentage.

[#4565]
==== Creating a sales price

First, create a standard price for B2B items. To do so, select the option *Minimum quantity*, the *Referrer* and the *Amazon account* in the *System » Item » Sales prices* menu.

[.instruction]
Creating a standard sales price for B2B items:

. Go to *System » Item » Sales prices*.
. Click on *New*.  +
→ The *New* tab will open.
. Enter *1* for the Option *Minimum quantity*.
. Select the referrer *Amazon Germany B2B*.
. Select the *Amazon account*, that is activated for Amazon B2B.
. Pay attention to the explanations given in table 10 in the *<<item/managing-items#880, Managing items>>* page of the manual and carry out further setting as desired.
. *Save* the settings.

[#4570]
==== Creating sales prices for quantity discounts

Proceed as described below to offer quantity based discounts to Amazon business customers.

[.instruction]
Creating sales prices for quantity discounts:

. Go to *System » Item » Sales prices*.
. Click on *New*.  +
→ The *New* tab will open.
. Enter the item quantity that you would like the discount to begin with for the option *Minimum quantity*. The quantity has to be larger than 1.
. Select the referrer *Amazon Germany B2B*.
. Select the *Amazon account*, that is activated for Amazon B2B.
. Pay attention to the explanations given in table 10 in the *<<item/managing-items#880, Managing items>>* page of the manual and carry out further setting as desired.
. *Save* the settings.

As an alternative, you can also display up to 5 more sales prices in percent for quantity based discounts, using property links. To do so, select the Amazon link *quantity_price_type* when creating the property of the type *Text* or *Selection* and enter the value *percent* when linking the property to the item. Additionally, create properties for *quantity_lower_bound1-5* and for the discount quantity and *quantity_price1-5* for the percentage.

[.instruction]
Creating a property for quantity_price_type:

.  Go to *System » Item » Properties*.
.  Open the property that you want to use for Amazon.  +
→ The property's editing area will open.
.  Select the product type from the drop-down menu next to *Amazon link*.  +
→ A new drop-down menu will appear.
.  Select the Amazon filed *quantity_price_type* from the drop-down menu.
.  Click on *Add*.  +
→ The link will be created.

Next, activate the <<item/managing-items#80, *property*>> in the item settings and enter the value *percent*.

[.instruction]
Activating a property for an item:

.  Go to *Item » Edit item*.
.  Open the item.
.  Click on the *Properties* tab.
.  Activate the property by placing a check mark next to it.
. *Save* the settings.  +
→ The field will be created for entering the value.
.  Enter the value *percent*.
. *Save* the settings.

Proceed in the same manner to create the properties *quantity_lower_bound1-5* and *quantity_price1-5*. Use properties of the type *Whole number* for *quantity_lower_bound1-5* and properties of the type *Whole number* or *Decimal number* for *quantity_price1-5*.

[#5700]
==  Setting up Amazon Pay

*Pay with Amazon* is a comprehensive payment solution for online sellers. Offer *Pay with Amazon* and enable millions of Amazon customers to shop securely on your website without re-entering their delivery and payment information. Customers can complete purchases quickly without leaving your website.

The advanced option for Payment with Amazon is special because it offers pure payment processing. This means that you only transfer the necessary amount due in order to process the payment. No details about the shopping cart or item data will be transferred (see Amazon).

The *<<order-processing/payment/amazon-pay#, Amazon Pay>>* page of the manual provides you with important information about integrating the payment provider in plentymarkets.

[#6600]
==  Retrieving the API log

The menu *<<basics/data-exchange/api-log#, Data » API log>>* contains a history of processes that run via the Amazon interface. The following formats are available for Amazon:

* *AmazonArticleExportAutomatic*
* *Amazoncatalog*
* *AmazonControllerOrders*
* *AmazonFBAImportReturns*
* *AmazonFBAInventoryUpdate*
* *AmazonFBAOrders*
* *AmazonOrder*
* *AmazonOrderFulfillment*
* *AmazonPayments*
* *AmazonPaymentsAdvanced*
* *AmazonPaymentsFulfillment*
* *AmazonPriceUpdate*
* *AmazonRequestReport*
* *AmazonStock*
* *ArticleAmazonCSV*
* *Reader_ArticleAmazonCSV_Execution*

[.instruction]
Viewing the API log:

.  Go to *Data » API log » Tab: API log*.
.  Select a format from the drop-down menu *Process*.
.  Select a *Date* if you only want to see entries for a specific day.
.  Click on *Search* to carry out the search.  +
→ The processes will be displayed.

Learn more about the API log in the following video tutorial:

video::204331739[vimeo]
