= Benutzerkonten verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Eigner, Benutzer, Benutzerkonten, Benutzerkonto, Rollen, Berechtigungen, Rechte
:description: Arbeiten mit plentymarkets: Verwalte Benutzerkonten, lege neue Benutzerkonten an und bearbeite bestehende Benutzerkonten im plentymarkets System.
:position: 30
:url: basics/admin-aufgaben/benutzer-verwalten
:id: CHBIF6G
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

:benutzerzugang: pass:quotes[Wähle einen **Benutzerzugang**.]
:tabelle: Beachte dazu die Erläuterungen in <<tabelle-benutzerzugänge>>.

In der Benutzerverwaltung erstellst du neue Benutzerkonten und bearbeitest bestehende Benutzerkonten. Darüber hinaus verknüpfst du Benutzerkonten mit Rollen und Zugängen.

* Mit Rollen gruppierst du Benutzerkonten und vereinfachst die Zuordnung gleicher Berechtigungen zu mehreren Benutzerkonten.
* Mit Zugängen verteilst du Berechtigungen an Benutzerkonten und Schnittstellen. Einem Benutzerkonto des Zugangs REST-API zum Beispiel weist du individuell REST-Calls zu.

In jedem plentymarkets System sind kostenfrei fünf CUL-Benutzerlizenzen enthalten. Weitere Benutzerkonten buchst du im link:http://www.plentymarkets.eu/preise/[Konfigurator] hinzu.

[NOTE]
.Was ist eine CUL-Benutzerlizenz?
====
CUL steht für Concurrent-User-Lizenzmodell. Über die Lizenz wird festgelegt, wie viele Benutzerkonten gleichzeitig auf das plentymarkets Backend, die REST-API und die plentymarkets App zugreifen dürfen. Wir limitieren also nur die gleichzeitige Nutzung und nicht die Anzahl der Benutzerkonten, die du erstellen kannst.
====

[#35]
== Passwortsicherheit einstellen

Im Menü *System » Einstellungen » Benutzer » Sicherheit* stellst du die Anforderungen ein, die Benutzer erfüllen müssen, wenn sie ein neues Passwort vergeben. Um die Anforderungen zu aktivieren, verfahre wie im Folgenden beschrieben.

[.instruction]
Passwortsicherheit einstellen:

. Öffne das Menü *System » Einstellungen » Benutzer » Sicherheit*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-sicherheit-einstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Jedes neu eingegebene Passwort wird ab jetzt auf die Erfüllung der eingestellten Anforderungen geprüft.

[[tabelle-sicherheit-einstellen]]
.Passwortsicherheit einstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Passwortsicherheit aktivieren*
|Wird diese Option aktiviert, muss jedes neu eingegebene Passwort die eingestellten Anforderungen erfüllen.

|*Mindestlänge*
|Mindestanzahl an Zeichen für neue Passwörter eingeben. +
*_Hinweis:_* Aus Sicherheitsgründen muss die Mindestlänge 8 oder mehr Zeichen betragen.

|*Passwortkriterien*
|Kriterien aktivieren, die für neue Passwörter gelten sollen. +
*_Hinweis:_* Aus Sicherheitsgründen müssen mindestens 3 Kriterien aktiviert sein.

|*Mindestanzahl erfüllter Kriterien*
|Anzahl der Kriterien einstellen, die neue Passwörter mindestens erfüllen müssen. +
*_Hinweis:_* Aus Sicherheitsgründen müssen mindestens 3 Kriterien aktiviert sein.

|*Anzahl zuletzt benutzter Passwörter*
|Anzahl der zuletzt benutzten Passwörter einstellen, die nicht erneut verwendet werden dürfen. Der Nutzer wird darauf hingewiesen, wenn er versucht, eines der zuletzt benutzten Passwörter erneut einzugeben. Wenn diese Funktion nicht gewünscht ist, 0 eintragen oder leer lassen. +
*_Hinweis:_* Die Anzahl der zu speichernden Passwörter muss 20 oder weniger betragen.

|*Gültigkeitszeitraum des Passworts*
|Nach Ablauf des Gültigkeitszeitraums in Tagen wird das Benutzerkonto gesperrt. Wenn diese Funktion nicht gewünscht ist, 0 eintragen oder leer lassen.
|====

[#10]
== Benutzerkonto erstellen

Bei der Erstverwendung deines Systems ist bereits ein Standardbenutzerkonto des Zugangs *Admin*, also ein Konto mit Administratorrechten, vorhanden. Du benötigst mindestens ein Admin-Benutzerkonto. Erstelle deshalb entweder ein neues Benutzerkonto des Zugangs *Admin* und lösche danach das Standardbenutzerkonto oder bearbeite das vorhandene Benutzerkonto. Im Folgenden wird beschrieben, wie du ein Benutzerkonto eines beliebigen Zugangs erstellst.

include::./_textblocks/instructions/benutzerkonto-erstellen.adoc[]

Der Benutzername darf kein Leerzeichen enthalten und muss mindestens 5 Zeichen lang sein.

Mit einen Klick auf *Mein Konto* gelangst du direkt in dein Benutzerkonto.

Die Benutzerzugänge sind vorgegeben und die Einstellungen der Zugänge sind nicht änderbar. Welche Berechtigungen bei Zugängen voreingestellt sind und welche du noch individuell am Benutzerkonto einstellen kannst, findest du in dieser Tabelle:

[[tabelle-benutzerzugänge]]
.Übersicht der verfügbaren Benutzerzugänge
[cols="1,3"]
|====
|Zugang |Erläuterung

|*Admin*
|Zugang, der über alle Berechtigungen ohne Einschränkung verfügt und mindestens einem Benutzerkonto zugeordnet werden muss, da nur ein Admin weitere Benutzerkonten uneingeschränkt erstellen, verwalten und bearbeiten kann. Bei Verwendung mehrerer Admin-Konten sind diese gleichberechtigt.

|*Backend*
|Zugang, für den im Benutzerkonto unter *Tab: Berechtigung* <<basics/admin-aufgaben/benutzer-verwalten#100, Bereiche>> und <<basics/admin-aufgaben/benutzer-verwalten#110, Funktionen>> freigeschaltet werden.

|*REST-API*
|Zugang, für den im Benutzerkonto <<basics/admin-aufgaben/benutzer-verwalten#120, REST-Calls>> freigeschaltet werden. Die REST-Calls werden dann einzeln aktiviert. Es werden dem Benutzerkonto also nicht pauschal alle REST-Calls freigeschaltet. +

*Achtung*: Nutzern mit diesem Benutzerzugang wird der Zugriff auf das Backend verweigert.
|====


[NOTE]
Die Zugänge *Callcenter*, *Logistik*, *Blog* und *Newsletter2Go* existieren nicht mehr und wurden zu einem Backend-Nutzer migriert.


[#20]
== Benutzerkonto bearbeiten

Nachdem ein Benutzerkonto erstellt wurde, wird das Konto in der Benutzerkontoübersicht hinzugefügt. Benutzerkonten werden dort alphabetisch aufgelistet. Wähle ein Benutzerkonto aus, um Einstellungen an dessen Konto vorzunehmen. Die Anzahl der Einstellungen hängt zum einen von deinem Benutzerzugang und zum anderen von dem Benutzerzugang des zu bearbeitenden Benutzerkontos ab. Mehrere Benutzerkonten gleichzeitig bearbeitest du per *Gruppenfunktion*.

[.instruction]
Benutzerkonto bearbeiten:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Klicke auf *Benutzer öffnen*. +
→ Das Benutzerkonto wird in einem neuen Tab geöffnet.
. Nimm Änderungen und Einstellungen gemäß <<tabelle-stammdaten>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Passwort ist gespeichert
====
Das beim Erstellen des Benutzerkontos eingegebene Passwort ist im Bearbeitungsmodus nicht sichtbar, ist aber gespeichert. Du musst es beim Bearbeiten des Benutzerkontos nicht erneut eingeben.
====

[#30]
=== Stammdaten pflegen

Im Tab *Stammdaten* nimmst du Änderungen und Einstellungen an den Benutzerdaten eines Kontos vor. *Benutzername*, *IP-Beschränkung*, *Benutzerzugang* und *Rollen* können nur von Personen mit Administratorrechten geändert werden. Alle anderen Stammdaten können Personen auch in ihrem eigenen Konto anpassen. Zudem ist das Sperren eines Benutzerkontos in diesem Tab möglich.

[[tabelle-stammdaten]]
.Stammdaten eines Benutzerkontos
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Titelzeile*
|In der Titelzeile werden *Benutzer-ID*, *Benutzername* sowie *Datum* und *Uhrzeit der letzten Änderung* an dem Benutzerkonto angezeigt. +
Die Benutzer-ID ist eine eindeutige Identifikationsnummer, die vom System vergeben wird und nicht änderbar ist.

|*Benutzer gesperrt*
|Aktivieren, um das Benutzerkonto zu sperren. Gesperrte Personen können sich nicht mehr in das System einloggen.

|*Benutzername*
|Name ohne Leerzeichen eingeben. Der Name ist ein Pflichteintrag, der für den Login benötigt wird. Der Benutzername darf kein Leerzeichen enthalten und muss mindestens 5 Zeichen lang sein.

|*Realer Name*
|Realer Name des Benutzers, der in der Kopfzeile des plentymarkets Administrationsbereichs angezeigt wird.

|*E-Mail*
|E-Mail-Adresse des Benutzerkontos eingeben. Diese ist u.a. für Benachrichtigungen des Systems, Benachrichtigungen aus Ereignisaktionen und auch für die Gruppenkommunikation innerhalb des Systems wichtig.

|*Google Mail*
|Bei Verwendung von Gmail, hier die Gmail-Adresse des Benutzerkontos eingeben.

|*Skype-Name*
|Bei Verwendung von Skype, hier den Skypenamen des Benutzerkontos eingeben.

|*Farbe*
|Im Bearbeitungsfenster eine Farbe durch Verschieben der Farbauswahl festlegen, einen Hexadezimalwert oder RGB-Werte eingeben. Die Farbe erleichtert die Identifikation des Benutzerkontos in anderen Bereichen, zum Beispiel im <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#600, Kalender>>.

|*Zeitzone*
|Zeitzone des Benutzerkontos wählen.

|*Bild-URL*
|Bild-URL eingeben, um zum Beispiel einen Platzhalter für ein Foto für Blogbeiträge zu hinterlegen.

|*UI-Sprache*
|Sprache für den Admin-Bereich. Diese Sprache wird als Standard beim Login verwendet.

|*IP-Beschränkung*
|IP-Adresse des Rechners der Person des Benutzerkontos eingeben, damit sich die Person mit diesem Benutzerkonto nur über diese IP-Adresse in das plentymarkets System einloggt.

|*Benutzerzugang*
|Benutzerzugang des Benutzerkontos wählen. Es stehen die Zugänge *Admin*, *Backend* und *REST-API* zur Verfügung.

|*Rollen*
|Rollen des Benutzerkontos wählen. Damit Rollen zur Auswahl stehen, müssen zuvor <<basics/admin-aufgaben/benutzer-verwalten#70, Rollen>> erstellt werden.

|*Neues Passwort*
|Neues Passwort eingeben, um dem Benutzerkonto ein neues Passwort zu erteilen.

|*Passwort wiederholen*
|Passwort noch einmal eingeben.

|*Neue App-PIN*
a|include::../../app/_textblocks/benutzerrechte/app-pin.adoc[]

|*App-PIN wiederholen*
|PIN noch einmal eingeben.
|====

[#40]
=== Eigner aktivieren

Du legst im Tab *Eigner* fest, in welchen Bereichen das Benutzerkonto als Eigner verfügbar sein soll. Wenn du zum Beispiel einen Kalender erstellst, musst du für den Kalender Eigner einrichten. Aktiviere den Bereich *Kalender* im Tab *Eigner*.

[.instruction]
Benutzer als Eigner aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Öffne einen Benutzer.
. Öffne das Tab *Eigner*.
. Aktiviere die Bereiche, in denen das Benutzerkonto als Eigner verfügbar sein soll.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

// ACHTUNG!!!! Aus der GUI wird auf die Kapitel zu E-Mail-Postfächern verlinkt. Falls diese Inhalte verschoben werden, bitte Ziyad oder einem anderen Mitglied des Cloud-Teams Bescheid sagen, damit der Link angepasst wird. Danke.

[#42]
=== E-Mail-Postfächer verwalten

Wenn du deine Domains von plentymarkets verwalten lässt, kannst du als Person mit Admin-Rechten im Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten » Tab: E-Mail* E-Mail-Postfächer für Systembenutzer erstellen und verwalten. Diese E-Mail-Postfächer werden bei einem Drittanbieter, dem externen E-Mail-Provider link:https://mailbox.org/business/[mailbox.org^], angelegt und von diesem Drittanbieter gehostet. Nachfolgend wird beschrieben, wie du E-Mail-Postfächer und zusätzliche E-Mail-Adressen pro Postfach (Alias) erstellst.

[IMPORTANT]
.E-Mail-Postfächer anderer Provider
====
Die hier beschriebene Einrichtung gilt nur für plentymarkets Kunden, die ihre Domains von plentymarkets verwalten lassen und die den externen Dienstleister link:https://mailbox.org/business/[mailbox.org^] nutzen möchten. Wenn du deine E-Mail-Konten über einen anderen Provider verwaltest und darüber E-Mails durch dein plentymarkets System versenden möchtest, ist diese Einrichtung nicht erforderlich. Beachte aber auch dann das Kapitel <<crm/e-mails-versenden#100, E-Mail-Server-Zugangsdaten speichern>> auf der Handbuchseite <<crm/e-mails-versenden#, E-Mails versenden>>.
====

[#44]
==== Postfach erstellen

Lege für Benutzer, die ein eigenes Postfach bei mailbox.org erhalten sollen, wie unten beschrieben ein Postfach an. Du benötigst Admin-Rechte, um Postfächer und Alias anzulegen.

[.instruction]
Neues Postfach erstellen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Klicke auf *Mein Konto*.
. Wechsele in das Tab *E-Mail*.
. Klicke auf *Neu*. +
→ Das Fenster *Postfach erstellen* wird angezeigt.
. Wähle als E-Mail-Adresstyp *Postfach*.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-postfach>>.
. Klicke auf *Postfach erstellen*. +
→ Das E-Mail-Postfach wird beim externen Dienstleister mailbox.org erstellt.

[[tabelle-postfach]]
.Postfach erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*E-Mail-Adresstyp*
|E-Mail-Adresstyp *Postfach* wählen. +
*Postfach* = Legt ein neues E-Mail-Postfach an. +
*Alias* = Legt eine zusätzliche E-Mail-Adresse für ein bestehendes Postfach an. Die Auswahl des Postfachs erfolgt über die Option *Zielpostfach*.

|*E-Mail-Adresse*
|E-Mail-Adresse eingeben, die dem Postfach zugeordnet werden soll. Lokalen Teil der E-Mail-Adresse vor dem @ eingeben. Domain-Teil aus der Dropdown-Liste wählen. +
*_Hinweis:_* Für Testdomains, zum Beispiel @plenty-test-drive, sowie für externe Domains, die nicht über plentymarkets verwaltet werden, können keine Postfächer angelegt werden. +
*_Hinweis:_* Nach dem Löschen einer E-Mail-Adresse ist diese Adresse 48 Stunden gesperrt. Erst nach Ablauf dieser Frist kann diese E-Mail-Adresse erneut vergeben werden.

|*Vorname* +
*Nachname*
|Vornamen und Nachnamen der Person mit diesem Benutzerkonto eingeben. Dieser Name wird mit der E-Mail-Adresse als Absender angezeigt.

|*Systembenutzer*
|Benutzerkonto wählen, dem das Postfach zugewiesen werden soll.

|*Weiterleitungen*
|Wenn E-Mails, die an dieses Postfach gesendet werden, an ein anderes Postfach weitergeleitet werden sollen, eine oder mehrere E-Mail-Adressen eingeben. Mehrere E-Mail-Adressen durch Komma getrennt hinterlegen, zum Beispiel kunde@ihredomain.de,consultant@ihredomain.de.

|*E-Mails in Postfach speichern*
|Option wird wählbar, wenn eine Weiterleitung eingerichtet wird. +
Aktiviert = E-Mails werden an die Ziel-E-Mail-Adressen weitergeleitet. Kopien der weitergeleiteten E-Mails werden auch in diesem Postfach gespeichert. +
Nicht aktiviert = E-Mails werden direkt an die Ziel-E-Mail-Adressen weitergeleitet. In diesem Postfach werden keine E-Mails gespeichert.

|*Passwort*; +
*Passwort wiederholen*
|Passwort eingeben und durch erneute Eingabe bestätigen. +
*_Hinweis:_* Passwort muss aus mindestens 8 Zeichen und einer Kombination aus Großbuchstaben, Kleinbuchstaben und Zahlen bestehen.

|*Tarif*
|Tarif wählen. Preise gelten zzgl. MwSt. Dein plentymarkets Vertrag wird nach dem Anlegen des Postfachs angepasst.
|====

==== Zugangsdaten für mailbox.org-Server in plentymarkets hinterlegen

Damit plentymarkets E-Mails, zum Beispiel Auftragsbestätigungen, für dich versenden kann, hinterlege im Menü <<crm/e-mails-versenden#100, System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Zugangsdaten>> die link:https://support.mailbox.org/knowledge-base/article/einrichtung-mit-sonstigen-mailprogrammen[Zugangsdaten^] zu dem mailbox.org-Postfach, über das du diese E-Mails versenden möchtest.

[#46]
==== Zusätzliche E-Mail-Adresse (Alias) für ein Postfach erstellen

Wenn ein Postfach über mehr als eine E-Mail-Adresse erreichbar sein soll, erstelle ein Alias für das Postfach. Die Anzahl der möglichen E-Mail-Adressen pro Postfach ist vom gewählten Tarif abhängig. Gehe wie unten beschrieben vor, um eine zusätzliche E-Mail-Adresse für ein Postfach zu erstellen.

[.instruction]
Zusätzliche E-Mail-Adresse für ein Postfach erstellen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Klicke auf *Mein Konto*.
. Wechsele in das Tab *E-Mail*.
. Klicke auf *Neu*. +
→ Das Fenster *Postfach erstellen* wird angezeigt.
. Wähle als E-Mail-Adresstyp *Alias*.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-e-mail-adresssen>>.
. Klicke auf *Postfach erstellen*. +
→ Die zusätzliche E-Mail-Adresse wird erstellt.

[[tabelle-e-mail-adresssen]]
.Zusätzliche E-Mail-Adresse für ein Postfach erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*E-Mail-Adresstyp*
|E-Mail-Adresstyp *Alias* wählen. +
*Postfach* = Legt ein neues E-Mail-Postfach an. +
*Alias* = Legt eine zusätzliche E-Mail-Adresse für ein bestehendes Postfach an. Die Auswahl des Postfachs erfolgt über die Option *Zielpostfach*.

|*E-Mail-Adresse*
|E-Mail-Adresse eingeben, die dem Postfach zugeordnet werden soll: Lokalen Teil der E-Mail-Adresse vor dem @ eingeben. Den Domain-Teil aus der Dropdown-Liste wählen. +
*_Hinweis:_* Nach dem Löschen einer E-Mail-Adresse ist diese Adresse 48 Stunden gesperrt. Erst nach Ablauf dieser Frist kann diese E-Mail-Adresse erneut vergeben werden.

|*Zielpostfach*
|Das Postfach wählen, in das E-Mails an diese Alias-Adresse eingehen sollen.
|====

[#46a]
==== Grundtarif ändern

Standardmäßig gilt für das Hosting von Postfächern bei mailbox.org über plentymarkets der mailbox.org-Grundtarif *Business Reseller*. Dieser Grundtarif ist für dich kostenlos, umfasst jedoch keinen Support von mailbox.org. Den Grundtarif kannst du jederzeit anpassen. Wenn du Support von mailbox.org wünschst oder den Leistungsumfang erweitern möchtest, passe deinen Grundtarif an. Der gewählte Grundtarif gilt für alle Postfächer deines gesamten plentymarkets Systems inklusive aller Mandaten.

[.instruction]
Grundtarif ändern:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Klicke auf *Mein Konto*.
. Wechsele in das Tab *E-Mail*.
. Klicke auf *Grundtarif ändern*. +
→ Das Fenster *Grundtarif wählen* wird angezeigt.
. Prüfe den Leistungsumfang der angebotenen Grundtarife.
. Wähle den gewünschten Grundtarif.
. Klicke auf *Grundtarif ändern*. +
→ Der Tarif wird übernommen und dein plentymarkets Vertrag wird angepasst. Du erhältst außerdem eine E-Mail mit weiteren Informationen von mailbox.org.

[#47]
==== Postfach löschen

Gehe wie unten beschrieben vor, um ein Postfach zu löschen. Du benötigst Admin-Rechte, um Postfächer/Alias zu löschen. Nach dem Löschen eines Postfachs/Alias kannst du erst nach 48 Stunden wieder ein neues Postfach/Alias mit der gelöschten E-Mail-Adresse anlegen.

[WARNING]
.E-Mails nach dem Löschen des Postfachs nicht mehr zugänglich
====
Nach dem Löschen eines Postfachs kannst du über mailbox.org nicht mehr auf die in diesem Postfach gespeicherten E-Mails zugreifen. Stelle sicher, dass von allen benötigten E-Mails eine lokale Kopie vorhanden ist.
====

[.instruction]
Postfach löschen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Klicke auf *Mein Konto*.
. Wechsele in das Tab *E-Mail*. +
→ Eine Liste der Postfächer wird angezeigt.
. Klicke in der Liste auf das Postfach, das du löschen möchtest.
. Klicke auf *Löschen* (icon:minus-square[role="red"]). +
→ Das Postfach und alle damit verbundenen Alias werden bei mailbox.org gelöscht. +
→ Dein plentymarkets Vertrag wird angepasst.

[#50]
=== Weitere Benutzereinstellungen

Im Bearbeitungsfenster eines Benutzerkontos findest du neben den bereits erwähnten noch weitere Tabs. Diese Tabs und ihre Einstellungsmöglichkeiten sind in anderen Themenbereichen erklärt. Zu den Erklärungen gelangst du über die Links in der rechten Tabellenspalte.

.Weitere Tabs im Bearbeitungsfenster eines Benutzerkontos
[cols="1,3"]
|====
|Tab |Erläuterung

|*Grußformel*
|In diesem Tab gibst du einen Text ein, der deinen Nachrichten und Kommentaren im Ticketsystem automatisch als <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#10, Grußformel>> angefügt wird.

|*Signatur*
|In diesem Tab gibst du einen Text ein, der deinen Nachrichten und Kommentaren im Ticketsystem automatisch als <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#20, Signatur>> angefügt wird.

|*Berechtigung*
|Dieses Tab wird im Kapitel <<basics/admin-aufgaben/benutzer-verwalten#90, Berechtigungen zuordnen>> detailliert beschrieben.

|*Persönliche Einstellungen*
|Hier nimmst du Einstellungen vor, die nur für das im System angemeldete Benutzerkonto gelten. Deshalb ist das Tab für dich auch nur in deinem eigenen Benutzerkonto sichtbar. Das Tab unterteilt sich in die Tabs <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#40, Allgemein>>, <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#50, Shortcuts>> und <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#60, Favoriten>>, die nur dich persönlich betreffen.

|*Kalender*
|Hier werden Einstellungen für den <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#600, Kalender>> vorgenommen.
|====

[#85]
== Mehrere Benutzerkonten bearbeiten

Mehrere Benutzerkonten bearbeitest du per *Gruppenfunktion* im Menü *Benutzer*. Bei der Gruppenfunktion werden zuvor gewählte Benutzerkonten bearbeitet.

[.instruction]
Gruppenfunktion ausführen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Benutzerkonten*.
. Wähle die zu bearbeitenden Benutzer.
. Klicke auf *Gruppenfunktion*. +
→ Das Fenster *Gruppenfunktion* wird geöffnet.
. Nimm die Einstellungen vor. Beachte die Erläuterungen in <<tabelle-gruppenfunktion>>.
. Klicke auf *Anwenden*. +
→ Die Benutzerkonten werden geändert.

[[tabelle-gruppenfunktion]]
.Benutzerkonten per *Gruppenfunktion* bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Löschen*
|Aktivieren, um gewählte Benutzerkonten zu löschen.

|*E-Mail senden*
|Aktivieren, um E-Mail an die gewählten Benutzerkonten zu senden. Das E-Mail-Programm wird geöffnet. Die Benutzerkonten sind als Empfänger eingetragen.

|*Skype*
|Aktivieren und *Sofortnachricht*, *Anruf* oder *Video-Anruf* wählen, um die Personen mit diesen Benutzerkonten über Skype zu kontaktieren.

|*Rollen*
|Aktivieren und eine, mehrere oder *ALLE* Rollen aktivieren, um die gewählten Benutzer mit diesen Rollen zu verknüpfen.
|====

[#100]
== Sichtbarkeiten festlegen

Im Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer* legst du fest, welche Bereiche und Einstellungen die Person mit diesem Benutzerkonto sehen kann, wenn die Person ein Menü öffnet. Bei fehlender Berechtigung ist zum Beispiel ein Lager oder sind Aufträge in einem Status für diese Person nicht sichtbar.

.Tab *Berechtigung* eines Backend-Benutzerkontos
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Vertriebslager*; +
*Reparaturlager*; +
*Vorratslager*; +
*Umschlagslager*; +
*Verteilerlager*; +
*Sonderlager* (Typ *Sonstiges*) +
|Benutzerberechtigungen für Lager erteilen. Nur erstellte <<warenwirtschaft/lager-einrichten#300, Lagertypen>> stehen zur Verfügung.

|*Sichtbare Auftragsstatus*
|Auftragsstatus festlegen, die *sichtbar* sein sollen. Die Person mit diesem Benutzerkonto sieht nur die Aufträge, die in diesen Status sind.

|*Setzbare Auftragsstatus*
|Auftragsstatus festlegen, die die Person mit diesem Benutzerkonto sehen darf.

|*Mandanten (Shops)*
|Einzelne, mehrere oder alle Mandanten (Shops) festlegen, die die Person mit diesem Benutzerkonto sehen darf. Die Person mit diesem Benutzerkonto hat nur auf die hier festgelegten Bereiche Zugriff. Wenn kein Mandant gewählt wurde, greifen auch weitere Berechtigungen nicht, da die Person mit diesem Benutzerkonto generell keinen Mandanten sieht. +
*Alle* = Die Person mit diesem Benutzerkonto hat Zugriff auf alle Mandanten. +
*Standard* = Die Person mit diesem Benutzerkonto hat Zugriff auf den Standard-Webshop.

|*Ticketstatus*
|Ticketstatus wählen, um festzulegen, welche Tickets mit welchem Status die Person mit diesem Benutzerkonto ansehen und bearbeiten darf. +
*Unsichtbar* = Die Person mit diesem Benutzerkonto sieht kein Ticket, das in diesem Status ist. +
*Sichtbar* = Die Person mit diesem Benutzerkonto sieht jedes Ticket, das in diesem Status ist. +
*Nur eigene* = Die Person mit diesem Benutzerkonto sieht nur Tickets, die in diesem Status sind und von denen sie Eigner ist. +
In der Ticketübersicht werden alle Tickets aufgeführt, also auch für das Benutzerkonto unsichtbare Tickets. Die Person mit diesem Benutzerkonto kann unsichtbare Tickets jedoch nicht öffnen.
|====

[#105]
== Rechte verwalten
Mithilfe von Rechten legst du fest, welche Bereiche und Einstellungen Personen mit einem Benutzerkonto in plentymarkets sehen und was die Person bearbeiten kann. Du kannst Rechte für jedes Benutzerkonto einzeln festlegen oder mithilfe von Rollen für mehrere Benutzerkonten.
Im Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer* können Rechte für einzelne Benutzer vergeben werden. Dies beinhaltet die REST-API-Berechtigungen, die Menü-Sichtbarkeiten und die Plugin-Menü-Sichtbarkeiten.
Ebenso können Rechte für Rollen vergeben werden. Ausgeschlossen davon sind die Plugin-Menü-Sichtbarkeiten. Vergibt man eine Rolle an einen Benutzer und hat man an diesen bereits weitere Rechte vergeben, sind alle dort enthaltenen Rechte wirksam.
Im Menüpunkt *Ressourcen* können die Auftragsherkünfte freigegeben werden, die für den Benutzer sichtbar sein sollen. +
Ordne einem Benutzerkonto nur die Rechte zu, die die Person für ihren Aufgabenbereich benötigt. Diese Einschränkung erhöht die Sicherheit und beugt Fehlern in deinem System vor.

[#110]
=== Rechte vergeben

Die Benutzerrechte im Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer* gliedern sich in die 3 folgend aufgeführten Bereiche.

[[tabelle-benutzerrechte]]
.Benutzerrechte
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Berechtigungen*
|REST-Rechte, die für bestimmte Aktionen benötigt werden.

|*Menü-Sichtbarkeiten*
|Abbildung von Menü und Systemeinstellungen. Dort können die für den Benutzer sichtbaren Bereiche gewählt werden. Die REST-Rechte für die Menüpunkte werden automatisch gesetzt.

|*Plugins*
|Hier wird die Menü-Sichtbarkeit für Plugins freigegeben. Zunächst werden nur die Plugins mit ihren einzelnen Einträgen, jedoch ohne die korrekte Route, angezeigt.
|====

include::./_textblocks/instructions/rechte-vergeben.adoc[]

[TIP]
Die Bereiche *Berechtigungen* und *Menü-Sichtbarkeiten* sind verknüpft, wodurch die gewählten Rechte für den jeweils anderen Bereich automatisch mit aktiviert werden.

[NOTE]
Sollten weitere Berechtigungen benötigt werden, erscheint eine Fehlermeldung. Beispiel: Der Menüpunkt *Blog* benötigt die Berechtigungen für “Blog anzeigen” und “Tag anzeigen”.

[#115]
=== Rechte für Rollen vergeben

Rollen kann man mehreren Benutzern zuweisen. Diese haben dann alle dieselben Rechte.
Für Rollen können lediglich Einstellungen für Berechtigungen und Menü-Sichtbarkeiten, nicht aber für Plugins vorgenommen werden.

[.instruction]
Rechte für Rollen vergeben:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Rollen*. +
→ Die Übersicht wird geöffnet.
. Wähle eine Rolle. +
→ Der Menüpunkt *Rechte* mit den Sichtbarkeiten wird geöffnet.
. Vergib die Rechte für Rollen in dem jeweiligen Bereich durch Anklicken der Checkboxen. Aktiviere komplette Bereiche oder klappe Bereiche auf, um einzelne Berechtigungen zu aktivieren, die dem Benutzerkonto zur Verfügung stehen sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#120]
=== Menü- und REST-API-Rechte verwalten

Im Tab *Berechtigung* legst du fest, welche Berechtigungen ein Benutzerkonto des Zugangs *Backend* für die REST-API erhält. In der Standardeinstellung sind keine REST-API-Berechtigungen vergeben. Benutzerkonten des Zugangs *Admin* verfügen über alle Berechtigungen.

[.instruction]
Menü- und REST-API-Rechte verwalten:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Öffne einen Benutzer.
. Öffne das Tab *Berechtigungen*.
. Klicke auf *Menü- und REST-API-Rechte verwalten*. +
→ Der Menüpunkt *Rechte* wird geöffnet.
. Vergib die Rechte in dem jeweiligen Bereich durch Anklicken der Checkboxen. Aktiviere komplette Bereiche oder klappe Bereiche auf, um einzelne Berechtigungen zu aktivieren, die dem Benutzerkonto zur Verfügung stehen sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#125]
=== App-Berechtigungen aktivieren

Im Tab *Mobile* legst du fest, welche Bereiche und Kennzahlen für Benutzerkonten in der plentymarkets App sichtbar sein sollen.

[.instruction]
App-Berechtigungen aktivieren:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Öffne einen Benutzer.
. Öffne das Tab *Mobile*.
. Aktiviere Funktionen oder Kennzahlen, die dem Benutzerkonto in der App zur Verfügung stehen sollen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#145]
=== Benutzerkonto entsperren

Die maximale Anzahl der Login-Versuche beträgt 5 pro Benutzerkonto oder 25 pro IP-Adresse. Wenn die maximale Anzahl der Login-Versuche überschritten wird, wird das Konto für 24 Stunden gesperrt. Personen mit Administratorrechten können ein Benutzerkonto vor Ablauf dieser 24 Stunden manuell entsperren.

[.instruction]
Benutzerkonto entsperren:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*. +
→ Die Benutzerkonten werden angezeigt.
. Doppelklicke auf das gesperrte Benutzerkonto. +
→ Das Benutzerkonto wird geöffnet.
. Klicke auf *Login entsperren*. +
→ Das Benutzerkonto wird entsperrt.

[#70]
== Rollen erstellen

Mit Rollen gruppierst du Benutzerkonten und erteilst mehreren Benutzern die gleichen Berechtigungen, ohne jedes Benutzerkonto einzeln bearbeiten zu müssen.

[.instruction]
Neue Rolle erstellen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rollen*.
. Klicke auf *Neue Rolle*. +
→ Das Fenster *Neue Rolle* wird geöffnet.
. Gib einen *Namen* für die Rolle ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Rolle wird in einem neuen Tab zur Bearbeitung geöffnet.

Erst beim Bearbeiten der Rolle legst du die Berechtigungen fest, die Benutzerkonten mit dieser Rolle haben. Bearbeite die Rolle deshalb nach dem Erstellen.

[#80]
== Rollen bearbeiten

Nachdem du eine Rolle erstellt hast, wird sie zur Bearbeitung geöffnet und der Rollenübersicht hinzugefügt, so dass du die Rolle auch später wieder öffnen und bearbeiten kannst. Rollen werden in der Übersicht alphabetisch gelistet. Jede Rolle gliedert sich in drei Tabs. Im Tab *Einstellungen* lässt sich der Name der Rolle ändern. Im Tab *Benutzer* verknüpfst du Benutzerkonten mit der Rolle. Im Tab *Berechtigungen* ordnest du der Rolle Berechtigungen zu. Für Rollen stehen dir die gleichen Berechtigungseinstellungen wie für Benutzerkonten des Zugangs *Backend* zur Verfügung. Details zu den Berechtigungen findest du hier auf der Seite im Kapitel <<basics/admin-aufgaben/benutzer-verwalten#90, Berechtigungen zuordnen>>.

Rollen können von Benutzern des Zugangs *Admin* oder des Zugangs *Backend* erstellt werden. Benutzerkonten des Zugangs *Backend* benötigen dafür die Berechtigungen.

[.instruction]
Benutzerkonten mit einer Rolle verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rollen*.
. Öffne eine Rolle.
. Öffne das Tab *Benutzer*.
. Wähle Benutzerkonten unter *Verfügbare Benutzer*.
. Klicke auf den *Pfeil nach rechts*, um Benutzerkonten in die Spalte *Zugeordnete Benutzer* zu übertragen. +
*_Oder:_* Ziehe ein Benutzerkonto per Drag &amp; Drop in die Spalte *Zugeordnete Benutzer*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Mehrere Benutzerkonten gleichzeitig verschieben
====
Mit *Strg* oder *cmd* und linker Maustaste markierst du mehrere Benutzer, um diese dann zusammen zu verschieben. Mit den unteren Pfeil-Schaltflächen bewegst du alle Benutzer.
====

Den Benutzerkonten unter *Zugeordnete Benutzer* wird die betreffende Rolle zugeordnet. Diese Zuordnung wird auch automatisch im Benutzerkonto im Tab *Stammdaten* unter *Rollen* eingestellt. Die Zuordnung kann an beiden Stellen im System angepasst werden.

[.instruction]
Rollen mit einem Benutzerkonto verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Öffne ein Benutzerkonto.
. Wähle eine, mehrere oder alle Rollen unter *Rollen*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Verknüpfung von Benutzerrollen mit Benutzern des Zugangs Admin
====
Für Administratoren gelten alle Berechtigungen. Trotzdem ist es für einige Vorgänge wichtig, dass Administratoren auch Rollen zugeordnet werden. So erhalten Administratoren zum Beispiel rollenbezogene E-Mails nur, wenn die Administratoren mit der betreffenden Rolle verknüpft wurden.
====

[.subhead]
Anwendungsbeispiel

Der Administrator der Firma MeinShop erstellt verschiedene Rollen. Die Rolle Mitarbeiter ist für alle Benutzerkonten gedacht und enthält sämtliche Berechtigungen, die jedem Benutzerkonten zugeordnet werden. Die individuelle Zuordnung dieser Berechtigungen entfällt. Auch Änderungen an den Berechtigungen, die alle Benutzerkonten betreffen, werden zentral in dieser Rolle vorgenommen. Zusätzlich zur Rolle Mitarbeiter erstellt der Administrator die spezifischen Rollen Lagerist und Buchhaltung mit weiteren Berechtigungen, die nur eine kleine Benutzergruppe benötigt.

.Beispiel für Rollen
[cols="1,3,3"]
|====
|Rolle |Berechtigungen |Menü-Sichtbarkeiten

|*Mitarbeiter*
|Mandanten (Shops) » Standard
|Start » Webmail +
Start » Forum

|*Lagerist*
|Lager
|System » Systemeinstellungen » Waren » Lager +
Waren +
Aufträge » Fulfillment

|*Buchhaltung*
|
|Start » Urlaubsverwaltung +
System » Systemeinstellungen » Mandant » Mandant wählen » Buchhaltung
|====

Herr Mustermann ist Logistiker bei MeinShop und erhält die Benutzerrollen Mitarbeiter und Lagerist. Wenn einem Benutzerkonto mehrere Rollen zugeordnet werden, addieren sich die Berechtigungen. Herr Mustermann erhält also die Berechtigungen *Mandanten (Shops)*, *Webmail* und *Forum* der Rolle Mitarbeiter sowie die Berechtigungen *Lager*, *Waren* und *Fulfillment* der Rolle Lagerist. Er verfügt aber nicht über die Berechtigungen *Urlaubsverwaltung* und *Buchhaltung*, da ihm die Rolle Buchhaltung nicht zugeordnet wurde.

== Rollen kopieren

Wenn du eine weitere Rolle benötigst, die sich von einer bestehenden Rolle nur minimal unterscheidet, dann kopiere die bestehende Rolle und nimm an der Kopie die Änderungen im Tab *Berechtigungen* vor.

[.instruction]
Rolle kopieren:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rollen*.
. Wähle eine Rolle.
. Klicke in der Symbolleiste auf *Kopieren*. +
→ Das Fenster *Rolle kopieren* wird geöffnet.
. Gib einen Namen ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Rolle wird kopiert und geöffnet.

== E-Mail an alle Benutzerkonten einer Rolle senden

Rollen ermöglichen es dir, E-Mails an alle Benutzerkonten zu senden, die über diese Rolle verfügen und eine E-Mail-Adresse in ihrem Benutzerkonto eingegeben haben.

[.instruction]
E-Mail an alle Benutzerkonten einer Rolle senden:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rollen*.
. Wähle eine Rolle.
. Klicke in der Symbolleiste auf *E-Mail senden*. +
→ Das E-Mail-Programm wird geöffnet. Die Benutzerkonten dieser Rolle sind als Empfänger eingetragen.

[#60]
== Benutzerkonto suchen

Filter helfen dir bei der Suche nach Benutzerkonten. Mit dem Filter *Zugang*, zeige beispielsweise nur Benutzerkonten des Zugangs *Backend* an. Ohne Filter werden in der Übersicht alle Benutzerkonten angezeigt. Folgende Elemente und Funktionen sind im Menü *Benutzer* verfügbar.

.Filteroptionen für Benutzer
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Suchen*
|Suche ausführen. Zuvor Filteroptionen zur Suche eingeben oder wählen.

|*Reset*
|Filtereinstellungen auf Standardwerte zurücksetzen.

|*ID*
|ID eingeben, um gezielt nach einem Benutzerkonto mit dieser ID zu suchen.

|*Name*
|Name eingeben, um gezielt nach Benutzerkonten mit diesem Namen zu suchen.

|*Zugang*
|Zugang wählen, um gezielt nach Benutzerkonten mit diesem Zugang zu suchen.

|*Rollen*
|Eine, mehrere oder alle Rollen wählen, um gezielt nach Benutzerkonten mit diesen Rollen zu suchen.
|====

[#150]
== Rollen und Prozesse verknüpfen

Verwende Rollen zum Beispiel auch bei <<automatisierung/prozesse/prozesse-einrichten#, Prozessen>>.

[.instruction]
Rollen und Prozesse verknüpfen:

. Öffne das Menü *System » Systemeinstellungen » Prozesse » Pro Rolle*.
. Klicke in der Zeile einer *Rolle* auf den *Pfeil* und dann auf *Neuer Prozess* (Bild 1).
. Gib einen *Namen* für die Rolle ein.
. Wähle für die *Sichtbarkeit* die Einstellung *Rolle*. +
→ Die Option *Rolle* wird eingeblendet.
. Wähle eine *Rolle* aus der Dropdown-Liste.
. Wähle, ob die Einstellungen durch einen Eigner mit dieser Rolle *änderbar* sein sollen.
. Wähle das *Lager* für den Prozess und eine *Farbe*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Die Prozesse werden für die gewählte Rolle angezeigt. Aufgrund der Sichtbarkeit sieht nur ein Benutzerkonto mit passender Rolle den Prozess.

== Konto für das plentymarkets Forum erstellen

Das plentymarkets Forum ist eine ständig wachsende Wissensdatenbank, die viele Antworten auf bereits gestellte Support-Fragen enthält. Im Forum helfen dir unsere Entwickler und andere plentymarkets Kunden bei technischen Fragen gern weiter. Außerdem findest du dort Tipps für das Arbeiten mit plentymarkets und du tauschst dich mit anderen plentymarkets Kunden aus. Gehe wie unten beschrieben vor, um ein Konto für das plentymarkets Forum zu erstellen. Benutzerkonten des Zugangs *Admin* erstellen so auch Forumkonten für andere Benutzerkonten.

[.instruction]
Konto für plentymarkets Forum erstellen:

. Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*.
. Klicke auf *Benutzer öffnen*. +
→ Das Benutzerkonto wird in einem neuen Tab geöffnet.
. Klicke im Bereich *plentymarkets Forum* auf *Konto erstellen* +
→ Das Forenkonto wird erstellt.

[#160]
== Anzahl eingeloggter Benutzerkonten verwalten

Abhängig von deinem plentymarkets Tarif ist die Anzahl der Benutzerkonten, die gleichzeitig in plentymarkets eingeloggt sein dürfen, möglicherweise beschränkt. Dieses Limit gilt für das plentymarkets Backend, die REST-API und die plentymarkets App.

Das kannst du tun, wenn du das Benutzerlimit erreichst:

* Eingeloggte Personen auffordern, sich manuell auszuloggen
* <<#170, Benutzerkonten über die Session-Verwaltung ausloggen>>
* <<#190, Benutzerlimit deines plentymarkets Vertrags erhöhen>>


[#170]
=== Benutzerkonten über Session-Verwaltung ausloggen

Gehe wie unten beschrieben vor, um Benutzerkonten über die Session-Verwaltung auszuloggen.

[NOTE]
.Admin-Rechte erforderlich
====
Du benötigst Admin-Rechte, um Benutzerkonten über die Session-Verwaltung auszuloggen.
====

[.instruction]
Benutzerkonten über Session-Verwaltung ausloggen:

. Zeige mit der Maus auf das User-Icon oben rechts.
. Klicke auf *Session-Verwaltung*. +
*_Oder:_* Öffne das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Session-Verwaltung*. +
→ Das Menü *Session-Verwaltung* wird geöffnet. +
→ Die eingeloggten Benutzerkonten werden angezeigt.
. Aktiviere die Kontrollkästchen der Benutzerkonten, deren Session du beenden möchtest, um sie auszuloggen.
. Klicke auf *Ausgewählte Sessions beenden*. +
→ Die gewählten Benutzerkonten werden ausgeloggt.

[#180]
=== Benutzerkonten ausloggen, wenn Benutzerlimit überschritten ist

Wenn die zulässige Anzahl gleichzeitig eingeloggter Benutzerkonten bereits erreicht oder überschritten ist, können nicht eingeloggte Admin-Benutzer die Session-Verwaltung über einen Link in der eingeblendeten Fehlermeldung erreichen.

[.instruction]
Benutzerkonten ausloggen, wenn Benutzerlimit überschritten ist:

. Logge dich in das plentymarkets Backend ein. +
→ Eine Fehlermeldung wird angezeigt.
. Klicke auf den Link in der Fehlermeldung. +
→ Das Menü *Session-Verwaltung* wird geöffnet. +
→ Die eingeloggten Benutzerkonten werden angezeigt.
. Aktiviere die Kontrollkästchen der Benutzerkonten, deren Session du beenden möchtest, um sie auszuloggen.
. Klicke auf *Ausgewählte Sessions beenden*. +
→ Die gewählten Benutzerkonten werden ausgeloggt. +
*_Hinweis:_* Der Login über die Fehlermeldung ist 10 Minuten gültig. Danach wirst du automatisch ausgeloggt.

[#190]
=== Weitere Benutzerlizenzen buchen

Weitere Benutzerlizenzen buchst du über den plentymarkets Konfigurator.

[.instruction]
Weitere Benutzerlizenzen buchen:

. Öffne das Menü *Start » Service-Center*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Das Service-Center wird in einem neuen Browser-Tab geöffnet.
. Klicke auf das blaue *Plus* des Systems. +
→ Die verfügbaren Tabs werden eingeblendet.
. Wechsele in das Tab *Vertrag*.
. Klicke auf eine der Schaltflächen *Tarif wechseln*. +
→ Der plentymarkets Konfigurator wird geöffnet.
. Klicke in der Fortschrittsleiste unterhalb des Konfigurators auf die Ansicht *Ausstattung*.
. Scrolle zum Bereich *Benutzerlizenzen (CUL)*.
. Klicke unter *Weitere Benutzerlizenzen (CUL)* auf das Plussymbol, um weitere Benutzerlizenzen hinzuzufügen.
. Klicke in der Fortschrittsleiste unterhalb des Konfigurators auf die Ansicht *Ihr System*. +
→ Eine Zusammenfassung der neuen Vertragsdaten wird angezeigt.
. Prüfe die Informationen sorgfältig.
. Klicke auf *Systemänderung bestellen*. +
→ Die Systemänderung wird durchgeführt.
