= Benutzerkonten verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Eigner, Benutzer, Benutzerkonten, Benutzerkonto, Rollen, Berechtigungen, Rechte
:description: Arbeiten mit plentymarkets: Verwalten Sie Benutzerkonten, legen Sie neue Benutzerkonten an und bearbeiten Sie bestehende Benutzerkonten im plentymarkets System.
:position: 30

In der Benutzerverwaltung erstellen Sie neue Benutzerkonten und bearbeiten bestehende Benutzerkonten. Darüber hinaus verknüpfen Sie Benutzerkonten mit Rollen und Klassen.

* Mit Rollen gruppieren Sie Benutzerkonten und vereinfachen die Zuordnung gleicher Berechtigungen zu mehreren Benutzerkonten.
* Mit Klassen verteilen Sie Berechtigungen an Benutzerkonten und Schnittstellen. Einem Benutzerkonto der Klasse API zum Beispiel weisen Sie individuell API-Calls zu.

In jedem plentymarkets System sind kostenfrei fünf CUL-Benutzerlizenzen enthalten. Weitere Benutzerkonten buchen Sie im link:http://www.plentymarkets.eu/preise/[Konfigurator] hinzu.

[NOTE]
.Was ist eine CUL-Benutzerlizenz?
====
CUL steht für Concurrent-User-Lizenzmodell. Über die Lizenz wird festgelegt, wie viele Benutzerkonten gleichzeitig auf das plentymarkets Backend, die REST-API und die plentymarkets App zugreifen dürfen. Wir limitieren also nur die gleichzeitige Nutzung und nicht die Anzahl der Benutzerkonten, die Sie erstellen können.
====

[#35]
== Passwortsicherheit einstellen

Im Menü *System » Einstellungen » Benutzer » Sicherheit* stellen Sie die Anforderungen ein, die Benutzer erfüllen müssen, wenn sie ein neues Passwort vergeben. Um die Anforderungen zu aktivieren, verfahren Sie wie im Folgenden beschrieben.

[.instruction]
Passwortsicherheit einstellen:

. Öffnen Sie das Menü *System » Einstellungen » Benutzer » Sicherheit*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-sicherheit-einstellen>>.
. *Speichern* Sie die Einstellungen. +
→ Jedes neu eingegebene Passwort wird ab jetzt auf die Erfüllung der eingestellten Anforderungen geprüft.

[[tabelle-sicherheit-einstellen]]
.Passwortsicherheit einstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Passwortsicherheit aktivieren*
|Wird diese Option aktiviert, muss jedes neu eingegebene Passwort die eingestellten Anforderungen erfüllen.

|*Mindestlänge*
|Mindestanzahl an Zeichen für neue Passwörter eingeben. +
*_Hinweis:_* Aus Sicherheitsgründen muss die Mindestlänge 8 oder mehr Zeichen betragen.

|*Passwortkriterien*
|Kriterien aktivieren, die für neue Passwörter gelten sollen. +
*_Hinweis:_* Aus Sicherheitsgründen müssen mindestens 3 Kriterien aktiviert sein.

|*Mindestanzahl erfüllter Kriterien*
|Anzahl der Kriterien einstellen, die neue Passwörter mindestens erfüllen müssen. +
*_Hinweis:_* Aus Sicherheitsgründen müssen mindestens 3 Kriterien aktiviert sein.

|*Anzahl zuletzt benutzter Passwörter*
|Anzahl der zuletzt benutzten Passwörter einstellen, die nicht erneut verwendet werden dürfen. Der Nutzer wird darauf hingewiesen, wenn er versucht, eines der zuletzt benutzten Passwörter erneut einzugeben. Wenn diese Funktion nicht gewünscht ist, 0 eintragen oder leer lassen. +
*_Hinweis:_* Die Anzahl der zu speichernden Passwörter muss 20 oder weniger betragen.

|*Gültigkeitszeitraum des Passworts*
|Nach Ablauf des Gültigkeitszeitraums in Tagen wird das Benutzerkonto gesperrt. Wenn diese Funktion nicht gewünscht ist, 0 eintragen oder leer lassen.
|====

[#10]
== Benutzerkonto erstellen

Bei der Erstverwendung Ihres Systems ist bereits ein Standardbenutzerkonto der Klasse **Admin**, also ein Konto mit Administratorrechten, vorhanden. Sie benötigen mindestens ein Admin-Benutzerkonto. Erstellen Sie deshalb entweder ein neues Benutzerkonto der Klasse **Admin** und löschen Sie danach das Standardbenutzerkonto oder bearbeiten Sie das vorhandene Benutzerkonto. Im Folgenden wird beschrieben, wie Sie ein Benutzerkonto einer beliebigen Klasse erstellen.

[.instruction]
Benutzerkonto erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Klicken Sie auf **Neu**. +
→ Das Fenster **Neuen Benutzer anlegen** wird geöffnet.
. Geben Sie den **Benutzernamen** ein.
. Geben Sie den **realen Namen** ein.
. Geben Sie das **Passwort** ein.
. Wiederholen Sie das Passwort.
. Geben Sie die E-Mail-Adresse der Person ein, damit sie Benachrichtigungen des Systems empfängt.
. Wählen Sie eine **Benutzerklasse**. Beachten Sie dazu die Erläuterungen in <<tabelle-benutzerklassen>>.
. **Speichern** Sie die Einstellungen.

Der Benutzername darf kein Leerzeichen enthalten und muss mindestens 5 Zeichen lang sein.

Mit einen Klick auf **Mein Konto** gelangen Sie direkt in Ihr Benutzerkonto.

Die Benutzerklassen sind vorgegeben und die Einstellungen der Klassen sind nicht änderbar. Welche Berechtigungen bei Klassen voreingestellt sind und welche Sie noch individuell am Benutzerkonto einstellen können, finden Sie in dieser Tabelle:

[[tabelle-benutzerklassen]]
.Übersicht der verfügbaren Benutzerklassen
[cols="1,3"]
|====
|Klasse |Erläuterung

|**Admin**
|Klasse, die über alle Berechtigungen ohne Einschränkung verfügt und mindestens einem Benutzerkonto zugeordnet werden muss, da nur ein Admin weitere Benutzerkonto uneingeschränkt erstellen, verwalten und bearbeiten kann. Bei Verwendung mehrerer Admin-Konten sind diese gleichberechtigt.

|**Variabel**
|Klasse, für die im Benutzerkonto unter **Tab: Berechtigung** <<basics/admin-aufgaben/benutzer-verwalten#100, Bereiche>> und <<basics/admin-aufgaben/benutzer-verwalten#110, Funktionen>> freigeschaltet werden.

|**Callcenter**
a|Klasse mit Berechtigungen für folgende Bereiche:

* Startseite
* Kalender
* Ticketsystem (Tickets öffnen, eBay-Nachrichten synchronisieren)
* Aufträge suchen und bearbeiten
* Neue Aufträge erstellen
* Kunden bearbeiten +

*_Hinweis_*: Diese Klasse existiert nicht mehr und wurde zum variablen Nutzer migriert.

|**API**
|Klasse, für die im Benutzerkonto <<basics/admin-aufgaben/benutzer-verwalten#120, API-Calls>> freigeschaltet werden. Die API-Calls werden dann einzeln aktiviert. Es werden dem Benutzerkonto also nicht pauschal alle API-Calls freigeschaltet. +

*Achtung*: Nutzern mit dieser Benutzerklasse wird der Zugriff auf das Backend verweigert.

|**Logistik**
a|Klasse mit Berechtigungen für folgende Bereiche:

* Startseite
* Kalender
* Warenbestände suchen und bearbeiten
* Wareneingänge suchen und bearbeiten
* Warenberechnung
* Datenimport und -export
* Lagerort-Verwaltung
* Aufträge suchen und bearbeiten
* Fulfillment +

*_Hinweis_*: Diese Klasse existiert nicht mehr und wurde zum variablen Nutzer migriert.

|**Blog**
a|Klasse mit Berechtigungen für folgende Bereiche:

* Startseite
* Kalender
* Blog +

*_Hinweis_*: Diese Klasse existiert nicht mehr und wurde zum variablen Nutzer migriert.

|**Newsletter2Go**
|Klasse, die automatisch für die Einrichtung einer <<crm/newsletter-versenden#2100, Newsletter2Go>>-Schnittstelle verwendet wird. +

*_Hinweis_*: Diese Klasse existiert nicht mehr und wurde zum variablen Nutzer migriert.
|====

[#20]
== Benutzerkonto bearbeiten

Nachdem ein Benutzerkonto erstellt wurde, wird das Konto in der Benutzerkontoübersicht hinzugefügt. Benutzerkonten werden dort alphabetisch aufgelistet. Wählen Sie ein Benutzerkonto aus, um Einstellungen an dessen Konto vorzunehmen. Die Anzahl der Einstellungen hängt zum einen von Ihrer Benutzerklasse und zum anderen von der Benutzerklasse des zu bearbeitenden Benutzerkontos ab. Mehrere Benutzerkonten gleichzeitig bearbeiten Sie per *Gruppenfunktion*.

[.instruction]
Benutzerkonto bearbeiten:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Klicken Sie auf **Benutzer öffnen**. +
→ Das Benutzerkonto wird in einem neuen Tab geöffnet.
. Nehmen Sie Änderungen und Einstellungen gemäß <<tabelle-stammdaten>> vor.
. **Speichern** Sie die Einstellungen.

[TIP]
.Passwort ist gespeichert
====
Das beim Erstellen des Benutzerkontos eingegebene Passwort ist im Bearbeitungsmodus nicht sichtbar, ist aber gespeichert. Sie müssen es beim Bearbeiten des Benutzerkontos nicht erneut eingeben.
====

[#30]
=== Stammdaten pflegen

Im Tab **Stammdaten** nehmen Sie Änderungen und Einstellungen an den Benutzerdaten eines Kontos vor. **Benutzername**, **IP-Beschränkung**, **Benutzerklasse** und **Rollen** können nur von Personen mit Administratorrechten geändert werden. Alle anderen Stammdaten können Personen auch in ihrem eigenen Konto anpassen. Zudem ist das Sperren eines Benutzerkontos in diesem Tab möglich.

[[tabelle-stammdaten]]
.Stammdaten eines Benutzerkontos
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Titelzeile**
|In der Titelzeile werden **Benutzer-ID**, **Benutzername** sowie **Datum** und **Uhrzeit der letzten Änderung** an dem Benutzerkonto angezeigt. +
Die Benutzer-ID ist eine eindeutige Identifikationsnummer, die vom System vergeben wird und nicht änderbar ist.

|*Benutzer gesperrt*
|Aktivieren, um das Benutzerkonto zu sperren. Gesperrte Personen können sich nicht mehr in das System einloggen.

|**Benutzername**
|Name ohne Leerzeichen eingeben. Der Name ist ein Pflichteintrag, der für den Login benötigt wird. Der Benutzername darf kein Leerzeichen enthalten und muss mindestens 5 Zeichen lang sein.

|**Realer Name**
|Realer Name des Benutzers, der in der Kopfzeile des plentymarkets Administrationsbereichs angezeigt wird.

|**E-Mail**
|E-Mail-Adresse des Benutzerkontos eingeben. Diese ist u.a. für Benachrichtigungen des Systems, Benachrichtigungen aus Ereignisaktionen und auch für die Gruppenkommunikation innerhalb des Systems wichtig.

|**Google Mail**
|Bei Verwendung von Gmail, hier die Gmail-Adresse des Benutzerkontos eingeben.

|**Skype-Name**
|Bei Verwendung von Skype, hier den Skypenamen des Benutzerkontos eingeben.

|**Farbe**
|Im Bearbeitungsfenster eine Farbe durch Verschieben der Farbauswahl festlegen, einen Hexadezimalwert oder RGB-Werte eingeben. Die Farbe erleichtert die Identifikation des Benutzerkontos in anderen Bereichen, zum Beispiel im <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#600, Kalender>>.

|**Zeitzone**
|Zeitzone des Benutzerkontos wählen.

|**Bild-URL**
|Bild-URL eingeben, um zum Beispiel einen Platzhalter für ein Foto für Blogbeiträge zu hinterlegen.

|**UI-Sprache**
|Sprache für den Admin-Bereich. Diese Sprache wird als Standard beim Login verwendet.

|**IP-Beschränkung**
|IP-Adresse des Rechners der Person des Benutzerkontos eingeben, damit sich die Person mit diesem Benutzerkonto nur über diese IP-Adresse in das plentymarkets System einloggt.

|**Benutzerklasse**
|Benutzerklasse des Benutzerkontos wählen. Es stehen die Klassen **Admin**, **Variabel** und **API** zur Verfügung.

|**Rollen**
|Rollen des Benutzerkontos wählen. Damit Rollen zur Auswahl stehen, müssen zuvor <<basics/admin-aufgaben/benutzer-verwalten#70, Rollen>> erstellt werden.

|**Neues Passwort**
|Neues Passwort eingeben, um dem Benutzerkonto ein neues Passwort zu erteilen.

|**Passwort wiederholen**
|Passwort noch einmal eingeben.

|*Neue App-PIN*
|Für Personal, das mit der plentymarkets App arbeitet, optional PIN mit 4 bis 12 Ziffern eingeben. Wenn eine PIN gespeichert ist, ist ein schneller Kontowechsel in der plentymarkets App möglich. Personal kann sich aber auch mit dem Passwort in die plentymarkets App einloggen. +
*_Tipp:_* Nachdem die PIN gespeichert wurde, werden in diesem Feld 4 Punkte angezeigt. Diese Punkte dienen dazu, sichtbar zu machen, dass für das Benutzerkonto eine App-PIN gespeichert ist, und stimmen nicht unbedingt mit der Länge der gespeicherten PIN überein. +
Beim schnellen Benutzerwechsel werden alle Benutzerkonten angezeigt, für die eine PIN gespeichert ist. Um die PIN zu entfernen, zum Beispiel, weil die Person nicht mehr mit der App arbeitet, die 4 Punkte löschen und das Konto erneut speichern. +
*_Hinweis:_* Wenn ein Benutzerkonto mit PIN in der Liste der

|*App-PIN wiederholen*
|PIN noch einmal eingeben.
|====

[#40]
=== Eigner aktivieren

Sie legen im Tab **Eigner** fest, in welchen Bereichen das Benutzerkonto als Eigner verfügbar sein soll. Wenn Sie zum Beispiel einen Kalender erstellen, müssen Sie für den Kalender Eigner einrichten. Aktivieren Sie den Bereich **Kalender** im Tab **Eigner**.

[.instruction]
Benutzer als Eigner aktivieren:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Öffnen Sie einen Benutzer.
. Öffnen Sie das Tab **Eigner**.
. Aktivieren Sie die Bereiche, in denen das Benutzerkonto als Eigner verfügbar sein soll.
. **Speichern** Sie die Einstellungen.

// ACHTUNG!!!! Aus der GUI wird auf die Kapitel zu E-Mail-Postfächern verlinkt. Falls diese Inhalte verschoben werden, bitte Ziyad oder einem anderen Mitglied des Cloud-Teams Bescheid sagen, damit der Link angepasst wird. Danke.

[#42]
=== E-Mail-Postfächer verwalten

Wenn Sie Ihre Domains von plentymarkets verwalten lassen, können Sie als Person mit Admin-Rechten im Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten » Tab: E-Mail** E-Mail-Postfächer für Systembenutzer erstellen und verwalten. Diese E-Mail-Postfächer werden bei einem Drittanbieter, dem externen E-Mail-Provider link:https://mailbox.org/business/[mailbox.org^], angelegt und von diesem Drittanbieter gehostet. Nachfolgend wird beschrieben, wie Sie E-Mail-Postfächer und zusätzliche E-Mail-Adressen pro Postfach (Alias) erstellen.

[IMPORTANT]
.E-Mail-Postfächer anderer Provider
====
Die hier beschriebene Einrichtung gilt nur für plentymarkets Kunden, die ihre Domains von plentymarkets verwalten lassen und die den externen Dienstleister link:https://mailbox.org/business/[mailbox.org^] nutzen möchten. Wenn Sie Ihre E-Mail-Konten über einen anderen Provider verwalten und darüber E-Mails durch Ihr plentymarkets System versenden möchten, ist diese Einrichtung nicht erforderlich. Beachten Sie aber auch dann das Kapitel <<crm/e-mails-versenden#100, E-Mail-Server-Zugangsdaten speichern>> auf der Handbuchseite <<crm/e-mails-versenden#, E-Mails versenden>>.
====

[#44]
==== Postfach erstellen

Legen Sie für Benutzer, die ein eigenes Postfach bei mailbox.org erhalten sollen, wie unten beschrieben ein Postfach an. Sie benötigen Admin-Rechte, um Postfächer und Alias anzulegen.

[.instruction]
Neues Postfach erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Klicken Sie auf **Mein Konto**.
. Wechseln Sie in das Tab **E-Mail**.
. Klicken Sie auf **Neu**. +
→ Das Fenster **Postfach erstellen** wird angezeigt.
. Wählen Sie als E-Mail-Adresstyp **Postfach**.
. Nehmen Sie die weiteren Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-postfach>>.
. Klicken Sie auf **Postfach erstellen**. +
→ Das E-Mail-Postfach wird beim externen Dienstleister mailbox.org erstellt.

[[tabelle-postfach]]
.Postfach erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**E-Mail-Adresstyp**
|E-Mail-Adresstyp **Postfach** wählen. +
**Postfach** = Legt ein neues E-Mail-Postfach an. +
**Alias** = Legt eine zusätzliche E-Mail-Adresse für ein bestehendes Postfach an. Die Auswahl des Postfachs erfolgt über die Option **Zielpostfach**.

|**E-Mail-Adresse**
|E-Mail-Adresse eingeben, die dem Postfach zugeordnet werden soll. Lokalen Teil der E-Mail-Adresse vor dem @ eingeben. Domain-Teil aus der Dropdown-Liste wählen. +
**__Hinweis:__** Für Testdomains, zum Beispiel @plenty-test-drive, sowie für externe Domains, die nicht über plentymarkets verwaltet werden, können keine Postfächer angelegt werden. +
**__Hinweis:__** Nach dem Löschen einer E-Mail-Adresse ist diese Adresse 48 Stunden gesperrt. Erst nach Ablauf dieser Frist kann diese E-Mail-Adresse erneut vergeben werden.

|**Vorname** +
**Nachname**
|Vornamen und Nachnamen der Person mit diesem Benutzerkonto eingeben. Dieser Name wird mit der E-Mail-Adresse als Absender angezeigt.

|**Systembenutzer**
|Benutzerkonto wählen, dem das Postfach zugewiesen werden soll.

|**Weiterleitungen**
|Wenn E-Mails, die an dieses Postfach gesendet werden, an ein anderes Postfach weitergeleitet werden sollen, eine oder mehrere E-Mail-Adressen eingeben. Mehrere E-Mail-Adressen durch Komma getrennt hinterlegen, zum Beispiel kunde@ihredomain.de,consultant@ihredomain.de.

|**E-Mails in Postfach speichern**
|Option wird wählbar, wenn eine Weiterleitung eingerichtet wird. +
Aktiviert = E-Mails werden an die Ziel-E-Mail-Adressen weitergeleitet. Kopien der weitergeleiteten E-Mails werden auch in diesem Postfach gespeichert. +
Nicht aktiviert = E-Mails werden direkt an die Ziel-E-Mail-Adressen weitergeleitet. In diesem Postfach werden keine E-Mails gespeichert.

|**Passwort**; +
**Passwort wiederholen**
|Passwort eingeben und durch erneute Eingabe bestätigen. +
**__Hinweis:__** Passwort muss aus mindestens 8 Zeichen und einer Kombination aus Großbuchstaben, Kleinbuchstaben und Zahlen bestehen.

|**Tarif**
|Tarif wählen. Preise gelten zzgl. MwSt. Ihr plentymarkets Vertrag wird nach dem Anlegen des Postfachs angepasst.
|====

==== Zugangsdaten für mailbox.org-Server in plentymarkets hinterlegen

Damit plentymarkets E-Mails, zum Beispiel Auftragsbestätigungen, für Sie versenden kann, hinterlegen Sie im Menü <<crm/e-mails-versenden#100, System » Systemeinstellungen » Mandant » Mandant wählen » E-Mail » Zugangsdaten>> die link:https://support.mailbox.org/knowledge-base/article/einrichtung-mit-sonstigen-mailprogrammen[Zugangsdaten^] zu dem mailbox.org-Postfach, über das Sie diese E-Mails versenden möchten.

[#46]
==== Zusätzliche E-Mail-Adresse (Alias) für ein Postfach erstellen

Wenn ein Postfach über mehr als eine E-Mail-Adresse erreichbar sein soll, erstellen Sie ein Alias für das Postfach. Die Anzahl der möglichen E-Mail-Adressen pro Postfach sind vom gewählten Tarif abhängig. Gehen Sie wie unten beschrieben vor, um eine zusätzliche E-Mail-Adresse für ein Postfach zu erstellen.

[.instruction]
Zusätzliche E-Mail-Adresse für ein Postfach erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Klicken Sie auf **Mein Konto**.
. Wechseln Sie in das Tab **E-Mail**.
. Klicken Sie auf **Neu**. +
→ Das Fenster **Postfach erstellen** wird angezeigt.
. Wählen Sie als E-Mail-Adresstyp **Alias**.
. Nehmen Sie die weiteren Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-e-mail-adresssen>>.
. Klicken Sie auf **Postfach erstellen**. +
→ Die zusätzliche E-Mail-Adresse wird erstellt.

[[tabelle-e-mail-adresssen]]
.Zusätzliche E-Mail-Adresse für ein Postfach erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**E-Mail-Adresstyp**
|E-Mail-Adresstyp **Alias** wählen. +
**Postfach** = Legt ein neues E-Mail-Postfach an. +
**Alias** = Legt eine zusätzliche E-Mail-Adresse für ein bestehendes Postfach an. Die Auswahl des Postfachs erfolgt über die Option **Zielpostfach**.

|**E-Mail-Adresse**
|E-Mail-Adresse eingeben, die dem Postfach zugeordnet werden soll: Lokalen Teil der E-Mail-Adresse vor dem @ eingeben. Den Domain-Teil aus der Dropdown-Liste wählen. +
**__Hinweis:__** Nach dem Löschen einer E-Mail-Adresse ist diese Adresse 48 Stunden gesperrt. Erst nach Ablauf dieser Frist kann diese E-Mail-Adresse erneut vergeben werden.

|**Zielpostfach**
|Das Postfach wählen, in das E-Mails an diese Alias-Adresse eingehen sollen.
|====

[#46a]
==== Grundtarif ändern

Standardmäßig gilt für das Hosting von Postfächern bei mailbox.org über plentymarkets der mailbox.org-Grundtarif **Business Reseller**. Dieser Grundtarif ist für Sie kostenlos, umfasst jedoch keinen Support von mailbox.org. Den Grundtarif können Sie jederzeit anpassen. Wenn Sie Support von mailbox.org wünschen oder den Leistungsumfang erweitern möchten, passen Sie Ihren Grundtarif an. Der gewählte Grundtarif gilt für alle Postfächer Ihres gesamtes plentymarkets Systems inklusive aller Mandaten.

[.instruction]
Grundtarif ändern:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Klicken Sie auf **Mein Konto**.
. Wechseln Sie in das Tab **E-Mail**.
. Klicken Sie auf **Grundtarif ändern**. +
→ Das Fenster **Grundtarif wählen** wird angezeigt.
. Prüfen Sie den Leistungsumfang der angebotenen Grundtarife.
. Wählen Sie den gewünschten Grundtarif.
. Klicken Sie auf **Grundtarif ändern**. +
→ Der Tarif wird übernommen und Ihr plentymarkets Vertrag wird angepasst. Sie erhalten außerdem eine E-Mail mit weiteren Informationen von mailbox.org.

[#47]
==== Postfach löschen

Gehen Sie wie unten beschrieben vor, um ein Postfach zu löschen. Sie benötigen Admin-Rechte, um Postfächer/Alias zu löschen. Nach dem Löschen eines Postfachs/Alias können Sie erst nach 48 Stunden wieder ein neues Postfach/Alias mit der gelöschten E-Mail-Adresse anlegen.

[WARNING]
.E-Mails nach dem Löschen des Postfachs nicht mehr zugänglich
====
Nach dem Löschen eines Postfachs können Sie über mailbox.org nicht mehr auf die in diesem Postfach gespeicherten E-Mails zugreifen. Stellen Sie sicher, dass von allen benötigten E-Mails eine lokale Kopie vorhanden ist.
====

[.instruction]
Postfach löschen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Klicken Sie auf **Mein Konto**.
. Wechseln Sie in das Tab **E-Mail**. +
→ Eine Liste der Postfächer wird angezeigt.
. Klicken Sie in der Liste auf das Postfach, das Sie löschen möchten.
. Klicken Sie auf **Löschen**. +
→ Das Postfach und alle damit verbundenen Alias werden bei mailbox.org gelöscht. +
→ Ihr plentymarkets Vertrag wird angepasst.

[#50]
=== Weitere Benutzereinstellungen

Im Bearbeitungsfenster eines Benutzerkontos finden Sie neben den bereits erwähnten noch weitere Tabs. Diese Tabs und ihre Einstellungsmöglichkeiten sind in anderen Themenbereichen erklärt. Zu den Erklärungen gelangen Sie über die Links in der rechten Tabellenspalte.

.Weitere Tabs im Bearbeitungsfenster eines Benutzerkontos
[cols="1,3"]
|====
|Tab |Erläuterung

|**Grußformel**
|In diesem Tab geben Sie einen Text ein, der Ihren Nachrichten und Kommentaren im Ticketsystem automatisch als <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#10, Grußformel>> angefügt wird.

|**Signatur**
|In diesem Tab geben Sie einen Text ein, der Ihren Nachrichten und Kommentaren im Ticketsystem automatisch als <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#20, Signatur>> angefügt wird.

|**Berechtigung**
|Dieses Tab wird im Kapitel <<basics/admin-aufgaben/benutzer-verwalten#90, Berechtigungen zuordnen>> detailliert beschrieben.

|**Persönliche Einstellungen**
|Hier nehmen Sie Einstellungen vor, die nur für das im System angemeldete Benutzerkonto gelten. Deshalb ist das Tab für Sie auch nur in Ihrem eigenen Benutzerkonto sichtbar. Das Tab unterteilt sich in die Tabs <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#40, Allgemein>>, <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#50, Shortcuts>> und <<basics/arbeiten-mit-plentymarkets/benutzerkonto-personalisieren#60, Favoriten>>, die nur Sie persönlich betreffen.

|**Kalender**
|Hier werden Einstellungen für den <<basics/arbeiten-mit-plentymarkets/aufgaben-und-kalender#600, Kalender>> vorgenommen.
|====

[#85]
== Mehrere Benutzerkonten bearbeiten

Mehrere Benutzerkonten bearbeiten Sie per **Gruppenfunktion** im Menü **Benutzer**. Bei der Gruppenfunktion werden zuvor gewählte Benutzerkonten bearbeitet.

[.instruction]
Gruppenfunktion ausführen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Benutzerkonten**.
. Wählen Sie die zu bearbeitenden Benutzer.
. Klicken Sie auf **Gruppenfunktion**. +
→ Das Fenster **Gruppenfunktion** wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in <<tabelle-gruppenfunktion>>.
. Klicken Sie auf **Anwenden**. +
→ Die Benutzerkonten werden geändert.

[[tabelle-gruppenfunktion]]
.Benutzerkonten per **Gruppenfunktion** bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Löschen**
|Aktivieren, um gewählte Benutzerkonten zu löschen.

|**E-Mail senden**
|Aktivieren, um E-Mail an die gewählten Benutzerkonten zu senden. Das E-Mail-Programm wird geöffnet. Die Benutzerkonten sind als Empfänger eingetragen.

|**Skype**
|Aktivieren und **Sofortnachricht**, **Anruf** oder **Video-Anruf** wählen, um die Personen mit diesen Benutzerkonten über Skype zu kontaktieren.

|**Rollen**
|Aktivieren und eine, mehrere oder **ALLE** Rollen aktivieren, um die gewählten Benutzern mit diesen Rollen zu verknüpfen.
|====

[#100]
== Sichtbarkeiten festlegen

Im Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer* legen Sie fest, was die Person mit diesem Benutzerkonto sehen kann, wenn die Person ein Menü öffnet. Bei fehlender Berechtigung ist zum Beispiel ein Lager oder sind Aufträge in einem Status für diese Person nicht sichtbar.

.Tab **Berechtigung** eines variablen Benutzerkontos
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Vertriebslager*; +
*Reparaturlager*; +
*Vorratslager*; +
*Umschlagslager*; +
*Verteilerlager*; +
*Sonderlager* (Typ *Sonstiges*) +
|Benutzerberechtigungen für Lager erteilen. Nur erstellte <<warenwirtschaft/lager-einrichten#300, Lagertypen>> stehen zur Verfügung.

|**Sichtbare Auftragsstatus**
|Auftragsstatus festlegen, die **sichtbar** sein sollen. Die Person mit diesem Benutzerkonto sieht nur die Aufträge, die in diesen Status sind.

|**Setzbare Auftragsstatus**
|Auftragsstatus festlegen, die die Person mit diesem Benutzerkonto setzen darf.

|**Mandanten (Shops)**
|Einzelne, mehrere oder alle Mandanten (Shops) festlegen, die die Person mit diesem Benutzerkonto sehen darf. Die Person mit diesem Benutzerkonto hat nur auf die hier festgelegten Bereiche Zugriff. Wenn kein Mandant gewählt wurde, greifen auch weitere Berechtigungen nicht, da die Person mit diesem Benutzerkonto generell keinen Mandanten sieht. +
**Alle** = Die Person mit diesem Benutzerkonto hat Zugriff auf alle Mandanten. +
**Standard** = Die Person mit diesem Benutzerkonto hat Zugriff auf den Standard-Webshop.

|**Ticketstatus**
|Ticketstatus wählen, um festzulegen, welche Tickets mit welchem Status die Person mit diesem Benutzerkonto ansehen und bearbeiten darf. +
**Unsichtbar** = Die Person mit diesem Benutzerkonto sieht kein Ticket, das in diesem Status ist. +
**Sichtbar** = Die Person mit diesem Benutzerkonto sieht jedes Ticket, das in diesem Status ist. +
**Nur eigene** = Die Person mit diesem Benutzerkonto sieht nur Tickets, die in diesem Status sind und von denen er Eigner ist. +
In der Ticketübersicht werden alle Tickets aufgeführt, also auch für das Benutzerkonto unsichtbare Tickets. Die Person mit diesem Benutzerkonto kann unsichtbare Tickets jedoch nicht öffnen.
|====

[#105]
== Rechte
Mithilfe von Rechten legen Sie fest, was Personen mit einem Benutzerkonto in plentymarkets sehen und was die Person bearbeiten kann. Sie können Rechte für jedes Benutzerkonto einzeln festlegen oder mithilfe von Rollen für mehrere Benutzerkonten.
Im Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer* können Rechte für einzelne Benutzer vergeben werden. Dies beinhaltet die REST-API-Berechtigungen, die Menü-Sichtbarkeiten und die Plugin-Menü-Sichtbarkeiten.
Ebenso können Rechte für Rollen vergeben werden. Ausgeschlossen davon sind die Plugin-Menü-Sichtbarkeiten. Vergibt man eine Rolle an einen Benutzer und hat man an diesen bereits weitere Rechte vergeben, sind alle dort enthaltenen Rechte wirksam.
Im Menüpunkt Ressourcen können die Auftragsherkünfte freigegeben werden, die für den Benutzer sichtbar sollen. +
Ordnen Sie einem Benutzerkonto nur die Rechte zu, die die Person für ihren Aufgabenbereich benötigt. Diese Einschränkung erhöht die Sicherheit und beugt Fehlern in Ihrem System vor.

[#110]
=== Rechte vergeben

Die Benutzerrechte im Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer* gliedern sich in die 3 folgend aufgeführten Bereiche.

[[tabelle-benutzerrechte]]
.Benutzerrechte
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Berechtigungen*
|REST-Rechte, die für bestimmte Aktionen benötigt werden.

|*Menü-Sichtbarkeiten*
|Abbildung von Menü und System tree. Dort können die für den Benutzer sichtbaren Bereiche gewählt werden. Die REST-Rechte für die Menüpunkte werden automatisch gesetzt.

|*Plugins*
|Hier wird die Menü-Sichtbarkeit für Plugins freigegeben. Zunächst werden nur die Plugins mit ihren einzelnen Einträgen, jedoch ohne die korrekte Route, angezeigt.
|====

[.instruction]
Rechte vergeben:

. Öffnen Sie das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Benutzer*. +
→ Die Übersicht wird geöffnet.
. Wählen Sie einen Benutzer. +
→ Der Menüpunkt *Rechte* mit den Sichtbarkeiten wird geöffnet.
. Vergeben Sie die Rechte für den jeweiligen Bereich durch Anklicken der Checkboxen. Aktivieren Sie komplette Bereiche oder klappen Sie Bereiche auf, um einzelne Berechtigungen zu aktivieren, die dem Benutzerkonto zur Verfügung stehen sollen.
. *Speichern* Sie die Einstellungen.

_Hinweis_: Die Bereiche Berechtigungen und Menü-Sichtbarkeiten sind verknüpft, wodurch die gewählten Rechte für den jeweils anderen Bereich automatisch mit aktiviert werden.

[NOTE]
Es kann sein, dass weitere Berechtigungen benötigt werden. Beispiel: Der Menüpunkt Blog benötigt die Berechtigungen für “Blog anzeigen” und “Tag anzeigen”.

[#115]
=== Rechte für Rollen vergeben

Rollen kann man mehreren Benutzern zuweisen. Diese haben dann alle dieselben Rechte.
Für Rollen können lediglich Einstellungen für Berechtigungen und Menü-Sichtbarkeiten, nicht aber für Plugins vorgenommen werden.

[.instruction]
Rechte für Rollen vergeben:

. Öffnen Sie das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Rechte » Rollen*. +
→ Die Übersicht wird geöffnet.
. Wählen Sie eine Rolle. +
→ Der Menüpunkt *Rechte* mit den Sichtbarkeiten wird geöffnet.
. Vergeben Sie die Rechte für Rollen in dem jeweiligen Bereich durch Anklicken der Checkboxen. Aktivieren Sie komplette Bereiche oder klappen Sie Bereiche auf, um einzelne Berechtigungen zu aktivieren, die dem Benutzerkonto zur Verfügung stehen sollen.
. *Speichern* Sie die Einstellungen.

[#120]
=== Menü- und REST-API-Rechte verwalten

Im Tab **Berechtigung** legen Sie fest, welche Berechtigungen ein Benutzerkonto der Klasse **Variabel** für die REST-API erhält. In der Standardeinstellung sind keine REST-API-Berechtigungen vergeben. Benutzerkonten der Klasse **Admin** verfügen über alle Berechtigungen.

[.instruction]
Menü- und REST-API-Rechte verwalten:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Öffnen Sie einen Benutzer.
. Öffnen Sie das Tab **Berechtigungen**.
. Klicken Sie auf **Menü- und REST-API-Rechte verwalten**. +
→ Der Menüpunkt *Rechte* wird geöffnet.
. Vergeben Sie die Rechte in dem jeweiligen Bereich durch Anklicken der Checkboxen. Aktivieren Sie komplette Bereiche oder klappen Sie Bereiche auf, um einzelne Berechtigungen zu aktivieren, die dem Benutzerkonto zur Verfügung stehen sollen.
. **Speichern** Sie die Einstellungen.

[#125]
=== App-Berechtigungen aktivieren

Im Tab **Mobile** legen Sie fest, welche Bereiche und Kennzahlen für Benutzerkonten in der plentymarkets App sichtbar sein sollen.

[.instruction]
App-Berechtigungen aktivieren:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Öffnen Sie einen Benutzer.
. Öffnen Sie das Tab **Mobile**.
. Aktivieren Sie Funktionen oder Kennzahlen, die dem Benutzerkonto in der App zur Verfügung stehen sollen.
. **Speichern** Sie die Einstellungen.

[#145]
=== Benutzerkonto entsperren

Die maximale Anzahl der Login-Versuche beträgt 5 pro Benutzerkonto oder 25 pro IP-Adresse. Wenn die maximale Anzahl der Login-Versuche überschritten wird, wird das Konto für 24 Stunden gesperrt. Personen mit Administratorrechten können ein Benutzerkonto vor Ablauf dieser 24 Stunden manuell entsperren.

[.instruction]
Benutzerkonto entsperren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Konten*. +
→ Die Benutzerkonten werden angezeigt.
. Doppelklicken Sie auf das gesperrte Benutzerkonto. +
→ Das Benutzerkonto wird geöffnet.
. Klicken Sie auf *Login entsperren*. +
→ Das Benutzerkonto wird entsperrt.

[#70]
== Rollen erstellen

Mit Rollen gruppieren Sie Benutzerkonten und erteilen mehreren Benutzern die gleichen Berechtigungen, ohne jedes Benutzerkonto einzeln bearbeiten zu müssen.

[.instruction]
Neue Rolle erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Rollen**.
. Klicken Sie auf **Neue Rolle**. +
→ Das Fenster **Neue Rolle** wird geöffnet.
. Geben Sie einen **Namen** für die Rolle ein.
. **Speichern** Sie die Einstellungen. +
→ Die Rolle wird in einem neuen Tab zur Bearbeitung geöffnet.

Erst beim Bearbeiten der Rolle legen Sie die Berechtigungen fest, die Benutzerkonten mit dieser Rolle haben. Bearbeiten Sie deshalb nach dem Erstellen die Rolle.

[#80]
== Rollen bearbeiten

Nachdem Sie eine Rolle erstellt haben, wird Sie zur Bearbeitung geöffnet und der Rollenübersicht hinzugefügt, so dass Sie die Rolle auch später wieder öffnen und bearbeiten können. Rollen werden in der Übersicht alphabetisch gelistet. Jede Rolle gliedert sich in drei Tabs. Im Tab **Einstellungen** lässt sich der Name der Rolle ändern. Im Tab **Benutzer** verknüpfen Sie Benutzerkonten mit der Rolle. Im Tab **Berechtigungen** ordnen Sie der Rolle Berechtigungen zu. Für Rollen stehen Ihnen die gleichen Berechtigungseinstellungen wie für Benutzerkonten der Klasse Variabel zur Verfügung. Details zu den Berechtigungen finden Sie hier auf der Seite im Kapitel <<basics/admin-aufgaben/benutzer-verwalten#90, Berechtigungen zuordnen>>.

Rollen können von Benutzern der Klasse Admin oder der Klasse Variabel erstellt werden. Benutzerkonten der Klasse Variabel benötigen dafür die Berechtigungen.

[.instruction]
Benutzerkonten mit einer Rolle verknüpfen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Rollen**.
. Öffnen Sie eine Rolle.
. Öffnen Sie das Tab **Benutzer**.
. Wählen Sie Benutzerkonten unter **Verfügbare Benutzer**.
. Klicken Sie auf den **Pfeil nach rechts**, um Benutzerkonten in die Spalte **Zugeordnete Benutzer** zu übertragen. +
*_Oder:_* Ziehen Sie einen Benutzerkonto per Drag &amp; Drop in die Spalte **Zugeordnete Benutzer**.
. **Speichern** Sie die Einstellungen.

[TIP]
.Mehrere Benutzerkonten gleichzeitig verschieben
====
Mit **Strg** oder **cmd** und linker Maustaste markieren Sie mehrere Benutzer, um diese dann zusammen zu verschieben. Mit den unteren Pfeil-Schaltflächen bewegen Sie alle Benutzer.
====

Den Benutzerkonten unter **Zugeordnete Benutzer** wird die betreffende Rolle zugeordnet. Diese Zuordnung wird auch automatisch im Benutzerkonto im Tab **Stammdaten** unter **Rollen** eingestellt. Die Zuordnung kann an beiden Stellen im System angepasst werden.

[.instruction]
Rollen mit einem Benutzerkonto verknüpfen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Öffnen Sie ein Benutzerkonto.
. Wählen Sie eine, mehrere oder alle Rollen unter **Rollen**.
. **Speichern** Sie die Einstellungen.

[TIP]
.Verknüpfung von Benutzerrollen mit Benutzern der Klasse Admin
====
Für Administratoren gelten alle Berechtigungen. Trotzdem ist es für einige Vorgänge wichtig, dass Administratoren auch Rollen zugeordnet werden. So erhalten Administratoren zum Beispiel rollenbezogene E-Mails nur, wenn die Administratoren mit der betreffenden Rolle verknüpft wurden.
====

[.subhead]
Anwendungsbeispiel

Der Administrator der Firma MeinShop erstellt verschiedene Rollen. Die Rolle Mitarbeiter ist für alle Benutzerkonten gedacht und enthält sämtliche Berechtigungen, die jedem Benutzerkonten zugeordnet werden. Die individuelle Zuordnung dieser Berechtigungen entfällt. Auch Änderungen an den Berechtigungen, die alle Benutzerkonten betreffen, werden zentral in dieser Rolle vorgenommen. Zusätzlich zur Rolle Mitarbeiter erstellt der Administrator die spezifischen Rollen Lagerist und Buchhaltung mit weiteren Berechtigungen, die nur eine kleine Benutzergruppe benötigt.

.Beispiel für Rollen
[cols="1,3,3"]
|====
|Rolle |Berechtigungen |Menü-Sichtbarkeiten

|**Mitarbeiter**
|Mandanten (Shops) » Standard
|Start » Webmail +
Start » Forum

|**Lagerist**
|Lager
|System » Systemeinstellungen » Waren » Lager +
Waren +
Aufträge » Fulfillment

|**Buchhaltung**
|
|Start » Urlaubsverwaltung +
System » Systemeinstellungen » Mandant » Mandant wählen » Buchhaltung
|====

Herr Mustermann ist Logistiker bei MeinShop und erhält die Benutzerrollen Mitarbeiter und Lagerist. Wenn einem Benutzerkonto mehrere Rollen zugeordnet werden, addieren sich die Berechtigungen. Herr Mustermann erhält also die Berechtigungen **Mandanten (Shops)**, **Webmail** und **Forum** der Rolle Mitarbeiter sowie die Berechtigungen **Lager**, **Waren** und **Fulfillment** der Rolle Lagerist. Er verfügt aber nicht über die Berechtigungen **Urlaubsverwaltung** und **Buchhaltung**, da ihm die Rolle Buchhaltung nicht zugeordnet wurde.

== Rollen kopieren

Wenn Sie eine weitere Rolle benötigen, die sich von einer bestehenden Rolle nur minimal unterscheidet, dann kopieren Sie die bestehende Rolle und nehmen an der Kopie die Änderungen im Tab **Berechtigungen** vor.

[.instruction]
Rolle kopieren:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Rollen**.
. Wählen Sie eine Rolle.
. Klicken Sie in der Symbolleiste auf **Kopieren**. +
→ Das Fenster **Rolle kopieren** wird geöffnet.
. Geben Sie einen Namen ein.
. **Speichern** Sie die Einstellungen. +
→ Die Rolle wird kopiert und geöffnet.

== E-Mail an alle Benutzerkonten einer Rolle senden

Rollen ermöglichen es Ihnen, E-Mails an alle Benutzerkonten zu senden, die über diese Rolle verfügen und eine E-Mail-Adresse in ihrem Benutzerkonto eingegeben haben.

[.instruction]
E-Mail an alle Benutzerkonten einer Rolle senden:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Rollen**.
. Wählen Sie eine Rolle.
. Klicken Sie in der Symbolleiste auf **E-Mail senden**. +
→ Das E-Mail-Programm wird geöffnet. Die Benutzerkonten dieser Rolle sind als Empfänger eingetragen.

[#60]
== Benutzerkonto suchen

Filter helfen Ihnen bei der Suche nach Benutzerkonten. Mit dem Filter **Klasse** zeigen Sie beispielsweise nur Benutzerkonten der Klasse **Variabel** an. Ohne Filter werden in der Übersicht alle Benutzerkonten angezeigt. Folgende Elemente und Funktionen sind im Menü **Benutzer** verfügbar.

.Filteroptionen für Benutzer
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Suchen**
|Suche ausführen. Zuvor Filteroptionen zur Suche eingeben oder wählen.

|**Reset**
|Filtereinstellungen auf Standardwerte zurücksetzen.

|**ID**
|ID eingeben, um gezielt nach einem Benutzerkonto mit dieser ID zu suchen.

|**Name**
|Name eingeben, um gezielt nach Benutzerkonten mit diesem Namen zu suchen.

|**Klasse**
|Klasse wählen, um gezielt nach Benutzerkonten mit dieser Klasse zu suchen.

|**Rollen**
|Eine, mehrere oder alle Rollen wählen, um gezielt nach Benutzerkonten mit diesen Rollen zu suchen.
|====

[#150]
== Rollen und Prozesse verknüpfen

Verwenden Sie Rollen zum Beispiel auch bei <<automatisierung/prozesse/prozesse-einrichten#, Prozessen>>.

[.instruction]
Rollen und Prozesse verknüpfen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Prozesse » Pro Rolle**.
. Klicken Sie in der Zeile einer **Rolle** auf den **Pfeil** und dann auf **Neuer Prozess** (Bild 1).
. Geben Sie einen **Namen** für die Rolle ein.
. Wählen Sie für die **Sichtbarkeit** die Einstellung **Rolle**. +
→ Die Option **Rolle** wird eingeblendet.
. Wählen Sie eine **Rolle** aus der Dropdown-Liste.
. Wählen Sie, ob die Einstellungen durch einen Eigner mit dieser Rolle **änderbar** sein sollen.
. Wählen Sie das **Lager** für den Prozess und eine **Farbe**.
. **Speichern** Sie die Einstellungen.

Die Prozesse werden für die gewählte Rolle angezeigt. Aufgrund der Sichtbarkeit sieht nur ein Benutzerkonto mit passender Rolle den Prozess.

== Konto für das plentymarkets Forum erstellen

Das plentymarkets Forum ist eine ständig wachsende Wissensdatenbank, die viele Antworten auf bereits gestellte Support-Fragen enthält. Im Forum helfen Ihnen unsere Entwickler und andere plentymarkets Kunden bei technischen Fragen gern weiter. Außerdem finden Sie dort Tipps für das Arbeiten mit plentymarkets und tauschen sich mit anderen plentymarkets Kunden aus. Gehen Sie wie unten beschrieben vor, um ein Konto für das plentymarkets Forum zu erstellen. Benutzerkonten der Klasse **Admin** erstellen so auch Forumkonten für andere Benutzerkonten.

[.instruction]
Konto für plentymarkets Forum erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Benutzer » Konten**.
. Klicken Sie auf **Benutzer öffnen**. +
→ Das Benutzerkonto wird in einem neuen Tab geöffnet.
. Klicken Sie im Bereich **plentymarkets Forum** auf **Konto erstellen** +
→ Das Forenkonto wird erstellt.

[#160]
== Anzahl eingeloggter Benutzerkonten verwalten

Abhängig von Ihrem plentymarkets Tarif ist die Anzahl der Benutzerkonten, die gleichzeitig in plentymarkets eingeloggt sein dürfen, möglicherweise beschränkt. Dieses Limit gilt für das plentymarkets Backend, die REST-API und die plentymarkets App.

Das können Sie tun, wenn Sie das Benutzerlimit erreichen:

* Eingeloggte Personen auffordern, sich manuell ausloggen
* <<#170, Benutzerkonten über die Session-Verwaltung ausloggen>>
* <<#190, Benutzerlimit Ihres plentymarkets Vertrags erhöhen>>


[#170]
=== Benutzerkonten über Session-Verwaltung ausloggen

Gehen Sie wie unten beschreiben vor, um Benutzerkonten über die Session-Verwaltung auszuloggen.

[NOTE]
.Admin-Rechte erforderlich
====
Sie benötigen Admin-Rechte, um Benutzerkonten über die Session-Verwaltung auszuloggen.
====

[.instruction]
Benutzerkonten über Session-Verwaltung ausloggen:

. Zeigen Sie mit der Maus auf das User-Icon oben rechts.
. Klicken Sie auf *Session-Verwaltung*. +
*_Oder:_* Öffnen Sie das Menü *System » Systemeinstellungen » Einstellungen » Benutzer » Session-Verwaltung*. +
→ Das Menü *Session-Verwaltung* wird geöffnet. +
→ Die eingeloggten Benutzerkonten werden angezeigt.
. Aktivieren Sie die Kontrollkästchen der Benutzerkonten, deren Session Sie beenden möchten, um sie auszuloggen.
. Klicken Sie auf *Ausgewählte Sessions beenden*. +
→ Die gewählten Benutzerkonten werden ausgeloggt.

[#180]
=== Benutzerkonten ausloggen, wenn Benutzerlimit überschritten ist

Wenn die zulässige Anzahl gleichzeitig eingeloggter Benutzerkonten bereits erreicht oder überschritten ist, können nicht eingeloggte Admin-Benutzer die Session-Verwaltung über einen Link in der eingeblendeten Fehlermeldung erreichen.

[.instruction]
Benutzerkonten ausloggen, wenn Benutzerlimit überschritten ist:

. Loggen Sie sich in das plentymarkets Backend ein. +
→ Eine Fehlermeldung wird angezeigt.
. Klicken Sie auf den Link in der Fehlermeldung. +
→ Das Menü *Session-Verwaltung* wird geöffnet. +
→ Die eingeloggten Benutzerkonten werden angezeigt.
. Aktivieren Sie die Kontrollkästchen der Benutzerkonten, deren Session Sie beenden möchten, um sie auszuloggen.
. Klicken Sie auf *Ausgewählte Sessions beenden*. +
→ Die gewählten Benutzerkonten werden ausgeloggt. +
*_Hinweis:_* Der Login über die Fehlermeldung ist 10 Minuten gültig. Danach werden Sie automatisch ausgeloggt.

[#190]
=== Weitere Benutzerlizenzen buchen

Weitere Benutzerlizenzen buchen Sie über den plentymarkets Konfigurator.

[.instruction]
Weitere Benutzerlizenzen buchen:

. Öffnen Sie das Menü *Start » Service-Center*. +
*_Tipp:_* Zeigen Sie dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Das Service-Center wird in einem neuen Browser-Tab geöffnet.
. Klicken Sie auf das blaue *Plus* des Systems. +
→ Die verfügbaren Tabs werden eingeblendet.
. Wechseln Sie in das Tab *Vertrag*.
. Klicken Sie auf eine der Schaltflächen *Tarif wechseln*. +
→ Der plentymarkets Konfigurator wird geöffnet.
. Klicken Sie in der Fortschrittsleiste unterhalb des Konfigurators auf die Ansicht *Ausstattung*.
. Scrollen Sie zum Bereich *Benutzerlizenzen (CUL)*.
. Klicken Sie unter *Weitere Benutzerlizenzen (CUL)* auf das Plussymbol, um weitere Benutzerlizenzen hinzufügen.
. Klicken Sie in der Fortschrittsleiste unterhalb des Konfigurators auf die Ansicht *Ihr System*. +
→ Eine Zusammenfassung der neuen Vertragsdaten wird angezeigt.
. Prüfen Sie die Informationen sorgfältig.
. Klicken Sie auf *Systemänderung bestellen*. +
→ Die Systemänderung wird durchgeführt.
