= Dein plentymarkets Konto
:lang: de
include::{includedir}/_header.adoc[]
:position: 10
:url: basics/admin-aufgaben/dein-konto
:id: AIXO9P7
:author: none

//make this more about what can be done in general and less about where exactly, because some stuff is in my account, other stuff isn't
Im Menü *plentymarkets Logo (Start) » Mein Konto* findest du Informationen zu deinem plentymarkets System. Du kannst Änderungen an den hier gespeicherten Informationen selbst vornehmen.
Zum Beispiel kannst du:

* deinen Vertrag mit plentymarkets einsehen und bearbeiten.
* die Kontaktinformationen, die wir für dich gespeichert haben, ändern.
* Partneragenturen Zugang zu deinem System ermöglichen.

[#20]
== Dein Vertrag mit plentymarkets

Im Menü *plentymarkets Logo (Start) » Mein Konto » Verträge* kannst du Informationen zu deinem Vertrag mit plentymarkets einsehen und bearbeiten.
Hier kannst du zum Beispiel:

* <<basics/admin-aufgaben/plentymarkets-konto#30, zu einem anderen Tarif wechseln>>
* <<basics/admin-aufgaben/plentymarkets-konto#40, gebuchte Leistungen einsehen und bei Bedarf kündigen>>
* <<basics/rechtliches/dsgvo#500, DSGVO-relevante Dokumente einsehen>>

[TIP]
.Service-Center wird schrittweise abgebaut
====
Vielleicht kannst du dich daran erinnern, deine Vertragsinformationen früher mal im Menü *plentymarkets Logo (Start) » Service-Center* eingesehen zu haben. Das Service-Center wird nach und nach aufgelöst.
Deshalb empfehlen wir dir, dich mit dem Bereich "Mein Konto" vertraut zu machen, noch bevor das Service-Center vollständig entfernt wird.
====

[#30]
=== Tarif wechseln

plentymarkets wächst mit deinen Anforderungen.
Du entscheidest selbst, z.B. welche Module dein Unternehmen benötigt und wie viele Aufträge du ungefähr pro Monat mit plentymarkets abwickeln wirst.
Wir stellen dir dafür die nötige Systemleistung zur Verfügung.

Im Bereich "Mein Konto" kannst du deinen plentymarkets Vertrag eigenständig im laufenden Betrieb anpassen.
Eine Anpassung des Vertrags ist zum Beispiel sinnvoll, wenn du mehr Aufträge generierst als im bestehenden Vertrag enthalten sind. Die Buchung einer höheren Anzahl an Aufträgen ist jederzeit möglich. Wenn du eine niedrigere Anzahl buchst, wird diese Änderung erst nach Ablauf der regulären Laufzeit deines aktuellen Vertrags wirksam.

[.instruction]
Vertrag ändern:

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:file-text[role="darkGrey"] *Verträge*. +
→ Informationen über deine laufenden Verträge werden angezeigt.
. Klicke auf icon:pencil[role="darkGrey"] *Vertrag bearbeiten*. +
→ Der Tarifkonfigurator wird eingeblendet.
. Passe die Vertragsdetails wie gewünscht an.

[#40]
=== Leistungen einsehen und bei Bedarf kündigen

Im Bereich "Mein Konto" siehst du alle in Rechnung gestellten Posten. Bei Bedarf kannst du hier einzelne Module oder sogar deinen gesamten Vertrag mit plentymarkets kündigen.

[.instruction]
Leistungen einsehen und kündigen:

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:file-text[role="darkGrey"] *Verträge*. +
→ Informationen über deine laufenden Verträge werden angezeigt.
. Klappe die Vertragsinformationen auf (icon:chevron-down[role="darkGrey"]). +
→ Klicke auf icon:ban[role="red"] [red]#Vertrag kündigen# oben rechts, um eine Kündigung deines gesamten Vertrags in Auftrag zu geben. +
→ Klicke auf icon:trash[role="darkGrey"] *Jetzt Kündigen* neben einem bestimmten Modul, um nur diese spezifische Dienstleistung zu kündigen.


[#440]
== Zertifizierten Agenturen Zugang zum System geben

Im Menü *plentymarkets Logo (Start) » Mein Konto » Agentur* gibst du zertifizierten Dienstleistern Zugriff auf dein System.
Es ist sinnvoll, einem Dienstleister Zugang zu deinem System zu gewähren, z.B. wenn du eine Design-Agentur mit der Erstellung deiner Website beauftragst oder wenn du mit einem Consultant zusammenarbeitest.
Der Dienstleister erhält dann unbegrenzten, d.h. Admin-Zugang zu deinem System.

[TIP]
.Entscheide selbst, welche Funktionen und Menüs zugänglich sein sollen!
====
Wenn du einer Agentur Zugang zu deinem System gewährst, gibst du dieser Agentur unbegrenzten, administrativen Zugang.

Wenn du der Agentur lieber nur Zugang zu bestimmten Funktionen oder Menüs geben möchtest, dann <<basics/admin-aufgaben/benutzer-verwalten#, erstelle ein neues Benutzerkonto>>, z.B. ein Backend-Konto, und passe die Zugriffsrechte an.
====

[discrete]
==== Zugriff gewähren

Gehe wie unten beschrieben vor, um der Agentur und/oder dem Consultant, mit denen du zusammenarbeitest, Zugriff auf dein System zu gewähren:

[.instruction]
Dienstleister zuweisen:

. Öffne das Menü *plentymarkets Logo (Start) » Mein Konto*. +
*_Tipp:_* Zeige dazu mit der Maus auf das plentymarkets Logo oben links. +
→ Der Bereich "Mein Konto" wird in einem neuen Browser-Tab geöffnet.
. Klicke auf icon:handshake-o[role="darkGrey"] *Agenturen*. +
→ Informationen über die Agenturen, mit denen du bereits zusammenarbeitest, werden angezeigt.
. Klicke auf icon:plus[role="darkGrey"] *Agentur hinzufügen*. +
→ Eine Liste der zertifizierten Dienstleister wird angezeigt.
. Klicke auf icon:plus[role="darkGrey"] *Hinzufügen* neben der Agentur, die Zugang zu deinem System erhalten soll.

*_Hinweis_*: Du kannst diesen Zugang jederzeit entziehen.
