= Drucker verwalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Drucker, plentyBase, Druckereinstellungen, Drucker konfigurieren, Druckverlauf, Druckhistorie, Druck Historie, Druckerprobleme
:position: 50

Im Menü **System » Systemeinstellungen » Einstellungen » Drucker** richten Sie lokal oder in Ihrem Netzwerk installierte Drucker in plentymarkets ein. Um plentymarkets mit lokal installierten Endgeräten zu verbinden, muss das Tool link:https://marketplace.plentymarkets.com/plugins/integration/plentybase_5053[plentyBase^] auf dem Rechner installiert und gestartet sein.

[#10]
== Druckerkonfiguration erstellen

Gehen Sie wie unten beschrieben vor, um eine Druckerkonfiguration zu erstellen.

[.instruction]
Druckerkonfiguration erstellen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Drucker**.
. Klicken Sie auf das Kontextmenü im Menübaum. +
→ Der Button **Neuer Drucker** wird eingeblendet.
. Klicken Sie auf **Neuer Drucker**. +
→ Das Konfigurationsmenü wird geöffnet.
. Nehmen Sie die Einstellungen vor. Beachten Sie die Erläuterungen in Tabelle 1.
. **Speichern** Sie die Einstellungen. +
→ Der Drucker wird im Menübaum angezeigt.
. Drucken Sie vor dem Produktiveinsatz einige Testseiten/-etiketten und experimentieren Sie mit verschiedenen Drucker-Plugins, um das Druckergebnis zu optimieren.

.Druckerkonfiguration erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|**Testseite**
|Druckereinstellungen durch den Ausdruck einer Testseite prüfen.

|**Name**
|Name eingeben. Der Name ist frei wählbar. So lassen sich mehrere gleiche Drucker unterschiedlich benennen.

|**Drucker**
|Zeigt die Drucker, die lokal oder im Netzwerk verfügbar sind.

|**Drucker-Dialog**
|Wählen, ob der Drucker-Dialog vor dem Ausdrucken geöffnet oder nicht geöffnet werden soll. +
**öffnen** = Ausrichtungs- und weitere Einstellungen müssen vor jedem Druck vorgenommen werden. +
**nicht öffnen** = Ausrichtungs- und weitere Einstellungen werden in diesem Menü vorgenommen und für den Druck verwendet.

|**Papierfach**
|Ein Papierfach wählen. Die verfügbare Auswahl ist abhängig vom gewählten Drucker.  +
**_Hinweis_**: Option ist nur für Windows verfügbar. +
Zur Konfiguration verschiedener Papierformate die Hinweise im nachfolgenden Unterkapitel beachten.  +

|**Papierformat**
|Ein Papierformat wählen. Die Papierformate werden vom Drucker bereitgestellt, daher können die Bezeichnungen abweichen. +
Bei Wahl eines benutzerdefinierbaren Papierformats, zum Beispiel **Custom**, werden Eingabefelder für die **Breite** und **Höhe** des Druckmediums eingeblendet. +
Wenn mehrere Formate benötigt werden weitere Drucker einrichten und diesen Druckern die unterschiedlichen Formate zuordnen.

|**Doppelseitiger Druck**
|Doppelseitiger Druck wird derzeit nicht unterstützt.

|**Skalierung**
|Skalierung wählen.  +
**Auf Seitengröße (Proportion nicht berücksichtigen)** = Der Ausdruck wird auf die Gesamtgröße des Druckbereichs skaliert. Diese Einstellung kann zu einer verzerrten Darstellung führen.  +
**Auf Seitengröße (Proportion berücksichtigen)** = Der Ausdruck wird innerhalb des Druckbereichs auf die größtmögliche Größe skaliert, bei der keine Verzerrung auftritt.  +
**Keine** = Der Ausdruck wird nicht skaliert.

|**Ausrichtung**
|Ausrichtung wählen, um nur in einer Ausrichtung zu drucken. Die angezeigten Optionen werden vom Drucker bereitgestellt, daher können die Bezeichnungen abweichen.  +
**portrait** = Ausrichtung im Hochformat  +
**landscape** = Ausrichtung im Querformat  +
*_Tipp:_* Option **Automatische Seitenausrichtung** markieren, um den Seiteninhalt automatisch auf der Seite auszurichten.

|**Oben, Unten, Links, Rechts**
|Optional Abstände in mm eingeben, um die Positionierung des Inhalts auf der Seite zu bestimmen.

|**Automatische Seitenausrichtung**
|Aktivieren, um den Seiteninhalt automatisch auf der Seite auszurichten.

|**Drucker-Plugin**
|Wählen, über welches Plugin plentymarkets den Drucker ansteuern soll. +
**__Tipp:__** Vor dem Produktiveinsatz Testseiten/-etiketten drucken, um die Druckqualität verschiedener Drucker-Plugins zu testen. +
**Standard** = Der Standard für das Betriebssystem wird verwendet. +
**Cups**; **PDFBox** = Wählen, wenn die Druckqualität mit der Option **Standard** nicht ausreicht. +
**ZPL** (Zebra Programming Language) = Wählen, wenn es sich um einen Zebra-Etikettendrucker handelt. +
**__Hinweis zum ZPL-Plugin:__** Das ZPL-Plugin ist für eine native Auflösung von 203 dpi optimiert. Bei anderen Auflösungen kann die Größe der Etiketten abweichen. Bei abweichender Etikettengröße *203 dpi* wählen oder ein anderes Drucker-Plugin verwenden. +
**__Hinweis zum ZPL-Plugin:__** Für eine optimale Nutzung des ZPL-Plugins muss der Drucker unter Mac OSX über das CUPS-Webinterface im <<basics/admin-aufgaben/drucker#65, RAW-Modus>> hinzugefügt werden.
|====

[#20]
== Drucker mit verschiedenen Papierfächern konfigurieren (nur Windows)

Wenn Sie über einen Drucker mit verschiedenen Papierfächern verfügen und mit verschiedenen Papierformaten arbeiten möchten, erstellen Sie ein Druckerprofil pro Papierfach.

[TIP]
.Beispielkonfiguration für verschiedene Formate
====
Sie möchten Rechnungen im Format DIN A4 und Etiketten im Format DIN A6 drucken.

Richten Sie ein Druckerprofil mit dem Papierformat DIN A4 und ein weiteres Druckerprofil mit dem Papierformat DIN A6 ein. Wählen Sie dabei den gleichen Drucker und ordnen Sie das passende Papierfach zu.
====

[#30]
== Druckerkonfiguration freigeben

Druckerprofile werden benutzerabhängig auf dem Rechner gespeichert. Sie stehen also nicht für andere Benutzer eines Rechners zur Verfügung. Wenn ein Druckerprofil auch für andere Benutzer zur Verfügung stehen soll, muss das Profil freigegeben werden. Die Freigabe erfolgt auf Ihrem Rechner und nicht in plentymarkets. Informationen dazu, wie Sie Drucker auf Ihrem Rechner freigeben, finden Sie in der Hilfe für Ihr Betriebssystem:

* Für Windows zum Beispiel link:http://windows.microsoft.com/de-de/windows/share-printer#1TC=windows-7[hier^]
* Für Mac zum Beispiel link:https://support.apple.com/de-de/HT4670[hier^]

[#40]
== Fehlerursachen und Fehler beheben

Die folgende Tabelle enthält Informationen zu Fehlercodes, die beim Einrichten des Druckers auftreten können.

.Fehlermeldungen im Menü **Drucker**
[cols="1,3,3,3"]
|====
|Code |Fehler |Ursache |Fehler beheben

|2000
|Unter Mac OS X: Kein CUPS Drucker gefunden.
|Kein angeschlossener Drucker verfügt über eine Netzwerkfreigabe. Diese Freigabe ist für die Druckerkommunikation über CUPS erforderlich.
|<<basics/admin-aufgaben/drucker#30, Drucker freigeben>>

|2001
|Unter Mac OS X: Unbekannter CUPS Drucker.
|Unter dem angegebenen Namen konnte kein Drucker im Netzwerk gefunden werden.
|<<basics/admin-aufgaben/drucker#30, Drucker freigeben>>

|2101
|Fehler beim Drucken.
|Verschiedene Ursachen möglich.
|

|2102
|Drucker wurde nicht gefunden.
|Der Drucker ist im System nicht mehr vorhanden oder die Konfiguration ist nicht mehr korrekt.
|Neuen Drucker hinzufügen oder anderen Drucker verwenden.
|====

[#50]
== Etiketten drucken

Zum Drucken von Etiketten werden Etikettendrucker eingesetzt, die ein schnelles Ausdrucken großer Etikettenmengen ermöglichen. Dazu sind diese Drucker mit Etikettenrollen ausgestattet sowie, je nach Modell, mit einer Schneidevorrichtung. In den Einstellungen des Menüs **System » Systemeinstellungen » Einstellungen » Drucker** legen Sie über die Option **Papierformat** die exakte Größe eines Etiketts fest. Sie wählen zwischen Standardformaten und einer frei konfigurierbaren Option, über die Sie benutzerdefinierte Größen hinterlegen (Tabelle 1).

Die Druckfunktionen sind mit üblichen Etikettendruckern kompatibel und wurden für Etikettendruckermodelle des Herstellers link:http://www.zebra.com[Zebra^] optimiert. Für den Einsatz als Desktop-Drucker empfehlen wir das Modell link:http://www.zebra.com/gb/en/products-services/printers/printer-type/desktop/g-series-gc.html[Zebra GC420d^].

[#60]
=== Zebra GC420d auf Ihrem Rechner installieren

Gehen Sie wie unten beschrieben vor, um das Druckermodell Zebra GC420d unter den Betriebssystemen Windows und Mac OSX zu installieren.

[.instruction]
Zebra GC420d installieren:

. Laden Sie die link:http://www.zebra.com/gb/en/support-downloads/desktop/gx430t.html#mainpartabscontainer_999b=drivers[Zebra Setup Utilities^]-Datei auf Ihren Rechner herunter.
. Installieren Sie diese Datei.
. Durchlaufen Sie den Installationsassistenten. +
→ Windows: Wählen Sie den Drucker ZDesigner GC420d. Hier ist der Druckertreiber ZPL eingestellt. +
→ Mac OSX: Stellen Sie den Druckertreiber ZPL ein. Testen Sie die Treibereinstellung für jede Etikettengröße. Um das Drucker-Plugin **ZPL** zu nutzen, konfigurieren Sie den Drucker für den <<basics/admin-aufgaben/drucker#65, RAW-Druck>>.

[#65]
=== Zebra-Drucker mit ZPL-Plugin einrichten (nur Mac OSX)

Um das ZPL-Plugin unter Mac OSX optimal zu nutzen, muss der Zebra-Drucker so konfiguriert werden, dass er Druckaufträge im RAW-Format empfängt. Beim Drucken im RAW-Format werden Druckdaten in der nativen Sprache des Druckers gesendet. Dabei bleiben die Druckdaten unverändert, da der Druckertreiber des Betriebssystems umgangen wird.

Den RAW-Druck konfigurieren Sie über die CUPS-Webschnittstelle. Gehen Sie wie unten beschrieben vor, um die CUPS-Webschnittstelle zu aktivieren und die Konfiguration des Druckers vorzunehmen.

[.instruction]
ZPL-Plugin - CUPS-Webschnittstelle aktivieren (nur Mac OSX):

. Öffnen Sie mit der Tastenkombination "cmd" + "Leertaste" die Spotlight-Suche.
. Geben Sie den Begriff **Terminal** ein.
. Betätigen Sie die Eingabetaste. +
→ Das Terminal wird geöffnet.
. Geben Sie im Terminal den Befehl **sudo cupsctl WebInterface=yes** ein.
. Betätigen Sie die Eingabetaste. +
→ Sie werden aufgefordert, Ihr Passwort einzugeben.
. Geben Sie Ihr Passwort ein. +
→ Die CUPS-Webschnittstelle ist aktiviert.

[.instruction]
ZPL-Plugin - Raw-Modus für Zebra-Drucker einrichten (nur Mac OSX):

. Navigieren Sie in einem Webbrowser zu der Adresse **http://localhost:631**. +
→ Die CUPS-Webschnittstelle wird angezeigt.
. Wechseln Sie in das Tab **Administration**.
. Klicken Sie auf **Add Printer**. +
→ Sie werden aufgefordert, Ihre Zugangsdaten einzugeben.
. Geben Sie Benutzername und Passwort ein. +
→ Die Seite **Add Printer** wird angezeigt.
. Wählen Sie den Zebra-Drucker aus der Liste.
. Klicken Sie auf **Continue**.
. Geben Sie einen Namen, eine Beschreibung und einen Standort für den Drucker ein.
. Markieren Sie **Share This Printer**, um den Drucker mit anderen zu teilen.
. Klicken Sie auf **Continue**.
. Wählen Sie in der Liste **Make** die Option **Raw**.
. Klicken Sie auf **Continue**.
. Klicken Sie auf **Add Printer**.
. Lassen Sie die Einstellungen **Starting Banner** und **Ending Banner** auf **none**.
. Klicken Sie auf **Set Default Options**. +
→ Ihr Zebra-Drucker kann Druckaufträge im RAW-Format empfangen. +
**__Hinweis:__** Der Zebra-Drucker wird nicht in den Systemeinstellungen angezeigt, ist aber eingerichtet und für plentyBase sichtbar.
. Wählen Sie im Menü **System » Systemeinstellungen » Einstellungen » Drucker** das Drucker-Plugin **ZPL**, um den Drucker hinzuzufügen.

[#70]
=== Etikettendruck konfigurieren

Die Größe und Breite Ihrer Etiketten konfigurieren Sie in plentymarkets. Fügen Sie hierfür den Etikettendrucker zur Druckerliste hinzu. Gehen Sie dazu wie unten beschrieben vor. Beispielhaft wird das Konfigurieren von Etiketten mit dem Format 104 x 150 beschrieben.

[.instruction]
Drucker mit Etikett 104 x 150 hinzufügen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Drucker**.
. Klicken Sie auf das Kontextmenü im Menübaum. +
→ Der Button **Neuer Drucker** wird eingeblendet.
. Klicken Sie auf **Neuer Drucker**. +
→ Das Konfigurationsmenü wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie aus der Dropdown-Liste **Drucker** den Etikettendrucker.
. Wählen Sie **nicht öffnen** für den **Druckerdialog**.
. Wählen Sie **Ungültige Auswahl** für das **Papierfach**.
. Wählen Sie **Custom** für das **Papierformat**.
. Geben Sie **150** als **Papierhöhe** ein.
. Geben Sie **104** als **Papierbreite** ein.
. Lassen Sie die Option einseitig für doppelseitigen Druck.
. Wählen Sie **auf Seitengröße (Proportion nicht beachten)** für die **Skalierung**.
. Wählen Sie **Hochformat** für die **Ausrichtung**.
. **Speichern** Sie die Einstellungen.

[TIP]
.Tipp bei verschiedenen Etikettengrößen
====
Wenn Sie verschiedene Etikettengrößen verwenden, können Sie entweder die Papierhöhe und Papierbreite beim Wechsel der Etikettengröße anpassen oder pro Etikettengröße einen eigenen Drucker erstellen.
====

[#80]
=== Fehlerhaften Etikettendruck korrigieren

Wenn der Druck leicht versetzt, der Hauptteil auf dem Label jedoch erkennbar ist, empfehlen wir, die Ausrichtung über die Einstellungen **Oben**, **Links**, **Unten** und **Rechts** anzupassen.

Wenn nur ein kleiner Teil der Angaben auf dem Etikett gedruckt wird oder Ihr Etikett komplett leer bleibt, passen Sie den Druckertreiber an. Insbesondere auf Apple-Rechnern hängt der korrekte Druck häufig vom Treiber ab, aber auch bei Windows-Computern kann der Druckertreiber die Fehlerursache sein.  +
Für Windows empfehlen wir Ihnen, den Drucker ZDesigner GC420d mit dem Treiber ZPL zu installieren. In einigen Fällen kann aber der ZDesigner GC420d (EPL) mit dem Druckertreiber EPL bessere Druckergebnisse liefern.

Wenn das Etikett wieder korrekt gedruckt wird, legen Sie sich einen Drucker mit den korrekten Einstellungen für das Etikett an, so dass Sie die Einstellungen wiederverwenden können. Wir empfehlen dazu, den Drucker mehrfach mit verschiedenen Treibern auf Ihrem Rechner zu installieren, denn so können Sie, wenn ein Etikett nicht korrekt gedruckt wird, den Druck schnell mit einem anderen Treiber noch einmal versuchen.

Eine weitere Ursache für einen fehlerhaften Druck kann sein, dass der Prozess statt auf die Etiketteneinstellungen in plentymarkets auf die Etikettenparameter Ihres Druckers zugreift. Tragen Sie eventuell Etikettenparameter in Ihren Druckereinstellungen nach.

Ab plentymarkets 7 stehen außerdem verschiedene Drucker-Plugins zur Auswahl. Wenn Sie mit der Druckqualität nicht zufrieden sind, experimentieren Sie mit den verschiedenen Drucker-Plugins.

[#90]
== Druckaufträge verwalten

Im Druckverlauf werden maximal die Druckaufträge der letzten 14 Tage angezeigt, die vom lokalen Rechner gestartet wurden.

=== Druckverlauf anzeigen

[.instruction]
Druckverlauf anzeigen:

. Öffnen Sie das Menü **Daten » Druck Historie**. +
→ Der Druckverlauf wird geöffnet. +
*_Hinweis:_* Der Druckverlauf wird lokal gespeichert. Wenn über den lokalen Rechner noch keine Dokumente gedruckt wurden, ist der Druckverlauf leer. +
*_Tipp:_* Standardmäßig werden 25 Einträge angezeigt. Über die Dropdown-Liste ändern Sie die Anzahl der angezeigten Einträge. +
*_Hinweis:_* Druckaufträge werden zwischengespeichert, um die Aufträge an den Drucker weiterzuleiten. Sobald der Druckauftrag zwischengespeichert wurde, wird das Dokument im Druckverlauf aufgeführt. Der Druckverlauf kann also Druckaufträge enthalten, die nicht gedruckt wurden.

=== Dokumente erneut drucken

Sie können die im Druckverlauf angezeigten Dokumente erneut drucken. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Dokumente erneut drucken:

. Öffnen Sie das Menü **Daten » Druck Historie**. +
→ Der Druckverlauf wird geöffnet.
. Aktivieren Sie die Kontrollkästchen der Dokumente, die erneut gedruckt werden sollen.
. Klicken Sie auf **Erneut drucken**. +
→ Die Dokumente werden gedruckt.

=== Dokumente manuell aus dem Druckverlauf entfernen

Im Druckverlauf werden maximal die Druckaufträge der letzten 14 Tage angezeigt. Nach Ablauf von 14 Tagen werden Druckaufträge automatisch aus dem Verlauf entfernt. Gehen Sie wie unten beschrieben vor, um Dokumente manuell aus dem Druckverlauf zu entfernen.

[.instruction]
Dokumente manuell aus dem Druckverlauf entfernen:

. Öffnen Sie das Menü **Daten » Druck Historie**. +
→ Der Druckverlauf wird geöffnet.
. **Löschen** Sie die Dokumente. +
→ Die Dokumente werden gelöscht.

[#100]
== Druckerkonfiguration löschen

Gehen Sie wie unten beschrieben vor, um eine Druckerkonfiguration zu löschen.

[.instruction]
Drucker löschen:

. Öffnen Sie das Menü **System » Systemeinstellungen » Einstellungen » Drucker**.
. Klicken Sie auf den Drucker. +
→ Das Konfigurationsmenü wird geöffnet.
. Klicken Sie auf **Löschen**. +
→ Die Druckerkonfiguration wird gelöscht.
