= plentymarkets Status
:lang: de
include::{includedir}/_header.adoc[]
:keywords: plentymarkets Status, plenty Status
:description: Erfahre mehr über plentymarkets Status.
:position: 80
:url: basics/admin-aufgaben/plentymarkets-status
:id: 50
:author: team-fulfillment

plentymarkets Status benachrichtigt dich per E-Mail in Störungsfällen, bei wichtigen Änderungen wie z.B. bei der Beendigung der Softwarepflege und Bereitstellung oder auch bei internen sowie externen Wartungsarbeiten bei einem unserer Partner. Im Fall einer Störung wird außerdem eine E-Mail mit dem voraussichtlichen Zeitpunkt der Behebung versendet.

[#plentymarkets-status-abonnieren]
== plentymarkets Status abonnieren

Mit einem Klick abonnierst du plentymarkets Status und erhältst im Falle von Neuigkeiten eine E-Mail an die in deinem Benutzerkonto gespeicherte E-Mail-Adresse.

[.instruction]
plentymarkets Status abonnieren:

. Logge dich in deinem plentymarkets Backend ein.
. Klicke auf die Benutzer-Schaltfläche (icon:user-circle[]) bzw. dein Benutzerbild oben rechts.
. Klicke auf *plentymarkets Status*. +
→ Die Ansicht *plentymarkets Status abonnieren* wird geöffnet.
. Aktiviere die Schaltfläche icon:toggle-off[role="red"]. +
→ Du hast plentymarkets Status erfolgreich abonniert.


[#hinweis-admin-benutzer]
== Hinweis für Admin-Benutzer

Standardmäßig erhält jeder *Admin*-Benutzer in deinem System die plentymarkets Status-E-Mails.

Wie du plentymarkets Status abbestellst, ist im Kapitel <<basics/admin-aufgaben/plentymarkets-status#, plentymarkets Status abbestellen>> beschrieben.

[#plentymarkets-status-abbestellen]
== plentymarkets Status abbestellen

Wenn du keine Benachrichtigungen erhalten möchtest, kannst du plentymarkets Status jederzeit abbestellen.

[.instruction]
plentymarkets Status abbestellen:

. Logge dich in deinem plentymarkets Backend ein.
. Klicke auf die Benutzer-Schaltfläche (icon:user-circle[]) bzw. dein Benutzerbild oben rechts.
. Klicke auf *plentymarkets Status*. +
→ Die Ansicht *plentymarkets Status abonnieren* wird geöffnet.
. Aktiviere die Schaltfläche icon:toggle-off[role="green"]. +
→ Du hast plentymarkets Status abbestellt und erhältst keine E-Mails mehr.

[#plentymarkets-status-e-mail-aendern]
== E-Mail-Adresse ändern

Die plentymarkets Status-E-Mail wird an die E-Mail-Adresse versendet, die im Benutzerkonto gespeichert ist.

Wenn du die Status-E-Mails an eine andere E-Mail-Adresse gesendet haben möchtest, musst du die E-Mail-Adresse im Benutzerkonto im Menü *Einrichtung » Einstellungen » Benutzer » Konten* ändern.
