= Kathrin_Entwurf_Kategorien
:lang: de
include::{includedir}/_header.adoc[]
:position: 0

//  ENTWURF
Kategorien in plentymarkets sind einerseits das, was Ihnen aus anderen Systemen als Warengruppen oder Artikelkategorien bekannt sind. Andererseits handelt es sich um Ihre Content-Seiten für den Bereich **CMS**. Die verschiedenen Kategorietypen verfügen generell über eine große Schnittmenge an Einstellungen. Zu diesen Gemeinsamkeiten zählt z.B. die Verwaltung in einer Ordnerstruktur. Dies ist über das Erstellen von Hauptkategorien und bis zu 5 Unterkategorien möglich. Eine weitere Gemeinsamkeit ist, dass üblicherweise Texte wie Beschreibung, Kurzbeschreibung, Meta-Beschreibung sowie grafische Elemente hinterlegt werden. Deshalb werden sie in plentymarkets gemeinsam als Kategorien verwaltet.

* SEO für Content + Artikel!
* CANONICAL
* MANDANTEN
* SITEMAP

Unterscheiden lassen sie sich in plentymarkets einfach anhand des Typs. Hierfür gibt es die Typen **Artikel**, **Content** und **Container**. Die gemeinsame Verwaltung als Kategorien bietet für jeden Typ einige zusätzliche Einstellungsmöglichkeiten, die sonst üblicherweise entweder für Warengruppen oder für Content-Seiten verwendet werden. In einigen Fällen sind diese jedoch auch praktisch für den jeweils anderen Typ. Zum Beispiel können Sie beim Typ **Content** per Template-Variable eine Kurzbeschreibung einfügen. Beim Typ **Artikel** können Sie Tags nutzen.

.Kategorietypen
[cols="a,a,a"]
|====
|Typ |Erläuterung |Ordnerfarbe Backend

|**Artikel**
|Unterteilung der Artikel im Webshop, e.g. Herren » Oberteile » T-Shirts
|Blau

|**Content**
|Content-Seiten für den Bereich **CMS**, e.g. Informationsseiten wie AGBs, Zahlungs- und Versandinformationen. PLATZHALTER
|Gelb

|**Container**
|Der Inhalt einer Kategorie des Typs Container kann ähnlich wie der von Freitextfeldern über Template-Funktionen auf anderen Seiten angezeigt werden, z.B. in einer anderen Kategorie. Außerdem werden damit die Bestellschritte des <<omni-channel/online-shop/cms#webdesign-webdesign-bearbeiten-bestellvorgang-individueller-bestellvorgang, **Individuellen Bestellvorgangs**  >> realisiert.
|Rot

|**Blog**
|Zurzeit ohne Funktion
|Gelb
|====

== Vorbereitungen

=== Kategorieebenen festlegen

Legen Sie zunächst fest, wie viele Kategorieebenen in Ihrem Webshop angezeigt werden sollen. Diese Einstellung nehmen Sie pro Mandanten (Shop) vor. Wenn Sie z.B. 4 einstellen, können keine Kategorien auf der 5. Ebene erstellt werden. Diese Einstellung gilt für den gesamten Kategoriebaum, d.h. für alle Kategorietypen.

[.instruction]
Kategorieebenen festlegen:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Kategorien » Grundeinstellungen**.
. Wählen Sie die maximal mögliche Ebenentiefe in der Kategorienavigation.
. **Speichern** Sie die Einstellung.

=== Struktur der Artikelkategorien planen

Erarbeiten Sie wenn möglich eine sinnvolle Kategoriestruktur, bevor Sie mit dem Erstellen der Kategorien beginnen. Überlegen Sie vor dem Erstellen von Artikelkategorien, welche Produkte Ihr Portfolio beinhaltet und leiten Sie daraus Kategorien und Unterkategorien ab. Tabelle 2 zeigt zwei stark vereinfachte Beispiele für verschiedene Artikelstrukturen.

.Beispiele für verschiedene Artikelkategoriestrukturen
[cols="a,a"]
|====
|Beispielstruktur 1 |Beispielstruktur 2

a|
* Damen
* Schuhe
* Accessoires
* etc.

* Herren
* Schuhe
* Accessoires
* etc.

* Kinder
* Schuhe
* Accessoires
* etc.

a|
* Schuhe
* Damen
* Herren
* Kinder

* Accessoires
* Damen
* Herren
* Kinder

* Etc.
* Damen
* Herren
* Kinder

|====

[TIP]
.Standard-Kategorie "Content"
====
Die Kategorie **Content** ist standardmäßig im System gespeichert. Eigene Kategorien mit dem Namen **Content** können nicht erstellt werden. Name und URL-Name der Kategorie **Content** sind nicht änderbar. Nicht namensbezogene Optionen, z.B. die Position, sind änderbar.
====

== Kategorie erstellen

Neue Kategorien erstellen Sie entweder als Hauptkategorie oder als Unterkategorie. Hauptkategorien sind Kategorien der ersten Ebene. Unterkategorien sind Kategorien aller weiterer Ebenen des Kategoriebaums. Wie Sie Haupt- und Unterkategorien erstellen, wird nachfolgend getrennt beschrieben.

=== Hauptkategorie erstellen

Gehen Sie wie unten beschrieben vor, um eine Hauptkategorie zu erstellen.

[.instruction]
Hauptkategorie erstellen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Klicken Sie links unten auf **Neue Kategorie**. +
→ Das Fenster **Neue Kategorie erstellen** wird geöffnet.
. Geben Sie einen Namen für die Kategorie ein.
. Wählen Sie **Hauptkategorie** als Kategorieebene.
. Klicken Sie auf **Erstellen**. +
→ Die Kategorie wird erstellt und im Verzeichnisbaum links angezeigt. +
**__Tipp:__** Neue Kategorien haben standardmäßig den Kategorietyp **Artikel**. Ändern Sie bei Bedarf den Kategorietyp.

=== Unterkategorie erstellen

Um eine Unterkategorie zu erstellen, muss eine Hauptkategorie vorhanden sein. Nachfolgend wird beschrieben, wie Sie eine Unterkategorie der zweiten Ebene erstellen. Um eine Unterkategorie der 3. oder 4. Ebene zu erstellen, klicken Sie die Unterkategorien an, bis Sie die Kategorie erreicht haben, zu der Sie eine Unterkategorie erstellen möchten. Sie haben zwei Möglichkeiten, Unterkategorien zu erstellen:

[.instruction]
Unterkategorie über Button "Neue Kategorie" erstellen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Klicken Sie links unten auf **Neue Kategorie**. +
→ Das Fenster **Neue Kategorie erstellen** wird geöffnet.
. Geben Sie einen Namen für die Kategorie ein.
. Wählen Sie **Unterkategorie** als Kategorieebene. +
→ Die Kategorieebenen werden auswählbar.
. Wählen Sie die Hauptkategorie, der die neue Kategorie untergeordnet werden soll.
. Klicken Sie auf **Erstellen**. +
→ Die Kategorie wird erstellt und im Verzeichnisbaum links als Unterkategorie angezeigt. +
**__Tipp:__** Neue Kategorien haben standardmäßig den Kategorietyp **Artikel**. Ändern Sie bei Bedarf den Kategorietyp.

[.instruction]
Unterkategorie über das Kontextmenü erstellen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Öffnen Sie die Kategorie, zu der Sie eine Unterkategorie erstellen möchten.
. Klicken Sie mit der rechten Maustaste auf die Kategorie. +
→ Das Kontextmenü wird geöffnet.
. Klicken Sie auf **Unterkategorie erstellen**. +
→ Das Fenster **Neue Unterkategorie erstellen** wird geöffnet.
. Geben Sie einen Namen für die Unterkategorie ein.
. Klicken Sie auf **Erstellen**. +
→ Die Kategorie wird erstellt und im Verzeichnisbaum links als Unterkategorie angezeigt. +
**__Tipp:__** Neue Kategorien haben standardmäßig den Kategorietyp **Artikel**. Ändern Sie bei Bedarf den Kategorietyp.

== Kategorie bearbeiten

Neue Kategorien werden im Verzeichnisbaum links angezeigt. Öffnen Sie eine Kategorie, indem Sie sie anklicken oder indem Sie mit der rechten Maustaste das Kontextmenü öffnen. Dieses Menü ermöglicht Ihnen den Schnellzugriff auf bestimmte Funktionen, um die Kategorie zu bearbeiten, zu verschieben, zu kopieren oder zu löschen. Sie können außerdem einen neuen Artikel oder eine Unterkategorie erstellen.

Das Bearbeitungsfenster einer Kategorie besteht aus 5 Tabs:

* **Einstellungen**
* **Beschreibung 1**
* **Beschreibung 2**
* **Dokumente**
* **Notiz**

Oberhalb der Tabs der Kategorie befindet sich eine Symbolleiste, deren Optionen in Tabelle 1 erläutert werden.

========
include::{includedir}/presets/kategorieeinstellungen.adoc[]
========= === Beschreibung speichern

In den Tabs **Beschreibung 1** und **Beschreibung2** fügen Sie Text ein und formatieren ihn. In das Webdesign Ihres Shops sowie an anderen Stellen fügen Sie diese Beschreibung über <<omni-channel/online-shop/cms-syntax#grundlagen-template-variablen, **Template-Variablen**  >> und <<omni-channel/online-shop/cms-syntax#grundlagen-template-funktionen, **Template-Funktionen**  >> ein. Mit **Beschreibung 1** und **2** haben Sie die Möglichkeit, zwei Texte zu einer Kategorie zu verfassen und an unterschiedlichen Stellen einer Webseite anzuzeigen. So können Sie **Beschreibung 1** z.B. oberhalb einer Artikelübersicht und **Beschreibung 2** darunter anzeigen.

Über das Dropdown-Menü rechts über dem Eingabefeld wählen Sie den Editor, mit dem Sie die Beschreibung bearbeiten möchten. Zur Verfügung stehen der **<<omni-channel/online-shop/cms#webdesign-werkzeuge-editor, Editor  >>**, der HTML-Editor **Textfeld** und der <<omni-channel/online-shop/cms#webdesign-werkzeuge-syntax-editor, **Syntax-Editor**  >>. Für den Typ **Container** stehen nur der HTML-Editor **Textfeld** und der **Syntax-Editor** zur Verfügung.

[#10]
=== Dokumente hochladen

Im Tab **Dokumente** laden Sie Dokumente hoch, die zu dieser Kategorie gehören.

Zulässig sind Datenformate wie JPEG, PNG, GIF, TIFF, PDF, DOC, ODC, OTH, XLS, XML, HTML, HTM, CSS, JavaScript, ZIP, JSON und GZIP.

[NOTE]
.Dokumente hochladen
====
Dokumente fügen Sie entweder über **Datei hochladen** oder per Drag-and-Drop-Funktion zum Tab hinzu.
====

Bei einer Kategorie vom Typ **Artikel** legen Sie bis zu zwei Kategoriebilder fest. Sie können weitere Dokumente und Bilder hochladen und so z.B. das Kategoriebild regelmäßig ändern, ohne das alte Bild zu löschen. Gehen Sie wie nachfolgend beschrieben vor, um Kategoriebilder festzulegen.

[.instruction]
Kategoriebilder für Kategorie des Typs Artikel festlegen:

. Öffnen Sie die **Kategorie**.
. Wechseln Sie in das Tab **Dokumente**.
. Zeigen Sie mit der Maus auf das gewünschte Bild.
. Setzen Sie ein Häkchen in der **Auswahlbox** des Bildes.
. Klicken Sie auf **Bild 1**.
. **Speichern** Sie die Einstellungen. +
→ Das Bild erhält einen roten Rahmen mit einer **1**.

Verfahren Sie für das 2. Kategoriebild genauso und klicken Sie in Schritt 5 auf **Bild 2**. Die Auswahl eines Kategoriebilds heben Sie auf, indem Sie ein Häkchen in der Auswahlbox des Bildes setzen und erneut auf **Bild 1** bzw. **Bild 2** klicken.

Die ausgegrauten Buttons der Symbolleiste werden wählbar, sobald ein oder mehrere Bilder durch Setzen eines Häkchens gewählt wurden. Dies ermöglicht es, die Vorschau für mehrere Bilder gleichzeitig zu öffnen, sie gleichzeitig herunterzuladen oder gemeinsam zu löschen.

[TIP]
.Anzeige der Kategoriebilder im Webshop
====
Standardmäßig wird nur Kategoriebild 1 im Webshop angezeigt. Hierfür wurde eine <<omni-channel/online-shop/cms-syntax#grundlagen-if, **if-Abfrage**  >> mit der Template-Variable <<omni-channel/online-shop/cms-syntax#webdesign-navigation, **$CurrentCategoryImageUrl** >> in das Template **ItemViewCategoriesList** eingefügt. Damit auch Kategoriebild 2 angezeigt wird, fügen Sie eine zweite if-Abfrage in das Template ein.
====

=== Notiz speichern

Im Tab **Notiz** speichern Sie Anmerkungen zu einer Kategorie. Hier können Sie z.B. festhalten, woher eine Information stammt, oder vermerken, dass bestimmte Abschnitte nicht geändert werden dürfen. Die in diesem Tab gespeicherten Informationen sind nur in plentymarkets sichtbar und werden nicht im Webshop ausgegeben. Notizen können nicht gelöscht werden.

[.instruction]
Notiz speichern:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Öffnen Sie die Kategorie.
. Geben Sie die Notiz in das Bearbeitungsfeld ein.
. **Speichern** Sie die Notiz. +
→ Die Notiz wird gespeichert und in einer gelben Sprechblase angezeigt. +
→ Notizen können nicht gelöscht werden.

== Kategorie aktivieren

=== Eine Kategorie aktivieren

Eine Kategorie ist erst im Webshop eines Mandanten (Shops) sichtbar, nachdem die Kategorie aktiviert wurde. Die Aktivierung nehmen Sie im Menü link::/[**Einstellungen » Mandant (Shop) » Standard » Kategorien » Aktivieren**] vor.

[.instruction]
Eine Kategorie aktivieren:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Öffnen Sie die Kategorie. +
→ Das Tab **Einstellungen** der Kategorie wird geöffnet.
. Wählen Sie im Bereich **Mandant (Shop)** die Mandanten, in denen die Kategorie aktiv sein soll.
. **Speichern** Sie die Einstellung. +
→ Die Kategorie wird für die gewählten Mandanten (Shops) sichtbar geschaltet.

Folgende Voraussetzungen müssen erfüllt sein, damit eine Kategorie im Webshop angezeigt wird:

. Die Kategorie muss für den Mandanten wie eben aktiviert werden.
. Für den Mandanten muss mindestens ein Artikel mit der Kategorie verknüpft sein.
. Im Tab **Kategorien** eines Artikels muss mindestens die Kategorie für den gewünschten Mandanten auf **Verfügbar** stehen.
. Der Artikel muss verfügbar sein, d.h., der Warenbestand muss positiv sein und beim Artikel muss im Tab **Verfügbarkeit** die Option **Webshop** auf **Sichtbar** gestellt sein.

=== Mehrere Kategorien für Mandanten gleichzeitig aktivieren

Das Menü **Einstellungen » Mandant (Shop) » Standard » Kategorien » Aktivieren** bietet Ihnen die Möglichkeit, Kategorien eines Mandanten zentral zu aktivieren bzw. zu deaktivieren.

[.instruction]
Mehrere Kategorien für Mandanten gleichzeitig aktivieren:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Kategorien » Aktivieren**.
. Markieren Sie die Kategorien, die Sie aktivieren möchten. +
**__Tipp:__** Mit **Alle auswählen** markieren Sie alle Kategorien. Mit **Alle abwählen** heben Sie die Markierung aller markierten Kategorien auf.
. **Speichern** Sie die Einstellungen.
. Prüfen Sie die Anzeige der Kategorien und Artikel im Webshop. +
**__Tipp:__** Es kann etwas dauern, bis eine aktivierte Kategorie im Webshop sichtbar ist. Prüfen Sie bei Problemen alle Einstellungen und laden Sie die Anzeige Ihres Webshops neu.

== Kategorien verwalten

=== Kategorien filtern

Kategorien können nach dem Mandanten, der Sprache und dem Typ gefiltert werden. Die Filter befinden sich oberhalb des Kategorieverzeichnisses. Ob eine Kategorie in der gewählten Kombination verfügbar ist, erkennen Sie am Schriftschnitt. Normal dargestellte Kategorien sind in der Kombination verfügbar. Für kursiv dargestellte Kategorien ist für die gewählte Filterkombination aus Mandant, Sprache und Typ keine Konfiguration vorhanden.

=== Kategorie suchen

Die Suchfunktion über dem Kategoriebaum hilft Ihnen, eine Kategorie schnell zu finden. Geben Sie den Namen der gesuchten Kategorie in das Textfeld ein. Bereits während der Eingabe werden die Suchergebnisse angezeigt.

=== Kategorie kopieren

Die Option **Kategorien kopieren** bietet die Möglichkeit, die gleiche Kategorie als Unterkategorie zu verschiedenen übergeordneten Kategorien zu erstellen. Dies ist z.B. sinnvoll, wenn Sie bei Bekleidung zwischen Damen, Herren, Kindern unterscheiden, aber bei allen dreien die Kategorie Hosen benötigen. Dazu die Kategorie mit sämtlichen Einstellungen kopieren und anschließend den Namen und die Beschreibung anpassen.

[.instruction]
Kategorie kopieren:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Zeigen Sie mit der Maus auf eine Kategorie.
. Klicken Sie rechts neben der Kategorie auf das Dreieck nach unten. +
→ Ein **Kontextmenü** wird geöffnet.
. Klicken Sie auf **Kategorie kopieren**. +
→ Die Menüübersicht **Kategorie kopieren** wird geöffnet.
. Wählen Sie **Hauptkategorie**, um die Kopie in der Hauptkategorieebene zu speichern. Wählen Sie **Unterkategorie**, um die Kopie in einer Unterkategorieebene zu speichern.
. Wählen Sie die Kategorie, unter der die Kopie eingeordnet werden soll.
. Klicken Sie auf **Kopieren**. +
→ Die Kategorie wird links im Verzeichnisbaum unter der gewählten Kategorie angezeigt.
. Passen Sie ggf. die Position der Kategorie an, um sie korrekt einzuordnen.

=== Kategorie verschieben

Kategorien werden im Bereich **Artikel » Kategorien** in der gewählten Struktur dargestellt. Aus der Kategoriestruktur und den Kategorienamen ergibt sich das Navigationsmenü, das im Webshop dargestellt wird. Die Struktur ergibt sich einmal aus den Haupt- und Unterkategorien und der Zuordnung dieser Kategorien zueinander. Das sind die sogenannten Ebenen. Zum anderen ergibt sie sich aus den Positionen. Mit der Position einer Kategorie legen Sie die Reihenfolge innerhalb einer Kategorieebene fest. Um eine Kategorie nachträglich in der Ebene zu verschieben, gibt es die Funktion **Kategorie verschieben**.

[.instruction]
Kategorie in Hauptkategorieebene verschieben:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Zeigen Sie mit der Maus auf eine Kategorie.
. Klicken Sie rechts neben der Kategorie auf das Dreieck nach unten. +
→ Ein **Kontextmenü** wird geöffnet.
. Klicken Sie auf **Kategorie verschieben**. +
→ Die Menüübersicht **Kategorie verschieben** wird geöffnet.
. Wählen Sie **Hauptkategorie**.
. Klicken Sie auf **Verschieben**. +
→ Die Kategorie wird links im Verzeichnisbaum in der obersten Ebene angezeigt.
. Passen Sie ggf. die Position der Kategorie an, um sie korrekt einzuordnen.

[.instruction]
Kategorie in Unterkategorieebene verschieben:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Zeigen Sie mit der Maus auf eine Kategorie.
. Klicken Sie rechts neben der Kategorie auf das Dreieck nach unten. +
→ Ein **Kontextmenü** wird geöffnet.
. Klicken Sie auf **Kategorie verschieben**. +
→ Die Menüübersicht **Kategorie verschieben** wird geöffnet.
. Wählen Sie **Unterkategorie**.
. Wählen Sie die Kategorie, unter der die Kategorie eingeordnet werden soll.
. Klicken Sie auf **Verschieben**. +
→ Die Kategorie wird links im Verzeichnisbaum unter der gewählten Kategorie angezeigt.
. Passen Sie ggf. die Position der Kategorie an, um sie korrekt einzuordnen.

== Kategorien löschen

Sie können Kategorien entweder vollständig löschen oder eine angezeigte Kombination aus Mandant (Shop) und Sprache. Beide Vorgehensweisen werden nachfolgend beschrieben.

=== Kategorie vollständig löschen

Kategorien können entweder über das Kontextmenü oder über die Symbolleiste der Kategorie gelöscht werden. Dabei wird die Kategorie in allen Mandanten und Sprachen aus dem System gelöscht.

[.instruction]
Kategorie über Kontextmenü löschen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Zeigen Sie mit der Maus auf eine Kategorie.
. Klicken Sie rechts neben der Kategorie auf das Dreieck nach unten. +
→ Das **Kontextmenü** wird geöffnet.
. Klicken Sie auf **Kategorie löschen**. +
→ Ein Fenster mit einer Sicherheitsabfrage wird angezeigt.
. Klicken Sie auf **Löschen**. +
→ Die Kategorie wird gelöscht.

[.instruction]
Kategorie über Symbolleiste löschen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Wählen Sie in den Filtereinstellungen den Mandanten und die Sprache. +
→ Die Kategorien dieser Filterkombination werden angezeigt.
. Öffnen Sie die Kategorie.
. Klicken Sie in der Symbolleiste der Kategorie auf **Löschen**. +
→ Das Fenster **Löschen** wird angezeigt.
. Klicken Sie auf **Kategorie löschen**, um die Kategorie vollständig zu löschen. +
→ Die Kategorie wird vollständig gelöscht.

=== Kombination aus Sprache und Mandanten (Shop) löschen

Statt eine Kategorie vollständig zu löschen, kann auch nur Beschreibung und Einstellungen für eine bestimmte Sprache eines Mandanten gelöscht werden. Gehen Sie dazu wie unten beschrieben vor.

[.instruction]
Kombination aus Sprache und Mandanten (Shop) löschen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Wählen Sie in den Filtereinstellungen den Mandanten und die Sprache. +
→ Die Kategorien dieser Filterkombination werden angezeigt.
. Öffnen Sie die Kategorie.
. Klicken Sie in der Symbolleiste der Kategorie auf **Löschen**. +
→ Das Fenster **Löschen** wird angezeigt.
. Klicken Sie auf **Sprache für Mandant löschen**, um die angezeigte Kombination aus Sprache und Mandant zu löschen. +
→ Die Kategorie wird für diese Kombination aus Sprache und Mandant gelöscht.

=== Alle ungenutzten Kategorien des Typs Artikel löschen

EINZELN LÖSCHEN beschreiben - nur angezeigte kombi oder ganze kategorie löschen

Mit der Funktion **Löschen ungenutzter Artikelkategorien** des Menüs **Einstellungen » Grundeinstellungen » Datenbank** löschen Sie sämtliche Kategorien des Typs **Artikel** aus dem System, die nicht mit mindestens einem Artikel verknüpft sind. Dabei bleiben alle Artikeldaten erhalten.

[.instruction]
Ungenutzte Kategorien des Typs Artikel löschen:

. Öffnen Sie das Menü **Einstellungen » Grundeinstellungen » Datenbank**.
. Klicken Sie im Bereich **Löschen ungenutzter Artikelkategorien** auf das Zahnrad. +
→ Alle Kategorien des Typs **Artikel** ohne Artikelverknüpfungen werden aus dem System gelöscht.

== !!!!Kategorie vom Typ Content ins Webshop-Design einbinden

Diese Seite noch integrieren? https://www.plentymarkets.eu/handbuch/mandant-shop/standard/webshop/content-seiten/

