= Kategorietyp Artikel bearbeiten
:lang: de
include::{includedir}/_header.adoc[]
:position: 20

Artikelkategorien erstellen Sie für die Einteilung Ihrer Artikel im Webshop. Überlegen Sie zunächst, welche Produkte Ihr Portfolio beinhaltet und teilen Sie Ihr Portfolio in Kategorien und Unterkategorien ein. Sie können z.B. **Damenbekleidung** und **Herrenbekleidung** als oberste Kategorie anlegen und darunter jeweils **Schuhe** etc. – oder eben genau andersherum: Sie können auch **Schuhe** als Hauptkategorie anlegen und darunter die Kategorien **Damen** und **Herren** anführen. Die Einteilung hängt von Ihrem Portfolio ab. +
Wie Sie **Haupt**- und **Unterkategorien** anlegen erfahren Sie auf der Seite **<<artikel/kategorien/kategorien-bearbeiten#, Kategorien bearbeiten>>**. Auf dieser Seite finden Sie auch alle anderen Einstellungen, die für alle Kategorietypen, d.h. Artikel, Content und Container, gelten.

[TIP]
.Kategorietyp Artikel
====
Kategorien des Typs Artikel erkennen Sie an den blau hinterlegten Ordner- und Seitensymbolen.
====

== Kategorietyp Artikel bearbeiten

In der folgenden Konfiguration werden nur die Einstellungen hervorgehoben, die für eine Kategorie des Typs **Artikel** unbedingt vorgenommen werden müssen und die sich von Kategorieeinstellungen für den Typ **Content** unterscheiden. Die weiteren Einstellungen sind in Tabelle 2 auf der Seite **<<artikel/kategorien/kategorien-bearbeiten#, Kategorien bearbeiten>>** erklärt.

[.instruction]
Kategorietyp Artikel bearbeiten:

. Öffnen Sie die Kategorie links im Kategorieverzeichnis.
. Stellen Sie als Typ **Artikel** ein. +
→ Bei neuen Kategorien wird automatisch der Typ **Artikel** eingestellt (Standard).
. Wählen Sie für **Template-Liste** ein Design.
. Wählen Sie für **Template-Produkt** ein Design.
. Wählen Sie eine **Elmar-Kategorie**.
. Klicken Sie auf **Speichern**, um die Einstellungen zu sichern.

Nachdem Sie die Kategorie angelegt haben, müssen Sie nun Ihre Artikel mit ihr verknüpfen. Dies tun Sie im Tab **Kategorien** eines Artikels.

[IMPORTANT]
.Kategorietyp ändern
====
Wenn Sie den Typ einer Kategorie, die bereits mit Artikeln verknüpft ist, von **Artikel** zu **Content** ändern, werden die Verknüpfungen nicht automatisch gelöscht. Allerdings ist die Kategorie am Artikel nicht mehr sichtbar.
====

Erfahren Sie mehr zum Verknüpfen von Artikeln mit Kategorien im folgenden Videotutorial:

video::99419244[vimeo]
