= Kategorien bearbeiten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Kategorien, Artikel, Content
:position: 10

**plentymarkets » Artikel » Kategorien**

== Kategorieebenen festlegen

Legen Sie zunächst fest, wie viele Kategorieebenen in Ihrem Webshop angezeigt werden sollen. Wenn Sie z.B. 4 einstellen, können keine Kategorien auf der 5. Ebene angelegt werden.

[.instruction]
Kategorieebenen festlegen:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Kategorien » Grundeinstellungen**.
. Wählen Sie die maximale Ebenentiefe in der Kategorienavigation.
. **Speichern** Sie die Einstellung.

== Kategorie erstellen

Eine neue Kategorie erstellen Sie immer dann, wenn Sie entweder eine neue Artikelkategorie für Ihren Webshop oder eine Seite mit Informationen für Ihren Webshop erstellen möchten. Um eine Unterkategorie erstellen zu können, muss zuvor eine Hauptkategorie vorhanden sein. Einige Kategorien sind schon standardmäßig im System angelegt. Eine dieser Kategorien ist die Kategorie **Content**.

[IMPORTANT]
.Standard-Kategorie "Content"
====
Der Name und der URL-Name der Kategorie **Content** sind nicht änderbar. Nicht namensbezogene Optionen, z.B. die Position, sind änderbar. Eigene Kategorien mit dem Namen **Content** können nicht angelegt werden.
====

Erfahren Sie mehr zum Anlegen von Kategorien im folgenden Videotutorial:

[.linkBox]
link:https://www.plentymarkets.eu/a-3146/[Kategorie anlegen, window="_blank"]

[TIP]
.Tipp: Struktur planen
====
Erarbeiten Sie eine sinnvolle Kategoriestruktur, bevor Sie mit dem Erstellen der Kategorien beginnen. +
Überlegen Sie vor dem Anlegen von Artikelkategorien, welche Produkte Ihr Portfolio beinhaltet und teilen Sie es in Kategorien und Unterkategorien ein. +
Sie können z.B. Damenbekleidung und Herrenbekleidung als oberste Kategorie anlegen und darunter jeweils Schuhe etc. – oder eben genau andersherum: Sie können auch Schuhe als Hauptkategorie anlegen und darunter die Kategorien Damen und Herren anführen. Die Einteilung hängt von Ihrem Portfolio ab.
====

=== Hauptkategorie erstellen

Im Folgenden erfahren Sie, wie Sie neue Hauptkategorien erstellen.

[.instruction]
Hauptkategorie erstellen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Klicken Sie links unten auf **Neue Kategorie**. +
→ Das Fenster **Neue Kategorie erstellen** wird geöffnet.
. Tragen Sie einen **Namen** für die Kategorie ein.
. Wählen Sie **Hauptkategorie** als Kategorieebene.
. Klicken Sie auf **Erstellen**, um die Kategorie anzulegen. +
→ Die Kategorie wird angelegt und im Verzeichnisbaum links angezeigt.

[TIP]
.Kategorietyp
====
Neue Kategorie haben standardmäßig den Kategorietyp **Artikel** (Tabelle 2).
====

=== Unterkategorie erstellen

Es gibt zwei Möglichkeiten, Unterkategorien zu erstellen.

[.instruction]
Unterkategorie über den Button erstellen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Klicken Sie links unten auf **Neue Kategorie**. +
→ Das Fenster **Neue Kategorie erstellen** wird geöffnet.
. Tragen Sie einen **Namen** für die Kategorie ein.
. Wählen Sie **Unterkategorie** als Kategorieebene. +
→ Die Kategorieebenen werden auswählbar.
. Wählen Sie die Hauptkategorie, der die neue Kategorie untergeordnet werden soll.
. Klicken Sie auf **Erstellen**, um die Kategorie anzulegen. +
→ Die Kategorie wird angelegt und im Verzeichnisbaum links als Unterkategorie angezeigt.
. Klicken Sie auf die Hauptkategorie, um die Unterkategorien zu sehen.

[.instruction]
Unterkategorie über das Kontextmenü erstellen:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Öffnen Sie die Kategorie, zu der Sie eine Unterkategorie anlegen möchten.
. Klicken Sie mit der rechten Maustaste auf die Kategorie. +
→ Das Kontextmenü wird geöffnet.
. Klicken Sie auf **Unterkategorie erstellen**. +
→ Das Fenster **Neue Unterkategorie erstellen** wird geöffnet.
. Tragen Sie einen **Namen** für die Unterkategorie ein.
. Klicken Sie auf **Erstellen**, um die Kategorie anzulegen. +
→ Die Kategorie wird angelegt und erscheint im Verzeichnisbaum links als Unterkategorie.
. Klicken Sie auf die Hauptkategorie, um die Unterkategorien anzuzeigen.

Um eine Unterkategorie der 3. oder 4. Ebene zu erstellen, klicken Sie die Kategorien an, bis Sie die Kategorie erreicht haben, zu der Sie die Unterkategorie erstellen möchten.

[IMPORTANT]
.Kategorien aktivieren
====
Damit eine Kategorie im Webshop sichtbar ist, müssen Sie die Kategorie noch aktivieren. Die Aktivierung nehmen Sie im Menü **Einstellungen » Mandant (Shop) » Standard » Kategorien » Aktivieren** vor.
====

== Kategorie bearbeiten

Die neu erstellte Kategorie finden Sie im Verzeichnisbaum links. Sie kann nun bearbeitet werden. Sie können die Kategorie öffnen, indem Sie sie anklicken oder indem Sie per rechter Maustaste das Kontextmenü öffnen. Dieses Menü ermöglicht Ihnen einen Schnellzugriff auf bestimmte Funktionen, um die Kategorie zu bearbeiten, zu verschieben, zu kopieren oder zu löschen. Sie können außerdem einen neuen Artikel oder eine Unterkategorie anlegen.

[IMPORTANT]
.Kategorie kopieren
====
Die Option **Kategorien kopieren** bietet die Möglichkeit, die gleiche Kategorie als Unterkategorie zu verschiedenen übergeordneten Kategorien anzulegen. Dies ist beispielsweise sinnvoll, wenn Sie bei Bekleidung zwischen Damen, Herren, Kindern unterscheiden, aber bei allen dreien die Kategorie Hosen benötigen. Dazu die Kategorie mit sämtlichen Einstellungen kopieren und anschließend den Namen und die Beschreibung noch anpassen.
====

Das Bearbeitungsfenster unterteilt sich in 5 Tabs. Diese Tabs sind: **Einstellungen**, **Beschreibung 1**, **Beschreibung 2**, **Dokumente** und **Notiz**. Oberhalb der Tabs befindet sich eine Symbolleiste, die in Tabelle 1 erläutert wird.

[cols="a,a"]
|====
|Einstellungen |Erläuterung

|**Kategoriepfad**
|Öffnet übergeordnete Kategorien direkt durch Klick auf den Link.

|**Speichern**
|Speichert die Einstellungen bzw. Änderungen an einer Kategorieseite.

|**ID**
|Wird automatisch vergeben und hier angezeigt.

|**Vorschau**
|Öffnet die Vorschau der Kategorie.

|**Inline-Edit-Vorschau**
|Öffnet eine Vorschau, die auch Bearbeitungsmöglichkeiten umfasst.

|**Bilder-Galerie**
|Öffnet die **<<omni-channel/online-shop/cms#bilder-galerie, Bilder-Galerie  >>** in einem neuen Tab. Hier werden Bilder hochgeladen. Die URL eines Bildes kann dann kopiert werden, um sie über den Editor in der Kategorieseite zu verknüpfen.

|**Template-Variablen und -Funktionen**
|Öffnet eine nach Bereichen sortierte Sammlung von <<omni-channel/online-shop/_cms-syntax/grundlagen/template-variablen#, **Template-Variablen**  >> und <<omni-channel/online-shop/_cms-syntax/grundlagen/template-funktionen#, **Template-Funktionen**  >>, die kopiert und in die Seite eingefügt werden können. +
Beispiele für Funktionen: +
**{% Link(xxx) %}** = Verlinkung auf eine andere Kategorieseite (xxx = ID der Seite) +
**{% Link_Help() %}** = Verlinkung auf die Hilfeseite +
**{% Link_ShippingCosts() %}** = Verlinkung auf die Erläuterung der Versandkosten +
__**Wichtig**__: Diese Funktionen können nicht in Newslettern oder Artikelbeschreibungen verwendet werden. Dort muss die absolute URL angegeben werden.

|**Multilingualität**
|Öffnet eine zweisprachige Ansicht. Die dargestellten Sprachen sind wählbar.

|**Kategorie-Einstellungen übertragen**
|Hier ggf. Optionen wählen, die von dieser Kategorie auf eine andere Kategorie mit der gleichen Kategorie-ID eines oder mehrerer Mandanten sowie einer oder mehrerer Sprachen übertragen werden sollen. Damit sind Kategorien mandanten- und sprachübergreifend einfacher und vor allem schneller zu bearbeiten.

|**Link**
|Template-Funktion der Kategorie. Diese enthält immer die Kategorie-ID zur eindeutigen Zuordnung.

|**Timestamp**
|Zeigt den Zeitpunkt der letzten Bearbeitung sowie den Bearbeiter an.
|====

__Tab. 1: Icons der Kategorie-Leiste__

=== Tab: Einstellungen

Das Tab **Einstellungen** wird automatisch geöffnet, wenn Sie eine Kategorie öffnen.

[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Typ**
|Zwischen **Artikel**, **Content** und **Container** wählen. +
In der Kategorieübersicht sind Kategorien des Typs **Artikel** blau hinterlegt. Kategorien des Typs **Content** sind gelb und Kategorien des Typs **Container** sind rot hinterlegt.

|**Name**
|Einen Namen für die Kategorie eintragen. +
Der gleiche Kategoriename darf in unterschiedlichen Kategorien auch auf derselben Ebene verwendet werden. Innerhalb einer Kategorie darf der Name jedoch nur einmal pro Ebene verwendet werden. Dies ermöglicht es, unterschiedliche Meta-Beschreibungen etc. für Kategorien des gleichen Namens zu speichern.

|**Tags**
|Tags, die zu der Kategorie passen, wählen. Beim Tippen werden direkt Vorschläge eingeblendet. Tags dienen dazu, der Kategorie Themengebiete zuzuordnen. Die Tags selbst werden unter <<basics/arbeiten-mit-plentymarkets/tags#, **Einstellungen » Grundeinstellungen » Tags**  >> angelegt.

|**URL-Name**
|Einen Namen für die Verwendung in der URL eintragen. +
Der Name wird beim Anlegen einer neuen Kategorie automatisch als URL-Name verwendet und kann hier geändert werden. Da beim Anlegen noch kein Mandant gewählt wird, wird die automatische URL zunächst nicht indiziert. +
Der gleiche URL-Name darf in unterschiedlichen Kategorien auch auf derselben Ebene verwendet werden. Innerhalb einer Kategorie darf der URL-Name jedoch nur einmal pro Ebene verwendet werden. +
__**Wichtig:**__ Verwenden Sie ausschließlich **ASCII-Code**, da der URL-Name keine Sonderzeichen enthalten darf. Folgende Zeichenfolgen dürfen zu Beginn eines URL-Namens nicht verwendet werden: a-, b-, c-, f-, fa-, p-, t-. Diese Anfangszeichen werden automatisch entfernt, falls sie eingetragen wurden. Aus a-klasse wird z.B. automatisch klasse. Der URL-Name aklasse wäre jedoch möglich für eine Kategorie mit dem Namen A-Klasse.

|**URL**
|Die URL der Kategorie wird angezeigt. +
Diese wird automatisch erstellt und eingetragen. Sie enthält den vollständigen Pfad, also die Domain, die Kategorieebenen sowie den URL-Namen.

|**Canonical**
|URL der Kategorie eintragen, die den gleichen Content enthält. So wird **<<omni-channel/online-shop/_cms-syntax/fallbeispiele/seo-guide#, Duplicate Content  >>** verhindert.

|**Kurzbeschreibung**
|Eine Kurzbeschreibung der Kategorie eintragen. Die Kurzbeschreibung wird über Template-Variablen in das Design des Webshops eingebunden.

|**Position**
|Zahl eintragen, um die Reihenfolge der Kategorien und Unterkategorien einer Kategorie auf gleicher Ebene festzulegen. Die Sortierungsreihenfolge wird im Menü **<<omni-channel/online-shop/mandanten-einrichten/_artikelansichten/grundeinstellungen#, Einstellungen » Mandant (Shop) » Standard » Artikelansichten » Grundeinstellungen  >>** festgelegt. Standardmäßig wird nach aufsteigender Position sortiert. +
**__Tipp:__** Positionsnummern in Zehnerschritten anlegen, damit neue Kategorien dazwischen eingefügt werden können.

|**Mandant (Shop)**
|Einen, mehrere oder alle Mandanten wählen, damit die Kategorie in diesen verfügbar ist. +
Wenn in einer Unterkategorie ein Mandant ausgewählt wird und dieser in den übergeordneten Kategorien nicht ausgewählt ist, wird die Auswahl auf die übergeordneten Kategorien übertragen. Wenn in übergeordneten Kategorien bereits andere Mandanten ausgewählt sind, wird der Mandant zusätzlich ausgewählt. Die Auswahl der anderen Mandanten bleibt somit erhalten. +
**Sichtbarkeit auf Unterkategorien übertragen** +
Die Option wird nur angezeigt, wenn Unterkategorien vorhanden sind. +
Häkchen setzen, um die Mandantensichtbarkeit auf alle Unterkategorien der Kategorie zu übertragen. Die Funktion bezieht sich nur auf den aktuellen Speichervorgang, d.h., das Häkchen muss für jeden Vorgang neu gesetzt werden. +
Wenn eine Sichtbarkeit entfernt wird (Häkchen bei Mandanten entfernen und speichern), wird dies auch auf die Unterkategorien übertragen, wenn die Funktion nicht aktiviert ist. +
Bei Hinzufügen einer Sichtbarkeit wird diese Sichtbarkeit automatisch auch für die übergeordneten Kategorien gesetzt.

|**Meta-Titel**
|Einen Namen eintragen. Dieser Name wird als Titel des Tabs im Webbrowser und als Suchergebnis in Suchmaschinen angezeigt. +
Wird das Feld leer gelassen, wird der Name als Titel verwendet. +
Auf die Länge des Titels achten. Kurze Titel sind besser für Tabs, da längere Titel abgekürzt werden. (Richtwert bis 50 Zeichen)

|**Meta-Beschreibung**
|Eine Meta-Beschreibung eintragen. Diese wird von Suchmaschinen ausgewertet und ist daher besonders bei der Startseite wichtig. Die Meta-Beschreibung sollte den wesentlichen Inhalt in einem Satz enthalten. (Richtwert bis 140 Zeichen)

|**Meta-Keywords**
|Konkrete Stichwörter, wie sie von Personen in Suchmaschinen eingegeben werden, eintragen.

|**Sitemap**
|Zwischen **Anzeigen** und **Nicht anzeigen** wählen. +
**Anzeigen** = Kategorie wird in die Sitemap aufgenommen. +
**Nicht anzeigen** = Kategorie wird nicht in die Sitemap aufgenommen.

|**Robots**
|Zwischen **all**, **index**, **nofollow**, **noindex** und **nofollow, noindex** wählen. Werte des Meta-Elements Robots werden von Crawlern der Suchmaschinen ausgewertet. Dem Crawler wird mithilfe dieser Werte mitgeteilt, wie er mit der Seite und den Links auf dieser Seite verfahren soll. +
**all** = Webseite der Kategorie in den Suchmaschinenindex aufnehmen und Links auf der Seite folgen. +
**index** = In Suchmaschinenindex aufnehmen. +
**nofollow** = Links auf der Seite nicht folgen. +
**noindex** = Nicht in den Suchmaschinenindex aufnehmen. +
**nofollow, noindex** = Den Links nicht folgen und die Webseite der Kategorie nicht in den Suchmaschinenindex aufnehmen.

|**Template-Seite**
|Ein Template wählen. Das hier gewählte Template bildet den Rahmen für die Kategorie. Option steht für Kategorien des Typs **Container** nicht zur Verfügung.

|**Template-Liste**
|Ein Template wählen. Das Template bestimmt, wie die Kategorieübersicht der aktuellen Kategorie aussieht. Die Option steht nur bei **Artikelkategorien** zur Verfügung.

|**Template-Produkt**
|Ein Template wählen. Das Template bestimmt die Einzelansicht der Artikel dieser Kategorie. Die Option steht nur bei **Artikelkategorien** zur Verfügung.

|**Volltextsuche**
|Zwischen **Ja** und **Nein** wählen. +
**Ja** = Vollständiger Text wird durchsucht. +
**Nein** = Text wird nicht vollständig durchsucht.

|**in Linkliste**
|Zwischen **Anzeigen** und **Nicht anzeigen** wählen. +
**Anzeigen**= Kategorie wird in der Navigation im Webshop angezeigt. +
**Nicht anzeigen** = Kategorie wird nicht in der Navigation im Webshop angezeigt.

|**Sichtbar**
|Zwischen **Öffentlich** und **Nach Login** wählen. +
**Öffentlich**= Kategorie ist für alle Besucher des Webshops sichtbar. +
**Nach Login** = Kategorie samt aller Unterkategorien ist nur für eingeloggte Besucher des Webshops sichtbar. Nicht eingeloggte Besucher werden auf Login-Seite umgeleitet.

|**Elmar-Kategorie**
|Elmar-Kategorie wählen.

|**Template-Variablen und -Funktionen übersetzen**
|Zwischen **Ja**, **Nur Link-Template-Variablen und -Funktionen** und **Nein** wählen. +
**Ja**= Alle Template-Variablen und -Funktionen werden übersetzt. +
**Nur Link-Template-Variablen und -Funktionen** = Nur Link-Template-Variablen und -Funktionen werden übersetzt. +
**Nein**= Keine Template-Variablen und -Funktionen werden übersetzt.
|====

__Tab. 2: Erläuterung des Tabs **Einstellungen**__

=== Tabs: Beschreibung 1 und 2

In den Tabs **Beschreibung 1** und **Beschreibung2** fügen Sie Text ein und formatieren ihn. In das Webdesign Ihres Shops sowie an anderen Stellen fügen Sie diese Beschreibung über <<omni-channel/online-shop/_cms-syntax/grundlagen/template-variablen#, **Template-Variablen**  >> und <<omni-channel/online-shop/_cms-syntax/grundlagen/template-funktionen#, **Template-Funktionen**  >> ein. Mit **Beschreibung 1** und **2** haben Sie die Möglichkeit, zwei Texte zu einer Kategorie zu verfassen und an unterschiedlichen Stellen einer Webseite anzuzeigen. So können Sie **Beschreibung 1** z.B. oberhalb einer Artikelübersicht und **Beschreibung 2** darunter anzeigen.

Über das Dropdown-Menü rechts über dem Eingabefeld wählen Sie den Editor, mit dem Sie die Beschreibung bearbeiten möchten. Zur Verfügung stehen der **<<omni-channel/online-shop/cms#webdesign-werkzeuge-editor, Editor  >>**, der HTML-Editor **Textfeld** und der <<omni-channel/online-shop/cms#webdesign-werkzeuge-syntax-editor, **Syntax-Editor**  >>. Für den Typ **Container** stehen nur der HTML-Editor **Textfeld** und der **Syntax-Editor** zur Verfügung.

[#10]
=== Tab: Dokumente

Im Tab **Dokumente** laden Sie Dokumente hoch. Alle Dateien, die zu der Kategorie gehören, speichern und finden Sie hier.

Zulässig sind Datenformate wie JPEG, PNG, GIF, TIFF, PDF, DOC, ODC, OTH, XLS, XML, HTML, HTM, CSS, JavaScript, ZIP, JSON und GZIP.

[NOTE]
.Dokumente hochladen
====
Dokumente fügen Sie entweder über **Datei hochladen** oder per Drag-and-Drop-Funktion zum Tab hinzu.
====

Bei einer Kategorie vom Typ **Artikel** legen Sie bis zu zwei Kategoriebilder fest. Sie können weitere Dokumente und Bilder hochladen und so z.B. das Kategoriebild regelmäßig ändern, ohne das alte Bild zu löschen. Gehen Sie wie nachfolgend beschrieben vor, um Kategoriebilder festzulegen.

[.instruction]
Kategoriebilder für Kategorie des Typs Artikel festlegen:

. Öffnen Sie die **Kategorie**.
. Wechseln Sie in das Tab **Dokumente**.
. Zeigen Sie mit der Maus auf das gewünschte Bild.
. Setzen Sie ein Häkchen in der **Auswahlbox** des Bildes.
. Klicken Sie auf **Bild 1**.
. **Speichern** Sie die Einstellungen. +
→ Das Bild erhält einen roten Rahmen mit einer **1**.

Verfahren Sie für das 2. Kategoriebild genauso und klicken Sie in Schritt 5 auf **Bild 2**. Die Auswahl eines Kategoriebildes heben Sie auf, indem Sie ein Häkchen in der Auswahlbox des Bildes setzen und erneut auf **Bild 1** bzw. **Bild 2** klicken.

Die ausgegrauten Buttons der Symbolleiste werden wählbar, sobald ein oder mehrere Bilder durch Setzen eines Häkchens gewählt wurden. Dies ermöglicht es, die Vorschau für mehrere Bilder gleichzeitig zu öffnen, sie gleichzeitig herunterzuladen oder gemeinsam zu löschen.

[TIP]
.Anzeige der Kategoriebilder im Webshop
====
Standardmäßig wird nur Kategoriebild 1 im Webshop angezeigt. Hierfür wurde eine <<omni-channel/online-shop/_cms-syntax/grundlagen/if#, **if-Abfrage**  >> mit der Template-Variable <<omni-channel/online-shop/_cms-syntax/webdesign/navigation#3, **$CurrentCategoryImageUrl** >> in das Template **ItemViewCategoriesList** eingefügt. Damit auch Kategoriebild 2 angezeigt wird, fügen Sie eine zweite if-Abfrage in das Template ein.
====

=== Tab: Notiz

Im Tab **Notiz** hinterlegen Sie Anmerkungen zu einer Kategorie. Hier können Sie z.B. festhalten, woher eine Information stammt, oder vermerken, dass bestimmte Abschnitte nicht geändert werden dürfen. Die in diesem Tab gespeicherten Informationen sind nur in plentymarkets sichtbar und werden nicht im Webshop ausgegeben. Notizen können nicht gelöscht werden.

=== Kategorien filtern

Kategorien können nach dem Mandanten, der Sprache und dem Typ gefiltert werden. Die Filter befinden sich oberhalb des Kategorieverzeichnisses. Ob eine Kategorie in der gewählten Kombination verfügbar ist, erkennen Sie anhand des Schriftschnitts. Normal dargestellte Kategorien sind in der Kombination verfügbar. Für kursiv dargestellte Kategorien ist für die gewählte Filterkombination aus Mandant, Sprache und Typ keine Konfiguration vorhanden.

=== Kategorie suchen

Die Suchfunktion über dem Kategoriebaum hilft Ihnen, eine Kategorie schnell zu finden. Geben Sie die gesuchte Bezeichnung der Kategorie in das Textfeld ein. Bereits während der Eingabe werden die Suchergebnisse angezeigt.

== Kategorien verschieben

Kategorien werden im Bereich **Artikel » Kategorien** in der gewählten Struktur dargestellt. Aus der Kategoriestruktur und den Kategorienamen ergibt sich das Navigationsmenü, das im Webshop dargestellt wird. Die Struktur ergibt sich einmal aus den Haupt- und Unterkategorien und der Zuordnung dieser Kategorien zueinander. Das sind die sogenannten Ebenen. Zum anderen ergibt sie sich aus den Positionen. Mit der Position einer Kategorie legen Sie die Reihenfolge innerhalb einer Kategorieebene fest. Um eine Kategorie nachträglich in der Ebene zu verschieben, gibt es die Funktion **Kategorie verschieben**.

[.instruction]
Kategorie in Hauptkategorieebene verschieben:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Zeigen Sie mit der Maus auf eine Kategorie.
. Klicken Sie rechts neben der Kategorie auf das Dreieck nach unten. +
→ Ein **Kontextmenü** wird geöffnet.
. Klicken Sie auf **Kategorie verschieben**. +
→ Die Menüübersicht **Kategorie verschieben** wird geöffnet.
. Wählen Sie **Hauptkategorie**.
. Klicken Sie auf **Verschieben**. +
→ Die Kategorie wird links im Verzeichnisbaum in der obersten Ebene angezeigt.
. Passen Sie ggf. die Position der Kategorie an, um sie korrekt einzuordnen.

[.instruction]
Kategorie in Unterkategorieebene verschieben:

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Zeigen Sie mit der Maus auf eine Kategorie.
. Klicken Sie rechts neben der Kategorie auf das Dreieck nach unten. +
→ Ein **Kontextmenü** wird geöffnet.
. Klicken Sie auf **Kategorie verschieben**. +
→ Die Menüübersicht **Kategorie verschieben** wird geöffnet.
. Wählen Sie **Unterkategorie**.
. Wählen Sie die Kategorie, unter der die Kategorie eingeordnet werden soll.
. Klicken Sie auf **Verschieben**. +
→ Die Kategorie wird links im Verzeichnisbaum unter der gewählten Kategorie angezeigt.
. Passen Sie ggf. die Position der Kategorie an, um sie korrekt einzuordnen.

== Mehrere Kategorien für Mandanten gleichzeitig aktivieren

Das Menü **Einstellungen » Mandant (Shop) » Standard » Kategorien » Aktivieren** bietet Ihnen die Möglichkeit, Kategorien eines Mandanten zentral zu aktivieren bzw. zu deaktivieren.

[.instruction]
Mehrere Kategorien für Mandanten gleichzeitig aktivieren:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Kategorien » Aktivieren**.
. Markieren Sie die Kategorien, die Sie aktivieren möchten. +
**__Tipp:__** Mit **Alle auswählen** markieren Sie alle Kategorien. Mit **Alle abwählen** heben Sie die Markierung aller markierten Kategorien auf.
. **Speichern** Sie die Einstellungen.
. Prüfen Sie die Anzeige der Kategorien und Artikel im Webshop. +
**__Tipp:__** Es kann etwas dauern, bis eine aktivierte Kategorie im Webshop sichtbar ist. Prüfen Sie bei Problemen alle Einstellungen und laden Sie die Anzeige Ihres Webshops neu.

