= Kategorierabatte speichern
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Webshop, Mandant, Kategorien, Rabatte, Kategorierabatte
:position: 45

Im Menü **Einstellungen » Mandant (Shop) » Standard » Kategorien » Rabatte** hinterlegen Sie Mengenrabatte für einzelne Artikelkategorien. Pro Kategorie sind bis zu drei Mengenrabatte möglich. Die gespeicherten Rabatte werden automatisch angewendet, wenn Kunden die rabattfähige Menge an Artikeln aus einer Kategorie erreichen oder überschreiten. Dabei gelten die eingegebenen Rabatte nur für die Standardkategorie eines Artikels.

[.instruction]
Kategorierabatte speichern:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Kategorien » Rabatte**.
. Nehmen Sie die Einstellungen vor. Beachten Sie Tabelle 1.
. **Speichern** Sie die Einstellungen. +
→ Der Rabatt wird automatisch im Webshop angewendet, sobald Kunden die rabattfähige Artikelmenge erreichen.

.Kategorierabatte speichern
[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Rabatt 1-3 (%)**
|Rabatt in Prozent eingeben.

|**ab Menge**
|Menge der bestellten Artikel der Kategorie eingeben, ab der der Rabatt greift.
|====

