Wenn du im Assistenten die Optionen *Verkaufspreis anlegen*, *Barcode anlegen* und/oder *Eigenschaft anlegen* gewählt hast, erstellt der Assistent diese Eigenschaften, Verkaufspreise und/oder Barcodes automatisch. Diese neu erstellten Datenfelder musst du nun noch mit den Varianten verknüpfen, die zum Marktplatz exportiert werden sollen. Wie das geht, ist im Bereich *Artikel* des Handbuchs beschrieben:

* Wie du Verkaufspreise mit Varianten verknüpfst, erfährst du im Kapitel <<artikel/artikel-verwalten#240, Verkaufspreise verknüpfen>>.
* Wie du Barcodes mit Varianten verknüpfst, erfährst du im Kapitel <<artikel/artikel-verwalten#250, Barcodes verknüpfen>>.
* Wie du Eigenschaften mit Varianten verknüpfst, erfährst du im Kapitel <<artikel/artikel-verwalten#4900, Eigenschaft verknüpfen und Wert speichern>>. +
*_Tipp:_* Eigenschaften, die du über den Assistenten erstellst, werden automatisch im Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen* zu einer Gruppe *{property-group}* hinzugefügt. Öffne diese Gruppe um zu sehen, welche neuen Eigenschaften verknüpft werden müssen.

////
[#quellen-verknuepfen]
== Im Assistenten erstellte Datenfelder mit Varianten verknüpfen

:property-group:

include::../../_textblocks/instructions/assistent-quellen-verknuepfen.adoc[]
////
