Nachdem du einen Katalog erstellt hast, ordnest du die Datenfelder des Marktplatzes den in plentymarkets gespeicherten Artikeldaten zu. Weitere Informationen zu den plentymarkets Datenquellen, die du zuordnen kannst, findest du unter <<daten/daten-exportieren/kataloge-verwalten#_datenquellen_zuordnen, Datenquellen zuordnen>>.

[TIP]
.Eigenschaften verwenden
====
Verwende <<artikel/artikel-verwalten#3000, Eigenschaften>>, um Werte für Datenfelder zu übergeben, für die es keine Artikeldaten in plentymarkets gibt.
====

[.instruction]
Datenfelder im Katalog zuordnen:

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet. +
→ Links werden die Datenfelder des Marktplatzes angezeigt. +
*_Hinweis:_* Alle mit * gekennzeichneten Felder sind Pflichtfelder und müssen einer plentymarkets Datenquelle zugeordnet werden.
. Wähle für die Datenfelder des Marktplatzes eine plentymarkets Datenquelle aus der Dropdown-Liste.
. Um einem Datenfeld eine weitere plentymarkets Datenquelle zuzuordnen, klicke auf *Quelle hinzufügen*. +
→ Eine neue Zeile wird eingeblendet. +
*_Hinweis:_* Auch wenn du einem Datenfeld mehr als eine Datenquelle zuordnest, wird nur ein Wert übertragen. Die Daten werden in der Reihenfolge geprüft, in der sie zugeordnet werden. Wenn also das erste Datenfeld keinen Wert liefert, wird das zweite Datenfeld übertragen usw.
. Nimm alle gewünschten Zuordnungen vor. +
. *Speichere* (icon:save[role="green"]) die Einstellungen.

////
[#datenfelder-zuordnen]
=== Datenfelder im Katalog zuordnen

include::../../_textblocks/instructions/katalog-datenfelder-zuordnen.adoc[]
////
