= Katalogexport prüfen

Katalogexporte kannst du mit dem Tool plentyBI prüfen. Zurzeit stehen die folgende Kennzahlen für Katalogexporte zur Verfügung:

* <<#1000, Marktplatz-Variantenvalidierung>> +
→ Prüft, ob die Variantendaten eines Katalogs wichtige Regeln bestimmter Marktplätze erfüllen.
* <<#2000, Marktplatz-Bestandsinformationen>> +
→ Visualisiert, welche Bestandsmengen an bestimmte Marktplätze übertragen wurden.

[#1000]
== Marktplatz-Variantenvalidierung

Mit der Kennzahl *Marktplatz-Variantenvalidierung* prüfst du, ob die Variantendaten eines Katalogs wichtige Regeln bestimmter Marktplätze erfüllen.

[IMPORTANT]
.plentyBI Tarif XS
====
Du benötigst den plentyBI Tarif *XS*, um die Kennzahl *Marktplatz-Variantenvalidierung* zu nutzen. Um plentyBI Tarife zu buchen, öffne das Menü *plentymarkets Logo (Start) » Mein Konto » Verträge*. Im Bereich *plentyBI Tarif buchen* stehen plentyBI-Tarife mit verschiedenen Umfängen zur Auswahl.
====

Zurzeit kannst du die Exporte zu den folgenden Amazon Flatfiles prüfen:

* 2020.1109-1_Clothing_DE
* 2020.1109-1_ConsumerElectronics_DE

Bei der Validierung werden alle Pflichtfelder geprüft, die nicht spezifisch für den Produkttyp sind.

[IMPORTANT]
.Die Marktplatz-Variantenvalidierung ist neu!
====
Die Marktplatz-Variantenvalidierung ist ein neues Feature. Wir arbeiten mit Hochdruck daran, den Funktionsumfang zu erweitern und weitere Marktplätze validierbar zu machen.
====

[#1100]
=== Kennzahl *Marktplatz-Variantenvalidierung* erstellen

Damit die Katalogvalidierung im Dashboard angezeigt wird, erstellst du eine Kennzahl. Du arbeitest zum ersten Mal mit Kennzahlen? Dann solltest du dich zuerst <<business-entscheidungen/plenty-bi/myview-dashboard#, mit den Grundlagen des Dashboards und der Kennzahlen vertraut machen>>.

[TIP]
.Rechte für plentyBI vergeben
====
Benutzer:innen mit Admin-Zugang zu deinem plentymarkets System können alle Kennzahlen einsehen und neue Kennzahlen erstellen. Benutzer:innen mit einem Zugang des Typs *Backend* muss diese Berechtigung erteilt werden. Wie du die Benutzerrechte vergibst, erfährst du auf der Handbuchseite <<business-entscheidungen/plenty-bi/myview-dashboard#300, Dashboard (Beta)>>.
====

Gehe wie unten beschrieben vor, um die Kennzahl *Marktplatz-Variantenvalidierung* zu erstellen.

[.instruction]
Kennzahl *Marktplatz-Variantenvalidierung* erstellen:

. Öffne das Menü *Einrichtung » plentyBI » Kennzahlen*.
. Gib einen Namen für die Kennzahl an.
. Wähle aus der Dropdown-Liste *Kennzahl* die Option *Marktplatz-Variantenvalidierung*.
. *_Optional:_* Gib einen Kommentar zur Kennzahl ein.
. Klicke im Bereich *Filter* auf *Bedingung hinzufügen*. +
→ Ein Filter mit Und-Bedingung wird hinzugefügt.
. Wähle aus der Dropdown-Liste *Herkunft* die Option *Herkunft*.
. Aktiviere in der Liste der Herkünfte die Option *Amazon*.
. Speichere icon:save[set=plenty] die Einstellungen. +
→ Die Kennzahl kann im Dashboard angezeigt werden.

[#2000]
== Marktplatz-Bestandsinformationen

Mit der Kennzahl *Marktplatz-Bestandsinformationen* visualisierst du, welche Bestandsmengen an bestimmte Marktplätze exportiert wurden. Du kannst also prüfen, zu welchem Zeitpunkt welcher Warenbestand für eine Variante an den Marktplatz gemeldet wurde.

[IMPORTANT]
.plentyBI Tarif L
====
Du benötigst den plentyBI Tarif *L*, um die Kennzahl *Marktplatz-Bestandsinformationen* zu nutzen. Um plentyBI Tarife zu buchen, öffne das Menü *plentymarkets Logo (Start) » Mein Konto » Verträge*. Im Bereich *plentyBI Tarif buchen* stehen plentyBI-Tarife mit verschiedenen Umfängen zur Auswahl.
====

Zurzeit kannst du mit der Kennzahl *Marktplatz-Bestandsinformationen* die Warenbestandsinformationen zu folgenden Marktplätzen visualisieren:

* Amazon

[IMPORTANT]
.Die Marktplatz-Bestandsinformationen ist neu!
====
Die Marktplatz-Bestandsinformationen ist ein neues Feature. Wir arbeiten mit Hochdruck daran, den Funktionsumfang zu erweitern und dir die Möglichkeit zu geben, den Bestandsexport für weitere Marktplätze zu visualisieren.
====

[#2200]
=== Rohdaten *marketplaceStockMovement* aktivieren

. Öffne das Menü *Einrichtung » plentyBI » Rohdaten*.
. Aktiviere die Rohdaten *marketplaceStockMovement* (icon:toggle-on[role="green"]).
. *Speichere* (icon:save[role="green"]) die Einstellung. +


[#2200]
=== Kennzahl *Marktplatz-Bestandsinformationen* erstellen

Um Bestandsinformationen im Dashboard zu visualisieren, erstellst du eine Kennzahl. Du arbeitest zum ersten Mal mit Kennzahlen? Dann solltest du dich zuerst <<business-entscheidungen/plenty-bi/myview-dashboard#, mit den Grundlagen des Dashboards und der Kennzahlen vertraut machen>>.

[TIP]
.Rechte für plentyBI vergeben
====
Benutzer:innen mit Admin-Zugang zu deinem plentymarkets System können alle Kennzahlen einsehen und neue Kennzahlen erstellen. Benutzer:innen mit einem Zugang des Typs *Backend* muss diese Berechtigung erteilt werden. Wie du die Benutzerrechte vergibst, erfährst du auf der Handbuchseite <<business-entscheidungen/plenty-bi/myview-dashboard#300, Dashboard (Beta)>>.
====

Gehe wie unten beschrieben vor, um die Kennzahl *Marktplatz-Bestandsinformationen* zu erstellen.

[.instruction]
Kennzahl *Marktplatz-Bestandsinformationen* erstellen:

. Öffne das Menü *Einrichtung » plentyBI » Kennzahlen*.
. Gib einen Namen für die Kennzahl an.
. Wähle aus der Dropdown-Liste *Kennzahl* die Option *Marktplatz-Bestandsinformationen*.
. *_Optional:_* Gib einen Kommentar zur Kennzahl ein.
. Klicke im Bereich *Filter* auf *Bedingung hinzufügen*. +
→ Ein Filter mit Und-Bedingung wird hinzugefügt.
. Wähle aus der Dropdown-Liste *Herkunft* die Option *Herkunft*.
. Aktiviere in der Liste der Herkünfte die Option *Amazon*.
. Speichere icon:save[set=plenty] die Einstellungen. +
→ Die Kennzahl kann im Dashboard angezeigt werden.
