[.instruction]
Katalog erstellen:

. Öffne das Menü *Daten » Kataloge*. +
*_Hinweis:_* Das Menü *Daten » Kataloge* ist erst sichtbar, wenn du ein Plugin installierst, das ein Katalog-Template verfügbar macht.
. Öffne das Menü *Daten » Kataloge*.
. Klicke auf *Katalog erstellen*.
. Gib einen Namen für den Katalog ein.
. Wähle das Katalog-Template *{catalogue-template-name}* aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Katalog wird erstellt. +
→ Der Katalog wird zur weiteren Bearbeitung geöffnet.

[#datenfelder-verknüpfen]
=== Datenfelder im Katalog verknüpfen

Nachdem du einen Katalog erstellt hast, verknüpfst du die Datenfelder des Marktplatzes mit in plentymarkets gespeicherten Artikeldaten. Weitere Informationen zu den plentymarkets Datenquellen, die du zuordnen kannst, findest du unter <<daten/daten-exportieren/kataloge-verwalten#_datenquellen_zuordnen, Datenquellen zuordnen>>.

[.instruction]
Datenfelder im Katalog verknüpfen:

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet. +
→ Links werden die Datenfelder des Marktplatzes angezeigt. +
*_Tipp:_* Pflichtfelder sind mit Sternchen gekennzeichnet.
. Wähle für die Datenfelder des Marktplatzes eine plentymarkets Datenquelle aus der Dropdown-Liste.
. Um einem Datenfeld eine weitere plentmarkets Datenquelle zuzuordnen, klicke auf *Quelle hinzufügen*. +
→ Eine neue Zeile wird eingeblendet. +
*_Hinweis:_* Auch wenn du einem Datenfeld mehr als eine Datenquelle zuordnest, wird nur ein Wert übertragen. Die Daten werden in der Reihenfolge der Zuordnung geprüft. Wenn also das erste Datenfeld keinen Wert liefert, wird das zweite Datenfeld übertragen usw.
. Nimm alle gewünschten Zuordnungen vor. +
*_Hinweis:_* Alle mit * gekennzeichneten Pflichtfelder müssen mit einer plentymarkets Datenquelle verknüpft werden.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Werte verknüpfen
====
In den Feldern im unteren Bereich der Katalog-Templates verknüpfst du von XXXX vorgegebene Werte mit plentymarktes Datenquellen. Für diese Felder werden die Benennungen von XXXX an den Marktplatz übermittelt.
====

=== _Beispiel:_ Feld "{beispiel-feld}" verknüpfen

Im Folgenden wird beispielhaft beschrieben, wie du das Feld *{beispiel-feld}* mit Artikeldaten aus plentymarkets verknüpfst.

. Öffne das Menü *Daten » Kataloge*.
. Klicke auf den Katalog. +
→ Der Katalog wird geöffnet.
. Wähle für das Katalogfeld *{beispiel-feld}* eine plentymarkets Datenquelle aus der Dropdown-Liste, zum Beispiel *Artikeltext > Name 1, Name 2, Name 3*, die auf dem Marktplatz als {beispiel-feld} angezeigt werden soll.
. Nimm die weiteren Zuordnungen analog vor. Verknüpfe mindestens alle Pflichtfelder.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.SKU verknüpfen
====
Wir empfehlen, das Datenfeld *SKU* mit der plentymarkets Datenquelle *Varianten-ID* zu verknüpfen, da die Varianten-ID der Variante eindeutig zugeordnet ist.
====

[TIP]
.Eigenschaften verwenden
====
Verwende <<artikel/artikel-verwalten#3000, Eigenschaften>>, um Werte für Datenfelder zu übergeben, für die es keine Artikeldaten in plentymarkets gibt.
====

[#quellen-verknuepfen]
== XXXIm Katalog erstellte Quellen mit Varianten verknüpfen

Wenn du im Assistenten die Optionen *Verkaufspreis anlegen*, *Barcode anlegen* und/oder *Eigenschaft anlegen* gewählt hast, erstellt der Assistent diese Eigenschaften, Verkaufspreise und/oder Barcodes automatisch. Diese neu erstellten Quellen musst du nun noch mit den Varianten verknüpfen, die zu OTTO Market exportiert werden sollen. Wie das geht, ist im Bereich *Artikel* des Handbuchs beschrieben:

* Wie du Verkaufspreise mit Varianten verknüpfst, erfährst du im Kapitel <<artikel/artikel-verwalten#240, Verkaufspreise verknüpfen>>.
* Wie du Barcodes mit Varianten verknüpfst, erfährst du im Kapitel <<artikel/artikel-verwalten#250, Barcodes verknüpfen>>.
* Wie du Eigenschaften mit Varianten verknüpfst, erfährst du im Kapitel <<artikel/artikel-verwalten#4900, Eigenschaft verknüpfen und Wert speichern>>. +
*_Tipp:_* Eigenschaften, die du über den Assistenten erstellst, werden automatisch im Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen* zu der Gruppe *OTTO Market* hinzugefügt. Öffne diese Gruppe um zu sehen, welche neuen Eigenschaften verknüpft werden müssen.

////
:catalogue-template-name: xxxx
:beispiel-feld: ddddd

include::../../_textblocks/instructions/katalog-erstellen.adoc[]
////
