Mit dem Assistenten *Kataloge erstellen - OTTO Market* erstellst du auf einfache Weise einen Katalog für den Export deiner Variantendaten zu OTTO Market. Du gibst dem Katalog einen eindeutigen Namen und entscheidest, für welche OTTO-Kategoriegruppe der Katalog gelten soll. Außerdem verknüpfst du im Assistenten schon bestimmte Pflichtfelder.

[TIP]
.Ein Katalog pro OTTO-Kategoriegruppe
====
Für jede OTTO-Kategoriegruppe benötigst du einen eigenen Katalog.
====

[.instruction]
Katalog mit dem Assistenten erstellen:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Kataloge erstellen - OTTO Market*.
. Folge den Anweisungen auf dem Bildschirm. +
*_Tipp:_* Wenn du zusätzliche Informationen zu einer der Optionen benötigst, klappe die Info-Box unten auf (icon:chevron-down[role="darkGrey"]).
. Überprüfe die Zusammenfassung auf mögliche Fehler.
. Wenn alles passt, klicke auf icon:check[role="green"] *Abschließen*. +
→ Der Katalog wird erstellt.
. Öffne den Katalog im Menü *Daten » Kataloge*, um <<#600, weitere Datenfelder>> zu verknüpfen.

[.collapseBox]
Schritt: *Name und Kategoriegruppe*
--
[[table-otto-market-catalogue-assistant]]
[width="100%"]
[cols="1,2"]
|======
| Einstellung | Erläuterung

| *Gib einen Namen für den Katalog ein.*
a| Name für den Katalog eingeben.

| *Für welche OTTO-Kategoriegruppe möchtest du einen Katalog erstellen?*
| Eine OTTO-Kategoriegruppe aus der Dropdown-Liste wählen.
|======
--

[.collapseBox]
Schritt: *Pflichtfelder*
--
In diesem Schritt des Assistenten legst du fest, welche in plentymarkets gespeicherten Variantendaten an den Marktplatz gesendet werden sollen. Dazu verknüpfst du jedes Pflichtfeld des Marktplatzes mit der Quelle in plentymarkets, die die Daten enthält, die du an den Marktplatz exportieren möchtest. Welche Datenfelder Pflichtfelder sind, ist abhängig vom Marktplatz und von der Produktkategorie. Statt eine bestehende Datenquelle zu verknüpfen, kannst du für einige Datenfelder auch eine neue Datenquelle erstellen.

* *Parent-SKU*: Wähle aus der Dropdown-Liste, welches Datenfeld als Parent-SKU übertragen werden soll.

* *SKU*: Wähle aus der Dropdown-Liste, welches Datenfeld als SKU übertragen werden soll.

* *Datenquelle wählen*: Eine bereits in plentymarkets vorhandene Datenquelle wird an OTTO Market exportiert. Die Datenquelle aus der Dropdown-Liste *Datenquelle* wählen. +
*_Hinweis:_* Die Verknüpfungen, die du vornimmst, werden nicht auf Sinnhaftigkeit geprüft. Prüfe deshalb die Verknüpfungen sorgfältig, bevor du den Export startest.

* *Eigenschaft anlegen*: Erstellt eine Eigenschaft und verknüpft diese Eigenschaft mit dem Datenfeld. Diese automatisch erstellte Eigenschaft wird im Menü <<willkommen/allgemeine-funktionen/eigenschaften#tabelle-eigenschaft-erstellen, Einrichtung » Einstellungen » Eigenschaften » Konfiguration>> gespeichert. +
 +
Die automatisch erstellte Eigenschaft hat die folgenden Einstellungen: +

  ** Bereich = Artikel
  ** Eigenschaftstyp = _je nach Anforderung des Marktplatzes_
  ** Sprache = Deutsch
  ** Name = Feld der OTTO-Kategoriegruppe
  ** Gruppe = OTTO Market
  ** Herkunft = (xxxleer)

* *Verkaufspreis anlegen*: Erstellt einen neuen Verkaufspreis und verknüpft diesen Verkaufspreis mit dem Datenfeld. Dieser automatisch erstellte Verkaufspreis kann im Menü <<artikel/einstellungen/preise#400, Einrichtung » Artikel » Verkaufspreise>> geprüft und bearbeitet werden. +
 +
Der automatisch erstellte Verkaufspreis hat die folgenden Einstellungen: +

  ** Abo-Intervall = Keins
  ** Interner Name = OTTO Market
  ** Externer Name = OTTO Market
  ** Ab Menge = 1
  ** Live umrechnen = Nein
  ** Währung = Euro
  ** Darstellung = Bei neuem Artikel immer anzeigen
  ** Mandant = Der in den OTTO Market-Grundeinstellungen gewählte Mandant
  ** Klasse = ALLE
  ** Land = Deutschland
  ** Herkunft = ?xxx (im Moment keine)

* *Barcode anlegen*: Erstellt einen Barcode und verknüpft diesen Barcode mit dem Datenfeld. Der automatisch erstellte Barcode kann im Menü <<artikel/einstellungen/barcodes#100, Einrichtung » Artikel » Barcodes>> geprüft und bearbeitet werden.
--

[.collapseBox]
Schritt: *Zusammenfassung*
--
[[table-otto-market-catalogue-assistant]]
[width="100%"]
[cols="1,2"]
|======
| Einstellung | Erläuterung

| Zusammenfassung
| Zeigt eine Zusammenfassung der Katalog-Einstellungen. Einstellungen ausklappen (icon:chevron-down[role="darkGrey"]) und prüfen.

|======
--

[#600]
=== Weitere Datenfelder verknüpfen (nicht im Assistenten)

Mit dem Assistenten verknüpfst du die Pflichtfelder für die gewählte OTTO-Kategoriegruppe. Du kannst aber auch zusätzliche Datenfelder verknüpfen, um noch mehr Informationen zu deinen Produkten an OTTO Market zu übermitteln.

TIP: Verknüpfe die Datenfelder *Marke*, *Versandart* und *Kategorie* mit einer plentymarkets Datenquelle.

[.instruction]
Weitere Datenfelder verknüpfen:

. Öffne das Menü *Daten » Kataloge*. +
→ Eine Liste der Kataloge wird angezeigt.
. Klicke auf den OTTO Market-Katalog. +
→ Der Katalog wird geöffnet. +
→ Links werden die Datenfelder des Marktplatzes angezeigt. +
*_Tipp:_* Pflichtfelder sind mit einem Sternchen gekennzeichnet.
. Wähle für die gewünschten Datenfelder des Marktplatzes eine plentymarkets Datenquelle aus der Dropdown-Liste.
. Um einem Datenfeld eine weitere plentymarkets Datenquelle zuzuordnen, klicke auf *Quelle hinzufügen*. +
→ Eine neue Zeile wird eingeblendet. +
*_Hinweis:_* Auch wenn du einem Datenfeld mehr als eine Datenquelle zuordnest, wird nur ein Wert übertragen. Die Daten werden in der Reihenfolge der Zuordnung geprüft. Wenn also das erste Datenfeld keinen Wert liefert, wird das zweite Datenfeld übertragen usw.
. Nimm alle gewünschten Zuordnungen vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
