Mit dem Assistenten *Kataloge erstellen - OTTO Market* erstellst du auf einfache Weise einen Katalog für den Export deiner Variantendaten zu OTTO Market. Du gibst dem Katalog einen eindeutigen Namen und entscheidest, für welche OTTO-Kategoriegruppe der Katalog gelten soll. Außerdem verknüpfst du im Assistenten alle Pflichtfelder.

[TIP]
.Ein Katalog pro OTTO-Kategoriegruppe
====
Für jede OTTO-Kategoriegruppe benötigst du einen eigenen Katalog.
====

[.instruction]
Katalog mit dem Assistenten erstellen:

. Öffne das Menü *Einrichtung » Assistenten » Omni-Channel*.
. Klicke auf den Assistenten *Kataloge erstellen - OTTO Market*.
. Folge den Anweisungen auf dem Bildschirm. +
*_Tipp:_* Wenn du zusätzliche Informationen zu einer der Optionen benötigst, klappe die Info-Box unten auf (icon:chevron-down[role="darkGrey"]).
. Überprüfe die Zusammenfassung auf mögliche Fehler.
. Wenn alles passt, klicke auf icon:check[role="green"] *Abschließen*. +
→ Der Katalog wird erstellt.
. *_Optional:_* Öffne den Katalog im Menü *Daten » Kataloge*, um weitere <<#600, optionale Felder>> zu verknüpfen.

[.collapseBox]
.Informationen zu den Optionen des Assistenten
--
[[table-otto-market-catalogue-assistant]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Schritt: *Name und Kategoriegruppe*

| *Gib einen Namen für den Katalog ein. *
a| Name für den Katalog eingeben.
// Bei Amazon wird automatisch ein Name erstellt.

| *Für welche OTTO-Kategoriegruppe möchtest du einen Katalog erstellen?*
| Eine OTTO-Kategoriegruppe aus der Dropdown-Liste wählen. +
// xxx

2+|Schritt: *Pflichtfelder*

| *Möchtest du für folgende Felder eine bestehende Datenquelle verknüpfen oder eine neue Datenquelle als Eigenschaft anlegen?*
a| plentymarkets Datenfelder mit den Datenfeldern der gewählten OTTO-Kategoriegruppe verknüpfen. Alle Datenfelder in diesem Schritt sind Pflichtfelder und müssen verknüpft werden.

* *Parent-SKU* =
* *SKU* =

* *Eigenschaft anlegen* = Erstellt eine neue Eigenschaft und verknüpft diese Eigenschaft mit dem Datenfeld. Die automatisch erstellten Eigenschaften werden im Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen* in der Gruppe *Amazon Catalog* zusammengefasst dargestellt. Als Name für die Eigenschaft wird das Feld der Flatfile vergeben. +
* *Verkaufspreis anlegen* = Erstellt einen neuen Verkaufspreis und verknüpft diesen Verkaufspreis mit dem Datenfeld. Die automatisch erstellten Verkaufspreise können im Menü *Einrichtung » Artikel » Verkaufspreise* geprüft und bearbeitet werden. Der Name des Verkaufspreises hat das Präfix "Amazon Katalog". +
* *Barcode anlegen* = Erstellt einen neuen Barcode und verknüpft diesen Barcode mit dem Datenfeld. Die automatisch erstellten Barcodes können im Menü *Einrichtung » Artikel » Barcodes* geprüft und bearbeitet werden. +
* *Datenquelle wählen* = Ein Datenfeld in plentymarkets wird an OTTO Market übertragen. Das Datenfeld aus der Dropdown-Liste *Quelle wählen* wählen. +
*_Hinweis:_* Felder mit der Option *Datenquelle manuell verknüpfen* können nicht automatisch im Assistenten verknüpft werden. Diese Felder müssen also manuell im Katalog verknüpfen werden, nachdem der Katalog erstellt wurde.
* *Datenquelle manuell verknüpfen* = Diese Felder werden nicht automatisch im Assistenten verknüpft und müssen manuell im Katalog verknüpfen werden, nachdem der Katalog angelegt wurde.

//*_Tipp:_* Wenn du schon einmal einen Katalog erstellt hast, werden beim nächsten Katalog Quellen als Vorschläge eingeblendet. Für jedes Feld wird die Quelle vorgeschlagen, die du bisher am häufigsten mit dem Feld verknüpft hast.

2+|Schritt: Zusammenfassung

| Zusammenfassung
| Zeigt eine Zusammenfassung der Katalog-Einstellungen. Einstellungen ausklappen (icon:chevron-down[role="darkGrey"]) und prüfen.
|====
--

Verknüpfe im Menü Daten » Kataloge weitere Datenfelder im Katalog, nachdem du den Assistenten abgeschlossen hast. Um eine korrekte Übertragung deiner Artikeldaten sicherzustellen, solltest du die Felder Marke, Versandart und Kategorie mit einer Datenquelle verknüpfen. Für diese Felder werden die Werte von OTTO an den Marktplatz übertragen. Mit optionalen Datenfeldern, die nicht mit einem * gekennzeichnet sind, kannst du deine Artikel detaillierter beschreiben. Dadurch erhöhst du die Chance, deine Artikel zu verkaufen.

[#600]
=== Optionale Datenfelder verknüpfen (nicht im Assistenten)

Mit dem Assistenten verknüpfst du alle Pflichtfelder für die gewählte OTTO-Kategoriegruppe. Du kannst aber auch zusätzliche Felder verknüpfen, um noch mehr Informationen zu deinen Produkten an OTTO Market zu übermitteln.

[.instruction]
Optionale Datenfelder verknüpfen:

. Öffne das Menü *Daten » Kataloge*. +
→ Eine Liste der Kataloge wird angezeigt.
. Klicke auf den OTTO Market-Katalog. +
→ Der Katalog wird geöffnet. +
→ Links werden die Datenfelder des Marktplatzes angezeigt. +
*_Tipp:_* Pflichtfelder sind mit Sternchen gekennzeichnet. Diese Pflichtfelder hast du bereits im Assistenten *Kataloge erstellen - OTTO Market* verknüpft.
. Wähle für die gewünschten Datenfelder des Marktplatzes eine plentymarkets Datenquelle aus der Dropdown-Liste.
. Um einem Datenfeld eine weitere plentymarkets Datenquelle zuzuordnen, klicke auf *Quelle hinzufügen*. +
→ Eine neue Zeile wird eingeblendet. +
*_Hinweis:_* Auch wenn du einem Datenfeld mehr als eine Datenquelle zuordnest, wird nur ein Wert übertragen. Die Daten werden in der Reihenfolge der Zuordnung geprüft. Wenn also das erste Datenfeld keinen Wert liefert, wird das zweite Datenfeld übertragen usw.
. Nimm alle gewünschten Zuordnungen vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
