Varianten, die du auf {market-availability} verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[.tabs]
====
Für eine Variante::
+
--


[.instruction]
Eine Variante für {market-availability} verfügbar machen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Tab: Varianten-ID » Tab: Einstellungen*.
. Öffne die Variante, die du auf {market-availability} verkaufen möchtest. +
*_Tipp:_* Um alle Varianten eines Artikels auf {market-availability} zu verkaufen, nimm die Einstellungen an der Hauptvariante vor. Die Verfügbarkeit wird dann für alle Varianten des Artikels aktiviert.
. Aktiviere im Bereich *Verfügbarkeit* die Option *Aktiv*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *{option-availability}*.
ifdef::web-api[]
. Aktiviere die Option *Web-API*.
endif::web-api[]
ifdef::idealo-direkt[]
. *_Optional:_* Wenn du idealo Direktkauf nutzen möchtest, aktiviere die Option *idealo Direktkauf*.
endif::idealo-direkt[]
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Variante ist für {market-availability} verfügbar.
ifdef::neckermann-provision[]
. Klicke auf das Tab *Multi-Channel*.
. Wähle ein *Provisionsmodell*.
. Wähle einen *Produkttyp*. +
*_Tipp:_* Informationen zu Provisionsmodellen und Produkttypen erhältst du von Neckermann.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
endif::neckermann-provision[]

--

Per Varianten-Gruppenfunktion::
+
--
Mit der <<artikel/import-export-anlage/anlage/massenbearbeitung#100, Varianten-Gruppenfunktion>> bearbeitest du mehrere Varianten gleichzeitig. Dabei wählst du die zu bearbeitenden Varianten direkt aus.

[.instruction]
Mehrere Varianten per Varianten-Gruppenfunktion für {market-availability} verfügbar machen:

include::../../../artikel/import-export-anlage/anlage/massenbearbeitung.adoc[tag=varianten-gruppenfunktion]

. Navigiere zum Bereich *Marktplatz-Verfügbarkeit*.
. Aktiviere das Kontrollkästchen links neben der Option *{option-availability}*.
. Aktiviere das Kontrollkästchen rechts neben der Option *{option-availability}*.
. Navigiere zum Bereich *Verfügbarkeit*.
. Aktiviere das Kontrollkästchen links neben der Option *Aktiv*.
. Aktiviere das Kontrollkästchen rechts neben der Option *Aktiv*.
. Klicke auf icon:execute[set=plenty] *Ausführen*, um die Einstellungen an den Varianten vorzunehmen.

--

Per Stapelverarbeitung::
+
--

Mit der <<artikel/import-export-anlage/anlage/massenbearbeitung#400, Stapelverarbeitung>> bearbeitest du mehrere Varianten gleichzeitig. Du verwendest Filter, um die zu bearbeitenden Varianten einzuschränken.

[.instruction]
Mehrere Varianten per Stapelverarbeitung für {market-availability} verfügbar machen:

include::../../../artikel/import-export-anlage/anlage/massenbearbeitung.adoc[tag=varianten-stapelverarbeitung]

. Navigiere zum Bereich *Marktplatz-Verfügbarkeit*.
. Aktiviere das Kontrollkästchen links neben der Option *{option-availability}*.
. Aktiviere das Kontrollkästchen rechts neben der Option *{option-availability}*.
. Navigiere zum Bereich *Verfügbarkeit*.
. Aktiviere das Kontrollkästchen links neben der Option *Aktiv*.
. Aktiviere das Kontrollkästchen rechts neben der Option *Aktiv*.
. Klicke auf icon:execute[set=plenty] *Anwenden*, um die Einstellungen an den Varianten vorzunehmen.

--
====

////
:market-availability: xxxx
:option-availability: xxxx

include::_textblocks/instructions/variantenverfuegbarkeit.adoc[]
////
