Varianten, die du auf {market-availability} verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[TIP]
.Gruppenfunktion oder Stapelverarbeitung nutzen
====
Die Verfügbarkeit für mehrere Varianten bearbeitest du entweder über die <<artikel/import-export-anlage/anlage/massenbearbeitung#100, Varianten-Gruppenfunktion>> oder die <<artikel/import-export-anlage/anlage/massenbearbeitung#400, Stapelverarbeitung>>.
====

[.instruction]
Variantenverfügbarkeit für {market-availability} einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Tab: Varianten-ID » Tab: Einstellungen*.
. Öffne die Variante, die du auf {market-availability} verkaufen möchtest. +
*_Tipp:_* Um alle Varianten eines Artikels auf {market-availability} zu verkaufen, nimm die Einstellungen an der Hauptvariante vor. Die Verfügbarkeit wird dann für alle Varianten des Artikels aktiviert.
. Aktiviere im Bereich *Verfügbarkeit* die Option *Aktiv*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Option *{option-availability}*.
ifdef::web-api[]
. Aktiviere die Option *Web-API*.
endif::web-api[]
ifdef::idealo-direkt[]
. *_Optional:_* Wenn du idealo Direktkauf nutzen möchtest, aktiviere die Option *idealo Direktkauf*.
endif::idealo-direkt[]
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Variante ist für {market-availability} verfügbar.
ifdef::neckermann-provision[]
. Klicke auf das Tab *Multi-Channel*.
. Wähle ein *Provisionsmodell*.
. Wähle einen *Produkttyp*. +
*_Tipp:_* Informationen zu Provisionsmodellen und Produkttypen erhältst du von Neckermann.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
endif::neckermann-provision[]

////
:market-availability: xxxx
:option-availability: xxxx


include::_textblocks/instructions/variantenverfuegbarkeit.adoc[]
////
