= Basic Price Search Engine
:lang: de
include::{includedir}/_header.adoc[]
:author: team-multi-channel
:keywords: Preissuchmaschine, Preise vergleichen, Preissuchmaschine, Export zu Preissuchmaschinen, Preissuchmaschinen, Export zu Preissuchmaschinen, Export für Preissuchmaschinen
:description: Multi-Channel in plentymarkets: Richte die Artikeldatenübertragung mit dem Plugin Basic Price Search Engine in deinem plentymarkets System ein.
:position: 10
:url: maerkte/preisportale/basic-price-search-engine
:id: NXJDHNS

Mit dem Format *Basic Price Search Engine* kannst du Artikeldaten exportieren, um sie an eine beliebige Preissuchmaschine zu übergeben. Du kannst darin Artikeldaten zuordnen, die die meisten Preissuchmaschinen erwarten.

TIP: Mit dem Format *Basic Price Search Engine* exportierst du deine Artikeldaten manuell in eine CSV-Datei, die du bei beliebigen Preissuchmaschinen hochladen kannst. Bevor du den Export einrichtest, kannst du im link::https://marketplace.plentymarkets.com/plugins/sales/preisportale[plentyMarketplace] prüfen, ob plentymarkets oder ein Drittunternehmen eine direkte Schnittstelle zu der Preissuchmaschine anbietet, auf der du deine Produkte verkaufen möchtest.

[#100-0]
== _Möglichkeit 1 (veraltet):_ Export über Exportformat BasicPriceSearchEngine-Plugin

NOTE: Der Elastische Export und die Exportformate werden für den Marktplatz-Export nicht mehr weiterentwickelt. Wir empfehlen dir deshalb, schon jetzt <<#900, Kataloge zu erstellen>>.

Für den Export zu Preissuchmaschinen stand bisher das Exportformat BasicPriceSearchEngine für den Elastischen Export zur Verfügung. Diese Exportmethode ist veraltet und wurde vom Katalogexport abgelöst. Im Moment kannst du das Exportformat BasicPriceSearchEngine immer noch nutzen. Beachte aber, dass die Technologie nicht mehr weiterentwickelt wird und der Support bald ausläuft.

[#100-1]
=== BasicPriceSearchEngine-Plugin installieren und einrichten

:price-search-engine: Preisportalen
:plugin-name: Basic Price Search Engine
:plugin-link: https://marketplace.plentymarkets.com/plugins/channels/preisportale/elasticexportbasicpricesearchengine_4777

include::../_textblocks/explanations/plugin-download.adoc[]

[#100-1]
=== Format BasicPriceSearchEngine-Plugin in plentymarkets einrichten

Mit der Installation dieses Plugins erhältst du das Exportformat *BasicPriceSearchEngine-Plugin*. Mit diesem Exportformat können Artikeldaten über den elastischen Export zu Preisportalen übertragen werden. Um dieses Format für den elastischen Export nutzen zu können, installiere zunächst das Plugin *Elastischer Export* aus dem plentyMarketplace, wenn noch nicht geschehen.

Sobald beide Plugins im deinem System installiert sind, kann das Exportformat *BasicPriceSearchEngine-Plugin* erstellt werden. Weitere Informationen findest du auf der Handbuchseite <<daten/daten-exportieren/elastischer-export#, Elastischer Export>>.

[.instruction]
Neues Exportformat erstellen:

. Öffne das Menü *Daten » Elastischer Export*.
. Klicke auf *Neuer Export* (icon:plus-square[role="green"]).
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<#einstellungen-basic-price-search-engine>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Eine ID für das Exportformat *BasicPriceSearchEngine-Plugin* wird vergeben. +
→ Das Exportformat wird in der Übersicht *Exporte* angezeigt.

In <<#einstellungen-basic-price-search-engine>> findest du spezifische Hinweise zu den Einstellungen, Formateinstellungen und empfohlenen Artikelfiltern für das Exportformat *BasicPriceSearchEngine-Plugin*.

[[einstellungen-basic-price-search-engine]]
.Formateinstellungen für BasicPriceSearchEngine-Plugin
[cols="1,3a"]
|====
| Einstellung | Erläuterung

2+| *Einstellungen*

| *Format*
| *BasicPriceSearchEngine-Plugin* wählen.

| *Bereitstellung*
| *URL* wählen.

| *Dateiname*
| Der Dateiname muss auf *.csv* oder *.txt* enden, damit ein Preisportal oder eine vergleichbare Schnittstelle die Datei erfolgreich importieren kann.

2+| *Artikelfilter*

| *Artikelfilter hinzufügen*
a|Artikelfilter aus der Dropdown-Liste wählen und auf *Hinzufügen* klicken. Standardmäßig sind keine Filter voreingestellt. Es ist möglich, alle Artikelfilter aus der Dropdown-Liste nacheinander hinzuzufügen. +

* *Aktiv* = *Aktiv* wählen. +
* *Märkte* = Eine oder mehrere Auftragsherkünfte wählen. Die gewählten Auftragsherkünfte müssen an der Variante aktiviert sein, damit der Artikel exportiert wird.

2+| *Formateinstellungen*

| *Auftragsherkunft*
|Die Auftragsherkunft wählen, die beim Auftragsimport zugeordnet werden soll.

| *MwSt.-Hinweis*
| Diese Einstellung ist für dieses Format nicht relevant.
|====

[#200]
=== Verfügbare Spalten der Exportdatei

:export-format: BasicPriceSearchEngine-Plugin

include::../../maerkte/_textblocks/instructions/exportdatei-herunterladen.adoc[]

[[spalten-exportdatei-basic-price-search-engine]]
.Verfügbare Spalten der Exportdatei für das Exportformat *BasicPriceSearchEngine-Plugin*
[cols="1,3a"]
|====
| Spaltenbezeichnung | Erläuterung

|article_id
|Die *ID* des Artikels.

|deeplink
|Der *URL-Pfad* des Artikels abhängig von den Formateinstellungen *Mandant*, *Produkt-URL* und *Auftragsherkunft*.

|name
|Entsprechend der Formateinstellung *Artikelname*.

|short_description
|Entsprechend der Formateinstellung *Vorschautext*.

|description
|Entsprechend der Formateinstellung *Beschreibung*.

|article_no
|Die *Variantennummer*.

|producer
|Der *Hersteller* des Artikels. Der *Externe Name* unter *Einrichtung » Artikel » Hersteller* wird bevorzugt, wenn vorhanden.

|model
|Das Modell unter *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Einstellungen » Grundeinstellungen*.

|availability
|Der *Name der Artikelverfügbarkeit* unter *Einrichtung » Artikel » Artikelverfügbarkeit* oder die Übersetzung gemäß der Formateinstellung *Artikelverfügbarkeit überschreiben*.

|ean
|Entsprechend der Formateinstellung *Barcode*.

|isbn
|Entsprechend der Formateinstellung *Barcode*.

|unit
|Die *Einheit* aus den berechneten Grundpreisinformationen.

|price
|Der *Verkaufspreis* der Variante, abhängig der Formateinstellung *Auftragsherkunft*.

|price_old
|Der *Angebotspreis* der Variante, abhängig der Formateinstellung *Auftragsherkunft*.

|weight
|Das *Gewicht* der Variante.

|category1
|Die *erste Kategorieebene der Standardkategorie* für den in den Formateinstellungen definierten *Mandanten*.

|category2
|Die *zweite Kategorieebene der Standardkategorie* für den in den Formateinstellungen definierten *Mandanten*.

|category3
|Die *dritte Kategorieebene der Standardkategorie* für den in den Formateinstellungen definierten *Mandanten*.

|category4
|Die *vierte Kategorieebene der Standardkategorie* für den in den Formateinstellungen definierten *Mandanten*.

|category5
|Die *fünfte Kategorieebene der Standardkategorie* für den in den Formateinstellungen definierten *Mandanten*.

|category6
|Die *sechste Kategorieebene der Standardkategorie* für den in den Formateinstellungen definierten *Mandanten*.

|category_concat
|Der *Kategoriepfad der Standardkategorie* für den in den Formateinstellungen definierten *Mandanten*.

|image_url_preview
|Das *Vorschaubild* des ersten Bildes der Variante.

|image_url
|Das *Bild* des ersten Bildes der Variante.

|shipment_and_handling
|Die am Artikel gespeicherten *Versandkosten*.

|unit_price
|Die *Grundpreisinformation* im Format "Preis / Einheit" (Beispiel: 10.00 EUR / Kilogramm)

|unit_price_value
|Der *Preis* aus den berechneten *Grundpreisinformationen*.

|unit_price_lot
|Der *Inhalt* aus den berechneten *Grundpreisinformationen*.

|variation_id
|Die *Varianten-ID*.
|====

[#100-0]
== _Möglichkeit 2 (empfohlen):_ Export über Katalog-Formate

Mit dem neuen Plugin link:xxxx[Plugin Basic Price Search Engine^]{nbsp}icon:external-link[] machst du deinen Export für Preissuchmaschinen zukunftssicher und flexibler denn je.

[#170]
=== Plugin installieren und bereitstellen

Um Artikeldaten über ein Katalog-Format exportieren zu können, installiere zunächst das Plugin link:xxxx[Basic Price Search Engine^]{nbsp}icon:external-link[] in deinem plentymarkets System. Dieses Plugin und viele andere Plugins findest du im link:https://marketplace.plentymarkets.com/[plentyMarketplace^]{nbsp}icon:external-link[].

:plugin: Basic Price Search Engine
include::../_textblocks/instructions/plugin-installation.adoc[]

[#902]
=== Katalog erstellen

Artikeldaten werden über ein Marktplatz-Format exportiert. Um deine Artikel zu einem Preisportal zu exportieren, erstellst du im Menü *Daten » Kataloge* einen Katalog. Ordne dann im Marktplatz-Format die vom Katalog vorgegebenen Marktplatz-Datenfelder den in plentymarkets gespeicherten Artikeldaten zu.

* Du arbeitest zum ersten Mal mit den Katalogen? Dann mache dich zuerst <<daten/daten-exportieren/kataloge-verwalten#, mit dem Prinzip der Kataloge vertraut>>.

:catalogue-template-name: Basic Price Search Engine
:catalogue-plugin:

include::../_textblocks/instructions/katalog-erstellen.adoc[]

[#filter-export]
=== Filter für Export setzen

Setze nun Filter, um nur bestimmte Artikel für das Preisportal zu exportieren.

* Wie du Filter setzt, erfährst du auf der Seite <<daten/daten-exportieren/kataloge-verwalten#, Kataloge verwalten>>.

[#data-field-mappings]
=== Datenfelder im Katalog zuordnen

Ordne nun die Marktplatz-Datenfelder im Katalog den in plentymarkets gespeicherten Artikeldaten zu.

include::../_textblocks/instructions/katalog-datenfelder-zuordnen.adoc[]

[#recommended-mappings]
=== Empfehlungen für Datenfeld-Zuordnungen

Um dich beim Erstellen eines Katalogs zu unterstützen, haben wir eine Liste mit empfohlenen Datenfeld-Zuordnungen zusammengestellt. Beachte, dass es sich hierbei nur um Empfehlungen handelt. Je nachdem, wie du deine Artikeldaten pflegst, können andere Zuordnungen sinnvoller sein als die hier gegebenen Empfehlungen.

[.collapseBox]
.Liste mit empfohlenen Datenfeld-Zuordnungen
--
include::_../textblocks/catalogue-mappings/basicpricesearchengine-recommended-mappings.adoc[]
--

[#activate-catalogue]
=== Katalog in CSV-Datei exportieren

Anders als bei anderen Marktplatz-Formaten kannst du für dieses Format nicht einfach den Katalog aktivieren und so den Export starten. Stattdessen exportierst du das Marktplatz-Format manuell in eine CSV-Datei und reichst diese Datei dann auch manuell an das Marktplatz weiter.

* Wie du Katalogdaten manuell exportierst, erfährst du auf der Seite <<daten/daten-exportieren/kataloge-verwalten#260, Kataloge verwalten>>.
