= CMS
:lang: en
include::{includedir}/_header.adoc[]
:position: 50
:url: online-store/online-store/cms
:id: 7PV0XAH

[IMPORTANT]
.The new *Ceres* online store
====
As of now, online store projects are based on the new online store plugin  <<omni-channel/online-store/setting-up-ceres#, Ceres>>. The *Ceres* store uses the latest and future-proof <<basics/first-steps/plugins#, plugin technology>>. Ceres can be customised easily and extended by additional plugins from the link:https://marketplace.plentymarkets.com/en/[plentyMarketplace^].

Online stores that have been created on the basis of the old CMS will be maintained during the transition period. However, no new features will be developed for the old CMS. We recommend to use the new *Ceres* online store for all future online store projects.

====

==  Content of this chapter

This chapter teaches you how to arrange your online store and customize its design to meet your needs. For further information, refer to the <<omni-channel/online-store/setting-up-clients/cms#web-design, Web design>> section. +
The CMS chapter also includes information about working with the <<omni-channel/online-store/setting-up-clients/cms#image-gallery, image gallery>>. Use the image gallery to upload images that should be displayed in your online store. Images can be grouped together there and managed in folders.

Use the <<omni-channel/online-store/setting-up-clients/cms#webspace, Webspace tool>> to save elements for your design, e.g. images, logos or JavaScript files. Elements are managed there on the file level.

The <<omni-channel/online-store/setting-up-clients/cms#documents, Documents>> page shows you another way to make files available to your customers. Here you will learn how to upload documents and link them to emails.

The <<omni-channel/online-store/setting-up-clients/cms#blog-weblog, Blog>> page teaches you how to set up a blog in your online store.

The <<omni-channel/online-store/setting-up-clients/cms#faqs, FAQ>> page shows you how to set up a list of *Frequently Asked Questions* in your online store.

This chapter also teaches you how to configure <<crm/sending-newsletters#, newsletters>> that are sent automatically and that help you reach a wide range of potential customers.

==  Web design in plentymarkets

This section teaches you how to work with the integrated *Content Management System*. It shows you how to edit *templates* and thus customize the design for your online store. Furthermore, you will learn how to use wildcard characters to insert content into your online store. Wildcard characters make it possible to edit the content dynamically. For example, you can use wildcard characters to display item prices and availabilities. Use <<omni-channel/online-store/setting-up-clients/cms-syntax#basics-if, if queries>> to make case-by-case decisions. Procedures will then be carried out on an if-then basis.

Format your online store with *CSS* and make changes to the design with only a few clicks of the mouse.

For further information, refer to the <<omni-channel/online-store/setting-up-clients/cms#web-design, Web design>> page of the manual.

==  Direct access to important pages of the manual

* <<omni-channel/online-store/setting-up-clients/cms#web-design, Web design>>
* <<omni-channel/online-store/setting-up-clients/cms#web-design-user-interface, User interface>>
* <<omni-channel/online-store/setting-up-clients/cms#web-design-basic-information-about-syntax, Basic information about syntax>>
* <<omni-channel/online-store/setting-up-clients/cms-syntax#basics-if, if queries>>
* <<omni-channel/online-store/setting-up-clients/cms#web-design-basic-information-about-syntax-displaying-lists, Displaying lists>>
* <<omni-channel/online-store/setting-up-clients/cms#web-design-editing-the-web-design, Editing the web design>>
* <<omni-channel/online-store/setting-up-clients/cms#best-practice-ssl-encryption, SSL encryption>>
* <<omni-channel/online-store/setting-up-clients/cms-syntax#web-design-pagedesign-link-ajaxbasket, Shopping cart with Ajax>>


[#settings.adoc]
include::_cms/settings.adoc[leveloffset=1]

[#settings-forms.adoc]
include::_cms/settings/forms.adoc[leveloffset=2]

[#settings-rss.adoc]
include::_cms/settings/rss.adoc[leveloffset=2]

[#settings-item-gallery.adoc]
include::_cms/settings/item-gallery.adoc[leveloffset=2]

[#web-design.adoc]
include::_cms/web-design.adoc[leveloffset=1]

[#web-design-user-interface.adoc]
include::_cms/web-design/user-interface.adoc[leveloffset=2]

[#web-design-basic-information-about-syntax.adoc]
include::_cms/web-design/basic-information-about-syntax.adoc[leveloffset=2]

[#web-design-basic-information-about-syntax-displaying-lists.adoc]
include::_cms/web-design/basic-information-about-syntax/displaying-lists.adoc[leveloffset=3]

[#web-design-basic-information-about-syntax-page-structure.adoc]
include::_cms/web-design/basic-information-about-syntax/page-structure.adoc[leveloffset=3]

[#web-design-basic-information-about-syntax-jquery.adoc]
include::_cms/web-design/basic-information-about-syntax/jquery.adoc[leveloffset=3]

[#web-design-tools.adoc]
include::_cms/web-design/tools.adoc[leveloffset=2]

[#web-design-tools-editor.adoc]
include::_cms/web-design/tools/editor.adoc[leveloffset=3]

[#web-design-tools-syntax-editor.adoc]
include::_cms/web-design/tools/syntax-editor.adoc[leveloffset=3]

[#web-design-tools-inline-editor.adoc]
include::_cms/web-design/tools/inline-editor.adoc[leveloffset=3]

[#web-design-editing-the-web-design.adoc]
include::_cms/web-design/editing-the-web-design.adoc[leveloffset=2]

[#web-design-editing-the-web-design-pagedesign.adoc]
include::_cms/web-design/editing-the-web-design/pagedesign.adoc[leveloffset=3]

[#web-design-editing-the-web-design-itemview.adoc]
include::_cms/web-design/editing-the-web-design/itemview.adoc[leveloffset=3]

[#web-design-editing-the-web-design-itemview-dimension-input.adoc]
include::_cms/web-design/editing-the-web-design/itemview/dimension-input.adoc[leveloffset=4]

[#web-design-editing-the-web-design-misc.adoc]
include::_cms/web-design/editing-the-web-design/misc.adoc[leveloffset=3]

[#web-design-editing-the-web-design-order-process.adoc]
include::_cms/web-design/editing-the-web-design/order-process.adoc[leveloffset=3]

[#web-design-editing-the-web-design-order-process-shopping-cart.adoc]
include::_cms/web-design/editing-the-web-design/order-process/shopping-cart.adoc[leveloffset=4]

[#web-design-editing-the-web-design-order-process-individual-order-process.adoc]
include::_cms/web-design/editing-the-web-design/order-process/individual-order-process.adoc[leveloffset=4]

[#web-design-editing-the-web-design-order-process-checkout.adoc]
include::_cms/web-design/editing-the-web-design/order-process/checkout.adoc[leveloffset=4]

[#web-design-editing-the-web-design-order-process-dhl-postfinder.adoc]
include::_cms/web-design/editing-the-web-design/order-process/dhl-postfinder.adoc[leveloffset=4]

[#web-design-editing-the-web-design-order-process-order-confirmation.adoc]
include::_cms/web-design/editing-the-web-design/order-process/order-confirmation.adoc[leveloffset=4]

[#web-design-editing-the-web-design-my-account.adoc]
include::_cms/web-design/editing-the-web-design/my-account.adoc[leveloffset=3]

[#web-design-editing-the-web-design-buttons.adoc]
include::_cms/web-design/editing-the-web-design/buttons.adoc[leveloffset=3]

[#web-design-editing-the-web-design-buttons-complying-with-the-shopping-cart-solution.adoc]
include::_cms/web-design/editing-the-web-design/buttons/complying-with-the-shopping-cart-solution.adoc[leveloffset=4]

[#web-design-editing-the-web-design-css.adoc]
include::_cms/web-design/editing-the-web-design/css.adoc[leveloffset=3]

[#image-gallery.adoc]
include::_cms/image-gallery.adoc[leveloffset=1]

[#social-bookmarks.adoc]
include::_cms/social-bookmarks.adoc[leveloffset=1]

[#best-practice.adoc]
include::_cms/best-practice.adoc[leveloffset=1]

[#best-practice-ssl-encryption.adoc]
include::_cms/best-practice/ssl-encryption.adoc[leveloffset=2]

[#webspace.adoc]
include::_cms/webspace.adoc[leveloffset=1]

[#blog-weblog.adoc]
include::_cms/blog-weblog.adoc[leveloffset=1]

[#faqs.adoc]
include::_cms/faqs.adoc[leveloffset=1]

[#documents.adoc]
include::_cms/documents.adoc[leveloffset=1]

[#deadlines.adoc]
include::_cms/deadlines.adoc[leveloffset=1]

[#constants.adoc]
include::_cms/constants.adoc[leveloffset=1]

[#search-and-replace.adoc]
include::_cms/search-and-replace.adoc[leveloffset=1]

[#customer-feedback.adoc]
include::_cms/customer-feedback.adoc[leveloffset=1]

[#plentymarkets-cms-library.adoc]
include::_cms/plentymarkets-cms-library.adoc[leveloffset=1]
