= Change history
:lang: en
include::{includedir}/_header.adoc[]
:keywords: change history, history, data history
:description: Learn more about the change history in plentymarkets.
:position: 62
:url: data/change-history
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:id: B499GID

Via the change history in the *Data » Change history* menu, you can track which user changed data of a data record in your system at which time.

Proceed as follows to display the change history.

[.instruction]
Displaying the change history:

. Go to *Data » Change history*.
. Select an option from the drop-down list *Reference type*.
. Enter the reference ID.
. Click on *Search* (icon:search[role="blue"]). +
→ A list of changes with the old and new values, the change date as well as the name and ID of the user who did the changes appears.

By clicking on the line, a window opens which contains further information.

[TIP]
.Currently available reference types
====
The following reference types are currently available in the change history:

* Contact
* Address
* Company
* Configuration of data cleansing
* ShopBooster
====
