= Carrying out data cleansing
:lang: en
include::{includedir}/_header.adoc[]
:keywords: cleansing, data cleansing, data clean-up, data cleanup, data purge, delete automatically, delete addresses, delete unused addresses, delete unused addresses, delete orders, delete change history, delete IP addresses in the order
:description: Learn how to automatically delete data records in your plentymarkets system.
:position: 70


This page of the manual describes how to delete certain data records after a certain time period has expired. You determine this time period in the *System » Settings » Data » Cleansing* menu.

[#100]
== Setting the visibility of the menu for variable users

In order that the *System » Settings » Data » Cleansing* menu is visible for users with the user class *Variable*, the menu must be activated in the user account.

In addition, rights in the *REST API* menu must be activated.

[.instruction]
Setting the visibility of the menu for variable users:

. Go to *System » Settings » User » Accounts*.
. Open the user with the user class *Variable* for whom you would like to activate the visibility of the menu.
. Open the *Right* tab.
. Click on the *Menu* tab.
. Expand the section *Settings » Basic settings » Data*.
. Activate the option *Cleansing*.
. Open the *REST API* tab.
. Expand the section *Data cleansing*.
. Activate the option *Show configuration* and *Save configuration*.
. *Save* the settings.

[#200]
== Entering deletion values

In order that data records are deleted in your plentymarkets system after a certain time period has expired, you must enter values for this time period. To do so, proceed as follows.

[NOTE]
.Further functions will be added to this menu step by step
====
Currently, you can automatically delete unassigned addresses, unused contacts, orders, the change history as well as IP addresses in the order. Step by step, further areas will be added to this menu.
====

[.instruction]
Entering deletion values:

. Go to *System » Settings » Data » Cleansing*.
. Enter a value in the input field. Pay attention to the information given in <<table-settings-data-cleansing>>.
. Activate the toggle button.
. *Save* the settings.


[[table-settings-data-cleansing]]
.Settings in the System » Settings » Data » Cleanup
[cols="1,3"]
|====
|Setting|Explanation

|*Deletion of unused addresses (after days)*
|Enter the number in days. After this time period has expired, unused addresses are automatically deleted from your plentymarkets system. An unused address is an address without any relations to a contact, an order, a POS and a warehouse. +
|*Deletion of unused contacts (after days)*
|Enter the number in days. After this time period has expired, unused contacts are automatically deleted from your plentymarkets system. An unused contact is a contact without incoming items, orders and tickets. +
|*Deletion of orders (after days)*
|Enter the number in days. After this time period has expired, orders are automatically deleted from your plentymarkets system. Orders and documents generated to the order are also deleted. Minimum value: 60 days. +
|*Deletion of Change History (after days)*
|Enter the number in days. After this time period has expired, the <<crm/managing-contacts#5100, change history>> entries are automatically deleted from your plentymarkets system. The Change History logs changes made in the plentymarkets system. Maximum value: 365 days. +
|*Deletion of IP addresses in the order (after days)*
|Enter the number in days. After this time period has expired, the IP address in an order is automatically deleted from your plentymarkets system. +
|====

[IMPORTANT]
.Toggle button
====
Data is only deleted if the toggle button was activated and the settings saved. +
If you do not want to delete the data automatically after the value entered for days, deactivate the toggle button and save this setting again. +
*Exception*: The deletion of the change history is still executed even with deactivated toggle button. The maximum value of 365 days is used.
====

[NOTE]
.Number of data records to be deleted
====
Currently, up to 5,000 data records can be deleted per day. plentymarkets will monitor this behaviour and adjust this to a higher value, if necessary.
====

[#300]
== Automatically deleting tickets

Delete tickets automatically from your ticket system. This setting is not carried out in the *System » Settings » Data » Cleansing* menu, but via the procedure manager in the ticket system in the *System » CRM » Ticket system » Procedures* menu.

Further information about the ticket system as well as an example scenario can be found on the <<crm/using-the-ticket-system#3000, Using the ticket system>> page of the manual.

[#400]
== Viewing the log

All changes that have been made in the *System » Settings » Data » Cleansing* menu are logged in the *Data » Log* menu for a period of 4 weeks: The date and time, the user as well as the old and new values are logged.

For further information about the log, refer to the <<basics/working-with-plentymarkets/datalog#, Data log>> page of the manual.
