= Carrying out data cleansing
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Cleansing, data cleansing, data purge, automatic deletion, deleting addresses, deleting unused addresses, deleting unused contacts, deleting orders, deleting history, deleting IP addresses
:description: Learn how to automatically delete data records in your plentymarkets system.
:position: 50

This page of the manual describes how to delete certain data records after a certain time period has expired. You determine this time period in the *System » System settings » Settings » Data » Cleanup* menu. +


There are 2 main reasons for deleting data using the data cleansing function. According to GDPR regulations, you as a seller are obliged to delete personal data saved in your system. In addition, you can use the data cleansing function to reduce memory usage. For example, this can help if the free memory capacity included in your plentymarkets tariff.

[#100]
== Setting the visibility of the menu for variable users

In order that the *System » System settings » Settings » Data » Cleansing* menu is visible for users with the user class *Variable*, the menu must be activated in the user account.

In addition, rights in the *REST API* menu must be activated.

[.instruction]
Setting the visibility of the menu for variable users:

. Go to *System » System settings » Settings » User » Accounts*.
. Open the user with the user class *Variable* for whom you would like to activate the visibility of the menu.
. Open the *Right* tab.
. Click on the *Menu* tab.
. Expand the section *Settings » Basic settings » Data*.
. Activate the option *Cleansing*.
. Open the *REST API* tab.
. Expand the section *Data cleansing*.
. Activate the option *Show configuration* and *Save configuration*.
. *Save* the settings.

[#200]
== Entering deletion values

In order that data records are deleted in your plentymarkets system after a certain time period has expired, you must enter values for this time period. To do so, proceed as follows.

[NOTE]
.Further functions will be added to this menu step by step
====
Currently, you can automatically delete unassigned addresses, unused contacts, orders, the history and the IP addresses attached to an order. Step by step, further areas will be added to this menu.
====

[.instruction]
Entering deletion values:

. Go to *System » System settings » Settings » Data » Cleanup*.
. Enter a value in the input field. Pay attention to the information given in <<table-settings-data-cleansing>>.
. Activate the toggle button.
. *Save* the settings.

[[table-settings-data-cleansing]]
.Settings in the System » System settings » Settings » Data » Cleanup menu
[cols="1,3"]
|====
|Setting| Explanation

|*Deletion of unused addresses (after days)*
|Enter the number in days. After this time period has expired, unused addresses are automatically deleted from your plentymarkets system. Unused addresses are those addresses that do not have any relation to a contact, an order, a POS or a warehouse. +
|*Deletion of unused contacts (after days)*
|Enter the number in days. After this time period has expired, unused contacts are automatically deleted from your plentymarkets system. Unused contacts are those contacts that do not have any relation to incoming goods, tickets or orders. +
|*Deletion of orders (after days)*
|Enter the number in days. After this time period has expired, orders are automatically deleted from your plentymarkets system. Orders are deleted including the documents belonging to them. Minimum value: 60 days. +
*_Important:_* The data deleted here are relevant for tax purposes that can not be restored. +
*_Note_:* Orders containing a document with the last number of the number range are not deleted until a more recent document has been generated in another order.
|*Deletion of the change history (after days)*
|Enter the number in days. After this time period has expired, entries in the <<crm/managing-contacts#5100, change history>> entries are automatically deleted from your plentymarkets system. The change history logs changes made to the data in your plentymarkets system. Maximum value: 365 days. +
|*Deletion of IP addresses in the order (after days)*
|Enter the number in days. After this time period has expired, IP addresses saved in the order are automatically deleted from your plentymarkets system. +
|====

[IMPORTANT]
.Activate the toggle button
====
Data is only deleted if the toggle button is activated and the settings have been saved. +
If you do not want to delete the data automatically after the number of days entered, deactivate the toggle button and save the settings once again. +
*Exception*: The deletion of the change history still takes place even if the toggle button is deactivated. The maximum value of 365 days is used.
====

[NOTE]
.Number of data records to be deleted
====
Up to 5,000 data records are currently deleted per day. plentymarkets will monitor this behaviour and adjust this value if necessary.
====

[#300]
== Automatically deleting tickets

Delete tickets automatically from your ticket system. This setting is not carried out in the *System » System settings » Settings » Data » Cleanup* menu, but via the procedure manager in the ticket system in the *System » System settings » CRM » Ticket System » System settings » Procedures* menu.

Further information about the ticket system as well as an example scenario can be found on the <<crm/using-the-ticket-system#3000, Using the ticket system>> page of the manual.

[#400]
== Viewing the log

All changes made in the *System » System settings » Settings » Data » Cleanup* menu are saved in the *Data » Log* menu for a period of 4 weeks. The date and time as well as the user who made changes to the values are logged in this menu.

For further information about the log, refer to the <<data/datalog#, Data log>> page of the manual.
