= Carrying out data cleanup
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Cleanup, cleansing, data cleansing, data purge, automatic deletion, deleting addresses, deleting unused addresses, deleting unused contacts, deleting orders, deleting history, deleting IP addresses
:description: Learn how to clean up data automatically in plentymarkets.
:position: 50
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:url: data/data-cleanup
:id: BPZ0VS4

This page of the manual describes how to delete certain data records after a certain time period has expired. You determine this time period in the *Setup » Settings » Data » Cleanup* menu.

There are 2 main reasons for deleting data using the data cleanup function:

* According to GDPR regulations, you as a seller are obliged to delete personal data saved in your system.
* In addition, you can use the data cleanup function to reduce memory usage. For example, this can help if the free memory capacity included in your plentymarkets tariff is exceeded.

[#100]
== Assigning user rights

Users of the type *Back end* can only access limited areas and menus in the plentymarkets back end. Thus, their access to the system is limited. If users of the type *Back end* should be able to work with the data cleanup menu, a user of the type *Admin* has to assign at least the rights listed in the following to users with *Back end* access.

[.instruction]
Assigning user rights for back end users:

. Go to *Setup » Settings » User » Rights » User*.
. Use the search function (icon:search[role="blue"]) and open the user account that should be edited.
. Activate in the *Authorisations* section, the options *Data > Data cleanup > Show data cleanup* and *Data > Data cleanup > Edit data cleanup*.
. *Save* (icon:save[role="green"]) the settings.

[#200]
== Entering deletion values

In order that data records are deleted in your plentymarkets system after a certain time period has expired, you have to enter values for this time period. Proceed as described below.

[NOTE]
.Further functions will be added to this menu step by step
====
Currently, you can automatically delete unassigned addresses, unused contacts, orders, the change history and the IP addresses attached to an order. Step by step, further areas will be added to this menu.
====

[.instruction]
Entering deletion values:

. Go to *Setup » Settings » Data » Cleanup*.
. Enter a value in the input field. Pay attention to the explanations given in <<table-settings-data-cleanup>>.
. Activate the toggle button (icon:toggle-off[role="red"]).
. *Save* (icon:save[role="green"]) the settings. +
→ The data cleanup is activated (icon:toggle-off[role="green"]).

[[table-settings-data-cleanup]]
.Settings in the *Setup » Settings » Data » Cleanup* menu
[cols="1,3"]
|====
|Setting| Explanation

|*Deletion of unused addresses (after days)*
|Enter the number in days. After this time period has expired, unused addresses are automatically deleted from your plentymarkets system. Unused addresses are those addresses that do not have any relation to a contact, an order, a POS or a warehouse. +
*_Note:_* The check for unused data records takes place every day. In this context, the system checks whether there are addresses that have been unused for a time longer than the duration you set. If addresses are unused, these are deleted the next day.

|*Deletion of unused contacts (after days)*
|Enter the number in days. After this time period has expired, unused contacts are automatically deleted from your plentymarkets system. Unused contacts are those contacts that do not have any relation to incoming items, tickets or orders. +
*_Note:_* The check for unused data records takes place every day. In this context, the system checks whether there are contacts that have been unused for a time longer than the duration you set. If contacts are unused, these are deleted the next day.

|*Deletion of orders (after days)*
|Enter the number in days. After this time period has expired, orders are automatically deleted from your plentymarkets system. Orders are deleted including the documents belonging to them. Minimum value: 60 days. +
*_Important:_* The data deleted here are relevant for tax purposes that can not be restored. +
*_Note 1:_* Orders containing a document with the last number of the number range are not deleted until a more recent document has been generated in another order. +
*_Note 2:_* The check for unused data records takes place every day. In this context, the system checks whether there are orders that have been unused for a time longer than the duration you set. If orders are unused, these are deleted the next day.

|*Deletion of the change history (after days)*
|Enter the number in days. After this time period has expired, entries in the <<crm/managing-contacts#5100, change history>> are automatically deleted from your plentymarkets system. The change history logs changes made to the data in your plentymarkets system. Maximum value: 365 days. +
*_Note:_* The check for unused data records takes place every day. In this context, the system checks whether there is data in the change history that has been unused for a time longer than the duration you set. If data in the change history is unused, it is deleted the next day.

|*Deletion of IP addresses in the order (after days)*
|Enter the number in days. After this time period has expired, IP addresses saved in the order are automatically deleted from your plentymarkets system. +
*_Note:_* The check for unused data records takes place every day. In this context, the system checks whether there are IP addresses that have been unused for a time longer than the duration you set. If IP addresses are unused, these are deleted the next day.

|====

[IMPORTANT]
.Activate the toggle button
====
Data is only deleted it the toggle button is activated (= icon:toggle-on[role="green"]) and the settings have been saved. +
If you do not want to delete the data automatically after the number of days entered, deactivate (= icon:toggle-off[role="red"]) the toggle button and save the settings once again. +
*Exception*: The deletion of the change history still takes place even if the toggle button is deactivated. The maximum value of 365 days is used.
====

[NOTE]
.Number of data records to be deleted
====
Up to 5,000 data records are currently deleted per day. plentymarkets will monitor this behaviour and adjust this value if necessary.
====

[#300]
== Automatically deleting tickets

Delete the tickets automatically from your ticket system. This setting is not carried out in the *Setup » Settings » Data » Cleanup* menu, but via the procedure manager in the ticket system in the *Setup » CRM » Ticket system » Procedures* menu.

Further information about the ticket system as well as an example scenario can be found on the <<crm/using-the-ticket-system#3000, Using the ticket system>> page of the manual.

[#400]
== Viewing the log

All changes made in the *Setup » Settings » Data » Cleanup* menu are saved in the *Data » Data log* menu for a period of 30 days. The date and time as well as the user who made changes to the values are logged in this menu.

For further information about the log, refer to the <<data/datalog#, Data log>> page of the manual.
