= Mehrsprachiger Webshop
:lang: de
include::{includedir}/_header.adoc[]
:position: 40


Die Einrichtung eines mehrsprachigen Webshops erfordert einige Schritte in unterschiedlichen Menüs Ihres plentymarkets-Systems, die hier zusammenhängend und systematisch erläutert werden. Die notwendigen Einstellunegn zur Einrichtung eines mehrsprachigen Webshops erkennen Sie an den Themen dieses Kapitels. Die hier beschriebene Reihenfolge kann von Ihnen variiert werden. Jedoch müssen alle Schritte durchgeführt werden.

== Standard-Sprache Ihres Systems

Jedes plentymarkets-System wird in einer Standard-Sprache installiert. Diese Standard-Sprache dient als Standard-Vorauswahl für alle Bereiche Ihres Systems, in denen Informationen mehrsprachig abgespeichert werden können. Dies sind u.a. die Bereiche **Webdesign**, **Kategorien** und **Artikel**.

Nach dem Speichern springt das System jeweils auf diese Standard-Vorauswahl zurück, sodass Sie die Sprache, die Sie bearbeiten möchten, erneut wählen müssen.

== Design auf eine andere Sprache übertragen

Im Menü **CMS** ist es möglich, das Design der Standardsprache Ihres Webshops auf eine andere Sprache zu übertragen. So sind nur noch textliche Anpassungen in der Zielsprache nötig, während der Shop in der Standardsprache gespiegelt wird.



[.instruction]
Design übertragen:

. Öffnen Sie das Menü **CMS » Webdesign**.
. Klicken Sie auf das Icon **Design übertragen**.
. Wählen Sie unter **Quelle** das Design, von dem Eigenschaften übernommen werden sollen, sowie die **Sprache**.
. Wählen Sie unter **Ziel** das Design, auf das die Eigenschaften übertragen werden sollen, und dessen **Sprache**.
. Wählen Sie die Bereiche, die von der Quelle auf das Ziel übertragen werden sollen (Häkchen setzen).
. Klicken Sie auf **Design übertragen**.

Auf diese Weise können aus einem Design in einer Sprache Vorlagen für mehrere Sprachen angelegt werden, die dann nur noch sprachlich angepasst werden müssen. Das Design Ihrer Zweitsprache entspricht jetzt exakt dem Design Ihrer Erstsprache.

[NOTE]
.Anpassung des Layouts
====
Die Anpassung des Layouts an die Sprache, nehmen Sie direkt im entsprechenden Template im Menü **CMS » Webdesign » Layout** vor. Wählen Sie in der oberen Menüleiste zuerst die Sprache und dann links das zu bearbeitende Layout.
====

== Weitere Sprachen aktivieren

Für Ihren Webshop können Sie mehrere Sprachen auswählen und entscheiden, ob Sie den gesamten Shop, oder nur den Bestellvorgang multilingual ausgeben möchten.
Sie können das __**Design**__ und die __**Sprachen**__ im Webshop auch zu einem späteren Zeitpunkt kopieren bzw. aktivieren, z.B. wenn Sie bereits Artikel und Kategorien für die Sprache angelegt haben. Wenn Sie die Sprachen jedoch zu Beginn aktivieren, können Sie den Fortschritt unmittelbar im Webshop überprüfen.


[.instruction]
Weitere Sprachen für den Webshop aktivieren:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Webshop » Multilingualismus**.
. Markieren Sie alle **Sprachen**, die Sie aktivieren möchten (Mehrfachauswahl mit Strg bzw. CMD + Mausklick).
. Wählen Sie bei **Bereich**, ob Sie **Artikel &amp; Layout &amp; Content-Seiten &amp; Bestellvorgang**, also den gesamten Webshop mehrsprachig ausgeben möchten, oder nur den **Bestellvorgang**.
. Klicken Sie auf **Speichern**, um die Einstellungen zu sichern. +
→ Ihr Webshop liegt nun in mehreren Sprachen vor.

Sie können dies überprüfen, indem Sie die URL Ihres Shops in einen Browser eingeben und den ISO-Code für die angelegte Sprache anhängen z.B. __**www.NAME_IHRES_SHOPS.de/en/**__ für Englisch oder auch __**www.NAME_IHRES_SHOPS.de/fr/**__ für Französisch.

Wenn Sie z.B. nur den Bereich **Bestellvorgang** auswählen und die Standard-Sprache Ihres Webshops mit auswählen, hat dies __**keinen Einfluss**__ auf die Standard-Sprache. Der Webshop bleibt in dieser vollständig verfügbar.

== Mehrsprachige Kategorien

In diesem Kapitel wird zunächst erläutert, wie Sie mehrsprachige Kategorien des Typs **Content**, **Artikel** und **Container** anlegen. Dabei wird davon ausgegangen, dass die Kategorien bereits in einer Sprache vorliegen (Standard-Sprache Ihres Shops). +
+
Es gibt grundsätzlich zwei Bearbeitungsmöglichkeiten. Sie können entweder eine mehrsprachige Bearbeitungsansicht wählen oder eine einsprachige. Bei der mehrsprachigen Ansicht haben Sie die Möglichkeit zwei Sprachen parallel zu bearbeiten und sehen die Inhalte einer anderen Sprache, z.B. der Standard-Sprache.

[WARNING]
.Sichtbarkeit im Menü Artikel » Kategorien
====
Damit die Kategorien im Verzeichnisbaum des Menüs **Artikel » Kategorien** erscheinen, müssen Sie in der Standard-Sprache Ihres Systems angelegt werden, d.h. Sie müssen der Kategorie in der __**Standard-Sprache**__ zumindest einen **Seitennamen** geben.
====

=== Einsprachige Ansicht

Eine __**Sprachvariante**__ einer bestehenden Kategorie legen Sie wie im Folgenden beschrieben an.



[.instruction]
Sprachvariante einer bestehenden Kategorie anlegen (einsprachig):

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Klicken Sie im Verzeichnisbaum auf die gewünschte Kategorie. +
→ Die Kategorie öffnet sich.
. Wählen Sie aus dem Dropdown-Menü **Sprache** die Sprache, in der Sie die Kategorie anlegen möchten (z. B. Englisch). +
→ Die Kategorie öffnet sich erneut in die ausgewählte Sprache.
. Bleiben Sie im Tab **Einstellungen** und tragen Sie unter **Name** eine Bezeichnung für die Seite ein.
. Wählen Sie eine **Template-Seite**, eine **Template-Liste**, ein **Template-Produkt** und eine Option zur **Volltextsuche**. Beachten Sie dabei die Einstellungen der Kategorie in der Standard-Sprache.
. Klicken Sie auf **Speichern**. +
→ Die Einträge werden gespeichert und der Pfad der Seite wird angelegt. Er ist in der Zeile **URL** sichtbar.
. Fügen Sie die Inhalte in der betreffenden Sprache ein.
. Klicken Sie auf **Speichern**, um die Einstellungen zu sichern.

=== Mehrsprachige Ansicht

Um eine **Sprachvariante** einer bestehenden Kategorie in der mehrsprachigen Ansicht hinzuzufügen, gehen Sie wie im Folgenden beschrieben vor.



[.instruction]
Sprachvariante einer bestehenden Kategorie anlegen (mehrsprachig):

. Öffnen Sie das Menü **Artikel » Kategorien**.
. Klicken Sie im Verzeichnisbaum auf die gewünschte Kategorie. +
→ Die Kategorie wird geöffnet.
. Klicken Sie auf das Icon **Multilingualität**. +
→ Die mehrsprachige Ansicht der Kategorie wird geöffnet.
. Wählen Sie links und rechts die gewünschte Sprachen.
. Tragen Sie in die Felder **Name**, **URL-Name** und **Meta-Titel** die gewünschten Bezeichnungen ein.
. Tragen Sie die fremdsprachigen Texte und Inhalte in das **Textfeld** ein.
. Klicken Sie auf **Speichern**, um Ihre Einstellungen zu sichern.



Die Startseite liegt jetzt auch auf Englisch vor. Sie können die englische Startseite aufrufen und sich das Ergebnis anschauen, z. B. unter __**www.NAME_IHRES_SHOPS.de/en/**__

== Sprachvariante eines Artikels anlegen

Die __**Standard-Sprache**__ Ihres Systems spielt auch hier eine wichtige Rolle, da die Artikel in der Artikelübersicht nur in der Standard-Sprache angezeigt werden. Außerdem können Sie Artikel, die nicht in der Standard-Sprache Ihres Systems vorliegen, nicht für den Webshop aktivieren. Dies bedeutet, dass jeder Artikel immer zuerst in der Standard-Sprache angelegt werden muss und dann übersetzt werden kann.



[.instruction]
Sprachvariante eines Artikels anlegen:

. Öffnen Sie das Menü **Artikel » Artikel bearbeiten**.
. Öffnen Sie den gewünschten **Artikel**.
. Wechseln Sie in das Tab **Texte**.
. Wählen Sie aus dem Dropdown-Menü **Öffne Sprache**, die von Ihnen gewünschte Sprache.
. Tragen Sie im Feld **Name 1** einen Namen (Übersetzung) für den Artikel in der gewählten Sprache ein.
. Fügen Sie alle weiteren **Texte** hinzu (Beschreibung, Technische Daten etc.).
. Klicken Sie auf **Speichern**, um Ihre Einstellungen zu sichern. +
→ Die Sprachvariante des Artikels wurde erstellt und der Artikel ist im Webshop sichtbar.

Wenn der Artikel im Webshop nicht sichtbar ist überprüfen Sie, ob er im Tab **Verfügbar** für den Webshop auf **sichtbar** gestellt ist und die**Kategorie**, in der er sich befindet, **aktiviert** ist. Diese Einstellungen sind nicht sprachabhängig und gelten für alle Sprachvarianten einer Kategorie bzw. eines Artikels.

Haben Sie den Artikel noch nicht mit einer Kategorie verknüpft, tun Sie dies im Tab **Kategorien** des Artikels. Weitere Details zum Verknüpfen von Artikeln mit Kategorien finden Sie auf der Handbuchseite **<<artikel/artikel-verwalten#300, Kategorien>>**.

== Sprachvariante einer E-Mail-Vorlage einrichten

Alle E-Mails, die über plentymarkets versendet werden, basieren auf **E-Mail-Vorlagen**. Diese werden im Menü **Einstellungen » Mandant (Shop) » Standard » E-Mail » Vorlagen** verwaltet. Sie können die E-Mail-Vorlagen dort lesen und ändern sowie neue Vorlagen erstellen. Ein plentymarkets-System enthält bereits verschiedene vorkonfigurierte E-Mail-Vorlagen.
Je nachdem, in welcher Sprache Ihr Kunde den Webshop nutzt, erhält er die entsprechende __**Sprachvariante**__ der E-Mail-Vorlage.



[.instruction]
Sprachvariante einer bestehenden E-Mail-Vorlage einrichten:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » E-Mail » Vorlagen**.
. Öffnen Sie die gewünschte **E-Mail-Vorlage** z.B. __**Eingangsbestätigung Webshop**__.
. Wechseln Sie in das Tab **E-Mail-Nachricht**.
. Wählen Sie die gewünschte __**Sprache**__ aus dem Dropdown-Menü **Sprache wählen**.
. Tragen Sie einen **Betreff** ein z.B. auf Englisch - Order confirmation. Thanks for shopping at www.NAME_IHRES_SHOPS.de.
. Fügen Sie den entsprechenden Text in das Feld **Inhalt**.
. Klicken Sie auf **Speichern**, um Ihre Einstellungen zu sichern. +
→ Die Sprachvariante der E-Mail-Vorlage wurde erstellt.

Weitere Details zu **Template-Funktionen und -Variablen**, die Sie in E-Mail-Vorlagen verwenden können, finden Sie unter **<<crm/e-mails-versenden#1200, Vorlagen>>**.

Um Ihre E-mail-Vorlagen bei gewählten Events automatisch zu versenden, legen Sie Ereignisaktionen an. Weitere Details zum __**automatischen E-Mail-Versand**__ finden sie auf den Handbuchseiten **<<crm/e-mails-versenden#2300, Automatischer Versand>>** und **<<basics/automatisierung/ereignisaktionen#, Ereignisaktionen>>**.

== Sprachvariante eines PDF-Dokuments anlegen

Damit nicht nur der Webshop mehrsprachig angezeigt wird, sondern auch Dokumente wie Rechnungen, Lieferscheine, Gutschriften etc., in der richtigen Sprache beim Kunden ankommen, können auch Vorlagen mehrsprachig eingerichtet werden.



[.instruction]
Sprachvariante einer bestehenden Dokument-Vorlage einrichten:

. Öffnen Sie das Menü **Einstellungen » Aufträge » Dokumente**.
. Wählen Sie das gewünschte Dokument.
. Wählen Sie oben unter **Sprache** die gewünschte Sprachvariante für das Dokument.
. Nehmen Sie alle Einstellungen wie gewünscht vor.
. Klicken Sie auf **Speichern**. +
→ Die **Sprachvariante** der Dokument-Vorlage wurde erstellt.

Alternativ können Sie auch die Einstellungen einer anderen Sprache und/oder Dokument-Vorlage kopieren und diese anschließend bearbeiten. Dies ist sinnvoll, wenn Sie bereits eine vollständig eingerichtete Dokument-Vorlage in einer Sprache haben. So stellen Sie sicher, dass die Vorlage für die nächste Sprache grundsätzlich gleich aufgebaut ist.
Weitere Details zu diesen Dokumenten und den Einstellungen finden Sie auf der Handbuchseite **<<auftragsabwicklung/auftraege/auftragsdokumente#, Dokumente>>**.

== Template-Funktion für Sprachen ins Design einfügen

Damit Ihre Kunden schnell und einfach von einer Sprache Ihres Webshops in eine andere wechseln können, ist das Einfügen von __**Template-Funktionen**__ in Ihr Webshop-Layout notwendig.
Verwenden Sie hierfür die Template-Funktionen, **Link_Lang("DE") %}**, **Link_Lang("EN") %}**, **Link_Lang("FR") %}** usw.
Je nachdem, zu welchem Zeitpunkt Sie Ihren Kunden den Wechsel ermöglichen wollen, ist eine Einbindung in das entsprechende Layout notwendig. Im folgenden Beispiel wird ein Link im deutschen Seiten-Layout **PageDesignContent** für den englischsprachigen Webshop eingefügt.

[.instruction]
Template-Funktion für Sprachen ins Layout einfügen:

. Öffnen Sie das Menü **CMS » Webdesign**.
. Wählen Sie im Dropdown-Menü **Sprache** die Sprache des Designs, die Sie bearbeiten möchten, z.B. **Deutsch**.
. Wählen Sie links im Verzeichnisbaum das Layout **PageDesignContent**. +
→ Das Layout öffnet sich in der gewählten Sprache.
. Fügen Sie die **Template-Funktion** für die gewünschte Sprache, für Englisch wäre dies **Link_Lang("EN") %}**, an der gewünschten Stelle im Layout ein.
. Klicken Sie auf **Speichern**. +
→ Der Link erscheint im deutschsprachigen Webshop.


Klicken Sie auf den Link, um die Sprache zu wechseln. Weitere Details zum __**Wechsel der Sprache im Webshop**__ finden Sie auf der Handbuchseite **<<omni-channel/online-shop/extras/_sprache#, Spracheinstellungen>>**.
