= Changing from Callisto to Ceres
:lang: en
:keywords: Online store, Client, Standard, Ceres, Plugin, Callisto, Ceres, Change, Transition, HowTo, Productive, Setup, Plugin Sets
:position: 20

In this Best Practice you will learn how to set up a <<omni-channel/online-store/setting-up-ceres#, Ceres>> online store in preview mode, while maintaining the productive operation of your Callisto online store at the same time.

== Creating a new plugin set

In order to set up your Ceres online store without affecting your Callisto store, you will first have to create a new <<basics/first-steps/plugins#30, plugin set>>.

[.instruction]
Creating a new plugin set:

. Go to *Plugins » Plugin Overview*.
. Click on *Create new Set* in the upper left corner. +
→ The window *New Plugin Set* opens.
. Enter a name for the plugin set.
. *Save* the settings. +
→ The plugin set has been created.

[WARNING]
====
The newly created plugin set *must not* be published for a client at this point. If you do publish the plugin set, it will overwrite your Callisto online store.
====

You can now begin to set up your Ceres online store in the newly created plugin set. This will not affect the productive operation of your Callisto store.

== Setting up the plugin set

After you have link:https://marketplace.plentymarkets.com/plugins/templates[purchased^] the plugins *Ceres* and *IO*, you need to *install* and *activate* these plugins for the plugin set you created.

[.instruction]
Setting up the plugin set:

. Go to *Plugins » Plugin Overview*.
. Click on the plugin set you created. +
→ The window *Plugin Set Details* opens.
. Select the option *All* in the search filters *Source*, *Installed* and *Active*.
. Click on *Search*. +
→ All purchased plugins are listed.
. Click on *Install plugin* in the *Action* column in the *Ceres* line. +
→ Das *Install plugin* window opens. +
→ The most current version of the plugin is preselected.
. Click on *Install*.
. Repeat steps 5 and 6 for the plugin *IO*.
. Click on *Save & publish plugins*. +
→ The notification *Deploying Plugin Set* is displayed.

This concludes the preliminary work and you can now begin to set up the Ceres online store. Take a look at the manual chapters <<basics/first-steps/quick-start#570, Quick start>> and <<omni-channel/online-store/setting-up-ceres#20, Setting up Ceres>> to learn how to do this.
In the following you will learn how to test your online store in the preview mode.

== Testing your Ceres online store in preview mode

In order to keep track of your changes in the online store, the *Plugin overview* offers you the option of accessing the store in a preview mode.
Before opening the Ceres online store in preview mode, you should deploy your plugin set one more time via the *Save & publish plugins* button. Please note that this may take a few moments.

[.instruction]
Opening the plugin set in preview mode:

. Go to *Plugins » Plugin overview*.
. Click on the previously created plugin set. +
→ The window *Plugin Set Details* opens.
. Click on *Plugin Set Preview*.
→ The online store opens in a new browser tab with the configurations of the selected plugin set.

[NOTE]
====
Please note that you need to allow <<basics/first-steps/quick-start#70, pop-ups>>, so that the store will open in a new browser tab.
====

== Going live with the Ceres online store

Once you have completed testing your online store in preview mode and you are ready to replace your Callisto store with Ceres, you need to *publish* the plugin set for the relevant client.
If necessary, this link can be reverted. You can return to your old Callisto online store at any time.

[.instruction]
Activating a plugin set for a client:

. Go to *Plugins » Plugin overview*.
. Click on the previously created plugin set. +
→ The window *Plugin Set Details* opens.
. Click on *Publish Plugin Set* in the upper left corner of the interface. +
→ The window  *Activate Sets* opens.
. Select the plugin set you want to publish for the desired client from the drop-down list. +
→ The notification *For webstore X, Plugin Set y is active* is displayed.

Your Ceres online store has now been put in productive operation and replaces your Callisto online store.
