= Setting up Ceres checkout in Callisto online stores
:lang: en
:keywords: Online store, client, Standard, Ceres, Plugin, Checkout, order process, Callisto
:position: 40

You want to use the new checkout in your Callisto online store and benefit from its plugin capabilities and individual customisability? No problem - we’ll guide you through the necessary steps. In case you need professional support for the integration of the Ceres checkout in Callisto, our link:https://marketplace.plentymarkets.com/services/CeresCheckout4Callisto_5475[marketplace^] can lead you in the right direction.

[NOTE]
.First things first:
====
* This Best Practice describes the setup of the Ceres checkout in a Callisto template. Please copy your design first. Do not make modifications to your active layout.
* To use the Ceres checkout, you need the current version of the Ceres and the IO plugins. You can find both on the plentyMarketplace. Both plugins have to be installed and deployed in a plugin set copy.
* In order to use your payment providers and shipping service providers in the Ceres checkout, you will have to load and install the relevant plugins from the link:https://marketplace.plentymarkets.com/plugins/payment[marketplace^]. Please note that there are payment providers that at this pojnt do not offer a plugin alternative and whose services can therefore not be implemented in the Ceres checkout.
====

[IMPORTANT]
.Working in a plugin set copy
====
To ensure that the live operations of your online store are not impaired while testing the Ceres checkout, we recommend that you initially make all of your changes in a plugin set copy. <<online-store/best-practices#copying_a_plugin_set, This best practice>> explains how to create a copy for your plugin sets. Test your changes in the <<plugins/plugin-sets#,preview mode>> before you integrate them into your live online store.
====

[#standard]

== Ceres checkout for Callisto online stores that use the *individual shopping cart* or the *standard order process*

If you operate a Callisto online store that uses the *individual shopping cart* or the *standard order process*, you will have to integrate the Ceres checkout sooner: The individual shopping cart will be deactivated on 01 March 2019; the standard order process will be deactivated on 01 June 2019. <<online-store/best-practices#bp-ceres-EOL, This chapter>> explains how you find out which order process you are currently using. +

If you follow the step-by-step instruction below, you can integrate the Ceres checkout in your Callisto online store in a few simple steps.

=== Managing routes
Ceres online stores use the logic of the plugin IO. In order to use the checkout with all the correct routes, proceed as follows:

[.instruction]
Carry out settings in the IO plugin:

. Go to *Plugins » Plugin overview*.
. Click on *IO*. +
→ The plugin opens.
. Click on *Configuration* in the directory tree.
. Click on the *Routing* tab.
. Deactivate the checkbox next to *Enable routes*. +
→ All routes are deactivated.
. Activate the routes */basket*, */checkout*, */confirmation*, */login*, */register*, */password-reset*, as well as */place-order* and */execute-payment*.
. *Save* the settings.

[IMPORTANT]
.Using the ShopBuilder in Callisto online stores that use the Ceres checkout
====
If you operate a Callisto online store with Ceres checkout and want to use the <<online-store/shop-builder#, ShopBuilder>>, you also need to activate the first route */*. Otherwise, the ShopBuilder will not load in your back end. Please note that this will overwrite your Callisto homepage. We recommend that you always make changes in a plugin set copy. After you have made changes, you can deactivate the homepage route */* again.
====

[.instruction]
Carry out settings in the Ceres plugin:

. Go to *Plugins » Plugin overview*.
. Click on *Ceres*. +
→ The plugin opens.
. Click on *Configuration* in the directory tree. +
→ The *Global* tab is pre-selected.
. Click on *Enable Callisto route pattern for items*. +
→ The Callisto routes are activated.
. *Save* the settings. +
→ The Ceres checkout is now active in your Callisto online store.

For the majority of users, this concludes the steps necessary to implement the Ceres checkout in Callisto stores. <<plugins/new-plugins#, Purchase and install>> the relevant plugins for payment providers and shipping service providers in your plugin set. You should test your new checkout thoroughly before you activate the plugin set for your client. +

Users who have made additional adjustments to their layout need to check whether any other links on their website lead customers to the checkout. These links have to be changed so that they link to the route */checkout*. We are not able to intercept all individual changes to the layout, since these can vary from user to user.

The visual design of the Ceres checkout will differ from your Callisto layout. You can edit the header and footer of the checkout and the shopping cart globally via the <<online-store/shop-builder#95, ShopBuilder>>. With the release of Ceres 3.1, you will be able to edit the entire checkout via the ShopBuilder. You can make further adjustments to the design with the help of a <<#theme, theme>>.

In a next step you need to adjust the routes for your legal information.

=== Adjusting the routes to your legal information

The four pieces of legal information - *Terms and conditions*, *Privacy policy*, *Legal disclosure* and *Cancellation rights* have to be connected in a different way in order to be displayed correctly.

[.instruction]
Adjusting the terms and conditions:

. Go to the *Item » Categories* menu.
. Open the Callisto category.
. Copy the category *Terms and conditions* as a main category. +
→ The new main category *Terms and conditions* opens.
. Enter *gtc* as the *URL name* of the category.
. *Save* the settings.

[.instruction]
Adjusting the privacy policy:

. Go to the *Item » Categories* menu.
. Open the Callisto category.
. Copy the category *Privacy policy* as a main category. +
→ The new main category *Privacy policy* opens.
. Enter *privacy-policy* as the *URL name* of the category.
. *Save* the settings.

[.instruction]
Adjusting the legal disclosure:

. Go to the *Item » Categories* menu.
. Open the Callisto category.
. Copy the category *Legal disclosure* as a main category. +
→ The new main category *Legal disclosure* opens.
. Enter *legal-disclosure* as the *URL name* of the category.
. *Save* the settings.

[.instruction]
Adjusting the cancellation rights:

. Go to the *Item » Categories* menu.
. Open the Callisto category.
. Copy the category *Cancellation rights* as a main category. +
→ The new main category *Cancellation rights* opens.
. Enter *cancellation-rights* as the *URL name* of the category.
. *Save* the settings.

When you have saved the routes for your legal information, activated the routes as described above and integrated all relevant payment and shipping service providers via plugins, your Ceres checkout is ready for action and you have successfully overcome the obstacles of the Callisto EOL.

[#individual-order-process]

== Ceres checkout for Callisto online stores that use the *individual order process*

If you are currently using the *individual order process* in your Callisto online store, you need to integrate the Ceres checkout by 01 September 2019 at the latest. Otherwise, your customers will not be able to place orders in your online store. +

<<online-store/best-practices#bp-ceres-EOL, This chapter>> explains how you find out which order process you are currently using. +

If you follow the step-by-step instruction below, you can integrate the Ceres checkout in your Callisto online store in a few simple steps.

=== Managing routes
Ceres online stores use the logic of the plugin IO. In order to use the checkout with all the correct routes, proceed as follows:

[.instruction]
Carry out settings in the IO plugin:

. Go to *Plugins » Plugin overview*.
. Click on *IO*. +
→ The plugin opens.
. Click on *Configuration* in the directory tree.
. Click on the *Routing* tab.
. Deactivate the checkbox next to *Enable routes*. +
→ All routes are deactivated.
. Activate the routes */checkout*, */confirmation*, */login*, */register*, */password-reset* as well as */place-order & /execute payment*.
. *Save* the settings.

[IMPORTANT]
.Using the ShopBuilder in Callisto online stores that use the Ceres checkout
====
If you operate a Callisto online store with Ceres checkout and want to use the <<online-store/shop-builder#, ShopBuilder>>, you also need to activate the first route */*. Otherwise, the ShopBuilder will not load in your back end. Please note that this will overwrite your Callisto homepage. We recommend that you always make changes in a plugin set copy. After you have made changes, you can deactivate the homepage route */* again.
====

[.instruction]
Carry out settings in the Ceres plugin:

. Go to *Plugins » Plugin overview*.
. Click on *Ceres*. +
→ The plugin opens.
. Click on *Configuration* in the directory tree. +
→ The *Global* tab is pre-selected.
. Click on *Enable Callisto route pattern for items*. +
→ The Callisto routes are activated.
. *Save* the settings. +
→ The Ceres checkout is now active in your Callisto online store.

=== Adjusting the order process

You need to adjust several categories in order for the checkout process to be working properly. To do so, proceed as follows:

[.instruction]
Creating categories:

. Go to the *Item » Categories* menu.
. Create a new main category with the name *login*.
. Open the category *login*.
. Select the category type *Container*.
. *Save* the settings.
. Create a new main category with the name *checkout*.
. Open the category *checkout*.
. Select the category type *Container*.
. *Save* the settings.

Afterwards, link the new categories to the Callisto order process.

[.instruction]
Adjusting the order process:

. Go to the *CMS » Web design*.
. Click on *Settings*. +
→ The menu *Design settings* opens.
. Click on the tab *Clients*.
. Select the client you want to edit.
. Click on the tab *Order process*.
. Click on *Search* next to *2nd order process step*.
. Select the newly created category *login*.
. Click on *Search* next to *3rd order process step*.
. Select the newly created category *checkout*.
. *Save* the settings.

Now, once you go to the checkout from the basket, you will be forwarded to the Ceres checkout, which offers new functions, such as payment plugins like PayPal.

=== Creating backlinks

You need to adjust the Callisto code in a few places so that users that are not logged in to your store are redirected to the order process after clicking the *To the checkout* button. To do so, proceed as follows:

[.instruction]
Creating backlinks for the shopping cart:

. Go to *Item » Categories*.
. Open the Callisto category.
. Click on the category *Shopping cart*.
. Click on the tab *Description 1*.
. Search for the code `{% if ( $CustomerID ) { Link_Checkout(3); } else { Link_Checkout(2); } %}`
. Replace this code with: `{% if( $CustomerID ) { $_check = Link_Checkout(3); $_backlink = ''; } else { $_check = Link_Checkout(2); $_backlink = '?backlink=/checkout'; } %} $_check.$_backlink`
. *Save* the settings.

[.instruction]
Creating backlinks for the shopping cart preview:

. Go to the *CMS » Web design » Layout » ItemView » ItemViewBasketPreviewList*.
. Search for the code: `{% if( $CustomerID ) { Link_Checkout(3); } else { Link_Checkout(2); } %}`
. Replace this code with: `{% if( $CustomerID ) { $_check = Link_Checkout(3); $_backlink = ''; } else { $_check = Link_Checkout(2); $_backlink = '?backlink=/checkout'; } %} $_check.$_backlink`
. *Save* the settings.

[.instruction]
Creating backlinks for the shopping cart overlay:

. Go to the *CMS » Web design » Layout » ItemView » ItemViewItemToBasketConfirmationOverlay*.
. Search for the code: `{% if ( $CustomerID ) { Link_Checkout(3); } else { Link_Checkout(2); } %}`
. Replace this code with: `{% if( $CustomerID ) { $_check = Link_Checkout(3); $_backlink = ''; } else { $_check = Link_Checkout(2); $_backlink = '?backlink=/checkout'; } %} $_check.$_backlink`
. *Save* the settings.

Users who have made additional adjustments to their layout need to check whether any other links on their website lead customers to the checkout. These links have to be changed so that they link to the route */checkout*. We are not able to intercept all individual changes to the layout, since these can vary from user to user.

The visual design of the Ceres checkout will differ from your Callisto layout. You can edit the header and footer of the checkout and the shopping cart globally via the <<online-store/shop-builder#95, ShopBuilder>>. With the release of Ceres 3.1, you will be able to edit the entire checkout via the ShopBuilder. You can make further adjustments to the design with the help of a <<#theme, theme>>.

In a next step, adapt the routes for your legal information.

=== Adjusting the routes to your legal information

The four pieces of legal information - *Terms and conditions*, *Privacy policy*, *Legal disclosure* and *Cancellation rights* have to be connected in a different way in order to be displayed correctly.

[.instruction]
Adjusting the terms and conditions:

. Go to *Item » Categories*.
. Open the Callisto category.
. Copy the category *Terms and conditions* as a main category. +
→ The new main category *Terms and conditions* opens.
. Enter *gtc* as the *URL name* of the category.
. *Save* the settings.

[.instruction]
Adjusting the privacy policy:

. Go to *Item » Categories*.
. Open the Callisto category.
. Copy the category *Privacy policy* as a main category. +
→ The new main category *Privacy policy* opens.
. Enter *privacy-policy* as the *URL name* of the category.
. *Save* the settings.

[.instruction]
Adjusting the legal disclosure:

. Go to *Item » Categories*.
. Open the Callisto category.
. Copy the category *Legal disclosure* as a main category. +
→ The new main category *Legal disclosure* opens.
. Enter *legal-disclosure* as the *URL name* of the category.
. *Save* the settings.

[.instruction]
Adjusting the cancellation rights:

. Go to *Item » Categories*.
. Open the Callisto category.
. Copy the category *Cancellation rights* as a main category. +
→ The new main category *Cancellation rights* opens.
. Enter *cancellation-rights* as the *URL name* of the category.
. *Save* the settings.

After you have saved your legal information, activated the routes as described above, adjusted the categories, created the backlinks and integrated all relevant payment and shipping service providers via plugins, your Ceres checkout is ready for action and you have successfully overcome the hurdles of the Callisto EOL.

[#theme]
== Theme

You have personalised your Callisto online store just the way you like it and are afraid that the Ceres design might interfere with it? You can easily download the link:https://marketplace.plentymarkets.com/plugins/storefront/themes/cerescoconut_6120[Coconut theme^] for Ceres and apply your own design to guarantee a consistent user experience.
