= Improving your Google Page Speed Insights rating
:lang: en
:keywords: Online store, client, Standard, Ceres, Plugin, Ceres, HowTo, setup, Plugin-Sets, Google, PSI, page speed, Page Speed, insights, Pages Speed Index, Performance, optimisation, optimization, 
:position: 110
:author: team-webshop

In this Best Practice you will learn which measures you can take to improve the link:https://developers.google.com/speed/pagespeed/insights/?hl=de[Google Page Speed Insights] performance rating of your plentyShop. In a first step, you will learn which of the standard Ceres functionality you can use in order to achieve higher PSI values. At a later point, this guide will also include modifications you can implement via a theme in order to attain a higher performance rating. The measures explicated below require no background in programming whatsoever.  


[IMPORTANT]
====
The measures we suggest in this guide can only improve the performance rating of your plentyShop to a certain degree. The release of plentyShop 6.0 will include adjustments that positively impact the PSI rating. We are alsways striving to improve the performance of plentyShop Ceres with each new version we release.
====

The following chapters detail 7 adjustments you can make to your plentyShop that you can implement without the need to code:
    
== Activating the Live Mode in the Ceres plugin

The Ceres plugin offers you the possibility to choose between the *Development mode* and the *Live mode*. In the development mode, you can use debbuging options and the plugin files are neither minimised nor bundled, which can negatively impact the performance of the online store. We advise you to operate your online store in live mode, in order to increase the performance. Take the following steps to activate live mode:



[.instruction]
Activate live mode:

. Open the menu *Plugins » Plugin set overview*.
. Select your plugin set.
. Click *Edit plugin set*.
. In the row of the Ceres plugin, click icon:cog[role="darkGrey"] *Settings*. +
→ The Ceres settings are opened.
. Click on the tab *Logging and performance*.
. Select the option *Live mode* for the setting *Performance level*.
. *Save* (icon:save[role="green"]) the settings.

If you activate the live mode, the Ceres files are bundled and minimised, resulting in a quicker loading of the pages of your online store.


== Optimising image widgets

Image files are one of the major culprits for low online store performance. You should, if possible, only include as many image widgets on your online store pages as you need for your purposes. A lower number of image widgets per page will positively impact the performance of your plentyShop. + 

=== Using modern image formats

Furthermore, we advise you to use modern image formats for the images you include in your online store. For the widgets *Background image*, *Image box*, and *Image carousel*, we recommend that you use the input field *Image selection* to store images in the format *WebP*. If you store a WebP image, the additional input field *Image selection for older browsers* will be displayed, which serves to display fallback images in browsers, that are not yet compatible with modern image formats. IF possible, we advise you to store images in JPEG format for these browsers. +


=== Activating lazy loading

Additionally, we recommend that you activate the option *Only load visible content* in the widget settings of every widget that includes images. This option, the so-called "Lazy loading", makes sure that image files which are not visible upon the initial access of the relevant page are loaded at a later time. The initial loading time of your online store pages is positively impacted by activating this option. 

== Reducting the number of widgets

The number of widgets you include on each online store page is prone to negatively affecting the performance of your plentyShop. The larger the number of widgets per page, the slower the loading times. This is particularly applicable to image widgets and to widgets that necessitate a large quantity of item data. Each additional widget impacts the time to first full interactivity of the page. +
We therefore recommend you use only as many widgets per page as is necessary for your purposes. On category pages, in particular, it is advisable to reduce the numver of displayed items, since category pages need to load large quantities of data and complex Javascript.

== Avoid invisible text caused by custom fonts

If you include custom fonts for your online store and do not use the drsign settings of the ShopBuilder, it is possible that browsers try to display certain sections of text before the custom font is loaded. As a result, your online store may be prone to a so-called *Flash of invisible text (FOIT)*, meaning a short time during which the text you want to display cannot be displayed by the browser. + 

In order to avoit FOITS, you can use a CSS command to intermittenly display a system font instead of your custom font. to do so, you add the directive *font-display: swap* in your *@font-face* styles, for instance by using the link:https://marketplace.plentymarkets.com/plugins/storefront/widgets/cfourcustomcssjs_5143[Custom CSS/JS in the frontend]) plugin. You can thereby prevent annyoing FOITS to happen, which can have a positive impact on the PSI rating of your online store.

== Activating the ShopBooster

The Time to first Byte (TTFB) is also part of the parameters evaluated by PSI, albeit to a small degree. In order to improve your TTFB values, you can activate the additional ShopBooster module for a fee. By activating the ShopBooster, page contents of your plentyShop are written into the cache, so that a second access to the page will benefit from greatly improved TTFB times.

[IMPORTANT]
.Additional costs
====
The activation of the ShopBooster comes at a fee. For each client, the additional costs amount to 0,004 € per 100 page accesses or page changes. A page access is the process in which one visitor or a webcrawler accesses a URL of your online store. A page chance is triggered by one of the following processes:


- Updating category or item data
- Updating ShopBuilder pages
- Deploying plugins
- Saving the Ceres settings
- Invalidating the cache by deactivating the ShopBooster

The additional costs of the ShopBooster amount to a maximum of 100€  per month per client.
====

[.instruction]
Activating the ShopBooster:

. Open the menu *Setup » Client » Select client » Webshop » ShopBooster*.
. Click *Activate ShopBooster*. +
→ A window is opened, informaing you about the additional costs involved.
. Click *Confirm* to activate the ShopBooster. +
→ The notification *ShopBooster has been activated* is displayed.

== Avoiding Javascript in code widgets

The ShopBuilder provides a code widget via which you can integrate additional adjustments that are not covered by ShopBuilder itself. If you want to inplement a piece of code, we advise you to avoid using Javascript in the code widget of the ShopBuilder. Instead, you can, for instance, use the link:https://marketplace.plentymarkets.com/plugins/storefront/widgets/cfourcustomcssjs_5143[Custom CSS/JS in the frontend] plugin or include the Javascript in a theme. Including additional Javascript in code widgets negatively impacts the loading times of your plentyShop. +
If you integrate additional Javascript via an external plugin or a theme, we recommend that you place the Javascript at the lower end of the HTML body.


== Linking payment plugins to the right containers

If you use payment plugins for your plentyShop that involve larger quantities of data (such as AmazonPay or PayPal), it is imperative for the performance of your online store to link these plugins to the correct corresponding template containers. We added new template containers with the release of Ceres 5.0 in order to load Javascript and CSS of payment plugins only in the places that they are needed for the successful order process. +
The plugin guides of the respective payment plugins, such as link:https://marketplace.plentymarkets.com/paypal_4690#80.[PayPal], already include detailed descriptions on how to link the contents of the plugins to the corresponding template containers. In general, you should link the Javascript of the payment method to the container *Checkout.AfterScriptsLoaded* and no longer to *ScriptLoader.AfterScriptsLoaded*. This can positively impact the performance of the online store.