= Attribute
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Attribut, Attribut, Attribut, Attribute, Attribute, Attribute, Attribute, Charakteristik, Charakteristika, Charakteristiken, Produkte charakterisieren, Artikel charakterisieren, Variante erzeugen, Varianten erzeugen, Variante generieren, Varianten generieren, Attribut erstellen, Attribute erstellen, Attributwert, Attributwerte, Attributwerten, Bildverknüpfung möglich, Attribut-Auswahl im Webshop, Gruppierbar in Artikellisten, Prozentualer Anteil, Mengenverteilung, Attributbilder, Attributbild, Marktplatzattributen, Marktplatzattribute, Marktplatzattribut, Marktplatzattributverknüpfung, Attributname, Attributnamen
:description: Attribute charakterisieren deine Produkte und bilden dabei verkaufbare Varianten.
:url: artikel/einstellungen/attribute
:position: 20
:id: 559N81B
:author: team-item

////
zuletzt bearbeitet 11.02.2021
////

Manche Artikel, wie Schuhe und T-Shirts, werden in verschiedenen Größen und Farben verkauft.
Solche Charakteristiken werden in plentymarkets als Attribute bezeichnet.
Mit Hilfe von Attributen kannst du deine Produkte charakterisieren und gleichzeitig auch <<artikel/einleitung/struktur#, verkaufbare Varianten>> erzeugen, wie z.B. das T-Shirt in der Farbe rot und in Größe S.

[TIP]
.Andere Möglichkeiten der Produktcharakterisierung
====
Möchtest du deine Produkte charakterisieren, _ohne_ dabei Varianten zu erzeugen?
Möchtest du beispielsweise nur die technischen Features eines Produkts in deinem plentyShop hervorheben?
Dies ist mit Hilfe von <<artikel/einstellungen/eigenschaften#, Eigenschaften und Merkmalen>> möglich!
====

Lerne Attribute spielerisch kennen:

video::265389643#t=0m54s[vimeo]


[discrete]
=== Ablauf

. Lege <<artikel/einstellungen/attribute#100, Attribute>>, wie Farbe sowie die entsprechenden <<artikel/einstellungen/attribute#200, Werte>>, wie rot, blau und grün an.
.. *_Optional_*: Verkaufst du deine Produkte auf Märkten wie Amazon und eBay?
Einige Märkte erfordern, dass du <<artikel/einstellungen/attribute#500, deine eigenen Attributwerte mit deren Attributwerten>> zuordnest.
.. *_Optional_*: Füge <<artikel/einstellungen/attribute#600, Bilder>> hinzu, um deine Attributwerte grafisch darzustellen.
.. *_Optional_*: Speichere die Namen von Attributen und Werten <<artikel/einstellungen/attribute#1000, in mehreren Sprachen>>.
. <<artikel/einstellungen/attribute#300, Erzeuge Varianten>>, indem du Attributwerte miteinander kombinierst.
Zum Beispiel ergeben sich 9 verschiedene Varianten, wenn du die Größen S, M, L mit den Farben rot, blau und grün kombinierst.

[#100]
== Neue Attribute erstellen

Lege zunächst Attribute wie Farbe oder Größe an.

[.instruction]
Neues Attribut erstellen:

. Öffne das Menü *Einrichtung » Artikel » Attribute*.
. Klicke auf *Neues Attribut* (icon:plus[role="green"]).
. Gib den internen Namen ein.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen. +
→ Das Attribut wird erstellt und das Tab *Grundeinstellungen* wird geöffnet.
. Nimm weitere Einstellungen vor. Beachte <<table-create-attribute>>.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen.

[[table-create-attribute]]
.Neues Attribut erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Name (intern)*
a|include::../_textblocks/tabelle/interne-name.adoc[]

| *Position*
a|Welches Attribut soll im plentyShop als erstes, zweites, drittes, usw. angezeigt werden?
Gib eine Positionsnummer in dieses Feld ein.
Wenn ein Artikel mehrere Attribute hat, werden die Attribute aufsteigend nach Positionsnummern dargestellt.

|[#intable-bild-link-erlauben]*Bildverknüpfung möglich*
a|Wähle diese Option (icon:check-square[role="blue"]), wenn sich das Artikelbild z.B. auf eBay ändern soll, je nachdem, welche Größe oder Farbe dein Kunde gewählt hat. Es werden also automatisch die passenden Bilder auf eBay eingeblendet.

*_Hinweis_*: Obwohl eine Variante mit mehreren Attributen verknüpft werden kann, ist die Bildverknüpfung nur für ein Attribut pro Variante möglich.

*_Zusätzliche Einstellungen_*: Verknüpfe deine Varianten mit den passenden Bildern. Stelle sicher, dass du diese Bilder für den Marktplatz verfügbar gemacht hast. Verknüpfe außerdem die Variantenbilder mit Marktplatzattributen. Diese Schritte werden <<artikel/einstellungen/attribute#900, in einem separaten Kapitel>> näher beschrieben.

|[#intable-attribut-auswahl]*Attribut-Auswahl im Webshop*
a|Wie sollen Kunden Größen oder Farben in deinem plentyShop wählen? Sollen sie den Namen aus einer Dropdown-Liste wählen oder auf eine Bildkachel klicken?

* *Per Dropdown* = Attributnamen werden in einer Dropdown-Liste angezeigt.
* *Per Bild* = Attribute werden als <<artikel/einstellungen/attribute#700, Bildkacheln im plentyShop>> angezeigt.
* *Per Box* = Attribute werden als Boxen mit Attributwerten im plentyShop angezeigt.

| *Gruppierbar in Artikellisten*
a|include::../_textblocks/tabelle/gruppierbar.adoc[]
|====

[#200]
== Werte festlegen

Lege Attributwerte wie Rot, Blau, Grün oder S, M, L, XL an.

[.instruction]
Attributwerte festlegen:

. Öffne das Menü *Einrichtung » Artikel » Attribute*.
. Klicke auf das Attribut.
. Wechsele in das Tab *Werte*.
. Klicke auf *Neuer Wert* (icon:plus[role="green"]).
. Gib den internen Namen ein.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen. +
→ Der Attributwert erhält eine ID und wird im Tab *Werte* angezeigt.
. Nimm weitere Einstellungen vor. Beachte <<table-create-attribute-values>>.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen.

[[table-create-attribute-values]]
.Attributwerte festlegen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *ID*
|Die ID wird automatisch vergeben und kann nicht geändert werden.

| *Bild*
|Wie sollen Kunden Größen oder Farben in deinem plentyShop wählen? Sollen sie den Namen aus einer Dropdown-Liste wählen oder auf eine Bildkachel klicken? Lade hier ein Bild hoch, wenn du den Attributwert grafisch darstellen möchtest. +
*_Zusätzliche Einstellungen_*: Lege auch in den Grundeinstellungen fest, dass dieses Attribut mit Bildern ausgewählt werden soll. Optional auch die maximale Bildgröße angeben. Diese Schritte werden <<artikel/einstellungen/attribute#700, in einem separaten Kapitel>> näher beschrieben.

| *Position*
|Welcher Attributwert soll im plentyShop als erster, zweiter, dritter, usw. angezeigt werden?
Gib eine Positionsnummer in dieses Feld ein.
Die Attributwerte werden aufsteigend nach Positionsnummern dargestellt.

| *Name*
|Name eingeben, der im plentyShop angezeigt werden soll.

| *Name (intern)*
a|Eindeutiger Name für den Attributwert. Der interne Name wird nur im plentymarkets Backend geführt und ist nicht im plentyShop sichtbar. Der interne Name darf nur einmal pro Attribut vergeben werden. Folgende Zeichen dürfen nicht für den internen Namen verwendet werden, da sonst Fehler beim Datenaustausch auftreten: +

* Komma
* Doppelpunkt
* Semikolon
* Anführungszeichen

| *Bemerkung*
|Optional Bemerkung zu dem Attributwert eingeben.

| *Prozentualer Anteil*
|Prozentwerte für die automatische Mengenverteilung von Attributwerten eingeben. Bei Nachbestellungen werden die Mengen der Attributwerte automatisch auf die Gesamtmenge verteilt. +
*__Hinweis:__* Die automatische Mengenverteilung funktioniert nur, wenn der Artikel genau 2 Attributwerte hat.
|====

[#300]
== Varianten mit den Attributen erzeugen

Die erste Variante eines Artikels wird als _Hauptvariante_ bezeichnet.
Hat ein Artikel mehrere Varianten, kann die Hauptvariante entweder selbst ein verkaufbares Produkt sein oder rein virtuell bestehen, um die weiteren Untervarianten des Artikels anhand von <<artikel/einleitung/vererbung#, Vererbung>> zu verwalten.

Wie genau du vorgehen wirst, hängt davon ab, ob die Hauptvariante verkaufbar ist oder nicht.

[.tabs]
====
Hauptvariante ist _nicht_ verkaufbar::
+
--
Stell dir vor, du verkaufst ein T-Shirt in den Größen S, M, L und XL.
Die Hauptvariante steht nicht zum Verkauf und entspricht auch keiner dieser Größen.
Die Hauptvariante ist lediglich ein Datencontainer zur Verwaltung von Preisen, Kategorien und anderen Produkteinstellungen.

. <<artikel/import-export-anlage/anlage/neue-artikel#200, Erstelle zuerst den Artikel>>, ohne Attribute auszuwählen.
Dadurch wird die Hauptvariante ohne Attribute angelegt.
. Wähle dann die Attribute aus, während du <<artikel/import-export-anlage/anlage/neue-artikel#400, die benötigten Varianten erstellst>>.

--
Hauptvariante ist verkaufbar::
+
--
Stell dir vor, du verkaufst ein T-Shirt in den Größen S, M, L und XL.
Die Hauptvariante steht zum Verkauf und entspricht einer dieser Größen, z.B. S.

. <<artikel/import-export-anlage/anlage/neue-artikel#200, Erstelle zuerst den Artikel>> und wähle dabei den passenden Attributwert aus, z.B. die Größe S.
Die Hauptvariante wird mit diesem Attributwert angelegt.
. Wähle dann die restlichen Attribute aus, während du <<artikel/import-export-anlage/anlage/neue-artikel#400, die weiteren Varianten erstellst>>.

--
====

[#400]
== Optionale Funktionen

[#500]
=== Attributwerte mit Marktplätzen verknüpfen

Einige Märkte, wie z.B. <<maerkte/amazon/varianten-vorbereiten#1350, Amazon>> und <<maerkte/ebay/ebay-einrichten#6100, eBay>>, verlangen, dass du _deine eigenen_ Attributwerte mit _ihren Attributwerten_ verknüpfst.
Stell dir zum Beispiel vor, du verkaufst ein türkisfarbenes T-Shirt. Der Markt, auf dem du es verkaufen willst, akzeptiert jedoch nur grün und blau. Verknüpfe deine eigenen Attributwerte mit denen auf dem anderen Markt, um sicherzustellen, dass deine Artikel korrekt angezeigt werden.

Dieses Video zeigt die Idee mit einem spielerischen Beispiel:

video::199993489#t=5m58s[vimeo]

[TIP]
.Attributwerte auch mit Variantenbildern verknüpfen
====
Soll sich das Artikelbild zusätzlich auch ändern, je nachdem, welche Größe oder Farbe ein Kunde wählt?
Einige Märkte, wie z.B. eBay, verlangen, dass du dafür zusätzlich deine <<artikel/einstellungen/attribute#900, Variantenbilder mit den passenden Attributwerten verknüpfst>>.
====

[#600]
=== Attribute grafisch darstellen

[#700]
==== Attributwerte als Bilder darstellen

Wie sollen Kunden Größen oder Farben in deinem plentyShop wählen? Sollen sie den Namen aus einer Dropdown-Liste wählen oder auf eine Bildkachel klicken?
Führe die folgenden drei Schritte aus, wenn deine Attributwerte als Bilder angezeigt werden sollen.

[.instruction]
Bilder für Attributwerte hochladen:

. Öffne das Menü *Einrichtung » Artikel » Attribute*.
. Klicke auf das Attribut.
. Wechsele in das Tab *Werte*.
. Klicke in der Spalte *Bild* auf *Bild hochladen* (icon:upload[set=plenty, role="purple"]).
. Wähle das Bild für den Attributwert.
. Klicke auf *Öffnen*.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen. +
→ Das Bild wird hochgeladen und eine Vorschau wird in der Spalte *Bild* angezeigt.
. Führe die gleichen Schritte aus, um Bilder für andere Attributwerte hochzuladen.

[.instruction]
Aussehen im plentyShop von Text zu Bild ändern:

. Öffne das Menü *Einrichtung » Artikel » Attribute*.
. Klicke auf das Attribut.
. Wechsele in das Tab *Grundeinstellung*.
. Wähle unter *Attributauswahl im Webshop* die Option *Per Bild*.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen.

[.instruction]
Größe der Attributbilder ändern:

. Öffne das Menü *Einrichtung » Artikel » Bilder » Einstellungen*.
. Gib im Bereich *Attributbilder* die maximale Höhe und Breite für die Bilder ein.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen.

[#800]
==== Individuelles Bild für jede Variante speichern

Soll sich das Artikelbild im plentyShop ändern, je nachdem, welche Größe oder Farbe dein Kunde wählt?
Gehe wie folgt vor, wenn die passenden Bilder automatisch eingeblendet werden sollen.

[#variante-bilder-link]
[.instruction]
Varianten mit den passenden Bilder verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Bilder*.
. <<artikel/artikel-verwalten#90, Lade die benötigten Bilder hoch>>.
. Wähle die Bilder (icon:check-square[role="blue"]), die du verknüpfen möchtest.
. Klicke auf *Variantenverknüpfung* (icon:plus[role="green"]). +
→ Das Fenster *Variantenverknüpfung* wird angezeigt.
. Verwende bei Bedarf die Filter links.
. Wähle die Varianten (icon:check-square[role="blue"]), die du mit den gewählten Bildern verknüpfen möchtest.
. Klicke auf *Verknüpfen* (icon:check[role="green"]). +
→ Die Bilder werden mit den gewählten Varianten verknüpft.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen. +
→ Wählt ein Kunde die Variante im plentyShop, sieht er das passende Artikelbild.

[#900]
===== Variantenbilder mit Marktplatzattributen verknüpfen

Soll sich das Artikelbild z.B. auch auf eBay ändern, je nachdem, welche Größe oder Farbe dein Kunde gewählt hat?

Einige Märkte, wie z.B. eBay, verlangen nicht nur, dass du deine <<artikel/einstellungen/attribute#500, Attribute mit dem Marktplatz verknüpfst>>, sondern auch, dass du deine Variantenbilder mit den passenden Attributwerten verknüpfst.

[TIP]
.Sind alle Voraussetzungen erfüllt?
====
////
nachdem alles umgestellt ist, mache den Link auf Marktplatz-Verfügbarkeit eindeutiger, nicht ganze Kapitel sondern Einstellung
////
Stelle sicher, dass du deine <<artikel/einstellungen/attribute#variante-bilder-link, Varianten bereits mit den entsprechenden Bildern verknüpft>> hast und dass du diese <<artikel/artikel-verwalten#90, Bilder für den Marktplatz verfügbar gemacht>> hast. Stelle außerdem sicher, dass du <<artikel/einstellungen/attribute#intable-bild-link-erlauben, Bildverknüpfungen in den Grundeinstellungen zugelassen>> hast.
====

[.instruction]
Variantenbilder mit Marktplatzattributen verknüpfen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Bilder*.
. Wähle unter *Marktplatzattributverknüpfung* den passenden Attributwert für das Artikelbild.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen. +
→ Wählt ein Kunde die Variante auf eBay, sieht er das passende Artikelbild.

[TIP]
.Wo finde ich das Feld "Marktplatzattributverknüpfung"?
====
Diese Option wird nur angezeigt, wenn das Bild bereits <<artikel/einstellungen/attribute#variante-bilder-link, mit mindestens einer Variante verknüpft>> ist.
====

[#1000]
=== Namen in mehreren Sprachen speichern

Ist dein plentyShop in mehreren Sprachen verfügbar? Dann musst du die Namen deiner Attribute und Attributwerte ebenfalls übersetzen.

[.instruction]
Attributnamen übersetzen:

. Öffne das Menü *Einrichtung » Artikel » Attribute*.
. Klicke auf das Attribut.
. Wechsele in das Tab *Name*.
. Gib den Namen in beliebig vielen Sprachen ein.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen.

[TIP]
.Darstellung des Attributnamens im plentyShop
====
Gib eine möglichst kurze Bezeichnung ein, da der Platz begrenzt ist. Der Attributname wird im plentyShop neben einer Auswahlbox angezeigt.
====

[.instruction]
Attributwerte übersetzen:

. Öffne das Menü *Einrichtung » Artikel » Attribute*.
. Klicke auf das Attribut.
. Wechsele in das Tab *Werte*.
. Wähle im Kopfbereich eine Sprache aus der Dropdown-Liste *Sprache anzeigen*. +
→ Es ändert sich ausschließlich der in der Spalte *Name* eingegebene Text.
. Gib in der Spalte *Name* die Attributwerte in der Fremdsprache ein.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen.

[TIP]
.Name in einer Sprache anzeigen und in einer anderen speichern
====
Die Dropdown-Liste *Sprache speichern* gibt an, in welcher Sprache der Name gespeichert wird, wenn du auf das Speichern-Symbol klickst.
In der Regel wirst du _nicht_ mit dieser Dropdown-Liste arbeiten, da die Sprache _automatisch_ hier gewählt wird, sobald du eine Sprache aus der Dropdown-Liste *Sprache anzeigen* wählst.

Du kannst aber eine abweichende Sprache aus der Dropdown-Liste *Sprache speichern* wählen, wenn du den Namen in einer Sprache anzeigen und in einer anderen speichern möchtest.
====

[#1100]
== Attribute löschen

Bevor ein Attribut gelöscht werden kann, müssen alle mit dem Attribut verknüpften Varianten gelöscht werden.
Die <<artikel/import-export-anlage/anlage/massenbearbeitung#300, Varianten-Gruppenfunktion>> ist ein nützliches Werkzeug dafür.

[.instruction]
Mit einem Attribut verknüpfte Varianten löschen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Stelle die Filter links wie folgt ein:
.. Setze links den Filter <<artikel/einleitung/suche#intable-tabellentyp, Tabellentyp>> auf *Varianten*.
.. Setze links den Filter <<artikel/einleitung/suche#intable-aktiv, Aktiv>> auf *ALLE*.
.. Wähle im Filter <<artikel/einleitung/suche#intable-alle, ALLE>> das Attribut aus der Dropdown-Liste.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Alle Varianten mit dem Attribut werden angezeigt.
. Wähle alle Varianten (icon:check-square[role="blue"]).
. Klicke auf *Varianten-Gruppenfunktion*. +
→ Das Fenster *Varianten-Gruppenfunktion* wird geöffnet.
. Wähle im Bereich *Aktionen* die Option *Varianten löschen* (icon:check-square[role="blue"]).
. Klicke auf icon:execute[set=plenty] *Ausführen*. +
→ Die Varianten werden gelöscht. +
→ Das Attribut kann nun gelöscht werden.

[.instruction]
Attribut löschen:

. Öffne das Menü *Einrichtung » Artikel » Attribute*.
. Klicke in der Zeile des Attributs auf *Löschen* (icon:minus-circle[role="red"]). +
→ Ein neues Fenster wird geöffnet.
. Klicke erneut auf *Löschen* (icon:minus-circle[role="red"]), um deine Entscheidung zu bestätigen. +
→ Das Attribut wird gelöscht.
