= Barcodes und Etiketten
:lang: de
include::{includedir}/_header.adoc[]
:description: Lerne, Barcodes Schritt für Schritt einzurichten und auf Artikeletiketten anzuzeigen.
:url: artikel/einstellungen/barcodes
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

//später :position: 60 einfügen wenn die Seite live sein soll

Barcodes dienen zur eindeutigen Kennzeichnung von Artikeln. Sie werden häufig z.B. auf Artikeletiketten oder auf Dokumenten wie Rechnungen und Lieferscheinen dargestellt. Diese Seite hilft dir, Barcodes Schritt für Schritt in plentymarkets einzurichten.

Zuerst <<artikel/einstellungen/barcodes#100, konfigurierst du Barcode-Typen>>. Mit anderen Worten, legst du fest, ob du GTIN, ISBN, UPC oder QR Barcodes brauchst und für welche Verkaufsplattformen du die Barcodes brauchst.

Falls du Barcodes nicht direkt von deinem Hersteller erhältst, d.h. falls du eine Eigenmarke vertreibst, dann musst du <<artikel/einstellungen/barcodes#200, die eigentlichen Barcodes von einer Organisation wie GS1 erwerben>>. Beispielsweise kaufst du hierfür ein Nummernkreis bestehend aus 1000 Barcodes. Du teilst plentymarkets mit, welche Barcodes du gekauft hast, indem du Informationen über den Nummernkreis speicherst.

Danach <<artikel/einstellungen/barcodes#300, ordnest du die Barcodes deinen Artikeln zu>>. Mit anderen Worten verknüpfst du deine Barcodes mit deinen Artikelvarianten.

Schließlich entscheidest du, wo du die Barcodes darstellen möchtest. Willst du beispielsweise Barcodes auf deinen Artikeletiketten darstellen, dann <<artikel/einstellungen/barcodes#900, gestaltest du die Etiketten>> und <<artikel/einstellungen/barcodes#1000, druckst sie aus>>.

[#100]
== Barcode-Typen konfigurieren

Welche Barcode-Typen benötigst du? Auf welchen Verkaufsplattformen wirst du die einzelnen Barcode-Typen verwenden? Speichere zunächst einige grundlegende Einstellungen für deine Barcodes.

[.instruction]
Barcodes konfigurieren:

. Öffne das Menü *Einrichtung » Artikel » Barcode*.
. Klicke auf icon:plus[role="green"] *Neuer Barcode*. +
→ Das Fenster *Neuer Barcode* wird geöffnet.
. Gib den Namen ein.
. Wähle den Typ. Beachte <<tabelle-barcode-typen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Barcode-Konfiguration erhält automatisch eine ID und die Einstellungen werden in einem neuen Tab geöffnet.
. Wähle (icon:check-square[role="blue"]) eine oder mehrere Herkünfte.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[tabelle-barcode-typen]]
.Barcode-Typen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*GTIN 8*; +
*GTIN 13*; +
*GTIN 14*; +
*GTIN 128*
|Global Trade Item Number (früher European Article Number, EAN) ist eine Produktkennzeichnung für Handelsartikel. Die GTIN besteht aus 8, 13, 14 oder maximal 128 Ziffern, die zentral verwaltet und an Hersteller auf Antrag vergeben wird.

13-stellige GTINs setzen sich zusammen aus Basisnummer, Artikelnummer und Prüfziffer. Die Basisnummer hat 7 bis 9 Stellen und besteht aus dem Länderpräfix der GS1-Mitgliedsgesellschaft, zum Beispiel 400 bis 440 für Deutschland, und der Unternehmensnummer. Die Artikelnummer des Herstellers hat 3 bis 5 Stellen (je nach Länge der Basisnummer). Die Prüfziffer nimmt die letzte Stelle ein.

|*ISBN*
|International Standard Book Number (Internationale Standardbuchnummer) ist eine eindeutige 10- oder 13-stellige Nummer zur Kennzeichnung von Büchern und anderen selbstständigen, nicht fortlaufenden Veröffentlichungen, zum Beispiel Multimedia-Produkten und Software.

|*QR*
|Quick Response Code. Im Code sind Version, Datenformat und Informationen enthalten.

|*CODE 128*
|Alphanumerischer Strichcode. Der Code128 setzt sich zusammen aus Startzeichen, Nutzinformation, Prüfziffer und Stoppzeichen.

|*UPC*
|Universal Product Code ist eine Produktkennzeichnung für Handelsartikel. Der UPC ist eine 12-stellige Nummer. Durch Voranstellung einer *0* kann die Zahlenkette als 13-stellige GTIN verwendet werden.
|====

[TIP]
.Beispiel: FNSKU-Barcodes
====
Auch wenn es für FNSKU keinen bestimmten Barcodetyp gibt, kannst du trotzdem FNSKU-Barcodes in plentymarkets konfigurieren. Gib einen aussagekräftigen Namen ein und wähle den gewünschten Typ, z.B. Code 128.
====

[#200]
== Barcodes erwerben und Nummernkreis speichern

Viele Händler haben für ihre Artikel keine GTINs (Barcodes), da sie die Artikel direkt importieren und die Hersteller keine GTINs vergeben. In diesem Fall können Händler GTINs von einer Organisation wie link:https://www.gs1-germany.de/[GS1^] erwerben. Beispielsweise können Händler ein Nummernkreis bestehend aus 1000 Barcodes kaufen.

Aber wie kriegt man diese Barcodes dann in plentymarkets rein? Du musst sie nicht extra importieren! Teile plentymarkets einfach mit, wie viele GTINs du besitzt und mit welcher Nummer diese beginnen. Wenn du dann <<artikel/einstellungen/barcodes#300, einem Artikel einen Barcode zuweist>>, wird automatisch der nächste verfügbare Barcode verwendet.

[.instruction]
GTIN-Nummernkreis speichern:

. Öffne das Menü *Einrichtung » Artikel » GTIN*.
. Gib den Startwert ein. +
→ Bei 13-stelligen GTINs wird ein 12-stelliger Wert eingegeben. Die Prüfziffer wird automatisch angehängt.
. Gib die Anzahl der GTINs ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Warum sieht der Nummernkreis nicht fortlaufend aus?
====
Auf den ersten Blick sieht es vielleicht nicht so aus, als ob der Nummernkreis immer um 1 erhöht wird. Aber vergesse nicht, dass die letzte Ziffer eine Prüfziffer ist. Die 12 Stellen davon sind fortlaufend. Lasse die Prüfziffer weg, wenn du den Startwert eingibst.
====

[#300]
== Barcodes zu Artikeln zuordnen

Wie viele Produkte möchtest du mit Barcodes versehen? Wenn du nur wenige Produkte hast, dann ist es wahrscheinlich am schnellsten, die <<artikel/einstellungen/barcodes#400, Barcodes manuell zu verknüpfen>>. Hast du dagegen viele Produkte, dann ist es wahrscheinlich schneller, die <<artikel/einstellungen/barcodes#500, Barcodes zu importieren>>.

Aber was ist, wenn du deine eigenen Barcodes gekauft und einen Nummernkreis gespeichert hast? In diesem Fall lässt du plentymarkets deine Produkte <<artikel/einstellungen/barcodes#600, automatisch den nächsten verfügbaren Barcode>> zuordnen.

[TIP]
.Barcodes werden auf Varianten-Ebene gespeichert
====
Technisch gesehen wird ein Barcode mit <<artikel/einleitung/struktur#, einer einzelnen Variante>> verknüpft und nicht mit dem Artikel als Ganzes. Wenn du zum Beispiel ein T-Shirt in den Farben Rot oder Blau verkaufst, dann haben das rote und das blaue T-Shirt jeweils einen eigenen Barcode.
====

[#400]
=== Barcodes manuell zu Artikeln zuordnen

[.instruction]
Barcodes manuell zu Artikeln zuordnen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel. +
→ Das Tab *Einstellungen* der Hauptvariante wird geöffnet.
. Wähle im Bereich *Barcode* die <<artikel/einstellungen/barcodes#100, zuvor gespeicherte Barcode-Konfiguration>> aus der Dropdown-Liste.
. Klicke auf *Hinzufügen* (icon:plus[role="green"]). +
→ Der Barcode-Typ wird hinzugefügt und in der Liste angezeigt.
. Gib den Code in das Feld *Code* ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#500]
=== Barcodes mit ElasticSync importieren

<<daten/daten-importieren/ElasticSync#, ElasticSync>> ist ein nützliches Werkzeug, um viele Barcodes gleichzeitig zu importieren. Die Idee ist ganz einfach. Anstatt Barcodes manuell zu Artikeln zuzuordnen, trägst du die gleiche Informationen in eine CSV-Datei ein und importierst diese Datei dann in dein System.

Anstatt den Barcode-Typ im Artikeldatensatz auszuwählen, <<daten/daten-importieren/sync-typen/elasticSync-artikel#1910, stellst du den Barcode-Typ als Abgleichfeld ein>>. Und anstatt den Barcode manuell im Artikeldatensatz einzutragen, <<daten/daten-importieren/sync-typen/elasticSync-artikel#2320, trägst du den Barcode in ein Zuordnungsfeld ein>>.

[#600]
=== Barcodes automatisch aus dem Nummernkreis zuordnen

Hast du einen <<artikel/einstellungen/barcodes#200, Nummernkreis bestehend aus GTIN 13 Barcodes>> gekauft, dann kann plentymarkets deinem Artikel automatisch den nächsten verfügbaren Barcode zuordnen.

[.instruction]
Barcodes automatisch aus dem Nummernkreis zuordnen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel. +
→ Das Tab *Einstellungen* der Hauptvariante wird geöffnet.
. Wähle im Bereich *Barcode* die <<artikel/einstellungen/barcodes#100, zuvor gespeicherte GTIN 13 Barcode-Konfiguration>> aus der Dropdown-Liste.
. Klicke auf *Hinzufügen* (icon:plus[role="green"]). +
→ Der Barcode-Typ wird hinzugefügt und in der Liste angezeigt.
. Klicke auf *GTIN generieren* (icon:cog[role="darkGrey", stack="arrow-right", stackPosition="lr"]), um automatisch den nächsten verfügbaren Barcode einzufügen.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Mehrere Varianten gleichzeitig bearbeiten
====
//nachdem die Artikel-Verwalten-Seite überarbeitet wurde, passe den Links an, da sie vermutlich nicht zum gleichen Ziel führen sollen.
Um GTINs mehrere Varianten gleichzeitig zuzuordnen, nutze die <<artikel/artikel-verwalten#330, Varianten-Gruppenfunktion>> oder die <<artikel/artikel-verwalten#330, Varianten-Stapelverarbeitung>>.
====

[#700]
=== Fehlerbehebung: Doppelte Barcodes ermitteln

Es ist technisch möglich, den selben Barcode für mehrere Varianten zu speichern. Wenn doppelte Barcodes nicht gewünscht sind, kannst du mehrmals vergebene Codes ermitteln und korrigieren. Dabei wird nach identischen Codes mit demselben Barcode-Typ gesucht, die verschiedenen Varianten zugeordnet sind.

[.instruction]
Doppelte Barcodes ermitteln:

. Öffne das Menü *Einrichtung » Artikel » Barcode*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Das Tab *Doppelte Barcodes* wird geöffnet.
. Klicke in den Filteroptionen auf *Suchen* (icon:search[role="blue"]), um alle doppelten Barcodes aufzulisten. +
*__Tipp:__* Gib in die Suchfelder eine *Varianten-ID* oder einen *Barcode* ein, um die Suche einzugrenzen. +
→ Die doppelten Codes werden angezeigt.
. Klicke auf die Variante, deren Code du ändern möchtest. +
→ Die Variante wird geöffnet.
. Bearbeite den Code der Variante.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#800]
== Etiketten

Artikeletiketten sind Hinweisschildchen auf einem Artikel oder der Artikelverpackung. Sie enthalten Informationen wie Preis, Inhalt, Barcode etc. Zuerst <<artikel/einstellungen/barcodes#900, gestaltest du deine Etiketten>> mit Hilfe von Vorlagen. Dann <<artikel/einstellungen/barcodes#1000, generierst du die Etiketten>> und druckst sie aus.

[#900]
=== Etiketten gestalten

Etiketten gestaltest du mit Hilfe von Vorlagen. Jede Vorlage enthält Informationen über die Größe des Etiketts, die Daten, die auf dem Etikett erscheinen sollen, und wo die einzelnen Daten auf dem Etikett positioniert werden sollen. Du kannst bis zu 10 Etikettenvorlagen speichern.

[.instruction]
Etikettenvorlage erstellen:

. Öffne das Menü *Einrichtung » Artikel » Etiketten*.
. Klappe den Bereich *Neue Vorlage* auf (icon:plus-square-o[role="darkGrey"]).
. Nimm die Einstellungen vor. Beachte <<tabelle-etikettenvorlage-erstellen>>. +
*_Tipp:_* Auf den Etiketten werden nur Werte ausgegeben, für die X- und Y-Koordinaten gespeichert wurden.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Etikettenvorlage wird erstellt.

[TIP]
.Mit dem X-Y-Koordinatensystem arbeiten
====
Gib mit Hilfe der X-Y-Koordinaten an, _welche Informationen_ auf dem Etikett erscheinen sollen und _wo jede Information_ positioniert werden soll.

*_Welche Info_*: Auf den Etiketten werden nur Werte ausgegeben, für die X- und Y-Koordinaten gespeichert wurden. Gib also Koordinaten für jede Information ein, die auf dem Etikett erscheinen soll.

*_Position der Info_*: Gib Koordinaten ein, um Artikeldaten auf dem Etikett zu positionieren. Die Werte orientieren sich am Koordinatensystem mit X- und Y-Achse. Die X-Achse verläuft von links nach rechts und die Y-Achse von oben nach unten. Nullwerte liegen also links und oben.
====

[TIP]
.Erscheinungsbild des Etiketts bestimmen
====
Möchtest du die Artikeldaten in normaler oder fetter Schrift darstellen? Sollen die Daten klein oder groß sein? Verwende die Dropdown-Listen, um die Schriftgröße und Schriftschnitt festzulegen.

Möchtest du den Titel von bestimmten Artikelparametern anzeigen? Soll der Text umgebrochen werden, wenn er die Breite des Etiketts überschreitet? Setze dazu Häkchen (icon:check-square[role="blue"]) neben den Optionen *Titel verbergen* und *Zeilenumbruch erlauben*.
====

[[tabelle-etikettenvorlage-erstellen]]
.Etikettenvorlage erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Name*
|Name für das Etikett eingeben.

|[#sprache]*Sprache*
|Sprache für das Etikett wählen. Standardmäßig ist die Systemsprache voreingestellt.

|*Zeichensatz*
|Zeichensatz wählen.

|*Seite*
|Seitenbreite und -höhe in Millimeter eingeben. Bei Verwendung von <<automatisierung/prozesse/drucker#50, Etikettendruckern>> kann die Seitengröße gleich der Etikettengröße sein.

|*Seitenrand*
|Seitenränder links und oben in Millimeter eingeben.

|*Etikett*
|Breite und Höhe des Etiketts in Millimeter eingeben. Die Größe des Etiketts muss zu den Werten der Seitengröße und der Zeilen- und Spaltenanzahl passen.

|*Zeilen pro Seite*
|Anzahl der Zeilen pro Seite eingeben.

|*Spalten pro Seite*
|Anzahl der Spalten pro Seite eingeben.

|*Sprache*
|Koordinaten eintragen, um <<artikel/einstellungen/barcodes#sprache, die ausgewählte Sprache>> auf dem Etikett anzuzeigen.

|*Artikel-ID*; +
*Varianten-ID*; +
*Variantenname*; +
*Externe Varianten-ID*; +
*Modell*; +
*Nummer der Hauptvariante*; +
*Artikelname*
|Koordinaten eintragen, um die Artikeldaten auf dem Etikett anzuzeigen.

|*Barcode*; +
*GTIN-Barcode*; +
*ISBN*
|Koordinaten eintragen, um den Barcode auf dem Etikett anzuzeigen. Setze ein Häkchen neben der Option *GTIN darstellen*, um die GTIN unter dem Barcode anzuzeigen.

|*1. Preis*; +
*2. Preis*
|Aktivieren, um den Preis der Variante anzuzeigen. Wählen, ob der Preistyp *Verkaufspreis* oder der Preistyp *UVP* angezeigt werden soll. Außerdem wählen, welcher Verkaufspreis angezeigt werden soll. +
*_Hinweis:_* Wird der Preistyp *UVP* gewählt, wird unabhängig vom gewählten Verkaufspreis immer der UVP der Variante ausgegeben.

|*Grundpreis*
|Aktivieren, um den Grundpreis der Variante anzuzeigen. Wählen, ob der Grundpreis des Preistyps *Verkaufspreis* oder der Grundpreis des Preistyps *UVP* angezeigt werden soll. Außerdem wählen, welcher Verkaufspreis angezeigt werden soll. +
*_Hinweis:_* Wird der Preistyp *UVP* gewählt, wird unabhängig vom gewählten Verkaufspreis immer der UVP der Variante ausgegeben. +
*_Hinweis:_* Wenn *Preis* und *Grundpreis* angezeigt werden sollen sicherstellen, dass für beide Optionen derselbe Preistyp und/oder Verkaufspreis gewählt wird.

|*Attribute*
|Setze ein Häkchen neben der Option *Attributnamen ausblenden*, um nur den Attributwert anzuzeigen. Der Attributname wird ausgeblendet.

|*Lagerort*
|Koordinaten eintragen, um den <<warenwirtschaft/wareneingaenge-verwalten#200, vorgeschlagenen Lagerort der Variante>> auf dem Etikett anzuzeigen. +
Öffne das Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Lager* und stelle sicher, dass du einen Lagerort im Feld *Lagerortvorschlag* eingestellt hast. Wurde kein Lagerort für eine Variante gewählt, wird der Standard-Lagerort stattdessen automatisch als Platzhalter-Lagerort verwendet. +
<<artikel/einstellungen/barcodes#1050, Erzeuge danach ein Etikett>> für den Lagerortvorschlag, indem du auf das Etikettensymbol (icon:barcode[role="blue"]) weiter rechts klickst.

|*Bestand*; +
*Einheit*; +
*Währung*;
|Koordinaten eintragen, um die Artikeldaten auf dem Etikett anzuzeigen.

|*Artikelbild*
|Koordinaten für die Positionierung des Artikelbildes eingeben. Maximalwerte für Höhe und Breite des Bildes eingeben. Wenn das Bild größer als die eingegebenen Werte ist, wird das Bild proportional eingepasst, damit das Bild nicht verzerrt angezeigt wird. +
Position des Artikelbildes wählen, um das Bild für Etiketten zu verwenden. Standardmäßig ist *Position 0* voreingestellt. Die Artikelbildpositionen werden im Tab *Bilder* eines Artikels festgelegt. Wenn eine Position gewählt wurde, zu der kein Bild verfügbar ist, wird das erste verfügbare Bild, mit Position 0 beginnend, verwendet.

|*Artikel-Freitextfeld 1 bis 4*
|<<artikel/artikel-verwalten#70, Freitextfeld>> wählen, damit der Text auf dem Etikett angezeigt wird.

|*Freitextfeld 1 bis 4*
|Zusätzliche Freitextfelder einrichten. Text in Feld eingeben. Der eingegebene Text wird auf dem Etikett angezeigt.

|*Grafik*
|Koordinaten für die Positionierung der Grafik eingeben. Maximalwerte für Höhe und Breite des Bildes eingeben. Wenn die Grafik größer als die eingegebenen Werte ist, wird die Grafik proportional eingepasst, damit die Grafik nicht verzerrt angezeigt wird. +
Grafiken im Menü *CMS » Webspace* hochladen. Die URL der Grafik aus dem Webspace kopieren und in das Feld *URL* einfügen.

2+|*Auftragsbezogene Daten*

|*Auftrags-ID*; +
*Externe Auftrags-ID*; +
*Lieferland*; +
*Artikelanzahl*
|Auftragsbezogene Parameter einrichten, um diese Parameter auf dem Etikett anzuzeigen.
|====

[TIP]
.Testseite drucken
====
Je nach Drucker weichen einige Ausdrucke auch bei einer korrekt eingerichteten Vorlage von den Einstellungen ab. Drucke daher beim Einrichten der Vorlage Probedrucke auf Normalpapier. Korrigiere die Positionen, bis du mit dem Ergebnis zufrieden bist, bevor du Etikettenpapier verwendest.
====

[#1000]
=== Etiketten erzeugen und drucken

Möchtest du das Etikett für eine _bestimmte Variante_ oder für alle _Artikel eines bestimmten Auftrags_ generieren? Möchtest du das Artikeletikett _manuell_ oder _automatisch_ generieren? Es gibt viele verschiedene Möglichkeiten, Etiketten zu erstellen.

* Du erzeugst manuell ein <<artikel/einstellungen/barcodes#1050, Etikett für einen bestimmten Lagerort>>.
* Du erzeugst manuell ein <<artikel/einstellungen/barcodes#1100, Etikett für eine bestimmte Variante>>.
* Du erzeugst manuell <<artikel/einstellungen/barcodes#1200, Etiketten für alle Artikel eines bestimmten Auftrags>>.
* Du druckst Artikeletiketten manuell <<artikel/einstellungen/barcodes#1300, über die plentymarkets App>> aus.
* Du druckst <<artikel/einstellungen/barcodes#1400, Etiketten automatisch beim Wareneingang>> aus.

[#1050]
==== Etikett für einen bestimmten Lagerort generieren

[.instruction]
Etikett für einen Lagerort generieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Öffne die Variante.
. Klicke auf den Tab *Lager*.
. Stelle sicher, dass du im Feld *Lagerortvorschlag* einen Lagerort ausgewählt hast.
. Klicke auf das Etikettensymbol (icon:barcode[role="blue"]) weiter rechts. +
→ Das Fenster *Etiketten generieren* wird geöffnet.
. Gib ein, wie viele Etiketten generiert werden sollen.
. Wähle die Etikettenvorlage aus der Dropdown-Liste.
. Klicke auf *Etiketten generieren* (icon:cog[role="darkGrey", stack="arrow-right", stackPosition="lr"]). +
→ Eine PDF-Datei mit der gewählten Anzahl der Etiketten wird generiert.

[TIP]
.Warum sehe ich auf meinen Etiketten immer nur den Standard-Lagerort?
====
Hast du einen Lagerortvorschlag für die Variante gespeichert? Öffne die Variante und klicke auf den Tab *Lager*. Stelle sicher, dass du im Feld *Lagerortvorschlag* einen Lagerort ausgewählt hast. Wurde kein Lagerort für eine Variante gewählt, wird der Standard-Lagerort stattdessen automatisch als Platzhalter-Lagerort verwendet.

Hast du auf das richtige Etikettensymbol geklickt? Klicke auf das Etikettensymbol (icon:barcode[role="blue"]) weiter rechts im Tab *Lager*. Klickst du stattdessen auf das Etikettensymbol in der obere Artikel-Symbolleiste, wird der Standard-Lagerort auf deinem Etikett fälschlicherweise angezeigt. Denk daran, dass jede Variante an einem anderen Ort gelagert werden kann. Mit anderen Worten, kann ein Artikel mehrere Lagerorte haben. Wenn du also ein Etikett für den gesamten Artikel generierst, weiß plentymarkets nicht, welcher Lagerort vorgesehen ist, und verwendet stattdessen den Standard-Lagerort.
====

[#1100]
==== Etikett für eine bestimmte Variante generieren

[.instruction]
Etikett für eine Variante generieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Öffne die Variante.
. Klicke in der _untere Symbolleiste_ auf das Etikettensymbol (icon:barcode[role="blue"]). +
→ Das Fenster *Etiketten generieren* wird geöffnet.
. Gib ein, wie viele Etiketten generiert werden sollen.
. Wähle die Etikettenvorlage aus der Dropdown-Liste.
. Klicke auf *Etiketten generieren* (icon:cog[role="darkGrey", stack="arrow-right", stackPosition="lr"]). +
→ Eine PDF-Datei mit der gewählten Anzahl der Etiketten wird generiert.

[TIP]
.Etiketten für alle Varianten eines Artikels generieren
====
Klicke in der _obere Symbolleiste_ auf das Etikettensymbol (icon:barcode[role="blue"]), um Etiketten für alle Varianten eines Artikels zu generieren.
====

[#1200]
==== Etiketten für alle Artikel eines Auftrags generieren

Sobald du eine Etikettenvorlage fertig erstellt hast, erscheint eine neue Option. Verwende diese Option, um Etiketten für alle Artikel eines bestimmten Auftrags zu generieren.

[.instruction]
Etiketten für alle Artikel eines Auftrags generieren:

. Öffne das Menü *Einrichtung » Artikel » Etiketten*.
. Klappe die Vorlage auf (icon:plus-square-o[role="darkGrey"]).
. Gib die Auftrags-ID ein.
. Klicke auf *Vorschau* (icon:eye[role="blue"]). +
→ Eine PDF-Datei mit Etiketten für die im Auftrag enthaltenen Artikel wird generiert.

[#1300]
==== Etiketten über die plentymarkets App drucken

Benutzt du die plentymarkets App? Dann kannst du mit deinem mobilen Gerät nach <<app/funktionen/artikelsuche#400, Artikeln suchen und Etiketten drucken>>.

[#1400]
==== Etiketten automatisch beim Wareneingang

Möchtest du Etiketten beim Wareneingang automatisch drucken? Dann erstelle <<automatisierung/prozesse/prozesse-einrichten#, einen plentymarkets-Prozess>> und füge <<automatisierung/prozesse/aktionen#150, die Aktion Artikeletikett>> hinzu.
