= Eigenschaften und Merkmale
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Merkmal, Merkmale, Merkmalgruppe, Merkmalgruppen, Aufpreis, Aufpreise, Bestellmerkmal, Bestellmerkmale, Bestellmerkmalen, Einfachauswahl, Mehrfachauswahl, Merkmale erstellen, Merkmal erstellen, Merkmaltyp, Merkmal-Typ, Merkmalverknüpfung, Merkmalwert, Merkmalwerte, Eigenschaft, Eigenschaften, Variant, Variante, Varianten, Kontakt, Kontakte, Lagerort, Lagerorte, Eigenschaft erstellen, Bereich, Eigenschaftstyp, Eigenschaft-Typ, Eigenschaftsgruppe, Eigenschaft bearbeiten, Auftragseigenschaft, Pfand, Pfandbetrag, Pfandbeträge, Zusatzkosten, zusätzliche Kosten anzeigen, Auswahleigenschaft, Multiselect, Aufpreistyp, Attribut, Attribute, Charakteristik, Charakteristika, Charakteristiken, Produkte charakterisieren, Artikel charakterisieren
:description: Lerne, wie du die technischen Features eines Produkts hervorhebst.
:url: artikel/einstellungen/eigenschaften
:position: 30
:id: I13JJLO
:author: team-item

//ToDo - after live - alle Links auf die Seite einmal prüfen
//ToDo - after live - includes
//ToDo - after live - fragen, ob die Positionsnummer eine Auswirkung hat
//ToDo - after live - Thorsten fragen, ob die Auswahleigenschaften exportiert werden können
//ToDo - after live - Bereich "Optionen" auf Richtigkeit prüfen
//ToDo - after live - look for a better icon than chain/link
//ToDo - after live - make sure the explanations are all correct: follow all the steps, insb. gruppen verknüpfen
//ToDo - after live - delete unnecessary comments
//ToDo - after live - Bei Verknüpfen, den Typ "Zeichenkette" prüfen - Tab Texte oder Eigenschaften? Wie viele Zeichen sind zulässig?
//ToDo - after live - Ankerpunkte einmal alle glatt ziehen und alle Links auf die Seite entsprechend anpassen (etwa 40 Dateien)

////
zuletzt bearbeitet 16.06.2021
////

Manche Artikel stechen aus der Masse heraus. Sei es eine Uhr, die wasserdicht ist, oder ein Lautsprecher, der mit Bluetooth ausgestattet ist.
Solche Charakteristiken werden in plentymarkets als Eigenschaften und Merkmale bezeichnet.

Mit Hilfe von Eigenschaften und Merkmalen kannst du z.B.:

* die technischen Features eines Produkts hervorheben (z.B. Bluetooth, WLAN).
* <<artikel/frontend-artikelsuche-verwalten#, Webshop-Filter einrichten>>. Deine Kunden verwenden dann diese Filter, um ihre Suchergebnisse im plentyShop zu verfeinern (z.B. nur die Lautsprecher sehen, die Bluetooth-fähig sind).
* <<artikel/anwendungsfaelle/personalisierte-artikel#, personalisierte Artikel>> zum Verkauf anbieten.

[#10]
== Hintergrund-Wissen

Merkmale, Eigenschaften und Attribute: Was ist der Unterschied?

* <<artikel/einstellungen/eigenschaften#100, Merkmale>> charakterisieren _ganze Artikel_.
Ist also ein Artikel z.B. in rot, blau oder grün erhältlich, dann gilt das Merkmal für alle drei Varianten.
Merkmale sind wenig flexibel, veraltet und werden schrittweise durch Eigenschaften ersetzt.
//Wir empfehlen daher, dass du bereits jetzt deine <<Merkmale in Eigenschaften umwandelst>>.
* <<artikel/einstellungen/eigenschaften#500, Eigenschaften>> charakterisieren _spezifische Varianten_.
Ist also ein Artikel z.B. in rot, blau oder grün erhältlich, dann kann die Eigenschaft für eine, zwei oder alle drei der Varianten gelten.
Eigenschaften bieten daher mehr Flexibilität.
* <<artikel/einstellungen/attribute#, Attribute>> sind zum Beispiel die verschiedene Farben und Größen, in denen deine Produkte erhältlich sind.
Mit Hilfe von Attributen kannst du deine Produkte charakterisieren und gleichzeitig auch verkaufbare Varianten erzeugen, wie z.B. ein T-Shirt in der Farbe rot und in Größe S.

//lass drin, könnte hilfreich sein als Erklärung Eigenschaft vs Attribute nachdem die Merkmale wegfallen
//Merkmale und Eigenschaften sind _passive Charakteristiken_ eines Artikels. Das heißt, dass sie nicht an den Warenbestand gekoppelt sind.
//Attribute hingegen erzeugen verkaufbare Varianten, die alle unterschiedliche Lagerbestände haben können. Beispielsweise kann die rote Variante ausverkauft sein, während die blaue noch auf Lager ist.

[#500]
== Eigenschaften

Diese Seite erklärt Eigenschaften, die zur Charakterisierung von Produkten verwendet werden.
Eigenschaften können aber auch für die nähere Charakterisierung von <<crm/kontakte-verwalten#950, Kontakte>> oder <<warenwirtschaft/lager-einrichten#850, Lagerorte>> verwendet werden.
Klicke auf die Links, um mehr über diese andere Anwendungsfälle zu erfahren.

[TIP]
.Wie viele Eigenschaften kann ich maximal erstellen?
====
Du kannst bis zu 500 Varianteneigenschaften erstellen und mit Varianten verknüpfen.
====

[#530]
[discrete]
==== Ablauf

[.tabs]
====
Manuelle Erstellung::
+
--

. <<artikel/einstellungen/eigenschaften#600, Erstelle Eigenschaften>> wie WLAN oder Bluetooth.
. <<artikel/einstellungen/eigenschaften#1200, Gruppiere die Eigenschaften>> bei Bedarf.
Zum Beispiel, um den Überblick in deinem plentymarkets-Backend zu behalten.
. <<artikel/einstellungen/eigenschaften#1400, Verknüpfe die Eigenschaften>> mit den passenden Varianten. Zum Beispiel, verknüpfe die Bluetooth-Eigenschaft mit deinen Bluetooth-fähigen Produkten.
//. <<artikel/frontend-artikelsuche-verwalten#, Erstelle Webshop-Filter>> bei Bedarf. Zum Beispiel, damit deine Kunden nach Bluetooth-fähigen Produkten im plentyShop filtern können.

--
Import::
+
--

plentymarkets enthält ein <<daten/daten-importieren/ElasticSync#, Import-Tool>>, mit dem du Eigenschaften importieren kannst.
Die Idee ist ganz einfach.
Anstatt Eigenschaftsdaten in plentymarkets manuell zu speichern, trägst du die gleiche Informationen in eine CSV-Datei ein und importierst diese Datei dann in dein System.

. Erstelle Eigenschaften wie WLAN oder Bluetooth und gruppiere sie bei Bedarf.
Verwende dazu die Import-Typen <<daten/daten-importieren/sync-typen/elasticSync-eigenschaften#, Eigenschaften>> und <<daten/daten-importieren/sync-typen/elasticSync-eigenschaften-auswahlwerte#, Auswahlwerte>>.

. Verknüpfe die Eigenschaften mit den passenden Varianten. Zum Beispiel, verknüpfe die Bluetooth-Eigenschaft mit deinen Bluetooth-fähigen Produkten.
Verwende dazu den <<daten/daten-importieren/sync-typen/elasticSync-artikel#2410, Import-Typ Artikel>>.
//. Erstelle Webshop-Filter bei Bedarf. Zum Beispiel, damit deine Kunden nach Bluetooth-fähigen Produkten im plentyShop filtern können.
//Verwende dazu den <<daten/daten-importieren/sync-typen/elasticSync-facetten#, Import-Typ Facetten>>.
//Siehe dazu auch ein <<daten/daten-importieren/elasticsync-best-practices/facetten#, Praxisbeispiel>>.
--
////
Kataloge und Assistenten bei Amazon und OTTO::
+
--
Nutzt du bereits das neue Katalog-Tool, um deine Produktdaten an einen Markt wie Amazon oder OTTO zu exportieren? Falls ja, dann kannst du Eigenschaften direkt im Katalog-Assistenten anlegen und mit dem Marktplatz verknüpfen.

Erfahre mehr am Beispiel des <<maerkte/amazon/variantendaten-exportieren#, Amazon-Katalog-Assistenten>>.

--
////
====

//video?

[#600]
=== Neue Eigenschaften erstellen

Erstelle die Eigenschaften, die du zur Charakterisierung deiner Produkte verwenden möchtest, z.B. Bluetooth oder WLAN.

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
//→ Eine Übersicht der zuvor erstellten Eigenschaften wird angezeigt.
. Klicke auf icon:plus[role="darkGrey"] *Eigenschaft erstellen*.
. Passe die Einstellungen an deine Bedürfnisse an.
. Speichere (icon:save[role="darkGrey"]) die Einstellungen.

[#650]
==== Details

[cols="1,4a"]
|======
|Einstellung |Erläuterung

| *ID*
|Sobald du die Eigenschaft erstmalig gespeichert hast, erhält sie automatisch eine fortlaufende und einzigartige ID.
Die ID kann nicht geändert werden.

| *Bereich*
|Wofür möchtest du die Eigenschaft nutzen?
Wähle den entsprechenden Bereich aus der Dropdown-Liste.
Je nachdem, welchen Bereich du hier wählst, ändern sich die weiteren Einstellungen im Menü.

*_Hinweis_*: Diese Einstellung kann nach dem Speichern nicht mehr geändert werden.

*_Hinweis_*: Diese Handbuchseite erklärt Eigenschaften vom Bereich *Artikel*.
Solche Eigenschaften werden zur Charakterisierung von Produkten verwendet.
Eigenschaften können aber auch für die nähere Charakterisierung von <<crm/kontakte-verwalten#950, Kontakte>> oder <<warenwirtschaft/lager-einrichten#850, Lagerorte>> verwendet werden.
Klicke auf die Links, um mehr über diese andere Anwendungsfälle zu erfahren.

| *Eigenschaftstyp*
|Welche Art von Eigenschaft möchtest du anlegen? Wähle den Eigenschaftstyp aus der Dropdown-Liste.

*_Hinweis_*: Diese Einstellung kann nach dem Speichern nicht mehr geändert werden.

[cols="1,4a"]
!======
!Typ !Wofür ist der Typ geeignet?

! *Kein*
!Der Name der Eigenschaft kann im plentyShop angezeigt werden.
Dies eignet sich, z.B. um die technischen Besonderheiten einer Variante hervorzuheben (Bluetooth, WLAN).
//* Filter zu erstellen (nur Bluetooh-fähige Produkte in die Suchergebnisse berücksichtigen)
//* <<artikel/einstellungen/eigenschaften#intable-bestellmerkmal, Als Bestellmerkmal>>: Eignet sich, z.B. um Kunden <<artikel/anwendungsfaelle/personalisierte-artikel#200, zusätzliche Optionen und Dienstleistungen>> während des Bestellvorgangs anzubieten.

! *Datum*
!Ein Datum kann im plentyShop angezeigt werden.

! *Datei*
!Eine Datei kann für die Variante verfügbar gemacht werden, z.B. eine Montageanleitung.

//<<artikel/einstellungen/eigenschaften#intable-bestellmerkmal, Als Bestellmerkmal>>: Ermöglicht es Kunden, z.B. <<artikel/anwendungsfaelle/personalisierte-artikel#100, ein eigenes Bild hochzuladen>>, das auf ein T-Shirt gedruckt werden soll.

! *Ganze Zahl*
!Eine ganze Zahl kann im plentyShop angezeigt werden.
Eignet sich, z.B. um ein Gewicht oder eine Länge anzugeben.
Beispielsweise ein HDMI-Kabel mit einer Länge von 10 m.

! *Kommazahl*
!Eine Zahl mit Kommastellen kann im plentyShop angezeigt werden.
Eignet sich z.B. um eine Versionsnummer anzugeben.
Beispielsweise Kopfhörer mit Bluetooth-Version 5.0.

! *Zeichenkette*
!Eine alphanumerische Zeichenkette kann im plentyShop angezeigt werden.
//Eine Zahl mit Kommastellen kann im plentyShop angezeigt werden.
//Eigent sich, z.B. um Maßangaben im plentyShop anzuzeigen. Beispielsweise ein Krug, der 1,4 Liter fasst.

! *HTML*
!Ein Text mit Formatierung kann im plentyShop angezeigt werden.
Eignet sich z.B., um variantenspezifische Produktbeschreibungen zu erstellen.

//<<artikel/einstellungen/eigenschaften#intable-bestellmerkmal, Als Bestellmerkmal>>: Ermöglicht es Kunden, z.B. <<artikel/anwendungsfaelle/personalisierte-artikel#100, einen persönlichen Text einzugeben>>, der auf ein T-Shirt gedruckt werden soll.

! *Text*
!Ein Text ohne Formatierung kann im plentyShop angezeigt werden.
Eignet sich z.B., um variantenspezifische Produktbeschreibungen zu erstellen.

! *Auswahl*
!Eignet sich zum Beispiel zur Umsetzung von Ja/Nein-Fragen.
Anders gesagt, dieser Typ eignet sich für Situationen, in denen es zwar mehrere Auswahlmöglichkeiten gibt - wie Ja und Nein -, aber nur eine davon auf die Variante zutrifft.

*_Anwendungsbeispiel_*: +
Stell dir vor, du verkaufst Kopfhörer.
Einige der Kopfhörer verfügen über ein integriertes Mikrofon.
Bei diesen Kopfhörern willst du also die Information "Mikrofon: Ja" anzeigen lassen und bei den anderen "Mikrofon: Nein".

. <<artikel/einstellungen/eigenschaften#710, Erstens>>: Erstellst du die verschiedenen Auswahlmöglichkeiten - wie Ja und Nein.
. <<artikel/einstellungen/eigenschaften#1400, Zweitens>>: Während du die Eigenschaft mit deinen Varianten verknüpfst, gibst du an, welche Kopfhörer den Wert "Ja" haben sollen und welche den Wert "Nein".
//. <<artikel/frontend-artikelsuche-verwalten#, Drittens>> erstellst du Webshop-Filter, die es deinen Kunden ermöglichen, gezielt nach Varianten mit einer bestimmten Wasserfestigkeitsstufe zu suchen.

! *Mehrfachauswahl*
!Eignet sich für Situationen, in denen es mehrere Auswahlmöglichkeiten gibt, und mehrere davon auf die Variante zutreffen.

*_Anwendungsbeispiel_*: +
Stell dir vor, du verkaufst Bluetooth-Kopfhörer.
Es gibt viele verschiedene Bluetooth-Profile.
Einige deiner Kopfhörer unterstützen alle Profile, andere unterstützen nur ein oder zwei Profile.
Du willst für jeden Kopfhörer angeben, welche Profile unterstützt werden, z.B. "Bluetooth Profil: A2DP, AVRCP, HFP, HSP".

. <<artikel/einstellungen/eigenschaften#710, Erstens>>: Erstellst du die verschiedenen Auswahlmöglichkeiten, d.h. alle Bluetooth-Profile.
. <<artikel/einstellungen/eigenschaften#1400, Zweitens>>: Während du die Eigenschaft mit deinen Varianten verknüpfst, gibst du an, welche Kopfhörer welche Profile unterstützen.
//. <<artikel/frontend-artikelsuche-verwalten#, Drittens>> erstellst du Webshop-Filter, die es deinen Kunden ermöglichen, gezielt nach Varianten mit solchen Besonderheiten zu suchen.
!======

| *Position*
|Welche Eigenschaft soll als erste, zweite, dritte, usw. angezeigt werden? Gib eine Positionsnummer in dieses Feld ein. Wenn eine Variante mehrere Eigenschaften hat, werden die Eigenschaften aufsteigend nach Positionsnummern in deinem plentyShop dargestellt.
|======

[#700]
==== Namen

[cols="1,4a"]
|======
|Einstellung |Erläuterung

| *Name*
|Gib einen Namen für die Eigenschaft in der angegebenen Sprache ein.
Dieser Name kann für Kunden <<artikel/einstellungen/eigenschaften#1500, im plentyShop sichtbar gemacht werden>>. Dies hängt davon ab, wie du das Layout mit ShopBuilder gestaltest.

*_Hinweis_*: Klicke auf icon:plus[role="darkGrey"], um den Namen in weitere Sprachen zu übersetzen.

| *Beschreibung*
|Gib eine Beschreibung für die Eigenschaft in der angegebenen Sprache ein.
Diese Beschreibung kann für Kunden <<artikel/einstellungen/eigenschaften#1500, im plentyShop sichtbar gemacht werden>>. Dies hängt davon ab, wie du das Layout mit ShopBuilder gestaltest.

Eine mögliche Anwendung ist die Darstellung eines erklärenden Textes für eine Bestelleigenschaft.

*_Hinweis_*: Klicke auf icon:plus[role="darkGrey"], um die Beschreibung in weitere Sprachen zu übersetzen.

| icon:plus[role="darkGrey"]
|Ist dein plentyShop in mehreren Sprachen verfügbar?

. Klicke auf icon:plus[role="darkGrey"] und wähle eine Sprachversion aus der Dropdown-Liste.
. Gib Übersetzungen für den Namen und die Beschreibung ein.

//sichtbar im Webshop je nachdem wie man ShopBuilder konfiguriert?
//Die Beschreibung wird angezeigt, wenn du mit dem Mauszeiger auf das Merkmal zeigst.
|======

[#710]
==== Auswahlwerte

[IMPORTANT]
.Nicht für jeden Eigenschaftstyp sichtbar
====
Diesen Bereich siehst du nur, wenn du mit einer Eigenschaft vom Typ *Auswahl* oder *Mehrfachauswahl* arbeitest.
Dieser Bereich ist für alle anderen Eigenschaftstypen unsichtbar.
====

Hier definierst du die einzelnen Werte, die zur Auswahl stehen.

. Klicke auf *Auswahlwert anlegen* (icon:plus[role="darkGrey"]). +
→ Das Fenster *Auswahlwert anlegen* wird geöffnet.
. Gib einen Namen für den Wert in der angegebenen Sprache ein.
. Wähle bei Bedarf eine Positionsnummer.
. Klicke auf *Speichern*. +
→ Der Wert wird erstellt und in der Übersicht angezeigt.
Der Wert erhält automatisch eine fortlaufende und einzigartige ID, die nicht geändert werden kann.
. Ist dein plentyShop in mehreren Sprachen verfügbar?
Dann klicke auf den Wert, um eine Detailansicht zu öffnen.
Dort kannst du Übersetzungen und Beschreibungen für den Wert eingeben.

[#780]
==== Amazon

Bei Bedarf kannst du hier <<maerkte/amazon/varianten-vorbereiten#1390, die Eigenschaft mit Amazon-Felder verknüpfen>>.
Dazu muss vorab im Bereich *Sichtbarkeit* eine Amazon-Herkunft aktiviert werden.

. Klicke auf *Verknüpfung hinzufügen* (icon:plus[role="darkGrey"]).
. Wähle mit Hilfe der drei Dropdown-Listen die passende Amazon-Plattform, Kategorie und Feld.
. Wiederhole den Vorgang, wenn du weitere Amazon-Felder verknüpfen möchtest.
. *Speichere* (icon:save[role="darkGrey"]) die Einstellungen. +
→ Die Eigenschaft ist mit Amazon verknüpft und wird beim nächsten Artikelexport übertragen.

[#730]
==== Gruppen

Soll die Eigenschaft einer oder mehreren <<artikel/einstellungen/eigenschaften#1200, Gruppen>> zugewiesen werden?
Falls ja, wähle die passende Gruppe aus der Dropdown-Liste aus.
Die gewählten Gruppen werden hier als sogenannte "Chips" dargestellt.
Klicke auf icon:close[set=darkGrey], um eine Gruppe wieder zu entfernen.

*_Hinweis_*: Diese Dropdown-Liste enthält nur <<artikel/einstellungen/eigenschaften#1200, Eigenschaftsgruppen, die bereits angelegt wurden>>.

[discrete]
===== Mehrere Eigenschaften einer Gruppe zuordnen

Es würde viel Zeit in Anspruch nehmen, manuell die Gruppe für jede einzelne Eigenschaft auszuwählen.
 plentymarkets enthält eine Funktion, mit der du mehrere Eigenschaften gleichzeitig einer Gruppe zuordnen kannst.

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Wähle die Eigenschaften (icon:check-square[role="blue"]), die du der Gruppe zuordnen möchtest.
. Klicke auf *Gruppen verknüpfen* (icon:chain[set=darkGrey]). +
→ Das Fenster *Gruppen verknüpfen* wird geöffnet.
. Wähle eine oder mehrere Eigenschaftsgruppen (icon:check-square[role="blue"]).
. Klicke auf *Link*. +
→ Die gewählten Eigenschaften werden den Gruppen zugeordnet.

[#740]
==== Sichtbarkeiten

[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Herkunft*
|Auf welchen Verkaufskanälen soll die Eigenschaft sichtbar sein?
Wähle (icon:check-square[role="blue"]) eine, mehrere oder alle Herkünfte.
Gib ein Wort in die Suchleiste ein, um die Ergebnisliste in Echtzeit einzugrenzen.

*_Hinweis_*: Die Dropdown-Liste enthält nur aktivierte Auftragsherkünfte.
Falls du also einen bestimmten Marktplatz in der Liste nicht finden kannst, öffne das Menü *Einrichtung » Aufträge » Auftragsherkunft* und stelle sicher, dass der Markt aktiviert wurde (icon:check-square[role="blue"]).

| *Mandant*
|Soll die Eigenschaft nur für bestimmte Mandanten (Shops) gelten? Falls ja, dann wähle alle Shops (icon:check-square[role="blue"]), für die diese Eigenschaft gelten soll.
Gib ein Wort in die Suchleiste ein, um die Ergebnisliste in Echtzeit einzugrenzen.

*_Hintergrund-Info_*: Mit plentymarkets kannst du mehrere Webshops, d.h. <<webshop/mandanten-verwalten#, mehrere Mandanten>>, mit nur einer Software verwalten. Somit ist es möglich, über ein plentymarkets System mehrere unterschiedliche Geschäftsbereiche zu realisieren. Das ist ein großer Vorteil. Aber es bedeutet auch, dass du plentymarkets immer mitteilen musst, für welchen Webshop die Eigenschaft gilt.

| *Überall anzeigen*
|Wo soll die Eigenschaft angezeigt werden? Wähle die Bereiche (icon:check-square[role="blue"]), wo deine Kunden die Eigenschaft sehen sollen.
|====

[#720]
==== Optionen

[cols="1,4a"]
|====
|Einstellung |Erläuterung

| *Einheiten*
|Handelt es sich bei der Eigenschaft um etwas wie ein Gewicht oder eine Länge, z.B. ein HDMI-Kabel mit einer Länge von 10 m?
Falls ja, dann wähle die passende <<artikel/einstellungen/einheiten#, Einheit>>.

| *Steuersatz*
|

[cols="1,4a"]
!======

! *Keine Besteuerung*
!Wähle diese Option (icon:check-square[role="blue"]), wenn _keine Mehrwertsteuer_ auf den eingegebenen Aufpreis berechnet werden soll.

Eine mögliche Anwendung ist z.B. die Darstellung von Pfandbeträgen, bei denen keine Mehrwertsteuer angewendet wird.
//In Rechnungen etc. erscheinen Merkmale, bei denen diese Option gewählt wurde, als eigene Position mit der ID -2.

! *Steuersatz von Variante*
!Wähle diese Option (icon:check-square[role="blue"]), wenn auf den eingegebenen Aufschlag _dieselbe Mehrwertsteuer_ berechnet werden soll, wie für die Variante.

Welcher Mehrwertsteuersatz für die Variante gespeichert ist, siehst du im Menü <<artikel/artikel-verwalten#280, Artikel » Artikel bearbeiten » [Variante öffnen] » Tab: Einstellungen » Bereich: Kosten » Dropdown-Liste: Umsatzsteuer>>.

! *Steuersatz A, B, C, D*
!Wähle diese Option (icon:check-square[role="blue"]), wenn _ein bestimmter Mehrwertsteuersatz_ auf den eingegebenen Aufschlag berechnet werden soll.

Die einzelnen Umsatzsteuersätze findest du im Menü <<auftraege/buchhaltung#550, Einrichtung » Mandant » [Mandant wählen] » Standorte » [Standort wählen] » Buchhaltung » Tab: Umsatzsteuersätze » [Konfiguration öffnen]>>.
!======

|
|

[cols="1,4a"]
!======

! *Bestelleigenschaft*
!Wähle diese Option (icon:check-square[role="blue"]), wenn die Eigenschaft dazu verwendet werden soll, dass Kunden ihre <<artikel/anwendungsfaelle/personalisierte-artikel#, Bestellungen personalisieren>> können.
Zum Beispiel:

* durch die Eingabe eines persönlichen Gravurtextes.
* durch die Auswahl zusätzlicher Serviceleistungen gegen Aufpreis.

! *zusätzliche Kosten anzeigen*
!
//stimmt das überhaupt, es ist nur eine Mutmaßung.
//fest steht, dass wenn man diese Option anklickt, dann wird die Eigenschaft im Artikeldatensatz unter Portlet "Bestelleigenschaften" sortiert
icon:check-square[role="blue"] = Der Aufpreis wird zur Gesamtsumme addiert.
Dabei wird auch der genaue Wert des Aufpreises separat angegeben.

icon:square-o[role="blue"] = Der Aufpreis wird zur Gesamtsumme addiert.
Der genaue Wert des Aufpreises wird aber nicht gesondert erwähnt.

! *als Mehrzeiliges Textfeld anzeigen*
!
//was macht diese Option?

//|[#intable-preiskalk]*Preiskalkulationseigenschaft*
//|Eigenschaften vom Typ "Ganze Zahl" oder "Kommazahl" können in <<artikel/einstellungen/preise#1000, Preiskalkulationen>> verwendet werden.
//Wähle diese Option (icon:check-square[role="blue"]), wenn du eine Eigenschaft vom Typ "Ganze Zahl" oder "Kommazahl" erstellst und sie in Preiskalkulationen verfügbar sein soll.
!======

| *Aufpreis*
|Willst du diese Eigenschaft gegen einen Aufpreis anbieten?
Aufpreise werden zum Beispiel erhoben für:

* zusätzliche Optionen oder Dienstleistungen, die Kunden bei der Bestellung wählen können.
* Pfandbeträge auf Glasflaschen

Wenn für die Eigenschaft ein Aufpreis berechnet werden soll, dann gib den Wert hier ein.
Aufpreise werden im plentyShop in der Artikelansicht und im Bestellvorgang automatisch zum Artikelpreis hinzu addiert.
//Standardmäßig ist 0,00 eingestellt und kein Aufpreis wird berechnet.
|====

[#1200]
=== Eigenschaften gruppieren

Wenn du viele Eigenschaften hast, dann kannst du sie gruppieren und somit leichter den Überblick in deinem plentymarkets-Backend behalten.

[TIP]
.Beispiel: Verkaufskanäle gruppieren
====
Stell dir zum Beispiel vor, du verwendest manche Eigenschaften für den Markt Amazon und andere für deinen plentyShop.
In diesem Fall könntest du eine Gruppe namens Amazon erstellen und eine andere Gruppe namens plentyShop.
====

////
diese Einleitung erst anzeigen nachdem Bestelleigenschaften veröffentlicht wurden

Es gibt zwei typische Anwendungsfälle für Eigenschaftsgruppen. Einerseits, wenn du viele Eigenschaften hast, dann kannst du sie gruppieren und somit leichter den Überblick in deinem plentymarkets-Backend behalten.

Andererseits kommen Eigenschaftsgruppen zum Einsatz, wenn du <<artikel/anwendungsfaelle/personalisierte-artikel#, personalisierte Artikel>> in deinem plentyShop verkaufst.
Mithilfe von Eigenschaftsgruppen kannst du angebotene Optionen oder Dienstleistungen unter einer Rubrik zusammenfassen.

[TIP]
.Beispiel: Mögliche Verzierungen gruppieren
====
Stell dir zum Beispiel vor, du verkaufst Trauringe. Deine Kunden können gegen Aufpreis einen optionalen Gold- oder Diamantbesatz wählen.
Um diese Optionen übersichtlich darzustellen, legst du eine Eigenschaftsgruppe namens "Verzierungen" an.
Innerhalb dieser Gruppe können Kunden die Optionen "Goldrand" oder "Diamantenrand" wählen.
====
////

[#1250]
==== Neue Gruppe erstellen

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen*.
//→ Eine Übersicht der zuvor erstellten Gruppen wird angezeigt.
. Klicke auf icon:plus[role="darkGrey"] *Gruppe erstellen*.
. Passe die Einstellungen an deine Bedürfnisse an.
. Speichere (icon:save[role="darkGrey"]) die Einstellungen.

//→ Die Gruppe wird erstellt und in der Übersicht angezeigt.
//Die Gruppe erhält automatisch eine fortlaufende und einzigartige ID, die nicht geändert werden kann.

[#1260]
===== Details

[cols="1,4a"]
|====
|Einstellung |Erläuterung

| *ID*
|Sobald du die Gruppe erstmalig gespeichert hast, erhält sie automatisch eine fortlaufende und einzigartige ID.
Die ID kann nicht geändert werden.

| *Position*
|Welche Eigenschaftsgruppe soll als erste, zweite, dritte, usw. angezeigt werden? Gib eine Positionsnummer in dieses Feld ein.
Wenn eine Variante Eigenschaften aus mehreren Gruppen hat, werden die Gruppen aufsteigend nach Positionsnummern in deinem plentyShop dargestellt.

| *Gruppentyp*
|Diese Option gilt nur für Bestelleigenschaften vom Typ *Kein*.
Wie viele Zusatzoptionen oder Dienstleistungen sollen deine Kunden aus der Gruppe wählen können?

[cols="1,4a"]
!======

! *Keine*
!Deine Kunden sehen die Bestelleigenschaften im plentyShop. Sie können jedoch nichts auswählen.

! *Select*
!Deine Kunden sehen eine Dropdown-Liste im plentyShop. Sie können nur eine Option aus der Liste auswählen.

! *Multiselect*
!Deine Kunden sehen Checkboxen im plentyShop. Sie können mehrere Optionen ankreuzen.
!======

| *Aufpreistyp*
|Hast du vor, Zusatzoptionen oder Dienstleistungen gegen Aufpreis anzubieten? Falls ja, dann wähle, ob der Aufpreis als Prozentsatz oder als Festbetrag behandelt werden soll, z.B. 5% oder 5 EUR.
|====

[#1270]
===== Namen

[cols="1,4a"]
|======
|Einstellung |Erläuterung

| *Name*
|Gib einen Namen für die Eigenschaftsgruppe in der angegebenen Sprache ein.
Dieser Name kann für Kunden <<artikel/einstellungen/eigenschaften#1500, im plentyShop sichtbar gemacht werden>>. Dies hängt davon ab, wie du das Layout mit ShopBuilder gestaltest.

*_Hinweis_*: Klicke auf icon:plus[role="darkGrey"], um den Namen in weitere Sprachen zu übersetzen.

| *Beschreibung*
|Gib eine Beschreibung für die Eigenschaftsgruppe in der angegebenen Sprache ein.
Diese Beschreibung kann für Kunden <<artikel/einstellungen/eigenschaften#1500, im plentyShop sichtbar gemacht werden>>. Dies hängt davon ab, wie du das Layout mit ShopBuilder gestaltest.

Eine mögliche Anwendung ist die Darstellung eines erklärenden Textes für eine Bestelleigenschaftsgruppe.

*_Hinweis_*: Klicke auf icon:plus[role="darkGrey"], um die Beschreibung in weitere Sprachen zu übersetzen.

| icon:plus[role="darkGrey"]
|Ist dein plentyShop in mehreren Sprachen verfügbar?

. Klicke auf icon:plus[role="darkGrey"] und wähle eine Sprachversion aus der Dropdown-Liste.
. Gib Übersetzungen für den Namen und die Beschreibung ein.

//sichtbar im Webshop je nachdem wie man ShopBuilder konfiguriert?
//Die Beschreibung wird angezeigt, wenn du mit dem Mauszeiger auf das Merkmal zeigst.
|======


[#1300]
==== Eigenschaften einer Gruppe zuordnen

plentymarkets enthält eine Funktion, mit der du mehrere Eigenschaften gleichzeitig einer Gruppe zuordnen kannst.

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. Wähle die Eigenschaften (icon:check-square[role="blue"]), die du der Gruppe zuordnen möchtest.
. Klicke auf *Gruppen verknüpfen* (icon:chain[set=darkGrey]). +
→ Das Fenster *Gruppen verknüpfen* wird geöffnet.
. Wähle eine oder mehrere Eigenschaftsgruppen (icon:check-square[role="blue"]).
. Klicke auf *Link*. +
→ Die gewählten Eigenschaften werden den Gruppen zugeordnet.

[#1350]
==== Bestehende Gruppen suchen

Zuvor erstellte Eigenschaftsgruppen werden in einer Übersicht angezeigt.

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen*.
. *_Option 1_*: Klicke auf icon:search[role="blue"] *Suchen*, um eine Liste aller Gruppen zu sehen.
. *_Option 2_*: Klicke auf icon:filter[role="darkGrey"], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.
. Klicke auf eine Gruppe in der Ergebnisliste, um eine Detailansicht zu öffnen.
Dort kannst du die Einstellungen der Gruppe ändern.

//Mit Hilfe von Filtern kannst du die Suchergebnisse einschränken und nur die Gruppen sehen, die bestimmte Kriterien erfüllen.

[cols="1,4"]
|====
|Einstellung |Erläuterung

| *ID*
|Gib eine ID ein, um nach der Gruppe mit genau dieser ID zu suchen.

*_Hintergrund-Info_*: Bei der Erstellung erhält jede Gruppe automatisch eine fortlaufende und einzigartige ID.

| *Name*
|Gib einen Namen ein, um nach Gruppen mit diesem Namen zu suchen.
Es ist auch möglich, nach Teilen des Namens zu suchen.

//*_Beispiel_*: Die Eingabe von "start" würde eine Eigenschaft namens "Startdatum" und "Startpaket" finden.

| *RESET*
|Setzt die gewählten Filterkriterien zurück.

| *SUCHEN*
|Führt die Suche aus. Die gefundenen Gruppen werden in der Übersicht angezeigt.

*_Tipp_*: Setze keine Filter, wenn du alle Gruppen in der Übersicht sehen möchtest.
|====

[#1360]
==== Gruppen wieder löschen

Bereits erstellte Gruppen werden im Menü *Einrichtung » Einstellungen » Eigenschaften » Gruppen* angezeigt.
Gruppen können hier auch gelöscht werden.

. Wähle die Gruppen (icon:check-square[role="blue"]), die du löschen möchtest.
. Klicke oben links auf *Eigenschaftsgruppen löschen* icon:trash[role="darkGrey"].
. Bestätige deine Entscheidung.

*_Hinweis_*: Die Eigenschaften, die den Gruppen zugeordnet sind, bleiben erhalten.

[#1400]
=== Eigenschaften mit Varianten verknüpfen

[#1410]
==== Wo verknüpfen?

Eigenschaften werden je nach Typ in einem anderen Tab verknüpft.
Öffne den Artikeldatensatz und klicke in der unteren Tab-Leiste auf das Tab *Eigenschaften* oder *Texte*. Welches Tab hängt vom Eigenschaftstyp ab.

[cols="1,2", width=100%]
|====
|Eigenschaftstyp |Wo wird die Eigenschaft verknüpft?

|Text +
HTML +
Zeichenkette
|<<artikel/artikel-verwalten#5000, Tab: Texte>>

|Kein +
Ganze Zahl +
Kommazahl +
Auswahl +
Mehrfachauswahl +
Datum +
Datei
|<<artikel/artikel-verwalten#4800, Tab: Eigenschaften>>
|====

[#1420]
==== Wie verknüpfen?

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. <<artikel/einleitung/suche#400, Suche>> und öffne die Variante.
. Klicke in der unteren Tab-Leiste auf das Tab *Eigenschaften* oder *Texte*.
Welches Tab hängt vom Eigenschaftstyp ab.
. Klicke in das Eingabefeld *Eigenschaften*. +
→ Eine Dropdown-Liste mit den verfügbaren Eigenschaften wird angezeigt.
. Wähle die passenden Eigenschaften (icon:check-square[role="blue"]).
. Klicke auf Hinzufügen (icon:plus[role="green"]). +
→ Die Eigenschaften werden hinzugefügt.
. Falls erforderlich, gib zusätzliche Informationen über die Eigenschaft ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +

//check this to make sure it's true
[TIP]
.Vererbung
======
Standardmäßig werden Eigenschaften und Werte von der Hauptvariante an die Untervarianten weitergegeben.
Wenn du eigene Eigenschaften an den Untervarianten pflegen möchtest, deaktiviere zuerst die Vererbung und verknüpfe dann die Eigenschaft.

Die Eigenschaften und Werte werden gemeinsam vererbt. Du kannst also nur alle oder keine Werte vererben.
======

[#1440]
[discrete]
===== Zusätzliche Informationen speichern

Je nach Anwendungsfall kann es nötig sein, zusätzliche Informationen zu speichern. Zum Beispiel:

* Handelt es sich bei der Eigenschaft um ein Gewicht oder eine Länge, dann muss der numerische Wert noch eingegeben werden.
* Handelt es sich um eine Produktbeschreibung für eine bestimmte Variante, dann muss der Text noch eingegeben werden.

[cols="1,4a"]
|======
|Einstellung |Erläuterung

2+| *Tab: Eigenschaften*

| *Name*
|Hier siehst du den Namen der Eigenschaft. Dies ist rein informativ und kann hier nicht geändert werden.

| *Typ*
|Hier siehst du den Eigenschaftstyp. Dies ist rein informativ und kann hier nicht geändert werden.

[cols="1,1a"]
!======
!Anzeige !Bedeutung

! *empty*
!Kein

! *int*
!Ganze Zahl

! *float*
!Kommazahl

! *selection*
!Auswahl

! *multiSelection*
!Mehrfachauswahl

! *date*
!Datum

! *file*
!Datei

!======

*_Hinweis_*: Je nach Eigenschaftstyp wirst du unterschiedlich mit der Spalte *Wert* interagieren.

| *Wert*
|Wie du mit dieser Spalte interagierst, hängt vom Eigenschaftstyp ab.

[cols="1,4a"]
!======
!Typ !Interaktion

! *empty*
!Keine weitere Bearbeitung nötig.

! *int*
!Gib den numerischen Wert als ganze Zahl ein, z.B. 350 Zentimeter.

Zulässig sind ganze Zahlen zwischen -2.147.483.648 und 2.147.483.647.

! *float*
!Gib den numerischen Wert als Kommazahl ein, z.B. 3,5 Meter.

Zulässig sind 8 Vor- und 4 Nachkommastellen.

! *selection*
!Wähle die passende Option aus der Dropdown-Liste.

! *multiSelection*
!Kreuze alle passenden Optionen an.

! *date*
!Klicke in das Eingabefeld und wähle das Datum aus dem Kalender aus. Oder gib das Datum manuell im folgenden Format ein: TT.MM.JJ

! *file*
!Klicke auf icon:upload[set=plenty, role=purple] *Dateien hochladen* und lade die passende Datei hoch.
!======

| *Aktionen*
|Klicke auf *Löschen* (icon:minus-circle[role="red"]), um die Eigenschaftsverknüpfung zu löschen. Die Eigenschaft selbst wird nicht gelöscht. Sie wird lediglich von der Variante getrennt.

*_Vererbungslogik_*: Beim Löschen einer Eigenschaftsverknüpfung greift die folgende Logik:
//test this to make sure it's true

* Entfernst du die Eigenschaft aus einer _Hauptvariante_? Dann wird die Eigenschaft auch aus allen Untervarianten entfernt, die diese Eigenschaft zuvor geerbt hatten.
* Enternst du die Eigenschaft aus einer _Unterviariante_, für die die Vererbung aktiviert ist? Dann wird die Vererbung deaktiviert. Die verbleibenden Eigenschaften werden nicht mehr geerbt, sondern werden direkt an der Untervariante gespeichert.
//* Löschst du die Eigenschaft einer _Hauptvariante_, werden die Verknüpfung und der Wert für alle Varianten des Artikels gelöscht, die die Eigenschaften der Hauptvariante erben.

//Wenn du die Eigenschaft einer Variante löschst, für die die Vererbung aktiviert ist, wird die Vererbung deaktiviert und die verbleibenden Eigenschaften werden direkt an der Variante gespeichert. +

2+| *Tab: Texte*

| *Text*
|Gib bis zu 65.535 Zeichen reinen Text ein.

*_Hinweis_*: Die Standardsprache deines plentymarkets Systems wird vorausgewählt.
Wenn du Text in einer anderen Sprache speichern willst, dann wähle die Sprache aus der Dropdown-Liste oben aus.

| *HTML*
|Gib bis zu 65.535 Zeichen Text ein.
Formatiere den Text wie gewünscht.
Wähle dazu deinen bevorzugten Editor aus der Dropdown-Liste oben rechts.

*_Hinweis_*: Die Standardsprache deines plentymarkets Systems wird vorausgewählt.
Wenn du Text in einer anderen Sprache speichern willst, dann wähle die Sprache aus der Dropdown-Liste oben aus.

| *Zeichenkette*
|Gib eine alphanumerische Zeichenkette ein.

| *Aktionen*
|Klicke auf *Löschen* (icon:minus-circle[role="red"]), um die Eigenschaftsverknüpfung zu löschen. Die Eigenschaft selbst wird nicht gelöscht. Sie wird lediglich von der Variante getrennt.

*_Vererbungslogik_*: Beim Löschen einer Eigenschaftsverknüpfung greift die folgende Logik:
//test this to make sure it's true

* Entfernst du die Eigenschaft aus einer _Hauptvariante_? Dann wird die Eigenschaft auch aus allen Untervarianten entfernt, die diese Eigenschaft zuvor geerbt hatten.
* Enternst du die Eigenschaft aus einer _Unterviariante_, für die die Vererbung aktiviert ist? Dann wird die Vererbung deaktiviert. Die verbleibenden Eigenschaften werden nicht mehr geerbt, sondern werden direkt an der Untervariante gespeichert.
//* Löschst du die Eigenschaft einer _Hauptvariante_, werden die Verknüpfung und der Wert für alle Varianten des Artikels gelöscht, die die Eigenschaften der Hauptvariante erben.

//Wenn du die Eigenschaft einer Variante löschst, für die die Vererbung aktiviert ist, wird die Vererbung deaktiviert und die verbleibenden Eigenschaften werden direkt an der Variante gespeichert. +

|======

[#1500]
=== Eigenschaften im plentyShop anzeigen

Wie deine Eigenschaften im <<webshop/ceres-einrichten#, plentyShop>> angezeigt werden, hängt davon ab, wie du die Einstellungen mit <<webshop/shop-builder#, ShopBuilder>> konfiguriert hast. Dieses Video bietet eine kurze Demonstration.

.Eigenschaften im plentyShop ausgeben
video::360260315#t=24m18s[vimeo]

[#800]
=== Mit bestehenden Eigenschaften arbeiten

[#810]
==== Eigenschaften suchen

Zuvor erstellte Eigenschaften werden in einer Übersicht angezeigt.

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*.
. *_Option 1_*: Klicke auf icon:search[role="blue"] *Suchen*, um eine Liste aller Eigenschaften zu sehen.
. *_Option 2_*: Klicke auf icon:filter[role="darkGrey"], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.
. Klicke auf eine Eigenschaft in der Ergebnisliste, um eine Detailansicht zu öffnen.
Dort kannst du die Einstellungen der Eigenschaft ändern.

//Mit Hilfe von Filtern kannst du die Suchergebnisse einschränken und nur die Gruppen sehen, die bestimmte Kriterien erfüllen.

[cols="1,4a"]
|====
|Einstellung |Erläuterung

| *ID*
|Gib eine ID ein, um nach der Eigenschaft mit genau dieser ID zu suchen.

*_Hintergrund-Info_*: Bei der Erstellung erhält jede Eigenschaft automatisch eine fortlaufende und einzigartige ID.

| *Name*
|Gib einen Namen ein, um nach Eigenschaften mit diesem Namen zu suchen.
Es ist auch möglich, nach Teilen des Namens zu suchen.

*_Beispiel_*: Die Eingabe von "start" würde eine Eigenschaft namens "Startdatum" und "Startpaket" finden.

//| *Sprache*
//|Wähle eine Sprache, um nach Eigenschaften zu suchen, für die ein Name in dieser Sprache gespeichert ist.

| *Gruppen*
|Wähle eine oder mehrere Gruppen aus (icon:check-square[role="blue"]), um nach den Eigenschaften dieser Gruppen zu suchen.

//* *Nicht gruppiert* = Es wird nach Eigenschaften gesucht, die keiner Gruppe zugeordnet sind.
//* *Gruppiert* = Es wird nach Eigenschaften gesucht, die einer Gruppe zugeordnet sind.

*_Hinweis_*: Diese Liste enthält nur bereits erstellten Gruppen. Hast du noch keine <<artikel/einstellungen/eigenschaften#1200, Eigenschaftsgruppen erstellt>>, siehst du hier auch keine Gruppennamen.

| *Bereich*
|Wähle einen oder mehrere Bereiche aus (icon:check-square[role="blue"]), um nach den Eigenschaften zu suchen, die für diesen Bereich verwendet werden.

| *Typ*
|Wähle einen oder mehrere Eigenschaftstypen aus (icon:check-square[role="blue"]), um nach den Eigenschaften dieses Typs zu suchen.

| *RESET*
|Setzt die gewählten Filterkriterien zurück.

| *SUCHEN*
|Führt die Suche aus. Die gefundenen Eigenschaften werden in der Übersicht angezeigt.

*_Tipp_*: Setze keine Filter, wenn du alle Eigenschaften in der Übersicht sehen möchtest.
|====

[#1600]
==== Eigenschaften exportieren

Möchtest du Informationen über Eigenschaften aus deinem plentymarkets System exportieren? Das geht in zwei Schritten:

* Zuerst verwendest du den <<daten/daten-exportieren/FormatDesigner#, FormatDesigner>>, um ein sogenanntes Datenformat zu erstellen.
** Verwende dabei den Formattyp <<daten/daten-exportieren/FormatDesigner/format-typen/eigenschaften#, Eigenschaften>>, wenn du die eigentlichen Eigenschaften und Eigenschaftsgruppen exportieren willst.
** Verwende dabei den Formattyp *item* mit den Datenfeldern <<daten/daten-exportieren/FormatDesigner/format-typen/artikel#1600, VariationEigenschaften>>, wenn du die Verknüpfungen zwischen Eigenschaften und Varianten exportieren willst.
* In einem zweiten Schritt verwendest du den <<daten/daten-exportieren/elastischer-export#, Elastischen Export>>, um die soeben erstellten Datenformate zu exportieren.

[#900]
==== Eigenschaften wieder löschen

Bereits erstellte Eigenschaften werden im Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* angezeigt.
Eigenschaften können hier auch gelöscht werden.

. Wähle die Eigenschaften (icon:check-square[role="blue"]), die du löschen möchtest.
. Klicke oben links auf *Eigenschaften löschen* (icon:trash[role="darkGrey"]).
. Bestätige deine Entscheidung.

[IMPORTANT]
.Auch Eigenschaften, die derzeit mit Varianten verknüpft sind, können gelöscht werden
====
Es ist möglich, Eigenschaften zu löschen, egal ob sie derzeit mit einer Variante verknüpft sind oder nicht.
Überlege es dir also gut, bevor du Eigenschaften löschst. Stelle sicher, dass die Eigenschaft für keine Varianten mehr benötigt wird.
====

[#910]
=== Fragen und Antworten

[.collapseBox]
.*Wie viele Eigenschaften kann ich maximal erstellen?*
--

Du kannst bis zu 500 Varianteneigenschaften erstellen und mit Varianten verknüpfen.

--

////
[#560]
[discrete]
==== Anzahl der Eigenschaften ist begrenzt

in the limits page, either use an include to display the limits for properties or add a comment to remind that it needs to be changed here if the limit changes
Wie viele Varianteneigenschaften du erstellen und verknüpfen kannst, hängt davon ab, welche plentymarkets Edition du gebucht hast.
Erfahre <<mehr über Limits>> und wie du bei Bedarf zu einer anderen Edition wechseln kannst.

[cols="1,1,1"]
|====
|Edition |Erstellen ^1^ |Verknüpfen ^2^

|*Basic / Zero / Advanced*
|500
|???

|*Classic / Partneredition*
|1000
|???

|*Flex*
|1500
|???

|*Plus / Enterprise*
|2000
|???
|====
[.small]#1: Maximum Anzahl an Eigenschaften vom Bereich "Artikel", die in plentymarkets erstellt werden können# +
[.small]#2: Maximum Anzahl an Eigenschaften, die mit einer einzigen Variante verknüpft werden können.#


lass drin für später Unterscheidung Attribute vs Eigenschaften
Im Gegensatz zu <<artikel/einstellungen/attribute#, Attributen>> sind die Eigenschaften passiv. Eigenschaften dienen also nicht dazu, Varianten zu erstellen. Eigenschaften sind nicht an den Warenbestand gekoppelt und in der Artikelansicht im plentyShop nicht wählbar.
////


[.collapseBox]
.*Ich finde meine Eigenschaft nicht im Artikeldatensatz. Wo ist sie?*
--

Eigenschaften werden je nach Typ in einem anderen Tab verknüpft.
Öffne den Artikeldatensatz und klicke in der unteren Tab-Leiste auf das Tab *Eigenschaften* oder *Texte*. Welches Tab hängt vom Eigenschaftstyp ab.

[cols="1,2", width=100%]
|====
|Eigenschaftstyp |Wo wird die Eigenschaft verknüpft?

|Kurztext +
Text
|<<artikel/artikel-verwalten#5000, Tab: Texte>>

|Kein +
Ganze Zahl +
Kommazahl +
Auswahl +
Mehrfachauswahl +
Datum +
Datei
|<<artikel/artikel-verwalten#4800, Tab: Eigenschaften>>
|====

--

[.collapseBox]
.*Merkmale, Eigenschaften und Attribute: Was ist der Unterschied?*
--

* <<artikel/einstellungen/eigenschaften#100, Merkmale>> charakterisieren _ganze Artikel_.
Ist also ein Artikel z.B. in rot, blau oder grün erhältlich, dann gilt das Merkmal für alle drei Varianten.
Merkmale sind wenig flexibel, veraltet und werden schrittweise durch Eigenschaften ersetzt.
//Wir empfehlen daher, dass du bereits jetzt deine <<Merkmale in Eigenschaften umwandelst>>.
* <<artikel/einstellungen/eigenschaften#500, Eigenschaften>> charakterisieren _spezifische Varianten_.
Ist also ein Artikel z.B. in rot, blau oder grün erhältlich, dann kann die Eigenschaft für eine, zwei oder alle drei der Varianten gelten.
Eigenschaften bieten daher mehr Flexibilität.
* <<artikel/einstellungen/attribute#, Attribute>> sind zum Beispiel die verschiedene Farben und Größen, in denen deine Produkte erhältlich sind.
Mit Hilfe von Attributen kannst du deine Produkte charakterisieren und gleichzeitig auch verkaufbare Varianten erzeugen, wie z.B. ein T-Shirt in der Farbe rot und in Größe S.

//lass drin, könnte hilfreich sein als Erklärung Eigenschaft vs Attribute nachdem die Merkmale wegfallen
//Merkmale und Eigenschaften sind _passive Charakteristiken_ eines Artikels. Das heißt, dass sie nicht an den Warenbestand gekoppelt sind.
//Attribute hingegen erzeugen verkaufbare Varianten, die alle unterschiedliche Lagerbestände haben können. Beispielsweise kann die rote Variante ausverkauft sein, während die blaue noch auf Lager ist.

--

[.collapseBox]
.*Kann ich Eigenschaften zur Charakterisierung von Lagerorten und Kontakten verwenden?*
--

Ja.
Eigenschaften können auch für die nähere Charakterisierung von <<crm/kontakte-verwalten#950, Kontakte>> oder <<warenwirtschaft/lager-einrichten#850, Lagerorte>> verwendet werden.
Klicke auf die Links, um mehr über diese andere Anwendungsfälle zu erfahren.

--

////
[.collapseBox]
.*Migration?*
--


== Migration Merkmale zu Eigenschaften
siehe Kanbanize-Karte für Merkmale -> Eigenschaften Assistenten
auch ganz unten als eigenes Kapitel und irgendwo im Merkmal Kapitel


--
////

////
[.collapseBox]
.*Personalisierte Artikel verkaufen?*
--

Text

--
////

[.collapseBox]
.*Kann ich Webshop-Filter anhand von Eigenschaften erstellen?*
--

Ja. Stell dir vor, du hast bereits:

* Eigenschaften wie WLAN oder Bluetooth angelegt.
* Die Eigenschaften mit den passenden Varianten verknüpft.
Zum Beispiel, die Bluetooth-Eigenschaft wurde mit deinen Bluetooth-fähigen Produkten verknüpft.

Jetzt kannst du Filter erstellen.
Zum Beispiel, damit deine Kunden nach Bluetooth-fähigen Produkten im plentyShop filtern können.
<<artikel/frontend-artikelsuche-verwalten#, Weitere Informationen zur Vorgehensweise>>.

--

[#100]
== Merkmale

Manche Artikel stechen aus der Masse heraus. Sei es eine Uhr, die wasserdicht ist, oder ein Lautsprecher, der mit Bluetooth ausgestattet ist.
Solche Charakteristiken werden in plentymarkets als Merkmale bezeichnet.

Mit Hilfe von Merkmalen kannst du z.B.:

* die technischen Features eines Produkts hervorheben (z.B. Bluetooth, WLAN).
* <<artikel/frontend-artikelsuche-verwalten#, Webshop-Filter einrichten>>. Deine Kunden verwenden dann diese Filter, um ihre Suchergebnisse im plentyShop zu verfeinern (z.B. nur die Lautsprecher sehen, die Bluetooth-fähig sind).
* <<artikel/anwendungsfaelle/personalisierte-artikel#, personalisierte Artikel>> zum Verkauf anbieten.

[TIP]
.Merkmale, Eigenschaften und Attribute: Was ist der Unterschied?
====
* <<artikel/einstellungen/eigenschaften#100, Merkmale>> charakterisieren _ganze Artikel_.
Ist also ein Artikel z.B. in rot, blau oder grün erhältlich, dann gilt das Merkmal für alle drei Varianten.
Merkmale sind wenig flexibel, veraltet und werden schrittweise durch Eigenschaften ersetzt.
//Wir empfehlen daher, dass du bereits jetzt deine <<Merkmale in Eigenschaften umwandelst>>.
* <<artikel/einstellungen/eigenschaften#500, Eigenschaften>> charakterisieren _spezifische Varianten_.
Ist also ein Artikel z.B. in rot, blau oder grün erhältlich, dann kann die Eigenschaft für eine, zwei oder alle drei der Varianten gelten.
Eigenschaften bieten daher mehr Flexibilität.
* <<artikel/einstellungen/attribute#, Attribute>> sind zum Beispiel die verschiedene Farben und Größen, in denen deine Produkte erhältlich sind.
Mit Hilfe von Attributen kannst du deine Produkte charakterisieren und gleichzeitig auch verkaufbare Varianten erzeugen, wie z.B. ein T-Shirt in der Farbe rot und in Größe S.

//lass drin, könnte hilfreich sein als Erklärung Eigenschaft vs Attribute nachdem die Merkmale wegfallen
//Merkmale und Eigenschaften sind _passive Charakteristiken_ eines Artikels. Das heißt, dass sie nicht an den Warenbestand gekoppelt sind.
//Attribute hingegen erzeugen verkaufbare Varianten, die alle unterschiedliche Lagerbestände haben können. Beispielsweise kann die rote Variante ausverkauft sein, während die blaue noch auf Lager ist.
====

[#200]
=== Merkmalgruppen erstellen

Es gibt zwei typische Anwendungsfälle für Merkmalgruppen. Einerseits, wenn du viele Merkmale hast, dann kannst du sie gruppieren und somit leichter den Überblick in deinem plentymarkets-Backend behalten.

Andererseits kommen Merkmalgruppen zum Einsatz, wenn du <<artikel/anwendungsfaelle/personalisierte-artikel#, personalisierte Artikel>> in deinem plentyShop verkaufst.
Mithilfe von Merkmalgruppen kannst du angebotene Optionen oder Dienstleistungen unter einer Rubrik zusammenfassen.

[TIP]
.Beispiel: Mögliche Verzierungen gruppieren
====
Stell dir zum Beispiel vor, du verkaufst Trauringe. Deine Kunden können gegen Aufpreis einen optionalen Gold- oder Diamantbesatz wählen.
Um diese Optionen übersichtlich darzustellen, legst du eine Merkmalgruppe namens "Verzierungen" an.
Innerhalb dieser Gruppe können Kunden die Optionen "Goldrand" oder "Diamantenrand" wählen.
====

[.instruction]
Neue Merkmalgruppe erstellen:

. Öffne das Menü *Einrichtung » Artikel » Merkmale*.
. Wechsele in das Tab *Neue Merkmalgruppe*.
. Nimm die Einstellungen vor. Beachte <<table-create-characteristic-groups>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-create-characteristic-groups]]
.Neue Merkmalgruppe erstellen
include::../_textblocks/tabelle/merkmalgruppe-erstellen.adoc[]

[#300]
=== Merkmale erstellen

Erstelle zunächst Merkmale, um deine Produkte zu charakterisieren.
Zum Beispiel, um technische Details wie Bluetooth oder WLAN anzugeben. Oder um Zusatzoptionen und Dienstleistungen gegen Aufpreis anzubieten.

[.instruction]
Neues Merkmal erstellen:

. Öffne das Menü *Einrichtung » Artikel » Merkmale*.
. Wechsele in das Tab *Neues Merkmal*.
. Nimm die Einstellungen vor. Beachte <<table-create-characteristic>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-create-characteristic]]
.Neues Merkmal erstellen
include::../_textblocks/tabelle/merkmal-erstellen.adoc[]

[#350]
=== Merkmale mit Artikeln verknüpfen

include::../_textblocks/konfigs/merkmal-mit-artikel-verknuepfen.adoc[]

////
== Migration Merkmale zu Eigenschaften
siehe Kanbanize-Karte für Merkmale -> Eigenschaften Assistenten
auch in die FAQ Bereich von Eigenschaften und irgendwo im Merkmal Kapitel
////
