= Einheiten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Einheit, Einheiten, Maßeinheit, Maßeinheiten, Größe, Maße, Länge, Breite, ISO-Code, ISO, Dezimalzahlen, Inhalt, Grundpreis, Preis pro, Stück, Kilogramm, Gramm, Milligramm, Liter
:description: Standardmäßig sind 52 Einheiten in plentymarkets gespeichert. Lerne, wie du weitere Maßeinheiten bei Bedarf erstellst.
:url: artikel/einstellungen/einheiten
:icons: font
:position: 100
:docinfodir: /workspace/manual-adoc
:docinfo1:
:id: IHTSF1W
:author: team-item

Einheiten wie Kilogramm, Liter und Zentimeter helfen dir, die Größe oder Maße deiner Produkte zu definieren.

Standardmäßig sind 52 Einheiten nach ISO-Code in plentymarkets gespeichert. Du kannst jedoch <<artikel/einstellungen/einheiten#100, weitere Maßeinheiten bei Bedarf erstellen>> oder die bestehenden Einheiten anpassen.

Darüber hinaus kannst du Einheiten mit unterschiedlichen Mengen kombinieren und somit <<artikel/einstellungen/einheiten#200, Varianten erzeugen>>. Beispielsweise verkaufst du eine Flasche Seife, die in 50ml, 100ml oder 150ml erhältlich ist.

Sicherlich hast du auch schon den <<artikel/einstellungen/einheiten#300, Grundpreis>> gesehen, der in den Regalen der Lebensmittelgeschäfte aufgeführt ist. Der Grundpreis gibt die Kosten pro Pfund, Liter oder andere Maßeinheit an. Berechnet wird er auf Grundlage von Inhalt, Einheit und Preis des Artikels. Dargestellt werden kann er auf Vertriebskanälen und auf Artikeletiketten.

[#100]
== Neue Einheiten erstellen und bestehende anpassen

Standardmäßig sind 52 Einheiten nach ISO-Code in plentymarkets gespeichert. Wirf dir einen Blick auf die bereits vorhandenen Einheiten im Menü *Einrichtung » Artikel » Einheiten*. Erstelle bei Bedarf weitere Einheiten oder passe die bestehende Einheiten an.

[.instruction]
Neue Einheit erstellen:

. Öffne das Menü *Einrichtung » Artikel » Einheiten*.
. Klicke auf *Neu* (icon:plus[role="green"]). +
→ Das Fenster *Neue Einheit anlegen* wird geöffnet.
. Gib einen Namen ein.
. *_Optional_*: Gib eine Positionsnummer ein.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen. +
→ Die neue Einheit wird erstellt und öffnet sich automatisch.
. Passe die Einheit bei Bedarf weiter an.

[.instruction]
Bestehende Einheiten anpassen:

. Öffne das Menü *Einrichtung » Artikel » Einheiten*.
. Klicke auf eine Einheit. +
→ Die Einheit öffnet sich in einem neuen Tab.
. Nimm die Einstellungen vor. Beachte <<table-edit-units>>.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen.

[[table-edit-units]]
.Einheiten bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+| *Einstellungen*

| *Position*
|Positionsnummer der Einheit eingeben.

| *Maßeinheit (ISO)*
|Maßeinheit anhand des ISO-Codes wählen.

| *Dezimalzahlen*
|Sind Dezimalzahlen für diese Maßeinheit zulässig? Zum Beispiel macht ein halber Liter Sinn. Aber ein halber Kanister wäre dagegen nicht sinnvoll.

2+| *Sprache*

| *Name der Einheit*
|Name der Einheit in den verwendeten Sprachen eingeben.
|====

[#200]
== Einheiten kombinieren und Varianten erzeugen

Einheiten kannst du mit unterschiedlichen Mengen kombinieren und somit Varianten erzeugen. Beispielsweise verkaufst du eine Flasche Seife, die in 50ml, 100ml oder 150ml erhältlich ist.

<<artikel/import-export-anlage/anlage/neue-artikel#200, Beim Erstellen eines Artikels>> kannst du die Einheit und den Inhalt des Artikels direkt eingeben. Wenn du <<artikel/import-export-anlage/anlage/neue-artikel#400, zusätzliche Varianten erstellst>>, kannst du auch die Einheit und den Inhalt jeder Variante eingeben.

[#300]
== Grundpreis auf Vertriebskanälen und Etiketten anzeigen

Sicherlich hast du schon den Grundpreis gesehen, der in den Regalen der Lebensmittelgeschäfte aufgeführt ist.
Der Grundpreis gibt die Kosten pro Pfund, Liter oder andere Maßeinheit an.

Berechnet wird er auf Grundlage von <<artikel/artikel-verwalten#270, Einheit, Inhalt>> und <<artikel/artikel-verwalten#240, Preis>> des Artikels.
Dargestellt werden kann er <<artikel/artikel-verwalten#270, im plentyShop>>, auf Vertriebskanälen wie <<maerkte/amazon/varianten-vorbereiten#860, Amazon>>, <<maerkte/ebay/ebay-einrichten#4000, eBay>>, <<maerkte/otto/otto-market#1302, OTTO>> oder <<maerkte/plus-gartenxxl#365, Netto>> und <<artikel/einstellungen/barcodes#900, auf Artikeletiketten>>.
