= Hersteller
:lang: de
include::{includedir}/_header.adoc[]
:description: plentymarkets unterstützt dich bei der Verwaltung deiner Hersteller. Lerne, wie du deine Herstellerdaten in plentymarkets speicherst.
:url: artikel/einstellungen/hersteller
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

//später :position: 50 einfügen wenn die Seite live sein soll

//bei jeder Überarbeitung, schauen was der Stand hier ist.
//https://forum.plentymarkets.com/t/unterscheidet-plenty-zwischen-hersteller-hersteller/440009/3

Wer stellt deine Produkte her? Erhalten deine Hersteller auch eine Provision? plentymarkets unterstützt dich bei der Verwaltung deiner Hersteller.

Du kannst Herstellerdaten entweder <<artikel/einstellungen/hersteller#100, manuell in plentymarkets speichern>> oder mit einem <<artikel/einstellungen/hersteller#200, Tool namens ElasticSync importieren>>. Außerdem kannst du <<artikel/einstellungen/hersteller#300, Provisionen für deine Hersteller speichern>> und angeben, <<artikel/einstellungen/hersteller#400, wer jedes deiner Artikel herstellt>>.

[#100]
== Herstellerdaten manuell anlegen

Lege zunächst einen Datensatz für jeden deiner Hersteller an. Wenn du nur wenige Herstellerdatensätze anlegen möchtest, empfiehlt sich die manuelle Erstellung. Hast du aber dagegen viele verschiedene Hersteller, dann ist es wahrscheinlich schneller, deine <<artikel/einstellungen/hersteller#200, Herstellerdaten zu importieren>>.

[.instruction]
Neuen Hersteller manuell hinzufügen:

. Öffne das Menü *Einrichtung » Artikel » Hersteller*.
. Klicke auf icon:plus[role="green"] *Neu*. +
→ Das Tab *Neuer Hersteller* wird geöffnet.
. Gib den Herstellerdaten ein. Beachte <<tabelle-hersteller-hinzufuegen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Hersteller wird hinzugefügt.

[[tabelle-hersteller-hinzufuegen]]
.Hersteller hinzufügen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*ID*
|ID für den Hersteller eingeben oder Feld leer lassen. Wenn keine ID eingeben wird, wird dem Hersteller automatisch die nächste freie ID zugeordnet.

|*Name*
|Internen Namen des Herstellers eingeben.

|*Logo-URL*
|URL zum Logo des Herstellers eingeben. Die URL darf bis zu 2.000 Zeichen umfassen.

|*Homepage*
|URL zur Homepage des Herstellers eingeben. Die URL darf bis zu 2.000 Zeichen umfassen.

|*Straße*; +
*Haus-Nr.*; +
*PLZ*; +
*Ort*; +
*Land*; +
*Telefonnummer*; +
*Faxnummer*; +
*E-Mail*
|Adressdaten des Herstellers eingeben.

|*PIXmania-ID*; +
*Neckermann.de Enterprise-ID*; +
*Neckermann.at Enterprise-ID*; +
*Neckermann.at Cross-Docking-ID*; +
*La Redoute-ID*; +
*Netto eStores-ID*; +
*Cdiscount.com-ID*
|Hersteller-ID des Marktplatzes eingeben. Die Hersteller-IDs eines Marktplatzes erhältst du beim Einrichten des <<maerkte#, Marktplatzes>>.

|*Externer Name*
|Externen Namen für den Hersteller eingeben, um eine alternative Bezeichnung für den Export zu speichern. Beim Artikelexport zu externen Marktplätzen, zum Beispiel über das Menü *Einrichtung » Märkte » Preisportale » Exporte*, wird der hier eingegebene Name des Herstellers verwendet. Wenn kein externer Name eingegeben wurde, wird die Eingabe unter *Name* verwendet. Der externe Name wird auch zu <<webshop/webshop-einrichten/extras/findologic#, FINDOLOGIC>> übertragen und für die Suche indexiert.

|*Position*
|Position für den Hersteller eingeben. Standardmäßig wird die Position *0* vergeben. Bei gleicher Position wird innerhalb der Position nach dem Namen sortiert.

|*Kommentar*
|Optional einen internen Kommentar über den Hersteller eingeben.
|====

[TIP]
.Kann ich meine Herstellerdaten stattdessen im CRM-Bereich speichern?
====
Vielleicht hast du schon mal bemerkt, dass du <<crm/kontakte-verwalten#90, Herstellerdatensätze im CRM-Bereich anlegen>> kannst. Sei aber vorsichtig. Diese Daten werden nämlich _nicht_ hier im Menü *Einrichtung » Artikel » Hersteller* übernommen. Daher empfehlen wir dir, die Herstellerdaten im CRM-Bereich vorerst zu ignorieren.
====

[#200]
== Herstellerdaten importieren

Lege zunächst einen Datensatz für jeden deiner Hersteller an. Wenn du nur wenige Herstellerdatensätze anlegen möchtest, empfiehlt sich die <<artikel/einstellungen/hersteller#100, manuelle Erstellung>>. Hast du aber dagegen viele verschiedene Hersteller, dann ist es wahrscheinlich schneller, deine Herstellerdaten zu importieren.

Herstellerdatensätze werden mit einem <<daten/daten-importieren/ElasticSync#, Tool namens ElasticSync>> importiert. Die Idee ist ganz einfach. Anstatt Herstellerinformationen in plentymarkets manuell zu speichern, <<daten/daten-importieren/sync-typen/elasticSync-hersteller#, trägst du die gleiche Informationen in eine CSV-Datei ein>> und importierst diese Datei dann in dein System.

[#300]
== Provisionen ergänzen

Hast du die <<artikel/einstellungen/hersteller#100, Basisdaten deiner Hersteller bereits gespeichert>>? Dann bist du jetzt bereit, Provisionsmodelle bei Bedarf hinzuzufügen.

[.instruction]
Herstellerprovisionen ergänzen:

. Öffne das Menü *Einrichtung » Artikel » Hersteller*.
. Klicke auf den Stift (icon:pencil[role="yellow-background"]). +
→ Der Herstellerdatensatz wird in einem neuen Tab geöffnet.
. Wechsele in das Tab *Provisionen*.
. Klicke auf das Plus (icon:plus[role="green"]). +
→ Eine neue Zeile für Provisionen wird der Tabelle hinzugefügt.
. Gib Informationen über die Provision ein. Beachte <<tabelle-herstellerprovision-hinzufuegen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Provision wird automatisch eine ID zugewiesen.

[[tabelle-herstellerprovision-hinzufuegen]]
.Provisionen für Hersteller hinzufügen
[cols="1,2"]
|====
|Einstellung |Erläuterung

|*Mandant (Shop)*
|Für welches Unternehmen gilt die Provision? Wähle den Mandanten aus der Dropdown-Liste.

|*Herkunft*
|Für welchen Markt oder für welche Verkaufsplattform gilt die Provision? Wähle die Auftragsherkunft aus der Dropdown-Liste.

|*Provision*
|Gib die Provision in Prozent ein.
|====

[TIP]
.Provisionen auf andere Hersteller übertragen
====
Gelten für mehrere deiner Hersteller die gleichen Provisionsmodelle? Du musst nicht jede Provision manuell anlegen! Kopiere ganz einfach eine Provision und übertrage sie auf andere Hersteller.

Klicke zunächst auf *Provisionen auf andere Hersteller übertragen* (icon:files-o[role="yellow-background"]). Verwende dann Häkchen (icon:check-square[role="blue"]), um zu bestimmen, welche Provision du kopieren möchtest und auf welchen Hersteller du sie übertragen möchtest.
Klicke anschließend auf icon:save[role="green"] *Provisionen übertragen*.
====

[#400]
== Hersteller mit Artikeln verknüpfen

Nachdem du deine Herstellerdaten in plentymarkets gespeichert hast, gibst du an, wer die einzelnen Artikel hergestellt hat. Dies geschieht indem du jeden Artikel mit einem Hersteller verknüpfst.

Es gibt mehrere Möglichkeiten, Artikel mit Herstellern zu verknüpfen:

* Gib den Hersteller an, <<artikel/artikel-verwalten#20, während du manuell einen neuen Artikel erstellst>>.
* Gib den Hersteller <<artikel/artikel-verwalten#610, im Tab Global eines bestehenden Artikels>> an.
* <<artikel/artikel-verwalten#155, Verwende die Gruppenfunktion>>, um den Hersteller manuell für mehrere bestehende Artikel gleichzeitig anzugeben.
* Möchtest du deine Artikel mit ElasticSync importieren? Dann <<daten/daten-importieren/sync-typen/elasticSync-artikel#2260, gib den Hersteller jedes Artikels in der zu importierenden CSV-Datei an>>.

[#500]
== Hersteller löschen

Bevor ein Hersteller gelöscht werden kann, müssen alle Verknüpfungen zum Hersteller gelöscht werden.
Die <<artikel/artikel-verwalten#155, Artikel-Gruppenfunktion>> ist ein nützliches Werkzeug dafür.

//Um Hersteller zu löschen, müssen zunächst alle Verknüpfungen des Herstellers zu Artikeln gelöscht werden. Verwende die *Artikel-Gruppenfunktion* und gehe wie im Folgenden beschrieben vor.

[.instruction]
Verknüpfungen zum Hersteller löschen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Wähle im Filter *Hersteller* den Hersteller aus der Dropdown-Liste.
. Wähle im Filter *Aktiv* die Option *ALLE*.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Alle Artikel des Herstellers werden angezeigt.
. Wähle alle Artikel (icon:check-square[role="blue"]).
. Klicke auf *Artikel-Gruppenfunktion*. +
→ Das Fenster *Artikel-Gruppenfunktion* wird geöffnet.
. Wähle im Bereich *Global* die Option *Hersteller* (icon:check-square[role="blue"]).
. Wähle die leere Option aus der Dropdown-Liste.
. Klicke auf *Ausführen* (icon:cog[role="darkGrey", stack="arrow-right", stackPosition="lr"]). +
→ Die Herstellerverknüpfungen werden gelöscht. +
→ Die Hersteller können nun gelöscht werden.

[.instruction]
Hersteller löschen:

. Öffne das Menü *Einrichtung » Artikel » Hersteller*.
. Klicke in der Zeile des Herstellers auf *Löschen* (icon:minus-circle[role="red"]). +
→ Ein neues Fenster wird geöffnet.
. Klicke erneut auf *Löschen* (icon:minus-circle[role="red"]), um deine Entscheidung zu bestätigen. +
→ Der Hersteller wird gelöscht.
