= Hersteller
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Hersteller, Provision, Herstellerdaten, Herstellerprovision, Provisionsmodelle, Provisionsmodell, Marke, Marken, Produzent, Fabrikant
:description: plentymarkets unterstützt dich bei der Verwaltung deiner Hersteller. Lerne, wie du deine Herstellerdaten in plentymarkets speicherst.
:url: artikel/einstellungen/hersteller
:position: 50
:id: RF86X9P
:author: team-item

////
zuletzt bearbeitet 04.01.2022

bei jeder Überarbeitung, schauen was der Stand hier ist.
https://forum.plentymarkets.com/t/unterscheidet-plenty-zwischen-hersteller-hersteller/440009/3
////

Wer stellt deine Produkte her?
Welche Marken verkaufst du?
plentymarkets unterstützt dich bei der Verwaltung deiner Herstellerdaten.

[discrete]
=== Ablauf

* <<artikel/einstellungen/hersteller#100, Erstelle zuerst die nötigen Herstellerdatensätze>> manuell oder per Import.
* Füge dann <<artikel/einstellungen/hersteller#300, Provisionsmodelle>> bei Bedarf hinzu.
* Gib schließlich an, wer jedes deiner Artikel herstellt. Dies geschieht indem du deine <<artikel/einstellungen/hersteller#400, Artikel mit Hersteller verknüpfst>>.
* Sollen deine Kunden im plentyShop gezielt nach Produkten des Herstellers suchen können?
Passe die <<artikel/einstellungen/hersteller#450, plentyShop-Einstellungen>> bei Bedarf an.

[#100]
== Herstellerdatensätze erstellen

[.tabs]
====
Manuelle Erstellung::
+
--
. Öffne das Menü *Einrichtung » Artikel » Hersteller*.
. Klicke auf icon:plus[role="green"] *Neu*. +
→ Das Tab *Neuer Hersteller* wird geöffnet.
. Gib den Herstellerdaten ein.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen. +
→ Der Hersteller wird hinzugefügt.

--
Daten-Import::
+
--
plentymarkets verfügt über ein <<daten/daten-importieren/ElasticSync#, Import-Tool>>.
Die Idee ist ganz einfach. Anstatt Herstellerinformationen in plentymarkets manuell zu speichern, <<daten/daten-importieren/sync-typen/elasticSync-hersteller#, trägst du die gleiche Informationen in eine CSV-Datei ein>> und importierst diese Datei dann in dein System.

--
====

[TIP]
.Kann ich meine Herstellerdaten stattdessen im CRM-Bereich speichern?
====
Vielleicht hast du schon mal bemerkt, dass du <<crm/kontakte-verwalten#90, Herstellerdatensätze im CRM-Bereich erstellen>> kannst.
Sei aber vorsichtig.
Diese Daten werden nämlich _nicht_ im Menü *Einrichtung » Artikel » Hersteller* übernommen.
Daher empfehlen wir dir, die Herstellerdaten im CRM-Bereich vorerst zu ignorieren.
====

:manual:

[cols="1,3a"]
|====
|Einstellung |Erläuterung

| *ID*
|
include::../_textblocks/einstellungen/hersteller/id.adoc[]

| *Name*
|
include::../_textblocks/einstellungen/hersteller/name.adoc[]

| *Logo-URL*
|
include::../_textblocks/einstellungen/hersteller/logo-url.adoc[]

| *Homepage*
|
include::../_textblocks/einstellungen/hersteller/homepage.adoc[]

| *Straße*
|
include::../_textblocks/einstellungen/hersteller/strasse.adoc[]

| *Haus-Nr.*
|
include::../_textblocks/einstellungen/hersteller/haus-nr.adoc[]

| *PLZ*
|
include::../_textblocks/einstellungen/hersteller/plz.adoc[]

| *Ort*
|
include::../_textblocks/einstellungen/hersteller/ort.adoc[]

| *Land*
|
include::../_textblocks/einstellungen/hersteller/land.adoc[]

| *Telefonnummer*
|
include::../_textblocks/einstellungen/hersteller/telefonnummer.adoc[]

| *Faxnummer*
|
include::../_textblocks/einstellungen/hersteller/faxnummer.adoc[]

| *E-Mail*
|
include::../_textblocks/einstellungen/hersteller/email.adoc[]

| *PIXmania-ID*
|
include::../_textblocks/einstellungen/hersteller/pixmania.adoc[]

| *Neckermann.de Enterprise-ID*
|
include::../_textblocks/einstellungen/hersteller/neckermann.adoc[]

| *Neckermann.at Enterprise-ID*
|
include::../_textblocks/einstellungen/hersteller/neckermann.adoc[]

| *La Redoute-ID*
|
include::../_textblocks/einstellungen/hersteller/laredoute.adoc[]

| *Netto eStores-ID*
|Gib die Hersteller-ID des Marktplatzes ein.
Die Hersteller-ID erhältst du beim Einrichten des Marktplatzes.

| *Cdiscount.com-ID*
|Gib die Hersteller-ID des Marktplatzes ein.
Die Hersteller-ID erhältst du beim Einrichten des Marktplatzes.

| *Externer Name*
|
include::../_textblocks/einstellungen/hersteller/externer-name.adoc[]

| *Position*
|
include::../_textblocks/einstellungen/hersteller/position.adoc[]

| *Kommentar*
|
include::../_textblocks/einstellungen/hersteller/kommentar.adoc[]

|====

[#300]
== Provisionen ergänzen

Nachdem du die <<artikel/einstellungen/hersteller#100, Basisdaten deiner Hersteller gespeichert>> hast, bist du bereit, Provisionsmodelle bei Bedarf hinzuzufügen.

[.instruction]
Herstellerprovisionen ergänzen:

. Öffne das Menü *Einrichtung » Artikel » Hersteller*.
. Klicke auf *Bearbeiten* (icon:pencil[role="yellow"]). +
→ Der Herstellerdatensatz wird in einem neuen Tab geöffnet.
. Wechsele in das Tab *Provisionen*.
. Klicke auf *Hinzufügen* (icon:plus[role="green"]). +
→ Eine neue Zeile für Provisionen wird der Tabelle hinzugefügt.
. Gib Informationen über die Provision ein.
. *Speichere* (icon:save[set=plenty, role="green"]) die Einstellungen. +
→ Der Provision wird automatisch eine ID zugewiesen.

[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Mandant (Shop)*
|Für welches Unternehmen gilt die Provision? Wähle den Mandanten aus der Dropdown-Liste.

| *Herkunft*
|Für welchen Markt oder für welche Verkaufsplattform gilt die Provision? Wähle die Auftragsherkunft aus der Dropdown-Liste.

| *Provision*
|Gib die Provision in Prozent ein.
|====

[TIP]
.Provisionen auf andere Hersteller übertragen
====
Gelten für mehrere deiner Hersteller die gleichen Provisionsmodelle? Du musst nicht jede Provision manuell erstellen! Kopiere ganz einfach eine Provision und übertrage sie auf andere Hersteller.

Klicke zunächst auf *Provisionen auf andere Hersteller übertragen* (icon:copy[set=plenty, role="yellow"]). Verwende dann Häkchen (icon:check-square[role="blue"]), um zu bestimmen, welche Provision du kopieren möchtest und auf welchen Hersteller du sie übertragen möchtest.
Klicke anschließend auf icon:save[set=plenty, role="green"] *Provisionen übertragen*.
====

[#400]
== Hersteller mit Artikeln verknüpfen

Nachdem du deine Herstellerdaten in plentymarkets gespeichert hast, gibst du an, wer die einzelnen Artikel hergestellt hat. Dies geschieht indem du jeden Artikel mit einem Hersteller verknüpfst.

Es gibt mehrere Möglichkeiten, Artikel mit Herstellern zu verknüpfen:

* Gib den Hersteller an, <<artikel/import-export-anlage/anlage/neue-artikel#200, während du manuell einen neuen Artikel erstellst>>.
* Gib den Hersteller <<artikel/artikel-verwalten#40, im Tab Global eines bestehenden Artikels>> an.
* <<artikel/import-export-anlage/anlage/massenbearbeitung#100, Verwende die Gruppenfunktion>>, um den Hersteller manuell für mehrere bestehende Artikel gleichzeitig anzugeben.
* Möchtest du deine Artikel importieren? Dann <<daten/daten-importieren/sync-typen/elasticSync-artikel#2260, gib den Hersteller jedes Artikels in der zu importierenden CSV-Datei an>>.

[#450]
== plentyShop-Einstellungen prüfen

Sollen deine Kunden im plentyShop gezielt nach Produkten eines bestimmten Herstellers suchen können?
Dann stelle sicher, dass du die folgenden Einstellungen konfiguriert hast:

* <<artikel/einstellungen/hersteller#100, Externer Name>>: Hast du einen externen Namen für den Hersteller gespeichert?
* <<artikel/webshop/suchleiste#70, Suchleiste>>: Wird der Hersteller bei den Suchergebnissen berücksichtigt?
* <<artikel/frontend-artikelsuche-verwalten#, Suchfilter>>: Hast du die Anleitung zum Einrichten der sogenannten Facettensuche gelesen?

[#500]
== Hersteller löschen

Bevor ein Hersteller gelöscht werden kann, müssen alle Verknüpfungen zum Hersteller gelöscht werden.
Die <<artikel/import-export-anlage/anlage/massenbearbeitung#200, Artikel-Gruppenfunktion>> ist ein nützliches Werkzeug dafür.

[.instruction]
Verknüpfungen zum Hersteller löschen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Stelle die Filter links wie folgt ein:
.. Setze links den Filter <<artikel/einleitung/suche#intable-tabellentyp, Tabellentyp>> auf *Artikel*.
.. Setze links den Filter <<artikel/einleitung/suche#intable-aktiv, Aktiv>> auf *ALLE*.
.. Wähle im Filter <<artikel/einleitung/suche#intable-hersteller, Hersteller>> den Hersteller aus der Dropdown-Liste.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Alle Artikel des Herstellers werden angezeigt.
. Wähle alle Artikel (icon:check-square[role="blue"]).
. Klicke auf *Artikel-Gruppenfunktion*. +
→ Das Fenster *Artikel-Gruppenfunktion* wird geöffnet.
. Wähle im Bereich *Global* die Option *Hersteller* (icon:check-square[role="blue"]).
. Wähle die leere Option aus der Dropdown-Liste.
. Klicke auf icon:execute[set=plenty] *Ausführen*. +
→ Die Herstellerverknüpfungen werden gelöscht. +
→ Die Hersteller können nun gelöscht werden.

[.instruction]
Hersteller löschen:

. Öffne das Menü *Einrichtung » Artikel » Hersteller*.
. Klicke in der Zeile des Herstellers auf *Löschen* (icon:minus-circle[role="red"]). +
→ Ein neues Fenster wird geöffnet.
. Klicke erneut auf *Löschen* (icon:minus-circle[role="red"]), um deine Entscheidung zu bestätigen. +
→ Der Hersteller wird gelöscht.
