= Tags und Markierungen
:lang: de
include::{includedir}/_header.adoc[]
:description: Verliere nicht den Überblick! Tags und Markierungen sind gute Möglichkeiten, Artikel übersichtlicher zu gestalten und besser zu sortieren.
:url: artikel/einstellungen/markierungen
:icons: font
:position: 100
:docinfodir: /workspace/manual-adoc
:docinfo1:

Es ist leicht, den Überblick zu verlieren, wenn du mit vielen verschiedenen Artikeln arbeitest. Tags und Markierungen sind gute Möglichkeiten, Artikel übersichtlicher zu gestalten und besser zu sortieren.

[TIP]
.Was ist der Unterschied zwischen Tags und Markierungen?
====
<<artikel/einstellungen/markierungen#100, Markierungen>> können nur mit ganzen Artikeldatensätzen verknüpft werden. Im Gegensatz dazu können <<artikel/einstellungen/markierungen#400, Tags>> mit individuellen Varianten verknüpft werden. Daher bieten Tags mehr Flexibilität.

Tags können auch verwendet werden, um andere Arten von Datensätzen hervorzuheben. Mit anderen Worten können Tags auch verwendet werden, um spezifische Kunden, Aufträge, Tickets usw. hervorzuheben.
====

[#100]
== Markierungen

Die Idee ist ganz einfach. Weise jedem deiner Artikel eine oder zwei Markierungen zu. Diese Markierungen siehst du, wenn du deine <<artikel/einleitung/suche#100, Artikel in der Übersicht>> betrachtest. Solche visuellen Unterstützungen helfen dir, die richtigen Artikel auf den ersten Blick zu finden. Du kannst auch <<artikel/einleitung/suche#100, gezielt nach Artikeln suchen>>, die eine bestimmte Markierung oder Kombination von Markierungen haben.

Wirf zunächst einen Blick auf die verschiedenen Markierungen, die in plentymarkets enthalten sind. Die Markierungen sind standardmäßig nach der ID benannt. Du kannst sie aber <<artikel/einstellungen/markierungen#200, bei Bedarf umbenennen>>. Sobald du mit den Namen zufrieden bist, kannst du die <<artikel/einstellungen/markierungen#300, Markierungen mit Artikeln verknüpfen>>.

[#200]
=== Markierungen umbenennen

Wirf zunächst einen Blick auf die verschiedenen Markierungen, die in plentymarkets enthalten sind. Es gibt 31 Symbole, die du als "Markierung 1" verwenden kannst und 11 Symbole, die du als "Markierung 2" verwenden kannst. Die Markierungen sind standardmäßig nach der ID benannt. Du kannst sie aber bei Bedarf umbenennen.

[.instruction]
Markierung umbenennen:

. Öffne das Menü *Einrichtung » Artikel » Markierungen*.
. Gib unter *Name* einen Namen ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#300]
=== Artikel mit Markierungen versehen

Sobald du mit den Namen zufrieden bist, kannst du die <<artikel/artikel-verwalten#810, Markierungen mit Artikeln verknüpfen>>. Diese Markierungen wirst du sehen, wenn du deine <<artikel/einleitung/suche#100, Artikel in der Übersicht>> betrachtest. Solche visuellen Unterstützungen helfen dir, die richtigen Artikel auf den ersten Blick zu finden. Du kannst auch <<artikel/einleitung/suche#100, gezielt nach Artikeln suchen>>, die eine bestimmte Markierung oder Kombination von Markierungen haben.

[#400]
== Tags

Im Gegensatz zu <<artikel/einstellungen/markierungen#100, Markierungen>> können Tags mit individuellen Varianten verknüpft werden. Daher bieten Tags mehr Flexibilität.

Tags können auch verwendet werden, um andere Arten von Datensätzen hervorzuheben. Mit anderen Worten können Tags auch verwendet werden, um spezifische Kunden, Aufträge, Tickets usw. hervorzuheben.

[#500]
=== Tags erstellen

<<basics/arbeiten-mit-plentymarkets/tags#, Erstelle zunächst die Tags>>, die du für deine Artikel verwenden möchtest.

[#600]
=== Varianten mit Tags versehen

<<artikel/artikel-verwalten#150, Verknüpfe dann deine Varianten mit einer beliebigen Anzahl von Tags>>. Tags, die du mit der Hauptvariate verknüpfst, werden an die anderen Varianten des Artikels vererbt. Wenn du pro Variante eigene Tags speichern möchtest, deaktiviere die Vererbung und speichere eigene Tags an den Varianten.
