= Verkaufspreise und Preiskalkulation
:lang: de
include::{includedir}/_header.adoc[]
:description: Lerne alles über Verkaufspreise, Preiskalkulationen, deren Einstellungen und deine Möglichkeiten.
:url: artikel/einstellungen/preise
:position: 70
:id: GBG1FJX
:author: none

Preise sind ein wichtiges Thema für jedes Geschäft.
Dank plentymarkets bist du bei der Gestaltung deiner Preise sehr flexibel.

* Erstens kannst du die <<artikel/einstellungen/preise#100, Bedingungen definieren>>, unter denen deine Produkte zu einem bestimmten Preis verkauft werden.
Zum Beispiel kannst du deine Produkte im Webshop günstiger anbieten als auf Amazon.
Oder du kannst deine Produkte günstiger an B2B-Kunden verkaufen als an B2C-Kunden. In plentymarkets bezeichnen wir solche Bedingungen als _Verkaufspreise_.
//bei zweitens: hier den Link auch zu einem Unterkapitel setzen. Es braucht ein Kapitel, wie verknüpfe ich meine Verkaufspreise mit Varianten. Dahin verlinken. Da in dem Kapitel soll Assistent, ElasticSync und manuelle Verknüpfung beschrieben werden. Und da in dem Kapitel soll es den Link geben zu Unterschied Artikel vs. Varianten.
* Zweitens kannst du <<artikel/einleitung/struktur#, Preise für jede Variante einzeln>> speichern.
Wenn du also ein T-Shirt in S, M, L und XL verkaufst, kannst du entscheiden, ob die XL-Variante etwas teurer als die anderen sein soll.
* Drittens kannst du plentymarkets deine <<artikel/einstellungen/preise#500, monetären Preise automatisch berechnen lassen>>.
Beispielsweise startest du mit dem Einkaufspreis des Artikels und fügst dann die Transportkosten, Lagerkosten und Steuern hinzu. Schließlich legst du eine Gewinnspanne von 20% oben drauf.

//evtl das Video wo anders hin platzieren. Evtl nur Teile vom Video verlinken. Weil es geht ja im Video um Erstellung von Verkaufspreise im Einrichtung Menü (also nicht Assistent) und Preiskalkulationen.
Dieses Video bietet dir eine spielerische Einführung in Verkaufspreise, Preiskalkulationen, deren Einstellungen und deine Möglichkeiten:

.Lerne Verkaufspreise spielerisch kennen
video::265406117[vimeo]

[#100]
== Verkaufspreise

Verkaufspreise definieren die _Bedingungen_, unter denen eine Variante zu einem bestimmten Preis verkauft wird.
Zum Beispiel kannst du deine Produkte im Webshop günstiger anbieten als auf Amazon. Oder du kannst deine Produkte günstiger an B2B-Kunden verkaufen als an B2C-Kunden.

//Info ergänzen, dass 2 Verkaufspreise standard in plenty angelegt sind. Weitere Preise können ergänzt werden und die 2 Standard-Preise können bearbeitet werden.

=== Neue Verkaufspreise erstellen

In plentymarkets werden Verkaufspreise zentral angelegt und verwaltet.
Entweder kannst du neue <<artikel/einstellungen/preise#150, Verkaufspreise mit Hilfe eines Assistenten anlegen>> oder du kannst neue <<artikel/einstellungen/preise#200, Verkaufspreise manuell im Einrichtungsmenü anlegen>>.
Beide Verfahren werden im Folgenden beschrieben.

So oder so, wirst du die Verkaufspreise an deine Bedürfnisse anpassen.
Du vergibst den Verkaufspreisen eindeutige Namen und entscheidest, für welche Währungen, Kundenklassen, Marktplätze, oder andere Bedingungen sie gelten sollen.
Anschließend werden die fertige <<Verkaufspreise mit einzelnen Varianten verknüpft>>.

[#150]
==== Mit dem Assistenten

Mit Hilfe des Assistenten kannst du auf einfache Weise neue Verkaufspreise erstellen.
//Wie erstellt man neue Verkaufspreise am einfachsten? Mit Hilfe unseres Assistenten!
Der Assistent führt dich durch die _gängigsten Einstellungen_.
Während des Prozesses vergibst du den Verkaufspreisen eindeutige Namen und entscheidest, für welche Währungen, Kundenklassen, Marktplätze, oder andere Bedingungen sie gelten sollen.
Es gibt auch <<einige erweiterte Einstellungen>>, die optional auch im Anschluß konfiguriert werden können.


[.instruction]
Verkaufspreis erstellen:

. Öffne das Menü *Einrichtung » Assistenten » Grundeinrichtung*.
. Klicke auf den Verkaufspreise-Assistenten.
. Klicke auf *Neue Konfiguration* (icon:plus[role="green"]).
. Folge den Anweisungen auf dem Bildschirm. Klappe die Info-Box unten auf (icon:chevron-down[role="darkGrey"]), wenn du zusätzliche Informationen zu einer der Optionen benötigst.
. Überprüfe die Zusammenfassung auf mögliche Fehler und klicke auf icon:check[role="green"] *Abschließen*. +
→ Der Assistent ist fertig. Wiederhole diese Schritte, bis du alle von deinem Unternehmen benötigten Verkaufspreise erstellt hast.

Der Assistent führt dich durch die _gängigsten Einstellungen_ für Verkaufspreise. Es gibt jedoch <<einige erweiterte Einstellungen>>, die optional auch konfiguriert werden können.

Sobald du alle für dein Unternehmen benötigten Verkaufspreise konfiguriert hast, bist du bereit, diese <<Verkaufspreise mit Artikeldatensätzen zu verknüpfen>>.

[.collapseBox]
.*Weitere Informationen über die einzelne Optionen*
--

[[tabelle-retoure-kassenbon]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Schritt: Einstellungen

|*Typ*
a|Welche Art von Verkaufspreis möchtest du konfigurieren? In den meisten Fällen wirst du einen _Standard-Verkaufspreis_ anlegen.

Aber in manchen Situationen willst du vielleicht stattdessen ein "UVP", "Setpreis" oder "Aktionspreis" erstellen.
Falls ja, dann aktiviere diese Option (icon:toggle-on[role="green"]).
//Ein zusätzlicher Konfigurationsschritt erscheint. Hier gibst du an, welche Art von Verkaufspreis du erstellen willst.
Es erscheint ein zusätzlicher Konfigurationsschritt, in dem du die Art des zu erstellenden Verkaufspreises festlegen kannst.

* *UVP* = Eine unverbindliche Preisempfehlung, die nur dazu dient, den Preisvergleich zwischen dem UVP und einem Standard-Verkaufspreis darzustellen. Der UVP wird im Webshop in rot und durchgestrichen neben dem Verkaufspreis dargestellt. Produkte können nicht zu dem UVP-Preis verkauft werden.
* *Aktionspreis* = Ein Angebotspreis, der z.B. bei Amazon nur für eine begrenzte Zeit gilt.
* *Setpreis* = Sets sind eine Möglichkeit, <<Produkte zu kombinieren>> und als eine Verkaufseinheit anzubieten. Wenn du dich entscheidest, Produkte zu einem Set zu kombinieren, dann musst du den einzelnen Set-Bestandteilen einen Setpreis geben.

|*Kundenklassen*
|Soll der Verkaufspreis nur für bestimmte Kundenklassen gelten? Willst du z.B. deine Produkte günstiger an B2B-Kunden verkaufen als an B2C-Kunden?
Falls ja, dann aktiviere diese Option (icon:toggle-on[role="green"]).
//Ein zusätzlicher <<Konfigurationsschritt namens Kundenklassen>> erscheint.
Es erscheint ein zusätzlicher Konfigurationsschritt, in dem du die Kundenklasse angeben kannst, für die dieser Verkaufspreis gilt.

*_Hinweis_*: <<crm/kontakte-verwalten#15, Erstelle die nötigen Kundenklassen>> im Voraus, falls sie nicht bereits in deinem plentymarkets System vorhanden sind.
|*Mengenabhängigkeit*
|Sollte der Verkaufspreis nur gelten, wenn ein Kunde _mehrere Exemplare des Artikels_ kauft?
Nehmen wir zum Beispiel an, du verkaufst Socken für 6 EUR pro Paar. Möchtest du, dass der Preis auf 5 EUR pro Paar reduziert wird, wenn ein Kunde 3 oder mehr Paar Socken kauft?
Falls ja, dann aktiviere diese Option (icon:toggle-on[role="green"]).
//Ein zusätzlicher <<Konfigurationsschritt namens Mengenabhängigkeit>> erscheint.
Es erscheint ein zusätzlicher Konfigurationsschritt, in dem du die Menge angeben kannst, für die dieser Verkaufspreis gilt.

*_Tipp_*: Füge _noch weitere_ mengenabhängige Verkaufspreise hinzu, um eine Preisstaffel nach Mengen zu erstellen.

2+|Schritt: Name

|*Interner Name*
|

|*Externer Name*
|

2+|Schritt: Verfügbarkeiten

|*Währungen*
|In welche Währungen soll der Preis automatisch umgerechnet werden?
Wähle sie aus der Liste aus (icon:check-square[role="blue"]).

*_Hintergrund-Info_*: Während du dein Webshop konfigurierst, kannst du entscheiden, in welchen <<webshop/ceres-einrichten#220, Sprachen>> und <<webshop/ceres-einrichten#201, Währungen>> dein Shop zugänglich sein soll.
//Du kannst also entscheiden, welche Sprachen und Währungen deine Kunden im Header wählen können.
Nehmen wir zum Beispiel an, dass Kunden die Währungen EUR, PLN, CHF und GBP aus der Kopfzeile wählen können.
Dann wäre es sinnvoll, deine Preise automatisch von der <<Standardwährung>>, z.B. EUR, in die anderen Währungen, z.B. PLN, CHF und GBP, umrechnen zu lassen.

|*Verkaufskanäle*
|
//info that if you choose Amazon or ebay, then an extra step called "Amazon-Konten" or "Ebay-Konten" will appear

|*Lieferländer*
|
|====

--

[#200]
==== Im Einrichtungsmenü

Erstelle beliebig viele Verkaufspreise, um die gesamte Breite deiner benötigten Preise in plentymarkets abzubilden.

[.instruction]
Verkaufspreis erstellen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise*.
. Klicke auf *Neu*. +
→ Das Tab *Neu* wird geöffnet.
. Nimm die Einstellungen gemäß <<table-create-sales-price>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-create-sales-price]]
.Verkaufspreis erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Abo-Interv.*
|Diese Option wurde vorbereitend für eine spätere Verwendung im Ceres-Webshop integriert und hat aktuell noch keine Funktion. +
*_Hinweis:_* Das Intervall wird für aktuelle Aboaufträge über den Scheduler nicht berücksichtigt.

|*Position*
|Positionsnummer eingeben. Verkaufspreise werden im Bereich *Verkaufspreise* von Artikelvarianten aufsteigend sortiert.

|*Interner Name DE*
|Internen Namen eingeben. Der interne Name wird nur im plentymarkets Backend geführt und ist nicht im Webshop sichtbar.

|*Externer Name DE*
|Externen Namen eingeben. Der externe Name wird in deinem Webshop angezeigt.

|*Ab Menge*
|Mengenwert eingeben. Über Verkaufspreise mit verschiedenen Mengenwerten bildest du mengenbezogene Preisstaffelungen in plentymarkets ab.

|*Währung*
|Eine, mehrere oder *ALLE* Währungen aktivieren.

|*Währung: Live umrechnen*
|Der Standardpreis wird per Live-Umrechnung in die <<payment/waehrungen#20, Währung>> umgerechnet und im Webshop angezeigt. Bei Wahl dieser Option werden die Preise der verwendeten Währungen vom System ermittelt. Die Umrechnungsfaktoren basieren auf den Einstellungen im Menü *Einrichtung » Aufträge » Zahlung » Währungen*.

|*Preistyp*
a|Optional einen Preistyp für den Verkaufspreis aktivieren.

* *UVP* = Aktivieren, wenn der Verkaufspreis der unverbindliche Verkaufspreis (UVP) ist. Wird der UVP und ein weiterer Verkaufspreis an der Variante verknüpft, dann wird der UVP im Webshop in rot und durchgestrichen neben dem Verkaufspreis dargestellt. +
*__Hinweis:__* Preise des Typs *UVP* dienen nur dazu, den Preisvergleich zwischen dem UVP und einem Verkaufspreis darzustellen. Varianten können nicht zu diesem UVP-Preis verkauft werden. +
* *Aktionspreis* = Aktivieren, um einen Verkaufspreis als Aktionspreis zu kennzeichnen. Aktionspreise werden zum Beispiel für Marktplätze wie <<maerkte/amazon/amazon-einrichten#, Amazon>> und <<maerkte/real-de/real-de-einrichten#, real.de>> verwendet. +
* *Setpreis* = Aktivieren, um einen Verkaufspreis als Preis für Setbestandteile zu kennzeichnen.

|*Darstellung*
|Aktivieren, um den Verkaufspreis beim Erstellen von Artikeln automatisch im Bereich *Verkaufspreise* anzuzeigen. Wenn diese Einstellung deaktiviert ist, kann der Verkaufspreis manuell beim Erstellen von Artikeln hinzugefügt werden.

|*Mandant*
|Einen, mehrere oder *ALLE* Mandanten (Shops) aktivieren, mit denen der Verkaufspreis verknüpft wird.

|*Klasse*
|Eine, mehrere oder *ALLE* Klassen aktivieren, mit denen der Verkaufspreis verknüpft wird. Der Verkaufspreis gilt nur für Kontakte der gewählten Klassen.

|*Land*
|Ein, mehrere oder *ALLE* Lieferländer aktivieren, mit denen der Verkaufspreis verknüpft wird.

|*Herkunft*
|Eine, mehrere oder *ALLE* Auftragsherkünfte aktivieren, mit denen der Verkaufspreis verknüpft wird.

|*Amazon-Konten*
|Ein, mehrere oder *ALLE* Amazon-Konten aktivieren, mit denen der Verkaufspreis verknüpft wird. Amazon-Konten sind verfügbar, nachdem die passende Amazon-Plattform unter *Herkunft* verknüpft wurde.

|*eBay-Konten*
|Ein, mehrere oder *ALLE* eBay-Konten aktivieren, mit denen der Verkaufspreis verknüpft wird. eBay-Konten sind verfügbar, nachdem die passende eBay-Plattform unter *Herkunft* verknüpft wurde.
|====

=== Bestehende Verkaufspreise bearbeiten

[#400]
==== Verkaufspreise suchen

Nutze Filter, um nach Verkaufspreisen zu suchen.

[.instruction]
Verkaufspreise filtern:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise*.
. Wähle die *Filter*. Beachte dazu die Erläuterungen in <<table-filter-sales-prices>>.
. Klicke auf *Suchen*. +
→ Die gefilterten Verkaufspreise werden in der Übersicht angezeigt.

[[table-filter-sales-prices]]
.Verkaufspreise filtern
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Suchfelder*

|*ID*
|ID eingeben, um nach dem Verkaufspreis mit dieser ID zu suchen.

|*Name*
|Name eingeben, um nach dem Verkaufspreis mit diesem Namen zu suchen.

|*Ab Menge*
|Mengenwert eingeben, um nach dem Verkaufspreis mit dieser Mengenstaffelung zu suchen.

2+|*Filter*

|*Mandant*
|Mandant oder *ALLE* wählen, um nach Verkaufspreisen für diesen Mandanten (Shop) zu suchen.

|*Klasse*
|Klasse oder *ALLE* wählen, um nach Verkaufspreisen für diese Kundenklasse zu suchen.

|*Herkunft*
|Herkunft oder *ALLE* wählen, um nach Verkaufspreisen für diese Auftragsherkunft zu suchen.

|*Amazon-Konten*
|Amazon-Konto oder *ALLE* wählen, um nach Verkaufspreisen für dieses Amazon-Konto zu suchen.

|*eBay-Konten*
|eBay-Konto oder *ALLE* wählen, um nach Verkaufspreisen für dieses eBay-Konto zu suchen.

|*Währung*
|Währung oder *ALLE* wählen, um nach Verkaufspreisen für diese Währung zu suchen.

|*Sprache*
|Sprache oder *ALLE* wählen, um nach Verkaufspreisen in dieser Sprache zu suchen. Standardmäßig ist *Deutsch* voreingestellt.

|*Land*
|Land oder *ALLE* wählen, um nach Verkaufspreisen für dieses Lieferland zu suchen.
|====

[#300]
==== Die Namen in mehreren Sprachen speichern

Nachdem du einen Verkaufspreis erstellt hast, übersetze nach Bedarf den Namen des Verkaufspreises in die von dir verwendeten Sprachen.

[.instruction]
Verkaufspreis übersetzen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise*.
. Öffne den Verkaufspreis im Tab *Preise*.
. Wechsele in das Tab *Sprache*.
. Gib den *internen Namen* in den benötigten Sprachen ein.
. Gib den *externen Namen* in den benötigten Sprachen ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

==== Erweiterte Einstellungen (nicht im Assistenten enthalten)

[#500]
== Preiskalkulationen

Preiskalkulationen ermöglichen dir das gezielte Zuschneiden und Staffeln von Preisen für Kundenklassen und Herkünfte. Zuerst <<artikel/einstellungen/preise#600, erstellst>> du individuelle Preisvarianten im Menü *Einrichtung » Artikel » Preiskalkulation*. Danach <<artikel/artikel-verwalten#240, verknüpfst>> du die Preiskalkulationen mit Varianten.

Preiskalkulationen werden automatisch auf die hinterlegten Preise angerechnet. Du kannst Preiskalkulationen auch per <<artikel/artikel-verwalten#330, Varianten-Gruppenfunktion>> für mehrere Artikelvarianten gleichzeitig einstellen.

[#600]
=== Preiskalkulationen erstellen

[.instruction]
Preiskalkulation erstellen:

. Öffne das Menü *Einrichtung » Artikel » Preiskalkulation*.
. Klicke auf *Neue Preiskalkulation*. +
→ Das Fenster *Neue Preiskalkulation* wird geöffnet.
. Gib einen Namen ein.
. Klicke auf *Hinzufügen*. +
→ Die neue Preiskalkulation wird geöffnet.
. Nimm die Einstellungen gemäß <<table-create-price-calculation>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-create-price-calculation]]
.Preiskalkulation erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Einstellungen*

|*Name*
|Name für die Preiskalkulation eingeben. Der Name wird im Bereich *Verkaufspreise* im Tab *Einstellungen* einer Artikelvariante angezeigt.

|*Preisquelle*
|Preis wählen, der als Grundlage für die Preiskalkulation dient.

|*Transportkosten*
|Aktivieren, um Transportkosten zur Preisquelle zu addieren. Die Transportkosten werden im Bereich *Kosten* im Tab *Einstellungen* einer Artikelvariante eingegeben.

|*Lagerkosten*
|Aktivieren, um Lagerkosten zur Preisquelle zu addieren. Die Lagerkosten werden im Bereich *Kosten* im Tab *Einstellungen* einer Artikelvariante eingegeben.

|*Zoll*
|Aktivieren, um Zollkosten zur Preisquelle zu addieren. Die Zollkosten werden im Bereich *Kosten* im Tab *Einstellungen* einer Artikelvariante eingegeben. Die Zollkosten werden in Prozent angegeben.

|*Betriebskosten*
|Aktivieren, um Betriebskosten zur Preisquelle zu addieren. Die Betriebskosten werden im Bereich *Kosten* im Tab *Einstellungen* einer Artikelvariante eingegeben. Die Betriebskosten werden in Prozent angegeben.

|*MwSt.*
|Aktivieren, um die Umsatzsteuer zur Preisquelle zu addieren. Der Umsatzsteuersatz wird im Bereich *Kosten* im Tab *Einstellungen* einer Artikelvariante gewählt. Die Umsatzsteuer wird in Prozent angegeben.

2+|*Verknüpfungen*

|*Hinzufügen*
|Auf *Hinzufügen* klicken, um eine neue Verknüpfung zu erstellen.

|*Ziel*
|Preis wählen, der als Zielpreis für die Preiskalkulation dient.

|*Operator*
|Operator wählen. *Plus*, *Minus*, *Plus Prozentwert*, *Minus Prozentwert*, *Mal* und *Geteilt* stehen zur Auswahl.

|*Operand*
|Numerischen Wert eingeben.

//Preiskalkulation: aktuell sind Herkunft/Mandant nur in Bezug auf Herstellerprovisionen. Da die Verkaufspreise eh für Mandante konfigurierbar sind.
|*Mandant (Shop)*
|Mandant (Shop) wählen, der mit der Preiskalkulation verknüpft wird.

|*Herkunft*
|Herkunft wählen, die mit der Preiskalkulation verknüpft wird.
|====
