= Verkaufspreise und Preiskalkulation
:lang: de
include::{includedir}/_header.adoc[]
:description: Lerne alles über Verkaufspreise, Preiskalkulationen, deren Einstellungen und deine Möglichkeiten.
:url: artikel/einstellungen/preise
:position: 70
:id: GBG1FJX
:author: none

Preise sind ein wichtiges Thema für jedes Geschäft.
Dank plentymarkets bist du bei der Gestaltung deiner Preise sehr flexibel.

* Erstens kannst du die <<artikel/einstellungen/preise#100, Bedingungen definieren>>, unter denen deine Produkte zu einem bestimmten Preis verkauft werden.
Zum Beispiel kannst du deine Produkte im Webshop günstiger anbieten als auf Amazon.
Oder du kannst deine Produkte günstiger an B2B-Kunden verkaufen als an B2C-Kunden. In plentymarkets bezeichnen wir solche Bedingungen als _Verkaufspreise_.
//bei zweitens: hier den Link auch zu einem Unterkapitel setzen. Es braucht ein Kapitel, wie verknüpfe ich meine Verkaufspreise mit Varianten. Dahin verlinken. Da in dem Kapitel soll Assistent, ElasticSync und manuelle Verknüpfung beschrieben werden. Und da in dem Kapitel soll es den Link geben zu Unterschied Artikel vs. Varianten.
* Zweitens kannst du <<artikel/einstellungen/preise#900, Preise für jede Variante einzeln>> speichern.
Wenn du also ein T-Shirt in S, M, L und XL verkaufst, kannst du entscheiden, ob die XL-Variante etwas teurer als die anderen sein soll.
* Drittens kannst du plentymarkets deine <<artikel/einstellungen/preise#1000, monetären Preise automatisch berechnen lassen>>.
Beispielsweise startest du mit dem Einkaufspreis des Artikels und fügst dann die Transportkosten, Lagerkosten und Steuern hinzu. Schließlich legst du eine Gewinnspanne von 20% oben drauf.

//evtl das Video wo anders hin platzieren. Evtl nur Teile vom Video verlinken. Weil es geht ja im Video um Erstellung von Verkaufspreise im Einrichtung Menü (also nicht Assistent) und Preiskalkulationen.
Dieses Video bietet dir eine spielerische Einführung in Verkaufspreise, Preiskalkulationen, deren Einstellungen und deine Möglichkeiten:

.Lerne Verkaufspreise spielerisch kennen
video::265406117[vimeo]

[#100]
== Verkaufspreise

Verkaufspreise definieren die _Bedingungen_, unter denen eine Variante zu einem bestimmten Preis verkauft wird.
Zum Beispiel kannst du deine Produkte im Webshop günstiger anbieten als auf Amazon. Oder du kannst deine Produkte günstiger an B2B-Kunden verkaufen als an B2C-Kunden.

//Info ergänzen, dass 2 Verkaufspreise standard in plenty angelegt sind. Weitere Preise können ergänzt werden und die 2 Standard-Preise können bearbeitet werden.

[#200]
=== Neue Verkaufspreise erstellen

In plentymarkets werden Verkaufspreise zentral angelegt und verwaltet.
Entweder kannst du neue <<artikel/einstellungen/preise#300, Verkaufspreise mit Hilfe eines Assistenten anlegen>> oder du kannst neue <<artikel/einstellungen/preise#400, Verkaufspreise manuell im Einrichtungsmenü anlegen>>.
Beide Verfahren werden im Folgenden beschrieben.

So oder so, wirst du die Verkaufspreise an deine Bedürfnisse anpassen.
Du vergibst den Verkaufspreisen eindeutige Namen und entscheidest, für welche Währungen, Kundenklassen, Marktplätze, oder andere Bedingungen sie gelten sollen.
Anschließend werden die fertige <<artikel/einstellungen/preise#900, Verkaufspreise mit einzelnen Varianten verknüpft>>.

[#300]
==== Mit dem Assistenten

Mit Hilfe des Assistenten kannst du auf einfache Weise neue Verkaufspreise erstellen.
//Wie erstellt man neue Verkaufspreise am einfachsten? Mit Hilfe unseres Assistenten!
Der Assistent führt dich durch die _gängigsten Einstellungen_.
Während des Prozesses vergibst du den Verkaufspreisen eindeutige Namen und entscheidest, für welche Währungen, Kundenklassen, Marktplätze, oder andere Bedingungen sie gelten sollen.
Es gibt auch <<artikel/einstellungen/preise#800, einige erweiterte Einstellungen>>, die optional auch im Anschluß konfiguriert werden können.


[.instruction]
Verkaufspreis erstellen:

. Öffne das Menü *Einrichtung » Assistenten » Grundeinrichtung*.
. Klicke auf den Verkaufspreise-Assistenten.
. Klicke auf *Neue Konfiguration* (icon:plus[role="green"]).
. Folge den Anweisungen auf dem Bildschirm. Klappe die Info-Box unten auf (icon:chevron-down[role="darkGrey"]), wenn du zusätzliche Informationen zu einer der Optionen benötigst.
. Überprüfe die Zusammenfassung auf mögliche Fehler und klicke auf icon:check[role="green"] *Abschließen*. +
→ Der Assistent ist fertig. Wiederhole diese Schritte, bis du alle von deinem Unternehmen benötigten Verkaufspreise erstellt hast.

Der Assistent führt dich durch die _gängigsten Einstellungen_ für Verkaufspreise. Es gibt jedoch <<artikel/einstellungen/preise#800, einige erweiterte Einstellungen>>, die optional auch konfiguriert werden können.

Sobald du alle für dein Unternehmen benötigten Verkaufspreise konfiguriert hast, bist du bereit, diese <<artikel/einstellungen/preise#900, Verkaufspreise mit Artikeldatensätzen zu verknüpfen>>.

[.collapseBox]
.*Weitere Informationen über die einzelne Optionen*
--

[[tabelle-retoure-kassenbon]]
[width="100%"]
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Schritt: Einstellungen

|*Typ*
a|Welche Art von Verkaufspreis möchtest du konfigurieren? In den meisten Fällen wirst du einen _Standard-Verkaufspreis_ anlegen.

Aber in manchen Situationen willst du vielleicht stattdessen ein "UVP", "Setpreis" oder "Aktionspreis" erstellen.
Falls ja, dann aktiviere diese Option (icon:toggle-on[role="green"]).
Es erscheint ein zusätzlicher Konfigurationsschritt, in dem du die Art des zu erstellenden Verkaufspreises festlegen kannst.

* *UVP* = Eine unverbindliche Preisempfehlung, die nur dazu dient, den Preisvergleich zwischen dem UVP und einem Standard-Verkaufspreis darzustellen. Der UVP wird im Webshop in rot und durchgestrichen neben dem Verkaufspreis dargestellt. Produkte können nicht zu dem UVP-Preis verkauft werden.
* *Aktionspreis* = Ein Angebotspreis, der z.B. bei Amazon nur für eine begrenzte Zeit gilt.
* *Setpreis* = Sets sind eine Möglichkeit, <<artikel/anwendungsfaelle/multipacks-pakete-sets#, Produkte zu kombinieren>> und als eine Verkaufseinheit anzubieten. Wenn du dich entscheidest, Produkte zu einem Set zu kombinieren, dann musst du den einzelnen Set-Bestandteilen einen Setpreis geben.

|*Kundenklassen*
|Soll der Verkaufspreis nur für bestimmte Kundenklassen gelten? Willst du z.B. deine Produkte günstiger an B2B-Kunden verkaufen als an B2C-Kunden?
Falls ja, dann aktiviere diese Option (icon:toggle-on[role="green"]).
Es erscheint ein zusätzlicher Konfigurationsschritt, in dem du die Kundenklasse angeben kannst, für die dieser Verkaufspreis gilt.

*_Hinweis_*: <<crm/kontakte-verwalten#15, Erstelle die nötigen Kundenklassen>> im Voraus, falls sie nicht bereits in deinem plentymarkets System vorhanden sind.

|*Mengenabhängigkeit*
|Sollte der Verkaufspreis nur gelten, wenn ein Kunde _mehrere Exemplare des Artikels_ kauft?
Nehmen wir zum Beispiel an, du verkaufst Socken für 6 EUR pro Paar. Möchtest du, dass der Preis auf 5 EUR pro Paar reduziert wird, wenn ein Kunde 3 oder mehr Paar Socken kauft?
Falls ja, dann aktiviere diese Option (icon:toggle-on[role="green"]).
Es erscheint ein zusätzlicher Konfigurationsschritt, in dem du die Menge angeben kannst, für die dieser Verkaufspreis gilt.

*_Tipp_*: Füge _noch weitere_ mengenabhängige Verkaufspreise hinzu, um eine Preisstaffel nach Mengen zu erstellen.

2+|Schritt: Name

|*Interner Name*
|Gib einen Namen für den Verkaufspreis ein.
Dieser Name erscheint an verschiedenen Stellen innerhalb deines plentymarkets Backends. Du wählst z.B. den Verkaufspreis anhand seines Namens, wenn du <<artikel/einstellungen/preise#900, ihn mit einzelnen Artikeln verknüpfst>>.

|*Externer Name*
|Gib einen externen Namen für den Verkaufspreis ein.
Dieser Name erscheint derzeit weder im Ceres noch im Callisto-Webshop.

2+|Schritt: Verfügbarkeiten

|*Währungen*
|In welche Währungen soll der Preis automatisch umgerechnet werden?
Wähle sie aus der Liste aus (icon:check-square[role="blue"]).

*_Hintergrund-Info_*: Während du dein Webshop konfigurierst, kannst du entscheiden, in welchen <<webshop/ceres-einrichten#220, Sprachen>> und <<webshop/ceres-einrichten#201, Währungen>> dein Shop zugänglich sein soll.
//Du kannst also entscheiden, welche Sprachen und Währungen deine Kunden im Header wählen können.
Nehmen wir zum Beispiel an, dass Kunden die Währungen EUR, PLN, CHF und GBP aus der Kopfzeile wählen können.
Dann wäre es sinnvoll, deine Preise automatisch von der <<payment/waehrungen#30, Standardwährung>>, z.B. EUR, in die anderen Währungen, z.B. PLN, CHF und GBP, umrechnen zu lassen.

Vergewissere dich, dass du mit den im Menü *Einrichtung » Aufträge » Zahlung » Währungen* gespeicherten <<payment/waehrungen#20, Umrechnungsfaktoren>> einverstanden bist.

|*Verkaufskanäle*
|Soll der Verkaufspreis nur für bestimmte Verkaufskanäle gelten? Möchtest du zum Beispiel den Artikel zu einem niedrigeren Preis in deinem Webshop verkaufen als auf Amazon?
Wähle alle Plattformen (icon:check-square[role="blue"]), für die dieser Verkaufspreis gelten soll.

*_Hinweis_*: Wenn du eBay oder Amazon wählst, erscheint ein zusätzlicher Konfigurationsschritt. In diesem Schritt teilst du plentymarkets mit, für welches eBay- oder Amazon-Konto der Verkaufspreis gelten soll.
<<maerkte/ebay/ebay-einrichten#, Verknüpfe also im Voraus dein eBay- oder Amazon-Konto mit plentymarkets>>.

|*Lieferländer*
|Soll der Verkaufspreis nur für bestimmte Lieferländer gelten?
Beispielsweise zahlst du wahrscheinlich unterschiedliche Steuersätze in unterschiedlichen Ländern. Aus diesem Grund willst du vielleicht einen Artikel in einigen Ländern zu einem etwas höheren Preis verkaufen, damit du die Differenz nicht selbst bezahlen musst.
Wähle alle Länder (icon:check-square[role="blue"]), für die dieser Verkaufspreis gelten soll.
|====

--

[#400]
==== Im Einrichtungsmenü

Erstelle beliebig viele Verkaufspreise, um die gesamte Breite deiner benötigten Preise in plentymarkets abzubilden.
Während des Prozesses vergibst du den Verkaufspreisen eindeutige Namen und entscheidest, für welche Währungen, Kundenklassen, Marktplätze, oder andere Bedingungen sie gelten sollen.

[.instruction]
Verkaufspreis erstellen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise*.
. Klicke auf icon:plus[role="green"] *Neu*. +
→ Das Tab *Neu* wird geöffnet.
. Nimm die Einstellungen vor. Beachte <<table-create-sales-price>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-create-sales-price]]
.Verkaufspreis erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Abo-Interv.*
|Diese Option wurde vorbereitend für eine spätere Verwendung im Ceres-Webshop integriert und hat aktuell noch keine Funktion. +
*_Hinweis:_* Das Intervall wird für aktuelle Aboaufträge über den Scheduler nicht berücksichtigt.

|*Position*
|Positionsnummer eingeben.
Wenn du mehrere <<artikel/einstellungen/preise#900, Verkaufspreise mit einer Variante verknüpfst>>, dann werden die Verkaufspreise anhand ihrer Positionsnummer im Artikeldatensatz sortiert angezeigt.

|*Interner Name DE*
|Gib einen Namen für den Verkaufspreis ein.
Dieser Name erscheint an verschiedenen Stellen innerhalb deines plentymarkets Backends. Du wählst z.B. den Verkaufspreis anhand seines Namens, wenn du <<artikel/einstellungen/preise#900, ihn mit einzelnen Artikeln verknüpfst>>.

|*Externer Name DE*
|Gib einen externen Namen für den Verkaufspreis ein.
Dieser Name erscheint derzeit weder im Ceres noch im Callisto-Webshop.

|*Ab Menge*
|Sollte der Verkaufspreis nur gelten, wenn ein Kunde _mehrere Exemplare des Artikels_ kauft?
Nehmen wir zum Beispiel an, du verkaufst Socken für 6 EUR pro Paar. Möchtest du, dass der Preis auf 5 EUR pro Paar reduziert wird, wenn ein Kunde 3 oder mehr Paar Socken kauft?
Falls ja, dann gib die Menge an, für die dieser Verkaufspreis gilt.

*_Tipp_*: Füge _noch weitere_ mengenabhängige Verkaufspreise hinzu, um eine Preisstaffel nach Mengen zu erstellen.

|*Währung*
|Für welche Währungen soll der Verkaufspreis gelten?
Wähle sie aus der Liste aus (icon:check-square[role="blue"]).

*_Hintergrund-Info_*: Während du dein Webshop konfigurierst, kannst du entscheiden, in welchen <<webshop/ceres-einrichten#220, Sprachen>> und <<webshop/ceres-einrichten#201, Währungen>> dein Shop zugänglich sein soll.
//Du kannst also entscheiden, welche Sprachen und Währungen deine Kunden im Header wählen können.
Nehmen wir zum Beispiel an, dass Kunden die Währungen EUR, PLN, CHF und GBP aus der Kopfzeile wählen können.
Dann wäre es sinnvoll, Preise auch für diese Währungen zu speichern.

*_Automatisch umrechnen lassen_*: Aktiviere die Option *Live umrechnen* (icon:check-square[role="blue"]), um deine Preise automatisch von der <<payment/waehrungen#30, Standardwährung>>, z.B. EUR, in die anderen Währungen, z.B. PLN, CHF und GBP, umrechnen zu lassen. +
Wenn du diese Option _nicht_ aktivierst, werden deine Preise alle die gleiche Zahl, aber unterschiedliche Währungen haben, z.B. 19 EUR und 19 PLN. Daher ist es meistens sinnvoll, die Preise automatisch umrechnen zu lassen.

Vergewissere dich, dass du mit den im Menü *Einrichtung » Aufträge » Zahlung » Währungen* gespeicherten <<payment/waehrungen#20, Umrechnungsfaktoren>> einverstanden bist.

|*Preistyp*
a|Welche Art von Verkaufspreis möchtest du konfigurieren? In den meisten Fällen wirst du einen _Standard-Verkaufspreis_ anlegen.

Aber in manchen Situationen willst du vielleicht stattdessen ein "UVP", "Setpreis" oder "Aktionspreis" erstellen.
Falls ja, dann wähle den entsprechenden Preistyp (icon:check-square[role="blue"]).

* *UVP* = Eine unverbindliche Preisempfehlung, die nur dazu dient, den Preisvergleich zwischen dem UVP und einem Standard-Verkaufspreis darzustellen. Der UVP wird im Webshop in rot und durchgestrichen neben dem Verkaufspreis dargestellt. Produkte können nicht zu dem UVP-Preis verkauft werden.
* *Aktionspreis* = Ein Angebotspreis, der z.B. bei Amazon nur für eine begrenzte Zeit gilt.
* *Setpreis* = Sets sind eine Möglichkeit, <<artikel/anwendungsfaelle/multipacks-pakete-sets#, Produkte zu kombinieren>> und als eine Verkaufseinheit anzubieten. Wenn du dich entscheidest, Produkte zu einem Set zu kombinieren, dann musst du den einzelnen Set-Bestandteilen einen Setpreis geben.

|*Darstellung*
|Soll dieser Verkaufspreis _automatisch_ mit neuen Artikeldatensätzen verknüpft werden?
Falls ja, dann aktiviere die Option *Bei neuem Artikel immer anzeigen* (icon:check-square[role="blue"]).

Wenn diese Einstellung deaktiviert ist, kannst du den <<artikel/einstellungen/preise#900, Verkaufspreis trotzdem manuell zu Artikeln hinzufügen>>.

|*Mandant*
|Soll der Verkaufspreis nur für bestimmte Mandanten (Shops) gelten? Falls ja, dann wähle alle Shops (icon:check-square[role="blue"]), für die dieser Verkaufspreis gelten soll.

|*Klasse*
|Soll der Verkaufspreis nur für bestimmte Kundenklassen gelten? Willst du z.B. deine Produkte günstiger an B2B-Kunden verkaufen als an B2C-Kunden?
Falls ja, dann wähle alle Kundenklassen (icon:check-square[role="blue"]), für die dieser Verkaufspreis gilt.

*_Hinweis_*: <<crm/kontakte-verwalten#15, Erstelle die nötigen Kundenklassen>> im Voraus, falls sie nicht bereits in deinem plentymarkets System vorhanden sind.

|*Land*
|Soll der Verkaufspreis nur für bestimmte Lieferländer gelten? Beispielsweise zahlst du wahrscheinlich unterschiedliche Steuersätze in unterschiedlichen Ländern. Aus diesem Grund willst du vielleicht einen Artikel in einigen Ländern zu einem etwas höheren Preis verkaufen, damit du die Differenz nicht selbst bezahlen musst.
Wähle alle Länder (icon:check-square[role="blue"]), für die dieser Verkaufspreis gelten soll.

|*Herkunft*
|Soll der Verkaufspreis nur für bestimmte Verkaufskanäle gelten? Möchtest du zum Beispiel den Artikel zu einem niedrigeren Preis in deinem Webshop verkaufen als auf Amazon?
Wähle alle Plattformen (icon:check-square[role="blue"]), für die dieser Verkaufspreis gelten soll.

*_Hinweis_*: Wenn du eBay oder Amazon wählst, wird die entsprechende Kontoeinstellung weiter unten eingeblendet. Hier teilst du plentymarkets mit, für welches eBay- oder Amazon-Konto der Verkaufspreis gelten soll.
<<maerkte/ebay/ebay-einrichten#, Verknüpfe also im Voraus dein eBay- oder Amazon-Konto mit plentymarkets>>.

|*Amazon-Konten*
|Teile plentymarkets mit, für welches Amazon-Konto der Verkaufspreis gelten soll.
<<maerkte/amazon/amazon-einrichten#, Verknüpfe also im Voraus dein Amazon-Konto mit plentymarkets>>.

Diese Einstellung ist ausgegraut, bis du eine Amazon-Plattform aus der Liste weiter oben auswählst.

|*eBay-Konten*
|Teile plentymarkets mit, für welches eBay-Konto der Verkaufspreis gelten soll.
<<maerkte/ebay/ebay-einrichten#, Verknüpfe also im Voraus dein eBay-Konto mit plentymarkets>>.

Diese Einstellung ist ausgegraut, bis du eine eBay-Plattform aus der Liste weiter oben auswählst.
|====

[#500]
=== Bestehende Verkaufspreise bearbeiten

Sobald du einen <<artikel/einstellungen/preise#200, neuen Verkaufspreis erstellt>> hast, wird er automatisch zur Übersicht im Menü *Einrichtung » Artikel » Verkaufspreise* hinzugefügt.

[#600]
==== Verkaufspreise suchen

Verwende die Filter links, um die in der Übersicht rechts angezeigten Verkaufspreise einzugrenzen.

[.instruction]
Verkaufspreise filtern:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise*.
. Wähle die Filter links. Beachte <<table-filter-sales-prices>>.
. Klicke auf *Suchen* (icon:search[role="blue"]). +
→ Die gefilterten Verkaufspreise werden in der Übersicht rechts angezeigt.

[[table-filter-sales-prices]]
.Verkaufspreise filtern
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ID*
|ID eingeben, um nach dem Verkaufspreis mit dieser ID zu suchen.

|*Name*
|Name eingeben, um nach dem Verkaufspreis mit diesem Namen zu suchen.

|*Ab Menge*
|Mengenwert eingeben, um nach dem Verkaufspreis mit dieser Mengenstaffelung zu suchen.

|*Mandant*
|Mandant oder *ALLE* wählen, um nach Verkaufspreisen für diesen Mandanten (Shop) zu suchen.

|*Klasse*
|Klasse oder *ALLE* wählen, um nach Verkaufspreisen für diese Kundenklasse zu suchen.

|*Herkunft*
|Herkunft oder *ALLE* wählen, um nach Verkaufspreisen für diese Auftragsherkunft zu suchen.

|*Amazon-Konten*
|Amazon-Konto oder *ALLE* wählen, um nach Verkaufspreisen für dieses Amazon-Konto zu suchen.

|*eBay-Konten*
|eBay-Konto oder *ALLE* wählen, um nach Verkaufspreisen für dieses eBay-Konto zu suchen.

|*Währung*
|Währung oder *ALLE* wählen, um nach Verkaufspreisen für diese Währung zu suchen.

|*Sprache*
|Sprache oder *ALLE* wählen, um nach Verkaufspreisen in dieser Sprache zu suchen. Standardmäßig ist *Deutsch* voreingestellt.

|*Land*
|Land oder *ALLE* wählen, um nach Verkaufspreisen für dieses Lieferland zu suchen.
|====

[#700]
==== Die Namen in mehreren Sprachen speichern

Nachdem du einen Verkaufspreis erstellt hast, übersetze nach Bedarf den Namen des Verkaufspreises in die von dir verwendeten Sprachen.

[.instruction]
Verkaufspreis übersetzen:

. Öffne das Menü *Einrichtung » Artikel » Verkaufspreise*.
. Öffne den Verkaufspreis im Tab *Preise*.
. Wechsele in das Tab *Sprache*.
. Gib den *internen Namen* in den benötigten Sprachen ein.
. Gib den *externen Namen* in den benötigten Sprachen ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#800]
==== Erweiterte Einstellungen (nicht im Assistenten enthalten)

//auch wie man dahin kommt. Ala, "<<link to 600, Suche nach dem Verkaufspreis>>."

[#900]
=== Verkaufspreis mit einer Variante verknüpfen

//hier nur auf den Abschnitt in die große Seite verlinken?

[#1000]
== Preiskalkulationen

Preiskalkulationen ermöglichen dir das gezielte Zuschneiden und Staffeln von Preisen für Kundenklassen und Herkünfte. Zuerst <<artikel/einstellungen/preise#600, erstellst>> du individuelle Preisvarianten im Menü *Einrichtung » Artikel » Preiskalkulation*. Danach <<artikel/artikel-verwalten#240, verknüpfst>> du die Preiskalkulationen mit Varianten.

Preiskalkulationen werden automatisch auf die hinterlegten Preise angerechnet. Du kannst Preiskalkulationen auch per <<artikel/artikel-verwalten#330, Varianten-Gruppenfunktion>> für mehrere Artikelvarianten gleichzeitig einstellen.

[#1100]
=== Preiskalkulationen erstellen

[.instruction]
Preiskalkulation erstellen:

. Öffne das Menü *Einrichtung » Artikel » Preiskalkulation*.
. Klicke auf icon:plus[role="green"] *Neue Preiskalkulation*. +
→ Das Fenster *Neue Preiskalkulation* wird geöffnet.
. Gib einen Namen ein.
. Klicke auf icon:plus[role="green"] *Hinzufügen*. +
→ Die neue Preiskalkulation wird geöffnet.
. Nimm die Einstellungen vor. Beachte <<table-create-price-calculation>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-create-price-calculation]]
.Preiskalkulation erstellen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|*Einstellungen*

|*Name*
|Name für die Preiskalkulation eingeben. Der Name wird im Bereich *Verkaufspreise* im Tab *Einstellungen* einer Artikelvariante angezeigt.

|*Preisquelle*
|Preis wählen, der als Grundlage für die Preiskalkulation dient.

|*Transportkosten*
|Aktivieren, um Transportkosten zur Preisquelle zu addieren. Die Transportkosten werden im Bereich *Kosten* im Tab *Einstellungen* einer Artikelvariante eingegeben.

|*Lagerkosten*
|Aktivieren, um Lagerkosten zur Preisquelle zu addieren. Die Lagerkosten werden im Bereich *Kosten* im Tab *Einstellungen* einer Artikelvariante eingegeben.

|*Zoll*
|Aktivieren, um Zollkosten zur Preisquelle zu addieren. Die Zollkosten werden im Bereich *Kosten* im Tab *Einstellungen* einer Artikelvariante eingegeben. Die Zollkosten werden in Prozent angegeben.

|*Betriebskosten*
|Aktivieren, um Betriebskosten zur Preisquelle zu addieren. Die Betriebskosten werden im Bereich *Kosten* im Tab *Einstellungen* einer Artikelvariante eingegeben. Die Betriebskosten werden in Prozent angegeben.

|*MwSt.*
|Aktivieren, um die Umsatzsteuer zur Preisquelle zu addieren. Der Umsatzsteuersatz wird im Bereich *Kosten* im Tab *Einstellungen* einer Artikelvariante gewählt. Die Umsatzsteuer wird in Prozent angegeben.

2+|*Verknüpfungen*

|*Hinzufügen*
|Auf *Hinzufügen* klicken, um eine neue Verknüpfung zu erstellen.

|*Ziel*
|Preis wählen, der als Zielpreis für die Preiskalkulation dient.

|*Operator*
|Operator wählen. *Plus*, *Minus*, *Plus Prozentwert*, *Minus Prozentwert*, *Mal* und *Geteilt* stehen zur Auswahl.

|*Operand*
|Numerischen Wert eingeben.

//Preiskalkulation: aktuell sind Herkunft/Mandant nur in Bezug auf Herstellerprovisionen. Da die Verkaufspreise eh für Mandante konfigurierbar sind.
|*Mandant (Shop)*
|Mandant (Shop) wählen, der mit der Preiskalkulation verknüpft wird.

|*Herkunft*
|Herkunft wählen, die mit der Preiskalkulation verknüpft wird.
|====
