= Verfügbarkeiten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Verfügbarkeit, Verfügbarkeiten, Artikelverfügbarkeit, Artikelverfügbarkeiten, Verfügbarkeitsstufe, Verfügbarkeitsstufen, Verfügbarkeitssymbol, Verfügbarkeit-Symbol, Callisto, Backend-Symbol, Webshop-Symbol, Lieferzeit, Lieferzeiten, Lieferung, AvailabilityString, AvailabilityIcon, ItemViewSingleItem, Attribut-Verfügbarkeit, Server-Prüfung, Client-Prüfung
:description: Lerne, wie du die zehn Verfügbarkeitssymbole in plentymarkets konfigurierst.
:url: artikel/einstellungen/verfuegbarkeiten
:position: 70
:id: TFKTSN1
:author: team-item

Aufgrund gesetzlicher Vorgaben muss für alle Artikel, die du anbietest, die Lieferfrist im Webshop angeben werden. In plentymarkets stehen zehn Verfügbarkeitsangaben zur Auswahl.

Konfiguriere zunächst die zehn Verfügbarkeitsstufen. Im zweiten Schritt definierst du dann die <<artikel/artikel-verwalten#intable-symbol, Verfügbarkeit jedes Artikels>>.

[#100]
== Verfügbarkeitsstufen konfigurieren

Die Verfügbarkeitstexte gibst du einmalig im plentymarkets Backend ein. Auch die Verfügbarkeitssymbole kannst du durch eigene Symbole ersetzen.

[.instruction]
Verfügbarkeitsangaben festlegen:

. Öffne das Menü *Einrichtung » Artikel » Verfügbarkeit*.
. Nimm die Einstellungen vor. Beachte <<table-define-availability>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[table-define-availability]]
.Verfügbarkeitsangaben festlegen
[cols="1,3a"]
|====
|Einstellung |Erläuterung

| *ID*
|Die IDs 1-10 wurden automatisch von plentymarkets vergeben und können nicht geändert werden.

*_Anwendungsfall_*: Stell dir vor, du willst eine Menge <<daten/daten-importieren/sync-typen/elasticSync-artikel#2300, Artikeldaten mit Hilfe einer CSV-Datei importieren>>. Unter anderem willst du die Verfügbarkeit jedes Artikels angeben. Anhand der IDs 1-10 kannst du die Verfügbarkeit jedes Artikels angeben.

| *Backend-Symbol*
|Hier werden die systemseitigen Verfügbarkeitssymbole angezeigt. Die Symbole sind standardmäßig eingestellt und können durch eigene Symbole ersetzt werden.

| *Name*
|Gib einen Namen oder eine Beschreibung für die Lieferzeit ein, z.B. Lieferung innerhalb von 48 Stunden, 3-5 Werktage, usw.

*_Tipp_*: Wähle eine andere Sprache aus der Dropdown-Liste, wenn du die Verfügbarkeitstexte in mehreren Sprachen speichern möchtest.

| **Durchschnittliche Lieferzeit**
|Gib die durchschnittliche Lieferzeit in Tagen ein. Diese Werte werden von Suchmaschinen ausgewertet.

*_Tipp_*: Gib realistische Lieferzeiten ein, da diese Angaben als Zusage gewertet werden und auch wettbewerbsrechtlich relevant sind.

| *Webshop-Symbol*
|Hier siehst du drei Schaltflächen.
Klicke auf die Schaltfläche ganz links, um eine Detailansicht des Symbols zu öffnen.

[cols="1,4"]
!===

! icon:upload[set=plenty, role="purple"]
! Klicke auf diese Schaltfläche, um dein eigenes Webshop-Symbol hochzuladen.
Das Symbol wird anstelle des Backend-Symbols im Webshop angezeigt. +
Mögliche Bildformate: *PNG*, *JPG* und *GIF*. Ideale Bildgröße: *16 x 16 Pixel*.

! icon:minus-circle[role="red"]
! Klicke auf diese Schaltfläche, um dein eigenes Webshop-Symbol zu löschen.
Nach dem Löschen wird das systemseitige Symbol im Webshop angezeigt.

!===
|====

[#200]
== Alter Webshop: Verfügbarkeit im Callisto Webshop anzeigen

Die Verfügbarkeit wird in Callisto standardmäßig über das Template <<webshop/webshop-einrichten/cms-syntax#webdesign-itemview-container-itemviewsingleitem, ItemViewSingleItem>> im Webshop angezeigt. Über die Template-Variablen **$AvailabilityString** und **$AvailabilityIcon** werden Verfügbarkeitstext und -symbol im Webshop dargestellt. Diese Template-Variablen sind standardmäßig im Template **ItemViewSingleItem** der plentymarkets Standard-Designs enthalten.

[TIP]
.Fehlerhafte Anzeige der Verfügbarkeit im Webshop
====
Wenn du eigene Webshop-Symbole für die Verfügbarkeit verwendest, lade für alle Verfügbarkeiten ein Symbol hoch, da bei fehlendem Symbol ein leerer Rahmen im Design angezeigt wird. +
Wenn die Webshop-Symbole nach Änderungen nicht korrekt im Webshop angezeigt werden, lösche den Cache deines Browsers und lade die Seite neu.
====

[IMPORTANT]
.Wechselwirkung: Attribut-Verfügbarkeit
====
Ob die Variante im Webshop sichtbar ist, hängt davon ab, welche <<webshop/webshop-einrichten/artikelansichten#, Art der Prüfung>> im Menü *Einrichtung » Mandant » [Mandant wählen] » Artikelansichten » Einstellungen* für die Attribut-Verfügbarkeit gewählt wurde:

* Wenn für die Option **Attribut-Verfügbarkeit** die Einstellung **Server-Prüfung** gewählt wurde, ist die Variante sichtbar und wählbar. Die Verfügbarkeit wird erst bei Auswahl des letzten Attributwerts im Bestellvorgang geprüft.
* Bei der Einstellung **Client-Prüfung** wird die Variante nicht im Webshop angezeigt oder ausgegraut.
====

[#300]
== Alte Systeme: Verfügbarkeiten aktivieren/deaktivieren

In der Regel sind nur zwei Schritte nötig, um die Lieferzeiten der in deinem Webshop angebotenen Artikel anzugeben.
Zuerst <<artikel/einstellungen/verfuegbarkeiten#100, definierst du die einzelnen Verfügbarkeitsstufen>>, z.B. Lieferung innerhalb von 48 Stunden, 3-5 Werktage, usw.
Dann <<artikel/artikel-verwalten#intable-symbol, verknüpfst du die passende Verfügbarkeitsstufe mit jedem deiner Artikel>>.

Die Verfügbarkeitsstufen sind standardmäßig aktiviert und im Webshop sichtbar.
Wurde eine Verfügbarkeit aber aus irgendeinem Grund deaktiviert, sind Produkte mit dieser Verfügbarkeit nicht mehr im Webshop sichtbar.
Sollte also ein Artikel nicht in deinem Webshop auftauchen, prüfe, ob die Verfügbarkeit für den Shop aktiviert ist.

[TIP]
.Diese Einstellung betrifft nur ältere Systeme
====
Bei neuen Systemen ist diese Einstellung obsolet und wird nicht mehr angezeigt. Wir empfehlen dir zu prüfen, ob du diese Einstellung in deinem System hast. Falls ja, aktiviere die Einstellung.
====

[.instruction]
Verfügbarkeiten für den Shop aktivieren:

. Falls vorhanden, öffne das Menü *Einrichtung » Mandant » [Mandant wählen] » Artikelansichten » Verfügbarkeit*.
. Aktiviere die Verfügbarkeiten mit gedrückter Strg- oder Cmd-Taste.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
