= Setting up idealo Checkout in plentymarkets
:lang: en
include::{includedir}/_header.adoc[]
:keywords: idealo, idealo Checkout, market, marketplace, price comparison
:description: Multi-Channel in plentymarkets: Set up the interface to the market idealo Checkout in your plentymarkets system.
:position: 10

On this page, you will find information about the settings you need to carry out in order to set up the market idealo Checkout in plentymarkets. Learn how to set up the interface, how to export items to idealo and how to define sales prices.

[#100]
== Registering with idealo

You need to register with link:http://www.idealo.de/[idealo^] before setting up idealo in plentymarkets. Please note that the website is currently only available in German.

[#200]
== Setting up idealo in plentymarkets

[IMPORTANT]
.Check idealo product CSV
====
Not all of the columns of idealo’s product CSV are available in plentymarkets at present. Check whether you need columns which are not yet available in plentymarkets prior to setting up idealo in plentymarkets. In this case, an integration of idealo is currently not possible. +
An overview of the columns which are available in plentymarkets can be found in the link:https://marketplace.plentymarkets.com/en/plugins/channels/preisportale/elasticexportidealode_4723[idealo plugin user guide^].
====

Carry out the following settings in plentymarkets in order to set up the interface to idealo.

[.instruction]
Setting up idealo:

. Go to *System » Markets » idealo Checkout*.
. Activate the automatic data exchange.
. Enter the API key as received from idealo.
. *Save* the settings.

Connecting to this market allows for the following automatic processes to take place:

* hourly order synchronisation

[#225]
== Installing the idealoDE-plugin

Data is transferred to idealo via the elastic export. In order to automatically transfer data to idealo, install the plugins link:https://marketplace.plentymarkets.com/en/plugins/channels/marktplaetze/elasticexport_4763[Elastic Export^] and link:https://marketplace.plentymarkets.com/en/plugins/channels/preisportale/elasticexportidealode_4723[idealo.de^] from the link:https://marketplace.plentymarkets.com/en[plentyMarketplace^]. For further information about the idealo item export, refer to the <<Setting up the item export, Setting up the item export>> chapter.

Installing the idealoDE plugin allows for the following processes to take place:

* automatic data transfer to idealo via the elastic export

[#250]
== Activating an order referrer

In order to link items, properties etc. with idealo, you have to activate the order referrer *idealo* in the menu *System » Orders » Order referrer* menu. +

If you want to use *idealo Checkout*, then also activate the order referrer *idealo Checkout*, as described in the <<Setting up idealo Checkout in plentymarkets, Setting up idealo Checkout in plentymarkets>> chapter.

[.instruction]
Activating the order referrer for idealo:

. Go to *System » Orders » Order referrer*.
. Place a check mark next to the option *idealo*.
. *Save* the settings.

[#275]
== Setting up idealo Checkout in plentymarkets

idealo Checkout enables your customers to buy items directly on the idealo website without having to enter your web shop. In order to set up idealo Checkout in plentymarkets, activate the order referrer *idealo Checkout*.

[.instruction]
Activating the order referrer for idealo Checkout:

. Go to *System » Orders » Order referrer*.
. Place a check mark next to the option *idealo Checkout*.
. *Save* the settings.

If you activate the order referrer *idealo Checkout*, then the column *checkout_approved* in the file which is generated with the elastic export is set to *true*.

[#300]
== Setting the item availability

Items have to be available for idealo. This is done in the *Availability* tab of an item within the <<item/managing-items#180, Item » Edit item » Open item » Tab: Variation ID>> menu. Activate the item availability for idealo as described below.

[.instruction]
Setting the item availability for idealo:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section. +
→ A list with all available markets is displayed.
. Activate the option *idealo*.
. Activate the option *Web API*.
. Click on *Add*. +
→ The market is added.
. *Save* the settings.

If you want to use idealo Checkout, then also activate the order referrer *idealo Checkout* in the *Markets* section. +

The availability for variations can be individually edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

[#400]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer idealo. This price is displayed on idealo.

[.instruction]
Defining a sales price for idealo:

. Open the menu *System » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *idealo*.
. *Save* the settings.

[#500]
==  Defining SKU manually

Add SKUs manually for specific referrers in the menu <<item/managing-items#170, Item » Edit item » Open item » Tab: Variation ID » Tab: Availability>> if needed.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
.  Click on the *Availability* tab.
.  Click on *Add* in the section *SKU*. +
→ The window *New SKU* is displayed.
.  Select the referrer *idealo*.
.  Enter the SKU.
.  Click on *Add*. +
→ The SKU is saved and displayed.

[#550]
== Setting up a shipping company as shipping method

If the order is carried out by a shipping company, the customer has to enter their phone number during the order process in order to arrange a delivery date. The shipping method shipping company is transferred as a property to idealo Checkout. Proceed as described below to create the property *FulfillmentType*.

[.instruction]
Creating a property for the shipping method shipping company:

. Go to <<item/managing-items#480, System » Item » Properties » Tab: New property>>.
. Enter the *Name (internal)*.
. Select *No* from the property type drop-down list.
. Select the property *FulfillmentType* for *idealo Direktkauf property*.
. *Save* the settings.

Next, you have to link the property to the item in the *Item » Edit item » Open item » Open variation » Tab: Properties* menu. Then set up the item export as described below.

For items which have the shipping method shipping company, it is also possible to transfer the additional services *TwoManHandlingPrice* and *DisposalPrice* to idealo Checkout. DisposalPrice can only be used in combination with the TwoManHandlingPrice. That means you have to create the property *TwoManHandlingPrice* as well as the property *DisposalPrice* and link them to the item. In both cases, select *Text* as the property type. Go to *Item » Edit item » Open item » Open variation » Tab: Properties* and enter the surcharge for the additional service with two decimal places behind the decimal separator. Use a period for the decimal separator (19.99).

[#600]
== Setting up the item export

Items are exported to idealo via elastic export with the data format IdealoDE. Therefore, the plugins *ElasticExport* and *ElasticExportIdealoDE* have to be installed. First, create the data format IdealoDE. Then transfer the URL to idealo.

[.instruction]
Setting up the item export:

. Go to *Data » Elastic export*.
. Click on *New export*.
. Carry out the settings. Pay attention to the explanations given in <<settings-item-export>>.
. Carry out further settings for item filters and format settings. Pay attention to the explanations given in table 2 on the <<basics/data-exchange/elastic-export, Elastic export>> page of the manual.
. *Save* the settings. +
→ The export format is given an ID and it appears in the overview within the *Exports* tab.

[[settings-item-export]]
.Settings for the item export
[cols="1,3"]
|====
|Setting |Explanation

2+|Settings

|*Name*
|Enter a name. The export format is listed by this name in the overview within the *Exports* tab.

|*Type*
|Select the type *item* from the drop-down list.

|*Format*
|Select the format *IdealoDE* from the drop-down list.

|*Limit*
|Enter a number. If you want to transfer more than 10,000 data records to idealo, then the output file will not be generated again for another 24 hours. This is to save resources.

|*Provisioning*
|Select *URL*.

|*Token, +
URL*
|If you have selected the option *URL* under *Provisioning*, then click on *Generate token*. The token is entered automatically. The URL is entered automatically if the token was generated under *Token*. Give this URL to idealo in order to export the items.
|====

[#650]
==  Activating payment methods

Activate the payment method *idealo Checkout*. This allows payments to be made for orders on idealo and displayed in your plentymarkets system.

[.instruction]
Activating idealo payment methods:

.  Go to *System » Orders » Payment » Methods*.
.  Place a check mark next to the setting *Also show inactive*.
. Open the folder *DE* &gt; *idealo Checkout*.
. Select the idealo payment method. +
→ The *Settings* tab opens.
.  Carry out the settings. Pay attention to the explanations given in <<settings-payment-method>>.
.  Place a check mark next to the option *Active*.
. *Save* the settings.

[[settings-payment-method]]
.Settings for the payment method
[cols="1,3"]
|====
| Setting | Explanation

|*Language*
| The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo* and *Upload logo*. This enables you to enter values for these options in various languages. The values for a language will be activated as soon as a buyer selects the language in the online store.

|*Name*
| Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
| Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
| If you have selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
| Do not select a country of delivery. +
 You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely set up.

|*Logo*
| Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

|*Logo view*
| If *Show upload logo* has been selected from the *Logo* drop-down list, then the logo that has been uploaded is displayed here.

|*Upload logo*
| If *Show upload logo* has been selected from the *Logo* drop-down list, upload an external logo here. +
 Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG and JPG.

|*Priority*
| Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
| If the payment method results in additional costs, enter the percentage value or the flat rate value. The choice depends on the conditions of your contract. *Important*: Do not enter a value into both fields. +
For further information, refer to the <<basics/statistics/managing-statistics#, Managing statistics>> page of the manual. For an example of flat rate and percentage costs, refer to the <<order-processing/payment/managing-payment-methods#20, Managing payment methods>> page of the manual.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *System » CRM » Classes* to activate or deactivate *Permitted payment methods*. +
For further information, refer to the <<order-processing/payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter.
====

For further information, refer to the <<order-processing/payment/managing-payment-methods#, Managing payment methods>> page of the manual.

[IMPORTANT]
.PayPal payment method
====
If you offer the PayPal payment method, it is mandatory to create and set up this payment method in your plentymarkets system. This is to ensure that the payment is imported correctly and assigned to the order.
====

[#700]
== Automatically sending order confirmations

Set up an <<basics/automation/event-procedures, event procedure>> to automatically send an order confirmation to idealo.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<order-confirmation-idealo>> below.
. *Save* the settings.
.  Carry out the settings as described in <<order-confirmation-idealo>> below.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[order-confirmation-idealo]]
.Event procedure for sending automatic order confirmations to idealo
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order generation: New order*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*idealo Checkout*

|*Procedure*
|*Order &gt; Send order confirmation to idealo*
|
|====

[#800]
== Automatically sending shipping confirmations

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically send a shipping confirmation to idealo when the outgoing items have been booked.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<shipping-confirmation-idealo>> below.
. *Save* the settings.
.  Carry out the settings as described in <<event-procedure-shipping-confirmation>> below.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[shipping-confirmation-idealo]]
.Event procedure for automatically sending shipping confirmations to idealo
[cols="1,3,3"]
|====
|Setting |Option | Selection

|*Event*
|*Order change: Outgoing items booked*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*idealo Checkout*

|*Procedure*
|*Shipping &gt; Send shipping confirmation to idealo*
|
|====

[#850]
== Automatically sending returns

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically inform idealo about returns.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-returns-idealo>> below.
. *Save* the settings.
.  Carry out the settings as described in <<event-procedure-returns-idealo>> below.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[event-procedure-returns-idealo]]
.Event procedure for sending automatic returns to idealo
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order generation: New return*
|

|*Filter 1*
|*Order &gt; Order type*
|*Return*

|*Filter 2*
|*Order &gt; Referrer*
|*idealo Checkout*

|*Procedure*
|*Returns &gt; Send return to idealo*
|
|====

[#900]
== Automatically sending cancellations

Set up an <<basics/automation/event-procedures#, event procedure>> to automatically inform idealo of cancellations.

[.collapseBox]
.Setting up an event procedure
--
.  Go to *System » Orders » Events*.
.  Click on *Add event procedure*. +
→ The *Create new event procedure* window opens.
.  Enter a name.
.  Select the *event* listed in <<event-procedure-cancellations-idealo>> below.
. *Save* the settings.
.  Carry out the settings as described in <<event-procedure-cancellations-idealo>> below.
. Select a *reason* for the cancellation.
.  Place a check mark next to the option *Active*.
. *Save* the settings.
--

[[event-procedure-cancellations-idealo]]
.Event procedure for automatically sending cancellations to idealo
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Status change: [8] Cancelled*
|

|*Filter 1*
|*Order &gt; Order type*
|*Order*

|*Filter 2*
|*Order &gt; Referrer*
|*idealo Checkout*

|*Procedure*
|*Order &gt; Send cancellation to idealo*
|
|====

[#1000]
== Viewing the API log

The menu *Data » API log » Tab: API log* contains a history of processes that run via the idealo interface. The *idealoDirektkauf* format is available for idealo.

[.instruction]
Viewing the API log:

.  Go to *Data » API log » Tab: API log*.
.  Select the format *idealoDirektkauf* from the *Process* drop-down list.
.  Select a date if you only want to see entries for a specific day.
.  Select the number of results per page.
.  Click on *Search* to display the results.
