= Setting up idealo
:lang: de
include::{includedir}/_header.adoc[]
:keywords: idealo, idealo Direktkauf, idealo Checkout, market, marketplace, price comparison
:description: Multi-Channel in plentymarkets: Set up the interface to the market idealo Checkout in your plentymarkets system.
:position: 10
:url: markets/idealo-checkout/idealo-setup
:id: JFWN4QY

On this page, you will find information about the settings you need to carry out in order to set up the market and price comparison portal idealo Checkout in plentymarkets. Learn how to set up the interface, how to export items to idealo Checkout and how to define sales prices. +

[.subhead]
About idealo

idealo started business in 2000 with the vision of helping users to make the right choices when buying products online and, now counting 50,000 sellers and 18 million users per month, has become one of Germany's most important e-commerce websites. +

With idealo Checkout, idealo offers a strong sales channel. The "Zum Kauf" (Buy now) button allows users to order a product directly on idealo.de, using a fully integrated checkout function. The sellers remain the contractual partners and take care of fulfilment as usual.

[.subhead]
idealo price comparison and idealo Checkout

With plentymarkets, you can both use the idealo price comparison and idealo Checkout (idealo's checkout function). If you set up idealo Checkout, you enable your customers to buy your products directly at idealo without having to enter your online store.


[#100]
== Registering with idealo

You have to register as a seller with idealo to set up the market in plentymarkets.

[IMPORTANT]
.Item data export
====
Inform idealo about how item data should be transferred before setting up idealo in plentymarkets (creating, updating, and deleting items on idealo). Item data can either be exported with a CSV file or via API (PWS 2.0 interface). +
If you export your items with PWS 2.0, items will be created on idealo once a day. Prices and stock are updated every 15 minutes. Items can also be deleted every 15 minutes. +
If you export your items with a CSV file using the elastic export, your items can be retrieved by idealo via URL. +
How to set up the different methods of data transfer in plentymarkets is described in the chapter <<Setting up the item export, Setting up the item export>>.
====

[#150]
=== Installing the Elastic Export plugin

In order to use the idealo plugin, you have to install the link:https://marketplace.plentymarkets.com/en/plugins/sales/marktplaetze/elasticexport_4763[Elastic Export^] plugin first. You can download the plugin in the link:https://marketplace.plentymarkets.com/en[plentyMarketplace^].


[#200]
== Going through the idealo assistant

Go through the *idealo Basic settings* assistant in the *Setup » Assistants » Omni-Channel* menu to carry out the basic settings for idealo in plentymarkets. With this assistant, you set up your idealo account in plentymarkets and carry out settings for the item data export to idealo and order import from idealo Checkout. +

[IMPORTANT]
.Item data export via API
====
It is mandatory to go through the *idealo Basic settings* assistant if you export your items to idealo with PWS 2.0. The automatic item export can only be set up in this assistant.
====


[#300]
== idealo price comparison and idealo Checkout

Depending on whether you only want to use the idealo price comparison or whether you want to enable your customers to buy items directly at idealo without having to enter your online store, different settings must be carried out. The overview below lists the settings required for idealo Checkout.

→ *Settings for idealo Checkout:*

- *Basic settings:* Go through the *idealo Basic settings* assistant in the *Setup » Assistants » Omni-Channel* menu.
- *Item export:* Set up the <<Item export via API (PWS 2.0 interface), automatic item export>> or the <<Item export with elastic export, item export via CSV file>>, depending on how you want to export your items to idealo.
- *Order referrer:* In addition to the order referrer *idealo*, also activate the <<Activating the order referrer, order referrer>> *idealo Checkout* in the *Setup » Orders » Order referrer* menu.
- *Item availability:* In addition to the option *idealo*, also activate the <<Setting the item availability, availability>> *idealo Checkout* in the *Item » Edit item » Open item » Tab: Variation ID » Tab: Availability* menu in the *Markets* section.
- *Sales price:* Set up a <<Defining a sales price, sales price>>.
- *SKU:* Add <<Defining SKU manually, SKUs>> if needed.
- *Payment method:* Activate the <<Activating the payment method idealo Direktkauf, payment method>> *idealo Direktkauf*.
- *Characteristics:* Create <<Creating characteristics, characteristics>> for idealo Checkout. With characteristics, you can transfer item properties, shipping methods, and charges to idealo Checkout.
- *Event procedures:* Set up <<Setting up event procedures, event procedures>> to automatically inform idealo Checkout about changes in the order status.


[#400]
== Activating the order referrer

In order to link items, characteristics etc. with the idealo price comparison portal, you have to activate the idealo order referrer in the *Setup » Orders » Order referrer* menu.

[.instruction]
Activating the order referrer for the idealo price comparison:

. Go to *Setup » Orders » Order referrer*.
. Place a check mark next to *idealo*.
. *Save* (icon:save[role="green"]) the settings.

If you would like to use idealo Checkout, then also activate the order referrer *idealo Checkout*. If you activate the order referrer *idealo Checkout*, then the column *checkout_approved* in the CSV file that is generated in the elastic export is set to *true*.


[#500]
== Setting the item availability

Items have to be available for idealo. This is done in the *Availability* tab of an item within the *Item » Edit item » Open item » Tab: Variation ID* menu. Activate the item availability for idealo as described below.

[.instruction]
Setting the item availability for the idealo price comparison:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section. +
→ A list with all available markets is displayed.
. Activate the option *idealo*.
. Activate the option *Web API*.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The market is added.
. *Save* (icon:save[role="green"]) the settings.

The availability for variations can be edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

If you want to use idealo Checkout, then also activate the option *idealo Checkout* in the *Markets* section.


[#600]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer idealo. This price is displayed on idealo. It is valid for the idealo price comparison and idealo Checkout.

[.instruction]
Defining a sales price for idealo:

. Go to *Setup » Item » Sales prices » Open sales price » Tab: Settings*. +
→ If you have not yet created a sales price, click on *New* to create a sales price.
. Place a check mark next to the referrer *idealo*.
. *Save* (icon:save[role="green"]) the settings.

[TIP]
.Minimum price
====
If you want to use a minimum price for the "price range" feature for idealo, then you have to define at least two sales prices for idealo: a minimum price and a standard sales price. The minimum price must have the price type *Special offer* and must be linked to the referrer *idealo Direktkauf*. +
Which price should be transferred to idealo as minimum price is defined with the setting *Which price would you like to transfer to idealo as minimum price?* in the *Item data* step of the idealo assistant. +
The "price range" feature must also be activated at idealo.
====


[#700]
== Defining SKU manually

Add SKUs manually for specific referrers in the *Item » Edit item » Open item » Tab: Variation ID » Tab: Availability* menu if needed.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Click on the *Availability* tab.
. Click on *Add* (icon:plus-square[role="green"]) in the *SKU* section. +
→ The *New SKU* window is displayed.
. Select the referrer *idealo*.
. Enter the SKU.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The SKU is saved and displayed.

If you want to use idealo Checkout, also add SKUs with the referrer *idealo Direktkauf*.


[#800]
== Setting up the item export

Items can be transferred to idealo with the automatic item export via API (PWS 2.0 interface) or via a CSV file with the elastic export. Depending on how you want to transfer your items to idealo, different settings are required. +

[IMPORTANT]
.Data transfer to idealo
====
Inform idealo about how item data should be transferred before the setup in plentymarkets.
====

Information about the different types of data transfer is available in <<item-export-idealo>>.

[[item-export-idealo]]
.idealo data transfer
[cols="1,3"]
|====
| Item export via API (PWS 2.0) | Item export via elastic export

|Item data export via interface
|Item data export via CSV file

|Items are created once a day
|Retrieval of item data via URL that is saved at idealo

|Price updates every 15 minutes
|Time interval for retrieval of item data is defined by idealo

|Stock updates every 15 minutes
|
|====

[#850]
=== Item export via API (PWS 2.0 interface)

If you want to transfer your items to idealo via API, go through the *idealo Basic settings* assistant in the *Setup » Assistants » Omni-Channel* menu and activate the automatic item data export. Apart from the assistant, no further settings are required to set up the automatic item export in plentymarkets. +

If you transfer your items via API, items will be created at idealo once per day. Prices and stock will be updated every 15 minutes. Items can also be deleted every 15 minutes.


[#900]
=== Item export with elastic export


If you export items via the elastic export, you have to carry out a few settings in the *Data » Elastic export* menu to set up the export format. In order to use the elastic export, the link:https://marketplace.plentymarkets.com/en/plugins/sales/marktplaetze/elasticexport_4763[Elastic Export^] plugin must be installed in your plentymarkets system. First create the data format IdealoDE and afterwards transfer the URL to idealo so that idealo will be able to retrieve your item data.

How to set up the elastic export to export your items to idealo is described in the following chapters <<Setting up the data format IdealoDE plugin in plentymarkets, Setting up the data format IdealoDE plugin in plentymarkets>> and <<Available columns for the export file, Available columns for the export file>>.

[#950]
==== Setting up the data format IdealoDE plugin in plentymarkets

[TIP]
.Settings only for elastic export
====
The settings described in this chapter only need to be carried out if you transfer your items to idealo with the elastic export.
====

[TIP]
.Check idealo product CSV
====
Not all of the columns of idealo's product CSV are available in plentymarkets at present. Check whether you need columns which are not yet available in plentymarkets prior to setting up idealo in plentymarkets. In this case, an integration of idealo is currently not possible. +
An overview of the columns which are available in plentymarkets can be found in the <<Available columns for the export file, Available columns for the export file>> chapter.
====

Set up the export format *IdealoDE* so that your items can be exported to idealo with the elastic export. For further information about the elastic export, refer to the <<data/exporting-data/elastic-export#, Elastic Export>> page. It is required to install the *Elastic export* plugin from the plentyMarketplace first before you can use the format *IdealoDE* for the elastic export.

[.instruction]
Creating a new export format:

. Go to *Data » Elastic export*.
. Click on *New export*.
. Carry out the settings as desired. Pay attention to the explanations given in <<format-settings-idealo>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The export format is given an ID and it appears in the overview within the *Exports* tab.

The following table lists details for settings, format settings and recommended item filters for the format *IdealoDE plugin*.

[[format-settings-idealo]]
.Format settings for IdealoDE
[cols="1,3"]
|====
|*Setting*  |*Explanation*

2+|*Settings*

|*Name*
|Enter a name. The export format will be listed under this name in the overview within the *Exports* tab.

|*Type*
|Select the type *Item* from the drop-down list.

|*Format*
|Select *IdealoDE-Plugin*.

|*Limit*
|Enter a number. If you want to transfer more than 9,999 data records to the price search engine, then the output file will not be generated again for another 24 hours. This is to save resources. If more than 9,999 data records are necessary, the setting *Generate cache file* has to be active. +
*Or:* If you want to transfer more than 9,999 data records to idealo, you can also install version 2.0 of the idealo plugin.

|*Generate cache file*
|Place a check mark if you want to transfer more than 9,999 data records to the price search engine. The output file will not be generated again for another 24 hours. We recommend not to activate this setting for more than 20 export formats. This is to save resources.

|*Provisioning*
|Select *URL*.

|*File name*
|The file name must have the ending *.csv* or *.txt* for idealo.de to be able to import the file successfully.

|*Token, URL*
|If you have selected the option *URL* under *Provisioning*, then click on *Generate token*. The token will be entered automatically. When the token is generated under *Token*, the URL is entered automatically.

2+|*Item filters*

|*Add item filters*
|Select an item filter from the drop-down list and click on *Add*. There are no filters set in default. It is possible to add multiple item filters from the drop-down list one after the other. +
*Variations* = Select *Transfer all* or *Only transfer main variations*. +
*Markets* = Select *idealo*. +
The availability for all markets selected here has to be saved for the item. Otherwise, the export will not take place. +
*Currency* = Select a currency. +
*Category* = Activate to transfer the item with its category link. Only items belonging to this category will be exported. +
*Image* = Activate to transfer the item with its image. Only items with images will be transferred. +
*Client* = Select client. +
*Stock* = Select which stocks you want to export. +
*Flag 1 - 2* = Select the flag. +
*Manufacturer* = Select one, several or *ALL* manufacturers. +
*Active* = Only active variations will be exported.

2+|*Format settings*

|*Product URL*
|Choose wich URL should be transferred to the price comparison portal, the item’s URL or the variation’s URL. Variation SKUs can only be transferred in combination with the Ceres store.

|*Client*
|Select a client. This setting is used for the URL structure.

|*URL parameter*
|Enter a suffix for the product URL if this is required for the export. If you have activated the transfer option for the product URL further up, then this character string will be added to the product URL.

|*Order referrer*
|Choose the order referrer *idealo*. The selected referrer is added to the product URL so that sales can be analysed later.

|*Marketplace account*
|Select the marketplace account from the drop-down list.

|*Language*
|Select the language from the drop-down list.

|*Item name*
|Select *Name 1*, *Name 2* or *Name 3*. These names are saved in the *Texts* tab of the item. Enter a number into the *Maximum number of characters (def. Text)* field if desired. This specifies how many characters should be exported for the item name.

|*Preview text*
|Select the text that you want to transfer as preview text. +
Enter a number into the *Maximum number of characters (def. text)* field if desired. This will specify how many characters should be exported for the item name. +
Activate the option *Remove HTML tags* if you want HTML tags to be removed during the export. +
If you only want to allow specific HTML tags to be exported, then enter these tags into the field *Permitted HTML tags, separated by comma (def. Text)*. Use commas to separate multiple tags.

|*Description*
|Select the text that you want to transfer as description. +
Enter a number into the *Maximum number of characters (def. text)* field if desired. This specifies how many characters should be exported for the description. +
Activate the option *Remove HTML tags* if you want HTML tags to be removed during the export. If you only want to allow specific HTML tags to be exported, then enter these tags into the field *Permitted HTML tags, separated by comma (def. Text)*. Use commas to separate multiple tags.

|*Target country*
|Select the target country from the drop-down list.

|*Barcode*
|Select the ASIN, ISBN or an EAN from the drop-down list. The barcode has to be linked to the order referrer selected above. If the barcode is not linked to the order referrer it will not be exported.

|*Image*
|Select *Position 0* or *First image* to export this image. +
*Position 0* = An image with position 0 will be transferred. +
*First image* = The first image will be transferred.

|*Image position of the energy efficiency label*
|Enter the position. Every image that should be transferred as an energy efficiency label must have this position.

|*Stock buffer*
|The stock buffer for variations with the limitation to the net stock.

|*Stock for variations without stock limitation*
|The stock for variations without stock limitation.

|*Stock for variations with no stock administration*
|The stock for variations without stock administration.

|*Live currency conversion*
|Activate this option to convert the price into the currency of the selected country of delivery. The price has to be released for the corresponding currency.

|*Retail price*
|Select gross price or net price from the drop-down list.

|*Offer price*
|This option does not affect this format.

|*RRP*
|Activate to transfer the RRP.

|*Shipping costs*
|The chosen payment method does not affect this format. All payment methods of the selected configuration will be exported. +
If no configuration has been selected, all configurations and payment methods will be exported. +
If *Transfer flat rate shipping charge* has been selected, only prepayment will be exported as the payment method.

|*VAT note*
|This option does not affect this format.

|*Item availability*
|Activate the *overwrite* option and enter item availabilities into the fields *1* to *10*. The fields represent the IDs of the availabilities. This will overwrite the item availabilities that are saved in the *Setup » Item » Availability* menu.
|====











[#1000]
==== Verfügbare Spalten der Exportdatei

[[spalten-exportdatei]]
.Spalten der Exportdatei
[cols="1,3"]
|====
| Spaltenbezeichnung | Erläuterung

|*article_id*
|*Pflichtfeld* +
Die SKU des Artikels. Bei Artikeln, die für idealo Direktkauf freigegeben wurden, wird hier eine SKU für idealo Direktkauf ausgegeben.

|*deeplink*
|*Pflichtfeld* +
Der URL-Pfad des Artikels abhängig vom gewählten Mandanten in den Formateinstellungen.

|*name*
|*Pflichtfeld* +
Entsprechend der Formateinstellung Artikelname.

|*short_description*
|Entsprechend der Formateinstellung *Vorschautext*.

|*description*
|*Beschränkung*: max. 1000 Zeichen +
Entsprechend der Formateinstellung *Beschreibung*.

|*article_no*
|Die Variantennr. unter *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Einstellungen » Grundeinstellungen*.

|*producer*
|Der Name des Herstellers des Artikels. Der Externe Name unter *Einrichtung » Artikel » Hersteller* wird bevorzugt, wenn vorhanden.

|*model*
|Das Modell unter *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Einstellungen » Grundeinstellungen*.

|*availability*
|*Pflichtfeld* +
Der Name der Artikelverfügbarkeit unter *Einrichtung » Artikel » Verfügbarkeit* oder die Übersetzung gemäß der Formateinstellung *Artikelverfügbarkeit überschreiben*. +
Bei idealo muss die Lieferzeit in Tagen angegeben werden.

|*ean*
|Entsprechend der Formateinstellung *Barcode*.

|*isbn*
|Entsprechend der Formateinstellung *Barcode*.

|*fedas*
|Der Amazon-Produkttyp unter *Artikel » Artikel bearbeiten » Artikel öffnen » Multi-Channel » Amazon*.

|*warranty*
|Aktuell nicht gepflegt.

|*price*
|*Pflichtfeld* +
Der Verkaufspreis der Variante.

|*price_old*
|Der Verkaufspreis vom Typ UVP der Variante, wenn in den Formateinstellungen aktiviert.

|*weight*
|Gewicht brutto in Gramm unter *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Einstellungen » Maße*.

|*category1-6*
|Der Name der Kategorieebene des Kategoriepfads der Standard-Kategorie für den in den Formateinstellungen definierten Mandanten.

|*category_concat*
|Kategoriepfad der Standard-Kategorie für den in den Formateinstellungen definierten Mandanten.

|*image_url_preview*
|URL zu einer für die Vorschau skalierten Version des Bildes gemäß der Formateinstellung *Bild*.

|*image_url*
|*Pflichtfeld* +
URL zu dem Bild gemäß der Formateinstellung *Bild*.

|*base_price*
|Die Grundpreisinformation im Format "Preis / Einheit". (Beispiel: 10,00 EUR / Kilogramm)

|*free_text_field*
|Der Wert eines Merkmals vom Typ Text oder Auswahl mit der Verknüpfung zu idealo.

|*checkoutApproved*
|Wird true gesetzt, wenn entweder die Auftragsherkunft idealo Direktkauf unter *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Verfügbarkeit » Märkte* aktiviert wurde oder ein Merkmal vom Typ *Kein* und der Verknüpfung zum idealo Direktkauf-Merkmal checkoutApproved gesetzt wurde.

|*itemsInStock*
|*Voraussetzung*: checkoutApproved ist true. +
Der Nettowarenbestand der Variante. Bei Artikeln, die nicht auf den Nettowarenbestand beschränkt sind, wird 999 übertragen.

|*fulfillmentType*
|*Voraussetzung*: checkoutApproved ist true. +
Merkmal vom Typ *Kein* und der Verknüpfung zum idealo Direktkauf-Merkmal *FulfillmentType > Spedition*, *FulfillmentType > Paketdienst*, *FulfillmentType > Brief* oder *FulfillmentType > Download*.

|*twoManHandlingPrice*
|*Voraussetzung*: checkoutApproved ist true und fulfillmentType ist Spedition. +
Merkmal vom Typ *Text*, *Auswahl* oder *Kommazahl* und der Verknüpfung zum idealo Direktkauf-Merkmal *twoManHandlingPrice*.

|*disposalPrice*
|*Voraussetzung*: *checkoutApproved* ist *true* und fulfillmentType ist *Spedition*. +
Merkmal vom Typ *Text*, *Auswahl* oder *Kommazahl* und der Verknüpfung zum idealo Direktkauf-Merkmal *disposalPrice*.

|*Zahlungsarten*
|*Pflichtfeld*: (Mindestens eine Zahlungsart) +
Es werden die Zahlungsarten gemäß der Formateinstellung *Versandkosten* in einer eigenen Spalte übermittelt.
|====


[#1100]
== Zahlungsart idealo Direktkauf aktivieren

Damit Zahlungen für Aufträge von idealo Direktkauf durchgeführt und in deinem plentymarkets System angezeigt werden, aktiviere die Zahlungsart *idealo Direktkauf*.

[TIP]
.Zahlungsart nur für idealo Direktkauf
====
Die Zahlungsart *idealo Direktkauf* muss nur aktiviert werden, wenn du idealo Direktkauf nutzt.
====

[.instruction]
idealo-Zahlungsart aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *DE > idealo*.
. Wähle die *idealo-Zahlungsart*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Nimm die gewünschten Einstellungen vor. Beachte dazu die Erläuterungen in <<zahlungsart-idealo>>.
. Setze ein Häkchen bei der Option *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[zahlungsart-idealo]]
.Einstellungen für idealo-Zahlungsart
[cols="1,3"]
|====
| *Einstellung* | *Erläuterung*

|*Sprache*
|Folgende Optionen werden sprachabhängig gespeichert: *Name*, *Infoseite*, *Infoseite (Intern)*, *Logo* und *Logo hochladen*. Damit hast du die Möglichkeit, die Werte für diese Optionen in mehreren Sprachen einzugeben. Die Werte einer Sprache werden aktiviert, wenn ein Käufer im Webshop die Sprache wählt.

|*Name*
|Name eintragen, der im Webshop und auf Rechnungen etc. angezeigt werden soll.

|*Infoseite*
|Als Information zur Zahlungsart eine Kategorieseite vom Typ *Content* oder die URL einer Webseite eintragen.

|*Infoseite (Extern)*
|Wenn unter *Infoseite* die Einstellung *Infoseite (Extern)* gewählt wurde, hier die URL der Infoseite eintragen.

|*Lieferländer*
|Kein Lieferland wählen. +
Du kannst die Zahlungsart nicht in deinem Webshop verwenden. Deshalb wird diese Zahlungsart in plentymarkets nur aktiviert, aber nicht vollständig eingerichtet.

|*Logo*
|Eine der folgenden Optionen für die Anzeige eines Logos wählen: +
*Standard-Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird angezeigt. +
*Kein Logo anzeigen* = Das in plentymarkets für die Zahlungsart eingestellte Logo wird nicht angezeigt. +
*Upload-Logo anzeigen* = Blendet die Optionen *Logoansicht* und *Logo hochladen* ein.

|*Logoansicht*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, wird das hochgeladene Logo hier angezeigt.

|*Logo hochladen*
|Wenn unter *Logo* die Option *Upload-Logo anzeigen* gewählt wurde, hier ein externes Logo hochladen. +
Auf *Dateien hochladen* klicken und das Logo wählen, das für die Zahlungsart hochgeladen werden soll. Erlaubte Datenformate: GIF, PNG und JPG.

|*Priorität*
|Priorität für die Anzeige der Zahlungsart im Webshop wählen.

|*Kosten: Pauschal oder Prozentual*
|Wenn bei der Zahlungsart zusätzliche Kosten berechnet werden, den Prozentwert oder Pauschalwert gemäß der Vertragskonditionen eintragen. *Wichtig:* Nicht in beide Felder einen Wert eintragen. +
Weitere Informationen findest du auf der Handbuchseite <<basics/arbeiten-mit-plentymarkets/statistik/statistiken-verwalten#, Statistiken verwalten>>. Ein Beispiel für pauschale und prozentuale Kosten findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#20, Zahlungsarten verwalten>>.
|====

[TIP]
.Zahlungsart in Kundenklasse erlauben
====
Im Menü *Einrichtung » CRM » Kundenklassen* aktivierst oder deaktivierst du erlaubte Zahlungsarten. +
Weitere Informationen findest du im Kapitel <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.

[IMPORTANT]
.Zahlungsart PayPal
====
Wenn du PayPal als Zahlungsart anbietest, muss die Zahlungsart PayPal zwingend in deinem plentymarkets System hinterlegt und eingerichtet sein, damit die Zahlung korrekt importiert und dem Auftrag zugeordnet werden kann.
====


[#1200]
== Merkmale erstellen

Mit <<artikel/einstellungen/eigenschaften#100, Merkmalen>> verknüpfst du bestimmte Eigenschaften, die du für die Einrichtung des Marktplatzes idealo Direktkauf benötigst, mit deinen Artikeln. Mit Merkmalen überträgst du Artikeleigenschaften, Versandarten und Gebühren an idealo Direktkauf.

[NOTE]
.Bestimmte Merkmale können nur mit Plugin-Version 2.0 verwendet werden
====
Die Merkmale *DeliveryComment*, *DepositFee*, *DisposalPrice*, *EnergyClass*, *FreeReturnDays*, *Gender*, *Material* und *Replica* können nur verwendet werden, wenn die Plugin-Version 2.0 in deinem plentymarkets System installiert ist. Außerdem können diese Merkmale nur in Verbindung mit dem automatischen Artikelexport (Datenübertragung per Schnittstelle) zu idealo Direktkauf übertragen werden. Den automatischen Artikelexport aktivierst du im idealo-Assistenten im Schritt *Automatische Datenübertragung*. +
Wenn du den automatischen Artikelexport im idealo-Assistenten aktiviert hast, kannst du alle idealo-Merkmale übertragen. +
Wenn du deine Artikel per CSV-Datei mit dem elastischen Export überträgst, kannst du nur das Merkmal *FulfillmentType* verwenden.
====

[#1250]
=== Merkmal für Material und Zielgruppe/Geschlecht erstellen

Mit den Merkmalen Material und Gender überträgst du Informationen zu Material und Zielgruppe bzw. Geschlecht an idealo Direktkauf.

Im Folgenden wird beschrieben, wie du das Merkmal *Material* erstellst. Erstelle das Merkmal *Gender* auf die gleiche Weise, wähle jedoch den Merkmaltyp *Text*.

[.instruction]
Merkmal für Material einrichten:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *Material*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[#1300]
=== Merkmal für Versandarten erstellen

Wenn du idealo Direktkauf nutzt, findet der Verkauf direkt bei idealo statt und du musst Informationen zur Versandart an idealo Direktkauf übergeben. Versendest du deine Artikel mit einem Paketdienst, einer Spedition, per Brief oder Download, wird diese Pflichtinformation mit einem Merkmal angegeben und an idealo Direktkauf übergeben. Bei der Versandart *Spedition* wird beim Verkauf des Artikels die Telefonnummer des Käufers zur Abstimmung eines Liefertermins mit dem beauftragten Speditionsunternehmen erfragt.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *FulfillmentType* anzulegen, mit dem du angibst, ob du die Versandart *Spedition*, *Paketdienst*, *Brief* oder *Download* verwendest.

[.instruction]
Merkmal für Versandart erstellen:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *FulfillmentType*. +
→ Eine Dropdown-Liste erscheint.
. Wähle je nach Versandart einen Wert aus der Dropdown-Liste. Die Werte *Spedition*, *Paketdienst*, *Brief* und *Download* sind verfügbar.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[.subhead]
Weitere Merkmale für Versandarten

Für Artikel mit der Versandart *Spedition* kann die zusätzliche Dienstleistung *Zwei-Mann-Lieferung bis zum Aufstellort* und *Altgeräteabholung* als Merkmal an idealo Direktkauf übergeben werden. Die Altgeräteabholung kann nur in Kombination mit der Zwei-Mann-Lieferung übergeben werden. Das heißt, du musst sowohl das Merkmal *Zwei-Mann-Lieferung (twoManHandlingPrice)* als auch das Merkmal *Altgeräteabholung (DisposalPrice)* anlegen und beide mit dem Artikel verknüpfen. Wähle in beiden Fällen als Merkmaltyp *Kommazahl*. Gib den Aufpreis am Artikel für die zusätzliche Dienstleistung mit zwei Dezimalstellen und mit Punkt als Dezimaltrenner (19.99) im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* ein.

[#1350]
=== Merkmal für Kommentar zur Lieferung erstellen

Mit dem Merkmal *DeliveryComment* werden weitere Informationen zur Lieferung übermittelt.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *DeliveryComment* zu erstellen.

[.instruction]
Merkmal für Kommentar zur Lieferung erstellen:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *Text* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *DeliveryComment*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[#1400]
=== Merkmal für Energieeffizienzklasse erstellen

Mit dem Merkmal *EnergyClass* überträgst du Informationen zur Energieeffizienzklasse an idealo Direktkauf.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *EnergyClass* zu erstellen.

[.instruction]
Merkmal für Energieeffizienzklasse einrichten:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *EnergyClass*. +
→ Eine Dropdown-Liste erscheint.
. Wähle je nach Energieeffizienzklasse einen Wert aus der Dropdown-Liste.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[#1450]
=== Merkmal für kostenlose Rückgabe erstellen

Mit dem Merkmal *FreeReturnDays* überträgst du Informationen zur kostenlosen Rückgabefrist, d.h. die Frist, innerhalb der ein Artikel kostenlos zurückgegeben werden kann, an idealo Direktkauf.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *FreeReturnDays* zu erstellen.

[.instruction]
Merkmal für kostenlose Rückgabefrist einrichten:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *ganze Zahl* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *FreeReturnDays*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst anschließend das Merkmal mit dem Artikel.

[#1500]
=== Merkmal für Pfand erstellen

Mit dem Merkmal *DepositFee* überträgst du Informationen zum Pfand an idealo Direktkauf. Dieses Merkmal wird benötigt, wenn für einen Artikel Pfand gezahlt werden muss.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *DepositFee* zu erstellen.

[.instruction]
Merkmal für Pfand einrichten:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *Kommazahl* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *DepositFee*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.

[#1550]
=== Merkmal für Replika erstellen

Mit dem Merkmal *Replica* gibst du an, ob es sich bei dem Artikel um eine Replika handelt.

Gehe wie im Folgenden beschrieben vor, um das Merkmal *Replica* zu erstellen.

[.instruction]
Merkmal für Replika einrichten:

. Öffne das Menü *Einrichtung » Artikel » Merkmale » Tab: Neues Merkmal*.
. Gib den *Namen (intern)* ein.
. Wähle als Merkmaltyp *kein* aus der Dropdown-Liste.
. Wähle bei *idealo Direktkauf-Merkmal* das Merkmal *Replica*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Im Menü *Artikel » Artikel bearbeiten » Artikel öffnen » Variante öffnen » Tab: Merkmale* verknüpfst du anschließend das Merkmal mit dem Artikel.


[#1600]
== Ereignisaktionen einrichten

Richte Ereignisaktionen ein, um Änderungen am Auftragsstatus automatisch an idealo zu senden. Du kannst mit Ereignisaktionen Auftragsbestätigungen, Versandbestätigungen, Retouren und Stornierungen automatisch an idealo Direktkauf senden.

[TIP]
.Ereignisaktionen für idealo Direktkauf
====
Ereignisaktionen müssen nur eingerichtet werden, wenn du idealo Direktkauf nutzt.
====

[#1650]
=== Auftragsbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um nach Eingang eines Auftrags automatisch eine Auftragsbestätigung an idealo zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<auftragsbestaetigung-idealo>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<auftragsbestaetigung-idealo>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[auftragsbestaetigung-idealo]]
.Ereignisaktion zum automatischen Senden von Auftragsbestätigungen an idealo
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neuer Auftrag*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Auftrag &gt; Auftragsbestätigung an idealo senden*
|
|====

[#1700]
=== Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um automatisch eine Versandbestätigung an idealo zu senden, nachdem ein Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<versandbestaetigung-idealo>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<versandbestaetigung-idealo>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[versandbestaetigung-idealo]]
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an idealo
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Versand > Versandbestätigung an idealo senden*
|
|====

[#1750]
=== Retouren automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um idealo automatisch über Retouren zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<retouren-idealo>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<retouren-idealo>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[retouren-idealo]]
.Ereignisaktion zum automatischen Senden von Retouren an idealo
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Retoure > Retoure an idealo senden*
|
|====

[#1800]
=== Stornierungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um idealo automatisch über Stornierungen zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]). +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß <<stornierungen-idealo>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Das Ereignis wird erstellt.
. Nimm die weiteren Einstellungen gemäß <<stornierungen-idealo>> vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Ereignisaktion wird gespeichert.
--

[[stornierungen-idealo]]
.Ereignisaktion zum automatischen Senden von Stornierungen an idealo
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Statuswechsel: [8] Storniert*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Herkunft*
|*idealo Direktkauf*

|*Aktion*
|*Auftrag: Stornierung an idealo senden*
|
|====


[#1900]
== API-Log abrufen

Im Menü *Daten » API-Log* findest du eine Historie über Vorgänge, die über die idealo-Schnittstelle ausgeführt wurden. Das Format idealoDirektkauf steht dir für idealo zur Verfügung.

[.instruction]
API-Log abrufen:

. Öffne das Menü *Daten » API-Log » Tab: API-Log*.
. Wähle das Format *idealoDirektkauf* aus der Dropdown-Liste *Vorgang*.
. Wähle ggf. ein Datum, um nur Einträge eines bestimmten Tages zu erhalten.
. Wähle die Anzahl der Ergebnisse pro Seite.
. Klicke auf *Suchen* (icon:search[role="blue"]), um die Ergebnisse anzuzeigen.
