= Setting up idealo
:lang: de
include::{includedir}/_header.adoc[]
:keywords: idealo, idealo.de, idealo Direktkauf, idealo Checkout, idealo setup, setting up idealo, market, marketplace, price comparison, idealo price comparison, CSV file, CSV export, elastic export, idealo plugin, checkoutApproved
:description: Multi-Channel in plentymarkets: Set up the interface to the market idealo Checkout in your plentymarkets system.
:position: 10
:url: markets/idealo-checkout/idealo-setup
:id: JFWN4QY
:author: team-multi-channel

On this page, you will find information about the settings you need to carry out in order to set up the market and price comparison portal idealo Checkout in plentymarkets. Learn how to set up the interface, how to export items to idealo Checkout and how to define sales prices. +

[discrete]
===== About idealo

idealo started business in 2000 with the vision of helping users to make the right choices when buying products online and, now counting 50,000 sellers and 18 million users per month, has become one of Germany's most important e-commerce websites. +

With idealo Checkout, idealo offers a strong sales channel. The "Zum Kauf" (Buy now) button allows users to order a product directly on idealo.de, using a fully integrated checkout function. The sellers remain the contractual partners and take care of fulfilment as usual.

[discrete]
===== idealo price comparison and idealo Checkout

With plentymarkets, you can both use the idealo price comparison and idealo Checkout (idealo's checkout function). If you set up idealo Checkout, you enable your customers to buy your products directly at idealo without having to enter your online store.


[#100]
== Registering with idealo

You have to register as a seller with idealo to set up the market in plentymarkets.

[IMPORTANT]
.Item data export
====
Inform idealo about how item data should be transferred before setting up idealo in plentymarkets (creating, updating, and deleting items on idealo). Item data can either be exported with a CSV file or via API (PWS 2.0 interface). +
If you export your items with PWS 2.0, items will be created on idealo once a day. Prices and stock are updated every 15 minutes. Items can also be deleted every 15 minutes. +
If you export your items with a CSV file using the elastic export, your items can be retrieved by idealo via URL. +
How to set up the different methods of data transfer in plentymarkets is described in the chapter <<Setting up the item export, Setting up the item export>>.
====

[IMPORTANT]
.Contact idealo if you transfer your items via API
====
If you would like to export your items to idealo via API (PWS 2.0 interface), first contact idealo at tam@idealo.de to receive your access data.
====

[#150]
=== Installing the idealo plugin

In order to use the idealo, you have to install the link:https://marketplace.plentymarkets.com/en/plugins/sales/preisportale/elasticexportidealode_4723[ElasticExportIdealoDE plugin^] in your plentymarkets system first. You can download the plugin in the link:https://marketplace.plentymarkets.com/en[plentyMarketplace^]{nbsp}icon:external-link[].

[#175]
=== Installing the Elastic Export plugin

In order to use the idealo plugin, you have to install the link:https://marketplace.plentymarkets.com/en/plugins/sales/marktplaetze/elasticexport_4763[Elastic Export plugin^] first. You can download the plugin in the link:https://marketplace.plentymarkets.com/en[plentyMarketplace^]{nbsp}icon:external-link[].


[#200]
== Going through the idealo assistant

Go through the *idealo Basic settings* assistant in the *Setup » Assistants » Omni-Channel* menu to carry out the basic settings for idealo in plentymarkets. With this assistant, you set up your idealo account in plentymarkets and carry out settings for the item data export to idealo and order import from idealo Checkout. +

[IMPORTANT]
.Item data export via API
====
It is mandatory to go through the *idealo Basic settings* assistant if you export your items to idealo with PWS 2.0. The automatic item export can only be set up in this assistant.
====


[#300]
== idealo price comparison and idealo Checkout

Depending on whether you only want to use the idealo price comparison or whether you want to enable your customers to buy items directly at idealo without having to enter your online store, different settings must be carried out. The overview below lists the settings required for idealo Checkout.

*Settings for idealo Checkout:*

- *Basic settings:* Go through the *idealo Basic settings* assistant in the *Setup » Assistants » Omni-Channel* menu.
- *Item export:* Set up the <<Item export via API (PWS 2.0 interface), automatic item export>> or the <<Item export with elastic export, item export via CSV file>>, depending on how you want to export your items to idealo.
- *Order referrer:* In addition to the order referrer *idealo*, also activate the <<Activating the order referrer, order referrer>> *idealo Checkout* in the *Setup » Orders » Order referrer* menu.
- *Item availability:* In addition to the option *idealo*, also activate the <<Setting the variation availability, availability>> *idealo Checkout* in the *Item » Edit item »* _Open item_ *» Tab: Variation ID » Tab: Availability* menu in the *Markets* area.
- *Sales price:* Set up a <<Defining a sales price, sales price>>.
- *SKU:* Add <<Defining SKU manually, SKUs>> if needed.
- *Payment method:* Activate the <<Activating the payment method idealo Direktkauf, payment method>> *idealo Direktkauf*.
- *Characteristics:* Create <<Creating characteristics, characteristics>> for idealo Checkout. With characteristics, you can transfer item properties, shipping methods, and charges to idealo Checkout.
- *Event procedures:* Set up <<Setting up event procedures, event procedures>> to automatically inform idealo Checkout about changes in the order status.


[#400]
== Activating the order referrer

In order to link items, characteristics etc. with the idealo price comparison portal, you have to activate the idealo order referrer in the *Setup » Orders » Order referrer* menu.

[.instruction]
Activating the order referrer for the idealo price comparison:

. Go to *Setup » Orders » Order referrer*.
. Activate the referrer *idealo*.
. *Save* (icon:save[role="green"]) the settings.

If you would like to use idealo Checkout, then also activate the order referrer *idealo Checkout*. If you activate the order referrer *idealo Checkout*, then the column *checkout_approved* in the CSV file that is generated in the elastic export is set to *true*.


[#500]
== Setting the variation availability

You need to activate all variations that you want to sell on idealo. This is done in the *Availability* tab of a variation within the *Item » Edit item »* _Open item_ *» Tab: Variation ID* menu.

[TIP]
.Selling all variations of an item on idealo
====
If you want to sell all variations of an item on idealo, carry out the settings below for the item's main variation. All other variations of the item then inherit the settings of the main variation.
====

[.instruction]
Activating the variation availability for idealo:

. Go to *Item » Edit item »* _Open item_ *» Tab: Variation ID » Tab: Settings*.
. Open the variation that you want to sell on idealo.
. In the *Availability* area, active the option *Active*.
. Click on the *Availability* tab.
. In the *Markets* area, click in the selection field.  +
→ A list of all available markets is displayed.
. Activate the option *idealo*.
. Activate the option *Web API*.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The market is added.
. *Save* (icon:save[role="green"]) the settings. +
*_Note:_* If you want to use idealo Checkout, also activate the option *idealo Checkout* in the *Markets* area.


[#600]
== Defining a sales price

Proceed as described below to define a sales price for the order referrer idealo. This price is displayed on idealo. It is valid for the idealo price comparison and idealo Checkout.

[.instruction]
Defining a sales price for idealo:

. Go to *Setup » Item » Sales prices »* _Open sales price_ *» Tab: Settings*. +
→ If you have not yet created a sales price, click on *New* to create a sales price.
. Activate the referrer *idealo*.
. *Save* (icon:save[role="green"]) the settings.

[TIP]
.Minimum price
====
If you want to use a minimum price for the "price range" feature for idealo, then you have to define at least two sales prices for idealo: a minimum price and a standard sales price. The minimum price must have the price type *Special offer* and must be linked to the referrer *idealo Direktkauf*. +
Which price should be transferred to idealo as minimum price is defined with the setting *Which price would you like to transfer to idealo as minimum price?* in the *Item data* step of the idealo assistant. +
The "price range" feature must also be activated at idealo.
====


[#700]
== Defining SKU manually

:referrer-sku: idealo

include::../_textblocks/instructions/sku-manually.adoc[]

If you want to use idealo Checkout, also add SKUs with the referrer *idealo Direktkauf*.


[#800]
== Setting up the item export

Items can be transferred to idealo with the automatic item export via API (PWS 2.0 interface) or via a CSV file with the elastic export. Depending on how you want to transfer your items to idealo, different settings are required. +

[IMPORTANT]
.Data transfer to idealo
====
Inform idealo about how item data should be transferred before the setup in plentymarkets.
====

Information about the different types of data transfer is available in <<#item-export-idealo>>.

[[item-export-idealo]]
.idealo data transfer
[cols="1,1"]
|====
| Item export via API (PWS 2.0) | Item export via elastic export

|Item data export via interface
|Item data export via CSV file

|Items are created once a day
|Retrieval of item data via URL that is saved at idealo

|Price updates every 15 minutes
|Time interval for retrieval of item data is defined by idealo

|Stock updates every 15 minutes
|
|====

[#850]
=== Item export via API (PWS 2.0 interface)

If you want to transfer your items to idealo via API, go through the *idealo Basic settings* assistant in the *Setup » Assistants » Omni-Channel* menu and activate the automatic item data export. Apart from the assistant, no further settings are required to set up the automatic item export in plentymarkets. +

If you transfer your items via API, items will be created at idealo once per day. Prices and stock will be updated every 15 minutes. Items can also be deleted every 15 minutes.


[#900]
=== Item export with elastic export


If you export items via the elastic export, you have to carry out a few settings in the *Data » Elastic export* menu to set up the export format. In order to use the elastic export, the link:https://marketplace.plentymarkets.com/en/plugins/sales/marktplaetze/elasticexport_4763[Elastic Export^]{nbsp}icon:external-link[] plugin must be installed in your plentymarkets system. First create the data format IdealoDE and afterwards transfer the URL to idealo so that idealo will be able to retrieve your item data.

How to set up the elastic export to export your items to idealo is described in the following chapters <<Setting up the data format IdealoDE plugin in plentymarkets, Setting up the data format IdealoDE plugin in plentymarkets>> and <<Available columns for the export file, Available columns for the export file>>.

[#950]
==== Setting up the data format IdealoDE plugin in plentymarkets

[TIP]
.Settings only for elastic export
====
The settings described in this chapter only need to be carried out if you transfer your items to idealo with the elastic export.
====

[TIP]
.Check idealo product CSV
====
Not all of the columns of idealo's product CSV are available in plentymarkets at present. Check whether you need columns which are not yet available in plentymarkets prior to setting up idealo in plentymarkets. In this case, an integration of idealo is currently not possible. +
An overview of the columns which are available in plentymarkets can be found in the <<Available columns for the export file, Available columns for the export file>> chapter.
====

Set up the export format *IdealoDE* so that your items can be exported to idealo with the elastic export. For further information about the elastic export, refer to the <<data/exporting-data/elastic-export#, Elastic Export>> page. It is required to install the *Elastic export* plugin from the plentyMarketplace first before you can use the format *IdealoDE* for the elastic export.

[.instruction]
Creating a new export format:

. Go to *Data » Elastic export*.
. Click on *New export*.
. Carry out the settings as desired. Pay attention to the explanations given in <<#format-settings-idealo>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The export format is given an ID and it appears in the overview within the *Exports* tab.

The following table lists details for settings, format settings and recommended item filters for the format *IdealoDE plugin*.

[[format-settings-idealo]]
.Format settings for IdealoDE
[cols="1,3"]
|====
| *Setting*  | *Explanation*

2+| *Settings*

| *Name*
|Enter a name. The export format will be listed under this name in the overview within the *Exports* tab.

| *Type*
|Select the type *Item* from the drop-down list.

| *Format*
|Select *IdealoDE-Plugin*.

| *Limit*
|Enter a number. If you want to transfer more than 9,999 data records to the price search engine, then the output file will not be generated again for another 24 hours. This is to save resources. If more than 9,999 data records are necessary, the setting *Generate cache file* has to be active. +
*_Or:_* If you want to transfer more than 9,999 data records to idealo, you can also install version 2.0 of the idealo plugin.

| *Generate cache file*
|Activate if you want to transfer more than 9,999 data records to the price search engine. The output file will not be generated again for another 24 hours. We recommend not to activate this setting for more than 20 export formats. This is to save resources.

| *Provisioning*
|Select *URL*.

| *File name*
|The file name must have the ending *.csv* or *.txt* for idealo.de to be able to import the file successfully.

| *Token, URL*
|If you have selected the option *URL* under *Provisioning*, then click on *Generate token*. The token will be entered automatically. When the token is generated under *Token*, the URL is entered automatically.

2+| *Item filters*

| *Add item filters*
|Select an item filter from the drop-down list and click on *Add*. There are no filters set in default. It is possible to add multiple item filters from the drop-down list one after the other. +
*Variations* = Select *Transfer all* or *Only transfer main variations*. +
*Markets* = Select *idealo*. +
The availability for all markets selected here has to be saved for the item. Otherwise, the export will not take place. +
*Currency* = Select a currency. +
*Category* = Activate to transfer the item with its category link. Only items belonging to this category will be exported. +
*Image* = Activate to transfer the item with its image. Only items with images will be transferred. +
*Client* = Select client. +
*Stock* = Select which stocks you want to export. +
*Flag 1 - 2* = Select the flag. +
*Manufacturer* = Select one, several or *ALL* manufacturers. +
*Active* = Only active variations will be exported.

2+| *Format settings*

| *Product URL*
|Choose wich URL should be transferred to the price comparison portal, the item’s URL or the variation’s URL. Variation SKUs can only be transferred in combination with the Ceres store.

| *Client*
|Select a client. This setting is used for the URL structure.

| *URL parameter*
|Enter a suffix for the product URL if this is required for the export. If you have activated the transfer option for the product URL further up, then this character string will be added to the product URL.

| *Order referrer*
|Choose the order referrer *idealo*. The selected referrer is added to the product URL so that sales can be analysed later.

| *Marketplace account*
|Select the marketplace account from the drop-down list.

| *Language*
|Select the language from the drop-down list.

| *Item name*
|Select *Name 1*, *Name 2* or *Name 3*. These names are saved in the *Texts* tab of the item. Enter a number into the *Maximum number of characters (def. Text)* field if desired. This specifies how many characters should be exported for the item name.

| *Preview text*
|Select the text that you want to transfer as preview text. +
Enter a number into the *Maximum number of characters (def. text)* field if desired. This will specify how many characters should be exported for the item name. +
Activate the option *Remove HTML tags* if you want HTML tags to be removed during the export. +
If you only want to allow specific HTML tags to be exported, then enter these tags into the field *Permitted HTML tags, separated by comma (def. Text)*. Use commas to separate multiple tags.

| *Description*
|Select the text that you want to transfer as description. +
Enter a number into the *Maximum number of characters (def. text)* field if desired. This specifies how many characters should be exported for the description. +
Activate the option *Remove HTML tags* if you want HTML tags to be removed during the export. If you only want to allow specific HTML tags to be exported, then enter these tags into the field *Permitted HTML tags, separated by comma (def. Text)*. Use commas to separate multiple tags.

| *Target country*
|Select the target country from the drop-down list.

| *Barcode*
|Select the ASIN, ISBN or an EAN from the drop-down list. The barcode has to be linked to the order referrer selected above. If the barcode is not linked to the order referrer it will not be exported.

| *Image*
|Select *Position 0* or *First image* to export this image. +
*Position 0* = An image with position 0 will be transferred. +
*First image* = The first image will be transferred.

| *Image position of the energy efficiency label*
|Enter the position. Every image that should be transferred as an energy efficiency label must have this position.

| *Stock buffer*
|The stock buffer for variations with the limitation to the net stock.

| *Stock for variations without stock limitation*
|The stock for variations without stock limitation.

| *Stock for variations with no stock administration*
|The stock for variations without stock administration.

| *Live currency conversion*
|Activate this option to convert the price into the currency of the selected country of delivery. The price has to be released for the corresponding currency.

| *Retail price*
|Select gross price or net price from the drop-down list.

| *Offer price*
|This option does not affect this format.

| *RRP*
|Activate to transfer the RRP.

| *Shipping costs*
|The chosen payment method does not affect this format. All payment methods of the selected configuration will be exported. +
If no configuration has been selected, all configurations and payment methods will be exported. +
If *Transfer flat rate shipping charge* has been selected, only prepayment will be exported as the payment method.

| *VAT note*
|This option does not affect this format.

| *Item availability*
|Activate the *overwrite* option and enter item availabilities into the fields *1* to *10*. The fields represent the IDs of the availabilities. This will overwrite the item availabilities that are saved in the *Setup » Item » Availability* menu.
|====


[#1000]
==== Available columns for the export file

[[columns-export-file]]
.Columns of the export file
[cols="1,3"]
|====
| Column description | Explanation

| *article_id*
| *Required* +
The SKU of the item. For all items which are configured for idealo Checkout, a SKU will be generated for idealo Checkout.

| *deeplink*
| *Required* +
The URL of the item depending on the selected client in the format settings.

| *name*
| *Required* +
According to the format setting *Item name*.

| *short_description*
|According to the format setting *Item name*.

| *description*
| *Limitation*: max. 1000 characters +
According to the format setting *Description*.

| *article_no*
|The *Variation number* within *Item » Edit item »* _Open item_ *»* _Open variation_ *» Settings » Basic settings*.

| *producer*
|The *Name of the manufacturer* of the item. The *external name* within *Setup » Item » Manufacturer* will be preferred, if existing.

| *model*
|The *Model* within *Items » Edit items »* _Open item_ *»* _Open variation_ *» Settings » Basic settings*.

| *availability*
| *Required* +
The *Name of the item availability* within *Setup » Item » Item availability* or the translation according to the format setting *Overwrite item availability*. +
For idealo, the delivery time must be indicated in days.

| *ean*
|According to the format setting *Barcode*.

| *isbn*
|According to the format setting *Barcode*.

| *fedas*
|The *Amazon product type* within *Items » Edit item »* _Open item_ *» Multi-Channel » Amazon*.

| *warranty*
|Currently not configured.

| *price*
| *Required* +
The sales price of the variation.

| *price_old*
|The sales price of type RRP of the variation, if activated in the format settings.

| *weight*
|The gross weight in gram within *Items » Edit item »* _Open item_ *»* _Open variation_ *» Settings » Measurements*.

| *category1-6*
|The name of the category level of the category path of the default category for the client which is configured in the format settings.

| *category_concat*
|The category path of the default category for the client which is configured in the format settings.

| *image_url_preview*
|The URL for the image which is scaled for preview according to the format setting *Image*.

| *image_url*
| *Required* +
The URL of the image according to the format setting *Image*.

| *base_price*
|The base price information in the format "price / unit". (e.g.: 10,00 EUR / kilogram)

| *free_text_field*
|The value of a characteristic of type *Text* or *Selection* with a link to idealo.

| *checkoutApproved*
|Is *true* if the order referrer *idealo Direktkauf* within *Items » Edit item »* _Open item_ *»* _Open variation_ *» Availability » Markets* is set or a characteristic of type *No* and the link to the idealo Checkout characteristic *CheckoutApproved* is configured.

| *itemsInStock*
| *Requirement*: checkoutApproved is true. +
The net stock of the variation. For items which are not limited to the net stock, *999* will be exported.

| *fulfillmentType*
| *Requirement*: checkoutApproved is true. +
Characteristic of type *No* with link to one of the options for the idealo Checkout characteristic *FulfillmentType > Spedition*, *FulfillmentType > Paketdienst*, *FulfillmentType > Brief* or *FulfillmentType > Download*.

| *twoManHandlingPrice*
| *Requirement*: checkoutApproved is true and fulfillmentType is "Spedition". +
Characteristic of type *Text*, *Selection* or *float* and the link to the idealo Checkout characteristic *twoManHandlingPrice*.

| *disposalPrice*
| *Requirement*: checkoutApproved is true and fulfillmentType is "Spedition". +
Characteristic of type *Text*, *Selection* or *float* and the link to the idealo Checkout property *disposalPrice*.

| *Zahlungsarten*
| *Required*: (at least one payment method) +
All payment methods will be exported, according to the format setting *Shipping costs* in their own column.
|====


[#1100]
== Activating the idealo payment method

Activate the payment method *idealo Checkout*. This allows payments to be made for orders on idealo and to be displayed in your plentymarkets system.

[TIP]
.Payment method for idealo Checkout
====
You only have to activate the payment method *idealo Checkout* if you use idealo Checkout.
====

[.instruction]
Activating the idealo payment method:

. Go to *Setup » Orders » Payment » Methods*.
. Activate the option *Also show inactive*.
. Open the folder *DE > idealo Checkout*.
. Select the idealo payment method. +
→ The *Settings* tab opens.
. Carry out the settings as desired. Pay attention to the explanations given in <<#payment-method-idealo>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings.

[[payment-method-idealo]]
.Settings for the idealo payment method
[cols="1,3"]
|====
| *Setting* | *Explanation*

| *Language*
|The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo*, and *Upload logo*. This enables you to enter values for these options in various languages. The values for a language are activated as soon as a buyer selects the language in the online store.

| *Name*
|Enter the name that should be displayed in the online store and on invoices etc.

| *Info page*
|Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

| *Info page (external)*
|If you selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

| *Countries of delivery*
|Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely set up.

| *Logo*
|Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

| *Logo view*
|If *Show upload logo* was selected from the *Logo* drop-down list, then the logo that was uploaded is displayed here.

| *Upload logo*
|If *Show upload logo* was selected from the *Logo* drop-down list, then upload an external logo here. +
Click on *Upload files* and select the logo that you want to upload for the payment method. Permitted data formats: GIF, PNG, and JPG.

| *Priority*
|Select the priority for displaying the payment method in the online store.

| *Costs: Flat rate or percentage*
|If the payment method results in additional costs, enter the percentage value or flat rate value. The choice depends on the conditions of your contract. *_Important:_* Do not enter a value into both fields. +
For further information, refer to the <<business-decisions/business-intelligence/statistics#, Managing statistics>> page. For an example of flat rate and percentage costs, refer to the <<payment/managing-payment-methods#20, Managing payment methods>> page.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *Setup » CRM » Classes* to activate or deactivate permitted payment methods. +
For further information, refer to the <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter.
====

For further information, refer to the <<payment/managing-payment-methods#, Managing payment methods>> page.

[IMPORTANT]
.PayPal payment method
====
If you offer the PayPal payment method, it is mandatory to create and configure this payment method in your plentymarkets system. This is to ensure that the payment is imported correctly and assigned to the order.
====


[#1200]
== Creating characteristics

Use <<item/settings/properties#100, characteristics>> to link specific characteristics to your items which are required to set up idealo Checkout. Item properties, shipping methods and fees are transferred to idealo Checkout with characteristics.

[NOTE]
.Characteristics can only be used with the idealo plugin version 2.0
====
The characteristics *DeliveryComment*, *DepositFee*, *DisposalPrice*, *EnergyClass*, *FreeReturnDays*, *Gender*, *Material*, and *Replica* can only be used if the idealo plugin version 2.0 is installed in your plentymarkets system. These characteristics can only be exported to idealo Checkout if you activate the automatic item export (data export via interface). The automatic item export is activated in the *Automatic data transfer* step of the idealo assistant. +
If the automatic item export is activated, you can export all idealo characteristics. +
If you transfer your items with via CSV file with the elastic export, you can only use the characteristic *FulfillmentType*.
====

[#1250]
=== Creating the characteristics material and gender

Use the characteristics *Material* and *Gender* to transfer information about material and target group or gender to idealo Checkout.

Proceed as described below to create the characteristic *Material*. Create the *Gender* characteristic in the same way, but select the type *Text* instead.

[.instruction]
Creating a characteristic for material:

. Go to *Setup » Item » Characteristics » Tab: New characteristic*.
. Enter the *Name (internal)*.
. Select *No* from the characteristic type drop-down list.
. Select the characteristic *Material* for *idealo Direktkauf property*.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the characteristic to the item in the *Item » Edit item »* _Open item_ *»* _Open variation_ *» Tab: Characteristics* menu.

[#1300]
=== Creating characteristics for shipping methods

With idealo Checkout, the customer buys the items directly at idealo and you have to send shipping information to idealo Checkout. If you ship your items with a parcel service, a shipping company, via letter or via download, this mandatory information is transferred to idealo with a characteristic. If the order is carried out by a shipping company, the customer has to enter their phone number during the order process in order to arrange a delivery date.

Proceed as described below to create the characteristic *FulfillmentType*. This characteristic indicates whether you use the shipping method *shipping company*, *parcel service*, *letter*, or *download*.

[.instruction]
Creating a characteristic for the shipping method:

. Go to *Setup » Item » Characteristics » Tab: New characteristic*.
. Enter the *Name (internal)*.
. Select *No* from the characteristic type drop-down list.
. Select the characteristic *FulfillmentType* for *idealo Direktkauf property*. +
→ A drop-down list is shown.
. Select a value from the drop-down list, depending on the shipping type. The values *Spedition* (shipping company), *Paketdienst* (parcel service), *Brief* (letter), and *Download* (download) are available.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the characteristic to the item in the *Item » Edit item »* _Open item_ *»* _Open variation_ *» Tab: Characteristics* menu.

[discrete]
===== Further characteristics for shipping methods

For items which have the shipping method *shipping company*, it is also possible to transfer the additional services *TwoManHandlingPrice* and *DisposalPrice* to idealo Checkout. DisposalPrice can only be used in combination with *TwoManHandlingPrice*. That means you have to create the characteristic *TwoManHandlingPrice* as well as the property *DisposalPrice* and link them to the item. In both cases, select *decimal number* as the characteristic type. Go to *Item » Edit item »* _Open item_ *»* _Open variation_ *» Tab: Properties* and enter the surcharge for the additional service with two decimal places behind the decimal separator. Use a period for the decimal separator (19.99).

[#1350]
=== Creating a characteristic for delivery comments

Use the characteristic *DeliveryComment* to transfer further information about the delivery.

Proceed as described below to create the characteristic *DeliveryComment*.

[.instruction]
Creating a characteristic to specify further information about the delivery:

. Go to *Setup » Item » Characteristics » Tab: New characteristic*.
. Enter the *Name (internal)*.
. Select *Text* from the characteristic type drop-down list.
. Select the characteristic *DeliveryComment* for *idealo Direktkauf property*.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the characteristic to the item in the *Item » Edit item »* _Open item_ *»* _Open variation_ *» Tab: Characteristics* menu.

[#1400]
=== Creating the characteristic energy efficiency class

Use the characteristic *EnergyClass* to transfer information about the energy efficiency class to idealo Checkout.

Proceed as described below to create the characteristic *EnergyClass*.

[.instruction]
Creating a characteristic for the energy efficiency class:

. Go to *Setup » Item » Characteristics » Tab: New characteristic*.
. Enter the *Name (internal)*.
. Select the characteristic type *No* from the characteristic type drop-down list.
. Select the characteristic *EnergyClass* for *idealo Direktkauf property*. +
→ A drop-down list is shown.
. Select a value from the drop-down list, depending on the energy efficiency class.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the characteristic to the item in the *Item » Edit item »* _Open item_ *»* _Open variation_ *» Tab: Characteristics* menu.

[#1450]
=== Creating the characteristic free return

Use the characteristic *FreeReturnDays* to transfer information about the free return period to idealo Checkout.

Proceed as described below to create the characteristic *FreeReturnDays*.

[.instruction]
Creating a characteristic for the free return period:

. Go to *Setup » Item » Characteristics » Tab: New characteristic*.
. Enter the *Name (internal)*.
. Select the characteristic type *whole number* from the drop-down list.
. Select the characteristic *FreeReturnDays* for *idealo Direktkauf property*.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the characteristic to the item in the *Item » Edit item »* _Open item_ *»* _Open variation_ *» Tab: Characteristics* menu.

[#1500]
=== Creating the characteristic deposit fee

Use the characteristic *DepositFee* to transfer information about the deposit fee to idealo Checkout. This characteristic is required if a deposit fee must be paid for an item.

Proceed as described below to create the characteristic *DepositFee*.

[.instruction]
Creating the characteristic deposit fee:

. Go to *Setup » Item » Characteristics » Tab: New characteristic*.
. Enter the *Name (internal)*.
. Select the characteristic type *decimal number* from the drop-down list.
. Select the characteristic *DepositFee* for *idealo Direktkauf property*.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the characteristic to the item in the *Item » Edit item »* _Open item_ *»* _Open variation_ *» Tab: Characteristics* menu.

[#1550]
=== Creating the characteristic replica

Use the characteristic *Replica* to specify whether the item is a replica.

Proceed as described below to create the characteristic *Replica*.

[.instruction]
Creating the characteristic replica:

. Go to *Setup » Item » Characteristics » Tab: New characteristic*.
. Enter the *Name (internal)*.
. Select the characteristic type *No* from the characteristic type drop-down list.
. Select the characteristic *Replica* for *idealo Direktkauf property*.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the characteristic to the item in the *Item » Edit item »* _Open item_ *»* _Open variation_ *» Tab: Characteristics* menu.


[#1600]
== Setting up event procedures

Set up event procedures to automatically inform idealo about changes in the order status. You can use event procedures to automatically send order confirmations, shipping confirmations, returns, and cancellations to idealo Checkout.

[TIP]
.Event procedures for idealo Checkout
====
You only have to set up event procedures if you use idealo Checkout.
====

[#1650]
=== Automatically sending order confirmations

Set up an <<automation/event-procedures#, event procedure>> to automatically send an order confirmation to idealo.

:table-event-procedure: <<#order-confirmation-idealo>>

include::../../_includes/textblocks/instructions/EA.adoc[]

[[order-confirmation-idealo]]
.Event procedure for automatically sending order confirmations to idealo
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *Order generation: New order*
|

| *Filter 1*
| *Order &gt; Order type*
| *Order*

| *Filter 2*
| *Order &gt; Referrer*
| *idealo Checkout*

| *Procedure*
| *Order &gt; Send order confirmation to idealo*
|
|====

[#1700]
=== Automatically sending shipping confirmations

Set up an <<automation/event-procedures#, event procedure>> to automatically send a shipping confirmation to idealo when the outgoing items have been booked.

:table-event-procedure: <<#shipping-confirmation-idealo>>

include::../../_includes/textblocks/instructions/EA.adoc[]

[[shipping-confirmation-idealo]]
.Event procedure for automatically sending shipping confirmations to idealo
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *Order change: Outgoing items booked*
|

| *Filter 1*
| *Order &gt; Order type*
| *Order*

| *Filter 2*
| *Order &gt; Referrer*
| *idealo Checkout*

| *Procedure*
| *Shipping > Send shipping confirmation to idealo*
|
|====

[#1750]
=== Automatically sending returns

Set up an <<automation/event-procedures#, event procedure>> to automatically inform idealo about returns.

:table-event-procedure: <<#returns-idealo>>

include::../../_includes/textblocks/instructions/EA.adoc[]

[[returns-idealo]]
.Event procedure for automatically sending returns to idealo
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *Order generation: New return*
|

| *Filter 1*
| *Order &gt; Order type*
| *Return*

| *Filter 2*
| *Order &gt; Referrer*
| *idealo Checkout*

| *Procedure*
| *Return > Send return to idealo*
|
|====

[#1800]
=== Automatically sending cancellations

Set up an <<automation/event-procedures#, event procedure>> to automatically inform idealo of cancellations.

:table-event-procedure: <<#cancellations-idealo>>

include::../../_includes/textblocks/instructions/EA.adoc[]

[[cancellations-idealo]]
.Event procedure for automatically sending cancellations to idealo
[cols="1,3,3"]
|====
|Setting |Option |Selection

| *Event*
| *Status change: [8] Cancelled*
|

| *Filter 1*
| *Order &gt; Order type*
| *Order*

| *Filter 2*
| *Order &gt; Referrer*
| *idealo Checkout*

| *Procedure*
| *Order: Send cancellation to idealo*
|
|====


[#1900]
== Viewing the log

:marktplatz: idealo
:identifikator: ElasticExportIdealoDE

include::../_textblocks/instructions/viewing_logs.adoc[]

[#2000]
== FAQ

[#2100]
=== Item export via API (PWS 2.0 interface)

===== Not all of my items are exported to idealo. What can I do?

[.indented]
If you transfer your items to idealo via API (PWS 2.0), but not all of your items have been exported, you can try to update the timestamp for market exports. Updating the timestamp might help because usually, only variations which have been updated within the last 2 days are exported to idealo.

[.instruction]
Updating the timestamp for market exports:

. Go to *Item » Batch processing*.
. In the *Procedures* area, activate the option *Update timestamp for market exports*.
. Click on *Apply* (icon:execute[set=plenty]). +
→ All items which are configured for idealo will be exported to idealo with the next item export.
