= Setting up idealo Checkout
:lang: en
include::{includedir}/_header.adoc[]
:keywords: idealo, idealo Checkout, market, marketplace, price comparison
:description: Multi-Channel in plentymarkets: Set up the interface to the market idealo Checkout in your plentymarkets system.
:position: 10
:url: markets/idealo-checkout/idealo-setup
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:

On this page, you will find information about the settings you need to carry out in order to set up the market and price comparison portal idealo Checkout in plentymarkets. Learn how to set up the interface, how to export items to idealo Checkout and how to define sales prices. +

[.subhead]
idealo price comparison and idealo Checkout

With plentymarkets, you can both use the idealo price comparison and idealo Checkout. idealo Checkout enables your customers to buy items directly on the idealo website without having to enter your web shop. +

The idealoDE plugin is required in order to use the idealo price comparison and idealo Checkout.

[#100]
== Registering with idealo

You need to register with link:https://partner.idealo.com/de/[idealo^] before setting up idealo in plentymarkets. Please note that this website is currently only available in German.


////
=== Performing an authentication at idealo

In order to allow plentymarkets access to your idealo account, you have to perform an authentication at idealo. This enables the data exchange between idealo and plentymarkets.

[.instruction]
Performing the authentication at idealo:

. Log into idealo with your idealo access data.
. Go to *Mein idealo » Einstellungen*.
. Click on *API Clients*.
. In the *Partner Web Service 2.0* section, click on *Neuen API Client erstellen*. +
→ The API credentials consisting of client ID and client password are created and displayed in a new window.

In order to allow plentymarkets access to your idealo account, enter the client ID and the client password in your plentymarkets system. The link:https://marketplace.plentymarkets.com/en/plugins/channels/preisportale/elasticexportidealode_4723[idealoDE plugin^] is required. The plugin can be downloaded in the plentyMarketplace.

[.instruction]
Entering the API credentials in plentymarkets:

. Go to *Setup » Markets » idealo Checkout » Configuration » Processes*.
. Enter the *client ID* and *client password* that you have received from idealo.
. *Save* (icon:save[role="green"]) the settings. +
→ A token is generated which allows plentymarkets access to idealo.
////

[#150]
== Installing the idealoDE plugin

Data is transferred to idealo via the elastic export. In order to automatically transfer data to idealo, install the link:https://marketplace.plentymarkets.com/en/plugins/channels/marktplaetze/elasticexport_4763[Elastic Export^] and link:https://marketplace.plentymarkets.com/en/plugins/channels/preisportale/elasticexportidealode_4723[idealoDE^] plugins from the link:https://marketplace.plentymarkets.com/en[plentyMarketplace^]. +

Installing the plugin is required both if you want to use the idealo price comparison and idealo Checkout. +

//and stock and prices are automatically synchronised with idealo//

Installing the idealoDE plugin allows for the following processes to take place:

* automatic data transfer to idealo via the elastic export
//* automatic price and stock synchronisation//

[#200]
== Setting up idealo in plentymarkets

//Activating the order import//

[IMPORTANT]
.Check idealo product CSV
====
Not all of the columns of idealo’s product CSV are available in plentymarkets at present. Check whether you need columns which are not yet available in plentymarkets prior to setting up idealo in plentymarkets. In this case, an integration of idealo is currently not possible. +
An overview of the columns which are available in plentymarkets can be found in the link:https://marketplace.plentymarkets.com/en/plugins/channels/preisportale/elasticexportidealode_4723[idealo plugin user guide^].
====

Carry out the following settings in plentymarkets in order to activate the automatic hourly order import from idealo. This setting is required both if you want to use the idealo price comparison and idealo Checkout.

[.instruction]
Activating the order import:

. Go to *Setup » Markets » idealo Checkout*.
. Place a check mark next to the *Activate automatic data exchange* option.
. Enter the API key as received from idealo.
. *Save* (icon:save[role="green"]) the settings.

//Connecting to this market allows for the following automatic processes to take place:

//* hourly order synchronisation//

[#250]
== idealo price comparison: Activating the order referrer

In order to link items, properties etc. with the idealo price comparison, you have to activate the *idealo* order referrer in the *Setup » Orders » Order referrer* menu. +

[.instruction]
Activating the order referrer for the idealo price comparison:

. Go to *Setup » Orders » Order referrer*.
. Place a check mark next to the option *idealo*.
. *Save* (icon:save[role="green"]) the settings.

If you would like to use *idealo Checkout*, then also activate the order referrer *idealo Checkout*, as described in the <<Setting up idealo Checkout in plentymarkets, Setting up idealo Checkout in plentymarkets>> chapter.

[#300]
== idealo price comparison: Setting the item availability

Items have to be available for idealo. This is done in the *Availability* tab of an item within the *Item » Edit item » Open item » Tab: Variation ID* menu. Activate the item availability for idealo as described below.

[.instruction]
Setting the item availability for the idealo price comparison:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section. +
→ A list with all available markets is displayed.
. Activate the option *idealo*.
. Activate the option *Web API*.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The market is added.
. *Save* (icon:save[role="green"]) the settings.

The availability for variations can be edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu. +

If you would like to use *idealo Checkout*, then also activate the order referrer *idealo Checkout* in the *Markets* section, as described in the <<Setting up idealo Checkout in plentymarkets, Setting up idealo Checkout in plentymarkets>> chapter.

[#400]
== idealo price comparison and idealo Checkout: Defining a sales price

Proceed as described below to define a sales price for the order referrer idealo. This price is displayed on idealo. It is valid for the idealo price comparison and idealo Checkout.

[.instruction]
Defining a sales price for idealo:

. Go to *Setup » Item » Sales prices » Open sales price » Tab: Settings*.
. Place a check mark next to the referrer *idealo*.
. *Save* (icon:save[role="green"]) the settings.

[#500]
== idealo price comparison and idealo Checkout: Defining SKU manually

Add SKUs manually for specific referrers in the *Item » Edit item » Open item » Tab: Variation ID » Tab: Availability* menu if needed.

[.instruction]
Adding SKU:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Click on the *Availability* tab.
. Click on *Add* (icon:plus-square[role="green"]) in the *SKU* section. +
→ The *New SKU* window is displayed.
. Select the referrer *idealo*.
//. Select the idealo account from the *Account* drop-down list. This is required if you use the idealo plugin version 2.0 so that your SKUs can be assigned to the account. +
//→ Select *Keine Konto-Zuordnung* (assign no account) if you use the idealo plugin version 1.0.
. Enter the SKU.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The SKU is saved and displayed.

[#600]
== idealo price comparison and idealo Checkout: Setting up the item export

Items are exported to idealo via elastic export with the data format idealoDE. Therefore, the plugins *ElasticExport* and *ElasticExportIdealoDE* have to be installed. First, create the data format idealoDE. Then transfer the URL to idealo. +

Setting up the item export is required both if you want to use the idealo price comparison and idealo Checkout.

[.instruction]
Setting up the item export:

. Go to *Data » Elastic export*.
. Click on *New export*.
. Carry out the settings. Pay attention to the explanations given in <<settings-item-export>>.
. Carry out further settings for item filters and format settings. Pay attention to the explanations given in table 2 on the <<data/exporting-data/elastic-export#300, Elastic export>> page.
. *Save* (icon:save[role="green"]) the settings. +
→ The export format is given an ID and it appears in the overview within the *Exports* tab.

[[settings-item-export]]
.Settings for the item export
[cols="1,3"]
|====
|Setting |Explanation

2+|Settings

|*Name*
|Enter a name. The export format is listed by this name in the overview within the *Exports* tab.

|*Type*
|Select the type *item* from the drop-down list.

|*Format*
|Select the format *idealoDE* from the drop-down list.

|*Limit*
|Enter a number. If you want to transfer more than 10,000 data records to idealo, then the output file will not be generated again for another 24 hours. This is to save resources.

|*Provisioning*
|Select *URL*.

|*Token*, +
*URL*
|If you selected the option *URL* under *Provisioning*, then click on *Generate token*. The token is entered automatically. The URL is entered automatically if the token was generated under *Token*. Give this URL to idealo in order to export the items.
|====

[#625]
== Setting up idealo Checkout in plentymarkets

idealo Checkout enables your customers to buy items directly on the idealo website without having to enter your web shop. The following chapters deal with the settings which are necessary in order to use idealo Checkout in plentymarkets. +

In order to use idealo Checkout in plentymarkets, activate the order referrer *idealo Checkout* and set the item availability for *idealo Checkout*.

[.instruction]
Activating the order referrer for idealo Checkout:

. Go to *Setup » Orders » Order referrer*.
. Place a check mark next to the option *idealo Checkout*.
. *Save* (icon:save[role="green"]) the settings.

If you activate the order referrer *idealo Checkout*, then the column *checkout_approved* is set to *true* in the file that is generated in the elastic export.

[.instruction]
Setting the item availability for idealo Checkout:

. Go to *Item » Edit item » Open item » Tab: Variation ID » Tab: Settings*.
. Activate the main variation in the *Availability* section.
. Click on the *Availability* tab.
. Click in the selection field in the *Markets* section. +
→ A list with all available markets is displayed.
. Activate the option *idealo Checkout*.
. Make sure that the *Web API* option is activated.
. Click on *Add* (icon:plus-square[role="green"]). +
→ The market is added.
. *Save* (icon:save[role="green"]) the settings.

The availability for variations can be edited in the *Item » Edit item » Open item » Tab: Variations » Open variation » Tab: Variation ID » Tab: Availability* menu.

[#650]
== idealo Checkout Activating the payment method *idealo Checkout*

Activate the payment method *idealo Checkout*. This allows payments to be made for orders on idealo and to be displayed in your plentymarkets system.

[.instruction]
Activating the idealo payment method:

. Go to *Setup » Orders » Payment » Methods*.
. Place a check mark next to the setting *Also show inactive*.
. Open the folder *DE > idealo Checkout*.
. Select the idealo payment method. +
→ The *Settings* tab opens.
. Carry out the settings. Pay attention to the explanations given in <<settings-payment-method-idealo>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings.

[[settings-payment-method-idealo]]
.Settings for the payment method
[cols="1,3"]
|====
| Setting | Explanation

|*Language*
| The following options are saved for the language selected: *Name*, *Info page*, *Info page (internal)*, *Logo*, and *Upload logo*. This enables you to enter values for these options in various languages. The values for a language are activated as soon as a buyer selects the language in the online store.

|*Name*
| Enter the name that should be displayed in the online store and on invoices etc.

|*Info page*
| Select a category page of the type *content* or enter the URL of a website to provide information about the payment method.

|*Info page (external)*
| If you selected the option *Info page (external)* under *Info page*, then enter the URL of the info page here.

|*Countries of delivery*
| Do not select a country of delivery. +
You cannot use the payment method in your online store. Therefore, this payment method is only activated in plentymarkets. It is not completely set up.

|*Logo*
| Select one of the following options for displaying the logo: +
*Show standard logo* = The logo that is saved in plentymarkets for this payment method is displayed. +
*Do not show a logo* = The logo that is saved in plentymarkets for this payment method is not displayed. +
*Show upload logo* = The options *Logo view* and *Upload logo* are displayed.

|*Logo view*
| If *Show upload logo* was selected from the *Logo* drop-down list, then the logo that was uploaded is displayed here.

|*Upload logo*
| If *Show upload logo* was selected from the *Logo* drop-down list, then upload an external logo here. +
Click on *Upload files* and select the logo that you would like to upload for the payment method. Permitted data formats: GIF, PNG, and JPG.

|*Priority*
| Select the priority for displaying the payment method in the online store.

|*Costs: Flat rate or percentage*
| If the payment method results in additional costs, enter the percentage value or the flat rate value. The choice depends on the conditions of your contract. *Important:* Do not enter a value into both fields. +
For further information, refer to the <<basics/working-with-plentymarkets/statistics/managing-statistics#, Managing statistics>> page. For an example of flat rate and percentage costs, refer to the <<payment/managing-payment-methods#20, Managing payment methods>> page.
|====

[TIP]
.Permitting the payment method in customer classes
====
Go to *Setup » CRM » Classes* to activate or deactivate *permitted payment methods*. +
For further information, refer to the <<payment/managing-payment-methods#30, Permitting the payment method in a customer class>> chapter.
====

For further information, refer to the <<payment/managing-payment-methods#, Managing payment methods>> page.

[IMPORTANT]
.PayPal payment method
====
If you offer the PayPal payment method, it is mandatory to create and configure this payment method in your plentymarkets system. This is to ensure that the payment is imported correctly and assigned to the order.
====

[#660]
== idealo Checkout Creating properties

Use <<item/managing-items#480, properties>> to link specific properties to your items which are required to set up idealo Checkout. Item properties, shipping methods and fees are transferred to idealo Checkout with properties.

[IMPORTANT]
.Properties can only be used with the idealo plugin version 2.0
====
The properties *DeliveryComment*, *DepositFee*, *DisposalPrice*, *EnergyClass*, *FreeReturnDays*, *Gender*, *Material*, and *Replica* can be used as soon as the idealo plugin version 2.0 becomes available and is installed in your plentymarkets system.
====

[#665]
=== Creating the properties material and gender

Use the properties *Material* and *Gender* to transfer information about material and target group or gender to idealo Checkout. +

Proceed as described below to create the property *Material*. Create the *Gender* property in the same way, but select the property type *Text* instead.

[.instruction]
Creating a property for material:

. Go to *Setup » Item » Properties » Tab: New property*.
. Enter the *Name (internal)*.
. Select *No* from the property type drop-down list.
. Select the property *Material* for *idealo Direktkauf property*.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the property to the item in the *Item » Edit item » Open item » Open variation » Tab: Properties* menu.

[#675]
=== Creating properties for shipping methods

With idealo Checkout, the customer buys the items directly at idealo and you have to send shipping information to idealo Checkout. If you ship your items with a parcel service, a shipping company, or via download, this mandatory information is transferred to idealo with a property. If the order is carried out by a shipping company, the customer has to enter their phone number during the order process in order to arrange a delivery date. +

Proceed as described below to create the property *FulfillmentType*. This property indicates whether you use the shipping method *shipping company*, *parcel service*, or *download*.

[.instruction]
Creating a property for the shipping method:

. Go to *Setup » Item » Properties » Tab: New property*.
. Enter the *Name (internal)*.
. Select *No* from the property type drop-down list.
. Select the property *FulfillmentType* for *idealo Direktkauf property*. +
→ A drop-down list appears.
. Select a value from the drop-down list, depending on the shipping method. The values *Spedition* (shipping company), *Paketdienst* (parcel service), and *Download* (download) are available.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the property to the item in the *Item » Edit item » Open item » Open variation » Tab: Properties* menu.

[.subhead]
Further properties for shipping methods

For items which have the shipping method shipping company, it is also possible to transfer the additional services *TwoManHandlingPrice* and *DisposalPrice* to idealo Checkout. DisposalPrice can only be used in combination with TwoManHandlingPrice. That means you have to create the property *TwoManHandlingPrice* as well as the property *DisposalPrice* and link them to the item. In both cases, select *decimal number* as the property type. Go to *Item » Edit item » Open item » Open variation » Tab: Properties* and enter the surcharge for the additional service with two decimal places behind the decimal separator. Use a period for the decimal separator (19.99).

[#676]
=== Creating a property for delivery comments

Use the property *DeliveryComment* to transfer further information about the delivery. +

Proceed as described below to create the property *DeliveryComment*.

[.instruction]
Creating a property to specify further information about the delivery:

. Go to *Setup » Item » Properties » Tab: New property*.
. Enter the *Name (internal)*.
. Select *Text* from the property type drop-down list.
. Select the property *DeliveryComment* for *idealo Direktkauf property*.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the property to the item in the *Item » Edit item » Open item » Open variation » Tab: Properties* menu.

[#680]
=== Creating the property energy efficiency class

Use the property *EnergyClass* to transfer information about the energy efficiency class to idealo Checkout. +

Proceed as described below to create the property *EnergyClass*.

[.instruction]
Creating a property for the energy efficiency class:

. Go to *Setup » Item » Properties » Tab: New property*.
. Enter the *Name (internal)*.
. Select the property type *No* from the drop-down list.
. Select the property *EnergyClass* for *idealo Direktkauf property*. +
→ A drop-down list appears.
. Select a value from the drop-down list, depending on the energy efficiency class.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the property to the item in the *Item » Edit item » Open item » Open variation » Tab: Properties* menu.

[#685]
=== Creating the property free return

Use the property *FreeReturnDays* to transfer information about the free return period to idealo Checkout. +

Proceed as described below to create the property *FreeReturnDays*.

[.instruction]
Creating a property for the free return period:

. Go to *Setup » Item » Properties » Tab: New property*.
. Enter the *Name (internal)*.
. Select the property type *whole number* from the drop-down list.
. Select the property *FreeReturnDays* for *idealo Direktkauf property*.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the property to the item in the *Item » Edit item » Open item » Open variation » Tab: Properties* menu.

[#690]
=== Creating the property deposit fee

Use the property *DepositFee* to transfer information about the deposit fee to idealo Checkout. This property is required if a deposit fee must be paid for an item. +

Proceed as described below to create the property *DepositFee*.

[.instruction]
Creating a property for the deposit fee:

. Go to *Setup » Item » Properties » Tab: New property*.
. Enter the *Name (internal)*.
. Select the property type *decimal number* from the drop-down list.
. Select the property *DepositFee* for *idealo Direktkauf property*.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the property to the item in the *Item » Edit item » Open item » Open variation » Tab: Properties* menu.

[#695]
=== Creating the property replica

Use the property *Replica* to specify whether the item is a replica. +

Proceed as described below to create the property *Replica*.

[.instruction]
Creating the property replica:

. Go to *Setup » Item » Properties » Tab: New property*.
. Enter the *Name (internal)*.
. Select the property type *No* from the drop-down list.
. Select the property *Replica* for *idealo Direktkauf property*.
. *Save* (icon:save[role="green"]) the settings.

Next, you have to link the property to the item in the *Item » Edit item » Open item » Open variation » Tab: Properties* menu.

[#700]
== idealo Checkout: Automatically sending order confirmations

Set up an <<automation/event-procedures#, event procedure>> to automatically send an order confirmation to idealo.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<event-procedure-order-confirmation-idealo>> below.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
. Carry out further settings. Pay attention to the explanations given in <<event-procedure-order-confirmation-idealo>> below.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[event-procedure-order-confirmation-idealo]]
.Event procedure for automatically sending order confirmations to idealo
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order generation: New order*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Referrer*
|*idealo Checkout*

|*Procedure*
|*Order > Send order confirmation idealo*
|
|====

[#800]
== idealo Checkout Automatically sending shipping confirmations

Set up an <<automation/event-procedures#, event procedure>> to automatically send a shipping confirmation to idealo when the outgoing items have been booked.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<event-procedure-shipping-confirmation-idealo>> below.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
. Carry out further settings. Pay attention to the explanations given in <<event-procedure-shipping-confirmation-idealo>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[event-procedure-shipping-confirmation-idealo]]
.Event procedure for automatically sending shipping confirmations to idealo
[cols="1,3,3"]
|====
|Setting |Option | Selection

|*Event*
|*Order change: Outgoing items booked*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Referrer*
|*idealo Checkout*

|*Procedure*
|*Shipping > Send shipping confirmation to idealo*
|
|====

[#850]
== idealo Checkout: Automatically sending returns

Set up an <<automation/event-procedures#, event procedure>> to automatically inform idealo about returns.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<event-procedure-returns-idealo>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
. Carry out further settings. Pay attention to the explanations given in <<event-procedure-returns-idealo>>.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[event-procedure-returns-idealo]]
.Event procedure for automatically sending returns to idealo
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Order generation: New return*
|

|*Filter 1*
|*Order > Order type*
|*Return*

|*Filter 2*
|*Order > Referrer*
|*idealo Checkout*

|*Procedure*
|*Return > Send return to idealo*
|
|====

[#900]
== idealo Checkout: Automatically sending cancellations

Set up an <<automation/event-procedures#, event procedure>> to automatically inform idealo of cancellations.

[.collapseBox]
.Setting up an event procedure
--
. Go to *Setup » Orders » Events*.
. Click on *Add event procedure* (icon:plus-square[role="green"]). +
→ The *Create new event procedure* window opens.
. Enter a name.
. Select the *event* listed in <<event-procedure-cancellations-idealo>>.
. *Save* (icon:save[role="green"]) the settings. +
→ The event is created.
. Carry out further settings. Pay attention to the explanations given in <<event-procedure-cancellations-idealo>>.
. Select a *reason* for the cancellation.
. Place a check mark next to the option *Active*.
. *Save* (icon:save[role="green"]) the settings. +
→ The event procedure is saved.
--

[[event-procedure-cancellations-idealo]]
.Event procedure for automatically sending cancellations to idealo
[cols="1,3,3"]
|====
| Setting | Option | Selection

|*Event*
|*Status change: [8] Cancelled*
|

|*Filter 1*
|*Order > Order type*
|*Order*

|*Filter 2*
|*Order > Referrer*
|*idealo Checkout*

|*Procedure*
|*Order > Send cancellation to idealo*
|
|====

[#1000]
== Viewing the API log

The *Data » API log* menu contains a history of processes that run via the idealo interface. The *idealoDirektkauf* format is available for idealo.

[.instruction]
Viewing the API log:

. Go to *Data » API log » Tab: API log*.
. Select the format *idealoDirektkauf *from the *Process* drop-down list.
. Select a *date* if you only want to see entries for a specific day.
. Select the number of results per page.
. Click on *Search* to display the results.
