Die Zahlungsart *Amazon* ist für Aufträge, die über den Marktplatz Amazon in dein plentymarkets System kommen und nicht zu verwechseln mit der Zahlungsart *Amazon Pay*, die für Kund:innen ist, die über den Marktplatz Amazon in deinem plentyShop einkaufen.

Aktiviere die <<payment/zahlungsarten-verwalten#, Zahlungsart>> *Amazon*, wie im Folgenden beschrieben.

[.instruction]
Zahlungsart Amazon aktivieren:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Option *Auch inaktive anzeigen*.
. Klicke auf den Ordner *International &gt; Amazon*. +
→ Die Einstellungen für die Amazon-Zahlungsart werden angezeigt.
. Setze ein Häkchen bei *Aktiv*.
. Nimm ggf. weitere Einstellungen vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[TIP]
.Zahlungsart in Kundenklassen erlauben
====
Im Menü *Einrichtung » CRM » Kundenklassen* aktivierst oder deaktivierst du *erlaubte Zahlungsarten*. +
Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#30, Zahlungsart in Kundenklasse erlauben>>.
====

Weitere Informationen findest du auf der Handbuchseite <<payment/zahlungsarten-verwalten#, Zahlungsarten verwalten>>.
