Varianten, die du auf Amazon-Länderplattformen verkaufen möchtest, müssen im Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Tab: Varianten-ID* im Tab *Verfügbarkeit* aktiviert werden.

[TIP]
.Gruppenfunktion oder Stapelverarbeitung nutzen
====
Die Verfügbarkeit für mehrere Varianten bearbeitest du entweder über die <<artikel/import-export-anlage/anlage/massenbearbeitung#100, Varianten-Gruppenfunktion>> oder die <<artikel/import-export-anlage/anlage/massenbearbeitung#400, Stapelverarbeitung>>.
====

[.instruction]
Variantenverfügbarkeit für Amazon-Länderplattform einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » Tab: Varianten-ID » Tab: Einstellungen*.
. Öffne die Variante, die du auf der Amazon-Länderplattform verkaufen möchtest. +
*_Tipp:_* Um alle Varianten eines Artikels auf der Amazon-Länderplattform zu verkaufen, nimm die Einstellungen an der Hauptvariante vor. Die Verfügbarkeit wird dann für alle Varianten des Artikels aktiviert.
. Aktiviere im Bereich *Verfügbarkeit* die Option *Aktiv*.
. Wechsele in das Tab *Verfügbarkeit*.
. Klicke im Bereich *Märkte* in das Auswahlfeld. +
→ Eine Liste mit allen verfügbaren Märkten wird angezeigt.
. Aktiviere die Amazon-Länderplattform(en), für die die Variante verfügbar sein soll.
. Aktiviere die Option *Web-API*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Der Marktplatz wird hinzugefügt.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Wechsele in das Tab *Multi-Channel*.
. Nimm die Einstellungen im Bereich *Amazon* vor. Beachte dazu die Erläuterungen in <<#artikelverfügbarkeit-amazon>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[artikelverfügbarkeit-amazon]]
.Variantenverfügbarkeit für Amazon einstellen
//tag::table[]
[cols="1,3"]
|====
| Einstellung | Erläuterung

| *Produkttyp*
|<<daten/export-import/datenformate/item#50, Amazon-Produkttyp>> wählen.

| *FBA-Abwicklung*
| Einen der Amazon-Marktplätze *AMAZON_EU* (Europa), *AMAZON_FE* (Ferner Osten), *AMAZON_NA* (Nordamerika) wählen, wenn der Artikel über FBA vermarktet werden soll.

| *Amazon FBA*
| Aktivieren, wenn die FBA-Funktion genutzt werden soll und wenn FBA-Bestände importiert werden sollen. +
Wenn du die Option *Amazon FBA* aktivierst, können für diesen Artikel FBA-Bestände in plentymarkets importiert werden und Amazon Multi-Channel-Aufträge, die mit FBA versendet werden, können angemeldet werden.
|====
//end::table[]

[IMPORTANT]
.Variantenverfügbarkeit für MFN und FBA
====
Wenn du deine Varianten für MFN und FBA verfügbar stellen möchtest, wähle, am Beispiel für Deutschland, die Amazon Länderplattform *Amazon Germany* und die Länderplattform *Amazon FBA Germany*.
====
