[#860]
=== Export von Grundpreisangaben vorbereiten

Die deutsche Grundpreisverordnung schreibt vor, dass für Produkte, die nach Gewicht, Volumen, Länge oder Fläche verkauft werden, der Grundpreis in unmittelbarer Nähe des Endpreises anzugeben ist.

Amazon berechnet den Grundpreis aus dem übermittelten Preis und den Angaben zu Menge und Einheit. Je nach Kategorie erwartet Amazon andere Felder. Informationen dazu, welche Werte für eine Kategorie übermittelt werden müssen, findest du in der Lagerbestandsdateivorlage der Amazon-Kategorie.

* Erstelle für jedes Feld, das Amazon für die Grundpreisangabe deiner Varianten erwartet, eine Eigenschaft.
* Verknüpfe die Eigenschaften mit einer Variante und speichere die Werte der Variante.

[#bp-100]
==== Eigenschaften für Grundpreisangaben erstellen

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*. +
→ Die Übersicht der Eigenschaften wird geöffnet.
. Klicke auf *Eigenschaft hinzufügen* (icon:plus-square[role="green"]).
. Wähle aus der Dropdown-Liste *Bereich* die Option *Artikel*.
. Nimm die weiteren Einstellungen vor. Beachte dazu die Informationen in <<#table-amazon-property-base-price>>.
. Gib eine Positionsnummer für die Eigenschaft ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Eigenschaft wird erstellt und zur weiteren Bearbeitung geöffnet.
. Nimm die weiteren Einstellungen gemäß <<#table-amazon-property-base-price>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#table-amazon-property-base-price]
.Eigenschaft erstellen
[cols="1,2a"]
|===
| *Einstellung* | *Erläuterung*

2+| Ansicht *Allgemein*

| *Bereich*
| Option *Artikel* wählen.

| *Eigenschaftstyp*
| * Für Mengenangaben Option *Kommazahl* wählen.
* Für Maßeinheiten Option *Auswahl* wählen.

| *Name*
| Name des Amazon-Felds eingeben. +
*_Hinweis:_* Speichere den Namen für alle Sprachen, die für eine Amazon-Plattform genutzt werden.

2+| Ansicht *Sichtbarkeit*

| *Herkunft*
| Gewünschte Amazon-Plattformen aktivieren.

2+| Ansicht *Werte*

| *Werte* (nur bei Typ *Auswahl*)
| Werte für die von Amazon erlaubten Maßeinheiten speichern.

2+| Ansicht *Amazon*

| *Amazon-Plattform*; +
*Kategorie*; +
*Feld*
| Amazon-Plattform, Kategorie und Feld aus den Dropdown-Listen wählen.

|===

[#bp-200]
==== Grundpreisangaben an Variante speichern

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Varianten-Tab: Eigenschaften*. +
*_Tipp:_* Um alle Varianten eines Artikels zu verknüpfen, nimm diese Einstellung an der Hauptvariante vor. Die Einstellung wird an alle Varianten des Artikels vererbt.
. Klicke im Bereich *Varianteneigenschaften* in das Feld *Eigenschaften*. +
→ Eine Dropdown-Liste mit den verfügbaren Eigenschaften wird angezeigt.
. Aktiviere die Eigenschaft, die du gerade erstellt hast.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird in der Liste der Eigenschaften angezeigt.
. Wähle in der Spalte *Wert* aus der Dropdown-Liste die Einheit, zum Beispiel *GR*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#bp-300]
==== Beispiele für Grundpreisangaben

TIP: In den folgenden Beispielen wird anhand der Amazon-Felder *item_display_weight* und *item_display_weight_unit_of_measure* beschrieben, wie du Eigenschaften für Mengenangaben und Maßeinheiten erstellst. Beachte jedoch, dass Amazon je nach Kategorie andere Felder erwartet. Informationen dazu, welche Werte für eine Kategorie übermittelt werden müssen, findest du in der Lagerbestandsdateivorlage der Amazon-Kategorie.

[.collapseBox]
.*_Beispiel:_* Mengenangabe item_display_weight
--

Ablauf:

* Erstelle eine Eigenschaft *item_display_weight*.
* Verknüpfe die Eigenschaft *item_display_weight* mit einer Variante und speichere das Gewicht an der Variante.

[.instruction]
Eigenschaft für Menge item_display_weight erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*. +
→ Die Übersicht der Eigenschaften wird geöffnet.
. Klicke auf *Eigenschaft hinzufügen* (icon:plus-square[role="green"]).
. Wähle aus der Dropdown-Liste *Bereich* die Option *Artikel*.
. Wähle aus der Dropdown-Liste *Eigenschaftstyp* die Option *Kommazahl*.
. Gib in das Feld *Name* den Namen *item_display_weight* ein. +
*_Hinweis:_* Speichere den Namen für alle Sprachen, die für eine Amazon-Plattform genutzt werden.
. Gib eine Positionsnummer für die Eigenschaft ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Eigenschaft wird erstellt und zur weiteren Bearbeitung geöffnet.
. Wechsele in die Ansicht *Sichtbarkeit*.
. Aktiviere im Bereich *Herkunft* die gewünschten Amazon-Plattformen.
. Wechsele in die Ansicht *Amazon*.
. Klicke auf *Verknüpfung hinzufügen* (icon:plus-square[role="green"]).
. Wähle aus der Dropdown-Liste eine *Amazon-Plattform*.
. Wähle aus der Dropdown-Liste *Kategorie* eine Kategorie.
. Wähle aus der Dropdown-Liste *Feld* die Option *item_display_weight*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Eigenschaft wird gespeichert und kann mit Varianten verknüpft werden.

[.instruction]
Variante mit Eigenschaft *item_display_weight* verknüpfen und Wert speichern:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Varianten-Tab: Eigenschaften*. +
*_Tipp:_* Um alle Varianten eines Artikels zu verknüpfen, nimm diese Einstellung an der Hauptvariante vor. Die Einstellung wird an alle Varianten des Artikels vererbt.
. Klicke im Bereich *Varianteneigenschaften* in das Feld *Eigenschaften*. +
→ Eine Dropdown-Liste mit den verfügbaren Eigenschaften wird angezeigt.
. Aktiviere die Eigenschaft *item_display_weight*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird in der Liste der Eigenschaften angezeigt.
. Gib in der Spalte *Wert* das Gewicht der Variante als Kommazahl ein, zum Beispiel `150`.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
--

[.collapseBox]
.*_Beispiel:_* Maßeinheit item_display__weight_unit_of_measure
--

Ablauf:

* Erstelle eine Eigenschaft *item_display_weight_unit_of_measure*.
* Verknüpfe die Eigenschaft *item_display_weight_unit_of_measure* mit einer Variante und wähle einen Eigenschaftswert.

[.instruction]
Eigenschaft für Maßeinheit item_display_weight_unit_of_measure erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*. +
→ Die Übersicht der Eigenschaften wird geöffnet.
. Klicke auf *Eigenschaft hinzufügen* (icon:plus-square[role="green"]).
. Wähle aus der Dropdown-Liste *Bereich* die Option *Artikel*.
. Wähle aus der Dropdown-Liste *Eigenschaftstyp* die Option *Auswahl*.
. Gib in das Feld *Name* den Namen *item_display_weight_unit_of_measure* ein. +
*_Hinweis:_* Speichere den Namen für alle Sprachen, die für eine Amazon-Plattform genutzt werden.
. Gib eine Positionsnummer für die Eigenschaft ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Eigenschaft wird erstellt und zur weiteren Bearbeitung geöffnet.
. Wechsele in die Ansicht *Sichtbarkeit*.
. Aktiviere im Bereich *Herkunft* die gewünschten Amazon-Plattformen.
. Wechsele in die Ansicht *Werte*.
. Klicke auf *+ Hinzufügen*.
. Gib als Namen die Einheit *KG* für Kilogramm ein.
. Speichere die Einstellung.
. Klicke erneut auf *+ Hinzufügen*.
. Gib als Namen die Einheit *GR* für Gramm ein.
. Speichere die Einstellung.
. Wechsele in die Ansicht *Amazon*.
. Klicke auf *Verknüpfung hinzufügen* (icon:plus-square[role="green"]).
. Wähle aus der Dropdown-Liste eine *Amazon-Plattform*.
. Wähle aus der Dropdown-Liste *Kategorie*.
. Wähle aus der Dropdown-Liste *Feld* die Option *item_display_weight_unit_of_measure*.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Eigenschaft wird gespeichert und kann mit Varianten verknüpft werden.

[.instruction]
Variante mit Eigenschaft item_display_weight_unit_of_measure verknüpfen und Wert speichern:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Varianten-Tab: Eigenschaften*. +
*_Tipp:_* Um alle Varianten eines Artikels zu verknüpfen, nimm diese Einstellung an der Hauptvariante vor. Die Einstellung wird an alle Varianten des Artikels vererbt.
. Klicke im Bereich *Varianteneigenschaften* in das Feld *Eigenschaften*. +
→ Eine Dropdown-Liste mit den verfügbaren Eigenschaften wird angezeigt.
. Aktiviere die Eigenschaft *item_display_weight_unit_of_measure*.
. Klicke auf *Hinzufügen* (icon:plus-square[role="green"]). +
→ Die Eigenschaft wird in der Liste der Eigenschaften angezeigt.
. Wähle in der Spalte *Wert* aus der Dropdown-Liste die Einheit, zum Beispiel *GR*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
--
