=== Grundpreis vorbereiten

Die deutsche Grundpreisverordnung schreibt vor, dass für Produkte, die nach Gewicht, Volumen, Länge oder Fläche verkauft werden, der Grundpreis in unmittelbarer Nähe des Endpreises anzugeben ist. Amazon berechnet diesen Grundpreis aus dem übermittelten Preis und den Angaben zu Menge und Einheit. Je nach Kategorie müssen dabei unterschiedliche Werte an Amazon übermittelt werden. Informationen dazu, welche Werte für eine Kategorie übermittelt werden müssen, findest du in der Lagerbestandsdateivorlage der Kategorie.

* Öffne die Lagerbestandsdateivorlage für die Kategorien, in denen du Artikel verkaufen möchtest.
* Prüfe, welche Werte du für die Grundpreisangabe an Amazon exportieren musst.
* Erstelle Eigenschaften für die benötigten Werte.

[[table-amazon-base-price]]
.Benötigte Eigenschaften für die Grundpreisangabe (Stand: 24.02.2021)
[cols="1,3a"]
|====
|Berechnungsgrundlage |Benötigte Werte

| Gewicht
a|

[cols="1,3a"]
!===
! Menge
! item_display_weight

! Maßeinheit
! item_display_weight_unit_of_measure

* Mögliche Werte: GR für Gramm, KG für Kilogramm

! Sonstige
! * unit_count
* unit_count_type
* item_package_quantity
* number_of_items
!===

| Volumen
a|

[cols="1,3a"]
!===
! Menge
! item_display_volume

! Maßeinheit
! item_display_volume_unit_of_measure

* Mögliche Werte: milliliter, liter

! Sonstige
! * unit_count
* unit_count_type
* item_package_quantity
* number_of_items
!===

| Länge
a|

[cols="1,3a"]
!===
! Menge
! item_display_length

! Maßeinheit
! item_display_length_unit_of_measure

* Mögliche Werte: cm für Zentimeter, M für Meter

! Außerdem
! * unit_count
* unit_count_type
* item_package_quantity
* number_of_items
!===

|====

[.instruction]
Eigenschaft für Menge erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*. +
→ Die Übersicht der Eigenschaften wird geöffnet.
. Klicke auf *Eigenschaft hinzufügen* (icon:plus-square[role="green"]).
. Wähle aus der Dropdown-Liste *Bereich* die Option *Artikel*.
. Wähle aus der Dropdown-Liste *Eigenschaftstyp* die Option *Kommazahl*.
. Gib in das Feld *Name* den Namen der Spalte in der Amazon-Lagerbestandsdatei ein, z.B. *item_display_weight*. +
*_Wichtig:_* Für die Eigenschaft darf nur dieser Name benutzt werden. Die Eigenschaft wird sonst nicht an Amazon übermittelt.
. Gib eine Positionsnummer für die Eigenschaft ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Eigenschaft wird erstellt und zur weiteren Bearbeitung geöffnet.
. *_Optional:_* Wenn du international verkaufst, speichere den Namen für weitere Sprachen.
. Wechsele in die Ansicht *Amazon*.
. Klicke auf *Verknüpfung hinzufügen* (icon:plus-square[role="green"]).
. Wähle aus der Dropdown-Liste eine *Amazon-Plattform*.
. Wähle aus der Dropdown-Liste *Kategorie* eine Kategorie.
. Wähle aus der Dropdown-Liste *Feld* das Feld aus der Amazon-Lagerbestandsdatei.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Verknüpfung wird gespeichert.

[.instruction]
Eigenschaft für Maßeinheit erstellen:

. Öffne das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration*. +
→ Die Übersicht der Eigenschaften wird geöffnet.
. Klicke auf *Eigenschaft hinzufügen* (icon:plus-square[role="green"]).
. Wähle aus der Dropdown-Liste *Bereich* die Option *Artikel*.
. Wähle aus der Dropdown-Liste *Eigenschaftstyp* die Option *Auswahl*.
. Gib in das Feld *Name* den Namen der Spalte in der Amazon-Lagerbestandsdatei ein, z.B. *item_display_weight_unit_of_measure*. +
*_Wichtig:_* Für die Eigenschaft darf nur dieser Name benutzt werden. Die Eigenschaft wird sonst nicht an Amazon übermittelt.
. Gib eine Positionsnummer für die Eigenschaft ein.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Eigenschaft wird erstellt und zur weiteren Bearbeitung geöffnet.
. *_Optional:_* Wenn du international verkaufst, speichere den Namen für weitere Sprachen.
. Wechsele in die Ansicht *Werte*.
. Klicke auf *+ Hinzufügen*.
. Gib als Namen die Einheit an, z.B. *KG* für Kilogramm.
. Speichere die Einstellung.
. Speichere ggf. weitere Werte.
. Wechsele in die Ansicht *Sichtbarkeit*.
. Aktiviere im Bereich *Herkunft* die gewünschten Amazon-Plattformen.
. Wechsele in die Ansicht *Amazon*.
. Klicke auf *Verknüpfung hinzufügen* (icon:plus-square[role="green"]).
. Wähle aus der Dropdown-Liste eine *Amazon-Plattform*.
. Wähle aus der Dropdown-Liste *Kategorie* eine Kategorie.
. Wähle aus der Dropdown-Liste *Feld* das Feld aus der Amazon-Lagerbestandsdatei.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Die Verknüpfung wird gespeichert.

[.instruction]
Eigenschaft für Grundpreisangaben an einer Variante speichern:

. Öffne das Menü *Artikel » Artikel bearbeiten » [Artikel öffnen] » [Variante öffnen] » Tab: Einstellungen*.
. Wechsele in das Tab *Eigenschaften*.
. Gib im Bereich *Varianteneigenschaften* den Namen der Eigenschaft ein.
*_Hinweis:_* Wenn du die Eigenschaft nicht findest, prüfe, ob du die richtige Amazon-Kategorie verknüpft hast.
. Klicke auf *Hinzufügen*. +
→ Die Eigenschaft wird hinzugefügt.
. Klicke in die Spalte *Wert*. +
→ Der Kalender wird eingeblendet.
. Wähle ein Startdatum für den Aktionspreis.
. Gib im Bereich *Varianteneigenschaften* den Eigenschaftsnamen *SalesEndDate* ein.
. Klicke auf *Hinzufügen*. +
→ Die Eigenschaft wird hinzugefügt.
. Klicke in die Spalte *Wert*. +
→ Der Kalender wird eingeblendet.
. Wähle ein Enddatum für den Aktionspreis. +
*_Tipp:_* Das Enddatum muss nach dem Startdatum liegen.

=====
