== VCS-Aufträge entsperren

Wenn du den VCS-Service von Amazon nutzt, werden alle Rechnungsdokumente automatisch erstellt, wenn die VCS-Berichte importiert werden. Du erstellst also selbst keine Rechnungsdokumente. Die Aufträge sind für die manuelle Rechnungserstellung gesperrt.
Falls Amazon keine Berichte erstellt oder für einen Auftrag keine Rechnung erzeugt wurde, kannst du VCS-Aufträge manuell entsperren.

NOTE: Die VCS-Berichte von Amazon haben oberste Priorität. Das gilt auch für entsperrte VCS-Aufträge, für die du manuell Rechnungsdokumente erstellt hast. Wenn Amazon mit einem späteren VCS-Bericht doch noch eigene Belege übermittelt, werden deshalb für diese Aufträge automatisch ein Stornobeleg und eine neue Rechnung erzeugt.

[.instruction]
VCS-Aufträge entsperren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Datenaustausch » Berichte*.
. Wechsle in das Tab *VCS-Aufträge entsperren*.
. Wähle in der Dropdown-Liste *Auftrags-ID-Typ*, ob du die *Amazon Auftrags-ID* oder die plentymarkets *Auftrags-ID* eingeben möchtest, um die Aufträge zu suchen.
. Gib in das Feld *Auftrags-ID-Liste* die ID der Aufträge ein. Mehrere ID kannst du durch Kommas getrennt eingeben.
. Klicke auf *VCS-Aufträge entsperren* (icon:execute[set=plenty]). +
→ Im Bereich *Ergebnisse* wird angezeigt, wie viele Aufträge entsperrt wurden. In der Tabelle siehst du den Status der einzelnen Aufträge. +
→ Du kannst für die entsperrten Aufträge manuell Rechnungsdokumente erstellen. +
*_Wichtig:_* Die manuell erstellten Rechnungsdokumente verlieren ihre Gültigkeit, wenn Amazon mit einem späteren VCS-Bericht eigene Belege übermittelt. Deine Rechnungsdokumente werden dann storniert und es wird eine neue Rechnung erstellt.

[Discrete]
===== Entsperrte Aufträge im Daten-Log finden

Im Menü *Daten » Log* kannst du bei Bedarf nachvollziehen, wann und durch welche:n Benutzer:in Aufträge entsperrt wurden. <<#list-log-filters>> zeigt, welche Filter du nutzen kannst, um Einträge im Log zu finden.

include::../../../_textblocks/instructions/logs_abrufen.adoc[tag=data-log-config]

[[list-log-filters]]
.Empfohlene Filter für Daten-Log
[cols="1,3a"]
|====
|Filter |Auswahl

| Integration
| PlentyLegacy\Modarkets

| Identifikator
| AmazonUnlockVcsOrder

| Referenzen

|* amazonOrderId
* orderId
