= Template functions
:lang: en
include::{includedir}/_header.adoc[]
:position: 90

toc::[]
== General information

The CMS syntax supports several kinds of functions. These functions can either be used globally or within specific templates.

== Global Functions

This section describes the functions that are used in both the web design and e-mail templates.

Some PHP functions have been integrated into the CMS syntax. Their usage corresponds to that directly in PHP.

<<cms-syntax/global/phpfunctions#, Open PHP functions  >>

== Web design

[.row]
====
[.col-md-6]
.PageDesign
=====
This section primarily contains link functions that return URLs to specific sections such as categories, home page, shopping cart, etc.

<<cms-syntax/web-design/pagedesign#, Open PageDesign  >>
=====

[.col-md-6]
.Navigation
=====
The functions in this section call various containers for displaying navigation menus (category navigation).

<<cms-syntax/web-design/navigation#, Open navigation  >>
=====
====

[.row]
====
[.col-md-6]
.ItemView
=====
The largest number of containers and thus functions are available for displaying items (e.g. product page, search result).

<<cms-syntax/web-design/itemview#, Open ItemView  >>
=====

[.col-md-6]
.Category
=====
This section only contains a small number of functions. However, note the function Form() that is used to return forms.

<<cms-syntax/web-design/category#, Open Category  >>
=====
====
== E-mail templates

Some link functions are available for using in e-mail templates.

<<cms-syntax/email/email#, Open E-mail  >>

