= Using the FBA service by Amazon
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Amazon FBA, FBA, Amazon Multi-Channel, Amazon FBA Multi-Channel, setting up Amazon FBA, FBA setup, set up Amazon FBA, shipping by Amazon, Amazon ships, Fulfillment by Amazon, Fulfilment by Amazon, Amazon Fulfilment, Amazon Fulfillment
:description: Multi-Channel in plentymarkets: Amazon ships your items with Amazon FBA.
:position: 40
:url: markets/amazon/amazon-fba
:id: VKWEAOP
:author: team-multi-channel


The abbreviation FBA stands for Fulfilment by Amazon. Instead of dealing with the orders yourself, packaging the items and sending them, you let Amazon take care of this task for you with the FBA programme. Of course, you then have to store at least some of your items with Amazon. +

For further information about setting up Amazon FBA in plentymarkets, watch this video tutorial:

.Amazon FBA
video::314713940[vimeo]

[#3300]
== Setting up the FBA service by Amazon

[#3400]
=== Creating a warehouse for Amazon FBA

Go to *Setup » Markets » Amazon » Settings » Tab: Order settings* and use the *Warehouse* option to select which warehouse you would like to use for Amazon fulfilment orders. This way, you can be sure that the complete range of stock management functions remain intact with the FBA programme and that you can keep track of the stock at Amazon in your plentymarkets system.

[.instruction]
Creating a warehouse:

. Go to *Setup » Stock » Warehouse*.
. Click on *New warehouse*.
. Enter a name for the warehouse.
. Select a *Warehouse type*. +
*_Note:_* If you only want to use this warehouse for FBA stock, i.e. if you only want to offer the stock of this warehouse for Amazon FBA and not in your online store or on other markets, then select the warehouse type *Repair*.
. Select *Amazon* as *Logistics type*.
. *Save* (icon:save[role="green"]) the settings to create the warehouse. +
→ The warehouse is listed in the overview in alphabetical order and opened.
. Carry out further settings according to the explanations on the <<stock-management/setting-up-a-warehouse#, Setting up a warehouse>> page of the manual.
. *Save* (icon:save[role="green"]) the settings.

Only you can decide whether the advantages tied to the FBA service outweigh the disadvantages for your personal situation as an online seller. Here we would only like to make reference to a few important points:

*  Amazon processes orders quickly and reliably. Peak times before Christmas run just as smoothly for store owners as the summer slump while most people are away on vacation.
*  Your listing on the market improves noticeably. You can expect higher sales figures.
*  The FBA service is subject to costs. Naturally, your gross margin will decrease. When doing a comprehensive comparison of the costs, keep in mind that the FBA service includes the expenses tied to storage, handling orders, customer service etc. and as such, relieves you from these expenditures.
*  Generally, items that are stored with Amazon can only be offered there as well. You need to have separate stock for other markets. Amazon's Multi-Channel fulfilment service, however, is a variation that provides you with additional possibilities in this matter.
*  You have much less stress with deliveries that cannot be sent or that are delayed. Packages with the Amazon logo are generally given priority.

[#3500]
=== FBA order import

Proceed as follows to define that your FBA orders are automatically imported in your plentymarkets system once a day.

[.instruction]
Automatically importing FBA orders:

. Go to *Setup » Markets » Amazon » Settings*.
. Select the account.
. Click on the *Order settings* tab.
. In the *Amazon FBA* area, activate the setting *Active*.
. *Save* (icon:save[role="green"]) the settings.

Order processing has the following steps:

*  The customer makes a purchase on Amazon.
*  Amazon sends the items.
*  The plentymarkets system requests a report.
*  Amazon creates the report.
*  The next day, plentymarkets automatically checks whether any Amazon reports exist. If yes, then these reports are imported.
*  Orders are generated in plentymarkets from the information contained in these reports.

[IMPORTANT]
.Note regarding the order import
====
Amazon only generates the list of orders once per day. Since it can take up to 2 days before an item is ready for shipping, FBA orders are available in your system with a time delay. Generally, the order confirmation that was generated by Amazon is available in your system two days after the item was shipped or a total of up to 4 days after it was ordered. The punctuality of the deliveries, however, is not affected. They will be carried out with the quickness that is customary for Amazon.
====

Amazon FBA orders are imported with the parameters *Status* and *Referrer*. Select the *Status* that is most appropriate for your process. For example, this could be status *[7] Outgoing items booked*. The referrer is automatically set to Amazon FBA or an Amazon FBA sub-referrer, e.g. Amazon FBA USA. The date when items are shipped is saved directly in plentymarkets. Therefore, stock is not reserved for items that are included in the order.

[TIP]
.Event procedures for fulfilment
====
Configure the event procedures that are necessary for the fulfilment process. Such event procedures are having invoices generated and sent to your customers with the help of automatic emails, and having the order then switch to another status. +
For further information, refer to the <<automation/event-procedures#, Event procedures>> and <<fulfilment#, Fulfilment>> pages of the manual.
====

[discrete]
===== FBA partial deliveries

Amazon will send FBA partial deliveries if the items ordered by the customer are stored in separate warehouses.
Hence, the customer receives multiple packages for one order. +
In plentymarkets, each FBA partial delivery is saved as a separate order, depending on the FBA warehouse which sends the item. You can import one tracking number from Amazon for each partial delivery and then assign it to the according partial delivery. You can generate a separate invoice for each partial delivery. This is necessary if the Amazon warehouses are located in different countries due to differing taxes.

[discrete]
===== European Fulfilment Network (EFN)

Amazon is continuously expanding its European Fulfilment Network for sellers who use shipment by Amazon. In order to use this network, it is required that you are fiscally registered in all countries in which you use FBA logistics centres. In order for your invoices to be generated correctly for these new logistics centres from the fiscal point of view, you can - in addition to your company location - select the warehouse location as basis for the default VAT rate. You can carry out these settings for each client (store) in the *Setup » Client » Select client » Locations » Select location » Accounting* menu. In the *VAT rates* tab, you save the necessary tax rates for the countries.

[TIP]
.Example: Logistics centre is located in Poland and items are shipped to Germany
====
To avoid that the Polish tax rate is used for orders that are shipped to Germany from a logistics centre in Poland, you also have to enter the country Germany with the German tax rate for the location Poland. To do so, go to *Setup » Client » Select client » Locations » Poland » Accounting » Tab: VAT rates*, select the country *Germany* and enter the German tax rate as well as the valid VAT number.
====

[#3600]
=== Automatically importing FBA returns

In case of a return, the purchaser sends the items back to Amazon. The return is imported into your plentymarkets system and listed in the order menu. It is given the return status that you selected in the *Setup » Orders » Settings* menu.

[IMPORTANT]
.Do not change the order
====
Returns will only be imported if the order exists in plentymarkets and its external order number was not changed.
====

Activate the import function as described below in order to automatically import FBA returns in your plentymarkets system.

[.instruction]
Activating the import function for FBA returns:

. Go to *Setup » Markets » Amazon » Settings*.
. Select the Amazon account.
. Click on the *Order settings* tab.
. Select the setting *Daily* from the *Returns import* drop-down list in the *Shipment by Amazon (FBA)* area.
. *Save* (icon:save[role="green"]) the settings.

[#3650]
=== Automatically importing FBA credit notes

Use the credit note import in order to automatically import FBA credit notes into your plentymarkets system. The credit notes are imported with the status which you have selected for the *Standard status for credit note* setting in the *Setup » Orders » Settings* menu. If you activate the credit note import, then FBA credit notes are imported into your plentymarkets system every 4 hours.

[IMPORTANT]
.Do not import FBA returns as credit notes via an event procedure
====
If you activate the credit note import, FBA credit notes are automatically imported into your plentymarkets system every 4 hours. Therefore, in this case do not use an event procedure to create credit notes from FBA returns.
====

[.instruction]
Activating the automatic credit note import:

. Go to *Setup » Markets » Amazon » Settings*.
. Select the Amazon account.
. Click on the *Order settings* tab.
. Select *Yes* for the *Credit note import* option.
. *Save* (icon:save[role="green"]) the settings.

[#3700]
== Setting up Amazon Multi-Channel

Amazon Multi-Channel Fulfilment is Amazon's service that enables you to fulfil orders from sales channels other than Amazon.co.uk using the inventory that you have stored in the Amazon fulfilment centre. (source: Amazon)

In other words, the Multi-Channel function allows you to store your items with Amazon and have Amazon ship your items even though you sell these items on external markets. This chapter describes which settings you have to carry out in your plentymarkets system so that these orders can be processed by Amazon.

The following steps are necessary to configure your stock and item data for Amazon Multi-Channel.

Watch this video tutorial for more information about Amazon Multi-Channel and setting up the service in your plentymarkets system:

.Amazon FBA
video::314727596[vimeo]

[#3800]
=== Creating a warehouse for Amazon Multi-Channel

Create a warehouse, if you have not yet created one as described in the <<Using the FBA service by Amazon, Using the FBA service by Amazon>> chapter. When using Multi-Channel fulfilment, it is important to set up a warehouse for each country-specific Amazon marketplace with the logistics type *Amazon* and the country as its location.

[IMPORTANT]
.Example of matching Amazon platform and warehouse location
====
Multi-Channel fulfilment takes place via amazon.co.uk. Create a new warehouse Amazon UK with the logistics type *Amazon* and the location Great Britain. The items must actually be stored with Amazon in that country e.g. in Great Britain. Otherwise they cannot be handled and shipped by amazon.co.uk.
====

[#3900]
=== Activating the variation availability for Amazon Multi-Channel

Carry out the following settings for the items that you want to make available for Amazon Multi-Channel.

[.instruction]
Activating the variation availability for Amazon Multi-Channel:

. Go to *Item » Edit item*.
. Open the item.
. Click on the *Multi-Channel* tab.
. Carry out the settings in the *Amazon* area. Pay attention to the explanations given in <<#item-availability-amazon>> in the <<#700, Setting the variation availability>> chapter.
. *Save* (icon:save[role="green"]) the settings.

[#4000]
=== Carrying out settings for Amazon Multi-Channel

Carry out the settings in the Amazon menu as described below.

[.instruction]
Setting up Amazon Multi-Channel:

. Go to *Setup » Markets » Amazon » Settings*.
. Click on the *Order settings* tab.
. Carry out the settings in the *Shipment by Amazon (FBA)* area. Pay attention to the explanations given in <<#amazon-multi-channel>>.
. *Save* (icon:save[role="green"]) the settings.

[[amazon-multi-channel]]
.Setting up Amazon Multi-Channel
[cols="1,3"]
|====
| Setting | Explanation

| *Active*
| Place a check mark to activate the daily order import.

| *Referrer*
| *Only use for Amazon orders* = Only process Amazon orders with FBA. +
*Can be used for all orders* = Process all orders with FBA.

| *Status*
|Select the <<orders/managing-orders#1200, order status>> for orders that were imported from Amazon.

| *Warehouse*
| Select which <<Creating a warehouse for Amazon FBA, warehouse>> should be used for Amazon shipments.

| *Outgoing items*
| Select whether outgoing items should be marked as booked or not. The option *Mark as booked* does not trigger an item movement. In order to trigger an item movement, select the option *Do not mark as booked* and set up an event procedure.

| *Returns import*
|Select whether returns should be imported *daily* or *never*.

| *Include coupons to returns*
|Select whether coupons can be used for FBA returns or not. If the FBA order was paid fully or partly with a coupon, the coupon is added to the return. A minimum order quantity for the coupon is not taken into consideration.

| *Stock import*
| Select the option *Hourly* to import stock on an hourly basis. +
Only changes in the stock data are taken into consideration. For further information about stock import options, refer to the <<Synchronising stock, Synchronising stock>> chapter.

| *Status for transmitted orders*
| Determines which order status should be used for multi-channel FBA orders that were transferred to FBA.

| *Item bundles Multichannel*
| Select which positions should be transferred to Amazon. +
*Transmit all order positions* = Transmit all positions included in the order to Amazon. If you select this option, then both the package position and the contents of the package are transmitted to Amazon. +
*Transmit package position only* = Only the package position is transferred to Amazon. +
*Transmit without package position* = Only the contents of the package are transferred to Amazon.

| *Shipping category*
| Select a shipping category. +
*Standard* = Normal shipping +
*Expedited* = Express shipping +
*Priority* = Fastest shipping service
|====

[#4100]
=== Automatically transferring the shipping permission to FBA

Set up an <<automation/event-procedures#, event procedure>> to automatically inform Amazon about the order. After Amazon has received this information, the order is processed and the item(s) are made ready for shipping.

:table-event-procedure: <<#event-procedure-fba-shipping-clearance>>

include::../../_includes/textblocks/instructions/EA.adoc[]

[[event-procedure-fba-shipping-clearance]]
.Event procedure for automatically transferring the shipping permission to FBA
[cols="1,3,3"]
|====
| Setting | Option | Selection

| *Event*
| *Order change: Status change > [5] Cleared for shipping*
|

| *Filter 1*
| *Order > Order warehouse*
| *Amazon Multi-Channel*

| *Filter 2*
| *Shipping > Shipping by FBA only*
|

| *Filter 3*
| *Order > Referrer*
| *_Important:_* Do not select an Amazon referrer. Otherwise, it may result in duplicate FBA orders.

| *Procedure*
| *Shipping > Transfer shipping permission to FBA*
|
|====

When switching to status 5, Amazon is informed that the items are cleared for shipping. Amazon ships the items and your plentymarkets system receives a confirmation from Amazon. The order switches to status 5.1, as determined in the <<Carrying out order settings, order settings>>. The package number is imported into your plentymarkets system.

[TIP]
.Import of package numbers
====
Package numbers are imported once per day.
====

[#2400]
=== Synchronising stock for Amazon Multi-Channel

Stock is synchronised with Amazon in the *Setup » Markets » Amazon » Data exchange » FBA stock* menu. There are a few different ways to do this. You can use the hourly automatic stock synchronisation, an automatic procedure or a CSV file.

[IMPORTANT]
.Only for Amazon Multi-Channel
====
This feature is intended for <<Setting up Amazon Multi-Channel, Amazon Multi-Channel>> only.
====

In plentymarkets, a distinction is made between automatic stock synchronisation and manual stock synchronisation. Both procedures are described below.


[.tabs]
====
Automatically synchronising stock::
+
--
Proceed as follows to automatically synchronise stock.

[.instruction]
Automatically synchronising stock:

. Go to *Setup » Markets » Amazon » Data exchange » FBA stock*.
. Select the Amazon account in the *Automatically* tab.
. Click on *Synchronise Amazon FBA stock*.

4 minutes are allotted for this process. If Amazon does not provide the data within this time frame, then stock is not synchronised. The next request will use the previous data that was not transferred. This can lead to errors. Therefore, we recommend that you manually synchronise data with a CSV file as described in the next chapter.

Stock information is only synchronised for those items that had their stock changed on Amazon in the last 30 days. We recommend that you use the manual synchronisation for the first import. The stock is synchronised according to the <<Carrying out the initial settings, initial settings>> in plentymarkets.
--

Manually synchronising stock::
+
--
Stock is synchronised manually via CSV file.

[IMPORTANT]
.Assigning SKU numbers
======
If you want to manually synchronise data, then you also have to specify how SKU numbers should be assigned to the stock. This is specified in the <<markets/amazon/amazon-setup#400, initial settings>>.
======

Before you carry out this synchronisation, you have to request the corresponding report file from Amazon in Seller Central. Download this CSV file and save it on your computer.

[.instruction]
Manually synchronising stock:

. Go to *Setup » Markets » Amazon » Data exchange » FBA stock*.
. Click on the *Manual* tab.
. Select the Amazon account.
. Click on *Select file* to select the CSV file that you have just saved.
. *Save* (icon:save[role="green"]) the settings to carry out the synchronisation.
--
====
