= Praxisbeipiele Kataloge für Aufträge und Auftragspositionen
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:description: Erfahre anhand von Praxisbeispielen, wie du dir einen Katalog für den Export von Aufträgen und Auftragspositionen erstellst.
:position: 100
:url: daten/daten-exportieren/katalog-auftraege
:id: OXKY6KE
:author: team-order-payment

Diese Handbuchseite führt Praxisbeispiele zum Erstellen eines Katalogs für den Export von Aufträgen und Auftragspositionen auf. Solltest du noch nicht vertraut sein mit den Katalogen, informiere dich zuerst im Handbuchkapitel <<daten/daten-exportieren/kataloge-verwalten#, Kataloge verwalten>>. Dort erhältst du alle benötigten Informationen, die du zum Erstellen und Bearbeiten von Katalogen brauchst.

Das Katalogformat Aufträge umfasst sowohl Datenfelder für Auftragsdaten als auch für Auftragspositionsdaten. Je nach Arbeitsablauf kannst du dir also entweder getrennte Kataloge für den Export der jeweiligen Daten anlegen oder die Daten in einem großen Katalog zusammenstellen und exportieren. Überlege generell, welche Daten du benötigst und welche Zusammenstellung in Katalogen für dich sinnvoll ist. +
Im Folgenden geben wir 2 Beispiele für das Erstellen von Katalogen für den Export von Aufträgen. Die Beispiele zeigen Möglichkeiten auf, wie der Export von Aufträgen mit dem Katalog gestaltet werden kann. Du kannst bei Bedarf die Beispiele als Unterstützung für die Erstellung deiner Kataloge nutzen.

Treffe die folgenden Einstellungen im Bereich *Format*, wenn du einen neuen Katalog erstellst:

[[table-format-settings]]
.Formateinstellungen Katalog für den Export von Aufträgen und Auftragspositionen
[cols="3,3"]
|====
|Einstellung|Auswahl

|*Export-Typ*
|Order Type

|*Format-Typ*
|Auftragspositionen

|*Format*
|Order

|====


[#50]
== Praxisbeispiel 1

simpler Katalog, keine Verknüpfungen, keine Besonderheiten

Angenommen du möchtest regelmäßig grundlegende Auftragsdaten aller Aufträge, die im Laufe eines Kalendermonats eingegangen sind, exportieren.
Welche Aufträge genau sollen exportiert werden? Wie sollen die Aufträge eingeschränkt werden, damit nicht alle exportiert werden? Das Einschränken ist empfohlen, sonst hohe Datenmengen und evtl. Daten, die gar nicht benötigt werden. Zielgerichtet vorgehen.  Welche Informationen sind wichtig für dich / benötigst du? Zum Beispiel:
Filter
- Zeitraum in Filtern einstellen (*Eingangsdatum*)
- *Auftragsherkunft* (um aufzuschlüsseln, welche Herkunft wieviele Aufträge generiert)
- und/oder Zahlungsart (um aufzuschlüsseln, welche Zahlungsart am häufigsten verwendet wird)

Welche Informationen sind relevant für mich? Welche Daten brauche ich, um Schlussfolgerungen ziehen zu können? Oder für die Ablage? Welche Daten brauche ich, um Aufträge auch später noch zuordnen zu können? Zum Beispiel:
- Auftrags-ID
- Auftragssummen, netto und brutto
- Zahlungsart
- Käufer:in (hier nur ID), evtl. speziell Lieferland

Diesen Katalog kann man grundlegend nutzen. Ließe sich erweitern um Auftragspositionen.
- Varianten-ID
- Menge
- Preis (EK?)


Instructions dazu? Oder in Schritte aufteilen? Tendiere zu Schritte

[# 100]
== Praxisbeispiel 2

Komplexer; Verknüpfungen, Auswahl (?), Besonderheiten; auf Ausweich-Datenfeld eingehen (z.B. Sprache)

Filter
- Auftragsstatus (z.B. nur Warenausgang gebucht)
-



Datenfelder
- Zahlungsbedingungen
- Auftragsposition verknüpft mit Lager?
- Käufer:in (Verknüpfung Vor- und Nachname)
- Referenzen und / oder Referenztyp
- Versanddienstleister (hier eingehen auf ID und Versanddienstleister-ID)
- Dokumente
