= Praxisbeipiele Kataloge für Aufträge und Auftragspositionen
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:description: Erfahre anhand von Praxisbeispielen, wie du dir einen Katalog für den Export von Aufträgen und Auftragspositionen erstellst.
:position: 100
:url: daten/daten-exportieren/katalog-auftraege
:id: OXKY6KE
:author: team-order-payment

Diese Handbuchseite führt Praxisbeispiele zum Erstellen eines Katalogs für den Export von Aufträgen und Auftragspositionen auf. Solltest du noch nicht vertraut sein mit den Katalogen, informiere dich zuerst im Handbuchkapitel <<daten/daten-exportieren/kataloge-verwalten#, Kataloge verwalten>>. Dort erhältst du alle benötigten Informationen, die du zum generellen Erstellen, Bearbeiten und Verwalten von Katalogen brauchst.

Das Katalogformat Aufträge umfasst sowohl Datenfelder für Auftragsdaten als auch für Auftragspositionsdaten. Je nach Arbeitsablauf kannst du dir also entweder getrennte Kataloge für den Export der jeweiligen Daten anlegen oder die Daten in einem großen Katalog zusammenstellen und exportieren. +
Du hast mit den Katalogen viele Gestaltungs- und Nutzungsmöglichkeiten. Überlege daher zuerst generell, wofür du die exportierten Daten nutzen möchtest und dann welche Daten du dafür benötigst und welche Zusammenstellung in Katalogen für dich sinnvoll ist. Du kannst zum Beispiel einen Katalog erstellen, um Auftragsdaten statistisch auszuwerten oder einen Katalog, in dem du alle Daten für dein Fulfillment zusammenfasst. Du entscheidest, wie die Kataloge aufgebaut sein sollen.

Im Folgenden geben wir Beispiele für Kataloge für den Export von Auftrags- und Auftragspositionsdaten. Die Beispiele zeigen Möglichkeiten auf, wie der Export von Auftragsdaten mit dem Katalog gestaltet werden kann. Du kannst bei Bedarf die Beispiele als Unterstützung für die Erstellung deiner Kataloge nutzen, bist aber in der Gestaltung deiner Kataloge frei.

Treffe die folgenden Einstellungen im Bereich <<daten/daten-exportieren/kataloge-verwalten#130, Format>>, wenn du einen neuen Katalog für den Export von Auftragsdaten erstellen möchtest:

[[table-format-settings]]
.Formateinstellungen Katalog für den Export von Aufträgen und Auftragspositionen
[cols="3,3"]
|====
|Einstellung|Auswahl

|*Export-Typ*
|Order Type

|*Format-Typ*
|Auftragspositionen

|*Format*
|Order

|====

[#50]
== Praxisbeispiel: Erster Katalog mit Auftragsdaten

Angenommen, du möchtest zur Auswertung einige grundlegende Auftragsdaten aller Aufträge, die im Laufe der letzten 14 Tage eingegangen sind, exportieren. +

[.discrete]
=== 1. Schritt: Welche Auftragsdaten brauche ich?

Überlege, welche Auftragsdaten für dich wichtig sind. Gehen wir davon aus, dass du erst mal nur die folgenden Auftragsdaten zur Auswertung brauchst:

- Auftrags-ID: Damit die Daten später noch zuzuordnen sind und ggf. auch erweitert werden können.
- Auftragsbeträge: Für eine Aufstellung von verschiedenen Auftragssummen. Überlege, welche Beträge für dich relevant sind, z.B. Brutto oder Netto. Für dieses Beispiel nehmen wir den Rechnungsbetrag.
- Lieferland: Um auszuwerten, wie viele Lieferungen in welches Land gehen.
- Zahlungsart: Um auszuwerten, welche Zahlungsarten gefragt sind.

Diese Liste lässt sich individuell anpassen und erweitern. Entscheide auch, welche Kombinationen von Informationen für dich relevant sind. Vielleicht ist es auch sinnvoll Daten zu gruppieren und in mehreren Katalogen anzulegen.

[.discrete]
=== 2. Schritt: Entsprechende Datenfelder hinzufügen

Füge die folgenden <<daten/daten-exportieren/kataloge-verwalten#160, Datenfelder>> hinzu, um die aufgelisteten Daten in einem Katalog zusammenzustellen. Du fügst ein Datenfeld hinzu, indem du daneben auf *Hinzufügen* (icon:add[set=material]) klickst. Speichere (icon:save[set=material]) danach den Katalog.

.Datenfelder:
* *Auftrag > Auftrags-ID*
* *Auftrag > Beträge > Rechnungsbetrag*
* *Auftrag > Lieferadresse*
* *Aufträge > Zahlungsart*

[TIP]
.Struktur der Datenfelder
====
Die Datenfelder (icon:order_return_create_edit[set=plenty]) sind thematisch in Ordnern gruppiert. In der ersten Ebene siehst du die Hauptordner. Wenn du einen Ordner öffnest werden entweder Datenfelder oder weitere Unterordner aufgelistet. Auch die Unterordner kannst du öffnen, um dir weitere Datenfelder anzeigen zu lassen. +
Beachte außerdem, dass du für manche Datenfelder nach dem Hinzufügen eine zusätzliche Auswahl treffen kannst. Dies siehst du an der Dropdown-Liste im hinzugefügten Datenfeld.
====

[.discrete]
=== 3. Schritt: Eingrenzung durch Filter

Überlege, welche Aufträge exportiert werden sollen und wie sich die Ergebnisse sinnvoll eingrenzen lassen. Dies empfiehlt sich allein schon, weil sonst sehr große Datenmengen entstehen und evtl. auch Daten im Export enthalten sind, die gar nicht benötigt werden. +
Für das Beispiel werden immer die Daten der letzten 14 Tage benötigt, wir brauchen also mindestens diesen Filter:

* *Erstellungsdatum* +
Füge den Filter über *Filter hinzufügen* hinzu und wähle dann *Letzte* aus der Dropdown-Liste aus. Gib die Anzahl der Tage, für das Beispiel 14, ein.

Auch die Filter lassen sich individuell erweitern. Geht es dir zum Beispiel nur um Aufträge, die bereits bezahlt sind, kannst du zusätzlich den Filter *Zahlungsstatus* und aus der Dropdown-Liste dann den Status *Bezahlt* wählen. Durch Hinzufügen von weiteren Filter werden die Ergebnisse eingegrenzt.
Speichere (icon:save[set=material]) den Katalog nach Setzen der Filter erneut.

[.discrete]
=== 4. Schritt: Katalog exportieren

Nachdem du alle Formateinstellungen vorgenommen sowie Datenfelder und Filter gesetzt hast, kann der Katalog exportiert werden. Vorher kannst du aber die <<daten/daten-exportieren/kataloge-verwalten#255, Vorschau>> nutzen, um deine Einstellungen zu überprüfen.

Wirf in diesem Zug auch noch mal einen Blick auf die <<daten/daten-exportieren/kataloge-verwalten#150, Exporteinstellungen>> deines Katalogs. Du kannst hier im Feld *Übertragung* wählen, wann der Export gestartet werden soll. Beachte dabei, dass Kataloge nach einem Export nur 15 Tage gespeichert werden. Beziehe dies ein, wenn du einen Katalog mehr als einmal verwenden möchtest. Plane den <<daten/daten-exportieren/kataloge-verwalten#260, Katalogexport>> entsprechend regelmäßig in deinen Arbeitsablauf ein.

[.discrete]
=== Bestehenden Katalog um Auftragspositionen erweitern

Wir haben nun einen ersten grundlegenden Katalog erstellt, der nutzbar ist. Nehmen wir an, du möchtest nun aber zusätzlich Auftragspositionsdaten exportieren. +
Du kannst Datenfelder und Filter eines bestehenden Katalogs einfach erweitern. Wenn du aber den ursprünglichen Katalog behalten und zusätzlich einen weiteren wie diesen aber mit mehr Datenfeldern haben möchtest, kannst du einen bestehenden Katalog kopieren und dann erweitern.

<<daten/daten-exportieren/kataloge-verwalten#190, Kopiere>> also den eben erstellten Katalog, damit wir die Kopie für das Beispiel erweitern können. +
Überlege dir anschließend, welche Daten zu Auftragspositionen für dich relevant sind. Im Beispiel wollen wir die bestehenden Daten erst mal nur durch weitere wenige grundlegende Informationen ergänzen. Du kannst dies aber individuell ausweiten.

- Artikel-ID und Varianten-ID = Um aufschlüsseln zu können, welche Artikel verkauft wurden.
- Menge = Um aufschlüsseln zu können, welche Mengen welcher Artikel (wird durch Artikel-ID abgefragt) verkauft wurden.

Füge also folgende Datenfelder hinzu:

* *Aufträge > Positionen > Artikel-ID*
* *Aufträge > Positionen > Varianten-ID*
* *Aufträge > Positionen > Menge*

Ändere bei Bedarf die <<daten/daten-exportieren/kataloge-verwalten#165, Reihenfolge der Datenfelder>>. Zudem kannst du auch die <<daten/daten-exportieren/kataloge-verwalten#162, Export Keys>> anpassen. Hast du als Format in den Exporteinstellungen JSON ausgewählt und änderst einen String eines Export Keys durch einen Punkt, ändert sich die Gruppierung der exportierten Daten. +
_Beispiel_:
Speichere (icon:save[set=material]) danach den Katalog.

Passe als nächsten Schritt die Filter an. Der Zeitraum, die letzten 14 Tage und damit der Filter *Eingangsdatum*, bleibt bestehen. Nehmen wir nun an, du hast vor Kurzem deine Verkaufskanäle erweitert und möchtest nun schauen, wie der neue Kanal sich so macht. Dann füge zusätzlich den Filter *Auftragsherkunft* hinzu und wähle dann die entsprechende Auftragsherkunft aus. Dadurch werden nur die gewählten Auftragsdaten der Aufträge der letzten 14 Tage mit dieser Auftragsherkunft exportiert. +
Auch die Filter kannst du individuell anpassen und noch weitere hinzufügen, wenn du die Ergebnisse weiter eingrenzen möchtest. Speichere (icon:save[set=material]) den Katalog, wenn du die Filtereinstellungen angepasst hast.

Hast du alle Änderungen in den Katalog eingepflegt und ihn gespeichert, kannst du mithilfe der <<daten/daten-exportieren/kataloge-verwalten#255, Vorschau>> wieder überprüfen, ob alles passt. Danach

[# 100]
== Praxisbeispiel 2

Komplexer; Verknüpfungen, Auswahl (?), Besonderheiten; auf Ausweich-Datenfeld eingehen (z.B. Sprache)

Filter
- Auftragsstatus (z.B. nur Warenausgang gebucht)
- *Auftragsherkunft* (um aufzuschlüsseln, welche Herkunft wieviele Aufträge generiert)



Datenfelder
- Zahlungsbedingungen
- Auftragsposition verknüpft mit Lager?
- Käufer:in (Verknüpfung Vor- und Nachname)
- Referenzen und / oder Referenztyp
- Versanddienstleister (hier eingehen auf ID und Versanddienstleister-ID)
- Dokumente
