= Praxisbeipiele Kataloge für Aufträge und Auftragspositionen
:lang: de
include::{includedir}/_header.adoc[]
:keywords:
:description: Erfahre anhand von Praxisbeispielen, wie du dir einen Katalog für den Export von Aufträgen und Auftragspositionen erstellst.
:position: 100
:url: daten/daten-exportieren/katalog-auftraege
:id: OXKY6KE
:author: team-order-payment

Diese Handbuchseite führt Praxisbeispiele zum Erstellen eines Katalogs für den Export von Aufträgen und Auftragspositionen auf. Solltest du noch nicht vertraut sein mit den Katalogen, informiere dich zuerst im Handbuchkapitel <<daten/daten-exportieren/kataloge-verwalten#, Kataloge verwalten>>. Dort erhältst du alle benötigten Informationen, die du zum generellen Erstellen, Bearbeiten und Verwalten von Katalogen brauchst.

Das Katalogformat Aufträge umfasst sowohl Datenfelder für Auftragsdaten als auch für Auftragspositionsdaten. Je nach Arbeitsablauf kannst du dir also entweder getrennte Kataloge für den Export der jeweiligen Daten anlegen oder die Daten in einem großen Katalog zusammenstellen und exportieren. +
Du hast mit den Katalogen viele Gestaltungs- und Nutzungsmöglichkeiten. Überlege daher zuerst generell, wofür du die exportierten Daten nutzen möchtest und dann welche Daten du dafür benötigst und welche Zusammenstellung in Katalogen für dich sinnvoll ist. Du kannst zum Beispiel einen Katalog erstellen, um Auftragsdaten statistisch auszuwerten oder einen Katalog, in dem du alle Daten für dein Fulfillment zusammenfasst. Du entscheidest, wie die Kataloge aufgebaut sein sollen.

Im Folgenden geben wir Beispiele für Kataloge für den Export von Auftrags- und Auftragspositionsdaten. Die Beispiele zeigen Möglichkeiten auf, wie der Export von Auftragsdaten mit dem Katalog gestaltet werden kann. Du kannst bei Bedarf die Beispiele als Unterstützung für die Erstellung deiner Kataloge nutzen, bist aber in der Gestaltung deiner Kataloge frei.

Treffe die folgenden Einstellungen im Bereich <<daten/daten-exportieren/kataloge-verwalten#130, Format>>, wenn du einen neuen Katalog für den Export von Auftragsdaten erstellen möchtest:

[[table-format-settings]]
.Formateinstellungen Katalog für den Export von Aufträgen und Auftragspositionen
[cols="3,3"]
|====
|Einstellung|Auswahl

|*Export-Typ*
|Order Type

|*Format-Typ*
|Auftragspositionen

|*Format*
|Order

|====

[#50]
== Praxisbeispiel: Export von grundlegenden Auftragsdaten

Angenommen, du möchtest zur Auswertung einige grundlegende Auftragsdaten aller Aufträge, die im Laufe der letzten 14 Tage eingegangen sind, exportieren.

[.discrete]
=== 1. Schritt: Welche Auftragsdaten brauche ich?

Überlege, welche Auftragsdaten für dich wichtig sind. Gehen wir davon aus, dass du erst mal nur die folgenden Auftragsdaten zur Auswertung brauchst:

- Auftrags-ID: Damit die Daten später noch zuzuordnen sind und ggf. auch erweitert werden können.
- Auftragsbeträge: Für eine Aufstellung von verschiedenen Auftragssummen. Überlege, welche Beträge für dich relevant sind, z.B. Brutto oder Netto. Für dieses Beispiel nehmen wir den Rechnungsbetrag.
- Lieferland: Um auszuwerten, wie viele Lieferungen in welches Land gehen.
- Zahlungsart: Um auszuwerten, welche Zahlungsarten gefragt sind.

Diese Liste lässt sich individuell anpassen und erweitern. Entscheide auch, welche Kombinationen von Informationen für dich relevant sind. Vielleicht ist es auch sinnvoll Daten zu gruppieren und in mehreren Katalogen anzulegen.

[.discrete]
=== 2. Schritt: Entsprechende Datenfelder hinzufügen

Füge die folgenden <<daten/daten-exportieren/kataloge-verwalten#160, Datenfelder>> hinzu, um die aufgelisteten Daten in einem Katalog zusammenzustellen. Du fügst ein Datenfeld hinzu, indem du daneben auf *Hinzufügen* (icon:add[set=material]) klickst. Speichere (icon:save[set=material]) danach den Katalog.

.Datenfelder:
* *Auftrag > Auftrags-ID*
* *Auftrag > Beträge > Rechnungsbetrag*
* *Auftrag > Lieferadresse*
* *Aufträge > Zahlungsart*

[TIP]
.Struktur der Datenfelder
====
Die Datenfelder (icon:order_return_create_edit[set=plenty]) sind thematisch in Ordnern gruppiert. In der ersten Ebene siehst du die Hauptordner. Wenn du einen Ordner öffnest werden entweder Datenfelder oder weitere Unterordner aufgelistet. Auch die Unterordner kannst du öffnen, um dir weitere Datenfelder anzeigen zu lassen. +
Beachte außerdem, dass du für manche Datenfelder nach dem Hinzufügen eine zusätzliche Auswahl treffen kannst. Dies siehst du an der Dropdown-Liste im hinzugefügten Datenfeld.
====

// Info export-Keys anpassen hier schon oder erst im anderen Beispiel?

[.discrete]
=== 3. Schritt: Eingrenzung durch Filter

Überlege, welche Aufträge exportiert werden sollen und wie sich die Ergebnisse sinnvoll eingrenzen lassen. Dies empfiehlt sich allein schon, weil sonst sehr große Datenmengen entstehen und evtl. auch Daten im Export enthalten sind, die gar nicht benötigt werden. +
Für das Beispiel werden immer die Daten der letzten 14 Tage benötigt, wir brauchen also mindestens diesen Filter:

* *Erstellungsdatum* +
Füge den Filter über *Filter hinzufügen* hinzu und wähle dann *Letzte* aus der Dropdown-Liste aus. Gib die Anzahl der Tage, für das Beispiel 14, ein.

Auch die Filter lassen sich individuell erweitern. Geht es dir zum Beispiel nur um Aufträge, die bereits bezahlt sind, kannst du zusätzlich den Filter *Zahlungsstatus* und aus der Dropdown-Liste dann den Status *Bezahlt* wählen. Durch Hinzufügen von weiteren Filter werden die Ergebnisse eingegrenzt.
Speichere (icon:save[set=material]) den Katalog nach Setzen der Filter erneut.

[.discrete]
=== 4. Schritt: Katalog exportieren

Nachdem du alle Formateinstellungen vorgenommen sowie Datenfelder und Filter gesetzt hast, kann der Katalog exportiert werden. Vorher kannst du aber die <<daten/daten-exportieren/kataloge-verwalten#255, Vorschau>> nutzen, um deine Einstellungen zu überprüfen.

Hier oder oben?
- Zeitplan
- manueller Export
- Katalog wird nur 15 Tage gespeichert


[.discrete]
=== Ausweitung um Auftragspositionen

Diesen Katalog kann man grundlegend nutzen. Ließe sich erweitern um Auftragspositionen.
- Varianten-ID
- Menge
- Preis (EK?)

[# 100]
== Praxisbeispiel 2

Komplexer; Verknüpfungen, Auswahl (?), Besonderheiten; auf Ausweich-Datenfeld eingehen (z.B. Sprache)

Filter
- Auftragsstatus (z.B. nur Warenausgang gebucht)
- *Auftragsherkunft* (um aufzuschlüsseln, welche Herkunft wieviele Aufträge generiert)



Datenfelder
- Zahlungsbedingungen
- Auftragsposition verknüpft mit Lager?
- Käufer:in (Verknüpfung Vor- und Nachname)
- Referenzen und / oder Referenztyp
- Versanddienstleister (hier eingehen auf ID und Versanddienstleister-ID)
- Dokumente
