= Multipacks, item bundles and sets
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Grouping variations, combining variations, combining products, combination offers, combined offers, Multipack, Multi-Pack, Multi-Packs, Multipacks, Item bundle, Item bundles, Bundle, Bundles, Kit, Gift set, Component, Components, Bundle component, Bundle components, Purchase price, Weight, Automatic calculation, Set, Sets, Item set, Item sets, Item type, From-price, From-prices, From price, From prices, Set price, Set component, Set components, Order quantity, Ceres
:description: Find out how to combine variations in plentymarkets to sell them in bundles.
:position: 20
:url: item/use-cases/combining-products
:id: NXZCPXN
:author: team-item

plentymarkets offers a variety of ways to combine products and sell them as a single unit.
<<table-combining-products>> compares the possibilities and uses examples to illustrate them.

[TIP]
.Are you familiar with how to manage items?
====
This page assumes that you already have <<item/introduction#, basic knowledge of item management>> in plentymarkets.
For example, it assumes that you:

* know the <<item/introduction/structure#, difference between items and variations>>.
* have already configured a few <<item/settings#, preparatory settings>> in your system.
For example, that you’ve already created a <<item/settings/categories#, category structure>>, set up <<fulfilment/preparing-the-shipment#1000, shipping profiles>> for your items, etc.
====

[[table-combining-products]]
.Combining products and selling them as a single unit
[cols="1,5,1"]
|====
|Type |Explanation |Item type

|<<#1000, Multipack>>
a|*_Example_*: 1 bottle of water, a package containing 6 bottles and a package containing 12 bottles.


*_Technical specifications_*:

* Multipacks are different quantities of _the same variation_.
* The main variation is the _smallest sales unit_ of the product, e.g. 1 bottle.
* All of the other variations are _combinations_ of this smallest sales unit, e.g. 6 or 12 bottles.
* Stock is managed for the main variation only.
|Multipack

|<<#2000, Bundle>>
a|*_Example_*: A beard care kit consisting of scissors, a brush, beard oil and beard wax.

*_Technical specifications_*:

* Bundles consist of _different variations_, which are grouped together and sold at a bundle price.
* The bundle can only be purchased as a whole. The individual components cannot be selected.
* It’s possible to combine variations with _different tax rates_ together in one bundle.
* It’s also possible to make the bundle price cheaper than the sum of all the individual prices.
|Default

|<<#3000, Set>>
a|*_Example_*: A football uniform composed of a jersey, shorts and socks. The end customer puts his own uniform together by selecting the appropriate size and colour for each of the three components.

*_Technical specifications_*:

* Sets consist of _multiple items_ (jersey, shorts, socks).
* While placing an order, the end customer chooses the appropriate variation (size, colour) for each item.
* The main variation is virtual. This means that the main variation cannot be sold.

*_Note:_* Sets are still being developed.
Starting with link:https://marketplace.plentymarkets.com/en/plugins/sales/online-shops/ceres_4697[Ceres 5]{nbsp}icon:external-link[], it will be possible to sell item sets in the online store. However, it will _not be possible_ to sell item sets on marketplaces like Amazon or eBay.
|Set
|====


[#1000]
== Multipacks

For *Multipack* items, the main variation is the smallest sales unit of the product. All other variations of the item are combinations of this smallest sales unit. Stock is managed for the main variation only. All variations of the item have the same attributes. That means that customers cannot select between different colours or other characteristics of the product. In the online store, customers select the variation with the number of products they want to buy.

[#1100]
=== Creating a Multipack item

Just like when you create *Default* items, a main variation is always created when a new multipack item is created. This main variation is linked permanently to the *Multipack* item and can only be created or deleted at the same time as the item itself. This main variation itself is the smallest sales unit of the product.

[.instruction]
Creating a Multipack item:

. Go to *Item » Edit item*.
. Click on *New*. +
→ The *New item* tab opens.
. Select the type *Multipack*.
. Carry out the additional settings. Note <<table-create-multipack>>.
. *Save* the settings. +
→ The *Multipack* item is created. +
→ The main variation opens in a new tab.

[TIP]
.Displaying new *Multipack* items in the item overview
====
The new *Multipack* item is not active. To display recently created items in the item overview in the *Item » Edit item* menu, select the *ALL* option for the *Active* filter in the search area. Then click on *Search*. Learn how to activate items and variations for the online store in the <<item/managing-items#180, Setting the availability>> chapter.
====

[[table-create-multipack]]
.Creating a Multipack item
[cols="1,3"]
|====
|Setting |Explanation

2+|*Item data*

|*Type*
|Select the item type *Multipack*. +
*Default* = Creates a *Default* item with main variation. +
*Set* = Creates a *Set* item. +
*Multipack* = Creates a *Multipack* item.

|*ID*
|The item ID is a unique, consecutive number that is used to identify each item in plentymarkets. If you leave this field empty, plentymarkets automatically assigns the next available ID.

|*Name*
|Enter a name for the multipack. The name is a mandatory entry. Learn how to change the name in the <<item/managing-items#50, Entering item texts>> chapter.

2+|*Variation » Category link*

|Category selection
|Select the category in which the multipack is to be published. Alternatively, click on *New category* to create a new category.
|====

[#1300]
=== Editing Multipack items

Now that you have created the *Multipack* item, you can refine the settings for the multipack. These settings are identical to the settings for <<item/managing-items#30, Default items>>.

[#1400]
=== Creating a multipack variation

A main variation is always created when a new *Multipack* item is created. The main variation is linked to an item. The main variation cannot be deleted. This main variation is the smallest sales unit of the product. All other variations of the item are this smallest sales unit multiplied by x. The stock of all variations is managed in the main variation only. The *Stock* tab of all other variations of the item only shows the theoretical stock. When the stock level of the main variation changes, the stock for all other variations of the item is recalculated.

[.instruction]
Creating a multipack variation:

. Go to *Item » Edit item*.
. Open the *Multipack* item.
. Open the *Variations* tab.
. Click on *New*. +
→ The *Create new variations* window opens.
. As the content, enter a quantity for the main variation. +
*_Tip:_* The variation’s units and the attributes cannot be changed.
. Click on *Create variation*. +
→ The variation is created. +
→ The variation is displayed in the variation overview.

The settings of the variations are edited in the same way as <<item/managin-items#170, Default variations>>. However, note the following limitations for multipack variations:

* Deactivate the inheritance function for the sales price and save a price.
* The information shown in the *Stock* tab cannot be edited. Stock is managed for the main variation only.

[#2000]
== Item bundles

An item bundle consists of multiple products. The bundle price of an item bundle may be lower than the sum of the individual prices. Go to *Item » Edit item* and use the *Bundle* filter to search for bundles.

[#2100]
=== Creating an item bundle

In the *Bundle* tab of a *Default* item, you create an item bundle which consists of multiple components, the basic items. If you add further variations to the opened item, you create a bundle. The bundle's components are displayed in the *Bundle components* tab where they can be edited or deleted.

[.instruction]
Creating an item bundle:

. Go to *Item » Edit item*.
. Click on *New*. +
→ The *New item* tab opens.
. Select the type *Default*.
. Enter a name.
. Enter the content.
. Select a category.
. Carry out additional settings as necessary. Pay attention to the information given for *Default* items on the <<item/managing-items#table-create-default-items, Managing items>> page of the manual.
. *Save* the settings. +
→ The item is created. +
→ The main variation opens in a new tab.
. Open the variation.
. Open the *Bundle » Add variation* tab.
. Place check marks next to the variations you want to add as bundle components.
. Click on *Add variation*. +
→ The components are added to the item bundle and displayed in the *Bundle components* tab.

Then link a sales price with the item bundle and enter a price. Learn how to link sales prices in the <<item/managing-items#240, Linking sales prices>> chapter. When processing the order, only the bundle price and the bundle components are shown. No individual prices are shown.

[NOTE]
.Using an existing item as the bundle item
====
Instead of creating a new bundle item, you can also use an existing item and add bundle components to this item. Note that the bundle item to which bundle components are added must not have stock.
====

[#2200]
=== Editing or deleting bundle components

In the *Bundle components* tab, you can change the quantity of the item bundle's variations, view the variations' net stock and delete bundle components that are no longer required.

[.instruction]
Deleting a bundle component:

. Go to *Item » Edit item*.
. Select *Yes* for the *Bundle* filter.
. Click on *Search*. +
→ All bundle items found are displayed in the overview.
. Open the bundle item.
. Open the variation.
. Open the *Bundle » Bundle components* tab.
. Place check marks next to the bundle components you want to delete.
. Click on *Delete bundle components*. +
→ The bundle components are deleted and no longer available in the item bundle.

[#2300]
=== Creating multiple bundles in one item

Item variations also can be bundles with multiple components. In this way, you can design very complex item bundles that meet your individual needs.

*_Example of bundle variations_*: Let's assume that you want to sell a bundle consisting of a hand towel and a larger bath towel. You also want to offer this bundle in different colours. To do so, the following steps are necessary:

* <<item/managing-items#400, Create an attribute>> with the colours you want to offer, for example red and blue.
* <<item/managing-items#20, Create an item>> that will serve as the bundle item, for example towel bundle.
* <<item/managing-items#160, Create variations>> of the bundle item and link the attribute values.
* Create items for the bundle components, for example hand towel and bath towel.
* Create variations of the bundle components, for example red hand towel, blue hand towel etc.
* Add the <<#2100, bundle components>> to the variations of the item bundle.

In doing so, you can sell the item *towel bundle* in your online store and offer the bundle colours *red* and *blue*.

[#2400]
=== Setting the stock of item bundles

The stock of a bundle depends on the bundle component with the lowest stock. The stock of this bundle component is displayed in the *Net stock* column of the item overview in the *Item » Edit item* menu. The bundle item itself must not have stock. In the *Stock* tab of a bundle component, you manage the stock, book incoming items, make stock corrections and view supplies as well as item movements. For further information, refer to the <<stock-management#, Stock management>> page of the manual.

[#2500]
=== Calculating the weight and purchase price

An item bundle is made up of various components. Each component has its own key figures, such as a <<item/managing-items#270, weight>> and a <<item/managing-items#280, purchase price>>. But how do these key figures come together for the entire bundle?

You could enter a weight and purchase price for the entire bundle as a whole. But there’s also a way to have plentymarkets automatically calculate these figures for you. This method is described below.

[.instruction]
Automatically calculating the weight and purchase price:

. Go to *Item » Edit item*.
. Select *Yes* for the *Bundle* filter.
. Click on *Search*. +
→ All item bundles found are displayed in the overview.
. Open the item bundle. +
→ The *Settings* tab opens.
. Choose the appropriate settings in the *Bundle* area. Note <<table-calculate-weight-purchase-price>>.
. *Save* the settings.
. <<basics/working-with-plentymarkets/general-functions#70, Reload>> the item bundle. +
→ The key figures will be calculated automatically. This calculation is based on the data entered for each individual component.


[[table-calculate-weight-purchase-price]]
.Automatically calculating the weight and purchase price
[cols="1,2"]
|====
|Setting |Explanation

|*Automatically calculate from bundle components: Net purchase price*
|The net purchase price will automatically be calculated. The calculation is based on the individual components. +
Once you have saved the changes and reloaded the menu, the field <<item/managing-items#280, *Net purchase price*>> will be greyed out in the *Costs* area on the right.

|*Automatically calculate from bundle components: Moving average purchase price (net)*
|The moving average purchase price (net) will automatically be calculated. The calculation is based on the individual components. +
Once you have saved the changes and reloaded the menu, the field <<item/managing-items#280, *Moving average purchase price (net)*>> will be greyed out in the *Costs* area on the right.

|*Automatically calculate from bundle components: Net weight*
|The net weight will automatically be calculated. The calculation is based on the individual components. +
Once you have saved the changes and reloaded the menu, the field <<item/managing-items#270, *Net weight*>> will be greyed out in the *Dimensions* area on the right.

|*Automatically calculate from bundle components: Gross weight*
|The gross weight will automatically be calculated. The calculation is based on the individual components. +
Once you have saved the changes and reloaded the menu, the field <<item/managing-items#270, *Gross weight*>> will be greyed out in the *Dimensions* area on the right.
|====

[TIP]
.Modifying several item bundles at once
====
Use the <<item/managing-items#330, variation group function or the batch processing function>> to calculate the weight and purchase price for multiple item bundles at the same time.
====

[TIP]
.Using automatic calculation by default
====
Do you normally want the weight and purchase price to be calculated automatically? Perhaps you only have a few items that should be excluded from the automatic calculation. No problem! Open the menu *Setup » Item » Settings* and specify which key figures should be calculated automatically. Use the options *Bundle automatic for gross weight*, *Bundle automatic for net weight*, *Bundle automatic for purchase prices* and *Bundle automatic for moving average purchase prices* to do so.
====

[TIP]
.Prefer to enter key figures by hand?
====
Do you want to enter the weight and purchase price for item bundles yourself? Do not check any of the boxes in the *Bundle* area, if you’d prefer to enter the data manually. If none of the boxes are checked, then the key figures for individual components won’t have any influence on the key figures for the item bundle.
====


[#3000]
== Sets

Imagine you sell football uniforms, consisting of jerseys, shorts and socks.
Wouldn’t it be great if end customers could put together their own uniforms?
In other words, if they could choose the appropriate colour and size for each component?
Item sets make it possible!

A set consists of multiple items (jersey, shorts, socks).
While placing an order, the end customer chooses the appropriate variation (colour, size) for each item.
It might help you to sketch out the items and variations that will be included in your set.

[[table-set-mind-map]]
//.Which items and variations should be included in the set?
[cols="1,^,^,^", stripes=none]
|====

|*Set*
3+|Football uniform

|*Items in the set*
|Jersey
|Shorts
|Socks

|*Variations per item*
a|* S and red
* L and red
* S and blue
* L and blue
a|* S and white
* L and white
* S and black
* L and black
a|* S and blue
* L and blue
* S and white
* L and white
|====

[IMPORTANT]
.Set function is only intended for the Ceres 5 store
====
It's possible to sell item sets in the link:https://marketplace.plentymarkets.com/en/plugins/sales/online-shops/ceres_4697[Ceres 5]{nbsp}icon:external-link[] store. Lower versions of Ceres do not support the set function.

The set function is only intended for the online store.
It's not possible to sell item sets on marketplaces like Amazon and eBay.
====

[#3100]
=== How do set prices work?

The unique thing about sets is that you don't know in advance exactly how the end customer will combine the variations. Therefore, it wouldn’t make sense to save fixed prices for sets.
Instead, plentymarkets calculates the price of the _cheapest possible combination_ and saves this information for the set.
This minimum price can be displayed in the online store and in the back end. For example: "Available from € 99.99".

plentymarkets regularly checks the prices of all the variations in the set and calculates the cheapest possible combination.
plentymarkets checks the prices:

* when you <<#3700, add a component to a set>>
* when you <<#3700, remove a component from a set>>
* when you <<#3900, manually update the "from-price">>
* every night

[#3200]
[discrete]
==== Preparing set prices

First, <<item/settings/prices#200, create a sales price>> for sets.
While doing so, specify that the type is a *Set price*.

Then <<item/settings/prices#900, link this sales price>> to all of the set components and enter a monetary price for each component.
Note that the set components are normal variations.

[TIP]
.Can items be cheaper if they’re purchased together as a set?
====
It’s possible to make a set cheaper than the sum of its components.
There are two ways to do this:

* On the one hand, you could save lower monetary prices for the set sales price than for the normal sales price.
* On the other hand, you could <<#4000, enter a percentage of discount>> that applies to the entire set.
====

[#3300]
=== Creating new sets

Have you already decided <<#3000, which items and variations should be included in the set>>?
Have you created a <<#3100, sales price especially for sets>>?
Then you’re ready to start creating sets!

//you can either create sets manually or you can <<import them with elasticsync>>
//as soon as the info about elasticsync is added, then remove the instruction heading and make the subhead visible instead - also use a subhead then for elasticsync

[#3400]
//[discrete]
//==== Manually creating an item set

[.instruction]
Manually creating an item set:

. Go to *Item » Edit item*.
. Click on icon:plus[role="green"] *New*. +
→ The *New item* tab opens.
. Carry out the settings for the set. Note <<table-create-set-items>>.
.. Select the type *Set*.
.. Enter a name for the item set.
.. Which category should the set appear in? Choose the category.
. *Save* (icon:save[role="green"]) the settings. +
→ The item set is created. +
→ The main variation appears in a new tab and <<#3500, can be edited further>>.

[TIP]
.What’s the main variation for?
====
A main variation is automatically created when you create a new set.
This main variation is linked to the set. It can only be created or deleted together with the set.
The main variation:

* is purely virtual and does not correspond to a physical product.
* serves as a data container, which you add components to.
* helps you manage settings for the entire set.
====

[[table-create-set-items]]
.Creating an item set
[cols="1,3"]
|====
|Setting |Explanation

2+|*Area: Item data*

|*Type*
a|Select the type *Set*. Lots of settings disappear when you choose this option. Now the menu only includes settings that are relevant to sets.

The other options in the drop-down list are intended for other situations:

* *Default* = Creates a <<item/managing-items#20, normal item>> or an <<#2000, item bundle>>.
* *Set* = Creates an item set.
* *Multipack* = Creates a <<#1000, multipack item>>.

//|*ID*
//|The item ID is a unique, consecutive number that is used to identify each item in plentymarkets. If you leave this field empty, plentymarkets automatically assigns the next available ID.

|*Name*
|Enter a name for the set. The name is a mandatory entry.
It will still be possible to change the name after you’ve created the set.

2+|*Area: Variation » Category link*

|
|Which <<item/settings/categories#, category>> should the set appear in? Choose the category.
Alternatively, click on *New category* to simultaneously create a new category and sort the set into this category.
|====

[#3500]
=== Editing existing sets

[#3600]
==== Searching for sets

<<#3300, While creating a new item set>>, the main variation is automatically opened in a new tab.
But where do you find the sets that you already created a while ago?

[.instruction]
Searching for and opening existing sets:

. Go to *Item » Edit item*.
. Look at the filters on the left.
.. Set the filter *Type* to *Set*.
.. Set the filter *Active* to *ALL*.
. Click on *Search* (icon:search[role="blue"]). +
→ The sets that are found will be displayed in an overview on the right.
. Click on a set to open it.

[#3700]
==== Adding or removing components

Have you already decided <<#3000, which items should be included in the set>>?
The items that you add to the set are regular items. In other words, they are items of the type *Default*.

* If you add an _item with multiple variations_ to the set, then your customers will be able to choose which variation they want to buy.
* If you add an _item without any variations_ to the set, i.e. an item that only consists of a main variation, then your customers won’t be able to select anything.

[.instruction]
Adding components to the set:

. <<#3600, Search for and open the appropriate item set>>.
. Click on the tab *Set » Add item(s)*.
. <<item/introduction/search#100, Search for the items>> that you want to add to the set. +
→ The items are listed.
. Select the items (icon:check-square[role="blue"]) you want to add to the set.
. Click on *Add item(s)*. +
→ The items will be added to the set. They are now listed in the *Settings* tab.

[TIP]
.Removing components again
====
Components that have already been added to the set are listed in the tab *Set » Settings*.
Here you can also remove the components that should no longer be part of the set.
Select the items (icon:check-square[role="blue"]) that you want to remove from the set and click on icon:minus-circle[role="red"] *Delete component*.
====

[#3800]
==== Managing the stock

The stock of a set depends on the set's variation with the lowest stock. The stock of this variation is displayed in the *Net stock* column of the item overview in the *Item » Edit item* menu. You cannot manage any stock information for the *Set* item itself. Instead, stock is managed in the *Stock* tab of the set components.
For further information about managing stock, refer to the <<stock-management#, Stock management>> chapter.

[#3900]
==== Optional: Manually updating the “from-price”

plentymarkets regularly checks the prices of all the variations in the set and calculates the cheapest possible combination.
plentymarkets checks the prices whenever a component is added to a set or removed from a set, as well as every night.
But you can also manually update the “from-price” at any time.

[.instruction]
Manually updating the “from-price”:

. <<#3600, Search for and open the appropriate item set>>.
. Click on the tab *Variation ID » Settings*.
. Click on the update symbol (icon:undo[role="darkGrey"]) within the *Sales prices* area.

[TIP]
.Updating the "from-price" for several items at once
====
Use the <<item/managing-items#155, item group function or batch processing>> to update the "from-price" for multiple items at once.
Do so by selecting the option *Update price from in sets* (icon:check-square[role="blue"]). This option is found in the area *Procedures*.
====

[#4000]
==== Optional: Granting discounts

By default, the price of an item set is equivalent to the sum of the individual prices of all set components. However, you can offer a discount in % on the total price of the set.

[.instruction]
Saving a discount for an item set:

. <<#3600, Search for and open the appropriate item set>>.
. Click on the tab *Set » Settings*.
. Enter a percentage into the *Discount* field. The total price will be discounted by this percent.
. *Save* (icon:save[role="green"]) the settings. +
→ The discount is applied.

[#4100]
==== Optional: Specifying the minimum or maximum order quantity

Let’s stick with the <<#3000, example above>> and assume that you sell football uniforms, consisting of a jersey, shorts and socks.
But now let’s assume that _you only want to sell the set to entire football teams_. In other words: you only want to sell the set to someone who is willing to buy at least 10 jerseys, shorts and socks at once.
In this case, you’re dealing with a _minimum order quantity_.

Each player should be able to choose their own size and colour.
It doesn’t matter which variation the customer chooses. It’s only important that the customer orders an acceptable number of each item.

[.instruction]
Defining permissible quantities for set components:

. <<#3600, Search for and open the appropriate item set>>.
. Click on the tab *Set » Settings*. +
→ The set components are listed.
. In the column *Activate quantity selection in shop*, select all of the components (icon:check-square[role="blue"]) that should be limited to a certain quantity. +
→ The fields will no longer be greyed out.
. Enter the maximum and minimum order quantities for each component.
. *Save* (icon:save[role="green"]) the settings.

//info-box: was macht man (was trägt man ein) wenn man nur bei 1 der Bestandteile eine Mindestbestellmenge hinterlegen will? Was macht man wenn man nur eine Mindestbestellmenge aber keine Maximalbestellmenge haben will?
////
=== Creating and managing item sets with ElasticSync

==== Importing sets with ElasticSync

==== Adding or removing components with ElasticSync

==== Editing further settings with ElasticSync
////

[#4200]
==== Settings in the remaining tabs

This page only describes the functions that apply specifically to item sets.
But there are lots of other settings and options that you can also configure in the data record.
For example, you can:

* save <<item/managing-items#40, global information>> in the data record
* <<item/managing-items#300, link the item set to categories>>
* save <<item/online-store/cross-selling#, cross-selling links>> to other items
* generate <<item/settings/barcodes#, labels and barcodes>>
* save <<item/managing-items#50, descriptive texts>> or <<item/managing-items#150, tags>>
* etc.

These settings correspond to the same ones available for regular items, e.g. items of the type *Default*.
You can find explanations of these settings on the <<item/managing-items#, page about manually creating default items>>.

////
[#4300]
=== What will happen to sets that were already created?

Did you create item sets before link:https://marketplace.plentymarkets.com/en/plugins/sales/online-shops/ceres_4697[Ceres 5]{nbsp}icon:external-link[] was released?
If so, then your previously created sets will be _migrated_.

*_Background_*: While developing the set function, we had to modify or remove a few options from the item data record.
Of course, your old sets should match these new changes too.
Here are the most important changes:

* Stock was removed
* Automatic stock functions were removed
* Prices linked to sets were removed and replaced by “from-prices” <<#3900, as described above>>
* Bundles were removed from sets
* Sets were removed from bundles
////

[#4400]
=== Displaying item sets in the online store

//fix the link once Franz gives you the URL

Have you worked your way through the instructions on this page and finished configuring sets in your plentymarkets system? Congratulations! Now you’re ready to <<online-store#, display the sets in your online store>>.
