= Give-aways
:lang: en
include::{includedir}/_header.adoc[]
:description: Learn how to add free give-aways or promotional items to an order.
:url: item/use-cases/give-aways
:icons: font
:position: 20
:docinfodir: /workspace/manual-adoc
:docinfo1:
:table-event-procedure: <<table-event-give-away>>

Use give-aways to generate more revenue in your online store by motivating your customers to buy more items and more frequently. The basic idea is simple: You offer customers a free, give-away item if they spend a certain amount of money in your store. Instead of adding these give-aways to each order manually, you can use an <<automation/event-procedures#, event procedure>> to automate this process.

This video offers you an introduction to the topic:

.Adding give-aways to an order
video::124509345[vimeo]

You can also add promotional items that aren’t sold in your online store. To do so, set the variation to *invisible* and then assign it to an invisible category, i.e. a category that is not activated for the online store.

include::../../_includes/textblocks/instructions/EA.adoc[]

[[table-event-give-away]]
.Event procedure for give-aways
[cols="1,2,2"]
|====
|Setting |Option |Selection

|**Event**
|**Order generation > New order**
|

|**Filter 1**
|**Order > Order type**
|**Order**

|**Filter 2**
|**Value of items (gross)**
|Select operator and enter value of items. +
*_Example:_* Operator *>=*, Value of items *50.00* = The variation will be added if the total item value is 50 GBP or more

|*Procedure*
|*Item > Add variation*
|Enter variation ID.
|====

[TIP]
.Tip: Bonus item scale
====
Use more than one event procedure to offer a bonus item scale. This allows you to offer different variations depending on the value of items customers buy. In the first event procedure, for example set the item value filter to *&gt;=  100.00 GBP* and *&lt; 200.00 GBP*. In the second event procedure, set an item value filter of *&gt;=  200 GBP* and select a different, more attractive variation.
====
