= Fehlermeldung: Request is throttled
:lang: de
:keywords: Amazon, Prime, Auftragsablauf
:position: 40

[NOTE]
====
Dieses Best Practice behandelt das auftretende Problem der Fehlermeldung: “Request is throttled” und dessen Lösung.
====

== Was bedeutet “Request is throttled”?

Für jede sogenannte “Operation” (Auftragsimport, Versandbestätigungen, Bestandsübermittlung/en usw.) existieren bei Amazon Limits für Anfragen (Maximum Request quota), welche, wenn diese überschritten werden, zu einer “Sperrung” der Operation führen. Weitere Anfragen werden von Amazon verworfen. Erst nach einer gewissen Zeit werden nach und nach (The Leaky Bucket Algorithm) wieder Kapazitäten dieser Operation zur Verfügung gestellt und die Übertragung ist erneut möglich.

Wer die genaue Funktionsweise noch einmal nachlesen möchte, kann dies im Englischen unter link:http://docs.developer.amazonservices.com/en_DE/dev_guide/DG_Throttling.html[Throttling: Limits to how often you can submit requests^] tun.

==  Hauptsächliche Ursache des Problems:

Dieses Problem tritt häufig auf, da aufgrund einer Konfiguration im plentymarkets System bei der Nutzung eines europäischen Verkäuferkontos bei Amazon zu viele Anfragen dieses Amazon-Kontos gesendet werden.

*Konkret:*

Unter *System » Märkte » Amazon » Einstellungen* wurden mehrere Amazon-Konten für unterschiedliche Plattformen hinterlegt, welche jedoch alle dasselbe europäische Verkäuferkonto “anzielen”. Diese Konten haben immer die gleiche Verkäufer-ID. In jedem / mehreren dieser Konten wurden diverse “Operationen” aktiviert.

Amazon-Plattformen, die meist zu einem europäischen Verkäuferkonto zusammengefasst sind (Stand 15.05.2017):

- Amazon.de , Amazon.fr, Amazon.it, Amazon.es, Amazon.co.uk

[IMPORTANT]
====
Es kann ebenfalls zu diesem Problem kommen, wenn ihr weitere externe Programme benutzt, welche auf euer Amazon-Konto zugreifen und dieses in Kombination mit plentymarkets “überfluten”.
====

== Lösung des Problems:

Bei solch einem europäischen Amazon-Verkäuferkonto ist es sinnvoll, wenn ihr in nur einem in plentymarkets hinterlegten Konto (*System » Märkte » Amazon » Einstellungen*) diverse “Operationen” aktiviert, da diese sonst für jedes in plentymarkets hinterlegtes Konto, welches zu dieser Verkäufer-ID gehört, die Daten zusätzlich übermitteln.

[TIP]
.Operationen, welche nicht “doppelt” / “mehrfach” aktiviert werden sollten und häufig zum oben genannten Fehler führen, sind:
====
- Auftragsimport
- Bestandsabgleich
- Bestandsänderungen
====

*P.S.:* Bei einem Konto für Amazon.com handelt es sich selbstverständlich nicht um eine Plattform eines europäischen Verkäuferkontos.
