= Fehlermeldung: Request is throttled
:lang: de
:keywords: Amazon, Prime, Auftragsablauf
:position: 40

[NOTE]
====
Dieser Beitrag behandelt dass auftretende Problem der Fehlermeldung : “Request is throttled” und dessen Lösung.
====

1. Was bedeutet “Request ist throttled” ?

2. Hauptsächliche Ursache/n des Problems

3. Lösung des Problems



1. **Was bedeutet “Request ist throttled” ?**

Für jede sogenannte “Operation” (Auftragsimport, Versandbestätigungen, Bestandsübermittlung/en usw.) existieren Anfragen Limits (Maximum Request quota) bei Amazon, welche, wenn diese überschritten werden, zu einer “Sperrung” der Operation führen. Weitere Anfragen werden von Amazon verworfen. Erst nach einer gewissen Zeit werden nach und nach (The Leaky Bucket Algorithm) wieder Kapazitäten dieser Operation zur Verfügung gestellt und die Übertragung ist erneut möglich.

Wer die genau Funktionsweise noch einmal nachlesen möchte kann dies im englischen unter << http://docs.developer.amazonservices.com/en_DE/dev_guide/DG_Throttling.html, Throttling: Limits to how often you can submit requests>>  tun.

2.  Hauptsächliche Ursache des Problems :

Dieses Problem tritt häufig auf, da aufgrund einer Konfiguration im plentymarkets-System bei der Nutzung eines europäischen Verkäuferkontos bei Amazon zuviele Anfragen dieses Amazon-Konto gesendet werden.

**Konkret:**

Unter Einstellungen » Märkte » Amazon » Grundeinstellungen wurden mehrere Amazon-Konten für unterschiedliche Plattformen hinterlegt, welche jedoch alle dasselbe europäische Verkäuferkonto “anzielen”. Diese Konten haben immer die gleiche Verkäufer-ID. In jedem/ mehreren dieser Konten wurden diverse “Operationen” aktiviert.

Amazon-Plattformen die meist zu einem europäischen Verkäuferkonto zusammengefasst sind (Stand 15.05.2017) :

Amazon.de , Amazon.fr, Amazon.it, Amazon.es, Amazon.co.uk
[IMPORTANT]
Es kann ebenfalls zu diesem Problem kommen, wenn ihr weitere externe Programme benutzt, welche auf
euer Amazon-Konto zugreifen und dieses in Kombination mit plentymarkets “überfluten”.
====

3. **Lösung des Problems :**

Bei solch einem europäischen Amazon-Verkäuferkonto ist es sinnvoll, wenn ihr in nur einem in
plentymarkets hinterlegten Konto (Einstellungen » Märkte » Amazon » Grundeinstellungen) diverse “Operationen” aktiviert, da diese sonst pro in plentymarkets hinterlegtem Konto, welches zu dieser Verkäufer-ID gehört, die Daten zusätzlich übermittelt.
[TIP]
.Operationen welche nicht “doppelt” / “mehrfach” aktiviert werden sollten und häufig zum oben genannten Fehler führen sind :
====
Auftragsimport
Versandbestätigung
Bestandsabgleich
Bestandsänderungen
====
**P.S.:** Bei einem Konto für Amazon.com handelt es sich selbstverständlich nicht um eine Plattform eines europäischen Verkäuferkonto.
