= Splitting reorders into work steps
:lang: en
include::{includedir}/_header.adoc[]
:position: 10
:url: stock-management/managing-reorders/splitting-reorders-into-work-steps

Connect your ticket system to reorders and build work steps for reorders.
You will first need to create a ticket template and then you can create work steps within the template.
You can add up to 30 work steps per template.
The ticket itselfs allows you to record the communication and the progress during a work step. Furthermore you can involve other users in the work step.
Once you have completed all of the steps, you can submit your order.

[IMPORTANT]
.**Example: When is it useful to create work steps?**
====
You need to create a **pattern** for custom-made shoes that are ordered directly from a manufacturer. Creating the pattern is the 1st **work step** (see the explanation of the work steps below). The pattern will be used to calculate the **cost of materials**. This is the 2nd work step. Further work steps are also created for the rest of the process and time periods are specified for them. The order will not be placed until all of the steps have been completed.
====

[#100]
== Creating a template that contains work steps

First you will learn how to create a template and then you will learn to set up work steps.

[#200]
=== Creating a template

Proceed as described below to create a new template.

[.instruction]
Setting up the template:

. Go to **System » System settings » Stock » Reorder management » Templates**.
. Click on **New Template**. +
→ A new **window** will open.
. Enter a **name** for the template.
. **Save** the settings. +
→ The template will be given an ID and will be added to the selection available in the **Templates** tab.

[#300]
=== Adding work steps to a template

In this menu, you can create up to **30 work steps** per template.
You can then use the work steps to generate tickets for a reorder.
The **Ticket** tab allows you to do so. It is located in the editing window of a reorder.

In order to create a work step, proceed as described below.

[.instruction]
Creating a work step:

. Go to **System » System settings » Stock » Reorder management » Templates**.
. Click on a **template** to open it.
. Click on the **New step** button. +
→ A new **window** will open.
. Carry out the **settings** as desired. Pay attention to the information given in table 1.
. **Save** the settings.

.settings for templates
[cols="1,3"]
|====
|Setting |Explanation

|**Title**
|Enter a title for a work step. +
You can extend the title by attaching either a **suffix** or adding a **prefix**. You can also use both. The settings can help you recognize which **order**, **customer** or reorder the work step belongs to.

|**Suffix**
|Select between the options **Reorder ID**, **Order date** and **Customer name**.

|**Prefix**
|Select between the options **Reorder ID**, **Order date** and **Customer name**.

|**Position**
|Select a prosition for each step. The position defines the correct order of the work steps.

|**Deadline**
|Enter a period of days. This will be used to calculate the deadline for completing the work step.

|**Owner**
|Here you can see all of the users who are authorized for the ticket system. Select an owner for the work step. The owner will be added automatically to tickets. However, you can add further owners in the ticket.

|**Role**
|Select the role of the owner. Go to **System » System settings » CRM » Ticket system » Settings** to create roles for the ticket system. These are not the same as user roles.

|**Type**
|Select a type. Go to **System » System settings » CRM » Ticket system » Settings** to create ticket types.

|**Status**
|Select a status. Go to **System » System settings » CRM » Ticket system » Settings** to create statuses for tickets. You need to create ticket statuses for each ticket type. Therefore each type can have different statuses.

|**Confidential**
|Select **Yes** or **No**.  +
**Yes** = The work step is confidential and for that reason only comments can be written. Messages can not be written.  +
**No** = The work step is not confidential and messages as well as comments can be written.

|**Message**
|Messages can be used for internal and external communication. This means you can write messages to communicate with customers, suppliers etc. You can use the messages to give more information about a work step and the current progess or any other information you would like to include. A message will always be sent as email to the ticket owners.
You only need to enter the <<basics/admin-tasks/manage-users#30, email address>> in the user account.

|**Comment**
|Comments are used for internal communication. Comments can not be read by external contributors such as customers or suppliers.
|====

[#400]
== Making use of work steps in the reorder

All work steps of a template will be converted into tickets when you click on **Generate ticket from template**. Next you can edit the tickets and write messages or comments.

[TIP]
.Only one template per reorder
====
You can only generate work steps once in a reorder. This means that you can only apply one template. If a template was applied, you can not apply a second template.
====

[#500]
=== Generating tickets for work steps

Proceed as described below to generate tickets for work steps. The supplier of the reorder is automatically linked to the ticket.

[.instruction]
Generating tickets for work steps:

. Go to **Stock » Reorder management » Reorders**.
. Open a reorder or create a new reorder.
. Click on the **Ticket** tab.
. Select a **Ticket template** from the drop-down list.
. Click on **Generate tickets**. +
→ For each step of the template one ticket will be created.

The system will give the ticket an ID and the IDs are used to list the tickets in descending order. The order in which the tickets are created defines the order of the ticket IDs. The ID of the reorder will be displayed in the ticket. In front of the reorder ID the abbreviation RO is displayed. This is meant to help you identify the tickets that belong to reorders.

[IMPORTANT]
.Adding steps
====
If you edit a template later on and you add more steps, the steps will not be added to reorders in which the template was applied.
====

[#600]
=== Editing tickets

Tickets can be used to share comments or messages. You can also add files in the **Attachment** tab. If a message is added, it will directly be sent as email to the supplier included in the ticket. The supplier's answer will also be shown in the ticket. Comments, however, are internal messages which are not sent to the supplier.

In addition, editing tickets is documented with statuses. The statuses available depend on the ticket type. The ticket types allow you to set up one type e.g. for customer support and one for reorder work steps.

Go to <<crm/using-the-ticket-system#, System » System settings » CRM » Ticket system>> to set up the function for retrieving emails as well as to create ticket types and statuses.

[#700]
== Searching for a template

You can use filters to search for templates. Proceed as described below to search fo ra template.

[.instruction]
Searching for a template:

. Go to **System » System settings » Stock » Reorder management » Templates**.
. Open the **Filter** tab and enter either the **ID** of the template, the **name** of the template or select a date that the template was **created on**.
. Click on **Search**. +
→ The results are displayed in the **Templates** tab.
