= Generating entry certificates (Gelangensbestätigungen)
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Entry certificate, Gelangensbestätigung, Fulfilment, Order documents, Order processing, Delivery, Export delivery
:position: 80
:nav-alias: Entry certificate (Gelangensbestätigung)

In plentymarkets, you can generate credit notes as PDF files, for example if you want to print them or send them to your customers as an email attachment. +
An entry certificate is required with deliveries from Germany into another EU country. Recipients confirm receipt of the incoming items in the respective EU country e.g. by signing the entry certificate and sending it back to the sender. +
Thus, an entry certificate is not only a document that accompanies export deliveries, but may also be a receipt relevant for taxes and accounting.

[#100]
== Setting up a document template for entry certificates

Before generating entry certificates, you have to set up a document template. This is done in the menu **System » Client » Select client » Locations » Select location » Documents**. +
For further information and instructions on setting up the document template, refer to the <<order-processing/orders/order-documents#, Order documents>> page of the manual.

[#200]
== Generating a single entry certificate

In plentymarkets, you can manually generate a single entry certificate directly in the order.

[.instruction]
Generating a single entry certificate:

. Go to **Orders » Edit orders**. +
→ The order overview opens.
. Select the order for which an entry certificate should be created by clicking on the **Order ID**. +
. Open the **Receipts** tab. +
. In the **Create receipt** drop-down menu, select the document **Entry certificate (Gelangensbestätigung**. +
. Carry out the settings according to <<table-orders-receipts-entry-certificate>>. +
. **Save** the settings to generate the entry certificate. +
→ A **PDF file** containing the generated entry certificate opens.

[[table-orders-receipts-entry-certificate]]
.Options in the *Create receipt* menu
[cols="1,3"]
|====
|Setting |Explanation

|**Date**
|Select the date that is displayed on the entry certificate. The present date is set by default.

|**Number**
|The document number is assigned automatically. No entry is required in this field.

|**Book outgoing items**
|Choose whether outgoing items should be booked after generating the entry certificate by selecting one of the options **YES** or **NO**.

|**Change order status to status**¤|Select a status that should be applied to the order after generating the entry certificate. Choose the option **No change** if a status change is not desired.

|**Comment**
|Enter a text that is displayed below the item list on the entry certificate. This step is optional.
|====

[#300]
== Generating several entry certificates

If you wish to generate several entry certificates at a time, use the search filter in the **Orders » Fulfilment** menu to determine the orders for which entry certificates should be generated. In addition, a status change can take place after the entry certificates have been generated.

[.instruction]
Generating several entry certificates:

. Go to **Orders » Fulfilment » Generate entry certificate (Gelangensbestätigung)**.
. Carry out the settings according to <<table-settings-fulfilment-entry-certificate>>
. Click on the **gear-wheel icon** to generate the entry certificates. +
→ A **PDF file** containing the entry certificates for the previously selected orders opens.

[[table-settings-fulfilment-entry-certificate]]
.Options in the *Generate entry certificate (Gelangensbestätigung)*
[cols="1,3"]
|====
|Setting |Explanation

|**Order status**
|From the list, select the status of the orders for which entry certificates should be generated.

|**Owner**
|Select the owner responsible for the orders for which the entry certificates should be generated. Select **ALL** if entry certificates should be generated for all owners.

|**Location**
|Select a location for which the entry certificates should be generated.

|**Warehouse**
|Select one of the warehouses or the option **ALL**.

|**Payment method**
|Select a payment method or *ALL*.

|**Sorting**
|Determine how the generated entry certificates should be sorted. The options **Order ID**, **Customer ID** and **Item ID** are available for different sorting methods.

|**Limit**
|Determine the maximum number of entry certificates generated at a time. There is a maximum of *200* entry certificates.

|**Change order status**
|Select a status that should be applied to the orders after generating the entry certificates. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been handled.

|**Comment**
|Enter a text that is later displayed below the item list on all entry certificates. This step is optional.
|====
