= Generating return slips
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Return slip, Generating return slips, Fulfilment, Order processing, Order documents, Return, Return delivery
:position: 96

[#100]
== General information about return slips

In plentymarkets, you can generate return slips as PDF files, for example if you want to print them or send them to your customers as an email attachment. +
This way, customers can enclose the return slips to their shipments when returning or exchanging items.

[#200]
== Setting up a document template for return slips

Before generating return slips, you have to set up a document template. This is done in the menu **System » Client » Select client » Locations » Select location » Documents**. +
For further information and instructions on setting up the document template, refer to the <<en/order-processing/orders/order-documents#, Order documents>> page of the manual.

[#300]
== Generating return slips

After having set up a document template for return slips, you can generate return slips in PDF format. In this process, a filter allows you to choose the orders to be considered and whether a status change should take place after the return slips have been generated.

[.instruction]
Generating return slips:

. Go to **Orders » Fulfilment » Generate return slips**.
. Carry out the settings according to <<table-settings-fulfilment-return-slip>>.
. Click on the **gear-wheel icon** to generate the return slips. +
→ A **PDF file** containing the return slips for the previously selected orders opens.

[[table-settings-fulfilment-return-slip]]
.Options in the *Generate return slips* menu¤[cols="1,3"]
|====
|Setting |Explanation

|**Order status**
|From the list, select the status of the orders for which return slips should be generated.

|**Owner**
|Select the owner responsible for the orders for which the return slips should be generated. Select **ALL** if return slips should be generated for all owners.

|**Location**
|Select a location for which the return slips should be generated.

|**Warehouse**
|Select one of the warehouses or the option **ALL**.

|**Payment method**
|Select a payment method or *ALL*.

|**Sorting**
|Determine how the generated return slips should be sorted. The options **Order ID**, **Customer ID** and **Item ID** are available for different sorting methods.

|**Limit**
|Determine the maximum number of return slips generated at a time. There is a maximum of *200* return slips.

|**Change order status**
|Select a status that should be applied to the orders after generating the return slips. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been handled.

|**Comment**
|Enter a text that is later displayed below the item list on all entry certificates. This step is optional.
|====
