= Invoices
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Invoice, Generating invoices, PDF template, Fulfilment, Order documents, Order processing
:position: 10

In plentymarkets, you can generate invoices, for example if you want to print them or send them to your customers as an email attachment. +
Depending on the country of delivery and the location of your business, invoices are subject to different legal requirements. Familiarise yourself with these requirements and make sure that all required invoice data is displayed on your invoice.

[#100]
== Setting up a document template for invoices

Before generating invoices, you have to set up a document template. This is done in the menu **System » Client » Select client » Locations » Select location » Documents**. +
For further information and instructions on setting up the document template, refer to the <<order-processing/orders/order-documents#, Order documents>> page of the manual.

[#200]
== Generating invoices

After having set up a document template for invoices, you can generate invoices in PDF format. In this process, a filter allows you to choose the orders are considered and whether a status change should take place after the invoices have been generated.

[.instruction]
Generating invoices:

. Go to **Orders » Fulfilment » Generate invoices**.
. Carry out the settings according to <<table-settings-fulfilment-invoices>>.
. Click on the **gear-wheel icon** to generate the invoices.
→ A **PDF file** containing the invoices for the previously selected orders opens.

[[table-settings-fulfilment-invoices]]
.Options in the *Generate invoices submenu*
[cols="1,3"]
|====
|Setting |Explanation

|**Order status**
|From the list, select the status of the orders for which invoices should be generated.

|**Owner**
|Select the owner responsible for the orders for which the invoices should be generated. Select **ALL** if invoices should be generated for all owners.

|**Location**
|Select a location for which the invoices should be generated.

|**Warehouse**
|Select a warehouse or **ALL**.

|**Customer class**
|Select a customer class for which the invoices should be generated or select the option **ALL** if invoices should be generated for all customer classes.

|**Payment method**
|Select a payment method or **ALL**.

|**Sorting**
|Determine how the generated invoices should be sorted. The options **Order ID**, **Invoice number** and **Item ID** are available for different sorting methods.

|**Limit**
|Determine the maximum number of invoices generated at a time. There is a maximum of **200** invoices.

|**Invoice date**
|Select a date from the calendar which should be displayed as invoice date on the invoice.

|**Change order status**
|Select a status that should be applied to the orders after generating the invoices. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been handled.
|====
