= Generating entry certificates (Gelangensbestätigungen)
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Entry certificate, Gelangensbestätigung, Fulfilment, Order documents, Order processing, Delivery, Export delivery
:position: 94

[#100]
== General information about entry certificates (Gelangensbestätigungen)

In plentymarkets, you can generate credit notes as PDF files, for example if you want to print them or send them to your customers as an email attachment. +
An entry certificate is required with deliveries from Germany into another EU country. Recipients confirm receipt of the incoming items in the respective EU country e.g. by signing the entry certificate and sending it back to the sender. +
Thus, an entry certificate is not only a document that accompanies export deliveries, but may also be a receipt relevant for taxes and accounting.

[#200]
== Setting up a document template for entry certificates

Before generating entry certificates, you have to set up a document template. This is done in the menu **System » Client » Select client » Locations » Select location » Documents**. +
For further information and instructions on setting up the document template, refer to the <<en/order-processing/orders/order-documents#, Order documents>> page of the manual.

[#300]
== Generating entry certificates (Gelangensbestätigungen)

After having set up a document template for entry certificates, you can generate entry certificates in PDF format. In this process, a filter allows you to choose the orders to be considered and whether a status change should take place after the entry certificates have been generated.

[.instruction]
Generating entry certificates (Gelangensbestätigungen):

. Go to **Orders » Fulfilment » Generate entry certificate (Gelangensbestätigung)**.
. Carry out the settings according to <<table-settings-fulfilment-entry-certificate>>
. Click on the **gear-wheel icon** to generate the entry certificates. +
→ A **PDF file** containing the entry certificates for the previously selected orders opens.

[[table-setting-fulfilment-entry-certificates]]
.Options in the *Generate entry certificate (Gelangensbestätigung)* menu
[cols="1,3"]
|====
|Setting |Explanation

|**Order status**
|From the list, select the status of the orders for which entry certificates should be generated.

|**Owner**
|Select the owner responsible for the orders for which the entry certificates should be generated. Select **ALL** if entry certificates should be generated for all owners.

|**Location**
|Select a location for which the entry certificates should be generated.

|**Warehouse**
|Select one of the warehouses or the option **ALL**.

|**Payment method**
|Select a payment method or *ALL*.

|**Sorting**
|Determine how the generated entry certificates should be sorted. The options **Order ID**, **Customer ID** and **Item ID** are available for different sorting methods.

|**Limit**
|Determine the maximum number of entry certificates generated at a time. There is a maximum of *200* entry certificates.

|**Change order status**
|Select a status that should be applied to the orders after generating the entry certificates. +
The status change is an important tool to make sure that the process is not carried out twice for orders that have already been handled.

|**Comment**
|Enter a text that is later displayed below the item list on all entry certificates. This step is optional.
|====
