= Barzahlung
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zahlungsart, Zahlungen, Barzahlung, Cash, Plugin, Barzahlung-Plugin, Barzahlungsplugin, Barzahlungs-Assistent, Barzahlungsassistent, PayUponPickup, Pay upon pickup, bezahlen, bar, bar bezahlen, Barzahlung-Schnittstelle, Barzahlungsschnittstelle, Barzahlungszahlung, Barzahlungs-Zahlung, Zahlungsplugin, Zahlungs-Plugin, Payment-Plugin, Paymentplugin, Payment-Integration, Paymentintegration, Paymentschnittstelle, Payment-Schnittstelle
:description: Integration des Plugins Barzahlung.
:position: 10
:url: payment/payment-plugins/barzahlung
:id: PRW1S0P
:author: team-order-payment

Mit dem Barzahlung-Plugin bindest du die Zahlungsart *Barzahlung* in deinen Webshop ein und stellst sie so deinen Kund:innen zur Auswahl. Lade dafür das Barzahlungs-Plugin im link:https://marketplace.plentymarkets.com/payuponpickup_4757[plentyMarketplace^]{nbsp}icon:external-link[] herunter. Die Einrichtung der Zahlungsart erfolgt über einen Assistenten. Zudem musst du einige grundlegende Einstellungen in deinem plentymarkets System ausführen, damit die Zahlungsart auch in deinem System aktiviert ist. +
Die Erklärungen auf dieser Seite finden nach dem Hinzufügen des Plugins Anwendung. Allgemeine Informationen zum Hinzufügen und Installieren von Plugins findest du im Abschnitt <<plugins#, Plugins>> des Handbuchs.

[#10]
== Ausführen des Assistenten

:name-des-assistenten: Barzahlung
:name-der-zahlungsart: Barzahlung

include::../../_includes/textblocks/instructions/ausfuehrung-assistent-zahlungsart.adoc[]

[#30]
== Kundenklassen und Versandprofile

include::../../_includes/textblocks/instructions/kundenklassen-und-versandprofile.adoc[]

[#40]
== Sprachelemente anpassen

Du kannst Benennungen, die das Barzahlungs-Plugin mitbringt, im Menü *CMS » Mehrsprachigkeit* nach deinen Bedürfnissen in allen verfügbaren Systemsprachen anpassen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Sprachdateien anpassen:

. Öffne das Menü *CMS » Mehrsprachigkeit.*
. Wähle auf der linken Seite die *Ausgangssprache* aus der Dropdown-Liste.
. Wähle auf der rechten Seite die *Zielsprache* aus der Dropdown-Liste.
. Klappe im Bereich *PayUponPickup* die Sektion *Zahlungsart* aus.
. Gib im Bereich der Zielsprache die gewünschten Texte für die einzelnen Sprachelemente ein.
. Speichere (icon:save[role=green]) die Einstellungen.

Weitere Informationen zum Bearbeiten von im Webshop angezeigten Texten findest du auf der Handbuchseite <<webshop/ceres-einrichten#231, Ceres-Webshop einrichten>>.
