= Kauf auf Rechnung
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zahlungsarten, Zahlungen, Rechnung, Rechnungskauf, Kauf auf Rechnung
:description: Integration des Plugins Kauf auf Rechnung
:position:
:url: payment/payment-plugins/kauf-auf-rechnung
:id: 8RUBSKP
:author: team-order-payment

Mit dem Plugin *Kauf auf Rechnung* bindest du die Zahlungsart Rechnung in deinem Webshop ein und stellst sie so deinen Kund:innen zur Auswahl. Die Integration erfolgt über einen Assistenten. Zudem musst du einige grundlegende Einstellungen in deinem plentymarkets System ausführen, damit die Zahlungsart auch in deinem System aktiviert ist.

== Zahlungsart einrichten

Bevor die Zahlungsart in deinem Webshop verfügbar ist, musst du zuerst einige Einstellungen in deinem plentymarkets Backend vornehmen.

[.discrete]
==== Zahlungsart einmalig aktivieren

Aktiviere als erstes die Zahlungsart einmalig in deinem System. Beachte, dass nur die Aktivierung der Zahlungsart notwendig ist. Alle weitere Einstellungen, wie z.B. zu Mandanten oder Lieferländern, haben keine Auswirkungen.

[.instruction]
Aktivierung der Zahlungsart:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Wähle einen Ordner aus.
. Aktiviere die Option *Aktiv* (icon:check-square[role="blue"]).
. Speichere (icon:save[role=green]) die Einstellungen.

[.discrete]
==== Zahlungsart in Kundenklassen erlauben

Stelle zudem sicher, dass die Zahlungsart unter dem Punkt *Erlaubte Zahlungsarten* in den << LINK Kundenklassen vorhanden ist

[.discrete]
==== Zahlungsart in Versandprofilen

und nicht im Bereich Gesperrte Zahlungsarten in den Versandprofilen aufgeführt ist.

[.discrete]
==== Ausführung des Assistenten

Nachdem du diese grundlegenden Einstellungen ausgeführt hast, gehe nun wie folgt vor, um die Zahlungsart einzurichten.

[.instruction]
Zahlungsart einrichten:

. Öffne das Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen]*.
. Wähle den Assistenten *Kauf auf Rechnung*.
. Schließe den Assistenten vollständig ab. +
→ Die Zahlungsart Rechnung ist in deinem Webshop verfügbar.

== Sprachelemente anpassen

Du kannst Benennungen, die das Kauf auf Rechnung-Plugin mitbringt, im Menü *CMS » Mehrsprachigkeit* nach deinen Bedürfnissen in allen verfügbaren Systemsprachen anpassen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Sprachdateien anpassen:

. Öffne das Menü *CMS » Mehrsprachigkeit.*
. Wähle auf der linken Seite die Ausgangssprache aus der Dropdown-Liste.
. Wähle auf der rechten Seite die Zielsprache aus der Dropdown-Liste.
. Klappe im Bereich Invoice die Sektionen Bankdaten, Verwendungszweck und Zahlungsart aus.
. Gib im Bereich der Zielsprache die gewünschten Texte für die einzelnen Sprachelemente ein.
. Speichere die Einstellungen.

Weitere Informationen zum Bearbeiten von im Webshop angezeigten Texten findest du auf der Handbuchseite << LINK Ceres-Webshop einrichten.

== Rechnungsdokumente erstellen

Rechnungen kannst du manuell oder automatisch über eine Ereignisaktion erzeugen. Erfahre, wie du Vorlagen für Rechnungsdokumente anlegst.
