= Klarna
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zahlungsarten, Zahlungen, Klarna
:description: Integration des Klarna-Plugins
:position:
:url: payment/payment-plugins/klarna
:id: 3SGDQQB
:author: team-order-payment

== Voraussetzung: Eröffnung eines Klarna-Händlerkontos

Für die Nutzung von Klarna benötigst du ein link:https://www.klarna.com/de/verkaeufer/[Klarna.Händlerkonto^]{nbsp}icon:external-link[]. Durch die Eröffnung des Kontos erhältst du Informationen sowie Zugangsdaten. Liegen diese nicht vor, kannst du das Plugin nicht einrichten und somit nicht nutzen. Sofern du noch keine Klarna-Registrierung durchlaufen hast oder deine Klarna-Kundennummer nicht mit Kxxxxxx beginnt, sende eine E-mail an vertrieb@klarna.com.

== Zahlungsart einrichten

Das Einrichten des Klarna-Plugins erfordert nur einige wenige Klicks und Einstellungen. Erforderlich sind die Konfiguration des Plugins und das Einrichten von Ereignisaktionen. Konfiguriere zunächst das Plugin.

[.instruction]
Konfiguration des Plugins:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht » [Plugin-Set wählen]*.
. Öffne auf das Plugin *Klarna*. +
→ Du wirst zur Authentifizierung weitergeleitet.
. Wähle einen Modus aus. Zur Auswahl stehen *Testing* und *Produktiv*.
. Gib nun den passenden *Benutzernamen* und das *Kennwort* ein. Achte darauf, die richtigen Daten für den ausgewählten Modus zu hinterlegen.
. *Speichere* (icon:save[role=green]) die Auswahl.

Als nächstes hast du die Möglichkeit, zwischen den Klarna Modulen *Klarna Payments* oder *Klarna Checkout* auszuwählen. Bei der Auswahl von *Klarna Payments* steht dir im Shop dann die Klarna Zahlungsart *Später bezahlen* zur Verfügung. Wählst du *Klarna Checkout*, überschreibt dies automatisch den bisherigen Checkout im Shop. Bei dieser Auswahl sind keine weiteren Konfigurationen mehr nötig. Die Überschreibung wird durch die Deaktivierung des Plugins rückgängig gemacht.

[.instruction]
Auswahl des Klarna Moduls:

. Öffne im Menü links Konfiguration » Allgemeine Einstellungen.
. Wähle ein Klarna Modul aus.
. *Speichere* (icon:save[role=green]) die Auswahl.

=== Kundenklassen

Stelle sicher, dass die Zahlungsart in den <<crm/kontakte-verwalten#15, Kundenklassen>> erlaubt ist und auch in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>> nicht gesperrt ist. Überlege dir hierfür, für welche Kundenklassen und Versandprofile die Zahlungsart gelten soll. Dies ist in jedem System individuell einstellbar.

[.instruction]
Zahlungsart in Kundenklasse erlauben:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Öffne die Kundenklasse, in dem die Zahlungsart erlaubt werden soll.
. Wähle die Zahlungsart aus der Liste im Bereich *Erlaubte Zahlungsarten* durch Anklicken aus.
. Speichere (icon:save[role=green]) die Einstellungen.

Wiederhole dies ggf. für weitere Kundenklassen.

=== Ereignisaktionen einrichten

Richte Ereignisaktionen ein, damit alle benötigten Daten automatisch an Klarna versendet werden. Dafür sind 5 Ereignisaktionen erforderlich.

[.collapseBox]
.*Ereignisaktion einrichten*
--

[.instruction]
Einrichtung einer Ereignisaktion:

. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das Ereignis gemäß Tabellen 1-5.
. *Speichere* (icon:save[role=green]) die Einstellungen.
. Nimm die Einstellungen gemäß Tabellen 1-5 vor.
. Aktiviere die Option *Aktiv*.
. *Speichere* (icon:save[role=green]) die Einstellungen.

--

==== Versandbestätigung automatisch senden

Damit die Zahlung bei Klarna aktiviert wird, muss eine Versandbestätigung gesendet werden. Dafür empfehlen wir die folgende Konfigurationen:

[[tabelle-ea-klarna-versandbestätigung]]
.Ereignisaktion Versandbestätigung an Klarna senden
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Warenausgang gebucht
|

| *Filter 2*
| Auftrag > Zahlungsart
| Alle Zahlungsarten des Klarna-Plugins auswählen.

| *Filter 1*
| Auftragstyp
| Auftrag

| *Aktion*
| Plugin: Versandbestätigung an Klarna senden
|

|====

==== Stornierung automatisch senden

Im Fall einer Stornierung eines Auftrags muss eine Information an Klarna erfolgen. Dafür empfehlen wir die folgende Konfiguration:

[[tabelle-ea-klarna-stornierung]]
.Ereignisaktion Stornierung an Klarna senden
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Statuswechsel
| Status aus dem stornierten Bereich wählen

| *Filter 2*
| Auftrag > Zahlungsart
| Alle Zahlungsarten des Klarna-Plugins auswählen.

| *Filter 1*
| Auftragstyp
| Auftrag

| *Aktion*
| Plugin: Stornierung an Klarna senden
|

|====

==== Rückerstattung automatisch senden

Im Fall einer Rückerstattung muss eine Information an Klarna erfolgen. Dafür empfehlen wir die folgende Konfiguration:

[[tabelle-ea-klarna-rückerstattung]]
.Ereignisaktion Rückerstattung an Klarna senden
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Neue Gutschrift
|

| *Filter 2*
| Auftrag > Zahlungsart
| Alle Zahlungsarten des Klarna-Plugins auswählen.

| *Filter 1*
| Auftragstyp
| Gutschrift

| *Aktion*
| Plugin: Rückerstattung Klarna senden
|

|====

==== Änderung der Auftragsanschrift automatisch senden

Sollte es zwischen Auftragsanlage und Versand zu einer Änderung der Auftragsanschriften kommen, muss dies an Klarna gemeldet werden. Dafür empfehlen wir die folgende Konfiguration:

[[tabelle-ea-klarna-anschriftsänderung]]
.Ereignisaktion Änderung der Auftragsanschrift an Klarna senden
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Statuswechsel
|

| *Filter 2*
| Auftrag > Zahlungsart
| Alle Zahlungsarten des Klarna-Plugins auswählen.

| *Filter 1*
| Auftragstyp
| Auftrag

| *Aktion*
| Plugin: Änderung der Auftragsanschrift an Klarna senden
|

|====

==== Änderung der Artikelpositionen automatisch senden

Sollte es zwischen Auftragsanlage und Versand zu einer Änderung an den Auftragspositionen kommen, muss dies an Klarna gemeldet werden. Dafür empfehlen wir die folgende Konfiguration:

[[tabelle-ea-klarna-artikeländerung]]
.Ereignisaktion Änderung der Artikelpositionen an Klarna senden
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Statuswechsel
|Status auswählen, bei dem das Ereignis ausgelöst werden soll.

| *Filter 2*
| Auftrag > Zahlungsart
| Alle Zahlungsarten des Klarna-Plugins auswählen.

| *Filter 1*
| Auftragstyp
| Auftrag

| *Aktion*
| Plugin: Änderung der Artikelpositionen an Klarna senden
|

|====
