= Mollie
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zahlungsarten, Mollie, Mollie-Plugin, Mollie-Assistent, Mollieassistent, Mollieplugin, Mollie-Account, Molliehändler, Mollieaccount, Mollie-Zahlung, Molliezahlung, Mollie-Zahlungsart, Molliezahlungsart, mollie-template, Mollie-Ereignisaktion, Mollieereignisaktion, Mollieversand, Mollie-Versand, Molliestorno, Molliestornierung, Mollie-Storno, Mollie-Stornierung, Molliegutschrift, Mollie-Gutschrift, Mollie-Rückzahlung, Mollierückzahlung, Mollie-Konfiguration, Molliekonfiguration, Mollie-Einstellung, Mollieeinstellung, Mollie-Schnittstelle, Mollieschnittstelle, Zahlungsplugin, Zahlungs-Plugin, Payment-Plugin, Paymentplugin, Payment-Integration, Paymentintegration, Paymentschnittstelle, Payment-Schnittstelle, Zahlart, Zahlarten
:description: Integration des Mollie-Plugins.
:position: 60
:url: payment/payment-plugins/mollie
:id: U2UV0PY
:author: team-order-payment

Mit dem Mollie-Plugin bindest du die *Mollie-Zahlungsarten* in deinen Webshop ein und stellst sie so deinen Kund:innen zur Auswahl. Lade dafür das Mollie-Plugin im link:https://marketplace.plentymarkets.com/mollie_6272[plentyMarketplace^]{nbsp}icon:external-link[] herunter. Die Einrichtung der Zahlungsarten erfolgt über einen Assistenten. Zudem musst du einige grundlegende Einstellungen in deinem plentymarkets System ausführen, damit die Zahlungsarten auch in deinem System aktiviert sind. +
Die Erklärungen auf dieser Seite finden nach dem Hinzufügen des Plugins Anwendung. Allgemeine Informationen zum Hinzufügen und Installieren von Plugins findest du im Abschnitt <<plugins#, Plugins>> des Handbuchs.

[#10]
== Voraussetzung: Registrierung bei Mollie

Für die Nutzung von Mollie benötigst du einen Account und die Zugangsdaten von Mollie. Liegen diese nicht vor, kannst du das Plugin nicht einrichten und somit nicht nutzen. Solltest du noch keinen Account bei Mollie haben, link:https://www.mollie.com/dashboard/signup/5543454?lang=de[registriere^]{nbsp}icon:external-link[] dich zunächst dort.

[TIP]
.Von Mollie unterstützte Währungen
====
Es gibt einige Vorgaben, die von Zahlungsanbietern gemacht werden, so in der Regel auch die unterstützten Währungen. Welche Währungen von Mollie unterstützt werden findest du in der Mollie Dokumentation auf der Seite link:https://docs.mollie.com/payments/multicurrency[Multicurrency^]{nbsp}icon:external-link[].
====

[#20]
== Ausführung des Assistenten

:name-des-assistenten: Mollie
:name-der-zahlungsart: Mollie

include::../../_includes/textblocks/instructions/ausfuehrung-assistent-zahlungsart.adoc[]

[IMPORTANT]
.Assistent muss erneut durchlaufen werden
====
Es kann vorkommen, dass du den Assistenten erneut durchlaufen musst. Wenn du eine Mollie-Zahlungsart, die in deinem plentymarkets System aktiviert ist, nach Abschluss des Assistenten über das Dashboard direkt in deinem Mollie-Account deaktivierst, muss der Assistent erneut abgeschlossen werden. Durchläufst du ihn erneut, stimmen die Einstellungen überein und können nicht zu einer Fehlkonfiguration führen.
====

[.collapseBox]
.*Ein-Click-Zahlungen*
--

Mit der Funktion Ein-Klick-Zahlungen können deine Kund:innen ihre Kreditkartendaten durch Anlegen eines Kundenkontos bei Mollie direkt speichern. So müssen sie ihre Daten nicht bei jedem Einkauf erneut eingeben und die Zahlungsabwicklung kann schneller erfolgen. Wenn du deinen Kund:innen diese Funktion zur Verfügung stellen möchtest, musst du sie im Assistenten aktivieren. +
Hast du Ein-Klick-Zahlungen aktiviert kannst du sehen, welche deiner Kund:innen diese Funktion nutzen. In diesem Fall wird im entsprechenden Kontaktdatensatz in plentymarkets eine eindeutige, von Mollie vergebene ID hinterlegt. Zudem sind in deinem Mollie-Account die Kund:innen aufgelistet, die Ein-Klick-Zahlungen nutzen.

--

include::../_textblocks/durchlauf-assistent-multimandanten.adoc[]

[#30]
== Template Container verknüpfen

Die standardmäßig benötigten Container werden während des Einrichtens über den Mollie-Assistenten automatisch für deinen Webshop verknüpft. Solltest du dennoch Container manuell verknüpfen wollen, dann gehe wie folgt vor.

[.instruction]
Container-Verknüpfungen einstellen:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht*.
. Öffne das Plugin-Set, das du bearbeiten möchtest.
. Öffne das Plugin *Mollie*.
. Öffne die *Container-Verknüpfungen*.
. Wähle einen oder mehrere Container, in denen der zuvor gewählte Content dargestellt werden soll. +
→ Beachte dazu die Erläuterungen in <<table-mollie-template-container>>.
. *Speichere* (icon:save[role=green]) die Einstellungen. +
→ Die Contents sind mit den Containern verknüpft.

[[table-mollie-template-container]]
.Template-Container verknüpfen
[cols="1,3"]
|====
|Content |Erläuterung

|*Payment button (Mollie)*
|Die Container *Order confirmation: Additional payment information* und *My account: Additional payment information* müssen verknüpft sein, um den Mollie Zahlen-Button im Checkout darzustellen.

|*Apple Pay Button*
| Verknüpfe einen oder mehrere der folgenden Container, um den Apple Pay Button an der entsprechenden Stelle darzustellen: +
- Warenkorbvorschau: *After "Checkout" button* +
- Warenkorb: *After "Checkout" button* +
- Warenkorb-Overlay: *Extend buttons* +
- Artikelansicht: *After add to shopping cart button*

|====

[#50]
== Kundenklassen und Versandprofile

include::../../_includes/textblocks/instructions/kundenklassen-und-versandprofile.adoc[]

[#60]
== Ereignisaktionen einrichten

Ereignisaktionen sind Teil der Automatisierungen, die du in plentymarkets einrichten kannst. Dabei löst ein bestimmtes Ereignis für eine Auswahl von Aufträgen eine bestimmte Aktion aus. Grundlegendes zu Ereignisaktionen findest du auf der Handbuchseite <<automatisierung/ereignisaktionen#, Ereignisaktionen>>.

Im Zusammenhang mit Zahlungsanbietern wie Mollie werden Ereignisaktionen verwendet, um wichtige Informationen von plentymarkets an den Zahlungsanbieter zu senden. Für Mollie gibt es drei notwendige und weitere optionale Ereignisaktionen. Die notwendigen Ereignisaktionen solltest du auf jeden Fall einrichten, es handelt sich dabei um den Versand der Auftragspositionen eines Auftrags, die Stornierung eines Auftrags und die Erstellung einer Gutschrift. Mollie muss informiert werden, wenn etwas davon eingeleitet wird. +
Neben diesen drei erforderlichen Ereignisaktionen stehen dir noch optionale Ereignisaktionen zur Verfügung. Diese kannst du nutzen, wenn sie in deinen individuellen Arbeitsablauf passen.

Im Folgenden wird eine Beispielkonfiguration und eine Erklärung zur Einrichtung für jede Ereignisaktion gegeben. Es ist jedoch wichtig, dass du die Ereignisaktion jeweils so anpasst, dass sie in deinen Arbeitsablauf passt.

[#70]
=== Versand bei Mollie anmelden

:table-event-procedure: <<table-procedure-mollie-shipment>>
include::../../_includes/textblocks/instructions/EA.adoc[]

[[table-procedure-mollie-shipment]]
.Ereignisaktion "Mollie | Versand anmelden"
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Das Ereignis wählen, nach dem der Versand angemeldet werden soll.
|

| *Filter 1*
| Auftrag > Zahlungsart
| Plugin: Mollie:*

| *Aktion*
| Plugin > Mollie | Versand anmelden
|

|====

Diese Ereignisaktion kann auch für Lieferaufträge verwendet werden. Der Lieferauftrag wird dann bei Mollie als Teilsendung angemeldet.

[#80]
=== Storno bei Mollie anmelden

:table-event-procedure: <<table-procedure-mollie-cancellation>>
include::../../_includes/textblocks/instructions/EA.adoc[]

[[table-procedure-mollie-cancellation]]
.Ereignisaktion "Mollie | Storno anmelden"
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Das Ereignis wählen, nach dem der Versand angemeldet werden soll.
|

| *Filter 1*
| Auftrag > Zahlungsart
| Plugin: Mollie:*

| *Aktion*
| Plugin > Mollie | Storno anmelden
|

|====

_Beachte_, dass ein Auftrag nicht storniert werden kann, solange eine Zahlung noch im Status "pending" ist. Die Ablaufzeit für die jeweiligen Zahlungsarten werden von Mollie vorgegeben und sind link:https://docs.mollie.com/payments/status-changes#expiry-times-per-payment-method[auf dieser Seite^]{nbsp}icon:external-link[] aufgeführt.

[#90]
=== Gutschrift bei Mollie anmelden

Achte beim Anlegen der Gutschrift darauf, dass die Auftragspositionen, die gutgeschrieben werden sollen, auch in der Gutschrift enthalten sind. Mehr Informationen über Gutschriften allgemein findest du im Kapitel <<auftraege/auftraege-verwalten#500, Auftragstyp Gutschrift>> nutzen im Handbuch. +
Die Ereignisaktion *Mollie | Gutschrift anmelden* kann auf Basis eines Auftrags und eines Gutschriftauftrags ausgeführt werden.

:table-event-procedure: <<table-procedure-mollie-refunds>>
include::../../_includes/textblocks/instructions/EA.adoc[]

[[table-procedure-mollie-refunds]]
.Ereignisaktion "Mollie | Gutschrift anmelden"
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Das Ereignis wählen, nach dem der Versand angemeldet werden soll.
|

| *Filter 1*
| Auftrag > Zahlungsart
| Plugin: Mollie:*

| *Aktion*
| Plugin > Mollie | Gutschrift anmelden
|

|====

[#92]
=== Rückzahlung erfolgreich oder gescheitert
Im Anschluss an die Aktion *Mollie | Gutschrift anmelden* stehen dir zwei weitere zusätzliche Ereignisse zur Verfügung, um den weiteren Verlauf des Auftrages abzubilden: *Mollie Rückzahlung gescheitert* und *Mollie Rückzahlung erfolgreich*. Richte optional Ereignisaktionen mit diesen Ereignissen wie oben beschrieben ein.

[#97]
=== Zahlung gescheitert
auch noch das Ereignis *Mollie | Zahlung gescheitert* zur Verfügung. Die Nutzung dieses Ereignisses ist optional. Du kannst es verwenden um zu bestimmen, wie mit Aufträgen verfahren werden soll, für die die Zahlung nicht erfolgen konnte.

[#100]
== Sprachelemente anpassen

Du kannst Benennungen, die das Mollie-Plugin mitbringt, im Menü *CMS » Mehrsprachigkeit* nach deinen Bedürfnissen in allen verfügbaren Systemsprachen anpassen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Sprachdateien anpassen:

. Öffne das Menü *CMS » Mehrsprachigkeit.*
. Wähle auf der linken Seite die *Ausgangssprache* aus der Dropdown-Liste.
. Wähle auf der rechten Seite die *Zielsprache* aus der Dropdown-Liste.
. Klappe im Bereich *Mollie* die Sektionen *Messages* und *Payment methods* aus.
. Gib im Bereich der Zielsprache die gewünschten Texte für die einzelnen Sprachelemente ein.
. Speichere (icon:save[role=green]) die Einstellungen.

Weitere Informationen zum Bearbeiten von im Webshop angezeigten Texten findest du auf der Handbuchseite <<webshop/ceres-einrichten#231, Webshop-Texte bearbeiten>>.
