= Nachnahme
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zahlungsarten, Zahlungen, Nachnahme
:description: Integration des Plugins Nachnahme
:position:
:url: payment/payment-plugins/nachnahme
:id: 3VRD6B6
:author: team-order-payment

Mit dem Plugin *Nachnahme* bindest du die Zahlungsart Nachnahme in deinem Webshop ein und stellst sie so deinen Kund:innen zur Auswahl. Dafür musst du einige grundlegende Einstellungen in deinem plentymarkets System ausführen, damit die Zahlungsart auch in deinem System aktiviert ist.
Die Erklärungen auf der Seite finden nach dem Hinzufügen des Plugins Anwendung. Allgemeine Informationen zum Hinzufügen und Installieren von Plugins findest du im Abschnitt <<plugins#, Plugins>> des Handbuchs.

[#10]
== Zahlungsart einmalig aktivieren

Aktiviere als erstes die Zahlungsart einmalig in deinem System. Beachte, dass nur die Aktivierung der Zahlungsart notwendig ist. Alle weitere Einstellungen, wie z.B. zu Mandanten oder Lieferländern, haben keine Auswirkungen.

[.instruction]
Aktivierung der Zahlungsart:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Wähle die zu aktivierende Zahlungsart aus.
. Aktiviere die Option *Aktiv* (icon:check-square[role="blue"]).
. Speichere (icon:save[role=green]) die Einstellungen.

[#20]
== Kundenklassen und Versandprofile

Stelle sicher, dass die Zahlungsart in den <<crm/kontakte-verwalten#15, Kundenklassen>> erlaubt ist und auch in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>> nicht gesperrt ist. Überlege dir hierfür, für welche Kundenklassen und Versandprofile die Zahlungsart gelten soll. Dies ist in jedem System individuell einstellbar.

[.instruction]
Zahlungsart in Kundenklasse erlauben:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Öffne die Kundenklasse, in dem die Zahlungsart erlaubt werden soll.
. Wähle die Zahlungsart aus der Liste im Bereich *Erlaubte Zahlungsarten* durch Anklicken aus.
. Speichere (icon:save[role=green]) die Einstellungen.

Wiederhole dies ggf. für weitere Kundenklassen.

[.instruction]
Zahlungsart in bestehenden Versandprofilen überprüfen:

. Öffne das Menü *Einrichtung » Aufträge » Versand » Optionen*.
. Wechsel in das Tab *Versandprofile*.
. Öffne das Versandprofil, in dem die Zahlungsart erlaubt sein soll.
. Überprüfe, ob die Zahlungsart im Bereich *Gesperrte Zahlungsarten* ausgewählt ist.
. Entferne die Auswahl der Zahlungsart, wenn sie für dieses Versandprofil erlaubt sein soll.
. Speichere (icon:save[role=green]) die Einstellungen.

Wiederhole dies ggf. für weitere Versandprofile.

[#30]
== Details der Zahlungsart im Webshop anzeigen

Das Template-Plugin Ceres bietet dir die Möglichkeit, Name und Logo deiner Zahlungsart im Bestellvorgang individuell anzuzeigen. Gehe wie im Folgenden beschrieben vor, um Name und Logo der Zahlungsart anzuzeigen.

[.instruction]
Details zur Zahlungsart einrichten:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht » [Plugin-Set wählen]*.
. Öffne auf das Plugin *Nachnahme*.
. Öffne das Menü *Konfiguration » Einstellungen*.
. Gib unter *Name* den Namen ein, der für die Zahlungsart im Webshop angezeigt werden soll.
. Gib unter Logo-URL eine https-URL ein, die zum Logo-Bild führt. Gültige Dateiformate sind .gif, .jpg oder .png. Die Maximalgröße beträgt 190 Pixel in der Breite und 60 Pixel in der Höhe.
. Speichere (icon:save[role=green]) die Einstellungen. +
→ Name und Logo der Zahlungsart werden im Bestellvorgang des Webshops angezeigt.

[#40]
== Zahlungsart im Bestellvorgang auswählen

Wenn mindestens ein aktives und gültiges Versandprofil die Eigenschaft Nachnahme enthält, wird die Zahlungsart in der Bestellabwicklung angezeigt und ist auswählbar. Nach Auswahl eines Versandprofils mit der Eigenschaft Nachnahme wird die Zahlungsart automatisch ausgewählt.
