= PayPal
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zahlungsarten, Zahlungen, PayPal, PayPal PLUS, PayPal Rechnung, Express-Button, PayPal Ratenzahlung
:description: Integration des PayPal-Plugins
:position:
:url: payment/payment-plugins/paypal
:id: K9UYAY1
:author: team-order-payment

== Voraussetzung: Eröffnung eines PayPal-Geschäftskontos

Für die Nutzung von PayPal benötigst du ein PayPal-Geschäftskonto. Durch die Eröffnung des Kontos erhältst du Informationen sowie Zugangsdaten. Liegen diese nicht vor, kannst du das Plugin nicht einrichten und somit nicht nutzen. Solltest du noch keines haben, link:https://www.paypal.com/de/business[eröffne ein PayPal-Geschäftskonto^]{nbsp}icon:external-link[].

== Ausführung des Assistenten

Das Einrichten des PayPal-Plugins wird mithilfe eines Assistenten durchgeführt. Der Assistent führt dich durch wichtige Einstellungen und enthält notwendige Informationen. Zu finden ist der Assistent in deinem plentymarkets Backend im Menü *Einrichtung » Assistenten » Plugins*. Wähle hier das entsprechende Plugin-Set, in dem das Plugin installiert ist und das du konfigurieren möchtest. Beachte, dass der PayPal-Assistent nach einem Update erneut durchlaufen werden.

[IMPORTANT]
.Aktivierung in Plugin-Set des Hauptmandanten
====
Für die Kontoverknüpfung und die Funktionsweise der Ereignisaktionen muss das PayPal-Plugin in dem Plugin-Set aktiviert sein, das für den Hauptmandanten verwendet wird. Da eine Abhängigkeit zum IO-Plugin besteht, musst du IO für den Bereitstellungsprozess (Speichern im Plugin-Set) aktivieren.
====

[.instruction]
Zahlungsart einrichten:

. Öffne das Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen]*.
. Wähle den Assistenten *PayPal*.
. Schließe den Assistenten vollständig ab. +
→ Die Zahlungsart Rechnung ist in deinem Webshop verfügbar.

== Zahlungsart einrichten

=== Widgets im ShopBuilder

Der PayPal Express-Button und die PayPal Ratenzahlung Banner stehen im ShopBuilder als Widgets zur Verfügung.

=== Template-Container verknüpfen

[IMPORTANT]
.Information zur Containerverknüpfung
====
Die standardmäßig benötigten Container werden während des Einrichtens über den PayPal-Assistenten automatisch für deinen Webshop verknüpft. Ab Version 5.4.0 werden benötigte und optionale Container in dem Plugin-Set verknüpft, in dem der Assistent durchlaufen wird.
====

Für die Zahlungsart PayPal PLUS, für den PayPal Express-Button und für die PayPal Ratenzahlung Banner stehen dir verschiedene Möglichkeiten zur Verfügung, um sie in deinen Shop einzubinden. Hierfür sind in den Templates in plentymarkets an relevanten Stellen Container hinterlegt, mit denen zur Individualisierung Contents verknüpft werden.

[.instruction]
Container verknüpfen:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht*.
. Öffne das Plugin-Set, das du bearbeiten möchtest.
. Öffne die *Einstellungen* des PayPal-Plugins.
. Klicke auf *Container-Verknüpfungen*.
. Wähle aus der Dropdown-Liste den Datenanbieter, den du verknüpfen möchtest.
. Wähle den Container, mit dem du den Datenanbieter verknüpfen möchtest. Beachte dazu die Erläuterungen in <<tabelle-containerverknüpfung>>.
. Wiederhole Schritte 5 und 6 für alle Datenanbieter, die du verknüpfen möchtest.
. *Speichere* (icon:save[role=green]) die Einstellungen.

[[tabelle-containerverknüpfung]]
.Container verknüpfen
[cols="1,3"]
|====
|Content |Erläuterung

2+| *Allgemein*

| *PayPal Checkout Scripts*
|Der Container *Checkout: After scripts loaded* muss verknüpft sein.

| *PayPal Confirmation Scripts*
|Der Container *Script loader: After scripts loaded* muss verknüpft sein.

| *PayPal Express Button Scripts*
|Der Container *Script loader: After scripts loaded* muss verknüpft sein.

|*PayPal Styles*
|	Der Container *Template: style* muss verknüpft sein, um die von PayPal benötigten Styles zu verwenden und optimale Funktionalität zu gewährleisten.

|*PayPal Express Button*
|Optional: Der Express-Button ist universell hinterlegbar, z.B. neben dem Warenkorb (Shopping cart). Er gibt dem Kunden die Möglichkeit, den Inhalt des gesamten Warenkorbs sofort zu kaufen, ohne den Umweg über die Kaufabwicklung zu machen. Hierbei wird er direkt zur Zahlung weitergeleitet. Die Lieferadresse wird von PayPal bereitgestellt.

|*PayPal Ratenzahlung Banner*
|Optional: Die PayPal Ratenzahlung Banner sind vielseitig hinterlegbar, um die Zahlungsart zu bewerben. Du kannst zwischen einem Grafikbanner (PayPal Installment Graphical Promotion Banner) und einem Textbanner (PayPal Installment Text Promotion Banner) wählen. Es ist keine separate Integration nötig. Im Assistenten können die Banner automatisch auf der Artikelseite, im Warenkorb oder im Checkout verknüpft werden. Zusätzlich stehen die Banner als Widgets für den ShopBuilder zur Verfügung und können somit individuell platziert werden, z.B. auf Landing Pages, auf Artikelseiten, im Warenkorb oder im Checkout.

|*PayPal Reinitialize Payment / PayPal PLUS Reinitialize Payment*
|Mit *My account: Additional payment information* verknüpfen, um dem Kunden im Mein-Konto-Bereich die Möglichkeit zu geben, nach nicht erfolgreicher Zahlung eine erneute Zahlung durchzuführen. Für PayPal wird die Schaltfläche *Jetzt zahlen* angezeigt, für PayPal PLUS wird die Wall angezeigt. +
Mit *Order confirmation: Additional payment information* verknüpfen, um dem Kunden in der Bestellbestätigung die Möglichkeit zu geben, nach nicht erfolgreicher Zahlung eine erneute Zahlung durchzuführen. Für PayPal wird die Schaltfläche *Jetzt zahlen* angezeigt, für PayPal PLUS wird die Wall angezeigt.

2+| *PayPal PLUS*

| *PayPal PLUS Wall*
|Durch die Verknüpfung mit dem Container *Checkout: Override payment method* ersetzt die PayPal PLUS Wall alle vorher eingestellten Zahlungsarten. Die Zahlungsarten, die zusätzlich zu den standardmäßig in der Wall angebotenen Zahlungsarten PayPal, Lastschrift, Kreditkarte sowie Kauf auf Rechnung eingestellt sind, werden in der Wall unter diesen gemäß ihrer Priorität angezeigt. +
Innerhalb des Assistenten stehen dir verschiedene Optionen zur Anzeige der PayPal PLUS Wall zur Verfügung: *Wall ersetzt Liste der Zahlungsarten*, *Wall innerhalb der Liste mit Zahlungsarten* oder *Wall in einem Overlay beim Kaufabschluss*.

|====

=== Webhook-Benachrichtigungen aktivieren

[TIP]
.Information zur Containerverknüpfung
====
Die standardmäßig benötigten Webhooks werden während des Einrichtens über den PayPal-Assistenten automatisch aktiviert. Individuelle Einstellungen zu Webhooks nimmst du im Schritt *Erweiterte Einstellungen* des Assistenten vor.
====

Dein plentymarkets System und die PayPal-Schnittstelle kommunizieren über sogenannte Webhooks. Bei bestimmten Ereignissen, z.B. dem Eingang einer Zahlung, sendet PayPal Webhook-Benachrichtigungen an plentymarkets. plentymarkets reagiert automatisch auf diese Benachrichtigungen. Tabelle 2 enthält zusätzliche Informationen zu den Webhooks.

[[tabelle-webhook-benachrichtigungen]]
.Webhook-Benachrichtigungen
[cols="1,3"]
|====
|Webhook |Erläuterung

| *PAYMENT.SALE.COMPLETED*
|Eine Zahlung ist abgeschlossen. Wenn PayPal diese Benachrichtigung sendet, wird die ausstehende Zahlung in plentymarkets als bezahlt markiert.

| *PAYMENT.SALE.DENIED*
|Eine Zahlung wurde verweigert. Wenn PayPal diese Benachrichtigung sendet, wird die ausstehende Zahlung in plentymarkets als nicht bezahlt markiert.

| *PAYMENT.SALE.PENDING*
|Eine ausstehende Zahlung liegt vor. Wenn PayPal diese Benachrichtigung sendet, wird die ausstehende Zahlung in plentymarkets angelegt.

| *PAYMENT.SALE.REFUNDED*
|Der Händler hat eine Zahlung teilweise oder vollständig erstattet. Wenn PayPal diese Benachrichtigung sendet, wird für die Zahlung eine Gutschrift in plentymarkets angelegt.

| *PAYMENT.SALE.REVERSED*
|Eine Zahlung wurde von PayPal rückgebucht.

|====

=== PayPal-Zahlung automatisch zurückzahlen

Richte eine Ereignisaktion ein, um die Rückzahlung einer Zahlung über PayPal zu automatisieren.

[.instruction]
Einrichtung einer Ereignisaktion:

. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das Ereignis gemäß <<tabelle-ea-automatische-rückzahlung-paypal>>.
. *Speichere* (icon:save[role=green]) die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ea-automatische-rückzahlung-paypal>> vor.
. Aktiviere die Option *Aktiv*.
. *Speichere* (icon:save[role=green]) die Einstellungen.

[[tabelle-ea-automatische-rückzahlung-paypal]]
.Ereignisaktion zur automatischen Rückzahlung der PayPal-Zahlung
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Das Ereignis wählen, auf das eine Rückzahlung folgen soll.
|

| *Filter 1*
| Auftrag > Zahlungsart
| Plugin: PayPal +
Plugin: PayPalExpress +
PayPal: PayPalPlus

| *Aktion*
| Plugin > Rückzahlung der PayPal-Zahlung
|

|====

Im Anschluss an die Aktion *Rückzahlung der PayPal-Zahlung* stehen dir stehen zwei zusätzliche Ereignisse zur Verfügung, um den weiteren Verlauf des Auftrages abzubilden: *PayPal Rückzahlung erfolgreich* und *PayPal Rückzahlung gescheitert*. Richte optional Ereignisaktionen mit diesen Ereignissen wie oben beschrieben ein.
