= PayPal
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zahlungsarten, Zahlungen, PayPal, PayPal PLUS, PayPal Rechnung, Express-Button, PayPal Ratenzahlung, PayPal-Rechnung, PayPal-Ratenzahlung, PayPal-Plugin, PayPalplugin, PayPal-Assistent, PayPalassistent, PayPal-Konfiguration, PayPalkonfiguration, Paypalzahlung, Paypal-Zahlung, Paypal-Zahlungsart, Paypalzahlungsart, PayPal-Geschäftskonto, Paypalkonto, Paypal-Konto, Paypalgeschäftskonto, Adressvalidierung, Paypal-Adressvalidierung, Paypal-Template, Paypaltemplate, paypal-Checkout, Checkout, Paypal-Style, PayPal-Wall, Paypal Wall, PayPalwall, PayPal-Banner, PayPal-Plus, PayPal-Webhook, Paypal-Schnittstelle, Paypal-Konfiguration, Paypalkonfiguration, PayPal-Rückzahlung, Paypalrückzahlung, Paypalexpress, PayPal-Express, PayPalPlus, Zahlungsplugin, Zahlungs-Plugin, Payment-Plugin, Paymentplugin, Payment-Integration, Paymentintegration, Paymentschnittstelle, Payment-Schnittstelle
:description: Integration des PayPal-Plugins.
:position: 90
:url: payment/payment-plugins/paypal
:id: K9UYAY1
:author: team-order-payment

Mit dem PayPal-Plugin bindest du die *PayPal-Zahlungsarten* in deinen Webshop ein und stellst sie so deinen Kund:innen zur Auswahl. Lade dafür das PayPal-Plugin im link:https://marketplace.plentymarkets.com/paypal_4690[plentyMarketplace^]{nbsp}icon:external-link[] herunter. Die Einrichtung der Zahlungsarten erfolgt erfolgt über einen Assistenten. Zudem musst du einige grundlegende Einstellungen in deinem plentymarkets System ausführen, damit die Zahlungsarten auch in deinem System aktiviert sind. +
Die Erklärungen auf dieser Seite finden nach dem Hinzufügen des Plugins Anwendung. Allgemeine Informationen zum Hinzufügen und Installieren von Plugins findest du im Abschnitt <<plugins#, Plugins>> des Handbuchs.

[#10]
== Voraussetzung: Eröffnung eines PayPal-Geschäftskontos

Für die Nutzung von PayPal benötigst du ein PayPal-Geschäftskonto. Durch die Eröffnung des Kontos erhältst du Informationen sowie Zugangsdaten. Liegen diese nicht vor, kannst du das Plugin nicht einrichten und somit nicht nutzen. Solltest du noch keines haben, link:https://www.paypal.com/de/business[eröffne ein PayPal-Geschäftskonto^]{nbsp}icon:external-link[].

[#20]
== Ausführen des Assistenten

[IMPORTANT]
.Aktivierung in Plugin-Set des Hauptmandanten
====
Für die Kontoverknüpfung und die Funktionsweise der Ereignisaktionen muss das PayPal-Plugin in dem Plugin-Set aktiviert sein, das für den Hauptmandanten verwendet wird. Da eine Abhängigkeit zum IO-Plugin besteht, musst du IO für den Bereitstellungsprozess (Speichern im Plugin-Set) aktivieren.
====

:name-des-assistenten: PayPal
:name-der-zahlungsart: PayPal

include::../_textblocks/ausfuehrung-assistent.adoc[]

[.collapseBox]
.*Informationen zur Adressvalidierung*
--

Im PayPal-Assistenten gibt es im Bereich *Auftragsabwicklung* den Punkt *Adressvalidierung*. Diese ist _automatisch aktiviert_. Zur Deaktivierung der Validierung musst du eine Auswahl treffen. Du kannst die Validierung entweder für alle oder für einzelne Länder deaktivieren. Setze dafür einen Haken (icon:check-square[role="blue"]) bei den Ländern, für die Adressen nicht validiert werden sollen. +
Wenn die Zahlung auch mit einer unvollständigen Adresse durchgeführt werden soll, solltest du die Adressvalidierung deaktivieren.

Die standardmäßige Validierung ist eine Anforderung von PayPal. Durch die Validierung wird geprüft, ob eine vollständige Adresse vorhanden ist. Es wird nicht geprüft, ob diese Adresse tatsächlich existiert. Nur wenn eine vollständige Adresse vorhanden ist, wird der erfolgreiche Zahlungsabschluss durchgeführt. +
Die Adressvalidierung von PayPal ist wichtig für die Absicherung beim Versand der Ware. Zudem bietet PayPal den Käufer- und Verkäuferschutz an, der gerade bei der Auftragsabwicklung über PayPal Express entscheidend ist. In diesem Fall wird die Adresse von PayPal selbst übernommen.

--

[#30]
== Widgets im ShopBuilder

Der PayPal Express-Button und die PayPal Ratenzahlung Banner stehen im ShopBuilder als Widgets zur Verfügung.

[#40]
== Template-Container verknüpfen

[IMPORTANT]
.Information zur Containerverknüpfung
====
Die standardmäßig benötigten Container werden während des Einrichtens über den PayPal-Assistenten automatisch für deinen Webshop verknüpft. Ab Version 5.4.0 werden benötigte und optionale Container in dem Plugin-Set verknüpft, in dem der Assistent durchlaufen wird.
====

Für die Zahlungsart PayPal PLUS, für den PayPal Express-Button und für die PayPal Ratenzahlung Banner stehen dir verschiedene Möglichkeiten zur Verfügung, um sie in deinen Shop einzubinden. Hierfür sind in den Templates in plentymarkets an relevanten Stellen Container hinterlegt, mit denen zur Individualisierung Contents verknüpft werden.

[.instruction]
Container verknüpfen:

. Öffne das Menü *Plugins » Plugin-Set-Übersicht*.
. Öffne das Plugin-Set, das du bearbeiten möchtest.
. Öffne das Plugin *PayPal*
. Klicke auf *Container-Verknüpfungen*.
. Wähle aus der Dropdown-Liste den Datenanbieter, den du verknüpfen möchtest.
. Wähle den Container, mit dem du den Datenanbieter verknüpfen möchtest. Beachte dazu die Erläuterungen in <<tabelle-containerverknüpfung>>.
. Wiederhole Schritte 5 und 6 für alle Datenanbieter, die du verknüpfen möchtest.
. *Speichere* (icon:save[role=green]) die Einstellungen.

[[tabelle-containerverknüpfung]]
.Container verknüpfen
[cols="1,3"]
|====
|Content |Erläuterung

2+| *Allgemein*

| *PayPal Checkout Scripts*
|Der Container *Checkout: After scripts loaded* muss verknüpft sein.

| *PayPal Confirmation Scripts*
|Der Container *Script loader: After scripts loaded* muss verknüpft sein.

| *PayPal Express Button Scripts*
|Der Container *Script loader: After scripts loaded* muss verknüpft sein.

|*PayPal Styles*
|	Der Container *Template: style* muss verknüpft sein, um die von PayPal benötigten Styles zu verwenden und optimale Funktionalität zu gewährleisten.

|*PayPal Express Button*
|Optional: Der Express-Button ist universell hinterlegbar, z.B. neben dem Warenkorb (Shopping cart). Er gibt Kund:innen die Möglichkeit, den Inhalt des gesamten Warenkorbs sofort zu kaufen, ohne den Umweg über die Kaufabwicklung zu machen. Hierbei wird er direkt zur Zahlung weitergeleitet. Die Lieferadresse wird von PayPal bereitgestellt.

|*PayPal Ratenzahlung Banner*
|Optional: Die PayPal Ratenzahlung Banner sind vielseitig hinterlegbar, um die Zahlungsart zu bewerben. Du kannst zwischen einem Grafikbanner (PayPal Installment Graphical Promotion Banner) und einem Textbanner (PayPal Installment Text Promotion Banner) wählen. Es ist keine separate Integration nötig. Im Assistenten können die Banner automatisch auf der Artikelseite, im Warenkorb oder im Checkout verknüpft werden. Zusätzlich stehen die Banner als Widgets für den ShopBuilder zur Verfügung und können somit individuell platziert werden, z.B. auf Landing Pages, auf Artikelseiten, im Warenkorb oder im Checkout.

|*PayPal Reinitialize Payment / PayPal PLUS Reinitialize Payment*
|Mit *My account: Additional payment information* verknüpfen, um Kund:innen im Mein-Konto-Bereich die Möglichkeit zu geben, nach nicht erfolgreicher Zahlung eine erneute Zahlung durchzuführen. Für PayPal wird die Schaltfläche *Jetzt zahlen* angezeigt, für PayPal PLUS wird die Wall angezeigt. +
Mit *Order confirmation: Additional payment information* verknüpfen, um Kund:innen in der Bestellbestätigung die Möglichkeit zu geben, nach nicht erfolgreicher Zahlung eine erneute Zahlung durchzuführen. Für PayPal wird die Schaltfläche *Jetzt zahlen* angezeigt, für PayPal PLUS wird die Wall angezeigt.

2+| *PayPal PLUS*

| *PayPal PLUS Wall*
|Durch die Verknüpfung mit dem Container *Checkout: Override payment method* ersetzt die PayPal PLUS Wall alle vorher eingestellten Zahlungsarten. Die Zahlungsarten, die zusätzlich zu den standardmäßig in der Wall angebotenen Zahlungsarten PayPal, Lastschrift, Kreditkarte sowie Kauf auf Rechnung eingestellt sind, werden in der Wall unter diesen gemäß ihrer Priorität angezeigt. +
Innerhalb des Assistenten stehen dir verschiedene Optionen zur Anzeige der PayPal PLUS Wall zur Verfügung: *Wall ersetzt Liste der Zahlungsarten*, *Wall innerhalb der Liste mit Zahlungsarten* oder *Wall in einem Overlay beim Kaufabschluss*. +
Beachte auch den Abschnitt <<payment/payment-plugins/paypal#50, Weitere Informationen zur PayPal PLUS Wall>>. Dort werden neben zusätzlichen Informationen auch Beschränkungen beschrieben.

|====

[#50]
=== Weitere Informationen zur PayPal PLUS Wall

In der PayPal PLUS Wall können, neben den PayPal PLUS Zahlungsarten, 10 weitere Zahlungsarten im Checkout ausgegeben werden. +
Beispielsweise sind für Deutschland die Zahlungsarten PayPal, Lastschrift, Kreditkarte und Kauf auf Rechnung möglich. Insgesamt wäre damit eine maximale Anzahl von 14 Zahlungsarten im Checkout möglich.
Wenn aber beispielsweise nur PayPal und Kreditkarte im Lieferland zur Verfügung stehen, dann ist die maximale Anzahl auf 12 beschränkt.

Zudem beschränkt die PayPal Plus Wall die maximalen Zeichen für die Namen anderer Zahlungsarten. Die Zeichenanzahl ist auf 25 beschränkt. Wenn ein Name länger als 25 Zeichen ist, dann wird der Name nach dem 25. Zeichen abgeschnitten. +
Hierbei ist zu beachten, dass Sonderzeichen, bspw. Umlaute, die Anzahl verringert, da die Sonderzeichen in ihrer HTML-Schreibweise ausgegeben werden.

PayPal gibt Folgendes an:

* max. Bildgröße von 100 x 25 px +
* max. 25 Zeichen für _methodName_ +
* max. 120 Zeichen für _description_

[#60]
== Webhook-Benachrichtigungen aktivieren

[TIP]
.Information zur Containerverknüpfung
====
Die standardmäßig benötigten Webhooks werden während des Einrichtens über den PayPal-Assistenten automatisch aktiviert. Individuelle Einstellungen zu Webhooks nimmst du im Schritt *Erweiterte Einstellungen* des Assistenten vor.
====

Dein plentymarkets System und die PayPal-Schnittstelle kommunizieren über sogenannte Webhooks. Bei bestimmten Ereignissen, z.B. dem Eingang einer Zahlung, sendet PayPal Webhook-Benachrichtigungen an plentymarkets. plentymarkets reagiert automatisch auf diese Benachrichtigungen. Tabelle 2 enthält zusätzliche Informationen zu den Webhooks.

[[tabelle-webhook-benachrichtigungen]]
.Webhook-Benachrichtigungen
[cols="1,3"]
|====
|Webhook |Erläuterung

| *PAYMENT.SALE.COMPLETED*
|Eine Zahlung ist abgeschlossen. Wenn PayPal diese Benachrichtigung sendet, wird die ausstehende Zahlung in plentymarkets als bezahlt markiert.

| *PAYMENT.SALE.DENIED*
|Eine Zahlung wurde verweigert. Wenn PayPal diese Benachrichtigung sendet, wird die ausstehende Zahlung in plentymarkets als nicht bezahlt markiert.

| *PAYMENT.SALE.PENDING*
|Eine ausstehende Zahlung liegt vor. Wenn PayPal diese Benachrichtigung sendet, wird die ausstehende Zahlung in plentymarkets angelegt.

| *PAYMENT.SALE.REFUNDED*
|Der Händler hat eine Zahlung teilweise oder vollständig erstattet. Wenn PayPal diese Benachrichtigung sendet, wird für die Zahlung eine Gutschrift in plentymarkets angelegt.

| *PAYMENT.SALE.REVERSED*
|Eine Zahlung wurde von PayPal rückgebucht.

|====

[#70]
== Zahlungsart einmalig aktivieren

include::../_textblocks/zahlungsart-aktivieren.adoc[]

[#80]
== Kundenklassen und Versandprofile

include::../_textblocks/kundenklassen-und-versandprofile.adoc[]

[#90]
== PayPal-Zahlung automatisch zurückzahlen

Richte eine Ereignisaktion ein, um die Rückzahlung einer Zahlung über PayPal zu automatisieren.

[.collapseBox]
.*Ereignisaktion einrichten*
--

[.instruction]
Einrichtung einer Ereignisaktion:

. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das Ereignis gemäß <<tabelle-ea-automatische-rückzahlung-paypal>>.
. *Speichere* (icon:save[role=green]) die Einstellungen.
. Nimm die Einstellungen gemäß <<tabelle-ea-automatische-rückzahlung-paypal>> vor.
. Aktiviere die Option *Aktiv*.
. *Speichere* (icon:save[role=green]) die Einstellungen.

--

[[tabelle-ea-automatische-rückzahlung-paypal]]
.Ereignisaktion zur automatischen Rückzahlung der PayPal-Zahlung
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

| *Ereignis*
| Das Ereignis wählen, auf das eine Rückzahlung folgen soll.
|

| *Filter 1*
| Auftrag > Zahlungsart
| Plugin: PayPal +
Plugin: PayPalExpress +
PayPal: PayPalPlus

| *Aktion*
| Plugin > Rückzahlung der PayPal-Zahlung
|

|====

Im Anschluss an die Aktion *Rückzahlung der PayPal-Zahlung* stehen dir stehen zwei zusätzliche Ereignisse zur Verfügung, um den weiteren Verlauf des Auftrages abzubilden: *PayPal Rückzahlung erfolgreich* und *PayPal Rückzahlung gescheitert*. Richte optional Ereignisaktionen mit diesen Ereignissen wie oben beschrieben ein.

[#100]
== Sprachelemente anpassen

Du kannst Benennungen, die das PayPal-Plugin mitbringt, im Menü *CMS » Mehrsprachigkeit* nach deinen Bedürfnissen in allen verfügbaren Systemsprachen anpassen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Sprachdateien anpassen:

. Öffne das Menü *CMS » Mehrsprachigkeit.*
. Wähle auf der linken Seite die *Ausgangssprache* aus der Dropdown-Liste.
. Wähle auf der rechten Seite die *Zielsprache* aus der Dropdown-Liste.
. Klappe im Bereich *PayPal* die verschiedenen Sektionen aus.
. Gib im Bereich der Zielsprache die gewünschten Texte für die einzelnen Sprachelemente ein.
. Speichere (icon:save[role=green]) die Einstellungen.

Weitere Informationen zum Bearbeiten von im Webshop angezeigten Texten findest du auf der Handbuchseite <<webshop/ceres-einrichten#231, Ceres-Webshop einrichten>>.
