= Sofortüberweisung von Klarna
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zahlungsarten, Zahlungen, Klarna, Sofort, Sofortüberweisung
:description: Integration des Sofort-Plugins
:position:
:url: payment/payment-plugins/sofort
:id: CT0BWMM
:author: team-order-payment

Mit dem Sofort-Plugin bindest du die Klarna-Zahlungsart *Sofort* in deinen Webshop ein und stellst sie so deinen Kund:innen zur Auswahl. Lade dafür das Sofort-Plugin im link:https://marketplace.plentymarkets.com/sofort_5050[plentyMarketplace^]{nbsp}icon:external-link[] herunter. Für die Einrichtung der Zahlungsart musst du einige grundlegende Einstellungen in deinem plentymarkets System ausführen, damit sie auch in deinem System aktiviert ist. +
Die Erklärungen auf dieser Seite finden nach dem Hinzufügen des Plugins Anwendung. Allgemeine Informationen zum Hinzufügen und Installieren von Plugins findest du im Abschnitt <<plugins#, Plugins>> des Handbuchs.

[#10]
== Voraussetzung: Eröffnung eines Geschäftskontos

Für die Nutzung von Sofort benötigst du ein link:https://www.sofort.com/payment/users/register[Geschäftskonto^]{nbsp}icon:external-link[]. Durch die Eröffnung des Kontos erhältst du Informationen sowie Zugangsdaten. Liegen diese nicht vor, kannst du das Plugin nicht einrichten und somit nicht nutzen.

[#20]
== Zahlungsart einrichten

Bevor du die Funktionen des Sofort-Plugins nutzen kannst, musst du zuerst dein Sofort-Konto mit deinem plentymarkets System verbinden.

[.instruction]
Sofort-Konto anbinden:

. Öffnen Sie das Menü *Plugins » Plugins-Set-Übersicht » [Plugin-Set wählen]*
. Öffne das Plugin *Sofort*
. Öffne im Plugin das Menü *Konfiguration » Grundeinstellungen*. +
→ Beachte die Erläuterungen in <<tabelle-plugineinstellungen>>.
. Gib den Konfigurationsschlüssel ein. +
→ Diesen Schlüssel erhältst du durch den Registrierungsprozess.
. Nimm weitere Einstellungen nach Bedarf im Bereich *Erweiterte Einstellungen* vor.
. *Speichere* (icon:save[role=green]) die Einstellungen.

[[tabelle-plugineinstellungen]]
.Container verknüpfen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+| *Grundeinstellungen*

| *Zahlungsart aktivieren*
|Standardmäßig ist hier *Nein* ausgewählt. Zum Aktivieren der Zahlungsart *Ja* auswählen.

| *Konfigurationsschlüssel*
|Den Konfigurationsschlüssel erhältst du nach der link:https://www.sofort.com/payment/users/register[Registrierung^]{nbsp}icon:external-link[].
Ohne korrekte Eingabe wird die Zahlungsart nicht aktiviert. +
Beispiel für den Aufbau des Konfigurationsschlüssels: {Kundennummer}:{Projekt-ID}:{API-Key}

|*Auftragsstatus in Status 4/5 setzen*
|Aktiviere diese Option, wenn Aufträge mit der Zahlungsart *Sofort* im System direkt Status 4 oder 5 erhalten sollen.

2+| *Erweiterte Einstellungen*

| *Grund 1*
|Legt den Text fest, der als Verwendungszweck bei der Überweisung angegeben wird (max. 27 Zeichen - Sonderzeichen werden ersetzt/gelöscht). Folgende Platzhalter werden mit konkreten Werten ersetzt: +
{{transaction_id}} = Transaktions-ID der Überweisung +
{{customer_name}} = Name des Endkunden +
{{customer_email}} = E-Mail Adresse des Endkunden +
Standard: {{transaction_id}}

| *Grund 2*
|Hier gilt das gleiche wie bei Verwendungszweck 1. Zusätzlich sind folgende Platzhalter möglich: +
{{customer_id}} = Endkundennummer +
{{customer_company}} = Firmenname des Endkunden +
Standard: -

|====

[#30]
== Zahlungsart einmalig aktivieren

include::../_textblocks/zahlungsart-aktivieren.adoc[]

[#40]
== Kundenklassen und Versandprofile

include::../_textblocks/kundenklassen-und-versandprofile.adoc[]
