= Sofortüberweisung von Klarna
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zahlungsarten, Zahlungen, Klarna, Sofort, Sofortüberweisung
:description: Integration des Sofort-Plugins
:position:
:url: payment/payment-plugins/sofort
:id: CT0BWMM
:author: team-order-payment

== Voraussetzung: Eröffnung eines Klarna-Händlerkontos

Für die Nutzung von Sofort benötigst du ein link:https://www.sofort.com/payment/users/register[Geschäftskonto^]{nbsp}icon:external-link[]. Durch die Eröffnung des Kontos erhältst du Informationen sowie Zugangsdaten. Liegen diese nicht vor, kannst du das Plugin nicht einrichten und somit nicht nutzen.

== Zahlungsart einrichten

Bevor du die Funktionen des Sofort-Plugins nutzen kannst, musst du zuerst dein Sofort-Konto mit deinem plentymarkets System verbinden.

[.instruction]
Sofort-Konto anbinden:

. Öffnen Sie das Menü *Plugins » Plugins-Set-Übersicht » [Plugin-Set wählen]*
. Öffne das Plugin *Sofort*
. Wähle *Konfiguration*.
. Gib den Konfigurationsschlüssel ein. +
→ Diesen Schlüssel erhältst du durch den Registrierungsprozess.
. Nimm weitere Einstellungen nach Bedarf im Bereich *Erweiterte Einstellungen* vor.
. *Speichere* (icon:save[role=green]) die Einstellungen.

[[tabelle-plugineinstellungen]]
.Container verknüpfen
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+| *Grundeinstellungen*

| *Zahlungsart aktivieren*
|Standard: Nein

| *Konfigurationsschlüssel*
|Den Konfigurationsschlüssel erhältst du nach der link:https://www.sofort.com/payment/users/register[Registrierung^]{nbsp}icon:external-link[].
Ohne korrekte Eingabe wird die Zahlungsart nicht aktiviert. +
Beispiel für den Aufbau des Konfigurationsschlüssels: {Kundennummer}:{Projekt-ID}:{API-Key}

2+| *Erweiterte Einstellungen*

| *Verwendungszweck (Zeile 1) (Pflichtangabe)*
|Legt den Text fest, der als Verwendungszweck bei der Überweisung angegeben wird (max. 27 Zeichen - Sonderzeichen werden ersetzt/gelöscht). Folgende Platzhalter werden mit konkreten Werten ersetzt: +
{{transaction_id}} = Transaktions-ID der Überweisung +
{{customer_name}} = Name des Endkunden +
{{customer_email}} = E-Mail Adresse des Endkunden +
Standard: {{transaction_id}}

| *Verwendungszweck (Zeile 2)*
|Hier gilt das gleiche wie bei Verwendungszweck 1. Zusätzlich sind folgende Platzhalter möglich: +
{{customer_id}} = Endkundennummer +
{{customer_company}} = Firmenname des Endkunden +
Standard: -

|====
