= Vorkasse
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zahlungsarten, Zahlungen, Vorkasse
:description: Integration des Plugins Vorkasse
:position:
:url: payment/payment-plugins/vorkasse
:id: C63BSZD
:author: team-order-payment

Mit dem Vorkasse-Plugin bindest du die Zahlungsart *Vorkasse* in deinen Webshop ein und stellst sie so deinen Kund:innen zur Auswahl. Lade dafür das Vorkasse-Plugin im link:https://marketplace.plentymarkets.com/prepayment_4758[plentyMarketplace^]{nbsp}icon:external-link[] herunter. Die Einrichtung der Zahlungsart erfolgt über einen Assistenten. Zudem musst du einige grundlegende Einstellungen in deinem plentymarkets System ausführen, damit die Zahlungsart auch in deinem System aktiviert ist. +
Die Erklärungen auf dieser Seite finden nach dem Hinzufügen des Plugins Anwendung. Allgemeine Informationen zum Hinzufügen und Installieren von Plugins findest du im Abschnitt <<plugins#, Plugins>> des Handbuchs.

[#10]
== Ausführung des Assistenten

:name-des-assistenten: Vorkasse
:name-der-zahlungsart: Vorkasse

include::../_textblocks/ausfuehrung-assistent.adoc[]

[#20]
== Zahlungsart einmalig aktivieren

include::../_textblocks/zahlungsart-aktivieren.adoc[]

[#30]
== Kundenklassen und Versandprofile

include::../_textblocks/kundenklassen-und-versandprofile.adoc[]

[#40]
== Sprachelemente anpassen

Du kannst Benennungen, die das Vorkasse-Plugin mitbringt, im Menü *CMS » Mehrsprachigkeit* nach deinen Bedürfnissen in allen verfügbaren Systemsprachen anpassen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Sprachdateien anpassen:

. Öffne das Menü *CMS » Mehrsprachigkeit.*
. Wähle auf der linken Seite die *Ausgangssprache* aus der Dropdown-Liste.
. Wähle auf der rechten Seite die *Zielsprache* aus der Dropdown-Liste.
. Klappe im Bereich *PrePayment* die Sektionen *Bankdaten*, *Reinitialisierung*, *Verwendungszweck* und *Zahlungsart* aus.
. Gib im Bereich der Zielsprache die gewünschten Texte für die einzelnen Sprachelemente ein.
. Speichere (icon:save[role=green]) die Einstellungen.

Weitere Informationen zum Bearbeiten von im Webshop angezeigten Texten findest du auf der Handbuchseite <<webshop/ceres-einrichten#231, Ceres-Webshop einrichten>>.
