= Vorkasse
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Zahlungsarten, Zahlungen, Vorkasse
:description: Integration des Plugins Vorkasse
:position:
:url: payment/payment-plugins/vorkasse
:id: C63BSZD
:author: team-order-payment

Mit dem Plugin *Vorkasse* bindest du die Zahlungsart Vorkasse in deinem Webshop ein und stellst sie so deinen Kund:innen zur Auswahl. Die Integration erfolgt über einen Assistenten. Zudem musst du einige grundlegende Einstellungen in deinem plentymarkets System ausführen, damit die Zahlungsart auch in deinem System aktiviert ist.
Die Erklärungen auf der Seite finden nach dem Hinzufügen des Plugins Anwendung. Allgemeine Informationen zum Hinzufügen und Installieren von Plugins findest du im Abschnitt <<plugins#, Plugins>> des Handbuchs.

[#10]
== Zahlungsart einmalig aktivieren

Aktiviere als erstes die Zahlungsart einmalig in deinem System. Beachte, dass nur die Aktivierung der Zahlungsart notwendig ist. Alle weitere Einstellungen, wie z.B. zu Mandanten oder Lieferländern, haben keine Auswirkungen.

[.instruction]
Aktivierung der Zahlungsart:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Wähle die zu aktivierende Zahlungsart aus.
. Aktiviere die Option *Aktiv* (icon:check-square[role="blue"]).
. Speichere (icon:save[role=green]) die Einstellungen.

[#20]
== Kundenklassen und Versandprofile

Stelle sicher, dass die Zahlungsart in den <<crm/kontakte-verwalten#15, Kundenklassen>> erlaubt ist und auch in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>> nicht gesperrt ist. Überlege dir hierfür, für welche Kundenklassen und Versandprofile die Zahlungsart gelten soll. Dies ist in jedem System individuell einstellbar.

[.instruction]
Zahlungsart in Kundenklasse erlauben:

. Öffne das Menü *Einrichtung » CRM » Kundenklassen*.
. Öffne die Kundenklasse, in dem die Zahlungsart erlaubt werden soll.
. Wähle die Zahlungsart aus der Liste im Bereich *Erlaubte Zahlungsarten* durch Anklicken aus.
. Speichere (icon:save[role=green]) die Einstellungen.

Wiederhole dies ggf. für weitere Kundenklassen.

[.instruction]
Zahlungsart in bestehenden Versandprofilen überprüfen:

. Öffne das Menü *Einrichtung » Aufträge » Versand » Optionen*.
. Wechsel in das Tab *Versandprofile*.
. Öffne das Versandprofil, in dem die Zahlungsart erlaubt sein soll.
. Überprüfe, ob die Zahlungsart im Bereich *Gesperrte Zahlungsarten* ausgewählt ist.
. Entferne die Auswahl der Zahlungsart, wenn sie für dieses Versandprofil erlaubt sein soll.
. Speichere (icon:save[role=green]) die Einstellungen.

Wiederhole dies ggf. für weitere Versandprofile.

[#30]
== Ausführung des Assistenten

Nachdem du diese grundlegenden Einstellungen ausgeführt hast, gehe nun wie folgt vor, um den Assistenten auszuführen und somit die Zahlungsart einzurichten.

[.instruction]
Zahlungsart einrichten:

. Öffne das Menü *Einrichtung » Assistenten » Plugins » [Plugin-Set wählen]*.
. Wähle den Assistenten *Vorkasse*.
. Schließe den Assistenten vollständig ab. +
→ Die Zahlungsart Vorkasse ist in deinem Webshop verfügbar.

[#40]
== Sprachelemente anpassen

Du kannst Benennungen, die das Vorkasse-Plugin mitbringt, im Menü *CMS » Mehrsprachigkeit* nach deinen Bedürfnissen in allen verfügbaren Systemsprachen anpassen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Sprachdateien anpassen:

. Öffne das Menü *CMS » Mehrsprachigkeit.*
. Wähle auf der linken Seite die *Ausgangssprache* aus der Dropdown-Liste.
. Wähle auf der rechten Seite die *Zielsprache* aus der Dropdown-Liste.
. Klappe im Bereich *PrePayment* die Sektionen *Bankdaten*, *Reinitialisierung*, *Verwendungszweck* und *Zahlungsart* aus.
. Gib im Bereich der Zielsprache die gewünschten Texte für die einzelnen Sprachelemente ein.
. Speichere (icon:save[role=green]) die Einstellungen.

Weitere Informationen zum Bearbeiten von im Webshop angezeigten Texten findest du auf der Handbuchseite <<webshop/ceres-einrichten#231, Ceres-Webshop einrichten>>.
