= PHPFunctions
:lang: en
include::{includedir}/_header.adoc[]
:keywords: PHPFunctions
:position: 1

//  auto generated content Thu, 06 Jul 2017 00:59:22 +0200
toc::[]
== Short description

The following PHP functions can also be used in the CMS syntax. Their usage corresponds to that directly in PHP.

== Global Template Functions

* <<cms-syntax/global/phpfunctions/array-key-exists#, array_key_exists  >> — Checks if a key exists in the array.
* <<cms-syntax/global/phpfunctions/arsort#, arsort  >> — Sorts an array in reverse order while maintaining the index association.
* <<cms-syntax/global/phpfunctions/asort#, asort  >> — Sorts an array while maintaining the index association.
* <<cms-syntax/global/phpfunctions/bin2hex#, bin2hex  >> — Returns an ASCII string that contains the parameter's hexadecimal output.
* <<cms-syntax/global/phpfunctions/ceil#, ceil  >> — Returns the next integer that is greater than or equal to the parameter.
* <<cms-syntax/global/phpfunctions/count#, count  >> — Counts all elements in an array or attributes in an object.
* <<cms-syntax/global/phpfunctions/curl-close#, curl_close  >> — Ends a cURL session.
* <<cms-syntax/global/phpfunctions/curl-exec#, curl_exec  >> — Runs a cURL session.
* <<cms-syntax/global/phpfunctions/curl-init#, curl_init  >> — Starts a cURL session.
* <<cms-syntax/global/phpfunctions/curl-setopt#, curl_setopt  >> — Sets an option for a cURL transfer.
* <<cms-syntax/global/phpfunctions/current#, current  >> — Returns the current element in an array.
* <<cms-syntax/global/phpfunctions/date#, date  >> — Formats a specified local time / date.
* <<cms-syntax/global/phpfunctions/explode#, explode  >> — Splits a string by string to create an array.
* <<cms-syntax/global/phpfunctions/floor#, floor  >> — Returns the next integer that is less than or equal to the parameter.
* <<cms-syntax/global/phpfunctions/htmlentities#, htmlentities  >> — Converts all suitable characters to HTML codes.
* <<cms-syntax/global/phpfunctions/implode#, implode  >> — Combines array elements to a string.
* <<cms-syntax/global/phpfunctions/in-array#, in_array  >> — Checks if a value exists in an array.
* <<cms-syntax/global/phpfunctions/is-array#, is_array  >> — Checks if the variable is an array.
* <<cms-syntax/global/phpfunctions/is-numeric#, is_numeric  >> — Checks if a variable is a number or a numeric string.
* <<cms-syntax/global/phpfunctions/is-string#, is_string  >> — Checks if the variable is of the type String.
* <<cms-syntax/global/phpfunctions/json-decode#, json_decode  >> — Decodes a JSON character string. The result can be saved to a local template variable.
* <<cms-syntax/global/phpfunctions/json-encode#, json_encode  >> — Returns the JSON representation of a value.
* <<cms-syntax/global/phpfunctions/krsort#, krsort  >> — Sorts an array by keys in reverse order.
* <<cms-syntax/global/phpfunctions/ksort#, ksort  >> — Sorts an array by keys.
* <<cms-syntax/global/phpfunctions/md5#, md5  >> — Calculate a string's MD5 hash.
* <<cms-syntax/global/phpfunctions/natcasesort#, natcasesort  >> — Sorts an array by natural order ignoring case.
* <<cms-syntax/global/phpfunctions/natsort#, natsort  >> — Sorts an array by natural order.
* <<cms-syntax/global/phpfunctions/nl2br#, nl2br  >> — Inserts HTML line wraps before all line wraps of a string.
* <<cms-syntax/global/phpfunctions/number-format#, number_format  >> — Formats a number with grouped thousands.
* <<cms-syntax/global/phpfunctions/print#, print  >> — Returns the contained value as HTML. Permitted values are a template variable or a string.
* <<cms-syntax/global/phpfunctions/round#, round  >> — Rounds the first parameter to the number of decimal places specified in the second parameter.
* <<cms-syntax/global/phpfunctions/rsort#, rsort  >> — Sorts an array in reverse order.
* <<cms-syntax/global/phpfunctions/simplexml-load-string#, simplexml_load_string  >> — Converts a string to a simpleXML object and returns this object.
* <<cms-syntax/global/phpfunctions/sort#, sort  >> — Sorts an array.
* <<cms-syntax/global/phpfunctions/str-replace#, str_replace  >> — Replaces all occurrences of a search string by a different string.
* <<cms-syntax/global/phpfunctions/strip-tags#, strip_tags  >> — Removes HTML tags from a string.
* <<cms-syntax/global/phpfunctions/stripos#, stripos  >> — Finds the first occurrence of a string ignoring case.
* <<cms-syntax/global/phpfunctions/strlen#, strlen  >> — Detects the string length.
* <<cms-syntax/global/phpfunctions/strpos#, strpos  >> — Finds the search string's first occurrence.
* <<cms-syntax/global/phpfunctions/strtolower#, strtolower  >> — Makes a string lowercase.
* <<cms-syntax/global/phpfunctions/strtotime#, strtotime  >> — Parses any English date format into a Unix timestamp.
* <<cms-syntax/global/phpfunctions/strtoupper#, strtoupper  >> — Makes all characters of a string uppercase.
* <<cms-syntax/global/phpfunctions/substr#, substr  >> — Returns part of a string.
* <<cms-syntax/global/phpfunctions/trim#, trim  >> — Strips whitespace or other characters from the beginning and end of a string.

== Global Template Variables

* $ENT_COMPAT — Constant: Only converts double quotation marks. Single quotation marks are not converted and remain unchanged.
* $ENT_QUOTES — Constant: Converts both double and single quotation marks.

