= Bearbeitungsfenster selbst gestalten
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ##Artikel##, Variante, Produkt, Produkte, Standard-Artikel, Artikel des Typs Standard, Artikel vom Typ Standard, Artikel erstellen, Artikeldaten erstellen, Artikel anlegen, Artikeldaten anlegen, Variante erstellen, Variantendaten erstellen, Variante anlegen, Variantendaten anlegen, Artikelanlage, Artikelverwaltung, Artikel verwalten, Artikel bearbeiten, Artikel manuell anlegen, Artikel manuell erstellen, Artikeldaten, Artikeldatensatz, Artikeldatensätze, Neuer Artikel, Neue Artikel, Assistant, Assistent, Assistenten, ElasticSync, Import, Importieren, Datenaustausch, Daten-Export, Datenexport, Daten-Import, Datenimport, Artikelimport, Artikel importieren, Varianten importieren, Artikeldaten importieren, Variantendaten importieren, CSV, Artikel exportieren, Artikelexport, Artikeldaten exportieren, FormatDesigner, Format-Typen, Daten
:description: ##Erfahre##, wie du deine Artikeldaten in plentymarkets importierst, exportierst und manuell verwaltest.
:position: 20
:url: artikel/import-export-anlage/anlage/bearbeitungsfenster-gestalten
:id: 864QUOC
:author: team-item

##Einleitung##


=== Anzeige von Artikeldaten in Artikel-Tabs personalisieren

Standardmäßig wird in den Tabs von Artikeln die Artikel-ID angezeigt. Statt die Artikel-ID im Tab anzuzeigen, kannst du den Namen oder die Nummer der Hauptvariante des Artikels anzeigen lassen. Gehe wie unten beschrieben vor, um die angezeigten Artikeldaten zu ändern.

[.instruction]
Anzeige von Artikeldaten in Artikel-Tabs personalisieren:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne einen Artikel. +
→ Das Tab *Einstellungen* der Hauptvariante wird geöffnet.
. Zeige mit der Maus auf das Tab des Artikels.
. Klicke auf die rechte Maustaste. +
→ Eine Dropdown-Liste wird angezeigt.
. Klicke auf *Umbenennen*. +
→ Das Fenster *Tab-Titel wählen* wird angezeigt.
. Wähle, ob im Tab-Titel von Artikeln die *Artikel-ID*, der *Variantenname der Hauptvariante* oder die *Variantennummer der Hauptvariante* angezeigt werden soll.
. Klicke auf **Umbenennen**. +
→ Die gewählten Artikeldaten werden in allen Tabs angezeigt. +
→ Wenn *Variantenname der Hauptvariante* oder *Variantennummer der Hauptvariante* eingestellt wird und diese Daten für einen Artikel nicht gespeichert sind, wird stattdessen die *Artikel-ID* angezeigt. +
**__Tipp:__** Die Anzeige im Tab des aktuell geöffneten Artikels ändert sich erst, nachdem der Artikel neu geladen wird.



=== Anzeige der Variantendaten in Varianten-Tabs personalisieren

Standardmäßig wird in den Tabs von Varianten die Varianten-ID angezeigt. Stattdessen kannst du den Variantennamen oder die Variantennummer anzeigen lassen. Gehe wie unten beschrieben vor, um die angezeigten Variantendaten zu ändern.

[.instruction]
Anzeige der Variantendaten in Varianten-Tabs personalisieren:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne einen Artikel. +
→ Das Tab **Einstellungen** der Hauptvariante wird geöffnet.
. Zeige mit der Maus auf das Tab der Variante.
. Klicke auf die rechte Maustaste. +
→ Eine Dropdown-Liste wird angezeigt. +
**__Tipp:__** Wenn die Dropdown-Liste nicht angezeigt wird, Wechsele in das Tab der Hauptvariante.
. Klicke auf *Umbenennen*. +
→ Das Fenster *Tab-Titel wählen* wird angezeigt.
. Wähle, ob im Tab-Titel von Varianten die *Varianten-ID*, der *Variantenname* oder die *Variantennummer* angezeigt werden soll.
. Klicke auf **Umbenennen**. +
→ Die gewählten Variantendaten werden in allen Tabs angezeigt. +
→ Wenn *Variantenname* oder *Variantennummer* eingestellt wird und diese Daten für eine Variante nicht gespeichert sind, wird stattdessen die *Varianten-ID* angezeigt. +
**__Tipp:__** Die Anzeige im Tab der aktuell geöffneten Variante ändert sich erst, nachdem der Artikel neu geladen wird.
