= Artikel und Varianten manuell anlegen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ##Artikel##, Variante, Produkt, Produkte, Standard-Artikel, Artikel des Typs Standard, Artikel vom Typ Standard, Artikel erstellen, Artikeldaten erstellen, Artikel anlegen, Artikeldaten anlegen, Variante erstellen, Variantendaten erstellen, Variante anlegen, Variantendaten anlegen, Artikelanlage, Artikelverwaltung, Artikel verwalten, Artikel bearbeiten, Artikel manuell anlegen, Artikel manuell erstellen, Artikeldaten, Artikeldatensatz, Artikeldatensätze, Neuer Artikel, Neue Artikel, Assistant, Assistent, Assistenten, ElasticSync, Import, Importieren, Datenaustausch, Daten-Export, Datenexport, Daten-Import, Datenimport, Artikelimport, Artikel importieren, Varianten importieren, Artikeldaten importieren, Variantendaten importieren, CSV, Artikel exportieren, Artikelexport, Artikeldaten exportieren, FormatDesigner, Format-Typen, Daten
:description: ##Erfahre##, wie du deine Artikeldaten in plentymarkets importierst, exportierst und manuell verwaltest.
:position: 10
:url: artikel/import-export-anlage/anlage/neue-artikel
:id: MNYRNTL
:author: team-item

Diese Seite setzt voraus, dass du bereits Grundkenntnisse über die Artikelstruktur in plentymarkets hast.
Zum Beispiel solltest du <<artikel/einleitung/struktur#, den Unterschied zwischen Artikeln und Varianten>> kennen. Du solltest auch wissen, dass Artikeldaten <<artikel/einleitung/vererbung#, vererbt>> werden können.

Zudem müssen folgende Daten im System vorhanden sein, um wie hier beschrieben Artikel und Varianten manuell zu erstellen:

* <<artikel/einstellungen/attribute#, Attribute>>
* <<artikel/einstellungen/attribute#, Attributwerte>>
* <<artikel/einstellungen/kategorien#, Kategorien>>
* <<artikel/einstellungen/preise#, Verkaufspreise>>


[#20]
== Einen neuen Artikel erstellen

//Mit dem Erstellen von Kategorien ist die Voraussetzung geschaffen, um deine Produkte zu sortieren.
Beim Erstellen eines neuen Artikels wird auch automatisch die erste Variante erstellt.
Diese Variante ist die <<artikel/einleitung/struktur#600, Hauptvariante>> und sie ist fest mit dem Artikel verbunden. Die Hauptvariante kann nur zusammen mit dem Artikel erstellt oder gelöscht werden.
//Erstelle nun neue Standardartikel.

Dieses Video zeigt spielerisch, wie Artikel manuell erstellt werden:

.Einen neuen Artikel erstellen
video::263297236#t=1m03s[vimeo]

[.instruction]
Einen neuen Artikel erstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Klicke auf icon:plus[role="green"] *Neu*. +
→ Das Tab *Neuer Artikel* wird geöffnet. Dieses Tab ist in mehrere Bereiche unterteilt.
. Nimm die Einstellungen wie in <<table-create-new-item>> beschrieben vor. Die folgenden Einstellungen sind dabei Pflicht:
.. Gib einen Namen ein.
.. Gib den Inhalt ein.
.. Wähle eine Kategorie.
. *Speichere* (icon:save[role="green"]) die Einstellungen. +
→ Der Artikel wird zusammen mit der Hauptvariante erstellt und in einem neuen Tab geöffnet.

[[table-create-new-item]]
.Artikel mit Hauptvariante erstellen
[cols="1,2"]
|====
|Einstellung |Erläuterung

2+| Bereich: *Artikeldaten*

| *Typ*
|Artikeltyp *Standard* wählen. +
*Standard* = Erstellt einen Artikel mit Hauptvariante. +
*Multipack* = Erstellt einen <<artikel/anwendungsfaelle/multipacks-pakete-sets#1000, Multipack-Artikel>>. +
*Set* = Erstellt einen <<artikel/anwendungsfaelle/multipacks-pakete-sets#3000, Setartikel>>. Setartikel können aktuell noch nicht im Webshop dargestellt werden. Daher wird das Erstellen von Setartikeln nicht empfohlen.

| **ID**
|Die Artikel-ID ist eine eindeutige, fortlaufende Zahl, die plentymarkets zur exklusiven Zuordnung jedes Artikels benötigt. Wird dieses Feld freigelassen, vergibt plentymarkets automatisch die nächste freie ID.

| **Hersteller**
|Hersteller wählen. Wie du Hersteller erstellst und verknüpfst, erfährst du unter <<artikel/einstellungen/hersteller#, Hersteller verwalten>>.

| **Name** +
[red]#(Pflichtfeld)#
|Artikelname eingeben. Der Artikelname ist eine Pflichteingabe. Wie du den Artikelnamen änderst, erfährst du im Kapitel <<artikel/artikel-verwalten#50, Artikeltexte eingeben>>.

| **Markierung**
|Markierung wählen. Artikel können mit Hilfe von Markierungen gefiltert werden. Wie du Markierungen bearbeitest und verknüpfst, erfährst du unter <<artikel/einstellungen/markierungen#, Markierungen einrichten>> und <<artikel/artikel-verwalten#810, Artikel mit Markierungen versehen>>.

| **Warentyp**
| **Lagerware** (Standardeinstellung), **Produktionsware**, **Colli** oder **Bestellware** wählen. +
**Colli** = Wählen, wenn der Artikel in mehreren Packstücken versendet wird. Weitere Packstücke müssen als eigene Artikel mit dem Warentyp Colli in plentymarkets erstellt werden, sollten aber nicht für den Webshop aktiviert werden.

2+| Bereich *Variante » Grundeinstellungen*

| **Variantenname**
|Variantenname für die Hauptvariante eingeben.

| **Variantennr.**
|Die Variantennummer wird automatisch nach dem im Menü **Einrichtung » Artikel » Einstellungen** festgelegten Muster vergeben. Variantennummern sind nachträglich im Tab **Einstellungen** einer Variante änderbar.

| **Ext. Varianten-ID**
|Externe Varianten-ID eingeben, die für die Hauptvariante des Artikels verwendet wird. Die externe Varianten-ID ist eine optionale Eingabe, die die Übernahme von Artikeln und Varianten aus einem externen System erleichtert. Externe Varianten-IDs sind nachträglich im Tab **Einstellungen** einer Variante änderbar.

| *Modell*
|

| **Inhalt** +
[red]#(Pflichtfeld)#
|Standardmäßig sind die Menge *1* und die <<artikel/einstellungen/einheiten#, Einheit>> *Stück* eingestellt. Einstellungen bei Bedarf anpassen. Der Inhalt ist eine Pflichteingabe.

2+| Bereich *Variante » Kategorieverknüpfung*

2+| Bereich *Variante » Attribute*

| **Attribute**
|Attribute für die Hauptvariante wählen. Werden Attribute für die Hauptvariante gewählt, sind die gewählten Attribute für alle Varianten des Artikels verfügbar. Wenn ein Artikel des Typs **Standard** erstellt wird, ohne Attribute für die Hauptvariante zu wählen, können beim <<artikel/artikel-verwalten#160, Erstellen von Varianten>> alle im System verfügbaren Attribute gewählt werden. Sobald eine Variante mit Attributen erstellt wurde, können weitere Varianten nur noch mit diesen Attributen oder ohne Attribute erstellt werden.

2+| Bereich *Variante » Verkaufspreise*

| **Verkaufspreise**
|<<artikel/einstellungen/preise#, Verkaufspreise>> verknüpfen und Werte für verknüpfte Preise eingeben.
|====

////
*_Hinweis:_* Neue Artikel und Änderungen an Artikeldaten sind nicht sofort im Webshop und den Exporten verfügbar. +
*_Tipp:_* Zeige eine Vorschau des Artikels an:
  .. Klicke in der Speicherzeile des Artikels auf das Augensymbol. +
  → Das Fenster *Mandant (Shop)* wird angezeigt. +
  .. Wähle in der Dropdown-Liste das *Plugin Set*, in dem du die Vorschau anzeigen möchtest.
  .. Wähle in der Dropdown-Liste den *Mandant (Shop)*, in dem du die Vorschau anzeigen möchtest. +
  *_Tipp:_* Die Einstellungen bleiben erhalten, wenn du die Vorschau das nächste Mal öffnest.
  .. Klicke auf *Ausführen*. +
  → Eine Vorschau des Artikels wird angezeigt.

Statt im Menü *Artikel » Artikel bearbeiten* erstellst du einen neuen Artikel des Typs *Standard*, indem du im Menü *Artikel » Kategorien* auf den Pfeil neben einer <<artikel/einstellungen/kategorien#, Kategorie>> klickst. Klicke dann im eingeblendeten Kontextmenü auf *Neuen Artikel erstellen*.

[TIP]
.Artikel des Typs **Standard** in Übersicht anzeigen
====
Der neue Artikel des Typs **Standard** ist noch inaktiv. Um neue Artikel nach dem Erstellen in der Übersicht im Menü **Artikel » Artikel bearbeiten** anzuzeigen, wähle auf der linken Seite für den Filter **Aktiv** die Option **ALLE** und klicke auf **Suchen**. Wie du deine Artikel und Varianten für den Webshop aktivierst, erfährst du im Kapitel <<artikel/artikel-verwalten#180, Verfügbarkeit einstellen>>.
====
////

== Zusätzliche Informationen speichern


[#160]
== Weitere Varianten erstellen

Beim Erstellen eines Artikels des Typs **Standard** wird immer eine Hauptvariante erstellt. Die Hauptvariante ist fest mit dem Artikel des Typs **Standard** verbunden und sie kann nicht gelöscht werden. Informationen der Hauptvariante wie Verkaufspreise und Verfügbarkeit werden von Artikelvarianten geerbt. Du kannst jede Variante aber auch individuell anpassen. Erfahre zunächst, wie du Varianten erstellst.

[.instruction]
Varianten erstellen:

. Öffne das Menü **Artikel » Artikel bearbeiten**.
. Öffne den Artikel des Typs **Standard**.
. Wechsele in das Tab **Varianten**.
. Klicke auf **Neu**. +
→ Das Fenster **Neue Variante erstellen** wird geöffnet.
. Gib den Inhalt ein.
. Wähle ein oder mehrere Attribute. +
→ Unter **Kombinationen** wird angezeigt, wie viele unterschiedliche Varianten erstellt werden.
. Klicke auf **Varianten erstellen**. +
→ Die Varianten werden erstellt und in der Variantenübersicht angezeigt. +
*_Hinweis:_* Neue Varianten und Änderungen an Variantendaten sind nicht sofort im Webshop und den Exporten verfügbar. +
*_Tipp:_* Zeige eine Vorschau der Variante an:
 .. Klicke in der Speicherzeile der Variante auf das Augensymbol. +
 → Das Fenster *Mandant (Shop)* wird angezeigt. +
 .. Wähle in der Dropdown-Liste das *Plugin Set*, in dem du die Vorschau anzeigen möchtest.
 .. Wähle in der Dropdown-Liste den *Mandant (Shop)*, in dem du die Vorschau anzeigen möchtest. +
 *_Tipp:_* Die Einstellungen bleiben erhalten, wenn du die Vorschau das nächste Mal öffnest.
 .. Klicke auf *Ausführen*. +
 → Eine Vorschau der Variante wird angezeigt.

[TIP]
.Attribute für Varianten wählen
====
Wenn du für die Hauptvariante Attribute wählst, sind diese gewählten Attribute für alle Varianten des Artikels verfügbar. Wenn du einen Artikel erstellst, ohne Attribute für die Hauptvariante zu wählen, können beim Erstellen von Varianten alle im System verfügbaren Attribute gewählt werden. Sobald eine Variante mit Attributen erstellt wurde, können weitere Varianten nur noch mit diesen Attributen oder ohne Attribute erstellt werden.

Lösche alle Varianten eines Artikels, dessen Hauptvariante keine Attribute besitzt, dann stehen dir beim Erstellen neuer Varianten wieder alle im System verfügbaren Attribute zur Auswahl. Somit musst du lediglich die Varianten und nicht den Artikel löschen, wenn du ein für den Artikel relevantes Attribut nachträglich hinzufügst. Die mit dem Artikel verknüpften Attribute können nach dem Erstellen von Varianten nicht mehr gelöscht oder hinzugefügt werden. Um Attribute zu löschen oder hinzuzufügen, müssen zunächst alle Varianten mit Attributen gelöscht werden.
====
