= jQuery
:lang: en
// include::{includedir}/_header.adoc[]
:keywords: jQuery, Syntax, Web design, CMS
:position: 100

*CMS » Web design*

== Content of this page

This page provides information about *jQuery*.

== Important information about jQuery

link:http://jquery.com/[jQuery^] is a fast and concise JavaScript Library that simplifies HTML document traversing, event handling, animating, and Ajax interactions for rapid web development. It is automatically available in your online store and can be used anywhere in your layout. We also offer you the additional libraries, link:http://jqueryui.com/[jQuery UI^] and link:http://jquerytools.github.io/[jQuery Tools^].

[WARNING]
.Check before implementing jQuery!
====
*Compatibility*

If you intend to work with other JavaScript libraries, such as *Prototype*, be sure to find out about the compatibility of both libraries beforehand and take any potential conflicts into consideration.

*Libraries*

The libraries mentioned should not be included into your layout a second time. This could have unforeseen consequences for the library's function.
====

[TIP]
.Tutorial
====
You can find a jQuery tutorial at the link link:http://learn.jquery.com/about-jquery/how-jquery-works/[http://learn.jquery.com/about-jquery/how-jquery-works/^].
====
