= Inventur durchführen
:lang: de
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: plentyWarehouse Artikeletiketten, plentyWarehouse Artikel Etiketten
:position: 60
:id: A5QKZMB
:url: warenwirtschaft/plentywarehouse/artikeletiketten-drucken

include::_textblocks/hinweis-voraussetzungen.adoc[]
include::_textblocks/hinweis-offene-beta.adoc[]

Für bestimmte Aufgaben im Lager, sollten deine Artikel und Varianten mit Etiketten ausgestattet sein. Diese Etiketten enthalten einen Barcode, in dem alle wichtigen Daten gespeichert sind. Über den Handscanner kann das Lagerpersonal schnell und fehlerfrei den jeweiligen Artikel identifizieren und je nach Bedarf eine <<warenwirtschaft/plentywarehouse/inventur-durchfuehren#, Inventur>> oder <<warenwirtschaft/plentywarehouse/artikel-umbuchen#, Umbuchung>> vornehmen oder den Artikel <<warenwirtschaft/plentywarehouse/artikel-verraeumen#, Verräumen>>.

plentyWarehouse macht es dir einfach, alle deine Artikel im Lager mit Etiketten zu versehen, denn du kannst Artikeletiketten ganz bequem aus der App heraus drucken.

Auf dieser Handbuchseite findest du alle Informationen zu notwendigen Einstellungen im Vorfeld sowie zum Druck von Artikeletiketten über plentyWarehouse.

[IMPORTANT]
.Voraussetzung: plentyBase
====
Um die Funktion *Artikeletiketten* in der plentyWarehouse App nutzen zu können, muss auf deinem Arbeitsrechner plentyBase installiert sein. plentyBase ist erforderlich, um die Kommunikation zwischen plentyWarehouse und deinem Etikettendrucker herzustellen. Auf der Handbuchseite <<automatisierung/prozesse/plentybase-installieren#, plentyBase installieren>> findest du alle weiteren Informationen sowie eine allgemeine Installationsanleitung für das Tool.
====

[#100]
== plentyWarehouse mit plentyBase verbinden

//TODO

[.instruction]
plentyWarehouse mit plentyBase verbinden:

//TODO

[#200]
== Einstellungen für Artikeletiketten vornehmen

//TODO

[.instruction]
Einstellungen für Artikeletiketten vornehmen:

//TODO

[#300]
== Artikeletiketten drucken
