= Artikel verräumen
:lang: de
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: plentyWarehouse Umbuchung, plentyWarehouse umbuchen, plentyWarehouse verräumen
:position: 40
:id: A5QIHYV
:url: warenwirtschaft/plentywarehouse/umbuchen-und-verraeumen

include::_textblocks/hinweis-voraussetzungen.adoc[]
include::_textblocks/hinweis-offene-beta.adoc[]

Die plentyWarehouse App beinhaltet die Funktion Verräumen. Einzelheiten dazu findest du auf dieser Handbuchseite. Zunächst folgt eine kurze Beschreibung der Funktion zum besseren Verständnis. Danach werden die <<app/funktionen/lagerverwaltung/verräumen#200, Einstellungen>> beschrieben, die einmalig im Voraus vorgenommen werden müssen. Diese Einstellungen greifen dann später, wenn du Artikel verräumst.

[#100]
== Wie werden Artikel verräumt?

Klappe die Box unten auf, um mehr über den Ablauf des Verräumens zu erfahren.

[.collapseBox]
.Ablauf beim Verräumen von Artikeln
--
Anfangs befinden sich alle Artikel am gleichen Platz. Beispielsweise können Kassenkräfte retournierte Artikel in eine Kiste hinter der Theke ablegen. Oder vielleicht werden Artikel aus Wareneingängen immer auf denselben Platz im Lager gestellt, um später auf die permanenten Lagerorte geräumt zu werden.

Sobald das Lagerpersonal bereit ist, die Artikel ins Regal zu räumen, wird die--- plentyWarehouse App geöffnet. Zuerst wird angegeben, wo die Artikel sich befinden, also aus welchem Lagerort heraus die Artikel verräumt werden sollen.

Daraufhin wird eine Übersicht aller Artikel angezeigt, die sich an diesem Lagerort befinden. Mitarbeiter:innen wählen den ersten Artikel aus und wählen in der App aus, an welchem neuen Lagerort der Artikel platziert werden soll.

plentyWarehouse wechselt automatisch zurück zur Übersicht aller noch ausstehenden Artikel. Das Lagerpersonal durchläuft den Prozess so lange, bis alle Artikel verräumt wurden oder das Verräumen manuell abgebrochen wird.
--

[#200]
== Einstellungen zum Verräumen vornehmen

Die Funktion zum Verräumen in plentyWarehouse lässt sich mithilfe einiger grundlegenden Einstellungen auf deine Bedürfnisse und Arbeitsabläufe anpassen.

So kannst du beispielsweise ... //TODO: Beispiel

[.instruction]
Einstellungen zum Verräumen vornehmen:

. <<warenwirtschaft/plentywarehouse/installation-und-ersteinrichtung#300, Logge dich in plentyWarehouse ein>>.
. Tippe auf das Menüsymbol (icon:bars[role="darkGrey"]) oben links.
. Tippe unten auf *Einstellungen* (icon:settings[role="darkGrey"]). +
→ Das Einstellungsmenü öffnet sich.
. Tippe auf *Verräumen* (icon:call_split[role="darkGrey"]). //TODO: Rotate
. Nimm die Einstellungen für das Verräumen vor. Beachte dazu die Erläuterungen in <<table-pw-redi-settings>>.

[[table-settings-reshelving]]
.Einstellungen zum Verräumen in plentyWarehouse
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Fokus auf Suchfeld*
|Wirst du typischerweise den <<app/funktionen/lagerverwaltung/verräumen#400, Quelllagerort angeben>>, indem du seinen Barcode scannst oder indem du den Lagerort aus einer Liste wählst? Falls du den Barcode scannen möchtest, kann diese Einstellung deine Arbeit beschleunigen. +
*Aktiviert* (icon:toggle-on[role="green"]) = Dein Mauszeiger beginnt automatisch in dem Barcodefeld, wenn du Artikel verräumst. Du kannst den Quelllagerort direkt scannen. +
*Deaktiviert* (icon:toggle-off[role="darkGrey"]) = Dein Mauszeiger beginnt nicht im Barcodefeld. Natürlich wird es weiterhin möglich sein, den Mauszeiger manuell in dem Feld zu platzieren.

| *Von Lagerort umzubuchende Menge*
|Wirst du typischerweise die gesamte Artikelmenge <<app/funktionen/lagerverwaltung/verräumen#600, verräumen>>? Falls ja, kann diese Einstellung deine Arbeit beschleunigen. +
*Aktiviert* (icon:toggle-on[role="green"]) = Die App schlägt dir automatisch vor, die gesamte an diesem Lagerort gefundene Menge zu verräumen. Natürlich kannst du bei Bedarf auch manuell eine andere Menge eingeben. +
*Deaktiviert* (icon:toggle-off[role="darkGrey"]) = Die Menge 1 wird vorgeschlagen. Die Menge muss manuell eingegeben werden.

| *Quelllagerortvorschlagsliste nach Zweck*
|Wo befinden sich deine Artikel, bevor sie verräumt werden? Wähle das passende <<warenwirtschaft/lager-einrichten#200, Lager>> aus der Dropdown-Liste. Verwende die Umschaltflächen, um <<warenwirtschaft/lager-einrichten#500, Lagerort-Zwecke>> ein- oder auszuschließen. +
*_Beispiel:_* Wähle die Lagerort-Zwecke *Wareneingang* und *Retoure*, wenn du sowohl Lieferungen neuen als auch von retournierten Artikeln schnell verräumen möchtest. +
*_Nutzung:_* Wenn du später Artikel verräumst, werden dir nur die Lagerorte als Quelllagerort vorgeschlagen, die diese Kriterien erfüllen. Willst du einen Lagerort verwenden, der _nicht vorgeschlagen_ wird, musst du den Lagerort scannen anstatt ihn aus der Vorschlagsliste in der App zu wählen.

| *Ziellagerortvorschlagsliste*
|Wohin möchtest du deine Artikel verräumen? Verwende die Umschaltflächen, um bestimmte Sorten von Lagerorten ein- oder auszuschließen. +
*Lagerortvorschlag* = Lagerorte, die <<warenwirtschaft/wareneingaenge-verwalten#200, mit einer Variante verknüpft>> sind. +
*Verwendete Lagerorte* = Lagerorte, in denen eine Variante bereits gelagert ist. +
*Leere Lagerorte* = Alle vorhandenen Lagerorte. +
*_Hinweis:_* Je nach Anzahl der Lagerorte kann die Einstellung *Leere Lagerorte* das Verräumen stark verlangsamen. Verknüpfe daher Varianten mit Lagerorten und aktiviere leere Lagerorte nur im Ausnahmefall. +
*_Nutzung:_* Wenn du später Artikel verräumst, werden dir nur die Lagerorte als Ziellagerort vorgeschlagen, die diese Kriterien erfüllen. Willst du einen Lagerort verwenden, der _nicht vorgeschlagen_ wird, musst du den Lagerort scannen anstatt ihn aus der Vorschlagsliste in der App zu wählen.

| *Ziellagerorte nach Zweck ausschliessen*
|Aktiviere diese Option, um zu verhindern, dass Lagerorte vom Zweck *Box* auf deiner Vorschlagsliste erscheinen. Dies kann sinnvoll sein, wenn du die App auch für <<app/funktionen/lagerverwaltung/rollende-kommissionierung#, rollende Kommissionierung>> verwendest, und du willst nicht, dass deine Boxen beim Verräumen in die Quere kommen.

| *Vorlage*
|Wie soll deine <<app/funktionen/lagerverwaltung/verräumen#500, Artikelliste>> aussehen? Die plentymarkets App verfügt bereits über eine Standard-Vorlage, die für die meisten Verräumungsprozesse geeignet ist. Du kannst allerdings auch weitere Vorlagen im Menü *Einrichtung » plenty App » Umbuchung* erstellen und dann hier aus dieser Dropdown-Liste auswählen. +
*_Tipp:_* Mit Vorlagen kannst du z.B. bestimmen, in welcher Reihenfolge und in welcher Schriftgröße einzelne Informationen später auf der Artikelliste dargestellt werden.
|====

[#300]
== Artikel verräumen

Gehe nun wie unten beschrieben vor, um Artikel mit plentyWarehouse zu verräumen.

[IMPORTANT]
.Stehen Artikel bereit?
====
Artikel können nur mit plentyWarehouse verräumt, wenn sie sich am richtigen Lagerort befinden. Sind zur Zeit keine Artikel am ausgewählten Lagerort vorhanden, werden auch keine Artikel zum Verräumen angezeigt.
====

////
[#400]
=== Quelllagerort angeben

Wo befinden sich aktuell die Artikel, die ins Regal müssen? Lege zuerst fest, welchen Lagerort du verräumen möchtest.

[.instruction]
Quelllagerort angeben:

. <<app/installation#1200, Melde dich bei der plentymarkets App an>>.
. Tippe oben links auf das *Menüsymbol* (icon:bars[role="blue"]).
. Tippe auf *Lagerverwaltung » Verräumen*. +
→ Eine Auflistung aller <<app/funktionen/lagerverwaltung/verräumen#200, vorgeschlagenen Lagerorte>> wird angezeigt.
. Scanne den Barcode des Lagerorts oder tippe in der App auf den Lagerort. +
→ Eine Auflistung aller hier gelagerten Artikel wird angezeigt.

[#500]
=== Artikel aussuchen

plentymarkets erstellt automatisch eine Auflistung aller Artikel, die sich aktuell an diesem Lagerort befinden. Dabei werden gleiche Artikel gruppiert. Müssen beispielsweise zwei Exemplare eines Artikels zurück ins Regal, können Mitarbeiter:innen die Artikelmenge direkt beim Verräumen angeben.

Die Liste enthält wichtige Informationen zu den Artikeln, die verräumt werden sollen. Mitarbeiter:innen sehen zum Beispiel die Artikel-ID und wie der Artikel heißt. Du kannst im Voraus selbst bestimmen, welche Informationen in der Liste angezeigt werden sollen. Richte dazu eine <<app/funktionen/lagerverwaltung/verräumen#200, Vorlage>> ein.

[.instruction]
Mit der Artikelliste arbeiten:

. Schaue auf die Liste, um herauszufinden, welche Artikel verräumt werden müssen.
. Entscheide, welchen Artikel du als erstes verräumen möchtest.
. Scanne den Barcode des Artikels oder tippe in der App auf den Artikel.

[#600]
=== Artikel verräumen

Wohin willst du diesen Artikel verräumen? Die App zeigt dir eine Auflistung aller <<app/funktionen/lagerverwaltung/verräumen#200, vorgeschlagenen Ziellagerorte>>. Scanne ganz einfach den Barcode eines Lagerorts oder tippe auf einen Lagerort in der App.

[.instruction]
Artikel verräumen:

. Stelle den Artikel am passenden Ort ins Regal.
. Scanne den Barcode dieses Lagerorts oder tippe in der App auf diesen Lagerort. +
→ Im Hintergrund ändert plentymarkets den Lagerort des Artikels. Im plentymarkets System ist eine <<warenwirtschaft/warenbestaende-verwalten#1100, Warenbewegung>> zu sehen. +
→ Müssen noch weitere Artikel vom Quelllagerort verräumt werden, wechselt der Bildschirm zurück zur <<app/funktionen/lagerverwaltung/verräumen#500, Artikelliste>> und du kannst mit dem nächsten Artikel fortfahren.

[TIP]
.Mehrere Exemplare eines Artikels
====
Gleiche Artikel werden in der App gruppiert. Müssen beispielsweise zwei Exemplare eines Artikels zurück ins Regal, kannst du die Artikelmenge direkt beim Verräumen angeben. Scanne dazu den Artikel mehrmals. Beim Scannen erhöht sich die Anzahl automatisch um eins. +
*_Hinweis_*: Tippe alternativ auf *Menge* und gib die Anzahl mit dem Tastenfeld ein.

Wenn du typischerweise die gesamte Menge verräumst, dann kannst du Zeit sparen, indem du die Option *Von Lagerort umzubuchende Menge* in den <<app/funktionen/lagerverwaltung/verräumen#200, App-Einstellungen>> aktivierst.
====


////