= Artikel suchen und Lagerorte inspizieren
:lang: de
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: plentyWarehouse Artikelsuche, Lagerorte inspizieren, Lagerorte untersuchen, Bestand einsehen
:position: 20
:id: Z9QIMNV
:url: warenwirtschaft/plentywarehouse/artikel-und-lagerorte

include::_textblocks/hinweis-voraussetzungen.adoc[]
include::_textblocks/hinweis-offene-beta.adoc[]

plentyWarehouse macht es dir leicht, jederzeit den Überblick über die Artikel, Bestände und Lagerorte deines plentymarkets Systems zu behalten.
Dazu stehen die Funktionen *Artikelsuche* und *Lagerort inspizieren* zur Verfügung. Auf dieser Handbuchseite erhältst du Informationen zum Umfang und zur Bedienung beider Funktionen.

[#100]
== Die Artikelsuche

Du möchtest unterwegs oder direkt im Lager Artikel suchen, Bestände anzeigen oder genauere Informationen zu Artikeln und Varianten einsehen? Dann nutze die Artikelsuche. <<#200, Nimm zunächst einige Einstellungen>> vor und bestimme so, wie die Suchergebnisse aussehen sollen. Diese Einstellungen greifen dann später, wenn du <<300, in plentyWarehouse nach Artikeln suchst>>.

[#200]
=== Einstellungen zur Artikelsuche vornehmen

Die Artikelsuche in plentyWarehouse lässt sich mithilfe einiger grundlegenden Einstellungen auf deine Bedürfnisse und Arbeitsabläufe anpassen.

So kannst du beispielsweise bestimmen, wie viele Suchergebnisse auf einmal angezeigt werden sollen oder welche Suchfelder in welcher Reihenfolge zur Verfügung stehen sollen.

[.instruction]
Einstellungen zur Artikelsuche vornehmen:

. <<awarenwirtschaft/plentywarehouse/installation-und-ersteinrichtung#300, Logge dich in plentyWarehouse ein>>.
. Tippe auf das Menüsymbol (icon:bars[role="darkGrey"]) oben links.
. Tippe unten auf *Einstellungen*. +
→ Das Einstellungsmenü öffnet sich.
. Tippe auf *Artikelsuche*.
. Nimm die Einstellungen für die Artikelsuche vor. Beachte dazu die Erläuterungen in <<table-pw-item-search-settings>>.

[[table-pw-item-search-settings]]
.Einstellungen zur Artikelsuche in plentyWarehouse
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Anzahl zu ladender Artikel*
|Wähle aus, wie viele Suchergebnisse du auf einmal sehen möchtest.

| *Artikelsuchfelder*
|Verwende die Umschaltflächen, um festzulegen, welche Parameter zur Suche nach Artikeln genutzt werden sollen. +
*Aktiviert* (icon:toggle-on[role="green"]) = Es wird möglich sein, Artikel anhand dieses Parameters zu suchen. +
*_Tipp:_* Tippe und halte (icon:drag_handle[role="darkGrey"]) für jeden aktivierten Parameter, um die Reihenfolge der angezeigten Suchfelder anzupassen.

| *Fokus auf Artikelsuchfeld*
|Suchst du typischerweise anhand eines bestimmten Parameters? Tippe auf deinen am häufigsten verwendeten Parameter. Später wenn du nach Artikeln suchst, wird dein Mauszeiger automatisch in diesem Feld beginnen. Natürlich ist es weiterhin möglich, den Mauszeiger manuell in einem anderen Suchfeld zu platzieren.
|====

[#300]
=== Artikel suchen

Über die Artikelsuche kannst du auf alle Artikel zugreifen, die in deinem plentymarkets System geplegt sind.

[.instruction]
Artikel suchen:

. <<warenwirtschaft/plentywarehouse/installation-und-ersteinrichtung#300, Logge dich in plentyWarehouse ein>>.
. Tippe auf das Menüsymbol (icon:bars[role="darkGrey"]) oben links. +
(icon:map-signs[]) *_Oder:_*: Finde die Artikelsuche im Bereich *Funktionen* auf dem Dashboard.
. Tippe auf *Artikelsuche* (icon:search[role="darkGrey"]). +
→ Die Artikelsuche wird geöffnet.
. Gib ein Suchkriterium ein, z.B. eine Varianten-ID.
. Tippe auf *Suchen* (icon:search[role="darkGrey"]). +
→ Die gefundenen Artikel werden aufgelistet.
. Tippe auf den gewünschten Artikel. +
→ Die Detailansicht wird angezeigt. 

Die Detailansicht besteht aus den Bereichen *Artikelinformation* und *Bestand*. Diese Bereiche enthalten, soweit sie im plentymarkets System gepflegt sind, jeweils die folgenden Daten.

[.tabs]
====
Artikelinformation::
+
--
* Varianten-ID und Variantennummer
* Artikel-ID
* Externe Varianten-ID
* <<artikel/einstellungen/attribute#, Attribute>>
* <<artikel/artikel-verwalten#180, Modell>>
* <<artikel/einstellungen/markierungen#400, Tags>>
* <<artikel/einstellungen/eigenschaften#500, Eigenschaften>>
--
 
Bestand::
+
--
* Name des Lagerorts, auf dem sich die gefundene Variante aktuell befindet
* Lager, in dem sich die gefundene Variante aktuell befindet
* Menge (<<warenwirtschaft/warenbestaende-verwalten#100, physischer Warenbestand>>), in der die Variante aktuell vorrätig ist
--
====