= Artikel suchen und Lagerorte inspizieren
:lang: de
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: plentyWarehouse Artikelsuche, Lagerorte inspizieren, Lagerorte untersuchen, Bestand einsehen
:position: 20
:id: Z9QIMNV
:url: warenwirtschaft/plentywarehouse/artikel-und-lagerorte

include::_textblocks/hinweis-voraussetzungen.adoc[]
include::_textblocks/hinweis-offene-beta.adoc[]

plentyWarehouse macht es dir leicht, jederzeit den Überblick über die Artikel, Bestände und Lagerorte deines plentymarkets Systems zu behalten.
Dazu stehen die Funktionen *Artikelsuche* und *Lagerort inspizieren* zur Verfügung. Auf dieser Handbuchseite erhältst du Informationen zum Umfang und zur Bedienung beider Funktionen.

[#100]
== Artikelsuche

Du möchtest unterwegs oder direkt im Lager Artikel suchen, Bestände anzeigen oder genauere Informationen zu Artikeln und Varianten einsehen? Dann nutze die Artikelsuche. <<#200, Nimm zunächst einige Einstellungen>> vor und bestimme so, wie die Suchergebnisse aussehen sollen. Diese Einstellungen greifen dann später, wenn du <<300, in plentyWarehouse nach Artikeln suchst>>.

[#300]
=== Einstellungen zur Artikelsuche vornehmen

Die Artikelsuche in plentyWarehouse lässt sich mithilfe einiger grundlegenden Einstellungen auf deine Bedürfnisse und Arbeitsabläufe anpassen.

So kannst du beispielsweise bestimmen, wie viele Suchergebnisse auf einmal angezeigt werden sollen oder welche Suchfelder in welcher Reihenfolge zur Verfügung stehen sollen.

[.instruction]
Einstellungen zur Artikelsuche vornehmen:

