= Etiketten drucken
:lang: de
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: plentyWarehouse Artikeletiketten, plentyWarehouse Artikel Etiketten, plentyWarehouse Lagerorte labeln, Lagerort Etiketten
:position: 60
:id: A5QKZMB
:url: warenwirtschaft/plentywarehouse/etiketten-drucken

include::_textblocks/hinweis-voraussetzungen.adoc[]
include::_textblocks/hinweis-offene-beta.adoc[]

Für bestimmte Aufgaben im Lager, sollten deine Artikel und Lagerorte mit Etiketten ausgestattet sein. Diese Etiketten enthalten einen Barcode, in dem alle wichtigen Daten gespeichert sind. Über den Handscanner kann das Lagerpersonal schnell und fehlerfrei den jeweiligen Artikel oder Lagerort identifizieren und je nach Bedarf eine <<warenwirtschaft/plentywarehouse/inventur-durchfuehren#, Inventur>> oder <<warenwirtschaft/plentywarehouse/artikel-umbuchen#, Umbuchung>> vornehmen oder den Artikel <<warenwirtschaft/plentywarehouse/artikel-verraeumen#, Verräumen>>.

plentyWarehouse macht es dir einfach, alle deine Artikel und Lagerorte im Lager mit Etiketten zu versehen. Du kannst Artikeletiketten jederzeit ganz bequem aus der App heraus drucken.

Auf dieser Handbuchseite findest du alle Informationen zu notwendigen Einstellungen im Vorfeld sowie zum Druck von Etiketten über plentyWarehouse.

[IMPORTANT]
.Voraussetzung: plentyBase
====
Um Etiketten über plentyWarehouse zu drucken, muss auf deinem Arbeitsrechner plentyBase installiert sein. plentyBase ist erforderlich, um die Kommunikation zwischen plentyWarehouse und deinem Etikettendrucker herzustellen. Auf der Handbuchseite <<automatisierung/prozesse/plentybase-installieren#, plentyBase installieren>> findest du alle weiteren Informationen sowie eine allgemeine Installationsanleitung für das Tool.
====

[#100]
== plentyWarehouse mit plentyBase verbinden

Zuerst muss sichergestellt sein, dass plentyWarehouse mit dem Drucker kommunizieren kann, den du für den Druck der Etiketten verwenden möchtest. Dazu ist es notwendig, plentyWarehouse einmalig mit dem Tool plentyBase zu verbinden.

[.instruction]
plentyWarehouse mit plentyBase verbinden:

. <<warenwirtschaft/plentywarehouse/installation-und-ersteinrichtung#300, Logge dich in plentyWarehouse ein>>.
. 

[#200]
== Einstellungen für Etiketten vornehmen

//TODO

[.instruction]
Einstellungen für Etiketten vornehmen:

//TODO

[#300]
== Etiketten drucken

//TODO
