= Installation und Ersteinrichtung (Beta)
:lang: de
include::{includedir}/_header.adoc[]
:author: team-mobile
:keywords: plentyWarehouseApp, plentyWarehouse einrichten, plentyWarehouse Login, plentyWarehouse Systemvoraussetzungen, plentyWarehouse Einstellungen, Mobile Warenwirtschaft
:position: 10
:id: B6QIHYV
:icons: font
:docinfodir: /workspace/manual-adoc
:docinfo1:
:url: warenwirtschaft/plentywarehouse/installation-und-ersteinrichtung

//TODO: Icons, Funktionssymbole in Tabelle, Infobox, dass im Menü noch einige Einträge ausgegraut sind, da noch nicht alle Funktionen vorhanden

Bist du bereits von den Vorteilen <<warenwirtschaft/plentywarehouse#, plentyWarehouse App (beta)>> der überzeugt? Dann verliere keine Zeit und richte jetzt die plentyWarehouse App auf der passenden Hardware ein.

Auf dieser Seite erfährst du, wie du plentyWarehouse installierst, wie du dich beim ersten Login zurechtfindest und allgemeine Einstellungen vornimmst.

include::_textblocks/hinweis-offene-beta.adoc[]

[#100]
== Wahl der passenden Geräte

include::../../app/_textblocks/hardware-voraussetzungen/hardware-plentywarehouse.adoc[]

[#200]
== plentyWarehouse installieren

Hast du sichergestellt, dass deine Geräte den oben beschriebenen Systemvoraussetzungen entsprechen? Dann lade dir im nächsten Schritt die plentyWarehouse App herunter und installiere sie.

//// 
* TODO: PlayStore Link zur Open Beta hinzufügen
////

[#300]
== In plentyWarehouse einloggen

Die plentyWarehouse App funktioniert in Kombination mit link:https://www.plentymarkets.com/de/[einem gebuchten plentymarkets System^]{nbsp}icon:external-link[]. Nutzer:innen melden sich in plentyWarehouse ganz einfach mit ihren gewohnten Zugangsdaten zum plentymarkets System an.

[.instruction]
In plentyWarehouse einloggen:

. Öffne plentyWarehouse auf deinem Gerät.
. Gib deine Zugangsdaten ein. Beachte dazu die Erläuterungen in <<table-pw-login>>.
. Tippe auf *Login*. +
→ Du wirst in plentyWarehouse eingeloggt.

[[table-pw-login]]
.Eingabefehler für den Login
[cols="1,3"]
|====
|Einstellung |Erläuterung
| *Plenty-ID*
|Gib die ID des plentymarkets Systems ein, dessen Warenbestand du mit plentyWarehouse verwalten möchtest.

| *Benutzername*
|Gib den Benutzernamen deines Kontos ein.

| *Passwort*
|Gib das Passwort deines Kontos ein.
|====

[#300]
== Dein plentyWarehouse Dashboard

Nachdem du dich <<#300, in plentyWarehouse eingeloggt>> hast, wird dir automatisch das Dashboard angezeigt.   Hier findest du auf einen Blick die wichtigsten Informationen und Einstiegspunkte. <<table-pw-dashboard>> enthält einen Überblick über die dargestellten Bereiche.

[TIP]
.Bereiche individuell anordnen
====
Du kannst die Bereiche des Dashboards in beliebiger Reihenfolge untereinander anordnen. Tippe und drücke dazu auf (icon:drag_handle[role="darkGrey"]) oben rechts an jedem Bereich und ziehe den Bereich an die gewünschte Stelle. Diese Einstellung wird permanent gespeichert.
====

[[table-pw-dashboard]]
.Bereiche auf dem Dashboard
[cols="1,3"]
|====
|Bereich |Erläuterung

| *Allgemeine Informationen*
|Hier findest du den Namen des eingeloggten Benutzers, den Zeitpunkt der letzten Anmeldung sowie die plentyID und die Adresse des Systems, auf das du über plentyWarehouse zugreifst.

| *Funktionen*
|Dieser Bereich enthält Kacheln mit Symbolen für die einzelnen Funktionen von plentyWarehouse. Tippe auf eine Kachel, um schnell zur jeweiligen Funktion zu gelangen. Wenn du diesen Bereich einige Male genutzt hast, sortieren sich die Kacheln automatisch. So werden die Kacheln der meistgenutzten Funktionen immer links im Bereich angezeigt.

| *Letzte Aktivitäten*
|Um dir den Überblick zu erleichtern, wird hier angezeigt, welche Aktionen du seit dem letzten Login mit plentyWarehouse ausgeführt hast. So lässt sich beispielsweise auf einen Blick nachvollziehen, wie viele Artikel bei der letzten Artikelsuche gefunden wurden oder wie viele Artikel in der letzten durchgeführten Umbuchung erhalten waren.
|====

Über das Dashboard gelangst du zu den weiteren Einstellungen und greifst auf die komplette Liste der Funktionen von plentyWarehouse zu. Tippe dazu einfach auf das Menüsymbol (icon:bars[role="darkGrey"]) oben links.

[#400]
== Allgemeine Einstellungen vornehmen

Bevor du zum ersten Mal mit plentyWarehouse in deinem Lager arbeitest, empfehlen wir dir, einige grundlegende Einstellungen vorzunehmen. Diese Einstellungen können dir die Arbeit mit plentyWarehouse deutlich erleichtern, da sie für alle Funktionen greifen. Natürlich kannst du diese allgemeinen Einstellungen jederzeit später wieder anpassen, falls deine Arbeitsweise sich einmal ändert.

[.instruction]
Allgemeine Einstellungen vornehmen:

. <<#300, Logge dich in plentyWarehouse ein>>.
. Tippe auf das Menüsymbol (icon:bars[role="darkGrey"]) oben links.
. Tippe unten auf *Einstellungen*. +
→ Das Einstellungsmenü öffnet sich.
. Nimm über die Menüpunkte im Bereich *Allgemeine Einstellungen* die Einstellungen vor. Beachte dazu die Erläuterungen in <<table-pw-general-settings>>.

[[table-pw-general-settings]]
.Allgemeine Einstellungen in plentyWarehouse
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Anzeige*
|

| *plentyBase*
|

| *Sprachausgabe*
|

| *Sonstiges*
|
|====


[#500]
== Aus plentyWarehouse bmelden

Gehe wie unten beschrieben vor, um dich aus plentyWarehouse abzumelden.

[.instruction]
Aus plentyWarehouse abmelden: 

. Tippe in der App oben links auf das Menüsymbol (icon:bars[role="blue"]).
. Tippe unten auf *Abmelden*. +
→ Das Fenster *Ausloggen* wird angezeigt.
. Bestätige, dass du dich wirklich abmelden möchtest. *_Hinweis:_* Beim nächsten Einloggen musst du alle Zugangsdaten erneut eingeben. +
→ Du wirst aus plentyWarehouse abgemeldet.