= PHPFunctions
:lang: de
// include::{includedir}/_header.adoc[]
:keywords: PHPFunctions
:position: 1

//  auto generated content Thu, 06 Jul 2017 00:59:27 +0200
== Kurzbeschreibung

Folgende PHP-Funktionen stehen auch innerhalb der CMS-Syntax zur Verfügung. Die Verwendung ist weitestgehend identisch mit der Verwendung direkt in PHP.

== Globale Template-Funktionen

* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-array-key-exists, array_key_exists>> — Prüft, ob ein Schlüssel in einem Array existiert.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-arsort, arsort>> — Sortiert ein Array in umgekehrter Reihenfolge und erhält die Index-Assoziation.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-asort, asort>> — Sortiert ein Array und erhält die Index-Assoziation.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-bin2hex, bin2hex>> — Gibt einen ASCII-String zurück, der die hexadezimale Wiedergabe des Parameters enthält.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-ceil, ceil>> — Liefert die nächste ganze Zahl, die größer oder gleich dem Parameter ist.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-count, count>> — Zählt alle Elemente eines Arrays oder Attribute eines Objekts.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-curl-close, curl_close>> — Beendet eine cURL-Session.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-curl-exec, curl_exec>> — Führt eine cURL-Session aus.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-curl-init, curl_init>> — Startet eine cURL-Session.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-curl-setopt, curl_setopt>> — Setzt eine Option für einen cURL-Transfer.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-current, current>> — Liefert das aktuelle Element eines Arrays.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-date, date>> — Formatiert ein(e) angegebene(s) Ortszeit/Datum.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-explode, explode>> — Teilt einen String anhand einer Zeichenkette zu einem Array.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-floor, floor>> — Liefert die nächste ganze Zahl, die kleiner oder gleich dem Parameter ist.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-htmlentities, htmlentities>> — Wandelt alle geeigneten Zeichen in entsprechende HTML-Codes um.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-implode, implode>> — Verbindet Array-Elemente zu einem String.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-in-array, in_array>> — Prüft, ob ein Wert in einem Array existiert.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-is-array, is_array>> — Prüft, ob die Variable ein Array ist.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-is-numeric, is_numeric>> — Prüft, ob eine Variable eine Zahl oder ein numerischer String ist.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-is-string, is_string>> — Prüft, ob Variable vom Typ string ist.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-json-decode, json_decode>> — Dekodiert eine JSON-Zeichenkette. Das Ergebnis kann in einer lokalen Template-Variablen gespeichert werden.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-json-encode, json_encode>> — Gibt die JSON-Repräsentation eines Wertes zurück.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-krsort, krsort>> — Sortiert ein Array nach Schlüsseln in umgekehrter Reihenfolge.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-ksort, ksort>> — Sortiert ein Array nach Schlüsseln.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-md5, md5>> — Errechnet den MD5-Hash eines Strings.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-natcasesort, natcasesort>> — Sortiert ein Array in natürlicher Reihenfolge, Groß/Kleinschreibung wird ignoriert.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-natsort, natsort>> — Sortiert ein Array in natürlicher Reihenfolge.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-nl2br, nl2br>> — Fügt vor allen Zeilenumbrüchen eines Strings HTML-Zeilenumbrüche ein.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-number-format, number_format>> — Formatiert eine Zahl mit Tausender-Gruppierung.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-print, print>> — Gibt enthaltenen Wert als HTML aus. Erlaubte Werte sind eine Template-Variable oder ein String.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-round, round>> — Rundet den ersten Parameter auf die im zweiten Paramter angegebene Anzahl von Nachkommastellen.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-rsort, rsort>> — Sortiert ein Array in umgekehrter Reihenfolge.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-simplexml-load-string, simplexml_load_string>> — Wandelt einen String in ein simpleXML-Objekt um und gibt dieses Objekt zurück.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-sort, sort>> — Sortiert ein Array.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-str-replace, str_replace>> — Ersetzt alle Vorkommen des Suchstrings durch einen anderen String.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-strip-tags, strip_tags>> — Entfernt HTML-Tags aus einem String.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-stripos, stripos>> — Findet das erste Vorkommen eines Strings, unabhängig von Groß- und Kleinschreibung.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-strlen, strlen>> — Ermitteln der String-Länge.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-strpos, strpos>> — Sucht das erste Vorkommen des Suchstrings.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-strtolower, strtolower>> — Setzt einen String in Kleinbuchstaben um.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-strtotime, strtotime>> — Wandelt ein beliebiges in englischer Textform angegebenes Datum in einen UNIX-Zeitstempel (Timestamp) um.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-strtoupper, strtoupper>> — Wandelt alle Zeichen eines Strings in Großbuchstaben um.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-substr, substr>> — Gibt einen Teil eines Strings zurück.
* <<omni-channel/online-shop/webshop-einrichten/cms-syntax#global-phpfunctions-trim, trim>> — Entfernt Whitespaces (oder andere Zeichen) am Anfang und Ende eines Strings.

== Globale Template-Variablen

* $ENT_COMPAT — Konstante: Konvertiert nur doppelte Anführungszeichen und lässt einfache Anführungszeichen unverändert.
* $ENT_QUOTES — Konstante: Konvertiert sowohl doppelte als auch einfache Anführungszeichen.

