= Relocation
:lang: en
include::{includedir}/_header.adoc[]
:keywords: Cloud relocation
:description: Cloud relocation
:position: 90

Use the menu **Start » plentymarkets account » Relocation** to relocate your system to a different cloud free of charge. The **Relocation** menu also lists the status of any currently planned relocation projects and information about any previous relocation projects. Refer to our website for further information about the link:https://www.plentymarkets.co.uk/product/cloud-hosting/[**cloud solutions provided by plentymarkets**].

== System relocation requirements

Make sure to fulfill the following requirements before you begin planning to relocate your system to a different cloud:

* Your domain must be managed by plentymarkets. If this is not the case, then relocate your <<start/plentymarkets-account/service-center/domain#, **main domain**  >>.
* You must have a current plentymarkets cloud contract. If this is not the case, then change your link:https://www.plentymarkets.co.uk/prices/book-plentymarkets-classic/[**contract**].
* The system relocation must be scheduled to begin at least 2 days in the future.

[WARNING]
.Files on FTP server are not migrated
====
When your system is relocated to a different cloud, the FTP host address of the plentymarkets system also changes. The files stored on the old FTP host are not copied to the new FTP host address during relocation. You need to move the FTP files manually.
====

== Planning a relocation

Proceed as described below to plan the relocation of your system to a different cloud. Please note that it is not possible to simultaneously relocate more than one system per cloud. As such, the relocation start time may be delayed.

[.instruction]
Planning a relocation:

. Go to **Start » plentymarkets account » Relocation**.
. Click on the **Plan relocation** tab.
. Select the target cloud, i.e. the cloud where you want to relocate your system to. +
→ The cost of the target cloud will be displayed.
. Select the date when the system relocation should begin.
. Select the time when the system relocation should begin. +
→ The system relocation must be scheduled to begin at least 2 days in the future.
. Click on **Start relocation** to request that the system be relocated. +
→ The planned relocation will be displayed in the **Planned relocation** tab. It will be started at the time indicated.

[IMPORTANT]
.Store availability
====
For mid-sized systems, relocation takes approximately 20 minutes. However, the actual duration always depends on the volume of data that is to be relocated. Your plentymarkets system is available during this time. However, you can not save any changes in the system. The order process is deactivated in your online store while your system is being relocated. Therefore, choose a time when you do not anticipate a large amount of traffic. We recommend that you plan the relocation for the middle of the night.
====

== Canceling a planned relocation

You can cancel a planned relocation any time before all of the processes in the menu **Start » plentymarkets account » Relocation » Tab: Planned relocation** have been completed. The relocation will be canceled as soon as possible. It may not be possible to cancel the relocation immediately. Proceed as described below to cancel a planned relocation.

[.instruction]
Canceling a relocation:

. Go to **Start » plentymarkets account » Relocation**.
. Click on the **Planned relocation** tab.
. Click on **Cancel relocation**. +
→ The relocation will be canceled as soon as possible. Processes that were already completed will be relocated back to the previous cloud.

If all processes have already been completed, i.e. if the system has been relocated completely, you will need to request a new relocation to move your system back to the previous cloud.

