= Gästebuch
:lang: de
include::{includedir}/_header.adoc[]
:position: 30

In einem Gästebuch können Ihre Kunden ihren Besuch in Ihrem Shop dokumentieren, indem sie dort eine Nachricht, eine Meinung oder einen Wunsch hinterlassen. Im Menü **Einstellungen » Mandant (Shop) » Standard » Module » Gästebuch** erstellen und konfigurieren Sie Gästebücher.

toc::[]
== Gästebuch erstellen und konfigurieren

Im Menü **Einstellungen » Mandant (Shop) » Standard » Module » Gästebuch** legen Sie die Sprache sowie die Darstellungsoptionen für das Gästebuch fest. Das Anlegen der Sprache ist Voraussetzung für die Konfiguration der Gästebuch-Einstellungen. Diese Einstellungen werden sprach- und mandantenspezifisch angelegt und sind erst nach Speichern der Sprache sichtbar. Gehen Sie wie unten beschrieben vor, um die Sprache und die weiteren Einstellungen festzulegen.

[.instruction]
Gästebuch erstellen und konfigurieren:

. Öffnen Sie das Menü **Einstellungen » Mandant (Shop) » Standard » Module » Gästebuch**.
. Klicken Sie auf das Tab **Neue Sprache**.
. Wählen Sie eine Sprache aus dem Dropdown-Menü.
. **Speichern** Sie die Einstellungen. +
→ Die Sprache wird im Tab **Sprache** angezeigt.
. Klicken Sie auf das **Plus** der gewünschten Sprache.
. Nehmen Sie die Einstellungen im Tab **Einstellungen** gemäß Tabelle 1 vor.
. **Speichern** Sie die Einstellungen.

[cols="a,a"]
|====
|Einstellung |Erläuterung

|**Format Datum**
|Das Format für die Darstellung des Datums aus dem Dropdown-Menü wählen.

|**Format Zeit**
|Das Format für die Darstellung der Uhrzeit aus dem Dropdown-Menü wählen.

|**Beiträge pro Seite**
|Wählen, wie viele Beiträge pro Seite im Gästebuch angezeigt werden sollen. Standardeinstellung ist 15.

|**BBCode erlauben**
|Wählen, ob die vereinfachte Auszeichnungssprache BBCode für die Formatierung der Texte der Gästebucheinträge erlaubt sein soll.

|**BBCode $img-Tag erlauben**
|Wählen, ob die vereinfachte Auszeichnungssprache BBCode für die Integration von Bildern in die Gästebucheinträge erlaubt sein soll.
|====

__Tab. 1: Gästebuch-Einstellungen__

== Bezeichner anpassen bzw. übersetzen

Im Tab **Bezeichner** hinterlegen Sie auf Wunsch eigene Bezeichnungen für die Standardbezeichner des Gästebuchs. Für ein Gästebuch in einer anderen Sprache hinterlegen Sie hier die Übersetzungen.

== Gästebuch in Design einbinden

Das Gästebuch wird über die Template-Variable **$Container_Guestbook** im Webshop angezeigt. Dazu fügen Sie die Template-Variable an geeigneter Stelle in eine Kategorie des Typs **Content** ein.

