= PageDesign
:lang: en
// include::{includedir}/_header.adoc[]
:position: 10

**plentymarkets » CMS » Web design » Layout » PageDesign**

== Content of this page

The following chapters describe the PageDesign in plentymarkets, i.e. the page structure that is controlled with the templates under PageDesign. This chapter provides you with basic information about using the templates as well as information about the HTML structure. The practical examples also provide more detailed information.

[IMPORTANT]
.Basic structures in the plentymarkets CMS
====
You will need to have basic knowledge of __**HTML**__ and __**CSS**__ in order to edit the templates in the plentymarkets CMS. Furthermore, we recommend that you first read and understand the information given in the <<omni-channel/online-store/_cms/web-design#, **Web design**  >> chapter. Pay special attention to the chapter <<omni-channel/online-store/cms-syntax#, **Basic information about syntax**  >> before you make changes to the templates. The <<omni-channel/online-store/_cms/web-design/basic-information-about-syntax/page-structure#, **Page structure**  >> chapter gives you an overview of the template structure in plentymarkets.
====

== General information about the page layout

The templates under **CMS » Web design » Layout » PageDesign** control the page structure and the design of various areas within the online store. We understand the page design to be your store's design frame including the complete content. Individual templates are used to display content such as the **items**, **categories**, **images**, **category pages (type: content)** or the **order process**. The templates already contain default content for displaying the different areas of the online store. However, this default content can be customized to meet your needs.

The layout is typically structured as follows: The area in the center is __**dynamic**__ which means that the content changes depending on which links or objects are clicked on. Items and category pages are displayed here, i.e. the different information pages such as the **terms and conditions**, **legal disclosure** or **contact information**. The **item search** and **categories** are dynamic pages as well. Clicking on a button will open the corresponding submenus. For example, clicking on a category will display its subcategories.

Most of the content on the sides of the page is static content which will neither change its form nor its size and will always be displayed at the same place. This content provides orientation for your customers and allows them to access any desired area of your online store.

== Page layout: Templates

The templates described below are used to customize your page design.

=== PageDesignContent

This page layout is used for displaying **categories** and **items**. You can select a different page layout for each category. This is configured in the **Settings** tab of each individual <<item/categories#, **category**  >>. It is also possible to use this template for the **checkout** and **my account** areas.

=== PageDesignCheckout

The template is automatically loaded when the <<omni-channel/online-store/_cms/web-design/editing-the-web-design/order-process/checkout#, **checkout**  >> area is accessed. We recommend that you design the template so that the main area spans the entire width of the online store. This means that no other elements will be displayed, as would be the case with a PageDesign that is composed of several columns. If no other elements are displayed, then the customer's attention will be focused exclusively on one area. This is especially important during the order process as it can help reduce the risk of customers deciding not to place an order at the last minute.

=== PageDesignMyAccount

The template is automatically loaded when the <<omni-channel/online-store/standard/my-account#, **my account**  >> area is accessed. We recommend that you design the template so that the main area spans the entire width of the online store. This means that no other elements will be displayed, as would be the case with a PageDesign that is composed of several columns. If no other elements are displayed, then the customer's attention will be focused exclusively on one area.

=== PageDesignCustom

This page layout offers three templates that can be used as an alternative for displaying **categories** and **items**. The templates can be selected in the category settings as an alternative to PageDesignContent.

=== PageDesignBlog

The template is automatically loaded when the **<<omni-channel/online-store/_cms/blog-weblog#, blog  >>** area is accessed.

=== PageDesignForum

The template is automatically loaded when the <<omni-channel/online-store/standard/modules/forum#, **forum**  >> area is accessed.

=== PageDesignPrepareMainColumn

Designs the main portion of the page layout.

== HTML structure

You can view and edit the HTML structure for every page layout. This is done in the tab with the ending **HtmlStructure**.

Please note that the wildcard characters in the following example should not be deleted as they are relevant for the function of plentymarkets.

The template contains the entire content of the particular page and gives the page the desired structure. The code is located in the **PageDesignContent** template and then in the **PageDesignContentHtmlStructure** tab. The simplified code looks like this:

[TIP]
.PageDesignContentHtmlStructure
====
$HtmlStartTag +
&lt;head&gt; +
&lt;title&gt;$HtmlMetaTitle&lt;/title&gt; +
$HtmlHeadLinkCSSTags +
$HtmlHeadJavaScriptTags +
$HtmlHeadMetaTags +
&lt;/head&gt; +
&lt;body&gt; +
$PageDesignContentMainFrame

$HtmlBodyOverlays +
&lt;/body&gt; +
&lt;/html&gt;
====

The following table explains the functions of the code elements in the **PageDesignContent** template:

[cols="a,a"]
|====
|Element |Explanation

|**$HtmlStartTag**
|The wildcard character includes the __**opening HTML tag**__ and specifies the __**DOCTYPE**__.

|**$HtmlMetaTitle**
|The __**page title**__ is displayed with this wildcard character. It is displayed in the title bar and as the tab title in most browsers. The page title is very important for the search function and for the ranking in search engines. Therefore, it should be short and it should be chosen appropriately.

|**$HtmlHeadLinkCSSTags**
|Implements the CSS specifications for the header.

|**$HtmlHeadJavaScriptTags**
|Implements the JavaScript content in the header.

|**$HtmlHeadMetaTags**
|This wildcard character implements meta tags, e.g. **keywords** that are important for __**search engine indexing**__.

|**$PageDesignContentMainFrame**
|This wildcard character inserts the content of the template **PageDesignContentMainFrame**. This template includes the wildcard character **MainFrame**. Therefore, this will also be explained below.

|**$HtmlBodyOverlays**
|Overlays are implemented here, e.g. a special layout for the shopping cart.
|====

__Table 1: elements of the tab **PageDesignContentHtmlStructure**__

