= Alter Webshop: Amazon Pay
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Amazon Pay, Amazon Payments Advanced, Zahlungsart
:description: Payment in plentymarkets: Richte die Schnittstelle zu Amazon Pay in deinem plentymarkets System ein.
:position: 40
:url: payment/zahlungsanbieter/amazon-pay
:nav-break: Alle Zahlungsanbieter

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *Amazon Pay* für Callisto Shops. Für die Verwendung von *Amazon Pay* in Ceres Shops erhältst du ausführliche Informationen in der Beschreibung des Plugins im link:https://marketplace.plentymarkets.com/plugins/payment/AmazonLoginAndPay_5072[plentyMarketplace^].
====

*Bezahlen mit Amazon* ist eine umfassende Zahlungslösung für Online-Händler. Durch *Bezahlen mit Amazon* gibst du Millionen von Amazon-Kunden die Möglichkeit, sicher auf deiner Website einzukaufen, ohne Versand- und Zahlungsinformationen erneut einzugeben. Kunden können Einkäufe rasch abschließen, ohne deine Website zu verlassen. Die Besonderheit der Advanced-Option von Bezahlen mit Amazon liegt darin, dass sie eine reine Zahlungsabwicklung bietet. Du übermittelst nur den zur Abwicklung der Transaktion notwendigen Zahlungsbetrag – ohne Details zum Warenkorb oder zu Artikeldaten.

[#10]
== Wichtige Hinweise

In diesem Kapitel findest du wichtige Hinweise zur Integration des Zahlungsanbieters in plentymarkets.

[NOTE]
.Amazon Pay und Webshop-Design
====
Beachte, dass für die erfolgreiche Integration von Amazon Pay in plentymarkets folgende Bedingungen erfüllt sein müssen:

* Verwendung des Standard-Designs Callisto (ab Version 3.4)
* Nutzung des Individuellen Bestellvorgangs
* Sicherer Umgang mit dem plentymarkets CMS
* Erfahrung mit der Einrichtung von Zahlungsdienstleistern
====

[IMPORTANT]
.Lieferzeiten beachten
====
Aufträge mit der Zahlungsart Amazon Pay sollten innerhalb von 30 Tagen abgewickelt werden, da sie sonst nach 30 Tagen automatisch storniert werden. Wenn du generell Artikel mit längeren Lieferzeiten verkaufst, kontaktiere bitte den Kundensupport von Amazon Pay. In Ausnahmefällen kann die 30-Tage-Frist verlängert werden.
====

[#20]
== Bezahlvorgang mit Amazon Pay

Nachdem der Kunde einen Artikel in den Warenkorb gelegt hat (Template: *ItemViewItemToBasketConfirmationOverlay*), wird eine Schaltfläche angezeigt (Template-Variable: *$AmazonPaymentsAdvancedButton*). Über diese Schaltfläche wird der Kunde direkt zu Amazon Pay weitergeleitet. Der Kunde muss sich daraufhin bei Amazon Pay einloggen. Der Kunde wird dann im Webshop durch die Widgets zur Bestätigung der Versandadresse sowie der Zahlungsart geführt. Danach durchläuft er die weiteren Schritte im Bestellvorgang wie üblich. Erst nach Abschluss der Bestellung wird die Zahlung durch Amazon Pay veranlasst. +
Die Bezahlung mit Amazon Pay kann auch aus dem Warenkorb heraus ausgeführt werden, wenn dort die entsprechende Schaltfläche angeklickt wird. Außerdem besteht die Möglichkeit, Amazon Pay erst im Checkout bei der Auswahl der Zahlungsart zu wählen. Hierbei wird der Kunde auf die Amazon-Pay-Seite weitergeleitet. Der oben beschriebene Ablauf erfolgt.

[#30]
=== SSL-Zertifikat

Zum einen benötigt dein Webshop ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>>, damit du die Zahlungsart Amazon Pay nutzen kannst. Außerdem ist es notwendig, nach der Konfiguration bzw. Änderungen das <<omni-channel/online-shop/webshop-einrichten/cms#webdesign-webdesign-bearbeiten, Design zu veröffentlichen>>, da verschiedene Elemente der Zahlungsart im *CMS* eingebunden sind.

[#40]
== Bei Amazon Pay registrieren

Du benötigst für die Zahlungsart *Amazon Pay* ein separates Konto für Amazon. Das im Menü *System » Systemeinstellungen » Märkte » Amazon » Einstellungen* angelegte Amazon Seller Central-Konto kannst du für die Zahlungsart Amazon Pay nicht nutzen. Der Registrierungsprozess als Händler bei *Bezahlen mit Amazon* wird im link:https://www.plentymarkets.eu/documents/category/2077/Login-und-Bezahlen-Registrierungshandbuch-DE-v1-2.pdf[Amazon-Pay-Registrierungshandbuch^] beschrieben.

Typischerweise dauert der Vorgang der Eröffnung eines Händlerkontos inklusive Verifikation 1 bis 2 Wochen. In der Zwischenzeit erhältst du weitere Anweisungen von Amazon Pay per E-Mail. Stelle sicher, dass diese E-Mails dem richtigen Bearbeiter weitergeleitet werden und folge den darin enthaltenen Anweisungen, um unnötige Verzögerungen zu vermeiden.

[IMPORTANT]
.Händler-URL und Integrator-URL eingeben
====
Du musst bei Amazon Pay unter Händler-URL und Integrator-URL *dein-plentyshop.de/plenty/api/payment_notification.php?payment=apa* eingeben. Ersetze *dein-plentyshop.de* durch die Adresse deines Shops. Die Adresse deines Shops findest du z.B. im Menü *System » Systemeinstellungen » Einstellungen » API » Daten* unter *Host*. Das Protokoll *https://* muss eingegeben werden. Die Vorgehensweise wird auch im link:https://www.plentymarkets.eu/documents/category/2077/Login-und-Bezahlen-Registrierungshandbuch-DE-v1-2.pdf[Amazon-Pay-Registrierungshandbuch^] beschrieben.
====

[#50]
== Amazon Pay in Callisto einrichten

Um die Schnittstelle zu Amazon Pay für deinen Callisto Shop in plentymarkets einzurichten, gehe wie im Folgenden beschrieben vor.

[.instruction]
Schnittstelle zu Amazon Pay einrichten:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
. Klicke auf *Amazon Pay*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechsle in das Tab *Schnittstelle*.
. Klappe den Mandanten auf.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-amazon-pay>>.
. *Speichere* die Einstellungen.

[[tabelle-schnittstelleneinrichtung-amazon-pay]]
.Schnittstelle zu Amazon Pay einrichten
[cols="1,3"]
|====
| Einstellung | Erläuterung

|*Händler-ID*
| Händler-ID eingeben, wie von Amazon erhalten.

|*Marktplatz-ID*
| Land wählen.

|*MWS Access Key ID*
| MWS Access Key ID eingeben, wie von Amazon erhalten.

|*Secret Key*
| Secret Key eingeben, wie von Amazon erhalten.

|*Sandbox-Modus*
|*Ja* = Testmodus ist aktiv, um die Zahlungsart zu testen. +
*Nein* = Testmodus ist ausgeschaltet, d.h. die Schnittstelle ist aktiv.

|*AddressWidget Width*
| Anzahl von Pixeln eingeben, um die Breite des Amazon Adress-Widgets festzulegen. Das Adress-Widget von Amazon wird statt der Auswahl der Lieferanschrift des Webshops angezeigt.

|*AddressWidget Height*
| Anzahl von Pixeln eingeben, um die Höhe des Amazon Adress-Widgets festzulegen. Das Adress-Widget von Amazon wird statt der Auswahl der Lieferanschrift des Webshops angezeigt.

|*AddressWidget ReadOnly Width*
| Anzahl von Pixeln eingeben, um die Breite des Amazon Adress-Widgets in der Bestellübersicht festzulegen. Das Adress-Widget von Amazon in der Bestellübersicht ist nicht editierbar.

|*WalletWidget Width*
| Anzahl von Pixeln eingeben, um die Breite des Amazon Zahlungsarten-Widgets festzulegen. Dieses Widget wird im Checkout anstelle der Auswahl der Zahlungsarten angezeigt, sofern Amazon Pay gewählt wurde. Damit wird dem Kunden die gewählte Zahlungsart angezeigt.

|*WalletWidget Height*
| Anzahl von Pixeln eingeben, um die Höhe des Amazon Zahlungsarten-Widgets festzulegen.

|*WalletWidget ReadOnly Width*
| Anzahl von Pixeln eingeben, um die Breite des Amazon Zahlungsarten-Widgets in der Bestellübersicht festzulegen. Die gewählte Zahlungsart wird in der Bestellübersicht in diesem Widget angezeigt und ist nicht editierbar.

|*Verfügbarkeit*
| Verfügbarkeit wählen. +
*1* - *10* = Nur Artikel bis zu der eingestellten Verfügbarkeit können mit Amazon Pay bezahlt werden. +
*Nicht prüfen* = Die Verfügbarkeit der Artikel wird nicht geprüft. +
Die <<artikel/artikel-verwalten#170, Verfügbarkeit>> wird im Tab einer Variante eingestellt. +
*Wichtig:* Amazon Pay verlangt generell den Versand eines Artikels innerhalb von maximal 30 Tagen. Andernfalls wird die Zahlung storniert.
|====

[IMPORTANT]
.Ein Konto pro Mandant (Shop)
====
Du benötigst für jeden Mandanten ein separates Konto bei Amazon Pay. Im Tab *Schnittstelle* findest du deshalb für jeden Mandanten ein eigenes Untermenü. Gib dort die individuellen Zugangsdaten für jeden Shop ein.
====

[#60]
== Zahlungsart aktivieren

Richte die <<payment/zahlungsarten-verwalten#20, Zahlungsart>> Amazon Pay im Tab *Einstellungen* der Zahlungsart ein. Prüfe zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#70]
== Amazon Pay im Callisto Webshop anzeigen

Optional zur standardmäßigen Anzeige von Amazon Pay im Webshop kannst du mit den Template-Funktionen *Container_CheckoutAmazonPaymentsAdvancedAddressWidget()* und *Container_CheckoutAmazonPaymentsAdvancedPaymentWidget()* das Adress-Widget und das Payment-Widget für Amazon Pay individuell in deinem Webshop anordnen. Außerdem findest du nachfolgend Beispiele für die Integration der Schaltfläche *Bezahlen mit Amazon* an den passenden Stellen im Design.

[WARNING]
.Keine Anpassungen am aktiven Design vornehmen
====
Nimm keine Änderungen an deinem aktiven Design vor. Bevor du Änderungen an deinem Design vornimmst, lege eine Sicherungskopie an, damit du jederzeit wieder zum Ursprungszustand zurückgelangst.
====

[#80]
=== Amazon-Pay-Widgets anzeigen

Gehe wie unten beschrieben vor, um das Adress-Widget und das Payment-Widget für Amazon Pay im Bestellvorgang anzuzeigen.

[.instruction]
Amazon-Pay-Widgets im Bestellvorgang anzeigen:

. Öffne das Menü *Artikel » Kategorien*.
. Öffne den Ordner des Designs, das du bearbeiten möchtest, z.B. Callisto Light 3.
. Öffne die Kategorie *Zahlung &amp; Versand*.
. Wechsle in das Tab *Beschreibung 1*.
. Füge das Code-Beispiel an der gewünschten Stelle ein.
. *Speichere* die Einstellungen.

[.subhead]
Code-Beispiel für Amazon-Pay-Widgets:

[source,plenty]
----
include::assets/EX-DE-Amazon-Payments-Advanced-Zahlung-Versand.html[]

----
[#90]
=== ItemViewItemToBasketConfirmationOverlay anpassen

Gehe wie unten beschrieben vor, um die Schaltfläche *Bezahlen mit Amazon* im Overlay für den Warenkorb an gewünschter Stelle einzubinden. Das Overlay wird angezeigt, nachdem der Kunde bei einem Artikel auf *In den Warenkorb* klickt.

[.instruction]
ItemViewItemToBasketConfirmationOverlay anpassen:

. Öffne das Menü *CMS » Webdesign*.
. Öffne den Ordner *Layout » ItemView*.
. Öffne das Template *ItemViewItemToBasketConfirmationOverlay*.
. Füge das Code-Beispiel an der gewünschten Stelle ein.
. *Speichere* die Einstellungen.

[.subhead]
Code-Beispiel für die Integration der Schaltflächen *Bezahlen mit Amazon* im Overlay:

[source,plenty]
----
include::assets/EX-DE-Amazon-Payments-Advanced-Overlay.html[]

----
[#100]
=== ItemViewBasketPreviewList anpassen

Gehe wie unten beschrieben vor, um die Schaltfläche *Bezahlen mit Amazon* in der Warenkorbvorschau anzuzeigen.

[.instruction]
ItemViewBasketPreviewList anpassen:

. Öffne das Menü *CMS » Webdesign*.
. Öffne den Ordner *Layout » ItemView*.
. Öffne das Template *ItemViewBasketPreviewList*.
. Füge das Code-Beispiel an der gewünschten Stelle ein.
. *Speichere* die Einstellungen.

[.subhead]
Code-Beispiel für die Integration der Schaltfläche *Bezahlen mit Amazon* in der Warenkorbvorschau:

[source,plenty]
----
include::assets/EX-DE-Amazon-Payments-Advanced-Warenkorbvorschau.html[]

----
[#110]
=== Kategorie Warenkorb anpassen

Gehe wie unten beschrieben vor, um die Schaltfläche *Bezahlen mit Amazon* im Warenkorb anzuzeigen.

[.instruction]
Kategorie Warenkorb anpassen:

. Öffne das Menü *Artikel » Kategorien*.
. Öffne den Ordner des Designs, das du bearbeiten möchtest, z.B. Callisto Light 3.
. Öffne die Kategorie *Warenkorb*.
. Wechsle in das Tab *Beschreibung 1*.
. Füge das Code-Beispiel an der gewünschten Stelle ein.
. *Speichere* die Einstellungen.

[.subhead]
Code-Beispiel für die Integration der Schaltfläche *Bezahlen mit Amazon* im Warenkorb:

[source,plenty]
----
include::assets/EX-DE-Amazon-Payments-Advanced-Warenkorb.html[]

----
[#120]
=== Kategorie Anmeldung anpassen

Gehe wie unten beschrieben vor, um die Schaltfläche *Bezahlen mit Amazon* auf der Anmeldeseite anzuzeigen.

[.instruction]
Kategorie Anmeldung anpassen:

. Öffne das Menü *Artikel » Kategorien*.
. Öffne den Ordner des Designs, das du bearbeiten möchtest, z.B. Callisto Light 3.
. Öffne die Kategorie *Anmeldung*.
. Wechsle in das Tab *Beschreibung 1*.
. Füge das Code-Beispiel an der gewünschten Stelle ein.
. *Speichere* die Einstellungen.

[.subhead]
Code-Beispiel für die Integration der Schaltflächen *Bezahlen mit Amazon* in der Anmeldung:

[source,plenty]
----
include::assets/EX-DE-Amazon-Payments-Advanced-Anmeldung.html[]

----

[#130]
== Benachrichtigungen automatisch senden

Mithilfe der in deinem plentymarkets System verfügbaren Ereignisaktionen kannst du die Kommunikation mit Kunden automatisieren, die Amazon Pay als Zahlungsart für ihre Aufträge gewählt haben. Im Folgenden werden die Ereignisaktionen für das automatische Versenden von <<payment/zahlungsanbieter/amazon-pay#80, Versandbestätigungen>>, <<payment/zahlungsanbieter/amazon-pay#90, Stornierungen>> sowie für die Abwicklung von <<payment/zahlungsanbieter/amazon-pay#100, Rückerstattungen>> und die Meldung <<payment/zahlungsanbieter/amazon-pay#150, abgelehnter Zahlungen>> beschrieben.

[IMPORTANT]
.Hinweis zum Versenden von Bestellbestätigungen
====
Analog zu den unten beschriebenen Ereignisaktionen kannst du eine Ereignisaktion für den automatischen Versand von Bestellbestätigungen per E-Mail einrichten. Beachte hierbei jedoch, dass Amazon Pay die E-Mail-Adressen von Kunden erst in dein plentymarkets System übermittelt, wenn die Kunden die Zahlung getätigt haben. Um Fehler zu vermeiden empfehlen wir, die Ereignisaktion so einzurichten, dass die E-Mail nicht bei Auftragseingang, sondern bei Zahlungseingang verschickt wird.
====

[#140]
=== Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch zu versenden, nachdem der Warenausgang gebucht wurde. Das Buchen des Warenausgangs und das Versenden der Versandbestätigung sollten nicht in einer Ereignisaktion erfolgen. Sonst kann es passieren, dass der Versand bestätigt wird, bevor der Warenausgang gebucht wurde. Richte daher eine separate Ereignisaktion zur Buchung des Warenausgangs ein, die gleichzeitig den Status z.B. auf 7.1 ändert. Den Statuswechsel nutzt du dann wiederum bei der Ereignisaktion zur Versandbestätigung als Ereignis, damit nur für Aufträge im festgelegten Status eine Versandbestätigung gesendet wird. Den gewünschten Status musst ggf. vorher im Menü <<auftraege/auftraege-verwalten#1200, System » Systemeinstellungen » Aufträge » Status>> erstellen.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 2.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 2 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Buchen des Warenausgangs
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Zahlungsart*
|*Amazon Pay*

|*Filter 2*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Aktion*
|*Auftrag &gt; Status ändern*
|
|====

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 3.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 3 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an Amazon Pay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
|*Status aus vorheriger Ereignisaktion wählen.*

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*Amazon Pay*

|*Aktion*
|*Versand &gt; Versandbestätigung an Amazon Pay senden*
|
|====

[#150]
=== Stornierungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Amazon automatisch über Stornierungen zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 4.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 4 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an Amazon Pay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für *stornierte Aufträge* wählen.

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*Amazon Pay*

|*Aktion*
|*Zahlungsarten &gt; Stornierung an Amazon Pay senden*
|
|====

[#160]
=== Rückerstattungen automatisch senden

Damit die Rückerstattung korrekte Beträge aufweist, erstelle einen *Auftragsstatus* für *Retouren* von Amazon Pay, der sicherstellt, dass die Retoure geprüft wurde und korrekt ist. Entsprechende Retouren müssen dann in diesen speziell dafür angelegten Auftragsstatus für Retoren gesetzt werden. Dieser Auftragsstatus sollte eine treffende Bezeichnung erhalten, z.B. *Retoure geprüft*, und muss bei den folgend beschriebenen Ereignisaktionen gespeichert werden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 5.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 5 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Rückerstattungen an Amazon Pay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für *geprüfte Retouren* wählen.

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*Amazon Pay*

|*Aktion*
|*Zahlungsarten &gt; Rückerstattung an Amazon Pay senden*
|
|====

Alternativ kannst du die Rückerstattung auch über den Auftrag veranlassen. Erstelle einen Auftragsstatus für Gutschriften von Amazon Pay, der sicherstellt, dass die Gutschrift geprüft wurde und korrekt ist. Entsprechende Gutschriften müssen dann in diesen Auftragsstatus gesetzt werden. Dieser Auftragsstatus sollte eine treffende Bezeichnung erhalten, z.B. Gutschrift geprüft. Speichere diesen Auftragsstatus bei den folgend beschriebenen Ereignisaktionen.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 6.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 6 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Rückerstattungen an Amazon Pay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für die *Gutschrift an Amazon Pay* wählen.

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Gutschrift*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*Amazon Pay*

|*Aktion*
|*Zahlungsarten &gt; Rückerstattung an Amazon Pay senden*
|
|====

[#170]
=== Abgelehnte Zahlungen automatisch melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um deine Kunden automatisch über abgelehnte Zahlungen zu informieren. Damit von Amazon abgelehnte Zahlungen automatisch per E-Mail an den Kunden und per Statuswechsel an dich gemeldet werden, erstelle einen *Auftragsstatus* für *abgelehnte Zahlungen* von Amazon Pay oder nutze einen vorhandenen Auftragsstatus.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 7.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 7 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Melden von abgelehnten Zahlungen durch Amazon Pay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Zahlung: Abgelehnt*
|

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*Amazon Pay*

|*Aktion 1*
|*Kunde &gt; E-Mail versenden*
| E-Mail-Vorlage wählen; +
*Kunde* wählen

|*Aktion 2*
|*Auftrag &gt; Status ändern*
| Auftragsstatus wählen, z.B. *[3.2] In Warteposition*
|====
