= atriga
:lang: de
include::{includedir}/_header.adoc[]
:keywords: atriga, atrigapaymax, Inkassodienstleister, Bonitätsprüfung
:description: Payment in plentymarkets: Richte den Inkassodienstleister atriga und die Bonitätsprüfung atrigapaymax in deinem plentymarkets System ein.
:position: 50
:url: payment/zahlungsanbieter/atriga
:id: HOMBF18

In plentymarkets hast du die Möglichkeit, sowohl nur link:http://gateway.atriga.com/dls/services/?DID=400005000[atriga Inkasso^] zu nutzen als auch atriga Inkasso in Verbindung mit der Bonitätsprüfung von link:http://www.atriga.de/co/atriga/paymax/paymax.html[atrigapaymax^].

[#10]
== atriga-Konditionen für plentymarkets

Für plentymarkets Kunden entstehen keinerlei Inkassokostenvorschüsse und keine Kosten bei Nichterfolg. Im Erfolgsfall erhältst du 100% Auszahlung. Ganz nach deiner Wahl, entweder online per DebitManager, E-Mail und/oder RSS-Feed, bist du jederzeit über den Ablauf der Inkassoaufträge informiert. In das atriga-link:http://gateway.atriga.com/dls/services/?DID=400002000[Inkassoverfahren^] ist die SCHUFA-Prüfung* deines Schuldners kostenfrei für dich integriert. Die Prüfung ermöglicht eine solide Einschätzung darüber, wie es um deinen Schuldner wirtschaftlich steht.

[.subhead]
Die atriga-Garantie

Durch atriga Inkasso entstehen keine nachträglichen Kosten – auch nicht im Nichterfolgsfall. Wird die Gesamtforderung bezahlt, erhältst du 100% deiner Haupt- und Nebenforderungen einschließlich Zinsen. Deshalb kannst du sofort – auch bei kleinen Rechnungsbeträgen – ohne Kostenrisiko professionelle Hilfe in Anspruch nehmen. +
Durch die SCHUFA-Prüfung* deines Schuldners passt atriga das Inkassoverfahren auf dessen wirtschaftliche Situation an und stellt sicher, dass alle Maßnahmen ergriffen werden, die zu einem Ausgleich deinerr offenen Forderung führen können (z.B.: individuell mit dir abgestimmte schriftliche Mahnungen, auch per E-Mail, Telefax und SMS, Meldung des Zahlungsverhaltens deines Schuldners an die SCHUFA* telefonischer Kontakt mit dem Schuldner durch geschulte atriga-Mitarbeiter und Juristen, persönlicher Schuldnerbesuch möglich, anschließendes Rechtsanwaltsmahnverfahren).

[.subhead]
Mahnverfahren Plus

Entscheide dich – falls notwendig – für die Durchführung eines gerichtlichen Mahnverfahrens, entstehen dir bei guter Schuldnerbonität nur Kosten für externe Vorschüsse (z.B. Gerichtsgebühren, Gerichtsvollziehergebühren), die du ohnehin bis zur Rückzahlung durch den Schuldner verauslagen müsstest.

* bei Firmen nur eingeschränkt möglich

[#20]
== Bei atriga registrieren

Registriere dich online kostenfrei und unverbindlich im atriga link:http://dm.atriga.de/[DebitManager™^].  +
Am Ende der Registrierung erhältst du eine atriga-Kundennummer. Die atriga-Kundennummer sendest du einfach per E-Mail an link:mailto:info@atriga.com[info@atriga.com]. Gib das Stichwort „plentymarkets“ im Betreff der E-Mail an, um die oben beschriebenen Konditionen zu erhalten. atriga stellt deinen Status dann auf plentymarkets Kunden um. Nach der Umstellung erhältst von atriga eine Nachricht und kannst anschließend die automatisierte Übertragung der Inkassomandate einrichten.  +
Sobald dein Schuldner zahlt, möchte atriga dir dein Guthaben möglichst noch am selben Tag überweisen. Hierfür benötigt atriga noch vor der Freischaltung eine von dir autorisierte Kontoverbindung, die du unter *Bankverbindungen* in deinem DebitManager™ hinterlegst.

[#30]
== Schnittstelle zu atriga einrichten

Die Schnittstelle ist in 2 Abschnitte unterteilt. Zusätzlich zur Aktivierung von atriga Inkasso kannst du auch die Bonitätsprüfung atrigapaymax aktivieren.

[#40]
=== atriga Inkasso einrichten

Für die Einrichtung der Schnittstelle benötigst du deinen Authentifizierungscode von atriga. Den Authentifizierungscode findest du im Backend deines DebitManager™. Damit der Authentifizierungscode bei atriga erstellt und angezeigt wird, muss die Abfrage für das XML-Interface freigeschaltet sein. Nachdem du deinen Authentifizierungscode kopiert hast, nimmst du die die folgenden Einstellungen in plentymarkets vor.

[.instruction]
Schnittstelle zu atriga Inkasso einrichten:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Dienste » atriga*.
. Fügen den kopierten *Authentifizierungscode* ein.
. Gib den numerischen Teil deiner *Kunden-ID* ein. +
→ z.B. 5555 bei der Kundennummer a-DE.0005555.
. *Speichere* die Einstellungen.

[IMPORTANT]
.Kunden-ID finden
====
Die Kunden-ID ist der Teil deiner atriga-Kundennummer ab der ersten Ziffer größer 0. Du findest die Kundennummer im sogenannten *InfoPanel* im DebitManager™. Wenn deine Kundennummer z.B. a-DE.00123456 ist, gibst du in plentymarkets 123456 ein.
====

[#50]
=== Bonitätsprüfung atrigapaymax einrichten

Wie du die Bonitätsprüfung atrigapaymax einrichtest, erfährst du im Folgenden. Bei jedem Einkauf eines Kunden erfolgt eine Prüfung.

[IMPORTANT]
.atrigapaymax und Webshop-Design
====
Beachte, dass für die erfolgreiche Integration von atriga in plentymarkets folgende Bedingungen erfüllt sein müssen:

* Verwendung des Standard-Designs Callisto (ab Version 3.4)
* Verwendung der plentymarketsCMStools (ab Version 1.08)
* Nutzung des Individuellen Bestellvorgangs
* Sicherer Umgang mit dem plentymarkets CMS
====

[.instruction]
Bonitätsprüfung atrigapaymax einrichten:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Dienste » atriga*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-einstellungen-atriga>>.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.

[[tabelle-einstellungen-atriga]]
.Einstellungen für eine Bonitätsprüfung mit atrigapaymax
[cols="1,3"]
|====
| Einstellung  | Erläuterung

|*Überprüfungsmethode*
|*Nachträgliche Bonitätsprüfung* = der Kunde gibt sein Einverständnis zur Prüfung und wird anschließend geprüft. Wenn er sein Einverständnis nicht gibt, stehen ihm die Zahlungsarten Rechnung, Lastschrift und Kreditkarte nicht zur Verfügung. Für die Prüfung sind Anpassungen an deinem Design notwendig. Im Template <<payment/zahlungsanbieter/atriga#120, PageDesignPrepareMainColumn>> müssen die Template-Variablen *AtrigaRequireUserConfirmation* und *AtrigaShowValidationError* angepasst werden.

|*Mindest-Warenkorbwert*
| Betrag, ab dem die Bonität geprüft wird. Wenn nichts eingegeben wurde, wird ab 0 Euro geprüft.

|*Maximaler Warenkorbwert*
| Betrag, bis zu dem die Bonität geprüft wird. Wenn der Warenkorbwert höher ist als der hier eingegebene Wert, wird keine Prüfung durchgeführt und dem Kunden werden die Zahlungsarten Lastschrift, Rechnungskauf und Kreditkarte nicht angeboten. Die Eingabe ist optional.

|*Abweichende Lieferanschrift*
| Wählen, ob für die 3 Zahlungsarten, für die eine Bonitätsprüfung durchgeführt wird, eine abweichende Lieferadresse erlaubt sein soll. +
*nur an Rechnungsanschrift erlaubt* = Eine abweichende Lieferadresse ist nicht erlaubt. +
*an separate Lieferanschrift erlaubt* = Eine abweichende Lieferadresse ist erlaubt.

|*Erlaubte Zahlungsart nach Bonität*
| Bonitätsergebnisse wählen, für die die Zahlungsart angezeigt wird. +
*Grün* = Die Zahlungsart wird nur Kunden mit grünem Bonitätsergebnis angezeigt. +
*Gelb* = Die Zahlungsart wird nur Kunden mit gelbem Bonitätsergebnis angezeigt. +
*Rot* = Die Zahlungsart wird nur mit rotem Bonitätsergebnis angezeigt. +
Mehrfachwahl möglich, um eine Zahlungsart für mehrere Bonitätsergebnisse anzeigen zu lassen.
|====

[.subhead]
Keine nachträgliche Änderung der Zahlungsart erlaubt

Wenn atrigapaymax aktiviert ist, kann ein registrierter Kunde die Zahlungsart eines Auftrags in seinem Konto nicht nachträglich ändern, selbst dann nicht, wenn du im Menü *Einrichtung » Mandant » Mandant wählen » Bestellvorgang » Einstellungen* für die Einstellung *Nachträgliche Änderung von Aufträgen erlauben* die Option *JA* gewählt hast.

[.subhead]
Bei fehlgeschlagener Prüfung erhält der Kunde negative Bonität

Wenn eine Bonitätsprüfung fehlschlägt, werden für den Kunden die Einstellungen eines negativen, d.h. roten, Bonitätsergebnisses berücksichtigt. Ob eine Prüfung fehlgeschlagen ist, kannst du im <<daten/api-log#, API-Log>> nachvollziehen. Die Prüfung ist fehlgeschlagen, wenn in der Response von atrigapaymax ein Error vermerkt ist. Beim nächsten Einkauf des Kunden wird erneut eine Prüfung durchgeführt.

[#60]
== Gültigkeit der Kaufabwicklungs-URL ändern

Inkassodienstleister wie atriga erhalten bei Eröffnung des Mahnverfahrens eine URL zur Auftragsübersicht des Auftrags, für den das Mahnverfahren eingeleitet werden soll. Wenn die Gültigkeit der URL zu knapp eingestellt ist, z.B. auf 7 Tage, kommt es zu einer Fehlermeldung (Beispiel: "Code: 111 Die Auftragsdaten können nicht mehr über die kurze Adresse aufgerufen werden. Bitte loggen Sie sich in Ihr Konto mit E-Mail-Adresse und Passwort ein, um die Auftragsdetails aufzurufen."). In diesem Fall musst du die Gültigkeit erhöhen:

[.instruction]
Gültigkeit ändern:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Mein-Konto » Grundeinstellungen*.
. Stelle einen höheren Wert für die Option *Gültigkeit der Kaufabwicklungs-URL* ein.
. *Speichere* die Einstellungen.

[#70]
== Aufträge übergeben

Du kannst Aufträge manuell oder automatisch für Inkassoverfahren übergeben.

=== Aufträge manuell übergeben

[#80]
Mit der Gruppenfunktion übergibst du Aufträge manuell an atriga Inkasso. Die Anzahl der Aufträge, die manuell übergeben wird, bestimmst du durch deine Auswahl. Das heißt, du kannst über die Gruppenfunktion auch einzeln Aufträge übergeben.

[.instruction]
Aufträge manuell übergeben:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Wähle einen oder mehrere Aufträge, indem du ein Häkchen setzt.
. Klicke auf *Gruppenfunktion*.
. Setze ein Häkchen bei *an atriga (Inkasso) übergeben*.
. Wenn du Mandanten hast, wähle einen Mandanten aus der Dropdown-Liste. +
→ Die Übergabe erfolgt an das Konto des Mandanten.
. Klicke auf *Anwenden*, um die Aufträge zu übergeben.

[#90]
=== Aufträge automatisch übergeben

Mit einer Aktion des *Aktionsmanagers* übergibst du die gewünschten Aufträge für ein Inkassoverfahren automatisch an atriga. Nur *Aufträge*, bei denen eine *Rechnung* oder eine *externe Rechnung* hinterlegt ist, werden an atriga übertragen.

[.instruction]
Aufträge automatisch übergeben:

. Öffne das Menü *Einrichtung » Aufträge » Aktionen*.
. Klicke auf das Tab *Neue Aktion*, um eine neue Aktion zu definieren.
. Wähle im Tab *Einstellungen* eine *Uhrzeit*.
. Setze ein Häkchen bei *Aktiv*.
. Gib einen *Namen* für die Aktion ein.
. Wechsle in das Tab *Filter*.
. Nimm die zu deinem Geschäftsablauf passenden Einstellungen im Tab *Filter* vor.  +
→ <<bild-aktion-atriga-konfigurieren>> zeigt eine Kombination der Einstellungen im Tab *neue Aktion*.
. Wähle im Tab *Aktion* für *atriga (Inkasso)* die Einstellung *AKTIV*.
. *Speichere* die Einstellungen.

Im Beispiel in <<bild-aktion-atriga-konfigurieren>> werden alle Aufträge, die sich seit *20 Tagen* im Status *3 Warten auf Zahlung* befinden, an atriga geschickt. Im atriga link:http://dm.atriga.de/[DebitManager™^] findest du Informationen zu deinen Inkassoaufträgen.

[IMPORTANT]
.Beschränkung auf Deutschland
====
Aktuell können nur Schuldner aus Deutschland an atriga übergeben werden.
====

[#100]
== Fehlgeschlagene Inkassoübergaben erneut übergeben

Sobald ein Auftrag an atriga übertragen wurde, ist er geblockt und kann nicht erneut übertragen werden. Eine Ausnahme besteht, wenn die erste Übertragung nicht erfolgreich war, z.B. aufgrund einer fehlerhaften Adresse. In diesem Fall kannst du den Auftrag gezielt zurücksetzen und noch einmal korrekt übertragen lassen.

[.instruction]
Auftrag zurücksetzen:

. Öffne das Menü *Aufträge » Inkasso-Übergaben*.
. Wähle einen oder mehrere Aufträge.
. Klicke auf *Aufträge zurücksetzen*. +
→ Du kannst den Auftrag erneut übergeben.

[#110"]
== Zahlungseingang für bereits übergebene Aufträge melden

Wenn ein Auftrag bereits an atriga übergeben wurde, werden Informationen über einen später eintreffenden Zahlungseingang nicht an atriga übertragen. Diese Möglichkeit ist seitens der atriga-Schnittstelle leider nicht vorgesehen. Melde in diesem Fall den Auftrag direkt bei atriga als bezahlt.

[#120"]
== Design für Bonitätsprüfung anpassen

Die Template-Variablen *AtrigaRequireUserConfirmation* und *AtrigaShowValidationError* bieten die Möglichkeit eine Einwilligung des Kunden zur Bonitätsprüfung in deinem Design zu integrieren.

[WARNING]
.Keine Anpassungen am aktiven Design vornehmen
====
Nimm keine Änderungen an deinem aktiven Design vor. Bevor du Änderungen an deinem Design vornimmst, lege eine Sicherungskopie an, damit du jederzeit wieder zum Ursprungszustand zurückgelangst.
====

[.instruction]
Design für Bonitätsprüfung anpassen:

. Öffne das Menü *CMS » Webdesign*.
. Öffne den Ordner *Layout » PageDesign*.
. Klicke auf *PageDesignPrepareMainColumn*.
. Suche die Template-Variablen *AtrigaRequireUserConfirmation* und *AtrigaShowValidationError*.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-template-variable-bonität>>.
. *Speichere* die Einstellungen.

[[tabelle-template-variable-bonität]]
.Template-Variablen für die Bonitätsprüfung
[cols="1,3"]
|====
| Element | Erläuterung

|*AtrigaRequireUserConfirmation*
|*true* = Zeigt eine Checkbox im Bestellvorgang an, die der Kunde aktivieren kann und damit der Bonitätsprüfung zustimmt. Diese Einstellung wird empfohlen. +
*false* = Die Checkbox zur Einwilligung des Kunden wird im Bestellvorgang nicht angezeigt.

|*AtrigaShowValidationError*
|*true* = Wenn die vom Kunden gewählte Zahlungsart aufgrund der Bonitätsprüfung abgelehnt wird, wird eine Fehlermeldung angezeigt. Beim Klick auf *Mehr Informationen* wird ein Fenster geöffnet, in dem genauere Informationen von atriga zur nicht verfügbaren Zahlungsart stehen. +
*false* = Das Fenster mit genaueren Informationen von atriga zur nicht verfügbaren Zahlungsart wird direkt nach abgelehnter Bonitätsprüfung geöffnet. Die vorherige Fehlermeldung wird übersprungen.
|====

[#130"]
== Inkasso-Übergaben anzeigen

Eine Übersicht der an atriga übermittelten Aufträge zeigst du im Menü *Aufträge » Inkasso-Übergaben* im Bereich *atriga (Inkasso)* an.
