= Alter Webshop: BitPay
:lang: de
include::{includedir}/_header.adoc[]
:keywords: BitPay, Zahlungsart
:description: Payment in plentymarkets: Richten Sie die Schnittstelle zu BitPay in Ihrem plentymarkets System ein.
:position: 60

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *BitPay* in Callisto Shops. Die folgenden Anleitungen sind somit nicht für Ceres Shops gültig!
====

BitPay ist ein marktführender Zahlungsanbieter für die virtuelle Peer-to-Peer-Währung Bitcoin. Mit BitPay können Transaktionen unmittelbar und überall auf der Welt vorgenommen werden und das ganz ohne Betrugs- oder Ausgleichsrisiko.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhalten Sie wichtige Hinweise zur Integration des Zahlungsanbieters in plentymarkets.

[.subhead]
Bezahlvorgang

Nach dem Abschluss der Bestellung erhält der Kunde eine Meldung, dass die Zahlung noch über einen Link abgeschlossen werden muss. Bei Klick auf den angezeigten Link wird der Kunde auf die Seite von BitPay weitergeleitet. Hier müssen erforderliche Daten für die Bezahlung eingegeben werden. Nach Eingabe und Bestätigung der Daten wird der Kunde auf die Bestellbestätigungsseite geleitet.

[.subhead]
Manueller Zahlungsimport

Zahlungen von BitBay werden nicht automatisch in plentymarkets importiert. BitPay-Zahlungen müssen Sie <<payment/zahlungen-verwalten#40, manuell buchen>>.

[#20]
== Bei BitPay registrieren

Bevor Sie die Zahlungsart in plentymarkets einrichten können, ist eine Registrierung bei BitPay erforderlich. Die Registrierung nehmen Sie über das link:https://bitpay.com/start[Kontaktformular^] vor. Sie erhalten dann die nötigen Informationen sowie Zugangsdaten, die Sie für die Konfiguration in plentymarkets benötigen.

[#30]
== BitPay in Callisto einrichten

Gehen Sie wie unten beschrieben vor, um die Schnittstelle zu BitPay für Ihren Callisto Shop in plentymarkets einzurichten.

[.instruction]
Schnittstelle zu BitPay einrichten:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
.  Klicken Sie auf *BitPay*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechseln Sie in das Tab *Schnittstelle*.
.  Klappen Sie den Mandanten auf.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-bitpay>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelleneinrichtung-bitpay]]
.Schnittstelle zu BitPay einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*ApiKey*
|Api-Schlüssel von BitPay eingeben. Der link:https://bitpay.com/api-keys[ApiKey^] kann nach der Registrierung bei BitPay erzeugt werden.

|*E-Mail-Benachrichtigung an*
|E-Mail-Adresse eingeben, an die Benachrichtigungen über Zahlungen gehen sollen.

|*Transaktionsgeschwindigkeit*
|Transaktionsgeschwindigkeit wählen. +
*low* = geringe Geschwindigkeit +
*medium* = mittlere Geschwindigkeit +
*high* = hohe Geschwindigkeit

|*Testbetrieb aktivieren*
|Testbetrieb aktivieren, um die BitPay-Funktionen zu testen, bevor mit dem System live gearbeitet wird.

2+|Mandant (Shop)-Optionen

|*Zugangsdaten für alle Mandanten (Shops) aktivieren*
|Nur sichtbar, wenn Mandanten eingerichtet sind. Aktivieren, um die Kontoeinstellungen, die über *Konto hinzufügen* für den Hauptshop gespeichert wurden, für alle Mandanten (Shops) zu übernehmen, unabhängig davon, was für andere Mandanten gespeichert wurde. Deaktivieren, um separate Zugangsdaten für weitere Mandanten (Shops) zu verwenden. Webshops, für die kein Konto hinzugefügt wurde, können mit BitPay nicht genutzt werden. +
Zur Unterstützung mehrerer Mandanten muss im Menü <<webshop/webshop-einrichten#grundeinstellungen, System » Mandant » Mandant wählen » Webshop » Einstellungen>> für die Option *Login* die Einstellung *Login in jedem einzelnen Shop ermöglichen* aktiviert sein.
|====

[#40]
== Zahlungsart aktivieren

Richten Sie die <<payment/zahlungsarten-verwalten#20, Zahlungsart>> BitPay im Tab *Einstellungen* der Zahlungsart ein. Prüfen Sie zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#50]
== API-Log abrufen

Im sehr seltenen Fall eines Fehlers bei der Datenübertragung können Sie im API-Log Details zum jeweiligen Fehler finden. Je nach Art des Fehlers wird Ihre Zahlung zwar bei BitPay gebucht, aber u.U. nicht in plentymarkets bestätigt, was wiederum zu einer fehlerhaften Buchung in plentymarkets führt.

[.instruction]
API-Log abrufen:

.  Öffnen Sie das Menü *Daten » API-Log » Tab: API-Log*.
.  Wählen Sie ein Format aus der Dropdown-Liste *Vorgang*.
.  Wählen Sie ggf. ein *Datum*, um nur Einträge eines bestimmten Tages zu erhalten.
.  Klicken Sie auf *Suchen*, um die Suche auszuführen. +
→ Die Vorgänge werden angezeigt.
