= Alter Webshop: CrefoPay
:lang: de
include::{includedir}/_header.adoc[]
:keywords: CrefoPay, Zahlungsart
:description: Payment in plentymarkets: Richte die Schnittstelle zu CrefoPay in deinem plentymarkets System ein.
:position: 80
:url: payment/zahlungsanbieter/crefopay
:id: 34EYYS7

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *CrefoPay* in Callisto Shops. Die folgenden Anleitungen sind somit nicht für Ceres Shops gültig!
====

link:https://www.creditreform.de/crefopay.html[CrefoPay^] wird angeboten vom Verband der Vereine Creditreform e.V. und ist eine Payment-Lösung für den Online-Handel.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhältst du wichtige Hinweise zur Integration des Zahlungsanbieters *CrefoPay* in plentymarkets.

[IMPORTANT]
.CrefoPay und Webshop-Design
====
Beachte, dass für die erfolgreiche Integration von CrefoPay in plentymarkets folgende Bedingungen erfüllt sein müssen:

* Verwendung des Standard-Designs Callisto (ab Version 2)
* Nutzung des Individuellen Bestellvorgangs
* Sicherer Umgang mit dem plentymarkets CMS
* Erfahrung mit der Einrichtung von Zahlungsdienstleistern
====

[.subhead]
Bezahlvorgang

Je nach gewählter Zahlungsart wird der Kunde nach dem Bestätigen der Bestellung auf eine Seite von CrefoPay weitergeleitet oder muss seine Daten direkt in einem eingeblendeten iframe eingeben. Wenn der Kunde weitergeleitet wurde, muss er dort die Daten für die gewählte Zahlungsart eingeben. Nachdem die Daten eingegeben wurden und die Zahlung durch den Kunden bestätigt wurde, wird der Kunde zurück zu deinem Webshop geleitet. Zahlungsarten, bei denen der Kunde weitergeleitet wird, sind Sofortüberweisung und PayPal (Stand 01.06.2016).

[#20]
== Bei CrefoPay registrieren

Registriere dich bei CrefoPay, bevor du mit der Einrichtung in plentymarkets fortfährst. Nimm hier link:http://www.creditreform.de/microsites/crefopay-kontakt.html[Kontakt^] zu CrefoPay auf.

[#30]
== CrefoPay in Callisto einrichten

Gehe wie unten beschrieben vor, um die Schnittstelle zu CrefoPay für deinen Callisto Shop in plentymarkets einzurichten.

[.instruction]
Schnittstelle zu CrefoPay einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *DE*.
. Klicke auf *CrefoPay*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechsle in das Tab *Schnittstelle*.
. Klappe den Mandanten auf.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-crefopay>>.
. *Speichere* die Einstellungen.

[[tabelle-schnittstelleneinrichtung-crefopay]]
.Schnittstelle zu CrefoPay einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Testmodus*
|Testmodus aktivieren, um die Datenübertragung zwischen plentymarkets und CrefoPay zu testen, ohne dass tatsächlich Zahlungen ausgeführt werden.

|*Händler-ID*
|Händler-ID eingeben, wie von CrefoPay erhalten.

|*Private Key*
|Private Key eingeben, wie von CrefoPay erhalten.

|*Shop-ID*
|Shop-ID eingeben, wie von CrefoPay erhalten.
|====

[#40]
== Zahlungsart aktivieren

Richte die <<payment/zahlungsarten-verwalten#20, Zahlungsart>> CrefoPay im Tab *Einstellungen* der Zahlungsart ein. Prüfe zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>. Die anzubietenden Zahlungsarten legst du direkt bei CrefoPay fest.

[#50]
== Einstellungen im CrefoPay-Konto vornehmen

In deinem CrefoPay-Konto gibst du die URLs für die Integration ein und wählst die Zahlungsarten, die du mit CrefoPay anbieten möchtest. Ob einem Kunden die Zahlungsarten tatsächlich angeboten werden, hängt von weiteren Faktoren, z.B. Fraud-Regeln, ab. In deinem CrefoPay-Konto gibt es einen Bereich für die Integration. In diesem Integrationsbereich gibst du zwei URLs ein und wählst die Zahlungsarten, die du nutzen möchtest. Die URLs müssen folgendem Schema entsprechen:

* Weiterleitungs-URL: https://MEIN-PLENTYSHOP.de/plenty/api/payment_notification.php?payment=crefopayredirectk
* Benachrichtigungs-URL: https://MEIN-PLENTYSHOP.de/plenty/api/payment_notification.php?payment=crefopay

[#60]
== CrefoPay im Callisto Webshop anzeigen

In diesem Kapitel wird beschrieben wie du CrefoPay im Webshop von plentymarkets anzeigst. Hierfür sind mehrere Schritte nötig. Zunächst wird die Kategorie *Bestellbestätigung* angepasst.

[WARNING]
.Keine Anpassungen am aktiven Design vornehmen
====
Nimm keine Änderungen an deinem aktiven Design vor. Bevor du Änderungen an deinem Design vornimmst, lege eine Sicherungskopie an, damit du jederzeit wieder zum Ursprungszustand zurückgelangst.
====

[#61]
=== Kategorie Bestellbestätigung anpassen

Damit die von CrefoPay angebotenen Zahlungsarten deinen Kunden im Webshop zur Verfügung stehen, musst du Änderungen an der Kategorie *Bestellbestätigung* vornehmen.

[.instruction]
Zahlungsartenauswahl in der Bestellbestätigung hinzufügen:

. Öffne das Menü *Artikel » Kategorien*.
. Öffne den Ordner des Designs, das du bearbeiten möchtest, z.B. Callisto Light 3.
. Öffne die Kategorie *Bestellbestätigung*.
. Wechsle in das Tab *Beschreibung 1*.
. Suche *div class="panel-body"*.
. Ersetze den Inhalt dieses Div-Containers mit dem Code aus dem Code-Beispiel.
. *Speichere* die Einstellungen.

[source,plenty]
----
include::assets/EX-DE-Crefopay-Bestellbestaetigung.html[]

----
[#63"]
=== CheckoutCustomerInvoiceAddress anpassen

Um bei der Adresseingabe nur für CrefoPay gültige Werte anzuzeigen, ist noch eine Anpassung im Template *CheckoutCustomerInvoiceAddress* notwendig.

[.instruction]
CheckoutCustomerInvoiceAddress anpassen:

. Öffne das Menü *CMS » Webdesign*.
. Öffne den Ordner *Layout » Checkout*.
. Öffne das Template *CheckoutCustomerInvoiceAddress*.
. Suche im Code die Stelle *&lt;option value="3"{% if $FormOfAddressID == 3 %} selected{% endif %}&gt;Familie&lt;/option&gt;*.
. Lösche die Code-Zeile aus dem Template.
. *Speichere* die Einstellungen.

[#64"]
=== CheckoutCustomerShippingAddress anpassen

Die gleiche Änderung nimmst du im Template *CheckoutCustomerShippingAddress* analog vor.

[.instruction]
CheckoutCustomerShippingAddress anpassen:

. Öffne das Menü *CMS » Webdesign*.
. Öffne den Ordner *Layout » Checkout*.
. Öffne das Template *CheckoutCustomerShippingAddress*.
. Suche im Code die Stelle *&lt;option value="3"{% if $FormOfAddressID == 3 %} selected{% endif %}&gt;Familie&lt;/option&gt;*.
. Lösche die Code-Zeile aus dem Template.
. *Speichere* die Einstellungen.

[#65"]
=== Namensprüfung für B2B-Kunden einrichten

CrefoPay benötigt bei Bestellungen von B2B-Kunden den Vor- und Nachnamen des Kunden auf der Rechnungsadresse. Die Template-Variablen *ValidateInvoiceAddressFirstNameIfCompany* und *ValidateInvoiceAddressLastNameIfCompany* bieten die Möglichkeit Vor- und Nachnamen von B2B-Kunden für Rechnungsadressen zu prüfen, wenn das Textfeld *Firma* ebenfalls gefüllt ist.

[.instruction]
Namensprüfung für B2B-Kunden einrichten:

. Öffne das Menü *CMS » Webdesign*.
. Öffne den Ordner *Layout » PageDesign*.
. Klicke auf *PageDesignPrepareMainColumn*.
. Suche die Template-Variablen *ValidateInvoiceAddressFirstNameIfCompany* und *ValidateInvoiceAddressLastNameIfCompany*.
. Ändere die Werte der beiden Variablen von *false* auf *true*. Beachte dazu auch die Erläuterungen in <<template-variablen-b2b>>.
. *Speichere* die Einstellungen.

[[template-variablen-b2b]]
.Template-Variablen für B2B-Kunden
[cols="1,3"]
|====
| Element | Erläuterung

|*ValidateInvoiceAddressFirstNameIfCompany*
|*true* = Prüfen, ob der *Vorname* eingegeben wurde, wenn in der Rechnungsadresse das Textfeld *Firma* gefüllt ist. +
*false* = Textfeld *Vorname* nicht prüfen.

|*ValidateInvoiceAddressLastNameIfCompany*
|*true* = Prüfen, ob der *Nachname* eingegeben wurde, wenn in der Rechnungsadresse das Textfeld *Firma* gefüllt ist. +
*false* = Textfeld *Nachname* nicht prüfen.
|====

[#70]
==  Versandbestätigungen automatisch senden

Damit CrefoPay Beträge an dich auszahlt, musst du bestätigen, dass du dem Kunde die Ware gesendet hast. Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch zu versenden, nachdem der Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß Tabelle 3.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß Tabelle 3 vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an CrefoPay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag* +
Lieferauftrag - optional für Teillieferungen

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*CrefoPay*

|*Aktion*
|*Versand &gt; Versandbestätigung an CrefoPay senden*
|
|====

[#80]
==  Rückerstattungen automatisch senden

Wenn ein Käufer Artikel retourniert, legst du eine Retoure an und melden diese an CrefoPay, damit der Kunde das Geld von CrefoPay zurück erhält. Mithilfe einer Ereignisaktion wird die Retoure automatisch an CrefoPay gemeldet.

[.instruction]
Retoure anlegen:

[#90]

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den CrefoPay-Auftrag. +
→ Das Tab *Übersicht* wird geöffnet.
. Wähle die Option *anlegen* aus der Dropdown-Liste *Retoure ...*.
. Wähle die Artikel, die retourniert wurden. +
→ Die Retoure wird angelegt und geöffnet.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß Tabelle 4.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß Tabelle 4 vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Rückerstattungen an CrefoPay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*CrefoPay*

|*Aktion*
|*Zahlungsarten &gt; Rückerstattung an CrefoPay senden*
|
|====

[#100]
==  Stornierungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um CrefoPay automatisch über Stornierungen zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß Tabelle 5.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß Tabelle 5 vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an CrefoPay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für *stornierte Aufträge* wählen.

|*Filter*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*CrefoPay*

|*Aktion*
|*Zahlungsarten &gt; Stornierung an CrefoPay senden*
|
|====

[#110]
== Rückerstattung bei Teilstornierung an CrefoPay senden

Wenn du z.B. einen Artikel, den der Kunde bestellt hat, doch nicht mehr liefern kannst, melde dies an CrefoPay, damit der Kunde sein Geld von CrefoPay zurück erhält. Diese Rückerstattung löst du direkt am Auftrag aus, indem du an CrefoPay meldest, dass der Auftrag abgeschlossen wurde. Daraufhin erhält der Kunde den Differenzbetrag von CrefoPay, der übrig bleibt, wenn die versandten Artikel vom Gesamtbetrag abgezogen werden.

[.instruction]
Rückerstattung melden:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den CrefoPay-Auftrag. +
→ Das Tab *Übersicht* wird geöffnet.
. Wechsle in das Tab *Einstellungen*.
. Klicke auf *CrefoPay-Zahlungsvorgang abschließen*.

Wenn ein Kunde mehr als den Auftragsbetrag gezahlt hat, kannst du den Zahlungsvorgang auch abschließen, um dem Kunden den zuviel gezahlten Betrag zu erstatten.
