= Alter Webshop: ExperCash
:lang: de
include::{includedir}/_header.adoc[]
:keywords: ExperCash, Zahlungsart
:description: Payment in plentymarkets: Richten Sie die Schnittstelle zu ExperCash in Ihrem plentymarkets System ein.
:position: 90

Die link:http://expercash.de/[ExperCash GmbH^] fusionierte im April 2016 mit MasterCard Payment Gateway Services Client Finance Ltd. Als Zahlungsanbieter für komplettes Financial Supply Chain Management unterstützt ExperCash mit seinen Payment-Lösungen Online-Shops bei der Abwicklung aller Prozesse rund um deren Zahlungsvorgänge.

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *ExperCash* in Callisto Shops. Die folgenden Anleitungen sind somit nicht für Ceres Shops gültig!
====

[#10]
== Wichtige Hinweise

In diesem Kapitel erhalten Sie wichtige Hinweise zur Integration des Zahlungsanbieters in plentymarkets.

[#20]
=== Bezahlvorgang

Die Auswahl der Zahlungsart erfolgt noch im Webshop. Anschließend wird der Kunde direkt zu ExperCash weitergeleitet. Die weiteren Inhalte werden in einem iframe bereitgestellt. Der Kunde gibt hier seine Daten ein. Dies erfolgt somit nicht im Webshop, sondern bei ExperCash. Nach der Eingabe und Bestätigung der Daten wird der Kunde auf die Bestellbestätigungsseite geleitet. Das iframe von ExperCash unterstützt aktuell die folgenden Sprachen: Deutsch, Englisch, Französisch, Italienisch und Spanisch. Die Sprache, die der Kunde im Checkout gewählt hat, wird auch automatisch für die Zahlungsabwicklung mit ExperCash verwendet.

[#30]
=== SSL-Zertifikat

Für die korrekte Verwendung der Zahlungsart ist ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>> erforderlich.

[WARNING]
.Fragen Sie Ihre Bank
====
Klären Sie vor einer Integration der Zahlungsart *ExperCash*, ob Ihre Bank die Abwicklung über iframes unterstützt.
====

[#40]
=== Verfügbare ExperCash-Zahlungsarten

Nachfolgend finden Sie eine Übersicht der für plentymarkets verfügbaren ExperCash-Zahlungsarten mit der System-ID in Klammern.

* Giropay (820)
* Kreditkarte (850)
* Kreditkarte Autorisierung/Reservierung (840)
* Lastschrift (810)
* Sofortüberweisung (830)
* Zahlungsauswahl durch den Endkunden (800)

[#50]
=== Währungen

Alle Beträge werden vor der Zahlung in die Webshop-Standardwährung umgerechnet. Alle Endkunden zahlen in dieser Währung. Für Kreditkartenzahlungen in unterschiedlichen Währungen müsste pro Währung ein separater Vertrag mit ExperCash abgeschlossen werden, weshalb plentymarkets immer in die Standardwährung des Webshops umrechnet.

[#60]
== Bei ExperCash registrieren

Um ExperCash in plentymarkets aktivieren zu können, müssen Sie sich bei Expercash registrieren. Kontaktieren Sie dafür die MasterCard Payment Gateway Services Client Finance Ltd per E-Mail an link:mailto:service_mpgs_dach@mastercard.com[service_mpgs_dach@mastercard.com].

[#70]
== ExperCash in Callisto einrichten

Gehen Sie wie unten beschrieben vor, um die Schnittstelle zu ExperCash für Ihren Callisto Shop in plentymarkets einzurichten.

[.instruction]
Schnittstelle zu ExperCash einrichten:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *DE*.
.  Klicken Sie auf *ExperCash*. +
→ Das Tab *Schnittstelle* wird geöffnet.
.  Klappen Sie den Mandanten auf.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-expercash>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelleneinrichtung-expercash]]
.Schnittstelle zu ExperCash einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Popup-ID*
|Zugangskennung zum Shop eingeben, wie von ExperCash erhalten.

|*Authorisation Key*
|Iframe-Sicherheitsschlüssel eingeben, wie von ExperCash erhalten.

|*CSS-URL (optional)*
|Aussehen des ExperCash-Iframe mit Hilfe einer CSS-Datei anpassen. Beachten Sie, dass es sich hierbei vorzugsweise um eine URL mit https-Protokoll handelt.

|*Profile-ID*
|Ziffer des Profils eingeben. Im Zweifelsfall die *1* eingeben. Da mindestens ein Profil vorhanden sein muss, ist dieser Wert meistens zutreffend.

2+|Mandant (Shop)-Optionen

|*Zugangsdaten für alle Mandanten (Shops) aktivieren*
|Nur sichtbar, wenn Mandanten eingerichtet sind. Aktivieren, um die Kontoeinstellungen, die über *Konto hinzufügen* für den Hauptshop gespeichert wurden, für alle Mandanten (Shops) zu übernehmen, unabhängig davon, was für andere Mandanten gespeichert wurde. Deaktivieren, um separate Zugangsdaten für weitere Mandanten (Shops) zu verwenden. Webshops, für die kein Konto hinzugefügt wurde, können mit ExperCash nicht genutzt werden. +
Zur Unterstützung mehrerer Mandanten muss im Menü <<webshop/webshop-einrichten#grundeinstellungen, System » Mandant » Mandant wählen » Webshop » Einstellungen>> für die Option *Login* die Einstellung *Login in jedem einzelnen Shop ermöglichen* aktiviert sein.
|====

[#80]
== Zahlungsart aktivieren

Richten Sie die <<payment/zahlungsarten-verwalten#20, Zahlungsarten>> für ExperCash im Tab *Einstellungen* der Zahlungsarten ein. Prüfen Sie zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.
