= Alter Webshop: heidelpay
:lang: de
include::{includedir}/_header.adoc[]
:keywords: heidelpay, Zahlungsart
:description: Payment in plentymarkets: Richte die Schnittstelle zu heidelpay in deinem plentymarkets System ein.
:position: 100
:url: payment/zahlungsanbieter/heidelpay

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *heidelpay* für Callisto Shops. Für die Verwendung von *heidelpay* in Ceres Shops erhältst du in der Beschreibung des Plugins im link:https://marketplace.plentymarkets.com/plugins/payment/Heidelpay_5700[plentyMarketplace^].
====

Die Heidelberger Payment GmbH, kurz heidelpay, ist ein führender europäischer Service-Provider rund um das Thema Payment. Das Leistungsspektrum des PCI/DSS-zertifizierten Unternehmens reicht von weltweiten E-Payment-Lösungen über Debitorenmanagement und Riskmanagement-Funktionen bis hin zu einem breiten Angebot alternativer Bezahlverfahren - schnell, sicher, einfach und umfassend.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhältst du wichtige Hinweise zur Integration des Zahlungsanbieters in plentymarkets.

[#20]
=== Bezahlvorgang

Für den Bezahlvorgang wird der Kunde zu heidelpay weitergeleitet und dort über ein iframe dazu aufgefordert, seine notwendigen Daten einzugeben. Die Auswahl der Zahlungsart erfolgt noch im Webshop. Anschließend wird der Kunde direkt zu heidelpay weitergeleitet. Die weiteren Inhalte werden in einem iframe bereitgestellt. Der Kunde gibt hier seine Daten ein. Dies erfolgt somit nicht im Webshop, sondern bei heidelpay. Nach der Eingabe und Bestätigung der Daten wird der Kunde auf die Bestellbestätigungsseite geleitet.

[#30]
=== SSL-Zertifikat

Für die korrekte Verwendung der Zahlungsart ist ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>> erforderlich.

[WARNING]
.Frage bei deiner Bank nach
====
Kläre vor einer Integration der Zahlungsart *heidelpay*, ob deine Bank die Abwicklung über iframes unterstützt.
====

[#40]
=== Verfügbare heidelpay-Zahlungsarten

Nachfolgend findest du eine Übersicht der für plentymarkets verfügbaren heidelpay-Zahlungsarten mit der System-ID in Klammern.

* Online-Lastschrift (1000)
* Vorkasse (1020)
* Rechnung (1030)
* Kreditkarten (1040)
* EC-Karten (1050)
* Banküberweisung mit PIN/TAN (1060)
* Virtual Account (1070)
* User Account (1080)
* Sofortüberweisung (1090)
* T-Pay (1091)
* Giropay (1092)
* IDEAL (NL) (1093)
* EPS (AT) (1094)
* Carte Bleue (1095)

[#50]
== Bei heidelpay registrieren

Kontaktiere das heidelpay-Vertriebsteam unter Tel. 06221-6517020 oder link:mailto:sales@heidelpay.de[sales@heidelpay.de] und bitte um ein Angebot. Unterschreibe das Angebot und sende es zurück an heidelpay. Du erhältst dann einen Kreditkartenakzeptanzvertrag von heidelpay zur Unterschrift. Nach Freigabe durch die Bank erhältst du die Zugangsdaten von heidelpay. Die Zugangsdaten benötigst du für die Aktivierung in plentymarkets.

[#60]
== heidelpay in Callisto einrichten

Gehe wie unten beschrieben vor, um die Schnittstelle zu heidelpay für deinen Callisto Shop in plentymarkets einzurichten. Zusätzlich steht für heidelpay das Untermenü <<payment/zahlungsanbieter/heidelpay#80, Optionen>> zur Verfügung, wo du z.B. ein Stylesheet (CSS) hinterlegst.

[.instruction]
Schnittstelle zu heidelpay einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
. Klickeauf *heidelpay*. +
→ Das Tab *Schnittstelle* wird geöffnet.
. Klappe dem Mandanten auf.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-heidelpay>>.
. *Speichere* die Einstellungen.

[[tabelle-schnittstelleneinrichtung-heidelpay]]
.Schnittstelle zu heidelpay einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Login-Daten

|*Benutzername*
|32-stelligen Login-Code eingeben, wie von heidelpay erhalten.

|*Passwort*
|8-stelliges Passwort eingeben, wie von heidelpay erhalten.

|*SENDER*
|32-stelligen Code eingeben, wie von heidelpay erhalten.

|*Channel*
|32-stelligen Code eingeben, wie von heidelpay erhalten.

|*Transaction Mode*
|*LIVE* eingeben.

|*Server*
|URL des Payment-Servers  eingeben, wie von heidelpay erhalten. +
Payment-URL *POST* (UTF-8 codiert) eingeben.

2+|Online-Überweisungs-Zahlungsarten: Channel-ID

|*Sofortüberweisung, T-Pay, Giropay, IDEAL, EPS*
|Channel-IDs der Zahlungsarten eingeben.

2+|Mandant (Shop)-Optionen

|*Zugangsdaten für alle Mandanten (Shops) aktivieren*
|Nur sichtbar, wenn Mandanten eingerichtet sind. Aktivieren, um die Kontoeinstellungen, die über *Konto hinzufügen* für den Hauptshop gespeichert wurden, für alle Mandanten (Shops) zu übernehmen, unabhängig davon, was für andere Mandanten gespeichert wurde. Deaktivieren, um separate Zugangsdaten für weitere Mandanten (Shops) zu verwenden. Webshops, für die kein Konto hinzugefügt wurde, können mit heidelpay nicht genutzt werden. +
Zur Unterstützung mehrerer Mandanten muss im Menü <<webshop/webshop-einrichten#grundeinstellungen, Einrichtung » Mandant » Mandant wählen » Webshop » Einstellungen>> für die Option *Login* die Einstellung *Login in jedem einzelnen Shop ermöglichen* aktiviert sein.
|====

[#70]
== Zahlungsarten aktivieren

Für heidelpay steht dir eine Vielzahl von Zahlungsarten zur Verfügung, die du im Menü <<payment/zahlungsarten-verwalten#20, Einrichtung » Aufträge » Zahlung » Zahlungsarten>> aktivierst. Prüfe zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#80]
== heidelpay im Callisto Webshop anzeigen

Im Untermenü *Optionen* hast du die Möglichkeit, ein Stylesheet und ein Banner sowie einen Frontend-Link einzurichten.

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
. Klicke auf *heidelpay*. +
→ Das Tab *Schnittstelle* wird geöffnet.
. Klappe den Bereich *Optionen* auf.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-optionen-heidelpay>>.
. *Speichere* die Einstellungen.

[[tabelle-optionen-heidelpay]]
.Optionen für heidelpay
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Stylesheet und Banner

|*Aktive Stylesheet-Datei*
|Hier wird ein *Vorschau-Symbol* zur Ansicht der hochgeladenen Stylesheet-Datei angezeigt.

|*Stylesheet-Datei hochladen (CSS)*
|Auf *Durchsuchen...* klicken, um eine Datei hochzuladen. Die Datei wird nach dem Speichern der Einstellungen unter *Aktive Stylesheet-Datei* angezeigt. Es können nur Dateien im CSS-Format hochgeladen werden.

|*Aktive Banner-Datei*
|Hier wird ein *Vorschau-Symbol* zur Ansicht der hochgeladenen Banner-Datei angezeigt.

|*Banner-Datei hochladen (PNG)*
|Auf *Durchsuchen...* klicken, um eine Datei hochzuladen. Die Datei wird nach dem Speichern der Einstellungen unter *Aktive Banner-Datei* angezeigt. Es können nur Dateien im PNG-Format hochgeladen werden. Die maximale Bannergröße beträgt 570 x 40 Pixel.

2+|Link-Dokument

|*Link-Dokument auswählen*
|Dokument wählen, das nach Klick auf den Link angezeigt werden soll. Wenn ein Dokument verlinken werden soll, das nicht in der Auswahl vorhanden ist, die Option *Benutzerdefiniert* wählen.

|*Text "Benutzerdefiniert"*
|Benutzerdefinierte Link-Bezeichnung eingeben, wenn unter *Link-Dokument auswählen* die Option *Benutzerdefiniert* gewählt wurde. +
Die Textzeile kann auch verwendet werden, um nur den eingegebenen Text an der Linkposition anzeigen zu lassen, z.B. als Hinweistext.

|*Ausrichtung*
|*Links*, *Zentriert* oder *Rechts* wählen.

|*Aktive Link-Datei*
|Hier wird ein Vorschau-Symbol zur Ansicht der hochgeladenen Link-Datei angezeigt.

|*Link-Datei hochladen (HTML)*
|Auf *Durchsuchen...* klicken, um eine Datei hochzuladen. Die Datei wird nach dem Speichern der Einstellungen unter *Aktive Link-Datei* angezeigt. Es können nur Dateien im HTML-Format hochgeladen werden.

|*Popup-Fenster: Breite*
|Breite des Fensters in Pixeln eingeben.

|*Popup-Fenster: Höhe*
|Höhe des Fensters in Pixeln eingeben.
|====

[.subhead]
CSS-Stylesheet

Folgenden Beispiel-Code kannst du für das Stylesheet für heidelpay verwenden.

[source,plenty]
----
include::assets/EX-DE-heidelpay-CSS.html[]

----
