= Alter Webshop: Klarna Checkout UK
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Klarna Checkout UK, Zahlungsart
:description: Payment in plentymarkets: Richte die Schnittstelle zu Klarna Checkout UK in plentymarkets ein.
:position: 130
:url: payment/zahlungsanbieter/klarna-checkout-uk

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *Klarna Checkout UK* in Callisto Shops. Die folgenden Anleitungen sind somit nicht für Ceres Shops gültig!
====

Klarna Checkout UK heißt in plentymarkets die Checkout-Lösung, die von Klarna im Vereinigtem Königreich angeboten wird. Mit dieser Checkout-Lösung sind andere Lieferländer als mit dem von Klarna in Deutschland angebotenem Checkout möglich. Der Klarna Checkout UK ist responsive.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhältst du wichtige Hinweise zur Integration des Zahlungsanbieters *Klarna Checkout UK* in plentymarkets.

[IMPORTANT]
.Klarna Checkout und Webshop-Design
====
Beachte, dass für die erfolgreiche Integration von Klarna Checkout UK in plentymarkets folgende Bedingungen erfüllt sein müssen:

* Verwendung des Standard-Designs Callisto (ab Version 2)
* Nutzung des Individuellen Bestellvorgangs
* Sicherer Umgang mit dem plentymarkets CMS
* Erfahrung mit der Einrichtung von Zahlungsdienstleistern
====

[#20]
=== Bezahlvorgang mit Klarna Checkout UK

Der Bezahlvorgang verläuft wie folgt: Der Kunde gibt seine E-Mail-Adresse und die Postleitzahl der Rechnungsadresse im Klarna Checkout UK ein. Bei Klarna-Bestandskunden oder wenn ein Kunde im Shop eingeloggt ist, wird die Rechnungsadresse automatisch ausgefüllt. Der Kunde klickt auf Jetzt kaufen. In der Bestellbestätigung kann der Kunde optional die Zahlungsart wechseln, sich also für eine andere über Klarna Checkout UK verfügbare Zahlungsmethode entscheiden. Die Seite, die den Wechsel der Zahlungsart ermöglicht, wird komplett von Klarna gehostet. Der Kunde erhält die Rechnung von Klarna. Für den Kunden ist der Bestellvorgang damit abgeschlossen. In deinem plentymarkets System wird ein Auftrag angelegt.

[#30]
=== SSL-Zertifikat

Klarna Checkout UK wird über ein iFrame direkt in plentymarkets integriert. Daher ist für die Nutzung der Zahlungsart ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>> notwendig.

[#40]
=== Verknüpfte Zahlungsarten

Klarna Checkout UK verknüpft die folgenden Zahlungsarten:

* American Express
* Maestro
* VISA
* VISA electron
* MasterCard
* Zahlen nach Warenerhalt - der Endkunde kann per Debitkarte oder Überweisung zahlen
* Weitere <<payment/zahlungsanbieter/klarna-checkout-uk#80, externe Zahlungsarten>>

[#50]
== Bei Klarna registrieren

Bevor du Klarna Checkout UK in deinem plentymarkets System einrichtest, musst du dich bei link:https://www.klarna.com/uk/business/sell-online-with-klarna[Klarna^] registrieren.

[#60]
== Klarna Checkout UK in Callisto einrichten

Gehe wie unten beschrieben vor, um die Schnittstelle zu Klarna Checkout UK für deinen Callisto Shop in plentymarkets einzurichten.

[.instruction]
Schnittstelle zu Klarna Checkout UK einrichten:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Setze ein Häkchen bei *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
. Öffne den Ordner *Klarna*.
. Klicke auf *Klarna Checkout UK*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechsle in das Tab *Schnittstelle*.
. Klappe einen Mandanten auf.
. Nimm die Einstellungen vor. Beachte dabei die Erläuterungen in <<tabelle-schnittstelleneinrichtung-klarna-checkout-uk>>.
. *Speichere* die Einstellungen.

[[tabelle-schnittstelleneinrichtung-klarna-checkout-uk]]
.Schnittstelle zu Klarna Checkout UK einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Allgemeine Einstellungen

|*Betriebsmodus*
|*Live* = Modus für den produktiven Betrieb. +
*Test* = Modus für den Testbetrieb. Wenn du den Testmodus wählst, wird keine Auszahlung von Klarna an dich vorgenommen, da Klarna davon ausgeht, dass es sich um eine Testbestellung, mit der die Datenübertragung geprüft wird, handelt. Klarna erhebt auch keine Gebühren für Bestellungen im Testmodus.

|*Länderzuordnung*
|Lieferland wählen, das zunächst als Standard-Lieferland verwendet wird.

|*Externe Zahlungsanbieter anzeigen*
|Aktivieren, um externe Zahlungsanbieter zuzulassen. +
Folgende Zahlungsarten sind in Kombination mit Klarna Checkout UK zulässig: +
PayPal, Amazon Pay, Vorkasse, Giropay, Barzahlung, Lastschrift, Nachnahme +
Auf die Schreibweise der Zahlungsarten achten, da sie in plentymarkets mit genau diesen Namen angelegt werden müssen. Nur <<payment/zahlungsarten-verwalten#20, aktive Zahlungsarten>> werden berücksichtigt.

2+|Klarna-Identifizierung

|*Verkäufer-ID (Merchant-ID)*
|Verkäufer-ID eingeben, wie von Klarna erhalten.

|*Sicherheitsschlüssel (SharedSecret)*
|Sicherheitsschlüssel eingeben, wie von Klarna erhalten.

2+|Pflichtangaben

|*Geburtstdatum*, +
*Lieferadresse*, +
*Kundenanrede*
|Angaben aktivieren, die der Kunde während des Bestellvorgangs verpflichtend angeben soll.

2+|Individualisierung des Kassenbereichs

|*Farbe der Schaltflächen*, +
*Hintergrundfarbe der Kontrollkästchen*, +
*Textfarbe der Schaltflächen*, +
*Häckchenfarbe der Kontrollkästchen*, +
*Farbe der Links*, +
*Farbe der Kopfzeile*
|Hexadezimal-Code eingeben, um eine Farbe festzulegen. +
Achte darauf, dass die Textfarbe und Farbe der Schaltflächen nicht gleich sind, damit sich der Text vom Hintergrund abhebt. Das Gleiche gilt für die Häkchenfarbe und die Hintergrundfarbe der Kontrollkästchen.
|====

[#70]
== Zahlungsart aktivieren

Richte die <<payment/zahlungsarten-verwalten#20, Zahlungsart>> Klarna Checkout UK in deinem plentymarkets ein und aktiviere die Zahlungsart. Prüfe zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#80]
== Externe Zahlungsarten im Klarna Checkout UK erlauben

Du kannst deinen Kunden über den Klarna Checkout UK auch einige externe Zahlungsarten anbieten. Diese zusätzlichen Zahlungsarten kannst du jedoch nur in Absprache mit Klarna anbieten. Wende dich daher an Klarna, bevor du externe Zahlungsarten einrichtest.

Damit Klarna die zusätzlichen Zahlungsarten erkennt, muss als Name die unten angegebene Schreibweise genutzt werden. Außerdem müssen die Logos der externen Zahlungsanbieter der angegebenen Bildgröße exakt entsprechen. Die in plentymarkets gespeicherten Standard-Logos sind zu groß für den Klarna Checkout. +
Die Zahlungsarten und Bildgrößen sind:

* PayPal (276 x 48 px)
* Amazon Pay (276 x 48 px)
* Vorkasse (69 x 24 px)
* Giropay (69 x 24 px)
* Barzahlen (69 x 24 px)
* Lastschrift (69 x 24 px)
* Nachnahme (69 x 24 px)

Die Liste der möglichen externen Zahlungsarten im Klarna Checkout UK wird von Klarna immer wieder geändert und erweitert, daher stellt die Liste hier keine vollständige Liste dar.

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
. Öffne den Ordner *Klarna*.
. Klicke auf *Klarna Checkout UK*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechsle in das Tab *Schnittstelle*.
. Klappe den Mandanten auf.
. Aktiviere die Einstellung *Externe Zahlungsanbieter*.
. *Speichere* die Einstellung.

Richten die zusätzlich gewünschten <<payment/zahlungsarten-verwalten#20, Zahlungsarten>> im Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten* in deinem plentymarkets Backend ein und aktiviere die Zahlungsarten.

[#90]
== Klarna Checkout UK im Callisto Webshop anzeigen

Den Klarna Checkout UK fügst du mit dem Container *{% Container_CheckoutKlarnaPayment() %}* in dein Design ein. Du kannst die Funktion an einer geeigneten Stelle in ein Template oder in eine Kategorie des Typs Container einfügen. Nachfolgend wird beschrieben, wie du den Klarna Checkout UK anstelle des Bestellschritts Kasse im Standard-Design Callisto Light 3 anzeigst. Hierzu erstellst du eine neue Kategorie des Typs *Container* und ersetzt den Standardbestellschritt Kasse durch deine neue Kategorie.

[WARNING]
.Keine Anpassungen am aktiven Design vornehmen
====
Nimm keine Änderungen an deinem aktiven Design vor. Bevor du Änderungen an deinem Design vornimmst, lege eine Sicherungskopie an, damit du jederzeit wieder zum Ursprungszustand zurückgelangst.
====

[.instruction]
Kategorie des Typs Container erstellen:

. Öffne das Menü *Artikel » Kategorien*.
. Klicke auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Gib einen Namen ein, z.B. Klarna Checkout UK.
. Klicke auf *Erstellen*. +
→ Die Kategorie wird im Tab *Einstellungen* geöffnet.
. Wähle unter *Typ* die Option *Container*.
. Wechsle in das Tab *Beschreibung 1*.
. Füge den Container *{% Container_CheckoutKlarnaPayment() %}* in das Textfeld ein.
. *Speichere* die Einstellungen.

Nimm im Tab *Einstellungen* weitere Einstellungen, wie z.B. Mandant wählen, vor. Anschließend fügst du die Kategorie als Bestellschritt in deinen Bestellvorgang ein.

[.instruction]
Kategorie als Bestellschritt hinzufügen:

. Öffne das Menü *CMS » Webdesign*.
. Klicke auf *Einstellungen*. +
→ Das Fenster *Design-Einstellungen* wird geöffnet.
. Wechsle in das Tab *Mandanten*.
. Klicke auf einen Mandanten.
. Wechsle in das Tab *Bestellvorgang*.
. Klicke im *3. Bestellschritt* auf *Suchen*.
. Wähle die neu erstellte Kategorie *Klarna Checkout UK*.
. Klicke auf *Auswählen*.
. *Speichere* die Einstellungen. +
→ Der Bestellschritt wird hinzugefügt.

[#100]
== Versandbestätigungen automatisch senden

Damit Klarna UK über den Versand der Artikel, die Stornierung von Aufträgen und über Rückerstattungen informiert wird, erstellst du Ereignisaktionen. Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an Klarna zu senden. Häufig warten Zahlungsanbieter mit der Auszahlung des vom Kunden gezahlten Betrags bis zur Versandbesätigung durch den Händler, um so dem Endkunden einen gewissen Schutz zu bieten.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß Tabelle 2.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß Tabelle 2 vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an Klarna Checkout UK
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag* +
Lieferauftrag - optional für Teillieferungen

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*Klarna Checkout UK*

|*Aktion*
|*Versand &gt; Versandbestätigung an Klarna UK senden*
|
|====

[#110]
== Rückerstattung automatisch melden

Um dem Käufer den gesamten Betrag zu erstatten, lege einen Auftrag vom Typ *Retoure* an. Anschließend richtest du eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Rückerstattungen automatisch an Klarna UK zu senden. Weitere Details zum Anlegen von Retouren findest du auf der Handbuchseite <<auftraege/auftraege-verwalten#400, Retoure>>.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß Tabelle 3.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß Tabelle 3 vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--

.Ereignisaktion zum automatischen Senden von Rückerstattungen an Klarna Checkout UK
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*Klarna Checkout UK*

|*Aktion*
|*Zahlungsarten &gt; Rückerstattung an Klarna UK senden*
|
|====

[#120]
== Stornierung automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Stornierungen automatisch an Klarna UK zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß Tabelle 4.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß Tabelle 4 vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an Klarna Checkout UK
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für *stornierte Aufträge* wählen.

|*Filter*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*Klarna Checkout UK*

|*Aktion*
|*Zahlungsarten &gt; Stornierung an Klarna UK senden*
|
|====

[#130]
== Gutschrift melden

Bei Gutschriften handelt es sich meist um Teilbeträge des Auftragsvolumens. Um diesen Betrag zu melden, nutze den Auftragstyp *Gutschrift* und gib in diesem einen Betrag ein, den du dem Kunden erstatten möchtest. Da die Summe in deinem Ermessen liegt und für jeden Auftrag unterschiedlich ausfällt, müssen Teilbeträge manuell eingegeben werden. Eine Automatisierung ist nicht möglich.

[.instruction]
Gutschrift anlegen, um Teilbetrag zu erstatten und zu melden:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den Klarna Checkout UK-Auftrag. +
→ Das Tab *Übersicht* wird geöffnet.
. Wähle die Option *anlegen* aus der Dropdown-Liste *Gutschrift ...*. +
→ Die Gutschrift wird angelegt.
. Öffne die neu angelegte Gutschrift.
. Wechsle in das Tab *Einstellungen*.
. Klicke unter *Rückzahlung* auf *Klarna Checkout UK Refund*.
. Gib die Summe ein, die du erstatten möchtest.
. Klicke auf *Rückzahlung tätigen*. +
→ Die Summe wird automatisch an Klarna Checkout UK gesendet.

[#140]
== Zahlungsstatus nachvollziehen

Im Tab *Zahlung* eines Auftrags hast du die Möglichkeit, Zahlungen nachzuvollziehen. Die Bedeutung der einzelnen Einträge und wann ein Eintrag erfolgt, wird nachfolgend erläutert. Die Einträge beziehen sich auf das Tab *Zahlung* des Hauptauftrags.

[#150]
=== Statusabfolge bei Komplettversand

[.subhead]
bestätigt &gt; erhalten

Wenn von Klarna akzeptiert wurde, dass der Kunde über Klarna bezahlt, wird eine Zahlung angelegt. Diese Zahlung erhält den Status *bestätigt*. Du sendest dem Kunden alle Artikel und eine Versandbestätigung an Klarna. Nach Erhalt der Versandbestätigung erhältst du das Geld von Klarna. Die Zahlung erhält den Status *erhalten*.

[#160]
=== Statusabfolge bei Teilversand

[.subhead]
bestätigt &gt; tlw. erhalten &gt; erhalten

Wenn von Klarna akzeptiert wurde, dass der Kunde über Klarna bezahlt, wird eine Zahlung angelegt. Diese Zahlung erhält den Status *bestätigt*. Du sendest dem Kunden zunächst aber nur einen Teil seiner Bestellung. Du sendest z.B. von 5 bestellten Artikeln 3 Artikel sofort, weil du diese im Lager vorrätig hast.
Du legst für die 3 Artikel einen Lieferauftrag an und buchst den Warenausgang am Lieferauftrag. Wenn du für das automatische Senden der Versandbestätigung auch *Lieferauftrag* im Filter *Auftrag &gt; Auftragstyp* aktiviert hast, wird für den Lieferauftrag die Versandbestätigung an Klarna gesendet. Im Hauptauftrag wird dann eine weitere Zahlung angelegt, die den Status *erhalten* erhält. Der Status der ersten Zahlung wechselt von *bestätigt* in *tlw. erhalten*. Wenn du die verbliebenen Artikel über einen 2. Lieferauftrag abwickelst und in diesem der Warenausgang gebucht wird, wird eine 3. Zahlung im Hauptauftrag angelegt. Diese Zahlung erhält den Status *erhalten* und der Status der ersten Zahlung wechselt ebenfalls von *tlw. erhalten* auf *erhalten*. +
Es wird also pro versendetem Lieferauftrag eine Zahlung hinzugefügt und erst wenn der Auftrag vollständig versendet wurde, wechselt auch die erste Zahlung in den Status *erhalten*. +
Wenn du für den Versand von Lieferaufträgen keine Versandbestätigung an Klarna senden möchtest, aktivierst du den Auftragstyp *Lieferauftrag* nicht im Filter der Ereignisaktion.

[#170]
=== Statusabfolge bei Stornierung, Gutschrift oder Rückerstattung

Bei einer Stornierung wechselt im Tab *Zahlung* des Hauptauftrags die Zahlung in den Status *widerrufen*. +
Bei einer Gutschrift wird im Tab *Zahlung* des Hauptauftrags eine Zahlung, die den Status *tlw. erstattet* hat, angelegt. In der Gutschrift selbst wird auch eine Zahlung angelegt. Die Zahlung in der Gutschrift hat den Status *bestätigt*. +
Bei einer Rückerstattung wird im Tab *Zahlung* des Hauptauftrags eine Zahlung, die den Status *erstattet* hat, angelegt. In der Retoure selbst wird eine Zahlung, die den Status *bestätigt* hat, angelegt.
