= Alter Webshop: Klarna Checkout UK
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Klarna Checkout UK, Zahlungsart
:description: Payment in plentymarkets: Richten Sie die Schnittstelle zu Klarna Checkout UK in plentymarkets ein.
:position: 130

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *Klarna Checkout UK* in Callisto Shops. Die folgenden Anleitungen sind somit nicht für Ceres Shops gültig!
====

Klarna Checkout UK heißt in plentymarkets die Checkout-Lösung, die von Klarna im Vereinigtem Königreich angeboten wird. Mit dieser Checkout-Lösung sind andere Lieferländer als mit dem von Klarna in Deutschland angebotenem Checkout möglich. Der Klarna Checkout UK ist responsive.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhalten Sie wichtige Hinweise zur Integration des Zahlungsanbieters *Klarna Checkout UK* in plentymarkets.

[IMPORTANT]
.Klarna Checkout und Webshop-Design
====
Beachten Sie, dass für die erfolgreiche Integration von Klarna Checkout UK in plentymarkets folgende Bedingungen erfüllt sein müssen:

* Verwendung des Standard-Designs Callisto (ab Version 2)
* Nutzung des Individuellen Bestellvorgangs
* Sicherer Umgang mit dem plentymarkets CMS
* Erfahrung mit der Einrichtung von Zahlungsdienstleistern
====

[#20]
=== Bezahlvorgang mit Klarna Checkout UK

Der Bezahlvorgang verläuft wie folgt: Der Kunde gibt seine E-Mail-Adresse und die Postleitzahl der Rechnungsadresse im Klarna Checkout UK ein. Bei Klarna-Bestandskunden oder wenn ein Kunde im Shop eingeloggt ist, wird die Rechnungsadresse automatisch ausgefüllt. Der Kunde klickt auf Jetzt kaufen. In der Bestellbestätigung kann der Kunde optional die Zahlungsart wechseln, sich also für eine andere über Klarna Checkout UK verfügbare Zahlungsmethode entscheiden. Die Seite, die den Wechsel der Zahlungsart ermöglicht, wird komplett von Klarna gehostet. Der Kunde erhält die Rechnung von Klarna. Für den Kunden ist der Bestellvorgang damit abgeschlossen. In Ihrem plentymarkets System wird ein Auftrag angelegt.

[#30]
=== SSL-Zertifikat

Klarna Checkout UK wird über ein iFrame direkt in plentymarkets integriert. Daher ist für die Nutzung der Zahlungsart ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>> notwendig.

[#40]
=== Verknüpfte Zahlungsarten

Klarna Checkout UK verknüpft die folgenden Zahlungsarten:

* American Express
* Maestro
* VISA
* VISA electron
* MasterCard
* Zahlen nach Warenerhalt - der Endkunde kann per Debitkarte oder Überweisung zahlen
* Weitere <<payment/zahlungsanbieter/klarna-checkout-uk#80, externe Zahlungsarten>>

[#50]
== Bei Klarna registrieren

Bevor Sie Klarna Checkout UK in Ihrem plentymarkets System einrichten, müssen Sie sich bei link:https://www.klarna.com/uk/business/sell-online-with-klarna[Klarna^] registrieren.

[#60]
== Klarna Checkout UK in Callisto einrichten

Gehen Sie wie unten beschrieben vor, um die Schnittstelle zu Klarna Checkout UK für Ihren Callisto Shop in plentymarkets einzurichten.

[.instruction]
Schnittstelle zu Klarna Checkout UK einrichten:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Setzen Sie ein Häkchen bei *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
. Öffnen Sie den Ordner *Klarna*.
. Klicken Sie auf *Klarna Checkout UK*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechseln Sie in das Tab *Schnittstelle*.
. Klappen Sie einen Mandanten auf.
. Nehmen Sie die Einstellungen vor. Beachten Sie dabei die Erläuterungen in <<tabelle-schnittstelleneinrichtung-klarna-checkout-uk>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelleneinrichtung-klarna-checkout-uk]]
.Schnittstelle zu Klarna Checkout UK einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

2+|Allgemeine Einstellungen

|*Betriebsmodus*
|*Live* = Modus für den produktiven Betrieb. +
*Test* = Modus für den Testbetrieb. Wenn Sie den Testmodus wählen, wird keine Auszahlung von Klarna an Sie vorgenommen, da Klarna davon ausgeht, dass es sich um eine Testbestellung, mit der die Datenübertragung geprüft wird, handelt. Klarna erhebt auch keine Gebühren für Bestellungen im Testmodus.

|*Länderzuordnung*
|Lieferland wählen, das zunächst als Standard-Lieferland verwendet wird.

|*Externe Zahlungsanbieter anzeigen*
|Aktivieren, um externe Zahlungsanbieter zuzulassen. +
Folgende Zahlungsarten sind in Kombination mit Klarna Checkout UK zulässig: +
PayPal, Amazon Pay, Vorkasse, Giropay, Barzahlung, Lastschrift, Nachnahme +
Auf die Schreibweise der Zahlungsarten achten, da sie in plentymarkets mit genau diesen Namen angelegt werden müssen. Nur <<payment/zahlungsarten-verwalten#20, aktive Zahlungsarten>> werden berücksichtigt.

2+|Klarna-Identifizierung

|*Verkäufer-ID (Merchant-ID)*
|Verkäufer-ID eingeben, wie von Klarna erhalten.

|*Sicherheitsschlüssel (SharedSecret)*
|Sicherheitsschlüssel eingeben, wie von Klarna erhalten.

2+|Pflichtangaben

|*Geburtstdatum*, +
*Lieferadresse*, +
*Kundenanrede*
|Angaben aktivieren, die der Kunde während des Bestellvorgangs verpflichtend angeben soll.

2+|Individualisierung des Kassenbereichs

|*Farbe der Schaltflächen*, +
*Hintergrundfarbe der Kontrollkästchen*, +
*Textfarbe der Schaltflächen*, +
*Häckchenfarbe der Kontrollkästchen*, +
*Farbe der Links*, +
*Farbe der Kopfzeile*
|Hexadezimal-Code eingeben, um eine Farbe festzulegen. +
Achten Sie darauf, dass die Textfarbe und Farbe der Schaltflächen nicht gleich sind, damit sich der Text vom Hintergrund abhebt. Das Gleiche gilt für die Häkchenfarbe und die Hintergrundfarbe der Kontrollkästchen.
|====

[#70]
== Zahlungsart aktivieren

Richten Sie die <<payment/zahlungsarten-verwalten#20, Zahlungsart>> Klarna Checkout UK in Ihrem plentymarkets ein und aktivieren Sie die Zahlungsart. Prüfen Sie zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#80]
== Externe Zahlungsarten im Klarna Checkout UK erlauben

Sie können Ihren Kunden über den Klarna Checkout UK auch einige externe Zahlungsarten anbieten. Diese zusätzlichen Zahlungsarten können Sie jedoch nur in Absprache mit Klarna anbieten. Wenden Sie sich daher an Klarna, bevor Sie externe Zahlungsarten einrichten.

Damit Klarna die zusätzlichen Zahlungsarten erkennt, muss als Name die unten angegebene Schreibweise genutzt werden. Außerdem müssen die Logos der externen Zahlungsanbieter der angegebenen Bildgröße exakt entsprechen. Die in plentymarkets gespeicherten Standard-Logos sind zu groß für den Klarna Checkout. +
Die Zahlungsarten und Bildgrößen sind:

* PayPal (276 x 48 px)
* Amazon Pay (276 x 48 px)
* Vorkasse (69 x 24 px)
* Giropay (69 x 24 px)
* Barzahlen (69 x 24 px)
* Lastschrift (69 x 24 px)
* Nachnahme (69 x 24 px)

Die Liste der möglichen externen Zahlungsarten im Klarna Checkout UK wird von Klarna immer wieder geändert und erweitert, daher stellt die Liste hier keine vollständige Liste dar.

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
.  Öffnen Sie den Ordner *Klarna*.
. Klicken Sie auf *Klarna Checkout UK*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechseln Sie in das Tab *Schnittstelle*.
.  Klappen Sie den Mandanten auf.
. Aktivieren Sie die Einstellung *Externe Zahlungsanbieter*.
. *Speichern* Sie die Einstellung.

Richten Sie die zusätzlich gewünschten <<payment/zahlungsarten-verwalten#20, Zahlungsarten>> im Menü *System » Aufträge » Zahlung » Zahlungsarten* in Ihrem plentymarkets ein und aktivieren Sie die Zahlungsarten.

[#90]
== Klarna Checkout UK im Callisto Webshop anzeigen

Den Klarna Checkout UK fügen Sie mit dem Container *{% Container_CheckoutKlarnaPayment() %}* in Ihr Design ein. Sie können die Funktion an einer geeigneten Stelle in ein Template oder in eine Kategorie des Typs Container einfügen. Nachfolgend wird beschrieben, wie Sie den Klarna Checkout UK anstelle des Bestellschritts Kasse im Standard-Design Callisto Light 3 anzeigen. Hierzu erstellen Sie eine neue Kategorie des Typs *Container* und ersetzen den Standardbestellschritt Kasse durch Ihre neue Kategorie.

[WARNING]
.Keine Anpassungen am aktiven Design vornehmen
====
Nehmen Sie keine Änderungen an Ihrem aktiven Design vor. Bevor Sie Änderungen an Ihrem Design vornehmen, legen Sie eine Sicherungskopie an, damit Sie jederzeit wieder zum Ursprungszustand zurückgelangen.
====

[.instruction]
Kategorie des Typs Container erstellen:

. Öffnen Sie das Menü *Artikel » Kategorien*.
. Klicken Sie auf *Neue Kategorie*. +
→
Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Geben Sie einen Namen ein, z.B. Klarna Checkout UK.
. Klicken Sie auf *Erstellen*. +
→ Die Kategorie wird im Tab *Einstellungen* geöffnet.
. Wählen Sie unter *Typ* die Option *Container*.
. Wechseln Sie in das Tab *Beschreibung 1*.
. Fügen Sie den Container *{% Container_CheckoutKlarnaPayment() %}* in das Textfeld ein.
. *Speichern* Sie die Einstellungen.

Nehmen Sie im Tab *Einstellungen* weitere Einstellungen, wie z.B. Mandant wählen, vor. Anschließend fügen Sie die Kategorie als Bestellschritt in Ihren Bestellvorgang ein.

[.instruction]
Kategorie als Bestellschritt hinzufügen:

. Öffnen Sie das Menü *CMS » Webdesign*.
. Klicken Sie auf *Einstellungen*. +
→
Das Fenster *Design-Einstellungen* wird geöffnet.
. Wechseln Sie in das Tab *Mandanten*.
. Klicken Sie auf einen Mandanten.
. Wechseln Sie in das Tab *Bestellvorgang*.
. Klicken Sie im *3. Bestellschritt* auf *Suchen*.
. Wählen Sie die neu erstellte Kategorie *Klarna Checkout UK*.
. Klicken Sie auf *Auswählen*.
. *Speichern* Sie die Einstellungen. +
→
Der Bestellschritt wird hinzugefügt.

[#100]
== Versandbestätigungen automatisch senden

Damit Klarna UK über den Versand der Artikel, die Stornierung von Aufträgen und über Rückerstattungen informiert wird, erstellen Sie Ereignisaktionen. Richten Sie eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an Klarna zu senden. Häufig warten Zahlungsanbieter mit der Auszahlung des vom Kunden gezahlten Betrags bis zur Versandbesätigung durch den Händler, um so dem Endkunden einen gewissen Schutz zu bieten.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das *Ereignis* gemäß Tabelle 2.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß Tabelle 2 vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an Klarna Checkout UK
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag* +
Lieferauftrag - optional für Teillieferungen

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*Klarna Checkout UK*

|*Aktion*
|*Versand &gt; Versandbestätigung an Klarna UK senden*
|
|====

[#110]
== Rückerstattung automatisch melden

Um dem Käufer den gesamten Betrag zu erstatten, legen Sie einen Auftrag vom Typ *Retoure* an. Anschließend richten Sie eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Rückerstattungen automatisch an Klarna UK zu senden. Weitere Details zum Anlegen von Retouren finden Sie auf der Handbuchseite <<auftraege/auftraege-verwalten#retoure, Retoure>>.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das *Ereignis* gemäß Tabelle 3.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß Tabelle 3 vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

.Ereignisaktion zum automatischen Senden von Rückerstattungen an Klarna Checkout UK
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure*
|

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*Klarna Checkout UK*

|*Aktion*
|*Zahlungsarten &gt; Rückerstattung an Klarna UK senden*
|
|====

[#120]
== Stornierung automatisch senden

Richten Sie eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Stornierungen automatisch an Klarna UK zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das *Ereignis* gemäß Tabelle 4.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß Tabelle 4 vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an Klarna Checkout UK
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für *stornierte Aufträge* wählen.

|*Filter*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*Klarna Checkout UK*

|*Aktion*
|*Zahlungsarten &gt; Stornierung an Klarna UK senden*
|
|====

[#130]
== Gutschrift melden

Bei Gutschriften handelt es sich meist um Teilbeträge des Auftragsvolumens. Um diesen Betrag zu melden, nutzen Sie den Auftragstyp *Gutschrift* und geben in diesem einen Betrag ein, den Sie dem Kunden erstatten möchten. Da die Summe in Ihrem Ermessen liegt und für jeden Auftrag unterschiedlich ausfällt, müssen Teilbeträge manuell eingegeben werden. Eine Automatisierung ist nicht möglich.

[.instruction]
Gutschrift anlegen, um Teilbetrag zu erstatten und zu melden:

. Öffnen Sie das Menü *Aufträge » Aufträge bearbeiten*.
. Öffnen Sie den Klarna Checkout UK-Auftrag. +
→ Das Tab *Übersicht* wird geöffnet.
. Wählen Sie die Option *anlegen* aus der Dropdown-Liste *Gutschrift ...*. +
→ Die Gutschrift wird angelegt.
. Öffnen Sie die neu angelegte Gutschrift.
. Wechseln Sie in das Tab *Einstellungen*.
. Klicken Sie unter *Rückzahlung* auf *Klarna Checkout UK Refund*.
. Geben Sie die Summe ein, die Sie erstatten möchten.
. Klicken Sie auf *Rückzahlung tätigen*. +
→ Die Summe wird automatisch an Klarna Checkout UK gesendet.

[#140]
== Zahlungsstatus nachvollziehen

Im Tab *Zahlung* eines Auftrags haben Sie die Möglichkeit Zahlungen nachzuvollziehen. Die Bedeutung der einzelnen Einträge und wann ein Eintrag erfolgt, wird nachfolgend erläutert. Die Einträge beziehen sich auf das Tab *Zahlung* des Hauptauftrags.

[#150]
=== Statusabfolge bei Komplettversand

[.subhead]
bestätigt &gt; erhalten

Wenn von Klarna akzeptiert wurde, dass der Kunde über Klarna bezahlt, wird eine Zahlung angelegt. Diese Zahlung erhält den Status *bestätigt*. Sie senden dem Kunden alle Artikel und eine Versandbestätigung an Klarna. Nach Erhalt der Versandbestätigung erhalten Sie das Geld von Klarna. Die Zahlung erhält den Status *erhalten*.

[#160]
=== Statusabfolge bei Teilversand

[.subhead]
bestätigt &gt; tlw. erhalten &gt; erhalten

Wenn von Klarna akzeptiert wurde, dass der Kunde über Klarna bezahlt, wird eine Zahlung angelegt. Diese Zahlung erhält den Status *bestätigt*. Sie senden dem Kunden zunächst aber nur einen Teil seiner Bestellung. Sie senden z.B. von 5 bestellten Artikeln 3 Artikel sofort, weil Sie diese auf Lager haben. Sie legen für die 3 Artikel einen Lieferauftrag an und buchen den Warenausgang am Lieferauftrag. Wenn Sie für das automatische Senden der Versandbestätigung auch *Lieferauftrag* im Filter *Auftrag &gt; Auftragstyp* aktiviert haben, wird für den Lieferauftrag die Versandbestätigung an Klarna gesendet. Im Hauptauftrag wird dann eine weitere Zahlung angelegt, die den Status *erhalten* erhält. Der Status der ersten Zahlung wechselt von *bestätigt* in *tlw. erhalten*. Wenn Sie die verbliebenen Artikel über einen 2. Lieferauftrag abwickeln und in diesem der Warenausgang gebucht wird, wird eine 3. Zahlung im Hauptauftrag angelegt. Diese Zahlung erhält den Status *erhalten* und der Status der ersten Zahlung wechselt ebenfalls von *tlw. erhalten* auf *erhalten*. +
Es wird also pro versendetem Lieferauftrag eine Zahlung hinzugefügt und erst wenn der Auftrag vollständig versendet wurde, wechselt auch die erste Zahlung in den Status *erhalten*. +
Wenn Sie für den Versand von Lieferaufträgen keine Versandbestätigung an Klarna senden möchten, aktivieren Sie den Auftragstyp *Lieferauftrag* nicht im Filter der Ereignisaktion.

[#170]
=== Statusabfolge bei Stornierung, Gutschrift oder Rückerstattung

Bei einer Stornierung wechselt im Tab *Zahlung* des Hauptauftrags die Zahlung in den Status *widerrufen*. +
Bei einer Gutschrift wird im Tab *Zahlung* des Hauptauftrags eine Zahlung, die den Status *tlw. erstattet* hat, angelegt. In der Gutschrift selbst wird auch eine Zahlung angelegt. Die Zahlung in der Gutschrift hat den Status *bestätigt*. +
Bei einer Rückerstattung wird im Tab *Zahlung* des Hauptauftrags eine Zahlung, die den Status *erstattet* hat, angelegt. In der Retoure selbst wird eine Zahlung, die den Status *bestätigt* hat, angelegt.
