= Alter Webshop: Masterpayment
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Masterpayment, Zahlungsart
:description: Payment in plentymarkets: Richten Sie die Schnittstelle zu Masterpayment in Ihrem plentymarkets System ein.
:position: 140

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *Masterpayment* für Callisto Shops. Für die Verwendung von *Masterpayment* in Ceres Shops erhalten Sie ausführliche Informationen in der Beschreibung des Plugins im link:https://marketplace.plentymarkets.com/plugins/payment/Masterpayment_4875[plentyMarketplace^].
====

Masterpayment bietet als führender Zahlungsanbieter verschiedene Payment-Lösungen wie Rechnungskauf, Ratenzahlung oder Anzahlungskauf und Finanzierungskauf. Ihre Kunden sind damit in der Lage, Zahlungen bequem über alle gängigen Zahlmethoden wie Kreditkarte, Lastschrift, Rechnungskauf oder eine Finanzierung zu leisten. Endkunden können ganz einfach bezahlen, ohne sich anmelden zu müssen.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhalten Sie wichtige Hinweise zur Integration des Zahlungsanbieters *Masterpayment* in plentymarkets.

[#20]
=== Bezahlvorgang

Für den Bezahlvorgang wird der Kunde zu Masterpayment weitergeleitet und dort über ein iframe aufgefordert, seine Daten einzugeben. Die Auswahl der Zahlungsart erfolgt noch im Webshop. Anschließend wird der Kunde direkt zu Masterpayment weitergeleitet. Die weiteren Inhalte werden in einem iframe bereitgestellt. Der Kunde gibt hier seine Daten ein. Dies erfolgt nicht im Webshop, sondern bei Masterpayment. Nach der Eingabe und Bestätigung der Daten wird der Kunde auf die Bestellbestätigungsseite geleitet.

[#30]
=== SSL-Zertifikat

Für die korrekte Verwendung der Zahlungsart *Masterpayment* ist ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>> erforderlich.

[WARNING]
.Fragen Sie Ihre Bank
====
Klären Sie vor einer Integration der Zahlungsart, ob Ihre Bank die Abwicklung über iframes unterstützt.
====

[#40]
=== Verfügbare Masterpayment-Zahlungsarten

Nachfolgend finden Sie eine Übersicht der für plentymarkets verfügbaren Masterpayment-Zahlungsarten mit der System-ID in Klammern.

* Debitkarte (1623)
* Finanzierung (1622)
* Kreditkarte (1600)
* Wiederkehrende Kreditkarte (1624)
* Online-Lastschrift (1610)
* Wiederkehrende Online-Lastschrift (1625)
* Ratenzahlung (1621)
* Rechnungskauf (1620)
* Anzahlungskauf (1626)
* SOFORT Überweisung (1627)

[#50]
== Bei Masterpayment registrieren

Um Masterpayment nutzen zu können, ist eine link:https://www.masterpayment.com/de/auth/register[Registrierung^] nötig. Sie erhalten die Zugangsdaten, die Sie für die Einrichtung von Masterpayment in plentymarkets benötigen.

[#60]
== Masterpayment in Callisto einrichten

Gehen Sie wie unten beschrieben vor, um die Schnittstelle zu Masterpayment für Ihren Callisto Shop in plentymarkets einzurichten.

[.instruction]
Schnittstelle zu Masterpayment einrichten:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
.  Klicken Sie auf *Masterpayment*. +
→ Das Tab *Schnittstelle* wird geöffnet.
.  Klappen Sie den Mandanten auf.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-masterpayment>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelleneinrichtung-masterpayment]]
.Schnittstelle zu Masterpayment einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Login (E-Mail), Secret Key*
|Zugangsdaten eingeben, wie von Masterpayment erhalten.

|*Kundendaten senden*
|Wählen, ob die Kundendaten gesendet werden sollen oder nicht.

|*IFrame-Breite*
|Breite in Pixeln eingeben (Standard: 450).

|*IFrame-Höhe*
|Höhe in Pixeln eingeben (Standard: 450).

2+|Mandant (Shop)-Optionen

|*Zugangsdaten für alle Mandanten (Shops) aktivieren*
|Nur sichtbar, wenn Mandanten eingerichtet sind. Aktivieren, um die Kontoeinstellungen, die über *Konto hinzufügen* für den Hauptshop gespeichert wurden, für alle Mandanten (Shops) zu übernehmen, unabhängig davon, was für andere Mandanten gespeichert wurde. Deaktivieren, um separate Zugangsdaten für weitere Mandanten (Shops) zu verwenden. Webshops, für die kein Konto hinzugefügt wurde, können mit Masterpayment nicht genutzt werden. +
Zur Unterstützung mehrerer Mandanten muss im Menü <<omni-channel/online-shop/webshop-einrichten#grundeinstellungen, System » Mandant » Mandant wählen » Webshop » Einstellungen>> für die Option *Login* die Einstellung *Login in jedem einzelnen Shop ermöglichen* aktiviert sein.
|====

[#70]
== Zahlungsart aktivieren

Richten Sie die <<payment/zahlungsarten-verwalten#20, Zahlungsart>> Masterpayment im Tab *Einstellungen* der Zahlungsart ein. Prüfen Sie zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#80]
== Versandbestätigungen automatisch senden

Damit Masterpayment über den Versand der Artikel, die Stornierung von Aufträgen und Retouren informiert wird und die Rechnung erstellt bzw. gelöscht wird, erstellen Sie Ereignisaktionen. Setzen Sie sich vor Live-Schaltung mit Ihrem Ansprechpartner bei Masterpayment in Verbindung, um die Ereignisaktionen zu testen. Richten Sie eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an Masterpayment zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das *Ereignis* gemäß Tabelle 2.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß Tabelle 2 vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an Masterpayment
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*Masterpayment*

|*Aktion*
|*Versand &gt; Versandbestätigung an Masterpayment senden*
|
|====

Alternativ wählen Sie als Ereignis die Einstellung *Statuswechsel* und dann den gewünschten *Status*, um den Versand durch einen Statuswechsel zu buchen.

[TIP]
.Tipp
====
Mit dieser Versandbestätigung erfährt Masterpayment, dass die Bestellung versendet ist. Dies aktiviert die Rechnung, die als PDF-Datei im Auftrag hinterlegt wird. Wenn Sie die Rechnung früher benötigen, stellen Sie ein früheres Ereignis ein.
====

[#90]
== Stornierungen automatisch senden

Richten Sie eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Stornierungen automatisch an Masterpayment zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Geben Sie einen Namen ein.
. Wählen Sie das *Ereignis* gemäß Tabelle 3.
. *Speichern* Sie die Einstellungen.
. Nehmen Sie die Einstellungen gemäß Tabelle 3 vor.
. Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an Masterpayment
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für *stornierte Aufträge* wählen.

|*Filter*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*Masterpayment*

|*Aktion*
|*Zahlungsarten &gt; Rückzahlung an Masterpayment senden*
|
|====
