= Alter Webshop: Masterpayment
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Masterpayment, Zahlungsart
:description: Payment in plentymarkets: Richten die Schnittstelle zu Masterpayment in deinem plentymarkets System ein.
:position: 140
:url: payment/zahlungsanbieter/masterpayment

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *Masterpayment* für Callisto Shops. Für die Verwendung von *Masterpayment* in Ceres Shops erhältst du ausführliche Informationen in der Beschreibung des Plugins im link:https://marketplace.plentymarkets.com/plugins/payment/Masterpayment_4875[plentyMarketplace^].
====

Masterpayment bietet als führender Zahlungsanbieter verschiedene Payment-Lösungen wie Rechnungskauf, Ratenzahlung oder Anzahlungskauf und Finanzierungskauf. Deine Kunden sind damit in der Lage, Zahlungen bequem über alle gängigen Zahlmethoden wie Kreditkarte, Lastschrift, Rechnungskauf oder eine Finanzierung zu leisten. Endkunden können ganz einfach bezahlen, ohne sich anmelden zu müssen.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhältst du wichtige Hinweise zur Integration des Zahlungsanbieters *Masterpayment* in plentymarkets.

[#20]
=== Bezahlvorgang

Für den Bezahlvorgang wird der Kunde zu Masterpayment weitergeleitet und dort über ein iframe aufgefordert, seine Daten einzugeben. Die Auswahl der Zahlungsart erfolgt noch im Webshop. Anschließend wird der Kunde direkt zu Masterpayment weitergeleitet. Die weiteren Inhalte werden in einem iframe bereitgestellt. Der Kunde gibt hier seine Daten ein. Dies erfolgt nicht im Webshop, sondern bei Masterpayment. Nach der Eingabe und Bestätigung der Daten wird der Kunde auf die Bestellbestätigungsseite geleitet.

[#30]
=== SSL-Zertifikat

Für die korrekte Verwendung der Zahlungsart *Masterpayment* ist ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>> erforderlich.

[WARNING]
.Fragen bei deiner Bank nach
====
Kläre vor einer Integration der Zahlungsart, ob deine Bank die Abwicklung über iframes unterstützt.
====

[#40]
=== Verfügbare Masterpayment-Zahlungsarten

Nachfolgend findest du eine Übersicht der für plentymarkets verfügbaren Masterpayment-Zahlungsarten inklusive der System-ID.

* Debitkarte (1623)
* Finanzierung (1622)
* Kreditkarte (1600)
* Wiederkehrende Kreditkarte (1624)
* Online-Lastschrift (1610)
* Wiederkehrende Online-Lastschrift (1625)
* Ratenzahlung (1621)
* Rechnungskauf (1620)
* Anzahlungskauf (1626)
* SOFORT Überweisung (1627)

[#50]
== Bei Masterpayment registrieren

Um Masterpayment nutzen zu können, ist eine link:https://www.masterpayment.com/de/auth/register[Registrierung^] nötig. Du erhältst die Zugangsdaten, die du für die Einrichtung von Masterpayment in plentymarkets benötigst.

[#60]
== Masterpayment in Callisto einrichten

Gehe wie unten beschrieben vor, um die Schnittstelle zu Masterpayment für deinen Callisto Shop in plentymarkets einzurichten.

[.instruction]
Schnittstelle zu Masterpayment einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
. Klicke auf *Masterpayment*. +
→ Das Tab *Schnittstelle* wird geöffnet.
. Klappe den Mandanten auf.
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-masterpayment>>.
. *Speichere* die Einstellungen.

[[tabelle-schnittstelleneinrichtung-masterpayment]]
.Schnittstelle zu Masterpayment einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Login (E-Mail), Secret Key*
|Zugangsdaten eingeben, wie von Masterpayment erhalten.

|*Kundendaten senden*
|Wählen, ob die Kundendaten gesendet werden sollen oder nicht.

|*IFrame-Breite*
|Breite in Pixeln eingeben (Standard: 450).

|*IFrame-Höhe*
|Höhe in Pixeln eingeben (Standard: 450).

2+|Mandant (Shop)-Optionen

|*Zugangsdaten für alle Mandanten (Shops) aktivieren*
|Nur sichtbar, wenn Mandanten eingerichtet sind. Aktivieren, um die Kontoeinstellungen, die über *Konto hinzufügen* für den Hauptshop gespeichert wurden, für alle Mandanten (Shops) zu übernehmen, unabhängig davon, was für andere Mandanten gespeichert wurde. Deaktivieren, um separate Zugangsdaten für weitere Mandanten (Shops) zu verwenden. Webshops, für die kein Konto hinzugefügt wurde, können mit Masterpayment nicht genutzt werden. +
Zur Unterstützung mehrerer Mandanten muss im Menü <<webshop/webshop-einrichten#grundeinstellungen, Einrichtung » Mandant » Mandant wählen » Webshop » Einstellungen>> für die Option *Login* die Einstellung *Login in jedem einzelnen Shop ermöglichen* aktiviert sein.
|====

[#70]
== Zahlungsart aktivieren

Richte die <<payment/zahlungsarten-verwalten#20, Zahlungsart>> Masterpayment im Tab *Einstellungen* der Zahlungsart ein. Prüfe zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#80]
== Versandbestätigungen automatisch senden

Damit Masterpayment über den Versand der Artikel, die Stornierung von Aufträgen und Retouren informiert wird und die Rechnung erstellt bzw. gelöscht wird, erstellst du Ereignisaktionen. Setze sich vor Live-Schaltung mit deinem Ansprechpartner bei Masterpayment in Verbindung, um die Ereignisaktionen zu testen. Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch an Masterpayment zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gibe einen Namen ein.
. Wähle das *Ereignis* gemäß Tabelle 2.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß Tabelle 2 vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an Masterpayment
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*Masterpayment*

|*Aktion*
|*Versand &gt; Versandbestätigung an Masterpayment senden*
|
|====

Alternativ wählst du als Ereignis die Einstellung *Statuswechsel* und dann den gewünschten *Status*, um den Versand durch einen Statuswechsel zu buchen.

[TIP]
.Tipp
====
Mit dieser Versandbestätigung erfährt Masterpayment, dass die Bestellung versendet ist. Dies aktiviert die Rechnung, die als PDF-Datei im Auftrag hinterlegt wird. Wenndu die Rechnung früher benötigst, stelle ein früheres Ereignis ein.
====

[#90]
== Stornierungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Stornierungen automatisch an Masterpayment zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß Tabelle 3.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß Tabelle 3 vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an Masterpayment
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für *stornierte Aufträge* wählen.

|*Filter*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*Masterpayment*

|*Aktion*
|*Zahlungsarten &gt; Rückzahlung an Masterpayment senden*
|
|====
