= Alter Webshop: mediafinanz
:lang: de
include::{includedir}/_header.adoc[]
:keywords: mediafinanz, Inkassodienstleister
:description: Payment in plentymarkets: Richten Sie die Schnittstelle zum Inkassodienstleister mediafinanz in Ihrem plentymarkets System ein.
:position: 150

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *mediafinanz* in Callisto Shops. Die folgenden Anleitungen sind somit nicht für Ceres Shops gültig!
====

Die mediafinanz AG ist Deutschlands erstes Inkassounternehmen mit TÜV-geprüftem Forderungsmanagement. Als einer der Vorreiter webbasierter Inkassoservices hat sich das Unternehmen seit nunmehr zehn Jahren in der Branche und am Markt etabliert. Erfahren Sie, wie Sie den Inkassodienstleister mediafinanz in plentymarkets einrichten.

[#10]
== Bei mediafinanz registrieren

Bevor Sie den Service von mediafinanz in plentymarkets einrichten können, registrieren Sie sich bei link:https://www.mediafinanz.de/inkassoverfahren-starten[mediafinanz^].

[#20]
== mediafinanz in Callisto einrichten

Um mediafinanz in plentymarkets einzurichten, müssen Sie zunächst Ihre Unternehmensinformationen eingeben bzw. ergänzen.

[.instruction]
Unternehmensinformationen eingeben:

. Öffnen Sie das Menü *System » Einstellungen » Stammdaten*.
. Geben Sie den Firmennamen ein.
. Geben Sie den Geschäftsführer ein.
. Geben Sie die Firmenadresse ein.
. Geben Sie eine Telefonnummer ein.
. Geben Sie eine E-Mail-Adresse ein.
. *Speichern* Sie die Einstellungen.

Nach dem erneuten Laden des Tabs *Einstellungen* sind eingegebenen Daten im Tab *Unternehmensinformationen* unter *mediafinanz* sichtbar. Aktivieren Sie anschließend die Schnittstelle zu mediafinanz.

[.instruction]
Schnittstelle zu mediafinanz aktivieren:

. Öffnen Sie das Menü *System » Aufträge » Inkasso » mediafinanz*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Klicken Sie auf *Mediafinanz aktivieren*. +
→ Die Schnittstelle wird aktiviert.

[#30]
== Mahnstufe zuordnen

Für die Zuordnung der Mahnstufe zu unbezahlten Aufträgen benötigen Sie einen <<auftraege/auftraege-verwalten#1200, Auftragsstatus>>. Sie können einen Standardstatus verwenden oder einen eigenen Auftragsstatus erstellen. Mit der folgenden Aktion ordnen Sie unbezahlten Aufträgen mit dem Aktionsmanager eine Mahnstufe zu.

[.instruction]
Mahnstufe per Aktionsmanager zuordnen:

. Öffnen Sie das Menü *System » Aufträge » Aktionen*.
. Wechseln Sie in das Tab *Neue Aktion*.
. Setzen Sie ein Häkchen bei *Aktiv*, um die Aktion zu aktivieren.
. Wählen Sie bei der Einstellung *Täglich ausführen um* eine Uhrzeit.
. Geben Sie einen *Namen* für die Aktion ein.
. Wechseln Sie in das Tab *Filter*.
. Wählen Sie den Status für unbezahlte Aufträge.
. Wählen Sie unter *Letzter Statuswechsel* die Option *Tage eingeben*. +
→ Das Feld *Tage* wird eingeblendet.
. Geben Sie die Anzahl der Tage ein, die sich der Auftrag im entsprechenden Status befindet.
. Wählen Sie unter *Zahlungseingang* die Option *OFFEN*.
. Wechseln Sie in das Tab *Aktion*.
. Wählen Sie unter *Ändere Auftragsstatus* den Status für die Zuordnung der Mahnstufe.
. Wählen Sie unter *Ändere Mahnstufe* eine Mahnstufe.
. *Speichern* Sie die Einstellungen.

[#40]
== Mahngebühr hinzufügen

Die Information an mediafinanz erfolgt in Form eines Artikels, der z.B. den Namen *Mahngebühr* hat und als Preis die entsprechende Gebühr. Der Artikel wird später den unbezahlten Aufträgen, die mit der vorigen Aktion ermittelt wurden, hinzugefügt. Dies geschieht entweder manuell oder mit einer Ereignisaktion. Unbezahlte Aufträge werden nur mit hinzugefügtem Mahnartikel an mediafinanz übermittelt. Wie Sie einen Artikel erstellen, erfahren Sie unter <<artikel/artikel-verwalten#20, Artikel erstellen>>. Speichern Sie anschließend die Artikel-ID im Menü *mediafinanz*.

[.instruction]
Artikel-ID hinterlegen:

. Öffnen Sie das Menü *System » Aufträge » Inkasso » mediafinanz*.
. Geben Sie unter *Artikel-ID Mahngebühr* die ID des zuvor erstellten Artikels ein.
. *Speichern* Sie die Einstellungen.

Richten Sie eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um den Mahnartikel automatisch allen unbezahlten Aufträgen zuzuordnen.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffnen Sie das Menü *System » Aufträge » Ereignisse*.
.  Klicken Sie auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Geben Sie einen Namen ein.
.  Wählen Sie das *Ereignis* gemäß <<tabelle-ereignisaktion-mediafinanz-mahnartikel>> vor.
. *Speichern* Sie die Einstellungen.
.  Nehmen Sie die Einstellungen gemäß <<tabelle-ereignisaktion-mediafinanz-mahnartikel>> vor.
.  Setzen Sie ein Häkchen bei *Aktiv*.
. *Speichern* Sie die Einstellungen.
--

[[tabelle-ereignisaktion-mediafinanz-mahnartikel]]
.Ereignisaktion zum automatischen Zuordnen des Mahnartikels zu unbezahlten Aufträgen
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
|Status für die *Zuordnung der Mahnstufe* wählen.

|*Filter*
|*Auftrag > Mahnstufe*
|*Mahnstufe*

|*Aktion 1*
|*Artikel > Mahnung erzeugen*
|*Varianten-ID eingeben*

|*Aktion 2*
|*Auftrag > Mahnstufe ändern*
|*Höhere Mahnstufe*
|====

[#50]
== Aufträge an mediafinanz übergeben

Sie können nun im Aktionsmanager eine Aktion erstellen, die bewirkt, dass die gewünschten Aufträge an mediafinanz übergeben werden. Als Beispiel könnten Sie die Aufträge anhand eines Auftragsstatus oder einer Mahnstufe filtern, um unbezahlte Aufträge mit der entsprechenden Mahnstufe an mediafinanz zu übermitteln.

[.instruction]
Aufträge per Aktionsmanager an mediafinanz übermitteln:

. Öffnen Sie das Menü *System » Aufträge » Aktionen*.
. Wechseln Sie in das Tab *Neue Aktion*.
. Setzen Sie ein Häkchen bei *Aktiv*, um die Aktion zu aktivieren.
. Wählen Sie bei der Einstellung *Täglich ausführen um* eine Uhrzeit.
. Geben Sie einen *Namen* für die Aktion ein.
. Wechseln Sie in das Tab *Filter*.
. Wählen Sie den Status für unbezahlte Aufträge.
. Wählen Sie unter *Auftragstyp* die Option *Auftrag*.
. Wählen Sie unter *Mahnstufe* per Ereignisaktion vergebene Mahnstufe.
. Wechseln Sie in das Tab *Aktion*.
. Wählen Sie unter *mediafinanz* die Option *AKTIV*.
. *Speichern* Sie die Einstellungen.

[#60]
== Inkasso-Übergaben anzeigen

Eine Übersicht der an mediafinanz übermittelten Aufträge zeigen Sie im Menü *Aufträge » Inkasso-Übergaben* im Bereich *Mediafinanz* an.
