= Alter Webshop: PayPal PLUS
:lang: de
include::{includedir}/_header.adoc[]
:keywords: PayPal Plus, Zahlungsart
:description: Payment in plentymarkets: Richte die Schnittstelle zu PayPal PLUS in deinem plentymarkets System ein.
:position: 20
:url: payment/zahlungsanbieter/paypal-plus
:id: LCFSITP

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *PayPal PLUS* für Callisto Shops. Für die Verwendung von *PayPal PLUS* in Ceres Shops erhältst du ausführliche Informationen in der Beschreibung des Plugins im link:https://marketplace.plentymarkets.com/plugins/payment/PayPal_4690[plentyMarketplace^].
====

PayPal PLUS beinhaltet neben der Zahlungsart PayPal weitere Zahlungsarten wie Kreditkarte oder Lastschrift. Die Zahlungsarten Lastschrift und Kauf auf Rechnung stehen jedoch nur für das Lieferland Deutschland zur Verfügung.

[#10]
== Geschäftskonto für PayPal PLUS eröffnen

Bevor du die Zahlungsart in plentymarkets einrichten kannst, ist die link:https://www.paypal.com/de/webapps/mpp/merchant[Eröffnung eines Geschäftskontos bei PayPal^] erforderlich. Du erhältst dann Informationen sowie Zugangsdaten, die du für die Einrichtung in plentymarkets benötigst.

[IMPORTANT]
.PayPal PLUS und Webshop-Design
====
Beachte, dass für die erfolgreiche Integration von PayPal PLUS in plentymarkets folgende Bedingungen erfüllt sein müssen:

* Verwendung des Standard-Designs Callisto (ab Version 2)
* Nutzung des Individuellen Bestellvorgangs
* Sicherer Umgang mit dem plentymarkets CMS
* Erfahrung mit der Einrichtung von Zahlungsdienstleistern
====

[#20]
== PayPal PLUS in Callisto einrichten

Wie und wo du festlegst, für welchen Shop und welche Lieferländer PayPal PLUS verfügbar ist, sowie die Schnittstellendaten einzugeben sind, erfährst du im Folgenden. Generell stehen dir nur die Lieferländer zur Auswahl, die du im Menü <<fulfillment/versand-vorbereiten#100, Einrichtung » Aufträge » Versand » Optionen » Tab: Lieferländer>> gewählt hast.

[.instruction]
PayPal PLUS-Schnittstelle einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öfffne den Ordner *International*.
. Klicke auf *PayPal PLUS*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechsle in das Tab *Schnittstelle*.
. Klappe einen Mandanten auf.
. Falls du zunächst einige Testkäufe durchführen möchtest, aktiviere den *Testmodus*.
. *Speichere* die Einstellungen.
. Klicke auf *Konto hinzufügen*. +
→ Du wirst zu PayPal weitergeleitet.
. Logge dich ein.
. Bestätige den Zugriff auf dein PayPal-Konto durch plentymarkets. +
→ Du wirst in dein plentymarkets System weitergeleitet.
. Wiederhole die Schritte 1 bis 6.
. Gib deinen Shop-Namen ein.
. Gib die URL zu deinem Logo ein, damit dein Logo im Warenkorb von PayPal angezeigt wird.
. Wähle *Ja*, wenn die Zugangsdaten für alle Mandanten gelten sollen.
. *Speichere* die Einstellungen.

[TIP]
.Testmodus oder Live-Modus
====
Wenn du zunächst einige Testkäufe in der Sandbox durchführen möchtest, aktiviere den Testmodus. Beachte, dass du bei Aktivierung des Testmodus an eine andere Adresse (Sandbox) bei PayPal weitergeleitet wirst. Speichere deshalb die Einstellungen für die Schnittstelle nach Aktivierung des Testmodus, bevor du das Konto hinzufügst.
====

[#30]
== Zahlungsarten aktivieren

Neben der Zahlungsart PayPal PLUS, die du im Menü <<payment/zahlungsarten-verwalten#20, Einrichtung » Aufträge » Zahlung » Zahlungsarten>> aktivierst, stehen dir weitere Zahlungsarten wie Kreditkarte oder Lastschrift zur Verfügung. Die Zahlungsarten Lastschrift und Kauf auf Rechnung können jedoch nur für das Lieferland Deutschland genutzt werden. Richte die gewünschten <<payment/zahlungsarten-verwalten#10, Zahlungsarten>> in deinem plentymarkets Backend ein und aktiviere die Zahlungsarten. Um die Logos weiterer Zahlungsarten anzuzeigen, lade die Logos direkt bei der Zahlungsart in einer Größe von maximal 100 x 25 px hoch. Prüfe zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[IMPORTANT]
.Einschränkungen für den Kauf auf Rechnung
====
Wenn der Einkaufswert kleiner als 1,50 EUR oder größer als 1500,00 EUR ist, wird der Kauf auf Rechnung über PayPal PLUS nicht angeboten. Zudem sind digitale Medien aufgrund der fehlenden Rücksendemöglichkeit vom Kauf auf Rechnung ausgeschlossen.
====

[#40]
== PayPal PLUS im Callisto Webshop anzeigen

In diesem Kapitel wird beschrieben, wie du PayPal PLUS in den individuellen Bestellvorgang von plentymarkets einfügst. Hierfür sind mehrere Schritte nötig. Zunächst wird PayPal PLUS in eine Kategorie des Typs *Container* eingefügt.

[WARNING]
.Keine Anpassungen am aktiven Design vornehmen
====
Nimm keine Änderungen an deinem aktiven Design vor. Bevor du Änderungen an deinem Design vornimmst, lege eine Sicherungskopie an, damit du jederzeit wieder zum Ursprungszustand zurückgelangst.
====

[IMPORTANT]
.Berechnung der Auftragssumme
====
PayPal und plentymarkets berechnen Preise aufgrund unterschiedlicher Anzahl der Nachkommastellen unterschiedlich. Deshalb können Rundungsdifferenzen zwischen der Auftragssumme in plentymarkets und bei PayPal auftreten. Die Rundungsdifferenzen werden im Hintergrund entweder durch eine Gutschrift oder einen Differenzartikel ausgeglichen, sodass die Summen in plentymarkets und bei PayPal übereinstimmen.
====

[#50]
=== Kategorie für weiteren Bestellschritt hinzufügen

Damit dein Kunde zunächst eine Versandart wählen kann und der Preis für den gewählten Versand korrekt an PayPal übermittelt wird, müssen Versand und Zahlung in zwei verschiedenen Schritten erfolgen. Deshalb erstellst du für die Wahl der Zahlungsart eine neue Kategorie und änderst anschließend die standardmäßig in Callisto Light enthaltene Kategorie *Zahlung &amp; Versand*.

[.instruction]
Kategorie des Typs Container erstellen:

. Öffne das Menü *Artikel » Kategorien*.
. Klicke auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Gib einen Namen ein, z.B. Zahlungsart wählen.
. Klicke auf *Erstellen*. +
→ Die Kategorie wird im Tab *Einstellungen* geöffnet.
. Wähle unter *Typ* die Option *Container*.
. Wechsle in das Tab *Beschreibung 1*.
. Füge das Code-Beispiel ein. +
→ Unten findest du ein ein Beispiel für Version 3 und Version 2 von Callisto Light.
. *Speichere* die Einstellungen.

[#60]
=== Kategorie Zahlung &amp; Versand ändern

Anschließend musst du die in Callisto Light 3 standardmäßig vorhandene Kategorie *Zahlung &amp; Versand* anpassen.

[.instruction]
Kategorie und Bestellschritt Zahlung &amp; Versand ändern:

. Öffne das Menü *Artikel » Kategorien*.
. Öffne den Ordner des Designs, das du bearbeiten möchtest, z.B. Callisto Light 3.
. Öffne die Kategorie *Zahlung &amp; Versand*.
. Ändere Namen im Tab *Einstellungen*, z.B. zu Versand.
. Wechsle in das Tab *Beschreibung 1*.
. Entferne den Div-Container zur Anzeige von Zahlungsarten.
. *Speichere* die Einstellungen.

[#70]
=== Bestellschritte anpassen

Die neu erstellte Kategorie sowie die geänderte Kategorie müssen jetzt den Bestellschritten des individuellen Bestellvorgangs hinzugefügt werden.

[.instruction]
Bestellschritte anpassen:

. Öffne das Menü *CMS » Webdesign*.
. Klicke auf *Einstellungen*. +
→ Das Fenster *Design-Einstellungen* wird geöffnet.
. Wechsle in das Tab *Mandanten*.
. Klicke auf einen Mandanten.
. Wechsle in das Tab *Bestellvorgang*.
. Klicke im *6. Bestellschritt* auf *Suchen*.
. Wähle die Kategorie *Versand*.
. Klicke auf *Auswählen*.
. Klicke im *7. Bestellschritt* auf *Suchen*.
. Wähle die neu erstellte Kategorie *Zahlungsart wählen*.
. Klicke auf *Auswählen*.
. Klicke im *8. Bestellschritt* auf *Suchen*.
. Wähle die Kategorie *Bestellübersicht &amp; Kaufabschluss*.
. Klicke auf *Auswählen*.
. Klicke im *9. Bestellschritt* auf *Suchen*.
. Wähle die Kategorie *Bestellvorgang*.
. Klicke auf *Auswählen*.
. *Speichere* die Einstellungen. +
→ Die Bestellschritte werden angepasst.

[#80]
=== Kategorie Kasse anpassen

Damit die Bestellschritte auch in der neuen Reihenfolge durchlaufen werden, muss außerdem noch die Kategorie Kasse angepasst werden.

. Öffne das Menü *Artikel » Kategorien*.
. Öffne den Ordner des Designs, das du bearbeiten möchtest, z.B. Callisto Light 3.
. Öffne die Kategorie *Kasse*.
. Wechsle in das Tab *Beschreibung 1*.
. Entferne das Listenelement für *Zahlung &amp; Versand*.
. Füge nach dem Listenelement *Anschrift* Listenelemente für die neuen Bestellschritte Versand und Zahlungsart wählen hinzu. +
→ Einen Beispiel-Code findest du unter dieser Beschreibung.
. Ersetze außerdem weiter unten im Code *Step 3* und *Step 4* durch das zweite Code-Beispiel unter dieser Beschreibung.
. *Speichere* die Einstellungen.

[#90]
=== Kategorie Bestellübersicht &amp; Kaufabschluss anpassen

Damit der Kunde aus der Bestellübersicht wieder in den richtigen Bestellschritt gelangt, wenn er seine Angaben noch einmal ändern möchte, muss außerdem noch eine Änderung an der Kategorie *Bestellübersicht &amp; Kaufabschluss* vorgenommen werden.

. Öffne das Menü *Artikel » Kategorien*.
. Öffne den Ordner des Designs, das du bearbeiten möchtest, z.B. Callisto Light 3.
. Öffne die Kategorie *Bestellübersicht &amp; Kaufabschluss*.
. Wechsle in das Tab *Beschreibung 1*.
. Suche im Code die Stelle *data-plenty="click:Redirect.toCheckoutTab('#shipping-payment')"*.
. Entferne *shipping-*, sodass der Code *data-plenty="click:Redirect.toCheckoutTab('#payment')"* stehen bleibt.
. *Speichere* die Einstellungen.

[#100]
=== PageDesignPrepareMainColumn anpassen

Damit PayPal PLUS korrekt ausgeführt und angezeigt wird, ist noch eine Anpassung im Template *PageDesignPrepareMainColumn* notwendig.

[.instruction]
PageDesignPrepareMainColumn anpassen:

. Öffne das Menü *CMS » Webdesign*.
. Öffne den Ordner *Layout » PageDesign*.
. Öffne das Template *PageDesignPrepareMainColumn*.
. Suche im Code die Stelle *gototab=shipping-payment*.
. Ersetze *shipping-payment* durch *payment*.
. *Speichere* die Einstellungen.

[#105]
=== PageDesignCheckout anpassen

Um nach der Bestellung die Bestellübersicht aufzurufen, ist noch eine Anpassung im Template *PageDesignCheckout* notwendig.

[.instruction]
PageDesignCheckout anpassen:

. Öffne das Menü *CMS » Webdesign*.
. Öffne den Ordner *Layout » PageDesign*.
. Öffne das Template *PageDesignCheckout*.
. Suche im Code die Stelle *PlentyFramework.setGlobal( 'checkoutConfirmCatID', {% CheckoutStepPageID(7) %});*.
. Ersetze *CheckoutStepPageID(7)* durch *CheckoutStepPageID(8)*.
. *Speichere* die Einstellungen.

[#108]
=== Beschreibung bei zusätzlichen Zahlungsarten anzeigen

Wenn du zusätzlich zu den PayPal PLUS eigenen Zahlungsarten weitere Zahlungsarten im Bestellvorgang verwenden, kannst du neben dem Namen der Zahlungsart einen Beschreibungstext in der Liste der Zahlungsarten anzeigen. Im Folgenden erfährst du am Beispiel der Zahlungsart *Vorkasse*, wie du eine Beschreibung hinzufügst. Nimm die folgenden Einstellungen bei <<payment/zahlungsarten-verwalten#40, anderen Zahlungsarten>> analog vor.

[.instruction]
Kategorie mit Beschreibungstext erstellen:

. Öffne das Menü *Artikel » Kategorien*.
. Klicke auf *Neue Kategorie*. +
→ Das Fenster *Neue Kategorie erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle die Kategorieart.
. Wenn du *Unterkategorie* aktivierst, wähle eine Kategorie, in der die Unterkategorie erstellt werden soll.
. Klicke auf *Erstellen*. +
→ Die neue Kategorie wird erstellt und das Tab *Einstellungen* wird geöffnet.
. Wähle den Typ *Content*.
. Aktiviere den *Mandant (Shop)*.
. *Speichere* die Einstellungen.
. Wechsle in das Tab *Beschreibung 2*.
. Wähle der rechten Dropdown-Liste die Option *Textfeld*.
. Gib eine Beschreibung in das Textfeld ein.
. *Speichere* die Einstellungen.

Nun musst du die zuvor erstellte Kategorie mit der Zahlungsart verknüpfen, damit die Beschreibung in der Übersicht der Zahlungsarten im Bestellvorgang mit PayPal PLUS angezeigt wird.

[.instruction]
Kategorie mit Zahlungsart verknüpfen:

.  Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
.  Aktiviere die Einstellung *Auch inaktive zeigen*.
.  Öffne den Ordner *International*.
.  Klicke auf *Vorkasse*. +
→ Das Tab *Einstellungen* wird geöffnet.
.  Wähle bei der Option *Infoseite* die Einstellung *Infoseite (Intern)*.
.  Klicke unter *Infoseite (Intern)* auf *Bearbeiten*. +
→ Das Fenster *Artikelvorlage wählen* wird geöffnet.
. Wähle die neu erstellte Kategorie.
. Klicke auf *Wählen*. +
→ Die Kategorie wird mit der Zahlungsart verknüpft.
. *Speichere* die Einstellungen.

[#110]
== Rechnungsvorlage für PayPal PLUS-Aufträge anpassen

Wenn du PayPal PLUS nutzt und Rechnungen für Aufträge erzeugen, die mit der PayPal-PLUS-Zahlungsart Rechnung bezahlt werden, ist es notwendig, dass du statt deiner eigenen Bankdaten die Bankdaten von PayPal auf der Rechnung anzeigst. Dies geschieht automatisch über einen Zahlungshinweis. Wenn du deine eigene <<auftraege/auftragsdokumente#170, PDF-Vorlage>> verwenden möchtest, gehe wie nachfolgend beschrieben vor.

[IMPORTANT]
.Breite des Zahlungshinweises beachten
====
Um die Bankdaten von PayPal PLUS korrekt auf deiner Rechnung auszugeben, muss für den Zahlungshinweis im Menü *System » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung* eine Breite von 120 Millimetern eingegeben werden.
====

[.instruction]
Eigene PDF-Vorlage verwenden:

. Öffne das Menü *Einrichtung » Mandant » Mandant wählen » Standorte » Standort wählen » Dokumente » Rechnung*.
. Wechsle in das Tab *PDF-Vorlage*.
. Wechsle dort in das Untertab *Neue Vorlage*.
. Wähle *PayPal PLUS* aus der Dropdown-Liste, um die Vorlage für PayPal PLUS zu hinterlegen.
. Wähle unter *Datei* die auf deinem Rechner hinterlegte PDF-Datei.
. Klicke auf *Öffnen*.
. *Speichere* die Einstellungen. +
→ Die PDF-Datei wird hochgeladen und kann im Tab *Vorlagen* angezeigt werden.

Bevor du die Rechnung auch an Kunden schicken, informieren dich, ob der Kunde nicht schon eine Rechnung von PayPal erhält, damit der Kunde nicht am Ende zwei Rechnungen erhält.

[#120]
== Lieferadresse nicht von PayPal PLUS übernehmen

Standardmäßig wird die Lieferadresse bei einer Bestellung mit PayPal PLUS direkt von PayPal übernommen und nicht die vom Kunden eingegebene. Wenn du die Lieferadresse nicht von PayPal übernehmen möchtest, gehe wie folgt vor.

[.instruction]
Lieferadresse nicht übernehmen:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Setze ein Häkchen bei *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
.  Klicke auf PayPal PLUS. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechsle in das Tab *Schnittstelle*.
. Klappe einen Mandanten auf.
. Aktiviere die Einstellung *Lieferadresse nicht übernehmen*.
. *Speichere* die Einstellungen.

[#130]
== Teilbetrag erstatten

Um dem Käufer einen Teil des Kaufbetrags zu erstatten, erstelle zunächst einen Auftrag vom Typ *Gutschrift* und gib in dieser Gutschrift die Summe an, die du erstatten möchtest. Da die Summe in deinem Ermessen liegt und für jeden Auftrag unterschiedlich ausfällt, müssen Teilbeträge manuell erstattet werden. Eine Automatisierung ist nicht möglich.

[.instruction]
Gutschrift anlegen, um Teilbetrag zu erstatten:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den gewünschten PayPal PLUS-Auftrag.
. Klicke im Tab *Übersicht* auf die Dropdown-Liste *Gutschrift ...* und wähle die Option *anlegen*. +
→ Die Gutschrift wird angelegt.
. Öffne nun die neu angelegte Gutschrift und wechsle in das Tab *Einstellungen*.
. Klicke unter *Rückzahlung* auf *PayPal PLUS Refund*.
. Gib die Summe ein, die du erstatten möchtest.
. Klicke auf *Rückzahlung tätigen*. +
→ Die Summe wird an PayPal gesendet.

[#140]
== Gesamtbetrag erstatten und automatisch an PayPal senden

Um dem Käufer den gesamten Betrag zu erstatten, lege einen Auftrag vom Typ *Gutschrift* an. Gutschriften werden automatisch der Zahlung zugeordnet.

[.instruction]
Gutschrift anlegen, um Gesamtbetrag zu erstatten:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den gewünschten PayPal PLUS-Auftrag.
. Klicke im Tab *Übersicht* auf die Dropdown-Liste *Gutschrift ...* und wähle die Option *anlegen*. +
→ Die Gutschrift wird angelegt.

Anschließend richtest du eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um die Beträge automatisch an PayPal PLUS zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß Tabelle 1.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß Tabelle 1 vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Rückzahlungen an PayPal PLUS
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Gutschrift*
|

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*PayPal PLUS*

|*Aktion*
|*Zahlungsarten &gt; Rückzahlung an PayPal PLUS senden*
|
|====

[#150]
==  Abgelehnte Zahlungen automatisch melden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um deine Kunden automatisch über abgelehnte Zahlungen zu informieren. Damit von PayPal PLUS abgelehnte Zahlungen automatisch per E-Mail an den Kunden und per Statuswechsel an dich gemeldet werden, erstelle einen *Auftragsstatus* für *abgelehnte Zahlungen* von PayPal PLUS oder nutze einen vorhandenen Auftragsstatus.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 2.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 2 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Melden von abgelehnten Zahlungen durch PayPal PLUS
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Zahlung: Abgelehnt*
|

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*PayPal PLUS*

|*Aktion 1*
|*Kunde &gt; E-Mail versenden*
| E-Mail-Vorlage wählen; +
*Kunde* wählen

|*Aktion 2*
|*Auftrag &gt; Status ändern*
| Auftragsstatus wählen, z.B. *[3.2] In Warteposition*
|====
