= Alter Webshop: POSTPAY
:lang: de
include::{includedir}/_header.adoc[]
:keywords: POSTPAY, Zahlungsart
:description: Payment in plentymarkets: Richte die Schnittstelle zu POSTPAY in deinem plentymarkets System ein.
:position: 190
:url: payment/zahlungsanbieter/postpay

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *POSTPAY* in Callisto Shops. Die folgenden Anleitungen sind somit nicht für Ceres Shops gültig!
====

link:http://www.postpay.de/de/p/postpay/postpay.html[POSTPAY^] ist der Zahlungsdienst der Deutschen Post. Mit POSTPAY bietest du deinen Webshop-Kunden eine Zahlungs- und Bestellabwicklung an, die bereits von vielen Kunden der Deutschen Post genutzt wird. POSTPAY bündelt die Zahlungsarten *Lastschrift*, *Vorkasse*, *Giropay*, *SOFORT Überweisung*, *Kreditkarte* und *Kauf auf Rechnung*.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhältst du wichtige Hinweise zur Integration des Zahlungsanbieters in plentymarkets.

[IMPORTANT]
.Auftragsanlage
====
Ein Auftrag wird in plentymarkets erst beim Zahlungseingang angelegt, erfolgt also noch nicht im Bestellvorgang bei Klick auf die Schaltfläche *POSTPAY* im Warenkorb.
====

[.subhead]
*Bezahlvorgang:*

Nach dem Bestätigen der Bestellung wird der Kunde auf eine Seite von POSTPAY weitergeleitet. Dort muss er sich in seinen POSTPAY-Account einloggen, eine Zahlungsoption wählen und die Zahlung bestätigen. Je nachdem, ob der Kunde bereits in deinem Webshop den Checkout-Prozess durchlaufen und dort POSTPAY als Zahlungsart gewählt hat, oder ob er auf die Schaltfläche *POSTPAY* im Warenkorb klickt, ohne sich eingeloggt zu haben, muss er unter Umständen noch seine Rechnungs- und Lieferanschrift bei POSTPAY eingeben.

Hier die beiden Varianten im Überblick:

* Der Kunde ist in deinem Webshop eingeloggt und hat dort bereits Rechnungs- und Lieferanschrift eingegeben. Diese Daten werden bei der Weiterleitung zu POSTPAY übernommen, können aber durch den Kunden noch angepasst werden.
* Der Kunde ist nicht in deinem Webshop eingeloggt und wählt *POSTPAY* über die Schaltfläche im Warenkorb. Der Kunde wird zu POSTPAY weitergeleitet und loggt sich dort mit seinen POSTPAY-Daten ein. Die primäre Zahlungsart und die Adresse sind bereits hinterlegt und die Bestellung kann mit einem Klick abgeschlossen werden. Hat der Kunde noch keinen POSTPAY-Account, muss er dort seine Daten für Rechnungs- und Lieferanschrift eingeben.

[#20]
== Bei POSTPAY registrieren

Sofern du bereits ein Händlerkonto bei link:https://de.allyouneed.com/de/customerlogin.html[Allyouneed.com^] hast, ist keine erneute Registrierung notwendig. Du kannst sofort mit der <<payment/zahlungsanbieter/postpay#30, Einrichtung von POSTPAY>> beginnen.

Wenn du noch keinen Vertrag hast, registriere dich bei link:https://de.allyouneed.com/de/dealer/page/selfsignup/step1?ssu=postpay[POSTPAY^]. Im Anschluss erhältst du den Händlervertrag für Allyouneed.com und POSTPAY per Post oder E-Mail übermittelt, der unterschrieben zurückgesendet werden muss. Ergänze den Händlervertrag um Angaben zum wirtschaftlichen Berechtigten und zum gesetzlichen Vertreter. Nach einer internen Prüfung durch POSTPAY wird dein Konto aktiviert und du erhältst per E-Mail eine Bestätigung mit deinen Zugangsdaten. Die Zugangsdaten benötigst du im nächsten Schritt für die Einrichtung in plentymarkets.

[#30]
== POSTPAY in Callisto einrichten

Gehe wie unten beschrieben vor, um die Schnittstelle zu POSTPAY für deinen Callisto Shop in plentymarkets einzurichten.

[.instruction]
Schnittstelle zu POSTPAY einrichten:

. Öffne das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *DE*.
.  Klicke auf *POSTPAY*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechsle in das Tab *Schnittstelle*.
.  Klappe den Mandanten auf.
.  Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-postpay>>.
. *Speichere* die Einstellungen.

[[tabelle-schnittstelleneinrichtung-postpay]]
.Schnittstelle zu POSTPAY einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Benutzername*
|Benutzername eingeben, wie von POSTPAY erhalten.

|*Passwort*
|Passwort eingeben, wie von POSTPAY erhalten.

|*Testmodus aktivieren*
|Testmodus aktivieren, um die POSTPAY-Funktionen zu testen, bevor mit dem System live gearbeitet wird.

|*Zugangsdaten für alle Mandanten (Shops) aktivieren*
|Nur sichtbar, wenn Mandanten eingerichtet sind. Aktivieren, um die Kontoeinstellungen, die über *Konto hinzufügen* für den Hauptshop gespeichert wurden, für alle Mandanten (Shops) zu übernehmen, unabhängig davon, was für andere Mandanten gespeichert wurde. Deaktivieren, um separate Zugangsdaten für weitere Mandanten (Shops) zu verwenden. Webshops, für die kein Konto hinzugefügt wurde, können mit POSTPAY nicht genutzt werden. +
Zur Unterstützung mehrerer Mandanten muss im Menü <<webshop/webshop-einrichten#grundeinstellungen, System » Systemeinstellungen » Mandant » Mandant wählen » Webshop » Einstellungen>> für die Option *Login* die Einstellung *Login in jedem einzelnen Shop ermöglichen* aktiviert sein.
|====

[#40]
== Zahlungsart aktivieren

Richte die <<payment/zahlungsarten-verwalten#20, Zahlungsart>> POSTPAY im Tab *Einstellungen* der Zahlungsart ein. Prüfe zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#50]
== URL für Push-Service hinterlegen

Logge dich mit deinen Daten bei POSTPAY ein und gib im Tab *Verwaltung* die *URL für den Push-Service* ein. Mit dieser URL teilst du POSTPAY mit, wohin Zahlungsbestätigungen gesendet werden sollen. Die URL ist nach folgendem Muster aufgebaut:

*DEINE_DOMAIN/plenty/api/payment_notification.php?payment=postpay&amp;*

Diese URL passt du gemäß der Domain deines Shops an und speicherst sie im *POSTPAY*-Backend.

[#60]
== Gutschrift für POSTPAY-Auftrag manuell anlegen

Es kann notwendig werden, für einzelne Aufträge, die über POSTPAY abgewickelt werden, Gutschriften zu erstellen. Du hast hierfür die Möglichkeit, individuelle Gutschriftenbeträge an POSTPAY zu senden.

[.instruction]
Gutschrift an POSTPAY senden:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den POSTPAY-Auftrag. +
→ Das Tab *Übersicht* wird geöffnet.
. Wähle die Option *anlegen* aus der Dropdown-Liste *Gutschrift ...*. +
→ Die Gutschrift wird angelegt.
. Öffne die neu angelegte Gutschrift.
. Wechsle in das Tab *Einstellungen*.
. Gib im Feld *POSTPAY Gutschrift senden* den Betrag ein.
. Klicke auf *POSTPAY Gutschrift senden*. +
→ Die Gutschrift wird an POSTPAY gesendet.

[#70]
== Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch zu versenden, nachdem der Warenausgang gebucht wurde.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 2.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 2 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an POSTPAY
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Zahlungsart*
|*POSTPAY*

|*Filter 2*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Aktion*
|*Versand &gt; Versandbestätigung an POSTPAY senden*
|
|====

[#80]
== Retouren automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Retouren automatisch an POSTPAY zu senden. Weitere Details zum Anlegen von Retouren findest du auf der Handbuchseite <<auftraege/auftraege-verwalten#400, Retoure>>.

[.collapseBox]
.Ereignisaktion einrichten
--
. Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
. Gib einen Namen ein.
. Wähle das *Ereignis* gemäß Tabelle 3.
. *Speichere* die Einstellungen.
. Nimm die Einstellungen gemäß Tabelle 3 vor.
. Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Retouren an POSTPAY
[cols="1,3,3"]
|====
|Einstellung |Option |Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Retoure (durch Kunde)*
|

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Retoure*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*POSTPAY*

|*Aktion*
|*Retoure &gt; Retoure an POSTPAY senden*
|
|====

[#90]
== Gutschriften automatisch senden

Um Gutschriften automatisch zu senden, benötigst du einen <<auftraege/auftraege-verwalten#1200, Auftragsstatus>> für Gutschriften. Du kannst einen Standardstatus verwenden oder einen eigenen Auftragsstatus erstellen. Nur fertig bearbeitete Gutschriften erhalten diesen Status. Diese Gutschriften dürfen nach dem Anlegen nicht geändert werden. Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Gutschriften automatisch an POSTPAY zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 4.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 4 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Gutschriften an POSTPAY
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für die *Gutschrift an POSTPAY* wählen.

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Gutschrift*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*POSTPAY*

|*Aktion*
|*Zahlungsarten &gt; Gutschrift an POSTPAY senden*
|
|====

[#100]
== Stornierung automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um POSTPAY automatisch über Stornierungen zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 5.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 5 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an POSTPAY
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für *stornierte Aufträge* wählen.

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*POSTPAY*

|*Aktion*
|*Zahlungsarten &gt; Stornierung an POSTPAY senden*
|
|====
