= Alter Webshop: Saferpay
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Saferpay, Zahlungsart
:description: Payment in plentymarkets: Richte die Schnittstelle zu Saferpay in deinem plentymarkets System ein.
:position: 200
:url: payment/zahlungsanbieter/saferpay

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *Saferpay* in Callisto Shops. Die folgenden Anleitungen sind somit nicht für Ceres Shops gültig!
====

link:https://www.six-payment-services.com/de/shared/offering/products/psp/ecommerce.html[Saferpay^] hat im deutschsprachigen Europa den Standard für E-Payment-Lösungen gesetzt und steht damit als Synonym für "sicheres Bezahlen im Internet". Dank Saferpay müssen sich Online-Händler wie Karteninhaber über die Sicherheit beim Einkaufen im Internet keine Sorgen mehr machen. Händler kennen und schätzen das sichere Bezahlen im Internet über Saferpay weltweit.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhältst du wichtige Hinweise zur Integration des Zahlungsanbieters Saferpay in plentymarkets.

[#20]
=== Bezahlvorgang

Für den Bezahlvorgang wird der Kunde zu Saferpay weitergeleitet und dort über ein iframe dazu aufgefordert, seine notwendigen Daten einzugeben. Die Auswahl der Zahlungsart erfolgt noch im Webshop. Anschließend wird der Kunde direkt zu Saferpay weitergeleitet und die weiteren Inhalte werden in einem iframe bereitgestellt. Der Kunde gibt hier seine Daten ein. Dies erfolgt somit nicht im Webshop, sondern bei Saferpay. Nach der Eingabe und Bestätigung der Daten wird der Kunde auf die Bestellbestätigungsseite geleitet.

[#30]
=== SSL-Zertifikat

Für die korrekte Verwendung der Zahlungsart ist ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>> erforderlich.

[WARNING]
.Frage bei deiner Bank nach
====
Klären vor einer Integration der Zahlungsart Saferpay, ob deine Bank die Abwicklung über iframes unterstützt.
====

[#40]
== Bei Saferpay registrieren

Schließe einen link:https://www.six-payment-services.com/dam/downloads/contracts/116004201_CO_Saferpay_Contract_DEU_DE_active.pdf[Vertrag für die Nutzung von Saferpay^] mit SIX Payment Services ab. Du erhältst mit der Bestätigung des Vertrags die Zugangsdaten, die du für die Aktivierung in plentymarkets benötigst.

[#50]
== Saferpay in Callisto einrichten

Gehe wie unten beschrieben vor, um die Schnittstelle zu Saferpay für deinen Callisto Shop in plentymarkets einzurichten.

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
.  Klicke auf *Saferpay*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechsle in das Tab *Schnittstelle*.
.  Klappe den Bereich *Zugangsdaten: Mandant* auf.
.  Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-saferpay>>.
.  Klappe den Bereich *Einstellungen: Mandant* auf.
.  Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-einstellungen-schnittstelle-saferpay>>.
. *Speichere* die die Einstellungen.

[[tabelle-schnittstelleneinrichtung-saferpay]]
.Schnittstelle zu Saferpay einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Konto-ID*
|ID des Saferpay-Kontos eingeben, wie von Saferpay erhalten.

|*Passwort*
|Passwort des Saferpay-Kontos eingeben, wie von Saferpay erhalten.

2+|Mandant (Shop)-Optionen

|*Zugangsdaten für alle Mandanten (Shops) aktivieren*
|Nur sichtbar, wenn Mandanten eingerichtet sind. Aktivieren, um die Kontoeinstellungen, die über *Konto hinzufügen* für den Hauptshop gespeichert wurden, für alle Mandanten (Shops) zu übernehmen, unabhängig davon, was für andere Mandanten gespeichert wurde. Deaktivieren, um separate Zugangsdaten für weitere Mandanten (Shops) zu verwenden. Webshops, für die kein Konto hinzugefügt wurde, können mit Saferpay nicht genutzt werden. +
Zur Unterstützung mehrerer Mandanten muss im Menü <<webshop/webshop-einrichten#grundeinstellungen, Einrichtung » Mandant » Mandant wählen » Webshop » Einstellungen>> für die Option *Login* die Einstellung *Login in jedem einzelnen Shop ermöglichen* aktiviert sein.
|====

Pro Mandant (Shop) findest du im Tab *Schnittstelle* ein Untermenü *Einstellungen* mit weiteren Funktionen, die nachfolgend erläutert werden.

[[tabelle-einstellungen-schnittstelle-saferpay]]
.Weitere Einstellungen im Tab *Schnittstelle*
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*E-Mail-Adresse für Zahlungsmeldung*
|Eine E-Mail-Adresse eingeben, an die eine Zahlung gemeldet werden soll.

|*Fenster bei erfolgter Zahlung verzögert schließen (Sekunden)*
|Bei erfolgreicher Zahlung wird eine Meldung angezeigt. Einen Zeitwert in Sekunden eingeben, den das Fenster geöffnet bleiben soll, um dem Kunden z.B. die Möglichkeit zu geben, die Meldung zu drucken. Wird kein Wert eingegeben, bleibt das Fenster 100 Sekunden geöffnet (Standardeinstellung). Wenn das Fenster nicht angezeigt werden soll, den Wert *0* eingeben.

|*Name des Karten- oder Kontoinhabers abfragen*
|Wählen, ob die Abfrage erfolgen soll.

|*Anzeige der Sprachauswahl im Bezahlvorgang*
|Wählen, ob die Sprachauswahl angezeigt werden soll.

|*Farben*
|Hexadezimalwerte für Farben der einzelnen Elemente eingeben.

|*Schrifttyp*
|Eine Schriftart eingeben, z.B. die gleiche Schriftart, die im Webshop verwendet wird.

|*Mandant (Shop)-Optionen*
|*Ja* oder *Nein* wählen. +
*Ja* = Optionen bzw. Eingaben unter *Farben* und *Schriftart* auch auf Mandanten (Shops) anwenden.
|====

[#60]
== Zahlungsart aktivieren

Richte die <<payment/zahlungsarten-verwalten#20, Zahlungsart>> Saferpay im Tab *Einstellungen* der Zahlungsart ein. Prüfe zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#70]
== API-Log abrufen

Ein korrekter Datenaustausch sowie die Bestätigung der Buchung bei Saferpay und in plentymarkets wird durch einen grünen Balken unter *Zahlungseingang* angezeigt. Im Fall eines Fehlers bei der Datenübertragung findest du im API-Log Details zum Fehler.

[.instruction]
API-Log abrufen:

.  Öffne das Menü *Daten » API-Log » Tab: API-Log*.
.  Wähle ein Format aus der Dropdown-Liste *Vorgang*.
.  Wähle ggf. ein *Datum*, um nur Einträge eines bestimmten Tages zu erhalten.
.  Klicke auf *Suchen*, um die Suche auszuführen. +
→ Die Vorgänge werden angezeigt.

Je nach Art des Fehlers wird deine Zahlung zwar bei Saferpay gebucht, aber u.U. nicht in plentymarkets bestätigt, was wiederum zu einer fehlerhaften Buchung in plentymarkets führt. Bei einem Fehler prüfe bitte zunächst im Saferpay-System, ob die Zahlung erfolgt ist. Du kannst dann die Buchung in plentymarkets manuell korrigieren. Solltest du dir nicht sicher sein oder einen Fehler nicht nachvollziehen bzw. beheben können, kontaktiere den Service von Saferpay oder wende dich an unser link:https://forum.plentymarkets.com/[Forum^].
