= Alter Webshop: Skrill
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Skrill, Zahlungsart
:description: Payment in plentymarkets: Richten Sie die Schnittstelle zu Skrill in Ihrem plentymarkets System ein.
:position: 230

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *Skrill* für Callisto Shops. Für die Verwendung von *Skrill* in Ceres Shops erhalten Sie ausführliche Informationen in der Beschreibung des Plugins im link:https://marketplace.plentymarkets.com/plugins/payment/Skrill_5142[plentyMarketplace^].
====

Mit link:https://www.skrill.com/de/[Skrill^] vereinen Sie eine große Zahl an länderspezifischen <<payment/skrill#40, Zahlungsarten>>.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhalten Sie wichtige Hinweise zur Integration des Zahlungsanbieters *Skrill* in plentymarkets.

[#20]
=== Bezahlvorgang

Die Auswahl der Zahlungsart erfolgt noch im Webshop. Anschließend wird der Kunde direkt zu Skrill weitergeleitet. Die weiteren Inhalte werden in einem iframe bereitgestellt. Der Kunde trägt hier seine Daten ein. Die Dateneingabe erfolgt somit nicht im Webshop, sondern bei Skrill. Nach der Eingabe und Bestätigung der Daten wird der Kunde auf die Bestellbestätigungsseite geleitet.

[#30]
=== SSL-Zertifikat

Für die korrekte Verwendung der Zahlungsart ist ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>> erforderlich. Die Bezahlseite von Skrill ist bereits SSL-verschlüsselt.

[WARNING]
.Fragen Sie Ihre Bank
====
Klären Sie vor einer Integration von Zahlungsarten, ob Ihre Bank die Abwicklung über iframes unterstützt.
====

[#40]
=== Verfügbare Skrill-Zahlungsarten

Nachfolgend finden Sie eine Übersicht der für plentymarkets verfügbaren Skrill-Zahlungsarten mit der System-ID in Klammern.

* Carte Bleue (510)
* Digital Wallet (560)
* Giropay (530)
* iDEAL (580)
* Kreditkarte (500)
* Lastschrift (520)
* maestro (570)
* netpay eps (550)
* Sofortüberweisung (540)
* Online-Überweisung (590)
* CartaSi (591)
* PostePay (592)
* Visa Delta/Debit (593)
* Dankort (595)
* Payolution Invoice (596)
* Payolution Ins (597)
* Payolution Mangirkart (598)

[#50]
==  Bei Skrill registrieren

Eröffnen Sie zunächst ein link:https://content.skrill.com/de/ecommerce-solutions/plentymarkets/[Geschäftskonto^] bei Skrill. Sie gelangen direkt zur Gewerbeanmeldung, wenn Sie auf *Jetzt anmelden* klicken. Folgen Sie den weiteren Schritten, um die Registrierung abzuschließen. In einem der Schritte werden Sie aufgefordert, ein *Geheimwort* einzurichten, das die Zahlungen verschlüsselt. Das Geheimwort benötigen Sie für die Einrichtung der Zugangsdaten in plentymarkets. Das Geheimwort sollte sich von Ihrem Login-Passwort unterscheiden und darf maximal 10 Zeichen lang sein. Für das Geheimwort sind nur Kleinbuchstaben und Zahlen zulässig. Es darf keine Sonderzeichen enthalten.

Machen Sie sich auch mit dem Bereich *Kontoauszug* in Ihrem Skrill-Konto vertraut. Hier können Sie später Ihre Transaktionshistorie als Excel-Tabelle herunterladen und beliebig verarbeiten.

[#60]
==  Skrill in Callisto einrichten

Skrill hat ein zweistufiges Sicherheitskonzept für die Aktivierung von Konten. Schritt 1 ist die Verifizierung der E-Mail-Adresse. Schritt 2 besteht in der Verifizierung Ihrer Personalangaben. Gehen Sie wie unten beschrieben vor, um die Schnittstelle zu Skrill für Ihren Callisto Shop in plentymarkets einzurichten.

[.instruction]
Schnittstelle zu Skrill einrichten:

. Öffnen Sie das Menü *System » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
.  Klicken Sie auf *Skrill*. +
→ Das Tab *Schnittstelle* wird geöffnet.
.  Geben Sie die E-Mail-Adresse ein, wie von Skrill erhalten.
.  Geben Sie das Geheimwort ein, wie von Skrill erhalten.
. *Speichern* Sie die Einstellungen.

[#70]
==  Zahlungsarten aktivieren

Richten Sie die <<payment/zahlungsarten-verwalten#20, Zahlungsarten>> für Skrill im Tab *Einstellungen* der Zahlungsarten ein. Prüfen Sie zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[IMPORTANT]
.Zahlungsart nach Bestellung ändern
====
Die *Zahlungsart* ist nach der Bestellung im Bereich *Mein Konto* des Webshops nicht änderbar, solange auf die Bestätigung der Zahlung gewartet wird. Im Bereich *Mein Konto* wird dazu ein Hinweis angezeigt. Wenn die Zahlung abgelehnt wurde, kann die Zahlungsart geändert werden.
====
