= Alter Webshop: SOFORT Überweisung
:lang: de
include::{includedir}/_header.adoc[]
:keywords: sofort überweisung, Zahlungsart, sofortüberweisung, sofortueberweisung
:description: Payment in plentymarkets: Richten Sie die Schnittstelle zu SOFORT Überweisung in Ihrem plentymarkets System ein.
:position: 240

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *Sofortüberweisung.de* für Callisto Shops. Für die Verwendung von *Sofortüberweisung.de* in Ceres Shops erhalten Sie ausführliche Informationen in der Beschreibung des Plugins im link:https://marketplace.plentymarkets.com/plugins/payment/SOFORT_5050[plentyMarketplace^].
====

link:https://www.sofort.com/ger-DE/kaeufer/su/online-zahlen-mit-sofort-ueberweisung/[SOFORT Überweisung^] ist das Direkt-Überweisungsverfahren der SOFORT GmbH. Mit der Zahlungsart *SOFORT Überweisung* veranlasst der Kunde noch während der Bestellung die Überweisung in seinem Online-Banking-Konto. Sie als Händler erhalten nach Abschluss der Transaktion über SOFORT Überweisung eine Echtzeitbestätigung. So können Sie Lagerware und digitale Güter sofort versenden - der Kunde erhält seine Einkäufe schneller. Direkt nach dem Zahlungseingang wird die Bestellung in plentymarkets als bezahlt markiert.

SOFORT Überweisung entspricht den hohen Sicherheitsstandards des Online-Bankings und verfügt über TÜV-geprüften Datenschutz. Ihre Kunden müssen sich weder registrieren, noch benötigen sie eine Kreditkarte. Sie bezahlen einfach, sicher und schnell direkt mit ihrem Online-Bankkonto.

[#10]
== Wichtige Hinweise

Nach dem Abschluss der Bestellung wird dem Kunden ein Formular mit einem Button angezeigt. Durch Klick auf diesen Button wird der Kunde auf eine Seite von SOFORT Überweisung weitergeleitet, um dort die weiteren benötigten Angaben zu machen. Nach Eingabe und Bestätigung oder bei Abbruch wird der Kunde zurück in den Webshop geleitet.

In der Statushistorie von Aufträgen, die mit SOFORT Überweisung bezahlt wurden, wird nach erfolgreicher Bestellung eine Echtzeitbestätigung vermerkt und die Freigabe für den Versand erteilt. Die Überweisung wurde durch den Kunden bereits ausgeführt, der Betrag ist aber nicht direkt auf Ihrem Konto verbucht. In der Zahlungshistorie wird die Echtzeitbestätigung ebenfalls vermerkt. Wenn Sie <<payment/bankdaten-verwalten#70, EBICS>> eingerichtet haben, wird der Auftrag nach erfolgreichem Zahlungsimport automatisch als bezahlt markiert. Es wird ein zweiter Eintrag in der Zahlungshistorie erstellt. Wenn Sie kein EBICS verwenden, müssen Sie die <<payment/zahlungen-verwalten#40, Zahlung manuell buchen>>.

[#20]
== Bei SOFORT Überweisung registrieren

Um SOFORT Überweisung in plentymarkets einzurichten, benötigen Sie ein Konto bei link:https://www.sofortueberweisung.de/payment/createNew/go[SOFORT Überweisung^]. Nachdem Sie sich registriert haben, erhalten Sie die Zugangsdaten, die Sie für plentymarkets benötigen.

[#30]
== SOFORT Überweisung in Callisto einrichten

Beim Einrichten der Schnittstelle zu SOFORT Überweisung haben Sie die Möglichkeit entweder ein bestehendes Projekt von SOFORT Überweisung mit plentymarkets zu verknüpfen oder ein neues Projekt anzulegen.

[#40]
=== Bestehendes Projekt verknüpfen

Wenn Sie bei SOFORT Überweisung bereits ein Projekt angelegt haben, dann richten Sie zunächst die Schnittstelle zu SOFORT Überweisung in plentymarkets ein und nehmen anschließend Einstellungen im Admin-Bereich von SOFORT Überweisung vor, damit Zahlungseingänge von SOFORT Überweisung erfolgreich an plentymarkets übergeben werden.

[.instruction]
Schnittstelle zu SOFORT Überweisung einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
. Klicken Sie auf *Sofortüberweisung.de*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechseln Sie in das Tab *Schnittstelle*.
.  Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-sofort>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-schnittstelleneinrichtung-sofort]]
.Schnittstelle zu SOFORT Überweisung einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Kunden-Nr.; +
Projekt-Nr.; +
Projekt-Passwort; +
Benachrichtigungs-Passwort*
|Daten eingeben, wie von SOFORT Überweisung erhalten.

|*Verwendungszweck*
|Verwendungszweck wählen. +
*Kundennummer* = Ihre Kundennummer als Verwendungszweck für den Bezahlvorgang übermitteln. +
*Datum* = Datum des Bezahlvorgangs als Verwendungszweck für den Bezahlvorgang übermitteln. +
*Benutzerdefinierter Freitext* = In der folgenden Zeile einen Text eingeben, der als Verwendungszweck für den Bezahlvorgang übermittelt wird.
|*Benutzerdefinierter Freitext*
|Wenn unter *Verwendungszweck* die Option *Benutzerdefinierter Freitext* gewählt wurde, einen Text für die Anzeige des Verwendungszwecks eingeben.
|====

Damit Zahlungseingänge von SOFORT Überweisung erfolgreich an plentymarkets übergeben werden, müssen die folgenden Einstellungen im Admin-Bereich von SOFORT Überweisung in dem gewünschten Projekt vorgenommen werden:[#50]

* Erfolgslink für die Shopsystem-Schnittstelle eingeben: *https://-USER_VARIABLE_0-/?result=ok&amp;ak=-USER_VARIABLE_3_URLENCODE-&amp;id=-USER_VARIABLE_1_URLENCODE-*
* Abbruchlink für die Shopsystem-Schnittstelle eingeben: *https://-USER_VARIABLE_0-/?result=cancel&amp;ak=-USER_VARIABLE_3_URLENCODE-&amp;id=-USER_VARIABLE_1_URLENCODE-* +
→ Wenn Sie kein SSL nutzen, nur *http* eingeben.
* Automatische Weiterleitung aktivieren
* E-Mail-Benachrichtigung anlegen: *Ihre E-Mail-Adresse*
* HTTP-Benachrichtigung anlegen: *$IHRE_DOMAIN/plenty/api/payment_notification.php?payment=sofort_ueberweisung* +
→ Wenn vorhanden, SSL-Domain eingeben, damit sensible Daten über eine verschlüsselte Verbindung gesendet werden.
* Nicht mehr änderbare Eingabeparameter *Betrag* und *Verwendungszweck* aktivieren, damit diese im Zahlungsprozess von Ihren Kunden nicht mehr änderbar sind.
* Parameter *Kunden-Nr* (User_id), *Projekt-Nr* (Project_id), *Projektpasswort* und *Benachrichtigungskennwort* mit den Daten in plentymarkets abgleichen. Bei der Überprüfung der Einträge der Hash-Algorithmus *SHA1* wählen.

[#60]
=== Neues Projekt über plentymarkets anlegen

Auf *Neues Projekt* klicken, um ein neues Projekt einzurichten. Neue Projekte werden in plentymarkets oder im Account bei SOFORT Überweisung angelegt - die angelegten Projekte werden in beiden Fällen bei SOFORT Überweisung gespeichert. +
Wenn Projekte *manuell* bei SOFORT Überweisung angelegt werden, müssen die Daten noch in plentymarkets eingegeben werden.

[.instruction]
Neues Projekt anlegen:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Zahlung » Zahlungsarten*.
. Aktivieren Sie die Einstellung *Auch inaktive zeigen*.
. Öffnen Sie den Ordner *International*.
. Klicken Sie auf *Sofortüberweisung.de*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechseln Sie in das Tab *Schnittstelle*.
.  Klicken Sie auf *Neues Projekt*.
.  Geben Sie Ihre Daten ein. +
→ Pflichtfelder sind mit *** gekennzeichnet.
.  Geben Sie einen Projektnamen ein.
.  Klicken Sie auf *Einrichten*. +
→ Sie werden zu SOFORT Überweisung weitergeleitet. Folgen Sie dem Einrichtungsassistenten.

[#70]
== Zahlungsart aktivieren

Richten Sie die <<payment/zahlungsarten-verwalten#20, Zahlungsart>> Sofortüberweisung.de in Ihrem plentymarkets ein und aktivieren Sie die Zahlungsart. Sobald diese Einstellungen vorgenommen wurden, wird dem Endkunden auch bei der Zahlungsart *Überweisung / Vorkasse* in der Verkaufsabwicklung zusätzlich ein Button zur Zahlungsabwicklung von SOFORT Überweisung angeboten. Auf diese Weise hat der Endkunde die Wahl, entweder per Überweisung zu zahlen oder SOFORT Überweisung zu nutzen. Prüfen Sie zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#80]
== Testmodus aktivieren

SOFORT Überweisung bietet die Möglichkeit, testweise Transaktionen durchzuführen, um Benachrichtigungen etc. zu prüfen.

[.instruction]
Testtransaktion aus Ihrem Shopsystem durchführen:

. Loggen Sie sich bei SOFORT Überweisung ein.
. Öffnen Sie den Bereich *Meine Projekte*.
. Wählen Sie ein Projekt.
. Aktivieren Sie den *Testmodus*.
. *Speichern* Sie die Einstellungen.
. Führen Sie eine Bestellung mit der Zahlungsart SOFORT Überweisung in Ihrem Webshop durch.

[IMPORTANT]
.Richtige Bankleitzahl im Testmodus eingeben
====
Wenn Sie den Testmodus aktiviert haben, müssen Sie eine der folgenden Bankleitzahlen eingeben:

Deutschland: 88888888

Belgien: 999

Sonstige: 00000

Bei der Eingabe anderer Bankleitzahlen wird die Überweisung trotz Testmodus abgeschickt. Weitere Angaben wie die Kontonummer, PIN oder TAN können frei erfunden werden.
====

Wenn Sie den Test durchgeführt haben, deaktivieren Sie den Testmodus wieder.

[#90]
== Zahlungseingänge importieren

Zahlungen werden von SOFORT Überweisung so oft gesendet, bis sie erfolgreich in plentymarkets importiert sind. Zusätzlich besteht die Möglichkeit, in Ihrem Konto bei SOFORT Überweisung unter *Benachrichtigungen* (Fehlerhafte HTTP-Benachrichtigungen) den Status fehlerhafter Übertragungen einzusehen. Dort können Sie auch fehlerhafte Sendungen wiederholen.

[WARNING]
.Domainwechsel
====
Bei einem Domainwechsel müssen die <<payment/zahlungsanbieter/sofortueberweisung#50, Einstellungen>> bei SOFORT Überweisung im Backend angepasst werden - die URLs stimmen dann nicht mehr. Der Zahlungsablauf funktioniert weiterhin, aber die Zahlungen werden nicht mehr ins System importiert.
====
