= Alter Webshop: Wirecard
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Wirecard, Zahlungsart
:description: Payment in plentymarkets: Richte die Schnittstelle zu Wirecard in deinem plentymarkets System ein.
:position: 250
:url: payment/zahlungsanbieter/wirecard

[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *Wirecard* in Callisto Shops. Die folgenden Anleitungen sind somit nicht für Ceres Shops gültig!
====

Mit plentymarkets können Kreditkartenzahlungen über link:https://www.wirecard.at/[Wirecard^] abgewickelt werden. Die Abwicklung erfolgt über QENTA, das ist Österreichs marktführender Payment-Service-Provider (PSP) und dabei für die Zahlungsabwicklung im Internet für Unternehmen verantwortlich. QENTA gehört zum Wirecard-Konzern, der zu den führenden internationalen Anbietern elektronischer Zahlungs- und Risikomanagementlösungen gehört.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhältst du wichtige Hinweise zur Integration des Zahlungsanbieters Wirecard in plentymarkets.

[#20]
=== Bezahlvorgang

Für den Bezahlvorgang wird der Kunde zu Wirecard weitergeleitet und dort über ein iframe dazu aufgefordert, seine notwendigen Daten einzugeben. Die Auswahl der Zahlungsart erfolgt noch im Webshop. Anschließend wird der Kunde direkt zu Wirecard weitergeleitet und die weiteren Inhalte werden in einem iframe bereitgestellt. Der Kunde trägt hier seine Daten ein. Dies erfolgt somit nicht im Webshop, sondern bei Wirecard. Nach der Eingabe und Bestätigung der Daten wird der Kunde auf die Bestellbestätigungsseite geleitet.

[#30]
=== SSL-Zertifikat

Für die korrekte Verwendung der Zahlungsart ist ein <<basics/admin-aufgaben/plentymarkets-konto#ssl-zertifikat, SSL-Zertifikat>> erforderlich.

[WARNING]
.Fragen bei deiner Bank nach
====
Kläre vor einer Integration der Zahlungsart Wirecard, ob deine Bank die Abwicklung über iframes unterstützt.
====

[#40]
=== Verfügbare Wirecard-Zahlungsarten

Nachfolgend findest du eine Übersicht der für plentymarkets verfügbaren Wirecard-Zahlungsarten mit der System-ID in Klammern.

* *eps Online-Überweisung* (950)
* *Giropay* (990)
* *iDEAL* (980)
* *Kreditkarte* (910)
* *Lastschrift* (960)
* *MAESTRO* (800)
* *paybox* (930)
* *paysafecard* (940)
* *QUICK* (970)
* *Zahlungsauswahl auf der Wirecard-Bezahlseite* (900)

[#50]
== Bei Wirecard registrieren

Bevor du Wirecard in plentymarkets einrichten kannst, musst du dich zunächst bei link:http://www.wirecard.at/[Wirecard^] registrieren. Nachdem du ein Konto angelegt hast, erhältst du die Zugangsdaten, die du für plentymarkets benötigst.

[#60]
== Wirecard in Callisto einrichten

Gehe wie unten beschrieben vor, um die Schnittstelle zu Wirecard für deinen Callisto Shop in plentymarkets einzurichten.

[.instruction]
Schnittstelle zu Wirecard einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
.  Klicke auf *Wirecard*. +
→ Das Tab *Schnittstelle* wird geöffnet.
.  Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-wirecard>>.
. *Speichere* die Einstellungen.

[[tabelle-schnittstelleneinrichtung-wirecard]]
.Schnittstelle zu Wirecard einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Kundennummer*
|Kundennummer eingeben, wie von Wirecard erhalten. Die Kundennummer ist für die eindeutige Identifikation notwendig.

|*Secret Key*
|Eindeutigen Wirecard-Sicherheitsschlüssel eingeben, wie von Wirecard erhalten.

|*Shop-ID*
|Die Shop-ID ist die Kennung des plentymarkets Webshops, wenn mehrere Lizenzen unter einer Kundennummer verwendet werden. +
*Wichtig:* Gib die Shop-ID nur an, wenn sie von Wirecard ausdrücklich angefordert wird.

|*Iframe-Breite*; +
*Iframe-Höhe*
|Maße in Pixeln für Breite und Höhe des Iframe eingeben. Die Standardmaße des Iframe sind 450 x 450 Pixel.
|====

[#70]
== Zahlungsarten aktivieren

Richte die <<payment/zahlungsarten-verwalten#20, Zahlungsarten>> für Wirecard im Tab *Einstellungen* der Zahlungsarten ein. Prüfe zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#80]
== Weitere Einstellungsmöglichkeiten bei Wirecard

Zusätzlich zu den oben beschriebenen Einstellungen sind bei Wirecard weitere Konfigurationen möglich, z.B. die Integration weiterer Sprachen oder individuell gestaltbarer Templates.

[.subhead]
Sprachen

Standardmäßig sind bei Wirecard nur Deutsch und Englisch freigeschaltet. Du kannst aber weitere Sprachen auf Anfrage bei Wirecard integrieren. Wirecard unterstützt aktuell 26 Sprachen.

[.subhead]
Währungen

Beachten, dass standardmäßig nur eine Währung bei Wirecard freigeschaltet ist.

[.subhead]
ImageURL

Die Image-URL ist der Link zu deinem Logo, das auf den Seiten von Wirecard eingebunden wird. Hier wird automatisch das Bild aufgenommen, das du unter *Einrichtung » Aufträge » Zahlung » Zahlungsarten* im Tab *Einstellungen* bei den Wirecard-Zahlungsarten gespeichert haben. Empfohlen wird ein Logo mit einer Größe von 95 x 65 Pixeln.

[.subhead]
Wirecard Premium-Templates

Du kannst die Premium-Templates direkt bei Wirecard anfordern bzw. unter link:http://www2.wirecard.at/landingpage/checkoutpage-layoutanpassung/[http://www.wirecard.at^] herunterladen. Du kannst die Premium-Templates dann nach deinen Vorstellungen anpassen. Um deine geänderten Templates zu aktivieren, musst du die Templates an Wirecard übermitteln. Dort werden die Templates dann in deine Wirecard-Konfiguration integriert. Die Integration deiner angepassten Templates ist kostenpflichtig.
