= Alter Webshop: WorldPay
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Worldpay, Zahlungsart
:description: Payment in plentymarkets: Richte die Schnittstelle zu WorldPay in deinem plentymarkets System ein.
:position: 260
:url: payment/zahlungsanbieter/worldpay


[IMPORTANT]
.Einrichtung der Schnittstelle nur in Callisto Shops
====
Diese Handbuchseite beschreibt ausschließlich die Einrichtung der Schnittstelle *WorldPay* in Callisto Shops. Die folgenden Anleitungen sind somit nicht für Ceres Shops gültig!
====

WorldPay ist ein Zahlungsanbieter mit Sitzen in den USA und dem Vereinigten Königreich, der es dir als Online-Händler ermöglicht, Kartenzahlungen online entgegenzunehmen. Dies gilt sowohl für UK-Händler, die alle Services des Zahlungsanbieters nutzen können, als auch für deutsche Online-Händler, die das Angebot bis auf wenige Ausnahmen voll ausschöpfen können. Um zu wählen, welche Karten du für Zahlungen akzeptierst, setze dich bitte mit dem Support von WorldPay in Verbindung.

[#10]
== Wichtige Hinweise

In diesem Kapitel erhältst du wichtige Hinweise zur Integration des Zahlungsanbieters WorldPay in plentymarkets.

[.subhead]
Bezahlvorgang

Im Bestellvorgang kann dein Kunde wie gewohnt die Zahlungsart wählen. Entscheidet sich der Kunde für eine Zahlung über WorldPay, kann er oder sie in einem neuen Fenster die Art der Karte angeben und die Kartendaten eingeben. Eine Anmeldung bei WorldPay durch den Endkunden ist nicht nötig. Nach Authentifizierung der Daten wird der Kunde zurück in deinen Webshop geleitet.

[IMPORTANT]
.Corporate Gateway
====
Die Anbindung von WorldPay an plentymarkets erfolgt über die WorldPay-Schnittstelle und basiert auf dem Vertragsmodell *Corporate Gateway*. Die CardPay-Schnittstelle wird nicht unterstützt.
====

[#20]
== Bei WorldPay registrieren

Um WorldPay in deinem em Online-Shop als Zahlungsart zu integrieren, musst du dich zunächst bei WorldPay registrieren und ein Konto freischalten. Fülle dazu das link:https://secure.worldpay.com/app/[Worldpay-Anmeldeformular^] vollständig online aus und schicke es ab. Informationen zum weiteren Verlauf erhältst du per E-Mail von WorldPay. Nachdem WorldPay dein Anmeldeformular akzeptiert hat, erhältst du WorldPay-Zugangsdaten sowie einen Link zum Freischaltungsauftrag, den du dann unter Angabe deiner Webshop-URL online ausfüllen und an WorldPay übermitteln. Im Anschluss prüft WorldPay die Funktionalität der Zahlungsseite deines Webshops und schaltet dich dann zum Online-Handel auf den WorldPay-Systemen frei.

[#30]
== WorldPay in Callisto einrichten

Für die Einrichtung in plentymarkets benötigst du die Zugangsdaten, die im Händler-Backend von WorldPay im Menü *Profile* hinterlegt sind. Gehe wie unten beschrieben vor, um die Schnittstelle zu WorldPay für deinen Callisto Shop in plentymarkets einzurichten.

[.instruction]
Schnittstelle zu WorldPay einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Zahlung » Zahlungsarten*.
. Aktiviere die Einstellung *Auch inaktive zeigen*.
. Öffne den Ordner *International*.
.  Klicke auf *WorldPay*. +
→ Das Tab *Einstellungen* wird geöffnet.
. Wechsle in das Tab *Schnittstelle*.
.  Klappe den Mandanten auf.
.  Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-schnittstelleneinrichtung-worldpay>>.
. *Speichere* die Einstellungen.

[[tabelle-schnittstelleneinrichtung-worldpay]]
.Schnittstelle zu WorldPay einrichten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Admin-ID*
|Admin-ID eingeben, wie von WorldPay erhalten.

|*Merchant-ID*
|Merchant-ID eingeben, wie von WorldPay erhalten.

|*XML-Passwort*
|Passwort eingeben, wie im WorldPay-Backend im Menü Profile gespeichert.

|*Max order amount in GBP*
|Maximal möglichen Transaktionsbetrag in Britischen Pfund eingeben.

|*Testbetrieb aktivieren*
|Testbetrieb aktivieren, um die WorldPay-Funktionen zu testen, bevor mit dem System live gearbeitet wird.

2+|Mandant (Shop) - Optionen

|*Zugangsdaten für alle Mandanten (Shops) aktivieren*
|Nur sichtbar, wenn Mandanten eingerichtet sind. Aktivieren, um die Kontoeinstellungen, die über *Konto hinzufügen* für den Hauptshop gespeichert wurden, für alle Mandanten (Shops) zu übernehmen, unabhängig davon, was für andere Mandanten gespeichert wurde. Deaktivieren, um separate Zugangsdaten für weitere Mandanten (Shops) zu verwenden. Webshops, für die kein Konto hinzugefügt wurde, können mit WorldPay nicht genutzt werden. +
Zur Unterstützung mehrerer Mandanten muss im Menü <<webshop/webshop-einrichten#grundeinstellungen, Einrichtung » Mandant » Mandant wählen » Webshop » Einstellungen>> für die Option *Login* die Einstellung *Login in jedem einzelnen Shop ermöglichen* aktiviert sein.
|====

[#40]
== Zahlungsart aktivieren

Richte die <<payment/zahlungsarten-verwalten#20, Zahlungsart>> für WorldPay im Tab *Einstellungen* der Zahlungsart ein. Prüfe zudem die Einstellungen für *Erlaubte Zahlungsarten* in den <<payment/zahlungsarten-verwalten#30, Kundenklassen>> und für *Gesperrte Zahlungsarten* in den <<fulfillment/versand-vorbereiten#1000, Versandprofilen>>.

[#50]
== Einstellungen bei WorldPay vornehmen

In deinem Händler-Backend von WorldPay musst du noch einige wichtige Daten hinterlegen, damit die Schnittstelle funktioniert. Loggen dich dafür in dein Händlerkonto bei WorldPay ein und nimm folgende Einstellungen in deinem Profil unter *Händlerkanal* vor.

[#60]
=== Händlerkanal einrichten

Richte den Händlerkanal im Backend von WorldPay ein.

* Im Bereich *Händlerkanäle* in der Zeile *http* die Option *Ja* unter *Aktiv* wählen.
* Unter *Inhalt* die Option *cgi* aus der Dropdown-Liste wählen.
* Unter *Adresse* die plentymarkets-URL nach folgendem Muster eingeben: *http://*ihr-plentyshop.de*/plenty/api/payment_notification.php?payment=worldpay* +
→ "ihr-plentyshop.de" durch eigenen Shop ersetzen.
* Unter *Methode* die Option *POST* aus der Dropdown-Liste wählen.
* Auf *Einstellungen speichern* klicken.

[#70]
=== Datenaustausch mit plentymarkets einstellen

Ebenfalls unter *Händlerkanal* gibst du an, welche Informationen du über welchen Kanal von WorldPay erhalten möchten. Im Folgenden wird die empfohlene Variante für plentymarkets beschrieben, mit der die Daten direkt zu deinem System hinzugeführt werden.

* Im Bereich *Vorgänge Händlerkanäle* in der Zeile *http* die Optionen aktivieren, die an plentymarkets übertragen werden sollen.
* Auf *Einstellungen speichern* klicken.

[#80]
== Versandbestätigungen automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Versandbestätigungen automatisch zu versenden, nachdem der Warenausgang gebucht wurde. Durch die Versandbestätigung an WorldPay wird automatisch die Zahlung des Kunden von WorldPay an dich übertragen. Hierdurch ändert sich der Zahlungsstatus bei WorldPay von *authorised* zu *captured*.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 2.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 2 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Versandbestätigungen an WorldPay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Warenausgang gebucht*
|

|*Filter 1*
|*Auftrag &gt; Zahlungsart*
|*WorldPay*

|*Filter 2*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Aktion*
|*Versand &gt; Versandbestätigung an WorldPay senden*
|
|====

[#90]
== Stornierungen oder Gutschriften automatisch senden

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um WorldPay automatisch über Stornierungen oder Gutschriften zu informieren.

[TIP]
.Tipp: Ereignisaktion für zwei Ereignisse
====
Richte eine Ereignisaktion für zwei Ereignisse ein, da sich die Ereignisaktion dem Zahlungsstatus bei WorldPay anpasst. Befindet sich die Zahlung bei WorldPay noch im Status *authorised* (d.h. die Zahlung wurde noch nicht übermittelt), wird automatisch eine Stornierung versendet. Befindet sich die Zahlung bei WorldPay bereits im Status *captured* (d.h. die Zahlung wurde bereits übermittelt), wird automatisch eine Gutschrift versendet.
====

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 3.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 3 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen oder Gutschriften an WorldPay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für *stornierte Aufträge* wählen.

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*WorldPay*

|*Aktion*
|*Zahlungsarten &gt; Stornierung oder Gutschrift an WorldPay senden*
|
|====

[#100]
== Stornierungen automatisch senden

Alternativ zur vorherigen Ereignisaktion richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um WorldPay automatisch über Stornierungen zu informieren. Mit dieser Ereignisaktion kannst du eine Zahlung nur dann stornieren, wen du diese noch nicht mit der vorherigen Ereignisaktion eingeholt haben, also im Status *authorised* bei WorldPay. Richte anschließend eine zweite Ereignisaktion ein, um WorldPay automatisch über <<payment/zahlungsanbieter/worldpay#110, Gutschriften>> zu informieren.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 4.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 4 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Stornierungen an WorldPay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsänderung: Statuswechsel*
| Status für *stornierte Aufträge* wählen.

|*Filter 1*
|*Auftrag &gt; Auftragstyp*
|*Auftrag*

|*Filter 2*
|*Auftrag &gt; Zahlungsart*
|*WorldPay*

|*Aktion*
|*Zahlungsarten &gt; Stornierung an WorldPay senden*
|
|====

[#110]
== Gutschriften automatisch senden

Nachdem eine Zahlung von dir bei WorldPay bereits abgeholt wurde, dort also den Status *captured* erhalten hat, kannst du keine Stornierungen, sondern nur noch Gutschriften zurücksenden. Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, um Gutschriften automatisch an WorldPay zu senden.

[.collapseBox]
.Ereignisaktion einrichten
--
.  Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
.  Klicke auf *Ereignisaktion hinzufügen*. +
→ Das Fenster *Neue Ereignisaktion erstellen* wird geöffnet.
.  Gib einen Namen ein.
.  Wähle das *Ereignis* gemäß Tabelle 5.
. *Speichere* die Einstellungen.
.  Nimm die Einstellungen gemäß Tabelle 5 vor.
.  Setze ein Häkchen bei *Aktiv*.
. *Speichere* die Einstellungen.
--
.Ereignisaktion zum automatischen Senden von Gutschriften an WorldPay
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

|*Ereignis*
|*Auftragsanlage: Neue Gutschrift*
|

|*Filter*
|*Auftrag &gt; Zahlungsart*
|*WorldPay*

|*Aktion*
|*Zahlungsarten &gt; Gutschrift an WorldPay senden*
|
|====

[#120]
== Gutschriften manuell anlegen

Es kann notwendig werden, für einzelne Aufträge, die über WorldPay abgewickelt werden, Gutschriften manuell zu erstellen. Du hast hierfür die Möglichkeit, individuelle Gutschriftenbeträge an WorldPay zu melden. Gehe dazu wie nachfolgend beschrieben vor.

[.instruction]
Gutschrift an WorldPay senden:

. Öffne das Menü *Aufträge » Aufträge bearbeiten*.
. Öffne den WorldPay-Auftrag. +
→ Das Tab *Übersicht* wird geöffnet.
. Wähle die Option *anlegen* aus der Dropdown-Liste *Gutschrift ...*. +
→ Die Gutschrift wird angelegt.
. Öffne die neu angelegte *Gutschrift*.
. Wechsle in das Tab *Einstellungen*.
. Gib Betrag in das Feld *WorldPay Gutschrift senden* ein.
. Klicke auf *Gutschrift an WorldPay senden*. +
→ Die Gutschrift wird an WorldPay gesendet.
