= FBA-Service von Amazon nutzen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Amazon FBA, FBA, Amazon Multi-Channel, Amazon FBA Multi-Channel, Amazon FBA einrichten, FBA einrichten, Versand durch Amazon, Amazon versendet, Fulfillment by Amazon, Fulfilment by Amazon, Amazon Fulfilment, Amazon Fulfillment
:description: Multi-Channel in plentymarkets: Amazon versendet deine Ware mit Amazon FBA.
:position: 50
:url: maerkte/amazon/amazon-fba-nutzen
:id: VKWEAOP
:author: team-multi-channel

Das Kürzel FBA steht für Fulfillment by Amazon. Statt die Aufträge selbst zu bearbeiten, die Ware zu verpacken und zu versenden, überlässt du beim FBA-Programm Amazon diese Aufgabe. Natürlich musst du zumindest einen Teil deiner Waren dann auch bei Amazon einlagern. +

Weitere Informationen zu Amazon FBA und zur Einrichtung des Services in plentymarkets findest du in diesem Video-Tutorial:

.Amazon FBA
video::314732668[vimeo]

[#3300]
== FBA-Service von Amazon einrichten

[#3400]
== Lager für Amazon FBA anlegen

Im Menü *Einrichtung » Märkte » Amazon » Einstellungen* im Tab *Auftragseinstellungen* stellst du unter *Lager* u.a. ein, welches Lager für Amazon Fulfillment-Aufträge verwendet werden soll, damit die komplette Funktionalität der Warenwirtschaft auch beim FBA-Programm erhalten bleibt und du die Lagerbestände bei Amazon über dein plentymarkets System im Blick behältst.

[.instruction]
Lager anlegen:

. Öffne das Menü *Einrichtung » Waren » Lager*.
. Klicke auf *Neues Lager*.
. Gib einen Namen für das Lager ein.
. Wähle einen *Lagertyp*. +
→ *Hinweis:* Wenn du dieses Lager nur für FBA-Bestände verwenden möchtest, d.h. wenn du den Bestand dieses Lagers nur für Amazon FBA und nicht in deinem Webshop oder auf anderen Marktplätzen anbieten möchtest, wähle den Lagertyp *Reparatur*.
. Wähle als *Logistiktyp* die Option *Amazon*.
. *Speichere* (icon:save[role="green"]) die Einstellungen, um das Lager anzulegen. +
→ Das Lager wird alphabetisch sortiert unter Lager angezeigt und geöffnet.
. Nimm die weiteren Einstellungen gemäß der Erläuterungen auf der Handbuchseite <<warenwirtschaft/lager-einrichten#, Lager einrichten>> vor.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Ob die mit dem FBA-Service verbundenen Vorteile oder die Nachteile für deine persönliche Situation als Online-Händler überwiegen, kannst du nur selbst einschätzen. Wir möchten hier nur auf einige wichtige Punkte hinweisen:

*  Amazon bearbeitet Aufträge schnell und zuverlässig. Spitzenzeiten vor Weihnachten sind für den Shopbetreiber genauso problemlos wie das Sommerloch während der Urlaubszeit.
*  Dein Listing auf dem Marktplatz verbessert sich, d.h. du kannst mit höheren Verkaufszahlen rechnen.
*  Der FBA-Service ist mit Kosten verbunden, d.h. deine Brutto-Marge sinkt. Für einen umfassenden Vergleich der Kosten bedenke jedoch, dass im FBA-Service der Aufwand für die Lagerhaltung, das Auftragshandling, den Kundenservice etc. enthalten ist und du so von diesem Aufwand entlastet wirst.
*  Ware, die bei Amazon gelagert ist, kann in erster Linie auch nur dort angeboten werden. Für andere Marktplätze benötigst du gesonderte Warenbestände. Mit dem Service Multi-Channel-Fulfillment stellt Amazon jedoch auch eine Variante zur Verfügung, die deine Möglichkeiten diesbezüglich erweitert.
*  Du hast deutlich weniger Ärger mit nicht zustellbaren Sendungen oder verzögerten Auslieferungen. Pakete mit Amazon-Logo werden in der Regel bevorzugt behandelt.

[#3500]
== FBA-Auftragsimport

Gehe wie im Folgenden beschrieben vor, um einzustellen, dass deine FBA-Aufträge täglich automatisch in dein plentymarkets System importiert werden.

[.instruction]
FBA-Aufträge automatisch importieren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Wähle das Konto.
. Wechsele in das Tab *Auftragseinstellungen*.
. Aktiviere im Bereich *Amazon FBA* die Option *Aktiv*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

Die Auftragsbearbeitung hat folgenden Ablauf:

*  Der Kunde kauft bei Amazon.
*  Amazon verschickt die Ware.
*  Das plentymarkets System fordert einen Bericht an.
*  Amazon erstellt den Bericht.
*  Am nächsten Tag prüft plentymarkets automatisch, ob Berichte bei Amazon vorliegen. Wenn ja, werden die Berichte importiert.
*  Aus den Berichten werden in plentymarkets Aufträge erzeugt.

[IMPORTANT]
.Hinweis zum Auftragsimport
====
Amazon generiert die Berichte nur einmal täglich. Da Artikel nach bis zu 2 Tagen versendet werden, sind die FBA-Aufträge erst mit einer zeitlichen Verzögerung in deinem System verfügbar. Die von Amazon generierte Auftragsbestätigung ist in der Regel zwei Tage nach Versand der Ware, also insgesamt bis zu 4 Tage nach Bestellung der Ware durch den Käufer, in deinem System verfügbar. Die Lieferpünktlichkeit wird davon jedoch nicht berührt und erfolgt in der von Amazon gewohnten Schnelligkeit.
====

Amazon FBA-Aufträge werden mit den Parametern *Status* und *Herkunft* importiert. Für die Option *Status* legst du den für deinen Prozess passenden Status fest, also zum Beispiel *[7] Warenausgang gebucht*. Die Herkunft wird automatisch auf Amazon FBA oder eine Amazon FBA-Unterherkunft, wie z.B. Amazon FBA USA, gesetzt. Der Warenausgang wird hier in plentymarkets direkt gebucht, so dass keine Reservierung des Bestands der enthaltenen Artikelpositionen stattfindet.

[TIP]
.Ereignisaktionen für Fulfillment
====
Lege die für den Fulfillment-Prozess nötigen Ereignisaktionen an, um eine Rechnung zu erzeugen und per E-Mail automatisch an den Käufer zu senden sowie den Auftrag dann in einen weiteren Status zu setzen. +
Beachte dazu die Handbuchseiten <<automatisierung/ereignisaktionen#, Ereignisaktionen>> sowie <<fulfillment#, Standard-Fulfillment im Detail>>.
====

[discrete]
===== FBA-Teillieferungen

Amazon FBA-Teillieferungen werden von Amazon veranlasst, wenn sich die von Amazon im Kundenauftrag versendete Ware in unterschiedlichen Amazon-Lagern befindet.
Bei den Kund*innen kommen nach Bestellung demzufolge mehrere Pakete zu einem getätigten Auftrag an. +
In plentymarkets wird jede FBA-Teillieferung anhand des versendenden FBA-Lagers als separater Auftrag im System angelegt. Pro Teillieferung kann eine Sendungsnummer von Amazon importiert und der jeweiligen Teillieferung zugeordnet werden. Pro Teillieferung kann eine separate Rechnung erzeugt werden, was aufgrund der unterschiedlichen zu berechnenden Steuern erforderlich ist, wenn die Amazon-Lager in unterschiedlichen Ländern liegen.

[discrete]
===== Europäisches Versandnetzwerk

Amazon erweitert kontinuierlich das europäische Versandnetzwerk für Händler, die Versand durch Amazon nutzen. Eine Voraussetzung ist, dass du in allen Ländern, in denen du FBA-Logistikzentren nutzt, steuerrechtlich registriert sind. Damit für diese neuen Logistikzentren deine Rechnungen auch steuerlich korrekt erstellt werden, kannst du neben deinem Firmensitz im Menü *Einrichtung » Mandant » Mandant wählen » Standorte » Standort wählen » Buchhaltung* den Lagerstandort als Basis für den Standard-Umsatzsteuersatz wählen und das individuell für jeden deiner Mandanten (Shops). Im gleichen Menü im Tab *Umsatzsteuersätze* erfässt du auch die notwendigen Steuersätze für die Länder.

[TIP]
.Beispiel: Logistikzentrum in Polen mit Versand nach Deutschland
====
Damit für Aufträge, die von einem Logistikzentrum in Polen nach Deutschland verschickt werden, nicht der polnische Steuersatz verwendet wird, muss für den Standort Polen zusätzlich das Land Deutschland mit dem deutschen Steuersatz eingetragen werden. Wähle dafür im Menü *Einrichtung » Mandant » Mandant wählen » Standorte » Polen » Buchhaltung » Tab: Umsatzsteuersätze* das Land *Deutschland* und trage den deutschen Steuersatz sowie die gültige USt-IdNr. ein.
====

[#3600]
== FBA-Retouren automatisch importieren

Im Retourenfall sendet der Käufer die Ware zurück an Amazon. Die Retoure wird in dein plentymarkets System importiert und mit dem Retourenstatus, den du im Menü *Einrichtung » Aufträge » Einstellungen* gewählt hast, im Auftragsmenü angelegt.

[IMPORTANT]
.Auftrag nicht ändern
====
Retouren werden nur importiert, wenn der Auftrag mit unveränderter externer Auftragsnummer in plentymarkets vorliegt.
====

Aktiviere wie im Folgenden beschrieben die Importfunktion, um FBA-Retouren automatisch in dein plentymarkets System zu importieren.

[.instruction]
Importfunktion für FBA-Retouren aktivieren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Öffne das Amazon-Konto.
. Wechsele in das Tab *Auftragseinstellungen*.
. Wähle im Bereich *Versand durch Amazon (FBA)* für die Einstellung *Retourenimport* die Option *Täglich*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#3650]
== FBA-Gutschriften automatisch importieren

Nutze den Gutschriftenimport, um FBA-Gutschriften automatisch in dein plentymarkets System zu importieren. Die Gutschriften werden mit dem Status importiert, der unter *Einrichtung » Aufträge » Einstellungen* für die Einstellung *Standard-Status Gutschrift* gewählt wurde. Wenn der Gutschriftenimport aktiviert ist, werden FBA-Gutschriften alle 4 Stunden importiert.

[IMPORTANT]
.FBA-Retouren nicht per Ereignisaktion als Gutschriften anlegen
====
Wenn du den Gutschriftenimport aktivierst, werden FBA-Gutschriften automatisch alle 4 Stunden in dein plentymarkets System importiert. Verwende deshalb in diesem Fall keine Ereignisaktion, um FBA-Retouren als Auftragstyp *Gutschrift* anzulegen.
====

[.instruction]
Automatischen Gutschriftenimport aktivieren:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Öffne das Amazon-Konto.
. Wechsele in das Tab *Auftragseinstellungen*.
. Wähle *Ja* für die Option *Gutschriftenimport*.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#3700]
== Amazon Multi-Channel einrichten

Amazon Multi-Channel bedeutet, dass "Lieferungen im Auftrag des Verkäufers durch Amazon verschickt werden, für Bestellungen, die nicht bei Amazon.de aufgegeben wurden, sondern z.B. auf eBay oder auf der persönlichen Website eines Verkäufers." (Quelle: Amazon)

Die Multi-Channel-Funktion ermöglicht dir also, Artikel bei Amazon zu lagern und von Amazon verschicken zu lassen, die du nicht bei Amazon, sondern auf anderen externen Marktplätzen verkaufst. Du erfährst in diesem Kapitel, welche Einstellungen du in deinem plentymarkets System vornehmen musst, damit diese Aufträge über Amazon abgewickelt werden können.

Die folgenden Schritte sind nötig, um deine Bestandsverwaltung und Artikeldaten für Amazon Multi-Channel einzurichten.

Weitere Informationen zu Amazon Multi-Channel und zur Einrichtung des Services in deinem plentymarkets System findest du in diesem Video-Tutorial:

.Amazon FBA
video::314735384[vimeo]

[#3800]
=== Lager für Amazon Multi-Channel anlegen

Lege ein Lager an, falls du noch kein Lager wie im Kapitel <<FBA-Service von Amazon nutzen, FBA-Service von Amazon nutzen>> beschrieben angelegt hast. Wichtig beim Multi-Channel-Versand ist, dass du für jeden landesspezifischen Amazon-Markt ein eigenes Lager mit dem Logistiktyp *Amazon* und das Land als Standort in plentymarkets eingerichtet hast.

[IMPORTANT]
.Beispiel für die Übereinstimmung von Amazon-Plattform und Lagerstandort
====
Beim Multi-Channel-Versand über amazon.co.uk muss ein eigenes Lager Amazon UK mit dem Logistiktyp *Amazon* und dem Standort Großbritannien angelegt werden. Die Ware muss also auch tatsächlich vor Ort bei Amazon z.B. in Großbritannien gelagert sein, da sonst keine Versandabwicklung über amazon.co.uk stattfinden kann.
====

[#3900]
=== Variantenverfügbarkeit für Amazon Multi-Channel einstellen

Nimm die im Folgenden beschriebenen Einstellungen an den Artikeln vor, die du für Amazon Multi-Channel verfügbar machen möchtest.

[.instruction]
Variantenverfügbarkeit für Amazon Multi-Channel einstellen:

. Öffne das Menü *Artikel » Artikel bearbeiten*.
. Öffne den Artikel.
. Wechsele in das Tab *Multi-Channel*.
. Nimm die Einstellungen im Bereich *Amazon* vor. Beachte dazu die Erläuterungen in <<artikelverfügbarkeit-amazon>> im Kapitel <<maerkte/amazon/amazon-einrichten#700, Variantenverfügbarkeit einstellen>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#4000]
=== Einstellungen für Amazon Multi-Channel vornehmen

Nimm die im Folgenden beschriebenen Einstellungen im Menü für Amazon vor.

[.instruction]
Amazon Multi-Channel einrichten:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Einstellungen*.
. Wechsele in das Tab *Auftragseinstellungen*.
. Nimm die Einstellungen im Bereich *Versand durch Amazon (FBA)* vor. Beachte dazu die Erläuterungen in <<#amazon-multi-channel>>.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[[amazon-multi-channel]]
.Amazon Multi-Channel einrichten
[cols="1,3"]
|====
| Einstellung | Erläuterung

| *Aktiv*
| Häkchen setzen, um den täglichen Auftragsimport zu aktivieren.

| *Herkunft*
| *Nur für Aufträge von Amazon verwenden* = Nur Aufträge von Amazon mit FBA abwickeln. +
*Für alle Aufträge verwendbar* = Alle Aufträge mit FBA abwickeln.

| *Status*
|<<auftraege/auftraege-verwalten#1200, Status>> der Aufträge wählen, die von Amazon importiert wurden.

| *Lager*
| Wählen, welches <<Lager für Amazon FBA anlegen, Lager>> für den Versand durch Amazon verwendet werden soll.

| *Warenausgang*
| Wählen, ob der Warenausgang als gebucht markiert werden soll oder nicht. Die Option *Als gebucht markieren* erzeugt keine Warenbewegung. Um eine Warenbewegung zu erzeugen, muss die Option *Nicht als gebucht markieren* eingestellt sein und eine Ereignisaktion eingerichtet werden.

| *Retourenimport*
|Wählen, ob Retouren *Nie* oder *Täglich* importiert werden sollen.

| *Gutschein bei Retouren berücksichtigen*
|Wählen, ob Gutscheine bei FBA-Retouren berücksichtigt werden sollen oder nicht. Wurde der FBA-Auftrag komplett oder teilweise mit einem Gutschein beglichen, wird der Gutschein bei der Retoure hinzugefügt und verrechnet. Dabei wird kein Mindestbestellwert für den Gutschein berücksichtigt.

| *Bestandsimport*
| Option *Stündlich* wählen, damit der Bestand importiert wird. +
Dabei werden nur Änderungen der Bestandsdaten berücksichtigt. Weitere Möglichkeiten zum Bestandsimport sind in Kapitel <<Bestand abgleichen, Bestand abgleichen>> beschrieben.

| *Status für übertragene Aufträge*
| Bestimmt den Auftragsstatus für Multi-Channel FBA Aufträge, die erfolgreich an FBA übertragen wurden.

| *Artikelpakete Multichannel*
| Wählen, welche Positionen an Amazon übertragen werden sollen. +
*Alle Auftragspositionen übertragen* = Alle Positionen, die sich im Auftrag befinden, an Amazon übertragen. Wenn diese Option gewählt wird, werden die Paketposition und die Paketbestandteile an Amazon übertragen. +
*Nur Paketposition übertragen* = Nur die Paketposition wird an Amazon übertragen. +
*Ohne Paketposition übertragen* = Nur die Paketbestandteile werden an Amazon übertragen.

| *Versandkategorie*
| Versandkategorie wählen. +
*Standard* = Normaler Versand +
*Expedited* = Schnellversand +
*Priority* = Bevorzugt (schnellster Versand)
|====

[#4100]
=== FBA-Versandfreigabe automatisch erteilen

Richte eine <<automatisierung/ereignisaktionen#, Ereignisaktion>> ein, damit Amazon automatisch eine Meldung über den Auftrag erhält und den Auftrag bearbeiten sowie den Versand veranlassen kann.

:table-event-procedure: <<#ereignisaktion-fba-versandfreigabe>>

include::../../_includes/textblocks/instructions/EA.adoc[]

[[ereignisaktion-fba-versandfreigabe]]
.Ereignisaktion zum automatischen Erteilen von FBA-Versandfreigaben an Amazon
[cols="1,3,3"]
|====
| Einstellung | Option | Auswahl

| *Ereignis*
| *Auftragsänderung: Statuswechsel &gt; [5] Freigabe Versand*
|

| *Filter 1*
| *Auftrag &gt; Auftragslager*
| *Amazon Multi-Channel*

| *Filter 2*
| *Versand &gt; Versand ausschließlich durch FBA*
|

| *Filter 3*
| *Auftrag &gt; Herkunft*
| *Wichtig:* Keine Amazon-Herkunft wählen, da es sonst zu Doppelungen bei FBA-Aufträgen kommen kann.

| *Aktion*
| *Versand &gt; FBA-Versandfreigabe erteilen*
|
|====

Bei Wechsel in Status 5 wird Amazon mit der Ereignisaktion darüber informiert, dass die Ware zum Versand freigegeben ist. Amazon verschickt die Ware und das plentymarkets System erhält intern eine Bestätigung von Amazon. Der Auftrag wechselt in Status 5.1, wie in den <<Auftragseinstellungen vornehmen, Auftragseinstellungen>> festgelegt. Die Paketnummer wird in dein plentymarkets System importiert.

[TIP]
.Import von Paketnummern
====
Paketnummern werden einmal täglich importiert.
====

[#2400]
=== Bestand für Amazon Multi-Channel abgleichen

Im Menü *Einrichtung » Märkte » Amazon » Datenaustausch » FBA-Warenbestand* hast du die Möglichkeit, neben dem stündlichen automatischen Bestandsabgleich mit Amazon deinen Bestand mit einer automatischen Aktion oder per CSV-Datei abzugleichen.

[IMPORTANT]
.Nur für Amazon Multi-Channel
====
Dieses Feature ist nur für <<Amazon Multi-Channel einrichten, Amazon Multi-Channel>> vorgesehen.
====

In plentymarkets wird zwischen einem automatischen Bestandsabgleich und einem manuellen Bestandsabgleich unterschieden. Beide Verfahren werden folgend beschrieben.


[.tabs]
====
Bestand automatisch abgleichen::
+
--
Gehe wie im Folgenden beschrieben vor, um einen automatischen Bestandsabgleich durchzuführen.

[.instruction]
Bestand automatisch abgleichen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Datenaustausch » FBA-Warenbestand*.
. Wähle im Tab *Automatisch* das Amazon-Konto.
. Klicke auf *Amazon FBA-Bestand synchronisieren*.

Für den Prozess ist eine Zeitspanne von 4 Minuten vorgesehen. Werden die Daten nicht innerhalb dieser Zeitspanne von Amazon zur Verfügung gestellt, dann werden die Bestände nicht abgeglichen. Bei der nächsten Anforderung werden dann die vorher nicht übertragenen Daten verwendet, was zu Fehlern führen kann. Daher ist ein manueller Abgleich per CSV-Datei zu empfehlen wie im folgenden Kapitel beschrieben.

Es werden nur Bestände von Artikeln übernommen, die in den letzten 30 Tagen eine Bestandsänderung auf Amazon erfahren haben. Für den Erstimport empfehlen wir dir den manuellen Abgleich. Die Warenbestände werden gemäß der <<Basiseinstellungen vornehmen, Grundeinstellungen>> abgeglichen.
--

Bestand manuell abgleichen::
+
--
Bestände werden manuell per CSV-Datei abgeglichen.


[IMPORTANT]
.SKU-Zuordnung
======
Für den manuellen Bestandsabgleich muss die SKU-Zuordnung in den <<maerkte/amazon/amazon-einrichten#400, Grundeinstellungen>> eingetragen werden.
======


Bevor du diesen Abgleich durchführst, musst du bei Amazon in der Seller Central die entsprechende Berichtsdatei anfordern, herunterladen und die CSV-Datei auf deinem Rechner speichern.

[.instruction]
Bestand manuell abgleichen:

. Öffne das Menü *Einrichtung » Märkte » Amazon » Datenaustausch » FBA Warenbestand*.
. Wechsele in das Tab *Manuell*.
. Wähle das Amazon-Konto.
. Klicke auf *Datei auswählen*, um die soeben gespeicherte CSV-Datei zu wählen.
. *Speichere* (icon:save[role="green"]) die Einstellungen, um den Abgleich durchzuführen.
--
====
