= CLC
:lang: de
include::{includedir}/_header.adoc[]
:keywords: CLC, China Logistic Center
:description: Erfahre, wie du CLC in plentymarkets einrichtest.
:position: 37
:url: fulfillment/clc
:id: 0PI6NSM
:author: team-fulfillment

[IMPORTANT]
.CLC-Plugin herunterladen
====
Die Schnittstelle zu CLC wird über ein Plugin integriert. Um das CLC-Plugin nutzen zu können, lade das Plugin im link:https://marketplace.plentymarkets.com/clc_7017[plentyMarketplace^]{nbsp}icon:external-link[] herunter.
====

[#bei-clc-registrieren]
== Bei CLC registrieren

Um die Schnittstelle für CLC in deinem plentymarkets System einzurichten, musst du bei link:https://www.tietjegroup.com/kontakt/[CLC^]{nbsp}icon:external-link[] registriert sein. Schreibe einfach eine E-Mail an mailto:email[kontakt@clc.tietjegroup.com].

Du erhältst dann von CLC die Daten, die du für die Einstellungen in plentymarkets benötigst.

[#clc-einrichten]
== CLC in plentymarkets einrichten

Die Schnittstelle zu CLC wird über ein Plugin integriert. Um das CLC-Plugin nutzen können, lade das Plugin im link:https://marketplace.plentymarkets.com/clc_7017[plentyMarketplace^]{nbsp}icon:external-link[] herunter.

Sobald du das <<plugins/hinzugefuegte-plugins-installieren#plugin-installieren, Plugin in einem Plugin-Set installiert>> hast, steht dir zum einfachen Einrichten der *CLC Assistent* im Menü *Einrichtung » Assistenten » Plugins* im relevanten Plugin-Set zur Verfügung.

[discrete]
=== Import von Warenbeständen

[IMPORTANT]
.Import von Warenbeständen
====
Die Warenbestände werden automatisch importiert. Den Import übernehmen Cron-Jobs. Cron-Jobs sind Prozesse, die in bestimmten Zeitintervallen automatisch ausgeführt werden.

Es gibt 2 Importtypen von Warenbeständen:

* Vollständiger Bestandsimport
* Bestandsabgleichsimport

Der vollständige Bestandsimport wird jeden Tag ausgeführt und überschreibt den Warenbestand aller Varianten mit einem absoluten Wert.

Der Bestandsabgleich hingegen nimmt eine relative Korrektur der verknüpften Varianten vor.

Beide Prozesse importieren CSV-Dateien von einem FTP-Server. Daher ist die erfolgreiche Verbindung zu diesem FTP-Server zwingend notwendig, damit die Prozesse erfolgreich ausgeführt werden können. Die Zugangsdaten gibst du im *CLC Assistenten* im Schritt <<#zugangsdaten, Zugangsdaten>> ein.

Die Cron-Jobs laufen automatisch, sobald du das Plugin installiert und es in einem Plugin-Set gespeichert und bereitgestellt hast. Das manuelle Auslösen der Prozesse ist demnach _nicht_ notwendig. Die einzige Voraussetzung ist die erfolgreiche Verbindung zum FTP-Server mit gültigen FTP-Daten.
====

[discrete]
=== Artikelexport

[IMPORTANT]
.Artikelexport
====
Damit all deine Artikeldaten von plentymarkets zu CLC exportiert werden können, müssen die folgenden Bedingungen erfüllt sein:

* der erste Barcode, der an der Variante gespeichert ist, muss vom Typ *GTIN 13* sein
* im Tab *Verfügbarkeit* der Variante müssen unter *Märkte* die selben Marktplätze gewählt sein, die auch in den Plugin-Einstellungen für die Herkunft aktiviert wurden
* das Änderungsdatum der Variante darf nicht länger als 25 Stunden zurückliegen
====

[#assistent-durchlaufen]
== CLC Assistent durchlaufen

Sobald du das <<plugins/hinzugefuegte-plugins-installieren#plugin-installieren, Plugin in einem Plugin-Set installiert>> hast, ist der *CLC Assistent* im Menü *Einrichtung » Assistenten » Plugins* im relevanten Plugin-Set verfügbar. Im Folgenden werden die einzelnen Schritte, die du im *CLC Assistenten* durchläufst, beschrieben.

[#zugangsdaten]
=== Zugangsdaten

Um eine Verbindung zwischen dem Plugin und dem von CLC bereitgestellten FTP-Server herzustellen, musst du alle Felder im Schritt *Zugangsdaten* ausfüllen.

[[table-save-login-details]]
.Zugangsdaten speichern
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Host*
|FTP-Adresse (beinhaltet nicht den Port) eingeben. +
*_Beispiel:_* `ftp.clc.example.com`

| *Port*
|FTP-Port eingeben, der in Kombination mit dem Host verwendet wird, um die Verbindungsadresse korrekt einzurichten. +
*_Beispiel:_* `990`

| *Benutzername*
|Benutzernamen für das FTP-Konto eingeben.

| *Passwort*
|Passwort für das FTP-Konto eingeben.

|====

[#dokumentenxport]
=== Dokumentenexport

Die CSV-Dateien enthalten zusätzliche Versandinformationen wie Versanddienstleister und Auftrags-ID und werden zu einem FTP-Server exportiert. Der Export erfolgt über eine <<#ereignisaktion-dokumentenxport, Ereignisaktion>>, die weiter unten beschrieben wird.

Nicht nur CSV-Dateien können exportiert werden, sondern auch PDF-Dokumente wie Rechnungen und Versandlabels. Im Schritt *Dokumentenexport* speicherst du die IDs der Auftragsherkünfte, für die du zusätzlich die Rechnung, den Lieferschein und das Versandlabel exportieren möchtest.

[NOTE]
Wenn du als Herkunft jeweils `-1` eingibst, wird der entsprechende Dokumententyp unabhängig von der Auftragsherkunft exportiert.

Du kannst diesen Prozess automatisieren, indem du eine <<#ereignisaktion-dokumentenxport, Ereignisaktion>> einrichtest. Wie du dazu vorgehst, ist im Folgenden beschrieben. Wenn die Ereignisaktion ausgelöst wird, werden die Dokumente für Aufträge mit den Herkünften, die du in deinem plentymarkets System gespeichert hast, exportiert.
Wenn das System keine erlaubte Herkunft findet, werden die Dokumente nicht exportiert. Dies betrifft auch den Auftragsexport.

[#ereignisaktion-dokumentenxport]
==== Ereignisaktion für den Dokumentenexport einrichten

Richte eine Ereignisaktion ein, um die Dokumente mit den zusätzlichen Versandinformationen zu exportieren. Gehe wie im Folgenden beschrieben vor.

[.instruction]
Ereignisaktion einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]), um eine neue Ereignisaktion zu erstellen. +
→ Ein Bearbeitungsfenster öffnet sich.
. Gib einen *Namen* für die Ereignisaktion ein, z.B. `CLC Additional Shipping Details`.
. Wähle das Auftragsereignis *Auftragsänderung > Statuswechsel*. +
*_Hinweis:_* Wir empfehlen das Ereignis *Statuswechsel*. Du kannst jedoch jedes andere beliebige Ereignis wählen, solange es sich um ein auftragsrelevantes Ereignis handelt.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#ereignisaktion-mit-plugin-verknuepfen]
==== Ereignisaktion mit dem Plugin verknüpfen

Damit das CLC Plugin auf die Ereignisaktion reagieren kann, musst du die Ereignisaktion mit dem Plugin verknüpfen. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Ereignisaktion mit dem CLC Plugin verknüpfen:

. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf die Ereignisaktion für die zusätzlichen Versandinformationen, die du gerade erstellt hast.
. Klicke auf *Aktion hinzufügen* (icon:plus-square[role="green"]) auf der rechten Seite des Bildschirms.
. Wähle die Einstellung *Plugins > CLC Additional Shipping Details Export*.
. Klicke auf *Hinzufügen*.
. Wähle im oberen Bereich der Ereignisaktion die Einstellung *Aktiv*, um die Ereignisaktion zu aktivieren.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#artikeleigenschaften]
=== Artikeleigenschaften

Sofern du dies noch nicht getan hast: <<#artikeleigenschaft-erstellen, Erstelle>> zunächst eine Artikeleigenschaft im plentymarkets Backend und verknüpfe dann die Eigenschaft über den Assistenten mit dem CLC Plugin, um sicherzustellen, dass der Auftragsexport korrekt funktioniert.

[TIP]
.Keine Artikeleigenschaft? Variantennummer wird an CLC übermittelt
====
Wenn du keine Artikeleigenschaft erstellst und diese nicht über den Assistenten mit dem Plugin verknüpfst, übermittelt dein plentymarkets System die Variantennummer als Paketcode an CLC.
====






[#artikeleigenschaft-erstellen]
[discrete]
==== Artikeleigenschaft erstellen

Öffne in deinem plentymarkets Backend das Menü *Einrichtung » Einstellungen » Eigenschaften » Konfiguration* und erstelle eine Eigenschaft für den Bereich *Artikel* vom Eigenschaftstyp *Text*. Alle anderen Einstellungen in diesem Schritt sind optional.
Weitere Informationen zu Eigenschaften findest du auf der Artikel-Handbuchseite <<artikel/einstellungen/eigenschaften#500, Merkmale und Eigenschaften>>.

Anschließend musst du die Eigenschafts-ID im Assistenten verknüpfen, damit der Auftragsexport korrekt funktioniert. Das Feld *Eigenschafts-ID für Paketcode* im Assistentenschritt *Artikeleigenschaften* wird für Auftragspositionen im Auftragsexport verwendet.






[#auftragseigenschaften]
=== Auftragseigenschaften

Wenn du beispielsweise das Programm *Prime by Seller* verwendest, wird diese Information in der Auftragseigenschaft des Auftrags gespeichert. Diese Eigenschaft wird an CLC übermittelt, damit CLC weiß, dass es sich um einen Prime-Auftrag handelt.

Das Feld *Eigenschafts-ID für Treueprogramm* wird für die Ermittlung des Treueprogramms verwendet. Dieses Feld wird automatisch befüllt. Die folgenden Werte sind verfügbar:

* DEFAULT
* ebay_plus
* Amazon_NextDay
* Amazon_SecondDay
* Amazon_Prime
* Amazon_Prime_NextDay
* Amazon_Prime_SecondDay
* Amazon_SameDay
* Amazon_Prime_SameDay

[#plugin-einstellungen]
=== Plugin-Einstellungen

Im Schritt *Plugin-Einstellungen* nimmst du einige allgemeine Einstellungen für das Plugin vor.


[[table-general-settings]]
.Allgemeine Einstellungen vornehmen
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Barcode-ID*
|ID des Barcodes eingeben, die beim Artikeldatenexport an CLC übertragen werden soll. Barcodes können im Menü *Einrichtung » Artikel » Barcode* erstellt werden. Jeder Barcode hat eine eindeutige ID und kann vom Plugin verwendet werden. +
Weitere Informationen findest du auf der Handbuchseite  <<artikel/einstellungen/barcodes#100, Barcodes und Etiketten>>.

| *Lager-ID*
|ID des Lagers eingeben, das für die Übertragung der Warenbestände von CLC genutzt werden soll.

| *Herkunft*
|ID der Herkunft eingeben, die die Aufträge für CLC kennzeichnet.

|====



[#status-versandbereit]
=== Status “Versandbereit”

Der Cron-Job *Versandbereit* führt täglich einen Datenimport vom FTP-Server aus. Dieser Cron-Job importiert die Amazon-Eigenschaften ASN und ARN. Du musst die IDs der Eigenschaften dann lediglich im Menü *Status „Versandbereit“* speichern.

*_Hinweis:_* Du musst die IDs _nicht_ eingeben, wenn du einen einfachen Import ausführen möchtest, der keine ASN- und ARN-Werte enthält. 

[IMPORTANT]
.Eigenschaft für Shipment ID
====
Das Feld *Eigenschaft für Shipment ID* wird automatisch befüllt, nachdem das Plugin erfolgreich installiert wurde. Das Ändern des Werts dieser Eigenschaft wird _nicht_ empfohlen. Wenn die *Eigenschaft für Shipment ID* nicht korrekt gesetzt ist, kann dies dazu führen, dass der *Ready for Dispatch*-Cron-Job keine erfolgreichen Ergebnisse liefert.
====

[#status-warenausgang]
=== Status für Warenausgang

Die *Status-ID* ist ein Pflichtfeld. Die ID wird verwendet, um den Status der Aufträge zu setzen. Sobald CLC den Auftrag ausgeführt hat, wird der Auftrag automatisch in den Status gesetzt, den du in diesem Schritt speicherst.

*_Hinweis:_* Üblicherweise sollte der Status, den du hier speicherst, gleich oder größer als 7 sein, z.B. _[7.1] Versand CLC_. Wenn du einen eigenen Status für CLC Aufträge erstellen möchtest, öffne das Menü *Einrichtung » Aufträge » Status*.

Weitere Informationen zum Auftragsstatus findest du auf der Handbuchseite <<auftraege/auftraege-verwalten#1200, Aufträge verwalten>>.

[discrete]
==== Ereignisaktion für den automatischen Warenausgang einrichten

Wenn du möchtest, dass der Warenausgang automatisch gebucht wird, sobald sich ein Auftrag in Status _[7.1] Versand CLC_ befindet, richte dir eine Ereignisaktion ein.

[.instruction]
Ereignisaktion für den automatischen Warenausgang einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]), um eine neue Ereignisaktion zu erstellen. +
→ Ein Bearbeitungsfenster öffnet sich.
. Gib einen *Namen* für die Ereignisaktion ein, z.B. `CLC Warenausgang buchen`.
. Wähle das Auftragsereignis *Auftragsänderung > Statuswechsel*.
. Wähle aus der Dropdown-Liste den passenden Status, z.B. _[7.1] Versand CLC_.
. Klicke auf *Aktion hinzufügen* (icon:plus-square[role="green"]).
. Wähle die Aktion *Auftrag > Warenausgang buchen*.
. Klicke auf *Hinzufügen*.
. Wähle die Einstellung *Aktiv*, um die Ereignisaktion zu aktivieren.
. *Speichere* (icon:save[role="green"]) die Einstellungen.

[#versandprofilkonfiguration]
=== Versandprofilkonfiguration

In diesem Schritt wählst du das Versandprofil und die Versandart (Paket oder Spedition) und gibst das Treueprogramm und deine Kundennummer ein. Außerdem kannst du die Optionen aktivieren, dass ein Retourenlabel erzeugt wird und dass die Auftrags-ID mit Suffix an CLC übertragen wird.

// weiter oben bei Auftragseigenschaften steht auch noch was mit Treueprogramm --> prüfen!


[#artikelexport-einstellungen]
=== Artikelexport-Einstellungen

In diesem Schritt wählst du das Identifikationsmerkmal, anhand dessen die Artikel zu CLC exportiert werden.

// ggf. den Text aus der Box oben hierhin verschieben oder wiederholen?

[#zusammenfassung]
=== Zusammenfassung

In diesem Schritt wird eine Zusammenfassung aller getätigten Eingaben in den einzelnen Schritten aufgelistet. Du kannst deine Angaben prüfen, diese ggf. anpassen und den Assistenten danach abschließen.

[#ereignisaktion-uebergabe-auftraege]
== Ereignisaktion für die Übergabe der Aufträge an CLC einrichten

// an welche Stelle passt diese EA am besten?

Richte für die Übergabe der Aufträge an CLC eine Ereignisaktion ein. Gehe dazu wie im Folgenden beschrieben vor.

[.instruction]
Ereignisaktion für die Übergabe der Aufträge an CLC einrichten:

. Öffne das Menü *Einrichtung » Aufträge » Ereignisse*.
. Klicke auf *Ereignisaktion hinzufügen* (icon:plus-square[role="green"]), um eine neue Ereignisaktion zu erstellen.
. Gib einen *Namen* für die Ereignisaktion ein, z.B. `Übergabe CLC`.
. Wähle aus der Dropdown-Liste *Ereignis* die Einstellung *Auftragsänderung > Statuswechsel*. +
*_Hinweis:_* Wir empfehlen das Ereignis *Statuswechsel*. Du kannst jedoch jedes andere beliebige Ereignis wählen, solange es sich um ein auftragsrelevantes Ereignis handelt.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
. Klicke auf *Aktion hinzufügen* (icon:plus-square[role="green"]).
. Wähle die Einstellung *Plugins > CLC Shipping Order Export*.
. Wähle die Einstellung *Aktiv*, um die Ereignisaktion zu aktivieren.
. *Speichere* (icon:save[role="green"]) die Einstellungen.
