= eBay Fulfillment Integrationsleitfaden
:lang: de
include::{includedir}/_header.adoc[]
:keywords: eBay Fulfillment
:description: Erfahren Sie, wie Sie eBay Fulfillment in plentymarkets einrichten.
:position: 35
:url: fulfillment/ebay-fulfillment

Das Einhalten aktueller E-Commerce-Standards ist wesentlich für Ihren Geschäftserfolg. Die Kundenerwartungen wachsen – Lieferungen sollen immer kostenlos, schnell und zuverlässig erfolgen. Mithilfe von eBay Fulfillment können Sie diese Standards einhalten: Alle Ihre Artikel erfüllen sofort die Servicestandards für eBay Plus und tragen so zum Umsatzwachstum Ihres Unternehmens bei.

Das Plugin befindet sich derzeit in der Beta-Phase. Während dieser Phase passt eBay das Programm den Bedürfnissen und Anforderungen der Verkäufer an.

Unter dem Dach von Shutl Limited, dem Logistikpartner von eBay, stellen führende E-Commerce-Anbieter ein unabhängiges und wettbewerbsfähiges Abwicklungs- und Versandnetzwerk bereit: Der Pionier der Full-Service-Logistik Fiege bringt fast 150 Jahre Logistikerfahrung, innovatives Denken und maximale Flexibilität in das Netzwerk ein. Der Omni-Channel-ERP-Anbieter plentymarkets verknüpft in diesem Zuge die verschiedenen Vertriebswege, Fulfillment-Standorte und Logistik miteinander durch professionelles Auftragsmanagement, Synchronisieren von Bestandsbewegungen und Bereitstellen und Hochladen von Sendungsnummern.

[#10]
== Plugin-Downlaod und Installation

[#20]
=== eBay OAuth2-Plugin herunterladen und installieren

Laden Sie das eBay OAuth2-Plugin kostenlos im plentyMarketplace herunter. Dazu müssen Sie in Ihrem plentymarkets Backend eingeloggt sein. Gehen Sie wie im Folgenden beschrieben vor:

[.instruction]
eBay OAuth2-Plugin herunterladen und installieren:


. Öffnen Sie das Menü Plugins » Plugin-Übersicht.
. Klicken Sie auf plentyMarketplace (siehe Bild 1). +
→ Ein neues Browser-Tab wird geöffnet.
. Geben Sie “eBay OAuth2” in die Suche ein.
. Klicken Sie auf der Seite des link:https://marketplace.plentymarkets.com/plugins/channels/marktplaetze/ebayoauth2_4787[eBay OAuth2-Plugins] auf *Zur Kasse*.
. Kaufen Sie das Plugin. +
→ Das Plugin ist für Ihr System freigeschaltet.
. Wählen Sie im Menü *Plugins » Plugin-Übersicht* die Option *Nicht installiert*.
. Klicken Sie auf *Suchen*, um das soeben gekaufte Plugin zu finden. +
→ Das Plugin wird angezeigt.
. Klicken Sie in der Zeile des Plugins auf der rechten Seite auf *Plugin installieren* (siehe Bild 2). +
→ Ein Fenster wird geöffnet.
. Wählen Sie die aktuellste Version des Plugins und klicken Sie auf *Installieren*.
. Klicken Sie in der Zeile des Plugins auf die Weltkugel (*Aktiv*) ganz links (siehe Bild 3).
. Klicken Sie auf *Speichern*.
→ Das Plugin ist gespeichert und bereitgestellt.

////
TODO
Bilder einfügen
////

Stellen Sie sicher, dass ein Konto im plentymarkets Backend im Menü *System » Systemeinstellungen » Märkte » eBay » Konten » OAuth2* verfügbar ist. Wenn Sie noch kein Konto haben, fügen Sie dieses unter *System » Systemeinstellungen » Märkte » eBay » Konten* hinzu.

[#30]
=== eBay Fulfillment-Plugin herunterladen und installieren

Nachdem Sie von eBay für die Beta-Phase freigeschaltet wurden, kaufen Sie das link:https://marketplace.plentymarkets.com/plugins/integration/ebayfiege_6018[eBay Fulfillment-Plugin] kostenlos im plentyMarketplace und installieren es. Gehen Sie dazu genauso vor, wie in der Handlungsanweisung in Kapitel <<fulfillment/ebay-fulfillment#20, eBay OAuth2-Plugin kaufen und installieren>> beschrieben.

[IMPORTANT]
.Hinweis
====
Bei dem eBay Fulfillment-Plugin ist es möglich, dass die oben aufgeführten Schritte 8 bis 10 deutlich mehr Zeit in Anspruch nehmen als bei dem zuvor installierten eBay OAuth2-Plugin.
====

[#40]
== Systemeinstellungen für eBay Fulfillment

[#50]
=== Auftragsherkunft aktivieren

Durch die Bereitstellung des eBay Fulfillment-Plugins ist die Auftragsherkunft *eBay Fulfillment* automatisch im Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft* vorhanden. Sie müssen diese Auftragsherkunft aktivieren.

[.instruction]
Auftragsherkunft aktivieren:


. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Auftragsherkunft*.
. Suchen Sie *eBay Fulfillment*.
. Aktivieren Sie die Option, indem Sie ein Häkchen setzen (siehe Bild 10).
. *Speichern* Sie die Einstellungen.

////
TODO
Bild einfügen
////

[#60]
=== EBSFKU anlegen

Barcodes dienen der Kennzeichnung von Artikeln in plentymarkets. Zur eindeutigen Identifikation der Artikel zwischen eBay Fulfillment und plentymarkets erstellen Sie den Barcode *EBFSKU*.

[.instruction]
EBFSKU anlegen:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Artikel » Barcode*.
. Klicken Sie auf *Neuer Barcode*.
. Geben Sie den Namen *EBFSKU* ein.
. Wählen Sie als *Typ* die Einstellung *CODE128*.
. *Speichern* Sie die Einstellung. +
→ Der Barcode öffnet sich.
. Wählen Sie als Herkunft die Einstellung *eBay Fulfillment* (siehe Bild 4).
. *Speichern* Sie die Einstellung erneut.

[WARNING]
.Wichtig
====
Beachten Sie, dass eBay Fulfillment keine Artikel verwalten kann, die über keine EBFSKU verfügen. Demnach werden Lieferungen von Artikeln, die über keine EBSFKU verfügen, nicht vom Fulfillment-Dienstleister angenommen.
====

////
TODO
Bild einfügen
////

[#70]
=== Lager einrichten

Richten Sie zwei Lager für eBay Fulfillment ein. Beachten Sie, dass ggf. zusätzliche Kosten für die Buchung weiterer Vetriebslager anfallen. Dies ist abhängig von Ihrem plentymarkets Tarif. Für Fragen zu Ihrem Tarif kontaktieren Sie den plentymarkets Service.

[.instruction]
Lager 1 vom Lagertyp Vertrieb einrichten:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Waren » Lager*.
. Klicken Sie auf *Neues Lager*.
. Geben Sie den Namen ein, z.B. *eBay Fulfillment Sales* (siehe Bild 5). +
→ *_Hinweis:_* Dieses Lager wird von eBay Fulfillment verwaltet.
. Wählen Sie als *Lagertyp* die Option *Vertrieb*.
. Wählen Sie als *Logistiktyp* die Option *Eigenes Lager*.
. *Speichern* Sie die Einstellungen. +
→ Das Lager wird geöffnet.
. Geben Sie die Adresse des Lagers ein.
. Wählen Sie unter *Verfügbar für Auftragsherkünfte (bei automatischer Lagerauswahl)* für welche Auftragsherkunft dieses Lager genutzt werden soll (siehe Bild 6). +
→ Mit der Steuerungs- bzw. Command-Taste, können Sie mehrere Herkünfte wählen.
. *Speichern* Sie die Einstellungen erneut.

[.instruction]
Lager 2 vom Lagertyp Sonstiges einrichten:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Waren » Lager*.
. Klicken Sie auf *Neues Lager*.
. Geben Sie den Namen ein, z.B. *eBay Fulfillment Exception*.
. Wählen Sie als *Lagertyp* die Option *Sonstiges*.
. Wählen Sie als *Logistiktyp* die Option *Eigenes Lager*.
. *Speichern* Sie die Einstellungen. +
→ Das Lager wird geöffnet.
. Geben Sie die Adresse des Lagers ein.
. *Speichern* Sie die Einstellungen erneut.


////
TODO
Hinweis für Einrichter ergänzen?
////

////
TODO
Bilder einfügen
////

[#80]
=== Versanddienstleister und Versandprofil einrichten

Stellen Sie sicher, dass für alle Versanddienstleister, die für das eBay Fulfillment-Programm eingesetzt werden, ein Versanddienstleister sowie ein Versandprofil eingerichtet sind.

[IMPORTANT]
.Hinweis
====
Für jeden neuen Fulfillment-Dienstleister muss sowohl ein neuer Versanddienstleister als auch ein neues Versandprofil vorhanden sein.
====

[#90]
==== Lieferländer aktivieren

eBay Fulfillment bietet den Versand in folgende Länder an:

* Deutschland
* Österreich
* Italien
* Belgien
* Niederlande
* Vereinigtes Königreich

Um in plentymarkets korrekt mit diesen Lieferländern arbeiten zu können, müssen diese in Ihrem plentymarkets System aktiviert werden.

[WARNING]
.Hinweis
====
Es kann zu Einschränkungen bei der Belieferung über andere Marktplätze aufgrund der begrenzten Anzahl an aktiven Lieferländern kommen.
====

[.instruction]
Lieferländer aktivieren:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen*. +
→ Das Tab *Lieferländer* wird geöffnet.
. Wählen Sie für die gewünschten Lieferländer in der Spalte *Aktiv* die Option *Aktiv* aus der Dropdown-Liste.
. Wählen Sie in der Spalte *Sprache* die gewünschte Sprache, die für das Lieferland aktiviert werden soll.
. *Speichern* Sie die Einstellungen.

[#100]
==== Versanddienstleister einrichten

Im plentymarkets Backend im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister* muss der Versanddienstleister, z.B. Hermes, erstellt und dessen Tracking-URL gespeichert sein.

[.instruction]
Versanddienstleister einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versanddienstleister*.
. Klicken Sie im Tab *Übersicht* auf *Neu*. +
→ Ganz unten wird eine neue Zeile hinzugefügt.
. Geben Sie im Feld *Name (de)* den Namen des Versanddienstleister, z.B. Hermes, ein. +
→ *_Hinweis:_* Dieser Name ist für Ihre Kunden im Webshop sichtbar.
. Geben Sie im Feld *Name (Backend)* den Namen des Versanddienstleisters oder eine alternative Bezeichnung für den internen Gebrauch ein. +
→ *_Hinweis:_* Dieser Name ist für Ihre Kunden nicht sichtbar. +
→ Tipp: Wenn Sie bereits ein Hermes-Versandprofil eingerichtet haben, verwenden Sie zur einfacheren Unterscheidung einen anderen Namen, z.B. *eBay Fulfillment*.
. Wählen Sie den Versanddienstleister, z.B. Hermes, aus der Dropdown-Liste.
. Geben Sie im Feld *Tracking-URL* die Tracking-URL des Versanddienstleisters ein (z.B. für Hermes: https://tracking.hermesworld.com/?TrackID=$PaketNr) +
→ Erfragen Sie die Tracking-URL ggf. bei Ihrem Versanddienstleister.
. *Speichern* Sie die Einstellungen.

////
TODO
Bild einfügen
////

[#110]
==== Versandprofil einrichten

Im plentymarkets Backend im Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile* muss ein Versandprofil mit diesem Versanddienstleister verfügbar sein.

[.instruction]
Versandprofil einrichten:

. Öffnen Sie das Menü *System » Systemeinstellungen » Aufträge » Versand » Optionen » Tab: Versandprofile*.
. Klicken Sie auf *Neu*.
. Wählen Sie den eben erstellten Versanddienstleister aus der Dropdown-Liste.
. Geben Sie den Namen in den Feldern *Name (de)* und *Name (Backend)* ein, z.B. Hermes.
. Setzen Sie im Bereich *Mandanten (Shops)* ein Häkchen bei Ihrem Online-Shop.
. Setzen Sie im Bereich *Auftragsherkunft* ein Häkchen bei den Herkünften, die Sie über eBay Fulfillment abwickeln möchten.
. *Speichern* Sie die Einstellungen.


////
TODO
Video einfügen?
////

[#120]
=== Auftragsstatus erstellen

Für eine bessere Übersicht wird das Erstellen von Auftragsstatus für Inbound- und Outbound-Aufträge sowie für nicht gesendete Inbound- und Outbound-Aufträge empfohlen.

Für den Fall, dass der Inbound oder Outbound nicht gesendet werden konnte, stellen Sie später im plentymarkets Backend im Menü *System » Systemeinstellungen » Aufträge » Versand » Fulfillment » eBay Fulfillment » Einstellungen* für *Inbound-Auftrag nicht gesendet* und *Outbound-Auftrag nicht gesendet* den Status ein, damit die Aufträge entsprechend abgefangen und von Ihnen geprüft werden können.

////
TODO
Text anpassen in der Einleitung, denn es gibt ja noch mehr als diese dort beschriebenen Status
////

[WARNING]
.Hinweis
====
Sie müssen freie, noch unbesetzte Auftragsstatus suchen und diese dann verwenden. Überschreiben Sie in keinem Fall bereits besetzte Auftragsstatus, da sich diese möglicherweise an anderer Stell im System bereits in Verwendung befinden.

Wählen Sie die Status zwischen 5 und 8.
====

[#130]
==== Auftragsstatus für Inbound (genutzt in Ereignisaktion)

[.instruction]
Auftragsstatus für Inbound erstellen:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Status*.
. Klicken Sie auf *Neuer Status*.
. Geben Sie im Feld *Neuer Status* die Nummer ein, z.B. *5.3*.
. Geben Sie im Feld *Name für neuen Status* den Namen ein, z.B. *eBay Fulfillment Inbound*.
. *Speichern* Sie die Einstellungen. +
→ Der neue Auftragsstatus *[5.3] eBay Fulfillment Inbound* wird erstellt.

[#140]
==== Auftragsstatus für Inbound-Auftrag gesendet (automatisches Statusupdate durch Plugin)

Im Falle einer erfolgreichen Übermittlung des Inbound an eBay Fulfillment, wird der Auftrag automatisch in den Status “Inbound gesendet” geändert, wenn Sie die folgenden Einstellungen vornehmen:

[.instruction]
Auftragsstatus für eBay Fulfillment Inbound gesendet erstellen:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Status*.
. Klicken Sie auf *Neuer Status*.
. Geben Sie im Feld *Neuer Status* die Nummer ein, z.B. *5.31*.
. Geben Sie im Feld *Name für neuen Status* den Namen ein, z.B. *eBay Fulfillment Inbound gesendet*.
. *Speichern* Sie die Einstellungen. +
→ Der neue Auftragsstatus *[5.31] eBay Fulfillment Inbound gesendet* wird erstellt.

[#150]
==== Auftragsstatus für Inbound-Auftrag nicht gesendet (automatisches Statusupdate durch Plugin)

[.instruction]
Auftragsstatus für *Inbound-Auftrag nicht gesendet* erstellen:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Status*.
. Klicken Sie auf *Neuer Status*.
. Geben Sie im Feld *Neuer Status* die Nummer ein, z.B. *5.5*.
. Geben Sie im Feld *Name für neuen Status* den Namen ein, z.B. *eBay Fulfillment Inbound nicht gesendet*.
. *Speichern* Sie die Einstellungen. +
→ Der neue Auftragsstatus *[5.5] eBay Fulfillment Inbound nicht gesendet* wird erstellt.

[#160]
==== Auftragsstatus für Outbound-Auftrag (Versandfreigabe, genutzt in Ereignisaktion)

[.instruction]
Auftragsstatus für *Outbound-Auftrag* erstellen:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Status*.
. Klicken Sie auf *Neuer Status*.
. Geben Sie im Feld *Neuer Status* die Nummer ein, z.B. *5.4*.
. Geben Sie im Feld *Name für neuen Status* den Namen ein, z.B. *eBay Fulfillment Outbound*.
. *Speichern* Sie die Einstellungen. +
→ Der neue Auftragsstatus *[5.4] Outbound* wird erstellt.

[#170]
==== Auftragsstatus für Outbound-Auftrag gesendet (automatisches Statusupdate durch Plugin)

[.instruction]
Auftragsstatus für *Outbound-Auftrag gesendet* erstellen:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Status*.
. Klicken Sie auf *Neuer Status*.
. Geben Sie im Feld *Neuer Status* die Nummer ein, z.B. *5.41*.
. Geben Sie im Feld *Name für neuen Status* den Namen ein, z.B. *eBay Fulfillment Outbound gesendet*.
. *Speichern* Sie die Einstellungen. +
→ Der neue Auftragsstatus *[5.41] Outbound gesendet* wird erstellt.

[#180]
==== Auftragsstatus für Outbound-Auftrag nicht gesendet (automatisches Statusupdate durch Plugin)

[.instruction]
Auftragsstatus für *Outbound-Auftrag nicht gesendet* erstellen:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Status*.
. Klicken Sie auf *Neuer Status*.
. Geben Sie im Feld *Neuer Status* die Nummer ein, z.B. *5.6*.
. Geben Sie im Feld *Name für neuen Status* den Namen ein, z.B. *eBay Fulfillment Outbound nicht gesendet*.
. *Speichern* Sie die Einstellungen. +
→ Der neue Auftragsstatus *[5.6] eBay Fulfillment Outbound nicht gesendet* wird erstellt.

[#190]
==== Auftragsstatus für abgelehnten Auftrag durch Fulfillment-Dienstleister

[.instruction]
Auftragsstatus für *abgelehnten Auftrag* durch Fulfillment-Dienstleister erstellen:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Status*.
. Klicken Sie auf *Neuer Status*.
. Geben Sie im Feld *Neuer Status* die Nummer ein, z.B. *5.7*.
. Geben Sie im Feld *Name für neuen Status* den Namen ein, z.B. *Auftrag abgelehnt*.
. *Speichern* Sie die Einstellungen. +
→ Der neue Auftragsstatus *[5.7] Auftrag abgelehnt* wird erstellt. +
→ Sie können diesen Status anschließend manuell filtern oder eine Ereignisaktion einrichten, damit Sie Aufträge in diesem Status weiterbearbeiten können. Wie Sie Ereignisaktionen einrichten, ist im Folgenden beschrieben.

[#200]
==== Auftragsstatus für Storno des Inbound-Auftrags

[.instruction]
Auftragsstatus für *Storno des Inbound-Auftrags* erstellen:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Status*.
. Klicken Sie auf *Neuer Status*.
. Geben Sie im Feld Neuer Status die Nummer ein, z.B. *8.2*.
. Geben Sie im Feld *Name für neuen Status* den Namen ein, z.B. *eBay Storno Inbound gesendet*.
. *Speichern* Sie die Einstellungen. +
→ Der neue Auftragsstatus *[8.2] eBay Storno Inbound gesendet* wird erstellt.


[#210]
=== Einstellung der Automatisierung

In plentymarkets besteht die Möglichkeit Routineaufgaben automatisiert durch das System erledigen zu lassen. Während der Nutzung des eBay Fulfillment-Services erleichtert das automatische Senden der Inbound-Benachrichtigung an eBay Fulfillment und auch das automatische Buchen von Warenausgängen Ihren Alltag.

Mit den Ereignisaktionen stellen wir Ihnen ein effektives Werkzeug zur Verfügung, mit dem Sie solche Automatismen einstellen und zuverlässig durch Ihr plentymarkets System ausführen lassen können. Das Grundprinzip von Ereignisaktionen ist leicht verständlich: Bestimmte Ereignisse lösen bestimmte Aktionen aus.

[#220]
=== Ereignisaktion für eBay Fulfillment Inbound einrichten

[.instruction]
Ereignisaktion für eBay Fulfillment Inbound einrichten:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen* (Plus-Zeichen).
. Geben Sie den Namen *eBay Fulfillment Inbound* ein.

*_Auslösendes Ereignis_*

. Wählen Sie aus der Dropdown-Liste *Ereignis* die Option *Auftragsänderung > Statuswechsel*.
. Wählen Sie aus der Dropdown-Liste *Status* den neu erstellten Status für Inbound.
. *Speichern* Sie die Einstellungen.

*_Filterkriterien für Aufträge_*

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Auftrag > Auftragstyp*.
. Klicken Sie auf *Hinzufügen*.
. Aktivieren Sie die Option *Auftrag*.

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Auftrag > Herkunft*.
. Klicken Sie auf *Hinzufügen*.
. Aktivieren Sie ausschließlich die Option *Manuelle Eingabe*. +
→ *_Wichtig:_* Aktivieren Sie hier keine anderen Optionen.

*_Auszuführende Aktion_*

. Klicken Sie auf Aktion hinzufügen.
 Wählen Sie die Aktion *Plugins > Einlagerungsbenachrichtigung an Logistiker senden*. +
→ *_Hinweis:_* Diese Aktion ist nur verfügbar, wenn Sie das eBay Fulfillment-Plugin installiert und bereitgestellt haben. +
→ *_Hinweis:_* Einlagerungsbenachrichtigung an Logistiker = Inbound notification

. Setzen Sie ein Häkchen bei Aktiv, um die Ereignisaktion zu aktivieren.
. *Speichern* Sie die Einstellungen.

[#230]
=== Ereignisaktion für eBay Fulfillment Outbound einrichten

[.instruction]
Ereignisaktion für eBay Fulfillment Outbound einrichten:

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen* (Plus-Zeichen).
. Geben Sie den Namen *eBay Fulfillment Outbound* ein.

*_Auslösendes Ereignis_*

. Wählen Sie aus der Dropdown-Liste Ereignis die Option *Auftragsänderung > Statuswechsel*.
. Wählen Sie aus der Dropdown-Liste *Status* den neu erstellten Status für Outbound.
. *Speichern* Sie die Einstellungen.

*_Filterkriterien für Aufträge_*

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Auftrag > Auftragstyp*.
. Klicken Sie auf *Hinzufügen*.
. Aktivieren Sie die Option *Auftrag*.
. Aktivieren Sie die Option *Lieferauftrag*.

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Auftrag > Auftragslager*.
. Klicken Sie auf *Hinzufügen*.
. Aktivieren Sie die Option *eBay Fulfillment Sales*.

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Versand > Lieferland*.
. Klicken Sie auf *Hinzufügen*.
. Aktivieren Sie die Optionen *Deutschland*, *Österreich*, *Italien*, *Belgien*, *Niederlande* und *UK*.

*_Auszuführende Aktion_*

. Klicken Sie auf Aktion hinzufügen.
. Wählen Sie die Aktion *Plugins > Versandfreigabe an Logistiker senden*. +
→ Hinweis: Diese Aktion ist nur verfügbar, wenn Sie das eBay Fulfillment-Plugin installiert und bereitgestellt haben. +
→ Hinweis: Versandfreigabe für den Logistiker= Outbound notification.
. Klicken Sie auf *Hinzufügen*.

. Setzen Sie ein Häkchen bei *Aktiv*, um die Ereignisaktion zu aktivieren.
. *Speichern* Sie die Einstellungen.

[#240]
=== Ereignisaktion für automatische Sendungsverfolgung (Versenden der Tracking-URL) (optional)

Mit Ihrem plentymarkets System ist es möglich, eine Versandbestätigung via E-Mail an Ihren Kunden zu versenden. Dies setzt voraus, dass Sie eine entsprechende E-Mail Vorlage in Ihrem System erstellt haben.

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Mandant » Standard » E-Mail » Vorlagen » Allgemeine Vorlagen > Auftrag: Versandbestätigung*.
. Wählen Sie das Tab *E-Mail-Nachricht*. +
→ Hier befindet sich ein Text, der standardmäßig in jedem System hinterlegt ist. Passen Sie diesen Text ggf. nach Ihren eigenen Wünschen an.
. Fügen Sie die Variable *$TrackingURL* an der gewünschten Stelle in Ihrem Text ein.
. *Speichern* Sie die Einstellungen.

[IMPORTANT]
.Hinweis
====
Klicken Sie im Tab *E-Mail-Vorlagen* rechts neben dem *Speichern*-Button auf den Button *Template-Variablen und -Funktionen*, um eine Übersicht über alle Variablen zu erhalten, die Sie in Ihre E-Mail-Vorlage einfügen können.
====

Die folgenden Schritte erklären, wie Sie eine Versandbestätigung automatisch an Ihre Kunden versenden können.

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen* (Plus-Zeichen).
. Geben Sie den Namen, wie z.B. *Automatisierung Sendungsverfolgung Outbound* ein.

*_Auslösendes Ereignis_*

. Wählen Sie aus der Dropdown-Liste *Ereignis* die Option *Auftragsänderung > Paketnummer*.

*_Filterkriterien für Aufträge_*

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Auftrag > Auftragstyp*.
. Klicken Sie auf *Hinzufügen*.
. Aktivieren Sie die Option *Auftrag*.
. Aktivieren Sie die Option *Lieferauftrag*.

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Auftrag > Auftragslager*.
. Klicken Sie auf *Hinzufügen*.
. Aktivieren Sie die Option *eBay Fulfillment Sales*.

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Auftrag > Herkunft*.
. Klicken Sie auf *Hinzufügen*. +
. Aktivieren Sie anschließend alle Herkünfte außer eBay.
→ *_Wichtig:_* eBay versendet eine eigene Bestätigungsmail mit der entsprechenden Tracking URL.

*_Auszuführende Aktion_*

. Klicken Sie auf *Aktion hinzufügen*.
. Wählen Sie die Aktion *Kunde > E-Mail versenden*.
. Klicken Sie auf *Hinzufügen*.
. Klicken Sie innerhalb des Aktionsfenster auf den Pfeil auf der linken Seite, sodass sich die Aktionsübersicht öffnet.
. Klicken Sie dort auf *Hinzufügen* (Plus-Zeichen).
. Wählen Sie im ersten Feld die Option *Auftrag: Versandbestätigung*.
. Wählen Sie im zweiten Feld die Option *Kunde*. +
→ Bild 7 zeigt die Übersicht einer fertiggestellten Aktion.

. Setzen Sie ein Häkchen bei *Aktiv*, um die Ereignisaktion zu aktivieren.
. *Speichern* Sie die Einstellungen.

////
TODO
Bild einfügen
////

[#250]
=== Automatisiertes Senden eines Outbounds an eBay Fulfillment

In plentymarkets ist es möglich, den gesamten Outbound-Prozess automatisiert durchlaufen zu lassen, ohne ein weitere manuelle Einstellungen durchführen zu müssen. Um dies umzusetzen, legen Sie eine weitere Ereignisaktion wie folgt an:

////
TODO
Hinweis nötig?

Hinweis an Einrichter: Bei Bestandskunden müssen hier die übrigen Ereignisaktionen  auf Überschneidungen hin überprüft und ggf. angepasst werden.
////

. Öffnen Sie im plentymarkets Backend das Menü *System » Systemeinstellungen » Aufträge » Ereignisse*.
. Klicken Sie auf *Ereignisaktion hinzufügen* (Plus-Zeichen).
. Geben Sie den Namen, wie z.B. *Automatisierung Outbound* ein.

*_Auslösendes Ereignis_*

. Wählen Sie aus der Dropdown-Liste *Ereignis* die Option *Auftragsänderung > Statuswechsel*.
. Wählen Sie aus der Dropdown-Liste *Status* den Status *Freigabe Versand*.
. *Speichern* Sie die Einstellungen.

*_Filterkriterien für Aufträge_*

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Auftrag > Auftragstyp*.
. Klicken Sie auf *Hinzufügen*.
. Aktivieren Sie die Option *Auftrag*.
. Aktivieren Sie die Option *Lieferauftrag*.

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Auftrag > Auftragslager*.
. Klicken Sie auf *Hinzufügen*.
. Aktivieren Sie die Option *eBay Fulfillment Sales*.

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Auftrag > Zahlungsart*.
. Klicken Sie auf *Hinzufügen*.
. Aktivieren Sie alle Zahlungsarten mit Ausnahme von *Nachnahme*.

. Klicken Sie auf *Filter hinzufügen*.
. Wählen Sie den Filter *Versand > Lieferland*.
. Klicken Sie auf *Hinzufügen*.
. Aktivieren Sie die Optionen *Deutschland*, *Österreich*, *Italien*, *Belgien*, *Niederlande* und *UK*.

*_Auszuführende Aktion_*

. Klicken Sie auf *Aktion hinzufügen*.
. Wählen Sie die Aktion *Auftrag > Status ändern*.
. Klicken Sie auf *Hinzufügen*.
. Wählen Sie aus der Dropdown-Liste den zuvor erstellten Status *eBay Fulfillment Outbound*.

. Setzen Sie ein Häkchen bei *Aktiv*, um die Ereignisaktion zu aktivieren.
. *Speichern* Sie die Einstellungen.
