= Versand-Center 2.0
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Versand-Center, Auftrag anmelden, Polling, Versandpaket, Versandlabel, Tagesabschlussliste, Auftragszusammenfassung, Retourenlabel, Auftrag stornieren, Auftrag zurücksetzen
:description: Erfahre, wie du das neue Versand-Center 2.0 in plentymarkets nutzt.
:position: 15
:url: fulfillment/versand-center-2.0
:id: JVNZPRL
:author: team-fulfillment

[TIP]
Auf dieser Seite stellen wir dir alle Funktionen des neuen Versand-Centers 2.0 vor. Weitere Funktionen werden kontinuierlich ergänzt und dann auch auf dieser Seite hinzugefügt.

Im Menü *Aufträge » Versand-Center 2.0* steuerst du alle Aktionen, die im Zusammenhang mit dem Versand deiner Artikel über die integrierten Versandschnittstellen stehen. Neben dem Suchen und Bearbeiten von Versandaufträgen hast du die Möglichkeit, Versandaufträge direkt bei einem Versanddienstleister anzumelden oder eine Polling-Datei und Auftragszuammenfassung zu erzeugen, um diese einem Versanddienstleister zu übergeben.

[#auftrag-suchen]
== Auftrag im Versand-Center suchen

Über die Übersicht im Versand-Center 2.0 kannst du alle Versandaufträge in einer Liste öffnen oder du wählst Filter, um die Suchergebnisse einzugrenzen.

// über welchen Zeitraum kann ich hier Aufträge suchen? wie lange sind die Aufträge in diesem Menü sichtbar?

[.instruction]
Auftrag im Versand-Center suchen:

. Öffne das Menü *Aufträge » Versand-Center 2.0*.
* *_Möglichkeit 1_*: Klicke auf icon:search[set=material], um eine Liste aller Versandaufträge zu sehen.
* *_Möglichkeit 2_*: Klicke auf icon:more_vert[set=material], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.
. Beachte die Erläuterungen zu den Filtern in Tabelle <<table-search-shipping-order>>.

[[table-search-shipping-order]]
.Filteroptionen zur Suche im Versand-Center
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Auftrags-ID*
|Gib eine ID ein, um nach dem Auftrag mit genau dieser ID zu suchen.

| *Angemeldet mit*
|Wähle eine oder mehrere Optionen (icon:check-square[role="blue"]), um nach Aufträgen in diesem Anmeldestatus zu suchen. +
*_Hinweis:_* In dieser Spalte siehst du dann den Versanddienstleister, mit dem der Auftrag angemeldet wurde. Wenn das Feld leer ist, wurde der Auftrag noch nicht angemeldet.

| *Versanddienstleister*
|Wähle einen oder mehrere Versanddienstleister (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Versanddienstleister zu suchen.

| *Versandprofil*
|Wähle ein oder mehrere Versandprofile (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Versandprofil zu suchen.

| *Auftragsstatus*
|Wähle einen oder mehrere Auftragsstatus (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Auftragsstatus zu suchen.

| *Eigner*
|Wähle einen oder mehrere Eigner (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Eigner zu suchen.

| *Mandant (Shop)*
|Wähle einen oder mehrere Mandanten (Shops) (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Mandanten (Shop) zu suchen.

| *Lager*
|Wähle einen oder mehrere Lager (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Lager zu suchen.

| *Auftragsdatum von / bis*
|Wähle aus den Kalendern (icon:calendar[]) die Daten aus, um nach Aufträgen in einem bestimmten Zeitraum zu suchen. 

| *Zurücksetzen*
|Setzt die gewählten Filterkriterien zurück.

| *Suchen*
|Führt die Suche aus. Die gefundenen Aufträge werden in der Übersicht angezeigt. +
*_Tipp:_* Setze keine Filter, wenn du alle Aufträge in der Übersicht sehen möchtest.

|====

[#uebersicht-anpassen]
== Übersicht im Versand-Center 2.0 anpassen

Das Versand-Center 2.0 enthält in der Übersicht standardmäßig die folgenden Spalten:

* Auftrags-ID
* Auftragsstatus
* Registriert mit
* Versandprofil
* Pakete
* Empfängername
* Empfängerregion

Über die Schaltfläche *Spalten konfigurieren* (icon:settings[set=material]) kannst du weitere Spalten in der Übersicht anzeigen oder bereits angezeigte Spalten deaktivieren.


[#gruppenfunktion]
== Gruppenfunktion nutzen

// Screenshot mit den Icons hinzufügen

TEXT


[[table-group-functions]]
.Gruppenfunktion im Versand-Center nutzen
[cols="2,1,6"]
|====
|Bedienelement |Symbol |Erläuterung

| *Aufträge bearbeiten*
| icon:edit[set=plenty]
|

| *Aufträge anmelden*
| icon:outgoing_items[set=plenty]
|

| *Polling*
| icon:file_extension_csv[set=plenty]
|

| *Retouren anmelden*
| icon:order_return[set=plenty]
|

| *Zusammenfassung*
| icon:order_note[set=plenty]
|

| *Versandlabel gruppieren*
| icon:order_open[set=plenty]
|

| *Retourenlabel gruppieren*
|
|

| *Aufträge zurücksetzen*
| icon:reset[set=plenty]
|

| *Aufträge stornieren*
| icon:cancel[set=plenty]
|

// prüfen, ob Aufträge stornieren auch in der Gruppenfunktion zur Verfügung steht oder nur im einzelnen Auftrag.

|====


// am besten farbigen Screenshot (--> Menüaufbau kenntlich machen)

[#auftrag-anmelden]
== Auftrag anmelden

Wenn du deine Aufträge im Versand-Center bei einem Versanddienstleister anmeldest, werden diese auch gleichzeitig an den Versanddienstleister übertragen. 

// ist der Hinweis auf der "alten" Seite bzgl. Hermes ProfiPaketService noch aktuell?

Verwende z.B. die <<#auftrag-suchen, Filtereinstellungen>> in der Suche des Versand-Centers, um nur Aufträge für einen bestimmten Versanddienstleister in einem bestimmten Auftragsstatus anzuzeigen. Bei der Anmeldung erhältst du sowohl im Erfolgsfall als auch im Fehlerfall eine Meldung vom Versanddienstleister.

Du kannst entweder einen Auftrag einzeln anmelden oder mehrere Aufträge über die Gruppenfunktion in der Übersicht anmelden. Um weitere Informationen zum Anmelden eines einzelnen Auftrags zu erhalten, klicke auf *Einen Auftrag anmelden* (Standardauswahl). Um weitere Informationen zum Anmelden mehrere Aufträge über die Gruppenfunktion in der Übersicht zu erhalten, klicke auf *Mehrere Aufträge über die Gruppenfunktion anmelden*.

[.tabs]
====
Einen Auftrag anmelden::
+
--

// Start Inhalt Tab 1:
Gehe wie im Folgenden beschrieben vor, um einen Auftrag einzeln anzumelden.

[.instruction]
Einen Auftrag anmelden:

. Öffne das Menü *Aufträge » Versand-Center 2.0*.
. Suche den Auftrag, den du anmelden möchtest, anhand der Filtereinstellungen wie im Kapitel <<#auftrag-suchen, Auftrag im Versand-Center suchen>> beschrieben. +
→  Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt.
. Öffne den Auftrag, den du anmelden möchtest.
. Klicke in der Symbolleiste ganz oben auf *Auftrag anmelden* (icon:outgoing_items[set=plenty]). +
→ Das Fenster *Auftrag anmelden* öffnet sich. 
. Wähle den Versanddienstleister, bei dem du den Auftrag anmelden möchtest, aus der Dropdown-Liste. +
*_Hinweis:_* Abhängig vom gewählten Versanddienstleister sind weitere Dropdown-Listen verfügbar mit zusätzlichen Optionen verfügbar. Diese zusätzlichen Optionen ermöglichen es dir, das Versandprofil für ausgewählte Aufträge nachträglich zu ändern oder das Versanddatum vor- oder zurückzudatieren.
. Wähle den Auftragsstatus, in dem sich der Auftrag nach erfolgreicher Anmeldung beim Versanddienstleister befinden soll, aus der Dropdown-Liste. +
*_Hinweis:_* Du kannst den Wechsel in diesen Auftragsstatus dann mit einer <<automatisierung/ereignisaktionen, Ereignisaktion>>, die z.B. automatisch den Warenausgang bucht, verknüpfen.
. Wähle den Auftragsstatus, in dem sich der Auftrag nach fehlgeschlagener Anmeldung beim Versanddienstleister befinden soll, aus der Dropdown-Liste. +
*_Hinweis:_* Du kannst den Wechsel in diesen Auftragsstatus dann mit einer <<automatisierung/ereignisaktionen, Ereignisaktion>> verknüpfen.
. Klicke auf *Anmelden*. +
→ Der Auftrag wird beim Versanddienstleister angemeldet.


// [TIP]
// .Zusatzoptionen bei manchen Versanddienstleistern verfügbar
// ====
// Im Fenster *Auftrag anmelden* sind abhängig vom Versanddienstleister zusätzliche Dropdown-Listen mit weiteren Optionen verfügbar. Diese zusätzlichen Optionen ermöglichen es dir, das Versandprofil für ausgewählte Aufträge nachträglich zu ändern sowie das Versanddatum vor- oder zurückzudatieren. +
// *_Hinweis:_* Die meisten Versanddienstleister bieten keine Zusatzoptionen. Daher siehst du meist keine weiteren Optionen in dem Fenster *Auftrag anmelden*.
// ====


// Ende Inhalt Tab 1
======
--




// Überschrift Tab 2
 
Mehrere Aufträge über die Gruppenfunktion anmelden::
+
--
// Start Inhalt Tab 2

Gehe wie im Folgenden beschrieben vor, um mehrere Aufträge über die Gruppenfunktion in der Übersicht anzumelden.

[.instruction]
Mehrere Aufträge über die Gruppenfunktion anmelden:

. Öffne das Menü *Aufträge » Versand-Center 2.0*.
. Suche die Aufträge, die du anmelden möchtest, anhand der Filtereinstellungen wie im Kapitel <<#auftrag-suchen, Auftrag im Versand-Center suchen>> beschrieben. +
→  Die Aufträge, die den eingestellten Suchkriterien entsprechen, werden in der Übersicht angezeigt.
. Aktiviere (icon:check-square[role="blue"]) die Aufträge, die du anmelden möchtest.
. Wähle in der Übersicht ganz oben auf *Aufträge anmelden* (icon:outgoing_items[set=plenty]). +
→ Das Fenster *Aufträge anmelden* öffnet sich. 
. Wähle den Versanddienstleister, bei dem du die Aufträge anmelden möchtest, aus der Dropdown-Liste. +
*_Hinweis:_* Abhängig vom gewählten Versanddienstleister sind weitere Dropdown-Listen verfügbar mit zusätzlichen Optionen verfügbar. Diese zusätzlichen Optionen ermöglichen es dir, das Versandprofil für ausgewählte Aufträge nachträglich zu ändern oder das Versanddatum vor- oder zurückzudatieren.
. Wähle den Auftragsstatus, in dem sich die Aufträge nach erfolgreicher Anmeldung beim Versanddienstleister befinden sollen, aus der Dropdown-Liste. +
*_Hinweis:_* Du kannst den Wechsel in diesen Auftragsstatus dann mit einer <<automatisierung/ereignisaktionen, Ereignisaktion>>, die z.B. automatisch den Warenausgang bucht, verknüpfen.
. Wähle den Auftragsstatus, in dem sich die Aufträge nach fehlgeschlagener Anmeldung beim Versanddienstleister befinden sollen, aus der Dropdown-Liste. +
*_Hinweis:_* Du kannst den Wechsel in diesen Auftragsstatus dann mit einer <<automatisierung/ereignisaktionen, Ereignisaktion>> verknüpfen.
. Klicke auf *Aufträge anmelden*. +
→ Die Aufträge werden beim Versanddienstleister angemeldet.


// [TIP]
// .Zusatzoptionen bei manchen Versanddienstleistern verfügbar
// ====
// Im Fenster *Auftrag anmelden* sind abhängig vom Versanddienstleister zusätzliche Dropdown-Listen mit weiteren Optionen verfügbar. Diese zusätzlichen Optionen ermöglichen es dir, das Versandprofil für ausgewählte Aufträge nachträglich zu ändern sowie das Versanddatum vor- oder zurückzudatieren. +
// *_Hinweis:_* Die meisten Versanddienstleister bieten keine Zusatzoptionen. Daher siehst du meist keine weiteren Optionen in dem Fenster *Auftrag anmelden*.
// ====


// Ende Inhalt Tab 2
--
====




[#angemeldeten-auftrag-anzeigen]
[discrete]
=== Angemeldeten Auftrag anzeigen

[#mehrere-auftraege-anmelden]
== Mehrere Aufträge anmelden

[#angemeldeten-auftrag-bearbeiten]
== Angemeldeten Auftrag bearbeiten

[#paketnummer-bearbeiten]
== Paketnummer bearbeiten

[#versandpaket-bearbeiten]
== Versandpaket bearbeiten

[#auftrag-stornieren]
== Auftrag stornieren

[WARNING]
.Versandauftrag stornieren vs. Versandauftrag zurücksetzen
====
Wenn du einen Versandauftrag stornierst, wird die Anmeldung in plentymarkets und auch beim Versanddienstleister zurückgenommen, sodass der Auftrag _nicht_ abgeholt wird.

Wenn du einen Auftrag zurücksetzt, ist er in plentymarkets wieder als offener Auftrag verfügbar, aber beim Versanddienstleister weiterhin angemeldet und wird berechnet. Die Funktion *Zurücksetzen* setzt lediglich die Anmeldungen zurück. Der Versandauftrag wird nicht beim Dienstleister storniert. Daher solltest du den Auftrag generell stornieren.
====

[#mehrere-auftraege-stornieren]
=== Mehrere Aufträge stornieren

[#auftrag-zuruecksetzen]
== Auftrag zurücksetzen

[WARNING]
.Versandauftrag stornieren vs. Versandauftrag zurücksetzen
====
Wenn du einen Versandauftrag stornierst, wird die Anmeldung in plentymarkets und auch beim Versanddienstleister zurückgenommen, sodass der Auftrag _nicht_ abgeholt wird.

Wenn du einen Auftrag zurücksetzt, ist er in plentymarkets wieder als offener Auftrag verfügbar, aber beim Versanddienstleister weiterhin angemeldet und wird berechnet. Die Funktion *Zurücksetzen* setzt lediglich die Anmeldungen zurück. Der Versandauftrag wird nicht beim Dienstleister storniert. Daher solltest du den Auftrag generell stornieren.
====

[#mehrere-auftraege-zuruecksetzen]
=== Mehrere Aufträge zurücksetzen

[#polling-datei-erzeugen]
== Polling-Datei erzeugen

Erzeuge für die Software eines Versanddienstleisters eine Polling-Datei, die zuvor gewählte Aufträge enthält. Eine Polling-Datei wird benötigt, wenn keine direkte Schnittstelle zu der Software des Versanddienstleisters besteht und somit die Anmeldung des Versandauftrags nicht über das Versand-Center 2.0 erfolgen kann. Die in plentymarkets erzeugte Polling-Datei ist im Regelfall eine CSV-Datei.

[.instruction]
Polling-Datei erzeugen:

. Öffne das Menü *Aufträge » Versand-Center 2.0*.
. Suche den Auftrag. Beachte <<#table-search-shipping-order#>>.
. Öffne den Auftrag.
. Klicke auf *Polling* (icon:file_extension_csv[set=plenty]).
//. Wähle den Versanddienstleister.
. Wähle den Auftragsstatus, in den die Aufträge geändert werden sollen.
. Aktiviere die Aufträge, die über den gewählten Versanddienstleister verschickt werden sollen.
. Klicke auf *Polling*, um die Polling-Datei zu erzeugen. +
→ Die Polling-Datei wird erzeugt.
. Speichere die Datei auf deinem Computer und sende sie an den Versanddienstleister.

// Konfig-Schritte nochmal genau prüfen

[#zusammenfassung-erzeugen]
== Zusammenfassung erzeugen

Erzeuge eine Auftragszusammenfassung bzw. Tagesabschlussliste von in deinem plentymarkets System eingerichteten Versanddienstleistern. 

Eine solche Zusammenfassung enthält alle Aufträge, die an einem Tag bei dem Versanddienstleister angemeldet wurden und vom Versanddienstleister abgeholt werden sollen. Die im Auftrag des Versanddienstleisters abholende Person unterschreibt dann diese Liste statt jedes Versandlabel einzeln zu unterschreiben. Die Liste dient also als Abholbeleg.


[.instruction]
Auftragszusammenfassung erzeugen:

. Öffne das Menü *Aufträge » Versand-Center 2.0*.
. Klicke auf *Zusammenfassung* (icon:order_note[set=plenty]).
. Wähle den Versanddienstleister, für den du die Zusammenfassung erstellen möchtest, aus der Dropdown-Liste. +
*_Hinweis:_* Falls vorhanden, werden weitere Optionen des Versanddienstleisters eingeblendet.
. Nimm ggf. Einstellungen für die Optionen vor.
. Klicke auf Ausführen. +
// Icon und korrekten Namen des Buttons einfügen.
→ Die PDF-Datei wird erzeugt.

// Konfig-Schritte nochmal genau prüfen

[#versandlabel-generieren]
== Versandlabel generieren

[#versandlabel-drucken]
=== Versandlabel drucken

// manuell und über Prozess und EA --> tabbing content verwenden

[#retourenetikett-abrufen]
== Retourenetikett abrufen

[#in-lieferauftraege-splitten]
== Aufträge in Lieferaufträge splitten

Lege fest, nach welchen Kriterien Aufträge in Lieferaufträge gesplittet werden sollen. Zur Auswahl stehen die folgenden Optionen: 

* Lager
* Versandprofil
* Lager und Versandprofil
* Lager- und Nettowarenbestand

Weitere Informationen findest du im Bereich <<auftraege, Aufträge>> im Kapitel <<auftraege/auftraege-verwalten#300, Auftragstyp Lieferauftrag nutzen>>.



== FAQ

[#faq-fehlerbericht]
[.collapseBox]
.Wo kann ich Fehlerberichte einsehen, wenn die Anmeldung des Auftrags fehlgeschlagen ist?
--
Wenn ein Auftrag nicht angemeldet werden kann, wird eine Fehlermeldung angezeigt.

Beachte bei der Fehlersuche auch das Menü *Daten » Log*. Die darin verfügbaren Einträge bleiben 4 Wochen lang gespeichert. Weitere Informationen findest du auf der Handbuchseite <<daten/datenlog#, Daten-Log>>.
--

[#faq-unicode-zeichen]
[.collapseBox]
.Darf ich Unicode-Zeichen in der Lieferadresse verwenden?
--
Einige Versandschnittstellen (APIs) erlauben nur lateinische Zeichensätze (ISO-8859-X), jedoch keinen Unicode. Daher sollten Lieferadressen keine Unicode-Zeichen enthalten. Mit DHL z.B. sind keine Anmeldungen möglich, wenn die Anschrift in griechischen Buchstaben gespeichert ist.
--

[#faq-adresszusatz]
[.collapseBox]
.Der Adresszusatz wird nicht übertragen. Was nun?
--
Manche Versanddienstleister verarbeiten die Angabe *Adresszusatz* aus der Lieferadresse nicht. In seltenen Fällen kann deshalb eine Sendung nicht zugestellt werden. +
Zu folgenden Versanddienstleistern wird derzeit der Adresszusatz _nicht_ übermittelt:

* DHL Freight
* DHL Supply Chain
* Swiss Post

Prüfe, ob der Adresszusatz korrekt zu deinem Versanddienstleister übertragen wird. Wenn der Adresszusatz nicht übertragen wird, passe dein Design im Webshop so an, dass in Abhängigkeit des gewählten Versanddienstleisters der Adresszusatz im Webshop ein- oder ausgeblendet oder ein Hinweis für die Kund:innen eingeblendet wird.
--

// weitere FAQs ergänzen