= Versand-Center 2.0
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Versand-Center, Auftrag anmelden, Polling-Datei, Polling, Versandpaket, Label, Tagesabschlussliste, Auftragszusammenfassung, Retourenlabel, Auftrag im Versandcenter anmelden, Auftrag stornieren, Auftrag zurücksetzen,
:description: Erfahre, wie du das neue Versand-Center 2.0 in plentymarkets nutzt.
:position: 15
:url: fulfillment/versand-center-2.0
:id: JVNZPRL
:author: team-fulfillment

[TIP]
Auf dieser Seite stellen wir dir alle Funktionen des neuen Versand-Centers 2.0 vor. Weitere Funktionen werden kontinuierlich ergänzt und dann auch auf dieser Seite hinzugefügt.

Im Menü *Aufträge » Versand-Center 2.0* steuerst du alle Aktionen, die im Zusammenhang mit dem Versand deiner Artikel über die integrierten Versandschnittstellen stehen. Neben dem Suchen und Bearbeiten von Versandaufträgen hast du die Möglichkeit, Versandaufträge direkt bei einem Versanddienstleister anzumelden oder eine Polling-Datei zu erzeugen, um diese einem Versanddienstleister zu übergeben.

[#auftrag-suchen]
== Auftrag im Versand-Center suchen

Über die Übersicht im Versand-Center 2.0 kannst du alle Versandaufträge in einer Liste öffnen oder du wählst Filter, um die Suchergebnisse einzugrenzen.

// über welchen Zeitraum kann ich hier Aufträge suchen? wie lange sind die Aufträge in diesem Menü sichtbar?

[.instruction]
Auftrag im Versand-Center suchen:

. Öffne das Menü *Aufträge » Versand-Center 2.0*.
. *_Möglichkeit 1_*: Klicke auf icon:search[set=material], um eine Liste aller Versandaufträge zu sehen.
. *_Möglichkeit 2_*: Klicke auf icon:more_vert[set=material], um die Suchergebnisse mit Hilfe von Filtern einzugrenzen.
. Beachte die Erläuterungen zu den Filtern in Tabelle <<table-search-shipping-order>>.


[[table-search-shipping-order]]
.Filteroptionen zur Suche im Versand-Center
[cols="1,3"]
|====
|Einstellung |Erläuterung

| *Auftrags-ID*
|Gib eine ID ein, um nach dem Auftrag mit genau dieser ID zu suchen.

| *Anmeldestatus*
|Wähle einen oder mehrere Anmeldestatus (icon:check-square[role="blue"]), um nach Aufträgen in diesem Anmeldestatus zu suchen.

| *Versanddienstleister*
|Wähle einen oder mehrere Versanddienstleister (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Versanddienstleister zu suchen.

| *Versandprofil*
|Wähle ein oder mehrere Versandprofile (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Versandprofil zu suchen.

| *Auftragsstatus*
|Wähle einen oder mehrere Auftragsstatus (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Auftragsstatus zu suchen.

| *Eigner*
|Wähle einen oder mehrere Eigner (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Eigner zu suchen.

| *Mandant (Shop)*
|Wähle einen oder mehrere Mandanten (Shops) (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Mandanten (Shop) zu suchen.

| *Lager*
|Wähle einen oder mehrere Lager (icon:check-square[role="blue"]), um nach Aufträgen mit diesem Lager zu suchen.

| *RESET*
|Setzt die gewählten Filterkriterien zurück.

| *SUCHEN*
|Führt die Suche aus. Die gefundenen Aufträge werden in der Übersicht angezeigt. +
*_Tipp:_* Setze keine Filter, wenn du alle Aufträge in der Übersicht sehen möchtest.

|====


== Übersicht im Versand-Center 2.0 anpassen

Das Versand-Center 2.0 enthält in der Übersicht standardmäßig die folgenden Spalten:

* Auftrags-ID
* Auftragsstatus
* Registriert mit
* Versandprofil
* Pakete
* Empfänger:in
* Empfängerregion


Über *Spalten konfigurieren* (icon:settings[set=material])kannst du weitere Spalten in der Übersicht anzeigen oder bereits angezeigte Spalten deaktivieren.


// Gruppenfunktionen hier noch erklären

// am besten farbigen Screenshot (--> Menüaufbau kenntlich machen)


== Auftrag anmelden

[discrete]
=== Angemeldeten Auftrag anzeigen

== Angemeldeten Auftrag bearbeiten

=== Paketnummer bearbeiten

=== Auftrag stornieren

[WARNING]
.Versandauftrag stornieren vs. Versandauftrag zurücksetzen
====
Wenn du einen Versandauftrag stornierst, wird die Anmeldung in plentymarkets und auch beim Versanddienstleister zurückgenommen, sodass der Auftrag _nicht_ abgeholt wird.

Wenn du einen Auftrag zurücksetzt, ist er in plentymarkets wieder als offener Auftrag verfügbar, aber beim Versanddienstleister weiterhin angemeldet und wird berechnet. Die Funktion *Zurücksetzen* setzt lediglich die Anmeldungen zurück. Der Versandauftrag wird nicht beim Dienstleister storniert. Daher solltest du den Auftrag generell stornieren.
====

=== Auftrag zurücksetzen

[WARNING]
.Versandauftrag stornieren vs. Versandauftrag zurücksetzen
====
Wenn du einen Versandauftrag stornierst, wird die Anmeldung in plentymarkets und auch beim Versanddienstleister zurückgenommen, sodass der Auftrag _nicht_ abgeholt wird.

Wenn du einen Auftrag zurücksetzt, ist er in plentymarkets wieder als offener Auftrag verfügbar, aber beim Versanddienstleister weiterhin angemeldet und wird berechnet. Die Funktion *Zurücksetzen* setzt lediglich die Anmeldungen zurück. Der Versandauftrag wird nicht beim Dienstleister storniert. Daher solltest du den Auftrag generell stornieren.
====
