= Versand-Center nutzen
:lang: de
include::{includedir}/_header.adoc[]
:keywords: Versand-Center, Versandauftrag anmelden, Polling-Datei, Polling, Versandpaket, Label, Tagesabschlussliste, Auftragszusammenfassung, Retourenetikett
:description: Erfahren Sie, wie Sie Versandaufträge anmelden und Polling-Dateien und Labels erzeugen.
:position: 20
:url: fulfillment/versand-center

Im Menü *Aufträge » Versand-Center* steuern Sie alle Aktionen, die im Zusammenhang mit dem Versand Ihrer Artikel über die integrierten Versandschnittstellen stehen. Neben der Suche und Bearbeitung von Versandaufträgen haben Sie die Möglichkeit, Versandaufträge direkt bei einem Versanddienstleister <<fulfillment/versand-center#700, anzumelden>> oder eine <<fulfillment/versand-center#1400, Polling-Datei>> zu erzeugen, um diese einem Versanddienstleister zu übergeben. Je nach Versanddienstleister und Versanddienstleister-Software ist der eine oder andere Weg notwendig.

Außerdem erfahren Sie auf dieser Handbuchseite, wie Sie eine <<fulfillment/versand-center#1500, Auftragszusammenfassung>> der in plentymarkets <<fulfillment/versand-vorbereiten#2500, eingerichteten Versanddienstleister>> erzeugen, <<fulfillment/versand-center#1600, Retouren anmelden>> und <<fulfillment/versand-center#1900, Labels erzeugen>>.

[#100]
== Versandauftrag suchen

Wenn Sie das Versand-Center öffnen, wird das Tab *Suche* automatisch geöffnet. Für die Suche von Versandaufträgen stehen Ihnen verschiedene Filter zur Verfügung, die im Folgenden beschrieben sind.

[.instruction]
Versandauftrag suchen:

. Öffnen Sie das Menü *Aufträge » Versand-Center*.
. Wählen Sie die Filter. Beachten Sie dazu die Erläuterungen in <<tabelle-versandauftrag-suchen>>.
. Klicken Sie auf die Lupe, um die Suche auszuführen. +
→ Die Ergebnisse werden anhand der gewählten Filter aufgelistet.

[[tabelle-versandauftrag-suchen]]
.Filteroptionen zur Suche im Versand-Center
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Auftrags-ID*
|Auftrags-ID eingeben, um Versandaufträge anhand der ID zu suchen. Mehrere IDs durch Komma getrennt eingeben.

|*Kunden-ID*
|Kunden-ID eingeben, um Versandaufträge anhand der Kunden-ID zu suchen.

|*Versandstatus*
|Versandstatus wählen, um nur Versandaufträge in diesem Status zu suchen.

|*Versanddienstleister*
|Versanddienstleister wählen, um Versandaufträge dieses Dienstleisters zu suchen.

|*Versandprofil*
|Versandprofil wählen, um nur Versandaufträge mit diesem Profil zu suchen.

|*pro Seite*
|Wählen, wie viele gefundene Versandaufträge pro Seite angezeigt werden sollen.

|*Auftragsstatus*
|Auftragsstatus wählen, um nur Aufträge in diesem Status zu suchen. +

|*Eigner*
|Eigner wählen, um nur Aufträge zu suchen, für die der Eigner verantwortlich ist.

|*Mandant (Shop)*
|Mandant (Shop) wählen, um nur die Versandaufträge eines Shops zu suchen.

|*Lager*
|Lager wählen, um nur Versandaufträge dieses Lagers zu suchen.

|*Zahlungsart*
|Zahlungsart wählen, um nur Versandaufträge zu suchen, die mit dieser Zahlungsart bezahlt wurden.
|====

Nachdem Sie die gesuchten Versandaufträge gefunden haben, können Sie diese bearbeiten oder beim Versanddienstleister anmelden. Wie Sie Versandaufträge bearbeiten, wird im Folgenden beschrieben. Wie Sie Versandaufträge anmelden, wird in den Kapiteln <<fulfillment/versand-center#700, Versandauftrag anmelden>> und <<fulfillment/versand-center#1400, Polling-Datei erzeugen>> auf dieser Handbuchseite beschrieben.

[#200]
== Versandpaket im offenen Versandauftrag bearbeiten

In einem offenen Versandauftrag können Sie Versandpakete bearbeiten, hinzufügen oder entfernen. Die Kundendaten des Empfängers bearbeiten Sie im Menü <<crm/kontakte-verwalten#300, CRM » Kontakte>>. Wenn Sie im Versandauftrag auf die ID des Kunden klicken, wird der Kundendatensatz geöffnet.

[TIP]
.Retourenetiketten im Versandauftrag
====
Im Tab *Retourenetiketten* eines Versandauftrages werden Retourenetiketten angezeigt und Aufträge des Typs Retoure mit den angemeldeten Retouren verknüpft. Eine Retoure wird im Normalfall erst nach dem Versand angelegt, weshalb bei einem offenen, nicht angemeldeten Auftrag das Tab leer ist.
====

[#300]
=== Versandpaket bearbeiten

Gehen Sie wie im Folgenden beschrieben vor, um ein Versandpaket zu bearbeiten. Die Parameter, wie das Gewicht und Volumen, werden aus den Artikeldaten ermittelt. Prüfen Sie daher die Angaben der Versandpakete und nehmen Sie ggf. Korrekturen vor.

[.instruction]
Versandpaket bearbeiten:

. Öffnen Sie das Menü *Aufträge » Versand-Center*.
. Wählen Sie die Suchkriterien. Beachten Sie dazu die Informationen in Kapitel <<fulfillment/versand-center#100, Versandauftrag suchen>>.
. Klicken Sie auf die Lupe. +
→ Die Versandaufträge, die mit den von Ihnen gewählten Suchkriterien übereinstimmen, werden angezeigt.
. Klappen Sie den Versandauftrag auf.
. Klicken Sie im Tab *Versandpakete* auf den Stift, um den Versandauftrag zu bearbeiten.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandpaket-bearbeiten>>.
. *Speichern* Sie die Einstellungen.

[[tabelle-versandpaket-bearbeiten]]
.Versandpaket bearbeiten
[cols="1,3"]
|====
|Einstellung |Erläuterung

|*Versandpaket*
|Versandpaket wählen, um dem Versandauftrag eine Paketgröße zuzuordnen. +
Wenn noch keine Versandpakete im Menü *Aufträge » Versand » Versandpakete* angelegt sind, werden den Versandaufträgen Standardpakete zugeordnet. +
*_Wichtig:_* Die Anzahl der Versandpakete im Menü *Aufträge » Aufträge bearbeiten » Auftrag öffnen » Tab: Einstellungen* hat keinen Einfluss auf die hier hinterlegten Pakete und wird bei Änderungen nicht angepasst. Daher die Anzahl der Pakete ausschließlich im Versand-Center ändern.

|*Gewicht*
|Gewicht des Versandpakets eingeben. +
Wenn am Artikel ein Gewicht gespeichert ist, wird das Gewicht in den Versandauftrag übernommen. Wenn kein Gewicht am Artikel gespeichert ist, wird standardmäßig 100 g eingetragen. Wenn der Artikel aus mehreren Packstücken besteht, wird das Gewicht auf die Anzahl der Packstücke aufgeteilt.

|*Packstückart*
|Packstückart nachträglich wählen. +
Wenn am Artikel eine Packstückart gespeichert ist, wird diese hier angezeigt.

|*Volumen*
|Volumen nachträglich eingeben. +
Wenn am Artikel die Länge, Breite und Höhe gespeichert sind, wird das Volumen aus diesen Werten berechnet.
|====

[#400]
=== Versandpaket hinzufügen

Gehen Sie wie im Folgenden beschrieben vor, um ein Versandpaket hinzuzufügen.

[.instruction]
Versandpaket hinzufügen:

. Öffnen Sie das Menü *Aufträge » Versand-Center » Tab: Suche*.
. Wählen Sie die Suchkriterien. Beachten Sie dazu die Informationen in Kapitel <<fulfillment/versand-center#100, Versandauftrag suchen>>.
. Klicken Sie auf die Lupe. +
→ Die Versandaufträge, die mit den von Ihnen gewählten Suchkriterien übereinstimmen, werden angezeigt.
. Klappen Sie den Versandauftrag auf.
. Wechseln Sie in das Tab *Hinzufügen*.
. Nehmen Sie die Einstellungen vor. Beachten Sie dazu die Erläuterungen in <<tabelle-versandpaket-bearbeiten>>.
. *Speichern* Sie die Einstellungen. +
→ Das Versandpaket wird hinzugefügt und das Tab *Versandpaket* geöffnet.

[#500]
=== Versandpaket entfernen

Gehen Sie wie im Folgenden beschrieben vor, um ein Versandpaket zu entfernen.

[.instruction]
Versandpaket entfernen:

. Öffnen Sie das Menü *Aufträge » Versand-Center » Tab: Suche*.
. Wählen Sie die Suchkriterien. Beachten Sie dazu die Informationen in Kapitel <<fulfillment/versand-center#100, Versandauftrag suchen>>.
. Klicken Sie auf die Lupe. +
→ Die Versandaufträge, die mit den von Ihnen gewählten Suchkriterien übereinstimmen, werden angezeigt.
. Klappen Sie den Versandauftrag auf.
. Klicken Sie im Tab *Versandpakete* auf *Löschen*. +
→ Das Versandpaket wird gelöscht.
. *Speichern* Sie die Einstellungen.

[#600]
== Aufträge in Lieferaufträge splitten

Sie haben die Möglichkeit festzulegen, nach welchen Kriterien Aufträge in Lieferaufträge gesplittet werden sollen. Zur Auswahl stehen die Optionen *Lager*, *Versandprofil*, *Lager und Versandprofil* und *Lager- und Nettowarenbestand*.


Weitere Informationen finden Sie im Bereich <<auftraege#, Aufträge>>.

[#700]
== Versandauftrag anmelden

Im Menü *Aufträge » Versand-Center » Tab: Anmelden* melden Sie Ihre Aufträge bei einem Versanddienstleister an und übertragen diese gleichzeitig an den Dienstleister. Voraussetzung für die Anmeldung ist, dass Sie zuvor im Tab *Suche* <<fulfillment/versand-center#100, Aufträge gesucht>> haben, die jetzt hier angezeigt werden. Sie haben z.B. die Möglichkeit, mit den Filtereinstellungen in der Suche des Versand-Centers nur Aufträge für einen oder für alle Versanddienstleister anzuzeigen. Bei der Anmeldung erhalten Sie sowohl im Erfolgsfall als auch im Fehlerfall eine Meldung vom Versanddienstleister.

[IMPORTANT]
.Sendungsnummer zu Hermes ProfiPaketService übertragen
====
Wenn Sie Versandaufträge bei Hermes ProfiPaketService anmelden und die Sendungsnummern übertragen möchten, müssen Sie die Option *Etiketten anfordern* aktivieren.
====

Im Folgenden wird beispielhaft die Anmeldung von Aufträgen bei dem Versanddienstleister *DHL Freight* beschrieben.

[.instruction]
Versandauftrag bei DHL Freight anmelden:

. Öffnen Sie das Menü *Aufträge » Versand-Center*.
. Wählen Sie aus der Dropdown-Liste *Versandstatus* die Option *offen*.
. Wählen Sie aus der Dropdown-Liste *Versanddienstleister* die Option *DHL*.
. Klicken Sie auf die Lupe. +
→ Die offenen Versandaufträge für DHL werden angezeigt.
. Wechseln Sie in das Tab *Anmelden*.
. Wählen Sie aus der Dropdown-Liste *Versanddienstleister* die Option *DHL Freight* aus.
. Wählen Sie aus der Dropdown-Liste *Ändere Auftragsstatus* den Auftragsstatus, den die Aufträge nach erfolgreicher Anmeldung erhalten sollen.  +
→ Diese Funktion kann mit einer <<automatisierung/ereignisaktionen#, Ereignisaktion>>, die z.B. automatisch den Warenausgang bucht, kombiniert werden.
. Aktivieren Sie die Aufträge, die Sie bei DHL Freight anmelden möchten.
. Klicken Sie auf *Anmelden*, um die Aufträge zu übertragen.

Mit der Option *Alle auswählen* werden alle Aufträge der aktuellen Seite ausgewählt.

[TIP]
.Zusatzoptionen bei manchen Versanddienstleistern verfügbar
====
Auf der rechten Seite im Tab *Anmelden* werden abhängig vom Dienstleister zusätzliche Optionen angezeigt. Die meisten Versanddienstleister haben keine Zusatzoptionen, daher bleibt die rechte Seite leer. Die Zusatzoptionen ermöglichen es, das Versandprofil für ausgewählte Aufträge nachträglich zu ändern sowie das Versanddatum vor- oder zurückzudatieren.
====

Beachten Sie auch das Kapitel <<fulfillment/versand-center#2000, Mögliche Fehlerquellen beim Anmelden des Versandauftrags>> auf dieser Handbuchseite.

[#800]
== Angemeldeten Versandauftrag bearbeiten

Wenn Sie einen Versandauftrag bei einem Versanddienstleister anmelden, wird der Versanddienstleister in Klammern hinter dem Versandstatus *angemeldet* eingetragen, z.B. *angemeldet (DHL Intraship/Versenden)*.

Angemeldete Versandaufträge erhalten eine Paketnummer sowie meist eine Transaktionsnummer des Versanddienstleisters. Außerdem steht eine Datei mit dem Versandlabel zur Verfügung, sodass Sie das Label drucken können. Die Versandkosten werden ebenfalls angezeigt, wenn der Versanddienstleister diese Funktion unterstützt. Einige Bearbeitungsmöglichkeiten werden je nach Versanddienstleister angezeigt, z.B. die Tabs *Stornierung* und *Zurücksetzen* bei DHL Intraship/Versenden. Es können auch andere oder weitere Tabs angezeigt werden.

[WARNING]
.Versandauftrag stornieren vs. Versandauftrag zurücksetzen
====
Wenn Sie einen Versandauftrag stornieren, wird die Anmeldung in plentymarkets und auch beim Versanddienstleister zurückgenommen, sodass der Auftrag nicht abgeholt wird.

Wenn Sie einen Auftrag zurücksetzen, ist er in plentymarkets wieder als offener Auftrag verfügbar, aber beim Versanddienstleister weiterhin angemeldet und wird berechnet. Die Funktion *Zurücksetzen* setzt lediglich die Anmeldungen zurück. Der Versandauftrag wird nicht beim Dienstleister storniert. Daher sollten Sie den Auftrag generell stornieren.
====

[#900]
=== Angemeldeten Auftrag anzeigen

Im Folgenden wird beschrieben, wie Sie z.B. beim Dienstleister DHL Intraship/Versenden angemeldete Aufträge anzeigen.

[.instruction]
Angemeldeten Auftrag anzeigen:

. Öffnen Sie das Menü *Aufträge » Versand-Center » Tab: Suche*.
. Wählen Sie aus der Dropdown-Liste *Versandstatus* die Option *angemeldet DHL Intraship/Versenden*.
. Klicken Sie auf die Lupe. +
→ Die bei DHL Intraship/Versenden angemeldeten Aufträge werden angezeigt.

[#1000]
=== Paketnummer bearbeiten

Im Folgenden wird beschrieben, wie Sie die Paketnummer bearbeiten, wenn Sie den angemeldeten Auftrag bereits gefunden haben.

[.instruction]
Paketnummer bearbeiten:

. Klappen Sie im Menü *Aufträge » Versand-Center » Tab: Suche* den angemeldeten Auftrag auf. Wie Sie den angemeldeten Auftrag anzeigen, ist im Kapitel <<fulfillment/versand-center#900, Angemeldeten Auftrag anzeigen>> beschrieben.
. Klicken Sie auf den Stift im Tab *Versandpakete*. +
→ Die Paketnummer wird geöffnet.
. Geben Sie eine andere Paketnummer ein.
. *Speichern* Sie die Einstellungen.

Informationen zum Import von Paketnummern finden Sie im Kapitel <<fulfillment/dokumente-erzeugen#800, Paketnummern importieren>> auf der Handbuchseite <<fulfillment/dokumente-erzeugen#, Dokumente erzeugen>>.

[#1100]
=== Versandauftrag stornieren

Wenn sich etwas an der Sendung geändert hat, z.B. ein Artikel hinzugefügt oder entnommen wurde, stornieren Sie den Versandauftrag. Der Auftrag kann danach erneut zum Versand angemeldet werden.

[.instruction]
Versandauftrag stornieren:

. Öffnen Sie das Menü *Aufträge » Versand-Center*.
. Suchen Sie den angemeldeten Versandauftrag.
. Klappen Sie den angemeldeten Versandauftrag auf.
. Wechseln Sie in das Tab *Stornierung*.
. Klicken Sie auf *Versand stornieren*.

[#1200]
=== Versandauftrag zurücksetzen

Die Funktion *Zurücksetzen* setzt lediglich die Anmeldung zurück. Der Versandauftrag wird nicht beim Dienstleister storniert. Stornieren Sie deshalb den Auftrag, wie im vorigen Kapitel beschrieben.

[.instruction]
Versandauftrag zurücksetzen:

. Öffnen Sie das Menü *Aufträge » Versand-Center*.
. Suchen Sie den Versandauftrag.
. Klappen Sie den Versandauftrag auf.
. Wechseln Sie in das Tab *Zurücksetzen*.
. Klicken Sie auf *Versand zurücksetzen*.

[#1300]
=== Versandlabel drucken

Das Versandlabel steht Ihnen im Menü *Aufträge » Versand-Center* im angemeldeten Versandauftrag zur Verfügung. Außerdem haben Sie im Versand-Center im Tab <<fulfillment/versand-center#1900, Label>> die Möglichkeit, die komplette Label-Anzahl sämtlicher Versandaufträge eines Dienstleisters in einer PDF-Datei zu generieren und auszudrucken.

[.instruction]
Versandlabel im Versandauftrag drucken:

. Öffnen Sie das Menü *Aufträge » Versand-Center » Tab: Suche*.
. Wählen Sie die Suchkriterien. Beachten Sie dazu die Informationen in Kapitel <<fulfillment/versand-center#100, Versandauftrag suchen>>.
. Klicken Sie auf die Lupe.
. Öffnen Sie den angemeldeten Versandauftrag.
. Klicken Sie im Tab *Übersicht* auf das PDF-Symbol. +
→ Das Versandlabel wird in einem separaten Fenster geöffnet und kann dann gedruckt werden.

[#1400]
== Polling-Datei erzeugen

Im Menü *Aufträge » Versand-Center » Tab: Polling* erzeugen Sie für die Software eines Versanddienstleisters eine Polling-Datei, die zuvor gewählte Aufträge enthält. Eine Polling-Datei wird benötigt, wenn keine direkte Schnittstelle zu der Software des Versanddienstleisters besteht und somit die Anmeldung des Versandauftrags nicht über das Tab *Anmelden* erfolgt. Die in plentymarkets erzeugte Polling-Datei ist im Regelfall eine CSV-Datei.

[.instruction]
Polling-Datei erzeugen:

. Öffnen Sie das Menü *Aufträge » Versand-Center*.
. Wählen Sie die Suchkriterien für den Auftrag. Beachten Sie dazu die Informationen in Kapitel <<fulfillment/versand-center#100, Versandauftrag suchen>>.
. Aktivieren Sie den Auftrag.
. Wechseln Sie in das Tab *Polling*.
. Wählen Sie den *Versanddienstleister*.
. Wählen Sie den *Auftragsstatus*, in den die Aufträge geändert werden sollen.
. Aktivieren Sie die Aufträge, die über den gewählten Versanddienstleister verschickt werden sollen.
. Klicken Sie auf *Anmelden*, um die Polling-Datei zu erzeugen. +
→ Die Polling-Datei wird erzeugt. Speichern Sie die Datei auf Ihrem Computer.

[IMPORTANT]
.DHL Easylog Kopfzeile
====
Wenn der Versanddienstleister *DHL Easylog* gewählt ist, steht die Option *Kopfzeile* zur Verfügung. Mit dieser Option wählen Sie, ob die Kopfzeile in der CSV-Datei angezeigt werden soll. Weitere Informationen dazu finden Sie auf der Handbuchseite <<fulfillment/versand-vorbereiten#, Versand vorbereiten>> im Kapitel <<fulfillment/versand-vorbereiten#2700, DHL Easylog>>.
====

[#1500]
== Auftragszusammenfassung erzeugen

Im Menü *Aufträge » Versand-Center » Tab: Zusammenfassung* erzeugen Sie eine Auftragszusammenfassung bzw. Tagesabschlussliste von in Ihrem plentymarkets System eingerichteten Versanddienstleistern.

[.instruction]
Auftragszusammenfassung erzeugen:

. Öffnen Sie das Menü *Aufträge » Versand-Center » Tab: Zusammenfassung*.
. Wählen Sie den Versanddienstleister für die Zusammenfassung aus der Dropdown-Liste. +
→ Falls vorhanden, werden weitere Optionen des Versanddienstleisters eingeblendet.
. Nehmen Sie Einstellungen für die Optionen vor.
. Klicken Sie auf *Ausführen*. +
→ Eine PDF-Datei wird erzeugt.

[TIP]
.Auftragszusammenfassung per elastischem Export exportieren
====
Als Alternative zur Auftragszusammenfassung eines Tages im Menü *Aufträge » Versand-Center » Tab: Zusammenfassung* können Sie einen <<daten/daten-exportieren/elastischer-export#, elastischen Export>> durchführen. Erstellen Sie dazu im Vorfeld ein Exportformat mit dem <<daten/daten-exportieren/FormatDesigner#, FormatDesigner>>.
====

[#1600]
== Retourenetikett abrufen

Im Menü *Aufträge » Versand-Center » Tab: Retoure* melden Sie Retouren bei einem Versanddienstleister an. Nach dem Anmelden der Retoure sind die Etiketten als PDF-Dateien verfügbar. Sie melden eine Retoure entweder über den Hauptauftrag oder über die Retoure an.

Um Retourenetiketten abzurufen, melden Sie Retouren im Versand-Center bei einem Versanddienstleister an.

[#1700]
=== Retourenetikett über Hauptauftrag abrufen

Wie Sie ein Retourenetikett im Hauptauftrag abrufen, wird im Folgenden beschrieben. Je nachdem, ob Sie im Menü *Aufträge* bereits eine Retoure für den Auftrag angelegt haben oder nicht, erfolgt die Zuweisung eines Auftrags des Typs *Retoure* zur angemeldeten Retoure leicht unterschiedlich. Rufen Sie zunächst das Etikett ab und nehmen Sie anschließend die Zuordnung zum Auftrag des Typs *Retoure* vor.

[.instruction]
Retourenetikett über Hauptauftrag abrufen:

. Öffnen Sie das Menü *Aufträge » Versand-Center » Tab: Suche*.
. Wählen Sie die Suchkriterien für den Auftrag. Beachten Sie dazu die Informationen in Kapitel <<fulfillment/versand-center#100, Versandauftrag suchen>>.
. Wechseln Sie in das Tab *Retoure*.
. Aktivieren Sie den Auftrag.
. Wählen Sie den *Retouren-Dienstleister*.
. Klicken Sie auf *Anmelden*, um die Retoure anzumelden. +
→ Das Etikett ist über das PDF-Symbol als PDF-Datei verfügbar.

Wenn Sie bereits einen Retourenauftrag im Menü *Aufträge* angelegt haben, dann weisen Sie diese Retoure durch Wahl der *Retouren-ID* dem Etikett zu.

Wenn Sie noch keinen Retourenauftrag im Menü *Aufträge* angelegt haben, öffnen Sie den Hauptauftrag und legen eine Retoure an. Beim nachträglichen Anlegen eines Auftrags des Typs *Retoure* wird der Retourenauftrag im Versandauftrag automatisch dem Retourenetikett zugewiesen.

[#1800]
=== Retourenetikett über Retoure abrufen

Wenn Sie bereits eine Retoure im Menü *Aufträge* angelegt haben, kann das Retourenetikett auch direkt über die Retoure abgerufen werden. Dazu benötigen Sie die ID der Retoure, denn Retouren werden im Versand-Center nur bei Angabe der Retouren-ID gefunden.

[.instruction]
Retourenetikett über Retoure abrufen:

. Öffnen Sie das Menü *Aufträge » Versand-Center*. +
→ Das Tab *Suche* wird geöffnet.
. Geben Sie die ID der Retoure in den Suchfilter *Auftrags-ID* ein.
. Klicken Sie auf die Lupe.
. Wechseln Sie in das Tab *Retoure*.
. Aktivieren Sie die Retoure.
. Wählen Sie den *Retouren-Dienstleister*.
. Klicken Sie auf *Anmelden*.
. Klappen Sie den Versandauftrag auf. +
→ Das Etikett ist im Tab *Retourenetiketten* über das PDF-Symbol als PDF-Datei verfügbar.

Die Etiketten können Sie dem Endkunden im Mein-Konto-Bereich des Webshops zum Download zur Verfügung stellen. Beachten Sie dazu auch das Kapitel <<fulfillment/versand-vorbereiten#3200, DHL Retoure Online>> auf der Handbuchseite <<fulfillment/versand-vorbereiten#, Versand vorbereiten>>.

Bei Retouren, die Sie hier im Tab *Retoure* des *Versand-Centers* anmelden und dann das Retourenetikett erhalten, wurde das Paket schon ausgeliefert und der Kunde hat die Ware erhalten. Bei <<fulfillment/versand-vorbereiten#3100, DHL Retoure Beileger>> legen Sie Paketen schon vor der Lieferung an den Kunden Retourenetiketten bei. Diese Beilegeretiketten werden ebenfalls im Tab *Retourenetiketten* des Versandauftrages angezeigt.

[#1900]
== Label erzeugen

Im Menü *Aufträge » Versand-Center » Tab: Label* haben Sie die Möglichkeit, für Ihre angemeldeten Aufträge Versandlabels zu erzeugen und diese dann anschließend zu drucken. Die Labels werden in einer PDF-Datei zum Download zur Verfügung gestellt. Pro Versanddienstleister wird eine PDF-Datei erzeugt.

[.instruction]
Labels erzeugen:

. Öffnen Sie das Menü *Aufträge » Versand-Center*.
. Suchen Sie anhand der Filter die Aufträge, für die Sie ein Sammel-PDF der Labels generieren möchten.
. Aktivieren Sie die Aufträge.
. Wechseln Sie ins Tab *Label*.
. Klicken Sie auf *Generieren*. +
→ Sie erhalten die Labels als PDF-Datei für den Download und können die Datei anschließend drucken.

[#2000]
== Mögliche Fehlerquellen beim Anmelden des Versandauftrags

In diesem Kapitel werden mögliche Fehlerquellen genannt, durch die Daten zum Versanddienstleister nicht übertragen werden. Wenn ein Auftrag nicht angemeldet werden kann, wird eine Fehlermeldung angezeigt.

Beachten Sie bei der Fehlersuche auch das Menü *Daten » API-Log » Tab: Versand-Center API-Log*. Die darin verfügbaren Einträge bleiben 7 Tage lang gespeichert.

[#2100]
=== Zeichensatz

Einige Versandschnittstellen (APIs) erlauben nur lateinische Zeichensätze (ISO-8859-X) jedoch keinen Unicode. Daher sollten Lieferanschriften keine Unicode-Zeichen enthalten. So sind mit DHL Intraship/Versenden z.B. keine Anmeldungen möglich, wenn die Anschrift in griechischen Buchstaben gespeichert ist.

[#2200]
=== Adresszusatz

Manche Versanddienstleister verarbeiten die Angabe *Adresszusatz* aus der Lieferanschrift nicht. In seltenen Fällen kann deshalb eine Sendung nicht zugestellt werden. +
Zu folgenden Versanddienstleistern wird derzeit der Adresszusatz nicht übermittelt:

* DHL Freight
* DHL Supply Chain
* Swiss Post

Achten Sie darauf, ob der Adresszusatz korrekt zu Ihrem Versanddienstleister übertragen wird. Wenn der Adresszusatz nicht übertragen wird, passen Sie Ihr Webshop-Design so an, dass in Abhängigkeit des gewählten Versanddienstleisters der Adresszusatz im Webshop ein- oder ausgeblendet oder ein Hinweis für den Kunden eingeblendet wird.

[#2300]
=== Versandprofil

Fehlermeldung: Code 1: Der Vorgang konnte nicht korrekt durchgeführt werden. Bitte Dateneingabe prüfen. Es wurde ein ungültiger Parameterwert übergeben: DHLFreightDataSet_ShippingInformation.

Lösung: Das Versandprofil wurde nicht korrekt eingerichtet oder es wurde ein Versanddienstleister, der nicht zum Versandpofil passt, gewählt.

[#2400]
=== Versandpakete

Es ist nicht möglich, Pakete im Auftrag im Tab <<auftraege/auftraege-verwalten#1540, Einstellungen>> hinzuzufügen. Wenn Sie weitere Pakete zu einen Auftrag hinzufügen oder die Anzahl ändern möchten, öffnen Sie den Auftrag im Versand-Center und bearbeiten Sie diesen im Tab <<fulfillment/versand-center#400, Hinzufügen>>.
